### ISSUE TITLE
Unable to instantiate decoder 'CIPMP3Decoder'

### ISSUE THREAD

**Issue by IlyaMyasoedov** [google/ExoPlayer#1000]
Hello...
I have tried to use HLS protocol to stream .mp3 audio files, but i get the exception :"Unable to instantiate decoder 'CIPMP3Decoder'". 
My device - ZTE Geek, OS Android 4.2.2
The log is attached in .txt file.
[Log.txt](https://github.com/google/ExoPlayer/files/47083/Log.txt)

**Comment by Ood-Tsen** [comment]
Hi @IlyaMyasoedov , try software decoder ?

**Comment by IlyaMyasoedov** [comment]
@Ood-Tsen , I fixed this issue when added one line to the source code (MediaCodecUtil.java):
<code>
if (Util.SDK_INT == 16
        && "OMX.qcom.audio.decoder.mp3".equals(name)
        && ("dlxu".equals(Util.DEVICE) // HTC Butterfly
            || "protou".equals(Util.DEVICE) // HTC Desire X
            || "C6602".equals(Util.DEVICE) // Sony Xperia Z
            || "C6603".equals(Util.DEVICE)
            || "C6606".equals(Util.DEVICE)
            || "C6616".equals(Util.DEVICE)
            || "L36h".equals(Util.DEVICE)
            || "SO-02E".equals(Util.DEVICE)
            || "CIPMP3Decoder".equals(Util.DEVICE))) {
      return false;
    }
</code>

**Comment by IlyaMyasoedov** [comment]
@Ood-Tsen. I wrote the wrong device by mistake

**Comment by ojw28** [comment]
We should blacklist this like we blacklisted CIPAACDecoder.

**Comment by IlyaMyasoedov** [comment]
@ojw28 Is this issue will be repaired in the next release?

**Comment by Ood-Tsen** [comment]
Hi @IlyaMyasoedov , you can do it by youself .

Just add CIPMP3Decoderin the list.

https://github.com/google/ExoPlayer/blob/dev/library/src/main/java/com/google/android/exoplayer/MediaCodecUtil.java#L180
