### ISSUE TITLE
Can we download separate audio and video link in a one video file?

### ISSUE THREAD

**Issue by zenom141** [google/ExoPlayer#10009]
Hello, 

I have separate links for audio and video files. I can play both audio and video by merging source. But how to download video and audio links in one file using exo? Can this be possible via exo or i have to use ffmpeg for merging? 

thanks

**Comment by marcbaechinger** [comment]
If I understand correctly, and the question is whether the download components of the library (`DownloadService` et al.) can be used to download a `MergingMediaSource`, then I think the answer is no, I'm afraid. 

You would probably have to transcode the two streams into a single container (using ffmpeg or a similar tool) or into an adaptive stream with a playlist/manifest. The `Downloaders` provided by the library expect a `MediaItem` that can be converted in either a `ProgressiveMediaSource`, `DashMediaSource`, `HlsMediaSource` or "SmoothStreamingMediaSource`.

It's probably possible to download both streams separately and then merged the already downloaded stream in a `MergingMediaSource`. The `CachingDataSource` would then find the data of both stream in the cache and deliver it back. So if you download the media programmatically (as opposed to adding a download to the `DownloadService`), this could work but this is not an out-of-the-box solution but needs some investigation and research on your side when giving it a try.

Please let me know whether I have understood the question correctly.

**Comment by zenom141** [comment]
Hello, yes u got it right. I have used ffmpeg to merge audio and video link. Thank you.
