### ISSUE TITLE
SingleSampleMediaSource Format.Builder bug

### ISSUE THREAD

**Issue by dejanm** [google/ExoPlayer#10016]
SetId for Format Builder is used twice, meaning subtitleConfiguration.id is the only valid id that will be used.
Please resolve the problem in the following code:

format =
        new Format.Builder()
            **.setId(trackId)**
            .setSampleMimeType(firstNonNull(subtitleConfiguration.mimeType, MimeTypes.TEXT_UNKNOWN))
            .setLanguage(subtitleConfiguration.language)
            .setSelectionFlags(subtitleConfiguration.selectionFlags)
            .setRoleFlags(subtitleConfiguration.roleFlags)
            .setLabel(subtitleConfiguration.label)
            **.setId(subtitleConfiguration.id)**
            .build();
            
I believe that trackId is not needed anymore.

- ExoPlayer version number 2.17.0
- Android version 12
- Android device Samsung s21

**Comment by icbaker** [comment]
Thanks for flagging this - I'll deprecate `SingleSampleMediaSource.Factory#setTrackId` but change the logic in the constructor to still use its value if `SubtitleConfiguration#id` is `null`.
