### ISSUE TITLE
TsExtractor works with all the program_map_PIDs in PAT as a PMT's PID

### ISSUE THREAD

**Issue by Avetri** [google/ExoPlayer#1001]
TsExtractor works with all the program_map_PIDs in PAT as a PMT's PID. But:
1. PIDs from 0x00 to 0x1F are reserved for another DVB SI tables.
2. Not only program_map_PIDs can be in PAT. 0x10 (NIT with program number 0x00) there is in PAT according to standards. At least one other PID can be there also.

**Comment by ojw28** [comment]
Feel free to send a pull request if you have a good fix for this. Thanks!

**Comment by ojw28** [comment]
@Avetri - What specification (including version + part) are you looking in to see that PIDs from 0x00 to 0x1F are reserved? I can't see this stated anywhere in ISO 13818-1:2000. Are you planning to send a pull request to fix the issue?

**Comment by ojw28** [comment]
The change above avoid treating network_PID as thought it's a program_map_PID. I'm not sure about the first point in this issue, however.

**Comment by ojw28** [comment]
Closing due to lack of update regarding the first point. The second point has been fixed.

**Comment by Avetri** [comment]
Thanks all the good people for the fix (program_number==0).
