### ISSUE TITLE
Http headers - multiple value for the same header

### ISSUE THREAD

**Issue by Xlcghs** [google/ExoPlayer#10013]
Hello,

I tried to add properties in the header of HTTP requests.
Do you have a way to add multiple values ​​for the same header ?
Example :
Header "Authorization" : value "value 1"
Header "Authorization" : value "value 2"

In the ExoPlayer code, you use "Map" so you can only have one value associated with a key (header). 
Should the ExoPlayer code be changed to take this use case into account (MultiMap instead of Map for example) ?

BR

**Comment by marcbaechinger** [comment]
Thanks for reporting!

I don't think we necessarily need a change in ExoPlayer for this. If I interpret the HTTP spec correctly you should be able to combine the values into a single field:

https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2

```
Multiple message-header fields with the same field-name MAY be present in a message if and only if 
the entire field-value for that header field is defined as a comma-separated list [i.e., #(values)]. It 
MUST be possible to combine the multiple header fields into one "field-name: field-value" pair, without 
changing the semantics of the message, by appending each subsequent field-value to the first, each 
separated by a comma. The order in which header fields with the same field-name are received is 
therefore significant to the interpretation of the combined field value, and thus a proxy MUST NOT 
change the order of these field values when a message is forwarded.
```

So in case a header is defined by the spec as a `comma-separated` list of values,  you can express what you want in a single header field by concatenating the values.

An example of such a header is [accept-language](https://httpwg.org/specs/rfc7231.html#header.accept-language)

Authorization doesn't seem to be a comma separated list header though: 
https://httpwg.org/specs/rfc7235.html#header.authorization

Please let me know if you think differently.

**Comment by Xlcghs** [comment]
Thank you it's very clear
