### ISSUE TITLE
Disable downmixing?

### ISSUE THREAD

**Issue by oggew2** [google/ExoPlayer#10015]
Exoplayer seems to be downmixing audio. Right now I am using JustPlayer (https://github.com/moneytoo/Player#readme) with a receiver capable of receiving EC3 and DTS (5.1 system). However, if any of those formats are played, the receiver only sees it as a "normal" Dobly digital on EC3 and shows that the stream only contains 2/0/.0. I have also tested the same media using kodi with forced passthrough and the receiver gets the 2/2/.1 signal and uses the surround.

I'm not sure if exo downmixes the content or if it's not using passthrough, but is there a way to force it to use passthrough and not meddle with the audio files?

**Comment by krocard** [comment]
Do you observe the same behavior with ExoPlayer's demo app (it could be a JustPlayer bug)? https://exoplayer.dev/demo-application.html
