### ISSUE TITLE
Difference between SingleSampleMediaSource and ProgressiveMediaSource

### ISSUE THREAD

**Issue by yuzhidi** [google/ExoPlayer#10034]
Hi,
although [SingleSampleMediaSource](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/source/SingleSampleMediaSource.java)  annotate
```
Loads data at a given Uri as a single sample belonging to a single MediaPeriod.
```
[ProgressiveMediaSource](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/source/ProgressiveMediaSource.java) annotate
```
Provides one period that loads data from a {@link Uri} and extracted using an {@link Extractor}.
```
seems `ProgressiveMediaSource` can get stream format by `Extractor.sniff`

is there any more brief introduction about the two MediaSource!

thx!

**Comment by ojw28** [comment]
* `SingleSampleMediaSource` loads data at the Uri as a single media sample, as per the documentation you've found. It's typically used for side-loaded subtitle files.
* `ProgressiveMediaSource` will parse multiple media samples out of a media container format (e.g., individual audio/video samples from an MP4 file).

We do have a plan to move side-loaded subtitles files to also use `ProgressiveMediaSource`. The way they're handled is a bit of an anomaly at the moment, and it causes some issues when used together with certain features (e.g., clipping). Once we've done this `SingleSampleMediaSource` might be removed completely.
