### ISSUE TITLE
Remove final modifier from LeanbackPlayerAdapter class

### ISSUE THREAD

**Issue by ppodgorski** [google/ExoPlayer#10036]
We want to apply some minor changes in one of LeanbackPlayerAdapter methods. Is there a possibility to remove a final modifier from LeanbackPlayerAdapter class so that we could subclass it?

**Comment by ojw28** [comment]
Making the class non-final effectively adds a bunch of extension points to our API surface. We don't want to add to our API surface without understanding why we're doing so. It may also be possible to do what you want with APIs that already exist.

Please could you provide details of the specific thing you're trying to do, and how you'd propose to implement it if this class were non-final? We can then assess whether that's the correct and best way to support your request. Thanks!

**Comment by ppodgorski** [comment]
Thanks for your reply! We want to override getDuration() method into something like this:
```
@Override
public long getDuration() {
    Timeline timeline = player.getCurrentTimeline();
    Timeline.Window window = timeline.getWindow(player.getCurrentWindowIndex(), new Timeline.Window());
    return window.defaultPositionUs;
}
```

That is because we are experiencing long buffering on our live streams when user scrub to the end of the stream. I've sent url to test content to dev.exoplayer@gmail.com, so you will be able to reproduce the problem.
Reproduction steps:
1. Switch "uri" in media.exolist.json to our url and play
2. Scrub to the end of the video

Limiting duration to window.defaultPositionUs is solving our problem.

**Comment by ojw28** [comment]
You can probably achieve the same thing using `ForwardingPlayer` to change the duration:

```
Player durationOverridePlayer = new ForwardingPlayer(player) {
  @Override
  public long getDuration() {
    Timeline timeline = getCurrentTimeline();
    Timeline.Window window = timeline.getWindow(getCurrentWindowIndex(), new Timeline.Window());
    return window.defaultPositionUs;
  }
};

LeanbackPlayerAdapter adapter = new LeanbackPlayerAdapter(context, durationOverridePlayer, updatePeriodMs);
```
