### ISSUE TITLE
H96 Max + Flutter: Green bar down side of player

### ISSUE THREAD

**Issue by ZoubairDaddow** [google/ExoPlayer#10031]
Hello,
I use [better_player](https://pub.dev/packages/better_player) that depends on [exo_player](https://exoplayer.dev/) version 2.15.1 for android
and when try to use stream video with dimensions 1920 * 1080
the player display the stream as photo shown

![photo5848165472284031314](https://user-images.githubusercontent.com/32312290/157015888-8040830a-c5d9-4027-ab2a-f65e0c5ac552.jpg)

**Flutter doctor**
[√] Flutter (Channel stable, 2.10.2, on Microsoft Windows [Version 10.0.19042.1266], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Enterprise 2019 16.11.8) 
[√] Android Studio (version 2020.3)
[√] VS Code (version 1.65.0)      
[√] Connected device (4 available)
[√] HTTP Host Availability       

In addition this issue does not show on mobile devices , just on some tv boxes such as **H96 Max**
Model : H96_Max_V11
Android version : 11

**Comment by ojw28** [comment]
This is unlikely to be an ExoPlayer issue. It's likely to be a device specific issue, or an issue with `better_player`.

I suggest you build and install our [demo application](https://exoplayer.dev/demo-application.html) on the problematic device. If the issue reproduces in the demo app, the it's a device specific issue. If it does not, then it's probably an issue with `better_player`. Thanks!

**Comment by ZoubairDaddow** [comment]
Does exo_player have a plan to build package for flutter ?

**Comment by ojw28** [comment]
No, we don't have a plan to do this.
