### ISSUE TITLE
how to use pinch to zoom function in exoplayer 

### ISSUE THREAD

**Issue by Programmingtimes** [google/ExoPlayer#10043]
i have found a page which shares how to use pitch to zoom in exoplayer 
https://medium.com/agile-freaks/exoplayer-pinch-to-zoom-functionality-bae397471c37
but issue is coding is in kotlin but my app and i know only java so can someone here help to transalte the code to java so i can use it in my project 
basically i need to know how to use pinch to zoom fun in exoplayer but since its out of box question, I googled myself and found that solution but still its in kotlin language which i have zero knowledge.

**Comment by ojw28** [comment]
I will leave this open for a few weeks in case anyone wants to help, but since it's more just a request for help with your own application development, it's not within scope for what we have capacity to help with directly.
