### ISSUE TITLE
Sound Playing on headphones and not with speakers

### ISSUE THREAD

**Issue by diabloo** [google/ExoPlayer#1004]
hi ,
i came across a bug yesterday while testing my online streaming application , some link play well with headphones and when i try to play them with speakers  the sound i really low with a lot of interference 
``` http://tiziouzou.ice.infomaniak.ch/15.aac ```

in Logcat i get this when playing with speakers  : 
```
11-30 13:23:43.967 5661-5673/com.my.app V/AudioSystem: ioConfigChanged() new output samplingRate 48000, format 1 channel mask 0x3 frameCount 960 latency 50
11-30 13:23:43.967 5661-5672/com.my.app  V/AudioSystem: ioConfigChanged() event 0, ioHandle 2
11-30 13:23:43.967 5661-5672/com.my.app  V/AudioSystem: ioConfigChanged() new output samplingRate 48000, format 1 channel mask 0x3 frameCount 960 latency 160
11-30 13:23:49.387 5661-6962/com.my.app V/AudioTrack: NormalizerV2(session: 143): mNormalizerV2->process(framecount: 2049)
11-30 13:23:49.387 5661-6962/com.my.app  V/AudioTrack: NormalizerV2: channelCount = 2, mStreamType = 3, mFlags = 0
11-30 13:24:03.987 5661-6962/com.my.app  V/AudioTrack: NormalizerV2(session: 143): mNormalizerV2->process(framecount: 3073)
11-30 13:24:03.987 5661-6962/com.my.app  V/AudioTrack: NormalizerV2: channelCount = 2, mStreamType = 3, mFlags = 0
11-30 13:24:18.547 5661-6962/com.my.app V/AudioTrack: NormalizerV2(session: 143): mNormalizerV2->process(framecount: 4097)
11-30 13:24:18.547 5661-6962/com.my.app  V/AudioTrack: NormalizerV2: channelCount = 2, mStreamType = 3, mFlags = 0
```
i use : ExtractorSampleSource with MediaCodecAudioTrackRenderer

**Comment by ojw28** [comment]
What device/os-version is this happening on?

**Comment by diabloo** [comment]
miltiple divices : samsung GT-S5310 4.1.2 
LG G2 4.4.2 
LG G2 5.0.1

**Comment by ojw28** [comment]
This doesn't sound like an ExoPlayer issue, since we don't do anything special for headphone vs speaker output. It's up to the platform to send the audio to the correct output. We've also not received a single other report of this issue. Closing for now.
