### ISSUE TITLE
Fetch All bitrate mentioned in the HLS stream manifest

### ISSUE THREAD

**Issue by amitsamal** [google/ExoPlayer#1005]
Hi Team,

Does exoplayer has a given method which can be used to fetch all the bitrates which are mentioned in the HLS manifest from server and use it to switch to those bitrate in the player. 

Thanks 
Amit

**Comment by ojw28** [comment]
If you try the ExoPlayer [demo app](https://github.com/google/ExoPlayer/tree/release-v2/demo) you'll see there are "Video" and "Audio" buttons that you can press. Pressing them gives you a dialog listing the available streams and allowing the user to select which one(s) are used. So I'd suggest taking a look at the demo app code to see how to achieve this.
