### ISSUE TITLE
Change Media with TextTracks on ExoPlayer v2.17.0 and v2.17.1

### ISSUE THREAD

**Issue by GouravSna** [google/ExoPlayer#10055]
Hi,

ExoPlayer Version: v2.17.0 and 2.17.1 

I am having a single player instance, which I use to pass multiple medias. It helps me to do the change medias. I don't use ExoPlayer's Playlist feature.
On UI, I show a spinner having multiple test tracks including 'None'. None will disable the test tracks.

Let's suppose 1st media is playing back and it has 'None' and I disabled the text track's visibility. 
In the below code, what i do; i clear the selected indices which basically tells ExoPlayer not to display anything from that text group. Reference https://github.com/google/ExoPlayer/blob/8129675b065bc98330ec775fb7a538c139793070/library/common/src/main/java/com/google/android/exoplayer2/trackselection/TrackSelectionOverrides.java#L123

```java
//actually change track.
        TrackGroup trackGroup = mappedTrackInfo.getTrackGroups(rendererIndex).get(groupIndex);
        if (!selectedIndices.isEmpty()) {
            if (rendererIndex == TRACK_TYPE_TEXT && selectedIndices.get(0) == TRACK_DISABLED) {
                // Just clear the selected indices,
                // it will let exoplayer know that no tracks from trackGroup should be played
                selectedIndices.clear();
            }

            TrackSelectionOverrides.TrackSelectionOverride trackSelectionOverride = new TrackSelectionOverrides.TrackSelectionOverride(trackGroup, selectedIndices);

            TrackSelectionOverrides trackSelectionOverrides = trackSelectionOverridesBuilder
                    .setOverrideForType(trackSelectionOverride)
                    .build();

            parametersBuilder.setTrackSelectionOverrides(trackSelectionOverrides);
        } else {
            //clear all the selections if the override is null.
            trackSelectionOverridesBuilder.clearOverride(trackGroup);
        }
        selector.setParameters(parametersBuilder);
```

**Issue:** When i change the track (either same media or another one having text tracks), i see that for next track also text tracks are in the disabled state.
Ex: Here i tried same content.

'French' is the default language having selection flag = 5 . So for the first time, `trackSelected` is `true` and next time `trackSelected` is `false`. I think Exo is again retaining some info for the trackgroups. 

Screenshots:

<img width="918" alt="Screenshot 2022-03-11 at 1 58 03 PM" src="https://user-images.githubusercontent.com/38206744/157831018-7505e2c4-77c2-4611-b26b-ec5ced1ef2b8.png">
<img width="987" alt="Screenshot 2022-03-11 at 1 58 43 PM" src="https://user-images.githubusercontent.com/38206744/157831025-b8b3329a-24f4-4472-b7b5-3eaea34aae3b.png">

**PS:** Please update te ExoPlayer demo app for changing the tracks; it is still using the deprecated API `setSelectionOverride`

**Comment by ojw28** [comment]
Is the text `TrackGroup` in the second piece of media equal to the text `TrackGroup` in the first piece of media? If so then it's working as intended that the override would continue to apply. If you don't want the override to continue to apply, then you should update the parameters to get rid of it when you switch to playing the second piece of media.

Regarding the demo app, we are currently updating both the UI components and demo app to use the new track selection APIs (which, unfortunately, are changing a little again, since we didn't get everything just how we wanted it the first time).

**Comment by GouravSna** [comment]
**This is the first media, it has a default subtitle track,**

<img width="1069" alt="Screenshot 2022-03-14 at 11 09 45 AM" src="https://user-images.githubusercontent.com/38206744/158112382-22bbe91d-3ffb-41db-aa65-d6af12012078.png">

**After change media, for the next media (Different media),**

This also has a default subtitle track. "But **_I have not selected 'NONE' track in this case_**. So you can see it has a default text track. 4th index is the default text track. 

<img width="1193" alt="Screenshot 2022-03-14 at 11 29 09 AM" src="https://user-images.githubusercontent.com/38206744/158113914-5edd24c5-94a7-4a67-8617-a4024f2a338e.png">


**Issue case:**

Let's suppose, I **_selected 'None' for text track for the first media_** then please check the following screen shot which is having different track groups for the next media but it does not have the default text track as 'Selected'.

<img width="1118" alt="Screenshot 2022-03-14 at 11 30 21 AM" src="https://user-images.githubusercontent.com/38206744/158113960-9f77290e-1f95-4ce0-a6af-d47e6d7a4c0f.png">

**Comment by ojw28** [comment]
I don't think it's relevant, but in your code I don't think the `           trackSelectionOverridesBuilder.clearOverride(trackGroup);` line is doing anything, because you don't do anything with the builder.

That aside, it's very hard to help based on IDE screenshots. If you'd like us to take a look then please could you provide two pieces of media that can be used to reproduce the issue?

**Comment by GouravSna** [comment]
> I don't think it's relevant, but in your code I don't think the ` trackSelectionOverridesBuilder.clearOverride(trackGroup);` line is doing anything, because you don't do anything with the builder.

Sure Noted. Will take a look. thanks


> That aside, it's very hard to help based on IDE screenshots. If you'd like us to take a look then please could you provide two pieces of media that can be used to reproduce the issue?

Media 1 
 http://cdnapi.kaltura.com/p/243342/sp/24334200/playManifest/entryId/0_uka1msg4/flavorIds/1_vqhfu6uy,1_80sohj7p/format/applehttp/protocol/http/a.m3u8

Media 2
http://d3rlna7iyyu8wu.cloudfront.net/skip_armstrong/skip_armstrong_multi_language_subs.m3u

**Comment by ojw28** [comment]
The second link returns a 403 for me. Please could you take a bit of time and provide some instructions and media that definitely work? Each time we look at an issue and don't have the information we need, that's time we could be spending more efficiently working on something else. Thanks!

**Comment by GouravSna** [comment]
> Media 1 http://cdnapi.kaltura.com/p/243342/sp/24334200/playManifest/entryId/0_uka1msg4/flavorIds/1_vqhfu6uy,1_80sohj7p/format/applehttp/protocol/http/a.m3u8
> 
> Media 2 http://d3rlna7iyyu8wu.cloudfront.net/skip_armstrong/skip_armstrong_multi_language_subs.m3u

In the 2nd media, in extension '8' is missing of m3u8. Sorry for that.

http://d3rlna7iyyu8wu.cloudfront.net/skip_armstrong/skip_armstrong_multi_language_subs.m3u8

I checked in demo app under playlist,

```java
{
        "name": "Cats -> Dogs",
        "playlist": [
          {
            "uri": "http://cdnapi.kaltura.com/p/243342/sp/24334200/playManifest/entryId/0_uka1msg4/flavorIds/1_vqhfu6uy,1_80sohj7p/format/applehttp/protocol/http/a.m3u8"
          },
          {
            "uri": "http://d3rlna7iyyu8wu.cloudfront.net/skip_armstrong/skip_armstrong_multi_language_subs.m3u8"
          }
        ]
      }
```

1. Selected 'None' text tracks for the 1st media.
2. Clicked on the next from UI button.
3. For the 2nd media, No text track is visible however default text track is present in the next media.

-Thanks
5.

**Comment by ojw28** [comment]
```
1. Selected 'None' text tracks for the 1st media.
2. Clicked on the next from UI button.
3. For the 2nd media, No text track is visible however default text track is present in the next media.
```
In the demo app for current releases (e.g., 2.17), this is working as intended, because selecting "None" disables the renderer, and disabling the renderer is not tied to any specific `TrackGroups`.

I think your problem is probably to do with the way the new style selection overrides apply. Note that a new style override only specifies a single `TrackGroup`:
```
new TrackSelectionOverrides.TrackSelectionOverride(trackGroup, selectedIndices);
```
Note also that each of the text tracks is in its _own_ group, because they present different content. So for an override to apply to the second piece of media, it's only necessary that an equal `TrackGroup` is present to one you've set an override for in the first piece of media. This can be true even if the total number of available text tracks is different.

You need to make sure that when transitioning to the new piece of media, there aren't any overrides present that apply to it. For example, create a new and empty `TrackSelectionOverrides.Builder` and make sure to incorporate it into the `TrackSelectionParameters`. This may be somewhat related to my earlier point about the line of code that I don't think is doing anything.

**Comment by GouravSna** [comment]
Hi @ojw28 ,

I tried your suggestion to clear the overrides before loading the another media. However, I can see that `TrackSelectionParameters` does not have any overrides before loading the another media but still for the next media, I can see the same issue where the default track is not coming as 'Selected'.

This is how I am clearing the overrides,

```java
        player.setTrackSelectionParameters(player.getTrackSelectionParameters().buildUpon().setTrackSelectionOverrides(TrackSelectionOverrides.EMPTY).build());

```

I have applied your suggestion where you pointed that code is not doing anything. So new piece of code looks like this,

``` java
//actually change track.
        TrackGroup trackGroup = mappedTrackInfo.getTrackGroups(rendererIndex).get(groupIndex);
        if (!selectedIndices.isEmpty()) {
            if (rendererIndex == TRACK_TYPE_TEXT && selectedIndices.get(0) == TRACK_DISABLED) {
                // Just clear the selected indices,
                // it will let exoplayer know that no tracks from trackGroup should be played
                selectedIndices.clear();
            }

            TrackSelectionOverrides.TrackSelectionOverride trackSelectionOverride = new TrackSelectionOverrides.TrackSelectionOverride(trackGroup, selectedIndices);
            trackSelectionOverridesBuilder.setOverrideForType(trackSelectionOverride);
        } else {
            //clear all the selections if selectedIndices are empty.
            trackSelectionOverridesBuilder.clearOverride(trackGroup);
        }

        parametersBuilder.setTrackSelectionOverrides(trackSelectionOverridesBuilder.build());
        selector.setParameters(parametersBuilder);

```

PS: Just to update, we are using `DefaultTrackSelector` and its `ParametersBuilder` in most of the cases. As mentioned [here](https://exoplayer.dev/track-selection.html#customizing-the-track-selector) in the docs that I can take advantage of it to customize the things.

Above code to clear the overrides, I directly tried on `Player`. Because I had tried on `DefaultTrackSelector` as well and was not working hence thought of giving a try directly on `Player` using `TrackSelectionParameters`. 


-Thanks

**Comment by ojw28** [comment]
It's quite hard for us to help with this in an efficient way, because we don't have clear reproduction steps short of trying to reconstruct your code snippets inside of our own application. In order for us to help efficiently, I'd suggest you write a small patch to our demo app that allows the problem to be reproduced, and upload it so we can take a look.

**Comment by GouravSna** [comment]
Please check this [branch](https://github.com/GouravSna/ExoPlayer-1/tree/Issue-10055). It's created from dev-v2 because I can see the new implementation for track change is there (using overrides).

As discussed earlier that in demo app and this is the behaviour of demo app;
if for the 1st media, I select 'None' text track then for the 2nd media also text track will be selected 'None' irrespective of the default text track available in the 2nd media.

So by keeping this in mind, I have added the print log in `onTracksInfoChanged(TracksInfo tracksInfo)` because here I am expecting fresh track information irrespective of what I selected for the previous medias.

So here what I can see that if I select 'None' text track for the first media then for the 2nd media, `isSelected` flag comes `false` for all the text tracks. Please check the logs using 'EXOTEST' filter.

My commit is [here](https://github.com/GouravSna/ExoPlayer-1/commit/a74b892b4884cb042be79576095f828fdcc5d56a).

Please let me know your thoughts.

-Thanks

**Comment by ojw28** [comment]
> As discussed earlier that in demo app and this is the behaviour of demo app; if for the 1st media, I select 'None' text track then for the 2nd media also text track will be selected 'None' irrespective of the default text track available in the 2nd media.

I already explained in [this comment](https://github.com/google/ExoPlayer/issues/10055#issuecomment-1066739857) that this behavior is expected for the demo app, and why.

**Comment by GouravSna** [comment]
Sure. @ojw28 , I think I need to adapt my code as per the changes there in dev-v2(not now) and I can see the unreleased changes for TrackSelection [here](https://github.com/androidx/media/blob/main/RELEASENOTES.md#unreleased-changes) on androidx/media.

Actually I was following https://exoplayer.dev/track-selection.html#selecting-specific-tracks and using this way but now I can see `setTrackSelectionOverrides` API is going to be removed. I don't see it in dev-v2. I need to refactor the way of changing the track.

Thanks a lot for your prompt answers and help.
