### ISSUE TITLE
Failed to instantiate a FrameworkMediaDrm

### ISSUE THREAD

**Issue by fkaduch** [google/ExoPlayer#10051]
Hello,

I upgraded my Android TV app's Exoplayer to the latest version 2.17.1 and try to play back Widevine  DRM protected DASH content against our media server. 
Code to initialize player is following:

       MediaItem mediaItem = new MediaItem.Builder()
                .setUri(inUri)
                .setMimeType(MimeTypes.APPLICATION_MPD)
                .setDrmConfiguration(
                        new MediaItem.DrmConfiguration.Builder(C.WIDEVINE_UUID)
                                .setLicenseUri(inWvLicenseUrl)
                                .build())
                .build();

        m_mediaPlayer.setMediaItem(mediaItem);
...

However, when trying to play DRM protected live stream, I am getting this error:
 
 E/FrameworkMediaDrm: Failed to instantiate a FrameworkMediaDrm for uuid: edef8ba9-79d6-4ace-a3c8-27dcd51d21ed.

Any idea what I am missing in the setup of the player to play DRM live stream ?
Would appreciate a code sample for the this latest 2.17.1 version to play DRM protected DASH stream.

- URI to test content - private , can send by email
- For protected content:
  - DRM scheme and license server URL - Widevine BuyDrm system, URL can send by email
  - Authentication HTTP headers - not used

many thanks for help
Frantisek

**Comment by icbaker** [comment]
What version were you on before 2.17.1 (and did the same content work on that version)?

What device do you observe this failure on? If it's only on specific devices please provide the output of `adb bugreport` after reproducing the problem. 

Can you try installing the [ExoPlayer demo app](https://exoplayer.dev/demo-application.html) and playing some of the widevine samples in there? Try those from both the `Widevine DASH (MP4, H264)` and `Widevine DASH (policy tests)` sections.

**Comment by fkaduch** [comment]
Hi Ian,

I was on version 2.12.1 and it did work. 
The output on 2.17.1.is following:
1. on Sony TV it work, using the same approach as Exoplayer demo does.
2. on Android TV emulator it does not work , issuing the E/FrameworkMediaDrm error. However, this may be caused by lack of DRM support in the Android TV emulator.

thanks

**Comment by icbaker** [comment]
I'm able to play widevine encrypted samples in the demo app on an API 30 Android TV emulator.

This doesn't sound like a problem with the ExoPlayer library - if you have device/emulator-specific problems I recommend you report them to the companies/teams responsible for those products.
