### ISSUE TITLE
How to start exoplayer with a lower bitrate even when network bandwidth is available

### ISSUE THREAD

**Issue by krackjack234** [google/ExoPlayer#10069]
Question
---------
We want to start player with a lower bitrate (say 600kbps) before it switches to a higher bitrate when configured abr mode or in fixed bitrate mode.

We want to achieve this to start player as soon as possible

We checked [this api](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/upstream/DefaultBandwidthMeter.Builder.html#setInitialBitrateEstimate(long)) but as per the documentation, player will take this value only if it cannot estimate current bandwidth

We want to start the player at a lower bitrate irrespective of player is able to detect available bandwidth or not.

Our exoplayer version 2.14.1

**Comment by icbaker** [comment]
Have you tried using the setter you linked to? I think it should do what you want.

The wording of the javadoc means the value will be used when the bandwidth can't be estimated by measuring actual transfer rate (which is only possible after playback has started).

**Comment by krackjack234** [comment]
Hi @icbaker  if we use this setter method then our playback gets delayed and it starts only after downloading 3-4 segments as I mentioned in ticket https://github.com/google/ExoPlayer/issues/10070

Also one more observation we have. If we do not call release of the player and just call prepare to play 2nd content, then the initial bitrate passed is ignored and the 2nd content starts with a higher bitrate.

**Comment by krackjack234** [comment]
Closing this issue as its tracked as part of #10070
