### ISSUE TITLE
Why is PlayerView deprecated and we are advised to use StyledPlayerView?

### ISSUE THREAD

**Issue by VincentJoshuaET** [google/ExoPlayer#10063]
I only want the pause/play buttons and it would be great if I did not have to implement that myself.

Maybe you can add something such that we can show or hide the playback buttons programatically or by XML.

**Comment by icbaker** [comment]
Have you tried the following methods on `StyledPlayerView`?

* [`setShowFastForwardButton(boolean)`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/ui/StyledPlayerView.html#setShowFastForwardButton(boolean))
* [`setShowNextButton(boolean)`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/ui/StyledPlayerView.html#setShowNextButton(boolean))
* [`setShowPreviousButton(boolean)`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/ui/StyledPlayerView.html#setShowPreviousButton(boolean))
* [`setShowRewindButton(boolean)`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/ui/StyledPlayerView.html#setShowRewindButton(boolean))
* [`setShowShuffleButton(boolean)`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/ui/StyledPlayerView.html#setShowShuffleButton(boolean))
* [`setShowSubtitleButton(boolean)`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/ui/StyledPlayerView.html#setShowSubtitleButton(boolean))
* [`setShowVrButton(boolean)`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/ui/StyledPlayerView.html#setShowVrButton(boolean))

Passing `false` to those results in a single play/pause button in the middle of the screen.
