### ISSUE TITLE
Exoplayer Play From Http (non Https) Urls with Media Items or Media Source [ java ]

### ISSUE THREAD

**Issue by arunkumartdr** [google/ExoPlayer#10079]
I want to play videos from urls using http protocol inside exoplayer in android app using **JAVA**.

i had tried the below method in manifest 
```
 android:usesCleartextTraffic="true"
```
that does not work for me on minimumsdk 23.

I have tested in android v7.1 and android 11.

Later i had came to know that i have to use DefaultHttpFactory / OKhttp from [here][1]

But i cant get good samples or implementation over internet. 

I had implemented okhttp in gradle
```
    implementation 'com.google.android.exoplayer:extension-okhttp:2.x.x'
```

but i dont know how to implement this methods or function in **JAVA**.

How to solve this with okhttp or is there a better solution?

  [1]: https://exoplayer.dev/network-stacks.html

**Comment by ojw28** [comment]
Starting with the [main demo app](https://github.com/google/ExoPlayer/tree/r2.17.1/demos/main) and adding `android:usesCleartextTraffic="true"` to the correct place in the Android manifest (i.e., [here](https://github.com/google/ExoPlayer/blob/r2.17.1/demos/main/src/main/AndroidManifest.xml#L38)) works fine for me. I also tried increasing the minimum SDK to 23, and it still worked fine.

If you do not observe the same, please provide a patch to our demo application that reproduces the problem. Else there's nothing actionable for us to do here, since it appears that everything works correctly.

**Comment by arunkumartdr** [comment]
my api settings :

```
        minSdk 24
        targetSdk 32
```

my  manifest : 

```
    <application
        ...................
        android:usesCleartextTraffic="true"
        android:networkSecurityConfig="@xml/network_security_config">
```

my network security config : 

```
<?xml version="1.0" encoding="utf-8"?>
<network-security-config xmlns:tools="http://schemas.android.com/tools">
    <base-config cleartextTrafficPermitted="true"
        tools:ignore="InsecureBaseConfiguration">
        <trust-anchors>
            <certificates src="system" />
        </trust-anchors>
    </base-config>
</network-security-config>

```

sample mp4 file : http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4

sample hls file : https://d3rlna7iyyu8wu.cloudfront.net/skip_armstrong/skip_armstrong_stereo_subs.m3u8

**Comment by arunkumartdr** [comment]
This works for me with out any external library for HLS.

```
DataSource.Factory dataSourceFactory = new DefaultHttpDataSource.Factory().setAllowCrossProtocolRedirects(true);
HlsMediaSource hlsMediaSource =
        new HlsMediaSource.Factory(dataSourceFactory)
                .setAllowChunklessPreparation(false) // use it only if needed
                .createMediaSource(MediaItem.fromUri(uri)); // pass your url
exoPlayer.addMediaSource(hlsMediaSource);
exoPlayer.prepare();
exoPlayer.setPlayWhenReady(true);
exoPlayer.play();
```

**Comment by arunkumartdr** [comment]
The above solution works for me and my friend , so i currently close the issue , reopen is you have any issue..
