### ISSUE TITLE
How to implement SSL pinning for the video stream?

### ISSUE THREAD

**Issue by sha3rawi33** [google/ExoPlayer#10075]
Some of my app users tried to capture the video source URL using HTTP proxy (MITM attack). which caused great loss to us.
is there a possible way to add 2 or 3 SSL certificates / or public keys to pin them and reject any other self-signed CA of 3rd party proxy apps?

it's so critical; hopefully someone can have a solution

**Comment by icbaker** [comment]
This isn't really an ExoPlayer question. If you're using the `DefaultHttpDataSource.Factory` (the default) then you can use Android's certificate pinning:
* https://developer.android.com/training/articles/security-ssl#Pinning (including a warning against doing this)
* https://developer.android.com/training/articles/security-config#CertificatePinning

If you're using a [different network stack](https://exoplayer.dev/network-stacks.html) then you should look up in their documentation how to pin the certificates you want.
