### ISSUE TITLE
Dynamic GOP for DASH

### ISSUE THREAD

**Issue by sridhard** [google/ExoPlayer#10073]
Hi,

This is a query regarding exoplayer support:

For better video compression, commercial video encoders have started using per-shot encoding. In per-scene(or per-shot) encoding the video is encoded separately for each scene and the combined together. This gives the best quality video at lower bitrate.

When video is encoded with per-shot encoding, I frames are places at equal intervals within a scene. but if we consider whole video the I frames are not at regular intervals.

Ex: Input video has scene changes at 0 - 10 - 20 - 30 seconds
each scene is encoded separately and then merged.
In output video I frames are at 0 - 4 - 8 - 10 - 14 - 18 - 20 - 24 - 28 seconds (Considering each scene has GOP size of 4 sec)

Is this kind of packaging supported by exo-player? DASH specification this is supported.

Note: Player like shaka-player support this. https://github.com/shaka-project/shaka-player/issues/4025

**Comment by icbaker** [comment]
ExoPlayer doesn't assume that I frames are equally distributed - the type of encoding you're describing should just work. I would recommend you try it, and if you find something doesn't work please file new specific issues with media we can use to reproduce and diagnose the problem.
