### ISSUE TITLE
Is there a direct replacement for constructor DefaultHttpDataSourceFactory(userAgent, bandwidthMeter) from 2.12.1 in 2.16.1?

### ISSUE THREAD

**Issue by alveru** [google/ExoPlayer#10072]
Hi, I am migrating from library 2.12.1 to 2.16.1, and it seems that constructor for DefaultHttpDataSourceFactory has been replaced for another constructor with fewer params.

My old code was:

 protected open fun createDashMediaSource(): MediaSource {
        val userAgent: String = VideoModule.getUserAgent()
        val httpDataSourceFactory = DefaultHttpDataSourceFactory(userAgent, bandwidthMeter)
        val dashMediaSourceFactory = DashMediaSource.Factory(DefaultDashChunkSource.Factory(httpDataSourceFactory), httpDataSourceFactory)
        drmSessionManager?.let { dashMediaSourceFactory.setDrmSessionManager(it) }
        return dashMediaSourceFactory.createMediaSource(MediaItem.fromUri(obtainVideoManifestUrl()))
    }

The new constructor has no params and it has no function to setup the bandwidthMeter directly:

 protected open fun createDashMediaSource(): MediaSource {
        val userAgent: String = VideoModule.getUserAgent()
        val httpDataSourceFactory = DefaultHttpDataSource.Factory()   <------- New constructor according to ReleaseNotes
        httpDataSourceFactory.setUserAgent(userAgent)       <----- setting user agent with new function
        val dashMediaSourceFactory = DashMediaSource.Factory(DefaultDashChunkSource.Factory(httpDataSourceFactory), httpDataSourceFactory)
        drmSessionManager?.let { dashMediaSourceFactory.setDrmSessionManager(it) }
        return dashMediaSourceFactory.createMediaSource(MediaItem.fromUri(obtainVideoManifestUrl()))
    }

I am wondering if is there a direct replacement for the bandwidth meter in the constructor for the data source factory?

**Comment by alveru** [comment]
i found it, is setTransferListener(........) listener, i will close this ticket

**Comment by arunk095** [comment]
@alveru can you post the how you have achieved using the function "setTransferListener" . It would be helpful. Thank you
