### ISSUE TITLE
Honda Infotainment Compatability?

### ISSUE THREAD

**Issue by rickeho** [google/ExoPlayer#10077]
I have a Honda Clarity, and am trying to run an app that uses ExoPlayer. Is it compatible with the Honda Infotainment system?
Thanks.

**Comment by ojw28** [comment]
ExoPlayer is compatible with Android devices, so if Honda publicly state that their infotainment system is running Android, and if it meets the version requirements outlined [here](https://exoplayer.dev/supported-devices.html), then that should be sufficient for ExoPlayer to work.

If Honda do not publicly state that their infotainment system is running Android, but it "appears to be Android", then you need to ask Honda what their device supports. In this case it's possible that they've forked Android but do not guarantee API compatibility. How compatible such forks are with official Android is something that the manufacturer would need to answer.
