### ISSUE TITLE
Video flickering on small sized video player

### ISSUE THREAD

**Issue by ale-groundcloud** [google/ExoPlayer#10086]
Exoplayer 2.17.0
Device: Galaxy tab A7 (SM-T500)
Android 11

When creating a small video player with an hls source the video flickers being stopped or playing. Tested the same behavior on a bigger version of the same view and didn't experience the issue.

I'm using jetpack compose to build a list and the cards contain a small videoplayer to show a preview of the videos, this breaks the UI completely resulting in the list losing all the effects and overlapping the elements after a while.

This issue is similar to https://github.com/google/ExoPlayer/issues/5768

**Comment by ojw28** [comment]
If you want us to take a look at this, I'd suggest you provide a small sample app as source code that reproduces the issue.

**Comment by ale-groundcloud** [comment]
will try to provide a demo project

**Comment by zernickov** [comment]
I've had the same issue but using the solution from [#7270](https://github.com/google/ExoPlayer/issues/7270) fixes it. It doesn't seem to be the safest solution, but forcing the DRM security level to L3 removes the flickering that I was getting on small video sizes that also had a high bitrate.

I only experienced the bug on the following device:
Device: Galaxy Tab A8 (SM-X205)
Android 11
Exoplayer 2.17.0

**Comment by ojw28** [comment]
Marking `needs more info` because we still don't have a demo project that reproduces the issue.
