### ISSUE TITLE
play the mp4 file failed casue of errorCode=ERROR_CODE_IO_READ_POSITION_OUT_OF_RANGE

### ISSUE THREAD

**Issue by dreamwhigh** [google/ExoPlayer#10087]
Base on the ExoPlayer demo (https://github.com/google/ExoPlayer), I replace the URI with the local file address ("/sdcard/DCIM/Camera/ExoPlayer_source.mp4") in media.exolist.json. The demo application prompts "Playback failed". I have parsed the metadata of the video source and found no abnormality. Please help to see why the exception is thrown. Thank you.

`[
  {
    "name": "Clear DASH",
    "samples": [
      {
        "name": "HD (MP4, H264)",
        "uri": "/sdcard/DCIM/Camera/ExoPlayer_source.mp4"
      },
...
  }
]`

- Output of running "adb bugreport" in the console shortly after encountering the issue
[ExoPlayer_log.log](https://github.com/google/ExoPlayer/files/8302169/ExoPlayer_log.log)

- URI to test content for reproduction
https://user-images.githubusercontent.com/48209921/158950345-bd0ae189-5ef5-4f7f-8430-cda4e7af4004.mp4

- ExoPlayer version number
[The latest ExoPlayer Demo](https://github.com/google/ExoPlay)

- Android version
12
- Android device
XIAOMI

**Comment by ojw28** [comment]
The media is invalid because it contains a `meta` box that doesn't start with the mandatory `hdlr` box, as per the MP4 spec.

**Comment by bruce3x** [comment]
@dreamwhigh How do you fix this problem? it's bug from xiaomi rom?
