### ISSUE TITLE
ffmpeg extensions compile error

### ISSUE THREAD

**Issue by Pecana** [google/ExoPlayer#10089]
Hello, I used to compile the ffmpeg extensions with old version but now I am getting an erorr becasue the Android.mk is missing under 
ExoPlayer/extensions/ffmpeg/src/main/jni/Android.mk
Where can i find it ?

Thank you

**Comment by AquilesCanta** [comment]
Can you clarify from which to which version are you transitioning?

**Comment by Pecana** [comment]
H

> Can you clarify from which to which version are you transitioning?

Hello, I am compiling from the currentl  version  2.17.1

**Comment by AquilesCanta** [comment]
Yeah, I'm not clear what's going on. I'm inclined to think it's an issue in the local setup. Android.mk has not been in use for a long time, since https://github.com/google/ExoPlayer/commit/19602ca4ca6dac92fa8aece86a7e48dccc97caa4. Please try following the build instructions on a fresh checkout and you can let us know what you observe.

**Comment by Pecana** [comment]
> Yeah, I'm not clear what's going on. I'm inclined to think it's an issue in the local setup. Android.mk has not been in use for a long time, since [19602ca](https://github.com/google/ExoPlayer/commit/19602ca4ca6dac92fa8aece86a7e48dccc97caa4). Please try following the build instructions on a fresh checkout and you can let us know what you observe.

Hello, I followed the stpes and the compile successed but I guess it misses the steps to generate the .so files, now only the .a files are present, any idea ?

**Comment by AquilesCanta** [comment]
It's impossible to know with this amount of info. For your peace of mind, I'm able to compile normally, so I think you might find an error in your console output.

**Comment by Pecana** [comment]
> It's impossible to know with this amount of info. For your peace of mind, I'm able to compile normally, so I think you might find an error in your console output.

Are you able to find the .so libraries file ?

**Comment by Pecana** [comment]
There is no error during compile, this is the last part of the log : https://pastebin.com/FL72ZpMi

here the full log : https://drive.google.com/file/d/1ITpCA2sY7VK5fHYNUShv85hOyxSCkhOi/view?usp=sharing

**Comment by AquilesCanta** [comment]
> Hello, I followed the stpes and the compile successed but I guess it misses the steps to generate the .so files, now only the .a files are present, any idea ?

Ah sorry, I misread. This is expected, because .a files are intended for static linking, unlike .so files which are meant for dynamic linking. The gradle build will generate an libffmpeg_jni.so (or something like that) which statically links against those .a files, avoiding the need for additional .so files. You should be able to play files using ffmpeg normally.

I think there's no issue then?

**Comment by Pecana** [comment]
> > Hello, I followed the stpes and the compile successed but I guess it misses the steps to generate the .so files, now only the .a files are present, any idea ?
> 
> Ah sorry, I misread. This is expected, because .a files are intended for static linking, unlike .so files which are meant for dynamic linking. The gradle build will generate an libffmpeg_jni.so (or something like that) which statically links against those .a files, avoiding the need for additional .so files. You should be able to play files using ffmpeg normally.
> 
> I think there's no issue then?

So can I just add the .a files into my "exo project" ? In the past rleases I used to copy the .so file also because looking at the FfmpegLibrary class it load libraries :
private static final LibraryLoader LOADER =
            new LibraryLoader("avutil", "swresample", "avresample", "avcodec", "ffmpeg");

**Comment by AquilesCanta** [comment]
> So can I just add the .a files into my "exo project" ? 

No.

> In the past rleases I used to copy the .so file also because looking at the FfmpegLibrary class it load libraries :

That's no longer necessary. As you can see the loader now only cares about ffmpegJNI. https://github.com/google/ExoPlayer/blob/release-v2/extensions/ffmpeg/src/main/java/com/google/android/exoplayer2/ext/ffmpeg/FfmpegLibrary.java#L35. You just need to follow the instructions in the readme, make sure decoder extensions are properly setup in your app and that's it.

**Comment by Pecana** [comment]
> > So can I just add the .a files into my "exo project" ?
> 
> No.
> 
> > In the past rleases I used to copy the .so file also because looking at the FfmpegLibrary class it load libraries :
> 
> That's no longer necessary. As you can see the loader now only cares about ffmpegJNI. https://github.com/google/ExoPlayer/blob/release-v2/extensions/ffmpeg/src/main/java/com/google/android/exoplayer2/ext/ffmpeg/FfmpegLibrary.java#L35. You just need to follow the instructions in the readme, make sure decoder extensions are properly setup in your app and that's it.

Ok, i will try to compile the whole project and check :-)

**Comment by Pecana** [comment]
I was able to get it finally :-)
After the spets reported into the readme i executed :
./gradlew :extension-ffmpeg:assembleRelease
So an AAR with the compiled libraries has been generated :-)

Thanks @AquilesCanta for your help and patience :-D

**Comment by AquilesCanta** [comment]
No problem, happy to help.

**Comment by eazes123** [comment]
@Pecana if you use decoder mp3 can you send that aar file.
