### ISSUE TITLE
Hls video take too much time if I download 5 video simultaneously.

### ISSUE THREAD

**Issue by NG-Gaurav** [google/ExoPlayer#10084]
if i only download 1 video than it take 2 minutes. but if i download 5 video simultaneously and after i pause 4 video than single same video take 8 minutes.

**Comment by ojw28** [comment]
This issue is too vague to be actionable. Please provide concrete reproduction steps. For example, a small patch to our demo app that would allow us to easily reproduce the issue.

**Comment by kaychyka17** [comment]
@NG-Gaurav can you please share your code how do you download HLS video? I already asked for help in issue #9583 but didn't get any useful answer. I try to download it but for some reason I get to small file.

**Comment by NG-Gaurav** [comment]
Actual i was adding subtitles list with media item. so after removing it video download working fine now.
