### ISSUE TITLE
Contd..  Closed Change Media with TextTracks on ExoPlayer v2.17.0 and v2.17.1

### ISSUE THREAD

**Issue by GouravSna** [google/ExoPlayer#10105]
https://github.com/google/ExoPlayer/issues/10055 issue was closed hence opened a new one for the continuation.

Hi @ojw28 ,

I tried your suggestion to clear the overrides before loading the another media. However, I can see that `TrackSelectionParameters` does not have any overrides before loading the another media but still for the next media, I can see the same issue where the default track is not coming as 'Selected'.

This is how I am clearing the overrides,

```java
        player.setTrackSelectionParameters(player.getTrackSelectionParameters().buildUpon().setTrackSelectionOverrides(TrackSelectionOverrides.EMPTY).build());

```

I have applied your suggestion where you pointed that code is not doing anything. So new piece of code looks like this,

``` java
//actually change track.
        TrackGroup trackGroup = mappedTrackInfo.getTrackGroups(rendererIndex).get(groupIndex);
        if (!selectedIndices.isEmpty()) {
            if (rendererIndex == TRACK_TYPE_TEXT && selectedIndices.get(0) == TRACK_DISABLED) {
                // Just clear the selected indices,
                // it will let exoplayer know that no tracks from trackGroup should be played
                selectedIndices.clear();
            }

            TrackSelectionOverrides.TrackSelectionOverride trackSelectionOverride = new TrackSelectionOverrides.TrackSelectionOverride(trackGroup, selectedIndices);
            trackSelectionOverridesBuilder.setOverrideForType(trackSelectionOverride);
        } else {
            //clear all the selections if selectedIndices are empty.
            trackSelectionOverridesBuilder.clearOverride(trackGroup);
        }

        parametersBuilder.setTrackSelectionOverrides(trackSelectionOverridesBuilder.build());
        selector.setParameters(parametersBuilder);

```

PS: Just to update, we are using `DefaultTrackSelector` and its `ParametersBuilder` in most of the cases. As mentioned [here](https://exoplayer.dev/track-selection.html#customizing-the-track-selector) in the docs that I can take advantage of it to customize the things.

Above code to clear the overrides, I directly tried on `Player`. Because I had tried on `DefaultTrackSelector` as well and was not working hence thought of giving a try directly on `Player` using `TrackSelectionParameters`. 

-Thanks

_Originally posted by @GouravSna in https://github.com/google/ExoPlayer/issues/10055#issuecomment-1068917477_

**Comment by ojw28** [comment]
Closing as a duplicate.
