### ISSUE TITLE
RoleFlag score calculation for RoleFlag == 0

### ISSUE THREAD

**Issue by SaurabhOfficial** [google/ExoPlayer#10106]
When filing a question:
-------------------------

Describe your question in detail.

I saw that exact matches are preferred only in case roleFlags are not equal to 0 in the defaultTrackSelector. 0 is treated as no preference in terms of roleFlags
```
   private static int getRoleFlagMatchScore(int trackRoleFlags, int preferredRoleFlags) {
      if (trackRoleFlags != 0 && trackRoleFlags == preferredRoleFlags) {
        // Prefer perfect match over partial matches.
        return Integer.MAX_VALUE;
      }
      return Integer.bitCount(trackRoleFlags & preferredRoleFlags);
    }
```

but what if preferredRoleFlag as 0 is a preference that the user has registered? and wants all tracks without any roleFlags only.

I ran into this scenario where a manifest has 2 audio tracks with all similar parameters except the roleFlags, one track has roleFlag as 0 and the second has 512 (Audio description) and the preferred roleFlag is 0. 
In this case the track selection selects AudioDescription track which is somewhat correct with current logic where set bit count would be the same for both 0 as well as 512.

should I change the implementation to include 0 as a preference indicator? 
is there some other way to handle this scenario? 
is there some exact track selection matching that I couldn't find in docs?
```
   private static int getRoleFlagMatchScore(int trackRoleFlags, int preferredRoleFlags) {
      if (trackRoleFlags == preferredRoleFlags) {
        // Prefer perfect match over partial matches.
        return Integer.MAX_VALUE;
      }
      return Integer.bitCount(trackRoleFlags & preferredRoleFlags);
    }
```

cc @LuGO0

**Comment by ojw28** [comment]
I think that the track without the audio description role flag should be selected in this case. As you note, the role flag match score will evaluate to the same value for both tracks. However in that case the tracks are further compared, and part of that further comparison is to prefer tracks that don't have any role flags over those that do:

https://github.com/google/ExoPlayer/blob/r2.17.1/library/core/src/main/java/com/google/android/exoplayer2/trackselection/DefaultTrackSelector.java#L2625

I think this logic is relatively recent, so if you're using an older version of ExoPlayer then please try with 2.17 and perhaps you'll see everything work as expected. If not, please provide us with some sample media that we can use to easily reproduce the issue. Thanks!

**Comment by dino-saurabh** [comment]
Got it, was using 2.16 for this media, will try it once with 2.17.1 👍🏼 

> if (trackRoleFlags != 0 && trackRoleFlags == preferredRoleFlags) {

@ojw28 I got one more question, why is that 0 has been excluded explicitly in the checks where we prefer exact matches over everything else? are there any caveats of doing so?

**Comment by ojw28** [comment]
The details of track selection are pretty subtle. There are a lot of parameters and interactions between them, as well as edge cases that need to be handled slightly differently. As a possibly relevant example, consider two tracks where one has no role flag and one has `ROLE_FLAG_MAIN`, and that the application doesn't specify a preference for any role flags. It's probably not right to prefer the track with no role flag in this case. Because the behavior is so subtle, we try and ensure good test coverage in `DefaultTrackSelectorTest`, and add cases to it as they come up.

I'm not sure exactly why this particular line of code is written this way, but if you remove the check there are four unit tests in `DefaultTrackSelectorTest` that start failing. So it does seem to be doing something useful. If you're interested in figuring it out, I'd suggest looking at the specific test cases that start failing :).

**Comment by ojw28** [comment]
Closing this for now because I _think_ 2.17 probably behaves as you expect. Please do let us know if that's not the case though, with some media that we can use to reproduce. Thanks!

**Comment by dino-saurabh** [comment]
> If you're interested in figuring it out, I'd suggest looking at the specific test cases that start failing :).

Sure will do Thanks !

**Comment by dino-saurabh** [comment]
> It's probably not right to prefer the track with no role flag in this case. 

One more question 👀, what about the scenario where the player is currently playing the Main track and the user wants to switch to the no-role flag track (just making this up, not really sure if there will be a scenario where both main and no-role flag tracks will be available for a single language), won't it be a bit buggy behavior not to switch the tracks even if the user explicitly told us to do so?

**Comment by dino-saurabh** [comment]
>>If you're interested in figuring it out, I'd suggest looking at the specific test cases that start failing :).

>Sure will do Thanks !

All 4 tests fail on the TextTrack Selection, Nothing fails related to the AudioTracks I am assuming hopefully, it's safe to do so on the AudioTrackScore 😅

**Comment by ojw28** [comment]
I'm not really sure that _explicitly_ selecting "no role flags" makes a lot of sense as a use case. It's kind of like selecting "the undefined thing". Maybe track selection overrides would be a better way of doing that.

That aside, there are so many hypothetical cases in track selection that I think it probably makes sense to defer giving cases like this too much thought, until we see concrete examples of them.
