### ISSUE TITLE
Video decoder is released when app is pushed to background

### ISSUE THREAD

**Issue by krackjack234** [google/ExoPlayer#10102]
Question
=======

We are seeing one issue with exoplayer v2.1.4.1 where exoplayer is playing audio but with black video for few secs when the app is brought to foreground from background

Steps
===

1. Start playing a video
2. Push app to background. App calls exoplayer api to pause player. It does not release the player
3. Bring app to foreground. App calls exoplayer api to play

Actual result: Player is playing only audio for ~2s before video frame is seen on the view. During this period, user sees black screen but can hear audio

Expected result: Video frames should be seen along with audio as soon as user brings app to foreground

Logs
====

```
03-22 22:26:28.962 24993 24993 D EventLogger: isPlaying [eventTime=14.24, mediaPos=153.18, window=0, period=0, false]
03-22 22:26:29.743 24993 24993 D EventLogger: surfaceSize [eventTime=15.02, mediaPos=153.18, window=0, period=0, 0, 0]
03-22 22:26:30.563 24993 24993 D EventLogger: videoDecoderReleased [eventTime=15.84, mediaPos=153.18, window=0, period=0, OMX.MTK.VIDEO.DECODER.AVC.secure]
03-22 22:26:43.616 24993 24993 D EventLogger: playWhenReady [eventTime=28.89, mediaPos=153.18, window=0, period=0, true, USER_REQUEST]
03-22 22:26:43.625 24993 24993 D EventLogger: isPlaying [eventTime=28.90, mediaPos=153.18, window=0, period=0, true]
03-22 22:26:43.828 24993 24993 D EventLogger: surfaceSize [eventTime=29.11, mediaPos=153.18, window=0, period=0, 1080, 613]
03-22 22:26:45.346 24993 24993 D EventLogger: videoDecoderInitialized [eventTime=29.29, mediaPos=153.47, window=0, period=0, OMX.MTK.VIDEO.DECODER.AVC.secure]
03-22 22:26:52.837 24993 24993 E EventLogger: audioTrackUnderrun [eventTime=38.12, mediaPos=162.57, window=0, period=0, 48000, 250, 360]
03-22 22:26:54.940 24993 24993 D EventLogger: videoSize [eventTime=40.22, mediaPos=164.54, window=0, period=0, 320, 180]
03-22 22:26:54.953 24993 24993 D EventLogger: renderedFirstFrame [eventTime=40.22, mediaPos=164.54, window=0, period=0, Surface(name=null)/@0x6d2285c]
```

We see that the video decoder is released when app is pushed to background and then initialised again when it is brought to foreground which is causing a delay in rendering the first video frame. The audio decoder is not released in this flow

**Is there anyway we can avoid releasing the video decoder?**

We know its not a recommended practise to keep the player alive when app is pushed to background, but here we have some constraints, hence asking the question.

**Comment by krackjack234** [comment]
hi @christosts  any update on this?

**Comment by tonihei** [comment]
> Push app to background. App calls exoplayer api to pause player. It does not release the player

The player has to be released when the app goes into background, or playback needs to be run in a foreground service instead. Otherwise the system is free to reclaim resources as it happened here.
