### ISSUE TITLE
Audio overlay on video with MergingMediaSource, controls not working after merging media source.

### ISSUE THREAD

**Issue by shriyaapptware** [google/ExoPlayer#10108]
```
protected boolean initializePlayer() {
    if (player == null) {
      Intent intent = getIntent();
      mediaItems = createMediaItems(intent);
      if (mediaItems.isEmpty()) {
        return false;
      }
      boolean preferExtensionDecoders =
          intent.getBooleanExtra(IntentUtil.PREFER_EXTENSION_DECODERS_EXTRA, false);
      RenderersFactory renderersFactory =
          DemoUtil.buildRenderersFactory(/* context= */ this, preferExtensionDecoders);

      trackSelector = new DefaultTrackSelector(/* context= */ this);
      lastSeenTracksInfo = TracksInfo.EMPTY;
      player =
          new ExoPlayer.Builder(/* context= */ this)
              .setRenderersFactory(renderersFactory)
              .setMediaSourceFactory(createMediaSourceFactory())
              .setTrackSelector(trackSelector)
              .build();
      player.setTrackSelectionParameters(trackSelectionParameters);
      player.addListener(new PlayerEventListener());
      player.addAnalyticsListener(new EventLogger(trackSelector));
      player.setAudioAttributes(AudioAttributes.DEFAULT, /* handleAudioFocus= */ true);
      player.setPlayWhenReady(startAutoPlay);
      playerView.setPlayer(player);
      serverSideAdsLoader.setPlayer(player);
      debugViewHelper = new DebugTextViewHelper(player, debugTextView);
      debugViewHelper.start();
    }
    boolean haveStartPosition = startItemIndex != C.INDEX_UNSET;
    if (haveStartPosition) {
      player.seekTo(startItemIndex, startPosition);
    }

    Uri uri_audio = Uri.parse(DEFAULT_MEDIA_AUDIO_URI);
    DataSource.Factory dataSourceFactory = new DefaultDataSource.Factory(this);
    MediaSource mediaSource, mediaSourceAudio;
    MergingMediaSource mergedSource = null;
    mediaSource = new ProgressiveMediaSource.Factory(dataSourceFactory)
        .createMediaSource(mediaItems.get(0));
    mediaSourceAudio = new ProgressiveMediaSource.Factory(dataSourceFactory)
        .createMediaSource(MediaItem.fromUri(uri_audio));

    mergedSource = new MergingMediaSource(mediaSourceAudio, mediaSource);

    player.addMediaSource(mergedSource);
    player.prepare();
    updateButtonVisibility();
    return true;
  }
```
Previous code is pointing to   player.setMediaItems(mediaItems, /* resetPosition= */ !haveStartPosition);    
but bound to use  player.addMediaSource(mergedSource); to merge the audio file over the video. DO we have other way to achieve this.

**Comment by shriyaapptware** [comment]
Seekbar and other controls like forward button, backward button, and subtitle buttons got disabled.

**Comment by marcbaechinger** [comment]
Looks like the media is not seekable which would explain why the seekBack/seekForward buttons are disabled. 

If you want us to look into this some further, you need to provide us with the media. If you're unable to share test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #10108". Please also update this issue to indicate you’ve done this.

**Comment by shriyaapptware** [comment]
I am trying to test with this audio below.   

private static final String DEFAULT_MEDIA_AUDIO_URI = "https://www.learningcontainer.com/wp-content/uploads/2020/02/Kalimba.mp3";

Video url is from the exoplayer sdk only. - https://html5demos.com/assets/dizzy.mp4

@marcbaechinger 
My objective of doing this is to apply audio file in some language to the existing video and if the video does not contains audio then apply some other audio file over it. I was looking for the solution but it seems not much content available.
Is there any way other of doing this?

**Comment by shriyaapptware** [comment]
It worked perfectly fine with the different audio file. Thanks a lot @marcbaechinger
