### ISSUE TITLE
Audio starts before Video in STATE_READY

### ISSUE THREAD

**Issue by sapanda** [google/ExoPlayer#1011]
I just upgraded from 1.4 to 1.5.2. The player enters STATE_READY when the audio is ready but the video takes a second longer to start playing. Is this a regression from 1.4 or is it by design? i.e. does the player now choose to play the audio as soon as it's ready even if video isn't?

I noticed this issue with a 1440p 10mbps HEVC video. Issue wasn't as noticeable with a 1080p 10mbps H.264 video.

For reference, here are the two streams:
HEVC: http://104.197.206.39:1935/live/mc1_abr.smil/playlist.m3u8
H.264: http://104.197.206.39:1935/vod/_definst_/mp4:videos/canalp/cp_1_1080_10.mp4/playlist.m3u8

**Comment by ojw28** [comment]
I don't think it's a regression; I think it was always that way. It's most likely avoidable if you ensure there's always a video keyframe near the start of each video segment. This is a property that's (in practice) guaranteed in DASH and SmoothStreaming; both of which will give you better streaming performance than when using HLS.
