### ISSUE TITLE
Do you provide #EXT-X-I-FRAMES-ONLY thumbnail preview function in HLS stream?

### ISSUE THREAD

**Issue by generlist** [google/ExoPlayer#10111]
Hello ~
I know HLS Play can provide preview thumbnails of The #EXT-X-I-FRAMES-ONLY playback.
Does exoPlayer currently support implementable functions for this tag?
When I asked a question a few years ago, I said that it was not supported, so I am asking again.

**Comment by marcbaechinger** [comment]
I think issue #8938 describes the current state.

If you have a stream with iframe only tracks then it is best to try out whether your stream is working. The referenced issue explains in more details how you can do this.

I'm closing this issue as a duplicate.
