### ISSUE TITLE
Should a custom `AudioProcessor` implementation handle all possible encodings?

### ISSUE THREAD

**Issue by OxygenCobalt** [google/ExoPlayer#10115]
I'm implementing my own `AudioProcessor` tailored to my app's uses in particular. I intend to provide this implementation to `MediaCodecAudioRenderer` and `LibflacAudioRenderer` when the `Player` instance is created.. However, after reading library implementations like [ResamplingAudioProcessor](https://github.com/google/ExoPlayer/blob/02f7aafe67b4893134a31ea55a3ba0f0535df145/library/core/src/main/java/com/google/android/exoplayer2/audio/ResamplingAudioProcessor.java), I'm confused about what encodings are actually sent to my `AudioProcessor`. 

Should an `AudioProcessor` just handle a resampled output like `ENCODING_PCM_16BIT`? Or is it more appropriate to handle every single possible encoding [i.e `ENCODING_PCM_8BIT`, `ENCODING_PCM_FLOAT`]? Some clarification here would be much appreciated.

**Comment by krocard** [comment]
Custom audio processors are only run if the output is `ENCODING_PCM_16BIT`. If the float output is enabled, they are not run:

https://github.com/google/ExoPlayer/blob/8129675b065bc98330ec775fb7a538c139793070/library/core/src/main/java/com/google/android/exoplayer2/audio/DefaultAudioSink.java#L309-L312

The code ignores the provided `audioProcessorChain` in non PCM_16BIT: https://github.com/google/ExoPlayer/blob/8129675b065bc98330ec775fb7a538c139793070/library/core/src/main/java/com/google/android/exoplayer2/audio/DefaultAudioSink.java#L608-L615
