### ISSUE TITLE
Ffmpeg extension quesion

### ISSUE THREAD

**Issue by tpuserhp** [google/ExoPlayer#10128]
I'm able to build the ffmpeg extension and use it in the demo app and my own app. But I want to just have the armeabi-v7a and arm64-v8a libraries generated only to reduce the apk size. When I build the demo project, it seems  x86 and x64_64 libraries needs to be in  the ANDROID-LIBS folder. I build the ffmpeg extension in  the Linux machine and  copy the ffmpeg directory to Windows 10  where Android Studio is resided. What needs to be done to achieve this? Thanks.

**Comment by vovan888** [comment]
app/build.gradle:

```
android {
        ndk {
            abiFilters "armeabi-v7a", "arm64-v8a"
        }
}

```

**Comment by tpuserhp** [comment]
Yes, the suggested changes resulted in a smaller size of the apk  generated. Thank you very much  for your help. This issue can be closed now.
