### ISSUE TITLE
DASH representation varied (FormatEvaluator called) too frequently? 

### ISSUE THREAD

**Issue by yanlove** [google/ExoPlayer#1012]
Hello,

I was testing how often the AdaptiveEvaluator is called in DASH, i.e., how often the DASH representation is changed. I thought the format should be evaluated once a segment. But after I print a simple message to see how often AdaptiveEvaluator is called, I found the calling frequency of this method is irregular:

11-30 20:20:03.814 3860-4076/com.google.android.exoplayer.demo V/DASHtest: Playback Position:
11-30 20:20:05.305 3860-4076/com.google.android.exoplayer.demo V/DASHtest: Playback Position:
11-30 20:20:06.306 3860-4076/com.google.android.exoplayer.demo V/DASHtest: Playback Position:
11-30 20:20:07.037 3860-4076/com.google.android.exoplayer.demo V/DASHtest: Playback Position:
11-30 20:20:07.747 3860-4076/com.google.android.exoplayer.demo V/DASHtest: Playback Position:
11-30 20:20:08.328 3860-4076/com.google.android.exoplayer.demo V/DASHtest: Playback Position:
11-30 20:20:09.009 3860-4076/com.google.android.exoplayer.demo V/DASHtest: Playback Position:
11-30 20:20:10.360 3860-4076/com.google.android.exoplayer.demo V/DASHtest: Playback Position:
11-30 20:20:11.081 3860-4076/com.google.android.exoplayer.demo V/DASHtest: Playback Position:
11-30 20:20:11.561 3860-4076/com.google.android.exoplayer.demo V/DASHtest: Playback Position:
11-30 20:20:13.593 3860-4076/com.google.android.exoplayer.demo V/DASHtest: Playback Position:
11-30 20:20:14.234 3860-4076/com.google.android.exoplayer.demo V/DASHtest: Playback Position:
11-30 20:20:14.874 3860-4076/com.google.android.exoplayer.demo V/DASHtest: Playback Position:

Does anyone know how frequent the DASH representation is evaluated and changed? Is there a way to configure this frequency (which part of the code?). 

Any ideas would be greatly appreciated. Thanks a lot.

**Comment by ojw28** [comment]
For each stream, evaluation occurs before each segment load. Note that this is not the same as saying that evaluations will occur evenly once every segment duration, because each segment fetch may take more or less time, and segment fetches may be batched together. Evaluation may also occur every 2 seconds, in order to re-evaluate in case buffered media should be discarded in order to re-buffer at a higher quality. Note that most DASH playbacks have two streams (one for video, and a separate one for audio).

**Comment by yanlove** [comment]
Thank you for the answers. I also found some cases where no segment is being downloaded and buffer size is fixed, but the format evaluation occurs. I think that's what you meant by "re-evaluate to discard segments". (like the below log, the next segment fixed at 80s for a while)

12-01 10:21:14.849 12935-13269/com.google.android.exoplayer.demo V/DASHtest: Playback Position:32485000; Next Segment Start Time:60000000; Bandwidth: 4447233; Requested Bitrate:3245900; Bufed chunk Bitrate:2070985
12-01 10:21:19.493 12935-13269/com.google.android.exoplayer.demo V/DASHtest: Playback Position:37119000; Next Segment Start Time:70000000; Bandwidth: 6673129; Requested Bitrate:3792491; Bufed chunk Bitrate:2070985
12-01 10:21:32.626 12935-13269/com.google.android.exoplayer.demo V/DASHtest: Playback Position:50259000; Next Segment Start Time:80000000; Bandwidth: 4070575; Requested Bitrate:3792491; Bufed chunk Bitrate:2884382
12-01 10:21:34.678 12935-13269/com.google.android.exoplayer.demo V/DASHtest: Playback Position:52332000; Next Segment Start Time:80000000; Bandwidth: 4070575; Requested Bitrate:3792491; Bufed chunk Bitrate:2884382
12-01 10:21:36.710 12935-13269/com.google.android.exoplayer.demo V/DASHtest: Playback Position:54367000; Next Segment Start Time:80000000; Bandwidth: 4070575; Requested Bitrate:3792491; Bufed chunk Bitrate:2884382


Also, would you let me know where we can modify the way the player loads a segment (i.e., when/how often to send a HTTP request and start downloading) and the way the player plays a segment (e.g., I want to display some toast when the played segment is lower than a certain quality or print some statistics). Which class/method I should refer to? I am sorry if this is too obvious. I am really new to this and have been looking at the code, but no luck. Thanks a lot.

**Comment by ojw28** [comment]
- Yes, that would be re-evaluation logic.
- `DefaultLoadControl` co-ordinates how/when loads are allowed to proceed.
