### ISSUE TITLE
Is there any avaiable widevine test license url(in china)? connect to  proxy.uat.widevine.com fail

### ISSUE THREAD

**Issue by saralee2012** [google/ExoPlayer#10125]
question:
-------------------------

- i'm trying to use exoplayer to play drm video;when i run demo application(https://exoplayer.dev/demo-application.html) to play widevine demo video, i get an SocketTimeoutException error; is there any other avaiable widevine test license url that i can use to test demo; i'm in china mainland, can't connect to  proxy.uat.widevine.com, thanks!

error info:
-------------------------
com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: java.net.SocketTimeoutException: failed to connect to proxy.uat.widevine.com after 8000ms

**Comment by rrfrias** [comment]
Sorry for the delay. We do have some services within mainland China but there is no test license URI available. I assume our partners in mainland China have found a way to access proxy.uat.widevine.com . Let us know if you have any furthur questions.
