### ISSUE TITLE
Exoplayer v2.15.0 after audio pause,cannot resume the audio.

### ISSUE THREAD

**Issue by zhhach123** [google/ExoPlayer#10127]
Using Exoplayer to paly flac audio connected with dac device.First pause the audio,then resume it.It donnot work.So i write some logs in the ExoPlayerImplInternal. It seems enter the function(setPlayWhenReady(
            boolean playWhenReady, @PlaybackSuppressionReason int playbackSuppressionReason)).
![QQ截图20220330105929](https://user-images.githubusercontent.com/53030012/160742467-5afe793d-668f-4e7a-8598-3c3b4b43dfed.png)
But function handlerMessage donnot receive the message,even the message after.It seems the handler was broke down.I don’t know why this happened.
![QQ截图20220330111204](https://user-images.githubusercontent.com/53030012/160743867-ef6c91df-fd59-46f3-b596-39ef2db91648.png)
This is the log i write, type MSG_DO_SOME_WORK is to frequently so i shield it.

Thanks.

**Comment by marcbaechinger** [comment]
If you think there is an bug in the library, please [file a bug report](https://github.com/google/ExoPlayer/issues/new?assignees=&labels=bug%2Cneeds+triage&template=bug.yml) and provide the information requested there.
