### ISSUE TITLE
Duplicate class com.google.android.exoplayer2.ui.DownloadNotificationHelper found in modules jetified-exoplayer-core-2.17.0-runtime (com.google.android.exoplayer:exoplayer-core:2.17.0) and jetified-exoplayer-ui-2.15.1-runtime (com.google.android.exoplayer:exoplayer-ui:2.15.1)

### ISSUE THREAD

**Issue by sadaqatdev** [google/ExoPlayer#10122]
Duplicate class com.google.android.exoplayer2.ui.DownloadNotificationHelper found in modules jetified-exoplayer-core-2.17.0-runtime (com.google.android.exoplayer:exoplayer-core:2.17.0) and jetified-exoplayer-ui-2.15.1-runtime (com.google.android.exoplayer:exoplayer-ui:2.15.1)

**Comment by icbaker** [comment]
From the error message it looks like you're depending (either directly or transitively) on `exoplayer-core-2.17.0` and `exoplayer-ui-2.15.1`, i.e. two different versions.

From the [README](https://github.com/google/ExoPlayer/blob/release-v2/README.md#1-add-exoplayer-module-dependencies):

> When depending on individual modules they must all be the same version.

If you want to dig into where these dependencies are coming from in your project you use Gradle's `dependencies` task: https://docs.gradle.org/current/userguide/viewing_debugging_dependencies.html

**Comment by icbaker** [comment]
From the error message it looks like you're depending (either directly or transitively) on `exoplayer-core-2.17.0` and `exoplayer-ui-2.15.1`, i.e. two different versions.

From the [README](https://github.com/google/ExoPlayer/blob/release-v2/README.md#1-add-exoplayer-module-dependencies):

> When depending on individual modules they must all be the same version.

If you want to dig into where these dependencies are coming from in your project you use Gradle's `dependencies` task: https://docs.gradle.org/current/userguide/viewing_debugging_dependencies.html

**Comment by sadaqatdev** [comment]
solve by I avoided this issues by specifying video_player to 2.2.17.
