### ISSUE TITLE
No audio output when CMAF & Multi-Key & Segmented mp4 are packaged.

### ISSUE THREAD

**Issue by coooltype** [google/ExoPlayer#10136]
1. No audio when I package Widevine content as [multi-key + Segmented mp4] and play it in Android Exoplayer (2.16.1). But if I package it as [multi-key + Single mp4] it outputs audio.
Why is there no audio output for content packaged as [multi-key + segmented mp4] in Exoplayer? Is there a way to output audio with this content?

2. In Exoplayer, segmented-VTT subtitles are not displayed.
Exactly, only the first segmented subtitles are displayed, not later.
How can I get segmented-VTT subtitles to be displayed?

**Comment by marcbaechinger** [comment]
Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md). If you're unable to share bug reports or test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Please also update this issue to indicate you’ve done this.

I think you need to provide test media to make this actionable for us.

**Comment by marcbaechinger** [comment]
The given information isn't sufficient to make your report actionable for use I'm afraid. 

Please [file a bug for this issue](https://github.com/google/ExoPlayer/issues/new?assignees=&labels=bug%2Cneeds+triage&template=bug.yml) and fill the form there that collects the required information so we can look into this. 

I'm closing this issue so we don't have a duplicate after you filed the bug with the required information.

**Comment by coooltype** [comment]
[multi-key + Segmented mp4] content.
When I download and play content in Exoplayer Demo, I have no audio.

```
{
        "name": "segmented/cmaf",
        "uri": "https://contents.pallycon.com/DEMO/app/tears_of_steel-segmented/cmaf/stream.mpd",
        "drm_scheme": "widevine",
        "drm_license_uri": "https://license.pallycon.com/ri/licenseManager.do",
        "drm_key_request_properties": {
          "pallycon-customdata-v2": "eyJrZXlfcm90YXRpb24iOmZhbHNlLCJyZXNwb25zZV9mb3JtYXQiOiJvcmlnaW5hbCIsInVzZXJfaWQiOiJ1dGVzdCIsImRybV90eXBlIjoid2lkZXZpbmUiLCJzaXRlX2lkIjoiREVNTyIsImhhc2giOiJwYUoybFVTYmQ5aEpGQ3VkVWNLbFV2WDdaRGZSa3l6VmY2VHBzaTd2VUtvPSIsImNpZCI6ImRlbW8tdG9zLWFkdmFuY2VkIiwicG9saWN5IjoiOVdxSVdrZGhweFZHSzhQU0lZY25Kc2N2dUE5c3hndWJMc2QrYWp1XC9ib21RWlBicUkreGFlWWZRb2Nja3Z1RWZ4RGNjbTdjV2RWWHFyZE1nQVFqbXFmVVhja1doNEgwNGFMODlUa0hKOXUxWjJTUUlhSWFUXC9rd09JUFQyaWZMN2NkK0pBK2l0clpzaHNqbXpxR0R6NWVzOVhtbk0rWktUNnF4WUtOM2o0ekV3WURvTHlBeUhTZzVvN3BVQjVZa1YiLCJ0aW1lc3RhbXAiOiIyMDIyLTA0LTAxVDA5OjA5OjE5WiJ9"
        }
}
```

I would also like to know why the subtitles are not displayed.
