### ISSUE TITLE
Multiple AdaptationSet for Audio (Multiple Language)

### ISSUE THREAD

**Issue by seventhmoon** [google/ExoPlayer#1013]
Sample Src: http://shaka-player-demo.appspot.com/assets/angel_one.mpd

Is it possible to update the sample player, so that the "AUDIO" button is selecting Adaptation Set for Audio (if multiple available) rather than Representations (bit rates of same audio Adaption Set)?

I think for Audio, the more common use case is selecting "channel / language" rather than selecting "bitrate".

Suggest to add this feature in the demo application.

**Comment by ojw28** [comment]
We prefer exposing each individual stream in the demo app. There's nothing stopping you from implementing different behavior in your own app, if you prefer to do it a different way.
