### ISSUE TITLE
Ads UI not visible when set media item with ads ima with different ad tag

### ISSUE THREAD

**Issue by muibungs** [google/ExoPlayer#10135]
### ExoPlayer Version

2.17.1

### Devices that reproduce the issue

OPPO F11 Pro Android 11

### Reproducible in the demo app?

Yes

### Reproduction steps

1. Start player media item with Ad Tag URL
2. Set media item when button clicked with new media source with another ads tags URL 
3. When ads playing try to click 1-4 times
4. Ads Controller view not visible in player view

### Expected result

I think it should be shown ad UI ad before ads playing

### Actual result

Ad Ui is not showing in player view when ad playing.

### Media

I try to use this solution [https://github.com/google/ExoPlayer/issues/5514](https://github.com/google/ExoPlayer/issues/5514) it works for stack view but sometimes ad UI does not show 

https://user-images.githubusercontent.com/33998335/160980246-ba4a944d-99f7-4130-86cb-f4c52beb209d.mp4

My code for random ads before setting media item :
 ```
test.setOnClickListener(view -> {
      ArrayList<String> list = new ArrayList();
      list.add("https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dlinear&correlator=");
      list.add("https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dskippablelinear&correlator=");
      list.add("https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ar%3Dpreonlybumper&cmsid=496&vid=short_onecue&correlator=");

      Integer randomNum = 0 + (int)(Math.random()*2);

      MediaItem item = new MediaItem.Builder().setUri("https://storage.googleapis.com/exoplayer-test-media-1/mkv/android-screens-lavf-56.36.100-aac-avc-main-1280x720.mkv")
      .setAdsConfiguration(new MediaItem.AdsConfiguration.Builder(Uri.parse(list.get(randomNum))).build()).build();

      playerView.getAdViewGroup().removeAllViews();
      mediaItems.clear();
      mediaItems.add(item);
      player.setMediaItems(mediaItems);
    });
```

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by marcbaechinger** [comment]
I think that works if you remove the line

```
playerView.getAdViewGroup().removeAllViews();
```

from your code. This is removing the views that have been added by the ads SDK. If you just remove this this is not working. I tried that out and this is working fine for me.

**Comment by muibungs** [comment]
> I think that works if you remove the line
> 
> ```
> playerView.getAdViewGroup().removeAllViews();
> ```
> 
> from your code. This is removing the views that have been added by the ads SDK. If you just remove this this is not working. I tried that out and this is working fine for me.

 ```
private AdsLoader getClientSideAdsLoader(MediaItem.AdsConfiguration adsConfiguration) {
    // The ads loader is reused for multiple playbacks, so that ad playback can resume.
    if (clientSideAdsLoader == null) {
      clientSideAdsLoader = new ImaAdsLoader.Builder(/* context= */ this).build();
    }
    clientSideAdsLoader.setPlayer(player);
    return clientSideAdsLoader;
  }
```

I try to reproduce step by step on example. I have to release AdsLoader and remove AdGroupview. Then I set the media item Ads control work fine is not stacking and hiding. Thanks for supporting.
