### ISSUE TITLE
AudioTrack init failed

### ISSUE THREAD

**Issue by niuyaweiqq** [google/ExoPlayer#10138]
ExoPlayer Version
  2.17.0
error info
AudioTrack init failed 0 Config(48000, 12, 144000)
AudioTrack init failed 0 Config(44100, 12, 132300)

Devices that reproduce the issue

Moto Z (2)  Android 8

One of my users often makes this error. I want to know what this error message means and how I can get more detailed error information from playbackexception？

**Comment by marcbaechinger** [comment]
Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/question.md).

**Comment by niuyaweiqq** [comment]
> 请提供问题模板中要求的完整信息。问题模板可以在[这里](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/question.md)找到。
Sorry, the following is the playing address of HLS. The timeliness is three days. If it is out of date, please contact me in time
https://autoeq.top/mov/3B20413FC76C5F432EDE85B03E8AF0A1/3B20413FC76C5F432EDE85B03E8AF0A1.m3u8?expire=1649040572&auth=748b5204acae538d2f1d116d41c1d4d9f58a92d55ab00bb82dc9989c0c02f0db

**Comment by marcbaechinger** [comment]
I'm getting a 403.

If you want us to look into this issue please [file a bug](https://github.com/google/ExoPlayer/issues/new?assignees=&labels=bug%2Cneeds+triage&template=bug.yml) and provide the information requested there. Many thanks.

**Comment by niuyaweiqq** [comment]
I'm sorry that the address has expired. The following is a new address. This time I have extended the validity period. The existing test models on my side cannot reproduce this problem, but the collected user models and data will occur frequently, so I hope You can find this problem, if you have any other questions, please feel free to reply to me, I will reply as soon as I see it, thank you again。

https://autoeq.top/mov/3B20413FC76C5F432EDE85B03E8AF0A1/3B20413FC76C5F432EDE85B03E8AF0A1.m3u8?expire=1650422385&auth=90c99d582eb5e9143c3e14e496664bfd78e77690134f170468cfcc0440461942

**Comment by niuyaweiqq** [comment]
> 我得到一个403。
> 
> 如果您希望我们调查此问题，请[提交错误](https://github.com/google/ExoPlayer/issues/new?assignees=&labels=bug%2Cneeds+triage&template=bug.yml)并提供那里要求的信息。非常感谢。



I'm sorry that the address has expired. The following is a new address. This time I have extended the validity period. The existing test models on my side cannot reproduce this problem, but the collected user models and data will occur frequently, so I hope You can find this problem, if you have any other questions, please feel free to reply to me, I will reply as soon as I see it, thank you again。

https://autoeq.top/mov/3B20413FC76C5F432EDE85B03E8AF0A1/3B20413FC76C5F432EDE85B03E8AF0A1.m3u8?expire=1650422385&auth=90c99d582eb5e9143c3e14e496664bfd78e77690134f170468cfcc0440461942
