### ISSUE TITLE
Default line value for subtitle files (.vtt) with unspecified line value

### ISSUE THREAD

**Issue by dino-saurabh** [google/ExoPlayer#10145]
Unfortunately, we can't answer all questions. Unclear questions or questions with
insufficient information may not get attention.

Before filing a question:
-------------------------

why does line param = -1 and not Cue.UNSET for any subtitle file without any line params?
i.e if any subtitle file doesn't have line param values why am I getting the line value as -1 inside the PlayerView cues.

As a result, the subtitles are rendered at the absolute bottom without any bottomPaddingFraction, though I can get over this by mutating the cues inside the PlayerView `onCues()` function or applying the bottomPaddingFraction even for -1 line value, but I wanted to know why don't we get the UNSET value instead of -1 as a default?

**Comment by icbaker** [comment]
Duplicate of #7934 - see the reasoning in https://github.com/google/ExoPlayer/issues/7934#issuecomment-694063859 for more detail about why this is intentional and imo a correct interpretation of the WebVTT spec.

**Comment by dino-saurabh** [comment]
Thanks @icbaker 👍🏼
