### ISSUE TITLE
HLS streams crashing

### ISSUE THREAD

**Issue by benderzgreat** [google/ExoPlayer#10147]
### ExoPlayer Version

2.16.1 + 2.17.1 + 2.18.0

### Devices that reproduce the issue

- ChromeCast Model GZRNL
- ANDROID TV OS VERSION: 10
- KERNEL VERSION: 4.9.180
- TV OS BUILD: QTS1.210311.036.7814738

- Fire TV Stick 4K
- Software ver = Fire OS 6.2.8.7 (NS6287/3768)
- Fire TV Home ver = 6330065.1

### Reproducible in the demo app?

Yes; 2.16.1 + 2.17.1 + 2.18.0

### Reproduction steps

Play a stream from

 any Live stream from the Pac-12 Now Android app.

*Geo-restricted to US & Canada

Pre-roll ads play, the stream will play for 30 seconds and then get stuck in a buffering loop. The same stream plays without issue on web browsers[Mac(Chrome, Firefox, Safari), Linux(Firefox, Brave), Windows(Chrome, Firefox)], iOS player, Roku, VLC on both desktop and on Android, etc. I have been able to reproduce on the demo ExoPlayer app on both ChromeCast and FireTV devices. When there are no pre-roll ads the same stream plays in ExoPlayer without any issue.

I have been trying to troubleshoot this issue for a while with no luck. There doesn't seem to be any consistent or clear error messaging. I have tried changing many different properties of the stream, and forcing software decoding with not much of a difference. It seems to have something to do with the way the decoder is reading the PTS packets.

The same stream will play on the same devices with the VLC app, so it doesn't seem to be any direct incompatibility with the stream or devices decoding ability or compatibility.

[exoplayerDemoDebug.log](https://github.com/google/ExoPlayer/files/8400509/exoplayerDemoDebug.log)

### Expected result

30s of pre-roll ads, then join live stream. 

### Actual result

Playback gets suck in a buffering loop 30 seconds after starting content.

### Media

any Live stream from the Pac-12 Now Android app.

*Geo-restricted to US & Canada

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by benderzgreat** [comment]
[p12NowFrozen4-1-1650.log](https://github.com/google/ExoPlayer/files/8400950/p12NowFrozen4-1-1650.log)
logcat associated with bugreport submitted

**Comment by benderzgreat** [comment]
I just want to point out that I have a second source(https://v-emt.pac-12.com/debug/index.m3u8) to replicate the issue, as I am going to be using the first source listed(https://dev-vod-emt.pac-12.com/p12test/index.m3u8) to test changing some more parameters.

**Comment by benderzgreat** [comment]
[timestamps4-5-22.txt](https://github.com/google/ExoPlayer/files/8420792/timestamps4-5-22.txt)
[vlcDebugging.log](https://github.com/google/ExoPlayer/files/8420793/vlcDebugging.log)


I tried playing the stream in the VLC app on the FireTV stick and it worked without any issues. I have included a logcat of those playbacks and some more failures in the ExoPlayer demo app. As well as a text file with some extra insight into the timing of the related plays.

**Comment by benderzgreat** [comment]
Seems to be related to this issue


https://github.com/google/ExoPlayer/issues/8587


but I can't seem to get any fix working.


Any help would be appreciated.

**Comment by benderzgreat** [comment]
I have created a ticket with Google Issue Tracker as well.

https://issuetracker.google.com/228596527 HLS stream crashes after pre-roll ads

**Comment by icbaker** [comment]
I played the provided stream (https://v-emt.pac-12.com/debug/index.m3u8) on a Pixel 4a and a Chromecast with Google TV and it played successfully in both cases, though I didn't see any pre-roll ads in either case.

**Comment by benderzgreat** [comment]
@icbaker 
Could you please try again?

I just played the stream 5+ times and got pre-roll ads and the failure every time.

**Comment by icbaker** [comment]
I VPN'd to the USA (by guesswork) and now I receive pre-roll ads. If there are geo-specific parts of your repro instructions it's helpful to list these explicitly, to save back and forth like this :)

I see the buffering problem on my Pixel 4a. When it occurs I notice that the playback bar in the demo app switches from showing a small number (e.g. `0:42`, i.e. 42 seconds) to a very large negative number: `-458245:59:07` with the total duration of 1 minute.

[458,245 hours, 59 minutes and 7 seconds is 1,649,685,547 seconds](https://google.com/search?q=458245+hours+59+minutes+and+7+seconds+in+seconds), which is **very** similar to the current time in seconds since the unix epoch:
```
$ date +%s
1649685830
```

Over to Christos to dig more into this with HLS expertise. @benderzgreat, just to set expectations: We may not have time to look deeper into this immediately, so please don't ping the issue frequently asking for updates. We will look at it when we have time.

**Comment by benderzgreat** [comment]
@icbaker 

Thank you for taking another look!

Apologies for assuming US location, the stream _is_ geo-restricted to US and Canada.; I will update the instructions.

Understood about expectations, I just wanted to provide as much relevant information as possible so that I am not holding things up at all by lack of information.

If I have additional information to provide as I am continuing to research the issue from my side would the preferred method of communication be the developer e-mail then? I don't mean to come across as pushy, I just don't want to waste anyone's time by leaving out any updated information.

**Comment by benderzgreat** [comment]
@christosts 
Thank you, 
I understand this is low priority bug, however I would like to give a quick update on my half to hopefully save you some time if you do have the chance to look at this issue.

I have tried testing with the 2.18.0 demo app and still got the same results.

After looking at the stream pretty thoroughly via ffprobe it seems to me like the issue that I am seeing is happening during the handling of the difference of in PTS values by the decoder, when transitioning from ad segments to the content segments. Which would line up with the previous observations regarding the playback time suddenly jumping.

>
> I see the buffering problem on my Pixel 4a. When it occurs I notice that the playback bar in the demo app switches from showing a small number (e.g. `0:42`, i.e. 42 seconds) to a very large negative number: `-458245:59:07` with the total duration of 1 minute.
> 
>          -icbaker
>

As far as I can tell on my part, the HLS is using the proper discontinuity messaging, and I am not experiencing playback issues anywhere else. Let me know if there is any more information or context I can provide.

**Comment by benderzgreat** [comment]
After troubleshooting the issue with AWS MediaTailor engineering we were able to figure out the cause of the issue was that the manifests and segments coming from the ADS did not have the PDT included. 

* message from AWS follows for anyone with the same issue
> 1. Are you using program-date-time (PDT) from your content segments?
> If yes, we have another customer who recently reported that ExoPlayer required PDT to be inserted on all contents and ad  segments. We also have configuration flags we can enable either to your full account or specific configurations.
> calculateAdSegmentPdt - writes personalized PDT values on ad segments.
> calculateCutbackSegmentPdtFromOrigin - calculates the PDT so that after the avail is over, the PDT will match what the  origin is.
