### ISSUE TITLE
10142 - Error "OMX/mediaserver died, signaling error!" in fast forward

### ISSUE THREAD

**Issue by PaganiAlejandro** [google/ExoPlayer#10142]
### ExoPlayer Version

2.15.1

### Devices that reproduce the issue

Emulador Android TV (720p)

### Reproducible in the demo app?

Not tested

### Reproduction steps

1.  Play a content, for example a movie
2. Try to fast-forward the content
3. Crash

### Expected result

1.  Play a content, for example a movie
2. Try to fast-forward the content
3. Fast-forward and continue playback

### Actual result

when doing fast forward, it stays buffering and crashes

### Media

any content for example a movie

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by marcbaechinger** [comment]
We can't provide support for emulator issues I'm afraid. 

Can you let me know if you see the same issue on a real device? If this is an issue on the emulator only, we can't help you any further.

**Comment by PaganiAlejandro** [comment]
Good afternoon. I just did some testing and it only happens on the emulator. Thanks for your help.
