### ISSUE TITLE
libyuv possibly pointing to stale repository

### ISSUE THREAD

**Issue by Brahmasmi** [google/ExoPlayer#1015]
As per instructions on https://github.com/google/ExoPlayer/tree/master/extensions/vp9, we need to use the following command to clone libyuv
```
git clone https://git.chromium.org/external/libyuv.git libyuv
```
However, as per https://code.google.com/p/libyuv/wiki/GettingStarted, we need to use the following repository,
```
git clone https://chromium.googlesource.com/libyuv/libyuv
```
This change happened via this patch https://code.google.com/p/libyuv/source/diff?spec=svn1431&r=1431&format=side&path=/wiki/GettingStarted.wiki

This is important because our current source is stale, the recent updates are in the new repository.
current repository - https://chromium.googlesource.com/external/libyuv/
new repository - https://chromium.googlesource.com/libyuv/libyuv/

We may want to update our README.

**Comment by vigneshvg** [comment]
thanks for pointing this out. i will update it.
