### ISSUE TITLE
After adding cookie value in the code it doesnt work or play the video

### ISSUE THREAD

**Issue by rraj1572** [google/ExoPlayer#10152]
### ExoPlayer Version

2.15.1

### Devices that reproduce the issue

android 10

### Reproducible in the demo app?

Not tested

### Reproduction steps

1.Play and attached media in app but didnt work

### Expected result

as all other type of streams are working so this should also work

### Actual result

doesnt work at all

### Media

![image](https://user-images.githubusercontent.com/91118622/161536861-1332aefd-82a9-4cd6-8aa8-4c159fde5748.png)

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by ojw28** [comment]
Specifying custom headers is documented [here](https://exoplayer.dev/customization.html#customizing-server-interactions).

Assuming you've already found that and it didn't help, you'll need to provide us with more useful information. A screenshot of the IDE, which doesn't show how the objects being created are actually used, is not useful. I suggest you provide us with a small patch to the demo app that adds the sample content you wish to play, and the headers that you think should allow it to be played. That would then give us something concrete to reproduce with.

**Comment by rraj1572** [comment]
Video i am trying to play this stream : https://live-cf.cdn.hotstar.com/hls/live/2027118/ipl2022/hin/1540014152/15mindvrm019692964f4f48493280ac9da8f0ea305304april2022/master_6.m3u8|Origin=https//www.hotstar.com&Referer=https://www.hotstar.com/&cookie=CloudFront-Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9saXZlLWNmLmNkbi5ob3RzdGFyLmNvbS9obHMvbGl2ZS8yMDI3MTE4L2lwbDIwMjIvaGluLzE1NDAwMTQxNTIvMTVtaW5kdnJtMDE5NjkyOTY0ZjRmNDg0OTMyODBhYzlkYThmMGVhMzA1MzA0YXByaWwyMDIyLyoiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2NDkxNjY0ODV9fX1dfQ;CloudFront-Key-Pair-Id=APKAJC3ILMJXG4AINKJA;CloudFront-Signature=NKI75lw0iTYIxGcVRkVP96urq9XpkPtIRchpkGpu7Mq4AVNxkHAv-Y4f-fv9sxSE~6dl3KyRIrSeQYy9-PEIB4z1oHZPUZ8tb7f62TJ4RTcO4gdZbLtf5tS2X9-0GxMMWjOdnA9KinKEJrdlbE1c42xjQj1hEyr7j3soR2sV7EI6dO4Acbq1T5BMpZnYSsVFncMM9Up3GgvmFRip-VTy3c-v0~-503SzJxd6-XykCNPtsYABrMgaOmfTUnekSpk41X4MSuvmW3P8bd2aOLxcxv-uikrh~RWxLKc3BCDwGQ5Lj8TQyWOVIBayMblPM8cKbNFMlIigUKeDp0G0cInK2Q

This stream include 3 values to play that is cookie value, origin value and referer value. 

As you can clearly see in my previous screenshot i have assigned cookie value, origin value and referer value  to httpdatasourcefactory and still stream is not playling.

**Comment by rraj1572** [comment]
I have one question that why am i not able to use
 httpdatasourcefactory.setRequestProperty("string","string");

In my code ??
