### ISSUE TITLE
Notification runtime permission and Exoplayer

### ISSUE THREAD

**Issue by pawaom** [google/ExoPlayer#10160]
Google Recently announced we need to add Notification runtime permission, We are developing an app using Exoplayer which uses PlayerNotificationManager 

The question is do we need modify the PlayerNotificationManager notification like ask for permissions when we use exoplayer. how do we handle the permission dialog, like if the permission is not granted etc. 

Is the permission withdrawn  after some time if the app is not used for a long time.

**Comment by OxygenCobalt** [comment]
I don't think so. The [documentation on Android 13 DP 2](https://developer.android.com/about/versions/13/changes/notification-permission#exemptions) states that notifications connected to a `MediaSession` are excluded. I'd imagine `PlayerNotificationManager` would connect itself to ExoPlayer's `MediaSession` implementation, so it should still be accepted.
