### ISSUE TITLE
StylePlayerView is not working

### ISSUE THREAD

**Issue by pmrzygweb** [google/ExoPlayer#10164]
### ExoPlayer Version

2.17.0

### Devices that reproduce the issue

Pixel 2 running Android 11

### Reproducible in the demo app?

Not tested

### Reproduction steps

PlayerView is deprecated so I replaced with StylePlayerView
This was working with PlayerView but just show empty with StyleView

### Expected result

video should play

### Actual result

show empty

### Media

mp4

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by ojw28** [comment]
The reproduction steps provided are not sufficient for us to actually reproduce the issue. `StyledPlayerView` works fine in our own demo app, so just using `StyledPlayerView` is not by itself sufficient to reproduce the problem. Please provide concrete reproduction steps if you'd like us to look at this.
