### ISSUE TITLE
How can I achieve subtitle(Closed caption) button click listener in StyledPlayerView 

### ISSUE THREAD

**Issue by ArjunPatidar-numero** [google/ExoPlayer#10167]
I'm using the StyledPlayerView and I want to store the subtitle on or off state so for that I need subtitle button click listener.
Unable to get any override method in player listener.
Here is attached screenshot where I want listener
![Screenshot_1649485381](https://user-images.githubusercontent.com/79508854/162559699-a1ea3819-59cc-4663-9000-af2d09a783d3.png)

**Comment by icbaker** [comment]
If you want to know whether a subtitle track is currently selected by the player or not, you're best off listening to track selection events, rather than trying to hook the UI components directly: https://exoplayer.dev/track-selection.html#information-about-existing-tracks
