### ISSUE TITLE
How to handle the visibility of `exo_ads_overlay` view ?

### ISSUE THREAD

**Issue by drayan85** [google/ExoPlayer#10171]
We are running some automation testing with `AdsMediaSource` to play the video.

After displaying the ads `exo_ads_overlay` exist in the view hierarchy which causing to fail some of our automation test cases.

Is there any better way to handle this?

Currently, we are hiding and enable back the visibility  of `exo_ads_overlay`  inside `AdEventListener` when `AdEvent.AdEventType.CONTENT_PAUSE_REQUESTED` and `AdEvent.AdEventType.CONTENT_RESUME_REQUESTED`

**Comment by icbaker** [comment]
Do you mean `exo_ad_overlay` (I can't find any reference to `exo_ads_overlay` in our library)?

It's obviously up to you how you test your app, but it seems like this is really a limitation of your testing process - if the test fails when `exo_ad_overlay` is present in the view hierarchy but invisible to a user, is your test reflecting a real user's experience of using your app?

**Comment by drayan85** [comment]
@icbaker 

`exo_player_overlay` view is part of   [exo_styled_player_view.xml](https://github.com/google/ExoPlayer/blob/release-v2/library/ui/src/main/res/layout/exo_styled_player_view.xml) 

(https://github.com/google/ExoPlayer/blob/a308c691d120e0b8496b2e843635edd9cc7dcef0/library/ui/src/main/res/layout/exo_styled_player_view.xml#L61)

I am just wondering if we set visibility to `exo_player_overlay` `View.VISIBLE` and `View.GONE` will cause any unknown issue during the playback

**Comment by icbaker** [comment]
Closing because we don't want to firmly guarantee that your current approach will always work. If it works for now, that's great. In general though, as I said above, the underlying issue seems to be that your tests aren't quite observing the UI in the same way a real user would - and fixing that should make this question obsolete.
