### ISSUE TITLE
player.getCurrentLiveOffset() keep changing

### ISSUE THREAD

**Issue by fgl27** [google/ExoPlayer#10170]
### ExoPlayer Version

2.17.0

### Devices that reproduce the issue

Any device tested has this issues

### Reproducible in the demo app?

Not tested

### Reproduction steps

Play a live stream and check the value of player.getCurrentLiveOffset() changing

### Expected result

the value not chaging

### Actual result

the value changes

### Media

Any live streams seems to cause this issue

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by fgl27** [comment]
I'm using `player.getCurrentLiveOffset()` to get the playback value for live streams and I have found a issue.

The initial values show a values that is the correct one or almos (+- a few ms), but the value doesn't stays constant it keeps changing for a log time, it 5min of playback the value will change 3 to 5 seconds, but this is a live stream that is playing just fine no rebuffer no slows down notting.

I did some check on how the `getCurrentLiveOffset()` fun works, and the issue seems to be on the value of `getContentPosition() `that keeps changing up or down.

Yes I know this is a live stream and the value of `getContentPosition()` will change as segments are be used and download, but this change is not the expected behavior.

The value of `getContentPosition()` start at around 5000, the it changes to 4000, 5000 or 6000 the segment size is 2000ms and I change exoplayer to update the playlist it 1000ms, but after 5min of playback the values are 9000, 10000 or 11000, it keeps like this until it settles eventually on a value of LiveOffset that is wrong.

Another test that I did was using `player.seekTo(position_ms)` to change the position, and when I do this problem will not happen, the value of `player.getCurrentLiveOffset()` will be close to the position_ms I use and the value of `getContentPosition()` will not change as before, on this case the value of `player.getCurrentLiveOffset()` it will change a little (500ms at most) for about 10 to 30s and then will stop changing and will keep the same value for as long as the stream is live and no internet issue causes a rebuffer.

I tested this on the dev branch when the head was https://github.com/google/ExoPlayer/commits/bd52b19a851cc215b2abfcfd6339bbddad6325a5

I also tested when the head was https://github.com/google/ExoPlayer/commits/bf462aca69dbd4760c39ca2910188d91610f3a16

on both cases the issues is there, I don't know when this was introduce, but I do remember not having this problem

**Comment by fgl27** [comment]
I made a video do demonstrate the issue

https://www.youtube.com/watch?v=3yXGcv8Rjkw

Latency to broadcaster on top right is `player.getCurrentLiveOffset()`

- At 27s I change the playback speed to 0.25X, at 37s I change it back to 1X.
- The latency changes from 3.5 to 10s as expected but will not stay there.
- After 4 min the value is at 3.2s and the buffer size (`player.getTotalBufferedDuration()`) also is lower by similar amount.

There is an Exoplayer functionality that changes the playback speed, for some reason without user interaction?

Because from what I see there the latency is been lowered 0.02s to 0.03s it second of playback for no reason. Making one believed that the playback speed isn’t 1X, but 1.03X or close to it.

**Second test same video**

- At 5 min I use the progress bar (`player.seekTo(position_ms)`) to change the position of the video.
- The latency changes to 13.1s.
- After 20 seconds the latency stables at 12.8s.

Here for some reason using `player.seekTo(position_ms)` no issue.

**Comment by icbaker** [comment]
Are you playing low latency live streams? If so, this is expected:
> ExoPlayer adjusts the live offset by slightly changing the playback speed. The player will try to match user and media preferences, but will also try to react to changing network conditions. 

https://exoplayer.dev/live-streaming.html#customizing-the-playback-speed-adjustment-algorithm

This used to be done for all live streams, but since https://github.com/google/ExoPlayer/commit/b09b8dc2aba5f4b54d76a0b958c62aeb5e5b8075 (included in 2.17.0) it's only applied to low latency live streams (I'll re-word the live-streaming.html page to make this distinction more clear).

**Comment by icbaker** [comment]
From [lower down that page](https://exoplayer.dev/live-streaming.html#configuring-live-playback-parameters):
> If automatic playback speed adjustment is not desired, it can be disabled by setting `minPlaybackSpeed` and `maxPlaybackSpeed` to `1.0f`.

**Comment by fgl27** [comment]
I expected that the default would always be 1.0x Speed, most important it be 1.0 right after I manually set the speed.

No this is just a regular live stream, but maybe I'm wrong **How Exo determinates if it is a low latency stream?**

I will set the default speed I never did, as I expected the default be 1.0, and I don’t know the behavior of it after the user changes the speed manually, I’ll check all that and report.

**Comment by fgl27** [comment]
Setting 

```Java
.setLivePlaybackSpeedControl(
                            new DefaultLivePlaybackSpeedControl.Builder()
                                    .setFallbackMaxPlaybackSpeed(1.0f)
                                    .build())
```

Fix the issue.

Thanks.

**Comment by fgl27** [comment]
Another test was done and I have a doubt.

When the internet connection speed is very close to the stream minimum necessary bandwidth, the player will show down the playback until the latency is 30s.

Is this expected behavior?
There is a way to prevent this?

Even with `setLivePlaybackSpeedControl` we have this issue on this case.

**Comment by icbaker** [comment]
You've only set a max speed and not a min speed, so it seems expected that the player will still slow down. From the [linked guide](https://exoplayer.dev/live-streaming.html#customizing-the-playback-speed-adjustment-algorithm):

> For example, if rebuffers occur during playback, the player will move further away from the live edge.

Note that you don't need to set the `LivePlaybackSpeedControl` to implement my suggestion from https://github.com/google/ExoPlayer/issues/10170#issuecomment-1094899159. As described in the [linked guide](https://exoplayer.dev/live-streaming.html#configuring-live-playback-parameters), you can set the min and max speeds directly on either of:
* `DefaultMediaSourceFactory` (to affect all media being played)
* The specific `MediaItem`

Customizing the `LivePlaybackSpeedControl` is arguably more 'niche' because it's [designed to control **how** the player speeds up and slows down](https://exoplayer.dev/live-streaming.html#customizing-the-playback-speed-adjustment-algorithm), but if you're trying to disable speed changing completely (by setting both min and max to 1.0) then this is irrelevant.

**Comment by fgl27** [comment]
Sory a little busy didn't not get that there was two speed option, will set both.

thanks

**Comment by dev-platong** [comment]
@fgl27 

Maybe It's too late to answer this question, but I think these lines are logic of determination (In case of HLS).

```
    boolean disableSpeedAdjustment =
        mediaItem.liveConfiguration.minPlaybackSpeed == C.RATE_UNSET
            && mediaItem.liveConfiguration.maxPlaybackSpeed == C.RATE_UNSET
            && playlist.serverControl.holdBackUs == C.TIME_UNSET
            && playlist.serverControl.partHoldBackUs == C.TIME_UNSET;
```

https://github.com/androidx/media/commit/b12918d1e6b92763c0a7b870e598d260a052361f#diff-5dc6db1044707e738c63d3d43bd22bf0951fc34af6dbfbd8b1798b6e42002a74R571-R575

Media Playlist has `EXT-X-SERVER-CONTROL` tag and its property is `HOLD-BACK` or `PART-HOLD-BACK` .

https://datatracker.ietf.org/doc/html/draft-pantos-hls-rfc8216bis#section-4.4.3.8

**Comment by icbaker** [comment]
Closing because I think the question has been answered, and I've updated the live streaming docs page to try and make this behaviour more clear (this will go live with the next library release).

**Comment by fgl27** [comment]
Thanks all for the help!
