### ISSUE TITLE
VP9 build failures

### ISSUE THREAD

**Issue by Brahmasmi** [google/ExoPlayer#1017]
Following the instructions on https://github.com/google/ExoPlayer/tree/master/extensions/vp9,
```
ExoPlayer/extensions/vp9/src/main/jni$ ./generate_libvpx_android_configs.sh "${NDK_PATH}"
```
results in the following set of errors:
ARM Section
```
...
In file included from ../../libvpx/vp9/common/arm/neon/vp9_iht8x8_add_neon.c:11:0:
android/ndk/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/lib/gcc/arm-linux-androideabi/4.8/include/arm_neon.h:32:2: error: #error You must enable NEON instructions (e.g. -mfloat-abi=softfp -mfpu=neon) to use arm_neon.h
 #error You must enable NEON instructions (e.g. -mfloat-abi=softfp -mfpu=neon) to use arm_neon.h
  ^
In file included from ../../libvpx/vp9/common/arm/neon/vp9_iht4x4_add_neon.c:11:0:
android/ndk/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/lib/gcc/arm-linux-androideabi/4.8/include/arm_neon.h:32:2: error: #error You must enable NEON instructions (e.g. -mfloat-abi=softfp -mfpu=neon) to use arm_neon.h
 #error You must enable NEON instructions (e.g. -mfloat-abi=softfp -mfpu=neon) to use arm_neon.h
  ^
In file included from ../../libvpx/vpx_dsp/arm/loopfilter_neon.c:11:0:
android/ndk/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/lib/gcc/arm-linux-androideabi/4.8/include/arm_neon.h:32:2: error: #error You must enable NEON instructions (e.g. -mfloat-abi=softfp -mfpu=neon) to use arm_neon.h
 #error You must enable NEON instructions (e.g. -mfloat-abi=softfp -mfpu=neon) to use arm_neon.h
  ^
In file included from ../../libvpx/vpx_dsp/arm/intrapred_neon.c:11:0:
android/ndk/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/lib/gcc/arm-linux-androideabi/4.8/include/arm_neon.h:32:2: error: #error You must enable NEON instructions (e.g. -mfloat-abi=softfp -mfpu=neon) to use arm_neon.h
 #error You must enable NEON instructions (e.g. -mfloat-abi=softfp -mfpu=neon) to use arm_neon.h
  ^
...
```
X86 Section
```
...
  enabling postproc
Unable to invoke compiler: gcc  -m32 -DNDEBUG -O3 -fPIC -Wall -Wdeclaration-after-statement -Wdisabled-optimization -Wpointer-arith -Wtype-limits -Wcast-qual -Wvla -Wimplicit-function-declaration -Wuninitialized -Wunused-variable -Wunused-but-set-variable -Wno-unused-function

Configuration failed. This could reflect a misconfiguration of your
toolchains, improper options selected, or another problem. If you
don't see any useful error messages above, the next step is to look
at the configure error log file (config.log) to determine what
configure was trying to do when it died.

```
The NDK version is r10e.

**Comment by vickyg3** [comment]
The ARM section errors can be ignored (we work around that by using the .neon suffix). I will take a look at the x86 section and update here when i have a fix.

**Comment by vigneshvg** [comment]
Whoops, commented from the wrong github account.

**Comment by vigneshvg** [comment]
I tried to run the script as mentioned in the instructions and it did not fail for me. Can you please attach your config.log ? It's likely that something is wrong in your build environment.

**Comment by Brahmasmi** [comment]
Yes, my build environment needed the gcc-multilib. The config.log hint was helpful. Thank you. I had run a find for config.log before posting, but had not investigated it further. It needs a "--log=yes" switch to be passed in the generate_libvpx_android_configs.sh, for the log to be output.

Now, the build fails on the next step.
```
ExoPlayer/extensions/vp9/src/main/jni$ ${NDK_PATH}/ndk-build
cat: ./libvpx_android_configs/armeabi-v7a-hard/libvpx_srcs.txt: No such file or directory
...
...
make: *** No rule to make target `libvpx_android_configs/armeabi-v7a-hard/vpx_config.c', needed by `ExoPlayer/extensions/vp9/src/main/obj/local/armeabi-v7a-hard/objs/vpx/libvpx_android_configs/armeabi-v7a-hard/vpx_config.o'.  Stop.
```
Relevant Application.mk snippet
```
APP_ABI := armeabi armeabi-v7a-hard arm64-v8a
```
The generate_libvpx_android_configs.sh script probably needs to factor in the armeabi-v7a-hard target as well.

On a related note, the instruction in the README for VP9 is:
```
cd "${VP9_EXT_PATH}"/jni && \
${NDK_PATH}/ndk-build APP_ABI=all -j4
```
However, according to http://developer.android.com/ndk/guides/application_mk.html, the APP_ABI needs to be set in the Application.mk file. The command line APP_ABI switch has no effect. This is also the case with the README for Opus. We may want to update that as well.

**Comment by vigneshvg** [comment]
The generate_android_configs.sh script not support armeabi-v7a-hard target (we only support the ones listed in README.md). So it is expected to fail. I don't know much about the armeabi-v7a-hard target and if libvpx itself supports it. (Please feel free to send a pull request if you think you can fix the script for that target :) ).

APP_ABI command line switch works. And for completeness, README also lists the alternative of declaring APP_ABI in Application.mk (Please see https://github.com/google/ExoPlayer/tree/master/extensions/vp9#building-for-various-architectures)

**Comment by Brahmasmi** [comment]
The armeabi-v7a-hard target is a recent addition to the NDK. From what I understand from http://developer.android.com/ndk/guides/abis.html#hard, it is functionally equivalent to the armeabi-v7a ABI. As regards to libvpx, I think you are right, it does not seem to support this target yet, at least based on https://github.com/webmproject/libvpx/blob/master/build/make/Android.mk, the bug list and the discussion group (No hits on "armeabi-v7a-hard"). It was wrong of me to assume that libvpx would support it. I guess the generate script changes might be less difficult, but getting libvpx to support the target seems to be the more important step.

So as to why use armeabi-v7a-hard, I am not an expert, but my earlier reading suggests that it provides performance benefits to FPU bound code. I suppose we are FPU bound in this particular instance, since I do not know whether VP9 and/or Opus have native decoding support out yet. This post is a very good read for those who understand this - http://blog.alexrp.com/2014/02/18/android-hard-float-support/ (I do not for the most part). In case you do get a chance to peruse the above post, please let me know whether it is advisable to use this target instead of the vanilla armeabi-v7a. My current assessment is that the hard target is preferable.

With respect to the APP_ABI command line switch, it only builds for the armeabi target irrespective of the switch value. The armeabi arch is the default NDK target. This suggests that the switch is being ignored. The NDK version is r10e, which I presume is the current NDK release. I may be wrong here, but probably the switch may have been supported earlier and may have changed between NDK releases.

And apologies for missing out on the Application.mk multi-arch instructions. My bad.
