### ISSUE TITLE
What's new?

### ISSUE THREAD

**Issue by master255** [google/ExoPlayer#10182]
@icbaker @ojw28 @marcbaechinger 
You change versions of the module, but you don't introduce anything new. Why are you changing versions then? For example: 2.16.0 - only some deletions of old code, bug fixes, refactoring and changes in the working logic that do not change anything.

Maybe I don't understand your version changing system? A new version is not something new to you, but just a correction of old bugs and refactoring?

I get the impression that you're just pretending to be very active, but in fact do nothing.

**Comment by icbaker** [comment]
ExoPlayer does not follow [semantic versioning](https://semver.org/). However we do generally try to increment the X of 2.X.Y when making 'disruptive' changes, while incrementing the Y for for less invasive fixes and improvements.

You can see the changes that were included in the 2.16.0 release here:
https://github.com/google/ExoPlayer/blob/release-v2/RELEASENOTES.md#2160-2021-11-04

**Comment by master255** [comment]
@icbaker I have been watching your project for many years and it has not developed at all.

In that time you could create the best media module in the world. But you don't even support many codecs.
To say nothing of development.
