### ISSUE TITLE
Trace class names are obfuscated by proguard 

### ISSUE THREAD

**Issue by stevie-patreon** [google/ExoPlayer#10197]
### ExoPlayer Version

2.16.1

### Devices that reproduce the issue

Pixel 6 running Android 12

I'm profiling my video startup time and some potentially useful trace name data from Exoplayer is proguarded away

<img width="1081" alt="Screen Shot 2022-04-18 at 17 59 42" src="https://user-images.githubusercontent.com/97045378/163884552-5ce29e15-0aae-45f1-809f-cb7cc1e2b15a.png">

The cause is the passage [here](https://github.com/google/ExoPlayer/blob/f1b37bc547e7194354fe31e240afa8a8fb0b5c6c/library/core/src/main/java/com/google/android/exoplayer2/upstream/Loader.java#L410). Class names get obfuscated away, so all the "load: " messages have no value in production.
 

### Reproducible in the demo app?

Not tested

### Reproduction steps

1. Have an app that uses exoplayer
2. Take a trace using the released version of exoplayer with proguard

### Expected result

Useful trace names

### Actual result

Obfuscated trace names

### Media

n/a

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by stevie-patreon** [comment]
If I add 

```
-keepnames class * implements com.google.android.exoplayer2.upstream.Loader$Loadable
```

to my proguard configs I get the missing class names

**Comment by tonihei** [comment]
Given that tracing is more of debug tool where you usually have the mapping file available and the number of potential loading threads is very limited/well known, I'm inclined to not fix this. As you pointed out, you can easily keep the names yourself by adding such a proguard config. But keeping the class names of all Loadable implementations seems to be unnecessary in the general case, so I'll close this issue for now.
