### ISSUE TITLE
Latency Optimization - allowChunklessPreparation for HLS content

### ISSUE THREAD

**Issue by skusuj** [google/ExoPlayer#10196]
**Question**

We are using react-native-video for video playback which on Android uses Exoplayer. We determine video playback start up time (PTFF - Play To First Frame) by capturing the moment when user clicks on play button and the moment when we receive onReadyForDisplay event from native player. To better understand where most of the time spent we further break it up as player initialization time (user click to video load start event), Video Load duration (video load start event to video load event) and player ready duration (video load event to onReadyForDisplay). As part of latency optimization we are now enabling chunkless preparation for HLS content Type.  PTFF gain we see at P90 is very minimal (10-15ms). I am wondering if the player downloads initial chunks to determine required details for preparation by default why is enabling chunkless preparation not giving good gains?

**Exoplayer Library version**: 2.11.4

**Environment info**

React Native Environment Info:
System:
OS: macOS 11.6.2
CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
Memory: 106.40 MB / 16.00 GB
Shell: 3.2.57 - /bin/bash
Binaries:
Node: 12.22.7 - ~/.nvm/versions/node/v12.22.7/bin/node
npm: 6.14.15 - ~/.nvm/versions/node/v12.22.7/bin/npm
SDKs:
iOS SDK:
Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
Android SDK:
API Levels: 29, 30, 31
Build Tools: 29.0.3, 30.0.2, 31.0.0, 32.0.0
System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
IDEs:
Android Studio: 2020.3 AI-203.7717.56.2031.7784292
Xcode: 11.6/11E708 - /usr/bin/xcodebuild
npmPackages:
react: 16.8.3 => 16.8.3
react-native: 0.59.8 => 0.59.8

**Comment by christosts** [comment]
In case you have not seen it, this [blog post](https://medium.com/google-exoplayer/faster-hls-preparation-f6611aa15ea6) contains more information on HLS chunkless preparation, how it works, and what information it checks in the playlist. It could be that the playlist is formed in a way that chunkless preparation falls back to chunkful - have you checked what is being downloaded? It would help if you can share a link to an HLS stream so we can look at the playlist. If you cannot paste links here, please send a link at dev.exoplayer@gmail.com with subject "Issue #10196" and update this issue to indicate you've done this.

Thanks

**Comment by skusuj** [comment]
Hi christosts

Yes i have gone through that blog post and since the required codec information is present in HLS manifests we are using, thought of enabling chunkless preparation for faster start up time. Added an event listener factory to httpclient builder to log http requests and i don't see any request to download chunk before video load start event irrespective of whether chunkless preparation is enabled or not.

I have shared the sample sample HLS content URL on the mail group dev.exoplayer@gmail.com.

Thanks.

**Comment by skusuj** [comment]
Hi christosts,

Could you please check and confirm if HLS video chunk is downloaded to determine CODEC info if chunkless preparation is not enabled. I have shared sample HLS video URL in the mail.

Thanks.

**Comment by christosts** [comment]
Apologies for the delayed response.  Your playlist has 1 audio track and it is muxed with video. As described in the blog post

> Streams that benefit the most are those with multiple alternative renditions, like multiple audio languages.

The playlist you supplied to us does not fall in this category, so the benefits are not great. If you use playlists with multiple audio renditions, you will see bigger improvements. 

Other than that, your playlist contains the CODEC attribute correctly and chunkles preparation works fine.
