### ISSUE TITLE
DASH: Multiple base URLs and load error reporting 

### ISSUE THREAD

**Issue by javaboboApp** [google/ExoPlayer#10191]
Hello,
In the current project I'm working on our BE returns a list of different manifest mpd's.

For example
[
   {
      manifest: "**https://...live-001.mpd**"
    },
  {
      manifest: "**https://...live-002.mpd**"
    }
]

So if for example the first manifest fails (**https://...live-001.mpd** ) we could use https://...live-002.mpd and so on (creating another mediaItem and setting this).

My concern is that every time the first element fails (live-001.mpd) Exoplayer is not aware that there is another manifest to try (another variante - **https://...live-002.mpd**) so since there is no other variant it will do many retries for each particular manifest. (3 seconds -> retry -> 2 seconds -> retry ... etc). This would be increasing the VST (video start time).

I have seen in https://github.com/google/ExoPlayer/issues/771 that dash-spec indicates that you can specify in the same manifest multiple baseUrls that exoplayer would be using as fallbacks in case one fails, something like:

variant 1 (live-001.mpd") fails (applies blacklisting logic)
try immediately
variant 2 (live-002.mpd")
.. and so on..

As you can see, I suppose that once variant 1 fails, Exoplayer will try to use variant 2 immediately, this I think improves what we currently have. My question is:

What is recommended in this case?

1) Instead of returning multiple mpds on different links, include these fallbacks in the same manifest as multiple baseUrls

2) Modify DefaulErroHandlingPolicy in order to decrease the time to retry each cdn so the VST (video start time should improve)

**Comment by marcbaechinger** [comment]
Having multiple base URLs in the manifest is the recommended way. If you have a manifest with multiple base URLs, the player can choose a fallback for loading media without reloading a new manifest but instead can just choose a new base URL for downloading media chunks.

**Comment by javaboboApp** [comment]
Nice thanks for the answer. I got another question , in the case that we use multiple base URLs: 

 If Exoplayer is playing let's say 1 CDN and this fails. Is there any way to get this information (this exception) so we could track this error to our analytic platform indicating that this CDN is not working well?

**Comment by javaboboApp** [comment]
Nice thanks @marcbaechinger  for the answer. I got another question , in the case that we use multiple base URLs: 

 If Exoplayer is playing let's say first CDN and it fails. Is there any way to get this information (this exception) so we could track this error to our analytic platform indicating that this CDN is not working well?

**Comment by marcbaechinger** [comment]
Every load error is reported to `AnalyticsListener.onLoadError(
      EventTime eventTime,
      LoadEventInfo loadEventInfo,
      MediaLoadData mediaLoadData,
      IOException error,
      boolean wasCanceled)` whether you are using multiple base URLs or not. You can add your listener with `player.addAnalyticsListener(listener)`.

**Comment by javaboboApp** [comment]
Thanks for answer @marcbaechinger  :)

**Comment by javaboboApp** [comment]
@marcbaechinger I got a quick question if it cannot return a list of CDN in the same manifest. How do you recommend me customize Exoplayer in a way that I can set a list of CDNS ? before player start.. Problem here is that we are missing blacklisting logic if player is getting a list of CDN in different links.. 

I thinking in customize DASH-MANIFEST parser and set base url there..
