### ISSUE TITLE
What's the reason behind deprecating/removing onPlayerStateChanged()?

### ISSUE THREAD

**Issue by greypins** [google/ExoPlayer#10203]
We're in the process of migrating away from deprecated methods in ExoPlayer 2.16.1, and noticed all our usages of `AnalyticsListener`:
```
override fun onPlayerStateChanged(
        eventTime: EventTime,
        playWhenReady: Boolean,
        playbackState: Int
) {
   // do stuff based on playbackState and playWhenReady
}
```
Will need to be migrated as such:
```
private var playWhenReadyState: Boolean? = null
private var playbackState: Int? = null

override fun onPlayWhenReadyChanged(
        eventTime: EventTime,
        playWhenReady: Boolean,
        reason: Int
) {
    playWhenReadyState = playWhenReady
    handlePlayerStateChanged(eventTyime, playWhenReadyState ?: return, playbackState ?: return)
}

override fun onPlaybackStateChanged(
        eventTime: EventTime,
        state: Int
) {
  playbackState = state
  handlePlayerStateChanged(eventTyime, playWhenReadyState ?: return, playbackState ?: return)
}

private fun handlePlayerStateChanged(
        eventTime: EventTime,
        playWhenReady: Boolean,
        playbackState: Int
) {
   // do stuff based on playbackState and playWhenReady
}
```

Is this the correct approach to both 1) persisting our existing implementation and 2) reproducing the original `onPlayerStateChanged` implementation?

Also curious around the reasoning behind this method's deprecation since it's impacted a lot of our logging setup. Is there perhaps another method we should be relying on similar to `onPlayerStateChanged` but under a different interface/API?

Thanks!

**Comment by marcbaechinger** [comment]
The reasoning is to consistently have a one callback for each property of the `Player`.

For your use case you can look into [`onEvents(Player, Events)`](https://github.com/google/ExoPlayer/blob/release-v2/library/common/src/main/java/com/google/android/exoplayer2/Player.java#L637) and check whether the events [`EVENT_PLAYBACK_STATE_CHANGED`](https://github.com/google/ExoPlayer/blob/release-v2/library/common/src/main/java/com/google/android/exoplayer2/Player.java#L1317) or `EVENT_PLAY_WHEN_READY_CHANGED` are contained in the events object.

**Comment by greypins** [comment]
Gotcha. Makes sense.

Thanks for the alternative, we'll look into that method.

**Comment by yoobi** [comment]
Hello, just to be sure the correct/recommended way to replace `onPlayerStateChanged` is by overriding `onEvents` ? Or Is it still okay to override `onPlayWhenReadyChanged` if I'm only doing stuff when player is ready ?

**Comment by tonihei** [comment]
It's definitely okay to just use `onPlayWhenReadyChanged` if you are only interested in these changes.

It's also worth noting that are no player commands that can change both states (`playbackState` and `playWhenReady`) at the same time, so there will always be one change or the other anyway unless you make multiple player calls together.
