### ISSUE TITLE
Unable to play 2 videos simultaneously 

### ISSUE THREAD

**Issue by RakshithGB** [google/ExoPlayer#10211]
This issue is related to #9360 . However I'm able to play video on both views on my device but just not simultaneously. By default both players are set to auto-play and only the second player starts playing while the first is paused. At any given instant I can have only one active video player while the other is in a paused state, whichever I tap play on the other automatically goes to pause. The scrubbing (seek) feature seems to work on the paused video while the playing video is running. I used the same repository mentioned in that issue to debug this, re-linking the repo [here](https://github.com/dogtim/ExoPlayer/tree/feature/twoPlayer) again for reference. The `demo` example is the one with 2 views, it has the `DoublePlayerActivity.java` file in it.

I even tried to hardcode another video url for second instance thats using a different codec, eventhough in this case they are 2 separate codecs being used I still couldn't achieve simultaneous playback.

My questions:
1) Is it possible to play both the videos simultaneously and of the same codec? (They need not be in sync, one can start even x seconds after the other)
2) If yes, based on the example mentioned in the link am I missing something?

Any help is much appreciated.

**Comment by marcbaechinger** [comment]
It may be that the two players compete for the same audio focus. So each time you start one player the other player looses the audio focus and pauses. You should be to see this in the logs if you have `EventLogger` in place (which is the case for the demo project).  Filter logcat for `playbackSuppressionReason` or 'TRANSIENT_AUDIO_FOCUS_LOSS' to find the line in question. You can listen to this event yourself by adding your own `Listener` and overriding the `onPlaybackSuppressionReasonChanged` callback:

```
default void onPlaybackSuppressionReasonChanged(
        @PlaybackSuppressionReason int playbackSuppressionReason) {}
```

> Is it possible to play both the videos simultaneously and of the same codec?

Given the device provides more than a single instance for a given codec this is possible.

> If yes, based on the example mentioned in the link am I missing something?

In your sample project you have turned on audio focus handling on line 333 of the [DoublePlayerActivity](https://github.com/dogtim/ExoPlayer/blob/feature/twoPlayer/demos/main/src/main/java/com/google/android/exoplayer2/demo/DoublePlayerActivity.java#L333).

**Comment by RakshithGB** [comment]
Thank you so much! Setting the focus to `false` on both solved it.

**Comment by marcbaechinger** [comment]
Cool!

Please be aware that in this case you should [manage audio focus](https://developer.android.com/guide/topics/media-apps/audio-focus) on your own to behave in a way that does not annoy your users. Your users for instance expect that you stop playback when other apps start playing audio. If you don't do that it is likely that your users may be at least confused and they may uninstall your app for such reasons or give you low ratings.

I'm closing this issue. Please re-open if you think this is required.
