### ISSUE TITLE
How to add videoListener in v2.16.0

### ISSUE THREAD

**Issue by huaxiaxueyuan** [google/ExoPlayer#10216]
I updated the com.google.android.exoplayer2.video version from 2.11.3 to 2.16.0, but I can not found com.google.android.exoplayer2.video.VideoListener .

Is there any new methods to replace videoListener in v2.16.0 ？

**Comment by marcbaechinger** [comment]
From the [RELEASENOTES.md for 2.16.0](https://github.com/google/ExoPlayer/blob/release-v2/RELEASENOTES.md#2160-2021-11-04):

```
Remove `SimpleExoPlayer.addVideoListener`, `removeVideoListener` and `VideoListener`. 
Use `Player.addListener` and `Player.Listener` instead.
```

You should find the callbacks you used with `VideoListener` in `Player.Listener` starting from 2.16.0. If this is not the case please re-open this issue and add some details on what you are looking for so I can help some further.
