### ISSUE TITLE
WiKo device support

### ISSUE THREAD

**Issue by fguinet** [google/ExoPlayer#1022]
Hi, 
none of the ExoPlayer version I have tested, included the latest 1.5.1, have support on WiKo manufacturer device (e.g. WIKO CINK PEAX 2 Version 8 - Android 4.1.2, but on many other WiKo devices as well).
I don't understand how this could be possible as those devices should have pass through the Google CTS with success.
Is there a way to resolve this issue in the coming ExoPlayer version ?
Should that be impossible, we will be forced to move to another player because there are many customers with such device in our country and a lot of them are complaining ? 
You initially said that YouTube is using ExoPlayer, do you know the kind of workaround use for such device ?  

Many thanks for your help and answers,

FG

**Comment by ojw28** [comment]
We tested on a WIKO CINC FIVE V8 device and experienced similar issues. Unfortunately, we do not have a workaround. Please report the issue to the device manufacturer. Thanks!

**Comment by ojw28** [comment]
YouTube most likely fall back to Android's MediaPlayer API on the affected devices.
