### ISSUE TITLE
How to show track selector dialog item in separate dialog

### ISSUE THREAD

**Issue by Programmingtimes** [google/ExoPlayer#10239]
in exoplayer i use track selection dialog where it shows video, audio and cc in same dialog as tab and viewpager format but i want them to show in seperate dialog like 
button 1 = TRACK_TYPE_VIDEO;
button2 =TRACK_TYPE_TEXT
button 3 = TRACK_TYPE_AUDIO
can you help me to acheve this feature
current coding 
          ```
   MappingTrackSelector.MappedTrackInfo mappedTrackInfo;
                DefaultTrackSelector.Parameters parameters = trackSelector.getParameters();
                TrackSelectionDialog trackSelectionDialog =
                        TrackSelectionDialog.createForTrackSelector(
                                trackSelector,
                                dismissedDialog -> {
                                });
                trackSelectionDialog.show(getSupportFragmentManager(), null);
```

**Comment by ojw28** [comment]
I will leave this open for a few weeks in case anyone wants to help, but since it's more just a request for help with your own application development, it's not within scope for what we have capacity to help with directly.

**Comment by Programmingtimes** [comment]
thankyou. but i hope this  also will be helpful for other global exoplayer developers around the universe.
