### ISSUE TITLE
AAPT: error: resource android:attr/lStar not found.

### ISSUE THREAD

**Issue by smmousavi8872** [google/ExoPlayer#10232]
### ExoPlayer Version

2.17.1

### Devices that reproduce the issue

Hi and thank you very much for the great effort you have taken to implement such useful library.
The issue that I have been confronting since adding exoplayer dependency is a compile time error stating that : `.gradle\caches\transforms-3\5f3469f77d0052e094da22be022a7a67\transformed\core-1.7.0\res\values\values.xml:105:5-114:25: AAPT: error: resource android:attr/lStar not found.`, not allowing the project to build. 
I have taken below actions to solve the issue but non were conclusive:
1. downgraded all `androidx.core:core-ktx:+` dependencies to 1.6.0 version 
2. downgraded all `androidx.appcompat:appcompat:+` dependencies to 1.3.0 version 

I truly don't know what to do more, please help.

### Reproducible in the demo app?

No

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by marcbaechinger** [comment]
I'm not sure if this is about the same but I think I had a similar issue when migrating an app from an old ExoPlayer version to a recent one. 

As far as I remember I solved this by upgrading all (`androidx`) dependencies to to most recent version, setting the compileApiVersion to 32 and also by upgrading gradle and the gradle plugin to the most recent version possible (see this [commit](https://github.com/android/tv-samples/commit/77861558ecf4a2eb251220b08e5e0f59feef9af4)).

Can you check whether this helps for your case if you have't done so.

**Comment by smmousavi8872** [comment]
Thank you very much for your attention, I eventually managed to solve this issue by adding the snippet code below to my main module Gradle file inside the `android` block: 
```
configurations.all {
        resolutionStrategy.eachDependency { details ->
            def requested = details.requested
            if (requested.group == "androidx.appcompat") {
                if (requested.name == "appcompat") {
                    details.useVersion "1.3.1"
                }
            }
            if (requested.group == "androidx.core") {
                if (requested.name == "core" || requested.name == "core-ktx") {
                    details.useVersion "1.6.0"
                }
            }
        }
    }
```
I added this into the main module of my project on which all other modules depend. I also added `exoplayer` dependencies into the main module `dependencies` block.
