### ISSUE TITLE
Allow a play/stop action as an alternative to play/pause

### ISSUE THREAD

**Issue by lostchopstik** [google/ExoPlayer#10235]
### Use case description
Our streams are all live streams so we prefer not to allow pausing of the stream so that if they want to stop, they will need to reconnect to the live stream. Currently there is no way to show only a `play` button and no way to show `stop` in compact view.

### Proposed solution
Implement a compact-view compatible `setUsePlayStopAction(boolean)`

### Alternatives considered
Alternatives could be allowing a play button by itself and a stop button which is allowed to be added to the compact view

PS - Also curious if there is currently a built-in way for custom actions to be shown in compact view? This would at least solve the problem for now

**Comment by marcbaechinger** [comment]
I think your use case can be done with the API available.

> if there is currently a built-in way for custom actions to be shown in compact view

You can override `PlayerNotificationManager.getActionIndicesForCompactView()` to define the indices of buttons to be shown in compact view. If you are using a `CustomActionReceiver`  that should work for custom actions as well.

An alternative is to intercept the call to play and call stop instead:

```
ForwardingPlayer forwardingPlayer = new ForwardingPlayer(player) {
  @Override
  public void play() {
    super.stop();
  }
};

playerNotificationManager.setPlayer(forwardingPlayer);
```

You can override the icons of the button as described in the class level JavaDoc of `PlayerNotificationManager`.

**Comment by lostchopstik** [comment]
@marcbaechinger thanks for the tips! I was able to use the ForwardingPlayer and a custom icon to get the effect that I was going for.

**Comment by fourofspades** [comment]
Please note:  intercepting the call to play and call stop, if you have Android Auto or Automotive support will result in your app being rejected from the Google Play app store.

You should seekTo(0) to throw away the buffer.  This is the correct solution.   There are however some issues with the amount of buffer that's being downloaded and then discarded.    See here (Solution 2):   https://github.com/androidx/media/issues/146

**Comment by marcbaechinger** [comment]
I'm closing this as it is not the right thing to do generally. Please also not the comment from above about not doing this for Android Auto. Thanks for the heads-up fourofspades!
