### ISSUE TITLE
attempt playing DASH stream throws EOFException

### ISSUE THREAD

**Issue by j-garin** [google/ExoPlayer#1023]
I am building a video streaming app and have bumped into the issue.
When i attempt streaming a MPEG-DASH video,  SampleSourceTrackRenderer throws an EOFException in line 154. Please help me resolve it.

Here's the link to the video i'm attempting to play:
http://download.tsi.telecom-paristech.fr/gpac/dataset/dash/uhd/dashevc-ondemand-4s/dashevc-ondemand-4s.mpd

The screenshot with debug view is attached. 
![screenshot](https://cloud.githubusercontent.com/assets/9943889/11589357/8b3bff86-9a90-11e5-9115-341763a7f901.png)

**Comment by ojw28** [comment]
The SegmentBase elements in the manifest are incorrect (i.e. the ranges they specify don't exactly match the media). For example the first video representation has in the manifest:

```
<SegmentBase indexRangeExact="true" indexRange="1007-1470">
    <Initialization range="0-1006"/>
</SegmentBase>
```

But from manual inspection, the correct ranges look like they should be:

```
<SegmentBase indexRangeExact="true" indexRange="1016-1471">
<Initialization range="0-1015"/>
</SegmentBase>
```
