### ISSUE TITLE
ExoPlaybackException Source error

### ISSUE THREAD

**Issue by cbazalduaDev** [google/ExoPlayer#10240]
### ExoPlayer Version

2.17.1

### Devices that reproduce the issue

Xiaomi MiA2
Pixel 2
Samsung s22

### Reproducible in the demo app?

Yes

### Reproduction steps

1. pass a m3u8 link and you gonna recive this error 

### Expected result

Play media item

### Actual result

the playback crashes 

### Media

example link 
(with this link the error comes)
https://ipstori.xyz/api/v1/audio/a51b24b4-b6bc-4dac-95be-5951fa1b4efa.m3u8
https://ipstori.xyz/api/v1/audio/a51b24b4-b6bc-4dac-95be-5951fa1b4efa.m3u8/3D5aErvzJhwbsbnR-m3u8_0_1000.m3u8

(this link works well)
https://ipstori.xyz/api/v1/audio/4a193fed-f65c-4853-98b9-4cef5fadab47.m3u8
https://ipstori.xyz/api/v1/audio/4a193fed-f65c-4853-98b9-4cef5fadab47.m3u8/0Bpu2tkHKIRXErN6-m3u8_1_1000.m3u8

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by ojw28** [comment]
It's actually https://ipstori.xyz/api/v1/audio/a51b24b4-b6bc-4dac-95be-5951fa1b4efa.m3u8/3D5aErvzJhwbsbnR-m3u8_2_1000.m3u8 that causes the issue. The end of the media playlist is malformed. If you open it in a text editor, you'll see there's an `EXT-X-KEY` line near the end where the URI is missing (whereas on all other `EXT-X-KEY` lines, the URI is properly specified. This is what causes the failure:

```
#EXT-X-KEY:METHOD=AES-128,URI=""
```
