### ISSUE TITLE
Player not parsing Clearkey license acquisition url.

### ISSUE THREAD

**Issue by sr1990** [google/ExoPlayer#10246]
### ExoPlayer Version

2.17.1

### Devices that reproduce the issue

Pixel 5

### Reproducible in the demo app?

Yes

### Reproduction steps

Added
```
      {
        "name": "CLEARKEY (cenc)",
        "uri": "https://media.axprod.net/TestVectors/v7-MultiDRM-SingleKey/Manifest_1080p_ClearKey.mpd",
        "drm_scheme": "clearkey"
      },
```
to media.exolist.json.

Works if I specify the drm license uri
```
      {
        "name": "CLEARKEY (cenc)",
        "uri": "https://media.axprod.net/TestVectors/v7-MultiDRM-SingleKey/Manifest_1080p_ClearKey.mpd",
        "drm_scheme": "clearkey",
        "drm_license_uri": "https://drm-clearkey-testvectors.axtest.net/AcquireLicense"
      },
```

### Expected result

The media plays successfully.

### Actual result

Playback crashes with the following error: 
E/EventLogger: playerFailed [eventTime=4.38, mediaPos=0.00, window=0, period=0, errorCode=ERROR_CODE_DRM_LICENSE_ACQUISITION_FAILED

One workaround is 
in DashManifestParser.java
1. in parseContentProtection(), 
- add the case to parse clearkey
```
case "urn:uuid:e2719d58-a985-b3c9-781a-b030af78d30e":
          uuid = C.CLEARKEY_UUID;
          schemeType = "clearkey";
          break;
```
    
-  Parse the clearkey url in the same method
```
if (XmlPullParserUtil.isStartTag(xpp, "clearkey:Laurl")) {
        if (xpp.next() == XmlPullParser.TEXT) {
          licenseServerUrl = xpp.getText();
        }
 } 
```
 
2. In parseAdaptationSet(), after line 416 while parsing the Content Protection, add

```
     } else if (XmlPullParserUtil.isStartTag(xpp, "ContentProtection")) {
        Pair<String, SchemeData> contentProtection = parseContentProtection(xpp);
        if (contentProtection.first != null) {
          drmSchemeType = contentProtection.first;
        }
        if (contentProtection.second != null) {
          if (drmSchemeType != null && drmSchemeType == "clearkey") {
            // update the license url of cenc
            for (int i = 0;i<drmSchemeDatas.size();i++) {
              if (drmSchemeDatas.get(i).uuid == C.COMMON_PSSH_UUID &&
                  drmSchemeDatas.get(i).licenseServerUrl == null)
                drmSchemeDatas.get(i).licenseServerUrl = contentProtection.second.licenseServerUrl;
            }
          }
          drmSchemeDatas.add(contentProtection.second);
        }
```

Please let me know what you think OR if I am missing anything.
Thanks.

### Media

https://media.axprod.net/TestVectors/v7-MultiDRM-SingleKey/Manifest_1080p_ClearKey.mpd

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by tonihei** [comment]
I think the content is configured as expected (see https://github.com/google/ExoPlayer/issues/3138#issuecomment-320247142 as a verification that both `ContentProtection` tags are expected, and https://github.com/Dash-Industry-Forum/dash.js/issues/3343 for another example where parsing the license url is requested).

And the proposed solution also looks sensible to me. Would you be willing to send a PR with the suggested changes? 

I'll mark the issue as an enhancement in the meantime (because it's not a bug, more a new feature to detect Clearkey LicenseURLs).

**Comment by tonihei** [comment]
This is now supported after merging a modified version of  #10260.

**Comment by sr1990** [comment]
Thanks @tonihei !
