### ISSUE TITLE
byteArray Stream

### ISSUE THREAD

**Issue by Mostafa24sd** [google/ExoPlayer#10259]
how can i stream video from byteArray source?
```
fun streamVideoListener(videoFrames: ByteArray){
        // receiving H.264 frames every 100ms.
}
```
I tried FFmpeg library. merged 100 frames and make few seconds video and add it to exo playlist. but performance is not good at all.

**Comment by tonihei** [comment]
You probably need to write your own `DataSource` to support this. Please have a look at #8125 or #8051 where similar questions have been asked before.
