### ISSUE TITLE
How to restart playback on getting AudioSink exceptions (e.g. WriteException), blacklisting the track that the exception was thrown for.

### ISSUE THREAD

**Issue by ggabdol** [google/ExoPlayer#10257]
When playback is failed with PlaybackException caused by any AudioSink exceptions, I'd like to restart the failed playback, blacklisting the track that the exception was thrown for. My question is, how can I find the audio track that had the problem of AudioSink exceptions from the TracksInfo when selecting audio tracks?

I found that ExoPlaybackException has [rendererFormat](https://github.com/google/ExoPlayer/blob/f1b37bc547e7194354fe31e240afa8a8fb0b5c6c/library/core/src/main/java/com/google/android/exoplayer2/ExoPlaybackException.java#L95) that seems to be the audio format that I need to blacklist, but I am not sure how to find this format from MappedTrackInfo when initially selecting audio track for the restarted playback.
I could navigate through MappedTrackInfo and try to find the format from the exception by calling equals() like this:
`formatFromException.equals(formatFromMappedTrackInfo)`, but it would work if the two formats are exactly same. I could use format.id, but it's not guaranteed that the id is always available from our playlists.

The question is more like finding a format that is held and used by a Renderer from TrackSelector. I would appreciate for an advice on that problem.

**Comment by icbaker** [comment]
I don't really understand the question. You're looking for a way to match up two `Format` that might be similar, but not identical - and yet you can't rely on `Format.id` (which is sort of designed for this situation). It's not clear to me how the library could implement your 'similar but not identical' logic if you're not able to implement it yourself?

**Comment by ggabdol** [comment]
Thanks for your reply @icbaker. Let me take an example to elaborate what I am trying to do.

Let's say I got an audio format being rendered by calling [ExoPlayer.getAudioFormat()](https://github.com/google/ExoPlayer/blob/f1b37bc547e7194354fe31e240afa8a8fb0b5c6c/library/core/src/main/java/com/google/android/exoplayer2/ExoPlayer.java#L1387), and another audio format from TracksInfo by calling:
```kotlin
player.currentTracksInfo
.trackGroupInfos.first { trackGroupInfo -> trackGroupInfo.trackType == C.TRACK_TYPE_AUDIO }
.trackGroup.getFormat(1)
```
This is a screenshot showing the comparison between the two formats that are supposed to be the same.
<img width="898" alt="FormatComparison" src="https://user-images.githubusercontent.com/2120203/168876292-2d1af036-ff18-46a7-8618-52875c3461b5.png">

As you can see their IDs are the same, but they are not equal, meaning the following is false.
```java
formatBeingRendered.equals(formatFromTracksInfo) // false
```

However, `Format.id` is annotated as `@Nullable`, so I am not sure if I could rely on only `Format.id` to identify a format for finding a track from the track list, because it is nullable, and there could be more than one format that has the same ID but from multiple different track groups, for example, Format(id = "0") in TrackGroup A and Format(id = "0") in TrackGroup B.

So, what is the typical way in ExoPlayer of finding a matching track format used by a renderer in the tracks that are available from TracksInfo? I hope my question makes sense for you now.

**Comment by icbaker** [comment]
@tonihei do you have a suggestion for updating the player's track selection to block the 'current' adaptively selected track in response to an error without needing to hunt through all the tracks for the track that 'matches' the `Format` from the renderer exception?

**Comment by tonihei** [comment]
I think generally we aim to use the same `Format` everywhere so that `formatBeingRendered.equals(formatFromTracksInfo)` is always true.

However, there are some technical issues with that when using HLS because either video and audio are muxed together, or the full information isn't know when publishing the `TracksInfo`.  But in the rendering pipeline, the samples for audio and video are split up and use their own respective `Format` with additional details. That's why these `Formats` are not generally `equal` to each other. 
I believe HLS formats have an `id` in all cases though, so if you know you are playing HLS, you should be fine comparing the `Format.id` values.

**Comment by ggabdol** [comment]
Thanks for the confirmation. @tonihei Yes, we are using only HLS stream at the moment. I will assume `id` is effectively `@NonNull` and use it for the comparison of formats.
