### ISSUE TITLE
Replacement for buildAudioProcessor

### ISSUE THREAD

**Issue by hhdsyxwei** [google/ExoPlayer#10253]
In DefaultRenderersFactory in version 2.11.8 there was a function that is buildAudioProcessor(), I call it by :
@OverRide
protected AudioProcessor buildAudioProcessor() {
return new AudioProcessor[]{recording, speedChange};
}
and return an AudioProcessor but when I upgrade exoplayer 2.17.1 , This function no longer exists. Is there any method or function in java that I can replace this?

**Comment by tonihei** [comment]
There is a method called `buildAudioSink` you can use instead. The easiest way is to copy the [default implementation](https://github.com/google/ExoPlayer/blob/r2.17.0/library/core/src/main/java/com/google/android/exoplayer2/DefaultRenderersFactory.java#L614) and then call `setAudioProcessors` on the `DefaultAudioSink.Builder`.

**Comment by hhdsyxwei** [comment]
would u please show me some code
