### ISSUE TITLE
No video only audio is playing

### ISSUE THREAD

**Issue by arunkumartdr** [google/ExoPlayer#10252]
**No video only audio is playing**

But works in Mxplayer SW decoder 

m3u8 link  with user agent : [ the below link will expire ]
```
http://31.172.87.52:2200/R-EX/SPORTS_STAR_SPORTS_TAMIL-in/tracks-v1a1/mono.m3u8?token=RED_z5owTAh2p_jPM283Dq1EbA==,1652304993.9359072311|User-agent=REDLINECLIENT
```

How to solve this issue in Exoplayer/ How to implement SW decoder in Exoplayer ?

**Comment by marcbaechinger** [comment]
```
curl --verbose "http://31.172.87.52:2200/R-EX/SPORTS_STAR_SPORTS_TAMIL-in/tracks-v1a1/mono.m3u8?token=RED_z5owTAh2p_jPM283Dq1EbA==,1652304993.9359072311|User-agent=REDLINECLIENT"
```

Gives a 403 so we don't have access to the media. Can you please check?

**Comment by arunkumartdr** [comment]
The problem is with source not in exoplayer , Thanks
