### ISSUE TITLE
No audio in a mp4 file with AAC

### ISSUE THREAD

**Issue by gupta-sachin** [google/ExoPlayer#1025]
I tried an mp4 video file on few android devices, the video is fine but there is no audio. This same file is being played with audio in other player apps on same devices.

This was tested on Android 4.4 and 6.0 with ExoPlayer 1.5.2. I will mail the sample file to olly [dot] exoplayer [at] gmail [dot] com with a link to this issue.

Thanks

**Comment by ojw28** [comment]
It appears this issue is already fixed in the dev branch, so the fix will make it into the next release.

**Comment by gupta-sachin** [comment]
Can you please give any ETA for next release. In case if its not supposed to be soon, please suggest the minimum code changes that I could do to fix it as for product stability concerns, we do not want to take complete dev branch. 

Thanks.
