### ISSUE TITLE
how to configure the buffer time about vast ad video to lower the startup time

### ISSUE THREAD

**Issue by Jacko07** [google/ExoPlayer#10263]
hi,  how to configure the buffer time about vast ad video to lower the startup time, thanks.

**Comment by icbaker** [comment]
Hi! Please provide complete information as requested in the question template. The template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/question.md).

Unfortunately we can't answer unclear questions or those with insufficient information.
