### ISSUE TITLE
CBCS scheme support for under android 25

### ISSUE THREAD

**Issue by shimiuh** [google/ExoPlayer#10264]
[From the documentation:](https://exoplayer.dev/supported-devices.html)
"DASH (Widevine CENC; “cbcs” scheme) | 7.1 | 25"
Is there a plan in the near future to support CBCS scheme on android 21? Or is it a hardware problem that will never get fixed?

**Comment by icbaker** [comment]
This is a limitation of the android platform, so there's nothing we can do in the library to work around it: https://developers.google.com/widevine/drm/overview#supported_encryption_schemes
