### ISSUE TITLE
ForwardingPlayer.setPlayWhenReady is not being called

### ISSUE THREAD

**Issue by nandovelazquez** [google/ExoPlayer#10268]
From migrating a `DefaultControlDispatcher` to `ForwardingPlayer`, do I need to implement something else besides only creating an instance of the `ForwardingPlayer` class? Because I'm not getting called the method `setPlayWhenReady` from the `ForwardingPlayer` but other methods are called as `getPlayWhenReady` and `isPlaying`, for example.

This is reproducible in the ExoPlayer Demo app v2.17.1 by just passing a `ForwardingPlayer` object to the `playerView` object through the method `setPlayer()`

Thank you!

**Comment by marcbaechinger** [comment]
The `PlayerControlView` is using `player.play()` and `player.pause()` which is delegated by the `ForwardingPlayer` to the wrapped `Player`. Then the wrapped player is calling `setPlayWhenReady(true|false)` but not on the `ForwardingPlayer` but internally on itself.

So you can intercept these calls by overriding `play()` and `pause()` of your `ForwardingPlayer`.

**Comment by nandovelazquez** [comment]
Thanks for the quick response!

The methods `play()` and `pause()` work. It might be helpful if that behavior is somewhere in the documentation for future references.

Thanks again.

**Comment by marcbaechinger** [comment]
We added a section about 'ForwardingPlayer' to the developer guide that will be published with the next release.
