### ISSUE TITLE
Exoplayer Extensions In Chromecast

### ISSUE THREAD

**Issue by jeprojects** [google/ExoPlayer#1026]
Is it possible to use the Exoplayer extensions  (https://github.com/google/ExoPlayer/tree/master/extensions) in a ChromeCast receiver?

**Comment by ojw28** [comment]
As far as I know Chromecast receiver applications are written in Javascript? In which case the answer is no, since ExoPlayer is written in Java for Android.

**Comment by jeprojects** [comment]
The chromecast can do Mpeg Dash, so I assume it is ExoPlayer it is using for the mediaplayer?

The receiver application is written in javascript, but I believe it is accessing ExoPlayer somehow on the chromecast.

**Comment by ojw28** [comment]
I don't think that's the case.
