### ISSUE TITLE
Method to disable sequential playback on MediaSource level

### ISSUE THREAD

**Issue by tosam144** [google/ExoPlayer#10262]
I am looking for a way to disable sequential playback of mp3s on `MediaSource` level (of course, the MediaSource in my case is a `ConcatenatingMediaSource`). I know about the method `setPauseAtEndOfMediaItems` on exoplayer level. But this disables sequential playback for ALL media sources used by exoplayer. I would like to disable sequential playback on one `MediaSource` while enable it on another `MediaSource`. Is there something like `MediaSource.setPauseAtEndOfMediaItems` ? Thank you!

**Comment by marcbaechinger** [comment]
There is no API for this I'm afraid, but I think implementing this with the existing API is straightforward.

You can listen to `Player.Listener.onMediaItemTransition(mediaItem, reason)` then look at the media item and set `pauseAtEndOfMediaItems` accordingly.

Would that work?

**Comment by tosam144** [comment]
Excellent, @marcbaechinger: thank you. That works perfectly indeed.
