### ISSUE TITLE
Customizable background for PlayerView

### ISSUE THREAD

**Issue by Jerinji2016** [google/ExoPlayer#10271]
I have an issue while rotating the screen in lower android version.
A black box appears while rotating. This seems to be because of background color in xml. It would be great if it could be configured.

**Comment by ojw28** [comment]
Please could you clarify what you're asking for. What do you want to be able to configure, and what do you expect the behavior to be on the affected device after you apply this configuration?

**Comment by Jerinji2016** [comment]
Im using exoplayer to play a video in an activity,
Every time I rotate the device the playerView is also rotated, before the video could load a black background is shown.
This seems to look odd. The issue mainly seen in lower end devices like zebra and motorola.

I gone through the package and seems like an xml is setup for background for the playerView and the default color for that is black. Could this be customizable?
