### ISSUE TITLE
Exoplayer freezes in buffering whem stream live (HLS)

### ISSUE THREAD

**Issue by huongnv251291** [google/ExoPlayer#1027]
Hi
I use Exoplayer for stream live. Some time it freezes on buffering and not change to Ready. I must use method seekto(0) in onstatechange  for continue load video. But with slow conection it will be loop in last chuck. Pls tell me How to fix it

**Comment by pajatopmr** [comment]
You might try applying PR#948.  I would be curious to know if this solves
your problem.  It solved a similar sounding problem for me.

On Sun, Dec 6, 2015 at 9:26 PM huongnv251291 <notifications@github.com>
wrote:

> Hi
> I use Exoplayer for stream live. Some time it freezes on buffering and not
> change to Ready. I must use method seekto(0) in onstatechange for continue
> load video. But with slow conection it will be loop in last chuck. Pls tell
> me How to fix it
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/ExoPlayer/issues/1027>.
>
-- 
-pmr

**Comment by huongnv251291** [comment]
thank for rep but your solution not work with me. After start video in secound buffering my exoplayer freezes in buffering, if in onStateChanged when buffering i set seekto(0) it can pass easy. but slow conection be loop in last chuck

**Comment by tungds** [comment]
I got the same problem in live stream. I bug in library and Exo freezes in buffering because Exo can't switch bitrate from lowest to higher.
You can paste the following code in to getChunkOperation method in HLSChunkSource class. This code works fine for me :
```
if (live) {
      if (previousTsChunk == null || switchingVariantSpliced) {
        chunkMediaSequence = getLiveStartChunkMediaSequence(nextVariantIndex);
      } else {
        chunkMediaSequence = switchingVariantSpliced
            ? previousTsChunk.chunkIndex : previousTsChunk.chunkIndex + 1;
        if (chunkMediaSequence < mediaPlaylist.mediaSequence) {
          // TODO: Decide what we want to do with: https://github.com/google/ExoPlayer/issues/765
          // if (allowSkipAhead) {
          // If the chunk is no longer in the playlist. Skip ahead and start again.
          chunkMediaSequence = getLiveStartChunkMediaSequence(nextVariantIndex);
          liveDiscontinuity = true;
          // } else {
          //   fatalError = new BehindLiveWindowException();
          //   return null;
          // }
        }
      }
    } 
```

Hope this help!

**Comment by huongnv251291** [comment]
Thank Tungns so much. I try your solution and test it on 3G and wifi it really. I hope on slowconnection it will not be loop agian.

**Comment by gergely-sallai** [comment]
I seem to have the same issue, when I start playing a live HLS and stop the player then start it a second time, exoplayer seem to buffer for ages. Sometimes it starts after like 20 seconds, sometimes it's 5 minutes. When the player is stuck at buffering all I can see in the logs that HLS chunks are downloading (starting and completing download successfully).

If i call a `seekTo(0)` on the player the stream starts **instantly**.
Also Tungds's previous answer doesn't seem to solve the issue entirely (maybe it's stuck for less time when that suggestion is applied, I'm not sure).

Could anyone provide some information what could be the problem here? I'm reporting this from **r1.5.3**, and tried the above suggestion on current master, commit: 3f5096f.

**Comment by tungds** [comment]
Hi gergely-sallai,

About Exo player freezes in bufferring, I guess Exo can't change bitrate. With my problem, I see my sequence ts chunks length in m3u8 file are difference. Thus, I guess when Exo player switches from lowest bitrate to higher, it miss some informations and it freezes.

**Comment by gergely-sallai** [comment]
Hi all, I've been investigating today.

The issue only appeared when `exoPlayer.stop()` was called, and then after some time `exoPlayer.start()` is called on a live HLS. As I mentioned in my previous comment a `seekTo(0)` seems to solve the issue. So I put this seek call in my `stop()` method.
So it looks like this:
```
public void stop() {
    exoPlayer.stop();
    exoPlayer.seekTo(0);
}
```
This solved my problem, it works perfectly now.

**Comment by tungds** [comment]
You shouldn't call exoplayer.stop() to stop player. You should call releaseplayer() to stop player, then to start again playerposition = 0 and preparePlayer(true).
Thanks!

**Comment by ojw28** [comment]
Please file a new issue including _all_ of the information requested in the issue template if this is still a problem in v1.5.10 or later. Thanks!
