### ISSUE TITLE
NPE in DashManifestParser:ParseAudioChannelConfiguration caused by old MPD file

### ISSUE THREAD

**Issue by nicolas400-bd** [google/ExoPlayer#10272]
### ExoPlayer Version

2.17.0

### Devices that reproduce the issue

Tablet Inspire 5

### Reproducible in the demo app?

No

### Reproduction steps

Our Movies App uses a local storage server to provide MPD files to the users.

### Expected result

The movie plays

### Actual result

The NPE crashed the App

### Media

Small portion of MPD /xml file with the problem: (see missing attribute schemeIdUri in AudioChannelConfiguration tag) 
```
<Representation xmlns="urn:mpeg:dash:schema:mpd:2011" audioSamplingRate="48000" bandwidth="228917" codecs="mp4a.40.2" id="audio-en-US-mp4a" height="0">
        <BaseURL>media-audio-en-US-mp4a.mp4</BaseURL>
        <AudioChannelConfiguration xmlns="urn:mpeg:dash:schema:mpd:2011"></AudioChannelConfiguration>
        <SegmentBase xmlns="urn:mpeg:dash:schema:mpd:2011">
          <Initialization range="0-1502" />
        </SegmentBase>
      </Representation>
```
      
      
      
Correct MPD /xml file for the same movie: (see AudioChannelConfiguration tag)

```
<Representation audioSamplingRate="48000" bandwidth="228917" codecs="mp4a.40.2" id="audio-en-US-mp4a">
        <AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2" />
        <BaseURL>media-audio-en-US-mp4a.mp4</BaseURL>
        <SegmentBase indexRange="1503-35926">
          <Initialization range="0-1502" />
        </SegmentBase>
      </Representation>

```

In a previous version of the library (2.9.5) the lines in the function parseAudioChannelConfiguration() were completely different, and in that case, if the element doesn't have the attribute: schemeIdUri, it will return _Format.NO_VALUE_

But in the actual version the function use : _Switch_ statement, and the result of this line:
`String schemeIdUri = parseString(xpp, "schemeIdUri", null);`
returns a "null", so the switch statements crash.

Although the MPD file is "incorrect", in the previous version of the library, it works.

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by icbaker** [comment]
The DASH spec is pretty clear in ISO 23009-1 section 5.8.1 and 5.8.2 that every descriptor element (of which `AudioChannelConfiguration` is one) requires a `@schemeIdUri` attribute.

ExoPlayer doesn't generally aim to support invalid media - you should fix the media to comply with the spec.
