### ISSUE TITLE
Include "the SDK-generated session ID for the current ads session, as initiated by a stream request." within onAdsManagerLoaded's  AdsManagerLoadedEvent object.

### ISSUE THREAD

**Issue by EugenioLopez1** [google/ExoPlayer#10284]
### [REQUIRED] Use case description
Currently, I do not see a reliable way to map a adsLoader.requestStream(stream) execution, to its respective response. 

This issue becomes apparent in the following scenario: 
- User selects content, initiating a stream request. 
- Before onAdsManagerLoaded is triggered(in my testing this has taken all the way up to 7 seconds but usually takes around 750ms to 2000ms), User backs out and selects another content, thus initiating another stream request on the same adsLoader and same StreamManager instance.
- onAdsManagerLoaded is then triggered twice, one for each stream request. 

Being able to map which stream request onAdsManagerLoaded is being called for would be extremely beneficial in these circumstances. 

Currently, adsLoader returns a **new** "SDK-generated session ID" every time .requestStream() is fired. However, I see no utility for this, as the "SDK-generated session ID" is not returned back within onAdsManagerLoaded, and is not available via Charles when combing through the pubads request/response or any other IMA related network traffic. 

adsLoader.requestStream's "SDK-generated session ID" also does **not** match the "sid" session-ID available in charles, which adds to further moot point. 

### Proposed solution
Include the "SDK-generated session ID" returned from adsLoader.requestStream() within onAdsManagerLoaded's  AdsManagerLoadedEvent object. This way, mapping streamIDs returned from the AdsManagerLoadedEvent object is made reliably possible, and the client side is able to perform any kind of logic which keeps record of ongoing streamRequests which have not yet returned a response.

**Comment by tonihei** [comment]
I'm not sure if we are the right recipient for this request? We only call `adsLoader.requestStream` within our newly added IMA-DAI extension and I don't see how these callbacks are ambiguous given they are encapsulated without our class. 

Did you mean to file a feature request for IMA directly? If not, please clarify how you interact with our player and/or the IMA extension, thanks!

**Comment by EugenioLopez1** [comment]
@tonihei You're correct, I'll raise this with IMA. Thank you.
