### ISSUE TITLE
About number of decoded frame rate

### ISSUE THREAD

**Issue by javaboboApp** [google/ExoPlayer#10282]
Hi all, 
I would like to know if we can calculate the number of decoded frames when using Exoplayer. 

Thanks.

**Comment by christosts** [comment]
I'm assuming you're talking for video frames.

You need to get a reference to the [`DecoderCounters`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/decoder/DecoderCounters.html) which contains this information. Please read through the class' javadoc to see which fields you need your app. `queuedInputBufferCount` holds the number of frames sent to the decoder and `renderedOutputBufferCount` holds the number of frames sent to the screen (the two counters may not match).

 You can get the reference to the `DecoderCounters` either by attaching an `AnalyticsListener` ([documentation](https://exoplayer.dev/analytics.html)) and overriding [`AnalyticsListener.onVideoEnabled`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/analytics/AnalyticsListener.html#onVideoEnabled(com.google.android.exoplayer2.analytics.AnalyticsListener.EventTime,com.google.android.exoplayer2.decoder.DecoderCounters)) or by calling [`ExoPlayer.getVideoDecoderCounters`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/ExoPlayer.html#getVideoDecoderCounters()). The same instance is being updated by the player. Make sure to call [`DecoderCounters.ensureUpdated()`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/decoder/DecoderCounters.html#ensureUpdated()) before reading from this instance.

You can see an example how the demo app displays the number of decoded frames [here](https://github.com/google/ExoPlayer/blob/r2.17.1/library/core/src/main/java/com/google/android/exoplayer2/util/DebugTextViewHelper.java#L146).

The same structure is used for audio frames, and you can get a reference to the audio-related `DecoderCounters` with `AnalyticsListener.onAudioEnabled()` or `ExoPlayer.getAudioDecoderCounters()`
