### ISSUE TITLE
What's the reasoning behind most default implementations being attributed as `final`?

### ISSUE THREAD

**Issue by greypins** [google/ExoPlayer#10283]
Hello!

My team's looking into overriding a couple methods in a majority of the provided classes (such as `OkHttpDownloader` or `DefaultPlaybackSessionManager`) and were curious about the reasoning behind making these implementations `final` as it prevents us from both extending and overriding methods for minor tweaks.

Currently we can either fork the class implementation or the entire repo and expose these classes publicly, both solutions we're not a huge fan of since we don't want to diverge from any updates/improvements to the underlying ExoPlayer library. We noticed classes like `OkHttpDataSource` and `DefaultTrackSelector` are not final (which is great!), why are other implementations designated with `final`?

What's the methodology on deciding which classes should not be extended by consumers?

Thanks!

**Comment by christosts** [comment]
It's matter of design principles and, to my knowledge, for Java it's best described in [Effective Java](https://www.oreilly.com/library/view/effective-java/9780134686097/), chapters 18 & 19. Please refer to this book for a thorough explanation and reasoning.

Briefly, we try to make all our classes final unless we have good reasons that an app using the player will benefit by subclassing a specific class. In that case, we try to implement the class to be ready for inheritance as much as possible. That said, it doesn't mean we always get it 100% right :) You may find classes in the player codebase that are non-final but should be, or that they are not documented accurately for inheritance. Still, that's our overall intention.
