### ISSUE TITLE
Does HLS and DASH not support gapless transition between two media items/sources?

### ISSUE THREAD

**Issue by ashutoshgngwr** [google/ExoPlayer#10288]
Hi there!

I am trying to achieve a gapless transition between multiple HLS/DASH audio-only media items. I am queuing two media items to the playlist. When ExoPlayer transitions from one media item to another, there's a little glitch in the playback. I am not sure if this is by design, limitation or a bug.

I have set up a [minimal demo project](https://github.com/ashutoshgngwr/exoplayer-demo) with a [single activity](https://github.com/ashutoshgngwr/exoplayer-demo/blob/main/app/src/main/java/io/github/ashutoshgngwr/exoplayerdemo/MainActivity.kt) to demonstrate this. The demo is using the 2.17.1 release. All three encodings, DASH, HLS and MP3, have the same source. I used FFMPEG to generate these.

```kt
// DASH
exoPlayer.addMediaItem(MediaItem.fromUri("https://cdn.trynoice.com/public/dash/white_noise_white_noise/index.mpd"))
exoPlayer.addMediaItem(MediaItem.fromUri("https://cdn.trynoice.com/public/dash/white_noise/index.mpd"))

// HLS
// exoPlayer.addMediaItem(MediaItem.fromUri("https://cdn.trynoice.com/public/hls/white_noise_white_noise/index.m3u8"))
// exoPlayer.addMediaItem(MediaItem.fromUri("https://cdn.trynoice.com/public/hls/white_noise/index.m3u8"))

// Progressive
// exoPlayer.addMediaItem(MediaItem.fromUri("https://cdn.trynoice.com/public/white_noise_white_noise.mp3"))
// exoPlayer.addMediaItem(MediaItem.fromUri("https://cdn.trynoice.com/public/white_noise.mp3"))

exoPlayer.playWhenReady = true
exoPlayer.prepare()
```

### Observations

- There's **a noticeable glitch** when the **DASH** media item transitions from one to another.
- There's **a noticeable glitch** when the **HLS** media item transitions from one to another.
- There's **no glitch** when **progressive** (MP3) media item transitions from one to another.

### Other variations

- I tried to change the audio codec of HLS/DASH streams from AAC to MP3, but I ended up with the same result.
- Both MPEG-TS and FMP4 containers in HLS streams produced the same result.
- Using a `ConcatenatingMediaSource` instead of two media items also produced the same result.

### Other related issues

- https://github.com/google/ExoPlayer/issues/6953
- https://github.com/google/ExoPlayer/issues/5500

**Comment by ashutoshgngwr** [comment]
I tried progressive media with AAC codec in a MP4 (M4A) container. There's a noticeable glitch during the media item transition. I am guessing it is a codec limitation and not necessarily an ExoPlayer issue.

**Comment by tonihei** [comment]
> All three encodings, DASH, HLS and MP3, have the same source.

They may have all the same source, but the output is definitely different. The relevant difference is that the mp3 files define gapless metadata that allows us to play them gapless, whereas the other two streams have no gapless metadata resulting in an audible transition between the tracks.
