### ISSUE TITLE
No sound for MPEG TS stream

### ISSUE THREAD

**Issue by jacktech24** [google/ExoPlayer#1029]
Hi,
I have problem playing TS video stream (with audio) as on some devices, there is no audio, only video. The video codec detected by VLC is MPEG-1/2 Video for video and MPEG Audio layer 1/2 for audio stream. Here is an example I prepared for you so you can test it http://home.pilsfree.net/jacktech24/ct24.ts

**Comment by jacktech24** [comment]
To provide more information, my code for initialization:
```kotlin
        var allocator = DefaultAllocator(BUFFER_SEGMENT_SIZE);

        // Build the video and audio renderers.
        var uri = Uri.parse(url)
        Timber.i("channel uri: $uri")
        var bandwidthMeter = DefaultBandwidthMeter(getMainHandler(), null);
        var dataSource = DefaultUriDataSource(mContext, bandwidthMeter, getUserAgent());
        var sampleSource = ExtractorSampleSource(uri, dataSource, allocator,
                BUFFER_SEGMENT_COUNT * BUFFER_SEGMENT_SIZE);
        var videoRenderer = MediaCodecVideoTrackRenderer(mContext,
                sampleSource, MediaCodec.VIDEO_SCALING_MODE_SCALE_TO_FIT, 5000, getMainHandler(),
                this, 50);
        var audioRenderer = MediaCodecAudioTrackRenderer(sampleSource,
                null, true, getMainHandler(), this, AudioCapabilities.getCapabilities(mContext));

        // Invoke the callback.
        var renderers = arrayOf<TrackRenderer>(videoRenderer, audioRenderer);
```

**Comment by ojw28** [comment]
- Few Android devices support H262 video, which this sample contains, so you're pretty lucky that you're even seeing video on whatever test device you're using. It's not required for Android devices to support this format, and many do not.
- The audio is audio/mpeg-L2, for which I believe the same applies.

Supported underlying formats can be found [here](http://developer.android.com/guide/appendix/media-formats.html). For maximum compatibility, you should really be using AAC audio and H264 video.
