### ISSUE TITLE
How to detect if external device is HDCP enabled before switching playback to the connected device

### ISSUE THREAD

**Issue by krackjack234** [google/ExoPlayer#10294]
Question
-------------------------

We want to know if exoplayer can detect an externally connected cable/device as HDCP enabled and then either switch to HD video or disable rendering if not supported.

We have seen below code to detect HDCP

```

  try {
      // Get an instance of the MediaDrm from the device
      MediaDrm mediaDrm = new MediaDrm(Constants.WIDEVINE_UUID);

      // Create a new DefaultTrackSelector.ParamsBuilder object
      DefaultTrackSelector.ParametersBuilder builder = new DefaultTrackSelector.ParametersBuilder(this);

  // Call this method to enable rendition switching across DASH AdaptationSets
      builder.setAllowMultipleAdaptiveSelections(true);

      // Get the values for hdcpLevel and maxHdcpLevel
      String connectedHdcpLevel = mediaDrm.getPropertyString("hdcpLevel");
      String maxHdcpLevel = mediaDrm.getPropertyString("maxHdcpLevel");
      Log.v(TAG, "HDCP Level: " + connectedHdcpLevel + " Max HDCP Level: " + maxHdcpLevel);

      // If either level is null or an empty String or reads "Unprotected"
      if ((TextUtils.isEmpty(connectedHdcpLevel) || TextUtils.isEmpty(maxHdcpLevel)) ||
              ("Unprotected".equals(connectedHdcpLevel) || "Unprotected".equals(maxHdcpLevel))) {
          Log.v(TAG, "Restricting rendition selection to SD");

          // Set the max video size to SD
          builder.setMaxVideoSizeSd();
      }

  // Create a new DefaultTrackSelector object, and set the Parameters object created above
      DefaultTrackSelector defaultTrackSelector = new DefaultTrackSelector(this);
      defaultTrackSelector.setParameters(builder.build());
      // Set this DefaultTrackSelector object on the ExoPlayerVideoDisplayComponent
      videoDisplayComponent.setTrackSelector(defaultTrackSelector);
  }
  catch (Exception exception) {
      if (exception instanceof UnsupportedSchemeException) {
          Log.e(TAG, "UnsupportedSchemeException: " + exception.getLocalizedMessage());
      }
      else {
          Log.e(TAG, "An unexpected error occurred: " + exception.getLocalizedMessage());
      }
  }
        
   
```

We want to know the following

1. How will the player detect if an external device is HDCP enabled when a user switches playback from one device to another after starting playback?

2. In case the player detects the newly connected device and finds it as non-HDCP compliant, is there any way to restrict rendering to SD without re-creating the track selector?

**Comment by christosts** [comment]
I believe the platform's [MediaDrm#getConnectedHdcpLevel()](https://developer.android.com/reference/android/media/MediaDrm#getConnectedHdcpLevel()) is what you need (also discussed in #8923). 

I think that covers your question and I will close this issue, but feel free to re-open if I missed something.

[edit/update]

> How will the player detect if an external device is HDCP enabled when a user switches playback from one device to another after starting playback?

I don't think the player handles HDCP levels itself and let's the app handle this.

> In case the player detects the newly connected device and finds it as non-HDCP compliant, is there any way to restrict rendering to SD without re-creating the track selector?

You can call [Player.setTrackSelectionParameters()](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/Player.html#setTrackSelectionParameters(com.google.android.exoplayer2.trackselection.TrackSelectionParameters)) and set new track selection parameters directly without creating a track selector instance.
