### ISSUE TITLE
Selected speed option is not identified by TalkBack

### ISSUE THREAD

**Issue by hshapley** [google/ExoPlayer#10298]
### ExoPlayer Version

2.17.1

### Devices that reproduce the issue

All devices tested so far: Pixel 2 XL (Android 11), Pixel 4 (Android 12), OnePlus Nord CE 2 Lite

### Reproducible in the demo app?

Not tested

### Reproduction steps

1. Enable TalkBack on the device
2. Open a video in ExoPlayer
3. Open the controls and select Settings, then Speed
4. Listen to the announced selection, and swipe through to "Normal"

### Expected result

- Normal should have focus by default
- TalkBack should read "Normal - Selected" or "Normal - Checked"

### Actual result

- The lowest speed option has focus by default
- When focus is moved to the selected option (Normal), it says "Normal - Double tap to activate". Which is incorrect, because it is already selected.

### Media

https://www.sample-videos.com/video123/mp4/480/big_buck_bunny_480p_2mb.mp4

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by christosts** [comment]
I can see this also occurs on the demo app. @icbaker will you able to take a look whether there is something in the UI elements that need to change?

**Comment by tonihei** [comment]
Fixed by the commit above.
