### ISSUE TITLE
Document ChunkSampleSource constructor parameters

### ISSUE THREAD

**Issue by abhiguru** [google/ExoPlayer#1030]
https://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer/chunk/ChunkSampleSource.html

public ChunkSampleSource(ChunkSource chunkSource,
                 LoadControl loadControl,
                 int bufferSizeContribution,
                 Handler eventHandler,
                 ChunkSampleSource.EventListener eventListener,
                 int eventSourceId)

Can someone tell me what does the last param "eventSourceId" stand for ? The DASH RendererBuilder is using DemoPlayer.TYPE_VIDEO ... how does eventSourceId map to TypeVideo integer value ? 

What I cant wrap my head around is how does eventSource maps to the integer values of TYPE_VIDEO or TYPE_AUDIO ?

**Comment by ojw28** [comment]
If you look in the [source code](https://github.com/google/ExoPlayer/blob/master/library/src/main/java/com/google/android/exoplayer/chunk/ChunkSampleSource.java) you'll see that this parameter is only used when invoking methods on the eventListener (it's basically just passed as the ID to the eventListener methods). We should improve the documentation for the ChunkSampleSource constructors.

**Comment by abhiguru** [comment]
got it, thanks for the update! New to Android and Java in general.
