### ISSUE TITLE
How can I set DataSpec.FLAG_ALLOW_GZIP for a fragment of an m3u8 video?

### ISSUE THREAD

**Issue by casolorz** [google/ExoPlayer#10313]
I'm having an issue with a video server that always sends a `gzip` response even if `identity` was passed for `Accept-Encoding`. 

I got it to work for the m3u8 manifest by manually setting the header to accept `gzip` but when ExoPlayer requests the fragment, it still sends `identity`. 

I looked at the ExoPlayer code and on `OkHttpDataSource` there is this piece of code:

    if (!dataSpec.isFlagSet(DataSpec.FLAG_ALLOW_GZIP)) {
          builder.addHeader(HttpHeaders.ACCEPT_ENCODING, "identity");
    }

So where do I set `dataSpec` so that I can allow `gzip` for loading fragments?

**Comment by ojw28** [comment]
> I got it to work for the m3u8 manifest by manually setting the header to accept gzip but when ExoPlayer requests the fragment, it still sends identity.

I'm not really sure what you mean by this. If the server is already sending a `gzip` response even if it wasn't requested, why does having ExoPlayer request a `gzip` response change anything? I also think ExoPlayer should already be allowing m3u8 manifests to be gzipped, by default. This happens [here](https://github.com/google/ExoPlayer/blob/r2.17.1/library/hls/src/main/java/com/google/android/exoplayer2/source/hls/playlist/DefaultHlsPlaylistTracker.java#L699) and [here](https://github.com/google/ExoPlayer/blob/r2.17.1/library/hls/src/main/java/com/google/android/exoplayer2/source/hls/playlist/DefaultHlsPlaylistTracker.java#L135), where in both cases the constructor that's called sets the appropriate flag [here](https://github.com/google/ExoPlayer/blob/r2.17.1/library/core/src/main/java/com/google/android/exoplayer2/upstream/ParsingLoadable.java#L112). Please could you clarify what you mean exactly?

For actual media segments, that sounds quite broken from the server-side. I'd suggest you contact whoever is responsible for the server and ask them to fix it.

**Comment by casolorz** [comment]
Let me see if I can explain the issue better. 

First let's ignore the manifest, that part seems to work fine, the issue is the segment request. 

OkHttp on [BridgeInterceptor.kt](https://github.com/square/okhttp/blob/5c62ed796d05682c969b2636d3419b5bc214eb11/okhttp/src/jvmMain/kotlin/okhttp3/internal/http/BridgeInterceptor.kt#L70) sets a `transparentGzip` flag only if `Accept-Encoding` is `null` and if it isn't a `Range` request. 

The `transparentGzip` flag is required for OkHttp to do transparent unzipping of the stream. Does ExoPlayer depend on transparent unzipping being provided by OkHttp? Or does ExoPlayer unzip the stream?

The server I'm trying to play a video from, even if you send `identity` for `Accept-Encoding`, it will respond with `Content-Encoding: gzip` but OkHttp will not do transparent unzipping because `identity` was used for `Accept-Encoding`.

I have zero control over the server, this is for a generic video player. 

I have made it all work by creating my own interceptor that injects `Accept-Encoding` as `gzip`. But ideally I should just be able to control the headers that are used when requesting segments. 

Hope that makes more sense.

**Comment by ojw28** [comment]
> Does ExoPlayer depend on transparent unzipping being provided by OkHttp?

Yes.

> The server I'm trying to play a video from, even if you send identity for Accept-Encoding, it will respond with Content-Encoding: gzip but OkHttp will not do transparent unzipping because identity was used for Accept-Encoding.

Understood; thanks for the clarification!

> I have zero control over the server, this is for a generic video player. I have made it all work by creating my own interceptor that injects Accept-Encoding as gzip. But ideally I should just be able to control the headers that are used when requesting segments.

If you accept gzip as an encoding for segments, isn't that potentially going to degrade performance when streaming from some  server(s) other than the one for which you're trying to fix this problem? Are you planning to apply your modification only for the specific server that you know to be problematic? It's a bit unclear what your proposed solution is that's going to solve the problem without introducing new problems elsewhere.

> So where do I set dataSpec so that I can allow gzip for loading fragments?

To answer your specific question, I think you could probably extend `OkHttpDataSource`, override `open` and have it build a new `dataSpec` with the added flag before passing it to `super.open`. You can do that with:
```
dataSpec.buildUpon().setFlags(flags | FLAG_ALLOW_GZIP).build();
```
Would that work for you?

**Comment by casolorz** [comment]
> If you accept gzip as an encoding for segments, isn't that potentially going to degrade performance when streaming from some server(s) other than the one for which you're trying to fix this problem? Are you planning to apply your modification only for the specific server that you know to be problematic? It's a bit unclear what your proposed solution is that's going to solve the problem without introducing new problems elsewhere.


The first solution I tried is to always add `Accept-Encoding` as `gzip`, I haven't seen any performance degradation. Are you saying it will degrade performance because there isn't much of a point on gzipping an already compressed video segment? 

My next attempt at fixing this might be to just add an interceptor that always does transparent unzipping if it detects the `Content-Encoding: gzip` header. I already had one for another server that always returned `brotli` compression. I will just have to test this a lot to make sure there aren't other issues. 

> To answer your specific question, I think you could probably extend OkHttpDataSource

I hadn't thought of this. That will probably also work. Thank you.

**Comment by ojw28** [comment]
> Are you saying it will degrade performance because there isn't much of a point on gzipping an already compressed video segment?

Yes. Gzipping media segments probably also has some negative impact on startup latency, because I think the client will need to download more of the first segment up-front before it can start playback. I'm not certain about this though!

On the plus side, a well configured server will likely avoid gzipping a media segment even if the client says that it will accept it, because the server should know that it's not useful to do so. I would guess most of the big cloud providers do this, provided they can infer the MIME type of the files being hosted. You'd have to do a bit of research to be sure! This might be why you don't see performance degradation in practice. We have definitely seen servers that don't do this though, and _will_ gzip media segments. This is why we explicitly request `identity` encoding (to stop servers from doing that).

**Comment by casolorz** [comment]
It all makes a lot more sense now, thank you for the extra info. I'll either add gzip only for that server or implement further transparent unzipping.
