### ISSUE TITLE
OkHttp extension ships with a ProGuard rule that breaks newer versions of OkHttp

### ISSUE THREAD

**Issue by Stonos** [google/ExoPlayer#10310]
### ExoPlayer Version

2.17.1

### Devices that reproduce the issue

All

### Reproducible in the demo app?

Not tested

### Reproduction steps

1. Add the following to your `build.gradle` file:
```groovy
implementation 'com.squareup.okhttp3:okhttp:5.0.0-alpha.7'
implementation 'com.google.android.exoplayer:extension-okhttp:2.17.1'
```
2. Add the following code somewhere:
```kotlin
PublicSuffixDatabase.get().getEffectiveTldPlusOne("example.com")
```
3. Compile a release version of the app with `minifyEnabled true`

### Expected result

`getEffectiveTldPlusOne` should return `example.com`.

### Actual result

`getEffectiveTldPlusOne` crashes with the following exception: 

```
java.lang.IllegalStateException: Unable to load PublicSuffixDatabase.gz resource from the classpath.
        at okhttp3.internal.publicsuffix.PublicSuffixDatabase.a(SourceFile:501)
```

This happens because of this consumer rule that ships with the OkHttp extension: https://github.com/google/ExoPlayer/blob/c3866449e248bb7e7fce6c78b51f4960e14a0c91/extensions/okhttp/proguard-rules.txt#L8

It probably stopped working due to this change in OkHttp: https://github.com/square/okhttp/pull/6974/

### Media

N/A

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by marcbaechinger** [comment]
Thanks for reporting.

I can repro this behaviour with the steps from above. I can also confirm that removing the mentioned line from the proguard rules solves the problem. It seems to work with `4.9.0` as well when I remove this line.

I'm not sure why we had this line actually. We followed the advice on the okhttp README at that time when it has been added.

Will check with okhttp folks.

**Comment by marcbaechinger** [comment]
This page suggests we can just remove our proguard config at least for gradle: https://square.github.io/okhttp/features/r8_proguard/

**Comment by Stonos** [comment]
Thanks for taking a look!

I think that it should be safe to delete the `proguard-rules.txt` file from the extension, since nowadays OkHttp is bundled with [its own rules](https://github.com/square/okhttp/blob/master/docs/features/r8_proguard.md) which should get picked up by R8.

> I'm not sure why we had this line actually. We followed the advice on the okhttp README at that time when it has been added.

I believe that this is because at the time OkHttp didn't have embedded rules. The extension's rules were added on [2018-04-03](https://github.com/google/ExoPlayer/commit/783a1b74e3c642efd1427375f71b1e8976c498b5), and OkHttp's rules were added on [2018-06-15](https://github.com/square/okhttp/commit/a16ec15ee08424058b26c6bd62afc98b32df98bc).

**Comment by yschimke** [comment]
Yep - please remove any lines related to OkHttp from your file.

Basically since 3.11.0 our advice has been to rely on the embedded rules. So we stripped out all the other rules, and have taken advantage of that when moving files around.

**Comment by ponthamaya** [comment]
@marcbaechinger any update on this?

**Comment by nuclearmagneton** [comment]
Any update on this?

**Comment by marcbaechinger** [comment]
Sorry, I haven't reference the commit in this issue. This landed on dev-v2 with this change:
https://github.com/google/ExoPlayer/commit/759de7d6120b5cfd4f5198122c1217ab05c0aade

I'm closing this issue. Please let me know if you think there is something missing. Thanks.
