### ISSUE TITLE
What means BUFFER_SEGMENT_SIZE and BUFFER_SEGMENTS in HlsRendererBuilder

### ISSUE THREAD

**Issue by tungds** [google/ExoPlayer#1031]
Hi,
I use Exo for nDVR HLS. My stream server using token to protect content and each token only exist for 2 minutes. I got the error "Response code 403" after play for 3 minutes. I check in HlsChunkSource class. I see Exo read all segment from chunklist many times for 5s~ 10s and then don't read. When Exo play for 2 minutes, I see Exo read all segment again a get the error " Response code 403". I guess   afer Exo read all segment to load data to buffer, it doesn't keep connect to server. So when Exo request to server again for next data, it got the error because token was dead. I decrease the BUFFER_SEGMENT_SIZE = 8 * 1024 instead 64 * 1024 and the error doesn't happend.

My stream server using 2 bitrate 450000 and 600000 so I want to understand What means BUFFER_SEGMENT_SIZE  and BUFFER_SEGMENTS to config two parameters to my application working fine.

Thanks!

**Comment by ojw28** [comment]
Isn't it a design flaw that your server decides the token is dead in this case? Why does the token have such a short lifespan? Fill/drain (i.e. filling a buffer, then not requesting any data for a while whilst the buffer is draining, then filling again) is a legitimate buffering strategy. Tokens should remain valid for a long enough period of time to accommodate such a strategy.

**Comment by ojw28** [comment]
To answer the question, the total buffer size (in bytes) is BUFFER_SEGMENT_SIZE multiplied by BUFFER_SEGMENTS. You're basically just making the buffer smaller by decreasing either of those values, which means the drain part of the fill/drain buffering cycle will be smaller; probably small enough such that the token doesn't become invalid. However the client will also have a smaller buffer if you do this, which makes re-buffering more likely to occur.

**Comment by tungds** [comment]
Thank for clearly answer. I understand them.
