### ISSUE TITLE
Android TV - 360 Videos - Explore video

### ISSUE THREAD

**Issue by nikolmamai** [google/ExoPlayer#10315]
While at mobile devices I could explore 360 videos either with touch or gyroscope, I am not able to do the same at android tv boxes. Youtube handles this case of exploring video with arrow buttons of D-PAD. I wonder if there is an ExoPlayer implementation of doing this or if they have made their own implementation.

Thank you in advance!

**Comment by ojw28** [comment]
Currently, you have to implement this yourself. Thanks!
