### ISSUE TITLE
Download never start on emulator

### ISSUE THREAD

**Issue by ChenLauter** [google/ExoPlayer#10312]
When I try to start a download with DownloadService.sendAddDownload(), I can received the callback on onDownloadChanged(), the download.state isDownload.STATE_QUEUED.But it never changed the state to STATE_DOWNLOADING or STATE_FAILED, it just  did nothing.The device is an android emulator, Pixel 5 API 30.How can I go next with it?

By the way, the download program can work on physical devices ......

**Comment by ojw28** [comment]
I tried reproducing this using our [demo app](https://exoplayer.dev/demo-application.html), and downloading worked fine for me (also using a Pixel 5 API 30 emulator). Does it reproduce for you with the demo app? If so, please provide more detailed and concrete reproduction steps. Thanks!

**Comment by vishnuchilakala** [comment]
Check if you are adding the requirement https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/scheduler/Requirements.html#DEVICE_STORAGE_NOT_LOW and if you are, removing it might fix this.

@ojw28  I have also encountered the same i.e. when the player think that the device storage is "low" and the requirement `DEVICE_STORAGE_NOT_LOW` is applicable, the download will forever stay in Queued state and never fail. It resumes when the available storage becomes "not low".

**Comment by ojw28** [comment]
Ah. That's a bit confusing, although if the emulator is indicating low storage then that would be working as intended from ExoPlayer's perspective.
