### ISSUE TITLE
MPEG-DASH MPD file not playable on ExoPlayer

### ISSUE THREAD

**Issue by Faiz786-Hp-rgb** [google/ExoPlayer#10311]
Hi everyone, I have developed a 360-degree video player for android to play tile-based adaptive DASH MPD files using ExoPlayer on our android application. I am facing a problem in playing the video that I have tiled using the Kvazaar encoder and repackaged it using the MP4Box. When I stream the MPD file on the application, the media controller shows that the file is being played but the screen is blank.
We have checked the player for bitrate adaptive MPD files and it works fine. Can anyone suggest what needs to be done to play the tile-based adaptive MPD file?

I am attaching the APK for the application and the MPD file with all its segments for reference

[Tiling (2).zip](https://github.com/google/ExoPlayer/files/8814723/Tiling.2.zip)
[app-debug.zip](https://github.com/google/ExoPlayer/files/8814747/app-debug.zip)
.

**Comment by ojw28** [comment]
We do not support HEVC tile tracks I'm afraid.
