### ISSUE TITLE
A->B loop repeat mode 

### ISSUE THREAD

**Issue by Waldmann375** [google/ExoPlayer#10323]
Before filing a feature request:
-----------------------
### [REQUIRED] Use case description
I want my player to be able to play only some defined portion of a song in a loop. I mean, if a song has duration of 60 seconds, and the AB mode is toggled, I set point A to 10 seconds andpoint B to 40 seconds, and player plays only this portion of 30 seconds in a loop.

### Proposed solution
just some assumptions:

1. There might be two separate properties for point A and point B in the player. 
2. When the  point B is set, the player plays the song only until it reaches the point B, and then it seeks back to a point A (which's default value is 0ms, i.e. the very beginning of the song)
3. If the value of point B was set to a value lower than current  poistion, the player seeks back to point A
4.  If the value of point B was set to a value highrer than total duration, this action is ignored

### Alternatives considered
 I can do this on a controller layer using just code logic, but when UI conroller(e.g. an activity or a fragment) dies, this logic will be stopped as well. 
I also mignt be able to make it live long enough by passing some data to a `MediaSessionService` object, but I don't know how, because `onBind()` for `MediaSessionService` is already defined.

**Comment by tonihei** [comment]
If I understand the request correctly, you'd like to continuously loop a section of the media between point A and B. Currently, you solve this with a `MediaController` implementation by observing the state and seeking when necessary.

The better solution for this is to set up the `MediaItem` you are requesting for playback with the correct parameters:
```
val mediaItem = MediaItem.Builder()
   // + other setters, e.g. setMediaId, setRequestMetadata
   .setClippingConfiguration(ClippingConfiguration.Builder().setStartPositionMs(A).setEndPositionMs(B).build())
   .build()
player.setMediaItem(mediaItem)
```
and then instruct the player to loop this clip:
```
player.setRepeatMode(Player.REPEAT_MODE_ONE)
```

This sets up playback statically with fixed points A and B and you won't be able to change this without interrupting playback. We have an open feature request to easily support updates to the `ClippingProperties` during playback in #3163. This isn't implemented yet, but something we will likely address in the future.

**Comment by tonihei** [comment]
I assume the question was answered and I can close this issue.
