### ISSUE TITLE
ExoPlayer crashes when converted to aar.

### ISSUE THREAD

**Issue by pineapplevine** [google/ExoPlayer#10320]
Hello.

Some modules of ExoPlayer are combined into one aar and used in the app.
Since ExoPlayer r2.16.1, the app crashes when playing videos.
We speculate that the crash was due to a bug in R8.
What do you know from the following information?

The source code has been changed a little in order to convert it to aar.

The reproduction procedure is as follows
1. run "make_aar.sh" to create aar
2. move /library/all/buildout/outputs/aar/library-release.aar to /demos/player/.
3. launch the demo application
4. select content

In addition, our investigation so far has revealed that it is possible to avoid the crash by changing the following code.
Since the actual processing content remains the same, we speculate that this is an R8 bug.
* ExoPlayer.java
```java
    private Builder(
        Context context,
        Supplier<RenderersFactory> renderersFactorySupplier,
        Supplier<MediaSourceFactory> mediaSourceFactorySupplier,
        Supplier<TrackSelector> trackSelectorSupplier,
        Supplier<LoadControl> loadControlSupplier,
        Supplier<BandwidthMeter> bandwidthMeterSupplier,
        @Nullable Supplier<AnalyticsCollector> analyticsCollectorSupplier) {
      this.context = context;
      this.renderersFactorySupplier = renderersFactorySupplier;
      this.mediaSourceFactorySupplier = mediaSourceFactorySupplier;
      this.trackSelectorSupplier = trackSelectorSupplier;
      this.loadControlSupplier = loadControlSupplier;
      this.bandwidthMeterSupplier = bandwidthMeterSupplier;
-     this.analyticsCollectorSupplier =
-         analyticsCollectorSupplier != null
-             ? analyticsCollectorSupplier
-             : () -> new AnalyticsCollector(checkNotNull(clock));
+     if (analyticsCollectorSupplier == null) {
+       this.analyticsCollectorSupplier = () -> new AnalyticsCollector(checkNotNull(clock));
+     } else {
+       this.analyticsCollectorSupplier = analyticsCollectorSupplier;
+     }
      looper = Util.getCurrentOrMainLooper();
      audioAttributes = AudioAttributes.DEFAULT;
      wakeMode = C.WAKE_MODE_NONE;
      videoScalingMode = C.VIDEO_SCALING_MODE_DEFAULT;
      videoChangeFrameRateStrategy = C.VIDEO_CHANGE_FRAME_RATE_STRATEGY_ONLY_IF_SEAMLESS;
      useLazyPreparation = true;
      seekParameters = SeekParameters.DEFAULT;
      seekBackIncrementMs = C.DEFAULT_SEEK_BACK_INCREMENT_MS;
      seekForwardIncrementMs = C.DEFAULT_SEEK_FORWARD_INCREMENT_MS;
      livePlaybackSpeedControl = new DefaultLivePlaybackSpeedControl.Builder().build();
      clock = Clock.DEFAULT;
      releaseTimeoutMs = DEFAULT_RELEASE_TIMEOUT_MS;
      detachSurfaceTimeoutMs = DEFAULT_DETACH_SURFACE_TIMEOUT_MS;
      this.playerOptions = null;
      this.plugin = null;
      this.qoeManager = null;
    }
```

I would like your opinion.
Thank you!

**Comment by ojw28** [comment]
This seems outside the scope of this issue tracking, since you're doing something custom (and not recommended) to cause the problem. It could be an R8 problem. It could also be that the way you're generating the single aar is not correctly picking up and merging all of the proguard rules defined by the individual modules.

**Comment by pineapplevine** [comment]
Thank you for answering.
We understand that it does not seem to be an ExoPlayer problem.
This issue will be closed.
