### ISSUE TITLE
How to use the setBackgrounded(boolean)?

### ISSUE THREAD

**Issue by NoGirlFriendException** [google/ExoPlayer#1032]
hello, i have one question about the DemoPlayer.  
 what's the functinality of setBackgrounded? 
 in which case I should use TURE or FALSE?

**Comment by NoGirlFriendException** [comment]
@ojw28  do u know the answer ? thx.

**Comment by ojw28** [comment]
The backgrounding functionality in the demo app was only ever really a best effort; not a complete solution. We'll be removing it in the 2.x the release. Implementing proper background playback support requires, among other things, moving the player into an Android service. This is work that an application developer will need to undertake should they wish to do this.
