### ISSUE TITLE
java.net.MalformedURLException: no protocol

### ISSUE THREAD

**Issue by bulkinav** [google/ExoPlayer#10321]
### ExoPlayer Version

2.16.1

### Devices that reproduce the issue

All devices

### Reproducible in the demo app?

Not tested

### Reproduction steps

When trying to play MPEG-DASH broadcast stream with filling the UTCTiming tag (without protocol), the follow exception appears:

` com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: java.net.MalformedURLException: no protocol: //site.com/current_time_xml`

By the way, it is considered normal to have no protocol indication (eg works on the web).

### Expected result

MPEG-DASH broadcast stream works without protocol in UTCTiming tag.

### Actual result

Exception appears in log, but this does not affect the video playback.

### Media

Manifest example:

```
<?xml version="1.0" encoding="UTF-8"?>
<MPD xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="urn:mpeg:dash:schema:mpd:2011" xmlns:cenc="urn:mpeg:cenc:2013" xsi:schemaLocation="urn:mpeg:dash:schema:mpd:2011 http://standards.iso.org/ittf/PubliclyAvailableStandards/MPEG-DASH_schema_files/DASH-MPD.xsd" type="dynamic" publishTime="2022-06-07T12:57:18.210Z" minimumUpdatePeriod="PT10S" availabilityStartTime="2022-03-14T18:53:13.205Z" minBufferTime="PT2S" suggestedPresentationDelay="PT40S" timeShiftBufferDepth="PT12H0M0S" profiles="urn:mpeg:dash:profile:isoff-live:2011">
  <Period start="PT0S" id="1">
    <AdaptationSet mimeType="video/mp4" frameRate="25/1" segmentAlignment="true" subsegmentAlignment="true" startWithSAP="1" subsegmentStartsWithSAP="1" bitstreamSwitching="false">
      <SegmentTemplate timescale="90000" duration="450000" startNumber="1"/>
      <Representation id="1" width="1280" height="720" bandwidth="3800000" codecs="avc1.64001f">
        <SegmentTemplate duration="450000" startNumber="1" media="../../../dash-live2/streams/dvr/dash1-12hFrag-hd-5-20220314T185304_$Number%09d$.mp4" initialization="dash1-12hFrag-hd-5-20220314T185304init.mp4"/>
      </Representation>
      <Representation id="2" width="1280" height="720" bandwidth="2400000" codecs="avc1.64001f">
        <SegmentTemplate duration="450000" startNumber="1" media="../../../dash-live2/streams/dvr/dash1-12hFrag-hd-4-20220314T185304_$Number%09d$.mp4" initialization="ash1-12hFrag-hd-4-20220314T185304init.mp4"/>
      </Representation>
      <Representation id="3" width="1280" height="720" bandwidth="1250000" codecs="avc1.64001f">
        <SegmentTemplate duration="450000" startNumber="1" media="../../../dash-live2/streams/dvr/dash1-12hFrag-hd-3-20220314T185304_$Number%09d$.mp4" initialization="dash1-12hFrag-hd-3-20220314T185304init.mp4"/>
      </Representation>
      <Representation id="4" width="640" height="360" bandwidth="950000" codecs="avc1.4d401e">
        <SegmentTemplate duration="450000" startNumber="1" media="../../../dash-live2/streams/dvr/dash1-12hFrag-hd-2-20220314T185304_$Number%09d$.mp4" initialization="dash1-12hFrag-hd-2-20220314T185304init.mp4"/>
      </Representation>
      <Representation id="5" width="640" height="360" bandwidth="350000" codecs="avc1.4d401e">
        <SegmentTemplate duration="450000" startNumber="1" media="../../../dash-live2/streams/dvr/dash1-12hFrag-hd-1-20220314T185304_$Number%09d$.mp4" initialization="dash1-12hFrag-hd-1-20220314T185304init.mp4"/>
      </Representation>
      <Representation id="6" width="160" height="90" bandwidth="110000" codecs="avc1.4d400b">
        <SegmentTemplate duration="450000" startNumber="1" media="../../../dash-live2/streams/dvr/dash1-12hFrag-hd-0-20220314T185304_$Number%09d$.mp4" initialization="dash1-12hFrag-hd-0-20220314T185304init.mp4"/>
      </Representation>
    </AdaptationSet>
    <AdaptationSet mimeType="audio/mp4" lang="rus" segmentAlignment="0" startWithSAP="1">
      <SegmentTemplate timescale="48000" media="../../../dash-live2/streams/1tv-dvr/dash1-12hFrag-hd-audio-lowres-20220314T185304_$Number%09d$.mp4" initialization="dash1-12hFrag-hd-audio-lowres-20220314T185304init.mp4" duration="240000" startNumber="1"/>
      <Representation id="7" bandwidth="64000" audioSamplingRate="48000" codecs="mp4a.40.2"/>
    </AdaptationSet>
    <AdaptationSet mimeType="audio/mp4" lang="rus" segmentAlignment="0" startWithSAP="1">
      <SegmentTemplate timescale="48000" media="../../../dash-live2/streams/1tv-dvr/dash1-12hFrag-hd-audio-hires-20220314T185304_$Number%09d$.mp4" initialization="dash1-12hFrag-hd-audio-hires-20220314T185304init.mp4" duration="240000" startNumber="1"/>
      <Representation id="8" bandwidth="128000" audioSamplingRate="48000" codecs="mp4a.40.2"/>
    </AdaptationSet>
    <AdaptationSet mimeType="application/mp4" lang="rus">
      <Role schemeIdUri="urn:mpeg:dash:role" value="subtitle"/>
      <SegmentTemplate timescale="90000" media="../../../dash-live2/streams/1tv-dvr/dash1-12hFrag-hd-caption-20220314T185304_$Number%09d$.mp4" initialization="dash1-12hFrag-hd-caption-20220314T185304init.mp4" duration="450000" startNumber="1"/>
      <Representation id="9" bandwidth="256" codecs="stpp"/>
    </AdaptationSet>
  </Period>
<UTCTiming schemeIdUri="urn:mpeg:dash:utc:http-xsdate:2014" value="//site.com/current_time_xml"/>
</MPD>
```

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by ojw28** [comment]
Looking at the dash specification (ISO 23009-1 2019), the `@value` attribute of a `UTCTiming` element with scheme `urn:mpeg:dash:utc:http-xsdate:2014` is defined pretty unambiguously to follow:
```
HTTP-VALUE = httpurl *[ WS httpurl ] ; httpurl is defined in IETF RFC 1738
```
where
```
httpurl = "http://" hostport [ "/" hpath [ "?" search ]]
```
which indicates that the `http:` prefix is required.

So your statement that it's considered normal to omit `http:` seems to be in direct contradiction to the specification. Please could you clarify why you think it's considered normal? The fact that it happens to work in some other player you've tried isn't really strong evidence. Thanks!

**Comment by ojw28** [comment]
> Exception appears in log, but this does not affect the video playback.

As an aside, I suspect that it will affect playback if the device's clock is incorrect. In particular, if the device's clock is fast then you may find that the player tries to request segments that aren't available yet. If the player can't understand the `UTCTiming` element then it's not going to be able to correct for this.

**Comment by kuznetcoff777** [comment]
> 
> which indicates that the `http:` prefix is required.
> 

Player can fetch mpd with http or https. If user will take mpd via https and there is http link inside, then i suppose will be warnings in web console, that there is insecure requests among other secure requests. Thats why schema should be conisdered, if player takes https mpd then goes to https time source, if http mpd, then http time source.

It is very strange that only http in dash specification

**Comment by ojw28** [comment]
> It is very strange that only http in dash specification

* I agree this is strange. ExoPlayer is also fine with `https:` (and indeed _any_ scheme that we know how to request).
* I still disagree with the original claim that completely omitting the scheme is considered normal though.

**Comment by kuznetcoff777** [comment]
>     ExoPlayer is also fine with `https:` (and indeed _any_ scheme that we know how to request).
But if to follow specification, then it is violation and exception should also be thrown that there must be only http.

>     * I still disagree with the original claim that completely omitting the scheme is considered normal though.
Then why not to do processing of omitted scheme (//) as commonly used (for example in web environment)?

**Comment by ojw28** [comment]
> But if to follow specification, then it is violation and exception should also be thrown that there must be only http.

We consider the important part of implementing the specification to be that we correctly handle specification compliant content. We're less concerned about explicitly failing for everything that doesn't exactly adhere to the specification. Doing the latter requires adding so many additional checks into the code that it's not a good use of time or computational resources. If you go as far as trying to validate that the video bitstream is compliant with the codec specification, it becomes infeasibly expensive.

> Then why not to do processing of omitted scheme (//) as commonly used (for example in web environment)?

My understanding is that omitting the scheme from a URL X is only valid when X is relative to some other absolute URL Y. In the case '//' is used and the scheme is omitted, resolution of X against Y ends up being URL X with the scheme inherited from Y. Is that your understanding too?

The reason we don't do that in this case is that the spec does seem fairly clear in that this URL is expected to be absolute. We've also not had any other occurrences of this being a problem, which suggests that omitting the scheme is not common in `UTCTiming` elements.
