### ISSUE TITLE
Play h264 stream from tcp from robomaster s1

### ISSUE THREAD

**Issue by Vinz1911** [google/ExoPlayer#10324]
Hello, 

i have the following problem, i currently develop my own control app for the DJI Robomaster S1. Now I want to catch the video stream from the Robot and display it in my app. From the DJI Docs I know that I get a raw h264 encoded stream from the robot which needs to be decoded to display, the stream is a tcp based connection. I didn't found a good solution, now I tried it with the Exoplayer. From the docs I saw I can read a RTSP stream and decoded it because it supports h264. So the Problem I have is, that this what I got is not a "real" RTSP stream? Just the raw h264 video data from ip + port. Can I manage it to play this kind of stream with the Exoplayer?

this is my code:

```kotlin
val player = ExoPlayer.Builder(this).build()
val media = MediaItem.fromUri("rtsp://192.168.2.1:40921")
val mediaSource = RtspMediaSource.Factory()
   .setDebugLoggingEnabled(true)
   .setForceUseRtpTcp(true)
   .createMediaSource(media)
playerView.player = player
player.setMediaSource(mediaSource)
player.prepare()
```

Screen keeps black and the only logs I got is the following:
```bash
I/ExoPlayerImpl: Init 43f4dd0 [ExoPlayerLib/2.17.1] [rm500, rm500, DJI, 25]
D/RtspClient: OPTIONS rtsp://192.168.2.1:40921 RTSP/1.0
    User-Agent: ExoPlayerLib/2.17.1
    CSeq: 0
```

Thank you!! 😊

**Comment by ojw28** [comment]
Sounds like an interesting project! Unfortunately, I'm not sure it's something we're going to be able to provide much support for; given it's unclear what type of stream you're dealing with.

I wonder whether [this project](https://github.com/DJI-Mobile-SDK-Tutorials/Android-VideoStreamDecodingSample) would be a better one to look at, and/or be a better place to ask for some help seeing as they're focused on the specific problem of getting video from DJI devices?

**Comment by ojw28** [comment]
It also looks like there's an official DJI SDK (which the project linked above depends on):

https://github.com/dji-sdk/Mobile-SDK-Android
