### ISSUE TITLE
More control over state listeneres 

### ISSUE THREAD

**Issue by Waldmann375** [google/ExoPlayer#10331]
### Use case description
I can never know if any listeners `Player.Listener` are already connected to a `MediaController`, or how many there are already.

### Proposed solution
All we have now is `addListener()` and `removeListener()`. But I would like also to have:
 - `clearListeners()` - remove all listeners, so I know for sure there are none 
 - `listeners` property, holding a list of listener objects currently added to this `MediaController` object.
 
### Alternatives considered
I do not know

**Comment by tonihei** [comment]
Could you clarify why you need this exactly and what kind of use case you are trying to solve?

In our current model, the lifecycle management of the listener should be the responsibility of the code who added the listener to the player. If you could just remove other listeners without their knowledge, you may easily break other code that relies on the listener being attached to the player.
