### ISSUE TITLE
Short rebuffering events on period transitions when audio/video do not align

### ISSUE THREAD

**Issue by baconz** [google/ExoPlayer#10339]
### ExoPlayer Version

2.17.1

### Devices that reproduce the issue

All devices, analysis was performed on an AndroidTV API 29 emulator.

### Reproducible in the demo app?

Yes

### Reproduction steps

1. Play the attached manifest using the demo app on any version 2.11.0 or later
2. Wait for the period transition at 0.66s
3. Observe that the state briefly becomes `BUFFERING`

It looks like this bug was introduced here https://github.com/google/ExoPlayer/commit/bc9a0860e0119957ecbe970fb62554b143b31a7f 

I think this is happening because if there is a jagged edge, and the audio ends after the video, the video renderer gets cleared before the stream transition occurs; so the `isReadingAhead` check in `doSomeWork` fails and the video renderer is not ready.

### Expected result

The content should not rebuffer on the period transition.

### Actual result

The content rebuffers on the period transision.

### Media

This manifest will reproduce the issue: https://www.philo.com/storage/dev/seth/gaps/m5.mpd

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by tonihei** [comment]
I can't reproduce this on an actual device, just the emulator. At the transition point of the periods, the renderer needs to release and re-initialize the video codec because the maximum input size changed. The actual device handles this fast enough to not cause any buffering, but the emulator is too slow and needs to enter the `BUFFERING` state until the decoder is ready again. This all seems to be working as intended as far as I can see.

**Comment by baconz** [comment]
I'm able to repro on a number of physical devices as well -- I repro'ed just now on a FireTV AFTSS, a TVision HUB, and GoogleTV. The only device I have access to right now that doesn't repro is the Bravia XBR-65X950H, which is interesting because the decoder on that device acts very strangely in other respects as well...

It makes sense that re-initializing the codec takes time, and that it could block playback. The thing I'm confused about is why the rebuffer only seems to happen once during playback. If I play through to the end, and then scrub back to the beginning and let the asset play again, I do not see it rebuffer when it crosses the period boundary the second time. Is the OS doing some caching of the codec under the covers? If so, can we pre-warm the cache?

**Comment by tonihei** [comment]
> If I play through to the end, and then scrub back to the beginning and let the asset play again, I do not see it rebuffer when it crosses the period boundary the second time.

ExoPlayer tries to reuse codecs if at all possible to avoid any disruption to playback. The first time you cross this period transition point, the maximum possible video size changes and the codec needs to be reconfigured to support the larger resolution. But when you seek back, we can keep the codec with the higher configured max values without recreating it. 

> Is the OS doing some caching of the codec under the covers? If so, can we pre-warm the cache?

It's more a question of configuring the codec in a way that works for both periods immediately. You can try to inject your own `MediaCodecAdapter.Factory` by overriding `DefaultRenderersFactory.getCodecAdapterFactory()`. Your custom `MediaCodecAdapter.Factory` can just forward to a `DefaultMediaCodecAdapterFactory`, but modify the `mediaFormat`  parameter values. In particular, `MediaFormat.KEY_MAX_WIDTH`, `MediaFormat.KEY_MAX_HEIGHT` and `MediaFormat.KEY_MAX_INPUT_SIZE`.  This only works if you know the higher resolution of the second period upfront, and it's also quite a deep customization, so we won't be able to debug and advise in much more detail.
