### ISSUE TITLE
ExoPlayer is not returning DVB subtitles

### ISSUE THREAD

**Issue by bgolob** [google/ExoPlayer#10337]
I'm using ExoPlayer 2.16.1 and I'm trying to play an HLS stream with DVB subtitles. Till now I could retrieve these subtitles using this = 
`player.currentTracksInfo.trackGroupInfos.filter { it.trackType == C.TRACK_TYPE_TEXT }.` 
But since ExoPlayer 2.17.1 this line of code returns an empty list for the same stream. Was there any change that affects DVB subtitles?

**Comment by tonihei** [comment]
Can you provide sample media here or to dev.exoplayer@gmail.com (with "Issue #10337" in the subject) so that we can reproduce? Without additional information we can say if this is working as intended or if it's a bug.
