### ISSUE TITLE
Unsupported Operation Exception on API level 29 and 30 devices.

### ISSUE THREAD

**Issue by dino-saurabh** [google/ExoPlayer#10335]
Describe your question in detail.
-------------------------
We are facing some issues while AudioTrack creation only on API levels 29 and 30, It throws UnsupportedOperationException while AudioTrack creation, Initially we suspected it to be an issue with offloaded playback but turning it off also did not help with this error.
this is the stack trace of this exception.
```
java.lang.UnsupportedOperationException: Cannot create AudioTrack at android.media.AudioTrack$Builder.build(AudioTrack.java:1018) 
at com.google.android.exoplayer2.audio.DefaultAudioSink$c.b(SourceFile:12) 
at com.google.android.exoplayer2.audio.DefaultAudioSink$c.a(SourceFile:1) 
at com.google.android.exoplayer2.audio.DefaultAudioSink.w(SourceFile:1) 
at com.google.android.exoplayer2.audio.DefaultAudioSink.F(SourceFile:4) 
at com.google.android.exoplayer2.audio.DefaultAudioSink.k(SourceFile:17) 
at uh.b.k(SourceFile:1) at com.google.android.exoplayer2.audio.f.m0(SourceFile:8) 
at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.P(SourceFile:45) at 
com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.t(SourceFile:16) at 
com.google.android.exoplayer2.m.d(SourceFile:139) 
at com.google.android.exoplayer2.m.handleMessage(SourceFile:29) 
at android.os.Handler.dispatchMessage(Handler.java:103) 
at android.os.Looper.loop(Looper.java:214) 
at android.os.HandlerThread.run(HandlerThread.java:67)

```
it seems the exception originates here, but I was not able to reason out why the state would still be uninitialized after creation?
```

try {
    final AudioTrack track = new AudioTrack(
            mAttributes, mFormat, mBufferSizeInBytes, mMode, mSessionId, mOffload,
            mEncapsulationMode, mTunerConfiguration);
    if (track.getState() == STATE_UNINITIALIZED) {
        // release is not necessary
        throw new UnsupportedOperationException("Cannot create AudioTrack");
    }
    return track;
} catch (IllegalArgumentException e) {
    throw new UnsupportedOperationException(e.getMessage());
}

```
Is this a bug with the Android Media API itself? or I am doing something wrong?

Exoplayer version details
-------------------------
we are using exoplayer version 2.16.1; unfortunately, the issue is not reproducible at our end.

cc @saurabhofficial

**Comment by tonihei** [comment]
It's hard to say without knowing further details what went wrong exactly, but some part of the media configuration or the system state prevents the `AudioTrack` from being created. It could be that you are trying to play an audio format in a passthrough or offload mode that isn't supported on this device for example. To understand the problem in more detail, we would need example media, the device this occurs on, a bugreport from the device and any other information about the player setup that may be relevant (track selection parameters, any audio customizations, etc).

**Comment by SaurabhOfficial** [comment]
we are also trying to get the bug report from any user who is facing this issue, we will share if we get some reports over the mail. The highest errors were on Sony Bravia VH2, and VH1.
meanwhile, I was going through the implementation checking for attributes that are additional for API level 29 and which show some transient behavior since it's not 100% reproducible some users of similar devices are able to play similar audio format contents. I stumbled upon allowedCapturePolicy but it's uniform across all devices and sessions I don't know if it can cause some trouble?

**Comment by tonihei** [comment]
> I stumbled upon allowedCapturePolicy but it's uniform across all devices and sessions I don't know if it can cause some trouble?

Sounds unrelated, but it's really not possible to say what can cause this without more information from these devices (ideally a bugreport that is likely to give some indication).

>  The highest errors were on Sony Bravia VH2, and VH1.
This definitely indicates a device-specific problem.
