### ISSUE TITLE
how to add custom play and pause icon for exo_play_pause button id

### ISSUE THREAD

**Issue by sureshsivalingam01** [google/ExoPlayer#10332]
I'm using StyledExoPlayer and custom controls .
Play Pause button icon relies on style of the button.  But I want to add custom play pause icon for exo_play_pause btn.How to do it?

<ImageButton
            android:id="@id/exo_play_pause"
            style="@style/ExoStyledControls.Button.Center.PlayPause"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:background="@color/transparent"
            android:src="@drawable/play_pause"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent" />

**Comment by marcbaechinger** [comment]
The ID of the drawables used by the UI compoanents are defined [here](https://github.com/google/ExoPlayer/blob/release-v2/library/ui/src/main/res/values/drawables.xml#L41). You can define your own drawables in your app that override the same ID to customize the icons.

Please also check [this section in the developer guide](https://github.com/google/ExoPlayer/blob/release-v2/library/ui/src/main/res/values/drawables.xml#L41).

**Comment by piyush921** [comment]
I am having styledplayerview on two screens. And if I override the icons by using exo_styled_controls_play, it will change icon on both players. How do i set different custom icon on both players ?
