### ISSUE TITLE
Audio quality is very low

### ISSUE THREAD

**Issue by ItamarStern1** [google/ExoPlayer#10346]
### ExoPlayer Version

2.14.2

### Devices that reproduce the issue

Pixel 2 android 13 (android studio emulator)

### Reproducible in the demo app?

Not tested

### Reproduction steps

---

### Expected result

The audio sounds good and clear.

### Actual result

I have the problem just in android 13, the audio quality is very low.

### Media

Not applicable

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by tonihei** [comment]
Please provide example media and any reproduction steps that allow use to reproduce the issue.

**Comment by ItamarStern1** [comment]
I opened your sample app from https://github.com/google/ExoPlayer.
I ran the "demo" app on android studio.
In the list I clicked on Playlists -> Audio -> Video -> Audio.
On a device with api 32 - this works fine.
On a device with api 33 - this sounds bad.
Thank you

**Comment by tonihei** [comment]
Thanks for reporting. It seems this is a known issue with the API 33 emulator system image (internal reference b/234520350) and will be fixed by the next emulator release.
