### ISSUE TITLE
Vimeo video support. 

### ISSUE THREAD

**Issue by Royal201709** [google/ExoPlayer#10343]
SimpleExoPlayer doesn't support playing vimeo videos using Jetpack Compose ?

**Comment by tonihei** [comment]
I'm not sure what you are asking exactly. If you have a direct media URL, it should be playable with ExoPlayer. But I doubt you can just play any existing Vimeo video as these likely don't offer access to the underlying video URL.
 
There is also no support for Jetpack Compose at the moment. Improving this is tracked by #9654.

**Comment by Royal201709** [comment]
I meant I have a Vimeo video url and want to play that in ExoPlayer. It's possible? Because I tried multiple times but could not achieve it.

**Comment by tonihei** [comment]
For general format support questions, please see https://exoplayer.dev/supported-formats.html. Otherwise, please provide more details (like the video URL) if you want us to investigate further.
