### ISSUE TITLE
Decoder failed: OMX.amlogic.mpeg2.decoder.awesome2

### ISSUE THREAD

**Issue by thor2002ro** [google/ExoPlayer#10355]
### ExoPlayer Version

2.17.1

### Devices that reproduce the issue

Xiaomi Mi TV Stick 4k running Android TV 11

### Reproducible in the demo app?

Not tested

### Reproduction steps

trying to play Live Channels TV from network server with TVheadend using PVR Live app , basically it just streams using a m3u list
there are 2 types of channels HD(h264) and SD(mpeg2)

Mpeg2 channels crash the player with a black screen

### Expected result

Stream

### Actual result

Black Screen with no menus

### Media

should have the same issue on all mpeg2 media

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by icbaker** [comment]
The underlying error in the bug report looks like it's coming from the framework `MediaCodec` (the stack trace from ExoPlayer about failing to disable the codec is just a secondary symptom):

```
06-19 10:30:56.109  1046   494 12102 E OMXNodeInstance: fillBuffer::storeFenceInMeta(0xf40056b4:amlogic.mpeg2.decoder.awesome2, 0x15 [2088960@0xf2f817d0 fc=106]) ERROR: ??(0xffffffc2)
06-19 10:30:56.109  1046   494 12102 W android.hardware.media.omx@1.0-service: Unrecognized status value: -62
06-19 10:30:56.109 10082 10879 15899 W konsult.pvrliv: Unrecognized status value: -62
06-19 10:30:56.109 10082 10879 15899 E ACodec  : signalError(omxError 0x80001001, internalError -62)
06-19 10:30:56.109 10082 10879 15898 E MediaCodec: Codec reported err 0xffffffc2, actionCode 0, while in state 6
06-19 10:30:56.110 10082 10879 15899 W ACodec  : not dequeuing from native window due to fatal error
06-19 10:30:56.110 10082 10879 15898 D SurfaceUtils: disconnecting from surface 0xefb19318, reason disconnectFromSurface
06-19 10:30:56.113 10082 10879 15899 E Surface : getSlotFromBufferLocked: unknown buffer: 0xf3f86630
06-19 10:30:56.113 10082 10879 15899 E ACodec  : queueBuffer failed in onOutputBufferDrained: -22
06-19 10:30:56.113 10082 10879 15899 E ACodec  : signalError(omxError 0x80001001, internalError -22)
06-19 10:30:56.113 10082 10879 15898 E MediaCodec: Codec reported err 0xffffffea, actionCode 0, while in state 0
06-19 10:30:56.115  1046   494 15908 I VDA     : [0] "ServiceDeviceTask(): buffer counts: IN[74,74], OUT[18,8,8] DEC[5->0] => DEVICE[0+3/3->0+10/17] => RR CLIENT[7]\\n"
```

Marking as device-specific.

**Comment by christosts** [comment]
This looks like a device-specific issue with the device decoder. I suggest you reach out to the device vendor. 

You can try to run the stream on another device, using the [ExoPlayer demo app](https://exoplayer.dev/demo-application.html), to verify whether the stream works on other devices. If the stream crashes on other devices, please update this issue, and email us with a stream link so that we can test and maybe repro.
