### ISSUE TITLE
BUG WITH EXOPLAYER DURATION

### ISSUE THREAD

**Issue by Usman-Click** [google/ExoPlayer#10357]
HI,
I started experiencing this problem last month after i downloaded a sample movie from this site (https://www.thenetnaija.net/videos/movies),

the video format is MP4 but the length is showing something like (82:45:24) hours while the actual length of the movie is (1:56:01) hour and it happen to all the videos from that website,

But the remaining videos that i downloaded from other sites are playing just fine.

Here is a screenshot of what is happening

**Comment by icbaker** [comment]
It's likely that the video file contains an incorrect duration in its metadata (as discussed in https://github.com/google/ExoPlayer/issues/9593).

Without access to the video file it's impossible to say for sure. I recommend you analyse it with https://gpac.github.io/mp4box.js/test/filereader.html as shown in https://github.com/google/ExoPlayer/issues/9593#issuecomment-956186528. That will probably explain where ExoPlayer is getting the 85 hour duration from.

**Comment by Usman-Click** [comment]
Okay,
As you said I analyzed it with https://gpac.github.io/mp4box.js/test/filereader.html
And found out that the problem is the same as https://github.com/google/ExoPlayer/issues/9593

Here is the screenshot of the analyzing 

![Screenshot_20220620-131355_Samsung Internet](https://user-images.githubusercontent.com/47116342/174600156-a2355cc6-f2a6-4c88-9995-564a8161ea53.jpg)

**Comment by Usman-Click** [comment]
All I want to know now is:
Is there a way to manually set the duration ourselves?

**Comment by icbaker** [comment]
> Is there a way to manually set the duration ourselves?

Not easily, no. I think the answer is the same as https://github.com/google/ExoPlayer/issues/9593#issuecomment-957801456: ExoPlayer aims to play correctly encoded/prepared content correctly. I'm afraid we don't go out of our way to support poorly encoded/prepared content.

**Comment by Usman-Click** [comment]
Thanks
