### ISSUE TITLE
disable audio track or volume

### ISSUE THREAD

**Issue by VeiZhang** [google/ExoPlayer#10350]
I want to ask whether there is a way to enable or disable audio track, make it like subtitle disable and enable. 
Because some video volume can't be control, so I want to have the switch.

**Comment by VeiZhang** [comment]
Additionally, some video played in Android TV device, but ExoPlayer can't set its volume, its volume controlled by TV, so how can I control its volume?

**Comment by tonihei** [comment]
You can change the volume of your stream by calling `Player.setVolume()`. Alternatively, you can also try to use `Player.setDeviceVolume()` or `decreaseDeviceVolume()`/`setDeviceMuted` to overwrite the device volume (for all streams).

**Comment by VeiZhang** [comment]
@tonihei Thanks, I will try it.
