### ISSUE TITLE
AES URI and key overriding

### ISSUE THREAD

**Issue by Ste-RH** [google/ExoPlayer#10351]
I have a question around AES.  Regarding an HLS manifest, the key server URI defined, and the key that is returned/used from that keyserver...

Is it possible to interject and override either/both the URI and the returned key?  If not, would there be a route via custom overriding classes to achieve overriding? Something like #6338 maybe, and then use a modified copy of Aes128DataSource to achieve what I desire?  Would such a custom DataSource all fit into the chain without issue?

**Comment by tonihei** [comment]
I'm not entirely sure which part you want to override, but there may be multiple options depending on the exact desired outcome:
 - Provide a custom `HlsPlaylistParserFactory` to `HlsMediaSource.Factory`. This can wrap the default implementation and modify any `HlsPlaylist` values before returning the playlist to the player.
 - You can modify the network requests being made just-in-time by using a `ResolvingDataSource` with a `Resolver` that is able to update any requested URI, request parameters etc. and can also block if needed to determine the correct request.
 - You can modify what is being read from a resource by providing a completely custom `DataSource`, which can wrap an existing source and do any modification you like. You may want to write a `DataSourceContractTest` if you do that to ensure the custom source fulfils all expectations of the interface.

**Comment by Ste-RH** [comment]
Thanks @tonihei.  Think I will be looking at a custom HLS playlist parser as this was also suggested in #6181.  Will let you/everyone know how I get on.

**Comment by Ste-RH** [comment]
Hmm, nope.  That is only at best gonna let me change the URL of the keyserver.  Custom DataSource it is I think.

**Comment by Ste-RH** [comment]
Ok, bit lost now @tonihei.  Looking into how Aes128DataSource is used...

In HlsMediaChunk, the method buildDataSource returns a new instance of a Aes128DataSource if there is an encryption key passed in.  So it does this mean no matter what custom DataSource/Factory I create/use, a Aes128DataSource will always be used for a video encrypted as Aes 128?

If so, there is no way at this level I can interject a custom key...?  This would leave the Resolver as the only option?

**Comment by tonihei** [comment]
Yes, the `Aes128DataSource` is used automatically for full segment encryption. 

I'm still not entirely sure what you are trying to customize :)  If I understand correctly you want
 1. Change the URL of the key server. 
     - This can be done by either wrapping the `HlsPlaylistParserFactory` or by using a `ResolvingDataSource` that amends the URI if required. 
 2. Change the actual key returned from the updated key server URL.
    - This is likely only possible by using a custom `DataSource` for the request that loads the key and is able to amend to the returned value. `HlsMediaSource` has a special `HlsDataSourceFactory` that lets you create different `DataSources` based on the type of request. The key requests will use `C.DATA_TYPE_DRM` as the `dataType`. 

Note that we also use a key cache that saves the key returned for a specific key server URL in order to avoid repeated requests for the same key. So you should make sure the original key server URI (before amendments) changes whenever the key is supposed to change as well, meaning you can't just use placeholder URI that is always the same even if the keys are not. (Not sure if that could be an issue for you)

**Comment by Ste-RH** [comment]
After some head scratching I have _something_ that works.  Though I have to remove a 'final' keywords within the ExoPlayer library code to allow the solution to work :/

Here is what I am doing:

- My own `AESHlsPlaylistParser` class that implements `ParsingLoadable.Parser<HlsPlaylist>`.  It contains an instantiated `HlsPlaylistParser` member that does the main parse and creates the `HlsPlaylist` that I then change the URI within.

- My own `AESHlsPlaylistParserFactory` class that implements `HlsPlaylistParserFactory`.  This allows me to create instances of `AESHlsPlaylistParser` and pass the key along into them.

- In my player code I can set the `HlsMediaSourceFactory` PlaylistParseFactor (using `setPlaylistParserFactory`).

Now for the meat of the solution.  Inside `AESHlsPlaylistParser` I override the 'parse' function thus:

```
@Override
public HlsPlaylist parse(Uri uri, InputStream inputStream) throws IOException
{
	HlsPlaylist hlsPlaylist = super.parse(uri, inputStream);

	Log.d( "AESHlsPlaylistParser", "AesHlsPlaylistParser : parse CALLED : uri = " + uri.getPath() + " | hlsPlaylist = " + hlsPlaylist.toString() );

	if( hlsPlaylist instanceof HlsMediaPlaylist &&
		m_Key != null && !m_Key.isEmpty() )
	{
		HlsMediaPlaylist hlsMediaPlaylist = (HlsMediaPlaylist)( hlsPlaylist );

		String newURI = "data:application/octet-stream;base64," + m_Key;

		int iNumSegments = ( hlsMediaPlaylist.segments != null ) ? hlsMediaPlaylist.segments.size() : 0;
		Log.d( "AESHlsPlaylistParser", "AesHlsPlaylistParser : parse : hlsMediaPlaylist = " + hlsMediaPlaylist.toString() + " | iNumSegments = " + iNumSegments + " | hlsMediaPlaylist.segments = " + hlsMediaPlaylist.segments.toString() );

		for( int iSegment = 0; iSegment < iNumSegments; ++iSegment )
		{
			HlsMediaPlaylist.Segment segment = hlsMediaPlaylist.segments.get( iSegment );
			int iNumParts = ( segment != null && segment.parts != null ) ? segment.parts.size() : 0;
			Log.d( "AESHlsPlaylistParser", "AesHlsPlaylistParser : parse : segment.url = " + segment.initializationSegment.fullSegmentEncryptionKeyUri + " | segment.initializationSegment.fullSegmentEncryptionKeyUri = " + segment.fullSegmentEncryptionKeyUri + " | iNumParts = " + iNumParts );

			// Change the URI
			segment.initializationSegment.fullSegmentEncryptionKeyUri = newURI;
			segment.fullSegmentEncryptionKeyUri = newURI;

			// Parts
			for( int iPart = 0; iPart < iNumParts; ++iPart )
			{
				HlsMediaPlaylist.Part part = segment.parts.get( iPart );
				if( part != null )
				{
					Log.d( "AESHlsPlaylistParser", "AESHlsPlaylistParserFactory : createPlaylistParser : part.fullSegmentEncryptionKeyUri = " + part.fullSegmentEncryptionKeyUri );

					part.initializationSegment.fullSegmentEncryptionKeyUri = newURI;
					part.fullSegmentEncryptionKeyUri = newURI;
				}
			}
		}

		// Trailing parts
		int iNumTrailingParts = (hlsMediaPlaylist.trailingParts != null) ? hlsMediaPlaylist.trailingParts.size() : 0;
		for( int iTrailingPart = 0; iTrailingPart < iNumTrailingParts; ++iTrailingPart )
		{
			HlsMediaPlaylist.Part trailingPart = hlsMediaPlaylist.trailingParts.get( iTrailingPart );
			if( trailingPart != null )
			{
				Log.d( "AESHlsPlaylistParser", "AESHlsPlaylistParserFactory : createPlaylistParser : trailingPart.fullSegmentEncryptionKeyUri = " + trailingPart.fullSegmentEncryptionKeyUri );

				trailingPart.initializationSegment.fullSegmentEncryptionKeyUri = newURI;
				trailingPart.fullSegmentEncryptionKeyUri = newURI;
			}
		}
	}

	return hlsPlaylist;
}
```

So the, the change I have to make to the ExoPlayer library code is to remove the `final` from `fullSegmentEncryptionKeyUri` in the `SegmentBase` class.

It works, but I am far from convinced it is the best method.  Any/all advice greatly received!

**Comment by tonihei** [comment]
> It works, but I am far from convinced it is the best method. 

I think it looks like the right approach if your goal is to override all `fullSegmentEncryptionKeyUri` values of all segments and parts. (Aside: You only need to override the parts if you expect to use low-latency streams that define parts)

> the change I have to make to the ExoPlayer library code is to remove the `final` from `fullSegmentEncryptionKeyUri`

The playlist objects are meant to be fully immutable so that they can be used across threads and classes can rely on values staying the same forever. The best way around this problem is to create a new instance instead of modifying the existing one:
```
return new HlsMediaPlaylist(
   playlist.playlistType,
   playlist.baseUri,
   playlist.tags,
   /* and so on... */
   updatedSegments,
   updatedTrailingParts,
   ...
);
```
where `updatedSegments` is a copy of the original segments created in a similar manner where you just change the `fullSegmentEncryptionKeyUri` and leave the rest unchanged.

**Comment by Ste-RH** [comment]
Thanks for the response @tonihei.

I can make the changes you suggest happen, and will be great to not have any changes to the core library!  Couple of questions...

1. Will I have to create new `initializationSegment` (if they are not null) on each segment, part, and trailingPart ?
2. What do I do for the new trailingPart list passed in when creating the new `HlsMediaPlaylist` ?  Are these just the last segments part list?

Thanks again!

**Comment by tonihei** [comment]
> Will I have to create new initializationSegment (if they are not null) on each segment, part, and trailingPart ?

The answer is likely yes. I think you don't necessarily have to create a new one for each segment and part as you can reference the same initialization segment from all of them (assuming they use the same).

> What do I do for the new trailingPart list passed in when creating the new HlsMediaPlaylist ? Are these just the last segments part list?

These are the parts of the yet unfinished final segment in a low-latency live stream. We have to keep them separate as the other properties of the full segment (like `durationUs`) are not yet known and we might need to remove the last trailing part if it's just a preload part (whereas `Segment` instances are not expected to change creation). 

I can see that your overall changes becomes quite long and cumbersome to write. If you think it's worth having a helper method like `HlsMediaPlaylist.copyWithFullSegmentEncryptionKeyUri`, feel free to send a PR. We already have similar methods like `HlsMediaPlaylist.copyWithEndTag`, so this doesn't feel out of place.

**Comment by tonihei** [comment]
Closing for now because it seems the question was answered.
