### ISSUE TITLE
HevcConfig.parse misreads reserved bit

### ISSUE THREAD

**Issue by rcombs** [google/ExoPlayer#10366]
### ExoPlayer Version

2.18.0

### Devices that reproduce the issue

N/A

### Devices that do not reproduce the issue

N/A

### Reproducible in the demo app?

Not tested

### Reproduction steps

Attempt to play an MP4 or MKV file with an HEVC stream having bit 6 set to 1 in the first byte of a NAL array in an `HEVCDecoderConfigurationRecord`.

### Expected result

HevcConfig.parse() should read the low 6 bits of the first byte to correctly determine the NAL type for each array.

### Actual result

Instead, it reads the low _7_ bits, incorrectly including the reserved bit. This is currently meant to always be 0, but could be given some kind of meaning in a future revision. This is very minor, but I happened to notice it while investigating another issue in the area, and figured I'd bring it up.

See https://github.com/google/ExoPlayer/blob/03569f9e6536e6c60cb585115d6d7352a4deab71/library/extractor/src/main/java/com/google/android/exoplayer2/video/HevcConfig.java#L66

```
int nalUnitType = data.readUnsignedByte() & 0x7F; // completeness (1), nal_unit_type (7)
```
should instead be:
```
int nalUnitType = data.readUnsignedByte() & 0x3F; // completeness (1), reserved (1), nal_unit_type (6)
```

### Media

Synthetic test clip attached: [test-clip.mp4.zip](https://github.com/google/ExoPlayer/files/8953476/test-clip.mp4.zip)

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by icbaker** [comment]
FYI @rcombs It looks like the parsing of NAL unit type may be incorrect both before and after this change - see discussion in https://github.com/androidx/media/issues/2464 and please chime in there if you think the `int nalUnitType = data.readUnsignedByte() & 0x3F` logic needs to stay as-is without the additional bit-shift.
