### ISSUE TITLE
Higer version of CMake required when generating aar for ffmpeg extension.

### ISSUE THREAD

**Issue by tpuserhp** [google/ExoPlayer#10368]
In my other issue #10354 it was suggested that I should  rebuild the extension every time I upgrade ExoPlayer.  I am using Exoplayer 2.18.0. When I tried to  rebuild the ffmpeg extension, I got error message that CMake  '3.21.0' or higher was not found. I only have CMake version 3.10.2 installed. CMake 3.18.1 is the highest version I can find under the CMake section of SD Tools. I manually downloaded  CMake 3.23.2 and made config changes according to https://developer.android.com/studio/projects/install-ndk. I did not  install the Ninja build system as I thought it is for performance improvement only. But I got error like could not get version from cmake.dir.  I gave up after a few tries.
Finally I changed the CMakeLists.txt to use 3.10.0 for cmake_minimum_required. I also changed ffmpeg build.gradle to 3.10.2 for android.externalNativeBuild.cmake.version. This allows me to generate the  aar successfully. 
For this error, what should be the best solution? To install a higher version of SDK that comes with the support of CMake 3.21.0 (or above) or manually download the supported  CMake  version like what I did? Where can I find  the corresponding SDK and Cmake versions?  Thanks.
I gave it another attempt after a good night sleep  and was able to use the CMake 3.23.2 that I manually downloaded to  build the  ffmpeg extension aar. But I'd still want your input on methods to handle the requirement of a higher  CMake  version and
the website I can find the cross reference of Android SDK version and the CMake version. Thanks.

**Comment by icbaker** [comment]
Looks similar/related to https://github.com/google/ExoPlayer/issues/9933

**Comment by tpuserhp** [comment]
Thanks for the update. Does it mean a fix will be available?

**Comment by lemontmoon** [comment]
Hi all, do anyone sucessfully compiled extension-ffmpeg-release.aar for 2.18.0 and got it working ? if yes,, can anyone share it for all architectures with all codecs ON ? thx,.

**Comment by tonihei** [comment]
The latest Android Studio (Dolphin | 2021.3.1 Beta 4) includes CMake 3.22.1. I assume this can be marked as fixed?

**Comment by tpuserhp** [comment]
Hi support. Thanks for the update. Yes, this issue has been resolved and
can be closed. Thanks.
