### ISSUE TITLE
Unexpected IndexOutOfBoundsException during playback

### ISSUE THREAD

**Issue by javaboboApp** [google/ExoPlayer#10377]
### ExoPlayer Version

2.15.1

### Devices that reproduce the issue

Android 10
Set-top box

### Reproducible in the demo app?

No

### Reproduction steps

1. Play linear content 
2. Got "Source error" IndexOutOfBoundsException during parsing manifest: 
    in DefaultDashChunkSource: updateManifest() 

### Expected result

Not exception is triggered 

### Actual result

**Exception during playback:** 

Unexpected IndexOutOfBoundsException: Index: 8, Size: 6, com.google.android.exoplayer2.ExoPlaybackException: Source error at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(:3) at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(:33) at android.os.Handler.dispatchMessage(Handler.java:103) at android.os.Looper.loop(Looper.java:214) at android.os.HandlerThread.run(HandlerThread.java:67) Caused by: com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected IndexOutOfBoundsException: Index: 8, Size: 6 at com.google.android.exoplayer2.upstream.Loader$LoadTask.handleMessage(:26) at android.os.Handler.dispatchMessage(Handler.java:107) ... 2 more Caused by: java.lang.IndexOutOfBoundsException: Index: 8, Size: 6 at java.util.ArrayList.get(ArrayList.java:437) at com.google.android.exoplayer2.source.dash.DefaultDashChunkSource.updateManifest(:6) at com.google.android.exoplayer2.source.dash.DashMediaPeriod.updateManifest(:6) at com.google.android.exoplayer2.source.dash.DashMediaSource.processManifest(:4) at com.google.android.exoplayer2.source.dash.DashMediaSource.onManifestLoadCompleted(:36) at com.google.android.exoplayer2.source.dash.DashMediaSource$ManifestCallback.onLoadCompleted(:2) at com.google.android.exoplayer2.source.dash.DashMediaSource$ManifestCallback.onLoadCompleted(:1) at com.google.android.exoplayer2.upstream.Loader$LoadTask.handleMessage(:24) ... 3 more

### Media

I will email media to : [dev.exoplayer@gmail.com](mailto:dev.exoplayer@gmail.com)

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by icbaker** [comment]
The manifest provided over email cannot be used to reproduce the problem, because it contains relative URLs and is not hosted.

Please provide a link to the hosted manifest we can use to play the stream and reproduce the problem.

**Comment by javaboboApp** [comment]
@icbaker  I have sent you more information via email. Thanks for your help.

**Comment by javaboboApp** [comment]
> The manifest provided over email cannot be used to reproduce the problem, because it contains relative URLs and is not hosted.
> 
> Please provide a link to the hosted manifest we can use to play the stream and reproduce the problem.

@icbaker I  have sent you more information via email. Thanks for your help.

**Comment by icbaker** [comment]
It looks like the number of `<Representation>` nodes in your video `<AdaptationSet>` might be changing over time. I think this would explain the stack trace. The email you originally sent shows 10 `<Representation` nodes with the following IDs:
1. `video_112kbps`
1. `video_288kbps`
1. `video_480kbps`
1. `video_840kbps`
1. `video_1500kbps`
1. `video_2300kbps`
1. `video_3000kbps`
1. `video_4400kbps`
1. `video_6500kbps`
1. `video_8000kbps`

But loading the manifest from the hosted URL you provided in the follow-up email I see only 9 `<Representation>` nodes:
1.  `video_112kbps`
2. `video_288kbps`
3.  `video_480kbps`
4.  `video_840kbps`
5.  `video_1500kbps`
6.  `video_3000kbps`
7.  `video_4400kbps`
8.  `video_6500kbps`
9.  `video_8000kbps`

It seems like the `video_2300kbps` one is missing.

Over to @tonihei to dig deeper into this.

**Comment by tonihei** [comment]
It isn't valid for a DASH manifest to remove or add `Representation` nodes within the same `Period`. See https://dashif-documents.azurewebsites.net/DASH-IF-IOP/master/DASH-IF-IOP.html#timing-mpd-updates (in particular the point about adaptation sets in a period must not change and representations in adaptation sets must not change).

If you want to handle changes in the available representations, you'd typically create a new `Period` where you are free to update these properties.
