### ISSUE TITLE
Custom extractor gets a lot of read calls

### ISSUE THREAD

**Issue by teccheck** [google/ExoPlayer#10375]
Hi there,

for the past few days I've been writing a custom extractor for an obscure container format that is used by the Gear360 live stream. It is based on the RIFF format so I used the AVI extractor as a reference. Now I have the problem that the video is quite choppy. I tried to find out why and discovered that for every frame, my extractor gets about **6000** `read` calls. These mainly read video sample data, but only about 16 bytes at once. The time it takes to read the full frame is on average about 32ms. The data comes from an HTTP Stream over wifi directly from the camera, so I can't provide an example stream here.

Is this supposed to be like this? If not, how can I make the extractor read more data at once using fewer `read` calls?

Stream details:
* Container Format: RIFF based, 1 video stream
* Video codec: h265
* Frame rate: 30fps

Phone details:
* Moto G7 Plus (lake)
* LineageOS 19.1 (Android 12)
* Has hardware h265 decoder

App details:
* Exoplayer 2.18 (core, ui, dash, smoothstreaming)
* [Repository](https://github.com/TecCheck/Gear360App)
* [Extractor code](https://github.com/TecCheck/Gear360App/blob/master/app/src/main/java/io/github/teccheck/gear360app/player/Extractor.kt)

Maybe I can upload a dump of a stream if this helps. Just let me know.

Thanks :wink:

**Comment by icbaker** [comment]
The [javadoc for `Extractor.read`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/extractor/Extractor.html#read(com.google.android.exoplayer2.extractor.ExtractorInput,com.google.android.exoplayer2.extractor.PositionHolder)) says:
> A single call to this method will block until some progress has been made, but will not block for longer than this. Hence each call will consume only a small amount of input data.

It's therefore expected for an `Extractor` to receive a lot of small `read()` calls. You should change your implementation to be performant in this scenario (e.g. by introducing some buffering/caching). 

Aside: You may also find it helpful to run your `Extractor` implementation through our `ExtractorAsserts` testing harness - as it may find lots of subtle bugs that will cause problems in various edge cases during playback. You can see an example of a test using this library (with lots of different media samples) here: https://github.com/google/ExoPlayer/blob/release-v2/library/extractor/src/test/java/com/google/android/exoplayer2/extractor/mp4/Mp4ExtractorTest.java
