### ISSUE TITLE
Is SAMPLE-AES not supported at all?

### ISSUE THREAD

**Issue by Jason239** [google/ExoPlayer#10376]
https://exoplayer.dev/supported-formats.html#sample-formats

The above page says that the SAMPLE-AES method is not supported, but looking at the other issues such as [this](https://github.com/google/ExoPlayer/issues/8372) or [this](https://github.com/shaka-project/shaka-packager/issues/659#issuecomment-536789814), I am not sure if it is not supported.

I have some clear-key encrypted contents and I can't playback these on ExoPlayer at all.
I packaged this by Shaka packager and modified manifests for clear-key setting, but which part was made wrong? Or is it just not supported?

**Comment by icbaker** [comment]
ExoPlayer does not support `EXT-X-KEY` tags with `METHOD=SAMPLE-AES` and `KEYFORMAT="identity"`. That's what is being referred to at https://exoplayer.dev/supported-formats.html#sample-formats.

The `EXT-X-KEY` tag is also used for streams protected by other forms of sample-level encryption e.g. widevine DRM, and these are supported by ExoPlayer. That's what's being investigated and referred to in the issues you linked.

**Comment by Jason239** [comment]
Okay, I got it. 
It's not supported for clear-key way.
Thanks :)
