### ISSUE TITLE
onPlayerError event not called on some devices for malformed DASH

### ISSUE THREAD

**Issue by wiktorwar** [google/ExoPlayer#10371]
### ExoPlayer Version

2.17.1

### Devices that reproduce the issue
- Pixel 4a - Android 12 
- Pixel XL - Android 11 (Audio plays, video fails to play, no `onPlayerError`) 
- Samsung A51 - Android 10 (hangs on buffering state, no error )
- Redmi note 6 pro (12)
### Devices that do not reproduce the issue
* Pixel 3 - Android 12 (video/audio fails to play, error is passed through `onPlayerError`)

### Reproducible in the demo app?

Yes

### Reproduction steps

1. Use one of the affected devices
2. Play `https://v.redd.it/yktp72er5dp81/DASHPlaylist.mpd` in the demo app
AB: No error is logged, although video codec was not initialized due to wrong mime encoded
EB: Exoplayer should call `onPlayerError` and `onVideoCodecError`

### Expected result

- `MediaCodecVideoRenderer` (`ERROR_CODE_DECODING_FAILED`) error passed through `onPlayerError`

### Actual result

- No error is thrown on some devices

### Media

(This is a dash that is wrongly encoded - it has `hevc` mime encoded in mp4 containers instead of `avc`). 
https://v.redd.it/yktp72er5dp81/DASHPlaylist.mpd

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by icbaker** [comment]
If the framework `MediaCodec` doesn't report an error (which seems to be the case based on the bugreport provided), then ExoPlayer doesn't really know anything has gone wrong - and therefore there's no way to alert the app via `onPlayerError`.

If `MediaCodec` reports an error to us (and we can't retry/workaround it) I believe this will always be reported to an app via `onPlayerError`.

The fact that it differs per-device suggests that some underlying codec implementations handle invalid input in different ways.

I don't think there's really anything actionable here from ExoPlayer's perspective, so I'm going to close this as infeasible.
