### ISSUE TITLE
how to play audio from google drive?

### ISSUE THREAD

**Issue by sahujaunpuri** [google/ExoPlayer#10382]
how to play audio(MP3) from google drive?

**Comment by rohitjoins** [comment]
Make sure the url you provide for this audio, points to a media file and not a webpage.

Please provide complete information as requested in the question template. The template can be
found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/question.md).

Unfortunately we can't answer unclear questions or those with insufficient information.
