### ISSUE TITLE
Support dav1d decoder

### ISSUE THREAD

**Issue by 337240552** [google/ExoPlayer#10387]
Can we provide support for dav1d decoder? dav1d has better performance than libgav1.

Test data:[Test AV1 Video 1280 * 720P](http://1500000711.vod2.myqcloud.com/18160fb8vodtranshk1500000711/062791b6387702302578852428/v.f1416867.mp4) 
Device: Samsung S7, CPU exynos5 Android 8.0 

With libgav1 decoder, so many stutters and janks.
<img width="1130" alt="image" src="https://user-images.githubusercontent.com/329210/176116902-f0b0434c-1195-47a2-a90a-00f172bd45b5.png">

With dav1d decoder, few stutters and janks.
<img width="776" alt="image" src="https://user-images.githubusercontent.com/329210/176117741-2a9b1265-090b-4139-b9f2-dd6851fba925.png">

**Comment by hualong-shen** [comment]
Hey, do we have any updates on this one? @christosts

**Comment by christosts** [comment]
We have an item in our backlog to update the AV1 decoder extension to switch to dav1d from libgav1. That will be in the media3 version, since we are no longer making new ExoPlayer standalone releases. However we have not committed to this work at the moment so I'm afraid I cannot share a timeline.

**Comment by tonihei** [comment]
I'm closing this issue in favor of the same request in the Media3 issue tracker: https://github.com/androidx/media/issues/1985.
