### ISSUE TITLE
Why does this stream work and then suddenly stop?

### ISSUE THREAD

**Issue by lpv-1902** [google/ExoPlayer#10388]
URL: http://khkbh.dk:8080/hls/livestream/index.m3u8

It suddenly stops then throws out a

[LoadTask] Unexpected exception loading stream
[LoadTask]   java.lang.IllegalStateException: interceptor okhttp3.OkHttpClient$Builder_InterceptorImpl@585de23 returned a response with no body

**Comment by rohitjoins** [comment]
I was able to play this stream on the Exoplayer demo app and it doesn't suddenly stops. 

Please provide complete information as requested in the question template. The template can be
found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/question.md).

Unfortunately we can't answer unclear questions or those with insufficient information.
