### ISSUE TITLE
StyledPlayerView Overload resolution ambiguity. All these functions match.

### ISSUE THREAD

**Issue by onikaii** [google/ExoPlayer#10397]
Hi, I have this problems

 
When I try to use setControllerVisibilityListener  in StyledPlayerView, this error appears

Overload resolution ambiguity. All these functions match.
public open fun setControllerVisibilityListener(listener: StyledPlayerControlView.VisibilityListener?): Unit defined in com.google.android.exoplayer2.ui.StyledPlayerView
public open fun setControllerVisibilityListener(listener: StyledPlayerView.ControllerVisibilityListener?): Unit defined in com.google.android.exoplayer2.ui.StyledPlayerView

but when I use com.google.android.exoplayer2.ui.PlayerView, everything works fine, how can I solve that?
 
 
activity

```
                binding.videoView.setControllerVisibilityListener { visibility ->
                    when (visibility) {
                        View.GONE -> {
                            Log.d(TAG, "initializePlayer() called with: visibility = $visibility")
                        }
                        View.VISIBLE -> {
                            Log.d(TAG, "initializePlayer() called with: visibility = $visibility")
                        }
                    }
                }
```

Layout

<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".ui.video_player.VideoPlayerActivity">

    <com.google.android.exoplayer2.ui.StyledPlayerView
        android:id="@+id/video_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="#000000"
        app:fastforward_increment="15000"
        app:rewind_increment="15000"
        app:show_buffering="when_playing"
        app:show_fastforward_button="true"
        app:show_next_button="true"
        app:show_previous_button="true"
        app:show_rewind_button="true"
        app:show_subtitle_button="true"
        app:use_sensor_rotation="true|false" />

    <FrameLayout
        android:id="@+id/brightnessControl"
        android:layout_width="48dp"
        android:layout_height="264dp"
        android:visibility="gone"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent">

        <ImageView
            android:id="@+id/icon_brightness_full"
            android:layout_width="24dp"
            android:layout_height="24dp"
            android:layout_gravity="top|center_horizontal"
            android:src="@drawable/ic_brightness_full"
            app:tint="@color/white" />

        <com.google.android.material.slider.Slider
            android:id="@+id/brightnessSlider"
            android:layout_width="200dp"
            android:layout_height="32dp"
            android:layout_gravity="center"

            android:padding="0dp"
            android:rotation="270"
            android:valueFrom="0.0"
            android:valueTo="100.0"
            app:labelBehavior="gone"
            tools:ignore="MissingConstraints" />

        <TextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_gravity="bottom|center_horizontal"
            android:layout_margin="0dp"
            android:padding="0dp"
            android:text="Brillo"
            android:textColor="@color/white" />

    </FrameLayout>
</androidx.constraintlayout.widget.ConstraintLayout>

    def version_exoplayer = "2.18.0"
    implementation "com.google.android.exoplayer:exoplayer-core:$version_exoplayer"
    implementation "com.google.android.exoplayer:exoplayer-ui:$version_exoplayer"

**Comment by rohitjoins** [comment]
@onikaii `PlayerView` has only function named `setControllerVisibilityListener` whereas `StyledPlayerView` has two such functions(out of which one is deprecated in favour of another). Based on the error I think compiler cannot uniquely identify which of these two functions to use. You can try extracting a variable and explicitly specify its type as explained [here](https://stackoverflow.com/questions/48804704/overload-resolution-ambiguity-all-these-functions-match)
