### ISSUE TITLE
Intercepting DAI stream URL using the ExoPlayer IMA extension

### ISSUE THREAD

**Issue by amiantoch** [google/ExoPlayer#10396]
Hi, 

we are currently trying out the ExoPlayer IMA extension for IMA server side inserted ad streams in our android app, by using `ImaServerSideAdInsertionMediaSource`. We encountered the following problem and would like to ask you how to best handle it.

We have been using the trick to have a placeholder @TOKEN@ configured in ad manager and replace it in our client with the proper auth token. The hook to do this seems to be missing from the IMA extension.
With a previous IMA SDK integration, the IMA SDK functionality was implemented by our client app, resolving the media URL dynamically in order to get the stitched stream. This allowed us to manipulate the loaded media URL of the stitched stream (via `VideoStreamPlayer.loadUrl(...` callback), so we could replace a stream token placeholder for authorisation, before passing the stitched stream url to the player. 

By using `ImaServerSideAdInsertionMediaSource`, the stitched stream URL seems to be passed to the player internally, and we were not yet able to find any way to intercept this stitched stream media URL over the new IMA extension API.

Do you have any suggestions as to how to best handle stream authorisation in the given context?

Thanks in advance!

**Comment by amiantoch** [comment]
Hi,

are there any updates on this issue?
Is any additional information required from our side to further clarify?

Thanks

**Comment by marcbaechinger** [comment]
I'm not quite sure whether I understand all your requirements and what manipulations you want to do at what moment in time of the SDK/Player interaction. But I think there are some hooks that are useful for you to know about.

The `ImaServerSideAdInsertionMediaSource.Factory` allows app to set their `MediaSourceFactory` by passing it to the constructor. By default apps want this to be the `DefaultMediaSourceFactory` to support HLS and DASH. In your case you may want to take advantage of this flexibility:

1) You can inject your own custom `DataSource.Factory` into the constructor of the `DefaultMediaSourceFactory` and then inject that into the constructor of the `ImaServerSideAdInsertionMediaSource.Factory`. The custom `DataSource.Factory` would then create a `ResolvingDataSource` that wraps the concrete `DataSource` that you are using. The `ResolvingDataSource` allows you to replace the `DataSpec` with your modified version by providing a `Resolver` and overriding its

```
DataSpec resolveDataSpec(DataSpec dataSpec) throws IOException;
```

The `DataSpec` passed in is what you would have seen in `loadUrl` (I think) and you can create a new `DataSpec` replacing that with whatever you like in the resolver. 

Note: If I'm not mistaken then the `Resolver` will be called for any requests manifest/playlist and any media (video/audio/text).

2) An alternative would be to implement your own `MediaSource.Factory` and pass it to the constructor of `ImaServerSideAdInsertionMediaSource.Factory`. Your implementation is a composition that delegates everything to an instance of `DefaultMediaSourceFactory` that you hold as a member field. Then when `MediaSource.Factory.createMediaSource(MediaItem)` is called your wrapper source receives the `MediaItem` and can `buildUpon()` to inject the modified URI before delegating to `createMediaSource` of the actual source and pass the new `MediaItem`.

Note: This approach does only manipulate the initial URI that is used to load the manifest/playlist initially. After that, media and the like is requested as without this change.

I hope one or the other approach may work for you. Please let me know in either case. :)

**Comment by amiantoch** [comment]
Very useful tips!:)
The second solution seems to be working perfectly for our needs.

Thank you!
