### ISSUE TITLE
Smooth quality switching

### ISSUE THREAD

**Issue by MolchanovDmitry** [google/ExoPlayer#10406]
I am using `setTrackSelectionParameters` to set the required tracks to play:
```
player.trackSelectionParameters =
     player.trackSelectionParameters
         .buildUpon()
         .setTrackSelectionOverrides(..)
         .build()
```
But after calling `setTrackSelectionParameters` there is a delay before the new tracks start playing.

Is there a way to smoothly switch tracks as they are ready?

**Comment by christosts** [comment]
> But after calling setTrackSelectionParameters there is a delay before the new tracks start playing.

By delay, I understand you mean that playback pauses and rebuffers. If the new parameters cause a change in a track, the player will drop any buffered data and start buffering the newly selected track.

> Is there a way to smoothly switch tracks as they are ready?

You probably need to tune the adaptive track selection logic for what you are trying to achieve, please see #6630 and likely [this comment](https://github.com/google/ExoPlayer/issues/6630#issuecomment-1023007702).

Closing this for now, please re-open if the answer is not sufficient.
