### ISSUE TITLE
How to call setConstrainAudioChannelCountToDeviceCapabilities(false) in demo app?

### ISSUE THREAD

**Issue by ybai001** [google/ExoPlayer#10405]
In latest code (dev branch), variable constrainAudioChannelCountToDeviceCapabilities is set to TRUE in defaultTrackSelector.

I'd like to change it to FALSE in my demo app. The first idea is in PlayerActivity::initializePlayer() method, adding one line as below:
` player = playerBuilder.build();`
`trackSelectionParameters`
`    .buildUpon()`
`    .setConstrainAudioChannelCountToDeviceCapabilities(false);    // Here is what I added.`          
`player.setTrackSelectionParameters(trackSelectionParameters);`

Unfortunately, this is not feasible because setConstrainAudioChannelCountToDeviceCapabilities() is a public method of class DefaultTrackSelector but not a one of class TrackSelectionParameters.

Do you have any suggestion about how to set constrainAudioChannelCountToDeviceCapabilities to FALSE without changing ExoPlayer  core library code? Or do you think it is reasonable to add setConstrainAudioChannelCountToDeviceCapabilities() method to TrackSelectionParameters class too?

Thank you very much in advance.

**Comment by christosts** [comment]
The fastest way is in `PlayerActivity.initializePlayer()` as you suggest, you can set it with

```java
player.setTrackSelectionParameters(
  new DefaultTrackSelector.Parameters.Builder(this)
    .setConstrainAudioChannelCountToDeviceCapabilities(false).build());
```

`DefaultTrackSelector.Parameters` is a subclass of `TrackSelectionParameters`.  

Note that by doing the above, the demo app will always use these parameters when playback starts. Persisting/loading parameters, e.g. `PlayerActivity.onSaveInstanceState()`, will no longer function.
