### ISSUE TITLE
getCurrentPosition returning different values in LibopusAudioTrackRenderer

### ISSUE THREAD

**Issue by Brahmasmi** [google/ExoPlayer#1040]
The ExoPlayer.getCurrentPosition function seems to be returning different values in the following equivalent cases:
1) After a pause, in the onPlayerStateChanged callback (playWhenReady=false, playbackState=READY),
```
a = getCurrentPosition()
```
2) Before resuming playback,
```
b = getCurrentPosition()
```
Ideally, (a == b) should evaluate to true, since the position after pause should be equal to the position before resuming playback. However, there is always a slight difference in these values, in the order of tens of milliseconds.
a) Is this to be expected or is this is a bug?
b) If this is to be expected, in the case of resuming playback after a pause, what would be the recommended practice to decide whether a seek is required or not? Would an absolute difference of 100 ms, or its roundabouts, be a good metric to skip seeking or is there a better way to accomplish this?

**Comment by ojw28** [comment]
This behavior is expected. It's a result of the threading model that ExoPlayer uses, and is unavoidable (there are different ways to do it, but each have their own quirks; it's not possible to make cross-thread message passing completely transparent to the user of the API, unless you want your application thread to hang in some cases instead ;)).

I'm not sure what you mean when you ask how you would determine whether a seek is required. In nearly all applications I would expect a seek to be triggered by some kind of event (e.g. the user dragging the seek bar, or a button being pressed, or something). In which case a seek would never be required unless an event has occurred. Note that you can seek when paused (or at any time), so it's not like you have to wait until you're resuming to perform a seek, either. Please clarify exactly what the use case is?

**Comment by Brahmasmi** [comment]
Understood that the seek can be performed at any time in the player lifecycle. Thank you. In my case, the player was seeking and failing, which resulted in this post as well as #1039 . I was unable to determine whether the mechanism for performing seek was incorrect or the trackrenderer was not seeking correctly.

Now on to the use case. From what I understand, on Android, the player can transition to a paused state either via a user interaction or the system taking away the audio focus. The audio focus loss can be temporary or permanent. Now, consider the following simple use case:
1) User presses pause
2) User presses play after some seconds

There are two opportunities to capture the current position of the player - before player.pause and in the onPlayerStateChanged callback. The first instance would be correct from the user perspective, since it is representative of the position where the user wants to pause. The second instance would be correct from the player perspective, since it is where the player actually may have paused. There would be some delta between these two positions. Since there is no way to determine this delta, there is no way to determine which of the two is the correct instance to capture the position. Currently, it is being captured in both instances, with the second overwriting the first.

However, the player does not report the final position even in the second instance. This implies that before resuming playback in step 2), a simple check of (capturedPosition==currentPlayerPosition) fails. Typically, a failure of this condition should result in a seek, since the last captured position is not the same as the current player position.

However, in this instance, the seek is trivial since the difference between a and b is within the order of tens of milliseconds. But, it may carry a non-trivial cost, especially if the seek happens over a slow data connection. Hence, my query so as to what would be the recommended practice to decide whether seek is required or not, before resuming playback after a pause. Currently, the seeking is being skipped if abs(currentPlayerPosition-capturedPosition) <= 100ms. I am curious to understand if there is a better way to accomplish this. I hope I have been able to flesh out the use case.

**Comment by ojw28** [comment]
I don't understand why you would ever want to seek between (1) and (2). If the user pauses and then presses play, they expect playback to resume from where the playback stopped. Which is accomplished by not calling seek between the two.

**Comment by Brahmasmi** [comment]
I may be wrong here, but please bear with me.

Thinking aloud based on my limited understanding, a player could encounter an error after being paused. This would require a player.release and player=null in the onPlayerError callback to clean up. Before resuming playback, the player would be null and would need to be instantiated and prepared. Thus, when resuming playback, the player may actually be at the start, since it may have been recreated. This would imply checking if it is at the last captured position, and if not, seek to it.

As another scenario, consider the case where the playback service is restarted by the system. When pausing, the service needs to release the wifi lock and the partial wake lock, and do a stopForeground(false). This implies that between the pause and the resume, the service could get garbage collected by the system and restarted. Again, the player would need to be instantiated and prepared.

Essentially, the case that is being guarded against is the player being recreated. Hence the seek. In case I am missing something here or am wrong about the above scenarios, please let me know.

**Comment by ojw28** [comment]
Ah. I see what you mean, but I think the solution is simpler than you think it is :).

- For the case where you're using the same player instance and where you want to pause/resume, you don't need to do anything.
- For the case where the player is being released and null'd and a new instance is being created later, you do need to restore the position.

The implement the second of these, you can just call getCurrentPosition to read the position immediately before releasing the player. Then when you instantiate the new player, immediately call seekTo to restore the position. If you look at the demo app, this is what it does. There's no need to do anything more complicated than that.

As a final point, note that getCurrentPosition is expected to return the correct position even if the player encounters an error, or whatever, so you don't need to worry that calling getCurrentPosition immediately prior to release might give you a bogus value. You can rely on the position returned being correct.

**Comment by Brahmasmi** [comment]
I had tried something similar, but multiple factors led to it not working:
1) The audio files I was using did not have the seek indexes, something that I learnt in #1039 and is now resolved.
2) I had wrapped the ExoPlayer instance in the util.PlayerControl. The playerControl.seekTo does not seem to work if called when the player is still preparing. I suppose it might be primarily because when the player is preparing, the getDuration check in playerControl.seekTo fails and hence the seek happens to 0, which is the start.

Thank you for the explanation and the information. I have now removed the PlayerControl completely and this works. And if the getDuration checks performed in the PlayerControl functions are actually applicable for ExoPlayer, please let me know.

**Comment by ojw28** [comment]
- `PlayerControl.seekTo` is intended to be called internally. You shouldn't call it directly. Always perform a seek directly on the player from your own code.
- As per the `PlayerControl` Javadoc, it's expected that most applications will not make use of that class (i.e. I'd expect most applications to be implementing their own playback controls UI of some kind).

Closing this, since it sounds like your issues have been resolved. Thanks!
