### ISSUE TITLE
How to normalise output audio streams?

### ISSUE THREAD

**Issue by coveroid** [google/ExoPlayer#10400]
Hello, First of all thanks for the great player you made.

I'm facing a problem, i play different streams (MP3,HLS, Dash etc ...) with the exoplayer , but none all of them have the same output volume result. I would like to found a way to normalize the output volume.

I tried         myAudioSink.setVolume(1F); but seems like the streams with low internal volume , cannot reach the maximum speaker volume. So basicaly i would like to get the same decibel output for each audio stream.

But i don't even know by where to start, if you could help / guide me about that would be really appreciate. 

Thanks

**Comment by tonihei** [comment]
In order to normalize the volume, the player would need to read and analyze the entire streams to figure out the relative volume and adjust accordingly. This is usually better done by re-encoding if at all possible. Please also see #3349 where a similar question has been asked.
