### ISSUE TITLE
Stream request results in multiple requests

### ISSUE THREAD

**Issue by juliusspencer** [google/ExoPlayer#1041]
**Description**

When the ExoPlayer is used to play certain audio files by streaming them from the network, the ExoPlayer makes 2 attempts to retrieve the file at varying byte offsets before commencing playback.

Steps to reproduce the problem from the demo application:
1) Install the demo application
2) Select Google Play (MP3 Audio)

**Details**
One execution of the example above, connected over wifi on a Nexus 6P, produced the following network requests:

GET /exoplayer-test-media-0/play.mp3 HTTP/1.1
User-Agent	ExoPlayerDemo/1.5.2 (Linux;Android 6.0.1) ExoPlayerLib/1.5.2
Accept-Encoding	identity
Host	storage.googleapis.com
Connection	Keep-Alive

GET /exoplayer-test-media-0/play.mp3 HTTP/1.1
Range	bytes=313-
User-Agent	ExoPlayerDemo/1.5.2 (Linux;Android 6.0.1) ExoPlayerLib/1.5.2
Accept-Encoding	identity
Host	storage.googleapis.com
Connection	Keep-Alive

**Expected behaviour**
Only a single network request is made by the ExoPlayer. 

**Notes**
We encounter this problem with AAC/MP4 files as well.

When we test this file (/exoplayer-test-media-0/play.mp3) with the Android MediaPlayer, it loads in one request.

GET /exoplayer-test-media-0/play.mp3 HTTP/1.1
User-Agent	stagefright/1.2 (Linux;Android 5.0.2)
Host	storage.googleapis.com
Connection	Keep-Alive
Accept-Encoding	gzip

**Comment by ojw28** [comment]
Yes, this is a known sub-optimality related to how stream selection works in `ExtractorSampleSource` at the moment. We plan on fixing it.

**Comment by juliusspencer** [comment]
Thanks for the quick response, can we expect this behaviour for all tracks (MP3, AAC etc) or just some?

**Comment by ojw28** [comment]
I believe this currently happens for all container media types. It does not occur for DASH or SmoothStreaming playbacks.

**Comment by swxch1985** [comment]
Will you have the plan to fix this issue?

**Comment by ojw28** [comment]
We're currently working on a 2.0 version of ExoPlayer, in which this issue will be fixed. We do not have an ETA as of now.

**Comment by ojw28** [comment]
This is fixed in the [2.x.x experimental branch](https://github.com/google/ExoPlayer/tree/dev-2.X.X-experimental).
