### ISSUE TITLE
MediaSession play/pause events not propagated to LeanbackPlayerAdapter

### ISSUE THREAD

**Issue by TheBeastLT** [google/ExoPlayer#10420]
### ExoPlayer Version

2.18.0

### Devices that reproduce the issue

Any Android TV

### Reproducible in the demo app?

Yes

### Reproduction steps

Connect player with a MediaSession and try to play/pause the video using mobile.

### Expected result

When clicking play/pause the controls overlay should be triggered and their state updated.

It seems that the `LeanbackPlayerAdapter` [listens](https://github.com/google/ExoPlayer/blob/03569f9e6536e6c60cb585115d6d7352a4deab71/extensions/leanback/src/main/java/com/google/android/exoplayer2/ext/leanback/LeanbackPlayerAdapter.java#L238-L240) to `onPlaybackStateChanged` player events, but play/pause action called from `MediaSessionConnector.` directly on a `Player` instance triggers only `onPlayWhenReadyChanged` event, which is not handled in the `LeanbackPlayerAdapter`.
By using `ForwadingPlayer` when setting player for the `MediaSessionConnector.` you can workaround this issue:
```
mediaSessionConnector.setPlayer(object : ForwardingPlayer(player) {
    override fun play() {
        playerAdapter.play()
    }

    override fun pause() {
        playerAdapter.pause()
    }

    override fun stop() {
        playerAdapter.pause()
    }
})
```

### Actual result

Controls overlay is not triggered and play/pause action stays in previous incorrect state.

### Media

Not applicable

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by christosts** [comment]
Thank you for reporting this. We submitted a fix (this issue will be updated once the commit is pushed the dev-v2 branch) which will be included in the next release (2.18.1 or 2.19.0, which ever comes first).
