### ISSUE TITLE
Issues with performing cleaning Exoplayer or hiding it and then switching views.

### ISSUE THREAD

**Issue by darren5231** [google/ExoPlayer#10422]
Hi there I've been looking all around to solve the issue as described in the title. I have a single instance of the Exoplayer and been trying to either overlap a view to not show the last frame when I clean the Exoplayer instance with the release method or trying to get the player to hide everything when I don't need it but both approaches are failing me. What I have right now is this layout in my android fragment component:

```
...
    <androidx.constraintlayout.widget.ConstraintLayout
        ...
    >
    
        <com.google.android.exoplayer2.ui.PlayerView
            android:id="@+id/player"
            android:visibility="invisible"
            ....
        />
        
        <androidx.constraintlayout.widget.ConstraintLayout
            android:id="@+id/background"
            ...
        >
            <ImageView 
                android:id="@+id/image1"
                ...
            />
            
            <ImageView 
                android:id="@+id/image2"
                ...
            />
        
        </androidx.constraintlayout.widget.ConstraintLayout>


    </androidx.constraintlayout.widget.ConstraintLayout>
...
```

And the logic follows with me creating an Exoplayer instance and grabbing the "player" view to set the newly created instance as directed from the exoplayer docs. Now the flow for this page as is supposed to operate as follows:

1. When this page load you're supposed to show "image1" and hide the Exoplayer
2. Pressing a button (right in my case) shows "image2" and preload Exoplayer with a video
3. When the video loads show "player" and hide "image2"
4. if the user presses the back key (left in my case) clean Exoplayer instance and gracefully show "image1" again.

Now I'm having issues with executing of what I want step 4 because when I clean the Exoplayer with either of these methods: release, stop, clearVideoSurface it results in the frame being persisted and sometimes distorted when I try to switch back to "image1". Or when I try to simply hide the "player" it results a jarring frame with the underlying elements under my fragments to be shown until "image1" pops in. I'd like to ask if there is a clean way to show "image1" cleanly without any jarring effects? In terms of the image loading logic I'm using it's all native android with a png resource I refer to when they need to be loaded.

Thanks in advance if you answer this.

**Comment by marcbaechinger** [comment]
>  when I clean the Exoplayer with either of these methods: release, stop, clearVideoSurface it results in the frame being persisted

I thought be default the last frame is not retained. What is your setting for [keepContentOnPlayerReset](https://github.com/google/ExoPlayer/blob/release-v2/library/ui/src/main/java/com/google/android/exoplayer2/ui/StyledPlayerView.java#L151)?

**Comment by darren5231** [comment]
@marcbaechinger thanks for the response. Seems playing around the translationZ property of the player view helped get the behaviour I'd like. I don't set keepContentOnPlayerReset to anything but what I noticed is when I try to hide the player view with the View.GONE or View.INVISIBLE property while it's stopped or playing, is that briefly the player view would turn transparent showing the underlying activity/fragment components before the layout operations of the view I'd like to be in place are displayed. 

Sorry for the confusion as I thought this was the last frame of the playing content but it actually was the player performing its cleanup mechanism correctly.
