### ISSUE TITLE
How to select an audio track by index

### ISSUE THREAD

**Issue by SharyRajpoot** [google/ExoPlayer#10436]
Issue:
There are some streams available online which have multiple audio tracks some are with proper information and metadata and some are black but they still have multiple audio tracks.

e.g:
**Movie XYZ** has 2 audio tracks...like this
```
Format(1/257, null, null, audio/mp4a-latm, mp4a.40.2, -1, hi, [-1, -1, -1.0], [2, 48000])
Format(2, null, null, audio/mp4a-latm, mp4a.40.2, -1, en, [-1, -1, -1.0], [6, 48000])
```
`This has almost complete info required to change audio tracks.. e.g en, hi`

Now there's another **Movie ABC** which has audio tracks like this...
```
Format(1/257, null, null, audio/mp4a-latm, mp4a.40.2, -1, null, [-1, -1, -1.0], [2, 48000])
Format(2, null, null, audio/mp4a-latm, mp4a.40.2, -1, null, [-1, -1, -1.0], [6, 48000])
```
Now noticed here a language param is `null` from track group formats..

So my question is how can I change these types of tracks when we have no lang. info available but sure have multiple audio tracks.
And i can't use the `trackSelector.setParameters(trackSelector.getParameters().withPreferredAudioLanguage(language))` here as this required a known lang. param but in **Movie ABC** we got `null, null` for two audio tracks.

So I need to know if there is any built-in function available like `trackSelector` that can help to change audio tracks like by index or simpler approach.
Hope you got my point and issue here..

**Comment by marcbaechinger** [comment]
The DevGuide has a page about track selection that includes a section [`Selecting specific tracks`](https://exoplayer.dev/track-selection.html#selecting-specific-tracks) that cover this case I think. 

You need to find the audio track group you are interested in and then you can select by index:

```
player.setTrackSelectionParameters(
    player.getTrackSelectionParameters()
        .buildUpon()
        .setOverrideForType(
            new TrackSelectionOverride(
                audioTrackGroup.getMediaTrackGroup(),
                /* trackIndex= */ 0))
        .build());
```

**Comment by yuroyami** [comment]
In case you don't know how to obtain track indexes, use the following code to analyze audio tracks of a certain media item :

```kotlin
fun analyzeTracks(exoplayer: ExoPlayer) {
        /* Getting the current tracks from the instance of ExoPlayer */
        val tracks = exoplayer.currentTracks

        for (group in tracks.groups) {
            val trackGroup = group.mediaTrackGroup
            val trackType = group.type
            if (trackType == C.TRACK_TYPE_AUDIO {
                for (i in (0 until trackGroup.length)) {
                    val format = trackGroup.getFormat(i)
                    val index = trackGroup.indexOf(format)
                         
                    /** Creating a custom 'Track' instance for every track in a track group **/
                    val track = Track()
                    track.trackGroup = trackGroup
                    track.index = index
                    track.format = format
                    track.selected = group.isTrackSelected(index)

                   /* Do what you wish with the track information, for example, use them in an override like @marcbaechinger did */

                }
            }
        }
    }
```


And this is the custom Track class I used above to save information about a track (format):

```kotlin
/*****************************************************************************************
 * Track wrapper class. It encapsulates all info we need about a track in a track group  *
 *****************************************************************************************/

class Track {

    /** The corresponding format (ExoPlayer calls every track a format **/
    lateinit var format: Format

    /** The index of the format (track) **/
    lateinit var index: Int

    /** The trackgroup in which the track/format exists **/
    lateinit var trackGroup: TrackGroup

    /** The current status of the track **/
    lateinit var selected: Boolean
}```

**Comment by SharyRajpoot** [comment]
@Reddnek I've done all the things already regarding changing audio/video tracks at runtime. It's just I noticed something [above](https://github.com/google/ExoPlayer/issues/10436#issue-1304837361) and wonder how we are gonna change track like this type of data and @marcbaechinger sure will try your solution as well and let you know about its results.

**Comment by SharyRajpoot** [comment]
Well, buddies above code and documentation need to be updated for the new and current releases of ExoPlayer. The things you told me is different in the latest version of ExoPlayer.

**Comment by SharyRajpoot** [comment]
Remove...

**Comment by SharyRajpoot** [comment]
> The DevGuide has a page about track selection that includes a section [`Selecting specific tracks`](https://exoplayer.dev/track-selection.html#selecting-specific-tracks) that cover this case I think.
> 
> You need to find the audio track group you are interested in and then you can select by index:
> 
> ```
> player.setTrackSelectionParameters(
>     player.getTrackSelectionParameters()
>         .buildUpon()
>         .setOverrideForType(
>             new TrackSelectionOverride(
>                 audioTrackGroup.getMediaTrackGroup(),
>                 /* trackIndex= */ 0))
>         .build());
> ```

This worked out for me and I have managed to change the audio track by index and group instead of language code.
Also one thing more I was using old lib. 2.17.1 and not able to find these fun. Now I upgraded to the latest 2.18 and implement the required features. I guess you should mention in your doc. that we are currently viewing the doc. for 2.xx version e.g: 2.18.
On each page of ExoPlayer [doc](https://exoplayer.dev).

**Comment by tonihei** [comment]
One further comment:

If you tracks look like in the example above, you can select them based on channel count preferences
```
Format(1/257, null, null, audio/mp4a-latm, mp4a.40.2, -1, null, [-1, -1, -1.0], [2, 48000])
Format(2, null, null, audio/mp4a-latm, mp4a.40.2, -1, null, [-1, -1, -1.0], [6, 48000])
```
The 6 channel track should be selected by default (if supported by the device) and you can use `setMaxAudioChannelCount(2)` to select the Stereo track.
