### ISSUE TITLE
MPEG-TS over RTSP Stream

### ISSUE THREAD

**Issue by AleSoHe** [google/ExoPlayer#10433]
I've been searching in both the documentation and the source code to check if the RTSP Media Source can handle the stream contained in MPEG-TS.

* RTSP works fine.
* MPEG-TS through UDP works fine.
* But when sending MPEG-TS with RTSP, the player doesn't work. It's not the case for many players such as VLC, GStreamer, Totem, MPlayer, etc.

Can ExoPlayer play video contained in MPEG-TS through RTSP?

**Comment by claincly** [comment]
ExoPlayer does not support TS at the moment and we don't have plan to support it any time soon. 

For a list of supported formats, please see [this folder](https://github.com/google/ExoPlayer/tree/release-v2/library/rtsp/src/main/java/com/google/android/exoplayer2/source/rtsp/reader)
