### ISSUE TITLE
when i play mp4 ,it can see but no voice.why?!

### ISSUE THREAD

**Issue by longmh** [google/ExoPlayer#1043]
when i play mp4 ,it can see but no voice.why?!
how to set?

**Comment by ojw28** [comment]
You'll need to provide a sample for us to answer this. Most likely the audio in the mp4 is a format not supported by Android.

**Comment by longmh** [comment]
The mp4 is a format  supported by Android，because i use it to play by other videoplayer, and it use.
this is the mp4 link：
http://f.ailesoft.com//video/20151207162439/7f5976e24a6a3d390fb8c27239cf8ce7/video.mp4

**Comment by AquilesCanta** [comment]
I have just played the video with the DemoPlayer, and everything works fine.  Isn't it possible that there is a problem with your configuration?
