### ISSUE TITLE
Why exoplayer cant play rtmp live videos that doesn't contain audio? 

### ISSUE THREAD

**Issue by AhmedHumk** [google/ExoPlayer#10438]
I use this library to stream audio from Android

https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/1157

The above issue were related to exoplayer that doesn't play rtmp live video without audio included..

How can i play rtmp stream even if it doesn't have audio?

**Comment by marcbaechinger** [comment]
There is a user in that thread saying that it works on `2.18.0` as opposed to `2.13.1` that you are using. Has it been fixed since then or is it still an issue with a recent version?

**Comment by AhmedHumk** [comment]
as i mentioned in the same issue 
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/1157#issuecomment-1184962747

i have migrated to the latest exoplayer 2.18.0

and the problems still persist if the stream has no audio exoplayer unable to play it , if the stream has audio exoplayer playing it .

in vlc vitamio stream playing normaly even if the audio disabled 

i still couldnt figure out how to make exoplayer play Rtmp stream that has no audio or has empty audio header

my current playing rtmp code  

```
public void initexo(){
        AdaptiveTrackSelection.Factory videoTrackSelectionFactory = new AdaptiveTrackSelection.Factory();
        TrackSelector trackSelector = new DefaultTrackSelector(
                b4a.context,
                videoTrackSelectionFactory
        );

        exoPlayer = new ExoPlayer.Builder(b4a.context)
                .setTrackSelector(trackSelector)
                .setBandwidthMeter(DefaultBandwidthMeter.getSingletonInstance(b4a.context))
                .build();
        getObject().setPlayer(exoPlayer);
        getObject().setKeepScreenOn(true);

        exoPlayer.addListener(new exoEventsLs());
    }
```

```
public void PlayRtmp(String videoURL){

        RtmpDataSource.Factory rtmpDataSourceFactory = new RtmpDataSource.Factory();
        MediaSource videoSource = new ProgressiveMediaSource.Factory(rtmpDataSourceFactory)
                .createMediaSource(MediaItem.fromUri(Uri.parse(videoURL)));
        exoPlayer.setMediaSource(videoSource);
        exoPlayer.prepare();
        exoPlayer.setPlayWhenReady(true);
    }
```

i am using exoplayer 2.18.0 i have tried every thing with no luck . the user who answer its working did not prove or provide his solution .

**Comment by marcbaechinger** [comment]
Can you provide us with a way how we can repro that? Like how can we test this with such a stream with disabled audio that still sends the audio headers (if I understand correctly).

**Comment by AhmedHumk** [comment]
@marcbaechinger ok give me a moment

**Comment by AhmedHumk** [comment]
i have found the issue it was in the bitrate on the fly within the library itself 

https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/wiki/Real-time-filters

when disabling the audio the bitrate were is still have the audio bitrate in the stream header which makes exoplayer unable to read it . i am glad to found solution that took me 18 hours to solve . this is not related to exoplayer now thank you for your help .

**Comment by marcbaechinger** [comment]
Well done! Thanks for confirming!

**Comment by AhmedHumk** [comment]
after i fix that issue that were related to the streaming library that were destroy the whole stream, i face an issue with other rtmp streamer that has no sound and exoplayer fail to play it .

this is a compiled rtmp streamer that will give you a choice to stream with sound or without sound.
its connected to my test server.. 
try to stream with sound checked. and play the RTMP With  exoplayer it will work
but if you remove the sound check it will fail to play
https://drive.google.com/file/d/1xjC46Pv52co31ZpvBAYxl4as9Njsh-O5/view?usp=sharing

**Comment by AhmedHumk** [comment]
Cant seems to find any solve around this i tried obs studio and streamed camera without audio exoplayer failed to play it, seems something wrong with exoplayer when decoding a stream that does not have audio

**Comment by AhmedHumk** [comment]
I spent couple of days to discover the issue without luck. But found a similar issue on this issues section.

https://github.com/google/ExoPlayer/issues/6719

I guess that something needed to be taking in consideration when decoding streams that doesn't has audio
