### ISSUE TITLE
Filter playable tracks for offline playback

### ISSUE THREAD

**Issue by chladto1** [google/ExoPlayer#10448]
We are filtering playable DRM tracks for online playback and we want to do the same for offline playback. The issue was discussed in #10341, #4825 and #10114. DRM tracks have different requirements and some one can not be played on the device. We want to filter unplayable tracks before we download them, but we can not find a proper solution. Could you please help us?

**Comment by icbaker** [comment]
It's not obvious to me if you're asking how to change what tracks are chosen when downloading: https://exoplayer.dev/downloading-media.html#downloading-and-playing-adaptive-streams

Or whether you're asking, when selecting tracks, how to identify which are playable on a given device.

Given that it sounds like you already know how to identify which tracks are playable:
> We are filtering playable DRM tracks for online playback and we want to do the same for offline playback

I think your question should be answered by my link above - but let me know if that's not the case, and maybe you could provide a bit more context.

**Comment by chladto1** [comment]
When playback, we set limit resolution to the lowest one, start playback, wait for `onKeyStatusChange` and limit playback to only tracks that comes with `STATUS_USABLE`. We know how to filter tracks for downloading in general. The problem is, how to check which tracks will be playable on the device without start playback and waiting for `onKeyStatusChange`.

**Comment by icbaker** [comment]
Gotcha, thanks for explaining.

Are you using [`OfflineLicenseHelper`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/drm/OfflineLicenseHelper.html) for managing the offline DRM licenses for your content? If so, you should be able to register the same [`OnKeyStatusChangeListener`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/drm/ExoMediaDrm.OnKeyStatusChangeListener.html) by building your `DefaultDrmSessionManager` before passing it to `OfflineLicenseHelper`.

I think (untested) that you will receive a callback when the offline license is acquired, and then that will contain the information you need to decide what stream to select when configuring the download components.

**Comment by chladto1** [comment]
Thanks, looks promising.
