### ISSUE TITLE
exoplayer cant play rtsp video that password include "@" string

### ISSUE THREAD

**Issue by ryanhe4** [google/ExoPlayer#10440]
I have rtsp uri 
rtsp://admin:@admin@169.254.2.100:554/0/onvif/profile2/media.smp

and get below messages
```
E/ExoPlayerImplInternal: Playback error
      UnknownHostException (no network)
```

i think player determines "admin@169.254.2.100:554" as host

is there any method to authenticate with username and pass ?

**Comment by claincly** [comment]
The URI syntax (RFC3986) specifies the user info in a URI to be:

```
      userinfo    = *( unreserved / pct-encoded / sub-delims / ":" )
      unreserved  = ALPHA / DIGIT / "-" / "." / "_" / "~"
      pct-encoded = "%" HEXDIG HEXDIG
      sub-delims  = "!" / "$" / "&" / "'" / "(" / ")"
                  / "*" / "+" / "," / ";" / "="
```

which means the password cannot include `@`. Also it's probably a bad idea to include `username:password` in your URI. 

FWIW we rely on Android's `Uri.getUserInfo()` to parse the URI.
