### ISSUE TITLE
I can't Invalidate StyledPlayerView Widget

### ISSUE THREAD

**Issue by sajjadshahbazi** [google/ExoPlayer#10447]
### ExoPlayer Version

2.17.1

### Devices that reproduce the issue

all devices

### Reproducible in the demo app?

Yes

### Reproduction steps

I want to play an mp4 link and after playing that, I want to clear the StyledPlayerView view. but StyledPlayerView keeps the last frame of the mp4 link. I can't invalidate the StyledPlayerView widget.

mp4 link : https://res.namava.ir/709-147fb5722f543315ad5388d415afd0e8.mp4

### Expected result

I expect when Invalidate StyledPlayerView Widget, the view of StyledPlayerView to be black. same as the state of before assign exoPlayer.

### Actual result

I invalidate the StyledPlayerView widget, but StyledPlayerView keeps the last frame of the mp4 link.

### Media

https://res.namava.ir/709-147fb5722f543315ad5388d415afd0e8.mp4

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by ojw28** [comment]
If you want to reset the view back to how it was before the player was assigned, you should either:

1. Detach the player from the view by calling `playerView.setPlayer(null)`;

or

2. Reset the player by calling `player.stop();` followed by `player.clearMediaItems();`

**Comment by sajjadshahbazi** [comment]
thank you
