### ISSUE TITLE
How to configure forward and rewind time values for player notification manager?

### ISSUE THREAD

**Issue by shaiksalam9182** [google/ExoPlayer#10452]
By default rewind button in the notification seeking player time by 5 seconds but forward button seeking player by 15 seconds. Can't find any direct functions in the player notification manager javadoc.

**Comment by marcbaechinger** [comment]
When you build your player you can set the `seekBackIncrements` or the `seekForwardIncrement` by using the setters of the `ExoPlayer.Builder`. This sets the seek increments generally for all `Player.seekBack()` and `Player.seekForward()` calls on that player instance.

If you want to have the behaviour specific for commands coming from the notification, you can use a `ForwardingPlayer` with which you wrap the player. Then you set the forwarding player to the `PlayerNotificationManager.setPlayer(forwardingPlayer)` and you can override the `seekBack()` and `seekForward()` methods on the forwarding player to customize it to fit your requirements.

**Comment by shaiksalam9182** [comment]
Thanks @marcbaechinger . It's working now
