### ISSUE TITLE
Use small screen to play HEVC video screen distortion, full screen normal

### ISSUE THREAD

**Issue by jianlin00000** [google/ExoPlayer#10455]
I use the official demo of exoplayer (v2.17.1) to play a **HEVC** video on a TV device, and set the size of StyledPlayerView to 480dp x 270dp, the picture of video is distorted and split into two parts. But if I set the size of StyledPlayerView to full screen, the video is normal.The test resources are as follows:
[http://vod2.lemmovie.com/vod/6f2bc675-bad5-942c-59c1-ffe7fbec05bc.m3u8](url)

I don't know if it's a problem with the resources or the player, can you tell me why?

**Comment by ojw28** [comment]
Please fill out the bug report template for this kind of issue. You can find it [here](https://github.com/google/ExoPlayer/issues/new?assignees=&labels=bug%2Cneeds+triage&template=bug.yml). I will close this one, since most of the information necessary to make it actionable is omitted. Thanks!
