### ISSUE TITLE
Can play mp4 link，but no voice！！

### ISSUE THREAD

**Issue by longmh** [google/ExoPlayer#1045]
The mp4 is a format supported by Android，because i use it to play by other videoplayer, and it use.
this is the mp4 link：
http://f.ailesoft.com//video/20151207162439/7f5976e24a6a3d390fb8c27239cf8ce7/video.mp4

**Comment by AquilesCanta** [comment]
I just wrote in the other thread. As I said, I have just played the video with the DemoPlayer, and everything works fine. It makes me think that there is an issue not related to ExoPlayer.

**Comment by ojw28** [comment]
Please make sure you're using the latest version (1.5.3 which was released yesterday, or the dev branch). I believe there were some fixes in 1.5.3 that may have resolved issues similar to the one you describe.

**Comment by longmh** [comment]
Thanks! i used the latest version,and it works fine!
