### ISSUE TITLE
Decoder init failed DTS

### ISSUE THREAD

**Issue by jeprojects** [google/ExoPlayer#1046]
Hi,

I am getting the following error:

```js
com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: [-49999], MediaFormat(1, audio/vnd.dts, -1, 16, -1, -1, -1, -1.0, 2, 48000, und, 0, false, -1, -1)
```

Am I correct in thinking that this is trying to access the hardware decoder on the device but failing (Nexus 6p) because hardware decode support doesn't exist?

If so, does exoplayer include software decoding support? Or do we need to fall back to our own?

Thanks for your help.

**Comment by andrewlewis** [comment]
Yes. That log line would be output when trying to create a decoder for audio/vnd.dts on a device with no decoder that supports it. Like most phones, Nexus 6P does not have a built-in DTS decoder. If possible, it is best to switch to a more widely supported format like AAC.

Note that cf27b83 added a check that there is a decoder for the source MIME type, before the track is enabled. So, on an up to date version of ExoPlayer, you shouldn't see this error if the source MIME type is accurate, and the stream should play with no audio (unless other playable audio formats are present). Is this a DASH stream with an incorrect codecs attribute?

**Comment by jeprojects** [comment]
Thanks @andrewlewis for your help.

This is the part in the mdp file

```js
  <Representation id="5" mimeType="audio/mp4" codecs="mp4a.a9" audioSamplingRate="48000" startWithSAP="1" bandwidth="1512297">
    <AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2"/>
    <BaseURL>audio0_dashinit.mp4</BaseURL>
    <SegmentBase indexRangeExact="true" indexRange="893-1296">
      <Initialization range="0-892"/>
    </SegmentBase>
   </Representation>
```

This was automatically generated using mp4box.

**Comment by andrewlewis** [comment]
You could try changing codecs="mp4a.a9" to codecs="dtsc" to make the codecs attribute consistent with the actual media format. That should hopefully give video-only playback, as no decoders will be found for the audio stream.

**Comment by jeprojects** [comment]
Thanks again.

That did the trick.

I am curious though, the one it selected was AAC, when there is AC3 available next in line.

```js
  <AdaptationSet segmentAlignment="true" group="2" lang="und" subsegmentAlignment="true" subsegmentStartsWithSAP="1">
   <Representation id="6" mimeType="audio/mp4" codecs="ac-3" audioSamplingRate="48000" startWithSAP="1" bandwidth="449268">
    <AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2"/>
    <BaseURL>audio1_dashinit.mp4</BaseURL>
    <SegmentBase indexRangeExact="true" indexRange="869-1260">
      <Initialization range="0-868"/>
    </SegmentBase>
   </Representation>
  </AdaptationSet>
  <AdaptationSet segmentAlignment="true" group="2" lang="und" subsegmentAlignment="true" subsegmentStartsWithSAP="1">
   <Representation id="7" mimeType="audio/mp4" codecs="mp4a.40.2" audioSamplingRate="48000" startWithSAP="1" bandwidth="309860">
    <AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2"/>
    <BaseURL>audio2_dashinit.mp4</BaseURL>
    <SegmentBase indexRangeExact="true" indexRange="900-1303">
      <Initialization range="0-899"/>
    </SegmentBase>
   </Representation>
  </AdaptationSet>
```

Is there something wrong with my configuration? Why would it skip ac3?

**Comment by andrewlewis** [comment]
It could skip AC-3 for the same reason it skips DTS: MediaCodecAudioTrackRenderer only handles the track if the device has a decoder for the track's format, or if there is an HDMI connection that advertises support for playing the format via encoded audio passthrough (on Android L and above).
