### ISSUE TITLE
App UI is lagging when E/BufferQueueProducer is appearing

### ISSUE THREAD

**Issue by menscikov** [google/ExoPlayer#10478]
### ExoPlayer Version

2.18.1

### Devices that reproduce the issue

Xiaomi Redmi Note 11 Pro running Android 12

### Reproducible in the demo app?

Not tested

### Reproduction steps

For some videos my log is spamming with these errors.
I could ignore it, but when these errors occur, the application's UI is lagging.
If i pause the video, lagging disappears.

Error is appearing only with surface type "surface_view". If i set it to "texture_view", everything is ok.

Why it is happening? Maybe UI is lagging because of logs? Maybe there is a way to disable these logs in the library to test this case?

`2022-07-27 11:13:19.820 31729-4282/com.my.app D/BufferPoolAccessor2.0: bufferpool2 0xb4000075d6490a28 : 9(18874368 size) total buffers - 8(16777216 size) used buffers - 33042/33051 (recycle/alloc) - 12/33051 (fetch/transfer)
2022-07-27 11:13:20.266 31729-32075/com.my.app E/BufferQueueProducer: [SurfaceView[com.my.app/com.my.app.myActivity]#26(BLAST Consumer)26](id:7bf100000023,api:3,p:31729,c:31729) waitForFreeSlotThenRelock TIMED_OUT 0
2022-07-27 11:13:20.266 31729-32075/com.my.app E/BufferQueueProducer: BQDUMP- BufferQueue mMaxAcquiredBufferCount=2 mMaxDequeuedBufferCount=19
    BQDUMP  mDequeueBufferCannotBlock=0 mAsyncMode=0
    BQDUMP  mQueueBufferCanDrop=0 mLegacyBufferDrop=1
    BQDUMP  default-size=[1080x607] default-format=4 BQDUMP  transform-hint=00 frame-counter=19737
    BQDUMP  mTransformHintInUse=00 mAutoPrerotation=0
    BQDUMPFIFO(0):
    BQDUMP(mConsumerName=SurfaceView[com.my.app/com.my.app.myActivity]#26(BLAST Consumer)26, mConnectedApi=3, mConsumerUsageBits=2304, mId=7bf100000023, producer=[31729:com.my.app], consumer=[31729:com.my.app])
    BQDUMPSlots:
    BQDUMP  [00:0xb40000766aa91c00] state=DEQUEUED 0xb40000766d389c80 frame=19728 [1920x1080:1920,10F]
    BQDUMP  [01:0xb40000766aa91d00] state=DEQUEUED 0xb40000766b0f8a80 frame=19726 [1920x1080:1920,10F]
    BQDUMP  [02:0xb40000766aa91e00] state=DEQUEUED 0xb40000766b2a9600 frame=19721 [1920x1080:1920,10F]
    BQDUMP  [03:0xb40000766b01ec00] state=DEQUEUED 0xb4000075ffdefc80 frame=19724 [1920x1080:1920,10F]
    BQDUMP  [04:
2022-07-27 11:13:20.266 31729-32075/com.my.app E/BufferQueueProducer: Slots:
    BQDUMP  [00:0xb40000766aa91c00] state=DEQUEUED 0xb40000766d389c80 frame=19728 [1920x1080:1920,10F]
    BQDUMP  [01:0xb40000766aa91d00] state=DEQUEUED 0xb40000766b0f8a80 frame=19726 [1920x1080:1920,10F]
    BQDUMP  [02:0xb40000766aa91e00] state=DEQUEUED 0xb40000766b2a9600 frame=19721 [1920x1080:1920,10F]
    BQDUMP  [03:0xb40000766b01ec00] state=DEQUEUED 0xb4000075ffdefc80 frame=19724 [1920x1080:1920,10F]
    BQDUMP  [04:0xb40000766b227000] state=DEQUEUED 0xb40000766cde3600 frame=19725 [1920x1080:1920,10F]
    BQDUMP  [05:0xb40000766b227200] state=DEQUEUED 0xb40000766d38a700 frame=19727 [1920x1080:1920,10F]
    BQDUMP  [06:0xb40000766b227300] state=DEQUEUED 0xb40000766d535400 frame=19731 [1920x1080:1920,10F]
    BQDUMP  [07:0xb4000075b7eb2100] state=DEQUEUED 0xb40000766ae0d680 frame=19732 [1920x1080:1920,10F]
    BQDUMP  [08:0xb40000766d431300] state=DEQUEUED 0xb40000766b20c200 frame=19733 [1920x1080:1920,10F]
    BQDUMP  [09:0xb40000766aa91100] state=DEQUEUED 0xb40000766ccd7100 frame=19720 [1920x1080:1920,10F]
    BQDUMP  [10:0xb40000766aa9
2022-07-27 11:13:20.308 31729-32075/com.my.app E/BufferQueueProducer: [SurfaceView[com.my.app/com.my.app.myActivity]#26(BLAST Consumer)26](id:7bf100000023,api:3,p:31729,c:31729) waitForFreeSlotThenRelock TIMED_OUT 0
2022-07-27 11:13:20.308 31729-32075/com.my.app E/BufferQueueProducer: BQDUMP- BufferQueue mMaxAcquiredBufferCount=2 mMaxDequeuedBufferCount=19
    BQDUMP  mDequeueBufferCannotBlock=0 mAsyncMode=0
    BQDUMP  mQueueBufferCanDrop=0 mLegacyBufferDrop=1
    BQDUMP  default-size=[1080x607] default-format=4 BQDUMP  transform-hint=00 frame-counter=19738
    BQDUMP  mTransformHintInUse=00 mAutoPrerotation=0
    BQDUMPFIFO(0):
    BQDUMP(mConsumerName=SurfaceView[com.my.app/com.my.app.myActivity]#26(BLAST Consumer)26, mConnectedApi=3, mConsumerUsageBits=2304, mId=7bf100000023, producer=[31729:com.my.app], consumer=[31729:com.my.app])
    BQDUMPSlots:
    BQDUMP  [00:0xb40000766aa91c00] state=DEQUEUED 0xb40000766d389c80 frame=19728 [1920x1080:1920,10F]
    BQDUMP  [01:0xb40000766aa91d00] state=DEQUEUED 0xb40000766b0f8a80 frame=19726 [1920x1080:1920,10F]
    BQDUMP  [02:0xb40000766aa91e00] state=DEQUEUED 0xb40000766b2a9600 frame=19721 [1920x1080:1920,10F]
    BQDUMP  [03:0xb40000766b01ec00] state=DEQUEUED 0xb4000075ffdefc80 frame=19724 [1920x1080:1920,10F]
    BQDUMP  [04:
2022-07-27 11:13:20.308 31729-32075/com.my.app E/BufferQueueProducer: Slots:
    BQDUMP  [00:0xb40000766aa91c00] state=DEQUEUED 0xb40000766d389c80 frame=19728 [1920x1080:1920,10F]
    BQDUMP  [01:0xb40000766aa91d00] state=DEQUEUED 0xb40000766b0f8a80 frame=19726 [1920x1080:1920,10F]
    BQDUMP  [02:0xb40000766aa91e00] state=DEQUEUED 0xb40000766b2a9600 frame=19721 [1920x1080:1920,10F]
    BQDUMP  [03:0xb40000766b01ec00] state=DEQUEUED 0xb4000075ffdefc80 frame=19724 [1920x1080:1920,10F]
    BQDUMP  [04:0xb40000766b227000] state=DEQUEUED 0xb40000766cde3600 frame=19725 [1920x1080:1920,10F]
    BQDUMP  [05:0xb40000766b227200] state=DEQUEUED 0xb40000766d38a700 frame=19727 [1920x1080:1920,10F]
    BQDUMP  [06:0xb40000766b227300] state=DEQUEUED 0xb40000766d535400 frame=19731 [1920x1080:1920,10F]
    BQDUMP  [07:0xb4000075b7eb2100] state=DEQUEUED 0xb40000766ae0d680 frame=19732 [1920x1080:1920,10F]
    BQDUMP  [08:0xb40000766d431300] state=DEQUEUED 0xb40000766b20c200 frame=19733 [1920x1080:1920,10F]
    BQDUMP  [09:0xb40000766aa91100] state=DEQUEUED 0xb40000766ccd7100 frame=19720 [1920x1080:1920,10F]
    BQDUMP  [10:0xb40000766aa9
2022-07-27 11:13:20.351 31729-32075/com.my.app E/BufferQueueProducer: [SurfaceView[com.my.app/com.my.app.myActivity]#26(BLAST Consumer)26](id:7bf100000023,api:3,p:31729,c:31729) waitForFreeSlotThenRelock TIMED_OUT 0
2022-07-27 11:13:20.352 31729-32075/com.my.app E/BufferQueueProducer: BQDUMP- BufferQueue mMaxAcquiredBufferCount=2 mMaxDequeuedBufferCount=19
    BQDUMP  mDequeueBufferCannotBlock=0 mAsyncMode=0
    BQDUMP  mQueueBufferCanDrop=0 mLegacyBufferDrop=1
    BQDUMP  default-size=[1080x607] default-format=4 BQDUMP  transform-hint=00 frame-counter=19739
    BQDUMP  mTransformHintInUse=00 mAutoPrerotation=0
    BQDUMPFIFO(0):
    BQDUMP(mConsumerName=SurfaceView[com.my.app/com.my.app.myActivity]#26(BLAST Consumer)26, mConnectedApi=3, mConsumerUsageBits=2304, mId=7bf100000023, producer=[31729:com.my.app], consumer=[31729:com.my.app])
    BQDUMPSlots:
    BQDUMP  [00:0xb40000766aa91c00] state=DEQUEUED 0xb40000766d389c80 frame=19728 [1920x1080:1920,10F]
    BQDUMP  [01:0xb40000766aa91d00] state=DEQUEUED 0xb40000766b0f8a80 frame=19726 [1920x1080:1920,10F]
    BQDUMP  [02:0xb40000766aa91e00] state=DEQUEUED 0xb40000766b2a9600 frame=19721 [1920x1080:1920,10F]
    BQDUMP  [03:0xb40000766b01ec00] state=DEQUEUED 0xb4000075ffdefc80 frame=19724 [1920x1080:1920,10F]
    BQDUMP  [04:
2022-07-27 11:13:20.352 31729-32075/com.my.app E/BufferQueueProducer: Slots:
    BQDUMP  [00:0xb40000766aa91c00] state=DEQUEUED 0xb40000766d389c80 frame=19728 [1920x1080:1920,10F]
    BQDUMP  [01:0xb40000766aa91d00] state=DEQUEUED 0xb40000766b0f8a80 frame=19726 [1920x1080:1920,10F]
    BQDUMP  [02:0xb40000766aa91e00] state=DEQUEUED 0xb40000766b2a9600 frame=19721 [1920x1080:1920,10F]
    BQDUMP  [03:0xb40000766b01ec00] state=DEQUEUED 0xb4000075ffdefc80 frame=19724 [1920x1080:1920,10F]
    BQDUMP  [04:0xb40000766b227000] state=DEQUEUED 0xb40000766cde3600 frame=19725 [1920x1080:1920,10F]
    BQDUMP  [05:0xb40000766b227200] state=DEQUEUED 0xb40000766d38a700 frame=19727 [1920x1080:1920,10F]
    BQDUMP  [06:0xb40000766b227300] state=DEQUEUED 0xb40000766d535400 frame=19731 [1920x1080:1920,10F]
    BQDUMP  [07:0xb4000075b7eb2100] state=DEQUEUED 0xb40000766ae0d680 frame=19732 [1920x1080:1920,10F]
    BQDUMP  [08:0xb40000766d431300] state=DEQUEUED 0xb40000766b20c200 frame=19733 [1920x1080:1920,10F]
    BQDUMP  [09:0xb40000766aa91100] state=DEQUEUED 0xb40000766ccd7100 frame=19720 [1920x1080:1920,10F]
    BQDUMP  [10:0xb40000766aa9
2022-07-27 11:13:20.935 31729-32075/com.my.app E/BufferQueueProducer: [SurfaceView[com.my.app/com.my.app.myActivity]#26(BLAST Consumer)26](id:7bf100000023,api:3,p:31729,c:31729) waitForFreeSlotThenRelock TIMED_OUT 0
2022-07-27 11:13:20.937 31729-32075/com.my.app E/BufferQueueProducer: BQDUMP- BufferQueue mMaxAcquiredBufferCount=2 mMaxDequeuedBufferCount=19
    BQDUMP  mDequeueBufferCannotBlock=0 mAsyncMode=0
    BQDUMP  mQueueBufferCanDrop=0 mLegacyBufferDrop=1
    BQDUMP  default-size=[1080x607] default-format=4 BQDUMP  transform-hint=00 frame-counter=19753
    BQDUMP  mTransformHintInUse=00 mAutoPrerotation=0
    BQDUMPFIFO(0):
    BQDUMP(mConsumerName=SurfaceView[com.my.app/com.my.app.myActivity]#26(BLAST Consumer)26, mConnectedApi=3, mConsumerUsageBits=2304, mId=7bf100000023, producer=[31729:com.my.app], consumer=[31729:com.my.app])
    BQDUMPSlots:
    BQDUMP  [00:0xb40000766aa91c00] state=DEQUEUED 0xb40000766d389c80 frame=19749 [1920x1080:1920,10F]
    BQDUMP  [01:0xb40000766aa91d00] state=DEQUEUED 0xb40000766b0f8a80 frame=19747 [1920x1080:1920,10F]
    BQDUMP  [02:0xb40000766aa91e00] state=DEQUEUED 0xb40000766b2a9600 frame=19742 [1920x1080:1920,10F]
    BQDUMP  [03:0xb40000766b01ec00] state=DEQUEUED 0xb4000075ffdefc80 frame=19745 [1920x1080:1920,10F]
    BQDUMP  [04:
2022-07-27 11:13:20.937 31729-32075/com.my.app E/BufferQueueProducer: Slots:
    BQDUMP  [00:0xb40000766aa91c00] state=DEQUEUED 0xb40000766d389c80 frame=19749 [1920x1080:1920,10F]
    BQDUMP  [01:0xb40000766aa91d00] state=DEQUEUED 0xb40000766b0f8a80 frame=19747 [1920x1080:1920,10F]
    BQDUMP  [02:0xb40000766aa91e00] state=DEQUEUED 0xb40000766b2a9600 frame=19742 [1920x1080:1920,10F]
    BQDUMP  [03:0xb40000766b01ec00] state=DEQUEUED 0xb4000075ffdefc80 frame=19745 [1920x1080:1920,10F]
    BQDUMP  [04:0xb40000766b227000] state=DEQUEUED 0xb40000766cde3600 frame=19746 [1920x1080:1920,10F]
    BQDUMP  [05:0xb40000766b227200] state=DEQUEUED 0xb40000766d38a700 frame=19748 [1920x1080:1920,10F]
    BQDUMP >[06:0xb40000766b227300] state=ACQUIRED 0xb40000766d535400 frame=19752 [1920x1080:1920,10F]
    BQDUMP >[07:0xb4000075b7eb2100] state=ACQUIRED 0xb40000766ae0d680 frame=19753 [1920x1080:1920,10F]
    BQDUMP  [08:0xb40000766d431300] state=DEQUEUED 0xb40000766b20c200 frame=19733 [1920x1080:1920,10F]
    BQDUMP  [09:0xb40000766aa91100] state=DEQUEUED 0xb40000766ccd7100 frame=19741 [1920x1080:1920,10F]
    BQDUMP  [10:0xb40000766aa9`

### Expected result

Fix UI lagging

### Actual result

UI is lagging

### Media

Not applicable

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by tonihei** [comment]
`E/BufferQueueProducer` logs are usually ignorable and more log spam than anything else. In this case it sounds as if they are related to the performance problems you are seeing. This is not exactly easy to debug and I think there is likely nothing we can do about it. What type of video are you trying to play? If you think it should be supported and has consistent performance problems on this device only, you may want to report it Xiaomi.

**Comment by menscikov** [comment]
It's a H264 - MPEG-4 AVC (part 10) 1920x1080, HLS video stream with 5 audio tracks.
I will check it later on different brand device.

**Comment by menscikov** [comment]
I've tested this stream on different brand Android 9 device and there is no lags. Looks like it's a Xiaomi issue.

**Comment by tonihei** [comment]
Thanks for verifying, I'll mark it as a device-specific bug. As said above, I don't think we can do much about it because it's either a performance issue or a device bug. If you can, please feel free to report to Xiaomi with reproduction steps in case they can address it.
