### ISSUE TITLE
Ensuring that Cronet is available before use with ExoPlayer?

### ISSUE THREAD

**Issue by jamesonwilliams** [google/ExoPlayer#10475]
Hi all! To experiment with HTTP/2 and HTTP/3, we've been onboarding the Cronet network stack, as in [the documentation](https://exoplayer.dev/network-stacks.html#cronet). Specifically, I am using the [`CronetDataSource.Factory`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/ext/cronet/CronetDataSource.Factory.html) to bind a CronetEngine into ExoPlayer:

```kotlin
val cronetFactory = CronetDataSource.Factory(
  CronetEngine.Builder(context)
      .addQuicHint("me.endpoint.com", 443, 443)
      .enableQuic(true)
      .build(),
  Executors.newSingleThreadExecutor()
)
```

The [Google documentation](https://developers.google.com/android/reference/com/google/android/gms/net/CronetProviderInstaller) makes it look like there's some work to do in order to make Cronet available via Google Play Services, e.g., to call:
```kotlin
CronetProviderInstaller.installProvider(context)
```

I also see that ExoPlayer has some various tools available for interacting with the CronetEngine and Google Play Services, e.g., [`CronetUtil`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/ext/cronet/CronetUtil.html).

**Question**: do I need to use either of these tools to ensure that CronetEngine is available when I use ExoPlayer? Or does that happen automatically inside of the `CronetDataSource.Factory`? Is there anything else I need to do in my application to ensure that ExoPlayer is *ready* to use Cronet via Play Services, or does the Factory handle it all?

**Comment by tonihei** [comment]
`CronetDataSource.Factory` just uses the provided `CronetEngine`. You can use `CronetUtil.buildCronetEngine(context)` to build an engine. This util method will automatically use the Google Play Services dependency if available on the device or a bundled version in your app if available. 

There are two noteworthy things here:
 - The Util method does roughly the same thing as `CronetEngine.Builder(context)` (which just uses the first version it can find if multiple are available).
 - The Util method doesn't install the Google Play Services update needed for Cronet. You can use `CronetProviderInstaller.installProvider(context)` if you want to trigger this from your app. Most devices with Google Play Services will have this installed already though and it may be easier to just fallback to the default network stack in case the device doesn't have the right version installed (this happens automatically). 
 - The Util method doesn't allow you to customize the `CronetEngine` options (like enabling QUIC), so for your goal it's probably better to just use `CronetEngine.Builder(context)`.
