### ISSUE TITLE
disable ad or lock on player

### ISSUE THREAD

**Issue by Drizkox** [google/ExoPlayer#10492]
Hello , im using exoplayer for playing hosted embed video , but popup make me quit the app , how can i lock the user on or disable action with ad ? ive seen someone doing this and its work perfectly now but idk how to do , im beginner ^^

**Comment by icbaker** [comment]
I'm afraid I don't really understand what you're asking. Please provide complete information as requested in the question template. The template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/question.md).

Unfortunately we can't answer unclear questions or those with insufficient information.

**Comment by Drizkox** [comment]
My english is rly bad sorry , then , i make easy explication x) , im playing external video with exoplayer , like youtube videos etc.... , but i have many popup , and clicking anywhere make me quit the app and open the ad popup , how i can "lock" the user on app and make popup not quit the app
