### ISSUE TITLE
How to remove SimpleExoPlayer instance in Test App?

### ISSUE THREAD

**Issue by hanlareum** [google/ExoPlayer#10508]
I have a question for exoplayer remaining issue.

I found SimpleExoPlayer instance remained in App after ExoPlayer instance deleted.

Please guide to me about fix it.

1. screenshot of android studio profiler
<img width="1445" alt="스크린샷 2022-08-08 오후 3 45 03" src="https://user-images.githubusercontent.com/6751983/183357094-4c6aab68-9dae-4b37-9539-872697db3fe5.png">

2. heap dump.
[memory-20220808T154800.hprof.zip](https://github.com/google/ExoPlayer/files/9279455/memory-20220808T154800.hprof.zip)

3. test code.
[source_codes.txt.zip](https://github.com/google/ExoPlayer/files/9279495/source_codes.txt.zip)

Thanks.

**Comment by christosts** [comment]
I don't see something obviously wrong in the code.* The player indeed passes its own reference to several components which creates some cyclic references. The DefaultTrackSelector constructed in SimpleLivePlayer.playback() should have a reference to the player too, I would have expected to see this on your screenshot too. However, once you call SimpleLivePlayer.release(), the player instance is nullified and none of the other components are reachable from the code, therefore I expect the garbage collector to eventually delete all the player instances. Could it be that GC hasn't been triggered yet?

\* have you considered using only one shared instance of the player and not recreate it every time in SimpleLivePlayer.playback()? Not for saving instances, but for saving some time initialising resources (threads) multiple times.

**Comment by hanlareum** [comment]
I called GC of Android studio Profiler after SimpleLivePlayer.release().
But SimpleExoPlayer still remains.

* I will consider to your suggest about shared instance of ExoPlayer.

**Comment by hanlareum** [comment]
I found one more things.
Same number of PlayerBase as SimpleExoPlayer instance remains.
What is PlayerBase$PlayerBaseWrapper instance?

<img width="1445" alt="스크린샷 2022-08-09 오후 2 58 17" src="https://user-images.githubusercontent.com/6751983/183575870-6c1de834-178f-4c38-9ef3-12d87fc270e1.png">

**Comment by christosts** [comment]
PlayerBase is a component of the Android platform. ExoPlayer does not use PlayerBase component directly. AudioTrack extends PlayerBase so what is being displayed could be the AudioTrack instances. AudioTrack instances are released with some delay (in background thread) after the player is released.

Can you please share some additional information?
- What version of ExoPlayer are you using?
- How exactly are you profiling your test? Can you share the test code in more detail and also describe when these images are taken? Is it immediately after calling SimpleLivePlayer.release()?

**Comment by hanlareum** [comment]
Version Information is below,
1. Android version is 10.
2. ExoPlayer version is 2.16.1.

And test scenario is below,
1. [ SimpleLivePlayer.playback() -> SimpleLivePlayer.stop() ] x 10
2. SimpleLivePlayer.release()
3. Click GC button of Android Studio Profiler.
4. Then capture memory heapDump after 5~6 seconds.

**Comment by christosts** [comment]
I kind of copied your code and gave it a try but don't see the player instance being kept in memory. I am trying with 2.18.1. Will you be able to upgrade to the latest version and try again?

**Comment by hanlareum** [comment]
when i use shared player, memory increment has reduced.
and I will change exoplayer to 2.18.1, then tell you about test result.

**Comment by tonihei** [comment]
Given the was no further message, I'll close this bug now. If you feel the problem still occurs and you have more data and reproduction steps, please feel free to re-open or file a new issue.
