### ISSUE TITLE
How disable predownload manifest.mpd

### ISSUE THREAD

**Issue by aleslanik2** [google/ExoPlayer#10504]
Hi, we have problem with predownloading manifest.mdp. 

Our situation
  * We have tens of thousands of clients. Android app with exoplayer in lastest version (2.18.1)
  * Overyone of them have playlist (ConcatenatingMediaSource) of dash audio (DashMediaSource)
  * The audio is typically spoken word about 45 minutes long
  * Server backend is Wowza and audio storage contains about millions of files
  
Our issue 
  * After set up playlist, Exoplayer will started download manifest.mpd for every item in playlist (typically length of playlist is about 15 items). 
  * Then Wowza will start caching all audio data to memory cache.
  * Due to the number of clients and volume of audios, this leads to fast memory filling (on Wowza side) and inefficient data movement between Wowza and the data store.

My question. There is a way to set the number of items that are preloaded? For example 2 or 3 items ?

Thanks for reply.

**Comment by aleslanik2** [comment]
I think I found a solution. ConcatenatingMediaSource has a useLazyPreparation property in the constructor, which does exactly what I need.

**Comment by icbaker** [comment]
Glad you found a solution!
