### ISSUE TITLE
closed captions not showing as available on mpeg2/h262 video

### ISSUE THREAD

**Issue by Andre-JFerreira** [google/ExoPlayer#10505]
### ExoPlayer Version

2.18.0

### Devices that reproduce the issue

Multiple android tv boxes (both ATV and AOSP)

### Devices that do not reproduce the issue

None

### Reproducible in the demo app?

Yes

### Reproduction steps

Create and entry on the media.exolist.json file for the .ts file used for testing and play it.

### Expected result

we should see the available closed captions as options

### Actual result

no closed captions are available to choose from

### Media

here is a .ts file that you can download where you can reproduce the issue

https://mega.nz/file/5bhGXYCQ#Ev73H9pQgScTPgOSW9kGgRn4j2ksyhiGwmEAu28T4QU

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by Andre-JFerreira** [comment]
Any update on this?

The captions are in DirecTV format. Does this info help in any case?

Thanks

**Comment by icbaker** [comment]
I can see subtitles with the provided file if I manually specify that the file contains a CEA-608 as described here: https://github.com/google/ExoPlayer/issues/10175#issuecomment-1098206520
