### ISSUE TITLE
StyledPlayerView alpha issue

### ISSUE THREAD

**Issue by sam-murphy55** [google/ExoPlayer#10515]
### ExoPlayer Version

2.18.1

### Devices that reproduce the issue

Samsung S9 (Android 10)
Samsung S10 (Android 12)

### Reproducible in the demo app?

No

### Reproduction steps

I am trying to make a UI where a video is playing in a `StyledPlayerView` which fades out when the user scrolls down. However I noticed that the moment I change the `alpha` of the `StyledPlayerView`, the UI messes up. On Samsung S9 (Android 10), it becomes invisible when I change alpha to any value (i.e. 0.99f, 0.5f, 0.2f, etc). On Samsung S10 (Android 12) the opposite is happening, changing alpha does not take effect at all. 

The code is simple:

    Box(
        modifier = Modifier
            .fillMaxSize()
    ) {
          AndroidView(
                modifier = Modifier
                    .fillMaxWidth()
                    .fillMaxHeight(0.65f),
                factory = { context ->
                    StyledPlayerView(context).apply {
                        hideController()
                        useController = false
                        resizeMode = AspectRatioFrameLayout.RESIZE_MODE_ZOOM

                        player = reelsPlayer.player
                        layoutParams = FrameLayout.LayoutParams(
                            ViewGroup.LayoutParams.MATCH_PARENT,
                            ViewGroup.LayoutParams.MATCH_PARENT
                        )
                       alpha = 0.5f // <---- Here
                    }
                }
            )
    }

I tried different versions of ExoPlayer like v.2.17.1 and 2.16.1. I am using Jetpack Compose version `1.2.0-rc02`. I tried the same code but replacing the `StyledPlayerView` with different `Views` like a TextView or `ConstraintLayout` and no issue occurs. I also tried a different approach where I put a `Composable` on top of the `StyledPlayerView` and have this Composable's alpha increase to achieve the same effect. But that didn't work either. The top Composable's `alpha` no longer works. 

This could be very much a Jetpack Compose issue. But it is possible that StyledPlayerView portability to Jetpack Compose is not 100% reliable and that some changes are required for `StyledPlayerView` to work flawlessly.

Edit: I tried this on a regular Android Project (No Jetpack Compose, old View system), and the issue is still there.

Thank you for your help.

### Expected result

StyledPlayerView alpha changes correctly.

### Actual result

StyledPlayerView alpha does change correctly and behaves oddly on different devices.

**Comment by andrewlewis** [comment]
As this is closed maybe you solved the issue already, but if not I would try setting the `surface_type` attribute of the view to `texture_view`. Making a `SurfaceView` translucent doesn't work because they are rendered differently from most views, whereas `TextureView` has an extra level of indirection that means it works like a "normal" view.
