### ISSUE TITLE
Change a custom tag of media item

### ISSUE THREAD

**Issue by JohnGeorgiou** [google/ExoPlayer#10517]
Hi,
Building a MediaItem:
MediaItem mediaItem = new MediaItem.Builder().setUri(someUri).setTag(someTag).build();
is it possible to change the tag of the mediaItem, or do I have to replace the media item with a new one with the new tag?

thank you

**Comment by christosts** [comment]
MediaItem is immutable. May I ask what you're trying to achieve? There may be functionality already in place.

**Comment by JohnGeorgiou** [comment]
I try to feed exoplayer with a list of media items.
Each media item has already a current position, Long milliseconds,  of a previous playback. 

I can use a List<Long> to hold the positions , but I m thinking to pass the position info in the mediaitem as a tag, and may be some extra info too.

So, listening to a new position event, I could save the new position to the current mediaitem's tag,  save the status locally, and afterwards on the cloud.

**Comment by tonihei** [comment]
I think this request is more or less the same as https://github.com/androidx/media/issues/33 and can probably be marked as a duplicate. In both cases we need to find a way to update the `MediaItem` without interrupting playback (e.g. by adding a method to `MediaSource` along the lines of `updateMediaItem` which returns whether it was possible).

**Comment by christosts** [comment]
I'll close this then. @JohnGeorgiou please follow the updates on the linked issue.
