### ISSUE TITLE
Backing the ExoPlayer playlist with another datatype

### ISSUE THREAD

**Issue by OxygenCobalt** [google/ExoPlayer#10511]
My app does not leverage the typical ExoPlayer media datatype, `MediaItem`, as it tends to be too restrictive for my use. Instead, I have my own datatype (`Song`) that can be transformed into a `MediaItem` for use in ExoPlayer. By extension, I have my own data structure for the queue (or "playlist") in my app that is also composed of `Song` instances.

I've been trying to leverage the ExoPlayer playlist system for some time so I could implement Gapless Playback in my app, however, the major issue stems from the way I must convert between `Song` and `MediaItem`:
- I can't just map the `Song` queue to a list of a `MediaItem` instances and then call `setMediaItems`, as such could occur during playback and cause a variety of issues.
- The more "correct" queue methods (ex. `addMediaItem` or `ShuffleOrder`) also do not suffice, as trying to keep two mirrors of the queue in different datatypes, making sure that edits in one also effect the other, is more or less asking for bugs to appear.

Thus, is there a way to extend ExoPlayer so that the playlist is backed with my own datatype, `Song`? That way, I could keep one copy of the queue and simply use the correct methods to notify ExoPlayer when it changes. **ExoPlayer should still try to attempt gapless playback, even with this custom playlist.**

I think `Timeline` is the API I should be using for this, but I have no clue if that's the case or how I could use it to do what I want. Any help on this would be greatly appreciated. Thank you.

**Comment by christosts** [comment]
> Thus, is there a way to extend ExoPlayer so that the playlist is backed with my own datatype, Song?

I don't think you can do that and I would go with option 2 as you described it

> keep two mirrors of the queue in different datatypes

The `Player.Listener` offers callbacks to figure out what's happening on the playlist (such as `onTimelineChanged()` and `onMediaItemTransition()` or the aggregate `onEvents()`) so you can listen to them and map them to your custom `Song` playlist. 

It there a specific state transition that you are concerned with?

**Comment by OxygenCobalt** [comment]
I did some more thought @christosts, and the main issue comes from shuffling really. My app uses it's own shuffling logic that is something like this:
- When re-shuffling, the queue is restored to it's original state (ex. Removed items are re-added), where it is either sorted or shuffled depending on if it is on or off.
- Changing the shuffling state does not change the current track. It is either moved to the front if we are shuffling, or the current index is changed to match with the new position of the song if unshuffled. *This must not interrupt playback.* This is why I can't just call `setMediaItems`, as that reloads the track and resets the position.
- Shuffled queues are not transformed from some unshuffled source queue. 

This is why I said that many of the media item methods are really not ideal for my use. I don't know how I could leverage the existing media item APIs to replicate my custom behavior. 

Also, I don't leverage `MediaSessionConnector` or anything else that would mutate the player timeline outside of my code. I have my own implementations for such that operate on `Song`. Thus, I don't need to change my queue to match the ExoPlayer playlist as much as I need to change the ExoPlayer playlist to match my queue.

Now, I could do something evil and load every possible song into my player, and then add a custom `ShuffleOrder` representing the queue where each shuffled index simply points to the corresponding song loaded in the player. This would get around the issue, however then I could have to deal with the process of generating these `ShuffleOrder` instances probably being quadratic.

**Comment by christosts** [comment]
>  Now, I could do something evil and load every possible song into my player, and then add a custom ShuffleOrder representing the queue where each shuffled index simply points to the corresponding song loaded in the player. 

I'm not sure why you call this evil, sounds like the MediaItems should be added to the player anyway, but maybe I'm missing information about your app. If you don't like ShuffleOrder, you may want to try `Player.moveMediaItems()` alternatively and change the positions of already queued MediaItems.

> This would get around the issue, however then I could have to deal with the process of generating these ShuffleOrder instances probably being quadratic.

I think this can be achieved in linear time, maybe with a few iterations over the playlist structure you are using. 

I'm inclined to close this is issue as it seems the current APIs offered by the player are sufficient for your use-case.

**Comment by OxygenCobalt** [comment]
Yeah, I think that's the best solution overall. I just assumed it would be quadratic (or close-to quadratic) since I would have to do something like:

```
for (every song in the queue) {
   idx = library.indexOf(song)
   addToShuffleOrderArray(idx) 
}
```

Which means I'm iterating through a larger list for each song in a smaller list. Maybe I'm wrong though. I do know however that I could optimize away trivial operations like moves and removals without having to run this routine.

**Comment by christosts** [comment]
For the fun of it(!), I'm almost certain you don't have to call `indexOf()` in the for-loop, which would cause the quadratic complexity. You could store 2 maps that map item-to-position (or position-to-item) for before and after the shuffle (needs two iterations), and then find for each item find its previous and new position with look-ups on the maps. This obviously comes with the cost of extra space for the maps. Overall, the playlist size should be so small than it doesn't really make a difference to the user.

**Comment by OxygenCobalt** [comment]
Okay, turns out that the idea I proposed doesn't really work @christosts.

I made this implementation that sort of does what I want:
```kotlin
class QueueShuffleOrder(private val to: IntArray, private val from: IntArray) : ShuffleOrder {
    override fun getLength() = to.size

    override fun getFirstIndex() = to.getOrElse(0) { C.INDEX_UNSET }

    override fun getLastIndex() = to.getOrElse(to.lastIndex) { C.INDEX_UNSET }

    override fun getNextIndex(index: Int) =  to.getOrElse(from[index] + 1) { C.INDEX_UNSET }

    override fun getPreviousIndex(index: Int) = to.getOrElse(from[index] - 1) { C.INDEX_UNSET }

    // These can't occur since the player isn't connected to anything that could change the
    // media items.

    override fun cloneAndClear(): ShuffleOrder {
        throw UnsupportedOperationException()
    }

    override fun cloneAndInsert(insertionIndex: Int, insertionCount: Int): ShuffleOrder {
        throw UnsupportedOperationException()
    }

    override fun cloneAndRemove(indexFrom: Int, indexToExclusive: Int): ShuffleOrder {
        throw UnsupportedOperationException()
    }

    companion object {
        fun from(queue: List<Song>, mapping: Map<Long, Int>): QueueShuffleOrder {
            val to = IntArray(queue.size)
            val from = IntArray(queue.size)
            for (entry in queue.withIndex()) {
                val playerIndex = requireNotNull(mapping[entry.value.id])
                to[entry.index] = playerIndex
                from[playerIndex] = entry.index
            }
            return QueueShuffleOrder(to, from)
        }
    }
}
```

But there is one crucial flaw: There can be multiple instances of the same song in a queue. For example, `MediaItem` 3 in the player could correspond to `Song` 4 and 5, and the shuffle order has no way to find which index the player is truly at based on the raw player index. The only way I could fix this would be:

1. For ShuffleOrder to use the index based on the shuffled indices, which is absurd to every use case except for mine.
2. To use the "true" index value I have in another object, but `ShuffleOrder` should be stateless, so I can't do that. 

Care to elaborate on how I could leverage `moveMediaItems`?
