### ISSUE TITLE
Disabled forward seeking but should enable previous seek

### ISSUE THREAD

**Issue by nagarrorohit** [google/ExoPlayer#10528]
Hi
I am facing some problem in exoplayer when I upgrade exoplayer dependency so basically while upgrading I see that **ControlDispatcher** and **DefaultControlDispatcher** have been removed from library and It's also mentioned that we should use Forwarding player for the same but I am not able to achieve proper result. I want to disable forward seek and enable previous seek.
This question has also been asked in this issue: https://github.com/google/ExoPlayer/issues/4945
but here in this we are using 
playerView.setControlDispatcher(controlDispatcher);

But **ControlDispatcher** and **DefaultControlDispatcher** have already been removed. so how we can achieve same result using forwardingplayer. any help on the same?

**Comment by rohitjoins** [comment]
@nagarrorohit You can achieve the same result using `ForwardingPlayer` by wrapping your player instance inside it and overriding `seekTo()` method as shown below: 

```
ForwardingPlayer forwardingPlayer = new ForwardingPlayer(player){
    @Override
    public void seekTo(int mediaItemIndex, long positionMs){
        maxPlayedPositionMs = Math.max(maxPlayedPositionMs, super.getCurrentPosition());
        super.seekTo(mediaItemIndex, Math.min(positionMs, maxPlayedPositionMs));
    }
};
playerView.setPlayer(forwardingPlayer);
```
You should also take care of other `seekTo()` operations in the `Player` interface.

**Comment by nagarrorohit** [comment]
Thanks @rohitjoins. It's working.
