### ISSUE TITLE
Do not Deprecate Player.Listener.onPlayerStateChanged()

### ISSUE THREAD

**Issue by XIZZW** [google/ExoPlayer#10533]
### [REQUIRED] Use case description

I need to listen for a state where the video is playing. The only way to do that right now is using `Player.Listener.onPlayerStateChanged()`.

```
exoPlayer.addListener(object : Player.Listener {
            override fun onPlayerStateChanged(playWhenReady: Boolean, playbackState: Int) {
                if (playWhenReady && playbackState == ExoPlayer.STATE_READY) {
                    // The video is playing
                }
            }
        })
```

However, this method is marked as deprecated. `onPlaybackStateChanged(int)` and `onPlayWhenReadyChanged(boolean, int)` are being recommended. However, none of them provides the state that the video is actually playing.

`onPlaybackStateChanged()` could means it's still loading and `onPlayWhenReadyChanged` could means it's loaded but still paused.

### Proposed solution
We should un-deprecate `onPlayerStateChanged`

### Alternatives considered
Or adde a new state: `STATE_PLAYING`

**Comment by rohitjoins** [comment]
@GC-Xi You can use either of the options below to know if the video is playing:

1.  `onEvents(Player player, Events events)` callback which has a reference to player and check
```
if (events.contains(Player.EVENT_PLAY_WHEN_READY_CHANGED) && player.getPlaybackState() == ExoPlayer.STATE_READY) {
    // The video is playing
}
```
2. `Player.isPlaying()` which returns whether the player is playing.

**Comment by XIZZW** [comment]
@rohitjoins That worked. Thanks!
