### ISSUE TITLE
Unresolved reference: addTextOutput

### ISSUE THREAD

**Issue by a-sarollahi** [google/ExoPlayer#10538]
I am updating Exoplayer from 2.15.0 to 2.18.1.

I used `addTextOutput { playerSubtitleView.onCues(it) }` to show the subtitl, but know in the new version I get error `Unresolved reference: addTextOutput`

I also tried to create a class that implements TextRendere.Output and set it to the player with a listener but I can’t get access to the output function in that class.

I appreciate it if you help me to know what should I use instead to fix the issue.

**Comment by deniscoman** [comment]
What's the solution here? I saw "not planed" but what should we do?

**Comment by a-sarollahi** [comment]
Hi, I closed it as it was duplicated.

the solution is instead of using 
`addTextOutput { playerSubtitleView.onCues(it) }`
we must use
```
addListener(object: Player.Listener{
                override fun onCues(cueList: List<Cue>) {
                    super.onCues(cueList)
                    playerSubtitleView.setCues(cueList)
                }
            })
```

**Comment by deniscoman** [comment]
Nvm, I found the answer here: 
https://github.com/google/ExoPlayer/issues/9805
