### ISSUE TITLE
Intercepting notification events

### ISSUE THREAD

**Issue by mpivchev** [google/ExoPlayer#10543]
I would like to intercept the notification events, so I can implement custom functionality when they are fired. Currently, they are being handled in this `NotificationBroadcastReceiver`:

```java
 @Override
    public void onReceive(Context context, Intent intent) {
      Player player = PlayerNotificationManager.this.player;
      if (player == null
          || !isNotificationStarted
          || intent.getIntExtra(EXTRA_INSTANCE_ID, instanceId) != instanceId) {
        return;
      }
      String action = intent.getAction();
      if (ACTION_PLAY.equals(action)) {
        if (player.getPlaybackState() == Player.STATE_IDLE) {
          player.prepare();
        } else if (player.getPlaybackState() == Player.STATE_ENDED) {
          player.seekToDefaultPosition(player.getCurrentMediaItemIndex());
        }
        player.play();
      } else if (ACTION_PAUSE.equals(action)) {
        player.pause();
      } else if (ACTION_PREVIOUS.equals(action)) {
        player.seekToPrevious();
      } else if (ACTION_REWIND.equals(action)) {
        player.seekBack();
      } else if (ACTION_FAST_FORWARD.equals(action)) {
        player.seekForward();
      } else if (ACTION_NEXT.equals(action)) {
        player.seekToNext();
      } else if (ACTION_STOP.equals(action)) {
        player.stop(/* reset= */ true);
      } else if (ACTION_DISMISS.equals(action)) {
        stopNotification(/* dismissedByUser= */ true);
      } else if (action != null
          && customActionReceiver != null
          && customActions.containsKey(action)) {
        customActionReceiver.onCustomAction(player, action, intent);
      }
    }
```

Sadly, I can't replace the receiver with my own, since it's private:

`  private final NotificationBroadcastReceiver notificationBroadcastReceiver;`

I was thinking of maybe overriding `getActions` and `getActionIndicesForCompactView` and make my own custom actions, but the original actions are used in so many cases in functions that are not overridable that I don't think it's possible to mimic when they are called. 

My final solution is to just make my own notification manager from scratch, but I hope it doesn't come to that.

Is there a way that I haven't found to intercept those events?

**Comment by marcbaechinger** [comment]
You can use a `ForwardingPlayer` to intercept the method calls done in `onReceive`. Issue #10212 has some more detail. Please let me know if this helps for your use case.

**Comment by mpivchev** [comment]
`ForwardingPlayer` did the trick, thank you.
