### ISSUE TITLE
Recreating player instance when transitioning from one activity to another

### ISSUE THREAD

**Issue by 1mean** [google/ExoPlayer#10547]
from one activity to another activity. Whether I need to create a new Exoplayer
```
mPlayer = ExoPlayer.Builder(context).build()
...
mPlayer.release()
```
If I switch activities frequently. I need stop the video and release Exoplayer. then create a new ExoPlayer in new Activity.
in my app. I can't use multiple fragments to share one ExoPlayer. so I have to create new ExoPlayer all the time.
Am I doing the right thing with the Exoplayer? 
Thank you very much！！！

**Comment by marcbaechinger** [comment]
Yes, the scenario you are describing is generally the recommended way. When an activity is paused/stopped, the player should release all resources. You are good citizen on your user's device. :)

I would think that creating a new media source and downloading media for playback is the most time-consuming part. Once class-loading is done, creating a new player instance is comparably cheap and renderers need to be reset either way to start rendering the new media. Things like data sources (specifically when using a `Cache`) can be created only once and stored in a static variable to be reused when creating another player instance (see the [`DemoUtil`](https://github.com/google/ExoPlayer/blob/release-v2/demos/main/src/main/java/com/google/android/exoplayer2/demo/DemoUtil.java#L87) of the demo app).

**Comment by 1mean** [comment]
Thank you very much @marcbaechinger
