### ISSUE TITLE
FFmpeg complie issue

### ISSUE THREAD

**Issue by NaveenDevrani** [google/ExoPlayer#10540]
I try to add an FFMPEG extension to my project. rest of all extensions I have successfully added with your all instructions.
but I am facing issues with the FFMPEG extension.

I follow your instructions 

1) cd "<path to project checkout>"
FFMPEG_MODULE_PATH="$(pwd)/extensions/ffmpeg/src/main"

2) NDK_PATH="<path to Android NDK>"

3) HOST_PLATFORM="darwin-x86_64"
4) cd "<preferred location for ffmpeg>" && \
git clone git://source.ffmpeg.org/ffmpeg && \
cd ffmpeg && \
git checkout release/4.2 
&& \
FFMPEG_PATH="$(pwd)"

5) ENABLED_DECODERS=(vorbis opus flac) 
6) cd "${FFMPEG_MODULE_PATH}/jni" && \
ln -s "$FFMPEG_PATH" ffmpeg

7) cd "${FFMPEG_MODULE_PATH}/jni" && \
./build_ffmpeg.sh \
  "${FFMPEG_MODULE_PATH}" "${NDK_PATH}" "${HOST_PLATFORM}" "${ENABLED_DECODERS[@]}"

but i am not able to compile ./build_ffmpeg.sh  file
error below  also attached the screenshot.

Using 8 jobs for make
./build_ffmpeg.sh: line 46: cd: /Users/naveendevrani/Documents/AndroidProject/xtreamapp/extensions/ffmpeg/src/main/jni/ffmpeg: No such file or directory
./build_ffmpeg.sh: line 48: ./configure: No such file or directory
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target `install-libs'.  Stop.
make: *** No rule to make target `clean'.  Stop.
./build_ffmpeg.sh: line 63: ./configure: No such file or directory
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target `install-libs'.  Stop.
make: *** No rule to make target `clean'.  Stop.
./build_ffmpeg.sh: line 76: ./configure: No such file or directory
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target `install-libs'.  Stop.
make: *** No rule to make target `clean'.  Stop.
./build_ffmpeg.sh: line 90: ./configure: No such file or directory
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target `install-libs'.  Stop.
make: *** No rule to make target `clean'.  Stop.

<img width="712" alt="FFMPEg" src="https://user-images.githubusercontent.com/37726754/185825822-210f34dd-f490-4866-9c7b-1232a6e1ca2b.png">

I am using MAC book pro M1 terminal 
can you please check and try to find the mistake 
please help me

**Comment by christosts** [comment]
I just ran the script on 2.18.2 which worked fine. Is this is an issue?
