### ISSUE TITLE
 TTML subtitles not disappeared even if there is no audio

### ISSUE THREAD

**Issue by Xlcghs** [google/ExoPlayer#10556]
Hello 

I have a problem with the TTML subtitles (Png image) with the version of Exo 2.17.
The subtitles are m4s segments with a duration between 2s and 4s presented in the manifest as follows:

```
<AdaptationSet mimeType="application/mp4" startWithSAP="1" lang="fra" segmentAlignment="true">
			<SegmentTemplate timescale="10000000" presentationTimeOffset="0" media="$RepresentationID$/Segment-$Time$.m4s" initialization="$RepresentationID$/init.m4i">
				<SegmentTimeline>
					<S t="8800112" d="29599888" />
					<S t="38400000" d="19200000" r="22" />
					<S t="480000000" d="38400000" />
					<S t="518400000" d="19200000" r="22" />
					<S t="960000000" d="38400000" />
					<S t="998400000" d="19200000" r="22" />
					<S t="1440000000" d="38400000" />
					<S t="1478400000" d="19200000" r="22" />
					<S t="1920000000" d="38400000" />
					<S t="63360000000" d="38400000" />
                                              		...
					<S t="63398400000" d="19200000" r="22" />
					<S t="63840000000" d="38400000" />
					<S t="63878400000" d="19200000" r="22" />
					<S t="64320000000" d="38400000" />
					<S t="64358400000" d="10400111" />
				</SegmentTimeline>
			</SegmentTemplate>
			<Representation codecs="stpp" id="stream_9" bandwidth="15000" />
</AdaptationSet>

```

In fact, the subtitle remains displayed even if there is no audio in the video (Exceeds the segment duration > 4s).
I have the impression that as long as there is a subtitle that follows, it replaces itself well, but the last of a dialogue that ends, disappears only after a certain time (tempo in the code?) which does not correspond to the end present in the xml.

PI: Following verification in the mp4 boxes of the m4s segment the data are consistent:
Example of a segment that its display exceeds 2s 
   timescale = 10000000
   sidx@subsegment_duration= 19200000

Do you have an idea please?  Is it a known problem ?

BR,
Saif

**Comment by icbaker** [comment]
I'm afraid we need media we can use to reproduce the problem in order to investigate this, probably a link to a stream hosted somewhere. Please either upload it here or send to dev.exoplayer@gmail.com using the subject `Issue #10556`. Please also update this issue to indicate you’ve done this.

**Comment by Xlcghs** [comment]
I have investigated the problem, in fact it is a problem in the stream.
I will close the ticket
