### ISSUE TITLE
Video resize mode depends on video format

### ISSUE THREAD

**Issue by Artur512** [google/ExoPlayer#10569]
Hello everyone, 
I would ask you about possibility to dynamically change sizeMode StyledPlayerView depends on video orientation.  Is possible to get know that video is in landscape or portrait?

```
       zoom.setOnClickListener {
            if (playerView.resizeMode == RESIZE_MODE_FIT) {
               playerView.resizeMode = RESIZE_MODE_ZOOM
            } else {
               playerView.resizeMode = RESIZE_MODE_FIT
            }
        }
```

Zoom is icon to change resize mode, I want to show or hide it in depends on video orientation because zooming in landscape is useless. 
This is how it looks like in RESIZE_MODE_FIT.
![Zrzut ekranu 2022-08-30 o 12 50 16](https://user-images.githubusercontent.com/15378808/187418265-e5f4ffb4-a5c6-4a39-af13-a13aff72165d.png)

**Comment by icbaker** [comment]
The video in the screenshot looks like it was originally a portrait video that's been encoded into a landscape format by 'burning in' some ['pillarbox' masking](https://en.wikipedia.org/wiki/Pillarbox).

A player has no way to detect these pillarbox bars, so there's no general way to make the original content full-screen when playing this encoding - you would need to tell the player where the bars are and manually zoom to crop them out. It's probably easier to re-encode the content to crop the pillarboxes (or use the original content without pillarboxes if you have access to it).

Given you're asking about quite a specific use-case of playing (imo) poorly encoded content, I don't think there's enough justification for adding additional complexity to `StyledPlayerView`. See the note about niche customizations of our UI components here: https://exoplayer.dev/ui-components.html#further-customization
