### ISSUE TITLE
Play jerky video

### ISSUE THREAD

**Issue by DinhLap96** [google/ExoPlayer#10566]
I am using v2.18.1

I'm still having issues with some laggy videos like the one at the link below :
https://drive.google.com/file/d/1HxVlcPIZXDNYjnA5Jp0VfvGWiq2VdhnO/view?usp=sharing
I don't know if there is a way to solve this problem.
I play videos on other apps without the same problem.

Can someone help me to solve it?

Code:

        val renderersFactory = DefaultRenderersFactory(activity.applicationContext)
            .forceEnableMediaCodecAsynchronousQueueing()
            .experimentalSetSynchronizeCodecInteractionsWithQueueingEnabled(true)
            .setEnableDecoderFallback(true)
            .setEnableAudioTrackPlaybackParams(true)
            .setEnableAudioOffload(true)
            .setAllowedVideoJoiningTimeMs(DefaultRenderersFactory.DEFAULT_ALLOWED_VIDEO_JOINING_TIME_MS)
            .setExtensionRendererMode(DefaultRenderersFactory.EXTENSION_RENDERER_MODE_PREFER)

**Comment by tonihei** [comment]
I'm afraid this isn't very useful for debugging because we don't know about the device, the media you are playing, etc. Please use the issue template when filing bugs and fill out the requested information as much as possible.
