### ISSUE TITLE
ExoPlayer version 2.11.7 - class com.google.android.exoplayer2.upstream.cache.Cache$CacheException|Failed to list cache directory files

### ISSUE THREAD

**Issue by AkshatTailang** [google/ExoPlayer#10560]
### ExoPlayer Version

Older (unsupported)

### Devices that reproduce the issue

Xiaomi Mi A3 running on Android version 11

### Devices that do not reproduce the issue

Oneplus 7T running on Android 11

### Reproducible in the demo app?

No

### Reproduction steps

While downloading the song through Exo Player 2.11.7

### Expected result

The file gets downloaded.

### Actual result

The file download gets failed with error - class com.google.android.exoplayer2.upstream.cache.Cache$CacheException|Failed to list cache directory files.

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by tonihei** [comment]
It sounds like something is not working with the cache directory you are using. The error is logged if `cacheDir.listFiles()` fails, which is a normal file operation. Specifically, it only returns null if "this pathname does not denote a directory, or if an I/O error occurs." I'm afraid we can't really do something about this unless you have a reproducible problem somehow.
