### ISSUE TITLE
Is there any api to clear the cache of one media item by id?

### ISSUE THREAD

**Issue by PeaceAllen** [google/ExoPlayer#10577]
Hi All,

Is there any API to clear the cache of one media item by id?

ExoPlayer play one media file with cache, later the media file is replaced by another one on server, but the url is not changed. it will report an error, code is ERROR_CODE_IO_READ_POSITION_OUT_OF_RANGE or 416 ?

**Comment by marcbaechinger** [comment]
From the JavaDoc I'd say [`Cache.removeResource(String key)`](https://github.com/google/ExoPlayer/blob/release-v2/library/datasource/src/main/java/com/google/android/exoplayer2/upstream/cache/Cache.java#L248) would be a candidate to try.

If you haven't declared a custom key, then the URI of the resource is the key.

**Comment by PeaceAllen** [comment]
> From the JavaDoc I'd say [`Cache.removeResource(String key)`](https://github.com/google/ExoPlayer/blob/release-v2/library/datasource/src/main/java/com/google/android/exoplayer2/upstream/cache/Cache.java#L248) would be a candidate to try.
> 
> If you haven't declared a custom key, then the URI of the resource is the key.

Yes, it works well, thank you very much.
