### ISSUE TITLE
Using segmented WebVTT subtitles

### ISSUE THREAD

**Issue by baboya** [google/ExoPlayer#1058]
HI, 
I've been trying to figure out how to display segmented subtitles. 
Here is an example:
http://damqu9bojvka3.cloudfront.net/processed/45/5091/hls_1000k/captions-en.m3u8

Any help will be appreciated.
Thanks,

**Comment by ojw28** [comment]
Presumably the m3u8 file you link to is part of a larger HLS playlist (i.e. it's referenced from a HLS master playlist)? In which case the issue is tracked by #151.
