### ISSUE TITLE
Player is downloading segments less than the given `minimumUpdatePeriod` in the Dash manifest

### ISSUE THREAD

**Issue by GouravSna** [google/ExoPlayer#10582]
For the _Live_ media where `minimumUpdatePeriod` is 2 seconds, i can see the Player is trying to download the segments less than 2 seconds. Sometimes, it tries to download multiple segments with in a second. Sometimes, it does not download in 2 seconds, that is clear for me after looking at [this](https://github.com/google/ExoPlayer/issues/3344#issuecomment-356015681) comment (#issue-2) 
I am using `targetLiveOffset` which is 10 seconds (we have to avoid latency across platforms). 

Network speed is quite good and can see that player is downloading the max available rendition segments. 

My assumption here is that Player is taking `targetLiveOffset` in consideration and trying to go as close as possible hence it is trying to download many chunks.
Am i right if not can you please share your thoughts around it.

ExoPlayer: v2.17.1
Device: Android STB

**Comment by tonihei** [comment]
I'm not sure I fully understand your proposal or question. I think there might be some confusion around loading, playing and manifest updates, which are all related, but also work independently:
 - The **manifest** is loaded once and then loaded again every `minimumUpdatePeriod` seconds (=every 2 seconds in your case) to get an up-to-date list of available media segments. There shouldn't be any manifest loading bursts or pauses.
 - The **media segments** are then loaded as fast as possible up to the last available segment (based on the last known manifest). So after each manifest load and with a fast network, you should see a burst of media segment downloads and then a pause until the next manifest with additional segments becomes available. Note that this is related to filling the player's queue to keep it as full as possible.
 - The **playback position** relative to the current live time is then set by `targetLiveOffset` (10 seconds behind live edge in your case) and is almost completely unrelated to the previous two bullet points. The only relationship is that the player can't play segments that aren't downloaded yet. 

Does that answer your question? If not, please clarify what behavior your are seeing and what you think should be happening instead.

**Comment by GouravSna** [comment]
> * The **media segments** are then loaded as fast as possible up to the last available segment (based on the last known manifest). So after each manifest load and with a fast network, you should see a burst of media segment downloads and then a pause until the next manifest with additional segments becomes available. Note that this is related to filling the player's queue to keep it as full as possible.

Thanks a lot for the detailed clarification @tonihei . I was looking at this point and was thinking that this should also happen on 2 seconds of interval. But after your point, it is clear that it can happen fast in the fast network.
