### ISSUE TITLE
Video subtitles not displaying correctly (overlapping) if there are overlapping time codes

### ISSUE THREAD

**Issue by BobbyJWhjr** [google/ExoPlayer#10590]
### ExoPlayer Version

2.18.1

### Devices that reproduce the issue

All android devices. Tested on Samsung S22 Ultra, Oneplus 7 Pro

### Devices that do not reproduce the issue

NA

### Reproducible in the demo app?

Not tested

### Reproduction steps

Play any media with overlapping media codes like some narrator speaking with background music then subtitles overlap with each other as depicted in image

### Expected result

When there are subtitles with overlapping time codes, expected behaviour should be  to display both subtitles at the same time, just stacked above/below each other.

![pxl_20220816_183726420](https://user-images.githubusercontent.com/95083263/188825006-599ebc72-bf15-4c35-ab6d-d7ae01cafab9.jpeg)

### Actual result

![Screen Shot 2022-08-16 at 12 02 36 PM](https://user-images.githubusercontent.com/95083263/188825719-4ad5f8ba-10d3-4e90-a079-b05079e3ca7b.png)

### Media

NA

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by nigelmegitt** [comment]
Correct presentation in this case depends on the subtitle format and data. Can you provide the source subtitle file?

**Comment by icbaker** [comment]
For SSA/ASS subtitles sideloaded from a file this should work.

For SSA/ASS subtitles in MKV this is known not to work, implementing it is tracked by https://github.com/google/ExoPlayer/issues/10295.

For Subrip subtitles this is known not to work, implementing it is tracked by https://github.com/google/ExoPlayer/issues/4794.

I believe this should work for both WebVTT and TTML subtitles (though I haven't double checked).

As @nigelmegitt says, please clarify what format subtitles you're asking about and provide a source file we can use to reproduce what you're seeing.

**Comment by nigelmegitt** [comment]
Related data point: Overlapping regions and therefore text is permitted by the specification in generic TTML, but not in the IMSC or EBU-TT-D profiles that are commonly used for subtitles and captions. (this is not a comment on the implementation in ExoPlayer)
