### ISSUE TITLE
message":"Source error","errorCode":3002,"name":"ExoPlaybackException"className":"ParserException

### ISSUE THREAD

**Issue by D-EXOPLAYER** [google/ExoPlayer#10599]
### ExoPlayer Version

2.15.1

### Devices that reproduce the issue

- ANDROIDTV - TIMVISION BOX (Android 10 - DTIW3930-10.0.0.19)
- ANDROIDTV - TIMBOX (Android 8.0.0 - uzw4010tim-5.6.2-2.20.0)
- FireTv Stick HD (Device Model AFTT - Fire OS 5.2.8.9 (678752620))
- FireTv Stick 4K (Device Model AFTMM - Fire OS 6.2.9.0 (NS6290/4022))

### Reproducible in the demo app?

Not tested

### Reproduction steps

Steps:
1) Open the app from timvisionbox (app store)
2) Play a Live channel 

### Expected result

Live channel plays successfully (without error)

### Actual result

Playback crash and show "PLAYBACK-EXOPLAYER" (5 times in 4 hours )
Adaptive streaming: DASH

### Media

Description:
Error Metadata
{"isNonFatal":false,"error":{"message":"Source error","errorCode":3002,"name":"ExoPlaybackException","type":0,"cause":{"className":"ParserException","message":"inputStream does not contain a valid media presentation description"}}}

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by icbaker** [comment]
> inputStream does not contain a valid media presentation description

This error indicates the DASH manifest is malformed. If you want us to investigate further please provide a link to the DASH manifest. Installing your app from the play store doesn't give us enough insight into what's going on to be useful I'm afraid.

https://github.com/google/ExoPlayer/blob/2a88f0fb295ff5b56e6fbcbe7e91bdf922cbae13/library/dash/src/main/java/com/google/android/exoplayer2/source/dash/manifest/DashManifestParser.java#L102-L106

**Comment by D-EXOPLAYER** [comment]
Hi @icbaker 
Is there any repository where there are exoplayers's errors?
Example: https://shaka-player-demo.appspot.com/docs/api/shaka.util.Error.html#.Code
br

**Comment by icbaker** [comment]
The error codes (in this case `3002`) are documented here: https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/PlaybackException.html
