### ISSUE TITLE
Codec regression when updating from 2.9.5 to 2.18.1

### ISSUE THREAD

**Issue by lmartin** [google/ExoPlayer#10604]
### ExoPlayer Version

2.18.1

### Devices that reproduce the issue

Motorola Moto E (2nd gen) 4G LTE - Android 6.0 API 23

### Reproducible in the demo app?

Yes

### Reproduction steps

Play mp4 video 1920x960@30fps 

### Expected result

Playback is smooth, hardware decoder is selected, log trace:
I MediaCodec: name=OMX.qcom.video.decoder.avc isType=false encoder=false
 

### Actual result

Playback is jerky, fallback on software decoder, log trace:
D MediaCodecInfo: NoSupport [codec.profileLevel, avc1.4D0029, video/avc] [OMX.qcom.video.decoder.avc, video/avc] [surnia_umts, MotoE2(4G-LTE), motorola, 23]
I MediaCodec: name=OMX.google.h264.decoder isType=false encoder=false

### Media

The same video but with a different codec profile works as expected (see attachment for logs). 
Working video codec : avc1.640028
Not working video codec : avc1.4D0029

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.
[exoplayerDemo-2.18.1-hw_failed.txt](https://github.com/google/ExoPlayer/files/9557876/exoplayerDemo-2.18.1-hw_failed.txt)
[exoplayerDemo-2.18.1-hw_success.txt](https://github.com/google/ExoPlayer/files/9557877/exoplayerDemo-2.18.1-hw_success.txt)

**Comment by lmartin** [comment]
I updated the description. 
Is there a way to restore the behaviour of Exoplayer 2.9.5, I mean accepting to use hw decoder for video codec avc1.4D0029?

**Comment by microkatz** [comment]
@lmartin You noted in your bug that the issue is reproducible with the demo app. Can you direct us to the content you used to reproduce this issue?

**Comment by lmartin** [comment]
Sorry but I can't share this private content. I fixed the issue by re-encoding the video with ffmpeg, I used this command :
`./ffmpeg -i input.mp4 -c:v libx264 -x264opts keyint=25 -c:a copy output.mp4`
