### ISSUE TITLE
How can we extract custom data being sent in SCTE35 marker in a livestream?

### ISSUE THREAD

**Issue by Debayudh** [google/ExoPlayer#10609]
We are being sent custom key-values in a scte35 marker in a livestream periodically, on the basis of which we need to do some ui operations.
We are receiving the periodic events in onMetadata(Metadata metadata).
However, the object we are receiving is a PrivFrame, and we are not able to extract the data from it. (Data is definitely coming, as the web player using videojs player is gtting the data.)

Is there any way to extract the custom data from the PrivFrame?

Also, is there a way to covert PrivFrame object to TimeSignalCommand object? (As per content operations, they are sending a SpliceCommand which we should be able to extract as TimeSignalCommand, but we are not sure how that happens)

**Comment by icbaker** [comment]
`PrivFrame` has a `privateData` field which may contain what you need?

Otherwise please provide a stream we can use to reproduce the problem in order for us to investigate further.
Please either upload it here or send to dev.exoplayer@gmail.com using the subject `Issue #10609`. Please also update this issue to indicate you’ve done this.

**Comment by Debayudh** [comment]
Hi @icbaker 

In the privateData, we are getting an array of bytes, which when converted to String, gives just the timestamp.
The stream is client-provided, so I'm not sure I will be able to share it.

**Comment by Debayudh** [comment]
Hi @icbaker 

We were able to get the data from scte markers using the onEvents() method of AnalyticsListener 
{
if (event == EVENT_METADATA){
                  
                        Object manifest = player.getCurrentManifest();
                        if (manifest != null) {
                            HlsManifest hlsManifest = (HlsManifest) manifest;
                            HlsMediaPlaylist hlsMediaPlaylist= hlsManifest.mediaPlaylist;
                            List<String> tags = hlsMediaPlaylist.tags;
}
}

But now we have run into a problem that the scte marker event continues to come for around 1.5-2 minutes after it is supposed to end.
This could be because we are getting a dvr stream, and we will try to get the test stream converted to non-dvr to confirm.

Is it possible to segregate the tags of current playing media from the mediaPlaylist ?
Or any other way to get only latest tags?
Kindly advise

**Comment by icbaker** [comment]
It looks like you're manually pulling tags out of the playlist. I think it's up to you to determine which ones are relevant for the current playback time.
