### ISSUE TITLE
Setting HTTP Headers to MediaItem

### ISSUE THREAD

**Issue by xeinebiu** [google/ExoPlayer#10607]
## Use Case

While migrating from `MediaSource` to `MediaItem`, I cannot find a way how to inject HTTP Headers for individual `MediaItem`.

````kotlin
            MediaItem
                .Builder()
                .setUri(stream.uri)
                .setTag(media)
                .setHeaders(....) // <-- no such method
                .build()
````

Is there any way to use `MediaItem` with individual `HTTP Headers` ?

**Comment by icbaker** [comment]
Duplicate of https://github.com/google/ExoPlayer/issues/6166
