### ISSUE TITLE
How to play the mkv url

### ISSUE THREAD

**Issue by FongMi** [google/ExoPlayer#10625]
Exoplayer 2.18.1

### The video don't have ID_EBML 0x1A45DFA3

https://bj29-enet.cn-beijing.data.alicloudccp.com/rAb0Dory%2F116468%2F61c422395c3fc77fd60d422eac7ec1987da968b2%2F61c4223991183b0b9f4b4888bfdcd60d0d4f0bcf?di=bj29&dr=181925&f=62fa623a42ee5e3d22b34d52b3cd101fbf4caa7a&response-content-disposition=attachment%3B%20filename%2A%3DUTF-8%27%27Farewell.My.Concubine.1993.BluRay.REMUX.1080i.AVC.DTS-HD.MA2.0-FGT.mkv&security-token=CAIS%2BgF1q6Ft5B2yfSjIr5fQB8DFtLBC7pGGZET0ilhhbet91o7spjz2IHFPeHJrBeAYt%2FoxmW1X5vwSlq5rR4QAXlDfNW2HYyCLqVHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLukMWr%2Fwq3PIdp2ma447NWQlLnzyCMvvJ9OVDFyN0aKEnH7J%2Bq%2FzxhTPrMnpkSlacGoABe1ZhvjPsmBZp%2F90NMyYvGKB9L997uP%2F5Rf9HUtB%2FyXgxLkRipcsEimui%2BqcPilniDC3eo4buaOi9xvefoodozoMBKY3qT6xoy9fRuvkYHhne%2BEza%2FpCM3sK2AcnotiHyyAScLVvasMrm%2BhMbdS0yoGpeSRepP%2FFhQfxlCPOWKAw%3D&u=fea919266f8e491dbfc4dde5396a8829&x-oss-access-key-id=STS.NTeLzqYocYSmfbEnX4adQ9KGD&x-oss-expires=1663307357&x-oss-signature=2CojFlVAEupX60XLqZIJwkyPQFBBTLQJgI56iKFrvF8%3D&x-oss-signature-version=OSS2

THIS IS SOURCE TO GET REAL URL
https://pan.ichuguang.com/%E5%BD%B1%E9%9F%B3%E8%B5%84%E6%BA%9033T/%E8%B1%86%E7%93%A3TOP250%20REMUX/001-050/020%20%E7%86%94%E7%82%891080P%20REMUX%EF%BC%882011%EF%BC%89

### The video have ID_EBML 0x1A45DFA3
https://bj29-enet.cn-beijing.data.alicloudccp.com/NRdxK7Ho%2F58672491%2F6141b65dc49b1133a25d4b9abe96c7a329407cee%2F6141b65d4976f1b38c9f40e7bbfca33e66d25c0c?di=bj29&dr=181925&f=62fa623afeb41f0c18734bc3a9880eb920a7bba9&response-content-disposition=attachment%3B%20filename%2A%3DUTF-8%27%27The.Shawshank.Redemption.1994.2160p.BluRay.REMUX.HEVC.DTS-HD.MA.5.1-FGT.mkv&security-token=CAIS%2BgF1q6Ft5B2yfSjIr5aAO%2FaD26pK3La%2BMVHDjVBmPeQVhPbdiTz2IHFPeHJrBeAYt%2FoxmW1X5vwSlq5rR4QAXlDfNSLsXSCLqVHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLukMWr%2Fwq3PIdp2ma447NWQlLnzyCMvvJ9OVDFyN0aKEnH7J%2Bq%2FzxhTPrMnpkSlacGoABXJsD38tscQ%2BOBux3%2FPu6QKqVw1mRgXTLHuJTJHbMhp%2Bwq1YYrTh5rOLnKufoqwgH%2FX4dToyMwYUlL3EtSB8kktmTdGfqUUD%2F%2FppMVL9q0PkG6FSA0A4aR6MP9WEfj2aKBas4Iw0fUkaqFtEd6nzzz%2FqoFVfYRI94QsnSEAsVBv0%3D&u=fea919266f8e491dbfc4dde5396a8829&x-oss-access-key-id=STS.NU5pL76ukktU3wriP31k9k3vk&x-oss-expires=1663307471&x-oss-signature=3sf%2Bgje9ICa1hflHpED4HO6dlRT5NcqKzh2lbH6uHXw%3D&x-oss-signature-version=OSS2

THIS IS SOURCE TO GET REAL URL
https://pan.ichuguang.com/%E5%BD%B1%E9%9F%B3%E8%B5%84%E6%BA%9033T/%E8%B1%86%E7%93%A3TOP250%20REMUX/001-050/001%20%E8%82%96%E7%94%B3%E5%85%8B%E7%9A%84%E6%95%91%E8%B5%8E%204K%20REMUX%EF%BC%881994%EF%BC%89%E3%80%901030%E3%80%91

**Comment by rohitjoins** [comment]
@FongMi I could retrieve the url for the media file by visiting the URL mentioned in `THIS IS SOURCE TO GET REAL URL`. For the second video it looks something like [this](https://pan.ichuguang.com/d/%E5%BD%B1%E9%9F%B3%E8%B5%84%E6%BA%9033T/%E8%B1%86%E7%93%A3TOP250%20REMUX/001-050/001%20%E8%82%96%E7%94%B3%E5%85%8B%E7%9A%84%E6%95%91%E8%B5%8E%204K%20REMUX%EF%BC%881994%EF%BC%89%E3%80%901030%E3%80%91/The.Shawshank.Redemption.1994.2160p.BluRay.REMUX.HEVC.DTS-HD.MA.5.1-FGT.mkv).

The first video is malformed and hence cannot be played successfully using Exoplayer and I get the error `ERROR_CODE_PARSING_CONTAINER_UNSUPPORTED`. Although the second video plays successfully, we cannot fetch the audio track for it. Can you please check the video if it is malformed, if not you can raise an issue following our bug template found [here](https://github.com/google/ExoPlayer/issues/new?assignees=&labels=bug%2Cneeds+triage&template=bug.yml).
