### ISSUE TITLE
FFMpeg not compiling with Gradle 7.4

### ISSUE THREAD

**Issue by cyberdreamandroid** [google/ExoPlayer#10629]
### ExoPlayer Version

2.18.1

### Devices that reproduce the issue

All

### Reproducible in the demo app?

Not tested

### Reproduction steps

Upgrade to latest Gradle 7.4 coming with Dolphin IDE.
FFMPEG compilation fails because NDK 23 Side-by-Side is used by default.

### Expected result

Compilation works

### Actual result

Solution: Add android.ndkVersion "21.4.7075529" to build.gradle of FFMPEG extension.

### Media

None

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by christosts** [comment]
I believe this is overlapping with #9933 and should be fixed in 2.18.2. Let me know if the issue still persists for you.
