### ISSUE TITLE
unable play video after proguard assumenosideeffects {*;}

### ISSUE THREAD

**Issue by laole918** [google/ExoPlayer#10628]
exoplayer:2.18.1
The following configuration cannot play video
``` groovy
-assumenosideeffects class timber.log.Timber {
    *;
}
```
But there is no problem with the following configuration
``` groovy
-assumenosideeffects class timber.log.Timber {
    public static void d(java.lang.String, ...);
}
```
Is it because some code of exoplayer has been deleted by assumenodeeffects {\*;}? Will this problem be fixed?

**Comment by rohitjoins** [comment]
@laole918 This proguard rule doesn't seem to effect Exoplayer library code in anyway as the rule is specific to the logging library class you are using.

Unfortunately we can't give 1:1 support for solving app specific issues. We'll leave this issue open for ~2 weeks in case anyone wishes to answer it here. If you think this is a problem with ExoPlayer, please narrow down your issue to describe the ExoPlayer behaviour that doesn't match your expectations.
