### ISSUE TITLE
How to play videos in UHD in Sony Xperia 1 IV

### ISSUE THREAD

**Issue by Shrihari1428** [google/ExoPlayer#10636]
The Sony Xperia 1 IV should be able to play videos in UHD (1644 x 3840), but in exoplayer the videos play at QHD (1096 x 2560). Is there way to make it play at UHD since the phone and even the native gallery player supports it.

Display.Mode[] modes = disp.getSupportedModes() gives me the following : 

Mode 1: 1096x2560/60.0fps
Mode 2: 1096x2560/120.0fps
Mode 3: 1644x3840/60.0fps
Mode 4: 1644x3840/120.0fps

I am unable to use param.preferredDisplayModeId to set the preferred mode. The active mode is always Mode 2 - 1096x2560/120.0fps.

But if I disable high refresh rate in the device settings (thereby disabling 120hz), the default mode still remains Mode 2. But I am able to set preferredDisplayMode to Mode 1. Even then I am unable to access mode 3 and 4.

Is there a way to access mode 3 and 4. Thanks in advance!

**Comment by christosts** [comment]
Is the video you are trying to play at UHD resolution? Can you share the video here?
