### ISSUE TITLE
StyledPlayerControlView : java.lang.RuntimeException: Could not read input channel file descriptors from parcel

### ISSUE THREAD

**Issue by nuclearmagneton** [google/ExoPlayer#10635]
### ExoPlayer Version

2.18.1

### Devices that reproduce the issue

OnePlus5
Android 7.1.1

### Reproducible in the demo app?

Yes

### Reproduction steps

received from crash report 

### Expected result

without crash

### Actual result

android.view.InputChannel.nativeReadFromParcel InputChannel.java
android.view.InputChannel.readFromParcel InputChannel.java:148
android.view.IWindowSession$Stub$Proxy.addToDisplay IWindowSession.java:841
android.view.ViewRootImpl.setView ViewRootImpl.java:640
android.view.WindowManagerGlobal.addView WindowManagerGlobal.java:342
android.view.WindowManagerImpl.addView WindowManagerImpl.java:93
android.widget.PopupWindow.invokePopup PopupWindow.java:1378
android.widget.PopupWindow.showAsDropDown PopupWindow.java:1234
android.widget.PopupWindow.showAsDropDown PopupWindow.java:1191
com.google.android.exoplayer2.ui.StyledPlayerControlView.displaySettingsWindow StyledPlayerControlView.java:-1
com.google.android.exoplayer2.ui.StyledPlayerControlView.access$3000 StyledPlayerControlView.java:-1
com.google.android.exoplayer2.ui.StyledPlayerControlView$ComponentListener.onClick StyledPlayerControlView.java:-1
android.view.View.performClick View.java:5794
android.view.View$PerformClick.run View.java:22728
android.os.Handler.handleCallback Handler.java:751
android.os.Handler.dispatchMessage Handler.java:95
android.os.Looper.loop Looper.java:154
android.app.ActivityThread.main ActivityThread.java:6138
java.lang.reflect.Method.invoke Method.java
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run ZygoteInit.java:893
com.android.internal.os.ZygoteInit.main ZygoteInit.java:783

### Media

any demo links

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by icbaker** [comment]
This looks like an issue in the OS, rather than the library. Are you able to reproduce it locally with the demo app? Does it reproduce on any recent Pixel devices?
