### ISSUE TITLE
Webm without sounds - Media Code: -11

### ISSUE THREAD

**Issue by rusmichal** [google/ExoPlayer#1063]
Hello I using Exoplayer to play movie in format WebM:

This is example movie
https://dzdkkcm9gxovs.cloudfront.net/uploads/1450174995-10174-6976/europe-west1-d.ge66k4eI.P9j6K-Ombg.webm

If i tried to start movie then i can't hear sound on devices with android < 5.0 I Tested on HtC one, Sony D2203 android with 4.x.x. I using Exoplayer version: 1.5.2

I recived lot of loogs:

`
12-15 14:52:25.111 3972-8345/com.vyda.stream.staging E/MediaCodec: err = 0
12-15 14:52:25.121 3972-8345/com.vyda.stream.staging E/MediaCodec: err = 0
12-15 14:52:25.121 3972-8345/com.vyda.stream.staging E/MediaCodec: err = -11
12-15 14:52:25.121 3972-8345/com.vyda.stream.staging E/MediaCodec: err = -11
12-15 14:52:25.131 3972-8345/com.vyda.stream.staging E/MediaCodec: err = -11
12-15 14:52:25.141 3972-8345/com.vyda.stream.staging E/MediaCodec: err = -11
12-15 14:52:25.151 3972-8345/com.vyda.stream.staging E/MediaCodec: err = 0
12-15 14:52:25.151 3972-8345/com.vyda.stream.staging E/MediaCodec: err = 0
12-15 14:52:25.151 3972-8345/com.vyda.stream.staging E/MediaCodec: err = -11
12-15 14:52:25.161 3972-8345/com.vyda.stream.staging E/MediaCodec: err = -11
12-15 14:52:25.191 3972-8345/com.vyda.stream.staging E/MediaCodec: err = 0
12-15 14:52:25.191 3972-8345/com.vyda.stream.staging E/MediaCodec: err = 0
`
Any ideas?

**Comment by ojw28** [comment]
The file contains Opus audio. Opus is only supported on Android at the platform level from 5.0 and above, as shown [here](http://developer.android.com/guide/appendix/media-formats.html). If you require playback on older platforms levels then you should use something that's more widely supported, like AAC.

**Comment by rusmichal** [comment]
Thanks :)
