### ISSUE TITLE
If I create Exoplayer instance in the thread which is not main thread , I can't get duration and current position from Exoplayer instance ( stuck in STATE_BUFFERING)

### ISSUE THREAD

**Issue by jowunnal** [google/ExoPlayer#10643]
Hello team, I'm making a audio app using Exoplayer with waveForm library.

What I am making is when waveForm's progress has changed that Exoplayer's current position is changed by waveForm's progress.

I don't know my code is bad or not anyways, if both tasks are performed in the main thread, then audio is stuttering.

So I made Exoplayer instance at other thread which is newsingleThread in CoroutineContext.

I can pause() or play() Exoplayer but PlaybackState is always 2(means buffering) and can't get currentPosition() or duration()

How am I supposed to do in this case?

sorry, for my bad English.

 I read [docs](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/ExoPlayer.html "docs") but I can't understand this case.

```
val mediaDispatcher = Executors.newSingleThreadExecutor().asCoroutineDispatcher()

private suspend fun createExoPlayer(audioFileName: String): ExoPlayer {
        return withContext(mediaDispatcher){
            if(Looper.myLooper()==null){
                Looper.prepare()
            }
            return@withContext ExoPlayer.Builder(context).build().apply {
              
                setMediaItem(getMeidaItem(context, audioFileName))
                playWhenReady=true
                seekTo(0, 0L)
                playbackParameters= PlaybackParameters(1f)
                addListener(object: Player.Listener{
                    override fun onPositionDiscontinuity(
                        oldPosition: Player.PositionInfo,
                        newPosition: Player.PositionInfo,
                        reason: Int
                    ) {
                        super.onPositionDiscontinuity(oldPosition, newPosition, reason)
                        launch(Dispatchers.Main){
                            mediaPosition.value=newPosition.positionMs
                        }
                    }

                    override fun onPlaybackStateChanged(playbackState: Int) {
                        when(playbackState){
                            ExoPlayer.STATE_IDLE -> Log.d("test","idle")
                            ExoPlayer.STATE_READY -> Log.d("test","ready")
                            ExoPlayer.STATE_BUFFERING -> Log.d("test","buffering")
                            ExoPlayer.STATE_ENDED -> Log.d("test","ended")

                        }
                    }
                })
                Log.d("test",playbackState.toString())
                prepare()
                Log.d("test",playbackState.toString())
            }
        }
    }
```
![2](https://user-images.githubusercontent.com/75519689/191762277-1368ec8c-396d-4b33-9242-90a762ba8e9a.PNG)

**Comment by christosts** [comment]
Apologies for the late response. Does the issue still remain?

**Comment by bolshakovsashka** [comment]
> Apologies for the late response. Does the issue still remain?

Hi, i have the same problem with exoplayer and background thread. 
ExoPlayer version 2.18.2
Android 12, 13

@jowunnal  code example looks valid

**Comment by christosts** [comment]
I'm not familiar with Kotlin and coroutines myself so please bear with me, but on the Java side after you call `Looper.prepare()` you need to call `Looper.loop()` too to run the message queie. And then finish with `Looper.quit()`.  In most use-cases I'm aware of with the player being delegated to another thread, the thread is of type `HandlerThread` which runs the Looper automatically. Mixing Executors with Loopers may not be straightforward.

Is it certain in the snippet above runs the Looper message queue?
