### ISSUE TITLE
Not hide seekbar on locksreen notification after set METADATA_KEY_DURATION equal -1

### ISSUE THREAD

**Issue by ivan12312312** [google/ExoPlayer#10648]
### ExoPlayer Version

2.18.1

### Devices that reproduce the issue

samsung s22 android 12

### Reproducible in the demo app?

Not tested

### Reproduction steps

insert code
```
mediaSessionConnector.setQueueNavigator(new TimelineQueueNavigator(mediaSession) {
    @Override
    public MediaDescriptionCompat getMediaDescription(Player player, int windowIndex) {
        Bundle extras = new Bundle();
        extras.putInt(MediaMetadataCompat.METADATA_KEY_DURATION, -1);

        return new MediaDescriptionCompat.Builder()
                .setMediaId(trackModel.mediaId)
                .setIconBitmap(trackModel.bitmap)
                .setTitle(trackModel.title)
                .setDescription(trackModel.description)
                .setExtras(extras)
                .build();
    }
});
```

### Expected result

seekbar not view on lockscreen

### Actual result

![lockscreen](https://i.ibb.co/C5MqWFH/photo-2022-09-24-21-43-36.jpg)
![after lockscreen](https://i.ibb.co/D5GJRWC/photo-2022-09-24-21-43-45.jpg)

### Media

-

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by marcbaechinger** [comment]
The `MediaDescriptionCompat` that you return with the `TimelineQueueNavigator` is used for the queue item in the queue only. The `extrasa` that you passed there with the duration is not used as you intend it. 

You can instead use a `MediaMetadataProvider` and set it with `MediaSessionConnector.setMetadataProvider(provider)`. You may want to look into the [default implementation](https://github.com/google/ExoPlayer/blob/release-v2/extensions/mediasession/src/main/java/com/google/android/exoplayer2/ext/mediasession/MediaSessionConnector.java#L1048) to see what is set there, so you provide similar data than the default.

Please reopen the issue if this doesn't work.
