### ISSUE TITLE
How to get the actual video's view vice the playerView?

### ISSUE THREAD

**Issue by whyvas** [google/ExoPlayer#10653]
I am trying to setup a view to overlay boxes that tensorflow returns in the form of bounding boxes. The problem is it's returning the bounding box positions based on a the playerview's size which includes grey bars if the aspect ratio of the video doesn't match the view's aspect ratio exactly so everything is a little offset. Is there a way to get a view of the actual video surface vice the playerview without using the fill mode?
https://imgur.com/a/r7SqHdd is a screenshot showing what I mean, playerView gives me the white box, I'd like only the video.

**Comment by marcbaechinger** [comment]
I'm not aware of an API that would give you this information. But you can probably calculate this yourself.

There is an event that you can receive with a `AnalyticsListener.onVideoInputFormatChanged` that gives you the dimensions of the video that is currently playing:

```
videoInputFormat [eventTime=15.90, mediaPos=11.46, window=0, period=0, id=2, mimeType=video/avc, bitrate=1774254, codecs=avc1.4D401F, res=854x380, fps=24.0]
```

When you have the dimension of the `View` you should be able to calculate the actual dimension on the surface.
Would that work?

**Comment by whyvas** [comment]
Hmmm, so figure out the aspect ratio of the view compared to that of the
video and then adjust whichever axis isn't maximized? I think that'll work,
thanks!

Yves

**Comment by marcbaechinger** [comment]
I'm closing this issue. Please re-open if needed.
