### ISSUE TITLE
What's the name of the tool to split the mono repo into YouTube and exoplayer?

### ISSUE THREAD

**Issue by fmatosqg** [google/ExoPlayer#10658]
On Adb podcast episode 189 with @marcbaechinger and Tony, at 23 min, they mention an open source tool called ( copy barrel ???) used to split a mono repository into 2 repositories.

I'd like to know the proper name/link of such tool, since it seems I got the name wrong.

Also keen to hear about any other similar tools.

* Episode link (115 MB): https://traffic.libsyn.com/secure/adbackstage/ADB189_v2.mp3?dest-id=2710847

* Show Notes: http://adbackstage.libsyn.com/episode-189-video-conference

**Comment by marcbaechinger** [comment]
The tool we are using internally to do source transformations is called Copybara. 

Here is the GitHub repo:
https://github.com/google/copybara

**Comment by marcbaechinger** [comment]
I'm closing this issue. Please re-open if you have further questions.
