### ISSUE TITLE
IMA | How to intercept the ad request? 

### ISSUE THREAD

**Issue by victor-munoz** [google/ExoPlayer#10660]
Hello Team, 

I found that the IMA extension fails to reproduce some ads because of problems with the VAST XML...Is there a way to intercept the ad request? I am thinking of something like an `addNetworkInterceptor.`

That would be very helpful to make corrections on knowing errors in the VAST XML so the IMA extension can reproduce them successfully. 

Best, 

Victor

**Comment by marcbaechinger** [comment]
The IMA extension is using the IMA SDK under the hood that requests the VAST file. The ExoPlayer extension only gets the ad events emitted by the SDK. 

So if there was such an option to intercept the request, that would be part of the IMA SDK and the interceptor would be in JavaScript. I doubt that the ExoPlayer IMA extension will/should expose such an API if there is one (which I do not know to be honest).

Besides these complexities, wouldn't it be better to make the VAST file work on the server side? If that's not possible, I think you can file a VAST bug report here: https://support.google.com/admanager/answer/9023950

**Comment by victor-munoz** [comment]
Thanks very much for your answer

**Comment by marcbaechinger** [comment]
I'm closing this issue. Please re-open if needed.
