### ISSUE TITLE
onMediaItemTransition not called when having a single media item with REPEAT_MODE_ALL

### ISSUE THREAD

**Issue by mpivchev** [google/ExoPlayer#10667]
Sometimes there are cases where even if we set to repeat a queue (`REPEAT_MODE_ALL`), we only have one track in the timeline. In that case I would assume that `Player.MEDIA_ITEM_TRANSITION_REASON_REPEAT` would trigger, since technically we are repeating the same track, but it doesn't seem like this is the case.

Here are the steps:
1. Have one track in a queue with `REPEAT_MODE_ALL` set.
2. Press the "skip to next" button.
3. The track plays again, but `onMediaItemTransition` is not triggered with `MEDIA_ITEM_TRANSITION_REASON_REPEAT`

Is this state not considered a media transition? If that's the case, how can I track whenever the media item repeats itself again?

**Comment by tonihei** [comment]
Thanks for reporting! This is not expected and it should send `onMediaItemTransition`. The reason should probably be `MEDIA_ITEM_TRANSITION_REASON_SEEK` though.

**Comment by tonihei** [comment]
Fixed by the commit above.
