### ISSUE TITLE
Potential bug in calculation of trackBitrates in AdaptiveTrackSelection

### ISSUE THREAD

**Issue by sruditsky** [google/ExoPlayer#10664]
### ExoPlayer Version

2.17.1

### Devices that reproduce the issue

A proprietary device running Android 10

### Reproducible in the demo app?

Not tested

### Reproduction steps

This is not a user facing bug and it was noticed during debugging.
While an HLS playback is being established check (with a debugger or log) what is being summed in the following loop in AdaptiveTrackSelection.java:

```Java
    for (int i = 0; i < checkpointBitrates.length; i++) {
      totalBitrate += checkpointBitrates[i];
    }
```
It looks like the values for checkpointBitrates are coming from 

``` Java
definition.group.getFormat(definition.tracks[j]).bitrate
```
which can contain the value of Format.NO_VALUE (= -1)

As 'normal' values in checkpointBitrates have the order of magnitude of 10^6 this does not change behavior in any significant way, however, this still feels like a bug. 

### Expected result

totalBitrate has a value equal exactly to the sum of all the bitrate components.

### Actual result

totalBitrate has a value slightly lower than the sum of all the bitrate components.

### Media

Not applicable

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by tonihei** [comment]
The HLS spec requires every #EXT-X-STREAM-INF tag to have the BANDWIDTH tag defined. See https://datatracker.ietf.org/doc/html/draft-pantos-hls-rfc8216bis#section-4.4.6.2:  _Every EXT-X-STREAM-INF tag MUST include the BANDWIDTH attribute._

This value eventually ends up in the track bitrates. In addition, ExoPlayer has safeguards to only include tracks with a defined bitrate in adaptive track selections in its `DefaultTrackSelector`. All this together implies that the code in `AdaptiveTrackSelection` can assume that all bitrates are set and none of them are `Format.NO_VALUE`. 

If you have a case (using ExoPlayer's default classes) where this isn't true, please provide an example playlist to reproduce the issue (or send it dev.exoplayer@gmail.com with "Issue #10664" in the subject).

**Comment by sruditsky** [comment]
![ExoPlayerIssue10664](https://user-images.githubusercontent.com/8403167/194722376-5e0acf99-2b24-41f7-8bd0-f1fa404c0356.png)

@tonihei 
I just took an unmodified ExoPlayer 2.18.1 and ran the demo app with "Apple multivariant playlist advanced (FMP4)" sample.
As you can see on the attached image most of the checkpointBitrates values (other than the video one) are -1s.

**Comment by tonihei** [comment]
Thanks, I see what you mean now. The tracks with NO_VALUE bitrate are not actually used for the selection, but they are used to calculate the total required bitrate. We'll update the code to fix this, but as you say, there shouldn't be any measurable impact on the algorithm itself.

**Comment by sruditsky** [comment]
@tonihei 
Thanks!

Yes, this is not an issue for the performance of the algorithm in the field, but if somebody tries to predict the outcome of this algorithm based on a specific input, for example, for test purposes, this might be an issue.

**Comment by tonihei** [comment]
Fixed by the commit above.
