### ISSUE TITLE
Unable to open TS video stream

### ISSUE THREAD

**Issue by menscikov** [google/ExoPlayer#10676]
### ExoPlayer Version

2.18.1

### Devices that reproduce the issue

Redmi Note 12 running Android 12

### Reproduction steps

Please open the attached video stream.

### Expected result

The video stream must open immediately.

### Actual result

Video sometimes is loading, but in 90% it won't open, will load indefinitely without any errors.

### Media

https://www.mediafire.com/file/nezv45mp1m3oxur/test_video.ts/file

**Comment by tonihei** [comment]
I tried to play this link 5 times in a row and it always started playing for me. If this reproduces in the ExoPlayer demo app for you, please note any changes you may have done. 

Aside: the actual video has lots of green decoding artefacts on the Pixel 4 I tested with.

**Comment by menscikov** [comment]
@tonihei thank you for testing.
I tried demo app, i can confirm that it's working there, but sound is missing. So the problem is with the audio codec.
In my app I'm using `DefaultRenderersFactory.EXTENSION_RENDERER_MODE_PREFER` or `DefaultRenderersFactory.EXTENSION_RENDERER_MODE_ON`. And with this setting turned on the video won't load.

**Comment by menscikov** [comment]
@tonihei, the user who sent me this video, attached this screenshot with media data (audio codec).
He said that audio codec with PID 257 can't be played in ExoPlayer.

![audio_codec](https://user-images.githubusercontent.com/45258003/194336915-34966578-d106-4e9b-b941-cf9520fc9e89.png)

**Comment by emveepee** [comment]
Works ok here 

10-06 14:33:03.044 18619 18619 D EventLogger:     [X] Track:0, id=2040/2042, mimeType=audio/mpeg-L2, channels=2, sample_rate=48000, supported=YES

Maybe that player needs ffmpeg?

**Comment by menscikov** [comment]
> Works ok here
> 
> 10-06 14:33:03.044 18619 18619 D EventLogger: [X] Track:0, id=2040/2042, mimeType=audio/mpeg-L2, channels=2, sample_rate=48000, supported=YES
> 
> Maybe that player needs ffmpeg?

It's strange, maybe your Pixel 4 device has better compatibility.
I have ffmpeg. Using version 4.4 at this moment in my app. Maybe i have to try with older ffmpeg version.

Is it opening without any issues? For example 5 times in a row? Or you have to wait long time before it will load?
On my phone it's opening 1 time from 5. And i have to wait about 30 seconds before it will load.
Without sound it's loading immediately.

Thank you.

**Comment by emveepee** [comment]
I was testing from an Android box with my ExoPlayer client but a/v seems good  https://imgur.com/a/MvHnAeF (audio needs to be turned on with the speaker icon)

**Comment by tonihei** [comment]
I'm assuming you are both using the Ffmpeg extension for the audio. If it's working for @emveepee, maybe something is misconfigured in your Ffmpeg build (@menscikov)?  If it's down to configuring Ffmpeg, that's not really part of our expertise. We are happy to help if you think something in our integration layer isn't working as it should.

**Comment by menscikov** [comment]
@tonihei i will try to compile ffmpeg 4.2 version, because it's recommended here [ffmpeg extension](https://github.com/google/ExoPlayer/tree/release-v2/extensions/ffmpeg). Will see if it helps.
Is there any plans to update ExoPlayer ffmpeg extension version to 5+? It's already released by ffmpeg.

**Comment by tonihei** [comment]
No immediate plans to update the extension. If you have insights into required changes when upgrading to version 5, feel free to send a PR.

**Comment by emveepee** [comment]
> I'm assuming you are both using the Ffmpeg extension for the audio. 

Yes I am using ffmpeg 4.2 it is trivial to install on linux follow the instructions.   Out of curiosity, I remember EventLogger displaying whether or not ffmpeg was being used but I don't see that anymore.  Is that option still available?

**Comment by tonihei** [comment]
@emveepee There should be `audioDecoderInitialized` logs with the name of the decoder. The ffmpeg ones look like `ffmpeg-<ffmpegVersionNumber>-<ffmpegCodecName>`.

**Comment by emveepee** [comment]
Thanks, it was easier see it before on the main selection but this lets me know too.  And yes it is using ffmpeg on this sample.
```
10-07 09:37:49.464 32112 32112 D EventLogger: audioDecoderInitialized [eventTime=3.22, mediaPos=0.00, window=0, period=0, ffmpegLavc58.131.100-mp3]
versus h/w on more typical files.
10-07 09:51:00.721  1484  1484 D EventLogger: audioDecoderInitialized [eventTime=3.25, mediaPos=0.00, window=0, period=0, c2.android.aac.decoder]
```

**Comment by tonihei** [comment]
I'll close the issue assuming there is nothing left we can do here.
