### ISSUE TITLE
we need support for ac3 audio codec

### ISSUE THREAD

**Issue by maanich** [google/ExoPlayer#10679]
i am looking for support for the audio codec in our android app can't find a solution for exoplayer to work with ac3 codec with no sound in android devices.

**Comment by tonihei** [comment]
Some devices support ac3, but it depends on the available codecs on the device. You can also have a look at the Ffmpeg extension for a software codec solution that can be added to devices that support it by default.

**Comment by maanich** [comment]
Thanks for quick reply  is it possible to get ac3 support from your side in exoplayer .Most Chinese boxes don’t have ac3 support and you need to do it by your self. we are happy to pay if you will support us in making ac3 audible in our app. Sent from Mail for Windows From: toniheiSent: 07 October 2022 10:20To: google/ExoPlayerCc: maanich; AuthorSubject: Re: [google/ExoPlayer] we need support for ac3 audio codec (Issue #10679) Some devices support ac3, but it depends on the available codecs on the device. You can also have a look at the Ffmpeg extension for a software codec solution that can be added to devices that support it by default.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by tonihei** [comment]
Please have a look at the Ffmpeg extension as suggested above. We unfortunately can't help you to debug/build your app directly.

**Comment by maanich** [comment]
If you please guide me any link regarding ac3 n ffmoeg pleaseSent from IphoneOn 7 Oct 2022, at 10:46 am, tonihei ***@***.***> wrote:﻿
Please have a look at the Ffmpeg extension as suggested above. We unfortunately can't help you to debug/build your app directly.
