### ISSUE TITLE
RTSP Over HTTP Tunneling

### ISSUE THREAD

**Issue by joseandroidengineer** [google/ExoPlayer#10675]
Hi all,

Been using ExoPlayer for a while now and I'm experimenting with the idea of RTSP over Http Tunneling. Does Exoplayer support this?

If so, how can I configure the player so that its properly handled.
Thank you

**Comment by tonihei** [comment]
I don't think this is supported by default, but you may be able to set this up yourself by passing our own `SocketFactory` to `RtspMediaSource`.

**Comment by joseandroidengineer** [comment]
I'll have to make my own Socket Factory within the exoplayer itself?

**Comment by tonihei** [comment]
You can pass a `SocketFactory` to `RtspMediaSource.Factory` from your app.

**Comment by tonihei** [comment]
Closing the issue as it seems the question was answered.
