### ISSUE TITLE
MediaCodecAudioRenderer error when play live SmoothStreaming content

### ISSUE THREAD

**Issue by efrop12** [google/ExoPlayer#10674]
When we play live content in Smooth Streaming, sometimes we are having problems with the audio media codec. The error we get is the following:

android.media.MediaCodec$CryptoException 
MediaCodecAudioRenderer error, index=1, format=Format(0, audio101_spa, audio/mp4, audio/mp4a-latm, null, 96000, es, [-1, -1, -1.0], [2, 48000]), format_supported=YES | 11 | 1127 | 1138
MediaCodecAudioRenderer error, index=1, format=Format(null, audio_482_spa, audio/mp4, audio/mp4a-latm, null, 96000, es, [-1, -1, -1.0], [2, 48000]), format_supported=YES | 0 | 1063 | 1063
MediaCodecVideoRenderer error, index=0, format=Format(5, video, video/mp4, video/avc, null, 6815744, null, [1920, 1080, -1.0], [-1, -1]), format_supported=YES | 2 | 873 | 875
MediaCodecVideoRenderer error, index=0, format=Format(5, video, video/mp4, video/avc, null, 6500000, null, [1920, 1080, -1.0], [-1, -1]), format_supported=YES | 3 | 590 | 593
MediaCodecAudioRenderer error, index=1, format=Format(0, audio_spa, audio/mp4, audio/mp4a-latm, null, 95000, es, [-1, -1, -1.0], [2, 48000]), format_supported=YES | 5 | 545 | 550
MediaCodecVideoRenderer error, index=0, format=Format(6, video, video/mp4, video/avc, null, 6500000, und, [1920, 1080, -1.0], [-1, -1]), format_supported=YES | 2 | 380 | 382
MediaCodecVideoRenderer error, index=0, format=Format(3, video, video/mp4, video/avc, null, 4000000, null, [1024, 576, -1.0], [-1, -1]), format_supported=YES | 5 | 296 | 301
MediaCodecAudioRenderer error, index=1, format=Format(null, audio_482_qha, audio/mp4, audio/mp4a-latm, null, 96000, qha, [-1, -1, -1.0], [2, 48000]), format_supported=YES | 0 | 165 | 165
MediaCodecAudioRenderer error, index=1, format=Format(0, audio101_qha, audio/mp4, audio/mp4a-latm, null, 96000, qha, [-1, -1, -1.0], [2, 48000]), format_supported=YES | 0 | 116 | 116
MediaCodecVideoRenderer error, index=0, format=Format(3, video, video/mp4, video/avc, null, 4613734, null, [1024, 576, -1.0], [-1, -1]), format_supported=YES | 0 | 97 | 97
MediaCodecVideoRenderer error, index=0, format=Format(5, video, video/mp4, video/avc, null, 6499968, null, [1920, 1080, -1.0], [-1, -1]), format_supported=YES | 1 | 55 | 56

Any clue where it can go? , what we have been able to see is that the problem reproduces randomly so we cannot find the cause.

**Comment by tonihei** [comment]
This seems to be related to the DRM content protection. We'd need a full bugreport and ideally test media to investigate further. You can send links to dev.exoplayer@gmail.com with "Issue #10674" in the subject if you don't want to post here.

As a first step, I would also suggest looking at the reported errors in logcat in case the error already contains enough information to tell you what's wrong.

**Comment by efrop12** [comment]
Hello, as tonihei suggested, several days ago I sent the requested information by email. Thanks

**Comment by tonihei** [comment]
Thanks!  Found the email :) 

@rrfrias Could you take a look to see where the exception is coming from? Bug report is attached to the email.

**Comment by rrfrias** [comment]
Hi @efrop12, i would like to share your bugreport with Broadcom (SoC) for furthur analysis. Do i have your permission?

Are you able to reproduce this problem on other devices? Any repro steps would be helpful.

Internal ref: 260959116
