### ISSUE TITLE
Android 12L - AbstractMethodError calling onSpatializerAvailableChanged

### ISSUE THREAD

**Issue by asos-edgeorge** [google/ExoPlayer#10684]
### ExoPlayer Version

2.18.0

### Devices that reproduce the issue

All devices that have this issue are Samsung devices within the Galaxy Z Fold/Flip series, running Android 12 (presumably 12L)

For example, the three most popular devices experiencing this issue are:

* Galaxy Z Flip3 5G
* Galaxy Z Flip4
* Galaxy Z Fold3 5G

### Devices that do not reproduce the issue

Non-Galaxy Z Flip/Fold series devices

### Reproducible in the demo app?

Not tested

### Reproduction steps

We have seen this issue in the wild and unfortunately do not have access to the affected devices to find steps to reproduce this crash.

Based on the crash reports received, it seems 86% of crashes occur when the app is in the background. Due to the nature of foldable devices, this could be perhaps linked to a form config change (i.e. folding/unfolding) or something similar.

Should it help, our player is defined as follows (with some minor code omitted)

```kotlin
// Cache
val cache = SimpleCache(createVideoCacheDir(context),
                LeastRecentlyUsedCacheEvictor(VIDEO_CACHE_SIZE.toLong()),
                ExoDatabaseProvider(context))

// CacheDataSource
val upstreamFactory: DataSource.Factory = OkHttpDataSourceFactory({ request -> okHttp.newCall(request) }, USER_AGENT)
val cacheDataSource = CacheDataSource.Factory()
                .setCache(exoCache)
                .setUpstreamDataSourceFactory(upstreamFactory)
                .setFlags(CacheDataSource.FLAG_IGNORE_CACHE_ON_ERROR)

// ExoPlayer
ExoPlayer.Builder(context)
                .setLooper(Looper.getMainLooper())
                .setMediaSourceFactory(DefaultMediaSourceFactory(cacheDataSource))
                .setTrackSelector(DefaultTrackSelector(context, AdaptiveTrackSelection.Factory()))
                .build()
```

### Expected result

The media plays successfully and backgrounding the app works as expected

### Actual result

Exoplayer crashes with the following stacktrace 

```
Fatal Exception: java.lang.AbstractMethodError: abstract method "void android.media.Spatializer$OnSpatializerStateChangedListener.onSpatializerAvailableChanged(android.media.Spatializer, boolean)"
       at android.media.Spatializer$SpatializerInfoDispatcherStub.lambda$dispatchSpatializerAvailableChanged$1$Spatializer$SpatializerInfoDispatcherStub(Spatializer.java:529)
       at android.media.Spatializer$SpatializerInfoDispatcherStub$$ExternalSyntheticLambda0.run(Spatializer.java:6)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.os.HandlerThread.run(HandlerThread.java:67)
```

### Media

Not applicable

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by christosts** [comment]
Thank you for reporting the issue, we will investigate. I'd like to ask some additional information. You mention this occurs only on "Galaxy Z Fold/Flip series, running Android 12 (presumably 12L)". Just to confirm, do you have data if your app is running on other devices with Android 12L/13? For example, Pixel devices have started receiving Android 13. Any errors there?

[added]
To avoid the error, you can force ExoPlayer to stop listening to [`Spatializer`](https://developer.android.com/reference/android/media/Spatializer.OnSpatializerStateChangedListener) changes. On your custom `DefaultTrackSelector`, you need to set `DefaultTrackSelector.Parameters` where `constrainAudioChannelCountToDeviceCapabilities` is disabled. Something like (in java)

```java
DefaultTrackSelector trackSelector = ...
trackSelector.setParameters(
  trackSelector.buildUponParameters().setConstrainAudioChannelCountToDeviceCapabilities(false).build());
```

That will affect the audio track selection logic and will make the player always play the playable audio track with the highest channel count (which was the behavior before version 2.18). This would affect your app if it is streaming different audio formats (eg stereo and surround formats) and you were relying on ExoPlayer to pick-up stereo or surround audio depending on the [`Spatializer`](https://developer.android.com/reference/android/media/Spatializer) properties.

**Comment by christosts** [comment]
[internal ref b/252738423]

**Comment by asos-edgeorge** [comment]
Thanks @christosts for your response

> Just to confirm, do you have data if your app is running on other devices with Android 12L/13? For example, Pixel devices have started receiving Android 13. Any errors there?

Based on our crash reports, we are not seeing this for any other device family or Android version. We support all devices running Android 5.0+, so based on that it's a reasonable assumption to say it doesn't look to affect anything else at this time. 

However, should we see any additional devices or OS' in the report, I will update this ticket. 

Going forwards, we will follow the approach you suggest and monitor the results in our crash reports. We should have results to feedback to you in ~2 weeks.

If there's anything else you need from me to help diagnosis, please do let me know here or reach out via email

**Comment by punxoi** [comment]
I'm facing the same issue.
See additional information below.
Thanks.

### ExoPlayer Version
2.18.1

### Devices that reproduce the issue
**100%Android 12**
**100% samsung**

- 58% Galaxy Z Flip3 5G
- 24% Galaxy Z Flip4
- 5% Galaxy Z Fold4
- 5% Galaxy Z Fold3 5G
- 3% Galaxy Z Flip
- 2% Galaxy Z Flip 5G
- 2% Galaxy Z Fold2 5G
- <1% Galaxy Fold 5G
- <1% Galaxy Tab S7
- <1% Galaxy Tab S6 Lite
- <1% Galaxy Z Flip3 5G

### Stacktrace
```
Fatal Exception: java.lang.AbstractMethodError: abstract method "void android.media.Spatializer$OnSpatializerStateChangedListener.onSpatializerAvailableChanged(android.media.Spatializer, boolean)"
       at android.media.Spatializer$SpatializerInfoDispatcherStub.lambda$dispatchSpatializerAvailableChanged$1$Spatializer$SpatializerInfoDispatcherStub(Spatializer.java:529)
       at android.media.Spatializer$SpatializerInfoDispatcherStub$$ExternalSyntheticLambda0.run(Spatializer.java:6)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by christosts** [comment]
@punxoi thank you for the information. May I ask, you mention this occurs 100% on Android 12. Is that Android 12 (API 31) or Android 12L (API 32)? Everything should be on 12L (API 32), but if you've seen any reports in API 31, that would be an interesting data point.

It's unclear yet why this error happens.

**Comment by christosts** [comment]
@asos-edgeorge also on

>  it seems 86% of crashes occur when the app is in the background

what is the behavior of your app when it's sent to the background? For example, does it continue to play media, does it release the player, anything in between?

**Comment by asos-edgeorge** [comment]
@christosts 

> what is the behavior of your app when it's sent to the background? For example, does it continue to play media, does it release the player, anything in between?

So as far as I can tell, we are calling `player.stop(true)` which looks to be deprecated

**Edit:** Should you wish to see a video of this behaviour I would be happy to email it to the address within the Exoplayer Bug Report template

**Comment by punxoi** [comment]
@christosts 
> @punxoi thank you for the information. May I ask, you mention this occurs 100% on Android 12. Is that Android 12 (API 31) or Android 12L (API 32)? Everything should be on 12L (API 32), but if you've seen any reports in API 31, that would be an interesting data point.
> 
> It's unclear yet why this error happens.

Firebase Crashlytics seems to show both 12 and 12L as 12.
![image](https://user-images.githubusercontent.com/8148046/196069498-7e1eb8dd-1456-4e1d-9f44-960fcf12f19c.png)
![image](https://user-images.githubusercontent.com/8148046/196069538-bd4db34a-8763-4196-93cc-68537ec933e0.png)

**Comment by christosts** [comment]
@asos-edgeorge @punxoi what is the compileSdkVersion you are are using to build your apk? Specifically, are you using a version before 32 (e.g. 30 or 31)?

**Comment by Mavamaarten** [comment]
@christosts I haven't chimed in before, but I see the same crash in our Crashlytics. We currently use compileSdk 31 and targetSdk 30.

**Comment by asos-edgeorge** [comment]
@christosts Same as the above. Compile SDK is 31 and target is 30

**Comment by punxoi** [comment]
@christosts Both compile and target SDK versions are 31.

**Comment by 390057892** [comment]
![image](https://user-images.githubusercontent.com/23398269/197119491-23ce9554-f2e7-4f7b-809b-3c0d7e7720ee.png)
I encountered the same problem. The devices that reported errors in the statistical information on the bugly platform are all Samsung version and Android 12

**Comment by 390057892** [comment]
> ![image](https://user-images.githubusercontent.com/23398269/197119491-23ce9554-f2e7-4f7b-809b-3c0d7e7720ee.png) I encountered the same problem. The devices that reported errors in the statistical information on the bugly platform are all Samsung version and Android 12
This is my dependent version
` 
    def exoplayer_version = '2.18.1'
    implementation "com.google.android.exoplayer:exoplayer-core:$exoplayer_version"
    implementation "com.google.android.exoplayer:extension-okhttp:$exoplayer_version"
`

**Comment by tonihei** [comment]
To solve this issue you need to upgrade your `compileSdkVersion` to at least 32. This is necessary when you depend on libraries like ExoPlayer that are already compiled against 32. Upgrading the compile SDK should have no influence on the app behaviour, it just makes the latest Android SDK available during compilation and code shrinking.

**Comment by asos-edgeorge** [comment]
Thanks @tonihei - could you perhaps update the documentation to reflect this? I cannot find a reference to this requirement

**Comment by tonihei** [comment]
Well, we weren't fully aware of this either until yesterday. :)

But it definitely seems expected that an app uses at least the compile SDK that all of its dependencies are using. Some dependencies like AndroidX appcompat seem to be able to enforce this automatically, so we'll try to do the same in the future to avoid the additional documentation need.

**Comment by asos-edgeorge** [comment]
Amazing. Thank you for investigating this, in hindsight it seems fairly obvious this is the issue 😅 If you can enforce the version going forwards then that'd certainly help

**Comment by zgzong** [comment]
@tonihei 
I think Samsung have a bug that they are reporting the device with api level 32 as android os 12 as well. They didn't distinct the android 12 and 12L. 

We are facing the same problem here, but both the application compileSdkVersion and targetSdkVersion are 33. 
At moment, the dev team has not be able to reproduce the issue. We will update this thread when we find more.

**Comment by pft-BohoWu** [comment]
I got this problem too.
Is upgrade compileSdkVersion the only way to solve? 
Won't you do some change to fix?

Thanks.

**Comment by christosts** [comment]
So far, we've identified the issue is caused by proguard stripping out the listener methods. The change we plan to do is to force apps to set their compileSDKversion to at least match the library. Changing the compileSDKversion should not have a functional impact to the app (the target SDK version does not need to change alongside by the way).

**Comment by christosts** [comment]
A note on repro steps (fyi @zgzong)

> At moment, the dev team has not be able to reproduce the issue.

The issue occurs when the platform triggers a callback on the [`Spatializer.OnSpatializerStateChangedListener`](https://developer.android.com/reference/android/media/Spatializer.OnSpatializerStateChangedListener), which can happen only on Android 12L+ devices that support Spatial Audio (check `Settings -> Sound -> Spatial Audio`).  The player's default behavior since 2.18 is to register a listener to the platform `Spatializer` during track selection, therefore your app must have a player instance that has started playback at some point and has not released the player yet. 

One way to repro is to trigger the listener's `onSpatializerEnabledChanged` callback by manually enabling/disabling Spatial Audio from the device settings (if you are using a BT headset, this option can be on the BT headset configuration options). To enable/disable the device settings, the app activity needs to go to the background, therefore the app must keep the player instance in the background too. We used the media3 [session demo](https://github.com/androidx/media/tree/release/demos/session) which supports background playback to repro.

Alternatively, if you want to test with the app/player in the foreground, you may trigger the `onSpatializerAvailableChanged` callback by connecting/disconnecting a headset. The callback will be triggered if the device considers that only one of the output device can render spatial audio, either the device speaker or the headset, but not both. This of course depends on the device and headset. It's probably harder to repro this scenario but if your app releases the player when in the background, then this is probably the user journey that impacts your app.

**Comment by zgzong** [comment]
@christosts  Thanks for sharing the detail about how to test spatial audio. 

On the other side, we met same lint error in the android studio which has been reported to google issuetracker already here https://issuetracker.google.com/issues/234009300

**Comment by arjun-anar** [comment]
Facing this issue on 100% Samsung devices running on Android 13
<img width="422" alt="image" src="https://user-images.githubusercontent.com/113344360/208072981-a25b0ee5-2d2f-44a5-a825-e5c872242944.png">
