### ISSUE TITLE
Skipped midrolls do not play when skipped to the very end of the video duration

### ISSUE THREAD

**Issue by vishnuchilakala** [google/ExoPlayer#10685]
### Use case description
When a user skips to the very end of the video, the [IMA sample application ](https://github.com/googleads/googleads-ima-android) plays the last of all the skipped mid rolls by default before considering the playback as ended. The Exoplayer IMA Extension ends the playback instantly, not playing any of the skipped mid rolls.

### Proposed solution
On position discontinuity, check if any midrolls have been skipped. If yes, do not send the content complete signal to IMA as of yet.

**Comment by vishnuchilakala** [comment]
PR raised for this issue: https://github.com/google/ExoPlayer/pull/10618

**Comment by tonihei** [comment]
I can reproduce the problem, thanks for reporting! Will have a look at the PR and continue the discussion there.

**Comment by tonihei** [comment]
This is now fixed by the PR in https://github.com/google/ExoPlayer/pull/10618
