### ISSUE TITLE
Reopen: Certain Devices are crashing with SQLiteException when using DownloadManager

### ISSUE THREAD

**Issue by 0xera** [google/ExoPlayer#10686]
clone for https://github.com/google/ExoPlayer/issues/9221

I have absolutely same problem on these devices with android 9/10/11

Honor/Huawei:
8.63% HONOR 10 LITE (ANDROID 10)
6.98% HONOR 20S (ANDROID 10)
6.07% HONOR 9X LITE (ANDROID 10)
5.48% HUAWEI NOVA 5T (ANDROID 10)
5.36% HUAWEI P SMART Z (ANDROID 10)

83.34% ANDROID 10
14.13% ANDROID 9

Xiaomi:
7% Redmi Note 9 (ANDROID 11)
5% Redmi Note 8T (ANDROID 11)
5% Redmi 9 (ANDROID 11)
4% Redmi Note 8 (ANDROID 11)
4% Redmi Note 9S (ANDROID 11)

100% ANDROID 11

**Comment by 0xera** [comment]
#9221

**Comment by 0xera** [comment]
#9221

**Comment by icbaker** [comment]
I've re-opened #9221, closing this as a duplicate.

**Comment by 0xera** [comment]
> I've re-opened #9221, closing this as a duplicate.

I cant write any comment in original issue( 

So I think this maybe happen because some vendor do something with sqlite for optimization. Maybe for fix add to exoplayer opportunity to use other databases?

**Comment by icbaker** [comment]
Sorry, I unlocked https://github.com/google/ExoPlayer/issues/9221 - you should be able to comment now.
