### ISSUE TITLE
How to stop buffering old mediaItem manifest when play other mediaitem?

### ISSUE THREAD

**Issue by thucngv** [google/ExoPlayer#10683]
I have a mediaitem list, when I switch to another mediaitem, the player continues to load the manifest of the old mediaitem

**Comment by icbaker** [comment]
Please provide clear & complete steps we can use to reproduce this - and also please provide a clear explanation of how you are measuring/observing "the player continues to load the manifest of the old mediaitem".

**Comment by thucngv** [comment]
> Please provide clear & complete steps we can use to reproduce this - and also please provide a clear explanation of how you are measuring/observing "the player continues to load the manifest of the old mediaitem".

I play a mediaitem playlist .
when next mediaitem, old mediaitem still loading manifest.
You can check by logging http request

**Comment by icbaker** [comment]
Closing because the clear repro steps requested weren't provided.
