### ISSUE TITLE
Configuration information 

### ISSUE THREAD

**Issue by shripaljadhav** [google/ExoPlayer#10689]
Hi everyone ,

1. Would like to know is there any method through which we can get DEFAULT_BUFFER_FOR_PLAYBACK_MS and DEFAULT_BUFFER_FOR_PLAYBACK_AFTER_REBUFFER_MS programmatically.  
2. Is there any algorithm which will decide depending on our network strength what will be the DEFAULT_BUFFER_FOR_PLAYBACK_MS and DEFAULT_BUFFER_FOR_PLAYBACK_AFTER_REBUFFER_MS .
3. Can we modify DEFAULT_BUFFER_FOR_PLAYBACK_MS and DEFAULT_BUFFER_FOR_PLAYBACK_AFTER_REBUFFER_MS when video is playing .

**Comment by icbaker** [comment]
> 1. Would like to know is there any method through which we can get DEFAULT_BUFFER_FOR_PLAYBACK_MS and DEFAULT_BUFFER_FOR_PLAYBACK_AFTER_REBUFFER_MS programmatically.

These are public fields, so you can read them programmatically from `DefaultLoadControl`.

> 2. Is there any algorithm which will decide depending on our network strength what will be the DEFAULT_BUFFER_FOR_PLAYBACK_MS and DEFAULT_BUFFER_FOR_PLAYBACK_AFTER_REBUFFER_MS .

These values are compile-time constants, they will not change based on your "network strength".

> 3. Can we modify DEFAULT_BUFFER_FOR_PLAYBACK_MS and DEFAULT_BUFFER_FOR_PLAYBACK_AFTER_REBUFFER_MS when video is playing .

No, see above - these are compile-time constants.
