### ISSUE TITLE
codec.queueSecureInputBuffer() calls taking too long for Widevine 60fps on some platforms

### ISSUE THREAD

**Issue by mbolaris** [google/ExoPlayer#10695]
In our testing with ExoPlayer on 60fps Widevine encrypted content we've observed calls to codec.queueSecureInputBuffer() are taking ~8-12ms on the Fire TV Omni and FireTV Insignia. On other platforms, we've checked the time is around ~4-6ms. These long queueSecureInputBuffer() times combined with needsSynchronizationWorkaround being set in doQueueSecureInputBuffer() prevent ExoPlayer from processing an audio and video sample on average every 16ms.

If we don't set needsSynchronizationWorkaround and feed audio and video in parallel we can mostly meet the ~16ms average time but it's still close.

If we look at the history of needsSynchronizationWorkaround it looks like it was initially only enabled for manufacturer.contains("samsung") || manufacturer.contains("motorola") but in the change to Make asynchronous queueing non-experimental (7a2c7c3297ea7dbe265cab215974178648c7d009) we see that the secure input synchronization workaround was applied universally.

Questions are:
Does anyone have any info on the decision to apply the secure input synchronization to all platforms or other info related to [Internal: b/149908061]?   
Any idea if it's likely safe to disable the needsSynchronizationWorkaround for the problem platforms so that we are calling codec.queueSecureInputBuffer() for audio and video in parallel from separate threads? On some platforms(Broadcom) we see video corruption without needsSynchronizationWorkaround but so far our limited testing of FireTV devices has not shown any issues with needsSynchronizationWorkaround set to false.

Also any idea about anything that could be causing the codec.queueSecureInputBuffer() calls to be so slow on the AFTTIFF43 and INSIGNIA_NS_43F301NA22?

**Comment by christosts** [comment]
`needsSynchronizationWorkaround` is there to solve the corrupted video issue you observed. There is no error raised when that happens, so the player or any app don't have a way to detect that at runtime. It was originally seen on some Samsung and Motorola phones and later on then it was detected on a Pixel 3. The fact that the video corruption cannot be detected led us to enable it for all devices.

> Any idea if it's likely safe to disable the needsSynchronizationWorkaround for the problem platforms so that we are calling codec.queueSecureInputBuffer() for audio and video in parallel from separate threads? On some platforms(Broadcom) we see video corruption without needsSynchronizationWorkaround but so far our limited testing of FireTV devices has not shown any issues with needsSynchronizationWorkaround set to false.

Debugging the corrupted video on one device went down to how the OEM implemented the native crypto API.  The implementation was re-using memory buffers per DRM session and the concurrent calls to MediaCodec.queueSecureInputBuffer() for audio and video were effectively corrupting data is those buffers. There was no public API to detect such an implementation detail, and thus enable the workaround only when needed. Unfortunately, I cannot offer more concrete help when to enable or disable the work around apart from extensive testing on the device at hand, and perhaps monitoring user reports.

> Also any idea about anything that could be causing the codec.queueSecureInputBuffer() calls to be so slow on the AFTTIFF43 and INSIGNIA_NS_43F301NA22?

It goes down to how the crypto API is implemented by the OEM. Unfortunately, I don't have more details other than saying that this is device specific.

**Comment by christosts** [comment]
Leaving the issue open for anyone else who may want to add some information.
