### ISSUE TITLE
Playback freeze on chunk discontinuity

### ISSUE THREAD

**Issue by sergju** [google/ExoPlayer#10692]
Playback freeze and no any error about discontinuity

### ExoPlayer Version

2.18.1

### Devices that reproduce the issue

Samsung Galaxy A30s

### Reproducible in the demo app?

Yes

### Reproduction steps

Start play stream

### Expected result

Playing stream until the end

### Actual result

Playing freeze after 6sec

### Media

[discont1.zip](https://github.com/google/ExoPlayer/files/9799926/discont1.zip)

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by tonihei** [comment]
Sorry for the late reply, but you have to define a discontinuity in the HLS playlist if the chunks are discontinuous. If I add `#EXT-X-DISCONTINUITY` before the second chunk, playback doesn't fail and instead continues as expected.
