### ISSUE TITLE
Play video with user agent or referr

### ISSUE THREAD

**Issue by ahmedaa6122** [google/ExoPlayer#10690]
How i can play videos with user agent or referr in exoplayer 2.18.1? I need full code please. Thanks

**Comment by icbaker** [comment]
* https://exoplayer.dev/network-stacks.html
* https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/upstream/DefaultHttpDataSource.Factory.html#setUserAgent(java.lang.String)
* https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/upstream/DefaultHttpDataSource.Factory.html#setDefaultRequestProperties(java.util.Map)
