### ISSUE TITLE
Startup delay not fixed when changing load control parameters

### ISSUE THREAD

**Issue by Malobash** [google/ExoPlayer#10704]
### ExoPlayer Version

2.18.1

### Devices that reproduce the issue

android mbox android 11.1

### Reproducible in the demo app?

Not tested

### Reproduction steps

1. add 2 media items:  udp://@192.x.x.x:1234 and udp://@192.x.x.y:1234  exoplayer demo app
2. try to switch between them by calling seekTo(2)
3. check the delay on startup, audio play before video and video is freezing for about 3 seconds

### Expected result

switch between channels of udp stream smoothly and quickly without letting the user wait 3 seconds before the video play
also audio and video must play in the same time

### Actual result

Delay in startup of playing udp video, in my case the audio buffer before the video for about 3 seconds while the video is streaming
Actually the audio play quickly but video no

### Media

ublic static void initializeExoPlayer() {

        ExoTrackSelection.Factory videoTrackSelectionFactory = new AdaptiveTrackSelection.Factory();
        RenderersFactory renderersFactory = new DefaultRenderersFactory(context.getApplicationContext())
                .setEnableAudioTrackPlaybackParams(true);
        TrackSelector trackSelector = new DefaultTrackSelector(context);
        trackSelector.setParameters(trackSelector.getParameters().buildUpon()
                .setMaxVideoSizeSd()
                .setPreferredTextLanguage("ar")
                .setPreferredAudioLanguage("en")
                .setMaxVideoBitrate(Integer.MAX_VALUE)
                .setPreferredAudioLanguages(languages)
                .build());
        ExoPlayer.Builder playerbuilder = new ExoPlayer.Builder(context);
        DefaultLoadControl loadControl = new DefaultLoadControl.Builder()
                .setBufferDurationsMs(5000, 5000, 250, 5000)
                .build();

        player = playerbuilder.setTrackSelector(trackSelector).setRenderersFactory(renderersFactory)
                .setLoadControl(loadControl).build();

        DataSource.Factory factory = () -> new UdpDataSource(3000, 10000);

        List<MediaSource> mediaSources = new ArrayList<MediaSource>();
        for (int i = 0; i < channels.size(); i++) {
            if (i < 20) {
                Uri videoUri = Uri.parse(channels.get(i).getStreaming_url());
                MediaSource mediaSource =
                        new ProgressiveMediaSource.Factory(factory)
                                .createMediaSource(new MediaItem.Builder()
                                        .setUri(videoUri)
                                        .build());
                mediaSources.add(mediaSource);
            }
        }
        player.setMediaSources(mediaSources);
        BaseTVActivity.playerView.setPlayer(player);
        player.prepare();

        player.setPlayWhenReady(true);
    }

### Bug Report

- [x] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by tonihei** [comment]
Sorry for the late reply. I think this is likely an issue in the media itself where the player can't find a start of the video stream. I assume this is using Transport Steam (TS)? If so, you might want to try some of the TS extractor flags in case they help. See https://developer.android.com/media/media3/exoplayer/troubleshooting#why-do-some-mpeg-ts-files-fail-to-play
