### ISSUE TITLE
Disabling complete access of software rendering mode in exoplayer

### ISSUE THREAD

**Issue by Kaviya-M** [google/ExoPlayer#10703]
I am developing a media player application. In that, audio/video player are developed using exoplayer API's.
My requirement is like I need to disable the complete use of software codecs for rendering. 
As per the documentation, it seems like exoplayer in default uses hardware acceleration first, and if hardware acceleration is not available it works on software codec for that particular file.
My expectation is the exoplayer should not play the media file if software rendering is needed for playing that media file. Only hardware acceleration must be supported.
I used below API's to set rendering modes. But unable to see any progress.
`DefaultRenderersFactory defaultRenderersFactory = new DefaultRenderersFactory(mContext).setEnableDecoderFallback(false);
                defaultRenderersFactory.setExtensionRendererMode(DefaultRenderersFactory.EXTENSION_RENDERER_MODE_ON).
                mBuilder.setRenderersFactory(defaultRenderersFactory);`

**Comment by christosts** [comment]
If you want to not use software decoders at all, you can provide a custom `MediaCodecSelector` by calling `DefaultRenderersFactory.setMediaCodecSelector()`. Your custom `MediaCodecSelector` can forward the `getDecoderInfos()` call to `MediaCodecSelector.DEFAULT` and then filter out any `MediaCodecInfo` that is not `hardwareAccelerated `.

Enabling decoder fallback or the extension renderers serve different functions.
