### ISSUE TITLE
Hello, how can i show button forward and backward at mini controller for chromecast function?

### ISSUE THREAD

**Issue by renesotolira** [google/ExoPlayer#10714]
Hello, how can i show button forward and backward at mini controller for chromecast function?

**Comment by marcbaechinger** [comment]
The general answer is that you can use `CastPlayer` like any other `Player` implementation with UI or other components that take a `Player`. So the anwser to the question is more or less that you can do that in the same way as for `ExoPlayer`. 

If you have problems with this approach please narrow down your question a bit to make it actionable for us. We can't give you support for general app development questions I'm afraid.
