### ISSUE TITLE
Ts url not work in android 9 and higher

### ISSUE THREAD

**Issue by ahmedaa6122** [google/ExoPlayer#10710]
Im use exoplayer 2.18.1 and when run my project in androi 8 and try ts url its work but when try my project in android 9 and higher ts url not work and this is my simple code who i use to play url

```
String videoUri = getIntent().getStringExtra("url");
String userg = "REDLINECLIENT";

	ExoPlayer player = new ExoPlayer.Builder(this).setTrackSelector(trackSelector).build();

	DefaultHttpDataSource.Factory dataSourceFactor = new DefaultHttpDataSource.Factory().setUserAgent(userg);

	ExtractorsFactory extractorsFactory = new DefaultExtractorsFactory();

	MediaSource mediaSource = new ProgressiveMediaSource.Factory(dataSourceFactor, extractorsFactory)
			.createMediaSource(MediaItem.fromUri(videoUri));
	// Create a player instance.

	playerView.setPlayer(player);

	player.prepare(mediaSource,true,true);

	player.setPlayWhenReady(true);`
```

And this is my Ts url :

http://77.247.109.140:2095/AYATV/AYAVIP/23958?token=GhoNVBVaEA4WWwMNBgtTWQJTBlQAVAECVQoGUwENUlcEDFAAU1AHAwZBHBpHRhBdAA9oDQdACQMBDFEJABgWERJdF2oPVhAOFlcACAUAUBpNQEMNDgcRCAIOVgYBAABdVg9JFxZbVhYODUVUWB5AXRkWUhYNA19tV10UWFJRFl4PTQlZShBdWmsHVVVVXAYaW0AGRk9AWkFDGlhfRFhYSENaDEEUU0ZRFlleTVheThoCDUIKFxBKEAkaMWgTGBYBGUwAWxVbXVoWWRJMRxBOGggRaBYGEUdAVlkPVEMWDkZRGkkXC1NKa1cMXlZRURZRDgxERllAAhAfGg9eX11ACxNnFVwCEAhaQQ9cRQ==

**Comment by christosts** [comment]
It would help if you mentioned the error raised. I noticed the content url is HTTP and not HTTPS, so I think your app may not be able to resolve HTTP urls. If that is so, please read the [Fixing “Cleartext HTTP traffic not permitted” errors](https://exoplayer.dev/troubleshooting.html#fixing-cleartext-http-traffic-not-permitted-errors) advice.

If that's not the problem, I suggest you try playing the content on the demo app. For example, it works fine with me on a Pixel 6 with Android 13 with the cleartext HTTP fix mentioned above. If the error persists, please report to us the specific device you are using and include a bug-report obtained from the device after the error occurred.
