### ISSUE TITLE
How to set large icon for download notification ?

### ISSUE THREAD

**Issue by donny9095** [google/ExoPlayer#10715]
Hi developers and everyone here,

This is just a question, and I hope you can help me answer it.
I'm wondering How to set large icon for download notification, when ExoPlayer library doesn't support it anymore.
I also want to know why the set large icon feature is gone.
Can you please detail How I can show the large icon when downloading ?

Thank you very much.

**Comment by marcbaechinger** [comment]
If you are asking about the notification that is created by the `DownloadService` then you can override `DownloadService.getForegroundNotification()` to provide whatever notification you wish to show. The demo app uses the `DownloadNotificationHelper` for creating this notification but this can be customized with whatever notification you want to show for you app.

**Comment by donny9095** [comment]
@marcbaechinger 
Thank you so much for your reply.
> If you are asking about the notification that is created by the DownloadService

Yes, This is exactly what I wanted to ask.

But Can you tell more details for your suggestion ?
Because in the demo app, https://github.com/google/ExoPlayer/blob/release-v2/demos/main/src/main/java/com/google/android/exoplayer2/demo/DemoDownloadService.java
I can not set large icon for `buildProgressNotification()` or `buildDownloadCompletedNotification()` or `buildDownloadFailedNotification()` methods.

Sorry, You mean I must to create a custom class based on `DownloadNotificationHelper` instead use `DownloadNotificationHelper` ?

An example code help me a lot ! Thank you !

**Comment by marcbaechinger** [comment]
You would have to create your own helper class or method that [builds a notification](https://developer.android.com/develop/ui/views/notifications). Then override the method `DownloadService.getForegroundNotification()` and return the notification you have built yourself.

Sample code for this is in the `DownloadNotificationHelper`.

**Comment by donny9095** [comment]
@marcbaechinger 
Thank you for your reply.
Can you tell me why the set large icon feature is removed ? Because I see previous versions were able to set large icon, but it has been removed in recent versions.

**Comment by donny9095** [comment]
@marcbaechinger 
Thank you for your reply !
Do you have any plans to add set large icon option for `DownloadNotificationHelper` in the future ? Because I don't want to create a custom class, that will make it harder for me to update the version of ExoPlayer.

**Comment by marcbaechinger** [comment]
We don't have plans to add this in the future yet. I can mark this issue as an low-priority enhancement, but the chances that this is being added is fairly small I'm afraid. If you want to have this any time soon, then I think you need to look into this yourself. Sorry for not having a better answer.

**Comment by donny9095** [comment]
@marcbaechinger 
Thank you for your reply.
Your answer helped me a lot ! Thank you again !
