### ISSUE TITLE
[IMA] Content is loaded before ad for DASH content

### ISSUE THREAD

**Issue by vishnuchilakala** [google/ExoPlayer#10719]
### ExoPlayer Version

2.18.1

### Devices that reproduce the issue

All devices

### Reproducible in the demo app?

Yes

### Reproduction steps

Play any content using the Exoplayer IMA Extension for ad supported playback.

### Expected result

Ad manifest should first be downloaded and playback should start, while concurrently / sequentially downloading the manifest of the actual content. (As Exoplayer correctly does with `.mkv` content but not with DASH content)

This would ensure that the video start time does not take a hit.

### Actual result

Content manifest is downloaded first, followed by ad manifest and only then the playback would start. (As Exoplayer wrongly does with DASH content but not with `.mkv` content)

This adds the content manifest download time to the video start time, which adds a significant hit.

### Media

Any DASH content with any IMA ad tag.

1. Play any of the `IMA Sample ad tags` content from the Demo app, all of which have `.mkv` contents.
2. Observe the behaviour i.e. ad manifest gets loaded first before the content.
3. Replace the `.mkv` content with any DASH stream (like [this one](https://storage.googleapis.com/exoplayer-test-media-1/60fps/bbb-clear-1080/manifest.mpd)) and start a playback again.
4. Observe the behaviour i.e. content manifest is downloaded first, followed by the ad manifest and only then the playback starts.

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by marcbaechinger** [comment]
I think you are right that the `AdsMediaSource` first starts preparing the content source and then starts the ads loader that makes the SDK download the ad tag. This is [done at the very same moment](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/source/ads/AdsMediaSource.java#L189) though and I don't think that switching these lines makes a difference. 

The `AdsMediaSource` behaves in the same way for whatever type of content source this is. Whether it is DASH or progressive media doesn't make a difference in behaviour.

> This would ensure that the video start time does not take a hit.

I can't see how we can improve this by changing the behaviour of the `AdsMediaSource` because loading the content stream and loading ads metadata by the SDK is processed in parallel. If you can share some ideas that work, we can change this issue to an enhancement so we can implement that improvement.

> This adds the content manifest download time to the video start time, which adds a significant hit.

Can you give a bit of more detail how and what you measured and what you are comparing with? It is true, that for DASH the player needs to download a manifest first and then picks media chunks from that manifest which adds a bit of more latency than for progressive sources like MVK or MP4.

**Comment by vishnuchilakala** [comment]
Thanks for the quick reply @marcbaechinger ! 

I looked at the sequence of network events happening on the Demo app.

**For DASH content:**
1. Actual content manifest is downloaded. (MPD)
2. Ads are loaded and then the ad manifest is downloaded.
3. Ad chunks start downloading and the playback starts.

**For `.mkv` content:**
1. Ads are loaded and then the ad manifest is downloaded.
2. Ad chunks start downloading and the playback starts.
3. Content starts downloading. (MKV)

Thus, the video start time (VST) for DASH includes the time taken to download the content manifest too, as opposed to the other type of content.


> This is [done at the very same moment](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/source/ads/AdsMediaSource.java#L189) though and I don't think that switching these lines makes a difference.


This is not what I am observing though.

**For a DASH media source:**
<img width="1790" alt="Screenshot 2022-10-25 at 5 55 56 PM" src="https://user-images.githubusercontent.com/80761270/197772450-a409a5cd-8996-40b5-8804-a25b861e5cca.png">
I see that the ad loading starts only after the content manifest is downloaded.

**But in the case of a progressive media source:**
<img width="1791" alt="Screenshot 2022-10-25 at 6 02 40 PM" src="https://user-images.githubusercontent.com/80761270/197773900-e0c0714f-07f4-4bd4-898d-d6a8f4a6d4fb.png">
The ads manifest is downloaded, the ad stream is downloaded and only then the content starts downloading.

I don't think this is happening concurrently / ad-first, which would not be a problem. But it is happening sequentially, which is hurting the VST.

> Can you give a bit of more detail how and what you measured and what you are comparing with?

I was testing with the content named `VMAP pre-roll` from the Demo app, where I saw that the behaviour is always to load the ad first. I then replaced the content uri with [this](https://storage.googleapis.com/exoplayer-test-media-1/60fps/bbb-clear-1080/manifest.mpd) and saw that the content manifest is now being loaded first as opposed to the ad manifest.

We recently introduced ads (mostly a single minute long pre-roll HLS ad for all DASH contents) using the Exoplayer IMA extension, post which there has been a significant increase in the average VST. Thus, we are looking for improvement opportunities.

Is there any obvious way to tweak this `AdsMediaSource` behaviour? Can you please direct me towards any relevant piece of code? Thanks!

**Comment by vishnuchilakala** [comment]
@marcbaechinger Can you please check the above comment and let me know if this indeed is expected behaviour? If not, can you please direct me on how I can change this behaviour?

**Comment by vishnuchilakala** [comment]
@marcbaechinger Any updates on this issue? Please let me know. Thanks!

**Comment by marcbaechinger** [comment]
No updates, sorry. 

> I don't think this is happening concurrently

The Dash manifest is loaded by ExoPlayer in a thread started for downlaoding, while the ad resources are loaded by the ads SDK. These are running in different threads. Your diagram from above shows that `native_sdk....` starts loaded while the `manifest.mpd` is still downloading.
