### ISSUE TITLE
Jerking video with addMediaItem

### ISSUE THREAD

**Issue by ipnet-me** [google/ExoPlayer#10734]
Hello there.

ExoPlayer Version: 2.16.1

Devices that reproduce the issue: Xiaomi Mi A2

I am doing a demo player that can play TS segments files from local directory or from URL
I this demo project I have 8 TS files, each video have 4 seconds duration. But every 4 seconds, I can see tiny jerking, in most cases you are not seeing it, but in case very dynamic video it is notable. I have very simple source code. 
Also I have uploaded my assets TS files [https://file.io/92R2O4HFlEyY](https://file.io/92R2O4HFlEyY)

I tested same TS segments in HTML5 video player - it playing very smooth. Also if put this files into m3u8 file and 

`player.setMediaItem(MediaItem.fromUri("seg.m3u8")) `

 also playing smooth without any issue

I would appreciate, if you can help me

Thanks

```
package com.arunavision.android.myapplication;

import androidx.appcompat.app.AppCompatActivity;

import android.app.ActionBar;
import android.net.Uri;
import android.os.Bundle;
import android.view.View;

import com.google.android.exoplayer2.ExoPlayer;
import com.google.android.exoplayer2.MediaItem;
import com.google.android.exoplayer2.source.DefaultMediaSourceFactory;
import com.google.android.exoplayer2.source.MediaSource;
import com.google.android.exoplayer2.ui.PlayerView;
import com.google.android.exoplayer2.util.MimeTypes;

import java.util.ArrayList;
import java.util.List;

public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);


        ExoPlayer player = new ExoPlayer.Builder(this.getBaseContext())
                .setMediaSourceFactory(new DefaultMediaSourceFactory(this.getBaseContext()))
                .build();


        String[] intArray = new String[]{ "638018019700000000", "638018019740000000", "638018019780000000", "638018019820000000", "638018019860000000", "638018019900000000", "638018019940000000", "638018019980000000"};



        List<MediaItem> mediaItems = new ArrayList<>();

        for (int i=0; i<intArray.length;i++){


            MediaItem mediaItem = new MediaItem.Builder()
                    .setUri(Uri.parse("asset:///"+intArray[i]+".asf"))
                    .build();


            mediaItems.add(mediaItem);

        }


        player.setMediaItems(mediaItems);

        player.prepare();
        player.play();

        PlayerView playerView = findViewById(R.id.idExoPlayerView);
        playerView.setPlayer(player);


    }
}
```

**Comment by tonihei** [comment]
I don't have access to the files anymore, but I assume that your individual TS files may not start at a keyframe or require the player to reinitialize the codec. If you play them individually, the player assumes they come from independent streams and only if you create an HLS playlist does the player assume these TS files represent continuous content and can be played without additional setup. Given you already solved the issue by using an HLS playlist, I'll close this issue.

**Comment by ipnet-me** [comment]
Hello, thanks for reply me, I am very sorry that example TS files were missing. I added new, can you check them, please.

https://file.io/92R2O4HFlEyY
