### ISSUE TITLE
How can I delay video in Exo Player

### ISSUE THREAD

**Issue by joshimaulik** [google/ExoPlayer#1073]
Hello,

I have a special requirement to delay video by 500ms in exo player.

If anyone of you have any idea please show me right direction to do it.

Thanks in Advance

**Comment by Bastian35022** [comment]
Do you want to delay the video track relative to the audio track, or delay all tracks relative to the live edge (assuming you are playing live content)?

**Comment by joshimaulik** [comment]
Yes, video track relative to audio track and vice versa

**Comment by Bastian35022** [comment]
In the ExoPlayer, the video track rendering is timed based on the audio track position. You could try introducing the offset in member getPositionUs() of MediaCodecAudioTrackRenderer, by adding the offset to the return value. Might break a few things though (especially for larger offsets), i don't fully understand the timing mechanisms of the ExoPlayer in detail.

**Comment by AquilesCanta** [comment]
I do not know which is the right direction. I can tell you that the MediaClock interface is used to provide timing information to the renderers. And something usually done, also, is to use the Audio track as "time provider", let us say. Perhaps, you could offset the time obtainment in the Video renderer to include an offset. Bastian's comment has just appeared. I would think twice before including the offset *in* the Audio part, as it would affect anything that takes its timing from the audio, I guess. So, I would incline towards the Video itself. I will make some research. If something useful comes up (such as the realization of having said something incorrect), I will write back. As a first impression, I don't know if this is something completely trivial, I supposed that muxed contents could provide a difficult scenario.

**Comment by Bastian35022** [comment]
I agree, doing this in the MediaCodecVideoTrackRenderer is the nicer solution. It even offers the interface FrameReleaseTimeHelper, which you can implement and set a corresponding class instance as frameReleaseTimeHelper. The delay must then be implemented in "adjustReleaseTime". It is a bit of work to implement this though.

**Comment by joshimaulik** [comment]
I figure out the way to do this Audio & Video delay. For video, I changed the "elapsedSinceStartOfLoopUs" and added the offset. For Audio, I changed the buffer timestamp to delay it.

Thank you guys for your response and comments.

**Comment by joshimaulik** [comment]
I am in quite a situation here, my audio and video delay are both working fine if I am rendering both audio and video.
But if I stops rendering the Video and only Audio renders at that time audio delay is not working. To make it work I tried to change  the handleBuffer(ByteBuffer buffer, int offset, int size, long presentationTimeUs) method in Audio Track.java class.

I added & Subtracted offset to each of the different times like, bufferstarttime, startMediaTimeUs, presentationTimeUs but none of this is working. I also tried by adding an offset into GetPositionUs method but all this is changes the seek position that's it. They don't delay the audio

As per above comments if I do the change in MediaCodecVideoTrackRenderer, then also it won't be in effect because I am not rendering Video at all.

**Comment by Bastian35022** [comment]
I thought you want to delay audio and video with respect to each other. If only audio is played, then what is the delay that you want to control?

**Comment by joshimaulik** [comment]
Below are my use cases:

1) I am playing MPEG DASH streaming on a tablet, in that case my Audio and Video both are played on one tablet and I can able to delay both of them by changing TimeStamps and releaseFrameTimings as per my comment. This is working fine

2) I want to play MPEG DASH streaming in such a way, that the Video will render on the Monitor and Audio will render on the tablet. For this, what I did is, stop rendering the Video on the Tablet. But in that case when I hit the play button, Audio on the tablet is going ahead than the Video on the monitor. That's the reason I want to delay the audio by couple of milliseconds so that I can make both Audio and Video in sync.

Sorry for my less understanding language, but I hope you get an overall idea what I want to do and why I want to delay the audio.

**Comment by ojw28** [comment]
- What's the use case for (1)?
- I don't really understand (2). Are the two devices playing independently, or is the monitor connected to the tablet? If they're separate devices then what's the synchronization mechanism between the two?

**Comment by joshimaulik** [comment]
1) use case for first point is I want to delay both audio and video on a tablet only.

2)Yes, those are two devices independently. Two devices are working in this manner. On first device user will press the Play button, so that a message will go to the second device to play the video and as soon as second device started playing video it will send Audio TimeStamps (bufferinfo.PresentationTimeUs) to the first tablet and that tablet will receive those timestamps and adjust their position accordingly and will play the audio at that timestamps.

**Comment by Bastian35022** [comment]
How about adjusting the timestamps that are exchanged between the tablets accordingly? That should steer the audio position and lead to the desired effect.

**Comment by joshimaulik** [comment]
I did it. I exchanged the Timestamp (Bufferinfo.presentationTimeUs) which is used in ProcessOutputBuffer method of MediaCodecAudioTrackRenderer.java class. I multicast this timestamp from the second device (which is playing AV both) and receive it on first device (which is playing audio only), but when I do fast forward on second device, it's not adjusting the audio on first device instead it adjust only the progress bar timestamp.

**Comment by Bastian35022** [comment]
If you use fast forward, the seekTo functions of the ExoPlayer and of the individual renderers are called (only on the device on which you do the fast forward). You also have to call these seekTo functions of the player on the other devices, with the same timestamp.

**Comment by ojw28** [comment]
I still don't understand what the point of (1) is. I understand what it does, I just don't understand why you would want to do it. If you're playing only on the tablet and you're delaying both audio and video, isn't that more or less the same as delaying neither of them? What are you actually trying to achieve?

For (2) I think you'd find it easier if you were to make the video on the monitor render earlier rather than having the audio on the tablet render later.

**Comment by joshimaulik** [comment]
@Bastian35022, I see that whenever we fast forward it's calling the seekTo function of MediaCodecAudioTrackRenderer then TrackRenderer and then SampleSourceTrackrenderer.java class. Thank you very much for your help.

Now the same way I am calling the seekTo function, if I found a sudden jump in the Timestamp which I am receiving on first device, from MediaCodecAudioTrackRenderer class, but it crashes the app. Is there anyohter way or place where I can call this seekTo() function to sync the audio?

**Comment by joshimaulik** [comment]
@ojw28, I want to delay the video & Audio for (1) point because, there is a bluetooth latency in android and this latency is different for different devices.

for (2), i can do that, but where I am stuck is if user FF the AV on monitor it should sync the audio on tablet which is not happening right now. For that i need to go with @Bastian35022 suggested way.

**Comment by Bastian35022** [comment]
The seekTo function of which class to you call? It looks like you have to call at least `seekToInternal` in `ExoPlayerImplInternal`, or even further up the stack if that's more convenient. Then, `seekTo` is also called for all enabled renderers.

**Comment by joshimaulik** [comment]
@Bastian35022, I called the player.seekTo() in player activity where I am receiving time stamps and when the difference between the two time stamps is greater than 2 seconds. And it seems it's working correctly and adjusting the audio chunks accordingly.

Thanks a lot for all your help guys...
