### ISSUE TITLE
API to set the length of the media to play (start and end)

### ISSUE THREAD

**Issue by susantasweng** [google/ExoPlayer#10739]
### [REQUIRED] Use case description
There is a video file which has pre + main + post video contents in a single video file. Now rather than trimming the main part of the video, as a library user I want to set the entire file as a source but also want to set the start and end to the player.
So that, player will show the total time, seek bar and seeking options according to this custom start and end time rather than the complete video content from the source.
It will be a great help if this would be possible.

Thank you.

**Comment by marcbaechinger** [comment]
Take a look at the DevGuide page about the `MediaItem` that has a [section about clipping a media stream](https://exoplayer.dev/media-items.html#clipping-a-media-stream). As described there you can do this with `MediaItem` properties or by using a `ClippingMediaSource`.

I'm closing this issue. Please reopen if you think this doesn't do what you want to achieve.
