### ISSUE TITLE
Exoplayer does not play H264 AVC1 file on Galaxy Tab A7

### ISSUE THREAD

**Issue by Timo1993** [google/ExoPlayer#10737]
I would like to play an MP4 file on the Galaxy Tab A7. It is downloaded from a webserver and stored on the device in the movies folder. When I open the MP4 video file with Android applications, it works well. But I have problems to open it with the Exoplayer. It throws the following error:

2022-11-02 07:26:57.571 7111-7770/xxx.xxx.xxxx D/MediaCodecInfo: NoSupport [codec.profileLevel, avc1.420029, video/avc] [OMX.SEC.avc.sw.dec, video/avc] [gta4lwifi, SM-T500, samsung, 30]

On the website it shows that H264 should be supported.

My code to load the video file:

              DataSource.Factory dataSourceFactory = new 
              DefaultDataSource.Factory(activity);
              File myDir = new File(Enironment.getExternalStoragePublicDirectory(Environment.DIRECTORY_MOVIES), "Test");
              String FILENAME = "video.mp4";
              File file = new File(myDir, FILENAME);
              Uri uri = Uri.fromFile(file);
              MediaItem mediaItem = MediaItem.fromUri(uri);
              MediaSource videoSource = new ProgressiveMediaSource.Factory(dataSourceFactory)
                    .createMediaSource(mediaItem);`

Do you have any idea why it is not supported?

**Comment by microkatz** [comment]
Reopening.

**Comment by microkatz** [comment]
@Timo1993 
That error code conveys one of two possible issues. One would be that the device does not contain a decoder that has codec profiles matching the one needed to decode the video file. The other would be that the decoder does indeed have a matching profile, but does not contain levels that can handle the codec level required by the video file.

Would you be able to provide a link to the mp4 file that is reproducing this issue?

**Comment by microkatz** [comment]
@Timo1993 
That error code conveys one of two possible issues. One would be that the device does not contain a decoder that has codec profiles matching the one needed to decode the video file. The other would be that the decoder does indeed have a matching profile, but does not contain levels that can handle the codec level required by the video file.

Would you be able to provide a link to the mp4 file that is reproducing this issue?
