### ISSUE TITLE
Set Max Bitrate still possible?

### ISSUE THREAD

**Issue by techker** [google/ExoPlayer#10747]
If version 2.10.1 from this tutorial
https://takusemba.medium.com/set-max-bitrate-on-exoplayer-e9cd4cc77445

Were can set the Max bit rate to a stream.

Is this still possible with latest version?

I need to reduce the bitrate in the preview player in EPG

**Comment by marcbaechinger** [comment]
It's possible to limit the max bitrate when selecting tracks of an adaptive stream. The dev guide has a page about [track selection](https://exoplayer.dev/track-selection.html) that tells about the API in the latest version.
