### ISSUE TITLE
how many attempts does the player have in case the player failed to request in the first time?

### ISSUE THREAD

**Issue by Lilsax** [google/ExoPlayer#10744]
How many attempts does the player have to request the manifest in case the player failed to request in the first time?

And is there anyway to insecure that if it exits ?

Like the player will attempt up to 3 times to request the manifest if it failed

**Comment by marcbaechinger** [comment]
There is a [section in the DeveloperGuide](https://exoplayer.dev/customization.html#customizing-error-handling) that explains how an app can customize the load error behavior by using an custom `LoadErrorHandlingPolicy` or by configuring the `DefaultLoadErrorHandlingPolicy`. The `DefaultLoadErrorHandlingPolicy` has a constructor that lets you define the `minimumLoadableRetryCount` which is set to 3 by default.
