### ISSUE TITLE
Compose crash when player is no longer visible

### ISSUE THREAD

**Issue by vidicunt** [google/ExoPlayer#10745]
### ExoPlayer Version

2.18.1

### Devices that reproduce the issue

Android emulator (tried on API 33)

### Reproducible in the demo app?

Not tested

### Reproduction steps

This is the compose code:

```
    val listener = remember {
        object : Player.Listener {
            override fun onPlaybackStateChanged(playbackState: Int) {
                if (playbackState == PlaybackState.STATE_ERROR)
                    onError()

                super.onPlaybackStateChanged(playbackState)
            }
        }
    }

    val mPlayer = remember {
        ExoPlayer.Builder(context).build().apply {
            repeatMode = ExoPlayer.REPEAT_MODE_ALL
            addListener(listener)

            setMediaItem(MediaItem.fromUri(uri))
            prepare()
        }
    }

    DisposableEffect(
        AndroidView(
            factory = {
                StyledPlayerView(context).apply {
                    useController = false
                    resizeMode = RESIZE_MODE_ZOOM
                    player = mPlayer
                }
            }, modifier = modifier
        )
    ) {
        onDispose {
            mPlayer.run {
                removeListener(listener)
                stop()
                release()
            }
        }
    }
```

### Expected result

App should not crash

### Actual result

App crashes

### Media

Not applicable

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by tonihei** [comment]
This is likely a similar problem as https://github.com/google/ExoPlayer/issues/10480. The player needs to be released when the Activity goes into the background (`onStop`/`onPause`) to avoid leaking resources or other unintended side effects.
