### ISSUE TITLE
Cannot play video without audio

### ISSUE THREAD

**Issue by windseamless** [google/ExoPlayer#10757]
It is impossible to play video without audio using HLS (whether there is audio data in the m3u8 is unpredictable). 
How to make it work in compatibility mode (if there is audio data in the m3u8, audio and video will be played at the same time; if there is no audio data, only video will be played).

Is there any good plan?
Thank you in advance.

**Comment by tonihei** [comment]
It definitely possible to play a stream without audio unless the player has been told by some metadata to expect audio and then gets stuck when trying to find audio data in the stream. That's impossible to say without having access to the stream.

**Comment by windseamless** [comment]
> It definitely possible to play a stream without audio unless the player has been told by some metadata to expect audio and then gets stuck when trying to find audio data in the stream. That's impossible to say without having access to the stream.

Thanks for answering!
However, I encountered a problem: when HLS started playing, there was audio data, and when there was no audio data during the playing, the playing stopped and could not continue.

**Comment by tonihei** [comment]
> However, I encountered a problem: when HLS started playing, there was audio data, and when there was no audio data during the playing, the playing stopped and could not continue.

This sounds like expected behavior. If the stream has audio data at some point, the player can reasonably assume that all the segments have audio data. And for this reason, it tries to load more data until it finds the audio data. 

If your stream set up changes, I'd suggest to create a separate m3u8 playlist that reflects the changes and add it as a new item to the player.

**Comment by windseamless** [comment]
> > However, I encountered a problem: when HLS started playing, there was audio data, and when there was no audio data during the playing, the playing stopped and could not continue.
> 
> This sounds like expected behavior. If the stream has audio data at some point, the player can reasonably assume that all the segments have audio data. And for this reason, it tries to load more data until it finds the audio data.
> 
> If your stream set up changes, I'd suggest to create a separate m3u8 playlist that reflects the changes and add it as a new item to the player.

Yes, I can dynamically modify whether my audio and video streams are packaged at the same time when recording.

This is a good suggestion. I'll try it.

**Comment by tonihei** [comment]
Closing this issue as it was either solved or there is nothing more we can do in the library to help.
