### ISSUE TITLE
Media controls missing in notification on Android 13

### ISSUE THREAD

**Issue by Zimbelstern** [google/ExoPlayer#10752]
Player notifications look very different on different API levels:

8: ![](https://zimbelstern.eu/8_resized.png)

12: ![](https://zimbelstern.eu/12_resized.png)

13: ![](https://zimbelstern.eu/13_resized.png)

Colors and layout doesn't mean much to me but what I've been trying to achieve for several days now is to **include rewind and fast-forward controls** as well as my **custom stop button** on **API level 33**. Everything I've tried so far has affected Android versions up to 12 only. The notification drawn on Android 13 _hasn't changed_ a bit.

I would like to have a notification layout like [presented here by Google](https://developer.android.com/static/images/about/versions/13/media-controls-phone-tablet.png).

So please tell me: How can I achieve this with exoplayer?

Below, you can find my code for the audio player service. I've shortened it for better readability.
In `onStartCommand()` there is:
```
mediaSession = MediaSessionCompat(this, TAG)
mediaSessionConnector = MediaSessionConnector(mediaSession)
player = ExoPlayer.Builder(this)
	.setTrackSelector(DefaultTrackSelector(this))
	.build()
	.also {
		it.setMediaItem(...)
		mediaSessionConnector.setPlayer(it)
		it.playWhenReady = true
		it.prepare()
	}.apply {
		addListener(object : Player.Listener {
			...
		})
	}
mediaSession.isActive = true
playerNotificationManager = customPlayerNotificationManager()
playerNotificationManager.setPlayer(player)
playerNotificationManager.setMediaSessionToken(mediaSession.sessionToken)
```

This is my `customPlayerNotificationManager`:
```
private fun customPlayerNotificationManager(): PlayerNotificationManager {
	return object : PlayerNotificationManager(
		this,
		PLAYER_CHANNEL,
		PLAYER_NOTIFICATION_ID,
		mediaDescriptionAdapter,
		null,
		customActionReceiver,
		R.drawable.ic_item_audio,
		R.drawable.ic_player_notification_play,
		R.drawable.ic_player_notification_pause,
		R.drawable.ic_exoplayer_stop,
		R.drawable.ic_exoplayer_rewind,
		R.drawable.ic_exoplayer_forward,
		R.drawable.ic_image_dummy,
		R.drawable.ic_image_dummy,
		null
	) {
		override fun createNotification(player: Player, builder: NotificationCompat.Builder?, ongoing: Boolean, largeIcon: Bitmap?): NotificationCompat.Builder? {
			return super.createNotification(player, builder, ongoing, largeIcon)?.also {
				startForeground(PLAYER_NOTIFICATION_ID, it.build())
			}
		}
	}.apply {
		setUsePreviousAction(false)
		setUseRewindActionInCompactView(true)
		setUseFastForwardActionInCompactView(true)
		setPlayer(player)
		setBadgeIconType(NotificationCompat.BADGE_ICON_NONE)
	}
}
```

My `customActionReceiver`:

```
private val customActionReceiver = object : PlayerNotificationManager.CustomActionReceiver {
	override fun getCustomActions(player: Player): MutableList<String> {
		return mutableListOf("STOP_PLAYER")
	}
	override fun createCustomActions(context: Context, instanceId: Int): MutableMap<String, NotificationCompat.Action> {
		return mutableMapOf(Pair("STOP_PLAYER",
			NotificationCompat.Action(R.drawable.ic_exoplayer_stop, R.string.exoplayer_stop_description,
				PendingIntent.getBroadcast(context, 1, Intent("STOP_PLAYER")
					.setPackage(context.packageName), IMMUTABLE_FLAG_OR_FALLBACK or PendingIntent.FLAG_CANCEL_CURRENT))))
	}
	override fun onCustomAction(player: Player, action: String, intent: Intent) {
		when (action) {
			"STOP_PLAYER" -> stopPlayerService()
		}
	}
}
```

I have a `mediaDescriptionAdapter `, too.
```
private val mediaDescriptionAdapter = object : PlayerNotificationManager.MediaDescriptionAdapter {
	override fun getCurrentContentTitle(player: Player): CharSequence {
		...
	}
	override fun createCurrentContentIntent(player: Player): PendingIntent? {
		...
	}
	override fun getCurrentContentText(player: Player): CharSequence? {
		...
	}
	override fun getCurrentLargeIcon(player: Player, callback: PlayerNotificationManager.BitmapCallback): Bitmap? {
		...
	}
}
```

**Comment by marcbaechinger** [comment]
Media controls [changed in Android 13](https://developer.android.com/about/versions/13/behavior-changes-13#playback-controls). You can do this with `MediaSessionConnector/PlayerNotificationManager` but then you need to serve the media session for Android 13 and the notification for API levels before 13. 

Alternatively you can try the [Media3 session module](https://github.com/androidx/media/tree/release/libraries/session) that provides support for all API levels.

**Comment by Zimbelstern** [comment]
Thanks. After trying again with `MediaSessionConnector` I've found the method I was looking for:
**`setCustomActionProviders`**

A `PlaybackStateCompat.CustomAction` for each button (similar and in addition to `PlayerNotificationManager.CustomActionReceiver`) seems to fix my problems with Android 13.
