### ISSUE TITLE
Save ExoPlayer Cache video in device Gallery

### ISSUE THREAD

**Issue by AsitDixit** [google/ExoPlayer#10754]
I'm playing video from URL in ExoPlayer and caching it using SimpleCache.

My app has a feature that the user can save video if he/she wants.

My video playing layout has a save button if the user click on that I want to save that video in his/her mobile gallery.

How can I achieve that? & what is the most effective way? Is there any way to save the cache video in gallery? One thing if user click the button before the download completed what should I do?

And one thing I'm playing a list of video in recyclerView if the user clicks on the save button and scrolls up/download I think the download will be distributed ,I think I have save video in a separate thread !!

**Comment by tonihei** [comment]
I would recommend downloading the file directly (e.g. using `HttpURLConnection`) if you want it to be playable by the gallery app. ExoPlayer's caching mechanism is optimized for caching byte ranges whenever we load them, and to reuse those ranges if possible. But it's not a generic downloader that just saves the entire file to disk.

**Comment by tonihei** [comment]
Closing the issue as it seems the question was answered.
