### ISSUE TITLE
LoopingMediaSource  Deprecated

### ISSUE THREAD

**Issue by guoxiaolongonly** [google/ExoPlayer#10755]
I need to merge two videos, the first video plays once and the second video loops infinitely.

but the LoopingMediaSource  deprecated in 2.18.1.Is there any way to achieve this function in 2.18.1.

code like this.  

    public static MediaSource buildMergeMediaSource(Context context, String firstUrl, String nextUrl) {
        DefaultDataSource.Factory defaultDataSourceFactory = new DefaultDataSource.Factory(context);
        ConcatenatingMediaSource mergingMediaSource = new ConcatenatingMediaSource(
                new DefaultMediaSourceFactory(defaultDataSourceFactory)
                        .createMediaSource(MediaItem.fromUri(firstUrl)),
                new LoopingMediaSource(
                        new DefaultMediaSourceFactory(defaultDataSourceFactory)
                        .createMediaSource(MediaItem.fromUri(nextUrl))));
        return mergingMediaSource;
    }

**Comment by tonihei** [comment]
As explained in the [deprecation notes](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/source/LoopingMediaSource.html), you can just use `player.setRepeatMode(Player.REPEAT_MODE_ONE)` once you reach the second item in the playlist.
