### ISSUE TITLE
Scaling video with Aspect Ratio

### ISSUE THREAD

**Issue by Angels-group** [google/ExoPlayer#1076]
Good day ! 

How can i scale video with ascpect ratio ?
I need to expand the width. Make the width of the video, the same as the width of my frame.
Thus, the part of a video may be invisible ..

This method is used in TVs. It called zoom.

![example](https://cloud.githubusercontent.com/assets/1552042/11908679/5e4dd17e-a5ef-11e5-83be-bb1f2a01177b.jpg)

Now i have "ORIGINAL", but need "SCALED".
I use SurfaceView and AspectRatioFrameLayout from ExoPlayer sample.
Method to set Aspect Ratio - like in example

videoFrame.setAspectRatio(height == 0 ? 1 : (width * pixelWidthAspectRatio) / height)

**Comment by ojw28** [comment]
The `MediaCodecVideoTrackRenderer` constructors take a `videoScalingMode` parameter. See [here](https://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer/MediaCodecVideoTrackRenderer.html#MediaCodecVideoTrackRenderer(android.content.Context,%20com.google.android.exoplayer.SampleSource,%20int)). You should experiment with passing `MediaCodec.VIDEO_SCALING_MODE_SCALE_TO_FIT_WITH_CROPPING` as the value for that parameter.

You probably don't want to use `AspectRatioFrameLayout` in conjunction with this parameter. It might make more sense to use `SurfaceView` directly, or alternatively use `AspectRatioFrameLayout` but set the ratio based on the desired ratio of the view, not the ratio of the video.

**Comment by Angels-group** [comment]
I found solution:

I use FrameLayout instead AspectRatioFrameLayout. Now i need implement a method that should comply with the aspect ratio.
So, i can change SurfaceView size manually like that (just for example):

```
ViewGroup.LayoutParams lp = surfaceView.getLayoutParams();
lp.height = 1500;
lp.width = 1500;
surfaceView.setLayoutParams(lp);
```

Thank you, ExoPlayer developers!
