### ISSUE TITLE
ExoPlayer, mobile technology (5G) connection and high bitrate IPTV live streams

### ISSUE THREAD

**Issue by romeor** [google/ExoPlayer#10766]
Hello,

Background:
I'm using TiviMate app which uses ExoPlayer to play content. Recently I got myself 5G Internet connection which runs 500 mbps down and 50 mbps up. My external router looks directly to the mast which is located like 1-1,5 km from my place, so my connection signal is strong and I get my 500 mbps. Also I've got a fibre connection on 300/300 mbps.

Issue:
When I watch high quality IPTV Live streams with 5G connection using TiviMate which uses ExoPlayer, picture starts to randomly buffer. It doesn't happen always. It may play for some time ok and then starts to buffer pretty often. If i switch to fiber, it does not. So what I did is compared TiviMate and Clouddy (which is using VLC library) network patterns. It seems, like TiviMate's burst just kill the 5G connection. It generates burst as 8000+ pps download and 3000+ pps upload. While Clouddy runs without such large burst and buffering never happens. 

I've attached pictures to compare traffic patterns with Clouddy and TiviMate (ExoPlayer). Does anybody have an idea how TiviMate dev could fix that behaviour? Or maybe there is fix needed from ExoPlayer devs team? I read the docs and it seems like issue could be in chosen network stack (may be dev should allow the end user to decide, which network stack should be used, if one is better for mobile connections than other) or maybe it is related with some kind of optimization which works wrong with mobile connections?

Clouddy:
![clouddy](https://user-images.githubusercontent.com/5564169/201062646-b83ae6e4-0bd4-4738-9bdd-4650e7fc77e8.PNG)
TiviMate
![tivimate](https://user-images.githubusercontent.com/5564169/201062651-76268968-e036-45bc-bc00-f019c027aea9.PNG)
TiviMate vs Clouddy
![tvmatevsclouddy](https://user-images.githubusercontent.com/5564169/201062656-215b2a6c-5690-49af-991b-55362e2b9368.PNG)
And using TiviMate when TV uses fiber internet connection
![kaabliga](https://user-images.githubusercontent.com/5564169/201093968-0268169c-3fb9-43d7-8b25-2791ef9b7e53.PNG)

**Comment by tonihei** [comment]
ExoPlayer has no or little influence on the behavior of the underlying network stack I'm afraid. We just open a HTTP connection and let the network stack handle the actual data transfer. As you say, there might be some difference depending on which network stack you are using and you can choose between the Android default, OkHttp and Cronet. See https://exoplayer.dev/network-stacks.html for more details.

**Comment by romeor** [comment]
Okay, thank you for the answer.

**Comment by romeor** [comment]
Hello,

have to open this one. It comes out it is not related to bursts.  it is something with ExoPlayer. When I use VLC/Clouddy it is ok. Is there any way I could as a user debug this issue for you?

**Comment by tonihei** [comment]
As indicated above, I would suggest to try out different network stacks and look into configuration options offered by Cronet and OkHttp to optimize this case. If you see certain options you think should always be set for ExoPlayer, please let us know, otherwise the behavior of the network stack is outside of our control.

**Comment by romeor** [comment]
Hello,

I'm sorry to update this issue, but i am not a developer and can't play with exoplayer settings. If I share the playlist I use, could you please take a look at the issue?

**Comment by romeor** [comment]
just to mind, i have analyzed a bit further the process. When I watch streams using ExoPlayer based players (televizo, tivimate, navigator ott etc) using my 5G connections and this buffering occurs like you see from the graphs above, all other apps in the same box with player start to act buggy. They all start to buffer and internet connection suffers. But other boxes and devices behind same 5G modem work fine. I think it is somehow related to the tivimate and android. Some more advanced or may be a dev should take a look i guess. and this happens only with cel. based connections. Both LTE and 5G in my case.

**Comment by romeor** [comment]
one new and important thing i should add, is that in CEL network tcp mss is 1400 and when i get dump of interface, i see a lot of retransmits. it might be an issue that needs attention? vlc some-how passes around it.

**Comment by romeor** [comment]
Ignore this. its somewhat hardware problem on isp side.

**Comment by romeor** [comment]
just for history: latest Zyxel 7101 FW V1.00(ABUV.7)C0 update fixes the issue.

9. [Internal Iusse #30757] [TR-369] Modify manual APN setting by SET message cause connection abnormal and connection unstable
