### ISSUE TITLE
Manifest creation

### ISSUE THREAD

**Issue by techker** [google/ExoPlayer#10761]
Hey guys , I'm digging in to an issue with our app. The issue we have is that some streams with live content that when you select audio/caption in the seek bar we odd selections.

Noticed on HLS

Multi language
French
essti 
und ..

we only need the Language selection.And not Multi language..

First I would like to know how this manifest is created?is it during the encoding process?

this is part of what we receive :
Group:0, adaptive_supported=N/A [
                                 [X] Track:0, id=1/15, mimeType=audio/mp4a-latm, codecs=mp4a.40.2, channels=2, sample_rate=48000,   **language=mul, supported=YES**
                              ]
                                 Group:1, adaptive_supported=N/A [
                                  [ ] Track:0, id=aac:fra a1, mimeType=audio/mp4a-latm, codecs=mp4a.40.2, channels=2, sample_rate=48000, language=fr, label=fra a1, supported=YES
                               ]
                               Group:2, adaptive_supported=N/A [
                                   [ ] Track:0, id=aac:dvs a2, mimeType=audio/mp4a-latm, codecs=mp4a.40.2, channels=2, sample_rate=48000, language=und, label=dvs a2, supported=YES
                                ]

I also noticed the [X] in the track mul? is there a way to get that info from that node?so I can remove it in the code.

I have been debugging the process and found that some streams return null as language or "en" that causes to double up English selection or if null shows unknown language.

Track:0, id=1/15, mimeType=audio/mp4a-latm, codecs=mp4a.40.2, channels=2, sample_rate=48000,  null, supported=YES**

Why only on some channels we get back mul that shows Multi Language.

I would like to learn more about this manifest process?or is this metatada?is it the provider that sets this?or is it exoplanet that generates this file?

thx!

**Comment by tonihei** [comment]
The manifest is created by the content producer (it's the M3U8 file you likely provided as a URI) and its them who should fix the content if needed. "mul" is and allowed RFC5646 language tag for "content in multiple languages" and it seems correct to offer this choice to the user if that's what the stream contains? 

You can manually enforce certain language preferences by track selection options, see https://exoplayer.dev/track-selection.html.

**Comment by tonihei** [comment]
Closing under the assumption that the question was answered.
