### ISSUE TITLE
Android Auto rejected because of audio not ducking

### ISSUE THREAD

**Issue by wasmedia96** [google/ExoPlayer#10768]
### ExoPlayer Version

2.18.1

### Devices that reproduce the issue

I have no idea which device google is using for testing Android Auto.

Here is my code.

```
player = ExoPlayer.Builder(context).build()
        player?.setHandleAudioBecomingNoisy(true)
        val audioAttributes: AudioAttributes = AudioAttributes.Builder()
            .setUsage(C.USAGE_MEDIA)
            .setContentType(C.AUDIO_CONTENT_TYPE_MUSIC)
            .setAllowedCapturePolicy(C.ALLOW_CAPTURE_BY_ALL)
            .build()
        player?.setAudioAttributes(audioAttributes,true)
        player?.addListener(this)
```

### Devices that do not reproduce the issue

Android auto Head unit with Android 9

### Reproducible in the demo app?

No

### Reproduction steps

Eligibility issues
--

Eligibility Issue 1: Driver distraction features -> Your app includes features that distract the driver. For example, your app does not pause or reduce the volume of the audio being played while the microphone is active. App does not perform as expectedYour app does not perform all functions properly or as expected from a user perspective.For example, when attempting to test audio functionality in Android Auto, two sets of audio are played at the same time. Driver distraction features Your app includes features that distract the driver. For example, your app does not pause or reduce the volume of the audio being played while the microphone is active.

 

### Expected result

My app should not rejected because i am using exoplayer to handle audio focus itself. 

### Actual result

My App rejected due to audio focus

### Media

I have no SC for this issue

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by Tolriq** [comment]
I guess you are new to Play Store and supporting Android Auto.

You will get plenty of such random rejections from that team validation over the life of your app. This will test your patience more than once.

Most of the time they will be false issues generated by wrong usage or device issue by the tester that will not make any attempt to understand and will reject.

Update version code push again and most of the time it will pass.

**Comment by tonihei** [comment]
I'd also suggest to test this yourself, e.g. triggering navigation instructions while you app is playing to see if it actually works. Your setup looks correct and I would assume that ducking works automatically.

**Comment by wasmedia96** [comment]
> I'd also suggest to test this yourself, e.g. triggering navigation instructions while you app is playing to see if it actually works. Your setup looks correct and I would assume that ducking works automatically.

Yes i did and its working for me.

**Comment by tonihei** [comment]
Then there is probably not much we can do in this issue tracker because the player is doing the right thing. If you think the certification isn't testing their requirements correctly, you probably need to get in touch with them to clarify that.

**Comment by Tolriq** [comment]
@wasmedia96 just to reassure you a little, it's frustrating as hell, it makes everybody loose time but you get used to it, because you have no choice :)

![image](https://user-images.githubusercontent.com/932609/201113795-afe29620-fbf5-468f-8cb7-06e2b5a20391.png)

Same exact random rejection the 28th September, updated version code and it passed as with now nearly 30 times happened in the last 7 years of Android Auto support in that app.

Even if you appeal and they redo the tests they will ask you to republish a new APK so don't waste time if you can't reproduce what they say.

Good luck with your app.
