### ISSUE TITLE
auto sniffing HLS and mp4 and do not need developer to build TrackRenderer myself

### ISSUE THREAD

**Issue by LiuDeng** [google/ExoPlayer#1077]
in demo app i use the first config and it play well
1.new Sample("YouKU","http://us.sinaimg.cn/0017W0DNjx06XTEl1ZfN050d010000i60k01.m3u8",
                  PlayerActivity.TYPE_HLS),
while if i use the second it play error
2.new Sample("YouKU","http://us.sinaimg.cn/0017W0DNjx06XTEl1ZfN050d010000i60k01.m3u8",
                  PlayerActivity.TYPE_OTHER),

#438 can exoplayer auto sniffing HLS and mp4 to auto play well?

**Comment by andrewlewis** [comment]
You could choose which renderer builder to use based on the URL like in [PlayerActivity.inferContentType](https://github.com/google/ExoPlayer/blob/1855a5a97d5fb6e6733d390148923a4c559f6546/demo/src/main/java/com/google/android/exoplayer/demo/PlayerActivity.java#L693). This is not as robust as ExtractorSampleSource's sniffing, which looks for structure in the input stream, but may be good enough for some use cases. I don't think we have any plans to sniff playlists/manifests like we do for media containers, at least in the near future.
