### ISSUE TITLE
Edit mode BG color

### ISSUE THREAD

**Issue by SudoDios** [google/ExoPlayer#10772]
Hi developers.
how to change edit mode background color ?
```xml
R.color.exo_edit_mode_background_color
```
can change to dark color 😅 ?

sudodios.

**Comment by icbaker** [comment]
This value is not customisable without forking the UI module or [depending on ExoPlayer as source](https://github.com/google/ExoPlayer#locally) and modifying `constants.xml`. This value is only used when displaying the `PlayerView` and `StyledPlayerView` in Android Studio and other developer tools, it is not used in production: https://developer.android.com/reference/android/view/View#isInEditMode()
