### ISSUE TITLE
Android 13 Support?

### ISSUE THREAD

**Issue by xiaoshu101** [google/ExoPlayer#10771]
From the release notes, there is no Android 13 compatibility for the latest version#2.18.1. 
We are wondering when you'll be supporting Android 13. Thanks

**Comment by tonihei** [comment]
Could you let us know which feature/change you are interested in?

**Comment by xiaoshu101** [comment]
We are workong on the Android 12 with exoplayer r2.17. And our target shall update the Android version to Android 13. 
So we want to know whether there is a new release version to support the Android 13 or not. Thanks

**Comment by yuroyami** [comment]
What is exactly is not working on Android 13?

**Comment by xiaoshu101** [comment]
Check the latest release version#2.18.2. There is no  Android 13 compatibility section too and the version 2.17.0 contain these information.
Therefore. If the device Android version update to the Android 13. Does it have a new version to adapter the Android 13 compatibility  ?

**Comment by tonihei** [comment]
There is no major adaptation needed for the core ExoPlayer library. If you think something needs to be adapted, please let us know more concretely, otherwise I'll just close this issue because there is nothing actionable for us.
