### ISSUE TITLE
How to get currently playing video track?

### ISSUE THREAD

**Issue by Karthik-0** [google/ExoPlayer#10775]
Hi, I am trying to display the current resolution in which the video is playing as youtube does.
As far as I have checked TrackIndex is required for this. But how to get a track index for current playing tracks?

![image](https://user-images.githubusercontent.com/41418580/201523321-5d30f0b9-259d-47cd-8d17-3427681cd048.png)

**Comment by icbaker** [comment]
To get the resolution of the currently playing track you can call [`Player.getVideoSize()`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/Player.html#getVideoSize()) (or use the [listener callback](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/Player.Listener.html#onVideoSizeChanged(com.google.android.exoplayer2.video.VideoSize))).

If you want more format info about the currently playing track you can listen to [`AnlayticsListener.onVideoInputFormatChanged`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/analytics/AnalyticsListener.html#onVideoInputFormatChanged(com.google.android.exoplayer2.analytics.AnalyticsListener.EventTime,com.google.android.exoplayer2.Format,com.google.android.exoplayer2.decoder.DecoderReuseEvaluation)).

**Comment by Karthik-0** [comment]
Thanks, @icbaker. It works.
