### ISSUE TITLE
Ensuring bitstream compatibility with ISO/IEC 14496-3 1.6.2.1

### ISSUE THREAD

**Issue by psharma676** [google/ExoPlayer#10785]
### [REQUIRED] Use case description
ISO/IEC 14496-3:2009 section 1.6.2.1  (AudioSpecificConfig) allows an audio stream set to a custom/arbitrary sampling frequency. Sampling frequency is a custom number when "samplingFrequencyIndex" == 0xf . When that is the case, there should be no less than 24 bits of "samplingFrequency" in the bitstream else it is an error/exception. 

### Proposed solution
1) Ensure that the spec is not being violated by adding appropriate bit stream length checks in AacUtil.getSamplingFrequency()
2) Add unit test cases for class AacUtil that do not exist at the moment.

**Comment by tonihei** [comment]
Thanks for the report and the PR!

As this is adding an additional correctness check without any new handling for these cases, I wonder why you want to add this check? Did you see media files where this condition is not fulfilled and that failed in other unexpected ways? Or is there another reason to introduce this check outside of "the spec says this isn't allowed"?

**Comment by psharma676** [comment]
It is a media error/violation seen in the field, but unfortunately we do not have a stream capture as it is not easy to reproduce. To instrument this change, we walked backwards from an out of bounds exception in bitArray.readBits(24). This change allows us to detect these media errors and gives the caller an option to handle them by retrying with the next segment and/or logging errors.

**Comment by tonihei** [comment]
Thanks for the clarification! The part about not getting a helpful error if it's just an IndexOutBoundsException is the purpose of your addition I didn't see initially. We'll merge the change soon.

**Comment by psharma676** [comment]
Yes, that is entirely correct, a helpful error is, well, more helpful :-) . Thanks for your review and glad I could help!
