### ISSUE TITLE
Update IMA SDK

### ISSUE THREAD

**Issue by dev-sharma-deltatre** [google/ExoPlayer#10788]
Exoplayer latest version is using IMA SDK: 3.26.0

3.26.0 will deprecate on March 1, 2023, and is only a few months away: https://developers.google.com/interactive-media-ads/docs/sdks/android/client-side/deprecation

Can we please update it to the latest version? 
Thank you

**Comment by tonihei** [comment]
The IMA version is already updated since https://github.com/google/ExoPlayer/commit/60a3ea48b8abf3949a87a2b3bc930ce83cf4ce3f

**Comment by dev-sharma-deltatre** [comment]
@tonihei  Is it updated on 2.18.1? I am using this version. I believe this is the latest one.

**Comment by tonihei** [comment]
No, the commit will be part of the next upcoming release only

**Comment by dev-sharma-deltatre** [comment]
Okay.  Can you please update me on the time frame when we are expecting that release?

**Comment by tonihei** [comment]
We don't give precise release dates, but it shouldn't be far away (a few days most likely)

**Comment by dev-sharma-deltatre** [comment]
Thank you so much for the prompt response. I really appreciate it.
