### ISSUE TITLE
Player unpauses media after preparing it even with playWhenReady set to false

### ISSUE THREAD

**Issue by yuroyami** [google/ExoPlayer#10796]
### ExoPlayer Version

2.18.1

### Devices that reproduce the issue

All devices I have

### Devices that do not reproduce the issue

-

### Reproducible in the demo app?

Not tested

### Reproduction steps

I have an app that loads media every 10 seconds (prepares it from storage using a DocumentFile Uri).

When ExoPlayer is initialized, I set the playWhenReady to false, to make sure it doesn't randomly unpause the playback when I prepare a media. However, on the second time (and third, and fourth, and so on), when I load media item and prepare it, it unpauses the video no matter what, unless I manually pause it to stop it (which is my current workaround)

### Expected result

Media should not play automatically with playWhenReady set to off.

### Actual result

Media is automatically playing after being prepared, thus ignoring playWhenReady = false

### Media

It doesn't matter which media I load, or what format, so it's not format-specific.

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by christosts** [comment]
Can you provide a minimal piece of code that demonstrates the problem? Ideally either modify the demo app and share a patch, or share a minimal project that we can download and reproduce the issue.

Thanks
