### ISSUE TITLE
Initial Bitrate Estimates do not follow suit for India

### ISSUE THREAD

**Issue by vishnuchilakala** [google/ExoPlayer#10790]
### ExoPlayer Version

2.18.1

### Devices that reproduce the issue

All

### Reproducible in the demo app?

Yes

### Reproduction steps

Play from / Hardcode India as the country and check the initial bitrate estimates.

### Expected result

5G_NSA > 5G_SA > 4G > 3G > 2G

### Actual result

5G_NSA >  4G > 5G_SA > 2G > 3G

### Media

Any media

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by vishnuchilakala** [comment]
PR raised with the fix: #10789

**Comment by tonihei** [comment]
This is working as expected because these number are based on real-world data and we update them in regular intervals. Even though 5G-SA aims to be faster than 4G, this is not necessarily the case in practice yet when averaged across an entire country.

**Comment by tonihei** [comment]
It's also worth highlighting that you can amend all of these values and group assignments in the `DefaultBandwidthMeter.Builder` if required.
