### ISSUE TITLE
Eac3 audio in video

### ISSUE THREAD

**Issue by carrinhoff** [google/ExoPlayer#10791]
I have a video that has "eac3 audio codec" , the video works perfectly but with no audio.
I've tried to use ffmpeg , i did built .aar successfully and added to the libs of my project, but when I call "Ffmpeg.isAvailable" , I always get "false" as response, so I assume is not working.

My .aar has 13kb of size and I added eac3 to the decoders.

What should I do now ? I really need to use exoplayer I didn't want to switch.
Thanks.

**Comment by icbaker** [comment]
> but when I call "Ffmpeg.isAvailable" , I always get "false" as response, so I assume is not working.

This sounds like a problem with the way you're building or depending on the ffmpeg extension, rather than anything specific about eac3. Have you made sure to follow the full instructions for building the extension? https://github.com/google/ExoPlayer/blob/release-v2/extensions/ffmpeg/README.md

It's unlikely we can offer much detailed support with the specifics of your build setup I'm afraid.

**Comment by carrinhoff** [comment]
I did, i have placed Exoplayer locally and have imported every library I needed like this

`    implementation project(':exoplayer-library-core')
    implementation project(':exoplayer-extension-cast')
    implementation project(':exoplayer-library-hls')
    implementation project(':exoplayer-library-ui')`

After that i followed the guides, I have used ndk 21 , and now i have a FFMPEG folder inside Exoplayer/extesions/ffmpeg/src/main/jni...

And after that 
`        exoPlayer = SimpleExoPlayer.Builder(this,mRenderFactory).build()
            mRenderFactory.setExtensionRendererMode(DefaultRenderersFactory.EXTENSION_RENDERER_MODE_ON )
`

And I still have no sound , FFmpeg.isAvaible continues to give false but i'm 100% that I didnt skip any step from this guide 
https://github.com/google/ExoPlayer/blob/release-v2/extensions/ffmpeg/README.md

**Comment by carrinhoff** [comment]
If I try to do this step -> `./gradlew extension-ffmpeg:assembleRelease`  that i found on another tutorial, i go the follow error


`
> Task :extension-ffmpeg:buildCMakeRelWithDebInfo[arm64-v8a] FAILED
C/C++: ninja: error: 'C:/Users/Fabio/ExoPlayer/extensions/ffmpeg/src/main/jni/ffmpeg/android-libs/arm64-v8a/libswresample.a', needed by 'C:/Users/Fabio/ExoPlayer/extensions/ffmpeg/buildout/intermediates/cxx/RelWithDebInfo/6p3re6p1
/obj/arm64-v8a/libffmpegJNI.so', missing and no known rule to make it

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':extension-ffmpeg:buildCMakeRelWithDebInfo[arm64-v8a]'.
> Build command failed.
  Error while executing process C:\Users\Fabio\AppData\Local\Android\Sdk\cmake\3.22.1\bin\ninja.exe with arguments {-C C:\Users\Fabio\ExoPlayer\extensions\ffmpeg\.cxx\RelWithDebInfo\6p3re6p1\arm64-v8a ffmpegJNI}
  ninja: Entering directory `C:\Users\Fabio\ExoPlayer\extensions\ffmpeg\.cxx\RelWithDebInfo\6p3re6p1\arm64-v8a'

  ninja: error: 'C:/Users/Fabio/ExoPlayer/extensions/ffmpeg/src/main/jni/ffmpeg/android-libs/arm64-v8a/libswresample.a', needed by 'C:/Users/Fabio/ExoPlayer/extensions/ffmpeg/buildout/intermediates/cxx/RelWithDebInfo/6p3re6p1/obj/
arm64-v8a/libffmpegJNI.so', missing and no known rule to make it


* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 12s
2 actionable tasks: 2 executed
`

**Comment by carrinhoff** [comment]
**Found the problem** 

It's impossible to do this correctly:

`cd "${FFMPEG_MODULE_PATH}/jni" && \
./build_ffmpeg.sh \
  "${FFMPEG_MODULE_PATH}" "${NDK_PATH}" "${HOST_PLATFORM}" "${ENABLED_DECODERS[@]}"`

because we get the following error : 

`/android-ndk-r21e/toolchains/llvm/prebuilt/windows-x86_64/bin/x86_64-linux-android21-pkg-config not found, library detection may fail.
`

There isn't any pkg-config inside NDK , how this should even work ?

**Comment by carrinhoff** [comment]
So I found the solution and I will post here to help anothers with the same problem.
The exoplayer guide : https://github.com/google/ExoPlayer/blob/release-v2/extensions/ffmpeg/README.md 
is incomplete for windows.

Inside build_ffmpeg.sh we have a command called "make" (used in linux) but windows doesn't know it , so you have to install chocolatey on power shell , and then "choco install make", after that you need to close all terminals and open again and from that you follow those exoplayer guidelines and everything should work fine.

To test if everything is ok you must receive true from calling "Ffmpeg.isAvailable" inside your project.
Now i have sound on my videos.

Btw, exoplayer team please update the documentation with this step.

**Comment by icbaker** [comment]
Glad you got it resolved!

> Btw, exoplayer team please update the documentation with this step.

The instructions currently make clear they're not tested on Windows. I will take a look at adding `set -e` to the `build_ffmpeg.sh` script so that any errors cause it to exit immediately - I think that should make it exit when it can't find the `make` command, and the resulting error should be fairly clear (that you need to install `make`). We don't have an opnion on where people install `make` from, so I don't think it would be appropriate to explicitly document that people use chocolatey to achieve this.

I'm going to close this since the question has been solved.
