### ISSUE TITLE
Playing video from byte array through AVPro

### ISSUE THREAD

**Issue by Gurwar** [google/ExoPlayer#10795]
Complete noobie to Exoplayer here.

I am working on a project that is using AV Pro in Unity. AV Pro is a multiplatform video player that is using the ExoPlayer library for Android video playback. 

The feature I want to develop is for video encryption. I don't want to have to save a decrypted file to the device before being able to playback. Instead I want to use the decrypted bytes of the video and allow the user to watch the video without having to save to device. For some reason AVPro does not currently support this feature. 

Is there a way to compile ExoPlayer to provide us access to this feature. I am also doing research on the AVPro github and will surely post my findings here.

Where can I start looking?

**Comment by christosts** [comment]
ExoPlayer loads data through `DataSource` components. There are various `DataSource` implementations that know how to read data from local files to remote HTTP endpoints. Your starting point is probably the `ByteArrayDataSource` that reads data directly from a byte array. To specify what `DataSource` to use, you'll need to pass a `DataSource.Factory` You can also read similar discussion on #9558.
