### ISSUE TITLE
How to load HD video from server in 360p or 144p quality in app

### ISSUE THREAD

**Issue by cstar-99** [google/ExoPlayer#10801]
I am working on a project where I load videos from a server, but the videos on my server are HD quality. So, how can I load this HD video in the low-quality video to save internet data? I tried trackselector.setparameter but it didn't change, videos are still loading in high quality.

**Comment by shubhamvashisht** [comment]
@cstar-99 To achieve this, you need to look into Adaptive bitrate streaming. Exo player provides built-in support for HLS, DASH etc. In simpler words, You need to have your media in multiple bitrates/resolution to achieve something like this.

**Comment by christosts** [comment]
As mentioned, you need to package and serve video content in a format that supports [Adaptive Bitrate Streaming](https://en.wikipedia.org/wiki/Adaptive_bitrate_streaming), which  ExoPlayer supports. You can find information the [Supported formats](https://exoplayer.dev/supported-formats.html) page, and specifically support for [DASH](https://exoplayer.dev/dash.html), [HLS](https://exoplayer.dev/hls.html), or [SmoothStreaming](https://exoplayer.dev/smoothstreaming.html). There is a plethora of tools how to convert individual video files to an adaptive format, but this is beyond the support we can offer.
