### ISSUE TITLE
Is there a way to update the subtitle in exo?

### ISSUE THREAD

**Issue by Lilsax** [google/ExoPlayer#10802]
is there a way to update the subtitle in exo player? Since im working with multi period manifest and the subtitle always come inside the 2nd period since the first period is an ad period 

and as i can see exo player tries to read the subtitle from the first period and in case it didnt find it, it will consider there is no subtitle or sub audio.

is there anything u can help me with this ??

regards

**Comment by icbaker** [comment]
Please can you provide complete reproduction steps so we can understand your exact setup and see how the player handles it.

Without that it's going to be very hard to understand your problem.

Please either post media links here or send them dev.exoplayer@gmail.com using the subject `Issue #10802`. Please also update this issue to indicate you’ve done this.

Thanks!

**Comment by Lilsax** [comment]
this is a question not a problem

im asking if there is a way to update the subtitle and manifest during the stream

**Comment by icbaker** [comment]
If you're asking about subtitles configured within a standard streaming protocol (e.g. DASH / HLS) (it's unclear from the minimal information provided so far) then your question is probably better targeted at the authors/maintainers of that spec - since any way to update the stream during playback will be defined in that spec, it wouldn't make sense for ExoPlayer to implement a custom solution for this.

If you are reporting that ExoPlayer doesn't implement a part of one of these specs then please provide more details (e.g. spec section, exact wording, example manifest, report of ExoPlayer's behaviour).

If your question is about some other way of providing subtitles to ExoPlayer then please provide enough information for me to understand how you're configuring this.

**Comment by Lilsax** [comment]
Hello @icbaker,

I apologize for not providing full information for this. Let me give you the full view of what I am dealing with right now.

So basically, for the dash single period manifest, everything including the subtitle is working fine. But in the case of having a multi-period dash manifest, the player will go and check the first period inside the manifest and check if it has sub audios or subtitles. In the case the first one doesn't have any, it will just skip the retrieving of subtitles and sub audios part and consider doesn't have any.

What I want to do is that I want the player to go and check all the periods inside the manifest and look for all the possible available subtitles and sub audios. This is because when dealing with SSAI, the first period is always an ad, and the subtitles and sub audios are inside the 2nd period or the 3rd, depending on how many pre-rolls I have.

**Comment by icbaker** [comment]
Thanks for the extra information - it sounds like you're reporting a problem in the way ExoPlayer handles DASH multi-period streams where subtitles are only present in periods after the first one. Please can you provide an example manifest that demonstrates the problem that we can use to reproduce it and understand exactly how the player is behaving.

----

> What I want to do is that I want the player to go and check all the periods inside the manifest and look for all the possible available subtitles and sub audios. This is because when dealing with SSAI, the first period is always an ad, and the subtitles and sub audios are inside the 2nd period or the 3rd, depending on how many pre-rolls I have.

This is unlikely to be the approach we take - it's much more likely that we will ensure the subtitles are read **when playing the period they're present in**. This means we don't need to read significantly ahead of the playback position.

**Comment by Lilsax** [comment]
Hello again,

I was investigating the player and discovered that it returns the subtitle and subaudio information every time it reads a new period. Therefore, my previous assumption was incorrect. I apologize for the mistake.

Thank you for your help.
