### ISSUE TITLE
Exoplayer not playing catch up and timeshift

### ISSUE THREAD

**Issue by randeeppr** [google/ExoPlayer#1080]
Hi,

When we pass a normal mpd URL exoplayer is playing it correctly but when we send some parameters with URL such as start time and endtime for catch up and timeshift, exoplayer strips the parameters and play live video.

This is how we pass the URL. Is this right?

sourceUrl = base + "/dash/" + chname + "/manifest.mpd?starttime="+StartTime+"&stoptime="+CurrentTime

                 player = new LukupPlayer(new DashRendererBuilder(userAgent,sourceUrl,"",
                new WidevineTestMediaDrmCallback(""), null)); 
                if(Constant.DEBUG)  Log.i("ModularDRM", sourceUrl);
                player.addListener(this);
                player.prepare();
                if(Constant.DEBUG)  Log.i("ModularDRM", "PreparePlayer ");
                player.setSurface(surfaceView.getHolder().getSurface());
                player.setPlayWhenReady(true);

Please advise.
Regards,
Randeep

**Comment by ojw28** [comment]
Are the parameters actually part of the DASH specification, or a specification of some kind? If not, it's unclear why you expect ExoPlayer to recognize them?

**Comment by randeeppr** [comment]
@ojw28 

I'm not sure about the dash specification. This is the format given by our encoder (Envivio). It is working in other dash players such as shaka player.

The url actually looks like this. May be my question was confusing.

Live url is this.
http://xyz.domain.com/dash/aljazeera/manifest.mpd
Its playing fine.

Catch up url is as below:
its not playing. Exoplayer is playing the live even if we pass these parameters.
http://xyz.domain.com/dash/aljazeera/manifest.mpd?starttime=1444905456000&stoptime=1444905636000

Starttime an stoptime are unixtimestamps in milliseconds.

How can we solve this. Because the we are using exoplayer in our STB to play dash streams encrypted with widevine modular DRM. 

Regards,
Randeep

**Comment by ojw28** [comment]
Thinking about this some more, most likely the query parameters cause the server to provide a different manifest as the response, in which case ExoPlayer wouldn't need to do anything special to handle them and they wouldn't need to be part of a standard.

I'm not really sure if you're constructing the URL correctly, but it's more common to use `UriBuilder` and methods like `UriBuilder.queryParam`, as opposed to just concatenating strings together, to ensure that it gets escaped correctly.

**Comment by randeeppr** [comment]
@ojw28 this is the reply from Envivio.

"This is out of the scope of the DASH spec. This is standard HTTP URL with a query string. Player should forward that to the server as-is."

Yes. As you mentioned it will give a different manifest url according to the query parameters.

Till now no luck. :(

**Comment by randeeppr** [comment]
@ojw28

Also is there any way to check the URL is reaching  exoplayer with query parameters?

**Comment by ojw28** [comment]
A sample stream would be useful. Please send a link to `dev.exoplayer@gmail.com`.

**Comment by randeeppr** [comment]
hi @ojw28 

I have sent a sample stream to you.

**Comment by ojw28** [comment]
I tried adding samples to the ExoPlayer demo app's `Samples.java` with and without the starttime and stoptime parameters. Without them I got a live stream. With them I got the requested window, so everything seems to work correctly as far as I can tell.

This was using the current dev branch, although I'm pretty sure you'd see the same correct behavior with the current master branch too (1.5.3). Are you using an older version? If so, please update. If you can reproduce the issue within the demo app using 1.5.3 or the dev branch, please let us know.
