### ISSUE TITLE
Not able to play .MPD file using exo player

### ISSUE THREAD

**Issue by joshimaulik** [google/ExoPlayer#1081]
Hello,

I want to play .MPD file using exo player. I have created a new .mpd file using mp4box utility and try to play that mpd file. To do that I have changed in samples.java file in exo player demo and replace this URL:

new Sample("Google Play",
        "http://www.youtube.com/api/manifest/dash/id/3aa39fa2cc27967f/source/youtube?"
        + "as=fmp4_audio_clear,fmp4_sd_hd_clear&sparams=ip,ipbits,expire,source,id,as&ip=0.0.0.0&"
        + "ipbits=0&expire=19000000000&signature=A2716F75795F5D2AF0E88962FFCD10DB79384F29."
        + "84308FF04844498CE6FBCE4731507882B8307798&key=ik0", PlayerActivity.TYPE_DASH),

with the one I created, e.g. http://10.24.8.8/testfile.mpd

When I tried to play it using exo player, nothing happens and it's not playing. 

Let me know if I am doing something wrong to play .mpd file.

Thank You

**Comment by ojw28** [comment]
There is insufficient information to allow us to debug the issue. We'd probably need a link to the problematic content to tell you what's going wrong.

**Comment by joshimaulik** [comment]
This is my mpd file:

<?xml version="1.0"?>

<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" minBufferTime="PT1.500S" type="static" mediaPresentationDuration="PT0H0M36.917S" maxSegmentDuration="PT0H0M29.250S" profiles="urn:mpeg:dash:profile:isoff-on-demand:2011">
 <ProgramInformation moreInformationURL="http://gpac.sourceforge.net">
  <Title>c:\Mp4Box\sample1.mpd generated by GPAC</Title>
 </ProgramInformation>

 <Period duration="PT0H0M36.917S">
  <AdaptationSet segmentAlignment="true" maxWidth="320" maxHeight="180" maxFrameRate="24" par="16:9" lang="und" subsegmentAlignment="true" subsegmentStartsWithSAP="1">
   <ContentComponent id="1" contentType="audio" />
   <ContentComponent id="2" contentType="video" />
   <Representation id="1" mimeType="video/mp4" codecs="mp4a.40.2,mp4v.20.3,mp4s.02,mp4s.01" width="320" height="180" frameRate="24" sar="1:1" audioSamplingRate="32000" startWithSAP="1" bandwidth="431760">
    <AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2"/>
    <BaseURL>c:/Mp4Box/seg_sample1init.mp4</BaseURL>
    <SegmentBase indexRangeExact="true" indexRange="2141-2196">
      <Initialization range="0-2140"/>
    </SegmentBase>
   </Representation>
  </AdaptationSet>
 </Period>
</MPD>

I am configuring this mpd file in localhost and giving it's URL in application. Let me know what other information you required

**Comment by ojw28** [comment]
The first thing that's apparent is that the manifest appears to declare muxed media (audio and video combined in a single stream). ExoPlayer only supports demuxed media where the audio and video are provided as separate streams in their own adaptation sets.

It's also unclear what your use case is. Given your manifest only defines a single representation, why are you using DASH in the first place as opposed to just using a (non-fragmented) mp4?

**Comment by joshimaulik** [comment]
Actually I want to set up a test environment for dash streaming and Exo player. What I thought was, I'll generate a mpd file using mp4box utility, host it on a local web server and try to play it using Exo player.

Now as per your post, Exo player supports only demux media, so could you please let me know how can I achieve my purpose and set up test environment for dash streaming?

Sent from my iPhone

On Dec 22, 2015, at 5:10 PM, ojw28 <notifications@github.com<mailto:notifications@github.com>> wrote:


The first thing that's apparent is that the manifest appears to declare muxed media (audio and video combined in a single stream). ExoPlayer only supports demuxed media where the audio and video are provided as separate streams in their own adaptation sets.

It's also unclear what your use case is. Given your manifest only defines a single representation, why are you using DASH in the first place as opposed to just using a (non-fragmented) mp4?

-
Reply to this email directly or view it on GitHub<https://github.com/google/ExoPlayer/issues/1081#issuecomment-166772107>.

************************************************************************************************************************************************************* eInfochips Business Disclaimer: This e-mail message and all attachments transmitted with it are intended solely for the use of the addressee and may contain legally privileged and confidential information. If the reader of this message is not the intended recipient, or an employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution, copying, or other use of this message or its attachments is strictly prohibited. If you have received this message in error, please notify the sender immediately by replying to this message and please delete it from your computer. Any views expressed in this message are those of the individual sender unless otherwise stated. Company has taken enough precautions to prevent the spread of viruses. However the company accepts no liability for any damage caused by any virus transmitted by this email. *************************************************************************************************************************************************************

**Comment by joshimaulik** [comment]
As per your comments, i have generated new mpd file with different AdaptationSet for audio and video but still i am not able to play it in exo player. Attached is my new mpd file for your reference.
[sample.txt](https://github.com/google/ExoPlayer/files/71083/sample.txt)

**Comment by ojw28** [comment]
The new mpd looks more in line with what ExoPlayer is expecting. Just saying it doesn't work isn't sufficient information to help debug the issue, however, especially given you haven't provided access to the actual media (only the manifest has been attached) or a bug report or log output. It sounds very much like a setup issue with your test content.

Please provide full information as specified [here](https://google.github.io/ExoPlayer/2015/10/01/reporting-issues.html) including a full bug report and a publicly accessible link to the media in a playable form. Ideally you will also have verified that your media plays correctly with some other player, such as [shaka](https://shaka-player-demo.appspot.com/).

**Comment by joshimaulik** [comment]
Ok, I will email you the mp4 file which I am using to dash stream. If you can generate me mpd file which i can play on Exo player, I will test it in my setup environment and let you know the result. FYI, I am using Exo player version which is supported by android-22. ExoPlayer-r1.5.0

**Comment by joshimaulik** [comment]
Attached is the .mp4 file which I am using.


________________________________

**Comment by ojw28** [comment]
We really don't have time to be providing consulting services; sorry. It's up to you to generate your own test content. If you can verify that your test content works correctly in some other player (i.e. that it's an ExoPlayer specific issue) or provide more detailed information as described [here](https://google.github.io/ExoPlayer/2015/10/01/reporting-issues.html) then we can take a look. Otherwise it's up to you to resolve the issue.

**Comment by joshimaulik** [comment]
Okay, thanks for your help.I will look into this on my own..
