### ISSUE TITLE
Typo in r2.18.2 release notes

### ISSUE THREAD

**Issue by neutric** [google/ExoPlayer#10811]
> Rename com.google.android.exoplayer2.audio.AudioProcessor to com.google.android.exoplayer2.audio.AudioProcessor.

Both source and target of the rename are identical.

**Comment by christosts** [comment]
Thanks for spotting this. This is an unfortunate miss, a result of publishing ExoPlayer in two different repositories.

For context, in [androidx/media3 ](https://github.com/androidx/media), the code is under `androidx.media3` and we have some automation in place to translate the code to the `com.google.android.exoplayer2` when publishing on this repository. The file did get moved in the [androidx/media3 ](https://github.com/androidx/media) project.
