### ISSUE TITLE
Clear Key with key rotation on DASH live service

### ISSUE THREAD

**Issue by echoy-harmonicinc** [google/ExoPlayer#10822]
I would like to know whether DASH clear key with key rotation is supported on ExoPlayer?

I have the manifest like below (removed unnecessary info for better readability):
Clear key is defined as per DASH-IF IOP-6 V5.0.0 clause 8 (with UUID `e2719d58-a985-
b3c9-781a-b030af78d30e`)
```
<?xml version="1.0" encoding="UTF-8" ?>
<MPD profiles="urn:mpeg:dash:profile:isoff-live:2011,http://www.dashif.org/guidelines/low-latency-live-v5" type="dynamic" availabilityStartTime="2011-03-01T00:00:00Z" minimumUpdatePeriod="PT4.0S" minBufferTime="PT0.1S" publishTime="2022-11-30T03:05:17.285Z" timeShiftBufferDepth="PT10M" xmlns="urn:mpeg:dash:schema:mpd:2011" xmlns:cenc="urn:mpeg:cenc:2013" xmlns:mspr="urn:microsoft:playready" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:mpeg:dash:schema:mpd:2011 DASH-MPD.xsd">
	<Period start="PT0S" id="1">
		<AdaptationSet mimeType="video/mp4" startWithSAP="1" segmentAlignment="true" par="16:9">
			<ContentProtection schemeIdUri="urn:mpeg:dash:mp4protection:2011" value="cenc" cenc:default_KID="d8fa10d5-1e55-366d-a8f3-fe564e20ed97"></ContentProtection>
			<ContentProtection schemeIdUri="urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed"></ContentProtection>
			<ContentProtection schemeIdUri="urn:uuid:e2719d58-a985-b3c9-781a-b030af78d30e"><clearkey:Laurl xmlns:clearkey="http://dashif.org/guidelines/clearKey" Lic_type="EME-1.0">https://<LicenseServer>/AcquireLicense</clearkey:Laurl></ContentProtection>
		</AdaptationSet>
	</Period>
</MPD>
```
(Ignore mixing DRM systems in single mpd. It's for dev purpose only)

I have also the init segment and segments PSSH box. It is constructed as per W3C "cenc" Initialization Data Format clause 4 (with UUID `1077efec-c0b2-4d02-ace3-3c1e52e2fb4b`)
```PSSH box: 0000003470737368010000001077efecc0b24d02ace33c1e52e2fb4b00000001b42128a2537d3ff2948c212d4020089900000000```

The license server complies with W3C EME spec clause 9

media.exolist.json
```
{
  "name": "<name>",
  "uri": "<url>",
  "drm_scheme": "clearkey",
  "drm_multi_session": true
}
```

However ExoPlayer refuses to use the KID from the box. It uses the default KID instead. That makes the service unplayable.

If I make the following changes in FrameworkMediaDrm to merge two DRM systems (Clear key & Common PSSH):
``` 
private static SchemeData getSchemeData(UUID uuid, List<SchemeData> schemeDatas) {
  if (C.CLEARKEY_UUID.equals(uuid)) {
    SchemeData clearKey = null;
    SchemeData commonPssh = null;
    for (SchemeData data : schemeDatas) {
      if (C.CLEARKEY_UUID.equals(data.uuid)) {
        clearKey = data;
      } else if (C.COMMON_PSSH_UUID.equals(data.uuid)) {
        commonPssh = data;
      }
    }
    if (clearKey != null && commonPssh != null) {
      return clearKey.copyWithData(commonPssh.data);
    }
  }
  if (!C.WIDEVINE_UUID.equals(uuid)) {
    // For non-Widevine CDMs always use the first scheme data.
    return schemeDatas.get(0);
  }
  ...
}
```
It plays just fine. 

I'm not sure if that's a bug, not yet supported in ExoPlayer, or I misconfigured it. Please advise.

**Comment by icbaker** [comment]
Please provide a stream we can play to reproduce the problem you're seeing.

Please either post a link here or send it to [dev.exoplayer@gmail.com](mailto:dev.exoplayer@gmail.com) using the subject `Issue #10822`. Please also update this issue to indicate you’ve done this.

**Comment by echoy-harmonicinc** [comment]
@icbaker email sent

**Comment by icbaker** [comment]
Thanks, I'm able to reproduce that the provided content doesn't play on an unmodified demo app, and with the suggested modification to `FrameworkMediaDrm` it plays.

Clause 9.3 of [DASH IOP Part6 v5.0.0](https://dashif.org/docs/IOP-Guidelines/DASH-IF-IOP-Part6-v5.0.0.pdf) says about key rotation (emphasis mine):
> For supporting this mechanism:
> * The MPD has no `default_KID` attribute in the `ContentProtection` element defined at the `AdaptationSet` level and it **has no `ContentProtection` child elements such as `PSSH` elements**.

The manifest you quoted above, and the one you provided a link to, both have a `clearkey:Laurl` child element inside the `<ContentProtection schemeIdUri="urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed">` element.

What happens if you remove that child element? I think (untested) it will change the list of `SchemeData` passed to the `FrameworkMediaDrm.getSchemeData` method you modified - because `hasData()` will return `false` here for the `SchemeData` derived from the clearkey info in the manifest:
https://github.com/google/ExoPlayer/blob/0c74758f0e6d5acff523182ac93ac7b91324498d/library/common/src/main/java/com/google/android/exoplayer2/drm/DrmInitData.java#L62-L65

**Comment by echoy-harmonicinc** [comment]
Dropped both `clearkey:Laurl` and `default_KID` (by commenting out related sections in DashManifestParser). Now the demo player plays fine.
So to make clear key & in-band key rotation to work, `LaUrl` is not supported and must be removed?

**Comment by icbaker** [comment]
> So to make clear key & in-band key rotation to work, `LaUrl` is not supported and must be removed?

Yes, because it's not supposed to be there as described by the DASH IOP guidance linked above.
