### ISSUE TITLE
Unseekable webm audio produced by Google Chrome

### ISSUE THREAD

**Issue by or-else** [google/ExoPlayer#10824]
ExoPlayer 2.18.1

There is a [well-known bug](https://bugs.chromium.org/p/chromium/issues/detail?id=642012) in Chrome (which Google acknowledges but refuses to fix) causing Chrome to produce webm audio with no SeekHead and no duration. A sample is attached.

```
% mkvalidator --details ~/Downloads/elevator-music.webm 
WRN801: The segment has no SeekHead section
mkvalidator 0.6.0: the file appears to be valid
Track #1             A_OPUS 24493 bits/s
	file "/Users/gene/Downloads/elevator-music.webm"
	created with Chrome / Chrome
```

When I seek the media, ExoPlayer changes state to `BUFFERING` first, `getCurrentPosition` returns the correct value. Then state changes to `READY` and `getCurrentPosition` returns 0. I.e. every time I seek it, it resets to the beginning. 

Using `setConstantBitrateSeekingEnabled(true)` does not appear to have any effect:
```java
new DefaultMediaSourceFactory(mActivity, new DefaultExtractorsFactory().setConstantBitrateSeekingEnabled(true))
                        .setDataSourceFactory(dataSourceFactory)
                        .createMediaSource(new MediaItem.Builder().setUri(uri).build());
```

Is there *any* way to make this media seekable by ExoPlayer on Android? I would be fine even if seeking is imprecise by a couple of seconds. The duration of the record is known, size in bytes too. It should be possible to seek to the approximately correct position with the assumption of the constant bit rate. I suspect VLC does just that because it can seek this media. Chrome can seek it too.

Would it help to transform the media to another format? If yes, how?

Thanks!

[elevator-music.webm](https://user-images.githubusercontent.com/5938143/204952925-039b317d-f8ca-42b6-a0de-7c5d2ee17e87.webm)

**Comment by or-else** [comment]
BTW, the antique `android.media.MediaPlayer` can seek these records.

**Comment by briantbutton** [comment]
I am confounded that, in Chrome, MediaSource supports one audio mimetype.  MediaRecorder also supports one mimetype.

But they are different!  So, I cannot take something from MediaRecorder and put it into a MediaSource directly.

Having trouble seeing how this could be . . .
<img width="325" alt="Screen Shot 2023-04-15 at 10 54 36 AM" src="https://user-images.githubusercontent.com/16803497/232245615-d76a8d8a-a79d-4f35-855b-5a8730c79803.png">

**Comment by or-else** [comment]
Even better: Chrome on iPhone cannot play a recording made by Chrome on a Mac.

**Comment by icbaker** [comment]
> Using `setConstantBitrateSeekingEnabled(true)` does not appear to have any effect:

ExoPlayer's `MatroskaExtractor` (which handles webm files) does not support constant bitrate seeking, so `DefaultExtractorsFactory` does not propagate that option and therefore it's expected not to have any effect in this case:
https://github.com/google/ExoPlayer/blob/67991cb91f237025d378182aecfcce4ce5c11264/library/extractor/src/main/java/com/google/android/exoplayer2/extractor/DefaultExtractorsFactory.java#L410-L423

The [webm spec](https://www.webmproject.org/docs/container/) lists the `SeekHead` as a SHOULD requirement: 
> WebM SHOULD contain the `SeekHead` element.

The same spec also makes it clear that seeking will be disabled if the file doesn't contain `Cues` element:
> Seeking will be disabled if the webm file does not have a key frame `Cues` element.

The file provided does not have a `Cues` element, this command returns no results:

```
$ mkvinfo --all --positions file.webm | grep -i cue
```

It looks like ExoPlayer is following the WebM demuxing spec here. If you have feedback about the behaviour of Chrome I suggest you provide that to them directly, it's not really on topic for this issue tracker.

**Comment by or-else** [comment]
> The [webm spec](https://www.webmproject.org/docs/container/) lists the SeekHead as a SHOULD requirement

That's exactly what Google said with respect to this bug in Chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=642012

To summarize: Google Chrome produces spec-compliant but effectively broken recordings. Google ExoPlayer unable to handle them but all is fine because it's spec compliant. Google is being Google. Did not expect anything else.
