### ISSUE TITLE
Cannot not play live stream

### ISSUE THREAD

**Issue by lnmcc** [google/ExoPlayer#1082]
Exoplayer Cannot play this stream , I test some other app (vlc, mxplayer),  It's Ok.

what is the probrem? Thanks

http://tclive.cmvideo.cn:8088/envivo_x/SD/cctv12/711/index.m3u8?msisdn=301036169cad2c446ba256c3e8beb65d&mdspid=&spid=699004&netType=5&sid=2202208788&pid=2028594089&timestamp=20151222093148&Channel_ID=0109_04090200-99000-200900000050000&ProgramID=603253026&ParentNodeID=10302057&client_ip=58.210.8.30&assertID=2202208788&encrypt=585b76ec9551e5a41e1b683ac15f19d9

**Comment by ojw28** [comment]
The link doesn't work for me (in VLC, safari, just using wget etc). I think it's either dead or geo-restricted. Please can you provide a working link? Thanks!

**Comment by lnmcc** [comment]
Sorry this strea is outdate.
