### ISSUE TITLE
dash webvtt subtitles don't show if subtitles in several chunks

### ISSUE THREAD

**Issue by sergju** [google/ExoPlayer#10823]
Hi
We have issue - dash webvtt subtitles don't show if subtitles in several chunks.
I understood ExoPlayer add chunk start time to time in vtt file.
If in chunk time is
00:01.000 --> 00:03.000
Chunk start time 30s for example, so render time we have 30s+1s = 31s
How to make to work proper?
It is all ok in hls.
Look like with dash field subsampleOffsetUs left OFFSET_SAMPLE_RELATIVE and I don't understand how make it correct

**Comment by icbaker** [comment]
Please provide a stream we can play to reproduce the problem you're seeing.

Please either post a link here or send it to dev.exoplayer@gmail.com using the subject `Issue #10823`. Please also update this issue to indicate you’ve done this.

**Comment by CWftw** [comment]
Hi, sent an email with subject Issue #10823 with an example manifest with this issue.

**Comment by sergju** [comment]
Hi, I sent email with manifest and vtt chunks

**Comment by icbaker** [comment]
Thanks for the manifest. When using DASH with stand-alone subtitles (i.e. not inside an MP4 container), the text files must not be segmented (i.e. there must be a single text file per-representation, per-period). From [DASH IOP section 5.2.10](https://dashif-documents.azurewebsites.net/DASH-IF-IOP/master/DASH-IF-IOP.html#standalone-text-timing) (emphasis mine):

> Some services store text adaptation sets in stand-alone IMSC1 or WebVTT files, without **segmentation** or [ISOBMFF] encapsulation.

That's why this isn't working.

**Comment by zevlg** [comment]
What about dynamic (LIVE) content, where there is no standalone subtitles file and subtitles has their own timeline and segmentation?

**Comment by icbaker** [comment]
@zevlg I would suggest asking that question of the DASH spec/IOP authors. I would guess that the recommendation will be to use segmented TTML subtitles, encapsulated in MP4 containers - since that's how DASH supports segmented subtitles as far as I understand it.
