### ISSUE TITLE
how to get the every frame of video when scrub move?

### ISSUE THREAD

**Issue by 515459445** [google/ExoPlayer#10821]
I want to preview the frame of position in the function onScrubMove(TimeBar timeBar, long position) of TimeBar.OnScrubListener,but i do not know how to realize it

**Comment by theBlbDan** [comment]
Refer to Issue  #3752

**Comment by rohitjoins** [comment]
Please provide complete information as requested in the question template. The template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/question.md).

Unfortunately we can't answer unclear questions or those with insufficient information.
