### ISSUE TITLE
About SoftFFmpegVideo

### ISSUE THREAD

**Issue by FongMi** [google/ExoPlayer#10827]
Since 2.17.0
Exo can't use SoftFFmpegVideo because allowChunklessPreparation is default true

Is there anyway to keep allowChunklessPreparation = true and use System SoftFFmpegVideo ?

Here is test link
http://113.62.253.10/live.aishang.ctlcdn.com/00000110240389_1/playlist.m3u8?CONTENTID=00000110240389_1&AUTHINFO=FABqh274XDn8fkurD5614t%2B1RvYajgx%2Ba3PxUJe1SMO4OjrtFitM6ZQbSJEFffaD35hOAhZdTXOrK0W8QvBRom%2BXaXZYzB%2FQfYjeYzGgKhP%2Fdo%2BXpr4quVxlkA%2BubKvbU1XwJFRgrbX%2BnTs60JauQUrav8kLj%2FPH8LxkDFpzvkq75UfeY%2FVNDZygRZLw4j%2BXtwhj%2FIuXf1hJAU0X%2BheT7g%3D%3D&USERTOKEN=eHKuwve%2F35NVIR5qsO5XsuB0O2BhR0KR

**Comment by rohitjoins** [comment]
I tried playing the media link in our demo app and was able to play it successfully. Please provide complete information as requested in the question template. The template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/question.md).

Unfortunately we can't answer unclear questions or those with insufficient information.

**Comment by FongMi** [comment]
Yes, This url can play, but only audio, can't see video.
Exoplayer 2.18.2

**Comment by rohitjoins** [comment]
Yeah correct. I modified the value for `allowChunklessPreparation` to false and could also see the video, although a bit laggy. We have this public api which can be used to change the default behaviour [here](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/source/hls/HlsMediaSource.Factory.html#setAllowChunklessPreparation(boolean))
