### ISSUE TITLE
Can I override ExoPlayer's Notification action buttons?

### ISSUE THREAD

**Issue by dimitradg** [google/ExoPlayer#10839]
I would like to override notification's action buttons in order to track some analytics.

For example, when user plays or pauses an audio track via the notification, I would like to put some logs and save some information on my application's database.

Is this possible?

I am currently using 2.14.2 ExoPlayer version.

Thank you in advance

**Comment by marcbaechinger** [comment]
I assume you are using `PlayerNotificationManager`. 

You can do  a `ForwardingPlayer` that you pass to the notification manager:

```
playerNotificationManager.setPlayer(new MyTrackingForwardingPlayer(player));
```

Then, in your `MyTrackingForwardingPlayer` you can override every method, intercept the call, trigger writing data to analytics/database (probably async) and finally delegate to the wrapped player.
