### ISSUE TITLE
Upgrade to version 2.18.2

### ISSUE THREAD

**Issue by rajeshgetyoteam** [google/ExoPlayer#10833]
ExoPlayer  : Version 2.18.2

Android Version : Android 12

Bug 

Duplicate class com.google.common.primitives.UnsignedBytes found in modules jetified-guava-31.0.1-android (com.google.guava:guava:31.0.1-android) and jetified-guava-primitives-r03 (com.google.guava:guava-primitives:r03)
Duplicate class com.google.common.primitives.package-info found in modules jetified-guava-31.0.1-android (com.google.guava:guava:31.0.1-android) and jetified-guava-primitives-r03 (com.google.guava:guava-primitives:r03)

**Comment by icbaker** [comment]
Hi! Please provide complete information as requested in the issue template (in particular the repro steps are missing). The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md).
