### ISSUE TITLE
Exoplayer is using 3.28.1 version from IMA which has crash.

### ISSUE THREAD

**Issue by dev-sharma-deltatre** [google/ExoPlayer#10845]
Exoplayer is using 3.28.1 version from IMA.
https://developers.google.com/interactive-media-ads/docs/sdks/android/client-side/history

Please refer to the document above. 
This version has issues with crashes on Android v27 and lower.

Can we please upgrade that?

**Comment by marcbaechinger** [comment]
Thanks for your report. We will bump the version to 3.29.0.

**Comment by dev-sharma-deltatre** [comment]
Can you help me know when can I expect a new release?

**Comment by dev-sharma-deltatre** [comment]
@marcbaechinger  Can you please update?

**Comment by marcbaechinger** [comment]
I don't know, I'm afraid.

**Comment by dev-sharma-deltatre** [comment]
@marcbaechinger Hello, It is February, I just wanted to remind you about the release for this fix as the IMA SDK version used in 2.18.2 is going to be deprecated soon. Eagerly waiting for the release.

**Comment by marcbaechinger** [comment]
Thank you! Really appreciate your help!

**Comment by icbaker** [comment]
@dev-sharma-deltatre It looks like the version bump (https://github.com/google/ExoPlayer/commit/8ed515880a0b6c05b766e868e2ef931b886925cc) didn't require any ExoPlayer code changes, so if you want to use IMA 3.29.0 in your app you don't need to wait for a new ExoPlayer release, just ensure version 3.29.0 is used at runtime by e.g. putting this in your `build.gradle` file (you can remove it when you update to a version of ExoPlayer that depends directly on 3.29.0):

```gradle
implementation 'com.google.ads.interactivemedia.v3:interactivemedia:3.29.0'
```
