### ISSUE TITLE
Buffer run out time 

### ISSUE THREAD

**Issue by hafiz013** [google/ExoPlayer#10853]
Since i have experience buffer run out when do player.repeatMode = Player.REPEAT_MODE_ALL or looping it.

So to stop this issue, i try to use like this :
```
player.repeatMode = Player.REPEAT_MODE_OFF
```

and inside function onPlayerStateChanged
```
on Player.STATE_ENDED -> {
       player.seekTo(0)
       player.playWhenReady = true
}
```

so the question is that,  does function inherit from 
```
exoplayer2.analytics.AnalyticsListener.onTracksChanged(

        eventTime: AnalyticsListener.EventTime,
        trackGroups: TrackGroupArray,
        trackSelections: TrackSelectionArray
)  
```
will call again after do replay the movie?

Thanks, any good comment I really appreciated.

**Comment by marcbaechinger** [comment]
> i have experience buffer run out when do player.repeatMode = Player.REPEAT_MODE_ALL

Can you expand on this a bit, it sounds like a bug to me. What do you mean with `buffer run out`? Does the player fall into `STATE_BUFFERING` when the end of the last item in the playlist is reached? 

I just tried this out with a playlist of two video media items in the demo app and this works well. If you can repro this with the latest ExoPlayer version 2.18.2, it would be very nice if you could add an [`EventLogger`](https://exoplayer.dev/listening-to-player-events.html#using-eventlogger) to the player and then repro this case, take a bug report and upload it here or send it to 
dev.exoplayer@gmail.com.

Regarding your other question. There are various events that are emitted, when the player transitions from a media item to another (repeated or normal auto transition to the next item).  `onTracksChanged` works and you can also use `onMediaItemTransitioned` for being notified about this.
