### ISSUE TITLE
Media3 migration script is not updated to support 2.18.2

### ISSUE THREAD

**Issue by WilliamLindblom** [google/ExoPlayer#10854]
### ExoPlayer Version

2.18.2

### Devices that reproduce the issue

N/A

### Reproducible in the demo app?

Not tested

### Reproduction steps

1. Run command: ./media3-migration.sh -m /path/to/gradle/project/root
2. Command fails

### Expected result

Version 2.18.2 should be supported by the migration script.

### Actual result

$ ./media3-migration.sh -m .
=============================================
Validation errors (use -f to force execution)
---------------------------------------------
[1] -> The version does not match '2.18.1'. Update to '2.18.1' or use the migration script matching your current version. Current version '2.18.2' found in
    ./app/build.gradle

### Media

N/A

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by marcbaechinger** [comment]
Thanks for reporting. I got aware of this just today. We will provide a fix for this.

**Comment by marcbaechinger** [comment]
For  a quick fix you can try to change these two lines in the script:

```
MEDIA3_VERSION="1.0.0-beta02"
LEGACY_PEER_VERSION="2.18.1"
```

to 

```
MEDIA3_VERSION="1.0.0-beta03"
LEGACY_PEER_VERSION="2.18.2"
```

https://github.com/google/ExoPlayer/blob/release-v2/media3-migration.sh#L129

**Comment by marcbaechinger** [comment]
The mappings and the version number of the script are up to date now and cherry picked into the release branch. Sorry for the wait.
