### ISSUE TITLE
How do i know the app loss audio focus because another  music app is getting focus

### ISSUE THREAD

**Issue by XinChenTw** [google/ExoPlayer#10869]
I try to get the suppression reason by ` player.getPlaybackSuppressionReason()`  after another  music app is playing, but the result is always 0, But the result is 1, when phone calling is coming

**Exoplayer Version: 2.11.4**

**Comment by tonihei** [comment]
If the loss is permanent, you get a `onPlayWhenReadyChanged` event with `PLAY_WHEN_READY_CHANGE_REASON_AUDIO_FOCUS_LOSS`. Only transient, temporary audio focus losses are signalled via `getPlaybackSuppressionReason` because they keep the player state and automatically resume.

**Comment by tonihei** [comment]
Closing as the question was answered.
