### ISSUE TITLE
How create emulator profile with a decoder capability HEVC 4K

### ISSUE THREAD

**Issue by billyjoker** [google/ExoPlayer#10868]
I am trying to check if a not TV device is capable for playing 4K videos for type HEVC.

I do not have a phisic 4K device, instead I am creating a new one with the android emulator. I put the profile for 4K, I mean, 3840 x 2160.

I need specifically the capability for hevc 4K, so I have to check with my code if the devide can do it. 
The problem is that there is no profiles that matches wih that requirements. This is my code:

```
    private boolean check4kDeviceCapability() {
        MediaCodecInfo[] decoderInfos = new MediaCodecList(MediaCodecList.REGULAR_CODECS).getCodecInfos();
        for (MediaCodecInfo decoderInfo : decoderInfos) {
            if (!decoderInfo.isEncoder() && decoderInfo.getSupportedTypes() != null
                    && decoderInfo.getSupportedTypes().length > 0) {
                for (String supportedType : decoderInfo.getSupportedTypes()) {
                    if (supportedType.equals("video/hevc")) {
                        MediaCodecInfo.CodecCapabilities capabilities =
                                decoderInfo.getCapabilitiesForType(MediaFormat.MIMETYPE_VIDEO_HEVC);
                        if (capabilities.getVideoCapabilities().isSizeSupported(3840, 2160)) {
                            Timber.i("4K source would be supported with this device");
                            return true;
                        }
                    }
                }
            }
        }
        return false;
    }
```

**Comment by microkatz** [comment]
@billyjoker 
I was able to self-test with a 4K H264 stream we have in the demo and the Android TV 4K emulator was able to return true with isSizeSupported with the content. Does your code work if you try it with AVC?

**Comment by billyjoker** [comment]
With AVC returns true properly, the problem is with HEVC. There is no way to emulate Android Tv with HEVC decoder, it seems as if by default it gets created with AVC

**Comment by microkatz** [comment]
@billyjoker 
I was able to test with a sample H265 stream with the emulator. It was not 4K but it did show that the emulator comes with a decoder for HEVC.
Through your testing, does the codepath not enter your conditional of `if (supportedType.equals("video/hevc"))`? What do you mean that by default "it gets created with AVC"?

**Comment by billyjoker** [comment]
In my testings, never comes into the conditional `if (supportedType.equals("video/hevc"))`
 _What do you mean that by default "it gets created with AVC"?_
I mean that I am supposing that the AVD creates an emulator with that setup, able to decode AVC 4K but not HEVC 4K, because that conditional is never reached into

**Comment by microkatz** [comment]
It may be accurate that the emulator does not have a decoder that can support HEVC 4K, but it definitely has HEVC decoders as I have witnessed through my own testing. My emulator contains the software decoder called "c2.android.hevc.decoder" with mimetype "video/hevc". You can see in the picture below that my list has MediaCodecInfo with supportedTypes containing "video/hevc". Furthermore, I tested with hardcoding 3840, 2160 and isSizeSupported returned true. At the very least for you, it should at least enter the `if (supportedType.equals("video/hevc"))` conditional. 

![image](https://user-images.githubusercontent.com/45770613/210807255-77e27689-3f33-48f7-804d-5f78f3be4fc6.png)

Whats the Android version your emulator is based on?

I would perhaps file a bug report with https://developer.android.com/studio/report-bugs#emulator-bugs. It seems that its an issue with your emulator?

**Comment by billyjoker** [comment]
What API Level did you choose? I did it tests on API 31 and higher. Anyway, HEVC 4K is working with h265 format, not h264

**Comment by microkatz** [comment]
I was testing with API Level 33. HEVC is eqiuvalent to H265. AVC is equivalent to H264. You said you got it working with HEVC? Does this mean that your issue is addressed?

**Comment by billyjoker** [comment]
I got it using an external emulator, Genymotion, it was the only one that it created a profile with Android Tv HEVC 4K (h265). The Android Studio emulator could not create that profile, only h264

**Comment by microkatz** [comment]
In that case it appears that the library and your code appear to be working as expected? I will close the issue. You can file a bug with https://developer.android.com/studio/report-bugs#emulator-bugs for adding HEVC 4K support to their emulated decoders if you would like.
