### ISSUE TITLE
Not played .mpd and .m2u8 files fine. 

### ISSUE THREAD

**Issue by FranEspino** [google/ExoPlayer#10866]
### ExoPlayer Version

2.18.1

### Devices that reproduce the issue

The app was working fine with this code snippet however it stopped working a week ago and I don't have the error log. 

### Actual result

E/BufferQueueProducer: [SurfaceTexture-1-8305-2](id:207100000009,api:3,p:8305,c:8305) waitForFreeSlotThenRelock TIMED_OUT 0
E/BufferQueueProducer: BQDUMP- BufferQueue mMaxAcquiredBufferCount=1 mMaxDequeuedBufferCount=32
    BQDUMP  mDequeueBufferCannotBlock=0 mAsyncMode=0
    BQDUMP  mQueueBufferCanDrop=1 mLegacyBufferDrop=1
    BQDUMP  default-size=[1x1] default-format=1 BQDUMP  transform-hint=00 frame-counter=0
    BQDUMP  mTransformHintInUse=00 mAutoPrerotation=0
    BQDUMPFIFO(0):
    BQDUMP(mConsumerName=SurfaceTexture-1-8305-2, mConnectedApi=3, mConsumerUsageBits=256, mId=207100000009, producer=[8305:com.inkamedia.inkaplay], consumer=[8305:com.inkamedia.inkaplay])
    BQDUMPSlots:
    BQDUMP  [00:0xb40000715c408500] state=DEQUEUED 0xb40000715c438c00 frame=0 [ 640x 360: 640,32315659]
    BQDUMP  [01:0xb4000070a87b5800] state=DEQUEUED 0xb40000715c4ba980 frame=0 [ 640x 360: 640,32315659]
    BQDUMP  [02:0xb4000070a87b5900] state=DEQUEUED 0xb4000070cd51e200 frame=0 [ 640x 360: 640,32315659]
    BQDUMP  [03:0xb4000070a87b5a00] state=DEQUEUED 0xb4000070ea27c480 frame=0 [ 640x 360: 640,32315659]
    BQDUMP  [04:0xb4000070a87b5b00] state=DEQUEUED 0xb4000070ea27c600 frame=0 [ 640x 360: 640,32315659]
    BQ
E/BufferQueueProducer: Slots:
    BQDUMP  [00:0xb40000715c408500] state=DEQUEUED 0xb40000715c438c00 frame=0 [ 640x 360: 640,32315659]
    BQDUMP  [01:0xb4000070a87b5800] state=DEQUEUED 0xb40000715c4ba980 frame=0 [ 640x 360: 640,32315659]
    BQDUMP  [02:0xb4000070a87b5900] state=DEQUEUED 0xb4000070cd51e200 frame=0 [ 640x 360: 640,32315659]
    BQDUMP  [03:0xb4000070a87b5a00] state=DEQUEUED 0xb4000070ea27c480 frame=0 [ 640x 360: 640,32315659]
    BQDUMP  [04:0xb4000070a87b5b00] state=DEQUEUED 0xb4000070ea27c600 frame=0 [ 640x 360: 640,32315659]
    BQDUMP  [05:0xb400007061bc8300] state=DEQUEUED 0xb4000070ea27c780 frame=0 [ 640x 360: 640,32315659]
    BQDUMP  [06:0xb400007061bc8400] state=DEQUEUED 0xb4000070ea27c900 frame=0 [ 640x 360: 640,32315659]
    BQDUMP  [07:0xb400007061bc8500] state=DEQUEUED 0xb4000070ea055700 frame=0 [ 640x 360: 640,32315659]
    BQDUMP  [08:0xb400007061bc8600] state=DEQUEUED 0xb4000070ea055880 frame=0 [ 640x 360: 640,32315659]
    BQDUMP  [09:0xb400007061bc8700] state=DEQUEUED 0xb4000070ea055a00 frame=0 [ 640x 360: 640,32315659]
    BQDUMP  [10:0xb4

### Media

...

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by microkatz** [comment]
I tried testing with your mediacontent but the url was not reachable. Is the content not currently being hosted? Also Is there any way that you could send a bug report so that we could review the logs?
If you're unable to share [bug reports](https://developer.android.com/studio/debug/bug-report) or
test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format
"Issue #10866". Please also update this issue to
indicate you've done this.

**Comment by microkatz** [comment]
I'm going to close this issue. Please reopen if you are still hitting this problem and can send logs/provide accessible media content to reproduce the issue.
