### ISSUE TITLE
Streaming video on rebuffering again after play 1 times

### ISSUE THREAD

**Issue by hafiz013** [google/ExoPlayer#10872]
### ExoPlayer Version

2.18.2

### Devices that reproduce the issue

*Osprey device android 11
*MediaCodecInfo name is c2.android.aac.decoder

Link device: https://www.ebay.com/itm/334306318018

### Devices that do not reproduce the issue

*Emulator android 10, 11, 12 and 13 (MediaCodecInfo name is c2.android.avc.decoder )
*Osprey device android 10  (MediaCodecInfo name is OMX.google.h264.decoder)

### Reproducible in the demo app?

Yes

### Reproduction steps

1. Link media url reproduce rebuffer again:
 a. https://xandrssads-staging-sponsored.secure.footprint.net/XAAF/di/DTV_Movers/DTV_Movers.mp4 (need vpn USA)
 b. https://xandrssads-sponsored.secure.footprint.net/XAAF/di/MEPS_112922_1080p/MEPS_112922_1080p.mp4 (need vpn USA)

2. Link media url not reproduce rebuffer again:
 a. https://static.videezy.com/system/resources/previews/000/049/943/original/002831-HD-COUNTDOWN-03.mp4

 override fun onPlayerStateChanged(
        eventTime: AnalyticsListener.EventTime, playWhenReady: Boolean, playbackState: Int
    ) {
        when (playbackState) {
            Player.STATE_IDLE -> {
   
            }
            Player.STATE_BUFFERING -> {
          
            }
            Player.STATE_READY -> {
           
            }
            Player.STATE_ENDED -> {
           
            }
        }
    }

When the play finish for 1 video and do repeat again this video, it shouldn't go back to Player.STATE_BUFFERING when mediacode using c2.android.aac.decoder. Meanwhile the rest of other mediacode no have problem (not return back to Player.STATE_BUFFERING).

### Expected result

 override fun onPlayerStateChanged(
        eventTime: AnalyticsListener.EventTime, playWhenReady: Boolean, playbackState: Int
    ) {
        when (playbackState) {
            Player.STATE_IDLE -> {
   
            }
            Player.STATE_BUFFERING -> {
          
            }
            Player.STATE_READY -> {
           
            }
            Player.STATE_ENDED -> {
           
            }
        }
    }

When the play finish for 1 video and do repeat again it shouldn't go back to Player.STATE_BUFFERING (This not happen to mediacode c2.android.avc.decoder and OMX.google.h264.decoder

### Actual result

`val videoComponent = player.videoComponent
        videoComponent?.setVideoTextureView(textureView)
        val textComponent = player.textComponent
        //textComponent?.addTextOutput(componentListener)
        this.player.addListener(componentListener)`

`val mediaSource = buildMediaSource(videoUri)
        player.setMediaSource(mediaSource, true)
        player.prepare()
        player.playWhenReady = true
        player.repeatMode = Player.REPEAT_MODE_ALL`

`private fun buildMediaSource(uri: Uri): MediaSource {
        return ProgressiveMediaSource.Factory(DefaultHttpDataSource.Factory())
            .createMediaSource(MediaItem.fromUri(uri))
    }`

`override fun onPlayerStateChanged(
        eventTime: AnalyticsListener.EventTime, playWhenReady: Boolean, playbackState: Int
    ) {
        when (playbackState) {
            Player.STATE_IDLE -> {
                logD("onPlayerStateChanged playWhenReady: $playWhenReady Player.STATE_IDLE")
            }
            Player.STATE_BUFFERING -> {.  <-- when finish first video and do repeat this video, it shouldn't go to this state for mediacode c2.android.aac.decoder but the rest of other mediacode are not go here.
                logD("onPlayerStateChanged playWhenReady: $playWhenReady Player.STATE_BUFFERING")
                xaafVideoVideoEventListener.onPlayerStateChanged(XaafVideoVideoEventListener.ExoPlayerState.BUFFERING)
            }
            Player.STATE_READY -> {
                logD("onPlayerStateChanged playWhenReady: $playWhenReady Player.Player.STATE_READY")
                xaafVideoVideoEventListener.onPlayerStateChanged(XaafVideoVideoEventListener.ExoPlayerState.READY)

            }
            Player.STATE_ENDED -> {
                logD("onPlayerStateChanged playWhenReady: $playWhenReady Player.STATE_ENDED")
                xaafVideoVideoEventListener.onPlayerStateChanged(XaafVideoVideoEventListener.ExoPlayerState.ENDED)
            }
        }
    }`

### Media

As explain in above, buffer state should not be called again if do repeating in mediacode c2.android.aac.decoder. This also happen in latest exoplayer 2.18.2.

To conclude, other mediacode so far so good, no go back to buffer state again when repeat the video. You can test on the list video url above.

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by christosts** [comment]
> *Osprey device android 11
> *MediaCodecInfo name is c2.android.aac.decoder

Is there a specific reason you mention the audio codec for the affected device? 

All mp4 files have both audio and video, hence during playback the player will acquire two decoders. `c2.android.aac.decoder` is the audio decoder, but during playback there will also be a video decoder initialised too. This specific decoder is not device specific.

I tried playing all files and did not observe the state transition to `STATE_BUFFERING` when restarting the the media item.   If the player goes back to `STATE_BUFFERING`, it means it has discarded the played content. That sounds more a `back buffer` issue on `LoadControl`, but I would assume that would behave the same on any device, whereas you mention it only happens on the Osprey device with Android 11 (but not Osprey with Android 10).

Can you please try the following:
- try to reproduce with your contents on the [demo app](https://exoplayer.dev/demo-application.html).
  - you'll need to set the repeat mode yourself, perhaps you can set it on `PlayerActivity.initializePlayer()` somewhere around [these lines](https://github.com/google/ExoPlayer/blob/r2.18.2/demos/main/src/main/java/com/google/android/exoplayer2/demo/PlayerActivity.java#L272). 
 - the demo app logs state transitions so you don't need to add additional logging, look for logs starting with `EventLogger: state`. 
 - grab a [bug report](https://developer.android.com/studio/debug/bug-report) from the device once the issue happens and either attach it on the bug, or if you don't want to share it publicly send it with an email at  dev.exoplayer@gmail.com with a subject "Issue #10872" (please also update this issue to indicate you've send us an email).
