### ISSUE TITLE
How to use/implement Crossfade with ExoPlayer?

### ISSUE THREAD

**Issue by pablopantaleon** [google/ExoPlayer#1087]
I want to use [crossfade](http://mp3.about.com/od/glossary/g/Crossfading-Definition-What-Is-Crossfading.htm) in my app. I did a some research but i can't find any information of how i can do this or any starting point, anyone knows a way to do this?

**Comment by ojw28** [comment]
This question is not about functionality supported directly by ExoPlayer, and therefore falls outside the scope of this issue tracker. Closing.
