### ISSUE TITLE
Is there a way to get the Segments length in exo player?

### ISSUE THREAD

**Issue by Lilsax** [google/ExoPlayer#10873]
i need to get the segment length in exo player

**Comment by tianyif** [comment]
Hi @Lilsax,

Could you please provide more contexts around the question? For example, in terms of "Segments length", does it refer to number of segments in a segment list or the duration of a single segment? Is your question regarding one specific streaming technique (DASH, HLS and etc.)?

Please provide complete information as requested in the question template. The template can be
found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/question.md).

Unfortunately we can't answer unclear questions or those with insufficient information.
