### ISSUE TITLE
can not play mp4 video packaged by PS format

### ISSUE THREAD

**Issue by yummyChina** [google/ExoPlayer#10874]
com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors
my play source is mp4  DASH which is fomated with PS
is code error or exoplayer is not supported?

**Comment by tianyif** [comment]
Hi @yummyChina,

We're glad to help you, but before proceeding, could you please provide complete information as requested in the issue template? The issue template can be found [here](https://github.com/google/ExoPlayer/issues/new?assignees=&labels=bug%2Cneeds+triage&template=bug.yml). If you're unable to share [bug reports](https://developer.android.com/studio/debug/bug-report) or test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #1234" ("#1234" is replaced with your issue number). Please also update this issue to indicate you've done this.
