### ISSUE TITLE
No AdOverlay but receiving  two callbacks AD_PERIOD_STARTED_EVENT , AD_PERIOD_ENDED_EVENT

### ISSUE THREAD

**Issue by shagun-firstlight** [google/ExoPlayer#10886]
dependencies : 
def EXO_PLAYER_VERSION = '2.18.2'
implementation 'com.google.android.gms:play-services-ads-identifier:18.0.1'
implementation 'com.google.ads.interactivemedia.v3:interactivemedia:3.29.0'
implementation ("com.google.android.exoplayer:extension-ima:${EXO_PLAYER_VERSION}"){
exclude group: 'com.google.android.exoplayer', module:'exoplayer-common'
}
implementation "com.google.android.exoplayer:exoplayer-core:${EXO_PLAYER_VERSION}"
implementation "com.google.android.exoplayer:exoplayer-dash:${EXO_PLAYER_VERSION}"
implementation "com.google.android.exoplayer:exoplayer-ui:${EXO_PLAYER_VERSION}"
implementation "com.google.android.exoplayer:exoplayer-hls:${EXO_PLAYER_VERSION}"
implementation "com.google.android.exoplayer:exoplayer-smoothstreaming:${EXO_PLAYER_VERSION}"
implementation "com.google.android.exoplayer:extension-mediasession:${EXO_PLAYER_VERSION}"

I have implemented DAI which is working fine on native app, but on react native app using the same code it is not working, getting two callbacks AD_PERIOD_STARTED_EVENT , AD_PERIOD_ENDED_EVENT but didint see any ad overlay

**Comment by marcbaechinger** [comment]
> is working fine on native app, but on react native app using the same code it is not working

We can't support you with issues that are specific to reactive native I'm afraid. 

If you think this is a problem with the ExoPlayer library please re-open this issue so we can investigate.
