### ISSUE TITLE
Wrong currentPosition(even negative value) after reset when play AC-4

### ISSUE THREAD

**Issue by Jo-Yewon** [google/ExoPlayer#10887]
### ExoPlayer Version

2.17.0

### Devices that reproduce the issue

Samsung Galaxy Z Flip 4 running Android 13
Samsung Galaxy Z Fold 2 running Android 12
Samsung Galaxy Note 8 running Android 9
(Probably unrelated.)

### Reproducible in the demo app?

Yes

### Reproduction steps

(a) Negative value case
1. Play AC4 media using the demo app.
2. Try to log currentPosition repeatedly. (I repeated at 100 ms intervals right after prepare.)
3. Negative value is returned right after playback.

<br/>

(b) Seeking case (only in my app)
I haven't tested this case in the demo app.
However, I think this is also a related issue.

I set SeekParameter.Exact to the player.

1. Play AC4 media.
2. Request to seek to a specific position.
5. Try to get current position when seek is completed.
6. Returned value is less than requested position. (50ms~4s difference)

<br/>

(+) Additional Information
I log some values from `ExoPlayerImplInternal-updatePlaybackPositions()`
And here are the results.
```
com.google.android.exoplayer2.demo   D  renderPositionUs 999999937792
com.google.android.exoplayer2.demo   D  set playbackInfo positionUs -62208
```

### Expected result

Return accurate current position

### Actual result

Return inaccurate current position (even negative)

### Media

Any AC4 media
(I used sample.ac4 in your repository/testdata.)

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by tonihei** [comment]
I can reproduce the problem and it seems the negative timestamps are produced by the AC4 decoder on these Samsung devices (`c2.dolby.ac4.decoder`). ExoPlayer extracts the audio samples starting at time 0, but after decoding the timestamps suddenly start at -63ms. This is arguably a bug in the decoder and should be reported to Samsung or Dolby. ExoPlayer already does its best to work around negative timestamps, but we still have to trust the values returned from the codec to be correct. 

@ybai001: Do you have any insights or knowledge about this issue? I assume that negative timestamp after decoding are unexpected, but happen consistently with the attached test file.

https://user-images.githubusercontent.com/26897506/211573099-6aa70ce1-e325-4f9e-a35c-6d73ee6b81b4.mp4

**Comment by ybai001** [comment]
> I can reproduce the problem and it seems the negative timestamps are produced by the AC4 decoder on these Samsung devices (`c2.dolby.ac4.decoder`). ExoPlayer extracts the audio samples starting at time 0, but after decoding the timestamps suddenly start at -63ms. This is arguably a bug in the decoder and should be reported to Samsung or Dolby. ExoPlayer already does its best to work around negative timestamps, but we still have to trust the values returned from the codec to be correct.
> 
> @ybai001: Do you have any insights or knowledge about this issue? I assume that negative timestamp after decoding are unexpected, but happen consistently with the attached test file.
> 
>  sample_ac4.mp4

@tonihei, thanks for pointing it out. I checked with team. Yes, this is an issue in AC-4 decoder codec2 implementation and we have submitted code review internally. Will deliver it to customer after internal process is done.

**Comment by tonihei** [comment]
Thanks @ybai001!  I'll close this issue as it's a confirmed device-specific problem that will be fixed, but is outside the scope of this issue tracker.

**Comment by Jo-Yewon** [comment]
Thank you. 
I appreciate your support!
