### ISSUE TITLE
how to set a custom repeat drawable ?

### ISSUE THREAD

**Issue by rylderoliveira** [google/ExoPlayer#10889]
## Issue

I'm trying to override the `exo_styled_controls_repeat_off`, `exo_styled_controls_repeat_one` and `exo_styled_controls_repeat_all` icons, following the documentation: https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/ui/StyledPlayerControlView.html.

The `exo_styled_controls_repeat_off` and `exo_styled_controls_repeat_one` works fine, but the `exo_styled_controls_repeat_all` shows nothing. I'm sure that the `REPEAT_MODE_ALL` is activated but the drawable does'nt appear.

 ## Uses

Exo version: 2.13.3 ( I cannot update it, because I need a `MIN SDK = 22` )
Emulator: Android TV API 30
Class: I'm current using PlayerView, but I tried to change to StyledPlayerView and doesn't work neither.

**Comment by tonihei** [comment]
> The exo_styled_controls_repeat_off and exo_styled_controls_repeat_one works fine

Do you mean you can replace these button by custom versions or that you can see the defaults?

> but the exo_styled_controls_repeat_all shows nothing

As in, there is a blank space or no button at all? 

> I'm sure that the REPEAT_MODE_ALL is activated but the drawable does'nt appear.

Just to make sure - how did you verify that the mode is activated? For example, did you enable the button via the `repeat_toggle_modes` property of the view?

> I cannot update it, because I need a MIN SDK = 22

Maybe not relevant to your original question, but just noted it: Even the latest ExoPlayer version supports minSdk=16, so you should be able to update your version.
