### ISSUE TITLE
FormatEvaluator for changing video quality in HLS ,

### ISSUE THREAD

**Issue by amitsamal** [google/ExoPlayer#1088]
Hi Team,

I can see we have FormatEvaluator for Dashchunksource for changing stream quality. Do we have similar approach for HLS streams in HLS chunk source. Currently i want to implement changing stream quality between high , medium and low for HLS streams but cat resolve how. 
1st approach : 1. Change the buffer capacity and max buffer size which effects the quality but for changing have to reinitialise the HLSrenderer builder which is not the ideal process. 

Do we have any other approach for the same. 

Thanks 
Amit Samal

**Comment by ojw28** [comment]
This is tracked by https://github.com/google/ExoPlayer/issues/676.
