### ISSUE TITLE
Creating a media source 

### ISSUE THREAD

**Issue by blackcrown01** [google/ExoPlayer#10893]
i'm following this tutorial on youtube and i'm using exoPlayer with Kotlin to play audio from firebase storage
-------------------------

the probleme is when i got to a part to creata media source 
the youtuber got a Uri option but i end up with MediaDataCompat instead 

here my full class to better reading 

thank you for any contrbution

`class FirebaseAudioSource
    @Inject constructor(
        private val audioDatabase: AudioDatabase
    ){
    //audiobook metadata holder
    var audioBooks = emptyList<MediaMetadataCompat>()

    //function to get audioBooks metadata
    suspend fun fetchMediaData() = withContext(Dispatchers.IO){
        state = STATE_INITIALIZING
        val allAudioBooks = audioDatabase.getAllBooks()
        audioBooks = allAudioBooks.map {
           MediaMetadataCompat.Builder()
                .putString(METADATA_KEY_ARTIST,it.narrator)
                .putString(METADATA_KEY_MEDIA_ID,it.bookId)
                .putString(METADATA_KEY_TITLE,it.title)
                .putString(METADATA_KEY_DISPLAY_ICON_URI,it.bookCover)
                .putString(METADATA_KEY_ALBUM_ART_URI,it.bookCover)
                .putString(METADATA_KEY_WRITER,it.writer)
                .putString(METADATA_KEY_MEDIA_URI,it.bookUrl)
                .putString(METADATA_KEY_RATING,it.bookRating.toString())
                .putString(METADATA_KEY_DISPLAY_TITLE,it.title)
                .putString(METADATA_KEY_DISPLAY_SUBTITLE,it.narrator)
                .putString(METADATA_KEY_DISPLAY_DESCRIPTION,it.narrator)
                .build()
        }
        state=STATE_INITIALIZED
    }

    fun asMediaSource(dataSourceFactory: DefaultDataSourceFactory):ConcatenatingMediaSource{
        val concatenatingMediaSource = ConcatenatingMediaSource()

        audioBooks.forEach {
            val mediaSource = ProgressiveMediaSource.Factory(dataSourceFactory)
                .createMediaSource(**here i got the issue it supose to ask for an uri and iyt asking for MediaMetadatCompat**))
        }
    }
`

**Comment by tonihei** [comment]
> here i got the issue it supose to ask for an uri and iyt asking for MediaMetadatCompat

The method you reference requires a `MediaItem` to be passed in. 

For getting started with playlists, I'd recommend reading https://exoplayer.dev/playlists.html to get the latest documentation.

**Comment by tonihei** [comment]
Closing the issue as the question was answered.
