### ISSUE TITLE
How to cache videos like instagram reels using exoPlayer?

### ISSUE THREAD

**Issue by AsitDixit** [google/ExoPlayer#10891]
My URLs are CDN(content delivery network). Stll it takes 4-5sec when loading in exoplayer. I want to cache the videos like instagram. Currently I'm using a background service and for loop to cache video like below:
```
        for(int i=0;i<mediaList.size();i++){
          if(mediaList.get(i).getType()==PostType.VIDEO){
              ExecutorService serviceVideo = Executors.newSingleThreadExecutor();
      int finalI = i;
              serviceVideo.execute(() -> {
                  new ProgressiveMediaSource.Factory(new CacheDataSource.Factory()
                          .setCache(SimpleMediaPlayer.simpleCache)
                          .setUpstreamDataSourceFactory(new DefaultHttpDataSource.Factory().setUserAgent("ExoplayerDemo"))
                          .setFlags(CacheDataSource.FLAG_IGNORE_CACHE_ON_ERROR))
                          .createMediaSource(MediaItem.fromUri(mediaList.get(finalI).getUrl()));
                  Log.d("TAGServices", "VID-CACHE: "+finalI);

              });
     }
}
```
But it is not woking as of my expectations. Is there any efficient way?

**Comment by marcbaechinger** [comment]
If you [search this issue tracker for `CacheWriter`](https://github.com/google/ExoPlayer/issues?q=is%3Aissue+CacheWriter) and include closed issues as well, you get a list of issues that are related to that question.

The code above that you posted creates a progressive media source with a `CacheDataSource` for each stream. This is how you create  the source for playback. To fill the cache with data you can use a `CacheWriter`. Check the response to #10831 for instance, that gives you a code snippet how you can use the `CacheWriter`.

I'm closing this issue as a duplicate.
