### ISSUE TITLE
เพิ่มความคมชัดของขนาดภาพ

### ISSUE THREAD

**Issue by Brutalnung** [google/ExoPlayer#10894]
Before filing a feature request:
-----------------------
- Search existing open issues, specifically with the label ‘enhancement’:
  https://github.com/google/ExoPlayer/labels/enhancement
- Search existing pull requests: https://github.com/google/ExoPlayer/pulls

When filing a feature request:
-----------------------
Replace the content in the sections below.

### [REQUIRED] Use case description
Describe the use case or problem you are trying to solve in detail. If there are
any standards or specifications involved, please provide the relevant details.

### Proposed solution
A clear and concise description of your proposed solution, if you have one.

### Alternatives considered
A clear and concise description of any alternative solutions you considered,
if applicable.

**Comment by marcbaechinger** [comment]
I have translated the title with Google translate to `Increase the sharpness of the image size.` That's probably not correctly translated and if it is, it's a bit vague to be actionable.

Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/feature_request.md).
