### ISSUE TITLE
Audio Sink Error when change bitrate

### ISSUE THREAD

**Issue by Riki-Aji** [google/ExoPlayer#10899]
### ExoPlayer Version

2.18.2

### Devices that reproduce the issue

Samsung A20s, Android Version 10

### Reproducible in the demo app?

Yes

### Reproduction steps

1. Play the Video
2. the video have multiple bitrates, and set auto bitrate
3. if network unstable and the bitrates change, the error Audio Sink Error will appear
4. com.google.android.exoplayer2.audio.AudioSink$UnexpectedDiscontinuityException: Unexpected audio track timestamp discontinuity: expected 1000097905661, got 1000091910995
5. video freeze but the audio is running

### Expected result

the video can play with audio or 
video and audio buffer first

### Actual result

Video freeze but audio running

### Media

![gambar](https://user-images.githubusercontent.com/29775844/210302439-1df10cb2-3d0e-41d7-a8aa-caf7205ac4c1.png)

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by YounessZekki** [comment]
I have the same issue in exoplayer. @Riki-Aji did you find a solution for this issue?

**Comment by icbaker** [comment]
Please provide a link to a stream with multiple audio bitrates (DASH or HLS) that we can use to reproduce the issue. Please either post it here or send it to dev.exoplayer@gmail.com using the subject `Issue #10899`. Please also update this issue to indicate you’ve done this.

**Comment by Riki-Aji** [comment]
hello, hello I have sent the details to the email

**Comment by tianyif** [comment]
Hi @Riki-Aji,

We received your details in the email. However, the app is from the Play Store. Would you please provide the sample stream so that I can look deeper by debugging the demo app, as you mentioned this could be reproduced on the demo app.
