### ISSUE TITLE
Identify onPlaybackStatsReady callbacks for Ads playback

### ISSUE THREAD

**Issue by MBakhshi96** [google/ExoPlayer#10897]
As mentioned in docs for `PlaybackStatsListener`, `onPlaybackStatsReady` callback is called separately for main playback item and all of the inserted ads (e.g. pre-roll ads). Since `PlaybackStats` for ad playbacks are not important for me, I only want to log stats for the main media item. Is there a way to identify the type of media item for which the  `PlaybackStats` is prepared?

**Comment by tonihei** [comment]
The `eventTime` parameter of `onPlaybackStatsReady` tells you about which playback the stats belong to. In particular, the `EventTime` contains a `Timeline` with the full playlist and ad information and the `mediaPeriodId` field that tells you about the current ad group index and ad index.

**Comment by MBakhshi96** [comment]
I'm now using `eventTime.mediaPeriodId.isAd()` to filter ad playbacks and it seems to work. Thank you for your help.
