### ISSUE TITLE
Xiaomi Redmi 6A (cactus) - Decoder error playing H265 video

### ISSUE THREAD

**Issue by sailesha** [google/ExoPlayer#10895]
### ExoPlayer Version

2.18.2

### Devices that reproduce the issue

* Xiaomi Redmi 6A (M1804C3CG) 16GB (GSM Unlocked)
* 

### Devices that do not reproduce the issue

* Samsung Galaxy 22

### Reproducible in the demo app?

Yes

### Reproduction steps

Try to play the attached video

https://user-images.githubusercontent.com/1601858/210158446-ff6422ec-7d8d-4efe-85e1-cceac81b9d1f.mp4

### Expected result

Video plays

### Actual result

Decoder error 

### Media

See attached video above

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by sailesha** [comment]
Here's another video that also has a decoder error. In logcat I can see the following:

> 12-31 18:33:59.019 I/VDO_LOG (  521): h265_sw_dec_init u4Width 720, u4Height 1280, u2ClipLeft 0, u2ClipRight 719, u2ClipBottom 1279, u2ClipTop 0, Offset 20480, Padding 20480
> 12-31 18:33:59.019 W/ResourceType(26566): For resource 0x7f080686, entry index(1670) is beyond type entryCount(802)
> 12-31 18:33:59.019 E/VDO_LOG (  521): segment eFuse, limit to FHD
> 12-31 18:33:59.019 E/VDO_LOG (  521): h265_sw_dec_init() unsupported Width 768, Height 1280, ReadWidth 720, RealHeight 1280
> 12-31 18:33:59.019 E/VDO_LOG (  521): [Err] h265_sw_dec_init Error code 0 0x3

https://user-images.githubusercontent.com/1601858/210159578-19546e50-6972-4970-aa44-9da22e296e30.mp4

**Comment by sailesha** [comment]
Verified that the videos above were too large. Here's the max width and height for the HEVC decoder:
* width: 16 - 1920
* height: 16 - 1088

I guess the decoder error is expected.

Some feature requests:
* could ExoPlayer surface a better error message in this situation?
* could ExoPlayer provide a better API to find the video resolution constraints for the chosen decoder?

**Comment by christosts** [comment]
I don't have a Redmi 6A in my disposal. Can you please play the videos using the ExoPlayer [demo app](https://exoplayer.dev/demo-application.html) and grab a bug-report from the device. I'd like to see what logs are reported from the demo app too, to see if the video track is considered `SUPPORTED` on not.

Thanks
