### ISSUE TITLE
How to run Exoplayer Demo with android 4.4.2

### ISSUE THREAD

**Issue by kinhdang** [google/ExoPlayer#1089]
Dear all !

How to run Exoplayer Demo with android 4.4.2, I'm import examples into Eclipse but error : 

PackageManager.FEATURE_LEANBACK not resolve
AudioManager.ACTION_HDMI_AUDIO_PLUG not resolve
....

**Comment by ojw28** [comment]
Regardless of what version of Android the device you're using is running, you need to be developing with the latest version of the Android SDK (Android 6.0 API 23). It sounds like you have an older version of the Android SDK installed on your machine.
