### ISSUE TITLE
Subtitles don't disable after upgrading to 2.18.2 from 2.18.1

### ISSUE THREAD

**Issue by emveepee** [google/ExoPlayer#10904]
After the upgrade I can no longer turn off subtitles, turning them on still works. The code snippet I use works to toggle the subtitles which has worked for several versions is 

```
        DefaultTrackSelector.Parameters parameters = trackSelector.getParameters();
        DefaultTrackSelector.Parameters.Builder builder = parameters.buildUpon();
        if (id.equals("Disable"))
        {
            builder.clearOverridesOfType(C.TRACK_TYPE_TEXT);
            builder.setRendererDisabled(C.TRACK_TYPE_TEXT, true);
            trackSelector.setParameters(builder);
            enableSubtitle = false;
            return;
        } else if (id.equals("Enable")) {
            builder.clearOverridesOfType(C.TRACK_TYPE_TEXT);
            builder.setPreferredTextLanguage(Locale.getDefault().getLanguage());
            builder.setSelectUndeterminedTextLanguage(true);
            builder.setRendererDisabled(C.TRACK_TYPE_TEXT, false);
            trackSelector.setParameters(builder);
            enableSubtitle = true;
            return;
        }
```
The rendererIndex seen in  DefaultTrackSelector() is the same (3) and I do see rendererDisabledFlags toggle start at {3=true} go to {} and the back to {3=true}

 I do notice is that the debug EventLogger() messages don't trigger when I disable subtitles.  Is there something new I need to to do force this change to be triggered?

**Comment by icbaker** [comment]
It sounds like you're saying that the text renderer is disabled, but you still see subtitles. That sounds surprising. Please provide a minimally reproducible example we can use to reproduce the problem (ideally fork the demo app and make a small commit on top, then send us a link to the GitHub project).

Note that the demo app is able to enable/disable subtitles at version 2.18.2 so you might want to take a look at how that's implemented. There's actually two places (beause there's two UI buttons for changing text tracks in the demo app):
* Demo app specific: https://github.com/google/ExoPlayer/blob/r2.18.2/demos/main/src/main/java/com/google/android/exoplayer2/demo/TrackSelectionDialog.java
* Standard UI elements: https://github.com/google/ExoPlayer/blob/r2.18.2/library/ui/src/main/java/com/google/android/exoplayer2/ui/StyledPlayerControlView.java#L2022

**Comment by emveepee** [comment]
Thank @icbaker Looking at ExoPlayer I changed builder.setRendererDisabled() to builder.setTrackTypeDisabled(); and it works in 2.18.2.  However this didn't work in 2.18.1, so for now I  just use both.

**Comment by icbaker** [comment]
Glad you got it working.
