### ISSUE TITLE
how i can set the startup bitrate in exo player?

### ISSUE THREAD

**Issue by Lilsax** [google/ExoPlayer#10900]
how i can set the startup bitrate in exo player?

**Comment by pradeepvernekarzee** [comment]
Please try the below code to set the initial bitrate
 DefaultBandwidthMeter.Builder(context).apply {
                setInitialBitrateEstimate(bitrate)
            }
  }.build()

**Comment by Lilsax** [comment]
that does not actually set the initial bitrate becasue it only work when

_Sets the initial bitrate estimate in bits per second that should be assumed when a bandwidth estimate is unavailable_

and the bandwidth estimate determined by the player so as long as that value is set that function is useless that's why it only work the first time u lunch the app 

so the real question in here is is there a way to set **bandwidth estimate** ??

**Comment by tonihei** [comment]
I assume your intention is not to set the bandwidth estimate (=the actual network speed), but rather to force a maximum selected bitrate for the first segment of each playback. If that's not the case, please clarify what you want to achieve. 

You can dynamically filter which formats can be selected by providing custom `AdaptiveTrackSelection` classes that override the `canSelectFormat` method with your custom filtering logic:

You can provide a custom `ExoTrackSelection.Factory` to `DefaultTrackSelector` (which can be set via `ExoPlayer.Builder.setTrackSelector`). This custom `ExoTrackSelection.Factory` can be a subclass of `AdaptiveTrackSelection.Factory` where you override `createAdaptiveTrackSelection`. In there you can return a subclass of `AdaptiveTrackSelection` where you override `canSelectFormat`. This method can return `false` for the first selection if the bitrate exceeds a certain value.

**Comment by Lilsax** [comment]
For whoever gonna wanna set this
this is the solution 

create this class and add it to 

thank you @tonihei 

`                        ExoTrackSelection.Factory videoTrackSelectionFactory = new LimitedABS.Factory();
`

 ```
public class LimitedABS extends AdaptiveTrackSelection {

       public LimitedABS(TrackGroup group, int[] tracks, BandwidthMeter bandwidthMeter) {
                super(group, tracks, bandwidthMeter);
        }

        @Override
        protected boolean canSelectFormat(Format format, int trackBitrate, float playbackSpeed, long effectiveBitrate) {
                long _effectiveBitrate;

                if(ReactExoplayerView.qualityCounter < 5) {
                        _effectiveBitrate = 50000;
                } else {
                        _effectiveBitrate = effectiveBitrate;
                }

                ReactExoplayerView.qualityCounter++;
                return Math.round(trackBitrate * playbackSpeed) <= _effectiveBitrate;
        }


        public static class Factory extends AdaptiveTrackSelection.Factory
        {

                @Override
                protected AdaptiveTrackSelection createAdaptiveTrackSelection(TrackGroup group, BandwidthMeter bandwidthMeter, int[] tracks, ImmutableList<AdaptationCheckpoint> adaptationCheckpoints) {
                        return new LimitedABS(group,tracks,bandwidthMeter);
                }

        }


}
```

**Comment by Lilsax** [comment]
Thank you @tonihei  it worked <3
