### ISSUE TITLE
How can I rotate a video without using texture_view?

### ISSUE THREAD

**Issue by casolorz** [google/ExoPlayer#10901]
I found out today that `app:surface_type="texture_view"` doesn't appear to work with HDR videos, well it works but the videos are pretty dark.  It is pretty easy to reproduce that issue, just add the `texture_view` attribute and play this video https://4kmedia.org/life-untouched-hdr-uhd-4k-demo/ on a CCwGTV. 

The issue is that now that I've removed `app:surface_type="texture_view"`, video rotation doesn't work anymore. 

So how can I rotate a video if I want to also allow HDR videos?

**Comment by tonihei** [comment]
ExoPlayer will have new frame processors in the next full release that allows you to rotate videos arbitrarily. This is already implemented, but not yet released.

Your current analysis is correct otherwise: `TextureView` doesn't fully support HDR, but `SurfaceView` can't be rotated. See also https://developer.android.com/reference/android/view/TextureView, where the table under "TextureView vs. SurfaceView Capabilities" lists these differences.

**Comment by casolorz** [comment]
Thank you, really appreciate the very informative response. 

Right now I'm on `androidx.media3:media3-exoplayer:1.0.0-beta03`. Will this change be on the next beta or full release or do you mean on a higher version than `1.0.0`?

**Comment by claincly** [comment]
what Toni meant is the code is only on the `dev-v2` branch and it's not present in any released artifact.

re: frame processor:

we expect to have this feature ready very soon (within the month) and it'll allow you to apply arbitrary GL shader to a decoded video stream. We will support rotation by only 1 loc change. and this feature does support HLG HDR content

**Comment by casolorz** [comment]
Ok, thank you for the clarification. Is there a way to monitor when `dev-2` is released?

**Comment by ThucVan** [comment]
Is there any workaround for this problem?

**Comment by claincly** [comment]
What problem are you referring to, `TextureView` not supporting HDR or video rotation?

Please post your question to the [media3 repo](https://github.com/androidx/media/issues) for further questions, as this repo is not actively worked on anymore.
