### ISSUE TITLE
Playing local aes128 encrypted mp4 file

### ISSUE THREAD

**Issue by AlirezaGhanbarinia** [google/ExoPlayer#1091]
Hi,
First, thanks for your awesome tool.

Actually, I'm trying to play an encrypted local mp4 file with the codes provided below.
Unfortunately, its not working and Exo can not play the video.
Would you please help me on this matter?
Appreciate any help.

,,,

     Allocator allocator = new DefaultAllocator(BUFFER_SEGMENT_SIZE);

    // Build the video and audio renderers.
    DefaultBandwidthMeter bandwidthMeter = new DefaultBandwidthMeter(player.getMainHandler(), null);
    DataSource dataSource = new DefaultUriDataSource(context, bandwidthMeter, userAgent);

    Aes128DataSource aes128DataSource = new Aes128DataSource(dataSource, AES_KEY, AES_IV);

    ExtractorSampleSource sampleSource = new ExtractorSampleSource(uri, aes128DataSource, allocator, BUFFER_SEGMENT_COUNT * BUFFER_SEGMENT_SIZE);
    MediaCodecVideoTrackRenderer videoRenderer = new MediaCodecVideoTrackRenderer(context, sampleSource, MediaCodec.VIDEO_SCALING_MODE_SCALE_TO_FIT, 5000, player.getMainHandler(), player, 50);
    MediaCodecAudioTrackRenderer audioRenderer = new MediaCodecAudioTrackRenderer(sampleSource, null, true, player.getMainHandler(), player, AudioCapabilities.getCapabilities(context));
    TrackRenderer textRenderer = new TextTrackRenderer(sampleSource, player, player.getMainHandler().getLooper());

    // Invoke the callback.
    TrackRenderer[] renderers = new TrackRenderer[ClassExoPlayer.RENDERER_COUNT];
    renderers[ClassExoPlayer.TYPE_VIDEO] = videoRenderer;
    renderers[ClassExoPlayer.TYPE_AUDIO] = audioRenderer;
    renderers[ClassExoPlayer.TYPE_TEXT] = textRenderer;
    player.onRenderers(renderers, bandwidthMeter);
,,,

**Comment by ojw28** [comment]
`Aes128DataSource` is package private to the HLS package, and as such is not part of ExoPlayer's public API. It's intended for internal use only, and is not a fully functional `DataSource` implementation. See the comment at the top of that class:

```
 * Note that this {@link DataSource} does not support being opened from arbitrary offsets. It is
 * designed specifically for reading whole files as defined in an HLS media playlist. For this
 * reason the implementation is private to the HLS package.
```

If you wish to play something that you've encrypted, it's your responsibility to implement and use a `DataSource` that provides correctly decrypted data (including from arbitrary offsets).
