### ISSUE TITLE
MediaCodec: Codec reported err 0xfffffff4/NO_MEMORY on Android 12 devices

### ISSUE THREAD

**Issue by VIkash2601** [google/ExoPlayer#10928]
### ExoPlayer Version

2.14.0

### Devices that reproduce the issue

Nokia 5.4

### Reproducible in the demo app?

Not tested

### Reproduction steps

1. Created instance of Exoplayer as Recyclerview Item and also a Viewpager Item.
2. If the Item is in focus, sometimes it plays perfectly but if scrolling is fast, it doesn't render the video from the URL.
3. Code:
`if (exoplayer == null && list != null) {`
`            val executorService = Executors.newSingleThreadExecutor()`
`            executorService.execute {`
`                val loadControl: LoadControl = DefaultLoadControl.Builder()`
`                    .setAllocator(DefaultAllocator(true, 16))`
`                    .setBufferDurationsMs(1 * 1024, 1 * 1024, 500, 1024)`
`                    .setTargetBufferBytes(-1)`
`                    .setPrioritizeTimeOverSizeThresholds(true)`
`                    .build()`
`                val trackSelector = DefaultTrackSelector(mActivity!!)`
`                try {`
`                    mActivity!!.runOnUiThread {`
`                        exoplayer =`
`                            SimpleExoPlayer.Builder(mActivity!!).setTrackSelector(trackSelector)`
`                                .setLoadControl(loadControl)`
`                                .build()`
`                        val dataSourceFactory: DataSource.Factory =`
`                            DefaultDataSourceFactory(`
`                                mActivity!!, mActivity!!.getString(R.string.app_name)`
`                            )`
`                        val videoSource: MediaSource =`
`                            ProgressiveMediaSource.Factory(dataSourceFactory)`
`                                .createMediaSource(MediaItem.fromUri(videoURL!!))`
`                        //exoplayer!!.setThrowsWhenUsingWrongThread(false)`
`                        exoplayer!!.addMediaSource(videoSource)`
`                        exoplayer!!.prepare()`
`                        //exoplayer!!.addListener(this@HomePostsAdapter)`
`                        exoplayer!!.repeatMode = Player.REPEAT_MODE_ONE`
`                        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {`
`                            val audioAttributes =`
`                                AudioAttributes.Builder()`
`                                    .setUsage(C.USAGE_MEDIA)`
`                                    .setContentType(C.CONTENT_TYPE_MOVIE)`
`                                    .build()`
`                            exoplayer!!.setAudioAttributes(audioAttributes, true)`
`                        }`
`                    }`
`                } catch (e: Exception) {`
`                    Log.d("PostHomeFragment", "Exception audio focus : $e")`
`                }`
`                mActivity!!.runOnUiThread {`
`                    videoView.findViewById<View>(com.google.android.exoplayer2.ui.R.id.exo_play).visibility =`
`                        View.GONE`
`                    if (exoplayer != null) {`
`                         videoView.player = exoplayer`
`                        // list!![0]!!.getFiles()!![0]!!.playerView = exoplayer`
`                        exoplayer!!.playWhenReady = true`
`                    }`
`                }`
`            }`
`        }`

### Expected result

The video should be played smoothly if the view is in focus.

### Actual result

the holder displays a blank screen where;
1. Sometimes the video is playing perfectly.
2. Only the audio is playing.
3. Neither the audio nor the video is playing.

### Media

Not applicable.

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by marcbaechinger** [comment]
We can't really help with `RecyclerView` implementations I'm afraid. Please refer to #867 where many developers share their experience and solutions with this.

>  it plays perfectly but if scrolling is fast, it doesn't render the video from the URL.

I think best is to stop creating players automatically when the scrolling is very fast.
