### ISSUE TITLE
Video stops but audio is continue working

### ISSUE THREAD

**Issue by Zo2m4bie** [google/ExoPlayer#1092]
Hi. I faced of with strange  problem. When I open a HLS video stream(other HLS video streams work fine), I see one-two frame and after that the video stops but I hear a voice from the video(I didn't call stop or release). In log I don't see any errors it looks like the video works fine. ts chunk size ~4sec. Can you help me with this? I want at least receive some error

Video info:

    Codec: H264 - MPEG-4 AVC (part 10) (h264) 
    Resolution: 1280x720

Audio info:

     Codec: MPEG AAC Audio (mp4a)

**Comment by Zo2m4bie** [comment]
Also I found that it doesn't reproduce on all devices

**Comment by ojw28** [comment]
There's insufficient information here for us to debug the issue. Please open a new issue containing all of the information listed [here](https://google.github.io/ExoPlayer/2015/10/01/reporting-issues.html) and we'll take a look.
