### ISSUE TITLE
url with PHP and parameters

### ISSUE THREAD

**Issue by Saule2006** [google/ExoPlayer#10922]
What is the way to provide the stream url in playlist with the php parameters?
In example:
this url works: http://server.com/test.php/index.m3u8
this one not: http://server.com/test.php?ch=tvchannel/index.m3u8

If there in the url link after the "php" comes the "?" sign, the Exo player do not opens the stream

**Comment by marcbaechinger** [comment]
If the path of an HLS URL does not end with the extension `m3u8`, you need to set the mimetype in the media item. 

Set the mime type to the `MediaItem.Builder` with `setMimeType(MimeTypes.APPLICATION_M3U8)` when you build the media item. You can also consult the [Developer Guide page for HLS](https://exoplayer.dev/hls.html#using-mediaitem).
