### ISSUE TITLE
First video frame is delayed cause Loadable is cancelled

### ISSUE THREAD

**Issue by stari4ek** [google/ExoPlayer#1093]
It can be easily observed if _DefaultBandwidthMeter_ is attached to _DataSource_. It notifies about bandwidth when transfer ends (when connection/socket is closed).

In my case:
* _UdpDataSource_ is used (multicast)
* _ExtractorSampleSource_ with TsExtractor
* h264/mp2 stream
* ExoPlayer from master (1.5.3)

It happens with _ExtractorSampleSource.enable(int track, long positionUs)_ which calls _restartFrom(long positionUs)_ which cancels _Loadable_ which closes socket.

I've measured time between player goes to _STATE_BUFFERING_ (and tracks info is available) and first video frame being rendered to surface

* with loader reset: ~1.2sec
* without reset: ~0.250sec

Checked 3 times for each situation on the same live stream.

With streams I'm using it drops ~300kb of data (collected in ~1.3sec).

**Comment by ojw28** [comment]
This issue is tracked by #1041
