### ISSUE TITLE
Viber pop-up message block video

### ISSUE THREAD

**Issue by Angels-group** [google/ExoPlayer#1094]
Good day! 

I found strange behavior ExoPlayer. If i receive message in Viber app, and I have the option "Pop-up message" in Viber settings - video and audio stops (just black screen) until I do not close the message window.

Can I change the behavior of ExoPlayer?

**Comment by ojw28** [comment]
Are you a developer of Viber, or a user? This sounds like an application issue, not an ExoPlayer issue. It's up to the application to pause/release the ExoPlayer instance at an appropriate time.

**Comment by Angels-group** [comment]
I am user.
For example, Youtube app stopped to pause at the pop-up message on Viber.

I have video streaming and it can not be put on pause.
It may possibly continue to play in ExoPlayer?

**Comment by ojw28** [comment]
This is an application developer decision; not something related to ExoPlayer.
