### ISSUE TITLE
Why does getCurrentPosition enforce the accessor thread rule?

### ISSUE THREAD

**Issue by stoyicker** [google/ExoPlayer#10955]
I have a use case where I am building a library which lays an abstraction layer on top of ExoPlayer for simplicity, including things such as managing an internal thread which is the one used to control ExoPlayer, allowing calls to the library to occur on any thread as we internally switch them to run on the thread required by ExoPlayer.

Speaking of this pattern specifically, it's fine to have operations such as playing or pausing be asynchronous, but querying the current position is a bit awkward: while it'd be theoretically possible to make it also asynchronous so that current position is emitted as an event as a result of a query made on an "unknown" thread that is then switched to ExoPlayer's, it sort of beats the point of simplicity and, unnecessarily at that, because getCurrentPosition is read-only so to speak, so I don't see why it needs to happen on ExoPlayer's control thread.

Note that I've found [this somewhat related issue](https://github.com/google/ExoPlayer/issues/7775), but I don't want to use ExoPlayer's UI so `progressUpdateListener` doesn't work for me and I really don't want to be polling the position in order to be able to provide it synchronously.

**Comment by microkatz** [comment]
Hello @stoyicker. Thank you for your question.

Between the Application and Playback threads there is shared state in the PlaybackInfo objects utilized by ExoPlayerImpl and ExoPlayerImplInternal. Some ExoPlayerImpl methods called on the Application thread, like `prepare` or `setMediaSources`,  set in motion events that 'un-link' the shared PlaybackInfo states, make changes to playbackInfo, and then 're-link'. If other threads could access GetCurrentPosition(), then there could be inconsistent results based on how the threads interleave.

You will need to either poll for the position or create some listener of your own to receive position updates.

**Comment by stoyicker** [comment]
I see, thanks!
