### ISSUE TITLE
video processing

### ISSUE THREAD

**Issue by ArshakManukyan** [google/ExoPlayer#10957]
Hi. I want to ask a question regarding video processing.

Is there any way for decoding two videos at some time? 

The use case is simple: Imagine you have a video and you want to add overlay video.

I couldn't find the answer to this.

Thanks.

**Comment by andrewlewis** [comment]
> Is there any way for decoding two videos at some time?
> The use case is simple: Imagine you have a video and you want to add overlay video.

The short answer is that there isn't an easy way to do this at the moment.

- We currently don't support having two videos playing via one ExoPlayer out of the box. So for now you'll need to use multiple players and keep them roughly synchronized yourself, or add this functionality via customization (see for example the comment near the end of #6723).
- Having done that, the two players will need their own output surfaces. They could come from two separate surface views, but for more flexibility in how to do the blending (for example, if you want to make one of them transcluent) you will probably need to render off-screen to `SurfaceTexture`s and process the video frames in GL textures.
- Android decoders don't support outputting translucent videos, so you may need to get the frames from the overlay into OpenGL anyway to do chroma-key or similar to generate an alpha channel, then blend the frames in a shader and output the result.

Doing all this customization is a lot of work. Later this year we expect to have more components available to make it easier, for example, we are currently working on adding `ExoPlayer.setVideoEffects` (that method will take what are basically factories for GL shader programs to apply to each video frame), then at some point we expect to have support for compositing multiple videos together.
