### ISSUE TITLE
How can I merge video and audio with different repeat modes ?

### ISSUE THREAD

**Issue by mustafatatarhan0** [google/ExoPlayer#10958]
```kotlin
val audioSource = ProgressiveMediaSource.Factory(dataSource)
                    .createMediaSource(MediaItem.fromUri(audioUri))
 val videoSource = ProgressiveMediaSource.Factory(dataSource)
                    .createMediaSource(MediaItem.fromUri(videoUri))
val mergingMediaSource = MergingMediaSource(videoSource, audioSource)
```

My player's repeat mode is `REPEAT_MODE_ONE`.
I want to play video with infinite loop but audio with a single loop. 

Like `LoopingMediaSource`.

But it deprecated.

How can I do this?

**Comment by microkatz** [comment]
@mustafatatarhan0. To answer your question, its quite difficult to utilize MergingMediaSource in that way as it requires matching periods for the different MediaSources. In your case, you have a smaller videoSource and longer audioSource. 

Your query reminded me of [Github Issue #8688](https://github.com/google/ExoPlayer/issues/8688). I think a similar solution might work for you with using two player instances, one for audio and one for video. Option number 5 in the thread and you can look at Toni's comment for guidance on synchronization.

**Comment by mustafatatarhan0** [comment]
Using two instances of exoplayer with a common manager solved my problem. Thanks! @microkatz
