### ISSUE TITLE
SmoothStream audio track language metadata is not made available

### ISSUE THREAD

**Issue by twcapps** [google/ExoPlayer#1095]
When we request the Audio tracks on a SmoothStream stream the language attribute on the manifest xml is not made available on the _MediaFormat_ language property return from the _getTrackFormat_ method:
https://github.com/google/ExoPlayer/blob/0c060f429f459f1bac2ffa0963cadc45ce35b73a/library/src/main/java/com/google/android/exoplayer/ExoPlayer.java#L327

It seems the language attribute is parsed and passed down to the _StreamElement_
https://github.com/google/ExoPlayer/blob/master/library/src/main/java/com/google/android/exoplayer/smoothstreaming/SmoothStreamingManifestParser.java#L580

But when the MediaFormat instance is created the language property is linked to the _TrackElement_ (not to the StreamElement):
https://github.com/google/ExoPlayer/blob/c9caaad50c4148a8c369816c100c170436a3d4d6/library/src/main/java/com/google/android/exoplayer/smoothstreaming/SmoothStreamingChunkSource.java#L417

The _TrackElement_ does not contain the language flag:
https://github.com/google/ExoPlayer/blob/master/library/src/main/java/com/google/android/exoplayer/smoothstreaming/SmoothStreamingManifest.java#L134

As a result the _getTrackFormat_ will always return a _MediaFormat_ with a language set to _null_, even if the metadata is available on the manifest.

**Comment by ojw28** [comment]
@AquilesCanta - Fancy looking at this? `SmoothStreamingManifestParser` needs to be updated so that the `Format` returned by `TrackElement.getFormat` includes the language, which it doesn't currently. Note that `type` is an example of something that's parsed at the stream element level but used in the track element level, which is more or less what needs doing in this case too.

**Comment by ojw28** [comment]
@bartsidee - Your fix looks good to me (aside from the one comment in just added to one of the ref'd changes). Are you planning to send a pull request to fix this, or do we need to do it ourselves? Thanks!

**Comment by bartsidee** [comment]
Created a pull request and a new branch which has dev as origin (current was master)

**Comment by ojw28** [comment]
Fixed in https://github.com/google/ExoPlayer/pull/1155.
