### ISSUE TITLE
Unable to play mp3 in assets folder using AssetDataSource

### ISSUE THREAD

**Issue by amanmj** [google/ExoPlayer#1096]
I am using exoplayer to play a song file - "song.mp3" present in "/src/main/assets" folder using AssetDataSource.

My code is as follows : 

```java
DataSource dataSource=new AssetDataSource(getApplicationContext());
ExtractorSampleSource extractorSampleSource=new       ExtractorSampleSource(Uri.parse("song.mp3"),dataSource,new DefaultAllocator(1000),5000);
ExoPlayer exo=ExoPlayer.Factory.newInstance(1);
TrackRenderer audio=new MediaCodecAudioTrackRenderer(extractorSampleSource,null,true);
exo.prepare(audio);
exo.setPlayWhenReady(true);
Log.i("Exoplayer duration","reached end "+exo.getDuration());
```

exo.duration() is returning "-1" and the song is not playing.
Please help.

**Comment by se-bastiaan** [comment]
`song.mp3` is not a correct uri. Try `asset:///song.mp3`.

**Comment by amanmj** [comment]
@se-bastiaan still the same problem. It won't play

**Comment by ojw28** [comment]
What @se-bastiaan suggests should work. There's not a lot we can do to investigate further unless you provide complete information as listed [here](https://google.github.io/ExoPlayer/2015/10/01/reporting-issues.html).

You should also ensure that the asset really is being included in your apk. Are you able to play it using `MediaPlayer` or any other media library?

**Comment by amanmj** [comment]
@ojw28 , yes the mp3 file is included in the apk and I am able to play it using MediaPlayer but through AssetFileDescriptor whereas I need a URI in case of AssetDataSource so AssetFileDescriptor won't work in case of Exoplayer.

I am using the current latest version of Exoplayer.
Here is a link to my code
https://github.com/amanmj/exoplayer_temp

**Comment by ojw28** [comment]
Please see list of complete information linked above, and provide it. Thanks.

**Comment by amanmj** [comment]
@ojw28 there is not any example of AssetDataSource in the demo app.
I have uploaded the bugReport. Please let me know if any other information is needed.
[bugreport.txt](https://github.com/google/ExoPlayer/files/79991/bugreport.txt)
Here is a link to my code
https://github.com/amanmj/exoplayer_temp

**Comment by AquilesCanta** [comment]
Try using larger parameters for the default allocator and the ExtractorSampleSource in: 

    ExtractorSampleSource extractorSampleSource=new ExtractorSampleSource(Uri.parse("song.mp3"),dataSource,new DefaultAllocator(1000),5000);

Such as the ones used in the DemoPlayer.

In particular, the ExtractorSampleSource gets blocked after lacking allocated space. You can check the ExtractorSampleSource class. To sum up, try

    ExtractorSampleSource extractorSampleSource=new ExtractorSampleSource(Uri.parse("song.mp3"),dataSource,new DefaultAllocator(64 * 1024), 64 * 1024 * 256);

Just like in the DemoPlayer. 

Regards.
