### ISSUE TITLE
Our application reported error: com.google.android.exoplayer2.ExoPlaybackException: Unexpected runtåime error

### ISSUE THREAD

**Issue by cxw18772827901** [google/ExoPlayer#10966]
### ExoPlayer Version

2.17.1

### Devices that reproduce the issue

SHARK PRS-A0 android11
The above is the device that has the problem, but this problem is an occasional problem, not a certain one. We have not been able to reproduce this problem manually.

### Reproducible in the demo app?

Not tested

### Reproduction steps

We have not found a regularity for this problem.

### Expected result

play normal,unexpected runtåime error will not appear.

### Actual result

we found error
com.google.android.exoplayer2.ExoPlaybackException: Unexpected runtime error
com.google.android.exoplayer2.g2.d(Unknown Source:8)
com.google.android.exoplayer2.f0.invoke(Unknown Source:2)
com.google.android.exoplayer2.util.s$c.a(Unknown Source:17)
com.google.android.exoplayer2.util.s.a(Unknown Source:16)
com.google.android.exoplayer2.util.a.run(Unknown Source:6)
com.google.android.exoplayer2.util.s.a(Unknown Source:66)
com.google.android.exoplayer2.util.s.b(Unknown Source:3)
com.google.android.exoplayer2.g2.release(Unknown Source:152)
com.google.android.exoplayer2.l3.release(Unknown Source:5)

### Media

All videos cannot be played after this issue occurs

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by tianyif** [comment]
Hi @cxw18772827901,

Is SHARK PRS-A0 running on android11 the only setup seeing this problem? Did you find the same problem on the other devices?
