### ISSUE TITLE
Is it possible set interval between MediaItems

### ISSUE THREAD

**Issue by iranandroid** [google/ExoPlayer#10967]
Hi
I have list of media items and i need set interval between media items like below image:
![mediaItems](https://user-images.githubusercontent.com/20900080/217283761-4672b67e-cde0-4817-a7ff-9043516cd399.png)
when stop box1 set 6 second interval and play box 2 , ...

is it possible?

**Comment by marcbaechinger** [comment]
I'm not sure about the user experience you are trying to achieve.

One way would be to insert a period of silence by using a `SilenceMediaSource` (see #10963 also). However, this would make the silence a part of the playlist. For the example above this would for instance mean that there are three items in the playlist (MediaItem 1 - 3) on window index 0, 1 and 2 and then the silence would be the 4th item. That's where my question about the user experience is coming from as the user would notice the silence as an item that can be seeked to and within that duration of silence with `seekTo(windowIndex, positionMs)` and `seekTo(positionMs)`.

We are going to open-source `ConcatenatingMediaSource2` soon (around this or next week). This would add another option where you could concatenate two media items/media sources together into a single window. With this approach you can concatenate `Media Item 3` and the `SilenceMediaSource` to a single window/media item. Then the silence would be added to `Media Item 3` and would be part of the window at index 2. The user wouldn't see the item in the playlist as a separate item but instead the `Media Item 3` would have the given duration of silence at the end. The user would still be able to seek within that duration of silence.

A third option that comes to mind would be to simply pause playback at for instance the end of `Media Item 3`. This would involve adding a `Player.Listener` and wait for the `onMediaItemTransitioned()` event. Then when the event tells you that the player transitions to `Media Item 3` you can call `exoPlayer.setPauseAtEndOfMediaItems(true)`. This makes the player pause at the end of `Media Item 3`. Then you can start a timer or something (like `Handler.postDelayed(Runnable)`) that continues playback after the given amount of time. This approach has the advantage that you don't have the silence in the playlist, not as a silence at the end of an item nor as a specific item for the silence.

That's what comes to my mind and I think choosing the right approach depends on the desired user experience, like whether there is a UI that allows the user to pause/play or not and things like this.

**Comment by iranandroid** [comment]
> I'm not sure about the user experience you are trying to achieve.
> 
> One way would be to insert a period of silence by using a `SilenceMediaSource` (see #10963 also). However, this would make the silence a part of the playlist. For the example above this would for instance mean that there are three items in the playlist (MediaItem 1 - 3) on window index 0, 1 and 2 and then the silence would be the 4th item. That's where my question about the user experience is coming from as the user would notice the silence as an item that can be seeked to and within that duration of silence with `seekTo(windowIndex, positionMs)` and `seekTo(positionMs)`.
> 
> We are going to open-source `ConcatenatingMediaSource2` soon (around this or next week). This would add another option where you could concatenate two media items/media sources together into a single window. With this approach you can concatenate `Media Item 3` and the `SilenceMediaSource` to a single window/media item. Then the silence would be added to `Media Item 3` and would be part of the window at index 2. The user wouldn't see the item in the playlist as a separate item but instead the `Media Item 3` would have the given duration of silence at the end. The user would still be able to seek within that duration of silence.
> 
> A third option that comes to mind would be to simply pause playback at for instance the end of `Media Item 3`. This would involve adding a `Player.Listener` and wait for the `onMediaItemTransitioned()` event. Then when the event tells you that the player transitions to `Media Item 3` you can call `exoPlayer.setPauseAtEndOfMediaItems(true)`. This makes the player pause at the end of `Media Item 3`. Then you can start a timer or something (like `Handler.postDelayed(Runnable)`) that continues playback after the given amount of time. This approach has the advantage that you don't have the silence in the playlist, not as a silence at the end of an item nor as a specific item for the silence.
> 
> That's what comes to my mind and I think choosing the right approach depends on the desired user experience, like whether there is a UI that allows the user to pause/play or not and things like this.

Hi @marcbaechinger 
These are great solutions. i needed 3th solution.
Thank yout
