### ISSUE TITLE
AudioManager API usage in ExoPlayer

### ISSUE THREAD

**Issue by dryganets** [google/ExoPlayer#10962]
Want to start a discussion around usage of the AudioManager API in the exoplayer.
We are seeing a number of new ANR's related to the component that is new in the exoplayer 2.16.1 - `StreamingVolumeManager`.

After an investigation we find some minor issues in the component and we have some suggestions to how it's usage could be improved.

We want to get your thoughts on that.

1. You are using internal platform API to listen to volume changes that might behave differently on different devices.
Not sure how it behaves on your's - I'm getting 5 broadcasts of the volume change on every volume button click on my `OnePlus85g`. 
As a result player makes 10 calls to the AudioManager (1 to get volume and 1 to get mute state).
You might think it is fast, but in fact those calls are IPC calls that getting result from the process responsible for the AudioSystem.

When you have more than one player instantiated (we might have up to 6) every player does 10 calls on it's player control thread.

We know that on some devices this calls might cause ANR's, so they potentially could block the player thread either.

We are going to try following changes in our fork of exoplayer:
- filter out broadcasts by the stream type in the StreamingVolumeManager
- Extract the AudioManager interface and provide default implementation as part of ExoPlayer initialization
- Use AudioManager to manipulate with audio.
- Provide a way to override the instance of the player's AudioManager though the ExoPlayer builder

In our internal implementation of builder we:
- Will make sure it accesses the AudioManager API from the single thread (always main for simplicity on first iteration). Part of problems might be coming from accessing the API from multiple different threads.
- Will update the cached values from broadcasts (use values provided in the broadcast instead of re-requesting the values.)
- We will share an instance between different players

Want to get your thoughts on that.

To me an opportunity to have your player control thread hang is scary.
I don't think you have any monitor for that in place at the moment or do you?
I don't think any metric we have will be able to detect such a hang at the moment.

**Comment by tianyif** [comment]
Hi @dryganets,

Thanks for the report! Actually, we are considering to add an opt-in `ExoPlayer.Builder` to allow the apps to enable / disable the `StreamVolumeManager`, since the device volume management is not recommended to be part of the local player. Can this solution solve your problem?

**Comment by dryganets** [comment]
Yep that would solve the problem.

**Comment by tianyif** [comment]
Thanks for the confirmation. Please expect our fix in the near future.

**Comment by tonihei** [comment]
This should be fixed in Media3 1.6.0
