### ISSUE TITLE
MediaCodecVideoRenderer: Video codec error

### ISSUE THREAD

**Issue by kirin233x** [google/ExoPlayer#10961]
### ExoPlayer Version

2.18.2

### Devices that reproduce the issue

It's only a problem on certain devices（A car device.）

### Reproducible in the demo app?

Not tested

### Reproduction steps

load the url, and the video cannot play.
https://vdse.bdstatic.com//b5ecb1f9b09e3997e9a9105249b373e2?authorization=bce-auth-v1%2F40f207e648424f47b2e3dfbb1014b1a5%2F2017-05-11T09%3A02%3A31Z%2F-1%2F%2Fa81395d4876e3b5804da397f8bd6ab7b1207c7f61d50490587c3e991887a3291

### Expected result

plays successful.

### Actual result

02-03 11:41:33.889  2043  2043 W /system/bin/hw/android.hidl.allocator@1.0-service: ashmem_create_region(32768) returning hidl_memory(0xf9f24a22b330, 32768)
02-03 11:41:33.909  2280  6624 E OMXNodeInstance: emptyBuffer(0xea6736c34740:RENESAS.DECODER.H264, 0x2 [6291456@0xea67161fc000 (0..+2087) f=10 ts=290000 fc=-1]) ERROR: InvalidState(0x8000100a)
02-03 11:41:33.909  8540  8783 E ACodec  : signalError(omxError 0x80001001, internalError -2147483648)
02-03 11:41:33.909  8540  8782 E MediaCodec: Codec reported err 0x80001001, actionCode 0, while in state 6
02-03 11:41:33.909  8540  8783 E ACodec  : [OMX.RENESAS.VIDEO.DECODER.H264] ERROR(0x8000100a)
02-03 11:41:33.910  8540  8783 E ACodec  : signalError(omxError 0x8000100a, internalError -2147483648)
02-03 11:41:33.913  8540  8782 D SurfaceUtils: disconnecting from surface 0xe433da17d010, reason disconnectFromSurface
02-03 11:41:33.914  8540  8782 E MediaCodec: Codec reported err 0x8000100a, actionCode 0, while in state 0
02-03 11:41:33.915  8540  8763 E MediaCodecVideoRenderer: Video codec error
02-03 11:41:33.915  8540  8763 E MediaCodecVideoRenderer:   java.lang.IllegalStateException
02-03 11:41:33.915  8540  8763 E MediaCodecVideoRenderer:       at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
02-03 11:41:33.915  8540  8763 E MediaCodecVideoRenderer:       at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2632)
02-03 11:41:33.915  8540  8763 E MediaCodecVideoRenderer:       at com.google.android.exoplayer2.mediacodec.t.j(Unknown Source:4)
02-03 11:41:33.915  8540  8763 E MediaCodecVideoRenderer:       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.f0(Unknown Source:44)
02-03 11:41:33.915  8540  8763 E MediaCodecVideoRenderer:       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.t(Unknown Source:71)
02-03 11:41:33.915  8540  8763 E MediaCodecVideoRenderer:       at com.google.android.exoplayer2.j1.o(Unknown Source:91)
02-03 11:41:33.915  8540  8763 E MediaCodecVideoRenderer:       at com.google.android.exoplayer2.j1.handleMessage(Unknown Source:208)
02-03 11:41:33.915  8540  8763 E MediaCodecVideoRenderer:       at android.os.Handler.dispatchMessage(Handler.java:102)
02-03 11:41:33.915  8540  8763 E MediaCodecVideoRenderer:       at android.os.Looper.loop(Looper.java:164)
02-03 11:41:33.915  8540  8763 E MediaCodecVideoRenderer:       at android.os.HandlerThread.run(HandlerThread.java:65)
02-03 11:41:33.918  8540  8763 E ExoPlayerImplInternal: Playback error
02-03 11:41:33.918  8540  8763 E ExoPlayerImplInternal:   com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.64001E, -1, null, [640, 360, 30.000227], [-1, -1]), format_supported=YES
02-03 11:41:33.918  8540  8763 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.j1.handleMessage(Unknown Source:301)
02-03 11:41:33.918  8540  8763 E ExoPlayerImplInternal:       at android.os.Handler.dispatchMessage(Handler.java:102)
02-03 11:41:33.918  8540  8763 E ExoPlayerImplInternal:       at android.os.Looper.loop(Looper.java:164)
02-03 11:41:33.918  8540  8763 E ExoPlayerImplInternal:       at android.os.HandlerThread.run(HandlerThread.java:65)
02-03 11:41:33.918  8540  8763 E ExoPlayerImplInternal:   Caused by: com.google.android.exoplayer2.video.MediaCodecVideoDecoderException: Decoder failed: OMX.RENESAS.VIDEO.DECODER.H264
02-03 11:41:33.918  8540  8763 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.video.q.a0(Unknown Source:4)
02-03 11:41:33.918  8540  8763 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.t(Unknown Source:149)
02-03 11:41:33.918  8540  8763 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.j1.o(Unknown Source:91)
02-03 11:41:33.918  8540  8763 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.j1.handleMessage(Unknown Source:208)
02-03 11:41:33.918  8540  8763 E ExoPlayerImplInternal:       ... 3 more
02-03 11:41:33.918  8540  8763 E ExoPlayerImplInternal:   Caused by: java.lang.IllegalStateException
02-03 11:41:33.918  8540  8763 E ExoPlayerImplInternal:       at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
02-03 11:41:33.918  8540  8763 E ExoPlayerImplInternal:       at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2632)
02-03 11:41:33.918  8540  8763 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.mediacodec.t.j(Unknown Source:4)
02-03 11:41:33.918  8540  8763 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.f0(Unknown Source:44)
02-03 11:41:33.918  8540  8763 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.t(Unknown Source:71)
02-03 11:41:33.918  8540  8763 E ExoPlayerImplInternal:       ... 5 more
02-03 11:41:33.919  8540  8763 E ExoPlayerImplInternal: Disable failed.
02-03 11:41:33.919  8540  8763 E ExoPlayerImplInternal:   java.lang.IllegalStateException
02-03 11:41:33.919  8540  8763 E ExoPlayerImplInternal:       at android.media.MediaCodec.native_flush(Native Method)
02-03 11:41:33.919  8540  8763 E ExoPlayerImplInternal:       at android.media.MediaCodec.flush(MediaCodec.java:2114)
02-03 11:41:33.919  8540  8763 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.mediacodec.t.flush(Unknown Source:2)
02-03 11:41:33.919  8540  8763 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.m0(Unknown Source:2)
02-03 11:41:33.919  8540  8763 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.o0(Unknown Source:32)
02-03 11:41:33.919  8540  8763 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.F(Unknown Source:24)
02-03 11:41:33.919  8540  8763 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.video.q.F(Unknown Source:17)
02-03 11:41:33.919  8540  8763 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.x0.f(Unknown Source:25)
02-03 11:41:33.919  8540  8763 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.j1.n(Unknown Source:15)
02-03 11:41:33.919  8540  8763 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.j1.o0(Unknown Source:33)
02-03 11:41:33.919  8540  8763 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.j1.k1(Unknown Source:12)
02-03 11:41:33.919  8540  8763 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.j1.handleMessage(Unknown Source:344)
02-03 11:41:33.919  8540  8763 E ExoPlayerImplInternal:       at android.os.Handler.dispatchMessage(Handler.java:102)
02-03 11:41:33.919  8540  8763 E ExoPlayerImplInternal:       at android.os.Looper.loop(Looper.java:164)
02-03 11:41:33.919  8540  8763 E ExoPlayerImplInternal:       at android.os.HandlerThread.run(HandlerThread.java:65)
02-03 11:41:33.925  2280  2624 E OMXNodeInstance: sendCommand(0xea6736c34740:RENESAS.DECODER.H264, StateSet(0), Idle(2)) ERROR: InvalidState(0x8000100a)
02-03 11:41:33.954  3614  3666 D FaceID_comm: map_type_data_callback map_type: 0  map_type_size:0  result:0

### Media

https://vdse.bdstatic.com//b5ecb1f9b09e3997e9a9105249b373e2?authorization=bce-auth-v1%2F40f207e648424f47b2e3dfbb1014b1a5%2F2017-05-11T09%3A02%3A31Z%2F-1%2F%2Fa81395d4876e3b5804da397f8bd6ab7b1207c7f61d50490587c3e991887a3291

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by microkatz** [comment]
@kirin521 
Thank you for reporting your issue. Would you be able to provide a full bugreport? If you're unable to share [bug reports](https://developer.android.com/studio/debug/bug-report) publicly, please send it to dev.exoplayer@gmail.com using a subject in the format
"Issue #10961". Please also update this issue to
indicate you've done this

**Comment by FongMi** [comment]
![image](https://user-images.githubusercontent.com/3471963/216951133-ff6f5792-56ab-4184-add8-4682989cc3cd.png)
No playblem, maybe is hardware problem, car device is not formal system.

**Comment by kirin233x** [comment]
> ![image](https://user-images.githubusercontent.com/3471963/216951133-ff6f5792-56ab-4184-add8-4682989cc3cd.png) No playblem, maybe is hardware problem, car device is not formal system.

I set fallback, and it works now.

**Comment by microkatz** [comment]
@kirin521 I'm glad that the playback is working for you? May I ask what changes did you set?

**Comment by kirin233x** [comment]
> @kirin521 I'm glad that the playback is working for you? May I ask what changes did you set?
I set the setEnableDecoderFallback in DefaultRenderersFactory
