### ISSUE TITLE
ResolvingDataSource - com.google.android.exoplayer2.ExoPlaybackException: Source error

### ISSUE THREAD

**Issue by androidplayer1** [google/ExoPlayer#10974]
### ExoPlayer Version

2.18.2

### Devices that reproduce the issue

Samsung A53
Android 13

### Reproducible in the demo app?

Not tested

### Reproduction steps

1. Create a MediaSource with Uri "app://<id>"
> In order to lazy load the media sources, no real stream uri is passed

ResolvingDataSource is initialised as seen on example.

Exoplayer will infeer the type of "app://<id>" and will result to code "0" (other)
Because of that, it is not able to find the correct Parser for it.

It works good for progressive media sources as that is a fallback for Content=0, but not for M3U8 streams

### Expected result

````kotlin
        private fun createExoMediaSource(
            context: Context,
            media: Media,
            resolveStream: (Media) -> MediaStream
        ): MediaSource {
            val resolvingDataSource = ResolvingDataSource.Factory(
                DefaultDataSource.Factory(context)
            ) { dataSpec ->
                val stream = media.stream ?: resolveStream(media)

                dataSpec
                    .buildUpon()
                    .setUri(stream.uri)
                    .setHttpRequestHeaders(stream.headers ?: emptyMap())
                    .build()
            }

            val factory = DefaultMediaSourceFactory(resolvingDataSource)

            return factory.createMediaSource(MediaItem.fromUri(media.uri))
        }
````

### Actual result

````kotlin
E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:637)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:607)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (FlvExtractor, FlacExtractor, WavExtractor, FragmentedMp4Extractor, Mp4Extractor, AmrExtractor, PsExtractor, OggExtractor, TsExtractor, MatroskaExtractor, AdtsExtractor, Ac3Extractor, Ac4Extractor, Mp3Extractor, AviExtractor, JpegExtractor) could read the stream.
        at com.google.android.exoplayer2.source.BundledExtractorsAdapter.init(BundledExtractorsAdapter.java:92)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1017)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
        at java.lang.Thread.run(Thread.java:1012)
````

### Media

Any source from
https://gist.github.com/Fazzani/8f89546e188f8086a46073dc5d4e2928

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by icbaker** [comment]
ExoPlayer currently requires the type of the stream (HLS, DASH or progressive (or something else)) to be known before any loading can happen. As you've seen `DefaultMediaSourceFactory` tries to infer this from the URI (looking at the 'file extension') and if it doesn't see a recognised suffix it falls back to using `ProgressiveMediaSource`. If you know a particular item is HLS before you resolve the URI then you can pass [`MimeTypes.APPLICATION_M3U8`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/util/MimeTypes.html#APPLICATION_M3U8) to [`MediaItem.Builder.setMimeType(String)`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/MediaItem.Builder.html#setMimeType(java.lang.String)).

If you don't know the type of the stream before you try and load it then this is currently not supported by ExoPlayer. Support is tracked by https://github.com/google/ExoPlayer/issues/3165.

**Comment by androidplayer1** [comment]
> ExoPlayer currently requires the type of the stream (HLS, DASH or progressive (or something else)) to be known before any loading can happen. As you've seen `DefaultMediaSourceFactory` tries to infer this from the URI (looking at the 'file extension') and if it doesn't see a recognized suffix it falls back to using `ProgressiveMediaSource`. If you know a particular item is HLS before you resolve the URI then you can pass [`MimeTypes.APPLICATION_M3U8`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/util/MimeTypes.html#APPLICATION_M3U8) to [`MediaItem.Builder.setMimeType(String)`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/MediaItem.Builder.html#setMimeType(java.lang.String)).
> 
> If you don't know the type of the stream before you try and load it then this is currently not supported by ExoPlayer. Support is tracked by #3165.

The mime type of stream is not known before I ask the server for it, so this is not an option for my case. It seems like bad engineering to not have in mind at all the lazy loading of streams.

I basically will continue for now using the "solution" provided on the Issue mentioned by you (https://github.com/androidx/media/issues/17)

Looks like the example posted by OP works fine for my case.
