### ISSUE TITLE
How to download Hls AES content.

### ISSUE THREAD

**Issue by spuday90** [google/ExoPlayer#10973]
Hi,
In our application we are playing AES content  when trying to download the same,  DownloadHelper.prepare throwing 
onPrepareError()
with exception class com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException
Response code 401.

Kindly help

**Comment by tianyif** [comment]
Hi @spuday90,

Unfortunately we can't answer this questions with insufficient information. Could you please provide complete information as requested in the question template. The template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/question.md). I'm closing this issue for now. You're welcome to create a new issue based on the above template, and we will be helping you from there.
