### ISSUE TITLE
Blank screen with audio in lastest version(when play video with audio)

### ISSUE THREAD

**Issue by Agono0** [google/ExoPlayer#10979]
I am new to exoplayer, and when i try to play a video from url(https://storage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4)
Exoplayer play only audio with blank screen.
Here's my code:
main.xml
```xml
<LinearLayout
		android:layout_width="match_parent"
		android:layout_height="match_parent"
		android:orientation="vertical"
		app:layout_behavior="@string/appbar_scrolling_view_behavior">
		<com.google.android.exoplayer2.ui.StyledPlayerView
			android:id="@+id/playerView"
			android:layout_width="match_parent"
			android:layout_height="match_parent"
			android:padding="8dp"
			android:orientation="horizontal"
			app:show_shuffle_button="true"
			app:show_subtitle_button="true"
			app:show_timeout="0" />
	</LinearLayout>
```
and here's my java code:
```java
ExoPlayer player = new ExoPlayer.Builder(MainActivity.this).build();

playerView.setPlayer(player);

MediaItem mediaItem = MediaItem.fromUri("https://storage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4");

player.setMediaItem(mediaItem);

player.prepare();

player.setPlayWhenReady(true);

player.play();
```

And this is the result:
![20230212_140915](https://user-images.githubusercontent.com/100796146/218310199-4f265479-0d32-479c-885b-93fe0cf3d680.jpg)

**Comment by marcbaechinger** [comment]
Please refer to [the dev guide](https://exoplayer.dev/hello-world.html) and the [demo app](https://github.com/google/ExoPlayer/tree/release-v2/demos/main/src/main/java/com/google/android/exoplayer2/demo) also.

Best is to add 

```
player.addAnalyticsListener(new EventLogger());
```

and then [examine the output of the logs](https://exoplayer.dev/debug-logging.html).

If this still doesn't help, paste the output of the logs here.

**Comment by Agono0** [comment]
After enable `EventLogger` &`ExoPlayerImpl` didn't find any useful text in logcat...
It's just say `is Playing`
I check R files , and it's looks fine.
But weird thing is after run app, the layout become `recyclerview`:
![Screenshot_20230214-031708_exoplayer](https://user-images.githubusercontent.com/100796146/218613312-50dfb1f0-cd3c-4d52-a854-da2b4533b47c.jpg)

Why this happens?

**Comment by Agono0** [comment]
This is error from my side...
Thanks for help :)
