### ISSUE TITLE
Memory leak when playing local video

### ISSUE THREAD

**Issue by yummyChina** [google/ExoPlayer#10987]
In the most simple demo

create player :

new Exoplayer.Builder().build

setMediaItem(MediaItem.from(videoPath))

styledvideoview set player 

prepare 
play

with local mp4 file play

the memeory use keep growthing by the time, and crash in the future

**Comment by tonihei** [comment]
ExoPlayer should stop acquiring new memory even in cases where playback can't start. Can you reproduce this problem with a specific mp4 file only? If so, can you share the file with us? Either attach it here or send an email to dev.exoplayer@gmail.com with "Issue #10987" in the issue title (and comment here if you've done that).
