### ISSUE TITLE
Getting live window time of HLS live stream

### ISSUE THREAD

**Issue by wishygupta** [google/ExoPlayer#10983]
I have a live HLS Stream.
Is there any API which can help me get the current live window time of Live Stream

**Comment by marcbaechinger** [comment]
I'm not sure what you mean with `current live window time`.

You can get the duration of the current live window as follows:

```
Timeline timeline = player.getCurrentTimeline();
timeline.getWindow(player.getCurrentMediaItemIndex(), new Timeline.Window()).getDurationMs();
```

The position within this window is the current position:

```
player.getCurrentPosition();
```
