### ISSUE TITLE
Is it possible to start a live stream (DASH or HLS) at a particular presentation date time?

### ISSUE THREAD

**Issue by baiqindotfubotv** [google/ExoPlayer#10985]
The problem I want to solve is to avoid a frame jump if user pauses and resumes a live stream. The live manifest for both DASH and HLS has a short live window which is 2 minutes. Let's say initially the user plays at live edge, we build a MediaItem as such:

```
val videoUrl1 = "https://www.live.com?offsetFromLiveSeconds=0.mpd"
val mediaItem = MediaItem.Builder().setUri(videoUrl1).build()
```

Let's assume user pauses for 10 minutes, then clicks resume, then we need to build a new url:

```
val videoUrl2 = "https://www.live.com?offsetFromLiveSeconds=600.mpd"
val mediaItem = MediaItem.Builder().setUri(videoUrl2).build()
```

The issue is that user will always see a frame jump after resuming because for ExoPlayer videoUrl1 and videoUrl2 are two unrelated manifest urls. What I think makes sense to do is remember the PDT of videoUrl1 when user pauses and when we starts playing videoUrl2 we set the initial PDT. But I cannot find exoPlayer api to do that. What I am looking for is basically something like this:

```
val videoUrl2 = "https://www.live.com?offsetFromLiveSeconds=600"
val mediaItem = MediaItem.Builder().setUri(videoUrl2).setInitialPDT(pdt).build()
```

Is this supported by latest ExoPlayer r2.18.2?

**Comment by tonihei** [comment]
If I understand your issue correctly, this feature request is already tracked by https://github.com/google/ExoPlayer/issues/9122.

**Comment by baiqindotfubotv** [comment]
> If I understand your issue correctly, this feature request is already tracked by #9122.

Yes they are related. Since [#9122](https://github.com/google/ExoPlayer/issues/9122) is still open can I assume there is no good solution with latest version of ExoPlayer?

**Comment by tonihei** [comment]
You can workaround this issue by modifying the default start position of the stream. I posted a way to do this on #9122.
