### ISSUE TITLE
can parse the frame rate of video when ts or trp file?

### ISSUE THREAD

**Issue by liangqiujuan** [google/ExoPlayer#10982]
when play a .mp4 file we can see the fps parameter in eventlog:

 D/EventLogger: downstreamFormat [eventTime=0.08, mediaPos=0.00, window=1, period=1, id=1, mimeType=video/avc, res=3840x2160, fps=29.970028]

D/EventLogger: videoInputFormat [eventTime=0.08, mediaPos=0.00, window=1, period=1, id=1, mimeType=video/avc, res=3840x2160, fps=29.970028]

But when play a .ts or trp file, there is no fps parameter.  whether can parse parameter fps of  .ts or .trp file?  Whether there are plans to support it in the future?

D/EventLogger: downstreamFormat [eventTime=2.24, mediaPos=0.00, window=5, period=5, id=1/256, mimeType=video/hevc, res=3840x2160]

D/EventLogger: videoInputFormat [eventTime=2.28, mediaPos=0.00, window=5, period=5, id=1/256, mimeType=video/hevc, res=3840x2160]

**Comment by tonihei** [comment]
Do you have any indication that the frame rate is available in these files? It might just be unknown. See also https://github.com/google/ExoPlayer/issues/4831 where this has been asked before. 

If you think it can be parsed from the file, feel free to send a PR to add this functionality (most likely in [H265Reader.java](https://github.com/google/ExoPlayer/blob/release-v2/library/extractor/src/main/java/com/google/android/exoplayer2/extractor/ts/H265Reader.java)).
