### ISSUE TITLE
Synchronize playback across multiple devices

### ISSUE THREAD

**Issue by AlicLee** [google/ExoPlayer#10990]
I have two Android programs(use exoplayer) playing the same mp4 file, and I am committed to keeping the playback time difference between the two programs within 16ms. But when I call the exact seekTo, I find that the difference between the two player is between 200-400ms, and I try other seekParameters, but the effect is not very good. Is there any better solution?

**Comment by AlicLee** [comment]
In addition, I use the onVideoFrameAboutToBeRendered method to obtain the playback time of the two programs.

**Comment by tonihei** [comment]
> two Android programs

Do you mean apps, or players within one app?

> But when I call the exact seekTo

The seek is exact in the sense of starting at exactly the right frame. It doesn't have any influence on the actual time it's displayed and when the players start playing. 

> Is there any better solution?

To synchronize the two players, you need to share the same media clock across both players. This sounds very hard to do if multiple apps are involved, but is doable with multiple Players in a single app. One of the player's needs to override its `MediaCodecAudioRenderer` to return the playback position of the second player's renderer from `getPositionUs`. You also need to align other state changes (e.g. calling `pause()` if one player stops playing). This is relatively hard at the moment as we don't have an out-of-the-box solution to synchronize multiple players.

**Comment by AlicLee** [comment]
Thank you for your reply. I mean that two identical Android programs are on different phones. I use the socket to make the two phones play almost at the same time (after they are ready), and then use the onVideoFrameAboutToBeRendered method to get the playback time of each frame, and then use the socket to synchronize the playback time of the two phones. Taking one mobile phone as a reference, the other mobile phone tracks the playback time of the other mobile phone through the exact seek to, but the exact seek to causes a large delay. The initial playback delay is 60-100ms. When I call the exact seek to multiple times, the delay increases to 200ms to 400ms. Can multiple mobile phones synchronize the time of two players through the synchronization of pts? I feel that sometimes the clocks of the two players are the same, but after a while the clocks are different. Why? Is it because of frame loss or frame skipping?

**Comment by AlicLee** [comment]
Hello, developer, I learned from searching issuse and some online materials that exolayer is synchronized based on sound. But in videos without sound, the getPositionUs of override MediaCodecAudioRenderer always return 0. So I tried to modify the processOutputBuffer of MediaCodecVideoRenderer, and passed in seekPts as the pts time to synchronize. The effect I want is that the pts time of the two videos is the same, However, the time gap between the two videos has not been shortened. Here is the code I added
```
if (seekPts != -1) {
            long earlyUs = (long) ((presentationTimeUs - seekPts) / playbackSpeed);
            if (isStarted) {
                // Account for the elapsed time since the start of this iteration of the rendering loop.
                earlyUs -= elapsedRealtimeNowUs - elapsedRealtimeUs;
            }
            if (earlyUs < 0) {
                boolean treatDroppedBuffersAsSkipped = joiningDeadlineMs != C.TIME_UNSET;
                if (shouldDropBuffersToKeyframe(earlyUs, elapsedRealtimeUs, isLastBuffer)
                        && maybeDropBuffersToKeyframe(positionUs, treatDroppedBuffersAsSkipped)) {
                    return false;
                }else{
                    skipOutputBuffer(codec, bufferIndex, presentationTimeUs);
                    updateVideoFrameProcessingOffsetCounters(earlyUs);
                    return true;
                }
            } else {
                long releaseTimeNs = System.nanoTime();
                notifyFrameMetadataListener(presentationTimeUs, releaseTimeNs, format);
                if (Util.SDK_INT >= 21) {
                    renderOutputBufferV21(codec, bufferIndex, presentationTimeUs, releaseTimeNs);
                } else {
                    renderOutputBuffer(codec, bufferIndex, presentationTimeUs);
                }
                updateVideoFrameProcessingOffsetCounters(earlyUs);
                seekPts = -1;
                return true;
            }
        }
```
See MediaCodecVideoRender.zip for the complete code,Finally, how can I achieve the pts synchronization of video? 
[MediaCodecVideoRenderer.zip](https://github.com/google/ExoPlayer/files/10783481/MediaCodecVideoRenderer.zip)

**Comment by tonihei** [comment]
Thanks for the clarification! 

Repeated seeking won't work because it introduces new delays every time you call seekTo. Just adjusting the timestamp of the renderer as suggested in last comment won't help either to synchronize playback across two devices.

If the streams are live streams, you could easily achieve your goal by setting the same live `targetOffsetMs` in the `MediaItem.LiveConfiguration` to make sure they automatically converge at the same playback position. 

For non-live streams, this setting isn't available out of the box, but you can trick the player into believing it's a live stream by giving it the real-time offset between the stream and unix epoch (this needs to be synced between the devices to get the same offset), and also a target live offset of `0` to enable automatic position adjustment to the same position. See the code below, which I used to make this work:

```
long playbackStartTimeSinceUnixEpochMs = /* set the same start time since Unix epoch for both devices */;
MediaSource mediaSource = /* create your regular MediaSource */;
MediaSource pretendLiveSource = new WrappingMediaSource(mediaSource) {
  @Override
  protected void onChildSourceInfoRefreshed(Timeline newTimeline) {
    Timeline pretendLiveTimeline = new ForwardingTimeline(newTimeline) {
      @Override
      public Window getWindow(int windowIndex, Window window,
          long defaultPositionProjectionUs) {
        super.getWindow(windowIndex, window, defaultPositionProjectionUs);
        // Tell the player this is a live stream and always keep a live offset of zero.
        window.isLive = true;
        window.isDynamic = true;
        window.liveConfiguration = new MediaItem.LiveConfiguration.Builder().setTargetOffsetMs(0).build();
        // Configure the real-time playback start time.
        window.windowStartTimeMs = playbackStartTimeSinceUnixEpochMs;
        // Attempt to start playback close to the intended playback position.
        window.defaultPositionUs = Util.msToUs(Math.max(0, System.currentTimeMillis() - playbackStartTimeSinceUnixEpochMs));
        return window;
      }
    };
    refreshSourceInfo(pretendLiveTimeline);
  }
};
player.setMediaSource(pretendLiveSource);
```

**Comment by AlicLee** [comment]
My application scenario is non-live streams. Thank you for your response. I will try your solution tomorrow

**Comment by AlicLee** [comment]
Hello, developer, your solution can synchronize two videos, but if there are other status changes, such as seek to, or two videos are not played at the same time (for example, one video is played first, the other is played later), how should I synchronize the two players? And if I want to correct the gap between the two videos during playing, does this method seem to be impossible? Is there a flexible way to synchronize two videos?

**Comment by tonihei** [comment]
> but if there are other status changes, such as seek to

Every call to `seekTo` overrides the target "live" offset to match the seek position. To make this work, you probably need to ignore these overrides by providing a custom `LivePlaybackSpeedControl` to the player. You can wrap `DefaultLivePlaybackSpeedControl` and just not forward calls to `setTargetLiveOffsetOverrideUs`.

> or two videos are not played at the same time

If you set the same value for `playbackStartTimeSinceUnixEpochMs` on both players, they should automatically play at the same position, even if you start later. 

> And if I want to correct the gap between the two videos during playing, does this method seem to be impossible?

The adjustment takes a while to work. If you set the same `windowStartTimeMs` in both players, the playback position will slowly correct itself by playing at a lower of higher speed (max 3% difference by default). This means it could easily take a minute or so until to reaches the intended position. You can make the adjustment faster by changing the min/max allowed speeds in `LiveConfiguration.Builder` or by configuring the `DefaultLivePlaybackSpeedControl` with different values. See https://exoplayer.dev/live-streaming.html#playback-speed-adjustment for more details.

Note that this is getting very advanced and we won't be able to provide 1:1 app support to make this work for your case. I think the pointers I provided here should put you in the right direction already.

**Comment by AlicLee** [comment]
I tried your suggestion, but I don't think it is a good way to do so. First, the time of two playback devices needs to be synchronized accurately (but it is easy to have problems on devices without network connection). Second, it is not allowed to play in cycles. Third, setting the same time also needs to be very accurate (it needs to be no more than System. currentTimeMillis(), and no less than the current time minus the playback time), The last point is that the adjustment takes a while to work is not effective immediately. I think skipOutputBuffer is a better choice. But I don't understand why skipOutputBuffer doesn't take effect in processOutputBuffer, and the two videos still maintain the same pts time gap. Can you give me some suggestions in this regard? Thank you very much

**Comment by tonihei** [comment]
> First, the time of two playback devices needs to be synchronized accurately (but it is easy to have problems on devices without network connection)

This needs to be solved by your app, e.g. by syncing the clock of the devices to each other (or calculating the diff).

> Second, it is not allowed to play in cycles.

I assume you mean repeat modes? You need to refresh the Timeline in this case with a new offset to ensure the position adjusts correctly.

> Third, setting the same time also needs to be very accurate

Yes, this is really the whole point, right? You want both devices to play at the same position, so you need to provide an accurate reference time which can be used to align the playback positions. 

> I think skipOutputBuffer is a better choice

You are right, for fast convergence of the position to its target, it's better to skip some samples instead of slowly adjusting the speed. However, this needs to be done by an internal seek operation that seeks forward in the already available buffer if possible. This isn't easily done I'm afraid, but you can file a new feature request to add an option to LivePlaybackSpeedControl to skip forward for faster adjustment.

**Comment by tonihei** [comment]
I'm closing this issue now because the original question of how to sync playbacks across devices has been answered.
