### ISSUE TITLE
Adding additional format support to ExoPlayer FFMpeg extension?

### ISSUE THREAD

**Issue by OxygenCobalt** [google/ExoPlayer#10993]
I'm considering patching ExoPlayer's FFMpeg extension to add support for more niche progressive audio formats, such as WAVPack or Monkey's Audio. Both of these formats have decoding support in FFMpeg, however they have their own container formats that aren't parsed by ExoPlayer. Moreover, they have no native `MediaCodec` support, which makes these formats sensible only in the context of the FFMpeg extension.

I would like to know the following about this:
1. What would be the general steps to add these additional formats? From what I already know, I would need to write a parser for the container, modify the native code that plugs into FFMpeg to allow access to the decoders I want, and add the required mime type checks to set up the decoder. Could you point to more specific places in the codebase that I should modify?
2. How upstreamable is this? For example, if I could scope the container parsers to the FFMpeg extension, I may try to create a PR. Otherwise, I'd imagine that I will be unable to upstream the changes, as without native `MediaCodec` support, the container parsers I want to write are effectively dead code.

**Note:** This is not a feature request. I am entirely planning to work on this myself.

**Comment by tonihei** [comment]
> What would be the general steps to add these additional formats?

The decoding capabilities of the Ffmpeg extension depend on how you configure the Ffmpeg during build time (see https://exoplayer.dev/supported-formats.html#ffmpeg-extension). I assume you already know this given the question. If you want to add other formats, you probably need to modify [this mapping](https://github.com/google/ExoPlayer/blob/3a654c1f54e19f261e717282fe42168b38d7e96c/extensions/ffmpeg/src/main/java/com/google/android/exoplayer2/ext/ffmpeg/FfmpegLibrary.java#L115). Other modifications are only needed if the formats need special initialization data or similar. If there is a clear mapping from ExoPlayer-defined MIME types to an Ffmpeg decoder name, then we are happy to accept PRs for this part. In case this isn't feasible, we are also happy to accept a PR that makes the mapping injectable, so you don't have to fork the extension (e.g. a static `registerCodecName(String mimeType, String codecName`). 

The container formats are probably more complicated to support and we generally accept only relevant container parsers. The fact that MediaCodec doesn't support a format is not necessarily a blocker, more the general usefulness of a container. It's fairly easy to inject custom extractors into ExoPlayer, so you can easily keep them in your code once you have them without upstreaming them.

**Comment by OxygenCobalt** [comment]
Yeah, the formats I'm trying to do have their own containers (and mime types) that I would have to implement myself since they are not used with other formats (They don't even have MKA atoms, I think). What is the API I should use to do that @tonihei?

**Comment by OxygenCobalt** [comment]
Figured out what I'd need to do to build an extractor. I could also theoretically try to hook into FFMpeg's container parsing with some kind of `FFMpegExtractor`, but I'd have to look further into that.
