### ISSUE TITLE
AV Sync issue in DASH Stream

### ISSUE THREAD

**Issue by mayurk2** [google/ExoPlayer#10996]
### ExoPlayer Version

2.18.3

### Devices that reproduce the issue

All devices.
Tested on Redmi Note 9 Pro, Samsung M32.

### Reproducible in the demo app?

Yes

### Reproduction steps

1. I saved the attached stream in some folder on Phone.
2. Hard coded the path in "media.exolist.json".
3. Played the media and observed AV sync.

### Expected result

Media should play with correct AV sync.

### Actual result

AV sync is not present.

### Media

https://drive.google.com/file/d/156XrRCy0Nxk6_u1fgQa9JVEExy3JeLRk/view?usp=sharing 

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by tonihei** [comment]
As far as I can see, your source media is simply not aligned. You can check yourself by listening to the audio-only file, check the time of the initial conversation ("You are a jerk Tom..."), it starts at 00:23 and ends at 00:27, and then compare the the video-only file where it still shows the previous scene between 00:23 and 00:27.

**Comment by mayurk2** [comment]
@tonihei Event I thought that is the issue first.
I saw that there is a difference in first PTS of audio and video when I printed the timestamp value here - https://github.com/google/ExoPlayer/blob/f72ca8338399c9e3c19e73fc0779f24baff14d35/library/extractor/src/main/java/com/google/android/exoplayer2/extractor/mp4/FragmentedMp4Extractor.java#L1057

But I later saw that VLC and Shaka player are able to play this content correctly and AV sync issue was not observed.

Is it possible to provide more info on why is this issue happens only with Exoplayer?

**Comment by mayurk2** [comment]
@tonihei From the VLC source code here - https://code.videolan.org/videolan/vlc/-/blob/master/modules/demux/mp4/mp4.c#L4749
It looks like VLC is using separate PTS and DTS values. The i_composition_time_offset (sampleCompositionTimeOffset in Exoplayer) is added only to PTS.
But Exoplayer does not have separate PTS and DTS values. Maybe that is resulting in AV sync issue?

**Comment by mayurk2** [comment]
@tonihei another observation:
I played the original video on YouTube - https://youtu.be/41hv2tW5Lc4
The dialogue starts before the the people show-up on the video - i.e. at ~0:24s.


I played audio and video separately on "QuickTime Player". 
In audio file, at 00:29 you can hear the dialogue "_..just want to be **awesome** in space_".
If you play the video file, you can make out that the actor saying "_**awesome**_" at 00:29.

Hence I think there is no AV sync issue in source file.

Can you please re-open the ticket for analysing/debugging this? (I am not able to re-open :( )

**Comment by tonihei** [comment]
Yes, you are right about the sync issue not being present in the source files. I got confused by the dialogue starting before you can see the people talking.

**Comment by tonihei** [comment]
The reason for the sync issue is that your video file defines an edit list with the correct offset, but also a duration. Edit lists with duration are ignored by ExoPlayer's fMP4 extractor (see [here](https://github.com/google/ExoPlayer/blob/f72ca8338399c9e3c19e73fc0779f24baff14d35/library/extractor/src/main/java/com/google/android/exoplayer2/extractor/mp4/FragmentedMp4Extractor.java#L1018)) because they are very uncommon and not really useful for segmented DASH playback. In your case, the edit list wants to move the entire timeline, and should use a duration of 0. If I force this duration of the edit list to be zero, everything works as expected. I'll leave it as "bad media" because the edit list should indicate 0 as a duration if I see it correctly.

**Comment by mayurk2** [comment]
@tonihei Thanks.
1. Do we have any plans to support edit list with duration?
2. Is edit list with duration against the spec? Or just that it is not supported by Exoplayer? (This info is useful for me to check with this content provider and make any changes in encoding or creating mp4 stream.)

**Comment by mayurk2** [comment]
@tonihei I checked the edits duration and it is matching with the track duration. I think this is also a valid case to be handled.
Raised a PR - https://github.com/google/ExoPlayer/pull/11010
