### ISSUE TITLE
Events for AudioFocus Loss

### ISSUE THREAD

**Issue by haydenkaizeta** [google/ExoPlayer#11009]
### [REQUIRED] Use case description
I want to report statistics around audio focus loss in my application. It seems I cannot observe the loss without overriding ExoPlayer's handling of audio focus.

I saw https://github.com/google/ExoPlayer/issues/10293 but I do not understand why `onPlaybackSuppressionReasonChanged` exists but does not account for permanent loss of focus.

### Proposed solution
Expose a listener/event to listen to all audio focus events, much like `onPlaybackSuppressionReasonChanged`.

### Alternatives considered
Set `handleAudioFocus` to false and handle in our application. This seems inefficient as ExoPlayer handles the audio focus well.

There is no other way to observe the audio focus to my knowledge.

**Comment by icbaker** [comment]
Permanent loss of audio focus results in the `playWhenReady` state of the `Player` changing, and this is reported through [`Player.Listener.onPlayWhenReadyChanged`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/Player.Listener.html#onPlayWhenReadyChanged(boolean,@com.google.android.exoplayer2.Player.PlayWhenReadyChangeReasonint)) with `reason = PLAY_WHEN_READY_CHANGE_REASON_AUDIO_FOCUS_LOSS`.

It sounds like that will give you the callback you're looking for?

**Comment by haydenkaizeta** [comment]
@icbaker yes this is exactly what I need, thank you!
