### ISSUE TITLE
How to set video center screen in case player streaming not running in full screen.

### ISSUE THREAD

**Issue by kinhdang** [google/ExoPlayer#1100]
Hi all !

How to set video center screen in case player streaming not running in full screen.

Thanks.

![untitled_](https://cloud.githubusercontent.com/assets/9839084/12079677/44e4aea6-b274-11e5-972f-6f4fa779bef9.png)

**Comment by ojw28** [comment]
ExoPlayer just renders into the `Surface` (typically a `SurfaceView`) provided by the application. How that `SurfaceView` is laid out in an application is the application developer's responsibility.
