### ISSUE TITLE
VP9 extension compile bug

### ISSUE THREAD

**Issue by menscikov** [google/ExoPlayer#11013]
### ExoPlayer Version

2.18.3

### Devices that reproduce the issue

MacBook Pro 2013

### Reproducible in the demo app?

Yes

### Reproduction steps

1. Build VP9 extension

### Expected result

Compile without errors.

### Actual result

After i use:
```
cd ${VP9_MODULE_PATH}/jni && \
ln -s "$LIBVPX_PATH" libvpx && \
./generate_libvpx_android_configs.sh
```

I get this error in the Terminal:
`clang: error: the clang compiler does not support '-march=armv7-a'`

### Media

No media is needed.

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by icbaker** [comment]
What version of `clang` and `make` are you using? In my (linux) development environment:

```shell
$ which clang
/usr/bin/clang
$ clang --version
Debian clang version 14.0.6
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
$ which make
/usr/bin/make
$ make --version
GNU Make 4.3
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by menscikov** [comment]
```
% which clang
/usr/bin/clang
% clang --version
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: arm64-apple-darwin22.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
% which make
/usr/bin/make
% make --version
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.
This program built for i386-apple-darwin11.3.0
```

**Comment by christosts** [comment]
Have you tried to continue building the extension? Despite the error, the script does produce the android config files that are needed to build the shared objects in the next steps.

**Comment by menscikov** [comment]
Hello, it's not a fatal error so it's continues to build. I can build it successfully.

The question is about `clang: error: the clang compiler does not support '-march=armv7-a'` error in the console.
So it looks like that VP9 extension will work on 3 platforms, except `armv7-a` according to the log.

**Comment by christosts** [comment]
The native libraries should be built from the NDK's toolchain on the next step of the instructions. I'm testing on a macOs 12.6.3 with `Apple clang version 14.0.0` and see the error too. However, the actual `.so` is built from the NDK and the shared objects for armv7a are under `{exoplayer_checkout_dir}/extensions/vp9/src/main/libs/armeabi-v7a`.

Please let us know if you have any problems running the extension on a device.

**Comment by menscikov** [comment]
Hello, thank you.
I haven't tested VP9 extension on that platform, just wanted to know is it ok to see this error in the console.
I'll try to test on the `armv7-a` device later if I get a chance.

**Comment by christosts** [comment]
I'll close the issue, feel free to re-open if things don't work as expected.
