### ISSUE TITLE
Not able to cast some of client provided m3u8 (Version 5) video URL

### ISSUE THREAD

**Issue by abhayJangde92** [google/ExoPlayer#11018]
### ExoPlayer Version

2.18.3

### Devices that reproduce the issue

All Android Device.

### Devices that do not reproduce the issue

All Supported Version

### Reproducible in the demo app?

Yes

### Reproduction steps

1. Try adding below url in sample app and try to cast on Android TV / chromcast device.

 new MediaItem.Builder()
         .setUri("https://content.uplynk.com/ext/fc1d615459a64336b5ccdc137ffeddc6/01GK5YWXVFSQMNQ30ASXB6XNEG.m3u8")
            .setMediaMetadata(new MediaMetadata.Builder().setTitle("Canela URL").build())
            .setMimeType(MIME_TYPE_HLS)
            .build());

### Expected result

Video should be cast on the TV successfully.

### Actual result

Video is not playing on the TV.

### Media

URL - https://content.uplynk.com/ext/fc1d615459a64336b5ccdc137ffeddc6/01GK5YWXVFSQMNQ30ASXB6XNEG.m3u8

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by marcbaechinger** [comment]
I don't  think we can help much with that I'm afraid.  I understand the stream works with ExoPlayer but it fails on the cast device. You need to debug this on the cast device I'm afraid.

**Comment by abhayJangde92** [comment]
Thanks @marcbaechinger for quick reply.

This is not the device specific issue you can reproduce it on every device (Android phone + any cast receiver). 

Could you please help me understand that is there any specific version of m3u8 file that we can cast.

**Comment by marcbaechinger** [comment]
According to your report, the playback problems seem to be specific to the cast device as you report. So I think the device specific tag is ok.

> Could you please help me understand that is there any specific version of m3u8 file that we can cast.

The biggest difference between Chromecast devices and Android is that on a Chromecast device the recevier app is written as a webapp running in a browser. So the server that delivers adaptive media generally needs to support CORS to please the browser and it's same-origin policy. 

Acting as an internet user I find this document about what is supported by cast devices: https://developers.google.com/cast/docs/media

**Comment by abhayJangde92** [comment]
fixed the issue.

Solution - Created new application (custom receiver) on Google Cast SDK Developer Console and used that key in my project.

Use this receiver application URL - https://googleads.github.io/googleads-ima-cast/client_receiver/player.html
if you want more UI customization create your own web page.
