### ISSUE TITLE
CastPlayer - java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by vitaliygerasymchuk** [google/ExoPlayer#11021]
### ExoPlayer Version

2.18.3

### Devices that reproduce the issue

OnePlus 7 running Android 11

### Reproducible in the demo app?

Yes

### Reproduction steps

Run cast demo.
Connect to the device with the cast capability (Tv, Speaker, reproduced on both)

### Expected result

The Cast session is started succesfuly 

### Actual result

```
java.lang.IllegalArgumentException: The given region must intersect with the Bitmap's dimensions.
  at androidx.palette.graphics.Palette$Builder.setRegion(Palette.java:733)
  at com.android.systemui.statusbar.notification.MediaNotificationProcessor.generateArtworkPaletteBuilder(MediaNotificationProcessor.java:332)
  at com.android.systemui.media.MediaDataManager.computeBackgroundColor(MediaDataManager.kt:475)
  at com.android.systemui.media.MediaDataManager.loadMediaDataInBg(MediaDataManager.kt:356)
   at com.android.systemui.media.MediaDataManager.access$loadMediaDataInBg(MediaDataManager.kt:89)
   at com.android.systemui.media.MediaDataManager$loadMediaData$1.run(MediaDataManager.kt:241)
   at android.os.Handler.handleCallback(Handler.java:938)
   at android.os.Handler.dispatchMessage(Handler.java:99)
   at android.os.Looper.loop(Looper.java:233)
   at android.os.HandlerThread.run(HandlerThread.java:67)
```

### Media

The issues is reproducible in the Exo Cast Demo application. 

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by marcbaechinger** [comment]
Thanks for reporting. 

Can you give us some more details how the stack trace above is related to the ExoPlayer library or the `CastPlayer`? I'm asking because the classes involved in the stack trace above look related to system UI and a notification while to the best of my knowledge the cast demo app of the library does not have a notification by default. 

How do you create the notification when you see the stack trace above and how does this related to the `CastPlayer` or the Media3 library in general? Did you modify the Cast demo app?

**Comment by vitaliygerasymchuk** [comment]
@marcbaechinger
I didn't modify the demo app. 
Media session has it's own notification:
![image](https://user-images.githubusercontent.com/31439136/221559880-82841991-5ef9-4700-a10d-0803e169a01c.png)
And as you can see - it definitely uses Palette library to colorise itself. 

Please, note that at the same time - different demo app on the same device creates this kind of Media Session notification successfully.  So having this in mind - i assume that the error is inside CastPlayer.

**Comment by vitaliygerasymchuk** [comment]
@marcbaechinger additional comment. I tried out your demo application (unmodified) on a different device OnePlus 8 running Android 12 - and everything worked as expected. I hope this information will help you.

**Comment by marcbaechinger** [comment]
The screenshot shows a notification from `Google Play Music` playing on a phone speaker. I don't think this is related to the `CastPlayer` of the cast demo app in any way. 

As far as I know the cast demo app does not create a session itself. It may be that the cast SDK does this in the background. 

The cast options that are used by default are in `DefaultCastOptionsProvider`. You may want to disable the cast SDK to create a session by adding `.setCastMediaOptions(new CastMediaOptions.Builder().setMediaSessionEnabled(false).build())` and provide your own options provider in the manifest. If the error goes away when disabling the session, this is a problem with the Cast SDK and the session/notification it creates under the hood. 

Personally, I'd recommend to disable the cast session and create your own but this is an opinionated choice of mine. If you prefer the cast SDK doing that this is a valid choice. I'm not sure whether I can help you fix this Cast SDK related problem in such a case though.

```
return new CastOptions.Builder()
        .setResumeSavedSession(false)
        .setEnableReconnectionService(false)
        .setCastMediaOptions(new CastMediaOptions.Builder().setMediaSessionEnabled(false).build())
        .setReceiverApplicationId(APP_ID_DEFAULT_RECEIVER_WITH_DRM)
        .setStopReceiverApplicationWhenEndingSession(true)
        .build();
```

**Comment by vitaliygerasymchuk** [comment]
Thanks @marcbaechinger. I will try out your suggestion!

**Comment by vitaliygerasymchuk** [comment]
@marcbaechinger disabling media session via the CastOptions.Builder helped to resolve the system UI crash. I'll probably go this direction in order not to depend on too many libraries. Thank you for your help!

**Comment by luckygoyal-bitmovin** [comment]
FYI, raised this with Google Cast SDK team as well. 
https://issuetracker.google.com/issues/278918062
