### ISSUE TITLE
How to custom ExoPlayer to handle Partial Content 206?

### ISSUE THREAD

**Issue by chientrm** [google/ExoPlayer#11022]
I know this is not supposed to be the correct way to consume stream.
The content length should be determined by ExoPlayer and the server is about to stream the whole file.
But, I don't trust my client to handle to the stream efficiently and not to abuse.
Is there a way that I can custom ExoPlayer to handle the `Range` header correctly?

**Comment by christosts** [comment]
Can I ask what you mean by "_I don't trust my client to handle to the stream efficiently_"?

> Is there a way that I can custom ExoPlayer to handle the Range header correctly?

Is your question how to change what values are sent upstream for the `Range` header? If yes, you could wrap the HttpDataSource instances you use in a [`ResolvingDataSource` ](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/upstream/ResolvingDataSource.html) which  allows you to change the[ `DataSpec `](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/upstream/DataSpec.html) for which the HTTP request will be performed. The `Dataspec` fields `position` and `length` are used for the Range header values.

**Comment by chientrm** [comment]
> 

AFAIK, currently ExoPlayer only use the `range` header to ask the server where to start streaming the media file.
ExoPlayer use load control to determine when to read more more from the stream, this looks like a hanging HTTP connection between server and ExoPlayer.
On the other hand if my server only send certain duration (like 60 seconds of stream) and close the connection, and ExoPlayer reads more on demand. That would turn the streaming process into a discrete series of short HTTP connection.
I wonder if that would help with the streaming performance for large amount of listeners. 🤔

**Comment by christosts** [comment]
> this looks like a hanging HTTP connection between server and ExoPlayer

For progressive media (e.g. loading an mp4 directly), the connection would be left open to reduce the cost or re-establishing the HTTP connection.

I don't exactly follow what you are trying to achieve so that I can offer more advice. The player behavior is different whether you are streaming a media container directly (eg mp4) or your  content is packaged in an adaptive format, like DASH or HLS. So to help you better, I'd need more specific information.

In addition, ExoPlayer has integrated with several HTTP libraries which tend to optimize their resources internally (such as connection pooling) and that's something outside the player's control. In might be a useful to read https://exoplayer.dev/network-stacks.html, in case you decide to change the network stack you are using.

Did the information provided above for the [ResolvingDataSource](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/upstream/ResolvingDataSource.html) answer your question? In that case I can close this issue.

**Comment by chientrm** [comment]
> 

My happy case looks like this:

1. User click audio A on the phone
2. ExoPlayer request with header `range: bytes=0`
3. Server send back `bytes=0-245760` of audio A (the audio is 32kbps Constant Bit Rate so that is equivalent to 60 seconds of duration).
4. ExoPlayer play till there's 10 seconds left.
5. ExoPlayer request with header `range: bytes= 245760-491520` which is the next 60 seconds.
6. Repeat

Currently ExoPlayer doesn't care about response header `range`.

**Comment by christosts** [comment]
If the server responded with `bytes=0-245760` and the player then asked data from `range: bytes= 245760-491520`, it seems that the player respected what the server sent.  What would you have preferred the player to do in that scenario?

**Comment by chientrm** [comment]
> If the server responded with `bytes=0-245760` and the player then asked data from `range: bytes= 245760-491520`, it seems that the player respected what the server sent. What would you have preferred the player to do in that scenario?

AFAIK, currently ExoPlayer doesn't use the `range` in response header.
When start playing, ExoPlayer will start a stream request without `range` header.
If user `seekTo` a position, ExoPlayer will start a new playing request with `range: bytes=<new-position>-` without the required length.
And if the server only send a chunk of data, ExoPlayer keep playing without any sound after that chunk decoded. 🤔

**Comment by christosts** [comment]
> AFAIK, currently ExoPlayer doesn't use the `range` in response header. When start playing, ExoPlayer will start a stream request without `range` header. If user `seekTo` a position, ExoPlayer will start a new playing request with `range: bytes=<new-position>-` without the required length. And if the server only send a chunk of data, ExoPlayer keep playing without any sound after that chunk decoded. 🤔

Is this something that can be reproduced on the demo app? In fact, is it possible to share a link to the content hosted on this specific server so that we can test ourselves and see what happens?

Note, If you're unable to share the test content publicly, please send the link to dev.exoplayer@gmail.com with subject "Issue #11022"and update this issue to let us know.

**Comment by chientrm** [comment]
> > AFAIK, currently ExoPlayer doesn't use the `range` in response header. When start playing, ExoPlayer will start a stream request without `range` header. If user `seekTo` a position, ExoPlayer will start a new playing request with `range: bytes=<new-position>-` without the required length. And if the server only send a chunk of data, ExoPlayer keep playing without any sound after that chunk decoded. 🤔
> 
> Is this something that can be reproduced on the demo app? In fact, is it possible to share a link to the content hosted on this specific server so that we can test ourselves and see what happens?
> 
> Note, If you're unable to share the test content publicly, please send the link to [dev.exoplayer@gmail.com](mailto:dev.exoplayer@gmail.com) with subject "Issue #11022"and update this issue to let us know.

I'm not sure if you'd find interests in the app but my best chance is to invite you to the Google Groups so that you can have more insights.
I've send you the invitation, there should be an email sent by now.
Feel free to ignore the invitation if you don't want to. 😗

**Comment by icbaker** [comment]
@chientrm Please provide (either posted here, or emailed as described by @christosts above) a link to an HTTP server that is behaving as described in https://github.com/google/ExoPlayer/issues/11022#issuecomment-1446326349:
> If user `seekTo` a position, ExoPlayer will start a new playing request with `range: bytes=<new-position>-` without the required length.
> And if the server only send a chunk of data, ExoPlayer keep playing without any sound after that chunk decoded. 🤔

i.e. when Exoplayer seeks into the middle of a file and makes an open-ended range request, the server responds with a partially fulfilled response that doesn't cover the file all the way to the end.

Without this we cannot look further into this issue.

You may also want to take a look at https://github.com/google/ExoPlayer/issues/10537 where ExoPlayer's handling of range requests is discussed in some detail (and note how we're able to answer the question when provided with a link to an HTTP server behaving as described by the reporter).
