### ISSUE TITLE
MediaCodecRenderer: Errors categorisation if fallback codec applied

### ISSUE THREAD

**Issue by NoNews** [google/ExoPlayer#11028]
Hi. At first thank you for all your efforts in developing `ExoPlayer`!

**Problem**
Sometimes main media codes isn't available, which triggers `ERROR_CODE_DECODER_INIT_FAILED`.
As a solution, it's possible to enable a fallback for `rendersFactory`:
```
renderersFactory.setEnableDecoderFallback(true)
```

Which according to logic in [MediaCoderRenderer](https://github.com/google/ExoPlayer/blob/f72ca8338399c9e3c19e73fc0779f24baff14d35/library/core/src/main/java/com/google/android/exoplayer2/mediacodec/MediaCodecRenderer.java#L981) adds all available mediacodes.
However, it looks like that we always throw the same error (with different codec details) if fallback codec isn't available in addition to main codec, which make it difficult to categorise errors in analytics (`onVideoCodecError`)

*Step 1*: Trying to initialise decoder
*Step 2*: Failed. Reported `ERROR_CODE_DECODER_INIT_FAILED`
*Step 3*: Trying to initialise fallback decoder
*Step 4*: Failed. Reported `ERROR_CODE_DECODER_INIT_FAILED` 

So, we understand that a fallback applied, however in analytics it will be 2 the same errors.
________

**Proposed behaviour**
It would be great to understand that it isn't possible to playback video via fallback codec, for instance, like this:

*Step 1*: Trying to initialise decoder
*Step 2*: Failed. Reported `ERROR_CODE_DECODER_INIT_FAILED`
*Step 3*: Trying to initialise fallback decoder
*Step 4*: Failed. Reported `ERROR_CODE_FALLBACK_DECODER_INIT_FAILED` 

**Question**
What do you think about this? Maybe I missed something and there some other ways to categorise coder initialisation errors?

Thank you in advance.

**Comment by christosts** [comment]
I do not know how you've setup your analytics pipeline, but I'm assuming you can figure out which error is for the primary decoder and which ones are for the secondary decoders, right? This can be derived by app-logic either on the device or the server side.

**Comment by tonihei** [comment]
You should also be able to see the concrete decoder info related to `ERROR_CODE_DECODER_INIT_FAILED` by checking the cause of the exception.

Something like
```
if (error.getCause() instanceof DecoderInitializationException) {
  DecoderInitializationException initError = (DecoderInitializationException) error.getCause();
  Log.d("initError", "failed codec = " + initError.codecInfo.name);
}
```

**Comment by NoNews** [comment]
>You should also be able to see the concrete decoder info related to ERROR_CODE_DECODER_INIT_FAILED by checking the cause of the exception.

I see, thank you! But would it be possible to understand somehow whether it's primary decoder or not by the error?
Or only manually, by querying such information from the device?

**Comment by christosts** [comment]
> I see, thank you! But would it be possible to understand somehow whether it's primary decoder or not by the error?

Isn't this something you can derive in your analytics logic, e.g. when playback starts, the first decoder init error is for the primary and any other errors immediately following up are for fallback decoders?

**Comment by tonihei** [comment]
If you have access to `codecInfo` already, you could also check `hardwareAccelerated`, `softwareOnly` etc to know more about the type of codec? Not sure if that is that is what you are looking for.
