### ISSUE TITLE
Does ExoPlayer support Vr playback, gyroscope, dual-screen mode ？

### ISSUE THREAD

**Issue by liuguangsen** [google/ExoPlayer#11029]
Before filing a feature request:
-----------------------
- Search existing open issues, specifically with the label ‘enhancement’:
  https://github.com/google/ExoPlayer/labels/enhancement
- Search existing pull requests: https://github.com/google/ExoPlayer/pulls

When filing a feature request:
-----------------------
Replace the content in the sections below.

### [REQUIRED] Use case description
Describe the use case or problem you are trying to solve in detail. If there are
any standards or specifications involved, please provide the relevant details.

### Proposed solution
A clear and concise description of your proposed solution, if you have one.

### Alternatives considered
A clear and concise description of any alternative solutions you considered,
if applicable.

**Comment by andrewlewis** [comment]
> Does ExoPlayer support Vr playback, gyroscope, dual-screen mode？

Spherical videos are supported ~~including with side-by-side playback~~ via `SphericalGLSurfaceView`, which can be used by setting `surface_type` set to `spherical_gl_surface_view` on the player view. This includes updating the view based on orientation sensors. Note: It is important to call `onResume` and `onPause` on the `PlayerView` based on visibility changes for this use case.

Does that cover what you are trying to do, or are you looking for something else? It's a bit hard to tell based on the terminology in your question, so it would be helpful if you could provide more details.

Edit: see comment on #11166 about side-by-side playback, which isn't supported out of the box.
