### ISSUE TITLE
Get current manifest from the player

### ISSUE THREAD

**Issue by wishygupta** [google/ExoPlayer#11036]
I am looking for some additional network logs which can give me the current manifest as string 
```
private val exoListener = object : Player.Listener {
        override fun onTimelineChanged(timeline: Timeline, reason: Int) {
            super.onTimelineChanged(timeline, reason)        
            if (exoPlayer != null && exoPlayer!!.playWhenReady) {
                val manifest: Any? = exoPlayer!!.currentManifest
                if (manifest != null) {
                    if (manifest is HlsManifest) 
                       readHLSManifest(manifest)
                }
            }
        }
    }
```

How can I get this manifest in string format? Or is there any other method to do it?

**Comment by marcbaechinger** [comment]
I think the API that the code snippet is using above is what's available. The player parses the HLS playlist and then provides it as part of the window.  

Under the hood the `getCurrentManifest` does `timeline.getWindow(getCurrentMediaItemIndex(), window).manifest`. There are different reasons for a timeline change. For HLS the manifest (or playlist) is available with the first timeline update with `TIMELINE_CHANGE_REASON_SOURCE_UPDATE` for the given window.

There is no text version available I'm afraid. Please note that `HlsPlaylist` may not contain all properties of the actual playlist but only what is actually used by the player.  The playlist is parsed by an `HlsPlaylistParser` that you can customize with `HlsMediaSource.Factory.setPlaylistParserFactory`.
