### ISSUE TITLE
Error Parsing HLS stream

### ISSUE THREAD

**Issue by Fleker** [google/ExoPlayer#1103]
A user was having some difficulty playing an HLS file in my app, which uses ExoPlayer. I checked the stream and confirmed I could not play it. Here is the stack trace: 

    01-03 18:46:18.823 18837-18837/com.felkertech.n.cumulustv W/System.err: com.google.android.exoplayer.ParserException: Couldn't match #EXT-X-VERSION tag in #EXT-X-VERSION: 2
    01-03 18:46:18.831 18837-18837/com.felkertech.n.cumulustv W/System.err:     at com.google.android.exoplayer.hls.HlsParserUtil.parseStringAttr(HlsParserUtil.java:39)
    01-03 18:46:18.832 18837-18837/com.felkertech.n.cumulustv W/System.err:     at  com.google.android.exoplayer.hls.HlsParserUtil.parseIntAttr(HlsParserUtil.java:44) 
    01-03 18:46:18.832 18837-18837/com.felkertech.n.cumulustv W/System.err:     at com.google.android.exoplayer.hls.HlsPlaylistParser.parseMediaPlaylist(HlsPlaylistParser.java:237)
    01-03 18:46:18.832 18837-18837/com.felkertech.n.cumulustv W/System.err:     at com.google.android.exoplayer.hls.HlsPlaylistParser.parse(HlsPlaylistParser.java:129)
    01-03 18:46:18.832 18837-18837/com.felkertech.n.cumulustv W/System.err:     at com.google.android.exoplayer.hls.HlsPlaylistParser.parse(HlsPlaylistParser.java:39)
    01-03 18:46:18.832 18837-18837/com.felkertech.n.cumulustv W/System.err:     at com.google.android.exoplayer.upstream.UriLoadable.load(UriLoadable.java:93)
    01-03 18:46:18.832 18837-18837/com.felkertech.n.cumulustv W/System.err:     at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
    01-03 18:46:18.832 18837-18837/com.felkertech.n.cumulustv W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
    01-03 18:46:18.832 18837-18837/com.felkertech.n.cumulustv W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    01-03 18:46:18.832 18837-18837/com.felkertech.n.cumulustv W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    01-03 18:46:18.832 18837-18837/com.felkertech.n.cumulustv W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    01-03 18:46:18.832 18837-18837/com.felkertech.n.cumulustv W/System.err:     at java.lang.Thread.run(Thread.java:818)

I opened up the m3u8 file and looked at the header. 

    #EXTM3U #EXT-X-VERSION: 2 #EXT-X-MEDIA-SEQUENCE: 811 #EXT-X-TARGETDURATION: 10 #ANVATO-STREAM-ID: GHLkmahl8W5

I just updated my app to use 1.5.3 and am still seeing this issue.

**Comment by ojw28** [comment]
If that's all on one line in the file then I think that's invalid. Each tag should be on its own line. Please clarify. Ideally, please provide the link to the actual m3u8 file. Thanks.

**Comment by Fleker** [comment]
Okay, here is the file that the user sent to me: http://play-pico-cl1.fs.anvato.net/m3u8/pico706-otas-wjbk/1928k/index.m3u8

It works fine on my desktop in VLC player, and if it is invalid somehow I don't know how that could be changed.

**Comment by ojw28** [comment]
I get `The page you are looking for is not found.` when I click on that link. Either it's broken or it's geo-restricted to a country that I'm not in?

**Comment by Fleker** [comment]
The link was working earlier today, but it seems like it is now broken. I uploaded a copy of the m3u8 file I downloaded from that url earlier.

[index.txt](https://github.com/google/ExoPlayer/files/76805/index.txt)

**Comment by ojw28** [comment]
The problematic lines are:

```
#EXT-X-VERSION: 2
#EXT-X-MEDIA-SEQUENCE: 811
#EXT-X-TARGETDURATION: 10
```

Per the HLS spec, there shouldn't be spaces between the `:` and the value. The provider should fix their HLS m3u8 to comply with the spec.
