### ISSUE TITLE
About macro expansion of tracker URLs when using client-side ad insertion

### ISSUE THREAD

**Issue by hyunwookim-moloco** [google/ExoPlayer#11032]
Hi! I have a question of MACRO expansion of Exo Player IMA extension.

I want to fire imp tracker of VAST response by replacing some parts of them.
For example, If the below VAST response is given,

```xml
<vmap:VMAP
		xmlns:vmap="http://www.iab.net/videosuite/vmap" version="1.0">
	<vmap:AdBreak timeOffset="#1" breakType="linear">
		<vmap:AdSource>
			<vmap:VASTAdData>
				<VAST version="3.0">
					<Ad sequence="1">
						<InLine>
							<AdSystem version="1">
								<![CDATA[...]]>
							</AdSystem>
							<AdTitle>
								<![CDATA[...]]>
							</AdTitle>
							<Impression id="Moloco">
								<![CDATA[https://dummy.com/imp?imp_id=abc123&user_id=%%USER_ID%%]]>
							</Impression>
							<Creatives>
								<Creative id="aaaaaD7TvvyX5ZtkIz4eG.j.Uz0Kglh3U7sDROzm" sequence="1">
									<Linear>
										<Duration>00:00:30</Duration>
										<TrackingEvents>
											<Tracking id="Moloco_4q" event="complete">
												<![CDATA[ https://dummy.com/imp?imp_id=abc123&user_id=%%USER_ID%%&event-complete ]]>
											</Tracking>
										</TrackingEvents>
										<VideoClicks></VideoClicks>
										<MediaFiles>
											<MediaFile id="mediafile" delivery="progressive" type="video/mp4" bitrate="700" width="1920" height="1080">
												<![CDATA[......]]>
											</MediaFile>

										</MediaFiles>
									</Linear>
									<CreativeExtensions></CreativeExtensions>
								</Creative>
							</Creatives>
							<Description></Description>
							<Survey></Survey>
							<Extensions></Extensions>
						</InLine>
					</Ad>
				</VAST>
			</vmap:VASTAdData>
		</vmap:AdSource>
	</vmap:AdBreak>
</vmap:VMAP>
```

we want to replace `%%USER_ID%%` to actual user id. 
- .../imp?imp_id=abc123&user_id=`%%USER_ID%%` -> .../imp?imp_id=abc123&user_id=`userid123`

Could you guide me on how to replace the macro with our custom value?
I will use Client-side Ad Insertion which described at https://exoplayer.dev/ad-insertion.html

**Comment by marcbaechinger** [comment]
The VAST file is not processed by ExoPlayer.

In case you are using the IMA extension, the VAST file is processed by the IMA SDK. THe same is true for the impressions sent back to a server by a URI. This is not happening in ExoPlayer code, so we can't help you with this I'm afraid.

If you are not using the IMA extension but want to populate the `AdPlaybackState` yourself, you need to parse the VAST file yourself anyway and you can change the URI accordingly..

**Comment by hyunwookim-moloco** [comment]
@marcbaechinger 

Oh, actually we use IMA-extension, then should I ask about this to IMA github?

**Comment by marcbaechinger** [comment]
Yeah, probably. The SDK is used under the hood by the extension. The idea is that apps don't need to interact with the SDK directly but instead only use the ExoPlayer API. 

If the SDK has an API that allows to transform the VAST file, you'd need to access this API and integrate your change with the IMA extension. So your need to interact with the SDK directly defeats a bit the idea of the extension and the SDK API may not be accessible with the extension. So depending on the degree of customization you need on the SDK level, you may need to implement this yourself by directly talking to the SDK.

However, IMA folks will be able to tell you whether such an Android API is available to customize the JavaScript core of the SDK.

**Comment by hyunwookim-moloco** [comment]
> JavaScript core of the SDK.

Do you mean the core of IMA SDK is javascript? Could you share the github repository of that?

**Comment by marcbaechinger** [comment]
There is an Android API but the implementation itself is in JavaScript I think. 

I'm not aware whether the SDK is developed on GitHub. I think not. There is a repository with samples here: https://github.com/googleads/googleads-mobile-android-examples

**Comment by hyunwookim-moloco** [comment]
Thank you for the guidance!

**Comment by hyunwookim-moloco** [comment]
@marcbaechinger 

I have a question about impression tracker of VAST.
As you said, player doesn't know what tracker URL too? Then how the trackers are fired? Does player call the tracker firing function?

**Comment by marcbaechinger** [comment]
Roughly, the SDK gives the player ad position and media URI. The player then tells the SDK when an ad has been finished playing and the SDK does the rest.

**Comment by hyunwookim-moloco** [comment]
Thank you for the explanation!!

**Comment by marcbaechinger** [comment]
Glad it was helpful!

I'm closing this issue. Please re-open if required.
