### ISSUE TITLE
Unexpected audio track timestamp discontinuity

### ISSUE THREAD

**Issue by sundaylol** [google/ExoPlayer#11043]
This problem occurs when I play the following video, how can I bypass this timestamp check？

<img width="872" alt="image" src="https://user-images.githubusercontent.com/16680840/223402888-2104bfc0-d811-41be-81c4-0508dd4335c5.png">

<img width="1328" alt="image" src="https://user-images.githubusercontent.com/16680840/223402458-dcf0c3fc-7835-4d49-85fa-8759a1f45980.png">

**Comment by rohitjoins** [comment]
Hi,

Can you please share the media file you're playing to get this issue? If you're unable to share the
test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format
"Issue #1234" ("#1234" is replaced with your issue number). Please also update this issue to
indicate you've done this.

**Comment by sundaylol** [comment]
> Hi,
> 
> Can you please share the media file you're playing to get this issue? If you're unable to share the test content publicly, please send them to [dev.exoplayer@gmail.com](mailto:dev.exoplayer@gmail.com) using a subject in the format "Issue #1234" ("#1234" is replaced with your issue number). Please also update this issue to indicate you've done this.
Thanks reply，the video is too big , i have send the video with email to dev.exoplayer@gmail.com

**Comment by rohitjoins** [comment]
Hi @sundaylol,

I can confirm that we have received the media file. Thanks.

**Comment by rohitjoins** [comment]
Hi @sundaylol,

I cannot reproduce this error on the demo app of Exoplayer. Can you please provide concrete steps to reproduce this error?

Please provide complete information as requested in the issue template. The issue template can
be found [here](https://github.com/google/ExoPlayer/issues/new?assignees=&labels=bug%2Cneeds+triage&template=bug.yml).

**Comment by sundaylol** [comment]
Hi @rohitjoins 
I played this video on the RK3566 platform. It may be a problem with the decoder provided by RK. Is there a way to ignore the timestamp check in this case?
