### ISSUE TITLE
Can you support any video decoder that ffmpeg supports？

### ISSUE THREAD

**Issue by ac1991** [google/ExoPlayer#11042]
Can you support any video decoder that ffmpeg supports？

example：
# ./configure  --list-decoders
aac                     dxa                     mp2                     s302m
aac_at                  dxtory                  mp2_at                  sami
aac_fixed               dxv                     mp2float                sanm
aac_latm                eac3                    mp3                     sbc
aasc                    eac3_at                 mp3_at                  scpr
...

**Comment by rohitjoins** [comment]
Hi,

Currently Exoplayer's ffmpeg extension only supports audio decoders. You can find the audio formats supported by ffmpeg [here](https://exoplayer.dev/supported-formats.html#ffmpeg-extension).
