### ISSUE TITLE
MediaCodecAudioRenderer error audio/mpeg-L2

### ISSUE THREAD

**Issue by Reksagon** [google/ExoPlayer#11044]
```
E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: MediaCodecAudioRenderer error, index=1, format=Format(1/4, null, null, audio/mpeg-L2, null, -1, null, [-1, -1, -1.0], [2, 48000]), format_supported=NO_UNSUPPORTED_TYPE
```
      
a strange error, on version 2.16.1 in some applications it reproduces HlsMediaResource and on 2.18.4 it does not reproduce anywhere at all.

**Comment by rohitjoins** [comment]
Hi! Please provide complete information as requested in the question template. The template can be
found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/question.md).

Unfortunately we can't answer unclear questions or those with insufficient information.
