### ISSUE TITLE
MediaSource wrapping a MediaItem drops the ad config

### ISSUE THREAD

**Issue by Human** [google/ExoPlayer#11046]
### ExoPlayer Version

2.18.4

### Devices that reproduce the issue

All Android devices tested, including those running Android 11, 12, and 13.

### Devices that do not reproduce the issue

All tested devices reproduced the issue.

### Reproducible in the demo app?

Yes

### Reproduction steps

The simplest way to reproduce this is to check out https://github.com/googleads/googleads-ima-android and modify exoplayerexample/MyActivity.java as shown in this PR: https://github.com/Human/googleads-ima-android/pull/1

### Expected result

We expect the preroll ad configured with `MediaItem.setAdsConfiguration()` to play, followed by the "regular" stream content as set by `MediaItem.setUri()`.

### Actual result

The preroll ad configured with `MediaItem.setAdsConfiguration()` is not played, but the "regular" stream content as set by `MediaItem.setUri()` does play.

### Media

https://github.com/Human/googleads-ima-android/pull/1 uses the reference media inside the reference project for the IMA SDK.

### Bug Report

- [x] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by marcbaechinger** [comment]
The change that you reference is using a `DefaultMediaSourceFactory` to create a media source and then sets this media source by using `player.setMediaSource(source)`.

With this you bypass the `DefaultMediaSourceFactory` that is used internally and configured with the required ads component (see L105 of your change).

You have three options. Just leave the sample as it is and then it works as expected. The second option is to change your code and use the `mediaSourceFactory` from L105 that is configured with ads component. And the third option would be to setup your `DefaultMediaSourceFactory` in the same way that you can see on L107.

I'm closing this issue. Please re-open if you think there is a bug in the library that prevents you from playing an ad.

**Comment by Human** [comment]
@marcbaechinger :1st_place_medal: This worked, thank you! In case others are searching on the issue:

```
player.setMediaSource(mediaSourceFactory.createMediaSource(mediaItem));
```

does the trick!
