### ISSUE TITLE
Square/Vertical content overlaps with ads in emulator

### ISSUE THREAD

**Issue by putragraha** [google/ExoPlayer#11048]
### ExoPlayer Version

2.17.1

### Devices that reproduce the issue

- Emulator Pixel 5 running Android 13

### Reproducible in the demo app?

Yes

### Reproduction steps

Play any vertical/square content with horizontal ads

### Expected result

Ads should disappear and content can be shown without overlapping to any ads

### Actual result

Content shown on top of the ads (overlapping)
![Screenshot from 2023-03-09 10-39-58](https://user-images.githubusercontent.com/6689845/223910757-b7fd452b-c2bd-4d01-8890-ff46f4da2051.png)

### Media

Media sample used will be sent through email

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by rohitjoins** [comment]
Hi @putragraha,

It seems you're using the IMA extension to play ads. The link shared via email for the content is to a webpage. Can you please provide link to the media that can be used to reproduce this issue in the demo app?

**Comment by putragraha** [comment]
Sorry, my bad, already sent you the correct link for the content and the tag uri as well.

> It seems you're using the IMA extension to play ads

Yes, it is using IMA extension.

Anyway, the issue also reproducible in exoplayer version 2.18.4

**Comment by rohitjoins** [comment]
Thanks for sharing the content url @putragraha.

At the end of second ad, I was able to reproduce some overlap with the content.
![Screenshot_20230313-115114](https://user-images.githubusercontent.com/32570096/224695793-a28f04e0-b5b6-464a-b4bb-539a5cbd148d.png)

@tonihei can you please take a look?

**Comment by tonihei** [comment]
This looks like an emulator issue. I can reproduce it on the Pixel 5, API 33 emulator, but not an any real device. Please see https://developer.android.com/guide/topics/media/exoplayer/supported-devices for a note about emulator support (at the bottom). In short, emulators are known to behave strangely with media playback and you should always try to test on a real device. 

The screenshot @rohitjoins shared above is likely just an issue in the short transition period after an ad where the player already continues playing, but the ad overlay hasn't been hidden yet.

**Comment by putragraha** [comment]
Noted, thanks @tonihei .
Attempted to reproduce the issue on Pixel 7 Pro (real device), and was not reproducible.

Well, if the issue only occurred in emulator, then it should be fine by now.

**Comment by putragraha** [comment]
Hi, will close this issue since not reproducible in real device, and should be referred as emulator issue instead.
Thanks.
