### ISSUE TITLE
Failed to connect to xxxx.xxxx.xxx/127.0.0.1:443

### ISSUE THREAD

**Issue by meijinzero** [google/ExoPlayer#11056]
the URL I catch from website and then do  -> exoplayer.loadUrl
normal m3u8 or mp4 url was fine to palyer on my code
the problem is the URL will by using HTTP CONNECT METHOD ,
it starts with “https://”    Redirect to xxxx.xxxx.xxx/127.0.0.1:443
and I uses none pre-setting DefaultHttpDataSource.Factory()
by the way,  the URL has "token" and "expire" key,  but I use IDM downloader was ok to download in time ,it's a mp4 file.
hlep!

**Comment by marcbaechinger** [comment]
Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md). If you're unable to share bug reports or test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Please also update this issue to indicate you’ve done this.

It's important to provide reproduction steps and media that makes an issue actionable for us. This means it must be clear what someone can do experience the problem. There is no API `exoplayer.loadUrl` that I'm aware of I'm afraid.
