### ISSUE TITLE
Display webvtt closed captions from an external file

### ISSUE THREAD

**Issue by andrei1990** [google/ExoPlayer#1106]
How to display closed captions for a HLS stream from an external file?
Right now i'm using this code to setup text renderer 
http://paste.ofcode.org/c9rGwrJXLZqsua7Qk7cLJr, but the video is freezing at 11 sec .

**Comment by ojw28** [comment]
Do you mean a completely external webvtt file, or a file listed in the HLS master playlist using a EXT-X-MEDIA tag? If completely external, I don't understand how your code would work, given you're not provided a URL for the WebVtt file anywhere. If listed in the HLS master playlist, this is not yet fully implemented, and is tracked by #151.
