### ISSUE TITLE
Add DTS-LBR and DTS:X support in MPEG2-TS extractor

### ISSUE THREAD

**Issue by rahulnmohan** [google/ExoPlayer#11075]
### Use case description

- Add support for extracting DTS LBR(DTS Express) and DTS UHD Profile 2(DTS:X) descriptor ID
  from PSI PMT
- Update the DTSReader class for extracting a DTS LBR or DTS UHD frame from the raw bitstream.
- Update the DTSUtil class to parse the DTS LBR or DTS UHD frame and report the format information.

Specification Docs:

1. ETSI EN 300 468 V1.17.1: Digital Video Broadcasting (DVB); Specification for Service Information (SI) in DVB systems EUROPEAN STANDARD
   Details of DVB descriptors for DTS LBR, and DTS UHD streams are available in this document.
2. ETSI TS 102 114 V1.6.1 (2019-08): DTS Coherent Acoustics; Core and Extensions with Additional Profiles
   Details of synchronization and format extraction of DTS Core(CA), and DTS LBR(DTS-HD with only Extension Sub-stream) are available in this document.
3. ETSI TS 103 491 V1.2.1 (2019-05): DTS-UHD Audio Format; Delivery of Channels, Objects and Ambisonic Sound Fields
    Details of synchronization and format extraction of DTS UHD stream are available in this document.

### Proposed Solution
Pull request for this feature update - https://github.com/androidx/media/pull/275

**Comment by rohitjoins** [comment]
The PR for this was merged.
