### ISSUE TITLE
Exoplayer sticks in preparing state when preparing HLS content with small ts chunk size

### ISSUE THREAD

**Issue by Zo2m4bie** [google/ExoPlayer#1107]
Hi. I tried to play a stream through ExoPlayer and it sticks in preparing state. The Stream contains small .ts files(~2 sec). I want to add, it happens only if ts files are small. I have another stream (it contains  bigger .ts files~9sec) and ExoPlayer plays without any problems.
I tried to look more deeply, and found that onLoadCompleted(Loadable loadable) ( https://github.com/google/ExoPlayer/blob/r1.5.0/library/src/main/java/com/google/android/exoplayer/hls/HlsSampleSource.java#L397 ) always calls with 

     enabledTrackCount = 0 
     preppared = false 

In this way maybeStartLoading() starts all the time (
https://github.com/google/ExoPlayer/blob/r1.5.0/library/src/main/java/com/google/android/exoplayer/hls/HlsSampleSource.java#L414 )
what I see in log:

     I/ExoPlayerImpl: Init 1.5.0
     D/EventLogger: start [0]
     D/com.google.android.exoplayer.ExoPlayer: playWhenReady=false, playbackState=preparing
     D/EventLogger: state [0.00, false, P]
     D/com.google.android.exoplayer.ExoPlayer: playWhenReady=true, playbackState=preparing
     D/EventLogger: state [0.00, true, P]

**Comment by ojw28** [comment]
You will have to provide a sample stream that reproduces this issue for us to investigate. As noted on another issue you filed, we cannot investigate issues when insufficient information is provided. There's a list of information that's useful when reporting issues [here](https://google.github.io/ExoPlayer/2015/10/01/reporting-issues.html).

**Comment by Zo2m4bie** [comment]
@ojw28 Ok, I've just sent the url  to you

**Comment by ojw28** [comment]
The stream does not contain any IDR frames. Each segment should contain at least one IDR frame (preferably near the start) as documented [here](https://developer.apple.com/library/ios/technotes/tn2224/_index.html#//apple_ref/doc/uid/DTS40009745-CH1-MEDIASTREAMSEGMENTATION-USE_AT_LEAST_ONE_IDR_FRAME_PER_SEGMENT__PREFERABLY_AT_THE_START_).

Note that you can make the sample play by setting `idrKeyframesOnly = false` in the `H264Reader` constructor, however this should not be required for HLS and doing this can cause visual corruption (and in the worst case decoder crashes) on other correct streams.

So it seems this is an encoding issue with the media.
