### ISSUE TITLE
Seeking for 4K HDR MP4 file is not working

### ISSUE THREAD

**Issue by menscikov** [google/ExoPlayer#11070]
### ExoPlayer Version

2.18.4

### Devices that reproduce the issue

Any device.

### Reproducible in the demo app?

Yes

### Reproduction steps

Open the video.

### Expected result

Seeking is working.

### Actual result

Try to seek the video, it won't work.

### Media

Video link has been sent to dev email.

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by christosts** [comment]
The link we received points to a file named with the `.mp4` extension but it's actually an HLS playlist, which looks malformed and can't be loaded with VLC either. Closing this issue as this looks like malformed media.

**Comment by menscikov** [comment]
Hello, @christosts.

Thank you for checking.
Yes, i tried to open it in VLC, seeking is not working there also.
But then i opened it with KODI, at seeking is working there. It's strange.

I will pass this information to the user who sent me this video link.
