### ISSUE TITLE
ExoPlaybackException occurs on some terminals

### ISSUE THREAD

**Issue by ogawa-ma** [google/ExoPlayer#11074]
I added a comment to a previously CLOSED https://github.com/google/ExoPlayer/issues/10567, but did not receive a response, so I started a new issue.
This problem still occurs.
I have retrieved the `data` for the device where the error occurred, since there was a previous request for `ProvisioningRequest` `data`.
Please check it.

https://github.com/google/ExoPlayer/issues/10567#issuecomment-1465546828

**Comment by rrfrias** [comment]
Sorry about this. I missed this because i was filtering using a label.

Thanks for the [failed](https://github.com/google/ExoPlayer/issues/10567#issuecomment-1465546828) provisioning request. I have opened an internal tracker [283034529](http://b/283034529) to follow up.

**Comment by ogawa-ma** [comment]
@rrfrias 
Hi! Any progress?

**Comment by rrfrias** [comment]
We parsed the provisioning message and it looks ok from a visual inspection. Getting someone to help from our provisioning service team.

**Comment by rrfrias** [comment]
Our provisioning team reported that playing back the request succeed. We cannot tell why it was rejected. Can you share a few more requests that failed? You can send it to [android-media-github@google.com](mailto:android-media-github@google.com)

**Comment by ogawa-ma** [comment]
@rrfrias 
I just shared a `ProvisioningRequest` for 4 devices to android-media-github@google.com.

Only the Pixel 7a that I shared had a Response code of 500. (The other 3 models were 400 errors that I shared before.)
Is the Pixel 7a a different problem?
![スクリーンショット 2023-07-26 11 55 41](https://github.com/google/ExoPlayer/assets/54785318/4152beed-b788-4efd-b499-bcc6f33f82f9)


Also, when I looked at the error log, the result of `DrmSessionException` was Response code: 400, but there was an error log where `onKeysError` occurred instead of `onProvisionError`.(All `ProvisioningRequests` shared by email this time are requests when `onProvisionError` occurs.)
Is the `onKeysError` a separate issue from this one?
![スクリーンショット 2023-07-26 11 59 05](https://github.com/google/ExoPlayer/assets/54785318/6ea6207b-cef0-402b-a9ea-e83b488eb4f2)

**Comment by ogawa-ma** [comment]
For your information, the version of ExoPlayer currently in use is 2.16.1.

**Comment by rrfrias** [comment]
Thanks. We are looking into them.

**Comment by rrfrias** [comment]
@ogawa-ma we were able to playback one of the provisioning request (Sony Xperia Z2) without an issue. We are still investigating the failure with NEC LaVie T11. For the other two, if you are a widevine licensee, you can get more information by contacting  [Widevine support](https://www.widevine.com/contact) or Widevine partner engineering contact if you have one. Please mention this tracker.

**Comment by rrfrias** [comment]
@ogawa-ma we are still looking at the Pixel 7a failure. If there are other provisioning requests that are failing, can you share them? Let us know if you need any help contacting the official Widevine support for information from the previous comment.

**Comment by ogawa-ma** [comment]
@rrfrias 
We have sent additional provisioning request failed device information and ProvisioningRequest data to android-media-github@google.com.
Please check.

We do not have a direct contract with Widevine and therefore cannot get support from Widevine.

**Comment by rrfrias** [comment]
Thanks. I analyzed/replayed the 7 provisioning requests you included. I was able to get a successful provisioning response for the first five. I got an HTTP 400 error for the last two. I am unable to share more information with non-Widevine licensees. 

I am also not sure why we see a difference in the first 5 provisioning requests (you see  HTTP 400 errors).

For the last two, are the people who maintain the license service that you use Widevine licensees?

**Comment by rrfrias** [comment]
For a device that supports multiple security levels and fails to provision, can you try opening a session at a lower security level [MediaDrm#openSession](https://developer.android.com/reference/android/media/MediaDrm#openSession(int))([SECURITY_LEVEL_SW_SECURE_CRYPTO](https://developer.android.com/reference/android/media/MediaDrm#SECURITY_LEVEL_SW_SECURE_CRYPTO)) and attempting playback at that security level?

(From the previous comment) For the last two, are the people who maintain the license service that you use Widevine licensees?

**Comment by ogawa-ma** [comment]
> For a device that supports multiple security levels and fails to provision, can you try opening a session at a lower security level [MediaDrm#openSession](https://developer.android.com/reference/android/media/MediaDrm#openSession(int))([SECURITY_LEVEL_SW_SECURE_CRYPTO](https://developer.android.com/reference/android/media/MediaDrm#SECURITY_LEVEL_SW_SECURE_CRYPTO)) and attempting playback at that security level?

Please wait a moment while we check it.

> (From the previous comment) For the last two, are the people who maintain the license service that you use Widevine licensees?

Yes.

**Comment by fredgc** [comment]
In general for problems like this, falling back to SECURITY_LEVEL_SW_SECURE_CRYPTO is the easiest solution. 

If you want a more complicated solution, please work with the streaming service you are working with. Since they are a Widevine licensee they can request support directly.
