### ISSUE TITLE
How to flip the video left-right without using TextureView.

### ISSUE THREAD

**Issue by hyoromo** [google/ExoPlayer#11084]
> If you can't use TextureView, it's also possible to set a rotation when configuring the MediaCodec, which you could do by subclassing MediaCodecVideoRenderer and passing your subclass via a custom RenderersFactory when building the player.

[#8099](https://github.com/google/ExoPlayer/issues/8099#issuecomment-715262463) the above exchange, is it possible to inherit from MediaCodecVideoRenderer and implement left-right reversal of video?

If possible, it would be helpful if you could be more specific in your implementation.

**Comment by tianyif** [comment]
Just adding a side note for the future issues, we will begin to triage the issues in [media repository](https://github.com/androidx/media) (new home of ExoPlayer) only, so please make sure the new issues are filed in that repository. This one can continues staying in ExoPlayer repository though.

Thanks in advance!

**Comment by hyoromo** [comment]
Thanks for the support.
I created [#285](https://github.com/androidx/media/issues/285) in the media repository.

**Comment by christosts** [comment]
thanks, I'll close this one and continue on the other repo.
