### ISSUE TITLE
How to add friendly obstructions to Exoplayer IMA Extension

### ISSUE THREAD

**Issue by WuBingHui** [google/ExoPlayer#11080]
Hi,

I use Exoplayer IMA Extension v2.18.1 to custom a ad player.

I used charles to check IAB ad event and found some obstructions view.

How to add friendly obstructions view to Exoplayer IMA Extension ?

**Comment by tonihei** [comment]
These can specified via `AdViewProvider.getAdOverlayInfos`. The default UI module uses this to register the playback controls as friendly obstruction for example. See https://developer.android.com/guide/topics/media/exoplayer/ad-insertion#ui-considerations for details.
