### ISSUE TITLE
How to notify volumeChange events to OM SDK

### ISSUE THREAD

**Issue by WuBingHui** [google/ExoPlayer#11087]
Hi,

I use Exoplayer IMA Extension v2.18.1 to custom a ad player with a  Mute/Unmute button

I used charles to check IAB ad event and found Exoplayer IMA could not  notify volumeChange events to OM SDK .

How to notify volumeChange events to OM SDK?

**Comment by tonihei** [comment]
ExoPlayer's IMA extension is reporting the value of `player.getVolume()` to the IMA `com.google.ads.interactivemedia.v3.api.player.VolumeProvider`.  I can't see this method being triggered though and I'm not sure under which circumstances the IMA SDK requests a volume. Do you know when this is meant to be happen? If not, this is probably a question for your IMA contact and not for ExoPlayer.
