### ISSUE TITLE
[IMA] DRM license request occurs during ad preroll

### ISSUE THREAD

**Issue by cdongieux** [google/ExoPlayer#11088]
I notice ExoPlayer starts downloading content and performs the corresponding DRM request when the IMA preroll ad is playing.

While the content loading is not a problem for me, I'm more concerned about the DRM license request happening before the content is actually (about to be) played because our streaming server uses the DRM request to count play events for our statistics.

It seems `AdsMediaSource.prepareSourceInternal()` is responsible for this behaviour as mentioned in [this issue](https://github.com/google/ExoPlayer/issues/10719). Do you know if there is any way to delay the DRM request to occur only when the content is about to be played?

**Comment by icbaker** [comment]
This is working as intended to ensure the transition from the ad into the content is as seamless as possible. We also start loading the video bytes before they start playing for the same reason.

Pre-loading of DRM licenses was implemented as part of https://github.com/google/ExoPlayer/issues/4133. You should be able to disable it by sub-classing `DefaultDrmSessionManager` and overriding [`preacquireSession()`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/drm/DefaultDrmSessionManager.html#preacquireSession(com.google.android.exoplayer2.drm.DrmSessionEventListener.EventDispatcher,com.google.android.exoplayer2.Format)) to be a no-op (see the default implementation in `DrmSessionManager`). This will cause playback to pause between the ad and content while the license request is made. See more about customising `DrmSessionManager` here: https://exoplayer.dev/drm.html#using-a-custom-drmsessionmanager

To be honest though, I think a much better solution would be to track play events in a different way (e.g. report analytics back from the player when playback position has actually reached the position you care about, or in-stream event messages that the player can emit when they are encountered).

**Comment by cdongieux** [comment]
Thanks for the answer. I agree, but this approach has the advantage to count playbacks without the need to change anything in our apps.
