### ISSUE TITLE
How to get pcm data during video playing?

### ISSUE THREAD

**Issue by GreenVegetables** [google/ExoPlayer#11097]
How to get pcm data during video playing? The exoplayer version used is 2.18.5.

**Comment by tonihei** [comment]
You can add a `TeeAudioProcessor` to `DefaultAudioSink` (by overriding `DefaultRenderersFactory.buildAudioSink`). In there, you can specify an `AudioBufferSink` to write your pcm data to. You can also use the predefined `WavFileAudioBufferSink` to write to a wav file if needed. Alternatively, you can write your own `AudioProcessor` to modify the pcm audio as needed.

**Comment by GreenVegetables** [comment]
> You can add a `TeeAudioProcessor` to `DefaultAudioSink` (by overriding `DefaultRenderersFactory.buildAudioSink`). In there, you can specify an `AudioBufferSink` to write your pcm data to. You can also use the predefined `WavFileAudioBufferSink` to write to a wav file if needed. Alternatively, you can write your own `AudioProcessor` to modify the pcm audio as needed.

Thank you. Following these steps, I successfully obtained the pcm data.
