### ISSUE TITLE
Detect if ExoPlayer instance is used by any PlayerView

### ISSUE THREAD

**Issue by androidplayer1** [google/ExoPlayer#11092]
I am currently developing a library that utilizes Exo Player. The library's service can receive a merging source that includes both audio and video files. To optimize data loading, I intend to implement a feature that checks whether the ExoPlayer instance is connected to any PlayerView. If it is, I will set the track selection to use video streams, otherwise only audio.

My question is: is this feature feasible with the current version of Exo Player?

**Comment by tonihei** [comment]
This isn't easily possible I'm afraid. But it should also be fairly straight-forward to handle this in your app? For example, maintain a field/list of ExoPlayer instances that are connected to a PlayerView. Every time you connect or disconnect from a view, you can update this list.

**Comment by androidplayer1** [comment]
> This isn't easily possible I'm afraid. But it should also be fairly straight-forward to handle this in your app? For example, maintain a field/list of ExoPlayer instances that are connected to a PlayerView. Every time you connect or disconnect from a view, you can update this list.

I do not own the logic outside. I wanted just to implement the service player without having domain or access to the app itself. I just wanted to make it more performant automatically that in case the player view is attached, I would select video track otherwise only audio.

Looks like the only option so far is to add an api to my service to notfiy about if player is attached or not.

**Comment by marcbaechinger** [comment]
I'm not sure I understand the context. Does your library build a player instance and then give that instance to an app to attach it to a player view? Does it help that you can use a `ForwardingPlayer` and monitor calls to `Player.setVideoSurface`, `setVideoTextureView` at al. ?
