### ISSUE TITLE
Firestick 4k max (files with hdr10+ and dolby vision profile 8.1)

### ISSUE THREAD

**Issue by bobaoapae** [google/ExoPlayer#11096]
### Bug

 issue with hdr10+.

I have a tcl c825 and firestick 4k max

on the firestick players cannot play this media:

General
Unique ID : 287260790794359083915345060219622240757 (0xD81C6A775E611494CE0759D557FFB1F5)
Complete name : G:\Downloads\Filmes\Cocaine Bear\Cocaine Bear - Get in line..mkv
Format : Matroska
Format version : Version 4
File size : 16.7 GiB
Duration : 1 h 35 min
Overall bit rate : 25.0 Mb/s
Frame rate : 23.976 FPS
Encoded date : 2023-03-14 13:49:23 UTC
Writing application : mkvmerge v73.0.0 ('25 or 6 to 4') 64-bit
Writing library : libebml v1.4.4 + libmatroska v1.7.1

Video
ID : 1
Format : HEVC
Format/Info : High Efficiency Video Coding
Format profile : Main 10@L5@High
HDR format : Dolby Vision, Version 1.0, dvhe.08.06, BL+RPU, HDR10 compatible / SMPTE ST 2094 App 4, Version 1, HDR10+ Profile B compatible
Codec ID : V_MPEGH/ISO/HEVC
Duration : 1 h 35 min
Bit rate : 24.3 Mb/s
Width : 3 836 pixels
Height : 1 602 pixels
Display aspect ratio : 2.40:1
Frame rate mode : Constant
Frame rate : 23.976 FPS
Color space : YUV
Chroma subsampling : 4:2:0 (Type 2)
Bit depth : 10 bits
Bits/(Pixel*Frame) : 0.165
Stream size : 16.2 GiB (97%)
Language : English (US)
Default : Yes
Forced : Yes
Color range : Limited
Color primaries : BT.2020
Transfer characteristics : PQ
Matrix coefficients : BT.2020 non-constant
Mastering display color primaries : Display P3
Mastering display luminance : min: 0.0050 cd/m2, max: 4000 cd/m2
Maximum Content Light Level : 461 cd/m2
Maximum Frame-Average Light Level : 305 cd/m2

Audio
ID : 2
Format : E-AC-3 JOC
Format/Info : Enhanced AC-3 with Joint Object Coding
Commercial name : Dolby Digital Plus with Dolby Atmos
Codec ID : A_EAC3
Duration : 1 h 35 min
Bit rate mode : Constant
Bit rate : 768 kb/s
Channel(s) : 6 channels
Channel layout : L R C LFE Ls Rs
Sampling rate : 48.0 kHz
Frame rate : 31.250 FPS (1536 SPF)
Compression mode : Lossy
Stream size : 525 MiB (3%)
Language : English (US)
Service kind : Complete Main
Default : Yes
Forced : Yes
Complexity index : 16
Number of dynamic objects : 15
Bed channel count : 1 channel
Bed channel configuration : LFE

This happend on all mkv files that have dolby vision 8.1 /hdr10+

Kodi solution to disable hdr10+ fix the issue, without this i have full black screen or duplicate image ([see here](https://preview.redd.it/vt2p4ee0c2oa1.jpeg?width=4032&format=pjpg&auto=webp&v=enabled&s=606052d50a1bf4922cf1951cc532a63c737beeca))

Also TV it's self can play without any issue, just have issue when using firestick

**Comment by tonihei** [comment]
Could you share the media with us for testing? You can send a link to dev.exoplayer@gmail.com with "Issue #11096" in the subject line. It would also help to see a bugreport taken after the playback fails, ideally with an ExoPlayer `EventLogger` attached.

**Comment by bobaoapae** [comment]
Yeah of course, already send email with a link to download media. Bug report i will try get in a moment

**Comment by bobaoapae** [comment]
[bugreport-kara-PS7624.3338N-2023-04-04-13-26-43.zip](https://github.com/google/ExoPlayer/files/11150792/bugreport-kara-PS7624.3338N-2023-04-04-13-26-43.zip)

**Comment by bobaoapae** [comment]
I have 3 medias with this problem, i can attach others if need more information later

**Comment by KyleSanderson** [comment]
This is already fixed in Kodi on Android (by disallowing either HDR10+ or DV). Additionally these devices seem to struggle with Profile 7, forcing 8.1 as a hack seems to work as well.

**Comment by bobaoapae** [comment]
Any news on that?

**Comment by mikemulhearn** [comment]
I have this same issue with Fire TV 4K Max

**Comment by Vorshim92** [comment]
please fix! T.T

**Comment by schadis** [comment]
Still same

**Comment by tonihei** [comment]
@abshankr  Could you have a look into this issue? It seems to be specific to a FireTV stick. If there is a fix or workaround that can be done in ExoPlayer, please feel free to let us know and we can work on integrating it into the library.

**Comment by mdezzi** [comment]
This is a problem for me on all new releases with DV. It's a major issue.

**Comment by NetixQc** [comment]
Still a bug on the Fire Stick 4K Max. Any ETA to fix this? How do we get Amazon to fix it?

**Comment by Leyous** [comment]
I confirm the bug is stille there. Please fix it! :)

**Comment by cobaltduff** [comment]
hello, the same problem keeps happening, it only works well for me with a modded kodi and leaving the choice to play dolby vision or HDR10+. There is some progress. Thank you
Firestick 4k Max , TCL C845

**Comment by Leyous** [comment]
> hello, the same problem keeps happening, it only works well for me with a modded kodi and leaving the choice to play dolby vision or HDR10+. There is some progress. Thank you Firestick 4k Max , TCL C845

Could you please explain how to mod Kodi to give me that choice? Thank you

EDIT: i found the Kodi modded version that has the Fix, but for me, surprisely, it's not working. I'll check again but i tried several time with several config of HDR On/Off.

**Comment by TheLinuxGuy** [comment]
> EDIT: i found the Kodi modded version that has the Fix, but for me, surprisely, it's not working. I'll check again but i tried several time with several config of HDR On/Off.

Link to the modded kodi version so I can try it?

**Comment by Leyous** [comment]
> > EDIT: i found the Kodi modded version that has the Fix, but for me, surprisely, it's not working. I'll check again but i tried several time with several config of HDR On/Off.
> 
> Link to the modded kodi version so I can try it?

This release has the fix -> https://github.com/quietvoid/xbmc/releases/tag/v21-dovi
you must go to options -> video -> uncheck hdr10+ and then play the videos. You must uninstall completely previous kodi versions.

**Comment by NetixQc** [comment]
Seems to be happening also on the newer revision of the Fire Stick 4k and 4k Max (2023)

See https://github.com/jellyfin/jellyfin-androidtv/issues/2630

**Comment by nreis96** [comment]
any updates on this? issue still persists.

**Comment by AALAMILLO** [comment]
Please fix it! Already exists an Amazon exoplayer port who provides support for this problem it seems.... I'm not an expert in android but some ideas will be great 😃👍

**Comment by userobvixus** [comment]
Please fix !! :))

**Comment by Vorshim92** [comment]
guys, try this apk from https://forums.plex.tv/t/plex-for-android/29115/492
Amazon Fire OS Devices (armv7a) version and let me know please

**Comment by Wahab417** [comment]
Any plan on fixing this issue, I see vimu media player for fire TV which uses exoplayer already figured a fix but their app is buggy.

**Comment by bibitocarlos** [comment]
Happening with samsung a54, jellyfin with exoplayer

**Comment by dandud100** [comment]
Same issue on my end with jellyfin + ExoPlayer on 4kmax

**Comment by josemmc95** [comment]
I have the same problem but with HDR10+ only version (SMPTE ST 2094 App 4, Version 1, HDR10+ Profile A compatible).

This mkv doesn't contain any DV profile.

Still no fix, right?

Edit:

I'm using my own Plex Server.

**Comment by laniakea789** [comment]
This also affects the new Google TV Streamer which uses the same SoC as Firestick 4k Max

**Comment by metallicats** [comment]
> This also affects the new Google TV Streamer which uses the same SoC as Firestick 4k Max

Thanks for informing us. I was about to buy the streamer because of this unsolvable issue.

**Comment by AdaptCharm** [comment]
I'm also having the same issue. Can you guys fix?

**Comment by icbaker** [comment]
Duplicating against the equivalent issue in the new issue tracker: https://github.com/androidx/media/issues/1895
