### ISSUE TITLE
How to handle unknown duration when dealing with multiple sources

### ISSUE THREAD

**Issue by IanDBird** [google/ExoPlayer#1110]
Sorry for the vague title, but I came across a scenario that I wasn't entirely sure how best to resolve...

Our application can request a HLS video stream (containing the video and audio tracks) but a separate MKV file that contains the subtitle (SRT) track. This is to allow playback of SRTs without being converted, and also to support progressive downloading of the file. This all works, except...

The MKV file just has the embedded SRT, and therefore no duration associated with with when parsed via the `WebmExtractor`. This means that the text `MediaFormat` it is created with, ends up having a duration of `TrackRenderer.UNKNOWN_TIME_US`. This means that when `ExoPlayerImplInternal.incrementalPrepareInternal` is called, although the other track formats have a valid (and known) duration, due to the missing one from the track format, the duration is recorded as unknown. 

I have the following simple fix/hack, but wanted to know if there was any recommended change that would be better:

```
diff --git a/library/src/main/java/com/google/android/exoplayer/extractor/webm/WebmExtractor.java b/library/src/main/java/com/google/android/exoplayer/extractor/webm/WebmExtractor.java
index 96ce99a..b009026 100644
--- a/library/src/main/java/com/google/android/exoplayer/extractor/webm/WebmExtractor.java
+++ b/library/src/main/java/com/google/android/exoplayer/extractor/webm/WebmExtractor.java
@@ -1244,7 +1244,7 @@ public final class WebmExtractor implements Extractor {
             MediaFormat.NO_VALUE, maxInputSize, durationUs, width, height, initializationData);
       } else if (MimeTypes.APPLICATION_SUBRIP.equals(mimeType)) {
         format = MediaFormat.createTextFormat(Integer.toString(trackId), mimeType,
-            MediaFormat.NO_VALUE, durationUs, language);
+            MediaFormat.NO_VALUE, durationUs == C.UNKNOWN_TIME_US ? C.MATCH_LONGEST_US : durationUs, language);
       } else {
         throw new ParserException("Unexpected MIME type.");
       }
```

**Comment by ojw28** [comment]
It feels like it should be possible for an MKV to define the duration regardless of the fact that it doesn't contain audio/video?

**Comment by IanDBird** [comment]
A very good question @ojw28. It looks like the missing duration is a bug in ffmpeg that we will fix and try to get pushed upstream. I'll still need to work out a local fix to make in ExoPlayer though, as it will take a significant amount of time for an upstream fix to be accepted and then to eventually be released in our own software (and users update).

I'm happy for you to just close this as something that you shouldn't need to handle. I'll probably end up exposing a mechanism to change the default value of `durationUs` to be `C.MATCH_LONGEST_US` when I know that the MKV is being used as only a subtitle container.

**Comment by ojw28** [comment]
I wonder if using `-t` can be used to set the duration. See [here](http://ffmpeg.org/ffmpeg-all.html#Main-options). Just a thought.

Closing as something we shouldn't need ot handle :).

**Comment by IanDBird** [comment]
Our initial investigation was that ffmpeg wasn't handling it when outputting multiple files (e.g. segments for mpegts and also mkv for the remuxed subtitle). However, turns out it was because our own code wasn't asking it to :) That's a lot easier for us to fix.
