### ISSUE TITLE
Exoplayer playing but nothing on surfaceView, only last frame when it ends sometimes

### ISSUE THREAD

**Issue by alenloncaric** [google/ExoPlayer#11102]
Hi,

 i am using 2.18.5 exoplayer and it runs on all our devices ok except on one...  
I get the callback that video is playing but surface is empty all the time. The only thing i sometimes see is the end frame of the video when closing the fragment. In which direction should i look? Any ideas.

thank you for the help in advance!

**Comment by icbaker** [comment]
There isn't really enough information here to help you.

What devices are working and which one has the problem?

Does the issue reproduce in the demo app?
