### ISSUE TITLE
how to make exoplayer2 use H264 codec instead of H265 in Kotlin Android?

### ISSUE THREAD

**Issue by Lz-01** [google/ExoPlayer#11101]
I am trying o create a rtsp stream with the exoplayer2 (release 2.18.5). And i am trying to force the player to use H264. It does not work with the MimeType, because the player overwrites it somehow and uses H265 instead. I think i have to request the codec format before or i have to edit the response body in order to get the codec H264.

resonse.body of the RTSP Stream:

```
...
m=video 0 RTP/AVP 35
a=rtpmap:35 H264/90000
a=rtpmap:102 H265/90000
...
```
this is the code for the exoplayer setup:
```
val url = cameraInfo.cameraURLScheme
val player = ExoPlayer.Builder(context).build()

        // Build the media items.
        val mediaItem = MediaItem.Builder().setMimeType(MimeTypes.VIDEO_H264)
            .setUri(url)
            .build()
    
        val mediaSource = RtspMediaSource.Factory().createMediaSource(mediaItem)
    
        // Add the media items to be played.
        player.addMediaSource(mediaSource)
        // Prepare the player.
        player.prepare()
        // Start the playback.
        player.play()
```
Sidenote: I cannot use the H265 because it does not have the sprop-vps parameter

I have already tried to set the Mimetype and i debugged it and the mediaEncoder was still H265. i get the followig exception

`Caused by: java.io.IOException: java.lang.IllegalArgumentException: missing sprop-vps parameter`

because it uses H265 Format.

**Comment by icbaker** [comment]
Please stop filing duplicate issues on the same topic. Please post any updates to https://github.com/androidx/media/issues/295 (since as you saw when filing this issue, we are not handling new issues in this project).
