### ISSUE TITLE
My CustomMediaCodecSelector does not blacklist H265

### ISSUE THREAD

**Issue by Lz-01** [google/ExoPlayer#11103]
I am trying to use a rtsp stream. the Stream has H264 and H265 Encoding. I need to force use the H264 over H265, because my sprop-vps parameters are not set in H265. My selector should not select the H265 Format. But the code is not being executed properly. This is my Selector:
 ```
class H264MediaCodecSelector : MediaCodecSelector {
    override fun getDecoderInfos(
        mimeType: String,
        requiresSecureDecoder: Boolean,
        requiresTunnelingDecoder: Boolean
    ): MutableList<MediaCodecInfo> {
        Log.d("H264MediaCodecSelector", "getDecoderInfos called")

        val codecInfoList = MediaCodecUtil.getDecoderInfos(mimeType, requiresSecureDecoder, requiresTunnelingDecoder)
        val filteredCodecInfo = mutableListOf<MediaCodecInfo>()
        for (codecInfo in codecInfoList) {
            if (!blacklistedCodec(codecInfo.name.lowercase(Locale.US))){
                filteredCodecInfo.add(codecInfo)
            }
        }

        return filteredCodecInfo
    }


    private fun blacklistedCodec(codecName : String) : Boolean{
        if (codecName.contains(MimeTypes.VIDEO_H265)){
            return true
        }
        return false
    }

}
```
 
 I am calling the selector here:
 
 `val player =exoPlayer.Builder(context).setRenderersFactory(DefaultRenderersFactory(context).setMediaCodecSelector(H264MediaCodecSelector())).build()`

**Comment by icbaker** [comment]
Please stop filing duplicate issues on the same topic. Please post any updates to https://github.com/androidx/media/issues/295 (since as you saw when filing this issue, we are not handling new issues in this project).

**Comment by Lz-01** [comment]
@icbaker cold you reopen it please, because it has not been resolved?
