### ISSUE TITLE
Do I need AdsManager?

### ISSUE THREAD

**Issue by Berlinmeri** [google/ExoPlayer#11119]
Currently I am using Ima extension and using ImaAdsLodar instead of AdsLoader instance. Therefore I can not set onAdsLoadedListener because ImaAdsLoder does not have. Thus I can not initialize adsManager object. My question is, Do I need to create adsManager object or it belongs to imaAdsLoader and I do not need to create again and reach it?
Thanks for help,

**Comment by icbaker** [comment]
The ExoPlayer IMA extension takes care of acquiring an `AdsManager` instance from the IMA SDK here:
https://github.com/google/ExoPlayer/blob/67991cb91f237025d378182aecfcce4ce5c11264/extensions/ima/src/main/java/com/google/android/exoplayer2/ext/ima/AdTagLoader.java#L1336

The ExoPlayer IMA extension doesn't give you direct access to the `AdsManager` instance, but instead proxies calls through its own API. Is there an operation you're trying to do that you can't do via this API?

**Comment by Berlinmeri** [comment]
I’m confused if I should just use adsmanager but as far as I understand I don’t need adsmanager when I use ima extension. Another problem is that AdEvent.STARTED is not triggered when playing a midroll ad. Do you have a suggestion on this subject? How can I detect every ads start?
 
```java
imaAdsLoder = new ImaAdsLoader.Builder(context)
         .setAdEventListener(adEvent -> {
             switch (adEvent.getType()) {
                 case LOADED:
                     break;
                 case STARTED:
                     Log.e("ImaAdsLoader","STARTED");
                     break;
                 case COMPLETED:
                     break;
                 case CONTENT_RESUME_REQUESTED:
                     break;
                 case ALL_ADS_COMPLETED:
                     break;
             }
 
         }).build();
 imaAdsLoader.setPlayer(exoPlayer);


```

**Comment by icbaker** [comment]
> Another problem is that `AdEvent.STARTED` is not triggered when playing a midroll ad.

There isn't enough information to help you with this. When I add the same logging to `PlayerActivity` of the demo app and play the `VMAP pre-, mid- and post-rolls, single ads` sample I see `STARTED` in logcat.

Does your ad tag work as expected when you use it in the [demo app](https://developer.android.com/guide/topics/media/exoplayer/demo-application)?
