### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by AdnanAlami** [google/ExoPlayer#11114]
https://www14.mp4upload.com:282/d/qwxzunpcz3b4quuotkqa4pkijfr7mkwfu7b5wj3padrcjqywm4eaglra/video.mp4
This link is not working for me.
Although I added his own reference.

**Comment by icbaker** [comment]
Hi! Please provide complete information as requested in the question template. The template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/question.md).

Unfortunately we can't answer unclear questions or those with insufficient information.

**Comment by AdnanAlami** [comment]
> يا@AdnanAlami. نحتاج إلى مزيد من المعلومات لحل هذه المشكلة ولكن لم يكن هناك تحديث في 14 يومًا من أيام الأسبوع. أضع علامة على المشكلة على أنها قديمة ، وإذا لم تكن هناك تحديثات جديدة في الأيام السبعة المقبلة ، فسوف أغلقها تلقائيًا.
> 
> إذا كان لديك المزيد من المعلومات التي ستساعدنا في الوصول إلى الجزء السفلي من هذا ، فما عليك سوى إضافة تعليق!



I had found a solution for my problem, but when I uploaded the update of my application in the Google Play Store, I got this error


Your application uses an insecure implementation of the X509TrustManager interface through the Apache HTTP client, which has resulted in a security vulnerability. Please see this Google Help Center article for details, including the deadline to address the vulnerability.


This is the code that I added to solve a problem that was directing me


    public void doTrustToCertificates() {
        TrustManager[] trustAllCerts = new TrustManager[] {
                new X509TrustManager() {
                    public java.security.cert.X509Certificate[] getAcceptedIssuers() {
                        return null;
                    }
                    public void checkClientTrusted(java.security.cert.X509Certificate[] certs, String authType) {
                        //No need to implement.
                    }
                    public void checkServerTrusted(java.security.cert.X509Certificate[] certs, String authType) {
                        //No need to implement.
                    }
                }
        };

        try {
            SSLContext sc = SSLContext.getInstance(getString(R.string.ssl));
            sc.init(null, trustAllCerts, new java.security.SecureRandom());
            HttpsURLConnection.setDefaultSSLSocketFactory(sc.getSocketFactory());
        } catch (Exception e) {
            System.out.println(e);
        }
    }

**Comment by icbaker** [comment]
I'm afraid questions about Play Store policies and SSL certificates are off-topic for this issue tracker.

Closing this issue because the information requested above has not been provided, and so it's unclear what the problem with ExoPlayer being encountered is or how we can help.
