### ISSUE TITLE
Is there a way to play flv live stream with wrong header information?

### ISSUE THREAD

**Issue by xtvj** [google/ExoPlayer#11118]
I need to play the flv stream, but the audio and video flag of the FLV stream header is wrong. The flag is set yes for audio and video,but actually there is only video, and I can't modify the stream. I saw [this answer](https://github.com/google/ExoPlayer/issues/6719#issuecomment-562042710), Exoplayer decodes flv using the FlvExtractor.java -> readFlvHeader() method to determine whether there are audio or video tracks, can FLV decoding be applied to my situation without modifying the source code?

When I use Exoplayer to play the stream, the screen is always black and no error log is printed out.

![2023-04-13 190027](https://user-images.githubusercontent.com/11442821/231809809-ff94f337-0762-43ec-8ad9-bd425834d96f.png)

[demo.flv.zip](https://github.com/google/ExoPlayer/files/11223813/demo.flv.zip)

**Comment by icbaker** [comment]
> can FLV decoding be applied to my situation without modifying the source code?

I don't think so, if you want to adapt ExoPlayer to play your invalid stream you probably need to fork `FlvExtractor` to make those changes. I'm afraid that's outside the scope of what we can offer support for on this issue tracker.
