### ISSUE TITLE
Can't play video dash on Samsung S23 Ultra

### ISSUE THREAD

**Issue by anhtuan1402** [google/ExoPlayer#11121]
### Bug

My app can play video dash from all devicee except s23 ultra.

I have debug show error 
2023-04-15 21:34:12.563 30736-777/? E/ExoPlayerImplInternal: Playback error
      UnknownHostException (no network)

It is error of s23 ultra or exoplayer ?

**Comment by christosts** [comment]
`UnknownHostException (no network)` indicates your device is not connected to the network. Can you check that? The error does not look specific to the library.

**Comment by anhtuan1402** [comment]
> `UnknownHostException (no network)` indicates your device is not connected to the network. Can you check that? The error does not look specific to the library.

Oh, network is normal, I debug then show more:
E/DefaultDrmSession: DRM session error :com.google.android.exoplayer2.drm.MediaDrmCallbackException: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect

**Comment by christosts** [comment]
This error says that the device cannot reach the DRM licence server. The license server is part of your media item configuration. To further help it's best to provide complete information as requested in the issue template, found [here](https://github.com/google/ExoPlayer/issues/new?assignees=&labels=bug%2Cneeds+triage&template=bug.yml).

If you're unable to share [bug reports](https://developer.android.com/studio/debug/bug-report) or test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #1234" ("#1234" is replaced with your issue number). Please also update this issue to indicate you've done this.

**Comment by christosts** [comment]
Apologies for the long delay. I looked at the code you sent us and the URL for the license server does not look like a valid HTTP URL. Is this how you build the URL or did you modify that before you sent it to us?
