### ISSUE TITLE
Add a method to resolve the shuffled position from the Timeline

### ISSUE THREAD

**Issue by tzugen** [google/ExoPlayer#11123]
Currently one has too loop through the Timeline, to figure out to which shuffle position an MediaItem at a given index resolves to:

```
    fun getCurrentShuffleIndex(): Int {
        val timeline = controller?.currentTimeline!!
        val currentMediaItemIndex = controller?.currentMediaItemIndex ?: return -1
        var windowIndex = timeline.getFirstWindowIndex(true)
        var count = 0
        while (windowIndex != C.INDEX_UNSET) {
            count++
            windowIndex = timeline.getNextWindowIndex(
                windowIndex, REPEAT_MODE_OFF,true
            )
            if (windowIndex == currentMediaItemIndex) return count
        }

        return -1
  }
```

It would be great if Timeline would have a method like getShuffledPositionOf(index: Int): Int

**Comment by christosts** [comment]
I see you already posting issues on the Media3 repository (e.g. https://github.com/androidx/media/issues/325), may I ask you to open this issue on the Media3 repository too?
