### ISSUE TITLE
How to start playing a live stream with an offset

### ISSUE THREAD

**Issue by cdongieux** [google/ExoPlayer#11136]
Hi,

I have a live stream with a 4 hours timeshift buffer. I need to start playing this stream with some offset from the live edge. The use case is to be able to start playing at the beginning of a show ; for example it's 10:00 and the show being currently broadcast started at 9:00, so I want ExoPlayer to start playing with a 1 hour offset from the live edge.

I saw this question https://github.com/google/ExoPlayer/issues/6149 but it's quite old and I think API changed. I also see the [LiveConfiguration.targetOffsetMs](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/MediaItem.LiveConfiguration.html#targetOffsetMs) property but it doesn't seem to work as ExoPlayer (2.18.1) starts playing at the live edge whenever I set a targetOffsetMs value or not.
I would like to give this offset at prepare time, to avoid waiting the `Player.STATE_READY` state and do a `seekTo(duration - offset)`.

So my question is: what is the best way to do it?

**Comment by rohitjoins** [comment]
Hi @cdongieux,

Setting [LiveConfiguration.targetOffsetMs](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/MediaItem.LiveConfiguration.html#targetOffsetMs) property on MediaItem allows you to set an offset when playing a live stream.

I tried doing this in the demo app and it works as expected. You can first create a live configuration
```
MediaItem.LiveConfiguration liveConfiguration = new MediaItem.LiveConfiguration.Builder().setTargetOffsetMs(60_000).build();
```
And then set it in the media item by
```
mediaItem.buildUpon().setLiveConfiguration(liveConfiguration).build();
```
Does this not work for you?

**Comment by rohitjoins** [comment]
We're closing this issue because there hasn't been any recent activity.
