### ISSUE TITLE
Custom Rotation Video Renderer Not Working On subsequent Video

### ISSUE THREAD

**Issue by akurni** [google/ExoPlayer#11148]
Hi, I have a question regarding custom video renderer that I created sometimes ago to rotate the video when playing to surface view.

The app uses single player instance (player is kept in activity and the fragment will get the player in activity)
It used to work fine, but it seems now it only works on the first media played (rotated) and when the next fragment with the other video is playing (video is not rotated).

This is my custom video renderer below that I passed through a custom renderers factory when initiating the player
```
    @Override
    protected void onOutputFormatChanged(Format format, @Nullable MediaFormat mediaFormat) {
        Format rotatedFormat = format.buildUpon().setRotationDegrees(rotationDegree).build();
        super.onOutputFormatChanged(rotatedFormat, mediaFormat);
    }

    @Override
    protected MediaFormat getMediaFormat(Format format, String codecMimeType, CodecMaxValues codecMaxValues, float codecOperatingRate, boolean deviceNeedsNoPostProcessWorkaround, int tunnelingAudioSessionId) {
        Format rotatedFormat = format.buildUpon().setRotationDegrees(rotationDegree).build();
        return super.getMediaFormat(rotatedFormat, codecMimeType, codecMaxValues, codecOperatingRate, deviceNeedsNoPostProcessWorkaround, tunnelingAudioSessionId);
    }
```

Any idea? Thanks

**Comment by akurni** [comment]
NVM, this only happens on Emulator, but if there's an explanation for this that will be helpful.

**Comment by christosts** [comment]
I do not have an explanation. Will you be able to provide a a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that demonstrates the problem in a way that we can build and test locally, and also specify what emulator exhibits this. This could be an Android Studio project on GitHub, or zipped up and sent to dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Please also update this issue to indicate you’ve done this.

We might beed to follow up on the emulator for this.

Thanks.

**Comment by akurni** [comment]
Ok will prepare one
