### ISSUE TITLE
Inquiry about LocalMediaDrmCallback

### ISSUE THREAD

**Issue by flashworldnet** [google/ExoPlayer#11140]
I'm trying to use LocalMediaDrmCallback for Widevine protected contents by explicitly providing decryption key. Is it possible to do so? I used this for Clearkey protected contents and it was working fine.

**Comment by marcbaechinger** [comment]
Quoting @icbaker "The LocalMediaDrmCallback looks like a reasonable approach for handling clearkey content when you already have the keys available." from #11146

Still assigning the expert. :)

**Comment by flashworldnet** [comment]
> Quoting @icbaker "The LocalMediaDrmCallback looks like a reasonable approach for handling clearkey content when you already have the keys available." from #11146
> 
> Still assigning the expert. :)

Here, the default KID for the stream is given with Widevine scheme in the manifest. Therefore, providing keys with CLEARKEY_UUID is not helping.

**Comment by appsoft124** [comment]
> I'm trying to use LocalMediaDrmCallback for Widevine protected contents by explicitly providing decryption key. Is it possible to do so? I used this for Clearkey protected contents and it was working fine.

with clearkey your content was working fine ?

**Comment by flashworldnet** [comment]
> > I'm trying to use LocalMediaDrmCallback for Widevine protected contents by explicitly providing decryption key. Is it possible to do so? I used this for Clearkey protected contents and it was working fine.
> 
> with clearkey your content was working fine ?

Not the same content. Two different contents, one is protected with Clearkey and other is with Widevine. For the Clearkey content, my coding was working fine with LocalMediaDrmCallback.

**Comment by appsoft124** [comment]
> > > I'm trying to use LocalMediaDrmCallback for Widevine protected contents by explicitly providing decryption key. Is it possible to do so? I used this for Clearkey protected contents and it was working fine.
> > 
> > 
> > with clearkey your content was working fine ?
> 
> Not the same content. Two different contents, one is protected with Clearkey and other is with Widevine. For the Clearkey content, my coding was working fine with LocalMediaDrmCallback.

Can you send me your email?

**Comment by flashworldnet** [comment]
> > > > I'm trying to use LocalMediaDrmCallback for Widevine protected contents by explicitly providing decryption key. Is it possible to do so? I used this for Clearkey protected contents and it was working fine.
> > > 
> > > 
> > > with clearkey your content was working fine ?
> > 
> > 
> > Not the same content. Two different contents, one is protected with Clearkey and other is with Widevine. For the Clearkey content, my coding was working fine with LocalMediaDrmCallback.
> 
> Can you send me your email?

sure. sanuja.avi@gmail.com

**Comment by appsoft124** [comment]
> > > > > I'm trying to use LocalMediaDrmCallback for Widevine protected contents by explicitly providing decryption key. Is it possible to do so? I used this for Clearkey protected contents and it was working fine.
> > > > 
> > > > 
> > > > with clearkey your content was working fine ?
> > > 
> > > 
> > > Not the same content. Two different contents, one is protected with Clearkey and other is with Widevine. For the Clearkey content, my coding was working fine with LocalMediaDrmCallback.
> > 
> > 
> > Can you send me your email?
> 
> sure. [sanuja.avi@gmail.com](mailto:sanuja.avi@gmail.com)

please check your email

**Comment by appsoft124** [comment]
> > > I'm trying to use LocalMediaDrmCallback for Widevine protected contents by explicitly providing decryption key. Is it possible to do so? I used this for Clearkey protected contents and it was working fine.
> > 
> > 
> > with clearkey your content was working fine ?
> 
> Not the same content. Two different contents, one is protected with Clearkey and other is with Widevine. For the Clearkey content, my coding was working fine with LocalMediaDrmCallback.

can you share your code ?

**Comment by icbaker** [comment]
I can't see how you can use `LocalMediaDrmCallback` to play widevine content. It works for clearkey because the license response for a particular piece of content is the same every time. I'm pretty sure this is not true for widevine (though i don't know the implementation details), because I believe the widevine license response involves a cryptographic handshake with some device-specific as well as content-specific keys. I don't think you can play widevine content without a widevine license server implementation which knows how to generate key response from key requests, and these are normally hosted on an HTTP server somewhere.

I'm going to close this because I don't believe what your asking for is possible.

**Comment by appsoft124** [comment]
> I can't see how you can use `LocalMediaDrmCallback` to play widevine content. It works for clearkey because the license response for a particular piece of content is the same every time. I'm pretty sure this is not true for widevine (though i don't know the implementation details), because I believe the widevine license response involves a cryptographic handshake with some device-specific as well as content-specific keys. I don't think you can play widevine content without a widevine license server implementation which knows how to generate key response from key requests, and these are normally hosted on an HTTP server somewhere.
> 
> I'm going to close this because I don't believe what your asking for is possible.
please fix my issue content not visible video playing but content not visible private void initializePlayer() {
        String URL = "https://1185-vos.dtvott.com/DASH/manifest.mpd";

        DefaultHttpDataSource.Factory defaultHttpDataSourceFactory = new DefaultHttpDataSource.Factory()
                .setUserAgent(USER_AGENT)
                .setTransferListener(new DefaultBandwidthMeter.Builder(this)
                        .setResetOnNetworkTypeChange(false)
                        .build());

        DashChunkSource.Factory dashChunkSourceFactory = new DefaultDashChunkSource.Factory(defaultHttpDataSourceFactory);
        DefaultHttpDataSource.Factory manifestDataSourceFactory = new DefaultHttpDataSource.Factory().setUserAgent(USER_AGENT);

        String keyString = "{\"keys\":[{\"kty\":\"oct\",\"k\":\"DScNTB7yoxmury9CTpsUQg\",\"kid\":\"+tnq96mAMAaGr3gJwDd6AA\"}],'type':\"temporary\"}";


        LocalMediaDrmCallback drmCallback = new LocalMediaDrmCallback(keyString.getBytes());

        DashMediaSource dashMediaSource = new DashMediaSource.Factory(dashChunkSourceFactory, manifestDataSourceFactory)
                .setDrmSessionManagerProvider(mediaItem -> new DefaultDrmSessionManager.Builder()
                        .setPlayClearSamplesWithoutKeys(true)
                        .setMultiSession(true)
                        .setKeyRequestParameters(new HashMap<String, String>())
                        .setUuidAndExoMediaDrmProvider(C.CLEARKEY_UUID, FrameworkMediaDrm.DEFAULT_PROVIDER)
                        .build(drmCallback))

//                .createMediaSource(new MediaItem.Builder()
//                        .setUri(Uri.parse(URL))
//                        .setMimeType(MimeTypes.APPLICATION_MPD)
//                        .setTag(null)
//                        .build());

                .createMediaSource(new MediaItem.Builder()
                                .setUri(Uri.parse(URL))
                                // DRM Configuration
                                .setDrmConfiguration(new MediaItem.DrmConfiguration
                                        .Builder(C.CLEARKEY_UUID).build())
                                .setMimeType(MimeTypes.APPLICATION_MPD)
                                .setTag(null)
                                .build());

        // Prepare the player.
        player = new ExoPlayer.Builder(this).build();
        player.setPlayWhenReady(true);
        binding.playerView.setPlayer(player);
        player.setMediaSource(dashMediaSource, true);
        player.prepare();
        player.addListener(new Player.Listener() {
            @Override
            public void onPlaybackStateChanged(int playbackState) {
                switch (playbackState) {
                    case Player.STATE_IDLE:
                        Log.d("PlayerLogs", "onPlaybackStateChanged - IDLE");
                        break;
                    case Player.STATE_BUFFERING:
                        Log.d("PlayerLogs", "onPlaybackStateChanged - BUFFERING");
                        break;
                    case Player.STATE_READY:
                        Log.d("PlayerLogs", "onPlaybackStateChanged - READY");
                        break;
                    case Player.STATE_ENDED:
                        Log.d("PlayerLogs", "onPlaybackStateChanged - ENDED");
                        break;
                }
                Player.Listener.super.onPlaybackStateChanged(playbackState);
            }


            @Override
            public void onPlayerError(@NonNull PlaybackException error) {
                Log.e("PlayerLogs", "onPlayerError - error: " + error.getMessage(), error);
                Player.Listener.super.onPlayerError(error);
            }
        });
    }
