### ISSUE TITLE
Clipping media source only shows clipped duration in progress bar

### ISSUE THREAD

**Issue by wishygupta** [google/ExoPlayer#11144]
I am using concating media source with clipped media and divided my content into 20 seconds of video each

```
        val userAgent = Util.getUserAgent(this, "Demo")

        val defaultMediaSource = DefaultDataSourceFactory(this, userAgent)
        progressiveMediaSource = ProgressiveMediaSource.Factory(defaultMediaSource)
        val hlsMediaSource = HlsMediaSource.Factory(defaultMediaSource)
        movieMediaSource =
            hlsMediaSource.createMediaSource(MediaItem.Builder()
                .setUri("https://devstreaming-cdn.apple.com/videos/streaming/examples/bipbop_4x3/bipbop_4x3_variant.m3u8")
                .setMediaId("content")
                .build())
        concatMediaSource = ConcatenatingMediaSource(ClippingMediaSource(
            movieMediaSource,
            0 * 1000 * 1000,
            1 * 1000 * 1000))
        player.addMediaSource(concatMediaSource)
        concatMediaSource.addMediaSource(ClippingMediaSource(
            movieMediaSource,
            1 * 1000 * 1000,
            20 * 1000 * 1000)
        )
        concatMediaSource.addMediaSource(ClippingMediaSource(
            movieMediaSource,
            20 * 1000 * 1000,
            40 * 1000 * 1000)
        )
        concatMediaSource.addMediaSource(ClippingMediaSource(
            movieMediaSource,
            40 * 1000 * 1000,
            60 * 1000 * 1000)
        )
```

For every clipped media I get progress bar of 20 seconds and not of 60 seconds.
How can I get of 60 seconds?
and the player.duration returns 20 instead of 60

**Comment by marcbaechinger** [comment]
I think showing 20 seconds is working as intended. If I understand correctly you create 4 windows when you clip this into pieces of 1sec, 19sec, 20sec and 20sec. This then creates four windows with the given durations by default.

You can look into [setShowMultiWindowTimeBar](https://developer.android.com/reference/androidx/media3/ui/PlayerControlView#setShowMultiWindowTimeBar%28boolean%29) that would show all windows at once. Please note that this method is a candidate for being deprecated soon.

Can you elaborate a bit on the use case and why you want to clip the stream into single pieces?

**Comment by wishygupta** [comment]
Basically am working on a video merger application where user will upload some video over cloud. 
And then try to insert other videos in between to it's original video. 
Exoplayer is being used to play the video to show preview to user of what they had made.
User can add a new media source at runtime at any position and the next mediasource / clip will move to next position.
I want to show the user a full progress bar of all the videos / clips they have added to concat media source. Since `[setShowMultiWindowTimeBar](https://developer.android.com/reference/androidx/media3/ui/PlayerControlView#setShowMultiWindowTimeBar%28boolean%29)` will be deprecated will there be an alternatie API for this.

**Comment by marcbaechinger** [comment]
The alternative is using a `ConcatenatingMediaSource2`. But I think for your use case that's not a good replacement, because you can't add/remove media sources once the source is created.
