### ISSUE TITLE
has a Native Crash for ExoPlayer:Playb

### ISSUE THREAD

**Issue by Kasq-Lee** [google/ExoPlayer#11159]
### Bug

I encountered a low-level error while using it, and I did not use the UI component. The main code is as follows:

```
DefaultRenderersFactory defaultRenderersFactory = new DefaultRenderersFactory(context);
        defaultRenderersFactory.setExtensionRendererMode(DefaultRenderersFactory.EXTENSION_RENDERER_MODE_PREFER);
        SimpleExoPlayer.Builder builder = new SimpleExoPlayer.Builder(context, defaultRenderersFactory);
        builder.setMediaSourceFactory(new DefaultMediaSourceFactory(new DefaultHttpDataSource.Factory().setConnectTimeoutMs(10000)));
        mPlayer = builder.build();

    private void initListener() {
        mPlayer.addListener(new Player.Listener() {
            @Override
            public void onPlayerStateChanged(boolean playWhenReady, int playbackState) {
              
            }

            @Override
            public void onPlayerError(@NonNull ExoPlaybackException error) {
              
            }
        });
    }
```

ABI: 'arm'
Timestamp: 2023-05-10 12:44:04-0400
pid: 751, tid: 4552, name: ExoPlayer:Playb  
uid: 10065
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x7ff91500
    r0  80515da0  r1  7ff91500  r2  00000320  r3  00000020
    r4  849e9978  r5  00000340  r6  00000340  r7  7ff91500
    r8  b3ba4edc  r9  b4d78200  r10 00000000  r11 00000000
    ip  00000000  sp  849e9958  lr  b3bc6e3b  pc  b0c68924

backtrace:
      #00 pc 00060924  /apex/com.android.runtime/lib/bionic/libc.so (__memcpy_base_a55+124) (BuildId: 29bc0f9d4101e570b3fe12148d8fe2fc)
      #01 pc 00046e37  /system/lib/libaudioclient.so (android::AudioTrack::write(void const*, unsigned int, bool)+266) (BuildId: 0e6541c880803e2edea73b4a5d4cc008)
      #02 pc 000d8da5  /system/lib/libandroid_runtime.so (int writeToTrack<signed char>(android::sp<android::AudioTrack> const&, int, signed char const*, int, int, bool)+104) (BuildId: 6c99b8fea85d3283f1f3743253b051f0)
      #03 pc 000d631b  /system/lib/libandroid_runtime.so (android_media_AudioTrack_write_native_bytes(_JNIEnv*, _jobject*, _jobject*, int, int, int, unsigned char)+126) (BuildId: 6c99b8fea85d3283f1f3743253b051f0)
      #04 pc 00db710b  /system/framework/arm/boot-framework.oat (art_jni_trampoline+122) (BuildId: 8ebceaef13c8403faa1c5b383dd86cf1fc566ed2)
      #05 pc 010848f7  /system/framework/arm/boot-framework.oat (android.media.AudioTrack.write+398) (BuildId: 8ebceaef13c8403faa1c5b383dd86cf1fc566ed2)
      #06 pc 02028267  /memfd:jit-cache (deleted) (offset 0x2000000) (c.b.a.a.x1.z.Q+710)
      #07 pc 0202af4f  /memfd:jit-cache (deleted) (offset 0x2000000) (c.b.a.a.x1.z.J+190)
      #08 pc 02023347  /memfd:jit-cache (deleted) (offset 0x2000000) (c.b.a.a.x1.z.g+4446)
      #09 pc 0202b36f  /memfd:jit-cache (deleted) (offset 0x2000000) (c.b.a.a.x1.c0.q0+254)
      #10 pc 02029405  /memfd:jit-cache (deleted) (offset 0x2000000) (c.b.a.a.c2.u.T+1644)
      #11 pc 020083db  /memfd:jit-cache (deleted) (offset 0x2000000) (c.b.a.a.c2.u.v+298)
      #12 pc 020210ab  /memfd:jit-cache (deleted) (offset 0x2000000) (c.b.a.a.r0.d+4370)
      #13 pc 02026c17  /memfd:jit-cache (deleted) (offset 0x2000000) (c.b.a.a.r0.handleMessage+2590)
      #14 pc 02059227  /system/framework/arm/boot-framework.oat (android.os.Handler.dispatchMessage+110) (BuildId: 8ebceaef13c8403faa1c5b383dd86cf1fc566ed2)
      #15 pc 0205baf1  /system/framework/arm/boot-framework.oat (android.os.Looper.loop+1376) (BuildId: 8ebceaef13c8403faa1c5b383dd86cf1fc566ed2)
      #16 pc 0205ab73  /system/framework/arm/boot-framework.oat (android.os.HandlerThread.run+250) (BuildId: 8ebceaef13c8403faa1c5b383dd86cf1fc566ed2)
      #17 pc 000d39d5  /apex/com.android.art/lib/libart.so (art_quick_invoke_stub_internal+68) (BuildId: f3dcf6d85f63090693a2a803bf4230f2)
      #18 pc 004eaf13  /apex/com.android.art/lib/libart.so (art_quick_invoke_stub+282) (BuildId: f3dcf6d85f63090693a2a803bf4230f2)
      #19 pc 0012bd2d  /apex/com.android.art/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+148) (BuildId: f3dcf6d85f63090693a2a803bf4230f2)
      #20 pc 003f8777  /apex/com.android.art/lib/libart.so (art::JValue art::InvokeVirtualOrInterfaceWithJValues<art::ArtMethod*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, art::ArtMethod*, jvalue const*)+374) (BuildId: f3dcf6d85f63090693a2a803bf4230f2)
      #21 pc 003f8887  /apex/com.android.art/lib/libart.so (art::JValue art::InvokeVirtualOrInterfaceWithJValues<_jmethodID*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, jvalue const*)+42) (BuildId: f3dcf6d85f63090693a2a803bf4230f2)
      #22 pc 00439995  /apex/com.android.art/lib/libart.so (art::Thread::CreateCallback(void*)+1056) (BuildId: f3dcf6d85f63090693a2a803bf4230f2)
      #23 pc 000aabb3  /apex/com.android.runtime/lib/bionic/libc.so (__pthread_start(void*)+40) (BuildId: 29bc0f9d4101e570b3fe12148d8fe2fc)
      #24 pc 00064023  /apex/com.android.runtime/lib/bionic/libc.so (__start_thread+30) (BuildId: 29bc0f9d4101e570b3fe12148d8fe2fc)

**Comment by marcbaechinger** [comment]
Thanks for your report. Can you let us know how you think the stack trace above is related to video playback with ExoPlayer? 

Like repro steps, ExoPlayer version, what device this is running on what extension renderers you have configured and a bug report would make this report actionable for us. 

Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md). If you're unable to share bug reports or test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #11159". Please also update this issue to indicate you’ve done this.

**Comment by tianyif** [comment]
This one is duplicated with https://github.com/androidx/media/issues/395. Closing this one since https://github.com/androidx/media/issues/395 follows more on the issue template. But we still need more information for https://github.com/androidx/media/issues/395.
