### ISSUE TITLE
Exoplayer without IMA extension in an Android background service

### ISSUE THREAD

**Issue by MaxmaxB** [google/ExoPlayer#11154]
Hello,

I'm currently building an Android Service that run as a system application on Android TV, in background. I'm using the Exoplayer with the IMA library to display ADS on a overlay, on top of other apps. I preload the ads and play them later on and it looks great. However, I sometime face issue, on some devices, when the app underneath is requesting the decoder and if I have a an AD in cache. It will basically call the onPlayerError listener forcing me to release the player.

I've been trying many things, including using different hardware / software decoder and video format. Now here is couple thing i wanted to ask:

- Is it possible to preload the ads by only downloading the file and prepare the codec only when I want to play?
- Is it possible to preload the ads, then release the codec once loaded and grab the codec again when I want to play?

Thank you
Max

**Comment by Maxhoppr** [comment]
I've been digging on that a little bit more and I manage to download the asset without preparing the decoder and only do it once I want to play the video. But I still lost control of the codec sometimes while the video is playing. Now I'm more investigating on using a custom decoder or taking priority of it of an existing one.

**Comment by tonihei** [comment]
> Is it possible to preload the ads by only downloading the file and prepare the codec only when I want to play?
> Is it possible to preload the ads, then release the codec once loaded and grab the codec again when I want to play?

All of this is already happening by default when playing ads with ExoPlayer's IMA extension. Do you have any indication that is does not happen in this way? If so, please provide more concrete reproduction steps, ideally using the ExoPlayer demo app (to avoid any issues introduced by your app code around the library). 

> in background

All interactions with the IMA SDK occur on the main thread of the application and the player has to run on the same thread to avoid any communication problems. Could you also clarify what "background" means in this context exactly?
