### ISSUE TITLE
How to play encrypted files

### ISSUE THREAD

**Issue by Sidnio** [google/ExoPlayer#11151]
###  1.Play ffmpeg-encrypted files

`ffmpeg -i decryption.mp4 -vcodec copy -acodec copy -encryption_scheme cenc-aes-ctr -encryption_key c7e16c4403654b85847037383f0c2db3 -encryption_kid a7e61c373e219033c21091fa607bf3b8 encryption.mp4`

FFMPEG encrypts video

How to play encrypted videos using ExoPlayer

-------------------------------------------------------------------------------------------------------------------------------------
###  2.Play AES-encrypted files
ExoPlayer2 HLS plays aes encrypted files

Or how to play AES encrypted files

 ExoPlayer2 plays AES encrypted files

To play AES-encrypted files with ExoPlayer2, you need to follow these steps:

First, you need to prepare an AES key, which must be the same key that you used to encrypt your files. The key must be a byte array with a length of 16, 24, or 32 bytes.

Next, you need to create a DataSource.Factory object that will be used to open the AES encrypted file. You can use the EncryptedFileDataSourceFactory class to create the object. For example:

```
val cipher = Cipher.getInstance("AES/CBC/PKCS7Padding")
val secretKeySpec = SecretKeySpec(keyData, "AES")
val ivParameterSpec = IvParameterSpec(ivData)
cipher.init(Cipher.DECRYPT_MODE, secretKeySpec, ivParameterSpec)
val defaultHttpDataSourceFactory = DefaultHttpDataSourceFactory(Util.getUserAgent(this, "exo-player"))
val fileDataSourceFactory = DefaultDataSourceFactory(this, null, defaultHttpDataSourceFactory)
val encryptedFileDataSourceFactory = EncryptedFileDataSourceFactory(
cipher,
fileDataSourceFactory
)
```
Here "keyData" and "ivData" are the keys and initialization vectors you use to encrypt your files.

Now you need to create a MediaSource object that will be used to pass the AES encrypted file to ExoPlayer2. You can use the
EncryptedProgressiveMediaSource class to create a MediaSource. For example:
```
val mediaSource = EncryptedProgressiveMediaSource.Factory(encryptedFileDataSourceFactory)
.createMediaSource(Uri.parse("file:///android_asset/encrypted_file.mp4"))
```

Note that the Uri.parse() method here converts the file path to a Uri object.

Finally, pass the MediaSource object to ExoPlayer2. For example:
```
val player = SimpleExoPlayer.Builder(this).build()
player.prepare(mediaSource)
player.play()
```
This way, you can play AES-encrypted files using ExoPlayer2.

![image](https://user-images.githubusercontent.com/33193340/236425164-e89f93b0-0b79-41a1-bb64-6aac5bf4d4b0.png)

# What I want to know is how to implement playback of encrypted files

**Comment by marcbaechinger** [comment]
Can you let me know, what is the intention of your issue? It looks like a documentation page from somewhere else. 

If you don't want to add something about what the intention is, we can close this issue I think?
