### ISSUE TITLE
ExoPlayer ￼

ExoPlayer is an application level media player for Android. The latest version is published as part of AndroidX Media under a new package name and all future development will be in that project.
Please refer to our migration guide and script to move your codebase to the Media3 package names.


### ISSUE THREAD

**Issue by Mikksrund** [google/ExoPlayer#11164]
**Please do not file new issues in this repository.**

All new feature requests should be filed in the
[Media3 issue tracker](https://github.com/androidx/media/issues/new?template=feature_request.md).

We will continue to update and reply to existing issues in this repository and
will keep existing feature requests active.

**Comment by tianyif** [comment]
Hi @Mikksrund,

Please file another issue with using our [issue template](https://github.com/androidx/media/issues/new?assignees=&labels=bug%2Cneeds+triage&template=bug.yml). Thanks!
