### ISSUE TITLE
Pause and play android 13 

### ISSUE THREAD

**Issue by anooravk** [google/ExoPlayer#11162]
### Bug

I'm basically trying to implement ima sdk via android and then passing the view in flutter via method channel but I'm facing an issue that the pause, play, full screen and minimize screen button doesn't work in android 13 while it works perfectly fine with the android version 11

**Comment by tianyif** [comment]
Hi @anooravk,

Please provide complete information as requested in the issue template. The issue template can
be found [here](https://github.com/androidx/media/issues/new?assignees=&labels=bug%2Cneeds+triage&template=bug.yml).
If you're unable to share [bug reports](https://developer.android.com/studio/debug/bug-report) or
test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format
"Issue #1234" ("#1234" is replaced with your issue number). Please also update this issue to
indicate you've done this.

**Comment by tianyif** [comment]
Let's keep tracking the issue in https://github.com/androidx/media/issues/398. Closing this one now.
