### ISSUE TITLE
Freeze for ~50sec when Playing an video which is DRM protected

### ISSUE THREAD

**Issue by almoghzn** [google/ExoPlayer#1116]
Hi,

I'm trying to play video which is DRM protected using ExoPlayer.
My license server is: EZDRM.

When the playback starts, an "executeKeyRequest" of "MediaDrmCallback" is called.
This callback takes ~1.5 seconds.
In that particular time, the "MediaCodecTrackRenderer"."doSomeWork" is still working which cause the "sampleHolder.timeUs" (which is the "presentationTimeUs") to be increased.
When the the license server responded with keys (after ~1.5 seconds as I mentioned), then, the "sampleHolder.timeUs" is around ~100 seconds,
this cause to the "MediaCodecTrackRenderer" to display the frame of 100sec and to be STUCK from seconds ~2 to seconds ~100.

My question is:
1. It is probably a bug which cause to the "sampleHolder.timeUs" to be increased over ~100 sec although it's been through just ~2 sec.

2. I know that using WIdewine DRM it should play 10 seconds of the video unencrypted.
How it is reflect according to what I've just described?

Thanks in advance.

**Comment by almoghzn** [comment]
Hi ojw28,

I'm looking for solution to my issue, 
By searching similar posts, I found Issue #129.

You wrote: "The first 5-10 seconds of the streams may be unencrypted (this is common as a way of allowing playback to start in parallel with the keys being requested)"

I debugged a lot the logic of ExoPlayer, and my findings are:
- ALL of my content is encrypted.
- My content packed using Bento4.
- From the first sample I get: sampleHolder.isEncrypted() = true (in "MediaCodecTrackRenderer"."feedInputBuffer")
- Also from the first fragment I see that the flags indicate that the content is encrypted:
"sampleFlags" = C.SAMPLE_FLAG_ENCRYPTED in: "FragmentedMp4Extractor"."readSample".

When I performed the same tests on ExoPlayer's contents like:
"WV: HDCP required", "WV: Secure video path required", etc...
I found that the first 8 seconds (or so) are NOT encrypted. i.e.:
sampleHolder.isEncrypted() = false

Therefore the media of ExoPlayer starts playing immediately while my media stacked.

What is the solution to my problem?

Also, How can I create dash which is DRM encrypted BUT the first ~8 seconds aren't?

**Comment by ojw28** [comment]
The initial description doesn't sound quite right to me. That aside, whether the front 8 seconds are unencrypted or not shouldn't make much difference (i.e. I don't think it would cause this kind of issue). I think we'd need further information as described [here](https://google.github.io/ExoPlayer/2015/10/01/reporting-issues.html) to investigate further.

**Comment by almoghzn** [comment]
Hi, ojw28 

Thank you for your quick response.

Following more details about the issue:

Scenario:
1. Create mpeg-dash encrypted using Bento4.
2. Play the encrypted mpeg-dash using ExoPlayer Demo.
3. The first frame that ExoPlayer Shows is frame for second ~50.
4. The ExoPlayer keep displaying these frame for ~50 seconds (i.e. until this frame really should display).

ExoPlayer Demo Version:
We have custom ExoPlayer Demo implemented in our project based on ExoPlayer Demo 1.3.1

Device info:
STB
Model: MBX XS
Brand: MyGica
Android version: 4.4.2

Attached (mpeg-dash-ezdrm-exoplayer-demo.txt) logcat of ExoPlayer Demo when I tried to play the encrypted content.
There are log record to debug the process.
You can find that after 01-06 16:17:04.158 the frame is freezing, and at 01-06 16:17:24.768 it's start to play (which is ~20 seconds after).

As I mentioned in my early post, my investigations come to:
1. ExoPlayer start to play the content.
2. The content identified as: hasContentProtection=true
3. A request to the license provider is invoke.
4. While waiting for keys from the license provider, the ExoPlayer does not starts to play.
5. In mean time the presentationTimeUs is increased.
6. When the license provider respond with keys the presentationTimeUs is much higher than the positionUs.
7. There for we are "waiting" until the positionUs will be near by to the presentationTimeUs.

Problems:
1. Why the presentationTimeUs is increased while we are waiting for keys from the license provider?
2. Why ExoPlayer Demo does not start to play the media as you mentioned in Issue #129 ?
3. When I investigate the same flow with Exo Player's content like: "WV: HDCP required", "WV: Secure video path required", etc... It's seems to playing the first 8 seconds and in this time the license server already respond with keys - therefore there was no freeze at all.


[bugreport.txt](https://github.com/google/ExoPlayer/files/80046/bugreport.txt)


[mpeg-dash-ezdrm-exoplayer-demo.txt](https://github.com/google/ExoPlayer/files/80043/mpeg-dash-ezdrm-exoplayer-demo.txt)

**Comment by ojw28** [comment]
ExoPlayer 1.3.1 is way too old for us to be supporting. Please try and reproduce with 1.5.3. Thanks!

**Comment by almoghzn** [comment]
Can you please advise how to create encrypted mpeg-dash that the first x seconds are not encrypted, as ExoPlayer's demo has?

**Comment by ojw28** [comment]
That seems unrelated to this issue, but you should ask for advice on a mailing list associated with the tool that you're using to package your content.
