### ISSUE TITLE
Does IMA uses its own player for ads?

### ISSUE THREAD

**Issue by wishygupta** [google/ExoPlayer#11165]
I have mostly seen in all ads SDK that they use their own player to play ads.
If I am using IMA with exoplayer does it uses application's exoplayer instance to play ads or IMA has its own player to play ads which comes on top of content player when ad is served.

**Comment by marcbaechinger** [comment]
If you are using the IMA extension of ExoPlayer, then the app configures it's player to have the ads support integrated in the `content player` to use the term you are using.

https://github.com/google/ExoPlayer/tree/release-v2/extensions/ima

You can also look into the Developer Guider to see how you can configure your player to have IMA integrated into it: https://developer.android.com/guide/topics/media/exoplayer/ad-insertion
