### ISSUE TITLE
The SurfaceView problem when using multi-player with ViewPager2

### ISSUE THREAD

**Issue by isaacchiang-kkstream** [google/ExoPlayer#11169]
Although I already know that multiple player instances can cause codec issues like these [example search](https://github.com/google/ExoPlayer/issues?q=is%3Aissue++RecyclerView++viewPager). We have a legacy implementation still use multiple player instances architecture.

Another issue we noticed only on android OS version 12+ is that the surface becomes transparent and the content of the next next page can be seen when using viewpager2. I attached the [source code](https://github.com/isaacchiang-kkstream/VideoPage) and [issued video](https://drive.google.com/drive/folders/1sYMemrf0mdc918OmYBePG_7Yx971YFhH?usp=share_link) here for reference. You can see that the problem occurs at 18th - 25th, and 50th second of the video. In fact the codec has an exception, but after press the play button, the current page's player still can playback the content.

Please help guide me how to solve this problem or give me some advice, thanks.

### My testing device information as following:
- name: Pixel 6
- android version: 13

**Comment by MobileLabStudio** [comment]
I have Flutter app with similar functionality (something like TikTok).
My first implementation was built upon "native" MediaPlayer on Android. In this case everything works fantastic. 
Every MediaPlayer lives on his own dedicated Thread. Also preloading multiple videos works well.

I decided to rewrite my implementation and use ExoPlayer (Media3 library) and this isn't even close to MediaPlayer. 
Multiple players throws 4003 and 4001 errors. 

Imo, the use case we are trying to achieve is very common and Google should pay attention on this. I hope the problem will be resolved soon

**Comment by MobileLabStudio** [comment]
@isaacchiang-kkstream I have a good news. Im'a still working on app mentioned in my previous comment.
My player getting stable. Instead of creating new ExoPlayers  try to reuse already created. As soon as my page is 1 page away from currently visible page I release associated ExoPlayer and if next page asks for new ExoPlayer the previous one will be reused.

**Comment by MobileLabStudio** [comment]
I'm still need cache and more efficient preloading strategy (not implemented yet). Here is a video from example app

https://github.com/google/ExoPlayer/assets/75519520/b4e6e4c4-5e14-49a6-aac6-d46cb0ce75ca

**Comment by tonihei** [comment]
If I read this issue correctly, you are mainly asking for guidance, examples and utilities to implement this scrolling view scenario in a reliable, efficient way, right?

We are already working on some preload related new classes and will publish detailed guidance on how to use them once they are ready. So I think the request above will be addressed by this. But in its current form, it's not clear if there is something more specific we need to solve in the meantime. Assuming it's just about the generic guidance and utils, I'll close the issue. Please reopen and file a new one if there I missed an important aspect.
