### ISSUE TITLE
 Request for Demo Code to Access exo_duration TextView in Java Code

### ISSUE THREAD

**Issue by HGSC-Learn** [google/ExoPlayer#11172]
** Request for Demo Code to Access exo_duration TextView in Java Code*

I hope this issue finds you well. I am writing to kindly request a demo code that demonstrates how to access the "exo_duration" TextView in Java code using ExoPlayer. I am particularly interested in understanding how to retrieve and display the duration of a media file being played.

As a backend developer working on a project that involves media playback, I have been exploring the capabilities of ExoPlayer, and I find it to be an excellent library for handling multimedia content. However, I am currently facing a challenge in accessing the "exo_duration" TextView programmatically within my Java code.

I would greatly appreciate it if you could provide me with a demo code snippet or an example that illustrates the process of accessing the "exo_duration" TextView and obtaining the duration value. This would immensely help me in understanding the implementation details and further enhance my development skills with ExoPlayer.

Additionally, if there are any specific instructions or prerequisites for integrating the demo code into an existing project, please provide them along with the code. Any additional documentation or resources related to this topic would also be highly beneficial.

Thank you in advance for your time and support. I eagerly await your response and the requested demo code. If you have any further questions or require more information, please do not hesitate to reach out to me.

Looking forward to your positive response.

Best regards,

HGSC

HGSC.learn@gmail.com

**Comment by tonihei** [comment]
Please file new issues in the media3 issue tracker as requested by the template.

For your actual question: To obtain the duration from the player, you should just be able to call `player.getDuration()` instead of trying to access the text value of an UI element.
