### ISSUE TITLE
OOM Error when use ExoPlayer with Android Auto

### ISSUE THREAD

**Issue by DenysLoboda** [google/ExoPlayer#11179]
### ExoPlayer configuration

```
                ExoPlayer.Builder(reactApplicationContext)
                    .setAudioAttributes(
                        AudioAttributes.Builder()
                            .setUsage(C.USAGE_MEDIA)
                            .setContentType(C.CONTENT_TYPE_MUSIC)
                            .build(),
                        false
                    ).setMediaSourceFactory(
                        DefaultMediaSourceFactory(reactApplicationContext)
                            .setLiveTargetOffsetMs(C.TIME_UNSET) /* use the media-defined default */
                    )
                    .build()
```

### Issue description

When I launch playback for audio stream with active connection to Android Auto I got OOM Error:

<img width="1461" alt="image" src="https://github.com/google/ExoPlayer/assets/109336128/4f2d0fe0-9256-4106-8d45-ed23ac752db2">

If I launch the same stream without connection to android auto all works fine.

**Comment by tonihei** [comment]
The fact that the Android Auto connection seems to cause this OOM indicates that this is something you report to Android Auto instead and the problem is not inside the ExoPlayer library.
