### ISSUE TITLE
The subtitle background is black color

### ISSUE THREAD

**Issue by zlxyc** [google/ExoPlayer#11177]
The subtitle (TTML) background is black color , and the system's subtitle background setting is not effective. This is likely due to the subtitle stream being set with a black background. Hope  add a function can overriding the stream's style.

![cb3424d8642a622580251ed036427c57](https://github.com/google/ExoPlayer/assets/10244713/84a9dbcd-3276-4ec3-9e1e-40b8fa3ae6e5)
![Screenshot_20230524_010439_ar tvplayer tv](https://github.com/google/ExoPlayer/assets/10244713/2708c6c3-e50c-4b47-be8c-f8a831418384)

**Comment by tonihei** [comment]
`SubtitleView` should automatically apply the caption styles defined in the system `CaptioningManager`. 

@icbaker Do you know if the TTML color overrides the system setting or the other way round?

**Comment by icbaker** [comment]
By default 'embedded' styling (i.e. that from the TTML file) is used. You can control this with [`SubtitleView.setApplyEmbeddedStyles(boolean)`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/ui/SubtitleView.html#setApplyEmbeddedStyles(boolean)).

**Comment by icbaker** [comment]
Closing as I believe the question has been answered.
