### ISSUE TITLE
Custom layout and position for subtitles

### ISSUE THREAD

**Issue by thathorizon** [google/ExoPlayer#11175]
Hi! 
I want customize SubtitleView from xml, set font, font size, margin, etc. Also I need change subtitles position based on controls visibility with ConstraintLayout.
How can I do that?

**Comment by tonihei** [comment]
Please file all new issue in the Media3 issue tracker as requested by the template.

Our UI elements provide a useful default UI that can be used as is or as a basis for further customization. See https://developer.android.com/guide/topics/media/exoplayer/ui-components#further_customization where this is mentioned as well. That said, `SubtitleView` already provides out-of-the-box customization options you may find useful, e.g. `setTextSize`, `setStyle`, `setBottomPaddingFraction`, etc.
