### ISSUE TITLE
Why do you add READ_EXTERNAL_STORAGE and WRITE_EXTERNAL_STORAGE permissions to manifest?

### ISSUE THREAD

**Issue by Bylynka** [google/ExoPlayer#1117]
I don't want to have these permissions for marshmallow. I removed these permissions and player works anyway. What do I lose if I remove them? 
I use player only for steaming video.

**Comment by AquilesCanta** [comment]
That is in case you want to reproduce local files through the DemoPlayer. By default, there are none. But if you added any to the Samples list, and the permission was not asked for, the app would crash.
