### ISSUE TITLE
M3U8 URL Playback error (Source error)

### ISSUE THREAD

**Issue by patelakshay13890** [google/ExoPlayer#11170]
Getting Error while playing M3U8 URL in Exo Player...

com.google.android.exoplayer2.ExoPlaybackException: Source error
Caused by: com.google.android.exoplayer2.ParserException: Input does not start with the #EXTM3U header

**Comment by tonihei** [comment]
Note: Please file new issue in the Media3 issue tracker as requested by the template and provide all the information the template asks for.

But just looking at your question it seems that your m3u8 URL doesn't actually contain a valid playlist if it doesn't start with this header. Or it is a M3U playlist, which are not supported (see https://github.com/google/ExoPlayer/issues/4066).
