### ISSUE TITLE
playback of Widevine's DASH live streams is very slowly

### ISSUE THREAD

**Issue by zlxyc** [google/ExoPlayer#11173]
### Bug

ExoPlayer doesn't seem to know from which version had this issue . The playback of Widevine's DASH live streams is very slow. I have tested several players based on ExoPlayer, like: TiviMate, OTT Navigator, and Android TV's Live Channels, and they all have this problem.

**Comment by tonihei** [comment]
Please file new issue in the media3 issue tracker as requested by the template and provide all the requested information too.

On some devices decryption slows down the decoding process and we added an asynchronous mode to ExoPlayer's renderer that should help with this general symptom. It's automatically enabled on devices with API >= 31 and you can manually enable it on lower API versions by calling `DefaultRenderersFactory.forceEnableMediaCodecAsynchronousQueueing()` (and pass this `DefaultRenderersFactory` to `ExoPlayer.Builder.setRenderersFactory`). See https://github.com/google/ExoPlayer/issues/6348 where this was originally reported.
