### ISSUE TITLE
When I load a video from local file, the first frames are lagging and contains green background

### ISSUE THREAD

**Issue by MohamedRejeb** [google/ExoPlayer#11182]
### Bug

When I load a video from local file, the first frames are lagging and contains green background.
And if I disable the playWhenReady, the video preview is just a green screen, it should contain the first frame of the video instead.
I'm using ExoPlayer with ComposeUI,
media3 versons I tried: 1.0.2, 1.1.0-alpha01

https://github.com/google/ExoPlayer/assets/41842296/8f25de52-59d1-4f8f-aeaa-2175d09789ea

**Comment by tonihei** [comment]
Note: Please file new issues in the media3 issue tracker as requested by the template.

This sounds like an issue with your media file, the codec on the device, or both. If you want to debug this further, I suggest you first try to play the same content in the ExoPlayer demo app (to exclude any issues coming from your integration), and then share the file and device details with us. You can also send an email to dev.exoplayer@gmail.com with "Issue #11182" in the subject if you don't want to share it here.

**Comment by MohamedRejeb** [comment]
The problem happens only in the emulator, it's not showing in a real device
