### ISSUE TITLE
ERROR_CODE_PARSING_CONTAINER_MALFORMED 3001 com.google.android.exoplayer2.ParserException: Loading finished before preparation is complete

### ISSUE THREAD

**Issue by liuguangsen** [google/ExoPlayer#11183]
### Bug

Hello, I am trying to add FfmpegExtractor implements Extractor  to Exo Extractors , yes i do it .
But the runtime was wrong.

**Error like this**:
 com.google.android.exoplayer2.ParserException: Loading finished before preparation is complete.

**This error occurred in this part of the source code**：
class: ProgressiveMediaPeriod 
method: maybeThrowPrepareError

Now, can you help me ?
or  
Can you provide some suggestions for extending the FfmpegEx embedding into the ExoPlayer？
.
**My FfmpegExtractor like this.**
`public class FfmpegExtractor implements Extractor {

  private static final int OUTPUT_BUFFER_SIZE_16BIT = 65536;
  private final FfmpegParserJni ffmpegParserJni;
  private final ByteBuffer byteBuffer;
  @Nullable
  private ExtractorInput extractorInput;
  private ExtractorOutput extractorOutput;
  private TrackOutput trackOutput;
  
  private final ParsableByteArray outputBuffer;
  private boolean isParserMetadata = false;

  public FfmpegExtractor(String url) throws FfmpegDecoderException {
                  outputBuffer = new ParsableByteArray();
                  ffmpegParserJni = new FfmpegParserJni(url);
                 byteBuffer = ByteBuffer.allocateDirect(OUTPUT_BUFFER_SIZE_16BIT).order(ByteOrder.nativeOrder());
                 byteBuffer.position(0);
                 byteBuffer.limit(OUTPUT_BUFFER_SIZE_16BIT);
  }

  @Override
  public boolean sniff(ExtractorInput input) throws IOException {
                return true;
  }

  @Override
  public void init(ExtractorOutput output) {
                extractorOutput = output;
                trackOutput = extractorOutput.track(0, C.TRACK_TYPE_AUDIO);
               if (!isParserMetadata) {
                      parserMetadata();
               }
  }

  @Override
  public @ReadResult int read(ExtractorInput input, PositionHolder seekPosition)throws IOException {
                if (!isParserMetadata){
                        parserMetadata();
                        return RESULT_CONTINUE;
                }
                boolean read = ffmpegParserJni.read(byteBuffer);
                if (!read){
                         return RESULT_END_OF_INPUT;
                }
              outputBuffer.reset(byteBuffer.array());
              trackOutput.sampleData(outputBuffer, outputBuffer.limit());
              return RESULT_CONTINUE;
  }

  @Override
  public void seek(long position, long timeUs) {
              ffmpegParserJni.seek(timeUs);
  }

  @Override
  public void release() {
              ffmpegParserJni.release();
  }

  private void parserMetadata() {
   // my audio file format, default
    Format mediaFormat =
        new Format.Builder()
            .setSampleMimeType(MimeTypes.AUDIO_RAW)
            .setAverageBitrate(96648)
            .setPeakBitrate(96648)
            .setMaxInputSize(3689186)
            .setChannelCount(2)
            .setSampleRate(44100)
            .setPcmEncoding(getPcmEncoding(16))
            .build();
    output.format(mediaFormat);
    isParserMetadata = true;
    extractorOutput.endTracks();
  }
}`

**Comment by tonihei** [comment]
I'm afraid we can't really help in detail with app-specific extensions. If you encounter problems using the existing interface, I'd suggest reading the Javadoc in detail again and compare your implementation to an existing default implementation of the same interface in ExoPlayer to find the differences.
