### ISSUE TITLE
Ads volume issue

### ISSUE THREAD

**Issue by Berlinmeri** [google/ExoPlayer#11184]
Hello,
I am using the Google Ima extension. When the ads comes out, there is a sudden increase in sound. How can I prevent this?
Thanks

**Comment by icbaker** [comment]
Please provide a way for us to reproduce the problem. Without that we can only guess about what might be happening, and can't really help you.

Please send the stream and ads config to dev.exoplayer@gmail.com using the subject `Issue #11184` in a form we can play in our [demo app](https://exoplayer.dev/demo-application.html). Please also update this issue to indicate you’ve done this.
