### ISSUE TITLE
How to re-open an issue ?

### ISSUE THREAD

**Issue by ZygmuntMalek** [google/ExoPlayer#11196]
I've created an issue https://github.com/google/ExoPlayer/issues/11019
which were closed by bot ( I had to wait for client which will deliver content for reproduction - which took some time ) but after sending email and add notify comment - nothing changes

**Comment by icbaker** [comment]
I've re-opened it, sorry I missed your comment.

**Comment by ZygmuntMalek** [comment]
My Issue were re-opened and marked as need more info but in the same time - I don't have rights to write in that ticket ( I've got more info )

**Comment by icbaker** [comment]
I've unlocked it
