### ISSUE TITLE
Exoplayer with LiveTV stream no sound 

### ISSUE THREAD

**Issue by miraclecra** [google/ExoPlayer#11197]
### Bug

Hi, Support 
Hope you are doing well.
I am developing one TV app with Exoplayer. 
For the Live streaming channel, there is no audio. A few channels are working with audio. But most channels are playing without audio.
Actually, these live channels have their own audio which is played by other players well.
I invested time in it but not found a good result.
Hope you fix this issue asap.

Thanks

**Comment by oceanjules** [comment]
Hi! Thank you for reporting an issue, however, in order for us to help you, we would need a more detailed report. We could then try reproducing this problem locally.

For that we have an issue template - please navigate [here](https://github.com/androidx/media/issues/new?assignees=&labels=bug%2Cneeds+triage&template=bug.yml).

If you're unable to share [bug reports](https://developer.android.com/studio/debug/bug-report) or the content you are using for testing publicly, then please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #1234" ("#1234" is replaced with your issue number). If you've done this, then please also update this issue afterwards.
