### ISSUE TITLE
Configure license clearkey

### ISSUE THREAD

**Issue by lionelyayan** [google/ExoPlayer#11198]
Hello everyone,

I managed to make a license configuration of type com.widevine.alpha.
this is the configuration.

```
player = new ExoPlayer.Builder(this, renderersFactory)
        .setTrackSelector(new DefaultTrackSelector(this))
        .setMediaSourceFactory(new DefaultMediaSourceFactory(this)
                .setDataSourceFactory(dataSourceFactory()))
        .build();

MediaItem.DrmConfiguration drmConfiguration = new MediaItem.DrmConfiguration.Builder(C.WIDEVINE_UUID)
        .setLicenseUri(Uri.parse(licenseKey))
        .setMultiSession(true)
        .build();
            
player.setMediaItem(new MediaItem.Builder()
      .setUri(Uri.parse(videoUri))
      .setDrmConfiguration(drmConfiguration)
      .build());
```

Then what about the configuration for type clearkey and org.w3.clearkey licenses? which is where the contents are not uri

clearkey:
`45eec91ce119fb6b1f3dd691cfaafdc6:8422e38ab1099ea6ac48224eeda057dd`

org.w3.clearkey:
`{"keys":[{"kty":"oct","kid":"x1-gd_kiXYMZpPECWc_w14","k":"vw5XYgDnI70Cv2DZtdARQq"},{"kty":"oct","kid":"U_izmERjXBystrRo1Gpigf","k":"_iDeFrAjiMzaA-pyGfQOr0"},{"kty":"oct","kid":"y6VR2QDaO_SuywlnYt-mQ5","k":"pq3xHGXKiqol9aoWj6glDA"}]}`

org.w3.clearkey:
`{"keys":[{"kty":"oct","k":"MGQ2NzEyYmYyYTg0ZWRjYzkzZDAwMWE5NjEzZjZmZWM","kid":"Y2ZiNWUyYjczYmVmNGYzYzg3OGYyNWFiODZhNzQ1MWY"}],'type':"temporary"}`

Thank you for your answer

**Comment by oceanjules** [comment]
Have you tried looking into the following:

- https://github.com/google/ExoPlayer/issues/3178
- https://github.com/google/ExoPlayer/issues/3201

and playing around with `LocalMediaDrmCallback` and `DefaultDrmSessionManager`?

Since you haven't set `drmSessionManagerProvider` of your `DefaultMediaSourceFactory`, it defaults to `DefaultDrmSessionManagerProvider`. And that implementation looks at your `MediaItem.DrmConfiguration` and gives you back `DefaultDrmSessionManager` with `HttpMediaDrmCallback` callback. Whereas instead, you could build your manager with a local callback `DefaultDrmSessionManager.Builder()....build(localCallback);`

**Comment by icbaker** [comment]
As @oceanjules says you should use `LocalMediaDrmCallback` and plumb your `DefaultDrmSessionManager` in as described here: https://developer.android.com/guide/topics/media/exoplayer/drm#using-a-custom-drmsessionmanager

**Comment by lionelyayan** [comment]
I've made `LocalMediaDrmCallback` and `DefaultDrmSessionManager`.

but the video comes out just blank black.
this is the configuration.
```
String keyString = "{"keys":[{"kty":"oct","kid":"x1-gd_kiXYMZpPECWc_w14","k":"vw5XYgDnI70Cv2DZtdARQq"},{"kty":"oct","kid":"U_izmERjXBystrRo1Gpigf","k":"_iDeFrAjiMzaA-pyGfQOr0"},{"kty":"oct","kid":"y6VR2QDaO_SuywlnYt-mQ5","k":"pq3xHGXKiqol9aoWj6glDA"}]}";

DefaultDrmSessionManager drmSessionManager = new DefaultDrmSessionManager.Builder().build(
       new LocalMediaDrmCallback(keyString.getBytes()));

MediaSource.Factory mediaSourceFactory =
      new DefaultMediaSourceFactory(this)
              .setDataSourceFactory(dataSourceFactory())
              .setDrmSessionManagerProvider(mediaItem -> drmSessionManager);

player = new ExoPlayer.Builder(this, renderersFactory)
        .setTrackSelector(new DefaultTrackSelector(this))
        .setMediaSourceFactory(mediaSourceFactory)
        .build();

DataSource.Factory dataSourceFactory = new DefaultHttpDataSource.Factory();
MediaSource mediaSource = new DashMediaSource.Factory(dataSourceFactory)
        .createMediaSource(MediaItem.fromUri(Uri.parse(videoUri)));

player.setMediaSource(mediaSource);
```


could you please correct if there is an error in the configuration.
thank you very much for the answer

**Comment by icbaker** [comment]
Two problems I can see at first glance:

* You don't set the scheme UUID of your `DefaultDrmSessionManager`, which means it [defaults to widevine](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/drm/DefaultDrmSessionManager.Builder.html#%3Cinit%3E()).

* You set a `MediaSourceFactory` on your `ExoPlayer.Builder`, but then you directly instantiate a `MediaSource` and pass it to `ExoPlayer.setMediaSource` (thus bypassing the `MediaSourceFactory` you've set on the player). This means your custom `DefaultDrmSessionManager` is not being used. See more info: https://developer.android.com/guide/topics/media/exoplayer/media-sources#media-source-based-playlist-api

**Comment by lionelyayan** [comment]
hello @icbaker 
I've made like this

```
String keyString = "{"keys":[{"kty":"oct","kid":"x1-gd_kiXYMZpPECWc_w14","k":"vw5XYgDnI70Cv2DZtdARQq"},{"kty":"oct","kid":"U_izmERjXBystrRo1Gpigf","k":"_iDeFrAjiMzaA-pyGfQOr0"},{"kty":"oct","kid":"y6VR2QDaO_SuywlnYt-mQ5","k":"pq3xHGXKiqol9aoWj6glDA"}]}";

DefaultDrmSessionManager drmSessionManager = new DefaultDrmSessionManager.Builder()
     .setMultiSession(false)
     .setUuidAndExoMediaDrmProvider(C.CLEARKEY_UUID, FrameworkMediaDrm.DEFAULT_PROVIDER)
     .build(new LocalMediaDrmCallback(keyString.getBytes()));

DefaultMediaSourceFactory mediaSourceFactory = new DefaultMediaSourceFactory(this)
     .setDataSourceFactory(new DefaultHttpDataSource.Factory());

mediaSourceFactory.createMediaSource(MediaItem.fromUri(Uri.parse(videoUri)));
mediaSourceFactory.setDrmSessionManagerProvider(mediaItem -> drmSessionManager);

player = new ExoPlayer.Builder(this, new DefaultRenderersFactory(this).forceEnableMediaCodecAsynchronousQueueing())
     .setTrackSelector(new DefaultTrackSelector(this))
     .setMediaSourceFactory(mediaSourceFactory)
     .build();

player.setMediaItem(new MediaItem.Builder()
     setUri(Uri.parse(videoUri))
     .build());

playerView.setPlayer(player);
```

but still not working, please tell me the correct configuration syntax.

Thank you for your answer

**Comment by icbaker** [comment]
You don't appear to be [preparing](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/Player.html#prepare()) your `Player` or triggering playback with `play()` or `setPlayWhenReady()`.

You might want to try with a non-DRM asset to start with, get that working, then iterate from there. I'm afraid we don't have capacity to offer this level of high touch support, so I won't be replying again on this issue - I recommend you look for answers in our docs: https://developer.android.com/guide/topics/media/exoplayer

**Comment by lionelyayan** [comment]
Thanks for the answer, apparently the problem is in the reverse key license
