### ISSUE TITLE
Does Exoplayer support eac3-joc?

### ISSUE THREAD

**Issue by astroncc** [google/ExoPlayer#11201]
Does Exoplayer support eac3-joc or eac3?
The device used is Galaxy S22.

Does it support playback on mobile devices? Does it support playback in Android's default codec?

Both EXTENSION_RENDERER_MODE_OFF and EXTENSION_RENDERER_MODE_PREFER will play regardless.

Below is the log that comes out when playing.

tracks [eventTime=0.08, mediaPos=0.00, window=0, period=0
group [
[X] Track:0, id=1, mimeType=video/avc, codecs=avc1.4D4028, res=1920x1080, fps=24.0, supported=YES
]
group [
[ ] Track:0, id=2, mimeType=audio/eac3-joc, bitrate=448000, channels=6, sample_rate=48000, language=und, supported=YES
]
]

**Comment by microkatz** [comment]
Yes Exoplayer supports eac3-joc and eac3. You said that there is playback happening. Is the audio not playing during playback?

If there is a hardware or software codec that supports the format then it will play. It seems based on your log snippet that there is some decoder available to play the audio.

**Comment by yyms3275** [comment]
Thank you for your answer. 👍🏻😀👍🏻

It plays well. Is the EAC3 audio codec not subject to a separate license? 

I know it as Dolby audio codec. If you upload the Player app to the Google Store and then service it, I'm worried about the license issue. 

Generally, there is no problem with playback at the time of H/W decoder, so shouldn't we prevent audio playback at the time of S/W decoder? 

For example, the MX player is playing by adding a separate external codec instead of playing it as a codec that is not supported by the S/W decoder.

**Comment by astroncc** [comment]
> Yes Exoplayer supports eac3-joc and eac3. You said that there is playback happening. Is the audio not playing during playback?
> 
> If there is a hardware or software codec that supports the format then it will play. It seems based on your log snippet that there is some decoder available to play the audio.

Thank you for your answer. 👍🏻😀👍🏻

It plays well. Is the EAC3 audio codec not subject to a separate license?

I know it as Dolby audio codec. If you upload the Player app to the Google Store and then service it, I'm worried about the license issue.

Generally, there is no problem with playback at the time of H/W decoder, so shouldn't we prevent audio playback at the time of S/W decoder?

For example, the MX player is playing by adding a separate external codec instead of playing it as a codec that is not supported by the S/W decoder.

**Comment by microkatz** [comment]
Thank you for your patience. I'm sorry, but I am not at liberty to advise on licensing concerns for commercial apps. I would suggest contacting Dolby with the parameters of how you intend to use their encodings and your questions. 

I'm going to close the issue.
