### ISSUE TITLE
Offline video playback (non drm but encrypted)

### ISSUE THREAD

**Issue by amitsamal** [google/ExoPlayer#1120]
Hi Team,

Our requirement is to play offline videos using exoplayer. The videos can be encrypted with any encryption format and downloaded on the user device. We need to decrypt it and then play it using exoplayer. We thought of decrypting the file and then using NanoHTTPD server to stream the bytes to exoplayer. Is it possible to do offline using this approach or any other technique you would recommend us for handling this scenario.

Thanks 
Amit Samal

**Comment by ojw28** [comment]
The best approach is to create your own `DataSource` to perform the decryption. Your implementation should wrap another `DataSource` that can be used to read the still encrypted data (you'd probably wrap a `FileDataSource`, but there's no reason not to allow wrapping of arbitrary sources). The read method of your implementation should read encrypted data from the wrapped source, decrypt it, and return the decrypted data to the caller.

**Comment by chile-zhong** [comment]
Hi,any updates? Thanks!
