### ISSUE TITLE
Exo Player produces too much Log in Android Studio Logger

### ISSUE THREAD

**Issue by atiqmumtaz507** [google/ExoPlayer#11208]
### Bug

SDK produces too much log and I see no option to disable or filter that log. Due to this I miss the log which the app classes produces. Is there any way existing in the SDk to disable logging?

**Comment by atiqmumtaz507** [comment]
14:17:40.690  D  Huffman Builder run in subthread
14:17:40.693  D  Tile Decoder (#thread:3, size:256 256 208 x544, alignment:256x16)
14:17:40.731  D  stream getLength() not supported, use temp buffer for loading stream, buffer addr 0x7877130000 length 98810
14:17:40.731  D  LoadInputStreamToMem va 0x7877130000  size 100992
14:17:40.732  D  Huffman Builder run in subthread
14:17:40.734  D  Tile Decoder (#thread:3, size:256 256 208 x544, alignment:256x16)
14:17:40.769  D  stream getLength() not supported, use temp buffer for loading stream, buffer addr 0x7877130000 length 98810
14:17:40.769  D  LoadInputStreamToMem va 0x7877130000  size 100992
14:17:40.771  D  Huffman Builder run in subthread
14:17:40.773  D  Tile Decoder (#thread:3, size:256 256 208 x544, alignment:256x16)
14:17:40.802  D  stream getLength() not supported, use temp buffer for loading stream, buffer addr 0x7877130000 length 98810
14:17:40.803  D  LoadInputStreamToMem va 0x7877130000  size 100992
14:17:40.804  D  Huffman Builder run in subthread
14:17:40.805  D  Tile Decoder (#thread:3, size:256 256 208 x544, alignment:256x16)
14:17:40.842  D  stream getLength() not supported, use temp buffer for loading stream, buffer addr 0x7877130000 length 98810
14:17:40.842  D  LoadInputStreamToMem va 0x7877130000  size 100992
14:17:40.844  D  Huffman Builder run in subthread
14:17:40.846  D  Tile Decoder (#thread:3, size:256 256 208 x544, alignment:256x16)
14:17:40.878  D  stream getLength() not supported, use temp buffer for loading stream, buffer addr 0x7877130000 length 98810
14:17:40.878  D  LoadInputStreamToMem va 0x7877130000  size 100992
14:17:40.880  D  Huffman Builder run in subthread
14:17:40.883  D  Tile Decoder (#thread:3, size:256 256 208 x544, alignment:256x16)
14:17:40.914  D  stream getLength() not supported, use temp buffer for loading stream, buffer addr 0x7877130000 length 98810
14:17:40.914  D  LoadInputStreamToMem va 0x7877130000  size 100992
14:17:40.916  D  Huffman Builder run in subthread
14:17:40.918  D  Tile Decoder (#thread:3, size:256 256 208 x544, alignment:256x16)
14:17:40.950  D  stream getLength() not supported, use temp buffer for loading stream, buffer addr 0x7877130000 length 98810
14:17:40.950  D  LoadInputStreamToMem va 0x7877130000  size 100992
14:17:40.951  D  Huffman Builder run in subthread
14:17:40.952  D  Tile Decoder (#thread:3, size:256 256 208 x544, alignment:256x16)
14:17:40.988  D  stream getLength() not supported, use temp buffer for loading stream, buffer addr 0x7877130000 length 98810
14:17:40.988  D  LoadInputStreamToMem va 0x7877130000  size 100992
14:17:40.990  D  Huffman Builder run in subthread
14:17:40.992  D  Tile Decoder (#thread:3, size:256 256 208 x544, alignment:256x16)
14:17:41.027  D  stream getLength() not supported, use temp buffer for loading stream, buffer addr 0x7877130000 length 98810
14:17:41.027  D  LoadInputStreamToMem va 0x7877130000  size 100992
14:17:41.029  D  Huffman Builder run in subthread
14:17:41.031  D  Tile Decoder (#thread:3, size:256 256 208 x544, alignment:256x16)
14:17:41.065  D  stream getLength() not supported, use temp buffer for loading stream, buffer addr 0x7877130000 length 98810
14:17:41.065  D  LoadInputStreamToMem va 0x7877130000  size 100992
14:17:41.067  D  Huffman Builder run in subthread
14:17:41.069  D  Tile Decoder (#thread:3, size:256 256 208 x544, alignment:256x16)
14:17:41.104  D  stream getLength() not supported, use temp buffer for loading stream, buffer addr 0x7877130000 length 98810
14:17:41.104  D  LoadInputStreamToMem va 0x7877130000  size 100992
14:17:41.106  D  Huffman Builder run in subthread
14:17:41.108  D  Tile Decoder (#thread:3, size:256 256 208 x544, alignment:256x16)
14:17:41.144  D  stream getLength() not supported, use temp buffer for loading stream, buffer addr 0x7877130000 length 98810
14:17:41.144  D  LoadInputStreamToMem va 0x7877130000  size 100992
14:17:41.146  D  Huffman Builder run in subthread
14:17:41.148  D  Tile Decoder (#thread:3, size:256 256 208 x544, alignment:256x16)
14:17:41.185  D  stream getLength() not supported, use temp buffer for loading stream, buffer addr 0x7877130000 length 98810
14:17:41.185  D  LoadInputStreamToMem va 0x7877130000  size 100992
14:17:41.187  D  Huffman Builder run in subthread
14:17:41.189  D  Tile Decoder (#thread:3, size:256 256 208 x544, alignment:256x16)
14:17:41.204  I  state->set(STOPPING)
14:17:41.211  D  [GraphicBufferSource](id:555300000001,api:2,p:21843,c:21843) disconnect
14:17:41.211  I  state->set(ALLOCATED)
14:17:41.212  I  state->set(RELEASING)
14:17:41.212  I  [c2.mtk.avc.encoder] release(1)
14:17:41.213  D  reset()
14:17:41.213  D  Video track stopping. Stop source
14:17:41.213  D  Video track source stopping
14:17:41.213  D  Video track source stopped
14:17:41.213  V  Track event err/info msg:101, trackId:1, type:1000,val:-1011
14:17:41.213  I  Received total/0-length (99/0) buffers and encoded 99 frames. - Video
14:17:41.214  D  Video track stopped. Status:0. Stop source
14:17:41.214  D  0 chunks are written in the last batch
14:17:41.214  D  WriterThread stopped. Status:0
14:17:41.217  I  state->set(RELEASED)
14:17:41.217  I  Codec shutdown complete
14:17:41.218  I  onLastStrongRef automatically unlinking death recipients
14:17:41.236  I  Adjust the moov start time from 0 us -> -90100 us
14:17:41.240  I  The mp4 file will not be streamable.
14:17:41.240  I  MOOV atom was written to the file
14:17:41.240  D  release()
14:17:41.240  D  ftruncate mPreAllocateFileEndOffset:54198 mOffset:52392 mMdatEndOffset:50130 diff:1806
14:17:41.240  D  MP4WtrCtrlHlpLooper stopped
14:17:41.240  I  Top 5 write durations(microseconds): #1:96 #2:102 #3:177 #4:2682 #5:17766
14:17:41.240  D  reset()
14:17:41.240  D  Video track stopping. Stop source
14:17:41.240  E  Stop() called but track is not started or stopped
14:17:41.406  D  tagSocket(6) with statsTag=0xffffffff, statsUid=-1
14:17:46.153  I  Background concurrent copying GC freed 475454(19MB) AllocSpace objects, 222(6768KB) LOS objects, 49% free, 17MB/35MB, paused 739us,361us total 116.568ms
14:17:46.162  W  A resource failed to call end. 
14:17:52.497  I  Background concurrent copying GC freed 388130(16MB) AllocSpace objects, 9(640KB) LOS objects, 50% free, 23MB/46MB, paused 458us,114us total 135.806ms
14:17:52.644  W  JNI critical lock held for 23.658ms on Thread[81,tid=22048,Runnable,Thread*=0xb400007746471400,peer=0x17295cb0,"sl-7-vsave-1"]
14:17:52.717  D  PreAllocation enabled
14:17:52.720  I  state->set(ALLOCATING)
14:17:52.720  I  allocate(c2.mtk.avc.encoder)
14:17:52.723  I  setting up 'default' as default (vendor) store
14:17:52.733  I  Created component [c2.mtk.avc.encoder]
14:17:52.733  I  state->set(ALLOCATED)
14:17:52.733  D  read media type: video/avc
14:17:52.737  D  extent() != 1 for single value type: algo.buffers.max-count.values
14:17:52.738  D  extent() != 1 for single value type: output.subscribed-indices.values
14:17:52.738  D  extent() != 1 for single value type: input.buffers.allocator-ids.values
14:17:52.738  D  extent() != 1 for single value type: output.buffers.allocator-ids.values
14:17:52.739  D  extent() != 1 for single value type: algo.buffers.allocator-ids.values
14:17:52.739  D  extent() != 1 for single value type: output.buffers.pool-ids.values
14:17:52.739  D  extent() != 1 for single value type: algo.buffers.pool-ids.values
14:17:52.741  D  ignored struct field coding.gop.values
14:17:52.743  D  ignored struct field coding.qp.values
14:17:52.745  D  ignoring local param raw.color (0xc2001809) as it is already supported
14:17:52.745  I  query failed after returning 22 values (BAD_INDEX)
14:17:52.746  D  c2 config diff is Dict {
                   c2::u32 algo.bitrate-mode.value = 3
                   c2::u32 algo.delay.value = 8
                   c2::i32 algo.priority.value = 0
                   c2::u32 algo.quality.value = 80
                   c2::float algo.rate.value = 0
                   c2::i32 coded.average-qp.value = 0
                   c2::u32 coded.bitrate.value = 64000
                   c2::float coded.frame-rate.value = 30
                   c2::u32 coded.pl.level = 20494
                   c2::u32 coded.pl.profile = 20484
                   c2::u32 coded.tile-layout.columns = 2
                   c2::u32 coded.tile-layout.order = 0
                   c2::u32 coded.tile-layout.rows = 1
                   c2::u32 coded.tile-layout.tile.height = 256
                   c2::u32 coded.tile-layout.tile.width = 256
                   c2::u32 coded.vui.color.matrix = 0
                   c2::u32 coded.vui.color.primaries = 0
                   c2::u32 coded.vui.color.range = 0
                   c2::u32 coded.vui.color.transfer = 0
                   c2::u32 coding.intra-refresh.mode = 0
                   c2::float coding.intra-refresh.period = 0
                   c2::u32 coding.request-sync-frame.value = 0
                   c2::i64 coding.sync-frame-interval.value = 1000000
                   Buffer coding.temporal-layering = {
                     00000000:  10 00 00 00 07 20 01 52  00 00 00 00 00 00 00 00  ..
14:17:52.746  W  expected specified color aspects (0:0:0:0)
14:17:52.748  D  raise bitrate: configured 160000 to floor 691200
14:17:52.748  D  minquality: requested QP unsupported, boost bitrate 691200 by 138240
14:17:52.748  D  minquality/target bitrate raised from 160000 to 829440 bps
14:17:52.748  D  shapeMediaFormat: deltas(2): AMessage(what = 0x00000000) = {

**Comment by atiqmumtaz507** [comment]
one way is to add this in android studio Logcat filter manually:
package:mine  -tag:MPEG4Writer -tag:CCodec -tag:libjpeg-alpha -tag:skia -tag:Codec2Client -tag:GraphicBufferSource -tag:MediaCodec -tag:C2OMXNode -tag:BufferQueueConsumer -tag:ColorUtils -tag:VQApply -tag:ReflectedParamUpdater -tag:MediaWriter -tag:hw-BpHwBinder -tag:TrafficStats -tag:audit

**Comment by rohitjoins** [comment]
Correct, you can query logs using https://developer.android.com/studio/debug/logcat#key-value-search. Does this help with your issue?

**Comment by rohitjoins** [comment]
You can also simply type something into the search box at the top and it should filter only messages containing the text you typed. 

The other option would be to right click on the line you don't like and select `Fold Lines like this`.
![Screenshot 2023-06-13 at 15 46 49](https://github.com/google/ExoPlayer/assets/32570096/b7b7278b-8b5f-431d-991f-4a0440e7f910)

**Comment by icbaker** [comment]
I don't believe any (?) of the logs quoted in https://github.com/google/ExoPlayer/issues/11208#issuecomment-1589200187 are coming from this library (ExoPlayer). They are all coming from Android framework components (some of which this library uses, but we have no control over their logging).

If you believe they're coming from this library please link to the lines in our code that are creating them.
