### ISSUE TITLE
exoplayer has a runtime error report

### ISSUE THREAD

**Issue by huihui-Android** [google/ExoPlayer#11204]
### Bug

here is the log :

06-12 09:40:24.227  9918  9918 W System.err: com.google.android.exoplayer2.ExoPlaybackException: Unexpected runtime error
06-12 09:40:24.227  9918  9918 W System.err: 	at com.google.android.exoplayer2.ExoPlayerImpl.lambda$release$5(ExoPlayerImpl.java:995)
06-12 09:40:24.227  9918  9918 W System.err: 	at com.google.android.exoplayer2.-$$Lambda$ExoPlayerImpl$mmvudecqiJgKISRfILg_QG9WU-M.invoke(Unknown Source:2)
06-12 09:40:24.227  9918  9918 W System.err: 	at com.google.android.exoplayer2.util.ListenerSet$ListenerHolder.invoke(ListenerSet.java:330)
06-12 09:40:24.227  9918  9918 W System.err: 	at com.google.android.exoplayer2.util.ListenerSet.lambda$queueEvent$0(ListenerSet.java:214)
06-12 09:40:24.227  9918  9918 W System.err: 	at com.google.android.exoplayer2.util.-$$Lambda$ListenerSet$NbKDn9xtItiyMgYZmjIx_Sv1FFQ.run(Unknown Source:6)
06-12 09:40:24.227  9918  9918 W System.err: 	at com.google.android.exoplayer2.util.ListenerSet.flushEvents(ListenerSet.java:236)
06-12 09:40:24.227  9918  9918 W System.err: 	at com.google.android.exoplayer2.util.ListenerSet.sendEvent(ListenerSet.java:251)
06-12 09:40:24.227  9918  9918 W System.err: 	at com.google.android.exoplayer2.ExoPlayerImpl.release(ExoPlayerImpl.java:991)
06-12 09:40:24.227  9918  9918 W System.err: 	at com.google.android.exoplayer2.SimpleExoPlayer.release(SimpleExoPlayer.java:1079)
06-12 09:40:24.227  9918  9918 W System.err: 	at com.tencent.wecarflow.media.player.exo.ExoPlayerImpl$3.run(ExoPlayerImpl.java:338)
06-12 09:40:24.228  9918  9918 W System.err: 	at android.os.Handler.handleCallback(Handler.java:938)
06-12 09:40:24.228  9918  9918 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:99)
06-12 09:40:24.228  9918  9918 W System.err: 	at android.os.Looper.loop(Looper.java:223)
06-12 09:40:24.228  9918  9918 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:7720)
06-12 09:40:24.228  9918  9918 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
06-12 09:40:24.228  9918  9918 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:617)
06-12 09:40:24.228  9918  9918 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997)
06-12 09:40:24.228  9918  9918 W System.err: Caused by: com.google.android.exoplayer2.ExoTimeoutException: Player release timed out.
06-12 09:40:24.228  9918  9918 W System.err: 	at com.google.android.exoplayer2.ExoPlayerImpl.lambda$release$5(ExoPlayerImpl.java:994)
06-12 09:40:24.228  9918  9918 W System.err: 	... 16 more

how can this bug appear：I'm switch next song ,i code the exoplayer do stop(),then release()。if i click next song button slow,this bug will not show,but if i click next song button quickly for 20-40s,it will show Unexpected runtime error

i use the exoplayer version is 
    implementation 'com.google.android.exoplayer:exoplayer-core:2.18.2'
    implementation 'com.google.android.exoplayer:exoplayer-hls:2.18.2'
and is update the latest verison
    implementation 'com.google.android.exoplayer:exoplayer-core:2.18.7'
    implementation 'com.google.android.exoplayer:exoplayer-hls:2.18.7'
this bug is not solve。

so, how can i do? hope to receive your message,thank you!

**Comment by oceanjules** [comment]
Hi @huihui-Android ,

Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/androidx/media/issues/new?assignees=&labels=bug%2Cneeds+triage&template=bug.yml).
If you're unable to share [bug reports](https://developer.android.com/studio/debug/bug-report) or test content publicly, please send them to [dev.exoplayer@gmail.com](mailto:dev.exoplayer@gmail.com) using a subject in the format "Issue https://github.com/google/ExoPlayer/pull/1234" ("https://github.com/google/ExoPlayer/pull/1234" is replaced with your issue number). Please also update this issue to indicate you've done this.

Thanks!
