### ISSUE TITLE
Play audio, the progress is greater than the total duration.

### ISSUE THREAD

**Issue by 756230883** [google/ExoPlayer#11205]
### Bug

Play audio, the progress is greater than the total duration. The audio address is https://oss.nbs.cn/M00/22/E4/wKhkDmPZ1uSAJWFwAlYRLUW4gK0892.mp3

![1686550706861](https://github.com/google/ExoPlayer/assets/9440937/98dc8309-c387-40c1-a43e-ddda0b44ed80)

**Comment by rohitjoins** [comment]
Exoplayer determines the total duration of an MP3 file by reading the file's metadata(if available). I utilised `ffprobe` to obtain the duration of the MP3 file above, which is reported as 16:19.85. For reference, you can view the screenshot.

![Screenshot](https://github.com/google/ExoPlayer/assets/32570096/1d1cda98-c610-405e-bb93-1f4739f2208f)

I also attempted to use other tools such as `ffmpeg` and `vlc`, and they all provided the same duration as Exoplayer.

In more complex scenarios where the duration is not provided or the file has a variable bitrate encoding, Exoplayer makes an estimation of the total duration. Although it may not be entirely accurate, it is still fairly close to the actual duration. More on this topic can be read [here](https://developer.android.com/guide/topics/media/exoplayer/troubleshooting#why-is-seeking-inaccurate-in-some-mp3-files).

**Comment by 756230883** [comment]
Thank you for your answer. What I mean is that the total duration of this MP3 file is correct, but when the playback reaches the end, the value obtained through getCurrentPosition is greater than the value of getDuration. There will be a difference of about 5 seconds to the end. The front of the log is the current progress, followed by the total duration

**Comment by 756230883** [comment]
> Exoplayer determines the total duration of an MP3 file by reading the file's metadata(if available). I utilised `ffprobe` to obtain the duration of the MP3 file above, which is reported as 16:19.85. For reference, you can view the screenshot.
> 
> ![Screenshot](https://user-images.githubusercontent.com/32570096/245538393-1d1cda98-c610-405e-bb93-1f4739f2208f.png)
> 
> I also attempted to use other tools such as `ffmpeg` and `vlc`, and they all provided the same duration as Exoplayer.
> 
> In more complex scenarios where the duration is not provided or the file has a variable bitrate encoding, Exoplayer makes an estimation of the total duration. Although it may not be entirely accurate, it is still fairly close to the actual duration. More on this topic can be read [here](https://developer.android.com/guide/topics/media/exoplayer/troubleshooting#why-is-seeking-inaccurate-in-some-mp3-files).

Thank you for your answer. What I mean is that the total duration of this MP3 file is correct, but when the playback reaches the end, the value obtained through getCurrentPosition is greater than the value of getDuration. There will be a difference of about 5 seconds to the end. The front of the log is the current progress, followed by the total duration

**Comment by 756230883** [comment]
@rohitjoins 
Please take a look at this question again, thank you

**Comment by rohitjoins** [comment]
> What I mean is that the total duration of this MP3 file is correct, but when the playback reaches the end, the value obtained through getCurrentPosition is greater than the value of getDuration.

This can happen in cases where media incorrectly specifies its own duration. 

To determine the total duration of the media, we rely on either extracting metadata from the MP3 file or analyse starting portions of the file. However, to obtain precise duration, it would be necessary to load the entire file into memory, which can be inefficient. Nonetheless, during playback, we retrieve all accessible chunks or data, which means that the actual total duration of the file may slightly exceed the estimated duration.
