### ISSUE TITLE
How do I set the picture of the first frame for the player?

### ISSUE THREAD

**Issue by TheMelody** [google/ExoPlayer#11228]
### Bug

How does ExoPlayer set the cover picture of the first frame of the video for the player? 

When I get the data from the backend, I can get the picture of the first frame. 

How do I set the picture of the first frame for the player?

**Comment by marcbaechinger** [comment]
Please do not cross post with androidx/media. Thanks.

Closing as a duplicate of https://github.com/androidx/media/issues/478
