### ISSUE TITLE
Gradle. build failing

### ISSUE THREAD

**Issue by shivamp2404** [google/ExoPlayer#11223]
### Bug

getting error on build on gitlab pipeline
`Could not resolve com.google.android.exoplayer:exoplayer:2.13.1.
         > Could not get resource 'https://s3-ap-southeast-1.amazonaws.com/jp-build-packages/release/com/google/android/exoplayer/exoplayer/2.13.1/exoplayer-2.13.1.pom'.
            > Could not GET 'https://s3-ap-southeast-1.amazonaws.com/jp-build-packages/release/com/google/android/exoplayer/exoplayer/2.13.1/exoplayer-2.13.1.pom'. Received status code 403 from server: Forbidden`

**Comment by icbaker** [comment]
ExoPlayer maven artifacts are only hosted by us on maven.google.com. I don't know what maven repo you're trying to reach but those URLs are not maven.google.com. The earliest version available on maven.google.com is 2.13.3. Older versions are no longer officially available.

You should have `google()` in your list of maven repositories in your gradle config: https://developer.android.com/build/dependencies#google-maven
