### ISSUE TITLE
No sound from file uri .mkv

### ISSUE THREAD

**Issue by lionelyayan** [google/ExoPlayer#11227]
Hi everyone,

I am having problems playing .mkv format videos
video plays normally, but no audio.

here is the url of the video.

> https://onedrive.astradamy.com/api/raw/?path=/Movies/Doctor.Strange.in.the.Multiverse.of.Madness.2022/Doctor.Strange.in.the.Multiverse.of.Madness.2022.IMAX.1080p.DSNP.WEB-DL.DDP5.1.Atmos.H.264-CMRG.mkv

The following is a warning message from Android Studio.
> 18:32:10.636  W  Unsupported mime audio/x-adpcm-ms
> 18:32:10.637  W  Unsupported mime audio/x-adpcm-dvi-ima
> 18:32:10.638  W  Unsupported mime audio/alac
> 18:32:10.639  W  Unsupported mime audio/ape
> 18:32:10.655  W  Unrecognized profile/level 1/32 for video/mp4v-es
> 18:32:10.655  W  Unrecognized profile/level 32768/2 for video/mp4v-es
> 18:32:10.655  W  Unrecognized profile/level 32768/64 for video/mp4v-es
> 18:32:10.660  W  Unsupported mime video/x-ms-wmv
> 18:32:10.662  W  Unsupported mime video/xvid
> 18:32:10.669  W  Unrecognized profile/level 1/32 for video/mp4v-es
> 18:32:10.774  W  type=1400 audit(0.0:87580): avc: denied { read }

Thank you for your answer

**Comment by tianyif** [comment]
Hi @lionelyayan,

What device did you reproduce with? I could reproduce this on my Pixel 4a, and I saw the log:

```
2023-06-26 17:12:43.056 17901-17901 EventLogger             com.google.android.exoplayer2.demo   D    group [
2023-06-26 17:12:43.056 17901-17901 EventLogger             com.google.android.exoplayer2.demo   D      [ ] Track:0, id=2, mimeType=audio/eac3, channels=6, sample_rate=48000, language=en, selectionFlags=[default], supported=NO_UNSUPPORTED_TYPE
2023-06-26 17:12:43.056 17901-17901 EventLogger             com.google.android.exoplayer2.demo   D    ]
```

But it looks as expected to me since Pixel 4a doesn't have a decoder for eac3, and eac3 is the only audio track in this media. Could you please use `EventLogger` to filter the logcat to see if that's also your case?
