### ISSUE TITLE
HLS parser doesn't account for whitespaces

### ISSUE THREAD

**Issue by subratiitkgp** [google/ExoPlayer#11230]
### Bug

The HLS playlist parser regex don't support whitespaces. e.g. the regex used in the Exoplayer parser is ":(\d+)\b" , whereas web browsers support whitespace using regex ": *(\d+)" . See: https://github.com/video-dev/hls.js/blob/master/src/loader/m3u8-parser.ts#L68 . This can cause disparity between android and web browsers and can break HLS playback on android.

**Comment by oceanjules** [comment]
Looking at the HLS spec (https://datatracker.ietf.org/doc/html/draft-pantos-hls-rfc8216bis#section-4.1), whitespaces are not allowed:

In particular: 

"Lines in a Playlist file are terminated by either a single line feed character or a carriage return character followed by a line feed character.  

Each line is a URI, is blank, or starts with the character '#'.  

Blank lines are ignored.  **Whitespace MUST NOT be present**, except for elements in which it is explicitly specified."

If you can find an official spec reference that allowed whitespaces in tags, we can reopen the issue.
