### ISSUE TITLE
I tried to limit the maximum resolution of the video, but it didn't work

### ISSUE THREAD

**Issue by strivexiong** [google/ExoPlayer#11234]
Hello, I want to limit the maximum resolution of the video playback. When I created the player, I called the `setMaxVideoSize()` function,  set the maximum resolution to (256, 144), but it did not take effect, and the resolution of the video played in the end was still the original resolution of the video

**create the player**
```
        mPlayer = SimpleExoPlayer.Builder(this).build()
        var tmpSelector = mPlayer!!.trackSelector as DefaultTrackSelector
        tmpSelector.parameters = tmpSelector.buildUponParameters()
            .clearVideoSizeConstraints()
            .setMaxVideoSize(256, 144)
            .build()
```

**Comment by tianyif** [comment]
Hi @strivexiong,

What are the available video tracks of your media? If the only available video tracks are all beyond the video size constraints, it could still be selected if [`setExceedVideoConstraintsIfNecessary(boolean)`](https://developer.android.com/reference/androidx/media3/exoplayer/trackselection/DefaultTrackSelector.Parameters.Builder#setExceedVideoConstraintsIfNecessary(boolean)) is set to `true`. In fact, this is `true` by default. 

For example a [sample media](https://github.com/google/ExoPlayer/blob/release-v2/demos/main/src/main/assets/media.exolist.json#L195) in the demo app - it just has one video track with size `1920x1080`. I set the max video size as (256, 144) to the `DefaultTrackSelector`, then by default, the 1920x1080 was still played. However, if I set `setExceedVideoConstraintsIfNecessary(boolean)` to `false`, then that track was not selected, and the playback started without video.

Could you please see if that's the case for you?
