### ISSUE TITLE
ExoPlayer play no callback onRenderedFirstFrame function ，Causing video playback failure

### ISSUE THREAD

**Issue by lishuxiong** [google/ExoPlayer#11232]
### Bug

The local MP4 file is played using ExoPlayer, and occasionally the video cannot be played. The reason for this is that onRenderedFirstFrame() has not been destroyed, with a probability of 10 bugs occurring twice

use com.google.android.exoplayer:exoplayer：2.18.0 

log

14:01:52.429  1730-2666  android.ha....0-service media.codec                E  Service not available yet
14:01:52.432  1730-2666  OMX-VDEC-1080P          media.codec                E  Unsupported output color format for c2d (2141391876)
14:01:52.432  1730-2666  OMX-VDEC-1080P          media.codec                E  Setting color format failed
14:01:52.439  1730-2666  OMX_VPP                 media.codec                E  unable to find area=vpp/config=frc.bypass.all, returning default=0
14:01:52.452  1730-2666  OMX-VDEC-1080P          media.codec                E  Extension: OMX.google.android.index.storeANWBufferInMetadata not implemented
14:01:52.452  1730-2666  OMX-VDEC-1080P          media.codec                E  Extension: OMX.google.android.index.configureVideoTunnelMode not implemented
14:01:52.452  1730-2666  OMX-VDEC-1080P          media.codec                E  Extension: OMX.google.android.index.useAndroidNativeBuffer is supported
14:01:52.452  1730-2666  OMX-VDEC-1080P          media.codec                E  Setparameter: unknown param 2130706502
14:01:52.452  1730-2666  OMX-VDEC-1080P          media.codec                E  set_parameter: Error: 0x8000101a, setting param 0x7f000046
14:01:52.452  1730-2666  OMXNodeInstance         media.codec                E  setParameter(0xf2720c04:qcom.decoder.avc, ??(0x7f000046)) ERROR: UnsupportedIndex(0x8000101a)
14:01:52.452  1730-2666  OMX-VDEC-1080P          media.codec                E  set_parameter: Error: 0x80001019, setting param 0x7f00005d
14:01:52.452  1730-2666  OMXNodeInstance         media.codec                E  setParameter(0xf2720c04:qcom.decoder.avc, OMX.google.android.index.allocateNativeHandle(0x7f00005d): Output:1 en=0) ERROR: UnsupportedSetting(0x80001019)
14:01:52.452  1730-2666  OMX-VDEC-1080P          media.codec                E  Extension: OMX.google.android.index.storeANWBufferInMetadata not implemented
14:01:52.452  1730-2666  OMX-VDEC-1080P          media.codec                E  get_parameter: unknown param 6f600011
14:01:52.452  1730-2666  OMXNodeInstance         media.codec                E  getParameter(0xf2720c04:qcom.decoder.avc, ??(0x6f600011)) ERROR: UnsupportedIndex(0x8000101a)
14:01:52.453  1730-2666  OMX-VDEC-1080P          media.codec                E  Setparameter: unknown param 2130706434
14:01:52.453  1730-2666  OMX-VDEC-1080P          media.codec                E  set_parameter: Error: 0x8000101a, setting param 0x7f000002
14:01:52.453  1730-2666  OMXNodeInstance         media.codec                E  setParameter(0xf2720c04:qcom.decoder.avc, ??(0x7f000002)) ERROR: UnsupportedIndex(0x8000101a)
14:01:52.455  1730-2666  OMXNodeInstance         media.codec                E  getConfig(0xf2720c04:qcom.decoder.avc, ??(0x7f000062)) ERROR: UnsupportedSetting(0x80001019)
14:01:52.506  1730-5438  OMX-VDEC-1080P          media.codec                E  Extension: OMX.google.android.index.AndroidNativeBufferConsumerUsage not implemented
14:01:52.518  8703-8703  BaseInputMethodService  com...method.sogou.xiaomi  E  onFinishInput
14:01:52.523  8703-8703  BaseInputMethodService  com...method.sogou.xiaomi  E  onStartInput

F E E E E 荻取的播放路径====onPLayWhenReadyChanged==1 
荻取的播放路径====onPlaybackStateChanged==2 
荻取的播放路径====onLoadStarted==/storage/emulated/0/Android/data/com.hanami.rocks/files/media_video. 
Service not available yet Unsupported output color format for c2d (2141391876) Setting color format failed unable to find area=vpp/config=fre.bypass.all, returning default=0 Extension: OMX.google. android. index. storeANWBufferInMetadata not implemented E Extension: OMX. google.android.index. configureVideoTunnelMode not implemented E Extension: OMX. google.android.index. useAndroidNativeBuffer is supported E Setparameter: unknown param 2130706502 E set_parameter: Errg: 0x8000101a, setting param 0X7f000046 E setParameter(Oxf2cb9804:qcom.decoder.avc,??(0×7f000046))ERROR:UnsupportedIndex(0x8000101a) E set_parameter: Error: 0x80001019, setting param 0x7f00005d E setParameter(0xf2cb9804:qcom.decoder.avc,OMX.googLe.android.index.allocatellativetandle(0x7f00005d) E Extension: OMX.google.android. index. storeANWBufferInMetadata not implemented E get_parameter: unknown param 6f600011 E getParameter (Oxf2cb9804: qcom. decoder .avc, ?? (0×6f600011)) ERROR: UnsupportedIndex(0x8000101a) E Setparameter: unknown param 2130706434 E set_parameter: Error: 0x8000101a, setting param 0×7f000002 E setParameter(0xf2cb9804:qcom.decoder.avc,??(0×7f000002))ERROR:UnsupportedIndex(0x8000101a) E getConfig(Oxf2cb9804:qcom.decoder.avc,??(0X7f000062))ERROR:UnsupportedSetting(0×80001019) E Extension: OMX.google.android. index. AndroidNativeBufferConsumerUsage not implemented Attempt to set frame rate on an unrecognized IGraphicBufferProducer E getConfig(0xf2cb9804:qcom.decoder.avc,??(0×7f000062))ERROR:.UnsupportedSetting(0x80001019) E Extension: OMX. google. android. index. AndroidNativeBufferConsumerUsage not implemented E [SurfaceTexture-1-21164-53] (1d: 52ac00000062, api:0, p:-1,c:21164) dequeueBuffer: BufferQueue has no col E dequeueBuffer failed: NO_INIT(-19). E Extension:OMX.google.android.index.AndroidNativeBufferConsumerUsagenotimplemented Insert message into database succeed, amount = 1 E onFinishInput

**Comment by tianyif** [comment]
Hi @lishuxiong,

Hi! Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/androidx/media/issues/new?assignees=&labels=bug%2Cneeds+triage&template=bug.yml).
If you're unable to share [bug reports](https://developer.android.com/studio/debug/bug-report) or test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #1234" ("#1234" is replaced with your issue number). Please also update this issue to indicate you've done this. 

Thanks!
