### ISSUE TITLE
Exoplaye Listener for onPlaybackStateChanged is continuesly looping 

### ISSUE THREAD

**Issue by Varun-M-Patange** [google/ExoPlayer#11231]
### Bug

We are adding Player Listener for listening player state, but for sometime, it is going in Loop in between Buffering State and State Ready, it is causing an issue, video is not playing, give us the solution.

**Comment by tianyif** [comment]
Hi @Varun-M-Patange,

From the provided information, it's hard to tell if it is an ExoPlayer library issue. I'm closing this one for now, please feel free to create a new one using the [template](https://github.com/androidx/media/issues/new?template=question.md) with more details.
