### ISSUE TITLE
Downloaded content auto removed after app update

### ISSUE THREAD

**Issue by pavelsust** [google/ExoPlayer#11247]
In my application i had implemented content download using exoplayer. Everything is working fine but when I update my application from google play store all downloaded content auto removed. 
How I can prevent downloaded content removed after app update?

**Comment by icbaker** [comment]
The `com.google.android.exoplayer2` project is now deprecated. We are not accepting any new issues in this project. Please file your issue in the `androidx.media3` GitHub project instead: https://github.com/androidx/media/issues
