### ISSUE TITLE
How to import .jar for exoplayer library into Unity

### ISSUE THREAD

**Issue by Gurwar** [google/ExoPlayer#11244]
I am working on a exoplayer library for Unity and am having issues with linking Exoplayer functions into Unity. I think the problem I am having is not having the exoplayer library in my Unity project in a way that can be read by the compiler. The way I tried to import Exoplayer is by exporting all the seperate modules of Exoplayer and putting them in the plugins/android folder in the Unity project. I read online that a .jar of the whole Exoplayer library is also required.

How would I go about building this jar file and linking it in Unity?

[Here's a link to the issues I have been having in more detail.](https://github.com/google/ExoPlayer/issues/11217)

**Comment by tonihei** [comment]
This looks like an extension or summary of the issue you already filed. I'll mark it as a duplicate.
