### ISSUE TITLE
Target buffer size reached with less than 500ms of buffered media data.[android Nougat] SUNMI DEVICE

### ISSUE THREAD

**Issue by msoliman22** [google/ExoPlayer#11242]
### Bug

Issue : video is stucking with black screen after 4 hours. playing and always give me this message "Target buffer size reached with less than 500ms of buffered media data."  then the app will go out with out of memory issue when the RAM will reach to the limit 

Code Snippet :  
  val  MIN_BUFFER_DURATION = 3000  // 3 seconds
        val MAX_BUFFER_DURATION = 5000  // 8 seconds
        val MIN_PLAYBACK_RESUME_BUFFER = 2000  // 1.5 seconds
        val MIN_PLAYBACK_START_BUFFER = 1000 // 0.5 seconds
        val loadControl =  DefaultLoadControl.Builder().setPrioritizeTimeOverSizeThresholds(false) .setAllocator( DefaultAllocator(true, C.DEFAULT_BUFFER_SEGMENT_SIZE)) .setBufferDurationsMs(MIN_BUFFER_DURATION, MAX_BUFFER_DURATION, MIN_PLAYBACK_START_BUFFER, MIN_PLAYBACK_RESUME_BUFFER) .setTargetBufferBytes(-1).createDefaultLoadControl()

        video_view?.player = ExoPlayer.Builder(InfiKIOSKApp.getInstance().applicationContext).setLoadControl(loadControl).build()
        video_view?.setShutterBackgroundColor(Color.TRANSPARENT);
        video_view?.setKeepContentOnPlayerReset(true)
        video_view?.player?.volume = 0f

 list_all.forEach {
         
                val mediaItem = MediaItem.fromUri(it.path)
                video_view?.player?.addMediaItem(mediaItem)
         
        }

Media Example : 

https://github.com/google/ExoPlayer/assets/92383246/863c00eb-421f-4d56-b74c-8ea02468df09

Devices that reproduce the issue

Sumi K2 and Sunmi K2-mini  Android 7.1.1
ExoPlayer Version

The latest version 2.18.7

**Comment by microkatz** [comment]
Hi @msoliman22.

Thank you for reporting your issue. First of all,  would you be able to share a [bug report](https://developer.android.com/studio/debug/bug-report) of your issue? If you can't send it publicly then please send it to android-media-github@google.com with the subject `Issue #11242`. Please also update this issue to indicate you've done this.

Secondly, is there a specific reason you have custom load control buffer settings? The default DEFAULT_MIN_BUFFER_MS is 50_000 which is much greater than your 3000. What happens if you set a larger MIN_BUFFER_DURATION and MAX_BUFFER_DURATION?

**Comment by msoliman22** [comment]
Hi @microkatz 

Thx for your response so let me share the bug report with you also I will declare my project target also the reason behind having  have custom load control buffer settings

so first of all my target is to run video slider to show some short videos that coming from the server so first I download these videos then I will run exoplayer and assign these media items that already saved in my internal folder 

most of the videos is in range 5 seconds To 30 seconds so I run my app to show these videos with Player.REPEAT_MODE_ALL and I didn't put any custom load control buffer settings at this time  . so I checked my RAM through this time and everything was ok so it's increasing and decreasing in expected range But after like 4 hours I found that one of the videos is freezing then the RAM started to increase and there is a log shown like that "Target buffer size reached with less than 500ms". then this is the crash that happened which is expected because the video stuck in buffering and the RAM increasing

Fatal Exception: java.lang.OutOfMemoryError: Could not allocate JNI Env
       at java.lang.Thread.nativeCreate(Thread.java)
       at java.lang.Thread.start(Thread.java:730)
       at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:941)
       at java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:1009)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1151)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:761)


so I read some articles about that the reason behind this issue that my videos are really short and there is a gab between Min and Max buffer so this will cause this issue besides that if video is like 5 seconds and buffering requiring 50 seconds so my video will be allocated in the memory 10 times which is big load on the RAM then they advise that I can have custom load control buffer settings with some suggested values so I tried again using this snippet of configuration 

```
val MIN_BUFFER_DURATION = 3000 // 3 seconds
val MAX_BUFFER_DURATION = 5000 // 8 seconds
val MIN_PLAYBACK_RESUME_BUFFER = 2000 // 1.5 seconds
val MIN_PLAYBACK_START_BUFFER = 1000 // 0.5 seconds
val loadControl = DefaultLoadControl.Builder().setPrioritizeTimeOverSizeThresholds(false) .setAllocator( DefaultAllocator(true, C.DEFAULT_BUFFER_SEGMENT_SIZE)) .setBufferDurationsMs(MIN_BUFFER_DURATION, MAX_BUFFER_DURATION, MIN_PLAYBACK_START_BUFFER, MIN_PLAYBACK_RESUME_BUFFER) .setTargetBufferBytes(-1).createDefaultLoadControl()

        video_view?.player?.trackSelectionParameters = video_view?.player?.trackSelectionParameters
            ?.buildUpon()
            ?.setTrackTypeDisabled(C.TRACK_TYPE_AUDIO,true)
            ?.build()!!

        video_view?.player = ExoPlayer.Builder(InfiKIOSKApp.getInstance().applicationContext).setLoadControl(loadControl).build()
        video_view?.setShutterBackgroundColor(Color.TRANSPARENT)
        video_view?.setKeepContentOnPlayerReset(true)
```
so I run my app after I put this configuration so it was running fine for like 3 hours then also one of the videos stucking (any video not specific one ) and I saw same message in log "Target buffer size reached with less than 500ms". also the RAM started to increase and there are one expected crash and another new crash at this time 

New Crash is "Min Buffer can not be less than bufferForPlaybackAfterRebufferMs". I don't have the full log currently but this is the title 

I hope that I was able to declare my issue so it's really a big issue for us in my company since it's related to the RAM and the only other option for me will be VideoView and media player which also have some issues with RAM increasing based on my experience 

also if you can help me with code example to edit the values for Buffers so it can be suitable to my videos with the properities that I described it will be great. thx in advance

**Comment by microkatz** [comment]
@msoliman22 

The buffering the 5 second video for 50 seconds is a result of the Repeat mode being on. The video is set to repeat so ExoPlayer is setting up to play 50 seconds of that video. If you used the DefaultLoadControl settings without Repeat mode, then it wouldn't copy the video that many times. From your scenario I think you can still use the default load control values.

You said this is easily reproducible with a single video, any video. Are you able to reproduce this on the demo app in our library? You don't need to pre-download the videos. Add the uri to media.exolist.json file. Add one line to PlayerActivity.java in `initalizePlayer()`
```java
player.setRepeatMode(Player.REPEAT_MODE_ONE);
```
Let us know if you hit the same issue.

**Comment by msoliman22** [comment]
@microkatz  Got it , I am getting the issue when I loop 2 videos or more with Player.REPEAT_MODE_ALL for like 3 hours . so i need to try with it in the demo app right ?

**Comment by msoliman22** [comment]
@microkatz I am running it now on the demo and I will let you know the results thx

**Comment by microkatz** [comment]
@msoliman22. Thank you! Post again here when you have the results.

**Comment by msoliman22** [comment]
Thx Micheal  , after I used the same steps that we are doing in the demo
including using ads loader everything is ok

**Comment by microkatz** [comment]
@msoliman22 

So you figured out your issue? Everything is resolved?

**Comment by msoliman22** [comment]
Yes, everything is fine.

**Comment by microkatz** [comment]
Cool. I'll close. Thank you for posting your issue on Github!
