### ISSUE TITLE
Having 2 players Issues

### ISSUE THREAD

**Issue by techker** [google/ExoPlayer#11249]
Hey, we have an app for TV that has an epg guide that in that guide we have a preview player and in the background have the current channel still streaming.

The issue is when we hit a channel that has AC3 Audio, when the preview start we get an error status -20 error when initializing Audio track. 
createTrack returned -38...
But in our case we do not want audio in the preview..

**Comment by icbaker** [comment]
The `com.google.android.exoplayer2` project is now deprecated. We are not accepting any new issues in this project. Please file your issue in the `androidx.media3` GitHub project instead: https://github.com/androidx/media/issues
