### ISSUE TITLE
Query on Tunneled playback

### ISSUE THREAD

**Issue by onlytanmoy** [google/ExoPlayer#11248]
Hi, I am using ExoPlayer in my Shield TV Pro 2019 device. Can I enable Tunneled playback? I am not sure if Shield supports it or not so thought of clarifying. Thanks!

**Comment by icbaker** [comment]
The `com.google.android.exoplayer2` project is now deprecated. We are not accepting any new issues in this project. Please file your issue in the `androidx.media3` GitHub project instead: https://github.com/androidx/media/issues

**Comment by onlytanmoy** [comment]
Done! https://github.com/androidx/media/issues/530
Thanks @icbaker closing this issue here.
