### ISSUE TITLE
how can i add subtitle from sdcard when playing?

### ISSUE THREAD

**Issue by archko** [google/ExoPlayer#11250]
i playing a video,with no subtitle, then i select a subtitle from sdcard.

```
MediaItem.SubtitleConfiguration
                    .Builder(Uri.fromFile(File(subtitlePath!!)))
                    .setLabel("ext subtitle")
                    .setId(id)
                    .setMimeType(mimeType)
                    .setSelectionFlags(C.SELECTION_FLAG_DEFAULT)
                    .build()

and exoplayer.setmediaitem()
exoplayer.prepare()
```
There will be a black screen if i do this, and I am an online video, and there will be a black screen for a long time

Can subtitles be loaded dynamically when playing videos? Each time prepare()

Can I update mediaitem to load subtitles?
thanks for help

**Comment by icbaker** [comment]
Adding subtitles during playback is not currently possible - support is tracked by https://github.com/google/ExoPlayer/issues/1649.
