### ISSUE TITLE
Exoplayer DrmSessionException Failed to restore keys ERROR_DRM_UNKNOWN

### ISSUE THREAD

**Issue by Envitec** [google/ExoPlayer#11258]
### Bug

I am getting this error when playing offline content. 

**ExoPlayer version 2.18.10**

Please see the error file attached.

Thanks
Rajesh

[exoplayer_drm_error.txt](https://github.com/google/ExoPlayer/files/12261814/exoplayer_drm_error.txt)

**Comment by rohitjoins** [comment]
The com.google.android.exoplayer2 project is now deprecated. We are not accepting any new issues in this project. Please file your issue in the androidx.media3 GitHub project instead: https://github.com/androidx/media/issues
