### ISSUE TITLE
HLS Live stream freezing with Exoplayer only

### ISSUE THREAD

**Issue by ghost** [google/ExoPlayer#11254]
### Bug

I am having issues playing this specific live stream:
https://5db313b643fd8.streamlock.net/Paroledivita/Paroledivita/playlist.m3u8
the playback freezes randomly and does not recover anymore. 
The issue is easily replicable, it freezes within one minute of playback, after few lags.
The stream plays fine on akamai tester and other online players. It might be a bit laggy there too, but these players recover playback and continue playing the stream, while exoplater apparently can't.
Tested on Exoplayer 2.18.7 and 2.19, on different devices and emulators: same issue.
Thank you.

**Comment by rohitjoins** [comment]
The `com.google.android.exoplayer2` project is now deprecated. We are not accepting any new issues in this project. Please file your issue in the `androidx.media3` GitHub project instead: https://github.com/androidx/media/issues
