### ISSUE TITLE
What use instead of setControllerVisibilityListener()?

### ISSUE THREAD

**Issue by thathorizon** [google/ExoPlayer#11252]
Hi!
I use setControllerVisibilityListener method in my app, but it's marked as deprecated. 
What I must use instead?

**Comment by icbaker** [comment]
As the deprecation message says, you should use https://developer.android.com/reference/androidx/media3/ui/PlayerView#setControllerVisibilityListener(androidx.media3.ui.PlayerView.ControllerVisibilityListener)

Using `PlayerControlView` without `PlayerView` is not currently supported (tracked by https://github.com/androidx/media/issues/514)
