### ISSUE TITLE
AudioSession generation opt out

### ISSUE THREAD

**Issue by dryganets** [google/ExoPlayer#11259]
Looks like the method call generateAudioSessionId causes various issues for the users of the exoplayer.
Seems like the platform call is not as reliable for some users as it should be ...

I wonder if the audio session is something that is strictly required in all use-cases.
Seems like it needed only for tunneling mode.
Do you think it is possible to limit the generation of the audio sessions to that mode only?

**Comment by microkatz** [comment]
Hi @dryganets 

I apologize but the com.google.android.exoplayer2 project is now deprecated. We are not accepting any new issues in this project. Please file your issue in the androidx.media3 GitHub project instead: https://github.com/androidx/media/issues
