### ISSUE TITLE
problem playing mpd and clearkey links 

### ISSUE THREAD

**Issue by untukapa123** [google/ExoPlayer#11256]
Does anyone know that the mpd + clearkey link can be played, the problem is that on OTT Navigator it works but you can't use exoplayer #KODIPROP:inputstreamaddon=inputstream.adaptive #KODIPROP:inputstream.adaptive.license_type=clearkey #KODIPROP:inputstream.adaptive.license_key=0005de226b16ae5d75df48aa6099cca6:75e80519551edc03e890e13f01abd26d #EXTINF:-1 tvg-id="SkysportsF1" tvg-name="SkysportsF1" group-title="UK" tvg-logo="https://i.ibb.co/M7mKzL8/skysportf1.png", SKYSPORTS F1 FHD #EXTVLCOPT:http-referrer=https://www.skysports.com http://linear004-gb-dash1-prd-ak.cdn.skycdp.com/100e/Content/DASH_003_sm/Live/channel(skysportsf1)/manifest_hd.mpd

**Comment by rohitjoins** [comment]
The `com.google.android.exoplayer2` project is now deprecated. We are not accepting any new issues in this project. Please file your issue in the `androidx.media3` GitHub project instead: https://github.com/androidx/media/issues
