### ISSUE TITLE
Mtos value coming 0,0,0,0 everytime

### ISSUE THREAD

**Issue by chinmaym14** [google/ExoPlayer#11255]
Will returning null in case of getAdViewGroup for AdViewProvider while using IMA extension result in mtos value to be 0,0,0,0?

```
override fun getAdViewGroup(): ViewGroup? {
        return null
    }
```

As seen in documentation of AdViewProvider class, if we pass null in **getAdViewGroup** method it is treated as audio only ads. Will it affect mtos value in that case?

**Comment by rohitjoins** [comment]
The `com.google.android.exoplayer2` project is now deprecated. We are not accepting any new issues in this project. Please file your issue in the `androidx.media3` GitHub project instead: https://github.com/androidx/media/issues
