### ISSUE TITLE
Playing really small files with the latest build (2.19.1) still fails to detect the file completion

### ISSUE THREAD

**Issue by theboubougne** [google/ExoPlayer#11267]
### Bug

This bug was introduced in v2.19.0, but even though it looks like it should be fixed according to the changelog, I'm still experiencing the issue with some very short files ( < 20s).
Sometimes the playback plays a small sound in an infinite loop, other time it stays in playback status, with no more progress and no more sound, until I start playing another file

For these files the onPlaybackStateChanged() callback is NOT called with Player.STATE_ENDED

**Comment by gemiren** [comment]
Has the same issue even with various durations, not just limited to the short durations. This is a serious bug.

**Comment by icbaker** [comment]
I'm unable to reproduce this with media3 1.1.1 (equivalent to exoplayer 2.19.1) and the media provided in https://github.com/androidx/media/issues/538, so this doesn't look like exactly the same issue.

The `com.google.android.exoplayer2` project is now deprecated. We are not accepting any new issues in this project. Please file your issue in the `androidx.media3` GitHub project instead, with media we can use to reproduce the issue: https://github.com/androidx/media/issues

**Comment by theboubougne** [comment]
Not sure to understand here. Your last release before deprecating the
project is breaking playback of short files and you will not fix it??
