### ISSUE TITLE
MI 11 T pro no audio, so cant record video ,no bluetooth ,fingerprint also doesnt work

### ISSUE THREAD

**Issue by redmifan** [google/ExoPlayer#11262]
I tried resetting the device yet the issue prevails, there is no audio so cant watch any videos in whatsapp, instagram, youtube. the camera is blank and doesnt allow video call .bluetooth wont turn on so cant connect any headphones. please help !! has anyone had this issues before ?

**Comment by microkatz** [comment]
Hello @redmifan,

I'm sorry you are having these issues but based on your description, it does not seem like an ExoPlayer specific problem. Your audio/video/camera issues span multiple apps and seem to be specific to your phone as well as being non-media based. I would suggest reaching out Xiaomi technical support.
