### ISSUE TITLE
How to get track groups?

### ISSUE THREAD

**Issue by lionelyayan** [google/ExoPlayer#11260]
Hello, i encountered a problem in the getCurrentTrackGroups() function.

When I select the build variant debug the trackGroups information appears.
![image](https://github.com/google/ExoPlayer/assets/55187991/0c5330e6-4c99-4b20-8228-d7e9fbfc5420)

But when I select the build variant release the trackGroups information is No value for trackGroups.
![image](https://github.com/google/ExoPlayer/assets/55187991/50b7d37a-d4ee-4656-b18b-048888804d8d)

I develop in android studio and using java.
Thanks for your answer

**Comment by microkatz** [comment]
The com.google.android.exoplayer2 project is now deprecated. We are not accepting any new issues in this project. Please file your issue in the androidx.media3 GitHub project instead: https://github.com/androidx/media/issues
