### ISSUE TITLE
IllegalArgumentException error on PlaybackStatsListener 

### ISSUE THREAD

**Issue by egeysn** [google/ExoPlayer#11263]
### Bug

Our application has an average of 200k daily users. When I test it, I couldn't detect any issues. However, when I examined Firebase crashlytics events, I noticed that the PlaybackStatsListener class is causing crashes for some users. I suppose the issue is related to the assertion at 
****line 658: Assertions.checkArgument(eventTime.realtimeMs >= currentPlaybackStateStartTimeMs);.**

ExoPlayer version : 2.16.0

Error: 
Fatal Exception: java.lang.IllegalArgumentException
com.google.android.exoplayer2.util.Assertions.checkArgument (Assertions.java:39)
com.google.android.exoplayer2.analytics.PlaybackStatsListener$PlaybackStatsTracker.updatePlaybackState (PlaybackStatsListener.java:658)
com.google.android.exoplayer2.analytics.PlaybackStatsListener$PlaybackStatsTracker.onEvents (PlaybackStatsListener.java:577)
com.google.android.exoplayer2.analytics.PlaybackStatsListener.onEvents (PlaybackStatsListener.java:260)
com.google.android.exoplayer2.analytics.AnalyticsCollector.lambda$setPlayer$1 (AnalyticsCollector.java:142)
com.google.android.exoplayer2.util.ListenerSet$ListenerHolder.iterationFinished (ListenerSet.java:272)
com.google.android.exoplayer2.util.ListenerSet.handleMessage (ListenerSet.java:224)
android.os.Handler.dispatchMessage (Handler.java:103)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:994)

<img width="1435" alt="Screen Shot 2023-08-14 at 22 26 44" src="https://github.com/google/ExoPlayer/assets/44908368/66b2e221-f301-453f-bfec-a9b3f09e8b67">

**Comment by microkatz** [comment]
Hi @egeysn.

The com.google.android.exoplayer2 project is now deprecated. We are not accepting any new issues in this project. If you could please file your issue in the androidx.media3 GitHub project instead: https://github.com/androidx/media/issues
