### ISSUE TITLE
the audio track of ac3  sounds intermittent

### ISSUE THREAD

**Issue by liangqiujuan** [google/ExoPlayer#11264]
### Bug

The test video has a audio track with the information:( we see it by MediaInfo tool)
448kb/s,48.0khz, 6 channels, AC-3(DVD Video)(Dlolby Digtal)

The sound is abnormal when play with exoplayer. But it is normal when play with vlc or other player on the same OTA box. It is normal too when paly on PC. 

We use exoplayer 2.12 or 2.18 to play, and the result is same.

So we think there may be a problem with exoplayer's extractor who deal the audio track.

 Please help analyze. 

If  you want to reproduce the problem, the device need to support AC3 decoding, or connect a OTA box to a TV that supports AC3, so that the sound can be passthrough to the TV for playback.

the log and test file will provide later.

**Comment by liangqiujuan** [comment]
log with exoplayer 2.18: [ac3.log](https://github.com/google/ExoPlayer/files/12357499/ac3.log)
the test file:
https://cowtransfer.com/s/812b47069f0049
if need input a code, please enter  yi2zod

**Comment by liangqiujuan** [comment]
The following video records the abnormal issues：

https://github.com/google/ExoPlayer/assets/80817127/a476f281-52d8-4437-9ee9-4defa98bcfe5

**Comment by microkatz** [comment]
Hello @liangqiujuan,

Thank you so much for reporting your issue.  The `com.google.android.exoplayer2` project is now deprecated and so we are not accepting any new issues in this project. Please file your issue in the `androidx.media3` GitHub project instead: https://github.com/androidx/media/issues
