### ISSUE TITLE
Displaying TTML subtitles in HLS converted from live DASH

### ISSUE THREAD

**Issue by RicFlinn** [google/ExoPlayer#11266]
I'm trying to figure out a way to make time-based subtitles captured from a live DASH stream display correctly after converting the stream to HLS.

My app converts a live DASH stream into HLS. A/V works as expected, but the DASH stream includes TTML-formatted subtitle segments that do not display. The app stores A/V segments from the live DASH stream, beginning at a random time within the stream. Audio, video, and subtitle segments are stored. I then create a set of HLS playlists from these segments to play back the video.

The TTML subtitle segments contain "begin" and "end" times for the display text relative to the start of the live DASH stream. A typical subtitle segment includes something like:

    <p begin="489:02:17.897" end="489:24:18.698" region="Region_187">
        <span style="Style_184_0">WHAT SHOULD I DO?</span>
    </p>
    
When playing the recording as a DASH stream, the subtitles display correctly, even when played back as a static DASH stream; i.e. not a dynamic stream using clock timing relative to when the stream was originally played. This means the subtitle decoder must be getting the timing data from the A/V stream and displaying the subtitles at the correct time based on this. (Side note: I see other evidence that this is true, like ExoPlayer's timeline bar has 489:20:17 as a start time.)

When playing the segments as an HLS stream, however, this internal timing reference is apparently NOT used, and the subtitles do not display, because the playback start time is 000:00:00 and the first subtitle displays at some much later time (489 hours, in the above example).

If I manually adjust the times in the segments, I get mixed results on whether or not they display. For example, if the above subtitle is the first one at the beginning of the stream, I can adjust it to look like this:

    <p begin="000:00:00.000" end="000:00:00.801" region="Region_187">
        <span style="Style_184_0">WHAT SHOULD I DO?</span>
    </p>

In some cases the caption will display correctly, and others it may just blink on and back off again. My hunch is that I'm not adjusting the times correctly according to when they should be displayed based on the A/V timing. Assuming that the first subtitle should start at time 0 rarely works as desired.

I'm wondering if there is a way to extract the display time value from the MP4 data and use that as a reference start time, and then adjust the subtitle times by this value. I'm not sure what this value would be called or where to look for it; I don't know much about how the the A/V renderers operate. I considered using the DASH timing information (availability start time, current time, etc), but I don't think this will be accurate enough.

**Comment by icbaker** [comment]
The `com.google.android.exoplayer2` project is now deprecated. We are not accepting any new issues in this project. Please file your issue in the `androidx.media3` GitHub project instead: https://github.com/androidx/media/issues

**Comment by icbaker** [comment]
When filing the new issue, please also include a link to an HLS stream we can play to reproduce the problem (or email it to android-media-github@google.com after filing and mention you've done that).
