### ISSUE TITLE
error on android 13 when disable_analog_output option is true 

### ISSUE THREAD

**Issue by Inkayuyu04** [google/ExoPlayer#11268]
**Please do not file new issues in this repository.**

All new questions should be filed in the
[Media3 issue tracker](https://github.com/androidx/media/issues/new?template=question.md).

We will continue to update and reply to existing issues in this repository and
will keep existing feature requests active.

I've been testing DRM content on my S22 Ultra(Android 13) and I'm having a
problem.
When I set the value of disable_analog_output to true in the Widevine DRM
options, I get the ERROR_CODE_DRM_DISALLOWED_OPERATION player error.
This error is not occurring on S21(Android 13) at all.

**Comment by marcbaechinger** [comment]
Please do not file new issues in this repository.

All new questions should be filed in the
[Media3 issue tracker](https://github.com/androidx/media/issues/new?template=question.md).

Thanks!
