### ISSUE TITLE
Support Ktor

### ISSUE THREAD

**Issue by sonatard** [google/ExoPlayer#11279]
The standard for HTTP clients is increasingly shifting towards Ktor.

**Comment by icbaker** [comment]
The `com.google.android.exoplayer2` project is now deprecated. We are not accepting any new issues in this project. Please file your issue in the `androidx.media3` GitHub project instead: https://github.com/androidx/media/issues

When re-filing please provide more information about the benefits you see of having a `DataSource` backed by ktor. It looks to me like ktor doesn't itself implement the HTTP protocol, but it wraps other HTTP stacks (OkHttp by default on Android) - so it would be good to understand if you are planning to use ktor-backed-by-okhttp, and if so what the concrete advantages would be over the existing OkHttp extension we provide (for media playback use-cases).
