### ISSUE TITLE
Downloading error

### ISSUE THREAD

**Issue by jasi381** [google/ExoPlayer#11272]
@Composable
fun MainUi2() {
    val contentUri =
        Uri.parse("https://demo.unified-streaming.com/k8s/features/stable/video/tears-of-steel/tears-of-steel.ism/.m3u8")

    val context = LocalContext.current
    val databaseProvider = StandaloneDatabaseProvider(context)
    val downloadDirectory = context.externalCacheDir
    val downloadCache = SimpleCache(downloadDirectory!!, NoOpCacheEvictor(), databaseProvider)
    val dataSourceFactory = DefaultHttpDataSource.Factory()

    val downloadExecutor = Executors.newSingleThreadExecutor()
    val downloadManager = DownloadManager(
        context, databaseProvider, downloadCache, dataSourceFactory, downloadExecutor
    )

    val mediaItem = MediaItem.Builder()
        .setUri(contentUri)
        .setMediaId("dummyId")
        .setMediaMetadata(
            MediaMetadata.Builder()
                .setTitle("Demo Video")
                .build()
        )
        .setMimeType("application/vnd.apple.mpegurl")
        .build()

    val mediaSource =
        HlsMediaSource.Factory(dataSourceFactory).createMediaSource(mediaItem)

    val callback = object : DownloadHelper.Callback {
        override fun onPrepared(helper: DownloadHelper) {
            val downloadRequest =
                helper.getDownloadRequest(Util.getUtf8Bytes(checkNotNull(mediaItem.mediaMetadata.title.toString())))
            downloadManager.addDownload(downloadRequest)
            Log.d("Dumy", "onPrepared: ${mediaItem.mediaMetadata.title.toString()}")
        }

        override fun onPrepareError(helper: DownloadHelper, e: IOException) {
            Toast.makeText(context, e.message, Toast.LENGTH_SHORT).show()
        }
    }

    val downloadHelper =
        DownloadHelper.forMediaItem(
            context,
            mediaItem,
            DefaultRenderersFactory(context),
            dataSourceFactory

        )

    Column(modifier = Modifier.fillMaxSize()) {
        ExoplayerUi(
            uri = contentUri,
            modifier = Modifier.weight(1f)
        )
        Row(
            modifier = Modifier.fillMaxWidth(),
            horizontalArrangement = Arrangement.SpaceEvenly
        ) {
            Button(
                onClick = {
                    try {
                        Toast.makeText(context, "Downloading", Toast.LENGTH_SHORT).show()
                        downloadHelper.prepare(callback)
//                        downloadManager.addDownload(downloadHelper.getDownloadRequest())
                        Toast.makeText(context, "Downloaded", Toast.LENGTH_SHORT).show()

                    } catch (e: Exception) {
                        Toast.makeText(context, e.message, Toast.LENGTH_SHORT).show()
                    }
                },
                modifier = Modifier
                    .padding(10.dp)
                    .weight(1f)
            ) {
                Text(text = "Download")
            }

            val downloadManagerrr =
                context.getSystemService(Context.DOWNLOAD_SERVICE) as android.app.DownloadManager
            Button(
                onClick = {
                    Toast.makeText(context, "Downloading", Toast.LENGTH_SHORT).show()
                    FileDownloadObject.downloadFile(
                        downloadManagerrr,
                        "https://demo.unified-streaming.com/k8s/features/stable/video/tears-of-steel/tears-of-steel.mp4/.m3u8",
                        context

                    )

                },
                modifier = Modifier
                    .padding(10.dp)
                    .weight(1f)
            ) {
                Text(text = "PlayOffline")
            }
        }
    }

}

@Composable
fun ExoplayerUi(uri: Uri, modifier: Modifier = Modifier) {

    val mediaItem =  MediaItem.Builder()
        .setUri(uri)
        .setMediaId("dummyId")
        .setMediaMetadata(
            MediaMetadata.Builder()
                .setTitle("Demo Video")
                .build()
        )
        .setMimeType("application/vnd.apple.mpegurl")
        .build()

    val context = LocalContext.current

    val exoPlayer = remember {
        ExoPlayer.Builder(context)
            .build()
            .apply {
                val defaultDataSourceFactory = DemoUtil.getHttpDataSourceFactory(context)
                val mediaSource = HlsMediaSource.Factory(defaultDataSourceFactory!!).createMediaSource(mediaItem)
                playWhenReady = true
                addMediaSource(mediaSource)
                prepare()
                addListener(object :Listener{
                    override fun onPlayerError(error: PlaybackException) {
                        super.onPlayerError(error)
                        Toast.makeText(context, error.message, Toast.LENGTH_SHORT).show()
                    }
                })
            }
    }

    AndroidView(
        modifier = modifier,
        factory = { _ ->
            PlayerView(context).apply {
                player = exoPlayer
                resizeMode = RESIZE_MODE_FIT

            }
        }
    )
}

whenever i dowload file the file size is zero bytes and it stores as uid format dont know why

**Comment by marcbaechinger** [comment]
>  val downloadManagerrr =
>            context.getSystemService(Context.DOWNLOAD_SERVICE) as android.app.DownloadManager
> 
>  FileDownloadObject.downloadFile(
>                    downloadManagerrr,
>                    "https://demo.unified-streaming.com/k8s/features/stable/video/tears-of-steel/tears-of-steel.mp4/.m3u8",
>                    context
>               )

This is not a Media3 API. I don't think that this `DownloadManager` that you are using is aware that this is a media download. I'd expect that it just downloads the manifest behind the given URI. It seems you mix using different APIs for downloading.

Best is to try the file in the demo app first. 
When I add your media URI to the demo app downloading works as well as playback of the downloaded media.

I recommend looking into the [Developer Guide regarding downloading media](https://developer.android.com/guide/topics/media/exoplayer/downloading-media).

I'm closing this issue. If you have further issues/questions, then please file a new issue in the new [androidx/media repository ](https://github.com/androidx/media/issues) instead. If you do that, please be aware that we can't give you 1:1 support on your application code I'm afraid.

**Comment by jasi381** [comment]
Actually i got the error and i fixed the code
