### ISSUE TITLE
Input does not start with the #EXTM3U header

### ISSUE THREAD

**Issue by ss0715jj** [google/ExoPlayer#11276]
### Bug

Hello, I tried to play the hls video, but some url caused the error 
"androidx.media3.common.ParserException: Input does not start with the #EXTM3U header.{contentIsMalformed=true, dataType=4}"

![image](https://github.com/google/ExoPlayer/assets/29917471/6c313404-e2c9-403d-b701-0886f5f74280)

The url used is "https://th2.ani90.com/k21/20687m1/index.m3u8"

MediaSourceEventListener calls onLoadError Below is the response header value

![image](https://github.com/google/ExoPlayer/assets/29917471/ba446274-c2c5-44bd-a20e-10419709cd46)

I tested this url on vlc player and it played.

Please let me know if you need any more information
Thank you for

**Comment by marcbaechinger** [comment]
When I try this URI with 

```
curl -v "https://th2.ani90.com/k21/20687m1/index.m3u8"
```

I don't manager to get an HLS playlist. It complains about SSL protocol problems.
Can you please make sure that the URI works?
You can test this with other http clients than ExoPlayer first also.

If you think it is possible to download the playlist from that URI and you think it is a problem of the Meda3 library then please file a new issue. 

This repository is deprecated and the issue trackeer is closed. So please do this in the in the new repository [androidx/media](https://github.com/androidx/media/issues/new?assignees=&labels=question%2C+needs+triage&projects=&template=question.md&title=) and file your question there.
