### ISSUE TITLE
Configuration For Kotlin DSL

### ISSUE THREAD

**Issue by electrodragon** [google/ExoPlayer#11275]
I'm implementing in build.gradle.kts, but it's not working
gradle.ext.exoplayerPrefix = "blahbhal"
This .ext field doesn't exist, Android Studio Girrafe

**Comment by marcbaechinger** [comment]
You need to give us a bit more context to make this actionable.

Please do this in the in the new repository [androidx/media](https://github.com/androidx/media/issues/new?assignees=&labels=question%2C+needs+triage&projects=&template=question.md&title=) and file your question there.


I'm closing this issue.

**Comment by icbaker** [comment]
I've updated the README instructions with Gradle Kotlin DSL examples: https://github.com/google/ExoPlayer/commit/4421ca90bdb275a242798fee06c6c6d5e0969d9c
