### ISSUE TITLE
When using the custom GLSurfaceView, when I seekTo progress from one video to another, the video screen still shows the same screen as the previous video, long before it shows correctly

### ISSUE THREAD

**Issue by AndroidYou** [google/ExoPlayer#11271]
### Bug

When using the custom GLSurfaceView, when I seekTo progress from one video to another, the video screen still shows the same screen as the previous video, long before it shows correctly

**Comment by tonihei** [comment]
The `com.google.android.exoplayer2` project is now deprecated. We are not
accepting any new issues in this project. Please file your issue in the
`androidx.media3` GitHub project instead:
https://github.com/androidx/media/issues

Please also include more detailed reproduction steps as requested by the issue template, thanks!
