### ISSUE TITLE
How can I set a subtitle and audio in castplayer

### ISSUE THREAD

**Issue by sajjadshahbazi** [google/ExoPlayer#11287]
### Bug

I want to set a subtitle and audio in the CastPlayer, but I Can't.

for subtitle, I Set :

```       
 val mediaItem = MediaItem.Builder()
            .setUri(Uri.parse(videoUrl))
            .setMimeType(mediaType)
            .setMediaMetadata(movieMetadata)
            .setTag(videoUrl)
            .setSubtitleConfigurations(
                listOf(MediaItem.SubtitleConfiguration.Builder(Uri.parse(subtitleUrl)).build())
            ).build()
```

for the subtitle, it didn't work.
After that I used this: https://github.com/google/ExoPlayer/issues/8669#issuecomment-792719685
First I converted from MediaItem to MediaQueueItem, and when I was making MediaQueueItem I Set Subtitle MediaTracks, After making the MediaQueueItem, I Converted the MediaQueueItem to MediaItem, and then I set the MediaItem to CastPlayer. but after preparing CastPlayer, I can't find Subtitle Tracks.

**Comment by icbaker** [comment]
The `com.google.android.exoplayer2` project is now deprecated. We are not accepting any new issues in this project. Please file your issue in the `androidx.media3` GitHub project instead: https://github.com/androidx/media/issues
