### ISSUE TITLE
How to add friendly obstructions to Exoplayer IMA Extension for 2.11.8 version

### ISSUE THREAD

**Issue by osaka911** [google/ExoPlayer#11286]
Hi all,

I use Exoplayer IMA Extension v2.11.8 to custom a ad player.
How to add friendly obstructions view to Exoplayer IMA Extension ?

Thank you,

**Comment by marcbaechinger** [comment]
For client side ads, the `ImaAdsLoader` has a method [`getAdDisplayContainer()`](https://github.com/androidx/media/blob/release/libraries/exoplayer_ima/src/main/java/androidx/media3/exoplayer/ima/ImaAdsLoader.java#L471) that returns you an `AdDisplayContainer`. This is a component of the ads SDK that offers a `addFriendlyObstruction()`. Please see the JavaDoc of [`getAdDisplayContainer()`](https://github.com/androidx/media/blob/release/libraries/exoplayer_ima/src/main/java/androidx/media3/exoplayer/ima/ImaAdsLoader.java#L471) also. 

For server-side ad insertion there isn't currently a way to do that.

**Comment by osaka911** [comment]
Dear @marcbaechinger,
Thanks for your reply,
Kindly check the code below is correct.

```kotlin
fun requestAds(requestData: AdsRequestData, friendlyObstructionList: List<FriendlyObstruction>) {
  val urlVmapApi: String = “link map | vast”

  adsLoader = builder?.buildForAdTag(Uri.parse(urlVmapApi))
  friendlyObstructionList.forEach { friendlyObstruction -> adsLoader?.adDisplayContainer?.registerFriendlyObstruction(friendlyObstruction) }
  if (loaderListener != null) adsLoader?.let { loaderListener!!.onResponse(it) }
}
```
And Is there a way to check if the overlay registration is working properly?

Thank a lot.

**Comment by marcbaechinger** [comment]
I can not review code that is related to the ads SDK I'm afraid. 

It looks like you are using the correct API. I can't tell whether this is correct in the sense of this being an accepted obstruction after calling that API.

**Comment by osaka911** [comment]
it's OK.
Thanks for your supports.
