### ISSUE TITLE
onPlayerError errorCode 4003

### ISSUE THREAD

**Issue by androidlukas** [google/ExoPlayer#11280]
### Bug

onPlayerError message MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.4D403C, -1, null, [820, 3552, 24.000002, null], [-1, -1]), format_supported=NO_EXCEEDS_CAPABILITIES

` com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:601)
android.os.Handler.dispatchMessage(Handler.java:102)
stackTrace android.os.Looper.loopOnce(Looper.java:226)
stackTrace android.os.Looper.loop(Looper.java:313)
stackTrace android.os.HandlerThread.run(HandlerThread.java:67)`

I try to play video on phone Samsung A22 5G and catch this error
*video sample I sent [dev.exoplayer@gmail.com](mailto:dev.exoplayer@gmail.com)

**Comment by icbaker** [comment]
The `com.google.android.exoplayer2` project is now deprecated. We are not accepting any new issues in this project. Please file your issue in the `androidx.media3` GitHub project instead: https://github.com/androidx/media/issues
