### ISSUE TITLE
How to programmatically mute the video?

### ISSUE THREAD

**Issue by trangvu9** [google/ExoPlayer#11295]
I have something like this but it doesn't work:

    player.setDeviceMuted(true);

I searched all over the android doc but all I found is deprecated warning.

This is such a basic functionality that's so hard to get right.

**Comment by rohitjoins** [comment]
Hi @trangvu9,

You can try setting the volume to 0. Please see the [documentation](https://developer.android.com/reference/androidx/media3/common/Player#setDeviceVolume(int,int)).

Btw the com.google.android.exoplayer2 project is now deprecated. We are not accepting any new issues in this project. Please file your issue in the androidx.media3 GitHub project instead: https://github.com/androidx/media/issues
