### ISSUE TITLE
DRM video not playing 

### ISSUE THREAD

**Issue by HiddenPirates** [google/ExoPlayer#11296]
I use to play DRM video with this code. Some drm video is playing but many are not playing. Please fix my code.

`DataSource.Factory defaultHttpDataSourceFactory = new DefaultHttpDataSource.Factory()
                .setUserAgent(userAgent)
                .setTransferListener(
                        new DefaultBandwidthMeter.Builder(PlayerActivity.this)
                                .setResetOnNetworkTypeChange(false)
                                .build()
                );

        DashChunkSource.Factory dashChunkSourceFactory = new DefaultDashChunkSource.Factory(defaultHttpDataSourceFactory);

        DataSource.Factory manifestDataSourceFactory = new DefaultHttpDataSource.Factory().setUserAgent(userAgent);

        UUID drmSchemeUuid = Util.getDrmUuid(drmScheme.toString());

        assert drmSchemeUuid != null;

        return new DashMediaSource.Factory(dashChunkSourceFactory, manifestDataSourceFactory)
                        .createMediaSource(
                                new MediaItem.Builder()
                                        .setUri(uri)
                                        // DRM Configuration
                                        .setDrmConfiguration(
                                                new MediaItem.DrmConfiguration.Builder(drmSchemeUuid)
                                                        .setLicenseUri(drmLicenseUrl).build()
                                        )
                                        .setMimeType(MimeTypes.APPLICATION_MPD)
                                        .setTag(null)
                                        .build()
                        );`

**Comment by rohitjoins** [comment]
The com.google.android.exoplayer2 project is now deprecated. We are not accepting any new issues in this project. Please file your issue in the androidx.media3 GitHub project instead: https://github.com/androidx/media/issues
