### ISSUE TITLE
Is exposing properties for skipSilence still possible?

### ISSUE THREAD

**Issue by mseroczynski** [google/ExoPlayer#11297]
I've found below tips here:
https://github.com/google/ExoPlayer/issues/6705

But they seem to be outdated as 
```
      override fun buildAudioRenderers(context: Context,
                                       extensionRendererMode: Int,
                                       mediaCodecSelector: MediaCodecSelector,
                                       enableDecoderFallback: Boolean,
                                       audioSink: AudioSink,
                                       eventHandler: Handler,
                                       eventListener: AudioRendererEventListener,
                                       out: ArrayList<Renderer>)
```
...does not expose ```audioProcessors``` anymore. I haven't found any simple way to adjust skip silence properties with current implementation and it is heavily requested feature in my app. Could you confirm that if it is currently anyhow possible?

**Comment by rohitjoins** [comment]
The com.google.android.exoplayer2 project is now deprecated. We are not accepting any new issues in this project. Please file your issue in the androidx.media3 GitHub project instead: https://github.com/androidx/media/issues.
