### ISSUE TITLE
Since the provided demo cannot be used, why can't we replace it with a new one? What is the purpose of this demo anyway?

### ISSUE THREAD

**Issue by iiheng** [google/ExoPlayer#11294]
Do we need a new demo that uses the new API? The current APIs are all outdated.

**Comment by rohitjoins** [comment]
The com.google.android.exoplayer2 project is now deprecated. We are not accepting any new issues in this project. Please file your issue in the androidx.media3 GitHub project instead: https://github.com/androidx/media/issues
