### ISSUE TITLE
[Request] Update IMA SDK to the latest version

### ISSUE THREAD

**Issue by devno44** [google/ExoPlayer#11298]
Regarding the issue bellow, please update IMA SDK to the latest version. This is a very serious bug and needs to be fixed urgently. Otherwise there will be problems updating target SDK to version 34.
https://groups.google.com/g/ima-sdk/c/XCrb5a5WiYI

Thank you !

**Comment by rohitjoins** [comment]
Duplicate of https://github.com/androidx/media/issues/665
