### ISSUE TITLE
The exoplayer is in a paused state, the surface has been released. At this time, dequeue graphic buffer from surface failed, causing mediacodec to report 0x80000000 Error

### ISSUE THREAD

**Issue by captain81** [google/ExoPlayer#11305]
### Bug

The exoplayer is in a paused state, and the surface has been released at this time. ExoPlayer will still dequeue input buffer and output buffer from modiacodec. At this time, dequeue graphic buffer from surface failed, causing mediacodec to report 0x80000000 Error. Please tell me how to solve this problem

**Comment by marcbaechinger** [comment]
The com.google.android.exoplayer2 project is now deprecated. We are not accepting any new issues in this project. Please file your issue in the androidx.media3 GitHub project instead: https://github.com/androidx/media/issues.
