### ISSUE TITLE
Blank Screen in Video

### ISSUE THREAD

**Issue by HakimBlaze10** [google/ExoPlayer#11308]
### Bug

I am using ExoPlayer library 2.18.0 with PlayerControlView.

The goal is to play a video from online and local source.

When I try to play the video on the device (RealMe X) the audio works well but the video layout is blank, and also the controls disappear around 5 seconds in.

**Comment by tianyif** [comment]
Hi @HakimBlaze10,

Unfortunately we cannot provide help with the limited information. Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/androidx/media/issues/new?assignees=&labels=bug%2Cneeds+triage&template=bug.yml). If you're unable to share [bug reports](https://developer.android.com/studio/debug/bug-report) or test content publicly, please send them to android-media-github@google.com with the subject `Issue #1234`. Please also update this issue to indicate you've done this.

**Comment by icbaker** [comment]
The `com.google.android.exoplayer2` project is now deprecated. We are not accepting any new issues in this project. Please file any new issues in the `androidx.media3` GitHub project instead: https://github.com/androidx/media/issues
