### ISSUE TITLE
oldPosition info and newPosition info return -1 for adGroupIndex

### ISSUE THREAD

**Issue by moniqueeeeee** [google/ExoPlayer#11303]
### Bug

Please support 

i have 3 preRoll and when i listen to "onPositionDiscontinuity" before first preroll started always return -1 for agroupIndex, it should return 0 for that to get firstAdGroup and first Adbreak ,

is there any idea how to return 0 or how to get firstAdgroup

i am using serversidemediasource

**Comment by marcbaechinger** [comment]
The com.google.android.exoplayer2 project is now deprecated. We are not accepting any new issues in this project. Please file your issue in the androidx.media3 GitHub project instead: https://github.com/androidx/media/issues.
