### ISSUE TITLE
https://github.com/androidx/media/issues/new?template=feature_request.md

### ISSUE THREAD

**Issue by Aziz83yahya** [google/ExoPlayer#11300]
**Please do not file new issues in this repository.**

All new feature requests should be filed in the
[Media3 issue tracker](https://github.com/androidx/media/issues/new?template=feature_request.md).

We will continue to update and reply to existing issues in this repository and
will keep existing feature requests active.

**Comment by rohitjoins** [comment]
Issue has only the template and no other information. Closing this now. Please reopen this one after editing or create another issue to provide information.

**Comment by Aziz83yahya** [comment]
Connecting to server
