### ISSUE TITLE
Screen blacks out on orientation changes(Dash with Widevine)

### ISSUE THREAD

**Issue by Amritpal33** [google/ExoPlayer#1130]
I am using Exoplayer with Dash+widevine Streaming. On orientation changes of the device the screen blackens out and then become visible on changed orientation,While the same is not happening in HLS Streaming.

Where is the issue and how can i fix it..Please help.

Thanks..!

**Comment by ojw28** [comment]
I believe this [is|was] a platform limitation related to secure surfaces, so there's nothing we can do to fix it in ExoPlayer itself. I haven't checked, but I have a feeling this has been fixed in recent Android platform releases.
