### ISSUE TITLE
configuration of bufferedFractionToLiveEdgeForQualityIncrease

### ISSUE THREAD

**Issue by Xlcghs** [google/ExoPlayer#11315]
Hello, 
Do you have a special api for changing the bufferedFractionToLiveEdgeForQualityIncrease value in a live case?

**Comment by tonihei** [comment]
The com.google.android.exoplayer2 project is now deprecated. We are not accepting any new issues in this project. Please file your issue in the androidx.media3 GitHub project instead: https://github.com/androidx/media/issues

There is an `AdaptiveTrackSelection.Factory` constructor that takes this value as an argument. It can't be changed at run-time (if that was your question).
