### ISSUE TITLE
ERROR_CODE_DRM_SYSTEM_ERROR 6006 while playing a drm content on android tv 7.1.2

### ISSUE THREAD

**Issue by raa-ju** [google/ExoPlayer#11314]
Hi,
When I try to play a drm content on android tv android version 7.1.2 it throws playbackException ERROR_CODE_DRM_SYSTEM_ERROR and error code 6006. But on newer version android tv it works well.
I used pallycon's widevine drm  configuration.

How to resolve it?

**Comment by tonihei** [comment]
The com.google.android.exoplayer2 project is now deprecated. We are not accepting any new issues in this project. Please file your issue in the androidx.media3 GitHub project instead: https://github.com/androidx/media/issues

This sounds like a device-specific DRM issue and it's unlikely we can provide a solution for this.
