### ISSUE TITLE
How to Pre cache list of HLS urls  

### ISSUE THREAD

**Issue by Usama99786** [google/ExoPlayer#11311]
I am building an  app like tiktok. I have a list of hls urls that I am getting from my server. I want to be able to precache them, So I won't have to wait for the video to load. I was able to achieve this for mp4 videos using CacheWriter. Is it possible to achieve this for hls urls?

**Comment by tonihei** [comment]
The com.google.android.exoplayer2 project is now deprecated. We are not accepting any new issues in this project. Please file your issue in the androidx.media3 GitHub project instead: https://github.com/androidx/media/issues

Please see https://developer.android.com/guide/topics/media/exoplayer/downloading-media#dl-play-adaptive-streams for details around downloading adaptive media. We are also working on improvements for pre-caching/pre-warming items for the type of app you are building and will publish more concrete guidelines around this topic once this is ready.
