### ISSUE TITLE
Migrating from exoplayer2

### ISSUE THREAD

**Issue by dreich** [google/ExoPlayer#11310]
Please tell me how to run the migration script media3-migration.sh in Windows?

**Comment by tianyif** [comment]
Hi @dreich,

Please checkout our [migration guide](https://developer.android.com/guide/topics/media/media3/getting-started/migration-guide) for instructions.

**Comment by marcbaechinger** [comment]
@dreich You'd need to find an execution environment on Windows that can run the bash script. Sorry for not having a better answer, but I doubt there will be direct support for Windows without a Unix shell.

**Comment by icbaker** [comment]
https://learn.microsoft.com/en-us/windows/wsl/install might be worth a look (but I'm afraid we don't have a Windows environment to test it with).
