### ISSUE TITLE
Fully synchronised audio playback with a `MixingAudioProcessor`

### ISSUE THREAD

**Issue by thomas-coldwell** [google/ExoPlayer#11317]
Hi 👋 I have been using ExoPlayer to try and play multiple audio tracks simultaneously. The setup I have at the minute consists of multiple audio renderers with one main renderer that holds the `MediaClock`. I also make use of asynchronous rendering so that they can be as in-sync with each other during playback as possible. However, they do still play the output slightly out of sync (~20ms) due to each having a separate `AudioSink` and subsequent `AudioTrack` they output to (I guess there is some kind of queue or lock at the audio HW level).

In order to fix this [the recommendation from the ExoPlayer team](https://github.com/google/ExoPlayer/issues/4261#issuecomment-389847939) seems to be to actually mix the audio before output by waiting for the PCM buffer of each audio renderer, then mixing and delivering this to a single AudioSink for playback. From my understanding this can be achieved like so:

- Create an instance of a custom `MixingAudioProcessor` in the renderers factory that can be accessed by ALL of the audio renderers
- Create a `DefaultAudioSink` and put the `MixingAudioProcessor` in its processing chain and pass this to the main audio renderer. We can then get the buffer when `queueInput` is called
- Then in each of the other audio renderers we need to pass in a custom audio sink (let's call it `CapturingAudioSink`) rather than the default audio sink otherwise this would just play out to a new audio track. Instead this custom audio sink should capture the output in the `handleBuffer` method and pass this over to the `MixingAudioProcessor`
- Within the `MixingAudioProcessor`, once we see we have got a chunk for all of the audio renderers then we can mix these together and write it into `replaceOutputBuffer` so that the mixed buffer is then played out by the single audio sink / `AudioTrack`

I sketched this out a little below so it's a bit clearer:
![image](https://github.com/google/ExoPlayer/assets/31568400/8a6f5966-235c-4b14-bd9e-7dfde18a483a)

I've now got this setup in my app, however, I'm running into a bit of a chicken and egg issue. Looking at the diagram you can see that the other (non-main) audio renderers will only output (to the `handleBuffer` method in that `CapturingAudioSink`) if the MediaClock advances. However, the MediaClock will only advance if we actually call `replaceOutputBuffer` in the audio processor and fill it with some data which gets passed to the `AudioTrack` - which only happens if we have the buffers from all of the renderers to produce the mixed output buffer. As a result nothing happens in this current setup - it simply stays at t = 0s and there is no audio output at all. 

I'm really not quite sure how to fix this issue or if there is some other way to achieve the original goal of having synchronised, sample-accurate playback of multiple audio tracks. If you could point me in the right direction here that would be greatly appreciated and happy to share actual code relating to the setup we currently have through private channels (e.g. email) 🙌

**Comment by icbaker** [comment]
The `com.google.android.exoplayer2` project is now deprecated. We are not accepting any new issues in this project. Please file your issue in the `androidx.media3` GitHub project instead: https://github.com/androidx/media/issues
