### ISSUE TITLE
Exoplayer and low latency CMAF

### ISSUE THREAD

**Issue by alfonsoramosa** [google/ExoPlayer#11316]
Hi,

I can see in the list of supported formats, that CMAF is already supported https://exoplayer.dev/supported-formats.html

We are looking into reducing the latency of our live streams going into low latency with CMAF over DASH + Widevine as DRM

Will Exoplayer support that out of the box in any AndroidTv device (where Widevine is mandatory), or it needs any kind of support from the device or chipset?

Thank you

**Comment by tonihei** [comment]
The com.google.android.exoplayer2 project is now deprecated. We are not accepting any new issues in this project. Please file your issue in the androidx.media3 GitHub project instead: https://github.com/androidx/media/issues

And to answer your questions: Both DRM protection with Widevine and low-latency streaming with DASH are supported out of the box. The main device/chipset-specific requirement is that the decoder for your format needs to have a secure variant (which should be widely available on most AndroidTV devices).
