### ISSUE TITLE
seeking method for simultaneous video speed and voice Change

### ISSUE THREAD

**Issue by KimDandan** [google/ExoPlayer#11327]
Hello,

I'm looking to implement the following features:
- Adjusting the speed of videos (which include audio).
- Changing the audio's voice (for instance, making a human voice sound like a robot).

Here's the approach I've considered:
- Use SimpleExoPlayer's setPlaybackParameters function for speed adjustment.
- For voice change, extend the BaseAudioProcessor and manipulate the inputBuffer.

Is it possible to implement it this way?
Both features must work together.
If there's a better approach or any recommendations, I'd greatly appreciate your guidance.

Thank you.

**Comment by tonihei** [comment]
This is untested, but I think when you build you own `DefaultAudioSink` in `DefaultRenderersFactory.buildAudioSink`, you can specify a custom `AudioProcessorChain` via `DefaultAudioSink.Builder.setAudioProcessorChain`. This allows you to intercept the call to `AudioProcessorChain.applyPlaybackParameters` to set the speed on the `SonicAudioProcessor` and also reconfigure your custom audio processor at the same time.
