### ISSUE TITLE
Exoplayer and HLS i-frames track for trick modes

### ISSUE THREAD

**Issue by alfonsoramosa** [google/ExoPlayer#11323]
Hi

We are looking into different alternatives to implement a more user friendly trick play for live and VOD content on AndroidTv using Exoplayer.

What we want to improve is the user to easily identify the position he is moving to when scrubbing (rewind, ...), or by using thumbnails or updating the video window very quickly while the user is navigating in the progress bar

One idea is to use HLS on AndroidTv as our HLS streams already have the I-frames low bitrate tracks that Apple uses for this purpose.

Is that functionality (to use these low bitrate I-frames tracks for this purpose and only for this purpose) supported by Exoplayer? meaning using them in the same way as Apple native player is using them on AppleTv

Thank you!

**Comment by tianyif** [comment]
Hi @alfonsoramosa,

The whole support of trick play touches several parts of the library, please checkout https://github.com/google/ExoPlayer/issues/3752#issuecomment-1147346684 for the detailed breakdowns. So far for HLS, we have the supports of parsing the I-frames tracks information from the playlist (part 1 in the above comment), and extracting the sample data from video container based formats (part 2 in the above comment). The rest of the list haven't been covered yet, which should all be tracked in https://github.com/google/ExoPlayer/issues/3752.
