### ISSUE TITLE
Looking for a way to update volume of each audio tracks in single video file

### ISSUE THREAD

**Issue by Saket7042** [google/ExoPlayer#11329]
Hello,

I'm building a feature to manipulate each audio track volume of a video and play it after that in Exoplayer. I'm using Media3 libraries 

Here's the approach I've considered:

I'm trying to fetch all audio tracks inside a video and for this I'm using MetadataRetriever.retrieveMetadata(this, inputMediaItem) and getting TrackGroup but from here I'm not able to find any suitable method to use AudioProcessor on each TrackGroup. 

There is this method as well EditedMediaItem.Builder(inputMediaItem).setEffects() in this we can pass AudioProcessor list but as I want to change volume of each track separately so not sure how I can achieve this. 

Please suggest some approach to implement this feature. 

Thank you.

**Comment by andrewlewis** [comment]
Just to check, do you prefer to modify the volumes on the fly (during playback) or do you want to produce a new video file with the changes then play that as a 'normal' file?

In either case [`ChannelMixingAudioProcessor`](https://github.com/androidx/media/blob/release/libraries/common/src/main/java/androidx/media3/common/audio/ChannelMixingAudioProcessor.java) with a matrix that keeps the same number of channels but has a non-1 mixing coefficient should work for this. It's just a question of whether you apply it via `ExoPlayer` or use `Transformer` to produce a file then play it as normal.

**Comment by Saket7042** [comment]
Thanks for the quick reply @andrewlewis 

I'm working on shorts/reels creation feature in that we have 3 different audio. Which are these
1.  Original video sound
2. Voiceover which can be provided by user's mic
3.  External audio clip which can be selected by user

I've to modify this on the fly(during playback) as well as create a new video file once user done with final changes. I'll look into this [ChannelMixingAudioProcessor](https://github.com/androidx/media/blob/release/libraries/common/src/main/java/androidx/media3/common/audio/ChannelMixingAudioProcessor.java)

So, to achieve this I've to  pass volume float value to each Custom ChannelMixingAudioProcessor class for each audio tracks. 

Just guessing there will be a few issues 
 
1. I've to identify what is the type(Original, Voiceover, External audio) of audio track and based on the type what volume should be set.
2. As I'm trying to modify it on the fly and playing on Exoplayer so processing time may be long.

**Comment by Gustl22** [comment]
I also want to modify the values on the fly, but once the `AudioSink` is build, the values are not able to be changed anymore, see [source](https://github.com/bluefireteam/audioplayers/blob/gustl22/exoplayer/packages/audioplayers_android_exo/android/src/main/kotlin/xyz/luan/audioplayers/player/ExoPlayerWrapper.kt):

```kotlin
class ExoplayerWrapper {
    private var player: ExoPlayer

    @androidx.annotation.OptIn(androidx.media3.common.util.UnstableApi::class)
    private var channelMixingAudioProcessor = ChannelMixingAudioProcessor()

    init {
        player = createPlayer(appContext)
    }

    @androidx.annotation.OptIn(androidx.media3.common.util.UnstableApi::class)
    private fun createPlayer(appContext: Context): ExoPlayer {
        val renderersFactory = object : DefaultRenderersFactory(appContext) {
            override fun buildAudioSink(
                context: Context,
                enableFloatOutput: Boolean,
                enableAudioTrackPlaybackParams: Boolean,
                enableOffload: Boolean,
            ): AudioSink {
                val audioSink =
                    DefaultAudioSink.Builder(appContext).setAudioProcessors(arrayOf(channelMixingAudioProcessor))
                        .build()
                return audioSink
            }
        }

        return ExoPlayer.Builder(appContext).setRenderersFactory(renderersFactory).build().apply {
            addListener(ExoPlayerListener(wrappedPlayer))
        }
    }

    @androidx.annotation.OptIn(androidx.media3.common.util.UnstableApi::class)
    override fun setVolume(leftVolume: Float, rightVolume: Float) {
        this.channelMixingAudioProcessor.putChannelMixingMatrix(
            ChannelMixingMatrix(
                2,
                2,
                floatArrayOf(leftVolume, 0f, 0f, rightVolume),
            ),
        )
    }
}
```

**Comment by andrewlewis** [comment]
The current implementation doesn't let you dynamically modify the channel weights, but you could fork the implementation to add support for that (aside: it's very likely that the weights will be set from a different thread than the playback thread which actually applies the values, so it will be necessary to make that work). I think @Samrobbo might have looked at doing this in the past and/or have some pointers.

One way to store the different audio sources would be as separate channels in a multi-channel audio stream. Then you can identify them based on channel index in the audio processor. (In the future we also plan to provide better support for mixing multiple audio streams together, but won't be available for a while.)

**Comment by Saket7042** [comment]
Yes, I've tried changing the volume on the fly but changes haven't reflected, But I can see this feature is implemented on instagram any idea how they have achieved it on Android.

**Comment by andrewlewis** [comment]
To be clear, the `ChannelMixingAudioProcessor` doesn't support this but I'm suggesting that you could take its code and modify it to support dynamic changes. We don't have time to give more detailed guidance about how to do that at the moment, but we'll probably add support for this at some point. I'll mark this as an enhancement to track that.

**Comment by andrewlewis** [comment]
Actually I'll close this because it's in our old repository. It seems to overlap with https://github.com/androidx/media/issues/797 anyway.
