### ISSUE TITLE
rtp multicast streaming

### ISSUE THREAD

**Issue by mouemen-Hares** [google/ExoPlayer#11322]
when i try to read a rtp multicast streaming i got this error:

java.net.ConnectException: failed to connect to /192.168.0.119 (port 1234) from /:: (port 47550): connect failed: ECONNREFUSED (Connection refused)

**Comment by icbaker** [comment]
The `com.google.android.exoplayer2` project is now deprecated. We are not accepting any new issues in this project. Please file your issue in the `androidx.media3` GitHub project instead: https://github.com/androidx/media/issues
