### ISSUE TITLE
I/ACodec: codec does not support config operating rate (err -2147483648)

### ISSUE THREAD

**Issue by zohaibmushwani** [google/ExoPlayer#11339]
### Bug

I have developed a custom curve view that provides speed values, and I'm using an FFmpeg wrapper in an Android application to apply these speed values to video segments. The primary goal is to enable variable playback speed for video segments in our front-end application.

I encountered an issue where I couldn't change the speed beyond a certain point. Specifically, I observed an error related to the operating rate in the logs.
I/ACodec: codec does not support config operating rate (err -2147483648)

I am speeding up or down the video using a handle and runnable for each segment and the next speed change is called after the time needs to be taken by segment. Still, I am facing issues after the speed does not change after some segments according to my speed list for the video.

I need to speedup or down the video from 0.1 to 10x.

**Comment by rohitjoins** [comment]
The com.google.android.exoplayer2 project is now deprecated. We are not accepting any new issues in this project. Please file your issue in the androidx.media3 GitHub project instead: https://github.com/androidx/media/issues
