### ISSUE TITLE
Discard Ad Breaks with the IMA Exoplayer extension

### ISSUE THREAD

**Issue by subarno26** [google/ExoPlayer#11335]
Hi, so we have a use case where we need to discard specific Ads as per various conditions. Earlier, the same was achievable through the AdsManager.discardAdBreaks() method which discarded the currently playing/next ad and resumed the content perfectly. However, we have made use of the IMA extension of Exoplayer where we cannot get a reference to the AdsManager class. Hence, there is no way to use the discardAdBreaks() method. 
Kindly suggest a way to discard specific ad breaks(pre/mid/post) on the player.

**Comment by rohitjoins** [comment]
The com.google.android.exoplayer2 project is now deprecated. We are not accepting any new issues in this project. Please file your issue in the androidx.media3 GitHub project instead: https://github.com/androidx/media/issues
