### ISSUE TITLE
Cannot resolve constructor 'Factory(BandwidthMeter)'

### ISSUE THREAD

**Issue by tuhoang1207** [google/ExoPlayer#11331]
This is my code:

@Override
    protected void onStart() {
        super.onStart();
        playerView = findViewById(R.id.video_player);
        BandwidthMeter bandwidthMeter = new DefaultBandwidthMeter.Builder(getApplicationContext()).build();
        TrackSelector trackSelector = new DefaultTrackSelector(new AdaptiveTrackSelection.Factory(bandwidthMeter));
    }

TrackSelector cannot resolve Factory(bandwidthMeter). I had try to remove bandwidthMeter like the instruction but nothing changed.
Is there any issue for this? Thank you

**Comment by rohitjoins** [comment]
The com.google.android.exoplayer2 project is now deprecated. We are not accepting any new issues in this project. Please file your issue in the androidx.media3 GitHub project instead: https://github.com/androidx/media/issues
