### ISSUE TITLE
com.google.android.exoplayer2.audio.DefaultAudioSink.int writeNonBlockingV21(android.media.AudioTrack,java.nio.ByteBuffer,int)(DefaultAudioSink.java:1660)

### ISSUE THREAD

**Issue by ThugKd** [google/ExoPlayer#11337]
crash

device : vivo Android 12 & vivo Android 13

stack:

#23880 ExoPlayer:Playback

SIGSEGV(SEGV_MAPERR)

解析原始
1
#00 pc 000000000004ee98 /apex/com.android.runtime/lib64/bionic/libc.so (__memcpy+232) [arm64-v8a::65f0a078b7cc159a5d3df081e44378ff]
2
#01 pc 00000000000afd3c /system/lib64/libaudioclient.so (_ZN7android10AudioTrack5writeEPKvmb+428) [arm64-v8a::6caeb157802a9f66ad1a31426751b900]
3
#02 pc 000000000019abe4 /system/lib64/libandroid_runtime.so [arm64-v8a::3661ab0c311533ec0462b765c16c5794]
4
#03 pc 0000000000194b9c /system/lib64/libandroid_runtime.so [arm64-v8a::3661ab0c311533ec0462b765c16c5794]
5
#04 pc 00000000001e9e40 /system/framework/arm64/boot-framework.oat [arm64-v8a::dc515fc83489af34c666933c83619a7e]
6
java:
7
android.media.AudioTrack.write(AudioTrack.java:3443)
8
com.google.android.exoplayer2.audio.DefaultAudioSink.writeNonBlockingV21(SourceFile:1)
9
com.google.android.exoplayer2.audio.DefaultAudioSink.writeBuffer(SourceFile:24)
10
com.google.android.exoplayer2.audio.DefaultAudioSink.processBuffers(SourceFile:4)
11
com.google.android.exoplayer2.audio.DefaultAudioSink.handleBuffer(SourceFile:55)
12
com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(SourceFile:10)
13
com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(SourceFile:31)
14
com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(SourceFile:16)
15
com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(SourceFile:14)
16
com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(SourceFile:24)
17
android.os.Handler.dispatchMessage(Handler.java:102)
18
android.os.Looper.loopOnce(Looper.java:223)
19
android.os.Looper.loop(Looper.java:324)
20
android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by rohitjoins** [comment]
The com.google.android.exoplayer2 project is now deprecated. We are not accepting any new issues in this project. Please file your issue in the androidx.media3 GitHub project instead: https://github.com/androidx/media/issues
