### ISSUE TITLE
 AAC decoder overriding with component recommendation

### ISSUE THREAD

**Issue by FlogFly** [google/ExoPlayer#11341]
10-13 16:14:18.934  6573  9560 D CCodec  : client requested max input size 499, which is smaller than what component recommended (8192); overriding with component recommendation.
10-13 16:14:18.934  6573  9560 W CCodec  : This behavior is subject to change. It is recommended that app developers double check whether the requested max input size is in reasonable range.

10-13 16:14:18.941  6573  9560 E Codec2-types: Failed to send buffer with BufferPool. Error: 4.
10-13 16:14:18.941  6573  9560 E Codec2-types: Invalid block data in C2ConstLinearBlock.
10-13 16:14:18.941  6573  9560 E Codec2-types: Invalid C2BufferData::linearBlocks. (Destination index = 0.)
10-13 16:14:18.941  6573  9560 E Codec2-types: Invalid C2Buffer::data.
10-13 16:14:18.941  6573  9560 E Codec2-types: Invalid C2FrameData::buffers[0].
10-13 16:14:18.941  6573  9560 E Codec2-types: Invalid C2Work::input.
10-13 16:14:18.941  6573  9560 E Codec2Client: queue – bad input.

**The max input size value set when creating the AAC decoder is too small, resulting in an input buffer exception** 

But currently, I haven't seen any API related introduction on how to set this Max input size during the initialization of Exoplayer, because this issue doesn't always occur, even when playing the same audio, it's not necessary to do so.  
thanks

**Comment by rohitjoins** [comment]
The com.google.android.exoplayer2 project is now deprecated. We are not accepting any new issues in this project. Please file your issue in the androidx.media3 GitHub project instead: https://github.com/androidx/media/issues
