### ISSUE TITLE
Device capabilities report unsupported frameRate

### ISSUE THREAD

**Issue by matte86** [google/ExoPlayer#11345]
Hi guys,

On a Samsung Galaxy A52 4G we are seeing `MediaCodecInfo.VideoCapabilities.areSizeAndRateSupported` returning `false` for FullHD (1080p) at 50 fps, whereas from spec this device should be capable of dealing with 1920x1080 up to 60 fps.

Is there any known issue on capabilities reporting for this device?

**Comment by matte86** [comment]
This is probably related also to the discussion in https://github.com/google/ExoPlayer/issues/10898

**Comment by christosts** [comment]
> whereas from spec this device should be capable of dealing with 1920x1080 up to 60 fps

Can you point us to the spec? And what video format are you using? Eg. AVC (H264), HECV (H265) or something else?

**Comment by matte86** [comment]
Hi @christosts , from what I can see from [here](https://www.samsung.com/it/smartphones/galaxy-a/galaxy-a52-awesome-black-128gb-sm-a525fzkgeue/):

<img width="1345" alt="video_res" src="https://github.com/google/ExoPlayer/assets/22575026/44cb2cd5-4547-4a51-8777-56c0457af353">

We see this issue with H.264 DASH encoded streams.

**Comment by christosts** [comment]
Thanks. Strictly speaking, the spec says 4K@30fps and it doesn't mention 60fps. I visited the page and didn't see anything specific to 1080@60fps. 

We are not aware of a problem with this devide under-reporting its capabilities. 

What version of ExoPlayer are you using? ExoPlayer has switched to using [MediaCodecInfo.VideoCapabilities.getSupportedPerformancePoints()](https://developer.android.com/reference/android/media/MediaCodecInfo.VideoCapabilities#getSupportedPerformancePoints()) and not `MediaCodecInfo.VideoCapabilities.areSizeAndRateSupported`

**Comment by matte86** [comment]
Thanks for the feedback @christosts! About the following:

> Thanks. Strictly speaking, the spec says 4K@30fps and it doesn't mention 60fps. I visited the page and didn't see anything specific to 1080@60fps.

I see your point but aren't usually capabilities upper-bounded? The page does not mention explicitly 1080@60fps but it refers to 4K@30fps. I can read from the [PerformancePoint](https://developer.android.com/reference/android/media/MediaCodecInfo.VideoCapabilities.PerformancePoint) documentation:

> Video performance points are a set of standard performance points defined by number of pixels, pixel rate and frame rate. **_Performance point represents an upper bound. This means that it covers all performance points with fewer pixels, pixel rate and frame rate._**

**Comment by christosts** [comment]
I agree, hence I asked you earlier what version of ExoPlayer are you using.

> What version of ExoPlayer are you using? ExoPlayer has switched to using [MediaCodecInfo.VideoCapabilities.getSupportedPerformancePoints()](https://developer.android.com/reference/android/media/MediaCodecInfo.VideoCapabilities#getSupportedPerformancePoints()) and not MediaCodecInfo.VideoCapabilities.areSizeAndRateSupported()
