### ISSUE TITLE
VPX undefined reference JNI function when build

### ISSUE THREAD

**Issue by thanasuk** [google/ExoPlayer#1134]
I have mips generate file from generate_libvpx_android_configs.sh and build it in ndk-build .
it success to build libvpx.so 
But in case libvpxJNI it got error message 'undefined reference' 
I find some solution by add
     'LOCAL_ALLOW_UNDEFINED_SYMBOLS := true' 
it can compile successful but in VPXDecoder can't find native function :

==================================
===== ERROR IN VPXDecoder.java =====
==================================

01-11 13:07:47.221 2338-2338/? D/dalvikvm: No JNI_OnLoad found in /data/app-lib/com.google.android.exoplayer.demo.vp9opus-1/libvpx.so 0x2c5e1dd8, skipping init
01-11 13:07:47.231 2338-2338/? D/dalvikvm: Trying to load lib /data/app-lib/com.google.android.exoplayer.demo.vp9opus-1/libvpxJNI.so 0x2c5e1dd8
01-11 13:07:47.231 2338-2338/? E/dalvikvm: dlopen("/data/app-lib/com.google.android.exoplayer.demo.vp9opus-1/libvpxJNI.so") failed: Cannot load library: mips_relocate_got(linker.cpp:1236): cannot locate "vpx_codec_dec_init_ver"...
01-11 13:07:47.231 2338-2338/? W/System.err: java.lang.UnsatisfiedLinkError: Cannot load library: mips_relocate_got(linker.cpp:1236): cannot locate "vpx_codec_dec_init_ver"...
01-11 13:07:47.241 2338-2338/? W/System.err:     at java.lang.Runtime.loadLibrary(Runtime.java:371)
01-11 13:07:47.241 2338-2338/? W/System.err:     at java.lang.System.loadLibrary(System.java:535)
01-11 13:07:47.241 2338-2338/? W/System.err:     at com.google.android.exoplayer.ext.vp9.VpxDecoder.<clinit>(VpxDecoder.java:32)
01-11 13:07:47.251 2338-2338/? W/System.err:     at com.google.android.exoplayer.ext.vp9.LibvpxVideoTrackRenderer.isLibvpxAvailable(LibvpxVideoTrackRenderer.java:158)
01-11 13:07:47.251 2338-2338/? W/System.err:     at com.google.android.exoplayer.ext.vp9.LibvpxVideoTrackRenderer.getLibvpxVersion(LibvpxVideoTrackRenderer.java:165)
01-11 13:07:47.251 2338-2338/? W/System.err:     at com.google.android.exoplayer.demo.vp9opus.VideoPlayer.updateDebugInfoTextView(VideoPlayer.java:295)
01-11 13:07:47.251 2338-2338/? W/System.err:     at com.google.android.exoplayer.demo.vp9opus.VideoPlayer.onCreate(VideoPlayer.java:114)

===================================
And this is NDK-BUILD ERROR
===================================

C:\android\ExoPlayer\extensions\vp9\src\main\jni>c:\android\ndk\ndk-build
process_begin: CreateProcess(NULL, cat ./libvpx_android_configs/mips/libvpx_srcs.txt, ...) failed.
[mips] Compile        : vpx <= vpx_config.c
[mips] SharedLibrary  : libvpx.so
[mips] Install        : libvpx.so => libs/mips/libvpx.so
[mips] Compile++      : vpxJNI <= vpx_jni.cc
[mips] Compile++      : yuv_static <= compare.cc
[mips] Compile++      : yuv_static <= compare_common.cc
[mips] Compile++      : yuv_static <= compare_posix.cc
[mips] Compile++      : yuv_static <= convert.cc
[mips] Compile++      : yuv_static <= convert_argb.cc
[mips] Compile++      : yuv_static <= convert_from.cc
[mips] Compile++      : yuv_static <= convert_from_argb.cc
[mips] Compile++      : yuv_static <= convert_to_argb.cc
[mips] Compile++      : yuv_static <= convert_to_i420.cc
[mips] Compile++      : yuv_static <= cpu_id.cc
[mips] Compile++      : yuv_static <= format_conversion.cc
[mips] Compile++      : yuv_static <= planar_functions.cc
[mips] Compile++      : yuv_static <= rotate.cc
[mips] Compile++      : yuv_static <= rotate_argb.cc
[mips] Compile++      : yuv_static <= rotate_mips.cc
[mips] Compile++      : yuv_static <= row_any.cc
[mips] Compile++      : yuv_static <= row_common.cc
[mips] Compile++      : yuv_static <= row_mips.cc
[mips] Compile++      : yuv_static <= row_posix.cc
[mips] Compile++      : yuv_static <= scale.cc
[mips] Compile++      : yuv_static <= scale_argb.cc
[mips] Compile++      : yuv_static <= scale_common.cc
[mips] Compile++      : yuv_static <= scale_mips.cc
[mips] Compile++      : yuv_static <= scale_posix.cc
[mips] Compile++      : yuv_static <= video_common.cc
[mips] StaticLibrary  : libyuv_static.a
[mips] Compile        : cpufeatures <= cpu-features.c
[mips] StaticLibrary  : libcpufeatures.a
[mips] SharedLibrary  : libvpxJNI.so
C:/android/ExoPlayer/extensions/vp9/src/main/obj/local/mips/objs/vpxJNI/vpx_jni.o: In function `Java_com_googl
e_android_exoplayer_ext_vp9_VpxDecoder_vpxInit':
C:/android/ExoPlayer/extensions/vp9/src/main/jni/vpx_jni.cc:73: undefined reference to `vpx_codec_dec_init_ver
'
C:/android/ExoPlayer/extensions/vp9/src/main/jni/vpx_jni.cc:73: undefined reference to `vpx_codec_vp9_dx_algo'

C:/android/ExoPlayer/extensions/vp9/src/main/obj/local/mips/objs/vpxJNI/vpx_jni.o: In function `Java_com_googl
e_android_exoplayer_ext_vp9_VpxDecoder_vpxDecode':
C:/android/ExoPlayer/extensions/vp9/src/main/jni/vpx_jni.cc:97: undefined reference to `vpx_codec_decode'
C:/android/ExoPlayer/extensions/vp9/src/main/obj/local/mips/objs/vpxJNI/vpx_jni.o: In function `Java_com_googl
e_android_exoplayer_ext_vp9_VpxDecoder_vpxClose':
C:/android/ExoPlayer/extensions/vp9/src/main/jni/vpx_jni.cc:107: undefined reference to `vpx_codec_destroy'
C:/android/ExoPlayer/extensions/vp9/src/main/obj/local/mips/objs/vpxJNI/vpx_jni.o: In function `Java_com_googl
e_android_exoplayer_ext_vp9_VpxDecoder_vpxGetFrame':
C:/android/ExoPlayer/extensions/vp9/src/main/obj/local/mips/objs/vpxJNI/vpx_jni.o: In function `Java_com_google_android_exoplayer_ext_vp9_VpxDecoder_vpxGetFrame':
C:/android/ExoPlayer/extensions/vp9/src/main/jni/vpx_jni.cc:110: undefined reference to `vpx_codec_get_frame'
C:/android/ExoPlayer/extensions/vp9/src/main/obj/local/mips/objs/vpxJNI/vpx_jni.o: In function `Java_com_google_android_exoplayer_ext_vp9_VpxDecoder_getLibvpxVersion':
C:/android/ExoPlayer/extensions/vp9/src/main/jni/vpx_jni.cc:156: undefined reference to `vpx_codec_version_str'
C:/android/ExoPlayer/extensions/vp9/src/main/obj/local/mips/objs/vpxJNI/vpx_jni.o: In function `Java_com_google_android_exoplayer_ext_vp9_VpxDecoder_vpxGetErrorMessage':
C:/android/ExoPlayer/extensions/vp9/src/main/jni/vpx_jni.cc:161: undefined reference to `vpx_codec_error'
collect2.exe: error: ld returned 1 exit status
make.exe: *** [C:/android/ExoPlayer/extensions/vp9/src/main/obj/local/mips/libvpxJNI.so] Error 1

**Comment by ojw28** [comment]
@vigneshvg - Could you comment on this? Thanks!

**Comment by vigneshvg** [comment]
I haven't had the time to look into this yet. Will look into it and comment here soon.

**Comment by thanasuk** [comment]
same issue: 
https://github.com/google/ExoPlayer/issues/1148
