### ISSUE TITLE
Multicast ABR Support in ExoPlayer

### ISSUE THREAD

**Issue by efrep** [google/ExoPlayer#11349]
I am working on a project that involves streaming multimedia content via multicast ABR (Adaptive Bitrate Streaming). I was wondering if anyone could provide information on whether ExoPlayer currently supports this functionality or if there are future plans to incorporate it.

I have reviewed the available documentation, but I haven't found specific details about multicast ABR support. I would appreciate any guidance, resources, or examples that you can share on this topic.

**Comment by tianyif** [comment]
Hi @efrep,

We already deprecated the ExoPlayer library and media3 is its new home, and since this is an enhancement and is likely to be tracked in the future, could you please open this issue in the [media3](https://github.com/androidx/media) library?
