### ISSUE TITLE
Image Issue in Notification itemBuilder

### ISSUE THREAD

**Issue by YogeshSinghPathania** [google/ExoPlayer#11344]
### Bug

Hi @marcbaechinger, I'm facing the image blur issue in notification Android 13.  I have set the `setMediaMetadata ` builder of exoplayer version 2.19.1. There are two scenario: 

1. setArtworkUri()-> If I'm using this image showing pixelated.

2. setArtworkData()-> If I'm using this image is not showing. I have convert the bitmap image to byteArray but its still not work.

I have checked in media3 library where I have seen this comment -https://github.com/androidx/media/issues/168
But I have integrate the 'setMediaMetadata' by the exoplayer. Just need to verify is there any way to fix this error with Exoplayer library or do we need to change the code into media3.

 These are the library that I'm using:
    api "androidx.media:media:1.6.0"
    api "com.google.android.exoplayer:exoplayer:2.19.1"
    api "com.google.android.exoplayer:extension-mediasession:2.19.1"
    api "com.google.android.exoplayer:extension-ima:2.19.1"

Thanks

**Comment by tianyif** [comment]
Hi @YogeshSinghPathania,

The mentioned fix to https://github.com/androidx/media/issues/168 was in the media3 session module. While you can solve this issue with continuing using ExoPlayer library, we strongly recommend you to migrate media3 as we already deprecated ExoPlayer library.

If you still want to use ExoPlayer library, you can have your customised implementation of [`MediaSessionConnector.MediaMetadataProvider`](https://github.com/google/ExoPlayer/blob/release-v2/extensions/mediasession/src/main/java/com/google/android/exoplayer2/ext/mediasession/MediaSessionConnector.java#L394), with doing something similar to the below snippet:

```
public static final class MyMediaMetadataProvider implements MediaMetadataProvider {

  private final DefaultMediaMetadataProvider defaultMediaMetadataProvider;

  @Override
  public MediaMetadataCompat getMetadata(Player player) {
    MediaMetadataCompat defaultMetadataCompat = defaultMediaMetadataProvider.getMetadata(player);
    Bitmap artworkBitmap = ... // Your logic to get artwork bitmap
    return new MediaMetadataCompat.Builder(defaultMetadataCompat)
                         .putBitmap(MediaMetadataCompat.METADATA_KEY_ART, artworkBitmap)
                         .build();
  }
}
```
and set this customised metadata provider through the [setter](https://github.com/google/ExoPlayer/blob/release-v2/extensions/mediasession/src/main/java/com/google/android/exoplayer2/ext/mediasession/MediaSessionConnector.java#L696).

And if you are going to migrate to media3, please be sure on the type of your app. If your app is with a service, then migrating to Media3 will directly solve your problem. If you have a standalone `MediaSession` without a service. Then you should migrate though, there is no `MediaNotificationManager` without a service, so you have to do your notification below API 33 or by using [`PlayerNotificationManager`](https://github.com/androidx/media/blob/release/libraries/ui/src/main/java/androidx/media3/ui/PlayerNotificationManager.java).
