### ISSUE TITLE
how can I save video to local storage of exoplayer cached video like Tiktok does

### ISSUE THREAD

**Issue by ddavud-git** [google/ExoPlayer#11351]
**Please do not file new issues in this repository.**

All new questions should be filed in the
[Media3 issue tracker](https://github.com/androidx/media/issues/new?template=question.md).

We will continue to update and reply to existing issues in this repository and
will keep existing feature requests active.

**Comment by ddavud-git** [comment]
Can you explain how Exoplayer caching works and how can how can I save video to local storage of exoplayer cached video like Tiktok does ?

**Comment by tianyif** [comment]
Hi @ddavud-git,

Could you please file this question in [Media3 issue tracker](https://github.com/androidx/media/issues/new?template=question.md) as suggested?
