### ISSUE TITLE
eca3 - eca audio format

### ISSUE THREAD

**Issue by SerkanKUL** [google/ExoPlayer#11356]
exoplayer movie with mkv extension in eca3 audio format in the latest version. The movie plays but there is no sound. eca3 and eca do not recognize the audio format. what do we need to do

**Comment by tonihei** [comment]
The com.google.android.exoplayer2 project is now deprecated. We are not accepting any new issues in this project. Please file your issue in the androidx.media3 GitHub project instead: https://github.com/androidx/media/issues

Please also provide all the information requested in bug template (reproduction steps, example media etc).
