### ISSUE TITLE
how to dynamic refresh the metadata of one playing media item?

### ISSUE THREAD

**Issue by PeaceAllen** [google/ExoPlayer#11353]
Dear sir,

I configure exo player with a simple cache, player is playing one mp3 file on server. Because some reasons, the mp3 file is modified, eg. insert an ending curve or cut some duration.  then the player could not completely play the mp3 file or throw response 416 error. how to dynamic make the player refresh the metadata?

**Comment by microkatz** [comment]
The google/ExoPlayer project is now deprecated. We are not accepting any new issues in this project. Please file your issue in the `androidx.media3` GitHub project instead:
https://github.com/androidx/media/issues
