### ISSUE TITLE
How to limit the interval between change bitrate for HLS stream?

### ISSUE THREAD

**Issue by felixyangtw** [google/ExoPlayer#11354]
I use exoplayer 2.18.7 to play hls stream.  I found a phenomenon. If the network bandwidth change rapidly. The adaptive bitrate will change frequently sometimes. I found it change to one bitrate and change to next bitrate immediately(<1s). Is there any way to limit the interval  between two bitrate changing?I mean that when exoplayer change to one bitrate and keep playing at the bitrate for an assigned interval and do next bitrate changing?

**Comment by tonihei** [comment]
The com.google.android.exoplayer2 project is now deprecated. We are not accepting any new issues in this project. Please file your issue in the androidx.media3 GitHub project instead: https://github.com/androidx/media/issues

Please also provide more details of any customizations you've done (e.g. parameters in `AdaptiveTrackSelection.Factory` if any) and details about the media you are using to better understand the context.
