### ISSUE TITLE
CC function broken in 2.18.7

### ISSUE THREAD

**Issue by Pradip-whiz** [google/ExoPlayer#11360]
Hi Team,

I was using exoplayer version 2.8.4 and CC was working fine for my one of the client(live stream) also it worked on version 2.16.0 but recently I have updated my exoplayer to version 2.18.7 and CC function got broken.The live stream which I am trying is "https://live.field59.com/kwtv/kwtv1/playlist.m3u8". This is live stream and we have lot of users in USA.

Please can you help me on this.

Thanks.

**Comment by icbaker** [comment]
The `com.google.android.exoplayer2` project is now deprecated. We are not accepting any new issues in this project. Please file your issue in the `androidx.media3` GitHub project instead: https://github.com/androidx/media/issues
