### ISSUE TITLE
add support to play mpd dash which doesn't have default kid in it

### ISSUE THREAD

**Issue by imrsaleh** [google/ExoPlayer#11364]
### This project is deprecated

- [X] I understand this project is deprecated and this issue will be closed with no response.

**Comment by imrsaleh** [comment]
add support for playing DASH that do not have a default KID (Key ID) in ExoPlayer.
This can be achieved by updating ExoPlayer to support playing DASH files without a default kid or by modifying the default behavior of the library to handle this type of DASH correctly.

**Comment by oceanjules** [comment]
@imrsaleh thank you for your suggestion - as you noticed, the project is deprecated and we do not accept new issues here.

Note that your particular enhancement has been suggested before and we always refer to the official specification that requires that field - see https://github.com/androidx/media/issues/563
