### ISSUE TITLE
Video blinking when switching between videos with different ratios (Android 14 only)

### ISSUE THREAD

**Issue by marzic93** [google/ExoPlayer#11362]
### Bug

On Android 14, there seems to be an issue with video blinking when switching between videos with varying aspect ratios. 

https://github.com/google/ExoPlayer/assets/7560411/7a0405e8-e577-4aab-8fec-34bab03d86ac

It looks like the last frame of the first video was applied scale from the second video. 
<img width="460" alt="SCR-20231211-ugiq" src="https://github.com/google/ExoPlayer/assets/7560411/2c5ebed5-5c33-4bce-a7f3-cdb9fc90f189">
The final frame has a black background that causes a blinking effect.
<img width="464" alt="SCR-20231211-ugft" src="https://github.com/google/ExoPlayer/assets/7560411/0a715eaa-2f95-4b5a-9fc0-bfc517245fd1">

This bug is reproduced on Android 14, everything works fine on previous versions.   Device for testing: Pixel 7 Pro

I've also created an example project ( https://github.com/marzic93/ExoplayerBugExample ) to reproduce this bug.

**Comment by icbaker** [comment]
The `com.google.android.exoplayer2` project is now deprecated. We are not accepting any new issues in this project. Please file your issue in the `androidx.media3` GitHub project instead: https://github.com/androidx/media/issues
