### ISSUE TITLE
Stream link starts downloading instead of playing, after it dowwnloaded completely it starts playing.

### ISSUE THREAD

**Issue by rogplay** [google/ExoPlayer#11366]
### This project is deprecated

- [X] I understand this project is deprecated and this issue will be closed with no response.

**Comment by rogplay** [comment]
https://strapi5ocasstore.blob.core.windows.net/strapi5ocasstore/Indian/Indian Movies/Ok Jaanu/OK Jaanu.mkv
this is the link i want to play in exoplayer but instead of playing it starts downloading in background after downloading completely it plays the video

**Comment by marcbaechinger** [comment]
Check if the server supports HTTP range requests. If this is not the reason, evaluate what checkbox you clicked when filing this issue. You can refile here: https://github.com/androidx/media/issues
