### ISSUE TITLE
onDeviceVolumeChanged(int volume, boolean muted) is never triggered on a TV device 

### ISSUE THREAD

**Issue by devanandaBandi** [google/ExoPlayer#11361]
### Bug

Hi am using Exoplayer 2.18.7 on my app for TV and trying to notice the volume change for the TV through onDeviceVolumeChanged(int volume, boolean muted) but this is never triggered even though I change the volume through the TV remote. 
Is there any limitation for TV devices to keep track of volume change?

**Comment by icbaker** [comment]
The `com.google.android.exoplayer2` project is now deprecated. We are not accepting any new issues in this project. Please file your issue in the `androidx.media3` GitHub project instead: https://github.com/androidx/media/issues
