### ISSUE TITLE
How can I get the exoplayer AudioSessionId?Help!!!!

### ISSUE THREAD

**Issue by wishes3** [google/ExoPlayer#1138]
It cost a lot of time.I can't get AudioSessionId.

/**
   * This is an unsupported operation.
   * <p>
   * Application of audio effects is dependent on the audio renderer used. When using
   * {@link com.google.android.exoplayer.MediaCodecAudioTrackRenderer}, the recommended approach is
   * to extend the class and override
   * {@link com.google.android.exoplayer.MediaCodecAudioTrackRenderer#onAudioSessionId}.
   *
   * @throws UnsupportedOperationException Always thrown.
   */
  @Override
  public int getAudioSessionId() {
    throw new UnsupportedOperationException();
  }

Help~!,

**Comment by ojw28** [comment]
You can extend `MediaCodecAudioTrackRenderer` and override onAudioSessionId. The ID is passed in right there as the argument, so you don't need to be calling anything from there.
