### ISSUE TITLE
In ExoPlayer, my input stream is pixelated, causing the player to display those pixelations. Instead of showing pixelated frames, I want the player to either freeze on the last frame or display a black screen when pixelation occurs.

### ISSUE THREAD

**Issue by amit12kumardish** [google/ExoPlayer#11400]
### This project is deprecated

- [X] I understand this project is deprecated, that I should file my issue in the [Media3 issue tracker](https://github.com/androidx/media/issues/new/choose) instead of here, and this issue will be closed with no response.

**Comment by amit12kumardish** [comment]
In ExoPlayer, my input stream is pixelated, causing the player to display those pixelations. Instead of showing pixelated frames, I want the player to either freeze on the last frame or display a black screen when pixelation occurs.

**Comment by tonihei** [comment]
The project is deprecated, please file your issue in the Media3 tracker as instructed.
