### ISSUE TITLE
How to import ExoPlayer to Android Studio

### ISSUE THREAD

**Issue by CaoPeng** [google/ExoPlayer#1141]

**Comment by AquilesCanta** [comment]
I think tt is quite straightforward. Have you tried...

* File -> Open
* Navigate to directory containing exoplayer.
* Select exoplayer, and click OK.

It will open multiple projects, one of which is the library itself. Another useful project is the DemoPlayer, which is basically an App that shows the usage of ExoPlayer. Shout if you have any trouble.
