### ISSUE TITLE
m3u8 video without sound not playing in exoplayer

### ISSUE THREAD

**Issue by AlirezaGhanbarinia** [google/ExoPlayer#1144]
I have a m3u8 video file without sound(the video does not have sound) and I am using exoplayer to play my videos. but in this special case exo does not play the video.this is my video link:

[M3U8 Link](http://www.vidanama.com:1935/vidanama/_definst_/channels/201511/1300/smil:50176e1b61b360be59f830a8994d87ee.smil/playlist.m3u8)

Appreciate any help.

**Comment by AquilesCanta** [comment]
The stream declares an Audio stream in both PAT and PMT but never includes any payload. I would suggest either removing the PSI entries or add audio payload. I don't think this kind of transport streams will have support in the near future.
