### ISSUE TITLE
Add support for ogg

### ISSUE THREAD

**Issue by amarkovits** [google/ExoPlayer#1145]
Hy

I'm trying to play a opus stream like this one: http://stream.xrm.fm/xrm-ele.opus but I have 2 issues:

Using FrameworkSampleSource it loads only after 15 seconds (setting the datasource on the MediaExtractor take a lot of time).
Code:
`SampleSource sampleSource = new FrameworkSampleSource(getApplicationContext(), Uri.parse(url), null);`

With the ExtractorSampleSource and WebmExtractor I get ExtractorSampleSource$UnrecognizedInputFormatException
Code:
`ExtractorSampleSource sampleSource = new ExtractorSampleSource(
                Uri.parse(url),
                new DefaultUriDataSource(this, "userAgent"),
                new DefaultAllocator(BUFFER_SEGMENT_SIZE), BUFFER_SEGMENT_SIZE * BUFFER_SEGMENT_COUNT,
                new WebmExtractor());`

In the end I create the trackrenderer like this:

`TrackRenderer audioRenderer = new LibopusAudioTrackRenderer(sampleSource);`

Is there another SampleSource I could use so I don't have the delay from FrameworkSampleSource or an Extractor that works with opus?

Andrei

**Comment by andrewlewis** [comment]
According to [Wikipedia](https://en.wikipedia.org/wiki/Opus_(audio_format)#Containers), .opus files are Ogg containers with Opus payloads. ExtractorSampleSource does not yet have an extractor for Ogg, which is why an UnrecognizedInputFormatException is thrown, but we are working on adding this functionality.

If you have control over the input file, I suggest using WebM instead for now.

**Comment by amarkovits** [comment]
Thank you.

Can you give an estimate when the extractor for Ogg will be ready?

Andrei

**Comment by marcbaechinger** [comment]
This is work in progress and unfortunately we don't have an ETA yet. 
The Opus URL you pasted is a live stream. Are you interested in live stream only?

**Comment by amarkovits** [comment]
I'm interested in live stream and also local files. 

Andrei

**Comment by ojw28** [comment]
@marcbaechinger added work-in-progress Ogg support in 89ce1ccedff72da5c7efc4ee50bfcd2d67e45818. The extractor doesn't yet support seeking, but should work otherwise.

**Comment by ojw28** [comment]
Ogg is seekable as of cd8df78162cddc041f9633caec4de9db4e7450cc, so we can close this.

**Comment by amarkovits** [comment]
Unfortunatly this ogg implementation seems to work only for vorbis in ogg. If I have opus in ogg (like in the example from the first post) it is not working (UnrecognizedInputFormatException)

**Comment by ojw28** [comment]
We'll be pushing Flac in Ogg support very soon. We don't have any immediate plans to support Opus in Ogg; although we do support Opus in other containers, like MKV. I filed #1447 to track Opus in Ogg support.
