### ISSUE TITLE
Problem with migrating to r1.5.3

### ISSUE THREAD

**Issue by Alviere** [google/ExoPlayer#1147]
Hi, everybody!
Currently I'm trying to migrate from `r1.5.2` to `r1.5.3` and I've encountered very unexpected behavior.
When I'm updating version in `build.gradle` file first of all I get such exception:

`Player is not abstract and does not override abstract method onAudioTrackUnderrun(int,long,long) in EventListener`

OK, API has changed, I implement this method in my class, try again and then all classes of package `com.google.android.exoplayer` aren't available, as well as package itself. When I switch back to `r1.5.2` everything seems fine.

Can anybody point me out where to search for solution? Thanks in advance!

**Comment by kientux** [comment]
You should checkout this github repository to see how they implement `Player`.

**Comment by Alviere** [comment]
`Player` is my class that implements all interfaces. And all is well in `r1.5.2`. It's not the case. After syncing gradle with `r1.5.3` `com.google.android.exoplayer` package becomes unavailable and gradle throws a lot of errors such as using methods of ExoPlayer classes which it can't find.

**Comment by ojw28** [comment]
I think whatever IDE you're using is just not doing a good job of telling you what the actual problem is. There are probably a few small specific things, similar to the one you've already fixed, that are broken. What's the first compilation error when you try and build?

**Comment by Alviere** [comment]
I'm using Android Studio.
First error I get listed in first message.

**Comment by ojw28** [comment]
You've fixed the `onAudioTrackUnderrun` error though, right? Please paste the exact error you see in the gradle build output (not just red underlines, or whatever, that the UI might be showing you).

**Comment by Alviere** [comment]
`Error:(132, 44) error: method copyAsAdaptive in class MediaFormat cannot be applied to given types;
required: String
found: no arguments
reason: actual and formal argument lists differ in length`
`Error:(175, 39) error: constructor Variant in class Variant cannot be applied to given types;
required: String,Format
found: int,String,int,<null>,int,int
reason: actual and formal argument lists differ in length`
`Error:(372, 21) error: constructor TsChunk in class TsChunk cannot be applied to given types;
required: DataSource,DataSpec,int,Format,long,long,int,int,HlsExtractorWrapper,byte[],byte[]
found: DataSource,DataSpec,int,Format,long,long,int,HlsExtractorWrapper,byte[],byte[]
reason: actual and formal argument lists differ in length`

And so on.

**Comment by ojw28** [comment]
Right, so some methods/variables have changed and you need to update your code to match the new method signatures. If you click on those errors, I think the IDE will land you somewhere in your own code where you're calling a method whose signature has changed. You'll need to adjust your code to match the new signatures.

**Comment by andreimarinescu** [comment]
@Alviere regarding the fact that the ExoPlayer classes seem to be missing, I've had the same issue when upgrading to a new GMS library yesterday. Before Android Studio is able to complete the first build, the new library signatures seem to not be loaded in the IDE, and you'll get missing symbol messages.

Just focus on the compile errors that Gradle is throwing (specifically the missing or changed methods) and once everything compiles correctly you'll regain the visibility of the library classes.

**Comment by Alviere** [comment]
@andreimarinescu @ojw28 Thanks for the hints! I'll try them as soon as I have time for this.
