### ISSUE TITLE
vpxJNI undefined reference

### ISSUE THREAD

**Issue by thanasuk** [google/ExoPlayer#1148]
i start command ndk-build and I got this error undefined reference when build libvpxJNI.so file 

[x86] SharedLibrary  : libvpxJNI.so
C:/android/exo/extensions/vp9/src/main/jni/vpx_jni.cc:65: error: undefined reference to 'vpx_codec_vp9_dx_algo'
C:/android/exo/extensions/vp9/src/main/jni/vpx_jni.cc:65: error: undefined reference to 'vpx_codec_dec_init_ver'
C:/android/exo/extensions/vp9/src/main/jni/vpx_jni.cc:89: error: undefined reference to 'vpx_codec_decode'
C:/android/exo/extensions/vp9/src/main/jni/vpx_jni.cc:99: error: undefined reference to 'vpx_codec_destroy'
C:/android/exo/extensions/vp9/src/main/jni/vpx_jni.cc:107: error: undefined reference to 'vpx_codec_get_frame'
C:/android/exo/extensions/vp9/src/main/jni/vpx_jni.cc:153: error: undefined reference to 'vpx_codec_version_str'
C:/android/exo/extensions/vp9/src/main/jni/vpx_jni.cc:158: error: undefined reference to 'vpx_codec_error'
collect2.exe: error: ld returned 1 exit status
make.exe: *** [C:/android/exo/extensions/vp9/src/main/obj/local/x86/libvpxJNI.so] Error 1

HELP ME PLEASE.

**Comment by thanasuk** [comment]
I think this is main problem :
process_begin: CreateProcess(NULL, cat ./libvpx_android_configs/x86/libvpx_srcs.txt, ...) failed.

**Comment by ojw28** [comment]
@vigneshvg - Could you comment on this? Thanks!

**Comment by vigneshvg** [comment]
./libvpx_android_configs/x86/libvpx_srcs.txt - this file should be generated by the generate_libvpx_android_configs.sh script. Did you run that? Did you follow the instructions in README.md precisely?

[1] https://github.com/google/ExoPlayer/blob/master/extensions/vp9/src/main/jni/generate_libvpx_android_configs.sh

**Comment by thanasuk** [comment]
im using windows64bit and run genarate bash in CYGWIN
now i know undefine reference appear because libsrc_txt not build with generate bash

this is result when I run this command : 

$ ./generate_libvpx_android_configs.sh c:/android/ndk

/cygdrive/c/android/exo/extensions/vp9/src/main/jni/libvpx_android_configs/armeabi-v7a /cygdrive/c/android/exo/extensions/vp9/src/main/jni

build_android_configs:
configure --target=armv7-android-gcc --sdk-path=c:/android/r6b --enable-neon --enable-neon-asm --disable-examples --disable-docs --enable-realtime-only --disable-vp8  --enable-vp9 --disable-webm-io --disable-vp10 --disable-libyuv --disable-runtime-cpu-detect
  disabling examples
  disabling docs
  enabling realtime_only
  enabling vp8
  disabling vp9
  disabling webm_io
  disabling libyuv
  disabling runtime_cpu_detect
Configuring selected codecs
Configuring for target 'armv7-android-gcc'
  enabling armv7
  enabling media
Unable to invoke compiler: c:/android/ndk/toolchains/arm-linux-androideabi-4.4.3/prebuilt/windows/bin/arm-linux-androideabi-gcc  --sysroot=c:/android/ndk/platforms/android-9/arch-arm

Configuration failed. This could reflect a misconfiguration of your
toolchains, improper options selected, or another problem. If you
don't see any useful error messages above, the next step is to look
at the configure error log file (config.log) to determine what
configure was trying to do when it died.

I think this is main issue: 
** Unable to invoke compiler: c:/android/ndk/toolchains/arm-linux-androideabi-4.4.3/prebuilt/windows/bin/arm-linux-androideabi-gcc  --sysroot=c:/android/ndk/platforms/android-9/arch-arm 

Im using Cygwin64 in windows 10 64bit
now im try to install Virtual Machine ubuntu 32bit for change Environment for generate bash

tellme if have any solution. Thank you very much. :)

**Comment by vigneshvg** [comment]
Do you know if scripts running in cygwin can access paths like c:/blah/blah2 ? Shouldn't you have to translate them to /drive_c/blah/blah2 or some such?

I am not very familiar with cygwin.

**Comment by thanasuk** [comment]
now i can build it successfully with Virtual Machine Linux 32bit.
that make i build armeabi armeabi-v7a x86 (NOT 64bit arch)
I think Environment is a problem.

I think i need to buy some macbook now. LOL

Thank you very much for your support. @ojw28  @vigneshvg
