### ISSUE TITLE
S5 mini: Seeking does not work for SD content only

### ISSUE THREAD

**Issue by nosyjoe** [google/ExoPlayer#1150]
On a S5 mini, I start by playing the first seconds of the "WV:Clear SD (MP4, H264)" video. Then I seek using the seeker, the video is paused but the video never starts playing at the new position ever.

When I do the same with the HD version, "WV:Clear HD (MP4, H264)", seeking works without problem.

As a third test I tried seeking on the adaptive video, "WV:Clear SD & HD (MP4, H264)", which does not work while it's still playing the SD video. once it switches to HD, seeking works.

exoplayer version: both 1.5.3 and current dev head (df7a96a)
Device: Samsung S5 mini SM-G800F
Android Version: 4.4.2

**Comment by nosyjoe** [comment]
update: seeking in sd doesn't work for 240p/800kbps. once the stream switches to 480p/2000kbps seeking is possible

same results for tests with "WV: Secure SD (MP4,H264)"

**Comment by ojw28** [comment]
Sounds pretty much the same as #603 (the power of search ;)). Does the workaround described there work in this case also?

**Comment by ojw28** [comment]
Note. An equivalent and simpler workaround on the dev branch would be to have `MediaCodecTrackRenderer.codecNeedsFlushWorkaround` return true for S5 Mini. Please test locally and see whether that helps.

**Comment by nosyjoe** [comment]
hey ojw28, yup, seems to be a duplicate - I will use the search next time, sorry ;) I'll use the original issue for further comments on the issue
