### ISSUE TITLE
Live Smooth Streaming: Offset to sample data was negative.

### ISSUE THREAD

**Issue by freakk82** [google/ExoPlayer#1152]
Attempting to play a Live Smooth Streaming video with ExoPlayer r1.5.3 on an Android 4.4.2 STB, I am getting the following error:

_com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.ParserException: Offset to sample data was negative._

**Comment by ojw28** [comment]
Would I be correct in thinking this is a sporadic failure, rather than something that happens all of the time?

**Comment by freakk82** [comment]
unfortunately it's happening with all the live streams in the app. Is there a public sample of live smooth streaming I can test to see if it works?

**Comment by ojw28** [comment]
There's a public sample built into the demo app that you can try (and it works as far as I know).

**Comment by freakk82** [comment]
I couldn't find the live smooth streaming sample in the demo app, only the "Super Speed" sample which is not live. The weird thing is that on a very old Exoplayer version, the same stream plays with no such error.

**Comment by ojw28** [comment]
Ah, I didn't spot the live part of your comment. There's an Azure live stream provided by Microsoft, that works fine for me:

```
    new Sample("Azure live",
        "http://b028.wpc.azureedge.net/80B028/SampleStream/49be9c8c-0317-470f-94a2-7472732dc844/"
        + "2cfaa74d-196a-4125-9c22-b84cbe4e9df9.ism",
        Util.TYPE_SS),
```

I also have some private test streams that work fine. Please could you provide a link to an affected stream?

**Comment by ojw28** [comment]
NB - I just updated the link in the response above, so copy it again if you tried within the last minute!

**Comment by freakk82** [comment]
Thanks, the sample you sent plays, but with the stream I have to use it fails this check from extractor/FragmentedMp4Extractor.java at line 695:
``` 
private boolean readSample(ExtractorInput input) throws IOException, InterruptedException {
    if (sampleIndex == 0) {
      int bytesToSkip = (int) (fragmentRun.dataPosition - input.getPosition());
      checkState(bytesToSkip >= 0, "Offset to sample data was negative.");
      input.skipFully(bytesToSkip);
    }
[...]
```
In my case bytesToSkip is always -61, and it throws the error.

**Comment by ojw28** [comment]
That suggests malformed media. There's nothing we can do to assist unless you can provide a test stream.

**Comment by freakk82** [comment]
Since I'm not allowed to publish the live stream url, could you please send me a PM ( ffr3akk@gmail.com )?

**Comment by ojw28** [comment]
Please provide the stream to `dev.exoplayer@gmail.com`. Thanks.

**Comment by ojw28** [comment]
I think the `data_offset` field in the `trun` boxes is set incorrectly in the underlying fragmented mp4 streams. You'll probably need to fix this to get your samples playing in ExoPlayer.

**Comment by freakk82** [comment]
That's quite unfortunate. Given that the same streams are playing on Smart TVs, STBs and an old version of the Exoplayer, an incompatibility with the new Exoplayer is not going to be enough for the content provider to work on the streams.
Thanks for the feedback anyway.

**Comment by ojw28** [comment]
If I've diagnosed this correctly, the only reason the streams worked previously is because we were completely ignoring the data offset. It's likely that some other platforms do this too, but it's essentially incorrect and causes parsing failures for legitimate streams where there exists non-sample data at the beginning of mdat boxes.

As a local workaround, it appears you can simply comment out the block of code where the failure occurs.

**Comment by freakk82** [comment]
Commenting that block the video plays, I wasn't sure of what other side effects it might bring. I will let the content provider know about the issue.
Thank you very much for the explanation.
