### ISSUE TITLE
HEVC playback on Philips 7100 UHD TV

### ISSUE THREAD

**Issue by soringp** [google/ExoPlayer#1153]
Can I do something to fix the playback issues on my tv? 

Here is how it looks like when I try WV DASH: Clear HD (MP4, H265) in ExoPlayer Demo v1.5.3:
https://youtu.be/IPbKoQuvtYs

The UHD sample is worse, image freezes after a few seconds.

The TV has HEVC hardware decode, powered by a Marvell Armada 1500 Pro 4k chipset. 

media_codecs.xml on the TV (running Android TV 5.1) contains this HEVC codec: OMX.marvell.video_decoder.hevc

Thanks

**Comment by soringp** [comment]
I've added the codec name in CodecCounters, populated in MediaCodecTrackRenderer, so I can display codec details on screen. It's using the correct codec, OMX.marvell.video_decoder.hevc.

I cannot do any debug on this TV, or install from unknown sources, but I can publish using Alpha Testing and this way I can get the demo on my TV.

I don't know much about media playback, but I'm willing to try and fix it on my own. 

What can I do?

**Comment by ojw28** [comment]
You should try and contact the device manufacturer in the first instance; it looks like a device specific issue. Although I'm not sure where to do that.

In terms of fixing the issue, what are you actually trying to achieve? You could just use H264 on this device, which probably isn't affected.

**Comment by soringp** [comment]
The decoder is working fine using the TV's media player (I thought maybe it's based on ExoPlayer), and in MX Player, so I'm not sure if Philips can help here. Their support is lacking anyway on their forum, so I don't expect to get help there. 

My goal is to try and make Kodi use this accelerated decoder for UHD videos, and I thought I can learn how to use it with this project. Plex is based on ExoPlayer but it has issues as well, the image freezes.

As a side note, I don't get image for WV DASH: Clear HD (MP4, H264), but H264 works fine with YouTube Dash.

**Comment by ojw28** [comment]
Closing as part of a scrub of old device specific issues.
