### ISSUE TITLE
upgrading from mediaplayer to exoplayer

### ISSUE THREAD

**Issue by alexistkd** [google/ExoPlayer#1154]
Hi i would like to upgrade my app that currently uses to stream shoutcast the native mediaplayer of android.

heres my code: http://pastebin.com/TjNx2pDD

im not sure where to begin, the documentation is not too clear of exoplayer

thank you so much.

**Comment by ojw28** [comment]
There is a demo app in this repository that shows how ExoPlayer can be used in an application. Converting your code is something you'll have to figure out for yourself (or ask on StackOverflow).
