### ISSUE TITLE
Seeking to a previous position in buffer

### ISSUE THREAD

**Issue by Falrach** [google/ExoPlayer#1156]
Hi,

For my use of ExoPlayer it is necessary to seek to a position within +- 500ms of the actual playback position without rebuffering. Since you said in previous question that you don't plan on keeping previous buffer, I tried to implement this functionality by adapting the RollingSampleBuffer.
(I'm using ExtractorRendererBuilder and only play audio via http-stream)

Instead of clearing the data in the dropDownstreamTo() - function, I increment an iterator which is later used in the readData() - function to get the right allocation from the dataQueue:
I use
````
        for(i < iteratorIndex)
            it.next();
````
instead of
````
    dataQueue.peek().
````

And to adjust the infoQueue, I adapted the skipToKeyframeBefore() - function with an additional if-clause:
````
if (timeUs < timesUs[relativeReadIndex])
{
    int searchIndex = relativeWriteIndex;
    while (searchIndex != relativeReadIndex)
    {
        if (timesUs[searchIndex] > timeUs)
        {
            // We've gone too far.
            break;
        }
        if ((flags[searchIndex] & C.SAMPLE_FLAG_SYNC) != 0)
        {
            // We've found a keyframe, and we're still before the seek position.
            sampleCountToKeyframe = sampleCount;
        }
        searchIndex = (searchIndex + 1) % capacity;
        sampleCount++;
    }
    if (sampleCountToKeyframe == -1) return -1;

    queueSize -= (relativeReadIndex - searchIndex);
    relativeReadIndex = relativeReadIndex > relativeWriteIndex ? relativeReadIndex - (relativeWriteIndex + sampleCountToKeyframe) : (relativeWriteIndex + sampleCountToKeyframe) % capacity;
    absoluteReadIndex = relativeReadIndex; // not relevant - is never used by me
    return offsets[relativeReadIndex];
}
````
The else-statement would contain the original code for timeUs > timesUs[relativeReadIndex].
This works so far, I can seek to previous positions.

One problem is, that after some time the totalBytesDropped is bigger than the absolutePosition -> the positionInAllocation is negative. This is probably due to the fact that i never adjust the totalBytesDropped when going a bit backwards. Now I don't know how to get the number of bytes I have to subtract after the seek backwards. Is there a possibility to do so?

And another problem that occurred is that the player is stuck in buffering state after about 50-60 minutes of playback. Now I'm not sure if this has something to do with not clearing the dataQueue or some other buffer limitations?

Thanks in advance!

**Comment by ojw28** [comment]
Sorry, but since this is very much a custom modification, it falls pretty far outside the scope of this issue tracker. I'd suggest asking on StackOverflow, or similar, where someone may be able to help.

**Comment by pellucide** [comment]
@Falrach,
     This is an old post. I stumbled upon it while searching for an implementation of a similar feature. I went ahead and implemented something similar. It can seek to a previous position in Buffer. Let me know if you still need it.

**Comment by kevinskrei** [comment]
@pellucide, I'm looking for something to maintain the buffer a bit behind the current position. Were you able to implement this?

**Comment by pellucide** [comment]
@kevinskrei Yes. It was a while ago that I implemented this. It is on the v1 of Exoplayer. Last time, I checkted it should be easy to port it to V2. Let me know if you need it, I will create a fork
