### ISSUE TITLE
Black screen for couple seconds when using shared elements transition

### ISSUE THREAD

**Issue by Xzan** [google/ExoPlayer#1160]
I don't know if this is the right place to report this issue. If not, please tell me where I can report this.

When I'm starting an activity with a shared element transition :  
```java
ActivityOptionsCompat options = ActivityOptionsCompat.makeSceneTransitionAnimation(this, holder.getVideoThumbnail(), getString(R.string.video_image_transition_name));
Intent intent = new Intent(this, PlayerActivity.class);
ActivityCompat.startActivity(this, intent, options.toBundle());
```

and I start the video (using DemoPlayer from https://github.com/google/ExoPlayer/tree/master/demo), I have a ~2seconds delay before the video is actually displayed even though the audio started. When the video appears, the audio and video are in sync.

If I delay the start of the video of 1500ms, the video and audio start at the same time.

Removing the transition or setting `setZOrderOnTop(true)` on the SurfaceView starts the video at the same time as the audio. Nevertheless, `setZOrderOnTop(true)` prevent my application to show the controls.

Is there something I am missing to fix this problem and use the shared element transition ?

**Comment by ojw28** [comment]
Most likely the player is starting before the surface has been created. You'll probably find that you can fix the problem by making sure `player.setPlayWhenReady(true);` doesn't occur until after `surfaceCreated` is invoked in `PlayerActivity`.

**Comment by Xzan** [comment]
Thank you for your reply, I don't believe it's the case as I set the setPlayWhenReady to true only if the surface is not null. Here is my setVideoURI method :

```java
    public void setVideoURI(Uri uri, boolean shouldStartWhenReady, int position) {
        mUri = uri;
        if (mMediaPlayer != null) {
            mMediaPlayer.release();
        }
        mMediaPlayer = new Player(getRendererBuilder(uri));
        mMediaPlayer.setBackgrounded(false);
        mMediaPlayer.seekTo(position);
        mMediaPlayer.addListener(this);
        mMediaPlayer.setInfoListener(this);
        mController.setMediaPlayer(this);
        mMediaPlayer.addListener(this);
        mMediaPlayer.prepare();
        Surface surface = mPlayer.getHolder().getSurface();
        mMediaPlayer.blockingSetSurface(surface);
        mMediaPlayer.setPlayWhenReady(surface != null && shouldStartWhenReady);
        mPlayPause.setImageResource(R.drawable.ic_pause_large);
        mController.hide();
    }
```

I have no other `setPlayWhenReady` call in my class nor do I call `mMediaPlayer.getPlayControler().start()` to start the video unless there is an action from the user

**Comment by Xzan** [comment]
I finally have had the time to put together a little demo that you can find here :
https://github.com/Xzan/ExoPlayerBug

This was tested on a Nexus 6P with Build MMB29Q and is reproducible every time.
Can you confirm you are experiencing the same behavior ?

**Comment by andrewlewis** [comment]
Using a TextureView instead of a SurfaceView seems to fix the problem in your demo. I think it is likely that the transition animation is not completely compatible with SurfaceView as configured in your app.

Note that TextureView is less efficient than SurfaceView in battery consumption, and video playback may be slightly less smooth.

**Comment by Xzan** [comment]
Thanks for your answer, I'll try and see if this fixes the problem in my main application as a workaround.

Since the TextureView is less efficient and you said the transition wasn't configured in my app, could you give me some leads on how I could configure the transition to play nicely with the SurfaceView ?

**Comment by andrewlewis** [comment]
It looks like the player has the surface and is rendering frames just after the transition, but the view is black despite that. At the moment the video does become visible, `ViewRootImpl: changeCanvasOpacity: opaque=false` is logged; I am not familiar with how transitions work, but SurfaceView is 'special' and I think it is plausible that it is incompatible with translucent activities. On the other hand, this opacity change happens about two seconds after the transition completes, so maybe there is something else going on.

I'd recommend using TextureView, but please update this thread if you investigate further and find a workaround that makes SurfaceView work. Thanks!

**Comment by andrewlewis** [comment]
Adding `surfaceView.setZOrderOnTop(true);` in the player activity's onCreate method actually seems to make this work with SurfaceView. With that change the transition is still not completely smooth, but you might be able to fix that by preparing the player when the transition completes instead of in onResume.

Could you confirm that you see the same behavior?

**Comment by Xzan** [comment]
Thank you very much for your help, I was able to experience the same behavior with `surfaceView.setZOrderOnTop(true)` in my demo app. Nevertheless, I had tried that in my main app before and the problem is that it will hide views that are supposed to be on top.

If you attached the `MediaController` to the `SurfaceView`, it works so I believe that in case you only have a video with its controller, the `setZOrderOnTop(true)` is enough and in case of more complex views, you have to use `TextureView` or you need to attach everything to the `SurfaceView`.

This ticket can be considered closed, thank you.
