### ISSUE TITLE
IllegalState Exception ?

### ISSUE THREAD

**Issue by abhiguru** [google/ExoPlayer#1162]
The videos were verified working before and now getting spurious errors.  
Any pointer on what might have caused this ?

Checked system Load and it avg ~1.5
https://gist.github.com/abhiguru/c9760df62ecfb3423a5a

Also this 
https://gist.github.com/abhiguru/3df5cd9799facb011bae

**Comment by ojw28** [comment]
What does "before" mean and what is "after" in this case?

**Comment by abhiguru** [comment]
Sorry for not being more complete, I had to reinstall my OS, studio etc... I checked out the code from my repo and studio downloaded the libs again and other external dependencies and I ran sample code and started getting this issue. 

Thinking it might be a possible update to the lib that caused it I posted it here. The last time I downloaded /updated the code was in early December which I had been using.

**Comment by ojw28** [comment]
I don't think this is particularly likely to be related to an ExoPlayer change. The second log is just a network timeout (i.e. bad network connectivity or the server not responding quickly enough). The first one looks like the underlying media server is in a bad state on the device.
