### ISSUE TITLE
problem with scrolling elements

### ISSUE THREAD

**Issue by MahdiTaghipour** [google/ExoPlayer#1164]
There is no problem when i use exo player in non scrolling elements. 
The problem occures when i try to use exo in a list view or scroll view. When i play the video and then start scrolling , a black screen appears on other views of the activity, and also some layouts overlap with other views. can anybody help me on this issue ?

**Comment by ojw28** [comment]
Try using TextureView instead of SurfaceView. You'll most likely find that it performs better when subjected to animations like scrolling.
