### ISSUE TITLE
use in fragment

### ISSUE THREAD

**Issue by wu21731** [google/ExoPlayer#1165]
if i hide the fragment which the player depend on , the player is also could see ,how to resolve it?

**Comment by ojw28** [comment]
I'm unsure as to what you're asking here. Please clarify. Thanks!

**Comment by wu21731** [comment]
I have two fragments, A and B. I put a player in fragment A. put baiduMap in fragment B,  then I hide A, and show B, I can see the player in fragment B.

**Comment by ojw28** [comment]
Please try explicitly hiding the SurfaceView itself. You could also try using TextureView, which will likely behave more as you expect.
