### ISSUE TITLE
Radio stream recording

### ISSUE THREAD

**Issue by kaltindas** [google/ExoPlayer#1167]
Hi, 

how to record the radio stream? is exoplayer supports recording feature?

**Comment by ojw28** [comment]
We don't support recording.

**Comment by kaltindas** [comment]
@ojw28 thank you for your answer. Are you planning in future to support this feature? Is there any possibility to modify your library to save/record bytes from inputstream of your exoplayer?

**Comment by dreich** [comment]
I need this feature too.

**Comment by ojw28** [comment]
Plans can change, but as of now we have no plan to support this feature.

**Comment by dreich** [comment]
ojw28, you may not implement directly this feature, but at least make API more accessible and convenient for developers to implement by themselves.

For example, some guy at
[http://stackoverflow.com/questions/40579478/android-exoplayer-live-audio-stream-vu-meter-audio-visualisation-and-recording](http://stackoverflow.com/questions/40579478/android-exoplayer-live-audio-stream-vu-meter-audio-visualisation-and-recording)
wrote:

>  I downgraded the Exoplayer to 1.5.3 as I couldn't figure out how to access the MediaCodecAudioTrackRenderer in the v2.
I extended the MediaCodecAudioTrackRenderer class as it has a processBuffer function I can override.

**Comment by ojw28** [comment]
V2 has the [same method](https://github.com/google/ExoPlayer/blob/r2.1.1/library/src/main/java/com/google/android/exoplayer2/audio/MediaCodecAudioRenderer.java#L312) and it looks to me like you can still override it, so I'm not sure the StackOverflow issue is particularly relevant.

Developers are free to fork part or all of ExoPlayer to implement what they need, where we don't provide a feature directly. Note that adding hooks to allow a feature to be conveniently developed as an extension is in itself a feature. Note also that a developer is free to propose a pull request that adds such hooks to the project.

**Comment by dreich** [comment]
Please, tell, where in ExoPlayer I can hook and capture input buffer (for mp3 stream) and write it to file?

**Comment by webserveis** [comment]
It would be interesting that function to give the possibility to listen seconds behind in a streaming radio, if you want to listen again heard.
