### ISSUE TITLE
Set Aspect Ratio of Frame

### ISSUE THREAD

**Issue by sweatapp** [google/ExoPlayer#1168]
I am having an issue. i am streaming a video from my server where the URL is at passedWorkoutObject.workoutMediaURL. The video plays fine, but I need to scale the frame to the right aspect ratio. onVideoSizeChanged is not called with this code below. How do I get the aspect ratio of the frame so I can scale my frame?

           player = ExoPlayer.Factory.newInstance(2);

            Allocator allocator = new DefaultAllocator(BUFFER_SEGMENT_SIZE);
            DataSource dataSource = new DefaultUriDataSource(this, null, versionName);

            MediaPresentationDescriptionParser parser = new MediaPresentationDescriptionParser();
            UriDataSource manifestDataSource = new DefaultUriDataSource(this, versionName);
            ManifestFetcher<MediaPresentationDescription> manifestFetcher = new ManifestFetcher<>(passedWorkoutObject.workoutMediaURL, manifestDataSource, parser);
            final DefaultBandwidthMeter bandwidthMeter = new DefaultBandwidthMeter();

            ExtractorSampleSource sampleSource = new ExtractorSampleSource(
            Uri.parse(passedWorkoutObject.workoutMediaURL), dataSource, allocator, BUFFER_SEGMENT_COUNT * BUFFER_SEGMENT_SIZE);

            MediaCodecVideoTrackRenderer videoRenderer = new MediaCodecVideoTrackRenderer(
                    this, sampleSource, MediaCodec.VIDEO_SCALING_MODE_SCALE_TO_FIT, 100, null, new MediaCodecVideoTrackRenderer.EventListener() {
                @Override
                public void onDroppedFrames(int count, long elapsed) {

                }

                @Override
                public void onVideoSizeChanged(int width, int height, int unappliedRotationDegrees, float pixelWidthHeightRatio) {
                    videoFrame.setAspectRatio(
                            height == 0 ? 1 : (width * pixelWidthHeightRatio) / height);
                }

                @Override
                public void onDrawnToSurface(Surface surface) {

                }

                @Override
                public void onDecoderInitializationError(MediaCodecTrackRenderer.DecoderInitializationException e) {

                }

                @Override
                public void onCryptoError(MediaCodec.CryptoException e) {

                }

                @Override
                public void onDecoderInitialized(String decoderName, long elapsedRealtimeMs, long initializationDurationMs) {

                }
            }, 100);

            MediaCodecAudioTrackRenderer audioRenderer = new MediaCodecAudioTrackRenderer(sampleSource);
            player.prepare(videoRenderer, audioRenderer);

            player.sendMessage(videoRenderer, MediaCodecVideoTrackRenderer.MSG_SET_SURFACE, surface);

            player.setPlayWhenReady(true);
            control = new PlayerControl(player);

**Comment by ojw28** [comment]
If you want your listener to be invoked then you need to pass a something other than null as the value of `eventHandler` in the `MediaCodecVideoTrackRenderer` constructor.

**Comment by sweatapp** [comment]
worked like a charm, thanks
The documentation should really be better on all of this.

**Comment by ojw28** [comment]
Whilst I agree in general that we need more detailed documentation, the Javadoc seems pretty clear in this specific case:

```
eventHandler - A handler to use when delivering events to eventListener. May be null if delivery of events is not required.
eventListener - A listener of events. May be null if delivery of events is not required.
```

Choosing to pass null implies that you're not interested in having your listener receive events.
