### ISSUE TITLE
Samsung Galaxy S4 Hangs, blurs out and Stucks on playing Widevine content.

### ISSUE THREAD

**Issue by Amritpal33** [google/ExoPlayer#1170]
I am using Dash with Widevine which is working fine in almost all supported devices while this weird issue is coming in Samsung s4. On playing Video for few minutes (changing the orientation of device couple times), the devices hangs, the screen got blurs out.

The device stucks and unless we plug its battery out, it does not works.

This issue was not Happening with HLS based Streaming.

I tested it on Sample app as well as My Plication.Issue is observed in both the cases.

**Comment by ojw28** [comment]
Let's use #1048 to track S4 Widevine issues.
