### ISSUE TITLE
DASH video track quality is set to max by default

### ISSUE THREAD

**Issue by j-garin** [google/ExoPlayer#1172]
hello.

I am developing a player app using the demo app as reference and bumped into this issue. When launching player activity, selected video track is 1080p, not auto. and video tracks are listed in the following order:
1080p
auto
720p
480p
What can be the cause? Any fix for this?

**Comment by ojw28** [comment]
The only thing I can think of that would cause this is if your DASH manifest has the 1080p representation in its own adaptation set at the top, and then a second adaptation set containing 720p/480p. Is that correct, and is there a reason why all three aren't in the same adaptation set?

**Comment by j-garin** [comment]
Indeed there are 2 adaptation sets in the mpd file, because there are 2 codecs. What is the good way to handle this and have 'auto' at track[0]?

**Comment by ojw28** [comment]
What are the two codecs, out of interest? Is the 1080p representation H265, or something like that?

**Comment by j-garin** [comment]
one is H.285 (for 1080p) and the other is H.264

**Comment by ojw28** [comment]
It's typically not possible to seamlessly adapt between different codecs. The auto track generated in this case is 720p and 480p only, and so it's pretty ambiguous whether the player should default to the H265 stream or to the two H264 streams (unless you have something in your manifest that indicates this somehow).

I think from the delivery point of view, it would be more normal to have H265 streams in 1080p, 720p and 480p, and then H264 streams in 720p and 480p. You'd then get an auto H265 track that can switch between the three H265 representations and would be enabled by default on devices with H265 decoders, and a separate auto H264 track, which would be the default on devices without an H265 decoder.

**Comment by j-garin** [comment]
that worked. thank you.
also i am experiencing difficulties with audio track selection. playback fails to incompatible track selection. is there a way to select audio track that is supported by the device automatically?

**Comment by ojw28** [comment]
ExoPlayer should already select a compatible audio track. What tracks do you have in your manifest, and on what device, and what selection are you seeing?

**Comment by j-garin** [comment]
It was the issue in mpd file. Sorry to have bothered you and thank you for your help.

**Comment by jeprojects** [comment]
@ojw28 This is a great help. One question though, with the multiple resolutions (1080p, 720p, 480p) will mpeg dash (and exoplayer) change between them all seamlessly without buffering? 

Or does this only happen when you have multiple bitrates for the same resolution (example: 1080p 10mbit, 5mbit, 4mbit)

**Comment by ojw28** [comment]
Yes, it's possible to switch resolution. On Jellybean and some KitKat devices there might be a slight (~50ms) freeze in the video across the resolution switch, but nothing worse than that. On newer devices it should be completely seamless. There's definitely no buffering involved.
