### ISSUE TITLE
StreamingDrmSessionManager and Handlers

### ISSUE THREAD

**Issue by ChernyshovYuriy** [google/ExoPlayer#1173]
There is the class:
https://github.com/google/ExoPlayer/blob/master/library/src/main/java/com/google/android/exoplayer/drm/StreamingDrmSessionManager.java

And there are Handlers as its members: 
- MediaDrmHandler mediaDrmHandler
- PostResponseHandler postResponseHandler

It is not clear what type of Looper does they accept in their constructors. This cause the question related to "close()" method:
mediaDrmHandler.removeCallbacksAndMessages(null);
postResponseHandler.removeCallbacksAndMessages(null);

If these Handlers owns Main Looper then there is a bug, Because application that use ExoPlayer use Main Looper as well to post its own Messages. In this case - all the messages in the queue will be delated.

Is it possible to specify what kind of Looper is there and if it is Main one - please correct "close()" method.

**Comment by ojw28** [comment]
The documentation not only documents which looper you should pass, but also exactly where you should get it from? See below.

```
   * @param playbackLooper The looper associated with the media playback thread. Should usually be
   *     obtained using {@link com.google.android.exoplayer.ExoPlayer#getPlaybackLooper()}.
```

**Comment by ChernyshovYuriy** [comment]
My fault, sorry!
Good to see quick and reliable response though.
