### ISSUE TITLE
Switch to another HLS stream too slow on LIVE

### ISSUE THREAD

**Issue by rajyvan** [google/ExoPlayer#1174]
On live : 
The first launch of a HLS stream is very smooth. 
I let the seek position go far enough (delta ~2min).
Then I switch to another stream, so prepare and play are called. 
It takes a long time to player to show the new stream (from 1min to ~10 min sometimes).
I'm not sure but a think, in HLSChunkSource > getChunkOperation > from line 368 : 

```
 int chunkIndex = chunkMediaSequence - mediaPlaylist.mediaSequence;
        if (chunkIndex >= mediaPlaylist.segments.size()) {
            if (!mediaPlaylist.live) {
                out.endOfStream = true;
            } else if (shouldRerequestLiveMediaPlaylist(nextVariantIndex)) {
                out.chunk = newMediaPlaylistChunk(nextVariantIndex);
            }
            return;
        }
```

The condition is always verified so return is called and it makes a loop.

**Comment by ojw28** [comment]
Yup, I have a fix for this that will be merged today.

**Comment by rajyvan** [comment]
Thanks a lot ;)

**Comment by ojw28** [comment]
Should be fixed by https://github.com/google/ExoPlayer/commit/d804446b343401f6487f62777c9a23173f79309b
