### ISSUE TITLE
How can Istop displaying a video during play back?

### ISSUE THREAD

**Issue by joshimaulik** [google/ExoPlayer#1179]
Hello,

I have specific requirement to stop rendering the video during the play back of DASH streaming using EXO Payer. 
My use case is like this, there is a button, "Stop Video", on a player activity along with "Logging" button. So when user clicks on that button it should stop rendering the video and only Audio should be render. I tried to implement it, and what I did is , on "Stop Video" button I called the releseplayer() and then call prepareplayer(true) method and during this method I passed a variable called "StopRenderVideo" to AsyncRendererBuilder class. and if that variable is true then only I am rendering the video and if it's false it will not render video. Like this:

if(stopRenderVideo)
        renderers[DemoPlayer.TYPE_VIDEO] = videoRenderer; // comment this line to render Audio only*/

Now, if I did this, it stops the video and renders only Audio but the last frame of the video freezes on the tablet, which does not look good. Instead of that freeze frame I want to show blank screen. Please let me know what else I need to do to achieve this.

Thanks

**Comment by ojw28** [comment]
You don't need to mess around with `releasePlayer` and `preparePlayer`. Just call `setSelectedTrack(DemoPlayer.TYPE_VIDEO, DemoPlayer.TRACK_DISABLED)`. You'll find that you get a far smoother transition that way, and the player wont need to re-buffer the audio from scratch.

For removing the last frame, you should just be setting the surface view to that it's no longer visible. Something like `surfaceView.setVisibility(View.INVISIBLE)`. Although this is more just managing your application UI, and is out of the scope of this issue tracker.
