### ISSUE TITLE
Android HLS Streaming Video is Blur On Few Samsung Mobiles

### ISSUE THREAD

**Issue by atulbhardwaj090** [google/ExoPlayer#1184]
I am trying to play a HLS Streaming url(having .m3u8 extension) using Android default Media Player, but the video is blur on Samsung mobiles but on other mobiles (Sony, Motorola, Htc) its working fine.

sorry had to delete the url, production issues... :)

Can you please suggest where I have to change, app side or server side?

**Comment by ojw28** [comment]
This is very vague. Please see [here](https://google.github.io/ExoPlayer/2015/10/01/reporting-issues.html) for the kind of information we need to be able to diagnose this kind of issue.

**Comment by ojw28** [comment]
Closing due to insufficient information.
