### ISSUE TITLE
Embedded WebVtt doesn't work for DASH playbacks in 1.5.4

### ISSUE THREAD

**Issue by drjunja86** [google/ExoPlayer#1185]
I'm trying to play Dash video with embedded WebVtt subtitles. As I understood, it should be possible to do with ExoPlayer version 1.5.4. However, I cannot get subtitles working with my reference video: http://media.axprod.net/TestVectors/v6-Clear/Manifest_1080p.mpd
There is no errors or any other useful information in logcat. Player just return 0 tracks count for TEXT type.

Is my reference video problem or is it player bug? Is there any other reference video with embedded WebVtt subtitles?

**Comment by ojw28** [comment]
All of the underlying work necessary to enable this has been done, but I think things haven't quite been wired together yet (probably just an oversight on our part :)). @AquilesCanta to take a look.

**Comment by AquilesCanta** [comment]
It is indeed a bug. The fix will be avaialble soon, I believe.

**Comment by drjunja86** [comment]
Ok, good, will wait for fix. Thank you.
