### ISSUE TITLE
Error Message on playing local ts file

### ISSUE THREAD

**Issue by felixyangtw** [google/ExoPlayer#1187]
Hi all:
   I download the exoplayer source and build and run it. I use it to play local ts file (path is /mnt/sdcard)
It will show the following message when I quit playing. I test it on two devices and they show the same message too. Please help to clarify and solve. Thanks.
device 1, nexus 9  android 6.0.1
device 2, samsung s6, android 5.1.1

error message:
01-26 11:40:47.230 12065 12404 W MessageQueue: Handler (com.google.android.exoplayer.upstream.Loader$LoadTask) {7d68e29} sending message to a Handler on a dead thread
01-26 11:40:47.230 12065 12404 W MessageQueue: java.lang.IllegalStateException: Handler (com.google.android.exoplayer.upstream.Loader$LoadTask) {7d68e29} sending message to a Handler on a dead thread
01-26 11:40:47.230 12065 12404 W MessageQueue: 	at android.os.MessageQueue.enqueueMessage(MessageQueue.java:543)
01-26 11:40:47.230 12065 12404 W MessageQueue: 	at android.os.Handler.enqueueMessage(Handler.java:631)
01-26 11:40:47.230 12065 12404 W MessageQueue: 	at android.os.Handler.sendMessageAtTime(Handler.java:600)
01-26 11:40:47.230 12065 12404 W MessageQueue: 	at android.os.Handler.sendMessageDelayed(Handler.java:570)
01-26 11:40:47.230 12065 12404 W MessageQueue: 	at android.os.Handler.sendEmptyMessageDelayed(Handler.java:534)
01-26 11:40:47.230 12065 12404 W MessageQueue: 	at android.os.Handler.sendEmptyMessage(Handler.java:519)
01-26 11:40:47.230 12065 12404 W MessageQueue: 	at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:212)
01-26 11:40:47.230 12065 12404 W MessageQueue: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
01-26 11:40:47.230 12065 12404 W MessageQueue: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
01-26 11:40:47.230 12065 12404 W MessageQueue: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
01-26 11:40:47.230 12065 12404 W MessageQueue: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
01-26 11:40:47.230 12065 12404 W MessageQueue: 	at java.lang.Thread.run(Thread.java:818)

**Comment by ojw28** [comment]
Please see #426 (it's a good idea to search existing issues before filing a new one, also!). Thanks!
