### ISSUE TITLE
video stalls when switching from one representation to another in mpeg dash 

### ISSUE THREAD

**Issue by pandukumar** [google/ExoPlayer#1188]
Hi,
  I am experimenting on mpeg-dash streaming, I am using mp4box to generate my content.
when i generate with 2 sec segment duration it plays smooth on Exoplayer. when i generate the content with >2 sec segment duration then playback stalls while switching the representation from low resolution to high resolution.
  And also if i have audio in multiple representations ExoPlayer always choose the first one. and its not changing automatically.

Any advise?
will share my content through mail.
thanks in advance

**Comment by ojw28** [comment]
- Longer segments should work fine, provided the configured buffer is large enough. Perhaps it's not in this case, if you're using a very high bitrate.
- We don't support adaptive audio, although the application can select the representation that it prefers.

**Comment by ojw28** [comment]
Your streams don't work from my location ("The Amazon CloudFront distribution is configured to block access from your country."). Please could you provide ones that aren't geo-restricted? Thanks!

**Comment by pandukumar** [comment]
Thanks for your reply.
i have shared the streams again.

**Comment by pandukumar** [comment]
any update??
waiting for your reply.

**Comment by ojw28** [comment]
The segments in the media aren't aligned properly, so this is a content issue. Below are the segment start and end times for the formats in your 10s manifest. Note that the representations with ids 10 and 8 have a significantly shorter first segments (8s) than the others (10s), which means that the segments are misaligned throughout by around 2s. Adaptation will be seamless between formats 8 and 10, and separately between formats 6, 4, 3, 2 and 1. But when switching between these groups a discontinuity is expected due to the misalignment.

The solution is to fix the content, I'm afraid!

```
Format 10
21000	8029011
8029011	18039022
18039022	28049022
28049022	38059033
38059033	48069044
48069044	58079055
58079055	68089066
68089066	78099077
78099077	88109088
88109088	98119100
98119100	108129111
108129111	118139122
118139122	128149122
128149122	138159133
138159133	148169144
148169144	155509822

Format 8
21000	8029011
8029011	18039022
18039022	28049022
28049022	38059033
38059033	48069044
48069044	58079055
58079055	68089066
68089066	78099077
78099077	88109088
88109088	98119100
98119100	108129111
108129111	118139122
118139122	128149122
128149122	138159133
138159133	148169144
148169144	155509822

Format 6
21000	10021000
10021000	20021000
20021000	30021000
30021000	40021000
40021000	50021000
50021000	60021000
60021000	70021000
70021000	80021000
80021000	90021000
90021000	100021000
100021000	110021000
110021000	120021000
120021000	130021000
130021000	140021000
140021000	150021000
150021000	155562666

Format 4
21000	10021000
10021000	20021000
20021000	30021000
30021000	40021000
40021000	50021000
50021000	60021000
60021000	70021000
70021000	80021000
80021000	90021000
90021000	100021000
100021000	110021000
110021000	120021000
120021000	130021000
130021000	140021000
140021000	150021000
150021000	155576555

Format 3
84000	10084000
10084000	20084000
20084000	30084000
30084000	40084000
40084000	50084000
50084000	60084000
60084000	70084000
70084000	80084000
80084000	90084000
90084000	100084000
100084000	110084000
110084000	120084000
120084000	130084000
130084000	140084000
140084000	150084000
150084000	155667333

Format 2
189000	10189000
10189000	20189000
20189000	30189000
30189000	40189000
40189000	50189000
50189000	60189000
60189000	70189000
70189000	80189000
80189000	90189000
90189000	100189000
100189000	110189000
110189000	120189000
120189000	130189000
130189000	140189000
140189000	150189000
150189000	155772333

Format 1
189000	10189000
10189000	20189000
20189000	30189000
30189000	40189000
40189000	50189000
50189000	60189000
60189000	70189000
70189000	80189000
80189000	90189000
90189000	100189000
100189000	110189000
110189000	120189000
120189000	130189000
130189000	140189000
140189000	150189000
150189000	155939000
```

**Comment by pandukumar** [comment]
Thanks for your response.
i would like to know how to get the segments start time and end time? is there any tool?
it will be helpful for me as i would be experimenting on generating dash content.
Thanks again.

**Comment by ojw28** [comment]
I manually added some logging to the ChunkIndex constructor in ExoPlayer, and then used the demo app to select different video formats. There's probably a better way though; I imagine tools exist :).
