### ISSUE TITLE
Green screen buffering Widevine protected Dash video

### ISSUE THREAD

**Issue by tajoumal** [google/ExoPlayer#1189]
Hey ExoTeam, 

We are using our own Widevine/Dash stream, that seems to work well on other devices. I cannot give you more details about the encoding unfortunately.

Behaviour: Whenever the video is changing bitrate to adapt to network, the screen turns green.

Expected behaviour: The player adapts to the new bitrate without showing a green screen.
 
ExoPlayer v1.5.4
Decoder OMX.SEC.avc.sw.dec
Samsung Galaxy S6 Edge+ device
Android 5.1.1

What I know about the stream: 
2 Seconds fragments
MP4 
360x270 @250kbps @ 25fps
360x270 @400kbps @ 25fps
480x360 @700kbps @ 25fps
720x540 @1000kbps @ 25fps

**Comment by ojw28** [comment]
Closing due to insufficient information. Please open a new issue containing complete information if you wish us to investigate.
