### ISSUE TITLE
Using Exoplayer's HlsRenderer with External Webvtt URL Issue (No MediaPlayer Progress, Caption is out of Sync)

### ISSUE THREAD

**Issue by ofuwape** [google/ExoPlayer#1193]
__ExoPlayer Version:__ 1.5.4

__Testing Devices:__
Samsung GT-I-9300I Android 4.3 API 18 
HTC Nexus 9 Android 6.0.1, API 23

__Links__
* __HLS:__ http://s3.amazonaws.com/curiosity-club/testing/hls_subs3/play.m3u8
* __VTT File Link:__ http://s3.amazonaws.com/curiosity-club/testing/hls_subs3/abc_enigmaman.vtt

__Issues__
* Player skips the first line of the vtt file, which throws off the sync between the sound and captions.
* MediaController only plays and pauses. Fast-forward, rewind seek buttons start the videos from the beginning. Also, there's no progress tracking due to the textRenderer setup. Works well without my textRenderer setup.

__Code Excerpt from HlsRendererBuilder__
```
...
DataSource textDataSource = new DefaultUriDataSource(context, bandwidthMeter, userAgent);
MediaFormat mediaFormat = MediaFormat.createTextFormat("id", MimeTypes.TEXT_VTT, MediaFormat.NO_VALUE,
                            C.MATCH_LONGEST_US, "en");
SingleSampleSource textSampleSource = new SingleSampleSource(Uri.parse(THE_WEBVTT_URL), textDataSource, mediaFormat);
TrackRenderer textRenderer = new TextTrackRenderer(textSampleSource, player, mainHandler.getLooper());

TrackRenderer[] renderers = new TrackRenderer[DemoPlayer.RENDERER_COUNT];
renderers[DemoPlayer.TYPE_VIDEO] = videoRenderer;
renderers[DemoPlayer.TYPE_AUDIO] = audioRenderer;
renderers[DemoPlayer.TYPE_METADATA] = id3Renderer;
renderers[DemoPlayer.TYPE_TEXT] = textRenderer;
player.onRenderers(renderers, bandwidthMeter);
...
```

#### I get the same issues on both devices and I have tweaked the MediaFormat object but still get the same result. I look forward to hearing from you. Thanks for the support in advance!

**Comment by ojw28** [comment]
The player doesn't skip the "mysterious music" caption for me. The captions are a little early, but they appear to be displayed at the times listed in the caption file itself, so that feels like an issue with the content to me?

There is a separate issue where seeking backward isn't working with this setup in the demo app, which I'll fix, but otherwise everything looks fine from the player's point of view.

**Comment by ofuwape** [comment]
@ojw28  Thanks for the quick and detailed response. I'll try other files to confirm your findings.
