### ISSUE TITLE
Reloading of segments during HLS playback

### ISSUE THREAD

**Issue by mgp** [google/ExoPlayer#1194]
Hello,

We use ExoPlayer 1.5.3 for HLS playback. We noticed that, after waiting for a stream to buffer, if we put the device in airplane mode and then attempt to seek, the operation never completes.

To help debug, we changed our `DataSource` implementation to [`OkHttpDataSource`](https://github.com/google/ExoPlayer/blob/master/extensions/okhttp/src/main/java/com/google/android/exoplayer/ext/okhttp/OkHttpDataSource.java). We are able to monitor the requests by its backing `OkHttpClient` instance using [Stetho](http://facebook.github.io/stetho/). What we noticed is that when the video loads for the first time (on a high-bandwidth connection), all segments are aggressively loaded:

https://slack-files.com/T029GG40X-F0KFLNR24-9c2fd749a1

This appears to coincide with the apparent buffering. But upon seeking to any position, all segments at and after the seek time are reloaded. From one seek operation:

https://slack-files.com/T029GG40X-F0KFK7KJ5-14e8d968c6

From another seek operation:

https://slack-files.com/T029GG40X-F0KFDJ5PE-191fee1658

This was surprising to us. We assumed that the "buffered" segments were somehow being cached, likely on disk. A cursory search revealed the [`Cache`](https://github.com/google/ExoPlayer/blob/master/library/src/main/java/com/google/android/exoplayer/upstream/cache/Cache.java) interface, but only an in-memory implementation and no found uses.

Our solution right now is to continue using the `OkHttpDataSource` implementation, and to configure its backing `OkHttpClient` instance with an on-disk LRU cache. However, from best we can understand, this cache is not particularly helpful for longer videos where the sum of all segment sizes exceeds the on-disk cache size.

For example, consider a hypothetical video with 100 segments, each of size 1MB. Say the on-disk cache is 50MB, and can therefore hold at most 50 segments. Because ExoPlayer attempts to load all segments upon initial playback, and the cache is LRU, then after all segments are loaded the cache will hold segments 51-100 -- even though at this time playback may only be on segment 10 (because the speed at which segments are loaded far exceeds the playback speed). Therefore if the user pauses the video and rewinds it 10 seconds to review some concept, that segment is a cache miss, and the reloading sequence in the images above happens.

Do you have any advice for handling large videos like this? Is the reloading behavior in the images above an ExoPlayer bug? If not, is there any way to control the preloading behavior of segments so that it is not so aggressive? This would lead to a higher likelihood that the segments near the current playback time are in the on-disk cache, and so the user rewinding the video 10 seconds or skipping ahead a bit will result in a cache hit.

The HLS stream in the above screenshots is http://fastly.kastatic.org/KA-youtube-converted/PEeUTQ0Gri8.m3u8/PEeUTQ0Gri8.m3u8.

Thanks!

**Comment by brian-chu-twc** [comment]
I have other observation,  given a big cache (say 100M), I can see it does not re-download the segments. However, when doing a seek to the beginning, it will re-download the first segment no matter what.

running on 1.5.4

**Comment by AquilesCanta** [comment]
I hadn't seen this. I will have a look.

**Comment by ojw28** [comment]
ExoPlayer does not cache to disk. Whilst it's beneficial for an individual application (in isolation) to cache media to disk, I'm not convinced that it's good for Android device health if many applications all start doing this by default as a result of using ExoPlayer. Hence our decision not to support this as a conveniently built in feature at the current time.

It's not true to say that ExoPlayer aggressively loads all segments into memory. ExoPlayer operates within a specified memory budget that the application controls. For HLS playbacks in the demo application, the memory budget is specified [here](https://github.com/google/ExoPlayer/blob/master/demo/src/main/java/com/google/android/exoplayer/demo/player/HlsRendererBuilder.java#L57)

**Comment by AquilesCanta** [comment]
I will close this issue as things have changed quite a lot in this matter, particularly in v2. If this issue persists in the new versions, please file a fresh one.
