### ISSUE TITLE
Playback of video with PSSH v1 box fails

### ISSUE THREAD

**Issue by sandersaares** [google/ExoPlayer#1195]
You will find a video titled [v6-MultiDRM-GenericEmePssh](https://github.com/Axinom/dash-test-vectors) among our test vectors. This video contains a v1 PSSH box that includes the [generic EME signaling for Common Encryption](https://w3c.github.io/encrypted-media/cenc-format.html#common-system), in addition to the DRM-technology-specific PSSH boxes.

The PSSH v1 box is present in both the manifest and the initialization segments.

This video fails to play with ExoPlayer 1.5.0. The following lines appear in the log:

    01-19 16:08:10.314    1624-1624/? E/BasePlayerController? onRendererInitializationError: Invalid pssh atom in cenc:pssh element
    01-19 16:08:10.314    1624-1624/? I/writeToLog? Adding text to log: BasePlayerController - player error: onRendererInitializationError: Invalid pssh atom in cenc:pssh element
    01-19 16:08:10.319    1624-1624/? E/BasePlayerController? ErrorInvalid pssh atom in cenc:pssh element
    01-19 16:08:10.319    1624-1624/? I/writeToLog? Adding text to log: BasePlayerController - player error: ErrorInvalid pssh atom in cenc:pssh element

You can compare against the v6-MultiDRM video, which differs only by the presence of this PSSH box and plays fine in ExoPlayer. Note that you need to provide a custom HTTP header in order to retrieve a license, as described on the test vectors page.

**Comment by ojw28** [comment]
In the short term we should probably just skip pssh boxes that have version > 0.

**Comment by ojw28** [comment]
Correction. Parse version 1, ignore version 2+.
