### ISSUE TITLE
Extensions on JCenter or MavenCentral

### ISSUE THREAD

**Issue by panzerdev** [google/ExoPlayer#1196]
After finding the `extensions` for OkHttp and others I wanted to import them into my project via gradle 

`compile 'com.google.android.exoplayer:exoplayer.extension:rX.X.X'`

but on JCenter I can't see anything deployed http://jcenter.bintray.com/com/google/android/exoplayer/

Are there plans to publish the extension as well?

**Comment by ojw28** [comment]
Dupe of https://github.com/google/ExoPlayer/issues/1434.
