### ISSUE TITLE
make selected track format available for adaptive stream

### ISSUE THREAD

**Issue by bartsidee** [google/ExoPlayer#1199]
For debugging purposes we would like to view the selected video track meta information of an adaptive stream.

We are able to request the video track using:

    index = player.getSelectedTrack(player.TYPE_VIDEO)
    format = player.getTrackFormat(player.TYPE_VIDEO, index)

Unfortunately the MediaFormat object returned is a nearly empty object in the case of an adaptive stream.

This seems to be expected behaviour in the current implementation as the track info is explicitly copied using a the "copyAsAdaptive" method to only include limited info:
https://github.com/google/ExoPlayer/blob/master/library/src/main/java/com/google/android/exoplayer/smoothstreaming/SmoothStreamingChunkSource.java#L373
https://github.com/google/ExoPlayer/blob/f11c2e113f0a4df35461296905a3c3b461cab6a9/library/src/main/java/com/google/android/exoplayer/dash/DashChunkSource.java#L582

It would be great enhancement feature to have to have a more actual representation of the currently selected track for adaptive streams though.

**Comment by ojw28** [comment]
This is already possible by listening to ChunkSampleSource or HlsSampleSource. In the demo app, these events end up in `EventLogger.onVideoFormatEnabled`, where they're printed to the log.

Having said that, we might do more to allow the current selection to be queried more easily (to be determined).

**Comment by bartsidee** [comment]
Thanks you for the reference, we will use the infoListener for now.

**Comment by ojw28** [comment]
In the [2.x.x experimental branch](https://github.com/google/ExoPlayer/tree/dev-2.X.X-experimental) there's a new `SimpleExoPlayer` that provides a `getVideoFormat` convenience method, along with `DebugListener.onVideoFormatChanged` for listening to changes. When using `ExoPlayer` directly, `VideoTrackRendererEventListener.onVideoInputFormatChanged` can be used to listen to changes in the format of video being consumed by a renderer. So all in all, 2.x.x should address this pretty comprehensively.
