### ISSUE TITLE
 Absence of default format in m3u8 video manifest causes video to be unreadable.

### ISSUE THREAD

**Issue by Dayzen** [google/ExoPlayer#1200]
Hello,

Using Exo player, I'm trying to play an m3u8-file with the following manifest :

```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=425000,RESOLUTION=432x240,NAME="240p"
http://example.com/-w240.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=650000,RESOLUTION=640x360,NAME="360p"
http://example.com/-w360.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1100000,RESOLUTION=854x480,NAME="480p"
http://example.com/-w480.m3u8
```

I've figured out that the problem comes from the selectVideoFormats() method in the VideoFormatSelectorUtil class, as it returns an ampty int[]. This is because isFormatPlayable() returns false on certain devices, which is supposed to be returned when the format is undecodable.

```
//Assuming that the media is H.264
if (format.width * format.height > maxDecodableFrameSize) {
  // Filtering stream that device cannot play
  return false;
}
```

I've overcome this issue on ExoPlayer 1.5.3 by editing the code as following :

```
if (isFormatPlayable(format, allowedContainerMimeTypes, filterHdFormats,
                 maxDecodableFrameSize) || i == 0)
```

where i == 0 ensure to get a default format

To do so I had to create my own VideoFormatSelectorUtil class (because initial VideoFormatSelectorUtil class is locked) , I was allowed to do so because it was directly called by hlsRenderBuilder. But since update 1.5.4, it is called from other locked class (DefaultHlsTrackSelector).  

It appears to be not easy to maintain such a trick through updates, I would know what do you suggest in such case. Can you help me with this ? Many thanks in advance !

**Comment by ojw28** [comment]
Is it a "real" Android device. What device is it, exactly, and what version of Android does it run?

**Comment by Dayzen** [comment]
Yes it's a real device, in this case it's the galaxy core gti8260 4.1.2 but I know from ExoPlayer code that any device can encounter  this issue if the video format is greater than "maxDecodableFrameSize"

**Comment by ojw28** [comment]
If the device is reporting what it supports correctly then the device would encounter an issue if we *didn't* filter the video streams. What value is the device reporting as maxH264DecodableFrameSize, and what profile levels does it find in the `maxH264DecodableFrameSize` method?

**Comment by Dayzen** [comment]
Hello,

on gti8260
maxH264DecodableFrameSize returns 101376 
profile level is 32

I can garantee you that without filtering video stream 240p (432x240) on gti8260 the device is able to play it. I did the trick again on ExoPlayer 1.5.4 and it works fine.

As I anderstand from your previous answer the device shouldn't be able to play the stream since it was filtered by isFormatPlayable() method. So my fix isn't safe while certain devices would not be able to play  unfiltered stream. 

I await your clarification before taking a decision.

Thank you !

**Comment by ojw28** [comment]
You understand correctly; yes. You're also correct to observe that we end up deriving a device's capabilities in a somewhat overly conservatively way. Things are much better on API level 21 and above, where we use a different platform API that provides us with better information.

For your case, if the default format is always pretty low quality for the streams that you're playing, then it should be relatively safe to do what you're doing. You could optionally enable your fix only on known bad devices, for example by inspecting http://developer.android.com/reference/android/os/Build.html#MODEL.

We'll be making it easier to select tracks that we don't think the device can play in the future, since we've received a few other requests for the ability to override our logic. Leaving this open to track this as an enhancement.

**Comment by Dayzen** [comment]
Do you think there's a way to know when a device is unable to play an unfiltered stream format ?

I want to let my tricky fix and get notify if my trick doesn't work. But since I've never had any problem with unfiltered stream I can't know what happens in this case (if there's a crash, an exception, or whatever).
If I can catch such event I would be able to play mp4 instead of hls to avoid any problem linked to this issue. 

I've tried to cause an issue by playing 480p stream on the gti8260 but it played well. 

Could you explain me what is supposed to happen when we play an unfiltred stream on an unsuitable device ?

**Comment by ojw28** [comment]
We now always attempt to play the lowest quality video format, even if it exceeds the reported device capabilities. This is enabled by default, and so should resolve this issue. If the lowest quality really does exceed the capabilities of the device, you'd expect to receive a playback failure via `Player.EventListener.onPlayerError`.
