### ISSUE TITLE
DASH playing a live stream.

### ISSUE THREAD

**Issue by vaszol** [google/ExoPlayer#1204]
Hello! In the example demo add their links to dash flows on ip camera and playback displays only the first frame and a zero length videos. How do I play a live stream from ip cameras?

**Comment by ojw28** [comment]
There's nowhere near enough detail to diagnose this, but if the cameras are video only (no audio) then you're probably hitting #758, and you'll need to wait for that to be fixed.

**Comment by vaszol** [comment]
this link https://bitlivedemo-a.akamaihd.net/mpds/stream-exo-liveedge.php?streamkey=bitcodin&#038;inputType=dash normal playing in commit 26 Jan 2015 @ojw28 ojw28 Fix DASH Live edge calculation.,
but non playing in current 22 jan 2016.  
how i fix it in current commit for playing my link?

**Comment by vaszol** [comment]
We've added an audio track to the video from cameras on nginx, then ExoPlayer Demo began to work with our video streams.
