### ISSUE TITLE
Setting Custom http headers while playing mpd file

### ISSUE THREAD

**Issue by jatin2225** [google/ExoPlayer#1205]
Is there any way by which we can set the custom http header while playing the .mpd file using Exoplayer.

**Comment by b95505017** [comment]
Using OkHttp extension as your HTTP data source, then hook up your custom http header via Interceptor with OkHttpClient.

**Comment by ojw28** [comment]
You can also use `HttpDataSource.setRequestProperty`.

**Comment by jatin2225** [comment]
In the given Exoplayer example, DashRendererBuilder I did the following changes. But it didn't worked.

public AsyncRendererBuilder(Context context, String userAgent, String url,
    MediaDrmCallback drmCallback, ExoPlayerWrapper player) {
  this.context = context;
  this.userAgent = userAgent;
  this.drmCallback = drmCallback;
  this.player = player;
  MediaPresentationDescriptionParser parser = new MediaPresentationDescriptionParser();
  manifestDataSource = new DefaultUriDataSource(context, userAgent);
  //manifestFetcher = new ManifestFetcher<>(url, manifestDataSource, parser);
  HttpDataSource defaultHttpDataSource = new DefaultHttpDataSource(userAgent, null);
  defaultHttpDataSource.setRequestProperty("X_CAMPAIGN_ID", "123456789");
  manifestFetcher = new ManifestFetcher<>(url, defaultHttpDataSource, parser);
}

Can you suggest whether we are doing something wrong?

**Comment by b95505017** [comment]
This block is only related to manifest fetching.
There are more data source below, such as `DataSource videoDataSource`.
