### ISSUE TITLE
Set Maximum Buffer for Exo Player

### ISSUE THREAD

**Issue by davigun** [google/ExoPlayer#1206]
Hello, i would like to know is there a way to set Max Buffer beside SET_MIN_BUFFER from the factory class? so that i can only download the chunk for the next 3 seconds only. Or is there anyway using throtling ?

**Comment by RamkumarVooda** [comment]
Any solution for this..?

**Comment by ojw28** [comment]
The initial question states that there's a way to do this already, so it's unclear what the question is beyond asking whether there's a second way of doing the same thing? If that is the question then the answer is no, although in 2.x the setting of a buffering policy should become much simpler and less specific to the different types of playback that ExoPlayer supports.

**Comment by ojw28** [comment]
Closing this. Note that in 2.x this becomes far more straightforward. Rather than the buffering configuration being set in separate places for DASH/HLS/SmoothStreaming/Other, it's now managed by a single LoadControl injected when creating the ExoPlayer instance.
