### ISSUE TITLE
HLS HEVC stream processing error

### ISSUE THREAD

**Issue by sapanda** [google/ExoPlayer#1207]
Hello, We recently ran a live event where we tried to stream an HLS HEVC stream to an S6 running Exoplayer 1.5.4. We verified that the stream was able to run fine in VLC, but it didn't run in the Exoplayer demo app and we got the errors listed bellow. Any idea what might be going wrong? Are there some parameters that need to be set on the stream (coming through Wowza)?

Unfortunately we were using a rented UHD hardware encoder that we don't currently have access to - so don't have a stream at the moment.

> I/ACodec(8134): [OMX.SEC.aac.dec] Now Idle->Executing
> I/ACodec(8134): [OMX.SEC.aac.dec] Now Executing
> E/ACodec(8134): OMXCodec::onEvent, OMX_ErrorStreamCorrupt
> W/AHierarchicalStateMachine(8134): Warning message AMessage(what = 'omx ', target = 15) = {
> W/AHierarchicalStateMachine(8134):   int32_t type = 0
> W/AHierarchicalStateMachine(8134):   void *node = 0x280
> W/AHierarchicalStateMachine(8134):   int32_t event = 1
> W/AHierarchicalStateMachine(8134):   int32_t data1 = -2147479541
> W/AHierarchicalStateMachine(8134):   int32_t data2 = 0
> W/AHierarchicalStateMachine(8134): } unhandled in root state.
> E/ACodec(8134): OMXCodec::onEvent, OMX_ErrorStreamCorrupt
> W/AHierarchicalStateMachine(8134): Warning message AMessage(what = 'omx ', target = 15) = {
> W/AHierarchicalStateMachine(8134):   int32_t type = 0
> W/AHierarchicalStateMachine(8134):   void *node = 0x280
> W/AHierarchicalStateMachine(8134):   int32_t event = 1
> W/AHierarchicalStateMachine(8134):   int32_t data1 = -2147479541
> W/AHierarchicalStateMachine(8134):   int32_t data2 = 0
> W/AHierarchicalStateMachine(8134): } unhandled in root state.
> E/ACodec(8134): OMXCodec::onEvent, OMX_ErrorStreamCorrupt
> W/AHierarchicalStateMachine(8134): Warning message AMessage(what = 'omx ', target = 15) = {
> W/AHierarchicalStateMachine(8134):   int32_t type = 0
> W/AHierarchicalStateMachine(8134):   void *node = 0x280
> W/AHierarchicalStateMachine(8134):   int32_t event = 1
> W/AHierarchicalStateMachine(8134):   int32_t data1 = -2147479541
> W/AHierarchicalStateMachine(8134):   int32_t data2 = 0
> W/AHierarchicalStateMachine(8134): } unhandled in root state.
> D/EventLogger(8134): decoderInitialized [20.83, OMX.SEC.aac.dec]
> E/ACodec(8134): OMXCodec::onEvent, OMX_ErrorStreamCorrupt
> W/AHierarchicalStateMachine(8134): Warning message AMessage(what = 'omx ', target = 15) = {
> W/AHierarchicalStateMachine(8134):   int32_t type = 0
> W/AHierarchicalStateMachine(8134):   void *node = 0x280
> W/AHierarchicalStateMachine(8134):   int32_t event = 1
> W/AHierarchicalStateMachine(8134):   int32_t data1 = -2147479541
> W/AHierarchicalStateMachine(8134):   int32_t data2 = 0
> W/AHierarchicalStateMachine(8134): } unhandled in root state.
> I/ACodec(8134): [OMX.SEC.aac.dec] Now handling output port settings change
> W/AHierarchicalStateMachine(8134): Warning message AMessage(what = 'omx ', target = 15) = {
> W/AHierarchicalStateMachine(8134):   int32_t type = 0
> W/AHierarchicalStateMachine(8134):   void *node = 0x280
> W/AHierarchicalStateMachine(8134):   int32_t event = 1
> W/AHierarchicalStateMachine(8134):   int32_t data1 = -2147479541
> W/AHierarchicalStateMachine(8134):   int32_t data2 = 0
> W/AHierarchicalStateMachine(8134): } unhandled in root state.
> I/ACodec(8134): [OMX.SEC.aac.dec] Now Executing
> E/ACodec(8134): OMXCodec::onEvent, OMX_ErrorStreamCorrupt
> W/AHierarchicalStateMachine(8134): Warning message AMessage(what = 'omx ', target = 15) = {
> W/AHierarchicalStateMachine(8134):   int32_t type = 0
> W/AHierarchicalStateMachine(8134):   void *node = 0x280
> W/AHierarchicalStateMachine(8134):   int32_t event = 1
> W/AHierarchicalStateMachine(8134):   int32_t data1 = -2147479541
> W/AHierarchicalStateMachine(8134):   int32_t data2 = 0
> W/AHierarchicalStateMachine(8134): } unhandled in root state.
> E/ACodec(8134): OMXCodec::onEvent, OMX_ErrorStreamCorrupt
> W/AHierarchicalStateMachine(8134): Warning message AMessage(what = 'omx ', target = 15) = {
> W/AHierarchicalStateMachine(8134):   int32_t type = 0
> W/AHierarchicalStateMachine(8134):   void *node = 0x280
> W/AHierarchicalStateMachine(8134):   int32_t event = 1
> W/AHierarchicalStateMachine(8134):   int32_t data1 = -2147479541
> W/AHierarchicalStateMachine(8134):   int32_t data2 = 0
> W/AHierarchicalStateMachine(8134): } unhandled in root state.
> E/ACodec(8134): OMXCodec::onEvent, OMX_ErrorStreamCorrupt
> W/AHierarchicalStateMachine(8134): Warning message AMessage(what = 'omx ', target = 15) = {
> W/AHierarchicalStateMachine(8134):   int32_t type = 0
> W/AHierarchicalStateMachine(8134):   void *node = 0x280
> W/AHierarchicalStateMachine(8134):   int32_t event = 1
> W/AHierarchicalStateMachine(8134):   int32_t data1 = -2147479541
> W/AHierarchicalStateMachine(8134):   int32_t data2 = 0
> W/AHierarchicalStateMachine(8134): } unhandled in root state.
> E/ACodec(8134): [OMX.qcom.video.decoder.hevc] ERROR(0x80001009)
> E/MediaCodec(8134): Codec reported an error. (omx error 0x80001009, internalError -2147483648)
> E/ExoPlayerImplInternal(8134): Internal runtime error.
> E/ExoPlayerImplInternal(8134): java.lang.IllegalStateException
> E/ExoPlayerImplInternal(8134): 	at android.media.MediaCodec.dequeueOutputBuffer(Native Method)
> E/ExoPlayerImplInternal(8134): 	at com.google.android.exoplayer.MediaCodecTrackRenderer.drainOutputBuffer(MediaCodecTrackRenderer.java:821)
> E/ExoPlayerImplInternal(8134): 	at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:489)
> E/ExoPlayerImplInternal(8134): 	at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:129)
> E/ExoPlayerImplInternal(8134): 	at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431)
> E/ExoPlayerImplInternal(8134): 	at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
> E/ExoPlayerImplInternal(8134): 	at android.os.Handler.dispatchMessage(Handler.java:98)
> E/ExoPlayerImplInternal(8134): 	at android.os.Looper.loop(Looper.java:146)
> E/ExoPlayerImplInternal(8134): 	at android.os.HandlerThread.run(HandlerThread.java:61)
> E/ExoPlayerImplInternal(8134): 	at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
> I/ACodec(8134): [OMX.qcom.video.decoder.hevc] Now Executing->Idle
> E/EventLogger(8134): playerFailed [21.59]
> E/EventLogger(8134): com.google.android.exoplayer.ExoPlaybackException: java.lang.IllegalStateException
> E/EventLogger(8134): 	at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:246)
> E/EventLogger(8134): 	at android.os.Handler.dispatchMessage(Handler.java:98)
> E/EventLogger(8134): 	at android.os.Looper.loop(Looper.java:146)
> E/EventLogger(8134): 	at android.os.HandlerThread.run(HandlerThread.java:61)
> E/EventLogger(8134): 	at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
> E/EventLogger(8134): Caused by: java.lang.IllegalStateException
> E/EventLogger(8134): 	at android.media.MediaCodec.dequeueOutputBuffer(Native Method)
> E/EventLogger(8134): 	at com.google.android.exoplayer.MediaCodecTrackRenderer.drainOutputBuffer(MediaCodecTrackRenderer.java:821)
> E/EventLogger(8134): 	at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:489)
> E/EventLogger(8134): 	at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:129)
> E/EventLogger(8134): 	at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431)
> E/EventLogger(8134): 	at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
> E/EventLogger(8134): 	... 4 more
> I/ACodec(8134): [OMX.qcom.video.decoder.hevc] Now Idle->Loaded
> I/ACodec(8134): [OMX.qcom.video.decoder.hevc] Now Loaded
> I/ACodec(8134):  [OMX.qcom.video.decoder.hevc] Now uninitialized
> I/ACodec(8134): [OMX.SEC.aac.dec] Now Executing->Idle
> I/ACodec(8134): [OMX.SEC.aac.dec] Now Idle->Loaded
> I/ACodec(8134): [OMX.SEC.aac.dec] Now Loaded
> I/ACodec(8134):  [OMX.SEC.aac.dec] Now uninitialized
> D/EventLogger(8134): state [21.66, true, I]
> D/dalvikvm(8134): GC_FOR_ALLOC freed 30295K, 64% free 17799K/49228K, paused 36ms, total 39ms
> D/dalvikvm(8134): GC_FOR_ALLOC freed 3118K, 64% free 17820K/49228K, paused 32ms, total 33ms
> D/dalvikvm(8134): GC_FOR_ALLOC freed 3145K, 64% free 17821K/49228K, paused 33ms, total 33ms
> D/dalvikvm(8134): GC_FOR_ALLOC freed 3146K, 64% free 17821K/49228K, paused 35ms, total 41ms
> D/ViewRootImpl(8134): ViewPostImeInputStage ACTION_DOWN

**Comment by andrewlewis** [comment]
I don't think there is much we can do without having a test stream that reproduces the issue. Please reply if you can provide one.

For what it's worth, it seems likely that the stream fed to the decoder was corrupted (OMX_ErrorStreamCorrupt) or lacked some required initialization data.
