### ISSUE TITLE
Is there a state in EXO player like player is fast forwarding or rewinding?

### ISSUE THREAD

**Issue by joshimaulik** [google/ExoPlayer#1208]
Hello,

I want to know is there a specific state when we FF or Reverse the playback. I know that when we FF or Reverse the play back, it comes into the MediaCodecaudioTrackrenderer's "SeekTo(position)" function to adjust he play back. 

What I am doing is, calling player.SeekTo function to adjust it's position to couple of milliseconds but I am not doing FF, so I just want to differentiate when will it actually FF through which function?

Thanks

**Comment by ojw28** [comment]
ExoPlayer doesn't have an API for fast-forward and rewind and so there isn't a corresponding state either. I'm not sure I understand your comment `when we FF or Reverse the playback`, since as above ExoPlayer doesn't have fast-forward and rewind APIs.

**Comment by joshimaulik** [comment]
What I want to know is, when we fast forward on exo player, it goes multiple times into seekTo() function of mediacodecaudiotrackrenderer class. So is there any way to find out what was the last position of fast forward ?

**Comment by ojw28** [comment]
There is no such thing as fast forward in ExoPlayer. As far as the player is concerned, it's just receiving lots of individual seek calls. You should probably implement your own playback controls that do have a concept of when the user is fast forwarding (i.e. user's finger is still dragging the control), and then use that.

**Comment by joshimaulik** [comment]
okay, thank you!!
