### ISSUE TITLE
issues exoplayer library android studio compile

### ISSUE THREAD

**Issue by alexistkd** [google/ExoPlayer#1212]
Hi i already added the exoplayer library to my proyect, now im trying to build it but im getting this error:

    Error:Could not run build action using Gradle distribution 'https://services.gradle.org/distributions/gradle-2.4-all.zip'.

this is my root build.gradle

    // Top-level build file where you can add configuration options common to all sub-projects/modules.
    
    buildscript {
        repositories {
            jcenter()
        }
        dependencies {
            classpath 'com.android.tools.build:gradle:1.5.0'
            // NOTE: Do not place your application dependencies here; they belong
            // in the individual module build.gradle files
            classpath 'com.novoda:bintray-release:0.2.7'
        }
    }
    
    allprojects {
        repositories {
            jcenter()
        }
    }
    
    task clean(type: Delete) {
        delete rootProject.buildDir
    }

how i can fix this? i follow this tutorial http://stackoverflow.com/questions/29776690/failed-to-apply-plugin-android-studio

but no luck still same issue.

thank you in advance.

**Comment by ojw28** [comment]
I don't think this is an ExoPlayer specific issue. I'd suggest you ask for help on StackOverflow, or similar.
