### ISSUE TITLE
Is it possible to recognize the type of stream automatically?

### ISSUE THREAD

**Issue by b95505017** [google/ExoPlayer#1213]
In demo app, we have to define each type of the sample stream, e.g. HLS, DASH, smoothStreaming. Then it knows which the renderer builder should be built and do the manifest fetching stuff.

Is it possible to just give the stream url without the type? Let ExoPlayer do the rest of the things.

**Comment by ojw28** [comment]
See https://github.com/google/ExoPlayer/issues/1077.
