### ISSUE TITLE
Video buffer underrun

### ISSUE THREAD

**Issue by traninho** [google/ExoPlayer#1217]
Hey,

It is possible to somehow detect video buffer underrun? I can see that there is a listener for audio:

`MediaCodecAudioTrackRenderer.EventListener#onAudioTrackUnderrun()`

But I cannot find out how to get buffer underrun event for video. 

Thank you.

**Comment by ojw28** [comment]
The closest analogy would be to look at dropped frames, which occur when the player ends up being late trying to render them. You can listen for dropped frames using `MediaCodecVideoTrackRenderer.EventListener.onDroppedFrames`. Note that if you don't want batched reporting, you need to set `maxDroppedFrameCountToNotify` to a suitably small value in the `MediaCodecVideoTrackRenderer` constructor.
