### ISSUE TITLE
Question: Switching Outputs and Adaptative HLS 

### ISSUE THREAD

**Issue by ThiagoMiranda** [google/ExoPlayer#1221]
Hi..
I'm developing a SDK based on the Exoplayer and I would like to have an option to the user manually switch outputs during the playback ( progressive not HLS ). Is there a method to do that easily? Something like: setUrl() ?

Another question: How can I make sure that my adaptative hls is working? I mean, switching automatically from one output to another ( it doesn't seems to be doing that even with multiple outputs on my m3u8 file ).

Thanks

**Comment by marcbaechinger** [comment]
I have seen adaptive bitrate selection working many times. It starts with the lowest quality and adapts if the bandwidth allows for it. It depends on network condition and the bitrate of the variants in the HLS. Also the variants are filtered to discard variants which can't be played on a given device. 

So the number of variant available depends on the device and the point in time to switch up/down depends on network condition. Please check the sample in the ExoPlayer Demo app under 'HLS'. Try the sample 'Apple master playlist'. It starts with the lowest quality (on screen it is named 'Gear 1') and then switches to better quality ('Gear 4' in my case which is the highest quality).

Can you provide more information for the first question? What url would you like the user to set? Actually, there is only one relevant URL for HLS, the one of the playlist. All further urls to network resources are derived from the playlist. When you want to set a new playlist URL you have to start again and create a new instance. But this can not happen 'during playback' inmy understanding.
