### ISSUE TITLE
Play DASH type, black screen

### ISSUE THREAD

**Issue by kinhdang** [google/ExoPlayer#1224]
Hello all !

We are using DASH type play in Eoplayer 1.5.4, audio working properly, but video not see, black screen. Any body knows, please help ?

many Thanks.

**Comment by andrewlewis** [comment]
Please read [reporting an issue](https://google.github.io/ExoPlayer/2015/10/01/reporting-issues.html) and provide the information described there. We would at least need to know the device and Android build you are using, and what stream you are playing, preferably in the demo app. Thanks!

**Comment by kinhdang** [comment]
Hello all !

we are testing stream in Exoplayer demo, running on SAMSUNG device, 
debug show : 
![umh_umm](https://cloud.githubusercontent.com/assets/9839084/12787772/72d673e0-cac9-11e5-917b-99301132ad08.png)
this is log file :
02-03 10:53:09.324: I/dalvikvm(1594): Could not find method com.google.android.exoplayer.demo.PlayerActivity.requestPermissions, referenced from method com.google.android.exoplayer.demo.PlayerActivity.maybeRequestPermission
02-03 10:53:09.324: W/dalvikvm(1594): VFY: unable to resolve virtual method 1552: Lcom/google/android/exoplayer/demo/PlayerActivity;.requestPermissions ([Ljava/lang/String;I)V
02-03 10:53:09.324: D/dalvikvm(1594): VFY: replacing opcode 0x6e at 0x0010
02-03 10:53:09.324: I/dalvikvm(1594): Could not find method com.google.android.exoplayer.demo.PlayerActivity.checkSelfPermission, referenced from method com.google.android.exoplayer.demo.PlayerActivity.requiresPermission
02-03 10:53:09.324: W/dalvikvm(1594): VFY: unable to resolve virtual method 1517: Lcom/google/android/exoplayer/demo/PlayerActivity;.checkSelfPermission (Ljava/lang/String;)I
02-03 10:53:09.324: D/dalvikvm(1594): VFY: replacing opcode 0x6e at 0x000e
02-03 10:53:10.314: I/dalvikvm(1594): Could not find method android.view.accessibility.CaptioningManager$CaptionStyle.hasForegroundColor, referenced from method com.google.android.exoplayer.text.CaptionStyleCompat.createFromCaptionStyleV21
02-03 10:53:10.314: W/dalvikvm(1594): VFY: unable to resolve virtual method 383: Landroid/view/accessibility/CaptioningManager$CaptionStyle;.hasForegroundColor ()Z
02-03 10:53:10.314: D/dalvikvm(1594): VFY: replacing opcode 0x6e at 0x0002
02-03 10:53:10.424: D/dalvikvm(1594): GC_FOR_ALLOC freed 100K, 4% free 5036K/5244K, paused 3ms, total 4ms
02-03 10:53:10.434: I/ExoPlayerImpl(1594): Init 1.5.3
02-03 10:53:10.434: D/EventLogger(1594): start [0]
02-03 10:53:10.434: D/EventLogger(1594): state [0.00, false, P]
02-03 10:53:10.444: D/EventLogger(1594): state [0.01, true, P]
02-03 10:53:10.764: D/dalvikvm(1594): GC_FOR_ALLOC freed 180K, 5% free 5626K/5908K, paused 14ms, total 14ms
02-03 10:53:10.844: I/dalvikvm(1594): Could not find method android.media.MediaCodec.releaseOutputBuffer, referenced from method com.google.android.exoplayer.MediaCodecVideoTrackRenderer.renderOutputBufferV21
02-03 10:53:10.844: W/dalvikvm(1594): VFY: unable to resolve virtual method 134: Landroid/media/MediaCodec;.releaseOutputBuffer (IJ)V
02-03 10:53:10.844: D/dalvikvm(1594): VFY: replacing opcode 0x6e at 0x0008
02-03 10:53:10.844: E/dalvikvm(1594): Could not find class 'android.media.PlaybackParams', referenced from method com.google.android.exoplayer.MediaCodecAudioTrackRenderer.handleMessage
02-03 10:53:10.844: W/dalvikvm(1594): VFY: unable to resolve check-cast 66 (Landroid/media/PlaybackParams;) in Lcom/google/android/exoplayer/MediaCodecAudioTrackRenderer;
02-03 10:53:10.844: D/dalvikvm(1594): VFY: replacing opcode 0x1f at 0x0015
02-03 10:53:10.844: I/dalvikvm(1594): Could not find method android.media.AudioTrack.write, referenced from method com.google.android.exoplayer.audio.AudioTrack.writeNonBlockingV21
02-03 10:53:10.844: W/dalvikvm(1594): VFY: unable to resolve virtual method 117: Landroid/media/AudioTrack;.write (Ljava/nio/ByteBuffer;II)I
02-03 10:53:10.844: D/dalvikvm(1594): VFY: replacing opcode 0x6e at 0x0001
02-03 10:53:10.844: W/dalvikvm(1594): VFY: unable to find class referenced in signature (Landroid/media/PlaybackParams;)
02-03 10:53:10.844: W/dalvikvm(1594): VFY: unable to find class referenced in signature (Landroid/media/PlaybackParams;)
02-03 10:53:10.894: I/dalvikvm(1594): Could not find method android.view.Display.getMode, referenced from method com.google.android.exoplayer.chunk.VideoFormatSelectorUtil.getDisplaySizeV23
02-03 10:53:10.894: W/dalvikvm(1594): VFY: unable to resolve virtual method 345: Landroid/view/Display;.getMode ()Landroid/view/Display$Mode;
02-03 10:53:10.894: D/dalvikvm(1594): VFY: replacing opcode 0x6e at 0x0000
02-03 10:53:10.894: I/dalvikvm(1594): Could not find method android.media.MediaCodecInfo$CodecCapabilities.getVideoCapabilities, referenced from method com.google.android.exoplayer.MediaCodecUtil.isSizeAndRateSupportedV21
02-03 10:53:10.894: W/dalvikvm(1594): VFY: unable to resolve virtual method 139: Landroid/media/MediaCodecInfo$CodecCapabilities;.getVideoCapabilities ()Landroid/media/MediaCodecInfo$VideoCapabilities;
02-03 10:53:10.894: D/dalvikvm(1594): VFY: replacing opcode 0x6e at 0x0019
02-03 10:53:10.894: I/OMXClient(1594): Using client-side OMX mux.
02-03 10:53:11.094: E/OMXNodeInstance(1594): OMX_GetExtensionIndex OMX.google.android.index.storeMetaDataInBuffers failed
02-03 10:53:11.094: W/OMXNodeInstance(1594): OMX_GetExtensionIndex OMX.google.android.index.prepareForAdaptivePlayback failed
02-03 10:53:11.114: I/OMXClient(1594): Using client-side OMX mux.
02-03 10:53:11.404: D/EventLogger(1594): availableRange [true, 161730770000, 161780817999]
02-03 10:53:11.404: D/EventLogger(1594): state [0.97, true, B]
02-03 10:53:11.784: D/EventLogger(1594): bandwidth [1.34, 621, 0.27, 18537]
02-03 10:53:11.814: D/EventLogger(1594): audioFormat [1.37, p0a1r0, 2]
02-03 10:53:11.814: I/OMXClient(1594): Using client-side OMX mux.
02-03 10:53:11.814: D/EventLogger(1594): decoderInitialized [1.38, OMX.google.aac.decoder]
02-03 10:53:11.864: I/SoftAAC2(1594): Reconfiguring decoder: 0->48000 Hz, 0->2 channels
02-03 10:53:11.884: D/EventLogger(1594): state [1.45, true, R]
02-03 10:53:12.124: D/EventLogger(1594): bandwidth [1.69, 160700, 0.27, 4743911]
02-03 10:53:12.444: D/EventLogger(1594): bandwidth [2.01, 160710, 0.23, 4743911]
02-03 10:53:12.644: D/dalvikvm(1594): GC_FOR_ALLOC freed 312K, 7% free 6238K/6652K, paused 5ms, total 5ms
02-03 10:53:12.754: D/EventLogger(1594): bandwidth [2.32, 161190, 0.17, 5494358]
02-03 10:53:13.624: D/EventLogger(1594): availableRange [true, 161740775333, 161790823333]
02-03 10:53:13.944: D/EventLogger(1594): bandwidth [3.50, 160684, 0.25, 5060913]
02-03 10:53:24.204: D/EventLogger(1594): availableRange [true, 161750780666, 161800828666]
02-03 10:53:24.544: D/EventLogger(1594): bandwidth [14.11, 160695, 0.28, 5060913]
02-03 10:53:26.534: D/InputEventConsistencyVerifier(1594): KeyEvent: ACTION_UP but key was not down.

**Comment by andrewlewis** [comment]
Please paste the output of `adb shell getprop ro.build.fingerprint` so we know the exact device and build you are testing on.

**Comment by kinhdang** [comment]
Thank for your reply !

This is my stream :  http://hls1.vn.v247tv.com/test/VnewsHD.480/manifest.mpd
,Please checking it and suggest our fix this problems.

**Comment by andrewlewis** [comment]
What Samsung device is it? Please run `adb shell getprop ro.build.fingerprint` and paste the output.

**Comment by kinhdang** [comment]
Hello !

my device : Samsung Galaxy Core Prime G361 Android 5.1 (Lollipop), and open Exo Demo by eclipse, so I'm sorry, we do not knows run adb shell getprop ro.build.fingerprint
Thanks.

**Comment by kinhdang** [comment]
Hello !

This is infor you need.
adb shell getprop ro.build.fingerprint
samsung/coreprimeve3gxx/coreprimeve3g:5.1.1/LMY48B/G361HXXU0AOL6:user/release-keys

**Comment by andrewlewis** [comment]
Your DASH manifest lists a video width of 853 pixels. This couldn't be played because VideoCapabilities.areSizeAndRateSupported returns false due to the [odd width](https://android.googlesource.com/platform/frameworks/base/+/master/media/java/android/media/MediaCodecInfo.java#1300).

However, it looks like the video is actually 720 pixels wide. The stream should play correctly if you replace "853" with "720" in the manifest.
