### ISSUE TITLE
Callback when frame drawn to surface

### ISSUE THREAD

**Issue by jmgirven** [google/ExoPlayer#1226]
Does ExoPlayer have a callback when a frame is drawn to the underlying surface? This would be analogous to the Android [Camera.PreviewCallback#onPreviewFrame](http://developer.android.com/reference/android/hardware/Camera.PreviewCallback.html), which gets called as frames are displayed, with the frames `byte[]` data. I would like access to each frame that is drawn to the surface.

Is this the `ByteBuffer buffer` from [MediaCodecVideoTrackRenderer#processOutputBuffer](https://github.com/google/ExoPlayer/blob/master/library/src/main/java/com/google/android/exoplayer/MediaCodecVideoTrackRenderer.java#L384) after super has been called? If I just overrode MediaCodecVideoTrackRenderer and returned `ByteBuffer buffer`?

**Comment by ojw28** [comment]
We don't provide such a callback. It's probably most appropriate for you to extend MediaCodecVideoTrackRenderer somehow, but it depends a bit on exactly what you're trying to do / what your use case it.

**Comment by jmgirven** [comment]
OK, thanks. As outlined a bit more in #1220, I would like to do some image processing on the video after it is decoded using ExoPlayer, but before it is rendered to the screen. I found that if I rendered the video to a hidden `SurfaceTexture` using ExoPlayer, and got notified that the surface was updated, then I could pass the frames on to my image processing library before rendering to the screen. I have an example using the Android camera rendering to a `SurfaceTexture` in a similar way, but there you have the above mentioned callback to trigger the image processing to reprocess the frame.

I will look into MediaCodecVideoTrackRenderer more to see if I can get the information I need. Otherwise, maybe I can override `SurfaceTexture` to give me frames and when they are update from there. If this sparks any ideas from you, or if more information would be helpful, let me know.

**Comment by ojw28** [comment]
Ah, I see. I haven't tried, but can't you just use [SurfaceTexture.OnFrameAvailableListener](http://developer.android.com/reference/android/graphics/SurfaceTexture.OnFrameAvailableListener.html) for this? [This](https://www.virag.si/2014/03/rendering-video-with-opengl-on-android/) might also be useful to take a look at.
