### ISSUE TITLE
Out of Memory Exception

### ISSUE THREAD

**Issue by sachinbhanot** [google/ExoPlayer#123]
Hi , 
I am using Samsung note tablet, we are playing  HLS stream videos in exo player.if ,we are playing a video or long or switching the different video , then app is crashed.
here is the log.
Please let me know how to resolve the issue.

11-06 18:35:45.208: E/JavaBinder(26172): !!! FAILED BINDER TRANSACTION !!!
11-06 18:35:47.138: E/dalvikvm-heap(26172): Out of memory on a 32784-byte allocation.
11-06 18:35:47.148: E/ACRA(26172): ACRA caught a OutOfMemoryError exception for com.jio.vod. Building report.
11-06 18:35:52.628: E/ACRA(26172): Jio On-Demand fatal error : null
11-06 18:35:52.628: E/ACRA(26172): java.lang.OutOfMemoryError
11-06 18:35:52.628: E/ACRA(26172):  at com.google.android.exoplayer.parser.ts.TsExtractor$Sample.<init>(TsExtractor.java:738)
11-06 18:35:52.628: E/ACRA(26172):  at com.google.android.exoplayer.parser.ts.TsExtractor.getSample(TsExtractor.java:256)
11-06 18:35:52.628: E/ACRA(26172):  at com.google.android.exoplayer.parser.ts.TsExtractor$PesPayloadReader.addSample(TsExtractor.java:506)
11-06 18:35:52.628: E/ACRA(26172):  at com.google.android.exoplayer.parser.ts.TsExtractor$AdtsReader.readOneAacFrame(TsExtractor.java:698)
11-06 18:35:52.628: E/ACRA(26172):  at com.google.android.exoplayer.parser.ts.TsExtractor$AdtsReader.read(TsExtractor.java:637)
11-06 18:35:52.628: E/ACRA(26172):  at com.google.android.exoplayer.parser.ts.TsExtractor$PesReader.readPES(TsExtractor.java:459)
11-06 18:35:52.628: E/ACRA(26172):  at com.google.android.exoplayer.parser.ts.TsExtractor$PesReader.read(TsExtractor.java:400)
11-06 18:35:52.628: E/ACRA(26172):  at com.google.android.exoplayer.parser.ts.TsExtractor.readTSPacket(TsExtractor.java:237)
11-06 18:35:52.628: E/ACRA(26172):  at com.google.android.exoplayer.parser.ts.TsExtractor.consumeUntil(TsExtractor.java:138)
11-06 18:35:52.628: E/ACRA(26172):  at com.google.android.exoplayer.hls.HlsSampleSource.continueBufferingInternal(HlsSampleSource.java:197)
11-06 18:35:52.628: E/ACRA(26172):  at com.google.android.exoplayer.hls.HlsSampleSource.prepare(HlsSampleSource.java:102)
11-06 18:35:52.628: E/ACRA(26172):  at com.google.android.exoplayer.MediaCodecTrackRenderer.doPrepare(MediaCodecTrackRenderer.java:186)
11-06 18:35:52.628: E/ACRA(26172):  at com.google.android.exoplayer.TrackRenderer.prepare(TrackRenderer.java:117)
11-06 18:35:52.628: E/ACRA(26172):  at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(ExoPlayerImplInternal.java:273)
11-06 18:35:52.628: E/ACRA(26172):  at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:201)
11-06 18:35:52.628: E/ACRA(26172):  at android.os.Handler.dispatchMessage(Handler.java:98)
11-06 18:35:52.628: E/ACRA(26172):  at android.os.Looper.loop(Looper.java:146)
11-06 18:35:52.628: E/ACRA(26172):  at android.os.HandlerThread.run(HandlerThread.java:61)
11-06 18:35:52.628: E/ACRA(26172):  at com.google.android.exoplayer.ExoPlayerImplInternal$1.run(ExoPlayerImplInternal.java:110)

**Comment by agGitHub** [comment]
Same problem here when I try to stream this stream (for example) : "http://radiocontinu.ic-stream.nl:7062/;" (MPEG 192 kbits/s)

I get the following error on some devices and namely on my Android Simulator (Genymotion) with Android 4.4.4. No problem on my real device samsung S4.

Any idea on how to fix this issue ?

07-01 06:03:39.525: D/MyApp(3096): ExoPlayer.STATE_PREPARING
07-01 06:03:39.525: D/EventLogger(3096): state [0.02, true, P]
07-01 06:03:39.625: W/System.err(3096): java.net.ProtocolException: Unexpected status line: ICY 200 OK
07-01 06:03:39.625: W/System.err(3096): 	at com.android.okhttp.internal.http.RawHeaders.setStatusLine(RawHeaders.java:108)
07-01 06:03:39.625: W/System.err(3096): 	at com.android.okhttp.internal.http.RawHeaders.fromBytes(RawHeaders.java:308)
07-01 06:03:39.625: W/System.err(3096): 	at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:135)
07-01 06:03:39.625: W/System.err(3096): 	at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:644)
07-01 06:03:39.625: W/System.err(3096): 	at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:347)
07-01 06:03:39.625: W/System.err(3096): 	at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:296)
07-01 06:03:39.625: W/System.err(3096): 	at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:503)
07-01 06:03:39.625: W/System.err(3096): 	at net.sourceforge.servestream.transport.HTTP.connect(HTTP.java:184)
07-01 06:03:39.625: W/System.err(3096): 	at net.sourceforge.servestream.utils.HTTPRequestTask.processUri(HTTPRequestTask.java:59)
07-01 06:03:39.625: W/System.err(3096): 	at net.sourceforge.servestream.utils.HTTPRequestTask.run(HTTPRequestTask.java:41)
07-01 06:03:39.625: W/System.err(3096): 	at java.lang.Thread.run(Thread.java:841)
07-01 06:03:39.625: D/MyApp(3096): &&& onHTTPRequestError path = http://radiocontinu.ic-stream.nl:7062/; useFFmpegPlayerfalse
07-01 06:03:39.625: D/MyApp(3096): &&& onHTTPRequestError delay = 0.122
07-01 06:03:39.641: D/MobileDataStateTracker(535): default: setPolicyDataEnable(enabled=true)
07-01 06:03:39.837: D/MobileDataStateTracker(535): default: setPolicyDataEnable(enabled=true)
07-01 06:03:39.985: D/MobileDataStateTracker(535): default: setPolicyDataEnable(enabled=true)
07-01 06:03:40.141: D/MobileDataStateTracker(535): default: setPolicyDataEnable(enabled=true)
07-01 06:03:40.337: D/MobileDataStateTracker(535): default: setPolicyDataEnable(enabled=true)
07-01 06:03:40.477: D/MobileDataStateTracker(535): default: setPolicyDataEnable(enabled=true)
07-01 06:03:41.229: D/MobileDataStateTracker(535): default: setPolicyDataEnable(enabled=true)
07-01 06:03:41.481: D/MobileDataStateTracker(535): default: setPolicyDataEnable(enabled=true)
07-01 06:03:42.337: D/MobileDataStateTracker(535): default: setPolicyDataEnable(enabled=true)
07-01 06:03:42.945: A/libc(3096): Fatal signal 11 (SIGSEGV) at 0x00000004 (code=1), thread 3591 (ExoPlayerImplIn)
07-01 06:03:43.049: I/DEBUG(142): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
07-01 06:03:43.049: I/DEBUG(142): Build fingerprint: 'generic/vbox86p/vbox86p:4.4.4/KTU84P/eng.buildbot.20150216.120346:userdebug/test-keys'
07-01 06:03:43.049: I/DEBUG(142): Revision: '0'
07-01 06:03:43.049: I/DEBUG(142): pid: 3096, tid: 3591, name: ExoPlayerImplIn  >>> com.radio.fm <<<
07-01 06:03:43.049: I/DEBUG(142): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 00000004
07-01 06:03:43.253: I/DEBUG(142): backtrace:
07-01 06:03:43.253: I/DEBUG(142):     #00  pc 00068810  /system/lib/libdvm.so (dvmFindCatchBlock+96)
07-01 06:03:43.253: I/DEBUG(142):     #01  pc 0017780f  /system/lib/libdvm.so
07-01 06:03:43.253: I/DEBUG(142):     #02  pc 003d7d27  [heap]
07-01 06:03:43.253: I/DEBUG(142):     #03  pc 0003b962  /system/lib/libdvm.so (dvmMterpStd(Thread*)+66)
07-01 06:03:43.253: I/DEBUG(142):     #04  pc 00037029  /system/lib/libdvm.so (dvmInterpret(Thread*, Method const*, JValue*)+217)
07-01 06:03:43.253: I/DEBUG(142):     #05  pc 000bd027  /system/lib/libdvm.so (dvmCallMethodV(Thread*, Method const*, Object*, bool, JValue*, char*)+759)
07-01 06:03:43.253: I/DEBUG(142):     #06  pc 000bd437  /system/lib/libdvm.so (dvmCallMethod(Thread*, Method const*, Object*, JValue*, ...)+55)
07-01 06:03:43.253: I/DEBUG(142):     #07  pc 000993c3  /system/lib/libdvm.so (interpThreadStart(void*)+995)
07-01 06:03:43.253: I/DEBUG(142):     #08  pc 0000bc7c  /system/lib/libc.so (__thread_entry+236)
07-01 06:03:43.253: I/DEBUG(142):     #09  pc 0003e295  /system/lib/libc.so (__pthread_clone+69)
07-01 06:03:43.253: I/DEBUG(142):     #10  pc 00098fdf  /system/lib/libdvm.so (internalThreadStart(void*)+655)
07-01 06:03:43.253: I/DEBUG(142): stack:
07-01 06:03:43.253: I/DEBUG(142):          90c929d0  92358dd4  
07-01 06:03:43.253: I/DEBUG(142):          90c929d4  90c929fc  [stack:3591]
07-01 06:03:43.253: I/DEBUG(142):          90c929d8  b7550825  /system/lib/libandroid_runtime.so (android::android_os_SystemClock_elapsedRealtime(_JNIEnv*, _jobject*)+21)
07-01 06:03:43.253: I/DEBUG(142):          90c929dc  a4d32680  /dev/ashmem/dalvik-zygote (deleted)
07-01 06:03:43.253: I/DEBUG(142):          90c929e0  b7550816  /system/lib/libandroid_runtime.so (android::android_os_SystemClock_elapsedRealtime(_JNIEnv*, _jobject*)+6)
07-01 06:03:43.253: I/DEBUG(142):          90c929e4  30000002  
07-01 06:03:43.253: I/DEBUG(142):          90c929e8  b4d424ac  /system/lib/libdvm.so (dvmPlatformInvoke+80)
07-01 06:03:43.253: I/DEBUG(142):          90c929ec  b849e0c8  [heap]
07-01 06:03:43.253: I/DEBUG(142):          90c929f0  fc100001  
07-01 06:03:43.253: I/DEBUG(142):          90c929f4  92358e20  
07-01 06:03:43.253: I/DEBUG(142):          90c929f8  951f87de  /data/dalvik-cache/data@app@com.radio.apk@classes.dex
07-01 06:03:43.253: I/DEBUG(142):          90c929fc  b7550845  /system/lib/libandroid_runtime.so (android::android_os_SystemClock_uptimeMillis(_JNIEnv*, _jobject*)+21)
07-01 06:03:43.253: I/DEBUG(142):          90c92a00  a4d32680  /dev/ashmem/dalvik-zygote (deleted)
07-01 06:03:43.253: I/DEBUG(142):          90c92a04  b7550836  /system/lib/libandroid_runtime.so (android::android_os_SystemClock_uptimeMillis(_JNIEnv*, _jobject*)+6)
07-01 06:03:43.253: I/DEBUG(142):          90c92a08  b4edecb4  /system/lib/libdvm.so
07-01 06:03:43.253: I/DEBUG(142):          90c92a0c  00000000  
07-01 06:03:43.253: I/DEBUG(142):     #00  90c92a10  00000001  
07-01 06:03:43.253: I/DEBUG(142):          90c92a14  9ddfefb8  /dev/ashmem/dalvik-LinearAlloc (deleted)
07-01 06:03:43.253: I/DEBUG(142):          90c92a18  b4d9ed2b  /system/lib/libdvm.so (dvmCallJNIMethod(unsigned int const*, JValue*, Method const*, Thread*)+315)
07-01 06:03:43.253: I/DEBUG(142):          90c92a1c  b863fd28  [heap]
07-01 06:03:43.253: I/DEBUG(142):          90c92a20  00000001  
07-01 06:03:43.253: I/DEBUG(142):          90c92a24  30000002  
07-01 06:03:43.253: I/DEBUG(142):          90c92a28  00000000  
07-01 06:03:43.253: I/DEBUG(142):          90c92a2c  b4da8e69  /system/lib/libdvm.so (dvmAddToReferenceTable(ReferenceTable*, Object*)+25)
07-01 06:03:43.253: I/DEBUG(142):          90c92a30  9d33f902  /data/dalvik-cache/system@framework@framework.jar@classes.dex
07-01 06:03:43.253: I/DEBUG(142):          90c92a34  b7550810  /system/lib/libandroid_runtime.so (android::android_os_SystemClock_elapsedRealtime(_JNIEnv*, _jobject*))
07-01 06:03:43.253: I/DEBUG(142):          90c92a38  b863fd38  [heap]
07-01 06:03:43.253: I/DEBUG(142):          90c92a3c  b4d9ed2b  /system/lib/libdvm.so (dvmCallJNIMethod(unsigned int const*, JValue*, Method const*, Thread*)+315)
07-01 06:03:43.253: I/DEBUG(142):          90c92a40  b863fd28  [heap]
07-01 06:03:43.253: I/DEBUG(142):          90c92a44  92358dcc  
07-01 06:03:43.253: I/DEBUG(142):          90c92a48  9e1a0c70  /dev/ashmem/dalvik-LinearAlloc (deleted)
07-01 06:03:43.253: I/DEBUG(142):          90c92a4c  92358dfc  
07-01 06:03:43.253: I/DEBUG(142):          ........  ........
07-01 06:03:43.253: I/DEBUG(142):     #01  90c92aa0  b863fd28  [heap]
07-01 06:03:43.253: I/DEBUG(142):          ........  ........
07-01 06:03:43.253: I/DEBUG(142):          ........  ........
07-01 06:03:43.369: I/BootReceiver(535): Copying /data/tombstones/tombstone_06 to DropBox (SYSTEM_TOMBSTONE)
07-01 06:03:43.385: W/InputDispatcher(535): channel '52b847b0 com.radio.fm/com.radio.fm.SearchActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
07-01 06:03:43.385: E/InputDispatcher(535): channel '52b847b0 com..radio.fm/com.radio.fm.SearchActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
07-01 06:03:43.385: W/InputDispatcher(535): channel '529ac9b8 com.radio.fm/com.radio.fm.SearchResultsActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
07-01 06:03:43.385: E/InputDispatcher(535): channel '529ac9b8 com.radio.fm/com.radio.fm.SearchResultsActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
07-01 06:03:43.385: W/InputDispatcher(535): channel '52b4aa3c com.radio.fm/com.radio.fm.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
07-01 06:03:43.385: E/InputDispatcher(535): channel '52b4aa3c com.radio.fm/com.radio.fm.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
07-01 06:03:43.385: D/dalvikvm(535): GC_FOR_ALLOC freed 1431K, 25% free 12482K/16532K, paused 15ms, total 15ms
07-01 06:03:43.389: E/JavaBinder(535): !!! FAILED BINDER TRANSACTION !!!
07-01 06:03:43.389: E/JavaBinder(535): !!! FAILED BINDER TRANSACTION !!!
07-01 06:03:43.389: W/ActivityManager(535):   Force finishing activity com.radio.fm/.SearchResultsActivity
07-01 06:03:43.389: W/ActivityManager(535): Exception thrown during pause
07-01 06:03:43.389: W/ActivityManager(535): android.os.TransactionTooLargeException
07-01 06:03:43.389: W/ActivityManager(535): 	at android.os.BinderProxy.transact(Native Method)
07-01 06:03:43.389: W/ActivityManager(535): 	at android.app.ApplicationThreadProxy.schedulePauseActivity(ApplicationThreadNative.java:660)
07-01 06:03:43.389: W/ActivityManager(535): 	at com.android.server.am.ActivityStack.startPausingLocked(ActivityStack.java:761)
07-01 06:03:43.389: W/ActivityManager(535): 	at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:2443)
07-01 06:03:43.389: W/ActivityManager(535): 	at com.android.server.am.ActivityStack.finishTopRunningActivityLocked(ActivityStack.java:2320)
07-01 06:03:43.389: W/ActivityManager(535): 	at com.android.server.am.ActivityStackSupervisor.finishTopRunningActivityLocked(ActivityStackSupervisor.java:2050)
07-01 06:03:43.389: W/ActivityManager(535): 	at com.android.server.am.ActivityManagerService.handleAppCrashLocked(ActivityManagerService.java:9548)
07-01 06:03:43.389: W/ActivityManager(535): 	at com.android.server.am.ActivityManagerService.makeAppCrashingLocked(ActivityManagerService.java:9441)
07-01 06:03:43.389: W/ActivityManager(535): 	at com.android.server.am.ActivityManagerService.crashApplication(ActivityManagerService.java:10086)
07-01 06:03:43.389: W/ActivityManager(535): 	at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:9637)
07-01 06:03:43.389: W/ActivityManager(535): 	at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:86)
07-01 06:03:43.417: I/jdwp(3008): Ignoring second debugger -- accepting and dropping
07-01 06:03:43.417: I/jdwp(1314): Ignoring second debugger -- accepting and dropping
07-01 06:03:43.417: D/Zygote(145): Process 3096 terminated by signal (11)
07-01 06:03:43.417: I/WindowState(535): WIN DEATH: Window{52b4aa3c u0 com.radio.fm/com.radio.fm.MainActivity}
