### ISSUE TITLE
getTrackCount returns always 0 or 1

### ISSUE THREAD

**Issue by don11995** [google/ExoPlayer#1233]
getTrackCount returns always 0 or 1, but tracks is more than 1. For example, in custom SubtitleParser player sees two audiotracks (mimeType), but if I call getTrackCount for audio it returns only one.

**Comment by AquilesCanta** [comment]
Can you please provide a stream?

**Comment by don11995** [comment]
It does not matter what kind of video is played, it always 1 or 0. ExoPlayer version 1.5.5. For example, this video: http://www.ex.ua/load/195128973. It has two audio streams.

**Comment by ojw28** [comment]
VLC thinks it only has one audio track. How have you determined that it has two?

Perhaps you're misunderstanding what a track is in this case. A track is a completely separate audio stream, so for example, if you have English and French audio tracks, then in that case there would be two of them. If you're interested in audio channels (e.g. mono v.s. stereo), you should query that using `ExoPlayer.getTrackFormat` to get the format, then look at `MediaFormat.channelCount` to get the number of channels.

**Comment by AquilesCanta** [comment]
Sorry for the delay, but @ojw28  is right. There are only two tracks in this file. A video track and an audio track.
