### ISSUE TITLE
ExoPlayer.STATE_READY docs is outdated

### ISSUE THREAD

**Issue by kboyarshinov** [google/ExoPlayer#1235]
From current [ExoPlayer.STATE_READY  documentation](https://github.com/google/ExoPlayer/blob/master/library/src/main/java/com/google/android/exoplayer/ExoPlayer.java#L215):

> `The player is prepared and able to immediately play from the current position. The player will be playing if {@link #setPlayWhenReady(boolean)} returns true, and paused otherwise.`

But `setPlayWhenReady` returns nothing:
```
public void setPlayWhenReady(boolean playWhenReady);
```

**Comment by ojw28** [comment]
I think it's just a typo, and should say: `if {@link #getPlayWhenReady()} returns true`. Thanks for pointing it out!

**Comment by kboyarshinov** [comment]
you're welcome :+1:
