### ISSUE TITLE
Exoplayer leaks surfacetexture switching movies

### ISSUE THREAD

**Issue by AndrewDickerson** [google/ExoPlayer#1236]
Exoplayer leaks a Surfacetexture when switching movies because I can't seem to free the oes texture between movies.

**Comment by AquilesCanta** [comment]
Can you provide some more information? I would like to reproduce the leakage. Are you releasing the player between runs? You are instantiating a new surface per stream, I guess?

**Comment by ojw28** [comment]
Agreed; this issue is unclear. ExoPlayer doesn't own the surface (or SurfaceTexture). The surface is injected into the player by the application, which can also clear the surface. Please clarify.

**Comment by ojw28** [comment]
Closing due to lack of information.
