### ISSUE TITLE
Unable to Play Certain Stream 

### ISSUE THREAD

**Issue by lovishsindhwani** [google/ExoPlayer#1237]
Hi

I am trying to play following stream, But i am not able to play it on exo:

[http://servidor.i-live.com.ar:9234](url)

Here is error log, i got from logcat:

`02-06 17:19:17.907 32746-32746/com.google.android.exoplayer.demo W/System.err: com.google.android.exoplayer.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to http://servidor.i-live.com.ar:9234
02-06 17:19:17.908 32746-32746/com.google.android.exoplayer.demo W/System.err:     at com.google.android.exoplayer.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:193)
02-06 17:19:17.908 32746-32746/com.google.android.exoplayer.demo W/System.err:     at com.google.android.exoplayer.upstream.DefaultUriDataSource.open(DefaultUriDataSource.java:135)
02-06 17:19:17.908 32746-32746/com.google.android.exoplayer.demo W/System.err:     at com.google.android.exoplayer.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:97)
02-06 17:19:17.908 32746-32746/com.google.android.exoplayer.demo W/System.err:     at com.google.android.exoplayer.upstream.DataSourceInputStream.open(DataSourceInputStream.java:56)
02-06 17:19:17.908 32746-32746/com.google.android.exoplayer.demo W/System.err:     at com.google.android.exoplayer.upstream.UriLoadable.load(UriLoadable.java:92)
02-06 17:19:17.908 32746-32746/com.google.android.exoplayer.demo W/System.err:     at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
02-06 17:19:17.908 32746-32746/com.google.android.exoplayer.demo W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
02-06 17:19:17.908 32746-32746/com.google.android.exoplayer.demo W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
02-06 17:19:17.908 32746-32746/com.google.android.exoplayer.demo W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
02-06 17:19:17.908 32746-32746/com.google.android.exoplayer.demo W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
02-06 17:19:17.908 32746-32746/com.google.android.exoplayer.demo W/System.err:     at java.lang.Thread.run(Thread.java:818)
02-06 17:19:17.908 32746-32746/com.google.android.exoplayer.demo W/System.err: Caused by: java.net.UnknownHostException: Unable to resolve host "servidor.i-live.com.ar": No address associated with hostname
02-06 17:19:17.908 32746-32746/com.google.android.exoplayer.demo W/System.err:     at java.net.InetAddress.lookupHostByName(InetAddress.java:470)
02-06 17:19:17.908 32746-32746/com.google.android.exoplayer.demo W/System.err:     at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
02-06 17:19:17.908 32746-32746/com.google.android.exoplayer.demo W/System.err:     at java.net.InetAddress.getAllByName(InetAddress.java:215)
02-06 17:19:17.908 32746-32746/com.google.android.exoplayer.demo W/System.err:     at com.android.okhttp.internal.Network$1.resolveInetAddresses(Network.java:29)
02-06 17:19:17.908 32746-32746/com.google.android.exoplayer.demo W/System.err:     at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:188)
02-06 17:19:17.908 32746-32746/com.google.android.exoplayer.demo W/System.err:     at com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:157)
02-06 17:19:17.908 32746-32746/com.google.android.exoplayer.demo W/System.err:     at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:100)
02-06 17:19:17.908 32746-32746/com.google.android.exoplayer.demo W/System.err:     at com.android.okhttp.internal.http.HttpEngine.createNextConnection(HttpEngine.java:357)
02-06 17:19:17.908 32746-32746/com.google.android.exoplayer.demo W/System.err:     at com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:340)
02-06 17:19:17.908 32746-32746/com.google.android.exoplayer.demo W/System.err:     at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:330)
02-06 17:19:17.908 32746-32746/com.google.android.exoplayer.demo W/System.err:     at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:248)
02-06 17:19:17.908 32746-32746/com.google.android.exoplayer.demo W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:437)
02-06 17:19:17.909 32746-32746/com.google.android.exoplayer.demo W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:114)
02-06 17:19:17.909 32746-32746/com.google.android.exoplayer.demo W/System.err:     at com.google.android.exoplayer.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:414)
02-06 17:19:17.909 32746-32746/com.google.android.exoplayer.demo W/System.err:     at com.google.android.exoplayer.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:341)
02-06 17:19:17.909 32746-32746/com.google.android.exoplayer.demo W/System.err:     at com.google.android.exoplayer.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:191)
02-06 17:19:17.909 32746-32746/com.google.android.exoplayer.demo W/System.err: 	... 10 more
02-06 17:19:17.909 32746-32746/com.google.android.exoplayer.demo W/System.err: Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
02-06 17:19:17.913 32746-32746/com.google.android.exoplayer.demo W/System.err:     at libcore.io.Posix.android_getaddrinfo(Native Method)
02-06 17:19:17.914 32746-32746/com.google.android.exoplayer.demo W/System.err:     at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:55)
02-06 17:19:17.914 32746-32746/com.google.android.exoplayer.demo W/System.err:     at java.net.InetAddress.lookupHostByName(InetAddress.java:451)
02-06 17:19:17.914 32746-32746/com.google.android.exoplayer.demo W/System.err: 	... 25 more`

Please look into this once..

Thanks

**Comment by andrewlewis** [comment]
`java.net.UnknownHostException: Unable to resolve host "servidor.i-live.com.ar": No address associated with hostname` looks like the cause. Make sure the device has a working internet connection and the app has permission to access the network. Is it just this specific stream that doesn't load, or do other URLs not load either?

**Comment by lovishsindhwani** [comment]
@andrewlewis 

Yes device has Internet Permission and other streams are working as well. 

Only this stream is causing problem on same network.

**Comment by ojw28** [comment]
The sample plays fine in the ExoPlayer demo app, if I add it to Samples.java as:

```
    new Sample("Test",
        "http://servidor.i-live.com.ar:9234", Util.TYPE_OTHER),
```

As Andrew notes, the root cause looks like a networking issue rather than an issue with the player. Please also try with the latest version of ExoPlayer, to be sure.

**Comment by lovishsindhwani** [comment]
@ojw28 

Thanks for update..

I have tried same stream with multiple Internet Service Providers(ISP)....Looks like this stream link is not working one ISP and others networks are playing this stream link smoothly just like your example.

So can we use some workaround for this situation or we have to rely on ISP.

**Comment by ojw28** [comment]
I doubt there is anything we can do to work around this particular issue.
