### ISSUE TITLE
com.google.android.exoplayer.ExoPlaybackException: java.io.IOException: Failed to instantiate extractor

### ISSUE THREAD

**Issue by bkjbkjbnkj687698698** [google/ExoPlayer#1239]
I am using below code to play video using EXOPlayer but it doesn't plays.

Video is in `mp4` format.Where am I going wrong?
Its showing error-

    com.google.android.exoplayer.ExoPlaybackException: java.io.IOException: Failed to instantiate extractor.

Code-

    loadvideo("res:/" + R.raw.samplevider);
    
    
    private void loadvideo(String path) {
        player = ExoPlayer.Factory.newInstance(2, 1000, 5000);
        Uri uri = Uri.parse(path);
        sampleSource = new FrameworkSampleSource(getActivity().getApplicationContext(), uri, null);
        // 1. Instantiate the player.
        // 2. Construct renderers.
        videoRenderer = new MediaCodecVideoTrackRenderer(getActivity().getApplicationContext(),sampleSource, MediaCodecSelector.DEFAULT, MediaCodec.VIDEO_SCALING_MODE_SCALE_TO_FIT_WITH_CROPPING);
        audioRenderer = new MediaCodecAudioTrackRenderer(sampleSource,MediaCodecSelector.DEFAULT);
        // 3. Inject the renderers through prepare.
        player.prepare(videoRenderer, audioRenderer);
        // 4. Pass the surface to the video renderer.
        player.sendMessage(videoRenderer, MediaCodecVideoTrackRenderer.MSG_SET_SURFACE, surfaceView.getHolder().getSurface());
        // 5. Start playback.
        player.setPlayWhenReady(true);
    }

**Comment by ojw28** [comment]
`FrameworkSampleSource` has been deprecated for a long time. You should be using `ExtractorSampleSource`. The demo app in this repository already has samples of mp4 playback, so you should use that as a starting point.
