### ISSUE TITLE
AES Encrypted offline file not playing

### ISSUE THREAD

**Issue by naveenmishra** [google/ExoPlayer#1241]
I am palying an AES encrypted audio only file using ExoPlayer (I am using Cipher to encrypt file in encoding format AES-ECB). I am using ExtracterRendererBuilder and have created my own DataSource for playing these encrypted files. In read(..) method of my DataSource, I am reading data from CipherInputStream. But this leads to "discontinuity detected" error and no audio is playing. 

Error: 
- AAC decoder returned error 0x4004, substituting silence
- AudioTrack: Discontinuity detected [expected 4829751, got 4620769]  

Please suggest.

**Comment by ojw28** [comment]
Most likely your custom components are not encrypting/decrypting correctly. Note that your DataSource needs to handle requests for data at arbitrary position offsets. A common source of errors when implementing this kind of thing is not accounting for padding added during encryption. You might like to try using `AES/CTR/NoPadding`, which is pretty well suited to this use case.
