### ISSUE TITLE
android.exoplayer.ParserException: Offset to sample data was negative.

### ISSUE THREAD

**Issue by abhiguru** [google/ExoPlayer#1242]
Randomly on seek events I am getting the error "Offset to sample data was negative." Same track seek would work 90% of the time and sometimes it throws the error in the gist below.  Race condition ? Any hints on what might be causing it ?

https://gist.github.com/abhiguru/bdd52dc7abb0c7bbdabc

**Comment by ojw28** [comment]
I think this was fixed in 1.5.4, in this change: https://github.com/google/ExoPlayer/commit/030f26fd2d1c381f35bbed0be0f1746be3625ed9. What version are you using?

**Comment by ojw28** [comment]
Closing. Please let us know if this still occurs on 1.5.4 or later.
