### ISSUE TITLE
Overriding seekTo in TrackRenderer

### ISSUE THREAD

**Issue by Viddi** [google/ExoPlayer#1243]
Hi,

I just updated from 1.5.3 to 1.5.5 and noticed that `final` was added to the seekTo method inside `SampleSourceTrackRenderer`:

https://github.com/google/ExoPlayer/blob/master/library/src/main/java/com/google/android/exoplayer/SampleSourceTrackRenderer.java#L117

Is there a specific reason to why this was added? I was overriding this method to listen to seek events.

Thanks.

**Comment by ojw28** [comment]
Overriding `seekTo` just to listen for seek events doesn't sound like the right thing to be doing. The only thing that can invoke a seek operation is your own code, so you shouldn't need to listen for seek events as such. Why don't you just implement listener logic in your own code at the point where you call seekTo (in the demo application, this would be equivalent to notifying listeners from `DemoPlayer.seekTo`.

**Comment by Viddi** [comment]
I'm working on a library that needs to provide these callbacks out of the box. One of them is a callback for any seek that happens during playback, not just for one particular seek. I decided to go this route since ExoPlayer operates on a separate thread. Calling `DemoPlayer.seekTo`, and then invoking the callback right after, might not guarantee that the `seekTo` has completely finished by the time the listener is invoked.

Correct me if I'm wrong, but at least by overriding `TrackRenderer`'s `seekTo` method (all I do is call super and then invoke the callback), I should always know that seek has happened for certain.

**Comment by ojw28** [comment]
> I'm working on a library that needs to provide these callbacks out of the box. One of them is a callback for any seek that happens during playback, not just for one particular seek

So encapsulate the ExoPlayer class with a wrapper class, like DemoPlayer in the demo application. Once you have a wrapper you can guarantee that all seek calls must be made through it, which gives you a single point at which to implement listener logic.

> Calling DemoPlayer.seekTo, and then invoking the callback right after, might not guarantee that the seekTo has completely finished by the time the listener is invoked.

What's the use case where it's important that the listeners aren't notified early, given they'll only be early by a matter of milliseconds?

**Comment by Viddi** [comment]
I have a wrapper class based on DemoPlayer already. Is invoking the callback inside `seekTo` in DemoPlayer effectively the same thing as invoking it in the `TrackRenderer` override?

**Comment by ojw28** [comment]
You're right that it will happen slightly earlier if done this way, but I really wouldn't expect it to make any difference unless you have very specific requirements (i.e. an unusual use case). The listeners will be invoked on a more sensible thread, also. So yes, I'd recommend you do it that way.

**Comment by Viddi** [comment]
I have pretty strict requirements regarding this case, since I'm using two instances of ExoPlayer, one for content, and one for client side ads. If you recommend that I just invoke the callback in DemoPlayer, then I'll leave it at that. What was the motivator to add final to `seekTo` anyway?

**Comment by ojw28** [comment]
- It's unclear that the requirement you have is sufficiently strict for it to matter. The difference really should be very small. So yes, just invoke the callback in `DemoPlayer`. If that doesn't work for some reason, then feel free to reply again here with more information!
- The motivator behind making more things final to stop people from extending parts of the library that were not intended to be extended, in ways that are likely to be error prone. In my opinion what you were doing sounds pretty error prone (particularly if you were invoking listeners directly from ExoPlayer's thread rather than posting back onto the application's main thread).
