### ISSUE TITLE
Add support for H.263 in FlvExtractor

### ISSUE THREAD

**Issue by arjuntu** [google/ExoPlayer#1244]
hi,
 I am trying to play a this flv video 
http://www.sample-videos.com/video/flv/240/big_buck_bunny_240p_2mb.flv, in exoplayer sample code.
But this error occurs as shown in below screenshot
![screenshoterror](https://cloud.githubusercontent.com/assets/9511283/12909516/9026dd06-cf27-11e5-9a1b-009f8f98d09f.jpg)
same  flv video of some resolutions are playing and some are not playing from the same site.
Any help.
Thanks in advance.

**Comment by andrewlewis** [comment]
That video has an H.263 stream but the FlvExtractor only supports H.264/AVC at the moment.

**Comment by arjuntu** [comment]
thanku andrewlewis. is their any way i can make it play??

**Comment by andrewlewis** [comment]
I don't think there is a quick fix to make it play.

@jeoliva originally contributed the FlvExtractor and may have an idea of what is involved in implementing this. It will be fairly similar to H.264, but it looks like H.263 does not use codec specific data so the width/height would need to be read separately (using ScriptTagPayloadReader to look up width/height elements, perhaps?).

**Comment by arjuntu** [comment]
ok. thanks again

**Comment by ojw28** [comment]
I don't think there's sufficient demand to warrant spending time on this issue. Closing.
