### ISSUE TITLE
HEVC 4k plays choppy

### ISSUE THREAD

**Issue by abhiguru** [google/ExoPlayer#1245]
Hello,

 API level 19, HEVC 4k playback using the default adaptive logic video encoded to 20Mbps bitrate I am seeing a lot of pauses, I checked and bandwidth is okay but the request being made by the player are not continuous despite empty buffer http://imgur.com/SwTDUyb

Any suggestions on what can be changed in the adaptive logic ?

**Comment by ojw28** [comment]
I'm pretty surprised any device running API level 19 even has an HEVC decoder. It was only a requirement from API level 21. I think you'd be better off using H264; HEVC is pretty new, relatively speaking, and so you shouldn't expect rock solid compatibility with older devices.

**Comment by abhiguru** [comment]
Actually, the SoC was "relatively" recently released. It is the firmware that needs to catchup.. being a new fab... API 21 and 22 ports are a little buggy so using API 19 which is working pretty solid with Exo (Did change the getViewportSize() to allow for 4k) except for this Adaptive logic that might need some tweaking. 

While we are on the topic, it seems the MPEG-DASH MPD support multiple base URL (multiple CDN) does the adaptive logic of Exoplayer take that into consideration while deciding where to pull the next chunk from ? 

The device is a video streaming device so it is okay to saturate the full available bandwidth for fetching video data can you suggest the changes I can do in that direction? 

One more question if I may, When you seek back to the content that is already viewed once instead of fetching it again maybe store it in a larger buffer for a bit, It is not an issue with 1080p but when you are on a 4k video and you seek back it is a little painful to watch the same chunks slowly streamed again.

**Comment by ojw28** [comment]
I'm pretty sure the bottom three paragraphs are all covered in existing issues in this tracker.

As for the initial issue here, it's unclear what "pause" means in the context, and you haven't provided a bug report or information about the device. Please file a fresh issue with complete information as described [here](https://google.github.io/ExoPlayer/2015/10/01/reporting-issues.html).
