### ISSUE TITLE
Support playback of WAV audio files

### ISSUE THREAD

**Issue by stangabogdan** [google/ExoPlayer#1246]
How can I play WAV audio files in the ExoPlayer?

**Comment by marcbaechinger** [comment]
You can't. 

ExoPlayer currently is focused on DASH, SmoothStreaming and HLS streaming formats. Besides this there is support for some 'standalone' formats including MP3 which are supported via ExtractorSampleSource. 

You can find the available Extractors here: https://github.com/google/ExoPlayer/blob/master/library/src/main/java/com/google/android/exoplayer/extractor/ExtractorSampleSource.java#L103

**Comment by ojw28** [comment]
Yes, we don't support WAV at this point in time. We may do so in the future, but it's not a priority.

**Comment by ojw28** [comment]
Opening this to track adding WAV support, since we have an internal contribution under review that will add support.

**Comment by ojw28** [comment]
Support for 16bit WAV files is now in the dev branch. Changes:
020a9759841da74e983fac48ea1d2e9af0dc7bbe
ef680e9ea6ad1148ab7142156cd5ccf010caaae6
402a00b48bbdf3ccbbda6bc8ae489a7aee3edb9e
41dbb3415022dc8c88e8bee86b27af91be1c2797

**Comment by ojw28** [comment]
NB - Issue most likely needs to remain open until we also support 8bit and 24bit, at which point it can be closed.

**Comment by ojw28** [comment]
8bit and 24bit is supported as of https://github.com/google/ExoPlayer/commit/de1ccea3756f28a74922db3a15c92bd68cde3829.
