### ISSUE TITLE
Refactor MediaCodecVideoTrackRenderer to avoid passing down Context

### ISSUE THREAD

**Issue by ptran-gpfw** [google/ExoPlayer#1247]
Would it be possible to refactor MediaCodecVideoTrackRenderer and remove the Context parameter from the constructor ([MediaCodecVideoTrackRenderer.java#L198](https://github.com/google/ExoPlayer/blob/e8073e3570d18b9765da6b5e3573fb564e1a3fdd/library/src/main/java/com/google/android/exoplayer/MediaCodecVideoTrackRenderer.java#L198-L198))?

Its only needed to to retrieve the system refresh rate ([VideoFrameReleaseTimeHelper.java#L202](https://github.com/google/ExoPlayer/blob/c31473c5964a6f1faa75934d31d8b333e99e712c/library/src/main/java/com/google/android/exoplayer/VideoFrameReleaseTimeHelper.java#L202-L202)).

According to [Law of Demeter](http://misko.hevery.com/2008/07/18/breaking-the-law-of-demeter-is-like-looking-for-a-needle-in-the-haystack/), it seems better to have the client pass in the refresh rate as a float.

**Comment by ojw28** [comment]
I don't think we want to do that. There are other things we'll likely need a `Context` for in the renderer classes in the future. Addressing a few points in the article specifically:

> Your JavaDoc is not very useful! Yes, by examining the API I can see that the Mechanic needs Context, but Context is the kitchen sink. What does the mechanic really need? (If you don’t have source code nearby than it may be hard to figure out).

I'd argue that there are cases where a caller shouldn't care what the context is being used for, and that this is one such case. Developers shouldn't need to figure out how to retrieve the refresh rate themselves; and requiring them to do this leaves room for subtle bugs that might occur should they implement it incorrectly. We could provide a util method to help, but there's still room for error. It should also be noted that there's no value in using anything other than the true refresh rate in this case, and hence providing the flexibility to do so does not achieve anything.

> Even if you don’t plan to reuse the code, the Context has high coupling with the rest of the system. Coupling is transitive, this means Mechanic inherits all of the badness through association.

This seems like a throwaway paragraph that doesn't actually mean anything. What is the "badness" and is it "inherited through association"?

The one really solid argument for injecting exactly what you need is ease of testing, but ExoPlayer is pretty far from that goal in any case. In some cases there are real test-ability vs performance trade-offs, and we opt for performance in those cases.
