### ISSUE TITLE
seamless/gapless mp4 (h264) loop

### ISSUE THREAD

**Issue by mjsibbald** [google/ExoPlayer#1249]
So we need like 20 sec loops, and on some phone this is the case with exoplayer. 
But is seems like at the end there is always a some sort of flush. 

Is there anybody that can advise me on this one. There is sometimes a half a sec delay (seek to 0 and resume). we need zero! 

I've seen people talking about using 2 instances queued which I think it over complicating things. Apple Avplayer has this AVMutableComposition, which works very good.

Thanks!

**Comment by andrewlewis** [comment]
This feature request will be addressed as part of playlist support in #1270. Seamless looping should be possible once that is implemented, though further optimizations for this specific use case may be possible.
