### ISSUE TITLE
loadError

### ISSUE THREAD

**Issue by abhiguru** [google/ExoPlayer#1251]
Hey,

 I have an MPD http://video.vcu.tv/134373_e46fa5a01d4819072a9b53667ff15b2f/134373.mpd, It should be generated with 24 segments but was instead generated with 23.999999998 due to a precision error which happens on some platform if the values get calculated in a certain way.  I have a bug filed with the encoder API to get the precision issue fixed so that 24 are generated as they should.. 

My question here is once the Exo player gets into the load error state, If I hit rewind and seek back to a segment that does exists and was played correctly the player won't play the segment again is this by design or is it something that can be changed ? 

https://gist.github.com/abhiguru/efe59963fc45d1535604

**Comment by ojw28** [comment]
- Having ExoPlayer handle a missing last segment without failure is tracked in #836, but yes, technically it's a content issue and the encoder should be fixed to not do this.
- The only way to recover is to prepare the player again following the failure; seeking isn't enough.
