### ISSUE TITLE
RTSP stream from external camera.

### ISSUE THREAD

**Issue by Anshumansharma12** [google/ExoPlayer#1254]
Hello i want to do live stream from one external camera. Camera is providing only RTSP stream. I was try to use "ExoPlayer" but its getting failed. Can you please help me out.

**Comment by abhiguru** [comment]
https://github.com/google/ExoPlayer/issues/55

**Comment by Anshumansharma12** [comment]
this post very old one jan-2015. so i want to know that its possible now? I really need it.

**Comment by andrewlewis** [comment]
As @abhiguru says, this is already tracked in #55 (and we don't currently support RTSP).

**Comment by abhiguru** [comment]
@Anshumansharma12  in the meanwhile either you can help implement support for it on Exo or look at alternative like javac + ffmpeg

**Comment by hosek** [comment]
Im doing alternative control app for SJCam (SJCam is using rtsp for preview) and I would recommend you VLC, it works like charm (if you dont mind, that vlc libraries are pretty big)

**Comment by juliusfriedman** [comment]
I have a project @ http://net7mma.codeplex.com/ which can provide a solution for Rtp and Rtsp playback.

The project is Mono / Android compatible and is very CPU and Memory Efficient.

There is a RtspServer as well as RtspClient and RtpClient implementations.

You can hook up any supported codec which is accessible through MediaCodec or you can implement your own.
