### ISSUE TITLE
Get duration of online mp3 file

### ISSUE THREAD

**Issue by PavelKorolev** [google/ExoPlayer#1255]
I wonder when it's safe to `getDuration()` of the audio track. I just need it once as fast as possible. 
When I try to get it immediately after `exoPlayer.prepare()` then I get `UNKNOWN_TIME`.
Didn't find an example in demo project. 
Looks like I need to do it in listener when playback status changed to `ExoPlayer.STATE_READY`, but then there will be useless getDuration on each play/pause action.

**Comment by ojw28** [comment]
If your code is going to have useless calls on each action, why don't you just have a boolean so that you only do it once?

**Comment by PavelKorolev** [comment]
It's okay, but thought there should be a cleaner way to call it once when player prepared, like in onPrepared() method of android default MediaPlayer. Thanks anyway.
