### ISSUE TITLE
Regression: certain Widewine-protected Dash streams no longer play

### ISSUE THREAD

**Issue by perchrh** [google/ExoPlayer#1256]
The error message is "W/MediaPresentationDescriptionParser: Skipped unsupported ContentProtection element".
Reverting commit 264d8d2406a7d7591a677f58b2221b928be8f595, makes the stream work again. 
This is a stream with pssh box version 0, created with the Harmonic encoder. 

In the stream that doesn't play, there is no pssh box in the manifest file, it's inside the init data of the mp4  file. The stream is multi-drm, with Widewine being one of the protection schemes. The files necessary to reproduce the issue are available at the url below. 

https://drive.google.com/file/d/0B-MiKMsYx1iHaURCazE4bkxTTmdYOG90QkhLWE16MHdDUWtv/view?usp=sharing

Looking at the changes in the commit, my theory is that the issue comes from not always returning the 'data' in parseContentProtection, maybe some checks in the current code are over-zealous.

**Comment by ojw28** [comment]
I think the change referenced above should fix this issue, but please could you verify.

**Comment by perchrh** [comment]
Fix confirmed! Thanks and feel free to use the supplied test data for automated tests if desired :)
