### ISSUE TITLE
Distortion playing MP4 in TextureView on some devices

### ISSUE THREAD

**Issue by edikfuks** [google/ExoPlayer#1260]
I am experiencing some distortion playing mpr4 video on Moto G (L 5.0.2) Exoplayer version 1.5.5. No exceptions are raised during the playback.
Initially the video plays fine, but after several seconds of playback the distortion starts.
Also, I am able to reproduce this issue when pausing the application and resuming it with the playing video. The application resumes with the distorted video.
Did anybody have a similar issue or has a solution to such video bug? Looks like there is some kind of  rendering issue.
![screenshot_2016-02-12-18-46-51](https://cloud.githubusercontent.com/assets/2530502/13024214/a65c6754-d1a6-11e5-889a-0dd67f806096.png)
![screenshot_2016-02-12-18-46-44](https://cloud.githubusercontent.com/assets/2530502/13024217/a8bdf0da-d1a6-11e5-947f-13bcfb405ed0.png)
![screenshot_2016-02-12-18-46-41](https://cloud.githubusercontent.com/assets/2530502/13024218/ad4f547c-d1a6-11e5-814a-32d360f34723.png)
![screenshot_2016-02-12-15-52-10](https://cloud.githubusercontent.com/assets/2530502/13024225/bd5a568c-d1a6-11e5-823a-0df100c988c2.png)
![screenshot_2016-02-12-18-39-42](https://cloud.githubusercontent.com/assets/2530502/13024228/c9072ca8-d1a6-11e5-9bfc-0dcc7a8ecd30.png)

**Comment by ojw28** [comment]
Does the issue reproduce with the streams in the demo app, if you switch it over to using TextureView?

**Comment by edikfuks** [comment]
Hello, @ojw28 !
Tried with the DemoPlayer and could reproduce this issue. Not sure what could cause the issue in my project after pausing and resuming the app
