### ISSUE TITLE
Multi Track Source for MP4 files. (Non-Adaptive)

### ISSUE THREAD

**Issue by jpshelley** [google/ExoPlayer#1261]
I was hoping to create a feature that allowed the user to switch between different video urls (Think SD --> HD). However we are not using adaptive capabilities at the moment such as DASH.
Is there a way to use a Multi Track Sample to send to the `MediaCodecVideoTrackRenderer` with multiple remote `.mp4` url files, and use the `getTrack()` methods to determine the possible urls given to the player?

Right now I have a hack-ish attempt at just restarting the Exo Player when we want to switch urls and there is always a bit of a lag due to the startup cost.

**Comment by ojw28** [comment]
If you're just using normal MP4 files, it's hard to see how a player could do significantly better than what you're doing already. There's always going to be a cost when a user manually switches from one stream to another, unless you would have the player continually buffer twice as much data just in case the user switches (this is not something we support).

**Comment by jpshelley** [comment]
@ojw28 Makes sense, I thought I'd ask just in case. Thanks.
