### ISSUE TITLE
Is there a method to limit the downloading bandwidth

### ISSUE THREAD

**Issue by wbo4958** [google/ExoPlayer#1262]
Guys, You know, Some new features need to limit the network bandwidth of exoplayer, is there a method to do some flow control?

expecting for quick reply,
Best Regards,

**Comment by ojw28** [comment]
Is this in the context of HLS, DASH, or something else? Please could you provide a little more information about what you're trying to achieve? Thanks.

**Comment by wbo4958** [comment]
Thx ojw28, It's  Extractor, I just want to limit the downloading speed.

**Comment by ojw28** [comment]
I'm not really sure what you're trying to achieve. If you restrict the bandwidth to less than the bandwidth of the media then you'll end up with repeated re-buffers. If you restrict the bandwidth to more than the bandwidth of the media, then it's unclear what you're actually achieving?

**Comment by wbo4958** [comment]
Hi ojw28,  You know, when I specify a mp3 URL to Exoplayer, Exoplayer will download the mp3 and cache to play, right? right now, some extra functions will use the whole internet bandwidth, so I need to "pause" the downloading procedure.

**Comment by ojw28** [comment]
We don't support that, no. It's possible to extend ExoPlayer to add support for this yourself though. A nice approach would be to implement a `DataSource` that wraps another `DataSource`, calling through to its methods but blocking for as long as some flag is set.. Note that you'd need to ensure sufficient synchronization around the flag.
