### ISSUE TITLE
How to set video source with m3u8 file?

### ISSUE THREAD

**Issue by vincent-law** [google/ExoPlayer#1264]
I need to assemble some uri path which represents a series video part into a m3u8 file.
But I don't find where to set this file to exoplayer?

**Comment by vincent-law** [comment]
In other words ,how can i set a m3u8 playlist to exoplayer?

**Comment by ojw28** [comment]
The demo app has examples of playing m3u8 HLS playlists; please take a look and use that as a starting point.
