### ISSUE TITLE
Is there a phonegap/cordova plugin using exoplayer?

### ISSUE THREAD

**Issue by cyclonmaster** [google/ExoPlayer#1265]
Is there a phonegap/cordova plugin using this exoplayer?

I know only vitamio plugin.

**Comment by ojw28** [comment]
I can't say that there isn't one anywhere, since anyone could have written one. But I can say that there's nothing officially supported.

**Comment by go2hyder** [comment]
[https://github.com/frontyard/cordova-exoplayer-plugin](https://github.com/frontyard/cordova-exoplayer-plugin)

Its working fine

**Comment by cyclonmaster-zz** [comment]
Wah! Thank you for the note
