### ISSUE TITLE
issues with in-stream SmoothStream captions

### ISSUE THREAD

**Issue by bartsidee** [google/ExoPlayer#1266]
playback of SmoothStreaming content with in-stream (dfxp) captions seems to be broken, the captions are correctly parsed and are returned on the getTrackCount and getTrackFormat methods, but when a text track is enabled with 

    setSelectedTrack(Player.TYPE_TEXT, index)

the player will stall in a buffering state in about 2-8s after the track is enabled. 

    ExoPlayer.STATE_BUFFERING

when captions are disabled playback continues without any issues

     setSelectedTrack(Player.TYPE_TEXT, -1)

I'm using the below to initialise the text renderer:

          DataSource textDataSource = new DefaultUriDataSource(context, bandwidthMeter, userAgent);
          ChunkSource textChunkSource = new SmoothStreamingChunkSource(manifestFetcher,
                  DefaultSmoothStreamingTrackSelector.newTextInstance(),
                  textDataSource, null, LIVE_EDGE_LATENCY_MS);
          ChunkSampleSource textSampleSource = new ChunkSampleSource(textChunkSource, loadControl,
                  TEXT_BUFFER_SEGMENTS * BUFFER_SEGMENT_SIZE, mainHandler, player,
                  DemoPlayer.TYPE_TEXT);
          textRenderer = new TextTrackRenderer(textSampleSource, player,
                  mainHandler.getLooper());

tested with: Exoplayer v1.5.5
notice: external captions are working correctly

**Comment by ojw28** [comment]
We have a few test samples with captions of this type, and they're working fine for me. Please could you provide a link to test content so that we can reproduce? Thanks.

**Comment by bartsidee** [comment]
Unfotunatly our current test stream has DRM protection, we have a non-DRM sample stream but that is working correctly.

After a side-by side comparison of the 2 streams I did noticed a minor difference in the header of the file:

None working file
Lmoofmfhd4traftfhd��trunT�mdat<?xml version="1.0" encoding="UTF-8"?><tt xml:lang="eng" xmlns="http://www.w3.org/ns/ttml" xmlns:tts="http://www.w3.org/ns/ttml#styling" xmlns:smpte="http://www.smpte-ra.org/schemas/2052-1/2010/smpte-tt" ><head>
<smpte:information smpte:mode="Enhanced" />
<styling>
<style xml:id="emb" tts:fontSize="4.1%" tts:fontFamily="monospaceSansSerif" />
<style xml:id="ttx" tts:fontSize="3.21%" tts:fontFamily="monospaceSansSerif"/>
<style xml:id="backgroundStyle" tts:fontFamily="proportionalSansSerif" tts:fontSize="18px" tts:textAlign="center" tts:origin="0% 66%" tts:extent="100% 33%" tts:backgroundColor="rgba(0,0,0,0)" tts:displayAlign="center" />
<style xml:id="speakerStyle" style="backgroundStyle" tts:color="white" tts:textOutline="black 1px" tts:backgroundColor="transparent" />
<style xml:id="textStyle" style="speakerStyle" tts:color="white" tts:textOutline="none" tts:backgroundColor="black" />
</styling><layout>
<region xml:id="full" tts:origin="0% 0%" tts:extent="100% 100%" tts:zIndex="1" />
<region xml:id="speaker" style="speakerStyle" tts:zIndex="1" />
<region xml:id="background" style="backgroundStyle" tts:zIndex="0" />
</layout>
</head><body><div>

</div></body></tt>

**Comment by ojw28** [comment]
We don't support DRM protected captions. See https://github.com/google/ExoPlayer/issues/718.

**Comment by bartsidee** [comment]
Unfotunatly our current test stream has DRM protection, we have a non-DRM sample stream but that is working correctly.

After a side-by side comparison of the 2 streams I did noticed a minor difference in the binary header of the file:

None working caption file

     Lmoof�mfhd�4traf�tfhd�������trun��T��mdat<?xml version="1.0" encoding="UTF-8"?> <br> <style xml:id="ttx" tts:fontSize="3.21%" tts:fontFamily="monospaceSansSerif"/><br> <style xml:id="backgroundStyle" tts:fontFamily="proportionalSansSerif" tts:fontSize="18px" tts:textAlign="center" tts:origin="0% 66%" tts:extent="100% 33%" tts:backgroundColor="rgba(0,0,0,0)" tts:displayAlign="center" /><br> <style xml:id="speakerStyle" style="backgroundStyle" tts:color="white" tts:textOutline="black 1px" tts:backgroundColor="transparent" /><br> <style xml:id="textStyle" style="speakerStyle" tts:color="white" tts:textOutline="none" tts:backgroundColor="black" /><br> </styling><layout><br> <region xml:id="full" tts:origin="0% 0%" tts:extent="100% 100%" tts:zIndex="1" /><br> <region xml:id="speaker" style="speakerStyle" tts:zIndex="1" /><br> <region xml:id="background" style="backgroundStyle" tts:zIndex="0" /><br> </layout><br> </head><body><div></p>  <p></div></body></tt></p>

Working caption file:

    Lmoofmfhd4traftfhd�&�trunT&�mdat<?xml version="1.0" encoding="UTF-8"?><tt xml:lang="eng" xmlns="http://www.w3.org/ns/ttml" xmlns:tts="http://www.w3.org/ns/ttml#styling" xmlns:smpte="http://www.smpte-ra.org/schemas/2052-1/2010/smpte-tt" ><head>
<smpte:information smpte:mode="Enhanced" />
<styling>
<style xml:id="emb" tts:fontSize="4.1%" tts:fontFamily="monospaceSansSerif" />
<style xml:id="ttx" tts:fontSize="3.21%" tts:fontFamily="monospaceSansSerif"/>
<style xml:id="backgroundStyle" tts:fontFamily="proportionalSansSerif" tts:fontSize="18px" tts:textAlign="center" tts:origin="0% 66%" tts:extent="100% 33%" tts:backgroundColor="rgba(0,0,0,0)" tts:displayAlign="center" />
<style xml:id="speakerStyle" style="backgroundStyle" tts:color="white" tts:textOutline="black 1px" tts:backgroundColor="transparent" />
<style xml:id="textStyle" style="speakerStyle" tts:color="white" tts:textOutline="none" tts:backgroundColor="black" />
</styling><layout>
<region xml:id="full" tts:origin="0% 0%" tts:extent="100% 100%" tts:zIndex="1" />
<region xml:id="speaker" style="speakerStyle" tts:zIndex="1" />
<region xml:id="background" style="backgroundStyle" tts:zIndex="0" />
</layout>
</head><body><div></p>  <p></div></body></tt></p>

could the header be the cause?

(notice captions are not drm protected)

**Comment by ojw28** [comment]
We don't support DRM protected captions. See https://github.com/google/ExoPlayer/issues/718.

**Comment by ojw28** [comment]
Although your non-working caption file doesn't look particularly as though it does have DRM protection...

**Comment by bartsidee** [comment]
the caption are **not** DRM protected, just the audio and video fragments, but this makes it hard to share the stream in question.

**Comment by ojw28** [comment]
It should be fine just to share the protected version in that case; I can just disable the video and audio parts of the playback and look at why the subtitles are problematic.

**Comment by bartsidee** [comment]
ok great! I have forwarded the stream url to dev.exoplayer@gmail.com

**Comment by ojw28** [comment]
Are the segments geo-restricted to some region? I keep getting 503 errors when I try and obtain them. Thanks.

**Comment by ojw28** [comment]
I was able to get at them through a US proxy. I can't reproduce the problem though. To test them I did the following:

1. Checked out 1.5.5 (i.e. the current master branch).
1. Added your URL to `Samples.java` of the demo app with type `TYPE_SS`.
1. In `SmoothStreamingRendererBuilder`, commented out the blocks that create the `DrmSessionManager`, video and audio renderers, and instead set `videoRenderer` and `audioRenderer` to null.
1. Play the sample in the demo app, enabling the text track by tapping on the text button.

It appears that the captions play fine in this environment, having tested the first 5 minutes. Does this work for you? Are you able to play the full media in the demo app if you update `SmoothStreamingTestMediaDrmCallback` to obtain a suitable key response? If so, it feels like the issue must be elsewhere in application code.

**Comment by bartsidee** [comment]
thank you for the feedback and verification; an interesting result let me take this back to run some additional test to:
1. rule out any form of application issue
2. verify if there is relation with the video/audio renderers

**Comment by bartsidee** [comment]
We have identified the cause of the issue, the problem was in the request of the closed caption manifest, the chunk url of the close caption contained a space, which was not correctly url encoded by exoplayer. As a result the caption chunk request failed and stalled the player in buffer state.

    GET {baseUrl}/QualityLevels(128000)/Fragments(Closed Captions=20020000)
    STATUS 400

A quick fix was made in the SmoothstreamingManifest on the RequestUri method to add url encoding (Uri.encode) on the chunkUrl. 
https://github.com/google/ExoPlayer/blob/master/library/src/main/java/com/google/android/exoplayer/smoothstreaming/SmoothStreamingManifest.java#L251.

    GET {baseUrl}/QualityLevels(128000)%2FFragments(Closed%20Captions%3D20020000) HTTP/1.1
    STATUS 200

I could imagine a patch on the UriUtil.resolve method would make it more generic for other parsers as well.

**Comment by ojw28** [comment]
This is actually a content issue, not an issue with ExoPlayer. Spaces in URLs are a bad idea in general (i.e. just don't do it). An example of a related issue on this tracker is https://github.com/google/ExoPlayer/issues/871.

For SmoothStreaming in particular, the specification explicitly states that you're not allowed to put unsafe characters into the Url attribute. If you drill down through the spec far enough you find that the part of the Url attribute that contains a space in your manifest is defined to consist of:

> URISAFE_IDENTIFIER_NONNUMERIC: A nonnumeric identifier that is safe for use in data fields
that are part of a URI [RFC2396].

**Comment by bartsidee** [comment]
Agreed that one can easily urlencode the base manifest (adaptive) or mp4 (progressive) before it is ingesting it in Exoplayer. This would be a simple on the application level.

But this can not be said on the chunks as they are generated by the exoplayer SDK. Apparently it is not uncommon to have spaces in chunk urls in the wild, so should exoplayer not be less strict on this matter in specific to chunk urls? 

As an example one can not expect parties to do a full re-encode of their content jsut because there is a space in the chunk url. As a result potentially different parties will have to apply patches to the exoplayer source to support such content which would be far from ideal

**Comment by ojw28** [comment]
Well, their content *explicitly* violates the SmoothStreaming specification. They also don't need to do a any re-encoding; they just need to adjust their manifests and rename the files?

If you have data to back up "not uncommon" and who these "different parties" are, then I guess we could discuss further. We haven't had any other major video providers come to us with this issue; most likely because they all correctly adhere to the specification.

**Comment by ojw28** [comment]
It may also work (and be specification compliant) to leave the files where they're located and simply update the manifests such that the url strings are already properly encoded. Don't take my word for it though!
