### ISSUE TITLE
Loading webvtt subtitle outside the HLS manifest

### ISSUE THREAD

**Issue by amitsamal** [google/ExoPlayer#1267]
Hi Team,

We were using exoplayer 1.4.2 version and subtitles were externally loading of type webvtt instead of manifest. But now when we are trying to migrate to 1.5.5 version of exoplayer we see lot of changes to the implementation. We implemented Sample source and exoplayercomponent , they seemed to be modified along with multitrackchunksource too. We loaded our external subtitles are extra renderers apart from Video and audio renderer. Please help us in this regard.

Thanks & Regards
Amit Samal

**Comment by ojw28** [comment]
Sideloading subtitles in 1.5.5 is simpler than it was previously. As an example, if you have two WebVtt subtitles that you want to sideload, you can create a renderer like:

```
    SampleSource[] sampleSources = new SampleSource[2];
    sources[0] = new SingleSampleSource(...);
    sources[1] = new SingleSampleSource(...);
    TrackRenderer textRenderer = new TextTrackRenderer(sampleSources, player,
        player.getMainHandler().getLooper());
```

Use `ExoPlayer.getTrackCount`, `ExoPlayer.getTrackFormat`, `ExoPlayer.getSelectedTrack` and `ExoPlayer.setSelectedTrack` to query the available subtitles and switch between them.
