### ISSUE TITLE
Question: about exoplayer instead of webview default player

### ISSUE THREAD

**Issue by gary-noovo** [google/ExoPlayer#1269]
Hi:
I'm develop our own android app with HLS,DASH support and I would like to replace webview default player by exoplayer.  It's meaning create some android app with exoplayer library and then replace webview default player and then the HTML5 video player will call directly to ExoPlayer intent. The exoplayer app and webview app are same app. The behavior will same as iOS HTML5 player, video player still embedded in webview but just replaced by exoplayer. Is there a way I can do such that?

thanks

**Comment by ojw28** [comment]
I'm not sure I fully understand the question, but it falls outside the scope of this issue tracker. I'd suggest asking on StackOverflow.
