### ISSUE TITLE
Support playlists (with buffering of next track when current track nears the end)

### ISSUE THREAD

**Issue by wbo4958** [google/ExoPlayer#1270]
Hello all,

I wan't to play 10 songs one by one, auto-switch by STATE_ENDED. When finished the first song, exoplayer will download the second song and prepare to play, so it may result some delay to play second song if bad bandwidth. So I was wondering if there are some policy to pre-load second song when first song is playing?

BR,

**Comment by ojw28** [comment]
This is supported in `dev-v2`. You'll need to build a `MediaSource` for each song that you want to play, then build a `ConcatenatingMediaSource` that wraps the 10 individual `MediaSource` instances. If you then provide the `ConcatenatingMediaSource` to the player, it'll play the tracks seamlessly, maintaining a consistent buffering policy across the transitions.

**Comment by nioncode** [comment]
How to apply this if we have many (e.g. 100) files in the playlist? Is it possible to just provide a FIFO system, where ExoPlayer asks us for the next MediaSource in the playlist whenever it wants to prepare for the next track? That would allow to lazily populate the MediaSources without wasting memory for having all these tracks in the playlist that might not even be played if the user stops playback before reaching them.

**Comment by ojw28** [comment]
You could implement your own `MediaSource` similar to `ConcatenatingMediaSource`, but backed by something like a `Cursor` (or whatever). Being able to lazily add to a `MediaSource` as a direct feature of the library is tracked by https://github.com/google/ExoPlayer/issues/1706.
