### ISSUE TITLE
Android Wear: Black screen but audio with demo streams

### ISSUE THREAD

**Issue by pflammertsma** [google/ExoPlayer#1271]
I'm trying to get the ExoPlayer demo app working for Android Wear (sounds absurd, but we hope to use it to display a pretty video in a production app).

I've tested it on a Samsung Galaxy Gear Live (AW 1.3, Android 5.1) and two host GPU-accelerated emulators (API 22 and API 23), and they give the same results: video is not displayed but playback suggests all is working correctly.

The emulator merrily plays the audio over my system speakers; I haven't had the opportunity to pair bluetooth speakers to the Gear Live to confirm audio is working there as well.

Having tested all samples, the "Video" button never appears when bringing up the controls; only the "Audio" and "Logging" buttons.

Here are two screenshots (note that the buttons have been renamed to single letters so they fit in the tiny display):  
![Imgur](http://i.imgur.com/0m33WJ5.png)![Imgur](http://i.imgur.com/3UkObqE.png)

Loading up the "Google Play (MP4,H264)" sample under "YouTube Dash" gives this Logcat output (logging set to "verbose"):

```
02-16 20:40:39.965 23194-23194/com.pixplicity.exoplayertest I/ExoPlayerImpl: Init 1.5.5
02-16 20:40:39.979 23194-23194/com.pixplicity.exoplayertest D/EventLogger: start [0]
02-16 20:40:39.979 23194-23194/com.pixplicity.exoplayertest D/EventLogger: state [0.00, false, P]
02-16 20:40:39.980 23194-23194/com.pixplicity.exoplayertest D/EventLogger: state [0.00, true, P]
02-16 20:40:40.141 23194-23204/com.pixplicity.exoplayertest W/art: Suspending all threads took: 10.894ms
02-16 20:40:40.290 23194-23194/com.pixplicity.exoplayertest D/EventLogger: availableRange [true, 0, 59280000]
02-16 20:40:40.290 23194-23194/com.pixplicity.exoplayertest V/EventLogger: loadStart [0.31, 1, 2, 0, 0]
02-16 20:40:40.309 23194-23194/com.pixplicity.exoplayertest D/EventLogger: state [0.33, true, B]
02-16 20:40:40.359 23194-23194/com.pixplicity.exoplayertest D/EventLogger: bandwidth [0.38, 696, 0.00, 5568000]
02-16 20:40:40.365 23194-23194/com.pixplicity.exoplayertest V/EventLogger: loadEnd [0.39, 1, 75]
02-16 20:40:40.365 23194-23194/com.pixplicity.exoplayertest V/EventLogger: loadStart [0.39, 1, 1, 0, 10007]
02-16 20:40:40.373 23194-23194/com.pixplicity.exoplayertest D/EventLogger: audioFormat [0.39, 140, 2]
02-16 20:40:40.385 23194-2637/com.pixplicity.exoplayertest I/OMXClient: Using client-side OMX mux.
02-16 20:40:40.399 23194-23194/com.pixplicity.exoplayertest D/EventLogger: decoderInitialized [0.42, OMX.google.aac.decoder]
02-16 20:40:40.418 23194-2638/com.pixplicity.exoplayertest I/SoftAAC2: limiting to stereo output
02-16 20:40:40.438 23194-23194/com.pixplicity.exoplayertest D/EventLogger: state [0.46, true, R]
02-16 20:40:40.450 23194-2638/com.pixplicity.exoplayertest I/SoftAAC2: Reconfiguring decoder: 0->44100 Hz, 0->2 channels
02-16 20:40:40.521 23194-23194/com.pixplicity.exoplayertest D/EventLogger: bandwidth [0.54, 159166, 0.11, 11169543]
02-16 20:40:40.524 23194-23194/com.pixplicity.exoplayertest V/EventLogger: loadEnd [0.55, 1, 159]
02-16 20:40:40.533 23194-23194/com.pixplicity.exoplayertest V/EventLogger: loadStart [0.55, 1, 1, 10007, 20015]
02-16 20:40:40.720 23194-23194/com.pixplicity.exoplayertest D/EventLogger: bandwidth [0.74, 159072, 0.13, 9714320]
02-16 20:40:40.732 23194-23194/com.pixplicity.exoplayertest V/EventLogger: loadEnd [0.75, 1, 199]
02-16 20:40:40.733 23194-23194/com.pixplicity.exoplayertest V/EventLogger: loadStart [0.75, 1, 1, 20015, 30000]
02-16 20:40:40.902 23194-23209/com.pixplicity.exoplayertest I/art: Background sticky concurrent mark sweep GC freed 25336(1183KB) AllocSpace objects, 3(144KB) LOS objects, 11% free, 11MB/12MB, paused 1.265ms total 149.829ms
02-16 20:40:41.011 23194-23209/com.pixplicity.exoplayertest W/art: Suspending all threads took: 5.603ms
02-16 20:40:41.087 23194-23194/com.pixplicity.exoplayertest D/EventLogger: bandwidth [1.11, 158742, 0.15, 9714320]
02-16 20:40:41.090 23194-23194/com.pixplicity.exoplayertest V/EventLogger: loadEnd [1.11, 1, 357]
02-16 20:40:41.090 23194-23194/com.pixplicity.exoplayertest V/EventLogger: loadStart [1.11, 1, 1, 30000, 40007]
02-16 20:40:41.256 23194-23194/com.pixplicity.exoplayertest D/EventLogger: bandwidth [1.28, 158555, 0.10, 9714320]
02-16 20:40:41.260 23194-23194/com.pixplicity.exoplayertest V/EventLogger: loadEnd [1.28, 1, 170]
02-16 20:40:41.260 23194-23194/com.pixplicity.exoplayertest V/EventLogger: loadStart [1.28, 1, 1, 40007, 50015]
02-16 20:40:41.377 23194-23194/com.pixplicity.exoplayertest D/EventLogger: bandwidth [1.40, 158942, 0.08, 11169543]
02-16 20:40:41.381 23194-23194/com.pixplicity.exoplayertest V/EventLogger: loadEnd [1.40, 1, 121]
02-16 20:40:41.381 23194-23194/com.pixplicity.exoplayertest V/EventLogger: loadStart [1.40, 1, 1, 50015, 59280]
02-16 20:40:41.491 23194-23194/com.pixplicity.exoplayertest D/EventLogger: bandwidth [1.51, 146952, 0.08, 12435686]
02-16 20:40:41.495 23194-23194/com.pixplicity.exoplayertest V/EventLogger: loadEnd [1.52, 1, 114]
02-16 20:41:40.632 23194-23194/com.pixplicity.exoplayertest D/EventLogger: state [60.65, true, E]
```

A quick breakdown of the samples:
- YouTube Dash: all samples give the behavior described in this issue
 the behavior described in this issue
- Widevine GTS:
  - all samples give a toast with "This device does not support the required DRM scheme"
- Widevine HDCP:
  - all samples give a toast with "This device does not support the required DRM scheme"
- Widevine Dash MP4,H264:
  - all "Clear" samples give the behavior described in this issue
  - all "Secure" samples give a toast with "This device does not support the required DRM scheme"
- Widevine Dash WebM,VP9: 
  - all "Clear" samples give the behavior described in this issue
  - all "Secure" samples give a toast with "This device does not support the required DRM scheme"
- Widevine Dash MP4,H265:
  - all "Clear" samples give the behavior described in this issue
  - all "Secure" samples give a toast with "This device does not support the required DRM scheme"
- SmoothStreaming:
  - "Super speed" gives the behavior described in this issue
  - "Super speed (PlayReady)" gives a toast with "This device does not support the required DRM scheme"
- HLS:
  - "Apple master playlist advanced" remains stuck on "preparing" despite outputting `loadEnd [8.08, 0, 822]`
  - all other samples give the behavior described in this issue

I'm having troubles figuring out how to troubleshoot this, so any suggestions are welcome.

**Comment by AquilesCanta** [comment]
Is it possible that the device does not count with a H264 decoder?

**Comment by ojw28** [comment]
Yes, I think the device most likely does not have a H264 decoder. As per the [Android CDD](http://static.googleusercontent.com/media/source.android.com/en//compatibility/android-cdd.pdf), video decoders are currently optional for Android Watch devices.

I think @andrewlewis has successfully used ExoPlayer's VP9 software decoder extension on Android Watch devices, so that might be something you could look at. If you need H.264, you'll likely need to implement a similar extension that bridges onto a H.264 software decoder.

**Comment by pflammertsma** [comment]
@andrewlewis Can you link me to that approach? I'm happy to continue tinkering.

**Comment by andrewlewis** [comment]
The [vp9 extension](https://github.com/google/ExoPlayer/tree/master/extensions/vp9) (and the [demo](https://github.com/google/ExoPlayer/tree/master/demo_misc/vp9_opus_sw) which uses it) should work fine on Android Wear devices. For example, I was able to play a WebM file from the sdcard on a Sony Smartwatch 3 running that demo app, without making any special modifications. You can also use the [OpenGL-based output buffer renderer](https://github.com/google/ExoPlayer/blob/master/demo_misc/vp9_opus_sw/src/main/java/com/google/android/exoplayer/demo/vp9opus/PlayerActivity.java#L143) which improves performance slightly.

Please be careful about battery consumption: in my experimentation, software playback of a video used 100% battery in about an hour! So this is only really suitable for short clips.

Last time I checked it was not possible for an app to make direct HTTP requests from Android Wear. So media needs to be pushed as an asset or as part of the microapp, or streamed from the paired device. In the latter case, we found that the [channel API](http://developer.android.com/training/wearables/data-layer/index.html) worked well.

Aside: many Android Wear devices do actually have video decoding hardware, but support for using it is not included in the Android system images.

**Comment by pflammertsma** [comment]
Excellent response, thanks so much @andrewlewis! I'll take a look at that demo and continue tinkering.

The breakdown of all samples in the issue description were actually all on a Samsung Galaxy Gear Live, so it would appear that this device specifically doesn't have video decoding. I'll do some additional tests on a Huawei Watch and LG G Watch R.

**Comment by andrewlewis** [comment]
Regarding testing on different watches: I wouldn't expect video decoding via the core ExoPlayer library to work on *any* Android Wear devices, because it uses MediaCodec to access device codecs. Even though many devices have the hardware for it, the Android system image does not expose it to the system or apps.

The VP9 extension should just work (on any device), because it bundles a software decoder with the library. Thanks!

**Comment by pflammertsma** [comment]
Ah, gotcha. That's too bad. Thanks for the clarification.
