### ISSUE TITLE
ExoPlayer in APK for SDK < 4.1???

### ISSUE THREAD

**Issue by j-t-h** [google/ExoPlayer#1272]
What will happen if an application has ExoPlayer included, but the video playback is not enabled for < 4.1 devices? I have an Application that I am upgrading to use ExoPlayer, however the business wants to support devices below 4.1. 

As long as I detect the SDK version before I try using ExoPlayer, will I be able to install the app on pre-4.1 devices?

I would rather not have to have two branches based on ExoPlayer/ without ExoPlayer.

Thanks.

**Comment by ojw28** [comment]
Yes, you will still be able to install the app on devices running older versions of Android. The minimum API level on which your application will install is determined (only) by minSdkVersion as specified in your application's manifest. You're free to use APIs that are more recent than the specified minimum version, up to whatever you specify as the targetSdkVersion in the application manifest, but it's your responsibility to ensure that use of those APIs is correctly guarded with SDK version checks. As long as you do that everything should be fine.
