### ISSUE TITLE
ExoPlayer fails to play HLS with audio

### ISSUE THREAD

**Issue by chile-zhong** [google/ExoPlayer#1283]
The following video is able to play but the audio is missing  when added as an HLS sample within the latest 1.5.5 demo app,but other player can do:(it's our interal HLS)
http://release.swiftsync.com.sg/test_movie/qa_testdata/lingling/unencrypt/12891/1/503/manifest.m3u8
the content of this HLS is :(it shows two tracks, but cannot show)
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio_track_503",NAME="chi",DEFAULT=YES,FORCED=NO,AUTOSELECT=YES,URI="503/audio/chi/playlist.m3u8",LANGUAGE="chi"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio_track_503",NAME="eng",DEFAULT=NO,FORCED=NO,AUTOSELECT=YES,URI="503/audio/eng/playlist.m3u8",LANGUAGE="eng"

#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID="subtitles_503",NAME="eng",DEFAULT=YES,FORCED=NO,AUTOSELECT=YES,URI="503/subtitle/eng/playlist.m3u8",LANGUAGE="eng"
#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID="subtitles_503",NAME="chi",DEFAULT=NO,FORCED=NO,AUTOSELECT=YES,URI="503/subtitle/chi/playlist.m3u8",LANGUAGE="chi"

#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=3000000,AUDIO="audio_track_503",SUBTITLES="subtitles_503",CLOSED-CAPTIONS=NONE
503/video/playlist.m3u8

**Comment by ojw28** [comment]
This is tracked by https://github.com/google/ExoPlayer/issues/73.
