### ISSUE TITLE
onPlayerError improvement

### ISSUE THREAD

**Issue by ChernyshovYuriy** [google/ExoPlayer#1284]
Dear colleagues,
I have an inquire about passing additional information with an error in ExoPlayer.
I am talking about **StreamingDrmSessionManager.java** and it's method:
`void onKeyResponse(Object response)`
In case of any error with License retrieving, our server returns important information with "**Object response**" and this causing exception in next line:
`mediaDrm.provideKeyResponse(sessionId, (byte[]) response);`
That is OK. But, however, we loosing that information form client side.
So I am asking, whether it is possible to by-pass response with Exception, so it will be possible to get it in "onPlayerError" callback ?

As possible solution now, we inject custom listener into WidevineMediaDrmCallback.java and parse 
`byte[] executeKeyRequest(final UUID uuid, final MediaDrm.KeyRequest request)`
response in order to intercept message.

Thanks a lot in advance.

**Comment by ojw28** [comment]
You must be implementing `MediaDrmCallback`. You should have you `MediaDrmCallback.executeKeyRequest` check the response. If it's an error response this method should construct and throw an appropriate exception, which you can define yourself. Playback will then fail with this exception as the cause.

To provide more detail, the way I've seen this implemented elsewhere is for the license server to return a response whose body contains a status. For example:

```
Status=X
<data>
```

Upon obtaining the response, `MediaDrmCallback.executeKeyRequest` will then parse the response and look at the status. If it's ok, it'll return <data>. If it's not ok, it'll construct and throw an appropriate exception. Note that the license server response is something you can design yourself, so you can put any information in there that you want to include in the exception.

**Comment by ChernyshovYuriy** [comment]
Hi and thanks for the quick response.
`MediaDrmCallback ` is what I was talking about, in particular it's implementation in our project `class WidevineMediaDrmCallback implements MediaDrmCallback`.
According to your suggestion I should intercept response and parse it. This is what I am doing, but I am not blocking farther execution and allow to return data from `byte[] executeKeyRequest(final UUID uuid, final MediaDrm.KeyRequest request)`.
Ok, thanks for the solution.

**Comment by ChernyshovYuriy** [comment]
Oh, I forget important thing!
In both methods of the `MediaDrmCallback `:
`byte[] executeKeyRequest(final UUID uuid, final MediaDrm.KeyRequest request)`
`byte[] executeProvisionRequest(final UUID uuid, final MediaDrm.ProvisionRequest request)`
we must return bytes array.
This is the point. In case of success - we have no issues, but in case of any error we have to pass these bytes farther. And this will cause finally `void onPlayerError(final ExoPlaybackException error)`.
And, in case we processing `executeKeyRequest` and detect an error - then there is double error in the side of ExoPlayerImpl. One is `onPlayerError` and another is custom License Error listener.

And intention of my initial question was to prevent it. To process an error in single place, in `onPlayerError` callback. Does it make sense for you now?

**Comment by ojw28** [comment]
You don't have to return a byte array. You should be throwing an exception, meaning you don't need to (i.e. can't) return anything.

**Comment by ChernyshovYuriy** [comment]
Ok, let me try tis approach.

**Comment by ChernyshovYuriy** [comment]
This approach works well, thanks a lot. I think question can be closed now :-)

**Comment by ojw28** [comment]
Great!
