### ISSUE TITLE
[Suggestion/Question]

### ISSUE THREAD

**Issue by Ameno-Sagiri** [google/ExoPlayer#1288]
Would it be possible for Media Player to support direct urls, such as direct mp4/avi etc links through Copy or Dropbox? It just seems to me that if it can support actual services, it would be able to support barebones web videos.

If not, could you tell me why I'm horrifically wrong <:^)

**Comment by ojw28** [comment]
I don't understand what's being asked here. ExoPlayer already supports playback of URLs, and its demo application contains multiple examples of this.

**Comment by Ameno-Sagiri** [comment]
I looked up Media Player Garry's Mod github and went to the first thing, didn't realize I posted in the wrong project. Closing.
