### ISSUE TITLE
DRM not initialized with protected MPD content when a supported pssh box is encoded into fragments

### ISSUE THREAD

**Issue by jlacivita** [google/ExoPlayer#1289]
Hi guys,

The fix for #1195 (https://github.com/google/ExoPlayer/issues/1195) in MediaPresentationDescriptionParser.java breaks the DemoPlayer.java example when using valid Widevine MPD files where the pssh box is stored inside of the Media Segments, and not the the "cenc:pssh" element. As per the MPD spec, the cenc:pssh element is optional, but the latest code nulls out the entire ContentProtection object simply because it doesn't have a cenc:pssh. Here's  the relevant bit from the MPD spec:

7.2.

4. ‘pssh’ license acquisition data or keys for each DRM in a format that is “Protection System Specific”. ‘pssh’ refers to the Protection System Specific Header box described in[26], 8.1.2. ‘pssh’ boxes may be stored in Initialization or Media Segments (see [26] 8.1 and 8.2). It may also be present in a cenc:pssh element in the MPD (see [5] 5.8.4.1, [26] 11.2.1). cenc:pssh information in the MPD increases the MPD size but may allow faster parsing, earlier access and addition of DRMs without content modification.

http://dashif.org/w/2015/04/DASH-IF-IOP-v3.0.pdf

It looks to me like you're assuming that a missing "cenc:pssh" element implies version 2+, but there's no way (at parse time) to know what version it is if it's not in the manifest. When this happens, DashRendererBuilder.java fails to set the hasContentProtection flag on any Widevine content with the cenc:pssh encoded in to the fragments. The offending code is:

```
    String schemeIdUri = xpp.getAttributeValue(null, "schemeIdUri");
    UUID uuid = null;
    SchemeInitData data = null;
    do {
      xpp.next();
      // The cenc:pssh element is defined in 23001-7:2015.
      if (ParserUtil.isStartTag(xpp, "cenc:pssh") && xpp.next() == XmlPullParser.TEXT) {
        data = new SchemeInitData(MimeTypes.VIDEO_MP4,
            Base64.decode(xpp.getText(), Base64.DEFAULT));
        uuid = PsshAtomUtil.parseUuid(data.data);
      }
    } while (!ParserUtil.isEndTag(xpp, "ContentProtection"));
    if (uuid == null) {
      Log.w(TAG, "Skipped unsupported ContentProtection element");
      return null;
    }
    return buildContentProtection(schemeIdUri, uuid, data);
```

I think what you may want is:

```
    String schemeIdUri = xpp.getAttributeValue(null, "schemeIdUri");
    UUID uuid = null;
    SchemeInitData data = null;
    do {
      xpp.next();
      // The cenc:pssh element is defined in 23001-7:2015.
      if (ParserUtil.isStartTag(xpp, "cenc:pssh") && xpp.next() == XmlPullParser.TEXT) {
        data = new SchemeInitData(MimeTypes.VIDEO_MP4,
            Base64.decode(xpp.getText(), Base64.DEFAULT));
        uuid = PsshAtomUtil.parseUuid(data.data);
        if (uuid == null) {
          Log.w(TAG, "Skipped unsupported ContentProtection element");
          return null;
        }
      }
    } while (!ParserUtil.isEndTag(xpp, "ContentProtection"));
    return buildContentProtection(schemeIdUri, uuid, data);
```

Which would return null when the uuid isn't parsed properly, but not when the entire "cenc:pssh" element is missing.

**Comment by ojw28** [comment]
I think this is fixed in the dev branch already, in https://github.com/google/ExoPlayer/commit/30a250fb43b7f0a8f9729f62ec24fbc91e09adff.

**Comment by jlacivita** [comment]
Awesome, thanks!

**Comment by jlacivita** [comment]
Any plans to make a release with this fix soon?

We want to ship WebVTT support, but we need this fixed before we can leverage it.

**Comment by ojw28** [comment]
We'll ship a release with this soon, yes.
