### ISSUE TITLE
"Buffer too small" Exception during MKV playback

### ISSUE THREAD

**Issue by ened** [google/ExoPlayer#1290]
When playing a certain MKV file, the "Buffer too small" exception will appear after a few seconds or after seeking.

ExoPlayer used is `dev`-branch, commit 128091a2bd86a45eca1d680cae4730fe8fb1d5c8.

The MKV file and `adb bugreport` output has been sent to dev.exoplayer@gmail.com.

100% Reproducible on Android 4.4 device (MTK-based). Other device test TBD.

Application log here:

```
file:///storage/usbotg/video/03.mkv/WiegelesHeliSki_DivXPlus_19Mbps_xvid.mkv

Actions: 
ExoPlayer.Factory.newInstance, 3
ExoPlayer: addListener, 
ExoPlayer: sendMessage, 1
ExoPlayer: prepare, com.google.android.exoplayer.MediaCodecVideoTrackRenderer@423c8c90, com.google.android.exoplayer.MediaCodecAudioTrackRenderer@423c8ff8, com.google.android.exoplayer.text.TextTrackRenderer@423c9458
ExoPlayer: setPlayWhenReady, true
ExoPlayer: getDuration, 
ExoPlayer: getCurrentPosition, 
ExoPlayer: getDuration, 
ExoPlayer: getCurrentPosition, 
ExoPlayer: getDuration, 
ExoPlayer: getCurrentPosition, 
ExoPlayer: getDuration, 
ExoPlayer: getCurrentPosition, 
ExoPlayer: getDuration, 
ExoPlayer: getCurrentPosition, 
ExoPlayer: getDuration, 
ExoPlayer: getCurrentPosition, 
ExoPlayer: getDuration, 
ExoPlayer: getCurrentPosition, 
ExoPlayer: getDuration, 
ExoPlayer: getCurrentPosition, 
ExoPlayer: getDuration, 
ExoPlayer: getCurrentPosition, 
ExoPlayer: getDuration, 
ExoPlayer: getCurrentPosition, 
ExoPlayer: getDuration, 
ExoPlayer: getCurrentPosition, 
ExoPlayer: getDuration, 
ExoPlayer: getCurrentPosition, 


com.google.android.exoplayer.ExoPlaybackException: java.lang.IllegalStateException: Buffer too small (65536 < 66039)
	at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:246)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.os.HandlerThread.run(HandlerThread.java:61)
	at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
Caused by: java.lang.IllegalStateException: Buffer too small (65536 < 66039)
	at com.google.android.exoplayer.SampleHolder.createReplacementBuffer(SampleHolder.java:148)
	at com.google.android.exoplayer.SampleHolder.ensureSpaceForWrite(SampleHolder.java:100)
	at com.google.android.exoplayer.extractor.RollingSampleBuffer.readSample(RollingSampleBuffer.java:189)
	at com.google.android.exoplayer.extractor.DefaultTrackOutput.getSample(DefaultTrackOutput.java:142)
	at com.google.android.exoplayer.extractor.ExtractorSampleSource.readData(ExtractorSampleSource.java:387)
	at com.google.android.exoplayer.SampleSourceTrackRenderer.readSource(SampleSourceTrackRenderer.java:209)
	at com.google.android.exoplayer.MediaCodecTrackRenderer.feedInputBuffer(MediaCodecTrackRenderer.java:581)
	at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:485)
	at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:129)
	at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431)
	at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
	... 4 more
```

**Comment by ojw28** [comment]
What's the use case for playing 19Mbps mpeg-4 part 2 video? That doesn't seem like a particularly sensible way to be encoding video for delivery to mobile devices...

**Comment by ened** [comment]
Use case is a offline playback device (in-car tablet), and this is one of our test files.

People might connect other data sources to our product (USB sticks, SD cards, recording devices), which themselves have raw, unprocessed, video files.

**Comment by ojw28** [comment]
Is this a device that you're developing directly (i.e. you control the platform software)? The root cause of the failure is that the mpeg2 decoder isn't allocating sufficiently large input buffers. So if you do have direct control, you should fix the problem in the platform.

**Comment by ojw28** [comment]
For comparison, OMX.qcom.video.decoder.mpeg4 on Nexus 5X allocates 1576960 byte buffers for this video. OMX.google.mpeg4.decoder allocates 3110400 byte buffers. On the affected device, it appears that the buffers are only 65536 bytes, which is much too small.

We've worked around the issue of too small input buffers for some other formats in MediaCodecVideoTrackRenderer.maybeSetMaxInputSize, where we set an explicit minimum at the application layer to pass down. We could add the following case for mpeg-4:

```
      case MimeTypes.VIDEO_MP4V:
        maxPixels = maxWidth * maxHeight;
        minCompressionRatio = 1;
        break;
```

which would match what Google's software decoder does. We might want to set minCompresisonRatio to 2 just to try and keep the allocation size under control a little.

Please try adding the above to MediaCodecVideoTrackRenderer to see if it resolves the issue for you. Although if you do have control over the platform, it's still preferable for you to fix the issue in the platform itself, so that the buffers are sized large enough for non-ExoPlayer based playbacks.

**Comment by ened** [comment]
Yes, we are developing the device and it's a MTK platform. The fact that `MediaPlayer` works won't help much here, I think.

I will retest/review the issue asap. Thanks Olly.

**Comment by ojw28** [comment]
Good to know. If you could test the fix suggested above, that would be helpful. We can merge that independently to a fix directly in the platform if so. The platform fix would probably need to come from MTK, assuming it's their decoder.

**Comment by ened** [comment]
@ojw28 the patch works well. Just tested it.

**Comment by ojw28** [comment]
@andrewlewis - What do you think a sensible value for minCompressionRatio would be for this case? I'm somewhat worried about using 1; it seems a little excessive. I was wondering about using 2. It appears the decoder on Nexus 5X uses 2. Feel free to apply a fix with whatever value you deem best. Should we do something for H263 whilst we're at it, to avoid the inevitable future bug?

**Comment by andrewlewis** [comment]
minCompressionRatio of 2 sounds fine, and H.263 can probably use the same.
