### ISSUE TITLE
Playback issues with MPEG-TS/MPEG2/MPA2 stream

### ISSUE THREAD

**Issue by stari4ek** [google/ExoPlayer#1292]
* checked on dev (7814aaac466aad8b76fcfaf64c53731c99e9e35d)
* video1: https://docs.google.com/uc?id=0B4_pcf38WwzYNVROQU8weW9NaG8&export=download
* video2: https://docs.google.com/uc?id=0B4_pcf38WwzYZW9OQUJMRUlNVlk&export=download

I have 2 issues with it.
**No audio track.**
* Nexus Player (sdk: 23, 3.10.20-gcf431b9 (2495654))
in the log I see, that no audio track is received from ExoPlayer:

> Tracks updated: [[PlayerTrackInfo(Video, 0, MediaFormat(null, video/mpeg2, -1, -1, 720, 576, -1, 1.0666667, -1, -1, null, -1, false, -1, -1, -1, -1)], [], []]
This issue is reported by user, I can not reproduce it locally, case I don't have device.

**Bumpy playback**
Same stream checked in DemoPlayer on Nvidia Shield. There is an audio, but whole playback is very bumpy

Log:
> D/EventLogger: decoderInitialized [0.09, OMX.Nvidia.mpeg2v.decode]
> D/EventLogger: decoderInitialized [0.09, OMX.Nvidia.mp2.decoder]
> W/ACodec: [OMX.Nvidia.mpeg2v.decode] setting nBufferCountActual to 10 failed: -1010
> W/ACodec: [OMX.Nvidia.mpeg2v.decode] setting nBufferCountActual to 9 failed: -1010
> D/EventLogger: videoSizeChanged [720, 576, 0, 1.4222223]
> D/EventLogger: state [0.14, true, R]
> E/AudioTrack: Discontinuity detected [expected 372979, got -8344]
> I/ACodec: video input Buffer After 677184 Us
> D/EventLogger: state [1.42, true, B]
> D/EventLogger: droppedFrames [1.42, 3]
> D/EventLogger: state [1.49, true, R]
> I/ACodec: video input Buffer After 281129 Us
> I/ACodec: video input Buffer After 209452 Us
> D/EventLogger: state [3.14, true, B]
> D/EventLogger: droppedFrames [3.14, 38]
> D/EventLogger: state [3.22, true, R]
> I/ACodec: video input Buffer After 208447 Us
> D/EventLogger: state [3.52, true, B]
> D/EventLogger: droppedFrames [3.52, 3]
> D/EventLogger: state [3.61, true, R]
> I/ACodec: video input Buffer After 364111 Us
> D/EventLogger: droppedFrames [4.21, 50]
> D/EventLogger: end [4.90]
> D/EventLogger: droppedFrames [4.90, 9]

Media info:

> General
> ID                                       : 1 (0x1)
> Complete name                            : /home/astar/insync/stari4ek@gmail.com/IPTV/issues/02_no_sound/dbcf02ce2adefb15953f284cc1bf56e5_-_.mp4
> Format                                   : MPEG-TS
> File size                                : 4.12 MiB
> Duration                                 : 12s 80ms
> Overall bit rate mode                    : Variable
> Overall bit rate                         : 2 857 Kbps
> 
> Video
> ID                                       : 2305 (0x901)
> Menu ID                                  : 9 (0x9)
> Format                                   : MPEG Video
> Format version                           : Version 2
> Format profile                           : Main@Main
> Format settings, BVOP                    : Yes
> Format settings, Matrix                  : Custom
> Format settings, GOP                     : M=3, N=24
> Format settings, picture structure       : Frame
> Codec ID                                 : 2
> Duration                                 : 11s 680ms
> Bit rate mode                            : Variable
> Bit rate                                 : 2 522 Kbps
> Maximum bit rate                         : 15.0 Mbps
> Width                                    : 720 pixels
> Height                                   : 576 pixels
> Display aspect ratio                     : 16:9
> Frame rate                               : 25.000 fps
> Standard                                 : PAL
> Color space                              : YUV
> Chroma subsampling                       : 4:2:0
> Bit depth                                : 8 bits
> Scan type                                : Interlaced
> Scan order                               : Top Field First
> Compression mode                         : Lossy
> Bits/(Pixel*Frame)                       : 0.243
> Stream size                              : 3.51 MiB (85%)
> 
> Audio
> ID                                       : 2306 (0x902)
> Menu ID                                  : 9 (0x9)
> Format                                   : MPEG Audio
> Format version                           : Version 1
> Format profile                           : Layer 2
> Codec ID                                 : 4
> Duration                                 : 11s 976ms
> Bit rate mode                            : Constant
> Bit rate                                 : 192 Kbps
> Channel(s)                               : 1 channel
> Sampling rate                            : 48.0 KHz
> Compression mode                         : Lossy
> Delay relative to video                  : -513ms
> Stream size                              : 281 KiB (7%)

**Comment by ojw28** [comment]
Neither mpeg2 nor mpa2 are officially supported by Android. If this is an nVidia Shield specific issue with their optional additional support for these codecs, then you should file the issue with nVidia in the first instance.
