### ISSUE TITLE
ExoPlayer never leaves preparation stage for TS/h264/mpa2

### ISSUE THREAD

**Issue by stari4ek** [google/ExoPlayer#1293]
* dev (7814aaac466aad8b76fcfaf64c53731c99e9e35d)
* video: https://docs.google.com/uc?id=0B4_pcf38WwzYcU5NQ1NsLVM3UEk&export=download
* checked in DemoPlayer
* NVidia Shield
* Sony BRAVIA 4K 2015 (SVP4KDTV15_EU)

With default DemoPlayer configuration, ExoPlayer never leaves "preparing" state

> 02-21 17:36:19.344 6731-6731/com.google.android.exoplayer.demo I/ExoPlayerImpl: Init 1.5.5
> 02-21 17:36:19.345 6731-6731/com.google.android.exoplayer.demo D/EventLogger: start [0]
> 02-21 17:36:19.345 6731-6731/com.google.android.exoplayer.demo D/EventLogger: state [0.00, false, P]
> 02-21 17:36:19.347 6731-6731/com.google.android.exoplayer.demo D/EventLogger: state [0.00, true, P]
> 

With _TsExtractor.WORKAROUND_ALLOW_NON_IDR_KEYFRAMES_ enabled, it detects tracks but playback is bumpy and don't move forward (very similar to https://github.com/google/ExoPlayer/issues/1292)

**Comment by ojw28** [comment]
If you want to play H264 without any IDR frames then you need to enable the workaround flag explicitly. If you have control over the generation side of these streams then you should include IDR frames. Aside from that, this issue is the same as #1292.

**Comment by stari4ek** [comment]
@ojw28, Thank You for checking it and I'm really sorry for misleading You.

You're right I have to enable WORKAROUND_ALLOW_NON_IDR_KEYFRAMES (and I **do** in my app). 

Even with WORKAROUND_ALLOW_NON_IDR_KEYFRAMES enabled it doesn't work on **Sony**.

It works well on _NVidia Shield_. And it works well on _Sony_ in default player and in **MX Player** with **HW+** decoder enabled.
I'm working on getting logs from Sony to check which codecs used in default player/mx palyer/exoplayer

Is it better to create new issue (sony specific) with proper description?

**Comment by ojw28** [comment]
Please file a new issue. Please include all of the information requested in the issue template. Thanks!
