### ISSUE TITLE
Can we play the YouTube Link into the Exoplayer?

### ISSUE THREAD

**Issue by Bhavdip** [google/ExoPlayer#1296]
Hello, I have successfully integrated the exoplayer into our application. We are able to play the HLS video (.m3u8) file which uploaded over remote server. Now we have some video links that uploaded over the youtube. Can I play YouTube link into exoplayer by enabling the Type_DASH?

Thanks

**Comment by ojw28** [comment]
The short answer is: No.

You can play anything to which you have a direct URL to the media. YouTube don't expose direct URLs, so you'd have to use their [player API](https://developers.google.com/youtube/android/player/) instead. Of course, you could alternatively host DASH content yourself, as you're doing for HLS, which would provide you with the direct URLs you need.
