### ISSUE TITLE
Expose whether the media being played is seekable

### ISSUE THREAD

**Issue by ojw28** [google/ExoPlayer#1300]
For non-seekable media, attempting to seek will restart playback from t=0 (or for live streams, restart playback from the live edge). We should expose whether the media being played is seekable, so that applications can query this property and determine what attempting to seek will actually do.

**Comment by zgxzgxzg** [comment]
How embodied in the code inside？

**Comment by ojw28** [comment]
This is fixed in `dev-v2`. Specifically, you can call `ExoPlayer.getCurrentTimeline` to get a `Timeline` that describes the media being played. `ExoPlayer.getCurrentWindowIndex` will tell you which window of the timeline is currently being played. You can query the timeline for details about the window, including whether it's seekable (`Window.isSeekable`).
