### ISSUE TITLE
request for setup recommendation (H.264 HW encoder)

### ISSUE THREAD

**Issue by kartajan** [google/ExoPlayer#1302]
Need setup recommendation for the following:
I have a HW H.264 encoder :
http://cgi.ebay.com/ws/eBayISAPI.dll?ViewItemVersion&item=331723486021&view=all&tid=1239181240014

settings that are not working:
H.264 level: baseline profile
Encoding Frame rate:30
Bitrate Control: vbr
Key Interval: 30
Encoded Size: 1280x720
MinQp: 3
MaxQp: 32
Max Bitrate: 2000
Audi Bitrate: 19200
Audio Channel: L+R
Audio Codec: AAC
Resample: Disable
Package: B
HTTP: /hdmi enable
Change TS ID: Disable
RTSP: Disable
Multicast IP: Disable
RTMP server ip: Disable

I have been trying to get it configured properly for the stream to be used in an application that uses exoplayer (CumulusTV), but it does not seem to function; the stream is working when accessed via VLC, so it is a configuration problem on my end. Please advise as to proper configuration. I looked at the "Video Encoding Recommendations" table 2, and set up for 720p H.264 baseline profile, but it still does not display the stream (it eventually crashes CumulusTV)

**Comment by ojw28** [comment]
It's beyond the scope of this issue tracker to be advising on configuration on your serving side infrastructure. If you can produce some sample content that you believe should be supported and does not play, please file an issue linking to that content and providing full details as requested in the issue template.
