### ISSUE TITLE
Scrambled captions after seeking

### ISSUE THREAD

**Issue by akucera09** [google/ExoPlayer#1304]
**ExoPlayer Version:** 1.5.6

**Testing Device:**
Asus Nexus 7, Android 6.0.1 API 23

**Issue**
We are seeing scrambled caption text directly after seeking an HLS video with 708 captions. After one block of scrambled text, captions look normal again and playing through the same segment without seeking does not show this problem. 

The following screen shots are at 35 seconds.

**Links**
HLS Media: http://test.theplatform.com.edgesuite.net/PDK_(VMS)/450/530/NUVO_H264_H264_SCC_2300.m3u8
Screen shot, seeked and scrambled: http://postimg.org/image/z0x4sc6et/
Screen shot, played from beginning : http://postimg.org/image/6mrp8giut/

**Comment by ojw28** [comment]
Yes, this is a known issue. It stems from the fact that frames can be out-of-presentation-order in the video stream. Caption data is embedded, and so is similarly out-of-presentation-order.

The video frames are reordered by the platform's video decoder, but for caption data we have to do the reordering ourselves. Our approach is sometimes a little too aggressive at the start of playback, and can end up processing caption data too soon only to have data with an earlier presentation timestamp arrive shortly afterward.

**Comment by bit101** [comment]
I'm still seeing this issue in ExoPlayer v2. Is this still a "known issue"? I'm also not only seeing it after seeking, but eventually after just letting certain streams play.

**Comment by ojw28** [comment]
@bit101 - It's still theoretically possible in V2, but it's less likely to occur than it was in V1. Regardless, it shouldn't occur during ongoing playback; this issue is specifically about the start of playback (or equivalently, immediately following either seeking or buffering). Let's track your issue with #2070.

**Comment by ojw28** [comment]
This is much better in V2; I think it can be closed.
