### ISSUE TITLE
Does EXOPlayer support x64 deviecs?

### ISSUE THREAD

**Issue by gongshoudao** [google/ExoPlayer#1305]
02-24 02:10:55.907 21889-1454/com.google.android.exoplayer.demo E/ExoPlayerImplInternal: Internal track renderer error.
                                                                                         com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.ffmpeg.h264.decoder, MediaFormat(null, video/avc, -1, -1, 400, 300, -1, 1.0, -1, -1, null, -1, false, 1920, 1080)
                                                                                             at com.google.android.exoplayer.MediaCodecTrackRenderer.notifyAndThrowDecoderInitError(MediaCodecTrackRenderer.java:388)
                                                                                             at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:374)
.......
Has any **Solution**？

**Comment by ojw28** [comment]
Yes, ExoPlayer supports all device architectures. If you want further assistance please file an issue that contains all of the information requested in the issue template.

**Comment by gongshoudao** [comment]
I use exoplayer to play .m3u8 files on x86 simulator，throw Internal track renderer error。How can i fix this use third-party like [vp9] which include jni method?
@ojw28

**Comment by AquilesCanta** [comment]
@gongshoudao It is impossible to help you with that amount of information. Also, since the issue is closed, please file a new issue including all information requested in the issue template.

**Comment by ojw28** [comment]
Simulators often don't fully implement the media stack that would be required on a real device. For media, it's better to test on real devices.
