### ISSUE TITLE
How to control two audio files playback currently

### ISSUE THREAD

**Issue by cuagia** [google/ExoPlayer#1306]
Sorry it's not issue but I'm newbie and didn't find any related document :(
I have a task as below:
Looping 1 audio file in raw folder as background music (background effect) with smaller volume . Currently play other downloaded audio file as normal.
1. Is it possible when use ExoPlayer ?
2. How to control play/pause/volume of two files separately 
Thank you.

**Comment by ojw28** [comment]
Sorry, we're a small team, and we don't scale to providing Q&A on this issue tracker. I'd suggest asking on stackoverflow.
