### ISSUE TITLE
1.5.5 broke playing videos captured on recent iphones

### ISSUE THREAD

**Issue by johngray1965** [google/ExoPlayer#1308]
I have an android app that's playing videos from a server that are uploaded from Android and ios devices.  Recently many of the videos uploaded from the ios devices stopped working in exoplayer.  I was able to track down the the version of the Android app where things went wrong, it was when I updated exoplayer from 1.5.4 to 1.5.5 (1.5.6 doesn't work either).  Reverting back to 1.5.4 resolved the issue.

The problem seems to be videos captured on  iPhone 6+'s and some iPhone 6's (In our experience all the videos on 6+'s failed to play, and some 6's but not others).  Sorry, but I have absolutely no idea how the videos are different.  They appeared to encoded the same way.

I'm happy to supply some examples of the videos that don't play.

Thanks

**Comment by ojw28** [comment]
Please supply test content. Thanks.

**Comment by johngray1965** [comment]
Here you go:

http://test.agora-net.com/IMG_1295.MOV

I can put that on the sdcard and reference in the demo app, it plays in 1.5.4, but not 1.5.5 or 1.5.6

Thanks

**Comment by ojw28** [comment]
@AquilesCanta - This is an interesting one to look at.

**Comment by AquilesCanta** [comment]
Confirmed bug. The fix will be available in the next release, I guess. Many thanks!

**Comment by AquilesCanta** [comment]
Will close again once the fix is available.
