### ISSUE TITLE
[QUESTION] SW \ HW Decoding 

### ISSUE THREAD

**Issue by Angels-group** [google/ExoPlayer#1313]
Good day, dear ExoPlayer's developers! 

Is it possible to implement a selection HW \ SW decoding using ExoPlayer?
The problem appeared on Android devices with the old processor.
Some devices work well, some can not cope with the video stream.
For example, there are MX Player app. There the user the opportunity to select the decoder. At the same time, some Android devices are working perfectly with MX Player (on the other decoder).
I compare the same video stream to ExoPlayer and MXPlayer.

I'm sorry if the topic discussed. I could not find an answer to my question.
I would be grateful if you help realize the selection the decoder.

Sorry for my english. Regards, Denis.

**Comment by AquilesCanta** [comment]
I am not perfectly sure what you want to do. But using your own `MediaCodecSelector` implementation should allow you to select the decoder you want.
