### ISSUE TITLE
[QUESTION] Mpeg-Dash

### ISSUE THREAD

**Issue by Bigcheese-** [google/ExoPlayer#1314]
Is there anyway to listen to an event for when the first frame has been rendered after selecting a new format. 
The BaseChunkSampleSourceEventListener.onDownstreamFormatChanged. Is not accurate enough for what I need, I need to know exactly when a frame is being pushed to the Surface when a new format is loaded.

Thanks,

**Comment by ojw28** [comment]
There is no functionality to do this, sorry.
