### ISSUE TITLE
[QUESTION] How to get pixelWidthAspectRatio parameter

### ISSUE THREAD

**Issue by Angels-group** [google/ExoPlayer#1319]
I need to implement a selection engine between ExoPlayer and MediaPlayer in my application.
As it turned out, some devices work best with MediaPlayer and some with ExoPlayer .
For the same aspect ratio I need to get the variable pixelWidthAspectRatio in MediaPlayer (like in ExoPlayer).
How ExoPlayer gets this variable?
Is it possible to get it in a MediaPlayer?
Does anyone have any links to similar examples of implementation?
I tried to trace the source code ExoPlayer, but could not completely understand.
Thank you for your help!

**Comment by ojw28** [comment]
I don't think MediaPlayer exposes a way for you to get at the pixel width aspect ratio.

**Comment by Angels-group** [comment]
How this variable is obtained?

**Comment by ojw28** [comment]
It's parsed out of the media stream by ExoPlayer's extractor implementations. You should be able to look through the ExoPlayer source code to find where it originates from in each of the extractors.

**Comment by Angels-group** [comment]
This variable is located directly in the stream or calculated from a number of other variables?

**Comment by ojw28** [comment]
It depends on the individual container format. Please look at the source code to answer this question yourself for whatever container you're interested in.
