### ISSUE TITLE
Not able to open local file (mp4) on Android Marshmallow 6.0.                     

### ISSUE THREAD

**Issue by Meera94** [google/ExoPlayer#1321]
Please search the existing issues before filing a new one, including issues that are closed. When filing a new issue please include all of the following, unless you're certain that they're not useful for the particular issue being reported.

- A description of the issue.
- Steps describing how the issue can be reproduced, ideally in the ExoPlayer demo app.
- A link to content that reproduces the issue. If you don't wish to post it publicly, please submit the issue, then email the link to dev.exoplayer@gmail.com including the issue number in the subject line.
- The version of ExoPlayer being used.
- The device(s) and version(s) of Android on which the issue can be reproduced, and how easily it reproduces. If possible, please test on multiple devices and Android versions.
- A bug report taken from the device just after the issue occurs, attached as a file. A bug report can be captured using "adb bugreport". Output from "adb logcat" or a log snippet is not sufficient.

**Comment by Meera94** [comment]
It is giving me the following exception: 
`com.google.android.exoplayer.ExoPlaybackException:` com.google.android.exoplayer.upstream.FileDataSource$FileDataSourceException: java.io.FileNotFoundException: /mnt/sdcard/filename.mp3: open failed: ENOENT (No such file or directory)`

Does this exception have to do with Androids new permission model .Or is the file path that I have given incorrect?
I am thinking that it could be the latter too since I could not open a local mp4 file on Exoplayer from SD card while using a lower API level as well. (API 21)

**Comment by Fleker** [comment]
Yes that's due to a lack of the `READ_EXTERNAL_STORAGE` permission. You need to have that in your manifest and create a prompt for the user to allow storage.

**Comment by Meera94** [comment]
Yes! Got it, thanks! :D

**Comment by ojw28** [comment]
I don't think that's correct. I'd expect the exception message to read "EACCES (Permission denied)" if the permission were missing. I think it's more likely that the path is incorrect.

**Comment by Fleker** [comment]
No, it is a permission issue. I had no storage permission enabled and got
that error.
