### ISSUE TITLE
HLS playback delay

### ISSUE THREAD

**Issue by chile-zhong** [google/ExoPlayer#1327]
When i play HLS, the progress bar turn to blue means it has been  downloaded, but when i seek to the downloaded place, the player always delay a few seconds, why?

**Comment by AquilesCanta** [comment]
One of the possible reasons is that the seek is frame accurate. This means that if we seek into a non iframe, we need to decode and discard buffers until we are able to decode the sought frame. However we have perceived some difference with the ExtractorSampleSource, so we will look into this. I cannot guarantee this will happen soon, though. Perhaps @ojw28 can provide some insight later.

**Comment by ojw28** [comment]
For HLS playbacks, ExoPlayer will always re-buffer when a seek is performed. We may optimize this at some point in the future, but it's non-trivial. For DASH and SmoothStreaming optimizing seeks within the buffer is more straightforward, and ExoPlayer already optimizes for these cases.
