### ISSUE TITLE
HLS parsing assumes manifest resolution is actual video resolution

### ISSUE THREAD

**Issue by IanDBird** [google/ExoPlayer#1328]
The `DefaultHlsTrackSelector` makes use of `VideoFormatSelectorUtil.selectVideoFormatsForDefaultDisplay` to filter which playlist variants it considers as playable by the device. As you follow the code through, it ends up making use of `isFormatPlayable` (with the `Format` being the one built from the playlist) which eventually ends up in `MediaCodecUtil.isSizeAndRateSupportedV21` or `MediaCodecUtil.isSizeSupportedV21` specifying the width and height defined within the playlist.

This seems to suggest that the code is assuming the playlist resolution is the actual video resolution that needs to be decoded. However, the HLS spec actually suggests something different:

```
      RESOLUTION

      The value is a decimal-resolution describing the optimal pixel
      resolution at which to display all the video in the Variant
      Stream.
```

This can lead to an issue where the manifest can correctly define a display resolution that includes potentially odd-valued heights, or widths. We originally found this when attempting to play a video via HLS where the manifest reported a resolution of `720x405` with the actual video having an actual resolution of `720x404`. The variant is being stripped because the `MediaCodecInfo` will report that it can't handle this resolution due to the `mWidthAlignment` or `mHeightAlignment` requirements. However, as mentioned earlier, this is a display resolution, not the actual video resolution.

**Comment by ojw28** [comment]
Under what condition(s) would the optimal pixel resolution to display a video be anything other than the actual pixel resolution of the video? Stretching 404 pixels onto 405 pixels sounds like a bad idea to me. It seems more likely that the manifest was off-by-one by mistake.

**Comment by ojw28** [comment]
Closing.
