### ISSUE TITLE
Error after updating to ExoPlayer 1.5.5

### ISSUE THREAD

**Issue by rimeissner** [google/ExoPlayer#1329]
Hey,

after updating from 1.5.3 to 1.5.5 we are getting reports on Android 4.x devices with detachFromGLContext and attachToGLContext:

`Fatal Exception: java.lang.RuntimeException: Error during detachFromGLContext (see logcat for details)
       at android.graphics.SurfaceTexture.attachToGLContext(SurfaceTexture.java:237)
       at android.view.GLES20TextureLayer.setSurfaceTexture(GLES20TextureLayer.java:81)
       at android.view.HardwareRenderer$Gl20Renderer.setSurfaceTexture(HardwareRenderer.java:1583)
       at android.view.TextureView.getHardwareLayer(TextureView.java:393)
       at android.view.View.getDisplayList(View.java:12878)
       at android.view.View.getDisplayList(View.java:12964)`

We use a TextureView to render a video. We wrap the SurfaceTexture of the TextureView in a Surface and pass it to the ExoPlayer. We handle the lifecycle of the SurfaceTexture with a SurfaceTextureListener (will reset Surface if the SurfaceTexture is destroyed).

I am aware that this issue is not directly occurring in the ExoPlayer, but the only TextureView on this Activity is used for rendering a video with the ExoPlayer library and no errors occurred before the upgrade.

As we cannot reproduce locally, any help would be greatly appreciated.

Cheers

P.S.: some devices on which the errors occur are: HUAWEI H30 U10, Samsung SM T230NU, Samsung SM G530H, LGE LGMS323, ALCATEL ONE TOUCH 7041

**Comment by AquilesCanta** [comment]
Is is possible to obtain bugreport from the devices where this happens? In the meantime I will run some experiments to see whether I can guess what the problem is.

**Comment by rimeissner** [comment]
Hey, it seems that there were some code changes on our side, where we move the SurfaceTexture between TextureView (based on https://github.com/google/grafika/blob/master/src/com/android/grafika/DoubleDecodeActivity.java).

The library update was just at the same time where we introduced this. Sorry for the wrong report, this ticket can be closed.

**Comment by blueslabs** [comment]
@rimeissner, we are having the same issue by moving SurfaceTexture between TextureView. How did you solve the problem?

**Comment by rimeissner** [comment]
@blueslabs sorry to tell, but we never solved that and moved to a different solution as it was to error prone on older platforms
