### ISSUE TITLE
Support for Widevine Modular DRM on Android 4.3

### ISSUE THREAD

**Issue by hudys** [google/ExoPlayer#1330]
Your developer guide says that DRM is supported on Android 4.3 and higher and all Android device are required to support Widevine Modular DRM. However Widevine website mentions that "Widevine Modular DRM is available on all devices running Android 4.4 and later." (Source: https://www.widevine.com/product_news.html).

I would like to ask you if you have any information about support for Widevine Modular DRM on Android 4.3 (for example supported vendor and devices).

Thank you for you answer.

**Comment by kidmiracleman** [comment]
Although MediaDrm API is available from 4.3 onwards, only 4.4 + is guaranteed to provide general availability of the underlying Widevine CDM.

The Widevine CDM is only guaranteed to be available on the Nexus 5 device running 4.3 (Although from testing it appears to be supported on Nexus 7 also)

**Comment by wvpaf** [comment]
Question was answered.
