### ISSUE TITLE
Incorrect track duration reported for some MP4 streams using mutliple timescale values

### ISSUE THREAD

**Issue by dbedev** [google/ExoPlayer#1331]
First of all thanks to all for creating this library, it really accelerates android video stream application development. 

As discovered the exoplayer (version 1.5.5 ) it does not seem to report the correct duration for some of my MP4 streams.

Some investigation on my side shows the mp4 files the player is having issues with are using different timescale values for the audio and video tracks.  Not sure if this is completely compliant with the mp4 spec. So I can't really judge if this is problem with the files or a limitation/bug in the mp4 parser. 

Anyway traced it down to the "extractor/mp4/AtomParsers.java"    - "parseTrak" method.

In the "parseTrak" method it seems to use the timescale from the "mvhd" box together with the duration as reported in the "tkhd" box  which for my files with will result in a wrong duration in us for  the track in the container that is using a different timescale value then specified in the "mvhd" box.

I'm not an expert in MP4 but assuming mp4 allows to use different timescales(as it is reported in mutliple places) it seems more logical to use the timescale from the "mdhd" box specific to a track instead of using the timescale value from the  "mvhd"  box for calculating the track duration in Us.

For my files to start working correctly it was sufficient to simply use "mdhdData.first" instead of "movieTimescale" variable to calculate “durationUs”.

Will unfortunately not be allowed to share the videos having the issue thanks to content copyright :( .

Found mp4 files in which the track duration in "tkhd" is related to the timescale of  "mvhd" and found files where the duration in "tkhd"  is related to the  "mdhd" so safer seems to be to either take it completely from mdhd or mvhd.

**Comment by ojw28** [comment]
According to ISO 14496-16, the duration in the `trak` box is:

> An integer that indicates the duration of this track (in the timescale indicated in the Movie Header Box).

So in this case I think that the extractor is doing the right thing and that the media is incorrect.
