### ISSUE TITLE
DASH adaptive playback

### ISSUE THREAD

**Issue by ChernyshovYuriy** [google/ExoPlayer#1335]
Dear ExoPlayer developers,
I am experiencing a problem when stream DASH Widevine content when network throttling.
ExoPlayer selects higher variant from start and never drop that variant below in order to adapt to the network conditions.
For instance, there are 6 available variants in the playlist. I do throttling up to 256 kbps. I see from a Player callback (onBandwidthSample) that speed reduced:
Transferred 789629 bytes in 26440 ms with 238919 bits/sec
However, ExoPlayer stays on the highest variant. This cause unacceptable performance.
My question is - is adaption configurable somehow via DefaultBandwidthMeter or AdaptiveEvaluator or any other way? Because it is written in:
http://google.github.io/ExoPlayer/guide.html
Section "Adaptive media playbacks" that it do adaptive playback.
Thanks in advance.

**Comment by ChernyshovYuriy** [comment]
I have found an answer somehow ...
Let's consider variants that I are in playlist:
Type:VIDEO
                           format:MediaFormat(null, video/avc, -1, -1, -1, -1, -1, -1.0, -1, -1, null, 653850000, true, -1, -1, -1, -1)
                           format:MediaFormat(video=137000, video/avc, 137000, -1, 240, 128, -1, -1.0, -1, -1, null, 653850000, false, -1, -1, -1, -1)
                           format:MediaFormat(video=320000, video/avc, 320000, -1, 368, 208, -1, -1.0, -1, -1, null, 653850000, false, -1, -1, -1, -1)
                           format:MediaFormat(video=511000, video/avc, 511000, -1, 480, 272, -1, -1.0, -1, -1, null, 653850000, false, -1, -1, -1, -1)
                           format:MediaFormat(video=708000, video/avc, 708000, -1, 640, 352, -1, -1.0, -1, -1, null, 653850000, false, -1, -1, -1, -1)
                           format:MediaFormat(video=1196000, video/avc, 1196000, -1, 848, 480, -1, -1.0, -1, -1, null, 653850000, false, -1, -1, -1, -1)
                           format:MediaFormat(video=1793000, video/avc, 1793000, -1, 848, 480, -1, -1.0, -1, -1, null, 653850000, false, -1, -1, -1, -1)

If I select variant 0, then ExoPlayer do variant changing automatically, more precisely, it do up variant switch very smoothly!
However, if I select manually one of the available variants - ExoPlayer stays on the selected one no matter what network conditions are.
Is this expected behaviour?

**Comment by ojw28** [comment]
This is expected behavior. The first track has `MediaFormat.adaptive` set to true, indicating that it's an adaptive track. The other tracks are non-adaptive tracks, and are there to allow explicitly overriding/disabling the adaptive behavior.
