### ISSUE TITLE
Galaxy S6 and S6 Edge, output buffer flag issue

### ISSUE THREAD

**Issue by Bigcheese-** [google/ExoPlayer#1338]
The outputBufferInfo coming out the decoder on the two devices always have the flag set to 0 and never triggers the KeyFram flag! Is this a bug related to ExoPlayer somewhere or is it a hardware issue from the MediaCodec side?

**Comment by ojw28** [comment]
What does this have to do with ExoPlayer?

For what it's worth, that sounds working as intended to me. According to the [Javadoc](http://developer.android.com/reference/android/media/MediaCodec.BufferInfo.html#flags), BUFFER_FLAG_KEY_FRAME is only set on *encoded* buffers (e.g. output from an encoder, not from a decoder).
