### ISSUE TITLE
Amazon FireTV - MP4 playback fails (OMX.google.android.index.storeMetaDataInBuffers)

### ISSUE THREAD

**Issue by aravinds03** [google/ExoPlayer#1339]
- ### Description of the issue
This issue is fork of #180 . When playing mp4 files using ExtractorRendererBuilder, I can hear the audio, but video frames are getting dropped and hence video is not progressing. From the logs, the error message says 
 ```
E/OMX-VDEC-1080P: Extension: OMX.google.android.index.storeMetaDataInBuffers not implemented
03-04 13:24:25.812 379-861/? E/OMXNodeInstance: getExtensionIndex(3d:qcom.decoder.avc, OMX.google.android.index.storeMetaDataInBuffers) ERROR: NotImplemented(0x80001006)
03-04 13:24:25.812 22571-24436/com.google.android.exoplayer.demo E/ACodec: [OMX.qcom.video.decoder.avc] storeMetaDataInBuffers failed w/ err -2147483648
 ```

- ### Steps describing how the issue can be reproduced, ideally in the ExoPlayer demo app.
In the exoplayer demo app, replace mp4 file url under Misc->Dizzy to the one that I emailed.

- ### A link to content that reproduces the issue. 
Emailed the link to dev.exoplayer@gmail.com including the issue number in the subject line.

- ### The version of ExoPlayer being used.
1.5.6. I can reproduce in 1.5.5 as well.

- ### The device(s) and version(s) of Android on which the issue can be reproduced.
This issue happens in Amazon Fire TV (Android 5.1, API level 22) only and it happens consistently.
This issue does not happen in OnePlus 2 phone. 

- ### Bugreport.
Bug report taken from amazon fire tv is available here https://www.dropbox.com/s/o8ow44xo551yt0t/bugreport.txt?dl=1 .

**Comment by ojw28** [comment]
FireOS isn't "proper Android". If this is FireTV specific then you'll probably have to report it to Amazon directly, since it's likely an issue with their FireOS implementation.

**Comment by aravinds03** [comment]
This issue is fixed after using amazon customized exoplayer https://github.com/amzn/exoplayer-amazon-port.
