### ISSUE TITLE
The audio isn't played

### ISSUE THREAD

**Issue by IlyaMyasoedov** [google/ExoPlayer#1340]
The audio isn't played on my device.
1. Log: 
com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.audio.decoder.aac, MediaFormat(null, audio/mp4a-latm, -1, -1, -1, -1, -1, -1.0, 2, 44100, null, -1, false, -1, -1, -1, -1)
2. Device description:
Device: AW989_msm8625
Model (and Product): i-mobile IQ5.1A Pro (IQ5.1A Pro)
OS Version: 3.4.0-perf-g41ec439-02236-gede1361(i-mobile IQ5.1A Pro T22)
OS API Level: 16

**Comment by ojw28** [comment]
Closing because you haven't provided all of the information requested in the issue template. There's not enough information here for us to efficiently investigate the issue.
