### ISSUE TITLE
playing mp3 on call state

### ISSUE THREAD

**Issue by kunalbhatia** [google/ExoPlayer#1347]
I created a simple example of exoplayer using library, below is the code:

```
Uri uri = Uri.parse(url);
player = ExoPlayer.Factory.newInstance(1);
DataSource dataSource = new DefaultUriDataSource(this, "HungamaPlayer");
ExtractorSampleSource extractorSampleSource = new ExtractorSampleSource(uri, dataSource, new DefaultAllocator(64 * 1024), 64 * 1024 * 256);
MediaCodecAudioTrackRenderer audioRenderer = new MediaCodecAudioTrackRenderer(extractorSampleSource, MediaCodecSelector.DEFAULT);
player.prepare(audioRenderer);
player.setPlayWhenReady(true);
```
 
 
I’m playing a simple mp3 file, when I got a phone call, in ringing state song was not playing, but as soon as I picked up the call, song started playing in the middle of the phonecall. If this bug is solved previously please let me know how?
 
Thanks in Anticipation.

**Comment by AquilesCanta** [comment]
I think this is something that your application should handle. Specially considering there are many different ways to solve this. Perhaps [this](http://developer.android.com/training/managing-audio/audio-focus.html) can help.
