### ISSUE TITLE
m3u8 video playing without sound

### ISSUE THREAD

**Issue by dsahm** [google/ExoPlayer#1349]
Hello,

I have m3u8 video sources. The videos are being played but without sound.
This is a sample video:
http://carl.media/fileadmin/converted/vid_398/vid_398_SD.mp4

VLC Player says the video is encoded in H264/AAC. The sound does get played when using the standard Android video library.

I have implemented Exoplayer into our project with the help of the demo app and everything works finde except the sound. Any suggestions?

Here is more information on the file:

```
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'vid_398_SD.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    creation_time   : 2016-03-04 13:31:08
    encoder         : Lavf56.1.0
  Duration: 00:03:40.04, start: 0.000000, bitrate: 1102 kb/s
    Stream #0:0(eng): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 480x270, 896 kb/s, 25 fps, 25 tbr, 25 tbn, 50 tbc (default)
    Metadata:
      creation_time   : 2016-03-04 13:31:08
      handler_name    : VideoHandler
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 200 kb/s (default)
    Metadata:
      creation_time   : 2016-03-04 13:31:08
      handler_name    : SoundHandler
```

I have also added the link to the sample app. 

`new Sample("Test", "http://video.carl.media/videos/vid_398/index.m3u8", Util.TYPE_HLS),`

The video does get played like in my app but no sound.

Thanks,
Daniel

**Comment by dsahm** [comment]
Here is more information on the file:

Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'vid_398_SD.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    creation_time   : 2016-03-04 13:31:08
    encoder         : Lavf56.1.0
  Duration: 00:03:40.04, start: 0.000000, bitrate: 1102 kb/s
    Stream #0:0(eng): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 480x270, 896 kb/s, 25 fps, 25 tbr, 25 tbn, 50 tbc (default)
    Metadata:
      creation_time   : 2016-03-04 13:31:08
      handler_name    : VideoHandler
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 200 kb/s (default)
    Metadata:
      creation_time   : 2016-03-04 13:31:08
      handler_name    : SoundHandler

**Comment by ojw28** [comment]
This is tracked by https://github.com/google/ExoPlayer/issues/73 (which also covers handling de-muxed audio).
