### ISSUE TITLE
Growing latency for ExtractorSampleSource/DefaultUriDataSource

### ISSUE THREAD

**Issue by vuzya** [google/ExoPlayer#1350]
Hello.
Could you please answer a question:
I'm playing flv over http using ExtractorSampleSource/DefaultUriDataSource. Sometimes I have video freeze due to buffering. So with time I have delay between real time elapsed and playback time.
Is there some way to handle this buffering just like for live streams? My goal is to have video to be sync with real time elapsed.
Is there's no component in player to do that - could you please suggest what class(if any) could be an example for me if I should implement such a mechanism myself?

**Comment by ojw28** [comment]
We do not support this feature.
