### ISSUE TITLE
parseEsdsFromParent bug

### ISSUE THREAD

**Issue by mice777** [google/ExoPlayer#1351]
Version: 1.5.6
File: AtomParsers.java
Method: parseEsdsFromParent
Some .mp4 files won't be played because of this bug.

In 3 places in this function is need for "variable-sized-coded length", that is the code with "> 127" comparision.
First two lengths are ignored, last one is used and is computed wrong. The left-shift is by 8 bits, while it must be by 7. 
In most cases it works (for lengths < 128), in rare cases it produces invalid length and array overflow afterwards, making entire playback to fail.

Fix: add and use this function instead of ugly hack and code duplication:

```
   private static int readDescrLength(ParsableByteArray in){
         int b;
         int num_bytes = 0;
         int length = 0;
         do{
            b = in.readUnsignedByte();
            ++num_bytes;
            length = (length << 7) | (b & 0x7f);
         }while(b>=128 && num_bytes<4);
         return length;
      }
```

Call this in all 3 places.
Following is fix for entire function.
Also note added "case 0x69:" which adds support for mp3 audio in some files.

      /** Returns codec-specific initialization data contained in an esds box. */
      private static Pair<String, byte[]> parseEsdsFromParent(ParsableByteArray parent, int position){
         parent.setPosition(position + Atom.HEADER_SIZE + 4);
         // Start of the ES_Descriptor (defined in 14496-1)
         parent.skipBytes(1); // ES_Descriptor tag
         readDescrLength(parent);
         parent.skipBytes(2); // ES_ID

         int flags = parent.readUnsignedByte();
         if((flags & 0x80 /* streamDependenceFlag */) != 0){
            parent.skipBytes(2);
         }
         if((flags & 0x40 /* URL_Flag */) != 0){
            parent.skipBytes(parent.readUnsignedShort());
         }
         if((flags & 0x20 /* OCRstreamFlag */) != 0){
            parent.skipBytes(2);
         }

         // Start of the DecoderConfigDescriptor (defined in 14496-1)
         parent.skipBytes(1); // DecoderConfigDescriptor tag
         readDescrLength(parent);

         // Set the MIME type based on the object type indication (14496-1 table 5).
         int objectTypeIndication = parent.readUnsignedByte();
         String mimeType;
         switch(objectTypeIndication){
         case 0x6B:
         case 0x69:
            mimeType = MimeTypes.AUDIO_MPEG;
            return Pair.create(mimeType, null);
         case 0x20:
            mimeType = MimeTypes.VIDEO_MP4V;
            break;
         case 0x21:
            mimeType = MimeTypes.VIDEO_H264;
            break;
         case 0x23:
            mimeType = MimeTypes.VIDEO_H265;
            break;
         case 0x40:
         case 0x66:
         case 0x67:
         case 0x68:
            mimeType = MimeTypes.AUDIO_AAC;
            break;
         case 0xA5:
            mimeType = MimeTypes.AUDIO_AC3;
            break;
         case 0xA6:
            mimeType = MimeTypes.AUDIO_E_AC3;
            break;
         case 0xA9:
         case 0xAC:
            mimeType = MimeTypes.AUDIO_DTS;
            return Pair.create(mimeType, null);
         case 0xAA:
         case 0xAB:
            mimeType = MimeTypes.AUDIO_DTS_HD;
            return Pair.create(mimeType, null);
         default:
            mimeType = null;
            break;
         }

         parent.skipBytes(12); // streamType(1), bufferSizeDB(3), maxBitrate(4), avgBitrate(4)

         // Start of the AudioSpecificConfig.
         parent.skipBytes(1); // AudioSpecificConfig tag
         int varInt = readDescrLength(parent);
         byte[] initializationData = new byte[varInt];
         parent.readBytes(initializationData, 0, varInt);
         return Pair.create(mimeType, initializationData);
      }

**Comment by ojw28** [comment]
Could you attach sample content that's affected by this issue for us to verify/test with? Or email it to dev.exoplayer@gmail.com? Thanks!

**Comment by mice777** [comment]
Link sent by email, since testing file has 700MB
