### ISSUE TITLE
vp8+vorbis file can not be played (same file, different device with #1090) 

### ISSUE THREAD

**Issue by seu070507** [google/ExoPlayer#1355]
@ojw28 
[vp8+vorbis.mkv.zip](https://github.com/google/ExoPlayer/files/166712/vp8.vorbis.mkv.zip)
[bugreport.txt](https://github.com/google/ExoPlayer/files/166853/bugreport.txt)

I have report an bug issue in #1090 before. This bug has been fixed in the latest release version
However, with the same file, When I use the different device(Samsung GT-N7100 android 4.4.2),
it still can not be played with the video track on, the screen is black and just voice!
exoplayer version:r1.5.6
device:Samsung GT-N7100
android: 4.4.2

**Comment by seu070507** [comment]
logcat log:
03-10 16:53:56.430 21745-21745/com.google.android.exoplayer.demo E/ViewSystem: ViewRootImpl #2 Surface is not valid.
03-10 16:53:56.445 21745-21745/com.google.android.exoplayer.demo I/dalvikvm: Could not find method com.google.android.exoplayer.demo.PlayerActivity.requestPermissions, referenced from method com.google.android.exoplayer.demo.PlayerActivity.maybeRequestPermission
03-10 16:53:56.445 21745-21745/com.google.android.exoplayer.demo W/dalvikvm: VFY: unable to resolve virtual method 1449: Lcom/google/android/exoplayer/demo/PlayerActivity;.requestPermissions ([Ljava/lang/String;I)V
03-10 16:53:56.445 21745-21745/com.google.android.exoplayer.demo D/dalvikvm: VFY: replacing opcode 0x6e at 0x0010
03-10 16:53:56.450 21745-21745/com.google.android.exoplayer.demo I/dalvikvm: Could not find method com.google.android.exoplayer.demo.PlayerActivity.checkSelfPermission, referenced from method com.google.android.exoplayer.demo.PlayerActivity.requiresPermission
03-10 16:53:56.450 21745-21745/com.google.android.exoplayer.demo W/dalvikvm: VFY: unable to resolve virtual method 1416: Lcom/google/android/exoplayer/demo/PlayerActivity;.checkSelfPermission (Ljava/lang/String;)I
03-10 16:53:56.450 21745-21745/com.google.android.exoplayer.demo D/dalvikvm: VFY: replacing opcode 0x6e at 0x000e
03-10 16:53:56.500 21745-21745/com.google.android.exoplayer.demo I/dalvikvm: Could not find method android.view.accessibility.CaptioningManager$CaptionStyle.hasForegroundColor, referenced from method com.google.android.exoplayer.text.CaptionStyleCompat.createFromCaptionStyleV21
03-10 16:53:56.500 21745-21745/com.google.android.exoplayer.demo W/dalvikvm: VFY: unable to resolve virtual method 291: Landroid/view/accessibility/CaptioningManager$CaptionStyle;.hasForegroundColor ()Z
03-10 16:53:56.500 21745-21745/com.google.android.exoplayer.demo D/dalvikvm: VFY: replacing opcode 0x6e at 0x0002
03-10 16:53:56.500 21745-21745/com.google.android.exoplayer.demo D/dalvikvm: DexOpt: couldn't find field Landroid/view/accessibility/CaptioningManager$CaptionStyle;.windowColor
03-10 16:53:56.500 21745-21745/com.google.android.exoplayer.demo I/dalvikvm: DexOpt: unable to optimize instance field ref 0x002d at 0x18 in Lcom/google/android/exoplayer/text/CaptionStyleCompat;.createFromCaptionStyleV21
03-10 16:53:56.630 21745-21745/com.google.android.exoplayer.demo D/ProgressBar: setProgressDrawable drawableHeight = 32
03-10 16:53:56.660 21745-21745/com.google.android.exoplayer.demo D/AbsSeekBar: AbsSeekBar Constructor: misSeebarAnimationAvailable = false
03-10 16:53:56.680 21745-21745/com.google.android.exoplayer.demo I/ExoPlayerImpl: Init 1.5.6
03-10 16:53:56.690 21745-21745/com.google.android.exoplayer.demo D/EventLogger: start [0]
03-10 16:53:56.695 21745-21745/com.google.android.exoplayer.demo D/EventLogger: state [0.00, false, P]
03-10 16:53:56.730 21745-21745/com.google.android.exoplayer.demo I/dalvikvm: Could not find method android.media.MediaCodec.releaseOutputBuffer, referenced from method com.google.android.exoplayer.MediaCodecVideoTrackRenderer.renderOutputBufferV21
03-10 16:53:56.730 21745-21745/com.google.android.exoplayer.demo W/dalvikvm: VFY: unable to resolve virtual method 86: Landroid/media/MediaCodec;.releaseOutputBuffer (IJ)V
03-10 16:53:56.730 21745-21745/com.google.android.exoplayer.demo D/dalvikvm: VFY: replacing opcode 0x6e at 0x0008
03-10 16:53:56.745 21745-21745/com.google.android.exoplayer.demo E/dalvikvm: Could not find class 'android.media.PlaybackParams', referenced from method com.google.android.exoplayer.MediaCodecAudioTrackRenderer.handleMessage
03-10 16:53:56.745 21745-21745/com.google.android.exoplayer.demo W/dalvikvm: VFY: unable to resolve check-cast 51 (Landroid/media/PlaybackParams;) in Lcom/google/android/exoplayer/MediaCodecAudioTrackRenderer;
03-10 16:53:56.745 21745-21745/com.google.android.exoplayer.demo D/dalvikvm: VFY: replacing opcode 0x1f at 0x0015
03-10 16:53:56.755 21745-21745/com.google.android.exoplayer.demo I/dalvikvm: Could not find method android.media.AudioTrack.write, referenced from method com.google.android.exoplayer.audio.AudioTrack.writeNonBlockingV21
03-10 16:53:56.755 21745-21745/com.google.android.exoplayer.demo W/dalvikvm: VFY: unable to resolve virtual method 69: Landroid/media/AudioTrack;.write (Ljava/nio/ByteBuffer;II)I
03-10 16:53:56.755 21745-21745/com.google.android.exoplayer.demo D/dalvikvm: VFY: replacing opcode 0x6e at 0x0001
03-10 16:53:56.760 21745-21745/com.google.android.exoplayer.demo W/dalvikvm: VFY: unable to find class referenced in signature (Landroid/media/PlaybackParams;)
03-10 16:53:56.760 21745-21745/com.google.android.exoplayer.demo W/dalvikvm: VFY: unable to find class referenced in signature (Landroid/media/PlaybackParams;)
03-10 16:53:56.775 21745-21745/com.google.android.exoplayer.demo D/EventLogger: state [0.08, true, P]
03-10 16:53:56.950 21745-23045/com.google.android.exoplayer.demo I/dalvikvm: Could not find method android.media.MediaCodecInfo$CodecCapabilities.getVideoCapabilities, referenced from method com.google.android.exoplayer.MediaCodecUtil.getVideoCapabilitiesV21
03-10 16:53:56.950 21745-23045/com.google.android.exoplayer.demo W/dalvikvm: VFY: unable to resolve virtual method 91: Landroid/media/MediaCodecInfo$CodecCapabilities;.getVideoCapabilities ()Landroid/media/MediaCodecInfo$VideoCapabilities;
03-10 16:53:56.950 21745-23045/com.google.android.exoplayer.demo D/dalvikvm: VFY: replacing opcode 0x6e at 0x000c
03-10 16:53:56.965 21745-23045/com.google.android.exoplayer.demo I/dalvikvm: Could not find method android.media.MediaCodecInfo$VideoCapabilities.areSizeAndRateSupported, referenced from method com.google.android.exoplayer.MediaCodecUtil.isSizeAndRateSupportedV21
03-10 16:53:56.965 21745-23045/com.google.android.exoplayer.demo W/dalvikvm: VFY: unable to resolve virtual method 93: Landroid/media/MediaCodecInfo$VideoCapabilities;.areSizeAndRateSupported (IID)Z
03-10 16:53:56.965 21745-23045/com.google.android.exoplayer.demo D/dalvikvm: VFY: replacing opcode 0x6e at 0x0012
03-10 16:53:56.985 21745-23045/com.google.android.exoplayer.demo I/dalvikvm: Could not find method android.media.MediaCodecInfo$VideoCapabilities.isSizeSupported, referenced from method com.google.android.exoplayer.MediaCodecUtil.isSizeSupportedV21
03-10 16:53:56.985 21745-23045/com.google.android.exoplayer.demo W/dalvikvm: VFY: unable to resolve virtual method 94: Landroid/media/MediaCodecInfo$VideoCapabilities;.isSizeSupported (II)Z
03-10 16:53:56.985 21745-23045/com.google.android.exoplayer.demo D/dalvikvm: VFY: replacing opcode 0x6e at 0x0012
03-10 16:53:57.015 21745-23045/com.google.android.exoplayer.demo I/OMXClient: Using client-side OMX mux.
03-10 16:53:57.045 21745-23045/com.google.android.exoplayer.demo I/OMXClient: Using client-side OMX mux.
03-10 16:53:57.095 21745-23045/com.google.android.exoplayer.demo W/linker: libsraxxd.so has text relocations. This is wasting memory and is a security risk. Please fix.
03-10 16:53:57.105 21745-23045/com.google.android.exoplayer.demo I/OMX: mDispatchers.add
03-10 16:53:57.115 21745-23045/com.google.android.exoplayer.demo I/ACodec:  [] Now uninitialized
03-10 16:53:57.120 21745-23063/com.google.android.exoplayer.demo I/OMXClient: Using client-side OMX mux.
03-10 16:53:57.125 21745-23063/com.google.android.exoplayer.demo I/ACodec: [OMX.SEC.vp8.dec] Now Loaded
03-10 16:53:57.130 21745-23063/com.google.android.exoplayer.demo E/ACodec: [OMX.SEC.vp8.dec] storeMetaDataInBuffers failed w/ err -2147483648
03-10 16:53:57.130 21745-23063/com.google.android.exoplayer.demo I/ACodec: [OMX.SEC.vp8.dec] Now Loaded->Idle
03-10 16:53:57.135 21745-23063/com.google.android.exoplayer.demo I/ACodec: [OMX.SEC.vp8.dec] Now Idle->Executing
03-10 16:53:57.140 21745-23063/com.google.android.exoplayer.demo I/ACodec: [OMX.SEC.vp8.dec] Now Executing
03-10 16:53:57.145 21745-23045/com.google.android.exoplayer.demo I/ACodec:  [] Now uninitialized
03-10 16:53:57.145 21745-23068/com.google.android.exoplayer.demo I/OMXClient: Using client-side OMX mux.
03-10 16:53:57.185 21745-21745/com.google.android.exoplayer.demo D/EventLogger: state [0.49, true, B]
03-10 16:53:57.185 21745-21745/com.google.android.exoplayer.demo D/EventLogger: decoderInitialized [0.49, OMX.SEC.vp8.dec]
03-10 16:53:57.195 21745-23068/com.google.android.exoplayer.demo W/linker: libsraxxd.so has text relocations. This is wasting memory and is a security risk. Please fix.
03-10 16:53:57.200 21745-23068/com.google.android.exoplayer.demo I/OMX: mDispatchers.add
03-10 16:53:57.200 21745-23068/com.google.android.exoplayer.demo I/ACodec: [OMX.google.vorbis.decoder] Now Loaded
03-10 16:53:57.205 21745-23068/com.google.android.exoplayer.demo I/ACodec: [OMX.google.vorbis.decoder] Now Loaded->Idle
03-10 16:53:57.210 21745-23068/com.google.android.exoplayer.demo I/ACodec: [OMX.google.vorbis.decoder] Now Idle->Executing
03-10 16:53:57.210 21745-23068/com.google.android.exoplayer.demo I/ACodec: [OMX.google.vorbis.decoder] Now Executing
03-10 16:53:57.210 21745-23068/com.google.android.exoplayer.demo I/ACodec: [OMX.google.vorbis.decoder] Now handling output port settings change
03-10 16:53:57.215 21745-23068/com.google.android.exoplayer.demo I/ACodec: [OMX.google.vorbis.decoder] Now Executing
03-10 16:53:57.295 21745-21745/com.google.android.exoplayer.demo D/EventLogger: decoderInitialized [0.60, OMX.google.vorbis.decoder]
03-10 16:53:57.395 21745-21745/com.google.android.exoplayer.demo D/EventLogger: videoSizeChanged [640, 640, 0, 1.0]
03-10 16:53:57.525 21745-21745/com.google.android.exoplayer.demo D/EventLogger: state [0.83, true, R]
03-10 16:53:57.735 21745-23048/com.google.android.exoplayer.demo D/dalvikvm: GC_FOR_ALLOC freed 466K, 14% free 10858K/12548K, paused 17ms, total 17ms
03-10 16:53:58.110 21745-23048/com.google.android.exoplayer.demo D/dalvikvm: GC_FOR_ALLOC freed 43K, 13% free 11410K/13092K, paused 18ms, total 18ms
03-10 16:53:59.550 21745-23048/com.google.android.exoplayer.demo D/dalvikvm: GC_FOR_ALLOC freed 13K, 13% free 12115K/13840K, paused 14ms, total 14ms
03-10 16:53:59.855 21745-23048/com.google.android.exoplayer.demo D/dalvikvm: GC_FOR_ALLOC freed 13K, 12% free 13076K/14792K, paused 18ms, total 18ms
03-10 16:54:00.290 21745-23048/com.google.android.exoplayer.demo D/dalvikvm: GC_FOR_ALLOC freed 15K, 11% free 14294K/16016K, paused 15ms, total 15ms
03-10 16:54:00.725 21745-21745/com.google.android.exoplayer.demo D/ProgressBar: updateDrawableBounds: left = 0
03-10 16:54:00.730 21745-21745/com.google.android.exoplayer.demo D/ProgressBar: updateDrawableBounds: top = 0
03-10 16:54:00.730 21745-21745/com.google.android.exoplayer.demo D/ProgressBar: updateDrawableBounds: right = 480
03-10 16:54:00.730 21745-21745/com.google.android.exoplayer.demo D/ProgressBar: updateDrawableBounds: bottom = 64
03-10 16:54:00.730 21745-21745/com.google.android.exoplayer.demo D/ProgressBar: updateDrawableBounds: mProgressDrawable.setBounds()
03-10 16:54:01.230 21745-21750/com.google.android.exoplayer.demo I/dalvikvm: threadid=3: reacting to signal 3
03-10 16:54:01.290 21745-21750/com.google.android.exoplayer.demo I/dalvikvm: Wrote stack traces to '/data/anr/traces.txt'
03-10 16:54:11.715 21745-21745/com.google.android.exoplayer.demo D/EventLogger: state [15.02, true, E]

**Comment by ojw28** [comment]
This is the same as https://github.com/google/ExoPlayer/issues/548. We'll add Note 2 to also receive the workaround.
