### ISSUE TITLE
Multiple Instances for ExoPlayer

### ISSUE THREAD

**Issue by gaganjawa** [google/ExoPlayer#1357]
Does **ExoPlayer** support multiple  **HLS** videos on a single activity ?
I am trying to play multiple videos(currently two) from one activity.  One of the video plays fine but for the other one , **unable to initiate decoder** `OMX.Google.xxxx` appears.
 How can I solve this ?

**Comment by andrewlewis** [comment]
See #273. Though it is possible to create and use more than one player at the same time on many devices, unfortunately there are some devices where this doesn't work.

You may be able to work around the limitation by using software codecs, but this is very inefficient. Also, based on your comment, the device is already trying to use a `OMX.google.` software decoder, so even that appears not to work. On what device did you see the error message?

**Comment by gaganjawa** [comment]
It was on Nexus 5x. 
It showed unable to initialize OMX.google.H264 decoder. 
Isn't there any reliable way to achieve this ?

**Comment by andrewlewis** [comment]
I don't know of a reliable way that works for all formats across all devices/builds, except using a software codec.
