### ISSUE TITLE
Audio capture for visualiser

### ISSUE THREAD

**Issue by m1c999** [google/ExoPlayer#1359]
Hi, I am trying to understand how to capture the audio to render a waveform on an OpenGL canvas but cannot see an obvious way of achieving this.

However, somebody suggested that it seems possible to implement by extending the
MediaCodecAudioTrackRenderer class as it has a processOutputBuffer() method. This method seems like it would be the correct entry point to capture or even modify output audio data.

Can anybody advise or point me in the right direction?  

This is not a defect - more of an enhancement which could be solved with documentation or comments

**Comment by ojw28** [comment]
It sounds like you're on the right track already, but you'll have to figure it out for yourself or ask somewhere more appropriate like StackOverflow. Our team doesn't scale to help with this kind of request. It's also not in our remit to add documentation/comments to the codebase indicating how features that we don't support might be implemented.
