### ISSUE TITLE
Webm/MKV extractor should support correct pixel aspect ratio

### ISSUE THREAD

**Issue by mice777** [google/ExoPlayer#1360]
Problem: Some MKV files have defined "display width/height" which may be different than pixel width/height. Current Webm extractor ignores that, resulting in stretched video.

File: WebmExtractor.java

Needed fixes:

- below line with "ID_PIXEL_HEIGHT = 0xBA;" add:
private static final int ID_DISPLAY_WIDTH = 0x54b0, ID_DISPLAY_HEIGHT = 0x54ba;
- add fields into Track class: int displayWidth = -1, displayHeight = -1;
- where ID_PIXEL_WIDTH and ID_PIXEL_HEIGHT are referenced to read width/height, add code to read and store fields displayWidth and displayHeight stored into currentTrack (methods integerElement and getElementType):
`   case ID_DISPLAY_WIDTH: currentTrack.displayWidth = (int)value; return;
   case ID_DISPLAY_HEIGHT: currentTrack.displayHeight = (int)value; return;`
- in Track.initializeOutput where MediaFormat.createVideoFormat is called, replace that statement by code:
`float pixelWidthRatio = MediaFormat.NO_VALUE;
            if(displayWidth>0 && displayHeight>0) {
               float sizeRatio = (float)width/height;
               float displayRatio = (float)displayWidth/displayHeight;
               pixelWidthRatio = displayRatio/sizeRatio;
            }
            format = MediaFormat.createVideoFormat(Integer.toString(trackId), mimeType, MediaFormat.NO_VALUE, maxInputSize, durationUs, width, height, initializationData, MediaFormat.NO_VALUE, pixelWidthRatio);`

That's it. Now correct pixel ratio is used as defined in some MKV files.

**Comment by mice777** [comment]
This is testing file to see the problem.
[AspectRatioTest.zip](https://github.com/google/ExoPlayer/files/168010/AspectRatioTest.zip)

**Comment by ojw28** [comment]
Thanks for the report! Your solution isn't quite complete because it doesn't take into account the possible default values for displayWidth and displayHeight (it would be valid to specify only one of them and have the other default from the corresponding pixel dimension). I'll add in some additional logic for that and merge a fix. Thanks!
