### ISSUE TITLE
minifyEnabled true proguard issue

### ISSUE THREAD

**Issue by j-t-h** [google/ExoPlayer#1361]
I am using ExoPlayer - com.google.android.exoplayer:exoplayer:r1.5.6

When generating a signed .apk I am getting these errors

```
Warning:com.google.android.exoplayer.MediaCodecAudioTrackRenderer: can't find referenced class android.media.PlaybackParams
Warning:com.google.android.exoplayer.audio.AudioTrack: can't find referenced class android.media.PlaybackParams
Warning:com.google.android.exoplayer.audio.AudioTrack$AudioTrackUtil: can't find referenced class android.media.PlaybackParams
Warning:com.google.android.exoplayer.audio.AudioTrack$AudioTrackUtilV23: can't find referenced class android.media.PlaybackParams
Warning:com.google.android.exoplayer.audio.AudioTrack$AudioTrackUtilV23: can't find referenced method 'void setPlaybackParams(android.media.PlaybackParams)' in library class android.media.AudioTrack
Warning:com.google.android.exoplayer.audio.AudioTrack$AudioTrackUtilV23: can't find referenced class android.media.PlaybackParams
Warning:com.google.android.exoplayer.chunk.VideoFormatSelectorUtil: can't find referenced method 'android.view.Display$Mode getMode()' in library class android.view.Display
Warning:com.google.android.exoplayer.chunk.VideoFormatSelectorUtil: can't find referenced class android.view.Display$Mode
```

If I comment out //minifyEnabled true .apk is generated without issue.

ExoPlayer is in a library package that is included in the "main" app package.

Any help appreciated.

**Comment by ojw28** [comment]
Are they even errors? I wouldn't expect something that's only a warning to prevent the apk from being generated. Note that the classes that aren't found are android library classes that were new in API level 23. Are you sure you're not using an out of date sdk?

**Comment by ojw28** [comment]
You need to target API level 23.

**Comment by ojw28** [comment]
Actually, I'm not certain about that. Proguard's troubleshooting page has a section on this [here](http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedclass). The relevant sentence being:

> If the missing class is an Android run-time class, you should make sure that you are building against an Android run-time that is sufficiently recent. You may need to change the build target in your project.properties file or build.gradle file to that recent version. You can still specify a different minSdkVersion and a different targetSdkVersion in your AndroidManifest.xml file.

**Comment by j-t-h** [comment]
So I changed compileSdkVersion 23 and left targetSdkVersion 22 and it works. Thanks for the help!

**Comment by j-t-h** [comment]
and of course targetSdkVersion 23 works also
