### ISSUE TITLE
Support UTF-16 srt files

### ISSUE THREAD

**Issue by anphunl** [google/ExoPlayer#1362]
I tried to add an external srt file to play.

My code : 

> MediaFormat mediaFormat = MediaFormat.createTextFormat("0", MimeTypes.APPLICATION_SUBRIP, MediaFormat.NO_VALUE, C.MATCH_LONGEST_US, null);
      Uri uri = Uri.parse("http://s.vn-hd.com:8080/store_06_2013/15062013/Rio_2011_1080p_2D_Bluray_DTS_x264_DON/Rio_2011_1080p_2D_Bluray_DTS_x264_DON_VIE.srt");
      DataSource textDataSource = new DefaultUriDataSource(context, bandwidthMeter, userAgent);
      SingleSampleSource textSampleSource = new SingleSampleSource(uri, textDataSource, mediaFormat);
      TrackRenderer textRenderer = new TextTrackRenderer(textSampleSource, player, player.getMainHandler().getLooper());
//...
renderers[DemoPlayer.TYPE_TEXT] = textRenderer;

It didn't show the subtitle, but returns errors in the console: Skipping invalid index: ��1��

**Comment by ojw28** [comment]
The file looks like it's UTF-16 encoded to me. We only support UTF-8. For what it's worth, several text editors on my machine are also unable to open this file (I could open it in emacs though). I converted it to UTF-8 and it worked fine.

**Comment by anphunl** [comment]
@ojw28 : Thank you for your note. How should we handle this situation? Do we have any way to detect its encoding?

**Comment by ojw28** [comment]
Someone could add UTF-16 srt support to ExoPlayer. It's unclear whether it's really worthwhile though. It's not high priority for us, in any case.

**Comment by anphunl** [comment]
@ojw28 : I use juniversalchardet to detect charset encoding of the stream, then use Scanner to parse SRT.

> compile 'com.googlecode.juniversalchardet:juniversalchardet:1.0.3'

Please check my file [https://github.com/anphunl/ExoPlayer/blob/master/library/src/main/java/com/google/android/exoplayer/text/subrip/SubripParser.java](Here).

I think we can merge it to the dev branch.

**Comment by ojw28** [comment]
We cannot merge things that take dependencies such as `org.mozilla.universalchardet`

**Comment by ojw28** [comment]
Closing for now because I don't think there's sufficient demand to merit spending time on this. If anyone wishes to send a pull request that adds support without taking any external dependencies (as was the case with the suggested change above), then feel free to do so, and we'd likely be happy merging it. Thanks!
