### ISSUE TITLE
HlsChunkSource wrong string comparison.

### ISSUE THREAD

**Issue by ChernyshovYuriy** [google/ExoPlayer#1363]
ExoPlayer version 1.5.6
In the **HlsChunkSource.java** there is wrong compare of the Strings.
Method:
`void getChunkOperation(TsChunk previousTsChunk, long playbackPositionUs, ChunkOperationHolder out)`
Lines 508 and 511
There is:
`MimeTypes.getAudioMediaMimeType(codecs) != MimeTypes.AUDIO_AAC`
and
`MimeTypes.getVideoMediaMimeType(codecs) != MimeTypes.VIDEO_H264`
which is wrong as you comparing references, not values.
Must be:
`!TextUtils.equals(MimeTypes.getAudioMediaMimeType(codecs), MimeTypes.AUDIO_AAC)`
and 
`!TextUtils.equals(MimeTypes.getVideoMediaMimeType(codecs), MimeTypes.VIDEO_H264`

**Comment by ojw28** [comment]
There's not actually a bug here. The static MimeType methods return the constants defined in MimeTypes, so doing referential equality checks against those same constants is valid.

**Comment by ChernyshovYuriy** [comment]
Right, my bad, but it is little implicitly :-)
Suppose  getAudioMediaMimeType() method will be changed, and there will be different person who will do that, it might be not so obvious for him as well.
I am fine with current implementation but this could be confusing as well in future.
P.S.
Thanks for response.

**Comment by ojw28** [comment]
It is true that it's a little error prone, as a pattern. We'll update to use the `MimeTypes.CONSTANT.equals(variable)` pattern at some point.

**Comment by ojw28** [comment]
Marking as a bug just so that we remember to fix it.

**Comment by ojw28** [comment]
The referential equality checks are gone in V2 (which isn't available on GitHub yet, but will be before too long). Closing since we've cleaned this up, and it's not actually a bug in V1.
