### ISSUE TITLE
Segment throughput calculation

### ISSUE THREAD

**Issue by bayantaani** [google/ExoPlayer#1368]
Hello,

I am trying to get the throughput for each chunk downloaded. In DefaultBandwidthMeter.OnTransferEnd(), there's bitsPerSecond that divides the bytes transferred by the elapsed time. However, As I read in [this issue](https://github.com/google/ExoPlayer/issues/1012)  that segment fetches may be batched together, so streamCount does not represent a fixed number of segments, which means that this estimate does not represent the value that I want all the time. Is there a place in the code where I can calculate the segment throughput as "in segment size divided by the time it took to download this segment"?

Thanks.

**Comment by ojw28** [comment]
DefaultBandwidthMeter invokes its listener with `onBandwidthSample` when a bandwidth estimate becomes available. It's true that each invocation may not correspond directly to a single chunk fetch, but then it's unclear why it would be a good idea to do that in the first place. If chunks are being downloaded in parallel in an overlapping way, then dividing the size of a chunk by the time it took to download it doesn't seem particularly useful. The bandwidth estimate you end up with ignores the fact that other data may or may not have been downloaded in parallel. Note there are other complexities too, such as if a chunk fetch failed half way through and had to be resumed via a retry mechanism.

What is is that you're actually trying to achieve? Is this for DASH or for HLS?

**Comment by bayantaani** [comment]
I want my app to estimate the available bandwidth regardless of the chunk size. Logically, and at a certain time, if I fetch a high quality chunk A the throughput is:
size_A/time_A = bw_A
or for a low quality chunk B:
size_B/time_B = bw_B
Assuming they occur under the same network conditions, bw_A and bw_B should be almost equal. However, when I restrict the video bitrate to a certain value, the estimated available bandwidth appears as if it's trying to match the video bitrate. So I thought maybe I can keep it stream adaptively, and for each played segment I can calculate its throughput.

**Comment by ojw28** [comment]
I don't really understand. DefaultBandwidthMeter's estimate is a already a bandwidth estimate that's independent of chunk size. What specifically is wrong with the estimates that it provides?

**Comment by bayantaani** [comment]
I'm sorry I was misunderstanding the difference between the throughput of a segment and the available bandwidth (how much the channel can carry). What I want to measure is the the available bandwidth, so I did a little research and it seems that we have to saturate the channel with packets to be able to measure it.
