### ISSUE TITLE
Non-Seamless sliding Animation issue when using Exoplayer

### ISSUE THREAD

**Issue by giridharkannan** [google/ExoPlayer#1371]
Am trying to build a kiosk app which would play images and videos in loop by using same Activity with view swapping. If a video had been played then any media transition after that shutters, even if no video is been played later on (setting AspectRatioFrameLayout view as GONE once video is finished). 

This issue is not occurring in my mobile but only in Android TV box mini-mx.

ExoPlayer Version: r1.5.4
Device: mini-mx (android version 5.1.1)
[when_showing_video.txt](https://github.com/google/ExoPlayer/files/172543/when_showing_video.txt)
[before_video.txt](https://github.com/google/ExoPlayer/files/172544/before_video.txt)
[after_video.txt](https://github.com/google/ExoPlayer/files/172545/after_video.txt)

Am attaching my SurfaceFlinger dump

**Comment by sbaar** [comment]
It would help to have a video. Try using a TextureView rather than a SurfaceView.

**Comment by ojw28** [comment]
To help with this kind of issue we really need an easy way of reproducing the problem. It's unclear whether this is even an ExoPlayer issue, as opposed to either an application bug or a device specific issue. My guess would be that the latter is most likely. Please check with the device manufacturer that it passes Android's Compatibility Test Suite.
