### ISSUE TITLE
Internal error with .m3u8 4k resolution video 

### ISSUE THREAD

**Issue by gbadoual** [google/ExoPlayer#1375]
I'm trying to play 4k video .m3u8 on device who can play 4k video files.
But I the exoplayer try automatically to play the highest resolution, even on device who can't play 4k.

How can I specify to downgrade the resolution wanted to play automatically the right resolution adapted to each device.

I want to avoid "Internal error" returned by exoplayer when we set a specific .m3u8 with several resolutions and choose the one adpated to the device to avoid this error :

`03-15 23:07:35.085 14539-16155/com.app_tizr.rg2016.app:RGVRProcess I/OMXClient: Using client-side OMX mux.
03-15 23:07:35.455 14539-16154/com.app_tizr.rg2016.app:RGVRProcess I/MediaCodec: [OMX.qcom.video.decoder.avc] setting surface generation to 14887937
03-15 23:07:35.455 14539-16155/com.app_tizr.rg2016.app:RGVRProcess W/ExtendedACodec: Failed to get extension for PASSINPUTBUFFERFD
03-15 23:07:35.465 14539-16155/com.app_tizr.rg2016.app:RGVRProcess I/ExtendedACodec: setupVideoDecoder()
03-15 23:07:35.465 14539-16155/com.app_tizr.rg2016.app:RGVRProcess I/ExtendedACodec: vpp-enable search is 0 and value is 0
03-15 23:07:35.475 14539-16155/com.app_tizr.rg2016.app:RGVRProcess E/ACodec: [OMX.qcom.video.decoder.avc] configureCodec returning error -1010
03-15 23:07:35.475 14539-16155/com.app_tizr.rg2016.app:RGVRProcess E/ACodec: signalError(omxError 0x80001001, internalError -1010)
03-15 23:07:35.475 14539-16154/com.app_tizr.rg2016.app:RGVRProcess E/MediaCodec: Codec reported err 0xfffffc0e, actionCode 0, while in state 3
03-15 23:07:35.475 14539-16140/com.app_tizr.rg2016.app:RGVRProcess E/MediaCodec: configure failed with err 0xfffffc0e, resetting...
03-15 23:07:35.495 14539-16155/com.app_tizr.rg2016.app:RGVRProcess I/OMXClient: Using client-side OMX mux.
03-15 23:07:35.535 14539-14539/com.app_tizr.rg2016.app:RGVRProcess E/EventLogger: internalError [1.24, decoderInitializationError]
03-15 23:07:35.535 14539-14539/com.app_tizr.rg2016.app:RGVRProcess E/EventLogger: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, MediaFormat(1, video/avc, -1, -1, 3840, 1920, 0, 1.0, -1, -1, null, 60034000, false, -1, -1)
03-15 23:07:35.535 14539-14539/com.app_tizr.rg2016.app:RGVRProcess E/EventLogger:     at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:346)
03-15 23:07:35.535 14539-14539/com.app_tizr.rg2016.app:RGVRProcess E/EventLogger:     at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:709)
03-15 23:07:35.535 14539-14539/com.app_tizr.rg2016.app:RGVRProcess E/EventLogger:     at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:391)
03-15 23:07:35.535 14539-14539/com.app_tizr.rg2016.app:RGVRProcess E/EventLogger:     at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:470)
03-15 23:07:35.535 14539-14539/com.app_tizr.rg2016.app:RGVRProcess E/EventLogger:     at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:451)
03-15 23:07:35.535 14539-14539/com.app_tizr.rg2016.app:RGVRProcess E/EventLogger:     at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431)
03-15 23:07:35.535 14539-14539/com.app_tizr.rg2016.app:RGVRProcess E/EventLogger:     at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
03-15 23:07:35.535 14539-14539/com.app_tizr.rg2016.app:RGVRProcess E/EventLogger:     at android.os.Handler.dispatchMessage(Handler.java:98)
03-15 23:07:35.535 14539-14539/com.app_tizr.rg2016.app:RGVRProcess E/EventLogger:     at android.os.Looper.loop(Looper.java:148)
03-15 23:07:35.535 14539-14539/com.app_tizr.rg2016.app:RGVRProcess E/EventLogger:     at android.os.HandlerThread.run(HandlerThread.java:61)
03-15 23:07:35.535 14539-14539/com.app_tizr.rg2016.app:RGVRProcess E/EventLogger:     at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
03-15 23:07:35.535 14539-14539/com.app_tizr.rg2016.app:RGVRProcess E/EventLogger:  Caused by: android.media.MediaCodec$CodecException: Error 0xfffffc0e
03-15 23:07:35.535 14539-14539/com.app_tizr.rg2016.app:RGVRProcess E/EventLogger:     at android.media.MediaCodec.native_configure(Native Method)
03-15 23:07:35.535 14539-14539/com.app_tizr.rg2016.app:RGVRProcess E/EventLogger:     at android.media.MediaCodec.configure(MediaCodec.java:1778)
03-15 23:07:35.535 14539-14539/com.app_tizr.rg2016.app:RGVRProcess E/EventLogger:     at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.configureCodec(MediaCodecVideoTrackRenderer.java:385)
03-15 23:07:35.535 14539-14539/com.app_tizr.rg2016.app:RGVRProcess E/EventLogger:     at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:334)
03-15 23:07:35.535 14539-14539/com.app_tizr.rg2016.app:RGVRProcess E/EventLogger:     at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:709) 
03-15 23:07:35.535 14539-14539/com.app_tizr.rg2016.app:RGVRProcess E/EventLogger:     at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:391) 
03-15 23:07:35.535 14539-14539/com.app_tizr.rg2016.app:RGVRProcess E/EventLogger:     at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:470) 
03-15 23:07:35.535 14539-14539/com.app_tizr.rg2016.app:RGVRProcess E/EventLogger:     at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:451) 
03-15 23:07:35.535 14539-14539/com.app_tizr.rg2016.app:RGVRProcess E/EventLogger:     at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431) 
03-15 23:07:35.535 14539-14539/com.app_tizr.rg2016.app:RGVRProcess E/EventLogger:     at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213) 
03-15 23:07:35.535 14539-14539/com.app_tizr.rg2016.app:RGVRProcess E/EventLogger:     at android.os.Handler.dispatchMessage(Handler.java:98) 
03-15 23:07:35.535 14539-14539/com.app_tizr.rg2016.app:RGVRProcess E/EventLogger:     at android.os.Looper.loop(Looper.java:148) 
03-15 23:07:35.535 14539-14539/com.app_tizr.rg2016.app:RGVRProcess E/EventLogger:     at android.os.HandlerThread.run(HandlerThread.java:61) 
03-15 23:07:35.535 14539-14539/com.app_tizr.rg2016.app:RGVRProcess E/EventLogger:     at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 
03-15 23:07:35.535 14539-16140/com.app_tizr.rg2016.app:RGVRProcess E/ExoPlayerImplInternal: Internal track renderer error.
03-15 23:07:35.535 14539-16140/com.app_tizr.rg2016.app:RGVRProcess E/ExoPlayerImplInternal: com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, MediaFormat(1, video/avc, -1, -1, 3840, 1920, 0, 1.0, -1, -1, null, 60034000, false, -1, -1)
03-15 23:07:35.535 14539-16140/com.app_tizr.rg2016.app:RGVRProcess E/ExoPlayerImplInternal:     at com.google.android.exoplayer.MediaCodecTrackRenderer.notifyAndThrowDecoderInitError(MediaCodecTrackRenderer.java:359)
03-15 23:07:35.535 14539-16140/com.app_tizr.rg2016.app:RGVRProcess E/ExoPlayerImplInternal:     at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:346)
03-15 23:07:35.535 14539-16140/com.app_tizr.rg2016.app:RGVRProcess E/ExoPlayerImplInternal:     at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:709)
03-15 23:07:35.535 14539-16140/com.app_tizr.rg2016.app:RGVRProcess E/ExoPlayerImplInternal:     at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:391)
03-15 23:07:35.535 14539-16140/com.app_tizr.rg2016.app:RGVRProcess E/ExoPlayerImplInternal:     at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:470)
03-15 23:07:35.535 14539-16140/com.app_tizr.rg2016.app:RGVRProcess E/ExoPlayerImplInternal:     at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:451)
03-15 23:07:35.535 14539-16140/com.app_tizr.rg2016.app:RGVRProcess E/ExoPlayerImplInternal:     at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431)
03-15 23:07:35.535 14539-16140/com.app_tizr.rg2016.app:RGVRProcess E/ExoPlayerImplInternal:     at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
03-15 23:07:35.535 14539-16140/com.app_tizr.rg2016.app:RGVRProcess E/ExoPlayerImplInternal:     at android.os.Handler.dispatchMessage(Handler.java:98)
03-15 23:07:35.535 14539-16140/com.app_tizr.rg2016.app:RGVRProcess E/ExoPlayerImplInternal:     at android.os.Looper.loop(Looper.java:148)
03-15 23:07:35.535 14539-16140/com.app_tizr.rg2016.app:RGVRProcess E/ExoPlayerImplInternal:     at android.os.HandlerThread.run(HandlerThread.java:61)
03-15 23:07:35.535 14539-16140/com.app_tizr.rg2016.app:RGVRProcess E/ExoPlayerImplInternal:     at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
03-15 23:07:35.535 14539-16140/com.app_tizr.rg2016.app:RGVRProcess E/ExoPlayerImplInternal:  Caused by: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, MediaFormat(1, video/avc, -1, -1, 3840, 1920, 0, 1.0, -1, -1, null, 60034000, false, -1, -1)
03-15 23:07:35.535 14539-16140/com.app_tizr.rg2016.app:RGVRProcess E/ExoPlayerImplInternal:     at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:346) 
03-15 23:07:35.535 14539-16140/com.app_tizr.rg2016.app:RGVRProcess E/ExoPlayerImplInternal:     at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:709) 
03-15 23:07:35.535 14539-16140/com.app_tizr.rg2016.app:RGVRProcess E/ExoPlayerImplInternal:     at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:391) 
03-15 23:07:35.535 14539-16140/com.app_tizr.rg2016.app:RGVRProcess E/ExoPlayerImplInternal:     at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:470) 
03-15 23:07:35.535 14539-16140/com.app_tizr.rg2016.app:RGVRProcess E/ExoPlayerImplInternal:     at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:451) 
03-15 23:07:35.535 14539-16140/com.app_tizr.rg2016.app:RGVRProcess E/ExoPlayerImplInternal:     at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431) 
03-15 23:07:35.535 14539-16140/com.app_tizr.rg2016.app:RGVRProcess E/ExoPlayerImplInternal:     at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213) 
03-15 23:07:35.535 14539-16140/com.app_tizr.rg2016.app:RGVRProcess E/ExoPlayerImplInternal:     at android.os.Handler.dispatchMessage(Handler.java:98) 
03-15 23:07:35.535 14539-16140/com.app_tizr.rg2016.app:RGVRProcess E/ExoPlayerImplInternal:     at android.os.Looper.loop(Looper.java:148) 
03-15 23:07:35.535 14539-16140/com.app_tizr.rg2016.app:RGVRProcess E/ExoPlayerImplInternal:     at android.os.HandlerThread.run(HandlerThread.java:61) 
03-15 23:07:35.535 14539-16140/com.app_tizr.rg2016.app:RGVRProcess E/ExoPlayerImplInternal:     at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 
03-15 23:07:35.535 14539-16140/com.app_tizr.rg2016.app:RGVRProcess E/ExoPlayerImplInternal:  Caused by: android.media.MediaCodec$CodecException: Error 0xfffffc0e
03-15 23:07:35.535 14539-16140/com.app_tizr.rg2016.app:RGVRProcess E/ExoPlayerImplInternal:     at android.media.MediaCodec.native_configure(Native Method)
03-15 23:07:35.535 14539-16140/com.app_tizr.rg2016.app:RGVRProcess E/ExoPlayerImplInternal:     at android.media.MediaCodec.configure(MediaCodec.java:1778)
03-15 23:07:35.535 14539-16140/com.app_tizr.rg2016.app:RGVRProcess E/ExoPlayerImplInternal:     at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.configureCodec(MediaCodecVideoTrackRenderer.java:385)
03-15 23:07:35.535 14539-16140/com.app_tizr.rg2016.app:RGVRProcess E/ExoPlayerImplInternal:     at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:334)
03-15 23:07:35.535 14539-16140/com.app_tizr.rg2016.app:RGVRProcess E/ExoPlayerImplInternal:     at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:709) 
03-15 23:07:35.535 14539-16140/com.app_tizr.rg2016.app:RGVRProcess E/ExoPlayerImplInternal:     at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:391) 
03-15 23:07:35.535 14539-16140/com.app_tizr.rg2016.app:RGVRProcess E/ExoPlayerImplInternal:     at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:470) 
03-15 23:07:35.535 14539-16140/com.app_tizr.rg2016.app:RGVRProcess E/ExoPlayerImplInternal:     at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:451) 
03-15 23:07:35.535 14539-16140/com.app_tizr.rg2016.app:RGVRProcess E/ExoPlayerImplInternal:     at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431) 
03-15 23:07:35.535 14539-16140/com.app_tizr.rg2016.app:RGVRProcess E/ExoPlayerImplInternal:     at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213) 
03-15 23:07:35.535 14539-16140/com.app_tizr.rg2016.app:RGVRProcess E/ExoPlayerImplInternal:     at android.os.Handler.dispatchMessage(Handler.java:98) 
03-15 23:07:35.535 14539-16140/com.app_tizr.rg2016.app:RGVRProcess E/ExoPlayerImplInternal:     at android.os.Looper.loop(Looper.java:148) 
03-15 23:07:35.535 14539-16140/com.app_tizr.rg2016.app:RGVRProcess E/ExoPlayerImplInternal:     at android.os.HandlerThread.run(HandlerThread.java:61) 
03-15 23:07:35.535 14539-16140/com.app_tizr.rg2016.app:RGVRProcess E/ExoPlayerImplInternal:     at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 
03-15 23:07:35.535 14539-14539/com.app_tizr.rg2016.app:RGVRProcess D/AndroidRuntime: Shutting down VM
03-15 23:07:35.555 14539-14539/com.app_tizr.rg2016.app:RGVRProcess E/AndroidRuntime: FATAL EXCEPTION: main
03-15 23:07:35.555 14539-14539/com.app_tizr.rg2016.app:RGVRProcess E/AndroidRuntime: Process: com.app_tizr.rg2016.app:RGVRProcess, PID: 14539
03-15 23:07:35.555 14539-14539/com.app_tizr.rg2016.app:RGVRProcess E/AndroidRuntime: java.lang.Error: FATAL EXCEPTION [main]
03-15 23:07:35.555 14539-14539/com.app_tizr.rg2016.app:RGVRProcess E/AndroidRuntime: Unity version     : 5.3.2f1
03-15 23:07:35.555 14539-14539/com.app_tizr.rg2016.app:RGVRProcess E/AndroidRuntime: Device model      : TCL 6055K
03-15 23:07:35.555 14539-14539/com.app_tizr.rg2016.app:RGVRProcess E/AndroidRuntime: Device fingerprint: TCL/idol4/idol4:6.0.1/MMB29M/156:userdebug/release-keys`

Can you explain me how to do it properly ?

Thanks in advance.

Gregoire Badoual

**Comment by ojw28** [comment]
Please provide full information, including a link to the media and a proper bug report, as requested in the issue template and also [here](https://google.github.io/ExoPlayer/2015/10/01/reporting-issues.html).

**Comment by rossthedevigner** [comment]
@gbadoual Did you ever solve this issue? I _think_ I'm running into the same thing.

**Comment by AquilesCanta** [comment]
Closing as this is quite an old issue and the required information was not provided. I can tell you that version 2 improves track selection. Try it out and open a new issue (with the required information in the issue template) if you still find complications.
