### ISSUE TITLE
Make Cue class Parcelable

### ISSUE THREAD

**Issue by b95505017** [google/ExoPlayer#1381]
In DemoPlayer, there are two things may be related to UI. One is Surface, it is responded for consume video frame, and it implement Parcelable; The other is Cue, it is related to caption stuff.

If I want to put DemoPlayer into another process Cue will become a obstacle when messaging with different processes.

**Comment by ojw28** [comment]
The same would be true of Id3Frame and subclasses too. Do you have a good way to access a Surface in a different process? Because unless you do, there's not much point doing anything else in this area!

**Comment by b95505017** [comment]
Because Surface implement Parcelable, I think it is easy to communicate via either iBinder or Messenger.

**Comment by ojw28** [comment]
It would be good if you could verify that passing a Surface across processes actually works, before we invest time in this. Please give it a try and let us know what you discover.

**Comment by b95505017** [comment]
ok

**Comment by b95505017** [comment]
Another point is that if I use ExoPlayer in MediaBrowserService/MediaBrowserServiceCompat, it has its own iBinder, everything communicate between UI & Service should wrap into Bundle, which should implement Parcelable.

**Comment by b95505017** [comment]
I've done the test, it works. :)
Using ExoPlayer in the Service in another process, and pass Surface using Bundle from Activity.

**Comment by ojw28** [comment]
Cool! Please feel free to send a pull request to our dev branch that makes `Cue` parcelable.

**Comment by ojw28** [comment]
You're more than welcome to implement this and send us a pull request to add support, but I don't think we'll be doing this ourselves and there's seemingly little additional demand. Hence I'm going to go ahead and close the issue for now.
