### ISSUE TITLE
Follow semver versioning

### ISSUE THREAD

**Issue by ryanseys** [google/ExoPlayer#1382]
It's apparent that ExoPlayer is a key part of a lot of people's apps. It would be great if versioning ExoPlayer was a little more structured i.e. follow [semver](http://semver.org/) and changes could be committed with semver in mind.

Also, even if you decide not to follow something like semver, when you break something in ExoPlayer, it would be great to document how users may migrate their existing code to use the latest library.

**Comment by ojw28** [comment]
Thanks for the suggestion. We'll consider this starting from our v2 release. We likely wont adopt semver because it would result in us incrementing the major version too frequently, but we should add more structure than exists currently.

**Comment by ojw28** [comment]
As per above, semver isn't realistic for this project as we'd end up incrementing the major version too frequently. As of V2 we've been incrementing X.Y.Z to mean:

X - Major new release
Y - API changes / large new features
Z - Bug fixes / small new features

I think that's the best we can do given the project's current rate of evolution.
