### ISSUE TITLE
I have a question that when I am changing the channel for live streaming then last channel is buffering?

### ISSUE THREAD

**Issue by HanumanGanga** [google/ExoPlayer#1384]
When I am changing the channel from 1 to 2 and within 2 sec I clicked on  the first channel then it is buffered. so it is playing old frame which is already played.So I am thinking that it is buffering.So How can clear the buffer  when I am changing channel.or When I am releasing the player.I didn't find anything to solve this issue.

**Comment by ojw28** [comment]
There is insufficient information here to answer the question (i.e. the type of media being played), but unless you're seeing an actual issue or negative impact related to this question, I would suggest that you trust that the player is doing something sensible.
