### ISSUE TITLE
High cpu usage compared to mediaplayer

### ISSUE THREAD

**Issue by digitalix** [google/ExoPlayer#1388]
To delete

**Comment by ojw28** [comment]
This issue doesn't provide enough information. For example:

- What does "YouTube videos" mean? YouTube videos are transcoded into many different formats, so you need to be more specific. Please provide a URL that's playable in both MediaPlayer and ExoPlayer and exhibits the behavior you observe.
- How are you measuring CPU usage?
- To which process(es) is the CPU usage attributed? For ExoPlayer, CPU utilisation is typically split between the application process and Android's mediaserver and surfaceflinger processes.
- What's your experimental setup in each case and how can we reproduce it?
- High CPU usage isn't in itself a significant problem. What negative effects are you seeing as a result of the high CPU usage?
- Please provide a full bug report, as is explicitly requested in the issue template.

**Comment by digitalix** [comment]
- For example I take this video https://youtu.be/nMt7nMUcQRQ and using http://www.youtube.com/get_video_info?&video_id=nMt7nMUcQRQ&asv=3&el=detailpage&hl=en_US
I getting normal mp4 or webm videos for mediaplayer and for exoplayer I am using DASH files and for test I use only audio ones which are audio/webm or audio/mp4

- I measuring CPU usage using Android Studio
- Using android cpu usage option from developer settings top process is mediaserver when I use android mediaplayer and my app process if I use exoplayer

- To reproduce it you have to extract video information using http://www.youtube.com/get_video_info?&video_id=nMt7nMUcQRQ&asv=3&el=detailpage&hl=en_US and choose one of available formats (I tested it for every format that youtube uses)
