### ISSUE TITLE
It takes seconds for video to render when the activity resumed

### ISSUE THREAD

**Issue by ldn0x7dc** [google/ExoPlayer#1389]
I'm using the official demo(1.5.6) and I'm turning on the **Play in background** options.
The problem is if I press the system recent apps menu during playing a demo video(like *Big Buck Bunny(Flv Video)*), and get back to the demo app, the video will **freeze for seconds** before it render normally. **This is bad for user experience.** The audio renders normall all the time.
Could anyone help solve this problem?

**Comment by ldn0x7dc** [comment]
Well, here are good news.
I guess the reason causing this problem can be explained [here](https://github.com/google/ExoPlayer/issues/318).
And the solution to this problem can be found [here](https://github.com/google/ExoPlayer/issues/1084) or [here](http://stackoverflow.com/questions/28727413/move-surfaceview-across-activities).
The essence to solving this problem is **surface switching**. A surface get destroyed after the host activity paused and a new surface get created after the host activity resumed. So some video frames are lost in the old surface(I guess), which causes the video freeze or images gap or black surface screen until the new surface receives new video frames(I guess again...).

**Comment by ldn0x7dc** [comment]
My fault.
The official demo **Play in background** is implemented by disable the video track. In this way, the image gap can **not** be avoided after the video track is restored even when no surface switching is happening.

**Comment by RMTT** [comment]
Hello,I also get the problem,and do you solved it?
