### ISSUE TITLE
Green overlay and corrupted playback on 4.1.2 device

### ISSUE THREAD

**Issue by sjrmanning** [google/ExoPlayer#1393]
Hi,

We're currently integrating ExoPlayer into an app that runs on devices back to 4.1.2, and on one of our devices we're seeing a strange issue playing back an mp4 file. This is occurring both with hardware acceleration enabled and disabled in the manifest file.

ExoPlayer version: We've tried the latest version, plus a few versions back.

Example screenshot:
![Example](http://i.imgur.com/8eez3QC.png)

I've sent an email to dev.exoplayer@gmail.com with a link to example content where this issue is occurring.

Any ideas what might be going on? I'm guessing this is probably a hardware issue. We don't see this behaviour in a standard VideoView, but we're using ExoPlayer to try fix issues with anamorphic widescreen content which isn't displaying correctly with the built-in VideoView.

**Comment by andrewlewis** [comment]
What is the one device/build where you see this? Please provide the output of `adb shell getprop ro.build.fingerprint`.

**Comment by sjrmanning** [comment]
It's a Geniatech set top box, here's the build fingerprint:

```
adb shell getprop ro.build.fingerprint
MBX/stvmx/stvmx:4.1.2/V1.03.04MX01_20130720/20130720:user/test-keys
```

**Comment by ojw28** [comment]
I haven't taken a more detailed look, but it feels a look like a device specific issue. It should probably be reported direct to the device manufacturer. Where can we get one of these devices? Is it one of [these](http://www.geniatech.com/pa/android-tv.asp)?

**Comment by ojw28** [comment]
Closing on the assumption this is a device specific issue. Please report it direct to the device manufacturer.
