### ISSUE TITLE
run streaming with demo exoplayer in some Set-top-box, black screen.

### ISSUE THREAD

**Issue by kinhdang** [google/ExoPlayer#1398]
Dear all !

When I run streaming with demo exoplayer in some Set-top-box, black screen, the video seems to play but just display a black blank screen when playing back, although, play good on mobile or tablet, attach log file, anyone knows. Please help.

Thanks.
[chinabox3.txt](https://github.com/google/ExoPlayer/files/190963/chinabox3.txt)

**Comment by AquilesCanta** [comment]
Please open a new issue including the information required in the issue_template file. As a starting point, we usually need to reproduce the issue ourselves. However, I did see errors in the provided log file such as:

`java.lang.IllegalArgumentException: Requested window android.os.BinderProxy@41584138 does not exist`

which I haven't seen before in the demo App(this does not mean it couldn't be an exoplayer related problem, of course). I wonder if you have introduced some modifications yourself or if this is a device specific issue(in which case, "some STB" is not a very detailed domain). Anyhow, we will require more information to help you. Thanks for reaching out!
