### ISSUE TITLE
setOnKeyListener useless

### ISSUE THREAD

**Issue by chile-zhong** [google/ExoPlayer#1400]
In the demo(PlayerActivity), root.setOnKeyListener seems useless ,why ?
the full code is following:

```
root.setOnKeyListener(new OnKeyListener() {
      @Override
      public boolean onKey(View v, int keyCode, KeyEvent event) {
        if (keyCode == KeyEvent.KEYCODE_BACK || keyCode == KeyEvent.KEYCODE_ESCAPE
            || keyCode == KeyEvent.KEYCODE_MENU) {
          Log.i("zhongzhizhi","KEYCODE_BACK");
          return false;
        }
        return mediaController.dispatchKeyEvent(event);
      }
    });
```

**Comment by ojw28** [comment]
Using git blame and looking at the original changes and their change descriptions can often answer questions of the form "what is this code for". See [here](https://github.com/google/ExoPlayer/blame/master/demo/src/main/java/com/google/android/exoplayer/demo/PlayerActivity.java). In this case, the code block is for AndroidTV devices.
