### ISSUE TITLE
Publish demo source jar

### ISSUE THREAD

**Issue by cperry-gpsw** [google/ExoPlayer#1403]
`DemoPlayer` is a great way to use `ExoPlayer` with the lowest barrier to entry. It currently is not published, I'd like to see it published so I could include it as a dependency without having to either do the git submodule thing, or copy paste into my project.

**Comment by ojw28** [comment]
Depending on the sources of a demo project doesn't feel like the right thing for you to be doing. It might be the easiest thing to do, but that doesn't make it right, particularly given you're probably only interested in the DemoPlayer and Builder classes. Copying them into your own project is the best approach in my opinion.

For 2.x release of ExoPlayer we're working on substantially reducing the amount of code that you need in your application. Specifically, it's likely that all of the functionality that currently resides in the Builder classes will be merged into the core library, and much of the complexity in DemoPlayer will go away too. This should further reduce the barrier to entry.
