### ISSUE TITLE
OEMCrypto_LoadKeys returns 10007

### ISSUE THREAD

**Issue by pykler** [google/ExoPlayer#1404]
Apps that use DRM are not working on my device. Using logcat I traced it down to this error. Unfortunately I cannot find anywhere what this error means.

```
03-30 23:52:49.309: D/DrmWidevineDash(379): OEMCrypto_LoadKeys returns 10007
03-30 23:52:49.309: E/WVCdm(379): CryptoSession::LoadKeys: OEMCrypto_LoadKeys error=10007
03-30 23:59:13.505: E/WVCdm(379): CdmEngine::AddKey: keys not added, result = 99
03-30 23:59:13.506: E/MediaDrm-JNI(9855): Illegal state exception: Failed to handle key response: DRM vendor-defined error: -2902 (-2902)
```

I am using a Nexus 6 and it has only recently started giving this error. I updated to the latest available updates and still seeing this.

Example apps that don't work because of this: Netflix.

More output from logcat

```
03-30 23:59:12.625: I/WVCdm(379): CdmEngine::OpenSession
03-30 23:59:12.625: D/DrmWidevineDash(379): OEMCrypto_OpenSession: starts! SID=0xb12e613c
03-30 23:59:12.628: D/DrmWidevineDash(379): OEMCrypto_OpenSession SID = 2
03-30 23:59:12.629: D/DrmWidevineDash(379): OEMCrypto_OpenSession: ends! returns 0
03-30 23:59:12.629: D/DrmWidevineDash(379): OEMCrypto_GetRandom: starts! randomData=0xb3ac3468, dataLength=8
03-30 23:59:12.629: D/DrmWidevineDash(379): OEMCrypto_GetRandom: ends! returns 0
03-30 23:59:12.630: D/DrmWidevineDash(379): OEMCrypto_LoadDeviceRSAKey: starts!SID=2, wrapped_rsa_key=0xb2c60800, wrapped_rsa_key_length=1280
03-30 23:59:12.635: D/DrmWidevineDash(379): OEMCrypto_LoadDeviceRSAKey: ends! returns 0
03-30 23:59:12.635: I/WVCdm(379): CdmEngine::QueryKeyControlInfo
03-30 23:59:12.635: W/WVCdm(379): BufferReader::Read<T> : Failure during parse: Not enough bytes (4)
03-30 23:59:12.636: W/WVCdm(379): CdmEngine::ExtractWidevinePssh: Unable to read atom size.
03-30 23:59:12.636: I/WVCdm(379): CdmEngine::GenerateKeyRequest
03-30 23:59:12.636: D/DrmWidevineDash(379): OEMCrypto_GetRandom: starts! randomData=0xb347ab00, dataLength=4
03-30 23:59:12.636: D/DrmWidevineDash(379): OEMCrypto_GetRandom: ends! returns 0
03-30 23:59:12.644: D/DrmWidevineDash(379): OEMCrypto_GetDeviceID: starts! deviceID=0xb2bb12a0, idLength=0xb183ef34
03-30 23:59:12.659: D/DrmWidevineDash(379): OEMCrypto_GetDeviceID: ends! returns 0
03-30 23:59:12.659: D/DrmWidevineDash(379): OEMCrypto_SupportsUsageTable: starts!
03-30 23:59:12.660: D/DrmWidevineDash(379): OEMCrypto_SupportsUsageTable: is_supported = 1
03-30 23:59:12.660: D/DrmWidevineDash(379): OEMCrypto_SupportsUsageTable: wv_app_version =0x23
03-30 23:59:12.660: D/DrmWidevineDash(379): OEMCrypto_SupportsUsageTable: ends! returns 0x0
03-30 23:59:12.660: D/DrmWidevineDash(379): OEMCrypto_IsAntiRollbackHwPresent: starts!
03-30 23:59:12.661: D/DrmWidevineDash(379): OEMCrypto_IsAntiRollbackHwPresent ends! ret=0, is_antirb_enabled = 1
03-30 23:59:12.661: D/DrmWidevineDash(379): OEMCrypto_APIVersion: starts!
03-30 23:59:12.661: D/DrmWidevineDash(379): hlos api version =  10
03-30 23:59:12.661: D/DrmWidevineDash(379): tz api version =  10
03-30 23:59:12.661: D/DrmWidevineDash(379): OEMCrypto_APIVersion: ends! returns version 10
03-30 23:59:12.661: D/DrmWidevineDash(379): OEMCrypto_GetHDCPCapability starts!
03-30 23:59:12.663: D/DrmWidevineDash(379): OEMCrypto_GetHDCPCapability current=255, max=4
03-30 23:59:12.663: D/DrmWidevineDash(379): OEMCrypto_GetHDCPCapability ends! ret = 0
03-30 23:59:12.663: D/DrmWidevineDash(379): OEMCrypto_GenerateNonce: starts! SID=2
03-30 23:59:12.664: D/DrmWidevineDash(379): OEMCrypto_GenerateNonce: ends! returns 0
03-30 23:59:12.664: D/WVCdm(379): PrepareKeyRequest: nonce=1436006011
03-30 23:59:12.664: D/DrmWidevineDash(379): OEMCrypto_GenerateRSASignature starts! SID=2, message=0xb484a100
03-30 23:59:12.664: D/DrmWidevineDash(379): message_length=1629, signature=0xb0935dc0, signature_length=2978213900
03-30 23:59:12.741: D/DrmWidevineDash(379): OEMCrypto_GenerateRSASignature returns 0
03-30 23:59:13.397: I/WVCdm(379): CdmEngine::RemoveKeys
03-30 23:59:13.397: D/DrmWidevineDash(379): OEMCrypto_CloseSession: starts! SID=1
03-30 23:59:13.398: D/DrmWidevineDash(379): OEMCrypto_CloseSession: ends! returns 0
03-30 23:59:13.399: I/WVCdm(379): CdmEngine::CloseSession
03-30 23:59:13.399: I/WVCdm(379): CdmEngine::AddKey
03-30 23:59:13.399: D/DrmWidevineDash(379): OEMCrypto_DeriveKeysFromSessionKey: starts! SID=2,enc_session_key=0xb0935140, enc_session_key_length=256, mac_key_context=0xb0a19c00,mac_key_context_length=1648, enc_key_context=0xb0a5f000, enc_key_context_length=1644
03-30 23:59:13.489: D/DrmWidevineDash(379): OEMCrypto_DeriveKeysFromSessionKey: ends! returns 0
03-30 23:59:13.489: D/DrmWidevineDash(379): OEMCrypto_LoadKeys starts! SID=2, message=0xb607fd00, message_length=340, signature=0xb3202360
03-30 23:59:13.489: D/DrmWidevineDash(379): signature_length=32, enc_mac_key_iv=0x0, enc_mac_key=0x0, num_keys=2, pst=0, pst_length=0
03-30 23:59:13.505: D/DrmWidevineDash(379): OEMCrypto_LoadKeys returns 10007
03-30 23:59:13.505: E/WVCdm(379): CryptoSession::LoadKeys: OEMCrypto_LoadKeys error=10007
03-30 23:59:13.505: E/WVCdm(379): CdmEngine::AddKey: keys not added, result = 99
03-30 23:59:13.506: E/MediaDrm-JNI(9855): Illegal state exception: Failed to handle key response: DRM vendor-defined error: -2902 (-2902)
```

**Comment by ojw28** [comment]
@wvpaf - Could you take a look?
@pykler - Please attach a full bug report, as is requested in the issue template. Thanks!

**Comment by pykler** [comment]
This link is the [bugreport](https://github.com/google/ExoPlayer/files/200650/bugreport.txt) from my Nexus 6. Also note that this bug report was generated after using the exoplayer demo app when playing any secured file.

Question: is any of the DRM on android hardware supported, is it possible that this is a hardware issue and not a software issue? There was a few drops of liquid that may have made it in the phone, the phone is fully functional and all the apps work but it seems just DRM is the only thing that is broken. 

Also: I see lots of Errors relating to Chromium disk IO, could that be related to load keys returning that error? you will probably see those in the attached report.

PS. I just factory reset the device and this bug report is fresh.

**Comment by polmabri** [comment]
Same issue with netflix on Nexus 5x Android 6.0.1 MHC19Q

**Comment by polmabri** [comment]
I get a similar error when trying to login into the netflix app, tried it on my nexus 5x with android 6.0.1 AND android n preview 3 NPD35K.
Already talked about three hours with a special netflix tech-team and tried everything to resolve the problem, including: executing a factory reset, diving into the android bug report, going through the logging file.... nothing helped.

Failed to handle key response: DRM vendor-defined error: -2902 (-2902)
`
build.board: bullhead
build.bootloader: BHZ11b
build.brand: google
build.cpu_abi: arm64-v8a
build.cpu_abi2: 
build.device: bullhead
build.display: NPD35K
build.fingerprint: google/bullhead/bullhead:N/NPD35K/2864170:user/release-keys
build.hardware: bullhead
build.host: vpeb4.mtv.corp.google.com
build.id: NPD35K
build.manufacturer: LGE
build.model: Nexus 5X
build.product: bullhead
build.radio: unknown
build.serial: 012ff5060bdc41d4
build.tags: release-keys
build.time: 1463100342000
build.type: user
build.user: android-build
version.codename: N
version.incremental: 2864170
version.release: N
version.sdk_int: 23

05-24 00:59:04.003 I/WVCdm (518): CdmEngine::OpenSession
05-24 00:59:04.003 D/DrmWidevineDash(518): OEMCrypto_OpenSession: starts! SID=0xff9db344
05-24 00:59:04.003 D/DrmWidevineDash(518): OEMCrypto_OpenSession Session ID = 0
05-24 00:59:04.004 D/DrmWidevineDash(518): OEMCrypto_OpenSession SID = 2
05-24 00:59:04.004 D/DrmWidevineDash(518): OEMCrypto_OpenSession: ends! returns 0
05-24 00:59:04.004 D/DrmWidevineDash(518): _oecc09: function time: 1ms (0s 1203594ns)
05-24 00:59:04.006 D/DrmWidevineDash(518): _oecc06: function time: 1ms (0s 1281927ns)
05-24 00:59:04.013 D/DrmWidevineDash(518): OEMCrypto_LoadDeviceRSAKey: starts! SID=2, wrapped_rsa_key=0xe75c4c00, wrapped_rsa_key_length=1280
05-24 00:59:04.018 D/DrmWidevineDash(518): OEMCrypto_LoadDeviceRSAKey: ends! returns 0
05-24 00:59:04.018 D/DrmWidevineDash(518): _oecc19: function time: 4ms (0s 4933126ns)
05-24 00:59:04.019 D/DrmWidevineDash(518): _oecc06: function time: 1ms (0s 1074844ns)
05-24 00:59:04.019 I/WVCdm (518): CdmEngine::QueryKeyControlInfo
05-24 00:59:04.020 I/WVCdm (518): CdmEngine::GenerateKeyRequest
05-24 00:59:04.020 D/DrmWidevineDash(518): OEMCrypto_GetDeviceID: starts! deviceID=0xe7277200, idLength=0xe787f26c
05-24 00:59:04.032 D/DrmWidevineDash(518): OEMCrypto_GetDeviceID: ends! returns 0
05-24 00:59:04.032 D/DrmWidevineDash(518): _oecc07: function time: 12ms (0s 12192553ns)
05-24 00:59:04.032 D/DrmWidevineDash(518): OEMCrypto_SupportsUsageTable: starts!
05-24 00:59:04.032 D/DrmWidevineDash(518): OEMCrypto_SupportsUsageTable: is_supported = 1
05-24 00:59:04.032 D/DrmWidevineDash(518): OEMCrypto_SupportsUsageTable: wv_app_version =0x32
05-24 00:59:04.032 D/DrmWidevineDash(518): OEMCrypto_SupportsUsageTable: ends! returns 0
05-24 00:59:04.032 D/DrmWidevineDash(518): _oecc29: function time: 0ms (0s 391666ns)
05-24 00:59:04.033 D/DrmWidevineDash(518): OEMCrypto_IsAntiRollbackHwPresent: starts!
05-24 00:59:04.033 D/DrmWidevineDash(518): OEMCrypto_IsAntiRollbackHwPresent ends! ret=0, is_antirb_enabled = 1
05-24 00:59:04.033 D/DrmWidevineDash(518): _oecc39: function time: 0ms (0s 459479ns)
05-24 00:59:04.033 D/DrmWidevineDash(518): OEMCrypto_APIVersion: starts!
05-24 00:59:04.033 D/DrmWidevineDash(518): hlos api version = 11
05-24 00:59:04.033 D/DrmWidevineDash(518): tz api version = 11
05-24 00:59:04.033 D/DrmWidevineDash(518): OEMCrypto_APIVersion: ends! returns version 11
05-24 00:59:04.033 D/DrmWidevineDash(518): _oecc22: function time: 0ms (0s 382656ns)
05-24 00:59:04.033 D/DrmWidevineDash(518): OEMCrypto_GetHDCPCapability starts!
05-24 00:59:04.034 D/DrmWidevineDash(518): OEMCrypto_GetHDCPCapability current=255, max=4
05-24 00:59:04.034 D/DrmWidevineDash(518): OEMCrypto_GetHDCPCapability ends! ret = 0
05-24 00:59:04.034 D/DrmWidevineDash(518): _oecc44: function time: 0ms (0s 364322ns)
05-24 00:59:04.034 D/DrmWidevineDash(518): OEMCrypto_GenerateNonce: starts! SID=2, nonce=0xe787f3bc
05-24 00:59:04.034 D/DrmWidevineDash(518): OEMCrypto_GenerateNonce: ends! returns 0
05-24 00:59:04.034 D/DrmWidevineDash(518): _oecc14: function time: 0ms (0s 410156ns)
05-24 00:59:04.034 D/WVCdm (518): PrepareKeyRequest: nonce=161667085
05-24 00:59:04.034 D/DrmWidevineDash(518): OEMCrypto_GenerateRSASignature starts! SID=2, message=0xe75dcc00
05-24 00:59:04.034 D/DrmWidevineDash(518): message_length=1630, signature=0xe7b39500, signature_length=0xe787f35c
05-24 00:59:04.169 D/DrmWidevineDash(518): OEMCrypto_GenerateRSASignature returns 0
05-24 00:59:04.169 D/DrmWidevineDash(518): _oecc36: function time: 134ms (0s 134261888ns)
05-24 00:59:04.603 I/WVCdm (518): CdmEngine::RemoveKeys
05-24 00:59:04.603 D/DrmWidevineDash(518): OEMCrypto_CloseSession: starts! SID=1
05-24 00:59:04.604 D/DrmWidevineDash(518): OEMCrypto_CloseSession: ends! returns 0
05-24 00:59:04.604 D/DrmWidevineDash(518): _oecc10: function time: 0ms (0s 518125ns)
05-24 00:59:04.606 I/WVCdm (518): CdmEngine::CloseSession
05-24 00:59:04.607 I/WVCdm (518): CdmEngine::AddKey
05-24 00:59:04.607 D/DrmWidevineDash(518): OEMCrypto_DeriveKeysFromSessionKey: starts! SID=2
05-24 00:59:04.607 D/DrmWidevineDash(518): enc_session_key=0xe78e1500, enc_session_key_length=256, mac_key_context=0xe742b000
05-24 00:59:04.607 D/DrmWidevineDash(518): mac_key_context_length=1649, enc_key_context=0xe78dc300, enc_key_context_length=1645
05-24 00:59:04.740 D/DrmWidevineDash(518): OEMCrypto_DeriveKeysFromSessionKey: ends! returns 0
05-24 00:59:04.741 D/DrmWidevineDash(518): _oecc21: function time: 133ms (0s 133497825ns)
05-24 00:59:04.741 D/DrmWidevineDash(518): OEMCrypto_LoadKeys starts! SID=2, message=0xe7428000, message_length=340, signature=0xe788f780, kary_addr=0xe78a96c0
05-24 00:59:04.741 D/DrmWidevineDash(518): signature_length=32, enc_mac_key_iv=0x0, enc_mac_key=0x0, num_keys=2, pst=(null), pst_length=0
05-24 00:59:04.749 D/DrmWidevineDash(518): OEMCrypto_LoadKeys returns 10036
05-24 00:59:04.749 D/DrmWidevineDash(518): _oecc47: function time: 8ms (0s 8107397ns)
05-24 00:59:04.749 E/WVCdm (518): CryptoSession::LoadKeys: OEMCrypto_LoadKeys error=10036
05-24 00:59:04.749 E/WVCdm (518): CdmEngine::AddKey: keys not added, result = 99
05-24 00:59:04.750 E/MediaDrm-JNI(18073): Illegal state exception: Failed to handle key response: DRM vendor-defined error: -2902 (-2902)
05-24 00:59:06.183 I/ActivityManager(892): START u0 {flg=0x10804000 cmp=com.android.systemui/.recents.RecentsActivity} from uid 10029 on display 0
`

**Comment by wvpaf** [comment]
Hi,

It seems that the resulting 'load keys' error is similar but the root error 'LoadKeys: OEMCrypto_LoadKeys error=10036' is different from the 'LoadKeys: OEMCrypto_LoadKeys error=10007'.
The WV team will follow up the SoC vendor out of band.

**Comment by jefftinker** [comment]
@pykler, @polmabri - If either of you still have a device in this state, and you have root on the device, the SoC manufacturer has requested the following information, which will allow them to create a custom TZ image to further debug the problem:

Reboot into fastboot:
adb reboot bootloader
fastboot getvar uid 

You should see something like:
$ fastboot getvar uid
uid: 0B2C1B0112000000000000000000

Please provide the uid.

**Comment by wvpaf** [comment]
@pykler &/or @polmabri , any update?  This case is starting to age. Any update would be helpful. Thanks,
