### ISSUE TITLE
how to delay chunk download in exoplayer-DASH

### ISSUE THREAD

**Issue by RamkumarVooda** [google/ExoPlayer#1406]
I am working on DASH streaming in ExoPlayer. 
I want to delay(time varies) the download of next chunk , because i have enough buffer to play for next few seconds.
How can i achieve this?

**Comment by ojw28** [comment]
Why don't you trust the player to buffer chunks in a sensible way? Or to put it another way, why do you actually want to do this? Having enough buffer to play the next few seconds isn't a good reason in itself, and artificially keeping the buffer small significantly increases the probability of re-buffers or playback failures.

**Comment by RamkumarVooda** [comment]
I am implementing an adaptive streaming algorithm in FormatEvaluator Class. So according to the algorithm i need to delay the download for some time only if the buffer is exceeding certain threshold.

**Comment by ojw28** [comment]
`LoadControl` (and `DefaultLoadControl`) implements this functionality currently, so you should start there.

**Comment by RamkumarVooda** [comment]
yes got it.
Thank you
