### ISSUE TITLE
Player doesn't change quality of picture when it changes stream on SDMC device 

### ISSUE THREAD

**Issue by Zo2m4bie** [google/ExoPlayer#1411]
Hi, I faced with very strange issues with adaptive stream on one of my device(And I want to call your attention that I can reproduce it only on one device(maybe it can happen on other devices but I don't have another device where I can reproduce this issue)).([link](http://en.sdmctech.com/products/products-center.html) to devices, I don't remember exactly device name, will update it in monday) So, my app plays HLS streams  and it change stream according to my current bandwidth, but I notice that on sdmc device quality doesn't change and it always plays stream with lowest bit-rate. So I logged HlsChunkSource to understand what happens.  
When player start to play it start from the lowest bit-rate ([here](https://github.com/google/ExoPlayer/blob/master/library/src/main/java/com/google/android/exoplayer/hls/HlsChunkSource.java#L650) return index of a lowest stream). And I was very surprised when on next iteration getNextVariantIndex method calculate my bandwidth and return stream with one of the biggest bit-rate and player started working with this stream. But problem that I didn't see any change on screen, it still was picture with bad quality, but player worked with one of the best stream. So I decided  to change [this place](https://github.com/google/ExoPlayer/blob/master/library/src/main/java/com/google/android/exoplayer/hls/HlsChunkSource.java#L650) to return here the best url index instead of one with lowest bit-rate, and I was very surprised when my player started working correct and now when it changes quality it changes picture quality too.

**Comment by Zo2m4bie** [comment]
**UPDATE:**

Device:
http://en.sdmctech.com/product/dv7819-4k-uhd-quad-core-android-tv-box-with-verimatrix-playready-and-widewine.html

But I have android 4.2 there

**Comment by ojw28** [comment]
Same as https://github.com/google/ExoPlayer/issues/953. Please report the issue to the device manufacturer, since I do not believe this is an ExoPlayer issue.
