### ISSUE TITLE
Format.frameRate always returning -1

### ISSUE THREAD

**Issue by ssenanayake** [google/ExoPlayer#1415]
public void onLoadCompleted(int sourceId, long bytesLoaded, int type, int trigger, Format format,
                                long mediaStartTimeMs, long mediaEndTimeMs, long elapsedRealtimeMs, long loadDurationMs) ....

and 

public void onDownstreamFormatChanged(int sourceId, Format format, int trigger, long mediaTimeMs)

The format.frameRate is always returning -1.

This is the case for different types of content....HLS VoD, HLS Live, DASH....

The frameRate is a metric we are using for QoS.

**Comment by ojw28** [comment]
It's not always -1 for DASH (as demonstrated if you simply modify the demo app to print the value). This callback is invoked without knowledge of what's being parsed from the data, so the frame rate needs to be indicated in the manifest (or equivalent) if it's to be set.

**Comment by ssenanayake** [comment]
Thanks ojw28.
