### ISSUE TITLE
Testing Wowza live streaming multi-profile using DASH does not change video quality

### ISSUE THREAD

**Issue by klevinism** [google/ExoPlayer#1418]
I am testing DASH stream on Exoplayer on android device.
When I open multi profile stream, the stream starts from the lower profile 360p and switches to the higher profile 720p after some seconds. (you can see the watermark on bottom right for each profile)
Even though the logo changes, the quality is the same, so to clarify, the video (check the quality) is from 360p and the static logo on bottom right is the logo is used in 720p profile.

This is not happening and it works fine when I open the same stream (multi-profile) from the same application but using HLS output.

What changes should I apply to make the multi profile stream in DASH to work properly?

Thanks in advance..

**Comment by ojw28** [comment]
I don't understand the question. The watermark/logo is presumably burnt directly into each of the video streams. If that's the case then it's not possible that we would be showing the watermark/logo from one of the streams but the underlying video from the other.

**Comment by klevinism** [comment]
Yes, the watermark is burnt directly into each video stream. So the lower profile(360p) has a watermark and the higher profile(720p) has a different watermark. The issue here is that the watermark changes from one streaming profile to another, but the video quality(from lower to higher quality) does not change at all.

**Comment by ojw28** [comment]
How is that possible? If the watermark changes then the player must be playing the stream that has that watermark baked into it. There's no such thing as playing a 720p stream at 360p quality, unless the device you're testing on is doing something bizarre.

Please can you provide a test URL that we can reproduce what you're seeing with, and details about the specific device you're testing on?

**Comment by klevinism** [comment]
I am sorry for this late response.. 

the test stream is: 
http://akamai227.tibo.tv/top227/ngrp:top.stream_all/manifest.mpd

and my device model: 
android tv box, android 4.4 OS, ATV582

**Comment by ojw28** [comment]
This sounds like a device specific error. Please report it to the device manufacturer (it's unclear whether the device has passed Android CTS).
