### ISSUE TITLE
.srt encoding problem

### ISSUE THREAD

**Issue by AbdelrahmanSalem** [google/ExoPlayer#1419]
I am trying to render the following .srt file which is in turkish language 
https://drive.google.com/a/microdoers.com/file/d/0B4Rir8tNZWg3ZDlTN1FrT2Jfc1k/view?usp=sharing
 the srt file opens ok on any editor on my machine but the TextTrackRenderer that is setup by the following lines

````
        DataSource textDataSource = new DefaultUriDataSource(context, bandwidthMeter, userAgent);

        MediaFormat mediaFormat = MediaFormat.createTextFormat("0", MimeTypes.APPLICATION_SUBRIP, MediaFormat.NO_VALUE, C.MATCH_LONGEST_US, null);

        SingleSampleSource textSampleSource = new SingleSampleSource(Uri.parse(subUri), textDataSource, mediaFormat);

        TrackRenderer subTitlerenderer = new TextTrackRenderer(textSampleSource, player, player.getMainHandler().getLooper());

        renderers[EMExoPlayer.RENDER_TEXT] = subTitlerenderer;
````

does not display characters like ý instead displays �
I have tried to get bytes in UTF-8 and create a new string but I think data is already lost 
So I guess it is an encoding problem with the TextTrackRenderer.

**Comment by AquilesCanta** [comment]
Please send the file to `dev.exoplayer@gmail.com`(access permission was not granted to the given resource) and post back so that we go look for it.

**Comment by AquilesCanta** [comment]
Same as [#1362](https://github.com/google/ExoPlayer/issues/1362). The issue here is that exoplayer only supports UTF-8 right now. I think you have two possible courses of action:

1. Convert your file to UTF-8 and serve the resulting file.
2. Programmatically do the conversion before feeding the file to the exoplayer parser.
