### ISSUE TITLE
[Question] Does ExoPlayer support Irdeto Playready for HLS?

### ISSUE THREAD

**Issue by scattym** [google/ExoPlayer#1424]
Hi,

I was just wondering if ExoPlayer supports Irdeto PlayReady DRM on HLS?

See USP site for more info:
http://docs.unified-streaming.com/documentation/drm/irdeto.html

Cheers,
M.

**Comment by ojw28** [comment]
We do not support this mode, no. If you wish to use DRM then the recommended approach is Widevine with DASH or SmoothStreaming. You can also use PlayReady with DASH or SmoothStreaming if you're targeting only AndroidTV devices.
