### ISSUE TITLE
IllegalStateException when parsing Wowza MP4 fragment

### ISSUE THREAD

**Issue by perchrh** [google/ExoPlayer#1427]
Playback of one of our Dash streams fails with the stack trace included below. 
The crash happens when an unexpected value is read during parsing of an MP4 fragment [1]. 

The stream plays successfully with Google Cast, and is successfully read by MP4 Reader, from thin multimedia. 

[1]  https://drive.google.com/file/d/0B-MiKMsYx1iHZ21NaGxsbjM1RnM/view?usp=sharing

<pre><code>
E/LoadTask: Unexpected exception loading stream
   java.lang.IllegalStateException: Top bit not zero: -859825398
      at com.google.android.exoplayer.util.ParsableByteArray.readUnsignedIntToInt(ParsableByteArray.java:299)
      at com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.readSample(FragmentedMp4Extractor.java:857)
      at com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:192)
      at com.google.android.exoplayer.chunk.ChunkExtractorWrapper.read(ChunkExtractorWrapper.java:93)
      at com.google.android.exoplayer.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:165)
      at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
</code></pre>

Edit: Seen on ExoPlayer version 1.5.7.

**Comment by ojw28** [comment]
Give the failure is in `readSample`, it's pretty unclear to me that the error is reading the initialization segment. Please provide a link to a playable DASH manifest that reproduces the issue.

Also, the issue template also contains an explicit request for useful information, like the version of ExoPlayer that you're using, which would be useful here.

**Comment by perchrh** [comment]
The ExoPlayer version in question is 1.5.7. The same behaviour happens with 1.5.6 and 1.5.3, I've not found a version where it works. Sorry for omitting that part. 

It may not be related to the initialization data. The reasoning behind this assumption was that a comment in the code said "Load and parse the initialization data.", above the stack trace entry for com.google.android.exoplayer.chunk.ContainerMediaChunk#load
Looking at it more closely, I see that the file in question is declared in the manifest as a media file, not an initialization file. 

Regarding a complete test stream, I'll check if that is permitted, and get back to you. Most likely the stream url will have to be sent over another channel, like private e-mail.

**Comment by ojw28** [comment]
It doesn't have to be a complete test stream. It's possible to do something like create a manifest by hand that contains just enough of the media to reproduce the issue, for example, and then host just that subset of the media and the custom mpd side by side. Or similar.

You can email `dev.exoplayer@gmail.com`, although please update this issue so we know to go look for it! Thanks.

As an aside, the comment to which you reference is a typo; we'll fix that!

**Comment by perchrh** [comment]
The requested test stream is now available, and sent to the indicate e-mail address.

**Comment by ojw28** [comment]
Thanks! It appears the `trun` boxes in this stream are invalid. Specifically, both `first‐sample‐flags‐present` and `sample‐flags‐present` are set to true, but the specification (ISO 14496-12) states:

> first‐sample‐flags‐present; this over‐rides the default flags for the first sample only. This makes it possible to record a group of frames where the first is a key and the rest are difference frames, without supplying explicit flags for every sample. **If this flag and field are used, sample‐flags shall not be present.**

**Comment by perchrh** [comment]
Thanks for looking into it. We'll report the issue as an mp4-production bug to Wowza. 

It would be convenient if ExoPlayer allowed this use-case, if the parser was more permissive, like Google CAST and Chrome/Dash reference client. 
Of course, it may not be an intended feature that the stream works there, but it does make sense that they want to support "most streams". 
I realize that ExoPlayer may have other goals or requirements than the mentioned players, and wanted to share this idea, nevertheless.

**Comment by ojw28** [comment]
We do support "most streams" ;). We've been supporting DASH for over 2 years now, this is the first stream that we've seen with this issue, and it appears to be a pretty clear violation of the MP4 spec.

If players become arbitrarily more permissive over time then what incentive is there for a provider to fix their streams? And if there is no incentive and providers all end up shipping subtly broken streams because players are permissive, how is someone ever supposed to write a new player from scratch? They'd need a complete list of "workarounds that everyone does even though they're not part of any spec". I'd actually rather see CAST and Chrome updated to explicitly fail on this type of stream, not the other way around.

**Comment by perchrh** [comment]
Thanks for the explanation. ExoPlayer does indeed support most streams! 
I'll add an argument to the list - code readability. Adding a number of workarounds to ExoPlayer will make the code more difficult to read/verify and to extend :)
