### ISSUE TITLE
Only audio playing for encrypted dash(widevine modular drm) for HD(720p)

### ISSUE THREAD

**Issue by randeeppr** [google/ExoPlayer#1429]
Hi,

I am using exoplayer(1.5.3) in android with videos encrypted in widevine Modular DRM.
For me all the live SD channels are playing fine.
But for live HD(720p) and VOD(720p) only audio is coming. 
What can be the reason.

In proxy, I have given the following configuration. 
```
ALLOWED_TRACK_TYPES = "SD_HD"
    content_key_specs = [{ "track_type": "HD",
                           "security_level": 1,
                           "required_output_protection": {"hdcp": "HDCP_NONE" }
                         },
                         { "track_type": "SD",
                           "security_level": 1,
                           "required_output_protection": {"cgms_flags": "COPY_FREE" }
                         },
                         { "track_type": "AUDIO"}]
    request = json.dumps({"payload": payload,
                          "content_id": content_id,
                          "provider": self.provider,
                          "allowed_track_types": ALLOWED_TRACK_TYPES,
                          "use_policy_overrides_exclusively": True,
                          "policy_overrides": policy_overrides,
                          "content_key_specs": content_key_specs
                         ?
```
We are playing the video on a settopbox and its not a level 1 device. Its software drm. Someone mentioned Exoplayer doesn't play HD tracks by default when device has security level 3. Do we have to do anything additional?

Regards,
Randeep

**Comment by kidmiracleman** [comment]
Hi,

In the ExoPlayer demo app  - DashRenderBuilder.java has a method 'filterHdContent'  this always returns true if device is not level 1 (Assuming here it's L3).  This causes the player to disregard the HD AdaptionSet in the mpd whilst parsing it.

You can set the filterHdContent to always return false if you want to play HD, however it is typical of content owners to require a L1 Widevine implementation for HD content.
