### ISSUE TITLE
Exoplayer throws exception but dash.js works fine

### ISSUE THREAD

**Issue by hanihashemi** [google/ExoPlayer#1431]
Hi, 

We creating mpd file in server side and [dash-js player](http://dashif.org/reference/players/javascript/1.4.0/samples/dash-if-reference-player/) can play it, but exoplayer throwing below exceptions:
[stack-trace.txt](https://github.com/google/ExoPlayer/files/211668/stack-trace.txt)

mpd file in our server:
http://84.241.32.199:81/api/v0/videos/15/mpd

In case the above URLs doesn't work here is the mpd and the video:
[manifest.txt](https://github.com/google/ExoPlayer/files/211669/manifest.txt)
[video.zip](https://github.com/google/ExoPlayer/files/211670/video.zip)

I'm using exoplayer version 1.5.6.

**Comment by AquilesCanta** [comment]
Same as [#605](https://github.com/google/ExoPlayer/issues/605).

**Comment by hanihashemi** [comment]
Thanks for the reference. If I understand #605 correctly , that issue is about *self*-initializing segments, meaning `BaseSegment`s *without* an `indexRange` attribute which understandably results in unbound requests (i.e. client has to find the initialization by some kind of trial and error) but our problem is different in that we do provide the `indexRange` attribute and the client is indeed capable of finding and reading the presentations and even beings the buffering (as can be seen from the stack traces) but then something happens.

Thanks in advance

**Comment by hanihashemi** [comment]
We found the solution :dancers: by adding <Initialization range="0-866" /> tag into SegmentBase and it's worked

Thank you ;)

**Comment by AquilesCanta** [comment]
Sorry, I could have clarified and save you some reading. Cheers!
