### ISSUE TITLE
MPEG-TS endless preparing state

### ISSUE THREAD

**Issue by gitTronco** [google/ExoPlayer#1433]
I'm trying to play a fragment of a stream to make a player and I have not managed to reproduce using Exoplayer.

I am using a DefaultUriDataSource with ExtractorSampleSource. But not if I'm right.
If I can provide guidance on what steps or what type of DataSource or SampleSource have to use you appreciate it. I attached a sample of the stream that I downloaded.

I'm using demo Exoplayer app, Using mysc other with my url to a local server with ts file.
new Sample("SYNTH", "http://<mylocalserver>/file.ts", Util.TYPE_OTHER),
When using the demo application to view the stream in TYPE_OTHER mode, the player is stuck in playbackState=preparing. It appears to be buffering the stream, but doesn't get any further into the actual playback of the stream after this.

This is the result of analyzing the file with average info:
[file.ts.zip](https://github.com/google/ExoPlayer/files/212613/file.ts.zip)

General
ID : 17066 (0x42AA)
Complete name : file.ts
Format : MPEG-TS
File size : 2.39 MiB
Duration : 43s 840ms
Overall bit rate mode : Variable
Overall bit rate : 449 Kbps

Video
ID : 481 (0x1E1)
Menu ID : 1 (0x1)
Format : AVC
Format/Info : Advanced Video Codec
Format profile : High@L3.1
Format settings, CABAC : Yes
Format settings, ReFrames : 3 frames
Codec ID : 27
Duration : 43s 860ms
Bit rate : 200 Kbps
Width : 1 280 pixels
Height : 720 pixels
Display aspect ratio : 16:9
Frame rate mode : Variable
Color space : YUV
Chroma subsampling : 4:2:0
Bit depth : 8 bits
Scan type : Progressive
Stream size : 1.05 MiB (44%)

Audio
ID : 482 (0x1E2)
Menu ID : 1 (0x1)
Format : MPEG Audio
Format version : Version 1
Format profile : Layer 2
Codec ID : 3
Duration : 49s 656ms
Bit rate mode : Constant
Bit rate : 224 Kbps
Channel(s) : 2 channels
Sampling rate : 48.0 KHz
Compression mode : Lossy
Delay relative to video : 3s 816ms
Stream size : 1.33 MiB (55%)

Menu
ID : 66 (0x42)
Menu ID : 1 (0x1)
Duration : 43s 840ms
List : 481 (0x1E1) (AVC) / 482 (0x1E2) (MPEG Audio)
Service name : syntheractive
Service provider : syntheractive
Service type : digital television

Device used: Huawey p8 with 5.0.1 android.
Acer iconia 7 with android 4.4.2

I'm trying to use DASH HLS but the previus info data indicates that the file is MPEG-TS files and Exoplayer developer guide says MPEG-TS -> ExtractorSampleSource.

**Comment by AquilesCanta** [comment]
Same as [#1263](https://github.com/google/ExoPlayer/issues/1263).
