### ISSUE TITLE
adding a filter to exoplayer.

### ISSUE THREAD

**Issue by Usernamezhx** [google/ExoPlayer#1440]
I want to add a filter to exoplayer to process frame image , i am not sure the buff position ,**ExoPlayer/library/src/main/java/com/google/android/exoplayer/MediaCodecVideoTrackRenderer.java** is that right ?

**protected boolean processOutputBuffer**(long positionUs, long elapsedRealtimeUs, MediaCodec codec,ByteBuffer buffer, MediaCodec.BufferInfo bufferInfo, int bufferIndex, boolean shouldSkip) 
I am wondering what the ByteBuffer actually contains . many thanks .

**Comment by ojw28** [comment]
Please see https://github.com/google/ExoPlayer/issues/1220.
