### ISSUE TITLE
ExoPlayer is not sending STATE_FINISHED on some devices

### ISSUE THREAD

**Issue by DavidMihola** [google/ExoPlayer#1443]
I am currently developing an application that is supposed to download a few MP4 videos and play them in an endless loop.

While everything works perfectly when I run the app on my phone (LG G2 with KitKat) I experience a strange problem on the intended device, which is a screenless Android box that shows up as "Unknown SoftwinerEvb" in Android Studio. It is running Android 4.2.2.

The problem now is that on this specific device ExoPlayer does not send a STATE_FINISHED signal when the video ends. I rely on that signal to clean up that instance of ExoPlayer and move on to the next content item.

From the logs it seems that everything is OK, all the other events (STATE_PREPARING, STATE_READY, etc.) are delivered without a problem.

Occasionally, I see messages like the following in the logs:

```
SystemClock: time going backwards: prev 7298066659940(ioctl) vs now 7298066604315(ioctl), tid=32607
SystemClock: time going backwards: prev 7299786994940(ioctl) vs now 7299784280399(ioctl), tid=32607
SystemClock: time going backwards: prev 7300675466109(ioctl) vs now 7300675465734(ioctl), tid=32521
SystemClock: time going backwards: prev 7303400685776(ioctl) vs now 7303399587401(ioctl), tid=32607

```
but they don't seem to directly coincide with the problem. I just mention them because they are the only thing unusual that came to my attention...

Any ideas why the event is not sent?

**Comment by DavidMihola** [comment]
Some more info:
* As expected, the video plays without problems on other devices with Jellybean, e. g. a Galaxy Nexus with Android 4.2.1
* The file itself is not the problem, I compared the MD5 sum with the original on the server and they match.

**Comment by ojw28** [comment]
It's likely a problem similar to the one we workaround for some decoders with `MediaCodecTrackRenderer.codecNeedsEosPropagationWorkaround`. Most likely adding the problematic codec to this workaround will resolve the issue. We can't debug further without a full bug report (as requested in the issue template).

**Comment by DavidMihola** [comment]
Thanks for the reply and sorry for not providing a full report right away!

**A description of the issue**
In short, on some devices ExoPlayer does not send STATE_ENDED when a local MP4 video is finished.

**Steps describing how the issue can be reproduced**
- Download sample video from this URL: http://www.sample-videos.com/video/mp4/720/big_buck_bunny_720p_10mb.mp4
- Copy downloaded video to device
- Open latest version of ExoPlayer Demo App (1.5.7) in Android Studio
- Add the following item to `Samples.MISC`:

```
new Sample(
    "Local Sample Video",
    "file:/storage/sdcard1/Pictures/officetv/SampleVideo_1280x720_10mb.mp4",
    Util.TYPE_OTHER
)
```
Of course, change the file path to point to the video location on the device.
- Start ExoPlayer Demo and play "Local Sample Video"
- Expected: After about 1 minute the Stream should stop, playbackState should be "ended" and progress should stop increasing
- Actual: After about 1 minute the Stream stop, but playbackState stays "ready" and progress keeps increasing indefinitely.

**The device(s) and version(s) of Android on which the issue can be reproduced**
- The device in question is small Android box. Unfortunately, I have yet to determine an exact device name. In Android Studio it shows up as  "Unknown SoftwinerEvb" (probably that should be "Softwinner"). `Build.MANUFACTURER` is "unknown", `Build.MODEL` is "SoftwinerEvb". The box itself has no label that would give any clues.
- The device is running Android 4.2.2.
- The problem appeared in 100% of my trials on this device.
- The problem did not appear on any other tested device at all.

**ADB Bugreport**: https://gist.github.com/DavidMihola/59e832ac78ce2ccd5f79e8948c21e3cf

**Comment by ojw28** [comment]
Thanks! You'll probably find that modifying MediaCodecTrackRenderer's codecNeedsEosPropagationWorkaround method to look as follows resolves the issue:

```
private static boolean codecNeedsEosPropagationWorkaround(String name) {
 return Util.SDK_INT <= 17 && ("OMX.rk.video_decoder.avc".equals(name)
    || "OMX.allwinner.video.decoder.avc".equals(name));
}
```

Please give that a try and let us know what you find!

**Comment by DavidMihola** [comment]
@ojw28: Excellent - that indeed solved the problem! Thank you so much!

Would you take that change into the main branch or should I just use a custom version in the future? If the former, should I send a pull request?

**Comment by ojw28** [comment]
I'll make a change to our dev branch to include this workaround.
