### ISSUE TITLE
Support Opus in Ogg container

### ISSUE THREAD

**Issue by ojw28** [google/ExoPlayer#1447]
Tracking issue, as per title. We support Vorbis and Flac in Ogg, but not yet Opus.

**Comment by ojw28** [comment]
This is supported in our [2.x.x experimental branch](https://github.com/google/ExoPlayer/tree/dev-2.X.X-experimental).

**Comment by MostafaDavodi** [comment]
i have the sample problem when i want to stream .ogg file . 
latest version of your repository is 1.5.9 , what version i should use to play a ogg file ? 
my sample code : 


        exoPlayer = ExoPlayer.Factory.newInstance(1);
        
//        String url = "http://nuo9.48349.com:808/playlist/dXBSb2fkLndpA2ltZWRpYs5vcmcvd2lrAXBlZGlhL2NvbW1vbnMvdHJhbnNjb2RlZC9iL2JiL1Rlc3RFb2dnX21wM180OGticHMUd2f2L1Rlc3RFb2dnX21wM180OGticHMUd2f2Lm9nZw.ogg";


        Allocator allocator = new DefaultAllocator(BUFFER_SEGMENT_SIZE);
        String userAgent = Util.getUserAgent(getBaseContext(), "ExoPlayerDemo");
        DataSource dataSource = new DefaultUriDataSource(getBaseContext(), null, userAgent);



        ExtractorSampleSource sampleSource = new ExtractorSampleSource(
                radioUri, dataSource, allocator, BUFFER_SEGMENT_SIZE * BUFFER_SEGMENT_COUNT);
        MediaCodecAudioTrackRenderer audioRenderer = new MediaCodecAudioTrackRenderer(sampleSource);

        exoPlayer.prepare(audioRenderer);
        exoPlayer.setPlayWhenReady(true);
        exoPlayer.release();
