### ISSUE TITLE
Rendering processed output buffer data as a waveform is always ahead of played audio

### ISSUE THREAD

**Issue by m1c999** [google/ExoPlayer#1449]
I have extended the MediaCodecAudioTrackRenderer to get access to the output buffer to render the PCM data as a waveform.  The problem I am having is that the waveform seems to render faster than the audio being played. I assumed that once the output buffer was processed and discarded any rendering would be matched with the audio playback.  BTW: the player is using a uri datasource.  Code used is below:

    @Override
    protected boolean processOutputBuffer(long positionUs, long elapsedRealtimeUs, MediaCodec codec, ByteBuffer buffer, BufferInfo bufferInfo, int bufferIndex, boolean shouldSkip) throws ExoPlaybackException {
        boolean processed = false;
        
       //  Clone buffer 
        ByteBuffer bb = deepCopy(buffer);

        processed = super.processOutputBuffer(positionUs,elapsedRealtimeUs,codec,buffer,bufferInfo, bufferIndex, shouldSkip);
        if (processed & !shouldSkip)
        {
            // send data to be converted to shorts and then propogate a callback to render float data
            transform(bb);
            return true;
        }
        else
        {
            return false;
        }
    }

**Comment by ojw28** [comment]
`MediaCodecAudioTrackRenderer.processOutputBuffer` feeds each output buffer into an `AudioTrack`, but note that an `AudioTrack` has its own audio buffer (at the platform level). So if that buffer is being kept full there will be a delay between an output buffer being processed and the corresponding audio actually being output from the device.

To do what you're wanting to do you would probably need to generate the data that you need for your visualization from each output buffer, then add that data to the back of a queue with the associated timestamp `bufferInfo.presentationTimeUs`. You could then pull items off the front of the queue and render them as `MediaCodecAudioTrackRenderer.getPositionUs()` reaches the associated timestamps.

**Comment by m1c999** [comment]
Makes sense now.  Thanks for the pointers,  much appreciated.
