### ISSUE TITLE
ExoPlayer Example: Widevine Dash playback failure due to MediaDrmStateException

### ISSUE THREAD

**Issue by AbhilashNagabhushan** [google/ExoPlayer#1451]
**Device: **LGE Nexus 5
** OS :** Android 6.0.1

**ExoPlayer Version**: r1.5.7

**Issue**:  Widevine Enabled Content playback failed.

**Steps to Reproduce**: 
Step 1: Download/Clone latest code base from master branch of https://github.com/google/ExoPlayer/ .

Step 2: Compile the "Demo" Example code provided from ExoPlayer Repository.

Step 3: Install ExoPlayer Demo App on the Device Mentioned above.

Step 4: Open the App

Step 5: Click on "WIDEVINE DASH POLICY TESTS(GTS)" option on landing page.

Steps 6:  Select  "WV: HDCP not required"

After above steps Player shows up but it fails to render the video.

This issue is reproducible every-time we run the example on the above device.

**Please find the attached bugreport**.

**Appreciate All help in resolving this issue**

Thanks in Advance,
Abhilash
[exoplayer_bugreport_20160418.txt](https://github.com/google/ExoPlayer/files/224026/exoplayer_bugreport_20160418.txt)

**Comment by wvpaf** [comment]
Can you check if the device is secure boot?
To do, boot into 'fast boot', so adb reboot or power on with up & down vol button held.

You should see 'secure boot enabled'.

if the device is not in secure boot this behavior is expected

**Comment by AbhilashNagabhushan** [comment]
Thank you for your time.

Have checked the boot status and it is a secure boot device.
Please find the attached screenshot.

Appreciate all help if this can be resolved at earliest.

Please let us know if you need any other information which will help in resolving the issue.

![nexus_screenshot](https://cloud.githubusercontent.com/assets/1391119/14843372/4d7574c6-0c6d-11e6-870d-f7204e1740a6.jpg)

Thanks,
Abhilash

**Comment by wvpaf** [comment]
This issue reports a similar to "google/ExoPlayer Failed to handle key response: DRM vendor-defined error
#1468".
