### ISSUE TITLE
Mp4Extractor java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by blueslabs** [google/ExoPlayer#1452]
I am getting this from our error report. Unfortunately we don't know which file was played based on this call stack. And we were not able to reproduce.
Two questions: 
1. What could be the reasons? Seems the video doesn't have any sync sample?
2. How should I catch this exception, so we can get the url and report this? Was trying to subclass ExtractorSampleSource, so we can override onLoadCanceled(), but unfortunately it is a final class.

```
java.lang.ArrayIndexOutOfBoundsException: length=45; index=-1
com.google.android.exoplayer.extractor.mp4.Mp4Extractor.getPosition(Mp4Extractor.java:153)
com.google.android.exoplayer.extractor.ExtractorSampleSource.createLoadableFromPositionUs(ExtractorSampleSource.java:616)
com.google.android.exoplayer.extractor.ExtractorSampleSource.maybeStartLoading(ExtractorSampleSource.java:602)
com.google.android.exoplayer.extractor.ExtractorSampleSource.restartFrom(ExtractorSampleSource.java:539)
com.google.android.exoplayer.extractor.ExtractorSampleSource.onLoadCanceled(ExtractorSampleSource.java:487)
com.google.android.exoplayer.upstream.Loader$LoadTask.handleMessage(Loader.java:240)
android.os.Handler.dispatchMessage(Handler.java:102)
android.os.Looper.loop(Looper.java:158)
android.os.HandlerThread.run(HandlerThread.java:61)
com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
```

**Comment by AquilesCanta** [comment]
Which version of exoplayer are you using? I can only point you to possibly related issues. But without the media, there is not much I can do. There was a bug related to this when the application of the edit list resulted in a "sample window" without any sync sample. You can also try looking it up in the issues.

**Comment by blueslabs** [comment]
Sorry, forgot to mention the version. It is 1.5.6.

**Comment by AquilesCanta** [comment]
Acording to [#1336](https://github.com/google/ExoPlayer/issues/1336), 1.5.6 presented this issue I speak of. Please update the exoplayer version and see if the exception changes. If it does, you have met an Exoplayer limitation, unfortunately. The new version will provide better error description, at least.

**Comment by AquilesCanta** [comment]
If the exception does not change, file a new issue including all the useful information. It would be really useful if you could provide a way to reproduce the crash.

**Comment by blueslabs** [comment]
I am still getting this from error report. The video files are good. I can play them with the app. I guess there are some edge cases to make this happen.

**Comment by AquilesCanta** [comment]
You updated the ExoPlayer version but the error you are getting is still `ArrayIndexOutOfBoundsException`? Are you sure that the client report is not in the older version? If this is not the case, I will not be able to do anything without a sample to reproduce the issue. From the stack trace, the crash looks exactly like the one I spoke before, but unfortunately I cannot explore every possible input for which this exception could be thrown. There are two possible ways to go:

1. Look out for an exception with message: `The edited sample sequence does not contain a sync sample`.
2. Get a media sample that reproduces the issue and file a new issue.
