### ISSUE TITLE
[Question] Why cannot use handler ?

### ISSUE THREAD

**Issue by marianpavel** [google/ExoPlayer#1453]
I took a look over the samples and I noticed a Handler that is made on the DemoPlayer object with a getter.
When I tried to make my implementation I noticed that I get an error because of te handler.
Why the constructor won't accept a handler that has been just created 

        ExtractorSampleSource sub = new ExtractorSampleSource(Uri.parse(intent.getStringExtra("srt")), dataSource, allocator,
                BUFFER_SEGMENT_COUNT * BUFFER_SEGMENT_SIZE);
        Handler mainHandler = new Handler();
        TrackRenderer textRenderer = new TextTrackRenderer(sub, player, mainHandler.getLooper());

**Comment by andrewlewis** [comment]
Are you calling `new Handler()` on a thread that has a Looper, like the main thread (see [Handler()](http://developer.android.com/reference/android/os/Handler.html#Handler()))? In the demo app, the renderers are built on the main thread. What error do you see?

**Comment by marianpavel** [comment]
Yes, I am calling new Handler in the main thread, I get that constructor cannot be resolve.

        Intent intent = getIntent();
        player = ExoPlayer.Factory.newInstance(2);

        String userAgent = Util.getUserAgent(this, "ExoPlayer");

        Allocator allocator = new DefaultAllocator(BUFFER_SEGMENT_SIZE);
        Handler mainHandler = new Handler();

        Uri uri = Uri.parse(intent.getStringExtra("url"));

        // Build the video and audio renderers.
        DefaultBandwidthMeter bandwidthMeter = new DefaultBandwidthMeter(mainHandler, null);
        DataSource dataSource = new DefaultUriDataSource(this, bandwidthMeter, userAgent);

        ExtractorSampleSource sampleSource = new ExtractorSampleSource(uri, dataSource, allocator,
                BUFFER_SEGMENT_COUNT * BUFFER_SEGMENT_SIZE);

        MediaCodecVideoTrackRenderer videoRenderer = new MediaCodecVideoTrackRenderer(this,
                sampleSource, MediaCodecSelector.DEFAULT, MediaCodec.VIDEO_SCALING_MODE_SCALE_TO_FIT, 5000);

        MediaCodecAudioTrackRenderer audioRenderer = new MediaCodecAudioTrackRenderer(sampleSource,
                MediaCodecSelector.DEFAULT, null, true);

        SurfaceView surfaceView = (SurfaceView) findViewById(R.id.surfaceView);

        player.prepare(videoRenderer, audioRenderer);
        player.sendMessage(videoRenderer, MediaCodecVideoTrackRenderer.MSG_SET_SURFACE, surfaceView.getHolder().getSurface());

        MediaController mediaController = (MediaController) findViewById(R.id.mediaController);

        PlayerControl playerControl = new PlayerControl(player);
        mediaController.setMediaPlayer(playerControl);
        mediaController.setEnabled(true);

        ExtractorSampleSource sub = new ExtractorSampleSource(Uri.parse(intent.getStringExtra("srt")), dataSource, allocator,
                BUFFER_SEGMENT_COUNT * BUFFER_SEGMENT_SIZE);

        TrackRenderer textRenderer = new TextTrackRenderer(sub, player, mainHandler.getLooper());

        player.setPlayWhenReady(true);

These are called in onCreate

**Comment by andrewlewis** [comment]
I'm not sure exactly what error you are referring to, so could you paste the exception here?

As a separate issue, DataSources can only be opened by one thing at a time, so you will need to have a separate one for the second ExtractorSampleSource.
