### ISSUE TITLE
请问怎么播放本地视频文件啊？比如raw里面的文件

### ISSUE THREAD

**Issue by v5lukia** [google/ExoPlayer#1455]
请问怎么播放本地视频文件啊？比如raw里面的文件？

**Comment by v5lukia** [comment]
How can play local video ? For example raw

**Comment by ojw28** [comment]
ExoPlayer correctly plays local file URIs of the form `file:///path/to/media/file.ext`. Beyond that, it's unclear what this issue is asking.
