### ISSUE TITLE
Exoplayer cannot player a Widevine asset (it can be played on shaka player) 

### ISSUE THREAD

**Issue by hoimingw** [google/ExoPlayer#1457]
**A description of the issue.**
Exoplayer (r1.5.7) cannot player a Widevine asset, which can be played on shaka player v1.6.5.

**Steps describing how the issue can be reproduced, ideally in the ExoPlayer demo app.**
1. Host a Widevine encrypted DASH asset on a webserver.
2. Enter the DASH URL at Exoplayer Demo app at Android Studio 1.5.1.
3. Connect Nexus 10 (Android 5.1.1) to the PC on which the Android Studio runs.
4. Click "Run" on Android Studio and choose Nexus 10.
5. The Exoplayer demo app is started on Nexus 10 but the video cannot be played.

**A link to content that reproduces the issue.**
The tested Widevine encrypted DASH asset can be downloaded from the following FTP server.
FTP server: ftp.harmonicinc.com
filename: dash_widevine.zip
username: hlit8448
password: 5jH62BU2

**The version of ExoPlayer being used.**
r1.5.7

**The device(s) and version(s) of Android on which the issue can be reproduced, and how easily it reproduces**
Device: Nexus 10
Android version: 5.1.1
Reproducible:  Always

**A bug report taken from the device just after the issue occurs, attached as a file. A bug report can be captured using "adb bugreport".**
The bug report can be found from the following FTP server.
FTP server: ftp.harmonicinc.com
filename: bugreport_exoplayer.txt
username: hlit8448
password: 5jH62BU2

**Comment by jefftinker** [comment]
Please check the license policy.  Nexus 10 is a level 3 (no hardware DRM support) device, if your policy specifies HDCP required or a secure data path, you will get this error.

**Comment by hoimingw** [comment]
Hi Jefftinker,
Thanks for your response. We will check the license and post updates here.
Thanks,

**Comment by wvpaf** [comment]
Hi hoimingw@, 

Any update? Else we will assume policy settings addressed issue and will close in the next 14 days ... or so.

**Comment by m-scheepers** [comment]
@jefftinker is there documentation which outlines the limitations of Widevine Device Security Level in relation to output protection settings?

Based on your comment of Apr 27 I am wondering if an issue we observed when HDCP_V1 is set relates to the Widevine Device Security Level of the device. I will investigate if this seems to be linked to Widevine Device Security level but would appreciate if you could confirm there are limitations in this field.

**Comment by wvpaf** [comment]
@Mark86NL  as for documentation if you are part of the CWIP program there are documents there that will describe the security levels.  

However to reiterate if L3, least secure, playback is chosen then HDCP cannot be initiated.

**Comment by m-scheepers** [comment]
@wvpaf thanks for this feedback. Our company is part of CWIP program. 
- what document describes the possible parameters per security level, such as HDCP settings?
- would it be possible to request Modular DRM Vendors Extension documentation as suggested in https://support.google.com/widevine/answer/6072714?hl=en

**Comment by pgrov** [comment]
@Mark86NL as your company is part of the CWIP program, you should reference the following documents related to your questions which are currently available on the CWIP portal.
- Android Vendor Extensions document
- Proxy Integration Document which includes an HDCP Output Matrix in the appendix

**Comment by wvpaf** [comment]
Closing as the path to documentation was provided above.
Please reopen if the main question was not addressed.
