### ISSUE TITLE
Infinite loop. Need help.

### ISSUE THREAD

**Issue by dianon** [google/ExoPlayer#1458]
Hello. I want to use **ExoPlayer** with **SurfaceView** and **SeekBar**. **buildTrackName** function I took from **ExoPlayer Demo**. I want to use **SeekBar** for changing position of player and **listView** for displaying all of audio track of my video. When I'm use **ExoPlayer** functions to get player duration or get all audio tracks  from video, these functions return -1 for **getDuration()** and 0 for **getTrackCount()**. I tried to put these functions in different parts of the code, but they work only in **onPlayerStateChanged** method of **ExoPlayer.Listener**. But! in this case, after all the functions, the program goes into an infinite loop.

    public class MainActivity extends AppCompatActivity implements SurfaceHolder.Callback{

    private String videoPath = "myVideoPath";
    private SurfaceView surfaceView;
    private SeekBar seekBar;
    private ListView listView;
    private ArrayList<String> trackList;
    private ArrayAdapter<String> arrayAdapter;
    private ExoPlayer exoPlayer;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        surfaceView = (SurfaceView) findViewById(R.id.surfaceView);
        seekBar = (SeekBar) findViewById(R.id.seekBar);
        listView = (ListView) findViewById(R.id.listView);

        trackList = new ArrayList<>();
        arrayAdapter = new ArrayAdapter<String>(this, android.R.layout.simple_expandable_list_item_1, audioList);
        listView.setAdapter(arrayAdapter);

        MediaCodecSelector mediaCodecSelector = MediaCodecSelector.DEFAULT;

        Uri uri = Uri.parse(videoPath);
        DataSource dataSource = new DefaultUriDataSource(this, "test");
        ExtractorSampleSource extractorSampleSource = new ExtractorSampleSource(
                uri, dataSource, new DefaultAllocator(64*1024), 256*64*1024,null);
        MediaCodecVideoTrackRenderer videoRenderer = new MediaCodecVideoTrackRenderer(this,extractorSampleSource,mediaCodecSelector,MediaCodec.VIDEO_SCALING_MODE_SCALE_TO_FIT);
        MediaCodecAudioTrackRenderer audioRenderer = new MediaCodecAudioTrackRenderer(
                extractorSampleSource, mediaCodecSelector);

        exoPlayer = ExoPlayer.Factory.newInstance(2);

        exoPlayer.sendMessage(videoRenderer, MediaCodecVideoTrackRenderer.MSG_SET_SURFACE, surfaceView.getHolder().getSurface());
        
        exoPlayer.prepare(videoRenderer,audioRenderer);

        exoPlayer.setPlayWhenReady(true);

        exoPlayer.addListener(new ExoPlayer.Listener() {
            @Override
            public void onPlayerStateChanged(boolean playWhenReady, int playbackState) {
                if (playbackState == ExoPlayer.STATE_READY){
                    seekBar.setMax((int)exoPlayer.getDuration());         
                    int trackCount = exoPlayer.getTrackCount(1);
                    for (int i = 0; i < trackCount; i++) {
                        trackList.add(buildTrackName(exoPlayer.getTrackFormat(1, i)));
                    }
                } //infinite loop after this place
            }

            @Override
            public void onPlayWhenReadyCommitted() {

            }

            @Override
            public void onPlayerError(ExoPlaybackException error) {

            }
        });

    }

    ///
    }

**Comment by ojw28** [comment]
This is a general programming question, not something that's specifically ExoPlayer related. There are several ways of avoiding an infinite loop, for example by posting a message to a different thread (or better) posting a message back to the same thread to be handled at a later time. I suggest taking a look at [Handlers](http://developer.android.com/reference/android/os/Handler.html).

Please ask general questions on StackOverflow rather than the issue tracker. Thanks!
