### ISSUE TITLE
[Question] About Widevine Provision & Security Level

### ISSUE THREAD

**Issue by imironhead** [google/ExoPlayer#1460]
I am trying to understand NotProvisionedException when open DRM session. As far as I know, there are three security levels. Both L1 & L2 are factory provisioned while L3 is field provisioned (according to this [page](http://www.programering.com/a/MDO1EjNwATQ.html)).

1. Does that mean L1 & L2 devices won't throw NotProvisionedException?

2. Since we have to provision devices when NotProvisionedException is thrown, is there any methods to erase provisions for testing? I have tried to factory reset 2 L1 devices and got no NotProvisionedException, does that mean it's not possible to erase "factory provision"? Can provision on L3 devices be erased by factory reset (or any other methods)?

Thanks

**Comment by ojw28** [comment]
- I *think* it's possible for NotProvisionedException to be thrown on both L1 and L3 devices. I don't fully understand the provisioning process though.
- As an aside, note that you can force an L1 device to use L3 by calling `mediaDrm.setPropertyString("securityLevel", "L3");` immediately after the `MediaDrm` is instantiated. This might be useful for your testing.
- On a rooted device, I believe it's possible to erase provisioning as follows:
```
adb root
adb remount
adb shell rm -r /data/mediadrm/IDM1013
```

**Comment by imironhead** [comment]
I renamed some files under /data/mediadrm/IDM1013/ and it works. Thanks.
