### ISSUE TITLE
Can not play video playlist in background mode

### ISSUE THREAD

**Issue by jimztercrack** [google/ExoPlayer#1465]
I'm using ExoPlayer to implement my media player for my Android application. Now i'm facing with the new issue .When i try to play video playlist in background mode( when user tap home button , my application enters background mode, audio keeps playing and turns off), the audio can not be played continuos as in the normal mode.

**Comment by ojw28** [comment]
General Q&A questions should be asked on StackOverflow, not our issue tracker. Thanks.
