### ISSUE TITLE
play music in background

### ISSUE THREAD

**Issue by jimztercrack** [google/ExoPlayer#1466]
How can I play the music in background  keeping the muisic even when i change the task or lock the screen here is the code: https://github.com/jimztercrack/TestPlayerActivity/blob/master/app/src/main/java/cr/go/sinart/testplayeractivity/TestPlayerActivity.java

**Comment by ojw28** [comment]
General Q&A questions should be asked on StackOverflow, not our issue tracker. Thanks.
