### ISSUE TITLE
Exoplayer to obtain decoded image.

### ISSUE THREAD

**Issue by Usernamezhx** [google/ExoPlayer#1467]
Last week, i have asked thi question , i'm still confused . I want to get the **decoded frame** to process E.g **denoise**, **enhancement **and so on . but I am not sure the specific location, i cant find the buff.i need your help . many thanks.

**Comment by ojw28** [comment]
I'm sorry, but this is an issue tracker; it's not the right place to ask general how-to / tutorial questions, particularly when the scope of the question is outside of the immediate scope of the project. This has already been answered in #1440. If you're still struggling, StackOverflow would be a more suitable place to ask your questions.
