### ISSUE TITLE
Failed to handle key response: DRM vendor-defined error

### ISSUE THREAD

**Issue by tiger1990** [google/ExoPlayer#1468]
**Configuration Of Device On Which Getting This Error:**
Below are the configuration of Nexus Device On Which i am getting this error:
Model : Nexus 5
Android Version: 6.0.1
BaseBand Version: M8974A-2.0.50.2.28
Kernel Version 
3.4.0-gbaedb01
android-build@vped10.mtv.corp.google.com#1
Sat Jan 16 01:19:53 UTC 2016
Build Number: MMB29V

I have tried this sample on multiple android devices.
Some of the devices giving me this error.
eg. Htc, Lyf, Lenovo 
You can easily reproduce this error on the above mention configuration of Nexus 5.

**Complete Logs Are Given Below:**

```
com.google.android.exoplayer.demo E/MediaDrm-JNI: Illegal state exception: Failed to handle key response: DRM vendor-defined error: -2902 (-2902)
04-06 13:26:43.085 14713-14713/com.google.android.exoplayer.demo E/EventLogger: internalError [2.60, drmSessionManagerError]
android.media.MediaDrm$MediaDrmStateException: Failed to handle key response: DRM vendor-defined error: -2902
at android.media.MediaDrm.provideKeyResponse(Native Method)
at com.google.android.exoplayer.drm.StreamingDrmSessionManager.onKeyResponse(StreamingDrmSessionManager.java:392)
at com.google.android.exoplayer.drm.StreamingDrmSessionManager.access$800(StreamingDrmSessionManager.java:45)
at com.google.android.exoplayer.drm.StreamingDrmSessionManager$PostResponseHandler.handleMessage(StreamingDrmSessionManager.java:482)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.os.HandlerThread.run(HandlerThread.java:61)
at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
04-06 13:26:43.092 14713-15537/com.google.android.exoplayer.demo E/ExoPlayerImplInternal: Internal track renderer error.
com.google.android.exoplayer.ExoPlaybackException: android.media.MediaDrm$MediaDrmStateException: Failed to handle key response: DRM vendor-defined error: -2902
at com.google.android.exoplayer.MediaCodecTrackRenderer.shouldWaitForKeys(MediaCodecTrackRenderer.java:680)
at com.google.android.exoplayer.MediaCodecTrackRenderer.feedInputBuffer(MediaCodecTrackRenderer.java:630)
at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:459)
at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431)
at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
at android.os.Handler.dispatchMessage(Handler.java:98)
at android.os.Looper.loop(Looper.java:148)
at android.os.HandlerThread.run(HandlerThread.java:61)
at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)

Caused by: android.media.MediaDrm$MediaDrmStateException: Failed to handle key response: DRM vendor-defined error: -2902
at android.media.MediaDrm.provideKeyResponse(Native Method)
at com.google.android.exoplayer.drm.StreamingDrmSessionManager.onKeyResponse(StreamingDrmSessionManager.java:392)
at com.google.android.exoplayer.drm.StreamingDrmSessionManager.access$800(StreamingDrmSessionManager.java:45)
at com.google.android.exoplayer.drm.StreamingDrmSessionManager$PostResponseHandler.handleMessage(StreamingDrmSessionManager.java:482)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148) 
at android.os.HandlerThread.run(HandlerThread.java:61) 
at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 
04-06 13:26:43.104 14713-14713/com.google.android.exoplayer.demo E/EventLogger: playerFailed [2.62]
com.google.android.exoplayer.ExoPlaybackException: android.media.MediaDrm$MediaDrmStateException: Failed to handle key response: DRM vendor-defined error: -2902
at com.google.android.exoplayer.MediaCodecTrackRenderer.shouldWaitForKeys(MediaCodecTrackRenderer.java:680)
at com.google.android.exoplayer.MediaCodecTrackRenderer.feedInputBuffer(MediaCodecTrackRenderer.java:630)
at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:459)
at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431)
at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
at android.os.Handler.dispatchMessage(Handler.java:98)
at android.os.Looper.loop(Looper.java:148)
at android.os.HandlerThread.run(HandlerThread.java:61)
at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
```

**Please find attached bugreport.:**
[nexus5-bugreport.txt](https://github.com/google/ExoPlayer/files/234152/nexus5-bugreport.txt)

**Comment by wvpaf** [comment]
Can you check if the device is secure boot?
To do, boot into 'fast boot', so adb reboot or power on with up & down vol button held.

You should see 'secure boot enabled'.

**Comment by wvpaf** [comment]
If the device is not secure booted this behavior is expected.

**Comment by jefftinker** [comment]
![image](https://cloud.githubusercontent.com/assets/16543268/14836182/20ed4d8e-0bc3-11e6-8c52-b6d45c36a86d.png)

**Comment by tiger1990** [comment]
![img_20160427_191448441](https://cloud.githubusercontent.com/assets/4586840/14854250/a052adbe-0cac-11e6-8a5e-23f02783cf40.jpg)

@jefftinker  I can see sameconfiguration as you see on your device.
@wvpaf  Secure Boot is enable in my divice.

**Comment by polmabri** [comment]
I get a similar error when trying to login into the netflix app, tried it on my nexus 5x with android 6.0.1 AND android n preview 3 NPD35K.
Already talked about three hours with a special netflix tech-team and tried everything to resolve the problem, including: executing a factory reset, diving into the android bug report, going through the logging file.... nothing helped.

`
build.board: bullhead
build.bootloader: BHZ11b
build.brand: google
build.cpu_abi: arm64-v8a
build.cpu_abi2: 
build.device: bullhead
build.display: NPD35K
build.fingerprint: google/bullhead/bullhead:N/NPD35K/2864170:user/release-keys
build.hardware: bullhead
build.host: vpeb4.mtv.corp.google.com
build.id: NPD35K
build.manufacturer: LGE
build.model: Nexus 5X
build.product: bullhead
build.radio: unknown
build.serial: 012ff5060bdc41d4
build.tags: release-keys
build.time: 1463100342000
build.type: user
build.user: android-build
version.codename: N
version.incremental: 2864170
version.release: N
version.sdk_int: 23

05-24 00:59:04.003 I/WVCdm   (518): CdmEngine::OpenSession
05-24 00:59:04.003 D/DrmWidevineDash(518): OEMCrypto_OpenSession: starts! SID=0xff9db344
05-24 00:59:04.003 D/DrmWidevineDash(518): OEMCrypto_OpenSession Session ID = 0
05-24 00:59:04.004 D/DrmWidevineDash(518): OEMCrypto_OpenSession SID = 2
05-24 00:59:04.004 D/DrmWidevineDash(518): OEMCrypto_OpenSession: ends! returns 0
05-24 00:59:04.004 D/DrmWidevineDash(518): _oecc09: function time: 1ms (0s 1203594ns)
05-24 00:59:04.006 D/DrmWidevineDash(518): _oecc06: function time: 1ms (0s 1281927ns)
05-24 00:59:04.013 D/DrmWidevineDash(518): OEMCrypto_LoadDeviceRSAKey: starts! SID=2, wrapped_rsa_key=0xe75c4c00, wrapped_rsa_key_length=1280
05-24 00:59:04.018 D/DrmWidevineDash(518): OEMCrypto_LoadDeviceRSAKey: ends! returns 0
05-24 00:59:04.018 D/DrmWidevineDash(518): _oecc19: function time: 4ms (0s 4933126ns)
05-24 00:59:04.019 D/DrmWidevineDash(518): _oecc06: function time: 1ms (0s 1074844ns)
05-24 00:59:04.019 I/WVCdm   (518): CdmEngine::QueryKeyControlInfo
05-24 00:59:04.020 I/WVCdm   (518): CdmEngine::GenerateKeyRequest
05-24 00:59:04.020 D/DrmWidevineDash(518): OEMCrypto_GetDeviceID: starts! deviceID=0xe7277200, idLength=0xe787f26c
05-24 00:59:04.032 D/DrmWidevineDash(518): OEMCrypto_GetDeviceID: ends! returns 0
05-24 00:59:04.032 D/DrmWidevineDash(518): _oecc07: function time: 12ms (0s 12192553ns)
05-24 00:59:04.032 D/DrmWidevineDash(518): OEMCrypto_SupportsUsageTable: starts!
05-24 00:59:04.032 D/DrmWidevineDash(518): OEMCrypto_SupportsUsageTable: is_supported = 1
05-24 00:59:04.032 D/DrmWidevineDash(518): OEMCrypto_SupportsUsageTable: wv_app_version =0x32
05-24 00:59:04.032 D/DrmWidevineDash(518): OEMCrypto_SupportsUsageTable: ends! returns 0
05-24 00:59:04.032 D/DrmWidevineDash(518): _oecc29: function time: 0ms (0s 391666ns)
05-24 00:59:04.033 D/DrmWidevineDash(518): OEMCrypto_IsAntiRollbackHwPresent: starts!
05-24 00:59:04.033 D/DrmWidevineDash(518): OEMCrypto_IsAntiRollbackHwPresent ends! ret=0, is_antirb_enabled = 1
05-24 00:59:04.033 D/DrmWidevineDash(518): _oecc39: function time: 0ms (0s 459479ns)
05-24 00:59:04.033 D/DrmWidevineDash(518): OEMCrypto_APIVersion: starts!
05-24 00:59:04.033 D/DrmWidevineDash(518): hlos api version =  11
05-24 00:59:04.033 D/DrmWidevineDash(518): tz api version =  11
05-24 00:59:04.033 D/DrmWidevineDash(518): OEMCrypto_APIVersion: ends! returns version 11
05-24 00:59:04.033 D/DrmWidevineDash(518): _oecc22: function time: 0ms (0s 382656ns)
05-24 00:59:04.033 D/DrmWidevineDash(518): OEMCrypto_GetHDCPCapability starts!
05-24 00:59:04.034 D/DrmWidevineDash(518): OEMCrypto_GetHDCPCapability current=255, max=4
05-24 00:59:04.034 D/DrmWidevineDash(518): OEMCrypto_GetHDCPCapability ends! ret = 0
05-24 00:59:04.034 D/DrmWidevineDash(518): _oecc44: function time: 0ms (0s 364322ns)
05-24 00:59:04.034 D/DrmWidevineDash(518): OEMCrypto_GenerateNonce: starts! SID=2, nonce=0xe787f3bc
05-24 00:59:04.034 D/DrmWidevineDash(518): OEMCrypto_GenerateNonce: ends! returns 0
05-24 00:59:04.034 D/DrmWidevineDash(518): _oecc14: function time: 0ms (0s 410156ns)
05-24 00:59:04.034 D/WVCdm   (518): PrepareKeyRequest: nonce=161667085
05-24 00:59:04.034 D/DrmWidevineDash(518): OEMCrypto_GenerateRSASignature starts! SID=2, message=0xe75dcc00
05-24 00:59:04.034 D/DrmWidevineDash(518): message_length=1630, signature=0xe7b39500, signature_length=0xe787f35c
05-24 00:59:04.169 D/DrmWidevineDash(518): OEMCrypto_GenerateRSASignature returns 0
05-24 00:59:04.169 D/DrmWidevineDash(518): _oecc36: function time: 134ms (0s 134261888ns)
05-24 00:59:04.603 I/WVCdm   (518): CdmEngine::RemoveKeys
05-24 00:59:04.603 D/DrmWidevineDash(518): OEMCrypto_CloseSession: starts! SID=1
05-24 00:59:04.604 D/DrmWidevineDash(518): OEMCrypto_CloseSession: ends! returns 0
05-24 00:59:04.604 D/DrmWidevineDash(518): _oecc10: function time: 0ms (0s 518125ns)
05-24 00:59:04.606 I/WVCdm   (518): CdmEngine::CloseSession
05-24 00:59:04.607 I/WVCdm   (518): CdmEngine::AddKey
05-24 00:59:04.607 D/DrmWidevineDash(518): OEMCrypto_DeriveKeysFromSessionKey: starts! SID=2
05-24 00:59:04.607 D/DrmWidevineDash(518): enc_session_key=0xe78e1500, enc_session_key_length=256, mac_key_context=0xe742b000
05-24 00:59:04.607 D/DrmWidevineDash(518): mac_key_context_length=1649, enc_key_context=0xe78dc300, enc_key_context_length=1645
05-24 00:59:04.740 D/DrmWidevineDash(518): OEMCrypto_DeriveKeysFromSessionKey: ends! returns 0
05-24 00:59:04.741 D/DrmWidevineDash(518): _oecc21: function time: 133ms (0s 133497825ns)
05-24 00:59:04.741 D/DrmWidevineDash(518): OEMCrypto_LoadKeys starts! SID=2, message=0xe7428000, message_length=340, signature=0xe788f780, kary_addr=0xe78a96c0
05-24 00:59:04.741 D/DrmWidevineDash(518): signature_length=32, enc_mac_key_iv=0x0, enc_mac_key=0x0, num_keys=2, pst=(null), pst_length=0
05-24 00:59:04.749 D/DrmWidevineDash(518): OEMCrypto_LoadKeys returns 10036
05-24 00:59:04.749 D/DrmWidevineDash(518): _oecc47: function time: 8ms (0s 8107397ns)
05-24 00:59:04.749 E/WVCdm   (518): CryptoSession::LoadKeys: OEMCrypto_LoadKeys error=10036
05-24 00:59:04.749 E/WVCdm   (518): CdmEngine::AddKey: keys not added, result = 99
05-24 00:59:04.750 E/MediaDrm-JNI(18073): Illegal state exception: Failed to handle key response: DRM vendor-defined error: -2902 (-2902)
05-24 00:59:06.183 I/ActivityManager(892): START u0 {flg=0x10804000 cmp=com.android.systemui/.recents.RecentsActivity} from uid 10029 on display 0
`

**Comment by wvpaf** [comment]
There are various failures that will lead to a  : 'Illegal state exception: Failed to handle key response: DRM vendor-defined error: -2902 (-2902)'

The original bugreport for this case the error right before is : ' WVCdm   : CryptoSession::LoadKeys: OEMCrypto_LoadKeys error=10012'. 

Following up with the OEM out of band.

**Comment by wvpaf** [comment]
no new update from the OEMs.

**Comment by Mark86NL** [comment]
What information would help you to identify and resolve this issue (f.i. manifests, etc.)? We are also experiencing this issue on a subset of devices  (f.i. Samsung SM-G361F (5.1.1); Samsung Galaxy S4 (5.0.1)).

What's special on our set-up is that we provide live streams from multiple streaming sources, using the same DRM set-up. Within one set-up this is working on all devices. On the alternative set-up we see the issue on a subset of devices. We would like to understand what differences in the stream could explain this issue.

**Comment by ojw28** [comment]
@wvpaf - Did we ever hear back from the OEM? If not, please add the "wont fix" label and close, since I don't think there's anything we can do to fix this in ExoPlayer.

**Comment by wvpaf** [comment]
We have not. Sorry.
