### ISSUE TITLE
[Question] Tracking Playback in HLS

### ISSUE THREAD

**Issue by donnfelker** [google/ExoPlayer#1469]
Hello, 

Thanks for the great lib. I am streaming HLS (m3u8 files) for an audio app I'm building. I need to be able to track how much of the audio has been listened to. I'm having a difficult time trying to figure out where to hook into the player to gather this information. Is this possible? If so, what class/listener should I look at? Thanks!

**Comment by ojw28** [comment]
What's wrong with `ExoPlayer.getCurrentPosition` and `ExoPlayer.getDuration`?

**Comment by donnfelker** [comment]
Seems to me it's a PEBCAK error in this case (me). 😄   Thanks for the quick tip @ojw28, not sure why I didn't see that before (facepalm).
