### ISSUE TITLE
how can i turn off the video volume?

### ISSUE THREAD

**Issue by lmqwudi** [google/ExoPlayer#1471]
how can i turn off  or turn down the video volume?

**Comment by andrewlewis** [comment]
You can set the volume by sending [MSG_SET_VOLUME](https://github.com/google/ExoPlayer/blob/master/library/src/main/java/com/google/android/exoplayer/MediaCodecAudioTrackRenderer.java#L78) to the MediaCodecAudioTrackRenderer like this: `player.sendMessage(audioRenderer, MediaCodecAudioTrackRenderer.MSG_SET_VOLUME, volume);`, where volume is a Float between 0 and 1.
