### ISSUE TITLE
Event at playback time?

### ISSUE THREAD

**Issue by damienoliver** [google/ExoPlayer#1472]
Hi,
I would like to dispatch event's at defined times during playback. Does exoplayer have a time observer object suitable for this use? ...I would like to avoid polling the currentPosition value if possible.

Thanks!

**Comment by ojw28** [comment]
No, there's no built in support for that. Although you could easily implement your own `TrackRenderer` and inject it into the player that could dispatch events at specified times during playback.

**Comment by damienoliver** [comment]
Thanks for the tip. `doSomeWork(long positionUs, long elapsedRealtimeUs)` seems to fire quick enough for my needs. Cheers.

**Comment by rakesh1988** [comment]
is there an equivalent in exoplayer2?

**Comment by andrewlewis** [comment]
The equivalent would be implementing your own Renderer (subclassing BaseRenderer) and using `positionUs` passed to [`render`](https://github.com/google/ExoPlayer/blob/ce55d1a/library/core/src/main/java/com/google/android/exoplayer2/Renderer.java#L208).

**Comment by ojw28** [comment]
Providing a more convenient API for this is also tracked by https://github.com/google/ExoPlayer/issues/2189.

**Comment by tonihei** [comment]
We're currently working on this feature to let the player run a callback when it reaches a certain playback position. We would like to have your opinion on some edge cases in #2189 - please let us know what would fit your requirements best.
