### ISSUE TITLE
when i call seekTo method i get an error

### ISSUE THREAD

**Issue by lmqwudi** [google/ExoPlayer#1473]
when I call seekTo method I get java.lang.IllegalStateException: Handler (android.os.Handler) {2bfdfc02} sending message to a Handler on a dead thread

**Comment by AquilesCanta** [comment]
This is not a proper issue report. Please read the ISSUE_TEMPLATE file and provide every corresponding item. On top of this, please see [#426](https://github.com/google/ExoPlayer/issues/426).
