### ISSUE TITLE
Question: Why is the bandwidth fraction to find effective bandwidth different between DASH/SS & HLS

### ISSUE THREAD

**Issue by peddisri** [google/ExoPlayer#1475]
I have a question.

The bandwidth meter gives an estimated bandwidth to HlsChunkSource & AdaptiveFormatEvaluator. I do understand the need of considering only a fraction of the estimated bandwidth due to inaccuracies in the estimated bandwidth. However, why is the fraction value different between HLS and SS/DASH?

AdaptiveFormatEvaluator (used for DASH & SS) uses 0.75 as the default bandwidth fraction, whereas HlsChunkSource considers 0.8.  Is there a reasoning behind this decision or a side-effect of different implementations.

I saw one of your comments on a different issue that in V2 of Exoplayer , you would start using FormatEvaluator for HLS too. This will unify the values eventually, am I right?.

Another related question is that if the user of bandwidth meter has to account for inaccuracies, won't it be good to handle it inside bandwidth meter itself? That way, anybody that uses Bandwidth meter gets the final bandwidth to be used for decision making and the decision making is consistent across all streaming formats.

**Comment by ojw28** [comment]
- Yes, HLS will use FormatEvaluator in V2.
- I suspect there isn't a really good reason behind the chosen values being different, however it should be noted that there are differences between DASH/SS and HLS that could require legitimately different fractions. Specifically (1) In DASH/SS audio is demuxed and will require some bandwidth of its own, where-as in HLS the audio is typically, but not always, muxed with the video (2) For HLS it's necessary to download overlapping chunks when switching qualities, where-as for DASH/SS this is not required.

**Comment by peddisri** [comment]
Thanks @ojw28 . I guessed this reason - but was curious to know how were these specific numbers were decided? Did the team do some kind of stream analysis? Anyways, thanks for the answer.! Really appreciate it.

**Comment by ojw28** [comment]
I don't think they've been fine tuned, if that's your question. In reality the optimal number is dependent on the serving side as well as the client. For example the cost of an edge cache miss on the serving side likely affects what the optimal number should be. So it's unlikely that a single best value exists, and if you have the time and the urge it's worth doing your own studies to try and find the best value for your specific use case.

**Comment by peddisri** [comment]
@ojw28 Thanks for the response.
