### ISSUE TITLE
Get current frame number not current time in millisecond

### ISSUE THREAD

**Issue by jclova** [google/ExoPlayer#1479]
I need to know the 'accurate' current frame.
However, ExoPlayer only provides current time in millisecond. (Using getCurrentPosition() call)
I could calculate the frame number from the millisecond but I get the round error so the frame number is not accurate.
There are other people who are asking for the same feature:
http://stackoverflow.com/questions/33626850/android-exoplayer-get-current-frame-number-from-video#comment61351768_33626850

**Comment by ojw28** [comment]
I don't think we'll ever provide a way to retrieve the exact frame number. In some types of media it's not possible to determine the exact frame number. It's more sensible to try and retrieve the exact frame timestamp. There's already a solution explaining how to do that on the StackOverflow question you're linking to, however, so why not just do that?
