### ISSUE TITLE
Question: is it possible to read multiple video track/audio track at the same time?

### ISSUE THREAD

**Issue by jclova** [google/ExoPlayer#1480]
Since version 1.5.0, ExoPlayer supports multi-track.
Is it possible to grab two video track at the same time? One would be drawn to the surface and another doesn't need to be. I just need to get the raw bytes. If so, would they be frame accurately synchronized?

Same question for audio. Is it possible to grab two audio track at the same time? One would be playing but another doesn't need to be. I just need to get the raw bytes. If so, would they be frame accurately synchronized?

**Comment by ojw28** [comment]
It's probably possible to extend ExoPlayer to do this kind of thing, but it's beyond the scope of the library directly and of this issue tracker.

**Comment by djdance** [comment]
why closed? i also need to know, Is it possible to grab two audio track at the same time? 
by default, using new multi-track feature, via 1 ExoPlayer instance?
