### ISSUE TITLE
Can't suppurt flv format to seek

### ISSUE THREAD

**Issue by mandagod** [google/ExoPlayer#1481]
flvxtractor.java

the isSeekAble return false.

**Comment by ojw28** [comment]
If you want to be able to seek, you should use a container format that's better designed for seeking (e.g. MP4). Not supporting seeking in containers that don't make seeking easy, such as FLV, is working as intended. See #860 for a little more detail.

**Comment by mandagod** [comment]
@ojw28  Thanks.
