### ISSUE TITLE
Stretched scaling issue with mp4 video

### ISSUE THREAD

**Issue by gbhall** [google/ExoPlayer#1482]
Referring to this dev branch commit https://github.com/google/ExoPlayer/commit/af611224779a3ba353ff6a1e72469ea178b8a4aa and issue #1428 

The only modifications I've made to the latest dev branch is adding 2 new mp4 samples and updated `ExtractorRendererBuild` to use `MediaCodec.VIDEO_SCALING_MODE_SCALE_TO_FIT_WITH_CROPPING` and changed the `video_frame` in `player_activity.xml` to `FrameLayout`. 

However an mp4 recorded with a Nexus 5 (and LG G3) appears completely vertically stretched. The other test video found online works perfect. 

Here's a screen recording of the issue: https://dl.dropboxusercontent.com/u/49669/device-2016-04-28-165515.mp4

Nexus 5 sample that doesn't work: 
https://dl.dropboxusercontent.com/u/49669/2016-04-28_162150.mp4

Other demo video that _does_ work:
http://www.quirksmode.org/html5/videos/big_buck_bunny.mp4

Any idea what the issue is? Thanks.

**Comment by gbhall** [comment]
Just tried footage from an iPhone 6. Same stretched issue in the demo player. 

Footage: https://dl.dropboxusercontent.com/u/49669/IMG_2823.MOV

**Comment by ojw28** [comment]
These videos include a non-zero rotation (i.e. the video is recorded horizontally, but the video includes metadata indicating that it needs to be rotated to 90 degrees to make it vertical before playback). Unfortunately, it appears there's an issue in the underlying platform when using VIDEO_SCALING_MODE_SCALE_TO_FIT_WITH_CROPPING together with this type of video. I'm not sure there's much we can do to fix it in ExoPlayer. I'll file an issue on the platform team.

**Comment by gbhall** [comment]
@ojw28 Ok no problem. Thanks man.

**Comment by ojw28** [comment]
Internal bug ref: 28512795

**Comment by fabiensanglard** [comment]
Late to the party but the dropbox links are dead. Can you reupload them so I can take a look at the issue ?

**Comment by gbhall** [comment]
@fabiensanglard Haha here you go: 

Screen recording: 
https://www.dropbox.com/s/22ccalte1cznmaq/device-2016-04-28-165515.mp4?dl=0

Sample:
https://www.dropbox.com/s/7hjlprwj5xevuze/2016-04-28_162150.mp4?dl=0

**Comment by olmur** [comment]
Does a workaround exist for this issue? I have the same problem on android 6 (api 23) video is rotated and stretched :(

**Comment by ojw28** [comment]
It appears this was fixed at the platform level in Android 11. For earlier versions of Android, I think the only workaround is to use `TextureView` and handle the transformation yourself.
