### ISSUE TITLE
Best way to get the playing time for MediaController

### ISSUE THREAD

**Issue by opatino** [google/ExoPlayer#1483]
Hi, I've implemented an early version of an RTSP client. I connect to an RTSP server and receive a TS stream. The RTSP client runs on a different thread and finally demoplayer has access to some information from this client.
 The RTSP server gives me information about duration of the program, but I can't get an straight way to put that duration into H264Reader or MpegAudioReader to create the format info including this duration. I think that if this info is provided MediaController would have access to the position.
All my options are going to mess up the current implementation. Can anybody think of a clean way to pass the duration parameter from my client to the Readers?

Thanks!

Oscar

**Comment by ojw28** [comment]
I think this is custom enough to be outside the scope of this issue tracker, sorry.
