### ISSUE TITLE
Response code: 501

### ISSUE THREAD

**Issue by mahich** [google/ExoPlayer#1489]
Hi,
      Can any one tel me why i am getting this error, first time my video is playing properly, but when i try to play second time the same video getting this below error.A
```
04-30 09:33:35.738: E/EventLogger(23412): internalError [0.60, rendererInitError]
04-30 09:33:35.738: E/EventLogger(23412): com.google.android.exoplayer.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 501
04-30 09:33:35.738: E/EventLogger(23412): 	at com.google.android.exoplayer.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:210)
04-30 09:33:35.738: E/EventLogger(23412): 	at com.google.android.exoplayer.upstream.DefaultUriDataSource.open(DefaultUriDataSource.java:135)
04-30 09:33:35.738: E/EventLogger(23412): 	at com.google.android.exoplayer.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:97)
04-30 09:33:35.738: E/EventLogger(23412): 	at com.google.android.exoplayer.upstream.DataSourceInputStream.open(DataSourceInputStream.java:56)
04-30 09:33:35.738: E/EventLogger(23412): 	at com.google.android.exoplayer.upstream.UriLoadable.load(UriLoadable.java:92)
```

**Comment by ojw28** [comment]
That's a server error (http response code 501). See [here](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#5xx_Server_Error). It's something that would most likely need to be rectified on the serving side. I'm not sure why the server only responds in this way for the second playback; that's something whoever is providing the server will have to look at.

**Comment by mahich** [comment]
Hi thank you very much for your reply, I am getting this issue only in fragment class. I mean if i take play button in fragment->onClick play button will display video in activity class(fragment->activity for second time onwards getting 501 exception), If i take play button in activity->onClick play button will display video in activity class(activity->activity videos are working good for all times) Can you please tel me why i am getting this issue for fragment->activity(PlayerActivity) only.
