### ISSUE TITLE
HLS WebVTT chunks

### ISSUE THREAD

**Issue by alvinhkh** [google/ExoPlayer#1494]
I have a hls live stream with subtitle tags. each subtitle m3u8 is a list of webvtt files. each webvtt start at 00:00:00.000, some files are empty when no subtitle at that time frame. 
I tried to use the demo player to load the stream, it can show a few seconds (it should be the first webvtt file), after that it stop showing next subtitles. 
Is this a bug or an unsupported behaviour?  

index.m3u8
> #EXTM3U
#EXT-X-VERSION:4
#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID="textstream",NAME="eng",LANGUAGE="eng",DEFAULT=NO,AUTOSELECT=YES,FORCED=NO,URI="t10000/sub_eng.m3u8"
...

sub_eng.m3u8
> #EXTM3U
#EXT-X-VERSION:4
#EXT-X-TARGETDURATION:9
#EXT-X-MEDIA-SEQUENCE:1460550399
#EXT-X-PROGRAM-DATE-TIME:2016-05-03T15:08:13.000Z
#EXTINF:8.312,
sub_eng_1460550399.webvtt
#EXTINF:6.162,
sub_eng_1460550400.webvtt
#EXTINF:9.641,
sub_eng_1460550401.webvtt
#EXTINF:8.235,
sub_eng_1460550402.webvtt
#EXTINF:8.005,
sub_eng_1460550403.webvtt
...

sub_eng_1460550399.webvtt
> WEBVTT
> X-TIMESTAMP-MAP=MPEGTS:6770154174,LOCAL:00:00:00.000
> 
> 00:00:00.000 --> 00:00:02.870
> ABC
> 
> 
> 00:00:02.963 --> 00:00:05.318
> ABC
>
>
> 00:00:05.428 --> 00:00:07.066
> ABC

sub_eng_1460550402.webvtt

> WEBVTT
> X-TIMESTAMP-MAP=MPEGTS:6772233418,LOCAL:00:00:00.000
> 
> 00:00:00.000 --> 00:00:01.684
> ABC
> 
> 
> 00:00:01.777 --> 00:00:04.741
> ABC

sub_eng_1460550403.webvtt
> WEBVTT
> X-TIMESTAMP-MAP=MPEGTS:6773082892,LOCAL:00:00:00.000
>

**Comment by ojw28** [comment]
It's probably a bug, but we really need a link to a playable sample to be able to efficiently debug the issue.

**Comment by alvinhkh** [comment]
the stream is live and sub_eng.m3u8 keep appending webvtt at the end of the file. 
it keeps around 3 hours of files, when (5) new webvtt added, MEDIA-SEQUENCE and PROGRAM-DATE-TIME will change and (5) webvtt at the top will be deleted.

that stream is not publicly available and maybe regional restricted (Hong Kong). I cant find any other stream yet.

**Comment by ojw28** [comment]
I'm pretty sure it's not the case that WebVTT on live streams is broken in general in ExoPlayer, so we really will need a test stream to take a look at this. We might be able to use a proxy to get around geo-restriction, but either way we definitely need a URL.

**Comment by alvinhkh** [comment]
are there any ways I can send the URL privately, not on this public tracker?

**Comment by ojw28** [comment]
Mail `dev.exoplayer@gmail.com`. Thanks.

**Comment by alvinhkh** [comment]
just a note, I sent out the link.

**Comment by ojw28** [comment]
Thanks for the link! This should be fixed on the dev branch by the change ref'd above.

**Comment by ChernyshovYuriy** [comment]
Dear colleagues,
What is version number for this fix?
I use version 1.5.9 and side load WebVTT text tracks. It works well with simple *.vtt file with appropriate text format inside.
However, it doesn't with *.m3u8 based text track file.
Format of the *.m3u8 file is:

```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:1753
#EXT-X-MEDIA-SEQUENCE:0
#EXTINF:1753.248,
<name_of_the_file_here>.vtt
#EXT-X-ENDLIST
```

Format of the *.vtt file is:

```
WEBVTT
X-TIMESTAMP-MAP=MPEGTS:900000,LOCAL:00:00:10.000

00:00:04.838 --> 00:00:07.707
Oh, the way you crushed Mike at Ping-Pong

00:00:07.707 --> 00:00:09.442
was such a turn-on.

00:00:09.442 --> 00:00:11.444
You want to...?

00:00:11.444 --> 00:00:11.945
You 

*******
```

ExoPlayer fails to parse such text with:

```
Caused by: com.google.android.exoplayer.ParserException: Expected WEBVTT. Got #EXTM3U
                          at com.google.android.exoplayer.text.webvtt.WebvttParserUtil.validateWebvttHeaderLine(WebvttParserUtil.java:41)
                          at com.google.android.exoplayer.text.webvtt.WebvttParser.parse(WebvttParser.java:56)
                          at com.google.android.exoplayer.text.webvtt.WebvttParser.parse(WebvttParser.java:32)
                          at com.google.android.exoplayer.text.SubtitleParserHelper.handleSample(SubtitleParserHelper.java:170)
                          at com.google.android.exoplayer.text.SubtitleParserHelper.handleMessage(SubtitleParserHelper.java:154)
                          at android.os.Handler.dispatchMessage(Handler.java:98)
                          at android.os.Looper.loop(Looper.java:148)
                          at android.os.HandlerThread.run(HandlerThread.java:61)
```

I am building SampleSource implementation as:

```
final MediaFormat mediaFormat = MediaFormat.createTextFormat(
                "id",
                MimeTypes.TEXT_VTT,
                MediaFormat.NO_VALUE,
                C.MATCH_LONGEST_US,
                "eng"
        );
new SingleSampleSource(Uri.parse(<url_here>), textDataSource, mediaFormat);
```

**Comment by ChernyshovYuriy** [comment]
Forget to mention, content has MPEG DASH format.
In general, is there acceptable to have m3u8 text source for a MPEG DASH stream?

**Comment by AquilesCanta** [comment]
@ChernyshovYuriy The issue with your approach is that you are trying to parse a m3u8 with a WebvttParser, therefore the error "Expected WEBVTT. Got #EXT3MU". This is unrelated to this thread. It is not a good idea to use a closed issue either, as it could easiliy get ignored. If you still don't manage to solve this, please open a new issue providing all the information requested in the issue template.

**Comment by ChernyshovYuriy** [comment]
Hi,
Thanks for response.
Yes, I realized that this is purely server side issue.
