### ISSUE TITLE
Video playback halts after EXT-X-DISCONTINUITY tag in live stream 

### ISSUE THREAD

**Issue by Skrewtape** [google/ExoPlayer#1496]
We have the following live stream:

http://edge.theplatform-live-test.top.comcast.net/demo/superflaco/loopstream/loopMaster.m3u8

When we try to play it in ExoPlayer, playback halts when it hits a discontinuity that transitions between a segment containing "LA_loop" and one containing "Free_Clouds".  We're not seeing any errors being thrown.  We're using Exo 1.5.7.

This content plays back properly in other players, such as hls.js, Safari, or AVPlayer.

**Comment by ojw28** [comment]
Please provide a full bug report as requested in the issue template.

**Comment by ojw28** [comment]
Actually, it looks like this is a content issue. Specifically, the absence of `EXT-X-DISCONTINUITY-SEQUENCE` tags in the individual media playlists. These are required for live streams where segments are removed from the media playlists, as per the HLS spec:

> If the server wishes to remove segments from a Media Playlist containing an EXT-X-DISCONTINUITY tag, the Media Playlist MUST contain an EXT-X-DISCONTINUITY-SEQUENCE tag.  Without the EXT-X-DISCONTINUITY-SEQUENCE tag, it can be impossible for a client to locate corresponding segments between Renditions.

Once these are added and your stream is spec compliant, I think you'll find that it works correctly (I was able to validate this by adding some hacks to simulate the tags being present).
