### ISSUE TITLE
Android TV Exoplayer controls

### ISSUE THREAD

**Issue by DavidMarak** [google/ExoPlayer#1498]
I couldn't find any example or tutorial for creating custom controlls for Exoplayer which would be functional on Android TV ( focusable with D-pad). Could someone give me hint how to do it ?
Thanks.
David

**Comment by ojw28** [comment]
The ExoPlayer library does not provide UI components; you need to build those yourself and have them call in to ExoPlayer (e.g. to start/stop playback when your play/pause buttons are pressed).
