### ISSUE TITLE
Playing GoPro live stream

### ISSUE THREAD

**Issue by cob4lt** [google/ExoPlayer#1499]
Hi all,

First of all, I am not a video export so maybe this is not issue at all. I only hope that this posts will help someone else to figure out way to play live stream video from GoPro 4 cameras.

So, first, in my android application, I had Vitamio library for this case, but then, I decided to switch to ExoPlayer because I think it is much better solution than vitamio and it is open source and in constant development stage.
For playing live stream, I used demo application (DemoPlayer class) to help start with something. 
First, I started with ExtractorRendererBuilder and UdpSampleSource (because gopro is transmitting via udp) and then I hit the wall because I was getting SocketTimeoutException.

Then I ffprobe live stream and this is what I 
```
[udp @ 0x7fa1a86016a0] No default whitelist set
[udp @ 0x7fa1a86016a0] end receive buffer size reported is 65536
[mpegts @ 0x7fa1a9002a00] Format mpegts probed with size=2048 and score=97
[mpegts @ 0x7fa1a9002a00] stream=0 stream_type=1b pid=1011 prog_reg_desc=
[mpegts @ 0x7fa1a9002a00] stream=1 stream_type=f pid=1100 prog_reg_desc=
[mpegts @ 0x7fa1a9002a00] stream=2 stream_type=80 pid=200 prog_reg_desc=
[mpegts @ 0x7fa1a9002a00] Before avformat_find_stream_info() pos: 0 bytes read:9296 seeks:0
[mpegts @ 0x7fa1a9002a00] parser not found for codec none, packets or times may be invalid.
[h264 @ 0x7fa1a8804600] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 0x7fa1a8804600] decode_slice_header error
[h264 @ 0x7fa1a8804600] no frame!
[h264 @ 0x7fa1a8804600] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 0x7fa1a8804600] decode_slice_header error
[h264 @ 0x7fa1a8804600] no frame!
[h264 @ 0x7fa1a8804600] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 0x7fa1a8804600] decode_slice_header error
[h264 @ 0x7fa1a8804600] no frame!
[h264 @ 0x7fa1a8804600] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 0x7fa1a8804600] decode_slice_header error
[h264 @ 0x7fa1a8804600] no frame!
[h264 @ 0x7fa1a8804600] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 0x7fa1a8804600] decode_slice_header error
[h264 @ 0x7fa1a8804600] no frame!
[h264 @ 0x7fa1a8804600] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 0x7fa1a8804600] decode_slice_header error
[h264 @ 0x7fa1a8804600] no frame!
[h264 @ 0x7fa1a8804600] Current profile doesn't provide more RBSP data in PPS, skipping
[h264 @ 0x7fa1a8804600] no picture 
[mpegts @ 0x7fa1a9002a00] invalid dts/pts combination 205200
[mpegts @ 0x7fa1a9002a00] invalid dts/pts combination 208800
[mpegts @ 0x7fa1a9002a00] invalid dts/pts combination 212400
[mpegts @ 0x7fa1a9002a00] invalid dts/pts combination 216000
[mpegts @ 0x7fa1a9002a00] invalid dts/pts combination 219600
[mpegts @ 0x7fa1a9002a00] invalid dts/pts combination 223200
[mpegts @ 0x7fa1a9002a00] invalid dts/pts combination 226800
[mpegts @ 0x7fa1a9002a00] Continuity check failed for pid 4113 expected 13 got 11
[h264 @ 0x7fa1a8804600] Current profile doesn't provide more RBSP data in PPS, skipping
[mpegts @ 0x7fa1a9002a00] invalid dts/pts combination 230400
.....
[h264 @ 0x7fa1a8804600] Current profile doesn't provide more RBSP data in PPS, skipping
[mpegts @ 0x7fa1a9002a00] invalid dts/pts combination 662400
[mpegts @ 0x7fa1a9002a00] max_analyze_duration 5000000 reached at 5000000 microseconds st:0
[mpegts @ 0x7fa1a9002a00] Could not find codec parameters for stream 1 (Audio: aac ([15][0][0][0] / 0x000F), 0 channels, fltp): unspecified sample rate
Consider increasing the value for the 'analyzeduration' and 'probesize' options
[mpegts @ 0x7fa1a9002a00] Could not find codec parameters for stream 2 (Unknown: none ([128][0][0][0] / 0x0080)): unknown codec
Consider increasing the value for the 'analyzeduration' and 'probesize' options
[mpegts @ 0x7fa1a9002a00] After avformat_find_stream_info() pos: 561944 bytes read:563072 seeks:0 frames:132
Input #0, mpegts, from 'udp://localhost:8554':
  Duration: N/A, start: 2.000000, bitrate: N/A
  Program 1 
    Stream #0:0[0x1011], 132, 1/90000: Video: h264 (Main), 1 reference frame ([27][0][0][0] / 0x001B), yuvj420p(pc, bt709, left), 320x240 [SAR 1:1 DAR 4:3], 1/50, 25 fps, 25 tbr, 90k tbn, 50 tbc
    Stream #0:1[0x1100], 0, 1/90000: Audio: aac ([15][0][0][0] / 0x000F), 0 channels, fltp
    Stream #0:2[0x200], 0, 1/90000: Unknown: none ([128][0][0][0] / 0x0080)
detected 4 logical cores
Unsupported codec with id 0 for input stream 2
[AVIOContext @ 0x7fa1a840c700] Statistics: 563072 bytes read, 0 seeks
```

And then I saw "mpegts" and test it with HlsRendererBuilder (with udp again), but then, I think HLS and UDP are not going together because I could not connect to IP addres udp://127.0.0.1:8556

Every help would be appreciated, or maybe if you can point me in the right direction, or maybe just to told that I can't do it in ExoPlayer

Thanks,
Frane

**Comment by ojw28** [comment]
As far as I know the UDP protocol used by newer GoPro cameras is proprietary, so I wouldn't expect it to "just work" with ExoPlayer. @ptran-gpfw can probably provide more insight.

**Comment by ptran-gpfw** [comment]
We have a Developer Program that recently launched and you can apply to join to get access to our Toolkits, one of them being our Camera Toolkit for Android that supports live preview: https://developer.gopro.com/info

**Comment by ptran-gpfw** [comment]
Unofficially: you should be able to use information from this reddit thread to get the data from the socket:
https://www.reddit.com/r/gopro/comments/2md8hm/how_to_livestream_from_a_gopro_hero4/

Then you should be able to extend [ExtractorRendererBuilder](https://github.com/google/ExoPlayer/blob/master/demo/src/main/java/com/google/android/exoplayer/demo/player/ExtractorRendererBuilder.java). At [line 65](https://github.com/google/ExoPlayer/blob/master/demo/src/main/java/com/google/android/exoplayer/demo/player/ExtractorRendererBuilder.java#L65), use the `ExtractorSampleSource` constructor that lets you pass an explicit extractor,

    ... = new ExtractorSampleSource(..., new TsExtractor());
