### ISSUE TITLE
Question: Using existing components with multiple instances of Exoplayer

### ISSUE THREAD

**Issue by pantos27** [google/ExoPlayer#1501]
I'm playing audio from MP3 files and I'm using two instances of Exoplayer, one to play and one to hold and prepare the next track for gapless playback.

My question is which of the Exoplayer components can be re-used and static and which needs to be recreated?
Some of the components I'm using:
OkHttpClient
OkHttp3.CacheControl
OkHttpDataSource
ExtractorSampleSource
Mp3Extractor
MetadataTrackRenderer
Id3Parser

Thanks

**Comment by ojw28** [comment]
I'm not sure about OkHttpCilent and OkHttp3.CacheControl, but for everything else you should be creating fresh instances (i.e. they should not be shared between players).

**Comment by pantos27** [comment]
Ok, thanks.

Should I ignore this log message then?
_OMXMaster: A component of name 'OMX.qcom.audio.decoder.aac' already exists, ignoring this one._

**Comment by pantos27** [comment]
oops.
Closed by mistake

**Comment by ojw28** [comment]
Yes, that message can be safely ignored (I'm not really sure why the platform prints that, but oh well!).
