### ISSUE TITLE
How to know when ExoPlayer and all it's resources are released

### ISSUE THREAD

**Issue by cperry-gpsw** [google/ExoPlayer#1503]
We've wrapped DemoPlayer and have written an API so that we can show videos in a ViewPager and provided continuous playback across orientation changes. When a page changes we release the necessary resources (AFAIK) and prepare a new DemoPlayer instance with the next video for playback.

We are having an issue where swiping quickly through the pages across many videos eventually produces a crash stemming from an OOM. 

Here is how we are releasing:

``` java
demoPlayer.blockingClearSurface();

if (mSurface != null) {
    surface.release();
}

demoPlayer.release();
```

Are any of these non-synchronous in any way? That would prevent us from doing proper cleanup before the next prepare because we expect that these calls are synchronous.

**Comment by ojw28** [comment]
`Player.release` has an asynchronous part to it, but it should be fine to release one player and instantiate the next without having to worry about an overlap in resource allocation. The situation may be better in V2 than in V1, so if you're still using V1 that might be relevant. If it's still a problem with V2, please let us know.

Note also that there's no need to release the player and instantiate a new one. You can just re-prepare the existing instance, which would be an easy way to avoid any uncertainty around resources not yet having been released.
