### ISSUE TITLE
java.io.EOFException

### ISSUE THREAD

**Issue by abighai** [google/ExoPlayer#1504]
when I played  hls stream, the app  occurred error, who can give me some helps, thanks!

url:http://hitfmzb.linker.cc:2012/channel1/channel1_64k.m3u8
error:
05-06 10:04:52.885: E/EventLogger(29656): internalError [13.54, loadError]
05-06 10:04:52.885: E/EventLogger(29656): java.io.EOFException
05-06 10:04:52.885: E/EventLogger(29656): 	at com.google.android.exoplayer.extractor.DefaultExtractorInput.readFromDataSource(DefaultExtractorInput.java:248)
05-06 10:04:52.885: E/EventLogger(29656): 	at com.google.android.exoplayer.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:69)
05-06 10:04:52.885: E/EventLogger(29656): 	at com.google.android.exoplayer.extractor.ts.TsExtractor.read(TsExtractor.java:134)
05-06 10:04:52.885: E/EventLogger(29656): 	at com.google.android.exoplayer.hls.HlsExtractorWrapper.read(HlsExtractorWrapper.java:240)
05-06 10:04:52.885: E/EventLogger(29656): 	at com.google.android.exoplayer.hls.TsChunk.load(TsChunk.java:115)
05-06 10:04:52.885: E/EventLogger(29656): 	at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
05-06 10:04:52.885: E/EventLogger(29656): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
05-06 10:04:52.885: E/EventLogger(29656): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
05-06 10:04:52.885: E/EventLogger(29656): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
05-06 10:04:52.885: E/EventLogger(29656): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
05-06 10:04:52.885: E/EventLogger(29656): 	at java.lang.Thread.run(Thread.java:841)

**Comment by andrewlewis** [comment]
The segments appear to be in ADTS format, but we try to use TsExtractor because their file names end `.ts`. The stream plays if I make HlsChunkSource [use AdtsExtractor](https://github.com/google/ExoPlayer/blob/master/library/src/main/java/com/google/android/exoplayer/hls/HlsChunkSource.java#L485). Try changing the segment file extensions from `.ts` to `.aac`.
