### ISSUE TITLE
Response Code Exception in Fragment class

### ISSUE THREAD

**Issue by mahich** [google/ExoPlayer#1505]
Hi ojw28,
     I am getting response code 501 exception  only in fragment class. I mean if i take play button in fragment->onClick play button will display video in activity class(fragment->activity for second time onwards getting 501 exception), If i take play button in activity->onClick play button will display video in activity class(activity->activity videos are working good for all times) Can you please tel me why i am getting this issue for fragment->activity(PlayerActivity) only.

**Comment by ojw28** [comment]
This almost certainly has nothing to do with ExoPlayer. You're getting an http 501 response code from the network stack (under ExoPlayer) only when doing something in particular in your app code (above ExoPlayer). You'll have to investigate this by yourself, unfortunately.
