### ISSUE TITLE
STATE_ENDED not called if the video renderer surface is null.

### ISSUE THREAD

**Issue by spalmerin21** [google/ExoPlayer#1512]
I have this method below to show/hide the surface. 

    public void setDisplay(boolean shouldShow) {
        Surface surface = PlayerFragment.mPreview.getHolder().getSurface();

        if (videoRenderer == null) {
            return;
        }

        if (shouldShow) {
            exoPlayer.sendMessage(
                    videoRenderer, MediaCodecVideoTrackRenderer.MSG_SET_SURFACE, surface);
        } else {
            exoPlayer.blockingSendMessage(
                    videoRenderer, MediaCodecVideoTrackRenderer.MSG_SET_SURFACE, null);
        }
    }

If shouldshow is false, the player continues to receive the STATE_READY, STATE_BUFFERING, and STATE_PREPARING callbacks. Once the player reaches the end however, the STATE_ENDED callback is not called. 

If shouldshow is true, the player receives all of the callbacks including STATE_ENDED.

Is there something else that needs to be set to get the STATE_ENDED callback when the surface is null? I am using a Nexus 6p on Android 6.0.1 with Exoplayer r1.5.7. 

Thanks.

**Comment by spalmerin21** [comment]
I have this method below to show/hide the surface. 

    public void setDisplay(boolean shouldShow) {
        Surface surface = PlayerFragment.mPreview.getHolder().getSurface();

        if (videoRenderer == null) {
            return;
        }

        if (shouldShow) {
            exoPlayer.sendMessage(
                    videoRenderer, MediaCodecVideoTrackRenderer.MSG_SET_SURFACE, surface);
        } else {
            exoPlayer.blockingSendMessage(
                    videoRenderer, MediaCodecVideoTrackRenderer.MSG_SET_SURFACE, null);
        }
    }

If shouldshow is false, the player continues to receive the STATE_READY, STATE_BUFFERING, and STATE_PREPARING callbacks. Once the player reaches the end however, the STATE_ENDED callback is not called. 

If shouldshow is true, the player receives all of the callbacks including STATE_ENDED.

Is there something else that needs to be set to get the STATE_ENDED callback when the surface is null? I am using a Nexus 6p on Android 6.0.1 with Exoplayer r1.5.7. 

Thanks.

**Comment by ojw28** [comment]
Do you need to actually unset the surface, or can you achieve what you're trying to achieve some other way? What's the use case exactly? Will the surface be hidden for a potentially extended period of time?Normally you should disable the video renderer in such cases, rather than leaving it enabled but without a surface.

**Comment by ojw28** [comment]
Let's use #1520 to track this, since it's the same question but the issue contains more information.
