### ISSUE TITLE
Where can I access the chunk being played?

### ISSUE THREAD

**Issue by bayantaani** [google/ExoPlayer#1526]
I am implementing an evaluation module for each chunk after they finish playing. I tried with FormatEvaluator, but I think it evaluates the chunks right after they finish downloading.
The video I am streaming has 150 chunks, but when I print the total number of evaluated chunks, they exceed 150, I guess that's because FormatEvaluator discards some low quality chunks in some cases where the network condition gets better.
Is there a class where I can check the bitrate of each segment being played?

**Comment by ojw28** [comment]
I don't understand what you're trying to do. What does it mean to "access or evaluate a chunk"? What are you actually trying to do specifically? Please provide more detail.

**Comment by bayantaani** [comment]
For each segment being played, I want to obtain its bitrate

**Comment by ojw28** [comment]
When do you need this information? When the chunk starts to load, finishes loading, starts to be played, finishes playing? And why. What are you actually trying to do with this information?

**Comment by bayantaani** [comment]
I am implementing a module that assesses the quality of each chunk played, one of the information needed for this assessment is the bitrate of each chunk. I guess the most appropriate time to get it is when the chunk starts to be played.

**Comment by bayantaani** [comment]
Hello.. I'm sorry if I did not make this clear earlier.
I want to be able to read the bitrates of all chunks played at the time they start to play.
For example, the playback goes like this for a stream of 150 4seconds-long chunks:
| chunk1, time=0 | chunk2, time = 4| chunk3, time = 8| ... | chunk150, time = 596|

After the first chunk loads and begins playback at time=0, I want to read the bitrate of chunk1, and the same goes for the rest of the chunks (after time=4 read bitrate of chunk2.. and so on)

I don't want to read any of the buffered data ahead, only the ones that begin playback.
Thanks in advance.

**Comment by ojw28** [comment]
You can see when the format being played changes by listening for invocations of `onDownstreamFormatChanged` on the `EventListener` that you pass to the `ChunkSampleSource` constructor. Note that this will only be invoked when the format changes, not for every chunk. If this is insufficient for your needs then you'll need to make some modifications directly to the ExoPlayer library to get at what you need.
