### ISSUE TITLE
Force the use of Audio Software Decoder

### ISSUE THREAD

**Issue by jrocharodrigues** [google/ExoPlayer#1528]
I have multiple SmothStreaming content that plays well on exoplayer in multiple devices.
However on a specific device, Gionee Elife E3 (http://www.gsmarena.com/gionee_elife_e3-6085.php) it doesn't work.
I hit play, the player starts buffering, but it never enters the state READY and the playback doesn't start.
I've increased the buffer to a point it loads all the video but it never changes to READY state.
After poking around a bit, i discover if i forced MediaCodecUtil.getDecoderInfo to return OMX.google.aac.decoder instead of OMX.MTK.AUDIO.DECODER.AAC the content plays.

I've tested on other devices that use the same decoder (OMX.MTK.AUDIO.DECODER.AAC) with the same content and it works fine, so i guess the problem is only with this device.

My question is, is there anyway i can force exoplayer to use OMX.google.aac.decoder without having to change exoplayer internal classes?

**Comment by ojw28** [comment]
We blacklist known broken decoders in `MediaCodecUtil.isCodecUsableDecoder`. We should add a case there to blacklist the (device + api-level + codec) combination, which will then solve the issue for all users of the library.

What are the values of `Build.DEVICE`, `Build.MODEL`, `Build.MANUFACTURER` and `Build.VERSION.SDK_INT` for the affected device?

**Comment by jrocharodrigues** [comment]
Hi,
Here are the values you asked:
Build.DEVICE: a70
Build.MODEL: a70
Build.MANUFACTURER: TMN
Build.VERSION.SDK_INT: 17

This device is a Gionee Elife E3, re branded and customized by an Portuguese Mobile Operator.
I don't know if, the not rebranded version, has the same problem but it will probably have different values for those properties.

Until the device/codec is added to the blacklist in `MediaCodecUtil.isCodecUsableDecoder` is there any other way to achieve the same result?

Thanks

**Comment by ojw28** [comment]
Yes, you can implement your own [MediaCodecSelector](https://github.com/google/ExoPlayer/blob/master/library/src/main/java/com/google/android/exoplayer/MediaCodecSelector.java). The default implementation just calls through to `MediaCodecUtil.getDecoderInfo`. You could implement a variant that does the same thing, except in the special case where you want something other than the default behavior. For such cases have your implementation call `MediaCodecUtil.getDecoderInfos` instead, and then iterate through the list until you find a decoder that you're happy to use and return that one.

**Comment by jrocharodrigues** [comment]
Ok thanks for the tip!

Best regards

**Comment by ojw28** [comment]
We've blacklisted the decoder. Please check on the device, since we don't have one on which we can reproduce.

It's quite possible that there are other device names used for variants of this hardware, but since we don't know what they are, we have no good way of expanding the blacklist to cover them at this point in time. Hence marking this issue as fixed.

**Comment by jrocharodrigues** [comment]
Just tested with the DEV branch on the device and it's working.
Thanks
