### ISSUE TITLE
Problem playing PIFF Mp4 (FragmentedMp4Extractor)

### ISSUE THREAD

**Issue by javier-tarazaga** [google/ExoPlayer#1529]
Hi, 

We are experiencing playback issues with a mp4 with PIFF brand. Nothing seems to play. Have been trying to trace the error but when starting to deal with the AtomParser things scape my knowledge. At least from what I could see in my tests is that the track duration it is always set to 0. For some reason the duration is not computed correctly. 

One of the things I tried was hardcoding the track duration in:

```
public static Track parseTrak(Atom.ContainerAtom trak, Atom.LeafAtom mvhd, boolean isQuickTime)
```

This managed to get the audio playing and 1 second or less of the video playing. With the video stream, droppedFrames start to show up in the logs after gets frozen. 

Version:
r1.5.8

This is the stream used:
http://vod-mp4.sfanytime.com/trailers/17000/17347/17347_download_eng_LOW_920.ism/Manifest.ismv

This is the stream info:

```
ffprobe version 3.0.2 Copyright (c) 2007-2016 the FFmpeg developers
  built with llvm-gcc 4.2.1 (LLVM build 2336.11.00)
  configuration: --prefix=/Volumes/Ramdisk/sw --enable-gpl --enable-pthreads --enable-version3 --enable-libspeex --enable-libvpx --disable-decoder=libvpx --enable-libmp3lame --enable-libtheora --enable-libvorbis --enable-libx264 --enable-avfilter --enable-libopencore_amrwb --enable-libopencore_amrnb --enable-filters --enable-libgsm --enable-libvidstab --enable-libx265 --disable-doc --arch=x86_64 --enable-runtime-cpudetect
  libavutil      55. 17.103 / 55. 17.103
  libavcodec     57. 24.102 / 57. 24.102
  libavformat    57. 25.100 / 57. 25.100
  libavdevice    57.  0.101 / 57.  0.101
  libavfilter     6. 31.100 /  6. 31.100
  libswscale      4.  0.100 /  4.  0.100
  libswresample   2.  0.101 /  2.  0.101
  libpostproc    54.  0.100 / 54.  0.100
[file @ 0x7f82b8c0da40] Setting default whitelist 'file,crypto'
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f82b9004600] Format mov,mp4,m4a,3gp,3g2,mj2 probed with size=2048 and score=100
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f82b9004600] ISO: File Type Major Brand: piff
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f82b9004600] Unknown dref type 0x08206c7275 size 12
    Last message repeated 1 times
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f82b9004600] Before avformat_find_stream_info() pos: 13017577 bytes read:3704890 seeks:112
[h264 @ 0x7f82b9019c00] no picture
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f82b9004600] All info found
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f82b9004600] After avformat_find_stream_info() pos: 94052 bytes read:3803194 seeks:113 frames:68
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/Users/javier-tarazaga/Desktop/Manifest.ismv':
  Metadata:
    major_brand     : piff
    minor_version   : 1
    compatible_brands: iso2piff
  Duration: 00:01:52.24, start: 0.000000, bitrate: 927 kb/s
    Stream #0:0(eng), 47, 1/10000000: Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 191 kb/s (default)
    Metadata:
      handler_name    : USP Sound Handler
    Stream #0:1(und), 21, 1/10000000: Video: h264 (Main), 2 reference frames (avc1 / 0x31637661), yuv420p(left), 512x288 [SAR 1:1 DAR 16:9], 1/50, 729 kb/s, 25 fps, 25 tbr, 10000k tbn, 50 tbc (default)
    Metadata:
      handler_name    : USP Video Handler
      encoder         : AVC Coding
detected 8 logical cores
[AVIOContext @ 0x7f82b8c0db20] Statistics: 3803194 bytes read, 113 seeks
```

Any ideas/hints?

Thanks!

**Comment by ojw28** [comment]
I added this sample to the demo app in Samples.java as:

```
new Sample("Test", "http://vod-mp4.sfanytime.com/trailers/17000/17347/17347_download_eng_LOW_920.ism/Manifest.ismv", Util.TYPE_SS)
```

and it plays just fine for me. Are you specifying the correct `TYPE` constant?

**Comment by javier-tarazaga** [comment]
Really!!? Never thought a MP4 with PIFF brand would play using TYPE_SS.

Don't have a device today with me but will check tomorrow first thing in the morning! Also will give it a try with encrypted content to check if everything works correctly as well.

**Comment by ojw28** [comment]
Ah, when using `TYPE_SS` ExoPlayer actually ends up fetching the SmoothStreaming manifest at:
```
http://vod-mp4.sfanytime.com/trailers/17000/17347/17347_download_eng_LOW_920.ism/Manifest
```
which it then plays correctly. It's unclear why you're trying to play the fragmented mp4 directly? Given it lacks a segment index, it's not (efficiently) seekable. The SmoothStreaming manifest adds this information, so it's better to play it that way.

The fragmented mp4 doesn't work when played directly for a couple of reasons.
1. ExoPlayer doesn't parse the `mehd` box, which leads to it determining an incorrect duration for the stream. We can fix this.
1. There aren't any `tfdt` boxes in the stream. Which I believe is normal for `piff`, but isn't something we handle currently. We can probably do so.

Even if we fix the above, we still wont allow seeking in this type of media. So you should really play the SmoothStreaming manifest, rather than the video file directly.

**Comment by ojw28** [comment]
This is fixed in dev. Note that seeking wont work. This is intentional for this type of media, as described above.
