### ISSUE TITLE
Unable to play HLS

### ISSUE THREAD

**Issue by PooriaFarhad** [google/ExoPlayer#1532]
Hello,

We are trying to play HLS m3u8 playlist with different bitrates but by every try we get "No variants selected".
It seems that our source does not get verified by this method:
isSizeSupportedV21(String mimeType, boolean secure, int width,
      int height)  

and also for this method:

// Assume the video is H.264.
      if (format.width * format.height > maxDecodableFrameSize) {
        // Filtering format because it exceeds the maximum decodable frame size.
        return false;
      }

**Comment by ojw28** [comment]
Please file issues that contain all of the information requested in the issue template. Specifically, we need a link to the content and a full bug report taken from the device to investigate this type of issue. Please file a new issue if you're able to provide complete information.
