### ISSUE TITLE
ExoPlayer fails to playback HEVC/AVC hybrid profile HLS v3 contents

### ISSUE THREAD

**Issue by wachiu** [google/ExoPlayer#1533]
Exoplayer version: 1.5.7
Exoplayer works perfectly with AVC only or HEVC only playlists. However, following errors occurs when the playlist contains both AVC and HEVC.
1. Audio stream doesn't work for some streams.
2. message "This device does not provide a decoder for application/id3" appears when HEVC streams are selected.

Does Exoplayer support HEVC/AVC hybrid playlist?

**Comment by ojw28** [comment]
Please file issues that contain all of the information requested in the issue template. Specifically, we need a link to the content and a full bug report taken from the device to investigate this type of issue. Please file a new issue if you're able to provide complete information.
