### ISSUE TITLE
Playback of some HEVC videos is blocky on ExoPlayer 1.5.7

### ISSUE THREAD

**Issue by faiyeah** [google/ExoPlayer#1535]
Environment setup:
Player version: Exoplayer 1.5.7
Android device model: Nexus 10
Android version: 5.1.1
Android security patch level: 2015-12-01
Kernel version: 3.4.67-g0ee50d5
Build Number: LMY48Z

Asset download location:
A. 1250_no_issue.zip (https://www.dropbox.com/s/aw8u3abqsqv7hbt/1250_no_issue.zip?dl=0)
- This (TS) asset has no macroblocks observed during playback (packaged by HLS)

B. 1300_blocky.zip (https://www.dropbox.com/s/te9x62j8sjg3wbo/1300_blocky.zip?dl=0)
- This (TS) asset has macroblocks observed during playback (packaged by HLS)

Observation:
- For Asset B, there are macroblocks observed during playback (which randomly appear around the edge of the display objects)
- We found another stream (Asset A) from another encoders works without playback issue
- For both Asset A and Asset B, no macroblock is observed using latest VLC player on windows to do playback
- Both Asset A and Asset B pass common HEVC validator that no syntatical error and encoding issue was found

Ryan Chan

**Comment by faiyeah** [comment]
Following are the playback screen captures that suffered macroblocks for Asset B:

![exoplayer_1](https://cloud.githubusercontent.com/assets/5735739/15314087/4bbd69a6-1c42-11e6-9e53-ff49e1864656.jpg)
![exoplayer_2](https://cloud.githubusercontent.com/assets/5735739/15314086/4bbced46-1c42-11e6-9c4b-f1559bb7cdae.jpg)

**Comment by andrewlewis** [comment]
The problematic stream seems to use H.265/HEVC Main Profile Level 4. The [CDD](http://static.googleusercontent.com/media/source.android.com/en//compatibility/android-cdd.pdf) states that devices must support up to Main Profile Level 3, and that Android TVs must support up to Main Profile Level 4.1. So it is not safe to rely on non-TV devices being able to play this stream, in general.

The stream plays correctly on Nexus Player and Nvidia Shield, so I thought the distortion might be due to playing a stream with an unsupported profile/level using the software decoder OMX.google.hevc.decoder. However, the CodecCapabilities for that decoder actually include Main Profile Level 4 so this should should be playable.

Separately, we should add capabilities checks for H.265 to reject the stream instead of trying to play it on devices that do not advertise support for this profile/level.

**Comment by faiyeah** [comment]
Hi @andrewlewis,

Well noted for the CCD's recommendation. But this looked weird since my attached two streams are of same encoding profile / level parameters (Main@L4), but only one of them can do the playback without any artifact. I am not sure whether this could be a bug in the HEVC decoder or not. 

Thus, I am creating this issue to keep track of that. Do you have anything that might help you to address the issue. 

Ryan Chan

**Comment by andrewlewis** [comment]
This stream has two PPSs, but we currently only send the first one to the decoder.

**Comment by faiyeah** [comment]
But as far as I know, this is syntax correct. Is this a limitation of the decoder? Is there any plan to support that? We are pretty sure there are many encoder vendors transcode stream with this property.

Many thanks.

Best regards,
Ryan Chan
- sent from my iPhone

**Comment by andrewlewis** [comment]
It's a bug in ExoPlayer that we don't currently send all the parameter sets the decoder. I'm working on a fix. As far as I know, the stream and decoder are fine.

**Comment by faiyeah** [comment]
Thanks for confirming this. We will stay tune for the fix.

Many thanks.

Best regards,
Ryan Chan
- sent from my iPhone

**Comment by ojw28** [comment]
This should be fixed in dev.

**Comment by wachiu** [comment]
Tested the dev branch with the above assets. The HEVC video played is still blocky.

**Comment by andrewlewis** [comment]
@wachiu I just tried playing the stream in 1300_blocky.zip again and couldn't spot any blockiness using the code on the dev branch. Could you describe where/when the video is blocky? Are you playing the same stream? What device/build are you using?

**Comment by wachiu** [comment]
@andrewlewis Yes I was using the same stream for the test. The device I was using is nexus 10. There were some small blocks around the edges of people. Sometimes they scattered over the screen.

**Comment by andrewlewis** [comment]
@wachiu On Nexus 10 running LMY49J I don't see the distortion that was visible before the fix referenced above. There are some subtle blocking artifacts but they look like the distortion introduced by some lossy block-based video compression algorithms, not error concealment in the decoder. What Android build is the device running? Do you see the same distortion when viewing the video using VLC/ffplay/similar?

**Comment by wachiu** [comment]
@andrewlewis My nexus 10 is LMY48Z. I also tried it using VLC and it played the HEVC stream perfectly. Do you think it is the difference in android version that caused the problem?

**Comment by andrewlewis** [comment]
@wachiu Possible but unlikely. Could you first double-check that you can see [this code](https://github.com/google/ExoPlayer/blob/dev/library/src/main/java/com/google/android/exoplayer/extractor/ts/H265Reader.java#L457) on the branch you're using? If so, please send a screenshot of the distortion to dev.exoplayer@gmail.com and I will see if I can see the same thing.

**Comment by wachiu** [comment]
@andrewlewis  switched to dev branch. can find your code in H265Reader.java. Exoplayer can play HEVC in HLS perfectly but not HEVC in DASH. screenshots sent to your email.

**Comment by andrewlewis** [comment]
@wachiu Please could you file a new issue, and include a link to a H.265/HEVC DASH test stream we can use to reproduce the issue? I will rename this issue to indicate that it's specific to HLS. Thanks.
