### ISSUE TITLE
How to play local video？

### ISSUE THREAD

**Issue by iflytek-duan** [google/ExoPlayer#1537]
- For example: 
video address is "/storage/emulated/0/huancun.mp4",URI is "file:///storage/emulated/0/huancun.mp4"
- but an error has occurred,the error message is:
com.google.android.exoplayer.extractor.ExtractorSampleSource$UnrecognizedInputFormatException: None of the available extractors (WebmExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, TsExtractor, FlvExtractor, OggVorbisExtractor, PsExtractor, WavExtractor) could read the stream.
How to fix it？
- thank you for your reply

**Comment by iflytek-duan** [comment]
**如何使用EXOPlayer进行本地视频播放？**
- 例如：本地视频地址为"/storage/emulated/0/huancun.mp4"，转换成URI后为"file:///storage/emulated/0/huancun.mp4"
- 我使用github上的Demo传入文件的URI地址进行本地视频你播放，却发生了异常：
com.google.android.exoplayer.extractor.ExtractorSampleSource$UnrecognizedInputFormatException: None of the available extractors (WebmExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, TsExtractor, FlvExtractor, OggVorbisExtractor, PsExtractor, WavExtractor) could read the stream. 
请问该如何解决呢？
- 谢谢您的回复。

**Comment by NoGirlFriendException** [comment]
哥们 我给你说 你是不是去我简书上发问了？ 我简书上叫 我是一只大金毛
你这个问题 我感觉不是地址传错了
而是选错了RenderBuilder. 
你如果用github上的demo的话 注意1下 是有一个地方设置type的 你看看 是不是 other.
mp4 应该是用 这个ExtractorRendererBuilder

**Comment by iflytek-duan** [comment]
哥们，我错了.... @NoGirlFriendException 事实证明，是我们服务端提供的视频本身就有问题...谢谢

**Comment by iflytek-duan** [comment]
closes #1537

**Comment by iflytek-duan** [comment]
closed #1537
