### ISSUE TITLE
Speed control for playback speed rate like (1x, 2x)

### ISSUE THREAD

**Issue by vinodgct** [google/ExoPlayer#1539]
Hi,
I am currently use exoplayer in my android app to play audio. I want to increase/decrease playback speed like (1.x, 2.x) etc. Can we control speed rate in exoplayer?

Please help.

Thanks & regards,
Vinod

**Comment by AquilesCanta** [comment]
There are quite a few issue threads about this. You can start with [#1216](https://github.com/google/ExoPlayer/issues/1216). There are many ways to do this. If after some research you still don't manage to get what you want, open a new issue with more specific constrains on what you want.

**Comment by yangwuan55** [comment]
@all Please see [here](https://github.com/yangwuan55/ExoPlayer/tree/playbackSpeed) ,I have a implementation of variable speed for exoplayer,support the preversion of 23.

**Comment by paulocoutinhox** [comment]
It was implemented?

**Comment by nzala** [comment]
can we control playback speed in ExoPlayer nw

**Comment by blennerSilva** [comment]
was it implemented yet?

**Comment by nzala** [comment]
@yangwuan55 hw use

**Comment by yangwuan55** [comment]
@nzala [https://github.com/yangwuan55/ExoPlayer/tree/playbackSpeed/demo_speed](url)

**Comment by yiShanXin** [comment]
@yangwuan55  By seekTo () to specify the time to play, getCurrentPosition () gets the time to be incorrect

**Comment by andrewlewis** [comment]
Note: we recently pushed support for playback speed adjustment to `dev-v2`. Please see the recent updates to #26 for more information.
