### ISSUE TITLE
Discontinuity detected error, even with EXT-X-MEDIA-SEQUENCE included in media playlist

### ISSUE THREAD

**Issue by algobunny** [google/ExoPlayer#1541]
Exoplayer freezes when playing ad content on a live stream.
The live stream goes to play an ad, during the very last few seconds it freezes, and is unable to proceed to the next ad or resume live stream. ADB reports discontinuity:
`05-04 15:52:30.271 6364-6512/com.google.android.exoplayer.demo E/AudioTrack: Discontinuity detected [expected 177664000, got 176957334]`

This issue is reproducible in demo app. I have a clean fork that contains streams, which are experiencing this issue: https://github.com/algobunny/ExoPlayer/tree/sample_news
Select News > KCRA 
Check during news times: https://docs.google.com/spreadsheets/d/1L6UE3nK1NhnHNcNNrSVSpCtoK4stiDF9Oqzsnxh8BZs/edit?usp=sharing

The #EXT-X-MEDIA-SEQUENCE flag is present in the media playlists (kcra-(b/c,d,e,f,g).m3u) 

This issue is present since ExoPlayer 1.5.4+
The problem did not occur in 1.5.3, and seems to have been introduced during this commit: https://github.com/google/ExoPlayer/commit/00f8deda3d7b558794986fcc6be47d49ea3a5b2b

Has anyone encountered a similar issue?

**Comment by ojw28** [comment]
As per previous comments on https://github.com/google/ExoPlayer/pull/1521 and the HLS spec, you need to include  EXT-X-DISCONTINUITY-SEQUENCE tags in this type of HLS media playlist. The KCRA media playlists do not contain this tag. This is a HLS spec violation, and is the reason you're observing these issues.

**Comment by biodatacomp** [comment]
@ojw28 Am seeing a similar issue and seem to have the EXT-X-DISCONTINUITY-SEQUENCE in right order in Media Playslists, but I am seeing a similar stalls with Discontinuity detected log in AudioTrack

try testing using:
http://stitcher.pluto.tv:80/stitch/hls/channel/5268abcd0ce20a8472000114/master.m3u8?device_type=android%2CLGE%2Cmobile&device_make=android%2CLGE%2Cmobile&sid=05192016SomeRandom1

**Comment by ojw28** [comment]
Please file a separate issue, since the issue here is very much that the tags are missing.
