### ISSUE TITLE
Compiling exoplayer together with gson

### ISSUE THREAD

**Issue by michaelgohl** [google/ExoPlayer#1543]
My gradle file looks like
`compile 'com.google.code.gson:gson:2.4'
 compile 'io.gresse.hugo.vumeterlibrary:vumeterlibrary:1.0.14'
 compile 'com.android.support:appcompat-v7:23.2.1'
 compile 'com.google.android.exoplayer:exoplayer:r1.5.8'`

Gradle sync works but executing tasks: [:App:assembleDebug] fails with:

Error:Execution failed for task ':App:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.7.0_79\bin\java.exe'' finished with non-zero exit value 2

When I remove 'com.google.code.gson:gson:2.4' that task execution works.

**Comment by ojw28** [comment]
This doesn't sound like an ExoPlayer issue...
