### ISSUE TITLE
Honour EXT-X-START:TIME-OFFSET tag in HLS level event playlist

### ISSUE THREAD

**Issue by will-work** [google/ExoPlayer#1544]
After requesting an event playlist that contains the following tags:

```
#EXT-X-PLAYLIST-TYPE:EVENT
#EXT-X-START:TIME-OFFSET=0

```

ExoPlayer starts requesting segments from the end of the playlist, rather than from the beginning.  

Example:

```
#EXTM3U
#EXT-X-TARGETDURATION:11
#EXT-X-VERSION:3
#EXT-X-PLAYLIST-TYPE:EVENT
#EXT-X-START:TIME-OFFSET=0
#EXTINF:11,
http://abc.com/segments/channel1/2277.ts
#EXTINF:11,
http://abc.com/segments/channel1/2278.ts
...
#EXTINF:11,
http://abc.com/segments/channel1/3244.ts
#EXTINF:11,
http://abc.com/segments/channel1/3245.ts
#EXTINF:11,
http://abc.com/segments/channel1/3246.ts

```

will cause the player to request segment 3244, then 3245 etc. 
- ExoPlayer version: 1.5.8.
- tested on Samsung S4 GT-I9295, Android 5.0.1
- reproducible on each test

**Comment by Ambroos** [comment]
@AquilesCanta Any news on this?

**Comment by AquilesCanta** [comment]
Not yet, we are working to have live seeking finished first. Sorry for the delay.

**Comment by ojw28** [comment]
This is fixed by the change ref'd above.
