### ISSUE TITLE
IndexOutOfBoundsException in HlsChunkSource.selectTrack() when no tracks available to play

### ISSUE THREAD

**Issue by brabeler** [google/ExoPlayer#1545]
In HlsChunkSource.selectTrack(), an IndexOutOfBoundsException will occur when tracks.get(selectedTrackIndex) is executed if selectedTrackIndex exceeds the length of the tracks array.

This will occur in a situation where the length of the tracks array is zero due to the video format selector determining that all the variants in the manifest file are not suitable for playback for various reasons.  If this happens, HlsChunkSource.prepare() will still blindly call selectTrack(0), which then causes the exception, IndexOutOfBoundsException.

I am using ExoPlayer 1.5.7.

I found this bug when trying to play an HLS stream on a Samsung Galaxy Note 4 with a qualcomm hevc decoder (OMX.qcom.video.decoder.hevc).  The device reports that the maximum video dimensions for hevc playback are 544x544, which obviously eliminates all the variants from playback consideration.  These maximum dimensions are wrong, but that seems to be a problem with the platform and not ExoPlayer.

I think some code should be added to HlsChunkSource.prepare() to not call selectTrack(0) if getTrackCount() == 0 and instead gracefully notify the upper layers that playback is not possible.

**Comment by ojw28** [comment]
To clarify, this doesn't actually cause the process to crash. Playback fails in a controlled way and the player's listener is invoked with the exception. Is that correct?

If so, then is the complaint here that the exception isn't useful (e.g. you'd prefer something like a `NoSupportedVariantsException` or similar)? This is something we'll be handling more gracefully in V2. It seems non-urgent to fix it in V1.

**Comment by brabeler** [comment]
Correct, the process does not crash and the onPlayerError() is invoked with the exception.  Yes, I think the issue is that the exception is not useful at all.  I'll do a quick fix on my end and wait for the real fix in V2.  Thanks.

**Comment by ojw28** [comment]
I think this is fixed in V2. Please let us know if this is not the case.
