### ISSUE TITLE
demo in MISC-> Dizzy download times will play repeatedly

### ISSUE THREAD

**Issue by a316789966** [google/ExoPlayer#1547]
I just opened the demo, and then start playing MISC-> Dizzy, and I opened the fiddler to track network, I found dizzy.mp4 will be repeated many times to download to start playing, if network conditions are not good, even up to 7 times the above

see log：
https://github.com/a316789966/img

**Comment by ojw28** [comment]
I'm not exactly sure what you're trying to say. The log shows the connection repeatedly failing (as you say, the network is bad). The player is retrying in an attempt to make the connection successfully. This is working as intended.

Please clarify exactly what behavior you're seeing *and* what you expect the behavior to be and how the two differ. Thanks!

**Comment by a316789966** [comment]
The player will request network access repeatedly when the network is not good. While asking for the next time, the previous requests are still downloading, which will cause more network traffic consumption .For example, it consumes 20M and even more network traffic when watching a 2M video. What’s worse, the bandwidth is being sucked down by the previous download request, which will cause playback failure easily. Moreover, even though we exit the app entirely, it will continue downloading if the download request is not yet completely finished. If the video is too big, it’s impossible to play successfully. Please check the video 1.
video1  http://v.youku.com/v_show/id_XMTU4MTY5ODc3Mg==.html

When the network is good, the player won’t play until it downloads the video twice completely. If we click the rewind button, the video will be completely downloaded once. If we drag the progress bar, the video will be completely downloaded 40 times or even more. My video adopted   AutoResponder function of fiddler to replace the online video with the local video, which is used to simulate the condition when the network is quite good. Please check the video 2.
log2 https://github.com/a316789966/img/blob/master/log2.txt
video2 http://v.youku.com/v_show/id_XMTU4MTY5ODc1Ng==.html

We are producing a player that can  play the video such as ：http://html5demos.com/assets/dizzy.mp4
1 This player can download while playing, instead of playing after completely downloading.
2 This player doesn’t need to consume too much network traffic.
It seems that mediaplayer can realize playing the courseware on net, but mediaplayer is not that useful.

**Comment by ojw28** [comment]
There was a comment posted here that seems to have disappeared. Was that deliberate?

**Comment by ojw28** [comment]
I'm not sure it's accurate that there are multiple requests in flight at once. We always cancel the previous request before we start another one. Are you sure this is the case? How exactly are you verifying that there are multiple requests in flight, and that the previous one has not been canceled prior to completion?

**Comment by ojw28** [comment]
It's also not accurate to state that the entire video has to finish downloading before playback starts. I observe playback starting whilst the download is still in progress for the dizzy sample.

**Comment by a316789966** [comment]
I have checked the network carefully. It turns out that the debugging software fiddler has a problem as a proxy server. The software will download all the requests completely even though its caller has quit, then it occupies the new request‘s bandwidth so that the player can’t play. After I replace it with network without proxy, it can play normally.
I have no idea if all the proxy servers have this problem. You may watch the following two videos I recorded to see the details about this problem.
http://v.youku.com/v_show/id_XMTU4MTY5ODc3Mg==.html     and
http://v.youku.com/v_show/id_XMTU4MTY5ODc1Ng==.html
Thanks for your patience.

**Comment by ojw28** [comment]
Thanks for the update. I haven't used it recently, but in the past I found that using [Stetho](https://code.facebook.com/posts/393927910787513/stetho-a-new-debugging-platform-for-android/) with ExoPlayer's OkHttp extension was a pretty good way of analyzing network requests.
