### ISSUE TITLE
Eia-608 repeatableControl logic causes issues

### ISSUE THREAD

**Issue by daynesh** [google/ExoPlayer#1550]
This line [here](https://github.com/google/ExoPlayer/blob/r1.5.8/library/src/main/java/com/google/android/exoplayer/text/eia608/Eia608TrackRenderer.java#L216) prevents the rendering of CC when ClosedCaptionText objects are followed by two consecutive `END_OF_CAPTION` control commands.

When two `END_OF_CAPTION` commands are processed, both the `captionStringBuilder` as well as the `caption` class members are cleared thereby causing this Track Renderer from rendering a caption at all.

Without knowing much about why the `captionBufferSize == 1` condition was introduced to begin with, removing this check seems to fix the issue for this scenario.  Therefore, code should read (culprit code segment is commented out here):

``` java
ClosedCaptionCtrl captionCtrl = (ClosedCaptionCtrl) caption;
        isRepeatableControl = /*captionBufferSize == 1 &&*/ captionCtrl.isRepeatable();
        if (isRepeatableControl && repeatableControl != null
            && repeatableControl.cc1 == captionCtrl.cc1
```

I presume the reason why this fixes my issue is because when the first `END_OF_CAPTION` command is processed, whatever is stored in `captionStringBuilder` gets stored in `caption` instead and then `captionStringBuilder` is subsequently cleared.  However, for the second `END_OF_CAPTION` command, the `caption` is set to the currently defined `captionStringBuilder` which in this case is an empty string resulting in no captions being rendered.

Please shed some light on this as well as share your opinions on my fix.

Thanks!

**Comment by ojw28** [comment]
I think @marcbaechinger wrote that particular block of code. @cdrolle is also looking at EIA-608 in general.

**Comment by ojw28** [comment]
We've made some recent changes in `dev-v2` around 608 handling. Marking as obsolete, assumed fixed. There aren't any reproduction steps for us to verify.
