### ISSUE TITLE
Exoplayer error list

### ISSUE THREAD

**Issue by replystreaming** [google/ExoPlayer#1552]
Hi,
We would like to know if there is a list of errors that the Exoplayer generates and passes to the client during streaming. IF yes would it be possible to get the full list and for each one some additional info in order to understand when they can happen?

**Comment by ojw28** [comment]
The injectable/extensible nature of ExoPlayer and the dependencies it has on the Android platform mean that it's not feasible to provide a single authoritative list of all errors.

Each exception class should be documented sufficiently well for you to understand what that error is, however. If you're aware of specific exceptions that are being thrown where there's insufficient information to help you understand when they can happen, and in the unlikely event that the exception stack trace doesn't help you to resolve your uncertainty, then please let us know.
