### ISSUE TITLE
Live multi-audio HLS audio out-of-sync with video when the audio track is switched

### ISSUE THREAD

**Issue by moacir69** [google/ExoPlayer#1553]
With live multi-audio HLS streams where audio and video data use different sequence numbers, audio gets out-of-sync with video whenever the audio track is switched and it never recovers. Video also freezes for a while soon after the audio track switch.
This can be synchronized using the first processed sequence number as reference.

**Comment by AquilesCanta** [comment]
Please open a new issue including all the requested items in the issue template. Namely, a way to reproduce the issue ourselves.
