### ISSUE TITLE
How often exoplayer will refresh the manifest file

### ISSUE THREAD

**Issue by randeeppr** [google/ExoPlayer#1555]
Hi,
We have this following manifest file. Send to email to dev.exoplayer with issue id as subject.

In the server, only once i can see exoplayer requesting for the manifest file. After that I can see only chunks are requested. I have given max age for *.mpd as 5s too.

Also, if we dont specify max age in http headers, will exoplayer use the UTC time specified in the manifest file?
```
 <UTCTiming schemeIdUri="urn:mpeg:dash:utc:direct:2012" value="2016-05-26T11:37:23.586Z" />
```
We are getting BehindLiveWindow exception. So we are checking what can be the issue.

Also how many chunks can be downloaded using this manifest? I couldn't make out and I can see player is playing it ~30 minutes then it freezes with BehindLiveWindowException. 

Regards,
Randeep

**Comment by ojw28** [comment]
minimumUpdatePeriod in the manifest is set to 42 years, which indicates to the player that it doesn't need to refresh it. The way the manifest is setup, that's probably correct. SegmentTemplate is used, which means the player doesn't need to update the manifest to work out the location of segments as they come available. The UTCTiming element allows the player to synchronize its clock (approximately) with that of the server's.

So, I can't see anything obviously wrong. We'd need a working test stream to provide further assistance.
