### ISSUE TITLE
[HLS] Closed caption display error on certain streams

### ISSUE THREAD

**Issue by perchrh** [google/ExoPlayer#156]
Tested on ExoPlayer dev-hls HEAD (faf196a581520f1f3164388bb25a68c90446c897).

The two streams mentioned below have an issue where closed captions are unreadable. 
Only two or three characters are displayed at a time, instead of the expected sentences. 

http://now.video.nfl.com/i/captiontest/closedcaptiontest_,350k,550k,.mp4.csmil/master.m3u8 (plays OK in Quicktime)
http://playertest.longtailvideo.com/adaptive/captions/playlist.m3u8 (no captions displayed by Quicktime)

**Comment by andudo** [comment]
@perchrh, please take a look at our fix, closed captions in your stream example should be displayed well now.

**Comment by nettverkfordyrsfrihet** [comment]
It looks good for the first example. The second example has characters appearing out of sequence, attaching screenshot showing the bad behavior. 
![screenshot_2015-01-21-23-15-45](https://cloud.githubusercontent.com/assets/6569353/5846519/7f6bf118-a1c4-11e4-8875-6946bc97dbf7.png)

Note that I've not been able to verify the second example in another player, as I don't have a player that displays ID3 metadata. The stream may not be well formed, for all I know.

**Comment by perchrh** [comment]
It looks good for the first example. The second example has characters appearing out of sequence, attaching screenshot showing the bad behavior. 
![screenshot_2015-01-21-23-15-45](https://cloud.githubusercontent.com/assets/6569353/5846519/7f6bf118-a1c4-11e4-8875-6946bc97dbf7.png)

Both streams play OK in latest VLC, there is no problem with out of sequence characters.

**Comment by andudo** [comment]
Thanks @perchrh. This is fixed now.
I notice that your example has two separate captions (type 0 and type 1) that are getting mixed together. The first one is the actual captions and the second one is just the phrase "CNN Situation Room" that appears from time to time. Do you know whats the purpose of having two and how it's expected to be displayed? VLC doesn't display the second one at all, which is what our fix does as well.

**Comment by perchrh** [comment]
@andudo Great! They are intended to be displayed at different areas of the screen, I guess. Maybe they flash "CNN Situation Room" on top of screen during commercials every now and then to tell the viewer what  program is on at this time.
