### ISSUE TITLE
How to implement Widevine protected DASH in ExoPlayer?

### ISSUE THREAD

**Issue by kunalbhatia** [google/ExoPlayer#1560]
I'm trying to implement below url with key on exoplayer sample code, but as I'm new to mpd url, I don't know how to? please can you help me out.

> Url: http://content.hungama.com/movie/video multi drm content/mpd/FF-2013-00000478/stream.mpd
> Widevine Key: http://wv.service.expressplay.com/hms/wv/rights/?ExpressPlayToken=AQAAAA9JKRcAAABQozUhB9oH71Otlp3ON5chSS0kirwRuEkbzKNFoJSJrX1qfYgEQvUXLZzdG38DW19Goaz-Q5CaZka45_ondnGPXOG-n3mHZkJg845G1Wgf6xz2bXYk1KrJrAwIgL6IzcY0TArENw

What is **video id** and **provider** from the above url?

When I try this url it gives me below error:

> 05-30 17:47:57.576 28110-28110/com.andromeda.kunalbhatia.demo.hungamaplayer I/ExoPlayerImpl: Init 1.5.8
>     05-30 17:47:57.591 28110-28165/com.andromeda.kunalbhatia.demo.hungamaplayer D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
>     [ 05-30 17:47:57.597 28110:28110 D/         ]
>     HostConnection::get() New Host Connection established 0xaa3c7090, tid 28110
>     [ 05-30 17:47:57.637 28110:28165 D/         ]
>     HostConnection::get() New Host Connection established 0xaa3c72a0, tid 28165
>     05-30 17:47:57.642 28110-28165/com.andromeda.kunalbhatia.demo.hungamaplayer I/OpenGLRenderer: Initialized EGL, version 1.4
>     05-30 17:47:57.742 28110-28110/com.andromeda.kunalbhatia.demo.hungamaplayer W/PathParser: Points are too far apart 4.007008481470478
>     05-30 17:47:57.742 28110-28110/com.andromeda.kunalbhatia.demo.hungamaplayer W/PathParser: Points are too far apart 4.011307673966016
>     05-30 17:47:58.174 28110-28110/com.andromeda.kunalbhatia.demo.hungamaplayer D/HungamaVideoPlayer: onRenderers
>     05-30 17:47:58.175 28110-28110/com.andromeda.kunalbhatia.demo.hungamaplayer D/HungamaVideoPlayer: preparing
>     05-30 17:47:58.177 28110-28110/com.andromeda.kunalbhatia.demo.hungamaplayer D/HungamaVideoPlayer: requestfocus
>     05-30 17:47:58.291 28110-28163/com.andromeda.kunalbhatia.demo.hungamaplayer W/VideoCapabilities: Unrecognized profile/level 0/0 for video/mpeg2
>     05-30 17:47:58.291 28110-28163/com.andromeda.kunalbhatia.demo.hungamaplayer W/VideoCapabilities: Unrecognized profile/level 0/2 for video/mpeg2
>     05-30 17:47:58.291 28110-28163/com.andromeda.kunalbhatia.demo.hungamaplayer W/VideoCapabilities: Unrecognized profile/level 0/3 for video/mpeg2
>     05-30 17:47:58.310 28110-28163/com.andromeda.kunalbhatia.demo.hungamaplayer I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
>     05-30 17:47:58.752 28110-28191/com.andromeda.kunalbhatia.demo.hungamaplayer I/OMXClient: Using client-side OMX mux.
>     05-30 17:47:58.754 28110-28191/com.andromeda.kunalbhatia.demo.hungamaplayer D/SoftAVCDec: Number of CPU cores: 2
>     05-30 17:47:58.777 28110-28190/com.andromeda.kunalbhatia.demo.hungamaplayer I/MediaCodec: [OMX.google.h264.decoder] setting surface generation to 28784641
>     05-30 17:47:58.778 28110-28191/com.andromeda.kunalbhatia.demo.hungamaplayer W/OMXNodeInstance: [1:google.h264.decoder] component does not support metadata mode; using fallback
>     05-30 17:47:58.778 28110-28191/com.andromeda.kunalbhatia.demo.hungamaplayer E/ACodec: [OMX.google.h264.decoder] storeMetaDataInBuffers failed w/ err -1010
>     05-30 17:47:58.778 28110-28191/com.andromeda.kunalbhatia.demo.hungamaplayer D/SoftAVCDec: Number of CPU cores: 2
>     05-30 17:47:58.779 28110-28191/com.andromeda.kunalbhatia.demo.hungamaplayer D/SoftAVCDec: Number of CPU cores: 2
>     05-30 17:47:58.802 28110-28196/com.andromeda.kunalbhatia.demo.hungamaplayer I/OMXClient: Using client-side OMX mux.
>     05-30 17:47:58.845 28110-28197/com.andromeda.kunalbhatia.demo.hungamaplayer I/SoftAAC2: limiting to stereo output
>     05-30 17:48:02.983 28110-28163/com.andromeda.kunalbhatia.demo.hungamaplayer E/ExoPlayerImplInternal: Internal track renderer error.
>     com.google.android.exoplayer.ExoPlaybackException: java.io.FileNotFoundException: https://proxy.uat.widevine.com/proxy?video_id=BigBunny&provider=
>         at com.google.android.exoplayer.MediaCodecTrackRenderer.shouldWaitForKeys(MediaCodecTrackRenderer.java:739)
>         at com.google.android.exoplayer.MediaCodecTrackRenderer.feedInputBuffer(MediaCodecTrackRenderer.java:670)
>         at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:513)
>         at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:129)
>         at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:434)
>         at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
>         at android.os.Handler.dispatchMessage(Handler.java:98)
>         at android.os.Looper.loop(Looper.java:148)
>         at android.os.HandlerThread.run(HandlerThread.java:61)
>         at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
>     Caused by: java.io.FileNotFoundException: https://proxy.uat.widevine.com/proxy?video_id=BigBunny&provider=
>         at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:238)
>         at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
>         at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java)
>         at com.google.android.exoplayer.util.Util.executePost(Util.java:759)
>         at com.andromeda.kunalbhatia.demo.hungamaplayer.HpLib_WidevineTestMediaDrmCallback.executeKeyRequest(HpLib_WidevineTestMediaDrmCallback.java:43)
>         at com.google.android.exoplayer.drm.StreamingDrmSessionManager$PostRequestHandler.handleMessage(StreamingDrmSessionManager.java:505)
>         at android.os.Handler.dispatchMessage(Handler.java:102)
>         at android.os.Looper.loop(Looper.java:148)
>         at android.os.HandlerThread.run(HandlerThread.java:61)

also let me know, if you require some more information.

**Comment by wvpaf** [comment]
kunalbhatia : can you provide the source of the URL's you are trying to play?  It seems that these may not be valid.

**Comment by kunalbhatia** [comment]
Hello @wvpaf , 
Below url is valid for next month, you can play the content on Google's Shaka player, below is the link for shaka player demo

See configuration on shaka player demo page [http://imgur.com/jcgViPI](url)

Shaka Player demo
> http://shaka-player-demo.appspot.com/demo/

> 

 DRM Content
> DRM Content URL: http://content.hungama.com/movie/video multi drm content/mpd/FF-2015-00000821/stream.mpd
> License Acquisition URL: http://wv.service.expressplay.com/hms/wv/rights/?ExpressPlayToken=AQAAAA9JKXUAAABQpmDhJoJ28mladdt6yLOM4lDNF-iNTtju2sg1hORxCWPeFxwsHBzbKXfEAWCp37i7IdwfGDXoG2IS5etnDs8ksKGnR_4Tw9j4yA-IyDeHADkCmEj-oSWeIPE1WTJnu9ypU3-SCw

**Comment by pgrov** [comment]
The link to the mpd has spaces in the URL "....video multi drm content...".  Can you please update the link so there are no spaces?

**Comment by wvpaf** [comment]
Hi @kaunalbhatia, Can you do as @pgrov asked? Thanks.

**Comment by kunalbhatia** [comment]
@wvpaf, I've asked my team members to generate one, I'll comment soon.

**Comment by wvpaf** [comment]
@kunalbhatia  Any update?

**Comment by kunalbhatia** [comment]
Hi @wvpaf, unfortunately I'm unable to get a dash URL without spaces, the content team is taking too much time in responding. I don't have rights to do so, otherwise this wouldn't have taking this much time.

**Comment by peddisri** [comment]
@kunalbhatia  Firstly, you need to modify the WidevineTestMediaDrmCallback.java such that you override the url with your License acquisition URL  here https://github.com/google/ExoPlayer/blob/release-v1/demo/src/main/java/com/google/android/exoplayer/demo/WidevineTestMediaDrmCallback.java#L57 

Can you please update this issue with a new URL (without spaces ) as requested by Google engineers here.?

**Comment by kunalbhatia** [comment]
@wvpaf, @peddisri, @pgrov

Following is the url, without spaces. You can test this link on [shaka player](https://shaka-player-demo.appspot.com/demo/), it works fine, also when i tested on exoplayer, it shows total minutes, but video doesn't play.

it shows this error: com.google.android.exoplayer.ExoPlaybackException: java.io.FileNotFoundException: https://proxy.uat.widevine.com/proxy?video_id=Tears&provider=

Working link below:
MPD: https://85-content.hungama.com/1218/4/FF-2014-00000642/stream.mpd
LA: https://wv.service.expressplay.com/hms/wv/rights/?ExpressPlayToken=AQAAAA9JKcEAAABQ0TzVN8BfBuuemyNm4uZLHlZXme0x1Qaqf6lbUm-Bk52mztzfC8HLtA_tzihZC7sYxd5jythYWzGgJ7Hgg1S-YYah-olULq-3IJnIJhJhZfo0O0Wm1dcC3pUlWgC3D-SUJX0XmQ

**Comment by peddisri** [comment]
In WidevineMediaDrmCallback.java file  executeKeyRequest function, modify the executePost as follows

Map<String,String> headers = new HashMap<>(1);
headers.put("Content-Type", "application/octet-stream");
return Util.executePost(url, request.getData(), headers);

With this the content works. Somehow, the Expressplay server mandates the content-type HTTP header.

**Comment by jefftinker** [comment]
Your update seems to confirm that your expressplay server requires the application/octet-stream content type so the issue can be closed. Is that correct or are there any further questions?

**Comment by ojw28** [comment]
It's possible the server simply requires the Content-Type header to be set to something (but doesn't really care what) for POST requests. We've seen the same requirement for sending POST requests on the client side when using the Cronet network stack. For this reason, we've actually just made a change in ExoPlayer V2 that sets Content-Type to application/octet-stream by default for Widevine provisioning/key requests. This change will be pushed to GitHub soon.

@jefftinker - Is application/octet-stream that be the most correct value for Content-Type, given we need to set it to something, or is there a more suitable value?

**Comment by jefftinker** [comment]
For provisioning requests the Content-Type should be application/json.

**Comment by ojw28** [comment]
I actually concluded that Content-Type shouldn't be set for provisioning requests, since a provisioning request doesn't have a body. We do now set Content-Type for key requests to `application/octet-stream`, which fixes this issue. 

Closing. If Content-Type really should be set to application/json for provisioning requests, even though they don't have bodies, please let me know. Thanks!
