### ISSUE TITLE
time resolution issue in MediaCodecVideoTrackRenderer.java

### ISSUE THREAD

**Issue by xijie76** [google/ExoPlayer#1563]
In function
protected boolean processOutputBuffer(long positionUs, long elapsedRealtimeUs, MediaCodec codec, ByteBuffer buffer, MediaCodec.BufferInfo bufferInfo, int bufferIndex, boolean shouldSkip) {
...
long elapsedSinceStartOfLoopUs = (SystemClock.elapsedRealtime() * 1000) - elapsedRealtimeUs;
...
}
the time got from SystemClock.elapsedRealtime() is in milisecond and elapsedRealtimeUs is also got by calling SystemClock.elapsedRealtime(). So it cannot get correct elapsedSinceStartOfLoopUs in microsecond resolution.
I think the correct code should be:
long elapsedSinceStartOfLoopUs = (SystemClock.elapsedRealtimeNanos() / 1000) - elapsedRealtimeUs;
(And elapsedRealtimeUs should also be got by calling SystemClock.elapsedRealtimeNanos())

The code can be found in both 1.4.2 and 1.5.8 (I found it on 1.4.2)

**Comment by ojw28** [comment]
We don't need sub-millisecond granularity, so this is not an issue. Microseconds are used as the unit only for consistency.

**Comment by xijie76** [comment]
I think at least this is a improvement to make the timestamp calculation more precious, right?
In my debug, I saw sometimes that the actual elapsedSinceStartOfLoopUs is only ~100 microseconds but in milisecond resoultion it jumps to 1milisecond.

**Comment by ojw28** [comment]
There's no benefit in making the calculation more accurate just for the sake of it. Once you're below the level at which the most discernible human can perceive a difference, there's nothing to be gained from going further.
