### ISSUE TITLE
IllegalArgumentException in extractor.mp4.AtomParsers.parseStbl when playing a video

### ISSUE THREAD

**Issue by fujunwei** [google/ExoPlayer#1567]
Most of video source is played finely except http://122.96.25.242:8088/trafficserver/386.mp4.

The detail crashed log can get from https://github.com/google/ExoPlayer/issues/1559#event-678256854.

**Comment by AquilesCanta** [comment]
A proper fix for this will be available in the next push. If you need it urgently, you can safely remove the failing assertion.

**Comment by fujunwei** [comment]
Thanks so much, it works finely now.
