### ISSUE TITLE
[DEV] Playback of HEVC/H.265 in DASH is blocky

### ISSUE THREAD

**Issue by wachiu** [google/ExoPlayer#1568]
Device used: Nexus 10
Build Number: LMY48Z
Exoplayer version: 1.5.8 dev branch

Exoplayer can't play HEVC in DASH perfectly. There are blocks scattered over the screen while playing. The stream files caused the issue is sent to dev.exoplayer@gmail.com

**Comment by andrewlewis** [comment]
I think the provided bitstream is probably invalid. The initialization segment contains a PPS with id 0, which we use to configure the codec, but some slices in the sample data appear to refer to a picture parameter set with id 1. I did not find any in-band PPSs near the start of the sample data.

Also, avplay/libav outputs errors about a missing parameter set with id 1 when playing the stream, though its decoder's error concealment seems to hide the errors well and the output looks okay.

Please could you check that the bitstream is valid?

**Comment by wachiu** [comment]
Double-checked. It is the problem of video files.
