### ISSUE TITLE
Support of DASH amendments?

### ISSUE THREAD

**Issue by arianaa30** [google/ExoPlayer#1569]
I want to play around with ExoPlayer as it supports MPEG-DASH. Is it updated with the latest DASH features? Does ExoPlayer support DASH's amendments such as the [Spatial Relation Description (SRD)](http://mpeg.chiariglione.org/standards/mpeg-dash/media-presentation-description-and-segment-formats/text-isoiec-23009-12014-dam-2) feature for tiled videos?

**Comment by ojw28** [comment]
We do not support SRD, and have no plans to do so at the moment.

**Comment by ojw28** [comment]
As for features more generally, the DASH spec is so broad I doubt there exists a player that "implements everything". In particular full multi-period support is missing from many players (ExoPlayer currently provides support only if the available representations are unchanged across periods, although will provide full support in 2.x). I suspect there's a really long tail of obscure DASH features that barely any players support.

**Comment by arianaa30** [comment]
Oh, that's bad. I wish at least SRD was supported. Do you know if there is any other player in Android that can support it? I need it for my PhD experiments.

**Comment by ojw28** [comment]
I'm not aware of any (which isn't the same as saying one doesn't exist). It feels like quite a niche feature; so it seems doubtful that a player would have prioritised implementing it.

**Comment by arianaa30** [comment]
Can we change the code and implement the SRD feature ourselves? Is the code high-level enough to allow developers to modify its DASH logic and add feature and stuff?

**Comment by ojw28** [comment]
This is something you'll have to figure out and answer for yourself; it's not something we'll be spending any time on ourselves. The code is all open source and there for you to look at!

**Comment by SrujithPoondla** [comment]
@arianaa30  were you able to implement SRD feature?
