### ISSUE TITLE
Get Bitrate in HLS streaming

### ISSUE THREAD

**Issue by abhirav** [google/ExoPlayer#1570]
I am trying to get Bitrate information for HLS streaming. I found below method:

@Override
    public void onBandwidthSample(int elapsedMs, long bytes, long bitrateEstimate) {
        Log.e(TAG, "bandwidth [" + getSessionTimeString() + ", " + bytes + ", "
                + getTimeString(elapsedMs) + ", " + bitrateEstimate + "]");
    }

It gets called for DASH and others, but not for HLS. 
Could anyone help me in calculating Bitrate out of HLS videos?

Thanks.

**Comment by indieboyalex** [comment]
In onLoadCompleted() I do the following

```
      if (sourceId == TYPE_VIDEO) {
            videoFormat = format;
            mVideoBitrate = format.bitrate;
        } else if (sourceId == TYPE_AUDIO) {
            mAudioBitrate = format.bitrate;
        }
 Log.d("ExoPlayer", "Using bitrate: " + ((mAudioBitrate + mVideoBitrate)/1000) + "kbps" + (videoFormat != null ?  " (" + videoFormat.id + ", " + videoFormat.codecs + ")" : ""));
```
