### ISSUE TITLE
Support Scalable Video Coding (SVC-DASH)?

### ISSUE THREAD

**Issue by andyx96** [google/ExoPlayer#1571]
Does Exoplayer support Scalable Video Coding, or in the future?

**Comment by Ood-Tsen** [comment]
No ,
I don't find any player on Android do support SVC.

**Comment by ojw28** [comment]
@Ood-Tsen is correct. Note that since ExoPlayer uses Android's platform decoders, any support would likely rely on changes being made to the underlying platform, in addition to changes to ExoPlayer.

**Comment by Ood-Tsen** [comment]
Basically, Scalable Video Coding (SVC) is multiple pass video decoding.
It require one pass to decode base layer and another pass to decode elementary layers for a single video frame. But in ExoPlayer,  it is only one pass. One video data in and one decoded data out. 

It's not that simple to integrate SVC on ExoPlayer. Not only lack of video codec but also need to keep decoded base layer data for elementary layer decoding.

**Comment by akamigishi** [comment]
Thank you very much Ood-Tsen and ojw28!
