### ISSUE TITLE
Yt-dash-mse-test sample media doesn't play in ExoPlayer

### ISSUE THREAD

**Issue by WeiChungChang** [google/ExoPlayer#1573]
Dear all:

I need to test EXO player on a platform which is still under develop but the network is not ready.

So i just copy the MPD as well as the corresponding files from Google's standard test URL =

http://yt-dash-mse-test.commondatastorage.googleapis.com/media/car-20120827-manifest.mpd

Also I have added an instance in samples.jave to indicate the path of MPD.

It looks like: file:///storage/sdcard0/test.mpd.

The path file:///storage/sdcard0 links to a USB device & I have checked the MPD parser indeed could find the MPD & do parse well.

After then I can see a few seconds the movie is played well but it crashed suddenly.

I am not sure if EXO player allows the media segments (files) to be played locates locally instead of on the network (so a HTTP connection is in need).

Could I use EXO player to play MPEG DASH as this case?

Why the crash happens (but I still can playback about a while) ?

Thanks in advance.

**Comment by ojw28** [comment]
Playback from a `file://` URI should work fine. The sample you link to doesn't appear to play successfully when using the `http://` URI either. It's most likely a content issue, in which case we'll follow up with the owner.

**Comment by ojw28** [comment]
The sample content contains very strange edit lists in three of the video representations. We're following up with the content owner to find out whether they think the media is valid, and will either get the media fixed or patch ExoPlayer depending on the outcome of that discussion. Thanks!

**Comment by ojw28** [comment]
We believe the content is broken. When it was generated the DASH and MSE specs weren't even finalised, so it likely contains more mistakes in addition to the one that's causing the playback failure in ExoPlayer. I've suggested that the content owners might like to either fix the content, or remove it.
