### ISSUE TITLE
Support 4k HEVC 60fps video?

### ISSUE THREAD

**Issue by felixyangtw** [google/ExoPlayer#1576]
Device: Samsung S6/Android 5.1.1
I use Exoplayer to play a 4K HEVC 60fps video and it is fine to play some frames from video beginning and the video stop but the audio continues. I found that the video frames are dropped by the function dropOutputBuffer in the function processOutputBuffer in MediaCodecVideoTrack, because the variables earlyUs is less -30000. I guess that performance of the device is not enough. However, I use its native player to play this video , it is OK. Both of exoplayer and native player use hardware decoder of the device, I think exoplayer should player this video well. Is there any reason? Thanks.

**Comment by ojw28** [comment]
Please provide sample content if you want us to look at this. Thanks.

**Comment by felixyangtw** [comment]
OK! Please try the video from 4K HEVC H.265 2160p 60Fps TV Fifa World Cup 2014


It provides the download link of this video, you can see the link on the page. Thanks!

I test it, and again, exoplayer only play several frames and stop. However, native player can play the video.

**Comment by felixyangtw** [comment]
Sorry. The link is missed. Please see
https://www.youtube.com/watch?v=bgnDEZAjLhI

The author put the video on 
https://mega.nz/#!5FNDybgY!u0IARmwnTJXGeSVoTEECrPPkjnsrtEfAelvptQVGLHY

Please help to clarify, thanks.

**Comment by guness** [comment]
I don't know if it is related but here what I notice with 1080p 60fps video on a low spec device:

When I run the video fullscreen it plays flawless, however when screen has some toolbar, status bar or FAB, player drops some frames noticeable with bare eye.

**Comment by ojw28** [comment]
That implies you're just hitting the limit of what the device is capable of. The graphics pipeline has more work to do when there are toolbars etc visible, because it has additional layers that need to be composited. Depending on how the device implements this the overhead may be negligible (because it's able to do it in hardware) or large (because the limit on the number of layers that can be composited in hardware is exceeded, resulting in the device having to do some additional software compositing).

**Comment by ojw28** [comment]
We've made some improvements that will be in the `2.6.0` release (and are on the dev-v2 branch currently), which should result in much better behavior when playing videos that are hitting or exceeding what the device is capable of. Frame drops will still occur (these are inevitable), but should no longer result in the video freezing indefinitely.
