### ISSUE TITLE
I have a HLS audio stream (URI contains encryption info). How dooes one access the raw audio that is passed on to Audiotrack? I am able to play the HLS audio without any issues with the exoplayer demo player using the HLS renderer.  

### ISSUE THREAD

**Issue by dimaag** [google/ExoPlayer#1579]
Please search the existing issues before filing a new one, including issues that are closed. When filing a new issue please include all of the following, unless you're certain that they're not useful for the particular issue being reported.

- A description of the issue.
- Steps describing how the issue can be reproduced, ideally in the ExoPlayer demo app.
- A link to content that reproduces the issue. If you don't wish to post it publicly, please submit the issue, then email the link to dev.exoplayer@gmail.com including the issue number in the subject line.
- The version of ExoPlayer being used.
- The device(s) and version(s) of Android on which the issue can be reproduced, and how easily it reproduces. If possible, please test on multiple devices and Android versions.
- A bug report taken from the device just after the issue occurs, attached as a file. A bug report can be captured using "adb bugreport". Output from "adb logcat" or a log snippet is not sufficient.

**Comment by ojw28** [comment]
Please file an issue where the entire description isn't in the title, and containing the information requested in the issue template. Thanks.
