### ISSUE TITLE
Raw Audio Bytes Extraction from HLS stream using Exoplayer

### ISSUE THREAD

**Issue by dimaag** [google/ExoPlayer#1580]
I have a HLS audio stream (URI contains encryption info). I am able to play the HLS audio without any issues with the exoplayer demo player using the HLS renderer. How does one access the raw audio that is passed on to Audiotrack? My goal is to modify the raw audio from the HLS stream.

**Comment by ojw28** [comment]
This is not something we support directly. It should be pretty easy for you to locate the point in code where ExoPlayer feeds data to the `AudioTrack`, though, and work back from there...
