### ISSUE TITLE
Seek to position and paint a single frame of video.

### ISSUE THREAD

**Issue by alexbirkett** [google/ExoPlayer#1582]
When my app (and the demo app) is sent to the background, the player and the `SurfaceView` are destroyed. I understand this is [best practice](https://github.com/google/ExoPlayer/issues/702).

When user brings the app back to the foreground the `SurfaceView` paints a black box.

I'd like to seek to a position in the video and paint a single frame, is this possible?

**Comment by ojw28** [comment]
ExoPlayer does this by default if you prepare a player but don't call `setPlayWhenReady(true)`. So the solution is to:
1. Create your new player when coming back to the foreground.
2. Seek to the position you wish to restore.
3. Prepare the player.

Note that seeking before preparing is more efficient then doing it the other way around (which could cause additional and unnecessary network requests to be made).
