### ISSUE TITLE
Unable to play m3u8 on Samsung Galaxy S4(4.2.2) with exoplayer version 1.5.8

### ISSUE THREAD

**Issue by techsmash** [google/ExoPlayer#1585]
I am getting an exception while trying to play video on a samsung galasy s4 with exoplayer version 1.5.8
The same video plays in v1.5.3

In the demo app, Samples.java, replace the HLS url to http://hlsvod-azc.pgatourlive.com/8183/media/hls/2016/06/08/786698183/1465346604723/master_mobile.m3u8

I have noticed this issue only on the Samsung Galaxy S4 running 4.2.2 .

I have tracked the issue to MediaCodecUtil.java 
codecInfo.getCapabilitiesForType(supportedType)
The supported type was video/avc 
The code name is OMX.ittiam.video.decoder.avc
Getting this error while calling codecInfo.getCapabilitiesForType(supportedType)

Here is the logcat.
06-08 11:22:49.399 E/EventLogger(17524): com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.MediaCodecUtil$DecoderQueryException: Failed to query underlying media codecs
06-08 11:22:49.399 E/EventLogger(17524): 	at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SourceFile:263)
06-08 11:22:49.399 E/EventLogger(17524): 	at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SourceFile:149)
06-08 11:22:49.399 E/EventLogger(17524): 	at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(SourceFile:275)
06-08 11:22:49.399 E/EventLogger(17524): 	at com.google.android.exoplayer.ExoPlayerImplInternal.prepareInternal(SourceFile:264)
06-08 11:22:49.399 E/EventLogger(17524): 	at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(SourceFile:201)
06-08 11:22:49.399 E/EventLogger(17524): 	at android.os.Handler.dispatchMessage(Handler.java:95)
06-08 11:22:49.399 E/EventLogger(17524): 	at android.os.Looper.loop(Looper.java:137)
06-08 11:22:49.399 E/EventLogger(17524): 	at android.os.HandlerThread.run(HandlerThread.java:60)
06-08 11:22:49.399 E/EventLogger(17524): 	at com.google.android.exoplayer.util.PriorityHandlerThread.run(SourceFile:40)
06-08 11:22:49.399 E/EventLogger(17524): Caused by: com.google.android.exoplayer.MediaCodecUtil$DecoderQueryException: Failed to query underlying media codecs
06-08 11:22:49.399 E/EventLogger(17524): 	at com.google.android.exoplayer.MediaCodecUtil.getDecoderInfosInternal(SourceFile:165)
06-08 11:22:49.399 E/EventLogger(17524): 	at com.google.android.exoplayer.MediaCodecUtil.getDecoderInfos(SourceFile:115)
06-08 11:22:49.399 E/EventLogger(17524): 	at com.google.android.exoplayer.MediaCodecUtil.getDecoderInfo(SourceFile:76)
06-08 11:22:49.399 E/EventLogger(17524): 	at com.google.android.exoplayer.MediaCodecUtil.maxH264DecodableFrameSize(SourceFile:298)
06-08 11:22:49.399 E/EventLogger(17524): 	at com.google.android.exoplayer.chunk.VideoFormatSelectorUtil.isFormatPlayable(SourceFile:168)
06-08 11:22:49.399 E/EventLogger(17524): 	at com.google.android.exoplayer.chunk.VideoFormatSelectorUtil.selectVideoFormats(SourceFile:102)
06-08 11:22:49.399 E/EventLogger(17524): 	at com.google.android.exoplayer.chunk.VideoFormatSelectorUtil.selectVideoFormatsForDefaultDisplay(SourceFile:60)
06-08 11:22:49.399 E/EventLogger(17524): 	at com.google.android.exoplayer.hls.DefaultHlsTrackSelector.selectTracks(SourceFile:87)
06-08 11:22:49.399 E/EventLogger(17524): 	at com.google.android.exoplayer.hls.HlsChunkSource.prepare(SourceFile:253)
06-08 11:22:49.399 E/EventLogger(17524): 	at com.google.android.exoplayer.hls.HlsSampleSource.prepare(SourceFile:149)
06-08 11:22:49.399 E/EventLogger(17524): 	at com.google.android.exoplayer.SampleSourceTrackRenderer.doPrepare(SourceFile:54)
06-08 11:22:49.399 E/EventLogger(17524): 	at com.google.android.exoplayer.TrackRenderer.prepare(SourceFile:110)
06-08 11:22:49.399 E/EventLogger(17524): 	at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(SourceFile:273)
06-08 11:22:49.399 E/EventLogger(17524): 	... 6 more
06-08 11:22:49.399 E/EventLogger(17524): Caused by: java.lang.IllegalArgumentException
06-08 11:22:49.399 E/EventLogger(17524): 	at android.media.MediaCodecList.getCodecCapabilities(Native Method)
06-08 11:22:49.399 E/EventLogger(17524): 	at android.media.MediaCodecInfo.getCapabilitiesForType(MediaCodecInfo.java:211)
06-08 11:22:49.399 E/EventLogger(17524): 	at com.google.android.exoplayer.MediaCodecUtil.getDecoderInfosInternal(SourceFile:147)
06-08 11:22:49.399 E/EventLogger(17524): 	... 18 more
06-08 11:22:49.399 I/CONVIVA (17524): [Conviva] [1465399369.40] [INFO] [SDK] [Monitor] sid=838761966 SetPlayerState(): changing player state from BUFFERING to STOPPED
06-08 11:22:49.399 I/CONVIVA (17524): [Conviva] [1465399369.40] [INFO] [SDK] [Monitor] sid=838761966 Enqueue CwsErrorEvent
06-08 11:22:49.399 D/EventLogger(17524): state [0.21, false, I]
06-08 11:22:49.399 V/WindowManager(  705): Window{42d5a750 u0 Keyguard}mOrientationRequetedFromKeyguard=false
06-08 11:22:49.409 I/SurfaceFlinger(  194): id=1697(31) createSurf 0x40879d74 (1x1),1 flag=4, com.pgatourlive.pga/com.pgatourlive.pga.activity.PlayerActivity
06-08 11:22:49.409 V/WindowManager(  705): Window{42d5a750 u0 Keyguard}mOrientationRequetedFromKeyguard=false
06-08 11:22:49.429 V/WindowManager(  705): Window{42d5a750 u0 Keyguard}mOrientationRequetedFromKeyguard=false
06-08 11:22:49.509 E/MP-Decision( 1650): num online cores: 4 reqd : 2 available : 4 rq_depth:2.000000 hotplug_avg_load_dw: 212
06-08 11:22:49.509 E/MP-Decision( 1650): DOWN cpu:3 core_idx:3 Ns:3.100000 Ts:240 total_time_down:245.000000
06-08 11:22:49.509 E/MP-Decision( 1650): DOWN cpu:2 core_idx:2 Ns:2.100000 Ts:240 total_time_down:245.000000
06-08 11:22:49.629 I/[PSDK-VA]::VideoAnalyticsPSDKWrapper#_playhead()(  615): playhead=0.0.
06-08 11:22:49.649 I/[PSDK-VA]::VideoAnalyticsPSDKWrapper#dataResolver(  615): Get qos info: 0; 0.0; 0; 0.0
06-08 11:22:49.729 I/SurfaceFlinger(  194): id=1691 Removed FreezeSurface (8/12)
06-08 11:22:49.729 I/SurfaceFlinger(  194): id=1693 Removed BlackSurface (8/11)

**Comment by ojw28** [comment]
Please can your try with the current dev branch? This was probably fixed by 82ef94e. Thanks!

**Comment by ojw28** [comment]
Closing assumed fixed on `dev` and in `1.5.9`. Please re-open if this is not the case.
