### ISSUE TITLE
Duration of HLS content always returned as -1

### ISSUE THREAD

**Issue by rini-m** [google/ExoPlayer#1587]
Hi, I am using exoplayer version 1.5.8. I have an issue while trying to play a HLS content. Duration of content is always returned as -1. I tried other sample HLS contents and it is working fine. I don't know why this one is not working. While debugging, I could find that duration of TextTrackRenderer returned  is TrackRenderer.UNKNOWN_TIME_US which results in media duration to be -1. Could you please advice what  can be the possible causes which would result in media duration to be -1?

**Comment by ojw28** [comment]
If it's only a specific piece of content that's broken, and if we don't have a link to that content, how are we supposed to follow up on this... ;)?

**Comment by xenDev** [comment]
I work with Rini on the same team.

Here is an example that shows the problem with BBB. 
http://bbb-small.s3-website-us-east-1.amazonaws.com/bbb_main.m3u8

The issue occurs only if WebVTT m3u8 is there.  As the duration is not known, fastforward resumes the playback from start.

Btw, this issue occurs with other content that we have.

**Comment by ojw28** [comment]
I think the problem is that your WebVTT playlists are missing #EXT-X-ENDLIST tags. The lack of this tag indicates that additional segments might be added to the playlist in the future. As a result the WebVTT part of your media is (correctly) treated as a live stream that may have additional media appended to it.

**Comment by ojw28** [comment]
So to conclude: Adding #EXT-X-ENDLIST tags to your WebVTT playlists should resolve the issue. You should do this regardless, since the lack of this tag may well lead to players repeatedly refreshing the WebVTT playlist in case new segments have been added.
