### ISSUE TITLE
Compute RBG color from ByteBuffer in MediaCodecVideoTrackRenderer

### ISSUE THREAD

**Issue by Oleur** [google/ExoPlayer#1589]
Hello, 

I'm currently looking for extracting the RGB color from the video buffer.
I am processing the outByteBuffer in `renderOutputBufferV21` before calling `codec.releaseOutputBuffer()` but it looks like the buffer is very small (size = 8). When I process the input buffer when calling `codec.getInputBuffer(inputIndex)` I am getting a larger buffer which respects the frame size. Converting this ByteBuffer as a `byte[]`I am able to get the frame in the YUV colorspace and the convert this frame to RGB colorspace.

Here the color extractor fonction:
```java
private void extractFrameColor(MediaCodec codec) {
        int inputIndex = codec.dequeueInputBuffer(20000);

        if (inputIndex < 0) {
            return;
        }

        ByteBuffer inputBuffer = codec.getInputBuffer(inputIndex);

        byte[] bytesFrame = new byte[inputBuffer.remaining()];
        inputBuffer.put(bytesFrame);

        android.media.MediaFormat format = codec.getOutputFormat();
        int width = format.getInteger(android.media.MediaFormat.KEY_WIDTH);
        int height = format.getInteger(android.media.MediaFormat.KEY_HEIGHT);
        long rgb = averageRGBFromYUV420(bytesFrame, width, height);

        /*a /= rgba.length;
        r /= rgba.length;
        g /= rgba.length;
        b /= rgba.length;*/

        //Log.e("MediaCodecTrackRenderer", "Average RGB Color " + (rgb & 0x0000FF) + ", " + ((rgb & 0x00FF00) >> 8) + ", " + ((rgb & 0xFF0000) >> 16));

        codec.queueInputBuffer(inputIndex, 0, inputBuffer.remaining(), 0, MediaCodec.BUFFER_FLAG_KEY_FRAME);
    }
```

I am note really sure which buffer I should take and where do I need to call the extractor method. I am currently implementing a custom MediaCodecVideoTrackRenderer. Is it possible to just override the `processOutputBuffer` method in a `CustomMediaCodecVideoTrackRenderer` which extends `MediaCodecVideoTrackRenderer` ? 

URL: http://s3-eu-west-1.amazonaws.com/cinemur-unicorn/starwars7_480p.mp4

Thanks for the help, 

Julien

**Comment by nikhilkilivayil** [comment]
@Oleur Any option to get YUV frame from applications without display the video content.
