### ISSUE TITLE
MediaCodecVideoTrackRenderer#processOutputBuffer 

### ISSUE THREAD

**Issue by whoyouni** [google/ExoPlayer#1591]
in a device with Rom OS always drop Frames ,what make condition(earlyUs < -30000) true

**Comment by ojw28** [comment]
Please provide sufficient information, as is clearly requested in the issue template, if you wish for us to investigate this kind of issue.

**Comment by whoyouni** [comment]
the device is [http://www.mi.com/tvzj/specs/](url),the video path is [http://training.finger66.com/action/MTQ2NTI3ODg5MTI4Nw==.mp4.m3u8?1](url) or [http://training.finger66.com/action/MTQ2NTI3ODg5MTI4Nw==.mp4?1](url)
