### ISSUE TITLE
Support of SHVC (Scalable HEVC)

### ISSUE THREAD

**Issue by arianaa30** [google/ExoPlayer#1597]
Hi, I was wondering if Exoplayer supports playing videos encoded with Scalable HEVC?

**Comment by ojw28** [comment]
We don't support SHVC. The answer in https://github.com/google/ExoPlayer/issues/1571 applies here too.

**Comment by arianaa30** [comment]
Thanks ojw28 for the answer. I have a stupid question: I understand that exoplayer relies on Android's platform decoders; but why is it that any support of say SHVC would likely rely on changes being made to the underlying platform?! Can't we do it simply by adding native libraries to decode any encoded video and whatnots?

For instance currently MP4Box which is a web-based player is able to read SHVC streams. If a web-based player can do that, why can't we do that here?! I appreciate if you clarify it for me.

**Comment by ojw28** [comment]
You're correct; it would be possible to bundle a software decoder that supports SHVC streams into your app, and use it from ExoPlayer. Such an approach would be similar to how we support bundling of FLAC, Opus and VP9 software decoders via [extensions](https://github.com/google/ExoPlayer/tree/master/extensions). We don't have any plans to do this to support SHVC though. Also note that software decoders are typically less able and significantly less power efficient than the hardware decoders that can be provided by the underlying platform on many devices.

**Comment by arianaa30** [comment]
It's clear now. Thanks. Given that there is already mp4box that plays it, how hard is it to add it myself to exoplayer? And do you think it might worth it? Will we get good performance with 3 layers?

**Comment by cconcolato** [comment]
@arianaa30 you're confusing mp4box and mp4client. Anyway note that GPAC mp4client does not yet support playback of SHVC on Android, only on Desktop platforms.

**Comment by ojw28** [comment]
@arianaa30 - I think those are questions you'll have to answer for yourself ;). It's not something we're interested in supporting directly at the current time.
