### ISSUE TITLE
Black screen when recreating SurfaceView

### ISSUE THREAD

**Issue by sergiomartinez4** [google/ExoPlayer#1599]
I've seen this issue already reported a few times, specially this one #1084, but all of them involve using TextureView, which is not an option for us.

The way to reproduce it is similar as the other issues reported, by destroying and recreating the SurfaceView. where once the method **player.setPlayWhenReady(true)** is called, the Audio starts playing, but the **onDrawnToSurface(surface)** takes around 3 seconds to be called.

I added this code on the OnCreate of the PlayerActivity on the demo app from ExoPlayer.

```
@Override
  public void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
final Handler handler = new Handler(this.getMainLooper());
    handler.postDelayed(new Runnable() {
      @Override
      public void run() {
        Log.w(TAG, "RUNNING FIRST POST");
        if (player != null) {
          player.removeListener(PlayerActivity.this);
          player.setPlayWhenReady(false);

        }
        surfaceView.setVisibility(View.GONE);

        handler.postDelayed(new Runnable() {
          @Override
          public void run() {
            Log.w(TAG, "RUNNING SECOND POST");
            surfaceView.setVisibility(View.VISIBLE);
            if (player != null) {
              player.addListener(PlayerActivity.this);
              player.setPlayWhenReady(true);
            }
          }
        }, 5000);
      }
    }, 6000);

```

It's more noticeable when playing the BipBop video: https://devimages.apple.com.edgekey.net/streaming/examples/bipbop_16x9/bipbop_16x9_variant.m3u8

After adding that code and installing the app, play the video. After 6 seconds the video will stop for 5 seconds. After resuming, the audio will start playing, and the video will play around 3 seconds later.

I tested it on a Nexus 5 5.1, and a HTC One  5.1.

Is there an optimized way to get around that?

**Comment by sergiomartinez4** [comment]
is there any news on this? I would really appreciate some feedback.

Just for the record, I can also see this issue playing the BipBop video (https://devimages.apple.com.edgekey.net/streaming/examples/bipbop_16x9/bipbop_16x9_variant.m3u8)

Thanks

**Comment by Ood-Tsen** [comment]
I test it on branch 'dev-2.X.X-experimental' on HTC One Android 5.1.

Video and audio come almost at the same time (closed , only slightly delayed).
But my problem is the picture is broken at very beginning. It should not be sync frame at that time.

**Comment by sergiomartinez4** [comment]
thanks for the info @Ood-Tsen , I just tried it and the delayed is definitely reduced, but I'm also getting the trash pixels at the beginning

**Comment by ghost** [comment]
@Ood-Tsen  i get the same problem.  does u fixed it?

**Comment by ojw28** [comment]
Smoothly switching between surfaces (including detaching and re-attaching) is tracked by https://github.com/google/ExoPlayer/issues/677.
