### ISSUE TITLE
ExoPlayer Issue on android 4.2.2

### ISSUE THREAD

**Issue by nimukup** [google/ExoPlayer#1601]
As reference on the below issue , 
https://github.com/google/ExoPlayer/issues/1577

We have added patch from broadcom for omx support and now we are getting error from the exoplayer , Please find attached log , Screen is showing and no video is there on the screen. 
How can we debug from here . Please help us  
[Exoplayer--bcm-JB-4.2.2.txt](https://github.com/google/ExoPlayer/files/318022/Exoplayer--bcm-JB-4.2.2.txt)

**Comment by andrewlewis** [comment]
What is the error from ExoPlayer? Please share a full bug report (`adb bugreport`). I couldn't find any clues about what is going on in those logs.

Note: We have very limited resources to deal with device-specific issues like this, and we can't efficiently investigate bugs on devices/builds that haven't passed Android CTS. I'd recommend you follow up with Broadcom directly.

**Comment by ojw28** [comment]
To add to the above: What you're asking with these issues is equivalent to asking us to assist with the platform media bring-up of this specific device. This is beyond what we're able to assist with, and is the responsibility of the device manufacturer (either yourselves of Broadcom, depending on exactly what your relationship is with them).

Please do not file further issues relating to this device unless you can show that it correctly passes Android's compatibility test suite, and is generally stable and able to run other apps such as YouTube successfully. Details about the compatibility test suite can be found [here](https://source.android.com/compatibility/cts/). Once the device passes CTS, at this point it becomes reasonable for you to open issues on this issue tracker. Please attach CTS test results showing the device passes when you do so.

Thanks!
