### ISSUE TITLE
DRM can not render the video, but reachs the WidevineTestMediaDrmCallback executeKeyRequest method

### ISSUE THREAD

**Issue by billyjoker** [google/ExoPlayer#1602]
- Exoplayer 1.5.8.
- Moto X with Android 5.1 

Currently i successfully reach the WidevineTestMediaDrmCallback `executeKeyRequest` method, but i am not able to render the video.

The exception seems to be related with the initialization of the video:

```
    java.lang.IllegalStateException
            at android.media.MediaCodec.native_stop(Native Method)
            at android.media.MediaCodec.stop(MediaCodec.java:635)
```

And

`com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc.secure, MediaFormat(1, video/avc, -1, -1, 852, 480, 0, 0.99921936, -1, -1, null, 2000011, false, 1280, 720, -1, -1, -1)`

**Comment by billyjoker** [comment]
As i am researching, it seems that a drm video can not be displayed on a TextureView, the only way is on a SurfaceView, it is related with the security...

**Comment by andrewlewis** [comment]
Yes, TextureView can't be used if the media requires a secure video path. See also #370.
