### ISSUE TITLE
Inconsistent representations in DASH live stream crashes player

### ISSUE THREAD

**Issue by nbruning** [google/ExoPlayer#1604]
As explained in the class comment of DashChunkSource, the parser loads the list of representations from the first manifest and expects the stream to contain the same representations in all further periods.

However, we have observed various cases in which this assumption does not hold, for example, when re-configuring the streaming platform.

Awaiting a proper fix, we should at least silently ignore extra / missing representations.

I'll push a small PR shortly which handles the situation gracefully.

Reproduction:
- Start a MPEG-DASH live stream.
- Reconfigure streaming platform to provide a different set of representations. 
- App crashes.

We've observed this using Unified Streaming Platform 1.7.6), using Exoplayer dev (f77ffd5).

_Stacktraces_

When a representation is removed in a later manifest:

```
E/ExoPlayerImplInternal(13164): Internal runtime error.
E/ExoPlayerImplInternal(13164): java.lang.IndexOutOfBoundsException: Invalid index 5, size is 5
E/ExoPlayerImplInternal(13164):     at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
E/ExoPlayerImplInternal(13164):     at java.util.ArrayList.get(ArrayList.java:308)
E/ExoPlayerImplInternal(13164):     at java.util.Collections$UnmodifiableList.get(Collections.java:1050)
E/ExoPlayerImplInternal(13164):     at com.google.android.exoplayer.dash.DashChunkSource$PeriodHolder.updatePeriod(DashChunkSource.java:1022)
E/ExoPlayerImplInternal(13164):     at com.google.android.exoplayer.dash.DashChunkSource.processManifest(DashChunkSource.java:767)
E/ExoPlayerImplInternal(13164):     at com.google.android.exoplayer.dash.DashChunkSource.continueBuffering(DashChunkSource.java:335)
E/ExoPlayerImplInternal(13164):     at com.google.android.exoplayer.chunk.ChunkSampleSource.continueBuffering(ChunkSampleSource.java:220)
E/ExoPlayerImplInternal(13164):     at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:127)
E/ExoPlayerImplInternal(13164):     at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:434)
E/ExoPlayerImplInternal(13164):     at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
E/ExoPlayerImplInternal(13164):     at android.os.Handler.dispatchMessage(Handler.java:98)
E/ExoPlayerImplInternal(13164):     at android.os.Looper.loop(Looper.java:145)
E/ExoPlayerImplInternal(13164):     at android.os.HandlerThread.run(HandlerThread.java:61)
E/ExoPlayerImplInternal(13164):     at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
```

When a representation is added in a later manifest:

```
E/ExoPlayerImplInternal(24515): Internal runtime error.
E/ExoPlayerImplInternal(24515): java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.exoplayer.dash.DashChunkSource$RepresentationHolder.updateRepresentation(long, com.google.android.exoplayer.dash.mpd.Representation)' on a null object reference
E/ExoPlayerImplInternal(24515):     at com.google.android.exoplayer.dash.DashChunkSource$PeriodHolder.updatePeriod(DashChunkSource.java:1023)
E/ExoPlayerImplInternal(24515):     at com.google.android.exoplayer.dash.DashChunkSource.processManifest(DashChunkSource.java:767)
E/ExoPlayerImplInternal(24515):     at com.google.android.exoplayer.dash.DashChunkSource.continueBuffering(DashChunkSource.java:335)
E/ExoPlayerImplInternal(24515):     at com.google.android.exoplayer.chunk.ChunkSampleSource.continueBuffering(ChunkSampleSource.java:220)
E/ExoPlayerImplInternal(24515):     at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:127)
E/ExoPlayerImplInternal(24515):     at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:434)
E/ExoPlayerImplInternal(24515):     at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
E/ExoPlayerImplInternal(24515):     at android.os.Handler.dispatchMessage(Handler.java:98)
E/ExoPlayerImplInternal(24515):     at android.os.Looper.loop(Looper.java:145)
E/ExoPlayerImplInternal(24515):     at android.os.HandlerThread.run(HandlerThread.java:61)
E/ExoPlayerImplInternal(24515):     at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
```

This issue might be the cause for #1365 and #1369.

**Comment by ojw28** [comment]
Is a new Period started in the manifest when these reconfigurations occur? I think this might be a requirement for doing this kind of thing (i.e. I don't think it's valid for the server just to be adding and removing Representation elements without starting a new Period).

**Comment by nbruning** [comment]
I've captured two manifests that will reproduce the problem.
Both manifests specify 1 period with id "1", with startsAt "PT0S".

I'm not sure whether this is valid from the servers perspective; however I feel it's probably better to use defensive programming. The patch I've submitted does not change the behavior of the player in case the representation list remains the same over time.

**Comment by ojw28** [comment]
I disagree with the assertion that defensive programming is better, in this context. I think I might write a blog post explaining exactly why at some point, since this has come up a few times, but roughly speaking:
- If a media spec specifies something, it's probably specified for a reason.
- If someone then produces content that violates the spec, if all media players follow the model you suggest, then the "solution" is for players to "handle" the spec violation.
- This encourages the production of more content that violates the spec, and so violates something that was specified for a reason.
- This in turn undermines the original media spec, and also makes it borderline impossible for someone to write a new player from scratch that plays the majority of media, because you end up with all kinds of unofficial "stuff" that players become expected to handle even though said "stuff" doesn't exist anywhere in an official media spec.

I don't think we'll be fixing this unless you can show that it's allowed by the DASH spec. I believe a new Period element has to be used for such reconfigurations.

**Comment by nbruning** [comment]
Quick browsed through the spec, didn't see it being allowed or disallowed specifically.

Surely understand your point of view not to include server-specific workarounds, so no worries if you close the issue and MR.

As for the issue: my guess is that reconfiguring was performed using a server restart, in which case the server probably restarts counting periods from zero. For a long-lived stream (tv channel) this might happen once in a while.

**Comment by ojw28** [comment]
The [DASH IF Recommendations](http://dashif.org/w/2015/04/DASH-IF-IOP-v3.0.pdf) implies in 3.2.12 that you should probably be starting a new Period to remove or add Representation elements in an Adaptation Set.

You should probably find a way of avoiding having server restarts underneath streams that users are actually consuming (short of something going fairly badly wrong, in which case failure would be expected). I don't think there exist technical reasons why this should not be possible.
