### ISSUE TITLE
DASH - Audio can start playing slightly before video

### ISSUE THREAD

**Issue by kinhdang** [google/ExoPlayer#1608]
Hello,

We play stream DASH type in ExoPlayer, during the playback, its observed that Video is stuck and only audio plays for few seconds and later the video starts to play.
this issure the same [https://github.com/google/ExoPlayer/issues/900](url) at #900 . Althought. Testing this Video Stream On Bitmovin at [(Test Your Video),](https://bitmovin.com/mpeg-dash-hls-drm-test-player/) this can be play well.

Anyknows, please give idea, how to fix ?
Thanks.

**Comment by adrianrdzv** [comment]
If it's a live stream, for us increasing liveEdgeLatencyMs in the DashChunkSource fixed the issue.

**Comment by peyoh** [comment]
Hello @adrianrdzv ,
what value you are using?

**Comment by ojw28** [comment]
I'm pretty sure this is resolved in `dev-v2`.
