### ISSUE TITLE
Server not sending down the correct response.

### ISSUE THREAD

**Issue by cyberjaime45** [google/ExoPlayer#1610]
Firstly, I want to thank for this awesome library.  I just integrated to my project. Its actually replacing another library I was using.

My app offers hundred of selected online radios that stream live using shoutcast, icecast among others. I noticed a great number of radios stations stopped playing when using this library on devices running android 4 & < 5. Lollipop and Marshmallow doesn't seem to have that problem. While debugging I noticed that response from the server was -1. (not sure if this means that server failed to send any response at all) 

So I changed the validation response code a bit (responseCode >= 1 && responseCode < 200 || responseCode > 299). With this change all stations are playing audio. I know this is not best way to fix this issue, but I don't have access to servers. Just wanted to share my issues.

**Comment by cyberjaime45** [comment]
Hey, I had the same problem. The issue here I believe is the response being -1. Somehow Android >=5 is able to handle this. However android 4+ fails due to a non- ok response.

In order to avoid go around I modified the validation response to: (responseCode >= 1 && responseCode < 200 || responseCode > 299)

This is not best way, but it works just fine.

**Comment by ojw28** [comment]
I think this is because the server you're hitting is using ICY rather than HTTP. There are various related issues [here](https://github.com/google/ExoPlayer/issues?utf8=%E2%9C%93&q=is%3Aissue%20ICY%20). Thanks for sharing!
