### ISSUE TITLE
Problem with subtitles MediaFormat.language at HLS stream

### ISSUE THREAD

**Issue by laurafuente** [google/ExoPlayer#1612]
For the following stream: https://devimages.apple.com.edgekey.net/streaming/examples/bipbop_16x9/bipbop_16x9_variant.m3u8, when I'm trying to get the list of subtitles by player.getTrackCount(TYPE_TEXT) the list of MediaFormat returned has a null value for the MediaFormat.language field. 

The HLS parser seems to be working correctly because when onSingleManifest is called at HlsRendererBuilder the masterPlaylist.subtitles field has an array of MediaFormats with the value language filled correctly

**Comment by AquilesCanta** [comment]
A fix will be available soon, thanks for the report.
