### ISSUE TITLE
MJPEG support

### ISSUE THREAD

**Issue by ened** [google/ExoPlayer#1614]
For a current project I'm evaluating various MJPEG players.
It can be very complicated (ffmpeg, native code, VLC) or simple with Java-only implementations like https://bitbucket.org/neuralassembly/simplemjpegview .

However, there are multiple MJPEG implementations in varying quality around. 
Ideally we would pick the best Java implementation and bring it into ExoPlayer as an extension (like flac, vp9).

@ojw28 is this something the project would support? If so, I will try to start the extension.

**Comment by ojw28** [comment]
You're more than welcome to create your own extension to do this, but we're unlikely to provide official support (i.e. we're unlikely to merge it into this repository or ensure that it continues to build against new versions of ExoPlayer). It's unclear that there's sufficient demand, and every edge case feature we decide to take slows down the speed at which we're able to iterate on the core use cases we should be prioritising. If sufficient demand is demonstrated, we could reconsider.
