### ISSUE TITLE
Which is the best player to do use to play .smil file with Adaptive bitrate streaming in android? 

### ISSUE THREAD

**Issue by Muthukathiravan** [google/ExoPlayer#1615]
Please search the existing issues before filing a new one, including issues that
are closed. When filing a new issue please include all of the following, unless
you're certain that they're not useful for the particular issue being reported.
- A description of the issue.
- Steps describing how the issue can be reproduced, ideally in the ExoPlayer
  demo app.
- A link to content that reproduces the issue. If you don't wish to post it
  publicly, please submit the issue, then email the link to
  dev.exoplayer@gmail.com including the issue number in the subject line.
- The version of ExoPlayer being used.
- The device(s) and version(s) of Android on which the issue can be reproduced,
  and how easily it reproduces. If possible, please test on multiple devices and
  Android versions.
- A bug report taken from the device just after the issue occurs, attached as a
  file. A bug report can be captured using "adb bugreport". Output from "adb
  logcat" or a log snippet is not sufficient.

**Comment by andrewlewis** [comment]
Are you trying to play a Smooth Streaming stream? Please could you provide a link to the media?

**Comment by Muthukathiravan** [comment]
Its not a smooth streaming.I am trying to play with HLS

**Comment by andrewlewis** [comment]
We need a link to the stream you're trying to play to diagnose this, as requested in the issue template.

If the stream really is HLS, are you building renderers to play an HLS stream? Using [HlsRendererBuilder](https://github.com/google/ExoPlayer/blob/master/demo/src/main/java/com/google/android/exoplayer/demo/player/HlsRendererBuilder.java) for example?

**Comment by Muthukathiravan** [comment]
http://<wowza-ip>E:1935/live/smil:mystream.smil/playlist.m3u8, I have checked with this URL,Give Me exact solution and example for this

**Comment by andrewlewis** [comment]
The name "E" looks wrong. Why is this using the same port as RTMP? We need to have the URL to a stream that is publicly visible to debug this. If you can't share it on this issue tracker please email it to dev.exoplayer@gmail.com.

**Comment by Muthukathiravan** [comment]
Sorry i have shared wrong URL,http://<wowza-ip>:1935/live/smil:mystream.smil/playlist.m3u8 this is the correct URL

**Comment by andrewlewis** [comment]
That looks wrong too. There is no domain name.

**Comment by ojw28** [comment]
This issue is really very confusing. Closing.

**Comment by mohammed-najeeb** [comment]
Does exoplayer run adaptive bitrate for smil file

**Comment by kevinp1005** [comment]
I have the same question with mohammed-najeeb, does the exoplayer able to play smil file ? In my case I'm using wowza streaming engine.
