### ISSUE TITLE
set referer value in Exo

### ISSUE THREAD

**Issue by AlirezaGhanbarinia** [google/ExoPlayer#1619]
How can we set referer value in Exo? seems that, it sends “-” as the default value now.

**Comment by ojw28** [comment]
What is "referer value"? Please provide significantly more information. Thanks.

**Comment by AlirezaGhanbarinia** [comment]
It should be the sender name or sign. For ex, Youtube should send it as “Youtube”, another clone of Youtube should send it as “Youtube2”. So the stream server can seperate these clients and identifies them with the Referer value.

**Comment by ojw28** [comment]
I get what a referrer is for, but how you specify it is probably specific to your serving infrastructure and what type of media you're playing. Hence there's insufficient information here for us to help. It could be as simple as just setting a query parameter in the URL that you're trying to play before passing it to ExoPlayer.

**Comment by AlirezaGhanbarinia** [comment]
I know, but our stream server, picks the Referer value from header of stream request. Can we set custom
header requests while calling stream URL?

**Comment by ojw28** [comment]
You're not providing sufficient information for us to understand the problem, sorry. You need to explain clearly _how_ the referrer value is being sent. If it's just a query parameter on a URL, you should just change the URL that you give to ExoPlayer.

**Comment by zsmatyas** [comment]
Isn't it a header value in the request in the major web browsers? In that case you can try something like

`defaultHttpDataSource.setRequestProperty("Referer", "my_referer_value");`

Similar to: 
http://stackoverflow.com/questions/31162441/setting-headers-for-streaming-mp4-video-and-playing-files-with-exoplayer
