### ISSUE TITLE
Not possible to generate a license challenge with the Android DRM Framework APIs, when using MediaDrm.KEY_TYPE_STREAMING

### ISSUE THREAD

**Issue by moacir69** [google/ExoPlayer#1621]
Currently it is not possible to generate a license challenge when using Android DRM Framework APIs and MediaDrm.KEY_TYPE_STREAMING in a Razer Forge / Android 5.1.1.
In the logs, there is the following error message when MediaDrm.getKeyRequest() is used to get a license challenge:

...
06-22 10:54:31.846 4919-4919/? E/PlayReady﹕ Error: playready_licacq_generate_challenge failed and returned -2147024774
06-22 10:54:31.846 4919-4919/? D/PlayReady﹕ playready_licacq_generate_challenge returns -2147024774, the length of challenge = 7102
06-22 10:54:31.847 4919-4919/? D/PRClient﹕ getKeyRequest:: playready_licacq_generate_challenge(1st) returned 0X8007007a BUFFERTOOSMALL, iLicenseQuerySizeLocal = 7102. Continue with good buffer size.
06-22 10:54:31.847 4919-4919/? D/PlayReady﹕ playready_licacq_generate_challenge starts!
--------- beginning of crash
06-22 10:54:31.865 4919-4927/? A/libc﹕ Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 4927 (FastMixer)
...

The related content is: http://essdrmproducts-eu.insidesecure.com/content/SS/encrypted/baseline/DaPromo/DaPromo.ism/manifest and the issue is reproduced when MediaDrm.getKeyRequest() is called with the following parameters:
- scope = session identifier for the related content key identifier
- init = related content manifest protection header
- mime type = null,
- key type = MediaDrm.KEY_TYPE_STREAMING
- optional parameters = null

The same method call is working fine with other devices, like the Asus Nexus Player / Android N.
Can you please analyse this issue?
Kind regards,

Moacir

**Comment by ojw28** [comment]
From the issue template, please include the following:
- A bug report taken from the device just after the issue occurs, attached as a
  file. A bug report can be captured using "adb bugreport". Output from "adb
  logcat" or a log snippet is not sufficient.

**Comment by moacir69** [comment]
[logs.txt](https://github.com/google/ExoPlayer/files/327556/logs.txt)

**Comment by moacir69** [comment]
Hi,
Do you have any update regarding this issue?
Thank you,

Moacir

**Comment by ojw28** [comment]
@wvpaf - Could you take a look at this? Thanks!

**Comment by wvpaf** [comment]
Hi there,
We took a look and will need to reach out to the OEM/SoC as the log looks like : 
error @ 12:27:48.097 results in error 500 from the PR server. 
....
06-22 12:27:48.094   492 16120 D DRMAgentDelegate: Silent acquisition initiated
06-22 12:27:48.097   492 16120 E drmagent-jni: [nativeGetMetaData] getProperty failed
06-22 12:27:48.097   492 16120 E drmagent-jni: [nativeGetMetadata] Error occurred
06-22 12:27:48.098   492 16122 D AbstractDRMLicenseAcquisitionHandler: Acquiring license from: http://essdrmproducts-eu.insidesecure.com/test-portal/device/portal?b=6369643d6369643a44423143394243352d453942382d343546352d424239462d4233413936323344303841304061757468656e7465632e746573742e706f7274616c2e636f6d7c7c616369643d6576616c7c7c6d3d505253696c656e744c6963656e736544656c6976657279
06-22 12:27:48.098   492 16122 D LicenseAcquisitionHlpr: License Acquisition URL from header: http://essdrmproducts-eu.insidesecure.com/test-portal/device/portal?b=6369643d6369643a44423143394243352d453942382d343546352d424239462d4233413936323344303841304061757468656e7465632e746573742e706f7274616c2e636f6d7c7c616369643d6576616c7c7c6d3d505253696c656e744c6963656e736544656c6976657279
06-22 12:27:48.098   492 16122 D LicenseAcquisitionHlpr: Web Initiator: supported
06-22 12:27:48.098   492 16122 D LicenseAcquisitionHlpr: Detected the TTS license server, will reconstruct the LA_URL accordingly
06-22 12:27:48.098   492 16122 D LicenseAcquisitionHlpr: Force time-based license: No
06-22 12:27:48.098   492 16122 D LicenseAcquisitionHlpr: Number of Minutes: 5
06-22 12:27:48.098   492 16122 D LicenseAcquisitionHlpr: Force OPL license: No
06-22 12:27:48.098   492 16122 D LicenseAcquisitionHlpr: OPL Level: 100
06-22 12:27:48.098   492 16122 D LicenseAcquisitionHlpr: Force Interval license: No
06-22 12:27:48.098   492 16122 D LicenseAcquisitionHlpr: Number of Second: 30
06-22 12:27:48.098   492 16122 D LicenseAcquisitionHlpr: Play enablers: 
06-22 12:27:48.098   492 16122 D LicenseAcquisitionHlpr: Force Acknowledgement: No
06-22 12:27:48.099   492 16122 D LicenseAcquisitionHlpr: New URL: http://essdrmproducts-eu.insidesecure.com/test-portal/device/portal?PlayRight=1
06-22 12:27:48.155  5872  5881 I art     : Wrote stack traces to '/data/anr/traces.txt'
06-22 12:27:48.155  7035  7040 I art     : Thread[5,tid=7040,WaitingInMainSignalCatcherLoop,Thread*=0xb7721ad8,peer=0x12c000a0,"Signal Catcher"]: reacting to signal 3
06-22 12:27:48.197   492 16122 W AbstractDRMLicenseAcquisitionHandler: Error while retrieving license: 500 : Internal Server Error (at http://essdrmproducts-eu.insidesecure.com/test-portal/device/portal?PlayRight=1)
06-22 12:27:48.198   492 16122 D AbstractDRMLicenseAcquisitionHandler: Received PlayReady Soap Error: 
06-22 12:27:48.198   492 16122 D AbstractDRMLicenseAcquisitionHandler:     FaultCode: soap:Server
06-22 12:27:48.198   492 16122 D AbstractDRMLicenseAcquisitionHandler:     FaultString: The length of the challenge is 0
....

**Comment by moacir69** [comment]
Hi there,
This is happening due to the failure in the generation of the license acquisition challenge with Android Media DRM Framework API. It either crashes or generates an empty one:

...
06-22 12:27:48.198 492 16122 D AbstractDRMLicenseAcquisitionHandler: FaultString: The length of the challenge is 0
...

Therefore, this is not a license server issue, but instead a client issue.
Thank you,

Moacir

**Comment by jefftinker** [comment]
Moacir, yes that looks right, the 500 error is a result of the invalid challenge provided to the server.

Looking at the log segment you posted in the original report, it looks like the challenge buffer you are providing may be too small:

06-22 10:54:31.847 4919-4919/? D/PRClient﹕ getKeyRequest:: playready_licacq_generate_challenge(1st) returned 0X8007007a BUFFERTOOSMALL, iLicenseQuerySizeLocal = 7102. Continue with good buffer size.

Can you check if increasing the buffer size allows the challenge to be returned?

**Comment by moacir69** [comment]
Hi,
The buffer size seems to be internal to the Android DRM Framework API, it is not passed as input.
Thanks,

Moacir

**Comment by wvpaf** [comment]
@moracir69, our DRM team does not integrate the PlayReady solution. 
You will need to reach out to the Razer folks to get more help.

**Comment by moacir69** [comment]
Thank you,
I have already got in touch with them.
Kind regards,

Moacir
