### ISSUE TITLE
Is it possible to use Widevine (WV) with Microsoft Smooth Streaming (MSS)?

### ISSUE THREAD

**Issue by tomaskukol** [google/ExoPlayer#1622]
As I can see in the code of DemoPlayer there is support for MSS and PlayReady. Is it possible to use also Widevine for Smooth Streams? Do we need to change the MSS manifest to support WV as it is supported for DASH to use more DRM methods?

**Comment by ojw28** [comment]
There's no obvious reason why this wouldn't work, but I don't think I've ever seen a SmoothStream/Widevine sample to know exactly what the manifest and chunks should look like.

@wvpaf - Do we have any sample streams?

**Comment by wvpaf** [comment]
Hi @tomaskukol , 

there is no path for MSS and WV. MSS is proprietary and will not inter-operate with WV.
