### ISSUE TITLE
Widevine and unique device id

### ISSUE THREAD

**Issue by mromer** [google/ExoPlayer#1624]
I want to limit the number of devices that a user can use to play DRM content. I am using Widevine, so my question is: is Exoplayer adding some unique device identifier to the licence request? I can see in the body request some bytes at the beginning that are always the same independently on the content (which could mean some kind of identifier) and a device id tag i.e device_id 4CAF609C86F&. Are some of them the identifiers?

In other hand, my Widevine support tell us that we can use privacyMode enabled in the DRM session. So there is a first request to get a certificate to obscure a second request which will return the valid licence. Is there something in Exoplayer managing this? Are those two requests thrown automatically by the Exoplayer or should we do it “manually”?
- The version of ExoPlayer being used.
  r1.5.5

Regards,
Marco

**Comment by ojw28** [comment]
I'm pretty sure that the key request contains a unique device identifier that you can use on the server side. We don't generate the license request ourselves; it comes from the Widevine CDM. I assume the structure of the key request must be documented somewhere. @wvpaf can probable assist.

As an aside, note that you're also free to add your own device identifiers to the request in your `MediaDrmCallback` implementation.

**Comment by mromer** [comment]
Hi @wvpaf ,
Some help on this subject? I have been reading something about a cert_serial_number that we are already sending in the license request. Can this be used to identify the device?

**Comment by wvpaf** [comment]
@mromer,  
To answer your original questions.
Exoplayer does not add anything to the license request that is done in the CDM.
However, there is a certificate serial number in the license request at the proxy level, that can be used to identify the device.

For the 2 requests using privacyMode, you can set privacyMode by MediaDrm.setPropertyString("privacyMode","enable"), the CDM will then generate the additional request for the service certificate and no other action is needed from the player.

**Comment by wvpaf** [comment]
@mromer  do you have your answers?  I am assuming so, and will close this case.
Please do reopen if further clarifications are needed.

**Comment by mromer** [comment]
Thanks @wvpaf for your help. We will use the certificate serial number as commented above.
