### ISSUE TITLE
Xamarin.Android Exoplayer is not supporting the WAV format files

### ISSUE THREAD

**Issue by sakthivelrajarethinam** [google/ExoPlayer#1625]
I noticed that WAV Extractor is added recently to Exoplayer (java) but in Xamarin.Android Exoplayer library is not having that fix yet, correct?

If yes, can you please let me know when it will be added to Xamarin.Android Exoplayer library?

**Comment by ojw28** [comment]
We don't have anything to do with Xamarin.Android; you'll have to ask them directly.
