### ISSUE TITLE
HLS audio track selection freeze 

### ISSUE THREAD

**Issue by khabedi** [google/ExoPlayer#1626]
On a live HLS stream, when we switch audio track (case of multi-audio stream) , we encounter a slight freeze of video ( 2 or 3 seconds), probably due to some buffer flush.
This was observed on version 1.5.8 on local implementation and also on demo app.
The device is an Android TV Google Nexus with Android 6.0.1.

Is there any fix for this issue  or some work in progress to optimize it ?

**Comment by ojw28** [comment]
If there are multiple de-muxed audio tracks, it doesn't make sense for the player to buffer all of them just in case the user changes their selection. Hence when the selection is changed there's a short delay whilst the newly selected stream is buffered. This is working as intended.

**Comment by khabedi** [comment]
This behaviour is less visible with ExoPlayer 2 and is more acceptable.

Thanks for your help
Regards
