### ISSUE TITLE
Obvious lag when play multiple mp4 files consecutively

### ISSUE THREAD

**Issue by sharkhuang** [google/ExoPlayer#1632]
My case is that I want to play multiple small mp4 clips consecutively like a whole movie but there is a obvious lag when switch video file. How can I solve this issue?

**Comment by sharkhuang** [comment]
@ojw28  what is the time-frame for 2.x release?

**Comment by ojw28** [comment]
When it's ready. Note however that there's already a [dev branch](https://github.com/google/ExoPlayer/tree/dev-2.X.X-experimental) that you can play around with, and it already features some [Playlist samples](https://github.com/google/ExoPlayer/blob/dev-2.X.X-experimental/demo/src/main/assets/sample_media.exolist.json#L335) that demonstrate seamlessly transitioning from one piece of media to another. We'll obviously be documenting this properly as we get close to doing a full 2.x release.

**Comment by sharkhuang** [comment]
Thanks a lot. Works well.
