### ISSUE TITLE
ExoPlayer seekTo method only working in debug mode with breakpoints

### ISSUE THREAD

**Issue by TonyGravano** [google/ExoPlayer#1633]
I'm currently using an ExoPlayer within Android Studio to play mp4 videos within my app, initially if the app was minimized or back grounded while the video was loaded the media player would completely stop and when the app was re-opened it was unusable and the activity had to be restarted. I managed to solve this problem by releasing the player when the activity was back grounded then when the app is reopened i check to see if the player is null and if so I instantiate it. I then use the seekTo method to try and get the video to resume from where it was when the app was left, I have the videos position stored correctly as the seekTo method works when the code is ran in debug mode with breakpoints, but it doesn't work without break points. Currently when the app is opened back up the video restarts from the beginning which isn't ideal

I've tested my code on Android 6.0 and 4.1, Sony Xperia Z5 and an Android Tablet and the problem occurs on both apis.

Here is my onPause method
![image](https://cloud.githubusercontent.com/assets/18525200/16372938/62d490e0-3c47-11e6-9ecd-05af503c1015.png)

Here is my onResume
![image](https://cloud.githubusercontent.com/assets/18525200/16372956/77ebd362-3c47-11e6-93c0-e72ee9f15ac1.png)

Here is my preparePlayer
![image](https://cloud.githubusercontent.com/assets/18525200/16372992/a4b00c1a-3c47-11e6-8602-3d9e8f42f8ce.png)

The code works when a break point is put on the mPlayer.getPlayerControl.seekTo(mVideoPosition) in the onResume().

Unfortunately i'm not that experienced with this so i'm not too sure what the problem could be on my side but I'm aware of the life cycle activities go through and with the implementation of these methods the player should run fine, as it does when break points are used. There is no error within the logs and I have managed to follow the program through up until it hits the seekTo() within ExoPlayer.java, I have been outputting to the log so I know the code gets that far, but obviously I cannot debug the ExoPlayer.java seekTo().

Any more information please feel free to ask.

**Comment by ojw28** [comment]
I think the demo app has the exact behaviour that you're trying to replicate, so I suggest you look at that. I'm not sure whether it resolves the issue for you, but you should be getting and setting position directly on the player, not on the player control.

**Comment by TonyGravano** [comment]
I had a look at the demo app and there wasn't really much I could see but I did manage to the fix the problem and you are correct regarding setting the position on the player and not the control. I implemented my own seekTo() and getCurrentPosition() on my player which call the exoplayers methods. I think the way my app is structured comapred to the demo app threw me off. 

Thanks for the help.
