### ISSUE TITLE
Does exoplayer support widevine drm on mpeg-dash with mpeg2 transport stream?

### ISSUE THREAD

**Issue by josephch** [google/ExoPlayer#1639]
Is widevine supported only for mp4 based dash or is it supported also on ts based  dash?

**Comment by ojw28** [comment]
We don't support Widevine for TS based DASH. We don't support TS based DASH at all, even without content protection. Note that the industry is moving away from TS; with Apple moving to add fMP4 within the HLS spec.

See the [supported formats](https://google.github.io/ExoPlayer/supported-formats.html) page for a good overview of what formats and format combinations ExoPlayer supports.
