### ISSUE TITLE
OMXVideoDecoder: SEC Failed: SecPassThrough: FAILED 0xff003

### ISSUE THREAD

**Issue by CaptnBlubber** [google/ExoPlayer#1640]
When trying to Play DRM Protected Content(WV/MP4 DASH) the Player will turn into endless Buffering State on Lenovo Tab Yoga Devices (Confirmed with YT2 and YT3)

**Reproduce:**

For reproduction the versions 1.5.1-1.5.9 were used and as Content, the Sample Content Provided in Demo Application was used. You can reproduce it with Content that has CENC E.g. WV:Secure SD &HD (MP4, H264) (https://storage.googleapis.com/wvmedia/cenc/h264/tears/tears.mpd)
- Open Demo App and Select CENC Video
- Let the Video Run for a few Seconds.
- At about 5-10 seconds (when the engines start) the player will start pausing the video (Freeze at the current Frame) and the audio will start to stutter. When observing the debug status text, it will continuously switch between buffering and rendering.
- The ADB log gets constantly spammed with the Same Error from OMXVideoDecoder
  `
  06-29 17:58:49.679 230-14001/? E/OMXVideoDecoder: SEC Failed: SecPassThrough: FAILED 0xff003
  06-29 17:58:49.679 230-14001/? E/OMXVideoDecoder: SEC Failed: SecPassThrough: FAILED 0xff003
  06-29 17:58:49.679 230-14001/? E/OMXVideoDecoder: SEC Failed: SecPassThrough: FAILED 0xff003
  06-29 17:58:49.689 230-14001/? E/OMXVideoDecoder: SEC Failed: SecPassThrough: FAILED 0xff003
  06-29 17:58:49.689 230-14001/? E/OMXVideoDecoder: SEC Failed: SecPassThrough: FAILED 0xff003
  06-29 17:58:49.689 230-14001/? E/OMXVideoDecoder: SEC Failed: SecPassThrough: FAILED 0xff003
  06-29 17:58:49.689 230-14001/? E/OMXVideoDecoder: SEC Failed: SecPassThrough: FAILED 0xff003
  06-29 17:58:49.699 230-14001/? E/OMXVideoDecoder: SEC Failed: SecPassThrough: FAILED 0xff003
  06-29 17:58:49.699 230-14001/? E/OMXVideoDecoder: SEC Failed: SecPassThrough: FAILED 0xff003
  06-29 17:58:49.699 230-14001/? E/OMXVideoDecoder: SEC Failed: SecPassThrough: FAILED 0xff003
  06-29 17:58:49.699 230-14001/? E/OMXVideoDecoder: SEC Failed: SecPassThrough: FAILED 0xff003
  06-29 17:58:49.709 230-14001/? E/OMXVideoDecoder: SEC Failed: SecPassThrough: FAILED 0xff003`

**Additional Information:**

For the sample content the first few seconds are playable, but on our Production L3 and L1 Widevine protected content this happens on the first frame so the player wont even switch from buffering to playing.

Here is the ADB Bugreport taken from LENOVO YOGA Tablet 2 Pro- 1380D (Android 5.0.1 API 21) Latest OS Version available for this device
[bugreport.txt](https://github.com/google/ExoPlayer/files/339702/bugreport.txt)

**Comment by ojw28** [comment]
@jefftinker / @wvpaf  - This looks similar to b/23713420. Do we have an update on that?

**Comment by bwidtmann** [comment]
note that this content is unencrypted for the first 10 seconds!

**Comment by wvpaf** [comment]
Hi,
There seems to be a fix in M MR1 according to the defect referenced by @ojw28  on 6/29.
