### ISSUE TITLE
Problem in playing mpd URLs.

### ISSUE THREAD

**Issue by ghost** [google/ExoPlayer#1642]
I implemented the ExoPlayer by almost copying the same codes except that of the Sample.java file. Instead I am giving the URLs by fetching through the server.
One problem which I am facing is that some .mpd URLs are playing fine but few URLs are not playing at all. But the same URL is playing perfectly fine in the demo app.
In latter case, the logcat shows the following: preparing -> buffering -> com.google.android.exoplayer.ExoPlaybackException: java.io.EOFException -> idle
This exception is caused only for few URLs.

Here is the code of Renderer

`case Util.TYPE_DASH:
                return new DashRendererBuilder(mContext, userAgent, url,
                        new WidevineTestMediaDrmCallback(contentId, provider));`

**Comment by ojw28** [comment]
There isn't enough information provided to help us with this issue, sorry. If it's working in the demo app, I suggest you start there and try and figure out what you've done differently.

**Comment by MohammedAtif** [comment]
The only thing which I didn't add is the Samples class and sample chooser class since I am getting the URLs from the server.  Most of the URLs are even working fine, but the URLs in the Samples.java file and few URLs from the server are causing the crash.

**Comment by MohammedAtif** [comment]
One more addition to the problem,
It is happening in few devices(Motorola Android 6.0) and working fine in few devices(Samsung android 6.0). Any compatibility issues?

**Comment by ghost** [comment]
Hi,
Problem seems to be in the Caching part. Can you help me out with this.

here is the code which I used

`Cache videoCache = new SimpleCache(context.getCacheDir(), new LeastRecentlyUsedCacheEvictor(1024 * 1024 * 10));
            DataSource videoDataSource = new DefaultUriDataSource(context, bandwidthMeter, userAgent);
            CacheDataSource videoCacheDataSource = new CacheDataSource(videoCache, videoDataSource, false, false);
            ChunkSource videoChunkSource = new DashChunkSource(manifestFetcher,
                    DefaultDashTrackSelector.newVideoInstance(context, true, filterHdContent),
                    videoCacheDataSource, new AdaptiveEvaluator(bandwidthMeter, 4000000, 10000, 20000, 25000, 0.75F), LIVE_EDGE_LATENCY_MS,
                    elapsedRealtimeOffset, mainHandler, player, DemoPlayer.TYPE_VIDEO);`

I tried playing multiple URLs by clearing the cache and it worked fine. But without clearing the cache its not playing.
