### ISSUE TITLE
Any working example for http livestreaming?

### ISSUE THREAD

**Issue by erkand-imeri** [google/ExoPlayer#1643]
Hello there, i am trying to implement the ExoPlayer player  instead of the default Android player.

But, i wanted to look for a  working code example implemented through Exoplayer.

I looked the demo app, but i need to know which classes should i include and how should i initiate them at the main Activity where my VideoView should be  drawed?

Thanks in advance, i would really appreciate any help.

**Comment by andrewlewis** [comment]
The demo app acts as a working example for HLS playback. Have a look at the [Developer guide](http://google.github.io/ExoPlayer/guide.html), [PlayerActivity.java](https://github.com/google/ExoPlayer/blob/master/demo/src/main/java/com/google/android/exoplayer/demo/PlayerActivity.java) and [HlsRendererBuilder.java](https://github.com/google/ExoPlayer/blob/master/demo/src/main/java/com/google/android/exoplayer/demo/player/HlsRendererBuilder.java). One approach is to use the demo's PlayerActivity as a starting point then remove parts which you don't need.

**Comment by sjsaleem** [comment]
https://github.com/karim23/SimpleStreamPlayer

_Regards_

_S Shaik_
