### ISSUE TITLE
HLS multi language: double language but same ISO 639-2

### ISSUE THREAD

**Issue by Gian84** [google/ExoPlayer#1644]
![screenshot_2016-06-30-17-24-57](https://cloud.githubusercontent.com/assets/16020779/16494988/c92a1224-3eeb-11e6-99bb-c6ee36fb8847.jpg)
![screenshot_2016-06-30-17-51-15](https://cloud.githubusercontent.com/assets/16020779/16494989/c92dab46-3eeb-11e6-8c46-551409c70b2a.jpg)
- When I try to reproduce an HLS multi language content in the ExoPlayer
  demo app the audio list shows the same ISO 639-2 for different languages.
- I'm using exoplayer 1.5.9.
- I'm using different devices: Sony D5103 Android 4.4.4, Samsung SM-T700 Android 5.0.2, Samsung Galaxy S4 Android 5.0.2 and others.
- Screenshots attached for different HLS contents. In the first case you can see "ITA" for both languages. I suppose the last row of the audio list should be "ENG" (in fact in the brackets I can read "audio-english").

N.B.
this is a snippet of the master playlist:

...
# EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="AUDIO_192000",NAME="audio-italian",DEFAULT=YES,AUTOSELECT=YES,LANGUAGE="ita"
# EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="AUDIO_192000",NAME="audio-english",DEFAULT=NO,AUTOSELECT=NO,LANGUAGE="eng",URI="v18.m3u8"

...

Thanks a lot.

**Comment by Gian84** [comment]
[HlsSampleSource.txt](https://github.com/google/ExoPlayer/files/346637/HlsSampleSource.txt)

Hi,
waiting for your next update I have tried to fix it and I share it with you.
I have just added the following snippet:
`if (MimeTypes.isAudio(format.mimeType)) {
            language = chunkSource.getHlsMasterPlaylist().audios.get(j).getFormat().language;
          }`

in the HlsSampleSource.java class (attached file, rows 560-562).
Obviously I have created getHlsMasterPlaylist() method to recover the private HlsMasterPlaylist.

**Comment by AquilesCanta** [comment]
Would you kindly provide the URL to the media (you can use dev.exoplayer@gmail.com if you don't want it to be public) so that I can see what the problem seems to be? The provided solution is appreciated but I would like to get to the bottom of the issue, since I fixed a somewhat similar issue not long ago.

**Comment by Gian84** [comment]
Yes, of course.
I sent to you an email with this bug title as subject field yesterday.
Let me know if you need more info.

**Comment by ojw28** [comment]
@AquilesCanta - Is this fixed in V2? I don't think we need to backport to V1, but we should make sure things are working correctly in V2.

**Comment by AquilesCanta** [comment]
Yes, this will be fixed in V2 once the new Hls patch gets pushed.
