### ISSUE TITLE
HTTP MPEG TS stream opening twice.

### ISSUE THREAD

**Issue by ddv2005** [google/ExoPlayer#1646]
I found that HTTP MPEG TS streams opening two times. First time it opening on prepare in ExtractorSampleSource. After that ExtractorSampleSource trying to enable media tracking on on first track it restart stream and open it again:

```
  public void enable(int track, long positionUs) {
    Assertions.checkState(prepared);
    Assertions.checkState(!trackEnabledStates[track]);
    enabledTrackCount++;
    trackEnabledStates[track] = true;
    pendingMediaFormat[track] = true;
    pendingDiscontinuities[track] = false;
    if (enabledTrackCount == 1) {
      // Treat all enables in non-seekable media as being from t=0.
      positionUs = !seekMap.isSeekable() ? 0 : positionUs;
      downstreamPositionUs = positionUs;
      lastSeekPositionUs = positionUs;
      restartFrom(positionUs);
    }
  }

```

restartFrom(positionUs); is absolutely unnecessary if positionUs==0 

Dmitry

**Comment by AquilesCanta** [comment]
I may be wrong, but I think this is fixed in V2, coming soon. I don't know what you mean with "opening", though. I don't think the data source gets closed at any point between prepare and enable. @ojw28 and @andrewlewis have the last word on this, however.

**Comment by ddv2005** [comment]
Actually first connection got 100-300Kb before restart. But more important that it double server usage because every request very resource intensive on server side.

**Comment by ojw28** [comment]
Yes, this should be addressed in V2.

**Comment by ojw28** [comment]
Fixed in `dev-v2`, which is the V2 development branch.
