### ISSUE TITLE
Enabling bitrate selective feature

### ISSUE THREAD

**Issue by PooriaFarhad** [google/ExoPlayer#1655]
Hello,

Is there any way to add bitrate selective feature for playing HLS video?
Users should be able to change the quality of the video but I didn't find any related information in the documentations.

Thanks

**Comment by ojw28** [comment]
The ExoPlayer [demo app](https://github.com/google/ExoPlayer/tree/release-v2/demo) allows the user to select which quality is played (click the "Video" button during playback and you'll get a selection dialog). I suggest you take a look at the the demo app code to see how it works.
