### ISSUE TITLE
Switching streams takes time for short videos (10s) even on good quality network

### ISSUE THREAD

**Issue by narayanaraoR** [google/ExoPlayer#1657]
Hi,

I have developed an app that records and plays short videos (10 secs max). 
But what I have noticed is even for very good network speeds (50mbps) it takes atleast 12 secs before switching to a better quality stream (see the log below) which doesn't work for me as my videos are only 10s long. Even the demo player bahaves in the same manner, switching only after 12s. The minDurationForQualityIncreaseMs is also 1000ms to make the stream switch faster but it does n't help.
What can I customise to make it switch better?
Some of the values I use in DashRendererBuilder are as follows:

```
private static final int BUFFER_SEGMENT_SIZE = 64 * 1024;
    private static final int VIDEO_BUFFER_SEGMENTS = 50;
    private static final int AUDIO_BUFFER_SEGMENTS = 54;
    private static final int TEXT_BUFFER_SEGMENTS = 2;
    private static final int LIVE_EDGE_LATENCY_MS = 3000;

    private static final int maxInitialBitrate = 800000;
    private static final int  minDurationForQualityIncreaseMs = 1000;
    private static final int maxDurationForQualityDecreaseMs = 3000;
    private static final int minDurationToRetainAfterDiscardMs = 2000;
    private static final float bandwidthFraction = 0.75F;
```

**Log**
07-07 17:27:41.091 8567-8567/com.videoapp D/DemoPlayer: video size changed bandwidth 1056727
07-07 17:27:41.261 8567-8567/com.videoapp D/DemoPlayer: video size changed bandwidth 12224000
07-07 17:27:41.451 8567-8567/com.videoapp E/QuestViewingPlayer: video size changed to 320 \* 142
07-07 17:27:41.671 8567-8567/com.videoapp D/DemoPlayer: video size changed bandwidth 15677894
07-07 17:27:41.711 8567-8567/com.videoapp D/DemoPlayer: video size changed bandwidth 15677894
07-07 17:27:42.031 8567-8567/com.videoapp D/DemoPlayer: video size changed bandwidth 15677894
07-07 17:27:42.111 8567-8567/com.videoapp D/DemoPlayer: video size changed bandwidth 15677894
07-07 17:27:42.431 8567-8567/com.videoapp D/DemoPlayer: video size changed bandwidth 15677894
07-07 17:27:44.531 8567-8567/com.videoapp D/DemoPlayer: video size changed bandwidth 41652712
07-07 17:27:53.771 8567-8567/com.videoapp E/ViewingPlayer: video size changed to 1280*570
07-07 17:27:57.831 8567-8567/com.videoapp D/DemoPlayer: video size changed bandwidth 41652712
07-07 17:27:58.171 8567-8567/com.videoapp D/DemoPlayer: video size changed bandwidth 41652712
07-07 17:28:03.161 8567-8567/com.videoapp D/DemoPlayer: video size changed bandwidth 37094796

**Comment by ojw28** [comment]
In ExoPlayer V2 you can implement your own `TrackSelection` and use it in place of `AdaptiveVideoTrackSelection`. In your implementation you can choose to switch quality faster if you wish to do so. You can configure ExoPlayer V2 to use your custom implementation by passing a `TrackSelection.Factory` to the `DefaultTrackSelector` constructor that instantiates instances of it.
