### ISSUE TITLE
Support fragmented MP4 + CENC with HLS

### ISSUE THREAD

**Issue by nahojkap** [google/ExoPlayer#1661]
Hi,

What are the plans to support fragmented MP4 (to allow content sharing between for example DASH and HLS) as per [1] ?  Sample link at [2]

Thanks,

Johan

[1] https://bitmovin.com/hls-news-wwdc-2016/
[2] https://tungsten.aaplimg.com/VOD/bipbop_adv_fmp4_example/v1/prog_index.m3u8

**Comment by ojw28** [comment]
This is on our radar and we'll use this issue to track the feature. We don't have a concrete plan at the moment, but we'd like to provide support. We're not yet decided on exactly what level of support we'll provide (e.g. we may opt to support only demuxed media chunks, as we do for DASH and SmoothStreaming).

We'd also hope that the majority of streaming providers will be able to serve DASH manifests in addition to HLS playlists, with both pointing to the same media chunks. In this scenario we'd recommend using DASH manifests for ExoPlayer.

**Comment by nahojkap** [comment]
Ok, thanks for the quick response.

Johan

**Comment by ojw28** [comment]
Some functionality added with https://github.com/google/ExoPlayer/commit/6306c269885475c0a6f947245ed19b60a010ccfd.

**Comment by cskinfill** [comment]
Does Exoplayer support fMP4 with HLS?  If so, which version of exoplayer is required?

**Comment by AquilesCanta** [comment]
r2.0.2 is the earliest one that includes it, but many features and bugfixes have been added in the later versions. I strongly suggest you update to the latest exoplayer version, if possible.

**Comment by ojw28** [comment]
Further changes in: https://github.com/google/ExoPlayer/commit/6314a0ec82343ee79075e7f8794a69471599b019

**Comment by ojw28** [comment]
@AquilesCanta - Can this be closed now? I think we're supporting this in `dev-v2` at this point?

**Comment by AquilesCanta** [comment]
Yes, I will keep adding minor improvements, but done.
