### ISSUE TITLE
autostart

### ISSUE THREAD

**Issue by dolar2006** [google/ExoPlayer#1664]
how to prevent autostart? (disable)

**Comment by AquilesCanta** [comment]
You mean something like setting playWhenReady as false?

**Comment by ojw28** [comment]
Playback is started only if `setPlayWhenReady(true)` is called on the player (which happens [here](https://github.com/google/ExoPlayer/blob/master/demo/src/main/java/com/google/android/exoplayer/demo/PlayerActivity.java#L371) in the ExoPlayer demo app). If you don't this behavior, simply don't make that call.
