### ISSUE TITLE
 How to provide a local Key to HLS for decrypting

### ISSUE THREAD

**Issue by biezhihua** [google/ExoPlayer#1665]
Hi:

My is developer from china. 
I have searched a list of questions, but did not find what I want.

How to provide a local Key to HLS for decrypting.

I found HlsChunkSourcel class newEncryptionKeyChunk method provides for decrypting the block, which by default is downloaded from the network key.

I want to use ByteArrayDataSource to provide a local Key, but I found newEncryptionKeyChunk is a private method, I can not override it to provide my key.

Hoping to get a reply, thank you

**Comment by biezhihua** [comment]
My English is very bad, please forgive me

**Comment by ojw28** [comment]
This is not something we support, so you'll have to take ExoPlayer as source and modify it to your needs if you want to do this.
