### ISSUE TITLE
How to generate a thumbnail?

### ISSUE THREAD

**Issue by Kisty** [google/ExoPlayer#1670]
ExoPlayer: 1.5.9

Am trying to make a video thumbnail from Android framewoork's ThumbnailUtils.createVideoThumbnail() but it doesn't support mp4v-es2 format. Am using ExoPlayer to show the video so is there an API to generate one? If not how would I go about doing it? I'd like to show multiple clips and I did notice the multiple ExoPlayer instances limitation (4 currently). Could I use one ExoPlayer instance to render all the clip thumbnails?

Thanks!

**Comment by andrewlewis** [comment]
For capturing the current frame, see #418.

You can reuse the player by calling stop, seekTo and prepare, passing renderers reading the new source. Note that there are some caveats to using more than one platform video decoder at a time; see #1286.
