### ISSUE TITLE
Anyway to access the underlying AudioTrack object that the MediaCodecAudioTrackRenderer uses?

### ISSUE THREAD

**Issue by KelvinJin** [google/ExoPlayer#1672]
I have a use case where I need to register periodic callbacks along with the playback. I know that you can achieve this by using `setPlaybackPositionUpdateListener` on the AudioTrack object. So I wonder whether this is possible when I use `MediaCodecAudioTrackRenderer`. (I did look at the code and realised that the audioTrack property is private...)

**Comment by ojw28** [comment]
Please see: https://github.com/google/ExoPlayer/issues/280
