### ISSUE TITLE
MediaCodecAudioTrackRenderer doesn't support AC3 audio codec

### ISSUE THREAD

**Issue by ElioTohm** [google/ExoPlayer#1673]
using ExtractorRendererBuilder class as an example any media with audio codec AC3 will throw the STATE_ENDED

**Comment by andrewlewis** [comment]
If the device has a decoder for AC-3 MediaCodecAudioTrackRenderer will use it, but few devices support this.

MediaCodecAudioTrackRenderer also supports passthrough of AC-3 audio if the device is running Android Lollipop (or later) and is connected to a receiver via HDMI. See also #722.
