### ISSUE TITLE
Streaming not smoothly (DRM-Widewine)

### ISSUE THREAD

**Issue by teokw90** [google/ExoPlayer#1674]
I am using exo player (version 1.5.4) for my application. But I found that streaming not smoothly when i try to stream certain content with DRM (widewine) in the following device model:
- Samsung Galaxy Tab S2 8.0
- Sony Xperia XA

May I know any solution when we facing similar issue?

**Comment by ojw28** [comment]
There was a Sony specific performance issue for Sony devices running Android 5.1.1, so if your Xperia is running that version of Android this could be the problem. As far as I'm aware, they fixed it in more recent OS updates. See https://github.com/google/ExoPlayer/issues/816 for details.

I'm not sure about the Tab. You haven't provided sufficient information, as is requested in the issue template, for us to investigate further.

**Comment by ojw28** [comment]
Closing due to lack of information requested in the issue template.
