### ISSUE TITLE
How can i remove notification bar display.

### ISSUE THREAD

**Issue by alphaDroid89** [google/ExoPlayer#1676]
Hi, How can i show/Hide notification panel display of a the
![device-2016-07-14-222914](https://cloud.githubusercontent.com/assets/1718991/16848282/ad90127a-4a12-11e6-8677-088c701eed79.png)
 player.

**Comment by AquilesCanta** [comment]
I'd suggest trying a general programming Q&A. We avoid answering these kind of queries in the issue tracker.

**Comment by AquilesCanta** [comment]
Courtesy of @andrewlewis:
https://developer.android.com/training/system-ui/status.html

**Comment by alphaDroid89** [comment]
@AquilesCanta : sorry, can you please refer my update. I don't need to show while playing video/audio.

**Comment by AquilesCanta** [comment]
I am sorry but I don't quite understand what I have to see in the provided screenshot. Even with more information, as I said before, it is not the purpose of this issue tracker to debug apps from users. Unfortunately, unless you have a bug to report or a feature request, we cannot help you as this is not exoplayer specific.

**Comment by jaydeep911** [comment]
Exoplayer notification
I just dont want this above notification.
What i have to do for this.

**Comment by ojw28** [comment]
ExoPlayer doesn't create or display any notifications. Where-ever that notification is coming from, it's not coming directly from the ExoPlayer library.
