### ISSUE TITLE
MPEG TS trackCount doesn't read all tracks

### ISSUE THREAD

**Issue by GoranNSW** [google/ExoPlayer#1677]
Hi,

I'm using DemoPlayer for playing MPEG TS stream but I'm unable to find a way to search for all available tracks. TrackCount always returns one track for video, and one for audio although there are more audio tracks or subtitle tracks. Also, DVB subtitle tracks are not recognized at all.

Is there a way to use TsExtractor class to list all tracks by their PID's and display their description?

**Comment by AquilesCanta** [comment]
I will look into this, could you also provide a link or a file to reproduce the issue? If you'd rather not make it public, please send it to dev.exoplayer@gmail.com

**Comment by GoranNSW** [comment]
I can't post files here so I sent you an email with samples.
Thank you in advance.

**Comment by GoranNSW** [comment]
I have been searching for days to find how to list all tracks and still can't figure out how to do it. Is there any way to find all tracks that are available in MPEG TS stream?

**Comment by AquilesCanta** [comment]
Yes, I am sorry about this delay. I am currently working on our HLS implementation. As soon as I finish this work, I hope next week, I will get to this.

**Comment by GoranNSW** [comment]
It was not my intention to put pressure on you, I was just hoping that the solution is less complicated and that I could help.

**Comment by AquilesCanta** [comment]
This will be supported in the next push, both versions. Sorry for the delay.

NOTE that we still don't support multiple CC services, but I plan to add this relatively soon. Thanks for the samples.

**Comment by GoranNSW** [comment]
Thank you very much, that's great news!

If you need some more samples I will do my best to find them.

**Comment by AquilesCanta** [comment]
I will probably reach out when I start working on multiple CC services support. Thanks!

**Comment by ojw28** [comment]
Assuming this is fixed based on the comments above.
