### ISSUE TITLE
[dev-2.X.X-experimental] seekTo only seek in the last file if there are multiple files in playlist.

### ISSUE THREAD

**Issue by mingchen** [google/ExoPlayer#1678]
**Version:**
branch dev-2.X.X-experimental commit dbb43567a33a6cb3cb511a76c21d26f8d72ee8fe

**Android OS:**
Nexus 5 Android 6.0

**Description:**
I have multiple video files in a playlist and play it well, however when I call seekTo(0), I expected this should be play from the very beginning of first file, however it only seek to the very beginning of the last file.

**Comment by andrewlewis** [comment]
You can specify the period (playlist item) to seek to if you use [seekTo(int periodIndex, long positionMs)](https://github.com/google/ExoPlayer/blob/dev-2.X.X-experimental/library/src/main/java/com/google/android/exoplayer2/ExoPlayer.java#L293). For example, to seek back to the start of the first period you can call seekTo(0, 0). The other variant of seekTo seeks relative to the start of the currently-playing period. There are still a few known issues with seeking in playlists, which we're working on, so this may not work perfectly yet.

**Comment by mingchen** [comment]
Thank you. Good to know there is a new API.
