### ISSUE TITLE
Override forward and rewind button of Tv remote

### ISSUE THREAD

**Issue by Samyak81** [google/ExoPlayer#1679]
How can I override forward and rewind button of tv remote. as i can not override tv remote controls.

**Comment by andrewlewis** [comment]
The KeyCompatibleMediaController in [PlayerActivity.java](https://github.com/google/ExoPlayer/blob/master/demo/src/main/java/com/google/android/exoplayer/demo/PlayerActivity.java#L728) should handle fast forward and rewind. Hopefully you can use that as a starting point.
