### ISSUE TITLE
Implement multiple audio tracks support for local media stream

### ISSUE THREAD

**Issue by xiangchun** [google/ExoPlayer#168]
I checked ExoPlayer, it implements MultiTrackChunkSource to support multiple audio tracks on master branch.
But how to implement multiple audio tracks support for local media stream, for example, I have a stream which contains :

General
Unique ID                                : 251352275511766917962423227176409075865 (0xBD18AFF96EE4BCA592507D6EF40F9099)
Complete name                            : D:\media\multi-audio-subtitle\MKV_MPEG2_Main@High_1920x1080_23.976fps_9audio.mkv
Format                                   : Matroska
Format version                           : Version 1
File size                                : 670 MiB
Duration                                 : 2mn 18s
Overall bit rate mode                    : Variable
Overall bit rate                         : 40.5 Mbps
Encoded date                             : UTC 2009-03-31 04:01:03
Writing application                      : mkvmerge v2.6.0 ('Kelly watch the Stars') built on Mar 24 2009 15:23:17
Writing library                          : libebml v0.7.7 + libmatroska v0.8.1

Video
ID                                       : 1
Format                                   : MPEG Video
Format version                           : Version 2
Format profile                           : Main@High
Format settings, BVOP                    : No
Format settings, Matrix                  : Custom
Codec ID                                 : V_MPEG2
Codec ID/Info                            : MPEG 1 or 2 Video
Duration                                 : 2mn 18s
Bit rate mode                            : Variable
Maximum bit rate                         : 35.0 Mbps
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 23.976 fps
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Compression mode                         : Lossy
Time code of first frame                 : 01:02:59:00
Time code source                         : Group of pictures header
Default                                  : Yes
Forced                                   : No

Audio #1
ID                                       : 2
Format                                   : PCM
Codec ID                                 : A_PCM/INT/LIT
Duration                                 : 2mn 18s
Bit rate mode                            : Constant
Channel(s)                               : 6 channels
Sampling rate                            : 48.0 KHz
Bit depth                                : 16 bits
Title                                    : PCM
Default                                  : Yes
Forced                                   : No

Audio #2
ID                                       : 3
Format                                   : DTS
Format/Info                              : Digital Theater Systems
Format profile                           : MA / Core
Mode                                     : 16
Format settings, Endianness              : Big
Codec ID                                 : A_DTS
Duration                                 : 2mn 18s
Bit rate mode                            : Variable
Bit rate                                 : Unknown / 1 509 Kbps
Channel(s)                               : 6 channels
Channel positions                        : Front: L C R, Side: L R, LFE
Sampling rate                            : 48.0 KHz
Bit depth                                : 16 bits
Compression mode                         : Lossless / Lossy
Title                                    : DTS
Default                                  : No
Forced                                   : No

Audio #3
ID                                       : 4
Format                                   : AC-3
Format/Info                              : Audio Coding 3
Mode extension                           : CM (complete main)
Format settings, Endianness              : Big
Codec ID                                 : A_AC3
Duration                                 : 2mn 18s
Bit rate mode                            : Constant
Bit rate                                 : 640 Kbps
Channel(s)                               : 6 channels
Channel positions                        : Front: L C R, Side: L R, LFE
Sampling rate                            : 48.0 KHz
Bit depth                                : 16 bits
Compression mode                         : Lossy
Stream size                              : 10.6 MiB (2%)
Title                                    : AC3
Default                                  : No
Forced                                   : No

Audio #4
ID                                       : 5
Format                                   : AAC
Format/Info                              : Advanced Audio Codec
Format profile                           : LC
Codec ID                                 : A_AAC
Duration                                 : 2mn 18s
Channel(s)                               : 6 channels
Channel positions                        : Front: L C R, Side: L R, LFE
Sampling rate                            : 48.0 KHz
Compression mode                         : Lossy
Title                                    : AACLC
Default                                  : No
Forced                                   : No

Audio #5
ID                                       : 6
Format                                   : AAC
Format/Info                              : Advanced Audio Codec
Format profile                           : HE-AAC / LC
Codec ID                                 : A_AAC
Duration                                 : 2mn 18s
Channel(s)                               : 6 channels
Channel positions                        : Front: L C R, Side: L R, LFE
Sampling rate                            : 48.0 KHz / 24.0 KHz
Compression mode                         : Lossy
Title                                    : AACHE
Default                                  : No
Forced                                   : No

Audio #6
ID                                       : 7
Format                                   : FLAC
Format/Info                              : Free Lossless Audio Codec
Codec ID                                 : A_FLAC
Duration                                 : 2mn 18s
Bit rate mode                            : Variable
Channel(s)                               : 6 channels
Sampling rate                            : 48.0 KHz
Bit depth                                : 16 bits
Title                                    : FLAC
Writing library                          : libFLAC 1.1.4 (UTC 2007-02-13)
Default                                  : No
Forced                                   : No

Audio #7
ID                                       : 8
Format                                   : WMA
Format profile                           : Lossless
Codec ID                                 : A_MS/ACM / 163
Codec ID/Info                            : Windows Media Audio
Duration                                 : 2mn 18s
Bit rate                                 : 1 152 Kbps
Channel(s)                               : 6 channels
Sampling rate                            : 48.0 KHz
Bit depth                                : 24 bits
Stream size                              : 19.0 MiB (3%)
Title                                    : Wma9.2Lossless
Language                                 : English
Default                                  : No
Forced                                   : No

Audio #8
ID                                       : 9
Format                                   : WMA
Format profile                           : Pro
Codec ID                                 : A_MS/ACM / 162
Codec ID/Info                            : Windows Media Audio
Duration                                 : 2mn 18s
Bit rate                                 : 768 Kbps
Channel(s)                               : 6 channels
Sampling rate                            : 48.0 KHz
Bit depth                                : 24 bits
Stream size                              : 12.7 MiB (2%)
Title                                    : Wma10Pro
Language                                 : English
Default                                  : No
Forced                                   : No

Audio #9
ID                                       : 10
Format                                   : Vorbis
Format settings, Floor                   : 1
Codec ID                                 : A_VORBIS
Duration                                 : 2mn 18s
Bit rate mode                            : Variable
Bit rate                                 : 480 Kbps
Channel(s)                               : 6 channels
Sampling rate                            : 48.0 KHz
Compression mode                         : Lossy
Stream size                              : 7.94 MiB (1%)
Title                                    : OGGVorbis
Writing library                          : libVorbis 1.0 (UTC 2002-07-17)
Default                                  : No
Forced                                   : No

**Comment by ojw28** [comment]
This is now tracked by #514.
