### ISSUE TITLE
UHD display detection not working correctly on Sony AndroidTV utilizing Android 6.0

### ISSUE THREAD

**Issue by bartsidee** [google/ExoPlayer#1685]
We noticed that 4k content did not switch correctly to 4k resolutions utilising Sony AndroidTV models that have the new Android 6.0 firmware, the max was FullHD. This was working correctly on Sony AndroidTV utilising Android 5.0/5.1 firmware.

After investigation with Sony the issue is caused by the getViewportSize method. Exoplayer is using a sony specific device check for SDK version 22:
https://github.com/google/ExoPlayer/blob/42e5d5c2e61d2715d62d715bbd92b715e7f78f88/library/src/main/java/com/google/android/exoplayer/chunk/VideoFormatSelectorUtil.java#L202

But for SDK version 23 it is using the 'new' getPhysicalWidth/getPhysicalHeight properties:
https://github.com/google/ExoPlayer/blob/42e5d5c2e61d2715d62d715bbd92b715e7f78f88/library/src/main/java/com/google/android/exoplayer/chunk/VideoFormatSelectorUtil.java#L226

Unfortunately the getPhysicalWidth/getPhysicalHeight are not returning 4k values on Sony devices, the reason is that Sony renders the Android UI on 2k resolution on all UHD compatible sets. So getPhysicalWidth/getPhysicalHeight will not output 3840,2160 but instead 1920,1080 on Sony devices.

Our request would be to remove the SDK check for Sony AndroidTV and apply the original Sony display detection for all Android versions:
https://github.com/google/ExoPlayer/blob/42e5d5c2e61d2715d62d715bbd92b715e7f78f88/library/src/main/java/com/google/android/exoplayer/chunk/VideoFormatSelectorUtil.java#L202

**Comment by ojw28** [comment]
> Unfortunately the getPhysicalWidth/getPhysicalHeight are not returning 4k values on Sony devices, the reason is that Sony renders the Android UI on 2k resolution on all UHD compatible sets

I don't really understand this statement. The whole point of those APIs is for them to report the actual display mode, which can have a different resolution to the UI (which is returned by getWidth/getHeight).

**Comment by ojw28** [comment]
Following up internally to work out if (a) the API is broken as I think it is, (b) whether it's Google or OEM code that's responsible if so, and (c) when we can expect it to be fixed. Once we have some clarity here, we'll extend the workaround if appropriate to API levels up to the one in which we expect a fix to land.

We believe a similar issue may also affect nVidia SHIELD, so we're taking a look at that too.

**Comment by ojw28** [comment]
We will be updating the Sony specific check to apply up to (and including) API level 24. We expect that getPhysicalWidth/Height will work correctly from API level 25 onward. We will also be adding a similarly specific check for nVidia SHIELD devices.

**Comment by ojw28** [comment]
Changes have been pushed to `dev-v1` and `dev-v2` to fix this.
