### ISSUE TITLE
How Save State of ExoPlayer

### ISSUE THREAD

**Issue by zaky295** [google/ExoPlayer#1687]
I Integrated Exoplayer and it's runs well, but when i integrated with my app then it's state is not save and when device is roted video is play from start so how to save player state.

**Comment by ojw28** [comment]
You can do what the demo app does and handle the rotation yourself, which avoids Activity recreation and hence the need to save and restore state. This is achieved [here](https://github.com/google/ExoPlayer/blob/r1.5.9/demo/src/main/AndroidManifest.xml#L44).

Else, you'll have to use the normal save/restore functionality provided by Activity to do this. ExoPlayer provides sufficient methods for you to query, for example, the current playback position, and restore it again in the recreated Activity.
