### ISSUE TITLE
NullPointerException when playing  HLS source in r1.3.3

### ISSUE THREAD

**Issue by VesnaRistevska** [google/ExoPlayer#1696]
I keep getting the following NullPointer exception with HLS stream. I'm using version r1.3.3 

/ExoPlayerImplInternal: Internal runtime error. java.lang.NullPointerException: Attempt to invoke interface          method 'void com.google.android.exoplayer.ExoPlayer$ExoPlayerComponent.handleMessage(int,    java.lang.Object)' on a null object reference at com.google.android.exoplayer.ExoPlayerImplInternal.sendMessageInternal(ExoPlayerImplInternal.java:591at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:229)  at android.os.Handler.dispatchMessage(Handler.java:98)
at android.os.Looper.loop(Looper.java:148) 
at android.os.HandlerThread.run(HandlerThread.java:61)
at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)

**Comment by ojw28** [comment]
1.3.3 is very old. Please try a more recent version and file a new issue if you're still having problems.
