### ISSUE TITLE
setBackgrounded(true) not working as expected in HLS video. (Video and audio downloading mismatch, while coming back to activity )

### ISSUE THREAD

**Issue by saurabhkpatel** [google/ExoPlayer#1698]
@ojw28 Need your comments or suggestions, on below issue.

I am trying to run background audio playback when a user leaves video player activity. I wrote service for that and I am handling ExoPlayer in service, Background play is working fine when I leave application at that time I am setting **"setBackgrounded(true)"** . When I am returning back to an application and open video player activity, here first I am checking if something is playing or not in service, if yes then use **"setBackgrounded(false)"** and attach surfaceView to show video.

In the above-described method, I am facing two problems, which I discussed below.

**Reproduce steps in ExoPlayer demo application :**

1) Start demo application, go **HLS** section, select first video name **"Apple master playlist".**
2) play this video.
3) pause this video at any time and note down MM:SS from seekbar and video display. [refer before.png]
4) Press home screen, by doing this activity goes to onResume() method and below code will be executed 

```
if (!enableBackgroundAudio) {
  releasePlayer();
} else {
  player.setBackgrounded(true);
}
shutterView.setVisibility(View.VISIBLE);
}
```

Note : It will set player in background mode as I enabled enableBackgroundAudio=true.

5) After few seconds come back to ExoPlayer Demo application by pressing "Overview" button and select ExoPlayer from it. Now compare seek-bar time and time which video frame displays. [Refer after.png file]

**Problem 1** : Both are different, now press the play button and you can see video frame will not refresh until seek bar will not sync with it.

It means the video frames are still downloading/rendering when a player is paused and **setBackgrounded** is **true**.

**Problem 2** : In step three if we won't pause a video and put an application in background mode and come back to the application, audio is playing and it's perfectly fine but when I came back to exoplayer demo application (foreground mode), I can see video frame is getting freeze for few seconds (5-6 seconds, sometimes I can see only black screen). It will be in sync with the seek bar after few seconds. (In this case also, audio and video downloading rate are different.)

Is this problem of audio and video downloading mismatch or video downloading happening with pause and setBackgrounded(true).

There any workaround to solve this problem?

You can find changes in demo application over here : https://github.com/saurabhkpatel/ExoPlayer/commit/78b7c66e6e7284afd7e23ddf7a439cee42462950

Attachments :

Before.png

![before](https://cloud.githubusercontent.com/assets/1188367/17121656/1237402a-528a-11e6-82e9-43082632b893.png)

After.png

![after](https://cloud.githubusercontent.com/assets/1188367/17121666/1d535a34-528a-11e6-8ad0-16111f8212bf.png)

**Comment by saurabhkpatel** [comment]
@ojw28  Is there any update on this issue, I posted 1 week before. If you require more information about this then please let me know i can provide you more details.

**Comment by ojw28** [comment]
This is basically boils down to being able to smoothly switch/detach/attach surfaces, which is discussed and tracked in https://github.com/google/ExoPlayer/issues/677.

Note: You appear to be using ExoPlayer V1 still, which is pretty old at this point. You should consider migrating to V2, where we've been making improvements in this area.

**Comment by saurabhkpatel** [comment]
@ojw28 : First of thanks for your reply on this thread after more than 11 Months. I reported this issue last summer at that time version 2 was not out.
I will try with version 2 and update the information in the new thread if require.
