### ISSUE TITLE
Multiple software decoder based instances - Android 5.1(API22)

### ISSUE THREAD

**Issue by brystel** [google/ExoPlayer#1700]
Hi,

I am reffering to #1357 

I got the same issue with initialize **OMX.google.h264.decoder** when I try to use multiple instances.

I have tested it on six real devices and it seems that ExoPlayer won't initialize software decoder only on devices with Android 5.1 (API 22). 

With android 4.4 and 6.0 software decoder work well.

Please note that I have successfully run 3 and more software decoder based instances with another library based on FFmpeg (on all devices).

I am using ExoPlayer r1.5.9.

I am attaching logs from device with android 5.1

> E/OMXMaster: A component of name 'OMX.google.h264.decoder' already exists, ignoring this one.
> E/OMXMaster: A component of name 'OMX.google.alac.decoder' already exists, ignoring this one.
> W/OMXNodeInstance: [1:google.h264.decoder] component does not support metadata mode; using fallback
> E/ACodec: [OMX.google.h264.decoder] storeMetaDataInBuffers failed w/ err -1010
> D/EventLogger: decoderInitialized [1.43, OMX.google.h264.decoder]
> I/OMXClient: Using client-side OMX mux.
> I/omx_core: OMX_Init 66 gInitCount=4
> E/OMXMaster: A component of name 'OMX.google.h264.decoder' already exists, ignoring this one.
> E/OMXMaster: A component of name 'OMX.google.alac.decoder' already exists, ignoring this one.
> D/EventLogger: decoderInitialized [1.44, OMX.google.aac.decoder]
> I/SoftAAC2: limiting to stereo output
> I/SoftAAC2: Reconfiguring decoder: 0->48000 Hz, 0->2 channels
> I/AudioTrack: set(): 0xabc2dbe0 streamType -1, sampleRate 48000, format 0x1, channelMask 0x3, frameCount 16384, flags #0, notificationFrames 0, sessionId 0, transferType 3
> E/SoftAVC: Decoder failed: -2
> E/ACodec: [OMX.google.h264.decoder] ERROR(0x80001001)
> E/ACodec: signalError(omxError 0x80001001, internalError -2147483648)
> E/MediaCodec: Codec reported err 0x80001001, actionCode 0, while in state 6
> E/ExoPlayerImplInternal: Internal runtime error.
>                                                                        java.lang.IllegalStateException
>                                                                            at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
>                                                                            at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:1037)
>                                                                            at com.google.android.exoplayer.MediaCodecTrackRenderer.drainOutputBuffer(MediaCodecTrackRenderer.java:890)
>                                                                            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:512)
>                                                                            at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:129)
>                                                                            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:434)
>                                                                            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
>                                                                            at android.os.Handler.dispatchMessage(Handler.java:98)
>                                                                            at android.os.Looper.loop(Looper.java:135)
>                                                                            at android.os.HandlerThread.run(HandlerThread.java:61)
>                                                                            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
> I/omx_core: OMX_Deinit 96 gInitCount=3

**Comment by andrewlewis** [comment]
Unfortunately there's not much we can do about errors like this. It's likely caused by running out of resources or a platform bug (or both).

Bundling your own software decoder will help reduce the dependency on the platform so you should see more consistent behavior on different Android versions. It sounds like you have found that FFmpeg works fine.

Please be warned that software video decoders can be quite inefficient and slow compared with decoders that are hardware-accelerated. Also, decoding multiple high resolution videos can consume a lot of memory, as each video's reference frames need to be stored as bitmaps. So make sure you play the lowest resolution videos possible for your use case.
