### ISSUE TITLE
Segments from different video cached into same cache file

### ISSUE THREAD

**Issue by yhd4711499** [google/ExoPlayer#1705]
**A description of the issue**
I use this code in demo app to enable caching for DASH video:

``` java
// PlayerActivy onCreate
final DefaultDataSourceFactory defaultMediaDataSourceFactory
            = new DefaultDataSourceFactory(this, userAgent, BANDWIDTH_METER);
    mediaDataSourceFactory = new DataSource.Factory() {
      @Override
      public DataSource createDataSource() {
        LeastRecentlyUsedCacheEvictor evictor = new LeastRecentlyUsedCacheEvictor(100 * 1024 * 1024);
        SimpleCache simpleCache = new SimpleCache(new File(getCacheDir(), "media_cache"), evictor);
        DefaultDataSource upstream = defaultMediaDataSourceFactory.createDataSource();
        return new CacheDataSource(simpleCache, upstream, false, false);
      }
    };
```

I did some researching and found that the `DashManifestParser.contentId` is not set to any value and remains `null` when it's used for setting `DataSpec.key`, which makes it possible for segments from different video cached into same cache file.

**Steps to reproduce**
1. Enable cache
2. Play some dash video

**Info**
Device: Nexus 5X running Android 6.0.0
ExoPlayer: dev2 (rev: 846f8e1d4685822d4816504127be1b3f4656b886)

**Comment by ojw28** [comment]
The application is ultimately responsible for providing the `contentId`, but you'd be correct to observe that there's no way to do this currently in V2. We'll enable this again (and possibly use the hash of the Uri as a default if the app doesn't specify one explicitly).

**Comment by danrossi** [comment]
@ojw28 I believe this is the best place for this. There is currently zero usage how CacheDataSource works. 

In the demo app there is the Dash code like this. 

```
 return new DashMediaSource(uri, buildDataSourceFactory(false),
            new DefaultDashChunkSource.Factory(mediaDataSourceFactory), mainHandler, eventLogger);
```

is buildDataSourceFactory supposed to be replaced with that code above  ? Is it possible setting the right cache key now ? 

I am hoping this is the right method for offline playback ?

**Comment by scrdev** [comment]
@ojw28 is it currently possible to set the contentId used to create the key ? I believe exoplayer now uses the Uri as default contentId which causes same videos to be cached multiple times if the Uri is different which can be quite ineffective, how can I avoid this ?

**Comment by ojw28** [comment]
@danrossi - The caching functionality is not yet packaged up in a way that enables for easy offline use (it is possible to build offline functionality on top and Google Play Movies does this, but it's quite complicated and custom to the individual app). We are working toward more comprehensive offline support, but it's very complicated to cover all use cases and so will take some time.
@scroozer - What type of media are you trying to play (i.e. what MediaSource implementation are you passing to the player)?

**Comment by scrdev** [comment]
@ojw28 I am currently using ExtractorMediaSource `MediaSource videoSource = new ExtractorMediaSource(Uri.parse(url),dataSourceFactory, extractorsFactory, null, null);` and passing it to the player.

**Comment by ojw28** [comment]
Right, there is currently no way to specify a key for that use case. I filed #2201 to track supporting this.

**Comment by ojw28** [comment]
I believe this is fixed now. You're able to pass your own `DashManifestParser` into the `DashMediaSource` constructor, and you can pass your own custom contentId to the `DashManifestParser` constructor. Even if you don't specify a custom contentId, I think we now end up using the content uri by default.
