### ISSUE TITLE
Video rotated 90 degrees in a playlist

### ISSUE THREAD

**Issue by mingchen** [google/ExoPlayer#1707]
**Code version:** 
dev-v2 commit 846f8e1d

**Device:**
Nexus 5 / Android 6.0

**Descrtiption:**
In ExoPlayer 2 play list, I have a phone recorded vertical screen video, when play in the middle of playlist, it will be rotate 90 degrees and stretched which is not expected. If it is the first of list, it plays normal.

**Reproduce issue:**
I have a [demo video](https://dl.dropboxusercontent.com/u/65653901/ExoPlayer2/772908b1-8076-41f1-8e02-508206b6efbb.mp4) show this issue, there is code changes to reproduce the issue:

```
--- a/demo/src/main/assets/sample_media.exolist.json
+++ b/demo/src/main/assets/sample_media.exolist.json
@@ -368,6 +368,9 @@
         "uri": "http://html5demos.com/assets/dizzy.mp4"
       },
       {
+            "uri": "https://dl.dropboxusercontent.com/u/65653901/ExoPlayer2/772908b1-8076-41f1-8e02-508206b6efbb.mp4"
+          },
+          {
         "uri": "http://storage.googleapis.com/exoplayer-test-media-1/mkv/android-screens-lavf-56.36.100-aac-avc-main-1280x720.mkv"
       }
     ]
```

If I put the video in the first with following code changes, there is no issue on the first video, however the next two videos are rotated 90 degrees:

```
--- a/demo/src/main/assets/sample_media.exolist.json
+++ b/demo/src/main/assets/sample_media.exolist.json
@@ -365,6 +365,9 @@
     "name": "Cats -> Dogs",
     "playlist": [
       {
+            "uri": "https://dl.dropboxusercontent.com/u/65653901/ExoPlayer2/772908b1-8076-41f1-8e02-508206b6efbb.mp4"
+          },
+          {
         "uri": "http://html5demos.com/assets/dizzy.mp4"
       },
       {
```

**Comment by ojw28** [comment]
Thanks for reporting this! It's most likely a device/platform issue rather than an issue in ExoPlayer, but we should be able to work around the problem fairly easily.

Did you test this on any other devices at all? If so, could you let us know whether behavior was as expected, or whether this issue was the same across all devices. Thanks!

**Comment by mingchen** [comment]
I also tested on Moto XT 1527 / Android 5.1, Sony Xperia S LT26i / Android 4.1.2 and HTC One Max / Android 5.0.1, it have the same issue.
What is the workaround ?
