### ISSUE TITLE
Subtitles style is not rendered correctly

### ISSUE THREAD

**Issue by ludovicroland** [google/ExoPlayer#1710]
**A description of the issue :**  Subtitles style is not always rendered correctly.

Here the code for the default style and the render :

``` java
public void configureSubtitlesLayout()
{
  final CaptionStyleCompat captionStyle = CaptionStyleCompat.DEFAULT;
  final float captionFontScale = 1.0f;

  subtitlesLayout.setStyle(captionStyle);
  subtitlesLayout.setFractionalTextSize(captionFontScale);
}
```

![subtitles1](https://cloud.githubusercontent.com/assets/3648438/17325230/ce6cc29e-58aa-11e6-86c0-cff386a55988.jpg)

And here a custom style with the render :

``` java
public void configureSubtitlesLayout()
{
  final CaptionStyleCompat userStyle = getUserCaptionStyleV19();
  final CaptionStyleCompat captionStyle= = new CaptionStyleCompat(Color.RED, Color.TRANSPARENT, Color.TRANSPARENT, CaptionStyleCompat.EDGE_TYPE_NONE, Color.BLACK, userStyle.typeface);
  final float captionFontScale = getUserCaptionFontScaleV19();

  subtitlesLayout.setStyle(captionStyle);
  subtitlesLayout.setFractionalTextSize(captionFontScale);
}

@TargetApi(19)
private float getUserCaptionFontScaleV19()
{
  final CaptioningManager captioningManager = (CaptioningManager) context.getSystemService(Context.CAPTIONING_SERVICE);
  return captioningManager.getFontScale();
}

@TargetApi(19)
private CaptionStyleCompat getUserCaptionStyleV19()
{
  final CaptioningManager captioningManager = (CaptioningManager) context.getSystemService(Context.CAPTIONING_SERVICE);
  return CaptionStyleCompat.createFromCaptionStyle(captioningManager.getUserStyle());
}
```

I still have the black blakcground even if it specifies `Color.TRANSPARENT` and the foreground color is still white even it specifies `Color.RED`.

![subtitles2](https://cloud.githubusercontent.com/assets/3648438/17325303/264338ea-58ab-11e6-93c2-700c694326aa.jpg)

I do not face this issue on all contents. The subtitles are provided by the the manifest of an ism file.

**The version of ExoPlayer being used :** 1.5.8

**The device(s) and version(s) of Android on which the issue can be reproduced,
  and how easily it reproduces. If possible, please test on multiple devices and
  Android versions.** : Nexus 5x on Android 6.0.1

**Comment by ojw28** [comment]
Most likely the subtitles include their own embedded styling information, which is applied in preference to the locally configured style by default. If you want to disable application of embedded styling information you can call `subtitlesLayout.setApplyEmbeddedStyles(false)`. Please give this a try and let us know if it helps! Thanks.

**Comment by ludovicroland** [comment]
Hi @ojw28,

Thx you so much for your help ! It works !
