### ISSUE TITLE
Mpeg-Dash stream start offset

### ISSUE THREAD

**Issue by brystel** [google/ExoPlayer#1711]
Hi,

Is there (r1.5.9) possibility to change start offset in dash live stream?
Video which is shown is behind ~40s of current time.

Thank you

**Comment by stelma** [comment]
I think that should be the live edge latency. I guess it should still be in the DashRendererBuilder as final static member.

**Comment by AquilesCanta** [comment]
Yes, sorry I hadn't seen this. As @stelma says, there is a parameter for this in the DashChunkSource constructor. You could try changing the value you are using. You should try posting this kind of questions in a general Q&A site, as the issue tracker is preferably reserved for bug reporting and feature requests.
