### ISSUE TITLE
Subtitle Erroneous Characters

### ISSUE THREAD

**Issue by cstew** [google/ExoPlayer#1712]
In certain situations, ExoPlayer is showing erroneous characters around subtitles. I think this is related to the font tag embedded within subtitles on the video. 

We have a video from a vendor where the font tag with a size attribute is used and we are seeing an additional character at the front of the subtitle. I've stripped down the subtitles from that video and reproduced with the font color attribute (this time with additional characters after the subtitle). 

Is there some workaround for this issue? I don't particularly care for support for the font tag, but I would like to figure out a way to show the correct subtitle text. 

Here is a sample mp4 file that reproduces the problem: https://www.dropbox.com/s/rklo2hg5nsb164e/subtitles.mp4?dl=1

Here is the .srt file that I used:
https://www.dropbox.com/s/20yqtpwetuz5db0/subtitles.srt?dl=1

![device-2016-08-02-111857](https://cloud.githubusercontent.com/assets/42011/17334360/fc03c376-58a3-11e6-87bd-75dd53a5faa4.png)

**Comment by ojw28** [comment]
This works fine on a test device I have, so it seems like it's probably Android version dependent. As per the issue template, please provide details about the devices and Android builds on which the issue reproduces (and preferably a full bug report).

**Comment by cstew** [comment]
Thank you for your help and the quick response! Here is some additional information:

I am on commit: `f4edea81a3141d16bdac9d48687f92928c49784d` just off of master. ExoPlayer 1.5.9. 

I reproduced by pasting the dropbox video link from above into the ExoPlayer demo app using `TYPE_OTHER` as the video type. 

I have not yet come across a device that renders these subtitles correctly. I have reproduced on the following devices:
LGE Nexus 5X (Android 6.0.1, API 23)
HTC Nexus 9 (Android 6.0.1, API 23)
Samsung SM-G920F (Android 6.0.1, API 23) 
Samsung SM-P600 (Android 4.4.2, API 19)
Samsung SCH-I545 (Android 4.3, API 18)

Attached is a bug report and the relevant logs from a 5X. 
[subtitle_report.txt](https://github.com/google/ExoPlayer/files/397570/subtitle_report.txt)
[subtitle_log.txt](https://github.com/google/ExoPlayer/files/397552/subtitle_log.txt)

Let me know if there is any additional info I can send along.

**Comment by ojw28** [comment]
The sample provided works fine on a Nexus 5X I have running MTC19T (same build as in the bug report attached above). Are you certain it reproduces on that device/build combination?

**Comment by cstew** [comment]
Yes, I am certain that the issue shows up on that device for me. 

To test, I added this as a sample to `Samples.java`:

``` java
new Sample("Subtitle Test", "https://www.dropbox.com/s/rklo2hg5nsb164e/subtitles.mp4?dl=1", Util.TYPE_OTHER)
```

Am I using the wrong type?

If it helps, I can also send you an apk that I've built on my machine.

**Comment by ojw28** [comment]
Oh right, I can reproduce this now. I was assuming you were sideloading the `.srt` subtitle file (playback works correctly if you do this), but you're actually embedding the subtitle in the `.mp4` file.

There's a pretty big piece of information missing here. How are you doing the embedding? You must be using some kind of tool or utility to do that. Are you sure that the tool works correctly in the case of the input containing font tags? It's notable that QuickTime player doesn't appear to play the captions in your sample video quite right either. If I had to guess, I'd say the media is not formatted correctly.

**Comment by cstew** [comment]
You're right that the colors aren't correct in Quicktime. They do work fine in VLC and I believe they work in iOS's media player. The subtitle text does show up correctly in each of these (which is the important part for me).

I'm using Handbrake to encode the subtitles. 

The issue for me is that I have a vendor that is supplying video files with embedded subtitles. These subtitles have a `<font size="24">` tag in them which I would happily ignore. The subtitles do playback correctly in the iOS version of the app I'm working on (with the font size ignored). I don't know why the vendor has that font tag and I am trying to work with them to get it removed, but I'm not sure how much progress I will be able to make there.  

I was able to reproduce this issue with the sample file you see above with the font color attribute as a test. I tried my best to strip things down to identify where the problem occurs. If you'd like a copy of the original file that prompted all of this, I'd be happy to send it along privately. 

That is very interesting that sideloading the `.srt` file works correctly. I may be able to work around this problem using that. 

Thanks for your help. I really do appreciate all of the free effort that you put into the project. Let me know if there's anything I can do to contribute to the issue, or if you judge this to not be a priority at the moment.

**Comment by ojw28** [comment]
It should be possible for you to write a short program that strips out the HTML tags, which you could then run on the srt file before you give it to Handbrake. That's probably the easiest way you could fix this.

**Comment by cstew** [comment]
The video creation and hosting is fully outside of my control. It is good to know that an external `.srt` file will render correctly. I may have to go that route. 

It is important to note that the vendor that is supplying the video to me is not using Handbrake to embed the subtitles into the video (they are using some other video encoding software). 

I've been doing some more digging this morning and it seems that the font tag issue may not be the actual cause of the problem. I see erroneous characters in the subtitles if there are more than 32 characters per subtitle. 

```
1
00:00:01,468 --> 00:00:03,068
Subtitle test

2
00:00:03,070 --> 00:00:04,710
This is a slightly longer captio

3
00:00:04,705 --> 00:00:05,505
This is a slightly longer caption

4
00:00:05,506 --> 00:00:08,506
This is a slightly longer 
caption2
```

Lines 1 and 2 display correctly. Lines 3 and 4 show an additional character when the subtitles are displayed. 

Below is the video that reproduces the problem and the `.srt` file that I encoded into it. 

Video: https://www.dropbox.com/s/v3wwk56qmu7h5xz/video.mp4?dl=1
Subtitle file: https://www.dropbox.com/s/5is3b7rb3zee2i3/subs.srt?dl=1

![device-2016-08-09-072316](https://cloud.githubusercontent.com/assets/42011/17519774/2d50b4c6-5e02-11e6-9467-b24115320a82.png)

Is this by design? Maybe there is a limit to how many characters can exist per subtitle row in the spec?

**Comment by cstew** [comment]
I forgot to note in that last comment, the latest video does show the correct subtitles in Quicktime and VLC on my computer.

**Comment by ojw28** [comment]
The issue here is that we're treating tx3g samples as though they're just text, where-as they actually consist of:
- 2 byte length N
- N bytes of text
- Optional additional boxes defining, for example, styling information.

We'll push a change shortly that parses just the N bytes of text, which will fix your issues (but wont color the subtitle as specified by the font tags). At some point in the future we'll also parse the tx3g styl box, which contains the color (and other styling information).

**Comment by cstew** [comment]
That's excellent. Thanks again for your help!

If there's anything I can do to provide more info or assist, let me know.

**Comment by hoseinmirian** [comment]
how can we read one by one text of the subtitles?

**Comment by hoseinmirian** [comment]
please send me the answer in my gmail : hosein.mirian@gmail.com
