### ISSUE TITLE
Simple HLS audio player

### ISSUE THREAD

**Issue by neowinston** [google/ExoPlayer#1713]
I'm new to Android and ExoPlayer development, coming from iOS. 

I just need to play HLS audio, and have tried the demo app and it works fine, but I still need a more simple example, without video, to get started. 

Could anyone please point me out to a simple HLS live radio stream sample code? 

Thank you very much!

**Comment by ojw28** [comment]
Please ask general questions on StackOverflow. This issue tracker is for issues and feature requests. Thanks!

**Comment by neowinston** [comment]
Thanks!
