### ISSUE TITLE
Exoplayer dev-v2 playback live stream shift 5 mins behind

### ISSUE THREAD

**Issue by norazhou** [google/ExoPlayer#1717]
I have a live dash stream, and tried with Exoplayer dev-v2. However, when playback it will shift 5 mins behind current time. For example, it start to playback live stream at 20:00 when it is actually 20:05 right now. Tested that Exoplayer dev-v1 and Shaka player can playback with current time. Is there any idea?

**Comment by ojw28** [comment]
It's a known issue with V2 that live playbacks are currently starting from the wrong place. We'll fix this shortly.

**Comment by ojw28** [comment]
This is fixed in latest `dev-v2`.

**Comment by norazhou** [comment]
Can you provide the code diff? As I find that the latest dev-v2 does not support subtitles, e.g HLS + WEBVTT. However, the older version support this.

**Comment by ojw28** [comment]
What does HLS with WebVTT have to do with this issue, which is about the position of playback in DASH Live streams?

**Comment by norazhou** [comment]
No..there is no relationship with this issue...I just hope WEVTT feature could work...Maybe I should open another issue about WEBVTT?

**Comment by norazhou** [comment]
Anyway, can you provide the code diff about the position of playback in live streams?

**Comment by ojw28** [comment]
Please file separate issues for unrelated problems. Please also include all of the information requested in the issue template when you do so; thanks.

There are a whole sequence of changes that fed into fixing this, some tangentially, so it's not really a case of there being a single change. Hence there is no simple diff that "fixed this". I can point you to the code that determines the default playback position, which is here: https://github.com/google/ExoPlayer/blob/dev-v2/library/src/main/java/com/google/android/exoplayer2/source/dash/DashMediaSource.java#L387

**Comment by norazhou** [comment]
Thank you very much~
Also for a related issue, is this feature for right position of playback in DASH Live streams also apply to HLS and smooth streaming?

**Comment by ojw28** [comment]
SmoothStreaming: Yes. HLS: Eventually but not yet. We prioritize DASH, as stated [here](https://medium.com/google-exoplayer/test-8b62d50362ef). A feature often lands for SmoothStreaming at the same time as for DASH because the two are quite similar (and share quite a lot of code). A feature lands later for HLS because the HLS spec is a mess.

**Comment by norazhou** [comment]
Thanks~can you inform me here when the right position for HLS live stream is fixed?
