### ISSUE TITLE
 Exception : boolean java.lang.String.equals(java.lang.Object)

### ISSUE THREAD

**Issue by biezhihua** [google/ExoPlayer#1721]
My is developer from china. 
I have searched a list of questions, but did not find what I want.

SDK_INT : 21
DEVICE:hnCHE-H  hwALE-H
codecName: OMX.k3.video.decoder.avc

At first, I use the process, we encountered the following issues:

```
Internal track renderer error.
com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.MediaCodecUtil$DecoderQueryException: Failed to query underlying media codecs
```

Then I followed the MediaCodecUtil file getDecoderInfosInternal() method.I print a more detailed exception log，It appeared the following exception:

Exception 1 : Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
Exception 2 : Attempt to invoke virtual method 'boolean android.media.MediaCodecInfo$CodecCapabilities.isFeatureSupported(java.lang.String)' on a null object reference

I added try catch to  getDecoderInfoInternal () method , then it can run normally, but I do not know to do right, it is proposed as a problem.

``` java
try {
    CodecCapabilities capabilities = null;
    try {
        capabilities = codecInfo.getCapabilitiesForType(supportedType);
    } catch (Exception e) {
       // Exception 1
    }
    boolean secure = false;
    try {
        secure = mediaCodecList.isSecurePlaybackSupported(mimeType, capabilities);
    } catch (Exception e) {
        // Exception 2
    }
    try {
        if ((secureDecodersExplicit && key.secure == secure) || (!secureDecodersExplicit && !key.secure)) {
            decoderInfos.add(new DecoderInfo(codecName, capabilities));
        } else if (!secureDecodersExplicit && secure) {
            decoderInfos.add(new DecoderInfo(codecName + ".secure", capabilities));
            return decoderInfos;
        }
    } catch (Exception e) {
    }
} catch (Exception e) {
    if (Util.SDK_INT <= 23 && !decoderInfos.isEmpty()) {
        // Suppress error querying secondary codec capabilities up to API level 23.
        YYTLog.d(TAG, "Skipping codec " + codecName + " (failed to query capabilities)" + "e=" + e.getMessage());
    } else {
        // Rethrow error querying primary codec capabilities, or secondary codec
        // capabilities if API level is greater than 23.
        YYTLog.d(TAG, "Failed to query codec " + codecName + " (" + supportedType + ")" + "e=" + e.getMessage());
        throw e;
    }
}
```

My English is very bad, please forgive me.

Hoping to get a reply, thank you

**Comment by andrewlewis** [comment]
Please could you provide the following information?
- Version of ExoPlayer (commit number)
- Full stack traces from the exceptions, including any cause
- The output of `adb shell getprop ro.build.fingerprint`

Thanks.

**Comment by ojw28** [comment]
Please also provide a full bug report using release `1.5.9` of ExoPlayer, shortly after reproducing the issue.

**Comment by ojw28** [comment]
@biezhihua - Please provide the requested information, or we'll close this issue. Thanks.
