### ISSUE TITLE
Can  this ExoPlayer  support Variable speed ?

### ISSUE THREAD

**Issue by CallBackMe** [google/ExoPlayer#1727]
I want to use the player at 2.0 speed plays music ！But I couldn't find a way to set this ！

**Comment by ojw28** [comment]
Please see #26

**Comment by yangwuan55** [comment]
@all Please see [here](https://github.com/yangwuan55/ExoPlayer/tree/playbackSpeed) ,I have a implementation of variable speed for exoplayer,support the preversion of 23.

**Comment by nzala** [comment]
hw using @yangwuan55
