### ISSUE TITLE
How To Change Default Seek Time In Exoplayer

### ISSUE THREAD

**Issue by zaky295** [google/ExoPlayer#1728]
Hi 
I Integrated ExoPlayer and it runs well but i want to change its default seek time.when i click on forward button on ExoPlayer it seek to 15 sec forward and when press on previous button than i seek to -5 sec back but i want to change this default time.
i want when i click on forward button it seek to 60sec forward from current position and when i click on previous button than it seek to -15 sec back from current position so please help me how can i do this.

**Comment by AquilesCanta** [comment]
You should take a look at the Player Activity of the DemoApp. It is implemented there.

**Comment by AquilesCanta** [comment]
I replied erroneously before(deleted now). As @ojw28 pointed out, it is likely you will have to implement your own MediaController to that end, as those values are hardcoded and the listeners made private. I would suggest you try getting some help in a general Q&A site, as the issue tracker is for bugs and feature requests.
