### ISSUE TITLE
Frame drop on Samsung Galaxy S7 when playing widevine encrypted content

### ISSUE THREAD

**Issue by cjveldkamp** [google/ExoPlayer#1729]
We are currently implementing the Exoplayer for our new Android App and are using Widevine Modular streams that are already used by other platforms.

On all android devices we have tested playback is OK, except the Samsung Galaxy S7 (tested with android 6.0.1). On this device we see a lot of frame drops during playback. It is also noticeable in the demo player, where you see the dob (droppedOutputBufferCount) value increasing when using our DRM streams. See attached movie. 

[Galaxy S7 playback issue.mov.zip](https://github.com/google/ExoPlayer/files/406824/Galaxy.S7.playback.issue.mov.zip)

It is only noticeable with the widevine encrypted streams. When we use non drm teststreams (same specs) there isn't a problem. 

We can deliver a test stream for reproduction, but we need the IP address for our whitelist.

**Comment by wvpaf** [comment]
Hi @cjveldkamp, 
It seems that S7 has had issues keeping up for smooth playback and encryption would impact playback as well.  Have you been able to test a track encoded at a lower bitrate?
Also an ADB bugreport would be helpful.
thaks.

**Comment by cjveldkamp** [comment]
Hi @wvpaf,

I have attached a bugreport file. 
[bugreport.txt](https://github.com/google/ExoPlayer/files/412763/bugreport.txt)

The lowest bitrate we use for our service is 2 mbit SD (768 x 576). We use this encode for a lot of platforms, but the S7 is the only one with problems. I guess that a 2mbit encode should not be a big problem for the S7, should it?

Any suggestions based on the new information? 

With kind regards,

Christiaan

**Comment by cjveldkamp** [comment]
@wvpaf I was wondering if you had the time too look into my comments? 

With kind regards, 

Christiaan

**Comment by wvpaf** [comment]
Hi @cjveldkamp, 
From the log the device seems to close down the h/w TEE driver : 
08-11 09:33:04.136  3138  3583 I TeeDriverClient: driver client closed [hardware/samsung_slsi/exynos8890/mobicore/ClientLib/src/driver_client.cpp:113]

We will need to dig deeper.

**Comment by cjveldkamp** [comment]
Hi @wvpaf, 

Any advice how to dig deeper from our side? Do you need more information or other logs? 

with kind regards, 

Christiaan

**Comment by jefftinker** [comment]
Hi Christian, The information you have provided is sufficient for now. This is not the only issue we've seen with the S7, we are continuing to investigate internally.

**Comment by wvpaf** [comment]
Samsung believes this issue is addressed but would like to verify playback. 
Can you share any content, not geo restricted for them to test?

**Comment by ojw28** [comment]
Let's use #1764 to track what's left to be done here. @cjveldkamp - If you are able to share test content and/or a demo apk that can be used for testing, please update #1764 rather than this one. Thanks!
