### ISSUE TITLE
Question on MP3 Playback. 

### ISSUE THREAD

**Issue by peddisri** [google/ExoPlayer#1732]
MP3Extractor.java has a logic to check for 4 consecutive MP3 frames to sniff the content and detect it as MP3. This is also done in synchronize API.  Is there any specific reason for this?

**Comment by andrewlewis** [comment]
The logic is intended to (approximately) match the behavior of the platform extractor (see [MP3Extractor.cpp](https://android.googlesource.com/platform/frameworks/av/+/master/media/libstagefright/MP3Extractor.cpp)). I think the search is intended to avoid false positives -- it is very unlikely that frames would be found at the correct offsets in random data. Do you think it should work in a different way?

**Comment by peddisri** [comment]
Well, we have a requirement of playing a file that has 3 MP3 frames. So, it fails because of this check. In my opinion, a check for one or two frames is sufficient.

**Comment by ojw28** [comment]
The fewer frames we check, the more likely we are to hit a false positive. I don't think we want to reduce the number of frames that we look for, but we should allow a match having seen fewer frames specifically in the case that end-of-stream is encountered during sniffing.

Is there any chance you could attach the file you're trying to play, or send it to `dev.exoplayer@gmail.com`? Please update the issue if you send it to the latter, so we know to check. Thanks!

**Comment by ojw28** [comment]
@peddisri - Please could you provide us with the file?

**Comment by ojw28** [comment]
This is fixed in `dev-v2`.
