### ISSUE TITLE
How to rotate video 90 to portrait mode

### ISSUE THREAD

**Issue by tuananhdtu** [google/ExoPlayer#1733]
Hi.

I record my video with Media Recorder and Camera with portrait mode.
With Media Recorder, i write: mMediaRecorder.setOrientationHint(270);
With camera:   mCamera.setDisplayOrientation(90);
# The output file will see result from bottom to top 

|           |
|           |
# |     ^    |  

And , i use exoplayer to play mp4 file from mMediaRecorder.
# the output file will see result from left to right

|           |
|  >      |
# |           |  

I've searched for information from issues tabs.
And i find Media Format file and change value 

maybeSetIntegerV16(format, "rotation-degrees", rotationDegrees);

but not change anything.

Help me.
Sorry for bad english

**Comment by ojw28** [comment]
There is quite a lot of discussion around this issue in https://github.com/google/ExoPlayer/issues/91. Please give that thread a read.
