### ISSUE TITLE
Deterministic MPEG-DASH Representation Switch

### ISSUE THREAD

**Issue by mikeswanson** [google/ExoPlayer#1735]
I've implemented a custom FormatEvaluator that correctly determines which format/representation  should be selected. However, I'd like it to be called more frequently than it is, and ideally, I'd like to signal a format change deterministically (i.e. you can call me, but I'd also like to call you). When a format change is signaled, I'd like it to switch as quickly as possible. By this I mean that--even if it's already buffered a lot of higher quality content--I'd like it to discard all of that content and make the switch.

Can anyone recommend a general strategy to accomplish this with ExoPlayer?

**Comment by ojw28** [comment]
To answer this (very old - sorry) question with respect to ExoPlayer V2:

* In V2 implementing a custom `TrackSelection` is the mechanism by which you can provide your own adaptive format selection algorithm.
* During loading, `TrackSelector.updateSelectedTrack` is already called at every point where changing the selected format would make any difference during loading. So I'm not sure there's any additional value in the "I'd also like to call you" part of this question. Unless of course you'd want a currently ongoing chunk fetch to be a canceled, which is not something we currently support
* When not loading, `TrackSelector.evaluateQueueSize` is called frequently, and provides an opportunity for you to discard from the buffer in order for it to be re-loaded in a different quality. This method will also be called between loads during loading phases.
