### ISSUE TITLE
about udpdatasource demo

### ISSUE THREAD

**Issue by lcksk** [google/ExoPlayer#1736]
Sorry, I'm a newbie for ExoPlayer,I need a demo to test  UDP over mpeg2TS (h264+aac,8M bitrate).
I don't  know how to use udpdatasource, any one could  provide me a simple demo similar to demo-ext ? thinks.
Any executable source code or suggestion are  appreciated.

**Comment by ojw28** [comment]
Closing since this is neither an issue nor a feature request. Unfortunately we don't have time to answer questions of this type on the issue tracker, sorry.
