### ISSUE TITLE
Migration from MultiTrackChunkSource? (1.3.3 -> 1.5.9)

### ISSUE THREAD

**Issue by DancinDirk** [google/ExoPlayer#1740]
Hello Everyone,

We've been using the ExoPlayer for over a year for an HLS Audio App but recently we have been having some issues with the playback pausing for no apparent reason. One thing we were looking at was updating to the latest version but then we noticed that MultiTrackChunkSource is gone. We've searched for migration instructions but have so far come up empty. Is there a clear upgrade path so we don't have to re-implement the whole thing from scratch?

@ojw28 I can see that you've been very active on this subject, do you have any advice?

Thanks in advance!

**Comment by AquilesCanta** [comment]
It shouldn't be too complicated moving to 1.5.9(or 1.5.10) if you the DemoApp as guide, I think. The interfaces haven't changed that much. Version 2 would be a different story. What is the complication specifically? HlsRendererBuilder contains most of the details related to HLS.

**Comment by ojw28** [comment]
As per the answer above, it should be fairly straightforward if you look at the difference between the demo app going from the version you're upgrading from to the current version.
