### ISSUE TITLE
USB optical passthrough on Nvidia Shield TV

### ISSUE THREAD

**Issue by arnoutvandervorst** [google/ExoPlayer#1741]
When using Plex for Android TV on the Nvidia Shield TV system, media which contains DTS or DD audio streams are always transcoded by the Plex Media Server. The reason for this is that the player thinks the device doesn't support DTS or DD. The Plex developers point to ExoPlayer not recognising or handling the USB dongle passthrough which has been enabled on the Shield recently through a firmware update. Reasoning for all this: I still have a DTS/DD receiver (Denon AVR-3801) without HDMI, so I have to resort to a USB-DAC to provide an optical connection between the Shield and the receiver. When using Kodi/SPMC with the IEC passthrough setting, this works perfectly. I'd really like Plex to support this to as this is my main HT environment.

Also see:
https://github.com/koying/SPMC/issues/162

Is this something that can be supported/fixed?

**Comment by arnoutvandervorst** [comment]
Seems we have to wait for Android N to support this:
https://developer.android.com/reference/android/media/AudioFormat.html#ENCODING_IEC61937

SPMC has already implemented this and strangely enough it works on my current Nvidia Shield TV with 3.2 firmware.

**Comment by slamdance** [comment]
We know the Shield supports USB/SPDIF audio and both Kodi and SPMC devs have figured out how to successfully implement it, so hopefully something can be done for ExoPlayer to implement it as well.  I doubt we will see Android N on the Shield before the end of the year.

**Comment by andrewlewis** [comment]
I think the fix for this doesn't rely on N. It would involve checking [AudioDevice](https://developer.android.com/reference/android/media/AudioManager.html#getDevices%28int%29) encodings (via [AudioDeviceInfo.getEncodings()](https://developer.android.com/reference/android/media/AudioDeviceInfo.html#getEncodings%28%29)), and listening for changes using [AudioDeviceCallback](https://developer.android.com/reference/android/media/AudioDeviceCallback.html). These are all available on M.

@arnoutvandervorst That encoding constant is for use by applications that want to output media that is not in one of the supported encodings (AC-3, E-AC-3, DTS or DTS-HD), so I think it's not directly related to this issue.

**Comment by andrewlewis** [comment]
To clarify, the underlying issue here is that ExoPlayer relies on HDMI audio plug info to detect passthrough capability, rather than checking AudioDevices (which should include USB audio devices).

**Comment by arnoutvandervorst** [comment]
Is that something that Plex can modify on their end using the ExoPlayer implementation, or does ExoPlayer need to be extended? If the latter, would the Plex devs need to do something additional to make it work? This would be a great enhancement for me (living in the HDMI-less-stone-age) and lots of others facing the same challenge.

**Comment by andrewlewis** [comment]
@arnoutvandervorst This will require some changes to ExoPlayer's AudioTrack wrapper, to detect the encoded output capability. Once that's done, hopefully it will be possible to enable passthrough automatically when the input format can't be decoded and the default output audio device supports it.

**Comment by gazzer82** [comment]
Is their any update on this, seems to still be an issue on the latest N release on the Nvidia Shield and is a pretty frustrating limitation?

**Comment by andrewlewis** [comment]
No updates at the moment but it's on our radar to look at it soon.

**Comment by huytman** [comment]
have this page on a 'changes check' status and saw this pop up today.  Glad to see it's at least being looked at.  I was hoping the N update would somehow fix this - it didn't.  Presently using the SPMC with the Plex addon.  Works as expected - 5.1 output through USB and HDMI - but nothing with the standalone Plex app.

**Comment by andrewlewis** [comment]
#1993 is a similar issue about supporting `AudioDeviceInfo` so marking this as a duplicate. This is still on our radar but I'm afraid other higher priority items have come up.
