### ISSUE TITLE
Exoplayer not playing audio AC3 codec

### ISSUE THREAD

**Issue by Kinoman512** [google/ExoPlayer#1750]
when I start  the video plays but no audio. is exoplayer support ac3 codec?

**Comment by AquilesCanta** [comment]
I am not sure what the case is here. @andrewlewis is the voice of knowledge here but what you are trying to play is a ts that includes an ac3 encoded audio stream? Or does the playlist refer to .ac3 segments?

As a side note, unless you are using extensions, codec support depends solely on the platform on which you are playing. You can find some information about this here:

https://developer.android.com/guide/appendix/media-formats.html

Depending on the circumstances, you might want to pass the samples through. Please clarify.

**Comment by Kinoman512** [comment]
i have mkv video with inner audio on my sd card. i thinck my device does support codec. But how to play audio? can i add codec library? How to determine which codec is not supported programmatically?

Audio 
      Format : AC-3
      Format/Info : Audio Coding 3
      Mode extension : CM (complete main)
      Format settings, Endianness : Big
      Codec ID : A_AC3
      Duration : 50 min
      Bit rate mode : Constant
      Bit rate : 384 kb/s
      Channel(s) : 6 channels
      Channel positions : Front: L C R, Side: L R, LFE
      Sampling rate : 48.0 kHz
      Frame rate : 31.250 FPS (1536 spf)
      Compression mode : Lossy
      Stream size : 138 MiB (11%)
      Language : English
      Default : No
      Forced : No

**Comment by AquilesCanta** [comment]
Unfortunately, this is not Exoplayer specific and you will have to look somewhere else. I can point you to

https://developer.android.com/reference/android/media/MediaCodecList.html

and

https://github.com/google/ExoPlayer/blob/r1.5.10/library/src/main/java/com/google/android/exoplayer/MediaCodecUtil.java

**Comment by andrewlewis** [comment]
Regarding adding codecs to the library: some of the [extensions](https://github.com/google/ExoPlayer/tree/release-v1/extensions) provide TrackRenderers that bundle their own software decoders, so they don't rely on platform codecs. The ExoPlayer v2 development branch has [an extension that wraps the FFmpeg library](https://github.com/google/ExoPlayer/tree/dev-v2/extensions/ffmpeg). It is possible to compile FFmpeg with support for decoding AC-3 audio.

**Comment by Kinoman512** [comment]
i dont know how to use this extension. Give me please example of using exentension.

**Comment by andrewlewis** [comment]
We don't have any detailed documentation on using the FFmpeg extension I'm afraid, but the v2 demo app will use it if it is built.

At a high level, you would need to follow the [instructions to build the extension](https://github.com/google/ExoPlayer/tree/dev-v2/extensions/ffmpeg/README.md), making sure to enable whatever decoders are needed when you configure the library. Then switch to one of the demo_ext build variants in Android Studio and play your stream from the demo app (by adding it to the samples list or starting the demo app with an intent pointing to the stream to play). We will provide some more details about this last step in an upcoming post on the [developer blog](https://medium.com/google-exoplayer) soon.
