### ISSUE TITLE
How to change the pitch of the audio

### ISSUE THREAD

**Issue by ghost** [google/ExoPlayer#1751]
Hello,

I want to ask that is the ExoPlayer have the Pitch Shift function or not? I mean the function, which can change the pitch of the audio while playing the video but does not change the playback rate.

If was yes, how can I use it?

Thank you.

(Sorry for my bad English)

**Comment by AquilesCanta** [comment]
For devices running API 23 or later, you can send a message to the MediaCodecAudioTrackRenderer setting the playback parameters, where you include the pitch. 

You can have a look at:

https://github.com/google/ExoPlayer/blob/r1.5.10/demo/src/main/java/com/google/android/exoplayer/demo/player/DemoPlayer.java

To see how messages are sent. Note that this will not work in older versions of android.

**Comment by ghost** [comment]
Thank you. Let me check it.
