### ISSUE TITLE
Which part shall I modify if I want to display 2 stream simultaneously?

### ISSUE THREAD

**Issue by MegaThomas** [google/ExoPlayer#1753]
I'm trying to play 2 streams side-by-side. I've tried to add more `videoRenderer` (like 2 videoRenderers, 1 audioRenderers & textRenderer) in the `DemoPlayer`, but I found `ExoPlayerImpl` has `selectedTrackIndices` which limit the number of active video tracks.

I suppose I can't use 2 players since I want to efficiently sync them. Which part of the video rendering pipeline should I change besides `ExoPlayerImpl`?

**Comment by palfu** [comment]
in release-v1, 

```
player.setSelectedTrack(TYPE_VIDEO, 0);
player.setSelectedTrack(TYPE_VIDEO1, 1);
```

work?

**Comment by ojw28** [comment]
For V2, this is answered in https://github.com/google/ExoPlayer/issues/2855.
