### ISSUE TITLE
How to get volume?

### ISSUE THREAD

**Issue by nezen** [google/ExoPlayer#1754]
I know I can set volume by `player.sendMessage(audioRenderer, MediaCodecAudioTrackRenderer.MSG_SET_VOLUME, volume);`

But as far as I know AudioTrack do not provide a method for getting its current volume, I want to make sure if there is any workaround.

Of course one of the option is something like this:

`private float mVolume;`

`public void setVolume(final float volume){`
    `this.mVolume = volume;`
    `player.sendMessage(audioRenderer, MediaCodecAudioTrackRenderer.MSG_SET_VOLUME, volume);`
`}`

`public float getVolume(){`
      `return mVolume;`
`}`

but the problem is that I can never get the initial volume.

**Comment by ojw28** [comment]
The initial volume is always 1.0, and the volume is thereafter only changed if you change it. So you should always know in application code what the volume is.

For V2, we can pretty easily add a `getVolume` method to `SimpleExoPlayer` so that you don't have to keep track of it yourself.
