### ISSUE TITLE
The timestamp corresponds to a time before the track was most recently resumed

### ISSUE THREAD

**Issue by dobrusev** [google/ExoPlayer#1755]
Hello team,

I'm using https://github.com/amzn/exoplayer-amazon-port which enables me to play Smooth Streaming with Playready (for some reason I can't play SS+Playready in the demo app that you have here).
I use it to play video content in amazon FireTV Stick but I see error:
`W/AudioTrack: The timestamp corresponds to a time before the track was most recently resumed: 113500000, 17341289112` every second.

Having this error the playback is not smooth and I see judders every second.
My question is what is causing this error? 
If it's from the manifest can I have a workaround to prevent the judders?
I'm sending you an email to dev.exoplayer@gmail.com with example SS manifest.

Keep the great work btw.

Thanks in advance!

**Comment by ojw28** [comment]
We're unable to provide support for Amazon's fork. Some FireOS devices have specific issues around audio timestamps / tracking of playback position. I believe their fork is intended to work around some of those issues, but this is something you'd have to follow up with them directly on (i.e. file an issue on their fork's issue tracker, not here).

**Comment by dobrusev** [comment]
Hi,

Thanks for the fast reply. 
I forgot to mention that I can see the same behavior with the latest ExoPlayer r1.5.10, that's why I raised the ticket here.

Can you tell me what's the reason for that error, please?

**Comment by ojw28** [comment]
The underlying problem is an issue with FireOS / FireOS devices, hence the need for you to contact Amazon directly. Note that FireOS is not Android; it's a heavily modified fork of Android. It seems they've failed to retain proper compatibility with Android in parts of the media stack on some of their devices; hence this kind of issue.
