### ISSUE TITLE
how to show subtitle ?

### ISSUE THREAD

**Issue by Hitexroid** [google/ExoPlayer#1756]
Hi , please help me to subtitle on ExoPlayer

i saw this Issue but not worked .

[https://github.com/google/ExoPlayer/issues/587](url)

**Comment by AquilesCanta** [comment]
If you are using version 1, have a look at the DemoPlayer class of the DemoApp. If you are using version 2, have a look at the PlayerActivity and go from there. Unfortunately, this issue tracker is reserved for bugs and feature requests, I'd suggest you try another Q&A such as StackOverflow for generic programming questions.

**Comment by Hitexroid** [comment]
i have the latest version ! but not showing subtitle

 i asked question from StackOverflow yesterday and an user gave me link of ExoPlayer
