### ISSUE TITLE
Does exoplayer support fast start in HLS without waiting to download the full ts segment

### ISSUE THREAD

**Issue by ssaroha** [google/ExoPlayer#1757]
For fast video playback start, does exoplayer support streaming option to start playback as soon as there is X seconds buffer which is enough to show the first few frames, instead of waiting for the full ts segment (which is usually 10 seconds long) to download.

I looked into the code https://github.com/ssaroha/ExoPlayer/blob/release-v1/library/src/main/java/com/google/android/exoplayer/hls/TsChunk.java#L92 here but doesn't seem clear if this feature is supported.

thanks

**Comment by AquilesCanta** [comment]
No, right now this is not possible. I cannot think of an easy way of achieving this either. The chunk loading model does not fit well in this schema, I think, so it would require quite a few changes. If this is case, unfortunately, It will not get prioritized. I'll discuss this with my colleagues and reach back.

**Comment by AquilesCanta** [comment]
I wrote a comment before which is now deleted. If you read it, forget about it. As @ojw28 correctly points out, we start the preparation of the HlsMediaPeriod as soon as we have loaded samples from the Chunk, and this happens as we get the data downloaded. My bad. In other words, there is no need to have the whole chunk downloaded to start playback.
