### ISSUE TITLE
ContentDataSource fails to retain AssetFileDescriptor - file randomly closed by GC

### ISSUE THREAD

**Issue by cbfiddle** [google/ExoPlayer#1759]
`ContentDataSource` calls `openAssetFileDescriptor` but fails to retain the returned `AssetFileDescriptor`. The doc for this method says that the caller is responsible for closing the asset file descriptor. The effect is that the `AssetFileDescriptor` is GCed at some random time at which point the underlying file descriptor is invalidated, causing an `IOException` if it is still in use at that time.

**Comment by ojw28** [comment]
Thanks for reporting this!

**Comment by asadw1** [comment]
> at some random time

Is there any way you can see a stacktrace of the execution? This can help find where the GC is happening.

**Comment by ojw28** [comment]
I'm not sure it's relevant when the GC happens. The point is that the DataSource implementations shouldn't be affected by it. We have a fix internally, and will push to GitHub soon.

**Comment by asadw1** [comment]
Noted. Thanks!
