### ISSUE TITLE
Exoplayer do not play video in some device. 

### ISSUE THREAD

**Issue by kinhdang** [google/ExoPlayer#1761]
Hello ExoPlayer !

We using Exo to playback DAS Streaming, Almost device working perfectly. But some setopbox, after playback streaming play about 1 to 5 minute, video stop althrough audio working perfectly.
We attach log file in here. Any knows this issue, Please help ?

Thanks.
[boxchina.txt](https://github.com/google/ExoPlayer/files/430699/boxchina.txt)

**Comment by andrewlewis** [comment]
Please provide all the information requested in the new issue template, including a full bug report taken from the device just after the issue occurs. You can capture one using `adb bugreport`.
