### ISSUE TITLE
Question about design of MediaPresentationDescriptionParser

### ISSUE THREAD

**Issue by ethanjyx** [google/ExoPlayer#1763]
Hello, I just have a question about the design of MediaPresentationDescriptionParser. When reading the code, I found the function buildFormat [here](https://github.com/google/ExoPlayer/blame/706c6908ec57005044f4b4a9f5b80266cad9eda3/library/src/main/java/com/google/android/exoplayer/dash/mpd/MediaPresentationDescriptionParser.java#L409). It appears the only thing it is doing is to do a `new Format`, why not remove this function and put the `new Format` directly in the callsites? Is this considering potential extensions to this function? What potential extensions are considered?

**Comment by ojw28** [comment]
Yes, it was written that way to allow extension (for provider specific extensions to the DASH manifest)..
