### ISSUE TITLE
Frame drop on Samsung Galaxy S7 when playing widevine encrypted content

### ISSUE THREAD

**Issue by workspace** [google/ExoPlayer#1764]
Hi. I encountered a problem when I try to apply Android M's new feature, PlaybackParams.
I put button to set PlaybackParams in latest v2 demo app. You can see my code in [this branch](https://github.com/tntcrowd/ExoPlayer/tree/dev-v2-playback-speed).
![image](https://cloud.githubusercontent.com/assets/7759511/17880014/548f4586-6931-11e6-85bb-a8593a3f164e.png)
(This image is captured from Nexus 5)

Then I try to play 'WIDEVINE DASH: MP4,H264 - Secure XX' sample(which my service want to support) with various PlaybackParams and devices. I used Nexus 5(API 23), Nexus 5X(API 23), Samsung Galaxy Note 5(API 23) and Samsung Galaxy S7(API 23) for tests. Nexus 5, Nexus 5X, and Galaxy Note 5 looks nice, however, only Galaxy S7 dropped frames with internal errors from audio renderer when I set PlaybackParams with speed above 1.5x. 

```
08-23 11:06:12.299 29975-29975/com.google.android.exoplayer2.demo E/EventLogger: internalError [10.80, audioTrackUnderrun [56704, 321, 187]]
```

I tried to figure out why these errors occured, but I can't grap any insights to solve this problem. [This method](https://github.com/google/ExoPlayer/blob/dev-v2/library/src/main/java/com/google/android/exoplayer2/audio/AudioTrack.java#L675) return false when errors occured. I will send logcat and videos to your email to help understanding.

version - latest ExoPlayer - branch dev-v2
how to reproduce - with Samsung Galaxy S7(API 23), Clone [my project(dev-v2-playback-speed)](https://github.com/tntcrowd/ExoPlayer/tree/dev-v2-playback-speed), Playing WIDEVINE DASH: MP4,H264 - Secure XX' samples with PlaybackParams(2.0x) - frame will be dropped!
(optional)
Try same things with Nexus series. It will work fine.

**Comment by jefftinker** [comment]
@ojw28 if you have received the logcat and videos related to this issue?  If so, can you attach them here?

**Comment by ojw28** [comment]
Logs shared internally. @KiminRyu, it would be helpful if you could provide a full bugreport (captured with "adb bugreport") shortly after encountering the issue, rather than just logcat output. Thanks!

**Comment by workspace** [comment]
@ojw28 I will try it! @jefftinker Are you interested in solving this issue? If you leave an email address, I will send you same mail with attachments. Thank you.

**Comment by wvpaf** [comment]
@KiminRyu, please attach the requested troubleshooting information to this case so the issue can be investigated.   Thanks.

**Comment by wvpaf** [comment]
The logs have been received outside of this case. Team is reviewing them now, not finding any errors/issues with the decryption process. Asking the OEM to take a look.

**Comment by wvpaf** [comment]
Samsung believe sthis issue is addressed but would like to verify playback. 
Can you share any content, not geo restricted for them to test?

**Comment by workspace** [comment]
@wvpaf Thank you for your response. 
Here is my [Exoplayer r2.0.4(latest version) demo with speed button](https://github.com/tntcrowd/ExoPlayer/tree/release-v2-playbackparams).
I tested with S7 again just before, and had same problem with frame drop.
I used Widevine Dash: MP4,H264 - WV: Secure HD (MP4, H264) sample in Exo Player demo, then change speed to 2.0x when playback.

**Comment by ojw28** [comment]
@wvpaf - Do we know what platform build we expect the Samsung fixes to land in? It would be good if we could share this; otherwise it's difficult to distinguish between "still broken" and "fixed from build X as expected" :). Thanks!

**Comment by wvpaf** [comment]
@ojw28 no details from the OEM representative yet other than SS has a fix. Waiting on details.

**Comment by workspace** [comment]
@wvpaf is there any detail from Samsung?? Approximately 70% of users in my service use samsung devices (in API >= 23) and they'd like to play video faster/slower. So, it is a quite serious problem for my service... Thanks!

**Comment by wvpaf** [comment]
Looks like S2 Tabs will get update in Feb/Mar, no word on S7.

**Comment by workspace** [comment]
@wvpaf @ojw28 Android Nougat Update for S7 solve this issue! I checked it, however, Galaxy Note 5, Galaxy S6 or other samsung devices seem to have the same issue yet. I guess...samsung will solve this issue with Nougat update for each devices.

**Comment by wvpaf** [comment]
@KiminRyu - thank you for the update. Yes Samsung will need to issue updates to those devices too.
