### ISSUE TITLE
Some HLS videos don't play - Stuck in Preparing State

### ISSUE THREAD

**Issue by ssenanayake** [google/ExoPlayer#1766]
Sample Video: http://ios-streaming.cnet.com/mpx/hls/2016/08/19/747447363521/Baby_Monitor_Capsule_892578_800/Baby_Monitor_Capsule_892578_800.m3u8

Exoplayer version is 1.5.10. It remains in Preparing State. Video plays well on Safari, VLC.

**Comment by ojw28** [comment]
This sample works fine for me in 1.5.10 using the demo app. Closing because we cannot reproduce, and because most of the requested information in the issue template was not provided.
