### ISSUE TITLE
Don't You bother that ExoPlayer instantiates huge part of the extractors during 'sniffing'?

### ISSUE THREAD

**Issue by Avetri** [google/ExoPlayer#1767]
Don't You bother that ExoPlayer instantiates huge part of the extractors during 'sniffing'?

sniff() isn't a static method. So the player creates an instance of extractor to sniff.
And than creates another one to play.

That instantiation is being repeated many time in the shot period before start playing. It causes high load on VM, CPU and memory in slow system with limited recources.

**Comment by Avetri** [comment]
UPD: All the extractors:

<pre>
for (int i = 0; i < extractors.length; i++) {
        try {
          extractors[i] = DEFAULT_EXTRACTOR_CLASSES.get(i).newInstance();
...
</pre>

**Comment by ojw28** [comment]
I wouldn't classify 11 as "many". Do you have any concrete numbers on what the overhead actually is? I really wouldn't expect it to be significant; there's nothing fundamentally expensive about the extractor classes from an instantiation point of view.

As an aside, note that you can pass just the extractors that you want to use to the constructor, if you know what type of media you're playing in advance.

**Comment by Avetri** [comment]
Ok, I understand. Thanks.
But I still think that static sniff() would be more preferable.

**Comment by ojw28** [comment]
Without numbers there's nothing to justify that claim. I suspect the instantiation overhead is negligible (certainly compared to something like inflating a view hierarchy or instantiating a decoder, both of which I'd expect to be at least an order of magnitude more expensive).

Note also that it's non-trivial to simply make the sniff implementations static. Some of the sniff implementations require large parts of the extractors, so you'd end up making a whole bunch of stuff static (which you'd then end up having to instantiate again inside of a concrete extractor should the sniffing be successful).

Closing for now. Feel free to reopen if you have concrete numbers showing a significant overhead.
