### ISSUE TITLE
seekTo() buffering data while an audio stream. 

### ISSUE THREAD

**Issue by roixa** [google/ExoPlayer#1768]
I tried to use simple implementation of exoplayer. 

`exoPlayer=ExoPlayer.Factory.newInstance(RENDERER_COUNT,minBufferMs,minRebufferMs);

 DefaultUriDataSource dataSource = new DefaultUriDataSource(getApplicationContext(),
                Util.getUserAgent(getApplicationContext(), StreamService.class.getSimpleName()));

Allocator allocator = new DefaultAllocator(BUFFER_SEGMENT_SIZE);

extractorSampleSource = new ExtractorSampleSource(Uri.parse(url),
                dataSource, allocator, BUFFER_SEGMENT_COUNT \* BUFFER_SEGMENT_SIZE);

audioTrackRenderer=new MediaCodecAudioTrackRenderer(extractorSampleSource, MediaCodecSelector.DEFAULT);
        exoPlayer.prepare(audioTrackRenderer);
        exoPlayer.setPlayWhenReady(true);`

`seekTo()` executes only in 2 variants. `exoPlayer.seekTo(exoPlayer.getCurrentPosition())`  continue streaming. With any other params, exoplayer executes seekTo(0). 
This is bug? If not how to solve this problem?

`url=" http://online.radiorecord.ru:8101/rr_128"`

**Comment by ojw28** [comment]
You're playing an unseekable live stream (i.e. seeking is not possible). Hence this is working as intended.
