### ISSUE TITLE
Change resolution faster with hls

### ISSUE THREAD

**Issue by grosalex** [google/ExoPlayer#1777]
Hi,

Is there a way to switch hls resolution depending on network faster? 
It takes something like 10s to get to my higher resolution when I'm having a real good connection I'd like it take only something likes 2s.

Any idea?

Regards,

**Comment by Avetri** [comment]
I have an idea.

I think You should change length of chunks.

**Comment by grosalex** [comment]
Hi, thanks for your answear but how can I do that?

Regards,

**Comment by Avetri** [comment]
You can do that if You have some relation to that HLS's source.
We saw the same issue on different players in a few operator networks when admins make wrong (too long chunks, 10 second and more) configuration of chunks cutter.

**Comment by grosalex** [comment]
yes but we don't have this issu with iOs playing the same video :/

**Comment by Avetri** [comment]
:) It's a natural situation if we look at who is creator of HLS.
They support all the versions of standard. And have know-how to avoid problematic places like switching to another quality before chunk end.

Could You attach URL or sample of that HLS's playlists?

And somebody from the player's authors should look at this issue too.

**Comment by Avetri** [comment]
We had many issues on our hardware players with HLS. But iOs has none of them, as like as VLC (pure SW player).

**Comment by grosalex** [comment]
Ok so I think I'm going to deal with chunck length as you said.

Thanks for your time and your answears :)

**Comment by AquilesCanta** [comment]
Have you tried V2? I am not sure, but since there have been many loading policy changes, you might note improvement. Give it a try and let me know how it goes.

**Comment by AquilesCanta** [comment]
Our HLS implementation is now undergoing some major design changes that should come into effect before long. So please have some patience if you encounter strange behaviors(specially regarding live content). The bug fixes have priority, so that should be solved shortly. Looking forward to your reply.

**Comment by gabriel-araujjo** [comment]
Transport Streams have time synchronization in packet headers. A solution
to fast switch may be use this field.

Em 26 de ago de 2016 06:49, "Santiago Seifert" notifications@github.com
escreveu:

**Comment by ojw28** [comment]
Quality switches up a lot faster in V2 (playing the demo app test streams I quite often see switching up as quickly as ~3s on a fast WiFi connection).
