### ISSUE TITLE
does the edge case of returning play back state as PREPARING instead of IDLE still hold true in DemoPlayer

### ISSUE THREAD

**Issue by keerthikorrapati** [google/ExoPlayer#1780]
I noticed this edge case while getting play back state in DemoPlayer:
    int playerState = player.getPlaybackState();
    if (rendererBuildingState == RENDERER_BUILDING_STATE_BUILT && playerState == STATE_IDLE
{
      // This is an edge case where the renderers are built, but are still being passed to the
      // player's playback thread.
      return STATE_PREPARING;
}
Does this edge case still hold true?

There is a case where I would need to call exoplayer.stop() after the renderers are built. Is it safe to set rendererBuildingState to RENDERER_BUILDING_STATE_IDLE so that I would get the correct playback state (ExoPlayer.STATE_IDLE in this case).

**Comment by ojw28** [comment]
The case has gone away in ExoPlayer V2. It still applies as far as I'm aware in V1.
