### ISSUE TITLE
HlsSampleSource alternative audios

### ISSUE THREAD

**Issue by Duna** [google/ExoPlayer#1784]
HlsSampleSource alternative audios have the same language as the primary muxed audio even in the manifest it is different one
Issue comes from HlsSampleSource.java line 568 at buildTracks(HlsExtractorWrapper extractor)

The correct code is:

```
else {
        extractorTrackIndices[trackIndex] = i;
        chunkSourceTrackIndices[trackIndex] = -1;
        **trackFormats[trackIndex++] = format.copyWithLanguage(format.language == null ? language : format.language);**
      }
```

**Comment by AquilesCanta** [comment]
This will be fixed in version 1 as well in the next push.
