### ISSUE TITLE
Handle Raw Audio data [Question]

### ISSUE THREAD

**Issue by pedronveloso** [google/ExoPlayer#1790]
I've looked at the documentation and I haven't found a way to handle the raw (decoded) audio. I see that there's a AudioTrack class, should that be used? And how?

My use case is that I want to do my own visualizer, don't want to rely on the OS-provided one because that one is leading to crashes on some devices, specially on Android M. With `MediaCodecAudioTrackRenderer` I have access to `processOutputBuffer` but that seems to be the encoded data still, is that correct?

**Comment by ojw28** [comment]
The buffers passed to `processOutputBuffer` hold decoded audio. This will usually be 16 bit PCM, but in certain cases can be 8/24/32 bit PCM instead. You can look at `MediaCodecAudioTrackRenderer.pcmEncoding` to determine which case you're seeing.

As an additional note: The semantics of `processOutputBuffer` are somewhat unclear in ExoPlayer V1, which might be causing some confusion. In ExoPlayer V2 we've tightened this up significantly. See the documentation [here](https://github.com/google/ExoPlayer/blob/dev-v2/library/src/main/java/com/google/android/exoplayer2/mediacodec/MediaCodecRenderer.java#L956).

**Comment by pedronveloso** [comment]
@ojw28 That answers my question, thank you! Got it working :)

The `pcmEncoding` its hidden, which made me re-implement the method that calculates it when extending `MediaCodecAudioTrackRenderer`. Not critical, but it would be useful to be able to read such property from an subclass.

**Comment by Kexiliu** [comment]
Hi, Pedro, 

I was also trying to modify the raw decoded pcm data, but the processed data has some noises/artifacts (the audio processing itself is correct and simple (adjusted the gain), verified before). have you experience this before?

**Comment by pedronveloso** [comment]
@Kexiliu Only saw this now. Not that I noticed, but then again I was playing stuff that was recorded from the phone's microphone so it 'naturally' contains some background noise, but nothing that sounded out of place.

**Comment by Kexiliu** [comment]
@pedronveloso no worries. The problem is solved now. :)
