### ISSUE TITLE
EIA608 subtitles enabled unconditionally by TsExtractor

### ISSUE THREAD

**Issue by tresvecesseis** [google/ExoPlayer#1793]
The TsExtractor adds a subtitle track unconditionally when it enables an H264 video track, to be able to see another type of subtitles (as in pull request #1781) I had to promote my subtitles modifying the DefaultTrackSelector.java even if there are not any EIA608 subtitles in the stream.

``` java
diff --git a/library/src/main/java/com/google/android/exoplayer2/trackselection/DefaultTrackSelector.java b/library/src/main/java/com/google/android/exoplayer2/trackselection/DefaultTrackSelector.java
index fabed81..13b0212 100644
--- a/library/src/main/java/com/google/android/exoplayer2/trackselection/DefaultTrackSelector.java
+++ b/library/src/main/java/com/google/android/exoplayer2/trackselection/DefaultTrackSelector.java
@@ -29,6 +29,7 @@ import com.google.android.exoplayer2.Format;
 import com.google.android.exoplayer2.RendererCapabilities;
 import com.google.android.exoplayer2.source.TrackGroup;
 import com.google.android.exoplayer2.source.TrackGroupArray;
+import com.google.android.exoplayer2.util.MimeTypes;
 import com.google.android.exoplayer2.util.Util;
 import java.lang.reflect.Method;
 import java.util.ArrayList;
@@ -513,6 +514,9 @@ public class DefaultTrackSelector extends MappingTrackSelector {
             } else {
               trackScore = 1;
             }
+//        HACK: force dvb subtitle
+          } else if (format.sampleMimeType.equals(MimeTypes.APPLICATION_DVBSUBS)) {
+            trackScore = 6;
           } else {
             trackScore = 0;
           }
```

With the support of multiple tracks of the same type this is not longer an issue (you could select other subtitles) but the first subtitle is, everytime, a fake one in our case. If it's not possible to detect reliably the presence of EIA608 subtitles, could you put its support behind a FLAG?

**Comment by AquilesCanta** [comment]
The reason behing the fake CEA reader (and the type mapping originally forced as well) is HLS. If I remember correctly, the muxed CEA tracks could appear intermittently, which was problematic. Once we add support for multiple CC channels, this should be fixed. For the time being, considering we don't have any way of handling the lifecycle of the CC channels (even if it is a single one), we cannot add the flag just yet. I am tracking this enhancement with #1677.
