### ISSUE TITLE
lot of drop frames want i read local movie in widevine level 3

### ISSUE THREAD

**Issue by guillaumemarc** [google/ExoPlayer#1794]
hi,
I use smartphone without level  1 so i use level 3 on hd content i disable the security on exoplayer do not read hd contain without level 1 
it work and i can read the movie but i have lot of drop frame

```
$ adb logcat |grep drop
D/EventLogger( 2272): droppedFrames [58.52, 50]
D/EventLogger( 2272): droppedFrames [99.03, 50]
D/EventLogger( 2272): droppedFrames [161.07, 50]
D/EventLogger( 2272): droppedFrames [204.97, 50]
D/EventLogger( 2272): droppedFrames [214.45, 50]
D/EventLogger( 2272): droppedFrames [228.13, 50]
D/EventLogger( 2272): droppedFrames [307.03, 50]
D/EventLogger( 2272): droppedFrames [409.83, 50]
D/EventLogger( 2272): droppedFrames [452.40, 50]
D/EventLogger( 2272): droppedFrames [500.86, 50]
D/EventLogger( 2272): droppedFrames [557.45, 50]
D/EventLogger( 2272): droppedFrames [644.05, 50]
D/EventLogger( 2272): droppedFrames [719.84, 50]
D/EventLogger( 2272): droppedFrames [760.62, 50]
D/EventLogger( 2272): droppedFrames [787.83, 50]
D/EventLogger( 2272): droppedFrames [886.00, 50]
D/EventLogger( 2272): droppedFrames [957.45, 50]
D/EventLogger( 2272): droppedFrames [1,022.79, 50]
D/EventLogger( 2272): droppedFrames [1,114.74, 50]
D/EventLogger( 2272): droppedFrames [1,203.59, 50]
D/EventLogger( 2272): droppedFrames [1,209.05, 50]
D/EventLogger( 2272): droppedFrames [1,227.27, 50]

```

sometime the video freeze during 2 second 
do you have a idea to solve this issue 

 i use exoplayer 1.5.6

**Comment by ojw28** [comment]
The issue template clearly requests significantly more information than you've provided, including a full bug report (output of `adb bugreport`) and additional information about the types of devices on which you see this issue, and the versions of both Android and ExoPlayer. Please provide this information. Thanks.

**Comment by guillaumemarc** [comment]
hi you can find my bug report https://drive.google.com/a/skylights.aero/file/d/0B39SzYITUl6rSVYtVWZBNV96TDA/view?usp=sharing
i understand much better my issue on my device with the content provide on the demo app or my, if a have 2 steam playback in the same time( audio + video ) the dropframe appear but if i only playback the stream video i have not any more the issue.

**Comment by wvpaf** [comment]
@guillaumemarc  Can you monitor the CPU usage on the device, you may be overrunning the device's capabilities.

**Comment by wvpaf** [comment]
Hi have not received an update in 4 weeks will close if no new data.
