### ISSUE TITLE
How can i encapsulation Exoplayer to a View

### ISSUE THREAD

**Issue by orbatm** [google/ExoPlayer#1795]
I try to encapsulation PlayerActivity to a View，but it is not fluent，can you help me ??

**Comment by orbatm** [comment]
i find my problem,...i had put 2 ExoView in my layout ,and it will be unfluent...but why.?!.only one of them is playing..

**Comment by ojw28** [comment]
Closing because question is vague and does not provide sufficient information for us to be able to help.
