### ISSUE TITLE
[Q] MPEG-DASH from a secure storage

### ISSUE THREAD

**Issue by j-garin** [google/ExoPlayer#1796]
Hi.

I want to use ExoPlayer to play files from a secure storage. I can get the file from the server using a GET request to a certain static endpoint with file path/name and auth token specified in the header. I am using ExoPlayer 1.5.3 with DashRendererBuilder and OkHttpDataSource from Demo app.
The mpd file loads just fine, but then ExoPlayer attempts to load mp4 files by adding <BaseURL> to the endpoint, which doesn't work. Please give me some hints on how i can override default and implement required behaviour.

Thank you.

**Comment by ojw28** [comment]
I'm not sure what default behavior you're trying to override. If you're saying that ExoPlayer is requesting the chunks from the wrong URLs then should fix the manifest or the location of the chunks so that they're not wrong?

**Comment by j-garin** [comment]
I have to request all chunks from the same URL, but with different header every time (put the chunk file path into header).

**Comment by ojw28** [comment]
Can you put it in the query part of the URL, rather than a header? If so you could probably do that within the boundaries of the DASH spec. If not, you'll have to modify ExoPlayer at the source level to get what you want. There are a whole bunch of places you could do this. It shouldn't be particularly hard to figure out, but it's not something we support or provide an explicit convenient hook to override for.

**Comment by jeprojects** [comment]
Can you modify/rewrite the URL within exoplayer? For example with okhttp?

Example base URL in mpd:

Http://file.com?header=headervalue

Then okhttp could use the information from that URL to create the headers to something like:

Headers
Header: headervalue

Request URL
Http://file.com

**Comment by ojw28** [comment]
That would be one way of doing it, yes. There's no particular need to use okhttp though. You could create a `DataSource` that wraps some other `DataSource`, re-writes the URL, and then passes the re-written `DataSpec` on the the wrapped `DataSource`. Such an approach would work with any wrapped `DataSource` (e.g. default/okhttp/cronet).

**Comment by j-garin** [comment]
ojw28, please give me a hint. Where and how are the urls for new chunks of data built?

**Comment by ojw28** [comment]
The two posts above should serve as a good starting point for working out a way of doing this. If you want to change the URLs where they're built, look in the dash package.
