### ISSUE TITLE
can not play FLAC URL 

### ISSUE THREAD

**Issue by nezen** [google/ExoPlayer#1799]
I want to play a flac and it turns out do not work. I just paste the code below to the demo_ext. I can make sure the url is available on my local network, the .so lib is loaded and the flac is playable on some others player. I also tried several flac files but never make it so far.

```

    private static final int BUFFER_SEGMENT_SIZE = 64 * 1024;
    private static final int BUFFER_SEGMENT_COUNT = 16;

    Uri uri = Uri.parse("http://192.168.0.101:49152/759ca69e8794f6a89359530cbb149c2e.flac");
    ExoPlayer player = ExoPlayer.Factory.newInstance(1);
    player.addListener(new ExoPlayer.Listener() {
      @Override
      public void onPlayerStateChanged(boolean playWhenReady, int playbackState) {
        Log.d("test", "onPlayerStateChanged:" + playbackState);
      }

      @Override
      public void onPlayWhenReadyCommitted() {

      }

      @Override
      public void onPlayerError(ExoPlaybackException error) {
        Log.d("test", "onPlayerError" + error.toString());
      }
    });

    ExtractorSampleSource sampleSource = new ExtractorSampleSource(
            uri,
            new DefaultUriDataSource(this, Util.getUserAgent(this, "ExoPlayerExtFlacTest")),
            new DefaultAllocator(BUFFER_SEGMENT_SIZE), BUFFER_SEGMENT_SIZE * BUFFER_SEGMENT_COUNT);

    LibflacAudioTrackRenderer audioRenderer = new LibflacAudioTrackRenderer(sampleSource);
    player.prepare(audioRenderer);
    player.setPlayWhenReady(true);

```

the log doesn't provide much info and no errors.

09-06 10:35:48.282 9930-9930/com.google.android.exoplayer.demo.ext D/test: onPlayerStateChanged:1
09-06 10:35:48.363 9930-9930/com.google.android.exoplayer.demo.ext D/test: onPlayerStateChanged:2
09-06 10:35:48.874 9930-9930/com.google.android.exoplayer.demo.ext D/test: onPlayerStateChanged:5

**Comment by nezen** [comment]
I checked the mediaplayer, but it didn't work either. 

09-06 11:15:59.730 8128-8128/test.com.servicetest W/MediaPlayer: Couldn't open file on client side; trying server side: java.io.FileNotFoundException: No content provider: http://192.168.0.101:49152/759ca69e8794f6a89359530cbb149c2e.flac
09-06 11:15:59.748 8128-8128/test.com.servicetest E/MediaPlayer: Unable to create media player

**Comment by andrewlewis** [comment]
Are you certain the device can access the private address in the URL? Can you play other URLs to FLAC streams using ExoPlayer or MediaPlayer?

To help diagnose this it would be useful to have a public URL to the file, posted here or emailed to dev.exoplayer@gmail.com, and a bug report taken just after trying to play the stream (output by `adb bugreport`).

**Comment by nezen** [comment]
I found actually the MediaPlayer can play the flac URL(I forgot to declare the "android.permission.INTERNET" permission, really sorry for this). but exoplayer still do not work(with INTERNET permission granted).  I can also play the url with VLC on my mac. 
Here is a url and I hope you can access: http://www.zaishuxia.com/music/files/pingfanzhilu.flac

**Comment by andrewlewis** [comment]
That stream plays fine for me when I add it to the samples in the (otherwise unmodified) demo_ext app on the latest code in the dev-v1 branch. Could you try reverting your modifications, check that the stream plays and then figure out how your code differs?

If you find that it doesn't play in the unmodified demo_ext app, please post a full bug report (instructions in my previous comment) and I will reopen the issue and investigate further. Thanks.
