### ISSUE TITLE
IllegalStateException playing MP4 and DASH with specific resolution

### ISSUE THREAD

**Issue by mromer** [google/ExoPlayer#1806]
I have two instances of Exoplayer, first one plays a MP4 and when it finishes, it starts the second Exoplayer with the DASH content. The problem is that it crashes when the resolution of the MP4 is equal to the first representation of the DASH. In any other case, playback is fine. 
For example:
MP4=320x142 and first representation of DASH = 320x142 -> crashes
MP4=480x270 and first representation of DASH = 320x142 -> works fine

First player is using com.google.android.exoplayer.demo.player.ExtractorRendererBuilder and second player com.google.android.exoplayer.demo.player.DashRendererBuilder (from the demo project).

The process is: Exoplayer with DASH is prepared in order to get the license. If license is fine, it releases the surface, then Exoplayer with MP4 is created and MP4 playback starts. When it finishes, it is released and Exoplayer with DASH gets the surface and it starts the playback. In that moment I get this trace: 

```
09-07 18:00:29.346 26658-28560/com.myapp E/ACodec: signalError(omxError 0x80001001, internalError -62)
09-07 18:00:29.347 26658-28559/com.myapp E/MediaCodec: Codec reported err 0xffffffc2, actionCode 0, while in state 6
09-07 18:00:29.352 26658-28560/com.myapp E/Surface: getSlotFromBufferLocked: unknown buffer: 0x8ffc7f50
09-07 18:00:29.352 26658-28560/com.myapp E/ACodec: queueBuffer failed in onOutputBufferDrained: -22
09-07 18:00:29.353 26658-28560/com.myapp E/ACodec: signalError(omxError 0x80001001, internalError -22)
09-07 18:00:29.355 26658-28559/com.myapp E/MediaCodec: Codec reported err 0xffffffea, actionCode 0, while in state 0
09-07 18:00:29.358 26658-27313/com.myapp E/ExoPlayerImplInternal: Internal runtime error.
         java.lang.IllegalStateException
             at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
             at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2379)
             at com.google.android.exoplayer.MediaCodecTrackRenderer.drainOutputBuffer(MediaCodecTrackRenderer.java:890)
             at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:512)
             at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:129)
             at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:434)
             at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
             at android.os.Handler.dispatchMessage(Handler.java:98)
             at android.os.Looper.loop(Looper.java:148)
             at android.os.HandlerThread.run(HandlerThread.java:61)
             at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
```

This is failing only for some devices: i.e Nexus 6. Android version 6.0.1
It works on Samsung Galaxy S6. Android version 6.0.1

Is there some problem switching between renderers? Does someone know why with different resolutions it woks fine on any device and with the same resolution it crashes on some devices?

Exoplayer version r1.5.9

**Comment by ojw28** [comment]
It's quite difficult to debug this kind of thing, since it's more likely than not that the issue is somewhere in your code (which we don't have :)). I'm not sure why the resolutions would be relevant I'm afraid.

One thing that can cause this kind of failure is when two decoders end up having a reference to the Surface at the same time, so you should definitely double check that this isn't the case. You must null out the Surface from one player (or release the player) before passing the Surface to the next player. If you're nulling out the Surface you must do so using a blocking message rather than a non-blocking one to ensure thread safety. Releasing the player is blocking as standard, so that approach would be fine.

As an aside, playlists in ExoPlayer 2.x will probably help you a lot with this use case.

**Comment by mromer** [comment]
I can't reproduce the issue with the version r1.5.10
Thanks again for your help :)
