### ISSUE TITLE
ExoPlayer occupies much more memory than MediaPlayer

### ISSUE THREAD

**Issue by huyn** [google/ExoPlayer#1809]
I compared the memory taken by both MediaPlayer and ExoPlayer and monitored by Memory Monitor tool in AndroidStudio. I played the same video(s) by MediaPlayer and ExoPlayer, and I found that memory line did not change when MediaPlayer was used, but it increased to a high level when ExoPlayer was used.
Please take a look at the attachment.
ExoPlayer was uesed from 15s to 1min in timeline, I switched it to MediaPlayer and performed gc from 1min5s. The gap was about 40-50M.
![image](https://cloud.githubusercontent.com/assets/946055/18335808/cab5cf7a-75b4-11e6-98e3-68e8d2a06239.png)

**Comment by ojw28** [comment]
It's not that ExoPlayer uses more memory, but rather than the memory is allocated in a different place. When using ExoPlayer, the media buffer is allocated within your process. When using MediaPlayer, the media buffer is allocated within one of the MediaServer processes.

**Comment by huyn** [comment]
@ojw28 Does the argument `requestedBufferSize` of `ExtractorSampleSource` influence it?
Thanks for your answer.

**Comment by ojw28** [comment]
You can change the size of the media buffer by tweaking parameters such as that one, yes. Obviously making the media buffer smaller increases the probability of re-buffers for network streamed media. If you're playing local content only it's generally safe to reduce it quite a bit. Note that when using MediaPlayer you have no control over the size of the buffer allocated in the MediaServer process.

**Comment by huyn** [comment]
@ojw28 I got another problem :( . When I played three MP4 videos at the same time in one activity, so there were three ExoPlayers playing and three mediacodec decoding. But I found threes players freezed frequently because of frame drop. I am sure that it has nothing to do with the cache. 
Here is the log:
```
09-08 19:08:48.537 12956-12956/com.aube.phone I/EXO: 8720===onDroppedFrames:50/4819
09-08 19:08:53.010 12956-12956/com.aube.phone I/EXO: 8673===onDroppedFrames:50/7946
09-08 19:08:56.537 12956-12956/com.aube.phone I/EXO: 8720===onDroppedFrames:50/7968
09-08 19:08:56.923 12956-12956/com.aube.phone I/EXO: 8719===onDroppedFrames:50/8556
09-08 19:08:58.566 12956-12956/com.aube.phone I/EXO: 8673===onDroppedFrames:50/5569
09-08 19:09:01.370 12956-12956/com.aube.phone I/EXO: 8720===onDroppedFrames:50/4854
09-08 19:09:01.455 12956-12956/com.aube.phone I/EXO: 8719===onDroppedFrames:50/4462
09-08 19:09:03.009 12956-12956/com.aube.phone I/EXO: 8673===onDroppedFrames:50/4465
09-08 19:09:10.272 12956-12956/com.aube.phone I/EXO: 8719===onDroppedFrames:50/8868
09-08 19:09:10.512 12956-12956/com.aube.phone I/EXO: 8720===onDroppedFrames:50/9151
09-08 19:09:11.170 12956-12956/com.aube.phone I/EXO: 8673===onDroppedFrames:50/8161
09-08 19:09:15.311 12956-12956/com.aube.phone I/EXO: 8719===onDroppedFrames:50/5051
09-08 19:09:17.485 12956-12956/com.aube.phone I/EXO: 8720===onDroppedFrames:50/6943
09-08 19:09:18.326 12956-12956/com.aube.phone I/EXO: 8673===onDroppedFrames:50/7111
09-08 19:09:25.345 12956-12956/com.aube.phone I/EXO: 8719===onDroppedFrames:50/10030
09-08 19:09:26.317 12956-12956/com.aube.phone I/EXO: 8720===onDroppedFrames:50/8850
09-08 19:09:27.118 12956-12956/com.aube.phone I/EXO: 8673===onDroppedFrames:50/8823
09-08 19:09:31.603 12956-12956/com.aube.phone I/EXO: 8719===onDroppedFrames:50/6270
09-08 19:09:33.409 12956-12956/com.aube.phone I/EXO: 8720===onDroppedFrames:50/7092
09-08 19:09:34.537 12956-12956/com.aube.phone I/EXO: 8673===onDroppedFrames:50/7426
09-08 19:09:37.736 12956-12956/com.aube.phone I/EXO: 8719===onDroppedFrames:50/6129
09-08 19:09:39.620 12956-12956/com.aube.phone I/EXO: 8720===onDroppedFrames:50/6193
09-08 19:09:39.702 12956-12956/com.aube.phone I/EXO: 8673===onDroppedFrames:50/5108
09-08 19:09:48.089 12956-12956/com.aube.phone I/EXO: 8719===onDroppedFrames:50/10350
09-08 19:09:48.732 12956-12956/com.aube.phone I/EXO: 8720===onDroppedFrames:50/9137
```
Looking forward to your advices

**Comment by ojw28** [comment]
Please file separate issues for unrelated problems. Although in this case there are a few issues already if you search for issues about multiple videos being played. You're likely just exceeding the limitations of the device.
