### ISSUE TITLE
Is there some example to show how to use the Mp3Extractor? who can help me?

### ISSUE THREAD

**Issue by hezhisu** [google/ExoPlayer#1810]
Please search the existing issues before filing a new one, including issues that
are closed. When filing a new issue please include all of the following, unless
you're certain that they're not useful for the particular issue being reported.
- A description of the issue.
- Steps describing how the issue can be reproduced, ideally in the ExoPlayer
  demo app.
- A link to content that reproduces the issue. If you don't wish to post it
  publicly, please submit the issue, then email the link to
  dev.exoplayer@gmail.com including the issue number in the subject line.
- The version of ExoPlayer being used.
- The device(s) and version(s) of Android on which the issue can be reproduced,
  and how easily it reproduces. If possible, please test on multiple devices and
  Android versions.
- A bug report taken from the device just after the issue occurs, attached as a
  file. A bug report can be captured using "adb bugreport". Output from "adb
  logcat" or a log snippet is not sufficient.

**Comment by andrewlewis** [comment]
To play MP3s you would normally use ExtractorSampleSource (in v1) or ExtractorMediaSource (in v2). These use Mp3Extractor internally, but for simple use cases your app does not need to refer to Mp3Extractor directly.

If you are using the release-v1 branch, take a look at [ExtractorRendererBuilder](https://github.com/google/ExoPlayer/blob/release-v1/demo/src/main/java/com/google/android/exoplayer/demo/player/ExtractorRendererBuilder.java#L64). For dev-v2, the ExtractrorMediaSource is created [here](https://github.com/google/ExoPlayer/blob/dev-v2/demo/src/main/java/com/google/android/exoplayer2/demo/PlayerActivity.java#L351).

If you are trying to do something specific with Mp3Extractor (not just play an MP3), please provide some more details.

**Comment by hezhisu** [comment]
use the ExtractorSampleSource , when i play at 50's, then i seek to 26's, actually the sound exceed 26's

**Comment by hezhisu** [comment]
use the ExtractorSampleSource , when i play at 50's, then i seek to 26's, actually the sound exceed 26's @andrewlewis

**Comment by andrewlewis** [comment]
It sounds like the issue you are seeing is that when you seek to a particular timestamp you hear media from a different timestamp. Seeking in variable bitrate MP3 streams is generally not exact, because the file header doesn't always provide a complete map from timestamp to byte offset. See also https://github.com/google/ExoPlayer/issues/328#issuecomment-168532148.

The fix is to use a different container with complete metadata, like MP4 or Matroska.

**Comment by ojw28** [comment]
Andrew's comment above is correct. If the media contains insufficient information to seek accurately, ExoPlayer will not seek accurately. There exist plenty of container formats that allow for accurate seeking.
