### ISSUE TITLE
Axinom Encrypted DASH video only plays for a few seconds in ExoPlayer 1.x

### ISSUE THREAD

**Issue by sandersaares** [google/ExoPlayer#1811]
We recently updated the Axinom DASH test vectors to target slightly more modern workflows and industry association specifications. Testing of this content with ExoPlayer revealed some issues. I report the main issue discovered here, possibly a few more to come later once we exclude some potential alternative causes for them.

The video in question is **v7-MultiDRM-SingleKey** from https://github.com/Axinom/dash-test-vectors. We tested the 1080p variant (which exhibits this issue) and the audio-only variant which played correctly. The v7-Clear video (same content, no encryption) played correctly.

We tested in a custom app that is basically the ExoPlayer demo app modified to target the Axinom license server, based on the instructions you find in the above test vectors repository. We plan to also test with ExoPlayer v2 branch soon. I do not currently have ready-made code to share to reproduce it but it should be fairly trivial to modify the demo app (just add the license token header and point it at the right license server URL).

ExoPlayer version: 1.5.10.

Device: Nexus 9 (running Android 7).

**Issue description**: Picture freezes after few (sometimes more) seconds of playback, sound will still play for around 20 to 30 seconds. But after that, sound also stops and android loading animation is shown. Failure can be seen in the log v7-MultiDRM-SingleKey - 1080p variant.txt.

Picture stops right before these lines are recorded in log:

```
09-08 14:54:46.705: E/(201): GraphicBufferAlloc::createGraphicBuffer(w=1920, h=1088) failed (Out of memory), handle=0x0
09-08 14:54:46.705: E/BufferQueueProducer(201): [SurfaceView - com.axinom.sample.vtbapp.exoplayer/com.axinom.support.MediaPlayerActivity] dequeueBuffer: createGraphicBuffer failed
09-08 14:54:46.705: E/ACodec(2744): dequeueBuffer failed: NO_MEMORY(-12).
```

More detailed log output attached: [v7-MultiDRM-SingleKey - 1080p variant.txt](https://github.com/google/ExoPlayer/files/463545/v7-MultiDRM-SingleKey.-.1080p.variant.txt)

Bug report attached: [report.zip](https://github.com/google/ExoPlayer/files/463955/report.zip)

**Comment by sandersaares** [comment]
Bug report attached.

**Comment by ojw28** [comment]
Hmm, the sample plays back fine for me on the same device + build combination.

**Comment by ojw28** [comment]
Not that you should ever have to do this, but does rebooting the device resolve the issue for you?

**Comment by sandersaares** [comment]
Interesting. We will dig deeper.

Additionally, we have applied a hotfix to the content - the sample aux info size in `saiz` was incorrect. However, as ExoPlayer did successfully play back at least partial content, I assume ExoPlayer was not affected by this. Still, we will re-test and report back on our findings.

**Comment by ojw28** [comment]
It is possible that the `saiz` issue was the root cause of the problem. I'd suggest re-testing in any case, since we're unable to reproduce.

**Comment by sandersaares** [comment]
After re-testing we do not see any difference in behavior. We also tested with Android 6 on Nexus 9 and got essentially equivalent behavior:

> Video “v7-MultiDRM-SingleKey” Android 6 crashes with error message which can be seen starting from the line
> 09-12 16:00:03.557   170   189 E BufferQueueProducer: [SurfaceView] setBufferCount: buffer owned by producer
> 
> Android 7 does not show any error message but just freezes (acts as before).

Bug report: [bugreport-2016-09-12-16-10-51.zip](https://github.com/google/ExoPlayer/files/467386/bugreport-2016-09-12-16-10-51.zip)

**Comment by ojw28** [comment]
Could you give the V2 demo app a try. For maximum reproducibility, it's preferable if you could avoid making any changes to the demo app. You can define your content to be loaded into the demo app using a `.exolist.json` file as described in https://github.com/google/ExoPlayer/issues/1812.

It's somewhat unclear how minimal the modification is between the demo app and what you're testing with is (log tags `MediaPlayerFragment`, `BaseMediaPlayer` etc suggest some non-trivial modifications). The test content still plays fine for me (in V1 demo app with minimal modification, and in V2).

Thanks.

**Comment by sandersaares** [comment]
Sure thing. Will report back once we have something that would help you reproduce this (or when we figure out what we are doing wrong on our side).

**Comment by sandersaares** [comment]
I confirm it seems to work fine in ExoPlayer demo app. Not sure why it does not work for us but I suppose that's beside the point.
