### ISSUE TITLE
S3 and S4 playback issues

### ISSUE THREAD

**Issue by philippela** [google/ExoPlayer#1817]
Hi,

I have a problem where the video is initially garbled on Samsung S3 and S4, but then becomes OK later on.

Has this been seen before? Seems pretty obvious and repro-able. What is the solution?

Thanks,
Philippe Laporte

**Comment by ojw28** [comment]
Issue reports that omit nearly all of the requested information in the issue template are not efficient for us to investigate, therefore closing. Please file an issue containing complete information, thanks.
