### ISSUE TITLE
Use SSLSocketFactory with DefaultHttpDataSource

### ISSUE THREAD

**Issue by rsatandroid** [google/ExoPlayer#1819]
Hi Team,

is there any way to set SSLSocketFactory  in DefaultHttpDataSource.

We want to use TrustManager - 
httpsURLConnection.setSSLSocketFactory(sslSocketFactory);

Thanks in advance.

**Comment by ojw28** [comment]
If you're trying to set it globally then you might have some luck calling the static method `HttpsURLConnection.setDefaultSSLSocketFactory()` prior to use of ExoPlayer? Calling the non-static variant is not something we expose, but it would be pretty straightforward for you to make your own `DataSource` implementation that does support this use case.

**Comment by rsatandroid** [comment]
Thank you for your input and such a great library with wide range of capabilities.

As DefaultHttpDataSource uses HttpURLConnection internally so i think setting it on HttpsURLConnection will not help.
I will go with my own DataSource implementation based on DefaultHttpDataSource.
