### ISSUE TITLE
Duplicate file ic_media_pause.png. Please help me !!!

### ISSUE THREAD

**Issue by zzBADzz** [google/ExoPlayer#1823]
Hi, 
When i compile new version v2.0.0 for my project. I see an error:
- app\build\intermediates\res\debug\drawable-hdpi-v4\ic_media_pause.png: error: Duplicate file. 
  I thinks my app've used media-route (In this libs have some ic_media_pause) from google cast api. And then when i build my project i must to have error (duplicate file ic_media_pause.png). Please help me to fix this problem Thanks so much.

**Comment by ojw28** [comment]
According to [this](http://stackoverflow.com/questions/19306819/android-resources-key-collision) there shouldn't be a build problem as a result of a naming clash, so I wonder if you need to do a full clean or whether there's something else wrong with your setup.

Having said that, I think we want to avoid naming conflicts and the app having to choose which resource to retain should one occur. Hence we'll add prefixes to the assets in ExoPlayer to avoid conflicts going forward.
