### ISSUE TITLE
MPEG-DASH live DVR out of memory

### ISSUE THREAD

**Issue by kvolkers** [google/ExoPlayer#1825]
Using the latest dev-v2 (Sep 14, 2016).

When playing an MPEG-DASH live stream and seeking to a certain "large" amount (for example 1 hour) before the live point the app's RAM usage increases until an OutOfMemoryError is thrown.

I have reproduced this using the demo player in combination with a youtube stream such as [this one](https://www.youtube.com/watch?v=y60wDzZt8yg).

What I think might be happening is that the maxBufferMs configured in the LoadControl is not adhered to and it tries to buffer endlessly up to the live point.

If you need any more information let me know and I will try to provide it.

**Comment by ojw28** [comment]
Thanks. We can reproduce this, and will push a change shortly.

**Comment by ojw28** [comment]
This should now be fixed on `dev-v2`, but please give it a try to double check. Thanks!

**Comment by kvolkers** [comment]
Confirmed fixed on latest dev-v2, nice!
