### ISSUE TITLE
enableBackgroundAudio in version 2.0.0 library?

### ISSUE THREAD

**Issue by rsatandroid** [google/ExoPlayer#1826]
Hi Team,
Does v 2.0.0 library supports background audio feature ?
In v1.5.3 we can were having option - enableBackgroundAudio

Thanks.

**Comment by ojw28** [comment]
This was never a feature of the ExoPlayer library. It was a feature of the demo application in previous versions, however note that it wasn't implemented anything like how you'd need to implement background playback in a production quality app. In particular, you'd need to use a foreground [Service](https://developer.android.com/guide/components/services.html) to implement this kind of functionality properly, so as to avoid things like the possibility of your process being killed during background playback.

We removed the feature from the demo app so as to avoid developers believing what we'd done was the right way of implementing background playback.
