### ISSUE TITLE
Issues when playing video h265 with HVC1 codec

### ISSUE THREAD

**Issue by trungd0** [google/ExoPlayer#1831]
Hi Team,
We really love EXO player and we really want to use it for our product.Our product is android boxes running android 4.4.4 .This mainboard  used rockchip rk3128
But now we are having big problem with video in format h265 HVC1 codec.It is stripe up, and it has greenline on the top player.Please see below image.

https://drive.google.com/file/d/0BySdRMqDpCEsYXlSSEpOOHNkdlU/view
I can not understand why, when we use video H265 format with HEVC codec it is normal
Please advise us.Thanks so much

**Comment by ojw28** [comment]
This is most likely an issue with Rockchip's H265 decoder implementation, and you should report it directly to them.

That said, if you're able to provide us with test content using broken and working variants, we can take a more detailed look. It may also be possible for us to come up with an workaround for the issue.

Thanks!

**Comment by ojw28** [comment]
Closing due to insufficient information.
