### ISSUE TITLE
Why most classes in v2 became final?

### ISSUE THREAD

**Issue by ghost** [google/ExoPlayer#1833]
Now it's hard to extend ExoPlayer implementation without forking library source or rewriting huge part of library.

**Comment by ojw28** [comment]
We were seeing a lot of cases where developers were using extension as a convenient but lazy (or worse, incorrect) way of achieving custom behaviors. In such cases it was often better to use composition or some other approach instead, or to make modifications to the library to support the functionality they desired more directly (in a way that all users of the library can benefit from). We made quite a few classes final to try and guide developers in these more correct directions. Note that we did this in V1; this isn't something that's new in V2.

We're happy to remove final modifiers where developers can demonstrate a specific use case for which we agree extension is the best way. So please file specific issues indicating what you're trying to do, and which classes would need to be non-final for it to be possible, and we'll consider them on a case-by-case basis.

**Comment by ghost** [comment]
My case is very specific.

I have issue with hls master playlist I need to play in application. It contains wrongly formated CODECS attribute
https://github.com/google/ExoPlayer/issues/1832
As I see, easiest way to fix it - clean codecs field in master playlist after it was parsed.

It would be done by extending HlsMediaPeriod with 3 extra lines of code, but HlsMediaPeriod and HlsMediaSource are final.

**Comment by ojw28** [comment]
Why don't you just fix the broken media?

**Comment by ghost** [comment]
I do not have influence on server part.  :(
Have to work with this media. Web player they use handles it well.

**Comment by ojw28** [comment]
That doesn't mean they shouldn't fix it. Assuming the content is owned by the same provider for whom the app is being produced, it's difficult to understand why they would refuse to amend the content...
