### ISSUE TITLE
How to crop the library ?

### ISSUE THREAD

**Issue by magical-xu** [google/ExoPlayer#1834]
It 's a good library , but if  I want a most simple function library jar package , how can i crop it to reduce the number of the method. Our project mehod exceeds the limit 65536 , so i want one of the most streamlined version. best wishes.
![image](https://cloud.githubusercontent.com/assets/15309220/18624341/827fa8fc-7e79-11e6-934b-99effbc0fc1a.png)

**Comment by ojw28** [comment]
There is nothing special about how you'd treat ExoPlayer vs any other library when it comes to this issue, so you should just follow the advice [here](https://developer.android.com/studio/build/multidex.html).
