### ISSUE TITLE
Issues playing a local URI video recorded on Nexus 5X, Android 7.0

### ISSUE THREAD

**Issue by vkislicins** [google/ExoPlayer#1835]
This is a very strange issue as it only appears on Nexus 5X running Android 7.0. My best guess is it is related to having several `SurfaceView`s initialised at the same time.

In an essence, my app is a Camera app and I'm using ExoPlayer to preview videos after recording. After recording the video, I replace the video capture fragment (which contains the camera preview surface) with the video preview fragment. My video player fragment will init an instance of ExoPlayer and will attempt to start the playback using a local `ContentProvider` `Uri` object and `ExtractorRendererBuilder`. The video player fragment will also have its own SurfaceView to work with. Like I said, works fine on all the phones I've tested with apart from N5X on 7. This is what I get out of ordinary on that device:

```
09-19 10:52:49.053 2193-3352/W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
09-19 10:52:49.091 2193-3352/I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
```

I've done a significant ammount of testing and noticed that what I see on my surface instead of the video playback, is the last frame of the Camera capture surface. I've checked my code and because my Camera surface is not created as part of the fragment lifecycle, it's also not destroyed at the point when the preview playback surface is created. So I end up with two `SurfaceView`s active and available. I've also checked that the correct (preview) surface is used when I start the playback in the preview fragment, and it is. Also the preview fragment is layered on top of the camera capture fragment. However I still see the last camera frame rather than the video playback. Just to triple check, I've removed all views from my camera preview container (to trigger distruction of the surface) before initialising my video preview fragment, and it finally worked as expected, as in the video was played correctly.

I don't mind removing the views from my camera capture container, probably a good thing anyway, however I'm confused to why this behaviour is happening and why is it only on that specific device or OS level or both.

**Comment by ojw28** [comment]
I'm don't think we have a good answer to this question/problem. It sounds very application specific, to the extent that it may or may not be an issue with application code (although if it is, it's curious that the resulting behavior appears to be device/os specific).

In any case, we can't prioritise investigating the issue vs other stuff, so closing. It sounds like you have a solution to the problem. You could also investigate TextureView, which may behave better for your use case.
