### ISSUE TITLE
When connection is interrupted (for few seconds) the start is delayed of a period equally to the last playback period

### ISSUE THREAD

**Issue by Joseph82** [google/ExoPlayer#1839]
**Description:** When the ExoPlayer is playing a realtime audio stream (mp3 audio codec), if the connection is turned off and, after few seconds, turned on again, the playback will actually start after the previous playback time, also if it is continuing download the data from the stream.

**Explanation:** Let's say we have the following scenario:
- The phone is connect to the wifi and at time t0 = 0 the playback starts.
- At time t1 = t0 + 180 seconds, the wifi is turned off 
- At time t2 = t1 + 5 seconds, the wifi is turned on again
- At time t3 = t2 + 180 seconds the playback starts

The player remains in BUFFERING state for about t1 seconds (180) and then it starts. 
**_NOTE_**: all the data continue to be downloaded (I checked it with [Charles Proxy](https://www.charlesproxy.com/)).

I tried with a lot of different t1 interval. Also for 1 hour or more, and the behaviour is exactly the same: when the wifi connection is re-acquired, before starting to play the Player will wait exactly the last playback duration.

**ExoPlayer version:** 1.5.9

**Devices:** I have verified the same issue on all the devices I tested(1+ One with Android 6.0.1, Nexus 5 with Android 4.4.4, Motorola Moto E with Android 5.0.2)

**Comment by ojw28** [comment]
This issue has been fixed in ExoPlayer 2 (i.e. 2.0.0 and greater). See #1285 for some more discussion about the issue.

**Comment by Joseph82** [comment]
I thought that the 1.x would be still maintained. Indeed I read: _"We will however continue to provide bug fixes for 1.x for the foreseeable future."_ (https://medium.com/google-exoplayer/exoplayer-2-x-its-here-plus-faqs-cce34b0d4c7b#.4gbl48c1y). So if I'm not wrong, this should also be fixed for the ExoPlayer 1.x , isn't it?

**Comment by ojw28** [comment]
It really depends on what the bug is and what's required to fix it. If back-porting a fix requires us to also back-port a bunch of huge architectural changes that allowed the fix to happen, then it's not viable (and is approximately equivalent to you updating to v2 in any case). This is one such case, so you will need to update to v2.
