### ISSUE TITLE
java.lang.VerifyError?

### ISSUE THREAD

**Issue by yanglichuan** [google/ExoPlayer#1841]
java.lang.VerifyError
player/EXOEventLogger
player.EXOPlayerManager.preparePlayer(EXOPlayerManager.java:672)
player.EXOPlayerManager.playUri(EXOPlayerManager.java:421)
com.ks.kaishustory.audioservice.MusicService.play(MusicService.java:214)

**Comment by ojw28** [comment]
Closing due to insufficient information.
