### ISSUE TITLE
Hls with aac audio plays no sound if there is no audio description in the the variant 

### ISSUE THREAD

**Issue by Nisse43** [google/ExoPlayer#1843]
This happens for videostreams that has no audio codec set in the master play list.

Problem is that the workaround in HlsChunkSource.java line 523 cant be disabled.

Atleast ExoPlayer v1 is affected.

**Comment by ojw28** [comment]
Including a CODECS attribute but failing to include the audio format in it is a violation of the HLS spec, as stated in #1832. The broken media should be fixed to resolve this issue.
