### ISSUE TITLE
All video Frames are dropped on some devices/Android builds - Widevine streams - decoding problem

### ISSUE THREAD

**Issue by lkcanal** [google/ExoPlayer#1844]
Hello to the Exoplayer team,

We encounter a serious problem on around 17% of our premium content application users. With our Widevine encrypted streams and the Dash Widevine ones of the Exoplayer Demo, it appears that on some devices and/or Android build, Exoplayer is dropping all video frames. It's like they are facing decryption and decode bugs.
(We are using Explayer 1.5.10-rc)
- Playing the same unencrypted stream plays without any problem.

After analyzing the issue on a One Plus X device I could get the hand on, I found that the device took a very long time to decode the videos buffers. The player do not have time to decode and render the video (processOutputBuffer method in the MediaCodeVideoTrackRender class), and drop the frame:
As other video buffers arrive in the pipeline, all video frames are dropped, the device renders 1,2 or 3 frames and then of course the video freezes.
In the other hand, the audio track is decrypted without any pb. So I tried to limit the playback of our track to the lowest video profile (around 500kbits/sec), and we saw that we have much less video frames dropped, but it's still unwatchabe (1 or 2 frames per sec at at best).

So I identified were in the Exoplayer code the device seems to looses so much time (inside the MediaCodecTrackRenderer class):

```
private boolean feedInputBuffer(long positionUs, boolean firstFeed) throws ExoPlaybackException {
...

if (sampleEncrypted) {
        MediaCodec.CryptoInfo cryptoInfo = getFrameworkCryptoInfo(sampleHolder,
            adaptiveReconfigurationBytes);
        codec.queueSecureInputBuffer(inputIndex, 0, cryptoInfo, presentationTimeUs, 0);
      } else {
        codec.queueInputBuffer(inputIndex, 0, bufferSize, presentationTimeUs, 0);
      }

...
}
```

It's like handling the getFrameworkCryptoInfo method for the device is too much. But it shouldn't. That's why we think it may be a bad implementation of the Widevine/Secure decoder stack in the Android version of the device. 

Another interesting point, is that with a prior update of Android, the device didn't have this kind of problem. And a beta of Android build Marshmallow fixes also the issue. 

I cannot give you for now any logcat or bug reports as I do not have the device anymore.
Here is the model and Android build number of the One Plus X device with the issue:
- Model number: ONE E1003
- Android version: 5.1.1
- Security update date: 07/01/2016
- Build number: ONE E1003_14_160728
- Kernel version: 3.4.0-perf+ OnePlus@ubuntu-56 #1 Thu Jul 28 

As soon as I can get a hand on this device or another with the same issue, I'll post ASAP a logcat and bugreports.

I do not know if there can be a workaround to be done with Exoplayer, if it's really a bad implementation of Widevine or secure decoders on the Android build ?

Thx in advance.

Lilian.

**Comment by ojw28** [comment]
@wvpaf - Could you follow up with the device manufacturer about this; it sounds fairly badly broken? Can we also check that this device will definitely fail some tests we now have in place to prevent this kind of thing going forward?

**Comment by wvpaf** [comment]
@ojw28 thanks for sending our way. we will attempt to get an example of this device and run it up and see what can do.

**Comment by pgrov** [comment]
This playback issues seemed to be resolved after a system upgrade to Android Marshmallow (Oxygen OS 3.1.2).

**Comment by wvpaf** [comment]
Hi @lkcanal,
Can you verify an upgrade to M resolved the issue?

**Comment by lkcanal** [comment]
Helle @wvpaf , yes I confirm that the M update resolved the issue on the One Plus X.
