### ISSUE TITLE
How to change the rule with InitializationTrackSelection?

### ISSUE THREAD

**Issue by b95505017** [google/ExoPlayer#1848]
In v2, there is an `InitializationTrackSelection` in `HlsChunkSource`, which will choose the first track in group.

``` java
   public InitializationTrackSelection(TrackGroup group, int[] tracks) {
      super(group, tracks);
      selectedIndex = indexOf(group.getFormat(0));
    }
```

If I want to choose the middle of the track with the decreasing bandwidth order in the beginning:

``` java
    public InitializationTrackSelection(TrackGroup group, int[] tracks) {
      super(group, tracks);
      selectedIndex = length / 2;
    }
```

How should I do in the preferred way?

**Comment by ojw28** [comment]
HLS playbacks using ExoPlayer are no longer constrained to start with the track given by `InitializationTrackSelection` (this is true at least for the `dev-v2` branch and for all future releases (i.e. 2.3.0 onward). Playback will start using whatever track is selected by the `TrackSelection`, in line with behaviour for DASH and SmoothStreaming.
