### ISSUE TITLE
Error 2998 while streaming on Samsung with OS 5.0.2

### ISSUE THREAD

**Issue by replystreamingwidevine** [google/ExoPlayer#1852]
During the development of an android application with exoplayer, we found an issue with some devices while streaming a video content. Only with devices Samsung with OS 5.0.2 (Lollipop) we get the error code -2998. The error is generated by the provideKeyResponse(sessionId, key) method. 
About the log for us the more relevant issue is the -2998. Here the log:

I/WVCdm   ( 2318): CdmEngine::AddKey
E/wv_dash ( 2318): Key context length should be less than 1KB
E/WVCdm   ( 2318): GenerateDerivedKeys: OEMCrypto_DeriveKeysFromSessionKey err=29
E/WVCdm   ( 2318): CdmEngine::AddKey: keys not added, result = 3
E/MediaDrm-JNI(22632): Illegal state exception: Failed to handle key response: DRM vendor-defined error: -2998 (-2998)
W/System.err(22632): android.media.MediaDrm$MediaDrmStateException: Failed to handle key response: DRM vendor-defined error: -2998
W/System.err(22632): at android.media.MediaDrm.provideKeyResponse(Native Method)
W/System.err(22632): at it.sky.common.player.drm.OnlineStreamingDrmInfoManager.manageRetrievedInfo(OnlineStreamingDrmInfoManager.java:67)
W/System.err(22632): at it.sky.common.player.drm.OnlineStreamingDrmInfoManager.manageRetrievedInfo(OnlineStreamingDrmInfoManager.java:20

Many thanks if you can support us solving this issue

**Comment by wvpaf** [comment]
@replystreamingwidevine  Samsung device is this happening on?  Is it multiple models? Can you provide the names so we can investigate on our end?  Does this work on some Samsung devices? Can you provide some of those model names?

Also are you passing in large optionalParameters in to MediaDrm.getKeyRequest?

**Comment by wvpaf** [comment]
no update in 4 weeks closing.
