### ISSUE TITLE
MergingMediaSource failed when use side loaded Text tracks

### ISSUE THREAD

**Issue by ChernyshovYuriy** [google/ExoPlayer#1853]
Dear colleagues,
In the current ExoPlayer v2, when use side loaded text tracks along side with dash source, there is last track missing in the MergingMediaPeriod#periods field. It results to NullPointerException at the line 180 of the MergingMediaPeriod.java.
I did investigation and found that callback.onPrepared() dispatches too earlier, in fact prior to MediaPeriod added to the array.
Be more specific, there are two callbacks that dispatches prior to MediaPeriod added to the array:
- SingleSampleMediaSource.java, line 103
- DashMediaPeriod.java, line 79

All these callback dispatches prior to MergingMediaSource.java line 120. Upon this callback MergingMediaPeriod decremented counter at the line 175, that leads to the wrong "pendingChildPrepareCount == 0" event and reveal farther logic. Then, when execution reached line 179, there is missing element in "periods" array.

I eliminate this effect temporary by commented callback "callback.onPrepared(this);" on lines 103 and 79 (described above) and modify MergingMediaSource.java:

```
for (int i = 0; i < periods.length; i++) {
      periods[i] = mediaSources[i].createPeriod(index, mergingPeriod, allocator, positionUs);
      Assertions.checkState(periods[i] != null, "Child source must not return null period");
      // Dispatch event only when element is in array
      mergingPeriod.onPrepared(periods[i]);
    }
```

I added media sources as:

```
new MergingMediaSource([DashMediaSource, SingleSampleMediaSource])
```

Also, still a bug in the SingleSampleMediaPeriod.java and it's filed "private byte[] sampleData" line 239. It is necessary to initialize it as well by:

```
private byte[] sampleData = new byte[INITIAL_SAMPLE_SIZE];
```

Otherwise there is NullPointerException at the line 267.
Excuse me for such technical description with dive into code, I hope that you will understand the issue.

**Comment by ChernyshovYuriy** [comment]
I have to notice that in case of no side loaded content we still need a callback dispatched from DashMediaPeriod's constructor. So it would be not an easy solution without know all aspects of the ExoPlayer structure.

**Comment by asapehrsson** [comment]
I have the same problem.

My workaround: Modify MergingMediaPeriod.java, MergingMediaSource.java and SingleSampleMediaPeriod.java.

First, change MergingMediaPeriod.java line 175.

```
if (--pendingChildPrepareCount > 0) {
```

to

```
if (pendingChildPrepareCount-- > 0) {
```

Then add code, MergingMediaSource.java, line 121

```
for (int i = 0; i < periods.length; i++) {
     periods[i] = mediaSources[i].createPeriod(index, mergingPeriod, allocator, positionUs);
    Assertions.checkState(periods[i] != null, "Child source must not return null period");
}
mergingPeriod.onPrepared(null); //added this line
```

Finally initialize sampleData in SingleSampleMediaPeriod.java

**Comment by ojw28** [comment]
@andrewlewis - Fixing this may well link into getting all the `onPrepared` calls onto the right thread.

**Comment by ojw28** [comment]
The issue is best understood by looking at `MergingMediaSource.createPeriod`:

```
periods[i] = mediaSources[i].createPeriod(index, mergingPeriod, allocator, positionUs);
```

Some `createPeriod` calls ends up calling `onPrepared` synchronously, so such calls happen before `periods[i]` is actually set to the period being created. `MergingMediaSource.onPrepared` relies on all entries in `periods` being non-null at the point where `pendingChildPrepareCount` is decremented to 0.
