### ISSUE TITLE
Make cronet release jar downloads publically available

### ISSUE THREAD

**Issue by Brahmasmi** [google/ExoPlayer#1857]
The cronet release jars download link leads to a login page. Could you please make the downloads available on a public location.

Steps to Reproduce:
https://github.com/google/ExoPlayer/tree/release-v2/extensions/cronet/README.md -> Build Instructions -> First point -> Link points to https://console.cloud.google.com/storage/browser/chromium-cronet/android -> Clicking leads to login page for cloud console.

**Comment by ojw28** [comment]
I'm pretty sure you can login with any regular Google account, so just using your personal GMail account, opening one if necessary, should be sufficient.

I agree this is not a good distribution mechanism. @kul3r4 - Can we please have a discussion with the Cronet team and come up with something better?

**Comment by kul3r4** [comment]
Hi, thanks for your interest in Cronet.
We are working on a better solution and will update this sample once that's ready.

**Comment by Brahmasmi** [comment]
@kul3r4 any luck/progress with the better solution? It would help to have a public download location for the cronet release jars. I may be wrong here, but automated builds might benefit from public download locations.

**Comment by kul3r4** [comment]
@Brahmasmi there is a planned integration on Google Play Services but it's not available yet.

**Comment by ojw28** [comment]
Closing because the way Cronet is distributed is unrelated to ExoPlayer. I suggest you file an issue on the Chromium issue tracker [here](https://bugs.chromium.org/p/chromium) under `component:Internals>Network>Library`.
