### ISSUE TITLE
Setting Dash clock sync endpoint

### ISSUE THREAD

**Issue by aletorrado** [google/ExoPlayer#1866]
Hi, I'm looking for any way to setup the Dash UTCTiming endpoint programatically (right now FFMPEG doesn't seem to support setting it in the manifest when using ISO Dash). Is that available with ExoPlayer2?

**Comment by ojw28** [comment]
This is not supported. I would have thought that if FFMPEG doesn't support adding UtcTiming elements, it probably doesn't support generating manifests that are formatted in such a way so as to require their presence. It wouldn't really make sense to do one without the other.

It sounds like you should be filing a feature request on FFMPEG in any case, or else manipulating the output of FFMPEG to manually insert the UtcTiming element yourself.
