### ISSUE TITLE
Gradle exoplayer 2

### ISSUE THREAD

**Issue by grosalex** [google/ExoPlayer#1871]
Sorry migth be a dummy question but what the compile line to add to gradle to update to 2.0.0, I've tried :

`compile 'com.google.android.exoplayer:exoplayer:r2.0.0'`

`compile 'com.google.android.exoplayer2:exoplayer:r2.0.0'`

but none makes gradle happy,

Regards,

**Comment by ojw28** [comment]
The first of those is correct, and works fine for me. Note that you need

```
repositories {
  jcenter()
}
```

somewhere in your gradle file(s) too.

**Comment by ojw28** [comment]
NB - Updated response above to say jcenter rather than mavenCentral.
