### ISSUE TITLE
Make it easier to customize player controls

### ISSUE THREAD

**Issue by artharyoung** [google/ExoPlayer#1873]
In the 1.x version, I just need to replace the MediaController in PlayerActivity then i can customize MediaController myself.But, in the 2.x version, the mediaController is integrated in the [SimpleExoPlayerView](https://github.com/google/ExoPlayer/blob/release-v2/library/src/main/java/com/google/android/exoplayer2/ui/SimpleExoPlayerView.java), so when I use ExoPlayer, I need to implement a same SimpleExoPlayerView replace with my own MediaController. Or is there any other idea?

I thought the SimpleExoPlayerView only need to provide control interface to user,no need to bind a MediaController.

**Comment by ojw28** [comment]
I don't think I agree that it's more difficult. SimpleExoPlayerView didn't exist in 1.x, and so you effectively had to implement something equivalent in application code (in the demo app, this was done in PlayerActivity and in the corresponding layout file).

So even once you take v2, pretend SimpleExoPlayerView doesn't exist and re-implement it all yourself in your activity, you're still only at equal difficulty to v1. And once you've done that, it's just as easy as it was in v1 to replace the controller.

So I don't think the assertion that it's more difficult is valid. There is of course value in making it demonstrably easier, however, so using this issue to track that.

**Comment by artharyoung** [comment]
@ojw28 Thank you for your reply. I have recognized the name of “SimpleExoPlayerView(Simple......)” may not use in the project directly. I will try customize it by myself.

**Comment by ojw28** [comment]
We've made it somewhat easier to customize the UI components in `dev-v2`. We'll post a blog post on our [blog](https://medium.com/google-exoplayer) when we push a release that includes them. As per above, you still have the option of implementing your own UI components as well.
