### ISSUE TITLE
r2.0.0 isPlaying()

### ISSUE THREAD

**Issue by orcunkobal** [google/ExoPlayer#1878]
Hello,

isPlaying() method removed on the new version ?

**Comment by ojw28** [comment]
You shouldn't be calling methods on UI components to query the state of the player (in V1 or V2). If you want to query the state of the player, query it directly.

A one minute investigation as to what that method did in V1 (by looking [here](https://github.com/google/ExoPlayer/blob/release-v1/library/src/main/java/com/google/android/exoplayer/util/PlayerControl.java#L84)) would tell you that it's equivalent to calling `getPlayWhenReady` directly on the player.

**Comment by orcunkobal** [comment]
thank you  @ojw28

**Comment by zishanj** [comment]
Isn't this `getPlayWhenReady` indicate the `autoplay` feature? `isPlaying` is expected to return `true` if the player is currently playing otherwise it will return false.
