### ISSUE TITLE
Exoplayer 2 video aspect ratio question

### ISSUE THREAD

**Issue by dreich** [google/ExoPlayer#1880]
Hello. Trying to remake my PlayerActvity for the 2nd version of ExoPlayer.
I've run into some problem about aspect ratio.

In previous version I used:

```
//    @Override
//    public void onVideoSizeChanged(int width, int height, int unappliedRotationDegrees, float pixelWidthAspectRatio) {
//        shutterView.setVisibility(View.GONE);
//        videoFrame.setAspectRatio(
//                height == 0 ? 1 : (width * pixelWidthAspectRatio) / height);
//    }
```

from Demo app.

In 2nd version demo app there is no such method. And in result video 3:4 is stretched horizontally to 16:10 phone width.

I also should say that I don't use SimpleExoPlayerView in layout because I need my own controls, exactly, one play/pause button.

In layout I have:

```
<com.google.android.exoplayer2.ui.AspectRatioFrameLayout android:id="@+id/player_view"
      android:focusable="true"
      android:layout_gravity="center"
      android:layout_width="match_parent"
      android:layout_height="match_parent">

        <SurfaceView android:id="@+id/surface_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_gravity="center"/>

        <View android:id="@+id/shutter"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="@android:color/black"/>

  </com.google.android.exoplayer2.ui.AspectRatioFrameLayout>
```

(By the way I don't know whether there is need to have a shutter, don't know what it is.)

Please, help me to keep aspect ratio corresponding to video aspect.

Maybe I should implement VideoRendererEventListener and it's method onVideoSizeChanged?
I read here that AspectRatioFrameLayout should keep ratio itself.

Thank you.

**Comment by eneim** [comment]
Why don't you **_learn**_ how they implement the SimpleExoPlayerView and write your own?

**Comment by ojw28** [comment]
Yeah. If you're going to implement your own solution, it seems reasonable that you should be able to start with `SimpleExoPlayerView` and modify it to your needs (or understand how it works and do the same thing).

The shutter is a black view that's made visible over the surface prior to anything having been drawn into it. It can help avoid rendering artifacts prior to the first frame being drawn.
