### ISSUE TITLE
Use both versions -> Request to change artifact Id to 'exoplayer2'

### ISSUE THREAD

**Issue by eneim** [google/ExoPlayer#1883]
- Description of the issue: I would like to use both version of ExoPlayer (1 and 2) in my library. But somehow ExoPlayer 1 is not fully included in the output. I suspect that current dependencies share the same groupId and artifactId --> the later one is prioritised over the older one.

So I would like to request:
1. Any idea on how could I use both version in one project.
2. If my investigation is wrong, please help.
3. If my investigation is true, please consider to change current artifactId to 'exoplayer2' (So the new gradle entry gonna be: `com.google.android.exoplayer:exoplayer2:r2.0.1`)

Thanks.

**Comment by ojw28** [comment]
Please see https://github.com/google/ExoPlayer/issues/1842. We don't have any plans to change the artifact id for v2.

**Comment by eneim** [comment]
Thanks. My bad to not look around. I'm reading exactly the SO you mentioned, and trying the solution of using jar.
