### ISSUE TITLE
DRM vendor-defined error -2990

### ISSUE THREAD

**Issue by ChernyshovYuriy** [google/ExoPlayer#1884]
Dear colleagues,
Before post this question I looked on other related issues and didn't find anything related to code "-2990". I decided to post separate question in order to distinguish issues by error code.
So here is a question.
Our error report system reports the error from application that is in market:

```
android.media.MediaDrm$MediaDrmStateException: Failed to get provision request: DRM vendor-defined error: -2990(com.quickplay.vstb.plugin.player:9290)
```

Content is Widevine DASH.
ExoPlayer version is 1.5.10
OS version is 6.0
Device model is "Lenovo A7010a48"

Would be very helpful to get more information related to provided error code.

**Comment by wvpaf** [comment]
@ChernyshovYuriy  it would be helpful to get an ADB bugreport from the device so we can tell why the provisioning request failed.

**Comment by ChernyshovYuriy** [comment]
Unfortunately, there is no more additional info available.
This statistic collected from error report system that is monitoring application in market.
If it is possible provide general description of the potential root causes it would be good, if not - then we probably can close this question unless some one else provide something detailed.

**Comment by ChernyshovYuriy** [comment]
Some good news. I have debug logs from the device experiencing error 2990. 
To whom can I email them? I don't want to post these logs here.
Thanks.

**Comment by wvpaf** [comment]
Are you a CWIP partner? if so please use the CWIP portal to submit logs. Else we will need to get you a good email address.

**Comment by ChernyshovYuriy** [comment]
Hi,
Yes, we are CWIP partner. Will submit logs there, thanks.

**Comment by wvpaf** [comment]
@ChernyshovYuriy I understand that CWIP team got you answers. Please reopen if that is not the case.

**Comment by rahulkalamkar** [comment]
I am getting the same error.
If this ticket is closed.

Please help out.
