### ISSUE TITLE
DRM vendor-defined error -2837

### ISSUE THREAD

**Issue by ChernyshovYuriy** [google/ExoPlayer#1885]
Dear colleagues,
Before post this question I looked on other related issues and didn't find anything related to code "-2837". I decided to post separate question in order to distinguish issues by error code.
So here is a question.
Our error report system reports the error from application that is in market:

```
android.media.MediaDrm$MediaDrmStateException: Failed to get key request: DRM vendor-defined error: -2837(com.quickplay.vstb.plugin.player:9290
```

Content is Widevine DASH.
ExoPlayer version is 1.5.10
OS version is 6.0.1
Device model is "ASUS_Z00ED"

Would be very helpful to get more information related to provided error code.

**Comment by ChernyshovYuriy** [comment]
Unfortunately, there is no more additional info available.
This statistic collected from error report system that is monitoring application in market.
If it is possible provide general description of the potential root causes it would be good, if not - then we probably can close this question unless some one else provide something detailed.

**Comment by wvpaf** [comment]
@ChernyshovYuriy I understand that CWIP team got you answers. Please reopen if that is not the case.
