### ISSUE TITLE
Keep buffer on SeekTo() or Playback from current position

### ISSUE THREAD

**Issue by sonikasoni** [google/ExoPlayer#1886]
I am trying to Playback few seconds from current position using 'Seekbar' touch, It cleared buffer data and start rebuffer from the current postion.
Suppose user have buffered 80% and My video's current playing position at 40%. If I play back at 30% position by 'Seekbar' touch. It start buffering and playing from 30% even if the already buffered 80% of data.

**Comment by ojw28** [comment]
It's very unclear what the question is here. Please clarify.
