### ISSUE TITLE
Adding Sonic playback rate component to v2

### ISSUE THREAD

**Issue by sergejsha** [google/ExoPlayer#1887]
I was able to change playback rate in the library v2 by sending `PlaybackParams` to the `MediaCodecAudioRenderer`. This only works with API level >= 23. To make it working with lower Android version I would like to use Sonic library. 

This is rather a design question. If you would need to add a component which inputs a PCM stream and outputs a PCM stream with an adjusted playback rate, where would you put this component in overall Player design? Thanks!

**Comment by ojw28** [comment]
This is discussed in some detail in #26. @andrewlewis is planning to take a look at playback rate changes on earlier API levels, so I'm assigning that issue to him.
