### ISSUE TITLE
SingleSampleMediaPeriod.SourceLoadable class missing sampleData initialization

### ISSUE THREAD

**Issue by ChernyshovYuriy** [google/ExoPlayer#1888]
There is `sampleData` member filed in the SingleSampleMediaPeriod.SourceLoadable.java.
This field is uninitialized and once side loaded track trying to be loaded there is NullPointerException at line 272.

Quick solution from my side is initialize value on the line 244:

```
private byte[] sampleData = new byte[INITIAL_SAMPLE_SIZE];
```

**Comment by ojw28** [comment]
This is already fixed in 'dev-v2'.

**Comment by ChernyshovYuriy** [comment]
Just verified proposed solution. Working as designed and as desired :-)
Thanks guys!
