### ISSUE TITLE
OkHttp extension on Maven?

### ISSUE THREAD

**Issue by aletorrado** [google/ExoPlayer#1889]
Is this extension available on Maven? I couldn't find any clear instructions on how to integrate it.

**Comment by ojw28** [comment]
I've created https://bintray.com/google/exoplayer/extension-okhttp. Bintray need to approve its addition to jCenter, I think. Hopefully this should happen pretty soon.

**Comment by ojw28** [comment]
This is a dupe of https://github.com/google/ExoPlayer/issues/1157, so closing this.
