### ISSUE TITLE
Clamp target GC heap - OutOfMemoryError

### ISSUE THREAD

**Issue by ghost** [google/ExoPlayer#1891]
I encountered OutOfMemoryError while doing the following:
1) Load video (In my case, HLS stream with subtitle source .srt from external URL)
2) Seek to some position
3) Press home button to go to home
4) Return to app
5) Let video play for a few minutes more...
6) Crash!

[Log.txt](https://github.com/google/ExoPlayer/files/508527/Log.txt)
Please see attached log

**Comment by ojw28** [comment]
There's nowhere near enough information here for us to debug your issue. You're not even indicating which app you're talking about, and haven't provided a full bug report as is explicitly requested in the issue template. Please provide complete information, or we'll have to close this. Thanks!
