### ISSUE TITLE
Calculating size of SurfaceView

### ISSUE THREAD

**Issue by AntonAndev** [google/ExoPlayer#1892]
Hello all, I am trying to add ExoPlayer 2.0.1 instead of MediaPlayer. With MediaPlayer in the onPrepared() method I use getVideoWidth() and getVideoHeight() to get width and height of video to calculate size of SurfaceView with correct aspect ratio. With ExoPlayer 2.0.1 library I am creating intance of SimpleExoPlayer:

```
            Handler mainHandler = new Handler();
            BandwidthMeter bandwidthMeter = new DefaultBandwidthMeter();
            TrackSelection.Factory videoTrackSelectionFactory =
                    new AdaptiveVideoTrackSelection.Factory(bandwidthMeter);
            TrackSelector trackSelector =
                    new DefaultTrackSelector(mainHandler, videoTrackSelectionFactory);
            LoadControl loadControl = new DefaultLoadControl();
            exoPlayer = ExoPlayerFactory.newSimpleInstance(context, trackSelector, loadControl);
            //simpleExoPlayerView.setPlayer(exoPlayer);
            exoPlayer.setVideoSurfaceHolder(videoHolder);
            exoPlayer.addListener(this);
```

I suppose I need to use this event to get width and height, but this event is not fired, why and what should I use? onPlayerStateChanged event is working.

```
    @Override
    public void onVideoSizeChanged(int width, int height, int unappliedRotationDegrees,
                                   float pixelWidthAspectRatio) {
        appendLog("onVideoSizeChanged: " +  String.valueOf(width) + ", " + String.valueOf(height) + ", " + String.valueOf(pixelWidthAspectRatio));
    }
```

Tried it on Android 6 on Sony Z3 Compact, LG Spirit.

**Comment by ojw28** [comment]
Where in your code are you registering the listener? There should be a call to `SimpleExoPlayer.setVideoListener` somewhere?

**Comment by AntonAndev** [comment]
oh yes, added it, now works, I was thinking addListener does it, thank you.
