### ISSUE TITLE
Problem with buffering using SimpleExoPlayer

### ISSUE THREAD

**Issue by AntonAndev** [google/ExoPlayer#1893]
Hello, I am adding ExoPlayer 2.0.1 instead of MediaPlayer, I am creating an instance of SimpleExoPlayer 

```
            Handler mainHandler = new Handler();
            BandwidthMeter bandwidthMeter = new DefaultBandwidthMeter();
            TrackSelection.Factory videoTrackSelectionFactory =
                    new AdaptiveVideoTrackSelection.Factory(bandwidthMeter);
            TrackSelector trackSelector =
                    new DefaultTrackSelector(mainHandler, videoTrackSelectionFactory);
            LoadControl loadControl = new DefaultLoadControl();
            exoPlayer = ExoPlayerFactory.newSimpleInstance(context, trackSelector, loadControl);
            //simpleExoPlayerView.setPlayer(exoPlayer);
            exoPlayer.setVideoSurfaceHolder(videoHolder);
            exoPlayer.addListener(this);
```

and use it to play a HLS stream

```
        DefaultBandwidthMeter bandwidthMeter = new DefaultBandwidthMeter();
        DataSource.Factory dataSourceFactory = new DefaultDataSourceFactory(this, Util.getUserAgent(this, userAgent), bandwidthMeter);
        MediaSource videoSource = new HlsMediaSource(url, dataSourceFactory, null, null);
        exoPlayer.prepare(videoSource);
        exoPlayer.setPlayWhenReady(true);
```

Problem with buffering is detected on streams from a server with ping ~110ms, if stream has SD format and 2mbits bitrate, SimpleExoPlayer plays it with interruptions, if stream has HD format and 6mbits bitrate, SimpleExoPlayer tries to buffer stream and goes to Idle state. If try to play streams from a server which is closer to me (ping 35 ms), problem is not occured. Tried it on Android 6. Is it possible to change buffer settings for SimpleExoPlayer instance? Update: 4G LTE Internet.

**Comment by ojw28** [comment]
Without links to sample content we're not able to assist debugging this issue. I think the default buffer settings should be fine for 2mbit/s and 6mbit/s.

**Comment by AntonAndev** [comment]
Hello, can I send links to your email (I can't share it here)? I published a new version of my app with SimpleExoPlayer, users complain, they have problems with watching tv channels using mobile internet too.

**Comment by ojw28** [comment]
You can send links to `dev.exoplayer@gmail.com` as in the issue template, thanks!

**Comment by ojw28** [comment]
Links provided do not appear functional. Closing due to lack of information. As per my earlier reply, the default buffer settings should be fine for 6mbit/s streams.
