### ISSUE TITLE
SimpleExoPlayerView.getPlayer?

### ISSUE THREAD

**Issue by minas90** [google/ExoPlayer#1895]
Hi there,
Is it possible to get player from SimpleExoPlayerView?
In some scenarios I don't have reference to the player, but I need to play / stop the video.
It was possible with VideoView and some similar implementation based on ExoPlayer.
I'm trying to switch to SimpleExoPlayerView and it is the only showstopper.

**Comment by ojw28** [comment]
Not currently, but it's trivial to add a `getPlayer` method. We will do this.

**Comment by minas90** [comment]
ok thanks 👍
