### ISSUE TITLE
Class Reference page for version 1.x

### ISSUE THREAD

**Issue by kyo504** [google/ExoPlayer#1896]
Hi, I'm developing streaming player with exoplayer but recently I could only see the class reference page for v 2.x. Where can I find the old one(v1.x)?

**Comment by b95505017** [comment]
https://github.com/google/ExoPlayer/releases/tag/r1.5.11_docs

**Comment by ojw28** [comment]
It got replaced with the 2.x reference, but I've restored the 1.x reference to http://google.github.io/ExoPlayer/doc/reference-v1/ and will also add a link at the top of the deprecated developer guide (https://google.github.io/ExoPlayer/guide-v1.html).

**Comment by kyo504** [comment]
@ojw28 Thanks for the link :)
