### ISSUE TITLE
Custom MediaExtractor based on ExoPlayer's Extractor

### ISSUE THREAD

**Issue by vxhviet** [google/ExoPlayer#1901]
[Question]
Dear ExoPlayer developers,

I'm not sure if this is the appropriate place to ask this question but I would love to receive some input from you guys. In our app, the seeking is the most crucial feature so I've been working directly with `MediaCodec` based on example from [grafika's MoviePlayer](https://github.com/google/grafika/blob/master/src/com/android/grafika/MoviePlayer.java). This works fine with normal Android video but it has trouble reading iOS's `mov` or even `mp4` video. Correct me if I'm wrong but I think the key problem here is the default `MediaExtractor` cannot read iOS's files. If I can somehow make the extractor work, then I can just pass the raw data into `MediaCodec` for decoding as usual.  

This [blog post](http://morphinity.github.io/blog/2015/12/03/decoding-frame-bitmap.html) is like the only material regarding this matter that I can find, but unfortunately the section about customized `MediaExtractor` is very brief. I would be very appreciated if you guys can provide some general guidance as I can see `ExoPlayer` has no problem reading iOS's files at all.

Thank you so much for your time.

**Comment by ojw28** [comment]
ExoPlayer doesn't use `MediaExtractor`. We instead implement our own set of extractors directly in the library (they're all in [this package](https://github.com/google/ExoPlayer/tree/release-v2/library/src/main/java/com/google/android/exoplayer2/extractor)). We did this for quite a few reasons, one of which was to allow us to more easily fix extractor bugs and support a wider range of file types.

It would be possible for you to replace your use of `MediaExtractor` with pieces of `ExoPlayer`, although there's no simple way just to swap them around. `ExtractorMediaSource` is probably the closest to what you want.

It's somewhat unclear why you're working directly with `MediaCodec`. Using ExoPlayer's extractors and feeding the data into `MediaCodec` sounds exactly like what full `ExoPlayer` just does for you...!

**Comment by vxhviet** [comment]
Dear ojw28, 

Thank you for your reply. I used to use `ExoPlayer` before (#1399) but because the seeking performance didn't meet our demand, we switched to FFmpeg and then `MediaCodec` instead. The main feature of our app is letting the user scrub through every frame and then extract the one they like. So there is no actual playback on the video and thus any issue with syncing and timing is not really relevant. The key factor is the seeking speed and the accuracy of the frame extraction.

I've managed to do that by manually feeding the data into `MediaCodec` and then process whatever output buffers it gives back. The performance for forward seeking is very good, backward seeking is a little bit slow but still acceptable. 

Another option is, as you said, employing `ExoPlayer` (version 2.0 has quite some change so it would need to take a while) and then somehow manually control the `MediaCodec` bit to utilize my piece of working code for the seeking and extracting feature. 

I've done a quick test with ExoPlayer v2, if I keep feeding the `seekTo()` with a small jump of 15 milliseconds (for example `seekPosition += 15000`), `ExoPlayer` can give accurate position but it works really slow. I'm sure there's still some optimization to be done because with my implementation, forward seeking can be as fast as playback.  In fact, it could be too fast that I would need to deliberately slow it down.

After a quick skimming, the `mediacodec/` package seem like the most relevant one. I'm still not sure which one is easier though, customizing `ExtractorMediaSource` or modifying ExoPlayer's `mediacodec` bit.

**Comment by ojw28** [comment]
Yeah, ExoPlayer is likely not optimized for this use case. It remains an option for you to use just the extractors provided by the ExoPlayer library, but exactly how to do this is dependent on your other application code, and is something you'll have to figure out for yourself.

**Comment by uplusplus** [comment]
How to use ffmpeg as an extractor ?
