### ISSUE TITLE
NumberFormatException in DashManifestParser

### ISSUE THREAD

**Issue by AntonAndev** [google/ExoPlayer#1903]
Hello, I am using SimpleExoPlayer (2.0.1) instance:

```
public void PlayStream(String URL, String type) {
        Uri url = Uri.parse(URL);
        MediaSource videoSource = null;
        // Measures bandwidth during playback. Can be null if not required.
        DefaultBandwidthMeter bandwidthMeter = new DefaultBandwidthMeter();
        // Produces DataSource instances through which media data is loaded.
        DataSource.Factory dataSourceFactory = new DefaultDataSourceFactory(this, Util.getUserAgent(this, userAgent), bandwidthMeter);
        // This is the MediaSource representing the media to be played.
        if (type.equals("m3u8")) {
            videoSource = new HlsMediaSource(url, dataSourceFactory, null, null);
        }
        else if (type.equals("dash")){
            videoSource = new DashMediaSource(url, dataSourceFactory, new DefaultDashChunkSource.Factory(dataSourceFactory), null, null);
        }
        // Prepare the player with the source.
        if (videoSource != null) {
            exoPlayer.prepare(videoSource);
            exoPlayer.setPlayWhenReady(true);
        }
    }
```

Tried to pass dash stream powered by flussonic 4.6.3 media server, following exception occured (I will send link example to your email):

> 10-06 12:26:48.910 32358-629/com.andevapps.ontv E/LoadTask: Unexpected exception loading stream
>                                                             java.lang.NumberFormatException: Invalid int: "v1"
>                                                                 at java.lang.Integer.invalidInt(Integer.java:138)
>                                                                 at java.lang.Integer.parse(Integer.java:410)
>                                                                 at java.lang.Integer.parseInt(Integer.java:367)
>                                                                 at java.lang.Integer.parseInt(Integer.java:334)
>                                                                 at com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parseInt(DashManifestParser.java:773)
>                                                                 at com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parseAdaptationSet(DashManifestParser.java:227)
>                                                                 at com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parsePeriod(DashManifestParser.java:206)
>                                                                 at com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parseMediaPresentationDescription(DashManifestParser.java:134)
>                                                                 at com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parse(DashManifestParser.java:96)
>                                                                 at com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parse(DashManifestParser.java:55)
>                                                                 at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:114)
>                                                                 at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
>                                                                 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
>                                                                 at java.util.concurrent.FutureTask.run(FutureTask.java:237)
>                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
>                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
>                                                                 at java.lang.Thread.run(Thread.java:818)
> 10-06 12:26:48.912 32358-626/com.andevapps.ontv E/ExoPlayerImplInternal: Source error.
>                                                                          com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected NumberFormatException: Invalid int: "v1"
>                                                                              at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:317)
>                                                                              at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
>                                                                              at java.util.concurrent.FutureTask.run(FutureTask.java:237)
>                                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
>                                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
>                                                                              at java.lang.Thread.run(Thread.java:818)
>                                                                           Caused by: java.lang.NumberFormatException: Invalid int: "v1"
>                                                                              at java.lang.Integer.invalidInt(Integer.java:138)
>                                                                              at java.lang.Integer.parse(Integer.java:410)
>                                                                              at java.lang.Integer.parseInt(Integer.java:367)
>                                                                              at java.lang.Integer.parseInt(Integer.java:334)
>                                                                              at com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parseInt(DashManifestParser.java:773)
>                                                                              at com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parseAdaptationSet(DashManifestParser.java:227)
>                                                                              at com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parsePeriod(DashManifestParser.java:206)
>                                                                              at com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parseMediaPresentationDescription(DashManifestParser.java:134)
>                                                                              at com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parse(DashManifestParser.java:96)
>                                                                              at com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parse(DashManifestParser.java:55)
>                                                                              at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:114)
>                                                                              at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
>                                                                              at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423) 
>                                                                              at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
>                                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
>                                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
>                                                                              at java.lang.Thread.run(Thread.java:818)

**Comment by ojw28** [comment]
If you could spend some time debugging this kind of issue prior to filing, it would sure help reduce our workload and allow us to focus on getting actual work done ;).

In this case, the stack trace indicates the failure happens [here](https://github.com/google/ExoPlayer/blob/f8a8302f7bbcb47997095bd97b086eb633e49972/library/src/main/java/com/google/android/exoplayer2/source/dash/manifest/DashManifestParser.java#L227) because we're trying to parse the AdaptationSet id attribute as an integer, but in the manifest it has value "v1". The DASH specification (ISO 23009-1) defines id like this:

```
<xs:attribute name="id" type="xs:unsignedInt"/>
```

So the manifest is broken rather than the player (the AdaptationSet id element should be an integer).
