### ISSUE TITLE
Maximum decodable video size on Android

### ISSUE THREAD

**Issue by okjoonkim** [google/ExoPlayer#1906]
Dear ExoPlayer Developers,

I would like to get an advice or recommendation about how to check if a decoder on Android can decode a specific frame size, like 2400x1600. Since some old devices raises an exception showing the renderer initialization failure while decoding, i want to check the decoder capability beforehand. 
Actually here are some functions i have tried so far.
- VideoCapabilities.isSizeSupported();
- VideoCapabilities.areSizeAndRateSupported()
- MediaCodecUtil.maxH264DecodableFrameSize();

However, those functions above are not reliable. For example, even though Nexus 5 or 6 phones are able to decode our specific frames, the listed functions always say that the given frame size is not supported. 

It will be very helpful if anyone give me any suggestions.

Thanks in advance

**Comment by Ood-Tsen** [comment]
Hi @okjoonkim 

You may get codec capability from android folder '/system/etc/media_codecs.xml'
(e.g. [media_codecs_8974.xml](https://github.com/ubports/android_device_fairphone_fp2/blob/master/media/media_codecs_8974.xml)' )

**Comment by AquilesCanta** [comment]
Checkout how we do it in V2 `MediaCodecInfo.isCodecSupported(String codec)`. We currently implement the checks for h264 and h265, I think, but the idea is the same for all of them. If you have any further questions, please try a general android Q&A.

**Comment by okjoonkim** [comment]
Thanks @Ood-Tsen and @AquilesCanta.
I believe that the information in the '/system/etc/media_codes.xml' is same to the data returned by VideoCapabilities instance. 
Currently  we are still using the ExoPlayer V1.5.10. 
I also believe that the MediaCodecUtil.maxH264DecodableFrameSize() function decides the maximum decodable frame size according to the codec profile level. 
Would you let me know if i misunderstood.
Thanks again.

**Comment by AquilesCanta** [comment]
Yes, 

> MediaCodecUtil.maxH264DecodableFrameSize() decides the maximum decodable frame size according to the codec profile level. 

is true, but this is only so for older APIs in v2. Can you give v2 a try? It does the correct checks for h264 and h265, but is conservative about other decoders, and returns true if not. Also, what format are you trying to play?

**Comment by okjoonkim** [comment]
@AquilesCanta We are decoding and playing H246-based HLS stream. Frankly speaking, it is hard to upgrade up to ExoPlayer V2 for now. Is it possible to make use of only some classes or functions from V2?
Thanks for your help.

**Comment by AquilesCanta** [comment]
>  Is it possible to make use of only some classes or functions from V2?

I wouldn't advise that, really. You can try, however, backporting some of the stuff from V2 and patching whatever you need.

> We are decoding and playing H246-based HLS stream

I assume you meant H264. It is strange as the calculation should be correct. Try attaching a debugger and see what's going on, another approach I'd recommend is playing the problematic streams in v2 and see if the behavior is any different. This doesn't require any effort from your part, but if we manage to reproduce it we might be able to help you.

**Comment by okjoonkim** [comment]
Sorry for confusion. What i am trying to figure out is that a device can decode a high resolution of stream (i.e. 2400x1600 H264) before playing it. If the device does not have the capability, we want to provide a low resolution. According to my tests, when the HLS m3u8 file contains high resolution stream and the player switches to a higher resolution from a low resolution while having a good internet bandwidth, the exoplayer library returns an exception. 
Is it doable to check the video capability before playing?
Thanks

**Comment by ojw28** [comment]
If the HLS master playlist includes RESOLUTION tags then I think streams beyond the device's capabilities are filtered out already (in V1 and V2).

**Comment by okjoonkim** [comment]
That is the issue i am facing right now. Surely i put the RESOLUTION tags in the m3u8 file but the player keeps trying to play the higher resolution. There is another thing i would like to point out. I also provide the stereoscopic VR stream having high resolution. Unless the device has the video capability to decode it, i want to disallow the VR experience beforehand. 
Thanks again.

**Comment by ojw28** [comment]
Please provide sample content for us to investigate this further and a full bug report captured shortly after the issue occurs.

**Comment by ojw28** [comment]
Closing as no sample content or bug report was provided.
