### ISSUE TITLE
Release failed when press power button (HLS)

### ISSUE THREAD

**Issue by HSY229** [google/ExoPlayer#1907]
Launch ExoPlayer V2.0.2 with HTC M8x Android 6.0,
press "HLS" button,
press "Apple 4x3 basic stream" button,
when player display,
press the power button of device,

then, I got:
1. `ExoPlayerImplInternal`: Period release failed.
2. `java.lang.NullPointerException`: Attempt to get length of null array 
3. com.google.android.exoplayer2.`source.hls.HlsMediaPeriod.release`(HlsMediaPeriod.java:106)

This is looks like #1693 & #1882.

[HTC_M8x_Android_6.txt](https://github.com/google/ExoPlayer/files/515703/HTC_M8x_Android_6.txt)

**Comment by ojw28** [comment]
Is this using the ExoPlayer demo app, or something you're written yourself?

**Comment by HSY229** [comment]
Yes, I use demo project.

**Comment by HSY229** [comment]
Thanks.
