### ISSUE TITLE
PlaybackControlView leaks itself and anything it refers to (including the player instance)

### ISSUE THREAD

**Issue by ojw28** [google/ExoPlayer#1908]
This is demonstrated by the app here:
https://github.com/PerkmannM/Demo-ExoPlayer

**Comment by ojw28** [comment]
Notes:
- The leak is much less severe if you upgrade to ExoPlayer r2.0.2 (it's still there though).
- Until we fix this, you can easily work around the problem, or at least mitigate it, by explicitly clearing the player from the view when it's no longer required, like: `mPlaybackControlView.setPlayer(null);` (for example on `onStop`).

**Comment by PerkmannM** [comment]
Thank you for fixing this issue!

When do you plan to release this version?

**Comment by philipgiuliani** [comment]
Would be awesome to see a new release soon! :)
