### ISSUE TITLE
[Question] Reuse BOTH SimpleExoPlayerView and SimpleExoPlayer after STATE_ENDED

### ISSUE THREAD

**Issue by eneim** [google/ExoPlayer#1918]
Assuming that I have played a local Video, using those 2 components. After the player reaches STATE_ENDED, it seems that it is not trivial to restart the playback again. What should I do if I want to "click to one button" to restart the playback from all over again.

Thanks and pardon me if I'm missing some thing.

**Comment by ojw28** [comment]
I think it is trivial; just seek back to 0 (by calling seekTo(0)) and that's it? Note that the ExoPlayer demo app allows you to seek back after the state has transitioned to ended (with the player controls).

**Comment by eneim** [comment]
@ojw28 I think I got the solution. Thanks a lot.
