### ISSUE TITLE
Controller in SimpleExoPlayerView is visible when I use app:use_controller="false"

### ISSUE THREAD

**Issue by tprochazka** [google/ExoPlayer#1919]
When I use `com.google.android.exoplayer2.ui.SimpleExoPlayerView` with `app:use_controller="false"`
Controller stay visible all the time.
Tested o r2.0.2

Only workaround is use `setUseController(false)` but XML layout attribute must be removed too, otherwise `setUseController(false)` will have no impact and controll will be visible also after call `setUseController(false)`  because of this method has this on the beginning

```
    if (this.useController == useController) {
      return;
    }
```

**Comment by ojw28** [comment]
We'll push a fix for this shortly; thanks!
