### ISSUE TITLE
Requesting demo app APKs

### ISSUE THREAD

**Issue by sandersaares** [google/ExoPlayer#1920]
A significant component in multiplatform solution planning is trying out media player functionality and compatibility with content, ideally using an official sample app.

ExoPlayer has a perfectly usable demo app for this. However, it currently requires an Android developer to build it, which is somewhat effortful. Trying playback against the latest version without Android developer involvement would simplify workflows.

It would be desirable to be able to obtain official APKs of the demo app, ideally both for releases and nightly/latest builds. This would simplify testing of ExoPlayer and video compatibility.

**Comment by ojw28** [comment]
For non-technical reasons this is currently non-trivial for us to do, unfortunately. If someone else were to set this up then I think it would be possible to add links from relevant parts of our documentation (e.g. [this page](https://google.github.io/ExoPlayer/demo-application.html)), although I'd need to double check this.

**Comment by ojw28** [comment]
For non-technical reasons, this is not something we plan on doing. Sorry!
