### ISSUE TITLE
Video stutters - how to pinpoint the root cause?

### ISSUE THREAD

**Issue by RikDriever** [google/ExoPlayer#1922]
We're using ExoPlayer in our app running on one specific device and recently received a new version of this device from the manufacturer for testing. 
The old device has a RK3188 and Android 4.2.2, the new one has a RK3368 and runs on 5.1.1. 
On this new device we're experiencing subtle stuttering in the video, especially when panning and zooming occurs in the video. 
I've tested with all kinds of videos. With the ExoPlayer demo app (v1.x and v2.x) and also my own vids rendered with FFMPEG (MP4 with different combinations of H264, H265, audio codecs, framerates, bitrates) but the result is the same stuttering. 
Playing the video with other videoplayers on the device like VLC or simply android.media.MediaPlayer, the stuttering doesn't occur. 

I realise it's probably hard to pinpoint the cause based on the above, but I'd appreciate some tips how to proceed from here.

**Comment by ojw28** [comment]
You should really follow up with the device manufacturer if this is a device specific performance problem, and if you have a relationship with them.
