### ISSUE TITLE
Ability to add drm key requests after player has been created

### ISSUE THREAD

**Issue by SteUK** [google/ExoPlayer#1924]
Hi,

This is a feature request...sorry if I have missed an option somewhere or posting this in the wrong place!

Using ExoPlayer branch dev-2.0.0-rc

I using Axinom as a DRM solution service.  This requires setting a drm key request - I am sure most of you know the procedure as it has been covered on here before.

What I would like to do is create my player up front, then later specify license tokens (created on demand).  Currently have altered HttpMediaDrmCallback, adding two functions:

public void RemoveKeyRequestProperty( String key )
public void AddKeyRequestProperty( String key, String value )

...and removing the final from the variable keyRequestProperties.

Not sure if this is the best approach, but it seems to work for me.

Thanks!
Ste

**Comment by ojw28** [comment]
You'd still need to ensure you call your additional methods before any call to `ExoPlayer.prepare`, else you'd have no guarantee that the properties are set prior to requests being triggered. Are you doing this?

**Comment by SteUK** [comment]
I sure am  :)  Playback is working as would be expected in our model.

Just wondered if the ability to do this is something that would be considered as an addition.  Otherwise the player would need creating once a license token has been obtained (webservice), and a new player would be needed to be instantiated for every different video.
