### ISSUE TITLE
[Question] HLS aes128-bit encrypted example

### ISSUE THREAD

**Issue by rainboy93** [google/ExoPlayer#1931]
Hi,
After long time searching without any result. I decided to ask you for an example of playing live stream video with HLS aes128-bit encrypted.
Thanks in advance.

**Comment by ojw28** [comment]
AES-128 encrypted HLS streams should work in an identical way to clear HLS streams. As an application developer, you shouldn't need to do anything differently. So please just refer to playback of clear HLS streams in the demo app.

**Comment by rainboy93** [comment]
Thanks for reply.
At the moment, i'm using amazon for encrypt provider. 
Also, I use the existed `Aes128DataSource` file and create my own `HlsRendererBuilder` file.
`onSingleManifest` callback i insert the AES128DataSource  with constructor relate to DefaultUriDataSource

`byte[] encryptionKey = getKey("AQEDAHh27I7ep8UA8h4ZkT7gjFnS50KkxJDdrviotvprqVDP9AAAAG4wbAYJKoZIhvcNAQcGoF8wXQIBADBYBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDA96RCavMQRqiSr8iwIBEIArzmvU03UeW0ZBVh2Vgiby/S8h7hW2AKklfrNpvlOW6hMSMdR5dGpNe3wC+w==");`
`byte[] encryptionIv = Base64.decode("sydcozjckA+4OYQl9wBXkg==", Base64.DEFAULT);`
`Aes128DataSource aes128DataSource = new Aes128DataSource(dataSource, encryptionKey, encryptionIv);`
`final HlsChunkSource chunkSource;`
`chunkSource = new HlsChunkSource(true /* isMaster */, aes128DataSource , manifest,
                        DefaultHlsTrackSelector.newDefaultInstance(context), bandwidthMeter,
                        timestampAdjusterProvider);`

But when i run it always return `Error while finalizing cipher` Exception.
How can i turn out of this problem.
By the way i get the key decrypted like the answer in this link [https://forums.aws.amazon.com/thread.jspa?messageID=606859](url)

**Comment by rainboy93** [comment]
By the way, this is the link stream that i use to test:
[http://dgk6hzyysiw9f.cloudfront.net/hlsprotected/002testpl.m3u8](http://dgk6hzyysiw9f.cloudfront.net/hlsprotected/002testpl.m3u8)
and the key information:

Encryption Key
`AQEDAHh27I7ep8UA8h4ZkT7gjFnS50KkxJDdrviotvprqVDP9AAAAG4wbAYJKoZIhvcNAQcGoF8wXQIBADBYBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDA96RCavMQRqiSr8iwIBEIArzmvU03UeW0ZBVh2Vgiby/S8h7hW2AKklfrNpvlOW6hMSMdR5dGpNe3wC+w==`

Encryption Key MD5
`thCW4vOEyIGjfAM3rbrwnw==`

Encryption Initialization Vector
`sydcozjckA+4OYQl9wBXkg==`

I can't find the way to make it possible to run. Can you help me.

**Comment by AquilesCanta** [comment]
I'll have a look.

**Comment by AquilesCanta** [comment]
By chance, have you managed to play the provided stream with any other player? I strongly suspect it's malformed. We cannot help you with that, unfortunately. Please close if that's the case.

**Comment by ojw28** [comment]
The source media looks broken to me too. It doesn't play in Safari or VLC either. Just looking at the manifest, every segment appears to be referencing a different (but overlapping) part of the same file (002test.ts), which definitely doesn't look right.

If you are able to produce HLS AES-128 content that works in Safari/VLC but not in ExoPlayer, please file a new issue. For this one, it looks like the media is just broken.
