### ISSUE TITLE
Recording of Stream Video from Exoplayer

### ISSUE THREAD

**Issue by Anshumansharma12** [google/ExoPlayer#1932]
Hello All,

I want to record video from Exoplayer. 

Right now am using Exoplayer for streaming, now with the stream i need to record that video into Android phone local storage. Please help me out how i can record video from streaming buffer.

Thanks
Anshuman

**Comment by ojw28** [comment]
This is not a feature supported by ExoPlayer, sorry! It's probably possible to do, but how is something you'd need to work out for yourself.

**Comment by Anshumansharma12** [comment]
Is it possible that i can cache streaming video and play it again?

**Comment by lbranimir** [comment]
Anshumansharma12, do you resolve that problem?
