### ISSUE TITLE
HLS Video playing too fast on Android TV

### ISSUE THREAD

**Issue by Mugurell** [google/ExoPlayer#1933]
Hello,

I was trying to implement ExoPlayer for HLS playback on Android TV.
I imported the demo project based off 2.0.2 and started the PlayerActivity on a Nexus Player with Nougat with basically
`startActivity(new Intent(this, PlayerActivity.class)    
    .putExtra(PlayerActivity.PREFER_EXTENSION_DECODERS, false)
 .setData(Uri.parse("https://devimages.apple.com.edgekey.net/streaming/examples/bipbop_4x3/gear1/prog_index.m3u8"))
    .putExtra(PlayerActivity.EXTENSION_EXTRA, new String())
    .setAction(PlayerActivity.ACTION_VIEW));
`

Because that stream shows a simple counter it is obvious that the stream is played at a faster than normal speed. This can also be seen with the media controller which happens to even jump 2 seconds.

Logcat says [http://pastebin.com/qKnJQQHJ](http://pastebin.com/qKnJQQHJ)

**Comment by ojw28** [comment]
There are two timers in the video stream that drift apart. We stay in sync with the bottom one. This is the same as what Safari does. If you're expecting the playback controls to stay in sync with the top timer rather than the bottom one then I think you're expecting the wrong thing.

Please clarify.

**Comment by Mugurell** [comment]
The playing rate of the stream is too high.
It's almost double than what it should be.

Here's a short video with the demo run on Nexus Player 
https://drive.google.com/open?id=0B3f8ie7PRefdZ29SNFZDQUM4Mkk

As it can be seen (if one is to look carefully) the stream starts playing at around second 6 of the recording and until second 12 of the recording ExoPlayer already played 11 seconds. In 6 seconds.

This does not happen with the same code and the same stream on a mobile device.

**Comment by ojw28** [comment]
Ah. This is device and setup specific rather than HLS specific, I think. Please see the comment about Nexus Player on [this](https://google.github.io/ExoPlayer/supported-devices.html) page, which I think is what you're seeing.

**Comment by Mugurell** [comment]
I have no words.
That was indeed the problem.

Thanks!

You're doing an awesome job!

**Comment by ojw28** [comment]
No worries!
