### ISSUE TITLE
How to keep the buffer after calling seekTo() ?

### ISSUE THREAD

**Issue by Ma7moudHatem** [google/ExoPlayer#1934]
I have a case where i need to keep the buffer after seeking to a position behind the current playback position. Currently the default behavior for the player is clearing the buffer if i seek behind the  current playback position and keeping it if i seek to a position afterward the playback position. 
So please help me to fix this issue or any advice.

**Comment by ojw28** [comment]
This is not something we'll be supporting with the in-memory buffer. We're working on enhancing on-disk caching to help better support this case. This is tracked by https://github.com/google/ExoPlayer/issues/420.
