### ISSUE TITLE
FFmpeg Support

### ISSUE THREAD

**Issue by SrujithPoondla** [google/ExoPlayer#1936]
I am using Android-FFmpeg .aar file from [Android-FFmpeg](http://writingminds.github.io/ffmpeg-android-java/) for loading FFmpeg binaries. Is there any way to link the ffmpeg command line output from that module to exoplayer so that it streams the video with out saving the video. Otherwise should i have to develop some FFmpeg decoder to decode video as an extension to exoplayer using Media Codec Renderer?

**Comment by ojw28** [comment]
This is quite far outside the scope of the issue tracker. We're not familiar enough with the Android-FFmpeg library to provide an answer. It seems almost like this is more a question for the Android-FFmpeg developers than it is for us.
