### ISSUE TITLE
Video over toolbar and color status bar gone

### ISSUE THREAD

**Issue by zmsansan** [google/ExoPlayer#1939]
I'am use video on top window with appcompat toolbar, but video on toolbar and color status bar gone instead under toobar and color status bar.
I'am simplify and customization demo for set aspect ratio. Aspect ratio = 4/3 and set RESIZE_MODE_FIXED_WIDTH.

This bug see on Android 6.0.1.

I think cause in AspectRatioFrameLayout y-coordinate is negative..

How solve this problem?

Link to example https://drive.google.com/open?id=0B3-5giPKh3HYT1Q2SGFta01MZHM
![photo617154541392078812](https://cloud.githubusercontent.com/assets/15428737/19347316/df30a8e6-9150-11e6-8e8a-a1110240af0a.jpg)

**Comment by ojw28** [comment]
I don't know, sorry. I don't think it's an ExoPlayer bug though. You should probably report the issue to the tool bar.
