### ISSUE TITLE
No video, only sound (hls, dash)

### ISSUE THREAD

**Issue by AntonAndev** [google/ExoPlayer#1940]
Some users complain what they see black rectangle instead of a video, but can hear a sound, and this problem is not only with HLS streams from my servers,  "Audio only" HLS playlists are not enabled on server, I use SimpleExoPlayer and SimpleExoPlayerView (r,2.0.1 and r.2.0.2). These users did not have such problem with previous version of my app with MediaPlayer class. Also I added a function to switch to DASH protocol, one user tried it, in this case the same problem with black rectangle. This problem occurs on following devices: 
MK808B Plus Android 4.4,  ALCATEL ONETOUCH IDOL 3 (5.5) (idol3) Android 5.0, Vodafone Smart mini (Vodafone_875) Android 4.1, Galaxy Tab4 Active (rubenslte) Android 5.1, k200 Android 4.4, Galaxy Win (delos3geur) Android 4.1, msm8625_d9 Android 4.1, s9201b Android 4.1, Redmi Note 3 (kenzo) Android 6.0, Iconbit xds94 kx Android 5.1

**Comment by AquilesCanta** [comment]
Can you provide a stream that reproduces the issue?

**Comment by AntonAndev** [comment]
I sent links to your dev.exoplayer... email

**Comment by AquilesCanta** [comment]
Unfortunately, I cannot reproduce the issue. 

If you are completely certain that the same media, on the same device used to work with MediaPlayer, I can only guess that the codec capabilities advertising is not correct or we are not correctly doing the check. In any case, I haven't heard of these things happening before. 

If you need/want to confirm this quickly, you could try disabling the codec profile/level check and see if things change. In the meantime, I'll see if I can get one of these devices to reproduce the issue.

**Comment by AntonAndev** [comment]
I asked user with Nexus 7 to email me, he has another problem, I removed Nexus 7 from list. Sorry.

**Comment by AntonAndev** [comment]
New user reported about this problem, the same pattern - no problem with previous version of my app with MediaPlayer and no video, only sound with in the new version with ExoPlayer, device Iconbit xds94 kx Android 5.1 (added to the list)

**Comment by AquilesCanta** [comment]
I'll see if I can reproduce it myself with one of the listed devices.

**Comment by AquilesCanta** [comment]
Both links play well in Galaxy Tab 4 Active, in the Demo App, last exoplayer version. Can you confirm that you can reproduce the issue on this device in the Demo App? Considering the profile is high for the video, it wouldn't surprise me if some of the devices don't support it. But in that case, the streams shouldn't play in MediaPlayer either. Let me know if you have any more data, but I won't be able to help you if I cannot reproduce this. And I certainly cannot try every device you list, unfortunately.

**Comment by AntonAndev** [comment]
I do not have such device, one user with device Rombica Ultra HD v002 reported about an error: "couldn't create decoder for omx.amlogic.avc.decoder.awesome." from ExoPlayer, so again no video, only audio. I will collect all errors from ExoPlayer in the future release by sending it to analytics service.

**Comment by AntonAndev** [comment]
Hello, following errors occur on devices: "Couldn't create decoder for..." and values:
OMX.k3.video.decoder.mpeg2
OMX.sprd.h264.decoder
OMX.SEC.avc.dec
OMX.allwinner.video.decoder.avc
OMX.k3.video.decoder.avc
OMX.ST.VFM.H264Dec (too many users were affected)
OMX.amlogic.avc.decoder.awesome (too many users were affected)
OMX.qcom.video.decoder.avc (too many users were affected)

Is there possible solutions to solve these problems?

**Comment by ojw28** [comment]
There's not enough information provided in this issue for us to investigate. We'd likely need a full bug report captured from the device shortly after experiencing the problem. Please file a new issue if you're able to provide one. Thanks!
