### ISSUE TITLE
HLS seeking in reverse (rewind) doesn't work on a live event stream.

### ISSUE THREAD

**Issue by jglanfield** [google/ExoPlayer#1941]
This is quite simple to reproduce. Essentially, if you call seekTo(P) where P is some time before the player's current position, it just seeks to the beginning of the stream (there is only one window and it can't do anything but seek to the beginning of it). It's the equivalent of calling seekTo(0).

I've noticed that one can reproduce this simply by removing the #EXT-X-ENDLIST tag from the .m3u8 index file. Once the tag is replaced, rewinding seems to work just fine.

Some sample code:

```
public void rewindButtonPressed(View view) {
    long currPosition = exoPlayer.getCurrentPosition();
    long seekPosition = currPosition - 1000; // go back 1 second

    exoPlayer.seekTo(seekPosition);
}
```

ExoPlayer version: 2.0.2
Android: 6.0.1 (Galaxy S7)

**Comment by ojw28** [comment]
We don't currently support seeking in live HLS. This is indicated in the `Timeline` exposed by the player. If you use the demo app, you'll see that the seek controls are disabled when playing such media.

Adding support for seeking in live HLS is tracked by https://github.com/google/ExoPlayer/issues/87.
