### ISSUE TITLE
Mpeg DASH: PTS will be reset 

### ISSUE THREAD

**Issue by WeiChungChang** [google/ExoPlayer#1945]
Dear all:

I just download the EXOplayer V2 a couple of days ago but find a strange thing when playing test URL.
Please refer to the test link below:
http://demo.unified-streaming.com/video/smurfs/smurfs.ism/smurfs.mpd?format=mp4
I find the after playing the first segment, the PTS will roll back to 0 again.
For native test link, it is no problem because the 'tfad' BOX provides the correct offset,
However, if there is no "tfad" BOX, the PTS will rollback to zero & abnormal condition happens.

Previously I worked for DASH by GStreamer where every time a new segment  starts the DASH demuxer will pass down the PTS offset to demuxer. Since the demuxer will reset the PTS to 0 (if no tfad box), it needs a correct offset. GStreamer does it well so it is fine.

Could someone give it a check please?

Also, I do NOT know how to create a new test item for V2. Previously it is easy by adding a new item within samples.java but I have no idea where it has gone...
Could someone help me to set the customized new test item please?

Thanks

**Comment by gbhall** [comment]
You can add your test item to this file:
https://github.com/google/ExoPlayer/blob/release-v2/demo/src/main/assets/media.exolist.json

**Comment by WeiChungChang** [comment]
Sorry;

Finally I found I made a mistake since the spec of ISO 23009-1 says:

**Each ‘traf’ box shall contain a ‘tfdt’ box.**

and the link indeed has tfdt.

Maybe the problem comes from other test MPD files which do NOT follow the spec.

Thanks

**Comment by ojw28** [comment]
There are multiple ways to add items to the demo app, which are documented [here](https://google.github.io/ExoPlayer/demo-application.html).

I'm not really sure what you're getting at here. I tried playing the sample to which you link and it plays fine in the demo app, with the time advancing correctly up to 1 minute. What do you mean when you say the "PTS will roll back to 0 again"? Are you referring to some internal state?
