### ISSUE TITLE
Demo project doesn't handle out-of-date live streams (?)

### ISSUE THREAD

**Issue by jglanfield** [google/ExoPlayer#1949]
I may be misunderstanding how the ExoPlayer.playWhenReady() method actually works, but when you press the play button in the demo project, it is handled in PlaybackControlView.java like so:

```
else if (playButton == view) {
  player.setPlayWhenReady(!player.getPlayWhenReady());
}
```

However, assume that the HLS stream is a live event and that the user has sat on the paused state for long enough that resuming playback from that state is no longer possible. In this case, it really should "fast forward" or reload the current stream.

I'm happy to be corrected on this.

**Comment by jglanfield** [comment]
No thoughts on this? I'll find a stream to test this on.

**Comment by jglanfield** [comment]
Here is a sample stream:

http://live.tvtomsk.ru/hls/RT-24.m3u8

The segments are 5 seconds in length, and there are 6 of them. Load the stream, play it for a second and then pause it. Wait for more than 30 seconds and then resume playback. Once it hits the end of the window the player will stop and will never resume.

**Comment by ojw28** [comment]
Yes, you're right. Note that you can just not implement it that way in your own app ;). We'll get around to fixing the demo app to do something more sensible at some point, but it's not high priority.

**Comment by jglanfield** [comment]
For sure. In the meantime, I'm guessing the best way to handle it is as I mentioned in my first post? If the stream ends, reload? But maybe there's a better way. In the demo app, the state of the stream when it stops playing is "IDLE" and playWhenReady is true. So there's nothing there that tells me I should reload the stream. Any thoughts?

**Comment by ojw28** [comment]
The demo app now handles this case in a nicer way. The relevant piece of code is `PlayerActivity.isBehindLiveWindow`, which identifies whether playback has failed due to falling behind the live window, and the place that makes use of it:

```
if (isBehindLiveWindow(e)) {
  clearResumePosition();
  initializePlayer();
} ...
```
