### ISSUE TITLE
Subtitles can be hidden prematurely or never rendered

### ISSUE THREAD

**Issue by jschools** [google/ExoPlayer#1950]
**Issue:**
Occasionally, a subtitle will be hidden prematurely or never displayed at all. Debugging the stream shows that the affected subtitles always span a text sample boundary. This issue occurs when rendering subtitles that come from a streaming MP4 source. I have tested using a TTML stream, but it may reproduce with other formats.

**Cause:**
Consider two adjacent text samples. Sample A starts at 03:00.000 and has a 1-minute duration. Sample B starts at 04:00.000 and also has a 1-minute duration. Subtitle S has a start time of 03:59.500 and an end time of 04:02.000, which spans the boundary of the two samples, and it is contained in sample A. Subtitle T starts at 4:03.000 and is contained in sample B. When the playback position reaches 3:59.500, the TextRenderer is operating on sample A, and it shows subtitle S at the correct time. It should remain visible until 04:02.000, but it disappears at 04:00.000 after being shown for only 500ms.

TextRenderer immediately abandons sample A and switches to sample B when the playback position reaches 04:00.000, which is two seconds before the end time of subtitle S. It queries sample B for subtitles at the current playback position (04:00.000) and finds no titles, since sample B does not contain subtitle S, and subtitle T doesn't start until 04:03.000. The renderer flushes the text output, hiding the subtitle prematurely.

**Workaround:**
The least invasive change I could make to solve the issue was to modify SimpleSubtitleDecoder so that it sets the start time of every text sample to the time of the first subtitle contained within that text sample. For example, the sample time of B is changed from 04:00.000 to 04:03.000. As long as the time spans of S and T are not intended to overlap, this should solve the problem. 

It seems like the correct place to fix this bug is actually in TextRenderer, so that even overlapping subtitles can be handled correctly. However, I didn't know how this would affect the display of subtitles during a seek.

**Comment by ojw28** [comment]
In this case I think correct media should duplicate Subtitle S in both Sample A (03:59.500 -> 04:00.000) and in Sample B (04:00.000 -> 04:02.000).

It seems wrong that a sample's content should extend beyond its duration. Such an approach wouldn't work properly when seeking, even with the fix you propose. For example if a seek occurred to 04:01.000 then the player would start from Sample B, and so wouldn't show Subtitle S even though it should be made visible. This is obviously not a major issue, but is an explanation of why it would be sensible for specifications to require duplication of the subtitle.

If you can point to a spec that indicates what you're doing is valid, please let us know.

**Comment by ojw28** [comment]
Note - When I say the seeking issue wouldn't be major, that really depends on how far subtitles extend beyond the end of their containing samples. If they extend a long way, it would be a more significant problem.

**Comment by jschools** [comment]
Hm, you're absolutely right:
https://www.w3.org/community/texttracks/2013/09/11/carriage-of-webvtt-and-ttml-in-mp4-files/

Guess I'll keep my temporary fix until the media can be repackaged. Thanks for your time.
