### ISSUE TITLE
Question. H.264 video profiles support by android devices

### ISSUE THREAD

**Issue by luckcoolla** [google/ExoPlayer#1952]
Hello,
I see that by default android devices should support only baseline video profile of H.264 AVC codec (https://developer.android.com/guide/appendix/media-formats.html), example Media type strings([link for other examples](https://developers.google.com/cast/docs/media#mp4-video-and-audio)):
- video/mp4; codecs="avc1.42E01E, mp4a.40.5"
- video/mp4; codecs="avc1.42E01F, mp4a.40.5"

I see other types of the H.264 support depends on the device. The next manifest could be player only by several our test devices:

``` ...
      <AdaptationSet
      group="2"
      contentType="video"
      par="16:9"
      minBandwidth="2000000"
      maxBandwidth="2000000"
      segmentAlignment="true"
      width="640"
      height="360"
      frameRate="25"
      mimeType="video/mp4"
      codecs="avc1.4D4029"
      startWithSAP="1">
      <!-- Common Encryption -->
      <ContentProtection
        schemeIdUri="urn:mpeg:dash:mp4protection:2011"
        value="cenc"
        cenc:default_KID="26AF8834-4766-48B4-8562-8C3F31343B9D">
      </ContentProtection>
      <!-- PlayReady -->
      <ContentProtection
        schemeIdUri="urn:uuid:9A04F079-9840-4286-AB92-E65BE0885F95"
        value="MSPR 2.0">
      </ContentProtection>
      <!-- Widevine -->
      <ContentProtection
        schemeIdUri="urn:uuid:EDEF8BA9-79D6-4ACE-A3C8-27DCD51D21ED">
      </ContentProtection>
      <!-- ClearKey -->
      <ContentProtection
        schemeIdUri="urn:uuid:1077EFEC-C0B2-4D02-ACE3-3C1E52E2FB4B">
      </ContentProtection>
      <!-- Marlin -->
      <ContentProtection
        schemeIdUri="urn:uuid:5E629AF5-38DA-4063-8977-97FFBD9902D4">
<mas:MarlinContentIds>
  <mas:MarlinContentId>urn:marlin:kid:26af8834476648b485628c3f31343b9d</mas:MarlinContentId>
</mas:MarlinContentIds>
      </ContentProtection>
      <SegmentTemplate
        timescale="25"
        initialization="cmorefsden-$RepresentationID$.dash"
        media="cmorefsden-$RepresentationID$-$Time$.dash"
        startNumber="1">
        <!-- 2016-10-17T07:48:00Z / 1476690480 -->
        <SegmentTimeline>
          <S t="36917262000" d="50" r="89" />
        </SegmentTimeline>
      </SegmentTemplate>
      <Representation
        id="video=2000000"
        bandwidth="2000000"
        scanType="progressive">
      </Representation>
    </AdaptationSet>
    ...
```

Is there any way to add support of a non-baseline H.264 codec programmatically?

**Comment by AquilesCanta** [comment]
Sorry for prematurely closing this. As @ojw28 correctly pointed out, if you are using Exoplayer, you could add an extension for decoding H.264 through software in a similar way as the [VP9 extension](https://github.com/google/ExoPlayer/tree/release-v2/extensions/vp9) does. I am sure someone else will be able to provide more accurate information about this.

**Comment by ojw28** [comment]
Right, you could implement an extension that bridges onto a software H264 decoder with main/high profile support. You can look at the VP9 extension for a general example of how to do this. It would be up to you to implement something similar that bridges onto a suitable H264 decoder. Note that software decoders are in general less efficient than the hardware supported decoders that are often exposed through MediaCodec. There's no guarantee that a software decoder would be able to decode fast enough, particularly at high bitrates. Power consumption will also likely be higher. This is something you'd have to experiment with and make your own decision on.

I think the example you provide is main profile. I would expect the vast majority of devices to handle main profile, despite it not being required by the Android CDD. YouTube use main profile quite liberally, although they do have a fallback I believe. Are there popular devices that you're seeing not support it? Would it be an option to also provide a low quality baseline profile stream as an additional Representation, for such devices?

**Comment by luckcoolla** [comment]
Thank you for help, I will check out the VP9 extension realisation.

> Are there popular devices that you're seeing not support it?

Nexus 6 and several Samsung devices (not sure they are popular as Nexus one); sony xperia m4

> Would it be an option to also provide a low quality baseline profile stream as an additional Representation, for such devices?

Sure, it's an option, we are going to fix the stream set up and add new Representations

**Comment by ojw28** [comment]
I would expect Nexus 6 to support main profile. Looking again at your sample, it appears to have DRM. Are you sure it's not a DRM issue / limitation that you're hitting? We'd need a test stream or at least a full bug report to debug further.

**Comment by luckcoolla** [comment]
I'm sure (at ~95% :-) ), it's not a DRM issue. We have a clear stream with same settings and it has same video track that is not supported by same devices list. Let me check it again and post its manifest part.

```
<AdaptationSet
      group="2"
      contentType="video"
      par="16:9"
      minBandwidth="432000"
      maxBandwidth="1500000"
      minWidth="320"
      maxWidth="640"
      minHeight="180"
      maxHeight="360"
      segmentAlignment="true"
      frameRate="25"
      mimeType="video/mp4"
      startWithSAP="1">
      <SegmentTemplate
        timescale="25"
        initialization="cmorefsd-$RepresentationID$.dash"
        media="cmorefsd-$RepresentationID$-$Time$.dash"
        startNumber="1">
        <!-- 2016-10-18T09:36:19Z / 1476783379 -->
        <SegmentTimeline>
          <S t="36919584475" d="50" r="899" />
        </SegmentTimeline>
      </SegmentTemplate>
      <Representation
        id="video=432000"
        bandwidth="432000"
        width="320"
        height="180"
        codecs="avc1.42C01F"
        scanType="progressive">
      </Representation>
      <Representation
        id="video=1000000"
        bandwidth="1000000"
        width="480"
        height="270"
        codecs="avc1.42C01F"
        scanType="progressive">
      </Representation>
      <Representation
        id="video=1500000"
        bandwidth="1500000"
        width="640"
        height="360"
        codecs="avc1.4D4029"
        scanType="progressive">
      </Representation>
    </AdaptationSet>
```

I've just checked - Nexus 6 and sony xperia m4 cann't work with the last Representation
<img src="https://cloud.githubusercontent.com/assets/3755157/19474784/d6ecb462-9539-11e6-868f-40a3dccf8466.png" alt="screenshot_2016-10-18-13-45-47" width="400" height="600"/>

**Comment by ojw28** [comment]
Can you share the clear stream so we can take a look? I think it should be supported on a Nexus 6.

**Comment by luckcoolla** [comment]
@ojw28 I've discussed with PM the stream sharing/tmp vpn creation. We are sorry, but it's not an option now
