### ISSUE TITLE
AspectRatioFrameLayout width/height problem due to the deformation fraction. 

### ISSUE THREAD

**Issue by cesards** [google/ExoPlayer#1953]
Developers are not able to tweak the field `MAX_ASPECT_RATIO_DEFORMATION_FRACTION` contained in the `AspectRatioFrameLayout`, so we can't really control the final measurement of the view (the current deformation fraction is very low, as 0.01f)

![video](https://cloud.githubusercontent.com/assets/1536079/19440820/3f4c7bba-947b-11e6-8984-affe64f4a2d8.png)

It doesn't matter if you set the aspect ratio to `RESIZE_MODE_FIXED_WIDTH` or `RESIZE_MODE_FIXED_HEIGHT`, because you are going to be having the same problem with the bottom part of the view.

**Comment by ojw28** [comment]
I'm a bit confused by this issue. If you want complete control over the final measurement of the view then you shouldn't be using `AspectRatioFrameLayout`. By definition it doesn't provide you with exact control.

I'm uncertain whether you understand correctly what the deformation fraction does. Would you tweak it to be larger or smaller, and what would you expect this to achieve?

**Comment by marcbaechinger** [comment]
When you are using RESIZE_MODE_FIT which is the default mode you can control the dimension/measurement of the SimpleExoPlayerVideoView. The view itself is not resized in this case but only the video inside the view.

**Comment by eneim** [comment]
can you put a better screenshot? why use black video screen on black background?

**Comment by eneim** [comment]
Actually my solution for this is to build my own widget that mimics AspectRatioFrameLayout. I guess that will be much faster and more flexible for user side.
