### ISSUE TITLE
Question. ExoPlayer2 STATE_PREPARING analog

### ISSUE THREAD

**Issue by luckcoolla** [google/ExoPlayer#1956]
Hello,
I see exo player 2.0 has been updated with ExoPlayer.STATE_PREPARING removing. Is there any method to check the state like player.isPreparing()? - I cann't find any similar, except player.isLoading(), but it returns false.
Or probably.. are you going to move back the state?

exoPlayer 1.x behavior:

```
10-17 17:05:01.704 14251-14251/com.example.development D/VideoPlayerManagerImpl: preparePlayer() called, uri: http://...
10-17 17:05:01.704 14251-14251/com.example.development I/ExoPlayerImpl: Init 1.5.9
10-17 17:05:01.709 14251-14251/com.example.development D/VideoPlayerManagerImpl: playWhenReady=false, playbackState=preparing
10-17 17:05:01.804 14251-14251/com.example.development D/VideoPlayerManagerImpl: playWhenReady=false, playbackState=buffering
10-17 17:05:02.229 14251-14251/com.example.development D/VideoPlayerManagerImpl: playWhenReady=false, playbackState=ready
```

exoPlayer 2.x behavior:

```
10-17 17:03:32.257 13401-13401/com.example.development D/VideoPlayerManagerImpl: preparePlayer() called, uri:http://...
10-17 17:03:32.257 13401-13401/com.example.development I/ExoPlayerImpl: Init 2.0.1
10-17 17:03:32.307 13401-13401/com.example.development D/VideoPlayerManagerImpl: playWhenReady=false, playbackState=buffering
10-17 17:03:32.407 13401-13401/com.example.development D/VideoPlayerManagerImpl: onLoadingChanged(true)
10-17 17:03:34.057 13401-13401/com.example.development D/VideoPlayerManagerImpl: playWhenReady=false, playbackState=ready
```

So, btw preparePlayer() call and 17:03:32.257 and 17:03:32.307 we don't know, what is the player state/

**Comment by ojw28** [comment]
Preparing is treated as buffering in V2. Existence of the preparing state didn't generalize well to the introduction of playlist support. I don't think it's necessary for you to be able to distinguish between the two states. Do you have a use case where this is necessary?

**Comment by luckcoolla** [comment]
Yeah, I really don't need to distinguish btw preparing and buffering. 

But in the current realization I can see time delay between prepare(source) call and listener.onPlayerStateChanged(..) being called. This is the issue, in exo 1.x it was 5 ms, as you can see.

**Comment by ojw28** [comment]
State changes in ExoPlayer are asynchronous by design, so there will be a small delay between performing an operation that changes the state and the state change taking effect and becoming visible. You still haven't explained why this is a problem for you.

**Comment by luckcoolla** [comment]
well, I have several places where playback should be started, in the start method I'm checking, if the preparing is not being performed already. 
Thank you for clarification, I'm going to implement it in the wrapper layer.
