### ISSUE TITLE
Wrong ExoPlayer version dependency in extension-okhttp 

### ISSUE THREAD

**Issue by b95505017** [google/ExoPlayer#1957]
https://bintray.com/google/exoplayer/download_file?file_path=com%2Fgoogle%2Fandroid%2Fexoplayer%2Fextension-okhttp%2Fr2.0.3%2Fextension-okhttp-r2.0.3.pom

``` xml
<groupId>com.google.android.exoplayer</groupId>
<artifactId>extension-okhttp</artifactId>
<version>r2.0.3</version>
<packaging>aar</packaging>
<dependencies>
  <dependency>
  <groupId>com.google.android.exoplayer</groupId>
  <artifactId>exoplayer</artifactId>
  <version>r2.0.2</version>
  <scope>runtime</scope>
  </dependency>
```

**Comment by ojw28** [comment]
Fixed. Thanks. We're still "fixing" that file manually as part of the release process, since we haven't had time to work out how to fix it automatically. I just got it wrong this time around!
