### ISSUE TITLE
How to get the current sound amplitude from exovideplayer?

### ISSUE THREAD

**Issue by qillura** [google/ExoPlayer#1959]
For the current project I'm working on, we want to display an animation based on the sound amplitude of video playing in exoplayer, which updates every 30 ms. Is there a way to grab the sound amplitude from exoplayer?

One way to do so is to grab the decibel out of the decompressed audio frames, or directly from the hardware. Are any of the two possible with ExoPlayer?

**Comment by ojw28** [comment]
This is not something we support.

**Comment by ojw28** [comment]
Note: Depending on what exactly you mean by the decibel value, I'm not even sure that the question makes sense. What would you expect the reference point be?

**Comment by qillura** [comment]
sorry clarifying my quesiton:

For the current project I'm working on, we want to display an animation based on the sound amplitude of video playing in exoplayer, which updates every 30 ms. Is there a way to grab the sound amplitude from exoplayer?

One way to do so is to grab the decibel out of the decompressed audio frames, or directly from the hardware. Are any of the two possible with ExoPlayer?

**Comment by ojw28** [comment]
It's still unclear what you mean by decibel. That aside, this is not something we support directly. It would probably be possible for you to extend ExoPlayer's audio renderer and AudioTrack classes to add support for this, but this is not something we intend to support in the core library.

**Comment by qillura** [comment]
Thanks a lot!
