### ISSUE TITLE
How to get the current sound amplitude from exovideplayer?

### ISSUE THREAD

**Issue by qillura** [google/ExoPlayer#1960]
Really sorry for extra issue created. Let me clarify my question:

For the current project I'm working on, we want to display an animation based on the sound amplitude of video playing in Exoplayer, which updates every 30 ms. So we need the average sounds amplitude for the last 30ms of video that was played.

One way to do so is to grab the decibel out of the decompressed audio frames, or directly from the hardware. Are any of the two possible with ExoPlayer?

Apologize again for the extra issue!

**Comment by ojw28** [comment]
Same as https://github.com/google/ExoPlayer/issues/1959.
