### ISSUE TITLE
Trying to play Live HLS stream in Exoplayer

### ISSUE THREAD

**Issue by ShikhaAndroid** [google/ExoPlayer#1961]
I am using Live **HLS** Stream to play the video in the **Exoplayer** . Stream does not call the **PLAYER ENDED** state, rather than that it keep calling the **PLAYER IDLE** state. I just want to inform the users that the **LIVE** stream is ended with the text message. I just want to know how can i find the **PLAYER ENDED** state in the live stream.

**Comment by ojw28** [comment]
Please provide a full bug report, as is clearly requested in the issue template, along with the other requested information.

**Comment by Arlem** [comment]
@shikha7763 does your last manifest contain the #EXT-X-ENDLIST Tag on the last row?

**Comment by ShikhaAndroid** [comment]
@ojw28 i am using Wowza cloud for live streaming. where i can find this #EXT-X-ENDLIST Tag.

**Comment by Arlem** [comment]
It should be on the .m3u8 the player is reading from. [Maybe it's not supported on Wowza](https://www.wowza.com/forums/showthread.php?47755-EXT-X-ENDLIST-this-tag-is-not-appended-to-m3u8-playlist)?

**Comment by crossle** [comment]
same error, ExoPlayer2 not do #EXT-X-ENDLIST tag, and no end state when live playback end

**Comment by ojw28** [comment]
Wowza should be appending the EXT-X-ENDLIST tag to their live stream HLS media playlists when a live streams end, else this is how the player will behave. I suggest you continue to raise this issue with the Wowza team.

**Comment by crossle** [comment]
If live end, append EXT-X-ENDLIST tag, but exoplayer need wait a moment, and callback the end state

**Comment by ojw28** [comment]
I believe ExoPlayer handles this case correctly already. This issue appears to be specifically about Wowza streams, where the tag is incorrectly not appended.
