### ISSUE TITLE
HLS video corrupted on ASUS MeMO Pad 7 ‏(ME572C)‏ in portrait mode

### ISSUE THREAD

**Issue by tothvoj-gl** [google/ExoPlayer#1972]
When you play this stream https://cdn-films.economist.com/PP/miami.m3u8 in the demo app on this specific tablet, the video is corrupted.

![img_20161020_142020](https://cloud.githubusercontent.com/assets/16701922/19559795/d9ef3088-96d1-11e6-863d-c5c10de999e8.jpg)

The strange thing is, that when you rotate the device to landscape mode, the video is displaying fine without any glitches. I found only these two errors in the logs:

```
10-20 14:21:38.489 13802-14583/com.google.android.exoplayer2.demo E/OMXNodeInstance: OMX_GetExtensionIndex OMX.google.android.index.storeMetaDataInBuffers failed
10-20 14:21:38.499 13802-14649/com.google.android.exoplayer2.demo E/ACodec: [OMX.Intel.VideoDecoder.AVC] storeMetaDataInBuffers failed w/ err -2147483648
```

**Comment by ojw28** [comment]
Closing as part of a scrub of old device specific issues.
