### ISSUE TITLE
Mp4 meta header parsing error

### ISSUE THREAD

**Issue by xylik** [google/ExoPlayer#1973]
Hi, 
ExoPlayer_1(dev branch) fails to correctly seek and after seek operation play local mp4 video file although Android MediaPlayer, native Xiaomi Video Player and native Samsung mini video player can play that same file normally.

Issue is manifested on Xiaomi Redmi 3 Pro(Lollipop 5.1.1) and Samsung mini S4(KitKat 4.4). I have not tested the issue on other phones than those two.

The cause of this issue due to my investigation is because of invalid parsing of mp4 metadata atoms(moov ...). I came to this conclusion by comparing output of [IsoViewer](https://github.com/sannies/isoviewer) and Mp4Extractor.Mp4Track.TrackSampleTable of video track. 

First problem i saw when looking into TrackSampleTable is that first video frame is not key-frame although it should be because IsoViewer shows first frame as keyframe by parsing stss atom of video track.

How i came to this issue? 
Am cutting mp4 remote video files with ffmpeg compiled for android, the command looks like this:
ffmpeg -ss 00:00:47.427 -i https://yt_mp4_path/in.mp4 -t 00:00:08.095 -c:a copy -c:v copy /local_path/out.mp4

When cut operation is finished am playing cutted file with ExoPlayer but before play i seek on that file to compensate imprecise video cutting for:
delta = cut_start_time_stamp - first_key_frame_time_stamp_before_cut_start_time_on_remote_file

Explanation: FFmpeg command from above first seeks on remote mp4 video file(in.mp4) than cuts it(-t param specifies cut length) starting from first key-frame before <-ss time> without re-encoding(plain bit stream copy) video/audio and saves it in local file(out.mp4).

Problematic ffmpeg cutted file and full length mp4 file can be obtained from my gdrive:
https://drive.google.com/open?id=0Byn0xtAvVbCWbThTVWJfSHN1aG8

On problematic mp4 file when looking into TrackSampleTable.flags of video track, am seeing first keyFrame on index=97  which is not correct it should be on index=0.

I have encountered this issue with all files which I had cut with ffmpeg, and the pattern is allways the same: native video players can play those files without problems, exo starts playing audio but video is freezed on some frame for few moments and then continues playing video normally. During the play time, audio seems to play correctly only video is freezed for few moments....

**Comment by ojw28** [comment]
Sounds edit list related.

**Comment by andrewlewis** [comment]
This appears to be the same as #1659. We do not support prerolling when applying an edit list. The first sample (which is a synchronization sample) gets discarded when applying the edit.

**Comment by xylik** [comment]
@andrewlewis @ojw28 Thanks for pointing me to #1659 and keep up with good work on ExoPlayer, would you be so kind and take a look at my superuser [question](http://superuser.com/questions/1133700/compensate-key-frame-time-distance-when-video-cutting-with-ffmpeg) it's related to issue i opened here.

**Comment by andrewlewis** [comment]
This is not really in scope for this issue tracker, but: to cut the video so it starts at an arbitrary position you will either need (1) a player that can pre-roll from the key-frame before the cut point, or (2) to re-encode (at least) the first group of pictures up to the key-frame following the cut point.

In case (1) the player has to decode almost a whole group of pictures in the worst case which will introduce a pause when playback starts. How bad this may be depends on key-frame interval and device performance.

In case (2) the player doesn't need to do anything special but (if you need to do this for arbitrary inputs) it might be difficult to restrict transcoding to just the first group of pictures and still produce a valid stream.
