### ISSUE TITLE
How to handle orientation change with activity recreation

### ISSUE THREAD

**Issue by makvasic** [google/ExoPlayer#1974]
Device: Samsung Galaxy Core 2 (API 19)
Exoplayer version: r2.0.3
This is probably device specific issue.

So, I have retained fragment which holds exoplayer instance because I have complex layouts for different configurations and still want to maintain video playback on orientation changes.
(Solution inspired by this [blogpost](http://jtdowdall.blogspot.rs/search?updated-min=2014-01-01T00:00:00-07:00&updated-max=2015-01-01T00:00:00-07:00&max-results=3))

Only for this device I get the error after orientation change.
`OnPlayerError` gives me `ExoPlaybackException.TYPE_UNEXPECTED`

```
10-20 13:58:10.463 15457-7028/*************** E/ExoPlayerImplInternal: Internal runtime error.
      java.lang.IllegalStateException
            at android.media.MediaCodec.dequeueOutputBuffer(Native Method)
            at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:850)
            at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:477)
            at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431)
            at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:265)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:146)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
```

Here's the [bugreport.](https://github.com/google/ExoPlayer/files/541687/makvasic_SG_Core2_bugreport.txt)

Bug aside, is there any preferred way of maintaining video playback during orientation changes without `android:configChanges="orientation|screenSize"` for exoplayer?

Thanks.

**Comment by ojw28** [comment]
It's quite difficult (although not impossible) to retain video playback across an activity recreation. The fact it's crashing in this way suggests that you've implemented an incorrect solution, that's trying to do something with a Surface after it has been destroyed. This is not an ExoPlayer issue as such.

I'm a little dubious about the correctness of the post you reference. Does the author provide a working example somewhere, and if so does that work for you? Are you able to recreate a working solution using MediaPlayer based on that post?

We do intend to try and provide some guidance in this area at some point, but it'll take us some time; it's not particularly easy to address.

**Comment by makvasic** [comment]
Great, thank you for fast response.

I have solution based on the post with MediaPlayer which is working without any problems regarding orientation.
In short there needs to be global instance of the player and after orientation we only need to reattach the surface...
I was amazed that exoplayer "was doing this out of the box". I have global instace of exoplayer and after orientation I set player to the view `simpleExoPlayerView.setPlayer(player)` and it just worked :) (I was very suspicious why it's working, but then it's exoplayer that's why I love it) so I didn't look into it any more until now :/

Anyway thank you for the great support.

**Comment by b95505017** [comment]
I placed ExoPlayer in Service, and pass Surface from Activity to Service. It means that the Service could run on different process.
Using Loader is a good way to deal with the Activity configuration change.
