### ISSUE TITLE
Implementation of parallel chunks in ExoPlayer

### ISSUE THREAD

**Issue by ravin353** [google/ExoPlayer#1980]
Hi,

I am working on the Exoplayer. I have implemented according to the documentation specified. So, I need to make bit effective to reduce the buffering time. So i need 2 more byte arrays which will loaded by next playing video say(6s). So how can i achieve this in Exoplayer.

Thanks,
R

**Comment by ojw28** [comment]
It's unclear exactly what this is requesting, but it's not possible to configure the amount of parallelism used by ExoPlayer during buffering (and we have no current plans to add this feature).
