### ISSUE TITLE
Video is played with green mosaic using Exoplayer

### ISSUE THREAD

**Issue by JunfeiW** [google/ExoPlayer#1984]
I have a mp4 file, which can be found on this link:
http://ac-pk3qanow.clouddn.com/8614cf7d18c67f009d37.mp4

As you can see in chrome, it is played well. 
But when use ExoPlayer on my cell phone which is (Android 5.1 and using MTK platform), it will be displayed with green mosaic.

![image](https://cloud.githubusercontent.com/assets/5487724/19616630/db818502-984a-11e6-9ed5-a0ac60917c9e.png)

**Comment by JunfeiW** [comment]
Here is exoplayer version:  
compile 'com.google.android.exoplayer:exoplayer:r2.0.4'

**Comment by andrewlewis** [comment]
Please provide all the information requested in the issue template. To diagnose this it would be useful to have a bug report taken just after seeing the artifacts (output by `adb bugreport`). It looks like it might be device-specific as I couldn't reproduce it on a Nexus 5 running L.

**Comment by andrewlewis** [comment]
This stream appears to be in H.264/AVC High profile level 3.0, which is higher than the minimum video decoding requirements for non-TV devices (see [the CDD](https://source.android.com/compatibility/android-cdd.html#5_3_video_decoding)), so there is no guarantee that it can be decoded.

**Comment by AquilesCanta** [comment]
If you want to, you can try playing the file using MediaPlayer. If the issue persists, it is quite likely it is a matter of decoding capacity. Let us know if the issue doesn't reproduce with MediaPlayer, please.

**Comment by JunfeiW** [comment]
Sorry for trouble, figures out that is download problem, the stream file is not downloaded correctly.
Greats thanks for all your help
