### ISSUE TITLE
Ability to play sections of a video (eg: 0:10s - 0:30s) 

### ISSUE THREAD

**Issue by satyan** [google/ExoPlayer#1988]
I'm looking at version 2.x of the API and trying to figure out if I could play sections of a video. eg: play only certain sections in a  1 minute video (eg: 10s- 30s then 40-50s).

Could use seek, but each section would start buffering initially.. and playback doesn't seem smooth.

I tried using the ConcatenatingMediaSource, (providing the same media multiple times, with different timeline). Though, couldn't figure out how to set the start and end time with the Timeline API. 

Any suggestions would be helpful. Thanks.

**Comment by satyan** [comment]
Thanks @andrewlewis for picking it up.. Any quick suggestions on how we could implement it currently? Seeking manually is an option, though not the best.

**Comment by andrewlewis** [comment]
@satyan Sorry for not replying sooner. Please try out ClippingMediaSource and let us know if this does what you need. You can compose ClippingMediaSources in a ConcatenatingMediaSource or LoopingMediaSource as required.

An important caveat is that when playback transitions into a ClippingMediaSource the player needs to do a frame-exact seek operation. To avoid buffering you therefore need to ensure that the clipping start point corresponds to a synchronization sample/key-frame. (Playback should work even if you don't do this, but transitions from one source to the next will not be seamless.)

**Comment by rafiip** [comment]
@andrewlewis  ClippingMediaSource was removed from 2.1.0 release . should we import it manually ?
ps: 
i used this method inside LoopingMediaSource but playback is not seamless 
```

**Comment by jmgirven** [comment]
[ClippingMediaSource](https://github.com/google/ExoPlayer/blob/dev-v2/library/src/main/java/com/google/android/exoplayer2/source/ClippingMediaSource.java) is currently in the dev-v2 branch, so presumably will be available in future releases.

**Comment by satyan** [comment]
Thanks for including this quickly.. It worked beautifully for my case.

**Comment by ojw28** [comment]
It will be available in 2.2.0.
