### ISSUE TITLE
Support CRYPTO_MODE_AES_CBC

### ISSUE THREAD

**Issue by yanglichuan** [google/ExoPlayer#1989]
CRYPTO_MODE_AES_CBC = MediaCodec.CRYPTO_MODE_AES_CBC;

**Comment by yanglichuan** [comment]
not find

**Comment by ojw28** [comment]
We don't support CRYPTO_MODE_AES_CBC yet. Note that it's only available from API level 24, so it's not hugely useful right now given the low penetration of the Android N release. We do have support going forward, so marking as an enhancement.

**Comment by ghost** [comment]
@ojw28  is CBC mode guaranteed in API 24 or is it an OEM 'optional' mode?

Also - what encryption pattern is suuported - cbcs or cbc1?

**Comment by ojw28** [comment]
Unsure. @wvpaf, do you know?

**Comment by ojw28** [comment]
We've added the necessary support in ExoPlayer. Note that the platform only provides the underlying support from API level 24+. We've also found quite a few API level 24+ devices that appear to not work correctly with the new crypto modes. We're following up with the device manufacturers, and also trying to get some better platform level testing in place.
