### ISSUE TITLE
How to get Video Uri

### ISSUE THREAD

**Issue by HeroZ-Dodge** [google/ExoPlayer#1996]
When I playing a MP4 , how can I get A DataSource reference to get the Uri of MP4 ?( maybe  the MP4 is redirects ) ?

**Comment by ojw28** [comment]
This is not something we support directly. What do you need this functionality for?

**Comment by HeroZ-Dodge** [comment]
when user playing mp4 ,I want to report the Uri , used for statistical performance

**Comment by ojw28** [comment]
We're tracking adding support for this in https://github.com/google/ExoPlayer/issues/2054, so I'll go ahead and close this one.
