### ISSUE TITLE
Support wider range of DASH manifests

### ISSUE THREAD

**Issue by ojw28** [google/ExoPlayer#2]
Currently ExoPlayer only supports a narrow subset of possible DASH manifests. Support should be added for manifests containing segment lists and segment templates.

Note: As a workaround, application developers can already support arbitrary DASH manifests through implementing their own parser and ChunkSource (it's probably useful to use DashMp4ChunkSource as a starting point).

**Comment by hafidben** [comment]
Do you have an example of an MPD file with segmentList ?

**Comment by ojw28** [comment]
You could try: http://www-itec.uni-klu.ac.at/dash/ddash/mpdGenerator.php?segmentlength=6&type=full
