### ISSUE TITLE
Post-processing of HLS encrytion key

### ISSUE THREAD

**Issue by xbezdeka** [google/ExoPlayer#2002]
Hi,
I'm using exoplayer 2.0.3 with HLS media playlist with encrypted chunks using standard AES-128 encryption. Only difference is that URI provided for key in the media playlist doesn't lead to the final key, but to some intermediate key that is used for generation of the final key.

Is it possible with Exoplayer API to intercept this key before it's used for decryption and modify it?

**Comment by xbezdeka** [comment]
Ok, for others struggling with this problem, I was able to do what I need by creating custom DataSource object working as a wrapper and monitoring underlying http communication. When open() method is called and Uri in dataspec matches the Uri for key request I intercept data in read() method and modify it accordingly.

**Comment by AquilesCanta** [comment]
We have recently added an `HlsDataSourceFactory` interface. By implementing one, you can provide a custom `DataSource` for media chunks, playlists and keys. In your case @xbezdeka, it might make sense to take advantage of this to avoid matching the Uri yourself. Let me know if you run into any issues.
