### ISSUE TITLE
Change surface can not show image immediately

### ISSUE THREAD

**Issue by lipangit** [google/ExoPlayer#2005]
Hello

[In the project](https://github.com/lipangit/JieCaoVideoPlayer) I need to change surface when playing video.

Example : When MediaPlayer play video on a TextureView(or SurfaceView), I click fullscreen button it will call mediaPlayer.setSurface(OtherSurfaceHolder) to change TextureView(or SurfaceView) on fullscreen and go on play.
But this project is the same as android.media.MediaPlayer Android System Mediaplayer, Image will delay 3-5 minutes.
You can try [this apk](https://github.com/lipangit/TestExoPlayer/blob/master/downloads/app-debug.apk?raw=true), There are two SurfaceView click one SurfaceView will setDisplay on the SurfaceView.Sound is continuous but image when switch holder have very big delay.

ExoPlayer is very small and good performance, I want to uese ExoPlayer, but Image delay when change surfaceHolder is not good,So I have to use [bilibili](https://github.com/Bilibili/ijkplayer), can you please help study to solve the problem.

**Comment by ojw28** [comment]
Please see: https://github.com/google/ExoPlayer/issues/318

**Comment by lipangit** [comment]
I have read all your conversation.

He seems to solve to the problem. But the solution is not common and not universial, I can not use  that code directly, I will learn and study DynamicExoPlayer and exoplayer.

**Comment by lipangit** [comment]
@ojw28 
Change surface in different textureview is not stable, maybe faild.

But change surface in the same textureview is stable, always succeed.

**Comment by lipangit** [comment]
Do you think this is system bug?

**Comment by ojw28** [comment]
This really is already covered in some detail by #318. It's unclear what "not common and not universal" means, or why you can't use the solution provided in that issue. It's also unclear what "not stable" means; there's not enough information here for us to help.
