### ISSUE TITLE
Video glitching while playing MPEG-DASH + Widevine in Exynos devices

### ISSUE THREAD

**Issue by Shyri** [google/ExoPlayer#2009]
Hi,
We are facing glitches in video playback with DRM protected content in devices with Exynos. We are using h264, MPEG-DASH and Widevine. We have tested in several devices, it is only happening in devices having Exynos processor but not in those with Qualcomm.
Here there's a screen record of the glitches.

![ezgif-2386533970](https://cloud.githubusercontent.com/assets/1894980/19772176/aae70e2a-9c65-11e6-9693-665829386eda.gif)

Each bitrate is giving different glitch shapes, but always the same within the same bitrate. In any case it doesn't seem to be a bitrate issue.

Unfortunately I cannot give a link to the content. Exoplayer used was version 2, tag release-v2.

Devices having the issue:
- SM-G925F - Android 6.0.1 
- SM-T710 - Android 6.0.1
- SM-N920C - Android 6.0.1

Devices without issue:
- SM-G900F - Android 6.0.1
- LGE Nexus 5 - Android 6.0.1

**Comment by wvpaf** [comment]
@Shyri can you provide a adb log? if the content cannot be shared there may not be much the OEM can do to troubleshoot.

**Comment by Shyri** [comment]
@wvpaf We've tried with a reprocessed version of the same content, with and without protection. It works properly without protection, so we think is some specific issue with the DRM.

I'll attach a bugreport in case you can see something in there. We'll keep testing further

[exoplayer2_report.txt](https://github.com/google/ExoPlayer/files/576367/exoplayer2_report.txt)

**Comment by Shyri** [comment]
Hi @wvpaf , we have an update on this.
We tried to package a small sample of a video using widevine test license server in order to see if it was working properly and there could be some problem of our DRM provider. The result is still same, not glitching for qualcomm, glitching for Exynos. You can see here:

![ezgif-411331412](https://cloud.githubusercontent.com/assets/1894980/20096730/87145d96-a5ab-11e6-8273-406199e67e60.gif)

Attached you can see the source and the packaged content with the mpd, so you can test with it, together with a bugreport in case it is useful.

[test_video.zip](https://github.com/google/ExoPlayer/files/577968/test_video.zip)

Thanks

**Comment by cagdasdirek** [comment]
@wvpaf any update about this issue?

**Comment by Shyri** [comment]
Hi @wvpaf 
We have another update:
We have tried with Samsung S7 edge, which has Exynos 8 family and glitches are not happening.
Also we have tried a Samsung S6 edge with Android 5.0.1 and it is not happening, but after updating it to Android 6.0.1 it started glitching. Could this be some Samsung bug in their firmware or something?

**Comment by ojw28** [comment]
@wvpaf - Friendly ping. Can we follow up on this? Thanks.

**Comment by mlondon1** [comment]
This sounds similar to the issue we were seeing on Samsung devices.  If you try Level 3 security rather than default Level 1, does the issue go away?   Also are you using Exoplayer 2.0.3 or greater?

**Comment by wvpaf** [comment]
Hi I was hoping to have more detailed update, however there is good news.  

According to the OEM representative the issue has been fixed for few 'familys' of Exynos powered devices.  
But have not been able to get updates on what versions will be needed nor how the fixes would be applied.

**Comment by Faved** [comment]
Hi All,

I am just posting to see if there has been any further developments regarding this issue. I know wvpaf mentioned that there has been some "fixes" and how they will be applied is not known.

has anyone heard anything?

Many thanks

**Comment by Shyri** [comment]
Hi again @wvpaf we are still facing this issue and it's blocking us very hard. It seems OEM hasn't release the fix yet... We are running all options here and it would be very useful for us if you can tell what the fix consists of. I mean what was the bug about and how did they fix it.

Thank you very much

**Comment by mlondon1** [comment]
Did you try using Level 3 security?

**Comment by Shyri** [comment]
Hi @mlondon1

Maybe I am wrong, but I think the devices don't really need to support level 3 if they already provide level 1.
Trying to force to level 3 on all devices listed on top (ones with exynos) will lead to this exception

```java
android.media.MediaDrm$MediaDrmStateException: Failed to handle provision response: DRM vendor-defined error: -2954
   at android.media.MediaDrm.provideProvisionResponseNative(Native Method)
   at android.media.MediaDrm.provideProvisionResponse(MediaDrm.java:900)
   at com.google.android.exoplayer.drm.StreamingDrmSessionManager.onProvisionResponse(StreamingDrmSessionManager.java:361)
   at com.google.android.exoplayer.drm.StreamingDrmSessionManager.access$700(StreamingDrmSessionManager.java:47)
   at com.google.android.exoplayer.drm.StreamingDrmSessionManager$PostResponseHandler.handleMessage(StreamingDrmSessionManager.java:483)
   at android.os.Handler.dispatchMessage(Handler.java:102)
   at android.os.Looper.loop(Looper.java:158)
   at android.os.HandlerThread.run(HandlerThread.java:61)
   at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
```

also, according to this link http://www.programering.com/a/MDO1EjNwATQ.html L3 should be provided by the manufacturer, it makes sense not to provide L3 is they already are providing L1 in hardware right?

Have you tried? which devices are you using?

**Comment by ojw28** [comment]
As far as I know it should always be possible to force to L3, and L3 does not require manufacturer specific integration work. There were some ExoPlayer releases that didn't handle L3 provisioning correctly, but it should work with the latest 1.x and 2.x releases.

**Comment by mlondon1** [comment]
We worked around some of these Samsung CDM issues by using L3 security in Exoplayer 2.x with success on many Android devices.  We were having some device specific issues like you have above that were resolved by going this route.  Without it, we would be stuck as well.

**Comment by wvpaf** [comment]
There does seem to be a few issues with the Exynos chip based devices. The OEM has investigated and believes they have a fix. however we do not have any details on the fix, what the defect/solution is, nor what version of the software with the fix. 

Do you observe the macroblocking with the widevine exoplayer test content?

**Comment by wvpaf** [comment]
If no reply i will close next week.

**Comment by wvpaf** [comment]
Closing

**Comment by Shyri** [comment]
Finally... Today Samsung released a new update that includes upgrade to Android 7 and a fix to this issue. So at the end all was related to Samsung's firmware...
