### ISSUE TITLE
Ffmpeg Documentation

### ISSUE THREAD

**Issue by SrujithPoondla** [google/ExoPlayer#2010]
Is there any documentation for exoplayer, how to test the ffmpeg extension?  I am able to successfully build the Ffmpeg extension and its jni libraries.If any one worked on this please tell.

**Comment by andrewlewis** [comment]
To try out the ffmpeg extension from the demo app:
1. Follow the [instructions](https://github.com/google/ExoPlayer/tree/dev-v2/extensions/ffmpeg) to build the native part of the extension.
2. Show build variants in Android Studio and select the `withExtensionsDebug` build variant of the demo app module.
3. Play some media where the audio is in one of the formats that can be decoded by the FfmpegAudioRenderer. Note that the set of supported formats will depend on the options you used to configure FFmpeg in step 1.

To test out playback of your own streams in the demo app, follow the instructions in the developer guide about [playing your own content](https://google.github.io/ExoPlayer/demo-application.html#playing-your-own-content). Note that the 'prefer extensions' flag will determine whether the FfmpegAudioRenderer is used in preference to MediaCodecAudioRenderer if both renderers support the audio format.

**Comment by SrujithPoondla** [comment]
Thanks @andrewlewis , Is there any tutorial to build our own custom extractor renderer for video using Ffmpeg extension or any other extension?

**Comment by andrewlewis** [comment]
@SrujithPoondla If you want to write a custom video renderer that uses FFmpeg, I'd recommend taking a look at the [vp9 extension](https://github.com/google/ExoPlayer/tree/release-v2/extensions/vp9) as a starting point. That extension wraps libvpx but you could use a similar structure for wrapping FFmpeg. I'm not aware of any tutorials about how to do this I'm afraid.

As a general point, video decoding in software is normally inefficient compared to using decoders that are part of the platform. I'd advise against this approach, especially if your app targets mobile devices.

**Comment by nguyenxvn** [comment]
Thanks @andrewlewis I get and build ffmpeg extension from github with the guild to build but i get some error. This guild is use for Linux. Do you have any guild to build this entension on Window OS?

**Comment by andrewlewis** [comment]
@nguyenxvn I'm afraid I don't have any information on building FFmpeg on Windows. Maybe [FFmpeg's compilation guide](https://trac.ffmpeg.org/wiki/CompilationGuide) will help.

**Comment by nguyenxvn** [comment]
@andrewlewis I Switch my computer os to Linux and build successfully. Thanks alot!
