### ISSUE TITLE
Udp demo ExoPlayer

### ISSUE THREAD

**Issue by D2dream** [google/ExoPlayer#2011]
i am using exoplayer for live streaming using udp but unable to get desired output it showing an error Unable to connect to 239.0.0.1:1234 i have tried alot but unable to solve plz help

**Comment by andrewlewis** [comment]
There's not enough information to help here, beyond the obvious suggestion of making sure that the address is accessible. Perhaps try playing it using another player.

If you can narrow down the issue to a bug relating to ExoPlayer, please file a new issue providing all the requested information.
