### ISSUE TITLE
add custom media Controller 

### ISSUE THREAD

**Issue by AlirezaGhanbarinia** [google/ExoPlayer#2018]
how to add custom media Controller to Exo player?

in the previous version by using "getPlayerControl" function , we accessed to media controller and player seekbar , is there a function like this in the new version?

**Comment by ojw28** [comment]
We don't use or support `android.media.MediaController` in ExoPlayer V2. It was never an API that was particularly well suited for `ExoPlayer`. Even in V1 it was expected that most people would not use it, with `PlayerControl` documented to say:

> This class is provided for convenience, however it is expected that most applications will implement their own player controls and therefore not require this class.

In V2 we've introduced our own UI components (`SimpleExoPlayerView` and `PlaybackControlView`). They will be really easy to customize from the next release (r2.0.5), and we'll hopefully have a chance to write a blog post detailing this.

**Comment by cyberjaime45** [comment]
This is good news for me, @ojw28  when you do think r2.0.5 will be available?

**Comment by prashant47b** [comment]
https://github.com/google/ExoPlayer/issues/2018
