### ISSUE TITLE
alternative for InfoListener in ExoPlayer2

### ISSUE THREAD

**Issue by AlirezaGhanbarinia** [google/ExoPlayer#2019]
what is the alternative for Info Listener in the new ExoPlayer 2 ?
in the previous version we used InfoListener to detect quality of video by changing internet speed .
I want to know is there an alternative in the new version?
thanks

**Comment by ojw28** [comment]
`InfoListener` was never part of the ExoPlayer API. It was only defined in `DemoPlayer` in the demo app, not in the core library. In V2 the equivalent to copying `DemoPlayer` is to use `SimpleExoPlayer` directly, which is in the core library. It defines a bunch of listeners that you can register that provide equivalent functionality.
