### ISSUE TITLE
audio streams getting struck with new exoplayer update

### ISSUE THREAD

**Issue by sachinbhanot** [google/ExoPlayer#202]
Hi ,
we are trying to playing some audio in new updated exoplayer. the video is getting stuck. .

Its working  in version 1.0.11

http://music.hdi.cdn.ril.com/mod/_definst_/smil:test/1_2021_2.smil/playlist.m3u8

Here are some waring:-
12-12 16:25:06.236: W/SoftAAC2(5245): aacDecoder_DecodeFrame decoderErr = 0x4004
12-12 16:25:06.236: W/SoftAAC2(5245): AAC decoder returned error 0x4004, substituting silence
12-12 16:25:06.428: W/SoftAAC2(5245): aacDecoder_DecodeFrame decoderErr = 0x4004
12-12 16:25:06.429: W/SoftAAC2(5245): AAC decoder returned error 0x4004, substituting silence
12-12 16:25:06.574: E/AudioTrack(5245): Discontinuity detected [expected 18823589, got 19102226]
12-12 16:25:06.735: W/SoftAAC2(5245): aacDecoder_DecodeFrame decoderErr = 0x4004
12-12 16:25:06.736: W/SoftAAC2(5245): AAC decoder returned error 0x4004, substituting silence
12-12 16:25:07.107: W/SoftAAC2(5245): aacDecoder_DecodeFrame decoderErr = 0x4004
12-12 16:25:07.108: W/SoftAAC2(5245): AAC decoder returned error 0x4004, substituting silence

Error:-
12-12 16:26:36.816: E/AudioTrack(5245): Discontinuity detected [expected 58134975, got 58367170]
12-12 16:26:37.779: E/AudioTrack(5245): Discontinuity detected [expected 59295969, got 59621048]
12-12 16:26:38.105: E/AudioTrack(5245): Discontinuity detected [expected 59969347, got 60247984]
12-12 16:26:38.442: E/AudioTrack(5245): Discontinuity detected [expected 60596283, got 60898148]
12-12 16:26:39.002: E/AudioTrack(5245): Discontinuity detected [expected 61455427, got 61734059]
12-12 16:26:39.496: E/AudioTrack(5245): Discontinuity detected [expected 62221678, got 62430659]
12-12 16:26:39.520: E/AudioTrack(5245): Discontinuity detected [expected 62453879, got 62709304]
12-12 16:26:39.983: E/AudioTrack(5245): Discontinuity detected [expected 63173703, got 63405904]
12-12 16:26:40.518: E/AudioTrack(5245): Discontinuity detected [expected 63939963, got 64241815]
12-12 16:26:40.884: E/AudioTrack(5245): Discontinuity detected [expected 64613334, got 64868759]
12-12 16:26:41.259: E/AudioTrack(5245): Discontinuity detected [expected 65240279, got 65565359]
12-12 16:26:41.739: E/AudioTrack(5245): Discontinuity detected [expected 66052978, got 66331615]
12-12 16:26:41.984: E/AudioTrack(5245): Discontinuity detected [expected 66563814, got 66819237]
12-12 16:26:42.455: E/AudioTrack(5245): Discontinuity detected [expected 67283636, got 67585492]
12-12 16:26:42.677: E/AudioTrack(5245): Discontinuity detected [expected 67817692, got 68073115]
12-12 16:26:43.025: E/AudioTrack(5245): Discontinuity detected [expected 68421414, got 68676828]
12-12 16:26:43.420: E/AudioTrack(5245): Discontinuity detected [expected 69071567, got 69326992]
12-12 16:26:43.917: E/AudioTrack(5245): Discontinuity detected [expected 69837831, got 70116461]
12-12 16:26:44.156: E/AudioTrack(5245): Discontinuity detected [expected 70348661, got 70627304]
12-12 16:26:44.643: E/AudioTrack(5245): Discontinuity detected [expected 71114923, got 71393559]
12-12 16:26:44.880: E/AudioTrack(5245): Discontinuity detected [expected 71625759, got 71950848]
12-12 16:26:45.263: E/AudioTrack(5245): Discontinuity detected [expected 72322367, got 72577781]

**Comment by amifer** [comment]
@suresh777 Where can I get the old Exoplayer library?
