### ISSUE TITLE
Group video calling with Wowza Server Android Rtsp Protocol

### ISSUE THREAD

**Issue by praween05** [google/ExoPlayer#2022]
I am using Wowza server for video streaming. The live stream is coming in form of RTSP URL. I want to stream it in android. Also I need to play multiple RTSP URL at the same time on same page ie group video conferencing. Can I achieve the same by the help of ExoPlayer. 

Let me know if it is feasible through ExoPlayer

**Comment by AquilesCanta** [comment]
See #55.
