### ISSUE TITLE
There is only one static frame with sounds while playing video. 

### ISSUE THREAD

**Issue by DevinAllenLee** [google/ExoPlayer#2023]
ExoPlayer is a very powerful player for us , thank you so much.
       But when I tested it on some outdated phones ,  such as Huawei Y511 , Coolpad 8190Q and so on , I found the problem as the title says.
        I`m using version r2.0.4 , but  I`ve  tried other versions like r1.5.9 or r1.5.12 , they failed , either.

**Comment by AquilesCanta** [comment]
This is not enough information for us to help you. Please open a new issue including ALL the information required in the **issue template**. Please double check you include everything listed there.
