### ISSUE TITLE
Compose playlist into sections

### ISSUE THREAD

**Issue by pkegashira** [google/ExoPlayer#2026]
I have a question since i couldn't find anywhere for reliable info. I have an app that has a number of files to play. i need to compose all these into a playlist and perform specific actions on every track, thus things like flash the UI with certain sound files, set a background music for certain video files.

The direction i took was to get the index of the currently playing track and apply my logic. But didn't go well. so i have 2 questions:
1. how can i both play a video and a background music?
2. How can i compose a playlist in which i can divide into sessions where i perform specific actions taking into account user interactions like skip/next

thanks.

**Comment by ojw28** [comment]
> But didn't go well.

Why not? I would expect this approach to work fine.

> how can i both play a video and a background music?

If the video and background audio have the same duration then you can merge them with MergingMediaSource. If they have different durations then this is not something we support. You could use a separate player instance for the background music.

**Comment by ojw28** [comment]
Closing due to lack of clarification.
