### ISSUE TITLE
How to add HTTP Header to MediaSource (Exoplayer 2)

### ISSUE THREAD

**Issue by bubavanhalen** [google/ExoPlayer#2031]
Is there a possibility to use add HTTP-Header such as an "Authorization: Basic xxxxx" to the `MediaSource`. In v2.0.4. 

I found another one with the same problem who explains it little bit better: [HERE](http://stackoverflow.com/questions/40130486/android-exoplayer-create-mediasource-from-defaulthttpdatasource)

**Comment by ojw28** [comment]
I don't really understand the StackOverflow post. If the poster can create a DataSource instance to do what they want, it should be trivial for them to implement DataSource.Factory just to provide instances that are created that way, like:

```
  DataSource.Factory factory = new Factory() {
    @Override
    public DataSource createDataSource() {
      // Create and return source with headers set as required.
    }
  };
```
