### ISSUE TITLE
Audio artifacts during custom processing on audio bytebuffer

### ISSUE THREAD

**Issue by Kexiliu** [google/ExoPlayer#2035]
Hello, (all following line numbers are based on the tip of this repo right now)

I'm trying to do some custom processing on the audio part of a video stream (byte array/byte buffer with variable name "temporaryBuffer" at line 641 of com.google.android.exoplayer2.audio.AudioTrack), the output audio produces with mild artifacts, like "broken audio" with discontinuities (AV still sync at this moment). 

To fix this audio issue, I changed the AudioTrack constructor param (buffersize), at line 457 of com.google.android.exoplayer2.audio.AudioTrack. Now audio is smooth but the video will stuck at a still picture: looks like video frame update is skipped at line 405 of com.google.android.exoplayer2.video.MediaCodecVideoRenderer, and earlyUS will increase over time.

Could you give me some pointer to fix this, I guess either 
1. let me change audio (byte array/byte buffer) without causing artifacts, 
or 
2. maintain AV sync when audio buffersize is changed?

Thanks in advance!

**Comment by ojw28** [comment]
Given (a) The underlying AudioTrack simply plays what it's given, and (b) ExoPlayer feeds regular audio data to the underlying AudioTrack correctly, any artifacts being introduced must be purely a result of the processing that you're performing on the buffers.

This is something you'll need to resolve for yourself, I'm afraid. There's no particular reason why you'd need to change the buffer size; it should be more than large enough already.
