### ISSUE TITLE
Streaming does not work for most streams with 128Kb over mobile connection

### ISSUE THREAD

**Issue by setfire2** [google/ExoPlayer#2039]
Hello,

I use ExoPlayer in my brand new radio streaming app:
https://play.google.com/store/apps/details?id=de.hanosoft.droidio

Currently, I face the following issue: streaming works fine over WiFi for all stations. Over a mobile connection (using UMTS in Germany) a lot of the streams that have a bitrate of 128Kb/s do not start playing. It's an interesting effect since I didn't see the problem occur for streams with lower or HIGHER bitrate. Therefore it does not look like a bandwidth issue to me.

This is an example for a faulty station:
http://bigrradio.cdnstream1.com/5218_128?cb=809148.mp3
This station works fine:
http://108.61.30.179:6520/

Both are mp3 with 128Kb/s. Like I said, over WiFi both stations work fine. The returned content type is audio/mpeg for both streams.

Any idea anyone?

Thanks in advance and kind regards,
Sören

**Comment by ojw28** [comment]
The link indicated as faulty above plays fine for me using ExoPlayer on both a Pixel and an emulator. There's nothing in ExoPlayer that's specific to particular types of mobile connection. We simply use the underlying http stack in both cases. So whatever this is, it's unlikely to be an ExoPlayer issue. You'd need to provide a full bug report (as requested in the issue template) for us to have a chance of further narrowing down the cause.

**Comment by setfire2** [comment]
Thanks for the response. I just tried with a different Smartphone and the problem does not occur there. The phone where it fails is a OnePlus One with Cyanogenmod installed. I guess you can close the issue. If somebody has an idea what may cause the problem on that specific device, I'd be happy to hear from you. Thanks.

**Comment by ojw28** [comment]
Sounds likely to be an issue with Cyanogenmod, so I'd suggest you report it there, or to OnePlus. Alternatively, if you're able to provide a bug report shortly after encountering the issue, it might be possible for us to provide a workaround.

**Comment by setfire2** [comment]
Cyanogen is OPOs official software :-)

Regards,
Sören


Am 06.11.2016 um 19:57 schrieb ojw28:

**Comment by ojw28** [comment]
Yeah, I realised and updated my response, heh :).
