### ISSUE TITLE
start playing video with low bit-rate

### ISSUE THREAD

**Issue by AlirezaGhanbarinia** [google/ExoPlayer#2042]
Hi,

I have update ExoPlayer and facing some issue.
In older version, When i play video HLS link, It was start playing with low bit-rate (low quality).
how to start playing with low bit-rate in exoplayer 2 ?

Please provide me solution for same.

**Comment by dreich** [comment]
Hello!

And I just wanted to ask whether ExoPlayer does automatically switch to the most appropriate track (bitrate) in HLS stream.

**Comment by ojw28** [comment]
Yes, it does.

**Comment by dreich** [comment]
Do these rows respond for auto switching? Is DefaultTrackSelector the class which is reponsible?

> ```
>         TrackSelection.Factory videoTrackSelectionFactory = new AdaptiveVideoTrackSelection.Factory(BANDWIDTH_METER);
>         trackSelector = new DefaultTrackSelector(mainHandler, videoTrackSelectionFactory);
>         trackSelector.addListener(this);
>         trackSelector.addListener(eventLogger);
>         player = ExoPlayerFactory.newSimpleInstance(this, trackSelector, new DefaultLoadControl());
> ```

Should I call any special method for enabling auto switching?

**Comment by ojw28** [comment]
The `TrackSelector` creates track selections. For the adaptive video case the selections are produced by the `AdaptiveVideoTrackSelection.Factory` in the code above. As long as you have similar code to the code in the demo app (and above), it will be enabled by default.

**Comment by shaikhmohsink** [comment]
Hi AlirezaGhanbarinia,
Were you able to figure out a way to always start with the lowest bitrate?
If so please can you share the same.

Thanks,
Mohsin

**Comment by slezadav** [comment]
You can use 
`TrackSelection.Factory videoTrackSelectionFactory = new AdaptiveVideoTrackSelection.Factory Factory(BandwidthMeter bandwidthMeter, int maxInitialBitrate,
        int minDurationForQualityIncreaseMs, int maxDurationForQualityDecreaseMs,
        int minDurationToRetainAfterDiscardMs, float bandwidthFraction)`
and set the maxInitialBitrate value
