### ISSUE TITLE
Play [.m3u8] stream,always in loading

### ISSUE THREAD

**Issue by gongshoudao** [google/ExoPlayer#2043]
The log look like the stream was load completed,but the [onPlayerStateChanged] is always Buffering.
ExoPlayer Verison:2.0.2
Video Format:3mu8
NetWork Connection:WiFi
SDK version:5.1

Log is here:

I: Init 2.0.2
W: Ignoring messages sent after release.
D: state [0.02, true, I]
E: Player_state====playWhenReady=true, playbackState=idle
D: state [0.02, true, B]
E: Player_state====playWhenReady=true, playbackState=buffering
D: positionDiscontinuity
D: sourceInfo [periodCount=1, windowCount=1
D:   period [?]
D:   window [?, false, false]
D: ]
D: onLoadStarted: 
D: loading [true]
D: positionDiscontinuity
D: onLoadStarted: 
D: onLoadCompleted: 
D: onLoadStarted: 
D: onLoadCompleted: 
D: onLoadStarted: 
D: onLoadCompleted: 
D: onLoadStarted: 
D: onLoadCompleted: 
D: onLoadStarted: 
D: onLoadCompleted: 
D: onLoadStarted: 
D: onLoadCompleted: 
D: onLoadStarted: 
D: Tracks [
D:   Renderer:0 [
D:     Group:0, adaptive_supported=N/A [
D:       [X] Track:0, id=0, mimeType=video/avc, supported=YES
D:     ]
D:   ]
D:   Renderer:1 [
D:     Group:0, adaptive_supported=N/A [
D:       [X] Track:0, id=null, mimeType=audio/mp4a-latm, channels=2, sample_rate=44100, language=und, supported=YES
D:     ]
D:   ]
D:   Renderer:2 [
D:     Group:0, adaptive_supported=N/A [
D:       [ ] Track:0, id=null, mimeType=application/cea-608, supported=YES
D:     ]
D:   ]
D:   Renderer:3 [
D:     Group:0, adaptive_supported=N/A [
D:       [X] Track:0, id=null, mimeType=application/id3, supported=YES
D:     ]
D:   ]
D: ]
D: loading [false]
D: sourceInfo [periodCount=1, windowCount=1
D:   period [429.43]
D:   window [429.43, true, false]
D: ]
D: onDownstreamFormatChanged: 
I: MuxOMX ctor
I: [OMX.qcom.video.decoder.avc] setting surface generation to 24938500
D: set up nativeWindow 0xcd997908 for 640x480, color 0x7fa30c04, rotation 0, usage 0x42002900
I: MuxOMX ctor
D: set up nativeWindow 0xcd997908 for 640x480, color 0x7fa30c04, rotation 0, usage 0x42002900
D: sourceInfo [periodCount=1, windowCount=1
D:   period [429.43]
D:   window [429.43, true, false]
D: ]
D: Client defaulted notificationFrames to 3675 for frameCount 11025
D: onLoadCompleted: 
D: onLoadCompleted:

**Comment by ojw28** [comment]
It's unclear what you're actually reporting here. Please provide more details, sample media and a full bug report.
