### ISSUE TITLE
only play audio, video not working after ffmpeg compress

### ISSUE THREAD

**Issue by stephen1706** [google/ExoPlayer#2044]
after i compress a video using ffmpeg command -vcodec mpeg4, it appears that the video player can only play the audio, while the image is blank. i try to open this file using other video player and it is working okay. this is the compression code:

```
String[] complexCommand = {"-y", "-i", path,
                "-strict", "experimental", "-s", resolution, "-r", "25",
                "-vcodec", "mpeg4", "-b", "1000k", "-ab", "48000", "-ac", "2",
                 saveVideoPath + "out.mp4"};
```

if i remove the -vcodec mpeg4 it is working fine on the exoplayer. any idea why? because other player works okay and i dont want to omit the -vcodec mpeg4 command, otherwise the compressing process will be very slow

**Comment by andrewlewis** [comment]
Consult Android's [supported media formats](https://developer.android.com/guide/appendix/media-formats.html) pages and the [CDD](https://source.android.com/compatibility/cdd.html) for information about what formats should be playable on all Android devices/builds. Your best bet may be to encode the video as an H.264/AVC or VPx bitstream, as these formats are relatively widely used. You should be able to configure FFmpeg to encode those formats efficiently but I'm afraid it's outside the scope of this forum to provide specific guidance on encoding tools.

You mention it's playable in other players (and I'll assume you mean on Android). Those players may use their own bundled software decoders, which could explain the discrepancy. That said, if you find that the problematic stream can be played using the platform [MediaPlayer](https://developer.android.com/reference/android/media/MediaPlayer.html), please share a link to the media and a bug report from the device, as requested in the issue template, and we'll take a look.

**Comment by stephen1706** [comment]
- The version of ExoPlayer being used : r2.0.4
- The device(s) and version(s) of Android on which the issue can be reproduced,
  and how easily it reproduces : all device cannot play the video encoded using  "-vcodec mpeg4"
  command in ffmpeg. but this video can be played using the [MediaPlayer](https://developer.android.com/reference/android/media/MediaPlayer.html)

[Video link](https://staging-culture-happy5.s3-ap-southeast-1.amazonaws.com/happy5_prod-6/video/408a20fa-0c13-4934-9901-8c01532feda4.mp4)

[bugreport.txt](https://github.com/google/ExoPlayer/files/582596/bugreport.txt)

**Comment by andrewlewis** [comment]
This appears to be the same as #2007. Please follow that issue for updates. Thanks!

**Comment by andrewlewis** [comment]
As noted in my previous comment and on #2007, you may wish to switch to H.264/AVC instead (if possible). The capabilities reporting for that codec seems to be more reliable.
