### ISSUE TITLE
HLS stream: LoadTask: Unexpected exception loading stream

### ISSUE THREAD

**Issue by sdex** [google/ExoPlayer#2047]
An exception whet trying open the HLS video stream. 
Reproduced with the demo app (ExoPlayer 2.0.4).
Devices - Emulator 6.0, 7.0, Samsung Galaxy S6, Xiaomi Redmi note 3.

The stream link was sent. 

[bugreport.txt](https://github.com/google/ExoPlayer/files/576017/bugreport.txt)
[log.txt](https://github.com/google/ExoPlayer/files/576011/log.txt)

**Comment by AquilesCanta** [comment]
Thanks for reporting this. Will look at it shortly.

**Comment by AquilesCanta** [comment]
This is already fixed in the dev-v2 branch. You can use that branch if needed, or wait until v2.0.5 is actually released.

**Comment by sdex** [comment]
@AquilesCanta Thanks for quick reply. I checked dev-r2 - works well.
