### ISSUE TITLE
vp8/vorbis webm never plays on SCH-i545 4.4.2 (Qualcomm APQ8064T Snapdragon 600)

### ISSUE THREAD

**Issue by ryango** [google/ExoPlayer#205]
Not sure what you want to do about device issues so I figured I'd file it and you can close if you don't want this issue on file.

1 - OMX.SEC.vp8.dec is garbage, so I put a continue in MediaCodecUtil when we encounter that guy. Still stuck but I can get the first frame, so the decoder is working.
2 - Audio never progresses - stuck on waitingForFirstSyncFrame on the webm sample Big Buck Bunny (I assume the one from the CTS tests). If I just use the clock, video progresses fine without audio. If I skip waitingForFirsSyncFrame in feedInputBuffers playback works.

Note this plays fine w/ MediaPlayer so I'm not sure what's going on there.

**Comment by ZuZuK** [comment]
have similar issue with same codec while trying to play advertisement stuff on samsung galaxy tab 4.
device: Samsung SM-T231, Android 4.4.2
codec: OMX.SEC.vp8.dec
problem: audio is playing OK, video is not rendering while trying to play advertisement pre-roll block
source: ImaSdk sample source http://pubads.g.doubleclick.net/gampad/ads?sz=400x300&iu=%2F6062%2Fiab_vast_samples&ciu_szs=300x250%2C728x90&impl=s&gdfp_req=1&env=vp&output=xml_vast2&unviewed_position_start=1&url=[referrer_url]&correlator=[timestamp]&cust_params=iab_vast_samples%3Dlinear

**Comment by brianchu** [comment]
I wonder if you have the same problem I have. Do you know which media file you end up using playing? webM? or mp4? or 3gp? I saw IMA sdk pick webM and it fails to play in Exoplayer.

**Comment by ojw28** [comment]
I believe this is the same as #548, which is now mostly fixed (and will be fully fixed next week). Let's use that issue for tracking.
