### ISSUE TITLE
Move getDurationUs(), startTimeUs & endTimeUs down to MediaChunk

### ISSUE THREAD

**Issue by WeiChungChang** [google/ExoPlayer#2050]
Hi all:

I am studying the EXOPlayer and have a suggestion about the loadable(chunk) interface.

As the figure below, there are four (abstract)classes inherit the abstract class **chunk** . 
Also, interface chuck has a public method named getDurationUs and two public data members named startTimeUs & endTimeUs. However, as you see, the 3 child classes named DataChunk, HlsInitializationChunk & InitializationChunk **are of type = header** and they do NOT own the properties about duration, start time & end time (hence now it is forced to assign the invalid value = **C.TIME_UNSET** when calling the super's constructor). **So why not move the properties down to MediaChunk class?**

It keeps the **Single Responsibility Principle** or otherwise the modification of getDurationUs,  startTimeUs & endTimeUs will be taken place at chunk and may wrongly propagate to  DataChunk, HlsInitializationChunk & InitializationChunk. 

A clearer OO design may be of the figure at the bottom.  I believe a little modification will decouple the thing well and make it better.

Thanks

![chunk_getduration](https://cloud.githubusercontent.com/assets/14846473/20119861/2b4a3fea-a645-11e6-8bac-cfda98c0db4e.png)

![modification](https://cloud.githubusercontent.com/assets/14846473/20119889/47d6ce26-a645-11e6-8be4-eff0f716eab0.png)

**Comment by ojw28** [comment]
I see where you're coming from, but in practice, if you do this, you end up having a to add a whole bunch of blocks that look like:

```
if (chunk instanceof MediaChunk) {
  // Cast to MediaChunk and do something
} else {
  // Do something else
}
```

So pragmatically it ends up being quite a bit cleaner just to define them in `Chunk`.
