### ISSUE TITLE
Report url after redirection to application event listeners

### ISSUE THREAD

**Issue by vishveshdk** [google/ExoPlayer#2054]
Does ExoPlayer provide the IP Address of the server that delievered the media Segment? Similar issue was raised previous in the following bug: https://github.com/google/ExoPlayer/issues/2028

I have used the latest version of ExoPlayer with HLS stream, it does not return the IP address of the Server. The IP address is useful in identify server delivering data. Quite useful to track the source of rebuffer etc.

iOS has MPMovieAccessLogEvent and AVPlayerItemAccessLogEvent, which provide server IP Address. Are there any plan to provide this information?

**Comment by ojw28** [comment]
I'm not sure `HttpUrlConnection` exposes a way of getting the IP address at the platform level. Do you really need the actual IP address, or is the URL after redirection sufficient?

**Comment by vishveshdk** [comment]
Actual IP address would be great. With CDNs being used it would help in identifying problem causing server. 
Everytime ExoPlayer downloads a segment, it could pass on the IP address of the server supplying the segment as part of Format class.

**Comment by ojw28** [comment]
I understand what you're trying to do. I'm saying the actual IP address doesn't appear to be exposed by the underlying network stack, which is why I'm asking whether the URL after redirection is sufficient.

The CDN I have most experience working with redirects to URLs that are machine specific, so having the resolved URL would be fine. I suspect most (all?) CDNs do this, and if so the resolved URL should be fine for your purposes. Can you confirm whether or not this is the case?

**Comment by vishveshdk** [comment]
I understand now, It should be good enough.

**Comment by ojw28** [comment]
Updated the title to reflect the enhancement we'll provide for this.
- The URL after redirection will be reported through `AdaptiveMediaSourceEventListener`'s `onLoadCompleted` method, and possibly `onLoadCanceled` and `onLoadError` in the case that the cancelation or error occurs after the connection has been established.
- We may also want to report the URL after redirection via something in `ExtractorMediaSource.EventListener`.

**Comment by ojw28** [comment]
Reassigning to @tonihei as this is (primarily) analytics related.

**Comment by tonihei** [comment]
That's relatively easy to implement. @ojw28's comment above is a little bit outdated as we made some changes to the media source event reporting.

The updated version is:
- The URL after redirection will be reported through `MediaSourceEventListener`'s callbacks (as above in `onLoadCompleted` and if applicable also in `onLoadCanceled` and `onLoadError` ).
- The URl will be a new additional field in the `LoadEventInfo` parameter.

**Comment by tonihei** [comment]
Closing as the requested info is now part of the MediaSourceEventListener callbacks.
