### ISSUE TITLE
Forced subtitles for DASH

### ISSUE THREAD

**Issue by SoroushDMA** [google/ExoPlayer#2058]
So, I know the concept of forced subtitles are kinda new, i was wondering if Exoplayer 2 supports forced subtitles? If yes, how do we distinguish that from other Text TrackGroup?

Also, Is it possible to have both forced subtitle and subtitle at the same time?

P.S. I'm working with Widevine Dash files

**Comment by andrewlewis** [comment]
We support forced text tracks but only for HLS streams and Matroska files at the moment. (You can check [Format.selectionFlags](https://github.com/google/ExoPlayer/blob/94cc606/library/src/main/java/com/google/android/exoplayer2/Format.java#L169) in the TrackGroup's formats for [C.SELECTION_FLAG_FORCED](https://github.com/google/ExoPlayer/blob/94cc606091799b4a03593582528a600494979b15/library/src/main/java/com/google/android/exoplayer2/C.java#L202).)

However, it looks like we don't support forced subtitles for DASH. Could you give some details about how you want to signal forced subtitles, and/or provide some sample media? Thanks.

**Comment by ojw28** [comment]
- We also support specifying selection flags on side-loaded subtitles. The application is responsible for providing the `Format` in that case, and so can specify any desired flags.
- For DASH specifically, we could easily support a standard way of indicating forced subtitles in DASH manifests, were one to exist. I can't find such a feature in the DASH spec, however. If you're aware of one then please let us know, and we can look at adding support for it.
- We don't (easily) support both forced and non-forced subtitles being enabled simultaneously. I think that commonly, non-forced subtitles will also contain the forced subtitles as well, meaning you don't need to worry about enabling more than one track at once.

**Comment by SoroushDMA** [comment]
I'm thinking of defining our own `role`, maybe we can call it "forced". Having `forced` `role` plus the language tag gives us the uniqueness we need.

Here is an example of generated manifest file: (changed the file format from .mpd to .txt)
[presentation_forced.txt](https://github.com/google/ExoPlayer/files/596211/presentation_forced.txt)

**Comment by ojw28** [comment]
I think something like that would be the right approach. It feels like something that should be standardized properly though, if we're to officially support it. Is this something you could suggest to [DASH-IF](http://dashif.org/)?

**Comment by SoroushDMA** [comment]
Of course. I'll let you guys know about their response. 
Thank you

**Comment by ojw28** [comment]
If you do end up using your own custom element in the manifest, then it should be relatively straightforward for you to support it in ExoPlayer as follows:
1. Extend `DashManifestParser`. Let's say you call your extension `CustomDashManifestParser`. In this class, override whatever methods you need to override to parse the custom element or attribute, and set the flags on the text `Format` accordingly.
2. When creating a `DashMediaSource` instance to provide to the player, inject an instance of your `CustomDashManifestParser` through the constructor that allows you to do this*.

\* Such a constructor doesn't currently exist, but we'll push a change in a week or so that adds one ;).

**Comment by SoroushDMA** [comment]
Since `Role` is a standard element, I was thinking of doing a pull request to support `Role` in `DashManifestParser`. What do you think?

**Comment by ojw28** [comment]
You'd still need to extend the parser as well because you'll need to actually use the (non-standard) content of the element in the parser to set the appropriate flag on the `Format`. If you want to add some kind of hook for `Role` elements in `DashManifestParser`, so as to make the extension easier, then that sounds like a sensible idea.

**Comment by ojw28** [comment]
It's now possible to inject a custom parser, so the approach described above should be a viable solution for this issue. Feel free to send a pull request if additional flexibility is needed in `DashManifestParser`.

**Comment by ojw28** [comment]
FYI - We'll be pushing a change to `dev-v2` shortly that parses `Role` elements and sets `C.SELECTION_FLAG_DEFAULT` if the element looks like:
```
<Role schemeIdUri="urn:mpeg:dash:role:2011" value="main"/>
```
This is sufficient to cause the track to be selected by default by `DefaultTrackSelector`.

**Comment by SoroushDMA** [comment]
Cool, thanks for letting me know.

**Comment by SoroushDMA** [comment]
Do you know what the ETA for this change is going to be?

**Comment by ojw28** [comment]
The change is on `dev-v2` already, and is ref'd above. We don't have a good ETA of our next release as of now.

**Comment by SoroushDMA** [comment]
Thanks, I thought the changes are reflected in that branch's RELEASENOTES.md

**Comment by SoroushDMA** [comment]
I have a question, I need more flexibility on the `Role` tag, as in I need to read the `value` of the tag. In order to get that, I added a `roleValue` field to the `Format` class and made the proper changes. I can do a pull request for that, but just wanted to double check with you and make sure it is the right way of doing it.

**Comment by ojw28** [comment]
It would be helpful if you could explain exactly what it is you're trying to do from a functionality perspective (reading the value of the tag is the means by which you're trying to do it, but does not explain what it is you're trying to do or why). What are the possible values of the tag for your use case?

**Comment by SoroushDMA** [comment]
`main`, `alternate` or `forced` are some values we might put into it. The reason we need to read it is because what if a video content has more than one forced subtitle and more than one audio, so based on the changes on audio we need to change the forced subtitle. Some text tracks might not even have the `Role` tag.

**Comment by ojw28** [comment]
Why isn't `Format.selectionFlags` sufficient for this? Presumably "main" is SELECTION_FLAG_DEFAULT and "forced" is SELECTION_FLAG_FORCED. What does "alternate" mean, and is it just no flags (i.e. 0)?

**Comment by SoroushDMA** [comment]
We already have some contents that the `Role` field might not be one of the ones I just mentioned. I'm trying to expose the `value` to have more flexibility, since there is no standard for the `value` yet.

**Comment by ojw28** [comment]
I think you need to justify the need for flexibility with specific examples. If we were to just add extra flexibility everywhere in case it's useful, without understanding why, then everything would become very bloated and we'd have no way of knowing that we really made the right choices.

Without specific examples it remains unclear why selection flags are not sufficient. If there are a few specific extra flags you need, for example, then it's probably more suitable just to define some extra flags than it is to add a free-form string field. Well defined flags are also much clearer to handle for someone implementing a TrackSelector without necessarily knowing all the details of the MediaSource.

**Comment by SoroushDMA** [comment]
I think my problem stems from the fact that `Role` `value`s are not a standard yet, and that would result in contents to have different `value`s for `Role`.

I wanted to give the flexibility of handling different cases to the user (developer) by exposing the `Role` value, but making use of selection flags and adding extra flags seem like a better solution.
Thank you

**Comment by SoroushDMA** [comment]
I was looking at the DASH documentation and Media presentation description and segment formats which is in ISO/IEC 23009-1:2014 that you can find in the following link:
[ISO/IEC 23009](http://standards.iso.org/ittf/PubliclyAvailableStandards/index.html
)
In page 69 section 5.8.4.2, it defines the`Role` tag and in page 73 section 5.8.5.5, DASH `Role` scheme is defined along with 7 `Role` value in the table. As you can see in the definition of Role tag, one Adaptation Set or one media content component may have multiple roles even within the same scheme.

**Comment by ojw28** [comment]
You can OR multiple flags together to represent that. That's why they're flags rather than consecutive numbers ;).
