### ISSUE TITLE
 The dev-v2 lastest code HLS Live crash java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by crossle** [google/ExoPlayer#2059]
-                         E  java.lang.ArrayIndexOutOfBoundsException: length=12; index=-1
                         E      at java.util.ArrayList.get(ArrayList.java:310)
                         E      at java.util.Collections$UnmodifiableList.get(Collections.java:1054)
                         E      at com.google.android.exoplayer2.source.hls.playlist.HlsPlaylistTracker.adjustPlaylistTimestamps(HlsPlaylistTracker.java:312)
                         E      at com.google.android.exoplayer2.source.hls.playlist.HlsPlaylistTracker.access$800(HlsPlaylistTracker.java:38)
                         E      at com.google.android.exoplayer2.source.hls.playlist.HlsPlaylistTracker$MediaPlaylistBundle.processLoadedPlaylist(HlsPlaylistTracker.java:429)
                         E      at com.google.android.exoplayer2.source.hls.playlist.HlsPlaylistTracker$MediaPlaylistBundle.onLoadCompleted(HlsPlaylistTracker.java:396)
                         E      at com.google.android.exoplayer2.source.hls.playlist.HlsPlaylistTracker$MediaPlaylistBundle.onLoadCompleted(HlsPlaylistTracker.java:326)
                         E      at com.google.android.exoplayer2.upstream.Loader$LoadTask.handleMessage(Loader.java:355)
                         E      at android.os.Handler.dispatchMessage(Handler.java:102)
                         E      at android.os.Looper.loop(Looper.java:148)
                         E      at android.app.ActivityThread.main(ActivityThread.java:5417)
                         E      at java.lang.reflect.Method.invoke(Native Method)
                         E      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                         E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by crossle** [comment]
```
                     E  java.lang.NullPointerException: Attempt to read from field 'java.util.List com.google.android.exoplayer2.source.hls.playlist.HlsMasterPlaylist.variants' on a null object reference
                     E      at com.google.android.exoplayer2.source.hls.HlsMediaPeriod.buildAndPrepareSampleStreamWrappers(HlsMediaPeriod.java:276)
                     E      at com.google.android.exoplayer2.source.hls.HlsMediaPeriod.prepare(HlsMediaPeriod.java:93)
                     E      at com.google.android.exoplayer2.ExoPlayerImplInternal.updatePeriods(ExoPlayerImplInternal.java:1139)
                     E      at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:449)
                     E      at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:301)
                     E      at android.os.Handler.dispatchMessage(Handler.java:98)
                     E      at android.os.Looper.loop(Looper.java:148)
                     E      at android.os.HandlerThread.run(HandlerThread.java:61)
                     E      at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
```

**Comment by andrewlewis** [comment]
@crossle Please could you provide steps to reproduce this, including what media you were playing, in case it's needed to investigate further? Thanks.

**Comment by crossle** [comment]
Sorry, no reproduce step, only playbacking LIVE streaming,   randomly occurred, maybe network slow

**Comment by AquilesCanta** [comment]
Sorry for the delay on this. I think I have an idea of what the issue is. I will provide a fix which will reference this issue.
