### ISSUE TITLE
Interlaced Video is not Playing on Google-Pixel

### ISSUE THREAD

**Issue by ram992** [google/ExoPlayer#2060]
Hello, is there any known bug with exo-palyer about not being able to play an Interlaced Video.

I have checked on HTC 620 G (running android 4.4.2) on Vivo Max (running android 5.1.1)  
and on Google Pixel

The Video format : res: 1920 X 1080 an interlaced video with 5mbps video bit rate.
The player is playing on the two devices but not on pixel.

what I get is , the audio is playing but I cannot see any video. But when I am interacting with the player I am able to see the actual video till then No video appears on the player surface. once my interaction is done the surface is again blank

I am using your Demo App, hard coding the url's in the JSON list in the assets folder.

**Comment by andrewlewis** [comment]
I don't know of any specific issues around playing interlaced video on Pixel devices. We can take a look if you provide a URL to the problematic media.

**Comment by ojw28** [comment]
Closing due to lack of required information. See also #2013 which may be relevant.
