### ISSUE TITLE
seekTo is not working with SimpleExoPlayer

### ISSUE THREAD

**Issue by jdprajapati** [google/ExoPlayer#2061]
Hi,

MediaSource[] mediaSources = new MediaSource[3];
mediaSources[0] = buildMediaSource(Uri.parse(PlayUrl), null);
mediaSources[1] = buildMediaSource(Uri.parse(PlayUrl1), null);
mediaSources[2] = buildMediaSource(Uri.parse(PlayUrl2), null);

ConcatenatingMediaSource concatenatedSource =
                new ConcatenatingMediaSource(mediaSources[0], mediaSources[1], mediaSources[2]);

player.seekTo(0, 30000);
or 
player.seekTo(30000);

It will start from begining not the seek time.

Can you please help me for this problem.

Thanks in advance.

Please search the existing issues before filing a new one, including issues that
are closed. When filing a new issue please include all of the following, unless
you're certain that they're not useful for the particular issue being reported.

- A description of the issue.
- Steps describing how the issue can be reproduced, ideally in the ExoPlayer
  demo app.
- A link to content that reproduces the issue. If you don't wish to post it
  publicly, please submit the issue, then email the link to
  dev.exoplayer@gmail.com including the issue number in the subject line.
- The version of ExoPlayer being used.
- The device(s) and version(s) of Android on which the issue can be reproduced,
  and how easily it reproduces. If possible, please test on multiple devices and
  Android versions.
- A bug report taken from the device just after the issue occurs, attached as a
  file. A bug report can be captured using "adb bugreport". Output from "adb
  logcat" or a log snippet is not sufficient.

**Comment by andrewlewis** [comment]
Please provide the URLs you're trying to play and we will take a look. (Note that we don't support seeking in [some container formats](https://google.github.io/ExoPlayer/supported-formats.html#standalone-container-formats).)

**Comment by jdprajapati** [comment]
HI,

"file:///storage/emulated/0/IPTV/arynews_20160915_2046_155.ts"
I am using my local file ts file, its not working with local file.

**Comment by jdprajapati** [comment]
can you please give me solution as soon as possible because I am stuck here.
Thanks in advance

**Comment by andrewlewis** [comment]
We don't support seeking in MPEG-TS. You will need to use a different format if you require seeking (see the linked page in my previous comment).

See #966 for some more background on this.

**Comment by jdprajapati** [comment]
How's it possible?
If I am using m3u8 files then I am able to seek function and it work, why its not working with chunks.
Actually My chunks size is too much that's why I am using ExtractorMediaSource for play seemless play chunks.

Please give me solution its very important.

Thanks.

**Comment by andrewlewis** [comment]
Please read #966 for an explanation of why we support seeking with HLS and not plain MPEG-TS.
