### ISSUE TITLE
Subtitles with SingleSampleMediaSource

### ISSUE THREAD

**Issue by AndreasHohn** [google/ExoPlayer#2064]
Hello,

I created a videoplayer with ExoPlayer and now I want to display subtitles. Right now im stuck at the following lines:

```
MediaSource videoSource = new ExtractorMediaSource(video,dataSourceFactory, extractorsFactory, null, null);
MediaSource subtitleSource = new SingleSampleMediaSource(subtitleUri,dataSourceFactory,?,?);
// Plays the video with the sideloaded subtitle.
MergingMediaSource mergedSource = new MergingMediaSource(videoSource, subtitleSource);
// Prepare the player with the source.
mPlayer.prepare(videoSource);
```

I do not know what SingleSampleMediaSource needs as a Format and duration (both question marks)? The subtitles will be .srt files. Has somebody an example or can explain it to me?

**Comment by ram992** [comment]
Hello @AndreasHohn please refer closed issue #2017

**Comment by ram992** [comment]
You need to use subtitle view to display the subtitles

**Comment by AndreasHohn** [comment]
Thank you for the link. So you have an example for using subtitle view?

**Comment by andrewlewis** [comment]
You can use SimpleExoPlayerView as a starting point/example (see https://github.com/google/ExoPlayer/issues/2017#issuecomment-259633365).
