### ISSUE TITLE
mp4 video with audio stream type mp3 is played without sound

### ISSUE THREAD

**Issue by vishnuganta22** [google/ExoPlayer#2066]

**Comment by vishnuganta22** [comment]
Video:
Dimensions: 1920*1080
Codec:H.264
Framerate: 24 frames per second

Audio:
Codec: MPEG-1 Layer 3(MP3)
Channels:Stereo
Sample rate: 44100Hz

**Comment by vishnuganta22** [comment]
version : exoplayer:r2.0.4

**Comment by vishnuganta22** [comment]
Device: Nexus 10
Android version: 5.1.1

**Comment by vishnuganta22** [comment]
Sent the video file to email(dev.exoplayer@gmail.com)

**Comment by andrewlewis** [comment]
The audio track has a `.mp3` box in the `stsd` which we don't currently handle. The code is specified for [Quicktime](https://developer.apple.com/library/mac/documentation/QuickTime/QTFF/QTFFChap3/qtff3.html#//apple_ref/doc/uid/TP40000939-CH205-BBCGEBEH) and it looks there is also an alternative way to signal it using an [ObjectTypeIndication](http://mp4ra.org/object.html).

**Comment by vishnuganta22** [comment]
@andrewlewis can we expect any estimated time for beta-version of exo-player with the above enhancement.We are waiting for it.

**Comment by andrewlewis** [comment]
@vishnuganta22 I don't have a concrete ETA for this yet, but the (unreviewed) patch is very simple:
1. Add `TYPE__mp3 = Util.getIntegerCodeForString(".mp3");` in [Atom.java](https://github.com/google/ExoPlayer/blob/d922a21/library/src/main/java/com/google/android/exoplayer2/extractor/mp4/Atom.java).
2. Add a check for `|| childAtomType == Atom.TYPE__mp3` in [AtomParsers.java](https://github.com/google/ExoPlayer/blob/d922a21/library/src/main/java/com/google/android/exoplayer2/extractor/mp4/AtomParsers.java#L630).
3. Set the MIME type in [parseAudioSampleEntry](https://github.com/google/ExoPlayer/blob/d922a21/library/src/main/java/com/google/android/exoplayer2/extractor/mp4/AtomParsers.java#L859): `else if (atomType == Atom.TYPE__mp3) { mimeType = MimeTypes.AUDIO_MPEG; }`.

**Comment by vishnuganta22** [comment]
@andrewlewis thanks for your comment.
after changing the code as you mentioned it is working.

**Comment by vishnuganta22** [comment]
@andrewlewis i can't able to able to push my changes to this repo.
getting access denied

**Comment by vishnuganta22** [comment]
Want to create a PR with my changes

**Comment by andrewlewis** [comment]
Thanks for the pull request, but we have already submitted this change internally. The feature should be available next time we push to `dev-v2`.

**Comment by ojw28** [comment]
This should be fixed in `dev-v1` and `dev-v2`.
