### ISSUE TITLE
how to set the screenOrientation play

### ISSUE THREAD

**Issue by helinfeng** [google/ExoPlayer#2075]
my video is portrait Recording , my video file is portrait,but the player always horizontal when i was play my video, i want know how to set the screenOrientation portrait !thanks

**Comment by ojw28** [comment]
There's quite a lot of information about portrait videos and rotation in https://github.com/google/ExoPlayer/issues/91. Have you read through that thread? If so and if that doesn't answer your question, you'll need to provide more information (as explicitly listed in the issue template) for us to help.

**Comment by helinfeng** [comment]
the same to #91 and i was use the SurfaceView! T_T
