### ISSUE TITLE
how do I use M2tsExtrator for exoplayer2

### ISSUE THREAD

**Issue by codesunshine** [google/ExoPlayer#2076]
Please search the existing issues before filing a new one, including issues that
are closed. When filing a new issue please include all of the following, unless
you're certain that they're not useful for the particular issue being reported.

- A description of the issue.
- Steps describing how the issue can be reproduced, ideally in the ExoPlayer
  demo app.
- A link to content that reproduces the issue. If you don't wish to post it
  publicly, please submit the issue, then email the link to
  dev.exoplayer@gmail.com including the issue number in the subject line.
- The version of ExoPlayer being used.
- The device(s) and version(s) of Android on which the issue can be reproduced,
  and how easily it reproduces. If possible, please test on multiple devices and
  Android versions.
- A bug report taken from the device just after the issue occurs, attached as a
  file. A bug report can be captured using "adb bugreport". Output from "adb
  logcat" or a log snippet is not sufficient.

**Comment by Avetri** [comment]
Is your issue related to the issue #1488 ?

**Comment by AquilesCanta** [comment]
You can have a look at the Demo App to see how to instance a ExtractorMediaSource. Unfortunately, the issue tracker is not intended to be used for general general Q&A. If you are not able to play your media in the demo app (as Avetri says, #1488 is possibly related) you will need to provide all the information requested in the issue template. Make sure you don't create a duplicate, please.
