### ISSUE TITLE
Capabilities: Video not playing (plays fine in V1)

### ISSUE THREAD

**Issue by cristin** [google/ExoPlayer#2078]
Hi! I recently updated to exoplayer 2 on an app that we are working and have an issue when playing mp4 video files encoded (h264 profile 10) on iOS. Only the audio plays and no video. I saw that exoplayer 1 doesn't had this problem. Do you know what's the issue and how did you solved it? Thank you!

**Comment by AquilesCanta** [comment]
Could you please provide the mentioned file? If you don't want to post it here, you can send it to dev.exoplayer@gmail.com.

**Comment by cristin** [comment]
I emailed you a test video.

**Comment by ojw28** [comment]
The test video plays fine on devices I have, so this is likely a device specific capability issue (i.e. the same issue as #2034). I'll leave this issue open for now and follow up when we have more logging in place so that we can capture logging from your test device and use it to put a workaround in place.

**Comment by Andoctorey** [comment]
The same for me, iphone created video doesn't work on any device I have in v2 - https://res.cloudinary.com/aparlay/video/upload/vc_h264/eo_60/trssyxllsem4xqueocwv.mp4

**Comment by ojw28** [comment]
Please could you:
1. Check out the latest `dev-v2` code.
2. Try and play the affected video.
3. Paste the output of `adb logcat -s "MediaCodecInfo"` here. You should see a bunch of lines containing "FalseCheck" the detail exactly why the stream wasn't played.

Thanks!

**Comment by Andoctorey** [comment]
Tried to play https://res.cloudinary.com/aparlay/video/upload/vc_h264/eo_60/trssyxllsem4xqueocwv.mp4 on the latest dev-v2 code -  no `MediaCodecInfo` log, please check https://gist.github.com/Andoctorey/0ccb12dfab7e755881b27a464a93b693

**Comment by ojw28** [comment]
@Andoctorey - You need to test with the very latest `dev-v2` code to see the logging. The output you've suggests you're using a slightly older version.

**Comment by Andoctorey** [comment]
Sorry, on emulator I have - `FalseCheck [size.support, 720x1280] [OMX.google.h264.decoder, video/avc] [generic_x86_64, Android SDK built for x86_64, unknown, 23]`

**Comment by ojw28** [comment]
For vertical videos, which both videos in this issue are, this should be resolved by: https://github.com/google/ExoPlayer/commit/2e3ffe1e94a16d6ca1e5c09f818969cbcd531abe

Marking as fixed. Please let us know if you still see the issue on the very latest `dev-v2` branch. Thanks.
