### ISSUE TITLE
Exoplayer with widevine asset: IllegalArgumentException

### ISSUE THREAD

**Issue by jorgevila** [google/ExoPlayer#2080]
with a Widevine asset encoded by us, we are getting this exception: IllegalArgumentException from native.

```
  ExoPlayerImplInternal  E  Internal runtime error.
                         E  java.lang.IllegalArgumentException
                         E      at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
                         E      at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:2478)
                         E      at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:653)
                         E      at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:479)
                         E      at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:432)
```

The inputs to MediacodecRenderer.queueSecureInputBuffer method are:
     MediaCodecRenderer  D  [feedInputBuffer.queueSecureInputBuffer] inputindex =2, offset=0, cryptoinfo = [2 subsamples, key [5b424034396635666437], iv [c6123054797a5db00000]
                            , clear [5, 5], encrypted [1, 75]], presentationTimeUs = 0, flags=0

Any clue which value could be illegal or how to debug it?
Thank you.

**Comment by ojw28** [comment]
Closing because insufficient information was provided. Please file a new issue containing all of the information requested in the issue template if you want us to investigate further.
