### ISSUE TITLE
Playing parts of videos when playing a sequence of videos

### ISSUE THREAD

**Issue by alexshelepov** [google/ExoPlayer#2082]
Hi!

I've implemented code that play sequence of mp4 videos from device sdcard using ConcatenatingMediaSource. Now it plays video1, video2. If video1 duration is 10 sec and video2 duration is 12 sec then player play video1 from 0:00 to 0:10 and then video2 from 0:00 to 0:12 so "playlist" duration is 22 sec.

I want to play only parts of videos eg 6 sec from video1 (from 0:02 to 0:08) and then 2 sec from video2 (from 0:03 to 0:05) so "playlist" duration should be 8 sec. 

What is the best way to implement it? Should I implement MediaSource interface? Or I can only observe progress and seek player?

- The version of ExoPlayer being used.
r2.0.4

**Comment by andrewlewis** [comment]
This enhancement is the same as #1988.
