### ISSUE TITLE
Question: not able to modify bytebuffer in handleBuffer() function of AudioTrack.java

### ISSUE THREAD

**Issue by Kexiliu** [google/ExoPlayer#2084]
In handleBuffer() function, if (isNewSourceBuffer==true) && (sdk<21), bytebuffer is converted to bytearray and write to AudioTrack. I'm able to modify that bytearray without problem. But if (sdk>=21) &&  (isNewSourceBuffer==true) if I add

```
      if (Util.SDK_INT < 21) {
        // Copy {@code buffer} into {@code temporaryBuffer}.
        int bytesRemaining = buffer.remaining();
        if (temporaryBuffer == null || temporaryBuffer.length < bytesRemaining) {
          temporaryBuffer = new byte[bytesRemaining];
        }
        int originalPosition = buffer.position();
        buffer.get(temporaryBuffer, 0, bytesRemaining);
        buffer.position(originalPosition);
        temporaryBufferOffset = 0;
      }
      else
      {
        //this is what i added
        ByteBuffer bb = ByteBuffer.allocateDirect(buffer.capacity());
        bb.limit(buffer.limit());
        for (int i = buffer.position(); i < buffer.remaining(); i++)
        {
          bb.put(buffer.get(i));
        }
        buffer = bb;
        buffer.position(0);
      }
```
I should be able to hear the original sound, but i'm hearing lots of noises and "Discontinuity detected [expected 4626000, got 4411000]" is shown in log, the video is also slower. Also tried couple other ways, as soon as i change the bytebuffer, the audio will be very weird.

**Comment by andrewlewis** [comment]
See the documentation for handleBuffer. The method may partially consume the buffer that is passed in, in which case the same buffer will be passed on the next call to continue writing it. Then isNewSourceBuffer will be false, so the passed in buffer will be used (not your replacement buffer).

In this specific case, it looks like your added code will advance the position of the input buffer to the end, so no bytes will by written on the second call, even if it your replacement buffer was only partially consumed on the first call.

**Comment by Kexiliu** [comment]
Thanks for your answer!
