### ISSUE TITLE
How to catch OnPrepared event.

### ISSUE THREAD

**Issue by lipangit** [google/ExoPlayer#2087]
If simpleExoPlayer.setPlayWhenReady(false);

How to catch OnPrepared event, getPlaybackState() is not initiative.

**Comment by ojw28** [comment]
It's unclear what this question is asking. ExoPlayer doesn't have an event called `OnPrepared`. ExoPlayer V2 doesn't even have the concept of a preparing state. In general, it's unclear what "preparing" actually means. It might be clearer if you instead phrase your question in terms of exactly what you're trying to achieve. Thanks!

**Comment by lipangit** [comment]
player.prepare(.. , .. , ..);   will loading video.

I want to know when the video is prepared, start play right away.

**Comment by ojw28** [comment]
You should [add a listener](http://google.github.io/ExoPlayer/doc/reference-v1/com/google/android/exoplayer/ExoPlayer.html#addListener-com.google.android.exoplayer.ExoPlayer.Listener-). Its [onPlayerStateChanged](http://google.github.io/ExoPlayer/doc/reference-v1/com/google/android/exoplayer/ExoPlayer.Listener.html#onPlayerStateChanged-boolean-int-) will be invoked when a state change occurs.

Note that if all you're trying to do is start playback as soon as possible, there's no need for you to wait until preparation happens for you to tell the player that you want it to start playback. Just call `setPlayWhenReady(true)` straight away, and it'll start playing as soon as possible.

**Comment by lipangit** [comment]
Yes , but 
```
    @Override
  public void onPlayerStateChanged(boolean playWhenReady, int playbackState) {
    if(playbackState == ExoPlayer.STATE_READY){
       // this is not accurate
    }
  }
```

playbackState == ExoPlayer.STATE_READY  is not accurate, I just want to know just prepared after preparing, if pause video and go on play video  will also get there.

**Comment by ojw28** [comment]
If you really need to do this, it seems pretty easy for you to track whether you're preparing or not. Why can't you just do something like:

```
boolean isPreparing;
...
isPreparing = true;
player.prepare(...);
...
```

```
@Override
public void onPlayerStateChanged(boolean playWhenReady, int playbackState) {
  if(isPreparing && playbackState == ExoPlayer.STATE_READY){
     // this is accurate
     isPreparing = false;
  }
}
```

It's still unclear why you need this in the first place. What do you actually want to _do_ when you see that the player has been prepared?

**Comment by lipangit** [comment]
Preparing and playing UI is not same, I want know when change ui from preparing to playing .

Thank you, that code is what I need.
