### ISSUE TITLE
Help me define DASH stream URL

### ISSUE THREAD

**Issue by dreich** [google/ExoPlayer#2088]
Hello, dear developer of ExoPlayer!

Would you be so kind to help me extract valid URL of DASH stream for playing in ExoPlayer?
Go to [http://tsargrad.tv/broadcast](http://tsargrad.tv/broadcast).
Using F12 (network profiler) I see .manifest, .hdr, .idx requests, but not .mpd.
What URL should I take?

Thanks.

**Comment by ojw28** [comment]
Reverse engineering websites to extract content URLs is not in the scope of this issue tracker.
