### ISSUE TITLE
Support HLS with Widevine

### ISSUE THREAD

**Issue by noamtamim** [google/ExoPlayer#2089]
Since October, Chromecast supports HLS with Widevine. ExoPlayer should also support that profile.

Does this require transmuxing and/or a change to MediaDRM/MediaCrypto/MediaCodec?

**Comment by ojw28** [comment]
Changes to support this were added underneath `MediaDrm` in Android Nougat. We also need to make some changes in ExoPlayer on top of that.

**Comment by noamtamim** [comment]
Does this mean that even when you add support in ExoPlayer, it will only apply to Nougat and up?

Without the changes to `MediaDrm`, is it possible to implement it using transmuxing? Widevine on iOS is doing something similar, in the opposite direction -- transmuxing DASH chunks to HLS TS chunks.

**Comment by ojw28** [comment]
> Does this mean that even when you add support in ExoPlayer, it will only apply to Nougat and up?

Yes, which is partly why we're not prioritising this work right now. Widevine would need to provide a standalone library for Android to get this working on older versions of Android, which they don't do currently. Note that even if they were to do this, it would likely only be L3 security, which may or may not be acceptable for your use case.

> Without the changes to MediaDrm, is it possible to implement it using transmuxing? Widevine on iOS is doing something similar, in the opposite direction -- transmuxing DASH chunks to HLS TS chunks.

What you refer to as transmuxing must presumably include decryption. So the same answer as above applies; Widevine would need to provide a library for this to be supported.

DASH/FMP4/CENC (in "cenc" mode) is the recommended approach for delivering protected content to Android devices.

**Comment by noamtamim** [comment]
Understood. What if we're doing HLS **with fMP4** instead of TS? Presumably the lower-level details are the same as DASH.

**Comment by ojw28** [comment]
Unfortunately Apple mandated use of the `cbcs` CENC scheme for fMP4 in the HLS RFC. Support for `cbcs` was also only added in Nougat. Prior to Nougat the `cenc` CENC scheme is the only one supported.

**Comment by noamtamim** [comment]
I have my own packager, which I can configure to generate HLS with fMP4/CENC (effectively, producing m3u8 playlists instead of MPD files). 
How much effort would it be to support that in ExoPlayer? 
Obviously that would deviate from the standard, so official ExoPlayer will not support it.

EDIT: encoder->packager.

**Comment by ojw28** [comment]
The work to support HLS/WV/CENC(cbcs scheme) and HLS/WV/CENC(cenc scheme) is probably more or less the same, with some small caveat around propagating the right scheme information. However this work is not a priority for us at the moment because the standard compliant cbcs scheme is only going to work from Nougat.

More generally, why would HLS/WV/CENC(cenc scheme) be a sensible thing to do? Such streams presumably wont work on iOS devices. If the streams you're generating are for Android devices only, you should really just generate an MPD instead. Choosing to attempt HLS/WV/CENC(cenc scheme) is attempting to use a worse, less well supported and non-standard-compliant approach that's pretty much equivalent to DASH anyway; why would you not just use DASH at that point ;)?

**Comment by kidmiracleman** [comment]
@ojw28   - what about the indication that patents are now about to be asserted around the use of DASH MPD's   - which means MPEG-LA will want to extract royalties for the use of ExoPlayer to support DASH streaming..    Does this make HLS/WV/CENC(cenc scheme) more viable  (and hence higher priority)?

**Comment by ojw28** [comment]
We are unable to provide legal advice on this issue tracker. You need to obtain your (e.g. region specific) advice. It's completely unrelated to the viability of an unrelated feature, in any case. We have no plans to change priorities, either.

**Comment by sivarajendranaidu** [comment]
Does ExoPlayer support DASH CBCS on devices running API level 24 (i.e. Nougat) [nexus players ]?
Please provide your inputs

**Comment by noamtamim** [comment]
@sivarajendranaidu it doesn't yet (but this ticket tracks it). As you can see in @ojw28's comment, this is a low priority task -- specifically because it only applies to level 24 and up (1.2% of the market).

**Comment by sargeway** [comment]
I had a question similar to @noamtamim. I understand HLS+fMP4+CBCS+Widevine is supported in Nougat+ (i.e. Android 7.x & 8.x), however, what's the minimum Android + ExoPlayer version that will support HLS+fMP4+CENC(CTR)+Widevine? The 2.6.0 release notes (https://github.com/google/ExoPlayer/blob/dev-v2/RELEASENOTES.md) state HLS support was updated to include "Support for Widevine protected FMP4 variants", however the Supported Devices page does not list HLS+Widevine support at all (https://google.github.io/ExoPlayer/supported-devices.html). Furthermore, the Supported Formats page (https://google.github.io/ExoPlayer/supported-formats.html) states that Widevine is not supported in HLS but is planned for API 24+. 

So while the 2.6.0 release notes do not provide specific Android version support, they seem to contradict the Supported Devices and Formats pages. Can you shed more light on what's actually supported wrt HLS+Widevine (CENC vs. CBCS) in ExoPlayer 2.6.0?

TIA.

**Comment by noamtamim** [comment]
@ojw28 @AquilesCanta is this issue implemented? It's not marked closed, but as mentioned above, the release notes for 2.6.0 say "HLS: Support for Widevine protected FMP4 variants" -- presumably this is this ticket.

I'm asking because we have now implemented HLS+fMP4+Widevine in our packager, and the test stream doesn't work on ExoPlayer (but does work on Shaka).

**Comment by AquilesCanta** [comment]
It should work, yes. Would you kindly send us a link to dev.exoplayer@gmail.com?

**Comment by noamtamim** [comment]
The test stream is using "regular" cenc, not cbcs. Should it work as well?

**Comment by noamtamim** [comment]
I checked and there was a glitch in the test stream when I tested. It works now.
Shouldn't this ticket be closed?

**Comment by sargeway** [comment]
Please don’t close this ticket without updating/syncing the docs and providing feedback: Can you shed more light on what's actually supported wrt HLS+Widevine (CENC vs. CBCS) in ExoPlayer 2.6.0?

**Comment by ojw28** [comment]
The supported formats page has been updated already. We'll expand the supported devices page shortly.

**Comment by ojw28** [comment]
Both pages are now updated.
