### ISSUE TITLE
Support AVI

### ISSUE THREAD

**Issue by bene25** [google/ExoPlayer#2092]
Is it possible to play .avi format on ExoPlayer 2.0.
Due to FrameworkSampleSource are removed, are there any other way to play it?

**Comment by ojw28** [comment]
No, this is not supported in V2. Someone would have to implement an ExoPlayer AVI extractor. It's unclear there's really any significant demand for it, however.

**Comment by lodup29** [comment]
I would also like to see an ExoPlayer avi extractor implemented.

**Comment by nero12** [comment]
Same here, i would love to see .avi extractor, nothing out there ?

**Comment by dirondir** [comment]
I would be happy to see .avi extractor

**Comment by Aditya94A** [comment]
Any updates on this? This should be bumped up.

The fact that AVI format is horribly outdated and nobody should use it is not going to deter our simple minded users! ~7% of the files that my users try to play every day are AVI. With 20k DAU, this is insane. I get at least one 1-star review everyday specifically about this.

**Comment by danyangwu** [comment]
I would also like to see an ExoPlayer avi extractor implemented.

**Comment by Pecana** [comment]
Yes , please add support for this kind of format :-)

**Comment by mytvpro** [comment]
i believe there is in fact significant demand for this

> No, this is not supported in V2. Someone would have to implement an ExoPlayer AVI extractor. It's unclear there's really any significant demand for it, however.

**Comment by mytvpro** [comment]
many older video files still use .avi need to turn to other players to view them. .avi was once very widely used and still very much in circulation i'm not sure why it's not higher priority

**Comment by PriyankaThakkar612** [comment]
Please add support for .avi extractor. We would love to see that.

**Comment by AshishPsaini** [comment]
We are getting 1 star from users for these videos formats. Please provide the support for avi, flv, wmv and mpg formats.

**Comment by mdtuyen** [comment]
@AshishPsaini Don't use exoplayer, there are too many errors in this library, even worse than the videoview

**Comment by AshishPsaini** [comment]
> @AshishPsaini Don't use exoplayer, there are too many errors in this library, even worse than the videoview

Please help me which player I should use in my app.

**Comment by mdtuyen** [comment]
@AdityaAnand1 ijkplayer is better

**Comment by AshishPsaini** [comment]
> @AdityaAnand1 ijkplayer is better

Thanks. Please share your email id or connect with me on ashishpsaini@gmail.com on hangout.

**Comment by HaiderSaleem** [comment]
Still neither avi nor wmv support is added.

**Comment by otopba** [comment]
Also waiting for avi support

**Comment by Raykud** [comment]
if they didn't care to add it in the last 4 years, and even marked it as "low priority" (2 years ago) there is ZERO chances they will implement an avi extractor. I say this as I know how google works 🙃 .

**Comment by dburckh** [comment]
> No, this is not supported in V2. Someone would have to implement an ExoPlayer AVI extractor. It's unclear there's really any significant demand for it, however.

Although it is not commonly used for streaming, it is still very common in trail cams, lower end dash cams and drones.  I don't know how many people I've told to install VLC over the years.

**Comment by mytvpro** [comment]
It's very common in archived video. Everything older is avi.

**Comment by barbuslex** [comment]
+1 need support for AVI and DivX/XVID format

**Comment by LukasThijs** [comment]
We still need .avi support why is this being ignored

**Comment by mytvpro** [comment]
> We still need .avi support why is this being ignored

Because they think no one needs it even though we all keep saying we do

**Comment by ojw28** [comment]
To clarify, we do understand there's some demand and value to implementing this. As is the case with most widely used open source projects, we receive far more requests than we're able to handle, and we need to prioritize what we work on fairly ruthlessly. This feature is not important enough for us to work on at this point in time.

We accept open source contributions, and would accept a high quality pull request that adds an AVI extractor. ExoPlayer is also extensible enough such that you could implement an AVI extractor and inject it into the player from your own codebase. In other words, the direct development team are not the _only_ group of people who could add support for this.

**Comment by dburckh** [comment]
I'll have some time this summer to work on it.  I have a lot of experience
with different containers and I've read the AVI and OpenDML spec.  Based on
my personal library, it looks like the primary codecs are MJPEG/PCM and
H263 (xvid) and AC3.  Both combos have challenges with ExoPlayer/stock
Android.  There are also a ton of trail cams out there that still use AVI.
I'm not sure what they are using.  My neighbor has one, I'll get some
samples...

**Comment by Pentaphon** [comment]
> We still need .avi support why is this being ignored

.avi has been largely replaced by .mp4, webm, and even more-so mkv so it makes sense that the devs don't really care about that container anymore. It's up to the community to submit a PR and it has to happen sooner than later because the more time passes, the less people are interested in working on it.

**Comment by D00mch** [comment]
@dburckh , how is it going?

**Comment by wubi517** [comment]
I am still waiting avi extractor.

**Comment by emouawad** [comment]
Please add AVI support

**Comment by kurthuwig** [comment]
Regarding: "AVI will go away and be replaced by MP4": the MP4 container is from the MPEG consortium and only supports MPEG streams. This means that you cannot get other streams in it without conversion. E.g. H.263 video + PCM audio does not work. But that's what most network cameras offer.

**Comment by dburckh** [comment]
My repo with support AVI is available to clone and test out.  I've added an option to Misc in the demo to pick any user file off the device.

What is working:
- Video: H264, MJPEG, XVID (MPEG-4) - Note: MPEG-4 is supported on all devices, but on my Pixel 3a it's only supported at low resolution.
- Audio: MP3, PCM, AAC.  AC3 and DTS should work, are not generally supported by Android.  Might work on Android TV

Not working:
- Video: MP42 (not supported on Android)

Not supported yet:
- OpenDML - Not supported.  Maybe in the future.

https://github.com/dburckh/ExoPlayer

If you find an issue, you can report it and I'll try to fix it.  Please have a link available so I can download the file.

**Comment by dburckh** [comment]
Just added MJPEG support updated prior comment.  Going to start writing tests!

**Comment by moneytoo** [comment]
@dburckh Amazing work! Could you please enable _Issues_ section in your GitHub fork so we can discuss issues there? I still need to verify some exception I got but I don't want to spam this thread. Thank you once again!

**Comment by dburckh** [comment]
Done.  Make sure you get me a link to a sample.

**Comment by kurthuwig** [comment]
Great work! I know two guys that work on an AVI extractor, too. I've sent them a link to your repo. They have some issues but got a very good understanding of the AVI format, so I assume working together would speed things up a lot.

**Comment by dburckh** [comment]
So, the only things I have left on my TODO list are tests and maybe openDML.  If there are feature requests or bugs, let me know.  I suspect there will be some FourCC variants that I don't have, but those are a quick fix (@moneytoo already found one).

**Comment by dburckh** [comment]
There is a PR up for the ExoPlayer team now.  I assume they will request some changes, but hopefully they will accept it in one form or another.  

FYI:  I changed the branch to "avi"

**Comment by dburckh** [comment]
Google asked me to just put the AVI changes in my first PR, so moved the MJPEG and Demo changes into a branch called "everything" and made it default.

**Comment by ojw28** [comment]
@AquilesCanta has been looking at adding AVI support, and can probably provide an update here.

**Comment by AquilesCanta** [comment]
Initial support is ready and will be released soon. But as explained in https://github.com/google/ExoPlayer/pull/9915, support is incomplete and we'll need support from the community to report (and ideally send PRs for) any issues you encounter. 

For those, please file fresh issues.

EDIT: AVI support exists in the dev branch.
