### ISSUE TITLE
Support offlining DRM keys

### ISSUE THREAD

**Issue by ram992** [google/ExoPlayer#2094]
Hello, I have implemented offline DRM management, by creating an offlineDrm SessionManager from streamingDrm SessionManager. I am sorting keys and then restoring them with mediaDrm.restoreKeys

But my implementation works fine if I am doing it with single file at a time.

Like creating DRM session fetching keys, storing them. Then in the offline mode I will just pick the keys
And start playback.

My question is is there any way to download the keys store keysetID for them before downloading the actual video and storing all in a single folder.

I have tried it but every time I try to play offline the player give me a DRM session exception

Can you tell me if there is any need to create player instance when downloading keys.

**Comment by ojw28** [comment]
There's no real need to create a player to obtain offline DRM keys, but the implementation for actually doing this isn't trivial. It's something we intend to support in the future. Marking this as an enhancement.

**Comment by ojw28** [comment]
Actually, this is already tracked by #876. Closing this one.
