### ISSUE TITLE
Play in-progress MPEG-TS

### ISSUE THREAD

**Issue by fougere-mike** [google/ExoPlayer#2095]
ExoPlayer Version: ExoPlayer2 ([dev-v2](https://github.com/google/ExoPlayer/tree/dev-v2))
Test Device: NVIDIA Shield (android tv)

I'm attempting to play h.262 video embedded in an mpeg-ts container (on an NVIDIA Shield). Normal playback works correctly, but the catch is that I need to be able to grow the file during playback. Currently, it seems if I append more data to the file during playback ExoPlayer will ignore it. 

From what I can tell, the player seems to be checking the file length only once, during initialisation. This explains why it doesn't play the appended video. 

Is it possible to have ExoPlayer re-check the file length periodically? If so, could someone point me in the right direction?

**Comment by ojw28** [comment]
This is not something we'll be supporting. It doesn't seem appropriate to be writing to the file simultaneously whilst it's being read. What should the player do if it gets to the "end" of the file, given it has no way of knowing whether you'll append more data to it, for example?

If you really need to do this you should write a custom `DataSource` implementation that's capable of handling this case, and with the assumptions programmed in that you want to hold. You can use `FileDataSource` as a starting point, so it's probably not that much work.

**Comment by fougere-mike** [comment]
Ok, thanks I'll give that a shot. Is `DataSource` the only component which is aware of the file's length? It seems like `DataSpec` also has a notion of `length`. Would it be appropriate to simply set the `DataSpec`'s length to `C.LENGTH_UNSET` in this case?

**Comment by ojw28** [comment]
The `DataSpec`'s length is probably already unset for this use case. The way the rest of the player finds out about the actual length of the data is through the value returned from `DataSource.open`, so you need to make sure you return unset from your `open` implementation rather than the length of the file, which is what `FileDataSource` returns.

**Comment by fougere-mike** [comment]
Perfect, thank you. Also thanks for the quick responses!
