### ISSUE TITLE
Seeking MPEG2-TS

### ISSUE THREAD

**Issue by fougere-mike** [google/ExoPlayer#2098]
I've just discovered that mpeg2-ts is [not seekable](https://github.com/google/ExoPlayer/blob/dev-v2/library/src/main/java/com/google/android/exoplayer2/source/ExtractorMediaSource.java#L41). 

I'm not sure why that's the case. Are there plans to add seeking for mpeg-ts in the future? If not, could someone give me some info on how I might approach adding support myself?

Cheers.

**Comment by ojw28** [comment]
Please see https://google.github.io/ExoPlayer/supported-formats.html. If you were to do this yourself, you'd probably need to implement some kind of binary search into the media until you find the seek position.

**Comment by fougere-mike** [comment]
Understood, thanks.

**Comment by chenxi2035** [comment]
Hi,ojw28，I encountered the same problem,have you got a solution? Thank you in advance.
