### ISSUE TITLE
How to detect HLS video is for Live, VOD or Event in Exoplayer android

### ISSUE THREAD

**Issue by londhenamdev** [google/ExoPlayer#2099]
I have integrated android exoplayer in my application. I have to detect the HLS (.m3u8) stream received is for Live or VOD or Event, so depending on that controller has to be modified for the player. I have only one instance of player so that should handle all the supported media like vod or live or event.
I am looking for some debug points to know working of m3u8 parser in exoplayer so that I can able to receive this parameters.

**Comment by AquilesCanta** [comment]
Live vs Event differentiation is not supported, yet. For Live vs Event you can check the current Timeline, but that's not HLS specific.

For playlist type support you can track #805.

**Comment by gvader** [comment]
I've checked commits referenced in #805 but was unable to determine a correct way to check content type. Unable to access Playlist object from HlsMediaSource in none of high level component APIs. Could you provide any example how to do that?

**Comment by AquilesCanta** [comment]
Have a look at the `onTimelineChanged` callback (`Exoplayer.EventListener`). The second argument recieved should be an instance of HlsMediaPlaylist. There you can look at the `playlistType`.

**Comment by gvader** [comment]
I found `isCurrentWindowDynamic()` in `SimpleExoPlayer` class. It did the job for me, but the documentation was little unclear. Would be good to add some reference with better description about this Window/Period convention. And whole description of relation window and period size/number with playback type would be nice too.
