### ISSUE TITLE
AAC licensing question

### ISSUE THREAD

**Issue by setfire2** [google/ExoPlayer#2103]
Hello everybody,

I developed a streaming radio app for Android:
https://play.google.com/store/apps/details?id=de.hanosoft.droidio

Currently, I only allow it to play MP3 streams because I am concerned about licensing issues with AAC streams. ExoPlayer plays the AAC streams just fine. But do I have to pay license fees to the Via Corp?
http://www.via-corp.com/licensing/aac/licensefees.html

I explained the circumstances to them but I only recieved the answer, I have to pay the fees for every device or program that acts as an AAC decoder.

Looking at
https://developer.android.com/guide/appendix/media-formats.html#core
it seems that Android can decode AAC by default. So it's not my app or ExoPlayer that delivers the decoder, right? Does Google or do the device manufacturers pay these fees already?

Thanks in advance,
Soeren

**Comment by ojw28** [comment]
We're not able to provide legal advice. I can however state some facts that may assist you, which are accurate as of the time of writing:

- The core ExoPlayer library does not contain an AAC decoder. It calls into Android's `MediaCodec` API to access a decoder provided by the underlying OS. Including the core ExoPlayer library does not result in your application binary containing an AAC decoder.
- Building and including some of the ExoPlayer extensions, for example the [FFmpeg extension](https://github.com/google/ExoPlayer/tree/release-v2/extensions/ffmpeg), may result in decoders being included in your application binary.

**Comment by setfire2** [comment]
Okay thanks. This is what I expected.
