### ISSUE TITLE
Is Exoplayer a solution for bug in Android media player that causes dropped audio?

### ISSUE THREAD

**Issue by boywithk9** [google/ExoPlayer#2109]
We have an app that plays 3 simultaneous audio tracks using the native Android mediaplayer. From time to time, we receive reports from users that one or two of the tracks drop or fail to play. No error appears in the event logs. In most cases, restarting the device fixes the issue, but some users report being unable to correct the issue by any means (restarting, deleting/reinstalling app). 

Is this potentially an issue that would be corrected by using Exoplayer instead?

**Comment by ojw28** [comment]
Without any information about the underlying cause of the issue to which you refer, it's impossible to say. Sorry!
