### ISSUE TITLE
Update documentation to configure Android Studio with github sources

### ISSUE THREAD

**Issue by danrossi** [google/ExoPlayer#2110]
I'm trying to use github sources in an external project. Trying to customise the demo application within those same sources causes conflict issues. I require the dev-v2 branch for trialing the changes in the cache features to see if it will do the offline downloading properly. 

I see no documentation how to do this, only include the release files ?

**Comment by danrossi** [comment]
After a mountain of failed researching. this is the best thing that I could come up with that wouldn't  break when it imported the gradle scripts. Importing the project module did not go down well. 

```
include ':library'
project(':library').projectDir = new File(settingsDir, '../ExoPlayer/library')
```

Then in the dependancies section

```
compile project(':library')
```

It seems to make a copy of the sources I think. So hopefully it syncs those.

**Comment by ojw28** [comment]
See https://github.com/google/ExoPlayer/issues/2974.
