### ISSUE TITLE
Additional operations to receive url from custom object

### ISSUE THREAD

**Issue by ghost** [google/ExoPlayer#2117]
Hi there. Just a question. I have a custom model and for receiving content url I need to send 1 more network request. Where can I implement this logic? I thought that I can do this on custom MediaSource but passed url goes to Period -> Extractor -> Loadable and so on. Thank you.

**Comment by ojw28** [comment]
I would have thought you should do the request to obtain the media URL before you create the player (i.e. entirely in your own code).

**Comment by ghost** [comment]
But I have a list of object and don't want to make request for all of them at a time. I want to make a request for a specific object only when player start to play it.

**Comment by andrewlewis** [comment]
Can you use a custom [DataSource](https://github.com/google/ExoPlayer/blob/f8ed4cf/library/src/main/java/com/google/android/exoplayer2/upstream/DataSource.java) to do this? You could provide arbitrary identifier URIs for content to MediaSources, then resolve these in your custom DataSource's open method, which would then then delegate to e.g. DefaultDataSource.

**Comment by ojw28** [comment]
You could also make your own `MediaSource` as a solution to this problem. The DASH, SmoothStreaming and HLS `MediaSource` implementations all make "top level requests" of this kind to retrieve the manifests that contain the individual stream URLs. So they're in some ways similar, albeit quite a bit more complicated than what you'll need.
