### ISSUE TITLE
DASH live stream

### ISSUE THREAD

**Issue by Reaper213cheng** [google/ExoPlayer#2119]
Someone can tell me,whether the ExoPlayer has supported DASH live stream? Thanks

**Comment by ojw28** [comment]
Yes

**Comment by Reaper213cheng** [comment]
Thanks. I have another issue. 
I try to use nginx-rtmp-module to product the MPD for DASH live-streaming,but the ExoPlayer is not working with the mpd.If you meet this question before ?Thanks

**Comment by ojw28** [comment]
If you have an issue, please file a new issue including all of the information in the issue template. We cannot efficiently investigate or answer questions without the requested information. Thanks!
