### ISSUE TITLE
Decoder OMX.amlogic.avc.decoder.awesome has issues handling flush after EOS

### ISSUE THREAD

**Issue by unext-wendong** [google/ExoPlayer#2120]
- Issue description

Seeking to any other place of the content after the player went into ExoPlayer.STATE_ENDED state will cause the freeze of the video on a device using OMX.amlogic.avc.decoder.awesome decoder. The audio in this case plays for a while from the seek target position before ExoPlayer.STATE_BUFFERING is reported and also stops.

Streaming protocol tried: Smooth Streaming. (Don't think it's specific to protocol).

- Steps to reproduce

Content: the "Super speed" SMOOTHSTREAMING sample content in ExoPlayer demo app.

Change the ExoPlayer demo app to seek to any place within the content after ExoPlayer.STATE_ENDED is received, e.g. in file demo/src/main/java/com/google/android/exoplayer/demo/PlayerActivity.java:
```
  public void onStateChanged(boolean playWhenReady, int playbackState) {
    if (playbackState == ExoPlayer.STATE_ENDED) {
+      player.getPlayerControl().seekTo(10000); // make sure it's a valid position
+      return;
-      showControls();
    }
```
- Device

HikariBox 2000
https://www.ntt-west.co.jp/kiki/hikaribox/hb-2000/spec/

Video decoder used: OMX.amlogic.avc.decoder.awesome
Android version: 4.4

Since the issue is specific to the video decoder, I believe it can also happen on other devices using the same decoder.
- ExoPlayer version used

v1.5.12

- Log

[log_amlogic_20161129.txt](https://github.com/google/ExoPlayer/files/618587/log_amlogic_20161129.txt)

You can see the following messages in the log:
```
11-29 18:22:13.177   127  8113 D AmlogicVideoDecoderAwesome: 	===mEosStamp 120787000 ==
11-29 18:22:13.757   127  8106 D AmlogicVideoDecoderAwesome:   		  EosStamp coming 120787
11-29 18:22:13.757   127  8106 V AmlogicVideoDecoderAwesome: ******* EOS buffer in decoder output.
11-29 18:22:13.767   127  8106 D AmlogicVideoDecoderAwesome: displayThread___eos_fillBufferDone
11-29 18:22:13.767   127  8106 V AmlogicVideoDecoderAwesome: ******* EOS buffer in decoder output.
...
11-29 18:22:14.107  8061  8061 E PlayerActivity: onStateChanged STATE_ENDED wli seek to 0
...
11-29 18:22:14.117   127  8103 I OmxComponent: OMX.amlogic.avc.decoder.awesome: flush input
...
11-29 18:22:14.117   127  8103 I OmxComponent: OMX.amlogic.avc.decoder.awesome: flush output
11-29 18:22:14.117   127  8103 V AmlogicVideoDecoderAwesome: flushOutput:367 >
11-29 18:22:14.127   127  8106 D AmlogicVideoDecoderAwesome: displayThread___eos_fillBufferDone
...
11-29 18:22:14.307   127  8106 E AmlogicVideoDecoderAwesome: displayThread___should not here
```
- Others

Verified the same sequence works on Nexus 5X using qualcomm avc decoder.

**Comment by ojw28** [comment]
Can you confirm that normal seeking (prior to having reached the ended state) work successfully, and that the player does indeed transition properly into the ended state? Thanks!

**Comment by unext-wendong** [comment]
Normal seek has no problem.

> and that the player does indeed transition properly into the ended state?

I assume ExoPlayer reports onStateChanged(ExoPlayer.STATE_ENDED) only when the transition to ended state completes. Do you mean it's possible that there is an issue in ExoPlayer that this event is reported incorrectly?

As for the decoder, the following logs should indicate that it's EOS state. The event onStateChanged(ExoPlayer.STATE_ENDED) was reported after this.
```
11-29 18:22:13.177   127  8113 D AmlogicVideoDecoderAwesome: 	===mEosStamp 120787000 ==
11-29 18:22:13.757   127  8106 D AmlogicVideoDecoderAwesome:   		  EosStamp coming 120787
11-29 18:22:13.757   127  8106 V AmlogicVideoDecoderAwesome: ******* EOS buffer in decoder output.
11-29 18:22:13.767   127  8106 D AmlogicVideoDecoderAwesome: displayThread___eos_fillBufferDone
11-29 18:22:13.767   127  8106 V AmlogicVideoDecoderAwesome: ******* EOS buffer in decoder output.
```

**Comment by unext-wendong** [comment]
Fixed by https://github.com/google/ExoPlayer/issues/2131.
