### ISSUE TITLE
How to get MPEG-TS bitrate?

### ISSUE THREAD

**Issue by catbaxter** [google/ExoPlayer#2126]
EventLogger.onLoadCompleted works like a charm for hls sources but not for mpeg-ts.

**Comment by AquilesCanta** [comment]
I am going to assume that by mpeg-ts you mean a raw ts file using an extractor media source. This makes sense considering onLoadCompleted implements an AdaptiveMediaSourceEventListener method which only applies for adaptive media. Even if it did, I don't think onLoadCompleted would provide any generally useful information as it doesn't handle the download throttling done by extractor media source. You should also clarify if you are looking for the download bandwidth or the TS flie bitrate (as defined by the PCR, for example). I assume the first. You can have a look at BandwidthMeter and see how it's done. I hope this provides some insight. You should try asking this kind of questions in a general Q&A exchange. The issue tracker is reserved for bug reports and feature requests, mainly.
