### ISSUE TITLE
This m3u8 file can't play with release-v2,but release-v1 can play normally.

### ISSUE THREAD

**Issue by gongshoudao** [google/ExoPlayer#2129]
The below video can't play start from 1:05 on exoplayer v2.0 , but the version 1.0 can.
How can I fix this?(Forgive me of fool English :-D )

This is video link:
http://www.androidcycle.com/wp-content/uploads/2016/11/testvideo/online2.m3u8

And this is .ts list in this .m3u8 file:

#EXTM3U
#EXT-X-TARGETDURATION:10
#EXT-X-MEDIA-SEQUENCE:0
#EXTINF:64.333
http://ohfng5qj9.bkt.gdipper.com/loco_1_video_51000_0.ts
#EXTINF:60.000
http://ohfng5qj9.bkt.gdipper.com/loco_1_video_51000_1.ts
#EXTINF:60.000
http://ohfng5qj9.bkt.gdipper.com/loco_1_video_51000_2.ts
#EXTINF:60.000
http://ohfng5qj9.bkt.gdipper.com/loco_1_video_51000_3.ts
#EXTINF:60.000
http://ohfng5qj9.bkt.gdipper.com/loco_1_video_51000_4.ts
#EXTINF:60.000
http://ohfng5qj9.bkt.gdipper.com/loco_1_video_51000_5.ts
#EXTINF:60.000
http://ohfng5qj9.bkt.gdipper.com/loco_1_video_51000_6.ts
#EXTINF:5.100
http://ohfng5qj9.bkt.gdipper.com/loco_1_video_51000_7.ts
#EXT-X-ENDLIST

Thank you!

**Comment by AquilesCanta** [comment]
First, please try fixing the duration declared in the manifest (~60 secs) to be closer to the actual chunks duration (~6secs, at least for chunks 1 and 3. I haven't tried the others). After that, please open a new issue describing exactly what the steps to reproduce are, and what the expected result is.

**Comment by gongshoudao** [comment]
![image](https://cloud.githubusercontent.com/assets/4568329/20780739/609c7ff8-b7b8-11e6-8744-c8247258e1d5.png)

If I disable the video,the player can play audio normally.
Maybe ExoPlayerImplInternal#doSomeWork() method has some issue or the play is severe
