### ISSUE TITLE
Progressive download: start loading from specific time

### ISSUE THREAD

**Issue by xucian** [google/ExoPlayer#2130]
Hi. 
I need to stream large hi-res videos from url and I'm thinking how it's best to implement it.
Having smooth full-res playback is most important than waiting time, so a calculated amount of video will download beforehand, based on a lot of factors, including disk space. because of this, we don't need SmoothStreaming, HLS, DASH etc. as we'll only use the same data file - the one of the highest quality.
I first went with progressive download, but I see the loading resets to 0 when seeking before current position or after the last buffered segment. 
Is it a limitation of the progressive download approach or with exoplayer? if the former is true, what approach would you recommend instead?
The only additional thing I need is to load a video file from a specific time

**Comment by ojw28** [comment]
On the serving side I don't think you need to do anything fancy. Hosting an mp4, mkv or webm file in a standard way should be fine. You should check your server supports partial range requests, but beyond that I don't think you need to do anything special

On the client side, we don't provide out-of-the-box support for things like downloading part of the media to disk beforehand. So that's something you'd need to look at building yourself, if you really need to do this.

**Comment by xucian** [comment]
Thanks for this useful info!
so, if at the position x(non-zero) there's no buffered media and I call seekTo(x) and this results is re-buffering from zero,  it means the server doesn't support partial range requests, right? if this is true, I guess I should switch from plain Amazon S3 to an active server

**Comment by ojw28** [comment]
In case it wasn't clear, when I said you don't need to do anything fancy, I explicitly meant you don't need to be looking at anything related to progressive downloading, at least as it's described [here](https://en.wikipedia.org/wiki/Progressive_download). Comments like

> The offset parameter name differs for various servers so it must be specified in player settings.

on that page suggest what it's describing isn't really standardized. Just hosting the file in a normal way on a server that supports partial range requests is the best thing to do.

I'd be pretty surprised if Amazon servers don't support partial range requests by default. It's a pretty standard thing. If it weren't supported then their servers wouldn't support something as simple as resuming a partial download, for example. I don't know what an "active server" is, but I doubt you need one. You're probably just not using a suitable container format for your media (e.g. mp4, mkv or webm). Search for "seek" in our [supported formats](https://google.github.io/ExoPlayer/supported-formats.html) page for more information.

**Comment by xucian** [comment]
Crystal clear now! 
I just forgot that for some test videos I was using a local, poor python server (the well-known one-liner "python -m http.server").
Indeed, Amazon S3 supports that feature (I see the "Accept-Ranges bytes" header in response).
Thanks! 
Really-really valuable piece of info :)
