### ISSUE TITLE
ExoPlayer 2.0 scaling video view

### ISSUE THREAD

**Issue by YuriyRashkevych94** [google/ExoPlayer#2141]
Hi) i have an issue with scaling video view using ExoPlayer 2.0. I found that scaling can be reached through AspectRatioFrameLayout object using setAspectRatio() method. Yes, it helps but a little bit((
Is there any else approach to do scaling? I know that we need to use TextureView instead of Surface View when we do that kind of things, but i can find out how((

**Comment by ojw28** [comment]
Closing because it's unclear what the question is.
