### ISSUE TITLE
OkHttp extension depends on "+" dependency

### ISSUE THREAD

**Issue by BoD** [google/ExoPlayer#2144]
As you can see here: 
https://github.com/google/ExoPlayer/blob/release-v2/extensions/okhttp/build.gradle#L40

The version of the OkHttp dependency has a "+" which means, use the latest.  This is bad practice as this leads to unreproducible builds.

In fact there has just been a new version of OkHttp which broke our build and it took a bit of time for us to realize the reason was this :)

Please use an explicit version instead.

**Comment by ojw28** [comment]
This is fixed already in `dev-v2` and will be in the next release. See:

https://github.com/google/ExoPlayer/blob/dev-v2/extensions/okhttp/build.gradle#L40

Thanks!
