### ISSUE TITLE
[QUESTION]:  Is there a way to allow an end user to choose to use Audio pass through or not?

### ISSUE THREAD

**Issue by stuckless** [google/ExoPlayer#2148]
I'm using ExoPlayer r2.0.4

Some devices such as Shield support audio passthrough, but if you don't have it hooked up to a receiver that can decode it... you get video without audio.

I've included the ffmpeg extension and enabled ac3 decoder, and this works well, now, using shield, I can get audio and video without using a receiver.  I'm guessing ffmpeg is software decoding it.

The challenge that I see, is that some users will want this, and others will not.  So, in my application (SageTV MiniClient), I'm trying to figure out if there is a way to allow the end user to configure if they support pass-through audio.

I've reviewed the code, but it's not evident to me where I'd implement such a feature, of if ExoPlayer has a "setPassthroughEnabled(false)" type of API that I'd call on the player, etc.

Just looking for some guidance as how this could be implemented, or if ExoPlayer already supports this.  I'm assuming that becuase I've pulled in ffmpeg, and I get audio in test setup (where I didn't before), that passthough would not longer be working in this scenario, since ffmpeg is handling the audio.

Thanks for all great work.

**Comment by andrewlewis** [comment]
For context, the most common ways ExoPlayer might play these surround sound formats are:
1. If the MediaCodecAudioRenderer was passed AudioCapabilities that indicate that the HDMI connection supports AC-3, E-AC-3, DTS or DTS-HD output, it will write encoded data to the AudioTrack for decoding on the receiver (passthrough).
1. If passthrough is not available and the device has a decoder for the format accessible via MediaCodec, the audio can be decoded on-device and output as PCM. I've only seen this in a few devices and sometimes the decoder is limited (e.g. only decoding stereo).
1. If you have compiled the ffmpeg extension with the required codec, and have set SimpleExoPlayer to prefer extension decoders (or equivalent), the audio gets decoded to multi-channel PCM. (Note that ffmpeg only gets priority if extension renderers come first, for example, if [EXTENSION_RENDERER_MODE_PREFER](https://github.com/google/ExoPlayer/blob/894ae1a/library/src/main/java/com/google/android/exoplayer2/SimpleExoPlayer.java#L117) is set.)

MediaCodecAudioRenderer decides whether to use passthrough based on the AudioCapabilities passed in, so you can override what formats are available there. If you pass in an AudioCapabilities that [only allows stereo](https://github.com/google/ExoPlayer/blob/8d122a1/library/src/main/java/com/google/android/exoplayer2/audio/AudioCapabilities.java#L36), passthrough won't be used. I think that gives the control you're looking for. (Aside: I think a platform setting was added for Android TVs in Android N which allows the user to override whether passthrough is always on or off. That setting should override what encodings are included when AudioCapabilities is constructed based on the HDMI capabilities.)

So you can implement a setting to force passthrough on/off by providing the relevant AudioCapabilities to MediaCodecAudioRenderer, and, if you put MediaCodecAudioRenderer before FfmpegAudioRenderer, passthrough should be used in preference to on-device decoding if possible.

If you need to get further control over what renderers are used (and information on what formats are in the input) you could experiment with providing your own TrackSelector. See MappingTrackSelector/DefaultTrackSelector as a starting point.

**Comment by stuckless** [comment]
Thanks for the detailed explanation.   I think that simply using `extensionRendererMode` in the SimpleExoPlayer solves my initial issue... ie, I'm only providing ffmpeg extension for people that don't have harware decoding... so I can turn on/off the user of extension renderers (I'm only using ffmpeg audio) using that variable.  thx.

I think that using the AudioCapabilities is definitely a more robust solution.

Side/Note, it would be nice if ExoPlayer had the ability to easily blacklist codecs (ie, some hardware implementations are buggy, would be nice to pass a list of blacklisted hardware codecs to the player)
