### ISSUE TITLE
Mpeg-L2 audio doesnt work on some devices

### ISSUE THREAD

**Issue by bene25** [google/ExoPlayer#2153]
On some devices mpeg-L2  is not working. How can I play it?
It doesnt pass hasOnlyUnplayableTracks, but on other device the same stream works fine.

**Comment by andrewlewis** [comment]
Do those devices have a Layer II decoder? Can you play the stream using a MediaPlayer-based app started with `adb shell am start -a android.intent.action.VIEW -d "<url goes here>" -t "audio/*"`?

See the [supported formats](https://google.github.io/ExoPlayer/supported-formats.html#sample-formats) page for more information.

**Comment by bene25** [comment]
Yes, It works.

**Comment by andrewlewis** [comment]
Did you find that the file plays using MediaPlayer but not ExoPlayer? If so, please provide a link to the content and tell us what device you a testing on.

**Comment by bene25** [comment]
Yes, video plays, but audio doesnt.
Minix X7 mini
Stream dump - [dump.ts.zip](https://github.com/google/ExoPlayer/files/633574/dump.ts.zip)

**Comment by ojw28** [comment]
I suspect the device doesn't expose its decoder properly. The sample works fine for me on Pixel, so it doesn't seem like an ExoPlayer issue.
