### ISSUE TITLE
Capabilities: VP8 video "exceeds capabilities" (but plays fine if forced)

### ISSUE THREAD

**Issue by laurencedawson** [google/ExoPlayer#2157]
When opening this file the first frame is never rendered and the file isn't played.

`https://zippy.gfycat.com/ForsakenRedAllosaurus.webm`

Tested with the sample and in my own Exoplayer deployment (v2.0.4)

Tried on multiple versions of Android (7.1, 7.0, and older).

The log is very minimal...

`12-05 14:18:55.566: I/ExoPlayerImpl(5308): Init 2.0.4`

**Comment by Mihuilk** [comment]
I'am not sure but I think  you should install [VP9 extension](https://github.com/google/ExoPlayer/tree/release-v2/extensions/vp9)

**Comment by laurencedawson** [comment]
Most webm files play fine, this one just doesn't even initialize / play the first frame. It seems strange that no error is thrown or debug logs written.

**Comment by ojw28** [comment]
The issue is similar to https://github.com/google/ExoPlayer/issues/2034, and occurs because the VP8 decoder under-reports its true capabilities. On `dev-v2` you can enable "try and play anyway" behavior with:

```
trackSelector.setParameters(
    trackSelector.getParameters().withExceedRendererCapabilitiesIfNecessary(true));
```

on your `DefaultTrackSelector` instance.

**Comment by ojw28** [comment]
Note: The exact reason this video is rejected is because it has an odd height (397px). If you control the encoding side you should probably try and ensure the video dimensions are even for best compatibility. There were issues with Chrome and odd dimension VP8 as well (search Google for: `vp8 odd resolution`), for example.

**Comment by laurencedawson** [comment]
@ojw28 setting the additional params on `dev-v2` did the trick. Is there a timescale for this rolling to prod? 

Thanks

**Comment by ojw28** [comment]
We've enabled this by default in `dev-v2` now, so you wont even need to do it yourself. We're looking to wrap up a release this week.
