### ISSUE TITLE
Multiple CC tracks support in Transport Stream files

### ISSUE THREAD

**Issue by bene25** [google/ExoPlayer#2161]
Hello. How I could get multiple subtitles embeded in .ts file?

   trackInfo = trackSelector.getCurrentSelections().info;
        trackGroups = trackInfo.getTrackGroups(2);
        trackGroupsAdaptive = new boolean[trackGroups.length];
        for (int groupIndex = 0; groupIndex < trackGroups.length; groupIndex++) {
            TrackGroup group = trackGroups.get(groupIndex);

trackGroups return only one subtitle though there are 3 subtitles.

Subtitles format CEA-608

You could find stream details here: https://github.com/google/ExoPlayer/issues/2056

**Comment by bene25** [comment]
Any help for this issue?

**Comment by AquilesCanta** [comment]
We still don't have proper support for multiple CC services. This is on the map, possibly Q1. I will use this issue to track this.

**Comment by AquilesCanta** [comment]
I am working on adding multiple CC support now. However, the stream you provided doesn't seem to include 608, but rather DVB subtitles. I am speaking about the file provided [here](https://github.com/google/ExoPlayer/issues/2056#issuecomment-263528470). If you have a TS with multiple 608 channels, or even better, an HLS stream, please send a link to dev.exoplayer@gmail.com. This should speed up the process. 

As far as I know, HLS does not support dvb subtitles.
