### ISSUE TITLE
DataSourceInputStream bug

### ISSUE THREAD

**Issue by xbezdeka** [google/ExoPlayer#2162]
I believe that there is bug in DataSourceInputStream. After one interation of **read()** method, **bytesRead()** method will return size 3 instead of 1, because **totalBytesRead** will be counted multiple times. 
The reason for this is because **read()** method internally calls **read(byte[] buffer)** which calls **read(byte[] buffer, int offset, int length)** while all methods in chain increment totalBytesRead class attribute.

**Comment by ojw28** [comment]
Heh, yes :(. We'll fix this. Thanks!

**Comment by ojw28** [comment]
Fixed in: https://github.com/google/ExoPlayer/commit/e5bc00e
