### ISSUE TITLE
Live dash manifest refresh issue

### ISSUE THREAD

**Issue by tao1** [google/ExoPlayer#2164]
Hello,

Playback of live dash freeze after 30s on my streams. This issue looks similar to issue #397.
It is reproducible with ExoPlayer version 1.5.12 and 2.0.4 for production dash streams produced by my company. During 1.5.12 debugging, it appears that manifest refresh is not handled as expected by DashChunkSource. I mean overlap between 2 manifest downloads is not well handled, leading to this freeze. Notice this stream runs finely on Dash Industry Forum reference implementation and Labgency player but also fails on Shaka player.
I can share the failing stream url only privately. 
PLEASE contact me for I give you stream url and vpn access details to this stream.

Cheers,

Laurent.

**Comment by ojw28** [comment]
Please email `dev.exoplayer@gmail.com` with a test stream. We need one that works without using a VPN, however, if you want us to investigate the problem. It sounds like the manifests you're generating are invalid, particularly since you're also seeing the issue using Shaka player.

**Comment by ojw28** [comment]
Confirmed the manifests are invalid. Following up via email. Thanks!
