### ISSUE TITLE
Support setting request properties on DefaultHttpDataSourceFactory

### ISSUE THREAD

**Issue by trckashyap** [google/ExoPlayer#2166]
Need to send custom headers to our server while streaming media URL.
Please provide an API to support this in Exoplayer v2.
Earlier we used to do this via DefaultHttpDataSource(setRequestProperty method), but now its not exposed in Renderers or RendererBuilder.

-Kashyap.

**Comment by ojw28** [comment]
- There is no class called `RendererBuilder`, as far as I can see?
- You can implement your own `HttpDataSource.Factory` to generating instances of `DefaultHttpDataSource` that are configured the way you want them, so I think this is possible. If you don't think this works, please clarify why not.
- We could make it easier by allowing request properties to be set on `DefaultHttpDataSourceFactory`. Would that help?

**Comment by trckashyap** [comment]
Allowing request properties to be set on DefaultHttpDataSourceFactory would be great else we need to build our own ExtractorRendererBuilder, HlsRendererBuilder etc to add headers after createDataSource() is done.

**Comment by ojw28** [comment]
I'm really struggling to follow what you're referring to. There are no classes called RendererBuilder, ExtractorRendererBuilder or HlsRendererBuilder in ExoPlayer V2. It shouldn't be much work at all to implement your own `HttpDataSource.Factory` to support this case, as per my second bullet point above, until we add support to the default one.

**Comment by trckashyap** [comment]
Thanks...Tried out implementing my own Factory and successfully able to do it, but in future it would be great if a method is exposed similar to createDataSource() in Factory.

**Comment by ojw28** [comment]
Note: We should also add support for the okhttp and cronet factories.
