### ISSUE TITLE
HLS video triggering frequent (unnecessary?) track change events

### ISSUE THREAD

**Issue by ghost** [google/ExoPlayer#2168]
Description:  

I am using ExoPlayer 2.0.4 to play HLS video. I am observing that I am receiving constant track change events (one every few seconds) followed by buffering and a subsequent another track change event, buffering, etc. Additionally, it appears that when the track change events are getting fired, it is reselecting the same track that it has been using.

I am using the DefaultBandwidthMeter, DefaultLoadControl and AdaptiveVideoTrackSelection.Factory with no customized parameters (I've tried custom parameters but I appear to get the same behavior).

Below is an excerpt from my logs detailing the frequency of the track changes and which track is being selected.

```
12-07 11:34:01.353 2252-2252/ D/.player.VideoPlayer: Track Change [ resolution=848x480, framerate=-1.0 codecs=null,  bitrate=-1,  sizeRatio1.0062894]
12-07 11:34:03.363 2252-2252/ D/.player.VideoPlayer: Track Change [ resolution=848x480, framerate=-1.0 codecs=null,  bitrate=-1,  sizeRatio1.0062894]
12-07 11:34:10.923 2252-2252/ D/.player.VideoPlayer: Track Change [ resolution=1920x1080, framerate=-1.0 codecs=null,  bitrate=-1,  sizeRatio1.0]
12-07 11:34:24.043 2252-2252/ D/.player.VideoPlayer: Track Change [ resolution=1920x1080, framerate=-1.0 codecs=null,  bitrate=-1,  sizeRatio1.0]
12-07 11:34:28.103 2252-2252/ D/.player.VideoPlayer: Track Change [ resolution=1920x1080, framerate=-1.0 codecs=null,  bitrate=-1,  sizeRatio1.0]
12-07 11:34:35.213 2252-2252/ D/.player.VideoPlayer: Track Change [ resolution=1920x1080, framerate=-1.0 codecs=null,  bitrate=-1,  sizeRatio1.0]
12-07 11:34:39.763 2252-2252/ D/.player.VideoPlayer: Track Change [ resolution=1920x1080, framerate=-1.0 codecs=null,  bitrate=-1,  sizeRatio1.0]
12-07 11:34:44.293 2252-2252/ D/.player.VideoPlayer: Track Change [ resolution=1920x1080, framerate=-1.0 codecs=null,  bitrate=-1,  sizeRatio1.0]
12-07 11:34:53.483 2252-2252/ D/.player.VideoPlayer: Track Change [ resolution=1920x1080, framerate=-1.0 codecs=null,  bitrate=-1,  sizeRatio1.0]
```

Below is a copy of the playlist (urls redacted)

```
#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=670509,RESOLUTION=848x480,FRAME-RATE=23.974,CODECS="avc1.4d401e,mp4a.40.2"
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=670509,RESOLUTION=848x480,FRAME-RATE=23.974,CODECS="avc1.4d401e,mp4a.40.2"
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=670509,RESOLUTION=848x480,FRAME-RATE=23.974,CODECS="avc1.4d401e,mp4a.40.2"
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=455955,RESOLUTION=640x360,FRAME-RATE=23.974,CODECS="avc1.4d401e,mp4a.40.2"
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=455955,RESOLUTION=640x360,FRAME-RATE=23.974,CODECS="avc1.4d401e,mp4a.40.2"
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=455955,RESOLUTION=640x360,FRAME-RATE=23.974,CODECS="avc1.4d401e,mp4a.40.2"
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2509026,RESOLUTION=1920x1080,FRAME-RATE=23.974,CODECS="avc1.640028,mp4a.40.2"
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2509026,RESOLUTION=1920x1080,FRAME-RATE=23.974,CODECS="avc1.640028,mp4a.40.2"
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2509026,RESOLUTION=1920x1080,FRAME-RATE=23.974,CODECS="avc1.640028,mp4a.40.2"
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1030187,RESOLUTION=1280x720,FRAME-RATE=23.974,CODECS="avc1.64001f,mp4a.40.2"
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1030187,RESOLUTION=1280x720,FRAME-RATE=23.974,CODECS="avc1.64001f,mp4a.40.2"
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1030187,RESOLUTION=1280x720,FRAME-RATE=23.974,CODECS="avc1.64001f,mp4a.40.2"
```

**Comment by AquilesCanta** [comment]
I am not sure it's selecting the same track everytime, from what I can understand from that (not formatted) manifest, there are three variants with the same resolution and bandwidth. I have a feeling that's related to the issue. I will have a more thorough look but, if possible, please provide all the information required in the issue template. If you don't want to make the link public, please send it to dev.exoplayer@gmail.com.

**Comment by ghost** [comment]
@AquilesCanta I sent an email with relevant information to dev.exoplayer@gmail.com.  The issue number is in the subject.  Let me know if you need more info.

**Comment by AquilesCanta** [comment]
I am getting a 403. Can you fix this?

**Comment by ghost** [comment]
@AquilesCanta Unfortunately, the URLs are designed to expire after so much time (I think 4 hours?).  I've sent you an updated playlist.  If you need me to send you another one to expiry let me know.  Thanks for looking into this.

**Comment by AquilesCanta** [comment]
I'll try to recreate the issue myself, then. Until then, I'd suggest trying to attach a debugger and working out the root cause of the issue.

**Comment by ghost** [comment]
@AquilesCanta So here is what I'm seeing...

ExoPlayerImplInternal gets periodic messages for MSG_SEEK_TO which in turn calls ExoPlayerImplInternal.seekToInternal().

Within seekToInternal(), this condition fails...

`if (periodIndex == playbackInfo.periodIndex && ((periodPositionUs == C.TIME_UNSET && playbackInfo.positionUs == C.TIME_UNSET) || ((periodPositionUs / 1000) == (playbackInfo.positionUs / 1000)))) {
    // Seek position equals the current position. Do nothing.
    return;
}`

`periodIndex == playbackInfo.periodIndex : true`
`periodPositionUs == C.TIME_UNSET && playbackInfo.positionUs == C.TIME_UNSET : false`
`(periodPositionUs / 1000) == (playbackInfo.positionUs / 1000) : false`

resulting in repeated calls to seekToPosition().  seekToPosition() always ends up with a non-null newPlayingPeriodHolder resulting in a call to setPlayingPeriodHolder().  This results in new track selections which calls the track selector's onSelectionActivated() which is what triggers my listener for onTrackSelectionsChanged() on my DefaultTrackSelector.

I'm not sure if this information helps or not.  I'll keep digging.  Unfortunately, ExoPlayerImplInternal doesn't appear in the javadocs so I'm unsure as to what a lot of these method calls are and why they're being called.  Hopefully this explanation of the flow my app is going through will help. 

Let me know if you have any questions.

Also, if it would help, PM me to let me know when you have time to look at this and I can try and send you a fresh copy of the playlist.  This will give you more of an opportunity to look at the data that I'm using.

**Comment by ghost** [comment]
@AquilesCanta I have discovered what the issue is and it is a client side issue.  I appreciate you taking the time to work through this with me.  This issue can be closed.
