### ISSUE TITLE
Detect whenever a new video start to play in ConcatenatingMediaSource

### ISSUE THREAD

**Issue by liauli** [google/ExoPlayer#2169]
I am new to ExoPlayer and it runs smoothly so far.
I am using ConcatenatingMediaSource to play many videos at once but I have a problem: I need to detect whenever each video start to play so I can send statistic data related to each video. 
I used STATE_READY at first but this state also called after STATE_BUFFER finished so I don't know which STATE_READY is the first one or the other one that called after buffering.
Is there any other way to achieve this?
I have another idea but I haven't found a way to do this. So after a video finished, in STATE_ENDED I started the next video. I tried to create a new MediaSource and do player.prepare(MediaSource) but it didn't work. 
I also used onPositionDiscontinuity() from Exoplayer listener but it is also fired along with STATE_READY.
Can someone help me ?
Thank you!

**Comment by ojw28** [comment]
Please see: https://github.com/google/ExoPlayer/issues/2053
