### ISSUE TITLE
FormatEvaluator#determineIdealFormat ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by ened** [google/ExoPlayer#217]
```
    /**
     * Compute the ideal format ignoring buffer health.
     */
    protected Format determineIdealFormat(Format[] formats, long bitrateEstimate) {
      long effectiveBitrate = computeEffectiveBitrateEstimate(bitrateEstimate);
      for (int i = 0; i < formats.length; i++) {
        Format format = formats[i];
        if (format.bitrate <= effectiveBitrate) {
          return format;
        }
      }
      // We didn't manage to calculate a suitable format. Return the lowest quality format.
      return formats[formats.length - 1];
    }
```

Probably this needs a small check to prevent a *ArrayIndexOutOfBoundsException*.

```
    /**
     * Compute the ideal format ignoring buffer health.
     */
    protected Format determineIdealFormat(Format[] formats, long bitrateEstimate) {
      long effectiveBitrate = computeEffectiveBitrateEstimate(bitrateEstimate);
      for (int i = 0; i < formats.length; i++) {
        Format format = formats[i];
        if (format.bitrate <= effectiveBitrate) {
          return format;
        }
      }
      // We didn't manage to calculate a suitable format. Return the lowest quality format.
      if(formats.length > 0) {
        return formats[formats.length - 1];
      } else {
        return null;
      }
    }
```

**Comment by ojw28** [comment]
None of those are actual crashes that take down the app though, unless I'm mistaken? What the user sees in all of theses cases is an error message, which is effectively what's supposed to happen.

**Comment by ojw28** [comment]
We should propagate clearer exceptions back to the application. It's then up the the application to word the error message to the user. So this issue is effectively tracking propagating something better than, for example, NullPointerException, back to PlayerActivity.

**Comment by ened** [comment]
Well, things don't play and internal errors are shown. To the common developer this sounds like a unfinished library. 

Agree with you exceptions should be clear and moved up one level. Thanks!

**Comment by ojw28** [comment]
Printing internal errors is generally useful for debugging. It's actually the demo application that's printing the errors, not the library, because it's probably something a developer would want to do.

But yeah, let's leave this issue to track making the exceptions thrown a little clearer.

**Comment by ojw28** [comment]
I think the exceptions are fairly sane now. I suspect that the Genymotion simulator may fail to pass Android's CTS tests for video, in which case it shouldn't really be considered representative of a real Android device (NB - According to [this](https://m.google.com/app/basic/stream/z12st5kpfk2vjvqui22cxr0xuxmigp34304?cbp=l67qxg7hagr&partnerid=operamini1104&sview=27&cid=5&soc-app=115&soc-platform=1&spath=/app/basic/%2BGenymotionEmulator/posts&sparm=cbp%3Dzd7gr8otkypv%26partnerid%3Doperamini1104%26sview%3D27%26cid%3D5%26soc-app%3D115%26soc-platform%3D1%26stct%3DChYQ_PWi84-KwQIYsOfUman_wAIgACgHEhQIABCw59SZqf_AAhjCxJHek4a4AhgC%26spath%3D/app/basic/108625703815216743905/posts%26sparm%3Dcbp%253D1q4yv25tei143%2526partnerid%253Doperamini1104%2526sview%253D27%2526spath%253D/app/basic/102082383403038732632/posts%2526sparm%253Dcbp%25253D18neyar9iq2s2%252526partnerid%25253Doperamini1104%252526sview%25253D27) they were passing nearly all of the tests some time ago, but specifically noted video as an area where they still have failures.
