### ISSUE TITLE
keeping buffer at the specified position

### ISSUE THREAD

**Issue by rafiip** [google/ExoPlayer#2171]
Hi,
I am using latest version of exoplayer and i'm trying to play a local video through it .
i'm trying to play specified video between 2 given points in a loop , and since i want to make that loop seamless , i would like to keep buffer at start point ( not start point of the default video but the given one ).
i will appreciate if you point me to the right direction since i almost lost my mind to it .

**Comment by ojw28** [comment]
We already support seamless looping in ExoPlayer V2. So I think all you need is the ability to play a section of a video (rather than the whole thing), which you could then loop. The ability to play a section of a video is tracked by #1988, so please follow that issue.
