### ISSUE TITLE
BDN (PNG+XML) subtitles

### ISSUE THREAD

**Issue by sarahachem** [google/ExoPlayer#2177]
I am currently using exoplayer with an application to play DRM encrypted movies with subtitles. Some movies have SRT subtitles, which I managed to integrate successfully in the DashRendererBuilder class using the following code in the buildRenderers method:
```java
          MediaFormat mediaFormat = MediaFormat.createTextFormat("0", MimeTypes.APPLICATION_SUBRIP, MediaFormat.NO_VALUE, C.MATCH_LONGEST_US, null);
          Uri uri = Uri.parse(getSRTURI());
          DataSource textDataSource = new DefaultUriDataSource(context, bandwidthMeter, userAgent);
          SingleSampleSource textSampleSource = new SingleSampleSource(uri, textDataSource, mediaFormat);
          TrackRenderer textRenderer = new TextTrackRenderer(textSampleSource, player, player.getMainHandler().getLooper());
```
However, other movies have BDN subtitles, which consist of PNG and XML files. Is there a way to integrate such subtitles in exoplayer?

**Comment by ojw28** [comment]
We do not support bitmap subtitles. Support for them is tracked by #179 (I'm not sure whether BDN is another variant of bitmap subtitle format, but I think we can use the same issue for tracking).
