### ISSUE TITLE
One media chunk may be downloaded for multiple times

### ISSUE THREAD

**Issue by aidynamic** [google/ExoPlayer#2178]
Hi, I am testing the ExoPlayer for HLS adaptive streaming. The version of my ExoPlayer is 2.0.4.
I found that a media chunk may be downloaded for multiple times during the play. 
For instance, when I started to play a HLS video, the video player requested two representations of the first video chunks. (gear1 is a low resolution version, gear 2 is a high resolution version).
The requested URIs are as follows:
https://devimages.apple.com.edgekey.net/streaming/examples/bipbop_4x3/gear1/fileSequence0.ts
https://devimages.apple.com.edgekey.net/streaming/examples/bipbop_4x3/gear2/fileSequence0.ts

This problem also happened to some other chunks during the play, and here is a log of the requested media chunks during play.
You can see that the media chunk 0, 2, 3, 4, 6 are requested for multiple times. 
How does this happen? Is this a bug? 
Downloading a video chunk for multiple times will waste bandwidth.

12-10 17:47:26.767 27663-27953/com.google.android.exoplayer2.demo D/httpOpen: https://devimages.apple.com.edgekey.net/streaming/examples/bipbop_4x3/bipbop_4x3_variant.m3u8
12-10 17:47:27.814 27663-27974/com.google.android.exoplayer2.demo D/httpOpen: https://devimages.apple.com.edgekey.net/streaming/examples/bipbop_4x3/gear1/prog_index.m3u8
12-10 17:47:27.933 27663-27974/com.google.android.exoplayer2.demo D/httpOpen: https://devimages.apple.com.edgekey.net/streaming/examples/bipbop_4x3/gear1/fileSequence0.ts
12-10 17:47:28.483 27663-27974/com.google.android.exoplayer2.demo D/httpOpen: https://devimages.apple.com.edgekey.net/streaming/examples/bipbop_4x3/gear2/prog_index.m3u8
12-10 17:47:28.826 27663-27974/com.google.android.exoplayer2.demo D/httpOpen: https://devimages.apple.com.edgekey.net/streaming/examples/bipbop_4x3/gear2/fileSequence0.ts
12-10 17:47:29.697 27663-27974/com.google.android.exoplayer2.demo D/httpOpen: https://devimages.apple.com.edgekey.net/streaming/examples/bipbop_4x3/gear2/fileSequence1.ts
12-10 17:47:30.919 27663-27974/com.google.android.exoplayer2.demo D/httpOpen: https://devimages.apple.com.edgekey.net/streaming/examples/bipbop_4x3/gear2/fileSequence2.ts
12-10 17:47:32.016 27663-27974/com.google.android.exoplayer2.demo D/httpOpen: https://devimages.apple.com.edgekey.net/streaming/examples/bipbop_4x3/gear4/prog_index.m3u8
12-10 17:47:32.146 27663-27974/com.google.android.exoplayer2.demo D/httpOpen: https://devimages.apple.com.edgekey.net/streaming/examples/bipbop_4x3/gear4/fileSequence2.ts
12-10 17:47:33.879 27663-27974/com.google.android.exoplayer2.demo D/httpOpen: https://devimages.apple.com.edgekey.net/streaming/examples/bipbop_4x3/gear4/fileSequence3.ts
12-10 17:47:56.764 27663-27974/com.google.android.exoplayer2.demo D/httpOpen: https://devimages.apple.com.edgekey.net/streaming/examples/bipbop_4x3/gear1/fileSequence3.ts
12-10 17:48:10.963 27663-27974/com.google.android.exoplayer2.demo D/httpOpen: https://devimages.apple.com.edgekey.net/streaming/examples/bipbop_4x3/gear1/fileSequence3.ts
12-10 17:48:14.315 27663-27974/com.google.android.exoplayer2.demo D/httpOpen: https://devimages.apple.com.edgekey.net/streaming/examples/bipbop_4x3/gear1/fileSequence4.ts
12-10 17:48:26.027 27663-27974/com.google.android.exoplayer2.demo D/httpOpen: https://devimages.apple.com.edgekey.net/streaming/examples/bipbop_4x3/gear1/fileSequence4.ts
12-10 17:48:29.255 27663-27974/com.google.android.exoplayer2.demo D/httpOpen: https://devimages.apple.com.edgekey.net/streaming/examples/bipbop_4x3/gear1/fileSequence5.ts
12-10 17:48:29.905 27663-27974/com.google.android.exoplayer2.demo D/httpOpen: https://devimages.apple.com.edgekey.net/streaming/examples/bipbop_4x3/gear1/fileSequence6.ts
12-10 17:48:30.184 27663-27974/com.google.android.exoplayer2.demo D/httpOpen: https://devimages.apple.com.edgekey.net/streaming/examples/bipbop_4x3/gear4/fileSequence6.ts
12-10 17:48:34.417 27663-27974/com.google.android.exoplayer2.demo D/httpOpen: https://devimages.apple.com.edgekey.net/streaming/examples/bipbop_4x3/gear4/fileSequence7.ts
12-10 17:48:36.176 27663-27974/com.google.android.exoplayer2.demo D/httpOpen: https://devimages.apple.com.edgekey.net/streaming/examples/bipbop_4x3/gear4/fileSequence8.ts
12-10 17:48:57.586 27663-27974/com.google.android.exoplayer2.demo D/httpOpen: https://devimages.apple.com.edgekey.net/streaming/examples/bipbop_4x3/gear4/fileSequence9.ts
12-10 17:48:59.021 27663-27974/com.google.android.exoplayer2.demo D/httpOpen: https://devimages.apple.com.edgekey.net/streaming/examples/bipbop_4x3/gear4/fileSequence10.ts
12-10 17:49:17.884 27663-27974/com.google.android.exoplayer2.demo D/httpOpen: https://devimages.apple.com.edgekey.net/streaming/examples/bipbop_4x3/gear4/fileSequence11.ts
12-10 17:49:20.582 27663-27974/com.google.android.exoplayer2.demo D/httpOpen: https://devimages.apple.com.edgekey.net/streaming/examples/bipbop_4x3/gear4/fileSequence12.ts
12-10 17:49:25.207 27663-27974/com.google.android.exoplayer2.demo D/httpOpen: https://devimages.apple.com.edgekey.net/streaming/examples/bipbop_4x3/gear4/fileSequence13.ts

I added the Log.d() function in HttpDataSource.open() and HlsMediaChunk.load() to print out
the requested URIs. 
And I found this issue. 

The content that I used for test is this one:
"samples": [
{
"name": "Apple 4x3 basic stream",
"uri": "https://devimages.apple.com.edgekey.net/streaming/examples/bipbop_4x3/bipbop_4x3_variant.m3u8"
},
Exoplayer version:2.0.4
Device: Android 6.0

**Comment by aidynamic** [comment]
Update:
I set up a streaming server, and used the Exoplayer to request HLS media chunks from it.
Here is the log from the apache server. The first media chunk is downloaded from the server for two times. The adaption algorithm is the default AdaptiveVideoTrackSelection().
legend_240p0.ts, 240p is the video resolution, 0 is the sequence number.  

==> /var/log/apache2/access.log <==
 - - [11/Dec/2016:12:21:56 +0800] "GET /hls/legend/legend.m3u8 HTTP/1.1" 200 510 "-" "ExoPlayerDemo/2.0.4 (Linux;Android 6.0.1) ExoPlayerLib/2.0.4"
 - - [11/Dec/2016:12:21:56 +0800] "GET /hls/legend/legend_240p.m3u8 HTTP/1.1" 200 1046 "-" "ExoPlayerDemo/2.0.4 (Linux;Android 6.0.1) ExoPlayerLib/2.0.4"
 - - [11/Dec/2016:12:21:56 +0800] "GET /hls/legend/legend_240p0.ts HTTP/1.1" 200 705109 "-" "ExoPlayerDemo/2.0.4 (Linux;Android 6.0.1) ExoPlayerLib/2.0.4"
 - - [11/Dec/2016:12:21:59 +0800] "GET /hls/legend/legend_360p.m3u8 HTTP/1.1" 200 1046 "-" "ExoPlayerDemo/2.0.4 (Linux;Android 6.0.1) ExoPlayerLib/2.0.4"
 - - [11/Dec/2016:12:21:59 +0800] "GET /hls/legend/legend_360p0.ts HTTP/1.1" 200 924505 "-" "ExoPlayerDemo/2.0.4 (Linux;Android 6.0.1) ExoPlayerLib/2.0.4"
 - - [11/Dec/2016:12:22:01 +0800] "GET /hls/legend/legend_360p1.ts HTTP/1.1" 200 459205 "-" "ExoPlayerDemo/2.0.4 (Linux;Android 6.0.1) ExoPlayerLib/2.0.4"
 - - [11/Dec/2016:12:22:01 +0800] "GET /hls/legend/legend_360p2.ts HTTP/1.1" 200 482141 "-" "ExoPlayerDemo/2.0.4 (Linux;Android 6.0.1) ExoPlayerLib/2.0.4"
 - - [11/Dec/2016:12:22:02 +0800] "GET /hls/legend/legend_360p3.ts HTTP/1.1" 200 514665 "-" "ExoPlayerDemo/2.0.4 (Linux;Android 6.0.1) ExoPlayerLib/2.0.4"
 - - [11/Dec/2016:12:22:24 +0800] "GET /hls/legend/legend_360p4.ts HTTP/1.1" 200 555838 "-" "ExoPlayerDemo/2.0.4 (Linux;Android 6.0.1) ExoPlayerLib/2.0.4"
 - - [11/Dec/2016:12:22:25 +0800] "GET /hls/legend/legend_360p5.ts HTTP/1.1" 200 572945 "-" "ExoPlayerDemo/2.0.4 (Linux;Android 6.0.1) ExoPlayerLib/2.0.4"

When I changed to the RandomTrackSelection() for bitrate adaption, it seemed that most of the media chunks were requested for multiple times.


==> /var/log/apache2/access.log <==
- - [11/Dec/2016:12:30:20 +0800] "GET /hls/legend/legend.m3u8 HTTP/1.1" 200 510 "-" "ExoPlayerDemo/2.0.4 (Linux;Android 6.0.1) ExoPlayerLib/2.0.4"
 - - [11/Dec/2016:12:30:20 +0800] "GET /hls/legend/legend_240p.m3u8 HTTP/1.1" 200 1046 "-" "ExoPlayerDemo/2.0.4 (Linux;Android 6.0.1) ExoPlayerLib/2.0.4"
 - - [11/Dec/2016:12:30:20 +0800] "GET /hls/legend/legend_240p0.ts HTTP/1.1" 200 705109 "-" "ExoPlayerDemo/2.0.4 (Linux;Android 6.0.1) ExoPlayerLib/2.0.4"
 - - [11/Dec/2016:12:30:23 +0800] "GET /hls/legend/legend_360p.m3u8 HTTP/1.1" 200 1046 "-" "ExoPlayerDemo/2.0.4 (Linux;Android 6.0.1) ExoPlayerLib/2.0.4"
 - - [11/Dec/2016:12:30:23 +0800] "GET /hls/legend/legend_360p0.ts HTTP/1.1" 200 518384 "-" "ExoPlayerDemo/2.0.4 (Linux;Android 6.0.1) ExoPlayerLib/2.0.4"
 - - [11/Dec/2016:12:30:24 +0800] "GET /hls/legend/legend_240p0.ts HTTP/1.1" 200 705110 "-" "ExoPlayerDemo/2.0.4 (Linux;Android 6.0.1) ExoPlayerLib/2.0.4"
 - - [11/Dec/2016:12:30:25 +0800] "GET /hls/legend/legend_240p1.ts HTTP/1.1" 200 346593 "-" "ExoPlayerDemo/2.0.4 (Linux;Android 6.0.1) ExoPlayerLib/2.0.4"
 - - [11/Dec/2016:12:30:25 +0800] "GET /hls/legend/legend_240p2.ts HTTP/1.1" 200 374041 "-" "ExoPlayerDemo/2.0.4 (Linux;Android 6.0.1) ExoPlayerLib/2.0.4"
 - - [11/Dec/2016:12:30:26 +0800] "GET /hls/legend/legend_360p2.ts HTTP/1.1" 200 482141 "-" "ExoPlayerDemo/2.0.4 (Linux;Android 6.0.1) ExoPlayerLib/2.0.4"
 - - [11/Dec/2016:12:30:28 +0800] "GET /hls/legend/legend_360p3.ts HTTP/1.1" 200 514665 "-" "ExoPlayerDemo/2.0.4 (Linux;Android 6.0.1) ExoPlayerLib/2.0.4"
 - - [11/Dec/2016:12:30:48 +0800] "GET /hls/legend/legend_240p3.ts HTTP/1.1" 200 376862 "-" "ExoPlayerDemo/2.0.4 (Linux;Android 6.0.1) ExoPlayerLib/2.0.4"
 - - [11/Dec/2016:12:30:49 +0800] "GET /hls/legend/legend_240p4.ts HTTP/1.1" 200 416717 "-" "ExoPlayerDemo/2.0.4 (Linux;Android 6.0.1) ExoPlayerLib/2.0.4"
 - - [11/Dec/2016:12:30:49 +0800] "GET /hls/legend/legend_240p5.ts HTTP/1.1" 200 415589 "-" "ExoPlayerDemo/2.0.4 (Linux;Android 6.0.1) ExoPlayerLib/2.0.4"
 - - [11/Dec/2016:12:31:08 +0800] "GET /hls/legend/legend_360p5.ts HTTP/1.1" 200 572946 "-" "ExoPlayerDemo/2.0.4 (Linux;Android 6.0.1) ExoPlayerLib/2.0.4"
 - - [11/Dec/2016:12:31:09 +0800] "GET /hls/legend/legend_360p6.ts HTTP/1.1" 200 519365 "-" "ExoPlayerDemo/2.0.4 (Linux;Android 6.0.1) ExoPlayerLib/2.0.4"
 - - [11/Dec/2016:12:31:10 +0800] "GET /hls/legend/legend_360p7.ts HTTP/1.1" 200 489849 "-" "ExoPlayerDemo/2.0.4 (Linux;Android 6.0.1) ExoPlayerLib/2.0.4"
 - - [11/Dec/2016:12:31:29 +0800] "GET /hls/legend/legend_240p7.ts HTTP/1.1" 200 375546 "-" "ExoPlayerDemo/2.0.4 (Linux;Android 6.0.1) ExoPlayerLib/2.0.4"
 - - [11/Dec/2016:12:31:30 +0800] "GET /hls/legend/legend_240p8.ts HTTP/1.1" 200 633481 "-" "ExoPlayerDemo/2.0.4 (Linux;Android 6.0.1) ExoPlayerLib/2.0.4"
 - - [11/Dec/2016:12:31:32 +0800] "GET /hls/legend/legend_240p9.ts HTTP/1.1" 200 179837 "-" "ExoPlayerDemo/2.0.4 (Linux;Android 6.0.1) ExoPlayerLib/2.0.4"
 - - [11/Dec/2016:12:31:49 +0800] "GET /hls/legend/legend_360p9.ts HTTP/1.1" 200 234546 "-" "ExoPlayerDemo/2.0.4 (Linux;Android 6.0.1) ExoPlayerLib/2.0.4"
 - - [11/Dec/2016:12:31:49 +0800] "GET /hls/legend/legend_240p9.ts HTTP/1.1" 200 179837 "-" "ExoPlayerDemo/2.0.4 (Linux;Android 6.0.1) ExoPlayerLib/2.0.4"
 - - [11/Dec/2016:12:31:49 +0800] "GET /hls/legend/legend_240p10.ts HTTP/1.1" 200 390961 "-" "ExoPlayerDemo/2.0.4 (Linux;Android 6.0.1) ExoPlayerLib/2.0.4"
 - - [11/Dec/2016:12:31:50 +0800] "GET /hls/legend/legend_360p10.ts HTTP/1.1" 200 532713 "-" "ExoPlayerDemo/2.0.4 (Linux;Android 6.0.1) ExoPlayerLib/2.0.4"
 - - [11/Dec/2016:12:31:51 +0800] "GET /hls/legend/legend_240p10.ts HTTP/1.1" 200 390961 "-" "ExoPlayerDemo/2.0.4 (Linux;Android 6.0.1) ExoPlayerLib/2.0.4"
 - - [11/Dec/2016:12:31:51 +0800] "GET /hls/legend/legend_240p11.ts HTTP/1.1" 200 299781 "-" "ExoPlayerDemo/2.0.4 (Linux;Android 6.0.1) ExoPlayerLib/2.0.4"
 - - [11/Dec/2016:12:32:07 +0800] "GET /hls/legend/legend_360p11.ts HTTP/1.1" 200 421794 "-" "ExoPlayerDemo/2.0.4 (Linux;Android 6.0.1) ExoPlayerLib/2.0.4"
 - - [11/Dec/2016:12:32:07 +0800] "GET /hls/legend/legend_240p11.ts HTTP/1.1" 200 299781 "-" "ExoPlayerDemo/2.0.4 (Linux;Android 6.0.1) ExoPlayerLib/2.0.4"
 - - [11/Dec/2016:12:32:08 +0800] "GET /hls/legend/legend_240p12.ts HTTP/1.1" 200 361257 "-" "ExoPlayerDemo/2.0.4 (Linux;Android 6.0.1) ExoPlayerLib/2.0.4"
 - - [11/Dec/2016:12:32:09 +0800] "GET /hls/legend/legend_240p13.ts HTTP/1.1" 200 383441 "-" "ExoPlayerDemo/2.0.4 (Linux;Android 6.0.1) ExoPlayerLib/2.0.4"
 - - [11/Dec/2016:12:32:28 +0800] "GET /hls/legend/legend_240p14.ts HTTP/1.1" 200 377426 "-" "ExoPlayerDemo/2.0.4 (Linux;Android 6.0.1) ExoPlayerLib/2.0.4"
 - - [11/Dec/2016:12:32:29 +0800] "GET /hls/legend/legend_240p15.ts HTTP/1.1" 200 262181 "-" "ExoPlayerDemo/2.0.4 (Linux;Android 6.0.1) ExoPlayerLib/2.0.4"
 - - [11/Dec/2016:12:32:48 +0800] "GET /hls/legend/legend_360p15.ts HTTP/1.1" 200 373102 "-" "ExoPlayerDemo/2.0.4 (Linux;Android 6.0.1) ExoPlayerLib/2.0.4"
 - - [11/Dec/2016:12:32:49 +0800] "GET /hls/legend/legend_360p16.ts HTTP/1.1" 200 596821 "-" "ExoPlayerDemo/2.0.4 (Linux;Android 6.0.1) ExoPlayerLib/2.0.4"
 - - [11/Dec/2016:12:32:49 +0800] "GET /hls/legend/legend_360p17.ts HTTP/1.1" 200 280605 "-" "ExoPlayerDemo/2.0.4 (Linux;Android 6.0.1) ExoPlayerLib/2.0.4"

**Comment by aidynamic** [comment]
There may be something wrong with the function  getNextChunk() for HLS.
HlsChunkSource.java -> getNextChunk()

The problem happens at this block of code.
if (switchingVariant) {
        chunkMediaSequence = Util.binarySearchFloor(mediaPlaylist.segments,
            previous.startTimeUs, true, true) + mediaPlaylist.mediaSequence;
}
In my test, binarySearchFloor() sometimes cannot return the right sequence number for the next video chunk if a switch happens. 
For example, the sequence number of the previous chunk is 8.
If a switch happens, the returned sequence number for the next video chunk may remain at 8, and this may repeat for several times.
So, A video chunk may be downloaded for several times until it jumps out.

**Comment by AquilesCanta** [comment]
This is working as intended. As a matter of fact, when switching variants, the next loaded chunk should not introduce any new samples, ideally. This is due to the fact that the HLS spec does not require key frames to be provided at the start of the chunk.

Let's say we just load the next chunk. Any samples preceding the first key frame(which may be anywhere in the chunk) have to be discarded, as they cannot be decoded. If said samples have new content, you will perceive a gap in playback. Hope this made things clear. Other adaptive protocols, like DASH, don't present this inconvenient.

**Comment by ojw28** [comment]
Not only does the HLS spec not require segments to begin with key-frames, it doesn't require segment boundaries to be aligned across variants either. To switch variant without downloading any overlapping content, the spec would have to require both of these properties. Other adaptive streaming standards (i.e. commonly used DASH profiles, and also SmoothStreaming) do require these properties, and hence switching variants when using them is significantly more efficient than it is when using HLS.

We recommend using DASH for adaptive streaming. It's more efficient in quite a few ways, this being just one example.

**Comment by aidynamic** [comment]
@AquilesCanta @ojw28  Many thanks for your help! Your replies are insightful, and now I understand it.
