### ISSUE TITLE
java.lang.RuntimeException: failure code: -22

### ISSUE THREAD

**Issue by LucianWang** [google/ExoPlayer#2180]
01-02 05:18:32.707 E/AndroidRuntime(18389): java.lang.RuntimeException: failure code: -22
01-02 05:18:32.707 E/AndroidRuntime(18389): at android.media.MediaPlayer.invoke(MediaPlayer.java:677)
01-02 05:18:32.707 E/AndroidRuntime(18389): 	at android.media.MediaPlayer.getInbandTrackInfo(MediaPlayer.java:1973)
01-02 05:18:32.707 E/AndroidRuntime(18389): 	at android.media.MediaPlayer.scanInternalSubtitleTracks(MediaPlayer.java:2132)
01-02 05:18:32.707 E/AndroidRuntime(18389): 	at android.media.MediaPlayer.access$600(MediaPlayer.java:536)
01-02 05:18:32.707 E/AndroidRuntime(18389): 	at android.media.MediaPlayer$EventHandler.handleMessage(MediaPlayer.java:2479)
01-02 05:18:32.707 E/AndroidRuntime(18389): 	at android.os.Handler.dispatchMessage(Handler.java:102)
01-02 05:18:32.707 E/AndroidRuntime(18389): 	at android.os.Looper.loop(Looper.java:136)
01-02 05:18:32.707 E/AndroidRuntime(18389): 	at android.app.ActivityThread.main(ActivityThread.java:5011)
01-02 05:18:32.707 E/AndroidRuntime(18389): 	at java.lang.reflect.Method.invokeNative(Native Method)
01-02 05:18:32.707 E/AndroidRuntime(18389): 	at java.lang.reflect.Method.invoke(Method.java:515)
01-02 05:18:32.707 E/AndroidRuntime(18389): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:807)
01-02 05:18:32.707 E/AndroidRuntime(18389): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:623)
01-02 05:18:32.709 W/ActivityManager( 1623):   Force finishing activity readtv.ghs.tv/.activity.VodVideoActivity
In the r1.5.9 version is OK, and now to upgrade to r1.5.10 after this problem. I'm not sure why this is the reason.
I hope you can give me an answer as soon as possible, thank you

**Comment by andrewlewis** [comment]
This looks like an issue with MediaPlayer not ExoPlayer.
