### ISSUE TITLE
Gapless loop, multiple tracks in sync, capture audio from microphone

### ISSUE THREAD

**Issue by mateusgrb** [google/ExoPlayer#2184]
Hi, I'm developing an android app and I would like to know if I can implement the following requirements using ExoPlayer:
-Play multiple tracks at the same time in sync(they have the same beat)
-Play track in a gapless loop
-Capture audio from microphone and play it together with other tracks in some scenarios

I tried to do that with MediaPlayer but the syncing was not so accurate. Playing tracks in sync is the crucial feature here.

Do you think it's possible to implement these features with ExoPlayer?

**Comment by andrewlewis** [comment]
- Gapless playback should just work if the input media has the right metadata and you're using the default MediaCodecAudioRenderer (see this [blog post](https://medium.com/google-exoplayer/exoplayer-2-x-new-audio-features-cfb26c2883a#.rddn60fl6) for more information).
- For looping use LoopingMediaSource (see the [blog post on MediaSource composition](https://medium.com/google-exoplayer/exoplayer-2-x-mediasource-composition-6c285fcbca1f#.xzxs2k1sg)).

We don't have direct support for playing multiple tracks at the same time in sync, or handling any capture operations. These are not really in scope for a general-purpose media player. For playing multiple tracks in sync you likely need to mix the audio yourself before writing one stream to an AudioTrack. If you need to use ExoPlayer for reading media you could probably implement a custom audio renderer passed to each player which handles mixing and writing to the same AudioTrack (you'd need to handle receiving data from each player on its own playback thread, and then exposing the playback position from your mixed AudioTrack). This may or may not work and would likely get quite complicated, so the best solution is probably to implement a custom player using AudioTrack and the other low-level media APIs in the Android framework!
