### ISSUE TITLE
[Question] Is the HLS package part of the public API?

### ISSUE THREAD

**Issue by BoD** [google/ExoPlayer#2185]
I'm sorry, this is not really an issue, but a question.

I am currently in the need of implementing an HLS "parser" and I was wondering if I could consider that the classes in the `com.google.android.exoplayer2.source.hls` and `com.google.android.exoplayer2.source.hls.playlist` were part of the "public API" of ExoPlayer.  

By that I mean, that I can trust that my code can depend on it, and it should not break when new versions are released (except of course major versions).

**Comment by ojw28** [comment]
- Anything that's public is by definition part of the public API.
- We don't guarantee not to break the public API between versions (minor or major). We do of course don't break the public API just for the sake of it, either ;).
- Where we do make breaking changes, you can expect them to be in the form of compilation errors (e.g. a change to a method signature means your code no longer compiles). So they should be immediately obvious on upgrading and fairly easy for you to resolve.
- You can expect for us not to silently break things (e.g. leave a method signature unchanged but completely change what each variable means). So if you upgrade and your code does still compile, you can reasonably assume the APIs on which you depend were unchanged. Of course, this does not guarantee no bugs were introduced in the new version. We recommend thoroughly testing your application following taking of an upgrade.

**Comment by BoD** [comment]
Thanks a lot :)
