### ISSUE TITLE
SDK Location not found

### ISSUE THREAD

**Issue by lawloretienne** [google/ExoPlayer#2187]
I tried to clone this repo and then open the demo project in Android Studio, except it keeps throwing an error

`Error:SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.`

I checked the path set in the sdk.dir variable of local.properties and it is the correct path.  I don't have this issue when opening other projects i have cloned from Github.

How can i resolve this?

**Comment by AquilesCanta** [comment]
I have just cloned and imported the project and it worked just fine. You should ask in a general Q&A exchange. It's most likely some local config.

**Comment by RaisaLemishko** [comment]
@lawloretienne Hello, Etienne. 
I'm facing the same issue with this repo https://github.com/BionicAndr/Andr.2016.11  
How did you solve it? 
Thanks in andvance for help!

**Comment by lawloretienne** [comment]
I never solved the issue, but I do have a custom implementation of ExoPlayer in one of my repos
https://github.com/lawloretienne/Loop
