### ISSUE TITLE
[Question] Load Codec in to exoplayer

### ISSUE THREAD

**Issue by huongnv251291** [google/ExoPlayer#2190]
i get problem when play in multi driver because error in codec. Api 23 and above it can play normal but below 23 some driver got freeze. I know it's codec. Now i wan't to change video render and audio render to sw like ffmpeg how i can load it to exoplayer

**Comment by andrewlewis** [comment]
ExoPlayer has some extensions wrapping software decoders. To get started, follow the instructions in the extension README files: [ffmpeg extension README.md](https://github.com/google/ExoPlayer/blob/release-v2/extensions/ffmpeg/README.md), [vp9 extension README.md](https://github.com/google/ExoPlayer/blob/release-v2/extensions/vp9/README.md), etc.

The [demo app documentation](https://google.github.io/ExoPlayer/demo-application.html#including-extension-decoders) describes how to play your media in the demo app using the extensions, so you can follow those instructions to check you've built the extensions correctly.

If you're using SimpleExoPlayer in your app, pass `true` for [preferExtensionDecoders](https://github.com/google/ExoPlayer/blob/dca4d16/library/src/main/java/com/google/android/exoplayer2/SimpleExoPlayer.java#L127) to use extension renderers in preference to MediaCodec-based renderers.

Note: software video decoders are likely to be less efficient than the decoders in the platform, so you might want to use the extensions only on pre-API 23 builds.
