### ISSUE TITLE
Switching seamlessly between videos

### ISSUE THREAD

**Issue by michaelstrigy** [google/ExoPlayer#2192]
Hi,

I am trying to add a pretty simple ability to the exoplayer2 but can't seem to find any information on the subject.
The target is to be able to load several video streams together (all of which are createded and managed by me) and render only one of them at a given time. that mean to manage several parallel buffers and renderers and display the frame of one of them (seamlesly switching) while changing sources dynamically according to an internal logic. currently I can't seem to find a direction to follow:
should i add a new media source?
should i change the track selector?
or is the solutions in another place?

Thanks!

**Comment by ojw28** [comment]
I'm not sure I'd describe that as a simple use case. Sounds pretty complicated to me ;). It's not something we support directly. It likely is possible to customize ExoPlayer for this use case, but we're unable to provide guidance; sorry.
