### ISSUE TITLE
HLS support for H262 inside MPEG-TS container

### ISSUE THREAD

**Issue by barhom** [google/ExoPlayer#2195]
Can exoplayer support playing back H262 (mpeg2) video inside an MPEG-TS container served via HLS?

We are well aware that H262 (mpeg2) is not usually supported in Android devices. However, is it possible to use software decoders (FFmpeg?) to add support for this?

**Comment by ojw28** [comment]
- H262 in MPEG-TS is supported by ExoPlayer at the container level. The extractor has a [H262Reader](https://github.com/google/ExoPlayer/blob/release-v2/library/src/main/java/com/google/android/exoplayer2/extractor/ts/H262Reader.java)). I would expect this to work in the HLS case also, although I've never tried this.
- The device will still of course need an H262 decoder to decode the frames. If the device has one then playback should just work. If it doesn't, you'd need to bridge onto a software decoder. Bridging onto FFMPEG video decoders is not currently supported, and is tracked by https://github.com/google/ExoPlayer/issues/2159.
