### ISSUE TITLE
java.lang.VerifyError: com/google/android/exoplayer/MediaCodecTrackRenderer

### ISSUE THREAD

**Issue by LucianWang** [google/ExoPlayer#2196]
I use exoplayer and TextureView to play.M3u8 live streaming, in the Android 4.0.4 encountered this problem. Is the equipment does not support it? Or can only be api16 after the full support it? Please give me a reply as soon as possible, thank you very much.

01-01 08:12:58.861 E/AndroidRuntime( 3811): 	at readtv.ghs.tv.player.HlsRendererBuilder$AsyncRendererBuilder.onSingleManifest(HlsRendererBuilder.java:154)
01-01 08:12:58.861 E/AndroidRuntime( 3811): 	at readtv.ghs.tv.player.HlsRendererBuilder$AsyncRendererBuilder.onSingleManifest(HlsRendererBuilder.java:91)
01-01 08:12:58.861 E/AndroidRuntime( 3811): 	at com.google.android.exoplayer.util.ManifestFetcher$SingleFetchHelper.onLoadCompleted(ManifestFetcher.java:378)
01-01 08:12:58.861 E/AndroidRuntime( 3811): 	at com.google.android.exoplayer.upstream.Loader$LoadTask.handleMessage(Loader.java:245)
01-01 08:12:58.861 E/AndroidRuntime( 3811): 	at android.os.Handler.dispatchMessage(Handler.java:99)
01-01 08:12:58.861 E/AndroidRuntime( 3811): 	at android.os.Looper.loop(Looper.java:137)
01-01 08:12:58.861 E/AndroidRuntime( 3811): 	at android.app.ActivityThread.main(ActivityThread.java:4424)
01-01 08:12:58.861 E/AndroidRuntime( 3811): 	at java.lang.reflect.Method.invokeNative(Native Method)
01-01 08:12:58.861 E/AndroidRuntime( 3811): 	at java.lang.reflect.Method.invoke(Method.java:511)
01-01 08:12:58.861 E/AndroidRuntime( 3811): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
01-01 08:12:58.861 E/AndroidRuntime( 3811): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
01-01 08:12:58.861 E/AndroidRuntime( 3811): 	at dalvik.system.NativeStart.main(Native Method)
01-01 08:12:58.865 E/StatisticService( 1293): ** Activity appCrashed readtv.ghs.tv
01-01 08:12:58.866 W/ActivityManager( 1293):   Force finishing activity readtv.ghs.tv/.activity.HomeActivity

**Comment by AquilesCanta** [comment]
It's not clear to me what the issue is. I think you missed part of the stack trace. Please file a new issue including all the information required in the issue template. Read each item carefully, please.
