### ISSUE TITLE
How to load stream in the desired position?

### ISSUE THREAD

**Issue by Anton111111** [google/ExoPlayer#2197]
I have several qualities of streams (http). Can i start laod new stream and start play in position where current playing.

How i try to do it:
```
public void changeQuality(String uri) {

        this.oldPosition = exoPlayer.getCurrentPosition();
        this.oldState = exoPlayer.getPlayWhenReady();

        DataSource.Factory dataSourceFactory = new DefaultDataSourceFactory(context,
                userAgent, null);
        ExtractorsFactory extractorsFactory = new DefaultExtractorsFactory();
        MediaSource videoSource = new ExtractorMediaSource(Uri.parse(uri),
        dataSourceFactory, extractorsFactory, null, null);
        exoPlayer.prepare(videoSource);
}
```

And on onPlayerStateChanged i seek to old position:

```
    @Override
    public void onPlayerStateChanged(boolean playWhenReady, int playbackState) {
      
        if (playbackState == ExoPlayer.STATE_READY) {
            if (this.oldPosition > -1) {
                exoPlayer.seekTo(this.oldPosition);
                this.oldPosition = -1;
                exoPlayer.setPlayWhenReady(this.oldState);
                }
            }
        }
    }
```

But it show first frame than jump to old position. How i can don't show first frame and start showing from old position?

**Comment by ojw28** [comment]
You're probably using a media format that is not seekable. Please see the [supported formats page](https://google.github.io/ExoPlayer/supported-formats.html). If you want to seek to a non-zero position, you need to use a container format that supports seeking.

**Comment by Anton111111** [comment]
But it jump to needed position after first frame. I use MP4.

**Comment by Anton111111** [comment]
I'm sorry but I feel like an idiot. I need to use exoPlayer.prepare(videoSource, false, true); instead of exoPlayer.prepare(videoSource);

**Comment by ojw28** [comment]
Hah, yes, I was just writing a comment suggesting you tried that :). Glad you solved the issue!
