### ISSUE TITLE
Exoplayer 2 - play multiple sounds/audio simultaneously (using MergingMediaSource?)

### ISSUE THREAD

**Issue by Pepa112** [google/ExoPlayer#2200]
I'm using in my app several instances of `SimpleExoPlayer` to play audio file (Wav file). I want play all these files simultaneously. Now there is some small gap between these files. Is it possible to have only one instance of `SimpleExoPlayer` with more sounds files? 

I tried use `MergingMediaSource` but it's now working. It's playing only one Wav file (not all).

Code:

            MediaSource ms = new MergingMediaSource(audioSources.toArray(new MediaSource[audioSources.size()]));
            mMediaPlayerTracker1.addListener(myExoPlayerEventListener);
            mMediaPlayerTracker1.prepare(ms);

            //Adding MediaSource to the ArrayList
            audioSources.add(new ExtractorMediaSource(
                        Uri.fromFile(new File(path)), mediaDataSourceFactory, defaultExtractorsFactory,
                        mainHandler, exoEventListener));

Thanks for help or advice!

**Comment by nashxena** [comment]
Any thing on this? I have a similar problem. Thanks for any suggestions/clues here.

**Comment by ojw28** [comment]
To achieve this you'd probably need to be mixing the audio prior to feeding it into a single AudioTrack instance. This is not a use case we currently support, sorry!

**Comment by xdestiny110** [comment]
I have achieve this. I generate an audio file that contain 4 audio tracks. Then I override `buildAudioRenderers` in `DefaultRenderersFactory`, and `getMediaClock` in `MediaCodecAudioRenderer`. Also I implement `TrackSelector`. In that way I can play all audio track simultaneously.
