### ISSUE TITLE
Allow specifying a custom cacheKey to ExtractorMediaSource

### ISSUE THREAD

**Issue by ojw28** [google/ExoPlayer#2201]
Spun out of @scroozer's comments on #1705. Looks like it's just a matter of allowing the key to be passed through the constructor and down into ExtractorMediaPeriod where the load DataSpecs get instantiated?

**Comment by scrdev** [comment]
@ojw28 Yes since ExtractorMediaSource doesnt have any argument for the key to be used when instantiating DataSpec, it looks like ExtractorMediaPeriod is simply passing an sha1 hash of the uri as key when creating the DataSpec.

**Comment by ojw28** [comment]
This was fixed by the change ref'd above.
