### ISSUE TITLE
ExoPlayer v2. Display multiple videos on one screen android device.

### ISSUE THREAD

**Issue by leodaddydev** [google/ExoPlayer#2203]
I met one problem screen multiplayer on 1 device with Exoplayer and I don't know how to do this . So i need a help. plz teach me how to do it or a example.
Thanks for support.

**Comment by ojw28** [comment]
StackOverflow is a more appropriate place to ask general questions. This tracker is for issues and feature requests.

**Comment by leodaddydev** [comment]
OK. Thanks ojw28 . i'll try in StackOverflow.
