### ISSUE TITLE
unable to play "Dizzy" video from demo app on OTT TV Box

### ISSUE THREAD

**Issue by shanestap** [google/ExoPlayer#2204]
Description:  Building the demo app and deploying to this android tv device, the player shows a black screen with controls.
Reproduced with the demo app:  using the latest demo app, playback of many videos shows the same issue.  Specifically the Misc/Dizzy option.
Link to content:  most of the content in the demo app
ExoPlayer version:  latest (10 days ago)
Device:
  OTT TV Box T95N
  Android 5.1.1
  reproducible every time
Debug output after playing dizzy:

I/ExoPlayerImpl: Init 2.0.4
D/EventLogger: state [0.20, true, I]
I/Choreographer: Skipped 54 frames!  The application may be doing too much work on its main thread.
D/EventLogger: state [0.44, true, B]
D/EventLogger: sourceInfo [periodCount=1, windowCount=1
D/EventLogger:   period [?]
D/EventLogger:   window [?, false, false]
D/EventLogger: ]
D/EventLogger: loading [true]
W/NalUnitUtil: Unexpected aspect_ratio_idc value: 254
D/EventLogger: sourceInfo [periodCount=1, windowCount=1
D/EventLogger:   period [25.00]
D/EventLogger:   window [25.00, true, false]
D/EventLogger: ]
W/VideoCapabilities: Unsupported mime video/mpeg2
W/VideoCapabilities: Unsupported mime video/vc1
W/Utils: could not parse long range '1-'
W/VideoCapabilities: Unsupported mime video/wvc1
W/Utils: could not parse long range '1-'
W/VideoCapabilities: Unsupported mime video/wmv3
W/VideoCapabilities: Unsupported mime video/mjpeg
W/AudioCapabilities: Unsupported mime audio/aac-adif
W/AudioCapabilities: Unsupported mime audio/aac-latm
W/AudioCapabilities: Unsupported mime audio/adts
W/AudioCapabilities: Unsupported mime audio/adpcm-ima
W/AudioCapabilities: Unsupported mime audio/adpcm-ms
W/AudioCapabilities: Unsupported mime audio/alac
W/AudioCapabilities: Unsupported mime audio/wma
W/AudioCapabilities: Unsupported mime audio/wmapro
W/AudioCapabilities: Unsupported mime audio/ape
W/AudioCapabilities: Unsupported mime audio/truehd
W/AudioCapabilities: Unsupported mime audio/ffmpeg
W/VideoCapabilities: Unsupported mime video/x-vnd.on2.vp6
W/VideoCapabilities: Unsupported mime video/x-vnd.on2.vp6a
W/VideoCapabilities: Unsupported mime video/x-vnd.on2.vp6f
W/VideoCapabilities: Unsupported mime video/rm
W/VideoCapabilities: Unsupported mime video/wmv2
W/VideoCapabilities: Unsupported mime video/wmv1
W/AudioCapabilities: Unsupported mime audio/ac3
W/AudioCapabilities: Unsupported mime audio/eac3
W/AudioCapabilities: Unsupported mime audio/mpeg-L2
W/AudioCapabilities: Unsupported mime audio/dtshd
D/EventLogger: Tracks [
D/EventLogger:   Renderer:0 [
D/EventLogger:     Group:0, adaptive_supported=N/A [
D/EventLogger:       [ ] Track:0, id=2, mimeType=video/avc, res=480x360, supported=NO_EXCEEDS_CAPABILITIES
D/EventLogger:     ]
D/EventLogger:   ]
D/EventLogger:   Renderer:1 [
D/EventLogger:     Group:0, adaptive_supported=N/A [
D/EventLogger:       [X] Track:0, id=1, mimeType=audio/mp4a-latm, channels=2, sample_rate=44100, language=und, supported=YES
D/EventLogger:     ]
D/EventLogger:   ]
D/EventLogger: ]
I/OMXClient: Using client-side OMX mux.
D/EventLogger: audioEnabled [9.20]
D/EventLogger: positionDiscontinuity
I/omx_core: OMX_Init 66 gInitCount=1
V/AML_all_components: --------------------------------
                      ARCH = arm
                      author:aml.sh multi-media team
                      branch name:   * jb-mr1-amlogic
                      git version:   011dae5a4bcb3e3676f392664ac0bf74db6cca1b 
                      last changed:  Date: Sun Dec 27 20:57:19 2015 +0800
                      build-time:     Thu Jan 7 14:47:14 CST 2016
                      build-name:     jintao.xu
                      uncommitted-file-num:0
                      cd /mnt/fileroot/jintao.xu/5.1.p201
                      hostname droid07
                      --------------------------------
V/OmxComponentManagerImpl: loadLibrary:228 Loading OMX library libOmxVideo.so.
E/omx_video: amvenc_avc open failed!set default instance number as 1,ret=-1,Permission denied(13)
I/omx_core: Core library has 11 components
E/OMXMaster: A component of name 'OMX.google.h264.decoder' already exists, ignoring this one.
E/OMXMaster: A component of name 'OMX.google.alac.decoder' already exists, ignoring this one.
I/SoftAAC2: limiting to stereo output
I/SoftAAC2: Reconfiguring decoder: 0->44100 Hz, 0->2 channels
D/EventLogger: audioDecoderInitialized [9.26, OMX.google.aac.decoder]
D/EventLogger: audioFormatChanged [9.26, id=1, mimeType=audio/mp4a-latm, channels=2, sample_rate=44100, language=und]
I/AudioTrack: set(): 0xab4ed8d8 streamType -1, sampleRate 44100, format 0x1, channelMask 0x3, frameCount 15052, flags #0, notificationFrames 0, sessionId 0, transferType 3
V/RenderScript: 0xab4ecc88 Launching thread(s), CPUs 4
D/EventLogger: audioSessionId [79]
D/EventLogger: state [9.41, true, R]
D/EventLogger: loading [false]
D/EventLogger: state [34.40, true, E]

**Comment by ojw28** [comment]
I think this is fixed already (within the last 10 days).
