### ISSUE TITLE
HLS webVtt subtitle is out of sync on v2.1.0

### ISSUE THREAD

**Issue by ofuwape** [google/ExoPlayer#2208]
**Description**
The HLS webvtt subtitle display is out of sync on v2.1.0 but plays fine on v1.5.13 and the Safari Browser.

**Devices**
I get this same issue on the following devices:
- HTC Nexus 9 (Android 7.0 API 24) {Real Device}
- Nexus 6 (Android 7.0 API 24) {Virtual Device}
- Nexus 6 (Android 6.0 API 23) {Virtual Device}

**Video URL:** https://cdn.curiositystream.com/system/Encoding/HW/000/000/685/670/storyhouse_insidethearizona_rev3_preview-3ea65eb4706954bfe635f261c129a4dd41f92dbb_v2.m3u8

**Comment by ojw28** [comment]
We'll merge a fix for this shortly, thanks!

**Comment by ojw28** [comment]
This is fixed on `dev-v2`. We will likely do a bug-fix-only `2.1.1` release next week.
