### ISSUE TITLE
Does player supports 360 VR videos?

### ISSUE THREAD

**Issue by ronit-kadwane** [google/ExoPlayer#2211]
I checked this question [](https://github.com/google/ExoPlayer/issues/432) but no satisfactory answer, So can you please inform does this player supports 360vr videos?
If yes then please provide demo example.

**Comment by superbderrick** [comment]
see this repo.
https://github.com/googlevr/gvr-android-sdk
they provide similar component with exoplayer (sdk-simplevideowidget).
