### ISSUE TITLE
DrmToday with exoplayer 

### ISSUE THREAD

**Issue by afrostreambahri** [google/ExoPlayer#2215]
Hello
i can't read video with drmtoday 

what should i put on drmKeyRequestProperties?

i try with is but it's not working 

 ArrayList<String> drmKeyRequestPropertiesList = new ArrayList<>();
                JSONObject js=new JSONObject ();
                try {
                    js.put("userId", "12345");
                    js.put("sessionId", "12345");
                    js.put("merchant", "afrostream");
                }catch ( Exception ee)
                {
                    ee.printStackTrace();
                }
  drmKeyRequestPropertiesList.add("dt-custom-data");

               drmKeyRequestPropertiesList.add(js.toString());
drmKeyRequestProperties = drmKeyRequestPropertiesList.toArray(new String[0]);

                Sample smp=new UriSample( name,  drmSchemeUuid,  drmLicenseUrl,          drmKeyRequestProperties,  false,uri,extension) ;
                Intent nb=smp.buildIntent(getApplicationContext());
                startActivity(nb);

**Comment by ojw28** [comment]
We're not particularly familiar with DrmToday. I'd suggest asking them for assistance on this, since what properties to set is dependent on what their requirements, not on ExoPlayer.
