### ISSUE TITLE
Language of the Format class.

### ISSUE THREAD

**Issue by ChernyshovYuriy** [google/ExoPlayer#2216]
Hi colleagues,
In the latest version 2.1.0 I found that "language" field of the Format class in some cases get its value from MetadataUtil's class field:
```
String LANGUAGE_UNDEFINED = "und"
```
and sometimes its value is null.
It introduced inconsistency for the default / undefined / unknown value and brakes client side logic, when comparator compares two objects of Format type and gives wrong result just because one of them has "und" value while another one has null value.
It would be more robust and less client side affected when there will be a single, public accessible constant which will describe default / unknown /  unavailable / etc .. value of the language.
Probably, same approach would be helpful for other fields.

**Comment by AquilesCanta** [comment]
In my humble opinion, there might exist a scenario where not present is not the same as undefined. I would rather consider having a method utility isLanguageDefined() or similar that handles this for you, if needed. I wouldn't normalize this before the application level. But I guess it's open for discussion. @andrewlewis , @ojw28, @erdemguven  ?

**Comment by ChernyshovYuriy** [comment]
Yes, I forced to implement such normalization now because it broke comparator logic.
In anyways, there must be some public constant available because on application level I have no idea what "und" means.

**Comment by ojw28** [comment]
As @AquilesCanta notes, there's a difference between the media explicitly stating the language is undetermined ("und") and the media not saying anything about the language at all (null). I think it's correct that these cases are distinguished by the language field being set differently.

"und" is a well defined language code, and there are other special codes such as "mul" and "mis". See [here](https://en.wikipedia.org/wiki/ISO_639) for more details. Android platform APIs such as [Locale](https://developer.android.com/reference/java/util/Locale.html) also make use of it. So I don't think "und" deserves a public constant unless we also add constants for all other language codes too, and I'm not sure we really need to do that.

**Comment by ChernyshovYuriy** [comment]
Thank you guys for clarifications with standards!
