### ISSUE TITLE
Audio won't play on some devices

### ISSUE THREAD

**Issue by boywithk9** [google/ExoPlayer#2217]
*** PLEASE DO NOT IGNORE THIS ISSUE TEMPLATE ***

We recently updated our apps using Exoplayer to play 3 simultaneous audio tracks. The apps work as expected on all our test devices, and for most users.

However, since releasing the updates yesterday, we've received two reports from users who say the audio does not play since they installed the update. One user is using a Samsung S4 (SPH-L720T) and Android 5.0.1. The other user is using an LG G3 (LG-D855) with Android 5.0. 

We are not able to reproduce the issue on any of our test devices. I'll email you a link to the app.

We are using Exoplayer 2.0.4.

**Comment by ojw28** [comment]
We're unable to offer support debugging individual applications, sorry. If you uncover a specific ExoPlayer issue during your own debugging, please provide detailed repo steps, ideally with our demo app or a modification of it to which you can make the source code available.
