### ISSUE TITLE
Custom TrackSelection Helper Class

### ISSUE THREAD

**Issue by ram992** [google/ExoPlayer#2220]
Hello,

Can I get some help on how to Customize the TrackSelection Helper Class,
cause I want to show the quality selection not as a popup/dialog but as a part of mediaController,

For now I have modified my mediaController class( and layout ) to call the track selection helper class on the click of image on the controller itself , but it displays the tracks in checkedList (android default one).

I have searched the web for this kind of implementation, but I could not find one, I guess that it is very easy as there is no question regarding this thing. 

Few more details : I want to fill the tracks in a grid kind of layout  and also want the random adaptation feature, 

So I have started a new Issue (rather a question)  to know the answer

**Comment by ram992** [comment]
Hello any help on this one

**Comment by ojw28** [comment]
This is a question about building Android user interfaces. It's not particularly ExoPlayer specific, and falls outside the scope of this issue tracker. Sorry.
