### ISSUE TITLE
Unable to play videos from Application's Movie directory using exoplayer 2.0

### ISSUE THREAD

**Issue by falaksevak** [google/ExoPlayer#2221]
```
videoPreview.setPlayer(ViewUtils.initializeVideoPlayer(getContext()));
DataSource.Factory dataSourceFactory = new DefaultDataSourceFactory(getContext(), Util.getUserAgent(getContext(), APP_NAME));
ExtractorsFactory extractorsFactory = new DefaultExtractorsFactory();
MediaSource videoSource = new ExtractorMediaSource(Uri.parse(mVideoFilePath), dataSourceFactory, extractorsFactory, new Handler(), null);
mVideoPlayer.prepare(videoSource);
```

mVideoPath in the above snippet is: 
```/storage/emulated/0/Android/data/com.ic/files/Movies/MP4_-595253706.mp4```

exoplayer is not able to play the video. There is no exception thrown either. Is this a bug or is my setup missing something?

**Comment by ojw28** [comment]
The ExoPlayer demo app works fine for playing content from local directories, so I think this is likely to be an issue with your code. I'd suggest you try reproducing with the demo app, and filing an issue with specific reproduction steps if you're able to recreate the issue there.

A few other things to keep in mind:
- You may need to be careful with URI encoding/escaping when the URI contains underscores, as is the case here. You might want to try playing a file without any underscores in it to see if that works. That would indicate an encoding/escaping issue.
- You may need to request the READ_EXTERNAL_STORAGE permission at runtime, depending on what API level you're targeting. The demo app does this [here](https://github.com/google/ExoPlayer/blob/r2.1.0/demo/src/main/java/com/google/android/exoplayer2/demo/PlayerActivity.java#L317).
