### ISSUE TITLE
Is there a visualizer library that's compatible with ExoPlayer?

### ISSUE THREAD

**Issue by chenshuiluke** [google/ExoPlayer#2222]
As the title asks, is there a visualizer library that's compatible with ExoPlayer?

**Comment by ojw28** [comment]
I'm not aware of any.

You could build one on top of Android's standard [Visualizer](https://developer.android.com/reference/android/media/audiofx/Visualizer.html) API, passing the audio session ID being used by ExoPlayer. If using SimpleExoPlayer you can query the audio session ID using [SimpleExoPlayer.getAudioSessionId](https://github.com/google/ExoPlayer/blob/r2.1.0/library/src/main/java/com/google/android/exoplayer2/SimpleExoPlayer.java#L398), and also listen to changes to the ID using [SImpleExoPlayer.setAudioDebugListener](https://github.com/google/ExoPlayer/blob/r2.1.0/library/src/main/java/com/google/android/exoplayer2/SimpleExoPlayer.java#L439).

It's probably also possible to modify ExoPlayer to add direct hooks on which a Visualizer could be built. We don't provide any hooks currently, however.
