### ISSUE TITLE
`getCurrentPosition()` returning incorrect value which is larger than video duration

### ISSUE THREAD

**Issue by ashiagr** [google/ExoPlayer#2224]
Hi

I'm running ExoPlayer r2.1.0 on Nexus 5x with Android 7.0

When I play [this HLS video ](https://link-removed.m3u8), the playback position displayed is very large as if its some elapsed time from a clock. Here's a screenshot: http://imgur.com/VReQ5ws. Because of this the seek bar position is not updated as current position is larger than video duration.

The issue is reproducible in the Exoplayer release-v2 branch demo app for above video. Just replace any HLS video link inside media.exolist.json with above video link.

Any ideas on why this happens and how we can eliminate it?

Thanks!

**Comment by ojw28** [comment]
This happens for on-demand content that includes EXT-X-PROGRAM-DATE-TIME tags. The sample timestamps are (possibly correctly) grounded by program-date-time in this case, but the timeline still thinks the start of the media is at timestamp 0. Hence the huge numbers. We'll take a look.

**Comment by ojw28** [comment]
This is fixed on the `dev-v2` branch. The fix is a little. . .strange, but hopefully it'll do the trick.

**Comment by ashiagr** [comment]
Great! Thanks for a quick response. Will test it out.

**Comment by manishvwynk** [comment]
I have take the fix for it but still facing the issue .
