### ISSUE TITLE
Any code style for contributing ExoPlayer

### ISSUE THREAD

**Issue by yqritc** [google/ExoPlayer#2225]
Hi,

Is there any code style file for ExoPlayer like the following?   
(Android framework development codestyle)
https://android.googlesource.com/platform/development/+/master/ide/intellij/codestyles/AndroidStyle.xml

I want to send PR, but I couldn't find any.
It would be very helpful if there is one.

thanks!

**Comment by ojw28** [comment]
We roughly adhere to the [Google Java style guide](https://google.github.io/styleguide/javaguide.html). You may also find [this](https://github.com/google/styleguide) useful. The code across the project is pretty consistent, so I'd say the best style guide is the code that's already there :).
