### ISSUE TITLE
Only audio plays on certain devices (DASH only)

### ISSUE THREAD

**Issue by AndrewJack** [google/ExoPlayer#2228]
**- A description of the issue.**
Playing the DASH stream below does not play on certain devices. 
Demo player outputs "Media includes video tracks, but none are playable by this device".
Reproduced on Samsung SM-G920F

**- Steps describing how the issue can be reproduced, ideally in the ExoPlayer
  demo app.**

Play the below links on a Samsung SM-G920F

- HLS will play fine
- DASH will display "Media includes video tracks, but none are playable by this device"

**- A link to content that reproduces the issue.**
https://d2jyv85kc4p0re.cloudfront.net/ABtEOrCRSOSDDlcekhkSCA/manifest.mpd
https://d2jyv85kc4p0re.cloudfront.net/ABtEOrCRSOSDDlcekhkSCA/manifest.m3u8

**- The version of ExoPlayer being used.**
r2.0.4

**- The device(s) and version(s) of Android on which the issue can be reproduced,
  and how easily it reproduces.**
Samsung SM-G920F - HLS works, but DASH doesn't 
Nexus 6p - HLS and DASH streams work 

**- A bug report taken from the device just after the issue occurs, attached as a
  file. A bug report can be captured using "adb bugreport". Output from "adb
  logcat" or a log snippet is not sufficient.**
[dash-bug.txt](https://github.com/google/ExoPlayer/files/661619/dash-bug.txt)

**Comment by ojw28** [comment]
This is fixed already in r2.1.0, to the extent that it's possible. If playback works with r2.1.0, then problem solved. If playback still fails with r2.1.0 then the device simply isn't capable of decoding 1080p (this is probably not the case for the device in question).

Note that it's more usual for different bitrate streams to also be encoded at different resolutions when creating DASH content, so as to better support low end devices. There definitely exist many lower end Android devices that cannot allocate video buffers large enough for 1080p content. If you're producing this content, you may wish to consider this and adjust your content accordingly.

**Comment by BorislavKamenov** [comment]
Hello folks. I've experienced the same problem, actually two problems. 

**To reproduce the bug you can use the follow link:**
http://box.tivi.bg/c/cnn

**That is the problem**

- on Samsung Galaxy S4 Lollipop 5.0.1 when I play the link only audio runs and shows a toast:
_Media includes video tracks, but none are playable by this device_  

- on AndroidTV Emulator Marshmallow when I play the link only video runs and shows a toast:
_Media includes audio tracks, but none are playable by this device_  

Logcat from Samsung Galaxy S4:
http://prntscr.com/e6qd85

I'm using **r2.2.0** of Exoplayer on both devices

Really strange. Do someone has any idea? 

Thanks

**Comment by BorislavKamenov** [comment]
Hello folks! I've experienced the same problem, actually two similar problems.

**To reproduce use this link (MPEG-4):**
http://box.tivi.bg/c/cnn
 
**What is the problem:**

- on AndroidTV Emulator Marshmallow the video start to play but audio missing and shows this message:
_Media includes audio tracks, but none are playable by this device_

- on Samsung Galaxy S4 Lollipop 5.0.1 the audio start to play but video missing and shows toast:
_Media includes video tracks, but none are playable by this device_

**Logcat when start to play on Samsung device**
http://prntscr.com/e6qd85

Really strange problem. Do someone has any idea? 

Thanks.

**Comment by andrewlewis** [comment]
Decoding the video stream requires an MPEG-2 decoder. It seems the Samsung Galaxy S4 does not declare support for this format (hence the `supported=NO_UNSUPPORTED_TYPE` logging).

See the [supported media formats page](https://developer.android.com/guide/topics/media/media-formats.html) and the [CDD](https://source.android.com/compatibility/cdd.html) for information on the minimum video decoding capabilities you can rely on. Android TVs are 'strongly recommended' to have MPEG-2 decoders, but emulators often have poor support for media so it is best to test on real devices.
