### ISSUE TITLE
HLS DVR Support

### ISSUE THREAD

**Issue by jayachandrak** [google/ExoPlayer#223]
Hi All,
 
i am new to Exo player i have tried playing HLS DVR playlist which is not working 

please suggest me is it possible with Exo player

Thanks

**Comment by ojw28** [comment]
- If you're asking about HLS support in general, it's being developed in the dev-hls branch. If you look at the demo app in that branch, you'll see there are some example HLS streams that are playable, and should serve as a guide as to how you can play your own.
- If you're asking specifically about the ability to seek within the live window of HLS DVR streams, your request is a duplicate of #87.
