### ISSUE TITLE
ExoPlayer 2 How can I get audio/subtitle streams info and switch them at runtime?

### ISSUE THREAD

**Issue by personshelldon** [google/ExoPlayer#2230]
Hello, I need to implement simple track selection function during playing video files (audio and subtitle). Can I get this working with ExoPlayer and if yes - how? I can not find any documentation about this type of problem. Also, I need to show simple track info before user switches the track (language/name of the track). Thanks in advance for any help.

**Comment by ojw28** [comment]
The [demo app](https://github.com/google/ExoPlayer/tree/r2.1.0/demo) already does this. I suggest you take a look at it to see how it works.
