### ISSUE TITLE
Problem with exo-player 2.1.0 and subtitles

### ISSUE THREAD

**Issue by laurafuente** [google/ExoPlayer#2232]
Hi,
I've been trying to show the different subtitles of the stream "https://devimages.apple.com.edgekey.net/streaming/examples/bipbop_16x9/bipbop_16x9_variant.m3u8" but I'm not able to show them.

I'm using the demo application at the HLS section with the Apple 16x9 basic stream file

Regards

**Comment by ojw28** [comment]
Please see #2208. This is fixed in r2.1.1, which we just pushed (~5 minutes ago :)).

**Comment by laurafuente** [comment]
Thanks :)
