### ISSUE TITLE
HLS Video Scaling

### ISSUE THREAD

**Issue by Guro** [google/ExoPlayer#224]
Hello, i need to stretch the video to fill the screen on hls stream.

Currently as i have seen by default inside HlsRendererBuilder.java scaling mode is set to:
MediaCodec.VIDEO_SCALING_MODE_SCALE_TO_FIT  (documentation: "The content is scaled to the surface dimensions")
but this option doesn't stretches the video to full screen, any suggestions how this can be achieved?

Thanks

**Comment by bagusflyer** [comment]
I have the similar question (I want to stretch the video to its width). The event is not even called.

**Comment by Guro** [comment]
for me the event was called, just comment this line:
surfaceView.setVideoWidthHeightRatio(height == 0 ? 1 : (pixelWidthHeightRatio * width) / height);

**Comment by ojw28** [comment]
Yes. That's right. Alternatively (and slightly cleaner) you can just use SurfaceView directly, rather than using VideoSurfaceView (the whole point of this class is to be able to match the video's aspect ratio, so given you don't want to do this, you can just use SurfaceView directly).
