### ISSUE TITLE
SimpleExoPlayer work with SimpleExoPlayerView

### ISSUE THREAD

**Issue by darktiny** [google/ExoPlayer#2240]
I want to get video's size through `SimpleExoPlayer.VideoListener`, then change `SimpleExoPlayerView`'s resizeMode dynamically. Currently it's impossible.

Here's the code

```java
SimpleExoPlayer player;
SimpleExoPlayerView playerView;
VideoListener listener;

...

playerView.setPlayer(player);  // will call player's setVideoListener
player.setVideoListener(listener) // will replace the previous one
```

since `SimpleExoPlayer`'s `VideoListener` is not exposed, there's no way to reach the goal except reflection

ExoPlayer version: 2.1.1

**Comment by lioun1729** [comment]
resizeMode means resolution shows user in device monitor?

or video frame?

if the latter, I think video frame's size is dependent on encoder

so it can't change

It is only my opinion, other person comment please if i was wrong about this issue

**Comment by ojw28** [comment]
- As it happens there's also `SimpleExoPlayer.setVideoDebugListener`, which receives changes in the video size as well. It's not really intended to be used this way, but you could probably use it to do what you want.
- I can't really think of a valid reason for setting the resize mode dynamically; it doesn't sound right. Can you explain what you're trying to achieve? If you really do need to do this then it's likely we just need to add another resize mode that does what you need directly, so that you don't have to mess about changing it dynamically.

**Comment by darktiny** [comment]
@ojw28 What I need is `centerCrop` resize mode just like android's `ImageView`.

**Comment by ojw28** [comment]
I don't think the approach in your pull request is the best way to achieve this. I have a feeling it might not always work properly, but I don't have any hard data confirming this yet.

In any case, if you're using `SimpleExoPlayer` and `SimpleExoPlayerView` in their default configuration (i.e. the video is being rendered to a `SurfaceView`), then you should use [`SimpleExoPlayer.setVideoScalingMode`](https://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/SimpleExoPlayer.html#setVideoScalingMode-int-) to achieve this. The value you need to pass is `C. VIDEO_SCALING_MODE_SCALE_TO_FIT_WITH_CROPPING`. You should set the `resizeMode` of the `SimpleExoPlayerView` to `fit`.

**Comment by darktiny** [comment]
@ojw28 I have tried your advice, it doesn't work. 

```java
     /**
     * The content is scaled, maintaining its aspect ratio, the whole
     * surface area is used, content may be cropped.
     * <p class=note>
     * This mode is only suitable for content with 1:1 pixel aspect ratio as you cannot
     * configure the pixel aspect ratio for a {@link Surface}.
     * <p class=note>
     * As of {@link android.os.Build.VERSION_CODES#N} release, this mode may not work if
     * the video is {@linkplain MediaFormat#KEY_ROTATION rotated} by 90 or 270 degrees.
     */
    public static final int VIDEO_SCALING_MODE_SCALE_TO_FIT_WITH_CROPPING = 2;
```

**Comment by ojw28** [comment]
What does "doesn't work" mean exactly? It should work. Setting `resizeMode` to `fit` should make the view the correct size at least. What are you seeing being drawn into the view if not cropped video?

**Comment by darktiny** [comment]
@ojw28 just video with black edges

**Comment by ojw28** [comment]
`resizeMode` actually needs setting to `fill` rather than `fit`. I then see expected behavior on Pixel, but not on the emulator. Does it work for you?

**Comment by darktiny** [comment]
@ojw28 it works, thanks for your help
