### ISSUE TITLE
Track selection in a HLS stream

### ISSUE THREAD

**Issue by AntonAndev** [google/ExoPlayer#2241]
Hello, I have a question. I configured a HLS stream on media server with 2 tracks:
1. For high bitrate video and audio
2. For low bitrate only audio

Now my app uses ExoPlayer library 2.1.0. Track selection doesn't work, app uses only first track, in bad network conditions app goes to buffering or error state and doesn't select a second track. Tried the same stream in my iOS app with AVPlayer class, it selects second track successfully. What is wrong with usage of SimpleExoPlayer in my app?

```
private static final DefaultBandwidthMeter BANDWIDTH_METER = new DefaultBandwidthMeter();
private DefaultTrackSelector trackSelector;
private DataSource.Factory dataSourceFactory;
private Handler mainHandler;
```

```
@Override
protected void onCreate(Bundle savedInstanceState) {      
// some other code  
       dataSourceFactory = new DefaultDataSourceFactory(this, Util.getUserAgent(this, userAgent), BANDWIDTH_METER);
       mainHandler = new Handler();
}
```
```
private void initExoPlayer() {
        if (exoPlayer == null) {
            TrackSelection.Factory videoTrackSelectionFactory = new AdaptiveVideoTrackSelection.Factory(BANDWIDTH_METER);
            trackSelector = new DefaultTrackSelector(videoTrackSelectionFactory);
            exoPlayer = ExoPlayerFactory.newSimpleInstance(context, trackSelector, new DefaultLoadControl());
            simpleExoPlayerView.setPlayer(exoPlayer);
            exoPlayer.addListener(this);
        }
}

private void releaseExoPlayer() {
        if (exoPlayer != null) {
            exoPlayer.stop();
            exoPlayer.release();
            exoPlayer = null;
            trackSelector = null;
        }
}

public void PlayExoStream(String URL, String type) {
        initExoPlayer();
        Uri url = Uri.parse(URL);
        MediaSource videoSource = null;
        if (type.equals("m3u8")) {
            videoSource = new HlsMediaSource(url, dataSourceFactory, mainHandler, null);
        }
        else if (type.equals("dash")){
            videoSource = new DashMediaSource(url, dataSourceFactory, new DefaultDashChunkSource.Factory(dataSourceFactory), mainHandler, null);
        }
        if (videoSource != null) {
            exoPlayer.prepare(videoSource);
            exoPlayer.setPlayWhenReady(true);
        }
}
```

```
    @Override
    public void onTracksChanged(TrackGroupArray trackGroups, TrackSelectionArray trackSelections) {

        MappingTrackSelector.MappedTrackInfo mappedTrackInfo = trackSelector.getCurrentMappedTrackInfo();
        if (mappedTrackInfo != null) {
            if (mappedTrackInfo.getTrackTypeRendererSupport(C.TRACK_TYPE_VIDEO)
                    == MappingTrackSelector.MappedTrackInfo.RENDERER_SUPPORT_UNSUPPORTED_TRACKS) {
                Toast.makeText(MainActivity.this, "Unsupported", Toast.LENGTH_SHORT).show();
            }
            if (mappedTrackInfo.getTrackTypeRendererSupport(C.TRACK_TYPE_AUDIO)
                    == MappingTrackSelector.MappedTrackInfo.RENDERER_SUPPORT_UNSUPPORTED_TRACKS) {
                Toast.makeText(MainActivity.this, "Unsupported", Toast.LENGTH_SHORT).show();
            }
        }
    }
```

**Comment by ojw28** [comment]
We don't support adaptation between audio+video and audio only tracks, sorry. This is mainly because DASH and SmoothStreaming do not have the same kind of concept due to the fact that audio and video tracks are de-muxed. To support this kind of adaptation for HLS only would require our HLS implementation to deviate significantly from the code that we use for DASH and SmoothStreaming, and this is not something we're keen on doing.

As an aside, I don't really understand *why* adaptation to audio only is part of the HLS spec. In most cases I'd argue that buffering is preferable to the video disappearing. For the minority of cases where it's not, it seems simpler just to include an extremely low bitrate video track than to require players to handle the video track disappearing.

**Comment by AntonAndev** [comment]
Ok, thank you. I have an app for Android and for iOS. On iOS Apple requires to add "audio only" track to support low bandwidth. It is simply cheaper than encoding all TV channels to very low bitrate video version.

**Comment by ojw28** [comment]
I guess the reasoning behind my last paragraph is that it wouldn't even be necessary to encode the TV stream. You could just encode a thumbnail as a very low bitrate video track. Each segment could probably just have a single key-frame. That key-frame could even just be solid black. Seems like it would have been easier. Unfortunately it's just not how things are :). Oh well!

**Comment by AntonAndev** [comment]
Thanks for the help :)
