### ISSUE TITLE
Xiaomi Mi Box: Aspect ratio problem on android tv screen

### ISSUE THREAD

**Issue by ashiagr** [google/ExoPlayer#2242]
Hi

Non 16:9 videos are getting stretched on Xiaomi Mi Box Android 6 TV box in an app using tv leanback library and `ExoPlayer 2.1.0` `SimpleExoPlayerView`.

```
<com.google.android.exoplayer2.ui.SimpleExoPlayerView
        android:id="@+id/texture_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_gravity="center"
        app:surface_type ="texture_view"/>
```
 
Video gets to normal aspect ratio for few seconds but gets stretched soon after and then never goes back to normal. Here's a screenshot: http://imgur.com/a/TV6hD. 

Issue seems to be reproducible on device but not emulator.

Providing [video](https://content.uplynk.com/36a92ce3461f443c9b3e2c12a0c64653.m3u8) for testing.

**Comment by ojw28** [comment]
Does the issue reproduce using ExoPlayer's demo app, or just your own? Do you have other physical devices on which the app behaves correctly? We don't have a Xiaomi Mi Box to test on, but I'll try and get hold of one.

In the meantime, if you're seeing different behavior on Mi Box than on other devices, you should probably report the issue to Xiaomi as it's likely to be a device specific issue with the platform software in that case.

**Comment by sergeymild** [comment]
i have that problem too on Nexus 6p
![226617552_15594240633121820944](https://cloud.githubusercontent.com/assets/3685209/21750642/dbcad3a2-d5c0-11e6-8c79-1a1b44017d93.jpg)

**Comment by ojw28** [comment]
@sergeymild - I doubt it's the exact same issue. Either way, please provide sample content + a full bug report (i.e. the output of `adb bugreport` captured whilst reproducing the problem) if you want us to investigate. Thanks!

**Comment by ojw28** [comment]
I was able to reproduce this. It appears to be a bug with the H264 decoder on Xiaomi devices (OMX.amlogic.avc.decoder.awesome), where the output format of the decoder has the wrong dimensions.

**Comment by ojw28** [comment]
@agr111 - Is it possible for you to report this issue directly to Xiaomi? Thanks!

**Comment by ojw28** [comment]
Actually, I have a contact route. I'll send it their way and see if they can provide an update. Thanks!

**Comment by ashiagr** [comment]
Awesome! Thank you.

**Comment by ojw28** [comment]
[Internal ref: 34270647]

**Comment by ojw28** [comment]
My understanding is that Xiaomi will be fixing this in an upcoming platform update. I don't have an ETA.
