### ISSUE TITLE
Stack on buffering state when remove and add AspectRatioFrameView

### ISSUE THREAD

**Issue by ChernyshovYuriy** [google/ExoPlayer#2243]
Dear colleagues,
This is more question rather then bug / unexpected behaviour report.
In our application we use different Fragments to display video. Recently we discovered that once AspectRatioFrameView that holds surface for the video rendering removed from the one View and added to another, it stack on the buffering state forever.
The only one workaround is to invoke pause and play in order to force ExoPlayer go on.
This is a piece of logs describing stuff happening between remove and add calls.
The question is - does anyone faced the same behaviour? What was a solution?
Important note: I tried to reproduce on ExoPlayer Sample app but it works perfectly! The only one difference I found so far between ExoPlayer Sample app and our app is that all Views in our are creating dynamically in the code while ExoPlayer's ones inflating from xml.

Log:
```
12-21 21:17:36.295 D: PlayerFragment.detachVideoView(371)	Detach Video view	(QPServiceBinder-Thread)
12-21 21:17:36.301 D: HDCP check result: External Screen: false HDCP: false
12-21 21:17:36.302 D: [OMX.qcom.video.decoder.avc] Now Executing->Idle
12-21 21:17:36.318 D: [OMX.qcom.video.decoder.avc] Now Idle->Loaded
12-21 21:17:36.319 D: [OMX.qcom.video.decoder.avc] Now Loaded
                      
                      [ 12-21 21:17:36.326   314: 3916 E/         ]
                      Destroy C2D instance
                      
                      [ 12-21 21:17:36.326   314: 3916 E/         ]
                      Destroy C2D instance
12-21 21:17:36.326 D: Now uninitialized
12-21 21:17:36.328 D: ~ACodec
12-21 21:17:36.463 D: ExoPlayerVstbImpl.getBufferedRange(1755)	Buffered 8039 ms	(ExoPlayerVstbImpl)
12-21 21:17:36.464 D: ExoPlayerVstbImpl.getBufferedRange(1755)	Buffered 8039 ms	(ExoPlayerVstbImpl)
12-21 21:17:36.466 D: ExoPlayerVstbImpl.getAudioCodecType(1569)	Codecs:mp4a.40.2, mime:audio/mp4a-latm	(QPServiceBinder-Thread)
12-21 21:17:36.466 W: ExoPlayerVstbImpl.getSubtitleTrack(656)	Selected Format is null	(QPServiceBinder-Thread)
12-21 21:17:36.467 W: ExoPlayerVstbImpl.getClosedCaptionTrack(564)	Selected Format is null	(QPServiceBinder-Thread)
12-21 21:17:36.469 D: ExoPlayerVstbImpl.getBufferedRange(1755)	Buffered 8028 ms	(ExoPlayerVstbImpl)
12-21 21:17:36.472 D: ExoPlayerVstbImpl.getAudioCodecType(1569)	Codecs:mp4a.40.2, mime:audio/mp4a-latm	(QPServiceBinder-Thread)
12-21 21:17:36.473 W: ExoPlayerVstbImpl.getSubtitleTrack(656)	Selected Format is null	(QPServiceBinder-Thread)
12-21 21:17:36.473 W: ExoPlayerVstbImpl.getClosedCaptionTrack(564)	Selected Format is null	(QPServiceBinder-Thread)
12-21 21:17:36.480 D: ExoPlayerVstbImpl.getAudioCodecType(1569)	Codecs:mp4a.40.2, mime:audio/mp4a-latm	(QPServiceBinder-Thread)
12-21 21:17:36.480 W: ExoPlayerVstbImpl.getSubtitleTrack(656)	Selected Format is null	(QPServiceBinder-Thread)
12-21 21:17:36.481 W: ExoPlayerVstbImpl.getClosedCaptionTrack(564)	Selected Format is null	(QPServiceBinder-Thread)
12-21 21:17:36.486 D: PlayerFragment$PlaybackControllerInternalListener.onPlaybackProgress(1034)	Current time: 31002	(QPServiceBinder-Thread)
12-21 21:17:36.487 D: ExoPlayerVstbImpl.getBufferedRange(1755)	Buffered 8008 ms	(QPServiceBinder-Thread)
12-21 21:17:37.459 D: ExoPlayerVstbImpl.getBufferedRange(1755)	Buffered 7039 ms	(ExoPlayerVstbImpl)
12-21 21:17:37.467 D: ExoPlayerVstbImpl.getAudioCodecType(1569)	Codecs:mp4a.40.2, mime:audio/mp4a-latm	(QPServiceBinder-Thread)
12-21 21:17:37.469 W: ExoPlayerVstbImpl.getSubtitleTrack(656)	Selected Format is null	(QPServiceBinder-Thread)
12-21 21:17:37.470 W: ExoPlayerVstbImpl.getClosedCaptionTrack(564)	Selected Format is null	(QPServiceBinder-Thread)
12-21 21:17:37.484 D: ExoPlayerVstbImpl.getBufferedRange(1755)	Buffered 7023 ms	(ExoPlayerVstbImpl)
12-21 21:17:37.493 D: ExoPlayerVstbImpl.getBufferedRange(1755)	Buffered 7012 ms	(ExoPlayerVstbImpl)
12-21 21:17:37.497 D: ExoPlayerVstbImpl.getAudioCodecType(1569)	Codecs:mp4a.40.2, mime:audio/mp4a-latm	(QPServiceBinder-Thread)
12-21 21:17:37.498 W: ExoPlayerVstbImpl.getSubtitleTrack(656)	Selected Format is null	(QPServiceBinder-Thread)
12-21 21:17:37.499 W: ExoPlayerVstbImpl.getClosedCaptionTrack(564)	Selected Format is null	(QPServiceBinder-Thread)
12-21 21:17:37.518 D: ExoPlayerVstbImpl.getAudioCodecType(1569)	Codecs:mp4a.40.2, mime:audio/mp4a-latm	(QPServiceBinder-Thread)
12-21 21:17:37.520 W: ExoPlayerVstbImpl.getSubtitleTrack(656)	Selected Format is null	(QPServiceBinder-Thread)
12-21 21:17:37.522 W: ExoPlayerVstbImpl.getClosedCaptionTrack(564)	Selected Format is null	(QPServiceBinder-Thread)
12-21 21:17:37.530 D: PlayerFragment$PlaybackControllerInternalListener.onPlaybackProgress(1034)	Current time: 32002	(QPServiceBinder-Thread)
12-21 21:17:37.535 D: ExoPlayerVstbImpl.getBufferedRange(1755)	Buffered 6961 ms	(QPServiceBinder-Thread)
12-21 21:17:38.196 I: ViewRoot's Touch Event : ACTION_DOWN
12-21 21:17:38.273 I: ViewRoot's Touch Event : ACTION_UP
12-21 21:17:38.293 D: PlayerFragment.attachVideoView(348)	Attach Video view	(QPServiceBinder-Thread)
12-21 21:17:38.332 V: LG Codec Adapter start
12-21 21:17:38.332 D: ACodec
12-21 21:17:38.332 D: Now uninitialized
12-21 21:17:38.332 D: ACodec
12-21 21:17:38.334 D: initiateAllocateComponent
12-21 21:17:38.334 D: onAllocateComponent
12-21 21:17:38.336 I: Using client-side OMX mux.
12-21 21:17:38.350 D: Successfully allocated OMX node 'OMX.qcom.video.decoder.avc'
12-21 21:17:38.350 D: [OMX.qcom.video.decoder.avc] Now Loaded
12-21 21:17:38.352 I: [OMX.qcom.video.decoder.avc] setting surface generation to 31720454
12-21 21:17:38.353 V: called getLGCodecSpecificData
12-21 21:17:38.353 V: Called LGgetCodecSpecificDataMSG
12-21 21:17:38.353 D: initiateConfigureComponent
12-21 21:17:38.353 D: configureCodec
12-21 21:17:38.355 W: Failed to get extension for PASSINPUTBUFFERFD
12-21 21:17:38.356 V: called IsLGComponent
12-21 21:17:38.356 I: setupVideoDecoder()
12-21 21:17:38.356 I: vpp-enable search is 0 and value is 0
12-21 21:17:38.356 D: Called setupVideoDecoder start
12-21 21:17:38.363 I: Decoder will be in frame by frame mode
12-21 21:17:38.363 W: Failed to set frame packing format on component
12-21 21:17:38.363 V: Called LGconfigureCodecMSG
12-21 21:17:38.363 V: Not support LGCodec
12-21 21:17:38.367 D: onStart
12-21 21:17:38.368 D: [OMX.qcom.video.decoder.avc] Now Loaded->Idle
12-21 21:17:38.377 D: set up nativeWindow 0x94533508 for 848x480, color 0x7fa30c04, rotation 0, usage 0x42002900
12-21 21:17:38.378 D: [OMX.qcom.video.decoder.avc] Allocating 22 meta buffers on output port
12-21 21:17:38.397 D: [OMX.qcom.video.decoder.avc] Now Idle->Executing
12-21 21:17:38.397 D: [OMX.qcom.video.decoder.avc] Now Executing
12-21 21:17:38.398 D: ExoPlayerComponentListenerImpl.onVideoDecoderInitialized(642)	Video decoder:OMX.qcom.video.decoder.avc	(ExoPlayerVstbImpl)
                      
                      [ 12-21 21:17:38.406   314:10833 E/         ]
                      not in avi mode
                      
                      [ 12-21 21:17:38.406   314:10833 E/         ]
                      not in avi mode
12-21 21:17:38.413 D: ExoPlayerEventLogger.onPlayerStateChanged(95)	state [9.69, true, B]	(ExoPlayerVstbImpl)
12-21 21:17:38.414 D: ExoPlayerVstbImpl$ExoPlayerListener.onPlayerStateChanged(1612)	ExoPlayer State Changed to: STATE_BUFFERING (playWhenReady: true)	(ExoPlayerVstbImpl)
12-21 21:17:38.414 D: PlayerInterface.setBufferState(480)	Setting Buffer State to: EMPTY from ACTIVE	(ExoPlayerVstbImpl)
12-21 21:17:38.414 D: PlaybackController$PlayerInterfaceListenerImpl.onBufferingStateChanged(2851)	Playback Controller Buffering State did change to EMPTY for PlaybackOrtsItem{mMetaId=3}	(ExoPlayerVstbImpl)
12-21 21:17:38.421 D: [OMX.qcom.video.decoder.avc] Now handling output port settings change
12-21 21:17:38.426 D: ExoPlayerVstbImpl.getBufferedRange(1755)	Buffered 6059 ms	(QPServiceBinder-Thread)
12-21 21:17:38.428 D: ExoPlayerVstbImpl.getAudioCodecType(1569)	Codecs:mp4a.40.2, mime:audio/mp4a-latm	(QPServiceBinder-Thread)
12-21 21:17:38.432 D: set up nativeWindow 0x94533508 for 848x480, color 0x7fa30c04, rotation 0, usage 0x42002900
12-21 21:17:38.434 D: [OMX.qcom.video.decoder.avc] Allocating 12 meta buffers on output port
12-21 21:17:38.448 D: [OMX.qcom.video.decoder.avc] Now Executing
12-21 21:17:38.461 W: Failed to get Profile and Level from Component
12-21 21:17:38.461 W: Failed to get Entropy from Component
12-21 21:17:38.464 D: ExoPlayerVstbImpl.getBufferedRange(1755)	Buffered 6039 ms	(ExoPlayerVstbImpl)
12-21 21:17:38.465 D: ExoPlayerVstbImpl.getBufferedRange(1755)	Buffered 6039 ms	(ExoPlayerVstbImpl)
12-21 21:17:38.465 D: ExoPlayerVstbImpl.getBufferedRange(1755)	Buffered 6039 ms	(ExoPlayerVstbImpl)
12-21 21:17:38.470 D: ExoPlayerComponentListenerImpl.onRenderedFirstFrame(623)	Rendered First Frame for Surface(name=null)/@0x9152f90	(ExoPlayerVstbImpl)
```

**Comment by ojw28** [comment]
If you're not able to reproduce with the sample app (or a modification of it) then that would point toward an application specific issue, and I'm not sure there's much we can do to help. There's no reason inflating views from xml would result in different behavior compared to creating views in code. Please feel free to update this issue if you do find a way to modify the demo app that causes the issue to reproduce there!

**Comment by ChernyshovYuriy** [comment]
Hi.

I am able to reproduce this issue on sample app.
Fork is locating here: https://github.com/ChernyshovYuriy/ExoPlayer/tree/remove_add_video_view
Changes are in:
- PlayerActivity.java
- DefaultLoadControl.java
- player_activity.xml

Here is important precondition. In DefaultLoadControl (for simplicity) DEFAULT_BUFFER_FOR_PLAYBACK_AFTER_REBUFFER_MS is set to **30000** ms, which is completely legal value for re-buffering.
Try to play, for instance,  WIDEVINE DASH H264 Clear SD.
On top, along side with other buttons, there will be "Add Vid" and "RemVid" buttons.
Try to rewind somewhere and play for a seconds.
Then press "Rem Vid" and wait for a couple of seconds.
Then press "Add Vid".
When you re-add view, there will be "stuck" observed, video just freeze and no audio. Also, a screen is green (probably some kind of artifacts or invalid data from the previous video frame, no idea).
If you decrease value of DEFAULT_BUFFER_FOR_PLAYBACK_AFTER_REBUFFER_MS to 5000 ms then there is no issue. But in real applications this parameter rarely has such low value.
So, there are two questions:
- Why re-add a view causing re-buffering
- Why such value as 30000 ms causing such un-expected behaviour

This issue raised based on real application that is not yet in production but going to be launched this year. DEFAULT_BUFFER_FOR_PLAYBACK_AFTER_REBUFFER_MS was a last point that I even though to consider while investigated it :-)

**Comment by ojw28** [comment]
> DEFAULT_BUFFER_FOR_PLAYBACK_AFTER_REBUFFER_MS is set to 30000 ms, which is completely legal value for re-buffering.

It's not a sensible value to use unless you also change some of the other values defined there. By just changing that constant you're saying you want the player to maintain between `15s` (`minBufferUs`) and `30s` (`maxBufferUs`) of buffer, but that you don't want the player to actually start playing unless there's `30s` (`bufferForPlaybackAfterRebufferUs`) of media in the buffer. The player is doing what you've told it to do: It maybe has a buffer of `20s` (fine according to the first two constants) and is not resuming playback (fine according to the third constant). To avoid getting stuck this way, you should ensure that `bufferForPlaybackAfterRebufferUs` is smaller than `minBufferUs`. We should probably assert this and document it more clearly, so we'll use this issue to track that. But the root cause is you're not setting configuring the load control with sensible values.

> If you decrease value of DEFAULT_BUFFER_FOR_PLAYBACK_AFTER_REBUFFER_MS to 5000 ms then there is no issue. But in real applications this parameter rarely has such low value.

I'm not sure how you've reached the conclusion that real applications rarely use the default values. I suspect the vast majority of applications *do* use the default values. Google's streaming services (YouTube, Play Movies etc) use low values too. Setting the value as high as 30s would require the application to download a pretty huge buffer in some cases (e.g. 30MB in the case of an 8mbit/s stream). It's generally not desirable to require such a large buffer prior to resuming playback.

Re-opening to track adding sanity assertions and documentation only.

**Comment by ChernyshovYuriy** [comment]
Thank you for such detailed clarification, it really helped me.
Still have one concern: Why re-add a view causing re-buffering?

**Comment by ojw28** [comment]
Buffering is anything preventing the player from making progress. In the case of switching the view, the player may switch into a buffering state for a very short period of time until the first frame is dequeued from the newly acquired video decoder and rendered to the newly provided surface. There's usually no network re-buffer involved. Note there are other scenarios (apart from swapping the view) that could also result in the stuck state, if the constants are not configured sensibly.
