### ISSUE TITLE
Support seamlessly changing tracks during adaptive playbacks (DASH/SS/HLS)

### ISSUE THREAD

**Issue by AntonAFA** [google/ExoPlayer#2250]
Hello, have a question.
Is it possible in Exoplayer2 to switch between tracks seamlessly without rebufferring?

For example start buffering the switched track only from point where the last dowloaded chunk of the previous track is ended?
Or in case of text track changes it takes a couple of seconds until the track is changed and rebuffered.

Any ideas?

**Comment by ojw28** [comment]
This is not currently supported. Marking as an enhancement.

**Comment by AquilesCanta** [comment]
So a possible way of switching stream quality without forcing a rebuffer (note that it might be unavoidable) would be injecting a custom AdaptiveTrackSelection through the DefaultTrackSelector's constructor `DefaultTrackSelector(TrackSelection.Factory adaptiveTrackSelectionFactory)`. A good place to start looking is `AdaptiveTrackSelection`.

This custom adjustable track selection could then be configured to select specific qualities, if the default adaptive behavior is not adequate. Threading here might be a concern, as most likely the quality is selected in the main thread, but the TrackSelection methods are invoked on the playback thread, so this is something that must be kept in mind. The changes in qualities will take effect from the moment they are applied to the custom track selection onwards.

This is just an idea of how it can be done in application code, it is not yet on our map to implement this enhancement as part of the library, unfortunately. Feel free to post any issues you encounter here.

**Comment by hsahnv** [comment]
Is there any plan about this?

**Comment by tonihei** [comment]
@hsahnv No current plans to support that. As described above, you can implement such a feature yourself by customizing AdaptiveTrackSelection.

**Comment by Romantic-LiXuefeng** [comment]
Is there any plan to support this feature?

**Comment by tonihei** [comment]
@Romantic-LiXuefeng Still no immediate plan to support this. You can easily implement it yourself as noted above, maybe also using the `canSelectTrack` method of `AdaptiveTrackSelection`. To support that in a better way, we'd need to restructure some code which is non-trivial.

**Comment by robosoft-abhishek-v** [comment]
@AntonAFA @ojw28 @AquilesCanta Any update on this? Still this is not supported in ExoPlayer?

**Comment by vabhishek** [comment]
@AntonAFA @ojw28 @AquilesCanta Hey Any update on this? ExoPlayer still does not support this out of the box?

**Comment by ojw28** [comment]
When there is an update, it will be posted here.

**Comment by tonihei** [comment]
This is an old issue, but the general request still makes sense. I'll de-duplicate it a newer version of in the Media3 repository: https://github.com/androidx/media/issues/1631. Also note there is still a manual workaround to inject custom track filters dynamically as explained in https://github.com/google/ExoPlayer/issues/6630#issuecomment-1023007702.
