### ISSUE TITLE
Issue in com.google.android.exoplayer2.trackselection.DefaultTrackSelector.setParameters

### ISSUE THREAD

**Issue by ebaradel** [google/ExoPlayer#2251]
"getAndSet" returns the previous value ,not the updated one.

I've changed the code as following in my environment to go ahead: 
``` 
public void setParameters(Parameters params) {
    Assertions.checkNotNull(params);
    paramsReference.getAndSet(params);
    if (!paramsReference.get().equals(params)) {
       invalidate();
    }
  }
```

**Comment by ojw28** [comment]
It looks correct how it is currently to me, and it's desired that the `getAndSet` return the previous value. The correct behavior is to update paramsReference to the new params and call invalidate if the old and new params are different, which I think the current code does correctly. In your updated version the condition looks like it will always evaluate to false. Please clarify.

**Comment by ebaradel** [comment]
ok sorry for my misunderstanding.
