### ISSUE TITLE
Enhance the far seek  response of streaming

### ISSUE THREAD

**Issue by WeiChungChang** [google/ExoPlayer#2253]
as #2247 

http://programmingmemojohnchang.blogspot.tw/2016/12/improve-performance-of-short-seek-of_22.html

For 4K movie, if the seek locates within the last download media chunk but has not been in sampleQueue yet. We will download redundant data currently.

It makes the response time of seek slower. Also, it leads to waste of network flow.

Here a request to review the problem is delivered.

Thanks~

**Comment by ojw28** [comment]
A solution for this issue was merged in https://github.com/google/ExoPlayer/pull/2318.
