### ISSUE TITLE
AdaptiveVideoTrackSelection Class is used both for Video and Audio Tracks

### ISSUE THREAD

**Issue by giladna** [google/ExoPlayer#2257]
Hi,
It will be better to give that class more generic name maybe

10x
Gilad

**Comment by ojw28** [comment]
I don't think it is used for audio tracks in any default configuration. It's also not well suited to audio adaptation; and if audio adaptation is desired a different implementation would probably be preferable. Please clarify and point out the circumstances in which it is used for audio tracks if you think this is incorrect.

**Comment by ojw28** [comment]
Closing due to lack of information.

**Comment by giladna** [comment]
Hi  Olly,

This is used in also in Audio Tracks
In case you have bitrates selection capability for audio quality

When I come to check the Auto bitrate for AUDIO
I get the instance of AdaptiveVideoTrackSelection

**Comment by ojw28** [comment]
I'm not convinced that actually happens. There's another issue [here](https://github.com/google/ExoPlayer/issues/1975) that says, I think correctly, that audio isn't adaptive by default. If there are multiple audio tracks then current behavior is to pick one and stick with it. The default track selector only ever selects a fixed track for audio [here](https://github.com/google/ExoPlayer/blob/r2.1.1/library/src/main/java/com/google/android/exoplayer2/trackselection/DefaultTrackSelector.java#L657).

Can you provide an example of a stream where, if added to the demo app, performs an adaptive audio playback?
