### ISSUE TITLE
AC3- FFmpeg’s configure script

### ISSUE THREAD

**Issue by GianmarcoGiunti** [google/ExoPlayer#2261]
My device is support AC3 audio and in Exoplayer AC3 audio is not working.

I am using this version in android:
compile 'com.google.android.exoplayer:exoplayer:r1.5.12'

I need to enable and write script for AC3 audio? 
Please give me easiest solution for play AC3 audio in my device.

Before I am using Videoview and AC3 is working with videoview and with Exoplayer it's not working.

Thanks advance,
Jd

**Comment by ojw28** [comment]
If this is still a problem, please file a new issue including all of the information requested in the issue template (e.g. a full bug report, detailed reproduction steps that show AC3 not working, etc).
