### ISSUE TITLE
Problem with ExoPlayer guide code and exoplayer version exoplayer:r2.1.1

### ISSUE THREAD

**Issue by Waheed388** [google/ExoPlayer#2268]
I trying to play server videos with links in my mobile app. I preferred to use exoplayer library over default videoView but the problem is [guide code](http://google.github.io/ExoPlayer/guide.html) is not helping me. If I use exo version :r2.1.1 then this constructor stop working 

TrackSelector trackSelector =
                new DefaultTrackSelector(mainHandler, videoTrackSelectionFactory);

and if I use exo version :r2.0.1 then above mentioned code start working.

and this constructor is not working in both versions 

 DataSource.Factory dataSourceFactory = new DefaultDataSourceFactory(this, userAgent, bandwidthMeter);

is there any updated code to play online saved videos in mobile app.

**Comment by lioun1729** [comment]
The Demo App in Library is better than ExoPlayer guide page

**Comment by ojw28** [comment]
We'll update the guide to fix this, thanks!

**Comment by ojw28** [comment]
I've fixed the first issue raised. The second appears to work fine for me. It's possible "this" isn't a `Context` in your code, in which case you'll need to tweak it slightly. In any case, it's trivial to look up what the constructor arguments should be in the [documentation](http://google.github.io/ExoPlayer/doc/reference/).
