### ISSUE TITLE
MediaCodecAudioRender always wins over FfmpegAudioRenderer

### ISSUE THREAD

**Issue by stari4ek** [google/ExoPlayer#2269]
* dev-v2, 163a3a7bb876d309f5d28cc62473f093802d8aea
* demo player with extensions
* ffmpeg with mp3 decoder
* MPEG-TS stream with audio/mpeg-L2
* nvidia shield

NVidia shield:
```
D/MediaCodecInfo: NoSupport [channelCount.support, 2, supported 1] [OMX.Nvidia.mp2.decoder, audio/mpeg-L2] [foster, SHIELD Android TV, NVIDIA, 23]
D/MediaCodecInfo: NoSupport [channelCount.support, 2, supported 1] [OMX.Nvidia.mp2.decoder, audio/mpeg-L2] [foster, SHIELD Android TV, NVIDIA, 23]
D/EventLogger: Tracks [
D/EventLogger:   Renderer:0 [
D/EventLogger:     Group:0, adaptive_supported=N/A [
D/EventLogger:       [X] Track:0, id=null, mimeType=video/avc, res=1920x1080, supported=YES
D/EventLogger:     ]
D/EventLogger:   ]
D/EventLogger:   Renderer:2 [
D/EventLogger:     Group:0, adaptive_supported=N/A [
D/EventLogger:       [X] Track:0, id=null, mimeType=audio/mpeg-L2, channels=2, sample_rate=48000, supported=NO_EXCEEDS_CAPABILITIES
D/EventLogger:     ]
D/EventLogger:   ]
D/EventLogger:   Renderer:6 [
D/EventLogger:     Group:0, adaptive_supported=N/A [
D/EventLogger:       [ ] Track:0, id=null, mimeType=application/cea-608, supported=YES
D/EventLogger:     ]
D/EventLogger:   ]
D/EventLogger: ]
```

device decoder declares that it supports 1 channel only (btw, Philips, QM16XE_U, QM163E with OMX.MTK.AUDIO.DECODER.DSPMP1 does the same)

Please check `RendererCapabilities.supportsFormat`:
`MediaCodecAudioRender` returns `ADAPTIVE_NOT_SEAMLESS | formatSupport` while `FfmpegAudioRenderer` returns just `formatSupport`.

It means that `FORMAT_EXCEEDS_CAPABILITIES` wins over `FORMAT_HANDLED` which looks wrong

**Comment by stari4ek** [comment]
BTW, is it expected that decoders:
* OMX.Nvidia.mp2.decoder (nvidia shield)
* OMX.MTK.AUDIO.DECODER.DSPMP1 (philips)

returns `MediaCodecInfo.getMaxInputChannelCount()` == **1**?

No issues with audio playback on NVidia shield.

Should I create separate issue for it?

**Comment by kiall** [comment]
By default, exoplayer will prefer to use native rather than extension renderers.

You can pass a extensionRendererMode paramater to ExoPlayerFactory.newSimpleInstance() with a value of SimpleExoPlayer.EXTENSION_RENDERER_MODE_PREFER to have ExoPlayer prefer the extension..

**Comment by stari4ek** [comment]
> By default, exoplayer will prefer to use native rather than extension renderers.

This is expected behavior if both renderers are supported **equally**. For example both **FORMAT_HANDLED** or both **FORMAT_EXCEEDS_CAPABILITIES**

But in described situation we compare "fully supported" vs "lacking proper support" where "lacking proper support" wins

**Comment by ojw28** [comment]
I think there's a one line bug (we're forgetting to mask the value [here](https://github.com/google/ExoPlayer/blob/r2.1.1/library/src/main/java/com/google/android/exoplayer2/trackselection/MappingTrackSelector.java#L352)) that causes this. We'll push a fix shortly. Thanks!

**Comment by stari4ek** [comment]
@ojw28 , thank you

What about **MediaCodecInfo.getMaxInputChannelCount() == 1** from nvidia/mediatek MediaCodec? is it expected behavior?

**Comment by ojw28** [comment]
I doubt it, particularly if you're seeing it work successfully with more channels. I suggest you report the issue directly to nVidia.

**Comment by stari4ek** [comment]
With Nvidia it works with 2 channels pretty well.
But for Philips (with OMX.MTK.AUDIO.DECODER.DSPMP1) doesn't - stalled video. ffmpeg solves the issue
