### ISSUE TITLE
Background audio

### ISSUE THREAD

**Issue by dreich** [google/ExoPlayer#2276]
Hello! Thank you for ExoPlayer!

I read in issue of November that background audio was never a feature of ExoPlayer.
But I need it very much :). You know, my (not very unpopular) free android app "Orthodox radio" ([https://play.google.com/store/apps/details?id=ru.pravradio.andrey]) plays mp3 streams using standard MediaPlayer and doesn't use foreground service, but it works good and have good marks.
I tried to use ExoPlayer in the app (dev version) and saw that it loads mp3 stream approximately 10 times faster than MediaPlayer (when starting playing).
That is why I (and thousands of users) whould be happy to use your masterpiece.
Maybe now it is already possible somehow for ExoPlayer to keep playing in background?

Happy New Year!

**Comment by ojw28** [comment]
Using MediaPlayer without a foreground service is not advisable and will not work properly in certain circumstances. In particular, if the user launches another application and the OS decides to kill a process to free up resources (e.g. memory) for it, there's nothing stopping the OS from killing your process. A foreground services *is* the mechanism for applications to indicate to the OS that they're doing something important whilst not necessarily being in the foreground, and hence that they should not be killed. You really should be using one.

MediaPlayer and ExoPlayer are the same in that neither do anything "special" with respect to background playback. Either can be used to play audio in the background. In both cases a foreground service is required to ensure correct behavior.
