### ISSUE TITLE
adding a custom header to DefaultHttpDataSource

### ISSUE THREAD

**Issue by amspayam** [google/ExoPlayer#2280]
Hi I'm new to ExoPlayer and want to add a http request header to my url for player but i didn't find any method to do it.
thanks.

**Comment by ojw28** [comment]
See https://github.com/google/ExoPlayer/issues/2166.

**Comment by amspayam** [comment]
thanks for your response, i tried this soloution and it worked greate on android api level 21 and above but below that api level the library cant handle the response

**Comment by ojw28** [comment]
There is nothing we can do to help given such a vague statement, sorry.
