### ISSUE TITLE
Make integration with cast SDK easier

### ISSUE THREAD

**Issue by ojw28** [google/ExoPlayer#2283]
As per title, we should make it easier for applications to make use of ExoPlayer (for local playback) and the cast SDK (for remote playback) together. In particular, we should make it easier to attach ExoPlayer's UI components (e.g. PlaybackControlView/SimpleExoPlayerView) to a remote playback during casting.

**Comment by Khoosham** [comment]
in the mean time maybe you can check this project ExoPlayer2 and Cast SDK v3 working example
https://github.com/lawloretienne/Loop

VideoDetailsFragment is casting videos...

i did not check it since i dont have a cast tv

**Comment by Khoosham** [comment]
@ojw28 when will this enhancement occur.
i tried adding cast sdk yesterday and gave up. too much work and complicated :(

**Comment by ojw28** [comment]
This is now implemented in `dev-v2`. Please give it a try and let us know what you think!
