### ISSUE TITLE
ExoPlayer throws load error while playing SmoothStreaming LIVE contents

### ISSUE THREAD

**Issue by dineshkumarkb** [google/ExoPlayer#2292]
Description:

ExoPlayer keeps throwing "Load Error" while playing smooth streaming live contents.

Player Version : 1.5.12
URL used : http://telecolor.econcept.it/live/primarete.isml/manifest
Android OS : Android 5.1.1
Device : Samsung note 3

Steps to Reproduce:

1. Play any smooth streaming live URL
2. Validate the logs of onLoadError() method.
3. Player keeps throwing LoadError multiple times

**Comment by ojw28** [comment]
The content is broken in the same way as described in https://github.com/google/ExoPlayer/issues/2101 and https://github.com/google/ExoPlayer/issues/1152. You should report the issue to the content producer, and ask them to fix it.

Having said that, we've seen this reported a few times now. We'll likely add a workaround to allow playback to proceed (you will still see a warning message logged every few seconds).
