### ISSUE TITLE
ID3 metadata for mp3 stream does not work 

### ISSUE THREAD

**Issue by blackraven96** [google/ExoPlayer#2293]
I don't have ID3 metadata with mp3 stream (for example http://stream.ouifm.fr/ouifm-high.mp3 ) with exoplayer 2.1.

It is possible to added it ?

thanks.

**Comment by ojw28** [comment]
The stream doesn't contain ID3 metadata. There's ICY metadata in the response headers, but this is not something we support.

**Comment by ChernyshovYuriy** [comment]
Hi team,
Any plans to support ICY Metadata?
I switched to ExoPlayer in my own personal project named [Open Radio](https://bitbucket.org/ChernyshovYuriy/openradio), it works excellent but I still tight to custom library named [FFmpegMediaMetadataRetriever](https://github.com/wseemann/FFmpegMediaMetadataRetriever) to get metadata of the Radio Station stream (which is important data for such streams).

**Comment by ojw28** [comment]
We've no plans to support ICY metadata, sorry. It's probably not that hard for you to make a small extension to ExoPlayer that adds support, if you're sufficiently motivated to do so ;).

**Comment by ChernyshovYuriy** [comment]
Sure, I do motivated. Is it possible to provide some guidelines / hints / directions where to start to "dig" from. Thanks :-)
