### ISSUE TITLE
Compiling Flac extension and adding the APK in priv-app folder makes app to CRASH

### ISSUE THREAD

**Issue by dcf82** [google/ExoPlayer#2302]
Hi dears friends,

I'm working on a personal application which integrates the Exoplayer 1.x, but the App is intended to be installed as a System App. I decided to add the Flac Codec extension by compiling the JNI libraries, compiling the project itself & generating a AAR library, so I added the final library to my personal project.

My proguard rules are the following:

# This prevents the names of native methods from being obfuscated.
-keepclasseswithmembernames class * {
    native <methods>;
}

# Keep unobfuscated the Exoplayer library itself
-keep class com.google.android.exoplayer.** {*;}

I compiled my project in release mode and enabled obfuscation, etc. but I'm facing the following two  scenarios:

- When the APK is installed directly, it runs pretty well with no issues
- When the same APK is installed in the priv-app folder, the library fails and shows the following error:

```
01-05 13:58:16.978  7667  8453 E LoadTask: java.lang.UnsatisfiedLinkError: No implementation found for long com.google.android.exoplayer.ext.flac.FlacJni.flacInit() (tried Java_com_google_android_exoplayer_ext_flac_FlacJni_flacInit and Java_com_google_android_exoplayer_ext_flac_FlacJni_flacInit__)
01-05 13:58:16.978  7667  8453 E LoadTask: at com.google.android.exoplayer.ext.flac.FlacJni.flacInit(Native Method)
01-05 13:58:16.978  7667  8453 E LoadTask: at com.google.android.exoplayer.ext.flac.FlacJni.<init>(SourceFile:55)
01-05 13:58:16.978  7667  8453 E LoadTask: at com.google.android.exoplayer.ext.flac.FlacExtractor.init(SourceFile:60)
01-05 13:58:16.978  7667  8453 E LoadTask: at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractorHolder.selectExtractor(SourceFile:901)
01-05 13:58:16.978  7667  8453 E LoadTask: at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(SourceFile:829)
01-05 13:58:16.978  7667  8453 E LoadTask: at com.google.android.exoplayer.upstream.Loader$LoadTask.run(SourceFile:209)
01-05 13:58:16.978  7667  8453 E LoadTask: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
01-05 13:58:16.978  7667  8453 E LoadTask: at java.util.concurrent.FutureTask.run(FutureTask.java:237)
01-05 13:58:16.978  7667  8453 E LoadTask: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
01-05 13:58:16.978  7667  8453 E LoadTask: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
01-05 13:58:16.978  7667  8453 E LoadTask: at java.lang.Thread.run(Thread.java:761)
01-05 13:58:16.982  7667  7916 W System.err: java.lang.UnsatisfiedLinkError: No implementation found for long com.google.android.exoplayer.ext.flac.FlacJni.flacInit() (tried Java_com_google_android_exoplayer_ext_flac_FlacJni_flacInit and Java_com_google_android_exoplayer_ext_flac_FlacJni_flacInit__)
01-05 13:58:16.982  7667  7916 W System.err: at com.google.android.exoplayer.ext.flac.FlacJni.flacInit(Native Method)
01-05 13:58:16.982  7667  7916 W System.err: at com.google.android.exoplayer.ext.flac.FlacJni.<init>(SourceFile:55)
01-05 13:58:16.983  7667  7916 W System.err: at com.google.android.exoplayer.ext.flac.FlacExtractor.init(SourceFile:60)
01-05 13:58:16.983  7667  7916 W System.err: at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractorHolder.selectExtractor(SourceFile:901)
01-05 13:58:16.983  7667  7916 W System.err: at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(SourceFile:829)
01-05 13:58:16.983  7667  7916 W System.err: at com.google.android.exoplayer.upstream.Loader$LoadTask.run(SourceFile:209)
01-05 13:58:16.983  7667  7916 W System.err: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
01-05 13:58:16.983  7667  7916 W System.err: at java.util.concurrent.FutureTask.run(FutureTask.java:237)
01-05 13:58:16.983  7667  7916 W System.err: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
01-05 13:58:16.983  7667  7916 W System.err: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
01-05 13:58:16.983  7667  7916 W System.err: at java.lang.Thread.run(Thread.java:761)
01-05 13:58:16.984  7667  7916 W FlurryAgent: Error logged: uncaught
01-05 13:58:16.989  7667  7916 E AndroidRuntime: FATAL EXCEPTION: ExoPlayerImplInternal:Handler
01-05 13:58:16.989  7667  7916 E AndroidRuntime: Process: com.celltick.lockscreen, PID: 7667
01-05 13:58:16.989  7667  7916 E AndroidRuntime: java.lang.UnsatisfiedLinkError: No implementation found for long com.google.android.exoplayer.ext.flac.FlacJni.flacInit() (tried Java_com_google_android_exoplayer_ext_flac_FlacJni_flacInit and Java_com_google_android_exoplayer_ext_flac_FlacJni_flacInit__)
01-05 13:58:16.989  7667  7916 E AndroidRuntime: at com.google.android.exoplayer.ext.flac.FlacJni.flacInit(Native Method)
01-05 13:58:16.989  7667  7916 E AndroidRuntime: at com.google.android.exoplayer.ext.flac.FlacJni.<init>(SourceFile:55)
01-05 13:58:16.989  7667  7916 E AndroidRuntime: at com.google.android.exoplayer.ext.flac.FlacExtractor.init(SourceFile:60)
01-05 13:58:16.989  7667  7916 E AndroidRuntime: at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractorHolder.selectExtractor(SourceFile:901)
01-05 13:58:16.989  7667  7916 E AndroidRuntime: at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(SourceFile:829)
01-05 13:58:16.989  7667  7916 E AndroidRuntime: at com.google.android.exoplayer.upstream.Loader$LoadTask.run(SourceFile:209)
01-05 13:58:16.989  7667  7916 E AndroidRuntime: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
01-05 13:58:16.989  7667  7916 E AndroidRuntime: at java.util.concurrent.FutureTask.run(FutureTask.java:237)
01-05 13:58:16.989  7667  7916 E AndroidRuntime: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
01-05 13:58:16.989  7667  7916 E AndroidRuntime: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
01-05 13:58:16.989  7667  7916 E AndroidRuntime: at java.lang.Thread.run(Thread.java:761)
01-05 13:58:16.991  7667  7706 W FlurryAgent: Flurry session ended
```

Could you please provide any feedback on what I'm not doing properly?

Thanks so much in advance.

**Comment by ojw28** [comment]
It sounds like the apk is fine, given it's working when installed normally. Which would indicate that it's not a proguard issue. It's most likely that the native library just isn't being loaded successfully. If I were you, I'd start digging [here](http://stackoverflow.com/questions/20906445/unable-to-load-so-library-files-when-making-a-system-application), which looks like a similar issue.

**Comment by ojw28** [comment]
If you do a Google search for "android system app native library" there are a whole bunch of results that look related, also :).

**Comment by dcf82** [comment]
I really appreciate your feedback & thanks for your quick response. I will take a look and let you know.

**Comment by dcf82** [comment]
One interesting observation here is that after putting the APK into priv-app & if I run the app the library doesn't run, but If I override the current app installed from Android Studio (using the Same APK) the app runs successfully. Very strange!

**Comment by dcf82** [comment]
Hi, I did a hello world sample app to isolate this issue but I'm seeing that the same issue comes up, is there a way you could give me some support, i can share the small project & donate some money for this support, if yes, please tell me the amount?

Thanks
David

**Comment by dcf82** [comment]
This is an observation that I found during my testing:

// Log when the library is installed properly

drwxrwx--x 2 u0_a129 u0_a129 4096 2017-01-06 12:07 app_data
drwxrwx--x 2 u0_a129 u0_a129 4096 2017-01-06 12:07 app_dynamicIcons
drwxrwx--x 2 u0_a129 u0_a129 4096 2017-01-06 12:07 app_textures
drwxrwx--x 3 u0_a129 u0_a129 4096 2017-01-06 12:07 app_webview
drwxrwx--x 9 u0_a129 u0_a129 4096 2017-01-06 12:07 cache
drwxrwx--x 2 u0_a129 u0_a129 4096 2017-01-06 12:07 databases
drwxrwx--x 3 u0_a129 u0_a129 4096 2017-01-06 12:08 files
lrwxrwxrwx 1 root    root      43 2017-01-06 12:07 lib -> /data/app/com.celltick.lockscreen-1/lib/arm
drwxrwx--x 2 u0_a129 u0_a129 4096 2017-01-06 12:08 shared_prefs
shamu:/data/data/com.celltick.lockscreen #

// Log when the library is NOT installed
drwxrwx--x  2 u0_a108 u0_a108 4096 2017-01-06 12:15 app_data
drwxrwx--x  2 u0_a108 u0_a108 4096 2017-01-06 12:15 app_dynamicIcons
drwxrwx--x  2 u0_a108 u0_a108 4096 2017-01-06 12:15 app_textures
drwxrwx--x  3 u0_a108 u0_a108 4096 2017-01-06 12:15 app_webview
drwxrwx--x 10 u0_a108 u0_a108 4096 2017-01-06 12:15 cache
drwxrwx--x  2 u0_a108 u0_a108 4096 2017-01-06 12:15 databases
drwxrwx--x  4 u0_a108 u0_a108 4096 2017-01-06 12:16 files
lrwxrwxrwx  1 root    root      37 2017-01-06 12:15 lib -> /system/lib/com.celltick.lockscreen-1
drwxrwx--x  2 u0_a108 u0_a108 4096 2017-01-06 12:16 shared_prefs

The interesting point here is that the folder "/system/lib/com.celltick.lockscreen-1" is exaclty the same as the APK NAME I put inside /system/priv-app folder,
that's means if I call the apk Start.apk and put it inside /system/priv-app, the path will be this one: "lib -> /system/lib/Start"
instead of "lib -> /data/app/com.celltick.lockscreen-1/lib/arm"
