### ISSUE TITLE
setPlayWhenReady does not report duration for mp3 file

### ISSUE THREAD

**Issue by Behrouz-m** [google/ExoPlayer#2306]
Hi. when I use `setPlayWhenReady` for online mp3 preparation & play, It does not return duration for mp3 file in `STATE_READY` state. 

I've attached ID3v2 tag to mp3 file that contains the correct duration but it seems that the player does not read the value.

I'm using the version r2.1.0 of Exoplayer

**Comment by ojw28** [comment]
There's nothing we can do to investigate this unless you provide the information requested in the issue template (specifically in this case, a sample stream that reproduces the issue). We don't rely on ID3 metadata for the duration; we read or derive it from the actual media stream.

**Comment by Behrouz-m** [comment]
I've attached the samples.

[mp3 sample.zip](https://github.com/google/ExoPlayer/files/692700/mp3.sample.zip)

**Comment by ojw28** [comment]
I'm struggling to work out what your issue is. The player indicates the duration correctly for me, and it also corrects reports the TLEN ID3 tag. When playing the sample in the demo app I see the following logged:

```
01-09 10:33:03.660  3092  3092 D EventLogger: audioDisabled [42.76]
01-09 10:33:05.549  3092  3092 D EventLogger: state [0.00, true, I]
01-09 10:33:05.642  3092  3092 D EventLogger: state [0.09, true, B]
01-09 10:33:05.642  3092  3092 D EventLogger: sourceInfo [periodCount=1, windowCount=1
01-09 10:33:05.642  3092  3092 D EventLogger:   period [?]
01-09 10:33:05.642  3092  3092 D EventLogger:   window [?, false, false]
01-09 10:33:05.642  3092  3092 D EventLogger: ]
01-09 10:33:05.642  3092  3092 D EventLogger: loading [true]
01-09 10:33:05.694  3092  3092 D EventLogger: sourceInfo [periodCount=1, windowCount=1
01-09 10:33:05.694  3092  3092 D EventLogger:   period [1.17]
01-09 10:33:05.694  3092  3092 D EventLogger:   window [1.17, true, false]
01-09 10:33:05.694  3092  3092 D EventLogger: ]
01-09 10:33:05.695  3092  3092 D EventLogger: Tracks [
01-09 10:33:05.695  3092  3092 D EventLogger:   Renderer:1 [
01-09 10:33:05.695  3092  3092 D EventLogger:     Group:0, adaptive_supported=N/A [
01-09 10:33:05.695  3092  3092 D EventLogger:       [X] Track:0, id=null, mimeType=audio/mpeg, channels=1, sample_rate=24000, supported=YES
01-09 10:33:05.695  3092  3092 D EventLogger:     ]
01-09 10:33:05.695  3092  3092 D EventLogger:     Metadata [
01-09 10:33:05.695  3092  3092 D EventLogger:       TSSE: description=LAME 32bits version 3.99.5 (http://lame.sf.net)
01-09 10:33:05.695  3092  3092 D EventLogger:       TLEN: description=1389
01-09 10:33:05.695  3092  3092 D EventLogger:     ]
01-09 10:33:05.695  3092  3092 D EventLogger:   ]
01-09 10:33:05.695  3092  3092 D EventLogger: ]
```

Where `1.17` is the duration derived from the actual media stream and `1389` is the duration in the ID3 metadata.

**Comment by Behrouz-m** [comment]
thanks for the answer.
the value `1389` is calculated by Lame encoder according to `input num samples` . It seems that the value is based on `millisecond`.
So, what should I do to fix the problem ?

**Comment by ojw28** [comment]
You haven't really explained what the problem is, since playback works fine. What's the actual issue you're encountering as a result of the duration values disagreeing by ~200ms?

If you need precise duration you should add an appropriate header to the MP3 (e.g. a VBRI header) or use a more appropriate container format (e.g. MP4).

**Comment by Behrouz-m** [comment]
The problem is the player do not report duration for lengthy mp3 files (more than about 10 sec) for low bandwidth networks (aka 20KByte/sec) even I've attached the ID3V2 tag that contains the length. What should I do to fix the duration report problem ? The player starts to play the mp3 with no duration while the player is still downloading the mp3 file.

**Comment by ojw28** [comment]
I don't think that would happen unless both (a) you're streaming and your server isn't including a content length header in the response, and (b) the mp3 doesn't include an appropriate header (e.g. a VBRI header) indicating duration. You can fix either issue to get duration reported correctly. Adding ID3 metadata isn't relevant to this problem.

**Comment by Behrouz-m** [comment]
thanks for the advice. I'm using Lame programmatically. Do you know which function of lame should I call to fix the issue ?
