### ISSUE TITLE
How to define the buffer size when consuming a AAC audio stream

### ISSUE THREAD

**Issue by thefenix1** [google/ExoPlayer#231]
I'm escaping from Android built in Media Player due lack of buffer control. My stream takes 20 seconds to load using my wifi network and that's unacceptable (among some other problems like endless buffering).

Is there any way to specify the buffer size? I'm not sure if I'm getting it well but it seems I have to use ChunkSampleSource since it has an option to specify buffer size. OTOH, seems to be used for adaptative rendering...and this is not applying to my scenario. 

Thanks

**Comment by ojw28** [comment]
You should be able to play AAC in the demo app using TYPE_AAC now, which gives you a lot more control over this kind of thing. If you follow the code path into ExtractorRendererBuilder then you'll find the place where the buffer size is set.
