### ISSUE TITLE
Does any one in this group implement Exo player with Expressplay to play PDCF content

### ISSUE THREAD

**Issue by satyamub** [google/ExoPlayer#2312]
Hi All,

I am trying to run a PDCF content (.mlv) file which is generated from Expressplay dashboard. We are using the test sdk of the Expressplay. We are using Media Source Type as "SINGLE _FILE". Still we can not able to play. It seems like, its creating a m3u8 playlist from the mlv but not able to play.

When we use the VideoView, it shows, that the m3u8 file is not found error.

Can you people help?

**Comment by ojw28** [comment]
Without any reproduction steps (e.g. a link to sample content that fails) we're not able to investigate the issue. Please file an issue with clear reproduction steps and test content if you want us to take a look.
