### ISSUE TITLE
Pre-Fetch viewing license for Widevine using sessionShare   

### ISSUE THREAD

**Issue by yanivlankry** [google/ExoPlayer#2313]
Team,
I’m trying to split license acquisition from content playing by getting the viewing license before the asset playing session begin and not as it is being handled today e.g. during asset playback. why? I need to be able to play assets when the devices have no network, so the license server is unreachable. 

my purpose is, that the offline DRM session will get and store the viewing license before the player start.
I thought that by enabling the session sharing I will be able to share the Keys of the two sessions and prevent the Player from asking for another key. 
Once I’ll see that the player don’t ask for key while playing asset, e.g. my license pre-fetch works, I’ll start asking for OFF-LINE Keys.

I started by adding the asset catalog with the "drm_key_request_properties". 
    "samples": [
      {
        "name": "Brave-PRWV",
        "uri": "file:/mnt/sdcard/assets/Brave-PRWV/Brave-PRWV.mpd",
        "drm_scheme": "widevine",
        "content_id":"Brave-PRWV",
        "content_type":"VOD",
        "drm_key_request_properties": {
          "sessionSharing": "enable"
        }
      },
      
in playerActivity I added a buildOfflineDrmSessionManager that passes the optional keys to the DRM session and I also checked that those parameters are treated in the StreamingDrmSessionManager.postKeyRequest() function. I expected the player to start playing and skip the viewing license request, since I already posted the viewing license.
My Questions:
1. how can I use the WideVine DRM "sesionShere" plugin? Since I’m using a proxy in my system, I did not use the keyRequestProperties as the demo do, so I thought that adding the keyRequestProperties to the “keyRequest = mediaDrm.getKeyRequest(, , ,
    MediaDrm.KEY_TYPE_STREAMING, optionalKeyRequestParameters);”  will do fine for my goal.

 
2. how can I enforce a session sharing property was set to the viewing license ? can the widevine diagnostic tool provide any information (I found none)
3. I kept my buildOfflineDrmSessionManager in global variable so the garbage collector wont dispose my buildOfflineDrmSessionManager.

My playerActivity build drm session function :
 private DrmSessionManager<FrameworkMediaCrypto> buildOfflineDrmSessionManager(UUID uuid, String contentId,String contentType,Map<String, String> keyRequestProperties) throws UnsupportedDrmException {
    if (Util.SDK_INT < 18) {
      return null;
    }
    MDrmManager mdrmMgr          = MDrmManagerImpl.getInstance();
    MediaDrmCallback drmCallbackOffline = mdrmMgr.getMediaDrmCallbackHandler(contentId,contentType,buildHttpDataSourceFactory(false),null,"OFF LINE");
    HashMap<String, String> copyKeyRequestProperties = null;

    if (keyRequestProperties != null) {
        copyKeyRequestProperties = new HashMap<String, String>(keyRequestProperties);
    }

    return new StreamingDrmSessionManager<>(uuid,FrameworkMediaDrm.newInstance(uuid), drmCallbackOffline,copyKeyRequestProperties , mainHandler, eventLogger);

  }   

thank you for your help,
Yaniv

**Comment by ojw28** [comment]
I don't think session sharing is the correct thing to be using. We recently pushed a helper class to make this easier to our dev branch, [here](https://github.com/google/ExoPlayer/blob/dev-v2/library/src/main/java/com/google/android/exoplayer2/drm/OfflineLicenseHelper.java). To acquire an offline license:

1. Create an instance of helper.
1. Call download on the helper (from a non-UI thread, since it will perform some networking). This will acquire an offline license. The return value is a keySetId, which you need to persist for use when performing the offline playback.

You can also use the helper to renew or release an offline license that has been acquired.

To play the content using an acquired offline license:

1. Create a DefaultDrmSessionManager (this has been renamed from StreamingDrmSessionManager because it now supports the offline use case too).
1. Call setMode(MODE_PLAYBACK, keySetId), passing the keySetId for the offline license.
1. Build the player as normal. It should use the offline license for playback.

**Comment by yanivlankry** [comment]
sorry for the late response.
i'll look in to   it and update.
thank you for the guidance.
Yaniv

**Comment by yanivlankry** [comment]
Hi,

1.    I updated my code to support local assets. I’d like to contribute my
work to the global effort.



2.    I have an abnormal behavior  - I keep getting offlineKey as null.
After digging in the code – I think I missed the part where the
offlineLicenseKeySetId is being updated.
the blockingKeyRequest is setting the offlineLicenseKeySetId to null
(marked in red), this triggers the doLicense to take the sessionID
internally, but once the license is returned, I expected the
offlineLicenseKeySetId to be updated.

what do I miss ? thank you for your guidance,
Yaniv Lankry




  public byte[] download(HttpDataSource dataSource, DashManifest
dashManifest)

      throws IOException, InterruptedException, DrmSessionException {



…..



    }

    blockingKeyRequest(DefaultDrmSessionManager.MODE_DOWNLOAD, null,
drmInitData);

    return drmSessionManager.getOfflineLicenseKeySetId();

**Comment by yanivlankry** [comment]
it is working !!!!!

thank you for the guidance.

As I mentioned I added support for local files – how can I contribute my
work ?.

**Comment by ojw28** [comment]
Contributions should be made in the form of pull requests (see [here](https://github.com/google/ExoPlayer/blob/release-v2/CONTRIBUTING.md)). It's unclear exactly what you want to contribute though, since I suspect the changes you made were in your application code rather than in the ExoPlayer library.

**Comment by yanivlankry** [comment]
Hi,
i'd like to go back to my initial question How can i "Pre-Fetch viewing
license for Widevine using sessionShare ?"
your guidance lead me to handle OFF-LINE assets, how do you recommend me to
handle , pre-fetch  viewing license for streaming assets Widevine ?
P.S.
the new dev project you provided has better streaming session manager - i
recommend to migrate it to the trunk.

thank you for you time
Yaniv Lankry
Cisco

**Comment by ojw28** [comment]
The dev branch was migrated to trunk a couple of days ago.

I don't think we really recommend pre-fetching of licenses for streaming. Lots of streaming services have restrictions on simultaneous streaming sessions, so if the user has multiple devices pre-fetching has a tendency to incorrectly stop playbacks on other devices. Maybe that doesn't affect your case, but it's an example of the kind of things that can go wrong when you start doing this. If you license server is fast, it's unclear how large the benefit of pre-fetching licenses is. I'm sure it's possible to do, but it's not something we're going to be spending time providing guidance for at this point in time.

**Comment by yanivlankry** [comment]
one of the scenarios i'm trying to solve is the key expiration. i know that
Exo-player ask for keys only once. so in case of live streaming asset that
its key will be expire - i would like to be able to re-fetch the key.
basically we are using rotating keys and we provide long duration, but i
want to prevent the replay in case of license expiration, and be able to
add more keys during playback is running. this is one of my main reasons
for pre fetch.
Thank you
Yaniv
