### ISSUE TITLE
Determination between Live and VOD

### ISSUE THREAD

**Issue by ChernyshovYuriy** [google/ExoPlayer#2320]
Hi team,

While [new feature](https://github.com/google/ExoPlayer/issues/87) is very cool, many applications depends on previous behaviour, when duration of Live stream is some kind of not in normal range, for instance -1.
Now, with this feature when user can seek within Live stream, what is a way to get know that stream is Live. We can not relay on -1 (or whatever value is) anymore.
Our Library has 3 different types of players and they manageable by common interface.
Now, it is inconsistence in behaviour from ExoPlayer side.
The question is - is there any way that ExoPlayer can notify that stream is Live?

**Comment by ojw28** [comment]
You can query this information from the player's timeline. The demo application does this [here](https://github.com/google/ExoPlayer/blob/r2.1.1/demo/src/main/java/com/google/android/exoplayer2/demo/PlayerActivity.java#L430). Static means VOD. Dynamic means Live.

We should probably add an `ExoPlayer.isDynamic` method for convenience, so you don't have to query the timeline directly. I'll do this.

**Comment by ChernyshovYuriy** [comment]
Thanks guys for the support.
