### ISSUE TITLE
Background Media Playing (Surface turns green upon return)

### ISSUE THREAD

**Issue by anup1245** [google/ExoPlayer#2321]
We want our app to continue playing in the background in audio mode, so onSurface destroyed callback, we called clearVideoSurface(); and upon returning set the surface in onSurfaceCreated player.setVideoSurface(holder.getSurface());
But the view becomes green in color.
Not releasing the player in onStop or onPause.

Using v2.1.1

Steps to reproduce : playvideo -> home button -> open the app again

![test_exo](https://cloud.githubusercontent.com/assets/13576553/21917908/8498bda4-d900-11e6-907d-b6bcfaa6b4d8.png)

**Comment by ojw28** [comment]
We'll take a look at this if you provide us with an easy way to reproduce. Please can you provide the exact changes you've made to the demo app either as a pull request, or as a change in a fork you've made of the project? That way we can see exactly what you've done and reproduce without any guesswork. Thanks!

**Comment by anup1245** [comment]
Hi @ojw28 

The changes :
player_activity.xml we changed from SimpleExoPlayerView to Surface View
```
<SurfaceView
      android:id="@+id/player_view"
      android:layout_width="match_parent"
      android:layout_height="match_parent"/>
```
In Player activity :
onCreate method :
```
surfaceView = (SurfaceView) findViewById(R.id.player_view);
SurfaceHolder holder = surfaceView.getHolder();
holder.addCallback(this);
```
In SurfaceHolder.Callback:
```
@Override
  public void surfaceCreated(SurfaceHolder surfaceHolder) {
    player.setVideoSurface(surfaceHolder.getSurface());
  }

@Override
  public void surfaceDestroyed(SurfaceHolder surfaceHolder) {
    player.clearVideoSurface();
  }
```
And 
```
@Override
  protected void onDestroy() {
    super.onDestroy();
    releasePlayer();
  }
```
Not releasing player in onPause or onStop

Steps to reproduce:
1) Youtube DASH -> Google Glass (MP4,H264) 
2) Press Home Button
3) Recent Apps -> Select the app again
(It plays first time)

Again repeat the steps from 2nd step 
Screen turns green

Thanks

**Comment by RamIndani** [comment]
@anup1245 You closed this issue, I would like to know if you found a solution to this problem as I am also facing the same issue. Thanks (I am not asking for code, I am asking if you did any lifecycle changes).

**Comment by akarekal-coursera** [comment]
@RamIndani I was trying it on the emulator, but then saw that its advised to play on physical device.
On physical device it does not happen.
