### ISSUE TITLE
Read spatial audio metadata of a video (the metadata generated from "Spatial Media Metadata Injector")

### ISSUE THREAD

**Issue by Kexiliu** [google/ExoPlayer#2322]
I'm trying to read spatial audio metadata of a video from exoplayer, and couldn't find a way to do so. The metadata is generated from "Spatial Media Metadata Injector" here: https://github.com/google/spatial-media/tree/master/spatialmedia

and the information injected should be like this:
https://github.com/google/spatial-media/blob/master/docs/spatial-audio-rfc.md

![screen shot 2017-01-13 at 12 21 35 pm](https://cloud.githubusercontent.com/assets/8369355/21918296/f3525aea-d98a-11e6-8028-8fa8dd8f6086.png)

I tried to get the metadata from standard MediaMetadataReceiver but couldn't seem to do it. Any help would be greatly appreciated.

**Comment by ojw28** [comment]
This is not something we currently support. @dcower - Is that correct? What's the metadata generally used for? Would it be the audio renderer that needs it, if anyone, or is there value to exposing it all the way out to the user of the player?

**Comment by dcower** [comment]
@ojw28 That's correct -- this is not currently supported in ExoPlayer.

The metadata is used to signal the presence of spatial (ambisonic) audio in 360 media. AFAIK it's only used to signal that for upload to YouTube/Facebook/etc.; i.e., it's used as an ingest/upload format.

There are a few options I see here:
1) Don't support it. Just use the channel count to determine if the media has spatial audio (not ideal, but works pretty well if you only care about 360 videos); I think this allows instantiating a different audio renderer, similar to 3) below.
2) Support it and plumb metadata to the audio renderer only. This requires the audio renderer implementation to have some kind of fallback handling logic if you want to also support non-spatial audio, I think.
3) Support it and plumb metadata to the user of the player. This allows the player to instantiate a different audio renderer depending on presence of spatial audio.

**Comment by Kexiliu** [comment]
@ojw28 @dcower thank you both for answering my questions :) greatly appreciated!!

**Comment by ojw28** [comment]
It sounds like this metadata is used for ingest/upload, and so I think option (1) (not supporting it) sounds fine. Closing.
