### ISSUE TITLE
Minumum SDK version

### ISSUE THREAD

**Issue by dreich** [google/ExoPlayer#2324]
Hello, dear author!

Can you tell, what are minimal versions of SDK for two separate needs (two apps):
1) Playing HLS stream
2) Playing mp3 stream

I'm asking because I'd like to embrace as much people (and their old devices) as possible.
Thank you.

**Comment by ojw28** [comment]
This is explained [here](https://google.github.io/ExoPlayer/supported-devices.html).

**Comment by dreich** [comment]
I hope that compiling my project with "minSdkVersion 9" (thank you for this) I can use conditional statements to use MediaPlayer or ExoPlayer depending on device SDK version. If version < 16, use MediaPlayer, else use ExoPlayer.
Owing to the possible "minSdkVersion 9" I can embrace many old devices (<16) using MediaPlayer.
Am I right?

Thank you.

**Comment by ojw28** [comment]
That's correct, yes. It's your decision of course, but is it worth the extra work to target the ~2% (and decreasing) fraction of Android devices that are still running < 16? See the distribution of Android devices [here](https://developer.android.com/about/dashboards/index.html).

**Comment by dreich** [comment]
Thank you for care.
In my app that is 5,6% of live people using the app :) and I don't want to abandon them.
