### ISSUE TITLE
Get Current Uri MediaSource

### ISSUE THREAD

**Issue by belovolll** [google/ExoPlayer#2328]
Hi!I have two media source uri.

When i call seekToDefaultPosition(pos), i got call onTracksChanged and onTimelineChanged callbacks.

But, i don't know how get current uri media source after call seekToDefaultPosition(pos).

My code snippet:

``DefaultBandwidthMeter bandwidthMeter2 = new DefaultBandwidthMeter();
        
        DataSource.Factory dataSourceFactory = new DefaultDataSourceFactory(this,
                Util.getUserAgent(this, "yourApplicationName"), bandwidthMeter2);
      
        ExtractorsFactory extractorsFactory = new DefaultExtractorsFactory();
       
        MediaSource firstsource = new ExtractorMediaSource(Uri.parse("http://exampleurl.ru"),
                dataSourceFactory, extractorsFactory,10,null,null);
        MediaSource secondSource = new ExtractorMediaSource(Uri.parse("http://exampleurl.ru"),dataSourceFactory, extractorsFactory,10,null,null);

         ConcatenatingMediaSource concatenatedSource =
              new ConcatenatingMediaSource(firstsource,secondSource);
        concatenatedSource.prepareSource(mPlayer, true, this);
        mPlayer.prepare(concatenatedSource);``

Any help will be appreciated.

**Comment by ojw28** [comment]
I'm a little unclear what you're after here. If you're passing the uris into the player, don't you already know what they are? You can query the index of the media currently being played using [ExoPlayer.getCurrentWindowIndex](https://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/ExoPlayer.html#getCurrentWindowIndex--). Is that sufficient to resolve your question? Thanks!

**Comment by belovolll** [comment]
I thought there was a way to get the current url directly. And so it turns out that I need to store an array of uri separately and accessed by index.

**Comment by ojw28** [comment]
Yes, keeping the array yourself is the best way to do this.
