### ISSUE TITLE
STATE_ENDED not detected r2.1.1

### ISSUE THREAD

**Issue by Naguchennai** [google/ExoPlayer#2332]
STATE_ENDED not detected. Video repeating , looping never stoped. if i remove " exoplayerview.setPlayer(exoplayer);" only audio playing not repeating 

 ` BandwidthMeter defaultBandWidthMeter = new DefaultBandwidthMeter();
        TrackSelection.Factory videoTrackSelectionFactory =
                new AdaptiveVideoTrackSelection.Factory(defaultBandWidthMeter);
        TrackSelector trackSelector = new DefaultTrackSelector(videoTrackSelectionFactory);
        LoadControl loadControl = new DefaultLoadControl();
        exoplayer = ExoPlayerFactory.newSimpleInstance(this, trackSelector, loadControl);
        exoplayerview.setPlayer(exoplayer);
       // exoplayer.setPlayWhenReady(true);
        DataSource.Factory dataSourceFactory = new DefaultDataSourceFactory(
                this,
                Util.getUserAgent(this, getString(R.string.app_name)),
                (DefaultBandwidthMeter) defaultBandWidthMeter
        );
        ExtractorsFactory extractorsFactory = new DefaultExtractorsFactory();
        MediaSource videoSource = new ExtractorMediaSource(
                Uri.parse(VIDEO_URL),
                dataSourceFactory,
                extractorsFactory,
                null, null
        );
        LoopingMediaSource loopingSource = new LoopingMediaSource(videoSource);
        exoplayer.prepare(loopingSource);

        exoplayer.addListener(new ExoPlayer.EventListener() {

            @Override
            public void onLoadingChanged(boolean isLoading) {
                Log.v("isLoading","Listener-onLoadingChanged...");

            }

            @Override
            public void onPlayerStateChanged(boolean playWhenReady, int playbackState) {
                Log.v("playWhenReady","Listener-onPlayerStateChanged...");

                switch(playbackState) {
                    case ExoPlayer.STATE_BUFFERING:
                        videoprogressBar.setVisibility(View.VISIBLE);
                        exo_play.setVisibility(View.GONE);
                        exo_pause.setVisibility(View.GONE);
                        break;
                    case ExoPlayer.STATE_ENDED:
                        exoplayer.setPlayWhenReady(false);
                        exoplayer.seekTo(0,0);
                        Toast.makeText(VideoView_Activity.this, "stoped", Toast.LENGTH_LONG).show();
                        Log.v("naagu","Listener-onLoadingChanged...");
                        break;
                    case ExoPlayer.STATE_IDLE:
                        break;

                    case ExoPlayer.STATE_READY:
                        if (exoplayer.getPlayWhenReady()) {
                            videoprogressBar.setVisibility(View.GONE);
                        } else {

                        }
                        break;
                    default:
                        break;
                }

            }

            @Override
            public void onTimelineChanged(Timeline timeline, Object manifest) {
                Log.v("timeline","Listener-onTimelineChanged...");

            }

            @Override
            public void onTracksChanged(TrackGroupArray trackGroups, TrackSelectionArray trackSelections) {

            }

            @Override
            public void onPlayerError(ExoPlaybackException error) {

            }

            @Override
            public void onPositionDiscontinuity() {
                Log.v("onPositionDiscontinuity","Listener-onPositionDiscontinuity...");

            }
        });
        exoplayer.setPlayWhenReady(true);
`

**Comment by AquilesCanta** [comment]
This is working as intended. As you mention, you are using a LoopingMediaSource, so the player doesn't end because the media goes on "_forever_".

Could you please clarify:
>  if i remove " exoplayerview.setPlayer(exoplayer);" only audio playing not repeating

If you remove that line the player actually reaches ENDED state? Or it doesn't but the audio doesn't loop, as it would with the line.

**Comment by Naguchennai** [comment]
@AquilesCanta thank you my mistake
