### ISSUE TITLE
CryptoException error during playback

### ISSUE THREAD

**Issue by replystreamingwidevine** [google/ExoPlayer#2334]
During playback of some content,  we get a CryptoException error after a couple of minutes of playback with some content (not all). We are experiencing this issue on specific devices like Samsung Tab S2 and Samsung Tab S. We are using version 1.5.9 version of Exoplayer

Here the log that we have for this CryptoException
```
01-13 12:01:40.751 2600-10202/? E/wv_dash: Trustlet did not send a valid return code: 0xd
01-13 12:01:40.751 2600-10202/? E/wv_dash: tee_send_msg_general_cmd is failed.
01-13 12:01:40.751 2600-10202/? E/wv_dash: process drm decrypt CTR failed
01-13 12:01:40.751 2600-10202/? E/WVCdm: Decrypt error result in session sid5 during encrypted block: 1
01-13 12:01:40.756 9738-11049/it.anywhere E/ExoPlayerImplInternal: Internal track renderer error.
                                                                      com.google.android.exoplayer.ExoPlaybackException:android.media.MediaCodec$CryptoException: Error decrypting data
```

Moreover, after such error, we see in the log that the device seems not able to initialize DRM in Security Level 1 anymore. Here the snippet of log related to this situation:

```
01-13 12:05:52.551 2600-10201/? D/WVCdm: Instantiating CDM.
01-13 12:05:52.556 2600-3026/? I/WVCdm: CdmEngine::QueryStatus
01-13 12:05:52.556 2600-3026/? I/WVCdm: Level3 Library Sep 25 2014 17:10:03
01-13 12:05:52.556 2600-3026/? W/WVCdm: Could not read /data/mediadrm/IDM1013/ay64.dat2: No such file or directory
01-13 12:05:52.581 2600-3026/? E/wv_dash: No saved usage table. Creating new table.
01-13 12:05:52.601 2600-3026/? E/wv_dash: Trustlet did not send a valid return code: 0x1
01-13 12:05:52.601 2600-3026/? E/wv_dash: tee send dash_init fail
01-13 12:05:52.601 2600-3026/? E/wv_dash: process drm initialize failed
01-13 12:05:52.626 2600-3026/? W/WVCdm: Could not initialize L1. Falling Back to L3.
01-13 12:05:52.626 2600-3026/? I/WVCdm: L3 Terminate.
```

Moreover some cryptographic capabilities seems to be corrupted and we are not able to decrypt data that previously we were able to decrypt

The error seems to be very related to https://github.com/google/ExoPlayer/issues/1910. 

Thanks for your support

**Comment by replystreamingwidevine** [comment]
Any news on this topic?
Many thanks in advance

**Comment by wvpaf** [comment]
@replystreamingwidevine please provide full bugreport, logcat, and a link to working and non working content.

thanks,

**Comment by replystreamingwidevine** [comment]
Is there a private mail where we can send you the apk and all the information you need?

**Comment by andrewlewis** [comment]
@replystreamingwidevine Please send it to dev.exoplayer@gmail.com.

**Comment by replystreamingwidevine** [comment]
Info shared by mail. Thanks for the support

**Comment by wvpaf** [comment]
@replystreamingwidevine, thank you for the logcat but can you please provide the ADB Bugreport. That would have more data. 
thanks.

**Comment by replystreamingwidevine** [comment]
Bugreport sent via mail
Thanks

**Comment by wvpaf** [comment]
@replystreamingwidevine I have reviewed a bugreport with 'Dumpstate : 2017-01-31 11:40:01" heading. If this is indeed a Bugreport that you sent in email, I do not think it captures the behavior for this issue, I am not finding and CTR decryption errors.

**Comment by replystreamingwidevine** [comment]
Please check this line in the bugreport

01-31 11:39:37.273  8229  9943 E ExoPlayerImplInternal: com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.rk.video_decoder.avc.secure, MediaFormat(1, video/avc, -1, -1, 640, 360, 0, 1.0, -1, -1, null, -1, false, 854, 480, -1, -1, -1)

This is the root cause of the issue

**Comment by replystreamingwidevine** [comment]
You are checking bug report for ticket 2380. You should check my mail sent to dev.exoplayer@gmail.com on Monday around 10:48 UTC time

**Comment by wvpaf** [comment]
Oh i see, apologies there is a bit of a file shuffle on this side.
Let me go review that log.

**Comment by wvpaf** [comment]
I noted that you have opened a case with the WV CWIP Team.  
We should continue the troubleshooting there.
I will post a follow up with findings.

**Comment by wvpaf** [comment]
This has been assigned for followup with the device manufacture. No updates as of 2/20/17.

**Comment by wvpaf** [comment]
Sadly no new updates from OEM, there are issues with reproducing the issue on their side.

**Comment by wvpaf** [comment]
Looks like Samsung pushed updates back in Mar/Apr. Not sure if the carrier involved picked up the fixes.
