### ISSUE TITLE
Playing a particular resolution video in offline mode (DASH) 

### ISSUE THREAD

**Issue by Abilashinamdar** [google/ExoPlayer#2340]
My manifest(mpd) file contains multiple resolution videos(like 180p, 360p, 720 etc), i manually parsed the mpd file & downloaded all the video files and stored it in my Local Storage. When I play the video using this manifest file in offline mode, it is playing fine. Now I have deleted the 180p & 360p resolution files. Now when I try to play the video using the same **Manifest** file , it is not playing . `onLoadError ` is getting called with the deleted file uri.  How to configure to player to play only a particular resolution video that is available to play in offline mode ?

**Comment by WeiChungChang** [comment]
The problem seems to be that the manifest still contains the representations which include the deleted videos. When bit-rate switches, it may instruct the player to load a deleted video. I guess that is why the   **onLoadError** happens. 
Maybe the fast way to test is manually remove the representations related to the deleted videos from MPD and see if it works.

**Comment by Abilashinamdar** [comment]
That's what i don't want to remove any representations from the MPD, i want to play only existing files which are stored in my Local Storage. That any how it will works if i remove representations from the MPD but i don't want to touch the MPD.
Is there a way to configure the player to play only existing files? OR
Do we need to add any workaround code to make the player to play existing files?

**Comment by ashwanijanghu** [comment]
@Abilashinamdar Can you present any sample to play offline stored videos, I am able to download license offline and stored-retrieve it from native media drm. Need a sample to play video from local storage. Thanks in advance.

**Comment by ojw28** [comment]
Officially supporting offline mode is tracked by https://github.com/google/ExoPlayer/issues/2643.
