### ISSUE TITLE
How to create MutliPeriod or MultiWindow Timeline from single media file?

### ISSUE THREAD

**Issue by skuppa** [google/ExoPlayer#2342]
Is it possible to create MultiPeriod or MultiWindow Timeline from a single media file.

For example, if my media file is playing for 10 minutes then is it possible to create period/window for each 1 minute. It is like creating playlist from single media file consist of 10 playable windows.

Thanks, 
-Kuppa

**Comment by ojw28** [comment]
I don't really see why you'd want to do this. If it's just to make the UI appear differently (i.e. as though the content consists of multiple pieces of media with << and >> skip buttons) then it seems more appropriate to customise the UI, not fake a structure for the media that's not really true.

**Comment by skuppa** [comment]
Thank you for responding my question.

I am trying to index the big video with multiple chapters like DVD menu, and let user skip to next chapter or pick any chapter as per his needs.

**Comment by ojw28** [comment]
As above, I think you should implement this kind of thing in your own UI above the player. The timeline represents the structure of the media being played. Faking the structure of the media just because the default UI components use it isn't the right solution.

**Comment by skuppa** [comment]
Thanks for the suggestion.  Here is my use case, please advise me to the right direction..  I have video files that was shot in multiple angles and all video files have same timings.   I need to play video by switching the different angled's video file without any gaps.  My example as follows (I use second instead of microsecond):

 Assume, I have two video files.
Clip1_Angle1.mp4 (120 seconds)
Clip1_Angle2.mp4 (120 seconds)

And I expect my player should be playing
Clip1_Angle1.mp4 (0-5s) -> Clip1_Angle2.mp4(6s-10s) -> Clip1_Angle1.mp4 (11-15s) -> Clip1_Angle2.mp4(16s-20s) ->...

Thanks,
-Kuppa

**Comment by andrewlewis** [comment]
@skuppa Can you use a ConcatenatingMediaSource joining several ClippingMediaSources, where each of those has the required start/end position and wraps an ExtractorMediaSource with the required URI? Note that for seamless video playback you'll need to ensure that the start time of every ClippingMediaSource is a keyframe (see #1988). It's fine to load the same URI more than once in different sources.

**Comment by skuppa** [comment]
Thank you Andrew.  This is really helps.
