### ISSUE TITLE
Manifest fetching while Live stream on Pause

### ISSUE THREAD

**Issue by ChernyshovYuriy** [google/ExoPlayer#2348]
Dear colleagues,

I am wondering whether it is work as designed when channel manifest fetching while Live stream is on Pause?

To detect such behaviour I simple log callback "onTransferStart" on the listener assigned to "HttpDataSource" implementation.

Regards,

**Comment by ojw28** [comment]
Yes, it is. Otherwise there's no way to track changes in the live window. If you really want the player to be torn down completely then you should stop (or release) the player and prepare it again when it's next required.
