### ISSUE TITLE
ExoPlayer with MediaBrowserServiceCompat compability

### ISSUE THREAD

**Issue by GokhanArik** [google/ExoPlayer#2349]
Hi, 

I read that ExoPlayer works well with `MediaBrowserServiceCompat`, but I'm having issues setting the player to the view.

My `ExoPlayer` instance is inside the `MediaBrowserServiceCompat` and I have to access this player inside the activity. Is there any way to use it without calling `setPlayer()` method or communicate with the activity?

**Comment by ojw28** [comment]
This doesn't sound like an ExoPlayer issue (I didn't even know what MediaBrowserServiceCompat was until I looked it up). I suggest you ask this question on StackOverflow.
