### ISSUE TITLE
inputBuffers are not updated when doing adaptive reconfiguring

### ISSUE THREAD

**Issue by kanongil** [google/ExoPlayer#235]
In `MediaCodecTrackRenderer`, the `inputBuffers` are not re-obtained after `onInputFormatChanged` for adaptive codecs.

This causes issues for the h.264 video codec when it starts on a low resolution & profile, and is changed to a higher profile. Once this has occurred, the capacity of the `inputBuffers` can be too small to handle large input frames, which will cause the HLS demuxer to throw an exception in [`TsExtractor#convert()`](https://github.com/google/ExoPlayer/blob/0414b0d2f6cfda21c1db13166ff55d4b6cd20d2c/library/src/main/java/com/google/android/exoplayer/hls/TsExtractor.java#L290).

A simple fix for this issue is to treat all codecs as non-adaptive, but I'm sure there is a better solution.

**Comment by ojw28** [comment]
The input buffers aren't supposed to be re-obtained. They're supposed to be large enough already. In HlsChunkSource maxWidth and maxHeight indicate the maximum dimensions of the video. We attempt to infer the maximum from the resolutions indicated in the master playlist. These are optional, so we default to assuming 1080p if they're missing.

Are you attempting to switch to something higher than 1080p? If not, what resolution are you switching to, how big is the input buffer that's not big enough, and how big is the frame? Thanks!

**Comment by ojw28** [comment]
Note - There is a typo in the code that calculates maxHeight in HlsChunkSource (I'll fix this), but unless your video is taller than it is wide, that wouldn't cause the issue you're seeing.

**Comment by kanongil** [comment]
@ojw28 Let me check for you.

FYI, this works and allocates larger buffers on upswitching when I force disable adaptive support.

**Comment by ojw28** [comment]
Ok. Knowing what device + build you're running would also be useful. It sounds a bit like a device specific error where the buffers aren't being sized to be large enough. However if that's the case we can likely fix it by explicitly requesting larger ones using http://developer.android.com/reference/android/media/MediaFormat.html#KEY_MAX_INPUT_SIZE

**Comment by kanongil** [comment]
I tried MAX_INPUT_SIZE which resulted in a crash in the OMX layer.

Device: Samsung Galaxy Tab S 8.4 with Android 4.4.2
Codec: OMX.Exynos.avc.dec
MediaFormat: `{max-height=1280, height=224, csd-0=java.nio.ByteArrayBuffer[position=0,limit=27,capacity=27], max-width=1280, width=400, csd-1=java.nio.ByteArrayBuffer[position=0,limit=7,capacity=7], mime=video/avc, com.google.android.videos.pixelWidthHeightRatio=1.0}`.
Buffer capacity: `134400`.

If I force it to be non-adaptive, it will switch to use the high-quality MediaFormat: `{max-height=1280, height=720, csd-0=java.nio.ByteArrayBuffer[position=0,limit=30,capacity=30], max-width=1280, width=1280, csd-1=java.nio.ByteArrayBuffer[position=0,limit=7,capacity=7], mime=video/avc, com.google.android.videos.pixelWidthHeightRatio=1.0}`.
Capacity: `1382400`.

I'm thinking that either the `max` attributes are being ignored, or it is dependent on the `csd` values.

**Comment by kanongil** [comment]
Also, this does indeed seem to be device specific, as a test on another device allocated the large buffer on the first try.

**Comment by ojw28** [comment]
What value did you set MAX_INPUT_SIZE to when you attempted to set it? I'm guessing you tried 1382400, but if you didn't then it would be interesting if you could try that exact value.

**Comment by kanongil** [comment]
I did not try that exact value. I will fiddle around with a bit when I get back to work (where I have the device) tomorrow, and see if I can force it to allocate & handle large buffers.

**Comment by kanongil** [comment]
Ok, so I tried to simply force the width & height to equal the max values in `MediaFormat#maybeSetMaxDimensionsV16()`, and it allocates the correct buffer size (once I fixed the max-height bug). Maybe the "solution" to this issue is to just do this for all adaptive video codecs?

**Comment by ojw28** [comment]
That sounds quite likely to break something else. Setting MAX_INPUT_SIZE is the correct solution, if it can be made to work. Does it work if you set it to 1382400 (not that this is quite right either, but it will give an idea of whether a MAX_INPUT_SIZE based solution is possible)?

**Comment by ojw28** [comment]
Closing due to lack of response.
