### ISSUE TITLE
ExoPlayer v2 m3u8 embedded subtitles

### ISSUE THREAD

**Issue by davidmullis** [google/ExoPlayer#2351]
Hello
I'm using ExoPlayer v2.1.1 (SimpleExoPlayer with SimpleExoPlayerView) in my AndroidTV app. I'm getting an m3u8, to stream HLS video, which works fine.
The m3u8 may also contain webvtt subtitles files. When it does, I can call simpleExoplayer.getCurrentTrackGroups() on simpleExoplayer.getCurrentTrackSelections() and see that the subtitle track is there, but I don't see subtitles displayed on screen.
Can someone tell me the steps involved in displaying subtitles embeded in the m3u8?

A typical m3u8 that I teg looks like this:
>>>#EXTM3U
>>>#EXT-X-VERSION:7
>>>#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP->>>ID="subs",NAME="English",LANGUAGE="en",URI="https://skyfire.vimeocdn.com/1484861501->>>0x6435e2d69a681dc87e6f564c6292cc17074c31a5/166148372/subtitles/4771771/playlist.m3u8?d=2676.760000"

>>>#EXT-X-STREAM-INF:SUBTITLES="subs",PROGRAM-ID=1,BANDWIDTH=719749,AVERAGE->>>BANDWIDTH=618000,RESOLUTION=640x360,FRAME->>>RATE=25.000,CODECS="avc1.4D4016,mp4a.40.2"
>>>https://skyfire.vimeocdn.com/1484861501-0x6435e2d69a681dc87e6f564c6292cc17074c31a5/166148372/video/529178294/playlist.m3u8
>>>#EXT-X-STREAM-INF:SUBTITLES="subs",PROGRAM-ID=1,BANDWIDTH=1985961,AVERAGE->>>BANDWIDTH=1436000,RESOLUTION=960x540,FRAME->>>RATE=25.000,CODECS="avc1.64001F,mp4a.40.2"
>>>https://skyfire.vimeocdn.com/1484861501-0x6435e2d69a681dc87e6f564c6292cc17074c31a5/166148372/video/529178301/playlist.m3u8
>>>#EXT-X-STREAM-INF:SUBTITLES="subs",PROGRAM-ID=1,BANDWIDTH=3352398,AVERAGE->>>BANDWIDTH=1718000,RESOLUTION=1280x720,FRAME->>>RATE=25.000,CODECS="avc1.640020,mp4a.40.2"
>>>https://skyfire.vimeocdn.com/1484861501-0x6435e2d69a681dc87e6f564c6292cc17074c31a5/166148372/video/529178296/playlist.m3u8

**Comment by AquilesCanta** [comment]
They should be being displayed. If you would kindly:

1. Play the stream in the demo app.
2. Make sure the text track is selected.
3. Make sure there are cues in the WEBVTT files.
4. See if the subtitles are displayed.

If subtitles are displayed, then you are forgetting something in your app. Most likely, the text track is not being selected.

If subtitles are not displayed, please send a link to your stream to dev.exoplayer@gmail.com and make sure it is not geo-restricted or invalid. The links you published give me 403 or 410. Thanks!

**Comment by davidmullis** [comment]
Hi quilesCanta
Thanks for the quick reply.
Before I do that, I think my issues that the track is not selected can you tell me how to set a texttrack to selected.
If that doesn't work then I'll go through the above steps.

**Comment by davidmullis** [comment]
Hi again,
I used the ExoPlayer sample app and it is displaying the subtitles, so you're right. It's definitely something I'm missing in my code.
Would you kindly explain the steps involved is setting the text track to selected?

**Comment by AquilesCanta** [comment]
Have a look at DemoApp for a precise guide on how to do it. It's not much code. [This medium post](https://medium.com/google-exoplayer/exoplayer-2-x-track-selection-2b62ff712cc9) might also shed some light on track selection. Unfortunately, the issue tracker is not a good place for stack exchanging.
