### ISSUE TITLE
HLS - Format adapts at start even when a fixed track selection is used

### ISSUE THREAD

**Issue by ojw28** [google/ExoPlayer#2353]
See #2343. For HLS playback in V2 we always start playing out the first track in the master playlist, even if it's not present at all in the track selection. For example if the track selector has chosen a different track as a fixed track selection.

We should not start playing out the first track in the case that it's not present in the track selection at all. Aside from being confusing, it could cause failures (e.g. if the first track in the master playlist happens to be one that exceeds device capabilities).

**Comment by b95505017** [comment]
So after v2.3.0 released, is `InitializationTrackSelection` in `HlsChunkSource` still need?

**Comment by ojw28** [comment]
This is now fixed. Yes, it's still needed internally.

**Comment by b95505017** [comment]
I'm confused a little bit, how does the `InitializationTrackSelection` interact with the track selection from outside after v2.3.0? 
If we want player always start from the format in the middle of the bandwidth in playlist. (e.g. 240p, 360p, 720p, always start from 360p) Use track selection from outside is enough or we still have to modify InitializationTrackSelection?

**Comment by ojw28** [comment]
Outside is sufficient to get the format you want. Internally we may request a fraction of a segment from some other format, determined by `InitializationTrackSelection`, but any media loaded as a result wont be played out.

**Comment by Prawez** [comment]
Hi There,

I am using latest version of exoplayer and it is working perfectly fine at our end. However I have faced issue to show different bit rates from HLS video file. I am always getting current bit rate profile. I want to show all bit rates profile and allow user to chose any one of them.

Please assist me how I could achieve this? Any help really appricated.
