### ISSUE TITLE
Player stops after a few minutes

### ISSUE THREAD

**Issue by Moussine89** [google/ExoPlayer#2354]
I have player working with a url stream from internet ,when i start the player it works fine but when i turn off the device screen a few minutes later (5 to 7 minutes) it stops and doesn't recover until i turn on the screen. I need your help .

Steps on the ExoPlayer demo :

1-I went to SmoothStreaming -> SuperSpeed -> the player start fine 
2-I turn off the device screen
3-After a few minutes the player stops without automatic recovery
4-I turn on the device screen and the player recovers

My device : Nexus 5X 

Thanks a lot for your time.

**Comment by andrewlewis** [comment]
Background/screen off playback has been discussed on this issue tracker several times before -- in future, please search for an answer in previous issues before filing a new one. In this case, I suggest reading #930, #1826, #2276 and #421.

**Comment by Moussine89** [comment]
Thanks a lot and forgive my ignorance im new here :)
