### ISSUE TITLE
Support CEA-608 embedded in video representations in DASH

### ISSUE THREAD

**Issue by ojw28** [google/ExoPlayer#2362]
As per title.

**Comment by Natarajan92** [comment]
Hi ojw28,

As you marked it as enhancement , the updated version of Exo-Player will support embedded CEA-608 captions of video in Dash Streaming ? 

According to Dash-IF-IOP document, we use to signal the CEA-608  in manifest file as follows 

```
<Accessibility schemeIdUri="urn:scte:dash:cc:cea-608:2015"/>
```

Will it display CC by using updated version of Exo-Player ?

**Comment by ojw28** [comment]
That's the intention, yes. We're not promising to add support, but it's something we're actively looking at. This issue will be used to track any work in this area. If we do add support, it's likely that we will require the Accessibility element to be present in the AdaptationSet for CEA-608 to be enabled. It sounds like you're already adding it.

It would be preferable, although likely not required, if you could also fill out the `value` of the Accessibility element to indicate the language (and multiple channels, if applicable). This is described in the DASH-IF-IOP document also.

**Comment by ojw28** [comment]
Specifically, the most useful thing for the client would be if you used values of the form:
```
CC1=eng;CC3=deu
```

**Comment by ojw28** [comment]
This functionality should be working now in `dev-v2`. Please give it a try.

There's still one technical issue where events might go missing when seeking short distances and/or toggling the cea-608 tracks on and off, so the issue is kept open to track fixing that. It's unlikely to be much of an issue in practice, however.

**Comment by Natarajan92** [comment]
Ok! I will give a try and let you know . Thanks

**Comment by ojw28** [comment]
Marking as fixed. We'll track the remaining minor issue separately.
