### ISSUE TITLE
Adding ID3 Length tag support

### ISSUE THREAD

**Issue by Behrouz-m** [google/ExoPlayer#2364]
Hi. I know Exoplayer does not rely on ID3 Length tag but it is very useful that you implement this feature as an option for developers. I have a web server that converts opus to wav and then wav to mp3 on the fly to support all devices that are connecting to it. The problem is Exoplayer does not read ID3 Length and the web server just does not know the length of the generated mp3. So, the mp3 file will be served in http chunks but the audio length is added to ID3 length tag. So, if Exoplayer supports this tag (at least as a developer option) it is very helpful.
thanks.

**Comment by ojw28** [comment]
This isn't something we'll be supporting. You can add support in your own fork if you really need it. I suspect there are much better ways you could set this up on the server side that would avoid this problem.
