### ISSUE TITLE
Audio Focus and android.media.AUDIO_BECOMING_NOISY control in Exoplayer ?

### ISSUE THREAD

**Issue by bbincybbaby** [google/ExoPlayer#2367]
How to implement audio focus and audio becoming noisy in Exoplayer, which used only for streaming Audio ?

**Comment by ojw28** [comment]
Handling of audio focus is pretty much independent of the player, as far as I know. You listen to the broadcast, and then call whatever methods you want to change the state of the player (e.g. pausing it, stopping it, or whatever logic you require) when a broadcast event is received.

This is exactly the same as what you'd do if you were using MediaPlayer or any other third party player, also, so unless I've missed something I suggest you look for general tutorials on the issue.
