### ISSUE TITLE
 exoplayer-r2.1.1 error with shoutcast stream (Unable to connect to)

### ISSUE THREAD

**Issue by github8866** [google/ExoPlayer#2368]
Hello,
I have this problem : 
Exoplayer-r2.1.1 with eclipse cant play shoutcast stream url while icecast server url work well
the return err:
01-24 11:46:57.508: E/ExoPlayerImplInternal(18585): com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to http://radio.108.pl:8004/;stream/1

full error log:

01-24 11:57:24.238: E/ExoPlayerImplInternal(20813): Source error.
01-24 11:57:24.238: E/ExoPlayerImplInternal(20813): com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to http://radio.108.pl:8004/;stream/1
01-24 11:57:24.238: E/ExoPlayerImplInternal(20813): 	at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:204)
01-24 11:57:24.238: E/ExoPlayerImplInternal(20813): 	at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:123)
01-24 11:57:24.238: E/ExoPlayerImplInternal(20813): 	at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:618)
01-24 11:57:24.238: E/ExoPlayerImplInternal(20813): 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
01-24 11:57:24.238: E/ExoPlayerImplInternal(20813): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
01-24 11:57:24.238: E/ExoPlayerImplInternal(20813): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
01-24 11:57:24.238: E/ExoPlayerImplInternal(20813): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
01-24 11:57:24.238: E/ExoPlayerImplInternal(20813): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
01-24 11:57:24.238: E/ExoPlayerImplInternal(20813): 	at java.lang.Thread.run(Thread.java:841)
01-24 11:57:24.238: E/ExoPlayerImplInternal(20813): Caused by: java.net.ProtocolException: Unexpected status line: ICY 200 OK
01-24 11:57:24.238: E/ExoPlayerImplInternal(20813): 	at com.android.okhttp.internal.http.RawHeaders.setStatusLine(RawHeaders.java:108)
01-24 11:57:24.238: E/ExoPlayerImplInternal(20813): 	at com.android.okhttp.internal.http.RawHeaders.fromBytes(RawHeaders.java:308)
01-24 11:57:24.238: E/ExoPlayerImplInternal(20813): 	at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:135)
01-24 11:57:24.238: E/ExoPlayerImplInternal(20813): 	at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:644)
01-24 11:57:24.238: E/ExoPlayerImplInternal(20813): 	at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:347)
01-24 11:57:24.238: E/ExoPlayerImplInternal(20813): 	at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:296)
01-24 11:57:24.238: E/ExoPlayerImplInternal(20813): 	at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:503)
01-24 11:57:24.238: E/ExoPlayerImplInternal(20813): 	at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:201)
01-24 11:57:24.238: E/ExoPlayerImplInternal(20813): 	... 8 more

my phone SDK 4.4.2
Here the code that play the stream:

				DefaultBandwidthMeter bandwidthMeter = new DefaultBandwidthMeter();
				ExtractorsFactory extractorsFactory = new DefaultExtractorsFactory();
				DataSource.Factory 	dataSourceFactory = new DefaultDataSourceFactory(cntx,
						Util.getUserAgent(cntx, "streamradio"), bandwidthMeter);
				
				MediaSource StreamSource = new ExtractorMediaSource(
						Uri.parse(Globalvar.rd_url), dataSourceFactory,
						extractorsFactory, null, null);
				StartActivity.md_player.prepare(StreamSource);
				StartActivity.md_player.setPlayWhenReady(true);

Thank you

**Comment by andrewlewis** [comment]
The relevant error is `java.net.ProtocolException: Unexpected status line: ICY 200 OK`. See #890 and #1211. We don't directly support ICY but you can try using the [okhttp extension](https://github.com/google/ExoPlayer/tree/release-v2/extensions/okhttp).

**Comment by github8866** [comment]
Thank you for fast reply, 
I will check links you provided and I will update here

Regards
