### ISSUE TITLE
HLS Streaming?

### ISSUE THREAD

**Issue by encodi** [google/ExoPlayer#237]
I have these ts chunks and a m3u8 file, for adaptive streaming.

Does ExoPlayer support this?, before i get into it to implement it in our app. Thanks

**Comment by mine260309** [comment]
If you use dev-hls branch, yes it supports. Though it's under development...

**Comment by ojw28** [comment]
The answer above is correct. It's fairly stable at this point; and will be pushed to master relatively soon now.
