### ISSUE TITLE
Wrapped License

### ISSUE THREAD

**Issue by erenbakac** [google/ExoPlayer#2370]
Hi,

The license   we need to play contents comes within JSON format to my app. So i need to customize DefaultDrmSessionManager to handle json format. Is there any alternative way of handling license in a json response. 

Shaka Player can cope with this situation .

https://github.com/google/shaka-player/blob/master/docs/tutorials/license-wrapping.md#wrapping-license-responses

**Comment by ojw28** [comment]
You should implement your own `MediaDrmCallback` instead, which is one of the arguments passed when creating your `DefaultDrmSessionManager` instance. There are multiple ways in which you can implement the details. One option would be to do something like:

```
public final class MyMediaDrmCallback {

  private final HttpMediaDrmCallback wrapped;

  ....

  @Override
  public byte[] executeKeyRequest(UUID uuid, KeyRequest request) throws Exception {
    byte[] response = wrapped.executeKeyRequest(uuid, request);
    // Unwrap the raw response, optionally parsing additional JSON you've added.
    return rawResponse;
  }

} 
```

**Comment by erenbakac** [comment]
Thank you..
