### ISSUE TITLE
Support seamless (non-immediate) switching between DASH adaptation sets

### ISSUE THREAD

**Issue by SteUK** [google/ExoPlayer#2371]
Question!

I am using v 2.x releasve-v2.

Is there a flag I am missing that might allow seamless/no-break playback when changing adaptation set (using the method... trackselector -> setSelectionOverride).  Granted it would continue to play out the what has already been buffered before switching to the new data stream...

If not, is it even feasible?  I have been looking in reselectTracksInternal() as a starting point to gather more information...

Thanks!

**Comment by ojw28** [comment]
This is not currently supported.

**Comment by ojw28** [comment]
Out of interest, what's the actual use case for this? If the user is manually changing what they're trying to view via some UI, then it's in my opinion quite confusing for the actual switch to be delayed. If you're performing some kind of automatic adaptation, is the content in the two adaptation sets the same or different, and why is the switch necessary?

**Comment by SteUK** [comment]
It is for a VR application where it is felt user immersion is being stopped by the pause in (mainly) audio and visual.  In our case, think of each adaptation set as a scene camera.

Current thinking is that a delayed switch with continuation would be acceptable to the user as long as they are informed about the delay.  I am keen to go poking around to see if I can make ExoPlayer achieve this...if you think it is even feasible with the current code.  Pointers as to where to start would be much appreciated.

We thought about having a very low bitrate black representation that would, in theory, start up a lot quicker and thus give quick continuation of the audio.  But we cannot find a way to 'reset' the bandwidth heuristic such that this lowest bitrate representation of the new adaptation set is buffered in first.

Any/all ideas welcome!

**Comment by Jogan** [comment]
@SteUK Did you ever achieve this? I am trying to implement dynamic rendition support so that given a list of tracks with various resolutions and bitrates; we can seamlessly switch to higher or lower quality tracks on the fly if the user's connection changes.

**Comment by ghost** [comment]
@Jogan can you upload your customize code?

**Comment by ojw28** [comment]
Let's use #2250 to track this.
