### ISSUE TITLE
Failed to handle key response: DRM vendor-defined error: -2952

### ISSUE THREAD

**Issue by erenbakac** [google/ExoPlayer#2373]
Hi,

I need some help. I am currently trying to  add  playing offline content   feature to my app. I get "**android.media.MediaDrm$MediaDrmStateException: Failed to handle key response: DRM vendor-defined error: -2952**" error while i am downloading the manifest 
 using the code below .  

HttpDataSource.Factory httpDataSourceFactory=buildHttpDataSourceFactory(mUserAgent,BANDWIDTH_METER);

HttpMediaDrmCallback drmCallback = new HttpMediaDrmCallback(mLicense,httpDataSourceFactory, mKeyRequestProperties);

MyMediaDrmCallback callback=new MyMediaDrmCallback(drmCallback);//ı use this for wrapped license
FrameworkMediaDrm     mediaDrm= FrameworkMediaDrm.newInstance(C.WIDEVINE_UUID);
 offlineLicenseHelper = new OfflineLicenseHelper(mediaDrm, callback, mKeyRequestProperties);

 keySetId=  offlineLicenseHelper.download(httpDataSourceFactory.createDataSource(),dashManifest);// it returns related error.

I can get license from server  and parse it  successfully using MyMediaDrmCallback .

 Thank you.

**Comment by ojw28** [comment]
Please provide the information requested in the issue template if you want us to look at this. We cannot investigate problems of this kind without complete information, including a full bug report (instructions on how to obtain one are in the issue template you clicked through when filing this issue).

**Comment by barbarosalp** [comment]
What is the error code -2952 for?

**Comment by erenbakac** [comment]
I uploaded bugreport. 
  
[bugreport_offline.txt](https://github.com/google/ExoPlayer/files/729773/bugreport_offline.txt)

**Comment by wvpaf** [comment]
@erenbakac, the error indicates the license request is too large for this device. 
Can you try a license request with fewer optional parameters in getKeyRequest for this device? 
Starting in Android N this should not be an issue.

**Comment by erenbakac** [comment]
@wvpaf Sorry for late reply. I sorted it out by passing null value to create OfflineLicenseHelper instance. Thank you..
