### ISSUE TITLE
Audio playing with interference (mp3, hls)

### ISSUE THREAD

**Issue by permenko** [google/ExoPlayer#2375]
- A description of the issue:

Audio playing with interference

- Steps describing how the issue can be reproduced, ideally in the ExoPlayer
  demo app.

put http://78.140.209.5:1935/muzis/_definst_/mp3:evx/hov/y0k/evxhovy0ki5w.mp3/playlist.m3u8 to HLS samples. play any from hls

- A link to content that reproduces the issue:

http://78.140.209.5:1935/muzis/_definst_/mp3:evx/hov/y0k/evxhovy0ki5w.mp3/playlist.m3u8

- The version of ExoPlayer being used.

1.5.13 (but with 2.1.1 same issue)

- The device(s) and version(s) of Android on which the issue can be reproduced,
  and how easily it reproduces. If possible, please test on multiple devices and
  Android versions.

emulator:
Name: Nexus_5X_API_23
CPU/ABI: Google APIs Intel Atom (x86_64)
Target: google_apis [Google APIs] (API level 23)
image.sysdir.1: system-images/android-23/google_apis/x86_64/
hw.device.hash2: MD5:1be89bc42ec9644d4b77968b23474980
hw.gpu.enabled: yes

device:
Xiaomi mi4c
Android 7.1.1 (Resurrection Remix Nougat 7.1.1_r6 - NMF26Q)

device:
ASUS Z00D
Android 5.0.1

- A bug report taken from the device just after the issue occurs, attached as a
  file. A bug report can be captured using "adb bugreport". Output from "adb
  logcat" or a log snippet is not sufficient.

[bugreport.txt](https://github.com/google/ExoPlayer/files/729893/bugreport.txt) (from emulator)

[demo_v1.5.13.mp4.zip](https://github.com/google/ExoPlayer/files/729938/demo_v1.5.13.mp4.zip) (it's loud, be careful)

**Comment by ojw28** [comment]
The stream plays back with exactly the same interference in VLC as well, so I think this is likely to be an issue with the content.

**Comment by permenko** [comment]
@ojw28 working well at https://developer.jwplayer.com/tools/stream-tester/ (Render Mode: Flash)
same stream working well on ios too

**Comment by ojw28** [comment]
A 50% success rate doesn't exactly confirm the media is correct. Two players that do not share common code, failing in the same way, where they do not fail for other streams of the same type, still implies the media is more likely or not at fault.

The stream is now broken (times out), so we're unable to test further. If it can be made to work reliably then we may do a small amount of additional investigation.
