### ISSUE TITLE
Switch video as HLS switch track quality

### ISSUE THREAD

**Issue by doubleti** [google/ExoPlayer#2377]
Hello!
I want to add several video streams together and render only one of them at a given time. It's mean i have two quality of video with mp4 format, i want switch them as HLS switch quality.
Please help me how to do it ?
Thanks you!

**Comment by AquilesCanta** [comment]
My suggestion is to try DASH, SS or HLS. If your files are entire presentations (i.e. not chunked), this is not supported. You would have to create your own media source, choose the URL based on available bandwidth, solve ranged requests and splicing, etc. Basically, you need to reinvent adaptive streaming. If you choose to go down this path, have a look at the existing adaptive media sources.
