### ISSUE TITLE
How to display closed caption text on video?

### ISSUE THREAD

**Issue by shailesh2208** [google/ExoPlayer#2382]
Hi,
I am using Exoplayer to play video that format is either m3u8 or mp4. These video Url is embedded with closed caption text. I want to display closed caption on during video playing.

How can we display closed caption text that is embedded with video url?

**Comment by AquilesCanta** [comment]
Play the URL stream in the demo app. Check whether the text track is being exposed. If so, you can select it from the drop-down list. Have a look at the demo app's code for a precise guide on how to achieve this in your own app.

If the text track is not exposed, then check with other players whether the media is correct. If other players do correctly play the stream, please file a new issue including all the information requested in the issue template for us to look at.
