### ISSUE TITLE
Video not resizing in ViewDragHelper when using SurfaceView

### ISSUE THREAD

**Issue by Yonezpt** [google/ExoPlayer#2385]
I have been playing with the VDH from this tutorial, the last example where it imitates YouTube's mini player feature: http://flavienlaurent.com/blog/2013/08/28/each-navigation-drawer-hides-a-viewdraghelper/

And trying to implement the Exoplayer r2.1.1 by studying the available demo and the guide here: https://google.github.io/ExoPlayer/guide.html

Everything works perfectly, except when the video is dragged downwards. It won't resize to the size it should have, it doesn't resize at all, it stays cropped in the corner. If I use the TextureView instead of SurfaceView it resizes perfectly, but due to the power demand of TextureView and other downsides I would really prefer to use SurfaceView, but so far I have not been able to get it to resize correctly at all.

I have already looked through plenty of issues, googled a lot and even tried to implement the suggestion from here, but the problem remains: https://github.com/google/ExoPlayer/issues/452#issuecomment-132772365

So I have reached a point where I can't solve this on my own and would like to know if there is any solution to this problem.

**Comment by Yonezpt** [comment]
And I just found out that if I set a TextureView to the player, the controls become invisible. They are still there and they work if I click on their positions, but the entire control structure is completely invisible. They show up correctly if I don't set anything via setVideoTextureView.

**Comment by Yonezpt** [comment]
So this is becoming even bigger of a nightmare. If I set the textureview before setting the player, the player resize is gone, but the controls are visible

````java
        player.setVideoTextureView((TextureView) surfaceView);
        simpleExoPlayerView.setPlayer(player);
````

but if I do the same after setting the player then the player resizes correctly, but all the controls become invisible


````java
        simpleExoPlayerView.setPlayer(player);
        player.setVideoTextureView((TextureView) surfaceView);
````

I have no idea what is going on or how to fix this, there is nothing in the internet or in the issue tracker related to something like this.

EDIT: I finally figured out that the TextureView has to be set in the XML layout via `app:surface_type="texture_view"` Now the controls finally show up AND the player can be resized.

I will still be waiting for some sort of solution for the SurfaceView to stop ignoring scaling because TextureView has some drawbacks.

**Comment by Yonezpt** [comment]
No one can help?

**Comment by ojw28** [comment]
What API level is the device you're testing on? I *think* `SurfaceView` should work correctly during the drag on Nougat, so one option you have is to use `SurfaceView` on Nougat+ and `TextureView` on earlier API versions. This will at least mean you transition over slowly as more devices get Nougat.

If I remember correctly, there's a workaround you can use on earlier API levels where you obtain the `SurfaceView` from the `SimpleExoPlayerView` like:
```
SurfaceView surfaceView = (SurfaceView) simpleExoPlayerView.getVideoSurfaceView();
```
Then during the drag, you can repeatedly call:
```
surfaceView.getHolder().setFixedSize(w, h);
```
to force the surface to resize itself properly. Maybe give that a try and see if the approach looks promising? You'll have to figure out exactly where to get `w` and `h` from.

**Comment by ojw28** [comment]
It might be enough to use `surfaceView.getWidth()` and `surfaceView.getHeight()` for the width and height. Worth a try anyway.

**Comment by Yonezpt** [comment]
Ah, I see, so the scaling problem should be an API limitation. Haven't got Nougat yet, running the one just before that (MarshMallow, if I recall correctly). I had already tried the `setFixedSize` suggestion during drag, but the performance degrades a lot, making the dragging experience worse when compared to using TextureView instead.

I guess I'll take up on your other suggestion and target the SurfaceView for the higher API  if the scaling problem is not present, for now I will try to do some black magic and see if I can switch the SurfaceView to TextureView when the view is being dragged and switch back again once the dragging stopped, all while the video is still playing. It probably won't work, but it is worth trying, unless you already know the outcome from experience, in which case I would appreciate if you could share that with us.

**Comment by ojw28** [comment]
I think it's very unlikely you'll manage to swap the view type just for the drag in a way that's anywhere close to being seamless (i.e. I wouldn't spend too much time, if any, trying). You're best bet is probably TextureView before N and SurfaceView after N, if the `setFixedSize` hack doesn't work well enough.

**Comment by Yonezpt** [comment]
Alright, guess the safest bet, for now, is to target the surface/texture to the API like you said. Thanks a lot for helping out with this!
