### ISSUE TITLE
Player freezes when playing dash SD + 2K + 4K

### ISSUE THREAD

**Issue by Duna** [google/ExoPlayer#2388]
When playing youtube dash that has SH and UDH the player starts with 640 SH video segments, after a while it switches to 2K and the video freezes at the first frame but the sound continue playing. Trying with extensions VP9 or without and the same result occurred.
Same thing happen when force only to 2K and 4K, when switches to 4K the video freezes and audio continue playing

**Comment by ojw28** [comment]
Closing because the report does not include any of the information requested in the issue template. Please provide complete information as requested in the template if you want us to take a look.

**Comment by Duna** [comment]
D/EventLogger: bandwidth [166.92, 2133554, 1.88, 9083784]
01-30 14:19:30.494 3167-3300/system_process W/System.err: java.io.FileNotFoundException: /sys/devices/system/cpu/cpu1/cpufreq/scaling_cur_freq: open failed: ENOENT (No such file or directory)
01-30 14:19:30.494 3167-3300/system_process W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:456)
01-30 14:19:30.494 3167-3300/system_process W/System.err:     at java.io.FileInputStream.<init>(FileInputStream.java:76)
01-30 14:19:30.494 3167-3300/system_process W/System.err:     at java.io.FileInputStream.<init>(FileInputStream.java:103)
01-30 14:19:30.494 3167-3300/system_process W/System.err:     at java.io.FileReader.<init>(FileReader.java:66)
01-30 14:19:30.494 3167-3300/system_process W/System.err:     at com.android.server.misc.HWMonitorServiceWorker.getCPUFreq(HWMonitorServiceWorker.java:60)
01-30 14:19:30.494 3167-3300/system_process W/System.err:     at com.android.server.misc.HwMonitorService$UpdateTimeTask.run(HwMonitorService.java:113)
01-30 14:19:30.495 3167-3300/system_process W/System.err:     at java.util.Timer$TimerImpl.run(Timer.java:284)
01-30 14:19:30.495 3167-3300/system_process W/System.err: Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
01-30 14:19:30.495 3167-3300/system_process W/System.err:     at libcore.io.Posix.open(Native Method)
01-30 14:19:30.495 3167-3300/system_process W/System.err:     at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
01-30 14:19:30.495 3167-3300/system_process W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:442)
01-30 14:19:30.495 3167-3300/system_process W/System.err: 	... 6 more

**Comment by Duna** [comment]
- youtube link is (dash extracted from info file): https://www.youtube.com/watch?v=vlDzYIIOYmM
- Demo project used ExoPlayer version: latest release of v2 and v1, tried with and without extensions, .so compiled 
- Android 6.0, ARM v7a

**Comment by Duna** [comment]
[ 9549.022434@1] codec:H.264 4k2k decoder mem resource 0x28000000 -- 0x2bd00000
<6>[ 9549.030554@1] codec:                   sysinfo: 2560x1440, rate = 0, param = 0x31
<6>[ 9549.041515@1] codec:
<6>[ 9549.041515@1] vh264_4k2k_init
<6>[ 9549.041733@1] codec:H264_4K2K: decinfo: 2560x1440 rate=3600
<6>[ 9549.048531@1] codec:loading firmware vh264_4k2k_mc_single to vdec ram  ok!
<6>[ 9549.056166@2] codec:vdec_clock_set-----630
<6>[ 9549.058429@2] codec:gp_pll_user_cb_vdec call
<6>[ 9549.063593@1] codec:vdec_clock_set 2 to 648
<6>[ 9549.063595@2] codec:gp_pll_user_cb_vdec call set
<6>[ 9549.071227@1] codec:vdec1 video changed to 4096 x 2048 30 fps clk->648MHZ
<6>[ 9549.078735@1] codec:video first pts = 0
<6>[ 9549.204611@1] codec:Skip releasing CMA buffer 12
<6>[ 9549.204676@1] codec:4K2K dec stop, keeping buffer index = 12
<6>[ 9549.209820@1] codec:vdec_clock_set-----0
<6>[ 9549.213572@1] codec:vdec1_set_clk 2, 2
<6>[ 9549.217072@1] codec:vdec_clock_set 2 to 200
<6>[ 9549.221066@1] codec:vdec1 video changed to 0 x 0 0 fps clk->200MHZ
<6>[ 9549.227919@1] codec:amvdec_h264_4k2k_remove
<6>[ 9549.254885@2] codec:vdec_clock_set-----2
<6>[ 9549.254946@2] codec:vdec1_set_clk 0, 1
<6>[ 9549.256907@2] codec:vdec_clock_set 2 to 500
<6>[ 9549.261265@2] codec:Video stbuf alloced at 0000000023b00000, size = 15728640
<6>[ 9549.268102@2] codec:free_alloced_keep_buffer           (null).          (null).          (null)
<6>[ 9549.276912@2] codec:vdec_dev_reg.mem[0x0 -- 0x0]
<6>[ 9549.297181@2] codec:vdec base memory alloced 0000000027c00000
<6>[ 9549.298142@2] codec:amvdec_h264_4k2k probe start.
<6>[ 9549.301943@2] codec:H.264 4k2k decoder mem resource 0x28000000 -- 0x2bd00000
<6>[ 9549.309028@2] codec:                   sysinfo: 2560x1440, rate = 0, param = 0x31
<6>[ 9549.316355@2] codec:
<6>[ 9549.316355@2] vh264_4k2k_init
<6>[ 9549.321485@2] codec:H264_4K2K: decinfo: 2560x1440 rate=3600
<6>[ 9549.327210@2] codec:loading firmware vh264_4k2k_mc_single to vdec ram  ok!
<6>[ 9549.334204@2] codec:vdec_clock_set-----630
<6>[ 9549.337995@2] codec:gp_pll_user_cb_vdec call
<6>[ 9549.348344@2] codec:vdec_clock_set 2 to 648
<6>[ 9549.348346@1] codec:gp_pll_user_cb_vdec call set
<6>[ 9549.351467@2] codec:vdec1 video changed to 4096 x 2048 30 fps clk->648MHZ
<6>[ 9549.359582@2] codec:video first pts = 0
<6>[ 9549.494217@1] codec:Skip releasing CMA buffer 12
<6>[ 9549.494253@1] codec:4K2K dec stop, keeping buffer index = 12
<6>[ 9549.499114@1] codec:vdec_clock_set-----0
<6>[ 9549.502738@1] codec:vdec1_set_clk 2, 2
<6>[ 9549.506669@1] codec:vdec_clock_set 2 to 200
<6>[ 9549.511123@1] codec:vdec1 video changed to 0 x 0 0 fps clk->200MHZ
<6>[ 9549.516919@1] codec:amvdec_h264_4k2k_remove
<6>[ 9549.532313@1] codec:vdec_clock_set-----2
<6>[ 9549.532353@1] codec:vdec1_set_clk 0, 1
<6>[ 9549.534337@1] codec:vdec_clock_set 2 to 500
<6>[ 9549.538521@1] codec:Video stbuf alloced at 0000000023b00000, size = 15728640
<6>[ 9549.545857@1] codec:free_alloced_keep_buffer           (null).          (null).          (null)
<6>[ 9549.555117@1] codec:vdec_dev_reg.mem[0x0 -- 0x0]
<6>[ 9549.568773@1] codec:vdec base memory alloced 0000000027c00000
<6>[ 9549.569976@1] codec:amvdec_h264_4k2k probe start.
<6>[ 9549.573741@1] codec:H.264 4k2k decoder mem resource 0x28000000 -- 0x2bd00000
<6>[ 9549.581188@1] codec:                   sysinfo: 2560x1440, rate = 0, param = 0x31
<6>[ 9549.588014@1] codec:
<6>[ 9549.588014@1] vh264_4k2k_init
<6>[ 9549.593342@1] codec:H264_4K2K: decinfo: 2560x1440 rate=3600
<6>[ 9549.599079@1] codec:loading firmware vh264_4k2k_mc_single to vdec ram  ok!
<6>[ 9549.605683@1] codec:vdec_clock_set-----630
<6>[ 9549.609713@1] codec:gp_pll_user_cb_vdec call
<6>[ 9549.614996@0] codec:vdec_clock_set 2 to 648
<6>[ 9549.614998@1] codec:gp_pll_user_cb_vdec call set
<6>[ 9549.623015@1] codec:vdec1 video changed to 4096 x 2048 30 fps clk->648MHZ
<6>[ 9549.630564@1] codec:video first pts = 0
<6>[ 9549.764141@2] codec:Skip releasing CMA buffer 12
<6>[ 9549.764182@2] codec:4K2K dec stop, keeping buffer index = 12
<6>[ 9549.768738@2] codec:vdec_clock_set-----0
<6>[ 9549.773156@2] codec:vdec1_set_clk 2, 2
<6>[ 9549.776879@2] codec:vdec_clock_set 2 to 200
<6>[ 9549.780709@2] codec:vdec1 video changed to 0 x 0 0 fps clk->200MHZ
<6>[ 9549.786664@2] codec:amvdec_h264_4k2k_remove
<6>[ 9549.799580@2] codec:vdec_clock_set-----2
<6>[ 9549.799616@2] codec:vdec1_set_clk 0, 1
<6>[ 9549.801590@2] codec:vdec_clock_set 2 to 500
<6>[ 9549.806587@2] codec:Video stbuf alloced at 0000000023b00000, size = 15728640
<6>[ 9549.813184@2] codec:free_alloced_keep_buffer           (null).          (null).          (null)
<6>[ 9549.821722@2] codec:vdec_dev_reg.mem[0x0 -- 0x0]
<6>[ 9549.834919@2] codec:vdec base memory alloced 0000000027c00000
<6>[ 9549.836081@2] codec:amvdec_h264_4k2k probe start.
<6>[ 9549.839748@2] codec:H.264 4k2k decoder mem resource 0x28000000 -- 0x2bd00000
<6>[ 9549.847105@2] codec:                   sysinfo: 2560x1440, rate = 0, param = 0x31
<6>[ 9549.854169@2] codec:
<6>[ 9549.854169@2] vh264_4k2k_init
<6>[ 9549.859212@2] codec:H264_4K2K: decinfo: 2560x1440 rate=3600
<6>[ 9549.859510@2] codec:loading firmware vh264_4k2k_mc_single to vdec ram  ok!
<6>[ 9549.859711@2] codec:vdec_clock_set-----630
<6>[ 9549.864822@1] codec:gp_pll_user_cb_vdec call
<6>[ 9549.865854@2] codec:vdec_clock_set 2 to 648
<6>[ 9549.865855@1] codec:gp_pll_user_cb_vdec call set
<6>[ 9549.865857@2] codec:vdec1 video changed to 4096 x 2048 30 fps clk->648MHZ
<6>[ 9549.866925@2] codec:video first pts = 0
<6>[ 9550.004140@2] codec:Skip releasing CMA buffer 12
<6>[ 9550.004181@2] codec:4K2K dec stop, keeping buffer index = 12
<6>[ 9550.008914@2] codec:vdec_clock_set-----0
<6>[ 9550.012631@2] codec:vdec1_set_clk 2, 2
<6>[ 9550.016569@2] codec:vdec_clock_set 2 to 200
<6>[ 9550.020667@2] codec:vdec1 video changed to 0 x 0 0 fps clk->200MHZ
<6>[ 9550.026598@2] codec:amvdec_h264_4k2k_remove
<6>[ 9550.039473@2] codec:vdec_clock_set-----2
<6>[ 9550.039510@2] codec:vdec1_set_clk 0, 1
<6>[ 9550.041483@2] codec:vdec_clock_set 2 to 500
<6>[ 9550.045821@2] codec:Video stbuf alloced at 0000000023b00000, size = 15728640
<6>[ 9550.052617@2] codec:free_alloced_keep_buffer           (null).          (null).          (null)
<6>[ 9550.061254@2] codec:vdec_dev_reg.mem[0x0 -- 0x0]
<6>[ 9550.073955@2] codec:vdec base memory alloced 0000000027c00000
<6>[ 9550.075433@2] codec:amvdec_h264_4k2k probe start.
<6>[ 9550.078878@2] codec:H.264 4k2k decoder mem resource 0x28000000 -- 0x2bd00000
<6>[ 9550.085726@2] codec:                   sysinfo: 2560x1440, rate = 0, param = 0x31
<6>[ 9550.095596@2] codec:
<6>[ 9550.095596@2] vh264_4k2k_init
<6>[ 9550.098660@2] codec:H264_4K2K: decinfo: 2560x1440 rate=3600
<6>[ 9550.104429@2] codec:loading firmware vh264_4k2k_mc_single to vdec ram  ok!
<6>[ 9550.110719@2] codec:vdec_clock_set-----630
<6>[ 9550.114630@1] codec:gp_pll_user_cb_vdec call
<6>[ 9550.120059@2] codec:vdec_clock_set 2 to 648
<6>[ 9550.120060@1] codec:gp_pll_user_cb_vdec call set
<6>[ 9550.127634@2] codec:vdec1 video changed to 4096 x 2048 30 fps clk->648MHZ
<6>[ 9550.134739@2] codec:video first pts = 0
<6>[ 9550.176389@2] codec:video first checkin pts = 0
<6>[ 9550.176428@2] codec:first check in vpts <0x0:0x0> ok!
<6>[ 9550.180390@0] codec:crop_right = 0x0 crop_bottom = 0x0 chroma_format_idc = 0x0
<6>[ 9550.189309@0] codec:frame_mbs_only_flag 1, crop_bottom 0 frame_height 1440, mb_height 90 crop_right 0, frame_width 2560, mb_width 90
<6>[ 9550.200013@0] codec:dpb_start_addr=0x28ac8000, dpb_size=5652480, total_dec_frame_buffering=14, 
<6>[ 9550.208366@0] codec:mb_width=160, mb_height=92
<6>[ 9550.212731@0] codec:start alloc for 8/14
<6>[ 9550.216749@0] codec:Re-use CMA buffer 12
<6>[ 9550.220501@0] codec:H264 4k2k decoder canvas allocation successful, 
<6>[ 9550.227240@0] codec:6 CMA blocks allocated, canvas 128-155
<6>[ 9550.345369@0] codec:video first pts = 1
<6>[ 9550.345458@0] switch_vpu_mem_pd: di_pre ON
<6>[ 9550.347729@0] pre_de_buf_config: source change: 0x0/0/0/0=>0x9000/2560/1440/0
<6>[ 9550.364136@2] codec:H264 4k2k resolution changed!!
<6>[ 9550.364192@2] codec:vdec_clock_set-----630
<6>[ 9550.367369@2] codec:vdec1 video changed to 2560 x 1440 26 fps clk->648MHZ
<6>[ 9550.380596@0] codec:[video4osd] first  picture {2560,1440} pts:1,
<6>[ 9550.381088@0] switch_vpu_mem_pd: viu_vd1 ON
<6>[ 9550.385197@0] switch_vpu_mem_pd: afbc_dec ON
<6>[ 9550.389415@0] switch_vpu_mem_pd: di_post ON
<6>[ 9550.397268@0] codec:VsyncEnableVideoLayer
<6>[ 9556.583994@0] remote: press ircode = 0x1a,
<6>[ 9556.584034@0] remote: scancode = 0x006c,maptable = 0,code:0xe51afe01
<4>[ 9556.584640@0] 
<6>[ 9556.754207@0] remote: release ircode = 0x1a,
<6>[ 9556.754255@0] remote: scancode = 0x006c, maptable = 0,code:0x00000000
<4>[ 9556.755020@0] 
<6>[ 9557.856046@0] remote: press ircode = 0x1a,
<6>[ 9557.856137@0] remote: scancode = 0x006c,maptable = 0,code:0xe51afe01
<4>[ 9557.856707@0] 
<6>[ 9558.194160@0] remote: release ircode = 0x1a,
<6>[ 9558.194224@0] remote: scancode = 0x006c, maptable = 0,code:0x00000000
<4>[ 9558.194967@0] 
<6>[ 9558.502859@0] remote: press ircode = 0x1a,
<6>[ 9558.502941@0] remote: scancode = 0x006c,maptable = 0,code:0xe51afe01
<4>[ 9558.503517@0] 
<6>[ 9558.854201@1] remote: release ircode = 0x1a,
<6>[ 9558.854279@1] remote: scancode = 0x006c, maptable = 0,code:0x00000000
<4>[ 9558.855012@1] 
<6>[ 9584.504541@1] codec:video first pts = 0
<6>[ 9584.504605@0] switch_vpu_mem_pd: di_pre OFF
<6>[ 9584.624183@1] codec:4K2K dec stop, keeping buffer index = 2
<6>[ 9584.624296@1] codec:vdec_clock_set-----0
<6>[ 9584.628019@1] codec:vdec1_set_clk 2, 2
<6>[ 9584.631735@1] codec:vdec_clock_set 2 to 200
<6>[ 9584.635890@1] codec:vdec1 video changed to 0 x 0 0 fps clk->200MHZ
<6>[ 9584.642052@1] codec:amvdec_h264_4k2k_remove
<6>[ 9584.661031@0] codec:vdec_clock_set-----2
<6>[ 9584.661084@0] codec:vdec1_set_clk 0, 1
<6>[ 9584.663164@0] codec:vdec_clock_set 2 to 500
<6>[ 9584.667568@0] codec:Video stbuf alloced at 0000000023b00000, size = 15728640
<6>[ 9584.675312@0] codec:free_alloced_keep_buffer           (null).          (null).          (null)
<6>[ 9584.683188@0] codec:vdec_dev_reg.mem[0x0 -- 0x0]
<6>[ 9584.701222@1] codec:vdec base memory alloced 0000000027c00000
<6>[ 9584.702240@1] codec:amvdec_h264_4k2k probe start.
<6>[ 9584.706377@1] codec:H.264 4k2k decoder mem resource 0x28000000 -- 0x2bd00000
<6>[ 9584.706382@1] codec:                   sysinfo: 2560x1440, rate = 0, param = 0x31
<6>[ 9584.706383@1] codec:
<6>[ 9584.706383@1] vh264_4k2k_init
<6>[ 9584.706386@1] codec:H264_4K2K: decinfo: 2560x1440 rate=3600
<6>[ 9584.720682@1] codec:loading firmware vh264_4k2k_mc_single to vdec ram  ok!
<6>[ 9584.720874@1] codec:vdec_clock_set-----630
<6>[ 9584.720889@1] codec:gp_pll_user_cb_vdec call
<6>[ 9584.721917@1] codec:gp_pll_user_cb_vdec call set
<6>[ 9584.721923@1] codec:vdec_clock_set 2 to 648
<6>[ 9584.721926@1] codec:vdec1 video changed to 4096 x 2048 30 fps clk->648MHZ
<6>[ 9584.722587@1] codec:video first pts = 0
<6>[ 9584.854150@1] codec:vdec_clock_set-----0
<6>[ 9584.854187@1] codec:vdec1_set_clk 2, 2
<6>[ 9584.856208@1] codec:vdec_clock_set 2 to 200
<6>[ 9584.860291@1] codec:vdec1 video changed to 0 x 0 0 fps clk->200MHZ
<6>[ 9584.866445@1] codec:amvdec_h264_4k2k_remove
<6>[ 9584.879064@0] codec:DisableVideoLayer()
<6>[ 9584.879480@2] codec:video_freerun_mode_store(0)
<6>[ 9584.880579@0] codec:VsyncDisableVideoLayer
<3>[ 9584.894752@2] vfm_map_store:rm default
<3>[ 9584.895001@0] vfm_map_store:add default decoder ppmgr deinterlace amvideo
<6>[ 9586.530609@0] switch_vpu_mem_pd: viu_vd1 OFF
<6>[ 9586.530666@0] switch_vpu_mem_pd: afbc_dec OFF
<6>[ 9586.533566@0] switch_vpu_mem_pd: di_post OFF
<6>[ 9587.955010@1] aiu i2s playback disable
<6>[ 9587.955043@1] audio_hw_958_enable 0
<6>[ 9591.048684@2] [aml-i2s-dai]i2s dma ffffff8001ac4000,phy addr 916455424,mode 0,ch 2
<6>[ 9591.050614@2] ----aml_hw_iec958_init,runtime->rate=48000,sample_rate=4--
<6>[ 9591.058221@2] aml_set_spdif_clk rate
<6>[ 9591.060825@2] divider=20,frac=33920000,SDMval=5654
<6>[ 9591.065610@2] set normal 512 fs /4 fs
<6>[ 9591.069181@2] iec958 mode PCM16
<6>[ 9591.072697@2] IEC958 16bit
<4>[ 9591.074985@2] hdmitx: audio: aout notify rate 48000
<4>[ 9591.080010@2] hdmitx: audio: aout notify size 16
<4>[ 9591.084360@2] hdmitx: audio: no update
<6>[ 9591.088112@2] 958 with i2s
<6>[ 9591.091870@2] aiu i2s playback enable
<6>[ 9591.094342@2] audio_hw_958_enable 1
<4>[ 9591.694982@3] CPU3: Booted secondary processor
<6>[ 9601.384293@2] aiu i2s playback disable
<6>[ 9601.384331@2] audio_hw_958_enable 0
<6>[ 9606.394211@2] speaker_events--mute =0
<6>[ 9613.195976@2] [aml-i2s-dai]i2s dma ffffff8001ac4000,phy addr 916455424,mode 0,ch 2
<6>[ 9613.197928@2] ----aml_hw_iec958_init,runtime->rate=48000,sample_rate=4--
<6>[ 9613.204581@2] aml_set_spdif_clk rate
<6>[ 9613.208102@2] divider=20,frac=33920000,SDMval=5654
<6>[ 9613.212842@2] set normal 512 fs /4 fs
<6>[ 9613.221561@2] iec958 mode PCM16
<6>[ 9613.221619@2] IEC958 16bit
<4>[ 9613.222237@2] hdmitx: audio: aout notify rate 48000
<4>[ 9613.227120@2] hdmitx: audio: aout notify size 16
<4>[ 9613.231636@2] hdmitx: audio: no update
<6>[ 9613.235411@2] 958 with i2s
<6>[ 9613.238617@2] speaker_events--mute =1
<6>[ 9613.245310@2] aiu i2s playback enable
<6>[ 9613.245351@2] audio_hw_958_enable 1
<6>[ 9639.714899@2] aiu i2s playback disable
<6>[ 9639.714936@2] audio_hw_958_enable 0
<6>[ 9644.724245@2] speaker_events--mute =0
<6>[ 9649.151964@3] [aml-i2s-dai]i2s dma ffffff8001ac4000,phy addr 916455424,mode 0,ch 2
<6>[ 9649.153961@3] ----aml_hw_iec958_init,runtime->rate=48000,sample_rate=4--
<6>[ 9649.160643@3] aml_set_spdif_clk rate
<6>[ 9649.164809@3] divider=20,frac=33920000,SDMval=5654
<6>[ 9649.168839@3] set normal 512 fs /4 fs
<6>[ 9649.172472@3] iec958 mode PCM16
<6>[ 9649.175621@3] IEC958 16bit
<4>[ 9649.178254@3] hdmitx: audio: aout notify rate 48000
<4>[ 9649.183051@3] hdmitx: audio: aout notify size 16
<4>[ 9649.187654@3] hdmitx: audio: no update
<6>[ 9649.191331@3] 958 with i2s
<6>[ 9649.194190@3] speaker_events--mute =1
<6>[ 9649.204929@3] aiu i2s playback enable
<6>[ 9649.204968@3] audio_hw_958_enable 1
<6>[ 9657.305353@2] aiu i2s playback disable
<6>[ 9657.305412@2] audio_hw_958_enable 0
<6>[ 9662.314351@2] speaker_events--mute =0
<6>[ 9667.636699@2] [aml-i2s-dai]i2s dma ffffff8001ac4000,phy addr 916455424,mode 0,ch 2
<6>[ 9667.638686@2] ----aml_hw_iec958_init,runtime->rate=48000,sample_rate=4--
<6>[ 9667.645371@2] aml_set_spdif_clk rate
<6>[ 9667.648851@2] divider=20,frac=33920000,SDMval=5654
<6>[ 9667.653595@2] set normal 512 fs /4 fs
<6>[ 9667.657262@2] iec958 mode PCM16
<6>[ 9667.660310@2] IEC958 16bit
<4>[ 9667.663035@2] hdmitx: audio: aout notify rate 48000
<4>[ 9667.667946@2] hdmitx: audio: aout notify size 16
<4>[ 9667.672395@2] hdmitx: audio: no update
<6>[ 9667.676156@2] 958 with i2s
<6>[ 9667.679367@2] speaker_events--mute =1
<6>[ 9667.686770@2] aiu i2s playback enable
<6>[ 9667.686847@2] audio_hw_958_enable 1
<6>[ 9673.375043@3] aiu i2s playback disable
<6>[ 9673.375144@3] audio_hw_958_enable 0
<6>[ 9678.384559@3] speaker_events--mute =0
<4>[ 9681.745890@1] IRQ93 no longer affine to CPU1
<5>[ 9681.750057@0] CPU1: shutdown
<4>[ 9705.285433@2] IRQ94 no longer affine to CPU2
<5>[ 9705.287979@0] CPU2: shutdown
<6>[ 9718.459021@0] lowmemorykiller: Killing 'oid.tv.settings' (16861), adj 1000,
<6>[ 9718.459021@0]    to free 18476kB on behalf of 'kswapd0' (917) because
<6>[ 9718.459021@0]    cache 105260kB is below limit 106496kB for oom_score_adj 1000
<6>[ 9718.459021@0]    Free memory is 28064kB above reserved. nonmove free (33240kB),(53480kB)
<6>[ 9719.767885@0] lowmemorykiller: Killing 'roidlogic.PPPoE' (16539), adj 1000,
<6>[ 9719.767885@0]    to free 18036kB on behalf of 'kswapd0' (917) because
<6>[ 9719.767885@0]    cache 104600kB is below limit 106496kB for oom_score_adj 1000
<6>[ 9719.767885@0]    Free memory is 27648kB above reserved. nonmove free (33096kB),(52804kB)
<6>[ 9720.982182@0] lowmemorykiller: Killing 'droid.deskclock' (8611), adj 1000,
<6>[ 9720.982182@0]    to free 15252kB on behalf of 'kswapd0' (917) because
<6>[ 9720.982182@0]    cache 103268kB is below limit 106496kB for oom_score_adj 1000
<6>[ 9720.982182@0]    Free memory is 29376kB above reserved. nonmove free (32784kB),(53080kB)
<6>[ 9722.994781@3] lowmemorykiller: Killing 'd.process.media' (25925), adj 764,
<6>[ 9722.994781@3]    to free 22816kB on behalf of 'kswapd0' (917) because
<6>[ 9722.994781@3]    cache 100056kB is below limit 102400kB for oom_score_adj 529
<6>[ 9722.994781@3]    Free memory is 32260kB above reserved. nonmove free (34376kB),(51656kB)
<4>[ 9725.295495@3] IRQ95 no longer affine to CPU3
<5>[ 9725.299860@0] CPU3: shutdown
<6>[10057.230876@0] remote: press ircode = 0x19,
<6>[10057.230911@0] remote: scancode = 0x009e,maptable = 0,code:0xe619fe01
<4>[10057.231503@0] 
<6>[10057.404142@0] remote: release ircode = 0x19,
<6>[10057.404178@0] remote: scancode = 0x009e, maptable = 0,code:0x00000000
<4>[10057.404938@0] 
<6>[10059.421272@0] remote: press ircode = 0x1a,
<6>[10059.421393@0] remote: scancode = 0x006c,maptable = 0,code:0xe51afe01
<4>[10059.421942@0] 
<6>[10059.594136@0] remote: release ircode = 0x1a,
<6>[10059.594166@0] remote: scancode = 0x006c, maptable = 0,code:0x00000000
<4>[10059.594928@0] 
<6>[10059.622205@0] remote: press ircode = 0x1a,
<6>[10059.622239@0] remote: scancode = 0x006c,maptable = 0,code:0xe51afe01
<4>[10059.622829@0] 
<6>[10059.651567@0] [aml-i2s-dai]i2s dma ffffff8001ac4000,phy addr 916455424,mode 0,ch 2
<6>[10059.653489@0] ----aml_hw_iec958_init,runtime->rate=48000,sample_rate=4--
<6>[10059.662216@0] aml_set_spdif_clk rate
<6>[10059.663793@0] divider=20,frac=33920000,SDMval=5654
<6>[10059.668559@0] set normal 512 fs /4 fs
<6>[10059.672081@0] iec958 mode PCM16
<6>[10059.675151@0] IEC958 16bit
<4>[10059.677910@0] hdmitx: audio: aout notify rate 48000
<4>[10059.682678@0] hdmitx: audio: aout notify size 16
<4>[10059.687245@0] hdmitx: audio: no update
<6>[10059.690917@0] 958 with i2s
<6>[10059.694435@0] speaker_events--mute =1
<6>[10059.705076@0] aiu i2s playback enable
<6>[10059.705106@0] audio_hw_958_enable 1
<6>[10059.794122@0] remote: release ircode = 0x1a,
<6>[10059.794155@0] remote: scancode = 0x006c, maptable = 0,code:0x00000000
<4>[10059.794915@0] 
<6>[10060.392547@0] remote: press ircode = 0x16,
<6>[10060.392685@0] remote: scancode = 0x0067,maptable = 0,code:0xe916fe01
<4>[10060.393222@0] 
<6>[10060.564179@0] remote: release ircode = 0x16,
<6>[10060.564225@0] remote: scancode = 0x0067, maptable = 0,code:0x00000000
<4>[10060.564982@0] 
<6>[10063.545281@0] aiu i2s playback disable
<6>[10063.545483@0] audio_hw_958_enable 0
<6>[10063.621005@0] remote: press ircode = 0x13,
<6>[10063.621278@0] remote: scancode = 0x00e8,maptable = 0,code:0xec13fe01
<4>[10063.621768@0] 
<6>[10063.794221@0] remote: release ircode = 0x13,
<6>[10063.794273@0] remote: scancode = 0x00e8, maptable = 0,code:0x00000000
<4>[10063.795100@0] 
<6>[10063.825422@0] [aml-i2s-dai]i2s dma ffffff8001ac4000,phy addr 916455424,mode 0,ch 2
<6>[10063.827354@0] ----aml_hw_iec958_init,runtime->rate=48000,sample_rate=4--
<6>[10063.834061@0] aml_set_spdif_clk rate
<6>[10063.837668@0] divider=20,frac=33920000,SDMval=5654
<6>[10063.842284@0] set normal 512 fs /4 fs
<6>[10063.847353@0] iec958 mode PCM16
<6>[10063.849003@0] IEC958 16bit
<4>[10063.851678@0] hdmitx: audio: aout notify rate 48000
<4>[10063.856682@0] hdmitx: audio: aout notify size 16
<4>[10063.861074@0] hdmitx: audio: no update
<6>[10063.864839@0] 958 with i2s
<6>[10063.868221@0] aiu i2s playback enable
<6>[10063.871070@0] audio_hw_958_enable 1
<4>[10064.275202@1] CPU1: Booted secondary processor
<6>[10064.482083@0] codec:vdec_clock_set-----2
<6>[10064.482121@0] codec:vdec1_set_clk 0, 1
<6>[10064.484601@0] codec:vdec_clock_set 2 to 500
<6>[10064.490296@1] ionvideo open
<6>[10064.492127@1] ionvideo_stop_generating!!!!
<6>[10064.495229@1] ionvideo release
<3>[10064.525132@0] vfm_map_store:rm default
<3>[10064.528322@0] vfm_map_store:add default decoder ionvideo
<6>[10064.533050@1] codec:vdec_clock_set-----2
<6>[10064.533084@1] codec:vdec1_set_clk 0, 1
<6>[10064.540664@1] codec:vdec_clock_set 2 to 500
<6>[10064.540815@1] codec:Video stbuf alloced at 0000000023b00000, size = 15728640
<6>[10064.547589@1] codec:vdec_dev_reg.mem[0x0 -- 0x0]
<6>[10064.551973@1] codec:vdec base memory alloced 0000000024a00000
<6>[10064.561768@1] codec:amvdec_h264 mem-addr=24a00000,buff_offset=23a00000,buf_start=24b3e000
<6>[10064.565801@1] codec:H264 sysinfo: 640x360 duration=0, pts_outside=1, 
<6>[10064.573961@1] codec:sync_outside=0, use_idr_framerate=0
<6>[10064.578426@1] codec:264 ucode swap area: phyaddr 0000000036ba0000, cpu vaddr ffffff80003f1000
<6>[10064.594302@1] codec:start load orignal firmware ...
<6>[10064.594585@1] codec:loading firmware vh264_mc to vdec ram  ok!
<6>[10064.605558@1] reg:ionvideo
<6>[10064.608883@1] codec:video first pts = 0
<6>[10064.609321@1] ionvideo open
<6>[10064.615667@1] codec:video first checkin pts = 0
<6>[10064.615703@1] codec:first check in vpts <0x0:0x0> ok!
<4>[10064.641010@0] avc open
<4>[10064.643657@0] allocating phys 0x27c00000, size 18432k, wq:ffffffc01e330000.
<4>[10064.645287@0] amvenc_avc  memory config sucess, buff start:0x27c00000, size is 0x1200000, wq:ffffffc01e330000.
<4>[10064.656675@0] avc release, wq:ffffffc01e330000
<4>[10064.659310@0] remove  encode_work_queue ffffffc01e330000 sucess, _destroy_encode_work_queue line 3521.
<6>[10064.693375@0] codec:frame_mbs_only_flag 1, crop_bottom 4,  frame_height 360, 
<6>[10064.694695@0] codec:mb_height 23,crop_right 0, frame_width 640, mb_width 40
<6>[10064.701762@0] codec:max_dpb 9 size:3686400
<6>[10064.705967@0] codec:video first pts = 1
<6>[10064.714125@1] codec:vdec_clock_set-----100
<6>[10064.714168@1] codec:vdec1_set_clk 2, 4
<6>[10064.717393@1] codec:vdec_clock_set 2 to 100
<6>[10064.721529@1] codec:vdec1 video changed to 640 x 360 29 fps clk->100MHZ
<6>[10064.867300@0] codec:finished correct frame dur
<6>[10064.867331@0] codec: new=3202,old_duration=3203,cnt=25
<6>[10074.543614@0] codec:Over decoder supported size, width = 3840
<6>[10074.544120@1] codec:vdec_clock_set-----166
<6>[10074.547798@1] codec:vdec1_set_clk 0, 3
<6>[10074.551491@1] codec:vdec_clock_set 2 to 166
<6>[10074.555660@1] codec:vdec1 video changed to 3840 x 360 29 fps clk->166MHZ
<4>[10084.996870@1] dumpstate (26464): /proc/26464/oom_adj is deprecated, please use /proc/26464/oom_score_adj instead.
<4>[10095.609394@1] Bits 55-60 of /proc/PID/pagemap entries are about to stop being page-shift some time soon. See the linux/Documentation/vm/pagemap.txt for details.


------ LIST OF OPEN FILES (/system/xbin/su root lsof) ------
*** /system/xbin/su: Exit code 1
[/system/xbin/su: 0.202s elapsed]

**Comment by ojw28** [comment]
Tracked in #2390
