### ISSUE TITLE
DASH player failed to switch video quality from SD<->2K<->4k

### ISSUE THREAD

**Issue by Duna** [google/ExoPlayer#2390]
The Demo application with my DASH 4K link start to play initially in SD mode and then tries to switch in 2k mode. When switching to 2K the aduio continue to play but the video freezes at the last frame of SD. The video freezes till the end. I used the app without extensions, with extensions I didn't get freeze but very low frame rate.

- DASH extracted from info file of: https://www.youtube.com/watch?v=vlDzYIIOYmM
- ExoPlayer release-v2
- Devices with ARM v7a  Android 6.x
Bugreport: https://drive.google.com/file/d/0B_ElWh6cyPN0SnlybndOTlJSYkU/view?usp=sharing

**Comment by Duna** [comment]
D/EventLogger: bandwidth [166.92, 2133554, 1.88, 9083784]
01-30 14:19:30.494 3167-3300/system_process W/System.err: java.io.FileNotFoundException: /sys/devices/system/cpu/cpu1/cpufreq/scaling_cur_freq: open failed: ENOENT (No such file or directory)
01-30 14:19:30.494 3167-3300/system_process W/System.err: at libcore.io.IoBridge.open(IoBridge.java:456)
01-30 14:19:30.494 3167-3300/system_process W/System.err: at java.io.FileInputStream.(FileInputStream.java:76)
01-30 14:19:30.494 3167-3300/system_process W/System.err: at java.io.FileInputStream.(FileInputStream.java:103)
01-30 14:19:30.494 3167-3300/system_process W/System.err: at java.io.FileReader.(FileReader.java:66)
01-30 14:19:30.494 3167-3300/system_process W/System.err: at com.android.server.misc.HWMonitorServiceWorker.getCPUFreq(HWMonitorServiceWorker.java:60)
01-30 14:19:30.494 3167-3300/system_process W/System.err: at com.android.server.misc.HwMonitorService$UpdateTimeTask.run(HwMonitorService.java:113)
01-30 14:19:30.495 3167-3300/system_process W/System.err: at java.util.Timer$TimerImpl.run(Timer.java:284)
01-30 14:19:30.495 3167-3300/system_process W/System.err: Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
01-30 14:19:30.495 3167-3300/system_process W/System.err: at libcore.io.Posix.open(Native Method)
01-30 14:19:30.495 3167-3300/system_process W/System.err: at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
01-30 14:19:30.495 3167-3300/system_process W/System.err: at libcore.io.IoBridge.open(IoBridge.java:442)
01-30 14:19:30.495 3167-3300/system_process W/System.err: ... 6 more

**Comment by Duna** [comment]
On Pixel C is working well, is it x264/AVC linux codec issue, or ARM v7 processor issue?

**Comment by ojw28** [comment]
- I don't think it's realistic to expect the software VP9 extension to be able to decode 2K or 4K in real time (depending on bit-rate), so I think a low frame-rate would be expected.
- When not using the extension I suspect it's a device specific issue, particularly since you say Pixel C is working well. You should report it to whoever provides the Android build on the device (typically the device manufacturer). You may also just be hitting limitations of the device. The bit-rates you're using (up to 23Mbit/s) are extremely high. HEVC and VP9 are more appropriate codecs for 2K/4K, if the boxes support them.

**Comment by Duna** [comment]
If we select from the beginning only 4K or 2K sources than the player works flawlessly.
The issue comes in the way the codec is reinitialized in case of video source quality switching.

**Comment by ojw28** [comment]
It's most likely a device specific issue, as per my comment above. Please report it to whoever provides the Android build on the device.

**Comment by Duna** [comment]
Thanks for the clarification
