### ISSUE TITLE
Two exoplayer simultaneously play issue

### ISSUE THREAD

**Issue by usmanahmed951** [google/ExoPlayer#2391]
I wanted to play one video in two simpleexoplayersviews in the same activity at the same time using two different exo players and the media source is created using ConcatenatingMediaSource because I wanted to concatenate two or more videos. When i play the video its runs ok on the first time on both players. but when i again play the same concatenatemediasource one player video stop or does not play and other one does. and if I hit the play button again then the other player video stops and the other one works fine. And when i concate the three videos it got even worse. On the first run the player cause problems. Both players are in UIThread. And i also try this in different threads like one is in main UIthread and other one is other thread but i face the same issue every time. and exoplayerview are created on xml.

**Comment by andrewlewis** [comment]
There are a few existing issues about playing multiple videos at once (e.g. #1286). Please search existing issues before filing a new one.
