### ISSUE TITLE
exoplayer DASH segment change event too soon.

### ISSUE THREAD

**Issue by michaelstrigy** [google/ExoPlayer#2392]
Hi,

I have a unity 3d VR app that is using exoplayer 2-1-1 project with a small modification to show VR videos on a surface of unity tat exoplayer writes to.

exoplayer gets DASH manifest and changes between formats of it.

my problem is that when exoplayer changes the video source (video format), unity needs to know at exactly that time, but when trying to overload "VideoRendererEventListener"s "onVideoInputFormatChanged" to send the event, it reaches unity before the next video format is shown on device, about 300-500 ms before.

is there another event i can use to send unity the correct time the video is actually displayed on surface?

so far no tries are good and I don't know where to look further.

Thanks a lot!

**Comment by ojw28** [comment]
Could you explain why unity needs this (i.e. what it does with the event)? Thanks!

**Comment by michaelstrigy** [comment]
@ojw28 the video shown is needed to be displayed on a different shape and rotation, so unity should change them exactly when the video is changed.
if the change of video shown on surface and shape are not at the exact same time you will see a glitch in the video..

**Comment by michaelstrigy** [comment]
some new things: I saw that the video is only shown on screen when a new segment starts, that is if video is of 2 seconds segments the change is shown only in a time where a new 2 seconds segment starts.
when trying to tell unity this time, the action in unity is really close but not always perfect (causing common video glitches when sync is not at the same frame between video shown and unity action).

how can i get to the real accurate timing?

thanks a lot.

**Comment by ojw28** [comment]
How does each video frame actually get from ExoPlayer to Unity? Presumably you've provided a `Surface` of some kind to `ExoPlayer`, which was provided by Unity, and `ExoPlayer` is calling `releaseOutputBuffer` to release each video frame to the `Surface`. Is that correct? I wouldn't be surprised if there's some async step somewhere buried in the `Surface` implementation though, because the actual drawing in Unity is likely to be on a different rendering thread owned by Unity? In which case aren't glitches always going to be a possibility, unless you go quite a bit deeper in terms of how you implement the integration?

Ignoring the above, `onVideoInputFormatChanged` is definitely too soon, since it's triggered when the format going *into* the decoder changes, where-as you want an event when the format coming *out* of the decoder changes. What properties actually differ in the different representations that you're adapting between? If video width/height changes then you should get a `VideoRendererEventListener.onVideoSizeChanged`, which will be fired at a more appropriate time.

**Comment by michaelstrigy** [comment]
Hi, thanks for your reply!

as you said, the surface is sent to exoplayer from unity.
using onVideoSizeChanged isn't possible since the video streams used are the same size.
Is there any way to see when a frame is of different stream in the output buffer? maybe a correlation between input/output buffers timings? that way it will be possible to have more accurate timing.

Any ideas maybe?

Thanks, Michael.

**Comment by ojw28** [comment]
Is `MediaCodecVideoRenderer.onOutputFormatChanged` invoked at all on the format change, or is the format identical as far as the output side of the decoder is concerned, in which case it wont be invoked?

If it's not invoked then I think we'd need to record the presentation timestamp of the first input buffer to be queued after each change of input format. Probably as some kind of map from timestamp to format. Then we could look at the presentation timestamp of each output buffer being released. When an entry is found in the map, we could fire an event passing the mapped format, and remove the entry. Maybe you could have a try at implementing this approach to see if it works? If it does then we can consider merging a change. Note that a good solution should avoid excessive long to Long boxing/unboxing.

**Comment by michaelstrigy** [comment]
yep, that is the exact scenario, onOutputFormatChanged isn't invoked because the decoded frame are not different by any property.

I will try implementing this and update on the result, thanks!

**Comment by michaelstrigy** [comment]
Hi, just update were we are at.
I did an attempt to implement your suggested logic, in a similar way to your suggestion.
The result was it worked and we got a onOutputFormatChanged for output rendered frames.
Problem was it still did not give us the right accuracy for the presentation on screen, even when calculating with the difference between current position and onOutputFormatChanged presentation times.
That sent me to try different things closer to releaseOutputBuffer which may hold calls for unknown times after version 21 and therefore we try to approach it with pre 21 implementation and hopefully it will work.

if I will finally solve this soon I will of course update here,

Thanks you,
Michael.

**Comment by shalin186** [comment]
Hi Michael,

Did you have any further success on this? I was also trying similar things where I need to know the exact time when the first frame from different format is being displayed and I need to apply rotation starting from that frame. If there's even one frame mismatch I see a small glitch. Please let me know if you have any helpful information here.

Shalin

**Comment by andrewlewis** [comment]
Assuming you're rendering video output to a `SurfaceTexture`, I think the right way to do this is to store the presentation timestamps at which format changes occur, then map the release time of each frame (`SurfaceTexture.getTimestamp()`), onto a presentation time (more info in #3471) and then use this presentation time to look up whether the format has changed. This should allow you to get perfect synchronization.
