### ISSUE TITLE
Controls events and timeout

### ISSUE THREAD

**Issue by b77x** [google/ExoPlayer#2395]
Issue 1:
Just run the demo application, and hold the finger on the pause button and wait for it to hide. Now release. The event will be fired and the video will pause, even though the button was not visible.

My solution and issue 2.
I tried to fix on my custom view by trying to extend the timeout time to a long time and set it back to 5 second when tapup, so it would not hide while the user has not released, however changing the timeout using `setControllerShowTimeoutMs` will not propagate immediately, but only after the controls state has been changed, so the new timeout will only be used next time.

**Comment by ojw28** [comment]
Seems like a very minor issue. @marcbaechinger - We should probably prevent the controls from hiding whilst the user is interacting with them, and time the hiding of the controls from the point at which the touch ends.

**Comment by royhenengel** [comment]
As mentioned here, in my case I would like to set the timeout to be visible until the display is pressed again to hide them.
setControllerShowTimeoutMs doesn't set the timeout at all, and the value remains default.
