### ISSUE TITLE
Change style display of closed caption during runtime

### ISSUE THREAD

**Issue by shailesh2208** [google/ExoPlayer#2397]
I need requirement to change the following property of closed caption during runtime:-
            FontColor
            FontSizeScale
            FontBackgroundColor
            FontBackgroundOpacity
            FontOpacity
            FontEdgeType
            Typeface
How can we change above property during runtime and can it possible to meet my all above requirement?

**Comment by ojw28** [comment]
If you're using `SimpleExoPlayerView` you can get the `SubtitleView` by calling `simpleExoPlayerView.getSubtitleView()`. Once you have that view, there are a bunch of methods you can call on it to change the font and style. See the [documentation here](https://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/ui/SubtitleView.html), in particular methods like `setStyle`.
