### ISSUE TITLE
Play subclip of video from url in android exoplayer

### ISSUE THREAD

**Issue by aka-awasthi** [google/ExoPlayer#2398]
Hi, i want to play  subclip of particular video by providing starttime and endtime (I am Using MPEG DASH streaming)  ,how can i achieve this functionality in exoplayer ,android.Is there any api provided by exoplayer library (Any example or piece of code).I stuck at this problem for 2 days ,I didnt find any resources of references related to this problem.

**Comment by ojw28** [comment]
See https://github.com/google/ExoPlayer/issues/1988.
