### ISSUE TITLE
How I zoom in or moving scenes?

### ISSUE THREAD

**Issue by ihrthk** [google/ExoPlayer#240]

**Comment by ojw28** [comment]
ExoPlayer can draw video into any Surface. The surface is set by the application via MSG_SET_SURFACE to the MediaCodecVideoTrackRenderer. Beyond that, anything regarding translation of the Surface is up to the application developer, and is outside of the scope of ExoPlayer.

Depending on how much control you need, SurfaceView might be good enough, or you might want to look at TextureView and SurfaceTexture.
