### ISSUE TITLE
Neither surfaceView nor Texture View works 100 percent with exoplayer

### ISSUE THREAD

**Issue by gabbimark** [google/ExoPlayer#2406]
Hi i have done a lot of research on this by going through the forums and trying different approaches in my code.
- If i use surfaceview, then videos are rotated 90 or 270 degrees on preLollipop devices  See: https://github.com/google/ExoPlayer/issues/91
- If i use textureview i am experiencing where video playback as not as smooth as texture view and choppy on many older devices. Also there is no center crop available in texture view so on most phone video is either stretched veritically or horizantally. 
- I am using exoplayer r1.5.13
-Currently i have switched from surfaceView to textureView because of rotation issue on pre Lollipop devices but now i am experiencing stretching and choppiness. 

We have spent several weeks looking for a solution:
- Is there a complete solution for either texture view or surfaceView that include no chopiness, rotation issues or stretching issues.  Someone please put me on the right track.

**Comment by ojw28** [comment]
Using TextureView is fundamentally less efficient than using SurfaceView, so if you're pushing against the limitations of the device you should expect a slightly choppier experience. The rotation issue using SurfaceView is already tracked in the issue you reference.
