### ISSUE TITLE
Font color of subtitle is not changing using CaptionStyleCompat

### ISSUE THREAD

**Issue by shailesh2208** [google/ExoPlayer#2407]
My requirement is to change the font color of Closed caption sub title text. For fulfill requirement I am using
```
captionStyleCompat = new CaptionStyleCompat(Color.BLACK, Color.BLUE, Color.TRANSPARENT, CaptionStyleCompat.EDGE_TYPE_DROP_SHADOW, Color.GREEN, null);

simpleExoPlayerView.getSubtitleView().setStyle(captionStyleCompat);
```
As per above method my subtitle font color should be black. but still it is default color that is white where as background color has been changed from black to blue.
Why font color is not changed to black from its default color? I am also changing different color of first and second parameter. All the time background has been changed but foreground has not been changed.

As per documentation there is no any method found to change the font color of subtitle text.

**Comment by ojw28** [comment]
It depends a bit on the source media. If the media doesn't say anything about the caption style, then what you've done should work fine. If the media explicitly indicates a caption style, then anything it indicates takes priority by default. Given what you're seeing, I suspect the media has an explicit embedded caption style that specifies white text.

You can disable application of embedded caption styles and have ExoPlayer use only the style you provide by calling `simpleExoPlayerView.getSubtitleView().setApplyEmbeddedStyles(false)`. Please give that a try and let us know if it works. Thanks!

**Comment by shailesh2208** [comment]
Hi ojw28,
Using `simpleExoPlayerView.getSubtitleView().setApplyEmbeddedStyles(false)` It is working now. Thank u so much for suggestion.
