### ISSUE TITLE
Last subtitle sample being dropped by MP4 extractor

### ISSUE THREAD

**Issue by brabeler** [google/ExoPlayer#2408]
This issue is present in ExoPlayer 1.5.13.  I imagine it would apply to v2 as well.

I have a couple MP4 videos using TX3G subtitles where the last subtitle ended well before the video ended.  For example, the video has a duration of 100 seconds but the last subtitle should only display starting from position 70 seconds and ending at position 80 seconds.  I noticed a problem in that I was never getting the onCues() callback to clear the last subtitle at position 80 seconds, so the last subtitle ended up being incorrectly displayed all the way until the end of the video.

I did some investigation and debugging and found the following.  All the samples for the TX3G track are being properly read in parseStbl() in AtomParsers.java.  However, before the TrackSampleTable is created, there is code to edit and/or trim down the samples based on an edit list:

    // Count the number of samples after applying edits.
    int editedSampleCount = 0;
    int nextSampleIndex = 0;
    boolean copyMetadata = false;
    for (int i = 0; i < track.editListDurations.length; i++) {
      long mediaTime = track.editListMediaTimes[i];
      if (mediaTime != -1) {
        long duration = Util.scaleLargeTimestamp(track.editListDurations[i], track.timescale,
            track.movieTimescale);
        int startIndex = Util.binarySearchCeil(timestamps, mediaTime, true, true);
        int endIndex = Util.binarySearchCeil(timestamps, mediaTime + duration, true, false);
        editedSampleCount += endIndex - startIndex;
        copyMetadata |= nextSampleIndex != startIndex;
        nextSampleIndex = endIndex;
      }
    }
    copyMetadata |= editedSampleCount != sampleCount;

In my case, the mediaTime is 0 and the duration is 80000 ms, which is the timestamp corresponding to the last sample in the TX3G track.  Thus, endIndex ends up being the index of the last sample which is supposed to clear the last subtitle (it has a size of 2 and the data is 0x00 0x00).  However, this causes editedSampleCount to be one less than sampleCount and thus the last sample gets dropped by the time the TrackSampleTable is created.

To fix this, I think endIndex should be calculated this way instead, with 'inclusive' being set to false:

int endIndex = Util.binarySearchCeil(timestamps, mediaTime + duration, false, false);

Also the same change probably needs to be applied a few lines down when endIndex is calculated again.

I don't know how this change would impact video or audio tracks, but for me, this change prevented the last sample in the TX3G track from being dropped from the TrackSampleTable and I got the resulting onCues() callback at position 80 seconds to clear the last subtitle.

Can you please look at this and advise if this change would be correct?

**Comment by andrewlewis** [comment]
Thanks for the thorough issue description.

Reading the specification, I think that last sample should be 'sliced' to duration zero. Unfortunately our handling of edit lists is incomplete (see the comment in parseStbl) and it looks like making your suggested change would mean that we could include a whole audio sample that should be completely removed. Why does this track have an edit list at all? It sounds like it isn't needed, and if it were removed you wouldn't encounter this edge case.

**Comment by brabeler** [comment]
I used ffmpeg to add a subtitle track to an existing MP4 file.  So I don't know why the edit list is there, but it seems that ffmpeg always creates an edit list for each track.

In my video there is an edit list for every track.  The edit list for the audio and video tracks indicate a duration equal to the length of the video.  But the edit list for the TX3G track indicates a duration equal to the length of that track itself, which is when the last subtitle ends.

If the last subtitle ends near the end of the video, then the problem is not very noticeable because the last subtitle is shown for only a few extra seconds.  But the problem really shows itself when the last subtitle is shown for quite a bit longer than it should.

**Comment by andrewlewis** [comment]
Does it work if you just pass `-use_editlist false` to FFmpeg, or are you relying on edit lists for something else?

**Comment by brabeler** [comment]
Yes it works, that option removes the edit list from the MP4 and now the last TX3G sample is no longer dropped.

Since ffmpeg is a popular tool to create MP4 files, I need a way to fix this problem without telling users to re-generate their MP4 file with that command-line option.  I can provide a fix in my code for my project, but I much prefer it fixed in ExoPlayer source so I don't have to propagate the fix for every code upgrade.  If you're not inclined to fix this, then do you have any insight into why ffmpeg creates an edit list by default when its not needed?  Thanks.

**Comment by andrewlewis** [comment]
I'll submit a fix that includes the sample for edits in non-audio tracks. This issue will be updated once it's merged. Thanks.
