### ISSUE TITLE
SeekTo Position of cutted song not working

### ISSUE THREAD

**Issue by Fed93** [google/ExoPlayer#2411]
Hi, 
I just made the transition from the Android Media Player to ExoPlayer and I noticed a bug in SeekTo Method.

If i try to seek to a position using seekbar while reproducing a cutted song (i removed the end of the song for example), ExoPlayer re-start reproducing from the Default Position (from the beginning) instead of the position i choosed.
While if i try to seek to a position of a song not cutted it work correctly.

I've tried with some other MusicPlayer but not happen even with Android media player in my old implementation did not happen, also i tried to put on my phone the same song but NOT cutted and the seekto method work correctly!

I'm using ExoPlayer r2.2.0 on Samsung Galaxy S6 (Reproduced also on other device).

When this happen there aren't exception or other error it simply re-start reproducing the song.

**Comment by andrewlewis** [comment]
Please provide the information requested in the issue template. We need a link to the problematic media to reproduce and investigate the issue.

**Comment by Fed93** [comment]
I've uploaded to google drive last media added to my library.
I've cutted this song and i can't seek to position
https://drive.google.com/open?id=0B4IKkuWtSFhkTzI3OUdCSEtzRUE

**Comment by andrewlewis** [comment]
How are you cutting the stream? The linked file has a Xing header but it doesn't have a table of contents so we treat the file as being unseekable.

**Comment by Fed93** [comment]
I'm using Mp3DirectCut for Windows
I cut the part and save changes with "Save audio file" button

**Comment by andrewlewis** [comment]
The tool you're using does not seem to be configured to rewrite a valid Xing table of contents. There may be an option to do this, or you may need to use a different program. You could try FFmpeg which rewrote the Xing header correctly when i tried it ([see instructions here](http://stackoverflow.com/questions/43890/crop-mp3-to-first-30-seconds)).

**Comment by Fed93** [comment]
Thanks!

**Comment by Fed93** [comment]
Hi, only a question, also FLAC file (not cutted) is unseekable?
