### ISSUE TITLE
[Question] Proper progressbar implementation for one way live streams (non-seekable)

### ISSUE THREAD

**Issue by Yonezpt** [google/ExoPlayer#2412]

**Comment by ojw28** [comment]
[This blog post](https://medium.com/google-exoplayer/customizing-exoplayers-ui-components-728cf55ee07a) describes various ways in which you can customize ExoPlayer's UI components. The easiest way to do what you want is to copy `exo_playback_control_view.xml` in the res/layout directory of your application and then customize it to meet your needs (e.g. by deleting the SeekBar element, or replacing it with something else - make sure what you replace it with doesn't use the same id if you do this).

You can also just implement your own UI from scratch. There is nothing forcing you to use `SimpleExoPlayerView` or `PlaybackControlView`. These are just standard UI components provided for convenience.
