### ISSUE TITLE
QA: How to access system DRM plugin when using software decoder extension

### ISSUE THREAD

**Issue by wendong-li** [google/ExoPlayer#2414]
This is a question not a bug report.

If we are using audio software decoder extension like opus and flac in the existing code, can we still use MediaCrypto to access the system DRM plugin, like Widevine?

If it's possible, are we supposed to use the ICrypto interface on the native side of the software decoder in the way how the native MediaCodec is implemented?

If this is not recommended, could you please let us know how we are supposed to handle this use case?

Thanks,

**Comment by ojw28** [comment]
I don't think it's possible to use MediaCrypto/MediaDrm in conjunction with software decoder extensions (i.e. decoders that aren't in the platform). @wvpaf can confirm.

**Comment by wendong-li** [comment]
@ojw28 
Thanks for the comment. Yes, using ICrypto doesn't seem to be an official solution since it's not part of the NDK APIs. But, the existing opus decoder seems to be using the Widevine DRM somehow, I was making a guess from the parameter name `wvCrypto`.
```
  private native int opusSecureDecode(long decoder, long timeUs, ByteBuffer inputBuffer,
      int inputSize, SimpleOutputBuffer outputBuffer, int sampleRate,
      ExoMediaCrypto wvCrypto, int inputMode, byte[] key, byte[] iv,
      int numSubSamples, int[] numBytesOfClearData, int[] numBytesOfEncryptedData);
```

The NDK does provide the AMediaDrm API for native apps, but it's not clear whether it's possible to associate it with the DRM session opened by the Java MediaDrm.

**Comment by ojw28** [comment]
That parameter name isn't accurate, so don't read anything into it. If you look at what happens on the JNI side of the opus extension, you'll see that `opusSecureDecode` is hardcoded to fail (see [here](https://github.com/google/ExoPlayer/blob/r2.2.0/extensions/opus/src/main/jni/opus_jni.cc#L128)).

It is theoretically possible to:
- Implement your own native library that implements DRM and an opus decoder.
- Build `ExoMediaCrypto` and `ExoMediaDrm` implementations on top of this native library.
- Specify that this native library should be used by the opus extension, by calling [`OpusLibrary.setLibraries`](https://github.com/google/ExoPlayer/blob/r2.2.0/extensions/opus/src/main/java/com/google/android/exoplayer2/ext/opus/OpusLibrary.java#L34).
If you were to do all this you could have a software based DRM solution that works with the opus extension, and the reason `OpusLibrary.setLibraries` and `opusSecureDecode` exist is to make this possible.

The above is not something I'd recommend attempting unless you're a DRM expert. It's quite involved on several fronts.

**Comment by wendong-li** [comment]
Thanks for the clarification.
