### ISSUE TITLE
PlayReady HLS using Viaccess-Orca (Discretix)

### ISSUE THREAD

**Issue by AhmedZahraz** [google/ExoPlayer#2418]
Hi,

I was just wondering if ExoPlayer supports PlayReady HLS using Viaccess-Orca (Discretix)?

See USP site for more info:
http://docs.unified-streaming.com/documentation/drm/hls.html#viaccess-orca-discretix-playready

Thanks

**Comment by AquilesCanta** [comment]
Currently, the only encryption method supported is AES-128. I doubt we will be adding any non-spec defined methods in the near future. Am I correct to say this encryption method escapes the spec?

**Comment by ojw28** [comment]
You can see what formats (and content protection) we support [here](https://google.github.io/ExoPlayer/supported-formats.html).
