### ISSUE TITLE
[Question] What are the difference among loadingPeriodHolder, readingPeriodHolder & playingPeriodHolder?

### ISSUE THREAD

**Issue by WeiChungChang** [google/ExoPlayer#2419]
Is there any document to explain them in detail?

I am curious about the timing to update them as well as the design concept about them.

Why we need such three MediaPeriodHolders? what's the difference between loadingPeriodHolder & readingPeriodHolder? 

Is the fast way to know the flow by running a movie containing multiple periods (such as MPEG DASH)? Or it is designed for sources such as ConcatenatingMediaSource?

Thanks in advance here.

**Comment by AquilesCanta** [comment]
Please have a look at [our medium blog](https://medium.com/google-exoplayer/exoplayer-2-x-mediasource-composition-6c285fcbca1f)(have a look around, you'll find some useful information) and this [Timeline documentation](http://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/Timeline.html).

The three media period holders are:
**playing**: Holds a reference to the period which is actually playing. The period that the renderers are displaying.
**reading:** Holds a reference to the period for which samples are being fed to the renderer. For instance, if the audio renderer has a 3 seconds buffer, the reading position is 3 seconds ahead of the playing position.
**loading**: Holds a reference to the period for which samples are being loaded. That is, the period for which media is being downloaded (if remote, of course) and the samples extracted.

Note that `loadingPeriodHolder.mediaPeriod == readingPeriodHolder.mediaPeriod == loadingPeriodHolder.mediaPeriod` may be true and will be true in most simple usecases. I hope the above made something a bit clearer. I'd suggest you to try your luck in a stack exchange site.
