### ISSUE TITLE
Guidelines to use custom encrypted data source ?

### ISSUE THREAD

**Issue by bbincybbaby** [google/ExoPlayer#2420]
Guidelines to use custom encrypted data source ?

http://stackoverflow.com/q/42038671/4639479

**Comment by ojw28** [comment]
In the snippet of code in the StackOverflow post, you instantiate a `DefaultDataSourceFactory` that gets passed in to the `ExtractorMediaSource`. If you want to use a custom `DataSource`, you need to instead instantiate a `DataSource.Factory` that creates instances of the custom `DataSource` that you want.
