### ISSUE TITLE
Question about multi-audio HLS audio variant data request

### ISSUE THREAD

**Issue by moacir69** [google/ExoPlayer#2426]
With ExoPlayer 2.0.4, the array of HlsSampleStreamWrapper created in HlsMediaPeriod.buildAndPrepareSampleStreamWrappers() includes all the media variants, leading to a data request in DataChunk.load() for all media playlists, even if only one of them is in use during playback.
Can you please provide information about why this behaviour has changed since ExoPlayer 1.5.8? In this case, a  media playlist data request is only performed when the associated audio track is selected during playback.
This can be reproduced with any multi-audio HLS content in any device.
Thank you,

Moacir

**Comment by AquilesCanta** [comment]
There are a few reasons:

* There used to be only 3 sample stream wrappers. Each of them(if present) would download one chunk to prepare, and assume the others tracks had the same shape. Sometimes this is ok, if the only changing aspect is the language, for audio and text. This leads me to:
* The codecs attribute is optional, and other information is not available in EXT-X-STREAM-INF or EXT-X-MEDIA. Particularly in older spec versions, like number of audio channels. This affects the decision of whether the format is supported by the device. After preparation, figuring these things out is too late.
* Lastly, maybe less important, this change allowed us removing non-adaptive track groups and selecting two audio tracks at the same time.

I hope this answers your question.

**Comment by moacir69** [comment]
Thank you for the quick reply!

Moacir

**Comment by AquilesCanta** [comment]
We might do something about this in the not-so-remote future.

**Comment by moacir69** [comment]
OK, thanks.

Moacir
