### ISSUE TITLE
Flac extension cause crash of released app

### ISSUE THREAD

**Issue by Fed93** [google/ExoPlayer#2427]
I've compiled and added the flac extension successful.
I've added the extension as a module in my app!

If i install app on my phone in debug it works great but if i compile to release it to the playstore, app crash when i try to reproduce flac song.

I use proguard provided with extension and proguard for main app (attached)
I'm using latest version of the extension adding -DHAVE_SYS_PARAM_H to LOCAL_CFLAGS in order to compile with latest ndk and ExoPlayer r2.2.0 on Samsung Galaxy S6.

Link to Flac Media: https://drive.google.com/open?id=0B4IKkuWtSFhkX2lyazEzcENCdzQ
[Logs & ProGuard.zip](https://github.com/google/ExoPlayer/files/757699/Logs.ProGuard.zip)

**Comment by erdemguven** [comment]
@Fed93 please add this to the flac extension proguard file (extensions/flac/src/main/proguard-rules.txt):
```
-keep class com.google.android.exoplayer2.util.FlacStreamInfo {
    *;
}
```
and try again.

**Comment by Fed93** [comment]
Yes, works great adding it to Proguard! 
Thank you very much! 

Only a question it's normal that FLAC song it's not seekable?

**Comment by erdemguven** [comment]
Good, soon a fix for it will be committed.

Unfortunately we don't support seeking if the flac file doesn't contain an seek table. See #1808

**Comment by Fed93** [comment]
Thank you very much!

**Comment by ojw28** [comment]
Reopening until fix is merged.
