### ISSUE TITLE
play h264 live stream

### ISSUE THREAD

**Issue by ihrthk** [google/ExoPlayer#243]
public DashChunkSource(DataSource dataSource, FormatEvaluator formatEvaluator,
                           Representation... representations) {
        this(buildManifest(Arrays.asList(representations)), 0, null, dataSource, formatEvaluator);
    }

private static MediaPresentationDescription buildManifest(List<Representation> representations) {
        Representation firstRepresentation = representations.get(0);
        AdaptationSet adaptationSet = new AdaptationSet(0, AdaptationSet.TYPE_UNKNOWN, representations);
        Period period = new Period(null, firstRepresentation.periodStartMs,
                firstRepresentation.periodDurationMs, Collections.singletonList(adaptationSet));
        long duration = firstRepresentation.periodDurationMs - firstRepresentation.periodStartMs;
        return new MediaPresentationDescription(-1, duration, -1, false, -1, -1, null,
                Collections.singletonList(period));
    }

According above all two  cdoe snippet.if i don't have representations,i have to a IndexOutOfBoundsException.What should i do?

Actually,i want to play h264 live stream,i only a video stream url,don't have Representation or Mainfest.Here you can provide a demo?

**Comment by ojw28** [comment]
If you don't have a manifest or a representation, then you're not trying to play DASH content, and hence DashChunkSource isn't the right thing to be using. I'm unclear what you're actually trying to play. The H264 is presumably in a container format of some kind.

**Comment by qqli007** [comment]
I want to play H264 live stream too, but it's not a normal format(maybe header is different,i am not sure about this).I think this means that I can't use MediaExtractor. So which samplesource should I use? Do I need to custom samplesource and trackrenderer?

and, I can extract one frame(it's an image)  buffer,but I dont know how to render it?

Also, I want know is it support mjpeg stream? 
refer to this link:     http://stackoverflow.com/questions/3205191/android-and-mjpeg


Thanks

**Comment by qqli007** [comment]
@ojw28 ,can you give me some help? Thanks

**Comment by ojw28** [comment]
We have no plans to support MJPEG. It's unclear what the "live streams" in this issue refer to, so I'm going to close it. If you can provide specific details of exactly what formats you're trying to play, ideally with a link to a test stream, then please feel free to open a new issue containing this information.
