### ISSUE TITLE
DASH: Support cross-AdaptationSet seamless switching

### ISSUE THREAD

**Issue by kqyang** [google/ExoPlayer#2431]
http://dashif.org/wp-content/uploads/2016/12/DASH-IF-IOP-v4.0-clean.pdf

```
3.8. Switching across Adaptation Sets
 ...
 A content author may signal such seamless switching property across Adaptation Sets by providing
 a Supplemental Descriptor along with an Adaptation Set with @schemeIdUri set to
 urn:mpeg:dash:adaptation-set-switching:2016 and the @value is a comma-
 separated list of Adaptation Set IDs that may be seamlessly switched to from this Adaptation Set.
 ...
 As an example, a content author may signal that seamless switching across an H.264/AVC Adap-
 tation Set with AdaptationSet@id=”h264” and an HEVC Adaptation Set with Adapta-
 tionSet@id=”h265” is possible by adding a Supplemental Descriptor to the H.264/AVC Ad-
 aptation Set with @schemeIdUri set to urn:mpeg:dash:adaptation-set-switch-
 ing:2016 and the @value=”h265” and by adding a Supplemental Descriptor to the HEVC
 Adaptation Set with @schemeIdUri set to urn:mpeg:dash:adaptation-set-switching:2016
 and the @value=”h264”
```

This technology is expected to be available in ISO/IEC 23009-1:2014/Amd.4:2016, section 5.3.3.5. 

Here is a sample content you can use for testing:
```
 "uri": "https://storage.googleapis.com/wvtemp/kylealexander/packager_test/iop_compliant_mpd_test/llama.mpd",
 "drm_scheme": "widevine",
 "drm_license_url": "https://proxy.uat.widevine.com/proxy?provider=widevine_test"
```

**Comment by ojw28** [comment]
Sanity check: Am I right in thinking the DASH IOP example is actually in violation of the DASH spec, because it uses string AdaptationSet@id values where-as the DASH spec says the type should be xs:unsignedInt? The example should use integers, I think?

**Comment by kqyang** [comment]
Good catch. I filed a bug to DASH-IF-IOP: https://github.com/Dash-Industry-Forum/DASH-IF-IOP/issues/136.

Not sure why DASH uses xs:unsignedInt for AdaptationSet but uses StringNoWhitespaceType for Representation. 

Anyway, the sample content referenced in the issue description should be compliant to both DASH spec and DASH-IF-IOP.

**Comment by ojw28** [comment]
Heh, I filed one through the form on the DASH-IF website. I had no idea it got mirrored to GitHub. I'll file any future issues on that tracker directly! Thanks for confirming.

**Comment by ojw28** [comment]
This is now supported in `dev-v2`.
