### ISSUE TITLE
MPEG DASH and MPEG-LA licensing 

### ISSUE THREAD

**Issue by nahojkap** [google/ExoPlayer#2434]
Hi,

Not an issue per se but are there any plans on allowing to build MPEG-DASH support as an extension rather than always including it by default? 

As we understand it, with the MPEG-LA licensing restrictions coming into (more) force, simply including ExoPlayer in an application would incur possible royalty obligations, even if you do not use DASH.

Thanks,

Johan

**Comment by AquilesCanta** [comment]
Please see #2139.
