### ISSUE TITLE
Seeking to end position when paused causes transition to next period

### ISSUE THREAD

**Issue by PaulWoitaschek** [google/ExoPlayer#2439]
ExoPlayer 2.2.0
Nexus 5x
Android 7.1.1

I use a `ConcatenatingMediaSource`. When I call `seekTo` with the current `windowIndex` and the duration of the file as `positionMs` in state `STATE_PAUSED` and `playWhenReady=false` I receive two events: `onPositionDisconunity`with that frame and `onPositionDisconity`with 0 but with the `windowIndex` increased.

This is problematic as when a user seeks with the seekbar he does not want to go to the next track when the player is paused.

**Comment by ojw28** [comment]
Fixed in dev-v2.
