### ISSUE TITLE
HLS AAC output:application/id3，application/cea-608

### ISSUE THREAD

**Issue by vince090416** [google/ExoPlayer#2440]
codecName:null hasDecoder:false
 mimeType:application/id3 supportsFormat:0
 ######UNSUPPORTED_TYPE#######
 codecName:null hasDecoder:false
 mimeType:application/cea-608 supportsFormat:0
 ######UNSUPPORTED_TYPE#######
 Tracks [
   Renderer:0 [
     Group:0, adaptive_supported=N/A [
       [X] Track:0, id=0, mimeType=video/avc, supported=YES
     ]
   ]
   Renderer:1 [
     Group:0, adaptive_supported=N/A [
       [X] Track:0, id=null, mimeType=audio/mp4a-latm, channels=6, sample_rate=48000, supported=YES
     ]
   ]
   Renderer:3 [
     Group:0, adaptive_supported=N/A [
       [ ] Track:0, id=null, mimeType=application/cea-608, supported=YES
     ]
   ]
   Renderer:4 [
     Group:0, adaptive_supported=N/A [
       [X] Track:0, id=null, mimeType=application/id3, supported=YES
     ]
   ]
 ]

**Comment by AquilesCanta** [comment]
I don't understand the question. Could you please clarify exactly what you are trying to do?

HLS is an adaptive streaming protocol, not a compression format (like H264, for example). In other words, HLS is not something you decode. In exoplayer, FFmpeg can be used as an extension to decode, for example, a video stream in a certain compression format. This is particularly useful when the device does not include hardware support for decoding such format. Can you please provide more context?

**Comment by ojw28** [comment]
Closing due to lack of clarity. There doesn't appear to be a description of a problem or a question in this issue.
