### ISSUE TITLE
Smooth Streaming {start_time} placeholder not supported

### ISSUE THREAD

**Issue by alfonsoramosa** [google/ExoPlayer#2447]
Exoplayer 2.2.0
Device: Nexus player
Android 7.1.1

Exoplayer is not working with some Smooth Streaming manifests.

That's happening when the `Url `for a `StreamIndex` has a placeholder for the start time with the format: `"start_time"` instead of `"start time"`  (with an underscore between start and time).

**Example:**

`<StreamIndex Type="audio" QualityLevels="3" TimeScale="10000000" Language="eng" Name="audio_eng" Chunks="1378" Url="QualityLevels({bitrate})/Fragments(audio_eng={start_time})">`

**SsManifest.java**

Placeholder defined as:
`private static final String URL_PLACEHOLDER_START_TIME = "{start time}";
`
The method `buildRequestUri()` is only replacing `"start time"`, but not `"start_time"`
Then, the placeholder remains in the Url, causing an error response.

**Comment by ojw28** [comment]
We should also match both {bitrate} and {Bitrate} according to the spec, rather than just {bitrate} as we do currently. We'll push a fix shortly.
