### ISSUE TITLE
Grab a frame of the video

### ISSUE THREAD

**Issue by thomas-le-bihan** [google/ExoPlayer#2451]
I want to grab a frame of the played video. I tried to work with `TextureView `(that have a `getBitmap()` method) making :

`player.setVideoTextureView(textureView);`

or 

```
<com.google.android.exoplayer2.ui.SimpleExoPlayerView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:surface_type="surface_view"
        app:resize_mode="fill"/>
```

But video is not anymore crop but fit `VideoView` and video is deformed.

How can I properly work with `TextureView` ?

**Comment by ojw28** [comment]
The question seems quite confused (what does VideoView have to do with anything; isn't it unrelated to ExoPlayer?), so I'm not sure what you're asking. If you're trying to use TextureView shouldn't you have: `app:surface_type="texture_view"`? You can then get the TextureView from the SimpleExoPlayerView and retrieve the Bitmap using:
```
TextureView textureView = (TextureView) simpleExoPlayerView.getVideoSurfaceView();
Bitmap bitmap = textureView.getBitmap();
```
