### ISSUE TITLE
add audiofocus to SimpleExoPlayer - Play button listener?

### ISSUE THREAD

**Issue by u2gilles** [google/ExoPlayer#2454]
I am using SimpleExoPlayer and I am trying to add audiofocus. Requesting the audiofocus at launch is easy. But I have problem requesting it when the user presses the play button,  which is encapsulated by the PlaybackControlView I recall.

Is other words, how can I capture the play button click event when using SimpleExoPlayer and SimpleExoPlayerView (PlaybackControlView)? There is no listener for that apparently.

Redifining simpleExoPlayer.setPlayWhenReady() to request audiofocus there does not seem possible because the instance of SimpleExoPlayer is given by a Factory, not from instantation with new keyword.

**Comment by ojw28** [comment]
You can do this by adding a listener to the ExoPlayer instance (`ExoPlayer.addListener`) and implementing the listener's `onPlayerStateChanged` to obtain or release audio focus as necessary. Note that `onPlayerStateChanged` will be called whenever `playWhenReady` is changed.

**Comment by u2gilles** [comment]
Thanks for your prompt answer but the problem with this solution, that I already tested with the debugger without fully implementing it, is that the onPlayerStateChanged() is called after the audio/video starts playing not before. I guess I can always stop playing if the audiofocus is denied but I wonder if SimpleExoPlayer/SimpleExoPlayerView provides a more elegant solution. How to capture the PLAY/PAUSE BUTTON event before the audio start playing? Or do you only recommend this solution, that is, stop playing in onPlayerStateChanged() if the audiofocus is denied .

**Comment by ojw28** [comment]
Ah, I see the issue. We should take a look at supporting this case. Thanks!

**Comment by u2gilles** [comment]
Thanks. In the meanwhile I already implemented your first solution. The very short overlapping when both audios play at the same time is not noticeable from the ear of course.
But still, android doc recommends about Audio Focus at [https://developer.android.com/guide/topics/media-apps/audio-app/mediasession-callbacks.html](url) : 

> Always call requestFocus() first, proceed only if focus is granted

**Comment by ojw28** [comment]
You can intercept play/pause calls after the patch ref'd above.
