### ISSUE TITLE
Check video object when playing

### ISSUE THREAD

**Issue by ghost** [google/ExoPlayer#2456]
I have questions about _ConcatenatingMediaSource_. I want to play multiple videos and every time when one video ends, to check one method. But in the case _ConcatenatingMediaSource_, he gives me to know about the latest after the end of the video, that is, at the end of the list of videos.

```
MediaSource  mediaSource;

for(int i = 0; i < videoList.size; i++){
    mediaSource = new ExtractorMediaSource(Uri.parse(Application.video_path + video.getName()), dataSourceFactory, extractorsFactory, null, null);
}

ConcatenatingMediaSource concatenatedSource = new ConcatenatingMediaSource(
            mediaSources.toArray(new MediaSource[mediaSources.size()]));

player.prepare(concatenatedSource);
player.setPlayWhenReady(true);
```
Q: How do I get **STATE_ENDED** after every video or how to understand in ConcatenatingMediaSource, which ended with some video to check like this?

```
if (firstVideo = STATE_ENDED){
    textView.setText(video.getName);
//////

```

And is it possible to send in the arguments ExtractorMediaSource class instead of uri of the file?

**Comment by andrewlewis** [comment]
Please see #2053.
