### ISSUE TITLE
FrameworkSampleSource with FileDescriptor

### ISSUE THREAD

**Issue by Nezz** [google/ExoPlayer#246]
Currently FrameworkSampleSource is designed to work with URIs. This makes it rather inconvenient to play media from other sources, like the APK (Assets for example). It would be a [one line change](https://github.com/google/ExoPlayer/blob/master/library/src/main/java/com/google/android/exoplayer/FrameworkSampleSource.java#L68) to make it work with with a FileDescriptor, since MediaExtractor has a [setDataSource overload](http://developer.android.com/reference/android/media/MediaExtractor.html#setDataSource%28java.io.FileDescriptor,%20long,%20long%29) for that.

My questions are:
Is there a way to play files from the Assets folder?
Are there any plans to add support for it?
Would it make sense to add a new SampleSource that is the same as FrameworkSampleSource just with that single line changed?

**Comment by spark85** [comment]
I changed the implementation with a custom SampleSource to use a FileDescriptor.  I obtained the FileDescriptor by creating an InputStream wrapped around a File object with the correct file name.  That fixed the issue with the MediaExtractor; and when I examined the MediaFormat it had all of the correct attributes.  (* I will post them by tomorrow morning). 

However, that still didn't solve the problem.  The player crashes when it tries to play the file, with a Signal 6 error; and FILE_DATA_SOURCE_END. 

I could use the asset folder; however, for security reasons we prefer to keep the media in internal storage.

**Comment by ojw28** [comment]
We can add an additional FrameworkSampleSource constructor that takes a FileDescriptor, if that helps. I'd like to understand the "still doesn't solve the problem" part though.

**Comment by Nezz** [comment]
Me too. I would have done it already, but I was too lazy to set up the environment to build it :)

**Comment by Nezz** [comment]
Works flawlessly for me.

**Comment by ojw28** [comment]
Closing this as the change is merged. It's likely the "still doesn't solve the problem" issue is something else. Feel free to open a separate issue to track that, if needed.
