### ISSUE TITLE
How to hide all control components?

### ISSUE THREAD

**Issue by ghost** [google/ExoPlayer#2460]
How to hide all controllers  (start button, pause, and so on) that they did not exist, and the screen will always full.

I looked, there is simpleExoPlayerView.setUseController(true) method;

But it deactivate the player ...

```
public void setUseController (boolean useController) {
    this.useController = useController;
if (useController) {
      controller.setPlayer(player);
    } else {
      controller.hide();
      controller.setPlayer(null);
    }
}
```
How to hide or delete these components?

**Comment by directable** [comment]
Have you tried just doing
simpleExoPlayerView.setUseController(false);
simpleExoPlayerView.hideController();

simpleExoPlayerView.setPlayer(playeryoucreated);

**Comment by ghost** [comment]
this method is not - hideController()
But it works for me. Thank you!
```
simpleExoPlayerView.setUseController(false);
simpleExoPlayerView.setPlayer(playeryoucreated);
```
