### ISSUE TITLE
Supported audio codecs -- Especially ATMOS

### ISSUE THREAD

**Issue by jmgirven** [google/ExoPlayer#2465]
Does ExoPlayer support whatever audio codecs the device does? Or does it have a list of supported codecs? Presumably the same applies for video?

I was asked if our app (using ExoPlayer) supports videos with "Dolby TrueHD 7.1 ATMOS" audio tracks, e.g: http://thedigitaltheater.com/index.php/dolby-trailers/. Unfortunately I don't have a device that supports ATMOS, so can't really test it for myself.

**Comment by jmgirven** [comment]
I see ExoPlayer mentions the mime type "audio/true-hd", but I actually don't if that is the same as ATMOS.

https://github.com/google/ExoPlayer/blob/25a966dc2300161448fa74dee5ee98322ff65604/library/src/main/java/com/google/android/exoplayer2/util/MimeTypes.java#L54

**Comment by andrewlewis** [comment]
On the rendering side, `MediaCodecAudioRenderer` and `MediaCodecVideoRenderer` support whatever codecs the device has, but on the extraction side we have to add support for each format individually (which can be non-trivial). See also [Supported formats](https://google.github.io/ExoPlayer/supported-formats.html) for more information.

Note that for surround playback it is common to output encoded audio directly to an audio receiver (passthrough). The Android platform supports passthrough of arbitrary formats from Nougat onwards, and #2147 tracks exposing this functionality. We're unlikely to prioritize it in the near future, however.

Not sure about TrueHD vs Atmos but [this page](https://blog.dolby.com/2014/06/dolby-atmos-home-theaters-questions-answered/) suggests that TrueHD is an extension.
