### ISSUE TITLE
ExoPlayer not able to play DASH media on Android 4.2.2

### ISSUE THREAD

**Issue by tanmaybaranwal** [google/ExoPlayer#2466]
- ExoPlayer not able to play DASH media on Samsung Galaxy Duos 4.2.1, while it is mentioned that minimum requirement for DASH is API 16. I've tried with ExoPlayer's Demo App and [other written code](https://gist.github.com/tanmaybaranwal/718e3993d32bb501f04015c72104f7e4). Both aren't working.
- I am using ExoPlayer 2.2.0
- The media is being played on 6.0.1 but not on 4.1.2 and 4.2.2
- On the ExoPlayer Demo App, the toast is "**Unable to instantiate OMX.PV avcdec**"
- The code which is linked above generates: 

> D/MediaCodecInfo: NoSupport [codec.profileLevel, avc1.64001f, video/avc] [OMX.PV.avcdec, video/avc] [logan2g, GT-S7262, samsung, 16]

**The complete log:**

> **E/ACodec**: Failed to allocate buffers after transitioning to IDLE state (error 0xfffffff4)
> **E/MediaCodec**: Codec reported an error. (omx error 0x80001001, internalError -12)
> **E/dalvikvm**: Could not find class 'android.media.MediaCodec$CodecException', referenced from method com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException.getDiagnosticInfoV21
> **W/dalvikvm**: VFY: unable to resolve instanceof 200 (Landroid/media/MediaCodec$CodecException;) in Lcom/google/android/exoplayer2/mediacodec/MediaCodecRenderer$DecoderInitializationException;
> **D/dalvikvm**: VFY: replacing opcode 0x20 at 0x0000
> **E/ExoPlayerImplInternal**: Renderer error.

**Comment by andrewlewis** [comment]
All representations in the stream linked in the first bullet item are in H.264/AVC High profile (the codecs attribute starts `avc1.64`), which exceeds the minimum requirements for video decoder support on Android API 16 builds. So it is not safe to assume that all devices can decode it (though many will be able to in practice). Please see [Supported formats](https://google.github.io/ExoPlayer/supported-formats.html#sample-formats) for more information.

If Baseline profile streams also can't be played and the device has another (software) decoder please let us know and we can blacklist the problematic decoder. Thanks.
