### ISSUE TITLE
CurrentPosition jumps at the beginning of the song

### ISSUE THREAD

**Issue by Nezz** [google/ExoPlayer#247]
When starting to mp3s (not tested with other formats) from the storage of the device I have noticed that the CurrentPosition jumps in a wierd way. When I start playing it jumps from 0 to X, then a bit later it jumps back by X.

Sample MP3:
https://mega.co.nz/#!oFMxCSCS!woKVlRK1m7Uk8OCa4_uXyO0IqLYTMXIydswLZ7iroaw

Logcat:
```
01-20 03:32:03.999 I/mono-stdout(28916): CurrentPosition=0
01-20 03:32:04.016 I/mono-stdout(28916): CurrentPosition=0
01-20 03:32:04.042 I/mono-stdout(28916): CurrentPosition=388
01-20 03:32:04.059 I/mono-stdout(28916): CurrentPosition=398
[...]
01-20 03:32:04.274 I/mono-stdout(28916): CurrentPosition=609
01-20 03:32:04.295 I/mono-stdout(28916): CurrentPosition=630
01-20 03:32:04.307 E/AudioTrack(28916): Discontinuity detected [expected 1020907, got 510453]
01-20 03:32:04.318 I/mono-stdout(28916): CurrentPosition=151
01-20 03:32:04.335 I/mono-stdout(28916): CurrentPosition=161
```
In this case at the beginning it jumped forward by ~400 ms then a bit later it jumped back by ~400 ms.

Half a second after those logs I get this (might be relevant):
```
01-20 03:32:04.769 I/mono-stdout(28916): CurrentPosition=609
01-20 03:32:04.819 E/MP3Extractor(28916): Unable to resync. Signalling end of stream.
01-20 03:32:04.821 I/mono-stdout(28916): CurrentPosition=650
```

I haven't observed this anything like this using the built in MediaPlayer.

Reproduced on the following devices: Alcatel Pop C7, Prestigio 5453, Huawei Y330 (all have MediaTek SOC)
Unable to reproduce on: Asus MeMoPad 7 (jumps forward 50-60ms at start, doesn't jump back)

**Comment by Nezz** [comment]
Occurs on master and dev branches too.

**Comment by ened** [comment]
How do you monitor the "CurrentPosition" exactly?

**Comment by Nezz** [comment]
It's a music game running a 60 fps loop. We query the CurrentPosition in every cycle and adjust the visuals accordingly.

**Comment by ojw28** [comment]
This issue was filed before ExoPlayer got its own MP3 extractor, so I'm guessing it was using the (now deprecated) FrameworkSampleSource. Please re-test using a recent version of ExoPlayer, where you should be using ExtractorSampleSource to make use of ExoPlayer's built in MP3 extractor.

Closing as obsolete. Please file a new issue if you're still able to reproduce using the steps above.
