### ISSUE TITLE
How to export ConcatenatingMediaSource into single mp4

### ISSUE THREAD

**Issue by redgetan** [google/ExoPlayer#2472]
Im using ConcatenatingMediaSource to playback multiple short mp4 in sequence (some of them coming from different sources). Is there a way to export the result into a single mp4 in sdcard for instance. I've tried to look for this information in the docs and issues but couldn't find anything.

**Comment by ojw28** [comment]
ExoPlayer is a library for media playback, not media generation, and hence this is not a supported feature.
