### ISSUE TITLE
Please change all methods and fields from private to protected

### ISSUE THREAD

**Issue by bigexxx** [google/ExoPlayer#2473]
It will be very useful if all methods and fields would be of type protected. 
Now i need very small modification for proper handling dpad controlling of seekbar (with proper delay, small steps with linear increase etc..), and for that i should copy all classes which used for that (SimpleExoPlayerView and PlaybackControlView) for small modification... it is not so good for later updates ((

**Comment by ojw28** [comment]
Whilst it might be convenient for you in the short term if we were we to do this, it would effectively add *every* field and method to the public API, meaning that changing literally anything could potentially break developers when they go to upgrade from one version of ExoPlayer to the next. This is not a good idea, and is not something we'll be doing.

It sounds like you're fixing something that doesn't work properly currently. Why not just contribute a fix directly to the library if so?
