### ISSUE TITLE
MediaSource for on-demand transcoded streams

### ISSUE THREAD

**Issue by waldheinz** [google/ExoPlayer#2483]
I have a HTTP server which can transcode video files to h264+aac / Matroska streams and deliver them live to the client. Using an `ExtractorMediaSource` I can play those streams just fine, but as expected the duration is unknown and seeking is not available.

Said server can also be queried for, amongst other stuff, the duration of the video files. For the transcoding, a query parameter accepting the start time is supported, and the server will deliver a stream from that time to the end of the source file.

So to support seeking I figured a custom `MediaSource` is due. What I currently have is a thin wrapper around `ExtractorMediaSource` which works like this:

  * in `prepareSource` it queries the server about the stream duration and calls back to the source listener with a `new SinglePeriodTimeline(duration, true)`
  * in `createPeriod` it instantiates the underlying `ExtractorMediaSource`, using the `positionUs` parameter to figure out the proper query parameter for the starting time and returns a MediaPeriod created by that source

This already gives me proper duration display, but seeking does not work: the `createPeriod` method is called only once, with `positionUs == 0`. An attempt to seek causes the playback to start from the beginning.

Obviously what I'm doing is not sufficient to communicate the specifics of my server to ExoPlayer, but honestly I'm a bit lost where to go from here. Is my `TimeLine` the problem, or passing through the `MediaPeriod`, both of them? 

PS: I could not dig out a mailing list / IRC channel for ExoPlayer, so please forgive I'm spamming the issue tracker with this.

**Comment by andrewlewis** [comment]
`ExtractorMediaPeriod` normally maps a timestamp onto a byte offset in `ExtractorMediaPeriod.seekToUs` using its `seekMap`. I guess your Matroska stream will be missing a cues element, so this seek map will be unseekable. You can verify this by breakpointing in that method and seeing what happens when you try to seek.

As a next step I'd probably try making a wrapper `Extractor` around `MatroskaExtractor` which passes in your own `ExtractorOutput` wrapper. Pass a factory that instantiates this wrapper to `ExtractorMediaSource`. You can intercept the call to `seekMap` and pass a replacement seekable seek map to the extractor output. Then the other piece you would need is a `DataSource` that adds the right query string parameter based on the last seeking operation. (You might need to lazily open the underlying source when reading starts, as `Extractor.seek` is called after `DataSource.open`.) The wrapped `Extractor` sees the same data as if it were really seeking in a complete stream. I haven't tried any of this so it might not work. There may also be simpler ways to achieve the same thing. Hope this helps!

**Comment by waldheinz** [comment]
@andrewlewis Thanks a bunch for your input, I actually got this to work. In addition to what you've said, there were two things to take care of:

  * The `MatroskaExtractor` doesn't like it very much when it's `DataSource` is swapped out, throwing `ArrayIndexOutOfBounds` exceptions and all kind of other scary stuff while choking on the "new" bytes it did not expect to see. So I'm lazily creating a new `MatroskaExtractor` in my own `Extractor.read` method whenever a seek occured.
  * Someone up in the pipeline seems to care about the timestamps contained in the Matroska stream, skipping output until a timestamp that is actually expected (or greater) comes by. I hacked my source to pass thru the timestamps from the source file instead of always starting at 0, so this problem is gone. I think this is the right thing to do anyway.

I'm very grateful you helped me to solve my immediate problem, but if there is a cleaner way to accomplish this I'd still like to hear about it. :-)

**Comment by andrewlewis** [comment]
Regarding recreating the `MatroskaExtractor` on every seek: is your wrapper correctly passing through the call to `seek(long, long)` before the new `DataSource` is read? That method resets some state in preparation for reading data from a different position, so it's important to call it. If you are calling that method but it's still failing I'd probably spend a while trying to debug what's going on, as it should work, assuming the server is providing valid data. From the extractor's perspective this looks like a 'normal' seek.

**Comment by waldheinz** [comment]
@andrewlewis You are right, I did not pass through the `seek` call, and doing so eliminates the need to re-create the `MatroskaExtractor`. Very nice!

But I just noticed something worse: Pausing the playback for too long (or re-starting the server, whatever causes the HTTP request to die) causes the playback to get stuck: The `DataSource` gets a `close` / `open` pair, which makes sense, but I don't see where I could get the proper "time" value from so I can build the proper query parameter for the server. The `DataSpec` passed into `DataSource.open` seems to carry only the byte-offset, but no time information. Is there some way to deal with that?

**Comment by andrewlewis** [comment]
If an error occurs while loading data, `ExtractorMediaSource` will try to resume from the last read byte offset. Can you make your server support range requests and just reopen using whatever query parameter you used the last time?

If that's not feasible then you could just stop and restart the player at the current playback position (just seeking won't work as seeking to the current position is a no-op). This is a pretty bad solution, though, as it will interrupt playback, and it's inefficient.

**Comment by waldheinz** [comment]
The server does not cache the transcoded video and stops the transcoding process when the request dies. So I don't see how I could implement range requests. :-/

In the end I dropped the custom `MediaSource` approach. Now I'm simply providing the player with a fresh `ExtractorMediaSource` on seek and added the relevant state tracking to my UI code. It's not exactly elegant, but so much simpler, I couldn't resist. :-)

Thanks again for your input @andrewlewis , I greatly appreciate your effort!
