### ISSUE TITLE
DRM protected content on rooted device

### ISSUE THREAD

**Issue by rburnham52** [google/ExoPlayer#2485]
We are currently looking at implementing ExoPlayer 2.x to play MPEG -DASH with Widevine protected content. One requirement we have though is that the user should not be able to play DRM protected content on rooted devices. 

What protection does exoplayer have when it comes to DRM content on rooted devices? If this is possible is there anything we need to do to enable this?

**Comment by ojw28** [comment]
> One requirement we have though is that the user should not be able to play DRM protected content on rooted devices.

I don't think this is a sensible requirement to have. It's your responsibility to specify the level of output protection you require when issuing keys to play the content. It's the responsibility of the underlying platform to only decrypt and play the content if the specified level of output protection is available, which may or may not depend on whether the device is rooted. If the device is rooted but still meets the level of output protection specified, then I can't think of a valid reason why you shouldn't allow playback to proceed. Preventing playback in this case will needlessly annoy many users.

> What protection does exoplayer have when it comes to DRM content on rooted devices? If this is possible is there anything we need to do to enable this?

ExoPlayer is pretty much just an intermediary when it comes to DRM. We parse the necessary information from the media container and plumb it to the underlying platform (e.g. via MediaDrm). So your question is more about the underlying platform. You should be able to trust that the underlying platform will enforce the specified security level whether a device is rooted or not. Many devices are able to support L1 Widevine with secure video output even when rooted. I suspect the vast majority of high end phones fall into this category. Some devices only support L3 Widevine whether they're rooted or not. A small subset of devices may support L1 Widevine when not rooted and only L3 Widevine when rooted.

**Comment by rburnham52** [comment]
@ojw28 Thanks for the info, while this might not seem like a sensible requirement its not something within our control, these requirements come from studio agreements.  I guess their concern is that it could be easier to rip drm protected content on a rooted devices. 

What your saying makes sense from a DRM point, i'm not sure how that will sit with the studios though. Sounds like i need to understand more about how android handles Widevine and the various security levels. Any suggestions on reading material?

**Comment by ojw28** [comment]
@nitro52 - I suggest you look at clarifying the requirement with the studios. For non-Android devices it may be that it makes sense. For Android devices I think playback should be allowed based on whether the device satisfies a certain Widevine security level (e.g. L1 or L3), not on some other arbitrary piece of information. It's possibly just an oversight.
@wvpaf - Do you know if this kind of requirement is normal in studio agreements?

**Comment by wvpaf** [comment]
@nitro52 & @ojw28, studio requirements differ too much to generalize.

However, the app should be able to tell if the device is rooted and invalidate the keys that have been delivered. Root detection does not automatically stop playback as mentioned earlier, typically playback continues but with a reduced video quality. 
to determine if rooted see : http://stackoverflow.com/questions/3424195/determining-if-an-android-device-is-rooted-programatically

**Comment by ojw28** [comment]
Closing as answered.

**Comment by rburnham52** [comment]
@ojw28 @wvpaf  Thanks for your help guys. If we can find a separate reliable root check then we might be able to handle this ourselves
