### ISSUE TITLE
No sound 

### ISSUE THREAD

**Issue by alexeymasliakov** [google/ExoPlayer#2488]
No sound, test with https://www.hlsplayer.net/ 
http://vod-i.uefa-france.beinsports.com/074350cb-690e-4697-9280-333a02868321/ea3e99d5-c3ee-41c7-8edd-2446049023c6.ism/manifest(format=m3u8-aapl).m3u8?hdnea=st=1487760901~exp=1487762101~acl=*~hmac=4b533869ea193c2d44ac94fb19415ad29ba8ce9b0ce42635ddcb556d19cd18f8

**Comment by AquilesCanta** [comment]
It gives me a 403. Can you fix it?

**Comment by alexeymasliakov** [comment]
just copy/paste url

**Comment by ojw28** [comment]
The link doesn't work for me either. It's either geo-restricted or no longer available. If it's geo-restricted then ideally provide a non-restricted test stream. If that's not possible, at least let us know to which country it's geo-restricted. I tried proxying via France, US and GB, and see a 403 response code in all cases.

**Comment by ojw28** [comment]
Closing because a working test stream has not been provided.
