### ISSUE TITLE
How do add multiple subtitle tracks and list/select them

### ISSUE THREAD

**Issue by tmho** [google/ExoPlayer#2489]
How do you list/select subtitle tracks in 2.2.0?  I'm using the `SimpleExoPlayer`.  When I supply multiple tracks, the first one will load and be active, but I'm not sure what happens to the second now how I can access it, I can't seem to see how to change or list the available tracks for a track type.

In exo 1.x I'm used to `player.setSelectedTrack(TYPE, INDEX)`

I'm trying to sideload 2 subtitle files like so:
```
Format englishSubs = Format.createTextSampleFormat(null, MimeTypes.APPLICATION_SUBRIP, null, Format.NO_VALUE, Format.NO_VALUE, "eng", null);
Format thaiSubs = Format.createTextSampleFormat(null, MimeTypes.APPLICATION_SUBRIP, null, Format.NO_VALUE, Format.NO_VALUE, "thai", null);
MediaSource englishSubsSource = new SingleSampleMediaSource(Uri.parse(ENGLISH), new DefaultHttpDataSourceFactory("userAgent"), englishSubs, C.TIME_UNSET);
MediaSource thaiSubsSource = new SingleSampleMediaSource(Uri.parse(THAI), new DefaultHttpDataSourceFactory("userAgent"), thaiSubs, C.TIME_UNSET);
MergingMediaSource mergedSource = new MergingMediaSource(videoSource, englishSubsSource, thaiSubsSource);
```

**Comment by ojw28** [comment]
If you modify the demo app to build your source, do you see both options listed under the "Text" button? If so, I suggest you try answering your own question by taking a look at how the demo app is doing it.

**Comment by tmho** [comment]
Is this on the right track?  I am able to changed the selected track with the following:

rendererIndex = index of the tracks you want to select from
indexOfTrackSelected = index which you'd like to chose

```
trackGroups = trackSelector.getCurrentMappedTrackInfo().getTrackGroups(rendererIndex);
override = new MappingTrackSelector.SelectionOverride(new FixedTrackSelection.Factory(), indexOfTrackSelected, 0);
trackSelector.setSelectionOverride(rendererIndex, trackGroups, override);
```

I'm still not clear what `0` value in the `MappingTrackSelector.SelectionOverride(new FixedTrackSelection.Factory(), indexOfTrackSelected, 0)` represents

**Comment by ojw28** [comment]
Yes. Pretty much! Tracks are arranged into groups. The `trackGroups` variable is an array of `TrackGroup` instances. Each `TrackGroup` may contain multiple individual tracks, each with its own format. A `TrackGroup` contains multiple individual tracks when it's possible to adapt between different quality streams of the same content. So for an adaptive video playback you'll typically see a `TrackGroup` containing multiple individual video tracks whose formats have different resolutions or bitrates. You don't generally expect to adapt between different text tracks, so a text `TrackGroup` will typically contain only a single track.

So to add comments to your block of code:

```
trackGroups = trackSelector.getCurrentMappedTrackInfo().getTrackGroups(rendererIndex);
// Look in trackGroups to locate the track you want to enable. You should end up with the
// index of the group and the index of the individual track within the group.
int trackGroupIndex = .....;
int trackIndexWithinGroup = .....; // Probably 0.
// Create the selection override
override = new MappingTrackSelector.SelectionOverride(
    new FixedTrackSelection.Factory(), trackGroupIndex, trackIndexWithinGroup);
trackSelector.setSelectionOverride(rendererIndex, trackGroups, override);
```

**Comment by tmho** [comment]
great! thanks for the info :+1:
