### ISSUE TITLE
exo_progress customization problems

### ISSUE THREAD

**Issue by vkhodonovych** [google/ExoPlayer#2490]
I have the problem to customize SeekBar `exo_progress ` for video progress. I'm trying to change a color of the SeekBar using approach described in the article(Customizing ExoPlayer’s UI components) ` app:controller_layout_id` but the issue with thumb color. I guess the problem inside `PlaybackControlView` but I don't know exactly where.  Here is my code:
xml file
    
       <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginTop="4dp"
            android:gravity="center_vertical"
            android:orientation="vertical">

            <SeekBar
                android:id="@id/exo_progress"
                android:layout_width="match_parent"
                android:layout_height="32dp"
                android:focusable="false" />

            <SeekBar
                android:id="@+id/exo_progress2"
                android:layout_width="match_parent"
                android:layout_height="32dp"
                android:focusable="false" />
        </LinearLayout>`

and java code

         // seekBar
        SeekBar seekBar = (SeekBar) playerView.findViewById(R.id.exo_progress);
        seekBar.getProgressDrawable().setColorFilter(new PorterDuffColorFilter(Color.parseColor("#DC221D"), PorterDuff.Mode.MULTIPLY));
        seekBar.getThumb().setColorFilter(new PorterDuffColorFilter(Color.RED, PorterDuff.Mode.SRC_IN));
        // seekBar2
        SeekBar seekBar2 = (SeekBar) playerView.findViewById(R.id.exo_progress2);
        seekBar2.getProgressDrawable().setColorFilter(new PorterDuffColorFilter(Color.parseColor("#DC221D"), PorterDuff.Mode.MULTIPLY));
        seekBar2.getThumb().setColorFilter(new PorterDuffColorFilter(Color.RED, PorterDuff.Mode.SRC_IN));

I have two different results for same code, see attached [link]( http://prntscr.com/ecd07t)
- The version of ExoPlayer being used is r2.2.0.
- The version of Android on which the issue can be reproduced is 4.4 KitKat.

How can fix this?

**Comment by ifucolo** [comment]
Hello
Try change your seekBar on xml for this:

```
<SeekBar
            android:id="@id/exo_progress"
            android:layout_width="match_parent"
            android:layout_height="30dp"
            android:layout_weight="1"
            android:progress="100"
            android:thumbTint="@color/blue" 
            android:progressTint="@color/red"
            android:background="#CC000000"/>
```


and change thumbTint and progressTint for a color you prefer

**Comment by toanvc** [comment]
Use this in your java code:
```
seekBar.setThumb(ContextCompat.getDrawable(context, R.drawable.your_thumb_id));
seekBar.setProgressDrawable(ContextCompat.getDrawable(context, R.drawable.your_progress_id)));
```

or you can also use them in your `xml` to customize your `SeekBar`. This issue doesn't belong to `ExoPlayer`, belongs to your code and your view. 

Refer to this link to see how custom it:
http://stackoverflow.com/questions/34932963/android-seekbar-with-custom-drawable

**Comment by ojw28** [comment]
Agreed this question is outside the scope of this issue tracker; it seems like a general question about Android view/ui customization.
