### ISSUE TITLE
Error HLS video playing

### ISSUE THREAD

**Issue by bene25** [google/ExoPlayer#2495]
HLS video doesn't play on ExoPlayer version r2.2.0. On the same device with ExoPlayer 2.1.0 everything works well.
Reproduced on Lenovo Vibe P1 API 23 and Emulator Nexus 5 API 22
Logs and M3U8 file sample in attachments.
[log_and_file_sample.zip](https://github.com/google/ExoPlayer/files/796886/log_and_file_sample.zip)

**Comment by AquilesCanta** [comment]
A fix will be available in the next push. Next time, please provide a link to the problematic media.

**Comment by ojw28** [comment]
Fixed in the dev-v2 branch.
