### ISSUE TITLE
DefaultTrackSelector : selectTextTrack skips the only closed caption track

### ISSUE THREAD

**Issue by wromaniuk** [google/ExoPlayer#2498]
I am trying to display closed captions using different streams than included in exoplayer demo, but found some issue.
I have debugged function selectTextTrack in DefaultTrackSelector.java and example stream (to be precise https://tungsten.aaplimg.com/VOD/bipbop_adv_example_v2/master.m3u8) is including few tracks and choosen to set in that function has selectionFlags value 5. 
Other stream I am trying to display CC has only one track and selectionFlags value is 0.
Cause isDefault and isForced are false in that case and formatHasLanguage also returns false flow of function is going to case: 
            // Track should not be selected.
            continue;
in result the only existing closed caption track is skipped and text track is not set.

I wonder if it is intentional behaviour or maybe it could be modified?

- ExoPlayer version: cloned from git@github.com:google/ExoPlayer.git 2017.02.22, branch  release-v2
- The device and version of Android: MIBOX3, Android TV 6.0.1

**Comment by ojw28** [comment]
We don't enable text tracks by default unless the media indicates that they should be enabled by default. If you try playing that stream in the demo app, you'll see that it's possible to manually enable the tracks through the UI by clicking the text button. So you should look at what the demo app does and do something similar in your app. Some of the responses in this issue may be helpful for you when figuring out which pieces of code you need to use: https://github.com/google/ExoPlayer/issues/2489

**Comment by wromaniuk** [comment]
Thanks for really quick response.
I have checked and I can confirm that after change text in UI demo app closed captions are now visible also for my stream.
Thanks again, Best Regards
