### ISSUE TITLE
Unexpected IllegalStateException: Top bit not zero When playing live dash stream

### ISSUE THREAD

**Issue by Naveen898989** [google/ExoPlayer#2500]
- We have a DASH test stream that we are trying to play but its not working. Player gives "Top bit not zero" error. It seems to be thrown when retrieving the NAL length. The first few NAL values seem to be fine. Suddenly, an incorrect NAL value comes in and after that it all goes down hill.
[log.txt](https://github.com/google/ExoPlayer/files/801003/log.txt)
- I am using r2.2.0
- Tested on Nexus 5x (Android 7.1), Samsung Tab 4 (Android 6.0.1)

Please let me know if you need anything else.

**Comment by ojw28** [comment]
Given we're able to play DASH content provided by many providers successfully, I think it's likely this is a content issue. Please validate the correctness of the video segments. If you can point to a specific thing in the media that's valid but we're not handling correctly, please let us know.

**Comment by Naveen898989** [comment]
The streams seems to be working on a couple of other players. Unfortunately, I do not know why it is failing. Is there a way for me to check the stream itself for correctness?

**Comment by ojw28** [comment]
At a high level it looks like the NAL unit lengths aren't specified correctly. The parsing logic ends up out of sync with the NAL unit headers and starts reading clearly incorrect lengths, leading to the failure. I think you'll need to spend some time debugging this yourself.

You may have to resort to manually inspecting and understanding the bitstream to see what's wrong, unfortunately. This is quite time consuming, and given this appears to be an isolated case we don't have cycles to help. If you discover the bitstream is valid and we're failing to handle some obscure case, please let us know specifically what that case is and we'll take another look.

You could also try reporting/discussing the issue with whoever provides the encoder and/or packager that's generating these streams.

**Comment by Naveen898989** [comment]
Thanks for the reply. You are right, in fact the sample sizes and the NAL lengths do not align. When a NAL length comes in that goes beyond the current sample size it skips reading all the data. Next time it reads the NAL it reads in a wrong position. I am not sure if this is a valid case or not, I just wanted you to know.
