### ISSUE TITLE
Support forcing playback controls to remain visible

### ISSUE THREAD

**Issue by yasaman93** [google/ExoPlayer#2501]
ExoPlayer view hides after some times. how can I prevent it from hiding?

**Comment by ojw28** [comment]
Call [setControllerShowTimeoutMs(0)](https://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/ui/SimpleExoPlayerView.html#setControllerShowTimeoutMs-int-)

**Comment by yasaman93** [comment]
I want my ExoPlayer view always be visible, even on clicks. how can I do that?
This method not set exoplayer view always visible!

**Comment by ojw28** [comment]
Ah, understood. There's no built in way to do this currently. Marking this issue as an enhancement. In the meantime, it shouldn't be too hard for you to build your own UI component, or modify `SimpleExoPlayerView` to support this yourself.

**Comment by ojw28** [comment]
This is supported in `dev-v2` and will be supported as of `r2.4.0`, which we hope to release later this week. You can:

1. Call setControllerShowTimeoutMs(0) to disable timeout.
1. Call setControllerHideOnTouch(false) to disable hide on touch.

The combination of the two should result in controls being always visible.
