### ISSUE TITLE
Select track from ADB

### ISSUE THREAD

**Issue by beakman** [google/ExoPlayer#2502]
I want to force certain video resolution from the adb.

For example: `adb shell am start -a com.google.android.exoplayer.demo.action.VIEW \ -d https://yourdomain.com/sample.mp4 --es vid_resolution "300x200"`

Any ideas on how can I do this?

Thank you all.

**Comment by ojw28** [comment]
This is not a supported feature of our demo app. It would be possible for you to do this kind of thing with your own application, but doing so fall outside the scope of this issue tracker.
