### ISSUE TITLE
Media Metadata tags

### ISSUE THREAD

**Issue by thesiamak** [google/ExoPlayer#2504]
First thanks to this awesome library . 

Second simply : **how can i get** loaded media(MP3/OGG/..) **meta data**(Artist , name,track no ,year and .. ) ? 
What about audio file artwork graphic ?

**Comment by ojw28** [comment]
If you're using the ExoPlayer V2 demo app then you should see metadata output to logcat with the log tag "EventLogger". It should be pretty easy for you to find where that happens in the demo app code, and then go from there.

We currently parse metadata for MP3 and MP4. I don't think we parse metadata for OGG yet. Please file a separate feature request if you're able to confirm that this is the case, linking or attaching media that you know to contain metadata that's not being output to "EventLogger". Thanks!

**Comment by thesiamak** [comment]
At this time i just need MP3 metadatas .
I was be able to get metadata via the method that demo app uses to(EventLogger) but obviously developers need a simpler way to get this information.

Thanks a lot for your help

**Comment by ojw28** [comment]
I'm not sure developers do need a simpler way. It's pretty simple already, once you remove the parts that you don't need:

```
MappedTrackInfo mappedTrackInfo = trackSelector.getCurrentMappedTrackInfo();
if (mappedTrackInfo != null) {
  for (int rendererIndex = 0; rendererIndex < mappedTrackInfo.length; rendererIndex++) {
    TrackSelection trackSelection = trackSelections.get(rendererIndex);
    if (trackSelection != null) {
      for (int selectionIndex = 0; selectionIndex < trackSelection.length(); selectionIndex++) {
        Metadata metadata = trackSelection.getFormat(selectionIndex).metadata;
        if (metadata != null) {
          // Metadata!
        }
      }
    }
  }
}
```

I'm not convinced that it's possible to make it simpler without introducing assumptions that might be true in your simple use case, but that may not be true in the general case (e.g. the assumption that there's only one set of metadata in the media, rather than potentially multiple pieces of metadata attached to different tracks, which may or may not be selected).

**Comment by thesiamak** [comment]
Now it's more clear! I was using a wrong and complicated method(Passing an interface to Logger) . I appreciate that.
Could you please let me know how to get MP3 artwork graphic too ? Since i couldn't find appropriate field for that in meta data(It's displaying an empty field in Logcat) i was looking for a way to get selected tracks artwork(cover) url . The goal is to load image in an ImageView.

**Comment by ojw28** [comment]
`SimpleExoPlayerView` pulls the artwork out of the `Metadata` object to display it, so take a look at what that class does (specifically, look at `SimpleExoPlayerView.setArtworkFromMetadata`).
