### ISSUE TITLE
how can I made the format background transparent!

### ISSUE THREAD

**Issue by Witype** [google/ExoPlayer#2506]
*** PLEASE DO NOT IGNORE THIS ISSUE TEMPLATE ***

Please search the existing issues before filing a new one, including issues that
are closed. When filing a new issue please include ALL of the following, unless
you're certain that they're not useful for the particular issue being reported.

- A description of the issue.
- Steps describing how the issue can be reproduced, ideally in the ExoPlayer
  demo app.
- A link to content that reproduces the issue. If you don't wish to post it
  publicly, please submit the issue, then email the link to
  dev.exoplayer@gmail.com including the issue number in the subject line.
- The version of ExoPlayer being used.
- The device(s) and version(s) of Android on which the issue can be reproduced,
  and how easily it reproduces. If possible, please test on multiple devices and
  Android versions.
- A bug report taken from the device just after the issue occurs, attached as a
  file. A bug report can be captured using "adb bugreport". Output from "adb
  logcat" or a log snippet is not sufficient.

I can play webm format file in demo,But the video background color is black,I want change the background to transparent so that I can play more than  3 or 4 at the some time ,how I can do this,thanks!

**Comment by ojw28** [comment]
Closing due to lack of clarity.

**Comment by Witype** [comment]
I playback the .webm file,how can I make the black area transparent,
![image](https://cloud.githubusercontent.com/assets/6899329/23395396/51e99908-fdc9-11e6-87b7-1145a2e4f08f.png)
The origin webm file background is transparent(in chrome),
![image](https://cloud.githubusercontent.com/assets/6899329/23395446/9ace65a4-fdc9-11e6-9be7-b0282f41015e.png)

**Comment by ojw28** [comment]
Tracked in https://github.com/google/ExoPlayer/issues/2509
