### ISSUE TITLE
how can I make .webm black background to transparent 

### ISSUE THREAD

**Issue by Witype** [google/ExoPlayer#2509]
**background color is transparent in chrome,**
![image](https://cloud.githubusercontent.com/assets/6899329/23395518/01b89e56-fdca-11e6-964e-41f21dd405ed.png)
 **background color is black when playback webm in exoplayer,**
![image](https://cloud.githubusercontent.com/assets/6899329/23395527/146819aa-fdca-11e6-9150-b648c60b8002.png)
thanks!!!

**Comment by ojw28** [comment]
@vigneshvg - Apparently you know about this ;) ([source](https://developers.google.com/web/updates/2013/07/Alpha-transparency-in-Chrome-video)). My guess would be there's no support for this on Android as I doubt the platform decoder will even output an alpha channel? Just a guess though - please clarify what your expectations would be!

**Comment by Witype** [comment]
@vigneshvg Is there anyway to do this,

in exoplayer
![8b208a60-051c-11e7-95e4-db1186532ef9](https://cloud.githubusercontent.com/assets/6899329/23777784/dbfd8168-0571-11e7-91db-62535597ee20.png)

in chrome
![479365a6-051c-11e7-8f05-e4ec2160ba94](https://cloud.githubusercontent.com/assets/6899329/23777785/dbfdb962-0571-11e7-9e62-85fc9a0fc2b2.png)

**Comment by vigneshvg** [comment]
The platform decoder does not support alpha channel.

It is theoretically possible to build an app that uses a bundled VPx decoder to decode the YUV and Alpha channels separately and render them in a surface that supports alpha blending. Although, as of now, it is beyond the scope of ExoPlayer (and the VP9 extension).

If there's enough interest (or use-cases), it could be added into the VP9 extension where we have two instances of the decoder (similar to how chrome supports it) and change the OpenGL shader to include the appropriate alpha channel values. But it may not be a simple change.

**Comment by Witype** [comment]
@vigneshvg 
I change the code libyuv::I420ToRGB565 to   libyuv::I420ToBGRA it has alpha channel ,but the color Incorrect,can you help me please ,thanks very much!
![device-2017-03-24-141829](https://cloud.githubusercontent.com/assets/6899329/24282909/56c889a2-109d-11e7-87a9-eb5d382492a8.png)

origin picture

![40001](https://cloud.githubusercontent.com/assets/6899329/24282935/8443511e-109d-11e7-9c0b-e3549fa12f64.png)


~~~
FUNC(jint, vpxGetFrame, jlong jContext, jobject jOutputBuffer) {
  ...
  if (outputMode == kOutputModeRgb) {
    // resize buffer if required.
    jboolean initResult = env->CallBooleanMethod(jOutputBuffer, initForRgbFrame,
                                                 img->d_w, img->d_h);
    if (initResult == JNI_FALSE) {
      return -1;
    }

    // get pointer to the data buffer.
    const jobject dataObject = env->GetObjectField(jOutputBuffer, dataField);
    uint8_t* const dst =
        reinterpret_cast<uint8_t*>(env->GetDirectBufferAddress(dataObject));

   // change this code libyuv::I420ToRGB565

    libyuv::I420ToBGRA(img->planes[VPX_PLANE_Y], img->stride[VPX_PLANE_Y],
                         img->planes[VPX_PLANE_U], img->stride[VPX_PLANE_U],
                         img->planes[VPX_PLANE_V], img->stride[VPX_PLANE_V],
                         dst, img->d_w * 4,
                        img->d_w, img->d_h);
  } else if (outputMode == kOutputModeYuv) {
    ...
  }
  return 0;
}
~~~
