### ISSUE TITLE
How can i scale video in ExoPlayer-V2 ?

### ISSUE THREAD

**Issue by kinhdang** [google/ExoPlayer#2511]
Dear all !
How can i scale video in ExoPlayer-V2 ?
We use com.google.android.exoplayer2.ui.SimpleExoPlayerView From ExoPlayer Example.

![20170228_155540](https://cloud.githubusercontent.com/assets/9839084/23398450/34354366-fdcf-11e6-8bbe-fd56918d166a.jpg)
![20170228_155552](https://cloud.githubusercontent.com/assets/9839084/23398466/435905d0-fdcf-11e6-8f57-de3dd22c5784.jpg)

THanks.

**Comment by toanvc** [comment]
Ask your content media person give you another video with aspect ratio 16:9, you will get your proper video on the screen. 
If you forced scale your video with the screen size, your video would be deformed.

**Comment by kinhdang** [comment]
hello toanvc !

yes we know that, but in v1 ExoPlayer can be scaled video with ascpect ratio in event   onVideoSizeChanged.

Any idea how to do this in v2, please help ?

**Comment by timusus** [comment]
You can set the `app:resize_mode="..."` in xml, or from code, use `simpleExoPlayerView.setResizeMode(...)`

See https://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/ui/SimpleExoPlayerView.html#setResizeMode-int-

**Comment by kinhdang** [comment]
hi timusus !

we use exoplayer2 with compile 'com.google.android.exoplayer:exoplayer:r2.0.0' , but can not found method simpleExoPlayerView.setResizeMode or Attribute app:resize_mode in xml file,

Thanks.

**Comment by kinhdang** [comment]
hi timusus !

maybe wrong version.

Thanks.

**Comment by timusus** [comment]
Yeah, I'm using v2.2.2 I believe.

**Comment by kinhdang** [comment]
thanks,
