### ISSUE TITLE
Improve smartness of Util.inferContentType

### ISSUE THREAD

**Issue by alfonsoramosa** [google/ExoPlayer#2513]
Exoplayer 2.2.0
Device: Nexus player
Android 7.1.1

Hi,

I have been playing Smooth Streaming clips with ExoPlayer,  without problem, with an url like:
http://myserver.com/video/example1.isml

But now I need to play a stream that is a "virtual subclip", with an url like
http://myserver.com/video/example1.isml/manifest?t=2017-02-22T17:30:00-2017-02-22T17:55:00

ExoPlayer can't identify the content type using this url and can't play the stream
see `Util.inferContentType(String fileName)`
ExoPlayer is using "manifest" as fileName instead of "example1.isml"

Are that kind of "virtual sublips" supported by ExoPlayer?
Wich is the right url format for that?

Can you please advice me about this issue?
Thanks

**Comment by ojw28** [comment]
If the problem is that `inferContentType` cannot infer the type correctly, but you already know the type, then the simple solution is just to not call `inferContentType` in the first place? The ExoPlayer demo app also supports hinting of the type to help with cases where it cannot be inferred. For example you can add a sample with hint to the samples json file like:

```
      {
        "name": "Name of sample",
        "uri": "http://myserver.com/video/example1.isml/manifest?t=2017-02-22T17:30:00-2017-02-22T17:55:00",
        "extension": "isml"
      }
```

where `extension` is the hint.

**Comment by alfonsoramosa** [comment]
Hi,

The problem here is that I don't know the type, just the url.
The type should be inferred using the url.

So, the question is if it's possible to use this kind of SS url's, with start and ent time with ExoPlayer and in the same time use Exoplayer's type inference feature.

**Comment by ojw28** [comment]
You could also just implement your own `inferContentType` method that's smart enough to work for this use case. It should be pretty trivial to do so? There's no reason why you have to use the implementation provided by the library.

Re-opening this to track making the library version a bit smarter for this case, but we'll handle it as low priority.
