### ISSUE TITLE
Incomplete Audio Object Type Parsing

### ISSUE THREAD

**Issue by otefhg** [google/ExoPlayer#2514]
exoPlayer 2.2.0
Not a device related bug
Not an SDK related bug

The parsing of the audioObjectType is incomplete in relation to the standard document ISO/IEC 14496-3, 
Table 1.16 – Syntax of GetAudioObjectType(), page 41.

In the file ExoPlayer-release-v2\library\src\main\java\com\google\android\exoplayer2\util\CodecSpecificDataUtil.java,
function parseAacAudioSpecificConfig(), line 89, the audio object type is parsed as follows:
`
  int audioObjectType = bitArray.readBits(5);
`        
However the standard states that a further 6 bits may be parsed to allow for an audioObjectType greater than 31.
In "Table 1.16 – Syntax of GetAudioObjectType()" the standard states the audioObjectType should be parsed as follows:

```
  GetAudioObjectType() 
  { 
    audioObjectType;                                                 5  uimsbf   
        if (audioObjectType == 31) {   
      audioObjectType = 32 + audioObjectTypeExt;  6 uimsbf  
        }    
        return audioObjectType;   
  } 
```
  
In addition the function buildAacAudioSpecificConfig() will need to be updated to allow for cases where the 
audioObjectType > 31.

Currently buildAacAudioSpecificConfig() is  

```
  public static byte[] buildAacAudioSpecificConfig(int audioObjectType, int sampleRateIndex,
      int channelConfig) {
    byte[] specificConfig = new byte[2];
    specificConfig[0] = (byte) (((audioObjectType << 3) & 0xF8) | ((sampleRateIndex >> 1) & 0x07));
    specificConfig[1] = (byte) (((sampleRateIndex << 7) & 0x80) | ((channelConfig << 3) & 0x78));
    return specificConfig;
  }
```

In order to correctly fill the specificConfig[] buffer we need to account for higher values of audioObjectType bit field.

```
  public static byte[] buildxHEAacAudioSpecificConfig(int audioObjectType, int sampleRateIndex,
                                                   int channelConfig) {
    byte[] specificConfig;
    int position=0;
    if(audioObjectType>31) {
      specificConfig = new byte[3];
      audioObjectType-=32;
      specificConfig[0] = (byte) (((0xFF << 3) & 0xF8) | ((audioObjectType >> 3) & 0x07 ));
      specificConfig[1] = (byte) (((audioObjectType<<5)&0xE0) | ((sampleRateIndex << 1)&0x1E) | ((channelConfig >> 3) & 0x01));
      specificConfig[2] = (byte) (((channelConfig << 5) & 0xE0));

    } else if (audioObjectType<31 && audioObjectType>=0) {
      specificConfig = new byte[2];
      specificConfig[0] = (byte) (((audioObjectType << 3) & 0xF8) | ((sampleRateIndex >> 1) & 0x07));
      specificConfig[1] = (byte) (((sampleRateIndex << 7) & 0x80) | ((channelConfig << 3) & 0x78));
    } else {
      return null;
    }
    return specificConfig;
  }
```

**Comment by andrewlewis** [comment]
@otefhg Thanks for reporting this. I'll submit a fix for parsing the audio specific config soon. It appears that we don't currently have any code that would pass an escaped AOT to `buildAacAudioSpecificConfig`, as we only use it for creating CSD when it's absent (in ADTS and SmoothStreaming manifests). Could you clarify how/where the fix for that method will be used?

**Comment by otefhg** [comment]
The fix is required if you want to play an mp4-file (using the USAC codec), as well as for Shoutcast and DASH streaming. In those cases the AOT == 42.

**Comment by andrewlewis** [comment]
Could you clarify whether the fix in 422c2d0 is sufficient? If you also need a fix for `buildAacAudioSpecificConfig`, please clarify where it will be used, as I don't think we currently pass an extended AOT anywhere in the library.

**Comment by otefhg** [comment]
The buildAacAudioSpecificConfig fix is not necessary , thanks again.

**Comment by andrewlewis** [comment]
Cool. Thanks for reporting this!
