### ISSUE TITLE
Provide callback that's invoked when video tunneling is enabled/disabled

### ISSUE THREAD

**Issue by directable** [google/ExoPlayer#2518]
Was curious if there is a mechanism to determine if tunneling was succesfully enabled when setting via setTunnelingAudioSessionId(int tunnelingAudioSessionId)

Also are there any plans to add to demo ?

**Comment by ojw28** [comment]
I don't think this information is exposed currently, but it should be fairly easy to expose it. It would necessarily be asynchronous though (e.g. a callback method invoked each time tunneling is enabled or disabled). Marking as an enhancement to consider exposing this information.

In the meantime, if you're just curious as to whether it's being enabled, you can add a log line [here](https://github.com/google/ExoPlayer/blob/r2.2.0/library/src/main/java/com/google/android/exoplayer2/trackselection/MappingTrackSelector.java#L490) that prints whether `enableTunneling` is true or false.

**Comment by tonihei** [comment]
We added a method `ExoPlayer.isTunnelingEnabled` to query the tunneling state of the currently selected tracks. You can listen to `Player.Listener.onTracksChanged` to get notified when tracks (and potentially this value) change.
