### ISSUE TITLE
Sometime would pop up play error durng playing video 

### ISSUE THREAD

**Issue by qiuxinyidian** [google/ExoPlayer#2526]
description：
     [Youtube] Sometime would pop up play error durng playing Youtube video 

     Top Activity:(1)com.android.systemui.recents.RecentsActivity 
     (2)com.google.android.apps.photos.home.HomeActivity 
     (3)com.google.android.apps.youtube.app.WatchWhileActivity 

03-02 21:13:15.895 20414 29478 E Surface : getSlotFromBufferLocked: unknown buffer: 0x7f72033720
03-02 21:13:15.895 20414 29478 W ACodec  : [OMX.qcom.video.decoder.avc] can not return buffer 15 to native window
03-02 21:13:15.898   670  6191 I OMX-VDEC-1080P: omx_vdec::component_deinit() complete
03-02 21:13:15.899   670  6191 I OMX-VDEC-1080P: Exit OMX vdec Destructor: fd=38
03-02 21:13:15.900   670  6191 I OMX-VDEC-1080P: Video slvp perflock released
03-02 21:13:15.915 20414 29471 E ExoPlayerImplInternal: Stop failed.
03-02 21:13:15.915 20414 29471 E ExoPlayerImplInternal: java.lang.IllegalStateException
03-02 21:13:15.915 20414 29471 E ExoPlayerImplInternal: 	at android.media.MediaCodec.native_stop(Native Method)
03-02 21:13:15.915 20414 29471 E ExoPlayerImplInternal: 	at android.media.MediaCodec.stop(MediaCodec.java:2007)
03-02 21:13:15.915 20414 29471 E ExoPlayerImplInternal: 	at hfp.p(SourceFile:485)
03-02 21:13:15.915 20414 29471 E ExoPlayerImplInternal: 	at rmq.p(SourceFile:272)
03-02 21:13:15.915 20414 29471 E ExoPlayerImplInternal: 	at hfp.k(SourceFile:447)
03-02 21:13:15.915 20414 29471 E ExoPlayerImplInternal: 	at hgb.k(SourceFile:289)
03-02 21:13:15.915 20414 29471 E ExoPlayerImplInternal: 	at rmq.k(SourceFile:192)
03-02 21:13:15.915 20414 29471 E ExoPlayerImplInternal: 	at hfe.c(SourceFile:8231)
03-02 21:13:15.915 20414 29471 E ExoPlayerImplInternal: 	at hfe.g(SourceFile:5560)
03-02 21:13:15.915 20414 29471 E ExoPlayerImplInternal: 	at hfe.f(SourceFile:526)
03-02 21:13:15.915 20414 29471 E ExoPlayerImplInternal: 	at hfe.handleMessage(SourceFile:245)
03-02 21:13:15.915 20414 29471 E ExoPlayerImplInternal: 	at android.os.Handler.dispatchMessage(Handler.java:98)
03-02 21:13:15.915 20414 29471 E ExoPlayerImplInternal: 	at android.os.Looper.loop(Looper.java:154)
03-02 21:13:15.915 20414 29471 E ExoPlayerImplInternal: 	at android.os.HandlerThread.run(HandlerThread.java:61)
03-02 21:13:15.915 20414 29471 E ExoPlayerImplInternal: 	at hru.run(SourceFile:40)

[Step] 
    1. Launch Youtube. 
    2. play Youtube video. 

happenedfrequency:Low
AndroidReleaseVer:7.1.1
happenedtime:2017/03/02 21:13:14
[Uploading log.zip…]()

**Comment by ojw28** [comment]
YouTube issues should be reported to YouTube (via the built in send feedback feature).
