### ISSUE TITLE
Support amr format file

### ISSUE THREAD

**Issue by Charles-ljc** [google/ExoPlayer#2527]
When I play an AMR NB format file recorded by android.media.MediaRecorder, I got an error "UnrecognizedInputFormatException: None of the available extractors could read the stream".
Is this format not supported?

**Comment by ojw28** [comment]
Please can you attach a sample stream to this issue, or email one to `dev.exoplayer@gmail.com` (and update this issue to indicate that you've done so)? Thanks!

**Comment by Charles-ljc** [comment]
A sample was emailed to that address.

**Comment by altair441n** [comment]
@liujinchaoDS I met same problem.What's the any solution?

**Comment by altair441n** [comment]
@liujinchaoDS @ojw28 I met same problem.What's the any solution?
