### ISSUE TITLE
VideoCapabilities: Unsupported profile 2 for video/mp4v-es

### ISSUE THREAD

**Issue by ghost** [google/ExoPlayer#2528]
Before playing out this error then only it plays, sometimes just a black screen

> I/ExoPlayerImpl: Init 2.0.0
> V/AdvPlayer: Listener-onPlayerStateChanged...1
> I/VideoCapabilities: Unsupported profile 2 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 2 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 2 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 2 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 2 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 2 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 2 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 2 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 8 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 8 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 8 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 8 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 8 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 8 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 8 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 8 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 16 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 16 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 16 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 16 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 16 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 16 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 16 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 16 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 32 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 32 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 32 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 32 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 32 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 32 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 32 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 32 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 64 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 64 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 64 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 64 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 64 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 64 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 64 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 64 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 128 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 128 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 128 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 128 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 128 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 128 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 128 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 128 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 256 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 256 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 256 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 256 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 256 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 256 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 256 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 256 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 512 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 512 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 512 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 512 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 512 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 512 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 512 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 512 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 1024 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 1024 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 1024 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 1024 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 1024 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 1024 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 1024 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 1024 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 2048 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 2048 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 2048 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 2048 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 2048 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 2048 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 2048 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 2048 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 4096 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 4096 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 4096 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 4096 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 4096 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 4096 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 4096 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 4096 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 8192 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 8192 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 8192 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 8192 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 8192 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 8192 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 8192 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 8192 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 16384 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 16384 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 16384 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 16384 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 16384 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 16384 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 16384 for video/mp4v-es
> I/VideoCapabilities: Unsupported profile 16384 for video/mp4v-es
> W/VideoCapabilities: Unrecognized profile/level 32768/2 for video/mp4v-es
> W/VideoCapabilities: Unsupported mime video/mpeg2
> W/VideoCapabilities: Unsupported mime video/vc1
> W/Utils: could not parse long range '1-'
> W/VideoCapabilities: Unsupported mime video/wvc1
> W/Utils: could not parse long range '1-'
> W/VideoCapabilities: Unsupported mime video/wmv3
> W/VideoCapabilities: Unsupported mime video/mjpeg
> W/AudioCapabilities: Unsupported mime audio/aac-adif
> W/AudioCapabilities: Unsupported mime audio/aac-latm
> W/AudioCapabilities: Unsupported mime audio/adts
> W/AudioCapabilities: Unsupported mime audio/adpcm-ima
> W/AudioCapabilities: Unsupported mime audio/adpcm-ms
> W/AudioCapabilities: Unsupported mime audio/alac
> W/AudioCapabilities: Unsupported mime audio/wma
> W/AudioCapabilities: Unsupported mime audio/wmapro
> W/AudioCapabilities: Unsupported mime audio/ape
> W/AudioCapabilities: Unsupported mime audio/truehd
> W/AudioCapabilities: Unsupported mime audio/ffmpeg
> W/VideoCapabilities: Unsupported mime video/x-vnd.on2.vp6
> W/VideoCapabilities: Unsupported mime video/x-vnd.on2.vp6a
> W/VideoCapabilities: Unsupported mime video/x-vnd.on2.vp6f
> W/VideoCapabilities: Unsupported mime video/rm
> W/VideoCapabilities: Unsupported mime video/wmv2
> W/AudioCapabilities: Unsupported mime audio/ac3
> W/AudioCapabilities: Unsupported mime audio/eac3
> W/AudioCapabilities: Unsupported mime audio/mpeg-L2
> W/AudioCapabilities: Unsupported mime audio/dtshd
> I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
> D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
> D/Atlas: Validating map...
> V/AdvPlayer: Listener-onPlayerStateChanged...2
> V/AdvPlayer: Listener-onTimelineChanged...
> V/AdvPlayer: Listener-onLoadingChanged...
> V/AdvPlayer: Listener-onTimelineChanged...
> I/OMXClient: Using client-side OMX mux.
> I/omx_core: OMX_Init 66 gInitCount=1
> V/AML_all_components: --------------------------------
>                       ARCH = arm
>                       author:aml.sh multi-media team
>                       branch name:   * jb-mr1-amlogic
>                       git version:   011dae5a4bcb3e3676f392664ac0bf74db6cca1b 
>                       last changed:  Date: Sun Dec 27 20:57:19 2015 +0800
>                       build-time:     Thu Jan 7 14:47:14 CST 2016
>                       build-name:     jintao.xu
>                       uncommitted-file-num:0
>                       cd /mnt/fileroot/jintao.xu/5.1.p201
>                       hostname droid07
>                       --------------------------------
> V/OmxComponentManagerImpl: loadLibrary:228 Loading OMX library libOmxVideo.so.
> E/omx_video: amvenc_avc open failed!set default instance number as 1,ret=-1,Permission denied(13)
> I/omx_core: Core library has 11 components
> E/OMXMaster: A component of name 'OMX.google.h264.decoder' already exists, ignoring this one.
> E/OMXMaster: A component of name 'OMX.google.alac.decoder' already exists, ignoring this one.
> I/SoftAAC2: limiting to stereo output
> I/SoftAAC2: Reconfiguring decoder: 0->48000 Hz, 0->2 channels
> I/OpenGLRenderer: Initialized EGL, version 1.4
> D/OpenGLRenderer: Enabling debug mode 0
> I/AudioTrack: set(): 0xab2e7a28 streamType -1, sampleRate 48000, format 0x1, channelMask 0x3, frameCount 16384, flags #0, notificationFrames 0, sessionId 0, transferType 3
> V/AdvPlayer: Listener-onPositionDiscontinuity...
> I/OMXClient: Using client-side OMX mux.
> V/AdvPlayer: Listener-onPlayerStateChanged...3
> E/ACodec: [OMX.amlogic.avc.decoder.awesome] storeMetaDataInBuffers failed w/ err -2147483648
> W/ACodec: [OMX.amlogic.avc.decoder.awesome] setting nBufferCountActual to 8 failed: -1010
> W/ACodec: [OMX.amlogic.avc.decoder.awesome] setting nBufferCountActual to 7 failed: -1010
> V/AdvPlayer: Listener-onPlayerStateChanged...2
> V/AdvPlayer: Listener-onPlayerStateChanged...3

On TV box android 5.1.

Please tell me what could be the problem?

**Comment by ojw28** [comment]
Closing because issue ignores the issue template and does not provide the information required for us to investigate the issue.
