### ISSUE TITLE
How to change ControlView layout dynamically

### ISSUE THREAD

**Issue by thesiamak** [google/ExoPlayer#2529]
I'm going to have an mp3 player with 2 states:
1- Minimized:few controls allowed here and also it's parent view height is limited .
![screenshot_1488720455](https://cloud.githubusercontent.com/assets/11936521/23587613/83e9818e-01c5-11e7-9dab-12b0faf2a614.png)

2- Fullscreen view: all controls and options allowed and can be displayed(Like exoplayers default layout).
![screenshot_1488281187](https://cloud.githubusercontent.com/assets/11936521/23587580/05b0ec94-01c5-11e7-91e1-08fe8c89acce.png)

The problem is that when a user clicked on minimized view i don't know how to change it to fullsceen view (As many of players do).
Please help.

**Comment by khacpv** [comment]
@draxdave 
I think it does not related to Exoplayer, 
Is Minimized state showing on notification bar? If so, you need to create some RemoteView by your self. Handle click event on the view by BroadcastReceiver and start your activity to go to fullscreen mode.

**Comment by ojw28** [comment]
Agreed this is a general Android UI question and hence is unrelated to ExoPlayer.

**Comment by thesiamak** [comment]
@khacpv 
I clearly understand what you mean and it's been implemented before and it's working . The Minimized state will be displayed in whole app till user clicks on minimized ExoplayerView(Now it must enlarge whole player to FullscreenView) .**The only problem is to switch between layouts while playing.** 

@ ojw28
It's not a general UI question my friend, because as i said before the implementation is done now. My problem is related to the ways that developers can use Exoplayer (Maybe!).

If you do not understand the question fine it does not mean that you have to close it.
