### ISSUE TITLE
[Q] Does ExoPlayer support Widevine WVM file container?

### ISSUE THREAD

**Issue by fpitters** [google/ExoPlayer#253]
I have made a quick test to play .wvm file with ExoPlayer, creating a new RendererBuilder with StreamingDrmSessionManager, but it doesn't run.

So, just wondering, would exoplayer plays WVM file container? Any info that I could read about this would be appreciated.

**Comment by ojw28** [comment]
It's not a use case we're supporting. We'd encourage you look at DASH/FMP4/MediaDrm instead.
-----
If you're feeling adventurous and if you really wanted to, you could probably get it working using FrameworkSampleSource, and manually removing all references to DrmSessionManager from MediaCodecTrackRenderer. It's not something we want to spend any time supporting though.

**Comment by fpitters** [comment]
@ojw28 , thank you for your answer and DASH tip.

Do you know if it's possible to manage Widevine WVM DRM with MediaDrm (Not sure if WVM format follows ISO/IEC 23001-7 spec), I'm stuck with its configuration, mainly about the pssh parameter (schemePsshData).

Trying to configure DrmManagerClient and running then MediaExtractor for the wvm raises always "E/WVMExtractor﹕ Drm manager failed to initialize." so I'm thinking those two don't talk between them. Or I'm I doing something wrong.

Sorry for keep asking, but it's very difficult to find related info.

**Comment by ojw28** [comment]
If you're using DrmManagerClient (which is correct for Classic Widevine) and MediaExtractor, then you shouldn't need a MediaDrm instance at all. Classic Widevine isn't a use case that ExoPlayer is supporting, so I can't provide much advice in the way of what's wrong. Sorry.

**Comment by blundell** [comment]
Would you still use `MediaCodec` for Classic Widevine as we are having problems where ExoPlayer will buffer our video after a classic license is obtained, but never start playing..?

**Comment by JamieAndresakis** [comment]
@blundell just curious if you were ever able to get wv classic working using the exoplayer. We noticed that using the exoplayer on some raw unencrypted content gave better video playback performance than using standard videoView. Most noticeably we saw certain artifacts and defects during playback disappeared and overall quality seemed to improve when using the exoplayer on a nexus player.

**Comment by blundell** [comment]
No we could not get classic to work, we ended up debugging at the C layer to work out what was going on (and I am no expert here) but it appears that classic works in a proprietary way with the MediaPlayer that is not compatible with ExoPlayer.

I bookmarked a lot of code in my research, it might not make total sense now but could give you some leads/insight:

[media/jni/android_media_MediaPlayer.cpp#L226-L229](https://github.com/android/platform_frameworks_base/blob/master/media/jni/android_media_MediaPlayer.cpp#L226-L229)

[media/libmediaplayerservice/MediaPlayerFactory.cpp#L63-L71](https://github.com/stevedesmond-ca/frameworks-av-spyder/blob/master/media/libmediaplayerservice/MediaPlayerFactory.cpp#L63-L71)

[media/java/android/media/MediaPlayer.java#L1061-L1065](https://github.com/android/platform_frameworks_base/blob/master/media/java/android/media/MediaPlayer.java#L1061-L1065)

[4.4.4 r1 media/libstagefright/include/WVMExtractor.h](http://androidxref.com/4.4.4_r1/xref/frameworks/av/media/libstagefright/include/WVMExtractor.h)

[media/libwvm/WVMExtractorImpl.cpp](https://android.googlesource.com/platform/frameworks/base/+/6681984cf6aaae5f26cf6b82c7bb9f1c50d7ecd7/media/libwvm/WVMExtractorImpl.cpp)

[5.0.0 r2 media/libmedia/ICrypto.cpp#requiresSecureDecoderComponent](http://androidxref.com/5.0.0_r2/xref/frameworks/av/media/libmedia/ICrypto.cpp#requiresSecureDecoderComponent)

[4.4.4_r1 media/libstagefright/DRMExtractor.cpp#L142-L146](http://androidxref.com/4.4.4_r1/xref/frameworks/av/media/libstagefright/NuMediaExtractor.cpp
https://github.com/android/platform_frameworks_base/blob/ics-mr1-release/media/libstagefright/DRMExtractor.cpp#L142-L146)

[ICS mr1 media/libstagefright/AwesomePlayer.cpp#L338-L344](https://github.com/android/platform_frameworks_base/blob/ics-mr1-release/media/libstagefright/AwesomePlayer.cpp#L338-L344)

____

[Android builders summit - The Android media framework pdf](http://events.linuxfoundation.org/sites/events/files/slides/Android%20builders%20summit%20-%20The%20Android%20media%20framework%20-%20final.pdf)

[androids stagefright media player architecture blog](https://quandarypeak.com/2013/08/androids-stagefright-media-player-architecture/)
