### ISSUE TITLE
Is is possible to give non overlapping KID's for widevine dash streams?

### ISSUE THREAD

**Issue by peak3d** [google/ExoPlayer#2530]
Hi,

for widewine / chrome (not android) its impossible to decrypt data with different session-id's but same KID's.

The widevine request for both Video and Audio returns the same set of KID's:
fist: 30303030303030303030303030303030
last: 30303030303030303030303030303037

Would it be possible to give Video / Audio a set of non overlappink KID's?

For example:
Audio:
fist: 30303030303030303030303030303030
last: 30303030303030303030303030303037

Video:
fist: 30303030303030303030303030303**1**30
last: 30303030303030303030303030303**1**37

Thanks!

Markus

**Comment by ojw28** [comment]
@wvpaf - I'm not sure I understand this question. Do you?

**Comment by peak3d** [comment]
@ojw28 we can close this issue, In the meantime I solved my issues / questions using other test media.
Thanks nevertheless for this great work (exo-player)
