### ISSUE TITLE
Disable Forward playback and Seek forward

### ISSUE THREAD

**Issue by shaikansaar** [google/ExoPlayer#2531]
Hi,

I just incorporated ExoPlayer v2.2.0 in my App and really love it. However, i have a requirement which i could not find in documentation. Forgive me if i am posting a stupid question as i am new to Android.

How can i disable the forward playback  and seek forward for a video (mp4) played on (http)?\
Also, i need to disable the player  Forward  button >>.

Any help will be appreciated.

Thanks

**Comment by ojw28** [comment]
You can create your own playback control UI that just doesn't have a forward button, or has a dummy one that's disabled. Some information about customizing the playback controls can be found [here](https://medium.com/google-exoplayer/customizing-exoplayers-ui-components-728cf55ee07a).
