### ISSUE TITLE
Video shows green stripes on Android TV

### ISSUE THREAD

**Issue by fasteque** [google/ExoPlayer#2541]
### Issue description
Some videos present green stripe (bottom-horizontal for landscape, left-vertical for portrait).

### Reproduction steps
Using the ExoPlayer demo app, just add a new entry with the video URL and play it (to reproduce it I've added it in the Misc section).
Green stripe is immediately noticeable.

### Link to test content
Test content provided by email.

### Version of ExoPlayer being used
r2.2.0: built demo application using the `release-v2` branch, commit aaaa23e5e4a6771b06067bd28d728781990bd454.

### Device(s) and version(s) of Android being used
The device is an Android TV box running Android 4.4.2 (more details provided by email along with test content and logs).
On Nvidia Shield TV (Android 7.0) the issue not reproducible.

### A full bug report captured from the device
Bug report provided by email.

**Comment by ojw28** [comment]
You'll need to report this issue to the device manufacturer. I don't think it's an ExoPlayer issue. It's almost certainly an issue with the AVC decoder on this device, or something in the graphics pipeline.
