### ISSUE TITLE
Question regarding displaying subtitles from using HLS format Video 

### ISSUE THREAD

**Issue by jazimm** [google/ExoPlayer#2546]
### Issue description
Not able to display subtitles in vvt file using HLS stream on 2+. Not able to see an example in the demo app and not sure if additional code is necessary outside of implementing HlsMediaSource as shown in demo.

### Reproduction steps
Currently testing with https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8 on demo app. Video plays but captions not displayed. Need updated example code or demo app displaying steps to implement captions if not automatically generated by using HlsMediaSource.

### Link to test content
https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8
https://bitdash-a.akamaihd.net/content/sintel/hls/subtitles_en.m3u8
https://bitdash-a.akamaihd.net/content/sintel/hls/subtitles_en.vtt

### Version of ExoPlayer being used
2.2

### Device(s) and version(s) of Android being used
Nexus 5 Running 6.0.1 
Nexus 6P running 7.1.1

### A full bug report captured from the device
No errors, just not displaying captions

**Comment by AquilesCanta** [comment]
On version 2.2, https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8 plays well, including subtitles. For the DemoApp, english subtitles should be enabled by default (you can make sure through the Text button at the top of the screen). Note that the first subtitles in the stream appear at 2:15, so you should seek if you don't want to wait 2 minutes.

**Comment by ojw28** [comment]
Appears to work correctly.
