### ISSUE TITLE
How to set mp3 player default thumbnail image?

### ISSUE THREAD

**Issue by jeffreyrajanofficial** [google/ExoPlayer#2549]
Is there any way to set default metadata thumbnail image for mp3 type file. I am using exoplayer current version(r2.2.0).

**Comment by ojw28** [comment]
Does [`SimpleExoPlayerView.setDefaultArtwork`](https://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/ui/SimpleExoPlayerView.html#setDefaultArtwork-android.graphics.Bitmap-) do what you want? Your question is quite vague.

**Comment by jeffreyrajanofficial** [comment]
@ojw28 This is exactly what i am looking for, sorry about the unclear description.

**Comment by ojw28** [comment]
Great; glad that helped!
