### ISSUE TITLE
Mi Box Android TV pass-through issues

### ISSUE THREAD

**Issue by mcd2000** [google/ExoPlayer#2550]
Mi Box does not pass-through correctly anything except Dolby Digital sound.
I've tried Dolby Digital Plus, DTS and DTS-HD MA samples. All of them play fine with Demo app on Nvidia Shield Android TV.
On the Mi Box there are video/audio sync issues. Video and time counter goes forward very fast to the end of the file while playing sound just fine.
I understand that this issue is device-specific as other devices work fine. From the other size, Kodi app can pass-through anything just fine on Mi Box, so there should be some workaround.

### Reproduction steps
Add the test file to the ExoPlayer Demo app's playlist and try to play with DTS-compatible receiver connected.

### Link to test content
https://drive.google.com/open?id=0B0xXv8gGqOpmdUdaYktobmxrWWM

### Version of ExoPlayer being used
r1.2.15, r.2.2.0

### Device(s) and version(s) of Android being used
Xiaomi Mi Box Android TV (MDZ-16-AB) (once)
Android 6.0.1

[adb-bugreport.txt](https://github.com/google/ExoPlayer/files/838681/adb-bugreport.txt)

**Comment by ojw28** [comment]
Please attach a bug report as specified in the issue template. There's more than one variant of Mi Box. We need to know exactly which one and exactly what build of Android it's running (which is the kind of information that a bug report includes).

**Comment by Angels-group** [comment]
I join the problem.
MiBOX MINI (Android 4.4) does not work correctly with ExoPlayer.
When using ExoPlayer (the last stable release), there is a dissynchronization of audio and video (video/audio sync issues).

When using native MediaPlayer, there is no problem.

**Comment by mcd2000** [comment]
Sorry, I've updated the ticket.
I must say, there is current only one Mi Box Android TV (certified by Google). So, I did not think, that the lack of this info could be an issue...
I can provide adb bugreport a little later.

**Comment by mcd2000** [comment]
@Angels-group Are sure that your issue is related with this one? I currently mention pass-through of multichannel audio only.

**Comment by ojw28** [comment]
@mcd2000 - We ask for the information in the issue template for a reason. There are, for example four different builds of Android 6.0.1 for the device you're using. The information you've provided is not sufficient for us to determine which build you're using. Please provide a full bug report as requested.

**Comment by mcd2000** [comment]
adb bugreport attached.

**Comment by tmc85** [comment]
Is there some information on this issue?

**Comment by andrewlewis** [comment]
I'm following up internally and will update this issue if/when I hear anything back.

**Comment by andrewlewis** [comment]
@mcd2000 Is this still reproducible with the latest system update for the device? There has unfortunately not been any activity on the internal bug [reference: b/36680230]. I can ask for an update again but it would be good to know that this is still broken first. Thanks in advance.

**Comment by mcd2000** [comment]
Need some time to re-check this on latest firmwares.

**Comment by mcd2000** [comment]
I've tested on the latest beta pre-view of Android 7 firmware.
Looks like this issue was resolved by Xiaomi.

**Comment by andrewlewis** [comment]
Sounds like this has been fixed by a system update. It's unlikely we will work around the issue on older versions, so I will close this for now. Please reopen or file a new issue if there are remaining problems.
