### ISSUE TITLE
FfmpegAudioRenderer fails to correctly handle channel layout changes in MPEG-TS streams

### ISSUE THREAD

**Issue by kiall** [google/ExoPlayer#2552]
Possibly related to / a regression of https://github.com/google/ExoPlayer/issues/2111

### Issue description

When FfmpegAudioRenderer is used for decoding an AC3 audio track, and that track's channel layout changes abruptly (as is common on MPEG-TS streams during commercial breaks etc), audio and video begins to stutter.

It's possible this isn't AC3 specific, but I don't have any other samples available to verify.

### Reproduction steps

* Add provided sample into the demo player media.exolist.json, example:

        {
          "name": "AC3 Audio Layout Change (TS)",
          "uri": "http://10.5.1.21/ac3-channel-layout-change.ts"
        },

* Build the demo app, with the ffmpeg extension enabled.
* Play the sample, wait for approx 1:01 and observe stuttering.

### Link to test content

https://www.dropbox.com/s/0uvzypw9ckusnqr/ac3-channel-layout-change.ts?dl=0

### Version of ExoPlayer being used

* ExoPlayer r2.2.0
* FFmpeg git sha 6c7a0876fefdd3c919afcabf493492cb4946ca6a

### Device(s) and version(s) of Android being used

Reproduces on:

* Android TV Emulator - v7.1.1
* nVidia Shield - Android 7.0, Shield SW 5.1 (24.28.403.124)

### A full bug report captured from the device

https://www.dropbox.com/s/py4bpiqds4pbb3g/bugreport-NYC-2017-03-12-22-55-21.zip?dl=0

**Comment by kiall** [comment]
It's also worth noting that if the audio is allowed to passthrough to the TV attached to the shield for decoding (and downmixing to 2 channel), the sample plays back fine.

**Comment by kiall** [comment]
FYI - I'll be travelling, and away from any Android TV dev stuff starting Friday for 2 weeks - any responses   needed will be slow, apologies.

Let me know if you need anything and I'll do my best!

**Comment by kiall** [comment]
Hey guys, anything you need from me to confirm this issue etc? Thanks!

**Comment by AquilesCanta** [comment]
Sorry for the delay on this. I think I know what the issue might be. I'll run some tests and update this issue.

**Comment by kiall** [comment]
Awesome, thanks @AquilesCanta :)

**Comment by AquilesCanta** [comment]
A fix will be available in the next push.

**Comment by ojw28** [comment]
Fixed in `dev-v2`. Please give it a try!

**Comment by kiall** [comment]
And, validated it works nicely! Thanks :)
