### ISSUE TITLE
java.util.NoSuchElementException

### ISSUE THREAD

**Issue by ChernyshovYuriy** [google/ExoPlayer#2554]
While investigating issue with live playback, I found that ExoPlayer v 2.2.0 fails with next exception:

```
03-10 10:40:17.770  6250  9327 E ExoPlayerImplInternal: Internal runtime error.
03-10 10:40:17.770  6250  9327 E ExoPlayerImplInternal: java.util.NoSuchElementException
03-10 10:40:17.770  6250  9327 E ExoPlayerImplInternal: 	at java.util.LinkedList.getLast(LinkedList.java:553)
03-10 10:40:17.770  6250  9327 E ExoPlayerImplInternal: 	at com.quickplay.google.android.exoplayer.source.chunk.ChunkSampleStream.getNextLoadPositionUs(:341)
03-10 10:40:17.770  6250  9327 E ExoPlayerImplInternal: 	at com.quickplay.google.android.exoplayer.source.CompositeSequenceableLoader.getNextLoadPositionUs(:35)
03-10 10:40:17.770  6250  9327 E ExoPlayerImplInternal: 	at com.quickplay.google.android.exoplayer.source.dash.DashMediaPeriod.getNextLoadPositionUs(:179)
03-10 10:40:17.770  6250  9327 E ExoPlayerImplInternal: 	at com.quickplay.google.android.exoplayer.ExoPlayerImplInternal.maybeContinueLoading(:1289)
03-10 10:40:17.770  6250  9327 E ExoPlayerImplInternal: 	at com.quickplay.google.android.exoplayer.ExoPlayerImplInternal.handlePeriodPrepared(:1276)
03-10 10:40:17.770  6250  9327 E ExoPlayerImplInternal: 	at com.quickplay.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(:316)
03-10 10:40:17.770  6250  9327 E ExoPlayerImplInternal: 	at android.os.Handler.dispatchMessage(Handler.java:98)
03-10 10:40:17.770  6250  9327 E ExoPlayerImplInternal: 	at android.os.Looper.loop(Looper.java:158)
03-10 10:40:17.770  6250  9327 E ExoPlayerImplInternal: 	at android.os.HandlerThread.run(HandlerThread.java:61)
03-10 10:40:17.770  6250  9327 E ExoPlayerImplInternal: 	at com.quickplay.google.android.exoplayer.util.PriorityHandlerThread.run(:40)
```

It is DASH / Widevine protected content.
Unfortunately, I can not provide manifest url to test. It could be consequence of the malformed manifest as well. However, when I looked into the ExoPlayer code, I decided to rise a ticket because even though ExoPlayer should not fail at the specified place.

**Comment by ChernyshovYuriy** [comment]
Small update.
We found that there was stale manifest provided, could be a reason, because playback was triggered in "frozen" state, like infinite pause.
Anywhere, I think it was a good stress test :-)
Don't know if you have any idea how to protect failed code from NoSuchElementException.

**Comment by ChernyshovYuriy** [comment]
Btw, is the a way to detect stale manifest and throw appropriate exception?

**Comment by ojw28** [comment]
It's quite difficult in general to detect stale manifest cases. It's also quite unclear to me how this particularly stack trace results from there being one.

The above aside, the player does not crash in this case. It fails gracefully, which is working as intended given the manifest was incorrect. I don't think we're inclined to spend any effort on throwing a more accurate exception for this case.
