### ISSUE TITLE
pixelated screen appears while activity onresume is called after on pause

### ISSUE THREAD

**Issue by gajendrakumartwinwal** [google/ExoPlayer#2558]
I have used Exoplayer in SurfaceView. I am facing serious issue while exoplayer surfaceview removed and added to another viewgroup it shows pixelated screen for 2-3 seconds same is appearing while player is playing and i press the home button and when i come back to same activity it shows pixelated screen for 2-3 seconds.
PFA screenshot of the surfaceview as well.
![before](https://cloud.githubusercontent.com/assets/9496478/23938255/84bf319e-0981-11e7-8205-a824c6e1f018.png)
![after](https://cloud.githubusercontent.com/assets/9496478/23938258/8b74f636-0981-11e7-8cb0-7c08831c6fc4.png)

**Comment by ojw28** [comment]
There is insufficient information here for us to help. Please provide all of the information requested in the issue template, including clear reproduction steps and a full bug report.

The issue you describe probably falls under being able to smoothly switch/detach/re-attach a surface, which is discussed in and tracked by https://github.com/google/ExoPlayer/issues/677.
