### ISSUE TITLE
HLS Adaptive track not change quality on Android TV although  callback onVideoFormatEnabled called

### ISSUE THREAD

**Issue by Null45** [google/ExoPlayer#2567]
# Issue Description
Using exoplayer v1 (r1.5.14) with android tv. On both android TV devices () adaptive track doesn't change video image quality. The same app with the same stream's on my Nexus 5x working as intended. Used demo-app like exoplayer configuration.

# Reproduction steps
Run HLS Stream url: https://bitdash-a.akamaihd.net/content/MI201109210084_1/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8 on android tv with default adaptive track (0).

**Version of ExoPlayer being used**
r1.5.14

# Device(s) and version(s) of Android being used
Test Devices:
Sony 
Model: BRAVIA 2015 KDL-43W756C
OS Version: AndroidTV 5.1.1
BUILD: SVPDTV15_EU-user 5.1.1 LMY48E.S265 3.533 release-keys

Phillips
Model: 40PUT6400/60
OS Version: AndroidTV 5.1.1

# Test URL
HLS Stream url: https://bitdash-a.akamaihd.net/content/MI201109210084_1/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8

**Comment by Null45** [comment]
any updates? idk how to fix this

**Comment by AquilesCanta** [comment]
I haven't managed to reproduce in SONY BRAVIA 2015 or SONY BRAVIA 4K. Adaptation works well there.

But please have a look at #1411 and #953.
