### ISSUE TITLE
[Discussion] Potential race between HlsSampleSource and TsChunk?

### ISSUE THREAD

**Issue by mine260309** [google/ExoPlayer#257]
This is not an issue, just some discussion about potential TsExtractor's race between HlsSampleSource and TsChunk.

When I read the code related to how HlsSampleSource read the chunk data, it's noticed that reading-data from DataSource and getting-sample from Extractor are in two threads:

* Reading data is in `TsChunk.load()`, which runs in a backgroud thread:
```java
      while (bytesRead != -1 && !loadCanceled) {
        bytesRead = extractor.read(dataSource);
        if (bytesRead != -1) {
          loadPosition += bytesRead;
        }
      }
```
* Getting sample is in `HlsSampleSource.readData()`, which runs in ExoPlayer's event loop. And other functions access the extractor, e.g. 
```java
    extractor.getSample(track, sampleHolder)
    extractor.discardUntil(i, timeUs);
```
I don't see any protection of the two threads accessing extractor;
Although there is `ConcurrentLinkedQueue` to protect the `SampleQueue.internalQueue` in TsExtractor, other members are not protected.

The question is, can we make sure there is no race accessing TsExtractor?

**Comment by ojw28** [comment]
Can you be specific about which members you're concerned about? The members that are accessed from both threads are marked as volatile, SamplePool is protected with synchronization, and as you say the sample queues use ConcurrentLinkedQueue. I can't see anything not covered by these measures.

Thanks!

**Comment by mine260309** [comment]
Thanks for your comment!
It did not notice SamplePool is protected with synchronization.

The reason I asked the question is because I was planning to add a member in SampleQueue and realized that it should be protected by mutex or synchronization.
Now it's clear and I'll close the question.
