### ISSUE TITLE
ExoPlayer Can't Play a particular HLS Transport Stream

### ISSUE THREAD

**Issue by shalin186** [google/ExoPlayer#2571]
I am not able to play a particular hls transport stream using exoplayer, while most of my other streams work just fine. 
I am sending out stream details in the email.

I have tried it on Galaxy S6 and S7 with android 6.0.1. 

Would appreciate any help regarding this.

**Comment by shalin186** [comment]
Forgot to mention that the same stream plays without any issues using android native player.
Here I am attaching the output logs.
One of the errors I see from the log is:
**E/EXYNOS_H264_DEC: Failed to set buffer process type(not supported)**
[error_logs_3.txt](https://github.com/google/ExoPlayer/files/859356/error_logs_3.txt)

**Comment by AquilesCanta** [comment]
Please see #1263.

With the FLAG_DETECT_ACCESS_UNITS, It will play well on Galaxy S6, at least. I didn't manage to play the sample on Sony Bravia 4k. But that is a different issue.
