### ISSUE TITLE
Error playing a HLS video, wrong stream?

### ISSUE THREAD

**Issue by maruiz81** [google/ExoPlayer#2572]
Hi everybody, I am using the Exoplayer version 2.2.0 to play HLS video. Please note that I have two stream providers, one of them is ok but another provider some times is ok some times not. The error that I have in Exoplayer is this.

```
E/ExoPlayerImplInternal: Internal runtime error.java.lang.ArrayIndexOutOfBoundsException: length=2; index=2
    at com.google.android.exoplayer2.source.hls.HlsSampleStreamWrapper.selectTracks(HlsSampleStreamWrapper.java:205)
    at com.google.android.exoplayer2.source.hls.HlsMediaPeriod.selectTracks(HlsMediaPeriod.java:142)
    at com.google.android.exoplayer2.ExoPlayerImplInternal$MediaPeriodHolder.updatePeriodTrackSelection(ExoPlayerImplInternal.java:1491)
    at com.google.android.exoplayer2.ExoPlayerImplInternal$MediaPeriodHolder.updatePeriodTrackSelection(ExoPlayerImplInternal.java:1478)
    at com.google.android.exoplayer2.ExoPlayerImplInternal$MediaPeriodHolder.handlePrepared(ExoPlayerImplInternal.java:1464)
    at com.google.android.exoplayer2.ExoPlayerImplInternal.handlePeriodPrepared(ExoPlayerImplInternal.java:1269)
    at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:316)
    at android.os.Handler.dispatchMessage(Handler.java:98)
    at android.os.Looper.loop(Looper.java:224)
    at android.os.HandlerThread.run(HandlerThread.java:61)
    at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
```

I think probably this is the same error that this [issue 2234](https://github.com/google/ExoPlayer/issues/2234) that was closed like bad stream. My problem here is the provider can't find the issue. I have to say that the same streams are working properly in IOS. I have used a proxy to get information about the stream (unfortunately the m3u8 URL have expiration and I can't share or save it for further test and probably I can't share because is under copyright). With the proxy I capture some streams that have worked good and other that have failed. I would like to have a tool to analyse the .ts or maybe some clue about I have to find. Any help will be appreciated. Thanks in advance!

**Comment by AquilesCanta** [comment]
The issue here might be that there is a change in the number of tracks included in the transport streams. To analyze ts files `mediainfo` and `dvbsnoop` are useful. With these you can check the number and type of tracks included in the underlying ts files. Using a debugger and adding breakpoints to ExoPlayer is also a good way, but might take longer to do efficiently.

If you need to concatenate different HLS streams, instead of putting them in the same playlist, it might be an option to use a `ConcatenatingMediaSource`. The ts themselves might be well formed, but a change in the number of tracks (for example, audio or video appearing/disappearing) can cause this, if they belong in the same playlist. We won't be able to investigate the issue without the media, unfortunately.

**Comment by maruiz81** [comment]
I have permission to share a .ts that failed for me. I only have this .ts in this attempt so I think Exoplayer crashed with this ArrayIndexOutOfBoundsException while was decoding this .ts. I analysed this with Media Info but I can't find something wrong, maybe you can find something. Many thanks.
[170320_ZAFA_1020_DmrBcV_350_hdsNum10160.ts.zip](https://github.com/google/ExoPlayer/files/855440/170320_ZAFA_1020_DmrBcV_350_hdsNum10160.ts.zip)

**Comment by AquilesCanta** [comment]
The provided .ts contains two PMTs, and the first one only declares audio. This would make ExoPlayer fail only when there is a discontinuity tag for this segment or when adaptation happens when playing a chunk with similar characteristics, I think. Removing the first PMT from the stream should make it work.

**Comment by maruiz81** [comment]
Hi again

Some more information about the problem. 

The provider is always the same. 
The player, when it fails with ArrayIndexOutOfBounds, it will be when it processes the first ts file (as far as we could see). 
There is one case below (example 1 and example 2), which is the same live stream and the player failed the first time we tried to connect but succeeded the next we tried to connect (and we could play the stream until we stopped it).


In this case (example 0) of failure, the proxy dump shows that Exoplayer is:
1.	Retrieving the m3u8 (you can find it attached)
2.	Retrieving the 3rd file in the m3u8: 170320_ZAFA_1020_DmrBcV_hds/170320_ZAFA_1020_DmrBcV_350_hdsNum10160.ts
3.	Throws an ArrayIndexOutOfBounds while process this file
And this is the end of the HTTP conversation. In this case, there is no discontinuity tag or adaptation taking place - correct?
[Example0.zip](https://github.com/google/ExoPlayer/files/858186/Example0.zip)

I also looked at other streams; I am uploading two more examples which are from the same live stream.
Example 1:
1.	Retrieving the m3u8 (you can find it attached)
2.	Retrieving the 3rd file in the m3u8: 170317_ZAGV_1620_bJj1KA_hds/170317_ZAGV_1620_bJj1KA_350_hdsNum20963.ts
3.	Throws an ArrayIndexOutOfBounds while process this file
[Example1.zip](https://github.com/google/ExoPlayer/files/858192/Example1.zip)

Example 2: (this is another part of the same stream as example 1, but a few minutes later)
1.	Retrieving the m3u8 (you can find it attached)
2.	The player has already retrieved _ZAGV_1620_bJj1KA_hds/170317_ZAGV_1620_bJj1KA_350_hdsNum20989.ts,  _ZAGV_1620_bJj1KA_hds/170317_ZAGV_1620_bJj1KA_350_hdsNum20990.ts and _ZAGV_1620_bJj1KA_hds/170317_ZAGV_1620_bJj1KA_350_hdsNum20991.ts
3.	Retrieves the missing files in this m3u8: _ZAGV_1620_bJj1KA_hds/170317_ZAGV_1620_bJj1KA_350_hdsNum20992.ts and 170317_ZAGV_1620_bJj1KA_hds/170317_ZAGV_1620_bJj1KA_350_hdsNum20993.ts
4.	Continues to request m3u8 for updates
[Example2.zip](https://github.com/google/ExoPlayer/files/858194/Example2.zip)

Finally, as far as we can understand the mediainfo dump, the ts. files we have attached all have 2 PMTs (first with audio and second with audio/video). For instance, when looking at the TS_program_map_section of _ZAGV_1620_bJj1KA_hds/170317_ZAGV_1620_bJj1KA_350_hdsNum20989.ts (first .ts in the success case)  and _ZAGV_1620_bJj1KA_hds/170317_ZAGV_1620_bJj1KA_350_hdsNum20992.ts both have 2 PMTs as in the files with the failure case.

thank you for your help

**Comment by AquilesCanta** [comment]
As mentioned before, please try reproducing the issue after removing the PMT that only declares audio. If you manage to reproduce the issue in that case, comment again below, including all the information requested in the issue template.

**Comment by oukb** [comment]
Hi
I have the same problem with old and new ams.

First file from old ams
./bcdb52266de34f1e8aa5474d17b0850c_portal_MQ.mp4Frag1Num0work.ts
It's ok 

```
	** Frames **
	Track #0 - Frames:  I P P P P P P P P P P P P P P P P P P P P P P P P P P P P P 	AA: 0, BB: 0

		Good! Track starts with a keyframe
		Keyframes count: 4
		Key frame interval within track: 2.0 seconds

	Track #1 - Frames:  I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I
```


Second file from new ams - didn't work.
./bcdb52266de34f1e8aa5474d17b0850c_portal_MQ.mp4Frag1Num0dontwork.ts

```
	** Frames **
	Track #0 - Frames:  P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P 	AA: 0, BB: 0

		Warning: note this is not starting with a keyframe. This will cause not seamless bitrate switching
		Keyframes count: 3
		Key frame interval within track: 2.0 seconds

	Track #1 - Frames:  I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I

```


[chunks.zip](https://github.com/google/ExoPlayer/files/1125302/chunks.zip)

**Comment by ojw28** [comment]
(deleting cross-post)
