### ISSUE TITLE
"Repeat" toggle function (Repeat All/Repeat One) on playlist

### ISSUE THREAD

**Issue by liauli** [google/ExoPlayer#2577]
I have list of videos played using ExoPlayer and I want to add Repeat button. I am using ConcatenatingMediaSource so far and I don't know how to handle if the user changed the toggle to "Repeat One" or changing it back to "Repeat All"
Thanks

**Comment by AquilesCanta** [comment]
You can try using a `LoopingMediaSource` on top of the `ConcatenatingMediaSource` to achieve repetition. Depending on whether it's repeat all or one, you use or don't use the `ConcatenatingMediaSource`.

**Comment by liauli** [comment]
Thank you for your response.
As far as I know, once we set the MediaSource, we couldn't change it in the middle of playback ?
I was thinking about checking the Repeat toggle before starting the next video so I can decide should the player repeat the last video or go to next video from the list, but I still couldn't find how to do that.

**Comment by ojw28** [comment]
I'm sure there are ways to implement this along the lines of what you suggest, but to do it really seamlessly (and simply) we'd probably need to add some direct support. Marking as an enhancement.

**Comment by ojw28** [comment]
Setting the repeat mode is now supported in the dev-v2 branch (`ExoPlayer.setRepeatMode`). You can also enable a toggle on `SimpleExoPlayerView` (`SimpleExoPlayerView.setRepeatToggleModes`). Please give it a try!
