### ISSUE TITLE
ExoPlayer Demo app stuck at buffering when playing MPEG-4 network stream

### ISSUE THREAD

**Issue by naceto** [google/ExoPlayer#2581]
### Issue description
Trying to play a HD MPEG-4 network stream with the demo app, player is stuck at buffering state. When I downloaded part of the stream and added the file to the assets folder of the demo app, there is only audio playing.

### Reproduction steps
By adding the linked file to the demo app's assets folder and adding it to media.exolist.json.

### Link to test content
Test steam:
https://drive.google.com/file/d/0B3T5QyE45HZ9S3VmU0phVHA0dk0/view?usp=sharing

### Version of ExoPlayer being used
Tryed it on both the release-v2 branch and dev-v2 branch. Version in build.gradle shows releaseVersion = 'r2.3.0' (in the dev-v2 branch)

### Device(s) and version(s) of Android being used
Tested on OnePlus One (6.0.1) and Sony KD43XD8088 Android TV (6.0.1)

**Comment by AquilesCanta** [comment]
See #1894 and similar issues (there are plenty). It works if you enable FLAG_ALLOW_NON_IDR_KEYFRAMES.
