### ISSUE TITLE
MediaCodecVideoRenderer without Surface never ends

### ISSUE THREAD

**Issue by ghost** [google/ExoPlayer#2582]
### Issue description
When instantiating a MediaCodecVideoRenderer and never call `setSurface` (or set it to `null`) the render will never return `true` for `isEnded`. This will cause the player to play the video forever (after the audio track finishes the player will switch to the stand alone clock and keeps playing)

### Reproduction steps
Create MediaCodecVideoRenderer and a MediaCodecAudioRenderer use them in a ExoPlayer and never call `setSurface`

### Link to test content
http://html5demos.com/assets/dizzy.mp4

### Version of ExoPlayer being used
v2.3.0

### Device(s) and version(s) of Android being used
Nexus 5X emulator, Pixel XL, OnePlus 2

### A full bug report captured from the device
N/A

**Comment by rustyshelf** [comment]
We have this same issue, I thought I'd comment because for us this happens when the user leaves our app, we remove the video from the surface it was playing on but we still keep playing in the background. Is there a recommended way to handle switching from rendering the video to just playing the audio seamlessly @ojw28?

**Comment by ghost** [comment]
@ojw28 mentioned one workaround in the issue referenced above (#2575), which is that you can enable or disable the renderer 

We implemented a solution where we extend the `MediaCodecVideoRenderer` and overwrite `handleMessage` to check for `C.MSG_SET_SURFACE`. When that messages is received we updated an internal `enabled` state which we use in `isEnded` 

```
public boolean isEnded() {
  return !enabled || super.isEnded();
}
```

That solution is rather hacky and we have not tested all edge cases, but it works for our video files.

**Comment by ojw28** [comment]
If you have demuxed audio and video then disabling the renderer is actually the right thing to do. We'll stop requesting the video stream in that case, so there will be a big bandwidth saving. We'll seamlessly rejoin the stream when the renderer is enabled again.

If your audio and video are demuxed then you can do the above, but the rejoin wont be seamless. The right thing for seamless is to detach the surface as you are doing, and for us to fix this bug.

**Comment by ojw28** [comment]
There are actually a bunch of things slightly wrong with surface attach/detach whilst the renderer is enabled. We'll use this issue to track these problems in general.

**Comment by ojw28** [comment]
We still have some further changes to come around making surface switches more seamless, but the initial issue as reported here should now be fixed.

**Comment by rustyshelf** [comment]
Thanks so much, we've been waiting for this and another issue to be fixed and both have. Wow! Of course we're demanding users so now we want to know when it will appear in a release ;) (sorry)
