### ISSUE TITLE
MediaDrm.EVENT_KEY_EXPIRED  event happens for Widevine DRM content

### ISSUE THREAD

**Issue by richardissuperman** [google/ExoPlayer#2584]
**Issue description**

We keep receiving MediaDrm.EVENT_KEY_EXPIRED event in StreamingSessionManager.java, line 451,  after onKeyResponse() called, which stops the codec from decoding.

Is there any pattern and reason why this event will be fired from MediaDrm object?

Thanks

**Comment by ojw28** [comment]
It means what it says (the keys have expired). What license and renewal durations are your licenses configured to use?

**Comment by richardissuperman** [comment]
Hi @ojw28 i just confirmed with our content provider, they set the license key expiration to 7 sec.... sorry for the spammer you can just close this issue .thanks
