### ISSUE TITLE
Can not seek and playback 

### ISSUE THREAD

**Issue by crossle** [google/ExoPlayer#259]
[Test stream](https://dn-hls-233-tv-cn-bj-01.qbox.me/54b85dc2695a32406e060000/54bd0d30695a322e43030000/source/index.m3u8) can not playback after 20:45's. BTW, can not seek after 20:45's

Log
```
Spurious audio timestamp (system clock mismatch): 7488223, 10332951181, 10338014549, 169853968
```

**Comment by ojw28** [comment]
Your stream doesn't work in Safari or VLC either. For me at least. ExoPlayer actually does better than either of them (Safari goes into an infinite loop after 15 seconds of playback, and seeking doesn't work at all, where-as VLC draws lots of corrupt video frames).

I think the stream is probably invalid. Please re-open if you're relatively sure that's not the case.

**Comment by crossle** [comment]
But ffplay work well, if you visit the link, the video in china.

**Comment by ojw28** [comment]
Apple define the HLS spec. So if it doesn't play in Apple's own players, then I don't think it can be called valid.
