### ISSUE TITLE
Detecting the DRM support before player initializing

### ISSUE THREAD

**Issue by evorotilova** [google/ExoPlayer#2591]
Hello,

Searched for similar tickets but haven't found one.
Is it possible to detect that a device doesn't support DRM playing before player initialization or playing a video? If it is do you have some plans about it? Or how can we do it by ourselves?

Thanks!

**Comment by richardissuperman** [comment]
different DRM has a unique UUID schema, you do something like what exoplayer does, use the uuid to init a MediaDrm object, if its not supported exceptions will be thrown
```
public static FrameworkMediaDrm newInstance(UUID uuid) throws UnsupportedDrmException {
    try {
      return new FrameworkMediaDrm(uuid);
    } catch (UnsupportedSchemeException e) {
      throw new UnsupportedDrmException(UnsupportedDrmException.REASON_UNSUPPORTED_SCHEME, e);
    } catch (Exception e) {
      throw new UnsupportedDrmException(UnsupportedDrmException.REASON_INSTANTIATION_ERROR, e);
    }
  }
```
