### ISSUE TITLE
How to Encrypt and Decrypt Widevine DRM Video stream in Android Exoplayer

### ISSUE THREAD

**Issue by senthilxperio** [google/ExoPlayer#2601]
Hi All,

We have downloaded Sample Exo-Player from git-hub
[https://github.com/google/ExoPlayer]

As mentioned in your previous mail we have checked StreamingDrmSessionManager.jav, MediaDrm, httpMediaDrmCallback. In all these methods the below URL, provider getting passed correctly. But video is not playing, only length is getting displayed.

media.exolist.json in the asset folder we have made the below changes. We have doubt whether we are passing the drm license URL is passed correctly. Please check and let us know is the this correct way to send drm license URL as clear stream is playing correctly.

{
"name": "segmented-unencrypted",
"uri": "https://s3.amazonaws.com/sprngpod/drm/511996_06276e1bd3a6227634cb148115ddd33a/mpds/unenc/segmented/unecn_mdash.mpd",
"drm_scheme": "widevine",
"drm_license_url": "https://proxy.uat.widevine.com/proxy?video_id=154785865002&provider=xxxx"
},
{
"name": "unsegemented-unencrypted",
"uri": "https://s3.amazonaws.com/sprngpod/drm/511996_06276e1bd3a6227634cb148115ddd33a/mpds/unenc/unsegmented/unecn_unsegmentdmdash.mpd",
"drm_scheme": "widevine",
"drm_license_url": "https://proxy.uat.widevine.com/proxy?video_id=154785865002&provider=xxxx"
},
{
"name": "Segmented-encrypted",
"uri": "https://s3.amazonaws.com/sprngpod/drm/511996_06276e1bd3a6227634cb148115ddd33a/mpds/encrypted/segmented/ecn_mdash.mpd",
"drm_scheme": "widevine",
"drm_license_url": "https://proxy.uat.widevine.com/proxy?video_id=154785865002&provider=xxxx"
},
{
"name": "unsegemented-encrypted ",
"uri": "https://s3.amazonaws.com/sprngpod/drm/511996_06276e1bd3a6227634cb148115ddd33a/mpds/encrypted/segmented/ecn_mdash.mpd",
"drm_scheme": "widevine",
"drm_license_url": "https://proxy.uat.widevine.com/proxy?video_id=154785865002&provider=xxxx"
},

Thanks Again

**Comment by ojw28** [comment]
Same as https://github.com/google/ExoPlayer/issues/2579.
