### ISSUE TITLE
No video, only audio when playing DASH + Widevine secure content on ZTE e8q

### ISSUE THREAD

**Issue by jrocharodrigues** [google/ExoPlayer#2603]
### Issue description
When trying to play Secure DASH + Widevine Content only the audio plays fine but there is no video (surface stays black).
Looking at the track list i see all the tracks for video and audio are available and supported.
On other devices the content plays well, so i guess it's device specific issue.

### Reproduction steps
I can reproduce the issue on this device when playing any of the *Widevine DASH: MP4,H264* secure sample content on the demo app.

### Link to test content
I can reproduce the issue using content from the demo app

### Version of ExoPlayer being used
2.3.0

### Device(s) and version(s) of Android being used
The device is ZTE e8q+ running Android 4.4.2, customized by a telecom and re branded as MEO Tablet 2.

### A full bug report captured from the device
[bugreport.zip](https://github.com/google/ExoPlayer/files/868495/bugreport.zip)

**Comment by ojw28** [comment]
Thanks for the report! Unfortunately the bug report didn't capture the whole playback session. Could you do an additional test run where you start `adb logcat > log.txt` with the device attached, then reproduce the issue, then kill logcat. This will generate a logcat file that's guaranteed to capture the whole playback session. Thanks!

[Aside: Logcat output isn't a substitute for a full bugreport. A full bugreport is always important. In addition, logcat output captured as described above can be helpful if the logcat captured in the bugreport didn't cover a long enough period of time].

**Comment by jrocharodrigues** [comment]
Hi,
Thanks for the answer. 
Just captured the logcat as you asked. 
[log.zip](https://github.com/google/ExoPlayer/files/872165/log.zip)
If you need anything else just ask.


BRs

**Comment by jrocharodrigues** [comment]
Hi,

Did you have the chance to look at the issue again? Do you need more info or logs?

Thanks

**Comment by jrocharodrigues** [comment]
@ojw28 Friendly ping, just to check if the logs i provided are ok.

**Comment by ojw28** [comment]
I can't see anything obvious in the logs. It sounds like the device is broken, but it's only using L3 Widevine according to:

> 03-27 11:25:32.063 E/DRMLEVEZ( 5338): requiresSecureDecoder=false, securityLevel=L3, mimeType=video/avc

@wvpaf - Can you see anything? Could you ask the device manufacturer to take a look if not?

**Comment by wvpaf** [comment]
The logcat does not indicate any widevine issues/error either. Other than what @ojw28  mentioned the device is only reporting it supports non secure playback, L3, so no playback is expected.

Are you a CWIP partner? If so please reach out to your widevine contact.

**Comment by jrocharodrigues** [comment]
Hi, 
Thanks for the answer.
No, i'm not a CWIP partner so i guess there's nothing i can do...

Just one question, since you say no playback is expected (due to the device only supports L3), shouldn't the player exit or throw an exception instead of only playing audio?

**Comment by ojw28** [comment]
Whether you'd expect playback to succeed depends on how your license is configured (e.g. whether the license policy requires a secure output path, which L3 is unable to provide).

If the license requires a secure output path and the device only has L3, then I'd expect playback to fail with a `CryptoException`. If the license does not require a secure output path then I'd expect playback to succeed.

If I had to guess, I'd say the most likely scenario here is that your license does not require a secure output path, but that the device is broken in a way that's causing the black output. Given the video tracks are being selected, as evidenced in the logs you've attached, I don't think you'd ever expect black output on a correctly functioning device.
