### ISSUE TITLE
how to set playback speed on audio and video in android

### ISSUE THREAD

**Issue by ashishvirani** [google/ExoPlayer#2605]
i have creating gif maker application on android and i put video speed on video but video speed view is not working and you can save video speed then speed is save on video so, please help me to display only video speed view.

**Comment by ojw28** [comment]
It's extremely unclear what the issue is that you're describing, and we will be unable to assist without a clearer description, sorry. You may find this issue relevant: https://github.com/google/ExoPlayer/issues/26
