### ISSUE TITLE
dispatchKeyEvent not working 

### ISSUE THREAD

**Issue by youneslalami** [google/ExoPlayer#2609]
I have webview video app that run an other activity with exoplayer when the url is a stream, until here its ok but in the exoplayer activiter i cant get dispatchKeyEvent work and when i clicke on the  back key i should clicke twice and more to go back and  for mp4 and hls it show me the stream on a page web

**Comment by ojw28** [comment]
It's extremely unclear what the issue is that you're describing, and we will be unable to assist without a clearer description, sorry.

**Comment by youneslalami** [comment]
the probleme in my exoplayer app when i click on the back key to return to the main activity i should click twice on return key and for mp4,m3u8 URL when i clicke on back key it play the stream on web page

**Comment by ojw28** [comment]
This is really not a clear description of the issue. ExoPlayer has nothing to do with the webview. Neither does ExoPlayer do anything special with the back key; handling is typically up to the application, which points toward this being an issue in your application code.

**Comment by youneslalami** [comment]
My probleme is when i click to back key to finish(); i soulde clicke twice

**Comment by AquilesCanta** [comment]
+1 I have the same issue

**Comment by youneslalami** [comment]
This is my code i soulde click two time the first just restart the stream and the sconde close activity
```
@Override
    public boolean dispatchKeyEvent(KeyEvent event) {
        // Show the controls on any key event.
        playback.show();

if(event.getAction()==KeyEvent.KEYCODE_BACK){
            player.stop();
      
        player.release();
finish();

        }


 return super.dispatchKeyEvent(event) || playback.dispatchMediaKeyEvent(event);
    }
```

**Comment by youneslalami** [comment]
This is my code i shoulde click two time the first just restart the stream and the sconde close activity

@Override
    public boolean dispatchKeyEvent(KeyEvent event) {
        // Show the controls on any key event.
        playback.show();

if(event.getAction()==KeyEvent.KEYCODE_BACK){
            player.stop();
      
        player.release();
finish();

        }


 return super.dispatchKeyEvent(event) || playback.dispatchMediaKeyEvent(event);
    }
