### ISSUE TITLE
Play HLS AndroidBox not smooth

### ISSUE THREAD

**Issue by dinhhieuac** [google/ExoPlayer#261]
I'm using device MXQ Quad Core Android 4.4.2
http://www.amazon.co.uk/JUSTOP-Android-Kitkat-1080P-Graphic/dp/B00HVMKHUI
when play link HLS video play not smooth,I only hear sound.
link hsl : http://zate.je/hls2/index.m3u8

log:
01-23 17:31:32.278: E/ACodec(8415): [OMX.amlogic.avc.decoder.awesome] storeMetaDataInBuffers failed w/ err -2147483648
01-23 17:31:32.418: E/OMXMaster(8415): A component of name 'OMX.google.alac.decoder' already exists, ignoring this one.
01-23 17:31:32.448: E/OMXMaster(8415): A component of name 'OMX.google.alac.decoder' already exists, ignoring this one.
01-23 17:31:39.318: E/ACodec(8415): [OMX.amlogic.avc.decoder.awesome] storeMetaDataInBuffers failed w/ err -2147483648
01-23 17:31:53.648: E/ACodec(8415): [OMX.amlogic.avc.decoder.awesome] storeMetaDataInBuffers failed w/ err -2147483648
01-23 17:31:53.718: E/OMXMaster(8415): A component of name 'OMX.google.alac.decoder' already exists, ignoring this one.
01-23 17:31:57.818: E/ACodec(8415): [OMX.amlogic.avc.decoder.awesome] storeMetaDataInBuffers failed w/ err -2147483648
01-23 17:32:59.078: E/OMXMaster(8415): A component of name 'OMX.google.alac.decoder' already exists, ignoring this one.
01-23 17:34:22.128: E/PlayerActivity(8614): Playback failed
01-23 17:34:22.128: E/PlayerActivity(8614): java.net.MalformedURLException: Unknown protocol: ttp
01-23 17:34:22.128: E/PlayerActivity(8614): 	at java.net.URL.<init>(URL.java:182)
01-23 17:34:22.128: E/PlayerActivity(8614): 	at java.net.URL.<init>(URL.java:125)
01-23 17:34:22.128: E/PlayerActivity(8614): 	at com.google.android.exoplayer.util.ManifestFetcher$ManifestLoadable.load(ManifestFetcher.java:363)
01-23 17:34:22.128: E/PlayerActivity(8614): 	at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:206)
01-23 17:34:22.128: E/PlayerActivity(8614): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
01-23 17:34:22.128: E/PlayerActivity(8614): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
01-23 17:34:22.128: E/PlayerActivity(8614): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
01-23 17:34:22.128: E/PlayerActivity(8614): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
01-23 17:34:22.128: E/PlayerActivity(8614): 	at java.lang.Thread.run(Thread.java:841)
01-23 17:35:12.048: E/ACodec(8691): [OMX.amlogic.avc.decoder.awesome] storeMetaDataInBuffers failed w/ err -2147483648

**Comment by ojw28** [comment]
I wouldn't be surprised if the device is just broken. The decoder appears to be failing here:

01-23 17:31:57.818: E/ACodec(8415): [OMX.amlogic.avc.decoder.awesome] storeMetaDataInBuffers failed w/ err -2147483648

**Comment by ojw28** [comment]
As far as I'm aware, this device hasn't passed Android CTS, and so is not supported. Please re-open if you know otherwise.
