### ISSUE TITLE
Live set max allowed latency

### ISSUE THREAD

**Issue by aletorrado** [google/ExoPlayer#2610]
Hi, I have a HLS live streaming for a radio station, which should always be close to the live edge, even after a stall (for example, because of internet disconnections or any connectivity issue). I'm looking for something similar to the `liveMaxLatencyDurationCount` option of `hls.js`. Is this available with ExoPlayer?

Thanks

**Comment by AquilesCanta** [comment]
Not supported. But it should be fairly easy to implement. An approach I can imagine is, on each `onTimelineChanged`, compare the current playback position with `liveEdge - liveMaxLatencyDurationCount`. If less, seek to, say, `liveEdge - liveMaxLatencyDurationCount / 2`. This is just an idea, though. Having small latency might incur into many seeks, so you should evaluate what is most appropriate for your app. Hope this helps!

**Comment by duanyao** [comment]
You can also adjust playback speed instead of seek to catch up small latency.
