### ISSUE TITLE
Detect if LIVE content have video or not

### ISSUE THREAD

**Issue by zishanj** [google/ExoPlayer#2616]
I am working on a project in which I am using same url to deliver both LIVE audio and audio/video content and format is in m3u8. Is there any possibility to detect whether the stream contains video content or not, so I can show layout accordingly? 

I am using `HlsMediaSource` class.

**Comment by ojw28** [comment]
You can probably use `ExoPlayer.isCurrentWindowDynamic` for this. Please give it a try!

**Comment by ojw28** [comment]
Sorry, ignore the response above. I thought you were asking how to determine if the stream is live or not.

The ExoPlayer demo app lists the audio and video tracks (they're also logged by EventLogger). Take a look at what the demo app code does to achieve this, and it should be apparent how you can query the tracks and discover what's available.

**Comment by zishanj** [comment]
Thanks, I will give it a try and update here.

**Comment by zishanj** [comment]
I have checked the demo code and found that I have to use the `onTracksChanged` listener and check for the value of `MappingTrackSelector.MappedTrackInfo.RENDERER_SUPPORT_PLAYABLE_TRACKS`in `mappedTrackInfo.getTrackTypeRendererSupport(C.TRACK_TYPE_VIDEO)`. It works! :)
