### ISSUE TITLE
ExoPlayer integration into FireTV and Android TV app

### ISSUE THREAD

**Issue by ram992** [google/ExoPlayer#2625]
Hello Ojw, Sorry for raising this as an Issue but this was one of the cases.

The ExoPlayer and the supporting DemoApp are very excellent in making mobile and Tab integrations,
from an Average Android Developer view. 

But is there any source where I can get pointed for doing the same for Android TV.

I have tried the existing AndroidTV leanback project from github but it is using 1.5.8 version of the exo player, and I tried upgrading it to 2.2.0 but facing a lot of issues with it, I wanted this because I have written by own Track selection logic and Offline DRM session Manager for Mobile basing on the packages used in ExoPlayer 2.0.4 and it was not a big problem upgrading it to 2.2.0.
 
So can you please mention any source (other than stackOverflow cause I am already using it) or let me know if you are maintaining any document that can be helpful.

**Comment by ojw28** [comment]
I don't really understand the question. The ExoPlayer demo app should work fine on Android TV as well, so I'm not sure what the difference is vs mobile and tablet. FireTV is a bit different, depending on the version of FireOS. See [here](https://google.github.io/ExoPlayer/supported-devices.html).

**Comment by ram992** [comment]
Well to give a bit more details,  the demo app is working fine, the thing that I don't get is 
the LeanBack androidTV app uses a different Structure than the exoplayer Demo app,

Like it has a separate class for ExtractorRendererBuilder (why ? when exoplayer is supplying it and what is the equivalent for it in v2.0) and How can I write a separate class for Dash Support if I  follow the same architecture.

**Comment by ojw28** [comment]
I don't know about the leanback app. I suggest you ignore it and use the most recent ExoPlayer demo app.

**Comment by ram992** [comment]
Sure thanks Ojw, but there is one more question, can you suggest a fix,
 the problem is that, while running the demo app in Intex Mobile (Intex Aqua 4G) the video surface is not visible, but audio plays fine.
This not happening in other devices.

**Comment by ojw28** [comment]
We'd need a new issue that fills out the whole issue template to look at that.
