### ISSUE TITLE
How I can get audio tracks and subtitles?

### ISSUE THREAD

**Issue by bene25** [google/ExoPlayer#2626]
Hello.
I am using now ExoPLayer r2.3.1 version.
We have m3u8 file format such as:

#EXTM3U
#EXT-X-STREAM-INF:BANDWIDTH=490000,RESOLUTION=640x360
http://XXX.XXX.XX.XXX:31213/MEDIA/76336503.....583609776254/161/4161/
#EXT-X-STREAM-INF:BANDWIDTH=1500000,RESOLUTION=720x576
http://XXX.XXX.XX.XXX:31213/MEDIA/76336503.....583609776254/161/3161/
#EXT-X-STREAM-INF:BANDWIDTH=2500000,RESOLUTION=1280x720
http://XXX.XXX.XX.XXX:31213/MEDIA/76336503.....583609776254/161/2161/

Each EXT-X-STREAM-INF tag link to file like:

#EXTM3U
#EXT-X-TARGETDURATION:5
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:35156
#EXT-X-START:TIME-OFFSET=-25,PRECISE=YES
#EXT-X-KEY:METHOD=AES-128,URI="http://XXX.XXX.XX.XXX:02444/xxXXXXX/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/191/2191/aeskey_191_
#EXTINF:5,
http://XXX.XXX.XX.XXX:XXXXX/SSEGMENT/3020314583628416652818934133893/191/2191/seg_XXXXX.ts
#EXTINF:5,
http://XXX.XXX.XX.XXX:XXXXX/SSEGMENT/6545456465456456465454564/191/2191/seg_191_XXXXX.ts
#EXTINF:5,
http://XXX.XXX.XX.XXX:XXXXX/SSEGMENT/6545456465456456465454564/191/2191/seg_191_XXXXX.ts
#EXTINF:5,
http://XXX.XXX.XX.XXX:XXXXX/SSEGMENT/6545456465456456465454564/191/2191/seg_191_XXXXX.ts
#EXTINF:5,
http://XXX.XXX.XX.XXX:XXXXX/SSEGMENT/6545456465456456465454564/191/2191/seg_191_XXXXX.ts

Audio and subtitles are embeded in TS file.

As I uderstand you have made some changes in - https://github.com/google/ExoPlayer/commit/896550883f6d183e3ef46351eb3e494df8eaefba 

And now in HlsMediaChunk class:

extractor = new TsExtractor(TsExtractor.MODE_HLS, timestampAdjuster,
          new DefaultTsPayloadReaderFactory(esReaderFactoryFlags, muxedCaptionFormats));
muxedCaptionFormats.size() = 0.  

TrackSelectionHelper class:

mappedTrackInfo.getTrackGroups()
returns only one track on every track group

Stream example - https://drive.google.com/open?id=0B6PilUifi8koeHY2WlRsTEVkODQ

How can I get audiotracks and subtitles?
Thanks.

**Comment by AquilesCanta** [comment]
See #2014. This is not supported (except for CC). If you want to provide multiple audio track choices, the smartest choice is to demux them and declare them through EXT-X-MEDIA:TYPE="AUDIO". 

For closed captions you do not require any changes in the TS chunks, but you should add the corresponding EXT-X-MEDIA:TYPE="CLOSED-CAPTIONS" in the master playlist.

**Comment by bene25** [comment]
In previous version of player I did in HlsMediaChunk class:

 extractor = new TsExtractor(timestampAdjuster,
-            new DefaultTsPayloadReaderFactory(esReaderFactoryFlags), true);
+            new DefaultTsPayloadReaderFactory(esReaderFactoryFlags), false);

And after that I could get audiotracks. How can I do this in a new version?

**Comment by AquilesCanta** [comment]
Equivalent to that would be
```
extractor = new TsExtractor(TsExtractor.MODE_NORMAL, timestampAdjuster,
    new DefaultTsPayloadReaderFactory(esReaderFactoryFlags));
```
But keep in mind this is not its intended use, and we will most likely not provide support for any consequential issues.

**Comment by bene25** [comment]
class DefaultTsPayloadReaderFactory expects List<Format> closedCaptionFormats, and if I send null instead list player wont play video at all. If I send empty List<Format> player doesn't see tracks.
