### ISSUE TITLE
Handling default playback controls listener

### ISSUE THREAD

**Issue by zishanj** [google/ExoPlayer#2627]
Is there any way to handle default playback controls listener so we can override it with some additional feature?

**Comment by ojw28** [comment]
It's unclear what this question means. Also, there's a limit to the amount of per-app customization guidance we can provide. Please ask such questions on StackOverflow. This tracker is more for actual bugs/issues.

**Comment by zishanj** [comment]
Actually I am using `SimpleExoPlayerView` which shows default controls. I want to handle the click events of those controls play, pause, forward etc. so I can override it to extend its functionality.
