### ISSUE TITLE
com.google.android.exoplayer2.MediaFormat

### ISSUE THREAD

**Issue by ghost** [google/ExoPlayer#2629]
i'm importing this bit it dosen't support what to do i'm using     compile 'com.google.android.exoplayer:exoplayer:r2.3.1'

**Comment by andrewlewis** [comment]
The MediaFormat class was renamed to [Format](https://github.com/google/ExoPlayer/blob/r2.3.1/library/src/main/java/com/google/android/exoplayer2/Format.java) in version 2. If that's not what you're asking about please clarify the question.
