### ISSUE TITLE
How to play an UDP URI in demo module?

### ISSUE THREAD

**Issue by mossc** [google/ExoPlayer#2630]
**Step:**
1. Add an UDP URI in media.exolist.json
```
{
    "name": "Multicast",
    "samples": [
      {
        "name": "udp://@239.255.42.128:5004",
        "uri": "udp://@239.255.42.128:5004"
      }
    ]
},
```

2. Modify library/src/main/java/com/google/android/exoplayer2/upstream/DefaultDataSource.java
according to the reply from @Avetri of issue #2029 
```
library/src/main/java/com/google/android/exoplayer2/upstream/DefaultDataSource.java 
index ae6f1e0..28a5b3d 100644
@@ -40,7 +40,9 @@ public final class DefaultDataSource implements DataSource {
 
   private static final String SCHEME_ASSET = "asset";
   private static final String SCHEME_CONTENT = "content";
+  private static final String SCHEME_UDP = "udp";
 
+  private final DataSource udpDataSource;
   private final DataSource baseDataSource;
   private final DataSource fileDataSource;
   private final DataSource assetDataSource;
@@ -99,6 +101,7 @@ public final class DefaultDataSource implements DataSource {
     this.fileDataSource = new FileDataSource(listener);
     this.assetDataSource = new AssetDataSource(context, listener);
     this.contentDataSource = new ContentDataSource(context, listener);
+    this.udpDataSource = new UdpDataSource(listener);
   }
 
   @Override
@@ -116,6 +119,8 @@ public final class DefaultDataSource implements DataSource {
       dataSource = assetDataSource;
     } else if (SCHEME_CONTENT.equals(scheme)) {
       dataSource = contentDataSource;
+    } else if (SCHEME_UDP.equals(scheme)) {
+      dataSource = udpDataSource;
     } else {
       dataSource = baseDataSource;
     }
```

3. Test the demo module on Android phone.

**Result:**
Video won't be played and keep showing
`playWhenReady:true playbackState:buffering window:0`
![sss](https://cloud.githubusercontent.com/assets/13825672/24490425/1cb2d026-1555-11e7-8a03-1a5aae1a9593.png)

locat
```
03-30 14:10:25.105 27055-27251/com.google.android.exoplayer2.demo I/Adreno: QUALCOMM build                   : 03b6da7, I49f5588d88
                                                                            Build Date                       : 11/26/15
                                                                            OpenGL ES Shader Compiler Version: XE031.06.00.02
                                                                            Local Branch                     : 
                                                                            Remote Branch                    : refs/tags/AU_LINUX_ANDROID_LA.BF64.1.2.2_RB4.06.00.00.180.010
                                                                            Remote Branch                    : NONE
                                                                            Reconstruct Branch               : NOTHING
03-30 14:10:34.373 27055-27055/com.google.android.exoplayer2.demo I/ExoPlayerImpl: Init 2.3.1 [htc_himauhl, HTC_M9u, HTC, 23]
03-30 14:10:34.400 27055-27055/com.google.android.exoplayer2.demo D/EventLogger: state [0.00, true, I]
03-30 14:10:34.462 27055-27251/com.google.android.exoplayer2.demo W/OpenGLRenderer: Fail to change FontRenderer cache size, it already initialized
03-30 14:10:34.538 27055-27055/com.google.android.exoplayer2.demo D/EventLogger: state [0.14, true, B]
03-30 14:10:34.541 27055-27055/com.google.android.exoplayer2.demo D/EventLogger: sourceInfo [periodCount=1, windowCount=1
03-30 14:10:34.541 27055-27055/com.google.android.exoplayer2.demo D/EventLogger:   period [?]
03-30 14:10:34.541 27055-27055/com.google.android.exoplayer2.demo D/EventLogger:   window [?, false, false]
03-30 14:10:34.541 27055-27055/com.google.android.exoplayer2.demo D/EventLogger: ]
03-30 14:10:34.598 27055-27055/com.google.android.exoplayer2.demo D/EventLogger: loading [true]
```

**Note:**
1. ExoPlayer version: ExoPlayer-release-v2
2. The URI can be played normally on the same Android phone by VLC player

**Comment by Avetri** [comment]
Hello.

At least threre is no reason for @ before IP address.

Second, but not a source of the issue: 239 (as 224 and some others) group isn't suitable for an own multicast stream.

**Comment by Avetri** [comment]
@mossc 
Please attach a full logcat of the player and some sample part of the stream.

**Comment by mossc** [comment]
@Avetri 
Thanks for your reply.

About the @ before IP address, I had tested both URIs in VLC player Android version.
udp://@239.255.42.128:5004  ==> Play
udp://239.255.42.128:5004 ==> Won't play

And I had the same URI structure as issue #2029 , 

I think the UDP source is fine.

Or... I still miss something?

I will attach full log later.

**Comment by mossc** [comment]
@Avetri 
The full log for both URI:

udp://@239.255.42.128:5004
[full_log_with_a.txt](https://github.com/google/ExoPlayer/files/881760/full_log_with_a.txt)

udp://239.255.42.128:5004
[full_log_without_a.txt](https://github.com/google/ExoPlayer/files/881763/full_log_without_a.txt)

Also attach the successfully playback log of VLC player
udp://@239.255.42.128:5004
[vlc_with_a.txt](https://github.com/google/ExoPlayer/files/881779/vlc_with_a.txt)

**Comment by Avetri** [comment]
> I think the UDP source is fine.

I am not sure. Please attach a sample.
What is your source of multicast? It is sad if it is the VLC. Use tsplay.

Successfull VLC's playback says almost nothing. It is old native player that can open many kinds of bad content.

Unfortunatelly the logcat's logs are helpless. I saw no helpfull info. Output of the player is almost absent.

**Comment by mossc** [comment]
@Avetri 

My multicast source is a HDMI over IP **Transmitter**.
![devices](https://cloud.githubusercontent.com/assets/13825672/24544224/0c19bafa-1635-11e7-9073-24d44e16f7f1.jpg)

Testing environment:
HDMI -> **Transmitter** -> LAN -> **Receiver -> HDMI**

I would like to implement a android video player to replace that **Receiver -> HDMI**.

**Comment by Avetri** [comment]
@mossc 

So You have to make dumps of the Transmitter's stream in this case. No fact that there is MPEG TS in the stream as I expected.
I had (as DVB Engineer) a similar situation with security IP cams. Their developers don't like to completely follow MPEG TS standarts even when their streams look like it.

**Comment by mossc** [comment]
@Avetri 

OK, I will try to dump the Transmitter's stream.

Mean while, do you have any suggestion to build another transmitter?
May be another application like VLC?

I just want to try to use ExoPlayer play a multicast stream.

Thanks for your help!

**Comment by Avetri** [comment]
@mossc 
VLC isn't a good solution. It requires some tricks to send TS.
As I wrote above You should use [tsplay](https://sourceforge.net/projects/tstools.berlios/) as a source of multicast streams. But it is only a sender also. You need TS files.

**Comment by mossc** [comment]
@Avetri

I had dumped the streaming data from transmitter, please reference to the attachment.
[dump.out.zip](https://github.com/google/ExoPlayer/files/895418/dump.out.zip)

Check the dump file through MediaInfo:
![mediainfo](https://cloud.githubusercontent.com/assets/13825672/24733449/61c9879a-1aaa-11e7-9861-d8b27157e6e3.PNG)


Thanks

**Comment by Avetri** [comment]
@mossc @ojw28 
Issue #1002 strikes back.

**Comment by mossc** [comment]
@Avetri 
It seems really something happened on that TX device.
Thanks!!
