### ISSUE TITLE
Default player controller works once only in Fullscreen mode

### ISSUE THREAD

**Issue by zishanj** [google/ExoPlayer#2631]
I have tried to implement custom fullscreen mode in which the video is played in fullscreen. Initially, I have set the player `setUseController` to `false` in compact mode. But when the user switches to fullscreen mode I have set this property to `true`. Here is the screenshot of player in fullscreen mode with overlay player controls:
![screenshot_20170330-112540](https://cloud.githubusercontent.com/assets/1451292/24490873/08046b2e-153e-11e7-9e20-42a9ef6ec195.png)

This player control is in auto-hide mode. Once I tap on any button or use the seekbar and auto hide the controls, the controls does not display again. It works only when I set the `setUseController` to `true` initially.

**Comment by ojw28** [comment]
Please see https://github.com/google/ExoPlayer/issues/2627. This sounds like an error in your application code. There's no enough information for us to help.
