### ISSUE TITLE
Unexpected ID3 file Identifier,  on HLS stream

### ISSUE THREAD

**Issue by sanandrea** [google/ExoPlayer#2632]
Hi,
I have a crash on an HLS stream found and the crash log is on this [gist](https://gist.github.com/sanandrea/5244862008a21da740dd80a7c9c01942) .

The same stream on the iOS AVPlayer does not have problems. I cannot post the link to the stream because credentials are needed to access the CDN of the stream. I have captured the chunk I thought has the wrong ID3 metadata. I have attached the chunk on which the streaming fails (u-6400-a-48-1-1.ts and the extracted aac source.aac)

thanks in advance

[chunk.zip](https://github.com/google/ExoPlayer/files/881372/chunk.zip)

**Comment by ojw28** [comment]
It looks like you're using ExoPlayer V1. You should move to ExoPlayer V2 for more robust ID3 handling.

**Comment by sanandrea** [comment]
@ojw28 Thanks for your reply. I have also tried on the V2 ExoPlayer (some months before at commit 0cacd388fdff22408b54e2b7de2021c5b11f2742 => Merge: dbebaa87 75eb047e of 05/01/2017) but I encountered the same problem. I think I have tried before the release V2.2.0. I'm gonna make a new check today and let you know.

**Comment by ojw28** [comment]
Cool. Note there are a couple of remaining fixes in flight, which are tracked by https://github.com/google/ExoPlayer/issues/2604. I think your case is different though, and hopefully already fixed. If not, please respond to that issue. Note we wont be able to assist without sample content (provided privately if necessary via dev.exoplayer@gmail.com).

**Comment by sanandrea** [comment]
Hi @ojw28 I finally managed to have a [working test stream](http://csm-e.cds1.yospace.com/csm/extlive/skydeprd01,263032-test01hls.m3u8). I have tried with the latest ExoPlayer (release-v2 @ 2.3.1) and still have a problem related to timedMetaData. I am attaching the log
[sample_app_error_timedmetadata.log.zip](https://github.com/google/ExoPlayer/files/909368/sample_app_error_timedmetadata.log.zip)

**Comment by AquilesCanta** [comment]
I might be wrong, but I think the chunks are hosted in a different server than the playlist, and it's giving me a 403. Can you fix it?

**Comment by sanandrea** [comment]
@AquilesCanta I am sorry, I realized later, that the content on the CDN is geoblocked. I have sent an email to dev.exoplayer@gmail.com with the instructions. thank you!

**Comment by ojw28** [comment]
I gave the stream a try. It seemed to be doing something really weird where the video tracks were periodically being identified as audio, which was breaking playback. I couldn't reproduce any ID3 related failures, however. Are you sure you're still seeing ID3 failures, and not other failures related to incorrect track identification (which I suspect is an issue with the streams, although I didn't have time to confirm).

**Comment by AquilesCanta** [comment]
I haven't gotten any ID3 errors, either. Please try the dev branch and let me know if you are still getting the same ID3 decoding error. There has been some work on that area. 

The provided chunk does not declare any video (even though the stream in which it is presented does contain video). ExoPlayer does not currently support structural changes in the TS, except for specific cases under which the removal of video does not fall. As a workaround, you could add a black screen video to the chunks that have no video. Adding support for dynamic changes in the stream tracks is not on the roadmap, unfortunately.

**Comment by sanandrea** [comment]
Hi @AquilesCanta we have tried the following stream http://csm-e.cds1.yospace.com/csm/extlive/skydeprd01,263032-test01hls-audio.m3u8 it should be still working (via the CDN trick). News is that we have encountered the issue on the latest Exoplayer version 2.4.0 with the same exact error, but version 1.5.8 works perfectly and parses all timedMetadata.

**Comment by AquilesCanta** [comment]
Everything was working smoothly until I started getting a 403, around after 2 minutes of playback. Does the issue reproduce immediately for you?

**Comment by kashif135** [comment]
Any ETA when this bug fix will be released please?
