### ISSUE TITLE
"Skip silence" feature

### ISSUE THREAD

**Issue by mkaflowski** [google/ExoPlayer#2635]
Is there any chance to implement "skip silence" feature to Exoplayer or how can force player to do it? Some Podcast apps have it implemented.

**Comment by gemiren** [comment]
This will be an awesome feature.

**Comment by fjzboy** [comment]
@mkaflowski ,
I just need this feature too, i try remove the silence data in a custom AudioProcessor, but make nothing

**Comment by ojw28** [comment]
This feature is available to try on our `dev-v2` branch. You can turn on silence skipping using playback parameters, like:
```
player.setPlaybackParameters(
    new PlaybackParameters(/* speed= */ 1, /* pitch= */ 1, /* skipSilence= */ true));
```
