### ISSUE TITLE
How do I get the index of the current track being played using ExoPlayer

### ISSUE THREAD

**Issue by yookore** [google/ExoPlayer#2639]
I am working on an Android project that involves the use of Google's ExoPlayer. I have a list of video sources which I build a playlist from using the following code:

for (int i = 0; i < vidList.length(); i++) {
    MediaSource source = new ExtractorMediaSource(Uri.parse(vidList.getJSONObject(i).getString("url")),
                                buildDataSourceFactory(bandwidthMeter), extractorsFactory, mainHandler, HomeFragment.this);
                        mediaSources.add(source);
                        captions.add(vidList.getJSONObject(i).getString("caption"));
                    }

    mediaSource = new ConcatenatingMediaSource(mediaSources.toArray(new MediaSource[mediaSources.size()]));
I then call

exoplayer.prepare(mediasource, false, false)
and the videos play in succession fine. I would like to display the caption of the currently playing video in a textView and so I have a separate list that holds the "caption" values for each video.

From scouring through the code I see that I can get the currently playing video in the playlist like this;

exoPlayer.getCurrentPeriodIndex()
Which seems to work and returns the index except for one problem. It returns the value of 0 twice as playback starts. That is video at index 0 returns period 0 as well as video at index 1. This only occurs at indexes 0 and 1 and thereafter everything else looks fine except that the getCurrentPeriodIndex() will return theAccurateIndex - 1.

I see this also happening in the demo Exoplayer application. Is there a better way to determine what track is currently playing in the playlist?

Thanks.

**Comment by valdeir2000** [comment]
Managed to solve?
I also have the same doubt.

**Comment by andrewlewis** [comment]
Please could you provide steps to reproduce in the demo app? Specifically, where do you call `getCurrentPeriodIndex`? Thanks.

**Comment by valdeir2000** [comment]
It really was my mistake (logic error). I'll explain my situation.

I'm building the audio player. It turns out that I'm creating a custom notification with the buttons (previous, play, pause and next).

The problem is that I can not give the "next" command. So I decided to do it the following way.

```php
private void prepareMediaSource(ArrayList<Album.Music> musics, int start) {
        ArrayList<MediaSource> mediaSources = new ArrayList<>();

        for (Album.Music music : musics.subList(start, musics.size())) {
            mediaSources.add( new ExtractorMediaSource(Uri.parse(music.getUrlDownload()), dataSourceFactory, extractorsFactory, null, null));
        }

        ConcatenatingMediaSource concatenatingMediaSource = new ConcatenatingMediaSource(mediaSources.toArray(new MediaSource[mediaSources.size()]));
        player.prepare(concatenatingMediaSource);
    }
```

After all, how to change the mediaSource (Next or Previous)?

![](https://s11.postimg.org/wh35tir9f/Inked_Screenshot_1491312988_LI.jpg)

**Comment by andrewlewis** [comment]
If you prepare the player once with a `ConcatenatingMediaSource`, you can then seek to different sources using `player.seekTo(windowIndex, positionMs)`, where `windowIndex` is the index of the source in the concatenation to seek to. For an example, please refer to [PlaybackControlView.previous/next](https://github.com/google/ExoPlayer/blob/361241f/library/src/main/java/com/google/android/exoplayer2/ui/PlaybackControlView.java#L587).

@yookore Do you have steps to reproduce the original issue reported here in the demo app?

**Comment by valdeir2000** [comment]
Perfect! Thank you very much.
