### ISSUE TITLE
Support for limiting/disabling buffering

### ISSUE THREAD

**Issue by saket** [google/ExoPlayer#2642]
Hello folks, I tried searching a lot, but couldn't find anything that let's me control the buffering. I was wondering if it's possible to either limit buffering or disable it as soon as the first frame has been grabbed to display a preview. This would be helpful for our users that are on slower data connection.

### Version of ExoPlayer being used
r2.3.1

### Device(s) and version(s) of Android being used
Google emulator

**Comment by ojw28** [comment]
If you're trying to implement a preview, wouldn't it be a lot more efficient to extract the thumbnail on the server-side and just deliver it as an image to the client? It feels pretty heavy to be instantiating a video decoder and buffering the head of a video stream if that's the use case.

**Comment by saket** [comment]
I'm building a client for user submitted videos that are mostly hosted on imgur, gfycat, streamable, etc. so that won't be possible. But as you, I guess adding support for just getting the first frame would be heavy and not something that you'd want to do.

I also realized yesterday that Exoplayer does indeed not buffer the entire video. So my question is void.
