### ISSUE TITLE
How to retrieve bytes read online stream from Exoplayer after / before being played ?

### ISSUE THREAD

**Issue by satyres** [google/ExoPlayer#2645]
Hi , First thank you for this awesome library.
please if you don't mind i want to know how can i retrieve bytes read from Explayer after / before being played ?
i've looked at **ByteArrayDataSource** but i can't understand how to deal with it and how to use it with the player.
Kind regards

**Comment by ojw28** [comment]
What do you intend to do with the data once you've retrieved it?

**Comment by satyres** [comment]
i want to record them for my personal use .

**Comment by ojw28** [comment]
It's very unclear exactly what you're asking for. What do you actually intend to do with the data. What does "personal use" mean? If you just want to obtain the media file, why not download it directly using a normal http request?

**Comment by satyres** [comment]
ok,for the AAC and MP3 it's easy , but HLS , RTSP streams how can i record them ?
so the main idea is to obtain the bytes read before / after being played by the engine of Exoplayer.
so how can i obtain the bytes to record them on my phone?
Thank you
