### ISSUE TITLE
[HLS] Incorrect video height reported by onVideoSizeChanged()

### ISSUE THREAD

**Issue by mine260309** [google/ExoPlayer#265]
ExoPlayer's `onVideoSizeChanged()` shall report the video `width`, `height` and `pixelWidthHeightRatio`.
When I try to play some HLS streams (`1920*1080`), the video height is incorrectly reported as `1920*540`, `pixelWidthHeightRatio` is 1.

I added some logs in TsExtractor.H264Reader.parseMediaFormat() and MediaCodecVideoTrackRenderer.onOutputFormatChanged(), it shows TsExtractor correctly parse the width, height, but MediaCodec does not.
```
01-26 15:50:52.644    5265-5589/com.google.android.exoplayer.demo V/TsExtractor﹕ Set media format, width: 1920, height: 1080
...
01-26 15:50:53.105    5265-5584/com.google.android.exoplayer.demo V/MINEDBG﹕ {height=1184, what=1869968451, color-format=256, slice-height=1184, crop-left=32, width=2048, crop-bottom=563, crop-top=24, mime=video/raw, stride=4096, crop-right=1951}
```

The reported video width and height is calculated by:
```java
    currentWidth = hasCrop
        ? format.getInteger(KEY_CROP_RIGHT) - format.getInteger(KEY_CROP_LEFT) + 1
        : format.getInteger(android.media.MediaFormat.KEY_WIDTH);
    currentHeight = hasCrop
        ? format.getInteger(KEY_CROP_BOTTOM) - format.getInteger(KEY_CROP_TOP) + 1
        : format.getInteger(android.media.MediaFormat.KEY_HEIGHT);
```
here `hasCrop` is true, so `currentWidth = 1951-32+1 = 1920`, `currentHeight = 563-24+1 = 540`, where `KEY_CROP_*` are internal parameters.

So is it an issue in ExoPlayer, or in Android's media codec, or else?
How to get the correct video width/height in this case?

**Comment by ojw28** [comment]
I'm not certain, but it sounds like either an issue with the decoder implementation, or an issue with the actual underlying stream that you're trying to play. I'd guess it's more likely to be the latter, but we'd need a test stream that reproduces the issue to determine which of these is true.

**Comment by mine260309** [comment]
Test stream uploaded to GoogleDrive: https://drive.google.com/file/d/0B9tz6cYMkkwMa0FYeGF3Ui1xSmM/view?usp=sharing

From the stream side, `TsExtractor` gets the correct video size as well, and if you play it with VLC, the size is also correct.

From the decoder log, it looks like the video size is OK:
```
01-27 13:50:49.404  25406-26183/com.google.android.exoplayer.demo I/ACodec﹕ [OMX.TI.DUCATI1.VIDEO.DECODER] prepareForAdaptivePlayback(1920x1080)
```

Please have a look and test if you can reproduce the issue with the stream.

**Comment by fougere-mike** [comment]
This issue could be related to #375

**Comment by ojw28** [comment]
MediaCodecVideoTrackRenderer has an onInputFormatChanged and an onOutputFormatChanged. You say that the resolution is incorrect in onOutputFormatChanged. Could you look at what happens in onInputFormatChanged, and see if it's correct there? If it is, this is probably the same as #656.

**Comment by ojw28** [comment]
Assuming this is the same as #656. Closing.
