### ISSUE TITLE
Fire an event at a particular playback interval.

### ISSUE THREAD

**Issue by rafaeladel** [google/ExoPlayer#2653]
I'm wondering If there's an ability to fire an event every, say 30 seconds. I've searched in the issues for that and I found [issue](https://github.com/google/ExoPlayer/issues/1472), that says I should extend `TrackRenderer`.

I've searched for that class, didn't find it. But I've found `MediaCodecAudioRenderer`, Is that the class to be extended although I don't see where the event listener to be placed.

Is their a capability or a specific class to override or extend ?

**Comment by ojw28** [comment]
It should be pretty easy to write your own piece of code that looks at the playback position and fires events at specified times. It's not something you *need* the player to do for you. Having the player do it for you anyway for convenience is tracked by #2189.

**Comment by tonihei** [comment]
We're currently working on this feature to let the player run a callback when it reaches a certain playback position. We would like to have your opinion on some edge cases in #2189 - please let us know what would fit your requirements best.
