### ISSUE TITLE
Add a `release()` method to the DataSource interface

### ISSUE THREAD

**Issue by kiall** [google/ExoPlayer#2662]
### Issue description

DataSource's have no mechanism to release resources that must persist across seek's, but won't close automatically or be GC'd.

In my case, I have a custom DataSource to speak TVHeadend's custom TCP protocol. This connection is opened by the DataSource, and must persist across seeks, however, as a seek calls `close()` followed by `open()` with a non-zero `dataSpec.position`, we can't use `close()` to actually close the connection, as the timeshift buffer we're seeking within will be released when we close the connection, and we're unable to reopen a connection with the same state preserved.

Ideally, the DataSource interface would have a new method - `release()` which would be called once the DataSource is no longer required. This would allow us to maintain the connection between seek's, while providing a mechanism to cleanly close the connection once the datasource is no longer required.

The actual code I've got is a little more complicated, so hopefully this description does the request justice :)

### Reproduction steps

N/A

### Link to test content

N/A
### Version of ExoPlayer being used

2.3.1

### Device(s) and version(s) of Android being used

N/A

### A full bug report captured from the device

N/A

**Comment by ojw28** [comment]
I don't think we're going to support this, sorry. You can most likely achieve what you need without any direct support in ExoPlayer (e.g. by keeping track of your custom `DataSource` instances and releasing them when you release the player).
