### ISSUE TITLE
How can I preload multiple Videostreams before playing them

### ISSUE THREAD

**Issue by escamoteur** [google/ExoPlayer#2664]
Hi,

I need to be able to preload/prebuffer mutiple video streams (standard mp4 streams) before playing them so that they will start instantly. I need to be able to that while another Video is playing.
Is this possible with Exoplayer? How do I do that?

Thanks a lot for this great library!

Best
Thomas

**Comment by escamoteur** [comment]
Nobody here who knows how to solve this?

**Comment by ojw28** [comment]
We're using https://github.com/google/ExoPlayer/issues/2808 to track providing sample code for this use case.

**Comment by tonihei** [comment]
The new issue #3327 tracks an enhancement which more closely matches the request made here. This enhancement aims at supporting instant playback of the next playlist item (without explicitly downloading the content using a cache).
