### ISSUE TITLE
Implement MP2 audio support for HLS

### ISSUE THREAD

**Issue by SourceDoctor** [google/ExoPlayer#2665]
Some Stream URIs delivers mp2 Audio in HLS Stream.
Exoplayer says it cannot be decoded, so there is no sound.
It would be very nice to be implemented.

**Comment by ojw28** [comment]
The underlying platform does not provide support for MP2. It doesn't look like MP2 is allowed in the HLS spec, either. It might be possible to use the FFmpeg extension to play MP2 inside raw TS (not sure about the HLS case).

@andrewlewis - Is there a reason MP2 isn't listed as an option for FFmpeg [here](https://google.github.io/ExoPlayer/supported-formats.html)?

**Comment by andrewlewis** [comment]
Looks like the `mp3` decoder supports audio/mpeg-L2, so it should be added.

**Comment by ojw28** [comment]
As above, the FFmpeg extension might allow you to play MP2 successfully. It's not supported by the underlying platform. Closing.
