### ISSUE TITLE
ExoPlayer integration with Android Media Session/Controller

### ISSUE THREAD

**Issue by baq** [google/ExoPlayer#2666]
Hi,

I've been searching for examples or demos that integrate ExoPlayer2 with Android's Media Session and Controller interfaces.  The demo example included with ExoPlayer2 does a great job of showing how to use SimpleExoPlayer and its associated view to get up and running but my use case is a bit more complicated, and requires the ability to control Exoplayer from Android Wear and Auto, which requires the use of MediaSessionCompat, etc.  Any examples that the team is aware of that I could be pointed to?  Or perhaps this could be added to the Developer Guide?

Thanks for a great library!!
--Baq

**Comment by ojw28** [comment]
I'm not aware of any examples. The level of abstraction you're looking at is probably higher than anything we do directly on the ExoPlayer team. I suspect you'd find people with the ability to help on StackOverflow (or similar).

**Comment by ojw28** [comment]
An easy to use MediaSession integration was added as an extension in the `dev-v2` branch in https://github.com/google/ExoPlayer/commit/5be79d4f42848d40491d97c33a044eedaaa79f92. We'll be following up with further improvements and documentation.

**Comment by ojw28** [comment]
This will land in the `r2.5.0` release. There will also be a blog post available soon that explains how to make use of it, in case it's not self explanatory.

**Comment by baq** [comment]
Awesome, thank you!  We got ours working a long way back through other forums and trial and error, but having a formal guide will make it much easier for future developers.

**Comment by marcbaechinger** [comment]
We published this blog post about how to use the media session extension to connect ExoPlayer with a MediaSession: 

https://medium.com/google-exoplayer/the-mediasession-extension-for-exoplayer-82b9619deb2d
