### ISSUE TITLE
How can ExoPlayer force to do a limited playback / preview only ? 

### ISSUE THREAD

**Issue by ayeshq** [google/ExoPlayer#2667]
I want to force ExoPlayer to do a limited playback or a preview only from an HlsMediaSource video.
The video could be more than one hour long, but in special cases I only need to do a preview for just 2 minutes or less.

ExoPlayer can return the video duration, but doesn't not allow changing it !

Is there a simple to do this ?

**Comment by andrewlewis** [comment]
Prepare the player with a [ClippingMediaSource](https://github.com/google/ExoPlayer/blob/25a966dc2300161448fa74dee5ee98322ff65604/library/src/main/java/com/google/android/exoplayer2/source/ClippingMediaSource.java), passing the source you want to clip and the start/end times to its constructor: `player.prepare(new ClippingMediaSource(hlsMediaSource, 0, 120 * C.MICROS_PER_SECOND));`.

**Comment by ayeshq** [comment]
Hi

Exoplayer gets prepared successfully when using the ClippingMediaSource, and **onPlayerError** callback is never triggered, but the streaming never starts !
And I see these errors in logcat::

- 04-28 04:19:44.704 529-529/? E/OMX-VDEC-1080P: Extension: OMX.google.android.index.storeANWBufferInMetadata not implemented
- 04-28 04:19:44.716 529-1119/? E/OMX-VDEC-1080P: Extension: OMX.google.android.index.describeColorAspects not implemented
- 04-28 04:19:44.716 529-27505/? E/OMX-VDEC-1080P: Extension: OMX.google.android.index.describeHDRStaticInfo not implemented

Is there an extension required called OMX ? I couldn't find anything in the extensions code containing 'OMX' !

I also want to confirm that the playback never fails if I don't use the ClippingMediaSource !

Thanks

**Comment by andrewlewis** [comment]
Those errors are output by the media framework and I think they're harmless/expected.

Please could you provide steps to reproduce this in the demo app, including a link to the sample media (send it to dev.exoplayer@gmail.com if you don't want to post it here)?
