### ISSUE TITLE
ANR after multiple releasing and playing on Sony Bravia

### ISSUE THREAD

**Issue by bivenik** [google/ExoPlayer#2670]
Hello. 

I've implemented exoplayer in my android tv application for playing clear and ecnrypted content. I have a screen with array of live channel (some of them encrypted, other clear) and surfaceView. When I fast switching between them (new channel start playing after delay of 1 second of staying on it) I get ANR:

> I/InputDispatcher(1971): Application is not responding: AppWindowToken{d32e80f token=Token{1169f96e ActivityRecord{27bd08e9 u0 xxx.VideoPlayerActivity t6}}} - Window{14d44aa5 u0 xxx.VideoPlayerActivity}.  It has been 5039.7ms since event, 5001.6ms since wait started.  Reason: Waiting to send key event because the focused window has not finished processing all of the input events that were previously delivered to it.  Outbound queue length: 0.  Wait queue length: 2.

So seems main thread is blocked. 
I close the app and TV becomes almost unresponsible. I can't play any video even in other apps like youtube. 
It happens on Sony KD43X8309C - AndroidTV 5.1.1 a lot of times. 
When I switch channel, I make player.release() and before start new stream I create new instance of SimpleExoPlayer and start play new content. 

Do you have any idea why it happens? Can Exoplayer broke the whole media part of TV? Or it's something wrong with TV firware?

Best regards,
Ilya

**Comment by ojw28** [comment]
This issue is being closed because it does not adhere to our issue template, and/or because it omits information requested in the issue template that is required for us to investigate the problem efficiently. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).
