### ISSUE TITLE
[HLS] How to avoid decoder deinit/init on resolution change

### ISSUE THREAD

**Issue by swinder0161** [google/ExoPlayer#2672]
### Issue description
I am using simple exoplayer.
Everytime the resolution changes, I see mediacodec decoder is freed and created again.
This shows a glitch in video playback which is quite visible.
Ideally since decoder has advertised adaptive playback feature in media_codecs.xml, the decoder shouldnot be released and created again, infact portsettingschange event should be used to deallocate buffers incase already allocated buffers are too small for output.

### Reproduction steps
Play any hls manifest and wait for resolution to change higher to lower or lower to higher.

### Version of ExoPlayer being used
r2.3.1

### Device(s) and version(s) of Android being used
Android TV with Custom ROM Android 6.0.1

**Comment by ojw28** [comment]
We already avoid decoder release and re-initialization if the codec advertises that it's adaptive. Furthermore, Android 6.0.1 requires decoders are adaptive according to the [Android CDD](https://source.android.com/compatibility/6.0/android-6.0-cdd.pdf). See section 5.3:

> Device implementations MUST support dynamic video resolution and frame rate switching through the
standard Android APIs within the same stream for all VP8, VP9, H.264, and H.265 codecs in real time
and up to the maximum resolution supported on the device.

So the Custom ROM is not compliant with the Android CDD, either because its codecs aren't adaptive or because they're not advertising themselves as being adaptive.

Alternatively, you're using a codec other than one of the four mentioned above. In this case there's nothing we can do at the ExoPlayer level.

**Comment by swinder0161** [comment]
The mediacodec.xml is something like
```
    <MediaCodec name="OMX.xxx.decoder">
      <Type name="video/3gpp" />
      <Type name="video/avc" />
      <Type name="video/hevc" />
      <Type name="video/mp4v-es" />
      <Type name="video/mpeg2" />
      <Type name="video/vc1" />
      <Type name="video/wvc1" />
      <Type name="video/x-vnd.on2.vp8" />
      <Type name="video/x-vnd.on2.vp9" />
      <Feature name="adaptive-playback"/>
    </MediaCodec>
```

I added Feature name="adaptive-playback"

Now I think it should be added per type, like
```
    <MediaCodec name="OMX.xxx.decoder">
      <Type name="video/3gpp" />
      <Type name="video/avc">
        <Feature name="adaptive-playback"/>
      </Type>
      <Type name="video/hevc">
        <Feature name="adaptive-playback"/>
      </Type>
      <Type name="video/mp4v-es" />
      <Type name="video/mpeg2" />
      <Type name="video/vc1" />
      <Type name="video/wvc1" />
      <Type name="video/x-vnd.on2.vp8">
        <Feature name="adaptive-playback"/>
      </Type>
      <Type name="video/x-vnd.on2.vp9">
        <Feature name="adaptive-playback"/>
      </Type>
    </MediaCodec>
```

Will this solve my problem? I will try to test it after few hours.

**Comment by ojw28** [comment]
Don't think so. Looks like it's in the right place already. It does looks strange that a single codec component apparently supports *all* of those types.

**Comment by ojw28** [comment]
Closing since this seems like a custom ROM issue. You should contact whoever provides the ROM should you require further help working out what the codecs xml file should contain.

**Comment by swinder0161** [comment]
Just for information, Following has worked for me.
```
    <MediaCodec name="OMX.xxx.decoder">
      <Type name="video/3gpp" />
      <Type name="video/avc">
        <Feature name="adaptive-playback"/>
      </Type>
      <Type name="video/hevc">
        <Feature name="adaptive-playback"/>
      </Type>
      <Type name="video/mp4v-es" />
      <Type name="video/mpeg2" />
      <Type name="video/vc1" />
      <Type name="video/wvc1" />
      <Type name="video/x-vnd.on2.vp8">
        <Feature name="adaptive-playback"/>
      </Type>
      <Type name="video/x-vnd.on2.vp9">
        <Feature name="adaptive-playback"/>
      </Type>
    </MediaCodec>
```
