### ISSUE TITLE
Unable to play some live stream video Url

### ISSUE THREAD

**Issue by shailesh-fusionitechnology** [google/ExoPlayer#2674]
Why some live Stream URL is not playing in ExoPlayer? where as these live Stream URL easily play on other media player like VLC.
When these live stream URL is try to play with ExoPlayer, it gives following error

`com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 302 `

Why this error is occurring?

**Comment by ChernyshovYuriy** [comment]
It would be good if you can provide URL to test on, some examples? It is incomplete report otherwise.

**Comment by ojw28** [comment]
What @ChernyshovYuriy said. Although guessing: There's probably a cross-protocol redirect (e.g. https -> http). You can find related issues [here](https://github.com/google/ExoPlayer/issues?utf8=%E2%9C%93&q=is%3Aissue%20cross%20protocol).

**Comment by shailesh-fusionitechnology** [comment]
These are the url on which issue is occurring.

1.http://api.new.livestream.com/accounts/22711876/events/6759790/live.m3u8

2.http://hls.ksl.com/t/KSL_NEWSRADIO/playlist.m3u8

**Comment by ChernyshovYuriy** [comment]
First URL is terminated because of 302 response, URL redirection. Don't know whether ExoPlayer supports redirection.
Second one works perfectly.

**Comment by ChernyshovYuriy** [comment]
First one also works perfectly if you set "allowCrossProtocolRedirects" to TRUE in DefaultHttpDataSource.
From my point of view, on these two URLs ExoPlayer **work as designed**.

**Comment by shailesh-fusionitechnology** [comment]
Thanks, its working by setting "allowCrossProtocolRedirects" to TRUE.
