### ISSUE TITLE
How to do ZoomIn on AndroidTV devices ?

### ISSUE THREAD

**Issue by nshutov** [google/ExoPlayer#2677]
Hello

I tryind do ZoomIn featrure on android tv device, and its no work(
On mobile devices ZoomIn work fine with AspectRatioFrameLayout
How do ZoomIn on tv devices?

PS My previos issues:
https://github.com/google/ExoPlayer/issues/2448
https://github.com/google/ExoPlayer/issues/2484

**Comment by MegaLabs1** [comment]
Having same question. Could anybody answer?

**Comment by KnIfER** [comment]
I guess it's android's fault.  
same issue on vlc-android when sdk=android5.6  
https://trac.videolan.org/vlc/ticket/20253

**Comment by ojw28** [comment]
I don't think we need both this issue and https://github.com/google/ExoPlayer/issues/2484 open at once. Marking as duplicate.
