### ISSUE TITLE
Playing adaptive HLS 

### ISSUE THREAD

**Issue by Stalker11** [google/ExoPlayer#2678]
Hi. I have some problems with playing adaptive HLS video. Player requests playlist several times, but loading only one chunk video. Is it normal? How can I fix it problem?

` D/AdaptiveHLSListener: onLoadCompleted: DataSpec[http://193.106.60.8:8090/hls2/2/high.m3u8, null, 0, 0, -1, null, 1] null
D/AdaptiveHLSListener: onLoadStarted: -1 0 http://193.106.60.8:8090/hls2/2/high-372.ts1 0 null null 80435 85749 1754526341
 D/AdaptiveHLSListener: onLoadCompleted: DataSpec[http://193.106.60.8:8090/hls2/2/high.m3u8, null, 0, 0, -1, null, 1] null
 D/AdaptiveHLSListener: onLoadCompleted: DataSpec[http://193.106.60.8:8090/hls2/2/high-372.ts, null, 0, 0, -1, null, 0] Format(2, application/x-mpegURL, null, 2128000, , null, [-1, -1, -1.0], [-1, -1])
D/AdaptiveHLSListener: onLoadCompleted: DataSpec[http://193.106.60.8:8090/hls2/2/high.m3u8, null, 0, 0, -1, null, 1] null
D/AdaptiveHLSListener: onLoadCompleted: DataSpec[http://193.106.60.8:8090/hls2/2/high.m3u8, null, 0, 0, -1, null, 1] null
D/AdaptiveHLSListener: onLoadCompleted: DataSpec[http://193.106.60.8:8090/hls2/2/high.m3u8, null, 0, 0, -1, null, 1] null
D/AdaptiveHLSListener: onLoadCompleted: DataSpec[http://193.106.60.8:8090/hls2/2/high.m3u8, null, 0, 0, -1, null, 1] null
D/AdaptiveHLSListener: onLoadCompleted: DataSpec[http://193.106.60.8:8090/hls2/2/low.m3u8, null, 0, 0, -1, null, 1] null
D/AdaptiveHLSListener: onLoadCompleted: DataSpec[http://193.106.60.8:8090/hls2/2/high.m3u8, null, 0, 0, -1, null, 1] null
D/AdaptiveHLSListener: onLoadCompleted: DataSpec[http://193.106.60.8:8090/hls2/2/high.m3u8, null, 0, 0, -1, null, 1] null
D/AdaptiveHLSListener: onLoadStarted: -1 0 http://193.106.60.8:8090/hls2/2/high-373.ts1 0 null null 85749 95749 1754536650
D/AdaptiveHLSListener: onLoadCompleted: DataSpec[http://193.106.60.8:8090/hls2/2/high.m3u8, null, 0, 0, -1, null, 1] null
D/AdaptiveHLSListener: onLoadCompleted: DataSpec[http://193.106.60.8:8090/hls2/2/high.m3u8, null, 0, 0, -1, null, 1] null
D/AdaptiveHLSListener: onLoadCompleted: DataSpec[http://193.106.60.8:8090/hls2/2/high-373.ts, null, 0, 0, -1, null, 0] Format(2, application/x-mpegURL, null, 2128000, , null, [-1, -1, -1.0], [-1, -1])
D/AdaptiveHLSListener: onLoadCompleted: DataSpec[http://193.106.60.8:8090/hls2/2/high.m3u8, null, 0, 0, -1, null, 1] null
D/AdaptiveHLSListener: onLoadCompleted: DataSpec[http://193.106.60.8:8090/hls2/2/high.m3u8, null, 0, 0, -1, null, 1] null
D/AdaptiveHLSListener: onLoadStarted: -1 0 http://193.106.60.8:8090/hls2/2/high-374.ts1 0 null null 95749 103089 1754543075
D/AdaptiveHLSListener: onLoadCompleted: DataSpec[http://193.106.60.8:8090/hls2/2/low.m3u8, null, 0, 0, -1, null, 1] null
D/AdaptiveHLSListener: onLoadCompleted: DataSpec[http://193.106.60.8:8090/hls2/2/high.m3u8, null, 0, 0, -1, null, 1] null
D/AdaptiveHLSListener: onLoadCompleted: DataSpec[http://193.106.60.8:8090/hls2/2/high.m3u8, null, 0, 0, -1, null, 1] null
D/AdaptiveHLSListener: onLoadCompleted: DataSpec[http://193.106.60.8:8090/hls2/2/high-374.ts, null, 0, 0, -1, null, 0] Format(2, application/x-mpegURL, null, 2128000, , null, [-1, -1, -1.0], [-1, -1])
D/AdaptiveHLSListener: onLoadCompleted: DataSpec[http://193.106.60.8:8090/hls2/2/high.m3u8, null, 0, 0, -1, null, 1] null
D/AdaptiveHLSListener: onLoadCompleted: DataSpec[http://193.106.60.8:8090/hls2/2/high.m3u8, null, 0, 0, -1, null, 1] null
D/AdaptiveHLSListener: onLoadCompleted: DataSpec[http://193.106.60.8:8090/hls2/2/high.m3u8, null, 0, 0, -1, null, 1] null
D/AdaptiveHLSListener: onLoadCompleted: DataSpec[http://193.106.60.8:8090/hls2/2/high.m3u8, null, 0, 0, -1, null, 1] null
D/AdaptiveHLSListener: onLoadCompleted: DataSpec[http://193.106.60.8:8090/hls2/2/low.m3u8, null, 0, 0, -1, null, 1] null
D/AdaptiveHLSListener: onLoadCompleted: DataSpec[http://193.106.60.8:8090/hls2/2/high.m3u8, null, 0, 0, -1, null, 1] null
D/AdaptiveHLSListener: onLoadStarted: -1 0 http://193.106.60.8:8090/hls2/2/high-375.ts1 0 null null 103089 112009 1754553786
D/AdaptiveHLSListener: onLoadCompleted: DataSpec[http://193.106.60.8:8090/hls2/2/high.m3u8, null, 0, 0, -1, null, 1] null
D/AdaptiveHLSListener: onLoadCompleted: DataSpec[http://193.106.60.8:8090/hls2/2/high.m3u8, null, 0, 0, -1, null, 1] null
D/AdaptiveHLSListener: onLoadCompleted: DataSpec[http://193.106.60.8:8090/hls2/2/high.m3u8, null, 0, 0, -1, null, 1] null
D/AdaptiveHLSListener: onLoadCompleted: DataSpec[http://193.106.60.8:8090/hls2/2/high-375.ts, null, 0, 0, -1, null, 0] Format(2, application/x-mpegURL, null, 2128000, , null, [-1, -1, -1.0], [-1, -1])
D/AdaptiveHLSListener: onLoadCompleted: DataSpec[http://193.106.60.8:8090/hls2/2/high.m3u8, null, 0, 0, -1, null, 1] null
D/AdaptiveHLSListener: onLoadCompleted: DataSpec[http://193.106.60.8:8090/hls2/2/high.m3u8, null, 0, 0, -1, null, 1] null
D/AdaptiveHLSListener: onLoadCompleted: DataSpec[http://193.106.60.8:8090/hls2/2/high.m3u8, null, 0, 0, -1, null, 1] null
D/AdaptiveHLSListener: onLoadCompleted: DataSpec[http://193.106.60.8:8090/hls2/2/high.m3u8, null, 0, 0, -1, null, 1] null
D/AdaptiveHLSListener: onLoadCompleted: DataSpec[http://193.106.60.8:8090/hls2/2/high.m3u8, null, 0, 0, -1, null, 1] null
D/AdaptiveHLSListener: onLoadStarted: -1 0 http://193.106.60.8:8090/hls2/2/high-376.ts1 0 null null 112009 122009 1754561451
D/AdaptiveHLSListener: onLoadCompleted: DataSpec[http://193.106.60.8:8090/hls2/2/low.m3u8, null, 0, 0, -1, null, 1] null
D/AdaptiveHLSListener: onLoadCompleted: DataSpec[http://193.106.60.8:8090/hls2/2/high.m3u8, null, 0, 0, -1, null, 1] null
D/AdaptiveHLSListener: onLoadCompleted: DataSpec[http://193.106.60.8:8090/hls2/2/high.m3u8, null, 0, 0, -1, null, 1] null
D/AdaptiveHLSListener: onLoadCompleted: DataSpec[http://193.106.60.8:8090/hls2/2/high.m3u8, null, 0, 0, -1, null, 1] null
D/AdaptiveHLSListener: onLoadCompleted: DataSpec[http://193.106.60.8:8090/hls2/2/high-376.ts, null, 0, 0, -1, null, 0] Format(2, application/x-mpegURL, null, 2128000, , null, [-1, -1, -1.0], [-1, -1])`

**Comment by ojw28** [comment]
This issue is being closed because it does not adhere to our issue template, and/or because it omits information requested in the issue template that is required for us to investigate the problem efficiently. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).
