### ISSUE TITLE
[Question][HLS] How to use standalone HlsMediaSource to get current windows position of Live Playback

### ISSUE THREAD

**Issue by swinder0161** [google/ExoPlayer#2679]
### Issue description
Before starting playback or attaching exoplayer to MediaSource, I want to know what is the current end location of HLS.
The window is dynamic since it is live playback, I want to know beforehand where the end is so that I can start from some other location based on end location.

**Comment by AquilesCanta** [comment]
> Before [...] attaching exoplayer to MediaSource

Before calling `prepare(MediaSource)`, ExoPlayer does not know what the stream looks like. In that case, you are on your own, unfortunately.

> Before starting playback

You can prepare the player with playWhenReady == false, see what the window looks like (`ExoPlayer.EventListener#onTimelineChanged` will help), seek to the position you are interested in, and then set playWhenReady to true. This should work, from what I understood.

> end location of HLS

I assume you mean the live edge or the start of the window.
