### ISSUE TITLE
Using ConcatenatingMediaSource with a LoopingMediaSource throws IndexOutOfBoundsException

### ISSUE THREAD

**Issue by RomiValladares** [google/ExoPlayer#2680]
### Question description
I have to play video A once, and after it finished, loop video B indefinitely. I'm trying to use ConcatenatingMediaSource for that:

    private SimpleExoPlayer initPlayer(ViewGroup layout, int playerViewId, ExoPlayer.EventListener eventListener) {
        // 1. Create a default TrackSelector
        TrackSelector trackSelector = new DefaultTrackSelector();

        // 2. Create a default LoadControl
        LoadControl loadControl = new DefaultLoadControl();

        // 3. Create the player
        this.player = ExoPlayerFactory.newSimpleInstance(getContext(), trackSelector, loadControl);

        SimpleExoPlayerView simpleExoPlayerView = (SimpleExoPlayerView) layout.findViewById(playerViewId);
        // Bind the player to the view.
        simpleExoPlayerView.setUseController(false);
        simpleExoPlayerView.setPlayer(player);

        if (eventListener != null)
            player.addListener(eventListener);
        // Prepare the player with the source.
        player.setPlayWhenReady(true);

        return player;
    }

    public void startPlayer(String firstURL, String loopingURL) {
        initProxy();

        DefaultBandwidthMeter bandwidthMeter = new DefaultBandwidthMeter();
        MediaSource firstSource = getVideoPlayerMediaSource(bandwidthMeter, firstURL);
        MediaSource secondSource = new LoopingMediaSource(getVideoPlayerMediaSource(bandwidthMeter, loopingURL));

        ConcatenatingMediaSource concatenatedSource =
                new ConcatenatingMediaSource(firstSource, secondSource);

        player.setPlayWhenReady(true);
        player.prepare(concatenatedSource);
        player.setVideoScalingMode(C.VIDEO_SCALING_MODE_SCALE_TO_FIT_WITH_CROPPING);

        setPlayerPlaying(true);
    }

    private void initProxy() {
        if (proxy == null)
            proxy = VideoCache.getProxy(getContext());
    }

    @NonNull
    private MediaSource getVideoPlayerMediaSource(DefaultBandwidthMeter bandwidthMeter, String videoUrl) {
        DataSource.Factory dataSourceFactory = new DefaultDataSourceFactory(getContext(),
                Util.getUserAgent(getContext(), "com.myapp"), bandwidthMeter);

        ExtractorsFactory extractorsFactory = new DefaultExtractorsFactory();

        Uri url = Uri.parse(videoUrl);
        MediaSource videoSource;

        if (videoUrl.contains(".mp4")) {
            url = Uri.parse(proxy.getProxyUrl(videoUrl));
            videoSource = new ExtractorMediaSource(url,
                    dataSourceFactory, extractorsFactory, null, null);
        } else {
            videoSource = new HlsMediaSource(url, dataSourceFactory, null, null);
        }

        return videoSource;
    }

**The videos play correctly if I don't use the LoopingMediaSource.** Otherwise, a white screen appears and the attached stacktrace occurs.

### Version of ExoPlayer being used
r2.2.0
(The stacktrace corresponds to r2.2.0, but I've just tried with r2.3.1, and the same happens).

### Media used
I'm using "http://techslides.com/demos/sample-videos/small.mp4" for the first source and "http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4" for the second.

### Device(s) and version(s) of Android being used
Nexus 5X - Android 6.0.1

### A full bug report captured from the device
[bugreport.txt](https://github.com/google/ExoPlayer/files/918321/bugreport.txt)

    E/ExoPlayerImplInternal: Internal runtime error.
    java.lang.IndexOutOfBoundsException
        at com.google.android.exoplayer2.util.Assertions.checkIndex(Assertions.java:66)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.getPeriodPosition(ExoPlayerImplInternal.java:1075)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.getPeriodPosition(ExoPlayerImplInternal.java:1057)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.getPeriodPosition(ExoPlayerImplInternal.java:1048)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleSourceInfoRefreshed(ExoPlayerImplInternal.java:870)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:320)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:148)
        at android.os.HandlerThread.run(HandlerThread.java:61)
        at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)

**Comment by ojw28** [comment]
I suspect the problem here is that if you don't specify the repetition count for `LoopingMediaSource` we default to `MAX_VALUE`, which in practice will loop forever. If you then concatenate something on the front there will be more than `MAX_VALUE` periods in the timeline, so we probably end up with an overflow.

You can pretty easily validate this theory by explicitly passing the number of repetitions to the `LoopingMediaSource` as a second argument. You should find `Integer.MAX_VALUE - 1` works, but `Integer.MAX_VALUE` doesn't. If so, you can pass `Integer.MAX_VALUE - 1` here as a workaround, or any value that's larger than the number of loops anyone's ever going to watch in practice (e.g. 100000).

Could you test this and let us know if that is indeed the issue? If so, we'll come up with a proper fix also.

**Comment by RomiValladares** [comment]
Hi! Just tested it; passing `Integer.MAX_VALUE - 1` as a second parameter for `LoopingMediaSource` worked.
Thank you!
