### ISSUE TITLE
VTT subtitle track for specific HLS stream is partly displayed

### ISSUE THREAD

**Issue by jschm1** [google/ExoPlayer#2682]
**Issue description**
ExoPlayer seems to have trouble displaying subtiles for a specific HLS stream (See content link below).
When selecting the subtitle track "da, id:Fremmedsprogstekster, text/vtt", texts should render from 26:32 to 27:05. ExoPlayer only displays a single text at 26:59.

**Reproduction steps**
- Feed the link below to the demo player. 
- Select subtitle track "da, id:Fremmedsprogstekster, text/vtt".
- Fast forward to 26:32 and observe that no subtitles are displaying until 26:59.
- Crosscheck in the web-player at: https://www.dr.dk/tv/se/martin-uden-x/-/martin-uden-x-1-4#!/26:32 which selects this specific subtitle track per default and renders texts correctly from 26:32.

**Link to test content**
http://drod10r-vh.akamaihd.net/i/all/clear/streaming/a0/58e23e346187a4025c2641a0/Martin-uden-X--1-4-_7098ea006e7543d78267701dfa05a0fe_,293,453,888,1881,2671,.mp4.csmil/master.m3u8?cc1=name=Fremmedsprogstekster~default=yes~forced=no~lang=da~uri=https://www.dr.dk/mu-online/api/1.3/subtitles/playlist/urn:dr:mu:manifest:58e23e346187a4025c2641a0%3Fsegmentsizeinms=60000%26subtitleType=Foreign&cc2=name=Dansk~default=no~forced=no~lang=da~uri=https://www.dr.dk/mu-online/api/1.3/subtitles/playlist/urn:dr:mu:manifest:58e23e346187a4025c2641a0%3Fsegmentsizeinms=60000%26subtitleType=Foreign_HardOfHearing

**Version of ExoPlayer being used**
R2.3.1 and below.

**Device(s) and version(s) of Android being used**
HTC 10, with Android 7.0. This issue has been confirmed on other devices as well.

**Comment by ojw28** [comment]
The media is broken. If you look at the media playlist for that subtitle track, it declares that each segment has a 60 second duration:

```
......
#EXTINF:60,
https://www.dr.dk/mu-online/api/1.3/subtitles/segment/urn:dr:mu:manifest:58e23e346187a4025c2641a0?segmentsizeinms=60000&index=21&subtitleType=Foreign
#EXTINF:60,
https://www.dr.dk/mu-online/api/1.3/subtitles/segment/urn:dr:mu:manifest:58e23e346187a4025c2641a0?segmentsizeinms=60000&index=22&subtitleType=Foreign
#EXTINF:60,
https://www.dr.dk/mu-online/api/1.3/subtitles/segment/urn:dr:mu:manifest:58e23e346187a4025c2641a0?segmentsizeinms=60000&index=23&subtitleType=Foreign
#EXTINF:60,
https://www.dr.dk/mu-online/api/1.3/subtitles/segment/urn:dr:mu:manifest:58e23e346187a4025c2641a0?segmentsizeinms=60000&index=24&subtitleType=Foreign
#EXTINF:60,
https://www.dr.dk/mu-online/api/1.3/subtitles/segment/urn:dr:mu:manifest:58e23e346187a4025c2641a0?segmentsizeinms=60000&index=25&subtitleType=Foreign
#EXTINF:60,
https://www.dr.dk/mu-online/api/1.3/subtitles/segment/urn:dr:mu:manifest:58e23e346187a4025c2641a0?segmentsizeinms=60000&index=26&subtitleType=Foreign
......
```

So subtitles between 26:32 and 27:05 should all be in the one (or at most two) segments that span this duration of time. If you look at the actual segment content you'll see that this is not the case; subtitles have been placed into the wrong segments.

When ExoPlayer performs a seek it will load the segments starting from the one that corresponds to the seek position. In this case the corresponding segment contains only the single subtitle that's displayed. The other subtitles are incorrectly declared in the segments that correspond to the previous ~8 minutes of the content.

The only way a player would successfully display all subtitles for this media is if it were to blindly download all of the subtitle segments regardless of what the seek position is, which is inefficient and not something we'll be doing. The correct fix is to fix the media.
