### ISSUE TITLE
Specify start-end of a MediaSource

### ISSUE THREAD

**Issue by PaulWoitaschek** [google/ExoPlayer#2684]
I want to create a playlist containing several files. Some files contain chapter marks, so I want to treat them as separate tracks.

Is it possible to specify multiple media sources for a single file so a single `ConcatenatingMediaSource` can represent the whole playlist?

**Comment by ojw28** [comment]
It might be possible using multiple `ClippingMediaSource` instances and concatenating them together, but I doubt that would be a good/satisfactory solution. It's definitely less efficient to play, and depending on the type of the files you may not get seamless transitions at the chapter boundaries.

A single file with chapter marks *is* a single file, and so it doesn't seem like a good idea to try and trick the player into treating it as multiple separate files. This sounds like a UI problem as much as anything. You could play it as a single file and have a UI that's aware of the chapter information, which would be a much better solution.
