### ISSUE TITLE
Continue playback on live audio stream when going offline

### ISSUE THREAD

**Issue by solevic** [google/ExoPlayer#2685]
We're using the ExoPlayer r2.3.1 to read an mp3 live stream which is streamed from an Icecast 2.4.0 media server.

When going offline, it seems that the player stops the playback since it cannot resolve the connection to the host. However, I still have few seconds of data in the buffer that I'd like to continue playing.

Is there any way to prevent the player from stopping the playback when there is no connectivity?

This is especially critical to us to be able to handle network hookups and provide a smooth and stable playback to our users.

**Comment by ojw28** [comment]
This is tracked by https://github.com/google/ExoPlayer/issues/1606.
