### ISSUE TITLE
About reconfiguration initializationData

### ISSUE THREAD

**Issue by cauchywei** [google/ExoPlayer#2692]
I found the following code in MediaCodecRenderder 

``` Java
// For adaptive reconfiguration OMX decoders expect all reconfiguration data to be supplied
// at the start of the buffer that also contains the first frame in the new format.
if (codecReconfigurationState == RECONFIGURATION_STATE_WRITE_PENDING) {
    for (int i = 0; i < format.initializationData.size(); i++) {
        byte[] data = format.initializationData.get(i);
        buffer.data.put(data);
    }
    codecReconfigurationState = RECONFIGURATION_STATE_QUEUE_PENDING;
}
```

it's clear to understand the code according to the comment. But I have a question that the code is just work round for ExoPlayer's custom Extractor cooperating with MediaCodec or there are some bugs with Android MediaExtractor and MediaCodec when I try to reconfigure it on some devices?

**Comment by ojw28** [comment]
It's just getting the data to be organized into buffers in the way that MediaCodec expects it. It's neither a workaround nor is it related to any known bugs.
