### ISSUE TITLE
Better handle mp4 files that have the moov atom at the end

### ISSUE THREAD

**Issue by michalliu** [google/ExoPlayer#2695]
Exoplayer2 seems will read the entire file in order to play the mp4. That's too bad

**Comment by ojw28** [comment]
It wouldn't be much work to change ExoPlayer to make a range request for the `moov` atom in this case. Specifically, if we encounter an `mdat` atom having not yet encountered the `moov` atom, we'd make a range request starting at the first byte after the end of the `mdat` atom and hope to find the `moov` atom there. Marking as an enhancement. If you provide us with some sample media then we'll take a look.

As an aside, if you're generating this content yourself, you really should be putting the `moov` atom at the beginning. Even with the approach described above you need to make three requests before playback starts with the `moov` atom is at the end, compared to just one if it's at the beginning. Hence startup latency / efficiency is significantly worse if the `moov` atom is at the end.

**Comment by andrewlewis** [comment]
The logic for parsing atoms in `Mp4Extractor` should [initiate a seek](https://github.com/google/ExoPlayer/blob/17762eb/library/src/main/java/com/google/android/exoplayer2/extractor/mp4/Mp4Extractor.java#L263) if it needs to skip over a large amount of unneeded data (>= 256 KB). Please provide sample media so we can check whether this is working as intended.

**Comment by michalliu** [comment]
Thanks.  It's confirmed the seek operation is performed correctly. issue closed.
