### ISSUE TITLE
Not able to compile exoplayer using build gradle  

### ISSUE THREAD

**Issue by Pash97** [google/ExoPlayer#2698]
I have added 

                    repositories {
                                            jcenter()
                                       }
also
                 dependencies {
                                            compile 'com.google.android.exoplayer:exoplayer:r2.3.0'
                                         }
But it's giving me Error
 
                           Error: Failed to resolve: com.google.android.exoplayer:exoplayer:r2.3.0

**Comment by ojw28** [comment]
Where have you added these lines? I'm guessing you've added them in the wrong place, but you'd need to provide your build.gradle files (or at least sample build.gradle files that reproduce the issue) if you want someone to help.

**Comment by Pash97** [comment]
The following is my code
build.gradle(Project)
-----------------
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.3'
        classpath 'com.android.tools.build:gradle:1.0.0-rc1'



        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
        mavenCentral()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
----------------------------
build.gradle(Module)
----------------------------
apply plugin: 'com.android.application'

android {
    compileSdkVersion 25
    buildToolsVersion "25.0.2"
    defaultConfig {
        applicationId "com.example.pash.drm"
        minSdkVersion 15
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
       
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

repositories {
    maven { url 'http://repo1.maven.org/maven2' }
    jcenter { url "http://jcenter.bintray.com/" }

    mavenCentral()
    jcenter()
}
dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'

    })
    compile 'com.android.support:appcompat-v7:25.3.0'
    compile 'com.android.support:design:25.3.0'
    compile 'com.android.support:recyclerview-v7:23.3.+'
    compile 'com.android.support:cardview-v7:23.3.+'
    testCompile 'junit:junit:4.12'
    compile 'com.github.bumptech.glide:glide:3.7.0'
    compile 'com.squareup.picasso:picasso:2.5.2'
    compile 'com.android.support:support-v4:21.0.3'
    compile 'com.nineoldandroids:library:2.4.0'
    compile 'com.daimajia.slider:library:1.1.5@aar'
    compile 'com.google.android.exoplayer:exoplayer:r2.3.0'

}

**Comment by ojw28** [comment]
I tried copying those Gradle files into Android Studio and they appear to work fine for me. It's all very messy though, and there are a few unrelated warnings about how you're mixing and matching different versions of support library modules, which is a bad idea.

Are you sure there's not a button to install the missing modules immediately underneath the error? I'd suggest you try cleaning your Gradle files up a bit, making sure you have everything (e.g. Android Studio) up to date. If all else fails, I'd suggest asking on StackOverflow, since I think this is an issue with your local setup and/or Gradle files rather than with ExoPlayer.
