### ISSUE TITLE
Don't show playback controls automatically (e.g. when playback starts/fails/ends)

### ISSUE THREAD

**Issue by or-dvir** [google/ExoPlayer#2699]
### Issue description
**observed behavior:** when a video starts or ends, the media controllers (play/pause/seekbar etc) are automatically shown.
**wanted behavior:** when the video starts or ends, do **not** show the media controllers.

i was able to prevent the controllers from showing on video **start** by calling `mExoPlayerView.hideController();` as the very first line inside the method `public void onPlayerStateChanged(boolean playWhenReady, int playbackState)`. however this does not prevent the controllers from being shown on video **end**. instead what happens is the controllers are shown and imminently hidden again. 
this probably means that when a video ends, the controllers are first shown in the internal ExoPlayer code, and only **after** that, triggers `public void onPlayerStateChanged(boolean playWhenReady, int playbackState)` in my code.

is it possible to **not** show the controllers on video end at all? if so, how could i do that? if not, please consider adding this feature to the next version (something like `showControllersOnStart(boolean show)` and `showControllersOnEnd(boolean show)`).

### Reproduction steps
play any video, and get to the end of it

### Link to test content
irrelevant. can be reproduced on any video.

### Version of ExoPlayer being used
2.3.1

### Device(s) and version(s) of Android being used
LG K10 running android 6.0

### A full bug report captured from the device
irrelevant. not a bug.

**Comment by ojw28** [comment]
It's quite hard to cater for exactly what everyone wants with the UI components we're providing, at least without ending up with a huge number of parameters. For the specific behavior you want, what would you expect the control timeout logic to be? We currently do not time out the controls if the player is not initialized or in the ended state (but we do time out the controls if the player is playing or buffering). Would you expect the controls to be made visible if there was a playback error?

I think if you're going to use standard UI components, you have to accept how they behave to some extent. If you want very specific behavior it's appropriate that you should consider implementing your own UI components to do exactly what you want. That aside, we may consider supporting this depending on your answers to the questions above.

**Comment by or-dvir** [comment]
@ojw28 thanks for you reply.
i understand what you mean about not being able to cater to everyones' needs and wants. however from what ive read about ExoPlayer it's all about customization - giving the developer a choice.

as for your question about the timeout logic, it could be the same. the issue i'm describing it not about "how long should i wait before hiding the controllers", but about having control over when to show and hide them (regardless of the timeout, which i already have control over with the method "setTimeOut" or whatever its called). i know i know... there are "show" and "hide" methods. but those may not achieve the intended result as i have described above where the controllers are visible for about half a second or so before hiding again which it not a nice thing for the end user.
sure, i could simply implement my own controls from scratch, but i **do** like the way you implemented it (all the things that i get out-of-the-box) and i **do** want to use it. for example i really like how i could just give my own view the id of "previous" and i automatically get that behavior without having to do anything else. it saves me time, makes my code shorter, and eliminates potential bugs on my end. **its really great! well done on that part!**.

but back to my original point... ExoPlayer is all about customization and the developer having control right? well right now i only have 2 options which are: **1)** using the default behavior, or **2)** completely disabling the controllers and coding my own custom ones from scratch. i feel like there should be something in the middle there and i thought about a much better idea than "showControllersOnStart(boolean)".
how about something like "useDefaultControllerVisibility(boolean)"? what i mean is that if its set to FALSE, then the responsibility of showing/hiding the controllers is completely up to the developer (i.e. the methods "hide" and "show" will not be called internally).
this kind of behavior would be much more generic and not cater to a specific use case, give the developer another level of control and customization, all while still having the benefit of using some of the out-of-the-box logic.

so to answer your other question: "Would you expect the controls to be made visible if there was a playback error?" (and all the other possible states) - with the solution i offer, i can choose whether i want to do that or not.

**Comment by ojw28** [comment]
Basically what you're after is just a way to disable auto-showing of the controls under all circumstances, correct? We could probably add that.

Regarding the timeout, you don't really have full control. In particular the timeout is only applied in playing and buffering states. There's no way to set a timeout that applies in the ended or not-yet-started states (you could of course do the timing yourself and manually hide, if you wanted).

Would a way of disabling auto-showing of the controls, with the timeout behavior left as it is now, be sufficient for your needs?

**Comment by or-dvir** [comment]
@ojw28 that would be perfect. exactly what i am looking for.
thank you!

**Comment by ojw28** [comment]
@tonihei - Fancy adding support for this (disabling auto-showing of controls), since you've been adding a few options in the UI classes?

**Comment by ojw28** [comment]
@or-dvir - To clarify, with this setting enabled would you expect the controls to still be made visible on user input (e.g. user taps, trackball events and key presses)? Or to put it another way, which of the following do you want to suppress:

1. Just the automatic showing of controls when the playback state changes (e.g. to the ended state)
1. All showing of controls (automatic showing + showing based on user input), except when you programmatically ask for the controls to be displayed

Thanks.

**Comment by or-dvir** [comment]
@ojw28 thats a good question... my original intent was for the first one (playback states). but would it be possible to add both as **separate** options? it's basically the same logic... the way i see it the more control for the developer the better :)

**Comment by ojw28** [comment]
Thanks for the clarification. I *think* you already have the second one (setUseController(false)).

**Comment by or-dvir** [comment]
@ojw28 hi. just wondering if this feature has been added, and if so, as of which version and what the names of the new functions are

thanks
