### ISSUE TITLE
Loads video on Main thread causing the app unresponsive

### ISSUE THREAD

**Issue by wingoku** [google/ExoPlayer#270]
I am trying to stream an hour long video using simple DefaultRenderer. However when I press backButton the activity becomes unresponsive and doesn't go away for quite a long time and stays there on the screen.

Is this a bug in the library or I am missing something?

**Comment by lexer** [comment]
:+1: This should be fixed. Android activity is just frozen when player works.

**Comment by wingoku** [comment]
@lexer I am currently trying to get the frame number of the frame that is being rendered on the surfaceview. however I couldn't create a reliable way to get the exact frame number that is being rendered. So if the video is seeked to some point X, the frame number and rendering goes out of sync meaning the frame number I calculated in Player State ready is rendered after a few seconds. Is there a way to get the frame number at the exact moment of rendering?

**Comment by ojw28** [comment]
Those are two different questions.

- The freezing is a known issue. It only occurs when attempting to release the player whilst it's buffering; all other usage should be freeze free. It does not affect DASH/HLS/SmoothStreaming. Only other playbacks. There's a TODO in here to fix it: https://github.com/google/ExoPlayer/blob/dev/library/src/main/java/com/google/android/exoplayer/FrameworkSampleSource.java#L34

- What do you need the frame number for? I'm not sure that all container formats even contain sufficient information to calculate the exact frame number after a seek. Would the media timestamp associated with the frame be sufficient for you needs? If so, you could extend MediaCodecVideoTrackRenderer and have the subclass report the timestamp of the last frame to be rendered, like:

```
  @Override
  protected boolean processOutputBuffer(long positionUs, long elapsedRealtimeUs, MediaCodec codec,
      ByteBuffer buffer, MediaCodec.BufferInfo bufferInfo, int bufferIndex, boolean shouldSkip) {
    boolean processed = super.processOutputBuffer(positionUs, elapsedRealtimeUs, codec, buffer,
        bufferInfo, bufferIndex, shouldSkip);
    if (!shouldSkip && processed) {
      lastOutputBufferTimestamp = bufferInfo.presentationTimeUs;
    }
    return processed;
  }

  /**
   * @return The presentation timestamp of the most recently released frame.
   */
  public int getLastFrameTimestampMs() {
    return (int) (lastOutputBufferTimestamp / 1000);
  }
```

**Comment by ojw28** [comment]
NB - That approach may actually be a few frames "ahead" during playback, although will settle of the exact correct value when paused.

**Comment by ojw28** [comment]
Closing this issue, since it's tracking multiple things. I've filed #274 to track the originally reported issue.

**Comment by kandroid** [comment]
Still not getting what is the solution of this ANR issue when releasing exoplayer on buffering. Can you guys please tell what is the workaround to avoid this?

**Comment by ojw28** [comment]
FrameworkSampleSource is deprecated, so the solution is to not use it. The demo app no longer uses it at all. Use ExtractorSampleSource instead.
