### ISSUE TITLE
S/PDIF Passthrough in exoplayer

### ISSUE THREAD

**Issue by darwinvtomy** [google/ExoPlayer#2700]
How can i enable S/PDIF passthrough, if i am using an android box 
**I enabled Ac3 support to the ff-mpeg in  Exoplayer but Its giving PCM output  in the S/PDIF** 
Device :-  Himedia H8 and Q5 Android Box
OS:- Android 5.1.1
H8 CPU:- Rockchip Rk3368 ARM Cortex A53 Octa-Core 64 Bit Processor   &
Q5 CPU:-Hisilicon Hi3798CV200 Quad core 64-bit high-performance ARM Cortex A53 CPU, 2.0GHz
These device has the build in support for Passthrough if i use normal Video View  it will give 5.1 output 
in the spdif .If i use the exoplayer it will give PCM stereo 
Buld in Renderer:- **RockFFPlayer** 
_Where do i start, please help !!!!_

**Comment by andrewlewis** [comment]
If the Android TV box is connected via HDMI, please read #2148. Otherwise, this is probably covered by the enhancement in #1741.

**Comment by darwinvtomy** [comment]
I followed your above comments and i got this error AudioTrack init failed: 0, Config(48000, 252, 20480)
does it have anything to do with this line of code
  private static final MediaCodecInfo PASSTHROUGH_DECODER_INFO =
      MediaCodecInfo.newPassthroughInstance("**_OMX.google.raw.decoder_**");

**Comment by andrewlewis** [comment]
There's not nearly enough information here to investigate this. As requested in the issue template, we need a full bug report. Also, I don't know anything about RockFFPlayer, but if it's an ExoPlayer renderer then the issue probably lies there.

If you want to use ExoPlayer's HDMI passthrough support, please refer to #2148 as mentioned in my previous comment.

**Comment by arnoutvandervorst** [comment]
It actually works for me now with Shield Preview 5.2. The update seems to have added something which tells ExoPlayer it can passthrough...yay!
