### ISSUE TITLE
Handle unexpected HLS playlist type

### ISSUE THREAD

**Issue by Teviz** [google/ExoPlayer#2702]
In HlsPlaylistTracker$MediaPlaylistBundle#onLoadCompleted method, the result of loadable.getResult() method is cast to HlsMediaPlaylist. It works all right int most time, but when some hls stream is uncontrollable, it will throw out  ClassCastException with the message like that.
`com.google.android.exoplayer2.source.hls.playlist.HlsMasterPlaylist cannot be cast to com.google.android.exoplayer2.source.hls.playlist.HlsMediaPlaylist`

I found the stream source through user log, but I cant reproduce it because in different time the playlist is different. When I got the url, the wrong playlist has changed and the stream plays no problem. 
I'm not sure is there any reason that it cant be HlsMasterPlaylist for you. But I think it may need to verify before cast to guarantee that the wrong source will not affect the player or even interrupt the program.

**Comment by ojw28** [comment]
Something *really* weird would have to happen on the server for this to end up happening on the client. Nevertheless, it should be easy just to check the type and call into `onLoadError` instead if it's not what we expect.

There's no way playback will be able to continue in this case (unless the server corrects what it's doing before the player gives up), but it will fail more gracefully.

**Comment by Teviz** [comment]
That's what I want, thanks.
BTW, is there any exact date or version that I can use the handled lib in my app?

**Comment by ojw28** [comment]
This is fixed in `dev-v2`. The fix will be in `r2.4.0` and above, so keep a look out for that. We will likely release later this week.
