### ISSUE TITLE
ffmpeg extension  amr file

### ISSUE THREAD

**Issue by shoyu666** [google/ExoPlayer#2704]
dear author:
      we want player .amr file ,but not support ,so we build ffmpeg extension , and build success
       is any ffmpeg extension exmple ? 

      we use
      EXTENSION_RENDERER_MODE_PREFER 
      ExtractorMediaSource(Uri.pares("xxx.amr"))

      get exception
       None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor) could read the stream.   

      my question is how to use ffmpeg   extension 

      we have see other extension test case  but no idea

**Comment by andrewlewis** [comment]
Adding support for extraction of AMR containers is tracked by #2527. (If you've built FFmpeg with AMR decoding you should be able to play AMR tracks embedded MP4s already, though.)
