### ISSUE TITLE
Unable to change buildDir to absolute path

### ISSUE THREAD

**Issue by canatella** [google/ExoPlayer#2709]
### Issue description

When doing an out of tree build, gradle fails:

gradle -PbuildDir=../test clean assembleDebug
Incremental java compilation is an incubating feature.
:demo:clean
:extension-ffmpeg:clean
...
:library-dash:generateReleaseResValues
:library-dash:generateReleaseResources
:library-dash:mergeReleaseResources
:library-dash:processReleaseManifest
:library-dash:processReleaseResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':library-dash:processReleaseResources'.
> Error: A library uses the same package as this project: com.google.android.exoplayer2.source.dash

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
 

### Reproduction steps
Change the build directory by giving the -PbuildDir=../test arguments to gradle when building exoplayer.

### Version of ExoPlayer being used
dev-v2: da1b55ed4 NullPointerException in CronetDataSource constructor

### Device(s) and version(s) of Android being used
Android SDK 25
Gradle 3.3

**Comment by ChernyshovYuriy** [comment]
Are you sure you build from the root of the project?
It builds fine on my side, logs attached.
Also, this is build related issue, how it correlates with the ExoPlayer ? I think your question is unrelated to some degree.
[buildExoPlayer.txt](https://github.com/google/ExoPlayer/files/944953/buildExoPlayer.txt)

**Comment by canatella** [comment]
Yes, I'm in the root of the project. It's working for other projects so I think it's related to ExoPlayer gradle configuration. 

I agree it's a build issue, is there a better place to report ExoPlayer build issues ?

I also forgot to mention that it was working before the modularisation changes and I'm on OSX.

**Comment by ojw28** [comment]
I don't think `-PbuildDir=../test` is a valid thing to do. It looks like this argument specifies the build directory of each module relative to its root.

Using `../test` means that `library/core`, `library/dash`, `library/hls` etc all end up trying to use the same build directory `library/test`, which is probably why bad things start to happen.

For comparison, using `-PbuildDir=test` works fine, with the modules having separate build directories `library/core/test`, `library/dash/test`, `library/hls/test` etc.

**Comment by canatella** [comment]
If you just mean ../test is not valid I might agree, but if you mean out of tree builds are not a valid things to do then I do disagree. It makes perfect sense, for example  see http://voices.canonical.com/jussi.pakkanen/2013/04/16/why-you-should-consider-using-separate-build-directories/.

Anyway If you are not completely against offering a way to do out of tree ExoPlayer builds, I investigated a bit the issue and wrote a simple patch that would allow it:

    diff --git a/build.gradle b/build.gradle
    index 9c83e045d..5b3c955df 100644
    --- a/build.gradle
    +++ b/build.gradle
    @@ -51,6 +51,11 @@ allprojects {
             releaseVersion = 'r2.3.1'
             releaseWebsite = 'https://github.com/google/ExoPlayer'
         }
    +    if (it.hasProperty('externalBuildDir')) {
    +        if (!new File(externalBuildDir).isAbsolute())
    +            externalBuildDir = new File(rootDir, externalBuildDir)
    +        buildDir = "${externalBuildDir}/${project.name}"
    +    }
     }

If you build with -PexternalBuildDir=../test it will work, it's working also with absolute paths. If you are willing to merge this, I can create a PR. 

I needed to add a it to hasProperty because of an issue in gradle (https://issues.gradle.org/browse/GRADLE-1826). It should be fixed but it still broken in recent gradle version so...

**Comment by ojw28** [comment]
I'm not adverse to supporting out of tree builds; I was just saying using `../someDir` doesn't appear to be the correct way to do it.

Is `externalBuildDir` something new that you're defining, or does it already have a use already that you're changing the behavior of? If it's something new that you're defining then your proposal looks good to me. Feel free to send a pull request to the `dev-v2` branch; thanks!

**Comment by canatella** [comment]
Ok then we agree ;) the ../someDir was just an easy way for people to reproduce the problem.

I made up externalBuildDir and I don't think externalBuildDir it is used so I'll create a PR with the change as is.

**Comment by canatella** [comment]
I just created pull request #2715.
