### ISSUE TITLE
Extract audio samples with ExoPlayer v2

### ISSUE THREAD

**Issue by yuriy-vorontsov** [google/ExoPlayer#2712]
Hello,

At the moment I use MediaExtractor to extract audio samples.
My code is based on the following example: https://developer.android.com/reference/android/media/MediaExtractor.html

I'm working on audio fingerprint, I have custom Extractor to fix lame issue (https://github.com/google/ExoPlayer/issues/328) and I want to extract audio samples with ExoPlayer using my custom Extractor.

Please provide an example how to use ExoPlayer instead of MediaExtractor.

**Comment by andrewlewis** [comment]
ExoPlayer's extractors don't have the same API as MediaExtractor, but it's probably quite straightforward to implement a wrapper that gives a similar interface. (I think the main difference to be aware of is that MediaExtractor has a blocking method to read a sample, whereas ExoPlayer's extractors read data incrementally.)

I'd start by reading the [Extractor](https://github.com/google/ExoPlayer/blob/ba9a82e/library/src/main/java/com/google/android/exoplayer2/extractor/Extractor.java) interface and its dependencies, and looking at how it's used from [ExtractorMediaPeriod](https://github.com/google/ExoPlayer/blob/ba9a82e9823ce55bd0f1e5492556a06862657d16/library/src/main/java/com/google/android/exoplayer2/source/ExtractorMediaPeriod.java). As this isn't really a playback issue, providing more detailed guidance is probably outside the scope of this issue tracker.
