### ISSUE TITLE
Play two videos at the same time in Exoplayer in TV boxes

### ISSUE THREAD

**Issue by karthiktag** [google/ExoPlayer#2713]
### Issue description
Playing the two video at same time in exoplayer it throws Error "Decoder init failed: OMX.amlogic.avc.decoder.awesome".In Nexus 7 Tablet it play the two videos without any error but in the Android TV Box such as TX8,H96,MiniMX it plays the first video alone and its throws error to the second video.some times it throws error for both the videos.(Note:View contains webview and 2 exoplayer.Its loads Iframe content inside the webview).

### Reproduction steps
Create the two instance of ExoPlayer and create separate instance of mediasource to the respective exoplayer instance .Prepare and play the two videos at same time. 

### Version of ExoPlayer being used
ExoPlayer 2.0.4

### Device(s) and version(s) of Android being used
Nexus 7 Tablet Android Version 6.0.1 - It plays the two video without error
Android TV Box                             - its throws error.
MiniMX Android Version 5.0
TX8      Android Version 5.0
H96      Android Version 6.0.1

### A full bug report captured from the device
FAILED to allocate omx component 'OMX.amlogic.avc.decoder.awesome' err=InsufficientResources(0x80001000)
04-20 06:00:46.289 19742-20101/? W/ACodec: Allocating component 'OMX.amlogic.avc.decoder.awesome' failed, try next one.
04-20 06:00:46.289 19742-20101/? E/ACodec: Unable to instantiate codec 'OMX.amlogic.avc.decoder.awesome' with err 0xfffffff4.
04-20 06:00:46.289 19742-20101/? E/ACodec: signalError(omxError 0xfffffff4, internalError -12)
04-20 06:00:46.289 19742-20100/? E/MediaCodec: Codec reported err 0xfffffff4, actionCode 0, while in state 1
04-20 06:00:46.292 19742-20098/? I/MediaCodec: [OMX.amlogic.avc.decoder.awesome] setting surface generation to 20215813
04-20 06:00:46.293 19742-20098/? V/MediaCodec: Found 2 pieces of codec specific data.
04-20 06:00:46.294 3764-9331/? D/OmxVideoDecoder: setParameter 544 0x1000017
04-20 06:00:46.294 3764-4157/? D/OmxComponent: getExtensionIndex 1091 name="OMX.google.android.index.storeANWBufferInMetadata"
04-20 06:00:46.294 3764-4157/? D/OmxComponent: getExtensionIndex 1091 name="OMX.google.android.index.storeMetaDataInBuffers"
04-20 06:00:46.294 3764-4157/? D/OmxVideoDecoder: setParameter 544 0x7f000002
04-20 06:00:46.295 3764-4157/? D/OmxVideoDecoder: setParameter 851 OMX_IndexAndroidStoreMetadataInBuffers
04-20 06:00:46.295 3764-4157/? E/OMXNodeInstance: setParameter(a6:amlogic.avc.decoder.awesome, OMX.google.android.index.storeMetaDataInBuffers(0x7f000002): Output:1 en=1 type=1) ERROR: BadPortIndex(0x8000101b)
04-20 06:00:46.295 19742-20099/? E/ACodec: [OMX.amlogic.avc.decoder.awesome] storeMetaDataInBuffers failed w/ err -2147483648
04-20 06:00:46.295 3764-4133/? D/OmxComponent: getExtensionIndex 1091 name="OMX.google.android.index.prepareForAdaptivePlayback"
04-20 06:00:46.295 3764-4133/? D/OmxVideoDecoder: setParameter 544 0x7f000004
04-20 06:00:46.295 3764-4133/? D/OmxVideoDecoder: setParameter 865 OMX_IndexAndroidPrepareForAdaptivePlayback
04-20 06:00:46.295 3764-4133/? D/OmxVideoDecoder: AdaptivePlayback: max resolution is 1280 * 720
04-20 06:00:46.298 3764-15885/? D/OmxVideoDecoder: setParameter 544 0x6000001
04-20 06:00:46.298 3764-15885/? D/OmxVideoDecoder: setParameter nPortIndex 0 CompFmt 0x7 ColorFmt 0
04-20 06:00:46.299 3764-4133/? D/OmxVideoDecoder: setParameter 544 0x6000001
04-20 06:00:46.299 3764-4133/? D/OmxVideoDecoder: setParameter nPortIndex 1 CompFmt 0 ColorFmt 0x15
04-20 06:00:46.300 3764-4860/? D/OmxVideoDecoder: setParameter 544 0x2000001
04-20 06:00:46.300 3764-4860/? D/OmxVideoDecoder: newBufferCount = 5, outWidth=1280, outHeight=720
04-20 06:00:46.300 3764-4860/? D/OmxVideoDecoder: setParameter nPortIndex 0 nFrameWidth 1280 nFrameHeight 720 nSliceHeight 16
04-20 06:00:46.300 3764-3764/? E/ResourceManagerService: getLowestPriorityBiggestClient_l: lowest priority 2 vs caller priority 2
04-20 06:00:46.300 3764-9331/? V/OmxVideoDecoder: mUseNativeBuffers 0
04-20 06:00:46.301 3764-4133/? D/OmxVideoDecoder: setParameter 544 0x2000001
04-20 06:00:46.301 3764-4133/? D/OmxVideoDecoder: newBufferCount = 4, outWidth=1280, outHeight=720
04-20 06:00:46.301 3764-4133/? D/OmxVideoDecoder: setParameter mUseNativeBuffers=0
04-20 06:00:46.301 3764-4133/? W/OmxVideoDecoder: Can not read property media.omx.display_mode
04-20 06:00:46.301 3764-4133/? D/OmxVideoDecoder: workaround for dynamic buffer allocation, tWidth=1280, tHieght=720
04-20 06:00:46.301 3764-4133/? D/OmxVideoDecoder: setParameter nPortIndex 1 nFrameWidth 1920 nFrameHeight 1088 nSliceHeight 1088
04-20 06:00:46.301 3764-4133/? V/OmxVideoDecoder: mUseNativeBuffers 0
04-20 06:00:46.302 3764-15885/? D/OmxComponent: getExtensionIndex 1091 name="OMX.google.android.index.enableAndroidNativeBuffers"
04-20 06:00:46.302 3764-15885/? D/OmxVideoDecoder: setParameter 544 0x7f000000
04-20 06:00:46.302 3764-15885/? V/OmxVideoDecoder: setParameter 845 EnableNativeBuffers 1
04-20 06:00:46.302 3764-15885/? V/OmxVideoDecoder: mUseNativeBuffers 1
04-20 06:00:46.302 3764-15885/? D/AmlogicVideoDecoderAwesome: get native buffer info NV:w:1920,h:1088..
04-20 06:00:46.302 3764-15885/? V/OmxVideoDecoder: updatePort:portDef.format.video.nFrameWidth=1920,portDef.format.video.nFrameHeight=1088
04-20 06:00:46.303 3764-15885/? V/OmxVideoDecoder: mUseNativeBuffers 1
04-20 06:00:46.303 3764-15885/? D/AmlogicVideoDecoderAwesome: get native buffer info NV:w:1920,h:1088..
04-20 06:00:46.303 3764-15885/? V/OmxVideoDecoder: updatePort:portDef.format.video.nFrameWidth=1920,portDef.format.video.nFrameHeight=1088
04-20 06:00:46.304 3764-4861/? D/OmxVideoDecoder: getConfig 994 0x700000f
04-20 06:00:46.304 3764-4861/? D/OmxVideoDecoder: getConfig 997 nIndex 0x700000f
04-20 06:00:46.304 3764-4861/? D/OmxVideoDecoder: getConfig OMX_IndexConfigCommonOutputCrop pRect->nWidth=1920, pRect->nHeight=1088
04-20 06:00:46.305 3764-20102/? I/OmxComponent: OMX_CommandStateSet 706 Cmd 0 nParam1 0x2
04-20 06:00:46.305 3764-20102/? I/OmxComponent: STATE_SET:   OMX_StateLoaded => OMX_StateIdle : OMX.amlogic.avc.decoder.awesome
04-20 06:00:46.305 3764-20102/? I/OmxComponent: STATE_TRANS: OMX_StateLoaded => OMX_StateIdle : OMX.amlogic.avc.decoder.awesome
04-20 06:00:46.306 19742-20094/? W/MediaCodec-JNI: try to release MediaCodec from JMediaCodec::~JMediaCodec()...
04-20 06:00:46.306 19742-20094/? W/MediaCodec-JNI: done releasing MediaCodec from JMediaCodec::~JMediaCodec().
04-20 06:00:46.306 3764-20102/? I/OmxComponent: STATE_TRANS: OMX_StateLoaded => OMX_StateIdle : OMX.amlogic.avc.decoder.awesome
04-20 06:00:46.307 3764-20102/? I/OmxComponent: STATE_TRANS: OMX_StateLoaded => OMX_StateIdle : OMX.amlogic.avc.decoder.awesome
04-20 06:00:46.307 3764-20102/? I/OmxComponent: STATE_TRANS: OMX_StateLoaded => OMX_StateIdle : OMX.amlogic.avc.decoder.awesome
04-20 06:00:46.307 3764-20102/? I/OmxComponent: STATE_TRANS: OMX_StateLoaded => OMX_StateIdle : OMX.amlogic.avc.decoder.awesome
04-20 06:00:46.307 3764-20102/? I/OmxComponent: STATE_TRANS: OMX_StateLoaded => OMX_StateIdle : OMX.amlogic.avc.decoder.awesome
04-20 06:00:46.308 19742-20098/? V/MediaCodec: input buffers allocated
04-20 06:00:46.308 3764-9331/? V/OmxVideoDecoder: mUseNativeBuffers 1
04-20 06:00:46.308 3764-9331/? D/AmlogicVideoDecoderAwesome: get native buffer info NV:w:1920,h:1088..
04-20 06:00:46.308 3764-9331/? V/OmxVideoDecoder: updatePort:portDef.format.video.nFrameWidth=1920,portDef.format.video.nFrameHeight=1088
04-20 06:00:46.308 3764-12290/? V/OmxVideoDecoder: mUseNativeBuffers 1
04-20 06:00:46.308 3764-12290/? D/AmlogicVideoDecoderAwesome: get native buffer info NV:w:1920,h:1088..
04-20 06:00:46.308 3764-12290/? V/OmxVideoDecoder: updatePort:portDef.format.video.nFrameWidth=1920,portDef.format.video.nFrameHeight=1088
04-20 06:00:46.308 19742-20094/? E/ExoPlayerImplInternal: Renderer error.
                                                          com.google.android.exoplayer2.ExoPlaybackException
                                                              at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.throwDecoderInitError(MediaCodecRenderer.java:371)
                                                              at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:359)
                                                              at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:748)
                                                              at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:324)
                                                              at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readFormat(MediaCodecRenderer.java:489)
                                                              at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:472)
                                                              at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431)
                                                              at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:265)
                                                              at android.os.Handler.dispatchMessage(Handler.java:98)
                                                              at android.os.Looper.loop(Looper.java:148)
                                                              at android.os.HandlerThread.run(HandlerThread.java:61)
                                                              at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                           Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.amlogic.avc.decoder.awesome, Format(1, null, video/avc, -1, , null, [320, 900, -1.0], [-1, -1])
                                                              at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:359) 
                                                              at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:748) 
                                                              at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:324) 
                                                              at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readFormat(MediaCodecRenderer.java:489) 
                                                              at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:472) 
                                                              at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431) 
                                                              at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:265) 
                                                              at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                              at android.os.Looper.loop(Looper.java:148) 
                                                              at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                              at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 
                                                           Caused by: android.media.MediaCodec$CodecException: Failed to initialize OMX.amlogic.avc.decoder.awesome, error 0xfffffff4
                                                              at android.media.MediaCodec.native_setup(Native Method)
                                                              at android.media.MediaCodec.<init>(MediaCodec.java:1670)
                                                              at android.media.MediaCodec.createByCodecName(MediaCodec.java:1651)
                                                              at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:345)
                                                              at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:748) 
                                                              at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:324) 
                                                              at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readFormat(MediaCodecRenderer.java:489) 
                                                              at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:472) 
                                                              at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431) 
                                                              at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:265) 
                                                              at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                              at android.os.Looper.loop(Looper.java:148) 
                                                              at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                              at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 
04-20 06:00:46.308 3764-12290/? D/OmxComponent: getExtensionIndex 1091 name="OMX.google.android.index.getAndroidNativeBufferUsage"
04-20 06:00:46.309 19742-20099/? D/SurfaceUtils: set up nativeWindow 0xd7090808 for 1920x1088, color 0x11, rotation 0, usage 0x2002900
04-20 06:00:46.312 3764-4133/? D/OmxVideoDecoder: setParameter 544 0x2000001
04-20 06:00:46.312 3764-4133/? D/OmxVideoDecoder: newBufferCount = 8, outWidth=1920, outHeight=1088
04-20 06:00:46.312 3764-4133/? E/OmxVideoDecoder: set output error, new BufferCountActual = 8
04-20 06:00:46.312 3764-4133/? E/OMXNodeInstance: setParameter(a6:amlogic.avc.decoder.awesome, ParamPortDefinition(0x2000001)) ERROR: UnsupportedSetting(0x80001019)
04-20 06:00:46.312 19742-20099/? W/ACodec: [OMX.amlogic.avc.decoder.awesome] setting nBufferCountActual to 8 failed: -1010
04-20 06:00:46.312 3764-15885/? D/OmxVideoDecoder: setParameter 544 0x2000001
04-20 06:00:46.312 3764-15885/? D/OmxVideoDecoder: newBufferCount = 7, outWidth=1920, outHeight=1088
04-20 06:00:46.312 3764-15885/? E/OmxVideoDecoder: set output error, new BufferCountActual = 7
04-20 06:00:46.312 3764-15885/? E/OMXNodeInstance: setParameter(a6:amlogic.avc.decoder.awesome, ParamPortDefinition(0x2000001)) ERROR: UnsupportedSetting(0x80001019)
04-20 06:00:46.312 19742-20099/? W/ACodec: [OMX.amlogic.avc.decoder.awesome] setting nBufferCountActual to 7 failed: -1010
04-20 06:00:46.312 3764-3764/? D/OmxVideoDecoder: setParameter 544 0x2000001
04-20 06:00:46.312 3764-3764/? D/OmxVideoDecoder: newBufferCount = 6, outWidth=1920, outHeight=1088
04-20 06:00:46.312 3764-3764/? D/OmxVideoDecoder: setParameter mUseNativeBuffers=1
04-20 06:00:46.312 3764-3764/? W/OmxVideoDecoder: Can not read property media.omx.display_mode
04-20 06:00:46.312 3764-3764/? D/OmxVideoDecoder: workaround for dynamic buffer allocation, tWidth=1920, tHieght=1088
04-20 06:00:46.313 3764-3764/? D/OmxVideoDecoder: setParameter nPortIndex 1 nFrameWidth 1920 nFrameHeight 1088 nSliceHeight 1088
04-20 06:00:46.313 3764-3764/? V/OmxVideoDecoder: mUseNativeBuffers 1
04-20 06:00:46.313 3764-3764/? D/AmlogicVideoDecoderAwesome: get native buffer info NV:w:1920,h:1088..
04-20 06:00:46.313 3764-3764/? V/OmxVideoDecoder: updatePort:portDef.format.video.nFrameWidth=1920,portDef.format.video.nFrameHeight=1088
04-20 06:00:46.316 3764-4861/? D/OmxComponent: getExtensionIndex 1091 name="OMX.google.android.index.useAndroidNativeBuffer2"
04-20 06:00:46.316 3764-4861/? V/OmxVideoDecoder: mUseNativeBuffers 1
04-20 06:00:46.316 3764-4861/? D/AmlogicVideoDecoderAwesome: get native buffer info NV:w:1920,h:1088..
04-20 06:00:46.316 3764-4861/? V/OmxVideoDecoder: updatePort:portDef.format.video.nFrameWidth=1920,portDef.format.video.nFrameHeight=1088
04-20 06:00:46.316 3764-20102/? I/OmxComponent: STATE_TRANS: OMX_StateLoaded => OMX_StateIdle : OMX.amlogic.avc.decoder.awesome
04-20 06:00:46.319 3764-4860/? D/OmxComponent: getExtensionIndex 1091 name="OMX.google.android.index.useAndroidNativeBuffer2"
04-20 06:00:46.319 3764-4860/? V/OmxVideoDecoder: mUseNativeBuffers 1
04-20 06:00:46.319 3764-4860/? D/AmlogicVideoDecoderAwesome: get native buffer info NV:w:1920,h:1088..
04-20 06:00:46.319 3764-4860/? V/OmxVideoDecoder: updatePort:portDef.format.video.nFrameWidth=1920,portDef.format.video.nFrameHeight=1088
04-20 06:00:46.319 3764-20102/? I/OmxComponent: STATE_TRANS: OMX_StateLoaded => OMX_StateIdle : OMX.amlogic.avc.decoder.awesome
04-20 06:00:46.322 3764-9331/? D/OmxComponent: getExtensionIndex 1091 name="OMX.google.android.index.useAndroidNativeBuffer2"
04-20 06:00:46.322 3764-9331/? V/OmxVideoDecoder: mUseNativeBuffers 1
04-20 06:00:46.322 3764-9331/? D/AmlogicVideoDecoderAwesome: get native buffer info NV:w:1920,h:1088..
04-20 06:00:46.322 3764-9331/? V/OmxVideoDecoder: updatePort:portDef.format.video.nFrameWidth=1920,portDef.format.video.nFrameHeight=1088
04-20 06:00:46.322 3764-20102/? I/OmxComponent: STATE_TRANS: OMX_StateLoaded => OMX_StateIdle : OMX.amlogic.avc.decoder.awesome
04-20 06:00:46.325 3764-4157/? D/OmxComponent: getExtensionIndex 1091 name="OMX.google.android.index.useAndroidNativeBuffer2"
04-20 06:00:46.325 3764-4157/? V/OmxVideoDecoder: mUseNativeBuffers 1
04-20 06:00:46.325 3764-4157/? D/AmlogicVideoDecoderAwesome: get native buffer info NV:w:1920,h:1088..
04-20 06:00:46.325 3764-4157/? V/OmxVideoDecoder: updatePort:portDef.format.video.nFrameWidth=1920,portDef.format.video.nFrameHeight=1088
04-20 06:00:46.325 3764-20102/? I/OmxComponent: STATE_TRANS: OMX_StateLoaded => OMX_StateIdle : OMX.amlogic.avc.decoder.awesome
04-20 06:00:46.327 3764-12290/? D/OmxComponent: getExtensionIndex 1091 name="OMX.google.android.index.useAndroidNativeBuffer2"
04-20 06:00:46.327 3764-12290/? V/OmxVideoDecoder: mUseNativeBuffers 1
04-20 06:00:46.327 3764-12290/? D/AmlogicVideoDecoderAwesome: get native buffer info NV:w:1920,h:1088..
04-20 06:00:46.328 3764-12290/? V/OmxVideoDecoder: updatePort:portDef.format.video.nFrameWidth=1920,portDef.format.video.nFrameHeight=1088
04-20 06:00:46.328 3764-20102/? I/OmxComponent: STATE_TRANS: OMX_StateLoaded => OMX_StateIdle : OMX.amlogic.avc.decoder.awesome
04-20 06:00:46.330 3764-4133/? D/OmxComponent: getExtensionIndex 1091 name="OMX.google.android.index.useAndroidNativeBuffer2"
04-20 06:00:46.330 3764-4133/? V/OmxVideoDecoder: mUseNativeBuffers 1
04-20 06:00:46.330 3764-4133/? D/AmlogicVideoDecoderAwesome: get native buffer info NV:w:1920,h:1088..
04-20 06:00:46.330 3764-4133/? V/OmxVideoDecoder: updatePort:portDef.format.video.nFrameWidth=1920,portDef.format.video.nFrameHeight=1088
04-20 06:00:46.330 3764-20102/? I/OmxComponent: STATE_TRANS: OMX_StateLoaded => OMX_StateIdle : OMX.amlogic.avc.decoder.awesome
04-20 06:00:46.330 3764-20102/? V/AmlogicVideoDecoderAwesome: acquireResources:237 >
04-20 06:00:46.330 3764-20102/? D/AmlogicVideoDecoderAwesome: mVideoDisplay =0
04-20 06:00:46.330 3764-20102/? V/AmlogicVideoDecoderAwesome: enable osd or video__rm default,ret=0
04-20 06:00:46.331 3752-3752/? I/SystemControl: writeSysfs [ /sys/module/amvdec_h265/parameters/double_write_mode ] [ 16 ] from pid=3764, uid=1013, process name=/system/bin/mediaserver
04-20 06:00:46.331 19742-20098/? V/MediaCodec: output buffers allocated
04-20 06:00:46.331 3752-3774/? I/SystemControl: writeSysfs [ /sys/module/amvdec_vp9/parameters/double_write_mode ] [ 1 ] from pid=3764, uid=1013, process name=/system/bin/mediaserver
04-20 06:00:46.334 3764-20102/? V/AmlogicVideoDecoderAwesome: enable osd or video ...0
04-20 06:00:46.334 3752-10322/? I/SystemControl: writeSysfs [ /sys/module/amvdec_h265/parameters/buf_alloc_width ] [ 1920 ] from pid=3764, uid=1013, process name=/system/bin/mediaserver
04-20 06:00:46.335 3752-3752/? I/SystemControl: writeSysfs [ /sys/module/amvdec_h265/parameters/buf_alloc_height ] [ 1088 ] from pid=3764, uid=1013, process name=/system/bin/mediaserver
04-20 06:00:46.335 3752-3774/? I/SystemControl: writeSysfs [ /sys/module/amvdec_h265/parameters/dynamic_buf_num_margin ] [ 0 ] from pid=3764, uid=1013, process name=/system/bin/mediaserver
04-20 06:00:46.336 3752-10322/? I/SystemControl: writeSysfs [ /sys/module/amvdec_vp9/parameters/buf_alloc_width ] [ 1920 ] from pid=3764, uid=1013, process name=/system/bin/mediaserver
04-20 06:00:46.337 3752-3752/? I/SystemControl: writeSysfs [ /sys/module/amvdec_vp9/parameters/buf_alloc_height ] [ 1088 ] from pid=3764, uid=1013, process name=/system/bin/mediaserver
04-20 06:00:46.337 3764-20102/? V/AmlogicVideoDecoderAwesome: enable osd or video hevc ret_1=0, ret_2=0, ret_3=0
04-20 06:00:46.337 3764-20102/? V/debugSetup: media.omx.dumpRecv is disabled
04-20 06:00:46.337 3764-20102/? V/debugSetup: media.omx.dumpCodec is disabled
04-20 06:00:46.337 3764-20102/? V/AmlogicVideoDecoderAwesome: *Input Frame Rate is 0..
04-20 06:00:46.337 3764-20102/? V/AmlogicVideoDecoderAwesome:  videoDefine.xFramerate:0  
04-20 06:00:46.337 19742-20104/? I/OMXClient: Using client-side OMX mux.
04-20 06:00:46.359 3764-20102/? V/AmlogicVideoDecoderAwesome: mFlvFlag=0
04-20 06:00:46.359 3764-20102/? V/AmlogicVideoDecoderAwesome: mOutBufferCount =6
04-20 06:00:46.360 3764-20102/? V/AmlogicVideoDecoderAwesome: mIsNativeBuffers =1
04-20 06:00:46.363 3764-20102/? I/amvdec: amvideo_init ret=0
04-20 06:00:46.363 3764-20102/? D/AmlogicVideoDecoderAwesome: output buffer:mOutWidth:1920, mOutHeight:1088
04-20 06:00:46.363 3764-20102/? I/OmxComponent: STATE_DONE:  OMX_StateLoaded => OMX_StateIdle : OMX.amlogic.avc.decoder.awesome
04-20 06:00:46.366 3764-20102/? I/OmxComponent: OMX_CommandStateSet 706 Cmd 0 nParam1 0x3
04-20 06:00:46.366 3764-20102/? I/OmxComponent: STATE_SET:   OMX_StateIdle => OMX_StateExecuting : OMX.amlogic.avc.decoder.awesome
04-20 06:00:46.366 3764-20102/? V/AmlogicVideoDecoderAwesome: prepare:170 >
04-20 06:00:46.366 3764-20102/? D/AmlogicVideoDecoderAwesome: mVideo mDisplayTread start
04-20 06:00:46.366 3764-20102/? D/AmlogicVideoDecoderAwesome: mDTaskStatus=0
04-20 06:00:46.366 3764-20102/? V/AmlogicVideoDecoderAwesome: start:183 >
04-20 06:00:46.366 3764-20102/? D/AmlogicVideoDecoderAwesome: mVideo start
04-20 06:00:46.366 3764-20102/? I/OmxComponent: STATE_TRANS: OMX_StateIdle => OMX_StateExecuting : OMX.amlogic.avc.decoder.awesome
04-20 06:00:46.366 3764-20102/? I/OmxComponent: STATE_DONE:  OMX_StateIdle => OMX_StateExecuting : OMX.amlogic.avc.decoder.awesome
04-20 06:00:46.367 3764-20107/? V/OMX_WorkerPeer: hardware/amlogic/omx/omx_framework/WorkerPeer.cpp:runWorkerStatic:152 --------------------
04-20 06:00:46.367 3764-20107/? V/OMX_WorkerPeer: hardware/amlogic/omx/omx_framework/WorkerPeer.cpp:runWorker:158 --------------------
04-20 06:00:46.367 19742-19742/? I/System.out: ExoplayerPlayer State Changed=2
04-20 06:00:46.367 19742-19742/? I/System.out: ExoplayerPlayer Timeline=com.google.android.exoplayer2.source.SinglePeriodTimeline@dc9d913
04-20 06:00:46.368 19742-19742/? I/System.out: ExoplayerPlayer onLoading=true
04-20 06:00:46.371 3764-20107/? V/AmlogicVideoDecoderAwesome: doCodecSpec csd_len=32
04-20 06:00:46.375 3764-20107/? V/AmlogicVideoDecoderAwesome: doCodecSpec csd_len=8
04-20 06:00:46.445 19742-20104/? I/omx_core: OMX_Init 66 gInitCount=1
04-20 06:00:46.445 19742-20104/? V/AML_all_components: --------------------------------
                                                       ARCH = arm
                                                       author:aml.sh multi-media team
                                                       branch name:   * jb-mr1-amlogic
                                                       git version:   b213a219c424e302e749de15d9afb53572b478bb 
                                                       last changed:  Date: Wed Sep 14 11:40:11 2016 +0800
                                                       build-time:     Tue Sep 20 10:24:49 CST 2016
                                                       build-name:     yvonne.chen
                                                       uncommitted-file-num:1
                                                       cd /mnt/nfsroot/yvonne.chen/p212
                                                       hostname droid12-sz
                                                       --------------------------------
04-20 06:00:46.445 19742-20104/? V/OmxComponentManagerImpl: loadLibrary:258 Loading OMX library libOmxVideo.so.
04-20 06:00:46.446 19742-20104/? E/omx_video: amvenc_avc open failed!set default instance number as 1,ret=-1,Permission denied(13)
04-20 06:00:46.446 19742-20104/? I/omx_core: Core library has 14 components
04-20 06:00:46.446 19742-20104/? E/OMXMaster: A component of name 'OMX.google.h264.decoder' already exists, ignoring this one.
04-20 06:00:46.446 19742-20104/? E/OMXMaster: A component of name 'OMX.google.alac.decoder' already exists, ignoring this one.
04-20 06:00:46.455 19742-19742/? I/System.out: ExoplayerPlayer Timeline=com.google.android.exoplayer2.source.SinglePeriodTimeline@6c76750
04-20 06:00:46.455 19742-19742/? I/System.out: OnPositionDiscontinuity
04-20 06:00:46.455 19742-19742/? I/STORS: Error occured in sidepanel=com.google.android.exoplayer2.ExoPlaybackException

**Comment by andrewlewis** [comment]
There are a few existing issues about playing multiple videos at once (e.g. #1286). Please search existing issues before filing a new one.
