### ISSUE TITLE
HLS: Playback re-buffers when toggling audio/closed-caption tracks

### ISSUE THREAD

**Issue by ChmielowiecAlek** [google/ExoPlayer#2718]
### Description:
- playback hangs for ~3 seconds when switching Closed Captions on
- internally, a new SelectionOverride is used to enable Closed Captions by calling DefaultTrackSelector.setSelectionOverride
- the player goes through an additional buffering state

### Precondition:
- a high-bandwidth network connection has been established

### Reproduction steps:
- run ExoPlayer demo application
- select HLS and `Apple16x9 basic stream`
- the playback is fluent
- tap on the sceen to show buttons and press Text
- switch from Default to CEA-608 and press OK
- state changes to buffering and there is about 3 seconds long gap

### Expected result:
- Closed Captions do appear without disturbing the playback.

### Actual result:
- the playback is disturbed, re-buffering is performed.

### Link to test content
https://devimages.apple.com.edgekey.net/streaming/examples/bipbop_16x9/bipbop_16x9_variant.m3u8

### Version of ExoPlayer being used
r2.3.1

### Device(s) and version(s) of Android being used
- Huawei P8 lite (ALE-L21), Android 6.0, API 23
- Xiaomi MIBOX3m Android 6.0.1, API 23

### Logcat output captured from the device
[logcat_output.txt](https://github.com/google/ExoPlayer/files/950777/logcat_output.txt)

### Bugreport
- I will send it by email

**Comment by ojw28** [comment]
Yes. This was a compromise we made deliberately in V2. We're aware it's annoying, but the way we used to achieve no disruption was technically incorrect for several reasons. We do plan to optimize it again in the future.

**Comment by ojw28** [comment]
Addressed in https://github.com/google/ExoPlayer/commit/06b3b3ca8d8ee807008e1cbd5d94c6de5cf96df0 in `dev-v2`.
