### ISSUE TITLE
getting error on line while import some exoplayer class

### ISSUE THREAD

**Issue by Pash97** [google/ExoPlayer#2719]
am importing compile 'com.google.android.exoplayer:exoplayer:r1.5.2' in my gradle

but giving error on while 

import com.google.android.exoplayer.MediaCodecSelector;
import com.google.android.exoplayer.hls.DefaultHlsTrackSelector;
import com.google.android.exoplayer.hls.PtsTimestampAdjusterProvider;

It giving me can not resolve  MediaCodecSelector,DefaultHlsTrackSelector,PtsTimestampAdjusterProvider.

**Comment by ojw28** [comment]
The classes you're trying to import don't exist in release 1.5.2, so that's expected. You can only use classes that actually exist in the version of ExoPlayer you're using. Why are you using such an old version?

**Comment by Pash97** [comment]
Because other release giving error
following is my code with r1.5.15 for HpLib_HlsHpLibRendererBuilder please help 

import android.content.Context;
import android.media.MediaCodec;
import android.os.Handler;

import com.google.android.exoplayer.DefaultLoadControl;
import com.google.android.exoplayer.LoadControl;
import com.google.android.exoplayer.MediaCodecAudioTrackRenderer;
import com.google.android.exoplayer.MediaCodecSelector;
import com.google.android.exoplayer.MediaCodecVideoTrackRenderer;
import com.google.android.exoplayer.TrackRenderer;
import com.google.android.exoplayer.hls.DefaultHlsTrackSelector;
import com.google.android.exoplayer.hls.HlsChunkSource;
import com.google.android.exoplayer.hls.HlsMasterPlaylist;
import com.google.android.exoplayer.hls.HlsPlaylist;
import com.google.android.exoplayer.hls.HlsPlaylistParser;
import com.google.android.exoplayer.hls.HlsSampleSource;
import com.google.android.exoplayer.hls.PtsTimestampAdjusterProvider;
import com.google.android.exoplayer.upstream.DataSource;
import com.google.android.exoplayer.upstream.DefaultAllocator;
import com.google.android.exoplayer.upstream.DefaultBandwidthMeter;
import com.google.android.exoplayer.upstream.DefaultUriDataSource;
import com.google.android.exoplayer.util.ManifestFetcher;

import java.io.IOException;

//import com.google.android.exoplayer.MediaCodecSelector;
//import com.google.android.exoplayer.hls.DefaultHlsTrackSelector;
//import com.google.android.exoplayer.hls.PtsTimestampAdjusterProvider;

public class HpLib_HlsHpLibRendererBuilder implements HpLib_RendererBuilder{

    private static final int BUFFER_SEGMENT_SIZE = 64 * 1024;
    private static final int MAIN_BUFFER_SEGMENTS = 254;
    private static final int AUDIO_BUFFER_SEGMENTS = 54;
    private static final int TEXT_BUFFER_SEGMENTS = 2;
    private final Context context;
    private final String userAgent;
    private final String url;
    private AsyncRendererBuilder currentAsyncBuilder;
    public HpLib_HlsHpLibRendererBuilder(LiveChannels player, String userAgent, String video_url) {
        this.context = player;
        this.userAgent = userAgent;
        this.url = video_url;
    }
    @Override
    public void buildRenderers(LiveChannels player) {
        currentAsyncBuilder = new AsyncRendererBuilder(context, userAgent, url, player);
        currentAsyncBuilder.init();
    }

    @Override
    public void cancle() {
        if (currentAsyncBuilder != null) {
            currentAsyncBuilder.cancel();
            currentAsyncBuilder = null;
        }
    }
    private static final class AsyncRendererBuilder implements ManifestFetcher.ManifestCallback<HlsPlaylist> {
        private final Context context;
        private final String userAgent;
        private final String url;
        private final LiveChannels player;
        private final ManifestFetcher<HlsPlaylist> playlistFetcher;
        private boolean canceled;

        public AsyncRendererBuilder(Context context, String userAgent, String url, LiveChannels player) {
            this.context = context;
            this.userAgent = userAgent;
            this.url = url;
            this.player = player;
            HlsPlaylistParser parser = new HlsPlaylistParser();
            playlistFetcher = new ManifestFetcher<>(url, new DefaultUriDataSource(context, userAgent),
                    parser);
        }

        public void init() {
            playlistFetcher.singleLoad(player.getMainHandler().getLooper(), this);
        }

        public void cancel() {
            canceled = true;
        }
        @Override
        public void onSingleManifestError(IOException e) {
            if (canceled) {
                return;
            }

            player.onRenderersError(e);
        }
        @Override
        public void onSingleManifest(HlsPlaylist manifest) {
            if (canceled) {
                return;
            }
            Handler mainHandler = player.getMainHandler();
            LoadControl loadControl = new DefaultLoadControl(new DefaultAllocator(BUFFER_SEGMENT_SIZE));
            DefaultBandwidthMeter bandwidthMeter = new DefaultBandwidthMeter();
            PtsTimestampAdjusterProvider timestampAdjusterProvider = new PtsTimestampAdjusterProvider();
            boolean haveSubtitles = false;
            boolean haveAudios = false;
            if (manifest instanceof HlsMasterPlaylist) {
                HlsMasterPlaylist masterPlaylist = (HlsMasterPlaylist) manifest;
                haveSubtitles = !masterPlaylist.subtitles.isEmpty();

            }
            // Build the video/id3 renderers.
            DataSource dataSource = new DefaultUriDataSource(context, bandwidthMeter, userAgent);
            HlsChunkSource chunkSource = new HlsChunkSource(true /* isMaster */, dataSource, manifest,
                    DefaultHlsTrackSelector.newDefaultInstance(context), bandwidthMeter,
                    timestampAdjusterProvider, HlsChunkSource.ADAPTIVE_MODE_SPLICE);
            HlsSampleSource sampleSource = new HlsSampleSource(chunkSource, loadControl,
                    MAIN_BUFFER_SEGMENTS * BUFFER_SEGMENT_SIZE, mainHandler, player, LiveChannels.TYPE_VIDEO);
            MediaCodecVideoTrackRenderer videoRenderer = new MediaCodecVideoTrackRenderer(context, sampleSource,
                    MediaCodecSelector.DEFAULT, MediaCodec.VIDEO_SCALING_MODE_SCALE_TO_FIT);
            MediaCodecAudioTrackRenderer audioRenderer = new MediaCodecAudioTrackRenderer(sampleSource,MediaCodecSelector.DEFAULT);


            TrackRenderer[] renderers = new TrackRenderer[2];
            renderers[0] = videoRenderer;
            renderers[1] = audioRenderer;
            //renderers[2] = textRenderer;
            player.onRenderers(renderers, bandwidthMeter);

        }

    }

}

**Comment by ojw28** [comment]
If you want help please provide a clear description of the problem. Just saying that it gives an error is not enough information for us to help.

**Comment by Pash97** [comment]
Well,

am using exoplayer compile 'com.google.android.exoplayer:exoplayer:r1.5.15' in my project gradle

While including this release am getting following error those i have mentioned in comment in my code am new in exoplayer, Please check it out

class HpLib_HlsHpLibRendererBuilder implements HpLib_RendererBuilder {
    private static final int BUFFER_SEGMENT_SIZE = 64 * 1024;
    private static final int MAIN_BUFFER_SEGMENTS = 254;
    private static final int AUDIO_BUFFER_SEGMENTS = 54;
    private static final int TEXT_BUFFER_SEGMENTS = 2;
    private final Context context;
    private final String userAgent;
    private final String url;
    private AsyncRendererBuilder currentAsyncBuilder;

    public HpLib_HlsHpLibRendererBuilder(LiveChannels player, String userAgent, String video_url) {
        this.context = player;
        this.userAgent = userAgent;
        this.url = video_url;
    }
    @Override
    public void buildRenderers(LiveChannels player) {
        currentAsyncBuilder = new AsyncRendererBuilder(context, userAgent, url, player);
        currentAsyncBuilder.init();
    }

    @Override
    public void cancle() {
        if(currentAsyncBuilder != null)
        {
            currentAsyncBuilder.cancel();
            currentAsyncBuilder = null;
        }
    }
    @Override
    public void cancel() {
        if (currentAsyncBuilder != null) {
            currentAsyncBuilder.cancel();
            currentAsyncBuilder = null;
        }
    }


    private static final class AsyncRendererBuilder implements ManifestFetcher.ManifestCallback<HlsPlaylist> { //Class 'AsyncRendererBuilder' must either be declared abstract or implement abstract method 'onManifest(String, T)' in 'ManifestCallback
        private final Context context;
        private final String userAgent;
        private final String url;
        private final LiveChannels player;
        private final ManifestFetcher<HlsPlaylist> playlistFetcher;
        private boolean canceled;
        public AsyncRendererBuilder(Context context, String userAgent, String url, LiveChannels player) {
            this.context = context;
            this.userAgent = userAgent;
            this.url = url;
            this.player = player;
            HlsPlaylistParser parser = new HlsPlaylistParser();
            playlistFetcher = new ManifestFetcher<>(url, new DefaultUriDataSource(context, userAgent),
                    parser);
        }
        public void init() {
            playlistFetcher.singleLoad(player.getMainHandler().getLooper(), this);//Can not resolve method 'singleLoad(android.os.Looper, com.example.pash.drm.HpLib_HlsHpLibRendererBuilder.AsyncRendererBuilder)
        }
        public void cancel() {
            canceled = true;
        }
        @Override//Method does not override method from its superclass
        public void onSingleManifestError(IOException e) {
            if (canceled) {
                return;
            }

            player.onRenderersError(e);
        }
        @Override //Method does not override method from its superclass
        public void onSingleManifest(HlsPlaylist manifest) {
            if (canceled) {
                return;
            }
            Handler mainHandler = player.getMainHandler();
            LoadControl loadControl = new DefaultLoadControl(new DefaultAllocator(BUFFER_SEGMENT_SIZE));
            DefaultBandwidthMeter bandwidthMeter = new DefaultBandwidthMeter();
            PtsTimestampAdjusterProvider timestampAdjusterProvider = new PtsTimestampAdjusterProvider();

            boolean haveSubtitles = false;
            boolean haveAudios = false;
            if (manifest instanceof HlsMasterPlaylist) {
                HlsMasterPlaylist masterPlaylist = (HlsMasterPlaylist) manifest;
                haveSubtitles = !masterPlaylist.subtitles.isEmpty();

            }
            // Build the video/id3 renderers.
            DataSource dataSource = new DefaultUriDataSource(context, bandwidthMeter, userAgent);
            HlsChunkSource chunkSource = new HlsChunkSource(true /* isMaster */, dataSource, manifest,
                    DefaultHlsTrackSelector.newDefaultInstance(context), bandwidthMeter,
                    timestampAdjusterProvider, HlsChunkSource.ADAPTIVE_MODE_SPLICE);    //Can not resolve ADAPTIVE_MODE_SPLICE
            HlsSampleSource sampleSource = new HlsSampleSource(chunkSource, loadControl,
                    MAIN_BUFFER_SEGMENTS * BUFFER_SEGMENT_SIZE, mainHandler, player, LiveChannels.TYPE_VIDEO);
            MediaCodecVideoTrackRenderer videoRenderer = new MediaCodecVideoTrackRenderer(context, sampleSource,
                    MediaCodecSelector.DEFAULT, MediaCodec.VIDEO_SCALING_MODE_SCALE_TO_FIT);//MediaCodecVideoTrackRenderer  in MediaCodecVideoTrackRenderer cannot be applied to 
            MediaCodecAudioTrackRenderer audioRenderer = new MediaCodecAudioTrackRenderer(sampleSource,
                    MediaCodecSelector.DEFAULT);

            TrackRenderer[] renderers = new TrackRenderer[2];
            renderers[0] = videoRenderer;
            renderers[1] = audioRenderer;
            //renderers[2] = textRenderer;
            player.onRenderers(renderers, bandwidthMeter);

        }
    }
}

**Comment by ojw28** [comment]
There is insufficient information here for us to help. When using 1.5.2 the errors you see are working as intended, because the classes you're trying to import don't exist. When using 1.5.15 you haven't provided a clear description of the errors you see. It sounds like your code is just broken, and debugging your code is beyond the scope of this issue tracker.

I'd suggest you take a look at the ExoPlayer demo app, which does compile and which you can find for r1.5.15 [here](https://github.com/google/ExoPlayer/tree/r1.5.15/demo). Perhaps using that as the starting point for your project would be a good idea.

As an aside, we'd strongly recommend using the latest ExoPlayer V2 release (r2.3.1) over ExoPlayer V1.
