### ISSUE TITLE
Video stuck on Nexus 10 Android 4.4.4 and 5.1.1

### ISSUE THREAD

**Issue by pi-andrei** [google/ExoPlayer#2722]
### Issue description
Video picture stuck after starting Dash playback on 15th-19th frame on Samsung Nexus 10 tablet Android 4.4.4/5.1.1 with specific video: http://media.axprod.net/TestVectors/v7-Clear/Manifest_1080p.mpd . Tried 2 different Nexus 10 devices. In general video continues to play, audio can be heard and subtitles are updated, but video shows same one frame. Also after trying to seek video, state "ExoPlayer.STATE_READY" event never dispatched after "ExoPlayer.STATE_BUFFERING" state. No error messages appear in device logs. Video plays normally on other devices.

Expected behaviour: Video never stuck and continues to play. After seeking player should receive ExoPlayer.STATE_READY after ExoPlayer.STATE_BUFFERING.

### Reproduction steps
1. Add video "http://media.axprod.net/TestVectors/v7-Clear/Manifest_1080p.mpd" to media.exolist.json file
2. Open ExoPlayer 2.3.1 sample App
3. Try to play added video

### Link to test content
http://media.axprod.net/TestVectors/v7-Clear/Manifest_1080p.mpd

### Version of ExoPlayer being used
2.3.1

### Device(s) and version(s) of Android being used
Samsung Nexus 10 tablet Android 4.4.4 and 5.1.1
Reproducible every time

### A full bug report captured from the device
sent by e-mail

**Comment by ojw28** [comment]
Did you try updating the Nexus 10 to Android 5.1? Whilst it would be good to avoid this issue on Nexus 10s that haven't taken the Lollipop update, it's obviously much lower priority if the issue has been fixed in the platform. The vast majority of Nexus 10s in the wild have taken the Android 5.1 update, and of course users who haven't taken it can opt to do so.

**Comment by pi-andrei** [comment]
Hello, thank you for reply. Device now updated to 5.1.1 and problem still exists. I sent you new bugreport log by e-mail.

**Comment by ojw28** [comment]
I'm able to reproduce this, but it doesn't seem particularly easy to debug what's going wrong. It seems specific to the content, or at least the way that the content has been encoded. I'm not saying it's not encoded correctly, I'm saying that many other streams do play correctly. It's unlikely we'll be able to allocate resources to look at this in the near term.

**Comment by pi-andrei** [comment]
Thanks. Then I have nothing to do but wait. Hope you will find time to fix this in future.

**Comment by ojw28** [comment]
Closing as we're not going to be able to allocate resources to look at this. The device is also over 6 years old at this point.
