### ISSUE TITLE
how to get control views dynamically?

### ISSUE THREAD

**Issue by or-dvir** [google/ExoPlayer#2724]
**- Search existing issues, including issues that are closed.**
only post i found kind of related to this issue was [https://github.com/google/ExoPlayer/issues/2529](url) , but the owner of the post claims that his problem is about switching between layouts. therefore i am opening a new issue. if you think that i should post this question on the above post, please let me know and i'll do so.

**- Consult our FAQs, supported devices and supported formats pages.**
i have looked through the documentation and could not find what i was looking for.

### Issue description
i have an xml file named "exo_playback_control_view.xml" so that SimpleExoPlayer will inflate it instead of the default controllers. what i would like to do though, is set some parameters of these views at runtime (specifically set an image which is stored on our server) and i cannot find a way to access these views (i didn't find any method like "getPauseView()" or "getPreviousView()" etc...).
did i miss something? is there a way for me to get a reference to these view objects so i can manipulate them at runtime (e.g. set an image from a server)?
i would highly prefer not write my own custom controllers from scratch because i would like to keep most of the default out-of-the-box behavior (which is very convenient!).
if there is no such way to get those references, please consider adding this feature in your next release.

### Version of ExoPlayer being used
2.3.1

**Comment by ojw28** [comment]
Can't you just use `view.findViewById`? For example `view.findViewById(R.id.exo_play)`?

**Comment by or-dvir** [comment]
@ojw28 i would very much like to use findViewById(). question is on what view will i call it?
since the inflation of "exo_playback_control_view.xml" is done internally, i need access to view which was created by the inflation and i can't find how to get a reference to it.

would i call it on my instance of SimpleExoPlayerView like `mySimpleExoPlayerView.findViewById(R.id.my_play_button)`?
the thing is i don't know if the internal view infalted from "exo_playback_control_view.xml" is being added to the same tree as the SimpleExoPlayerView, or it's a separate component which is simply displayed on top of it (for example using a fragment on top of the SimpleExoPlayerView layout).

if the former is correct (the inflated view is added to the same tree as SimpleExoPlayerView) then that would be great and the problem is solved by this line: `mySimpleExoPlayerView.findViewById(R.id.my_play_button)`.
if the latter is correct (the inflated view is kept separate and simply displayed on top of the SimpleExoPlayerView), then what view should i call findViewById on?

**Comment by ojw28** [comment]
You should be able to call it on the `SimpleExoPlayerView` instance? I'm pretty sure findViewById() searches the whole view hierarchy. You should even be able to do it on the root view of your whole activity once the `SimpleExoPlayerView` is inflated and attached (although if you have multiple such views in the hierarchy then you'd want to be more specific so you know which view you're going to find, and also starting further down the hierarchy is obviously more efficient).

**Comment by or-dvir** [comment]
@ojw28 i was writing/editing my previous comment while you posted your second answer and only saw your second comment now...
so just to make sure, the internally inflated view is **being added to the same tree** as SimpleExoPlayerView and i can simply call `mySimpleExoPlayerView.findViewById(R.id.my_play_button)`?

**Comment by ojw28** [comment]
Yes, the views are inflated into the SimpleExoPlayerView.

**Comment by or-dvir** [comment]
@ojw28 thanks for the clarification!
