### ISSUE TITLE
Does ExoPlayer plan to support HLS I-Frame Playlists?

### ISSUE THREAD

**Issue by PiotrWozniakSC** [google/ExoPlayer#2725]
In the question of HLS I-Frame Playlist (https://developer.apple.com/library/content/technotes/tn2288/_index.html#//apple_ref/doc/uid/DTS40012238-CH1-I_FRAME_PLAYLIST) support in ExoPlayer I couldn't find a definitive answer. The only thing I found is that there was some work in progress (https://github.com/google/ExoPlayer/issues/474) some time ago, but there's no indication whether it was / will be finished and when. I have done some tests of my own, feeding a sample I-Frame Playlist (from this project: https://github.com/pbs/iframe-playlist-generator) to ExoPlayer demo app (from r2.3.1), and it seems that ExoPlayer does not support that as of now - I got an error: "Failed to parse the playlist, could not identify any tags.", which suggests that ExoPlayer can't parse the I-Frame Playlist tags, e.g. the EXT-X-I-FRAME-STREAM-INF tag.

So the question is: is there a plan to support HLS I-Frame Playlists in ExoPlayer? And if so, when could that be expected?

**Comment by AquilesCanta** [comment]
Not yet supported, unfortunately. There was no plan either, but seeing increasing interest on this we might get to it. I cannot make any promises regarding the when. I will post any updates in #474.
