### ISSUE TITLE
DRM Challenge

### ISSUE THREAD

**Issue by steff-maya** [google/ExoPlayer#2727]
it's possible to create a key Challenge  for play a protected video with DRM  , i'm workin with  "theplatform"  and i need to pass a Challenge and the documentations says that its create by client 

"getWidevineLicense": {
    "releasePid": "xxXXXxx",
    "widevineChallenge": "Adlkejk="    
  }

**Comment by ojw28** [comment]
There are examples of playing Widevine protected content in the demo app, so that should be a good starting point.

It's a little unclear what this question is about, however. There's not really enough information or context (e.g. a link to the content you're trying to play) for us to assist.
