### ISSUE TITLE
 Time position BEFORE a playback jump in onPositionDiscontinuity() 

### ISSUE THREAD

**Issue by u2gilles** [google/ExoPlayer#2728]
AFTER a playback position jump (the user moves the seekbar), onPositionDiscontinuity() is called and :
- getCurrentWindowIndex() gives the window index AFTER the jump
- getCurrentPosition() gives the time position AFTER the jump.

Fine. But I also need the time position and window index BEFORE the jump. How can I retrieve these information?

The reason I need it is because I want to save the time position of each video when the user presses the NEXT and PREVIOUS video buttons back and forth. For example, if the user presses NEXT in the middle of Video2 then presses PREVIOUS, video2 won't start from the beginning as it is the case in the default implemenation.

Thanks and kind regards.
Gilles

**Comment by ojw28** [comment]
This is not currently supported. Marking as an enhancement, but it's unlikely to be treated with any high level of priority.

**Comment by u2gilles** [comment]
Thanks for you answer. I anticipated this answer so I put my treatment in OnClickListener of exo_prev and exo_next buttons  instead. It works fine.

**Comment by ojw28** [comment]
Yes, that should work. I think I'll close this in that case; it seems easy enough to support on the application side rather than as a player feature.

**Comment by u2gilles** [comment]
Ok. Thanks for prompt answers.

2017-04-28 16:33 GMT+07:00 ojw28 <notifications@github.com>:
