### ISSUE TITLE
Failed to resolve: com.google.android.exoplayer:exoplayer-core:r2.4.0

### ISSUE THREAD

**Issue by sergejsha** [google/ExoPlayer#2731]
Guys, I am trying to upgrade to latest version 2.4.0

`compile "com.google.android.exoplayer:exoplayer-core:r2.4.0"`

 and getting the error:

`Failed to resolve: com.google.android.exoplayer:exoplayer-core:r2.4.0`

Changing back to 2.3.1 compiles just fine. Should I wait until the artifacts get synchronized on jcenter or is there an issue with the release? Thanks!

**Comment by ojw28** [comment]
We're just waiting for Bintray to link the new modules to jCenter, which appears to be at least a semi-manual process. The issue should be resolved once they do this. They're normally pretty quick, so hopefully this will be fixed pretty soon!

**Comment by sergejsha** [comment]
Ok, thanks!

**Comment by ojw28** [comment]
Leaving open until linked so others can find the answer more easily.

**Comment by b95505017** [comment]
Ok we got everything we need. :)
https://jcenter.bintray.com/com/google/android/exoplayer/

**Comment by sergejsha** [comment]
Yes, everything compiles just fine. Thanks awesome release!

**Comment by muafakul** [comment]
i am still PROBLEM ,, the problem is how to do that ?
