### ISSUE TITLE
support multiple window play?

### ISSUE THREAD

**Issue by 13217300237** [google/ExoPlayer#2734]
Do you support multiple window play
I don't see multiple window in the demo, but I see a lot of cal lof  getCurrentWindowIndex() in codes.like 
![image](https://cloud.githubusercontent.com/assets/16287718/25464546/89307c0e-2b2f-11e7-9d1b-ae764473f662.png)

**Comment by ojw28** [comment]
Windows in this context are described [here](http://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/Timeline.html). If you're asking about playing multiple videos at once in different windows on screen, or something like that, then the code you've highlighted is unrelated. You haven't provided a clear description of what you're actually trying to do, so it's not possible for us to assist further.
