### ISSUE TITLE
Exoplayer stops when phone sleep

### ISSUE THREAD

**Issue by Karthikg206** [google/ExoPlayer#2738]
1. My Exoplayer 2  stops playing when phone getting automatic sleep?

2. MediaPlayer.setWakeMode(getApplicationContext(), PowerManager.PARTIAL_WAKE_LOCK);
like any functions in Exoplayer 2 ?

**Comment by ojw28** [comment]
Please see our [FAQs](https://google.github.io/ExoPlayer/faqs.html#how-do-i-keep-audio-playing-when-my-app-is-backgrounded).
