### ISSUE TITLE
Unable to play Some Videos 

### ISSUE THREAD

**Issue by bhupendra03** [google/ExoPlayer#2739]
Hi, 
I am using SimpleExoPlayer with playback support and using demo_speed app getting this error on some video.

Below is the link of video - : https://s3-eu-west-1.amazonaws.com/pvi-cloud/31013/1b514875-28b2-469c-a65d-2c92061fdef1/PVVideo1-000000693034.mp4

java.lang.NullPointerException: Attempt to invoke interface method 'long com.google.android.exoplayer2.util.MediaClock.getPositionUs()' on a null object reference                                                                                          at com.google.android.exoplayer2.ExoPlayerImplInternal.updatePlaybackPositions(ExoPlayerImplInternal.java:437)                                                                                          at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:471)                                                                                          at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:310)                                                                                          at android.os.Handler.dispatchMessage(Handler.java:98)                                                                                          at android.os.Looper.loop(Looper.java:148)                                                                                          at android.os.HandlerThread.run(HandlerThread.java:61)                                                                                          at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)

**Comment by ojw28** [comment]
Does this reproduce in the ExoPlayer demo app? And are you using custom renderers of some kind?
 Also, please properly fill out the issue template. If you don't provide the information we request, we're less likely to be able to help.

**Comment by bhupendra03** [comment]
@ojw28  I am using demo_speed app.

**Comment by ojw28** [comment]
We don't provide anything called demo_speed, as far as I know.

**Comment by ojw28** [comment]
It looks like you're using https://github.com/yangwuan55/ExoPlayer. This is an unofficial fork and is not controlled by us. It looks like the bug is specific to modifications that have been made on that fork. I'd suggest using official versions only.

Note that ExoPlayer supports changes to playback speed directly as of `2.4.0`, as described [here](https://medium.com/google-exoplayer/variable-speed-playback-with-exoplayer-e6e6a71e0343).
