### ISSUE TITLE
ANR/Unresponsiveness when releasing player whilst it buffers (FrameworkSampleSource).

### ISSUE THREAD

**Issue by ojw28** [google/ExoPlayer#274]
This is a known issue, tracked by a TODO here:
https://github.com/google/ExoPlayer/blob/dev/library/src/main/java/com/google/android/exoplayer/FrameworkSampleSource.java#L34

**Comment by wingoku** [comment]
@ojw28 I have the same issue on MediaPlayer as well. The video format is .mp4. 

Weird Fact:

Note 3: When I seek the video to unbuffered/buffered position, whether mediaPlayer.isPlaying() == true or false, the app/UI remains responsive.

Nexus 5: When I seek, the seek bar remains responsive but rest of the buttons becomes unresponsive, if the mediaPlayer.isPlaying() was true at the time of seeking but if I seek the video when the mediaPlayer.isPlaying == false, the UI becomes unresponsive.

Any solution to resolve this problem? I am using MediaController with SurfaceView.

**Comment by ojw28** [comment]
Yes, it's a known issue with MediaPlayer also. It's a property of the underlying threading model, which is less than ideal. We can/will work around it in the ExoPlayer case. Although to do so involves non-trivial thread hopping, and we haven't gotten around to it yet.

**Comment by AshtonEngberg** [comment]
Any updates on this? Having the scenario where the user loads a video and then navigates away is not uncommon; producing random ANR's is almost preventing use of this wonderful library.

**Comment by ojw28** [comment]
We've been adding alternative extractors to cover off the most common use cases (mp3, mp4, aac will land very soon). Depending on your use case, you may be able to switch to those if you're on the dev branch. If you have no idea what the container type of the content you're playing is going to be then these wont help (yet).

**Comment by ojw28** [comment]
It should also be noted that the Android MediaPlayer implementation suffers from the same ANR issue in some cases, so if that's what you're using instead, it's unclear whether it would even be a regression to switch over to a library that has the same problem.

**Comment by AshtonEngberg** [comment]
For mp4 could you point me to which classes? I'm still not as familiar with the source base yet as I'd like to be, thanks! Android MediaPlayer was dropped entirely since Exoplayer handles live streams and handles static (mp4) much better.

**Comment by ojw28** [comment]
FrameworkSampleSource is deprecated and its replacement ExtractorSampleSource can now be used in nearly all cases instead (on the dev branch at least).
