### ISSUE TITLE
when in service play music, setPlayWhenReady(false) is not work

### ISSUE THREAD

**Issue by huyongli** [google/ExoPlayer#2747]
### Issue description
i play mp3  music in a background service,  i use setPlayWhenReady(false) to pause, but it not work. But it work well then i try in activity
service is foreground service, and i create the SimpleExoPlayer in this service not in activity.

### Reproduction steps
Create SimpleExoPlayer in this service not in activity, and play mp3 music , try pause music by setPlayWhenReady(false), it not work 

### Version of ExoPlayer being used
r2.4.0

### Device(s) and version(s) of Android being used
100% reproduce

HW  PLK-AL10（6.0）

**Comment by huyongli** [comment]
i resolve it

**Comment by Khoosham** [comment]
@huyongli  can you post your service sample here. Thank you
