### ISSUE TITLE
HLS: Add factory for Extractors

### ISSUE THREAD

**Issue by IanDBird** [google/ExoPlayer#2748]
In ExoPlayer v2, the `HlsMediaChunk` class is responsible for constructing what extractor is required for a given format (`createExtractor`). This means that HLS handling is tightly coupled to what extractors are used.

Since applications are capable of creating their own extractors (e.g. their own `TsExtractor`) it would be useful to allow these to be passed into the HLS implementation to be used. This would require the `HlsMediaSource` accepting an extractor factory which could then be created by the application.

**Comment by stari4ek** [comment]
this is the only way to bypass `FLAG_ALLOW_NON_IDR_KEYFRAMES`, `FLAG_DETECT_ACCESS_UNITS` which can be required for some HLS streams.
`HlsMediaChunk` does not provide any other easy way to extend. It's final and pretty complex to provide own variant

**Comment by AquilesCanta** [comment]
Please give it a try and let us know if it works for you.
