### ISSUE TITLE
Detect adaptive playback changes in bandwidth?

### ISSUE THREAD

**Issue by indieocean** [google/ExoPlayer#275]
Is there a way to detect HLS adaptive playback changes e.g. bandwidth? 

We want to be able to detect when the source has changed in order to show SD, HD, Ultra HD Icons in the User Interface. We are having problems with users complaining that content is not in HD but we know its because of their bandwidth.

**Comment by ojw28** [comment]
Not right now. We need to add something to HlsSampleSource equivalent to ChunkSampleSource's Listener (which has onDownstreamFormatChanged for this purpose).

**Comment by indieocean** [comment]
Thanks! This would be a +1

**Comment by jeoliva** [comment]
Hi ojw28,

I created a new branch in my repo that implements events in HlsSampleSource (https://github.com/jeoliva/ExoPlayer/commit/95906f27387dc9e045bdc41e87bbf74743a8bf35). I tried to support exactly the same events supported right now in ChunkSampleSource although there are minimum differences that comes from differences in the media protocol used (for example, in HLS doesn't make sense having an Id identifying a format. We could "simulate" this using bandwidth or variant index as a string, but that's another story). 

The problem that I see with this is, there are some collisions with the name of the methods used for HlsSampleSource.EventsListener class and the methods used in ChunkSampleSource.EventsListener. It could be fixed easily just renaming the methods in HlsSampleSource.EventsListener or making them to have exactly the same parameters than the ones used in ChunkSampleSource (even although there will be some parameters no used) but before doing any of these things I would like to ask you a question: do you have any future plan (or are currently working on this) regarding making HlsSampleSource to be integrated in ChunkSampleSource or inheriting from it?

**Comment by ojw28** [comment]
Sorry for the delayed response. Yes, there is a plan to converge the HLS and DASH/SmoothStreaming implementations (we'll probably be converging onto the HLS model, rather than the other way around). It's pretty complicated to get everything to line up to actually do this, but I've done some experimental work and it looks promising.

In the meantime, I think we'd take a minimal patch to report quality switches out of HlsSampleSource (maybe one that just reports the selected bandwidth, and nothing else). Alternatively, you can just wait or patch locally to your requirements.

**Comment by ojw28** [comment]
FYI, https://github.com/google/ExoPlayer/commit/5ca2e0fd95d580df34599c84b37f9e1e4f49da87 is the first change towards the convergence of HLS and DASH/SmoothStreaming.

**Comment by jeoliva** [comment]
Perfect, many thanks for the info!

**Comment by ojw28** [comment]
This is supported in dev.

**Comment by crossle** [comment]
https://github.com/google/ExoPlayer/issues/345, if support manual switch video quality, will cool
