### ISSUE TITLE
Some HLS / DASH live contents stop working when change level on skipper

### ISSUE THREAD

**Issue by Gian84** [google/ExoPlayer#2750]
Hi,
I’m using skipper (http://www.technicolor.com/en/solutions-services/connected-home/video-devices/ott-set-top-boxes/skipper, http://www.telecomitalia.com/tit/en/archivio/media/note-stampa/market/2016/TIM-nuovo-decoder-TimVision-Android.html), it should be a supported device.
Android version is 6.0.1
I’m using Exoplayer demo app 2.3.1.

On skipper I have tried different content types (DASH, HLS,..), live or vod and clear or key-protected and they work correctly.

Unfortunately some HLS / DASH live contents stop working when change level. It freezes video track only.
In particular it seems that the content stop working when scale to a particular level, I don’t know if it depends on bitrate or on resolution.

Assuming resolution as “guilty” param and taking in account an HLS content, it seems that stop working when the level go to [1280*720].
Some cases as sample:
1. [640x360] -> [1280x720] -> [1920x1080] -> KO
2. [1280x720] -> [1920x1080] -> KO
3. [640x360] -> [1920x1080] -> OK

Assuming resolution as “guilty” param and taking in account a DASH content, it seems that stop working when the level go to bitrate=5000000.

I get the same beahviour with an h265 dash content.

The same contents work fine on different mobile devices Android (I have changed model and Android version)

I have sent an email (same title as object) where you can find a demo url, logs and bugreport.

Let me know if you need further informations.

**Comment by tonihei** [comment]
Closed the issue because it was either answered or we never received the information. Feel free to re-open if this is not the case.
