### ISSUE TITLE
Start volume problem

### ISSUE THREAD

**Issue by Merseyside** [google/ExoPlayer#2752]
I wrote you about two month ago. I got a problem with volume. I try to set it in 0 before playback starts. But when its ready it do not work as expected: for ~0.2 second it is loud and after that it becomes quiet. I got an  application on Google play. It is easy to reproduce:
1. Go to settings -> Sound -> Set crossfade for example to 10000ms, also turn on Crossfade fading option.
2. In folders or playlists add at least two tracks.
3. Start playing and wait for 'Track Duration' minus 'crossfade duration' you choose.
4. When it will be changed from first track to second you will hear this bug. For better experience use track with quiet end part and another track with loud start part.
Hope it does not work to download my app and check it. 
Link: https://play.google.com/store/apps/details?id=com.merseyside.admin.exoplayer
Code:
```
public void playTrack(Track track) {
        createPlayer();
        this.track = track;
        this.url = track.getPath();
        Uri builtUri = Uri.parse(url);
        DataSource.Factory dataSourceFactory = new DefaultDataSourceFactory(context, Util.getUserAgent(context, "MegamixPlayer"));
        ExtractorsFactory extractorsFactory = new DefaultExtractorsFactory();
        MediaSource streamSource = new ExtractorMediaSource(builtUri, dataSourceFactory, extractorsFactory, null, null);
        isNotificated = false;
        type = Player_Fragment.Type.MEMORY;
        player.prepare(streamSource);
        if (track.isMegamixTrack()) seekTo(Integer.valueOf(track.getStartPoint()));
        player.setPlayWhenReady(true);
} 

public void onPlayerStateChanged(boolean playWhenReady, int playbackState) {

        switch (playbackState){
            case ExoPlayer.STATE_READY:{
                PrintString.printLog("lifeCycle", "Ready");
                if (type== Player_Fragment.Type.MEMORY) {
                    if (isEndOfTrackClose) {
                        setVolume(0f);
                        PrintString.printLog("Volume", "Player volume = " + player.getVolume());
                        makeOppositeFading();
                        isEndOfTrackClose = false;
                    }
                }
                break;
            }
            case ExoPlayer.STATE_ENDED:{
                if (isLooping){
                    playTrack(track);
                }
                else if (!isNotificated) myInterface.endOfTrack();
            }
        }
    }

private void setVolume(float volume){
        PrintString.printLog("Volume", volume + "");
        if (exist()) player.setVolume(volume);
    }

    public boolean exist(){
        return !(player == null);
    }

private void makeOppositeFading(){
        final int increase;
        if (track.isMegamixTrack()){
            if (track.getIncrease()==0) {
                setVolumeMax();
                return;
            }
            increase = track.getIncrease();
        }
        else increase = Settings.CROSSFADE;
        if (track.isMegamixTrack() || Settings.CROSSFADE > 0) {
            new Thread(new Runnable() {
                @Override
                public void run() {
                    float volume = 0f;
                    int sleepTime = increase / 20;
                    float delta_volume = MAX_VOLUME/20;
                    while (volume < MAX_VOLUME) {
                        volume += delta_volume;
                        setVolume(volume);
                        PrintString.printLog("Fading", "Opposite " + String.valueOf(volume));
                        try {
                            Thread.sleep(sleepTime);
                        } catch (InterruptedException e) {
                            e.printStackTrace();
                        }
                    }
                }
            }).start();
        } else setVolumeMax();
    }
```

**Comment by Merseyside** [comment]
Here is the log:
04-30 12:32:08.096 7148-7148/com.merseyside.admin.exoplayer D/Volume: Ready
04-30 12:32:08.096 7148-7148/com.merseyside.admin.exoplayer D/Volume: isEndOfTrack is true
04-30 12:32:08.096 7148-7148/com.merseyside.admin.exoplayer D/Volume: 0.0
04-30 12:32:08.096 7148-7148/com.merseyside.admin.exoplayer D/Volume: Player volume = 0.0
04-30 12:32:08.101 7148-9812/com.merseyside.admin.exoplayer D/Volume: 0.05
04-30 12:32:08.101 7148-9812/com.merseyside.admin.exoplayer D/Volume: Opposite 0.05
04-30 12:32:08.601 7148-9812/com.merseyside.admin.exoplayer D/Volume: 0.1
04-30 12:32:08.603 7148-9812/com.merseyside.admin.exoplayer D/Volume: Opposite 0.1
04-30 12:32:09.103 7148-9812/com.merseyside.admin.exoplayer D/Volume: 0.15
04-30 12:32:09.105 7148-9812/com.merseyside.admin.exoplayer D/Volume: Opposite 0.15
04-30 12:32:09.605 7148-9812/com.merseyside.admin.exoplayer D/Volume: 0.2
04-30 12:32:09.605 7148-9812/com.merseyside.admin.exoplayer D/Volume: Opposite 0.2
04-30 12:32:10.105 7148-9812/com.merseyside.admin.exoplayer D/Volume: 0.25
04-30 12:32:10.106 7148-9812/com.merseyside.admin.exoplayer D/Volume: Opposite 0.25
04-30 12:32:10.606 7148-9812/com.merseyside.admin.exoplayer D/Volume: 0.3
04-30 12:32:10.606 7148-9812/com.merseyside.admin.exoplayer D/Volume: Opposite 0.3
04-30 12:32:11.106 7148-9812/com.merseyside.admin.exoplayer D/Volume: 0.35000002
04-30 12:32:11.607 7148-9812/com.merseyside.admin.exoplayer D/Volume: 0.40000004
04-30 12:32:11.607 7148-9812/com.merseyside.admin.exoplayer D/Volume: Opposite 0.40000004
04-30 12:32:12.107 7148-9812/com.merseyside.admin.exoplayer D/Volume: 0.45000005
04-30 12:32:12.108 7148-9812/com.merseyside.admin.exoplayer D/Volume: Opposite 0.45000005
04-30 12:32:12.608 7148-9812/com.merseyside.admin.exoplayer D/Volume: 0.50000006
04-30 12:32:12.612 7148-9812/com.merseyside.admin.exoplayer D/Volume: Opposite 0.50000006
04-30 12:32:13.112 7148-9812/com.merseyside.admin.exoplayer D/Volume: 0.5500001
04-30 12:32:13.112 7148-9812/com.merseyside.admin.exoplayer D/Volume: Opposite 0.5500001
04-30 12:32:13.613 7148-9812/com.merseyside.admin.exoplayer D/Volume: 0.6000001
04-30 12:32:13.613 7148-9812/com.merseyside.admin.exoplayer D/Volume: Opposite 0.6000001
04-30 12:32:14.113 7148-9812/com.merseyside.admin.exoplayer D/Volume: 0.6500001
04-30 12:32:14.114 7148-9812/com.merseyside.admin.exoplayer D/Volume: Opposite 0.6500001
04-30 12:32:14.614 7148-9812/com.merseyside.admin.exoplayer D/Volume: 0.7000001
04-30 12:32:14.614 7148-9812/com.merseyside.admin.exoplayer D/Volume: Opposite 0.7000001
04-30 12:32:15.114 7148-9812/com.merseyside.admin.exoplayer D/Volume: 0.7500001
04-30 12:32:15.116 7148-9812/com.merseyside.admin.exoplayer D/Volume: Opposite 0.7500001
04-30 12:32:15.616 7148-9812/com.merseyside.admin.exoplayer D/Volume: 0.80000013
04-30 12:32:15.617 7148-9812/com.merseyside.admin.exoplayer D/Volume: Opposite 0.80000013
04-30 12:32:16.117 7148-9812/com.merseyside.admin.exoplayer D/Volume: 0.85000014
04-30 12:32:16.119 7148-9812/com.merseyside.admin.exoplayer D/Volume: Opposite 0.85000014
04-30 12:32:16.619 7148-9812/com.merseyside.admin.exoplayer D/Volume: 0.90000015
04-30 12:32:16.620 7148-9812/com.merseyside.admin.exoplayer D/Volume: Opposite 0.90000015
04-30 12:32:17.120 7148-9812/com.merseyside.admin.exoplayer D/Volume: 0.95000017
04-30 12:32:17.121 7148-9812/com.merseyside.admin.exoplayer D/Volume: Opposite 0.95000017
04-30 12:32:17.621 7148-9812/com.merseyside.admin.exoplayer D/Volume: 1.0000001
04-30 12:32:17.621 7148-9812/com.merseyside.admin.exoplayer D/Volume: Opposite 1.0000001

**Comment by ojw28** [comment]
To better understand this, you need to have an understanding of ExoPlayer's threading model, as described [here](http://google.github.io/ExoPlayer/doc/reference/). Note that operations performed on the player, and events delivered from the player, are both asynchronous.

This means that a STATE_READY event will be delivered to you asynchronously, and the setVolume operation will be applied asynchronously. Hence this code style of code will not synchronously set the volume to 0 before playback starts:

```
public void onPlayerStateChanged(boolean playWhenReady, int playbackState) {
        switch (playbackState){
            case ExoPlayer.STATE_READY:{
                setVolume(0f);
                ...
```

To set the volume to 0 before playback starts, you'd need to call `setVolume` before calling `setPlayWhenReady(true)`.

Note that the asynchronous application of `setVolume` means the way you're calling it repeatedly to do a crossfade is also quite tenuous. At best you have very little control to ensure that the fade will be smooth. You might be better off looking at extending `MediaCodecAudioRenderer` and implementing the fade directly in that class; although this is fairly complicated and is something you'd need to figure out for yourself.

**Comment by Merseyside** [comment]
Some moments ago it was before setPlayWhenReady as in my last issue https://github.com/google/ExoPlayer/issues/2594. It works the same. Crossfade works well.  What have I  do make it starts with 0? You say its async, so i tried with Thread.sleep(), but there was no benefit.

**Comment by ojw28** [comment]
We cannot reproduce the issue when setVolume(0) is called before setPlayWhenRead(true). We tried it and it worked as expected for us. You need to follow the issue template and provide proper steps to reproduce in our demo app if you want us to investigate further, since as far as we can determine everything works correctly (which rather suggests a bug in your application code).

**Comment by Merseyside** [comment]
Omg, i'm  so sorry guys, its my fault. I found a bug:)
