### ISSUE TITLE
[Question] Closed Captions (CEA-608 & 708) support for B-Frames in H.264 

### ISSUE THREAD

**Issue by peddisri** [google/ExoPlayer#2758]
### Issue description
I have a question about Closed Captions support. 
H.264 content that supports B Frames have frames decoding order different than presentation order.  It is expected that the CC (608 and 708) data present in them should be ordered on presentation timestamps. From the code in Exo2, it looks like this re-ordering is not supported. Any plans of adding this support? If I were to add the support, I guess a variant of InfoQueue and DataQueue, ie. OrderedInfoQueue & OrderedDataQueue in DefaultTrackOutput may be necessary that orders the samples on timestamps.  Or perhaps a OrderedTrackOutput. Your opinion?

### Reproduction steps
Any AVC content that supports B Frames and CC.

### Link to test content
Can't be shared as of now. Will check how it can be shared if necessary.

### Version of ExoPlayer being used
2.3.1

### Device(s) and version(s) of Android being used
Any. Not device specific.

### A full bug report captured from the device
NA

**Comment by ojw28** [comment]
This is supported already (by the fact CeaDecoder uses a TreeSet). Trying to play some content of this form would presumably have allowed you to answer this question for yourself. If you're actually seeing captions being presented in the wrong order, please let us know.

**Comment by peddisri** [comment]
Thanks! My bad, I was looking at a higher level, not at CEADecoder level. This answers my question.
