### ISSUE TITLE
[HLS] Dropping frames constantly / freezing / low speed on seek

### ISSUE THREAD

**Issue by Guro** [google/ExoPlayer#276]
Hello, we have implemented exo-player in our project and we are using HLS for VOD delivering,
but it drops frames frequently, also seeking is much slower than in androids native media player.

tried tweaking parameters for MediaCodecVideoTrackRenderer (allowedJoiningTimeMs, maxDroppedFrameCountToNotify) but didn't get any results.

can anyone suggest anything?

**Comment by ojw28** [comment]
What do frequently and much slower mean in absolute terms? Are you using the dev or dev-hls branch with TYPE_HLS? On what device(s) do you see these issues?

**Comment by Guro** [comment]
I'm using dev-hls branch and yes I'm using it with TYPE_HLS, device is Rockchip's set top box (RK3188) with android 4.4.2 on it.


here is the log of last 2 minutes of playing hls video:
02-03 04:21:59.834    9455-9455/ge.myvideo.tv.debug D/PlayerActivity﹕ Dropped frames: 5
02-03 04:22:01.144    9455-9455/ge.myvideo.tv.debug D/PlayerActivity﹕ Dropped frames: 5
02-03 04:22:03.584    9455-9455/ge.myvideo.tv.debug D/PlayerActivity﹕ Dropped frames: 3
02-03 04:22:06.204    9455-9455/ge.myvideo.tv.debug D/PlayerActivity﹕ Dropped frames: 5
02-03 04:22:08.774    9455-9455/ge.myvideo.tv.debug D/PlayerActivity﹕ Dropped frames: 5
02-03 04:22:09.044    9455-9455/ge.myvideo.tv.debug D/PlayerActivity﹕ Dropped frames: 5
02-03 04:22:09.324    9455-9455/ge.myvideo.tv.debug D/PlayerActivity﹕ Dropped frames: 5
02-03 04:22:09.764    9455-9455/ge.myvideo.tv.debug D/PlayerActivity﹕ Dropped frames: 5
02-03 04:22:09.814    9455-9455/ge.myvideo.tv.debug D/PlayerActivity﹕ Dropped frames: 5
02-03 04:22:10.574    9455-9455/ge.myvideo.tv.debug D/PlayerActivity﹕ Dropped frames: 5
02-03 04:22:11.024    9455-9455/ge.myvideo.tv.debug D/PlayerActivity﹕ Dropped frames: 5
02-03 04:22:11.054    9455-9455/ge.myvideo.tv.debug D/PlayerActivity﹕ Dropped frames: 5
02-03 04:22:11.614    9455-9455/ge.myvideo.tv.debug D/PlayerActivity﹕ Dropped frames: 5
02-03 04:22:11.644    9455-9455/ge.myvideo.tv.debug D/PlayerActivity﹕ Dropped frames: 5
02-03 04:22:12.024    9455-9455/ge.myvideo.tv.debug D/PlayerActivity﹕ Dropped frames: 5
02-03 04:22:12.674    9455-9455/ge.myvideo.tv.debug D/PlayerActivity﹕ Dropped frames: 5
02-03 04:22:12.764    9455-9455/ge.myvideo.tv.debug D/PlayerActivity﹕ Dropped frames: 4
02-03 04:22:37.114    9455-9455/ge.myvideo.tv.debug D/PlayerActivity﹕ Dropped frames: 5
02-03 04:22:37.514    9455-9455/ge.myvideo.tv.debug D/PlayerActivity﹕ Dropped frames: 5
02-03 04:22:37.884    9455-9455/ge.myvideo.tv.debug D/PlayerActivity﹕ Dropped frames: 5
02-03 04:22:38.134    9455-9455/ge.myvideo.tv.debug D/PlayerActivity﹕ Dropped frames: 5
02-03 04:22:38.644    9455-9455/ge.myvideo.tv.debug D/PlayerActivity﹕ Dropped frames: 5
02-03 04:22:39.144    9455-9455/ge.myvideo.tv.debug D/PlayerActivity﹕ Dropped frames: 5
02-03 04:22:39.174    9455-9455/ge.myvideo.tv.debug D/PlayerActivity﹕ Dropped frames: 5
02-03 04:22:39.764    9455-9455/ge.myvideo.tv.debug D/PlayerActivity﹕ Dropped frames: 5
02-03 04:22:40.144    9455-9455/ge.myvideo.tv.debug D/PlayerActivity﹕ Dropped frames: 5
02-03 04:22:40.574    9455-9455/ge.myvideo.tv.debug D/PlayerActivity﹕ Dropped frames: 5
02-03 04:22:40.934    9455-9455/ge.myvideo.tv.debug D/PlayerActivity﹕ Dropped frames: 5
02-03 04:22:41.174    9455-9455/ge.myvideo.tv.debug D/PlayerActivity﹕ Dropped frames: 5
02-03 04:22:41.644    9455-9455/ge.myvideo.tv.debug D/PlayerActivity﹕ Dropped frames: 5
02-03 04:22:41.904    9455-9455/ge.myvideo.tv.debug D/PlayerActivity﹕ Dropped frames: 5
02-03 04:22:42.304    9455-9455/ge.myvideo.tv.debug D/PlayerActivity﹕ Dropped frames: 5
02-03 04:22:42.604    9455-9455/ge.myvideo.tv.debug D/PlayerActivity﹕ Dropped frames: 5
02-03 04:22:44.524    9455-9455/ge.myvideo.tv.debug D/PlayerActivity﹕ Dropped frames: 5
02-03 04:22:44.724    9455-9455/ge.myvideo.tv.debug D/PlayerActivity﹕ Dropped frames: 5
02-03 04:22:45.094    9455-9455/ge.myvideo.tv.debug D/PlayerActivity﹕ Dropped frames: 5
02-03 04:22:45.344    9455-9455/ge.myvideo.tv.debug D/PlayerActivity﹕ Dropped frames: 5
02-03 04:22:45.564    9455-9455/ge.myvideo.tv.debug D/PlayerActivity﹕ Dropped frames: 5
02-03 04:22:45.944    9455-9455/ge.myvideo.tv.debug D/PlayerActivity﹕ Dropped frames: 5
02-03 04:22:46.174    9455-9455/ge.myvideo.tv.debug D/PlayerActivity﹕ Dropped frames: 5
02-03 04:22:46.454    9455-9455/ge.myvideo.tv.debug D/PlayerActivity﹕ Dropped frames: 5
02-03 04:22:46.834    9455-9455/ge.myvideo.tv.debug D/PlayerActivity﹕ Dropped frames: 5
02-03 04:22:47.224    9455-9455/ge.myvideo.tv.debug D/PlayerActivity﹕ Dropped frames: 5
02-03 04:22:47.464    9455-9455/ge.myvideo.tv.debug D/PlayerActivity﹕ Dropped frames: 5
02-03 04:22:48.004    9455-9455/ge.myvideo.tv.debug D/PlayerActivity﹕ Dropped frames: 5
02-03 04:22:48.234    9455-9455/ge.myvideo.tv.debug D/PlayerActivity﹕ Dropped frames: 5
02-03 04:22:48.634    9455-9455/ge.myvideo.tv.debug D/PlayerActivity﹕ Dropped frames: 5
02-03 04:22:49.094    9455-9455/ge.myvideo.tv.debug D/PlayerActivity﹕ Dropped frames: 5


Dropped frames occur often after seeking.

Thanks

**Comment by Guro** [comment]
Increasing minBufferMs/minRebufferMs to 10000
Also Decresing maxDroppedFrameCountToNotify to 15 helped a little

**Comment by Guro** [comment]
I think thats a problem #278

**Comment by ojw28** [comment]
Changing maxDroppedFrameCountToNotify does nothing except changing the rate that dropped frames are reported. It wont have made any difference to the actual user visible experience.

Probably the same as #278, so let's use that issue for tracking
