### ISSUE TITLE
Tunneled video playback not starting

### ISSUE THREAD

**Issue by zoard25** [google/ExoPlayer#2761]
Hi,

I am working on an Android TV application and i want to enable tunneling for the video playback to improve performance. 

As i know enabling it should be just setting the audio session id with: trackSelector.setTunnelingAudioSessionId(C.generateAudioSessionIdV21(this));  but unfortunately it won't start the tunneling just by setting this id in my case. 

The device should support tunneling, i can find the video_decoder.tunnel.secure decoder when debugging the MediaCodecUtil class. But when requesting the info at: mediacodec.MediaCodecUtil#getDecoderInfo it always returns the first item/decoder from the list which in my case will be video_decoder.secure (not the tunneling one, because it is on the index 1 in the list).

If i force it to use the tunneled one the playback starts, but i think it's not the correct way, and something is wrong.
So what could be the reason that tunneling is not enabled just by setting the audio session id? From where do i know that the device is supporting it (besides from the codec list)?

I checked also at trackselection.MappingTrackSelector#maybeConfigureRenderersForTunneling - and there the video was not supported for tunneling (tunnelingVideoRendererIndex was -1) So here i had to force again.

Can you please advise how to proceed further?

Thanks!

Exoplayer version: 2.2.0
Android version: 7.0

**Comment by ojw28** [comment]
I think our code expects the tunneled decoder to be listed first (or for a single decoder to support both non-tunneled and tunneled mode).  If you manually change getDecoderInfo to ignore the first (i.e. non-tunneled) decoder, do you see tunneled playback working correctly in that case?

**Comment by zoard25** [comment]
I can see that the correct decoders are initialized (with tunneling) and the playback is starting but ex. if i do some seeks back and forth sometimes the image gets stuck. And after starting multiple times (2-3x) one asset the playback gets really laggy and even stops at some point and in the logs i can see errors like: "nexus_tunnel_bout_write: playpump write timeout, ret=5"

So i assume that is not playing correctly. But i don't know that it is hardware related or i did a mistake somewhere.

**Comment by ojw28** [comment]
It sounds like an issue that you need to report to the device manufacturer. Tunneled mode effectively hands the A/V output responsibilities to the device manufacturer's implementation, so there's not much we can do in ExoPlayer if it's not working properly. It's hard even to query whether it *is* working properly, since we do send the data "down the tunnel" for output, and that's time we see it.
