### ISSUE TITLE
Adding request headers to ExtractorMediaSource 

### ISSUE THREAD

**Issue by ArunkarthickNallasamy** [google/ExoPlayer#2764]
Hello,
 I need to add request headers for playing video with exoplayer. I could see it was available with ExtractorSampleSource and I could not add the same with ExtractorMediaSource. Also i dont see  ExtractorSampleSource part of r2.3.1.  Kindly help

**Comment by ojw28** [comment]
We will try and document customization points such as this a little better. You can do what you want as follows:

```
DefaultHttpDataSourceFactory dataSourceFactory = new DefaultHttpDataSourceFactory(userAgent);
dataSourceFactory.getDefaultRequestProperties().set("headerName", "headerValue");
return new ExtractorMediaSource(uri, dataSourceFactory, ...);
```

**Comment by ArunkarthickNallasamy** [comment]
Thank you so much that helped a lot. :)
