### ISSUE TITLE
Support rewind / backward playback

### ISSUE THREAD

**Issue by q-litzler** [google/ExoPlayer#2766]
Hello, this is a feature request.

I've been playing with the new playbackParameters feature, and it's great.

Will we be able to pass a negative speed value (to rewind the video) in the future ?

Thanks

**Comment by ojw28** [comment]
Video codecs are heavily optimized for forward playback. It's extremely difficult to smoothly play video backward without using huge amounts of memory. It is possible to play key-frames only, but this is not something we're likely to support any time soon. Marking as an enhancement nevertheless, for if/when we do get around to it.

**Comment by Angtrim** [comment]
Assuming that I have a video encoded with every frame as a key-frame, is there an easy way to make the Playback Parameters work with negative value? (Also I don't care about audio)

**Comment by ojw28** [comment]
This is not possible currently, sorry.

**Comment by ojw28** [comment]
I don't think we have any plans to support this more than we do today.
