### ISSUE TITLE
Playback Buffer re-download 

### ISSUE THREAD

**Issue by lioun1729** [google/ExoPlayer#2767]
![kakaotalk_20170504_094019970](https://cloud.githubusercontent.com/assets/16380086/25687041/f6a8e16c-30ad-11e7-863b-d9ced65d5faf.jpg)
![kakaotalk_20170504_094019478](https://cloud.githubusercontent.com/assets/16380086/25687043/f979278a-30ad-11e7-85a8-8271a5279beb.jpg)

The first picture is a exoplayer video demo

If I click the previous timeline (e.g. 00:10 , The second picture), The playback buffer is deleted and re-download

So, This causes the delay because player app tries downloading the video segment again that is previously downloaded

Is a inherent exoplayer's feature?

If that, where? (Library or Class, etc)

I want to prevent deleting the buffer and re-downloading the video segment when I click the previous timeline, instead I maintain the buffer that is previously downloaded

How can I do?

Thank you for read my question

**Comment by andrewlewis** [comment]
#420 has some information about caching, which should help with this.
