### ISSUE TITLE
Easy way of playing udp h264 encoded streaming

### ISSUE THREAD

**Issue by Schizo** [google/ExoPlayer#277]
I am wondering, if exoplayer can play out of the box x264 encoded live streams with hardware-acceleration? And if so, are there any examples targeting this case? To get the best possible latency, i need to go over plain udp streaming and i dont want to have any buffering. Can someone enlighten me? Thanks!

**Comment by ihrthk** [comment]
keep concern...

**Comment by Schizo** [comment]
what do you mean?

**Comment by ihrthk** [comment]
I am chinese,english is poor. I mean what i will  stared at this issue.Becase i need a easy way to play h264.

**Comment by Pitel** [comment]
I'm also interested in this use case. I want to play H.264 Annex B stream over UDP on Android.

**Comment by rejhgadellaa** [comment]
+1

**Comment by jeoliva** [comment]
I don't think that feature is supported right now. What you can do is implementing your own extractor for raw H.264. Out of curiosity, what is the interest behind playing a H.264 Annex B stream? playing what is coming from a video camera source? Take into account that raw H.264 doesn't contain timestamp information so playback will be always speeded up.

**Comment by rejhgadellaa** [comment]
@jeoliva hmm not sure if I want it to be raw H.264 but my video experience is limited.. What I want is to be able to play a videostream from my computer to a tablet on the same LAN. I use ffmpeg to send the stream over udp (mpegts). VLC plays the stream but has too much latency for my case (~1sec), I need it to be below 500ms so I thought I'd give exoplayer a try and see if I can get that down?

Anyway, I have no idea how to do this. If I add a sample (in the demo app) that points to udp://@:5000 it doesn't work.

**Comment by ojw28** [comment]
It's unclear exactly what this request is. For us to investigate further, we'd need a sample stream/capture of the media that you're trying to play.
