### ISSUE TITLE
player local mp4 use large memory

### ISSUE THREAD

**Issue by leach-chen** [google/ExoPlayer#2772]
**Issue description**

when I use the exoplayer2 play the local mp4 file.it use large memory
if the file is 10M,it will use 20M memory
if the file is 40M,it will use 40M memory,
if the file is 120M,it will use 40M memory,

why use so much memory?when I use videoview,it will use little memory

**Reproduction steps**

Handler mainHandler = new Handler(); 
BandwidthMeter bandwidthMeter = new DefaultBandwidthMeter(); 
TrackSelection.Factory videoTrackSelectionFactory = new AdaptiveTrackSelection.Factory(bandwidthMeter); 
TrackSelector trackSelector = new DefaultTrackSelector(videoTrackSelectionFactory);
 final LoadControl loadControl = new DefaultLoadControl(); 
player =ExoPlayerFactory.newSimpleInstance(this, trackSelector, loadControl); player_view.setPlayer(player);
 Uri mp4VideoUri = Uri.parse("file://" + Environment.getExternalStorageDirectory().getPath() + "/a.MP4"); DefaultBandwidthMeter bandwidthMeter1 = new DefaultBandwidthMeter(); DataSource.Factory dataSourceFactory = new DefaultDataSourceFactory(this,Util.getUserAgent(this, "yourApplicationName"), bandwidthMeter1); 
ExtractorsFactory extractorsFactory = new DefaultExtractorsFactory(); 
MediaSource videoSource = new ExtractorMediaSource(mp4VideoUri,dataSourceFactory, extractorsFactory, null, null); 
player.prepare(videoSource); 
player_view.setUseController(false);

**Version of ExoPlayer being used**

r2.3.0

**Comment by AquilesCanta** [comment]
You are ignoring part of the template. Read the template and include all the information required there. Of particular interest here is the media file.

**Comment by ojw28** [comment]
> why use so much memory?when I use videoview,it will use little memory

VideoView and MediaPlayer both use similarly large amounts of memory. The difference is that the memory is allocated inside the media server process, where-as ExoPlayer allocates the memory inside your application process.
