### ISSUE TITLE
Crash (SIGSEGV) when playing HLS video on Samsung Galaxy Nexus

### ISSUE THREAD

**Issue by artnalban** [google/ExoPlayer#2778]
### Issue description
SIGSEGV when playing HLS video on Samsung Galaxy Nexus

### Reproduction steps
Run demo app and play this media
http://edge.tpr-3ehznk.top.comcast.net/demo/content/PDK_(VMS)/501/291/2014_Seattle_to_Portland_(STP)_Bicycle_Classic.m3u8

### Version of ExoPlayer being used
Issue is reproducible on Exo 2.4.0 but is NOT reproducible on 1.5.16

### Device(s) and version(s) of Android being used
So far able to repro only on Samsung Galaxy Nexus API level 17

### A full bug report captured from the device
Please see logcat and adb bugreport attached
[crashlog.txt](https://github.com/google/ExoPlayer/files/977906/crashlog.txt)
[adbbugreport.txt](https://github.com/google/ExoPlayer/files/977907/adbbugreport.txt)

**Comment by ojw28** [comment]
Pretty sure this is fixed already (in a better way). See https://github.com/google/ExoPlayer/issues/2607.
