### ISSUE TITLE
Ogg/Opus playback is not seekable

### ISSUE THREAD

**Issue by Behrouz-m** [google/ExoPlayer#2783]
Hi, I am using opus extension. I plays opus files but it does not report the opus file duration.
may be my code has a problem. Please check it:

```java

    RenderersFactory rf = new RenderersFactory()
        {
            @Override
            public Renderer[] createRenderers(Handler eventHandler, VideoRendererEventListener videoRendererEventListener, AudioRendererEventListener audioRendererEventListener, TextRenderer.Output textRendererOutput, MetadataRenderer.Output metadataRendererOutput)
            {
                return new Renderer[]{new LibopusAudioRenderer(eventHandler, audioRendererEventListener)};
            }
        };
    player = ExoPlayerFactory.newSimpleInstance(rf, trackSelector, new MyExoLoadControl());
```

should I use the opus extension in other way ?

NOTE: I've just copied the **java** opus extension files directly into my project and I've embedded the jni code into my own jni code because I had libopus in static format in my own jni lib. It works except the seeking problem.
thanks.

I'm using Exoplayer 2.4

**Comment by Behrouz-m** [comment]
Here is my sample opus file:
[https://www.dropbox.com/s/985vx673byd74rf/ABET.opus?dl=1](https://www.dropbox.com/s/985vx673byd74rf/ABET.opus?dl=1)

**Comment by ojw28** [comment]
I tried just adding that sample URL the demo app and seeking worked fine. The only case I can think of where that wouldn't be the case is if you're serving the file from a server that doesn't indicate the content length in its response headers. In that case it's working as intended that the duration is not known, and you should configure your server more appropriately for media playback.

**Comment by ojw28** [comment]
Note: This is probably the same as another similar issue you filed, here: https://github.com/google/ExoPlayer/issues/2306.
