### ISSUE TITLE
React when onBandwidthSample

### ISSUE THREAD

**Issue by lioun1729** [google/ExoPlayer#2784]
Hi, I have a question about onBandwidthSample method in BandwidthMeter.Listener

I try to insert reaction code when onBandwidthSample

onBandwidthSample method is already reacted when some data is arrived if it is implemented some class (Am i correct? I confused about this)

If so, Where implements the onBandwidthSample? On PlayerActivity?

I already tried to implement the onBandwidthSample in PlayerActivity

But, It is not worked

I think that I was wrong about using onBandwidthSample method

Please help

Thank you for read this question

**Comment by andrewlewis** [comment]
Are you using [DefaultBandwidthMeter](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/upstream/DefaultBandwidthMeter.java)? You can pass in an event listener when instantiating it if you want to handle that event. Beyond that, I'm not sure what information you're looking for, so please clarify. Thanks!

**Comment by lioun1729** [comment]
@andrewlewis 

Umm.. I know what you mean but what should be passed to DefaultBandwidthMeter object?

PlayerActivity itself? or other object?

I confused about this

Suppose one situation below

I pass the PlayerActivity object itself to DefaultBandwidthMeter's listener

So, If PlayerActivity has received some data (e.g. dash chunk), onBandwidthSample method is called correctly?

**Comment by andrewlewis** [comment]
Pass something that implements `BandwidthMeter.EventListener`. You don't have to pass any particular object. Please read the code for `DefaultBandwidthMeter` if you want to see when the event listener is invoked.

**Comment by lioun1729** [comment]
@andrewlewis 

Ok, I have to think more

Thank you for your reply
