### ISSUE TITLE
SimpleExoPlayer.setVideoTextureView() fails with mpd + Widevine

### ISSUE THREAD

**Issue by niusounds** [google/ExoPlayer#2785]
### Issue description

`SimpleExoPlayer.setVideoTextureView()` fails with mpd + Widevine and stops playback.

On some devices(Nexus5, Galaxy S6), mpd(WebM,VP9) + Widevine is playable but some device (Pixel) cannot play it. Without DRM mpd(MP4,H264 or H265 and WebM,VP9) is working well.

I think it is actually a problem of `SimpleExoPlayer.setVideoSurface()`. I use this method to play video in VR app. It does not work.

### Reproduction steps

Use `exoPlayer.setVideoTextureView(textureView)` for video output.

For more details, see [whole Activity codes](https://github.com/niusounds/ExoPlayer_TextireView/blob/master/app/src/main/java/com/niusounds/exoplayertest/MainActivity.java) or clone this project https://github.com/niusounds/ExoPlayer_TextireView

### Link to test content

See [my project's README](https://github.com/niusounds/ExoPlayer_TextireView/blob/master/README.md#tested-urls)

### Version of ExoPlayer being used
2.4.0

### Device(s) and version(s) of Android being used

* Nexus 5 (Android 6.0.1)
* Galaxy S6 edge (Android 7.0)
* Pixel (Android 7.1.2)

### A full bug report captured from the device

[bugreport-N2G47O-2017-05-08-18-06-57.zip](https://github.com/google/ExoPlayer/files/982983/bugreport-N2G47O-2017-05-08-18-06-57.zip)

**Comment by andrewlewis** [comment]
TextureView can't be used to show Widevine L1 DRM content, which requires a secure output path. See also our [FAQs](https://google.github.io/ExoPlayer/faqs.html#should-i-use-surfaceview-or-textureview).

**Comment by niusounds** [comment]
Thank you for response.

Sorry, I didn't know that limitation.

Is there no way to render DRM protected content to Open GL Texture? I would like to create VR video player app that supports Widevine... (or some other DRM scheme)

**Comment by andrewlewis** [comment]
It is possible on devices that support VR mode running Android N or later. Please look at [Secure texture video playback](https://source.android.com/devices/graphics/arch-st#st_vid_play) as a starting point.

**Comment by niusounds** [comment]
OK! Thanks for information!

**Comment by andrewlewis** [comment]
If you're using the Google VR SDK you might also find the sample [sdk-videoplayer](https://github.com/googlevr/gvr-android-sdk/tree/master/samples/sdk-videoplayer) useful. It shows how to play a video using the secure output path.

**Comment by niusounds** [comment]
I'm using [GearVR Framework](https://github.com/Samsung/GearVRf) which encapsulates native OpenGL calls and provides scene graph implementation for Gear VR and Daydream. I'm developing for Gear VR so cannot use Google VR SDK...
