### ISSUE TITLE
How to change volume?

### ISSUE THREAD

**Issue by LutfiTekin** [google/ExoPlayer#2789]
Hello, I cannot find any useful or complete information about how to change volume.

I am currently using exoplayer r2.4.0

I need to lower volume when the audiofocus change occurs
` public void onAudioFocusChange(int focusChange) {
     
            switch (focusChange) {
                case AudioManager.AUDIOFOCUS_LOSS:
                    exoPlayer.setPlayWhenReady(false);
                    break;
                case AudioManager.AUDIOFOCUS_LOSS_TRANSIENT:
                case AudioManager.AUDIOFOCUS_LOSS_TRANSIENT_CAN_DUCK:
                    //TODO lower volume
                    break;
                case AudioManager.AUDIOFOCUS_GAIN:
                    //TODO restore volume
                    break;
            }
        }`

I've found code snippets like 

`player.sendMessage(audioRenderer, MediaCodecAudioTrackRenderer.MSG_SET_VOLUME, 0f);`

But i don't how to create an audioRenderer object.

**Comment by ojw28** [comment]
https://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/SimpleExoPlayer.html#setVolume-float-

**Comment by LutfiTekin** [comment]
I cannot find setVolume method in my exoplayer setup. 
```
TrackSelector trackSelector = new DefaultTrackSelector(null);
                exoPlayer = ExoPlayerFactory.newSimpleInstance(this, trackSelector);
                final String datasource = intent.getExtras().getString(DATA_SOURCE);
                DefaultHttpDataSourceFactory dataSourceFactory = new DefaultHttpDataSourceFactory("test");
                ExtractorsFactory extractor = new DefaultExtractorsFactory();
                MediaSource audioSource = new ExtractorMediaSource(Uri.parse(datasource), dataSourceFactory, extractor, null, null);
                exoPlayer.prepare(audioSource);
```

Is there something wrong with my code?

**Comment by LutfiTekin** [comment]
Sorry my bad I was using `ExoPlayer exoPlayer;` when declaring it;
`SimpleExoPlayer` worked.
Thanks for help.

**Comment by ojw28** [comment]
Great; glad you figured it out!

**Comment by coolavdhesh** [comment]
how to implement setVolume method for IJkExoplayer?

**Comment by andrewlewis** [comment]
@coolavdesh This issue tracker is only for ExoPlayer issues. I suggest asking the maintainers of that project.
