### ISSUE TITLE
FrameworkSampleSource: How to get codec errors?

### ISSUE THREAD

**Issue by TheNetStriker** [google/ExoPlayer#279]
I've integrated ExpPlayer into my app to play video using the FrameworkSampleSource. Some of my videos (e.g. M2TS videos) cannot be played by the FrameworkSampleSource, but I didn't get any errors on the listeners of ExoPlayer.

When playing M2TS from a file I found out that an ExoPlaybackException is thrown in MediaCodecTrackRenderer in "doPrepare". I've changed this so the exeption is also reported via the EventListener.

But if I play the same video using an http streaming url the ExoPlaybackException exception is not raised. (The exception is raised later in the M2TSBuffer component) Also the position and the buffer position of the ExoPlayer are > 0. Here are the logs from logcat:

W/M2TSExtractor﹕ Cannot get last PTS for Audio
D/ExtendedUtils﹕ Try creating ExtendedExtractor
E/QCExtractor﹕ ExtendedExtractor failed to instantiate extractor
E/ExtendedExtractor﹕ Failed to instantiate extractor
D/ExtendedUtils﹕ Couldn't create the extended extractor, return default one
I/OMXClient﹕ Using client-side OMX mux.
I/ACodec﹕ DRC Mode: Dynamic Buffer Mode
I/NuCachedSource2﹕ new range: offset= 2736128
I/NuCachedSource2﹕ ERROR_END_OF_STREAM
E/M2TSBuffer﹕ failed(-1011) in readAt(33404928).
E/M2TSBuffer﹕ mFinalStatus = -1011.

Is it possible to trigger such errors using the FrameworkSampleSource? I would like to sent an Intent for an external app to play the video if such an error occurs.

**Comment by ojw28** [comment]
If the underlying MediaExtractor isn't propagating the error up into ExoPlayer code, there's no way for us to propagate it out of ExoPlayer. Sorry.

We're working on reducing our dependencies on MediaExtractor to avoid issues such as this one in the future.

**Comment by TheNetStriker** [comment]
I've found a workarround to find out if the video was played or not. I'am simply setting a "videoPlayed" boolean when onVideoSizeChanged is called and then check this boolean in onPlayerStateChanged:

if (playbackState == ExoPlayer.STATE_ENDED && !videoPlayed)
            Toast.makeText(this, "Video could not be played", Toast.LENGTH_SHORT).show();
