### ISSUE TITLE
Variable speed implementation plays static on Motorola XT1575

### ISSUE THREAD

**Issue by rustyshelf** [google/ExoPlayer#2791]
### Issue description
This is a bit of a doozy, but I'll do my best to explain it here. On one specific Motorola device (detailed below) the variable speed implementation will play just static, instead of speeding up audio. Playing at 1x results in no static. The reason I say this is a doozy, is that installing exactly the same APK again can fix the issue. It seems like whether or not you get this bug is determined by some kind of post-install optimisation run by this particular device. So you can install it, have the issue, reinstall and you'll either have the issue again or won't.

The issue has something to do with the way the Sonic code is being optimised I think. We had this same issue when we used to ship the Sonic implementation inside our app as well. Identical symptoms. I'm filing this bug in the hopes that someone who works on ExoPlayer might know what this is, because we never managed to figure it out.

Basically every time we update our app, some of the users that had this issue report it to be fixed by the update, others report it to be broken. Re-installing the app from the store results in the same thing, it's either broken or fixed at install time. A working install will always work, a broken install will always fail. We have a beta now where we've changed over to using ExoPlayer 2.4 for the variable speed playback, in the hope that you'd magically fixed this issue, but it's still present with exactly the same symptoms.

The specific device is:
```
Phone: motorola - Moto X Style - XT1575 - clark
Kernel: 3.10.84-perf-g94afac7 - ilclbld33
Android version: 6.0 SDK 23
```

### Reproduction steps
This one isn't easy, but basically you have to get hold of the phone above, and try playing an mp3 back at variable speed on it. It doesn't seem to matter if it's streamed or downloaded or what the mp3 is. If playback works, you keep re-installing the app until it breaks.

### Link to test content
N/A

### Version of ExoPlayer being used
ExoPlayer 2.4

### Device(s) and version(s) of Android being used
Phone: motorola - Moto X Style - XT1575 - clark
Kernel: 3.10.84-perf-g94afac7 - ilclbld33
Android version: 6.0 SDK 23

### A full bug report captured from the device
We don't have any of these, but happy to try and capture any reports from our users you think might be useful.

I can understand this isn't the typical kind of bug you might want to track, but I've filed it in case it helps. If you feel it's too vague or hard to reproduce happy for you to close it.

**Comment by andrewlewis** [comment]
Apparently this device can be upgraded to Android Nougat. Is the issue still reproducible after that update, or only on Android Marshmallow?

**Comment by rustyshelf** [comment]
@andrewlewis we have two of them here, none of them have updates available. I haven't seen any of our customers that have Nougat either.

**Comment by andrewlewis** [comment]
If you have this device, please could you provide a bug report?

**Comment by ojw28** [comment]
Realistically I don't think we're going to be able to do anything here. Closing for now.

Aside: I think we decided the source claiming a Nougat update is available for this device was suffering an off-by-one error :).
