### ISSUE TITLE
Enable and Disable Captioning 

### ISSUE THREAD

**Issue by ArunkarthickNallasamy** [google/ExoPlayer#2792]
Hello,
 I was able to show subtitle, I was wondering how to provide enable and disable feature for closed captioning so that i can have a custom button in media controller which can toggle subtitle visibility.

**Comment by AquilesCanta** [comment]
The demo app is a good place to start. If you play any content with subtitles there, you'll see a "Text" button on the top of the screen. You can modify that code a little bit to achieve what you are looking for.
