### ISSUE TITLE
Problem with mp4 streaming

### ISSUE THREAD

**Issue by hpanahiird** [google/ExoPlayer#2793]
hi, I want to play an mp4 via internet link in exoplayer But when I seek to any position in video it sems like that it's downloading whole video from beginning to that position. Is this problem related to exoplayer or it is from server? how can  I handle this problem?

**Comment by ojw28** [comment]
Most likely the server doesn't support range requests, in which case the player has no alternative but to do this. If that's the case, you should use a more appropriate server configuration.
