### ISSUE TITLE
Release this project as an Android library to jCenter and Maven Central.

### ISSUE THREAD

**Issue by pajatopmr** [google/ExoPlayer#28]
The ExoPlayer would be very good to use in binary form from JCenter or Maven Central.  It is less useful as a source-only project as there is a higher likelihood of fork-and-hoard behavior.

**Comment by lnikkila** [comment]
Has a decision been made on this? Keeping the library updated would definitely be easier if we could fetch it from Maven Central.

**Comment by ojw28** [comment]
Yes. We'll do this for stable releases. You'll still need to use the source directly if you want to make modifications and/or work against the development branches, obviously.

**Comment by blundell** [comment]
:+1: fyi JCenter has a much easier release process than Maven Central

**Comment by mingfai** [comment]
before there is a stable release, and assume it will take more than a few weeks to become stable, may I suggest to release it as a "alpha", "beta", "rc" etc.? just make it very clear it is unstable and use it at your own risk...

**Comment by zayass** [comment]
We use ExoPlayer from inhouse maven repo. And add some code to publish it via gradle https://github.com/google/ExoPlayer/pull/314

May be it would be useful when you
> We'll do this for stable releases.

**Comment by ojw28** [comment]
Update - Our intention is to publish through https://bintray.com/google in due course.

**Comment by blundell** [comment]
fyi we made it super easy with this plugin https://github.com/novoda/bintray-release

```
publish {
    userOrg = 'google'
    groupId = 'com.google'
    artifactId = 'exoplayer'
    version = '1.0.0'
    description = 'Insert desc here'
    website = 'https://github.com/google/ExoPlayer'
}
```

`/gradlew clean build bintrayUpload -PbintrayUser=BINTRAY_USERNAME -PbintrayKey=BINTRAY_KEY -PdryRun=false`

**Comment by ojw28** [comment]
Added use of bintray-release in: https://github.com/google/ExoPlayer/commit/85be2aed0a5e5487504905d45c1a565d288feee2

**Comment by ojw28** [comment]
Added here: https://bintray.com/google/exoplayer

This is now just pending a bintray "add to jCenter" request. Once that gets done, we can close this issue.

**Comment by ojw28** [comment]
This is now done. @blundell , it would be great if novoda could stop publishing a version, now that we're publishing one officially? In particular, you've got the "exoplayer" name, where-as the official version is "exoplayer-google", which doesn't make much sense (here)[https://bintray.com/bintray/jcenter?filterByPkgName=exoplayer].

**Comment by blundell** [comment]
Yes we will switch to using the official upload and drop our release when yours is available :+1:

**Comment by ojw28** [comment]
Thanks! Closing this now.

**Comment by xrigau** [comment]
:100:

**Comment by noahmiller** [comment]
What's the appropriate build.gradle command to depend on ExoPlayer's bintray release?  Something like this (which fails with a "failed to resolve" error):

```
repositories {
   maven {
      url  "http://dl.bintray.com/google/exoplayer"
   }
}

dependencies {
   compile 'google:exoplayer:1.2.3'
}
```

**Comment by xrigau** [comment]
I assume it is something like:

```java
repositories {
   jcenter()
}

dependencies {
   compile 'com.google.android.exoplayer:exoplayer:r1.2.3'
}
```

**Comment by noahmiller** [comment]
Ah, that’s it, thanks for the help.

**Comment by zayass** [comment]
>
 ```groovy
repositories {
   jcenter()
}
>
dependencies {
   compile 'com.google.android.exoplayer:exoplayer:r1.2.3'
}
```

I think it should be in README

**Comment by bodyflex** [comment]
@zayass, second that!

**Comment by Schizo** [comment]
Me too!

**Comment by VAdaihiep** [comment]
@zayass thank you, don't know why they still not update README.

**Comment by bodyflex** [comment]
@VAdaihiep maybe someone should make a pull request

**Comment by HugoGresse** [comment]
I've juste created one : https://github.com/google/ExoPlayer/pull/476
