### ISSUE TITLE
Implement a mechanism to receive playback position updates for audio

### ISSUE THREAD

**Issue by jedhoffmann** [google/ExoPlayer#280]
I have an audio player built on top of android.media.AudioTrack and a feature for which I have not found parity in ExoPlayer is the ability to register for playback position callbacks and the ability to set the notification period for the position callbacks.

**Comment by ojw28** [comment]
Isn't it pretty straightforward to write this in your own application code, just by having something call ExoPlayer.getCurrentPosition at the desired rate?

**Comment by ojw28** [comment]
Closing as per the answer above. I don't think this is something that the library needs to support directly.
