### ISSUE TITLE
What is a Manifest?

### ISSUE THREAD

**Issue by AOrobator** [google/ExoPlayer#2801]
There are mentions of a manifest object in the [`MediaSource` code](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/source/MediaSource.java#L39) as well as the [`ExoPlayer.EventListener` code](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/ExoPlayer.java#L123) What is a manifest and how does it relate to a `Timeline` object? It's not clear what it is from the documentation.

**Comment by ojw28** [comment]
It's `null` for non-adaptive playbacks. Adaptive (i.e. DASH, SmoothStreaming and HLS) playbacks have the concept of a manifest that provides the player with information about the available media required for playback (e.g. the available qualities, the URL of each media chunk etc). The object in these cases is a representation of the manifest. The manifest structure varies by standard, so it'll be an instance of either `DashManifest`, `SsManifest` or `HlsManifest`depending on the type of media being played.

In most cases an application can ignore the manifest. It's only really useful if a content provider is doing something like inserting custom data into their manifests on the server side that they want to get at during playback.
