### ISSUE TITLE
AdaptiveVideoTrackSelection missing in r2.4.0 

### ISSUE THREAD

**Issue by lazarvgd** [google/ExoPlayer#2802]
Hi, I have updated my ExoPlayer from r2.2.0 to r2.4.0 and I got issue with AdaptiveVideoTrackSelection because it is missing in library.

If I change back version to r.2.2.0 everything works fine.
Can you please let me know what workaround can I use for this issue?

thanks :)

**code snippet:**
```

 mainHandler = new Handler();
        bandwidthMeter = new DefaultBandwidthMeter();

        videoTrackSelectionFactory = new AdaptiveVideoTrackSelection.Factory(bandwidthMeter);
        String userAgent = "Exo";
        trackSelector = new DefaultTrackSelector(videoTrackSelectionFactory);
        loadControl = new DefaultLoadControl();

        player = ExoPlayerFactory.newSimpleInstance(context, trackSelector, loadControl, null, SimpleExoPlayer.STATE_BUFFERING);
```

**Comment by ojw28** [comment]
It's been renamed to AdaptiveTrackSelection (because it's not used for audio as well). Note that it's pretty easy to answer this kind of question yourself just by looking through the project's change history (https://github.com/google/ExoPlayer/commit/ce5c0c18f952caa19b863345252fd267804d7e83).

**Comment by lazarvgd** [comment]
Sorry I am pretty new with ansroid and programming. Thanks :)
