### ISSUE TITLE
Cannot catch BehindLiveWindowException in onPlayerError method

### ISSUE THREAD

**Issue by lazarvgd** [google/ExoPlayer#2803]
Hi I have problem with catching `BehindLiveWindowException` in method 
```
@Override
 public void onPlayerError(ExoPlaybackException error) 
```
method is from ` implements ExoPlayer.EventListener ` interface.

I am trying to logout message that indicates issue with `BehindLiveWindowException`, but unfortunately my overridden method have never been executed.
Can you please give me a hint what am I doing wrong?

Please let me know if you need any additional information.
Thanks :)

**Comment by ojw28** [comment]
Please provide proper reproduction steps; there's nothing we can do with questions this vague.

**Comment by lazarvgd** [comment]
Here is simple player that I have used. If error BLW happens, method onPlayerError have never been called and I cannot reinitiate player.

`public class ExoPlayerActivity extends AppCompatActivity implements ExoPlayer.EventListener {
        SimpleExoPlayer player;
        String path;        // it can be url of video for online streaming or a url of local video

        @Override
        protected void onCreate(@Nullable Bundle savedInstanceState) {
            super.onCreate(savedInstanceState);
            setContentView(R.layout.activity_exoplayer);

            // set your path here
            path=<your path>;

            // 1. Create a default TrackSelector
            BandwidthMeter bandwidthMeter = new DefaultBandwidthMeter();
            TrackSelection.Factory videoTrackSelectionFactory =
                    new AdaptiveVideoTrackSelection.Factory(bandwidthMeter);
            TrackSelector trackSelector =
                    new DefaultTrackSelector(videoTrackSelectionFactory);

            // 2. Create a default LoadControl
            LoadControl loadControl = new DefaultLoadControl();
            // 3. Create the player
            player = ExoPlayerFactory.newSimpleInstance(this, trackSelector, loadControl);

            SimpleExoPlayerView playerView = (SimpleExoPlayerView) findViewById(R.id.player_view);
            playerView.setPlayer(player);
            playerView.setKeepScreenOn(true);
            // Produces DataSource instances through which media data is loaded.
            DataSource.Factory dataSourceFactory = new DefaultDataSourceFactory(this, Util.getUserAgent(this, "ExoPlayer"));

            // Produces Extractor instances for parsing the media data.
            ExtractorsFactory extractorsFactory = new DefaultExtractorsFactory();

            // This is the MediaSource representing the media to be played.
            MediaSource videoSource = new ExtractorMediaSource(Uri.parse(path),
                    dataSourceFactory, extractorsFactory, null, null);
            // Prepare the player with the source.
            player.addListener(this);
            player.prepare(videoSource);
            playerView.requestFocus();
            player.setPlayWhenReady(true);      // to play video when ready. Use false to pause a video
        }


        @Override
        protected void onPause() {
            super.onPause();
            if (player != null) {
                player.setPlayWhenReady(false); //to pause a video because now our video player is not in focus
            }
        }

        @Override
        public void onTimelineChanged(Timeline timeline, Object manifest) {

        }

        @Override
        public void onTracksChanged(TrackGroupArray trackGroups, TrackSelectionArray trackSelections) {

        }

        @Override
        public void onLoadingChanged(boolean isLoading) {

        }

        @Override
        public void onPlayerStateChanged(boolean playWhenReady, int playbackState) {
            switch (playbackState) {
                case ExoPlayer.STATE_BUFFERING:
                    //You can use progress dialog to show user that video is preparing or buffering so please wait
                    break;
                case ExoPlayer.STATE_IDLE:
                    //idle state
                    break;
                case ExoPlayer.STATE_READY:
                    // dismiss your dialog here because our video is ready to play now
                    break;
                case ExoPlayer.STATE_ENDED:
                    // do your processing after ending of video
                    break;
            }
        }

        @Override
        public void onPlayerError(ExoPlaybackException error) {
            // show user that something went wrong. I am showing dialog but you can use your way
            AlertDialog.Builder adb = new AlertDialog.Builder(ExoPlayerActivity.this);
            adb.setTitle("Could not able to stream video");
            adb.setMessage("It seems that something is going wrong.\nPlease try again.");
            adb.setPositiveButton("OK", new DialogInterface.OnClickListener() {
                @Override
                public void onClick(DialogInterface dialog, int which) {
                    dialog.dismiss();
                    finish(); // take out user from this activity. you can skip this
                }
            });
            AlertDialog ad = adb.create();
            ad.show();
        }

        @Override
        public void onPositionDiscontinuity() {
            //Video is not streaming properly
            Log.d("Mayur", "Discontinuity");
        }

        @Override
        protected void onDestroy() {
            super.onDestroy();
            player.release();   //it is important to release a player
        }
    }`

**Comment by ojw28** [comment]
How do you know that a BLW error is actually occurring? In absence of other information, the `onPlayerError` callback not being invoked indicates that there hasn't been an error. . !

Do you see other callbacks being invoked (e.g. if you add logging to `onLoadingChanged`)?

**Comment by lazarvgd** [comment]
I have accidentally ommited System.out.println("error occured"); in onPlayerError method.

Unfortunately, this message have never been invoked , but BLWE has been written in logcat.

**Comment by ojw28** [comment]
Do you see other callbacks being invoked (and does your approach to logging work in those other callbacks)? What do you see happening to the state of the player (e.g. in `onPlayerStateChanged`) when the error occurs?

**Comment by lazarvgd** [comment]
I easily can reproduce the BLWE error by restricting internet speed on emulator(Pixel) and neither `onPlayerStateChanged` or `onPlayerError` has been called.
I have logged `Log.i("onPlayerStateChanged", "Player State Changed");`

this message have never occurred in logcat.

**Comment by andrewlewis** [comment]
Do you see any of the callbacks being invoked at any time (unrelated to the behind live window issue)? At least `onPlayerStateChanged` should be called at some point. If not, that suggests the event listener is not being registered.

**Comment by lazarvgd** [comment]
I see for now that method `onDownstreamFormatChanged`  and `onLoadCanceled` has been called when I start player. I will update you if any other method is triggered.

**Comment by ojw28** [comment]
As Andrew says, it sounds like the listener is just not registered or there's something wrong with the way you're logging the callbacks being invoked. If `onPlayerStateChanged` were not being invoked then I think pretty much everything would be broken!

I'd suggest using the ExoPlayer [demo app](https://github.com/google/ExoPlayer/tree/release-v2/demo) as a starting point. If you see the callbacks not being invoked in the demo app then please provide clear reproduction steps. If the callbacks are being invoked there then the issue lies somewhere in your own code.

**Comment by lazarvgd** [comment]
As I said in comment above, the methods that have been called are:

- onLoadCanceled
- onLoadCompleted
- onLoadStarted
- onDownstreamFormatChanged

Apparently that some listeners are working just fine, but `onPlayerError` and `onPlayerStateChanged` have never been called. 

I have followed example from DemoApp, and my player is working just fine if bandwidth is ok, if I restrict it to 2 mbps, then error occurs.

I will try to play my stream in demo app and let you know the outcome.

**Comment by lazarvgd** [comment]
Hi I have downloaded and changed DemoApp a little bit: 

Here is the code from PlayerActivity that I have changed:

> https://pastebin.com/WbpVJSH1


I have observed if I change emulator network speed I got video stuck I do not get BLWE.
Any suggestions what could be next step?

thanks

UPDATE:

I have found error:
`05-11 10:25:53.558 12221-12221/com.google.android.exoplayer2.demo I/ERROR HLS: com.google.android.exoplayer2.ExoPlaybackException`

this catch BLWE error.

here is my code that I have wrote:

> https://pastebin.com/j2gHwkin

**Comment by ojw28** [comment]
It's unclear from the above whether you've resolved this, but I'm pretty sure there's no ExoPlayer issue here.

**Comment by lazarvgd** [comment]
Hi, I have implemented exoplayer in this way,but still cannot catch BLWException? I think this is a bug, 
 I have overridden the event listener and cannot reinitialize the player because method `onPlayerError`  have never been invoked.
here is the code:


` public class VideoPlayerActivity extends AppCompatActivity implements ExoPlayer.EventListener {

    private SimpleExoPlayerView simpleExoPlayerView;
    private String hlsVideoUri = "http://playertest.longtailvideo.com/adaptive/bbbfull/bbbfull.m3u8";
    private SimpleExoPlayer player;
    private ProgressBar progressBar;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_video_player);

        // 1. Create a default TrackSelector
        Handler mainHandler = new Handler();
        BandwidthMeter bandwidthMeter = new DefaultBandwidthMeter();
        TrackSelection.Factory videoTrackSelectionFactory = new AdaptiveVideoTrackSelection.Factory(bandwidthMeter);
        TrackSelector trackSelector = new DefaultTrackSelector(videoTrackSelectionFactory);

        // 2. Create a default LoadControl
        LoadControl loadControl = new DefaultLoadControl();


        // 3. Create the player
        player = ExoPlayerFactory.newSimpleInstance(this, trackSelector, loadControl);

        simpleExoPlayerView = (SimpleExoPlayerView) findViewById(R.id.player_view);
        simpleExoPlayerView.setPlayer(player);

        // Measures bandwidth during playback. Can be null if not required.
        DefaultBandwidthMeter defaultBandwidthMeter = new DefaultBandwidthMeter();
        // Produces DataSource instances through which media data is loaded.
        DataSource.Factory dataSourceFactory = new DefaultDataSourceFactory(this,
                Util.getUserAgent(this, "Exo2"), defaultBandwidthMeter);
        // Produces Extractor instances for parsing the media data.
        ExtractorsFactory extractorsFactory = new DefaultExtractorsFactory();
        // This is the MediaSource representing the media to be played.
        HlsMediaSource hlsMediaSource = new HlsMediaSource(Uri.parse(hlsVideoUri), dataSourceFactory, mainHandler, new AdaptiveMediaSourceEventListener() {
            @Override
            public void onLoadStarted(DataSpec dataSpec, int dataType, int trackType, Format trackFormat, int trackSelectionReason, Object trackSelectionData, long mediaStartTimeMs, long mediaEndTimeMs, long elapsedRealtimeMs) {

            }

            @Override
            public void onLoadCompleted(DataSpec dataSpec, int dataType, int trackType, Format trackFormat, int trackSelectionReason, Object trackSelectionData, long mediaStartTimeMs, long mediaEndTimeMs, long elapsedRealtimeMs, long loadDurationMs, long bytesLoaded) {

            }

            @Override
            public void onLoadCanceled(DataSpec dataSpec, int dataType, int trackType, Format trackFormat, int trackSelectionReason, Object trackSelectionData, long mediaStartTimeMs, long mediaEndTimeMs, long elapsedRealtimeMs, long loadDurationMs, long bytesLoaded) {

            }

            @Override
            public void onLoadError(DataSpec dataSpec, int dataType, int trackType, Format trackFormat, int trackSelectionReason, Object trackSelectionData, long mediaStartTimeMs, long mediaEndTimeMs, long elapsedRealtimeMs, long loadDurationMs, long bytesLoaded, IOException error, boolean wasCanceled) {

            }

            @Override
            public void onUpstreamDiscarded(int trackType, long mediaStartTimeMs, long mediaEndTimeMs) {

            }

            @Override
            public void onDownstreamFormatChanged(int trackType, Format trackFormat, int trackSelectionReason, Object trackSelectionData, long mediaTimeMs) {

            }
        });

        player.addListener(this);
        player.prepare(hlsMediaSource);
        simpleExoPlayerView.requestFocus();
        player.setPlayWhenReady(true);

        progressBar = (ProgressBar) findViewById(R.id.progressBar);
    }

    @Override
    public void onTimelineChanged(Timeline timeline, Object manifest) {

    }

    @Override
    public void onTracksChanged(TrackGroupArray trackGroups, TrackSelectionArray trackSelections) {

    }

    @Override
    public void onLoadingChanged(boolean isLoading) {

    }

    @Override
    public void onPlayerStateChanged(boolean playWhenReady, int playbackState) {

        switch (playbackState) {
            case ExoPlayer.STATE_BUFFERING:
                //You can use progress dialog to show user that video is preparing or buffering so please wait
                progressBar.setVisibility(View.VISIBLE);
                break;
            case ExoPlayer.STATE_IDLE:
                //idle state
                break;
            case ExoPlayer.STATE_READY:
                // dismiss your dialog here because our video is ready to play now
                progressBar.setVisibility(View.GONE);
                break;
            case ExoPlayer.STATE_ENDED:
                // do your processing after ending of video
                break;
        }
    }

    @Override
    public void onPlayerError(ExoPlaybackException error) {

        AlertDialog.Builder adb = new AlertDialog.Builder(VideoPlayerActivity.this);
        adb.setTitle("Could not able to stream video");
        adb.setMessage("It seems that something is going wrong.\nPlease try again.");
        adb.setPositiveButton("OK", new DialogInterface.OnClickListener() {
            @Override
            public void onClick(DialogInterface dialog, int which) {
                dialog.dismiss();
                finish(); // take out user from this activity. you can skip this
            }
        });
        AlertDialog ad = adb.create();
        ad.show();
    }

    @Override
    public void onPositionDiscontinuity() {

    }

    @Override
    protected void onPause() {
        super.onPause();
        if (player != null) {
            player.setPlayWhenReady(false); //to pause a video because now our video player is not in focus
        }
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        player.release();
    }
}`

**Comment by ojw28** [comment]
As per above:

> If you see the callbacks not being invoked in the demo app then please provide clear reproduction steps.

along with a proper bug report, as is requested in our issue template. There is still no firm evidence in this bug that the `BehindLiveWindowException` you're expecting to be notified of is even occurring inside of the player, except "but BLWE has been written in logcat" with no bug report provided so we can actually see the logging you're referring to.

We're not going to look at this without complete information (including a full bug report - a small snippet of logcat is not sufficient) and proper reproduction steps.
