### ISSUE TITLE
HLS Livestream crash and device reboot on Nexus 10

### ISSUE THREAD

**Issue by starchey** [google/ExoPlayer#2806]
### Issue description
Playing the following HLS livestream, {sent in email}, on a Nexus 10 running 5.1.1 will cause the app to crash and the device to reboot. This is happening 100% on this device, but is not affecting any other Android phones or tablets we have tested. We also notice it only happens when the higher resolution video track is selected, as if we force it to play the lowest, the crash does not occur.

### Reproduction steps
1) Modify ExoPlayer demo app to play live stream mentioned above (have been modifying a URI in media.exolist.json)
2) Play the stream
3) Stream will start at lowest resolution track, 400x224, then switch to highest, 1280x720

Within five minutes (typically within one minute), the app will crash and the device will reboot.

### Link to test content
Livestream URL sent in email.

### Version of ExoPlayer being used
Have tested with ExoPlayer 2.4.0 and latest from dev-v2 branch as of 05/10/17 12:32 MDT. Issue happens in both.

### Device(s) and version(s) of Android being used
Nexus 10 Tablet running 5.1.1
This is the only device we have been able to reproduce on, and we can reproduce 100% on this device

### A full bug report captured from the device
Bug report available here: https://www.dropbox.com/s/upflxydm5fejoxs/bugreport.txt?dl=0

**Comment by ojw28** [comment]
I'm able to reproduce this. Whilst it's almost certainly a device issue, we'll take a look and see if there's anything we can do to work around it.

**Comment by ojw28** [comment]
I think the workaround ref'd above fixes this issue.
