### ISSUE TITLE
Playing WMA audio stream failed even with FFMPEG !

### ISSUE THREAD

**Issue by satyres** [google/ExoPlayer#2807]
Hi , 
After successfully compiled FFMPEG library following the tutorial.
I've added --enable-decoder=asf \ to the config file and i've tried to play this stream 
http://techibes.wma.audio.tempo.fm/techibes/techib01.wma
, but it has failed 
saying that no suitable decode has been found ?
Please can anyone help me to solve this problem
Thanks

**Comment by andrewlewis** [comment]
ExtractorMediaSource doesn't include an extractor for WMA containers, so you'd need to implement one.

You'd also need to modify the FfmpegLibrary class so that it picks the `asf` FFmpeg decoder when it sees the relevant MIME type.

**Comment by ojw28** [comment]
Supporting WMA is tracked by https://github.com/google/ExoPlayer/issues/2155, but is low priority (i.e. is unlikely to get done unless someone outside of the core development team implements it and sends it as a pull request).

**Comment by satyres** [comment]
Thank you all for your quick answers , 
@andrewlewis  how can i developpe my own ExtractorMediaSource is there any tutorial how to achieve this ?
@ojw28 WMA in #2155 can't help me to solve my problem ?
As it said in the Tutorial you need only to add the WMA support to the config ffmpeg file , and Exoplayer will handle the rest ?
can't understand how to do this ! 
Regards

**Comment by satyres** [comment]
@andrewlewis  i've added the mimetype asf to FfmpegLibrary
in MimeType i've added :   public static final String AUDIO_ASF = BASE_TYPE_AUDIO + "/x-ms-wma";
and in FFmpegLibrary : case MimeTypes.AUDIO_ASF: return "wma1";
is it correct ?
what should i do next ?

**Comment by andrewlewis** [comment]
#2155 tracks supporting WMA containers. Doing that involves implementing an `Extractor` subclass that parses the structure of WMA files. I'm afraid we don't have the resources to give guidance on how to implement specific extractors, but your best option is probably to start by reading/understanding one of the existing Extractor implementations.

**Comment by satyres** [comment]
This seems quite hard to understand how Extractors works ! Exoplayer is intended to be customizable but without any guidance it's really hard !
It's not easy to work with audio streams , i've been struggling last weeks using ffmpeg only to try to play a local MP3 file after successfully build ffmpeg and the library as well , it works on my s4 but the sound was not clear at all !!
i've been searching on the net for weeks for good tutorial how to use ffmpeg with android ! and i've been unsuccessful to find anything , no books no tutorial , nothing i'm quite amazed how do people can work with such library on Android ! any way Thank you for your help.

**Comment by andrewlewis** [comment]
Some customizations are more complicated than others -- you're adding support for a new file format and the amount of work required will probably depend on how difficult it is to parse its structure. Hopefully the documentation on the Extractor interface and the provided implementations provide enough information to get started.

Regarding MP3 playback sounding wrong, if you file a new issue with the requested details we'll try to investigate. Note that you should be able to [play MP3s](https://developer.android.com/guide/topics/media/media-formats.html) on Android devices without resorting to using the ffmpeg extension, however.
