### ISSUE TITLE
How to pre-load/cache mp3s and other non-adaptive formats

### ISSUE THREAD

**Issue by lzyang187** [google/ExoPlayer#2808]
Can give me sample how cache mp3 with outputstream? And How to play mp3 from cache. I have found CacheDataSource, but I don't know how it use it. thx!

**Comment by lforxeverc** [comment]
I also need the help,thx!

**Comment by ojw28** [comment]
We will provide a blog post and/or documentation soon. Marking this as an enhancement for tracking purposes.

**Comment by escamoteur** [comment]
Would be awesome because I think using multiple Players cannot be the best solution.

**Comment by DnAGroup** [comment]
@escamoteur did you find any solution to your concern?

**Comment by escamoteur** [comment]
Unfortunately not. Still waiting for help from here

**Comment by erdemguven** [comment]
We just published a blog post: [Pre-caching/Downloading progressive streams in ExoPlayer](https://medium.com/google-exoplayer/pre-caching-downloading-progressive-streams-in-exoplayer-3a816c75e8f6)

I hope you'll find it useful.
