### ISSUE TITLE
Invoke ExoPlayer with DRM using AM

### ISSUE THREAD

**Issue by kmoza** [google/ExoPlayer#2813]
Hi,
I am trying to invoke the `PlayerActivity ` directly using activity manager and would like to do a secure playback using `DRM`. I know how to directly launch the `PlayerActivity ` using adb but dont know how to pass an URL as argument to `PlayerActivity ` for doing secure playback. 

Could someone help me on what option or arguments can be used to directly supply an URL to `PlayerActivity ` to do a secure playback.

**Comment by ojw28** [comment]
The intent structure for the demo app is described [here](https://google.github.io/ExoPlayer/demo-application.html). How to fire intents programmatically is a general Android question; you'd be best asking on StackOverflow.
