### ISSUE TITLE
Wrong audio duration

### ISSUE THREAD

**Issue by vicpinm** [google/ExoPlayer#2818]
ExoPlayer version: 2.4
Android version: any
Device: any

Hi, I have an audio with a wrong audio duration reported by exoplayer, with the method getDuration() of SimpleExoPlayer class. The link is:

http://www.ivoox.com/desmontando-a-darwin-maximo-sandin-bioantropologo_mn_273611_api_1.mp3

I think there is something wrong with this audio, because exoplayer returns about 8 seconds, but it lasts 47 minutes. If you open the same link in a browser like chrome, it shows the right duration.

**Comment by ojw28** [comment]
It appears the URL you provided sporadically redirects to (at least two) different destinations. The actual content after redirection is different depending on which destination you're redirected to. For example, I saw these redirections and corresponding content lengths:

http://podcastcdn-11.ivoox.com/audio/1/1/6/3/273611.mp3?secure=tfnju6iCTdvdWZU7NTZnmg==,1494632328
Content-Length: 22589648

http://podcastcdn-7.ivoox.com/audio/1/1/6/3/desmontando-a-darwin-maximo-sandin-bioantropologo273611.mp3?secure=Z-_Y4FTl2kj_j1-BJBA_hw==,1494632302
Content-Length: 22663670

The longer of the two appears to have an extra ~9 seconds of audio prefixed on the front of the stream. What I suspect is happening is that the server, for whatever reason, is somehow prefixing the response with another ~9 second long mp3 file. I don't think the type of concatenation that the server is doing is valid. In particular, I think the XING header from the ~9 second long file is being left intact in the concatenated response. When ExoPlayer sees this XING header it uses it to calculate the duration of the media, and (correctly!) determines it to be ~9 seconds long. If the server wants to be concatenating media this way then it needs to ensure that the end result is actually a well-formed media file in its own right.
