### ISSUE TITLE
modify the background color of SurfaceView

### ISSUE THREAD

**Issue by wlianghe00** [google/ExoPlayer#2821]
exoplayer version r2.4.0
how can i modify the background color of SurfaceView

![ph](https://cloud.githubusercontent.com/assets/3353880/26023545/88dab706-37f0-11e7-91d5-0fb0b736e64b.png)

i want Left and right blanks are modified to black

**Comment by Khoosham** [comment]
set the color in xml layout
android:background="#yourcolor"

**Comment by ojw28** [comment]
This is not really an ExoPlayer question. Please ask general Android questions on StackOverflow.

**Comment by hardikJoshi123** [comment]
Hello @Khoosham  i want to create same layout as yours (in your screenshot), can you please share relivent code?

**Comment by Khoosham** [comment]
@hardikJoshi123  what screenshot i cant see any ?

**Comment by hardikJoshi123** [comment]
@Khoosham  thanks for your reply. I am talking about screenshot attached bellow. 

![surface](https://user-images.githubusercontent.com/2733493/27167718-e0ee7fa2-51bf-11e7-9532-e2b981811bc7.png)

 I am using default exoplayerview in my xml. is this surfaceview with exoplayer ? I want to achive same UI with fullscreen button. Thanks!

**Comment by Khoosham** [comment]
@hardikJoshi123 

To customize the layout of PlaybackControlView throughout your app, or just for certain configurations, you can define exo_playback_control_view.xml layout file in your application res/layout directories. These layouts will override the one provided by the ExoPlayer library, and will be inflated for use by PlaybackControlView.

More information here: https://medium.com/google-exoplayer/customizing-exoplayers-ui-components-728cf55ee07a

Also if you want to add that u can specify custom layout in PlayerView like so:
```
<com.google.android.exoplayer2.ui.SimpleExoPlayerView android:id="@+id/player_view"
      android:layout_width="match_parent"
      android:layout_height="match_parent"
      app:controller_layout_id="@layout/custom_controls"/>
```

**Comment by hardikJoshi123** [comment]
Yea I did that @Khoosham 

 I am using viewPager. I want to display videos in my viewpager items. What I faced issue : 

 All videos are playing at same time and I can hear all video sounds all together. I also added fullscreen button, now when I click on it, I want to show same video with same progress as entire screen (fullscreen). 

 Thanks!
