### ISSUE TITLE
DRMed live stream not being played  after NonDRM live stream

### ISSUE THREAD

**Issue by erenbakac** [google/ExoPlayer#2822]
Hi,

I have a problem while playing DRMed live stream after playing NoDRM live stream on the same player. I call releasePlayer method  before playing for each stream. I shared related logs. I also snipped the network using Fiddler. You can see  all requests from the player.  I have sent log files to "dev.exoplayer@gmail.com"  
Thank you.

**Comment by marcbaechinger** [comment]
Hi

I think I recall having seen this as well but it seems to me it was device specific. 

Can you please provide more info? Here are the parts of the issue template which are important for this kind of issue:

Does this also happen when you create a completely new ExoPlayer instance?

### Link to test content
Provide a link to media that reproduces the issue. If you don't wish to post it
publicly, please submit the issue, then email the link to
dev.exoplayer@gmail.com including the issue number in the subject line.

### Version of ExoPlayer being used
Specify the absolute version number. Avoid using terms such as "latest".

### Device(s) and version(s) of Android being used
Specify the devices and versions of Android on which the issue can be
reproduced, and how easily it reproduces. If possible, please test on multiple
devices and Android versions.

### A full bug report captured from the device
Capture a full bug report using "adb bugreport". Output from "adb logcat" or a
log snippet is NOT sufficient. Please attach the captured bug report as a file.
If you don't wish to post it publicly, please submit the issue, then email the
bug report to dev.exoplayer@gmail.com including the issue number in the subject
line.

**Comment by erenbakac** [comment]
Hi,

I have sent these details to "dev.exoplayer@gmail.com" including all logs.

**Comment by ojw28** [comment]
Closing as obsolete. Apologies that it got ignored, but it's old to the extent that it may well not be relevant at this point! Please file a new issue if this is still a problem.

> I have a problem while playing DRMed live stream after playing NoDRM live stream on the same player. I call releasePlayer method before playing for each stream.

You should only be calling `release` on the player once you're done with using it. So it doesn't sound right that you would be calling a release method before playing something. Perhaps that's the root issue here?
