### ISSUE TITLE
A more convenient access to certain lifecycle event 

### ISSUE THREAD

**Issue by q-litzler** [google/ExoPlayer#2823]
Hello,

This is a request for a small adjustment.

In the `LoadControl` interface lies a certain number of very useful methods related to the exoplayer lifecycle:

onPrepared()
onReleased()
onStopped()

However at this point, we can only pass one instance of a `LoadControl` implementation into the `ExoPlayerFactory`, and by default this implementation is `DefaultLoadControl`, a class marked as final.

Right now, the only way I can access these callbacks in my project is by implementing my own `LoadControl` logic (that is copy pasting the DefaultLoadControl class and tweaking it a bit).

I think these kind of callbacks deserve their own separate interface so they can be accessed more conveniently.

Thanks

**Comment by ojw28** [comment]
These aren't intended for general purpose use outside of the player. They're intended for the `LoadControl` specifically. Note also that they're invoked directly on the player's internal playback thread, which is normally not what you'd want if you're trying to implement some external logic.

It's likely that whatever you're trying to do would be better off done in some other way, for example using an `ExoPlayer.EventListener`. What is it that you're trying to do, and why are the existing event listener callbacks not sufficient?

**Comment by q-litzler** [comment]
What I need is to know precisely when the player is done preparing its `MediaSource`. I would love if there was a dedicated method in `ExoPlayer.EventListener` for that, but that is not the case right now.
That's why I have been using the `LoadControl` interface, I know it's not meant to be used for this, but it's the only solution I could come up with. I'm not asking for a modification of the `LoadControl` interface, it's fine as it is.
But a similiar `onPrepared` callback in `ExoPlayer.EventListener` would be greatly appreciated.

Consider this simple scenario: I want to display a player only when the source is 100% ready to be played (It is part of the advertisement experience of the app I'm working on) and I want the assurance that this callback will not be called several times over the course of the MediaSource lifecycle (like it would be if I were using the `onLoadingChanged` or `onPlayerStateChanged` methods for example)

**Comment by ojw28** [comment]
I don't think `LoadControl.onPrepared` is called when you think it is. It's called as soon as the playback thread receives the `MediaSource` but before it's actually done anything with it. There will typically be zero buffer at the point when it's fired. So it doesn't seem at all correct for the use case you describe.

If you want to do something when the player is ready to be played then you should use `ExoPlayer.EventListener.onPlayerStateChanged`. The first call with `playbackState == ExoPLayer.STATE_READY` is the point at which the player is ready.

**Comment by q-litzler** [comment]
Ok, good to know. Thank you.
