### ISSUE TITLE
Reuse decoder instances on re-preparation + when seeking to a different period

### ISSUE THREAD

**Issue by ojw28** [google/ExoPlayer#2826]
ExoPlayer V2 re-uses decoder instances where possible as it plays through multiple periods of content (e.g. that have been concatenated using `ConcatenatingMediaSource`).

However the decoders are [always released](https://github.com/google/ExoPlayer/blob/ecb62cccd50d891338253faf768d400df0ecfa66/library/core/src/main/java/com/google/android/exoplayer2/ExoPlayerImplInternal.java#L635) and re-instantiated if the user explicitly seeks to a period other than the one currently being played, even in cases where it's possible that the instances could be retained and re-used. We should look at optimizing this case.

**Comment by ojw28** [comment]
We should also look at re-using decoder instances when a new MediaSource is passed via prepare(), where it's possible to do so.

**Comment by zsmatyas** [comment]
+1 :wink:

**Comment by BrainCrumbz** [comment]
Is there any help we can provide in improving this aspect? Have you already thought about potential design changes, or already have an idea that we can try to implement? TA

**Comment by ojw28** [comment]
Work is in progress. There's a [design proposal here](https://docs.google.com/document/d/1bR5KVn4fu_rPwPPbTAN8ZaWeQ8ehJHtDzCl3iR3AAVU/edit?usp=sharing). Feel free to post any comments you have. I don't think we need any help on the implementation side.

**Comment by Romantic-LiXuefeng** [comment]
> Work is in progress. There's a [design proposal here](https://docs.google.com/document/d/1bR5KVn4fu_rPwPPbTAN8ZaWeQ8ehJHtDzCl3iR3AAVU/edit?usp=sharing). Feel free to post any comments you have. I don't think we need any help on the implementation side.

@ojw28  I read the linked design proposal. It's so great. Is there a similar public design documents? If have, please give me the links. I am reading the ExoPlayer source code.Thanks!

**Comment by ojw28** [comment]
Thanks for the feedback! There aren't, but I think it's a good idea for us to try and publish more of our design documents externally. This was a bit of a trial run for doing that.

**Comment by Romantic-LiXuefeng** [comment]
@ojw28  Reselect tracks manually when playing HLS stream ,and then decoder instances re-init. Whether reuse decoder instances at this situation is feasible？

**Comment by ojw28** [comment]
That doesn't happen when I try, except in the case where the re-selection is selecting a video stream bigger than anything that the decoder was previously configured to play (in this case release and re-initialization is necessary because the existing decoder wont have sufficiently large buffers).

**Comment by Romantic-LiXuefeng** [comment]
> except in the case where the re-selection is selecting a video stream bigger than anything that the decoder was previously configured to play

Dose this mean re-selection from low bit rate video stream to high bit rate video stream?

@ojw28 
 Whether I switch from high bit rate to low bit rate or from low bit rate to high bit rate, The video decoder instances always needs [release](https://github.com/google/ExoPlayer/blob/71f72c59537711399dc5496136dd6b867acc6d77/library/core/src/main/java/com/google/android/exoplayer2/ExoPlayerImplInternal.java#L1045) and re-initialization.

ExoPlayer version: 2.9.0
Test url  : 
```
{
        "name": "Apple 16x9 basic stream",
        "uri": "https://devstreaming-cdn.apple.com/videos/streaming/examples/bipbop_16x9/bipbop_16x9_variant.m3u8"
 },
```

**Comment by Romantic-LiXuefeng** [comment]
@ojw28 Did you already had the time to look into this? Is there anything I can do to support you?

**Comment by ojw28** [comment]
Decoder re-use is not part of the 2.9.0 release, or any release to date. It's in the `dev-v2` branch only. Also note that this is still an open issue.

**Comment by ojw28** [comment]
Closing because this is supported in `2.10.0` (there is an alpha release available, and the final release is coming soon).

**Comment by Romantic-LiXuefeng** [comment]
> except in the case where the re-selection is selecting a video stream bigger than anything that the decoder was previously configured to play
> 
> Dose this mean re-selection from low bit rate video stream to high bit rate video stream?
> 
> @ojw28
> Whether I switch from high bit rate to low bit rate or from low bit rate to high bit rate, The video decoder instances always needs release and re-initialization.
> 
> ExoPlayer version: 2.9.0
> Test url :
> 
> {
>         "name": "Apple 16x9 basic stream",
>         "uri": "https://devstreaming-cdn.apple.com/videos/streaming/examples/bipbop_16x9/bipbop_16x9_variant.m3u8"
>  },

So great!  @ojw28 Is there possible to reuse the decoder in this condition , like the above description ?

**Comment by ojw28** [comment]
> Whether I switch from high bit rate to low bit rate or from low bit rate to high bit rate, The video decoder instances always needs release and re-initialization.

As in my previous response about this, I do not see this happening for high-resolution to low-resolution track re-selection. Neither do I see it happening for low-resolution to high-resolution track re-selection provided the decoder was originally configured for the high-resolution (i.e. high-resolution -> low-resolution -> high-resolution track re-selection will not cause any decoder re-initialization, because the decoder would have originally been configured for the high resolution).

I think you're either misinterpreting the logging that happens when a decoder is flushed (but not re-initialized), or you're not using 2.10.0, or something else is going on. In either case, if you think re-use is not happening when it should be happening, please file a new bug containing all of the information requested in the issue template, along with a full bug report.
