### ISSUE TITLE
Not getting where code is going wrong with drmSeesion

### ISSUE THREAD

**Issue by Pash97** [google/ExoPlayer#2827]
Getting Following error
------------------------
Internal track renderer error.
 com.google.android.exoplayer.ExoPlaybackException: java.lang.IllegalStateException: Media does not support uuid: edef8ba9-79d6-4ace-a3c8-27dcd51d21ed
     at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec.

**Comment by ojw28** [comment]
This issue tracker is not designed for you to copy/paste large amounts of your own code into to have other people debug it for you. Please can you fill out the issue template properly when filing future issues. In particular, please provide a link to the test content that wont play, along with any necessary details (e.g. license server) that would be necessary to play it.

ClearKey DRM is not supported in ExoPlayer V1. You need to be using V2 (the latest release is 2.4.0), as already suggested in https://github.com/google/ExoPlayer/issues/2798. Try starting with the V2 demo app. Add your ClearKey sample into `media.exolist.json`, which is a file in the demo app, like:

```
  {
    "name": "ClearKey DASH",
    "samples": [
      {
        "name": "Test Stream",
        "uri": "http://your-test-content-url",
        "extension": "mpd",
        "drm_scheme": "cenc",
        "drm_license_url": "your-license-url"
      }
    ]
  },
```

**Comment by Pash97** [comment]
Ok..Please tell me widevine and clearkey are different ..? if yes please help me how can i deal with clearkey i wrote widevine class as follow. please give me sample for clearkey if possible

**ClearkeyMediaDrmcallback.java**
------------------------------
import android.annotation.TargetApi;
import android.media.MediaDrm;
import android.os.Build;
import android.text.TextUtils;

import com.google.android.exoplayer.drm.MediaDrmCallback;
import com.google.android.exoplayer.util.Util;

import java.io.IOException;
import java.util.UUID;


public class ClearkeyMediaDrmcallback implements MediaDrmCallback {

    private static final String CLEARKEY_GTS_DEFAULT_BASE_URI =
            "http://"ip"/media/clearkey.json";

    private final String defaultUri;

    public ClearkeyMediaDrmcallback(String contentId, String provider) {
        String params = "?video_id=" + contentId + "&provider=" + provider;
        defaultUri = CLEARKEY_GTS_DEFAULT_BASE_URI + params;
    }

    public ClearkeyMediaDrmcallback(boolean b) {
        defaultUri = null;
    }

    @TargetApi(Build.VERSION_CODES.JELLY_BEAN_MR2)
    @Override
    public byte[] executeProvisionRequest(UUID uuid, MediaDrm.ProvisionRequest request) throws IOException {
        String url = request.getDefaultUrl() + "&signedRequest=" + new String(request.getData());
        return Util.executePost(url, null, null);
    }

    @TargetApi(Build.VERSION_CODES.JELLY_BEAN_MR2)
    @Override
    public byte[] executeKeyRequest(UUID uuid, MediaDrm.KeyRequest request) throws IOException {
        String url = request.getDefaultUrl();
        if (TextUtils.isEmpty(url)) {
            url = defaultUri;
        }
        return Util.executePost(url, request.getData(), null);
    }
}

**Comment by ojw28** [comment]
As already explained above, if you want a sample:
1. Stop using V1 ExoPlayer.
1. Check out the V2 demo app.
1. Add your content to `media.exolist.json` as described above.

**Comment by Pash97** [comment]
Video is stopping after some time.

**Logcat**

Renderer error.
                         com.google.android.exoplayer2.ExoPlaybackException
                             at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:708)
                             at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:511)
                             at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:479)
                             at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:308)
                             at android.os.Handler.dispatchMessage(Handler.java:98)
                             at android.os.Looper.loop(Looper.java:148)
                             at android.os.HandlerThread.run(HandlerThread.java:61)
                          Caused by: android.media.MediaCodec$CryptoException: Decryption Error
                             at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
                             at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:2292)
                             at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:699)
                             at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:511) 
                             at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:479) 
                             at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:308) 
                             at android.os.Handler.dispatchMessage(Handler.java:98) 
                             at android.os.Looper.loop(Looper.java:148) 
                             at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by Pash97** [comment]
Sorry for updating this issue above error resolved..Thank you for your needful help.

**Comment by rajat70** [comment]
### ClearKey Not Working

I'm trying to DASH stream an encrypted file using ClearKey DRM. Details of entry added in `media.exolist.json` are given below:

```
{
        "name": "ClearKey",
        "uri": "https://drmdemo-94ea7.firebaseapp.com/encrypt/manifest.mpd",
        "extension": "mpd",
        "drm_scheme": "cenc",
        "drm_license_url": "https://drmdemo-94ea7.firebaseapp.com/encrypt/key.json"
}
```

This is the error that I'm getting 
`Caused by: com.google.android.exoplayer2.drm.DrmSession$DrmSessionException: java.lang.IllegalStateException: Media does not support uuid: 1077efec-c0b2-4d02-ace3-3c1e52e2fb4b`

Can you help me out with what I'm doing wrong?

**Comment by ojw28** [comment]
@rajat70 - It doesn't look like the media is encrypted with ClearKey DRM. The only PSSH box in the actual stream has UUID set to `67706163-6365-6e63-6472-6d746f6f6c31`, which is apparently a UUID for "GPAC Player". I'd expect to see a PSSH box with UUID `1077efec-c0b2-4d02-ace3-3c1e52e2fb4b` for ClearKey encrypted content. Alternatively, that box should be specified in the DASH manifest.

**Comment by hishamMuneer** [comment]
@ojw28 "I'd expect to see a PSSH box with UUID 1077efec-c0b2-4d02-ace3-3c1e52e2fb4b for ClearKey encrypted content." - How can we create pssh box?

**Comment by ojw28** [comment]
The right UUID might also be e2719d58-a985-b3c9-781a-b030af78d30e, I'm not sure. I'm really not the right person to ask. I've never prepared any ClearKey content, and ClearKey support in ExoPlayer was added by an external contributor (https://github.com/google/ExoPlayer/pull/2372).

**Comment by hishamMuneer** [comment]
@ojw28 : 

## DRM File
```
<?xml version="1.0" encoding="UTF-8"?>
<GPACDRM type="CENC AES-CTR">
<!-- example for GPAC 'clear' DRM System - keys are listed after the content and UL follows -->
<DRMInfo type="pssh" version="1" cypherOffset="9" cypherKey="0x1077EFECC0B24D02ACE33C1E52E2FB4B" cypherIV="0x00000000000000000000000000000001">
<BS ID128="1077EFECC0B24D02ACE33C1E52E2FB4B"/>
<BS value="2" bits="32"/>
<BS ID128="0x279926496a7f5d25da69f2b3b2799a7f"/>
<BS ID128="0x676cb88f302d10227992649885984045"/>
<BS bits="8" string="CID=Toto"/>
<BS ID128="0xccc0f2b3b279926496a7f5d25da692f6"/>
<BS ID128="0xccc0f2b3b279926496a7f5d25da692d6"/>
</DRMInfo>
<CrypTrack trackID="1" IsEncrypted="1" IV_size="16" first_IV="0x0a610676cb88f302d10ac8bc66e039ed" saiSavedBox="senc">
<key KID="0x279926496a7f5d25da69f2b3b2799a7f" value="0xccc0f2b3b279926496a7f5d25da692f6"/>
<key KID="0x676cb88f302d10227992649885984045" value="0xccc0f2b3b279926496a7f5d25da692d6"/>
</CrypTrack>
</GPACDRM>
```

## MPD File

```
<?xml version="1.0"?>
<!-- MPD file Generated with GPAC version 0.7.2-DEV-rev195-g3824d94-master  at 2017-08-03T12:53:33.668Z-->
<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" minBufferTime="PT1.500S" type="static" mediaPresentationDuration="PT0H9M56.459S" maxSegmentDuration="PT0H0M5.000S" profiles="urn:mpeg:dash:profile:isoff-on-demand:2011,http://dashif.org/guidelines/dash264" xmlns:cenc="urn:mpeg:cenc:2013">
 <ProgramInformation moreInformationURL="http://gpac.io">
  <Title>sh_160x90_250k_encrypted_dash.mpd generated by GPAC</Title>
 </ProgramInformation>

 <Period duration="PT0H9M56.459S">
  <AdaptationSet segmentAlignment="true" maxWidth="160" maxHeight="90" maxFrameRate="24" par="16:9" lang="und" subsegmentAlignment="true" subsegmentStartsWithSAP="1">
   <ContentProtection schemeIdUri="urn:mpeg:dash:mp4protection:2011" value="cenc" cenc:default_KID="27992649-6a7f-5d25-da69-f2b3b2799a7f">
   <cenc:pssh></cenc:pssh>
   </ContentProtection>
   <Representation id="1" mimeType="video/mp4" codecs="avc1.64000D" width="160" height="90" frameRate="24" sar="1:1" startWithSAP="1" bandwidth="255335">
    <BaseURL>sh_160x90_250k_encrypted_dashinit.mp4</BaseURL>
    <SegmentBase indexRangeExact="true" indexRange="1168-3107">
      <Initialization range="0-1167"/>
    </SegmentBase>
   </Representation>
  </AdaptationSet>
 </Period>
</MPD>
```

**Comment by ojw28** [comment]
It's not within the scope of this issue tracker for us to assist with your media, sorry.

**Comment by hishamMuneer** [comment]
@ojw28  OK. Forget my media. I am getting the following error, what does this error mean?

## Error
`Illegal state exception: Failed to get key request: Unsupported scheme or data format (-2006)`

**Comment by hishamMuneer** [comment]
@ojw28 Or if you can tell where is the implemention of the getKeyRequest() method written specified in com.google.android.exoplayer2.drm.FrameworkMediaDrm class. 

```
 @Override
  public KeyRequest getKeyRequest(byte[] scope, byte[] init, String mimeType, int keyType,
      HashMap<String, String> optionalParameters) throws NotProvisionedException {
    final MediaDrm.KeyRequest request = mediaDrm.getKeyRequest(scope, init, mimeType, keyType,
        optionalParameters);
    return new KeyRequest() {
      @Override
      public byte[] getData() {
        return request.getData();
      }

      @Override
      public String getDefaultUrl() {
        return request.getDefaultUrl();
      }
    };
  }
```

**Comment by ojw28** [comment]
It means the media only contains a PSSH box with an unsupported UUID, as already described above. It looks like the stream is encrypted with some kind of GPAC specific DRM scheme, rather than ClearKey. It is not a DRM scheme that we support.

**Comment by hishamMuneer** [comment]
@wasabeef Can you help me by providing a working clear key example and by guiding how to create a pssh box? Your Clear Key example provided in exolist.json is returning 404.  Dead Link: http://html5.cablelabs.com:8100/cenc/ck/dash.mpd

## Sample
```

 - {
 -    "name": "ClearKey DASH",
 -    "samples": [
 -      {
 -        "name": "Big Buck Bunny (CENC ClearKey)",
 -        "uri": "http://html5.cablelabs.com:8100/cenc/ck/dash.mpd",
 -        "extension": "mpd",
 -        "drm_scheme": "cenc",
 -        "drm_license_url": "https://wasabeef.jp/demos/cenc-ck-dash.json"
 -      }
 -    ]
 -  }
```
