### ISSUE TITLE
Frame frozen for up to 10 seconds when scrubbing

### ISSUE THREAD

**Issue by brAzzi64** [google/ExoPlayer#2829]
We're currently on r.1.5.16, and are seeing an issue (that's been there since at least r.1.5.6) in which very often when jumping to a different position in a video, while playing, the audio will immediately start playing at the new position, but the video will remain frozen for somewhere between 1 to 10 seconds.

The frame in which the video freezes, is the one corresponding to **jumpPosition + frozenPeriod**; meaning that the user is presented with a "future" frame during "frozenPeriod" seconds, from which the video will smoothly continue playing once the time corresponding to that frame hits.

Our videos are an HLS playlist, containing different streams for various resolutions. However, this still happens when using one of those single streams directly. These per-resolution streams however, are actually a chunked playlist.

This is what entries on the original HLS playlist look like:

#EXTM3U

...

#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1200000
80299_04_03_MM30_exploreTown_mixed_1200.mp4.m3u8?3GLWJ2yr2dFoYAudKlIkh_k2hf0U23WV6XejfpPuicCDmNnepWkd1z0IrrwNVzBp0j_rySGHUadEv627Pki3YRkh-Xei5MOxoDDL2hvArZuTN_ZBn9uzfO6RN182FE8KlWFpxbSTRLsI6hJ5FalbsgkI7f0N18xyKUc1Xag554s

#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1650000
80299_04_03_MM30_exploreTown_mixed_1650.mp4.m3u8?3GLWJ2yr2dFoYAudKlIkh_k2hf0U23WV6XejfpPuicCDmNnepWkd1z0IrrwNVzBp0j_rySGHUadEv627Pki3YRkh-Xei5MOxoDDL2hvArZuTN_ZBn9uzfO6RN182FE8KlWFpxbSTRLsI6hJ5FalbsgkI7f0N18xyKUc1Xag554s

This is what the chunked playlist for one of the entries above looks like:

#EXTM3U
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-ALLOW-CACHE:NO
#EXT-X-VERSION:2
#EXT-X-TARGETDURATION:10
#EXTINF:10,
80299_04_03_MM30_exploreTown_mixed_1200.mp4Frag1Num0.ts
#EXTINF:10,
80299_04_03_MM30_exploreTown_mixed_1200.mp4Frag1Num1.ts
#EXTINF:10,
80299_04_03_MM30_exploreTown_mixed_1200.mp4Frag2Num2.ts
#EXTINF:10,
80299_04_03_MM30_exploreTown_mixed_1200.mp4Frag3Num3.ts

...

#EXTINF:7,
80299_04_03_MM30_exploreTown_mixed_1200.mp4Frag24Num24.ts
#EXT-X-ENDLIST

We verified that this happens also in the 2.X branch, and using the Demo app.

Our test device is a Nexus 6P with Android 7.1.2.

Sending a test URL for the chunk playlist to [dev.exoplayer@gmail.com.](url
[bugreport-N2G47O-2017-05-15-11-15-40.zip](https://github.com/google/ExoPlayer/files/1002047/bugreport-N2G47O-2017-05-15-11-15-40.zip)
)

**Comment by AquilesCanta** [comment]
This happens because most segments have their first keyframe at the end. So the decoder has to discard every sample until the one that allows decoding the posterior ones. This is counter-advised by the spec:

> The server SHOULD attempt to divide the source media at points that
   support effective decode of individual Media Segments, e.g. on packet
   and key frame boundaries.

Basically, the solution (the only one I can think of) is to remux the content so that the segment division helps individual segment decoding.

**Comment by brAzzi64** [comment]
If I understand correctly then, most of these 10-second chunks only have keyframes at the end?

Is dvbsnoop the right tool to analyze the chunks and spot this issue so I can report to our encoding team?

Thanks!

**Comment by AquilesCanta** [comment]
I don't know how to reflect this using dvbsnoop unfortunately. `mediainfo` might be the better way in this case. `ExoPlayer` is also a good choice and will be much easier/faster for you (if you need to learn how to use `mediainfo`). You should just add the proper debug logging.
