### ISSUE TITLE
No picture on some h264 streams (live TV captures)

### ISSUE THREAD

**Issue by goffioul** [google/ExoPlayer#2830]
### Issue description
Video is missing (audio only) on some h264 files.

I have a set a live TV captures that I'm using as a test bench for our video player app. These are captures from UDP multicast streams that are available at our customer's sites. When playing some of these captures in the ExoPlayer demo app, the video is missing (audio is ok). Because some of these streams use AC3 or MP2 for audio, I'm using the ffmpeg extension with the appropriate decoders (mainly ac3 amd mp3).

### Reproduction steps
All my streams are stored on a server and made available through plain HTTP (apache server). Playback is started with:

adb shell am start -d http://<hostname>/path/to/file.ts -a com.google.android.exoplayer.demo.action.VIEW

### Link to test content
Streams where video fails:
https://drive.google.com/open?id=0BwljeX6541LuWTBtdHNNTE1Ed2M
https://drive.google.com/open?id=0BwljeX6541LubUVmbGZad0QzcWM

Streams where video succeeds:
https://drive.google.com/open?id=0BwljeX6541Luck9BUDNnV1hIR3M

### Version of ExoPlayer being used
Compiled from git, branch release-v2 (currently 2.4.0).

### Device(s) and version(s) of Android being used
Tested on Android-IA, running on a Baytrail platform.

### A full bug report captured from the device
Will send the file by email.

**Comment by AquilesCanta** [comment]
They will work if you enable the `DefaultTsPayloadReaderFactory.FLAG_ALLOW_NON_IDR_KEYFRAMES` flag. On the release branch this is easy to do through the `DefaultExtractorsFactory#setTsExtractorFlags` method.

**Comment by goffioul** [comment]
Thanks, that fixed it.

Can you tell me what is the effect of using this flag on streams that would normally not need it? In case it's harmless, what would be the reason not to make it the default?

**Comment by AquilesCanta** [comment]
@andrewlewis is the correct person for answering that. But, basically, the flags makes the reader assume that I-frames are also IDR frames. It could be the case that the stream contains an I-frame which is succeeded by P or B frames that references frames before the I frame. This would mean that the decoder does not have the required information to decode said P or B frame. There is some useful information in the [MediaCodec docs](https://developer.android.com/reference/android/media/MediaCodec.html), look for "Stream Boundary and Key Frames". We are evaluating turning the flag on by default. We need to make sure it is safe to do. Hope this is helpful.

**Comment by andrewlewis** [comment]
Yes. To emphasize: if you set the flag then play a stream where a frame after a (non-IDR) I-frame refers to a frame before that I-frame, I think you could see error concealment artifacts appearing in the decoder output, as the decoder is not receiving a valid bitstream.

**Comment by goffioul** [comment]
That makes me wonder how other players solve this conundrum... Are you talking about artefacts that could appears only at playback startup (or after seek operation), or anytime during normal playback?

**Comment by andrewlewis** [comment]
The artifacts could appear on frames between the frame you seek to and the next IDR frame. I don't have any data on how common it is to have streams where I-frames can't be treated as IDR frames, but anecdotally it does seem to be rare.

**Comment by goffioul** [comment]
Thanks. I can live with transient artefacts after seek.

**Comment by goffioul** [comment]
@andrewlewis would you mind having a look at this stream:
https://drive.google.com/open?id=0BwljeX6541LuTy1GeHIwbTlsdGM

I'm seeing a lot of artefacts during playback. Is this the kind of possible problem you were referring to? Or are those due to the nature of the stream (the stream is not "clean", but that's a common scenario with live TV feeds).

**Comment by andrewlewis** [comment]
You could try playing it with a player like ffplay/mplayer/vlc/... in verbose logging mode to see if the video decoder outputs warning messages related to bitstream errors or error concealment. On cursory inspection, it certainly looks like the bitstream is incomplete or invalid.
