### ISSUE TITLE
wave file playback problem

### ISSUE THREAD

**Issue by Behrouz-m** [google/ExoPlayer#2835]
Hi. I'm using exo 2.4
I have problem with playing this wave file.

[https://www.dropbox.com/s/o7wyioop9b6rgsj/verbose.wav?dl=1](url)

please check it.

**Comment by AquilesCanta** [comment]
This issue is being closed because it does not adhere to our issue template, and/or because it omits information requested in the issue template that is required for us to investigate the problem efficiently. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).
 
If you’re able to provide complete information as requested in the issue template, please do so below and we’ll re-open the issue. Thanks!

Worth mentioning: The file plays well in the demo app.

**Comment by Behrouz-m** [comment]
I'm receiving this error:
```
W/WavHeaderReader: Ignoring unknown WAV chunk: 1380533830
W/WavHeaderReader: Ignoring unknown WAV chunk: 1718449184
```

what does it mean ?
I'm playing the file through http.

**Comment by Behrouz-m** [comment]
I'm using this code:
```java
        RenderersFactory rf = new RenderersFactory()
        {
            @Override
            public Renderer[] createRenderers(Handler eventHandler, VideoRendererEventListener videoRendererEventListener, AudioRendererEventListener audioRendererEventListener, TextRenderer.Output textRendererOutput, MetadataRenderer.Output metadataRendererOutput)
            {
                return new Renderer[]{new LibopusAudioRenderer(eventHandler, audioRendererEventListener)};
            }
        };
        player = ExoPlayerFactory.newSimpleInstance(rf, trackSelector, new MyExoLoadControl());
```
the problem is that wave decoder is not set. How can I set it?

**Comment by ojw28** [comment]
Why are you overriding the renderers to provide only an Opus renderer? If you're providing only an Opus renderer then you're not going to able to play WAV content.

Please also properly fill out the issue template, as has already been requested above, else we do not have sufficient information to help.

**Comment by Behrouz-m** [comment]
the reason is I don't know how to add Opus renderer  and I could not find any sample for the issue. please refer any proper code to fix this issue. thanks

**Comment by ojw28** [comment]
If you override the factory to provide only an Opus renderer, the player is only going to be able to play Opus.

It's not feasible for us to provide sample code for every possible customization. In general, if you want to replace a default component with a custom one, you should first take a look at the default implementation to see exactly what it does. If you look at `DefaultRenderersFactory` you'll see that it includes the Opus renderer automatically if `extensionRendererMode` is set to `EXTENSION_RENDERER_MODE_ON`. So for your use case you can just use the default factory and set that parameter through its constructor.
