### ISSUE TITLE
Rounded Corners

### ISSUE THREAD

**Issue by connorliveraise** [google/ExoPlayer#2837]
Is it possible to display the ExoPlayer with rounded corders (or cropped to a circle)?

I attempted using a background shape, or putting the SimpleExoPlayerView inside a [RoundedCornerLayout](http://stackoverflow.com/questions/26074784/how-to-make-a-view-in-android-with-rounded-corners/26201117), but the ExoPlayer's surface escapes the constraints of the parent, and so the background of the rounded corners are black instead of transparent.

I see that someone came up with a GL solution using the classic MediaPlayer. Is this functionality supported with ExoPlayer?

Thanks

**Comment by ojw28** [comment]
A GL issue sounds like overkill. It should be perfectly possible to render UI components over the top of the surface; playback controls being the most obvious example. So an approach that should work would be to add a view on top of the surface that's transparent in the middle and black around the edges, in whatever pattern you're trying to achieve.

**Comment by connorliveraise** [comment]
Thanks @ojw28, however placing a view on top will not work as the main view is another ExoPlayer (we are doing picture-in-picture combining 2 videos).

Any other suggestions or ideas?

**Comment by ojw28** [comment]
I don't think you can do what you're attempting using `SurfaceView`. Have you tried configuring `SimpleExoPlayerView` to use a `TextureView` instead? You should be able to set `app:surface_type="texture_view"` in your layout xml to do this. Then try your original approach with `RoundedCornerLayout` again.

**Comment by connorliveraise** [comment]
Thanks @ojw28 that worked!
