### ISSUE TITLE
can not play my .m3u8

### ISSUE THREAD

**Issue by 13217300237** [google/ExoPlayer#2838]
### Issue description
exo demo can not play my hls live channel.but I can play it in VLC on my cumputer.

### Reproduction steps
add a source:"http://198.255.10.2:88/AirSD/191/191.m3u8" into hls list of media.exolist.json file,
and run the demo with android studio

### Version of ExoPlayer being used
2.3.1

### Device(s) and version(s) of Android being used
android pad Nexus 9

### A full bug report captured from the device
https://github.com/18598925736/hankstest/blob/master/1755.log

**Comment by AquilesCanta** [comment]
I can't look into this in detail right now, but from the logcat (please follow the issue template to get a full bug report next time), I can see a date parsing error. You could try making the parser ignore that error and see if it plays after that to make sure that's the issue. If the content is actually malformed, you might consider fixing it. I'll come back to this issue as soon as I have free time.

**Comment by ojw28** [comment]
Agree the media is malformed. 2017-05-17T03:00:52.296-6:00 isn't a valid datetime. It should be 2017-05-17T03:00:52.296-**0**6:00. That said, we could trivially handle the case by making one of the digits before the colon optional?

**Comment by ojw28** [comment]
We've made our date parsing more lenient in https://github.com/google/ExoPlayer/commit/f16967cdfeda442128edc754cba0c40949a2d429, so this stream now plays successfully. To reiterate, however, the media is not spec compliant.
