### ISSUE TITLE
Video is not playing after reaching the end and seeking to the start on Galaxy S4

### ISSUE THREAD

**Issue by emakovsky** [google/ExoPlayer#284]
Steps:
1) Open Demo app (Tried both master and dev branches) and play Misc - Dizzy video
2) play video till the end. playbackState=ended
3) seek to any position before the end. Playback state is always buffering. Video is not playing. But very seldom it actually plays.

Applicable for S4. 
On nexus 4 everything works as expected.

**Comment by emakovsky** [comment]
Some details about the reason of the issue:
FrameworkSampleSource.getBufferedPositionUs() method returns extractor.getSampleTime() + 0;
as a result playback state is always buffering.

So main problem: is that ok if extractor.getCachedDuration() returns 0 on galaxy S4?

And will it be a good workaround for this issue:
long bufferedDurationUs = extractor.getCachedDuration();
 if (bufferedDurationUs == -1 || bufferedDurationUs == 0) {
      return TrackRenderer.UNKNOWN_TIME_US;
    }

**Comment by ojw28** [comment]
7f58a0be8192c375565d7c77950200ee0a38c011
