### ISSUE TITLE
Flush timing issues for passthrough playback using Offload profile

### ISSUE THREAD

**Issue by ghost** [google/ExoPlayer#2840]
### Issue description
Flush called inconsistently on audio HALs supporting AUDIO_OUTPUT_FLAG_COMPRESS_OFFLOAD.
During seek operations, it is expected that creation of a new AudioTrack will trigger a flush on the audio HAL to remove any buffered data that is no longer relevant. It has been observed that flush is not always called.

### Reproduction steps
* Note: Requires logging of flush() in an audio HAL and an audio policy configuration that supports a profile with audio offload.
* Load ExoPlayerDemo (no modifications) to DUT.
* Play track supported by Offload profile on device.
* Trigger seek in ExoPlayer. Repeat numerous times.
* Observe flush not always called in audio HAL upon seek.

### Link to test content
N/A, any test content supported by offload profile is sufficient to verify.

### Version of ExoPlayer being used
release-v2, 2.4.0

### Device(s) and version(s) of Android being used
Nexus Player (fugu), Android 7.1.1_r23

### A full bug report captured from the device
The bug report doesn't offer any insights (no crashes) without verbose/new logs.

In ExoPlayer's AudioTrack.java, the following code is executed on seek.
// AudioTrack.release can take some time, so we call it on a background thread.
      final android.media.AudioTrack toRelease = audioTrack;
      audioTrack = null;
      audioTrackUtil.reconfigure(null, false);
      releasingConditionVariable.close();
      new Thread() {
        @Override
        public void run() {
          try {
            toRelease.flush();
            toRelease.release();
          } finally {
            releasingConditionVariable.open();
          }
        }
      }.start();

In Threads.cpp, AudioFlinger::PlaybackThread::addTrack_l(), after the track is created it is assigned as the latest track (mLatestActiveTrack = track;)
 
In AudioFlinger::OffloadThread::prepareTracks_l(), after detecting a flush is pending, it will only be applied for the latest created track:
 
if (last) {
      mFlushPending = true;
}
 
If the new track is created (and addTrack_l() completes) before the line above is reached for the dying track, flush will not be called on the dying track.
It is unclear whether this is a bug in ExoPlayer (should ExoPlayer wait for AudioTrack release before creating a new one?) or in AudioFlinger.

**Comment by andrewlewis** [comment]
> It is unclear whether this is a bug in ExoPlayer (should ExoPlayer wait for AudioTrack release before creating a new one?) or in AudioFlinger.

ExoPlayer does wait for `release` to return in [`initialize`](https://github.com/google/ExoPlayer/blob/e87e231/library/core/src/main/java/com/google/android/exoplayer2/audio/AudioTrack.java#L635), though I'm not certain whether you're referring to the Java AudioTrack API or something lower level.

I think it's likely this is a platform issue. Do you have a bug filed on the AOSP issue tracker? If so I can follow up internally. Thanks.

**Comment by ghost** [comment]
Thanks Andrew, I've added the bug to AOSP's issue tracking:
https://issuetracker.google.com/issues/62109057

in AudioTrack.reset (The ExoPlayer Java implementation), there is the following comment/code which made me question whether a new AudioTrack (both Java and native) was created before the previous one was properly released:

// AudioTrack.release can take some time, so we call it on a background thread.
.....
new Thread() {
    @Override
    public void run() {
      try {
        toRelease.flush();
        toRelease.release();
      } finally {
        releasingConditionVariable.open();
      }
    }
 }.start();

**Comment by ojw28** [comment]
We release the platform AudioTrack on a background thread, but `releasingConditionVariable` ensures that a subsequent initialization of a platform AudioTrack will be blocked until that background thread has actually finished releasing the previous one.

Closing this issue, since this appears to be a platform problem and there's an AOSP issue tracking it, as ref'd above.
