### ISSUE TITLE
Cannot playback TS files by fail to identify key frame within it

### ISSUE THREAD

**Issue by WeiChungChang** [google/ExoPlayer#2841]
### Issue description
Cannot Playback TS files.
There is only audio & **_all video frames are dropped._**
**_It is because the frames are all deemed as "non-key"._**
However, if played on, ex: VLC player, the movie is fine.

The file's key frames could be identified by **_recovery point SEI message_**
 
_**"...a special header, called the SEI Recovery Point, tells the decoder to "start here, decode X frames, and then start displaying the video."**_ 

https://software.intel.com/en-us/forums/intel-media-sdk/topic/311715 
http://www.videoredo.net/msgBoard/showthread.php?34794-How-to-cut-H264-without-IDR-frame

**_It may need the flow to create the flow of parsing SEI message, check recovery point & identify the key frame by it.  _**   A proposal of solution is as #2842

### Reproduction steps
Put the issued files of Link to test content & playback it.

### Link to test content
https://drive.google.com/drive/folders/0B7H5vJR3qWj0djkzS2ZHeWR6ZTA

### Version of ExoPlayer being used
2.3.1

### Device(s) and version(s) of Android being used

100%, HTC x9 smartphone with Android 6.0

### A full bug report captured from the device
Playback issue & root cause is described as indicated;
Not a system issue so skip here.

**Comment by AquilesCanta** [comment]
Hi, please try the latest release. We've implemented key frame recognition using the random access indicator. Hopefully this works for you. Please post below (including a non-working stream) if you still run into issues.
