### ISSUE TITLE
Inconsistent Closed captioning

### ISSUE THREAD

**Issue by dhir-pratap** [google/ExoPlayer#285]
I am  trying to display closed caption from following link but I am unable to display it.
http://cdnbakmi.kaltura.com/p/243342/sp/24334200/playManifest/entryId/0_uka1msg4/flavorIds/1_vqhfu6uy,1_80sohj7p/format/applehttp/protocol/http/a.m3u8

Can you tell what are the CC format supported by Exo player? I believe the link has CC in WEBVTT format. I saw a related ticket <a  href="https://github.com/google/ExoPlayer/issues/68">here. Implement Closed Captioning support for HLS #68 </a>. It says The issue is closed but CC does not work for the said link and other live stream URLs.

**Comment by ojw28** [comment]
We currently support EIA-608. Support for WebVTT is tracked here:
https://github.com/google/ExoPlayer/issues/151

**Comment by dhir-pratap** [comment]
Do you sopport EIA-708 too? And is EIA-608/708 supported for live streams?

**Comment by ojw28** [comment]
We currently support EIA-608 only, for live and on-demand. WebVTT support should arrive relatively soon, although I can't provide a solid ETA.
