### ISSUE TITLE
It is very difficuit to detect correct stream type with exoplayer

### ISSUE THREAD

**Issue by mdtuyen** [google/ExoPlayer#2850]
Hi,
I'm working with my application to play video.
I see that exoplayer detect content type by `Util.inferContentType(String fileName) `function.
I'm working with http link with type m3u4 and mp4
but:
Some link m3p4, mp4 is not suffix.

I have not pattern for them so that I can't use abover function to detect content Type.

Some mp4 link can't play (Example: https://openload.co/embed/H334bKtpbhs/lei-tot-19052017-1v.mp4)
`
com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor) could read the stream.`

**Comment by andrewlewis** [comment]
The server returns an HTML page when I request that using `wget`. You need to give the player the URI of the actual video not an HTML page embedding it.

Do you need to support DASH/HLS/SS? If not, you can probably just use ExtractorMediaSource directly and don't need to call `inferContentType`.

**Comment by mdtuyen** [comment]
@andrewlewis 
Thanks for your answer,
You correct the mp4 link that I got only a webpage link.
If I have a link how do I detect content type of that link, I see that some link can't detect content type with suffix link (inferContentType not work).

**Comment by AquilesCanta** [comment]
`inferContentType` only tries to detect DASH vs HLS vs Smoothstreaming vs Other. It is not intended to detect the container format (mp4 vs mp3 vs ogg, etc). You could write your own method for this. Container detection by suffix is not something that ExoPlayer does at the moment. If you are going to use `ExtractorMediaSource` with all the default extractors (the included log suggests that), you could let the sniffing mechanism do the work for you, which should be the ground truth. Also, as @andrewlewis says
>Do you need to support DASH/HLS/SS? If not, you can probably just use ExtractorMediaSource directly and don't need to call inferContentType.
