### ISSUE TITLE
Clarify instructions for building FLAC extension (and other extensions)

### ISSUE THREAD

**Issue by Merseyside** [google/ExoPlayer#2851]
Hello! I have tried to add FLAC extensions. All steps are complete, but when I added EXoplayer folder to my project and write in my settings.gradle this:
include ':ExoPlayer:library'
include ':ExoPlayer:extension-flac'

and in build.gradle this:
compile project(':ExoPlayer:library')
compile project(':ExoPlayer:extension-flac')

I got this error:
Caused by: org.gradle.internal.component.model.ConfigurationNotFoundException: Project :app declares a dependency from configuration 'compile' to configuration 'default' which is not declared in the descriptor for project :ExoPlayer:library.

What I do wrong?

**Comment by ojw28** [comment]
I can't follow those instructions either.

@vigneshvg - It looks like they were originally added by you in the readme for VP9, before being copied elsewhere. Could you clarify how they're supposed to work? In particular, the checked out ExoPlayer is probably in a different directory to the user's own application project. It doesn't appear these instructions include enough information for the ExoPlayer directory to be found (and I suspect that what's happening is that it isn't found).

**Comment by PaulWoitaschek** [comment]
I managed to compile flac here using gradle without needing to pull the whole exo player folder in my sources.

https://github.com/PaulWoitaschek/MaterialAudiobookPlayer/blob/master/exoplayer-flac/build.gradle#L17

The task that prepares the dependency is here:

https://github.com/PaulWoitaschek/MaterialAudiobookPlayer/blob/master/buildSrc/src/main/java/de/ph1b/audiobook/ndkGen/PrepareFlac.kt#L15

But building that stuff was really really painful. I also got it working for opus, but it fails with very cryptic errors often times.

It would be so great if you could just ship these through maven.

**Comment by ojw28** [comment]
Ping @vigneshvg - Could you explain the instructions? If they don't work, we should remove/update them.

**Comment by satyres** [comment]
Thank you for the reply ! this does not answer my question , can i use the compiled version of the demo ?
Why i have to build it my self  , i don't understand ! the help guide is not helpful as well !
Sorry ! 
regards

**Comment by ojw28** [comment]
We do not provide pre-compiled versions of the demo app. Providing these is tracked by https://github.com/google/ExoPlayer/issues/1920, but for non-technical reasons this is currently non-trivial for us to do.

**Comment by Aditya94A** [comment]
Is there a list somewhere of unsupported or semi-supported formats/edge cases for ExoPlayer? I'd rather not run into these things in production.

@PaulWoitaschek Pardon me, I'm not familiar with using NDK, but I wonder if it's possible your exoplayer-flac and exoplayer-opus extensions could be made available as a library? That was be tremendously convenient and helpful :)

**Comment by PaulWoitaschek** [comment]
It's not my extensions, it's just the exoplayer extensions drawn together so they build with all these manual steps involved. 

Rather that me building it I would rather push for the exoplayer people just release it to maven. 
There is an issue for that but it has both status unclear. Maybe that can be escalated? 

It took me quite some time to get it to build and I think there would be a lot of hours saved if not everyone has to handle the complicated build process itself.

**Comment by Aditya94A** [comment]
@PaulWoitaschek Yes, of course! I was just wondering whether it's at all possible to have those as a separate dependency. I was indeed wrestling with this for hours before giving up. 

I wonder why it isn't simply built in to ExoPlayer, the extensions aren't very big in size. Anyways, if they are a common enough use case to have their build process explained officially surely we can offer a better way for developers to use them. @ojw28 please share your thoughts :)

**Comment by ojw28** [comment]
Distributing extensions via jCenter is tracked by https://github.com/google/ExoPlayer/issues/1434. Let's just use this issue to track making sure the manual instructions make sense.

**Comment by PaulWoitaschek** [comment]
Well I just modified my build.gradle to let the Android plugin handle the build. 

Then it's really straight forward as you only need to put the flac sources in the jni folder. 

For opus it's more complicated as I needed to modify the build files to get it working.

**Comment by ojw28** [comment]
Instructions have been clarified on the dev-v2 branch.
