### ISSUE TITLE
Returning from Picture in Picture mode (PIP) for Android TV shifts video playback

### ISSUE THREAD

**Issue by drhill** [google/ExoPlayer#2856]
### Issue description
Picture in Picture has issues on return from PIP to full screen.  Video playback is shifted (to the right) in the surfaceview.

### Reproduction steps
Use https://github.com/google/ExoPlayer/tree/dev-v2/demo
Add a button to the PlayerActivity that will call enterPictureInPictureMode()
Make sure the manifest includes:
    `<activity android:name=".ui.activity.PlayerActivity"
                  android:resizeableActivity="true"
                  android:supportsPictureInPicture="true"
                  android:launchMode="singleTask"
                  android:configChanges="screenSize|smallestScreenSize|screenLayout|orientation"/>`

### Link to test content
Use any mkv file (I used a 720p file with h264 video @23.976 and ac3 audio

### Version of ExoPlayer being used
dev-v2 branch

### Device(s) and version(s) of Android being used
AndroidTV emulator API 24.  Nvidia Shield (with previous version of exoplayer)

### A full bug report captured from the device
[pip_br.zip](https://github.com/google/ExoPlayer/files/1020616/pip_br.zip)

**Comment by ojw28** [comment]
@sureshcnvidia - Any idea about this one? I'm guessing it's not Shield specific, however, as it's also reported as occurring on the emulator.

**Comment by drhill** [comment]
It reproduces every time for me except when I added an override to onConfigurationChanged and set a breakpoint to see what the configurations being passed in were.  Just adding a log statement didn't help but manually looking at it while debugging seemed to.  Timing issue?

**Comment by andrewlewis** [comment]
[Possibly related to internal bug ref: 62512584]

**Comment by andrewlewis** [comment]
@drhill Is this still reproducible with the latest system update for the NVIDIA Shield?

**Comment by drhill** [comment]
Just tested with my app on Shield SW 6.2.  It returns to normal from PIP, but when you send it to PIP mode it initially shrinks the video playback to top left corner of the shrunken window and then if you hit the home key (or double press it to open up PIP options) the playback shifts to mostly below the bottom of the window.  You can see around the top black frame of a 2.35 video in the lower left corner while it continues playback.

**Comment by ojw28** [comment]
@sureshcnvidia - Any idea about this? Thanks!

**Comment by drhill** [comment]
This works fine now on the lastest Shield update.
