### ISSUE TITLE
show black screen before video played after activity resumed.

### ISSUE THREAD

**Issue by sschemer** [google/ExoPlayer#2857]
### Issue description
if resumed activity when playing video, the video will show black screen before continuing playing.

### Reproduction steps
as I test, it occurs in my app and offical demo app, i just test hls and mp4.and I init and release exoplayer
as the offical demo doing.

### Version of ExoPlayer being used
r2.4.0

### Device(s) and version(s) of Android being used
I test in oneplus3, android 7.1.1; xiaomi max, android 6.0; xiaomi 4, android 7.1.1

**Comment by ojw28** [comment]
This is expected because the underlying platform destroys the surface, and because we cannot draw into the new surface until after we've re-buffered and decoded the first frame at the current playback position. Sorry.
