### ISSUE TITLE
How to translate ExoPlaybackException errors ?

### ISSUE THREAD

**Issue by satyres** [google/ExoPlayer#2858]
Hi , is there a way to get the hole list of errors indexed by numbers in order to translate them to a different language ?

**Comment by ojw28** [comment]
Documenting common errors is discussed and tracked in https://github.com/google/ExoPlayer/issues/1611.

**Comment by satyres** [comment]
the #1611 is 1 year old and there is nothing important on it !
and https://github.com/google/ExoPlayer/blob/master/library/src/main/java/com/google/android/exoplayer/ExoPlaybackException.java#L21 is not  working

**Comment by ojw28** [comment]
I've updated the link (it's pretty trivial to find the Javadoc for ExoPlaybackException using Google, or just looking at the source code...). The fact it's one year old just indicates it's not very high priority for us. Posting the same thing again isn't going to speed anything up. Thanks.

**Comment by satyres** [comment]
Thank you so much for your help!
