### ISSUE TITLE
Failed to play .mp4 with a audio track of sampleRate 96000Hz

### ISSUE THREAD

**Issue by SnakeMM** [google/ExoPlayer#2861]
### Issue description
Failed to play mp4 video with 96000Hz sample rate audio track.
By Default, the whole video failed to play.
When I select Audio track "Disabled", the video track can play.
I'll post the whole log in email, but I think the problem is

> MediaCodecInfo: NoSupport [sampleRate.support, 96000] [OMX.google.aac.decoder, audio/mp4a-latm] [cancro, MI 3W, Xiaomi, 23]

I can play this video (with audio) using my SmartPhone MI 3W's default media player, default web browser.

### Reproduction steps
Play the video url I posted in email using ExoPlayer Demo App.

### Link to test content
see email.

### Version of ExoPlayer being used
r2.3.1

### Device(s) and version(s) of Android being used
MI 3W
Samsung S7
HTC_M10h
etc..

### A full bug report captured from the device
see email.

**Comment by ojw28** [comment]
Does the sample play correctly with the built in players on other devices (e.g. the Samsung S7)?

**Comment by SnakeMM** [comment]
Yes, it plays correctly with Samsung S7 built in player @ojw28

**Comment by andrewlewis** [comment]
Testing on a Nexus 6P, I see the same issue on Android Marshmallow but not on Nougat, so I suspect support for 96 kHz AAC was added to OMX.google.aac.decoder in Android Nougat. Closing as there's not much we can do to support this. One workaround is to bundle your own software audio codec to use on older builds (e.g., using the [ffmpeg extension](https://github.com/google/ExoPlayer/tree/dev-v2/extensions/ffmpeg)).
