### ISSUE TITLE
Probleme with TS 

### ISSUE THREAD

**Issue by youneslalami** [google/ExoPlayer#2864]
I creat a channel with ngnix playing a video on loop its work fin in vlc and other player but with exoplayer just play ipt lik vod not on loop

**Comment by AquilesCanta** [comment]
This issue is being closed because it does not adhere to our issue template, and/or because it omits information requested in the issue template that is required for us to investigate the problem efficiently. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).
 
If you’re able to provide complete information as requested in the issue template, please do so below and we’ll re-open the issue. Thanks!

**Comment by youneslalami** [comment]
Uri mp4VideoUri;
      String url =" http://ipbox.ddns.me:8080/live/younesalami/2625487136/2319.ts";
        BandwidthMeter bandwidthMeter = new DefaultBandwidthMeter();

        TrackSelection.Factory videoTrackSelectionFactory = new AdaptiveTrackSelection.Factory(bandwidthMeter);

        trackSelector = new DefaultTrackSelector(videoTrackSelectionFactory);

        player = ExoPlayerFactory.newSimpleInstance(this, trackSelector, new DefaultLoadControl());
        playback.setPlayer(player);
        userAgent = "Movie_show_player";
         mp4VideoUri = Uri.parse(url);

        DefaultBandwidthMeter bandwidthMeterA = new DefaultBandwidthMeter();
        DefaultDataSourceFactory dataSourceFactory = new DefaultDataSourceFactory(this, Util.getUserAgent(this, userAgent), bandwidthMeterA);
        ExtractorsFactory extractorsFactory = new DefaultExtractorsFactory();
        //

        if(url.contains(".m3u8")){

            videoSource1 = new HlsMediaSource(mp4VideoUri, dataSourceFactory, mainHandler, null);
        }else{

            videoSource1 = new ExtractorMediaSource(mp4VideoUri, dataSourceFactory, extractorsFactory, mainHandler, null);
    loopingSource = new LoopingMediaSource(videoSource1);
        player.stop();
        player.setPlayWhenReady(false);
        player.prepare(loopingSource);
        player.setPlayWhenReady(true);
    }

**Comment by AquilesCanta** [comment]
The URI included in the code snippet plays well on the demo app. This suggests there is an issue with your code.

We might be able to help you if you fill the issue template as requested above.

**Comment by youneslalami** [comment]
url work yes but not on loop

**Comment by AquilesCanta** [comment]
It is live content, I am not sure how looping should work.

**Comment by youneslalami** [comment]
for example when i have a live duration 2min it should restart for each 2min restart the stream each 2min

**Comment by youneslalami** [comment]
you can try it  let the stream finish and it will stop and from my server it run on loop
