### ISSUE TITLE
Pausing the video skips frames when the activity/fragment hosting is resumed. 

### ISSUE THREAD

**Issue by mrudulav3** [google/ExoPlayer#2865]
[bugreport-N2G47E-2017-05-25-11-21-47.zip](https://github.com/google/ExoPlayer/files/1029445/bugreport-N2G47E-2017-05-25-11-21-47.zip)
### Issue description
Expected Behavior - When the video is paused and the activity/fragment hosting it is resumed the video should not jump frames.
Observed Behavior - When the video is paused and the activity/fragment hosting it is resumed the video should jumps frames. The position of the playback doesn't change. When the video is toggled to play, it resumes but the frame is stuck till the playback reaches that position. 

### Reproduction steps
Open the Exoplayer Demo app. Using the 2.4.1-rc version. Play a video (DASH or HLS). Pause it and 
Overview button and press on it again to bring the activity to resume. Notice that the video frame skips

### Version of ExoPlayer being used
2.4.1-rc demo app

### Device(s) and version(s) of Android being used
Happens on Nexus 5x running 7.1.2 and Pixel running 7.1.2

### A full bug report captured from the device
Captured a video 
[screen_video_grab.zip](https://github.com/google/ExoPlayer/files/1029412/screen_video_grab.zip)

**Comment by ojw28** [comment]
This is discussed/tracked in https://github.com/google/ExoPlayer/issues/677
