### ISSUE TITLE
Exo Player Wake Lock

### ISSUE THREAD

**Issue by nkmedaa** [google/ExoPlayer#2866]
1. Exo Player containing Activities does not allow the device to lock after idle time even through  Exo player is paused. Any info  will be appreciated, Thank you

**Comment by andrewlewis** [comment]
If I remove the `keepScreenOn` attribute from the demo application's [player layout](https://github.com/google/ExoPlayer/blob/195a93e/demo/src/main/res/layout/player_activity.xml#L21), I find that the screen can turn off while the player is paused. See also #930.

`adb shell dumpsys power` shows what WakeLocks are held. A bug report includes the same dumpsys output.

**Comment by nkmedaa** [comment]
Hi andrewlewis ,
                           i did not used the keepScreenOn attribute. but still lit is not locking.

**Comment by andrewlewis** [comment]
You're probably either playing audio continuously or your app is holding a WakeLock, which we can't really help with. I suggest looking at the output of `adb shell dumpsys power` to debug this yourself.

**Comment by nkmedaa** [comment]
No i need my  device to be locked after device lock time when exo player is paused. Fore remaining screens it is working fine but screens which contains exo player for those only it is not working.
