### ISSUE TITLE
Consider normalizing all language codes to use a single standard

### ISSUE THREAD

**Issue by PiotrWozniakSC** [google/ExoPlayer#2867]
Version of ExoPlayer used: 2.3.1 (with plans to use latest)

ExoPlayer uses three-letter codes in Format.language for audio and subtitle tracks. Question is - what standard is used for these codes? Is it 639‑2/T, 639‑2/B, 639‑3 (https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes#Partial_ISO_639_table) or some other standard?

The Format.language field description states only "The language, or null if unknown or not applicable." (in v1 it was stated explicitly: "The language codes are two-letter lowercase ISO language codes (such as "en") as defined by ISO 639-1.") and I couldn't find the answer regarding v2 anywhere. I'd be grateful for the clarification.

**Comment by ojw28** [comment]
Pretty sure we just mirror whatever's in the source media. Assuming the source media uses some vaguely sane standard, then you should be able to normalize it into RFC 5646 using `Util.normalizeLanguageCode`.

**Comment by ojw28** [comment]
Hm, actually, I'm not about the second part of my answer.

**Comment by ojw28** [comment]
Fixed in `dev-v2`.
