### ISSUE TITLE
Can I override simpleExoPlayerView buttons' actions?

### ISSUE THREAD

**Issue by LutfiTekin** [google/ExoPlayer#2868]
Hello guys, is it possible to override play, pause, prev, next buttons in **simpleexoplayerview** 
I created a custom layout for  **simpleexoplayerview** and changed some of the buttons' appereances.

   ```
     <ImageButton android:id="@id/exo_next"
            android:background="?selectableItemBackground"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            app:srcCompat="@drawable/ic_file_download_black_24dp"/> 
```

I just want to change prev and next button.
I'm developing a simple podcast app and I want to change prev buttons as favorite and next button as download.

using exoplayer version 2.4.0

**Comment by ojw28** [comment]
If you want to make player controls that are substantially different to the default ones, then you should implement your own. Wiring a "next" button up to do something completely different than "next" doesn't sound like a great idea.
