### ISSUE TITLE
How to implement my own method to find the ideal Format for a  DASH Chunk in Exoplayer 2

### ISSUE THREAD

**Issue by qlthd** [google/ExoPlayer#2869]
Hi everyone, I'm new to developping Exoplayer.
Here is how my player is implemented: 
```
protected void onCreate (Bundle savedInstanceState){
        super.onCreate(savedInstanceState);
        mainHandler= new Handler();
        setContentView(R.layout.activity_main);
        View rootView = findViewById(R.id.root);
        rootView.setOnClickListener(this);
        playerView = (SimpleExoPlayerView) findViewById(R.id.player_view);
        playerView.setControllerVisibilityListener(this);
        playerView.requestFocus();
        initializePlayer();
    }


    private void initializePlayer(){

            Uri uri = Uri.parse("http://yt-dash-mse-test.commondatastorage.googleapis.com/media/motion-20120802-manifest.mpd");

            TrackSelection.Factory videoTrackSelectionFactory = new AdaptiveTrackSelection.Factory(BANDWIDTH_METER);

            trackSelector = new DefaultTrackSelector(videoTrackSelectionFactory);

            DefaultLoadControl loadControl = new DefaultLoadControl();

            player = ExoPlayerFactory.newSimpleInstance(this, trackSelector,loadControl);

            playerView.setPlayer(player);

            DataSource.Factory dataSourceFactory = buildDataSourceFactory2(BANDWIDTH_METER);

            DashMediaSource videoSource = new DashMediaSource(uri, buildDataSourceFactory2(null),new DefaultDashChunkSource.Factory(dataSourceFactory), mainHandler, null);

            LoopingMediaSource loopingSource = new LoopingMediaSource(videoSource);

            TextView debugView = (TextView) findViewById(R.id.debug_text_view);

            debugView.setTextColor(Color.WHITE);

            if (resumeWindow != C.INDEX_UNSET)
                player.seekTo(resumeWindow, resumePosition);

            player.prepare(loopingSource, resumeWindow == C.INDEX_UNSET, false );

    }
```
I'm working with DASH Media and try to make my own adaptation algorithm 
For each chunk (TrackGroup), I’d like to find the ideal format(Format in exoplayer, the ideal format like 1080p (Format.bitrate) or 720p or less given the connexion quality) thanks to the following method, but I don’t know where to put this method and how to call it for each chunk during a transfer to determine the ideal format thanks to quality connexion. I've been thinking of extracting informations from my MPD file and to get TrackGroups manually but it seems a bit complicated.

```
public Format algorithm(TrackGroup chunk, int i) {  
	//calculate the bandwidth estimate 
       return idealQuality; // a format which delivery bitrate should be under the bandwidth estimate
   
}
```
I can give you more details if necessary.
Thank you.

**Comment by ojw28** [comment]
You need to implement your own `TrackSelection.Factory` to use instead of `AdaptiveTrackSelection.Factory` which is what you're currently using. Use `AdaptiveTrackSelection` as a starting point. If you look at its implementation, one of its methods is `updateSelectedTrack`. It's this method that selects the track for the next chunk load.

**Comment by sandeshlasnapure** [comment]
Can you share implementation sample, how to use AdaptiveTrackSelection?

**Comment by zhanghuicuc** [comment]
Here is my implementation : https://github.com/zhanghuicuc/SimplePlayer/blob/dev-exo/library/src/main/java/com/google/android/exoplayer2/trackselection/QAdaptTrackSelection.java
Hope this helps.
