### ISSUE TITLE
Exoplayer guide on Looping is incomplete.

### ISSUE THREAD

**Issue by Edijae** [google/ExoPlayer#2875]
Kindly have a look at this issue posted on stalkoverflow and update your developer's guide if necessary.
[Exoplayer not looping the video](https://stackoverflow.com/q/44217063/3671509)

**Comment by ojw28** [comment]
It should hopefully be obvious to most readers that you're supposed to pass the looping source to get looping. I think the guide is sufficiently clear. If we were to spell everything out explicitly then the guide would be unnecessarily long and verbose for the majority of readers.
