### ISSUE TITLE
IllegalArgumentException by seek to negative position.

### ISSUE THREAD

**Issue by PaulWoitaschek** [google/ExoPlayer#2876]
When playing certain files and seeking to a negative position, the player logs the following exception and transitions to the error state.

https://gist.github.com/PaulWoitaschek/06682f82a962ae63aa639302b6bf98c8

With other files it is possible to seek to a negative position and upon play, exoplayer will start at 0.
I found this because I had a bug in my application that caused a seek to a negative position.

I think either the player should ignore negative positions and go to 0 or throw an exception that only positions >= 0 are allowed.

Tested with Android 6 Moto G4 Play, Nexus 5X Android 7.1.2 and Android Emulator 7.1.2, all running ExoPlayer 2.4.1.
A sample file is on it's way by mail.

**Comment by PaulWoitaschek** [comment]
Also after permitting negative values as position in my model class I found out that sometimes ExoPlayer returns slightly negative positions like `-67` in `getCurrentPosition()`. So I manually set all of them to 0 now.

**Comment by PaulWoitaschek** [comment]
in

**Comment by PaulWoitaschek** [comment]
My comment is kind of a second issue. Should I open a separate ticket for that?

**Comment by ojw28** [comment]
If you can provide clear reproduction steps (when making use of the fix above) then yes please file a separate issue.
