### ISSUE TITLE
Flac is not working in exoplayer:r2.4.1 ?

### ISSUE THREAD

**Issue by satyres** [google/ExoPlayer#2877]
Hi , 
Flac extension is not included in the last release of exoplayer ?
when i use the default demo Flac is working !
but when i use the gradle with **compile 'com.google.android.exoplayer:exoplayer:r2.4.1'**  is not working why ?
how to include it ? thanks

**Comment by PaulWoitaschek** [comment]
Because that's part of an extension you have to build manually if you want to use it:

https://github.com/google/ExoPlayer/tree/release-v2/extensions/flac

**Comment by satyres** [comment]
Thank you for the reply  , is it possible to use the already build in the Demo example ?
i've added new module like the demo and copied almost everything , it's working on the demo and not on the new module added ? how is that possible ?

**Comment by ojw28** [comment]
Let's use https://github.com/google/ExoPlayer/issues/2851 to track this.
