### ISSUE TITLE
How to implement Closed Captioning support for HLS?

### ISSUE THREAD

**Issue by sachinbhanot** [google/ExoPlayer#288]
Hi,

I have to integrated the closed captioning support for our videos? what are the different ways to integrate that.?  I don't have idea right now,

I have a .srt file . how to use with exoplayer ?

**Comment by ojw28** [comment]
We currently support EIA-608 captions for HLS. We'll be adding support for WebVTT captions soon.

**Comment by Ood-Tsen** [comment]
Actually, 
HLS does not support webvtt yet.
Shall we open another issue for tracking ?

**Comment by ojw28** [comment]
#151

**Comment by sachinbhanot** [comment]
Is there any support come for closed caption using srt file?
