### ISSUE TITLE
Replacing chunks in the buffer

### ISSUE THREAD

**Issue by wasp898** [google/ExoPlayer#2880]
We are trying to implement a strategy for replacing chunks in the buffer without discarding every segment (as the function maybeDiscardUpstream does). We are basically trying to do what explained in this [issue](https://github.com/google/ExoPlayer/issues/2721).

We have already changed a few things in the code, including LoadControl, DashMediaPeriod and ChunkSampleStream, and we managed to properly replace chunks in the LinkedList mediaChunks. But we still see no effect when playing the video. It seems that doing so is not enough. We suppose (after reading the issue mentioned above) that the underlying buffer does not get changed even though the methods are called and the LinkedList is modified. 

Can you help us spotting what else we need to consider to make the strategy work? Thanks.

We are using ExoPlayer v2.3.0 on Android 7.0 and Samsung Galaxy S7 Edge.

**Comment by ojw28** [comment]
If you've already found a method that does what you're trying to do (`maybeDiscardUpstream`), can't you inspect that method and figure out what it's doing differently?

**Comment by wasp898** [comment]
Thank you for the answer.
The missing piece seems to be in the TrackOutput, which handles the lower level buffer. It appears that ExoPlayer is using a circular byte buffer that puts chunks always in the back of the buffer (or it overwrites what's already in there), so for now we are investigating if it is possible to replace the circular buffer so that we can replace a chunk with another chunk, without discarding everything that comes after. 
We'll see if this approach leads us somewhere. Unless you have other suggestions?
Otherwise, I guess the issue can be closed. Thanks again.
