### ISSUE TITLE
E-AC3 support for HLS, Smooth & DASH playback available?

### ISSUE THREAD

**Issue by nataraajc** [google/ExoPlayer#2881]
ExoPlayer Version 2.3 (Demo Player from Android PlayStore)

The player throws error saying "Media includes audio track, but none are playable by this device" when we try to play E-AC3 audio in HLS, Smooth or DASH. Is there a way to playback EAC3 using software decoding or pass through to TV? Where as it plays AC3 content fine in HLS, Smooth and DASH.

**Comment by andrewlewis** [comment]
E-AC-3 can be played via HDMI passthrough where the connected device advertises support. It is possible for a devices to advertise support AC-3 but not E-AC-3.

See #2148 for more information on passthrough and on-device decoding of these formats.
