### ISSUE TITLE
Support key-frame accurate seeking in HLS

### ISSUE THREAD

**Issue by mohammed-atif** [google/ExoPlayer#2882]
<h3>SimpleExoPlayer.seekTo(int millis) issue</h3>
<p>I have seen several issues requesting the same feature of smoother seeking in Exoplayer</p>
<p>At one thread I have seen your reply mentioning about the decoder but Android's VideoView default seeking is much more smoother when compared to ExoPlayer or MediaPlayer</p>

<p><b>Here is my code for reference</b></p>

```
@Override
    public boolean onScroll(MotionEvent e1, MotionEvent e2, float distanceX, float distanceY) {
        long seekTo = (long) (mPlayer.getCurrentPosition() - distanceX);
        Log.d(TAG, "current scroll position "+seekTo);
        mPlayer.seekTo(seekTo);
        return true;
    }

```
I am using locally stored mp4 file to play using Exoplayer with TextureView

current exoplayer version - r2.4.1
```com.google.android.exoplayer:exoplayer-core:r2.4.1```

Are there any configurations that I have to change for smoother seeking?

**Comment by ojw28** [comment]
The reason behavior is different is that ExoPlayer does frame-accurate seeking (in all cases). I think VideoView does key-frame accurate seeking, which is faster but less accurate. We can use this issue to track supporting key-frame accurate seeking as an option, but it's low priority.

**Comment by mohammed-atif** [comment]
@ojw28 , In other players, we have a callback which notifies about the successful seeking. If I make multiple calls for seek using onScroll method, I can ignore the inputs if seek is in progress, but in case of ExoPlayer there is no such callback and due to multiple seek requests, the performance of seeking further goes down. It would be really good if ExoPlayer too provides the callbacks for seek completion.

Apart from that, as you mentioned about the key-frame seeking, can you provide me details about the class which I can look into to do minor tweaks at my end for better seeking?

**Comment by goffioul** [comment]
@AtifMohammed Not sure this will help you, but I also needed some callback after seek completion. What I come up with was to drop a flag in my app when starting the seek operation, then listen to state change in onPlayerStateChanged. If my flag was set and the player state was STATE_READY, then I fired my callback. That seemed to work for my use case.

**Comment by mohammed-atif** [comment]
@goffioul Thanks for the response, I figured it out few days ago but couldn't update here. While seeking the state goes to Buffer and after seek it shifts to ready.

@ojw28 forward seek works good after adding the callbacks. But when I seek backwards, player's current time is not updated.

```
int currentTime =  mSimpleExoPlayer.getCurrentTime();
int seekToMillis = currentTime - 45; //seek duration is very small in the range of 30 to 60 milliseconds
mSimpleExoPlayer.seekTo(seekToMillis);
```

if seekToMillis is currentTime + duration then everything works good, but when seeking back, in STATE_READY, currentTime remains same after every seek action which causes back and forth jerk to the video. Is it avoidable by making any changes?

**Comment by ojw28** [comment]
You shouldn't rely on the player reporting exactly your seek position back through getCurrentTime. The reported position may be adjusted slightly. If you want to seek in tiny increments like this, you should find a way to keep track of the last position that you performed a seek in your own code, and subtract 45 from that value each time. With that approach each position you pass to seekTo really will be 45 less than the previous value passed.

If we could keep this issue on topic, which is to support seeking to the nearest key-frame, that would be good. Thanks.

**Comment by green-nick** [comment]
Hi, @ojw28 
When we could see key-frame supporting on release? Will it be in 2.6.2?
Or does dev-branch stable enough?

**Comment by ojw28** [comment]
It will be 2.7.0 (I'm not sure whether we're doing any further 2.6.x releases, but if we are they wont include the relevant changes). We don't have an ETA yet.

**Comment by green-nick** [comment]
@ojw28 Ok, thanks!

**Comment by jclova** [comment]
Really hoping to see the seekTo() options for us to choose:
1. Accurate/slow seek
2. To nearest keyframe/fast seek.

**Comment by ojw28** [comment]
This is supported for all media types except HLS in 2.7.0, which will be released shortly, via `ExoPlayer.setSeekParameters`.

**Comment by ojw28** [comment]
2.7.0 is now released, so this is now supported except for when playing HLS content.

**Comment by jclova** [comment]
Hooray!!
Thank you so much for making the ExoPlayer awesome!

**Comment by KKXLC** [comment]
@ojw28 i have noticed an strange thing while using exoplayer in our app. we load small video files of say 6min and seek to a particular player position. after that we run method to get actual player position after say 5000 ms or 3 sec then it returns with a value (timestamp) of the current player position and we also store the current time at which we fetched the current player position. now if we compare this value with the ideal player position or say the position of player in file at that current milli which is say 3 sec after the seek . we fing the actual player position is lagging by 200 to 500 ms. if we re-seek then also the error remains and it may increase or decrease. so how accurate is excoplayer  ? how to correct the wrong seek ? we are looking to achieve 100 ms accuracy while seeking. any help please.

**Comment by KKXLC** [comment]
@ojw28 still facing problem in seeking accurately in Exoplayer. we are facing this problem of inaccurate seeking when ever we are trying to seek to a time or play the file from a particular time.
say if we start playing a media file *.mp4 (<15mb) to a particular point say "x". 
if we play a file giving the player position from were it has to play that media it seeks to that position and stat playing but inaccurately. to get inaccuracy we did below steps:

we again seek to point "x1" at current time CT1.
so the player position will change as the time changes so it means at time (CT1+t) the player position should be at (x1+t).
but when we fetch the player position at (CT1+t) we are getting (x1+tt).  so (tt-t = e), e is the error which ranges from 700 ms to 100 ms easily.
we are playing media at 1x player speed and content is fixed 24fps or 25 fps.
please help. how to remove this error and get at least 50 ms accuracy.

**Comment by tonihei** [comment]
@KKXLC Did you take into account that the player needs to rebuffer the media from the seek point? Could the "error" just be the buffer time?

**Comment by KKXLC** [comment]
we are calculating the buffer by tracking change of status of player and its like max 120 ms (some time its even as small as 20 ms and when the player is initialized first time then the buffer is high so we refresh to reduce the buffer value. we are adjusting it also but still the error remains the same.

**Comment by andrewlewis** [comment]
If I understand correctly, CT1 is the time at which you see the player position transition from BUFFERING to READY after the seek. I think the player position should indeed be advancing approximately linearly from that point, though there is a bug where the position may not quite be continuous during the first 500 ms of playback; see #3841 for more information. Do you really see "700 ms to 100 ms" error? If this is a typo and it's actually 70--100 ms then I think it could be explained by #3841. (I'm assuming the stream has audio; if not something else is going on.)

**Comment by ojw28** [comment]
Can this discussion please be moved to https://github.com/google/ExoPlayer/issues/3913. It's not related to what this one is supposed to be tracking. Thanks.

**Comment by animaonline** [comment]
When will this be support for HLS streams?

**Comment by ojw28** [comment]
We do not have an ETA for supporting this for HLS.

**Comment by BrainCrumbz** [comment]
Hi all. Does anyone know how key-frame accurate seeking is reflected in `SeekParameters` "constants" ([ref.](https://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/SeekParameters.html#field.summary))?

Which one should be passed to `setSeekParameters()` in order to achieve:

1. any frame accurate seeking
1. key-frame accurate seeking

?

TA

**Comment by andrewlewis** [comment]
@BrainCrumbz If you want to snap the seek position to the closest keyframe use `SeekParameters.CLOSEST_SYNC`. To see to a exact frame (the frame before the requested position, even if it's not a keyframe) use `SeekParameters.EXACT`.

**Comment by BrainCrumbz** [comment]
@ maintainers: would you consider a tiny PR over javadoc for those constants, to better clarify what each means? Not sure if e.g. *"seeking to the closest sync point"* fully clarifies that's a keyframe.

**Comment by ojw28** [comment]
The documentation is deliberately vague, because exactly what happens depends a bit on the type of media being played. For DASH and SmoothStreaming, chunk boundaries are the sync points. If a chunk contains an additional keyframe somewhere in the middle, that's not considered as a sync point. For regular MP4, sync points are keyframes. For fragmented MP4, sync points are fragment boundaries.

The takeaway here is that sync points are whatever the underlying format naturally supports. A sync point will nearly always be aligned with a keyframe, but it's not necessarily true that all keyframes will be considered sync points.

**Comment by tipoc123** [comment]
Do you have some enhancements for HLS seek? Current HLS seek is slow and not suitable for production use (ExoPlayer 2.9.6)

**Comment by NathanSass** [comment]
I agree. It would be great to see this scheduled ASAP

**Comment by junnova** [comment]
Like the MediaPlayer, it's just return the start position of the ts which the seek point owns to. The seeking operation is fast。
How should I modify the Exo source to be the same as the Seeking of MediaPlayer?

**Comment by stevemayhew** [comment]
@ojw28  and @AquilesCanta I'm looking at this now for I-Frame only playback.  The issue there is when you scrub multiple i-Frames are loaded an discard before any first frame shows, so the delay runs into 100's of milliseconds depending on the network and size of i-Frames.

My plan is to implement something similar to `DefaultDashChunkSource`'s method, `getAdjustedSeekPositionUs()` obviously the playlist would need to support and be marked with `#EXT-X-INDEPENDENT-SEGMENTS` for this to work.  Also before / after tolerances less than a segment duration would not really work (as there is no way to know the GOP interval in the HLS segments data).   For I-Frame only, this does not matter trivially as each segment contains only a single i-Frame.

Scrub seeking (like the original request is for) is best done in i-Frame mode, so we could restrict the `getAdjustedSeekPositionUs()` function to only adjust the position when the primary sample stream wrapper is I-frame only.

**Comment by tdc-w** [comment]
@stevemayhew 
>implement something similar to DefaultDashChunkSource's method, getAdjustedSeekPositionUs()

I have a similar issue.
Did this approach work?

**Comment by jonas-livesporttv** [comment]
@ojw28 you closing this issue means that key-frame accurate seeking in HLS is possible now?

**Comment by ojw28** [comment]
I believe support was added by @stevemayhew in the merged pull requests referenced above.
