### ISSUE TITLE
Audio visualization and buffer access crash

### ISSUE THREAD

**Issue by kvecoman** [google/ExoPlayer#2883]
I have created AudioVisualizer based on issue #1449, by extending MediaCodecAudioRenderer and overriding processOutputBuffer() and everything works fine while audio is playing, but the problem shows up when songs are being changed, my app sometimes crashes on single line in my native c++ code that reads from ByteBuffer that I obtained in processOutputBuffer(), so **my question is how can I know if I should read from ByteBuffer that I receive** while the songs are being changed. I have seen in MediaCodec source code that there are calls to buffer.setAccessible(false), but it is colored red (because it cannot be resolved) and I also don't have that method available when I import java.nio.ByteBuffer.

Also, the buffer is only read, it is not manipulated in any other way, relevant samples are copied and cached elsewhere.

This is my overriden processOutputBuffer() method:

```

@Override
    protected boolean processOutputBuffer( long positionUs, long elapsedRealtimeUs, MediaCodec codec, ByteBuffer buffer, int bufferIndex, int bufferFlags, long bufferPresentationTimeUs, boolean shouldSkip ) throws ExoPlaybackException
    {
        boolean fullyProcessed;




            //Check whatever we can for info if we should send this buffer
            if ( mEnabled && mOldBufferIndex != bufferIndex && !shouldSkip && mBufferReceiver != null && buffer != null && bufferFlags == 0 )
            {
                //Send buffer for visualization purposes
                mBufferReceiver.processBuffer( buffer, buffer.limit(), bufferPresentationTimeUs, mPcmFrameSize, mOutputSampleRate, positionUs );

                //Remember buffer that we used now, so we don't send same one again ( all buffers are processed in one run )
                mOldBufferIndex = bufferIndex;
            }
        


         
        fullyProcessed = super.processOutputBuffer( positionUs,
                elapsedRealtimeUs,
                codec,
                buffer,
                bufferIndex,
                bufferFlags,
                bufferPresentationTimeUs,
                shouldSkip );




        return fullyProcessed;
    }

```

**Comment by ojw28** [comment]
As long as you're handling the buffer synchronously in your processBuffer call, I'm pretty sure you should always have access in `processOutputBuffer` (prior to `super.processOutputBuffer` being called). You could also take a look at how/when buffers are being fed into `AudioTrack` from the regular `processOutputBuffer` implementation. The buffers must be valid at those points.

Unfortunately, since this is a customization rather than an issue with the library itself, we're unable to help further on this issue tracker.
