### ISSUE TITLE
Device dependent restart problems.

### ISSUE THREAD

**Issue by mofneko** [google/ExoPlayer#2884]
### Issue description
When regenerating an instance of the SimpleExoPlayer class, restart it on a specific device.

### Reproduction steps
When regenerating an instance of SimpleExplayer at an arbitrary timing, the device restarts. I generated a sample to check the phenomenon of restart. Please refer to the test content chapter.

### Link to test content
See complete diff.
https://github.com/mofneko/ExoPlayer/compare/dev-v2...mofneko:lab-player-init?expand=1

### Version of ExoPlayer being used
We using exoplayer version dev-v2.
and, repository last commit 3a448f3a0ea935f9e11b8a6bd5db8b4a62144cf3.

### Device(s) and version(s) of Android being used
Android O on Pixel（build no: OPP2.170420.019）is reproduce.
Android O on Nexus 5X（build no: OPP1.170223.012）is not reproduce.

**Comment by ojw28** [comment]
Device restarts for O need to be reported on the Android issue tracker, as described [here](https://source.android.com/source/report-bugs).

**Comment by mofneko** [comment]
ping @ojw28. Android mashmarrow on Pixel XL reproduced the same issue.
Should this issue be reported in a new issue? Or, can you resume this report?

**Comment by ojw28** [comment]
You should be reporting this issue on the Android issue tracker, as explained above.

**Comment by mofneko** [comment]
Thanks.
https://issuetracker.google.com/issues/62395952

**Comment by mofneko** [comment]
Thanks. I reported it!
https://issuetracker.google.com/issues/62395952
