### ISSUE TITLE
How to determine when a DASH media segment has been requested and received.

### ISSUE THREAD

**Issue by qlthd** [google/ExoPlayer#2886]
Hi everyone. I'd like to determine at the end of the video how many segments i have requested and received
Thanks

**Comment by ojw28** [comment]
`DashMediaSource` takes a `AdaptiveMediaSourceEventListener` argument through its constructor, which is invoked every time a load is started/stopped/canceled/completed. You should be able to do some counting in your listener implementation to figure this out.
