### ISSUE TITLE
Not display closed caption in HLS (text track is not exposed)

### ISSUE THREAD

**Issue by haoduong-acutek** [google/ExoPlayer#2887]
### Issue description
in HLS, The text track  is not exposed , so can not display closed caption

### Reproduction steps
With the same link, VLC played with ClosedCaption, but not with Exo sample app.

### Link to test content
Attached in email

### Version of ExoPlayer being used
r2.4.1

### Device(s) and version(s) of Android being used
STB version 6.0.1

### A full bug report captured from the device
Attached in email

**Comment by ojw28** [comment]
This is tracked by https://github.com/google/ExoPlayer/issues/2565.
