### ISSUE TITLE
How to ad preroll and midroll support in exoplayer 2.4 ??

### ISSUE THREAD

**Issue by naseeb8950925214** [google/ExoPlayer#2888]
Hi,

I want to play preroll and midroll ads in exoplayer on basis of que points e.g right after playing preroll ad, ads should be played at 30 seconds , 1 minute and 2 minute duration of content playback. I have tried for same and came to know that i can create playlists using **ConcatenatingMediaSource**. But this does not match my requirement, as i want to play ads at given que points. Please help me.

**Comment by andrewlewis** [comment]
If you know the URLs for the ad media at the time of instantiating the media source, you can use ConcatenatingMediaSource to concatenate ClippingMediaSources that load portions of content with MediaSources that load ads. For example, to play one minute of content with a midroll ad at 30 seconds and preroll/postroll ads, you could structure the media source like: `ConcatenatingMediaSource(prerollAdMediaSource, ClippingMediaSource(contentMediaSource, 0 s, 30 s), midrollAdMediaSource, ClippingMediaSource(contentMediaSource, 30 s, 60 s), postrollAdMediaSource)`.

If you don't know the URLs of the ads in advance you'll need to make a custom media source, like ImaAdsMediaSource.

**Comment by naseeb8950925214** [comment]
Thanks for pointing to ClippingMediaSource. Can you please tell me how to play ads on basis of ID3Metadata. e.g if i get AD tag at a particular moment, i should play ad and as soon as i get MP tag, main content should start playing.

**Comment by andrewlewis** [comment]
In that case, you can't construct a MediaSource in advance with all the ad URLs. We don't currently provide a direct way to make the player insert ads based on ID3 metadata, but you may be able to handle the metadata yourself using MetadataRenderer, and re-`prepare` the player as required.

**Comment by ManojJangra** [comment]
How to play IMA pre roll ads  and video content in  single Exoplayer. we are using this code 

 BandwidthMeter bandwidthMeter = new DefaultBandwidthMeter();
        TrackSelection.Factory videoTrackSelectionFactory = new AdaptiveTrackSelection.Factory(bandwidthMeter);
        TrackSelector trackSelector = new DefaultTrackSelector(videoTrackSelectionFactory);
        player = ExoPlayerFactory.newSimpleInstance(context, trackSelector);
        playerView = (SimpleExoPlayerView) findViewById(R.id.exoPlayerView);
        playerView.setPlayer(player);
		DataSource.Factory dataSourceFactory = new DefaultDataSourceFactory(context,
        Util.getUserAgent(context, "yourApplicationName"), null);
        MediaSource  contentMediaSource = new HlsMediaSource(Uri.parse(videoUrl), dataSourceFactory, mainHandler, null);
        player.prepare(videoSource);
        player.setPlayWhenReady(true);

Please suggest  me for IMA pre-roll ads.

**Comment by andrewlewis** [comment]
Instantiate an `ImaAdsMediaSource` passing in your existing `contentMediaSource`, as described in the [README](https://github.com/google/ExoPlayer/tree/dev-v2/extensions/ima).
