### ISSUE TITLE
Illegal playlist type: LIVE

### ISSUE THREAD

**Issue by needz** [google/ExoPlayer#2889]
### Issue description
The provided link works fine in buil-tin MediaPlayer, but doesn't play in ExoPlayer.
Is there anything that can be done to fix it? Thanks.

### Reproduction steps
Play the provided link in Demo app.

### Link to test content
http://stream01.yamgo.com/iPhone/HLS_TS/mptslive/clubbingtv-mobile.3gp.m3u8

### Version of ExoPlayer being used
ExoPlayer 2.4.0

### Device(s) and version(s) of Android being used
Nexus Player

### A full bug report captured from the device

> 05-30 17:16:00.075 17736-17736/com.google.android.exoplayer2.demo I/DefaultRenderersFactory: Loaded LibvpxVideoRenderer.
> 05-30 17:16:00.080 17736-17736/com.google.android.exoplayer2.demo I/DefaultRenderersFactory: Loaded LibopusAudioRenderer.
> 05-30 17:16:00.081 17736-17736/com.google.android.exoplayer2.demo I/DefaultRenderersFactory: Loaded LibflacAudioRenderer.
> 05-30 17:16:00.081 17736-17736/com.google.android.exoplayer2.demo I/DefaultRenderersFactory: Loaded FfmpegAudioRenderer.
> 05-30 17:16:00.083 17736-17736/com.google.android.exoplayer2.demo I/ExoPlayerImpl: Init ExoPlayerLib/2.4.0 [fugu, Nexus Player, Asus, 26]
> 05-30 17:16:00.105 17736-17736/com.google.android.exoplayer2.demo D/EventLogger: state [0.00, true, I]
> 05-30 17:16:00.108 17736-17736/com.google.android.exoplayer2.demo D/Track type: 2
> 05-30 17:16:00.108 17736-17736/com.google.android.exoplayer2.demo D/Track uri: http://stream01.yamgo.com/iPhone/HLS_TS/mptslive/clubbingtv-mobile.3gp.m3u8
> 05-30 17:16:00.138 17736-20243/com.google.android.exoplayer2.demo D/NetworkSecurityConfig: No Network Security Config specified, using platform default
> 05-30 17:16:00.180 17736-17752/com.google.android.exoplayer2.demo I/zygote: Starting a blocking GC ObjectsAllocated
> 05-30 17:16:00.184 17736-17736/com.google.android.exoplayer2.demo D/EventLogger: state [0.08, true, B]
> 05-30 17:16:00.200 17736-17749/com.google.android.exoplayer2.demo I/zygote: Do partial code cache collection, code=124KB, data=67KB
> 05-30 17:16:00.202 17736-17749/com.google.android.exoplayer2.demo I/zygote: After code cache collection, code=124KB, data=67KB
> 05-30 17:16:00.202 17736-17749/com.google.android.exoplayer2.demo I/zygote: Increasing code cache capacity to 512KB
> 05-30 17:16:00.321 17736-17785/com.google.android.exoplayer2.demo D/OpenGLRenderer: endAllActiveAnimators on 0xdb7f8500 (ExpandableListView) with handle 0xcc0cb760
> 05-30 17:16:00.418 17736-17736/com.google.android.exoplayer2.demo E/EventLogger: internalError [0.31, loadError]
>                                                                                  com.google.android.exoplayer2.ParserException: Illegal playlist type: LIVE
>                                                                                      at com.google.android.exoplayer2.source.hls.playlist.HlsPlaylistParser.parseMediaPlaylist(HlsPlaylistParser.java:291)
>                                                                                      at com.google.android.exoplayer2.source.hls.playlist.HlsPlaylistParser.parse(HlsPlaylistParser.java:129)
>                                                                                      at com.google.android.exoplayer2.source.hls.playlist.HlsPlaylistParser.parse(HlsPlaylistParser.java:41)
>                                                                                      at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:115)
>                                                                                      at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
>                                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
>                                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
>                                                                                      at java.lang.Thread.run(Thread.java:764)
> 05-30 17:16:00.419 17736-20238/com.google.android.exoplayer2.demo E/ExoPlayerImplInternal: Source error.
>                                                                                            com.google.android.exoplayer2.ParserException: Illegal playlist type: LIVE
>                                                                                                at com.google.android.exoplayer2.source.hls.playlist.HlsPlaylistParser.parseMediaPlaylist(HlsPlaylistParser.java:291)
>                                                                                                at com.google.android.exoplayer2.source.hls.playlist.HlsPlaylistParser.parse(HlsPlaylistParser.java:129)
>                                                                                                at com.google.android.exoplayer2.source.hls.playlist.HlsPlaylistParser.parse(HlsPlaylistParser.java:41)
>                                                                                                at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:115)
>                                                                                                at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
>                                                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
>                                                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
>                                                                                                at java.lang.Thread.run(Thread.java:764)
> 05-30 17:16:00.424 17736-17736/com.google.android.exoplayer2.demo E/EventLogger: playerFailed [0.32]
>                                                                                  com.google.android.exoplayer2.ExoPlaybackException
>                                                                                      at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:357)
>                                                                                      at android.os.Handler.dispatchMessage(Handler.java:101)
>                                                                                      at android.os.Looper.loop(Looper.java:164)
>                                                                                      at android.os.HandlerThread.run(HandlerThread.java:65)
>                                                                                   Caused by: com.google.android.exoplayer2.ParserException: Illegal playlist type: LIVE
>                                                                                      at com.google.android.exoplayer2.source.hls.playlist.HlsPlaylistParser.parseMediaPlaylist(HlsPlaylistParser.java:291)
>                                                                                      at com.google.android.exoplayer2.source.hls.playlist.HlsPlaylistParser.parse(HlsPlaylistParser.java:129)
>                                                                                      at com.google.android.exoplayer2.source.hls.playlist.HlsPlaylistParser.parse(HlsPlaylistParser.java:41)
>                                                                                      at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:115)
>                                                                                      at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
>                                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
>                                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
>                                                                                      at java.lang.Thread.run(Thread.java:764)

**Comment by AquilesCanta** [comment]
The live playlist type [is not supported by the spec](https://tools.ietf.org/html/draft-pantos-http-live-streaming-23#section-4.3.3.5). I will remove this exception so as to ignore the value if invalid, like in this case.
