### ISSUE TITLE
[HttpDataSource] Reaction to Content-Length header field being zero

### ISSUE THREAD

**Issue by bascel** [google/ExoPlayer#289]
After investigating an error i saw today while playing live DASH, i saw that this case is not being handled:

The Content-Length field in an http reponse from the server can have a value of zero. I don't know why this is sometimes happening in my case, but it does (occasionally), and [here](http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html) it is stated that "Any Content-Length greater than or equal to zero is a valid value".

So what happens in the ExoPlayer library? The value is parsed in `HttpDataSource.getContentLength(HttpUrlConnection)` and saved as the class attribute `HttpDataSource.dataLength`.

Finally, in `ChunkSampleSource.getBufferedPositionUs()`, this value is used via `mediaChunk.getLength()`, and results in a `java.lang.ArithmeticException` (divide by zero).

Where is the best spot to fix this? Simple zero check in `getBufferedPositionUs()`?

Side note: So far I only saw this happening when working with very small segments (up to 1 sample per segment)

**Comment by ojw28** [comment]
- Why are you working with such small segments, out of interest? That doesn't sound like a good idea.
- I think it's fine to fix it in getBufferedPositionUs, if that's the only thing that's broken. I can do this.

**Comment by ojw28** [comment]
Fixed in dev.

**Comment by bascel** [comment]
Thanks =)

Smaller segments allow for a lower e2e delay. Whether it's appropriate to use segments that small depends on some more restrictions/circumstances.
