### ISSUE TITLE
Set the volume of multiple MediaSource's in a MergingMediaSource

### ISSUE THREAD

**Issue by jmgirven** [google/ExoPlayer#2890]
Is it possible to have two `MediaSource`'s in a configuation like:

```
MediaSource audio = new ExtractorMediaSource(Uri.parse(".../audio.mp3")...);
MediaSource video = new ExtractorMediaSource(Uri.parse(".../video.mp4")...);
player.prepare(new LoopingMediaSource(new MergingMediaSource(video, audio)));
```

Where both have an audio track playing at the same time, and you can set the volume of each independently? E.g. video at 50% and audio at 75% in the above example.

**Comment by ojw28** [comment]
We do not support synchronized playback within a single player of multiple audio tracks. You'd have to do some quite in-depth customization to support that kind of use case, which is beyond the scope of this issue tracker.
