### ISSUE TITLE
HLS Live Stream Freezes and stops requesting chunks

### ISSUE THREAD

**Issue by jrocharodrigues** [google/ExoPlayer#2892]
### Issue description
When playing a HLS Live stream, the play back freezes, the player enters in buffering state, and stops downloading media chunks, only downloads playlist files.
### Reproduction steps
Add the stream i've sent by email to dev.exoplayer@gmail.com to the demo app, play it and wait until the playback freezes.

### Link to test content
Sent by mail to dev.exoplayer@gmail.com

### Version of ExoPlayer being used
ExoPlayer 2.1.0 - 2.4.1, in previous versions the stream works fine.

### Device(s) and version(s) of Android being used
Happens on every device i tested (Nexus 9, Pixel C, Nexus 5, Samsung S3, Samsung S7, Nexus 5x...).

### A full bug report captured from the device
Bug Report and logs also sent by mail to dev.exoplayer@gmail.com.

**Comment by jrocharodrigues** [comment]
I found the problem. 
The the value of #EXT-X-PROGRAM-DATE-TIME was coming with an date from the future, and it was causing the playback to stop.
Changing the value to an Date form the past solved the issue.
Thanks

**Comment by jrocharodrigues** [comment]
I've closed the issue because i've found the problem, and we could solve it server side.
Anyway, do you think this behaviour  ok? Should the player be so dependant on the the correctness of this tag?

**Comment by AquilesCanta** [comment]
We make our best to provide robust support, even sometimes when the stream is not technically valid. The amount of things that can go wrong is innumerable, and this issue tracker is a nice museum of malformed media. If we try to study and workaround every possible media malformation (we actually do sometimes), we won't have time to improve ExoPlayer for correct media. Besides, client-side-wise, the HLS spec is quite tricky as it is. 

We try to work around malformed media issues, but fixing the media should always be the first approach.

**Comment by jrocharodrigues** [comment]
@AquilesCanta Yes, you're right.
Two questions that can help me, and maybe others, to no open issues like this one, where the problem is on the media not following the spec.
1 - Which version of the spec is ExoPlayer following? Is there any place we can keep track on that?
2 - Is there any tool you can recommend to validate manifest/playlist files?

Thanks in advance

**Comment by AquilesCanta** [comment]
> 1 - Which version of the spec is ExoPlayer following? Is there any place we can keep track on that?

We aim for the newer ones but we try to support anything allowed by any of the versions of the spec, unless we have good reasons not to. The newer the spec version, the higher the chances of us supporting it eventually.   

> 2 - Is there any tool you can recommend to validate manifest/playlist files?

I don't know any. We'll probably write a [medium](https://medium.com/google-exoplayer) blogpost including the best practices for generating HLS content, but no automatic tool. Let me know if you run into any.

**Comment by jrocharodrigues** [comment]
>> 1 - Which version of the spec is ExoPlayer following? Is there any place we can keep track on that?

> We aim for the newer ones but we try to support anything allowed by any of the versions of the spec, unless we have good reasons not to. The newer the spec version, the higher the chances of us supporting it eventually.

Ok, once again i understand and agree with your position of trying to support the maximum things possible.
One of the reasons i made this question was because, for the TAG EXT-X-PROGRAM-DATE-TIME , until version 18, the spec stated in section [6.3.3](https://tools.ietf.org/html/draft-pantos-http-live-streaming-18#section-6.3.3):

 "The client MUST NOT depend upon the correctness or the consistency of
   the value of the EXT-X-PROGRAM-DATE-TIME tag."
This sentence was removed form version 19 onward.
And although i agree with you that in the case i reported, we should correct the issue with the tag on the server, there are probably other similar situations where it would be useful to know to which spec versions we should be looking at to know what could possible be wrong with the media.

>> 2 - Is there any tool you can recommend to validate manifest/playlist files?

> I don't know any. We'll probably write a medium blogpost including the best practices for generating HLS content, but no automatic tool. Let me know if you run into any.

The blogpost is a good idea.
Regarding tools, when trying to find cause of this issue, i''ve run into this python tool: https://github.com/epiclabs-io/hls-analyzer
It didn't help me with this issue in particular, but i will keep it in my toolbox, maybe it can help with others.

Best regards
