### ISSUE TITLE
Why ExoPlayer requires ACCESS_WIFI_STATE permission ?

### ISSUE THREAD

**Issue by RegisAG** [google/ExoPlayer#2894]
### Issue description
I use a version of ExoPlayer (I have not checked is still required in more recent versions but I don't want to change my ExoPlayer version) where there is a ACCESS_WIFI_STATE permission in the ExoPlayer manifest.
<uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>

The problem is that it adds a permission to my project and will block the automatic updates on the store. So I would like to remove this permission. It seems that my project works properly but I would like to be sure that it will not induce problem.

What is the purpose of this ACCESS_WIFI_STATE permission ? Can I remove it safely ?

### Reproduction steps
Add ExoPlayer to a project. It adds a ACCESS_WIFI_STATE permission to the project which blocks the automatic updates on Google Play.

### Link to test content
None.

### Version of ExoPlayer being used
Version 1.x (I don't know exactly which one).

### Device(s) and version(s) of Android being used
All.

### A full bug report captured from the device
N/A

**Comment by ojw28** [comment]
We removed this permission approximately 2 years ago. I don't think it was ever required, so likely it was added unintentionally and later removed. Obviously we can't fix versions going backward in time, so you should upgrade to either the latest 1.x or latest 2.x version if you a version with the permission removed.

You can probably remove it safely from the version you're using, yes.
