### ISSUE TITLE
Expose start and end points of ClippingMediaSource in UI, so that the user can adjust them

### ISSUE THREAD

**Issue by b0g8** [google/ExoPlayer#2898]
*** ISSUES THAT IGNORE THIS TEMPLATE WILL BE CLOSED WITHOUT INVESTIGATION ***

### Issue description
I want to let the user chose the start and end points of videos in a playlist. For this, the full duration of videos should be loaded, and the user be able to drag trim in/out points. Then, at playback, these points should be taken into consideration.

I did not find a built in way to achieve this, so now I'm relying on seeks and some hacks in the UI, but would be nice if it would be supported directly by ExoPlayer.

**Comment by ojw28** [comment]
This sounds niche enough for us to not support it directly. I'd suggest you implement your own UI components for this.
