### ISSUE TITLE
Stop video from looping

### ISSUE THREAD

**Issue by radko93** [google/ExoPlayer#2899]
Is there any way to stop a video from looping (e.g. after a button press)? Seems that  `onPlayerStateChanged` is not fired for `LoopingMediaSource` when a video ends (or at any other state other than the beginning). I don't want to interrupt during the playback. 

### Version of ExoPlayer being used
Currently testing on `2.2.0`, not sure if it's any different later on.

### Device(s) and version(s) of Android being used
Galaxy S7, 7.0.0

**Comment by ojw28** [comment]
In the `dev-v2` branch there's an `ExoPlayer.setRepeatMode` method that allows looping behavior to be toggled on and off. It's intended that you should use this rather than `LoopingMediaSource` except for certain niche use cases.

Will that let you do what you want?

**Comment by radko93** [comment]
Yeah, I missed this while searching the repo. Waiting for the release then, thanks!
