### ISSUE TITLE
Which part of the code to find a DASH segment number, its arrival time, other infos etc

### ISSUE THREAD

**Issue by qlthd** [google/ExoPlayer#2909]
Hi !
I'd like to find some informations about each segment requested during buffering, like its number, its arrival time, delivery time. I've created a class implementing `AdaptiveMediaSourceEventListener` with `void onLoadStarted(DataSpec dataSpec, int dataType, int trackType, Format trackFormat,int trackSelectionReason, Object trackSelectionData, long mediaStartTimeMs,long mediaEndTimeMs, long elapsedRealtimeMs);` The problem is that i can't get the segment number from this and i'm pretty sure it can be extracted from somewhere else in the code (i don't want to get the segment number by incrementing a variable each time onLoadStarted() is called), also i'm getting the arrival time with the variable `mediaStartTimeMs` but sometimes a n segment will have a smaller arrival time than the n-1 segment ( not logical !), that's why i'm not sure these values really correspond to a n segment, if i'm looking in the right place or not .
I've seen that these informations could maybe be obtained with the interface `DashSegmentIndex`, but i don't know how I could implement it and where could it be used ..

**Comment by ojw28** [comment]
You're looking in the right place (taking the demo app and updating `EventLogger` to output logging in the various `onLoad...` methods is a good place to get started and see what data is available). We do not report segment number, and do not plan on doing so. Media start and end time is preferred because it more gracefully handles cases like two segments being downloaded in a single request.

I'm not sure what you mean when you say:

> i'm getting the arrival time with the variable mediaStartTimeMs but sometimes a n segment will have a smaller arrival time than the n-1 segment ( not logical !)

What is an "arrival time"? To make it clearer what you're seeing, perhaps you can add logging to `onLoadStarted`, and then provide us with the sequence of logging that you see and that you believe to be unexpected.

**Comment by qlthd** [comment]
Thanks for your help !
Okay so the `AdaptiveMediaSourceEventListener` seems to be the right class to find these informations.
I was wrong about the arrival time let's forget this. My goal here is to get some informations about EACH segment requested, for example the segment duration. How could I get the duration of a segment ? I tried to do a substraction of mediaEndTimeMs- mediaStartTimeMs, but it seems the value is not relevant because it should be a static one.

**Comment by ojw28** [comment]
`mediaEndTimeMs - mediaStartTimeMs` is correct. I don't understand what you mean when you say it "should be a static one".

**Comment by qlthd** [comment]
figured out that a lot of informations for each segment can be obtained thanks to the AdaptiveMediaSourceEventListener interface like its size, its arrival time, delivery time using variables like mediaEndTimeMs provided in methods onLoadCompleted . But now I would like to get the the number (or index ?) assigned to each segment, i'm pretty sure it can be extracted from somewhere in the code. These values could be really useful for Chunk replacement. Have you got any ideas where I could find such values ? I've looked in classes implementing the DashSegmentIndex interface but didn't really find how to get what I wanted.

**Comment by ojw28** [comment]
As already explained above, we do not report segment number and do not plan on doing so. 

`AdaptiveMediaSourceEventListener` is only intended for reporting information (e.g. for logging / debugging purposes). It's not intended that such a listener be implemented to actually modify the way in which the player behaves. So it's pretty unclear what you mean when you say the information could be useful for chunk replacement.
