### ISSUE TITLE
Allow seeking in DVR window of DASH/SmoothStreaming live streams

### ISSUE THREAD

**Issue by lkcanal** [google/ExoPlayer#291]
It seems that the seek position for Live SmoothStreaming is always set to 0 has the duration is set to UNKOWN. So there is no way to play the DVR chunks in the past.
Any plan to implement  that ?

Thx.

**Comment by ojw28** [comment]
Allowing seeking in the DVR window of live streaming is planned (for DASH and SmoothStreaming, and perhaps HLS at a later stage). No ETA as of yet though.

**Comment by lkcanal** [comment]
Nice, thx for the answer.

BR.

**Comment by ojw28** [comment]
Leaving open to track delivery of the feature.

**Comment by ldimitroff** [comment]
Is there an ETA on when is this going to be tackled down? Is there anybody working on it now or has an ExoPlayer workaround to support DVR?

**Comment by haitech** [comment]
+1 for this feature :-)

**Comment by srikieonline** [comment]
+1 for this feature

**Comment by haitech** [comment]
@ojw28 any update on this? Out of your recent post this is almost finished?

**Comment by snwebEurosport** [comment]
+1 for this feature

**Comment by etido** [comment]
+1 for this feature

**Comment by brunomsg** [comment]
+1 for this

**Comment by nmhf** [comment]
+1 for this feature

**Comment by fredx21** [comment]
@ojw28 this seems like a popular request. Without giving us an ETA (although you can if you want), can you tell us what priority it has on your feature list?

**Comment by jonnyLPA** [comment]
+1 for this feature

**Comment by TBoshoven** [comment]
What part of this is not working exactly?
On ExoPlayer 1.5.3, I can seek within the available range of a DASH stream (although the demo player and PlayerControl currently do not support this).
I listen to the onAvailableRangeChanged of the DashChunkSource, and seek within this range.
It is possible for me to seek further than live though, resulting in 404.

**Comment by ojw28** [comment]
Yes, you can seek in the live window using the technique you describe for DASH playbacks. The remaining work consists of:

- Implementing the same for SmoothStreaming (and HLS, although that's tracked separately).
- Exposing the available window directly through the ExoPlayer API, rather than requiring that applications listen to DashChunkSource. Having to listen to DashChunkSource is pretty convoluted, particularly given there are normally two of them (video/audio). The plan is to do this as part of a larger refactoring effort that will clear up a bunch of niggles that have built up over the past year or two.

**Comment by luckcoolla** [comment]
+1 for DASH refactoring

**Comment by snwebEurosport** [comment]
Is there a roadmap for the refactoring ?

**Comment by ojw28** [comment]
Not a public one, but the effort is underway already already. We've made a dev-2.X.X-experimental for this, but have opted not to push until we're closer to being done.

**Comment by petrumo** [comment]
+1 for Smooth

**Comment by niclasam** [comment]
+1 For DASH

**Comment by niclasam** [comment]
Any information when seeking in DVR window for Live will be implemented?

**Comment by lkcanal** [comment]
Hi all,

you can indeed already "simulate" a seek in the dvr window of live streams without waiting for the 2.0.0 code branch. 
It's not a clean way to do it, but all you have to do is to be able to change the liveEdge value (see ..ChunkSource classes) on the fly during a playback and call seekTo(0) to force the player to set its new liveEdge position value. So just set the liveEdge value to a position inside your dvr window.

It does the trick in our products at my office. :-) (we are playing SmoothStreamings videos, but the trick should work the same way for Dash contents) 

Cheers.

**Comment by ojw28** [comment]
Seeking in the live window will work in 2.x for both DASH and SmoothStreaming. The functionality will be present in the demo app also. We'll be merging changes to the 2.x branch this week with this functionality.

**Comment by niclasam** [comment]
@ojw28 great news. do you have an expected timeline when release-v2 will be available?

**Comment by ojw28** [comment]
Seeking in the live window is fully supported in `dev-v2` at this point, for both DASH and SmoothStreaming. The functionality is present in the demo app also.

**Comment by peddisri** [comment]
What about HLS?

**Comment by ojw28** [comment]
Seeking in the live window for HLS is tracked by #87. See also [this post](https://medium.com/google-exoplayer/test-8b62d50362ef#.75atfayul), in particular the last paragraph that explains why features land first for DASH, and later for HLS.
