### ISSUE TITLE
onScrubStart has no position argument

### ISSUE THREAD

**Issue by ulyssesdotcodes** [google/ExoPlayer#2910]
Custom scrub behaviour for `DefaultTimeBar` relies on having an accurate `TimeBar` position. `onScrubStart` does not pass in a position, and `TimeBar` doesn't expose the scrub position through a getter. It would be incredibly useful to have `TimeBar` expose the scrub position or add a position argument to `onScrubStart`.

**Comment by ulyssesdotcodes** [comment]
Thank you!

**Comment by ulyssesp** [comment]
Thank you!
