### ISSUE TITLE
Is there a way to check if the dash stream is live or not?

### ISSUE THREAD

**Issue by jiafei1986** [google/ExoPlayer#2911]
Hi
I am using the exoplayer2 to play both vod and live stream, Is there a listener that can get the manifest?  so i can check if the dash is live or not? I was looking in the playerActivity of demo app but can not found it. 

Thanks

**Comment by botondbutuza** [comment]
Not part of the Exo team, but `player.isCurrentWindowDynamic()` is the method you're looking for.

**Comment by jiafei1986** [comment]
@botondbutuza Thank you very much, I will try it.
