### ISSUE TITLE
Get NAME attritube of a track

### ISSUE THREAD

**Issue by nguyenhoanglam** [google/ExoPlayer#2914]
I have a HLS url with the content below:
```java
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:BANDWIDTH=2196608,NAME="source",CODECS="avc1.66.30",RESOLUTION=640x360
chunklist_w1690814161_b2196608_t64c291cmNl.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=596608,NAME="160p",CODECS="avc1.66.30",RESOLUTION=640x160
chunklist_w1690814161_b596608_t64MTYwcA==.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=796608,NAME="240p",CODECS="avc1.66.30",RESOLUTION=640x240
chunklist_w1690814161_b796608_t64MjQwcA==.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1046608,NAME="360p",CODECS="avc1.66.30",RESOLUTION=640x360
chunklist_w1690814161_b1046608_t64MzYwcA==.m3u8
```
In the ExoPlayer demo app, with the Format object, we can get BANDWIDTH, CODECS, RESOLUTION attributes except the NAME attribute. How can I get the NAME attribute?

**Comment by AquilesCanta** [comment]
Listen for `ExoPlayer#EventListener#onTimelineChanged`. The manifest argument should carry an `HlsManifest` object, which contains a reference to the master playlist and a snapshot of the media playlist. Playlists (master and media) carry all their tags in the field `tags`. You can map each `EXT-X-STREAM-INF` to a format using the rest of the attributes. Unfortunately there is no better way, as we don't directly support this attribute. As far as I know, it is not defined in the spec.
