### ISSUE TITLE
Intended uses of setSelectionOverride and setRendererDisabled [Question]

### ISSUE THREAD

**Issue by ghost** [google/ExoPlayer#2917]
I'm trying to understand the difference between these two "options".

Currently, my understanding is that `setRendererDisabled` is for disabling the renderer completely, regardless of the overrides.  `setSelectionOverrides` is for selecting a different track to be rendered by the renderer, French text track vs an English text track.

Is this correct?

I have seen instances, with a text track, that you just set and clear overrides to enable/disable them.  If I wanted to toggle the text track on and off, should I use `setRendererDisabled` or `setSelectionOverrides`?

**Comment by ojw28** [comment]
> Is this correct?

Yes :).

> If I wanted to toggle the text track on and off, should I use setRendererDisabled or setSelectionOverrides?

If you're just playing a single video then I don't think it makes any difference.

It does make a difference if you're playing media that contains multiple periods. For example if you've concatenated multiple media items together using `ConcatenatingMediaSource`, or if you're playing a multi-period DASH stream. In these cases the available tracks can be different moving from period to period. Calling `setSelectionOverride` sets an override that's specific for a set of available tracks. So if you move to another period that has a different set of available tracks, the override wont apply. Disabling the renderer will apply across all periods.

**Comment by ghost** [comment]
I would like to note that  when using the overrides seems to provide a smoother playback experience.  Disabling a renderer causes the player to pause for a second and then resume.

**Comment by ojw28** [comment]
I do not see that issue in the demo app when disabling via the track selector. Are you sure? Please file an issue with specific reproduction steps in the demo app if so.
