### ISSUE TITLE
Issues with streaming MP4 with a paired audio device.

### ISSUE THREAD

**Issue by dhesson** [google/ExoPlayer#292]
The MP4 codec appears to not function properly when the phone is paired with a bluetooth speaker.  I tested on two different phones.  Note that *DASH video playback works fine on both devices with a paired speaker.*  The speaker I was using was a Big Jambox (BLE).

Nexus 5 @ OS 5.0.1 during video playback:

- Foregrounded application:  Audio and video lag once playback starts. 
- Backgrounded application:  Audio stream/playback works as expected.
- Re-foreground application:  Audio and video lag once playback starts.

Galaxy S4 @ OS 4.4.2 during video playback:

- Foregrounded application:  Playback never starts
- Backgrounded application:  Audio playback works
- Re-foreground application:  Everything works
- Seek to a random position:  Playback never starts

**Steps to reproduce**:

Prerequisite: Pair a bluetooth audio device with your phone.

1. Open the ExoPlayer Demo app.
2. Select Misc/Dizzy and let playback begin.
3. Observe audio and video playback stuttering.

**Comment by ojw28** [comment]
This should be fixed by using TYPE_MP4 instead of TYPE_OTHER, as per 7f58a0be8192c375565d7c77950200ee0a38c011.
