### ISSUE TITLE
ConcatenatingMediaSource ,a single seekbar

### ISSUE THREAD

**Issue by shoyu666** [google/ExoPlayer#2922]
dear author:
    we hava two or more  mp4 url,and we use ConcatenatingMediaSource, we want it play sequent，and it work as we want, except seekbar,  seekbar will reset when play next.
     my question is 
     a url mp4 file duration is 200,b url mp4 file duration is 300 and seekbar would be 500, not 200 change to 300,my english is poor ,Do I make myself clear。Look forward to your reply

**Comment by andrewlewis** [comment]
See #2122.

**Comment by shoyu666** [comment]
@andrewlewis 
    thanks 
   showMultiWindowTimeBar works fine
