### ISSUE TITLE
Combining ClippingMediaSource with LoopingMediaSource causes gap in loop

### ISSUE THREAD

**Issue by The41d3** [google/ExoPlayer#2923]
### Issue description
I want to loop part of mp3 (based on user selection) without having any silence gap in between loops. Right now in between loops there is a noticeable gap of silence. I can probably go around that using seeking, timer and listening to player events  for looping but that's not an elegant solution.

### Reproduction steps
Issue can be reproduced with any mp3 and on all devices I have tested it on. It also doesn't seem to depend on clipped length either.

```
Uri uri = Uri.parse(new File(track.getPath()).toString());
DataSource.Factory dataSourceFactory = new DefaultDataSourceFactory(context, Util.getUserAgent(context, ExoConst.APP_NAME));
ExtractorsFactory extractorsFactory = new DefaultExtractorsFactory();
ExtractorMediaSource baseMediaSource = new ExtractorMediaSource(uri, dataSourceFactory, extractorsFactory, null, null);
ClippingMediaSource clippingMediaSource = new ClippingMediaSource(baseMediaSource, startMS * 1000, endMS * 1000);
LoopingMediaSource loopingMediaSource = new LoopingMediaSource(clippingMediaSource);
	

```
### Link to test content
any mp3

### Version of ExoPlayer being used
2.4.1

### Device(s) and version(s) of Android being used

Samsung Galaxy S6 (7.0), Xiaomi Mi Note 4X (6.0), Nvidia Shield K1 (7.0), Huawei MediaPad T2 10.0 (5.1)

[bugreport.txt](https://github.com/google/ExoPlayer/files/1060360/bugreport.txt)

**Comment by tonihei** [comment]
I tried to reproduce your problem with the mp3 file in the demo app (Misc -> Google Play (MP3 Audio)) and the described MediaSource combination. I wasn't able to hear any noticeable amount of silence between loop iterations. 

Could you send me a link to the mp3 file you used? 
And how long is the gap we are talking about approximately?

**Comment by The41d3** [comment]
I managed to reproduce this using the bear.mp3 from the library.  So far I had no luck compiling demo app (grade issues) on AS3.0 but I will try to make a reproduction there as well. The gap seems to be around 50-100ms. 

Link with videos showing the issue: 
https://www.dropbox.com/sh/y5tmgoci85wb9de/AAC8uRpTPK62y6AfL4MZFULSa?dl=0

I'm thinking that there might be different configuration for ExoPlayer loading. Could it be that on default settings(I have not changed any default values) it is waiting for too much data before starting playback hence causing the delay?

**Comment by tonihei** [comment]
The above mentioned [commit](https://github.com/google/ExoPlayer/commit/56205893e5f392531baa9bc1d33a56858193a36e) solves your problem as long as you have media sources with audio-only tracks. 

You can also enforce the gapless playback for other media sources by passing `false` as a last parameter to [ClippingMediaSource](https://github.com/google/ExoPlayer/blob/dev-v2/library/core/src/main/java/com/google/android/exoplayer2/source/ClippingMediaSource.java#L72). Note, however, that this is only advisable if you can ensure that all tracks start with a key-frame at the specified startPosition of the clipping.
