### ISSUE TITLE
webvtt subtitles in HLS are not displayed when the PTS wraps around

### ISSUE THREAD

**Issue by bbagland** [google/ExoPlayer#2928]
### Issue description

Play a HLS stream where the PTS from the main video segment are wrapping around with webvtt subtitles.
[bugreport.1.txt.gz](https://github.com/google/ExoPlayer/files/1063692/bugreport.1.txt.gz)
The webvtt subtitles are never displayed.

### Reproduction steps
It is reproduced with the demo on the latest release 2.4.1.
it is not necessary, but it is easier if subtitles are set by default:

      DefaultTrackSelector.Parameters parameters = trackSelector.getParameters();
      parameters = parameters.withPreferredTextLanguage("heb");
      trackSelector.setParameters(parameters);

### Link to test content
stream to be sent by email

### Version of ExoPlayer being used
release 2.4.1 (commit 9f814850535afbe5a0123f7fa8fc2875ba2c5015)

### Device(s) and version(s) of Android being used
reproduced on Sony xperia z3 compact, as well as android tv devices.

**Comment by bbagland** [comment]
The subtitles are displayed if we call adjustTsTimestamp instead of adjustTsTimestamp instead of adjustSampleTimestamp in WebvttExtractor.java, ie:

long sampleTimeUs = firstCueTimeUs + timestampAdjuster.adjustTsTimestamp(Long.parseLong(mediaTimestampMatcher.group(1))) - vttTimestampUs;

**Comment by AquilesCanta** [comment]
A fix will be available in the next push. Thanks for reporting and your patience!

**Comment by ojw28** [comment]
This is fixed in `dev-v2`, and will be in `r2.5.3`, which will be released some time this week.

**Comment by bbagland** [comment]
Thanks.
I no longer have access to the environnent to replicate, but I will see if I can check nonetheless.
