### ISSUE TITLE
align:left in webvtt subtitles is not correct for RTL script

### ISSUE THREAD

**Issue by bbagland** [google/ExoPlayer#2929]
### Issue description

Play a HLS stream with webvtt subtitles in a RTL script and align:left or align:right in the positioning

align:left will be aligned on the right side instead of being aligned on the left side.

see https://w3c.github.io/webvtt/#webvtt-cue-text-alignment
align:{left,right} should be absolute positioning, where align:{start,end} should follow the script direction

actual behavior : ![left_align_actual](https://user-images.githubusercontent.com/15088154/26971509-c40a70aa-4d0d-11e7-81c9-afd579d0dbeb.png)
expected behavior: ![left_align_expected](https://user-images.githubusercontent.com/15088154/26971515-c7c92a24-4d0d-11e7-8c70-5105a3635abd.png)

### Reproduction steps
It is reproduced with the demo on the latest release 2.4.1.

### Link to test content
stream to be sent by email

### Version of ExoPlayer being used
release 2.4.1 (commit 9f814850535afbe5a0123f7fa8fc2875ba2c5015)

### Device(s) and version(s) of Android being used
reproduced on Sony xperia z3 compact, as well as android tv devices.

[bugreport.1.txt.gz](https://github.com/google/ExoPlayer/files/1063702/bugreport.1.txt.gz)

**Comment by bbagland** [comment]
correct behavior can be had by modifying WebvttCueParser.java:

private static Alignment parseTextAlignment(String s) {
    switch (s) {
      case "start":
	return Alignment.ALIGN_NORMAL;
      case "left":
        return Alignment.valueOf("ALIGN_LEFT");

instead of:
      case "left":
      case "start":
	return Alignment.ALIGN_NORMAL;

however ALIGN_LEFT/ALIGN_RIGHT is hidden by an annotation

**Comment by AquilesCanta** [comment]
Sorry for leaving this unattended.

Have the test streams been sent? If not, please send them with the subject "Issue #2929". Thanks.

**Comment by AquilesCanta** [comment]
The streams are no longer available, can you share them with us again please?

**Comment by AquilesCanta** [comment]
Closing due to lack of required information. Please share again and we will reopen the issue.
