### ISSUE TITLE
How to extract multiple EXT-X-PROGRAM-DATE-TIME?

### ISSUE THREAD

**Issue by b95505017** [google/ExoPlayer#2930]
For example this is my HLS vod:

```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-ALLOW-CACHE:NO
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-TARGETDURATION:10
#EXT-X-PROGRAM-DATE-TIME:2017-06-09T04:59:01.797Z

#EXTINF:10,
1496984341record00000.ts
#EXTINF:10,
1496984341record00001.ts
#EXTINF:10,
1496984341record00002.ts
#EXT-X-DISCONTINUITY
#EXT-X-PROGRAM-DATE-TIME:2017-06-09T05:00:18.360Z
#EXTINF:10,
1496984341record00003.ts
#EXTINF:10,
1496984341record00004.ts
#EXTINF:10,
1496984341record00005.ts
#EXTINF:10,
1496984341record00006.ts
#EXTINF:10,
1496984341record00007.ts
#EXTINF:4,
1496984341record00008.ts
#EXT-X-DISCONTINUITY
#EXT-X-PROGRAM-DATE-TIME:2017-06-09T05:01:33.889Z
#EXTINF:10,
1496984341record00009.ts
#EXTINF:10,
1496984341record00010.ts
#EXTINF:8,
1496984341record00011.ts
#EXT-X-ENDLIST
```

Is there any callback or pulling API I could get the absolute time position?
In HLS.js, here is a callback: https://github.com/video-dev/hls.js/issues/800

**Comment by AquilesCanta** [comment]
Could you provide a bit more context to understand what the purpose is?

Note that the samples will be in the timebase of the PROGRAM-DATE-TIME tags. Which means that if you get the playback position, it will map with the program-date-time tags in the media playlist.

Also, from the last release onwards it is possible to get all tags from the manifest, but I don't think it will provide useful information.

**Comment by b95505017** [comment]
In my sample, there are three absolute timestamps.
It would be better if there is a callback when absolute time is discontinued, also I want to pull the current absolute timestamp at any time.

**Comment by AquilesCanta** [comment]
> also I want to pull the current absolute timestamp at any time.

I think `getCurrentPostiion` gives you exactly this. Regarding getting a callback for a specific playback position, see #2090. Hope this answers your question.

**Comment by b95505017** [comment]
```java
      } else if (line.startsWith(TAG_PROGRAM_DATE_TIME)) {
        if (playlistStartTimeUs == 0) {
          long programDatetimeUs =
              C.msToUs(Util.parseXsDateTime(line.substring(line.indexOf(':') + 1)));
          playlistStartTimeUs = programDatetimeUs - segmentStartTimeUs;
        }
```
I think it could only handle the first timestamp `#EXT-X-PROGRAM-DATE-TIME:2017-06-09T04:59:01.797Z`, other two timestamps will be ignored.

**Comment by AquilesCanta** [comment]
Yes, there was some discussion about this and it was eventually decided it should be done this way. It shouldn't affect your visibility of timestamps, however. `getCurrentPosition` is derived from sample timestamps, which are the ground truth of the stream.

**Comment by b95505017** [comment]
>Note that the samples will be in the timebase of the PROGRAM-DATE-TIME tags. Which means that if you get the playback position, it will map with the program-date-time tags in the media playlist.

@AquilesCanta I log `getCurrentPosition` and it always started from `0`, which is not based on `EXT-X-PROGRAM-DATE-TIME:2017-06-09T04:59:01.797Z`.

**Comment by AquilesCanta** [comment]
Could you provide a stream that reproduces this? If you don't want to make it public you can send it to dev.exoplayer@gmail.com. Following the issue template makes this process much more agile.

**Comment by b95505017** [comment]
@AquilesCanta The content of the m3u8 is in the first post. And the link is below:
https://vod.straas.net/companyId/100592/1496984341rl74rdlvsh/playlist.m3u8
Is that means `getCurrentPosition` should start from `1496984341797` which maps to `2017-06-09T04:59:01.797Z`?

Also I still don't understand how to get these three timestamps based on current `dev-v2` branch of Exoplayer:
```
#EXT-X-PROGRAM-DATE-TIME:2017-06-09T04:59:01.797Z
...
#EXT-X-DISCONTINUITY
#EXT-X-PROGRAM-DATE-TIME:2017-06-09T05:00:18.360Z
...
#EXT-X-DISCONTINUITY
#EXT-X-PROGRAM-DATE-TIME:2017-06-09T05:01:33.889Z
```

**Comment by b95505017** [comment]
@AquilesCanta @ojw28 Any idea why `getCurrentPosition` of the sample I provided above always started from `0` instead of `1496984341797`?

**Comment by AquilesCanta** [comment]
Yes, sorry I misguided you. As documented in ExoPlayer `getCurrentPosition()`:
`Returns the playback position in the current window, in milliseconds.`
The start of the window is always 0, AFAIK.
To get what you need, you'll have to add to that value, the current window's `positionInFirstPeriodUs`.

I am going to mark this as an enhancement to populate other relevant information of the window in HLS.

**Comment by AquilesCanta** [comment]
Keep in mind the units in which each method returns the values. They are either included in the method's name or documented in the javadoc.

**Comment by jasonchuang** [comment]
Hi @AquilesCanta , the commit [fill missing window information...](https://github.com/google/ExoPlayer/commit/e344e9cbb756a384c437850028c3fb09e145a386
) doesn't modify `HlsPlaylistParser` and seems only support  to retrieve **single** `EXT-X-PROGRAM-DATE-TIME` from timeline for  the player. Any ideas or plans to extend the support for retrieving the **multiple** program date time tag? Thanks

**Comment by AquilesCanta** [comment]
@jasonchuang Can you clarify precisely what the usecase is? Most likely, the information you need is already available.

**Comment by jasonchuang** [comment]
@AquilesCanta, thanks for your response, for the example m3u8 from [the begging of this post](https://github.com/google/ExoPlayer/issues/2930#issue-234786541), it contains `three` different PROGRAM-DATE-TIME tags, and what I want to do here is to get the current `epoch unix timestamp` according to different current position, e.g., position 1 ~ 30 started from **1496984341**(2017-06-09T04:59:01.797Z), position 31 ~ 84 started from **1496984418**(2017-06-09T05:00:18.360Z) and position 85 ~ 112 started from  **1496984493**(2017-06-09T05:01:33.889Z). And the patch [fill missing window information](https://github.com/google/ExoPlayer/commit/e344e9cbb756a384c437850028c3fb09e145a386
) seems works for returning the `first` program date time via `windowStartTimeMs`, but not available for all program date time tags. Do you have any suggestions on this? Thanks.

**Comment by jasonchuang** [comment]
@AquilesCanta, just found [Expose all tags](https://github.com/google/ExoPlayer/commit/26728142eea52f16f8ce98734e915f0b92f54ca4) commit in `branch dev-v2-r2.5.0`, and seems works for my usecase 👍!!  But will it be better to notify the current `epoch unix timestamp base` has been changed from **EXT-X-DISCONTINUITY and EXT-X-PROGRAM-DATE-TIME** tags  via `onTimelineChanged` or `onPositionDiscontinuity` listener instead of parsing date time tags outside player?
