### ISSUE TITLE
Getting Java.io.IOException: Error while finalizing ciphe

### ISSUE THREAD

**Issue by suresh-s** [google/ExoPlayer#2931]
we are using Exoplayer 2.2.0 in Android App. 
Video is playing properly in normal scenario from start to end.  when we seek two times or more, we are getting following exception 

D/BluetoothManagerService( 1569): Message: 401
E/ExoPlayerImplInternal( 4760): Source error.
E/ExoPlayerImplInternal( 4760): java.io.IOException: Error while finalizing cipher
E/ExoPlayerImplInternal( 4760): at javax.crypto.CipherInputStream.fillBuffer(CipherInputStream.java:104)
E/ExoPlayerImplInternal( 4760): at javax.crypto.CipherInputStream.read(CipherInputStream.java:155)
E/ExoPlayerImplInternal( 4760): at com.google.android.exoplayer2.source.hls.Aes128DataSource.read(Aes128DataSource.java:96)
E/ExoPlayerImplInternal( 4760): at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFromDataSource(DefaultExtractorInput.java:247)
E/ExoPlayerImplInternal( 4760): at com.google.android.exoplayer2.extractor.DefaultExtractorInput.read(DefaultExtractorInput.java:56)
E/ExoPlayerImplInternal( 4760): at com.google.android.exoplayer2.extractor.ts.TsExtractor.read(TsExtractor.java:180)
E/ExoPlayerImplInternal( 4760): at com.google.android.exoplayer2.source.hls.HlsMediaChunk.loadMedia(HlsMediaChunk.java:257)
E/ExoPlayerImplInternal( 4760): at com.google.android.exoplayer2.source.hls.HlsMediaChunk.load(HlsMediaChunk.java:194)
E/ExoPlayerImplInternal( 4760): at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
E/ExoPlayerImplInternal( 4760): at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
E/ExoPlayerImplInternal( 4760): at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/ExoPlayerImplInternal( 4760): at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/ExoPlayerImplInternal( 4760): at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/ExoPlayerImplInternal( 4760): at java.lang.Thread.run(Thread.java:818)
E/ExoPlayerImplInternal( 4760): Caused by: javax.crypto.BadPaddingException: EVP_CipherFinal_ex
E/ExoPlayerImplInternal( 4760): at com.android.org.conscrypt.NativeCrypto.EVP_CipherFinal_ex(Native Method)

**M3U8 Content**

#EXTM3U
#EXT-X-VERSION:4
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-TARGETDURATION:141
#EXT-X-KEY:METHOD=AES-128,URI="xxyyzzdrm"
#EXTINF:141.040000,
#EXT-X-BYTERANGE:11619904@0
https://s3- xxxxx.com/stage/abc/xyz_512k_00000000.ts
#EXT-X-ENDLIST

Could you help us to figure out the issue?

**Comment by ojw28** [comment]
This issue is being closed because it does not adhere to our issue template, and/or because it omits information requested in the issue template that is required for us to investigate the problem efficiently. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).
 
If you’re able to provide complete information as requested in the issue template, please do so below and we’ll re-open the issue. Thanks!
