### ISSUE TITLE
About VideoListener

### ISSUE THREAD

**Issue by Caij** [google/ExoPlayer#2933]
When i use SimpleExoPlayerView， I found  player.setVideoListener(componentListener)， Then I can not set  VideoListener.  Can you design player.addVideoListener()?

Thanks

**Comment by ojw28** [comment]
Please try using `setVideoDebugListener`. If that's not sufficient for your needs, please explain exactly what your use case is for needing this. Please also see https://github.com/google/ExoPlayer/issues/2800, which is similar to this one.

**Comment by Caij** [comment]
OK
