### ISSUE TITLE
Player Random playlist player

### ISSUE THREAD

**Issue by HayDar-Android** [google/ExoPlayer#2934]
Music player  playlist ,Order play use `ConcatenatingMediaSource` class ,
What is random play?

How to achieve？

**Comment by andrewlewis** [comment]
Can you just shuffle the array of MediaSources before passing it to ConcatenatingMediaSource's constructor? Or do you need something different?

**Comment by HayDar-Android** [comment]
@andrewlewis 
Is random in the playing process.

**Comment by HayDar-Android** [comment]
@andrewlewis 
After playing the next random one, rather than automatically the next one。

**Comment by ojw28** [comment]
It's unclear what's being asked here. Closing due to lack of clarity.
