### ISSUE TITLE
getWidevine

### ISSUE THREAD

**Issue by steff-maya** [google/ExoPlayer#2937]
i need to  get de widevine  for make this  request licence ,my question is where it's de widevine  on the exoplayer #

https://widevine.entitlement.theplatform.com/wv/web/ModularDrm/getWidevineLicense?schema=1.0
	&form=xml
    &_releasePid=5Dv1CGzf1FWZ
    &_widevineChallenge=%01%D9dz9

**Comment by ojw28** [comment]
The demo app includes Widevine protected samples, and can be used as a starting point to see what you need to do.
