### ISSUE TITLE
IMA Support

### ISSUE THREAD

**Issue by imarenco** [google/ExoPlayer#2938]
Hi, I'm needing IMA extension support in stable reléase, could you please confirm me when will be available?.

thanks!.

Related:
#2617

**Comment by ojw28** [comment]
We do not have an ETA at this moment, and still need to fix some behavior (e.g. how seeking interacts with ads in the timeline) before we can release to stable. Please follow #2617.

**Comment by ManojJangra** [comment]
Please guide way of using  IMA extension in the ExoPlayer in our app.

**Comment by ojw28** [comment]
It's not done yet, which is why #2617 is still open. Updates will appear there when available.
