### ISSUE TITLE
Subtitles not synced after video rewind.

### ISSUE THREAD

**Issue by hare989** [google/ExoPlayer#2944]
After seek HLS video to previous time external WebVTT subtitles freezes at current time and stays displayed until video stream get to that time again and after that subtitles continue to show regularly. Subtitles work as expected after seeking forward. I'm using ExoPlayer 1.5.4.

**Comment by AquilesCanta** [comment]
It should be very easy for you to test your stream in the latest versions of v1 and v2, adding your sample to the demo app. Many improvements and bugfixes have landed for webvtt in HLS, particularly for v2. Please file a new issue without ignoring the issue template if you see this reproducing in newer versions.
