### ISSUE TITLE
How can I get the number (or index) of a  DASH segment ?

### ISSUE THREAD

**Issue by qlthd** [google/ExoPlayer#2948]
Hi ! I figured out that a lot of informations for each segment can be obtained thanks to the  `AdaptiveMediaSourceEventListener` interface like its size, its arrival time, delivery time using variables like mediaEndTimeMs provided in methods `onLoadCompleted` . But now I would like to get the the number (or index ?) assigned to each segment, i'm pretty sure it can be extracted from somewhere in the code. These values could be really useful for Chunk replacement. Have you got any ideas where I could find such values ? I've looked  in classes implementing the `DashSegmentIndex`  interface but didn't really find how to get what I wanted.

**Comment by ojw28** [comment]
This is already tracked by https://github.com/google/ExoPlayer/issues/2909, you don't need to file a separate issue.
