### ISSUE TITLE
Video's small window and full screen switch to the carton phenomenon

### ISSUE THREAD

**Issue by panhuiAipami** [google/ExoPlayer#2949]
### Issue description
Full screen and small screen switch, expect seamless connection, but each switch will have about two seconds

### Reproduction steps
On the playback page, SimpleExoPlayerView specifies a small window with a wide width, and then a full screen.There's a caton phenomenon in small screen to full screen or full screen
--------------------------------------------------------------
{if (mPlayerView != null) {
            // 切换为小屏
            if (!big) {
                full_screen.setVisibility(View.GONE);
                full_screen.removeAllViews();
                frameLayout.removeAllViews();
                ViewGroup last = (ViewGroup) mPlayerView.getParent();//找到videoitemview的父类，然后remove
                if (last != null) {
//                    last.removeAllViews();
                    last.removeView(mPlayerView);
                }
                frameLayout.addView(mPlayerView);
                int mShowFlags =
                        View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN
                                | View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION
                                | View.SYSTEM_UI_FLAG_LAYOUT_STABLE;
                full_screen.setSystemUiVisibility(mShowFlags);
            } else {
                //切换为全屏
                ViewGroup viewGroup = (ViewGroup) mPlayerView.getParent();
                if (viewGroup == null)
                    return;
                viewGroup.removeAllViews();
                full_screen.addView(mPlayerView);
                full_screen.setVisibility(View.VISIBLE);
                int mHideFlags =
                        View.SYSTEM_UI_FLAG_LOW_PROFILE
                                | View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN
                                | View.SYSTEM_UI_FLAG_FULLSCREEN
                                | View.SYSTEM_UI_FLAG_IMMERSIVE
                                | View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION
                                | View.SYSTEM_UI_FLAG_HIDE_NAVIGATION;
                full_screen.setSystemUiVisibility(mHideFlags);
            }
        } else {
            full_screen.setVisibility(View.GONE);
        }
---------------------------------------------------------------------
[log.TXT](https://github.com/google/ExoPlayer/files/1073444/log.TXT)

### Link to test content
http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4

### Version of ExoPlayer being used
exoplayer: r2.4.1

### Device(s) and version(s) of Android being used
Skyworth Q2 TV box Android5.1.1

### A full bug report captured from the device
06-14 11:25:56.535 5136-5136/? E/cutils-trace: Error opening trace file: Permission denied (13)
06-14 11:25:56.985 5115-5115/net.dxauto.tvgo E/STATE_IDLE: ----------停止---------
06-14 11:25:56.988 5115-5115/net.dxauto.tvgo E/Video: URI = http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4
06-14 11:25:56.991 5115-5115/net.dxauto.tvgo E/onPositionDiscontinuity: --------onPositionDiscontinuity-------
06-14 11:25:57.019 5115-5115/net.dxauto.tvgo E/STATE_BUFFERING: ----------缓冲---------
06-14 11:25:57.020 5115-5115/net.dxauto.tvgo E/onTimelineChanged: --------onTimelineChanged-------com.google.android.exoplayer2.source.LoopingMediaSource$LoopingTimeline@1f7f56a0
06-14 11:25:57.020 5115-5115/net.dxauto.tvgo E/onLoadingChanged: ---------------true
06-14 11:25:57.764 5115-5115/net.dxauto.tvgo E/onTimelineChanged: --------onTimelineChanged-------com.google.android.exoplayer2.source.LoopingMediaSource$LoopingTimeline@16f96301
06-14 11:25:57.914 2805-19717/? E/OMXNodeInstance: setParameter(428:amlogic.avc.decoder.awesome, OMX.google.android.index.storeMetaDataInBuffers(0x7f000002): Output:1 en=1 GB=0) ERROR: BadPortIndex(0x8000101b)
06-14 11:25:57.914 5115-5168/net.dxauto.tvgo E/ACodec: [OMX.amlogic.avc.decoder.awesome] storeMetaDataInBuffers failed w/ err -2147483648
06-14 11:25:57.930 2805-3132/? E/OmxVideoDecoder: set output error, new BufferCountActual = 8
06-14 11:25:57.930 2805-3132/? E/OMXNodeInstance: setParameter(428:amlogic.avc.decoder.awesome, ParamPortDefinition(0x2000001)) ERROR: UnsupportedSetting(0x80001019)
06-14 11:25:57.930 2805-8638/? E/OmxVideoDecoder: set output error, new BufferCountActual = 7
06-14 11:25:57.930 2805-8638/? E/OMXNodeInstance: setParameter(428:amlogic.avc.decoder.awesome, ParamPortDefinition(0x2000001)) ERROR: UnsupportedSetting(0x80001019)
06-14 11:25:57.997 5115-5171/net.dxauto.tvgo E/omx_video: amvenc_avc open failed!set default instance number as 1,ret=-1,Permission denied(13)
06-14 11:25:57.997 5115-5171/net.dxauto.tvgo E/OMXMaster: A component of name 'OMX.google.h264.decoder' already exists, ignoring this one.
06-14 11:25:57.997 5115-5171/net.dxauto.tvgo E/OMXMaster: A component of name 'OMX.google.alac.decoder' already exists, ignoring this one.
06-14 11:25:58.806 5115-5115/net.dxauto.tvgo E/STATE_READY: ----------播放---------
06-14 11:25:58.829 3082-3101/system_process E/ActivityManager: com.skyworthdigital.sky2dlauncher is in user secure list: android/system/com.android/com.mipt/com.skyworth/com.skyworthdigital/com.skydigital/com.sky/com.ktcp/cn.beevideo/com.iflytek/com.nanosic/com.droidlogic.PPPoE/com.hpplay.allcast/com.explorer/com.slanissue.tv.erge/eu.chainfire.perfmon/com.gamecast/com.antutu/com.jd.smart.tv
06-14 11:26:00.013 3082-3460/system_process E/ActivityManager: com.skyworthdigital.sky2dlauncher is in user secure list: android/system/com.android/com.mipt/com.skyworth/com.skyworthdigital/com.skydigital/com.sky/com.ktcp/cn.beevideo/com.iflytek/com.nanosic/com.droidlogic.PPPoE/com.hpplay.allcast/com.explorer/com.slanissue.tv.erge/eu.chainfire.perfmon/com.gamecast/com.antutu/com.jd.smart.tv
06-14 11:26:00.775 2805-3201/? E/OMXNodeInstance: setParameter(429:amlogic.avc.decoder.awesome, OMX.google.android.index.storeMetaDataInBuffers(0x7f000002): Output:1 en=1 GB=0) ERROR: BadPortIndex(0x8000101b)
06-14 11:26:00.775 5115-5207/net.dxauto.tvgo E/ACodec: [OMX.amlogic.avc.decoder.awesome] storeMetaDataInBuffers failed w/ err -2147483648
06-14 11:26:00.786 2805-8638/? E/OmxVideoDecoder: set output error, new BufferCountActual = 8
06-14 11:26:00.786 2805-8638/? E/OMXNodeInstance: setParameter(429:amlogic.avc.decoder.awesome, ParamPortDefinition(0x2000001)) ERROR: UnsupportedSetting(0x80001019)
06-14 11:26:00.786 2805-29402/? E/OmxVideoDecoder: set output error, new BufferCountActual = 7
06-14 11:26:00.786 2805-29402/? E/OMXNodeInstance: setParameter(429:amlogic.avc.decoder.awesome, ParamPortDefinition(0x2000001)) ERROR: UnsupportedSetting(0x80001019)
06-14 11:26:05.776 2805-2805/? E/OMXNodeInstance: setParameter(42a:amlogic.avc.decoder.awesome, OMX.google.android.index.storeMetaDataInBuffers(0x7f000002): Output:1 en=1 GB=0) ERROR: BadPortIndex(0x8000101b)
06-14 11:26:05.776 5115-5235/net.dxauto.tvgo E/ACodec: [OMX.amlogic.avc.decoder.awesome] storeMetaDataInBuffers failed w/ err -2147483648
06-14 11:26:05.791 2805-3201/? E/OmxVideoDecoder: set output error, new BufferCountActual = 8
06-14 11:26:05.791 2805-3201/? E/OMXNodeInstance: setParameter(42a:amlogic.avc.decoder.awesome, ParamPortDefinition(0x2000001)) ERROR: UnsupportedSetting(0x80001019)
06-14 11:26:05.791 2805-14543/? E/OmxVideoDecoder: set output error, new BufferCountActual = 7
06-14 11:26:05.791 2805-14543/? E/OMXNodeInstance: setParameter(42a:amlogic.avc.decoder.awesome, ParamPortDefinition(0x2000001)) ERROR: UnsupportedSetting(0x80001019)
06-14 11:26:05.806 5115-5115/net.dxauto.tvgo E/onLoadingChanged: ---------------false

**Comment by ojw28** [comment]
I'm pretty sure this question is already discussed/tracked by https://github.com/google/ExoPlayer/issues/1845 and https://github.com/google/ExoPlayer/issues/677.
