### ISSUE TITLE
Players how to set up a proxy server?

### ISSUE THREAD

**Issue by LittleSunZ** [google/ExoPlayer#2954]
I want to set a socket or HTTP proxy,What do I do?
thanks!

**Comment by andrewlewis** [comment]
ExoPlayer will generally request whatever URI you provide, and my understanding is that the system will use a proxy server if one is configured in Settings for the relevant network connection. If you're running a local proxy server you'd just pass a URI referring to localhost. If that doesn't answer your question please clarify what you're trying to do.

**Comment by ojw28** [comment]
This sounds outside the scope of this issue tracker.
