### ISSUE TITLE
Cannot play hls link with Exoplayer

### ISSUE THREAD

**Issue by mdtuyen** [google/ExoPlayer#2955]
I'm woking with television application.

The first I will make an request to get m3u8 link from server. Second I use Exoplayer to play that link.

But content of that link is not content of chanel.

I use Fiddler to check request and see that Exoplayer send an GET request with the link I detect and server redirect to another link.

I check it with Vitamio and see that Vitamio don't send any Request and video play GOOD.

I don't understand here. Please help me check it with Exoplayer. Why it send GET request.

**Comment by AquilesCanta** [comment]
Could you please follow the issue template? If you could replace "that link" and "another link" with actual links, that would help me understand what the problem is.

> Why it send GET request

The GET requests are necessary to fetch playlists and chunks. Bue maybe I am not understanding correctly.

**Comment by mdtuyen** [comment]
Hi @AquilesCanta 

In my case:

- The first get link to play: Send request A -> Get response is B (link to play)

Vitamio: setVideoUrl(B) => Play OK

Exoplayer: setVideoUrl(B) => WORK but content is not B link.

Check fiddler: Exoplayer send GET request with link is B and return link C (this is content that Exoplayer present- but I need play link B)

With Vitamio I don't see any request when play link B and Content is correct.

**Comment by AquilesCanta** [comment]
I am inclined to think that the server is redirecting ExoPlayer but not Vitamio, or the other way around. Try to emulate Vitamio's http request's header with ExoPlayer. It could be the user agent, or other header. Unfortunately I cannot help you anymore, as this is most likely not an ExoPlayer bug.

**Comment by mdtuyen** [comment]
Hi, As the previous issue that the reason is UserAgent, I change userAgent to okhttp/2.5.0 as Vitamio the video worked.

Now When play this link: http://103.9.76.165:1935/vod/_definst_/mp4:show/tuyetdinhgiacquan15/tap1_360.mp4/playlist.m3u8?vntv_endtime=1498919340&vntv_starttime=0&vntv_hash=QyNYm5vPs6DSXFKqlnrd4ABkl6UIGkXdjIf57vzbpq8=

That link play fine on Vitamio, but not work with Exoplayer.
I change UserAgent but It not work.

I thinks there are problem with authen. Please help me.
