### ISSUE TITLE
Question on the meaning of drm_license_url field

### ISSUE THREAD

**Issue by Gian84** [google/ExoPlayer#2958]
Hi,
I have just a question / doubt about drm_license_url in media.exolist.json.
I thought it was the override of licenseUrl. 

So, _byte[] executeKeyRequest(UUID uuid, KeyRequest request)_ method in class _HttpMediaDrmCallback.java_ in my opinion should be edited as snippet below:

_\-    String url = request.getDefaultUrl();
\-    if (TextUtils.isEmpty(url)) {
\-      url = defaultUrl;
\-    }
\+      String url = defaultUrl;
\+      if (TextUtils.isEmpty(url)) {
\+          url = request.getDefaultUrl();
\+      }_

Could you explain me the real meaning of it?

Thank you in advance

**Comment by ojw28** [comment]
The code is correct how it is currently. drm_license_url is the URL to use if there isn't one specified in the `KeyRequest`.
