### ISSUE TITLE
[Q] Does ExoPlayer use the Android native libraries?

### ISSUE THREAD

**Issue by blundell** [google/ExoPlayer#296]
Trying to get my head around how ExoPlayer works.

The android.media.MediaPlayer uses StagefrightPlayer which is the AwesomePlayer under the hood (and the NuPlayer on some platform versions..is that right?)

So my question is does ExoPlayer use these native libraries as well? or have I got it all wrong :smiley_cat:

**Comment by ojw28** [comment]
The developer guide should help answer this: http://developer.android.com/guide/topics/media/exoplayer.html

**Comment by blundell** [comment]
I've read that page it doesn't mention about the underlying C libraries that are being used. Could you point to where in the docs you are referring?

**Comment by ojw28** [comment]
"ExoPlayer is a media player built on top of the MediaExtractor and MediaCodec APIs released in Android 4.1". So it calls through to the native implementations of those APIs (not AwesomePlayer or NuPlayer).

**Comment by blundell** [comment]
ok so I'll follow the source code of those to see what it does :+1:
