### ISSUE TITLE
Widevine rental license issue - videos on Android 4.x devices play past expiration time

### ISSUE THREAD

**Issue by uthonangi** [google/ExoPlayer#2962]
We are implementing offline playback of videos using Widevine. When setting the store license to be 'true' (downloadable), license type as 'rental' and the play duration to a specific value, on Android 4.x devices, Widevine allows playback of videos past the rental time. On Android 5.x, 6.x and 7.x devices, assets cannot be played once the time expires. 

Steps to reproduce:
1. Acquire a license from the client app with a rental period to expire equal to the video duration (1 hour movie).
2. After downloading the video, put the device in airplane mode. 
3. Start playback, and let the video play uninterrupted until completion.
4. After the video completes, try to replay it.

Expected:
As with other Android versions (5, 6, and 7), a second play or play after the expiration time is not allowed, because the license prevents it.
Actual:
On Android 4.x, repeated plays are possible.

Also, if the system time on 4.x device is changed; License expiration is not honored. On Android 5, 6 or 7 devices, video playback is prevented if system time is changed.

FYI: We posted on WV Googleforums as well. But wanted to open a ticket here to see if anyone on the ExoPlayer side has seen this issue and if they can confirm? We are not expecting a fix but just a confirmation so that we can pull support for offline playback with rental licenses on 4.x devices.

**Comment by ojw28** [comment]
Please can you add a link to where this is reported to Widevine? This isn't an ExoPlayer issue, and the Widevine team are best placed to confirm the issue. We'll likely close this one (up to @wvpaf). It's good to have the cross-reference though.

**Comment by forbesjo** [comment]
This issue has been posted to the WV group https://groups.google.com/forum/?nomobile=true#!topic/cwip-discuss/PNe9sTPuFEk

**Comment by wvpaf** [comment]
adding @pgrov

**Comment by pgrov** [comment]
Will reach out and request additional log data via the provided WV Group post.

**Comment by ojw28** [comment]
Closing this as further discussion should be on the WV group post. Thanks.
