### ISSUE TITLE
Provide use case specific demo apps (in Kotlin)

### ISSUE THREAD

**Issue by kernja** [google/ExoPlayer#2965]
1) There's no comments besides auto-generated boilerplate comments,
2) It's overkill and overly complicated, and
3) Having a simple project that plays a local, bundled, hardcoded MP3 would be fantastic.

If you want people to be able to contribute and use your project, having it easily accessible would be a great start.

**Comment by ojw28** [comment]
> There's no comments besides auto-generated boilerplate comments,

Which specific parts would you like to see comments attached to? Just commenting everything doesn't always make things clearer in practice.

> It's overkill and overly complicated

I think what you really mean is that it's over-complicated for your specific use case. There are other issues on this issue tracker asking for more features in the demo app, heh. It should be pretty easy for you to delete from the demo app until you get down to your use case (and conversely, going in the opposite direction isn't as easy).

> Having a simple project that plays a local, bundled, hardcoded MP3 would be fantastic.

We're thinking about providing simple, use case specific demo apps. It's not going to happen soon though.

**Comment by ojw28** [comment]
Rephrased the title of this issue to track what I think we really need to do here.

**Comment by ojw28** [comment]
These should probably be written in Kotlin, given we're now Kotlin first.

**Comment by tonihei** [comment]
Superseded by #5854.
