### ISSUE TITLE
Adaptive stream mode in demo app

### ISSUE THREAD

**Issue by nguyenhoanglam** [google/ExoPlayer#2972]
I've downloaded the exoplayer demo app. In the demo app, there're Default mode , multiple check list mode and Enable random adaptation mode. I do not know which mode is use for adaptive stream (auto change resolution base on bandwith)? 

Please help me!

**Comment by tonihei** [comment]
The "Default" mode automatically adapts to streams based on the current bandwidth estimate. When you look at the debug line just above the video, you can see the current resolution (for example, r:640x320). Depending on your network this may change while playing the video.

**Comment by nguyenhoanglam** [comment]
@tonihei Thanks a lot! 
I've another two question!

- In my HSL stream, there're 4 tracks: 240p, 360p,720p and a source track. I only want to make an adaptive stream among 240p, 360p and 720p tracks(except source track). How can I do this?

- When the player change track automatically, how can I know which track (track index) is currently playing?

It would be great if you can help me. Thanks in advance!

**Comment by AquilesCanta** [comment]
> In my HSL stream, there're 4 tracks: 240p, 360p,720p and a source track. 

Could you clarify what source track is? 

> When the player change track automatically, how can I know which track (track index) is currently playing?

`SimpleExoPlayer's` `getVideoFormat` and `getAudioFormat` will provide quite a bit of information about the video and audio currently playing.

**Comment by nguyenhoanglam** [comment]
@AquilesCanta Here's my m3u8 file description:

```java
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:BANDWIDTH=2196608,NAME="source",CODECS="avc1.66.30",RESOLUTION=1280x720
chunklist_w1270825050_b2196608_t64c291cmNl.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=596608,NAME="160p",CODECS="avc1.66.30",RESOLUTION=1280x160
chunklist_w1270825050_b596608_t64MTYwcA==.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=796608,NAME="240p",CODECS="avc1.66.30",RESOLUTION=1280x240
chunklist_w1270825050_b796608_t64MjQwcA==.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1046608,NAME="360p",CODECS="avc1.66.30",RESOLUTION=1280x360
chunklist_w1270825050_b1046608_t64MzYwcA==.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1196608,NAME="480p",CODECS="avc1.66.30",RESOLUTION=1280x480
chunklist_w1270825050_b1196608_t64NDgwcA==.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1496608,NAME="720p",CODECS="avc1.66.30",RESOLUTION=1280x720
chunklist_w1270825050_b1496608_t64NzIwcA==.m3u8
```

As you can see, source track is a track with highest resolution (original track). How can I exclude source track from adaptive tracks?

**Comment by AquilesCanta** [comment]
I see. This is not a term I had heard before.

You could take advantage of the default track selector. Configure the DefaultTrackSelector you are using to use the max video size or bitrate you'd like. Like so:

```
DefaultTrackSelector trackSelector = new DefaultTrackSelector();
// Using the video size.
trackSelector.setParameters(trackSelector.getParameters().withMaxVideoSize(...));
// Using the video bitrate.
trackSelector.setParameters(trackSelector.getParameters().withMaxVideoBitrate(...));
// Assuming you are using SimpleExoPlayer.
SimpleExoPlayer player = ExoPlayerFactory.newSimpleInstance(/* renderersFactory */, trackSelector);
```

I guess in your case the bitrate alternative is better. If none of the previous work, you could also subclass DefaultTrackSelector and write your own selectVideoTrack, overriding the existing one. For example, if you know your _source track_ is listed first, you could filter out the video track with id 0. I suggest you play around with the default track selector.

A few notes: 

- The resolution looks strange, do all videos have the same width but change height?
- Do the streams not contain audio? If they do, you should probably add the corresponding codecs entry.
- The NAME attribute is not defined in the spec, so you count on a different property in the format to identify the source track.

Hope this helps.

**Comment by ojw28** [comment]
As an additional point: The best way to exclude the source track is to not include it in the master playlist to start with. You shouldn't push this kind of functionality to the client, since in doing so you're relying on *all* client players supporting this functionality, where-as you could just solve the problem in a single place on the serving side by not including it to start with.
