### ISSUE TITLE
Problem of gradle adding ExoPlayer as a module

### ISSUE THREAD

**Issue by qlthd** [google/ExoPlayer#2974]
Hi ! I'd like to modify ExoPlayer's code and for this i have to add it as a module.
I added a folder `'libraries'` and put the ExoPlayer folder inside. 

![lib](https://user-images.githubusercontent.com/26259902/27328419-08f51180-55aa-11e7-927f-5f94ffdfdf82.png)

Then i added `include ':libraries:ExoPlayer'` in the project `settings.gradle`. Finally in the Project Structure settings i added :libraries:ExoPlayer' as a dependency to my project, but after this, i keep getting this error : 
`Error:Project :app declares a dependency from configuration 'compile' to configuration 'default' which is not declared in the descriptor for project :libraries:ExoPlayer.`
Thank you for your future help.

**Comment by nerd-sj** [comment]
I get the same error. Any fixes?

**Comment by ojw28** [comment]
We'll be making this much easier from the next release (and easier for the `dev-v2` branch shortly, in advance of the release).

**Comment by ojw28** [comment]
Please try the instructions under the "Locally" heading in the README in the dev-v2 branch ([here](https://github.com/google/ExoPlayer/blob/dev-v2/README.md)).

Note the instructions will only work with the dev-v2 branch at this point, so you'll need to checkout that branch for them to work. They will not work on release-v2 until the changes are merged into that branch.
