### ISSUE TITLE
ExoPlayer Flac Extension build instructions produce "use of undeclared identifier 'memset'" error

### ISSUE THREAD

**Issue by oikmar** [google/ExoPlayer#2975]
### Issue description
To enable playback of FLAC media, we are trying to include the flac libraries following instructions in the flac-extension. following the [build instructions](https://github.com/google/ExoPlayer/blob/release-v2/extensions/flac/README.md), the ndk-build fails with the following error:

"error: use of undeclared identifier 'memset' memset(&mWriteHeader, 0, sizeof(mWriteHeader));"

### Reproduction steps
Follow the build instructions for flac extension.

### Link to test content
sent a terminal log to the dev email.

### Version of ExoPlayer being used
release-v2

### Device(s) and version(s) of Android being used
Building on MacOs version 10.12.5. 
installed NDK version: 15.0.4075724

an issue search did not turn up anything similar.

**Comment by oikmar** [comment]
i have built other extensions ([opus](https://github.com/google/ExoPlayer/tree/release-v2/extensions/opus), for instance) successfully. so, i think the tool-chain is working.

**Comment by oikmar** [comment]
was able to build flac-1.3.1 with the above fix.

**Comment by ojw28** [comment]
Fixed in `dev-v2` in https://github.com/google/ExoPlayer/commit/a7ed199622500584d5070335f2381288198a53e7
