### ISSUE TITLE
HLS with mutliple audio/subtitle tracks in TS stream

### ISSUE THREAD

**Issue by goffioul** [google/ExoPlayer#2976]
Consider those samples that contain multiple audio and/or subtitle tracks:
https://drive.google.com/open?id=0BwljeX6541LubXprdmEtTFdBT00
https://drive.google.com/open?id=0BwljeX6541LualNuV0VTSXFWSlk

I convert them to HLS using ffmpeg and codec "passthrough":

    ffmpeg -i SOURCE.ts -codec copy -map 0 -f segment -segment_list playlist.m3u8 out-%04d.ts

When playing the samples in the demo app, I can see all audio/subtitle tracks. When playing the HLS version in the demo app, there's only one audio/subtitle track. By comparison, ffprobe correctly detects all audio/subtitle tracks.

The operation above is typically what a TV headend would do when wrapping a stream into HLS.

Is there a way to make ExoPlayer to see all tracks from the TS segments?

**Comment by AquilesCanta** [comment]
Not in HLS, no. Track #2014 for multiple muxed tracks support in HLS. My suggestion is that you demux the audio streams and expose them as EXT-X-MEDIA elements. Keep in mind that these should be [packed audio segments](https://tools.ietf.org/html/draft-pantos-http-live-streaming-23#section-3.4). Unfortunately, I haven't done this before, but I don't think it would be too complicated with ffmpeg and maybe some extra scripting.

> Is there a way to make ExoPlayer to see all tracks from the TS segments?

You could try modifying the HlsMediaChunk code to replace TsExtractor.MODE_HLS with TsExtractor.MODE_SINGLE_PMT, but this is not officially supported and might caused undesired behavior depending on the encoding of the media.

**Comment by AquilesCanta** [comment]
Note that demuxing the alternative audios is also the smart thing to do, as it will save some wasted bandwidth.

**Comment by goffioul** [comment]
I think you missed the part that this is typically what a TV headend does to wrap live TV broadcasts into HLS. You don't have control over that.

**Comment by goffioul** [comment]
This is particularly a pain when your live TV broadcast contains multiple subtitle tracks, let's say DVB-S. The only 2 options you have on the headend are:
1) burn the subtitles in the video: this means that delivery content through a single media source, you know have to deliver the same content multiple times with different subtitle tracks burnt in the video; then you have to make your player app to know *somehow* that in order to activate subtitles for stream A, it actually has to play another stream B
2) let the headend passthrough all MPEG-TS elementary streams into the HLS (basically only wrapping the original stream), but this is not supported by ExoPlayer

**Comment by goffioul** [comment]
There are probably side-effects I'm not seeing yet, but this simple oneliner allows me to see all tracks in HLS mode:

    diff --git a/library/core/src/main/java/com/google/android/exoplayer2/extractor/ts/TsExtractor.java b/library/core/src/main/java/com/google/android/exoplayer2/extractor/ts/TsExtractor.java
    index 71b8375..6f6d63d 100644
    --- a/library/core/src/main/java/com/google/android/exoplayer2/extractor/ts/TsExtractor.java
    +++ b/library/core/src/main/java/com/google/android/exoplayer2/extractor/ts/TsExtractor.java
    @@ -450,7 +450,7 @@ public final class TsExtractor implements Extractor {
             }
             remainingEntriesLength -= esInfoLength + 5;
 
    -        int trackId = mode == MODE_HLS ? streamType : elementaryPid;
    +        int trackId = elementaryPid;
             if (trackIds.get(trackId)) {
               continue;
             }

Of course, as mentioned in #2014, problems may/will arise if the PMT or PID change, but in the case of wrapped live TV broadcast, this is not happening (to my knowledge).

**Comment by AquilesCanta** [comment]
> This is particularly a pain when your live TV broadcast contains multiple subtitle tracks, let's say DVB-S.

DVB subtitles are not supported by the HLS spec. ExoPlayer does support multiple 608 streams.

The change you propose above is similar to my suggestion of using a different mode. However, this is not supported and there might be future changes that break this patch.

**Comment by goffioul** [comment]
> DVB subtitles are not supported by the HLS spec.

Unfortunately, that's what coming out of my customer's equipment. What would you suggest as a solution then?

**Comment by AquilesCanta** [comment]
I think DVB subs will work anyway. I haven't tested this, though. Of course, the single stream per type limitation will apply unless you override it yourself, as discussed above.
