### ISSUE TITLE
How to pass FLAG_ALLOW_NON_IDR_KEYFRAMES in HLS

### ISSUE THREAD

**Issue by goffioul** [google/ExoPlayer#2979]
When using ExtractorMediaSource, I can pass a customized DefaultExtractsFactory and set FLAG_ALLOW_NON_IDR_KEYFRAMES on it. When but using HlsMediaSource, I don't see a way to achieve the same.

**Comment by AquilesCanta** [comment]
This is a duplicate of #2833.
