### ISSUE TITLE
Switch rendition if the rendition which Exoplayer has chosen is not available

### ISSUE THREAD

**Issue by abhishekredspace** [google/ExoPlayer#2981]
I am using Exoplayer 2 in my video player for playback.
When playing HSL streams is it possible to switch rendition if one of the renditions mentioned in m3u8 file is not available. 
We receive a master m3u8 file from the server. This has all the available renditions. Sometimes it can happen that one of the renditions is not available and can respond with status code of 500, 501, 502, 503, 400 or 403 and if Exoplayer chooses that rendition to play it throws an error. 

What I am trying to achieve here is if one of the rendition is bad rendition and exoplayer is not able to play it, then it should choose the next/other rendition to play which are available but should not throw onPlayerError callback. 

I have also looked at https://github.com/google/ExoPlayer/issues/676 where it talks about changing video track selection using TrackSelector and TrackSelection. 

I have implemented Exoplayer.EventListener where I listen for  
```@Override public void onTimelineChanged(Timeline timeline, Object manifest) { }
@Override public void onTracksChanged(TrackGroupArray trackGroups, TrackSelectionArray trackSelections) {
    // Here I get all video formats and text tracks using 
}
@Override public void onPlayerError(ExoPlaybackException e) { handleError(e); }
```

So when Exoplayer loads and if it picks the rendition which is bad at first place, I get a callback in onPlayerError. 
Is it possible for Exoplayer to choose the other rendition if the one it has picked is bad.

**Comment by AquilesCanta** [comment]
> Is it possible for Exoplayer to choose the other rendition if the one it has picked is bad.

This is already done by ExoPlayer. However some discussion is in order here. The spec says:

> `If the server wishes to remove an entire presentation, it SHOULD`
   `provide a clear indication to clients that the Playlist file is no`
  `longer available (e.g. with an HTTP 404 or 410 response).`

5xx HTTP error codes are reserved for server errors, whereas 404 and 410 explicitly speak about resource changes. If you can use 410 to indicate unavailability, that will make ExoPlayer do exactly what you aim for. If not, we should discuss whether 500 error codes are appropriate. This is because some other users have complained we should not retry if the player gets a 5xx error. E.g: #2844. But I think there are others. Hope this answers your question. Please close if so.

**Comment by abhishekredspace** [comment]
Thanks for your answer and information.

**Comment by abhishekredspace** [comment]
I agree that for 5xxx HTTP error codes Exoplayer should not retry but in case there are 5 renditions available and out of these 5 renditions, 3 comes from the same server and 2 comes from some other server. Consider the 3 coming from the same server, that server encountered a problem and now if exoplayer picks any one of them we will receive 5xxx error code and no point in retrying. However the remaining 2 which comes from another server, Exoplayer should try to play them instead of throwing an error. So my point is if we are sure that all the available rendition will throw 5xxx error then only Exoplayer should throw an error otherwise it should try to play the one which is good.

**Comment by AquilesCanta** [comment]
Sounds like a good argument. I'll give it a thought and post any updates here.

**Comment by abhishekredspace** [comment]
Thanks for giving it a thought. Just to add here AvPlayer in iOS already does this, so this functionality becomes important for us as we are trying to keep the behaviour of both platforms i.e. Android and iOS to be in sync.

**Comment by abhishekredspace** [comment]
Hello Exoplayer team,
Any updates on this issue?

Thanks

**Comment by AquilesCanta** [comment]
Hi, this is still on radar, but we haven't allocated time for it yet, unfortunately. Hopefully we'll get to it soon. Many thanks for your patience!

**Comment by ojw28** [comment]
This is tracking enabling blacklisting for response codes other than 404 and 410, I think?

**Comment by AquilesCanta** [comment]
Correct.

**Comment by AquilesCanta** [comment]
Please give the new LoadErrorHandlingPolicy a try and let us know if it suits your needs.

Thanks!

**Comment by abhivinny** [comment]
Thanks a lot. I will give it a try.
