### ISSUE TITLE
Should there be MappingTrackSelector.clearRendererDisabled() ?

### ISSUE THREAD

**Issue by goffioul** [google/ExoPlayer#2982]
In the same way you can clear all overrides in MappingTrackSelector, should there also be a way to clear any disabled flag that were previously set on some renderers?

**Comment by ojw28** [comment]
No? It seems unlikely an app will disable multiple renderers and need to un-disable them all simultaneously (and you've provided no actual use case to suggest otherwise). It also seems trivial just to iterate over the number of renderers if you want to do this.

**Comment by goffioul** [comment]
It's a way to reset the track selector before loading a different stream. It's also trivial to iterate over the renderers to clear the overrides, but there's an API to clear all overrides at once. For symmetry, I thought it made sense to have the same for the enable/disable flag.

**Comment by ojw28** [comment]
If your use case is as you describe, you can simply use `setSelectionOverride` for everything, and do a full reset with `clearSelectionOverrides`. You can disable a renderer for a given set of tracks using `setSelectionOverride(index, tracks, null)`.

The reason renderers can be disabled with both `setSelectionOverride(index, tracks, null)` and `setRendererDisabled(index, true)` is that the first applies only when a specific set of tracks is available, where-as the second persists across playback of different pieces of media that have different sets of tracks. If you want to reset going from one piece of media to another anyway, there's no reason you can't just use the first option.

**Comment by goffioul** [comment]
Yes, of course. I missed the fact that you can also disable a renderer with setSelectionOverride. Thanks.

**Comment by goffioul** [comment]
Not sure it's a bug or intended behavior, but I'm having trouble using only setSelectionOverride to disable a renderer (using null for the override). My use case is that I have a custom track selector that inherits from DefaultTrackSelector and overrides selectTextTrack. The implementation of selectTextTrack selects one subtitle track based on app-specific criteria (for instance, English subtitles). When the code is trying to disable the renderer with setSelectionOverride(..., null), it does not seem to have any effect.

So, what I'm observing is that a null override does not supersede the default selection (made by the track selector). Is that so?

**Comment by goffioul** [comment]
Is it possible a null overrides stopped being effective with this change?
https://github.com/google/ExoPlayer/commit/2f4bfc3f5fd49e3a356180869a81751dd301a0c5#diff-d131621e999e7a12c3e3e3844b05521cL250

Before the change, it sounds like rendererTrackSelections[i] could get assigned null if the override was null. After the change, a null override is not applied anymore.

**Comment by ojw28** [comment]
Yeah, looks broken. Thanks for reporting! I've filed https://github.com/google/ExoPlayer/issues/2988 to track a fix (and test).
