### ISSUE TITLE
[Question] Reuse Flac Decoder for extra processing

### ISSUE THREAD

**Issue by Fed93** [google/ExoPlayer#2984]
Hi,
I'm trying to apply extra processing to a flac file using the FlacDecoderJni provided with ExoPlayer Extension

I've created a DataSpec, DataSource and finally a DefaultExtractorInput instances.
I've also created an instance of decoderjni and set data using my DefaultExtractorInput instance.
It seems to work fine i also can get FlacStreamInfo, but when I check data in the output byte buffer, after calling method DecodeSample, I see that is full of zero.
I've seen that the FlacDecoder constructor class use InitializationData instead of Extractor Input... But i don't understand what I have to pass as InitializationData.
Someone can help me?

**Comment by ojw28** [comment]
Can you just look at where that constructor is called by the ExoPlayer library, and trace back to where the data is coming from (right click -> Find Usages in Android Studio makes this really easy)? You should be able to answer your own question this way.

**Comment by Fed93** [comment]
Already done.
It's used in LibflacAudioRenderer in createDecoder method (com.google.android.exoplayer2.ext.flac.LibflacAudioRenderer#createDecoder)
But when i try to find usage of this method i see the popup with no usage found.

**Comment by ojw28** [comment]
You should receive a "Do you want to find usages of the base method" dialog when you try and find usage of that method. If you click Yes then you should find a usage (in SimpleDecoderAudioRenderer's maybeInitDecoder method).

**Comment by Fed93** [comment]
I've found various method but are all private.
Also initializationData (variable of Format class used as argument in createDecoder method) used by FlacDecoder is created from SampleStreams in other private method when ExoPlayer load track before playing it.
After this, i tried again to decode flac file using ExtractorInput, FlacStreamInfo is being read good but ByteBuffer is full of zero after calling decoderJni.decodeSample.

I create ExtractorInput using this code
`DataSpec spec = new DataSpec(filePath);`
`FileDataSource source = new FileDataSource();`
`source.open(spec);`
`ExtractorInput input = new DefaultExtractorInput(source, 0, C.LENGTH_UNSET);`

and then i set it to DecoderJni
`decoderJni.setData(input);`

There's something wrong in here?

**Comment by ojw28** [comment]
I'm having a hard time working out what you're doing, which is making it difficult to provide any int here. Let's say you start from the working ExoPlayer demo app. What is it exactly that you're trying to do, and at a high level what changes have you tried to make in order to achieve your goal? You appear to be hooking into the Flac extension at a very low level; certainly lower than we would envisage ever being necessary.

**Comment by Fed93** [comment]
I'm trying to analyze song in order to extrapolate bpm, key, peak and other information and show them and do some other stuff before song is played (for example applying some particular filter).
To do this I need a buffer with uncompressed data of the song. 
I've two different part in my app:
One is the basic player (based on ExoPlayer)
Writed from zero without using ExoPlayer Demo App but only using documentation
One is the audio processor 
My problem is that I need some library to decode Flac and I think Flac extension can help me

**Comment by ojw28** [comment]
Ok. It sounds like there are two different things you need to do:
1. Use the Flac extension in the normal way. I don't think there's any need for you to customize it, or understand what it's doing internally, or anything like that.
1. Add processing to the decoded audio data. This is a completely separate topic, and should probably be done using an `AudioProcessor`. You can inject a custom processor by creating an extension of `DefaultRenderersFactory` and overriding `buildAudioProcessors` to instantiate your custom processor.

**Comment by Fed93** [comment]
For the first point your right... I don't need any customisations.
For the second point.. but creating an extension doesn't force me to use it by creating a SimpleExoPlayer instance?
I create it by this way:  
`TrackSelector trackSelector = new DefaultTrackSelector(new FixedTrackSelection.Factory());`
`DefaultRenderersFactory renderersFactory = new DefaultRenderersFactory(mContext, null,
                DefaultRenderersFactory.EXTENSION_RENDERER_MODE_PREFER);`
`SimpleExoPlayer baseInstance = ExoPlayerFactory.newSimpleInstance(renderersFactory, trackSelector);`

My idea is to process audio before creating player and play music

**Comment by ojw28** [comment]
I don't really understand what your question is. I think the only thing you need to change is the `DefaultRenderersFactory`, which you need to extend so that you can override `buildAudioProcessors` as explained above.

**Comment by ojw28** [comment]
Closing due to lack of updates. Regardless of whether there's still a question here, it seems beyond the scope of this issue tracker.

**Comment by Fed93** [comment]
Hi, sorry but i was away and without internet connection.
I've solved without using Flac Extension but using an external java flac decoder.
When app analyze a music file ExoPlayer isn't instantiated because i don't need it.
