### ISSUE TITLE
Preparing ConcatenatingMediaSource fails when a child media source fails

### ISSUE THREAD

**Issue by adithyankumar** [google/ExoPlayer#2987]
In Exo player while we ConcatenatingMediaSource , when one url in playlist is not found in server , it is not playing other video also. For the whole playlist it throws not file found(404).

**Comment by tonihei** [comment]
The ConcatenatingMediaSource waits till all child media sources are successfully prepared before starting playback. If one of them fails for whatever reason, the whole playlist fails.

When you say the playlist "throws" a 404, I assume you mean that either [ExtractorMediaSource.Listener.onLoadError](https://github.com/google/ExoPlayer/blob/d979469659861f7fe1d39d153b90bdff1ab479cc/library/core/src/main/java/com/google/android/exoplayer2/source/ExtractorMediaSource.java#L54) or [AdaptiveMediaSourceEventListener.onLoadError](https://github.com/google/ExoPlayer/blob/d979469659861f7fe1d39d153b90bdff1ab479cc/library/core/src/main/java/com/google/android/exoplayer2/source/AdaptiveMediaSourceEventListener.java#L137) gets called (depending on the type of media you use). When this happens you can set up a new ConcatenatingMediaSource without the failing source and retry. This should solve your problem.
