### ISSUE TITLE
How to import ExoPlayer library as a module into my project ?

### ISSUE THREAD

**Issue by qlthd** [google/ExoPlayer#2989]
Hi,
I'd like to modify existing files in ExoPlayer, but how can I import it so that i could modify it ?

**Comment by ojw28** [comment]
Dupe of https://github.com/google/ExoPlayer/issues/2974.

**Comment by qlthd** [comment]
Why closing an issue that doesn't have any answer for the moment ?

**Comment by ojw28** [comment]
Because you already have an open issue that's exactly the same, which is https://github.com/google/ExoPlayer/issues/2974.
