### ISSUE TITLE
Background music during video playback

### ISSUE THREAD

**Issue by b0g8** [google/ExoPlayer#2990]
### Issue description
I want to implement background music during video playback. I thought of MergingMediaSource, but it seems it does not support this scenario.
You can have multiple AudioTrack run in parallel, the result is fine. 

Similar issue is #2200 , but it is closed.

**Comment by ojw28** [comment]
The answer is the same as in #2200. If you need tight synchronization, you'll probably need to be mixing the audio prior to feeding it into a single AudioTrack instance. This is not a use case we currently support I'm afraid. If you don't need tight synchronization then you can just use two `ExoPlayer` instances (i.e. an extra one for the background music).

**Comment by b0g8** [comment]
Thanks, I'm trying to use two instances, and share the clock.
