### ISSUE TITLE
Snapshot in SimpleExoPlayerView

### ISSUE THREAD

**Issue by O6e36ashenII** [google/ExoPlayer#2993]
Hello i'm using exoplayer library to play hls video from my cams. 
By the demo, in app we using SimpleExoPlayerView for playing video. At first i tried to get snapshot by creating bitmap. But i have always getting black image on return. I founded the solution then exoplayer playing in textureView.  The problem that i don't understand how to use TextureView instead SimpleExoPlayerView. 
By the code from demo the initialization of player performed in method initializePlayer(SimpleExoPlayerView simpleExoPlayerView).
I can't move on without solution how to get this snapshot of my video cams.
Thanks.

**Comment by b0g8** [comment]
Here is a good  [article](https://medium.com/google-exoplayer/customizing-exoplayers-ui-components-728cf55ee07a) detailing how attributes can be set. One such attribute for SimpleExoPlayerView is surface_type. If it is 1, then a SurfaceView(default) is used, if it is 2, a TextureView is used. (Check SimpleExoPlayerView for more details).

**Comment by O6e36ashenII** [comment]
I founded what difference. but can't find any implementation with exoplayer 2.
Were i need to prepare the textureView in my code ?
`
 public void initializePlayer(SimpleExoPlayerView simpleExoPlayerView, String camUrl, boolean useControler, boolean audio, boolean hls, long seekToPos) {

        if (player == null) {

            TrackSelection.Factory videoTrackSelectionFactory = new AdaptiveVideoTrackSelection.Factory(bandwidthMeter);
            trackSelector = new DefaultTrackSelector(videoTrackSelectionFactory);


            player = ExoPlayerFactory.newSimpleInstance(SafeSity.context, trackSelector, new DefaultLoadControl());// Check it in future
            player.addListener(this);

            eventLogger = new EventLogger(trackSelector);
            player.addListener(eventLogger);
            player.setAudioDebugListener(eventLogger);
            player.setVideoDebugListener(eventLogger);


            simpleExoPlayerView.setPlayer(player);
            player.seekTo(seekToPos);
            player.setPlayWhenReady(true);

            playerNeedsSource = true;
            simpleExoPlayerView.hideController();
            simpleExoPlayerView.setUseController(useControler);


        }
        if (playerNeedsSource && camUrl != null) {

            MediaSource mediaSource;
            if(hls){
                mediaSource = new HlsMediaSource(Uri.parse(camUrl), dataSourceFactory, mainHandler, eventLogger);
            }else {
                mediaSource = new ExtractorMediaSource(Uri.parse(camUrl), dataSourceFactory,new DefaultExtractorsFactory(), mainHandler, null);
            }

            if (!audio){
                for (int i = 0; i < player.getRendererCount(); i++) {
                    if (player.getRendererType(i) == C.TRACK_TYPE_AUDIO) {
                        trackSelector.setRendererDisabled(i, true);
                    }
                }
            }


            player.prepare(mediaSource);
            player.setPlayWhenReady(true);
            playerNeedsSource = false;


        }
    }`

my XML:
`    <com.google.android.exoplayer2.ui.SimpleExoPlayerView
            android:id="@+id/livevideo_videoplayer"
            android:layout_width="0dp"
            android:layout_height="0dp"
            android:layout_alignParentStart="true"
            android:layout_alignParentTop="true" />`

**Comment by O6e36ashenII** [comment]
and how to use controller in textureView. Can't find any solutions

**Comment by ojw28** [comment]
- There is no requirement that you use `SimpleExoPlayerView`. You can use a `TextureView` directly if you prefer. You can use `SimpleExoPlayer.setVideoTextureView` to set a `SimpleExoPlayer` instance to output to a `TextureView`.
- If you do want to use `SimpleExoPlayerView`, you can specify `surface_type` as @b0g8 notes above. You can retrieve the `TextureView` from the `SimpleExoPlayerView` using `SimpleExoPlayerView. getVideoSurfaceView` and then casting to `TextureView`.

**Comment by O6e36ashenII** [comment]
![image](https://user-images.githubusercontent.com/14329021/27532085-bc90396a-5a67-11e7-865a-8987ab75d6fa.png)
Hi The second version works fine, except that you still have to make your MediaPlayerControl to control the video stream, since the SimpleExoPlayerView is under the TextureView in the xml_layout file.
I hope i making all right.
`
            simpleExoPlayerView.setPlayer(player);
            simpleExoPlayerView.getPlayer().setVideoTextureView(textureView);`
Or have some option to use mideacotrol from simpleExoPlayerView in textureView?

**Comment by ojw28** [comment]
You seem to have somehow used a combination of the two suggestions. That's not a sensible thing to do. Either use the first suggestion, or use the second one (probably the second one).

**Comment by O6e36ashenII** [comment]
ok, ty for helping !
