### ISSUE TITLE
Does ExoPlayer handle multiple programs in MPEG-TS

### ISSUE THREAD

**Issue by goffioul** [google/ExoPlayer#2995]
I have a sample MPEG-TS stream, captured from live TV broadcast, that contains 2 programs (1 x video + 1 x audio, 1 x video + 1 x audio). It doesn't seem to work properly in the demo app. Are multi-program MPEG-TS supported?

**Comment by WeiChungChang** [comment]
1. You may need a tool to retrieve one of the program to playback in advance, such as FFMpeg.
If you don't know the command, leave a message here & I could search it for you.

2. If it is still black screen during playback, play it with, ex VLC player to see if it works.

3. If VLC works, try this patch https://github.com/google/ExoPlayer/pull/2842
to see if it works.

If step 3 resolves your problem; please, help to push the support of recovery point key frame check.

**Comment by AquilesCanta** [comment]
I don't know which version you are using but try `TsExtractor.MODE_MULTI_PMT`. Multiprogram TSs are supported. However, preparation time might be longer and some users might prefer to use single PMT mode. If you are going to do that, might make sense to filter out all PMTs that don't correspond to the service you want to play. If you run into any issues, please include all the info requested in the issue template. In the not so far future, removing extra PMTs might not be necessary.

**Comment by goffioul** [comment]
I'm using ExoPlayer 2.4.2 and the demo app, which is using MODE_SINGLE_PMT. In this case, I expect to see only the tracks corresponding to a single programs. However, the demo app shows tracks for all programs (and my problem is most likely related to the fact that it selects the video track from one program and the audio track from the other one).

What I don't understand is why PatReader creates a PmtReader for all programs, even when mode is MODE_SINGLE_PMT. Shouldn't it create only one PmtReader?

**Comment by AquilesCanta** [comment]
The idea behind MODE_SINGLE_PMT was that users that obtain their TSs from tuners were able to filter the streams of a single program. So, that mode expects a single PMT to exist.

> Shouldn't it create only one PmtReader?

It would be arbitrary to pick the first found PMT and discard the rest. It would cause undesirable non-deterministic behavior. As I mentioned before, this is undergoing some changes, which might apply to this conversation. But they are not yet decided. 

So, the best way to go right now is to either use multi PMT mode or filter out the PMTs of services which you don't want the extractor to render. If using multi PMT, you can use the ID of the tracks' formats to differentiate services.

**Comment by goffioul** [comment]
Even with multi PMT mode enabled, the demo app will select by default video and audio tracks from different programs (video track from program 1 and audio track from program 2). That does not really make sense.
