### ISSUE TITLE
Parsing BaseURL in Dash Manifest with line breaks

### ISSUE THREAD

**Issue by alex-hryzak** [google/ExoPlayer#2996]
If there is a line break inside of BaseURL, the value will not be trimmed, resulting in a faulty url (including the line breaks and spaces). Like this:

>
    <AdaptationSet mimeType="text/vtt" lang="en" streamName="Englisch">
      <Representation>
        <BaseURL>
        ../subtitles/FLI4560_AMF_SUB_en.vtt
        </BaseURL>
      </Representation>
    </AdaptationSet>

I tried this with the latest versions of ExoPlayer 1.x and 2.x

**Comment by ojw28** [comment]
I don't think it's valid to have line breaks, or indeed any whitespace, inside of a BaseURL element. None of the examples in either the DASH spec (ISO 23009-1) or the DASH IF recommendations (http://dashif.org/guidelines/) do so.

Please let us know if you kind find some documentation indicating otherwise. Thanks!

**Comment by vikingmedia** [comment]
https://www.w3.org/TR/2001/REC-xmlschema-2-20010502/#anyURI states

> NOTE: Spaces are, in principle, allowed in the ·lexical space· of anyURI, however, their use is highly discouraged (unless they are encoded by %20).

It doesn't say anything about line breaks. However, older versions of ExoPlayer did interpret BaseURLs with line breaks correctly.

**Comment by ojw28** [comment]
In that case, to be more precise :)... If you do add line breaks or whitespace inside of the BaseURL element, then I don't think you should expect it to be trimmed.

**Comment by vikingmedia** [comment]
hi @ojw28, I have to admit you're probably right from a technical perspective. I still think though, that successfully playing a slightly malformed manifest is of more value to the users than us being right :-). I can't think of any situation in which not trimming line feeds and white spaces in the BaseURL would make sense or add to the robustness of the player. The manifest that @alex-hryzak posted was created by [Bitmovin](https://github.com/bitmovin), a fast growing professional encoding service. The other players in our ecosystem correctly play the subtitles, and so did Exoplayer before we updated to the current version (have to admit though, that one of the players is the one provided by Bitmovin). Anyway, that's only my humble opinion. Thank you for providing us with this great player!

**Comment by ojw28** [comment]
I'd suggest you report the issue to Bitmovin; who I suspect will be happy to make a quick fix on their side.

**Comment by vikingmedia** [comment]
already did that, thanks. Just wanted to contribute my opinion, that's all.
