### ISSUE TITLE
Support for one AdaptationSet element in the DASH manifest

### ISSUE THREAD

**Issue by bschuste** [google/ExoPlayer#2998]
### Issue description
This is a feature request, as written in https://google.github.io/ExoPlayer/supported-formats.html,
.."Media streams must be demuxed, meaning that video, audio and text must be defined in distinct AdaptationSet elements in the DASH manifest..."

Is there a way to support audio and video streams in one AdaptationSet?

### Reproduction steps
The media content has been produced with MP4Box, audio and video are deinterleaved in one mdat box.
MP4Box -dash 2000 -frag 2000 -rap -segment-name segment- video200012.mp4

### Link to test content
[segment.zip](https://github.com/google/ExoPlayer/files/1105767/segment.zip)

### Version of ExoPlayer being used
r2.1.1

### Device(s) and version(s) of Android being used
Motorola G4, android 6.0.1

### A full bug report captured from the device
Not a bug.

**Comment by ojw28** [comment]
This is not something we intend to support. The DASH IF recommendations mandates that audio/video are demuxed ("only non-multiplexed Representations shall be used, i.e. each Representation only contains
41 a single media component"). If I remember correctly, most DASH profiles mandate this too.
