### ISSUE TITLE
Get YUV frames from HLS online url

### ISSUE THREAD

**Issue by nikhilkilivayil** [google/ExoPlayer#2999]
Any option to get YUV frame buffer ?

**Comment by ojw28** [comment]
We do not provide a direct API for this, but there are multiple approaches you could look into if you're trying to grab video frames in a particular format. For example you could use TextureView.getBitmap to get the current frame in a bitmap, at which point you could do your own conversion into a preferred format.

Without a proper description of the use case it's impossible to provide any solid guidance regarding whether what you're trying to do is feasible, and if so what the best approach would be. If you want to provide more information, please do so here and we'll re-open the issue. Thanks!
