### ISSUE TITLE
Ac3PassthroughAudioTrackRenderer is missing from library

### ISSUE THREAD

**Issue by takn** [google/ExoPlayer#300]
Hi I was trying to test out the DemotPlayer but it's expecting 'com.google.android.exoplayer.Ac3PassthroughAudioTrackRenderer;' which is missing from the library. 
Can you please add it so the sample code works? thank you.

**Comment by ojw28** [comment]
Which branch are you using? I believe this is fixed already (as of about an hour ago).

**Comment by ojw28** [comment]
Marking as closed, because I'm pretty sure this is fixed. Please re-open if not.
