### ISSUE TITLE
Video of LoopingMediaSource containing a ClippingMediaSource has a delay

### ISSUE THREAD

**Issue by wildebeast** [google/ExoPlayer#3001]
**Description**

When creating a LoopingMediaSource that contains a ClippingMediaSource of another MediaSource, the player has a short delay in between loops. Is it possible to make the loop seamless?

Note: I see that this issue looks similar to https://github.com/google/ExoPlayer/issues/2923, but that appears to relate exclusively to audio-only files, not video.

**Reproduction**

I've forked the demo app (which uses version 2.4.2) and reproduced the issue here:

https://github.com/wildebeast/ExoPlayer/commit/2f36665bc9af199cc14e6a85a16d59317cf24043

To test, choose the last element in the sample list ("Reproduced Behavior: Clipped Loop Delay").

**Devices Tested**

Nexus 9, Samsung S4, Samsung Galaxy SM-T700

**Comment by andrewlewis** [comment]
From #1988: "An important caveat is that when playback transitions into a ClippingMediaSource the player needs to do a frame-exact seek operation. To avoid buffering you therefore need to ensure that the clipping start point corresponds to a synchronization sample/key-frame. (Playback should work even if you don't do this, but transitions from one source to the next will not be seamless.)" Is the clipping start point a keyframe?

**Comment by tonihei** [comment]
Have a look at #2923 again. We added a new constructor to [ClippingMediaSource](https://github.com/google/ExoPlayer/blob/dev-v2/library/core/src/main/java/com/google/android/exoplayer2/source/ClippingMediaSource.java#L72) which lets you disable the discontinuity. Note, that this is only advisable if you can ensure your clipping start point is a key-frame as @andrewlewis already pointed out.

**Comment by wildebeast** [comment]
Thanks for the tips @tonihei and @andrewlewis!
