### ISSUE TITLE
Screen stuck when play for a while

### ISSUE THREAD

**Issue by 13217300237** [google/ExoPlayer#3002]
part of log is below:
`Line 25382: 06-26 17:38:48.416 W/System.err( 6348): com.google.android.exoplayer2.ExoPlaybackException
	Line 25384: 06-26 17:38:48.416 W/System.err( 6348): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:350)
	Line 25386: 06-26 17:38:48.416 W/System.err( 6348): 	at android.os.Handler.dispatchMessage(Handler.java:98)
	Line 25388: 06-26 17:38:48.416 W/System.err( 6348): 	at android.os.Looper.loop(Looper.java:148)
	Line 25390: 06-26 17:38:48.416 W/System.err( 6348): 	at android.os.HandlerThread.run(HandlerThread.java:61)
	Line 25392: 06-26 17:38:48.416 W/System.err( 6348): 	at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
	Line 25394: 06-26 17:38:48.416 W/System.err( 6348): Caused by: java.lang.ArrayIndexOutOfBoundsException: length=2; index=2
	Line 25396: 06-26 17:38:48.416 W/System.err( 6348): 	at com.google.android.exoplayer2.source.hls.HlsSampleStreamWrapper.finishedReadingChunk(HlsSampleStreamWrapper.java:322)
	Line 25398: 06-26 17:38:48.416 W/System.err( 6348): 	at com.google.android.exoplayer2.source.hls.HlsSampleStreamWrapper.readData(HlsSampleStreamWrapper.java:299)
	Line 25400: 06-26 17:38:48.416 W/System.err( 6348): 	at com.google.android.exoplayer2.source.hls.HlsSampleStream.readData(HlsSampleStream.java:49)
	Line 25402: 06-26 17:38:48.416 W/System.err( 6348): 	at com.google.android.exoplayer2.BaseRenderer.readSource(BaseRenderer.java:282)
	Line 25404: 06-26 17:38:48.416 W/System.err( 6348): 	at com.google.android.exoplayer2.metadata.MetadataRenderer.render(MetadataRenderer.java:121)
	Line 25406: 06-26 17:38:48.416 W/System.err( 6348): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:466)
	Line 25408: 06-26 17:38:48.416 W/System.err( 6348): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300)
	Line 25410: 06-26 17:38:48.416 W/System.err( 6348): 	... 4 more
	Line 25412: 06-26 17:38:48.416 E/EventLogger( 6348): playerFailed [4.13]
	Line 25414: 06-26 17:38:48.416 E/EventLogger( 6348): com.google.android.exoplayer2.ExoPlaybackException
	Line 25416: 06-26 17:38:48.416 E/EventLogger( 6348): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:350)
	Line 25418: 06-26 17:38:48.416 E/EventLogger( 6348): 	at android.os.Handler.dispatchMessage(Handler.java:98)
	Line 25420: 06-26 17:38:48.416 E/EventLogger( 6348): 	at android.os.Looper.loop(Looper.java:148)
	Line 25422: 06-26 17:38:48.416 E/EventLogger( 6348): 	at android.os.HandlerThread.run(HandlerThread.java:61)
	Line 25424: 06-26 17:38:48.416 E/EventLogger( 6348): 	at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
	Line 25426: 06-26 17:38:48.416 E/EventLogger( 6348): Caused by: java.lang.ArrayIndexOutOfBoundsException: length=2; index=2
	Line 25428: 06-26 17:38:48.416 E/EventLogger( 6348): 	at com.google.android.exoplayer2.source.hls.HlsSampleStreamWrapper.finishedReadingChunk(HlsSampleStreamWrapper.java:322)
	Line 25430: 06-26 17:38:48.416 E/EventLogger( 6348): 	at com.google.android.exoplayer2.source.hls.HlsSampleStreamWrapper.readData(HlsSampleStreamWrapper.java:299)
	Line 25432: 06-26 17:38:48.416 E/EventLogger( 6348): 	at com.google.android.exoplayer2.source.hls.HlsSampleStream.readData(HlsSampleStream.java:49)
	Line 25434: 06-26 17:38:48.416 E/EventLogger( 6348): 	at com.google.android.exoplayer2.BaseRenderer.readSource(BaseRenderer.java:282)
	Line 25436: 06-26 17:38:48.416 E/EventLogger( 6348): 	at com.google.android.exoplayer2.metadata.MetadataRenderer.render(MetadataRenderer.java:121)
	Line 25438: 06-26 17:38:48.416 E/EventLogger( 6348): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:466)
	Line 25440: 06-26 17:38:48.416 E/EventLogger( 6348): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300)
	Line 25442: 06-26 17:38:48.416 E/EventLogger( 6348): 	... 4 more`

I don't know what's happening,so can any one give me some direction I will thank very much.

**Comment by andrewlewis** [comment]
This issue is being closed because it does not adhere to our issue template, and/or because it omits information requested in the issue template that is required for us to investigate the problem efficiently. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

If you’re able to provide complete information as requested in the issue template, please do so below and we’ll re-open the issue. Thanks!
