### ISSUE TITLE
Error inflating class com.google.android.exoplayer2.ui.SimpleExoPlayerView

### ISSUE THREAD

**Issue by afrostreambahri** [google/ExoPlayer#3003]
hello
i had this issue when i upgrade exoplayer library from 2.3.1 to 2.4.2 
android.view.InflateException: Binary XML file line #27: Binary XML file line #27: Error inflating class com.google.android.exoplayer2.ui.SimpleExoPlayerView

please help me 

this is my player_activity.xml : 

<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/root"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:keepScreenOn="true">

    <RelativeLayout    android:layout_width="match_parent"
        android:layout_height="match_parent"  >
        <ProgressBar
            android:id="@+id/loading_spinner"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:visibility="gone"

            android:layout_gravity="center|center_horizontal"
            android:indeterminate="true"
            android:indeterminateTintMode="src_atop"
            android:layout_centerInParent="true"

            android:indeterminateTint="#bb33b5e5"
            />
    </RelativeLayout>

    <com.google.android.exoplayer2.ui.SimpleExoPlayerView android:id="@+id/player_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

    </com.google.android.exoplayer2.ui.SimpleExoPlayerView>

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:background="#88000000"
        android:orientation="vertical"
        >

        <TextView android:id="@+id/debug_text_view"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:paddingLeft="4dp"
            android:paddingRight="4dp"
            android:textSize="10sp"
            tools:ignore="SmallSp"/>

        <LinearLayout android:id="@+id/controls"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="horizontal"
            android:visibility="visible"
            android:gravity="center_vertical">

            <LinearLayout android:id="@+id/controls_root"
                android:layout_height="wrap_content"
                android:orientation="horizontal"
                android:visibility="visible"
                android:layout_width="320dp">

                <ImageView
                    android:layout_width="120dp"
                    android:layout_height="30dp"
                    app:srcCompat="@drawable/logo300"
                    android:id="@+id/imageViewLogo"
                    android:visibility="visible"
                    android:layout_marginLeft="5dp"
                    android:elevation="0dp"
                    android:scaleType="fitCenter"
                    android:layout_gravity="center_vertical"/>

                <LinearLayout android:id="@+id/controls_topright"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"
                    android:orientation="horizontal"
                    android:gravity="right"
                    android:visibility="visible"

                    android:showDividers="middle"
                    android:divider="@drawable/empty_tall_divider"
                    android:paddingLeft="10dp"
                    android:paddingRight="10dp">

                </LinearLayout>

            </LinearLayout>

            <LinearLayout android:id="@+id/controls_cast"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:gravity="right"
                android:orientation="horizontal"

                android:visibility="visible"
                >

                <android.support.v7.app.MediaRouteButton
                    android:id="@+id/media_route_button"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:background="@android:color/transparent"
                    android:divider="@drawable/empty_tall_divider"
                    android:layout_weight="1"
                    android:mediaRouteTypes="user"
                    android:visibility="visible"
                    android:gravity="right" />

                <LinearLayout
                    android:layout_width="35dp"
                    android:layout_height="match_parent"
                    android:id="@+id/LayoutbntClose"

                    android:gravity="center"
                    android:orientation="vertical">

                <ImageView
                    android:layout_width="20dp"
                    android:layout_height="18dp"
                    android:layout_marginRight="3dp"
                    android:padding="10dp"

                    android:background="@drawable/close"
                    android:id="@+id/bntClose"
                    android:visibility="visible"

                    android:scaleType="centerCrop"
                    android:layout_gravity="center_vertical"/>

                </LinearLayout>

            </LinearLayout>

        </LinearLayout>
    </LinearLayout>
    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:background="#88000000"
        android:orientation="vertical"
        >

        <fragment
            android:id="@+id/castMiniController"
            android:layout_width="fill_parent"
            android:layout_height="wrap_content"
            android:layout_alignParentBottom="true"
            android:visibility="gone"
            class="com.google.android.gms.cast.framework.media.widget.MiniControllerFragment"/>

    </LinearLayout>

</FrameLayout>

**Comment by ojw28** [comment]
This sounds like an issue with your project rather than anything wrong with ExoPlayer. Perhaps you're missing a dependency somehow. I'd suggest taking a look at our demo app, checking that works, and assuming that it does work trying to figure our what your project is doing differently.
