### ISSUE TITLE
getDuration() is negative!

### ISSUE THREAD

**Issue by LittleSunZ** [google/ExoPlayer#3004]
url is https://lcache.qingting.fm/cache/20170428/387/387_20170428_030000_040000_24_0.aac。
Please tell how to solve, thanks!

**Comment by AquilesCanta** [comment]
Could you confirm it is not C.TIME_UNSET?

**Comment by ojw28** [comment]
I'm pretty sure it will be. `C.TIME_UNSET` is an allowed and documented return value. The type of file you're trying to play makes determining the duration very difficult. The player would need to download and parse the entire file to work the duration out. When I try and play the file in VLC I see that it does show a duration, but that the duration shown constantly changes over time (i.e. it's estimating, and the estimate is being updated during playback).

If you control the source content then you should use a more appropriate container format (e.g. mp4).
