### ISSUE TITLE
Reduce time of connection life

### ISSUE THREAD

**Issue by bene25** [google/ExoPlayer#3005]
Hello. I didnt find place where I could ask question like google groups. We are using exoplayer version 2.0.4. How could we reduce connection life(for now it's living for 5 minutes)?
And how we could reduce requests beatrate (for now we have 12 seconds per second)?
Thanks.

**Comment by ojw28** [comment]
There's not enough information here for us to help. What are you defining as connection life, and how are you measuring it? I don't understand what beatrate means, either. What type of media is being played?

**Comment by ojw28** [comment]
Closing due to lack of information.
