### ISSUE TITLE
Demo App > Misc > Dizzy playback incomplete after onResume

### ISSUE THREAD

**Issue by ened** [google/ExoPlayer#301]
While testing the demo App, I tried playing the "Dizzy" mp4 clip.
During the playback, I turned the tablet (MTK based) off (standby) and back on. 

The App will then play the clip again from the beginning, and:
 - The audio will restart from the beginning
 - The video will stay off until the previous position has been reached and will then continue to be displayed

When trying this a couple of times, it will behave in the same way.

The expected behaviour should be a continued playback (both audio & video) from the last known position.

**Comment by ened** [comment]
Reproduced on Nexus 7 (2013) running Android 5.0.2.

**Comment by ojw28** [comment]
I can reproduce this, and I think I have a fix (I'll do some further testing tomorrow).

**Comment by ojw28** [comment]
Fixed in dev.
