### ISSUE TITLE
Compilation fails in branch dev-v2

### ISSUE THREAD

**Issue by goffioul** [google/ExoPlayer#3010]
Since this commit https://github.com/google/ExoPlayer/commit/81d077c037e3d559d28fa95e596ef91788587add
Class ClosedSource is missing from the repo.

    library/core/src/main/java/com/google/android/exoplayer2/source/offline/Downloader.java:28: error: cannot find symbol
    import com.google.android.exoplayer2.util.ClosedSource;
                                             ^
      symbol:   class ClosedSource
      location: package com.google.android.exoplayer2.util

**Comment by ojw28** [comment]
Fixed in https://github.com/google/ExoPlayer/commit/19a3d94022d4450eaccaaf48bcbf71f27aef4418
