### ISSUE TITLE
Offline Licence Aquisition

### ISSUE THREAD

**Issue by MongeziNombewu** [google/ExoPlayer#3016]
Hi

I am trying to acquire and store a DRM license for a video to playback, The OfflineLicenseHelper seems to accommodate this, but requires  DrmInitData object when trying to download the license [downloadLicense(DrmInitdata)]). What data should be populated in the SchemeData object required to initialize the DrmInitData object?

**Comment by fabiobazurto** [comment]
How did you get this behavior?
