### ISSUE TITLE
ExoPlayer enters into endless buffering state (HLS)

### ISSUE THREAD

**Issue by sdex** [google/ExoPlayer#3021]
### Issue description
ExoPlayer enters into endless buffering state. VLC plays video fine. 

### Reproduction steps
Run the video, seek to 4:00 minutes, on 4:10 playback is stopped, ExoPlayer enters into endless buffering state.

### Link to test content
The link has been sent. 

### Version of ExoPlayer being used
2.4.3

### Device(s) and version(s) of Android being used
All devices and emulators. 

### A full bug report captured from the device
The report has been sent. 

Maybe, the issue is related to #2872.

Thanks.

**Comment by ojw28** [comment]
The media is broken. Specifically, the text media playlist (e.g. 09.m3u8) contain discontinuities where-as the variant media playlists (e.g. 01.m3u8) do not. More worryingly, if you look at the snippet of 09.m3u8 below, it's listing the exact same segment twice around the discontinuity, with two different durations. A segment can only have one duration, and should only be listed once.
```
#EXTINF:10,
20170630T141639-09-25.vtt
#EXT-X-DISCONTINUITY
#EXTINF:0.01,
20170630T141639-09-25.vtt
```
If you disable the text track (it's selected by default as this is what the master playlist requests) then playback proceeds successfully.
