### ISSUE TITLE
Chrome OPUS MediaRecorder

### ISSUE THREAD

**Issue by wtroynelson** [google/ExoPlayer#3023]
Just upgraded from Exoplayer v1 to Exoplayer v2. v1 can decode OPUS audio generated by Chrome media recorder just fine using WebmExtractor(). MatrasokaExtractor on v2 seems to have problems decoding a Chrome generated OPUS file (using MediaRecorder and recording voice from microphone)

Chrome generated OPUS seems to have a few hundred bytes of extra data at the beginning of the file. If i manually trim the file to the Matroska header (bytes "1a 45 df a3" from hexdump -C) then it is successful in playing the audio, although it sounds slightly distorted. The distortion could be device dependant since I've had issues with the native decoder doing the same thing. Current device is a Samsung Tab E

Main issue is that WebmExtractor seems to search by itself for the Matroska header and MatroskaExtractor does not (tested both on the same file generated by Chrome).

Error as seen in logcat:
`Caused by: com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor) could read the stream.`

Here is the link to the file I am testing:

https://drive.google.com/file/d/0B27-wdzgmDWBTkJ0OHZqUFNOOGM/view?usp=sharing

**Comment by ojw28** [comment]
The sample file doesn't seem to play in V1 either for me. What version of V1 were you using, exactly?

**Comment by ojw28** [comment]
I can't play it in VLC or Chrome either. Are you sure the link is correct?

**Comment by wtroynelson** [comment]
Hmm.. odd. I'll do some research and get back to you this afternoon. It would have been June last year that I compiled Exoplayer v1. Found this in the build.gradle

publish {
    repoName = 'exoplayer'
    userOrg = 'google'
    groupId = 'com.google.android.exoplayer'
    artifactId = 'exoplayer'
    version = 'r1.5.7'
    description = 'The ExoPlayer library.'
    website = 'https://github.com/google/ExoPlayer'
}


Here is the top entry from libopus 'git -log'

commit 3105fa273c125faeda6b7168c74854a7f71a90c4
Author: Tristan Matthews <tmatth@videolan.org>
Date:   Wed Jun 28 16:29:02 2017 -0400

    Add checksum for opus 1.2.1 release

**Comment by ojw28** [comment]
The content you've linked to is only 88 bytes long, so I suspect the link is incorrect.

**Comment by wtroynelson** [comment]
It appears you are correct. It seems my instance of MediaRecorder running in Chrome got bugged somehow, and in 24 hours of debugging I never thought to hit refresh on that page.

I have confirmed Exoplayer v2 with libopus working well with Chrome MediaRecorder (now that Chrome is generating valid OPUS in WebM).
