### ISSUE TITLE
Video of High-Quality when setPlaybackParameters above 4x is not work

### ISSUE THREAD

**Issue by iponkan** [google/ExoPlayer#3027]
I was trying to play video in 2x／4x／6x，when it is 480p videos，it is fine。When quality of video is high,like 1080p or 2k,2x is fine, but 4x the video is not palying and the time keep going-up.
here is my code:

```
PlaybackParameters playbackParameters = new PlaybackParameters(speed, 1.0f);
player.setPlaybackParameters(playbackParameters);
```

**Comment by ojw28** [comment]
The device simply isn't able to decode the video stream quickly enough. Handling this case better (e.g. by only showing key-frames) is tracked by https://github.com/google/ExoPlayer/issues/1948.

**Comment by iponkan** [comment]
@ojw28 when i click the fastforward button it can paly the frame，so i think it is still have problem in 
setPlaybackParameters not work when play 4x high-quality video
