### ISSUE TITLE
External Subtitles VTT

### ISSUE THREAD

**Issue by imarenco** [google/ExoPlayer#3029]
Hello,
I've been using 2.4.3 version but I'm needing some examples to use multiple vtt external files in order to switch these subtitles. Are there some examples available to keep an eye on them?

I tried to use MergingMediaSource but this only Works with 1 subtitle file.

thnks!

**Comment by ojw28** [comment]
You can merge as many subtitle files as you want using `MergingMediaSource`. Just pass an extra child `SingleSampleMediaSource` for each additional subtitle file. The `MergingMediaSource` constructor takes an arbitrarily large array...

**Comment by imarenco** [comment]
Ok, but how I can switch the subtitles? @ojw28

**Comment by ojw28** [comment]
Through the normal track selection APIs (e.g. `DefaultTrackSelector`). If you create this kind of source in the demo app then there will be a button that allows you to select the subtitle, so that should serve as a pretty good starting point for you to work out how it's done.

**Comment by imarenco** [comment]
Hello I use DefaultTrackSelector but when I use getTrackGroup(C.TRACK_TYPE_TEXT) the size of group is 0. When I use the equal method with C.TRACK_TYPE_AUDIO the size of audio it's right.

MappedTrackInfo mappedTrackInfo = trackSelector.getCurrentMappedTrackInfo();
TrackGroupArray group =  mappedTrackInfo.getTrackGroups(C.TRACK_TYPE_TEXT);

Do you know why that happens?
@ojw28  @andrewlewis

**Comment by ojw28** [comment]
`getTrackGroups` doens't expect a C.TRACK_TYPE constant as its argument, so that's definitely wrong. The Javadoc clearly indicates that you need to pass a renderer index. As per my previous response, you should spend some time looking at the demo app and use that as a starting point.
