### ISSUE TITLE
Seekbar

### ISSUE THREAD

**Issue by Patelchir** [google/ExoPlayer#3034]
I want to change seekbar whenever i swipe the seekbar and whenever i use getduration() method the value of my audio file is negative.. so what can i do for get for total duration of my audio file?

**Comment by ojw28** [comment]
I'm not sure what this question means. Please try rephrasing. Thanks!

**Comment by Patelchir** [comment]
I want to say that i am streaming audio in exo player.. so how can i get streaming song total duration??? is it any method available in exoplayer?

**Comment by AquilesCanta** [comment]
This is most likely a duplicate of #3004. If not, please update this thread with the file you are trying to play and explain exactly the expected and actual behavior.
