### ISSUE TITLE
Prebuffering

### ISSUE THREAD

**Issue by Fullhazard** [google/ExoPlayer#3036]
Hi! This is my first post to Github. Is it possible to get pre-buffering percentage with Exoplayer?

`

                        int estimatedBufferDuration = (int) C.TIME_UNSET;
                        int estimatedBufferPosition = (int) player.getBufferedPosition();
                        if (estimatedBufferPosition != C.TIME_UNSET) {
                            estimatedBufferDuration = (int) (estimatedBufferPosition - player.getCurrentPosition());
                        }
                        int percentage = 0;
                        if (estimatedBufferDuration != C.TIME_UNSET) {
                            percentage = (estimatedBufferDuration * 100) / DEFAULT_MIN_BUFFER_MS;
                            percentage = Math.max(0, Math.min(100, percentage));
                        }

`
Thanks about this to ojw28! Above code will provides buffering percentages, not pre-buffering percentages for me .

**Comment by Fullhazard** [comment]
First of all I wanna apologize for my english. I just realized that prebuffering/preloading is wrong word for this.  I  Wanna try to explain my problem as well as possible.. When I start to play stream buffering percentages jumps instantly from 0 to 100%..  Otherwise buffering percentage goes smoothly from 0 to 100% after swiping SeekBar  After swiping SeekBar stream stops for second  at this point percentage is still 0).  After that stream jumps to next frame/segment. At  this point buffering goes smoothly from 0 to 100% and playback starts successfully when percentage reaches 100%.  

So.. Is it possible to get buffering percentage from begin to end.

**Comment by ojw28** [comment]
`getBufferedPercentage` is what you should be using. If that's not working for you then please provide clear reproduction steps that let us reproduce the problem you're seeing.

**Comment by Fullhazard** [comment]
Maybe most easiest way to explain my "problem" is... Jumping from segment to another segment(seeking)., buffer percentage stays 0% until jumping is happened(and buffering starts. Most of times jumping from segment to another segment takes more time than buffering upcoming segment. 

I have tested hls live and vod streams..

Here is the methods i am using if it is any help..

`

    public void bufferPercentage()
    {
        int estimatedBufferDuration = (int) C.TIME_UNSET;
        int estimatedBufferPosition = (int) player.getBufferedPosition();
        if (estimatedBufferPosition != C.TIME_UNSET) {
            estimatedBufferDuration = (int) (estimatedBufferPosition - player.getCurrentPosition());
        }

        if (estimatedBufferDuration != C.TIME_UNSET) {
            percentage = (estimatedBufferDuration * 100) / (DEFAULT_MIN_BUFFER_MS * 250); // -> 2500
            percentage = Math.max(0, Math.min(100, percentage));
        }
    }
`

    @Override
    public void onPlayerStateChanged(boolean playWhenReady, int playbackState) {

        if (playbackState == ExoPlayer.STATE_ENDED)
        {
            showControls();
            progressDialog.dismiss();
            handler.removeCallbacksAndMessages(runnable);
            timer.cancel();
            Toast.makeText(getApplicationContext(), "Playback ended", Toast.LENGTH_LONG).show();
        } else if (playbackState == ExoPlayer.STATE_BUFFERING)
        {
            progressDialog.show();
            Timer(); // Method Timer() changes text of progressDialog and sets cancelable

            handler = new Handler(); // Handler checks current Buffering percentage every
            final Runnable runnable = new Runnable() {
                @Override
                public void run() {
                    bufferPercentage(); // Method bufferPercentage() provides estimated buffering percentage
                    if (cdTimer == 0) {
                        progressDialog.setMessage("Buffering takes too long.. " + percentage + "%");
                        progressDialog.setCancelable(true);
                    } else if (cdTimer == 1) {
                        progressDialog.setMessage(String.valueOf("Buffering.. " + percentage + "%"));
                        progressDialog.setCancelable(false);
                    }
                    handler.postDelayed(this, 10);
                }
            };
            handler.postDelayed(runnable, 10);

        } else if (playbackState == ExoPlayer.STATE_READY) {
            progressDialog.dismiss();
            handler.removeCallbacksAndMessages(runnable);
            timer.cancel();
        }
        updateButtonVisibilities();
    }

``

**Comment by ojw28** [comment]
The above response doesn't describe any actual problem. It just seems to describe doing a seek. What is the actual problem?

**Comment by Fullhazard** [comment]
"Most of times jumping from segment to another segment takes more time than buffering upcoming segment." Is it possible to get estimated percentage already in previous segment?

**Comment by ojw28** [comment]
I just don't understand what that means, sorry...

**Comment by Fullhazard** [comment]
Should buffering starts immediately after seeking?

**Comment by ojw28** [comment]
Yes
