### ISSUE TITLE
Make segment indexes visible to subclasses of DefaultDashChunkSource

### ISSUE THREAD

**Issue by ojw28** [google/ExoPlayer#3037]
This is to enable customizations to the source that require access to the segment indices (i.e. the parsed SIDX boxes).

We may also want to expose more of the RepresentationHolder. It currently has protected visibility, which suggests it was intended to be accessed by subclasses at some point in time.

**Comment by mangui** [comment]
thanks @ojw28 
it will definitively be useful to be able to access segment indices

**Comment by ojw28** [comment]
@mangui - Please give the above change a look and verify that it's sufficient for you. Please close this issue if so. Thanks!
