### ISSUE TITLE
Can we tweak hardware/software decoding in Exoplayer?

### ISSUE THREAD

**Issue by malleshamdasari** [google/ExoPlayer#3039]
I have searched a lot on hardware acceleration of video decoding in Exoplayer but I couldn't find any information. I have looked at Mediacodec folder of explayer code to tweak but couldn't get success. Is exoplayer using hardware decoders? If so, how can I tweak?

**Comment by andrewlewis** [comment]
Android provides a list of codecs in priority order, and ExoPlayer picks the first usable decoder that supports playback of input media format. This is generally a hardware accelerated decoder if the device has one for the format. Please read [`MediaCodecUtil`](https://github.com/google/ExoPlayer/blob/79f7db7/library/core/src/main/java/com/google/android/exoplayer2/mediacodec/MediaCodecUtil.java) for details of how this works.

Generally it's best to leave codec selection up to ExoPlayer. However, if you need to change the behavior you can implement a custom [`MediaCodecSelector`](https://github.com/google/ExoPlayer/blob/ce55d1a/library/core/src/main/java/com/google/android/exoplayer2/mediacodec/MediaCodecSelector.java). For example, you could put in logic that picks only decoders with names starting "OMX.google.", which should be software decoders. Different devices have different decoders so the logic would need to be robust to this. We also provide the [vp9](https://github.com/google/ExoPlayer/tree/76faa5b/extensions/vp9) extension, which provides a separate non-MediaCodec based renderer that wraps libvpx for VP9 decoding in software.

**Comment by brandoncodes** [comment]
Hey I'm not sure if this will help you. From what I understand with Exoplayer it will attempt to choose the best codec for you, it checks to see what hardware acceleration is available on the device. You'll see this in the debug logs; it'll tell you what is unsupported, and then in a video/audio debug listener you can see which codec was chosen.

As a side note, if you need software decoders you can use:

`        
DefaultRenderersFactory rf = new DefaultRenderersFactory(this.getApplicationContext(), null, DefaultRenderersFactory.EXTENSION_RENDERER_MODE_ON);
        player = ExoPlayerFactory.newSimpleInstance(
                rf,
                new DefaultTrackSelector(),
                new DefaultLoadControl()
        );
`

If you want to prefer the use of software decoders (i.e. ffmpeg for audio) just set the EXTENSION_RENDERER_MODE_ON to EXTENSION_RENDERER_MODE_PREFER

**Comment by malleshamdasari** [comment]
Hi brandon, Thank you very much for the response. This is exactly what I was looking for. I will try with EXTENSION_RENDERER_MODE_PREFER. Thanks

**Comment by willcun** [comment]
Hello,

Please excuse me if this is the correct place to ask this question.  However,  I'm new to Exoplayer and I'm trying to get it to work with IIS Smooth Streaming.  I have a live stream setup that plays well in IE with Silverlight but it doesn't play on Android with Exoplayer.  The Expressions Encoder is using IIS Smooth Streaming with VC-1 for Video and WMA Professional for Audio.

When I point Exoplayer to the IIS Smooth Stream the seek bar shows the amount of time in the stream and at the top it has a button for Audio and a button for Text but no sound or video shows.  

Can someone assist me in letting me know what I'm doing wrong?  The Smooth Streaming demos that come with Exoplayer work however my live stream doesn't.

**Comment by ojw28** [comment]
Android doesn't support VC-1 or WMA at the decoder level. You really need to be using something a bit more standard (e.g. H.264 and AAC) if you want to target multiple platforms. I don't even think Microsoft's own new browser (Edge) supports Silverlight, by the way. See [here](https://blogs.windows.com/msedgedev/2015/07/02/moving-to-html5-premium-media/).

**Comment by willcun** [comment]
ojw28 thank you for the quick response!!!  

Ok so going encoder to IIS publishing point doesn't work with the vc-1 codec. Gotcha...    Is it possible to use HLS from IIS with the vc-1 codec?

**Comment by ojw28** [comment]
Android does not support VC-1. The HLS specification doesn't even accommodate VC-1, as far as I'm aware.

**Comment by willcun** [comment]
Ok... Thanks!!  I guess I can stop beating my head against the wall.  LOL
