### ISSUE TITLE
Frequent playing interrupts via HSCSD connection

### ISSUE THREAD

**Issue by dim4ikhot** [google/ExoPlayer#3043]
Hi. I'm using Exoplayer version 2.4.3. I searched a lot, but did not find any solution. So, the issue is next: I have next implementation of exoPlayer(audio only) with okHttp3, which plays live audio streams:

```
BandwidthMeter bandwidthMeter = new DefaultBandwidthMeter();
            TrackSelection.Factory audioTrackSelectionFactory = new AdaptiveTrackSelection.Factory(bandwidthMeter);
            trackSelector = new DefaultTrackSelector(audioTrackSelectionFactory);
            trackSelector.init(this);
            // 2. Create a default LoadControl. Here we can set needed buffers sizes.
            LoadControl loadControl = new DefaultLoadControl();
            _player = ExoPlayerFactory.newSimpleInstance(_context, trackSelector, loadControl);
            _player.addListener(this);
            _player.setAudioDebugListener(this);
            _player.setPlayWhenReady(true);
            userAgent = Util.getUserAgent(_context, "ExoPlayerWrapper");

            okHttpClient = new OkHttpClient.Builder()
                    .retryOnConnectionFailure(true)
                    .followRedirects(true)
                    .build();
           
            MediaSource mediaSources = buildMediaSource(Uri.parse(_streamUrl), null);
            _player.prepare(mediaSources, true, true);

```
where buildMediaSource id:
```
private MediaSource buildMediaSource(Uri uri, String overrideExtension) {
        int type = Util.inferContentType(!TextUtils.isEmpty(overrideExtension) ? "." + overrideExtension
                : !TextUtils.isEmpty(uri.getLastPathSegment()) ? uri.getLastPathSegment() : "");
        switch (type) {
            case C.TYPE_SS:
                return new SsMediaSource(uri, buildHttpDataSourceFactory(false),
                        new DefaultSsChunkSource.Factory(mediaDataSourceFactory), mainHandler, this);
            case C.TYPE_DASH:
                return new DashMediaSource(uri, buildHttpDataSourceFactory(false),
                        new DefaultDashChunkSource.Factory(mediaDataSourceFactory), mainHandler, this);
            case C.TYPE_HLS:
                return new HlsMediaSource(uri, buildHttpDataSourceFactory(false), MIN_LOAD_RETRY_COUNT, mainHandler, this);
            case C.TYPE_OTHER:
                return new ExtractorMediaSource(uri, buildHttpDataSourceFactory(false), new DefaultExtractorsFactory(),
                        MIN_LOAD_RETRY_COUNT, mainHandler, this, null);
            default: {
                throw new IllegalStateException("Unsupported type: " + type);
            }
        }
    }

```
and buildHttpDataSourceFactory is:

```
private OkHttpDataSource.Factory buildHttpDataSourceFactory(boolean useBandwidthMeter) {
        return new OkHttpDataSourceFactory(okHttpClient, userAgent, useBandwidthMeter ? BANDWIDTH_METER : null);
    }
```

It works well with WiFi. The player plays smoothly and without any interrupts. But the users are complain, that they always have the interrupts during playing. And I reproduced this behavior with HSCSD Internet connection. When I start playing, after some time I get `onAudioTrackUnderrun(...)` callback with bufferSize 44100, bufferSizeMs 250 and the 3-d argument is always different. And when I get this callback, the playing is interrupts and after 1-3 seconds of buffering, the player starts playing again. It happens very often - 1-2 times per minute. I did not try to play the stream with demo app. Help me please or explain, why I get this behavior with cellular data, but don't get it with WiFi.

**Comment by ojw28** [comment]
Most likely the type of stream you're playing just isn't robust against the connection being interrupted, and in the HSCSD case the network is being periodically interrupted. Streaming standards such as DASH, HLS and SmoothStreaming are robust against interruptions. Something like streaming an indefinite MP3 stream is not, since there's no way for the client to indicate to the server where it should resume from when re-establishing the connection.

**Comment by dim4ikhot** [comment]
Thanks for the fast reply. So the main issue is not with Exoplayer, but related with two things: 
1) From stream type.
2) From Internet connection type.
I correct understood? And if this is the case, we cannot fix, correct?

**Comment by ojw28** [comment]
It's not possible to say because you haven't provided a stream (and so we do not know what type of stream you're playing) or a way for us to reproduce the issue (which would allow us to look further). That would be my assumption though, yes.

**Comment by dim4ikhot** [comment]
Here is the stream:

http://glzwizzlv.bynetcdn.com/glz_mp3?awCollectionId=misc&awEpisodeId=glz

I do not know, how exactly to reproduce the issue. Users say, that they just press play and listen the stream via mobile network and they get interruptions in playing. And unfortunately, I can't tell how exactly often does it happen
P.S I forgot to mention that users also say, that this stream works well with TuneIn app.

**Comment by ojw28** [comment]
Right, that type of stream can't be seamlessly rejoined if the connection breaks (as far as I know). This limitation would apply to any type of network. So the remaining question is: Why does this particular type of connection appear to break frequently, and what is breaking it. I doubt it's the player if the stream is working well over WiFi, so it's more likely to be the network provider or the server.

It could be that it's possible to avoid connection drops by changing the way in which the player fetches media. In particular the way ExoPlayer tries to fetch media in bursts may cause the provider or server to terminate the connection in the idle time between the bursts. You could try increasing the minimum buffer duration in `DefaultLoadControl` to equal the maximum buffer duration, which will cause the player to request data in more of a constant trickle. We'd be interested to know if you have any success, if you try doing this.

The long term solution to this kind of thing is to use a streaming technology that does allow for seamless rejoin. Specifically DASH or HLS.

**Comment by dim4ikhot** [comment]
I tried the solution, you offered, but it did not take any effect to solve the problem. Here is what I did:

```
DefaultAllocator allocator = new DefaultAllocator(true, BUFFER_SEGMENT_SIZE);
LoadControl loadControl = new DefaultLoadControl(allocator,
                    DEFAULT_MAX_BUFFER_MS,
                    DEFAULT_MAX_BUFFER_MS,
                    DEFAULT_BUFFER_FOR_PLAYBACK_MS,
                    DEFAULT_BUFFER_FOR_PLAYBACK_AFTER_REBUFFER_MS );
            _player = ExoPlayerFactory.newSimpleInstance(context, trackSelector, loadControl);
```
where `BUFFER_SEGMENT_SIZE = 64 * 1024`. 
As I correct understood, the 2-nd argument of the `DefaultLoadControl` should be the same as 3-d argument, but I still got the interruptions. 
Then I tried to play with all arguments: I changed 2-nd and 3-d arguments to  `DEFAULT_MIN_BUFFER_MS` and the last argument to 1000. I still got the interruptions in playing, but now the player had resume faster and it sounded better, but not satisfactorily.  And I tried to increase/decrease all of the arguments, but I did not get the expected result...I always got interruptions in playing.
Does player has any other settings, which I can change to get better sound? Or the stream, which we use is not good?

**Comment by ojw28** [comment]
As above, the proper solution (and the only way to seamlessly handle connection breaks/re-connects) is to move to something like DASH or HLS.

The question as to why this type of connection appears to break frequently is still unanswered. Given the suggestions above didn't help, I think your best option if you still want to answer this question would be to dig around using Wireshark to figure out what's happening on the network (e.g. you might be able to see if the client or server is terminating the connections, and from there figure out why). Assisting with this type of investigation is beyond the scope of this issue tracker, although if you do find something interesting then we'd be keen to hear what you find!
