### ISSUE TITLE
How to request drm decryption key with key-id from decoder extension?

### ISSUE THREAD

**Issue by Frydac** [google/ExoPlayer#3047]
### Issue description

We implemented our own audio decoder as an extension to exoplayer, and created a demo of it using the exoplayer demo application. That works as intended for local files and HLS/DASH streaming.
One of our clients now wants us to support their widevine drm encryption. They already use it on content with other codecs that are part of exoplayer/android and work as intended using exoplayer.

As I understand it, in our decode function of our decoder implementation (extended from SimpleDecoder) we get an encrypted DecoderInputBuffer with a filled in cryptoInfo object from exoplayer.
As an example, I have been able to use javax.crypto.cipher to decrypt the buffer when I hardcode the actual decrypt key in there, and use that together with the initialisation vector in the cryptoInfo. (it is using AES/CTR with symmetric key-pair)

The issue I'm having is that in the filled in cryptoInfo object the key-ID is available, and I'm guessing I have to manually connect with the license server to request the actual key to decrypt with?
I am guessing I should use the DefaultDrmSessionManager for this, but I can't seem to figure out how to do this.

I can understand that this might not strictly fall under exoplayer issues, however I hope to get some pointers that set me on the right track (or some link to relevant documentation).
I'm still learning about DRM as I go, so any pointers on how DRM is supposed to work and why, are also greatly appreciated. (For example how (un)safe is it to decrypt in the java layer).

### Reproduction steps
not relevant

### Link to test content
I guess also not relevant as you don't have our decoder?

### Version of ExoPlayer being used
Our work is currently built on commit 569cec7fe tagged r2.3.0

### Device(s) and version(s) of Android being used
Currently using Huawei Nexus P6 with android 7.1.2

### A full bug report captured from the device
not relevant

**Comment by ojw28** [comment]
I don't think it's possible to write your own Widevine implementation, and as far as I know the implementation in the platform is tied to using the platform decoders. I think you'd need a software implementation of Widevine that has your decoder baked into it for such an approach to be feasible, and I don't think Widevine distributes the pieces that you'd need to build such a thing.

@wvpaf - Is there any way to make this work that I'm not aware of, given current Widevine offerings? Thanks.

**Comment by wvpaf** [comment]
Hi @Frydac, you and/or your partner should be WV partners and can get access to documentation that should make your path clearer. Please refer to http://www.widevine.com/.  If you and/or your company have already signed an agreement with WV then please reach out to your WV rep.
thanks, Paul

**Comment by Frydac** [comment]
Thanks for the information!

**Comment by gotokyle** [comment]
@Frydac hi can you plz share how you hardcoded the actual decryption key?
plz reply
thanks
