### ISSUE TITLE
Videos in viewflipper

### ISSUE THREAD

**Issue by sainer** [google/ExoPlayer#3048]
I have ViewFlipper (inflated manually form XML in activity on start) with programatically added two SimpleExoPlayerView views. I want to play two videos (about 5 sec) in these views. First video working fine but the second freezes on last frame of the first video, but sounds playing and after 5 seconds first wideo work again fine.

I use r2.4.3 Exo player.

It is my code for playing videos;

```
void playVideo(SimpleExoPlayerView currentView) {
        dataSourceFactory = new DefaultDataSourceFactory(MainApplication.context,
                Util.getUserAgent(this, "WGSplayer"), null);
        // Produces Extractor instances for parsing the media data.
        extractorsFactory = new DefaultExtractorsFactory();
        TrackSelection.Factory videoTrackSelectionFactory =
                new AdaptiveTrackSelection.Factory(null);
        trackSelector =
                new DefaultTrackSelector(videoTrackSelectionFactory);
        // 2. Create the player
        player = ExoPlayerFactory.newSimpleInstance(this, trackSelector);
        player.addListener(exoPlayerEventListener);
        currentView.setUseController(false);
        currentView.setPlayer(player);
        player.setPlayWhenReady(true);
        videoSource = new ExtractorMediaSource(Uri.parse((String) currentView.getTag()),
                dataSourceFactory, extractorsFactory, null, null);
        player.prepare(videoSource);
        player.seekTo(player.getCurrentPosition()-1);
    }
```
I launch playVideo method every time when flip occurs.

I noticed second wideo working fine but the first wideo overlap the second so there is only audio without wideo visible video. Why an overlap occurs?

**Comment by soadri** [comment]
I think your code is so heavy, the object is created in every time when flip occurs and set again
