### ISSUE TITLE
Special video cannot seek to the position ,always play from position 0

### ISSUE THREAD

**Issue by langxuelang** [google/ExoPlayer#3050]
I use the exoplayer version1.5.16,when I use "seekto" method to seek,I have found that whatever the seekto position is,the video will play from 0 position. 

added:
the version exoplayer v2 is also have this problem

This is the video link:
https://drive.google.com/open?id=0BwneL-jNaOWGbjc0SlFqMVB3aDQ

**Comment by ojw28** [comment]
Please see the note on [this page](https://google.github.io/ExoPlayer/supported-formats.html) about seeking support.
