### ISSUE TITLE
Question: How to change loopcount using LoopMediaSource on the fly

### ISSUE THREAD

**Issue by michalliu** [google/ExoPlayer#3052]
I'm currently using LoopingDataSource, Can I change the loop count while video is playing? 
For example:
The initial loop count is set to 3, while the player is playing at the 2nd loop, I want to stop **looping play the video** , not stop the video immediately. That means after the 2nd loop, the player shouldn't proceed to the 3nd loop.

**Comment by ojw28** [comment]
What's the actual use case? If you want repeat mode functionality that can be toggled on and off during playback, this is resolved in the `dev-v2` branch where there's a new `ExoPlayer.setRepeatMode` method. This will be the recommended way to control looping, except for fairly niche use cases, and will remove the need for you to use `LoopingMediaSource` if that's what you're trying to achieve.

**Comment by michalliu** [comment]
Thanks, setRepeatMode is exactly what I need. Hope the new version releasing soon.
