### ISSUE TITLE
Video plays twice (Broken edit list)

### ISSUE THREAD

**Issue by weichaoIO** [google/ExoPlayer#3055]
### Issue description
Video plays twice.

### Reproduction steps
(1) open project `ExoPlayer-release-v2`
(2) modify 
`ExoPlayer-release-v2\demo\src\main\assets\media.exolist.json`
change `https://storage.googleapis.com/exoplayer-test-media-1/gen-3/screens/dash-vod-single-segment/video-avc-baseline-480.mp4` 
to 
`http://cdn-qn.jsxfedu.com/143316ce15c308005b66787AA8DFDF5758CBC5385CEF3A6F94B.mp4?download/%E5%8C%97%E5%B8%88%E7%89%A9%E7%90%86%E5%85%AB%E4%B8%8A%E7%AC%AC%E4%B8%80%E7%AB%A0%E7%AC%AC%E4%BA%8C%E8%8A%82%E3%80%8A%E7%86%94%E5%8C%96%E5%92%8C%E5%87%9D%E5%9B%BA%E3%80%8B%E5%BE%AE%E8%AF%BE%EF%BC%88%E4%B8%80%EF%BC%894864692728784271591.mp4&e=1498814369&token=WeuWc8DJu0C32R_A35eXq5Y5-owUIRw7W7tBssd6:5bqvhMVBJf4wxeddAjRVos9T-50=&wsiphost=local`
(3) then, just play one time, it won't change to state `ExoPlayer.STATE_ENDED` for the first time until play twice. 

### Link to test content
http://cdn-qn.jsxfedu.com/143316ce15c308005b66787AA8DFDF5758CBC5385CEF3A6F94B.mp4?download/%E5%8C%97%E5%B8%88%E7%89%A9%E7%90%86%E5%85%AB%E4%B8%8A%E7%AC%AC%E4%B8%80%E7%AB%A0%E7%AC%AC%E4%BA%8C%E8%8A%82%E3%80%8A%E7%86%94%E5%8C%96%E5%92%8C%E5%87%9D%E5%9B%BA%E3%80%8B%E5%BE%AE%E8%AF%BE%EF%BC%88%E4%B8%80%EF%BC%894864692728784271591.mp4&e=1498814369&token=WeuWc8DJu0C32R_A35eXq5Y5-owUIRw7W7tBssd6:5bqvhMVBJf4wxeddAjRVos9T-50=&wsiphost=local

### Version of ExoPlayer being used
r2.4.3

### Device(s) and version(s) of Android being used
All devices I used.

### A full bug report captured from the device
Sorry, I can't understand about this.

### Others
I modified ExoPlayerImplInternal
```
        boolean allRenderersEnded = true;
        boolean allRenderersReadyOrEnded = true;
        for (Renderer renderer : enabledRenderers) {
            // TODO: Each renderer should return the maximum delay before which it wishes to be called
            // again. The minimum of these values should then be used as the delay before the next
            // invocation of this method.
            renderer.render(rendererPositionUs, elapsedRealtimeUs);
            allRenderersEnded = allRenderersEnded && renderer.isEnded();
            // Determine whether the renderer is ready (or ended). If it's not, throw an error that's
            // preventing the renderer from making progress, if such an error exists.
            boolean rendererReadyOrEnded = renderer.isReady() || renderer.isEnded();
            if (!rendererReadyOrEnded) {
                renderer.maybeThrowStreamError();
            }
            allRenderersReadyOrEnded = allRenderersReadyOrEnded && rendererReadyOrEnded;
        }
```
to
```
        boolean hasRenderersEnded = false;
        boolean allRenderersReadyOrEnded = true;
        for (Renderer renderer : enabledRenderers) {
            // TODO: Each renderer should return the maximum delay before which it wishes to be called
            // again. The minimum of these values should then be used as the delay before the next
            // invocation of this method.
            renderer.render(rendererPositionUs, elapsedRealtimeUs);
            hasRenderersEnded = hasRenderersEnded || renderer.isEnded();// TODO 取消列表内连续播放，因为部分 MP4 文件解析可能有问题，会连续播放两次。此处改为当检测到一个 MP4 播放结束后就完全结束。
//            Log.d("aaaa", "renderer.isEnded():" + renderer.isEnded());
            // Determine whether the renderer is ready (or ended). If it's not, throw an error that's
            // preventing the renderer from making progress, if such an error exists.
            boolean rendererReadyOrEnded = renderer.isReady() || renderer.isEnded();
            if (!rendererReadyOrEnded) {
                renderer.maybeThrowStreamError();
            }
            allRenderersReadyOrEnded = allRenderersReadyOrEnded && rendererReadyOrEnded;
        }
```
It can solve my problem, but it may not be support to video list.

**Comment by ojw28** [comment]
The mp4 file actually contains an edit list in just the video track that requests it be played twice. The audio track doesn't contain such an edit list, which is why the second playback doesn't have any audio.

Seems like the media is at fault to me, since it should not contain the edit list in the video track. @andrewlewis might have further insight.

**Comment by weichaoIO** [comment]
@ojw28 Thanks for you reply. I think you are right. I didn't even realize that "the second playback doesn't have any audio". 

Does my modified code has any bad effects?

**Comment by ojw28** [comment]
As far as I can see, the change you've made causes playback to end as soon as the shortest track ends, where-as currently playback ends as soon as the longest track ends.

In the general case the existing behavior is correct. Your change may cause media to finish playback prematurely in the case that the tracks are of uneven duration. If you only want to play this particular file then your change looks pretty safe, although if that's the case you'd be better off just fixing the file.
