### ISSUE TITLE
HLS Stream doesn't play

### ISSUE THREAD

**Issue by oukb** [google/ExoPlayer#3059]
Hi
I have the same problem with old and new ams.
First file from old ams
./bcdb52266de34f1e8aa5474d17b0850c_portal_MQ.mp4Frag1Num0work.ts
It's ok 
```
    ** Frames **
    Track #0 - Frames:  I P P P P P P P P P P P P P P P P P P P P P P P P P P P P P     AA: 0, BB: 0
        Good! Track starts with a keyframe
        Keyframes count: 4
        Key frame interval within track: 2.0 seconds
    Track #1 - Frames:  I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I
```
Second file from new ams - didn't work.
./bcdb52266de34f1e8aa5474d17b0850c_portal_MQ.mp4Frag1Num0dontwork.ts
```
    ** Frames **
    Track #0 - Frames:  P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P     AA: 0, BB: 0
        Warning: note this is not starting with a keyframe. This will cause not seamless bitrate switching
        Keyframes count: 3
        Key frame interval within track: 2.0 seconds
    Track #1 - Frames:  I I I I I I I I I I I I I I I I I I I I I I I I I I I I I I
```
ExoPlayer requested only playlist and first chunk.
```
1.1.1.1 - - [05/Jul/2017:13:58:36 +0300] "GET /xxx/594e8634e1485fa5798b45b1_576p.mp4.m3u8 HTTP/1.1" 200 307 "-" "test android/1.0.9 (Linux;Android 7.1.2) ExoPlayerLib/2.4.0"
1.1.1.1 - - [05/Jul/2017:13:58:36 +0300] "GET /xxx/594e8634e1485fa5798b45b1_576p.mp4Frag1Num0.ts HTTP/1.1" 200 1949760 "-" "test android/1.0.9 (Linux;Android 7.1.2) ExoPlayerLib/2.4.0"
```
[chunks.zip](https://github.com/google/ExoPlayer/files/1125302/chunks.zip)

Second stream doesn't have I-Frame. Is this problem for ExoPlayer ?

On IOS and other players and platforms plays without problem. 
[demo-noExtensions-debug.apk.zip](https://github.com/google/ExoPlayer/files/1145424/demo-noExtensions-debug.apk.zip)

**Comment by ojw28** [comment]
I don't know what "ams" is. Please clarify. I'm also confused. In the debugging above there's a clear indication that the source content is not correct (where-as the "old" file is). Shouldn't you be reporting this to whoever is generating the content, rather than here?

**Comment by oukb** [comment]
Sorry, ams - adobe media server 5.
VOD content from apache module mod_hlshttp.so

**Comment by ojw28** [comment]
You should probably report this to the AMS developers, given you're claiming it used to produce content that passed validation, and no longer does so.
