### ISSUE TITLE
HLS pause management?

### ISSUE THREAD

**Issue by encodi** [google/ExoPlayer#306]
Sorry if this already have been brought into the list or if there is a way i havent found about.

Is there a way to pause an HLS streaming with ExoPlayer at this point ? 

(UPDATE)
I think i didnt explained myself, but i found my own answer, i feel like a noob, yes it is possible to pause/resume, the problem was that i was using the exoplayer in an Amazon fire tv application so i had to handle the remote control key to the setPlayWhenReady(false/true) method

**Comment by ojw28** [comment]
I'm not sure I understand the question. The demo app has playback controls, including a pause button that pauses playback?
