### ISSUE TITLE
MediaCodec$CryptoException: Unknown Error

### ISSUE THREAD

**Issue by Gian84** [google/ExoPlayer#3064]
### Issue description
When I try to play a Widevine protected content I get a CryptoException only when EME is greater  than L2.
Devices I have used are indicated as L1, so contents should start correctly.
I know Nexus bug about securityLevel on Qualcom processor but Nexus 6P and skipper should work.
mErrorCode: -2998
detailMessage: Unknown Error
mErrorCode I get it is  not appears in docs, what does it mean?

### Reproduction steps
- set security level from license server side (EME) to L1 or L2
- try to play wv protected content from client -> ok: content starts correctly
- set security level from license server side (EME) to L3 or L5
- try to play wv protected content from client -> ko: MediaCodec$CryptoException: Unknown Error

### Link to test content
Content uri via email.

### Version of ExoPlayer being used
ExoPlayer 2.4.3

### Device(s) and version(s) of Android being used
Skipper (https://www.tim.it/tv/nuovo-decoder-timvision) - Android 6.0.1
Nexus 5 - Android 6.0.1
Nexus 6P - Android 7.1.1 (Patch securityLevel 05/01/2017)

### A full bug report captured from the device
adb bugreport via email

**Comment by wvpaf** [comment]
Unfortunately the N5 has release with an HDCP issue, from the OEM. 
This is not slated to be addressed. Recommendation is not to require HDCP on N5

**Comment by Gian84** [comment]
Thank you for the info.
Maybe I understood the problem, it was the audio stream security level.
So probably it is my error on Widevine side and not Exoplayer side, sorry and thanks again.

**Comment by Jiekai** [comment]
Hi Gian84, would you mind sharing what security level settings you set to make this work? We've been encountering the same problem.
