### ISSUE TITLE
Change Subtitles Style

### ISSUE THREAD

**Issue by hawkiq** [google/ExoPlayer#3065]
am developing simple video player with vtt subtitles
I want to change styles for captions by

      private void configureSubtitleView() {
        int defaultSubtitleColor = Color.argb(255, 218, 218, 218);
        int outlineColor = Color.argb(255, 43, 43, 43);
        Typeface subtitleTypeface = Typeface.createFromAsset(getAssets(), "fonts/droid.ttf");
        CaptionStyleCompat style =
                new CaptionStyleCompat(defaultSubtitleColor,
                        Color.TRANSPARENT, Color.TRANSPARENT,
                        CaptionStyleCompat.EDGE_TYPE_OUTLINE,
                        outlineColor, subtitleTypeface);
        subtitleLayout.setStyle(style);
        subtitleLayout.setFractionalTextSize(SubtitleView.DEFAULT_TEXT_SIZE_FRACTION * fontScale);
    }

and call it in **onCreate** method, but nothing changed. is that an issue or I have missed something.

**Comment by ojw28** [comment]
Does it help if you call `subtitleLayout.setApplyEmbeddedStyles(false)`?

**Comment by hawkiq** [comment]
I've tried it to call `subtitleLayout.setApplyEmbeddedStyles(false);` before `subtitleLayout.setStyle(style);`
but nothing changed.
implemented new method to test font size also nothing changed.

        private void incrementFontSize() {
        float fontScale = 2f;
        fontScale = Math.min(fontScale * 1.05f, 3f);
        subtitleLayout.setFractionalTextSize(SubtitleView.DEFAULT_TEXT_SIZE_FRACTION * fontScale);

        Log.i("EXOPlayer", "fontScale: " + fontScale);
    }

**Comment by hawkiq** [comment]
@ojw28 thanks for pointing me to disable default style which results to know that I have used SimpleExoPlayerView so to make changes to subtitles I must call

     simpleExoPlayerView = (SimpleExoPlayerView) findViewById(R.id.PlayerView);
     simpleExoPlayerView.getSubtitleView().setStyle(style);

thanks.
