### ISSUE TITLE
Local video prepare more time

### ISSUE THREAD

**Issue by Teviz** [google/ExoPlayer#3072]
When preparing an online video, ExoPlayer is much better than MediaPlayer obviously.
But as for a local video, MediaPlayer seems faster than ExoPlayer with hundreds of milliseconds. I test on some different devices and get the same result.
What factors may lead to this outcome and is there a way to reduce the preparing time when playing a local video?

Thanks for your time.

**Comment by ojw28** [comment]
It's very hard to understand what you're actually measuring. What are you timing from, and until, for example? How are you doing the timing? There's no reason why ExoPlayer should be any slower.

**Comment by Teviz** [comment]
Sorry for my ambiguous expression. 
What I'm timing is the preparing time when playing a video.
The reason I measure it is because the speed of rendering first frame is important to users.
Here is the MediaPlayer code:

```java
mMediaPlayer.setOnPreparedListener(new MediaPlayer.OnPreparedListener() {
    @Override
    public void onPrepared(MediaPlayer mp) {
        Log.i(TAG, "MediaPlayer ------ " + (SystemClock.uptimeMillis() - mStartTime));
        mMediaPlayer.start();
    }
});

long startTime = SystemClock.uptimeMillis()
mMediaPlayer.prepare();
```

And Here is the ExoPlayer code
```java
mExoPlayer.addListener() {new ExoPlayer.EventListener() {
        //...
        @Override
        public void onPlayerStateChanged(boolean playWhenReady, int playbackState) {
              if (playbackState == ExoPlayer.STATE_READY && !mPrepared) {
                    mPrepared = true;
                    Log.i(TAG, "ExoPlayer ------ " + (SystemClock.uptimeMillis() - mStartTime));
              }
        }
    }
}

long startTime = SystemClock.uptimeMillis()
mExoPlayer.prepare(mediaSource); //
```
onRenderedFirstFrame callback works too but still spends more time than MediaPlayer.
I don't think ExoPlayer is slower than MediaPlayer too, so I want to know is there anything I did wrong and what I can do to improve it.

**Comment by ojw28** [comment]
What values are you seeing in each case? I'm not sure that `MediaPlayer` guarantees to have rendered a frame before it invokes its `OnPreparedListener` callback. And if it doesn't guarantee that, you're effectively timing different things. It's somewhat unclear why you're measuring this, also. Do you actually perceive that ExoPlayer is slower to start when using your app? If the difference is not perceptible, it's probably not a real concern.

**Comment by Teviz** [comment]
I think it's perceptible and then I do the test. 
The first time I found that is when using cache, MediaPlayer seems to be faster.
I'm also confused too. This only happens when preparing a local video.You could also code a demo with MediaPlayer to verify.

**Comment by soadri** [comment]
What means the 'local video' ?

**Comment by AquilesCanta** [comment]
@soadri, from the context, I'd say it's stored on the device, as opposed to
>an online video

**Comment by ojw28** [comment]
Please can you provide a test file that reproduces this? There are lots of potential variables here, some of which may be content specific, so we'd really like exact and specific reproduction steps before we spend any time trying to reproduce. Thanks.

**Comment by Teviz** [comment]
@soadri @AquilesCanta 
Sorry for my ambiguous expression. The 'local video' I referred is the video file stored on the device.

**Comment by Teviz** [comment]
@ojw28 
Of course, I have sent one of the test files to dev.exoplayer@gmail.com.
Firstly, I doubt the class FileDataSource which uses RandomAccessFile to read file is the reason why prepare is slow. So I try to use class MappedByteBuffer which import from NIO to improve the performance, but it seems to behave nearly. I'm not sure is there something I did wrong.
And then I hook the every method in ExoPlayer library and found that when to play mp4, #processMoovAtom in class Mp4Extractor cost almost half of the total time. I'm not sure is there any problem too.
If you have any suggestion to help me to improve the performance when preparing the local video, please tell me. Thank you for your time.

**Comment by Teviz** [comment]
Any updates?
It seems not to be the i/o limit. Because I preload a video into memory and read the stream from memory is not better.

**Comment by ojw28** [comment]
No update; this is not particularly high priority for us to look at, as it is not a widely reported issue. We'll try and get to it at some point.

**Comment by Teviz** [comment]
Alright, in fact, I have some different opinion because start instantly is a comfortable experience.
We want to improve that, so file cache is an acceptable way, when there are some cache files, the local file prepare time will not be ignored.
Preparing local file is slower than MediaPlayer is perceptible, the phenomenon is easy to reproduce. There must be some optimization for the start time when preparing the local file but regret that it's not in your plan.
Anyway, thank you for your time. ExoPlayer helped us a lot, I hope it will be better sincerely. If there are some usable time for you, I think that point may be considered.

**Comment by subu1** [comment]
Encrypted Downloaded video taking too much time on starting(2 hours video 400 mb) But small size video prepared fastly (150 mb below)

**Comment by ojw28** [comment]
I'm going to close this as not reproducible. I tried playing the sample video provided on a Galaxy S8. I couldn't perceive any difference, and we don't see many (any?) other reports of this issue. On my Galaxy S8 the time to the first frame hitting the display was consistently under ~200ms total, which seems inconsistent with:

> MediaPlayer seems faster than ExoPlayer with hundreds of milliseconds

If you want us to take a more detailed look, I think the onus is on you to provide more concrete evidence (e.g. a sample app that hooks up `MediaPlayer` and `ExoPlayer` and more clearly demonstrates the problem compared to what has been provided so far on this issue). If you're willing to do that, please do so and we'd love to take a look.

A few additional points:

* We have enabled significant improvements to initialization time for playbacks other than the first one via codec reuse. [See this blog post](https://medium.com/google-exoplayer/improved-decoder-reuse-in-exoplayer-ef4c6d99591d) for details.
* A further improvement that will help with initialization time for the initial playback is tracked by https://github.com/google/ExoPlayer/issues/5796. https://github.com/google/ExoPlayer/issues/5795 may also help in certain more specific use cases.
* https://github.com/google/ExoPlayer/issues/3326 is tracking slower startup of audio playbacks when using ExoPlayer V2 compared to V1, although I think that's only tangentially related.
