### ISSUE TITLE
 r2.4.3 Error converting bytecode to dex

### ISSUE THREAD

**Issue by c3stream** [google/ExoPlayer#3078]
compileSdkVersion 26
buildToolsVersion "26.0.0"
exoPlayerVerion = 'r2.4.3'

> Error:Error converting bytecode to dex:
> Cause: com.android.dex.DexException: Multiple dex files define Lcom/google/android/exoplayer2/source/hls/playlist/HlsPlaylistTracker$PrimaryPlaylistListener;
> Error:com.android.dex.DexException: Multiple dex files define Lcom/google/android/exoplayer2/source/hls/playlist/HlsPlaylistTracker$PrimaryPlaylistListener;
> Error:	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:661)
> Error:	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:616)
> Error:	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:598)
> Error:	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
> Error:	at com.android.dx.merge.DexMerger.merge(DexMerger.java:198)
> Error:	at com.android.builder.dexing.DexArchiveMergerCallable.call(DexArchiveMergerCallable.java:60)
> Error:	at com.android.builder.dexing.DexArchiveMergerCallable.call(DexArchiveMergerCallable.java:36)
> Error:	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
> Error:	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
> Error:	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
> Error:	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
> Error:	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
> Error:Execution failed for task ':app:transformDexArchiveWithDexMergerForDebug'.
> > com.android.build.api.transform.TransformException: com.android.dex.DexException: Multiple dex files define Lcom/google/android/exoplayer2/source/hls/playlist/HlsPlaylistTracker$PrimaryPlaylistListener;

**Comment by ghost** [comment]
Have you clean your project ?? 
Seems like you have 2 different versions ....
