### ISSUE TITLE
issues while playing video on different android OS

### ISSUE THREAD

**Issue by hawkiq** [google/ExoPlayer#3081]
hello guys am having issue playing some type of videos on devices below Android Nougat, I was testing playing video on my phone **Galaxy S7 Nougat** so I didn't face any problem, then transferred app to my friend's phone and he cannot play all videos I have, here is video info if it can help to solve my issue.

**this info for file works in Nougat and not work in other devices**

    General
    Complete name                            : C:\Users\lenovo\Downloads\Video\myvideo.mp4
    Format                                   : MPEG-4
    Format profile                           : Base Media
    Codec ID                                 : isom (isom/iso2/avc1/mp41)
    File size                                : 236 MiB
    Duration                                 : 53 min 38 s
    Overall bit rate                         : 614 kb/s
    Writing application                      : Lavf56.36.100
    
    Video
    ID                                       : 1
    Format                                   : AVC
    Format/Info                              : Advanced Video Codec
    Format profile                           : High@L3
    Format settings, CABAC                   : Yes
    Format settings, RefFrames               : 4 frames
    Codec ID                                 : avc1
    Codec ID/Info                            : Advanced Video Coding
    Duration                                 : 53 min 38 s
    Bit rate                                 : 448 kb/s
    Width                                    : 854 pixels
    Height                                   : 480 pixels
    Display aspect ratio                     : 16:9
    Frame rate mode                          : Constant
    Frame rate                               : 23.976 (24000/1001) FPS
    Color space                              : YUV
    Chroma subsampling                       : 4:2:0
    Bit depth                                : 8 bits
    Scan type                                : Progressive
    Bits/(Pixel*Frame)                       : 0.046
    Stream size                              : 172 MiB (73%)
    Writing library                          : x264 core 146 r2555 0c21480
    Encoding settings                        : cabac=1 / ref=3 / deblock=1:0:0 / analyse=0x3:0x113 / me=hex /     subme=7 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=1 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=12 /     lookahead_threads=2 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=3 / b_pyramid=2 / b_adapt=1 / b_bias=0 / direct=1 / weightb=1 / open_gop=0 / weightp=2 / keyint=250 / keyint_min=23 / scenecut=40 / intra_refresh=0 / rc_lookahead=40 / rc=crf / mbtree=1 / crf=23.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / ip_ratio=1.40 / aq=1:1.00

    Audio
    ID                                       : 2
    Format                                   : AAC
    Format/Info                              : Advanced Audio Codec
    Format profile                           : LC
    Codec ID                                 : 40
    Duration                                 : 53 min 38 s
    Bit rate mode                            : Constant
    Bit rate                                 : 160 kb/s
    Channel(s)                               : 2 channels
    Channel(s)_Original                      : 6 channels
    Channel positions                        : Front: L C R, Side: L R, LFE
    Sampling rate                            : 48.0 kHz
    Frame rate                               : 46.875 FPS (1024 SPF)
    Compression mode                         : Lossy
    Stream size                              : 61.5 MiB (26%)
    Default                                  : Yes
    Alternate group                          : 1

**and this info for video that works on all devices.**

```
General
Complete name                            : C:\Users\sa lenovo\Downloads\Video\myvideo01.mp4
Format                                   : MPEG-4
Format profile                           : Base Media
Codec ID                                 : isom (isom/iso2/avc1/mp41)
File size                                : 149 MiB
Duration                                 : 44 min 32 s
Overall bit rate                         : 468 kb/s
Writing application                      : Lavf56.36.100

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L2.1
Format settings, CABAC                   : Yes
Format settings, RefFrames               : 4 frames
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 44 min 32 s
Bit rate                                 : 303 kb/s
Width                                    : 480 pixels
Height                                   : 360 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 23.976 (24000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.073
Stream size                              : 96.4 MiB (65%)
Writing library                          : x264 core 146 r2555 0c21480
Encoding settings                        : cabac=1 / ref=3 / deblock=1:0:0 / analyse=0x3:0x113 / me=hex / subme=7 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=1 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=12 / lookahead_threads=2 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=3 / b_pyramid=2 / b_adapt=1 / b_bias=0 / direct=1 / weightb=1 / open_gop=0 / weightp=2 / keyint=250 / keyint_min=23 / scenecut=40 / intra_refresh=0 / rc_lookahead=40 / rc=crf / mbtree=1 / crf=23.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / ip_ratio=1.40 / aq=1:1.00
Language                                 : English

Audio
ID                                       : 2
Format                                   : AAC
Format/Info                              : Advanced Audio Codec
Format profile                           : LC
Codec ID                                 : 40
Duration                                 : 44 min 32 s
Bit rate mode                            : Constant
Bit rate                                 : 160 kb/s
Channel(s)                               : 2 channels
Channel(s)_Original                      : 6 channels
Channel positions                        : Front: L C R, Side: L R, LFE
Sampling rate                            : 48.0 kHz
Frame rate                               : 46.875 FPS (1024 SPF)
Compression mode                         : Lossy
Stream size                              : 51.0 MiB (34%)
Default                                  : Yes
Alternate group                          : 1
```

**Comment by ojw28** [comment]
What type of phone is your friend's phone, given that's the one where the media isn't playable ;)...?

**Comment by hawkiq** [comment]
@ojw28 I've tested on two phones right now and problem still exist , my friend's phone is **Galaxy Note 5** running lollipop 5.1  and  **huawei**

**Comment by ojw28** [comment]
Please provide complete information about the problematic devices, as requested in the issue template (e.g. a bug report captured from that device). What actually happens when you try to play the content?

It's quite likely the problematic phones just don't support decoding of AVC High@L3 video streams.

**Comment by hawkiq** [comment]
@ojw28  this log captured by android monitor for device Samsung SM-G903M using android 6.0
```
07-19 21:48:59.531 25805-29870/iq.osamasw.maplayer I/ACodec: [OMX.Exynos.avc.dec] configureOutputBuffersFromNativeWindow setBufferCount : 15, minUndequeuedBuffers : 4
07-19 21:48:59.531 25805-29870/iq.osamasw.maplayer I/ACodec: [OMX.Exynos.avc.dec] allocated meta buffer with ID 0xad812150 (pointer = 0x9d994000)
07-19 21:48:59.531 25805-29870/iq.osamasw.maplayer I/ACodec: [OMX.Exynos.avc.dec] allocated meta buffer with ID 0xad809560 (pointer = 0x9d994020)
07-19 21:48:59.531 25805-29870/iq.osamasw.maplayer I/ACodec: [OMX.Exynos.avc.dec] allocated meta buffer with ID 0xad809e70 (pointer = 0x9d994040)
07-19 21:48:59.531 25805-29870/iq.osamasw.maplayer I/ACodec: [OMX.Exynos.avc.dec] allocated meta buffer with ID 0xad820f10 (pointer = 0x9d994060)
07-19 21:48:59.531 25805-29870/iq.osamasw.maplayer I/ACodec: [OMX.Exynos.avc.dec] allocated meta buffer with ID 0xad80e790 (pointer = 0x9d994080)
07-19 21:48:59.531 25805-29870/iq.osamasw.maplayer I/ACodec: [OMX.Exynos.avc.dec] allocated meta buffer with ID 0xad8099c0 (pointer = 0x9d9940a0)
07-19 21:48:59.531 25805-29870/iq.osamasw.maplayer I/ACodec: [OMX.Exynos.avc.dec] allocated meta buffer with ID 0xb0e11fb0 (pointer = 0x9d9940c0)
07-19 21:48:59.531 25805-29870/iq.osamasw.maplayer I/ACodec: [OMX.Exynos.avc.dec] allocated meta buffer with ID 0xb0e11650 (pointer = 0x9d9940e0)
07-19 21:48:59.536 25805-29870/iq.osamasw.maplayer I/ACodec: [OMX.Exynos.avc.dec] allocated meta buffer with ID 0xad80e8d0 (pointer = 0x9d994100)
07-19 21:48:59.536 25805-29870/iq.osamasw.maplayer I/ACodec: [OMX.Exynos.avc.dec] allocated meta buffer with ID 0xad809b50 (pointer = 0x9d994120)
07-19 21:48:59.536 25805-29870/iq.osamasw.maplayer I/ACodec: [OMX.Exynos.avc.dec] allocated meta buffer with ID 0xad80ed80 (pointer = 0x9d994140)
07-19 21:48:59.536 25805-29870/iq.osamasw.maplayer I/ACodec: [OMX.Exynos.avc.dec] allocated meta buffer with ID 0xad821830 (pointer = 0x9d994160)
07-19 21:48:59.536 25805-29870/iq.osamasw.maplayer I/ACodec: [OMX.Exynos.avc.dec] allocated meta buffer with ID 0xb0855880 (pointer = 0x9d994180)
07-19 21:48:59.536 25805-29870/iq.osamasw.maplayer I/ACodec: [OMX.Exynos.avc.dec] allocated meta buffer with ID 0xad821600 (pointer = 0x9d9941a0)
07-19 21:48:59.536 25805-29870/iq.osamasw.maplayer I/ACodec: [OMX.Exynos.avc.dec] allocated meta buffer with ID 0xad812650 (pointer = 0x9d9941c0)
07-19 21:48:59.766 25805-29870/iq.osamasw.maplayer W/ACodec: do not know color format 0x7fc00002 = 2143289346
07-19 21:49:06.036 25805-29868/iq.osamasw.maplayer I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
07-19 21:49:06.041 25805-29868/iq.osamasw.maplayer I/System.out: KnoxVpnUidStorageknoxVpnSupported API value returned is false
07-19 21:49:07.696 25805-29868/iq.osamasw.maplayer I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
07-19 21:49:07.696 25805-29868/iq.osamasw.maplayer I/System.out: KnoxVpnUidStorageknoxVpnSupported API value returned is false
07-19 21:49:11.461 25805-29868/iq.osamasw.maplayer I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
07-19 21:49:11.466 25805-29868/iq.osamasw.maplayer I/System.out: KnoxVpnUidStorageknoxVpnSupported API value returned is false
07-19 21:49:11.931 25805-29619/iq.osamasw.maplayer E/ExoPlayerImplInternal: Source error.
                                                                            com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 404
                                                                                at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:211)
                                                                                at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:123)
                                                                                at com.google.android.exoplayer2.source.SingleSampleMediaPeriod$SourceLoadable.load(SingleSampleMediaPeriod.java:275)
                                                                                at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                at java.lang.Thread.run(Thread.java:818)
07-19 21:49:11.961 25805-29870/iq.osamasw.maplayer I/ACodec:  [OMX.Exynos.avc.dec] Now uninitialized
                                                             
                                                             [ 07-19 21:49:11.966  2567:29885 I/         ]
                                                             SAACD_COMP_Reset() in
07-19 21:49:11.981 25805-29879/iq.osamasw.maplayer I/ACodec:  [OMX.SEC.aac.dec] Now uninitialized
```

**Comment by ojw28** [comment]
`InvalidResponseCodeException: Response code: 404` is just an HTTP 404. This isn't player error.

**Comment by hawkiq** [comment]
@ojw28 but the file is found and works on my phone Galaxy S7 Nougat, I saw the error and thought link for file is invalid but when its worked on my phone I sent log here.

**Comment by hawkiq** [comment]
@ojw28 I've managed to know what was the problem and it was like you said its not player's fault 👍 
it was because of **subtitle file** not video, it was contain a **space** in link so it wasn't readable in devices pre Nougat, i think I've missed to handle the error. I've fixed links for subtitles and it was fine to play all videos in all devices .
