### ISSUE TITLE
How to properly disregard PTS timestamps when playing MPEG TS streams?

### ISSUE THREAD

**Issue by hrvach** [google/ExoPlayer#3082]
### 1. How to properly disregard PTS timestamps when playing MPEG TS streams?

I am trying to implement trick play from a RTSP streamer, which is basically an i-frame only stream. As it's generated on the fly, presentation timestamps and faulty continuity counters need to be ignored and images displayed upon arrival. What would be the way to go in implementing this? 

### 2. How to disable audio track?
What is the proper way to disable an audio track in a mpeg transport stream? Not mute, but disable it altogether from playback, leaving only video playing?

_Version of ExoPlayer being used - Exoplayer2, r2.4.3_

**Comment by ojw28** [comment]
Implementing support for HLS trick play is tracked by https://github.com/google/ExoPlayer/issues/474. It's not something we've had a chance to think about yet, unfortunately. Please follow that issue for updates.
