### ISSUE TITLE
SmoothStreaming Playready LicenseNonce failed

### ISSUE THREAD

**Issue by ChrisPuissant** [google/ExoPlayer#3088]
### Issue description
**Context:**
Device is AndroidTV.
Using the ExoPlayer demo app, SmoothStreaming Playready demo video is working correctly so Playready support is implemented on the device.

**My case:**
Now with my test video, I use same demo app.
Test video is Playready encrypted SmoothStreaming and working on other non Android device.
License server I use does not send LicenseNOnce as server admin told me that SimpleNonPersistentLicense Class which was resending LicenceNonce is deprecated and removed from PlayReady Server SDK.

![sans-titre](https://user-images.githubusercontent.com/2690334/28472273-3c674aca-6e40-11e7-926d-8353b592e59a.png)

So I get this error message: 

```
07-21 17:49:09.877 142-606/? E/PlayReadyUtil: Cannot find <LicenseNonce>
07-21 17:49:09.877 142-606/? E/PlayReadySession: Cannot extract nonce
07-21 17:49:09.877 142-606/? E/PlayReadySessionManager: PlayReadySessionManager::processResponse() failed
07-21 17:49:09.878 28279-4684/com.google.android.exoplayer2.demo E/MediaDrm-JNI: Illegal state exception: Failed to handle key response: Unsupported scheme or data format (-2006)
07-21 17:49:09.882 28279-28279/com.google.android.exoplayer2.demo E/EventLogger: internalError [2.78, drmSessionManagerError]
                                                                                 android.media.MediaDrm$MediaDrmStateException: Failed to handle key response: Unsupported scheme or data format
                                                                                     at android.media.MediaDrm.provideKeyResponse(Native Method)
                                                                                     at com.google.android.exoplayer2.drm.FrameworkMediaDrm.provideKeyResponse(FrameworkMediaDrm.java:104)
                                                                                     at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.onKeyResponse(DefaultDrmSessionManager.java:582)
                                                                                     at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.access$900(DefaultDrmSessionManager.java:51)
                                                                                     at com.google.android.exoplayer2.drm.DefaultDrmSessionManager$PostResponseHandler.handleMessage(DefaultDrmSessionManager.java:687)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                     at android.os.Looper.loop(Looper.java:135)
                                                                                     at android.os.HandlerThread.run(HandlerThread.java:61)
```

Here is the keyrequest send by Exoplayer:
```
<?xml version="1.0" encoding="UTF-8"?>
<soap:Envelope 
    xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" 
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <soap:Body>
        <AcquireLicense 
            xmlns="http://schemas.microsoft.com/DRM/2007/03/protocols">
            <challenge>
                <Challenge 
                    xmlns="http://schemas.microsoft.com/DRM/2007/03/protocols/messages">
                    <LA 
                        xmlns="http://schemas.microsoft.com/DRM/2007/03/protocols" Id="SignedData" xml:space="preserve">
                        <Version>1</Version>
                        <ContentHeader>
                            <WRMHEADER 
                                xmlns="http://schemas.microsoft.com/DRM/2007/03/PlayReadyHeader" version="4.0.0.0">
                                <DATA>
                                    <PROTECTINFO>
                                        <KEYLEN>16</KEYLEN>
                                        <ALGID>AESCTR</ALGID>
                                    </PROTECTINFO>
                                    <KID>mrrpwdQ2T0qhsJ1QAFmvOQ==</KID>
                                    <CHECKSUM>Zu2aX4tTMrs=</CHECKSUM>
                                    <LA_URL>***PRIVATE****</LA_URL>
                                    <CUSTOMATTRIBUTES>
                                        <IIS_DRM_VERSION>7.1.1565.21</IIS_DRM_VERSION>
                                    </CUSTOMATTRIBUTES>
                                </DATA>
                            </WRMHEADER>
                        </ContentHeader>
                        <CLIENTINFO>
                            <CLIENTVERSION>2.5.0.1788</CLIENTVERSION>
                        </CLIENTINFO>
                        <RevocationLists>
                            <RevListInfo>
                                <ListID>ioydTlK2p0WXkWklprR5Hw==</ListID>
                                <Version>11</Version>
                            </RevListInfo>
                            <RevListInfo>
                                <ListID>gC4IKKPHsUCCVhnlttibJw==</ListID>
                                <Version>11</Version>
                            </RevListInfo>
                            <RevListInfo>
                                <ListID>BOZ1zT1UnEqfCf5tJOi/kA==</ListID>
                                <Version>12</Version>
                            </RevListInfo>
                            <RevListInfo>
                                <ListID>Ef/RUojT3U6Ct2jqTCChbA==</ListID>
                                <Version>35</Version>
                            </RevListInfo>
                        </RevocationLists>
                        <CustomData>&amp;lt;LicenseRequest&amp;gt;&amp;lt;LicenseType&amp;gt;NonPersistent&amp;lt;/LicenseType&amp;gt;&amp;lt;AnalogOutputProtectionLevel&amp;gt;200&amp;lt;/AnalogOutputProtectionLevel&amp;gt;&amp;lt;DigitalOutputProtectionLevel&amp;gt;300&amp;lt;/DigitalOutputProtectionLevel&amp;gt;&amp;lt;AnalogVideoProtectionLevel&amp;gt;150&amp;lt;/AnalogVideoProtectionLevel&amp;gt;&amp;lt;DigitalVideoProtectionLevel&amp;gt;250&amp;lt;/DigitalVideoProtectionLevel&amp;gt;&amp;lt;ExpirationUtcDateTime&amp;gt;2017-08-04T11:02:53+0200&amp;lt;/ExpirationUtcDateTime&amp;gt;&amp;lt;FirstPlayExpiration&amp;gt;P150D&amp;lt;/FirstPlayExpiration&amp;gt;&amp;lt;/LicenseRequest&amp;gt;</CustomData>
                        <LicenseNonce>J1WQLTaV8+X+LqI1e1dnVg==</LicenseNonce>
                        <EncryptedData 
                            xmlns="http://www.w3.org/2001/04/xmlenc#" Type="http://www.w3.org/2001/04/xmlenc#Element">
                            <EncryptionMethod Algorithm="http://www.w3.org/2001/04/xmlenc#aes128-cbc" />
                            <KeyInfo 
                                xmlns="http://www.w3.org/2000/09/xmldsig#">
                                <EncryptedKey 
                                    xmlns="http://www.w3.org/2001/04/xmlenc#">
                                    <EncryptionMethod Algorithm="http://schemas.microsoft.com/DRM/2007/03/protocols#ecc256" />
                                    <KeyInfo 
                                        xmlns="http://www.w3.org/2000/09/xmldsig#">
                                        <KeyName>WMRMServer</KeyName>
                                    </KeyInfo>
                                    <CipherData>
                                        <CipherValue>TrI33EPlN0od88NhZgBAhWMG85DUb1PV4x7pBZDmwl0/vFIvl1CckuxAoRtVwNNVFlfiNiX6K1Q1nhX7DGXqOdA664CIK7/OwdlpBYb+9QXZMdgholjJMhLkxtjwLWQRW1wwA1w2H+1QqEJXcFUt/VbbO1d4iAUsvkDz2pBGyOQ=</CipherValue>
                                    </CipherData>
                                </EncryptedKey>
                            </KeyInfo>
                            <CipherData>
                                <CipherValue>rcN5+sUBEl1p32JE+xaQ9Qbc4LxoZcu5umSI2hTTjzfqr6h7uKJ/qbkvDWY/7sySI3MH9VMqieqKEy5aumh9gUHTpQVAGLlMbflbEBlwUHKDUYct2cAk3FvU6WkhqSP6UOPtNmfaUwjiKpYJTJLCIBJ55GtMVqQ1pZy/sPLgKSYgXz+7xayIETsuaGMhJqTXTKPbzGzVAbaANDsMPZHkknW4QajfbhaH2Qa5Ms4V72gcrpxSP8IUDt9/Tml1efzvV9nGg4bKu78apRwsGWHYXJe019dFOjYbfQsLFFOBdC/AwN5g5IFwyquuQOplDyNFvMIXGBea9G58yhGqfIvSNxhLw8pj/MJlaphcMjjEHTxGmP27GM4+emUjGdo4ozQLhw0AQIhHmjg918hx95+B2KK3EZ0C07A2kTvVhHIrW+9z0Nr1vlhN95NLwsbj4piXUZ5futTA8HGvd/IGkl43GngXHR36p9TCE9Ey2EiND8C59errXowgmV9Q/+I0LSqdmHRAQQ0I4tSjY7qZ51lcZBrXJ8m18Y4i3UeqMmhrnSpxCsiMqBtwf5hiBbIwc7hHw9/aDI69pdLtqz2mu0rKeNb6X5eN8q0QQf8l8huwjElL5EhPqSiZuMgfDCt+ZnvsWGL2EH0QC/EAa+P+cddSujHhDtxsxiSAwP9FtIvofr3UQIgX5Y4aYvIDMdzrAbzBAtkX9EiGdb+zpGoD7C0kxqK07Nv3NTaK7FzeIEwg5viXOzR921GFJHCjXl0FXzePSFtuLA6pw9y6Dg23qPEEHX719ZEmOvsCNZP25v9twWm0w03QTaHqMNAmzpNEO5YBuN1HSf7eSsPwM51EjrAJU7XD+/hIWWPTmjV9sY+4LLUJlz9dXORB/CWiP30tqRwYsLGPmjdrnQyzNNn5mji3IcrFSEEyjcItSoBJsJFdDunJQjpIbDkQiGDgZsBIcGYvBnGAHhpPPEiHnEyeOF2hQuDNXSykuiVnMGrWrlh5v+8/PrfwwMEhHHftu5lvIsIOJ7r9rhEaD/d0Nv1zCSvbUORdpB5q049QuPNbOQFa8smUyjpFirRmqLxo4qQFd6kDor+kyUlSlHXKgUOCqXcvExoGphksHBm0r9v3KAMHRkK8Lz9EZa0nW4PFhry41wMole+v9TsnW+QXNUCh2jHwRWjSFlrn0DhFbyzYenda8GAtXwo4y0WBCmG62rsw2hQ/+ZXbgNMdiV3R4BAFuhPO5TfxSlwNpkK3q+xG13ePOo0nT9zh82x68WCGmrlMAZqHvijzQZqHy0u34sn+8qVSZYQXJ96c4SRscg1oL5kJGU1277Z1OG4u/Vk7HLqb0LW/9twthDcwqwUocOB6lXAlIwBWkqXnfLT0QFuo1aN4yG7ZXWTPAH8o31sQSmslg3yptMsYbZFnMrzRa2c2n7KBXtYIJh4AOfGwfZVBUz3x+gKNWD7qVtoXq04Ea8bg7So+Q3z48SMBXpM+LMZ7XT22rB16M4ed83GKrzwaWnmu4JcIs9HmFdS+GUgTJ7w4ilCH9MT2dsCNezvOYN4ueDwxFTyw+QCtTSoPrhd6FB8sg6m91sSI3sdQmAn4Q3cQa+EjEuGAyD6oyB44JPihzAPKHPxx2PZVZSoauCnkm6dFPNuUKnsivxH0gj/NqKIB+8LNCdn8wWSwvdR0cYnxhUu8K2wqG19jaBlTQRGCwtv7QrGYhckBNvnpIdBr+eff1PtrA41i83abM/mb99GN8vH2VuO8y3pmlt2w4gr+xvzoCmQwqMuDf7H1/iLOYCXltOpzf9stTwSJVJtZ4X/uNzBA5/zdHpboXncfiFSzYOYGnjpFkLBcu6//zhQj6o/uboHb0vHuHeO2/R0h9oRBIp73BgJ4AMirEA74y7hherTCKoQEm/M/D48m+vfRyzJGsVIo3aclwZmEXsFuxMcQLVmCcbGXOViM0m15l4x9SKhIETp1MlVN3iuEwWDXEJHKg59ayHGdgYrzf0mv3yejuLEx8kT/y04fROG2W7aJYQLtTUMaQhAlX3NRbGcj7riPGCHQtOPc2iszGKlzmI4b7hKwZLHjA/J9gB7IqQuQZ5TDepEs94X8ynqDkWu/ThlDbgF10Ghebq0MltKHRuMS9gYo3aSsSOA9zywxl33wZbRW/XQm1wNvU3UBGeKdLw6dMYupJ42cgQFdEfNSU/yJw5ZZRoWlZv2UNzDBL1e+q4LXZAYBJQAyk+ue8L5qrunL72XxSYvzFMfi/sa8sdCx34FdbFbv4LJWiCtlyYnsdaf9qxqqpbofN17aFFlW1ixWLltInpyiPGv7u9xbMIZXMEoHAKnJzE2QiLIi0ih+ZVm7vwVhPfcRwyCxMAkUW126ibN3XXr1GwAJeeG1dm2cZGSHJeOh0uxuJcM+v6ZYr1MKbT/8vm2grLrV8zsQac1afaOei4chl99fLQ4zaN9yny4qjIboZhu9RsRZCIoBuLRtnheXZyOI4ckzVcuGRhb2CWMrf9muGAtLAfCW5efNwXgy90Ek19X9Z00rvpbsp7hAgLhKvTtJEz/qbRrHq+CHQvNez2S4mdqum6xIkRN2Hbzm6ke/9sst9wu6QnBWRD3u8H+IGBMV0ihvjqH0MhRViC4Yy8E30aV7+czpai44spL0jY9vm9j6XN7A4BhRQjhA0HFfo/UnJdMq+DGLAEoyAfrKhY1BdPaSIXMWEQdsGt787krpdDxDCiuE6nSUet+ndZMIp8697Vuh/rx/1CQdR4hmf805JlDUPErXP7tKTGhyMVeDFCfefzTQZNJRzw6cTW6i9XedidyIT6VOF42yqZrQw/e20ohsIc69wRmgejgkS+XdzIMfHXOCObFFCcplmfSyKPCw+07OpaetFgFTZ3bfcsq3g2u4P+Vo0vbPtAwSKgtgLiApEJfanBcDaHwA4FviWeMtZRUxaJawxl+EG08k3TzUiWeYqDFuQa6RMXhDVVNyMHLlg12X0DlPJFhbagB6AeCj7GOyPOnymBtfo3FXjmvb5Lbm6KFDR7u/d60VaKeX4FXN/GK4BeL78UUN7nyLjMhna+cuTrqYN23sCopRyL5RRMeDqN0N+6pOAz3ac6aplpn2zC6vN4VV6X8gOKF1OVHoUMMRG+EN+CvEMCANTI6RTHTFD8Mn0GBTeujTbihupns2dxP6TTq/98oQwgNSoz/sKvBM1f9cplZD 8cRBmkJu3fRJoB9+rbSpc2scKPCthxdHMxl/Omw4sj4+CfInzkOL6GnvIsX2THRSSygZ554ro38gSe13OdaBVnXEQik8apPWB6xx5P+E0oGOLSOeSwj8VDFMvSx8UxS/HOUTsrLH+zkv3E2ijeBTHGSWAoyXc2RqnyuoYzX+MgnsRk5mihtDy1Qxg7E5BYghGxo3K1wZrLpPPnmoR3aweuEKkEyLuBspg3irYQUv7WvjLTk=</CipherValue>
                            </CipherData>
                        </EncryptedData>
                    </LA>
                    <Signature 
                        xmlns="http://www.w3.org/2000/09/xmldsig#">
                        <SignedInfo>
                            <CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315" />
                            <SignatureMethod Algorithm="http://schemas.microsoft.com/DRM/2007/03/protocols#ecdsa-sha256" />
                            <Reference URI="#SignedData">
                                <DigestMethod Algorithm="http://schemas.microsoft.com/DRM/2007/03/protocols#sha256" />
                                <DigestValue>ebbhhgt22OdNWqM8pwjOSv7sTt6I3pPbpl0J7FRnwH8=</DigestValue>
                            </Reference>
                        </SignedInfo>
                        <SignatureValue>r8cshogs8x+4dxxTRuHeQ+pMgF8VnbSPXaEHf2la7dm8cFV8zSiNIzzi/Eb0se669J8LjJyFRl2D76RIPJFGbw==</SignatureValue>
                        <KeyInfo xmlns="http://www.w3.org/2000/09/xmldsig#">
                            <KeyValue>
                                <ECCKeyValue>
                                    <PublicKey>lchfScMWZr1gX2fZ9/6XIgJ62y2W/QXnPkGz4v76B5xT917E0MebgrRVdJk6peCnUMGvT+vtzjwRHRugpx/Sbg==</PublicKey>
                                </ECCKeyValue>
                            </KeyValue>
                        </KeyInfo>
                    </Signature>
                </Challenge>
            </challenge>
        </AcquireLicense>
    </soap:Body>
</soap:Envelope>
```

Here is the license server response:
```
<?xml version="1.0" encoding="UTF-8"?>
<soap:Envelope 
    xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" 
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <soap:Body>
        <AcquireLicenseResponse 
            xmlns="http://schemas.microsoft.com/DRM/2007/03/protocols">
            <AcquireLicenseResult>
                <Response 
                    xmlns="http://schemas.microsoft.com/DRM/2007/03/protocols/messages">
                    <LicenseResponse 
                        xmlns="http://schemas.microsoft.com/DRM/2007/03/protocols">
                        <Version>1</Version>
                        <Licenses>
                            <License>WE1SAAAAAAMnVZAtNpXz5f4uojV7V2dWAAMAAQAAAcIAAgAEAAAAegACADYAAAAgAAAAOQAAABhWwkCjQQlMTa0dC2c1wMskAAIANgAAACAAAAA5AAAAGAsDhdZPD6ZDu601bx6gBJoAAgA2AAAAIAAAADkAAAAY2CdmeKbCvkSPiAiuJVsBpwABAAUAAAASAAAA+gCWAAAAAAADAAIAAAAyAAAADQAAAAoAAQABADIAAAAMAAAAIwABADQAAAAKB9AAAAAzAAAACgABAAMACQAAAPIAAQAKAAAAnpq66cHUNk9KobCdUABZrzkAAQADAIDhOpjAdeaV0gat0zcZc7d36RfZY4SKginmUlPg9KFzdvrPEkH+OW1l7t0uruE6nhqWc4XgNnsUEvgVaLlNx2XJnNcPbrw981l+6gj2ItPGGXfGFyUuTD1/gtovje5msT3KtpyD85kR+d
 +mltJ478moS/kneV8aro2CA62OtliO0wAAACoAAABMAAEAQJz82L001gMqFB7eIcK3CYGB1Y1QEmee7wEw+yMwLFKfHHgGqlVjG5MvcvEpqMMYweT3w71Uq75MepR0Ly3OoPUAAQALAAAAHAABABBMRw/pwmhQ/NXosYEUKnXI</License>
                        </Licenses>
                        <CustomData>99cd08f2-8162-e9f0-8bbd-b62c3cf7eb54|&amp;lt;LicenseRequest&amp;gt;&amp;lt;LicenseType&amp;gt;NonPersistent&amp;lt;/LicenseType&amp;gt;&amp;lt;AnalogOutputProtectionLevel&amp;gt;200&amp;lt;/AnalogOutputProtectionLevel&amp;gt;&amp;lt;DigitalOutputProtectionLevel&amp;gt;300&amp;lt;/DigitalOutputProtectionLevel&amp;gt;&amp;lt;AnalogVideoProtectionLevel&amp;gt;150&amp;lt;/AnalogVideoProtectionLevel&amp;gt;&amp;lt;DigitalVideoProtectionLevel&amp;gt;250&amp;lt;/DigitalVideoProtectionLevel&amp;gt;&amp;lt;ExpirationUtcDateTime&amp;gt;2017-08-04T11:02:53+0200&amp;lt;/ExpirationUtcDateTime&amp;gt;&amp;lt;FirstPlayExpiration&amp;gt;P150D&amp;lt;/FirstPlayExpiration&amp;gt;&amp;lt;/LicenseRequest&amp;gt;</CustomData>
                        <Acknowledgement>
                            <TransactionID>b9f56c8c-654f-4da0-b4ca-eba67d2ee609</TransactionID>
                        </Acknowledgement>
                    </LicenseResponse>
                </Response>
            </AcquireLicenseResult>
        </AcquireLicenseResponse>
    </soap:Body>
</soap:Envelope>
```

### Version of ExoPlayer being used
v2.4.4

### Device(s) and version(s) of Android being used
Android TV 5.1.1

**Comment by ojw28** [comment]
I don't think this is an ExoPlayer issue. You're effectively communicating directly with the underlying PlayReady CDM on the device. ExoPlayer is only an intermediary that's passing your communication through.

The PlayReady CDM does not like the format of your license response, and there is nothing we can do to fix that. You'll need to figure out how the license server can send a response that the CDM is able to accept.

**Comment by ChrisPuissant** [comment]
Hi,

No solution found but just for information in case anyone encounters the problem in the future.

Seems we encounter the same issue with recent Microsoft Playready test server:

````http://test.playready.microsoft.com/service/````

````(not old one: http://playready.directtaps.net/pr/svc/)````

See: http://test.playready.microsoft.com/ for documentation.

Looks like when calling : ````http://test.playready.microsoft.com/smoothstreaming/SSWSS720H264PR/SuperSpeedway_720.ism/Manifest````
Exoplayer use old server by default when calling HttpMediaDrmCallback.executeKeyRequest(UUID uuid, KeyRequest request): 
````http://playready.directtaps.net/pr/svc/rightsmanager.asmx````
but when I force it to use new licence server I get same issue: ````http://test.playready.microsoft.com/service/rightsmanager.asmx````

Microsoft new test server response:
````<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope 
    xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <soap:Body>
        <AcquireLicenseResponse 
            xmlns="http://schemas.microsoft.com/DRM/2007/03/protocols">
            <AcquireLicenseResult>
                <Response 
                    xmlns="http://schemas.microsoft.com/DRM/2007/03/protocols/messages">
                    <LicenseResponse 
                        xmlns="http://schemas.microsoft.com/DRM/2007/03/protocols">
                        <Version>1</Version>
                        <Licenses>
                            <License>WE1SAAAAAAMaeibs8zhdqy0it+ryPsfcAAMAAQAAAVAAAwACAAAAMgABAA0AAAAKAAEAAAAzAAAACgABAAEAMgAAAAwAAAAiAAEANAAAAAoAlgACAAQAAAAIAAMACQAAAPIAAQAKAAAAngJn4wkzj2xDpd1g/+ZnHnAAAQADAICGOU1CiA8Hu/MpmhisvjV4fDLQMHUPPMF0St6Q2QO9Qw4TQJj44uNoxvT0aEYxZG3pjnCLwWrz870Os/drQeDoMqDctjF9qvbujEdH58PzCfSgEA8intkZJ4sKRevunFRD1GEcMijjg+8ecPw4IKMtE+mvEIrAk5YpSm20WksNPgAAACoAAABMAAEAQJz82L001gMqFB7eIcK3CYGB1Y1QEmee7wEw+yMwLFKfHHgGqlVjG5MvcvEpqMMYweT3w71Uq75MepR0Ly3OoPUAAQALAAAAHAABABBjdk+DAQOpxH7pNk3t8KBF</License>
                        </Licenses>
                        <Acknowledgement>
                            <TransactionID>8b53fef0-4213-4812-b803-b1dc56331ae7</TransactionID>
                        </Acknowledgement>
                    </LicenseResponse>
                </Response>
            </AcquireLicenseResult>
        </AcquireLicenseResponse>
    </soap:Body>
</soap:Envelope>
````

So the new format seems to not correspond to what PlayReady CDM is able to accept.

**Comment by jeoliva** [comment]
Hi @ChrisPuissant,

In fact, the problem is in the manifest of the stream you are testing that is "declaring" a license url that is not valid any more. In other words, the license url declared in the ProtectionHeader element of the stream manifest is "http://playready.directtaps.net/pr/svc/rightsmanager.asmx". 

Exoplayer gets the license url directly from your manifest and then you get the error.

One question. How are you forcing the new license url? Although Exoplayer has a mechanism to define a default license url, that one is only used when there is no a license url defined in the manifest (not the case in the stream you are testing). I am assuming you did it without modifying Exoplayer source code (probably a wrong assumption :)).

**Comment by ChrisPuissant** [comment]
Hi @jeoliva

Yes I modified Exoplayer source for testing :) (HttpMediaDrmCallback.executeKeyRequest(UUID uuid, KeyRequest request) to be precise)

I just wanted to use recommended action from Microsoft as described on this page [http://test.playready.microsoft.com/](url) assuming the ProtectionHeader was correct :
````
Use enhanced resources listed on the new 2017 test server http://test.playready.microsoft.com/.
Use http://test.playready.microsoft.com/service/rightsmanager.asmx with the same parameters or using the new query string syntax
````

**Comment by jeoliva** [comment]
Makes sense :).

@ojw28, what should be the right way to proceed in case you need to force a specific license server url? That's not weird, I have faced that kind of requirement many times when working with PlayReady protected streams and Silverlight based players.

For example, I have seen many cases in which player forces a specific license server url when working in testing environment so it uses a dummy license server. 

I have seen also other cases in which, in production, the license server url is always specified by the app. Otherwise, if you rely on the one within the manifest, if for some reason you need to change the license server url, then you need to change all your manifest files (and purge CDN content, which has many implications and some potential "scalability" issues).

Although in current implementation there is the possibility of defining a default url that will be used whenever the license is not specified in the manifest, there is no way of "hardcoding" a specific license url. I see three possible solutions here:

1. - Use defaultUrl and don't specify a license url in the manifest. Not always possible as protection header is generated by the DRM provider and you can not modify it (it has a signature).
2. - Modify HttpMediaDrmCallback to support a new url parameter that in case of defined will override the licenseUrl within the manifest (or a flag that indicates whether defaultUrl should override the one in the manifest).
3. - At the app level, extend HttpMediaDrmCallback and implement our own logic there. In this case, setting a specific and fixed licenseUrl.

Solution 3 is pretty straight forward although given I have seen this requirement in many cases I wonder whether makes sense covering this case within Exoplayer library (Solution 2).

What do you think?

**Comment by ChrisPuissant** [comment]
@jeoliva 

I have opted for a custom MediaDrmCallback implementation at app level too.
However, as protection header has dummy server url, the dummy url stays in the generated KeyRequest

**Comment by ojw28** [comment]
My interpretation of this issue is that the AndroidTV on which you're testing falls into the category of "older Silverlight clients", as in the documentation included in the first post. Support for whatever the old license format was may be deprecated on the serving side, but if you wish to continue targeting such devices I don't see any alternative but to ensure that you continue to serve them with the older format licenses. Am I missing something?

**Comment by jeoliva** [comment]
I think the problem in this case was the license server url declared in the manifest was not valid anymore. Pointing to a new and valid license server requires modifying HttpMediaDrmCallback class (current implementation allows you to set a default license server but that is only used in case no one is declared in the manifest). 

Forcing a specific license server url is not a weird requirement and in fact was supported, and commonly used, in Silverlight based applications. This specific case (license server not valid) could sound weird but there are other situations in which forcing the license server is commonly used: testing in different environments or putting the logic of selecting the license server in the app side to avoid the need of updating all your assets (manifests) in case the license server changes.

Given said this, I propose one of these modifications (I offer myself to do the PR):
1. Add a forceDefaultUrl flag to HttpMediaDrmCallback constructor. In case it is set to true, HttpMediaDrmCallback will use defaultUrl even when a licenseServer is found in the manifest.
2. Don't set HttpMediaDrmCallback as a final class so we can extend it and implement our own logic for license server selection.

Thanks!

**Comment by ojw28** [comment]
- Could you clarify how the license server URL is declared in the manifest? Is it part of the Base64 data inside of the ProtectionHeader element? Just checking, since I don't think we explicitly parse a license URL anywhere in the manifest parser.
- Is it possible that passing a license response to the DRM session can change the default URL in the KeyRequest for subsequent KeyRequest instances obtained from the session? This can definitely happen for Widevine protected playbacks (I think the license response can include a new default URL, and that this functionality is used to do things like have the initial license request hit a different server than subsequent requests that belong to the same session). If so then I'm not certain the proposals would be valid in all cases.

**Comment by ChrisPuissant** [comment]
I don't think the issue came from Playready client, after checking, the client version used in the device is 2.5.0.1788, SimpleNonPersistentLicense class was already deprecated.

But manually replacing the URL in the KeyRequest doesn't work in my case. In fact it was worst...

I agree with jeoliva on adding a way to force licence server URL.
Doesn't work for me neither with non-persistent licences but works very well with persistent ones.

**Comment by jeoliva** [comment]
@ojw28, regarding point 1, yes, license server url is part of the base64 data inside of the protectionHeader element. Because it was quite common using a different one Silverlight provided a way to override it.

Regarding point 2, honestly I am not sure about it. I haven't seen that behavior before but I can't 100% confirm that kind of "license server redirect" is not supported by PlayReady. Anyway, I don't see too much problem on that. Even Silverlight allowed this and, in the worst case, what we are allowing is an app developer setting up a license server that doesn't work with their streams but this is totally under her control. I mean, she should know that in case of forcing a specific license server she should provide one that works with her assets.

The problem some big OTT companies are facing with this is having a license server defined in the manifest (protection header) could even impact scalability of their OTT platform. For example, if they need to purge all CDN content just because they changed their license server url.

**Comment by ojw28** [comment]
Adding a `forceDefaultUrl` flag sounds good to me. Feel free to send a pull request to the `dev-v2` branch.

**Comment by ojw28** [comment]
Forcing a specific license URL is supported as of `2.5.2`.
@jeoliva @ChrisPuissant - Can this issue be closed now?

**Comment by ojw28** [comment]
Assuming the answer is yes. Please reply here if not, and we can re-open.
