### ISSUE TITLE
Video frames moves forward when player is paused and its position changes in the layout

### ISSUE THREAD

**Issue by minaEweida** [google/ExoPlayer#3090]
I am using Exoplayer 2.4.3 in a Fragment playing Mp4 videos, but I can't use android:configChanges="orientation|keyboardHidden", at the same time I don't want restart buffering again each time device's orientation changes. So what I am doing is keeping a static instance of the SimpleExoPlayer, and I just create a new SimpleExoPlayerView and the set the player to it. However, if I change orientation while player is paused, the video frames keeps moving forward even if I seek the player to the current position. The audio works fine but the video frames keeps shifting forward and when I click play, the video frame will stay still until the current video frame position is actually reached, then continues normally.

Also this happens in the tablet landscape layout, if user scrolls down, the player changes to be a mini player on the right handside, which is done by changing the SimpleExoPlayerView position in the layout. However same issue happens if video was paused.

**Comment by andrewlewis** [comment]
This is a known issue but there were recently some changes to keep data buffered in the sample queue until it's rendered, which may help address this (for example, 1b71e3b4). I'm not sure whether all the required changes have landed yet, but please could you try switching to the `dev-v2` branch and seeing if it's reproducible?

**Comment by minaEweida** [comment]
I tested it on dev-v2 branch and it worked just fine, Thank you. I was wondering, is there a planned release soon to include this fix?

**Comment by andrewlewis** [comment]
There will likely be a release over the next couple of weeks.
