### ISSUE TITLE
Incorrect pom dependency for extension-ima

### ISSUE THREAD

**Issue by malachid** [google/ExoPlayer#3093]
### Issue description
In https://github.com/google/ExoPlayer/blob/dev-v2-r2.5.0/library/core/build.gradle, 
it says `releaseArtifact = 'exoplayer-core'`

https://jcenter.bintray.com/com/google/android/exoplayer/exoplayer-hls/r2.5.0-beta1/:exoplayer-hls-r2.5.0-beta1.pom correctly shows the dependency as
```
    <dependency>
      <groupId>com.google.android.exoplayer</groupId>
      <artifactId>exoplayer-core</artifactId>
      <version>r2.5.0-beta1</version>
      <scope>runtime</scope>
    </dependency>
```

https://jcenter.bintray.com/com/google/android/exoplayer/extension-ima/r2.5.0-beta1/:extension-ima-r2.5.0-beta1.pom is incorrect:
```
    <dependency>
      <groupId>ExoPlayer</groupId>
      <artifactId>library-core</artifactId>
      <version>unspecified</version>
      <scope>runtime</scope>
    </dependency>
```

### Reproduction steps
`compile "com.google.android.exoplayer:extension-ima:r2.5.0-beta1"` will show the problem. 
Or you can just look at the pom files on jcenter above.

### Link to test content
N/A - see jcenter links above

### Version of ExoPlayer being used
r2.5.0-beta1

### Device(s) and version(s) of Android being used
Device not necessary to repro. 
Hosted pom file has incorrect dependency, so gradle will report the error before it gets to a device, if necessary.

### A full bug report captured from the device
N/A - see jcenter links above

**Comment by malachid** [comment]
Of course, it's a low priority as you can work around it:
```
    compile("com.google.android.exoplayer:extension-ima:r2.5.0-beta1") {
        // https://github.com/google/ExoPlayer/issues/3093
        exclude group:'ExoPlayer', module:'library-core'
    }
```

**Comment by ojw28** [comment]
I've fixed this manually. I think this happened because we published the module separately to the other modules for r2.5.0-beta1. In subsequent release it'll be published at the same time as the others, so hopefully this wont happen again. If it does, please let us know!

**Comment by malachid** [comment]
Confirmed that it has been resolved; although, since the version was not rev'd and it is not a snapshot, anyone who had previously referenced it will need to add `--refresh-dependencies` to their gradle command once.

**Comment by ojw28** [comment]
Yes. It should be fixed in the next rev'd version also, we just haven't gotten around to pushing one yet ;). Thanks!
