### ISSUE TITLE
Notify when LoopingMediaSource is looped

### ISSUE THREAD

**Issue by sheaam30** [google/ExoPlayer#3096]
### Issue description
When playing a LoopingMediaSource, it would be useful to get notified when the source is looping.

### Reproduction steps
Prepare a LoopingMediaSource and play it, at the end of the source it restarts from the beginning but the player doesn't notify us.

### Version of ExoPlayer being used
r2.3.1

**Comment by tonihei** [comment]
You can listen to [EventListener.onPositionDiscontinuity](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/ExoPlayer.java#L174) to get notified of a position discontinuity. A position discontinuity occurs every time the playback transitions from one period to another (even if it is the beginning of the same period), if a seek occurred, or when an automatic internal discontinuity occurred. Querying `player.getCurrentWindowIndex()` and `player.getCurrentPosition() ` should help you to determine the current state.
