### ISSUE TITLE
Shoppable video 

### ISSUE THREAD

**Issue by AbhiHearty** [google/ExoPlayer#3099]
Can any one tell me is Shoppable video possible in Exoplayer ??

**Comment by andrewlewis** [comment]
ExoPlayer can play video. Whatever UI you provide in addition to that is up to your app.

**Comment by AbhiHearty** [comment]
I think you dont get me properly shoppable in the sense interactive video technology which is based on video player . https://www.wirewax.com/examples/ Refer to this link and play some videos out there..

**Comment by andrewlewis** [comment]
ExoPlayer provides building blocks for this kind of thing but you're going to need to implement the interaction as part of your app.

For "hotspots": #2189 tracks allowing the app to listen for playback reaching a particular position. Without that enhancement, you can still poll the player position or inspect video frame presentation timestamps using a custom video renderer. Then you can show some UI on top of the video at the relevant time and handle interaction with it.

For branching videos: you could use `DynamicConcatenatingMediaSource`, which allows for dynamic addition/removal of clips.

For 360 video: we don't provide built-in support but see #2211. You can also do arbitrary rendering by passing ExoPlayer's video renderer a Surface from a SurfaceTexture, which you then use as input to your own rendering logic.

**Comment by AbhiHearty** [comment]
I can Take the relevant position from the player but the question is how can i sense the pixels in the video ? and the hotspots are from the api . So how can i or how the hotspots are made to look common for both app and web ?

**Comment by andrewlewis** [comment]
If by "sense the pixels in the video" you mean inspect the output of the video decoder, there is no efficient way to do that in general. It seems like you should instead be delivering timed metadata that tells your app what to show on top of the player at what time. It's up to your application what you show on top of the video and how you render it. For example, you could try putting a WebView with a transparent background on top of the player and trigger changes in what it displays based on the playback position.

I think it's outside the scope of this issue tracker to give further guidance. Let us know if you have specific feature requests that would require ExoPlayer changes.

**Comment by AbhiHearty** [comment]
No i have only the inspecting part to be done by player itself . However i ll try with the timed meta data. Thanks for the time . :)

**Comment by tonihei** [comment]
We're currently working on this feature to let the player run a callback when it reaches a certain playback position. We would like to have your opinion on some edge cases in #2189 - please let us know what would fit your requirements best.
