### ISSUE TITLE
How does ExoPlayer support API level 9?

### ISSUE THREAD

**Issue by ddobrev** [google/ExoPlayer#31]
I tried using ExoPlayer in an application that has to support 2.3.7 and above. However, both FrameworkSampleSource and MediaCodecTrackRenderer require API level >= 16. I guess FrameworkSampleSource can be replaced by ChunkSampleSource but what about MediaCodecTrackRenderer? Does anyone have a 9-compatible implementation of TrackRenderer?

**Comment by eudson** [comment]
Hello @ddobrev, did you had any progress on this. If not, how are you supporting API Level 9 to 15?

**Comment by ddobrev** [comment]
@eudson I am afraid not, we simply kept using the standard MediaPlayer.

**Comment by ddobrev** [comment]
Hello @ojw28 . Could you please tell me the minimum required SDK if ExoPlayer is only used for audio?

**Comment by ojw28** [comment]
16
