### ISSUE TITLE
MediaSource.releaseSource NPE

### ISSUE THREAD

**Issue by zhaocheng19940105** [google/ExoPlayer#3102]
*** ISSUES THAT IGNORE THIS TEMPLATE WILL BE CLOSED WITHOUT INVESTIGATION ***

Before filing an issue:
-----------------------
1. I closed the wifi and release this player  2.Then open the wifi init player 

When reporting a bug:
-----------------------
Attempt to invoke interface method 'void com.google.android.exoplayer2.source.MediaSource.releaseSource()' on a null object reference
07-26 18:03:21.132 8041-8574/com.abc.agency.teacher E/Tinker.UncaughtHandler: catch exception when loading tinker:java.lang.NullPointerException: Attempt to invoke interface method 'void com.google.android.exoplayer2.source.MediaSource.releaseSource()' on a null object reference
                                                                                  at com.google.android.exoplayer2.source.ConcatenatingMediaSource.releaseSource(ConcatenatingMediaSource.java:103)
                                                                                  at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:724)
                                                                                  at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:684)

### Issue description
ConcatenatingMediaSource release source thow NPE

### Reproduction steps
release player close wifi  and open wifi init player maybe  reappear

### Version of ExoPlayer being used

compile 'com.google.android.exoplayer:exoplayer-core:r2.4.4'

### Device(s) and version(s) of Android being used
Xiaomi 5

**Comment by zhaocheng19940105** [comment]
I think release player Need time to do synchronization problems

**Comment by zhaocheng19940105** [comment]
for (int i = 0; i < mediaSources.length; i++) {
      if (!duplicateFlags[i]) {
        mediaSources[i].releaseSource();
      }
    }  
 this a npe in ConcatenatingMediaSource release

**Comment by zhaocheng19940105** [comment]
ClippingMediaSource npe

**Comment by ojw28** [comment]
I think this can only happen if you've passed null entries in the array of `MediaSource`s that you need to pass to the `ConcatenatingMediaSource` constructor. It's invalid to pass null entries, so you'll need to fix that in your code.
