### ISSUE TITLE
Widevine/MPEG-DASH: Video freezes, Audio goes on.

### ISSUE THREAD

**Issue by alex-schwartzman** [google/ExoPlayer#3103]
### Issue description
After 10-15 seconds of playback, the player stops rendering the frames. Audio continues.

### Reproduction steps
* Add Manifest+la_url to the demo app
* Start playback in the demo app
* Wait 15 seconds

### Link to test content
Sent the link to dev.exoplayer@gmail.com . There is a trick, however, license acquisition challenge is comcast-specific (base64-encoded binary license request payload as GET parameter _widevineChallenge) and the LA_URL is valid for just 15 minutes. Could be an option to meet in the Google Hangout and share valid LA_URL for investigation.

### Version of ExoPlayer being used
2.3.1
2.4.4
2.0.4

### Device(s) and version(s) of Android being used
5.0.2 on Japanese device docomo/SO-03F, it's like Sony, but heavily rebranded

### A full bug report captured from the device
Experiment timing is as follows (precision is 2 seconds):
07-26 15:35:45 - launched the app
07-26 15:36:07 - video stopped rendering

[video-hangs.zip](https://github.com/google/ExoPlayer/files/1176271/video-hangs.zip)
[docomo-sony-bugreport.zip](https://github.com/google/ExoPlayer/files/1176270/docomo-sony-bugreport.zip)

**Comment by ojw28** [comment]
Is the implication that this is content specific (i.e. does not reproduce with any of the Widevine protected content provided by default in the demo app)? Please try in particular all streams under "Widevine DASH Policy Tests" to see if any/all of those reproduce the problem. Thanks.

**Comment by ojw28** [comment]
Is it also device specific, or not?

**Comment by alex-schwartzman** [comment]
Yes, it's device specific. Only mentioned devices are affected.

In the meanwhile, I figured out following details:
1. Using _top_, I compared CPU load, required to play my streams on the Japanese XPeria Z3 versus European XPeria Z3. On that Japanese device CPU load is twice as high. 
2. As well, Japanese devices cause the following message printed to the logcat: 07-13 17:47:33.296 W/ACodec  ( 9173): do not know color format 0x7fa30c04 = 2141391876 , However, European versions do not.
3. Playback stops when the player switches to the 8MBps bitrate. In the initial experiment, I observed 10-15 seconds playback because I started with 1MBps, and then relied on the player to increase the quality. In the clean experiment, I fixed the bitrate to the predefined value and observed. Turned out that on the affected devices, there is no problem playing 4MBps stream, but when ExoPlayer is given an 8MBps stream - it consumes almost all CPU and drops all frames.

So far, my theory is:
1. Those affected devices are not capable of switching the surface to color format COLOR_QCOM_FORMATYUV420PackedSemiPlanar32m (0x7fa30c04)
2. Therefore, they fall back to converting 0x7fa30c04 into something like COLOR_FormatYUV420SemiPlanar just after decoding. And that's why CPU load is higher.

If my theory proves right, then there is a little ExoPlayer may do to improve the situation, except, maybe, adapting the algorithm of the maximum bitrate estimation, and including that "incompatible surface" variable into it.

**Comment by ojw28** [comment]
My guess is this is similar (or the same as) https://github.com/google/ExoPlayer/issues/816, despite the fact that slightly different builds are involved. In which case there's not a lot we can do about it, unfortunately. The device OEM/carrier would need to provide a platform software update to resolve the issue.

**Comment by alex-schwartzman** [comment]
Is it possible to add "surface compatibility check" into maximum-bitrate estimation algorithm?

**Comment by ojw28** [comment]
I doubt there exist platform APIs that would expose the information we'd need to perform such a check. If you're aware of a way to do this, please feel free to suggest it here. Closing for now on the assumption the OEM/carrier would need to provide a platform software update to resolve the issue.
