### ISSUE TITLE
Exoplayer stops on its own when in background

### ISSUE THREAD

**Issue by blennerSilva** [google/ExoPlayer#3104]
### Issue description
the issue is best described this way, when im using my app in background mode and using other apps at the same time such as facebook or instagram, exoplayer kills my app instantly.

### Reproduction steps
Start the player and leave app, open facebook(for example, is the app the reproduces de most times the error) use for a few minutes, 1 minute or less is enough, press the home button the, app is killed.

### Link to test content
https://www.youtube.com/watch?v=iDJ3JkPah1g

### Version of ExoPlayer being used
im using exoplayer 2.4.4 the issue is happening since 2.2.0 , it was the first version i put im my app before that i used another player.

### Device(s) and version(s) of Android being used
this issue is happening on every android device my app is installed at. But the testing device is moto g4 plus with android 7.0 nougat. but the issue happens since the 6.0

## as you can see at the moment of the crash the app simply dies and no log is recorded.

![screen shot 2017-07-26 at 11 12 47](https://user-images.githubusercontent.com/10924301/28625701-67b19756-71f3-11e7-87a3-54ebae448685.png)

**Comment by andrewlewis** [comment]
Please attach the output of `adb bugreport` taken just after reproducing the issue.

**Comment by blennerSilva** [comment]
[bugreport-NPJS25.93-14-4-2017-07-26-11-25-54.zip](https://github.com/google/ExoPlayer/files/1176902/bugreport-NPJS25.93-14-4-2017-07-26-11-25-54.zip)


here is the full bugreport

**Comment by andrewlewis** [comment]
Are you using a foreground service to continue playback while your app is in the background? If not, please read #2276.

**Comment by blennerSilva** [comment]
yes i use a service for that

![screen shot 2017-07-26 at 11 55 59](https://user-images.githubusercontent.com/10924301/28627892-6fa45a38-71f9-11e7-9a1b-cdfc773d097c.png)

**Comment by blennerSilva** [comment]
i could send you my service code on private if you'd like

**Comment by ojw28** [comment]
Is it a *foreground* service (see [here](https://developer.android.com/guide/components/services.html#Foreground))?

> exoplayer kills my app instantly

ExoPlayer doesn't have any app killing functionality, so something else is going on here (most likely in your own code) ;).

**Comment by andrewlewis** [comment]
In case it's useful: you can dump information about your service(s) using `adb shell dumpsys activity services -p [packagename]`. Foreground services show `isForeground=true` under their service record.

**Comment by blennerSilva** [comment]
Guys im sorry to keep pounding on this issue but i ran out of aways to try to fix it...and i dont quite understand de concept of foreground service so here is my service code plz give a hint on how to fix it 

[PlayerBackgroundService.java.zip](https://github.com/google/ExoPlayer/files/1261048/PlayerBackgroundService.java.zip)

**Comment by ojw28** [comment]
From the link I posted above:

> to request that your service run in the foreground, call startForeground()

Which you're not doing anywhere in your code, so it's unsurprising that your app is being killed. In any case, I'd suggest you ask somewhere like StackOverflow (and read the link I already posted above) to learn about foreground services, since it isn't an ExoPlayer specific topic.
