### ISSUE TITLE
Render Audio normally but Video to ByteBuffer only?

### ISSUE THREAD

**Issue by ephemer** [google/ExoPlayer#3105]
Hi, it seems like this should be *easier* than rendering the video output to a surface but I haven't figured it out yet.

What I'd really like is to render the video directly to an OpenGLES texture and have the Audio output handled by ExoPlayer. This would be equivalent to using the `AVPlayer` class on iOS / mac OS with a custom `AVPlayerItemVideoOutput`.

The data stream would look like this:
> Video File / URL --> ExoPlayer --> Audio playback & decoded video in pixel ByteBuffer

And I don't think StackOverflow is the place for this question (although there are numerous unanswered questions on there along these lines). Instead it is about a missing part of the ExoPlayer docs IMHO.

If there's no currently encouraged/possible way of doing this, would you kindly point me to what I'd need to subclass to get that result?

**Comment by ephemer** [comment]
It seems like `DummySurface` would be useful, but I can't see how it fits in to the rest of the the ExoPlayer ecosystem.

**Comment by andrewlewis** [comment]
At a high level, to render to a GL texture: get a GL context and generate the texture, then use it to construct a `SurfaceTexture`, then use that to construct a `Surface` which you pass to the decoder. For more details, including how to update the texture with the latest decoder output, read [this documentation on SurfaceTexture](https://source.android.com/devices/graphics/arch-st) and the [SurfaceTexture reference](https://developer.android.com/reference/android/graphics/SurfaceTexture.html). Some things to note:
- `GlSurfaceView` may be useful to reduce the amount of boilerplate you need to make the GL context.
- The texture containing decoder output is an external texture so if you use a fragment shader to copy from it you need to use `samplerExternalOES`.
- Compared to outputting from the decoder directly to a `SurfaceView` surface, this is going to be less power efficient and audio/video synchronization won't be as good.

`DummySurface` is used internally to work around the limitation that a `MediaCodec` must always have a surface attached while it is initialized, so I don't think it's useful for what you're trying to do.

**Comment by ephemer** [comment]
@andrewlewis thanks, I'll give that a shot
