### ISSUE TITLE
Add ImaAdsMediaSource.AdsListener callback triggered when the user taps an ad

### ISSUE THREAD

**Issue by malachid** [google/ExoPlayer#3106]
### Issue description
The use case is tracking ad start/stop.

https://github.com/google/ExoPlayer/blob/dev-v2-r2.5.0/extensions/ima/src/main/java/com/google/android/exoplayer2/ext/ima/ImaAdsLoader.java
is public and contains `public interface EventListener`
which further contains `void onAdPlaybackState(AdPlaybackState adPlaybackState)`
https://github.com/google/ExoPlayer/blob/dev-v2-r2.5.0/extensions/ima/src/main/java/com/google/android/exoplayer2/ext/ima/AdPlaybackState.java
shows that the class is package private. This prevents implementing the ImaAdsLoader.EventListener interface.

In AdPlaybackState, we just need to change `/* package */` to public.

### Reproduction steps
`implements ImaAdsLoader.EventListener`

### Link to test content
Independent of any specific content

### Version of ExoPlayer being used
dev-v2-r2.5.0

### Device(s) and version(s) of Android being used
N/A - doesn't compile

### A full bug report captured from the device
N/A - doesn't compile

**Comment by andrewlewis** [comment]
To track when ads start/stop playing, call [`player.isPlayingAd`](https://github.com/google/ExoPlayer/blob/dev-v2-r2.5.0/library/core/src/main/java/com/google/android/exoplayer2/Player.java#L389) in [`Player.EventListener.onPositionDiscontinuity`](https://github.com/google/ExoPlayer/blob/dev-v2-r2.5.0/library/core/src/main/java/com/google/android/exoplayer2/Player.java#L116). There are also methods on the player to get the current ad index and the current ad index in the ad group, and the`Timeline` instance contains information about ad groups.

**Comment by malachid** [comment]
Hi Andrew - thank you for the feedback.
For anyone else reading this and looking for instructions, here's some details during a PreRoll->Video:

When starting the PreRoll, onTimelineChanged is called with isPlayingAd=true 8 times

If you click Learn More, neither onTimelineChanged or onPositionDiscontinuity is called.

When you hit the back arrow, onPositionDiscontinuity is called with isPlayAd=false once, then onTimelineChanged is called with isPlayingAd=true 3 times

When the ad ends, onPositionDiscontinuity is called with isPlayAd=false once, then onTimelineChanged is called with isPlayingAd=false once

Hope that helps others.

**Comment by malachid** [comment]
Andrew - I wonder if `imaAdsLoader.addCallback` might be a better approach?  While there is some bouncing/duplication of events, it does capture transition to Learn More.  Do you see any problems with using that callback?

**Comment by andrewlewis** [comment]
In case it's useful, here some more information about what's going on:

> When starting the PreRoll, onTimelineChanged is called with isPlayingAd=true 8 times

The timeline is updated each time we get more information about the structure of the media: when the times of ad groups becomes known, when the number of ads in the first ad break is updated, when the ad media URI and the duration of the ad become known, etc..

> If you click Learn More, neither onTimelineChanged or onPositionDiscontinuity is called.

The player is released when the application goes into the background (to open more information in Chrome for example), so there's no discontinuity.

> When you hit the back arrow, onPositionDiscontinuity is called with isPlayAd=false once, then onTimelineChanged is called with isPlayingAd=true 3 times

When the player returns to the foreground, we first seek to the pending content position causing a discontinuity, then this gets resolved to an ad position if there's a pending ad that needs to be played first.

> When the ad ends, onPositionDiscontinuity is called with isPlayAd=false once, then onTimelineChanged is called with isPlayingAd=false once

Transitions from ad to ad, ad to content and content to ad will all trigger position discontinuities. Timeline changes occur whenever more information becomes known about the structure of media.

Regarding detecting the user tapping 'Learn more', we should probably add an event to `ImaAdsMediaSource.AdsListener` to allow apps to handle this (it currently just has a callback for handling ad loading errors). For all the ad tags I've seen, tapping the ad causes the player to enter the background, but maybe the app has to handle this event itself in some cases. I'll mark this as an enhancement to track adding the listener callback. I think that should be sufficient for apps to handle events related to ad playback without needing to listen for `ImaAdsLoader` events, but let me know if you can think of anything else. Thanks!

**Comment by malachid** [comment]
Hi Andrew - thanks for the quick response.

When this is completed, the suggested pattern would be (correct me if I'm wrong):
1. track ad starts via onTimelineChanged w/ isAdPlaying=true (an optionally debounce, depending on our own use case)
2. track ad clicks via AdsListener new method
3. track ad playback resumed via onTimelineChanged w/ isAdPlaying=true
4. track ad ended via onTimelineChanged w/ isAdPlaying=false

I haven't tried it yet, but I think the only use case for onPositionDiscontinuity w/ isAdPlaying=true will be going from content->ad (midroll or postroll)?  I think that would still fall into bucket 1 though.

**Comment by andrewlewis** [comment]
You could store whether ads are currently playing in a field. In `onPositionDiscontinuity` call `isPlayingAd()` and if the returned value is not equal to the value in the field, update the field and handle the ads started/stopped event as appropriate. The other thing necessary to make this work is to handle `onTimelineChanged` to set the initial value of the field (when the timeline first updates we know whether the player is initially in a ad or not). `ImaAdsLoader` does this, so please read that for a concrete example.

To be clear: there's no guarantee of getting a call to `onTimelineChanged` when (for example) resuming content after playing an ad, so it's necessary to handle `onPositionDiscontinuity` for that. Hope this helps!
