### ISSUE TITLE
ID3 Metadata crash causes MP3 to be unplayable

### ISSUE THREAD

**Issue by rustyshelf** [google/ExoPlayer#3116]
### Issue description
When playing this particular MP3 through ExoPlayer the following exception occurs, causing playback to fail:

> 07-28 11:53:04.081 12638 14002 E ExoPlayerImplInternal: com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected IllegalArgumentException: 55 > 53
> 07-28 11:53:04.081 12638 14002 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:317)
> 07-28 11:53:04.081 12638 14002 E ExoPlayerImplInternal: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
> 07-28 11:53:04.081 12638 14002 E ExoPlayerImplInternal: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
> 07-28 11:53:04.081 12638 14002 E ExoPlayerImplInternal: 	at java.lang.Thread.run(Thread.java:762)
> 07-28 11:53:04.081 12638 14002 E ExoPlayerImplInternal: Caused by: java.lang.IllegalArgumentException: 55 > 53
> 07-28 11:53:04.081 12638 14002 E ExoPlayerImplInternal: 	at java.util.Arrays.copyOfRange(Arrays.java:3534)
> 07-28 11:53:04.081 12638 14002 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.metadata.id3.Id3Decoder.decodeGeobFrame(Id3Decoder.java:519)
> 07-28 11:53:04.081 12638 14002 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.metadata.id3.Id3Decoder.decodeFrame(Id3Decoder.java:361)
> 07-28 11:53:04.081 12638 14002 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.metadata.id3.Id3Decoder.decode(Id3Decoder.java:135)
> 07-28 11:53:04.081 12638 14002 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.extractor.mp3.Mp3Extractor.peekId3Data(Mp3Extractor.java:330)
> 07-28 11:53:04.081 12638 14002 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.extractor.mp3.Mp3Extractor.synchronize(Mp3Extractor.java:248)
> 07-28 11:53:04.081 12638 14002 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.extractor.mp3.Mp3Extractor.sniff(Mp3Extractor.java:149)
> 07-28 11:53:04.081 12638 14002 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractorHolder.selectExtractor(ExtractorMediaPeriod.java:710)
> 07-28 11:53:04.081 12638 14002 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:645)
> 07-28 11:53:04.081 12638 14002 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
> 07-28 11:53:04.081 12638 14002 E ExoPlayerImplInternal: 	... 3 more

The MP3 in question is [this one](https://media.blubrry.com/tricodepais/content.blubrry.com/tricodepais/tricodepais_ep028.mp3)

### Reproduction steps
- Attempt to play MP3 linked in this issue, playback fails with ID3 exception.

### Link to test content
https://media.blubrry.com/tricodepais/content.blubrry.com/tricodepais/tricodepais_ep028.mp3

### Version of ExoPlayer being used
2.4.4

### Device(s) and version(s) of Android being used
Tested on quite a few phones, Google Pixel, Samsung Galaxy S6, S7, etc.

**Comment by ojw28** [comment]
Please verify this is fixed on the `dev-v2` branch. Thanks!

**Comment by rustyshelf** [comment]
Updated to v2.5.1 and confirmed this now works. It's fixed quite a few other shows we've had issues reported with as well. As always, great work :)
