### ISSUE TITLE
How to add libmp3lame of ffmpeg in ExoPlayer? 

### ISSUE THREAD

**Issue by mrjerometw** [google/ExoPlayer#3117]
*** ISSUES THAT IGNORE THIS TEMPLATE WILL BE CLOSED WITHOUT INVESTIGATION ***
### Issue description
I want to add "libmp3lame" of FFMpeg in ExoPlayer .
But it's happened that "ERROR: libmp3lame >= 3.98.3 not found"

I already add mp3lame-dev package, refer this article 
http://ask.xmodulo.com/fatal-error-lame-no-such-file-or-directory.html

### Reproduction steps
According to "ffmpeg/README.md" , I add "--enable-libmp3lame" script, like these ..

COMMON_OPTIONS="\
    --target-os=android \
    --disable-static \
    --enable-shared \
    --disable-doc \
    --disable-programs \
    --disable-everything \
    --disable-avdevice \
    --disable-avformat \
    --disable-swscale \
    --disable-postproc \
    --disable-avfilter \
    --disable-symver \
    --disable-swresample \
    --enable-avresample \
    --enable-decoder=vorbis \
    --enable-decoder=opus \
    --enable-decoder=flac \
    --enable-libmp3lame \
    " && \
cd "${FFMPEG_EXT_PATH}/jni" && \
git clone git://source.ffmpeg.org/ffmpeg ffmpeg && cd ffmpeg && \
./configure \
    --libdir=android-libs/armeabi-v7a \
    --arch=arm \
    --cpu=armv7-a \
    --cross-prefix="${NDK_PATH}/toolchains/arm-linux-androideabi-4.9/prebuilt/${HOST_PLATFORM}/bin/arm-linux-androideabi-" \
    --sysroot="${NDK_PATH}/platforms/android-9/arch-arm/" \
    --extra-cflags="-march=armv7-a -mfloat-abi=softfp" \
    --extra-ldflags="-Wl,--fix-cortex-a8" \
    --extra-ldexeflags=-pie \
    --target-os=android \
    --disable-static \
    --enable-shared \
    --enable-libmp3lame \
    && \
make -j4 && make install-libs && \
make clean && ./configure \
    --libdir=android-libs/arm64-v8a \
    --arch=aarch64 \
    --cpu=armv8-a \
    --cross-prefix="${NDK_PATH}/toolchains/aarch64-linux-android-4.9/prebuilt/${HOST_PLATFORM}/bin/aarch64-linux-android-" \
    --sysroot="${NDK_PATH}/platforms/android-21/arch-arm64/" \
    --extra-ldexeflags=-pie \
    ${COMMON_OPTIONS} \
    && \
make -j4 && make install-libs && \
make clean && ./configure \
    --libdir=android-libs/x86 \
    --arch=x86 \
    --cpu=i686 \
    --cross-prefix="${NDK_PATH}/toolchains/x86-4.9/prebuilt/${HOST_PLATFORM}/bin/i686-linux-android-" \
    --sysroot="${NDK_PATH}/platforms/android-9/arch-x86/" \
    --extra-ldexeflags=-pie \
    --disable-asm \
    ${COMMON_OPTIONS} \
    && \
make -j4 && make install-libs && \
make clean

### Version of ExoPlayer being used
ExoPlayer Version:
commit 2bebd526e1ece801ef53e6daeaaee76b0255ec6d
Merge: 3ada4e1 1b64d62
Author: ojw28 <olly@google.com>
Date:   Fri Jun 30 19:07:03 2017 +0100

    Merge pull request #3009 from google/dev-v2-r2.4.3
    
    r2.4.3
----------------------------------------------------------------
FFMpeg version
commit 8e275a74b09cc87f4334ed572f919b7647d4bea1
Author: Michael Niedermayer <michael@niedermayer.cc>
Date:   Wed Jul 26 20:26:43 2017 +0200

    avcodec/diracdec: Fix integer overflow in signed multiplication in UNPACK_AR
    
    Fixes: runtime error: signed integer overflow: 1073741823 * 4 cannot be repr
    Fixes: 2729/clusterfuzz-testcase-minimized-5902915464069120
    
    Found-by: continuous fuzzing process https://github.com/google/oss-fuzz/tree
    Signed-off-by: Michael Niedermayer <michael@niedermayer.cc>

### OS 
Ubuntu 14.04 

### A full bug report captured from the device
ffmpeg/ffbuild/config.log

/home/jerome/android_sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc --sysroot=/home/jerome/android_sdk/ndk-bundle/platforms/android-9/arch-arm/ -isysroot /home/jerome/android_sdk/ndk-bundle/platforms/android-9/arch-arm/ -D_ISOC99_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -Dstrtod=avpriv_strtod -DPIC -march=armv7-a -mfloat-abi=softfp -march=armv7-a -std=c11 -fomit-frame-pointer -fPIC -marm -pthread -c -o /tmp/ffconf.6aF6w1Fo/test.o /tmp/ffconf.6aF6w1Fo/test.c
/tmp/ffconf.6aF6w1Fo/test.c:1:23: fatal error: lame/lame.h: No such file or directory
 #include <lame/lame.h>
                       ^
compilation terminated.
ERROR: libmp3lame >= 3.98.3 not found

**Comment by andrewlewis** [comment]
Does it work if you add `--enable-decoder=mp3` instead?

**Comment by mrjerometw** [comment]
@andrewlewis 
Oh my God !
You are right !!
It's successful 
Thank you very much !

**Comment by andrewlewis** [comment]
Glad it worked :)
