### ISSUE TITLE
sync audio & video to common PCR clock

### ISSUE THREAD

**Issue by mansoorahmed084** [google/ExoPlayer#3122]
I'm using ExoPlayer v1.5.11 and in current implementation of av sync, video follows audio and audio is free flow.
I want to implement an avsync logic in ExoPlayer for broadcast usecase in which both audio & video follows a common PCR clock 
(say system clock). I have a restriction that i cannot drop audio frames as it would create audible artifacts.

Here's what i have understood from code so far. ExoPlayer uses updatePositionUs() to update the media position & elapsedRealTimeUs parameters 
and passes these to the renderers via doSomeWork(). Audio pushes its frames to audioTrack which accumulates upto 32KB of audio frames and based 
on audio position and some calculated delay video renders or drops the frames. Here audio has no inbuilt notion of timing. 

I'm having problem implementing a logic which will sync audio with system clock based on latency & PTS (let for the time being video follow audio)
, it is not able to calculate correct delay after which i should call handlebuffer().

Suppose a audio buffer comes into processOutputBuffer() of MediaCodecAudioTrackRenderer() with PTS 168922, and after calculations it finds out that 
its too early wrt elapsedRealtimeUs. So i don't send this frame to audiotrack yet and return. Now problem is that when it agains returns to same processOutputBuffer() second time,
updatePositionUs() in ExoplayerImpInternal.java has already been called and now i gain has a new elapsedRealtimeUs value. So in a way audio is losing its sense of timing.

Can anyone guide me how to do it? Do i need to make 2 seperate audio & video clocks which will sync to common clock.
Also how to handle when it goes out of sync say after frame drop.

**Comment by ojw28** [comment]
It's difficult to see how you can both not drop any audio and perform a re-synchronization at the same time. The only way I could see that working is by changing the playback speed temporarily to achieve re-synchronization (which is something you could look at doing).

How accurate does the synchronization really need to be?

**Comment by mansoorahmed084** [comment]
thanks for the prompt reply.
I was also thinking on similar lines, when none of audio or video is master, we will have to drop frames to resync. I would consider changing playback speed, that sounds good.

Also can you confirm whether going with two internal clocks, one for audio & one for video is the right approach? Regarding accuracy, i should be able to play DVB TS streams or live TV without any noticible delay between audio & video. I'm in process of finalizing a strategy so it's essential for me to make sure i'm choosing the right path that why i need your expert help.

If you feel there is some better strategy, let me know i'm open to it as well.

**Comment by mansoorahmed084** [comment]
Hi,

I have been able to sync audio to PCR clock but i am not sure when should i render the first video frame. When video is using audio media positionUs, which is updated from android.media.audioTrack it's syncing well. But when i try to decouple this, even after considering audio track latency of 79ms, video is ahead of audio by few milli seconds.
Can you please tell me how to render 1st video frame so that it's played in sync with audio?

**Comment by ojw28** [comment]
I really don't understand enough about what your use case is to provide sensible guidance. What exactly are you trying to play (is there one stream, or two), how many players are you using (one or two), why do you need to sync against PCR, and what is the clock "common" with? It's quite unclear from the current description. Thanks.

**Comment by mansoorahmed084** [comment]
Okay let me explain the strategy again and then you can comment whether that is a good idea or not.

I'm using ExoPlayer in broadcast usecase to play AV streams. In current implementation, audio is free run and video follows audio using PositionUs but this is not suitable for broadcast. We want both audio & video to follow a common PCR clock [you can consider a system clock as reference for time being] and sync to this clock only.

What i have done is made audio follow system clock instead of free run. Now i need to add some logic in video track renderer so that audio & video are in sync but not using PositionUs of audio track. It is the way it should be done or we will have to sync video to audio using this media position (positionUs) parameter only?

**Comment by ojw28** [comment]
If you've made audio follow PCR somehow, then the audio renderer should be reporting the position correctly, and video should be following that correct position. You shouldn't need to make any changes to the video renderer. If the audio renderer is mis-reporting its position then you should fix that, after which you'd have `PCR <-- [follows] -- Audio <-- [follows] -- Video`.

**Comment by mansoorahmed084** [comment]
yea after making audio follow PCR, it reports correct positionUs. I have tested on many streams and current implementation is working fine (where video is using PositionUs from audio track). I would like to know whether it is even possible to make video also independent (not following audio but PCR).

I get stuck here, when i try to remove dependency of video on positionUs (audio), it goes out of sync. Even after considering audiotrack latency of around 79msec, i couldn't match audio & video sync as i don't exactly know when 1st frame of audio is actually rendered (coz i now don't have positionUs anymore). I hope you get my point.
If you feel doing above is not feasible then i will go with what i have already achieved and fine tune it, else please suggest how to do it.

Also, I get lost when i try to find from where exactly positionUs is fetched. It is calculated & updated based on getPosition() calls from ExoplayerImpInternal.java --> AudioTrack.java --> android.media.audioTrack --> all the way to AudioTrack.cpp in which it refers to proxy->getPosition() and this proxy has been created using track which was created by AudioFlinger().

After this i have not been able to find where proxy->getPosition() goes. Any pointers would be helpful.

**Comment by ojw28** [comment]
If audio is following PCR, and video is following audio, then video is already following PCR. What is the benefit of trying to have video follow PCR directly? You could probably inject a custom Renderer whose sole purpose is to act as a clock and have both audio and video renderers follow that (you'd need to make the audio renderer no longer implement MediaClock). It's unclear what the benefit is though, since it seems more convoluted and is otherwise equivalent. I think the way you're doing things currently is the best way.

I think the audio timestamp code path that you're following probably disappears into proprietary SoC vendor code, which is typically proprietary / not open source. Which is probably why you can't find where it goes (I didn't confirm this theory, but it seems highly likely).

**Comment by mansoorahmed084** [comment]
Thanks for the help. Much appreciate that.
