### ISSUE TITLE
exoplayer - 416 http response code

### ISSUE THREAD

**Issue by noammazuz** [google/ExoPlayer#3123]
i saw this link. 
https://github.com/google/ExoPlayer/issues/2259
and i think the problem is similar.

when i try to play this url https://xmediadownloadservice.hunterhrms.com/api/video?ContentPath=XEFwcGxpY2FudFxiYWFkMzA3NS1mNTU4LTQ4NzctYTM2YS0xY2RjOWNhMzk1MTdcYmFhZDMwNzUtZjU1OC00ODc3LWEzNmEtMWNkYzljYTM5NTE3Lm1wNA==&UserNameToken=VkpPQlNBUFBcMTAxNTUxMjYxOTE0NzczNzBeXl5eNC84LzIwMTcgMTM6MDM6NTg=&PasswordToken=S2xZT3E3enlCdE42THBGQVN1enJBWkduRFpObUZwL05pNjdkbVptYi9RWlZiMDNDcUtHdVZxQU5hMWhTUm5OK28vZUhGUGI5dldMeGludlkrZ3hnKzU3M2Fmb1NrTWIwdGdsaTZsZUNIWnA0VGMvaFJjejU0Ukp3a2JGL09yeEt2ZEE0bGh3d25vdzVQaEV0cVllK2dQbDJCUnlYZjdhR2tHaWc4VjhKRWdVPQ==&isTheSameUser=True&TransactionCode=cf7bef1b-ecb2-4997-8343-259bae796dbahttps://xmediadownloadservice.hunterhrms.com/api/video?ContentPath=XEFwcGxpY2FudFxiYWFkMzA3NS1mNTU4LTQ4NzctYTM2YS0xY2RjOWNhMzk1MTdcYmFhZDMwNzUtZjU1OC00ODc3LWEzNmEtMWNkYzljYTM5NTE3Lm1wNA==&UserNameToken=VkpPQlNBUFBcMTAxNTUxMjYxOTE0NzczNzBeXl5eNC84LzIwMTcgMTM6MDM6NTg=&PasswordToken=S2xZT3E3enlCdE42THBGQVN1enJBWkduRFpObUZwL05pNjdkbVptYi9RWlZiMDNDcUtHdVZxQU5hMWhTUm5OK28vZUhGUGI5dldMeGludlkrZ3hnKzU3M2Fmb1NrTWIwdGdsaTZsZUNIWnA0VGMvaFJjejU0Ukp3a2JGL09yeEt2ZEE0bGh3d25vdzVQaEV0cVllK2dQbDJCUnlYZjdhR2tHaWc4VjhKRWdVPQ==&isTheSameUser=True&TransactionCode=cf7bef1b-ecb2-4997-8343-259bae796dba

i get Source error.  com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 416

in browser its working but from android from exo player, its not.

if the problem is in the initialization chunk, how can i check it? and learn more about the issue (stsd box etc),
else what is the problem?

**Comment by ojw28** [comment]
This doesn't appear to be a valid media file. The `mediainfo` tool doesn't seem to be able to tell much about it. Playback doesn't work for me in VLC or Chrome on Linux either.
