### ISSUE TITLE
Question: Is there a same function in v2 for onDownstreamFormatChanged(v1)

### ISSUE THREAD

**Issue by jiafei1986** [google/ExoPlayer#3124]
I am upgrading a video app from v1 to v2,  there is a third party logic added in the method onDownstreamFormatChanged as below 
for example in the DemoPlayer in v1:
```
@Override
	public void onDownstreamFormatChanged(int sourceId, Format format, int trigger, long mediaTimeMs) {
		if (infoListener == null) {
			return;
		}
		if (sourceId == TYPE_VIDEO) {
			videoBitrate = format.bitrate;
			videoFormat = format;
			infoListener.onVideoFormatEnabled(format, trigger, mediaTimeMs);
		} else if (sourceId == TYPE_AUDIO) {
			audioBitrate = format.bitrate;
			infoListener.onAudioFormatEnabled(format, trigger, mediaTimeMs);
		}

		if (videoBitrate > 0 && audioBitrate > 0) {
			AnalyticsManager.onBitrateChange(((audioBitrate + videoBitrate) / 1000));
		}
	}
```
as you can see there is a piece of code  AnalyticsManager.onBitrateChange(((audioBitrate + videoBitrate) / 1000));   is there function that i can add this code in the exoplayer v2?

Thanks in advance.

**Comment by ojw28** [comment]
There is still an `onDownstreamFormatChanged` in V2 (and it's used in `EventLogger` in the demo app).

**Comment by jiafei1986** [comment]
@ojw28 thank you, just found out it .
