### ISSUE TITLE
Add instructions for building extensions on Windows

### ISSUE THREAD

**Issue by Aditya94A** [google/ExoPlayer#3127]

**Comment by ojw28** [comment]
None of our dev team use Windows, so it's somewhat difficult for us to do this. It might be a case of someone figuring it out and then sending a pull request that adds the necessary instructions.

@andrewlewis suggests you give [Windows Subsystem for Linux](https://msdn.microsoft.com/en-gb/commandline/wsl/about) a try, which is provided by Microsoft for running Linux environments directly on Windows. You may well just be able to follow the existing instructions using that.

**Comment by schwarzichet** [comment]
Basically there is no need to use WSL or something else to build it on windows.
For me , just use powershell to setup those environment variable then use NDK to build. The procedure is exactly same .

**Comment by ojw28** [comment]
Closing since it sounds like there's a straightforward solution to this.

**Comment by robindanielk** [comment]
@Crossady...Hi, I am new to Android Ndk..Can you kindly help me with the procedure to add ffmpeg in windows!!
