### ISSUE TITLE
ConcatenatingMediaSource seek lost

### ISSUE THREAD

**Issue by shoyu666** [google/ExoPlayer#3134]
dear author:
                    i use ConcatenatingMediaSource (a.mp4,b.mp4),we need record position that user has reach
for example
a.mp4  10s
b.mp4   20s
15s mean  at window 1,pisition 5

we use seekto(window,position) after prepare
but it case  only play b.mp4 ,a.mp4 lost,user can not seek to a.mp4,it only can seek to begin of b.mp4, a.mp4 can not find.  

before  -------10s(a.mp4)----------,------20s(b.mp4)----------
seekto(1,15000) after prepare
after     ------20s(b.mp4)----------

                                                                 thanks

**Comment by andrewlewis** [comment]
What do you mean by "a.mp4 lost"? Could you describe the steps to reproduce the problem, what happens and what you expect to happen?

**Comment by shoyu666** [comment]
ConcatenatingMediaSource  mean i can connect a.mp4 b.mp4
if do nothing after prepare ,it play a.mp4 and b.mp4 as a single file,play a first then play b,and user can seek
if use seekto(window,position) after prepare
it play b.mp4 only,seek at begin use seekbar  == b.mp4 0 pisiton

I am sorry for my poor english 

a.mp4  lost mean missing/can not find a

**Comment by andrewlewis** [comment]
Does https://github.com/google/ExoPlayer/issues/2122#issuecomment-291202163 help? If not, please could you phrase the question differently?

**Comment by shoyu666** [comment]
dear auth
               thanks for you reply.
 i have read #2122
 my problem is 
 url    http://xxxxxx/a.mp4    t1=10s   window 0
 url    http://xxxxxx/b.mp4    t2=20s   window 1
 use **ConcatenatingMediaSource(a.mp4,b.mp4)**  and DefaultPlaybackControlView.setShowMultiWindowTimeBar(true)
 it work fine,and seekbar is t1+t2 , everything was fine
 but when i use seekto(1,15000) api after prepare() api
 the result equals
**ConcatenatingMediaSource(b.mp4)**
move seekbar at begin (position 0) equals  b.mp4 position 0 
a.mp4 missing

nothing change ,only diff is call seekto(1,15000) api after prepare() api
debug player i can find
getCurrentTimeline().getPeriodCount()=2
getCurrentTimeline().getWindowCount()=2
getCurrentTimeline().getPeriod(0,new Timeline.Period()).getDurationUs()==UnSet
getCurrentTimeline().getPeriod(1,new Timeline.Period()).getDurationUs()==t2==20000
a.mp4 never play in screen,it just missing

**Comment by andrewlewis** [comment]
We can only show the multi-window time bar if we know the duration of every item in the concatenation. I think what's happening is that when you immediately seek to the second item, we never load the first one, so its duration is unknown, so the time bar reverts to showing a single window. If you know the durations of the two clips you may be able to work around this by wrapping the sources in ClippingMediaSources with specified end-points equal to their durations, as suggested in https://github.com/google/ExoPlayer/issues/2122#issuecomment-291202163.

**Comment by shoyu666** [comment]
dear auth 
 thanks,you are so kind, I understand
 by the way 
 how to use ClippingMediaSource?
 public ConcatenatingMediaSource(MediaSource... mediaSources) support mutil mediaSources

 public ClippingMediaSource(MediaSource mediaSource, long startPositionUs, long endPositionUs) not support

should i use 
ClippingMediaSource(ConcatenatingMediaSource(a.mp4,b.mp4)) ?

**Comment by andrewlewis** [comment]
ConcatenatingMediaSource(ClippingMediaSource(a.mp4, 0, aDurationMicroseconds), ClippingMediaSource(b.mp4, 0, bDurationMicroseconds)) should work.
