### ISSUE TITLE
Ffmpeg extension's FfmpegDecoder doesnt work 

### ISSUE THREAD

**Issue by richardissuperman** [google/ExoPlayer#3137]
### Issue description
I follow the exact same steps listed here to configure all the libs : 
https://github.com/google/ExoPlayer/tree/dev-v2/extensions/ffmpeg
When i run the demo project(include the FFmpeg extension) all native libraries have been loaded already,  FfmpegLibrary.java's isAvailable() method is returning true in runtime.

However, when i try to play a mp4 container with audio track mimeType=audio/mp4a-latm, i failed to get the decoder. fmpegHasDecoder(codecName) method return false. and that codec name is "aac" which is a very typical audio decoder.(Noted that in SimpleExoplayer source code i forced it to use FfmpegAudioRenderer instead of the default MediaCodec one)

It results in no audio will be played, and error message "Media includes audio tracks, but none are playable by this device"

### Version of ExoPlayer being used
I used released version 2

### Device(s) and version(s) of Android being used
Nexus 5p, since this is software decoding i dont think device matter

### A full bug report captured from the device

below is the log :

Tracks [
08-04 19:00:42.233 20009-20009/com.google.android.exoplayer2.demo D/EventLogger:   Renderer:0 [
08-04 19:00:42.233 20009-20009/com.google.android.exoplayer2.demo D/EventLogger:     Group:0, adaptive_supported=YES [
08-04 19:00:42.234 20009-20009/com.google.android.exoplayer2.demo D/EventLogger:       [ ] Track:0, id=139, mimeType=audio/mp4a-latm, bitrate=49221, channels=2, sample_rate=22050, supported=NO_UNSUPPORTED_TYPE
08-04 19:00:42.234 20009-20009/com.google.android.exoplayer2.demo D/EventLogger:       [ ] Track:1, id=140, mimeType=audio/mp4a-latm, bitrate=127864, channels=2, sample_rate=44100, supported=NO_UNSUPPORTED_TYPE
08-04 19:00:42.235 20009-20009/com.google.android.exoplayer2.demo D/EventLogger:     ]
08-04 19:00:42.235 20009-20009/com.google.android.exoplayer2.demo D/EventLogger:   ]

**Comment by andrewlewis** [comment]
The instructions in the README only enable a subset of possible decoders. You'd need to change the arguments to configure to use others. See also the [supported formats page](https://google.github.io/ExoPlayer/supported-formats.html#ffmpeg-extension).

**Comment by andrewlewis** [comment]
Out of interest, is there any reason you want to bundle a decoder for AAC rather than using the one provided by the device? If you've found a device/build with a broken decoder it would be useful to know about it. Thanks!

**Comment by richardissuperman** [comment]
@andrewlewis oh thanks, i dont know the aac is not included in the default supported settings, will try and configure again then.
No i dont have a broken device, the reason i want to use the ffmpeg one is i wanted to study how you build the ffmpeg decoder and build a ffmpeg **video renderer**,because we have some **HUAWEI** devices which doesnt work well with MediaCodec api, wanted to try the software decoding approach.But im not sure if it is possible , 

if you have any clues on that please give me some ;) thanks

**Comment by andrewlewis** [comment]
See #2159.
