### ISSUE TITLE
Ignore load errors in subtitle tracks sideloaded using SingleSampleMediaSource

### ISSUE THREAD

**Issue by minaEweida** [google/ExoPlayer#3140]
I am using MergingMediaSource in order to display Video and subtitles. For some reason the text source file might be removed from the server so the url will return 404, giving the following exception com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 404

At this point it makes sense, the problem is I can't play the video if this happens although I expect that if the text source is not found, I could at least play the video.

Below you can find the code snippet for preparing the media links

```
MediaSource videoSource = new ExtractorMediaSource(mp4VideoUri, dataSourceFactory, extractorsFactory, null, null);

Format textFormat;
MediaSource[] mediaSources = new MediaSource[videoDetailsModel.getVideoSubtitleModels().size() + 1];
mediaSources[0] = videoSource;
for (int i = 0; i < videoSubtitleModels.size(); i++) {
  VideoSubtitleModel videoSubtitleModel = videoSubtitleModels.get(i);
  textFormat = Format.createTextSampleFormat(null, videoSubtitleModel.getCaptionMimeType(), null, Format.NO_VALUE, Format.NO_VALUE, videoSubtitleModel.getCaptionSrcLang(), null);
  mediaSources[i + 1] = new 
  SingleSampleMediaSource(Uri.parse(videoSubtitleModel.getCaptioningUrl()), dataSourceFactory, textFormat, C.TIME_UNSET);
}
MediaSource mediaSourceWithText = new MergingMediaSource(mediaSources);

// Prepare the player with the source.
player.prepare(mediaSourceWithText);
```

**Comment by pedromfmachado** [comment]
Did you fins any solution for this? I'm facing the same issue

**Comment by minaEweida** [comment]
The only solution I have now is to validate each Text Url before passing it to exoplayer.

**Comment by AquilesCanta** [comment]
Let's use this issue to track relaxing loading errors for the SingleSampleMediaSource to allow playback to continue in these cases.

**Comment by pedromfmachado** [comment]
@AquilesCanta I have a similar issue: 
I have several ExtractorMediaSource loaded with a MergingMediaSource and if one of them does not exist (404 error) the player fails to play. Is this the expected behaviour even it all the other sources exist and are functioning correctly?

**Comment by ojw28** [comment]
As of the change above, it's possible to configure `SingleSampleMediaSource` to treat load failures in a way that doesn't cause an error to be propagated. @pedromfmachado - Yes that's expected, and your use case is different to the one tracked here. Please file a separate issue.

**Comment by talhatariq** [comment]
so why you are using
