### ISSUE TITLE
FLV extractor don't support format change

### ISSUE THREAD

**Issue by linyongsheng** [google/ExoPlayer#3141]
At most time, a FLV stream don't change it's  format once request.But in my app, the live stream will change it's input format without resend http request.The new format don't tell the codec, lead to the video or audio play error.

change ``VideoTagPayloadReader`` class line 85:
``if (packetType == AVC_PACKET_TYPE_SEQUENCE_HEADER && !hasOutputFormat) ``
to
``if (packetType == AVC_PACKET_TYPE_SEQUENCE_HEADER ) ``

the some problem in class ``AudioTagPayloadReader ``

**Comment by linyongsheng** [comment]
@ojw28

**Comment by ojw28** [comment]
Wouldn't the proposed change about cause the format to be output repeatedly, over and over again?

Aside: This is very low priority for us. FLV is very much legacy at this point.

**Comment by ojw28** [comment]
Closing; I don't think we're realistically ever going to get to this, and the proposal has not been clarified.
