### ISSUE TITLE
Choreographer.getInstance may throw NullPointerException

### ISSUE THREAD

**Issue by michalliu** [google/ExoPlayer#3144]
We've got some crash reports indicate that `Choreographer.getInstance()` may throw a NullPointerException inside framework. The stack as follows:

> java.lang.NullPointerException: Attempt to read from field 'float android.view.DisplayInfo.refreshRate' on a null object reference
> android.view.Choreographer.getRefreshRate(Choreographer.java:183)
> android.view.Choreographer.<init>(Choreographer.java:171)
> android.view.Choreographer.<init>(Choreographer.java:72)
> android.view.Choreographer$1.initialValue(Choreographer.java:98)
> android.view.Choreographer$1.initialValue(Choreographer.java:91)
> java.lang.ThreadLocal$Values.getAfterMiss(ThreadLocal.java:430)
> java.lang.ThreadLocal.get(ThreadLocal.java:65)
> android.view.Choreographer.getInstance(Choreographer.java:194)
> com.google.android.exoplayer2.video.VideoFrameReleaseTimeHelper$a.d(ProGuard:283)
> com.google.android.exoplayer2.video.VideoFrameReleaseTimeHelper$a.handleMessage(ProGuard:265)
> android.os.Handler.dispatchMessage(Handler.java:98)
> android.os.Looper.loop(Looper.java:135)
> android.os.HandlerThread.run(HandlerThread.java:61)

I attempted to fix the problem by the following patch https://github.com/michalliu/ExoPlayer/commit/b11f7fa9d87f16eb8abff6f1e53b496d0fa2dc87

Kindly please review the patch, Thanks

**Comment by ojw28** [comment]
Please provide details of the devices on which you're seeing this, and in particular the build fingerprint (or similar) identifying what version of Android is being run on the device.

**Comment by michalliu** [comment]
We found the crash on various devices and android versions as follows
![android-version](https://user-images.githubusercontent.com/1010851/29020224-de708830-7b93-11e7-91dc-a279b7c549a1.png)
![models](https://user-images.githubusercontent.com/1010851/29020235-e765c2c0-7b93-11e7-9ba6-11fffbaa3882.png)

The ROMS list:
1. `vivo/FUNTOUCH/Funtouch OS_3.0 Lite`
2. `OnePlus/OnePlus2/OnePlus2:5.1.1/LMY47V/1436865039:user/release-keys/fail`
3. `ZTE/P839A01/msm8916_64:5.1.1/LMY47V/zte.20160130.135926:user/release-keys/fail`
4. `samsung/ja3gzc/ja3g:5.0.1/LRX22C/I9500ZCUIQD1:user/release-keys/fail`
5. `vivo/FUNTOUCH/Funtouch OS_2.5`
6. `alps/full_ali6735m_35gc_a_l1/ali6735m_35gc_a_l1:5.1/LMY47D/1469676685:user/release-keys/fail`
7. `Oppo/COLOROS/V2.1`
8. `Oppo/COLOROS/V3.0_170510_Beta`

and many

**Comment by michalliu** [comment]
This is crash stack happens on android 5.1.1

> java.lang.NullPointerException: Attempt to read from field 'float android.view.DisplayInfo.refreshRate' on a null object reference
> android.view.Choreographer.getRefreshRate(Choreographer.java:181)
> android.view.Choreographer.<init>(Choreographer.java:170)
> android.view.Choreographer.<init>(Choreographer.java:72)
> android.view.Choreographer$1.initialValue(Choreographer.java:98)
> android.view.Choreographer$1.initialValue(Choreographer.java:91)
> java.lang.ThreadLocal$Values.getAfterMiss(ThreadLocal.java:430)
> java.lang.ThreadLocal.get(ThreadLocal.java:65)
> android.view.Choreographer.getInstance(Choreographer.java:192)
> com.google.android.exoplayer2.video.VideoFrameReleaseTimeHelper$a.d(ProGuard:283)
> com.google.android.exoplayer2.video.VideoFrameReleaseTimeHelper$a.handleMessage(ProGuard:265)
> android.os.Handler.dispatchMessage(Handler.java:98)
> android.os.Looper.loop(Looper.java:139)
> android.os.HandlerThread.run(HandlerThread.java:61)

ROM is `OnePlus/OnePlus2/OnePlus2:5.1.1/LMY47V/1436865039:user/release-keys/fail`
Which matches the code http://androidxref.com/5.1.1_r6/xref/frameworks/base/core/java/android/view/Choreographer.java

`DisplayManagerGlobal.getInstance().getDisplayInfo` may returns null  under some circumstance indeed

http://androidxref.com/5.1.1_r6/xref/frameworks/base/core/java/android/hardware/display/DisplayManagerGlobal.java

**Comment by michalliu** [comment]
The crash rate is very low, It's better to handle the problem though.

**Comment by ojw28** [comment]
It's likely that the second issue is handled by https://github.com/google/ExoPlayer/commit/dbfbcd63125fbb34bfc98ac4786393617c3c16e1.

**Comment by ojw28** [comment]
Actually, it's likely that this issue is fully handled already by https://github.com/google/ExoPlayer/commit/dbfbcd63125fbb34bfc98ac4786393617c3c16e1. Please report this again if you still observe the issue after the 2.5.0 release.

**Comment by michalliu** [comment]
emm, not exactly same issue. The crash is at different location,  the fix https://github.com/google/ExoPlayer/commit/dbfbcd63125fbb34bfc98ac4786393617c3c16e1 resolves the problem partially. I will send another PR for this issue

**Comment by ojw28** [comment]
I know it's in a different location, but if `getDefaultDisplayRefreshRate` returns 0 then the code that you're seeing crash wont ever execute (and I suspect that `getDefaultDisplayRefreshRate` will always return 0 in the cases where the crash you're seeing occurs).
