### ISSUE TITLE
How to send custom header in exoplayer while playing mpd widevine

### ISSUE THREAD

**Issue by skyshine999** [google/ExoPlayer#3145]
I wanted to send headers to server for authentication purpose,i read previous issues for setting custom header i tried with httpdatasource adding headers to it but from server side they are not able to receive is there any other process to send custom headers

**Comment by ojw28** [comment]
Without describing what you've tried in any detail, it's not possible for us to offer any guidance as to what you might be doing wrong.

**Comment by ojw28** [comment]
Closing due to lack of information.
