### ISSUE TITLE
Question: Playing video with partial cache?

### ISSUE THREAD

**Issue by xdestiny110** [google/ExoPlayer#3148]
I have cache a part of video from plain http by using simplecache. When I try to play cache video without internet connection it says "source error". 
My question is that does exoplayer support that playing cache video without internet connection? 
If not, would you please give me some advices?

**Comment by ojw28** [comment]
You would expect playback to fail upon reaching a non-cached part of the video. If playback is failing at the start then it's possible the media is structured in a way that requires the player to read the end of the file before it can start playback (this is relatively common for Matroska/WebM streams).

**Comment by xdestiny110** [comment]
@ojw28 Thanks to your answer! I move meta file header to head in mp4 file by using [faststart](https://github.com/FFmpeg/FFmpeg/blob/master/tools/qt-faststart.c) . Now I can play video without internet.
