### ISSUE TITLE
Allow extending TimestampAdjuster

### ISSUE THREAD

**Issue by fougere-mike** [google/ExoPlayer#3152]
I am implementing exoplayer components to allow playback of mpeg-ts video recorded from over the air broadcasts (including the ability to seek). 

Since these broadcasts are continuous, the timestamps can grow very large. When a 'recording' is made by saving a window of the broadcast to disk, the first timestamp in the recorded video will often be many days, or weeks. 

This appears to break the intended behaviour of `TimestampAdjuster`. When a seek is performed, [TsExtractor resets the TimestampAdjuster](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/extractor/ts/TsExtractor.java#L202), which triggers the [timestamp offset to be recalculated](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/util/TimestampAdjuster.java#L146), using a `firstSampleTimestamp` of 0.

For my seeking implementation to work correctly, I need to calculate the timestamp offset of the first frame of the video, and always use that as the adjustment, even after seeking:
```
    /**
     * Offsets a sample timestamp in microseconds.
     *
     * @param timeUs The timestamp of a sample to adjust.
     * @return The adjusted timestamp in microseconds.
     */
    public long adjustSampleTimestamp(long timeUs) {
        if (timeUs == C.TIME_UNSET) {
            return C.TIME_UNSET;
        }

        // Record the adjusted PTS to adjust for wraparound next time.
        if (lastSampleTimestamp != C.TIME_UNSET) {
            lastSampleTimestamp = timeUs;
        } else {
            // ========================================================
            // This line modified. `timestampOffsetUs` is initialised to `C.TIME_UNSET` in the constructor.
            // ========================================================
            if (timestampOffsetUs == C.TIME_UNSET && firstSampleTimestampUs != DO_NOT_OFFSET) {
                // Calculate the timestamp offset.
                timestampOffsetUs = firstSampleTimestampUs - timeUs;
            }
            synchronized (this) {
                lastSampleTimestamp = timeUs;
                // Notify threads waiting for this adjuster to be initialized.
                notifyAll();
            }
        }
        return timeUs + timestampOffsetUs;
    }
```
This way, the `timestampOffsetUs` is only calculated once. This solution has been tested, and seems to work. (That said, if anyone can think of a different approach that could work, I'd love to hear it.)

The issue I'm having is that `TimestampAdjuster` is marked `final`, which means I can't provide my customised implementation to `TsExtractor`. In fact, the only way I've found to actually use my custom `TimestampAdjuster` is to copy-paste-modify the following classes:
- `TsExtractor`
- `TsExtractorsFactory`
- `TsPayloadReader`
- `TsPayloadReaderFactory`
- `TsPesReader`
- `TsSectionPayloadReader`
- `TsSectionReader`

This is obviously undesirable. Is there any possibility of refactoring `TimestampAdjuster` to be an interface with a default implementation? Or perhaps just remove `final` from `TimestampAdjuster`?

It's very possible my custom `TimestampAdjuster` is not the correct solution to my problem, so I'm happy to hear if anyone has a different approach that could work.

**Comment by fougere-mike** [comment]
@ojw28 Any update on this? I'm updating my fork and hit the same issue again.

**Comment by AquilesCanta** [comment]
Sorry, this fell off my radar. I'll see what I can do.

**Comment by AquilesCanta** [comment]
Would you be okay with having a TimestampAdjuster interface, with the current TimestampAdjuster becoming DefaultTimestampAdjuster? In practice, I think this means you'd have to fork TsExtractor only. Would this work for you?

**Comment by AquilesCanta** [comment]
By the way, have you tried seeking in v2.9.0?

**Comment by fougere-mike** [comment]
I would be fine with an interface, and I believe one of TsExtractor's constructors accepts either a `TimestampAdjuster` or `TimestampAdjusterProvider`, so that should work fine.

I wasn't aware anything around seeking mpeg2 had changed in v2.9.0, so I'll give it a shot and report back.

**Comment by fougere-mike** [comment]
Seeking appears to work quite well now. The only issue I have is that the duration isn't updated if the file is being played _while_ still being written (a "live" recording).

The TimestampAdjuster worked as expected though, which I think means I can stop using a fork, and just supply my own MediaSource that refreshes the duration.

**Comment by AquilesCanta** [comment]
Can we close this issue then? If you end up running into any issues we can revisit this.

You can post below and we will reopen the issue.
