### ISSUE TITLE
How to stream encrypted file using exoplayer (sample)?

### ISSUE THREAD

**Issue by ghost** [google/ExoPlayer#3159]
I am trying to stream encrypted audio file (.mp3),but I do not know how to achieve this. I am requesting a sample, or some form of direction to do that?. There is an issue here https://github.com/google/ExoPlayer/issues/2467 but it is discussing play local encrypted file. Thanks for help.

**Comment by andrewlewis** [comment]
There's not really enough information here to give specific advice, and it's probably beyond the scope of the issue tracker anyway. If the server is just providing an encrypted file, you could decrypt in a custom `DataSource` (possibly like `AesCipherDataSource`).
