### ISSUE TITLE
Ffmpeg extension support

### ISSUE THREAD

**Issue by andersonkxiass** [google/ExoPlayer#3162]
I've seen some relations issue about ffmpeg extension support, but no one help me to understanding how to ffmpeg extension work in exoplayer.

I've sent a email to dev.exoplayer@gmail.com

> I've tried to player some formats that are supported for Ffmpeg extension. So, after made the Ffmpeg build  (https://github.com/google/ExoPlayer/tree/release-v2/extensions/ffmpeg) and generate aar file,i putted aar file to my project and so I tried to player Amr format but I'm getting error:(https://stackoverflow.com/questions/45515166/exoplayer-2-amr-format-using-ffmpeg-extension) 

How to use **Ffmpeg** extension? 

Does the Flac extension have a `FlacExtractor` as each stand-alone supported format, **ffmpeg** must have an Extractor for each item in the supported list?

```
AMR-NB  | –enable-decoder=amrnb
AMR-WB | –enable-decoder=amrwb
AAC         | –enable-decoder=aac
```
So i need to write:

`AmrNbExtractor, AmrWbExtractor, AACExtractor` ?

So, someone can explain how to ffmpeg extension work in fact?

**Comment by ojw28** [comment]
The extension provides a `Renderer` only. You can see the classes that it provides in our [Javadoc](http://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/ext/ffmpeg/package-summary.html). The extension does not provide any extractors.

**Comment by ojw28** [comment]
Let's provide some brief instructions for using the extension.

**Comment by andersonkxiass** [comment]
@ojw28  I'll try to apply according instructions in the readme. Thank you for reply.
