### ISSUE TITLE
failed to resolve "support-core-utils" and "support-annotations" when upgrading to 2.5.X

### ISSUE THREAD

**Issue by or-dvir** [google/ExoPlayer#3168]
hi.
currently i am using version 2.4.4 and everything works fine. however when trying to upgrade to 2.5.0 or 2.5.1 i get the following errors:
Failed to resolve: com.android.support:support-core-utils:25.4.0
Failed to resolve: com.android.support:support-annotations:25.4.0

any ideas?

**Comment by ojw28** [comment]
The support libraries have moved. You need to add the Google maven repository to your project, like [this](https://github.com/google/ExoPlayer/blob/release-v2/build.gradle#L34).

**Comment by or-dvir** [comment]
@ojw28 thank you it worked :)
