### ISSUE TITLE
Video frame lag for 1080p videos after 12 hours of non-stop playback

### ISSUE THREAD

**Issue by vishnuganta22** [google/ExoPlayer#3175]
### Issue description
We have a 1080p video to be played constantly on device more than 15hours. Initial playback will be fine. After 10 or 12 hours of playback 1080p videos are getting slow or freezing. I am not sure whether it's a slow frame issue or not. But audio playback is fine, we never observed any disturbance with audio in that player state 

### Reproduction steps
- Play a video with below properties more than 10 hours

Properties
Video:
Dimensions : 1920 x 1080
Codec: H.264
Framerate: 30 frames per second
Bitrate : 4116 kbps

Audio:
Codec: MPEG-4 AAC
Channels: Stereo
Sample rate: 48000 Hz
Bitrate: 92kbps

### Version of ExoPlayer being used
ExoPlayer Version: 2.5.1

### Device(s) and version(s) of Android being used
Android Version: 5.1.1

Device Name: MINIX NEO X9

### A full bug report captured from the device
You can watch this video for a better understanding of the behavior https://vimeo.com/229807293

**Comment by rohit5ram** [comment]
Even I face the same issue @ojw28 @andrewlewis

**Comment by kedarnath9** [comment]
We have been facing the same. In our use case, we have to play 1080p videos for more than 18 hours. After 10 + hours of playback 1080p videos started shuttering or lag between frames is observed.

**Comment by andrewlewis** [comment]
Please could you provide specific steps to reproduce in the ExoPlayer demo app? Do you see this behavior if you loop one of the samples in the ExoPlayer demo app for example? Is it device-specific?

Do you see anything suspicious if you attach the [Android monitor](https://developer.android.com/studio/profile/am-basics.html) in Android Studio? It would be interesting to look at a method trace, heap dump and systrace to see if there is anything strange going on.

**Comment by rohit5ram** [comment]
@andrewlewis  Android monitor didn't show any thing suspicious. The CPU and Memory profile was very stable. @vishnuganta22 can help you with the steps to reproduce. It's not device specific as we tried with AndroidMediaPlayer and everything worked brilliantly.

**Comment by vishnuganta22** [comment]
@ojw28 and @andrewlewis 
Any update on this

**Comment by andrewlewis** [comment]
@vishnuganta22 Please could you provide specific steps to reproduce in the ExoPlayer demo app? Do you see this behavior if you loop one of the samples in the ExoPlayer demo app for example? Is it device-specific?

**Comment by vishnuganta22** [comment]
@andrewlewis we didn't tried it on Exoplayer Demo App
We will try to reproduce it on Demo App and let you know

**Comment by aldocano** [comment]
Can you please provide help on playing that type of vimeo url? 
Like this https://vimeo.com/229807293 you mentioned above?

**Comment by andrewlewis** [comment]
@aldocano For help on playing videos from a particular provider, I suggest searching their documentation or contacting them directly. This isn't really a question for the ExoPlayer team.

Regarding the original issue: I think we don't have enough information to investigate effectively, so I'll close this. If you can provide steps to reproduce in the ExoPlayer demo app, please file a new issue. If it's not reproducible in the demo app, maybe the application has a leak or some other bug that causes the slowness.
