### ISSUE TITLE
Rendering freeze when video quality changes due to bandwidth throttling

### ISSUE THREAD

**Issue by soadri** [google/ExoPlayer#3176]
### Issue description
When video quality changes due to bandwidth throttling, video rendering freeze occurs but audio does not

### Reproduction steps
Testing in the 2 android devices, the problem is occurred on both devices

### Link to test content
Attaching mpd file that I used for test below
and test content is a 4K video downloading in YouTube site 'LG Jazz HDR'

### Version of ExoPlayer being used
ExoPlayer 2.4.4

### Device(s) and version(s) of Android being used
LG v20 - Android 7.0 (First case)
Samsung Galaxy Note II - Android 4.4.2 (Second case)

### A full bug report captured from the device
Attaching LogCat file including the problem situation

First case, I make the mpd file using MP4Box in the Linux Server (Ubuntu)

and I modified ExoPlayer demo app that can play the my content (in the Linux Server)

When playing the content with no bandwidth throttling, demo player has no problem

but with bandwidth throttling using tc (used in Linux) and when segment quality requested by demo player is changed, video rendering freeze is occurred and dropping frame is also occurred can be seen below attached LogCat file

Second case is same as the first case!

[mpd.txt](https://github.com/google/ExoPlayer/files/1227395/mpd.txt)
[LogCat.txt](https://github.com/google/ExoPlayer/files/1227396/LogCat.txt)

**Comment by soadri** [comment]
https://www.youtube.com/watch?v=0YQZGRHWShg&t=20s
https://www.youtube.com/watch?v=I7CycuMpQ3w

I tested more using these videos, the same problem is occurred again that referred in this issue

**Comment by soadri** [comment]
.

**Comment by soadri** [comment]
I also found same problem when using dash.js reference player in same situation

**Comment by ojw28** [comment]
That kind of suggests the source media is broken, doesn't it? In which case there's nothing we can do to help here unless you're able to host some content that reproduces the problem and provide a working link to it.

I can't see anything obvious in the logs. It looks like playback starts at 2160p and is working fine. It then successfully switches to 720p. It then switches back to 2160p and at this point starts to drop all frames. There's nothing to indicate why though.

**Comment by soadri** [comment]
@ojw28 

It successfully switches to other quality, but player screen freezes after quality switching

Freezing means here that the picture on player screen is stop and never change to the next picture, no motion

Player timeline bar still progress but screen is stopped when video quality is changed

Sorry, I didn't refer the more detail situation

1) Playback starts at 2160p

2) At this point, I throttle the contents server's bandwidth using Linux tc command

3) So, quality switches to 720p

4) After a while, I remove the bandwidth limit

5) Quality switches to 2160p and player screen freezes (audio plays well, the problem is occurred only video)

When player screen freezes, can show 'droppedFrame' log in LogCat

Thank you for read this

**Comment by soadri** [comment]
@ojw28 

The problem of this issue may be caused by scarce processing power of client device or server

It is not because of ExoPlayer internal features

So this issue is closed
