### ISSUE TITLE
skipping 10 sec forward of backward

### ISSUE THREAD

**Issue by lazarvgd** [google/ExoPlayer#3177]
First of all I want to say sorry if this is duplicate question, I couldn't find the same or similar question.

Question:
Is there an option in exoplayer that allows skipping 10 seconds forward or backward? This feature is something like on YouTube when you press right or left arrow( J or L keys).

Thanks

**Comment by ojw28** [comment]
`player.seekTo(player.getCurrentPosition() + 10000)` would seek forward 10 seconds (similar to seek backward)?

**Comment by lazarvgd** [comment]
Thank you very much sir! :+1:
