### ISSUE TITLE
Offline clear key drm 

### ISSUE THREAD

**Issue by mhassanist** [google/ExoPlayer#3178]
Is there a clear simple way now to implement Clear Key DRM in ExoPlayer 2 ?
I have the keyID and KeyValue and the video URL is **online**  however the keys are stored offline. I just want to set the keys by hand instead of getting them from license server.

**Comment by ojw28** [comment]
Clarification around ClearKey support is tracked by https://github.com/google/ExoPlayer/issues/3138.

**Comment by mhassanist** [comment]
I'm able to get the clear key to work if I put the response on the server.
http://ec2-52-42-32-95.us-west-2.compute.amazonaws.com/shaka/shaka_final/request.php 

My question is how to set those values on the player without requesting it from online server.

**Comment by ojw28** [comment]
You will have to implement a `MediaDrmCallback` that provides a local response.

**Comment by mhassanist** [comment]
Thanks a lot for your replay.

Do you have or can provide any example or sample code for this ?

**Comment by mhassanist** [comment]
I made this. But not sure how to return the key value from these methods.

```
public class MyDRMCallBack implements MediaDrmCallback {
    @Override
    public byte[] executeProvisionRequest(UUID uuid, ExoMediaDrm.ProvisionRequest request) throws Exception {
        return new byte[0];
    }

    @Override
    public byte[] executeKeyRequest(UUID uuid, ExoMediaDrm.KeyRequest request) throws Exception {
        return new byte[0];
    }
}
```

**Comment by ojw28** [comment]
I don't think provisioning is relevant. For the key request you'll need to respond with whatever the server response would be.

**Comment by mhassanist** [comment]
It worked thank yo very much for your support.
Here is the final class is some one needs it.
```

import com.google.android.exoplayer2.drm.ExoMediaDrm;
import com.google.android.exoplayer2.drm.MediaDrmCallback;
import java.util.UUID;

public class MyDRMCallBack implements MediaDrmCallback {

    String keyString;

    @Override
    public byte[] executeProvisionRequest(UUID uuid, ExoMediaDrm.ProvisionRequest request) throws Exception {
        return new byte[0];
    }

    public MyDRMCallBack(String keyId, String keyValue) {
        this.keyString = "{\"keys\":[{\"kty\":\"oct\",\"k\":\""+keyValue+"\",\"kid\":\""+keyId+"\"}],\"type\":\"temporary\"}";;
    }

    @Override
    public byte[] executeKeyRequest(UUID uuid, ExoMediaDrm.KeyRequest request) throws Exception {
        return keyString.getBytes();
    }
}

```

**Comment by ojw28** [comment]
Glad you got it working! You can probably throw `UnsupportedOperationException` from `executeProvisionRequest`, since you're basically not supporting it :). The ClearKey CDM should never request provisioning from the callback, as far as I'm aware.

**Comment by ojw28** [comment]
By the way, how would you feel about making a pull request to contribute this back to the `dev-v2` branch, in the `drm` package, called something like `LocalClearKeyMediaDrmCallback`? Please feel free to send a pull request if you're able.
