### ISSUE TITLE
how to implement tap to play in exoplayer

### ISSUE THREAD

**Issue by mehulTank** [google/ExoPlayer#3179]
This library very fine helpful to me but i want try from many time to implement tap top play in recycle view but not get proper output is it possible to implement to tap to play here in recycle view ?

**Comment by ojw28** [comment]
ExoPlayer provides a method to play (e.g. `setPlayWhenReady(true)`. How you wire that up to UI is not really an ExoPlayer question, so I'd suggest you ask on StackOverflow.
