### ISSUE TITLE
Cannot playback H262 after wrapping it in MP4 by FFMpeg

### ISSUE THREAD

**Issue by WeiChungChang** [google/ExoPlayer#3181]
### Issue description
Cannot playback H262 after wrapping it in MP4 by FFMpeg.

### Reproduction steps
https://drive.google.com/open?id=0B7H5vJR3qWj0NjJEb0JLb3pvc28

```
      {
        "name": "output.mp4",
        "uri": "asset:///output.mp4"
      },
```

### Link to test content
https://drive.google.com/open?id=0B7H5vJR3qWj0NjJEb0JLb3pvc28

### Version of ExoPlayer being used
r2.5.0-beta1

### Device(s) and version(s) of Android being used
HTC-X9

### A full bug report captured from the device
It has only audio but no video (black screen)

**Comment by ojw28** [comment]
Pull request was merged. Thanks!
