### ISSUE TITLE
Playback stops at when quality reach 1080p in Amlogic S905X

### ISSUE THREAD

**Issue by JacksonFoo** [google/ExoPlayer#3183]
**Issue description**

This is an error that regard "Caused by: android.media.MediaCodec$CryptoException: Unknown Error" occurred when playing 1080p bitrate for Widevine in the Amlogic Chipset
If this error occurs, playback can not be resumed unless you press the retry button and exit.
It occurs in X96 STB

**Link to test content**
none

**Version of ExoPlayer being used**
r2.4.4

**Device(s) and version(s) of Android being used**
X96 STB
Android 6.0.1

**Widevine Info Returned by Widevine Server**
[https://www.dropbox.com/s/wezq7tnu4w4nqjn/widevine_modular_amlogic_s905x.json?dl=0](url)

**A full bug report captured from the device**
[https://www.dropbox.com/s/i0yu0ksglveor0p/error_log_s905x.txt?dl=0](url)

Thank you and best regards,

**Comment by Stane1983** [comment]
Can you give more details on issue? Which Android 6 SDK release (from Amlogic)? Which sample? There is issue with newer SDKs from Amlogic (including Nougat) where ExoPlayer crashes even before playback starts but that is debugged and fixed today actually in cooperation with Amlogic engineer. Fix is simple:
Add:
`-keep class com.google.android.exoplayer2.ext.vp9.LibvpxVideoRenderer{*;}`
to proguard rules.

Error mentioned was happening on any stream on S905x and S912.

**Comment by JacksonFoo** [comment]
@Stane1983 Hi Stane, Sure. 
This issues is happening only h264 1080p not vp9 format, in additional I don't use vp9 software decoder provided by exoplayer. For vp9 I able to play any video quality up to 4k UHD, but h264 only able to play up to 720p not even 4k UHD. 

My temporary solution is cap the resolution or quality to 720p. 

Here are the details of X96 full details of firmware info.
https://www.dropbox.com/s/xx27ojoak9ccj2u/Screenshot_20170830-150358.png?dl=0

Please let me know if you any idea to solve this.

Thanks

**Comment by Stane1983** [comment]
@JacksonFoo are you building firmware yourself? What I'm interested in if you have installed ReadLog Amlogic application to grab all logs to USB and send it to me so I can forward it to Amlogic engineer for further inspection.

**Comment by JacksonFoo** [comment]
@Stane1983 Nope, the box are using original firmware. Alright sure I will install the [readlog](https://www.dropbox.com/s/rnt8j86g8ebgmcu/ReadLog.apk?dl=0) and grab the log for you. 

Thanks for helping out.

**Comment by JacksonFoo** [comment]
@Stane1983 Here are the logs that you have requested [https://www.dropbox.com/s/vx7lk095smep1ts/logcat_and_device_info.zip?dl=0](url) , please let me know whether this sufficient for you.

**Comment by ojw28** [comment]
Sorry we didn't look at this. It's most likely that you're trying to play secure content on a device that only has L3 Widevine (i.e. failure is working as intended because the required security level is not satisfied), or a device specific issue. If this issue is still relevant, I suggest you follow up with Amlogic to find out what's wrong.
