### ISSUE TITLE
Performance issues with BT.709 color space

### ISSUE THREAD

**Issue by danha306** [google/ExoPlayer#3186]
### Issue description
We have a performance problem that arises with high bitrate H.264 Widevine-protected DASH content in combination with color space BT.709. On some phones this combination results in very choppy, borderline unwatchable videos. Converting the video to YUV420, while keeping the bitrate and other settings, provides smooth playback on the affected phones.

Our hope is that there is a way of improving the other performance other than converting the videos, as that would take up a lot of time and storage on our part.

### Reproduction steps
This can be reproduced by playing one of our media files on one of the affected phones.

### Link to test content
Test content mailed to dev.exoplayer@gmail.com.

### Version of ExoPlayer being used
2.4.0

### Device(s) and version(s) of Android being used
Several devices reported by users, but the ones we have on hand are:
Samsung Galaxy A5 (2017) (Android 6.0.1)
Sony Experia Z5 Compact (Android 7.1)

### A full bug report captured from the device
Bug report mailed to dev.exoplayer@gmail.com.

**Comment by ojw28** [comment]
It seems unlikely we'd be able to do anything about this. The performance is probably in the decoder or underlying graphics pipeline in the platform.

**Comment by danha306** [comment]
That's pretty much in line with what we thought, but we figured we might as well ask in case there was something obvious that we had missed. Thank you for a quick response.
