### ISSUE TITLE
 ExoPlayer.EventListener() is depricated

### ISSUE THREAD

**Issue by lazarvgd** [google/ExoPlayer#3192]
Hi after updating ExoPlayer to version r2.5.1 I got the problem that  **ExoPlayer.EventListener()** is depricated. What can I use instead of this event listener in order to get **onPlayerError** so I can detect **[BLWE](https://github.com/google/ExoPlayer/issues/1074)**?

thanks :)

**Comment by ojw28** [comment]
Please look at the Javadoc:
http://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/ExoPlayer.EventListener.html

**Comment by lazarvgd** [comment]
@ojw28 I have looked at that doc but still didn't get the information about what can I use instead of this listener. Please help me with this. thanks

**Comment by ojw28** [comment]
The only thing written there is "Use Player.EventListener instead.". Which presumably answers your question.

**Comment by lazarvgd** [comment]
Thank you and sorry. I did not understand the doc. It is my fault, please sorry :)

**Comment by ojw28** [comment]
Heh, no problem :)!
