### ISSUE TITLE
Huawei Honor PE-TL10 - SIGSEGV with dlfree(libc) when playing DASH video

### ISSUE THREAD

**Issue by sshurick** [google/ExoPlayer#3193]
### Issue description
Hi, guys!

I run into a problem: my App crashes very often when playing DASH video on Youtube:

Here is the top of the stack trace.
08-18 16:34:39.855  2449  2449 I DEBUG   :     #00  pc 00011978  /system/lib/libc.so (dlfree+1191)
08-18 16:34:39.855  2449  2449 I DEBUG   :     #01  pc 0000dec7  /system/lib/libc.so (free+10)
08-18 16:34:39.855  2449  2449 I DEBUG   :     #02  pc 0008394b  /system/lib/libcrypto.so (CRYPTO_free+34)
08-18 16:34:39.855  2449  2449 I DEBUG   :     #03  pc 0002f673  /system/lib/libssl.so (ssl_parse_serverhello_tlsext+738)
08-18 16:34:39.855  2449  2449 I DEBUG   :     #04  pc 000181d1  /system/lib/libssl.so (ssl3_get_server_hello+1008)

see the bugreport for the full stacktrace.

I have found the issue with the similar dlfree at the top of the stack
https://github.com/google/ExoPlayer/issues/3071
but the bugreport it contains (log2.txt) has the different stack trace, containing libstagefright.so (Mediacodec) on the stack.  So the issues look different.

### Reproduction steps
Just add the link to the test content to ExoPlayer-demo
Play the video, and it will most likely crash soon (especially on start)

### Link to test content
https://manifest.googlevideo.com/api/manifest/dash/playback_host/r4---sn-hxb54vo-238l.googlevideo.com/id/feaebd78ef85f6a8/key/yt6/mn/sn-hxb54vo-238l/mm/31/expire/1503076915/ms/au/requiressl/yes/ei/0s2WWaT1OMiT7ASF7rKABg/pl/19/mv/m/initcwndbps/2056250/ipbits/0/mt/1503055203/ip/195.144.226.238/sparams/as%2Cei%2Chfr%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Cmm%2Cmn%2Cms%2Cmv%2Cpcm2cms%2Cpl%2Cplayback_host%2Crequiressl%2Csource%2Cexpire/signature/AF7DA87F97E27AF921E62B3BD669B576E1EB46EE.172FFBE19E49130AB5C5EDDD0B91AB1656946837/as/fmp4_audio_clear%2Cfmp4_sd_hd_clear/hfr/1/pcm2cms/yes/source/youtube/itag/0

### Version of ExoPlayer being used
2.5.1

### Device(s) and version(s) of Android being used
Huawei Honor PE-TL10 Running android 4.4.2
The issue is not reproducible on other devices I tested (Samsung, Nexus9) running Android 6+

### A full bug report captured from the device
attached
[log2.txt.zip](https://github.com/google/ExoPlayer/files/1234824/log2.txt.zip)

Thank you in advance )

**Comment by sshurick** [comment]
I have also caught one more crash with this DASH content on Meizu MX4  running android 4.4.2

Stack trace of the crash is pretty much the same:

08-18 18:52:44.322 6003-6003/? I/DEBUG:     #00  pc 00026690  /system/lib/libc.so (tgkill+12)
08-18 18:52:44.322 6003-6003/? I/DEBUG:     #01  pc 00017c95  /system/lib/libc.so (pthread_kill+64)
08-18 18:52:44.322 6003-6003/? I/DEBUG:     #02  pc 00017e8d  /system/lib/libc.so (raise+10)
08-18 18:52:44.322 6003-6003/? I/DEBUG:     #03  pc 00016ba7  /system/lib/libc.so
08-18 18:52:44.322 6003-6003/? I/DEBUG:     #04  pc 00025f40  /system/lib/libc.so (abort+4)
08-18 18:52:44.322 6003-6003/? I/DEBUG:     #05  pc 00015d54  /system/lib/libc.so (dlfree+2376)
08-18 18:52:44.322 6003-6003/? I/DEBUG:     #06  pc 0008ce4f  /system/lib/libcrypto.so (CRYPTO_free+34)
08-18 18:52:44.322 6003-6003/? I/DEBUG:     #07  pc 000342bf  /system/lib/libssl.so (ssl_parse_serverhello_tlsext+738)
08-18 18:52:44.322 6003-6003/? I/DEBUG:     #08  pc 000197c3  /system/lib/libssl.so (ssl3_get_server_hello+1202)

I can try to reproduce the issue to get the crash report if needed.

**Comment by ojw28** [comment]
I think this is a platform issue. It would need to be reported to (and most likely fixed by) Huawei directly. Closing as obsolete, since we're not going to be able to do anything about it in ExoPlayer.
