### ISSUE TITLE
Add option to insert Media at specific index in DynamicConcatenatingMediaSource

### ISSUE THREAD

**Issue by b0g8** [google/ExoPlayer#3195]
### Issue description
Currently, if adding with addMediaSource(int index, MediaSource mediaSource), it replaces the item in a DynamicConcatenatingMediaSource. Also,  if one chooses to move an item, the item is removed from current position(ok) and replacing the destination(nok).

This is not consistent with the behavior of ArrayList, for example, where moving an item means that it is inserted at destination, and shifts destination and following items.

Please, either change the current behavior, or add an option to insert items, not just replace.

### Version of ExoPlayer being used
2.5.1

### Device(s) and version(s) of Android being used
all

**Comment by ojw28** [comment]
Are you certain that's what happens? Internally `DyanamicConcatenatingMediaSource` looks like it's calling through to `ArrayList.add`, so it's difficult to see how the behavior you're observing can occur. How are you determining that items are being removed/replaced (i.e. what's the exact sequence of calls you're making)? Thanks.

**Comment by b0g8** [comment]
I can confirm that now it works properly, without any changes in code regarding MediaSource. Previously, I got an exception from DyanamicConcatenatingMediaSource related to index out of range. Maybe it was due to some other stuff that was in work on my side. Anyway, I'll keep an eye on
it. Thanks.
