### ISSUE TITLE
Widevine L1 audio cannot be played.

### ISSUE THREAD

**Issue by rush0825** [google/ExoPlayer#3196]
Hi All, 
   White we test Exoplayer with customer asset, we found the Exoplayer cannot play L1 audio stream.
The logcat will show below. Could you show up what kind of this error and possible root cause ?

08-17 15:25:15.915  5122 18201 E ExoPlayerImplInternal: Renderer error.
08-17 15:25:15.915  5122 18201 E ExoPlayerImplInternal: com.google.android.exoplayer2.ExoPlaybackException
08-17 15:25:15.915  5122 18201 E ExoPlayerImplInternal:         at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:708)
08-17 15:25:15.915  5122 18201 E ExoPlayerImplInternal:         at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:511)
08-17 15:25:15.915  5122 18201 E ExoPlayerImplInternal:         at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:479)
08-17 15:25:15.915  5122 18201 E ExoPlayerImplInternal:         at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:308)
08-17 15:25:15.915  5122 18201 E ExoPlayerImplInternal:         at android.os.Handler.dispatchMessage(Handler.java:98)
08-17 15:25:15.915  5122 18201 E ExoPlayerImplInternal:         at android.os.Looper.loop(Looper.java:148)
08-17 15:25:15.915  5122 18201 E ExoPlayerImplInternal:         at android.os.HandlerThread.run(HandlerThread.java:61)
08-17 15:25:15.915  5122 18201 E ExoPlayerImplInternal: Caused by: android.media.MediaCodec$CryptoException: Unknown Error
08-17 15:25:15.915  5122 18201 E ExoPlayerImplInternal:         at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
08-17 15:25:15.915  5122 18201 E ExoPlayerImplInternal:         at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:2292)
08-17 15:25:15.915  5122 18201 E ExoPlayerImplInternal:         at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:699)
08-17 15:25:15.915  5122 18201 E ExoPlayerImplInternal:         ... 6 more
08-17 15:25:15.916  3639 18216 I OmxComponent: OMX_CommandStateSet 705 Cmd 0 nParam1 0x2
08-17 15:25:15.916  3639 18216 I OmxComponent: STATE_SET:   OMX_StateExecuting => OMX_StateIdle : OMX.amlogic.avc.decoder.awesome.secure
08-17 15:25:15.916  3639 18216 I OmxComponent: OMX.amlogic.avc.decoder.awesome.secure: flush input
08-17 15:25:15.916  3639 18216 V AmlogicVideoDecoderAwesome: flushInput:490 >
08-17 15:25:15.916  3639 18216 V OMX_WorkerPeer: hardware/amlogic/omx/omx_framework/WorkerPeer.cpp:flushInput:56 --------------------
08-17 15:25:15.916  3639 18216 V AmlogicVideoDecoderAwesome: pause:198 >
08-17 15:25:15.923  3639 18216 V AmlogicVideoDecoderAwesome: reset:238 >
08-17 15:25:15.923  3639 18216 D AmlogicVideoDecoderAwesome: reset_1
08-17 15:25:15.927  5122  5122 E EventLogger: playerFailed [4.29]

**Comment by ojw28** [comment]
I don't think any Android devices support "L1 audio" at this point in time. So I don't think you should be requiring a secure output path in your license policy for audio.

**Comment by rush0825** [comment]
Could it possible to post the right L1 policy to reference ?
Below is our customer policy, is it right ?
```javascript
 [{ "track_type": "UHD2",
 "security_level": 5,
 "required_output_protection": {"hdcp":
 "HDCP_NONE" }
 },
 { "track_type": "UHD1",
 "security_level": 5,
 "required_output_protection": {"hdcp":
 "HDCP_NONE" }
 },{ "track_type": "HD",
 "security_level": 5,
 "required_output_protection": {"hdcp":
 "HDCP_NONE" }
 },
 { "track_type": "SD",
 "security_level": 5
 },
 { "track_type": "AUDIO",
 "security_level": 1
 }]
```

**Comment by ojw28** [comment]
If you are a Widevine partner or have any contacts at Widevine you should reach out to them directly. If not, ping this again and I'll ask someone from Widevine to take a look.
