### ISSUE TITLE
RTMP Extension depends on GNU LGPL code

### ISSUE THREAD

**Issue by fboldog** [google/ExoPlayer#3197]
### Issue description
ExoPlayer RTMP extension depends on a project which contains GNU Lesser General Public License code.
Is this compatible with the ExoPlayer license?

### Link to test content
https://github.com/ant-media/LibRtmp-Client-for-Android/blob/master/rtmp-client/src/main/cpp/librtmp/rtmp.c

### Version of ExoPlayer being used
2.5.1

**Comment by ojw28** [comment]
I'm not really sure what you mean by "compatible". To use an extension you need to abide by the licenses of both the extension code in this repository (licensed under Apache 2.0) and any libraries that the extension you're using depends on (which may have their own, different licenses).

**Comment by fboldog** [comment]
Thanks, I thinking in the same way. 
Neither page mention about the copied librtmp source license and original source. 
Without digging into the source no one notified about this "problem".
It might be a good idea to include a statement somewhere in the documentation that extensions may have different licenses than ExoPlayer.

**Comment by ojw28** [comment]
Gradle seems to make it easy, in general, for you to pull in transient dependencies without knowing much about it. Librtmp could itself add a dependency of its own to some third library that also has a different license, for example. I think that as an app developer, you'll probably always need to check the whole dependency tree to see exactly what you're pulling in (and it seems people have written tools, for example [this](https://github.com/RobertFischer/Gradle-License-Report), to help).

We could add a general note in the README file of each extension, but I don't think it would solve the problem. You'd still end up having to check the whole dependency tree yourself regardless.

**Comment by ojw28** [comment]
Marking as an enhancement to add generic "dependencies may have different licenses" comment into the README of each extension.

**Comment by fboldog** [comment]
👍  Thanks.
