### ISSUE TITLE
ExoPlayer2 disables Next button but does not disable Previous button

### ISSUE THREAD

**Issue by SopMar** [google/ExoPlayer#3200]
I am using _ConcatenatingMediaSource_ to play Videos in a Sequence

I found a bug, Like I have three items in an ArrayList and currently playing first one, then it does not disables previous button (this is really bad thing).

Other hand, If I am playing 3rd one, then it disables next button (that is really good thing)

So how can I disable previous button, if I am playing first video item

Dependencies I am using:

```
compile 'com.google.android.exoplayer:exoplayer-core:r2.5.1'
compile 'com.google.android.exoplayer:exoplayer-dash:r2.5.1'
compile 'com.google.android.exoplayer:exoplayer-ui:r2.5.1'
```

**Comment by andrewlewis** [comment]
The previous button is also enabled if the user can seek back to the start of the current item (window), so I think this is working as intended. See the code in [`PlaybackControlView`](https://github.com/google/ExoPlayer/blob/b2da61f/library/ui/src/main/java/com/google/android/exoplayer2/ui/PlaybackControlView.java#L830).

If you need to implement previous/next buttons that only jump between playlist items, you could [customize the layout](https://medium.com/google-exoplayer/customizing-exoplayers-ui-components-728cf55ee07a) to hide the provided buttons and add your own buttons which have the behavior you need.
