### ISSUE TITLE
Caching content

### ISSUE THREAD

**Issue by moises-orduno** [google/ExoPlayer#3203]
### Issue description
I'm trying to download the mp4 content from the mpd url with the caching option

//creating a tempo folder

            tempFolder = Util.createTempDirectory(mView.getActivityContext(), "ExoPlayerTest");

//using the cache option

               DataSpec dataSpec = new DataSpec(Uri.parse("http://yt-dash-mse-test.commondatastorage.googleapis.com/media/car-20120827-manifest.mpd"));
               DataSource dataSource = mHttpDataSourceFactory.createDataSource();
                cache = new SimpleCache(tempFolder, new NoOpCacheEvictor());
                CacheUtil.CachingCounters counters = new CacheUtil.CachingCounters();
                CacheUtil.cache(dataSpec, cache, dataSource, counters);

but when I save it

                 CacheDataSource dataSource = new CacheDataSource(cache,  mHttpDataSourceFactory.createDataSource(), 0);

//define the stream to get the source
                
                File targetFile = new File("/storage/emulated/0/DCIM/Camera/tempfile");
                OutputStream outStream = new FileOutputStream(targetFile);
                DataSourceInputStream inputStream = new DataSourceInputStream(dataSource,
                        new DataSpec(Uri.parse(contentUrl), DataSpec.FLAG_ALLOW_CACHING_UNKNOWN_LENGTH));
                try {
                    inputStream.open();
                    byte[] buffer = new byte[1028];
                    int bytesRead;
                    while ((bytesRead = inputStream.read(buffer)) != -1) {
                        outStream.write(buffer, 0, bytesRead);

                    }

sometimes it saves it, sometimes it doesn't I wonder if it is not what is was intended for, does it mean that I have to download the content in another way?

### Reproduction steps
Describe how the issue can be reproduced, ideally using the ExoPlayer demo app.

### Link to test content
I'm using the content from http://dash-mse-test.appspot.com/media.html

### Version of ExoPlayer being used
2.5.0

### Device(s) and version(s) of Android being used
I'm using a Moto G4 Plus with Android 7

### A full bug report captured from the device
I'm not sure if this is an issue or not, I'm just trying to know if the cache implementation was meant for this kind of use

**Comment by ojw28** [comment]
The issue description isn't particularly clear. I don't really understand what the two code blocks referenced are for (why are there two blocks?). The second one doesn't seem to properly close either input or output streams, and so appears to be incomplete. Please provide complete information if you want us to take a look.

**Comment by moises-orduno** [comment]
@ojw28 Hi, I'm just trying to know if the new cache option can be used to download the video chunks as mp4 from the .mpd url

**Comment by ojw28** [comment]
Right, but the sample code attached is extremely unclear, which makes it hard to understand what you're doing (or trying to do). That aside, for downloading DASH content, you should look at `DashDownloader` in the `dev-v2` branch.
