### ISSUE TITLE
Is video seeking working in Exoplayer v1 with live smoothstreaming ?

### ISSUE THREAD

**Issue by idroji5** [google/ExoPlayer#3207]
Hello,

Is Exoplayer v1 live video seeking working or do I have to upgrade to Exoplayer latest version? 
I've tested Exoplayer latest version demo and seeking in live video streams is working, but i would like to know if there is option to make Exoplayer v1 working, because migration is hard at this point.

I am using PlayerControl.seekTo method but is not working in live streams, it is only working on VOD streams.

Many thanks!
Jordi

**Comment by AquilesCanta** [comment]
At this point we are only backporting bugfixes to V1, so unfortunately migration to V2 is the only option to get live seeking.

**Comment by idroji5** [comment]
Thanks, for your quick feedback
