### ISSUE TITLE
Ad - Error vast empty

### ISSUE THREAD

**Issue by imarenco** [google/ExoPlayer#3210]
### Issue description(IMA Extension)
I'm trying to use VAST files, but when it's empty, the player doesn't do content playback.

### Link to test content(Example empty vast)
- https://pubads.g.doubleclick.net/gampad/ads?slotname=/62955556/foxplay-qp-operadores-app/series/the-walking-dead/video/pre&sz=640x480&ciu_szs=&cmsid=3636&vid=1902841960&cust_params=auth_level%3Dbasic%26videoid%3D1902841960%26channel%3Dfox%26format%3Depisode%26userstatusid%3D51%26mso%3Dprensatoolbox%26collection%3D&url=&unviewed_position_start=1&output=xml_vast3&impl=s&env=vp&gdfp_req=1&ad_rule=0&vad_type=linear&vpos=preroll&pod=1&min_ad_duration=0&max_ad_duration=120000&ppos=1&lip=true&correlator=1503690413590

### Version of ExoPlayer being used
Version : 2.5.1

### Device(s) and version(s) of Android being used
test: Samsung J7 with Marshmallow(6.0.1)

### A full bug report captured from the device
The device doesn't return an error and the player doesn't do playback of the content.

### A full bug report captured from the device
8-26 20:27:36.422 2595-2595/com.tbxnet.experience W/ImaAdsLoader: onAdEvent: LOG
08-26 20:27:36.423 2595-2595/com.tbxnet.experience W/ImaAdsLoader:   type: adLoadError
08-26 20:27:36.423 2595-2595/com.tbxnet.experience W/ImaAdsLoader:   errorCode: 1009
08-26 20:27:36.423 2595-2595/com.tbxnet.experience W/ImaAdsLoader:   errorMessage: The response does not contain any valid ads.

**Comment by LauraTBX** [comment]
Any news about the issue?
I have the same problem!!!

**Comment by andrewlewis** [comment]
I couldn't reproduce this error using the ad tag provided above. I see an AdError VAST_EMPTY_RESPONSE 1009, but this is handled in ImaAdsLoader by resuming content. Please could you check the steps to reproduce? Thanks.

**Comment by ojw28** [comment]
I'm able to reproduce this, but it looks like everything is working as intended to me. The server isn't providing us with an ad in the VAST response, so we're not playing one. Playback of the content continues successfully. Please let us know if you disagree :).

**Comment by ojw28** [comment]
Correction: I'm not able to reproduce the "player doesn't do content playback" part of this issue. I see VAST_EMPTY_RESPONSE but the content then plays correctly, which is the same as what @andrewlewis observed.

If you're still seeing this issue please provide complete information including a full bug report. The log snippet at the top of this issue doesn't contain any information about the content playback that would have been attempted after the empty VAST response was received.
