### ISSUE TITLE
Can't play playready protected stream on Samsung S4 ("this device does not support the required DRM scheme")

### ISSUE THREAD

**Issue by to-jbm** [google/ExoPlayer#3211]
**Issue description**
Can't play playready protected stream on Samsung S4, and got "this device does not support the required DRM scheme" message

**Reproduction steps**
Just tried to play stream super speed (PlayReady) on the demo application on samsung S4 

**Link to test content**
super speed (PlayReady) from the Exoplayer demo app

**Version of ExoPlayer being used**
2.5.1

**Device(s) and version(s) of Android being used**
Samsung s4, Version 4.4.2
and Samsung core 2, Version 4.4.2

Can you please help me with this issue?

**Comment by ojw28** [comment]
The error message is correct. Only AndroidTV devices are required to support PlayReady. For Android mobile devices support is optional, and most do not support it.

**Comment by to-jbm** [comment]
thank you for your  replay
but there is many android apps like "bein connect" that use playready protected streams and works on samsung s4 and all devices with android API +18

**Comment by Doolali** [comment]
ExoPlayer relies on native DRM support which for Android phone devices will be Widevine.
There are SDKs for PlayReady out there but they will also come with the hefty PlayReady licensing fees.

**Comment by ojw28** [comment]
It should also be noted that software SDKs may be significantly less secure than native DRM solutions.

**Comment by to-jbm** [comment]
@Doolali So all those SDKs are paid ? there is no free SDK ?
@ojw28 thank you but unfortunately native solution  doesn't support playready for most of android devices

**Comment by ojw28** [comment]
I do not know of any free SDKs that support PlayReady (that's not to say there definitely isn't one!). Widevine is very much the recommended route for targeting Android devices.

Note that common encryption means it's possible to have the same content support multiple DRM schemes simultaneously; it's not the case that you'd need to generate two copies of the content to support both PlayReady and Widevine.

**Comment by to-jbm** [comment]
I made severals searchs
It seems that there is no public free SDK. (I found just one but unfortunately it throws a drm exception)
