### ISSUE TITLE
AdaptiveTrackSelection failed to switch up for live hls

### ISSUE THREAD

**Issue by james12695** [google/ExoPlayer#3224]
I've tried the ExoPlayer demo app with my LIVE HLS with 3s segment and failed to switch up high quality track due to insufficient bufferedDurationUs in `AdaptiveTrackSelection`,  and found the similar issues #2477 and #3017 but both are marked as enhancement. So can we mark this issue as `bug` instead of `enhancement` and have a rough plan for this fix?
Thanks

**Comment by ojw28** [comment]
Duplicate of #3017. Please avoid filing duplicate issues.
