### ISSUE TITLE
Different speed of audio playback on different devices

### ISSUE THREAD

**Issue by coffeeforyou** [google/ExoPlayer#3229]
At first, thanks a lot for such an amazing and flexible library! I'm writing because of an oddity, which I don't know how to explain or resolve.

**When I play back audio on my HTC One, I noticed that it runs slightly faster than the video (with the same audio) on my laptop (= 1s faster after roughly one hour of playback).** At the start of the playback, the audio on the laptop and the phone is perfectly synchronized, but as said, after one hour of playback there is a quite notable difference.
Surprisingly, I cannot reproduce this on a newer smartphone (Galaxy S7 Edge).

Assuming that Exoplayer runs a bit faster than it should every now and then, I tried to fix this behavior by comparing the current position of Exoplayer with the time where it theoretically should be (using `System.currentTimeMillis()`), but surprisingly the difference here was always just a few ms, not explaining the audible difference. (On the Galaxy S7 Edge these occasional adjustments work perfectly fine to keep the measured difference below 5ms, and there is no audible difference.)

For me, the assumption would be that `System.currentTimeMillis()` does not return accurate results on my HTC One (runs too fast or too slow), as the difference between audio on the smartphone and audio on the laptop is easily noticeable, but somehow I can't believe this and I'm looking for any other possible explanation.

Of course, any thoughts or input would be highly appreciated! **In general, it would also be interesting to know if Exoplayer ensures that after 10s of time elapsed it has played back exactly 10s**, or to understand how to ensure this myself in a more elegant way than comparing values from `System.currentTimeMillis()` with `getCurrentPosition()`.

Thanks a lot in advance!

**Comment by ojw28** [comment]
The underlying platform is responsible for playing the audio we feed to it, and for playing it at the correct rate. So it's likely that the HTC One platform implementation is just playing the audio very slightly faster than 1x speed. This wouldn't necessarily be related to any publicly accessible clock, although it is true that clocks on mobile devices tend to have some variance in them.

It's quite unclear whether this is actually a real issue for you, or just a hypothetical question. If it's a hypothetical question, I think we should just close this as a quirk of the HTC One. If it's posing a real issue, please describe what the use case is and why it's a problem.

**Comment by coffeeforyou** [comment]
Thanks a lot for the comprehensive answer! Actually, I don't know to which extent this could be an issue - it will depend on the number of devices which behave similarly to my HTC One, once I publish my app. I only have three devices to test on.
Maybe, if you have any other ideas where I could search or what I could try out, I'd be happy to hear them. My latest unsuccessful attempt was to find the reason in the timestamps in the mp4 files I use. I will continue trying to find the root cause, and if I find it, I'll let you know, but I agree that this is most likely not an issue of Exoplayer.

**Comment by ojw28** [comment]
When I ask whether it's a real issue, I guess what I'm really asking is whether your app really needs audio to play out at _exactly_ 1x speed (e.g. because you're synchronizing audio playback across multiple devices, or similar). If you're just doing media playback, a slightly off playback speed doesn't seem like a problem your users would notice.

If you are synchronizing audio across multiple devices then ExoPlayer is perhaps not the best tool (I'm not sure what is, however).
