### ISSUE TITLE
SmoothStreaming URLs that uses parenthesis "(...)" as part of the URL causes server side errors

### ISSUE THREAD

**Issue by nahojkap** [google/ExoPlayer#3230]
### Issue description
SmoothStreaming URLs that uses parenthesis "(...)" as part of the URL are not correctly preserved.  This kind of format has been seen when Microsoft MediaServices are used.  

For example, http://host/content.ism/manifest(filter=x) is changed by SsMediaSource.java into http://host/content.ism/manifest(filter=x)/Manifest which may produce an invalid URL towards the server side.

A simple solution would be to check for "manifest(...)" in the lastPathSegment and use the manifestUri directly if that is the case - something along the lines of

this.manifestUri = manifestUri == null ? null : lastPathSegment.contains("manifest") && lastPathSegment.contains("(") && lastPathSegment.contains(")")) ? manifestUri : lastPathSegment.equals("manifest") ? manifestUri : Uri.withAppendedPath(manifestUri, "Manifest");

### Reproduction steps
Use a manifest URL which ends with /manifest(filter=x), attempt playback, error is returned from remote server

### Link to test content
While the below link does not use the specified parameters inside the parenthesis, the URL will be rewritten by ExoPlayer and cause the error.

http://playready.directtaps.net/smoothstreaming/SSWSS720H264/SuperSpeedway_720.ism/manifest(filter=no)

### Version of ExoPlayer being used
SsMediaSource.java in current dev-v2 branch

### Device(s) and version(s) of Android being used
All devices

### A full bug report captured from the device
Not applicable

**Comment by nahojkap** [comment]
Thanks @ojw28 for wrapping this up - Irma came along and messed with all our plans & I got somewhat behind.  Will let you know if we have any issues with this when we get around to integrating it.

**Comment by ojw28** [comment]
Sorry to hear you were caught up in that. Thanks for your help on this, and yes, let us know if there are any remaining issues when you get back up and running.
