### ISSUE TITLE
Hello: how can I change the code rate when playing HLS streaming?

### ISSUE THREAD

**Issue by yubaolinfish** [google/ExoPlayer#3243]
Hello: how can I change the code rate when playing HLS streaming?

**Comment by ojw28** [comment]
Please provide more detailed information. I don't understand what this means; sorry!

**Comment by yubaolinfish** [comment]
We have a multi bit rate stream, and how do we use exoplayer for seamless handover?

**Comment by yubaolinfish** [comment]
We have a multi bit rate stream, and how do we use exoplayer for seamless handover?
Is it controlled by the parameters of MediaFormat?

**Comment by ojw28** [comment]
We adapt between the different variant streams automatically based on current network conditions. If you want to customize the adaptation logic, you should look in the `trackselection` package as a starting point.

**Comment by yubaolinfish** [comment]
![image](https://user-images.githubusercontent.com/10411717/30193937-d0e97d90-9482-11e7-8ede-698718885867.png)
Is this? If it is, every time will create a player, will not have the interface Caton? Thank you

**Comment by ojw28** [comment]
I do not understand the question, sorry. Please attempt to rephrase if you can.

**Comment by ojw28** [comment]
Closing due to lack of information.
