### ISSUE TITLE
add SimpleExoPlayerView Controls on Lock Screen and Notifications

### ISSUE THREAD

**Issue by fathallah1990** [google/ExoPlayer#3247]
how to add SimpleExoPlayerView Controls on Lock Screen and Notifications. I want to create notification player control when start play music on activity.

**Comment by ojw28** [comment]
I'd suggest you give [this blog post](https://medium.com/google-exoplayer/the-mediasession-extension-for-exoplayer-82b9619deb2d) a read, as a starting point!

**Comment by boswelja** [comment]
To add to this, I'm currently using the MediaSessionConnector and handling play / pause with my own BroadcastReceiver.. Is there any way I can use MediaButtonReceiver or something similar with the player?

**Comment by ojw28** [comment]
I can't see a reason why you wouldn't be able to register a `MediaButtonReceiver` directly on the `MediaSessionCompat` that you're passing into the extension, although it's somewhat unclear what you're asking.

@marcbaechinger - Could/should we be adding any direct support for `MediaButtonReceiver` to the extension?

**Comment by marcbaechinger** [comment]
Controls on the LockScreen are in the responsibility of app developers. This can be implemented by using a [media style notification](https://developer.android.com/reference/android/support/v7/app/NotificationCompat.MediaStyle.html) which makes the controls appear in the notification drawer as well as on the lock screen.
