### ISSUE TITLE
[Question]Is exoplayer support 7.1 AAC?

### ISSUE THREAD

**Issue by xdestiny110** [google/ExoPlayer#3248]
I know exoplayer support 7.1 in EAC from issue #3161 . I wonder is exoplayer support 7.1 AAC?
If not, is that in road map?

**Comment by andrewlewis** [comment]
Yes, it should just work. For example, if you're playing this stream on an Android TV device the device will decode all eight channels and send them as PCM data over the HDMI connection. Or on a phone with stereo speakers the audio channels should be downmixed to stereo. Let us know if you have any problems.
