### ISSUE TITLE
608 captions will not appear without seeking back

### ISSUE THREAD

**Issue by sergiomartinez4** [google/ExoPlayer#3250]
### Issue description
After I load the video with 608 captions and select the right text track, the captions will not show. I need to seek back (before completing the video playback) in order for the captions to appear.

The expected behavior is that the 608 captions must always appear when they're enabled.

### Reproduction steps
I added the below HLS video to the Demo Samples using the latest ExoPlayer version 2.5.1.
The video has 608 captions, and you can see them at ~2 seconds, ~8 seconds and ~9 seconds.

Steps
1. Load the Demo app and select the video
2. Enable text track with 608 captions.
3. Let it play and watch for any text tracks (no text tracks will appear).
4. At this point, you can also wait until the end of the video and seek all the way to the beginning and repeat step 3. You will not see any caption.

There are some steps I follow to make the captions to appear.
1. Load the Demo app and select the video
2. Enable text track with 608 captions.
3. Let it play for a couple of seconds (or anytime before the video completes) and seek back to the beginning.
4. Let it play and you will see the captions at ~2 seconds, ~8 seconds and ~9 seconds.

### Link to test content
http://solutions.brightcove.com/jwhisenant/hls/608_exoplayer_captions_issue/bipbop/bipbop_4x3_variant_1seg.m3u8

### Version of ExoPlayer being used
ExoPlayer version used: 2.5.1

### Device(s) and version(s) of Android being used
Tested with Google Pixel with Android 7.1.2

### A full bug report captured from the device
Bug report:
[bugreport-NJH47F-2017-09-07-16-45-03.zip](https://github.com/google/ExoPlayer/files/1286076/bugreport-NJH47F-2017-09-07-16-45-03.zip)

**Comment by sergiomartinez4** [comment]
are there any news about possible causes?

**Comment by AquilesCanta** [comment]
I'll have a look.

**Comment by ojw28** [comment]
This is fixed in `dev-v2`, and will be in `r2.5.3`, which will be released some time this week.

**Comment by sergiomartinez4** [comment]
Awesome, thanks!
