### ISSUE TITLE
Determine whether seeking or repeating

### ISSUE THREAD

**Issue by AOrobator** [google/ExoPlayer#3252]
Does Exoplayer have any plans to distinguish between seeking to the beginning of a period and repeating once? Using the repeat modes and a `DynamicConcatenatingMediaSource`, if I check that `player.getCurrentPosition() == 0` in `onPositionDiscontinuity()`,  I'm not able to tell whether the song has just repeated or the user has seeked to the beginning of the song. Some sort of callback in Player.EventListener would be great.

**Comment by AOrobator** [comment]
Conversation started on Medium: https://medium.com/@andreworobator/whats-the-best-way-to-be-notified-of-when-a-repeating-track-ends-so-i-can-count-how-many-time-a-e01f7a0024a

with @tonihei

**Comment by tonihei** [comment]
We thought about different ways of providing a clear way to notify the listener of what caused a position discontinuity. Our preferred method is to add a parameter to the `onPositionContinuity(@PositionContinuityReason int reason)` callback. It would provide one of three possible reasons: 1. automatic transition to next period (might be repeating the current one), 2. seeking within the current to another period, 3. other internal reasons causing a discontinuity.
Would that solve your issue? I think it gives you that extra bit of information (in addition to the period/window index and current playback position) to allow you to distinguish between all different cases.

**Comment by AOrobator** [comment]
Having a parameter in `onPositionDiscontinuity()` would be a great solution. I think we should separate the first reason into 2 different `int reason`s. One if it's repeating, another if it isn't.

**Comment by tonihei** [comment]
I think you can easily check if it is repeating the same item by comparing the period or window index to the previous one. Alternatively, you can also check the current repeat mode (`player.getRepeatMode()`) to determine whether playback is in a repeat loop or not. 

It wouldn't make much sense to add it here given how easy it is to get this information from the player. Besides, it would add unnecessary complications to the interface as there might be more parameters influencing the automatically selected next period (e.g. the shuffle mode, changes to a dynamic playlist, etc.).  

That said - we will add the described parameter to the onPositionDiscontinuity callback. Should be available in one of our upcoming releases (or the dev-branch).

**Comment by natez0r** [comment]
is this planned for 2.5.4?

**Comment by ojw28** [comment]
It will land in 2.6.0. We don't have an ETA.
