### ISSUE TITLE
 Samsung Note 8 dropping the connection

### ISSUE THREAD

**Issue by neowinston** [google/ExoPlayer#3256]
I now have a Samsung Note 8 and the our app using HLS is dropping the connection. It will play for a few minutes then just stop and it does not matter if itis streaming through the data 4g or WiFi same results. 

Using Wifi the app just stops playing and I have to shutdown the app and restart it for the audio to return. The Note 8 will play the BBN app on WIFI but the audio stops after a few minutes and I noticed that if I press the volumebutton on the side of the phone the audio returns. 

Any ideas why this could be happening?

**Comment by ojw28** [comment]
Is this for background audio playback, and if so are you running a foreground service and holding both WiFi and Wake locks (see [here](https://google.github.io/ExoPlayer/faqs.html#how-do-i-keep-audio-playing-when-my-app-is-backgrounded))?

**Comment by neowinston** [comment]
Thanks for your answer, I'm verifying if that solves the problem.
