### ISSUE TITLE
Using the remote's Play/Pause button when player controls are visible cause repeated plays/pauses

### ISSUE THREAD

**Issue by glad** [google/ExoPlayer#3259]
When the player controls are visible and holding down the Play/Pause button on the remote (e.g. an Amazon FireTV remote) causes the player to play/pause repeatedly.

You can see the behaviour here: http://imgur.com/a/y8sNI

Steps to reproduce:

1. When video player is open, give focus to the player controls's Play/Pause button
2. On your remote hold down the Play/Pause button (see: https://goo.gl/NV1kf4)
3. Notice the play/pause button on the screen toggles repeatedly

Likely issue is this case statement:
https://github.com/google/ExoPlayer/blob/9a026671301f8a6f9d987bf689b7df07360c0a28/library/ui/src/main/java/com/google/android/exoplayer2/ui/PlaybackControlView.java#L1006

**Comment by ojw28** [comment]
I think you're right. We should be checking `event.getRepeatCount()` so that we can ignore subsequent events. The exceptions to this rule are `KEYCODE_MEDIA_FAST_FORWARD` and `KEYCODE_MEDIA_REWIND`, for which we it is correct that we take action for each repeated event.
