### ISSUE TITLE
Question about ExoPlayer & deinterlacing

### ISSUE THREAD

**Issue by barhom** [google/ExoPlayer#3262]
Does Exoplayer have any setting for turning on or off deinterlacing ?
I am playing back a few videos using exoplayer that would (imo) be better if deinterlacing would be on.

I am comparing when playing back the same video using "VLC" and turning on or off de-interlacing (blend, via the D-shortcut on VLC).

**Comment by andrewlewis** [comment]
Please see [issue #2013](https://github.com/google/ExoPlayer/issues/2013#issuecomment-257634155).
