### ISSUE TITLE
How to use multicast - UdpDataSource？

### ISSUE THREAD

**Issue by Z1W3** [google/ExoPlayer#3264]
I read about issues#2029, but still did not solve.
This url(udp://@224.0.0.0:1234) can be played on the VLC player.
My device(Nexus9 android 7.1.1) supports udp.
### My Code

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        LOGGER.e("onCreate");
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_exoplayer);
        initView();
        createTrackSelector();
        createPlayer();
        bindPlayer();
        createMediaSource();
    }

    private void initView(){
        this.simpleExoPlayerView = (SimpleExoPlayerView) findViewById(R.id.player_view);
    }

    /**1. Create a default TrackSelector.*/
    private void createTrackSelector(){
        BandwidthMeter bandwidthMeter = new DefaultBandwidthMeter();
        TrackSelection.Factory videoTrackSelectionFactory = new AdaptiveTrackSelection.Factory(bandwidthMeter);
        this.trackSelector = new DefaultTrackSelector(videoTrackSelectionFactory);
    }

    /**2. Create the player.*/
    private void createPlayer(){
        this.player = ExoPlayerFactory.newSimpleInstance(getApplicationContext(), trackSelector);
    }

    /**Bind the player to the view.*/
    private void bindPlayer(){
        simpleExoPlayerView.setPlayer(player);
    }

    private void createMediaSource() {
        DefaultBandwidthMeter bandwidthMeter = new DefaultBandwidthMeter();
        // Produces DataSource instances through which media data is loaded.
        DefaultDataSource2.Factory dataSourceFactory = new DefaultDataSourceFactory(getApplicationContext(),
                Util.getUserAgent(getApplicationContext(), getString(R.string.app_name)), bandwidthMeter);
        // Produces Extractor instances for parsing the media data.
        ExtractorsFactory extractorsFactory = new DefaultExtractorsFactory();
        // This is the MediaSource representing the media to be played.
        Uri uri = Uri.parse("udp://@224.0.0.0:1234");
        MediaSource videoSource = new ExtractorMediaSource(uri, dataSourceFactory, extractorsFactory, handler, this);
        // Prepare the player with the source.
        player.prepare(videoSource);
        player.setPlayWhenReady(true);
    }

### class DefaultDataSource2

    private static final String TAG = "DefaultDataSource2";

    private static final String SCHEME_UDP = "udp";

    private final Context context;
    private final TransferListener<? super DataSource> listener;

    private final DataSource baseDataSource;
    private DataSource udpDataSource;

    private DataSource dataSource;

    public DefaultDataSource2(Context context, TransferListener<? super DataSource> listener,
                             String userAgent, boolean allowCrossProtocolRedirects) {
        this(context, listener, userAgent, DefaultHttpDataSource.DEFAULT_CONNECT_TIMEOUT_MILLIS,
                DefaultHttpDataSource.DEFAULT_READ_TIMEOUT_MILLIS, allowCrossProtocolRedirects);
    }

    public DefaultDataSource2(Context context, TransferListener<? super DataSource> listener,
                             String userAgent, int connectTimeoutMillis, int readTimeoutMillis,
                             boolean allowCrossProtocolRedirects) {
        this(context, listener,
                new DefaultHttpDataSource(userAgent, null, listener, connectTimeoutMillis,
                        readTimeoutMillis, allowCrossProtocolRedirects, null));
    }

    public DefaultDataSource2(Context context, TransferListener<? super DataSource> listener,
                             DataSource baseDataSource) {
        this.context = context.getApplicationContext();
        this.listener = listener;
        this.baseDataSource = Assertions.checkNotNull(baseDataSource);
    }

    @Override
    public long open(DataSpec dataSpec) throws IOException {
        Assertions.checkState(dataSource == null);
        String scheme = dataSpec.uri.getScheme();
        if(SCHEME_UDP.endsWith(scheme)){
            dataSource = getUdpDataSource();
        }
        else {
            dataSource = baseDataSource;
        }
        return dataSource.open(dataSpec);
    }

    @Override
    public int read(byte[] buffer, int offset, int readLength) throws IOException {
        return dataSource.read(buffer, offset, readLength);
    }

    @Override
    public Uri getUri() {
        return dataSource == null ? null : dataSource.getUri();
    }

    @Override
    public void close() throws IOException {
        if (dataSource != null) {
            try {
                dataSource.close();
            } finally {
                dataSource = null;
            }
        }
    }

    private DataSource getUdpDataSource(){
        if(udpDataSource == null){
            udpDataSource = new UdpDataSource(listener);
        }
        return udpDataSource;
    }

### My Error hints

  E/ExoPlayerImplInternal: Source error.
                                                                   
  com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to udp://@224.0.0.0:1234
                                                                       at 
  com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:194)
                                                                       at 
  com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:137)
                                                                       at 
  com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:692)
                                                                       at 
  com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:315)
                                                                       at 
  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                       at 
  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                       at java.lang.Thread.run(Thread.java:761)
                                                                    Caused by: java.net.MalformedURLException: unknown 
  protocol: udp
                                                                       at java.net.URL.<init>(URL.java:596)
                                                                       at java.net.URL.<init>(URL.java:486)
                                                                       at java.net.URL.<init>(URL.java:435)
                                                                       at 
  
  com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:341)
                                                                       at 
  com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:192)
                                                                       at 
  com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:137) 
                                                                       at 
  com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:692) 
                                                                       at 
  com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:315) 
                                                                       at 
  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                                       at 
  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                                       at java.lang.Thread.run(Thread.java:761)

**Comment by andrewlewis** [comment]
It looks like you're passing an instance of `DefaultDataSourceFactory`, not a custom factory that returns a `UdpDataSource`. Please try implementing `DataSource.Factory` and returning an instance of your `DefaultDataSource2` from its `createDataSource` method.
