### ISSUE TITLE
DefaultDrmSessionManager in MODE_DOWNLOAD repeatedly requests a license even though it's already loaded

### ISSUE THREAD

**Issue by Palethorn** [google/ExoPlayer#3270]
### Issue description
I wish to use DefaultDrmSessionManager in MODE_DOWNLOAD for live streaming contents that are crypted with the same content keys. Cannot help but notice that the license has been retrieved every time even for the same content. Is this an OK behaviour? I want for license to be downloaded once, and reused for future DRM sessions without additional load on a license proxy.

### Reproduction steps
- Build the DrmSessionManager using this method:
```
    private DrmSessionManager<FrameworkMediaCrypto> buildDrmSessionManager(
            UUID uuid, String licenseUrl, String[] keyRequestPropertiesArray) throws UnsupportedDrmException {

        HttpMediaDrmCallback drmCallback = new HttpMediaDrmCallback(licenseUrl,
                buildHttpDataSourceFactory(false));
        if (keyRequestPropertiesArray != null) {
            for (int i = 0; i < keyRequestPropertiesArray.length - 1; i += 2) {
                drmCallback.setKeyRequestProperty(keyRequestPropertiesArray[i],
                        keyRequestPropertiesArray[i + 1]);
            }
        }

        DefaultDrmSessionManager<FrameworkMediaCrypto> sm = new DefaultDrmSessionManager<>(uuid,
                FrameworkMediaDrm.newInstance(uuid), drmCallback, null, mainHandler, null);

        sm.setMode(DefaultDrmSessionManager.MODE_DOWNLOAD, null);
        return sm;
    }
```
- Try playing the same content twice
- Access log shows that the license server was called

### Link to test content
Additional information may be forwarded if needed to dev.exoplayer@gmail.com.

### Version of ExoPlayer being used
Version of ExoPlayer 2.5.1

### Device(s) and version(s) of Android being used
Tested on multiple devices with versions ranging from 4.4 to 6.0

### A full bug report captured from the device
No bug report for this issue.

### Possible solution
I have identified a piece of code which is causing this issue: https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/drm/DefaultDrmSessionManager.java#L515
Even if the license is succesfully restored using MediaDRM request is still being sent here.
Quick patch:
```
// Instead of:
  if (restoreKeys()) {
    postKeyRequest(sessionId, MediaDrm.KEY_TYPE_OFFLINE);
  }
// This piece can be used:
  if (restoreKeys()) {
    state = STATE_OPENED_WITH_KEYS;
    if (eventHandler != null && eventListener != null) {
      eventHandler.post(new Runnable() {
        @Override
        public void run() {
          eventListener.onDrmKeysRestored();
        }
      });
    }
  } else {
    postKeyRequest(sessionId, MediaDrm.KEY_TYPE_OFFLINE);
  }
```

**Comment by ojw28** [comment]
There are two reasons why you might like to renew an offline license:

1. Most license servers issue offline licenses that are only valid for a limited window of time. Renewal will extend the license validity in this case (or cause the license to become invalid, if the server believes the user should no longer have access).
1. To report usage metrics associated with the offline license.

We opportunistically attempt to renew offline licenses for these reasons, however an existing offline license will still work if the renewal fails. I think your only real issue here is load on the license proxy. Is this a real concern; I wouldn't expect the load to really be that great, even with this behavior?

**Comment by Palethorn** [comment]
From what I've noticed, the load is not that noticeable on a proxy, and zap time is not that much improved. If the renewal is an intentional behaviour then we can close this issue. Thank you for the information.
