### ISSUE TITLE
How to use exo_playback_control_view separately below the player and not over it

### ISSUE THREAD

**Issue by pawaom** [google/ExoPlayer#3272]
How to use exo_playback_control_view separately below the player and not over it

I have a Relative layout where I am showing the video using SimpleExoPlayerView and SimpleExoPlayer , 

I want to show the controls which are in the layout file of exo_playback_control_view separately  below the ExoPlayerView   and not over it as is the case in most players

is there any way this can   achieved

**Comment by ojw28** [comment]
You should be able to:
1. Disable playback controls in `SimpleExoPlayerView` by calling `simpleExoPlayerView.setUseController(false)`.
1. Add a `com.google.android.exoplayer2.ui.PlaybackControlView` somewhere else in your layout, bind it to the player using `playbackControlView.setPlayer(player)`, and unbind it (if you need to) by calling `playbackControlView.setPlayer(null)`.
