### ISSUE TITLE
Question about equalizer for exoplayer.

### ISSUE THREAD

**Issue by psedoykin** [google/ExoPlayer#3273]
Hello, 
Do you plan to implement equalizer for exoplayer?  

Now I am using standard equalizer (https://developer.android.com/reference/android/media/audiofx/Equalizer.html)  but it is not good because it has only 5 bands for mostly devices.

**Comment by ojw28** [comment]
I don't think we have plans for our own equalizer support. It's something you could add yourself, if you require it, however.
