### ISSUE TITLE
How to force rotation of video playback?

### ISSUE THREAD

**Issue by hzulla** [google/ExoPlayer#3275]
Hello,

For our app, we want to play a landscape video on a portrait UI phone with 90° rotation on purpose. The phone's user interface will not be rotated during playback, so the 90° rotation is intended behaviour. But ExoPlayer will rotate the video based on the phone's orientation and the video's metadata automatically. There is no parameter that allows me to override the video rotation for playback.

My naive attempt was to use `android:rotation="90"` for the `SimpleExoPlayerView`, but that results in a black view during playpack.

So what is the proper way to achieve this?

Thanks.

[I did read #91 prior to this, but that other bug report is about a different topic - as far as I understood that issue, there it's about a video that contains rotation metadata which were used wrongly during playback.]

**Comment by ojw28** [comment]
`SimpleExoPlayerView` doesn't support this use case directly, so you'll need to do a bit more work yourself.

The easiest approach is to use `TextureView` directly, by adding it to your layout and using `SimpleExoPlayer.setVideoTextureView`. Once using a `TextureView` you should be able to call `TextureView.setTransform` to set the desired rotation and transformation. You may need to listen to `SimpleExoPlayer.VideoInfoListener.onVideoSizeChanged` to get the video dimensions for calculating the transformation (see the source code for `SimpleExoPlayerView` for an example of how you can do this). If you need playback controls then you can add `PlaybackControlView` to your layout along with the `TextureView`.
