### ISSUE TITLE
Work with frequences

### ISSUE THREAD

**Issue by Merseyside** [google/ExoPlayer#3281]
Any API for low, middle, high frequences?

**Comment by ojw28** [comment]
Please can you try and more clearly define this question? It's unclear what you actually want, or what you're trying to do. Thanks.

**Comment by Merseyside** [comment]
I work with audio tracks. I wanna change frequences like in traktor, raise/omit frequences. For examle omit low frequences = no bass

**Comment by ojw28** [comment]
In that case, please see https://github.com/google/ExoPlayer/issues/3273 and https://github.com/google/ExoPlayer/issues/3058. Thanks.
