### ISSUE TITLE
Bitrate  issue

### ISSUE THREAD

**Issue by ManojJangra** [google/ExoPlayer#3285]
Hi,
We are using ExoPlayer version2. In my application we are using data saving mode, in this functionality when we are select data saving mode on, in that case we are show low bit rate selected and if off , set high bit rate.
when bit rates more than 4 in this case data saving mode showing wrong selection. for ex. we are getting 5 bit rates, in data saving mode on, 4th index are selected.
bit rates getting in decreasing order

if (mPlayerDataSavingIcon.isChecked()) {// check data saving mode is on
                            isQualityAuto = false;
                            if (AppUtils.getNetworkMode(MainActivity.this).equalsIgnoreCase("2G")) { // when data on 2g network (bit rates order is increasing )
                                onQualityChangeClick(1);
                            } else { 
                                onQualityChangeClick(trackCount-1);
                            }
                        } else {
                            if (trackCount > 2) { // check data saving mode is off
                                onQualityChangeClick(0);
                            }
                        }

kindly suggest me the same.

**Comment by ojw28** [comment]
It's unclear what the question is here. The snippet of code doesn't include any calls to ExoPlayer components. It would be the app's responsibility to select the tracks that it wants to use. Please clarify.

**Comment by ManojJangra** [comment]
Hi,
We are using ExoPlayer version2.
When we getting different bit rates (5)

0) 1280x720
1) 640x360
2) 320x180
3) 265x144
4) 160x90

we want to show selected 
if data saving mode is on ( 4th index selected)
if data saving mode is off (0 index selected)

if(Data saving mode on){
  pass  position-1 index
}else{
 pass 0 index
}

when we get 4 bit rates.
Data saving mode working fine.

kindly suggest me the same.
Thanks.

**Comment by ojw28** [comment]
The ExoPlayer demo app already demonstrates how to perform track selections, so I'd suggest you use that as a starting point.

**Comment by ManojJangra** [comment]
Hi,
I am sharing build of my application with exoplayer v2, bit rate switching manually  working properly.
when we click on data saving (Toggle Button) ,toggle button is selected  low quality should be selected and not selected high quality should be selected.

You can check in build attached in given link.

https://i.diawi.com/fUZq5e

**Comment by ojw28** [comment]
Sorry, but this sounds like an application bug. We're not able to spend time debugging this kind of thing for you. If you can describe a specific ExoPlayer bug that's causing this, please do so. Else you'll have to figure it out on your own, I'm afraid.
