### ISSUE TITLE
how can i use Gaussian Blur  with video (surfaceview or TextureView)

### ISSUE THREAD

**Issue by zhoushuqiang** [google/ExoPlayer#3286]
how can i use Gaussian Blur  with video (surfaceview or TextureView)
thanks

**Comment by ojw28** [comment]
This is not really a question directly related to ExoPlayer, and as such falls outside the scope of this issue tracker. Although at a high level:

* This is not possible with SurfaceView
* You should probably take a look at outputting the video to a [SurfaceTexture](https://developer.android.com/reference/android/graphics/SurfaceTexture.html). At that point you've essentially got video in a GL texture, and so can apply GL shaders etc. You'd be best off asking somewhere like StackOverflow if you need assistance on this part.
