### ISSUE TITLE
Hide all video control tools except loading progress bar

### ISSUE THREAD

**Issue by OkoyaUsman** [google/ExoPlayer#3287]
Ok! 
Not a bug, not an issue, just an individual request.
I needed a hint on how to generally disable or hide the SEEKBAR and the Play/Pause controls.. I followed an already solved method here to disable the default control with:

`app:useDefaultControls="false"`

but using that also disable the buffering gif or is it called progressive "loading" gif? :)
All I need is like a code to disable the seek bar and play/pause functions or preferably hide them...

Not interesting but...couldn't figure it out.

**Comment by ojw28** [comment]
I don't think this is an ExoPlayer question. If you're using ExoMedia, you'll need to ask the maintainers of that project.
