### ISSUE TITLE
Ima Ads error with Video Adsense

### ISSUE THREAD

**Issue by hoanganh2020** [google/ExoPlayer#3289]
Hi,

I have error with IMA video Adsense. 

Link: https://ima3vpaid.appspot.com/?adTagUrl=

` Caused by: AdError [errorType: LOAD, errorCode: AdErrorCode [name: ADS_REQUEST_NETWORK_ERROR, number: 1012], message: Unable to request ads from server due to network error.]`

`No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://imasdk.googleapis.com' is therefore not allowed access.", source: https://imasdk.googleapis.com/native/sdkloader/native_sdk_v3.html?sdk_version=a.3.7.4&hl=en&wvr=2&app=ima.droidviet.com.exoplayerima (0`

**Comment by andrewlewis** [comment]
Does the VAST ad server's response (from `https://ima3vpaid.appspot.com`) have an CORS header? See the [IMA documentation](https://developers.google.com/interactive-media-ads/docs/sdks/html5/cors), or the [VAST 3.0 specification](https://www.iab.com/wp-content/uploads/2015/06/VASTv3_0.pdf) subsection 2.1.5.2.

**Comment by ojw28** [comment]
Closing due to lack of information. I agree this is probably a CORS issue.
