### ISSUE TITLE
Byte Range Request

### ISSUE THREAD

**Issue by soadri** [google/ExoPlayer#3298]
In ExoPlayer, player requests over HTTP by setting request range

e.g. bytes=17654432-22314354 -> segment 1

After segmenting video, bytes of each segment is defined

Can I change the byte range request and be playback without any problem?

Some example is below

bytes=17654432-19354221 -> half of segment 1

bytes=19354222-22314354 -> remainder half of segment 1

Thank you for read this

**Comment by ojw28** [comment]
As long as the requested data is loaded one way or another, there's no reason in that would prevent you from doing this, as long as you made the change correctly. Having said that, I don't understand why you would want to do this.

**Comment by soadri** [comment]
@ojw28 

I want to confirm whether video can be played when player requests some range of bytes part of segment

Thank you for reply
