### ISSUE TITLE
Question : How to play one video between another video?

### ISSUE THREAD

**Issue by rranjithkumar100** [google/ExoPlayer#3299]
My mainSource is movie (~2 hours)

My secondSource & thirdSource are video Ads (2 mins)

I need to play first video advertisement after 30 mins movie played. And need to play second video advertisement after 60 mins movie played.

I need play 3 videos in following sequence

main movie (first 30 min) --> 2 min first ads --> main movie (31-60 mins) --> 2 min second ads --> main movie (61- end)

Shall I use **ConcatenatingMediaSource** for this scenario? 

Currently I am using **compile 'com.google.android.exoplayer:exoplayer:r2.5.1'**

Thank you for your valuable response.

**Comment by andrewlewis** [comment]
To play a clip from a longer `MediaSource`, pass it to `ClippingMediaSource`'s constructor along with the start/end times you want to play. Then `ConcatenatingMediaSource` can be used to join together the clips, so the source you pass to `prepare` will be a `ConcatenatingMediaSource` with `ClippingMediaSource`s for the movie clips and normal `MediaSource`s (e.g., `ExtractorMediaSource`s) for the ads.

Please note the caveat on #1988: to make playback seamless, you will need to ensure that the start point of each clip lies on a keyframe.
