### ISSUE TITLE
Cannot play *.ts files, captured from DVB-T.

### ISSUE THREAD

**Issue by krok55** [google/ExoPlayer#330]
Hello,

I have a local *.ts file that I'm trying to play from external storage (/mnt/sdcard/...)
I don't get any kind of error in the LogCat, but the file just won't start...

On the "standard" MediaPlayer it works fine.
I've used DefaultRendererBuilder for my trials (others are not able to parse local storage links or expect some kind of manifest file)
Please take a look on the file that I was trying to play:
http://www.filedropper.com/debug_2

Please help me with this issue.
Thanks!

**Comment by ojw28** [comment]
The file is no longer present at the link, but you should be able to play *.ts files using TYPE_TS in the demo app, if you use the dev branch (we'll push support to master next week).
