### ISSUE TITLE
IMA extension: Support playback of HLS ads

### ISSUE THREAD

**Issue by jeevarajp** [google/ExoPlayer#3302]
I am using exoplayer version 2.5.3

I followed exactly same steps in https://medium.com/google-exoplayer/playing-ads-with-exoplayer-and-ima-868dfd767ea blog and was able to play mp4 ads.  But I am unable to play HLS ads using exoplayer ima extension 2.5.3.

Please advise me whether this ima extension (2.5.3) has HLS ad support or not.  If yes, what am I doing wrong? If no, please advise any alternative way for achieving it.

Thanks.

**Comment by andrewlewis** [comment]
It should work. What goes wrong when you try to insert ads with an `HlsMediaSource` as the content media source?

**Comment by jeevarajp** [comment]
Yes, I am able to play HLS content (using HlsMediaSource).  But HLS advertisements are not playing for me (mp4 advertisement plays).

**Comment by andrewlewis** [comment]
We assume the ad media URIs provided by the IMA SDK are all playable with `ExtractorMediaSource` at the moment, so this isn't supported.

Please could you provide the ad tag you're trying to play here, or email it to dev.exoplayer@gmail.com, then we can take a look? It's probably fairly straightforward to make this work if IMA supports it. Thanks.

**Comment by jeevarajp** [comment]
Below is the ad tag I am trying to play.

`<VAST version="2.0"><Ad id="1"><InLine><AdSystem/><AdTitle/><Impression>../static/clear_dot.gif?impression</Impression><Creatives><Creative><Linear skipoffset="00:00:08"><Duration>00:00:30</Duration><MediaFiles><MediaFile delivery="progressive" type="application/x-mpegURL" scalable="true" width="" height="">https://www.outsourcelive.com/vast/advertisement_hls/Amazon_hls/amaz.m3u8</MediaFile></MediaFiles><TrackingEvents><Tracking event="creativeView">../static/clear_dot.gif?createView</Tracking><Tracking event="start">../static/clear_dot.gif?start</Tracking><Tracking event="firstQuartile">../static/clear_dot.gif?firstQuartile</Tracking><Tracking event="midpoint">../static/clear_dot.gif?midpoint</Tracking><Tracking event="thirdQuartile">../static/clear_dot.gif?thirdQuartile</Tracking><Tracking event="complete">../static/clear_dot.gif?complete</Tracking><Tracking event="skip">../static/clear_dot.gif?skip</Tracking><Tracking event="mute">../static/clear_dot.gif?mute</Tracking><Tracking event="unmute">../static/clear_dot.gif?unmute</Tracking><Tracking event="pause">../static/clear_dot.gif?pause</Tracking><Tracking event="rewind">../static/clear_dot.gif?rewind</Tracking><Tracking event="resume">../static/clear_dot.gif?resume</Tracking><Tracking event="fullscreen">../static/clear_dot.gif?fullscreen</Tracking><Tracking event="expand">../static/clear_dot.gif?expand</Tracking><Tracking event="collapse">../static/clear_dot.gif?collapse</Tracking><Tracking event="acceptInvitation">../static/clear_dot.gif?acceptInvitation</Tracking><Tracking event="close">../static/clear_dot.gif?close</Tracking></TrackingEvents><VideoClicks><ClickThrough>
			         http://ya.ru/
			    </ClickThrough><ClickTracking>
				../static/clear_dot.gif?click
			    </ClickTracking></VideoClicks></Linear></Creative></Creatives></InLine></Ad></VAST>`

**Comment by jeevarajp** [comment]
So Exoplayer IMA extension v2.5.3 doesn't have support for playback of HLS ads right now?

Is it possible to me to set AdsRenderingSettings mimetype as mentioned here in this post and add HLS ads support to IMA extension?

When can I expect HLS ads support? Please advise.

**Comment by andrewlewis** [comment]
Correct. We don't support this right now.

To implement it, we need to create the right type of media source in `AdsMediaSource`, and also handle media sources that don't allow immediate creation of a period. No promises when it will be done, but I expect we can push a change to support this during the new few weeks.

**Comment by rjlevesque** [comment]
Hi @andrewlewis, sorry to be a pest but any updates on HLS ad support?

**Comment by andrewlewis** [comment]
@rjlevesque No updates yet I'm afraid.

**Comment by jeevarajp** [comment]
@ojw28 / @andrewlewis could you please let me know release version of exoplayer which includes this feature?

**Comment by andrewlewis** [comment]
Please try it out on the release candidate branch `dev-v2-r2.6.1` and let us know if you have any problems. Thanks!
