### ISSUE TITLE
Exoplayer set visibility not working 

### ISSUE THREAD

**Issue by rranjithkumar100** [google/ExoPlayer#3304]
In my case I use the two exoplayer. 

So I need to pause  & hide the first one.

So I try to setVisiblity(gone) for first player. 

`mExoPlayer.setVisibility(View.GONE); // NOT working `

**How to set visibility for ExoPlayer?**

**Comment by ojw28** [comment]
This is probably a duplicate of https://github.com/google/ExoPlayer/issues/3160, which was fixed in r2.5.2. If it's not a duplicate, please provide all of the information requested in the issue template, since there's insufficient information here for us to help.

**Comment by rranjithkumar100** [comment]
Thanks a lot @ojw28 

Sorry for duplicate issue.
