### ISSUE TITLE
Show buffer bar in player

### ISSUE THREAD

**Issue by hawkiq** [google/ExoPlayer#3306]
I have question , if I want to show buffer bar to users so they can know how much forward they able to do, 
Regards

**Comment by andrewlewis** [comment]
The [DefaultTimeBar](https://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/ui/DefaultTimeBar.html) provided in the UI module shows the buffered duration. Could you describe in a bit more detail what functionality you're looking for? Thanks.

**Comment by hawkiq** [comment]
@andrewlewis 
am sorry I accidentally posted the issue without attach the code or screenshots
I've mad custom control for player and used SeekBar to show progress for media
```
        <LinearLayout
            android:id="@+id/control_seek"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_gravity="center_horizontal"
            android:orientation="horizontal">

            <TextView
                android:id="@+id/time_current"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_gravity="center_horizontal"
                android:paddingLeft="4dip"
                android:paddingRight="4dip"
                android:paddingTop="4dip"
                android:text="@string/dummy_00_00"
                android:textColor="#ffffff"
                android:textSize="14sp"
                android:textStyle="bold" />

            <SeekBar
                android:id="@+id/mediacontroller_progress"
                style="?android:attr/progressBarStyleHorizontal"
                android:layout_width="0dip"
                android:layout_height="30dp"
                android:layout_weight="1" />

            <TextView
                android:id="@+id/player_end_time"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_gravity="center_horizontal"
                android:paddingLeft="4dip"
                android:paddingRight="4dip"
                android:paddingTop="4dip"
                android:text="@string/dummy_99_99"
                android:textColor="#ffffff"
                android:textSize="14sp"
                android:textStyle="bold" />
        </LinearLayout>
```

its shows like this
![sc1](https://user-images.githubusercontent.com/7524502/30954552-47980f04-a439-11e7-8f4a-ee588fd260c4.png)


but I want to view buffer bar like something light grey so user know they can progress more.
like this
![img_20170928_104050_655](https://user-images.githubusercontent.com/7524502/30954633-9afa847e-a439-11e7-9245-aadf552e0f70.jpg)

**Comment by ojw28** [comment]
You can query `getBufferedPosition` and `getBufferedPercentage` on the player to get the values you need. How you implement your own custom control to display the buffered position correctly is outside the scope of this issue tracker.
