### ISSUE TITLE
Video not rendering correctly on Lenovo TAB3 8

### ISSUE THREAD

**Issue by mraj0045** [google/ExoPlayer#3307]
Im trying to play a video from asset folder. It is working fine on some devices, but in some devices it not playing correctly.

Device that I have found the issue:
Lenovo TAB3 8

Replicate the issue by playing the video from the asset folder.
[logcat.txt](https://github.com/google/ExoPlayer/files/1340069/logcat.txt)
[bug_report.txt](https://github.com/google/ExoPlayer/files/1340070/bug_report.txt)
![device-2017-09-28-134319](https://user-images.githubusercontent.com/12872183/30956507-304d3362-a455-11e7-8fa8-de245158bf72.png)

**Comment by ojw28** [comment]
Are you sure the fact you're playing from the assets folder is relevant? Or does playing the same content some other way (e.g. from a server) cause the same problem?

**Comment by mraj0045** [comment]
@ojw28 I haven't tried playing from a server. I will check it and get back to you.

**Comment by mraj0045** [comment]
@ojw28  I'm facing the problem while playing from the server too.
URL -> https://firebasestorage.googleapis.com/v0/b/vpremiere-1eea0.appspot.com/o/splash_720.mp4?alt=media&token=995a955c-7ddf-469c-b651-228321c8f9a5

**Comment by ojw28** [comment]
Closing as obsolete. I don't think there's much we can do to fix this. You should report the problem to the device manufacturer.
