### ISSUE TITLE
Player Discontinuity detected and black screen for 5 seconds

### ISSUE THREAD

**Issue by mitchellwit** [google/ExoPlayer#3308]
Exoplayer version 2.5.3

Hello,

I have some protected HLS streams for example: https://api.hidive.com/manifest/master/dd5e4aa62cdc3cb59031efd99e1c094ad8e114f1/ACF_s01e001_tv_br_or_ja_xx_HLS_16x9_00_v.m3u8

The stream contains a 'bumper' which is basically a chunk of 5seconds and the rest of the video in chunks. The problem is when the user is logged in to the app, i have to send some values in the request headers(or as parameters in the url). Then the bumper plays for 5seconds like it should and you should expect that the player picks the next chunk and just continues but.. The player starts at 0 again and i see 5 seconds black screen(the first chunk time). And then the next chunk starts. The subtitles are not synced properly anymore and i see this error in my logcat:
E/AudioTrack: Discontinuity detected [expected 65160755, got 60040755]

If i play the stream without the request headers. The player just continues counting after the 5sec chunk and everything goes smoothly like it should.

Am i missing something? What can be wrong?

Thanks

**Comment by ojw28** [comment]
It sounds like your HLS media playlists are missing EXT-X-DISCONTINUITY tags between the bumper and the remainder of the video, which are required if you want to do this kind of thing. Please see the [HLS spec](https://tools.ietf.org/html/draft-pantos-http-live-streaming-23#section-4.3.2.3) for details. The link provided above gives me a 404, so I wasn't able to verify this diagnosis.

**Comment by ojw28** [comment]
Closing on the assumption the above diagnosis was correct. If it's not, please reply here with a working stream and we'll reopen the issue. Thanks!

**Comment by mitchellwit** [comment]
https://api.hidive.com/manifest/master/dd5e4aa62cdc3cb59031efd99e1c094ad8e114f1/AGK_s01e001_tv_or_na_ja_xx_HLS_16x9_01_i.m3u8

**Comment by mitchellwit** [comment]
Note, the error only happens if i add some http headers, without the stream works correctly

**Comment by ojw28** [comment]
Works correctly for me (without headers). Since you've not provided any information about what headers you're setting, or how, we're unable to assist further.

Presumably those headers are changing the content in a way that makes it invalid (they must be doing something, else behavior wouldn't be different in that case).

**Comment by mitchellwit** [comment]
Issue can be closed it seemed like they did not return the EXT-X-DISCONTINUITY tags when the headers were present. Sorry but thanks for your time!

**Comment by ojw28** [comment]
Weird bug; glad you tracked it down :).

**Comment by TarifHatoum** [comment]
hi, how did you fix this discontinuity issue ?

**Comment by ojw28** [comment]
@Anonymous123456789123 - The fix would have been on the serving side (i.e. it's a content issue), and would have been to properly include EXT-X-DISCONTINUITY tags in the media playlist as per the HLS spec even when the request headers were present.
