### ISSUE TITLE
testing out ExoPlayer with an emulator

### ISSUE THREAD

**Issue by orcaman** [google/ExoPlayer#331]
Is there an emulator around capable of running ExoPlayer? The default emulator that comes with Android Studio shouts out "playback error" when running the videos from the demo app included in the repo. If the answer is "no", can anyone elaborate on why it is not possible? Thanks!

**Comment by ojw28** [comment]
It's unlikely to be possible for secure drm protected playbacks. For all other playbacks (i.e. most playbacks) there's no fundamental limitation preventing it from working, although emulator support for video has traditionally been poor.
