### ISSUE TITLE
Low video quality compared to MediaPlayer

### ISSUE THREAD

**Issue by naceto** [google/ExoPlayer#3313]
### Issue description
Video quality is poor using Exoplayer compared to android's MediaPlayer (pictures in the link).

### Reproduction steps
Just play the provided video in ExoPlayer's demo app.

### Link to test content
https://www.dropbox.com/sh/c8l05doll378l49/AAB4MdHN4krrWYje-Ggd54g6a?dl=0

### Version of ExoPlayer being used
r2.5.3

### Device(s) and version(s) of Android being used
reproduced only on NEXBOX A95X so far

**Comment by ojw28** [comment]
This looks like a device specific issue that you'd need to report to the manufacturer. If they were using un-modified Android then I think both ExoPlayer and MediaPlayer would be using the same decode + output path, which implies the manufacturer must have done some kind of customization.
