### ISSUE TITLE
Support In-Playlist Timed Metadata

### ISSUE THREAD

**Issue by juechemparathy** [google/ExoPlayer#3319]
@ojw28 - Any plans to support "In-Playlist Timed Metadata" ?
 
#EXT-X-DATERANGE
Metadata is expressed as a date-based range inside a playlist
Each range carries a content-defined set of attribute/value pairs
Ref: Slide 42 -http://devstreaming.apple.com/videos/wwdc/2016/504m956dgg4hlw2uez9/504/504_whats_new_in_http_live_streaming.pdf

**Comment by AquilesCanta** [comment]
You can access all tags in the playlists from `HlsPlaylist#tags`, including `#EXT-X-DATERANGE`. And you can access the playlist through `Player#getCurrentManifest` (and its corresponding listener methods). Please see `HlsManifest`. What specifically are you interested in doing that would require ExoPlayer support?

**Comment by juechemparathy** [comment]
Cool, that works.
