### ISSUE TITLE
Dont report IDLE state when loader error

### ISSUE THREAD

**Issue by crossle** [google/ExoPlayer#332]
Playback HLS stream, when loader error `com.google.android.exoplayer.upstream.HttpDataSource$HttpDataSourceException:`, onError receive the error, but then why onStateChanged receive the IDLE state? use the latest version, before work well.

**Comment by ojw28** [comment]
It's always been well documented that the state transitions to IDLE after playback fails [here](http://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer/ExoPlayer.Listener.html#onPlayerError(com.google.android.exoplayer.ExoPlaybackException). This is not new behavior.
