### ISSUE TITLE
IMA Ads: listen to events

### ISSUE THREAD

**Issue by rubenweerts** [google/ExoPlayer#3322]
### Issue description
As a developer I want to be able to respond to certain events. The events of these interfaces are hidden when using the Ima-extension: `AdErrorListener`, `AdsLoadedListener`, `AdEventListener`
I'm currently unable to respond to these events:  
```
ALL_ADS_COMPLETED,
FIRST_QUARTILE,
MIDPOINT,
SKIPPED,
TAPPED,
ICON_TAPPED,
THIRD_QUARTILE,
LOADED,
AD_PROGRESS
```

A solution would be to allow an external listener to receive these events aswel. i.e. `ImaAdsLoader.addAdEventListener()` and `ImaAdsLoader.addAdErrorListener()`, ect.
Or make an encapsulating listener that transfers all 3 listeners to external code.

Another quicker solution could be to not make the class `final` so I can add the functionality myself.

### Reproduction steps
None, this is a feature request to open up the SDK

### Link to test content
None needed

### Version of ExoPlayer being used
r2.5.3

### Device(s) and version(s) of Android being used
Any device, but for the sake to name one I'm using the Nexus 6p.

### A full bug report captured from the device
See description

**Comment by andrewlewis** [comment]
I wonder if we should just provide a getter for the `com.google.ads.interactivemedia.v3.api.AdsLoader` field. Then you could add an additional `AdErrorListener` and `AdsLoadedListener` in your app, and in the `AdsLoadedListener` you could get the `AdsManager` and attach another `AdEventListener`. Does that sound like it would meet your requirements?

**Comment by rubenweerts** [comment]
Yes, that sounds good. Any solution that allows me to receive the original IMA SKD's events is fine 👍

**Comment by mitchellwit** [comment]
When can we expect this to be in release?

**Comment by ojw28** [comment]
It's in 2.6.0, for which there's current a dev branch. We're still finishing off a few bits and pieces to cherry-pick into it, and expect it to be pushed sometime next week (no promises though).
