### ISSUE TITLE
Sideloading a subtitle using exoplayer

### ISSUE THREAD

**Issue by cengizkandemir** [google/ExoPlayer#3324]
In issue 2017, a side-loading example for subtitles is given using a MergingMediaSource. Then it is suggested that either SimpleExoPlayerView should be used or its implementation should be replicated. I wasn't able to achieve the latter.

In SimpleExoPlayerView.java, ComponentListener implements onCue (feeding cues to SubtitleView's onCue implementation) and is given to player's TextRenderer.Output using some setter. These are the only relevant pieces of codes that I was able to observe. So, I tried to do the same.

- Merge a video and  text source
- Create a similar component listener, and call SubtitleView's onCue in its implementation
- Register component listener interface using setTextOutput() method of the player

However, onCue of my own component listener implementation is not invoked at all. What could be the reason? Am I missing something on SimpleExoPlayerView implementation?

I am using the material provided in [this page](http://www.storiesinflight.com/js_videosub/).

I tried using the meme types of "TEXT_VTT" and "APPLICATION_SUBRIP" but no avail.

ExoPlayer version: r2.5.0

**Comment by andrewlewis** [comment]
That page references an `.srt` file so, assuming you're trying to play that, I think `MimeTypes.APPLICATION_SUBRIP` is right. The text source should be a `SingleSampleMediaSource` (as in https://github.com/google/ExoPlayer/issues/2017).

If you set a breakpoint in `TextRenderer.updateOutput` does it get hit during playback?

**Comment by cengizkandemir** [comment]
I do not have a TextRenderer object at any part. Do I need a TextRenderer? I mean there wasn't a TextRenderer object in SimpleExoPlayerView as well. As I said, I strictly followed what I was able to see there.

**Comment by andrewlewis** [comment]
It's part of ExoPlayer's core library.

**Comment by cengizkandemir** [comment]
How do I incorporate a TextRenderer to make my implementation work? Any issue/sample that you could direct me?

**Comment by andrewlewis** [comment]
It's internal to the player, so you don't need to write any code to incorporate it. It would be useful to set a breakpoint in its `updateOutput` method to diagnose what's going on. In Android Studio, press Ctrl + N and type "TextRenderer" to open the sources for the file. Then you can set a breakpoint and see if it gets hit when you run your app.

Or alternatively share the code you're using to set up the player and we can take a look.

**Comment by cengizkandemir** [comment]
Here is how I do it

```
MediaSource videoSource = new ExtractorMediaSource(
        videoUri,
        dataSourceFactory,
        new DefaultExtractorsFactory(),
        null,
        null);
Format subtitleFormat = Format.createTextSampleFormat(
        null,
        MimeTypes.APPLICATION_SUBRIP,
        0,
        "en");
MediaSource textMediaSource = new SingleSampleMediaSource(
	Uri.parse("http://www.storiesinflight.com/js_videosub/jellies.srt"),
	dataSourceFactory,
	subtitleFormat,
	C.TIME_UNSET);
source = new MergingMediaSource(videoSource, textMediaSource); // to be used later


// nested to some class that has SubtitleView as member
class SomeListener implements ..., TextRenderer.Output, ... {
	...
        // this function doesn't seem to be invoked
	public void onCues(List<Cue> cues) {
	    // some logging here
	    if (subtitleView != null) {
		subtitleView.onCues(cues);
	    }
	}
	...
}

player.setTextOutput(listener);
...
// later, play the video assuming its prepared and whatnot
player.setPlayWhenReady(true);
```

As I said, video plays, subtitles are missing.

**Comment by andrewlewis** [comment]
That part looks okay, as long as you are preparing the player with the merged source (not just the video source). Please change `setTextOutput` to `addTextOutput`, just in case this is getting called from somewhere else overwriting your listener.

If you want us to investigate further, please could you provide a link to full minimal source code to reproduce the problem?

**Comment by cengizkandemir** [comment]
I am trying to integrate ExoPlayer locally instead of downloading compiled jars using gradle. I'll try to debug now.

**Comment by cengizkandemir** [comment]
I can confirm that SimpleExoPlayer's "setTextOutput" function is invoked, setting textOutput member but breakpoint doesn't seem to be triggered @ updateOutput function of TextRenderer.

**Comment by cengizkandemir** [comment]
addTextOutput seems to be missing. It is present in release-v2, but not in dev-v2-r2.5.0

**Comment by andrewlewis** [comment]
Are you using DefaultRenderersFactory? If you step through `TextRenderer.render` are input buffers arriving?

Please upgrade to the latest version if you can, in case there was a bug fix.

**Comment by cengizkandemir** [comment]
I think yes. newSimpleInstance seems to create a new DefaultRenderersFactory. We are feeding a DefaultTrackSelector. Now using dev-v2-r2.5.3, breakpoint does not trigger at TextRenderer.renderer.

**Comment by andrewlewis** [comment]
Could you try replacing 0 with C.SELECTION_FLAG_DEFAULT in the call to `createTextSampleFormat`? (You need to pass one of the `C.SelectionFlags` constants to [Format.createTextSampleFormat](https://github.com/google/ExoPlayer/blob/dev-v2-r2.5.3/library/core/src/main/java/com/google/android/exoplayer2/Format.java#L289).)

**Comment by cengizkandemir** [comment]
Wow! That did the trick. So much for c/p code :). There doesn't seem to be a selection flag constant with value of 0. Perhaps that was causing problem?

Thanks for quick replies. I appreciate.

**Comment by andrewlewis** [comment]
Cool. Glad you got it to work :)
