### ISSUE TITLE
Seekable option disable with mp3 online files, same channels and framerate

### ISSUE THREAD

**Issue by JuanNova** [google/ExoPlayer#3330]
### Issue description

The problem is when I am trying to play a sound and the exoplayer tell me that the mp3 file is not seekeable.

The online mp3 files are:

- http://audios.esradio.fm/espana/17/10/06/otras-noticias-los-golpistas-quieren-proclamar-la-independencia-el-martes-118113.mp3 -> seekable

- http://audios.esradio.fm/espana/17/10/06/tertulia-de-dieter-la-bandera-de-espana-118122.mp3 -> This file is not seekable

### Reproduction steps

Trying in  ExoPlayer demo app, only modifying two uri properties in media.exolist.json with two routes to online mp3 files

### Version of ExoPlayer being used
Versions that I test: 'com.google.android.exoplayer:exoplayer:r2.5.3' and with 'com.google.android.exoplayer:exoplayer:r2.4.2'

### Device(s) and version(s) of Android being used

Android 6 OnePlusOne, Android 7 Nexus 6, and simulators

### A full bug report captured from the device

**_With seekable option:_**
I/ExoPlayerImpl: Init ExoPlayerLib/2.4.3 [generic_x86, Android SDK built for x86, unknown, 25]
D/EventLogger: state [0.01, true, I]
D/EventLogger: state [0.02, true, B]
D/EventLogger: sourceInfo [periodCount=1, windowCount=1
D/EventLogger:   period [?]
D/EventLogger:   window [?, false, false]
D/EventLogger: ]
17949-18103/com.google.android.exoplayer2.demo D/NetworkSecurityConfig: No Network Security Config specified, using platform default
D/EventLogger: loading [true]
7949-17965/com.google.android.exoplayer2.demo D/OpenGLRenderer: endAllActiveAnimators on 0x9f143a00 (ExpandableListView) with handle 0x9d1f7bc0
D/EventLogger: sourceInfo [periodCount=1, windowCount=1
D/EventLogger:   period [1269.24]
D/EventLogger:   window [1269.24, true, false]
D/EventLogger: ]
17949-18102/com.google.android.exoplayer2.demo I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
D/EventLogger: Tracks [
D/EventLogger:   Renderer:1 [
D/EventLogger:     Group:0, adaptive_supported=N/A [
D/EventLogger:       [X] Track:0, id=null, mimeType=audio/mpeg, channels=2, sample_rate=44100, supported=YES
D/EventLogger:     ]
D/EventLogger:   ]
D/EventLogger: ]
D/EventLogger: audioEnabled [0.56]
17949-18116/com.google.android.exoplayer2.demo I/OMXClient: MuxOMX ctor
D/EventLogger: audioDecoderInitialized [0.65, OMX.google.mp3.decoder]
D/EventLogger: audioFormatChanged [0.65, id=null, mimeType=audio/mpeg, channels=2, sample_rate=44100]
D/EventLogger: state [0.65, true, R]
17949-18102/com.google.android.exoplayer2.demo D/AudioTrack: Client defaulted notificationFrames to 5512 for frameCount 11025
D/EventLogger: audioSessionId [17049]
D/EventLogger: loading [false]
7949-17954/com.google.android.exoplayer2.demo I/art: Do partial code cache collection, code=28KB, data=23KB
17949-17954/com.google.android.exoplayer2.demo I/art: After code cache collection, code=28KB, data=23KB
17949-17954/com.google.android.exoplayer2.demo I/art: Increasing code cache capacity to 128KB

_**Without seekable option:**_
I/ExoPlayerImpl: Init ExoPlayerLib/2.4.3 [generic_x86, Android SDK built for x86, unknown, 25]
D/EventLogger: state [0.00, true, I]
D/EventLogger: state [0.10, true, B]
D/EventLogger: sourceInfo [periodCount=1, windowCount=1
D/EventLogger:   period [?]
D/EventLogger:   window [?, false, false]
D/EventLogger: ]
D/EventLogger: loading [true]
17949-17954/com.google.android.exoplayer2.demo I/art: Do partial code cache collection, code=59KB, data=43KB
17949-17954/com.google.android.exoplayer2.demo I/art: After code cache collection, code=58KB, data=43KB
17949-17954/com.google.android.exoplayer2.demo I/art: Increasing code cache capacity to 256KB
17949-17965/com.google.android.exoplayer2.demo D/OpenGLRenderer: endAllActiveAnimators on 0x9f143a00 (ExpandableListView) with handle 0x9d1f7b80
D/EventLogger: sourceInfo [periodCount=1, windowCount=1
D/EventLogger:   period [3850.81]
D/EventLogger:   window [3850.81, false, false]
D/EventLogger: ]
D/EventLogger: Tracks [
D/EventLogger:   Renderer:1 [
D/EventLogger:     Group:0, adaptive_supported=N/A [
D/EventLogger:       [X] Track:0, id=null, mimeType=audio/mpeg, channels=2, sample_rate=44100, supported=YES
D/EventLogger:     ]
D/EventLogger:   ]
D/EventLogger: ]
D/EventLogger: audioEnabled [0.51]
17949-21460/com.google.android.exoplayer2.demo I/OMXClient: MuxOMX ctor
D/EventLogger: audioDecoderInitialized [0.54, OMX.google.mp3.decoder]
D/EventLogger: audioFormatChanged [0.54, id=null, mimeType=audio/mpeg, channels=2, sample_rate=44100]
D/EventLogger: state [0.57, true, R]
17949-21451/com.google.android.exoplayer2.demo D/AudioTrack: Client defaulted notificationFrames to 5512 for frameCount 11025
D/EventLogger: audioSessionId [17057]
D/EventLogger: loading [false]

**Comment by ojw28** [comment]
This question is covered on our FAQ page, [here](https://google.github.io/ExoPlayer/faqs.html#why-are-some-media-files-not-seekable).
