### ISSUE TITLE
Cookie in android

### ISSUE THREAD

**Issue by ArunkarthickNallasamy** [google/ExoPlayer#3333]
How to set cookies for streaming videos, i mean where do i add them? headers?? or do we have some specific functions? we are using DefaultHttpDataSourceFactory so can i add as cookie in DefaultRequestProperties?

**Comment by AquilesCanta** [comment]
I think there are existing issues about this topic, like #3045. Please search in the issue tracker, or provide a  more context if your problem is not covered.

**Comment by ArunkarthickNallasamy** [comment]
That issue that u pointed to actually didnt gave a solution, so can u help out? i just need to know whether adding a header key cookie will solve the issue?
