### ISSUE TITLE
Get when next song will get play

### ISSUE THREAD

**Issue by rajesh-gauswami** [google/ExoPlayer#3336]
I want to get future timestamp when next song will get play. I am using
  ` implementation 'com.google.android.exoplayer:exoplayer:r2.5.3'`

**Comment by tonihei** [comment]
You can use player.getDuration() to get the duration of the current song. I suppose that's the timestamp you are looking for? If you'd like to know the remaining duration, you can also subtract player.getCurrentPosition().

**Comment by rajesh-gauswami** [comment]
CurrentPosition: 30779 
Total Duration :  30775
How this could be possible can you please explane

**Comment by rajesh-gauswami** [comment]
player.getDuration() - player.getCurrentPosition() != time, when next song will get play 
i tested it. Simply i just want to know when exact next song will get start to play.
`long futureTimeStamp  = (System.currentTimeMillis()) + (player.getDuration() - player.getCurrentPosition());`
But its not same when next song get actually play.

**Comment by tonihei** [comment]
The most likely cause is that your media is reporting a slightly wrong duration. Can you check that this is the case?
