### ISSUE TITLE
Support setting thumb Drawable in DefaultTimeBar

### ISSUE THREAD

**Issue by nimdokai** [google/ExoPlayer#3337]
As I understand from releas note of version 2.4.0 Exoplayer `SeekBar` was replaced by `DefaultTimeBar`. https://github.com/google/ExoPlayer/blob/dev-v2/RELEASENOTES.md

As I can seen, as on 19Feb2017: https://github.com/bigexxx/ExoPlayer/blob/c5db6f39a6e07b4f98364ff40476e4e213172488/library/src/main/java/com/google/android/exoplayer2/ui/PlaybackControlView.java 
`exo_progress` was `SeekBar` type:
(line 285): `progressBar = (SeekBar) findViewById(R.id.exo_progress);`

And right now: https://github.com/google/ExoPlayer/blob/release-v2/library/ui/src/main/java/com/google/android/exoplayer2/ui/PlaybackControlView.java
it is:
`(line: 384):timeBar = (TimeBar) findViewById(R.id.exo_progress);`

`DefaultTimeBar` does not have method like `.setThumb()` and it seems to me that thumb is created as `Canvas` in private method `drawPlayhead(Canvas canvas)`.

Question: is is possible to set own thumb icon in `DefaultTimeBar`?

**Comment by andrewlewis** [comment]
We should be able to add a way set the scrubber/thumb drawable soon. As an alternative, you could try making a wrapper around the platform `SeekBar` widget which implements ExoPlayer's `TimeBar` interface.

Do you also need a way to override the seek bar track drawable, or is it just the thumb you need to customize? Thanks.

**Comment by nimdokai** [comment]
Hi Andrew,

Thank you for respond and suggestion.

> Do you also need a way to override the seek bar track drawable, or is it just the thumb you need to customize?
I just need to customize thumb.

Best regards,
Wojciech

**Comment by micer** [comment]
Hey guys, is there any ETA when customization of the thumb Drawable will be added? I might need that one too. Btw I agree that changing seek bar drawable is not needed. Thanks!

**Comment by andrewlewis** [comment]
It will be pushed next time we update the development branch, which is likely to be within the next week or so.

**Comment by ojw28** [comment]
This has been pushed to `dev-v2`.
