### ISSUE TITLE
Determin when video is stalled

### ISSUE THREAD

**Issue by Anton111111** [google/ExoPlayer#3338]
Hello! 
I wonder can i determine that video is stalled for buffering?
I try check onPlayerStateChanged. But i don't see ability to get real state of player. I see that STATE_BUFFERING don't mean that player stop video.  
I need to track how many times video is stalled for buffering,

**Comment by tonihei** [comment]
When the player state changes to STATE_BUFFERING is does exactly that - stop the video playback and buffer data only. Why do you think the player is still playing?

**Comment by Anton111111** [comment]
I just write to the log state of the player. And I see that the video is playing, but STATE_BUFFERING sometimes appears in the log

**Comment by tonihei** [comment]
You probably also see a change back to STATE_READY? That indicates the player continues playing. 

If you like to look any further please also fill out the issue template describing how we can reproduce your problem exactly and also provide example media producing this problem.

**Comment by Anton111111** [comment]
Oh. It's not problem ;)  Only question.

**Comment by ojw28** [comment]
You should see that `STATE_BUFFERING` corresponds to periods of time during which the player is stalled buffering. The ExoPlayer demo app outputs state transitions to logcat, and I see them occurring as expected. You can view these state transitions using `adb logcat` during playback. To get just event transition lines, you can use `adb logcat | grep "EventLogger: state"`.

If you feel there's still a problem, please provide a log captured during usage of the ExoPlayer demo app, annotated with the point at which you think the reported state is incorrect. Thanks!
