### ISSUE TITLE
Audio mismatch on HLS Stream using ExoPlayer

### ISSUE THREAD

**Issue by ffyeahh** [google/ExoPlayer#334]
Hi, i'm using ExoPlayer-dev branch, downloaded on March 4, 2015
i've tested a HLS url, but the audio seems mismatched by a few miliseconds,
the audio is a bit slower than the video, 
but i tried the same link in native MediaPlayer class, and the audio & video matched just fine.

I'm using SetTopBox running android 4.2 to test

i can email you the test URL if needed
(i'm sorry i cannot share the URL publicly)

**Comment by ffyeahh** [comment]
I'm sorry, it turns out to be specific device issue, i've tried it in another device, Sony Xperia Z2 running 4.4.4 and it runs fine...
is there any command to shift audio for some miliseconds in ExoPlayer?

**Comment by ojw28** [comment]
No, although you could modify AudioTrack.java to have the getCurrentPositionUs method return what it returns now, but shifted by the desired amount. Video sync's off the audio, so by doing that you should be able to fix the mismatch.
