### ISSUE TITLE
DtsReader: Add support for other dts sync values 

### ISSUE THREAD

**Issue by zhanghuicuc** [google/ExoPlayer#3340]
Hi,
`DtsReader` only supports sync value of `0x7FFE8001` now. However, according to "ETSI TS 102 114", there are other sync values like `0xFE7F0180`, `0x1FFFE800` and `0xFF1F00E8`. Some of them stand for a 14-bit format.
Any plans on adding support for these sync values and 14-bit dts audio format?

Thanks. 

### Link to test content
http://vod.zhenxian.fm/1812_part.ts

**Comment by AquilesCanta** [comment]
Could you point me to the document version and section that define when the alternative sync words are used? From the copy I have:

>SYNC (Sync word)
> The sync word denotes the start of an audio frame, or a component thereof. For a core substream, the sync word is 0x7ffe8001. A core frame can also exist in an extension substream, where the sync word is 0x02b9261.

But I couldn't find the alternative ones.

**Comment by zhanghuicuc** [comment]
From ETSI TS 102 114 V1.2.1 Section 5.3:

> When DTS bit stream is stored in 16-bit words such as on CD, SYNC will be stored as 0x7ffe and 0x8001. However, when DTS bit stream is viewed on an IBM PC platform, since the high byte and low byte are switched, SYNC will appear like 0xfe7f and x0180.
Note that, in order to make the harsh sound less unpleasant when DTS bit stream is mistakenly played back as PCM format, DTS now provides a 14-bit format that reduces the dynamic range from 16 to 14 bits. In this 14-bit format, DTS bit stream is stored only in the least significant 14 bits of a 16-bit word, the most significant 2 bits are not used, In case of this, SYNC is stored in three words: 0x1fff, 0xe800, and 0x07f. 

I also found the alternative ones in FFmpeg/libavcodec/dca_syncwords.h
`#define    DCA_SYNCWORD_CORE_BE              0x7FFE8001U`
`#define    DCA_SYNCWORD_CORE_LE              0xFE7F0180U`
`#define    DCA_SYNCWORD_CORE_14B_BE          0x1FFFE800U`
`#define    DCA_SYNCWORD_CORE_14B_LE          0xFF1F00E8U`

**Comment by AquilesCanta** [comment]
Hi, we will be pushing support for this soon. If you have any sample content for DCA_SYNCWORD_CORE_LE and DCA_SYNCWORD_CORE_14B_BE, please send a copy to us. Thanks!

**Comment by zhanghuicuc** [comment]
Sorry, I don't have such sample contents either.
