### ISSUE TITLE
How to integrate DRM video play functionality in Exoplayer using EZDRM  and WOWZA server

### ISSUE THREAD

**Issue by dhanashreeborkar** [google/ExoPlayer#3341]
(no description supplied)

**Comment by dhanashreeborkar** [comment]
Please provide guidelines to set up exo player for playing DRM video link on WOWZA server using EZDRM. Is we need to give license key for every DRM video? please explain the working of exo player in detail for playing DRM video.

**Comment by AquilesCanta** [comment]
We will need clarification on what "DRM video" looks like. I don't believe the server makes much difference. The main points to look at are:
- Video container
- The protection scheme
- The DRM platform (widevine, playready, etc)

Depending on what the answers for these are, it could "just work". Look at the demo app for DRM samples, you could try just setting up your video in the demo app sample list.

**Comment by dhanashreeborkar** [comment]
Our DRM platform is widevine, can you explain , what is video container and protection scheme.kindly , provide us the link  for setting up our video in demo app sample list.

**Comment by AquilesCanta** [comment]
Have a look at the DemoApp: In media.exolist.json you will find widevine encrypted samples (for example, under Widevine DASH Policy Tests (GTS)). Try adding an entry for your media.

**Comment by dhanashreeborkar** [comment]
Kindly, share Demo app link.

**Comment by dhanashreeborkar** [comment]
please share link for DEMO APP . with a  piece of code to play DRM video in exo-player

**Comment by andrewlewis** [comment]
Please read the [developer guide](https://google.github.io/ExoPlayer/guide.html) and the [demo application](https://google.github.io/ExoPlayer/demo-application.html) page.

**Comment by dhanashreeborkar** [comment]
How to play downloaded DRM video on exo player in offline mode. Do I have to download 3 different files including mpd ,video.mp4 , audio.mp4 for playing single video on exo player? Thanks for guiding me

**Comment by dhanashreeborkar** [comment]
I wish to store the cached video in local storage and play it on Exo player, Please share code for the same. I am working on DASH videos.

**Comment by AquilesCanta** [comment]
@erdemguven will be able to point you to the right resources.

**Comment by dhanashreeborkar** [comment]
Please share solution for storing cached video in local storage and play it on exo player, including download of drm video.

**Comment by erdemguven** [comment]
For downloading Dash, please look at:
https://github.com/google/ExoPlayer/blob/dev-v2/library/dash/src/main/java/com/google/android/exoplayer2/source/dash/offline/DashDownloader.java
and for offline license:
https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/drm/OfflineLicenseHelper.java
Sorry, currently there is no sample code.

**Comment by dhanashreeborkar** [comment]
How to access cached video and store it in local storage? how play stored video in offline mode condition: video is DRM video ?

**Comment by AquilesCanta** [comment]
@dhanashreeborkar, please take a look at the resources provided by @erdemguven. We might be able to help if you have more specific questions but unfortunately we don't have any demo for this specific feature.
