### ISSUE TITLE
MaxVideoBitrate problem

### ISSUE THREAD

**Issue by erenbakac** [google/ExoPlayer#3347]
Hi,

However i set withMaxVideoBitrate value before player.prepare, player still changes video profiles to higher than i set. For example i set 600.000. when i checked current video bitrate after i while i get 3.000.000.

The stream has 500.000,900.000,1.500.000,3.000.000 video formats

    int maxBitrate=600000;
    player.seekToDefaultPosition();
    trackSelector.getParameters().withMaxVideoBitrate(maxBitrate);
    player.prepare(mediaSource, !haveResumePosition, false);

**Comment by tonihei** [comment]
withMaxVideoBitrate(maxBitrate) does not change the existing set of parameters. It returns a new Parameters class which can be enabled by calling trackSelector.setParameters(parameters)
