### ISSUE TITLE
(Question) M3U8/HLS Parse "Issue"

### ISSUE THREAD

**Issue by MrArca9** [google/ExoPlayer#3354]
Here is what the server returns: 
```
Content-Length: 3162
Connection: close
X-Powered-By: PHP/7.1.8
Access-Control-Allow-Origin: *
Cache-Control: no-store, no-cache, must-revalidate


#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:1336
#EXT-X-ALLOW-CACHE:YES
#EXT-X-TARGETDURATION:16
#EXTINF:8.333333,
/hlsr/TUZYAxUKRA9EA1FfUVNdAwQBUgFRBlYJUFMPUFRUVgBXV1QBVwEADFVHSRsRFhZWVlQ UQZHCAIDBhRHERcEEGkNVEBcQFAFVFBWG05AEFpaXEMCUkkQQFxVGl9GVldQBlQSTkQHHkEDFwtYDj0AVkFQAl1AX1xFWV0URwsKPgZTCVEMAkBcF1ZHSRsLERQRDRssXRYXXVNUQkxFJwUDDlMSWREPDQgVCQNFdwcVRHtWVBFLCgxAVRV9dCZKRk1AVA1EEAcWAxdcR1YBUlJGHxVaDk0MEUBJFwsaMDdGTUBTHEQHCBEPWghHXxsPURELFRVDURE6QFVGRUoABQkEEBReElJETkRYBx06Wg0MClZUTQhXDBYQChcAGklGCQ4MXxBfEDkSD1FEX0cLVFNSAhVE/a3rts2l1/ableenpbiliylnann1/267/4c4dcc5de938400a884864b43c6406c1/267_1336.ts

[Snip]
```
When exoplayer tries loading this up, it includes the space in the url between "ZWVlQ" and "UQZH".

When playing the file in vlc, it replaces the space with a + sign.

Is there a way I can tell the player to replace the space content with a + sign or remove the space all together?

Thanks for the help.

(Under NDA, cannot provide stream link at this time unfortunately :( Hope the issue was well enough described.) 

EDIT:

In version higher than 5.0 it seems to work. Lower than 5.0 it doesn't. Still trying to get a proxy working on higher than lolipop.

**Comment by AquilesCanta** [comment]
I think the URL encoder is responsible for the encoding of unsafe characters (such as space, see [RFC 1738](https://www.ietf.org/rfc/rfc1738.txt), Section 2.2). I'd rather not do this in ExoPlayer to avoid discussions like + vs %20, or others that might follow. 

I can think of two options for solving this until we get to do anything about it. You can either inject your own playlist parser (which could be rather inconvenient, even if wrapping the default one) or you can also inject your own data source, which intercepts urls and escapes them however it suits the server. These components can be injected through HlsMediaSource constructor arguments. Let me know if any of both options works for you.

**Comment by MrArca9** [comment]
Thanks for the reply!

I understand the ambiguity but having the option to .ReplaceUnsafe(Char/String) would be nice to have. Even if it isn't enabled by default. Having slightly more control would be great :)

As far as HlsMediaSource goes, would that intercept calls to the links inside of the m3u8? To my understanding it only deals with the initial fetch? Which would leave me to believe the only other solution is a custom playlist parser, which I don't have the faintest idea where to start with.

**Comment by AquilesCanta** [comment]
> As far as HlsMediaSource goes, would that intercept calls to the links inside of the m3u8? To my understanding it only deals with the initial fetch?

The HlsDataSourceFactory is used to create all DataSources, which are used to access all resources, so you can intercept all URLs, including the ones that need escaping.

If you decided to write your own playlist parser (I think the other alternative is the easier one), you could fork the existing one, adding escaping. It can then be injected through HlsMediaSource's constructor.
