### ISSUE TITLE
lost video head 3 seconds data

### ISSUE THREAD

**Issue by zhoushuqiang** [google/ExoPlayer#3358]
dear:
     I used exoplayer to play mp4, when it play pause 3 seconds, when past 3 second, it start play.
the mp4 file is attach, please Extract the zip file.
[clock-0-10.mp4.zip](https://github.com/google/ExoPlayer/files/1387670/clock-0-10.mp4.zip)

thanks

**Comment by ojw28** [comment]
This content has a weird edit list that's (roughly) clipping the first video frame. We should probably handle such cases better, but why has the content been produced in this way? Seems a little broken to me.

**Comment by zhoushuqiang** [comment]
@ojw28 
Can we be compatible with this video?
the video timestamp is not standard.

**Comment by ojw28** [comment]
We've added an option that lets you manually disable edit list handling, that you can set on the extractor factory (see the change ref'd above - it should be fairly self explanatory). Of course, this will ignore correct edit lists as well.
