### ISSUE TITLE
Not able to play Nikon's 1080p 60 fps video

### ISSUE THREAD

**Issue by oneroman** [google/ExoPlayer#3359]
Hi there,

I am trying to do playback for a particular video using the demo app and could not do it (video is stuck, only audio works). The video is captured by [Nikon D750 Camera](https://en.wikipedia.org/wiki/Nikon_D750) and the video is 1080p 60 fps.

You could find the video [here](https://github.com/oneroman/TestVideoRepository/blob/master/DSC_6132.mov?raw=true) and I did add the video into demo app using the following

> "name": "Misc",
    "samples": [
      {
        "name": "One more test video",
        "uri": "https://github.com/oneroman/TestVideoRepository/blob/master/DSC_6132.mov?raw=true"
      },

Any guidance will be helpful if that's already known issue. Thank in advance!

**Comment by andrewlewis** [comment]
It's likely the decoder just can't keep up. For playback on mobile devices, it's better to use lower frame rate, resolution and/or data rate. [The CDD](https://source.android.com/compatibility/8.0/android-8.0-cdd#5_3_4_h_264) specifies what devices are required to support. This file won't play back at all on some Android devices as support for H.264/AVC High profile is not required.

We recently added some functionality to play just keyframes when the decoder can't keep up (https://github.com/google/ExoPlayer/commit/b3d462df398578836139f14cd708230fdf8a9b04). On the `dev-v2` branch I do see some frames when playing this file, but I think it's not going to be possible to play this file back smoothly without transcoding it first.

**Comment by dtrembovetski** [comment]
@andrewlewis the same video plays fine (albeit without sound) on the same device (Galaxy S6 and Nexus 6, both with Android 7) with the native android player - would it be possible to make at least that work?

**Comment by andrewlewis** [comment]
Thanks for the information. This file has a raw audio track, for which we have to rechunk the samples. It looks like the extracted audio sample timestamps are off by a factor of four. This causes the video to play four times as fast as it should, because of how we handle inconsistencies between the quantity of PCM audio data and its presentation timestamps, which leads to playback not being smooth.

It could be a bug in how we rechunk the audio or calculate its presentation timestamps, or it could be a problem with the original media.

**Comment by oneroman** [comment]
@andrewlewis I am sharing with you one more [video](https://github.com/oneroman/TestVideoRepository/blob/master/DSC_6156.mov?raw=true) which captured by the same camera model and has 1080p 30 fps and we are able to reproduce the same issue using it. So, the point is that root cause probably is not due to frame rate/data rate, it probably causes by audio.

>    {
        "name": "Nikon's 1080p 30fps",
        "uri": "https://github.com/oneroman/TestVideoRepository/blob/master/DSC_6156.mov?raw=true"
      },

**Comment by rupiapps** [comment]
hi, I have exactly the same problem when trying to play back files from Canon or Nikon cameras. Could this be solved by setting playbackrate to 0.25?

**Comment by andrewlewis** [comment]
@Rupilein Please could you provide a link to one of the files so we can verify the cause is the same? Thanks.

**Comment by rupiapps** [comment]
hi, I put a sample in google drive: https://drive.google.com/file/d/1VU9ADy2bfWbYNn3XBER6PL8CrS3qLuCj/view?usp=sharing
settings the playbackrate did not help.
It would be cool if this could be fixed :)

**Comment by andrewlewis** [comment]
This is actually the same as #4228, for which we should have a fix soon.

**Comment by rupiapps** [comment]
works for me with 2.8.1
great work :+1:
