### ISSUE TITLE
Can not play TS file

### ISSUE THREAD

**Issue by DavidNguyen2017** [google/ExoPlayer#3361]
**Issue description**

I try to play a TS file but can not, may be have problem decode audio. VLC can play normal

Following is log message:

```
10-17 12:00:25.910 9121-9121/com.google.android.exoplayer2.demo D/EventLogger: state [21.29, true, R]
10-17 12:00:25.944 3793-3853/? D/AudioFlinger: mixer(0xf0b1dc00) throttle end: throttle time(10)
10-17 12:00:25.964 3793-3853/? D/AudioFlinger: mixer(0xf0b1dc00) throttle end: throttle time(4)
10-17 12:00:27.717 3799-9920/? W/SoftAAC2: aacDecoder_DecodeFrame decoderErr = 0x4004
10-17 12:00:27.717 3799-9920/? W/SoftAAC2: AAC decoder returned error 0x4004, substituting silence
10-17 12:00:27.808 3799-9920/? W/SoftAAC2: aacDecoder_DecodeFrame decoderErr = 0x4004
10-17 12:00:27.808 3799-9920/? W/SoftAAC2: AAC decoder returned error 0x4004, substituting silence
10-17 12:00:27.848 3799-9920/? W/SoftAAC2: aacDecoder_DecodeFrame decoderErr = 0x4004
10-17 12:00:27.848 3799-9920/? W/SoftAAC2: AAC decoder returned error 0x4004, substituting silence
10-17 12:00:28.065 3799-9920/? W/SoftAAC2: aacDecoder_DecodeFrame decoderErr = 0x4002
10-17 12:00:28.066 3799-9920/? W/SoftAAC2: AAC decoder returned error 0x4002, substituting silence
10-17 12:00:28.271 3799-9920/? W/SoftAAC2: aacDecoder_DecodeFrame decoderErr = 0x4004
10-17 12:00:28.271 3799-9920/? W/SoftAAC2: AAC decoder returned error 0x4004, substituting silence
10-17 12:00:28.341 3799-9920/? W/SoftAAC2: aacDecoder_DecodeFrame decoderErr = 0x4004
10-17 12:00:28.341 3799-9920/? W/SoftAAC2: AAC decoder returned error 0x4004, substituting silence
10-17 12:00:30.064 3799-9920/? W/SoftAAC2: aacDecoder_DecodeFrame decoderErr = 0x4004
10-17 12:00:30.064 3799-9920/? W/SoftAAC2: AAC decoder returned error 0x4004, substituting silence
10-17 12:00:30.986 3799-9920/? I/SoftAAC2: Reconfiguring decoder: 48000->48000 Hz, 2->1 channels
10-17 12:00:31.048 3799-9920/? W/SoftAAC2: aacDecoder_DecodeFrame decoderErr = 0x4002
10-17 12:00:31.048 3799-9920/? W/SoftAAC2: AAC decoder returned error 0x4002, substituting silence
10-17 12:00:31.049 3799-9920/? I/SoftAAC2: Reconfiguring decoder: 48000->48000 Hz, 1->2 channels
10-17 12:00:31.065 9121-9794/com.google.android.exoplayer2.demo D/AudioTrack: Client defaulted notificationFrames to 8208 for frameCount 16416
10-17 12:00:31.083 9121-9794/com.google.android.exoplayer2.demo D/AudioTrack: Client defaulted notificationFrames to 8208 for frameCount 16416
10-17 12:00:31.086 3799-9920/? W/SoftAAC2: aacDecoder_DecodeFrame decoderErr = 0x4002
10-17 12:00:31.086 3799-9920/? W/SoftAAC2: AAC decoder returned error 0x4002, substituting silence
10-17 12:00:31.092 3799-9920/? W/SoftAAC2: aacDecoder_DecodeFrame decoderErr = 0x4002
10-17 12:00:31.092 3799-9920/? W/SoftAAC2: AAC decoder returned error 0x4002, substituting silence
10-17 12:00:31.431 3799-9920/? W/SoftAAC2: aacDecoder_DecodeFrame decoderErr = 0x4004
10-17 12:00:31.431 3799-9920/? W/SoftAAC2: AAC decoder returned error 0x4004, substituting silence
10-17 12:00:31.733 9121-9794/com.google.android.exoplayer2.demo E/AudioTrack: Discontinuity detected [expected 66484488, got 66271155]
10-17 12:00:32.223 3799-9920/? W/SoftAAC2: aacDecoder_DecodeFrame decoderErr = 0x4004
10-17 12:00:32.223 3799-9920/? W/SoftAAC2: AAC decoder returned error 0x4004, substituting silence
10-17 12:00:32.498 9121-9794/com.google.android.exoplayer2.demo E/AudioTrack: Discontinuity detected [expected 67039155, got 66825822]
10-17 12:00:32.498 3799-9920/? W/SoftAAC2: aacDecoder_DecodeFrame decoderErr = 0x4004
10-17 12:00:32.498 3799-9920/? W/SoftAAC2: AAC decoder returned error 0x4004, substituting silence
10-17 12:00:33.394 3799-9920/? W/SoftAAC2: aacDecoder_DecodeFrame decoderErr = 0x4007
10-17 12:00:33.394 3799-9920/? W/SoftAAC2: AAC decoder returned error 0x4007, substituting silence
10-17 12:00:33.435 9121-9794/com.google.android.exoplayer2.demo E/AudioTrack: Discontinuity detected [expected 67764489, got 67551155]
10-17 12:00:33.863 3799-9920/? W/SoftAAC2: aacDecoder_DecodeFrame decoderErr = 0x4004
10-17 12:00:33.863 3799-9920/? W/SoftAAC2: AAC decoder returned error 0x4004, substituting silence
10-17 12:00:34.462 9121-9794/com.google.android.exoplayer2.demo E/AudioTrack: Discontinuity detected [expected 68575155, got 68361822]
10-17 12:00:35.004 4071-4071/system_process V/NotificationService: pkg=de.blinkt.openvpn canInterrupt=false intercept=true
10-17 12:00:35.013 4071-4071/system_process V/NotificationService: pkg=de.blinkt.openvpn canInterrupt=false intercept=true
10-17 12:00:35.746 9121-9794/com.google.android.exoplayer2.demo E/AudioTrack: Discontinuity detected [expected 69641822, got 69428489]
10-17 12:00:36.485 3799-9920/? W/SoftAAC2: aacDecoder_DecodeFrame decoderErr = 0x4004
10-17 12:00:36.485 3799-9920/? W/SoftAAC2: AAC decoder returned error 0x4004, substituting silence
10-17 12:00:37.280 9121-9794/com.google.android.exoplayer2.demo E/AudioTrack: Discontinuity detected [expected 70964489, got 70751155]
10-17 12:00:37.381 3799-9920/? W/SoftAAC2: aacDecoder_DecodeFrame decoderErr = 0x4002
10-17 12:00:37.381 3799-9920/? W/SoftAAC2: AAC decoder returned error 0x4002, substituting silence
10-17 12:00:38.003 9121-9794/com.google.android.exoplayer2.demo E/AudioTrack: Discontinuity detected [expected 71476488, got 71263155]
10-17 12:00:38.193 3799-9920/? W/SoftAAC2: aacDecoder_DecodeFrame decoderErr = 0x4004
10-17 12:00:38.193 3799-9920/? W/SoftAAC2: AAC decoder returned error 0x4004, substituting silence
10-17 12:00:38.276 3799-9920/? W/SoftAAC2: aacDecoder_DecodeFrame decoderErr = 0x4002
10-17 12:00:38.276 3799-9920/? W/SoftAAC2: AAC decoder returned error 0x4002, substituting silence
10-17 12:00:38.874 9121-9794/com.google.android.exoplayer2.demo E/AudioTrack: Discontinuity detected [expected 72137822, got 71924489]
10-17 12:00:39.088 3799-9920/? W/SoftAAC2: aacDecoder_DecodeFrame decoderErr = 0x4004
10-17 12:00:39.088 3799-9920/? W/SoftAAC2: AAC decoder returned error 0x4004, substituting silence
10-17 12:00:39.431 3799-9920/? W/SoftAAC2: aacDecoder_DecodeFrame decoderErr = 0x4007
10-17 12:00:39.431 3799-9920/? W/SoftAAC2: AAC decoder returned error 0x4007, substituting silence
10-17 12:00:39.926 9121-9794/com.google.android.exoplayer2.demo E/AudioTrack: Discontinuity detected [expected 72969822, got 72756489]
10-17 12:00:39.947 3799-9920/? W/SoftAAC2: aacDecoder_DecodeFrame decoderErr = 0x4004
10-17 12:00:39.947 3799-9920/? W/SoftAAC2: AAC decoder returned error 0x4004, substituting silence
10-17 12:00:40.560 3799-9920/? W/SoftAAC2: aacDecoder_DecodeFrame decoderErr = 0x4007
10-17 12:00:40.561 3799-9920/? W/SoftAAC2: AAC decoder returned error 0x4007, substituting silence
10-17 12:00:40.985 9121-9794/com.google.android.exoplayer2.demo E/AudioTrack: Discontinuity detected [expected 73823156, got 73609822]
10-17 12:00:41.157 3799-9920/? W/SoftAAC2: aacDecoder_DecodeFrame decoderErr = 0x4004
10-17 12:00:41.158 3799-9920/? W/SoftAAC2: AAC decoder returned error 0x4004, substituting silence
10-17 12:00:41.592 4071-4105/system_process D/AlarmManager: targetPackage = com.android.providers.tv
10-17 12:00:41.592 4071-4105/system_process D/AlarmManager: targetPackage = com.estrongs.android.pop
10-17 12:00:41.607 4071-4105/system_process I/ActivityManager: Start proc 10344:com.android.providers.tv/u0a32 for service com.android.providers.tv/.EpgDataCleanupService
10-17 12:00:41.608 4071-4125/system_process D/AlarmManager: targetPackage = null
10-17 12:00:41.611 4071-4127/system_process D/AlarmManager: targetPackage = null
10-17 12:00:41.683 10344-10344/? W/System: ClassLoader referenced unknown path: /system/priv-app/TvProvider/lib/arm
10-17 12:00:41.685 10344-10351/? I/art: Debugger is no longer active
10-17 12:00:41.685 10344-10351/? I/art: Starting a blocking GC Instrumentation
10-17 12:00:41.715 4071-5051/system_process D/AlarmManager: targetPackage = com.google.android.gms
10-17 12:00:41.717 4071-2884/system_process D/AlarmManager: targetPackage = com.android.providers.tv
10-17 12:00:41.739 10344-10360/? D/EpgDataCleanupService: Received intent: Intent { act=com.android.providers.tv.intent.CLEAN_UP_EPG_DATA flg=0x4 cmp=com.android.providers.tv/.EpgDataCleanupService (has extras) }
10-17 12:00:41.789 4071-5041/system_process I/ActivityManager: Killing 7542:org.videolan.vlc/u0a93 (adj 906): empty #17
10-17 12:00:41.810 4071-4839/system_process D/ActivityManager: cleanUpApplicationRecord -- 7542
10-17 12:00:41.866 9121-9794/com.google.android.exoplayer2.demo E/AudioTrack: Discontinuity detected [expected 74484488, got 74271155]
10-17 12:00:43.226 9121-9794/com.google.android.exoplayer2.demo E/AudioTrack: Discontinuity detected [expected 75636489, got 75423155]
10-17 12:00:44.557 3799-9920/? W/SoftAAC2: aacDecoder_DecodeFrame decoderErr = 0x4004
10-17 12:00:44.557 3799-9920/? W/SoftAAC2: AAC decoder returned error 0x4004, substituting silence
10-17 12:00:44.578 9121-9794/com.google.android.exoplayer2.demo E/AudioTrack: Discontinuity detected [expected 76767155, got 76553822]
10-17 12:00:45.108 3799-9920/? W/SoftAAC2: aacDecoder_DecodeFrame decoderErr = 0x4004
10-17 12:00:45.108 3799-9920/? W/SoftAAC2: AAC decoder returned error 0x4004, substituting silence
10-17 12:00:45.264 4071-4071/system_process V/NotificationService: pkg=de.blinkt.openvpn canInterrupt=false intercept=true
10-17 12:00:45.278 4071-4071/system_process V/NotificationService: pkg=de.blinkt.openvpn canInterrupt=false intercept=true
10-17 12:00:45.679 9121-9794/com.google.android.exoplayer2.demo E/AudioTrack: Discontinuity detected [expected 77663155, got 77449822]
10-17 12:00:45.965 3799-9920/? W/SoftAAC2: aacDecoder_DecodeFrame decoderErr = 0x4004
10-17 12:00:45.965 3799-9920/? W/SoftAAC2: AAC decoder returned error 0x4004, substituting silence
10-17 12:00:46.834 9121-9794/com.google.android.exoplayer2.demo E/AudioTrack: Discontinuity detected [expected 78601822, got 78388489]
10-17 12:00:47.988 3799-9920/? W/SoftAAC2: aacDecoder_DecodeFrame decoderErr = 0x4004
10-17 12:00:47.989 3799-9920/? W/SoftAAC2: AAC decoder returned error 0x4004, substituting silence
10-17 12:00:48.237 3799-9920/? W/SoftAAC2: aacDecoder_DecodeFrame decoderErr = 0x4007
10-17 12:00:48.237 3799-9920/? W/SoftAAC2: AAC decoder returned error 0x4007, substituting silence
10-17 12:00:48.347 9121-9794/com.google.android.exoplayer2.demo E/AudioTrack: Discontinuity detected [expected 79903156, got 79689822]
10-17 12:00:48.841 3799-9920/? W/SoftAAC2: aacDecoder_DecodeFrame decoderErr = 0x4004
10-17 12:00:48.841 3799-9920/? W/SoftAAC2: AAC decoder returned error 0x4004, substituting silence
10-17 12:00:49.609 9121-9794/com.google.android.exoplayer2.demo E/AudioTrack: Discontinuity detected [expected 80948488, got 80735155]
10-17 12:00:50.379 3799-9920/? W/SoftAAC2: aacDecoder_DecodeFrame decoderErr = 0x4006
10-17 12:00:50.379 3799-9920/? W/SoftAAC2: AAC decoder returned error 0x4006, substituting silence
10-17 12:00:50.550 9121-9794/com.google.android.exoplayer2.demo E/AudioTrack: Discontinuity detected [expected 81673822, got 81460489]
10-17 12:00:51.167 3799-9920/? W/SoftAAC2: aacDecoder_DecodeFrame decoderErr = 0x4004
10-17 12:00:51.167 3799-9920/? W/SoftAAC2: AAC decoder returned error 0x4004, substituting silence
10-17 12:00:51.565 9121-9794/com.google.android.exoplayer2.demo E/AudioTrack: Discontinuity detected [expected 82484489, got 82271155]
10-17 12:00:51.929 3799-9920/? W/SoftAAC2: aacDecoder_DecodeFrame decoderErr = 0x4002
10-17 12:00:51.929 3799-9920/? W/SoftAAC2: AAC decoder returned error 0x4002, substituting silence
10-17 12:00:51.959 3799-9920/? W/SoftAAC2: aacDecoder_DecodeFrame decoderErr = 0x4004
10-17 12:00:51.959 3799-9920/? W/SoftAAC2: AAC decoder returned error 0x4004, substituting silence
10-17 12:00:52.213 3799-9920/? W/SoftAAC2: aacDecoder_DecodeFrame decoderErr = 0x400a
10-17 12:00:52.213 3799-9920/? W/SoftAAC2: AAC decoder returned error 0x400a, substituting silence
10-17 12:00:52.480 5424-5751/com.google.android.apps.mediashell I/chromium: [5424:5751:INFO:ssdp_device.c(101)] SSDP packets sent for 117 seconds = 15
10-17 12:00:52.848 9121-9794/com.google.android.exoplayer2.demo E/AudioTrack: Discontinuity detected [expected 83551155, got 83337822]
10-17 12:00:52.939 3799-9920/? W/SoftAAC2: aacDecoder_DecodeFrame decoderErr = 0x4007
10-17 12:00:52.939 3799-9920/? W/SoftAAC2: AAC decoder returned error 0x4007, substituting silence
10-17 12:00:53.550 3799-9920/? W/SoftAAC2: aacDecoder_DecodeFrame decoderErr = 0x4004
10-17 12:00:53.550 3799-9920/? W/SoftAAC2: AAC decoder returned error 0x4004, substituting silence
10-17 12:00:53.857 9121-9794/com.google.android.exoplayer2.demo E/AudioTrack: Discontinuity detected [expected 84340489, got 84127155]
```

**Link to test content**
http://45.119.81.26/au_stream.zip

**Version of ExoPlayer being used**
Exoplayer release v2

**Device(s) and version(s) of Android being used**
We tested on the Android 7, Amlogic device.

**Comment by ojw28** [comment]
Have you read our [FAQs](https://google.github.io/ExoPlayer/faqs.html#why-do-some-mpeg-ts-files-fail-to-play), and if not, does that help?

**Comment by DavidNguyen2017** [comment]
Dear ojw28

Thank you for your supporting
I had try to call function setTsExtractorFlags with: FLAG_DETECT_ACCESS_UNITS and FLAG_ALLOW_NON_IDR_KEYFRAMES, but still do not work. Can you help check file that i had public: http://45.119.81.26/au_stream.zip?

Thanks,

**Comment by DavidNguyen2017** [comment]
Dear ojw28,

My testing file have audio sample rate is: 44100 hz, so i try convert to 48000 hz then it play ok, so is exoplayer can not play file with audio sample rate is: 44100 hz or this problem related to hardware decode?

Thanks,

**Comment by ojw28** [comment]
VLC also seems to have issues playing this file (it keeps inserting little silences during the playback). I think it's probably just not encoded correctly.

**Comment by DavidNguyen2017** [comment]
Dear ojw28,

Thank you for your information
- I had another file really play smooth on the VLC Android, MxPlayer,  MoviePlayer, but with Exoplayer then can not, here is file that i had tested, can you help me check it.
http://45.119.81.26/au_test_nonscramble_920.zip

- This file have TS packet size is: 204 bytes, it have insert 16 bytes FEC information at end of each package

- I had changed TS_PACKET_SIZE in the TsExtractor.java equal 204
> private static final int TS_FEC_SIZE = 16;
> private static final int TS_PACKET_SIZE = 188+TS_FEC_SIZE; 

- Exoplayer when play with this file show black screen:
![20171020_095607](https://user-images.githubusercontent.com/32013022/31803395-a7bff2d4-b57d-11e7-8586-15f6f9f827ea.jpg)

- I had use tool to analysis this file then see PCR information include direct in the video stream different with other file that Exoplayer can play. Following is analysis image:

> can not play

![pcr](https://user-images.githubusercontent.com/32013022/31803538-81651c08-b57e-11e7-8142-9dc73243dd35.png)

> play well
![pcr1](https://user-images.githubusercontent.com/32013022/31803632-1215a088-b57f-11e7-84f0-ef845ff484c8.png)

Thanks,

**Comment by DavidNguyen2017** [comment]
Dear Ojw28,

I am reality need to help check on this file: http://45.119.81.26/au_test_nonscramble_920.zip
I am working project use Exoplayer to playback multicast scramble stream. and i spent more time to debug can not play stream problem, but still is not successful.

Thank you for advice

**Comment by rcvangemert** [comment]
Are you using live555 library? I have found that exoplayer cannot play my
ts file/sream but vlc can. (os android)

**Comment by DavidNguyen2017** [comment]
Dear rcvangemert,

Thank you for your information.

Yes file that i need to help check then VLC, MxPlay, ... can play well on the android, but Exoplay then can not.
No, i do not use live555 library, i use Dektec StreamXpress(https://www.dektec.com/products/applications/StreamXpress/) to multicast stream my ts file through RTP, and use Exoplayer to playback.

Thanks,

**Comment by ojw28** [comment]
> This file have TS packet size is: 204 bytes

I don't really understand this. TS packets are by definition 188 bytes. If you're doing something that's not specification compliant, you shouldn't expect it to work ;). Is your content according to some media standard? If so could you point us to it. Thanks!

**Comment by DavidNguyen2017** [comment]
Dear ojw28,

Thank you for your supporting,

> TS packets are by definition 188 bytes

- Yes, TS packet size is 188 bytes, you are correct.
- But in this case added 16 bytes [Forward error correction](https://en.wikipedia.org/wiki/Forward_error_correction)(FEC) for purpose fix error if transmission have error issue. Forward error correction is added by [ISDB](https://en.wikipedia.org/wiki/ISDB) & [DVB](https://en.wikipedia.org/wiki/Digital_Video_Broadcasting) (16 bytes)
- Please see image following is define transport stream packet, it is reference from this link: https://en.wikipedia.org/wiki/MPEG_transport_stream

![image](https://user-images.githubusercontent.com/32013022/32002075-c87e6450-b9c5-11e7-815e-a28d18b42916.png)

Thanks,

**Comment by ojw28** [comment]
Shouldn't the communication medium be removing the additional information at the receiving end, also?

**Comment by DavidNguyen2017** [comment]
Dear ojw28,

- Yes, we can remove this additional information.

Thanks,

**Comment by DavidNguyen2017** [comment]
Dear ojw28,

Have any update for this issue.

Thanks,

**Comment by ojw28** [comment]
My understanding was you were going to be removing the additional information, as per your comment above. I'd expect that to fix the issue, so I'm unclear what kind of update you're looking for from our side. Please clarify. Thanks!

**Comment by DavidNguyen2017** [comment]
Dear ojw28,

Thank you for your information,

But although i had remove additional information, Exoplayer still can not play, in while MX Player, MoviePlayer, VLC play normal
I upload file after remove additional information here, you can download and check it
http://45.119.81.26/dump_input.zip

Thank you very much,

**Comment by ojw28** [comment]
The sample you've attached plays fine on a test device I have (Galaxy S8).

**Comment by DavidNguyen2017** [comment]
Dear ojw28,

Oh, i am test on AmLogic device and android 7, just hear sound, video do not show(black screen)
What Exoplayer version that you test(release v2)?

Thanks,

**Comment by ojw28** [comment]
There's only audio if I play it in VLC too. And `mediainfo` can only see an audio track (see below). If there's video in this file, it's not being declared correctly. This is a content issue, not an issue with ExoPlayer.
```
General
ID                                       : 920 (0x398)
Complete name                            : /usr/local/google/home/olly/Downloads/dump_input.ts
Format                                   : MPEG-TS
File size                                : 276 MiB
Duration                                 : 12mn 4s
Overall bit rate mode                    : Constant
Overall bit rate                         : 3 200 Kbps
Network name                             : #K#D#D#I

Audio
ID                                       : 260 (0x104)
Menu ID                                  : 920 (0x398)
Format                                   : AAC
Format/Info                              : Advanced Audio Codec
Format version                           : Version 2
Format profile                           : LC
Muxing mode                              : ADTS
Codec ID                                 : 15
Duration                                 : 12mn 4s
Bit rate mode                            : Variable
Bit rate                                 : 126 Kbps
Channel(s)                               : 2 channels
Channel positions                        : Front: L R
Sampling rate                            : 48.0 KHz
Compression mode                         : Lossy
Stream size                              : 10.9 MiB (4%)

Menu
ID                                       : 50 (0x32)
Menu ID                                  : 920 (0x398)
Duration                                 : 12mn 4s
List                                     : 258 (0x102) () / 260 (0x104) (AAC)
Service name                             : %0%j!<%s%A%c%s%M%k
Service provider                         : #K#D#D#I
Service type                             : digital television
UTC 2017-09-19 11:00:00                  : ja:?7!&GO3X9V:B%[!<%9%"%+%G%_!<!!!t#4#2 / ja:!V%1%s%?%C%-!<$NGO;:!W / reserved for future use /  / 00:30:00 / 
UTC 2017-09-19 11:30:00                  : ja:6%GO%o%s%@%i!<#2!!!t#1!$#2 / ja:!t#1!VGnB?H/!A@uLnLwE5!!:F=PH/!W!t#2!V7'K\;TH/!A%H%+%iGO$H@uLnLwE5!W / reserved for future use /  / 01:00:00 / 
UTC 2017-09-19 12:30:00                  : ja:1I8w$NL>GO$?$A%;%l%/%7%g%s!J%G%#!<%W%9%+%$!K / ja:!t#2#3#4!V%G%#!<%W%9%+%$!W / reserved for future use /  / 01:00:00 / 
```

**Comment by DavidNguyen2017** [comment]
Dear ojw28,

Thank you for you information

Here i can play this file with VLC, MX Player, Movie Player on the Android 7, AmLogic device(Android TV Box). I can see video and hear sound too.
And i analyze media information have Video Track, so i do not think content issue.

> General
> ID                          : 920 (0x398)
> Complete name               : C:\Users\ASUS\Downloads\dump_input\dump_input.ts
> Format                      : MPEG-TS
> File size                   : 276 MiB
> Duration                    : 12 min 4 s
> Overall bit rate mode       : Constant
> Overall bit rate            : 3 200 kb/s
> Network name                : #K#D#D#I
> 
> Video
> ID                          : 258 (0x102)
> Menu ID                     : 920 (0x398)
> Format                      : HEVC
> Format/Info                 : High Efficiency Video Coding
> Format profile              : Main 10@L3@Main
> Codec ID                    : 36
> Duration                    : 12 min 4 s
> Width                       : 720 pixels
> Height                      : 240 pixels
> Display aspect ratio        : 2.727
> Frame rate                  : 59.940 (60000/1001) FPS
> Standard                    : Component
> Color space                 : YUV
> Chroma subsampling          : 4:2:0 (Type 0)
> Bit depth                   : 10 bits
> Color range                 : Limited
> Color primaries             : BT.709
> Transfer characteristics    : BT.709
> Matrix coefficients         : BT.709
> 
> Audio
> ID                          : 260 (0x104)
> Menu ID                     : 920 (0x398)
> Format                      : AAC
> Format/Info                 : Advanced Audio Codec
> Format version              : Version 2
> Format profile              : LC
> Muxing mode                 : ADTS
> Codec ID                    : 15
> Duration                    : 12 min 4 s
> Bit rate mode               : Variable
> Channel(s)                  : 2 channels
> Channel positions           : Front: L R
> Sampling rate               : 48.0 kHz
> Frame rate                  : 46.875 FPS (1024 spf)
> Compression mode            : Lossy
> Delay relative to video     : -799 ms
> 
> Menu
> ID                          : 50 (0x32)
> Menu ID                     : 920 (0x398)
> Duration                    : 12 min 4 s
> List                        : 258 (0x102) (HEVC) / 260 (0x104) (AAC)
> Service name                : %0%j!<%s%A%c%s%M%k
> Service provider            : #K#D#D#I
> Service type                : digital television
> UTC 2017-09-19 11:00:00     : ja:?7!&GO3X9V:B%[!<%9%"%+%G%_!<!!!t#4#2 / ja:!V%1%s%?%C%-!<$NGO;:!W / reserved for future use /  / 00:30:00 / 
> UTC 2017-09-19 11:30:00     : ja:6%GO%o%s%@%i!<#2!!!t#1!$#2 / ja:!t#1!VGnB?H/!A@uLnLwE5!!:F=PH/!W!t#2!V7'K\;TH/!A%H%+%iGO$H@uLnLwE5!W / reserved for future use /  / 01:00:00 / 
> UTC 2017-09-19 12:30:00     : ja:1I8w$NL>GO$?$A%;%l%/%7%g%s!J%G%#!<%W%9%+%$!K / ja:!t#2#3#4!V%G%#!<%W%9%+%$!W / reserved for future use /  / 01:00:00 / 

Thanks,

**Comment by ojw28** [comment]
I suspect you're looking at different media than you attached in https://github.com/google/ExoPlayer/issues/3361#issuecomment-342188380, since I'm not seeing that?

**Comment by AquilesCanta** [comment]
Just a thought: Check whether adding an `H265Reader` for PID 258 in `TsExtractor` fixes your issue, @DavidNguyen2017. This is a longshot, but maybe you are using a newer mediainfo version that sniffs all PIDs (the VLC part is otherwise surprising). Possibly, the PMT doesn't include an entry for the HEVC stream that comes on PID 258, which would explain why it is not delivered by ExoPlayer.

If this is the case, then media needs to be fixed, and there is nothing ExoPlayer can do about it.

**Comment by DavidNguyen2017** [comment]
Dear ojw28,

I analyze same your file

Thanks,

**Comment by DavidNguyen2017** [comment]
Dear AquilesCanta,

Thank you for your information.
So Exoplayer do not support play multi PID same other player? is it correct?

Thanks,

**Comment by AquilesCanta** [comment]
> So Exoplayer do not support play multi PID same other player? is it correct?

No. ExoPlayer does support multiple PIDs. I have checked the stream, ExoPlayer does allocate an H265 reader for pid 258, so there is no need for you to manually do it. 

The h265 stream does not seem to contain any key frames, which likely means that the stream is malformed. @andrewlewis, can you provide insight here? Perhaps some kind of FLAG_ALLOW_NON_IDR_KEYFRAMES is applicable here?

@DavidNguyen2017, this is most likely not going to be addressed this week or the next. Please be patient.

**Comment by DavidNguyen2017** [comment]
Dear AquilesCanta,

Thank you for your information
I will wait update from you

Many thanks,

**Comment by andrewlewis** [comment]
Implementing a `FLAG_ALLOW_NON_IDR_KEYFRAMES` for `H265Reader` is unfortunately a bit complicated because it would be necessary to store the `num_extra_slice_header_bits` for every defined PPS in order to be able to parse `slice_type` from the `slice_segment_header` (and we don't currently parse the contents of PPSs). I had a quick try anyway and even then the decoder threw an error when decoding the first I slice as a keyframe, so I'm not sure that even having such a flag would fix playing this stream.

I will close this for now because the media appears not to have IDR frames. Please feel free to investigate further and reopen if the bitstream is valid and support for reading it can be implemented in `H265Reader`.
