### ISSUE TITLE
IndexOutOfBoundsException: SimpleExoPlayer.getDuration()

### ISSUE THREAD

**Issue by Khang-NT** [google/ExoPlayer#3362]
### Issue description, Reproduction steps
I have no idea why and how does it happen, just receive some crash logs from my crash reporting service (affected at lest 30 users, 20 different kind of devices).
I post here to find if someone have same issue or has solution for it.

### Link to test content
N/A

### Version of ExoPlayer being used
`r2.5.3`

### Device(s) and version(s) of Android being used
Variety device and version.

### A full bug report captured from the device
Crash log:
```
java.lang.IndexOutOfBoundsException
	at com.google.android.exoplayer2.Timeline$1.getWindow(Timeline.java:522)
	at com.google.android.exoplayer2.Timeline.getWindow$28c22ef2(Timeline.java:618)
	at com.google.android.exoplayer2.Timeline.getWindow(Timeline.java:605)
	at com.google.android.exoplayer2.ExoPlayerImpl.getDuration(ExoPlayerImpl.java:313)
	at com.google.android.exoplayer2.SimpleExoPlayer.getDuration(SimpleExoPlayer.java:749)
```

**Comment by tonihei** [comment]
Can you give us some more details about the media sources you use and the point in time when this exception occurs (e.g. does it happen after a seek, or in which method do you call player.getDuration())?

**Comment by ojw28** [comment]
Also, how do you call `prepare` on the player? Are you using the one argument version, or the three argument version? If you're using the one argument version, that should be fine. If you're using the three argument version, what are you setting the arguments to? Thanks!

**Comment by Khang-NT** [comment]
I didn't experience this crash on my device, so I don't know what really happen before crash. 
The app is an music player, which can stream YouTube DASH audio, HLS live video, and local music on user phone. No clue to know which source user was playing.

I use `HlsMediaSource` for HLS video, `ExtractorMediaSource` for the rest, compose with `ConcatenatingMediaSource` and `LoopingMediaSource` as the only one argument to call `prepare` .

This error didn't happen on previous `ExoPlayer` version that I used: `r2.4.3`

**Comment by Khang-NT** [comment]
It happens when I call `getDuration` on the event `Player.EventListener.onTimelineChanged`

**Comment by tonihei** [comment]
Thanks for the additional info. We have some ideas what might be going wrong here and are currently looking into this. We'll let you know as soon as we published a fix.

**Comment by ojw28** [comment]
Should be fixed in `dev-v2`.
