### ISSUE TITLE
Android 5.0 Audio and video asynchrony

### ISSUE THREAD

**Issue by stubhbw** [google/ExoPlayer#3368]
Ask a question and ask for help:
B_Activity is responsible for local video playback, there is a button to display or hide the player, click switch, no problem on the Android6.0, but Android5.0 will lead to hide again display audio and video synchronization (in the hands of the two sets of mobile phone are XIAOMI red rice 2A), video seems to every time is directly loaded into the cache to the position, waiting for synchronization of audio after the broadcast. What solution do?

**Comment by stubhbw** [comment]
B_Activity init SimpleExoPlayer:

            TrackSelection.Factory adaptiveTrackSelectionFactory = new AdaptiveTrackSelection.Factory(BANDWIDTH_METER);
            trackSelector = new DefaultTrackSelector(adaptiveTrackSelectionFactory);
            LoadControl loadControl = new DefaultLoadControl();
            player = ExoPlayerFactory.newSimpleInstance(this, trackSelector, loadControl);
            player.addListener(this);
            mSimpleExoPlayerView.setPlayer(player, trackSelector);
            mSimpleExoPlayerView.setBackgroundResource(R.color.black);
            player.setPlayWhenReady(true);
            mDataSourceFactory = new DefaultDataSourceFactory(this,
                    Util.getUserAgent(this, "MyAppliaction"), BANDWIDTH_METER);
            mExtractorsFactory = new DefaultExtractorsFactory();
            MediaSource videoSource = new ExtractorMediaSource(uri,
                mDataSourceFactory, mExtractorsFactory,
           //  mainHandler, error -> Log.e(TAG, "onLoadError: " + error.getMessage()));
                null, null);
            player.prepare(videoSource);

xml in B_Activity:

      <RelativeLayout
            xmlns:android="http://schemas.android.com/apk/res/android"
            xmlns:tools="http://schemas.android.com/tools"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:id="@+id/root"
            tools:context="com.yinji.lgr.ui.activity.PlayActivity">

      <com.yinji.lgr.view.video.SimpleExoPlayerView
            android:id="@+id/simpleExoPlayerView"
            android:layout_width="match_parent"
            android:layout_height="match_parent"/>
      </RelativeLayout>

Player to play local video, then hide the player controls SimpleExoPlayerView the hide, then the player again, the video will display the time axis in front of the screen, the picture frame, the process is not affected by time, audio, video and audio to the painting surface position, video and audio synchronous playback. Again on two days. No progress, did not find the video refresh screen API, the preliminary test of the Android below M will appear this phenomenon. Who can help me? Thank you very much

**Comment by ojw28** [comment]
I do not understand what the question is, sorry. We really need proper concrete reproduction steps to investigate issues. Thanks.
