### ISSUE TITLE
ExoPlayer is unable to play certain m3u playlists

### ISSUE THREAD

**Issue by hallyhaa** [google/ExoPlayer#3369]
### Issue description
ExoPlayer is unable to play certain m3u playlists. These are full audiobooks consisting of thousands of ten-second mp3 chunks. When I open these in the demo app,
it seems buffering takes a while, but then, when buffering stops, there is still no sound. No error message. Nothing.

### Reproduction steps
This is how I reproduce the faulty behaviour on my Ubuntu 17.04 laptop:
1 git clone a fresh copy of the demo app
2 Change the buildToolsVersion to 26.0.2 in constants.gradle (since I do not have version 25 installed)
3 change gradle version to gradle:3.0.0-rc1 in the outer build.gradle file (automatically done by AS)
4 Insert the following four lines in media.exolist.json, at line 345 (in the HLS section):
      {
        "name": "Fails to play mp3 audio only",
        "uri": "(URL here)"
      },
5 run the app, select the newly inserted HLS item

### Link to test content
(In the above "uri" field, replace the URL with one of those that I will send to the given email address.)

### Version of ExoPlayer being used
r2.5.3

### Device(s) and version(s) of Android being used
Samsung Galaxy S8 running android 7.0, «Samsung experience» version 8.1
This is not a once-in-a-while error, it happens every time.

**Comment by AquilesCanta** [comment]
The issue is that the files have .mp3 extension but are actually transport streams. The available options (aside from modifying the library code) are fixing the extension of the files in the server, or waiting until we push support for extractor injection (track #2748 for this, should happen relatively soon).

**Comment by hallyhaa** [comment]
So the stream would have come out right had the file extensions been .ts instead of .mp3?

**Comment by AquilesCanta** [comment]
That's correct. Give it a try. Extractor injection for HLS will be possible from the next push onwards.
