### ISSUE TITLE
Adding subtitle as string instead of url

### ISSUE THREAD

**Issue by b77x** [google/ExoPlayer#3372]
I have noticed that the examples only contains subtitle implementation using the url of the subtitle file. I need to be able to add subtitles as string. How do I do this?

**Comment by ojw28** [comment]
What does a subtitle as a string actually look like? There's not enough information in your description for us to help. Please clarify. Thanks.

**Comment by b77x** [comment]
For example, currently the subtitles are loaded with .srt url like this:
```
subtitleUri = Uri.parse("http://www.example.com/video.srt");

MediaSource videoSource = new ExtractorMediaSource(videoUri, dataSourceFactory, extractorsFactory, null, null);

Format subtitleFormat = Format.createTextSampleFormat(null, MimeTypes.APPLICATION_SUBRIP, Format.NO_VALUE, "en");

MediaSource subtitleSource = new SingleSampleMediaSource(subtitleUri, dataSourceFactory, subtitleFormat, C.TIME_UNSET);
```

I am looking to load the subtitle as string data instead of url, like this

```
    String subtitleString = "1\n" +
            "00:02:17,440 --> 00:02:20,375\n" +
            "Senator, we're making\n" +
            "our final approach into Coruscant.\n" +
            "\n" +
            "2\n" +
            "00:02:20,476 --> 00:02:22,501\n" +
            "Very good, Lieutenant.";
```

**Comment by ojw28** [comment]
Why would this use case ever arise? It seems pretty strange.

In any case, the way to do this would be to make the `dataSourceFactory` for just the `SingleSampleMediaSource`, that instantiates `ByteArrayDataSource` instances, which are initialized with `subtitleString.getBytes()`. You can pass whatever you like as `subtitleUri`.

**Comment by b77x** [comment]
In some cases the subtitle text is already fetched and no need to send another network request. Also it might be saved as a file locally.

I don't completely understand "that instantiates `ByteArrayDataSource` instances, which are initialized with `subtitleString.getBytes()`."

Here is what I tried so far:

```
DataSource.Factory dataSourceFactory2 = new DefaultDataSourceFactory(context,
              Util.getUserAgent(context, "yourApplicationName"), dbandwidthMeter);
MediaSource subtitleSource3 = new SingleSampleMediaSource(
             null, dataSourceFactory2, subtitleFormat, C.TIME_UNSET);

```

but with no success.

**Comment by ojw28** [comment]
* If it's saved as a file locally, you can just use the normal approach and pass a file URI (e.g. of the form `file:///path/to/subtitle/file.srt`. That should just work, although you may need to obtain an Android runtime permission to read the file, depending on where it's stored.
* If its actually a byte[] you need to implement your own `DataSourceFactory`, rather than using `DefaultDataSourceFactory`. You need to implement it to create `ByteArrayDataSource` instances. When you do that, you should pass `subtitleString.getBytes()` into the `ByteArrayDataSource` constructor.
