### ISSUE TITLE
Make CacheUtil documentation clearer w.r.t. task priority

### ISSUE THREAD

**Issue by DevGary** [google/ExoPlayer#3374]
CacheUtils and PriorityDataSource doesn't seem to ever call add(int priority) or remove(int priority) on PriorityTaskManager so PriorityTaskManager's highestPriority is never set so proceed(int priority) never proceeds.

**Comment by ojw28** [comment]
It's the responsibility of code calling into `CacheUtil` methods to add and remove the priority. You can see this pattern in, for example, `ProgressiveDownloader` in the `dev-v2` branch.

The reason this pattern makes sense is that the caller might want to cache N individual files as part of some larger operation. If we were to call add and remove inside `CacheUtil` that would create N-1 very brief priority changes when the priority is removed and then immediately re-added. If there are other tasks with a lower priority they'll end up being started and immediately stopped every time this happens, so it can create quite a lot of churn. If the caller is responsible, they can add the priority once, perform their N operations, then remove the priority when they're done. This is demonstrated in `SegmentDownloader` in the `dev-v2` branch.

I agree the documentation is unclear. We'll use this issue to track fixing that.

**Comment by DevGary** [comment]
Okay, thanks for the clarification.
