### ISSUE TITLE
Can not Seeking video local

### ISSUE THREAD

**Issue by minhphuong1894** [google/ExoPlayer#3376]
Hi
i got the issue like that : 
i play a video online with exo-player simple android on dev-v2 branch
i add samples with my link to video : 
 samples.add(new Sample("http://dto.tevolution.tv/dto-test/download.ism/download.ismv",
            "TEST DEVICE", MINE));
it's play perfect.
but
i wanna play video local.  i download video from "http://dto.tevolution.tv/dto-test/download.ism/download.ismv" and i run video offline.
but i can't seeking it ?
i try to another video file  simple.mp4 video, it's seeking ok
but my file download.ismv , it can seeking?
can you help me ? that's important with me . 
thanks so much

**Comment by anhpttps01988** [comment]
I also have the same error :raising_hand:

**Comment by ojw28** [comment]
There is no difference between streaming this sample and playing it offline. Seeking is unsupported in both cases.

Please see [this FAQ](https://google.github.io/ExoPlayer/faqs.html#why-are-some-media-files-not-seekable) for why. In this case the file is fragmented mp4. We expect it contain a `sidx` box to enable seeking, and it does not, hence seeking is not enabled.

**Comment by anhpttps01988** [comment]
Hi ojw28, This feature seeking is still supported when running online with video imsv. But  with running offline, it not working, I can't not understand

**Comment by ojw28** [comment]
I tried streaming the link provided in this issue, and it wasn't seekable.

**Comment by minhphuong1894** [comment]
hi ojw28
can you contact me with my email : minhphuong1894@gmail.com
i wanna send you some pictures about my problems. it's ok
thanks.
