### ISSUE TITLE
Official implementation of PlayerAdapter from Leanback Library

### ISSUE THREAD

**Issue by mkjensen** [google/ExoPlayer#3382]
I suggest adding an extension with an official ExoPlayer implementation of [PlayerAdapter](https://developer.android.com/reference/android/support/v17/leanback/media/PlayerAdapter.html) from [v17 Leanback Library](https://developer.android.com/topic/libraries/support-library/packages.html#v17-leanback) of [Support Library](https://developer.android.com/topic/libraries/support-library/index.html).

I did find two implementations in Google samples ([Leanback Support Library Showcase App for Android TV](https://github.com/googlesamples/leanback-showcase/blob/master/app/src/main/java/android/support/v17/leanback/supportleanbackshowcase/app/media/ExoPlayerAdapter.java) and [Android TV Leanback Support Library sample - Videos by Google](https://github.com/googlesamples/androidtv-Leanback/blob/master/app/src/main/java/com/google/android/exoplayer2/ext/leanback/LeanbackPlayerAdapter.java)) but they are different. I also tried to implement my own version but it seems to me that something like this should have an official implementation. I think it is easy to end up with an incomplete and/or incorrect implementation otherwise.

A pitfall that I have encountered when attempting an implementation is the values from [Player.getCurrentPosition()](https://github.com/google/ExoPlayer/blob/ab6f9aea5bbdf414993766308dd808ab660d956b/library/core/src/main/java/com/google/android/exoplayer2/Player.java#L356), [Player.getBufferedPosition()](https://github.com/google/ExoPlayer/blob/ab6f9aea5bbdf414993766308dd808ab660d956b/library/core/src/main/java/com/google/android/exoplayer2/Player.java#L362), and [Player.getDuration()](https://github.com/google/ExoPlayer/blob/ab6f9aea5bbdf414993766308dd808ab660d956b/library/core/src/main/java/com/google/android/exoplayer2/Player.java#L351) returning incorrect values when seeking. At least when seeking outside a buffered section of a video, I think. This potentially results in a weird user experience if the UI is updated with values that are not valid values in regard to the actual duration of a video.

I will be happy to provide a branch with the boilerplate code for a new extension if someone with the proper ExoPlayer experience would then do the actual implementation of [PlayerAdapter](https://developer.android.com/reference/android/support/v17/leanback/media/PlayerAdapter.html).

### Issue description
This is a feature request, see above.

### Reproduction steps
This is a feature request, see above.

### Link to test content
This is a feature request, see above.

### Version of ExoPlayer being used
r2.5.4

### Device(s) and version(s) of Android being used
- NVIDIA Shield TV (Android 7.0)
- Android TV Intel x86 Atom System Image (Android 8.0)

### A full bug report captured from the device
This is a feature request, see above.

**Comment by mkjensen** [comment]
I have created a branch, https://github.com/mkjensen/ExoPlayer/tree/playeradapter-extension,  with the boiler plate code for adding a ExoPlayer PlayerAdapter extension.

Specifically, have a look at the https://github.com/mkjensen/ExoPlayer/tree/playeradapter-extension/extensions/playeradapter folder. 

The commit that adds the boiler plate code: https://github.com/mkjensen/ExoPlayer/commit/9f4697fe6f927a4f375d44e1e436c9674a1a4ff0

**Comment by mkjensen** [comment]
I added a few more commits to the branch, making it even more clear what needs to be done. If someone wants to do the ExoPlayer work based on the branch I guess we can just squash the commits before doing a PR.

**Comment by ojw28** [comment]
We already have one: https://github.com/google/ExoPlayer/tree/dev-v2/extensions/leanback

**Comment by mkjensen** [comment]
I can't believe I missed that. Thanks.

**Comment by mkjensen** [comment]
Note that version 27 of the Support Library adds additional methods to implement: https://developer.android.com/sdk/support_api_diff/27.0.0/changes.html

**Comment by jboisjo** [comment]
Would be cool to have a live feature! Like right now it's fine when you know the duration of the video, but what if it's a livestream?
