### ISSUE TITLE
Simple rotation with simpleExoPlayerView.setRotation(90); causes black view  during playback

### ISSUE THREAD

**Issue by pawaom** [google/ExoPlayer#3385]
Simple rotation with simpleExoPlayerView.setRotation(90); causes black view  during playback

We are just trying to display the simpleExoPlayerView in a 90 degree rotation, how ever when we try to do so it causes 
black view  during playback

The same video work perfectly if simpleExoPlayerView is not rotated

how can we achieve this a simple rotation of a view

**Comment by ojw28** [comment]
I don't think you can rotate a `SurfaceView` in this way, which is what `SimpleExoPlayerView` uses by default as the video surface. You'll need to configure the view to use a `TextureView` instead. If you have a `SimpleExoPlayerView` in layout xml, you can do this with `app:surface_type="texture_view"`, where on the root view in the layout `xmlns:app="http://schemas.android.com/apk/res-auto"`
