### ISSUE TITLE
Is there a way to customize the scrubber/playhead canvas?

### ISSUE THREAD

**Issue by alexandreprado** [google/ExoPlayer#3387]
I noticed it has the controllers to change its size and color, but I have this project I'm working on, and it has this specific scrubber design:

![player_slider](https://user-images.githubusercontent.com/1447296/31885938-a5081dee-b7c8-11e7-8abd-53869251af6a.png)

Is there any way to achieve this?

Thanks in advance!

**Comment by andrewlewis** [comment]
Please follow #3337.
