### ISSUE TITLE
Exception when playing HLS stream

### ISSUE THREAD

**Issue by jinghao666** [google/ExoPlayer#3388]
Most of the time, there's no problem。 But some machines should error ：getSourceException=com.google.android.exoplayer2.h.u: java.io.FileNotFoundException: /data/data/myapp/cache/7ed8740be8710073700985dcc45b23a0.m3u8: open failed: ENOENT (No such file or directory) ，

**Comment by AquilesCanta** [comment]
Please fill the issue template items.

That error usually means there is a reference to a playlist in the local file system that is not there. That means either the media source is being prepared with a URI that points to a non-existent file, or the master playlist contains an invalid URI.

**Comment by ojw28** [comment]
Closing due to lack of information.
