### ISSUE TITLE
Faster seekto for exo player

### ISSUE THREAD

**Issue by anhmiuhv** [google/ExoPlayer#3389]
Hi,

I'm currently using ExoPlayer 2.5.4 for playing an offline resource. With my current implementation (which is the one on the guide website), the seekTo took about 500 - 1000 ms to update the frame. Is there any way I can config it to be faster? I'm running it on the pixel gen 1. I'm using a textureView as a renderer.

**Comment by ojw28** [comment]
The only way to make it faster is support seeking to nearest key-frame rather than to the exact frame. This is tracked by https://github.com/google/ExoPlayer/issues/2882.
