### ISSUE TITLE
With one link sometime can't play

### ISSUE THREAD

**Issue by mdtuyen** [google/ExoPlayer#3392]
I play one link m3u8 sometime it catch exception:
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.google.android.exoplayer2.source.hls.playlist.HlsPlaylistTracker$MediaPlaylistBundle.isSnapshotValid()' on a null object reference

I click retry after several and it continue play. 
That mean the link not error. 
Why the exception popup ?

**Comment by AquilesCanta** [comment]
Looks like a bug, but if we could have access to the stream, that'd be very useful. Would it be possible for you to send it to dev.exoplayer@gmail.com?

**Comment by mdtuyen** [comment]
hi, here is some link:
```
http://apps2.101vn.com/app/code/mytvapp.php?id=vstv036&token=NTku(*)TUzLjB-1(*)i40(*)g&st=(*)T[gv(*)j(Tv(*)j[gxNy[gy(*)ToxN(T&play.m3u8
http://apps2.101vn.com/app/code/mytvapp.php?id=vstv036&token=NTku(*)TUzLjB-1(*)i40(*)g&st=(*)T[gv(*)j(Tv(*)j[gxNy[gy(*)ToxO(T&play.m3u8
http://apps2.101vn.com/app/code/mytvapp.php?id=vstv036&token=NTku(*)TUzLjB-1(*)i40(*)g&st=(*)T[gv(*)j(Tv(*)j[gxNy[gy(*)ToxNg&play.m3u8
http://tv.101vn.com/ok/blog/code/fpt/live.php?app=apps&code=dG9rZW49TlRrdSgqKVRVekxqQi0xKCopaTQwKCopZyZzdD0oKilUW2d2KCopaihUdigqKWpbZ3hOeVtneSgqKVRveE4oVA==&kenh=hbo&play.m3u8
```

**Comment by mdtuyen** [comment]
I implement a mediaplayer use Exoplayer with function jum to next video in playlist if have an error. If video is playing I change it to another url the error occur.

**Comment by AquilesCanta** [comment]
Hello @mdtuyen, could you check the 4 streams/urls are working/correct? The first 3 return an empty response body with a 200 (which suggests the urls are correct, but the parentheses and wildcards suggest otherwise). The fourth link returns 200 as well, but an HTML page indicating a server error, instead of an HLS playlist.

**Comment by ojw28** [comment]
Closing due to lack of information.
