### ISSUE TITLE
Unable to stop segments download when live is paused and app in background 

### ISSUE THREAD

**Issue by davibe** [google/ExoPlayer#3394]
### Issue description

When I watch a live HLS video and pause the playback, the player stops downloading segments after a while, but it keeps polling the inner manifest. This can be desirable because it keeps duration information up-to-date.
When I stop the video and then play it again (calling `prepare()`) the main manifest is re-downloaded.

Here is my problem: I need to be able to avoid re-downloading the main manifest when going in background and then resuming the application. This is because the main manifest has token based entitlement protection and such token may expire. Inner manifest on the other hand is protected with a long session and it does not share the same timing problem under normal situations.

Because of this, when going in background:
- I can't use `stop()` because, as explained before, on resume I would have to trigger the download of the main manifest by calling `prepare()` again
- I can't use `pause()` because during background inner manifest polling would never stop (not desirable for the user)

Consider that I do not have control of the backend / video delivery / entitlement infrastructure.
Also, comparing to iOS, AVPlayer behaves like this (basically this is the expected behaviour):
- when paused it keeps downloading both segments and inner manifest
- when going in background it stops downloading everything
- when resuming from background it can resume playback without re-downloading the main manifest

What's the correct/suggested approach to achieve the same result with exoplayer ?

### Reproduction steps

The behaviour can be observed using the official exoplayer demo application and opening the test content

### Link to test content
I sent the link to the test content by email with the reference to this issue.

### Version of ExoPlayer being used
We are using `release-v2` branch at 1fdc11f2b30547392c6fe6d2485493837d8f41a2

### Device(s) and version(s) of Android being used
Any device will work, emulator included

**Comment by ojw28** [comment]
Relying on the player not re-downloading the master playlist for the service to work sounds extremely fragile. What would happen if iOS were updated to do this? Is there a documented guarantee anywhere that AVPlayer wont behave in this way?

Given there are entitlements involved, I'm guessing you must have some kind of relationship with whoever's managing the backend? If so then I'd suggest you talk to them and see what can be done on their side, because I think it's quite likely you'll run into trouble at some point in the future with the approach currently being pursued.

**Comment by AquilesCanta** [comment]
Is the main manifest the master playlist? If so, would it work injecting your own DataSource (see `HlsDataSourceFactory`) that caches the master playlist so that it is downloaded only once, the first time?

**Comment by ojw28** [comment]
I don't really see this as a player issue, so closing.

**Comment by davibe** [comment]
thx for the suggestions.
