### ISSUE TITLE
Playback control buttons click event not firing

### ISSUE THREAD

**Issue by Habush** [google/ExoPlayer#3397]
### Issue description
I have created a `SimpleExoPlayer` and added an `EventListener` to listen when the user clicks the control buttons (Play/Pause, Next, Previous). Here is the  `onPlayerStateChanged` method I have overrided
```
@Override
    public void onPlayerStateChanged(boolean playWhenReady, int playbackState) {
            if(playbackState == PlaybackStateCompat.STATE_PAUSED){
                Log.d(TAG, "Pause clicked");
            }

            if(playbackState == PlaybackStateCompat.STATE_SKIPPING_TO_NEXT){
                Log.d(TAG, "Next clicked");
            }

            if(playbackState == PlaybackStateCompat.STATE_SKIPPING_TO_PREVIOUS){
                Log.d(TAG, "Previous clicked");
            }
    }
```
Now, when I click **Pause**, it is logged `Log.d(TAG, "Pause clicked")`. However, clicking **Previous** and ***Next** buttons doesn't do anything, i.e no log is written.
I have made sure that I have added listener to the player like this: `player.addListener(this);`
 ### Reproduction steps
Create an Activity that uses `SimpleExoPlayer` to play videos. Implement the `Player.EventListener` interface by the Activity and override the `onPlayerStateChanged` method.

### Link to test content
No media to link to.

### Version of ExoPlayer being used
**v2.5.2**

### Device(s) and version(s) of Android being used
**Device** : Android TV Emulator
**Android Version** : 7.0
**SdkVersion** : 25

### A full bug report captured from the device
There is no error report being output.

**Comment by andrewlewis** [comment]
The `playbackState` parameter is an ExoPlayer state, taking one of the `STATE_` values in [Player.java](https://github.com/google/ExoPlayer/blob/9bb8b24/library/core/src/main/java/com/google/android/exoplayer2/Player.java#L130), and has nothing to do with `PlaybackStateCompat` or media sessions.

There may be better ways depending on what you're trying to do, but one way to intercept these events is to pass your own `ControlDispatcher` implementation to `PlaybackControlView.setControlDispatcher`.

**Comment by AquilesCanta** [comment]
My tiny contribution: pausing the player does not change its `playbackState`, but rather its `playWhenReady` state.

**Comment by Habush** [comment]
@andrewlewis  Can you please give a little example on how to implement custom `PlaybackControlView` to  intercept the events? Thanks.

**Comment by andrewlewis** [comment]
I'm not sure a custom `PlaybackControlView` is the easiest way to do this. Can you just use `SimpleExoPlayerView.setControlDispatcher` (which calls through to `PlaybackControlView.setControlDispatcher`) and pass in your own implementation that adds additional handling for seeks and pause/resume?

**Comment by Habush** [comment]
Thanks for the reply!
I am actually looking to get  how long a user have watched a video when s/he presses next/previous button. I started using `onPositionDiscontinuity` to get the next/previous event and tried to get the current video position using `player.getCurrentPosition()`. However, that returns zero because it gets the position of the newly loaded video. So, in short, how can I get the current position of a video when I user presses next/previous button?
