### ISSUE TITLE
ConcatenatingMediaSource position.

### ISSUE THREAD

**Issue by erikasbulev** [google/ExoPlayer#3399]
Lets say I have 3 videos. Videos are provided via ConcatenatingMediaSource. 
Video1(10s) -> Video2(5s) - Video3(5s). 

when I call SimpleExoPlayer.getCurrentPosition(); I get the position of current video that is in progress. 

The total of my view show time should be 20s. Since three video durations add up to 20 seconds. 

When android device rotates I must handle the state. In order to re-continue to show the video from the position from which the device rotation was made, I need to save the current position of a player. The problem is that player returns the position of Media source within of ConcatenatingMediaSource. Let's say that device was rotated at Video2 2.5 second. When i call get current position I get 2500ms. However the video1 was passed. I would like to get 12500ms since the video1 was shown. Searched the Issues, haven't found anything specific. Any workaround?

**Comment by erikasbulev** [comment]
My apologies, should have read the documentation in more detail. You use get window index.

**Comment by rranjithkumar100** [comment]
@erikasbulev can you give your answer. I am also face same issue. Thanks

**Comment by erikasbulev** [comment]
@rranjithkumar100  you use player.getCurrentWindowIndex() which tells you which video is being shown (int) and then player.getCurrentPosition()(long) which tells you what position that video is right now.

so if you save state on video2 6th second you get windwo index = 1 and pisition 6000. And then on restore state you tell player which window you were player.seekTo(windowIndex, position);
