### ISSUE TITLE
Distorted video on specific resolution on Allwinner based device

### ISSUE THREAD

**Issue by akurni** [google/ExoPlayer#3401]
### Issue description
When we played the test content, the video will be rendered incorrectly. The content seems to be distorted. We tried to use another video with the same resolution and the same thing happened. When we tried using the original VideoView the video seems to be rendered fine.
The device uses OMX.allwinner.video.decoder.avc

> <check_lib_unload:394>:  Unloading the dynamic library for OMX.allwinner.video.decoder.avc
> 10-27 19:11:53.622 10615-11820/id.lumio.videoplayer I/OMXClient: Using client-side OMX mux.

Player source code:
https://github.com/akurni/Exoplayer-Demo-App.git

### Reproduction steps
We tried the same video with different resolution.

0.5x scale of the original ->  NORMAL
1.2x scale of the original -> NORMAL
Different videos with the same resolution of the test content -> CORRUPTED
We also tried to change the resolution to the nearest modulo 8 and 16 -> CORRUPTED

Expected Result (NORMAL):
![device-2017-10-27-191309](https://user-images.githubusercontent.com/1082715/32103501-e6370c28-bb4a-11e7-9636-200dc5f8c4f5.png)

Result (CORRUPTED):
![device-2017-10-27-190202](https://user-images.githubusercontent.com/1082715/32103518-f6cffa9a-bb4a-11e7-89c4-203b7c735b10.png)

### Link to test content
https://www.dropbox.com/s/xfsvc1rp45qf3z2/Marutama%20Ramen%20PIK%20ok%202500X1780.mp4?dl=0

### Version of ExoPlayer being used
r2.5.4

### Device(s) and version(s) of Android being used
Orange Pi PC -> 4.4.2

### A full bug report captured from the device
[bugreport.txt](https://github.com/google/ExoPlayer/files/1421998/bugreport.txt)

**Comment by akurni** [comment]
Somewhat the video looks normal with LargeHeap settings set to true.

**Comment by ojw28** [comment]
This is a platform issue that would need to be reported to (and resolved by) the device manufacturer. Closing as obsolete.
