### ISSUE TITLE
Multiple ClippingMediaSource not working for m3u8 files 

### ISSUE THREAD

**Issue by rranjithkumar100** [google/ExoPlayer#3405]
# Issue 
**When I use two or more ClippingMediaSource not working for m3u8. But working same code for MP4**

### Reproduction steps

**Bug : When I use Multiple ClippingMediaSource for m3u8 files not working**

But working in following cases

1. Only one ClippingMediaSource with m3u8 - working
2. Multiple ClippingMediaSource with mp4 - working 

        MediaSource movieMediaSource =getMediaSourceFromUrl(context, mLiveURL);
            final long oneMinute = 60000000L;
            ClippingMediaSource videoSource1 = new ClippingMediaSource(movieMediaSource, 0, oneMinute/2);

            ClippingMediaSource videoSource2 = new ClippingMediaSource(movieMediaSource, oneMinute/2, oneMinute);
  
            ConcatenatingMediaSource concatenatingMediaSource = new ConcatenatingMediaSource(videoSource1,videoSource2);

       public static MediaSource getMediaSourceFromUrl(Context context, String url) {
        mBandwidthMeter = new DefaultBandwidthMeter();
       //Produces DataSource instances through which media data is loaded.
        DefaultDataSourceFactory dataSourceFactory = new DefaultDataSourceFactory(context, 
        Util.getUserAgent(context, "MOD"), mBandwidthMeter);
       //Produces Extractor instances for parsing the media data.
        ExtractorsFactory extractorsFactory = new DefaultExtractorsFactory();
        MediaSource videoSource = null;
        if (url != null && !url.isEmpty()) {
            Log.d(TAG, "getMediaSourceFromUrl: 11");
            if (url.contains(".m3u8")) {
          //FOR LIVESTREAM LINK:
                Uri mp4VideoUri = Uri.parse(url);
                videoSource = new HlsMediaSource(mp4VideoUri, dataSourceFactory, null, null);
        
            } else if (url.contains(".mp4")) {
         //FOR SD CARD SOURCE:
                Uri mp4VideoUri = Uri.parse(url);
                videoSource = new ExtractorMediaSource(mp4VideoUri, dataSourceFactory, extractorsFactory, null, null);
              }
           }
            return videoSource;
        }

### Version of ExoPlayer being used
2.5.4

### Device(s) and version(s) of Android being used
Android 5.1 & Android 7.0

### A full bug report captured from the device

Lenova A6000+  & Nexus 6

### Error Log

> Internal runtime error.
                                                                    java.lang.IllegalStateException at com.google.android.exoplayer2.util.Assertions.checkState(Assertions.java:79) at com.ajax.mod.controller.player.MyHlsMediaSource.prepareSource(MyHlsMediaSource.java:97)  at com.google.android.exoplayer2.source.ClippingMediaSource.prepareSource(ClippingMediaSource.java:89) at com.google.android.exoplayer2.source.ConcatenatingMediaSource.prepareSource(ConcatenatingMediaSource.java:78) at com.google.android.exoplayer2.ExoPlayerImplInternal.prepareInternal(ExoPlayerImplInternal.java:425)  at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:328) at android.os.Handler.dispatchMessage(Handler.java:98)
at android.os.Looper.loop(Looper.java:154)
at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by tonihei** [comment]
The problem is that you can't re-use MediaSources. That means you need to create a new movieMediaSource for each ClippingMediaSource.

**Comment by rranjithkumar100** [comment]
Yes you are right.. @tonihei 

Problem solved. I close this issue 👍
