### ISSUE TITLE
SeekTo throws IndexOutOfRange after adding item to DynamicConcatenatingMediaSource.

### ISSUE THREAD

**Issue by ourdex86** [google/ExoPlayer#3407]
I am trying to use DynamicConcatenatingMediaSource to create dynamic playlists.

Here is the implementation.

```
public void initMusicPlayer(){

        if (songs !=null)
        {

            MediaSource mediaSource;
            ArrayList<MediaSource> sources = new ArrayList<>();

            MusicItem song;
            for (int i=0;i< songs.size();i++)
            {
                song = songs.get(i);
                mediaSource = buildMediaSource(Uri.parse(song.getMusicUrl()));
                sources.add(mediaSource);
            }

            dynamicMediaSource = new DynamicConcatenatingMediaSource();
            dynamicMediaSource.addMediaSources(sources);
            exoPlayer.prepare(dynamicMediaSource,false,false);

            exoPlayer.addListener(this);
            if (currentPlayingSongIndex == -1)
            {
                exoPlayer.setPlayWhenReady(false);
            }
            else
            {
                exoPlayer.seekTo(currentPlayingSongIndex,0);
                exoPlayer.setPlayWhenReady(true);
            }
        }
    }

public void addItemToPlaylist(MusicItem song,boolean shouldPlay){

        long position = exoPlayer.getContentPosition();
        MediaSource mediaSource = buildMediaSource(Uri.parse(song.getMusicUrl()));
        dynamicMediaSource.addMediaSource(mediaSource);
        exoPlayer.prepare(dynamicMediaSource,false,false);

        if (shouldPlay)
        {
            exoPlayer.seekTo(currentPlayingSongIndex,0);
        }
        else
        {
            exoPlayer.seekTo(currentPlayingSongIndex,position);
        }
    }
```
But, the audio is not played. Its  immediately invoking `onPlayerStateChanged` with player state `STATE_ENDED`

**Exoplayer Version :  r2.5.4
Android OS Version : 7.1.2
Device : Pixel XL**

**Comment by tonihei** [comment]
When the player immediately changes to STATE_ENDED, it usually means that your media files can't be loaded or played. Have you checked whether you can play your files with ExoPlayer directly (without using DynamicConcatenatingPlaylist)? Also, please check if you receive an error on Player.EventListener.onPlayerError().

In addition, please note that you only need to call player.prepare(mediaSource) once. It seems like you re-prepare the player in addItemToPlaylist. This is not necessary, just add the new playlist item to the dynamic concatenating media source.

**Comment by ourdex86** [comment]
I tried using *ConcatenatingMediaSource. *That is working fine but I cannot
use that because my playlist is dynamic(I should be able to add & remove
items to the playlist).

Also, I even if I call the *player.prepare *only once, still its not
playing.

Finally, *onPlayerError *is not called.

**Comment by tonihei** [comment]
Could you try to remove the seekTo operations? A transition to STATE_ENDED might also be caused by a seek to an invalid position.

**Comment by ourdex86** [comment]
But, if I remove the *seekTo* operation, then how can I play a particular
song in the playlist ?

**Comment by tonihei** [comment]
I'm just trying to find the reason for the problem you have. You're right that you should be able to call seekTo to play a particular song in the playlist. So, does it help to remove the seekTo operations? That is, your content plays without going to STATE_ENDED?

**Comment by Tolriq** [comment]
Seeks needs to happens after STATE_READY and not just after the prepare got caught by this one once :)

And you should not call prepare after adding songs to the playlist if the playlist was already prepared.

Init should call exoPlayer.prepare(dynamicMediaSource , true,true); to start clean then nothing more is needed.

**Comment by tonihei** [comment]
Not sure if I understand you correctly - does that mean you solved your problem now? Particularly by not calling prepare again?

**Comment by Tolriq** [comment]
I'm not the OP, I just give possible solutions to the issue from code posted and personal experience since I'm playing with DynamicConcatenatingMediaSource right now.

**Comment by tonihei** [comment]
Oh, sorry :) Didn't even notice. Thanks for the advice then. 

One small correction: seeks can happen at any time after calling prepare, there should be no need to wait for STATE_READY.

The rest is correct and as already described - prepare should only be called once preferably with the (source, true, true) parameters. Not resetting the state in prepare is usually only used when re-preparing after an error.

**Comment by Tolriq** [comment]
@tonihei don't want to hijack the thread, but in 2.5.4 even with a simple MediaSource, calling prepare then seek then playwhenready does not seek at all.

Only working solution, is prepare without playwhenready, wait for STATE_READY then seek then playwhenready(true)

**Comment by tonihei** [comment]
@Tolriq Preparing a media source and immediately seeking works fine for me. If you feel there's an issue, it would be great if you can open a new GitHub issue with reproduction steps.

@ourdex86 Did disabling the seeks prevent the player from switching to STATE_ENDED immediately?

**Comment by ourdex86** [comment]
@tonihei & @Tolriq .

Actually you both gave valid points.
I did the following & now everything works.

```
public void initMusicPlayer() {
        if (songs !=null)
        {
            long currentDuration = -1;
            if (isPlaying() && exoPlayer.getCurrentWindowIndex() == currentPlayingSongIndex)
            {
                currentDuration = exoPlayer.getCurrentPosition();
            }
            MediaSource mediaSource;
            ArrayList<MediaSource> sources = new ArrayList<>();
            MusicItem song;
            for (int i=0;i< songs.size();i++)
            {
                song = songs.get(i);
                mediaSource = buildMediaSource(Uri.parse(song.getMusicUrl()));
                sources.add(mediaSource);
            }
            dynamicMediaSource = new DynamicConcatenatingMediaSource();
            dynamicMediaSource.addMediaSources(sources);
            exoPlayer.addListener(this);
            exoPlayer.prepare(dynamicMediaSource,true,true);
            if (currentPlayingSongIndex == -1)
            {
                exoPlayer.setPlayWhenReady(false);
            }
            else
            {
                if (currentDuration != -1)
                {
                    exoPlayer.seekTo(currentPlayingSongIndex,currentDuration);
                }
                else
                {
                    exoPlayer.seekTo(currentPlayingSongIndex,0);
                }
                exoPlayer.setPlayWhenReady(true);
                sendBroadcast(new Intent("PLAY"));
                showNotification();
            }
        }
    }

public void addItemToPlaylist(MusicItem song,boolean shouldPlay)
    {
        songs = SingleTon.sharedInstance().getMusicItemsList();
        if (dynamicMediaSource!=null)
        {
            MediaSource mediaSource = buildMediaSource(Uri.parse(song.getMusicUrl()));
            dynamicMediaSource.addMediaSource(mediaSource);
            if (shouldPlay)
            {
                Handler handler = new Handler();
                handler.postDelayed(new Runnable() {
                    @Override
                    public void run() {
                        exoPlayer.seekTo(currentPlayingSongIndex,0);
                    }
                },500);
            }
        }
        else
        {
            initMusicPlayer();
        }
    }
```

But, I have to use a delay of 500 millis to play an item that was added to the playlist or else its getting crashed.

**Comment by Tolriq** [comment]
@tonihei I have also noticed that seekTo can crash but Javadoc does not says it can throw and the func is not marked a throwing.

@ourdex86 it's hard to know when you call addItemToPlaylist with just this extract :) You may want to provide full crash logs and more details to get more help.

**Comment by ourdex86** [comment]
@Tolriq 

Lets say I am playing a media source at index 1 & then while its being played if I add another item to the `DynamicMediaSource`  & if I try to play the same added media source immediately after adding  
 then I am getting this "IndexOutOfRange" exception at `DynamicMediaSource`. 

But, after adding it to the `DynamicMediaSource` & if I give a delay of 500 ms & then if I play the recently added media source then its working fine.

I hope you got it

**Comment by tonihei** [comment]
@Tolriq  player.seekTo is not supposed to throw. We noticed that there's a bug which may throw under certain circumstances after seeking (#3362). We're currently fixing this.

@ourdex86  Judging from your code, it seems that it was the seekTo that was throwing, right? As I said above, seeking to the item you just added should be supported and there should be no need for you to to delay this operation. The question is whether you are having a problem because of the issue we're currently fixing anyway (#3362) or whether your problem is something else and related to the DynamicConcatenatingMediaSource.

Could you please post a complete stack trace of your error or attach a bug report for us to investigate this further? Thanks!

**Comment by tonihei** [comment]
I was able to reproduce your issue myself. It's kind of related to the ongoing refactoring of the seek handling, so it's hopefully going to be fixed soon.

**Comment by tonihei** [comment]
We will push a fix to the dev branch soon which will allow you to pass in a custom Runnable to any of the DynamicConcatenatingMediaSource methods. These Runnables will be executed immediately after the player was made aware of the change. This removes the need for your workaround and also the timing of 500ms. The resulting code for your example would look like this:

```
dynamicMediaSource.addMediaSource(mediaSource, new Runnable() {
  @Override
  public void run() {
    exoPlayer.seekTo(newSongIndex, 0);
  }
});
```

**Comment by Tolriq** [comment]
@tonihei Just to confirm as 2.6.0 is already branched this means that this will go in for the release after?

**Comment by ojw28** [comment]
It will be cherry-picked into 2.6.0, I think.
