### ISSUE TITLE
shuffle in exoplayer

### ISSUE THREAD

**Issue by sn32247** [google/ExoPlayer#3408]
is function that support shuffle in exoplayer ?
 when shuffle is on and i clicking next button, play random music .

**Comment by somayenoori1987** [comment]
is function that support shuffle in exoplayer ?
 when shuffle is on and i clicking next button, play random music .

**Comment by tonihei** [comment]
There will be shuffle mode support in the next release. 
You can already use it when you check out the dev-branch. Just enable shuffling with [player.setShuffleModeEnabled(true)](https://github.com/google/ExoPlayer/blob/d02e1df4b42edaaaae171c0677730bec677fdc58/library/core/src/main/java/com/google/android/exoplayer2/Player.java#L321)

**Comment by Tolriq** [comment]
@tonihei  Just found that this is the last missing piece for DynamicConcatenatingMediaSource :(

Do you know if ETA for next stable version is more weeks than days? Just to know if I should disable the function for now or wait.

**Comment by tonihei** [comment]
There is no fixed date yet, but most likely in 2-3 weeks.
