### ISSUE TITLE
Implementing abandonment rule in ExoPlayer

### ISSUE THREAD

**Issue by kanthicn1** [google/ExoPlayer#3412]
I am trying to implement equivalent of "AbandonRequestsRule" (as the feature is called in dash.js player) in ExoPlayer. The aim is to keep tracking bandwidth measurements intermittently during a segment download and to abandon download at current quality, based on these intermediate bandwidth measurements. 
I am planning to implement this logic for HLS in hlsSampleStreamWrapper by the way of restarting the same chunk download but at a lower quality from onLoadCanceled method.

I noticed that if I "cancel" a current load mid-way in HlsMediaChunk by calling "closeQuitely", the event generated is still onLoadCompleted. The player just skips playing the un-downloaded parts of the segment and the Loader moves on to loading the next segment. Isn't the expected behavior supposed to be trying to re-download the current segment because it was "canceled"? Any pointers on how I can force such a behavior?

Since I am new to the code, I will appreciate any pointers.

**Comment by ojw28** [comment]
We do not support this currently, I'm afraid.
