### ISSUE TITLE
How can I send cookies?

### ISSUE THREAD

**Issue by oingbong** [google/ExoPlayer#3413]
Hello, team.
My English is not good enough. hope you understand.
I saw that https://github.com/google/ExoPlayer/issues/3045

I also need to send a cookie from the Exoplayer.

However my code is not working.
So i want that how you sent the the cookies.

What should I use?
1. java.net.CookieManager
2. com.google.android.exoplayer2.upstream.DefaultHttpDataSource

Below is my source code.

Case of java.net.CookieManager

     Map<String, List<String>> header = new HashMap<>();
     List<String> value = new ArrayList<>();
     value.add("domain={domainName};name={CookieName};value="+cookieValue1+";");
     header.put("Set-Cookie",value);
     URI u1 = URI.create("{domainName}");

     Map<String, List<String>> header2 = new HashMap<>();
     List<String> value2 = new ArrayList<>();
     value.add("domain={domainName};name={CookieName};value="+cookieValue2+";");
     header2.put("Set-Cookie",value2);

     Map<String, List<String>> header3 = new HashMap<>();
     List<String> value3 = new ArrayList<>();
     value.add("domain={domainName};name={CookieName};value="+cookieValue3+";");
     header3.put("Set-Cookie",value3);

     try {
         DEFAULT_COOKIE_MANAGER.put(u1, header);
          } catch (IOException e) {
         e.printStackTrace();
     }
     try {
         DEFAULT_COOKIE_MANAGER.put(u1, header2);
          } catch (IOException e) {
         e.printStackTrace();
     }
     try {
         DEFAULT_COOKIE_MANAGER.put(u1, header3);
          } catch (IOException e) {
         e.printStackTrace();
     }

     CookieHandler.setDefault(DEFAULT_COOKIE_MANAGER);

------------------------------------------------------------------------

Case of com.google.android.exoplayer2.upstream.DefaultHttpDataSource

            DefaultHttpDataSource defaultHttpDataSource = new DefaultHttpDataSource(userAgent, null, null);
                      defaultHttpDataSource.setRequestProperty("Cookie", "{cookie_name1}=" + keyPair + ";domain={domainName}");
                      defaultHttpDataSource.setRequestProperty("Cookie", "{cookie_name2}=" + keyPair + ";domain={domainName}");
                      defaultHttpDataSource.setRequestProperty("Cookie", "{cookie_name3}=" + keyPair + ";domain={domainName}");
            
            DefaultHttpDataSourceFactory httpDataSourceFactory = new DefaultHttpDataSourceFactory(userAgent, null, defaultHttpDataSource.DEFAULT_CONNECT_TIMEOUT_MILLIS, defaultHttpDataSource.DEFAULT_READ_TIMEOUT_MILLIS, true);
            DefaultDataSourceFactory dataSourceFactory = new DefaultDataSourceFactory(VideoActivity.this, null, httpDataSourceFactory);
            httpDataSourceFactory.createDataSource();

            Uri daUri = Uri.parse(streamUrl);
            mVideoSource = new HlsMediaSource(daUri, dataSourceFactory, 1, null, null);

**Comment by ojw28** [comment]
I don't understand the code snippet. In particular you create `defaultHttpDataSource` but never use it. The call to `httpDataSourceFactory.createDataSource();` is also not doing anything. You should probably get rid of those pieces of code, and set the properties on `httpDataSourceFactory` instead using `httpDataSourceFactory.setDefaultRequestProperty("x", "y");`.

**Comment by oingbong** [comment]
Thank you very much for helping me.
It working in the way you have told me.
I using **httpDataSourceFactory.setDefaultRequestProperty** Method.
God bless you.

**Comment by deepaksime** [comment]
@oingbong  can post the working code sample for hls media player using exomedia
