### ISSUE TITLE
Playing previously selected video profile, not (Default) Auto

### ISSUE THREAD

**Issue by kush83** [google/ExoPlayer#3416]
Hi Everyone,
I am stuck with an issue. While playing a video with exo player V2.4, it  automatically pick up last selected video profile, but i am expected default profile every time. Can any one please help me out for the same.Please...

**Comment by ojw28** [comment]
Without any proper reproduction steps, and a clearer description, there's no much we can do to help here.

**Comment by AquilesCanta** [comment]
You are possibly reusing the BandwidthMeter? Ignore if not.

**Comment by kush83** [comment]
Thanks everyone for your support. I have resolved this issue.
