### ISSUE TITLE
ExoPlayerImplInternal: Internal runtime error

### ISSUE THREAD

**Issue by slezadav** [google/ExoPlayer#3417]
### Issue description
Video gets stuck after playing for a while (approx. 12s). Sometimes it recovers and continues but sometimes freezes completely.

### Reproduction steps
Just play the video on a specific device, it may happen after a while. The strange thing is it seems to happen only when connected to certain wifi. When we connected to another one we were unable to reproduce the problem.(Or more probably something else happened at the same time, because I cannot imagine any way wifi connection could cause this.)

### Link to test content
https://v52-a.sdn.szn.cz/~SEC1~expire-1509710888~scope-video:spli~GYnRsPVZumT/v_52/vmd_59fadf8d405f7e03c6fdfcfb/1509616898?fl=mdk,d2ff3899|hls2,3,VOD,0

### Version of ExoPlayer being used
r2.5.4

### Device(s) and version(s) of Android being used
Only device we have been able to reproduce the bug with:
HUAWEI P10 lite  WAS-LX1
Android 7
Emui 5.1
kernel 4.1.18

Users reported the problem also on Huawei p8 lite

### A full bug report captured from the device
StackTrace:
[simple stack trace.txt](https://github.com/google/ExoPlayer/files/1437612/simple.stack.trace.txt)

Full bug report :
 [bugreport.txt](https://github.com/google/ExoPlayer/files/1437603/bugreport.txt)

**Comment by ojw28** [comment]
Closing as part of a scrub of device specific issues that were filed more than 2 years ago.
