### ISSUE TITLE
While playing an HLS track, it buffers the segments  "on-demand", and not the full track.

### ISSUE THREAD

**Issue by jjvargas** [google/ExoPlayer#342]
I would like to know some hints on how this can be modified (what areas in the code) as I have implemented cache support with a modified version of the CacheDataSource/Sink, so every time it loads a segment, this is being written on disk. So ideally all it would be good to load all the segments so the entire track is cached from the beginning and only the memory buffer works on demand. 

A Use Case might be when connected to a mobile network and moving, so the connection is variable - buffering ahead to the end of the track would make playback more tolerant of lost signal (tunnels, etc)

**Comment by ojw28** [comment]
There are pros and cons of doing this (obviously). I don't think it's appropriate to have this as default behavior, but there are cases where it would be helpful. We'll keep this in mind during future development, but there are no near term plans to support this mode.

**Comment by Arqu** [comment]
Anything new on this? I'm actually looking into this as it would allow us to do quite a few things more than just adjusting for bumps in the network through put.
https://github.com/google/ExoPlayer/issues/531

**Comment by niceteg** [comment]
Greetings! 
Look what I've found on the web, this  is something new I guess, you'll be  excited. More info here <http://prykirolu.granitefoundation.org/lnvilho>

See you around, teg

**Comment by niceteg** [comment]
Greetings, 

I've just found  some new methods to  solve the  problem  you're facing, read more here <http://sluzustishe.synchronizedswimmersnewyork.com/lndfrhs>


See you around, teg

**Comment by ravin353** [comment]
Hi, Can i get this functionality in the current release?

**Comment by niceteg** [comment]
I've read an interesting article recently, and I thought it  might be useful for you <http://natascia.jessicathomasyoga.com/lnln/020>

Warmest regards, teg

**Comment by masmil1988** [comment]
Is this an issue? Or there is some way to change this behaviour?

**Comment by ojw28** [comment]
It's an enhancement, which is why it's marked as such. We do not have any updates on if or when we'll support this yet, sorry.

**Comment by erdemguven** [comment]
DownloadManager can be used to download whole track to cache. There are some issues with downloading and playing the same content at the same time, like the downloaded data won't be available immediately for playback. Not ideal but I don't think there will be any better solution soon.
