### ISSUE TITLE
How to Add Multiple Subtitles and Switch them Accordingly

### ISSUE THREAD

**Issue by rburade21** [google/ExoPlayer#3421]
I wanted to SideLoad Multiple Subtitles Files int player,
I should be able to switch between these subtitle.
please fort sample code for it in your demo app

I am Working Exoplyer 2.4

Please reply soon i have been waiting for it from long time
Thanks In Advance

**Comment by ojw28** [comment]
This is already explained in the ExoPlayer [developer guide](https://google.github.io/ExoPlayer/guide.html#side-loading-a-subtitle-file). You just need to create more than one subtitle source and merge all of them together.

**Comment by rburade21** [comment]
Yes But how to Switch Between Diffrent Subtitle files while playing video,without preparing player again causing video buffering.please post sample code for it

**Comment by ojw28** [comment]
The ExoPlayer demo app shows how to switch between the different tracks, so if you're unable to switch at all you should take a look at that as a starting point.
