### ISSUE TITLE
AAC Error event not reflected in listeners

### ISSUE THREAD

**Issue by pantos27** [google/ExoPlayer#3427]
Got this line in logcat
SoftAAC2: AAC decoder returned error 16386, substituting silence

But for some reason either of these events were fired
```
ExtractorMediaSource.EventListener.onLoadError
Player.EventListener.onPlayerError

```
Is there another listener I should be listening to?

**Comment by ojw28** [comment]
That warning is logged from platform code. I don't think ExoPlayer is informed by the platform when it happens, so has no way to propagate it to the application.
