### ISSUE TITLE
Is there a way to play *.flv (flash) videos?

### ISSUE THREAD

**Issue by krok55** [google/ExoPlayer#343]
I've tried with default renderer and got this error:

03-07 20:49:09.075: E/ExoPlayerImplInternal(22661): Internal track renderer error.
03-07 20:49:09.075: E/ExoPlayerImplInternal(22661): com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: [-49999], MediaFormat(video/vp6, -1, 320, 240, -1.0, -1, -1, -1, -1, -1)
03-07 20:49:09.075: E/ExoPlayerImplInternal(22661): 	at com.google.android.exoplayer.MediaCodecTrackRenderer.notifyAndThrowDecoderInitError(MediaCodecTrackRenderer.java:335)
03-07 20:49:09.075: E/ExoPlayerImplInternal(22661): 	at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:309)
03-07 20:49:09.075: E/ExoPlayerImplInternal(22661): 	at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:660)
03-07 20:49:09.075: E/ExoPlayerImplInternal(22661): 	at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:369)
03-07 20:49:09.075: E/ExoPlayerImplInternal(22661): 	at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:462)
03-07 20:49:09.075: E/ExoPlayerImplInternal(22661): 	at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:442)
03-07 20:49:09.075: E/ExoPlayerImplInternal(22661): 	at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:401)
03-07 20:49:09.075: E/ExoPlayerImplInternal(22661): 	at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:203)
03-07 20:49:09.075: E/ExoPlayerImplInternal(22661): 	at android.os.Handler.dispatchMessage(Handler.java:95)
03-07 20:49:09.075: E/ExoPlayerImplInternal(22661): 	at android.os.Looper.loop(Looper.java:137)
03-07 20:49:09.075: E/ExoPlayerImplInternal(22661): 	at android.os.HandlerThread.run(HandlerThread.java:60)
03-07 20:49:09.075: E/ExoPlayerImplInternal(22661): 	at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
03-07 20:49:09.075: E/ExoPlayerImplInternal(22661): Caused by: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: [-49999], MediaFormat(video/vp6, -1, 320, 240, -1.0, -1, -1, -1, -1, -1)
03-07 20:49:09.075: E/ExoPlayerImplInternal(22661): 	at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:310)
03-07 20:49:09.075: E/ExoPlayerImplInternal(22661): 	... 10 more

Thanks!

**Comment by ojw28** [comment]
Flash videos are not supported.

**Comment by Sabinmon** [comment]
hi,
Can u tell tell me how to play flash videos in exoplayer.
