### ISSUE TITLE
Is it Possible to show only a part of video not the whole video in explayer

### ISSUE THREAD

**Issue by pawaom** [google/ExoPlayer#3432]
Is it Possible to show only a part of video not the whole video in explayer

I have a video of width 960 and height 540 ratio

I want to show that part staring from left -300 to right 550
and from tom 250-bottom 400

can this be done with exoplayer, I dont want to change aspect ratio, but only display that portion of video that I wish to show

**Comment by ojw28** [comment]
If you output to a `TextureView` then you can crop the video how you like with [setTransform](https://developer.android.com/reference/android/view/TextureView.html#setTransform(android.graphics.Matrix)).
