### ISSUE TITLE
How to store Dash video in phone storage, while video is streaming in exo player, like youtube app does? Please provide code for the same.

### ISSUE THREAD

**Issue by dhanashreeborkar** [google/ExoPlayer#3433]
(no description supplied)

**Comment by ojw28** [comment]
This is tracked by https://github.com/google/ExoPlayer/issues/2643. Updates will be posted there when available.

**Comment by dhanashreeborkar** [comment]
Please provide way to download dash video and play Dash video in offline mode(no internet).
