### ISSUE TITLE
How to get cue points / ad breakers for Google IMA ?

### ISSUE THREAD

**Issue by harneev** [google/ExoPlayer#3437]
I want to create a custom seekbar with ad breakers.
Can i do it with Exoplayer r2.5.4 with IMA extension ?
As i dont have access to AdsManager so i cannot get CuePoints. Can i solve this problem with latest version ?

**Comment by andrewlewis** [comment]
For accessing the `AdsManager`, please see  https://github.com/google/ExoPlayer/issues/3322#issuecomment-334759034.

Alternatively, if you're using ExoPlayer's UI library you could investigate using `DefaultTimeBar` with customization via its attributes, or, if you need more control, make your own implementation of `TimeBar`. `PlaybackControlView` passes ad break times to `TimeBar.setAdBreakTimesMs`.
