### ISSUE TITLE
Forced Reboot when failing to play DASH widevine.

### ISSUE THREAD

**Issue by zabirtech** [google/ExoPlayer#3443]
### Issue description
When starting Stream WV:Secure video path required (MP4,H264). Instead of crashing the application the whole device does a forced reboot. 
### Reproduction steps
1.Start Exoplayer Demo Sample.
2.Select Widevine DASH Policy Tests(GTS)
3.Play WV:Secure video path required (MP4,H264).
### Link to test content
Test content from Exoplayer Demo.

### Version of ExoPlayer being used
Exoplayer version 2.5.4

### Device(s) and version(s) of Android being used
Device(Samsung SM-T800). 
Android 4.4.2
### A full bug report captured from the device
Could not create full bug report because of forced reboot.
[Adblogcat.txt](https://github.com/google/ExoPlayer/files/1454423/Adblogcat.txt)

Video link of error: https://drive.google.com/file/d/1SuUK6bq84F20gyiPIhMEKsoYXe0VsTpg/view?usp=sharing
Please advise if you have any other metods to capture bugreport when device reboots.

**Comment by wvpaf** [comment]
@zabirtech does this happen 100% of the time?  

You can pull a ADB bugreport when it comes back and that might contain useful info.
However this device is pretty old and if the issue is in the chip sets most likely will not get addressed.

**Comment by ram992** [comment]
@wvpaf, this also happens on Moto Devices (Moto X-Play and Moto G3). In my App I use WV Modular DRM Content, and as soon as I play any add (Mid Rolls and MP4), and come back to content, the device does a force restart.
@zabirtech you may try this as a Hack
To overcome this, I have been swtching between players (Native Player for Ad and ExoPlayer for Content everyTime).
I cannot provide you logs at this time cause I do not have the devices, but if you get time you can look into this issue.

**Comment by wvpaf** [comment]
@ram992 can you get an ADBbugreport from a MotoG3?

**Comment by wvpaf** [comment]
@zabirtech same to you as well if you are able to capture a ABDbugreport from a more recent device that would be great.

**Comment by ram992** [comment]
Will try, but can't say as we got an update from Redmi tech team that they have fixed this issue and are releasing an OTA update. Anyway I will try.

**Comment by ram992** [comment]
Can you give me an intro how to do it, after the device restarts, cause it Moto G3 doesn't print anything and suddenly restarts.
If there is a way on getting the log from device(if it has after reboot), I will get that

**Comment by zabirtech** [comment]
What u could do is connect it to a computer. And run a log from there so
even if it crashes the computer could save it.

Den ons 28 mars 2018 09:12ram992 <notifications@github.com> skrev:

**Comment by ram992** [comment]
Hey @zabirtech , is it like running Debug.startMethodTracing();  
Cause I have connected it to my system and check in my logCat for error.
But it never prints any serious error. I will try this again today and will update

**Comment by zabirtech** [comment]
Yes correct like that. Yeah keep me in the loop.

Den tor 29 mars 2018 05:49ram992 <notifications@github.com> skrev:

**Comment by StaehliJ** [comment]
Have same issue with a Samsung SM-P600 running on Android 4.3(api18).

And one of our customer seem to have the same issue with an Samsung Galaxy A3(2017) (a3y17lte) running on Android 8.0. Sorry I can't provider any log or bug report about it.

**Comment by rrfrias** [comment]
Samsung investigated and was unable to reproduce with a A320F. A bugreport (even after the reboot) will be helpful, without which we will not be able to make progress.
