### ISSUE TITLE
Retry Button in exoplayer is resuming the video but seekbar is getting reset

### ISSUE THREAD

**Issue by SagarKhurana** [google/ExoPlayer#3444]
I am trying to figure out the issues in many different links but I am unable to find any solution for this.

When device internet goes off and after retrieving the internet connection when I click on retry button, the video does resume, but the seek bar and the start duration gets reset and after that seek bar really behaves abnormally (for ex. if I seek forward 20 mins. it only seeks till 2-3 mins, or if I seek back a bit, the start duration goes to negative, which is totally illogical).

I have made few changes in PlaybackControlView mainly the UI changes and added the loader(custom progress dialog) on the states to show the buffering. I don't think that can affect the seek bar functionality of the exo player.

The code is in the link for my player activity class and the logs of the progress update method to see the position getting reset after retry button click.

please refer the [question ](https://stackoverflow.com/q/47194988/5934054)for more info

**Comment by tonihei** [comment]
Could you tell us which version of ExoPlayer you're using? And what kind of media source do you use - just a single window/period or any kind of multi-window, concatenated media source? In the latter case, have you activated the multi-window timebar or are you using the default single window timebar?

I tested your decsription in the current dev-version and a random piece of media and I wasn't able to reproduce.

**Comment by SagarKhurana** [comment]
@tonihei , thanks for your reply.

I think so I am using release v2 version for the above development, but I need to check that again. 
I am currently using hls link to play the video. I have not done any settings or changes related to multi-window timebar. 

Do you want me to use the dev-v2-r2.6.0 for the same?

**Comment by tonihei** [comment]
To make sure it's not accidentally related to the other changes you made, it might be best when you try to play your media file in our latest demo app to see whether you can reproduce the error in there.

**Comment by SagarKhurana** [comment]
ok... Sure Let me test this once with your latest version and I will get back to you if I face any issue.
I will close this issue if my problem is resolved. thanks.

**Comment by ojw28** [comment]
Closing on the assumption this is resolved.
