### ISSUE TITLE
Fullscreen dedicated Activity

### ISSUE THREAD

**Issue by pedromfmachado** [google/ExoPlayer#3447]
### Issue description
When implementing a video component for my application I wanted to include the fullscreen functionality. However I've been facing some issues and wondering if anyone could point me in the right direction.

**Here's what I've tried:**
- Like many articles I found on the matter, I tried adding the view to the root of the layout and make any other elements invisible or even adding it to a fullscreen `Dialog`. The limitation here it would make it difficult to have a substantially different layout on fullscreen and to use the [Picture-in-picture mode](https://developer.android.com/guide/topics/ui/picture-in-picture.html).

**Therefore the most suitable solution seems to be a fullscreen dedicated `Activity`:**
- I could just pass the `MediaSource` and the current position when opening such `Activity`, but it ends up buffering and taking a lot of time to really start the video on fullscreen.
- I also tried to pass the `SimpleExoPlayer` to the `Activity` by binding it to a singleton, and although it is functionally acceptable, I'm not totally comfortable with the implementation.

The specific question here is: is there any way I could pass the current state of the player to the fullscreen `Activity` in order for it to start from the desired position without the overhead of the initial loading?

**Thanks for your help!**

### Version of ExoPlayer being used
2.5.1

**Comment by ojw28** [comment]
I think the right thing to do is to have a single player instance and find a way of passing it to the activity, as per your second suggestion.

This is quite a common approach for apps that need to be backgrounded too (e.g. music apps), although in such cases you'd typically put the single player instance inside of a Service and create a way to expose that instance to the activity.

What are you not comfortable with, exactly?

**Comment by pedromfmachado** [comment]
I have no specific concerns about it, I just felt like there could be a different approach here. Thanks for the help!
