### ISSUE TITLE
How to support HLS manual switch video quality?

### ISSUE THREAD

**Issue by crossle** [google/ExoPlayer#345]
1. Get many video quality from HLS master playlist
2. Add manual switch video quality

**Comment by crossle** [comment]
How abount this question?

**Comment by ojw28** [comment]
This is something you'd have to do yourself. The code for selecting format is in HlsChunkSource (and is also controlled by the value of variantIndices passed to the constructor of that class). So you'd need to figure out how to modify that class to suit your needs.
