### ISSUE TITLE
DynamicConcatenatingMediaSource.createPeriod(MediaPeriodId, Allocator) ignores ad related parameters

### ISSUE THREAD

**Issue by stoleruedgar** [google/ExoPlayer#3452]
Using IMA extension with a list of ImaAdsMediaSource in a DynamicConcatenatingMediaSource.
Seems the check for id.isAd() always returns false in the method ImaAdsMediaSource.createPeriod(MediaPeriodId, Allocator)

Took a closer look into DynamicConcatenatingMediaSource and it seems that in createPeriod(MediaPeriodId, Allocator) a new MediaPeriodId is created 
MediaPeriodId idInSource = new MediaPeriodId(id.periodIndex - holder.firstPeriodIndexInChild);
but it completely ignores the original's adGroupIndex and adGroupIndex.

Shouldn't this be changed to MediaPeriodId(id.periodIndex - holder.firstPeriodIndexInChild, id.adGroupIndex, id.adGroupIndex) ?

### Version of ExoPlayer being used
r2.5.4

### Device(s) and version(s) of Android being used
Samsung Galaxy S7, Android 7.0

**Comment by tonihei** [comment]
Sounds right, we're going to fix this :)

Thanks for reporting!

**Comment by andrewlewis** [comment]
As an aside, even with this fix (which we should definitely make, for the benefit of custom `MediaSource`s that have periods with ads and aren't based on `ImaAdsLoader`) I think using `ImaAdsMediaSource` in a concatenation won't work correctly:
- `ImaAdsLoader` asserts that the player's timeline has only one period and expects the only period in the timeline to be its own period when reacting to player events.
- `AdsMediaSource` currently asserts that it's the top-level source in the composition. This check should probably be moved into the `ImaAdsLoader` somehow.

**Comment by stoleruedgar** [comment]
I am actually trying to write a custom AdsMediaSource based on the ImaAdsMediaSource and related files implementation, but I have reached a dead wall. It seems that the Framework if you set cue points (as in the Ima extension) and you seek past one cue point but don't have a loaded Ad url then MediaSource.maybeThrowSourceInfoRefreshError() gets called and the player stops. Is there any way to recover from this and keep playing the original MediaSource?

**Comment by andrewlewis** [comment]
I'm not sure I follow what you're trying to do. If you seek past an (unplayed) cue point, surely its ad group must be played before you can play the content? So if its URL is not known at this point the player needs to buffer until it becomes known.

At a high level, it's possible to implement your own custom AdsLoader and use it from the provided AdsMediaSource, though there are some limitations at the moment (like not supporting ad insertion in multi-period content). If you could describe in a bit more detail what you're trying to do we can try to provide guidance. This is diverging from the original bug here, though, so it may be worth filing a separate question issue. Thanks!
