### ISSUE TITLE
IMA Extension: Support for DAI (Dynamic ad insertion)

### ISSUE THREAD

**Issue by priscila225** [google/ExoPlayer#3454]
Do you support (or have plans to support) Dynamic Ad Insertion in the IMA Extension? If so, can you give me some directions?
Currently I'm following the google doc/sample https://developers.google.com/interactive-media-ads/docs/sdks/android/dai-quickstart

Thanks

**Comment by andrewlewis** [comment]
The IMA extension supports client-side ad insertion based on VAST/VMAP ad tags. Please see https://github.com/google/ExoPlayer/tree/release-v2/extensions/ima for information on using the extension.
