### ISSUE TITLE
Multiple SimpleExoPlayerView with RESIZE_MODE_ZOOM enabled can result in video rendering on the wrong view

### ISSUE THREAD

**Issue by mpainenz** [google/ExoPlayer#3456]
### Issue description

Video playing on one SimpleExoPlayerView surface may also render to other SimpleExoPlayerView surfaces. In my example, I have two SimpleExoPlayerView. I start by rendering a video to the first View, then swap the underlying SimpleExoPlayer object to the second View.

What seems to happen, is that the Video which is being cropped on the first View, is being displayed on the second surface.

![Image Example](https://raw.githubusercontent.com/mpainenz/ExoPlayerOverdrawBugDemo/master/Example.png?raw=true)

In the image above, on the left hand side, the top player view is playing media. On the right hand side, I have swapped the underlying player between the two views, and as you can see some of the initial player view is being rendered to the second view.

### Reproduction steps

1. Create two View SimpleExoPlayerView objects with ResizeMode set to RESIZE_MODE_ZOOM

2. Load content which will be cropped, such that the cropped area will overlap the other SimpleExoPlayerView

3. Play media, and swap the underlying player between the two views

### Link to test content
https://github.com/mpainenz/ExoPlayerOverdrawBugDemo

### Version of ExoPlayer being used
r2.5.4

### Device(s) and version(s) of Android being used
Galaxy Note 5
Emulator - Nexus 5X API 22

### A full bug report captured from the device
[bugreport.zip](https://github.com/google/ExoPlayer/files/1468758/bugreport.zip)

**Comment by ojw28** [comment]
I was somewhat hesitant to merge the change that added `RESIZE_MODE_ZOOM`, since I wasn't really certain it would work properly across all devices (see: https://github.com/google/ExoPlayer/pull/3187). @stellabei - Any ideas?

If you're not dealing with DRM protected content, you'd probably be better off using `TextureView` and `TextureView.setTransform`.

**Comment by mpainenz** [comment]
I notice that simply hiding the first view object will solve the issue, however there seems to be a black flicker when doing so using setVisibility(View.INVISIBLE); or setVisibility(View.GONE); on a SurfaceView.

@ojw28 I don't suppose you might be able to provide a basic code snipped, including the layout XML to use in order to attach a player to a TextureView? I have attempted this change to fix the issue I mentioned with the flicker, but I could not seem to get TextureView to work.

**Comment by mpainenz** [comment]
I have added a working TextureView version to my GitHub project I submitted as an example for this bug.

https://github.com/mpainenz/ExoPlayerOverdrawBugDemo

If anyone else wants to get TextureView working, this might help. To enable TextureView in the project, , change the main activity in the Manifest file to .TextureViewActivity, or see the following file:

https://github.com/mpainenz/ExoPlayerOverdrawBugDemo/blob/master/app/src/main/java/com/solus/exoplayeroverdrawbugdemo/TextureViewActivity.java

**Comment by ojw28** [comment]
Glad you got it working! It's interesting that you're able to work around the problem by toggling visibility, but I suspect the use of `RESIZE_MODE_ZOOM` is fundamentally flaky and/or inconsistent across different Android devices. I'd definitely prefer to use `TextureView` if I were developing an app that requires this feature (unless L1 DRM is a requirement, in which use of `SurfaceView` is likely a requirement).

**Comment by mpainenz** [comment]
Thank you for suggesting the fix. My feedback would be that a Exoplayer demo app which demonstrates a variety of functionality might be useful for developers.

Textureviee has had other unexpected benefits such as the last played game remains visible if the player is detached. This works very well for the use case of a recyclerview containing exposure items.

Thanks again, happy to close this issue.

**Comment by mpainenz** [comment]
Sorry, that comment contained a few typos.

Thank you for suggesting the fix. My feedback would be that an Exoplayer demo app which demonstrates a variety of functionality might be useful for developers.

Textureview has had other unexpected benefits such as the last played frame remains visible if the player is detached. This works very well for the use case of a recyclerview containing exoplayer items.

Thanks again, happy to close this issue.
