### ISSUE TITLE
How to play live Video Broadcast mpeg-ts in exoplayer

### ISSUE THREAD

**Issue by rburade21** [google/ExoPlayer#3459]
How to play Broadcasted content in exoplayer.
I have MPEG-TS which contains multiple channels.
I want to play those channels in exoplayer
is it possible in exoplayer?if it is please give me direction.
i am currently using exoplayer 2.4v

**Comment by ojw28** [comment]
This question is far too vague for us to answer, sorry. We provide a demo app [here](https://github.com/google/ExoPlayer/tree/r2.5.4/demo) that can serve as a good starting point. You can also try playing your own content in the demo app, as documented [here](https://google.github.io/ExoPlayer/demo-application.html).
