### ISSUE TITLE
Preparing playback

### ISSUE THREAD

**Issue by pakerfeldt** [google/ExoPlayer#346]
What would be the proper way of preparing `TrackRenderers` for playback while ExoPlayer is currently playing something completely different? Ideally I would like to build a set of renderers and have them buffer X number of segments/bytes/seconds and then be able to just switch over to these renderers at some point. Trying to manually call prepare on a ChunkDataSource seems to mess up the state and cause Internal runtime error in ExoPlayer when trying to play it back.

**Comment by pakerfeldt** [comment]
One path we're trying is to use the CacheDataSource and try to manually open and read from the source to cache data to disk. Does that seem reasonable? One problem we have with that is unfortunately the lack of support for unbounded requests. The manifests we're using doesn't specify indexRange or mediaRange so everything just bypasses the cache.

**Comment by ojw28** [comment]
The caching layer isn't particularly flexible right now. It's very much designed for for the specific case where you (a) only make bounded requests, and (b) make range requests into few URLs. Unbounded requests aren't supported at all, and the caching layer wont handle each chunk being fetched from a separate URL in an efficient way. It's on our list of things to fix, but it's a pretty complex change, particularly to generalize in a way that doesn't degrade the case it's currently designed for. There's no ETA at the moment.

**Comment by pakerfeldt** [comment]
I see. In our case we have one URL per segment. My current approach is to write our own CacheDataSource similar to what's already in there but tailored for our scenario. I think what's not perfectly clear to me yet is how to construct `DataSpec`s in the right way in order to prefetch some data. But I'll figure that out somehow. Actually I'm more posing the question to see if there's any better way to solve this or if my approach seems reasonable.

**Comment by ojw28** [comment]
That's probably the best way short of some pretty major restructuring, yes.
