### ISSUE TITLE
Try to playing a mp4 file ,Codec reported an error.

### ISSUE THREAD

**Issue by ZhengWeicheng** [google/ExoPlayer#3460]
Version as: [ExoPlayerLib/2.5.3] [Che1, Che1-CL20, HUAWEI, 19] 
Log as below:

11-15 15:16:24.286 I/ExoPlayerImpl(12567): Init 41e364b0 [ExoPlayerLib/2.5.3] [Che1, Che1-CL20, HUAWEI, 19]

11-15 15:16:24.286 D/EventLogger(12567): state [0.00, true, I]

11-15 15:16:24.346 D/EventLogger(12567): state [0.06, true, B]

11-15 15:16:24.346 D/MediaCodecVideoRenderer(12567): FalseCheck [legacyFrameSize, 1242x2208] [Che1, Che1-CL20, HUAWEI, 19]

11-15 15:16:24.346 D/MediaCodecVideoRenderer(12567): FalseCheck [legacyFrameSize, 1242x2208] [Che1, Che1-CL20, HUAWEI, 19]

11-15 15:16:24.356 V/ACodec  (12567): Now uninitialized

11-15 15:16:24.356 D/EventLogger(12567): sourceInfo [periodCount=1, windowCount=1

11-15 15:16:24.356 V/ACodec  (12567): onAllocateComponent

11-15 15:16:24.356 I/OMXClient(12567): Using client-side OMX mux.

11-15 15:16:24.366 D/EventLogger(12567):   period [?]

11-15 15:16:24.366 D/EventLogger(12567):   window [?, false, false]

11-15 15:16:24.366 D/EventLogger(12567): ]

11-15 15:16:24.416 D/EventLogger(12567): sourceInfo [periodCount=1, windowCount=1

11-15 15:16:24.416 D/EventLogger(12567):   period [25.00]

11-15 15:16:24.416 D/EventLogger(12567):   window [25.00, true, false]

11-15 15:16:24.416 D/EventLogger(12567): ]

11-15 15:16:24.416 D/EventLogger(12567): videoEnabled [0.14]

11-15 15:16:24.416 D/EventLogger(12567): audioEnabled [0.14]

11-15 15:16:24.426 V/ACodec  (12567): [OMX.qcom.video.decoder.avc] Now Loaded

11-15 15:16:24.426 V/ACodec  (12567): onConfigureComponent

11-15 15:16:24.426 V/ACodec  (12567): [OMX.qcom.video.decoder.avc] storeMetaDataInBuffers succeeded

11-15 15:16:24.426 I/ACodec  (12567): DRC Mode: Dynamic Buffer Mode

11-15 15:16:24.436 I/ExtendedCodec(12567): Decoder will be in frame by frame mode

11-15 15:16:24.436 V/ACodec  (12567): onStart

11-15 15:16:24.436 V/ACodec  (12567): [OMX.qcom.video.decoder.avc] Now Loaded->Idle

11-15 15:16:24.436 V/ACodec  (12567): [OMX.qcom.video.decoder.avc] Allocating 4 buffers of size 1568768 on input port

11-15 15:16:24.456 V/ACodec  (12567): onAllocateComponent

11-15 15:16:24.456 V/ACodec  (12567): replaced oldest buffer #19 with age 0 (0xb83e2de0/0x76e3e2f0 stored in 0x7707f260)

11-15 15:16:24.456 V/ACodec  (12567): [OMX.qcom.video.decoder.avc] submitting output meta buffer ID 0xb83e5530 for graphic buffer 0x76e34dd0

11-15 15:16:24.456 D/EventLogger(12567): videoFormatChanged [0.17, id=2, mimeType=video/avc, res=1242x2208]

11-15 15:16:24.456 V/ACodec  (12567): [OMX.qcom.video.decoder.avc] calling emptyBuffer 0xb83e2320 w/ codec specific data

11-15 15:16:24.456 V/ACodec  (12567): MetaDataBuffersToSubmit=17 portMode=RESUBMIT

11-15 15:16:24.456 V/ACodec  (12567): replaced oldest buffer #18 with age 0 (0xb84138e0/0x76dde438 stored in 0x7707f240)

11-15 15:16:24.456 V/ACodec  (12567): [OMX.qcom.video.decoder.avc] submitting output meta buffer ID 0xb83e54e0 for graphic buffer 0x75ed64a0

11-15 15:16:24.456 I/OMXClient(12567): Using client-side OMX mux.

11-15 15:16:24.456 E/OMXMaster(12567): A component of name 'OMX.qcom.audio.decoder.aac' already exists, ignoring this one.

11-15 15:16:24.456 V/ACodec  (12567): [OMX.google.aac.decoder] Now Loaded

11-15 15:16:24.456 V/ACodec  (12567): onConfigureComponent

11-15 15:16:24.456 E/        (  262): not in avi mode

11-15 15:16:24.456 V/ACodec  (12567): [OMX.qcom.video.decoder.avc] onOMXEmptyBufferDone 0xb83e2230

11-15 15:16:24.456 V/ACodec  (12567): onStart

11-15 15:16:24.456 E/        (  262): not in avi mode

11-15 15:16:24.456 V/ACodec  (12567): [OMX.qcom.video.decoder.avc] onOMXFillBufferDone 0xb83e5530 time 0 us, flags = 0x00000020

11-15 15:16:24.456 V/ACodec  (12567): [OMX.qcom.video.decoder.avc] calling fillBuffer 0xb83e5530

11-15 15:16:24.456 V/ACodec  (12567): [OMX.qcom.video.decoder.avc] onOMXEmptyBufferDone 0xb83e2320

11-15 15:16:24.456 V/ACodec  (12567): [OMX.qcom.video.decoder.avc] onOMXFillBufferDone 0xb83e54e0 time 0 us, flags = 0x00000020

11-15 15:16:24.456 V/ACodec  (12567): [OMX.qcom.video.decoder.avc] calling fillBuffer 0xb83e54e0

11-15 15:16:24.476 D/EventLogger(12567): audioSessionId [76]

11-15 15:16:24.476 V/ACodec  (12567): [OMX.google.aac.decoder] calling fillBuffer 0x77e49c50

11-15 15:16:24.476 V/ACodec  (12567): [OMX.google.aac.decoder] calling fillBuffer 0x76e10b18

11-15 15:16:24.476 V/ACodec  (12567): [OMX.google.aac.decoder] calling fillBuffer 0x76e34c18

11-15 15:16:24.476 V/ACodec  (12567): [OMX.google.aac.decoder] calling fillBuffer 0x76e10c18

11-15 15:16:24.476 V/ACodec  (12567): [OMX.google.aac.decoder] onOMXEmptyBufferDone 0x76d7e140

11-15 15:16:24.476 V/ACodec  (12567): [OMX.google.aac.decoder] onOMXFillBufferDone 0x77e49c50 time 60116099 us, flags = 0x00000000

11-15 15:16:24.476 V/ACodec  (12567): [OMX.google.aac.decoder] onOMXEmptyBufferDone 0x7635d120

11-15 15:16:24.476 V/ACodec  (12567): [OMX.google.aac.decoder] onOMXFillBufferDone 0x76e10b18 time 60139319 us, flags = 0x00000000

11-15 15:16:24.476 V/ACodec  (12567): [OMX.google.aac.decoder] onOMXEmptyBufferDone 0x76e2e698

11-15 15:16:24.476 V/ACodec  (12567): [OMX.google.aac.decoder] onOMXFillBufferDone 0x76e34c18 time 60162539 us, flags = 0x00000000

11-15 15:16:24.476 V/ACodec  (12567): [OMX.google.aac.decoder] onOMXEmptyBufferDone 0x7635d008

11-15 15:16:24.476 V/ACodec  (12567): [OMX.google.aac.decoder] onOMXFillBufferDone 0x76e10c18 time 60185759 us, flags = 0x00000000

11-15 15:16:24.476 E/ExoPlayerImplInternal(12567): Internal runtime error.

11-15 15:16:24.476 E/ExoPlayerImplInternal(12567): java.lang.IllegalStateException

11-15 15:16:24.476 E/ExoPlayerImplInternal(12567): 	at android.media.MediaCodec.dequeueOutputBuffer(Native Method)

11-15 15:16:24.476 E/ExoPlayerImplInternal(12567): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:917)

11-15 15:16:24.476 E/ExoPlayerImplInternal(12567): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:529)

11-15 15:16:24.476 E/ExoPlayerImplInternal(12567): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:574)

11-15 15:16:24.476 E/ExoPlayerImplInternal(12567): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:350)

11-15 15:16:24.476 E/ExoPlayerImplInternal(12567): 	at android.os.Handler.dispatchMessage(Handler.java:98)

11-15 15:16:24.476 E/ExoPlayerImplInternal(12567): 	at android.os.Looper.loop(Looper.java:136)

11-15 15:16:24.476 E/ExoPlayerImplInternal(12567): 	at android.os.HandlerThread.run(HandlerThread.java:61)

11-15 15:16:24.486 E/EventLogger(12567): playerFailed [0.19]

11-15 15:16:24.486 E/EventLogger(12567): com.google.android.exoplayer2.ExoPlaybackException

11-15 15:16:24.486 E/EventLogger(12567): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:404)

11-15 15:16:24.486 E/EventLogger(12567): 	at android.os.Handler.dispatchMessage(Handler.java:98)

11-15 15:16:24.486 E/EventLogger(12567): 	at android.os.Looper.loop(Looper.java:136)

11-15 15:16:24.486 E/EventLogger(12567): 	at android.os.HandlerThread.run(HandlerThread.java:61)

11-15 15:16:24.486 E/EventLogger(12567): Caused by: java.lang.IllegalStateException

11-15 15:16:24.486 E/EventLogger(12567): 	at android.media.MediaCodec.dequeueOutputBuffer(Native Method)

11-15 15:16:24.486 E/EventLogger(12567): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:917)

11-15 15:16:24.486 E/EventLogger(12567): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:529)

11-15 15:16:24.486 E/EventLogger(12567): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:574)

11-15 15:16:24.486 E/EventLogger(12567): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:350)

11-15 15:16:24.486 E/EventLogger(12567): 	... 3 more

11-15 15:16:24.506 D/PowerManagerService(  906): handleSandman: canDream=false, mWakefulness=Awake

11-15 15:16:24.556 I/audio_hw_primary(  262): out_standby: enter: stream (0xb83869c0) usecase(0: deep-buffer-playback)

11-15 15:16:24.576 I/DEBUG   (  253): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***

11-15 15:16:24.576 I/DEBUG   (  253): Build fingerprint: 'Honor/Che1-CL20/Che1:4.4.4/Che1-CL20/C00B286:user/ota-rel-keys,release-keys'

11-15 15:16:24.576 I/DEBUG   (  253): Revision: '0'

11-15 15:16:24.576 I/DEBUG   (  253): pid: 12567, tid: 13737, name: CodecLooper  >>> zcweicheng.exoplayertest <<<

11-15 15:16:24.576 I/DEBUG   (  253): signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------

11-15 15:16:24.676 I/DEBUG   (  253):     r0 00000000  r1 000035a9  r2 00000006  r3 770b5cd0

11-15 15:16:24.676 I/DEBUG   (  253):     r4 00000006  r5 00000000  r6 000035a9  r7 0000010c

11-15 15:16:24.676 I/DEBUG   (  253):     r8 00000000  r9 72abd57d  sl 4017b5b1  fp 00000000

11-15 15:16:24.676 I/DEBUG   (  253):     ip 00000010  sp 77e397b0  lr 400f5b15  pc 40104abc  cpsr 000f0010

11-15 15:16:24.676 I/DEBUG   (  253):     d0  6c69616620294b34  d1  3030312d203a6420

11-15 15:16:24.676 I/DEBUG   (  253):     d2  73282c2928726576  d3  29745f7375746173

11-15 15:16:24.676 I/DEBUG   (  253):     d4  4320383433333a70  d5  2851455f4b434548

11-15 15:16:24.676 I/DEBUG   (  253):     d6  2d6365646f436d20  d7  4f74696d6275733e

11-15 15:16:24.676 I/DEBUG   (  253):     d8  0000000000000000  d9  0000000000000000

11-15 15:16:24.676 I/DEBUG   (  253):     d10 0000000000000000  d11 0000000000000000

11-15 15:16:24.676 I/DEBUG   (  253):     d12 0000000000000000  d13 0000000000000000

11-15 15:16:24.676 I/DEBUG   (  253):     d14 0000000000000000  d15 0000000000000000

11-15 15:16:24.676 I/DEBUG   (  253):     d16 ffffffff00000013  d17 00000006ffffffff

11-15 15:16:24.676 I/DEBUG   (  253):     d18 0001000200020001  d19 0006000500040003

11-15 15:16:24.676 I/DEBUG   (  253):     d20 c03c000000000000  d21 c038000000000000

11-15 15:16:24.676 I/DEBUG   (  253):     d22 0000000000000000  d23 c03c000000000000

11-15 15:16:24.676 I/DEBUG   (  253):     d24 000e000d000c000b  d25 0010000f000d000e

11-15 15:16:24.676 I/DEBUG   (  253):     d26 0000000000000000  d27 0000000000000000

11-15 15:16:24.676 I/DEBUG   (  253):     d28 3ff0000000000000  d29 0000000000000000

11-15 15:16:24.676 I/DEBUG   (  253):     d30 0010001000100010  d31 0000000000000000

11-15 15:16:24.676 I/DEBUG   (  253):     scr 60000012

11-15 15:16:24.676 I/DEBUG   (  253): 

11-15 15:16:24.676 I/DEBUG   (  253): backtrace:

11-15 15:16:24.676 I/DEBUG   (  253):     #00  pc 00021abc  /system/lib/libc.so (tgkill+12)

11-15 15:16:24.676 I/DEBUG   (  253):     #01  pc 00012b11  /system/lib/libc.so (pthread_kill+48)

11-15 15:16:24.676 I/DEBUG   (  253):     #02  pc 00012d25  /system/lib/libc.so (raise+10)

11-15 15:16:24.676 I/DEBUG   (  253):     #03  pc 00011a5b  /system/lib/libc.so

11-15 15:16:24.676 I/DEBUG   (  253):     #04  pc 00021370  /system/lib/libc.so (abort+4)

11-15 15:16:24.676 I/DEBUG   (  253):     #05  pc 00007107  /system/lib/libcutils.so (__android_log_assert+86)

11-15 15:16:24.676 I/DEBUG   (  253):     #06  pc 00052575  /system/lib/libstagefright.so (android::ACodec::BaseState::onInputBufferFilled(android::sp<android::AMessage> const&)+104)

11-15 15:16:24.676 I/DEBUG   (  253):     #07  pc 000552af  /system/lib/libstagefright.so (android::ACodec::BaseState::onMessageReceived(android::sp<android::AMessage> const&)+66)

11-15 15:16:24.676 I/DEBUG   (  253):     #08  pc 00055613  /system/lib/libstagefright.so (android::ACodec::ExecutingState::onMessageReceived(android::sp<android::AMessage> const&)+594)

11-15 15:16:24.676 I/DEBUG   (  253):     #09  pc 000088ef  /system/lib/libstagefright_foundation.so (android::AHierarchicalStateMachine::onMessageReceived(android::sp<android::AMessage> const&)+82)

11-15 15:16:24.676 I/DEBUG   (  253):     #10  pc 0000943d  /system/lib/libstagefright_foundation.so (android::ALooperRoster::deliverMessage(android::sp<android::AMessage> const&)+152)

11-15 15:16:24.676 I/DEBUG   (  253):     #11  pc 00008f17  /system/lib/libstagefright_foundation.so (android::ALooper::loop()+198)

11-15 15:16:24.676 I/DEBUG   (  253):     #12  pc 0000ea45  /system/lib/libutils.so (android::Thread::_threadLoop(void*)+104)

11-15 15:16:24.676 I/DEBUG   (  253):     #13  pc 0000e5e7  /system/lib/libutils.so

11-15 15:16:24.676 I/DEBUG   (  253):     #14  pc 0000d469  /system/lib/libc.so (__thread_entry+44)

11-15 15:16:24.676 I/DEBUG   (  253):     #15  pc 0000d609  /system/lib/libc.so (pthread_create+316)

11-15 15:16:24.676 I/DEBUG   (  253): 

11-15 15:16:24.676 I/DEBUG   (  253): stack:

11-15 15:16:24.676 I/DEBUG   (  253):          77e39770  00000000  

11-15 15:16:24.676 I/DEBUG   (  253):          77e39774  0000002e  

11-15 15:16:24.676 I/DEBUG   (  253):          77e39778  00000003  

11-15 15:16:24.676 I/DEBUG   (  253):          77e3977c  77e397bc  [stack:13737]

11-15 15:16:24.676 I/DEBUG   (  253):          77e39780  00000003  

11-15 15:16:24.676 I/DEBUG   (  253):          77e39784  4011c447  /system/lib/libc.so (writev+12)

11-15 15:16:24.676 I/DEBUG   (  253):          77e39788  72abd57d  /system/lib/libstagefright.so

11-15 15:16:24.676 I/DEBUG   (  253):          77e3978c  def65d89  

11-15 15:16:24.676 I/DEBUG   (  253):          77e39790  77e397bc  [stack:13737]

11-15 15:16:24.676 I/DEBUG   (  253):          77e39794  00000001  

11-15 15:16:24.676 I/DEBUG   (  253):          77e39798  00000015  

11-15 15:16:24.676 I/DEBUG   (  253):          77e3979c  72941530  

11-15 15:16:24.676 I/DEBUG   (  253):          77e397a0  00000001  

11-15 15:16:24.676 I/DEBUG   (  253):          77e397a4  4011c425  /system/lib/libc.so (write+12)

11-15 15:16:24.676 I/DEBUG   (  253):          77e397a8  4012d1cc  /system/lib/libc.so

11-15 15:16:24.676 I/DEBUG   (  253):          77e397ac  72941530  

11-15 15:16:24.676 I/DEBUG   (  253):     #00  77e397b0  00000006  

11-15 15:16:24.676 I/DEBUG   (  253):          77e397b4  00000000  

11-15 15:16:24.676 I/DEBUG   (  253):          77e397b8  000035a9  

11-15 15:16:24.676 I/DEBUG   (  253):          77e397bc  00000010  

11-15 15:16:24.676 I/DEBUG   (  253):          77e397c0  00000010  

11-15 15:16:24.676 I/DEBUG   (  253):          77e397c4  400f5b15  /system/lib/libc.so (pthread_kill+52)

11-15 15:16:24.676 I/DEBUG   (  253):     #01  77e397c8  00000006  

11-15 15:16:24.676 I/DEBUG   (  253):          77e397cc  00000000  

11-15 15:16:24.676 I/DEBUG   (  253):          77e397d0  00000000  

11-15 15:16:24.676 I/DEBUG   (  253):          77e397d4  400f5d29  /system/lib/libc.so (raise+14)

11-15 15:16:24.676 I/DEBUG   (  253):     #02  77e397d8  77e397e4  [stack:13737]

11-15 15:16:24.676 I/DEBUG   (  253):          77e397dc  400f4a5f  /system/lib/libc.so

**Comment by andrewlewis** [comment]
This issue is being closed because it does not adhere to our issue template, and/or because it omits information requested in the issue template that is required for us to investigate the problem efficiently. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

If you’re able to provide complete information as requested in the issue template, please do so below and we’ll re-open the issue. Thanks!
