### ISSUE TITLE
Hi; How can i get the current selected TRACK_TYPE_TEXT and TRACK_TYPE_VIDEO because onResume i would like to set the last selected tracks waiting for your soonest reply thanks!!

### ISSUE THREAD

**Issue by TarifHatoum** [google/ExoPlayer#3461]
(no description provided)

**Comment by TarifHatoum** [comment]
Hi; How can i get the current selected TRACK_TYPE_TEXT and TRACK_TYPE_VIDEO because onResume i would like to set the last selected tracks waiting for your soonest reply thanks!!

**Comment by AquilesCanta** [comment]
Assuming you are using ExoPlayer  v2, see `Player.getCurrentTrackSelections()`. The position assignment corresponds to the renderers that you built ExoPlayer with.

**Comment by TarifHatoum** [comment]
How could i save l last closed caption used and setted to alla other videos?

Sent from my iPhone

On Nov 15, 2017, at 12:31, Santiago Seifert <notifications@github.com<mailto:notifications@github.com>> wrote:


Assuming you are using ExoPlayer v2, see Player.getCurrentTrackSelections(). The position assignment corresponds to the renderers that you built ExoPlayer with.
