### ISSUE TITLE
Mp4 video track selection

### ISSUE THREAD

**Issue by sviety** [google/ExoPlayer#3464]
Hello,
I was wondering about video track selection for mp4 format. In my case i have to expose to the user all available video formats (quality). I have a list of url that points to the mp4 files that i want to expose as a available tracks. How can i achive this? Should i make a custom implementation of the MediaSource? If not can you guide me what will be the best approach to achive that?
Thanks

**Comment by ojw28** [comment]
You should probably implement this outside of the player. There's no reason why the player needs to be involved in which file is selected for playback, given they're just regular mp4s.

The proper way to do this would be to use a proper adaptive streaming standard like DASH or HLS, which would then also allow adaptation between the available qualities during playback.

**Comment by sviety** [comment]
Thank you for your response @ojw28. Currently our system involve adaptive streaming, but some of our content is available only as a mp4 file. I will follow your suggestions about implementing itoutside of the player.
Thanks
