### ISSUE TITLE
Interlaced video issue on Pixel devices

### ISSUE THREAD

**Issue by acommoner** [google/ExoPlayer#3468]
### Issue description
Videos that are interlaced with the TopFirst setting are not playing correctly on Pixel (sailfish & marlin), but seem to work correctly on other phones. The sound works fine & I'm not getting any explicit errors from ExoPlayer in the logs that I've seen.

It looks like both devices are using "omx.qcom.video.decoder.avc" for decoding, and if I force it to use a software decoder, the video renders correctly on these devices, but not on others. Is there an issue with the encoding itself or is it something Exo-related? I've tried to answer my own question, but haven't been able to find an answer thus far.

Video encoding specs:

Codec | H.264

Codec Options | InterlacedMode:TopFirst,MaxReferenceFrames:3,Level:3.1,ColorSpaceConversionMode:None,Profile:baseline
Maximum Number of Frames Between Keyframes | 90
Fixed Number of Frames Between Keyframes | false
Bit Rate | 1000
Frame Rate | 29.97
Video Max Frame Rate |  
Max Width | 1024
Max Height | 576
Sizing Policy | ShrinkToFit
Padding Policy | NoPad
Display Aspect Ratio | auto

Possibly related issues: 
[#2060](https://github.com/google/ExoPlayer/issues/2060) : not enough info here
[#2013](https://github.com/google/ExoPlayer/issues/2013) : seems to only be related to artifacts & not the same issue

### Reproduction steps
Load the video on a Pixel device

### Link to test content
Sent via email

### Version of ExoPlayer being used
2.5.4

### Device(s) and version(s) of Android being used
Google Pixel (sailfish) & Google Pixel XL (marlin), both running Android Oreo.

### A full bug report captured from the device
[bugreport-marlin-OPR3.170623.013-2017-11-15-08-55-56.zip](https://github.com/google/ExoPlayer/files/1476731/bugreport-marlin-OPR3.170623.013-2017-11-15-08-55-56.zip)

**Comment by ojw28** [comment]
I don't think Android officially supports interlaced H264 [internal ref: b/118755604], in which case what happens is pretty much going to be a best effort by the decoder being used. @andrewlewis can probably confirm.

**Comment by andrewlewis** [comment]
Yes. I don't think this is ExoPlayer-related. Whether interlacing is supported is likely to vary across devices/builds/codecs as you've noted, so if you have control over the encoding I'd avoid using interlacing.

**Comment by acommoner** [comment]
Alright. Thank you for the responses!
