### ISSUE TITLE
Accurately detect switching media in playlist

### ISSUE THREAD

**Issue by b0g8** [google/ExoPlayer#3471]
### Issue description
I want to accurately detect switching to new media in a playlist. Can this be detected from the frame itself? Like embedding some information in the SurfaceTexture? Or count the releaseOutputBuffer? I don't see other way. Currently I am using onPositionDiscontinuity, but it is difficult to sync at frame level.

### Version of ExoPlayer being used
2.5.4

### Device(s) and version(s) of Android being used
7.0

**Comment by andrewlewis** [comment]
There is information in `SurfaceTexture` to do this accurately:
- `SurfaceTexture.getTimestamp` returns the release time associated with the texture set on the last call to `SurfaceTexture.updateTexImage`.
- `MediaCodecVideoRenderer.renderOutputBufferV21` receives the original presentation timestamp of the output buffer and its release time, so you can override it to store a mapping from release time to original presentation timestamp.
- This means that you can recover the original presentation time of a frame based on a release time returned by `SurfaceTexture.getTimestamp`, and when the first frame of the new period is rendered to the texture this should jump to its start time.
