### ISSUE TITLE
Questions about gts test

### ISSUE THREAD

**Issue by zmafox** [google/ExoPlayer#3473]
[log.txt](https://github.com/google/ExoPlayer/files/1482089/log.txt)
Hi:
	I know that gts use the exoplayer, and would like to know which tag the gts package gts-5.0_r2 uses.
	My device failed at com.google.android.exoplayer.gts.DashTest#testWidevineH264Adaptive, the error log shows 
"Expected to dequeue video buffer with presentation timestamp: 134733000. Instead got: 134766000"
	Then I checked the timestamp of empty buffer, it has 2 134733000. 
	I wondoer why it has same timestamp, maybe flush function should be called.

Best Regards,
Ming,

**Comment by ojw28** [comment]
I'm not sure I follow your comment about empty buffers (why would there be empty buffers), but this error would be indicative of the decoder (OMX.Freescale.std.video_decoder.avc.v3.hw-based) incorrectly discarding video a video buffer when adaptively switching from one resolution to another.

I don't think the version in GTS corresponds exactly to any given tag, unfortunately, however if you're observing this issue I'd expect it to also reproduce running the (very-near-to-equivalent) tests in [DashStreamingTest](https://github.com/google/ExoPlayer/blob/r2.5.4/playbacktests/src/androidTest/java/com/google/android/exoplayer2/playbacktests/gts/DashStreamingTest.java). And if the goal of figuring out what tag is used is to help reproduce with access to the source code, that should be sufficient for your needs :).

**Comment by zmafox** [comment]
EmptyBuffer and FillBuffer are Openmax IL component command for decoders. they are input and output buffers queued to decoder.
I filtered the time stamp from 134566000 us to 134833000 us, and get 11 frames, 134733000us and 134766000us both appears twice.
[OMX.Freescale.std.video_decoder.avc.v3.hw-based] calling emptyBuffer 3 w/ time 134600000 us
[OMX.Freescale.std.video_decoder.avc.v3.hw-based] calling emptyBuffer 1 w/ time 134566000 us
[OMX.Freescale.std.video_decoder.avc.v3.hw-based] calling emptyBuffer 2 w/ time 134666000 us
[OMX.Freescale.std.video_decoder.avc.v3.hw-based] calling emptyBuffer 3 w/ time 134633000 us
[OMX.Freescale.std.video_decoder.avc.v3.hw-based] calling emptyBuffer 1 w/ time 134733000 us
[OMX.Freescale.std.video_decoder.avc.v3.hw-based] calling emptyBuffer 2 w/ time 134699000 us
[OMX.Freescale.std.video_decoder.avc.v3.hw-based] calling emptyBuffer 3 w/ time 134766000 us
[OMX.Freescale.std.video_decoder.avc.v3.hw-based] calling emptyBuffer 1 w/ time 134733000 us
[OMX.Freescale.std.video_decoder.avc.v3.hw-based] calling emptyBuffer 2 w/ time 134766000 us
[OMX.Freescale.std.video_decoder.avc.v3.hw-based] calling emptyBuffer 3 w/ time 134800000 us
[OMX.Freescale.std.video_decoder.avc.v3.hw-based] calling emptyBuffer 1 w/ time 134833000 us

Output Buffer count are also got 11 frames:
[OMX.Freescale.std.video_decoder.avc.v3.hw-based] onOMXFillBufferDone 15 time 134566000 us, flags = 0x00000000
[OMX.Freescale.std.video_decoder.avc.v3.hw-based] onOMXFillBufferDone 26 time 134600000 us, flags = 0x00000000
[OMX.Freescale.std.video_decoder.avc.v3.hw-based] onOMXFillBufferDone 14 time 134633000 us, flags = 0x00000000
[OMX.Freescale.std.video_decoder.avc.v3.hw-based] onOMXFillBufferDone 12 time 134666000 us, flags = 0x00000000
[OMX.Freescale.std.video_decoder.avc.v3.hw-based] onOMXFillBufferDone 20 time 134699000 us, flags = 0x00000000
[OMX.Freescale.std.video_decoder.avc.v3.hw-based] onOMXFillBufferDone 28 time 134733000 us, flags = 0x00000000
[OMX.Freescale.std.video_decoder.avc.v3.hw-based] onOMXFillBufferDone 25 time 134766000 us, flags = 0x00000000
[OMX.Freescale.std.video_decoder.avc.v3.hw-based] onOMXFillBufferDone 21 time 134766000 us, flags = 0x00000000
[OMX.Freescale.std.video_decoder.avc.v3.hw-based] onOMXFillBufferDone 19 time 134766000 us, flags = 0x00000000
[OMX.Freescale.std.video_decoder.avc.v3.hw-based] onOMXFillBufferDone 18 time 134800000 us, flags = 0x00000000
[OMX.Freescale.std.video_decoder.avc.v3.hw-based] onOMXFillBufferDone 17 time 134833000 us, flags = 0x00000000

For normal playback, input buffers have different timestamps in decoding sequence and decodrs can output frame with increased timestamp sequence.
In this test, I see all 11 frames from 134566000us to 134833000us, so I thinks decoder does not lost frames.
I also see video resolution changed twice from the log before 134833000us and timestamp of input buffer never repeat. Test application does not catch exception when input resolution changed, it proves decoder works fine.
The key point is whether output frame timestamp should be equal to input when input buffers has two 134733000us. If decoder treat the timestamp as error inputs, then it can handle it in many strategy, output timetsmp as its input sequence is just one of many solutions. If decoder choose other solution then the output timestamp is not extactly same as input. Error handling method vary in different decoder. I can see the video plays well during the test and I do not know why input timestamp get duplicate, and onProcessedOutputBuffer checks it such strictly.

**Comment by ojw28** [comment]
The test is asserting that the decoder should set output timestamp to match input timestamp, and that this should happen even if duplicate input timestamps occur. Duplicate timestamps are not too uncommon in practice during adaptive playbacks where the segmentation across different representations is not exactly aligned.

> If decoder treat the timestamp as error inputs, then it can handle it in many strategy, output timetsmp as its input sequence is just one of many solutions.... Error handling method vary in different decoder.

This is undesirable. If every decoder does something different then applications will end up behaving differently depending on what Android device they're running on. One of the goals of these tests (and enforcing them) is to improve consistency. Passing the timestamp from input to output is the obvious thing to do (and is what most decoder implementations do already).

> Test application does not catch exception when input resolution changed, it proves decoder works fine.

You could similarly argue that a decoder that discards every 1000th buffer is working fine, because a user probably wouldn't notice and a typical player implementation wouldn't fail playback. But a decoder that does that is definitely not fine :). The tests are more rigorous in terms of what they check. This is intentional.

**Comment by saiyamd** [comment]
Hello, on i.MX6 platform, the same test is failing with below error. 

"junit.framework.AssertionFailedError: Test timed out after 300000 ms."

My observation is, all the videos with adaptive playback play smoothly and at last the activity is getting stuck (the last frame of the video is stuck on screen) and the test is failing with this error. Can you suggest what could be the issue?

**Comment by andrewlewis** [comment]
@saiyamd Which specific test is failing? Is the decoder propagating the end of stream buffer correctly? If you file a new issue with the output of `adb bugreport` we can take a look.

**Comment by saiyamd** [comment]
@andrewlewis - Please check, issue created - https://github.com/google/ExoPlayer/issues/3902

**Comment by benjaminjrood** [comment]
Hello @saiyamd,

I too can confirm I am experiencing the same issue with the following:

1. i.MX6Q
2. N7.1.1 Android BSP from NXP (with upgraded codecs to N7.1.2/O8.0.0)
