### ISSUE TITLE
Live DASH playback fails after few tens of minutes.

### ISSUE THREAD

**Issue by SGA-masato-fujii** [google/ExoPlayer#3474]
We're developing Live DASH Playback application with ExoPlayer.
Now we're facing the following problem.

I guess this is our contents issue.
But I don't know what is wrong.
If you have any information, please let us know.

### Issue description
Live DASH playback fails after tens of minutes.

### Reproduction steps
1. start to playback Live DASH content.
2. wait a while <- stop to playback by error.

### Link to test content
Sorry, we can't provide our contents.

### Version of ExoPlayer being used
2.5.3

### Device(s) and version(s) of Android being used
Android 7.0, 6.0.1

### A full bug report captured from the device
```
11-17 18:58:54.659 E/LoadTask( 2481): Unexpected exception loading stream
11-17 18:58:54.659 E/LoadTask( 2481): java.lang.IllegalStateException: Top bit not zero: -1
11-17 18:58:54.659 E/LoadTask( 2481): 	at com.google.android.exoplayer2.util.ParsableByteArray.readUnsignedIntToInt(ParsableByteArray.java:379)
11-17 18:58:54.659 E/LoadTask( 2481): 	at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.parseTrun(FragmentedMp4Extractor.java:816)
11-17 18:58:54.659 E/LoadTask( 2481): 	at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.parseTruns(FragmentedMp4Extractor.java:636)
11-17 18:58:54.659 E/LoadTask( 2481): 	at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.parseTraf(FragmentedMp4Extractor.java:572)
11-17 18:58:54.659 E/LoadTask( 2481): 	at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.parseMoof(FragmentedMp4Extractor.java:547)
11-17 18:58:54.659 E/LoadTask( 2481): 	at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.onMoofContainerAtomRead(FragmentedMp4Extractor.java:458)
11-17 18:58:54.659 E/LoadTask( 2481): 	at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.onContainerAtomRead(FragmentedMp4Extractor.java:396)
11-17 18:58:54.659 E/LoadTask( 2481): 	at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.processAtomEnded(FragmentedMp4Extractor.java:374)
11-17 18:58:54.659 E/LoadTask( 2481): 	at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.readAtomPayload(FragmentedMp4Extractor.java:369)
11-17 18:58:54.659 E/LoadTask( 2481): 	at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:256)
11-17 18:58:54.659 E/LoadTask( 2481): 	at com.google.android.exoplayer2.source.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:112)
11-17 18:58:54.659 E/LoadTask( 2481): 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:315)
11-17 18:58:54.659 E/LoadTask( 2481): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
11-17 18:58:54.659 E/LoadTask( 2481): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
11-17 18:58:54.659 E/LoadTask( 2481): 	at java.lang.Thread.run(Thread.java:818)
```

**Comment by AquilesCanta** [comment]
> A full bug report captured from the device

This has not been provided. Without the media or a bugreport this is not possible to diagnose.

**Comment by ojw28** [comment]
I'm not sure there's much we can do even with a bug report in this case. The stack trace suggests the media is incorrectly encoded, because it specifies a negative sample duration in a `trun` box, or because it's setting the flag that indicates the existence of sample durations in the `trun` box when it shouldn't be.

We'd need access to the media to confirm this theory, and there may be other possible causes (e.g. the server not satisfying range requests correctly). Given we don't have access to the media, we have little option but to assume the most likely theory is correct and close on the assumption the media is broken.
