### ISSUE TITLE
Click noise during gapless playback of mp3s

### ISSUE THREAD

**Issue by th3hamm0r** [google/ExoPlayer#3475]
### Issue description
As I've mentioned in https://github.com/google/ExoPlayer/issues/3470#issuecomment-345212457, the ogg issue in #3470 is also valid for mp3s.
I've created a "mp3-test"-branch in the test-app created for #3470. The ExoPlayer plays a gap, where the custom player (which uses Android's media framework) does not.

### Reproduction steps
1. Clone into the "mp3-test"-branch of my test-app (https://github.com/th3hamm0r/exoplayer-gapless-test/tree/mp3-test)
2. Compare the sound of the ExoPlayer vs. the custom player. 
3. In my tests the `ExoPlayer` produced a click noise when transitioning (after 10s), the `CustomPlayer` did not.
Using `mpg123 --gapless 1.mp3 2.mp3` plays it gapless too.

The two files have been created with the following commands:

    ffmpeg -i INPUTFILE -f wav - | lame -V 2 --noreplaygain - source.mp3
    mp3splt -t 0.10 -q -f -o @n -b -d output source.mp3

### Link to test content
Note: This is a modified version of the ogg-test for #3470.

https://github.com/th3hamm0r/exoplayer-gapless-test/tree/mp3-test

### Version of ExoPlayer being used
2.5.4

### Device(s) and version(s) of Android being used
Tested on multiple devices, eg. Nexus 5 (6.0.1), Nexus 5X (8.0), Nexus 9 (7.1.1), Nokia 6,...

### A full bug report captured from the device
--

**Comment by andrewlewis** [comment]
This appears to work fine for me in the demo app: I can't hear any gap and I can see the encoder delay and padding are set to 2016 and 1656 respectively for the first file and 1800 and 1872 for the second.

Please could you check whether this is reproducible for you on the `dev-v2` branch? We recently switched to trimming audio ourselves in `DefaultAudioSink`. That said, I don't think the switch should have made any difference unless you're using a non-MediaCodec-based renderer.

**Comment by th3hamm0r** [comment]
@andrewlewis it may depend on your headset/device. I can clearly hear clicks from the ExoPlayer's playback.
I've now modified the mp3-test to playback 10 2s-files and I hope this creates notable gaps. The custom player with Android's media framework still plays it completely gapless.

**Comment by andrewlewis** [comment]
Still no luck reproducing this. I tried a couple of different devices and headsets. I can see that the AudioTrack is not being released and that some samples are getting trimmed as expected. If there is a gap being introduced, it likely means we are not trimming the right number of bytes from the start/end of the media.

@th3hamm0r I won't have more time to investigate this soon. One possible next step is to check that the trim sample counts in ExoPlayer's `TrimmingAudioProcessor.setTrimSampleCount` and in the platform `MediaFormat` provided by `MediaExtractor` match. If they do match, dump the PCM data written to the AudioTrack in your demo app vs. ExoPlayer, and locate the point of transitioning between the two files so we can figure out why different numbers of samples are being trimmed.

**Comment by ojw28** [comment]
I don't think we were ever able to reproduce this, and it has not been reported by any other users. Closing.
