### ISSUE TITLE
Allow CDM names as drm_scheme_uuid parameter.

### ISSUE THREAD

**Issue by ahemeda** [google/ExoPlayer#3478]
getting java.lang.IllegalArgumentException: Invalid UUID string when using

adb shell am start -a com.google.android.exoplayer.demo.action.VIEW  --es drm_license_url  "https://proxy.uat.widevine.com/proxy?video_id=48fcc369939ac96c&provider=widevine_test"   --es drm_scheme_uuid widevine https://storage.googleapis.com/wvmedia/cenc/h264/tears/tears.mpd

**Comment by AquilesCanta** [comment]
The drm_license_url is expecting a uuid, "widevine" is not. Try passing "`edef8ba9-79d6-4ace-a3c8-27dcd51d21ed`" instead. I will use this issue to track supporting CDM names as parameter as well.

**Comment by ahemeda** [comment]
thanks a lotm that works, what's the uuid for playready?

**Comment by ojw28** [comment]
https://www.google.com/search?q=playready+uuid
