### ISSUE TITLE
Broken build

### ISSUE THREAD

**Issue by axet** [google/ExoPlayer#3479]
Hello! According to 'constants.gradle' you are using: 

    minSdkVersion = 9
    supportLibraryVersion = '25.4.0'

But if you check SwitchCompat.java from 25.4.0 it is targeted for 14+ API, But if you checking the same SwitchCompat.java 25.3.1 the same file market for 7+ API.

https://developer.android.com/topic/libraries/support-library/rev-archive.html#25-3-1

Or here:

https://issuetracker.google.com/issues/37139255

I think solution should be lowering supportLibrary to 24.3.1 until issue is fixed (if ever?).

**Comment by ojw28** [comment]
ExoPlayer's minSdkVersion is being increased to 14 in the `2.6.0` release, to match the increase to 14 for most support library modules as of `26.0.0`, as documented [here](https://developer.android.com/topic/libraries/support-library/index.html).

99.5%+ of active Android devices are running API level 15 or later, as per [this data](https://developer.android.com/about/dashboards/index.html), so I wouldn't expect developers to need to target apps at earlier API levels at this point.
