### ISSUE TITLE
Shorten the time showing the source error in ExoPlayer

### ISSUE THREAD

**Issue by haihack** [google/ExoPlayer#3482]
### Issue description
When I play the online radio stream, it shows the below error message. I knew that the problem is on server side but it tooks 10 seconds to show the error. Is there any way to shorten the time showing error. I use ExoPlayer 2.5.4

### Link to test content
Streaming source: http://radio.visionotaku.com:8000/stream.mp3

### Version of ExoPlayer being used
2.5.4

### A full bug report captured from the device
> E/ExoPlayerImplInternal: Source error. com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to http://radio.visionotaku.com:8000/stream.mp3 at se.greenbird.exoplayershoutcast.ShoutcastDataSource.open(ShoutcastDataSource.java:182) at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:692) at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:315) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) at java.lang.Thread.run(Thread.java:818) Caused by: java.net.SocketTimeoutException: failed to connect to radio.visionotaku.com/162.243.156.226 (port 8000) after 10000ms

**Comment by andrewlewis** [comment]
It sounds like you just need to reduce the timeout for HTTP requests. The provided `DefaultHttpDataSourceFactory` has a constructor parameter for setting a timeout. `ShoutcastDataSource` is not part of ExoPlayer so I'm not sure whether it provides this facility.
