### ISSUE TITLE
Improve ott zapping time

### ISSUE THREAD

**Issue by alfonsoramosa** [google/ExoPlayer#3487]
Hi,

I'm using Exoplayer 2.4 on Android TV to play OTT live streams (DRM protected):
- Smooth Streaming + PlayReady
I'm using the same key to encrypt all the channels, so the same license should be valid to decrypt all the channels.

Currently, during each channel zapping, I'm releasing the player. Something similar to what the Exoplayer demo App is doing at PlayerActivity.releasePlayer().
After that, I'm starting the playback of the next channel.

That's the "first version" that I have implemented and now I need to improve the zapping time.

I can see the following possibilities.

- As I'm using the same DRM key, it should be possible to reuse the same license instead of requesting a new one.
- Reuse the same player instance.
- Reuse the same playback, just dynamically replace the previous manifest with the new one and continue playing on the live edge.

I will appreciate some guidance on how to implement that using Exoplayer and information about existing possibilities.

Best Regards,
Alfonso.

**Comment by alfonsoramosa** [comment]
Hi @ojw28 , @andrewlewis 

Can somebody provide feedback on this question? I will really appreciate it.

probably it's a frequent use case to use Exoplayer for OTT live playback.
Improve zapping time can be an interesting feature for many projects.  Of course, some dependencies can be project/implementation specific (Streaming protocol, DRM), but having a general guidance or clues will be useful.

Thanks!!
Alfonso

**Comment by ojw28** [comment]
It should definitely be possible to re-use the same player instance. This is pretty trivial (just re-prepare it with the new source). Re-using the same `MediaDrm` session should be possible too, but you'll probably need to supply a custom `DrmSessionManager` to do this, which has a way of keeping the session alive as the player is re-prepared with the new source. I don't think re-using the same playback will work (or makes sense).

Once https://github.com/google/ExoPlayer/issues/2826 is done, that should also help speed things up, provided you're re-using the same player instance.
