### ISSUE TITLE
Allow customisation of updateMediaSessionMetadata

### ISSUE THREAD

**Issue by thibseisel** [google/ExoPlayer#3497]
When using the MediaSession extension for ExoPlayer, it is possible to specify whether or not metadata should be updated with the `doMaintainMetadata` constructor parameter. If `true`, `MediaSessionConnector` will internally call the private method `updateMediaSessionMetadata` to recreate a `MediaMetadataCompat` from the currently playing `MediaDescriptionCompat`.

I already have MediaMetadataCompat objects stored in memory cache, and I'd like to retrieve them from it instead of creating them again. One solution would be to subclass `MediaSessionConnector` to redefine `setPlayer` and attach another `Player.Listener` to call my own updateMediaSessionMetadata, but it's not very handy.

Is there any easier way ? If not, I suggest the following:
1. Make `updateMediaSessionMetadata` protected, or
2. Provide a `MetadataProvider` interface to customize MediaSessionConnector, along with a `DefaultMetadataProvider` to retain the current behavior.

Thanks in advance !

**Comment by ojw28** [comment]
@marcbaechinger - What do you think?

**Comment by ojw28** [comment]
What's your memory cache keyed by?

**Comment by thibseisel** [comment]
To comply with the MediaSession API, my metadata and items are keyed by a media id, which could be any `String`. 
Also, you may note that I use RxJava `Observable` (and in this particular case, `Maybe`) to abstract network/disk access, so retrieving metadata from my cache is asynchronous.

**Comment by marcbaechinger** [comment]
The MetadataProvider approach seems like worth looking into on our side. I'll take a look into this.

**Option 1 for now (with QueueNavigator):**

If you need a quick solution for now, I wonder if you are using a `QueueNavigator` already? If you do so you can set the metadata yourself (while having doMaintainMetadata=false), that should work like when it is set by the connector. In case you are using the `TimelineQueueNavigator` you wrap it with your own implementatin of `QueueNavigator` to intercept the call to `onCurrentWindowIndexChanged` and then delegate to the actual `TimelineQueueNavigator`:

```
public void onCurrentWindowIndexChanged(Player player) {
   timelineQueueNavigator.onCurrentWindowIndexChanged(player);
   mediaSession.setMetadata(getMetadataForWindowIndex(player.getCurrentWindowIndex()));
}
```

The method `getMetadataForWindowIndex` can then just return the metadata object you are already caching.

**Option 2 for now**
If not using a `QueueNavigator` you can do what you mentioned and register your own `EventListener` and maintain metadata yourself. 


Let me know whether the quick options help for now. I'll look into the `MetadataProvider` approach asap.

**Comment by tsuharesu** [comment]
I was having the same problem because I didn't know about `QueueNavigator` and don't want to use it. What I did is to set a listener in my player using `player?.addListener(this)`. It's basically the same that `MediaSessionConnector` does internally.

```java
class ExoPlayerAdapter(private val mediaSessionCompat: MediaSessionCompat) : PlayerEventListener {

[...] 

private fun setupPlayer() {
    if (player == null) {
        player = ExoPlayerFactory.newSimpleInstance(context, DefaultTrackSelector())
    }

    MediaSessionConnector(mediaSessionCompat).setPlayer(player, null)
    player?.addListener(this)
}

override fun onTimelineChanged(timeline: Timeline?, manifest: Any?, reason: Int) {
    mediaSessionCompat.setMetadata(currentMedia)
}
}
```

**Comment by ojw28** [comment]
Support for this was added in https://github.com/google/ExoPlayer/commit/62ee13b11dcfaa504d9cab782662bcf8afcf7578.
