### ISSUE TITLE
Find out Format / Track what the player selects when is getting initialized

### ISSUE THREAD

**Issue by zsoltbokor** [google/ExoPlayer#3499]
Hello,

If I prepare the player with a media with multiple audio / subtitle  (multi language) the player selects one audio and one subtitle when startup but there is no possibility (or I can't find) to find out which one of the possible audio / subtitle has been selected.

When the player loads I have the list of tracks by renderers and using them I can change the audio / subtitle using the track index, group id etc and results an override in the **DefaultTrackSelector** instance but the override is empty when I load the player.

The **SimpleExoPlayer** has a private array with the renderers, every renderer contains a **FormatHolder** which also would be useful but unfortunately since the renderers array is private I can't access this info (in debug worked).

Please provide a way to find out or the default selected track indexes or the formats what has the **id** field. Thank you

**Comment by zsoltbokor** [comment]
Format.selectionFlags is what I was looking for.

**Comment by ojw28** [comment]
I don't think it is. Those flags are specified statically in the media itself. They may guide selection, but definitely do not accurately represent what the current selection is. The main demo app's `EventLogger.onTracksChanged` method demonstrates printing all of the available tracks to logcat, marking those that are currently selected with an "X". You can use that as a starting point.
