### ISSUE TITLE
Couldn't adaptive different codecs in HLS stream

### ISSUE THREAD

**Issue by ntminh90** [google/ExoPlayer#3500]
**Reproduction steps**
We built the V2 exoplayer for our app. 
We transcoded our stream into HLS stream with 2 profiles with different codec video in mainifest file.
1. 1080p H264
2. 2160p HEVC
We tried to test our HLS link on Exoplayer, but we couldn't adaptive between two profiles in good network environment. Only playing 1080p profile.
Then we tried to transcode our stream into HLS stream with 2 profiles with the same codec H264 or HEVC video in mainifest file. We could adaptive between two profiles.

 **HLS mainifest file link description to test content**
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-INDEPENDENT-SEGMENTS
#EXT-X-STREAM-INF:BANDWIDTH=5605600,AVERAGE-BANDWIDTH=5605600,CODECS="avc1.640028,mp4a.40.2",RESOLUTION=1920x1080,FRAME-RATE=30.000
1080p.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=13340800,AVERAGE-BANDWIDTH=13340800,CODECS="hev1.1.6.L153.B0,mp4a.40.2",RESOLUTION=3840x2160,FRAME-RATE=30.000
2160p.m3u8
```

**Version of ExoPlayer being used**
Release-V2

**Device(s) and version(s) of Android being used**
I used the Android 4K UHD TV Sony 6.0 and V3 Wechip STB for testing.

**A full bug report captured from the device**
```
[X] Track:0, id=1, mimeType=video/avc, bitrate=5605600, res=1920x1080, supported=YES
[ ] Track:0, id=0, mimeType=video/hevc, bitrate=13340800, res=3840x2160, supported=NO_EXCEEDS_CAPABILITIES
```

**Comment by ojw28** [comment]
You can enable cross-mime adaptiveness by creating your `DefaultTrackSelector` as follows:
```
trackSelector = new DefaultTrackSelector(adaptiveTrackSelectionFactory);
trackSelector.setParameters(trackSelector.getParameters().withAllowMixedMimeAdaptiveness(true));
```
Note that cross-mime adaptive switches may be less seamless than those that use the same codec, since the allocated decoder cannot be re-used. Ideally you'd provide HEVC transcodes at the lower resolutions too, so that devices that support HEVC can use only the HEVC transcodes (hence either getting a big bandwidth saving over what you're doing currently, or getting better quality).

**Comment by AquilesCanta** [comment]
I think it is worth mentioning that the hevc 4k stream is not supported by the device so, even if you enable allowMixedMimeAdaptiveness, it will not be adapted to, as it cannot be rendered according to device capability advertising. If the device does not support it, there is not much exoplayer can do about it. You could try lower quality profile/level configurations, if you control the media generation.

**Comment by ntminh90** [comment]
Hi AquilesCanta.
Our device under testing could decode and adaptive HEVC stream if the playlist has 1 HEVC profile or 2 HEVC profiles.
Our problem here is the different codecs in the mainifest file .m3u8 which could not adaptive between profiles.
Thanks

**Comment by AquilesCanta** [comment]
The stream is reported as NO_EXCEEDS_CAPABILITIES. This does not mean that the device cannot play hevc, but that this particular stream exceeds capabilities. It is likely that other hevc streams with lower resolution are supported. Sometimes, devices under-report their capabilities. You could try forcing its playback and see what happens.

The comment by @ojw28 above still applies, though.

**Comment by OrenMe** [comment]
@nyminh90 are you able to get codec data per variant?
I have a mixed playlist with both h264 and hevc and I a device which supports hevc and I get all tracks supported but all of them are flagged as hevc codec, even the h264 ones.

**Comment by ojw28** [comment]
@OrenMe - I think the behavior you're observing is a bug. We're tracking the issue in https://github.com/google/ExoPlayer/issues/3653.
