### ISSUE TITLE
Is MediaSource release supposed to be handled by user or internally?

### ISSUE THREAD

**Issue by davidliu** [google/ExoPlayer#3508]
I'm receiving a stacktrace that's basically the same as #1914, which is caused by me releasing the MediaSource manually. Should I not be doing this? If so, then is this MediaSource released elsewhere automatically?

**Comment by andrewlewis** [comment]
Yes. The player's current source is released when you call `prepare` (with a new source), `stop` or `release` on the player. So once you've passed a source to `prepare` the player will take ownership and you shouldn't release it.
