### ISSUE TITLE
EventListener.onTimelineChanged howto get current window

### ISSUE THREAD

**Issue by derlucas** [google/ExoPlayer#3509]
I'm using ExoPlayer 2.6.0 and made a simple Activity which creates a ConcatenatingMediaSource of some ExtractorMediaSource with http URL to Videos. All playing in endless loop without any issues.

Now i want to get the current window+position when the video changes. So i implement the DefaultEventListener and override the onTimelineChanged method.

If i ask my player within this method using player.getCurrentPeriodIndex() and player.getCurrentWindowIndex() i do not get the right values.
Are those values updated after the onTimelineChanged Event is fired? I also tried the onTracksChanged event, but with the same results.

Is there another way to get the current window directly after a new video was loaded? I looked in the EventLogger from the sample, but i could not find the right spot for my needed information.

If i put a Handler with a periodic postDelayed runnable to poll the getCurrentPeriodIndex and getCurrentWindowIndex i get the right results.

I'd rather not do the polling since i want to syncronise some players via network.

I'm using an Android TV box running 6.0.1 my App Compile SDK is 26, target 26, min 23. Build Tools Version 26.0.2

**Comment by andrewlewis** [comment]
`onPositionDiscontinuity` is called when playback transitions from one item to the next. You can get the new window index by calling `getCurrentWindowIndex`. Does that provide the information you need?

**Comment by derlucas** [comment]
Thank you very much. This is exactly what i need. Maybe yesterday it was too late and i sat too long on the problem so i did not see this onPositionDiscontinuity description :)
