### ISSUE TITLE
Subtitles stopped working after update to Exoplayer 2.6.0

### ISSUE THREAD

**Issue by tonihuotari** [google/ExoPlayer#3516]
### Issue description
After updating to Exoplayer 2.6.0 all subtitle/text tracks are marked as unsupported:

Here is some output from EventLogger
```
Renderer:2 [
     Group:0, adaptive_supported=N/A [
       [ ] Track:0, id=838144648, mimeType=text/vtt, bitrate=100, language=da, supported=NO_UNSUPPORTED_DRM
     ]
     Group:1, adaptive_supported=N/A [
       [ ] Track:0, id=1155354603, mimeType=text/vtt, bitrate=100, language=fi, supported=NO_UNSUPPORTED_DRM
     ]
     Group:2, adaptive_supported=N/A [
       [ ] Track:0, id=1201850606, mimeType=text/vtt, bitrate=100, language=no, supported=NO_UNSUPPORTED_DRM
     ]
     Group:3, adaptive_supported=N/A [
       [ ] Track:0, id=1112635959, mimeType=text/vtt, bitrate=100, language=sv, supported=NO_UNSUPPORTED_DRM
     ]
   ]
```

### Reproduction steps

1. Open the ExoPlayer demo app for version 2.5.4
2. Add the provided stream to media.exolist.json
3. Play content
4. Click on "Text"-button
--> There are multiple subtitle tracks; "da", "fi", "no", "sv"
5. Reproduce these steps for ExoPlayer version 2.6.0
--> "Text"-button is gone because no subtitle tracks are supported

### Link to test content
Sent to dev.exoplayer@gmail.com

### Version of ExoPlayer being used
ExoPlayer 2.6.0

### Device(s) and version(s) of Android being used
Android: 7.0, 5.0.1, issue does not seem to be OS related
Devices: Samsung Galaxy S3, Lenovo Tab 3, issue does not seem device related

### A full bug report captured from the device
Sent to dev.exoplayer@gmail.com

**Comment by ojw28** [comment]
I think the player is doing the correct thing here. The DASH manifest indicates that the text tracks are DRM protected, by including `ContentProtection` elements in the text `AdaptationSet`s. ExoPlayer doesn't support DRM protected text tracks, so it doesn't select them. In previous releases we blindly assumed that all text tracks were not protected, which would likely have caused failures if we attempted to select one that really was protected.

If this content works correctly using older versions of ExoPlayer, then it's likely that the text tracks are not DRM protected. In which case the DASH manifest is saying the wrong thing, and the solution is to fix that.

**Comment by tonihuotari** [comment]
Thanks @ojw28!
