### ISSUE TITLE
Error in project when upgrading to 2.6.0

### ISSUE THREAD

**Issue by admobwebmaster** [google/ExoPlayer#3518]
Hello Friend!
After updating the version in my project to 2.6.0 my project appears an error as it shows in the print below someone please could min help.

![exoplayer](https://user-images.githubusercontent.com/34076141/33393127-e0947b70-d51c-11e7-9c73-68bd5ca5937d.png)

**Comment by yurilaguta** [comment]
Press Alt + Enter and select first option OR just add method onSeekProcessed() in the anonymous class

**Comment by tonihei** [comment]
Alternatively, use can also use Player.DefaultEventListener when you are not interested in all events and just want to subscribe to some of them.

**Comment by admobwebmaster** [comment]
@Yurii-Laguta 

Hi friend, thanks for your help
I created the class onSeekProcessed but the error continues as it was :(

 @Override
            public void onSeekProcessed() {

            }
        });
