### ISSUE TITLE
[QUESTION] MONO/STEREO SOUND

### ISSUE THREAD

**Issue by imeanyou2** [google/ExoPlayer#3529]
Hello,

Thanks for the great player.

We have a question.

Does Exoplayer support MONO and STEREO sound as well ?

In detail, 
1. If the VOD is based on MONO, ExoPlayer plays the VOD with MONO ?
2. If the VOD is based on STEREO, ExoPlayer plays the VOD with STEREO ?

**Comment by andrewlewis** [comment]
The `AudioTrack` is configured to output with the number of channels specified in the input stream, so this should just work. Have you tried it?
