### ISSUE TITLE
Unknown destiny of the "USB tuner support" commit

### ISSUE THREAD

**Issue by Avetri** [google/ExoPlayer#3530]
@AquilesCanta , @ojw28 , hello.

I can't find any remains of ["Add tv module for USB tuner support + demo app"](https://github.com/google/ExoPlayer/commit/f257300d8e770b57a22cc4a9cbf1120943be7e91) commit (hash f257300d8e770b57a22cc4a9cbf1120943be7e91). It looks like was lost during the next merge.
What really was happen with the commit? Will be any future activity in this (USB tuners & DVB-S/C/T broadcst receiving) direction?

**Comment by AquilesCanta** [comment]
Yes, we will be pushing the tv extension once it reaches a stable state. The idea is to support broadcast tv on exoplayer. For now, it is built on top the linux DVB API. Unfortunately we cannot track this development as it will be not release until ready, which means commits will not be backed by the modified files. We will have more updates in 2018. Once we do release it, we are interested in all the feedback we can get so, please stay _tuned_.

**Comment by Avetri** [comment]
Thanks
