### ISSUE TITLE
[Question]Ability to pause player while Ad is playing

### ISSUE THREAD

**Issue by jazimm** [google/ExoPlayer#3532]
I read that you believe the user should not be able to interact with any user controls while a Video Ad is playing but it seems the user should be able to pause/play the Ad at a minimum to avoid having to restart an Ad if they don't wish to watch it at that time. Is there any functionality to access the players pause/play functionality while the ad is playing on v2.5? Thanks.

**Comment by andrewlewis** [comment]
Apps can call `setPlayWhenReady(false)` while an ad is playing to pause it. The provided UI controls are hidden during ads unless the player is paused (so for example, if you pause the player then seek past an ad the controls will be shown until the player is unpaused), but your app can provide custom controls that allow the user to play/pause during ads if desired.

**Comment by jazimm** [comment]
Thanks Andrew, I should have been more specific in asking if there was a way to turn on the user controls or allow the container ui to be clickable in order to set the setPlayWhenReady(true/false) when the user clicks on the ad container or parent as the ability to click the ad container or parents seems to be disabled while the ad is playing? Thanks

**Comment by raunakyadav** [comment]
Hi,
Is there a way to stop the autoplay of ads. Using setPlayWhenReady(false) stops the autoplay at start but if we wait around 2-3 secs and then click play, it skips the ad and jumps to playing content video. How can I enforce that the content is played only after ad completes? Same is observed on the demo app.

**Comment by andrewlewis** [comment]
@raunakyadav Thanks for reporting. I've filed #3764 to track this.
