### ISSUE TITLE
CEA608 - Incorrect alignment of long lines

### ISSUE THREAD

**Issue by zsmatyas** [google/ExoPlayer#3533]
This line attempts to work around the limitation that center alignment was not existing in the 608 standard: 

https://github.com/google/ExoPlayer/blob/e7c60a2a234ab11bc75335453a7836fef9509610/library/core/src/main/java/com/google/android/exoplayer2/text/cea/Cea608Decoder.java#L729

The problem is that too many lines matches this condition in normal cases. SCREEN_CHARWIDTH is 32. Any lines longer than 29 characters will be automatically center aligned irrespective of any other setting, like the screen being wide-aspect ratio, font size etc.

Multi line texts are shown with a separate CUE for each line. This condition is checked for each cue separately, so few of the lines (having close to 32 characters) will be center aligned, the others will stay left-aligned:

![device-2017-11-27-181448_a](https://user-images.githubusercontent.com/8737074/33508828-bc8091f6-d6b1-11e7-92f9-8e05ce320f11.jpg)

Would it be possible to add a new check to the if condition: "startPadding > 0"? That could reduce the number of false positives by skipping lines with absolutely no padding. An alternative solution would be to evaluate all lines and decide about center alignment for all or none together instead of for each line independently.

Incoming CEA608 commands leading to the issue demonstrated on the image above:
> 11-27 18:11:18.306 : MISC: RESUME_CAPTION_LOADING
> 11-27 18:11:18.349 : MISC: ERASE_DISPLAYED_MEMORY
> 11-27 18:11:18.379 : MISC: END_OF_CAPTION
> 11-27 18:11:30.309 : MISC: RESUME_CAPTION_LOADING
> 11-27 18:11:30.310 : PAC: Row:14; Col:1; Color:WHITE; italic:false; underline:false
> 11-27 18:11:30.328 : Incoming char: D
> 11-27 18:11:30.328 : Incoming char: a
> 11-27 18:11:30.340 : Incoming char: v
> 11-27 18:11:30.340 : Incoming char: e
> 11-27 18:11:30.365 : Incoming char: ,
> 11-27 18:11:30.365 : Incoming char:  
> 11-27 18:11:30.389 : Incoming char: y
> 11-27 18:11:30.389 : Incoming char: o
> 11-27 18:11:30.389 : Incoming char: u
> 11-27 18:11:30.389 : Incoming char:  
> 11-27 18:11:30.419 : Incoming char: h
> 11-27 18:11:30.419 : Incoming char: a
> 11-27 18:11:30.460 : Incoming char: v
> 11-27 18:11:30.460 : Incoming char: e
> 11-27 18:11:30.493 : Incoming char:  
> 11-27 18:11:30.493 : Incoming char: A
> 11-27 18:11:30.550 : Incoming char: n
> 11-27 18:11:30.550 : Incoming char: t
> 11-27 18:11:30.550 : Incoming char: h
> 11-27 18:11:30.550 : Incoming char: e
> 11-27 18:11:30.592 : Incoming char: m
> 11-27 18:11:30.592 : Incoming char:  
> 11-27 18:11:30.623 : Incoming char: a
> 11-27 18:11:30.623 : Incoming char: n
> 11-27 18:11:30.657 : Incoming char: d
> 11-27 18:11:30.657 : Incoming char:  
> 11-27 18:11:30.728 : Incoming char: t
> 11-27 18:11:30.728 : Incoming char: h
> 11-27 18:11:30.728 : Incoming char: e
> 11-27 18:11:30.728 : Incoming char: y
> 11-27 18:11:30.756 : PAC: Row:15; Col:1; Color:WHITE; italic:false; underline:false
> 11-27 18:11:30.797 : Incoming char: h
> 11-27 18:11:30.797 : Incoming char: a
> 11-27 18:11:30.829 : Incoming char: v
> 11-27 18:11:30.830 : Incoming char: e
> 11-27 18:11:30.887 : Incoming char:  
> 11-27 18:11:30.887 : Incoming char: p
> 11-27 18:11:30.887 : Incoming char: e
> 11-27 18:11:30.888 : Incoming char: o
> 11-27 18:11:30.919 : Incoming char: p
> 11-27 18:11:30.919 : Incoming char: l
> 11-27 18:11:30.960 : Incoming char: e
> 11-27 18:11:30.960 : Incoming char:  
> 11-27 18:11:30.990 : Incoming char: t
> 11-27 18:11:30.990 : Incoming char: o
> 11-27 18:11:31.052 : Incoming char:  
> 11-27 18:11:31.052 : Incoming char: t
> 11-27 18:11:31.053 : Incoming char: a
> 11-27 18:11:31.053 : Incoming char: l
> 11-27 18:11:31.086 : Incoming char: k
> 11-27 18:11:31.087 : Incoming char:  
> 11-27 18:11:31.129 : Incoming char: t
> 11-27 18:11:31.129 : Incoming char: o
> 11-27 18:11:31.158 : MISC: RESUME_CAPTION_LOADING
> 11-27 18:11:31.231 : MISC: ERASE_DISPLAYED_MEMORY
> 11-27 18:11:31.231 : MISC: END_OF_CAPTION

**Comment by zsmatyas** [comment]
One other example of incorrect assumptions in exoPlayer:

```
 D/Cea608Decoder: MISC: RESUME_CAPTION_LOADING
 D/Cea608Decoder: PAC: Row:14; Col:9; Color:WHITE; italic:false; underline:false
 D/Cea608Decoder: TAB: 3
 D/CueBuilder: Incoming char: '-'
 D/CueBuilder: Incoming char: '¿'
 D/CueBuilder: Incoming char: 'Q'
 D/CueBuilder: Incoming char: 'u'
 D/CueBuilder: Incoming char: 'é'
 D/CueBuilder: Incoming char: ' '
 D/CueBuilder: Incoming char: 'e'
 D/CueBuilder: Incoming char: 's'
 D/Cea608Decoder: PAC: Row:15; Col:9; Color:WHITE; italic:false; underline:false
 D/Cea608Decoder: TAB: 3
 D/CueBuilder: Incoming char: 'l'
 D/CueBuilder: Incoming char: 'o'
 D/CueBuilder: Incoming char: ' '
 D/CueBuilder: Incoming char: 'q'
 D/CueBuilder: Incoming char: 'u'
 D/CueBuilder: Incoming char: 'e'
 D/CueBuilder: Incoming char: ' '
 D/CueBuilder: Incoming char: 'n'
 D/CueBuilder: Incoming char: 'o'
 D/CueBuilder: Incoming char: ' '
 D/CueBuilder: Incoming char: 'p'
 D/CueBuilder: Incoming char: 'u'
 D/CueBuilder: Incoming char: 'e'
 D/CueBuilder: Incoming char: 'd'
 D/CueBuilder: Incoming char: 'e'
 D/CueBuilder: Incoming char: 's'
 D/CueBuilder: Incoming char: '?'
 D/Cea608Decoder: MISC: ERASE_DISPLAYED_MEMORY
 D/Cea608Decoder: MISC: RESUME_CAPTION_LOADING
 D/Cea608Decoder: MISC: ERASE_DISPLAYED_MEMORY
 D/Cea608Decoder: MISC: END_OF_CAPTION
```
The first line gets center aligned, as the start and end padding seems to be around the same range, but as the second line is longer, the end padding is smaller then the start padding, so it gets right aligned. As this is continuous text, they should be both middle or left aligned.

**Comment by zsmatyas** [comment]
I tested the above suggested idea: cut the cueBuilder.build() into 2 parts to calculate a common alignment. Assuming:
- right alignment is rare, and all lines should match the right alignment criteria for it.
- center alignment is artificially introduced by our decoder, but it should not be mixed with left aligned cues (but right + center aligned should result in center alignment for all lines)
- left alignment is the most common, but then all lines should be left aligned

I could calculate the common alignment by:
```
    int commonAligment = Cue.ANCHOR_TYPE_END;

    for (int i = 0; i < cueBuilders.size(); i++) {
      commonAligment = Math.min(cueBuilders.get(i).getAlignment(), commonAligment);
    }
```
This is a "leftmost of all current lines" alignment, and looks better than the current mix and match based on the Cea608Decoder assumptions. Worst case scenario: the artificial middle alignment of Cea608Decoder is not used, but the values that are coming from the content, that we interpreted as an intention for "center alignment with whitespaces". This whitespace alignment may be slightly off, but close to center and no more mixed alignment.

**Comment by ojw28** [comment]
Rather than consider all cues, I think it would makes sense to first divide the cues into groups of cues on consecutive lines. If there are some cues near the top and some other cues near the bottom, it makes sense to determine alignment separately.

I was also thinking it might make sense to look at the start/end padding of the lines in each group. If they all have the same start padding but ragged end padding, the group should probably be start aligned. If they have the same end padding and ragged start padding, the group should probably be end aligned. If they have ragged start and end padding, that's a good indicator they should be middle aligned.

I'm not really sure exactly how this should work. Are you able to provide some sample content that we can test various approaches with, and where the current approach isn't working well?

**Comment by zsmatyas** [comment]
You can also compare the Column value of the lines to be more restrictive. As you can see in the examples, the rows are consecutive, and the Columns are matching, so their left side should be matched -> this immediately suggests left alignment. 

Center alignment can be confirmed by comparing "Column + (character count / 2)" for consecutive lines. If 2 of them match, then the content provider intended to match the middle of the texts being aligned.

Right alignment can be confirmed by having 2 different column values where "column + character count" is the same for 2 consecutive lines. In that case the intention was having 2 lines ending at the same position: right alignment for sure.

**Comment by ojw28** [comment]
Yes, something along those lines sounds like a good approach.

**Comment by zsmatyas** [comment]
Any updates? :) Unfortunately, I was only authorized to share the bug report, but no related code changes at that point. Would be nice not having conflicting fixes, but cleanly back-merge your version.

**Comment by AquilesCanta** [comment]
No updates so far, unfortunately. Sorry.

**Comment by zsmatyas** [comment]
:repeat_one:

**Comment by ojw28** [comment]
Please feel free to send a pull request if you're in a rush for this change. Thanks.

**Comment by ojw28** [comment]
Fixed in `dev-v2`.
