### ISSUE TITLE
CEA608 - Padding might get into negative ranges

### ISSUE THREAD

**Issue by zsmatyas** [google/ExoPlayer#3534]
The following line calculates the end padding of the Cue for positioning: 

https://github.com/google/ExoPlayer/blob/e7c60a2a234ab11bc75335453a7836fef9509610/library/core/src/main/java/com/google/android/exoplayer2/text/cea/Cea608Decoder.java#L727

The values are:
`int endPadding = 32 - padding - StringLength. `

In unexpected cases (mostly caused by improper content) StringLength might be bigger than 32.

The problem is that some content - specifically beginnings of commercials in live channels - are missing the Preamble Address Code for the very first line (setting up the position where the line starts). So the first two lines are handled as one, incoming characters for both are added into a single StringBuilder, and will end up as a single Cue of possibly longer than 32 characters.

This line does not restrict the range, might result in a padding being negative if the character count is bigger than 32. Negative values will cause the SubtitlePainter have invalid ranges and will position the Subtitle completely incorrectly.

This is caused by incorrect content, but happens quite frequently. Could we add a simple check for negative values to correct this? Something like:
`endPadding = Math.max(endPadding, 0); `

This would correct the calculations so all interim values will stay in the valid range. This does not fix the issue, the originally 2 lines of subtitles will be shown in a single line, but at least inside the visible screen area.

**Comment by ojw28** [comment]
The cue ends up being start, center or end aligned. What would you expect to happen for this type of cue? Presumably either start or center. We should probably just explicitly enter one of those blocks in the case that `endPadding` is negative. Do you think one is better than the other?

**Comment by zsmatyas** [comment]
All these alignment options in 608Decoder are based on assumptions what the content provider intended to achieve by adding whitespaces around the text. As the negative value is caused by incorrect content, we should probably not trust the values and the safest could be center alignment for Pop-on captioning mode. But other modes cannot be center aligned, the only other common mode is Roll-up, always left aligned.
So something like this:

```
@@ -726,7 +726,7 @@ public final class Cea608Decoder extends CeaDecoder {
       // The number of empty columns after the end of the text, in the same range.
       int endPadding = SCREEN_CHARWIDTH - startPadding - cueString.length();
       int startEndPaddingDelta = startPadding - endPadding;
-      if (captionMode == CC_MODE_POP_ON && Math.abs(startEndPaddingDelta) < 3) {
+      if (captionMode == CC_MODE_POP_ON && (endPadding < 0 || (Math.abs(startEndPaddingDelta) < 3 && startPadding > 0))) {
         // Treat approximately centered pop-on captions are middle aligned.
         position = 0.5f;
         positionAnchor = Cue.ANCHOR_TYPE_MIDDLE;
```
Note: also added the condition suggested in https://github.com/google/ExoPlayer/issues/3533

**Comment by ojw28** [comment]
Agreed center alignment probably makes most sense. We can make a change and will close this issue when it's pushed. I'm not convinced by the other change (Re #3533); that could break as many cases as it fixes. I think we really need to do something smart that considers multiple lines for that one.
