### ISSUE TITLE
Skip preroll in audio stream

### ISSUE THREAD

**Issue by tokland** [google/ExoPlayer#3539]
I am writing a personal app to listen to streaming radios using react-native-audio-streamer (which uses ExoPlayer v2.1.1). My problem is that many streams have a preroll with info/ads, I'd like to skip it. 

An example: http://rac1.radiocat.net. I am able to do it in my GNU/Linux using mplayer with option `-ss N` (where N is a big number so the preroll is completely skipped whatever its duration):

```
$ mplayer -ss 1000 http://rac1.radiocat.net
[...]
ICY Info: StreamTitle='';StreamUrl='';adw_ad='true';durationMilliseconds='13113';insertionType='preroll';
[... only the 13-sec preroll is skipped, the radio audio plays normally ... ]
```

Is this possible with ExoPlayer? Thanks!

**Comment by andrewlewis** [comment]
Please try wrapping the media source in a [`ClippingMediaSource`](https://github.com/google/ExoPlayer/blob/3c201a0/library/core/src/main/java/com/google/android/exoplayer2/source/ClippingMediaSource.java#L41).

**Comment by andrewlewis** [comment]
Actually, setting a non-zero start point won't work unless the media is seekable.

**Comment by andrewlewis** [comment]
You could try implementing a custom media source that is similar to `ClippingMediaSource` but that doesn't do an initial seek and instead discards samples before the desired start position. I don't think we'd provide this feature in the library, though, as it won't work well for large start positions.

**Comment by tokland** [comment]
I am not familiar with the ExoPlayer codebase, I'll tryto play with `ClippingMediaSource`, thx.

Note: While the radio stream in the example is not seekable, the preroll is, you can write `mplayer -ss 5` for example, and jump to exactly 00:05 in the preroll. How `mplayer` is able to do this, I have no idea. I will get back with code if I am able to do something useful.

**Comment by tokland** [comment]
I've made some (unexpected) progress with what seems like a hack. First I clipped the streaming to skip the first 15 seconds:

```
new ClippingMediaSource(source, 15 * C.MICROS_PER_SECOND, 600000 * C.MICROS_PER_SECOND);
```

Ok, but as you said that could not work because the media was not flagged as seekable. So I fooled the method [ExtractorMediaPeriod.seekToUs](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/source/ExtractorMediaPeriod.java#L341) into thinking that it was seekable by commenting out this line:

```
// positionUs = seekMap.isSeekable() ? positionUs : 0;
```

And that's it, now the stream starts playing exactly at 15'' without any delay whatsoever and the ad is completely skipped. Not sure why this works.

**Comment by andrewlewis** [comment]
That change will cause the decode only flag to be set on samples before the start position specified. The effect is to load and skip the media before the start position, which sounds fine for your use case (the start position is small).
