### ISSUE TITLE
[Question] Adaptive bitrate behavior

### ISSUE THREAD

**Issue by alessandrojp** [google/ExoPlayer#3542]
Hi,

I put a log on `AdaptiveMediaSourceEventListener#onLoadCompleted` and I noticed that when it switches the bitrate, it is not getting the next .ts file from the last downloaded .ts

Seeing the log the .ts 0 took 0.2 and .ts 1 took almost 15 seconds, so the playback went to buffering state as expected because each .ts file has 10 seconds. After the .ts 1 started to play, it starts to download the same .ts 1 in low bitrate.

I would like to confirm why when it switched the bitrate, it downloaded the same .ts 1 if it is already being played making the playback goes to buffering state again when ts.1 (320kbps) finishes.
It should not download the next .ts 2 (128kbps)?

I'm using the default settings in the AdaptiveTrackSelection.

### Version of ExoPlayer being used
2.5.4

### Device(s) and version(s) of Android being used
Model: Google Pixel 
OS: 8.0.0

### A full bug report captured from the device
```
Player#onLoadCompleted bitrate:-1, loadDurationMs:205, bytesLoaded:358 speed:0.013324 Mbit/s url:https://xxx/master-track.m3u8 
Player#onLoadCompleted bitrate:-1, loadDurationMs:73, bytesLoaded:829 speed:0.086641 Mbit/s url:https://xxx/index.m3u8 
Player#onLoadCompleted bitrate:-1, loadDurationMs:89, bytesLoaded:829 speed:0.071065 Mbit/s url:https://yyy/index.m3u8 
Player#onLoadCompleted bitrate:320000, loadDurationMs:217, bytesLoaded:457404 speed:16.081639 Mbit/s url:https://yyyy/135161475-0.ts 
Player#onLoadCompleted bitrate:320000, loadDurationMs:14969, bytesLoaded:454772 speed:0.231788 Mbit/s url:https://yyy/475/135161475/1/5/135161475-1.ts 
Player#onLoadCompleted bitrate:128000, loadDurationMs:6410, bytesLoaded:183864 speed:0.218841 Mbit/s url:https://xxx/475/135161475/1/7/135161475-1.ts 
Player#onLoadCompleted bitrate:128000, loadDurationMs:6513, bytesLoaded:181796 speed:0.212958 Mbit/s url:https://xxx/475/135161475/1/7/135161475-2.ts 
Player#onLoadCompleted bitrate:128000, loadDurationMs:6402, bytesLoaded:183676 speed:0.218890 Mbit/s url:https://xxx/475/135161475/1/7/135161475-3.ts 
Player#onLoadCompleted bitrate:128000, loadDurationMs:6383, bytesLoaded:184428 speed:0.220441 Mbit/s url:https://xxx/475/135161475/1/7/135161475-4.ts 
Player#onLoadCompleted bitrate:128000, loadDurationMs:6569, bytesLoaded:183300 speed:0.212889 Mbit/s url:https://xxx/475/135161475/1/7/135161475-5.ts 
```

Thank you.

**Comment by ojw28** [comment]
Please see https://github.com/google/ExoPlayer/issues/3128#issuecomment-319618393.

**Comment by alessandrojp** [comment]
I'm going to take a look at the `EXT-X-INDEPENDENT-SEGMENTS`
Thanks!
