### ISSUE TITLE
java.lang.IllegalArgumentException, Decoder init failed: [REDACTED_DOMAIN_NAME], Format(video_eng=1052000, null, video/avc, 1052000, null, [1024, 576, -1.0], [-1, -1])

### ISSUE THREAD

**Issue by jiafei1986** [google/ExoPlayer#3546]
*** ISSUES THAT IGNORE THIS TEMPLATE WILL BE CLOSED WITHOUT INVESTIGATION ***

### Issue description
We are now using exoplayer v2.4.1 in our video app,  but now we saw many log in firebase.  just want to know what's the possible root cause for the below error log?
 
com.google.android.exoplayer2.d.b$a: Decoder init failed: [REDACTED_DOMAIN_NAME], Format(video_eng=1934000, null, video/avc, 1934000, null, [1280, 720, -1.0], [-1, -1])

### Reproduction steps
On my side, i cannot replicate this issue, i can only see these log on firebase.

### Link to test content
I will ask my colleague to provide it

### Version of ExoPlayer being used
2.4.1

### Device(s) and version(s) of Android being used
So far i checked the firebase, most devices model are SM-950F  SM-955F

### A full bug report captured from the device
arrow_drop_down
Caused by com.google.android.exoplayer2.e:
com.google.android.exoplayer2.d.b.a (MediaCodecRenderer.java:380)
com.google.android.exoplayer2.d.b.z (MediaCodecRenderer.java:367)
com.google.android.exoplayer2.d.b.b (MediaCodecRenderer.java:796)
com.google.android.exoplayer2.video.c.b (MediaCodecVideoRenderer.java:365)
com.google.android.exoplayer2.d.b.a (MediaCodecRenderer.java:494)
com.google.android.exoplayer2.i.f (ExoPlayerImplInternal.java:479)
com.google.android.exoplayer2.i.handleMessage (ExoPlayerImplInternal.java:308)
android.os.Handler.dispatchMessage (Handler.java:98)
android.os.Looper.loop (Looper.java:154)
android.os.HandlerThread.run (HandlerThread.java:61)
arrow_drop_down
Caused by com.google.android.exoplayer2.d.b$a: Decoder init failed: [REDACTED_DOMAIN_NAME], Format(video_eng=1934000, null, video/avc, 1934000, null, [1280, 720, -1.0], [-1, -1])
com.google.android.exoplayer2.d.b.z (MediaCodecRenderer.java:367)
com.google.android.exoplayer2.d.b.b (MediaCodecRenderer.java:796)
com.google.android.exoplayer2.video.c.b (MediaCodecVideoRenderer.java:365)
com.google.android.exoplayer2.d.b.a (MediaCodecRenderer.java:494)
com.google.android.exoplayer2.i.f (ExoPlayerImplInternal.java:479)
com.google.android.exoplayer2.i.handleMessage (ExoPlayerImplInternal.java:308)
android.os.Handler.dispatchMessage (Handler.java:98)
android.os.Looper.loop (Looper.java:154)
android.os.HandlerThread.run (HandlerThread.java:61)
arrow_drop_down
Caused by java.lang.IllegalArgumentException:
android.media.MediaCodec.native_configure (MediaCodec.java)
android.media.MediaCodec.configure (MediaCodec.java:1882)
com.google.android.exoplayer2.video.c.a (MediaCodecVideoRenderer.java:351)
com.google.android.exoplayer2.d.b.z (MediaCodecRenderer.java:356)
com.google.android.exoplayer2.d.b.b (MediaCodecRenderer.java:796)
com.google.android.exoplayer2.video.c.b (MediaCodecVideoRenderer.java:365)
com.google.android.exoplayer2.d.b.a (MediaCodecRenderer.java:494)
com.google.android.exoplayer2.i.f (ExoPlayerImplInternal.java:479)
com.google.android.exoplayer2.i.handleMessage (ExoPlayerImplInternal.java:308)
android.os.Handler.dispatchMessage (Handler.java:98)
android.os.Looper.loop (Looper.java:154)
android.os.HandlerThread.run (HandlerThread.java:61)

**Comment by botaydotcom** [comment]
Hi @jiafei1986 : It's very hard for us to debug/analyze this issue given the stack trace is obfuscated. Is there any way you could provide us with an un-obfuscated stack trace?


With that said, some of the symptoms here look a bit similar to issue: #3373 (I can't say for sure if they are really the same though), and we have fixed this issue on a more recent release (2.6.0). Maybe upgrading to a recent version can help?

**Comment by botaydotcom** [comment]
Another thing is: if you can provide the full bug report / logcat captured shortly after encountering the issue (with adb bugreport, as requested in the issue template), it will be helpful in debugging this as well. Thank you very much.

**Comment by botaydotcom** [comment]
Closing the issue as we don't have enough information to solve this.
