### ISSUE TITLE
Disabling subtitles in Exoplayer leaves the last caption left on the screen

### ISSUE THREAD

**Issue by samramez** [google/ExoPlayer#3547]
Hi, 
I've seen a number of issues regarding hiding and showing subtitles/captions but none was able to help me with my problem. In many of them, the issuer is referred to look and tweak the demo app which is also not helpful because it's not straightforward and I found no captioning in the demo app. Therefore, I end up using the following method (which I think there should be a simpler solution to this but lack of documentation and sources is not helping me find it) 

The task is simple, show and hide the subtitles in the video player. Inside my `VideoActivity.java` I have access to vtt Uri and from there I'm able to successfully side-load the subtitled video using the following code I got from the documention: https://google.github.io/ExoPlayer/guide.html

```java
// Build the video MediaSource.
MediaSource videoSource = new ExtractorMediaSource(videoUri, ...);
// Build the subtitle MediaSource.
Format subtitleFormat = Format.createTextSampleFormat(
    id, // An identifier for the track. May be null.
    MimeTypes.APPLICATION_SUBRIP, // The mime type. Must be set correctly.
    selectionFlags, // Selection flags for the track.
    language); // The subtitle language. May be null.
MediaSource subtitleSource = new SingleSampleMediaSource(subtitleUri, dataSourceFactory,subtitleFormat, C.TIME_UNSET);
// Plays the video with the sideloaded subtitle.
MergingMediaSource mergedSource = new MergingMediaSource(videoSource, subtitleSource);
```
Currently, the way I'm handling enabling and disabling subtitles is whenever status of captions is changed, I update some flags and then I call `releasePlayer()` and then `initializePlayer()`. 

Inside `initializePlayer()`  If captions are off I use:
 ```java 
player.prepare(mediaSource, !isTimelineStatic, !isTimelineStatic);
``` 
And if they're on, I'd use 
```java
player.prepare(mergedMediaSource)
```
My Problem:
When I turn off the captions, if a subtitle was on the screen at the time of clicking the turn-captions-off button, it will stay there even after I release and initiate the player again. The frozen caption is the very last caption on the screen before I release the player and it would stay frozen till the end of the video unless I turn captions on again.

Can you please help me fix this issue

**Comment by ojw28** [comment]
There are examples in the ExoPlayer demo app with captions. For example under `HLS -> Apple 16x9 basic stream`. You're probably using a `DefaultTrackSelector` in your app, and you should be calling methods on that object to disable/enable the subtitle, rather than completely releasing and re-preparing the player. The demo app's `TrackSelectionHelper` does this, although you can probably do something a bit simpler for your use case.

**Comment by samramez** [comment]
We use DASH streaming in our app and I can only access the subtitle via a link which ends with `.vtt` .

The example you referred to the demo app uses HLS streaming for showing captions.

**Comment by ojw28** [comment]
Using the `DefaultTrackSelector` to disable/enable the subtitle is exactly the same in both cases.

**Comment by samramez** [comment]
Thanks for your response @ojw28 
Can you please refer me to an example or sample which implements captions/subtitles using  `DefaultTrackSelector`. 
None of the methods for `DefaultTrackSelector` accepts any `Uri` or `List<Uri>` so I can pass the Uri to it.
Also, I'm not seeing any implementation of `DefaultTrackSelector` in the demo app which handles captions. If I'm missing something, I really appreciate if you give me more specific directions.

The only section in the [official documentation](https://google.github.io/ExoPlayer/guide.html) which speaks about implementing subtitles, is the method I'm currently using and unfortunately, it doesn't support disable/enable. This method also not used in the demo app.

**Comment by andrewlewis** [comment]
To toggle subtitles during playback without a releasing/recreating the player, prepare the player with a source that has subtitles (using your code snippet above) then disable/enable the text renderer in the track selector as required. The relevant code in the demo app is in `TrackSelectionHelper`.
