### ISSUE TITLE
SimpleExoPlayerView suface black when convertFromTranslucent.

### ISSUE THREAD

**Issue by Caij** [google/ExoPlayer#3549]
```
 public static void convertActivityFromTranslucent(Activity activity) {
        try {
            Method method = Activity.class.getDeclaredMethod("convertFromTranslucent");
            method.setAccessible(true);
            method.invoke(activity);
        } catch (Throwable t) {
        }
    }
```
when player playing,  call convertActivityFromTranslucent ,  the suface will black.

**Comment by ojw28** [comment]
You're using reflection to access a non-public API. This is not supported in general, and you should not do this*.

\* Granted, there are cases where pragmatically it can be useful to do this kind of thing. However you should do this at your own risk, and if something doesn't work it's up to you to find a way to resolve it. Anything you access in this way is also liable to stop working in future Android releases.

**Comment by andrewlewis** [comment]
Just to add to what Olly said: if you can find a way to do this with non-hidden APIs and it still doesn't work, it may be worth trying using `TextureView` (not `SurfaceView`).
