### ISSUE TITLE
How to play ima ad in HLS or MPD format?

### ISSUE THREAD

**Issue by ZohaibGhafoor** [google/ExoPlayer#3551]
how can i play hls or mpd format ads returned from dfp ?

**Comment by andrewlewis** [comment]
This is not currently supported, but planned for a release soon. Tracked by #3302.

**Comment by kinhdang** [comment]
Dear all !

Currently version 2.7.0 of Exoplayer, Any one know this case, please share.
we run demo apps but ads only show with ExtractorMediaSource.Factory, HlsMediaSource.Factory not show.

Thanks.
