### ISSUE TITLE
seekTo on ExoPlayer v.1.5.0

### ISSUE THREAD

**Issue by AHuminskyi** [google/ExoPlayer#3553]
Hi guys!

Kindly ask you to help with the issue which occurred. We have an Android application using **ExoPlayer v.1.5.0** implemented on the basis of SurfaceView. One of the functions of our app is to jump to the last video frame (function '**seek to**'). Unfortunately this can not be done because the last frame is not visible and can not be identified. Please tell if you faced such problem in older versions? Can our issue be solved if we update our Android application to the latest ExoPlayer 2.6.0?
P.S. Tested on different Android devices and Android versions above 16.
Many thanks in advance for your response.

**Comment by ojw28** [comment]
There is an open bug for us not displaying the last frame when seeking to the end of the content, [here](https://github.com/google/ExoPlayer/issues/2568). Marking as duplicate. We're unlikely to fix this soon, however.
