### ISSUE TITLE
Playbackcontrols controller showTimeoutMs should be updated even if the overlay is showing.

### ISSUE THREAD

**Issue by Jaydeeph** [google/ExoPlayer#3554]
This is not really a bug which why I'm not using the bug template, however, more if an enhancement. 

So when the playback controls UI is showing. Let's say you're using the default timeout which is 5000ms. You then change the timeout using "**setControllerShowTimeoutMs**" and set it to 0. Therefore it's there infinitely. Then playback UI will till timeout after 5000ms (5 seconds) rather than staying there. But if you show the playback UI again only then it's updated and will stay infinitely. Would it be possible to auto update the timeout even if the playback UI is showing or not? 
Currently, I'm setting the timeout and then calling ShowController or HideController to manually update it. But in the case of hideController, it doesn't make sense. 

For example, timeout is on 0. playback UI is showing. I change the timeout to 5000ms. The playback UI won't automatically update and disappear in 5 seconds. Rather I'd have to manually showControlls/hideControlls or touch the UI to actually update it. 

Hope all this made sense :P.

**Comment by botaydotcom** [comment]
Thanks for reporting. I think this can be classified as a bug, because after setControllerShowTimeoutMs, this should take effect immediately if the controller is already shown.

**Comment by Jaydeeph** [comment]
Ahh, I see. Thanks for the quick reply. It's a bug then :)

**Comment by ojw28** [comment]
Fixed in `dev-v2` branch. Will land in`2.7.x`.
