### ISSUE TITLE
The extension-cronet does not work with ./chromium-cronet/android/65.0.3286.0 version

### ISSUE THREAD

**Issue by nelson-xia** [google/ExoPlayer#3555]
I used the latest branch dev-v2 with the commit fbfa43f5a3ef11f5da115c439092b521564fb4fa and followed extensions/cronet/README.md. After downloaded the related jars and libraries, compiling with cronet extension seems fine, but when I run the demo with this extension, I got the following errors:
```
Information:Gradle tasks [:demo:assembleWithExtensionsDebug]
Error:com.android.builder.dexing.DexArchiveBuilderException: Failed to process /Users/gtxia/Research/ExoPlayer_V2/extensions/cronet/libs/cronet_impl_native_java.jar
Error:com.android.builder.dexing.DexArchiveBuilderException: Error while dexing org/chromium/base/process_launcher/ChildProcessServiceImpl.class
Error:com.android.dx.cf.code.SimException: invalid opcode ba (invokedynamic requires --min-sdk-version >= 26)
Error:Execution failed for task ':demo:transformClassesWithDexBuilderForWithExtensionsDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.dexing.DexArchiveBuilderException: com.android.builder.dexing.DexArchiveBuilderException: Failed to process /Users/gtxia/Research/ExoPlayer_V2/extensions/cronet/libs/cronet_impl_native_java.jar
Information:BUILD FAILED in 7s
```
Seems that the cronet version do not match the extension?

**Comment by tonihei** [comment]
This error message may appear if you use a Cronet version requiring Java 8 features and it's not enabled in your code. 

Can you make sure that both the gradle file of the ExoPlayer Cronet extension and the gradle file of your app have Java 8 features enabled?
The gradle files should contain 
```
android {
    ...
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
```

**Comment by ojw28** [comment]
Should we update `README.md` to document this?

**Comment by tonihei** [comment]
Yes, that would make sense to avoid confusion about this point.

**Comment by tonihei** [comment]
Closing issue, because the question has been answered and the README.md has been updated.
