### ISSUE TITLE
ima ad timeout issue.

### ISSUE THREAD

**Issue by ZohaibGhafoor** [google/ExoPlayer#3556]
is there any way to increase ima ad request timeout manually. because most of the time my player ad get timeout and not showing ad. or any other flexible way to guaranteed show the ad ?

my video ad size is 720p may be it can't load on slow or normal connection. but i require to show the ad on every connection.

**Comment by andrewlewis** [comment]
This isn't supported at the moment. The current plan is to add a way for apps to provide the AdsRequest (instead of creating it internally in `ImaAdsLoader`), at which point `AdsRequest.setVastLoadTimeout` could be used to override the default timeout of five seconds.
