### ISSUE TITLE
Exo Player decoding audio problem (Google Media Framework GMF)

### ISSUE THREAD

**Issue by zvonkokemperle** [google/ExoPlayer#356]
Hi,

I am using goole media framework (GMF) and I am encountering problems with the exo Player.

When the following video is played as an non-skippable video ad and the counter is counted to 0 when the content video should be played, then exo player is signaling the IMA sdk that the video is still playing. The counter is then counted to the negative and there is no way to watch the content video.

http://speed.pointroll.com/pointroll/media/asset/PointRollFlashDev/110157/PTR_2012_Video_640x360_480x270_384kbps_16secs.mp4

I have posted my problem on the IMA SDK Google Group here:
https://groups.google.com/forum/embed/?place=forum%2Fima-sdk&showsearch=true&showpopout=true&parenturl=https%3A%2F%2Fdevelopers.google.com%2Finteractive-media-ads%2Fcommunity#!topic/ima-sdk/EjCX_7641fs

and they said it is an Exo player bug and that I should post this issue here.

03-09 03:38:57.370  19932-20094/com.google.ads.interactivemedia.v3.samples.videoplayerapp W/AudioTrack﹕ Spurious audio timestamp: 593852, 88635038412, 88675467718
03-09 03:38:57.874  19932-20094/com.google.ads.interactivemedia.v3.samples.videoplayerapp W/AudioTrack﹕ Spurious audio timestamp: 593852, 88635038412, 88675972075
03-09 03:38:58.383  19932-20094/com.google.ads.interactivemedia.v3.samples.videoplayerapp W/AudioTrack﹕ Spurious audio timestamp: 593852, 88635038412, 88676480699
03-09 03:38:58.893  19932-20094/com.google.ads.interactivemedia.v3.samples.videoplayerapp W/AudioTrack﹕ Spurious audio timestamp: 593852, 88635038412, 88676991033

Thanks,

Zvonko

**Comment by fougere-mike** [comment]
I'm seeing a similar problem on a kindle fire tablet (same audio warnings). The audio will play for a second or two, then it cuts out.

I can provide more logs if needed.

**Comment by zvonkokemperle** [comment]
Hi,

I am not seeing this issue anymore after trying the build form the latest "dev" branch (4.17.2015) and using the MP4 extractor. The problem was still present when trying the build from 4.14.2015, but was not the same, the video stopped when there were 2 seconds left, so the negative counting was not the issue. Now it looks fine.
