### ISSUE TITLE
How to reduce the downloaded chunk number in HLS mode?

### ISSUE THREAD

**Issue by alordred** [google/ExoPlayer#3564]
Hey, I am trying to reduce the buffer when I play a HLS stream,
So, I dont want to download so many chunks (.ts file) from sever.
Is there any way to download only one chunk (.ts file) and store in buffer?

**Comment by alordred** [comment]
And please tell me is there any possible way to play ts.File randomly.
Randomly means can play 10.ts and then play 8.ts (every .ts file the I frame is the first frame)
How  can I play HLS chunks in reverse?

**Comment by AquilesCanta** [comment]
> I am trying to reduce the buffer when I play a HLS stream

You can play around with different loading parameters in `DefaultLoadControl`. Particularly, to reduce the buffer size you can override the default `maxBufferMs`. Keep in mind that this could have negative effects like frequent buffering and more network usage time.

> And please tell me is there any possible way to play ts.File randomly.

Not in HLS. You could manually put every TS file in a DynamicConcatenatingMediaSource and shuffle the contents (using `Player#setShuffleModeEnabled`) but the container format is not ideal, as in-file seeking would not be possible (only to the start of files). Preparation time could also be suboptimal.
