### ISSUE TITLE
Understanding exoplayer indepth

### ISSUE THREAD

**Issue by themavencoder** [google/ExoPlayer#3569]

**Comment by themavencoder** [comment]
1. What adaptation algorithm does exoplayer use; is it time based adaptive algorithm, buffer based adaptive algorithm or throughput based adaptive algorithm and is there a way I could lay my hands on the used algorithm?

2. The manifest file is sent from the cloud server to the dash client which is my player. Why can't the server just dynamically adapt the streaming rather than sending it to the client. 

3. DASH streaming is Dynamic Adaptive Streaming over HTTP. I'm making use of Microsoft Azure Media Services as my server because it supports DASH. I thought DASH streaming applies to only HTTP? Azure media services is HTTPS?

4. IF the video is in different representations on the server and each representations is in different segments. Does that mean that each segment has its own mpd attached to end of the segment?

5. When streaming occurs, with my understanding and with the materials I have read, Exoplayer requests for the video, depending on the network bandwidth and what other criterias does it use to select the representations that would be streamed?

**Comment by tonihei** [comment]
_For the general concept of DASH (questions 3,4):_
The server provides the same content in different representations (i.e. different video resolutions or audio bitrates). The content is split into segments which usually are a couple of seconds long to be able to switch representations during playback. To publish all the options to a player, the server also provides one single mpd file which describes the available representations and where to find the actual content. The player can then choose to download segments from the different representations as it likes. This concept is independent of the protocol used for the media (HTTP or HTTPS). 

_Client-side format selections (question 2):_
The player on the client side has the best knowledge about its local environment and bandwidth restrictions. Thus, it's usually better for the player to request the representation it thinks works best than for the server to guess what might work best for the player.

_Dynamic adaptation in ExoPlayer (quesitons 1,5):_
Exoplayer's default algorithm is throughput-based and uses the estimated bandwidth only (and some parameters controlling how often and when switching can occur). Have a look at [AdaptiveTrackSelection.java](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/trackselection/AdaptiveTrackSelection.java) to see our default implementation. You can provide your own adaptive track selection by passing in a custom track selection factory to the DefaultTrackSelector like so:
```
TrackSelector trackSelector = DefaultTrackSelector(new MyCustomTrackSelectionFactory());
Player player = ExoPlayerFactory.newSimpleInstance(..., trackSelector, ...);
```
