### ISSUE TITLE
Detect pause/resume in ExoPlayer

### ISSUE THREAD

**Issue by ghost** [google/ExoPlayer#3570]
I searched two days for this question in [github][1] but i can't find true answer . i want example for detecting `pause / resume` in `ExoPlayer > 2.x` . 
any one can give me an example ? i checked `onPlayerStateChanged` and problem not solved .

    onPlayerStateChanged   :   STATE_BUFFERING 
    onPlayerStateChanged   :   STATE_READY 

i just got this log from `onPlayerStateChanged` and this is not called in all times !

**Comment by ojw28** [comment]
`onPlayerStateChanged` is called whenever there's a change in playback state, including when the player is paused/resumed. Note there are two parts to the state: `playWhenReady` and `playbackState`. The player is playing if `playWhenReady == true && playbackState == Player.STATE_READY`. The states in other cases are described in the Javadoc for the `STATE_*` constants, [here](http://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/Player.html#STATE_BUFFERING).

**Comment by ghost** [comment]
Thank you very much 👍
