### ISSUE TITLE
Preload full subtitles from mkv (text track - S_TEXT/UTF8)

### ISSUE THREAD

**Issue by anonym24** [google/ExoPlayer#3572]
If I use external .srt subtitles and merge them with a video

`MediaSource mediaSourceWithText = new MergingMediaSource(videoMediaSource, textMediaSource);
exo.prepare(mediaSourceWithText);`

then in `TexRender` (https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/text/TextRenderer.java)

I can get all subtitles at any time position, so `subtitle.getEventTimeCount()` will return number of all events

But If I use only video (mkv) with internal subtitles (S_TEXT/UTF8)

`exo.prepare(mediaSourceVideoMkv); // just video source, there is no merging with external subtitles`

then  `subtitle.getEventTimeCount()` won't return numer of all event (all subtitles)

so `subtitle` instance will contain some strings (one/two) or not at all (null), it depends on current video position (preloaded buffer which contains data for small time range)

Is there any option to preload all subtitles when I start playing some video with internal subtitles?

So I want to `nextSubtitle` (https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/text/TextRenderer.java#L161) 
to be set only once and so it would contain all text for all time and would work the same as for external subtitles (`nextSubtitle = decoder.dequeueOutputBuffer(); ` is set only once during all playback for external subtitles)

p.s. you may guessing why do I need it, but it's just needed for one of my app functions (so I really need it)

**Comment by ojw28** [comment]
This is not supported, sorry.

**Comment by anonym24** [comment]
If you have time could you please suggest what should I do to implement this myself (local changes to exoplayer libraries)?

Mb extracting subtitles (text) from MKV in runtime somehow after exoplayer prepared video source and then re-init exoplayer source again - merging video and our extracted subtitles? `new MergingMediaSource(videoMediaSource, textMediaSourceExtractedFromMkv)`

Or it could be easier with some changes in core-library (change preload behavior for subtitles/text)?

**Comment by anonym24** [comment]
also added this question here https://stackoverflow.com/questions/47821715/preload-all-timings-text-of-internal-subtitles-buffer-for-text-render-decode
