### ISSUE TITLE
how to detect whether video contains audio track or not

### ISSUE THREAD

**Issue by Bhoomi-Zalavadiya** [google/ExoPlayer#3577]
Hello ,
I want to check if my video contains audio track or not. Based on that I want to add audio enable/disable functionality in my project

I am using  com.google.android.exoplayer:exoplayer:2.6.0 dependency in android studio 3..0.0

**Comment by AquilesCanta** [comment]
You can track the current tracks with Player#EventListener#OnTracksChanged and get the current ones with Player#getCurrentTrackGroups(). If you go through the track groups you can look for the type. If you additionally want to check if any of the audio tracks was selected, then Player#getCurrentTrackSelections() is the place to look at.
