### ISSUE TITLE
Need somthing like YoutubeMediaSource to play youtube videos 

### ISSUE THREAD

**Issue by varun7952** [google/ExoPlayer#3580]
Since Exoplayer release there is no feature to play valid Youtube video in Exoplayer. If we need to play youtube video, we need to use Youtube API which stream videos in separate player.  Isn't easy for developer and other people to use single player for all media then use multiple player. #

**Comment by ojw28** [comment]
Please see https://github.com/google/ExoPlayer/issues/2160.
