### ISSUE TITLE
Configure ExoPlayer To Keep Played Buffer

### ISSUE THREAD

**Issue by rustyshelf** [google/ExoPlayer#3583]
### Issue description
I searched all the documentation and previous issues and couldn't find a way to do this. What we'd like to be able to do is to specify how much of a buffer of previously played content ExoPlayer holds on to. So say you're playing a 2 hour MP3 file and you're 25 minutes in. If you skip back 10 seconds it would be nice to have that data still there and ready to play instantly. Currently what seems to happen is that the player re-buffers from the position you've seeked back to causing a pause in playback. In our case we'd probably set this to the equivalent of maybe 5 minutes of audio.

This would make for a better listener playback experience and probably result in significantly less data used for people that skip back a lot.

### Reproduction steps
- Stream a 2 hour MP3 up to 25 minutes
- Seek back 10 seconds
- The player pauses while it re-buffers this content

### Version of ExoPlayer being used
ExoPlayer 2.5.4

### Device(s) and version(s) of Android being used
All the devices we've tested on.

**Comment by ojw28** [comment]
On the dev-v2 branch we support specifying a back-buffer as part of `LoadControl`. Specifically, see `getBackBufferDurationUs` and `retainBackBufferFromKeyframe` (for an audio app you probably only care about the first one). If you otherwise want to use `DefaultLoadControl`, it should be possible to extend it and override just these methods.

**Comment by satyres** [comment]
@ojw28  Can you please explain more . Thanks
@rustyshelf Did you find a solution for this problem , i need the same feature for a radio stream , to be able to back for 10 second or more.
Thank you so much for your help

**Comment by rustyshelf** [comment]
@satyres the properties @ojw28 mentioned are in the development branch. Only he would be able to tell you when they are scheduled to go into a production build but they are all there as described.
