### ISSUE TITLE
Unable do play content after upgrading to ExoPlayer 2.6.0 from 1.2.X

### ISSUE THREAD

**Issue by Lezherus** [google/ExoPlayer#3585]
We were using ExoPlayer 1.2.X for a while now and decided to upgrade to 2.6.0, but our content won't play, returning some toasts:

"Media includes video tracks, but none are playable by this device"

and

"Media includes audio tracks, but none are playable by this device"

We tried playing in several emulators from Android 6 to 8, and on a Samsung Galaxy S8+ running Android 7.0

How to reproduce the issue:

Player Version: 2.6.0
Device: Pixel XL - API 24

1 - Downloand ExoPlayer version 2.6.0 release.

2 - Add the given media uri and drm_license_url using the drm_scheme "widevine" to the media.exolist.json.

3 - Run the ExoPlayer and try to play the media.

The media uri, proxy url and bugreport file were sent to dev.exoplayer@gmail.com

Thank you in advance for the help!

**Comment by ojw28** [comment]
This happens because we're concluding from the manifest that the stream only supports PlayReady DRM. This is because the manifest contains ContentProtection elements for PlayReady, but not for Widevine. Adding ContentProtection elements for Widevine should resolve this issue.

**Comment by Lezherus** [comment]
@ojw28 Thank you for the prompt answer! But now I'm wondering, if that's the case, why does it works on 1.2.X? Did ExoPlayer use to support PlayeReady but now it doesn't?

**Comment by ojw28** [comment]
Both V1 and V2 support PlayReady where supported by the underlying platform. PlayReady is only a requirement for AndroidTV devices, however. Most Android mobile devices don't provide support.

The reason V2 fails and V1 doesn't is just that V1 performs fewer checks prior to attempting to start playback. Which meant it was prone to try and play content in an unsupported DRM scheme and fail in an arbitrary way, but also that it was able to successfully play content in a supported DRM scheme even the scheme was missing from the manifest.

**Comment by Lezherus** [comment]
@ojw28 Thank you for the clarification. But we tried using another manifest with the widevine ContentProtection element included and it still doesn't works, but now it returns a different error.

I e-mailed you the bugreport and new manifest link, could you take a look, please?

**Comment by ojw28** [comment]
The updated manifest plays fine if you add the following line of JSON:
```
"extension": "mpd"
```
So it looks like:"
```
{
"name": "XXX",
"uri": "XXX",
"drm_scheme": "widevine",
"drm_license_url": "XXX"
"extension": "mpd"
},
```
The demo app tries and automatically infer the content type from the extension, but in this case the extension is "ism" and the demo app infers that it's a SmoothStreaming stream. Adding the extra line explicitly tells the demo app what the content type is.

**Comment by Lezherus** [comment]
@ojw28 Indeed, it played fine, thank you very much for the help! I must admit that I'm impressed with how fast you guys reply to the issues, congratulations on the amazing job, and please keep it up!
