### ISSUE TITLE
Can we manage focus and click listner of skip ad in case of tv.

### ISSUE THREAD

**Issue by shailesh2208** [google/ExoPlayer#3586]
Can we manage focus and click listener of **Skip ad** button when we playing ads with ExoPlyaer  IMA sdk on Amazon Fire TV or Android TV using **DPAD** key of remote?

**Comment by andrewlewis** [comment]
What kind of management did you have in mind? We have a workaround that should focus the skip button on Android TV devices: #3258.

**Comment by shailesh2208** [comment]
During playing Skipable ad, when Skip ad button visible on that time we want that by pressing dpad down button, skip ad button should be selected, when we press dpad up button, skip button should be un selected. During selected time when we press dpad OK(Center) button, ad should be skip.

**Comment by andrewlewis** [comment]
What's the behavior you're seeing on Android TV at the moment, and what version of ExoPlayer are you using?

**Comment by shailesh2208** [comment]
I am using 2.6.1 version and testing on Fire tv device and unable to get focus on skip button.
https://github.com/amzn/exoplayer-amazon-port/commit/642e95beaaeb57421ee4da43e0b72c3293c3191c

**Comment by andrewlewis** [comment]
If you press the OK button while the 'Skip ad' button is on screen, does the ad get skipped? If not, please try in the demo app on Android TV and let us know what you see. We can't really support FireOS-specific issues, but this is expected to work on Android TV at least.

**Comment by shailesh2208** [comment]
Yes its working fine for Android TV. Do you have any alternate solution of Amazon Fire TV?

**Comment by andrewlewis** [comment]
I'm afraid we don't. You could investigate why the workaround we have for Android TV (f2aed7186e9c47ddc55456c5f5bbeb5cb3100988) is not working on Fire TV. If there's a reasonably simple fix that makes it work on both platforms please let us know we can probably update it. Thanks!

**Comment by Viveek** [comment]
Does anyone can help me for Fire TV  'Skip ad' button focus issue?
