### ISSUE TITLE
Add GIF extractor

### ISSUE THREAD

**Issue by DSteve595** [google/ExoPlayer#3589]
### Issue description
GIFs can't be played with ExoPlayer. No extractor is able to read them.

### Link to test content
https://i.redd.it/njtj70s61s301.gif

### Version of ExoPlayer being used
2.6.0

**Comment by andrewlewis** [comment]
GIFs are very different from the kind of media ExoPlayer handles at the moment, so this would likely be a lot of work. Using a `WebView` or a library like [glide](https://github.com/bumptech/glide) is probably a better option. See also #2874.
