### ISSUE TITLE
I dont know how to compile native libraries C++ in android 

### ISSUE THREAD

**Issue by MiriSy** [google/ExoPlayer#3593]
i have android studio 3.0 . when i build exo player the native libraries not compiled.
any help ?

**Comment by AquilesCanta** [comment]
Which native libraries?

**Comment by MiriSy** [comment]
extensions like ffmpeg ...

**Comment by AquilesCanta** [comment]
https://github.com/google/ExoPlayer/tree/release-v2/extensions/ffmpeg

**Comment by MiriSy** [comment]
yes in that link i mean. i read readme.md but  i dont understand how to make , i have windows os

**Comment by AquilesCanta** [comment]
Please see #3127.
