### ISSUE TITLE
In the Android SDK 5.1 full screen switch, the video screen has 2 seconds delay

### ISSUE THREAD

**Issue by yangchaojiang** [google/ExoPlayer#3598]
In Android SDK 5.1 the following device version, Samsung s4 version: 4.3
Huawei che1, cl20, version: 4.4, Meizu, version 4.4.2, Huawei SCL-TL00 version 5.1 devices such as full-screen switch, the video screen with 2 seconds Caton,
![test](https://user-images.githubusercontent.com/13806413/34067725-b882c7a0-e268-11e7-8eec-58ea967b2b1d.gif)

**Comment by andrewlewis** [comment]
Are you changing the output video surface as part of the transition to full screen? Please read #677 and issues referenced there.

If you need this to work smoothly before Android Marshmallow, one thing you could try is putting the player's output surface/texture view on top of your UI layout, so you can just resize it when going full screen, to avoid switching surface.

**Comment by yangchaojiang** [comment]
Full screen playback switch cross screen processing in Android Marshmallow under Caton phenomenon

![device-2017-12-21-115956](https://user-images.githubusercontent.com/13806413/34240247-8a562c54-e647-11e7-903a-2c58874f8d5c.gif)

**Comment by andrewlewis** [comment]
Please could you provide more detail about what your application does when the full screen button is pressed?

**Comment by yangchaojiang** [comment]
Duplicate of #1845   [Provide examples](https://github.com/google/ExoPlayer/issues/1845#issuecomment-328724351)

code ：
    private void openFullscreenDialog() {
        ((ViewGroup) mExoPlayerView.getParent()).removeView(mExoPlayerView);
        mFullScreenDialog.addContentView(mExoPlayerView, new ViewGroup.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT));
        mFullScreenIcon.setImageDrawable(ContextCompat.getDrawable(MainActivity.this, R.drawable.ic_fullscreen_skrink));
        mExoPlayerFullscreen = true;
        mFullScreenDialog.show();
    }

    private void closeFullscreenDialog() {
        ((ViewGroup) mExoPlayerView.getParent()).removeView(mExoPlayerView);
        ((FrameLayout) findViewById(R.id.main_media_frame)).addView(mExoPlayerView);
        mExoPlayerFullscreen = false;
        mFullScreenDialog.dismiss();
        mFullScreenIcon.setImageDrawable(ContextCompat.getDrawable(MainActivity.this, R.drawable.ic_fullscreen_expand));
    }


private void initFullscreenButton() {

    PlaybackControlView controlView = mExoPlayerView.findViewById(R.id.exo_controller);
    mFullScreenIcon = controlView.findViewById(R.id.exo_fullscreen_icon);
    mFullScreenButton = controlView.findViewById(R.id.exo_fullscreen_button);
    mFullScreenButton.setOnClickListener(new View.OnClickListener() {
        @Override
        public void onClick(View v) {
            if (!mExoPlayerFullscreen)
                openFullscreenDialog();
            else
                closeFullscreenDialog();
        }
    });
}

**Comment by yangchaojiang** [comment]
Can this problem be repaired?

**Comment by ojw28** [comment]
Let's use https://github.com/google/ExoPlayer/issues/1845 to track implementing, and providing guidance on, seamless transitions to and from fullscreen.
