### ISSUE TITLE
HTTP stream failed over 3G network

### ISSUE THREAD

**Issue by gemiren** [google/ExoPlayer#36]
I am using the demo app to stream from the url http://50.31.154.35:80/wnycfm with DefaultRendererBuilder. The live streaming works fine with wifi connection. However, if wifi is off or not connected, the live streaming always stops after playing about one minute. This happens on both Nexus 5 (android 4.4.4) and S5 (android 4.4.2), so it is not a device related issue. 

The logcat outputs suggests the buffer is underrun and end of stream is reached. 
08-24 12:50:51.775: I/ExoPlayerImpl(29671): Init 1.0.12
08-24 12:51:12.085: I/OMXClient(29671): Using client-side OMX mux.
08-24 12:51:12.085: E/OMXMaster(29671): A component of name 'OMX.qcom.audio.decoder.aac' already exists, ignoring this one.
08-24 12:51:12.095: I/OMXClient(29671): Using client-side OMX mux.
08-24 12:51:12.095: E/OMXMaster(29671): A component of name 'OMX.qcom.audio.decoder.aac' already exists, ignoring this one.
08-24 12:52:42.805: W/AudioTrack(29671): releaseBuffer() track 0x4a38ea88 name=s:185;n:1;f:-1 disabled due to previous underrun, restarting
08-24 12:52:42.805: I/NuCachedSource2(29671): ERROR_END_OF_STREAM

Any help is appreciated!

**Comment by ojw28** [comment]
Closing.
