### ISSUE TITLE
persistent caching

### ISSUE THREAD

**Issue by davidlrzh** [google/ExoPlayer#360]
I'd like to implement a persistent cache for streamed video data in my app. Using CacheDataSource in ExoPlayer seems to be a good solution, but I can't find how. Anyone knows?

**Comment by ojw28** [comment]
Unless you happen to be implementing DASH with single-segment media, like YouTube does, then chances are CacheDataSource wont work for you yet. There's an issue tracking enhancing it to support other use cases here: #322 .
