### ISSUE TITLE
Audio not playing on HD mp4

### ISSUE THREAD

**Issue by tsmathavan** [google/ExoPlayer#3602]
The attached mp4 not working on Exo
player. Video only showing. Audio not playing.
[v3.zip](https://github.com/google/ExoPlayer/files/1565462/v3.zip)

**Comment by ojw28** [comment]
There's no (audible) audio when this sample is played in VLC, Quicktime or Chrome either, so this appears to be working as intended. There is an audio track in the file, but I think it's probably just silent.
