### ISSUE TITLE
Audio cut off from ConcatenatingMediaSource

### ISSUE THREAD

**Issue by mortenesbensen** [google/ExoPlayer#3608]
### Issue description
When combining two ExtractorMediaSources; one created from a byte array and one created from a url into a ConcatenatingMediaSource, the audio from the first media source is cut off at the end.

### Reproduction steps
Create two ExtractorMediaSources; one from a byte array of binary audio, one from a url. Add both to a ConcatenatingMediaSource or DynamicConcatenatingMediaSource and play. Audio from the first media source created from a byte array will be slightly cut off.

### Link to test content
For first media source: https://drive.google.com/open?id=1Kx6qg8Uy5urz3BF4V2QG4ofbkLXxThz2 (read to a byte array)

For second media source: http://open.live.bbc.co.uk/mediaselector/5/redir/version/2.0/mediaset/audio-nondrm-download/proto/http/vpid/p05r54nh.mp3

### Version of ExoPlayer being used
2.6.0

### Device(s) and version(s) of Android being used
Samsung Galaxy S6 Android 7.0 and Pixel 2 Android 8.1

### A full bug report captured from the device
https://drive.google.com/open?id=1_ELH7IYl-GLaZkwOtvrL3DQuS5a-tmfz

**Comment by andrewlewis** [comment]
These sources appear to be in different formats: the first is 8 kHz mono, while the second is 44.1 kHz stereo. I think what's going on is that we have to reconfigure the underlying AudioTrack at the point of transitioning from the first source to the second, which causes some media to be dropped. To get the streams to play seamlessly, please try using the same format for the two sources -- perhaps you can encode the first media source as 44.1 kHz stereo?
