### ISSUE TITLE
How to detect ExoPlayer playback smooth or not?

### ISSUE THREAD

**Issue by crossle** [google/ExoPlayer#361]

**Comment by ojw28** [comment]
What does "smooth" mean. There are a bunch of things you can look at.

1. Use [ExoPlayer's listener](http://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer/ExoPlayer.Listener.html). Note - The state constants are actually defined [here](http://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer/ExoPlayer.html).

2. You can also attach listeners to many of the individual components. For example, you can attach a listener to the video renderer that will count the number of dropped frames. See [here](http://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer/MediaCodecVideoTrackRenderer.EventListener.html).

The rest, you'll have to figure out for yourself ;).

**Comment by crossle** [comment]
Thanks
