### ISSUE TITLE
Question about track selection

### ISSUE THREAD

**Issue by pstambrecht** [google/ExoPlayer#3610]
Question:
What is the best way (right way) how to get and display list of available video qualities, audio tracks and subtitles? 

Now I:
1) Listen changes in onTrackChanged(...) method (Player.EventListener interface)
2) Iterate over all track groups and check theirs Formats to determine which is video track group (format mime type starts with "video" string)
3) Post this TrackGroup to Activity to display available formats

I use the same flow for audio and subtitles too.

But I thing I've not understood it well because it is lots of for-cycles.

**Comment by andrewlewis** [comment]
Please have a look at [`TrackSelectionHelper`](https://github.com/google/ExoPlayer/blob/505d5cd/demos/main/src/main/java/com/google/android/exoplayer2/demo/TrackSelectionHelper.java) which is used by the demo app to show a track selection dialog. The `showSelectionDialog` method takes a renderer index, and you can use `player.getRendererType` to get the type of each renderer (see also [`PlayerActivity.updateButtonVisibilities`](https://github.com/google/ExoPlayer/blob/505d5cd/demos/main/src/main/java/com/google/android/exoplayer2/demo/PlayerActivity.java#L581)).
