### ISSUE TITLE
Broken Playlist

### ISSUE THREAD

**Issue by num47** [google/ExoPlayer#3611]
While i have created a playlist i found that if any link of that playlist is not active then the whole playlist of that sample playlist does not work. If i had removed that broken link then that playlist was working but otherwise not. I had changed the position of that link - sometimes at the top, sometimes at the bottom, sometimes at the middle. The link was not working unless i moved the broken link removed from that playlist. 

And, on a separate topics - 
I am new to this coding thing. I was searching for a way to assign a picture for the name of the link. But i could not find a way anywhere. Can anyone please give me a direction how can i do this? 

Thanks

**Comment by andrewlewis** [comment]
Can you just handle the player error and update the playlist to remove the broken entry? Please could you describe with a bit more detail exactly what you're doing, what happens and what you expect to happen?

**Comment by num47** [comment]
i had added various video link. user have to click on the name of the link to watch that video. So, every time they want to view a different link that need to go back to the video list and then choose a different video. Some people might not like this and would have wish to watch the videos by clicking the next button. So, i had made a different playlist for whose who want to watch those videos by clicking next button. But, as i was saying, if any link got broken then the whole playlist broke down. 

I am giving you an example of the playlist
```
[
  {
    "name": "Sample Video",
    "samples": [
    {
        "name": "Sample Video No.1",
        "uri": "sample video link 1"
    },
    {
		"name": "Sample Video No.2",
		"uri": "sample video link 2"
	},
{
		"name": "Sample Video No.3",
		"uri": "sample video link 3"
	},
    {
        "name": "Sample Video No.4",
        "uri": "sample video link 4"
    },
    {
        "name": "Sample Video No.5",
        "uri": "sample video link 5"
    },
    {
        "name": "Sample Playlist",
"playlist": [
   {
        "uri": "sample video link 1"
    },
{
        "uri": "sample video link 2"
    },
{
        "uri": "sample video link 3"
    },
{
        "uri": "sample video link 4"
    },
{
        "uri": "sample video link 5"

    }
]
}
   
  ]
 }    
]
```

At first, i give the option to view the links separately so that viewer can choose as he/she wish. Then, i gave a playlist of the same video for those who wish to watch all the videos one by one. If they choose the playlist then they have a choice to go to the next video by pressing next button.

**Comment by andrewlewis** [comment]
Can you just handle the player error and update the playlist to remove the broken entry?

**Comment by num47** [comment]
Mate, as i was saying, i am really new to this coding thing. That might be possible but i have no idea what to edit - where to edit.

**Comment by tonihei** [comment]
You should have a `player.prepare(mediaSource)` somewhere in your code which prepares and starts the player.  This `mediaSource` is most likely a `ConcatenatingMediaSource` or a `DynamicConcatenatingMediaSource` created before that. When these concatenated media sources are created, they use a list of single media sources (corresponding to the playlist).

In case one of your playlist items fails to play, you'll get a notification by a call to `eventListener.onPlayerError`. When this happens, you can re-prepare the player with a new call to `player.prepare(mediaSource)` and a newly created concatenated media source without the failing item. You can check `player.getCurrentWindowIndex()` in the error callback to find out the index of the failing item.

Does that help you to find the right places?

**Comment by num47** [comment]
Thanks a lot tonihei. gonna try this.
