### ISSUE TITLE
how can I check buffer size after buffering?

### ISSUE THREAD

**Issue by kimkyuhwan** [google/ExoPlayer#3612]
Is there a way to check the size of the buffer after reading it from the Exoplayer?

**Comment by andrewlewis** [comment]
Does `Player.getBufferedPosition()` provide the information you need? If not, please could you elaborate on which buffer you're talking about, and what you mean by reading it?

**Comment by kimkyuhwan** [comment]
Thank you for answer :-).  But, It is not the answer I wanted.
This is my question:
 When max_buffer_ms, min_buffer_ms, and playback_buffer_ms are fixed in the exo-player, the server loads the chunks for a same amount of time regardless of the video quality. 
 I am wondering how to obtain the physical size of the chunks read at this time
 (ex 240p - > 180kb, 360-> 300kb ... 1080p ->2.1MB )

**Comment by tonihei** [comment]
When you set up your adaptive media source you should be able to pass in a [`AdaptiveMediaSourceEventListener`](http://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/source/AdaptiveMediaSourceEventListener.html) to the media source. This listener gets notifications whenever a load starts, ends, or fails. And it includes all times, number of loaded bytes etc.

**Comment by kimkyuhwan** [comment]
Thank you for your help! Have a nice day :-)
