### ISSUE TITLE
Question : How to handle ConcatenatingMediaSource playlist item error?

### ISSUE THREAD

**Issue by rranjithkumar100** [google/ExoPlayer#3613]
I am using ConcatenatingMediaSource to play list of videos. 

I have 5 videos. So add these videos with help of ConcatenatingMediaSource.
If 5 videos have valid URL -> no problem it played perfectly.

**My problem :**  

Incase if one video invalid URL like 404 error. **onPlayerError(ExoPlaybackException error)** method called &
Player stopped & other videos not playing.

For ex: If I give invalid url for 3rd video. It return error in 3rd video & my **4th, 5th videos not playing**

But I want to play the other videos incase it have any error.

**My code;**
Iterate for loop & add videos using ConcatenatingMediaSource

    MediaSource movieMediaSource = mMyExoPlayerMovie.getMediaSourceFromUrl(this, mMovieUrls.get(index));
    concatenatingMediaSource.addMediaSource(index, movieMediaSource);

Prepare code:

        mExoPlayer.prepare(mediaSource);

If any more details let me know.

**Comment by andrewlewis** [comment]
Can you just re-prepare the player with a new concatenation that omits the missing items?

This seems to be similar to #3611.
