### ISSUE TITLE
ExoPlayer r2.6.0 - could not find dependency  "com.google.android.exoplayer:exoplayer:r2.6.0"

### ISSUE THREAD

**Issue by lazarvgd** [google/ExoPlayer#3616]
Hi, I have wanted to update a exoplayer to newer version(from 2.5.4 to 2.6.0) .
I used this dependency : 
   ` compile 'com.google.android.exoplayer:exoplayer:r2.6.0'`

and I have got the message:

`Could not find dependency "com.google.android.exoplayer:exoplayer:r2.6.0"`

Can you please tell me is that the problem with your repo or I am using wrong dependency?

Thanks

**Comment by eneim** [comment]
@lazarvgd Change "r2.6.0" --> "2.6.0" and you are done.
