### ISSUE TITLE
[Support] Play only a block for preview video

### ISSUE THREAD

**Issue by mdtuyen** [google/ExoPlayer#3617]
I use Exoplayer for my project.
The first I have a full video.
However I want support preview.
Example:
Video long is 100min
I want to play preview from 5minute to 7 minute and that present on timebar duration is 00:00 to 02:00

How do I do that?

**Comment by tonihei** [comment]
Have you tried using a [ClippingMediaSource](http://google.github.io/ExoPlayer/doc/reference/index.html?com/google/android/exoplayer2/source/ClippingMediaSource.html)? It allows to wrap a normal media source and specify a start and end position. The timebar should automatically adapt to the new length.

**Comment by mdtuyen** [comment]
thanks
