### ISSUE TITLE
How can we make the scrubber move when we drag the scrubber instead of clicking on the seek bar

### ISSUE THREAD

**Issue by keshav1139** [google/ExoPlayer#3619]
### Issue description
Scrubber in seek bar is not draggable on the click events are triggered when clicked on seek bar.
How can we change the position of video by dragging the seekbar

### Reproduction steps
Play the video and try dragging the scrubber

### Version of ExoPlayer being used
4.1.0

### Device(s) and version(s) of Android being used
All Android devices

**Comment by tonihei** [comment]
The scrubber is draggable for me in our demo app. Can you give more details on why you think it's not draggable? And how I could reproduce your issue?

Also there is no ExoPlayer 4.1.0  - our current release version is 2.6.0.

**Comment by shwetha-DabKick** [comment]
I am extremely sorry this is in exomedia and not exo player, please close the issue. Regret the inconvenience caused.

**Comment by keshav1139** [comment]
I am extremely sorry this is in exomedia and not exo player, please close the issue. Regret the inconvenience caused.
