### ISSUE TITLE
MPEG DASH init segment can have more than one track

### ISSUE THREAD

**Issue by hodzic** [google/ExoPlayer#362]
It appears ExoPlayer library takes the first track in an init segment. This may not work if the init segment includes more than one track in arbitrary order.

I could provide a diff that resolves the issue.

**Comment by ojw28** [comment]
What are the other tracks that would be in the init segment?

**Comment by hodzic** [comment]
It is possible that each init segment includes both audio and video tracks. It is redundant, but does not seem disallowed by the MPEG DASH spec.

Here's a sample content: http://content.intertrust.com/dash/sintel/cleartext-split/mpd.xml

**Comment by hodzic** [comment]
Oops, didn't mean to close...

**Comment by ojw28** [comment]
In that case, is the problem that the video tracks contain audio as well? How would you propose fixing the issue (short of adding full support to the extractor for multiple tracks - which is something we want to do, but not quite yet).

**Comment by hodzic** [comment]
I have a relatively short diff I could share.

Basically, the public FragmentedMp4Extractor(int workaroundFlags, String mimeType) get the mimeType, it get passed down from the representation (where it's mandatory), and then moov parsing takes a track that matches the mimeType to the track type (in a somewhat fuzzy way).

Want the diff?

**Comment by ojw28** [comment]
I'd really like to avoid feeding stuff into the extractor that it shouldn't need to know about. It's also unclear to me whether the extractor will properly skip sample data that corresponds to the other tracks (although perhaps this just works already, I'm not sure).

It would be good to see the diff, thanks. Although I'd be inclined to say we wont do anything to fix this until we add proper multi-track support to the fmp4 extractor. Obviously content shouldn't be encoded in this way, regardless of whether the spec allows it, so it's not hugely important to fix quickly.

**Comment by hodzic** [comment]
There could be better way of doing it. But basically, I'd like to be able to instantiate the FragmentedMp4Extractor for a specific track type.

Hopefully the diff clears the communication. Don't see a way to attach the diff, so here:

diff --git a/library/src/main/java/com/google/android/exoplayer/chunk/parser/mp4/FragmentedMp4Extractor.java b/library/src/main/java/com/google/android/exoplayer/chunk/parser/mp4/FragmentedMp4Extractor.java
index d6229cf..801b0f6 100644
--- a/library/src/main/java/com/google/android/exoplayer/chunk/parser/mp4/FragmentedMp4Extractor.java
+++ b/library/src/main/java/com/google/android/exoplayer/chunk/parser/mp4/FragmentedMp4Extractor.java
@@ -124,6 +124,7 @@ public final class FragmentedMp4Extractor implements Extractor {
     CONTAINER_TYPES = Collections.unmodifiableSet(atomContainerTypes);
   }
 
+  private final String mimeType;
   private final int workaroundFlags;
 
   // Parser state
@@ -150,15 +151,16 @@ public final class FragmentedMp4Extractor implements Extractor {
   private Track track;
   private DefaultSampleValues extendsDefaults;
 
-  public FragmentedMp4Extractor() {
-    this(0);
+  public FragmentedMp4Extractor(String mimeType) {
+    this(0, mimeType);
   }
 
   /**
    * @param workaroundFlags Flags to allow parsing of faulty streams.
    *     {@link #WORKAROUND_EVERY_VIDEO_FRAME_IS_SYNC_FRAME} is currently the only flag defined.
    */
-  public FragmentedMp4Extractor(int workaroundFlags) {
+  public FragmentedMp4Extractor(int workaroundFlags, String mimeType) {
+    this.mimeType = mimeType.toLowerCase();
     this.workaroundFlags = workaroundFlags;
     parserState = STATE_READING_ATOM_HEADER;
     atomHeader = new ParsableByteArray(Mp4Util.ATOM_HEADER_SIZE);
@@ -363,6 +365,17 @@ public final class FragmentedMp4Extractor implements Extractor {
     return 0;
   }
 
+  private boolean trackMatchesMimeType(Track t) {
+    if (mimeType == null) return true;
+    if (mimeType.startsWith("audio")) {
+      return t.type == Track.TYPE_AUDIO;
+    } else if (mimeType.startsWith("video")) {
+      return t.type == Track.TYPE_VIDEO;
+    }
+    // otherwise, don't know this mime type, so take any track
+    return true;
+  }
+
   private void onMoovContainerAtomRead(ContainerAtom moov) {
     List<Atom.LeafAtom> moovChildren = moov.leafChildren;
     int moovChildrenSize = moovChildren.size();
@@ -380,8 +393,16 @@ public final class FragmentedMp4Extractor implements Extractor {
     }
     ContainerAtom mvex = moov.getContainerAtomOfType(Atom.TYPE_mvex);
     extendsDefaults = parseTrex(mvex.getLeafAtomOfType(Atom.TYPE_trex).data);
-    track = CommonMp4AtomParsers.parseTrak(moov.getContainerAtomOfType(Atom.TYPE_trak),
-        moov.getLeafAtomOfType(Atom.TYPE_mvhd));
+    LeafAtom mvhd = moov.getLeafAtomOfType(Atom.TYPE_mvhd);
+    // Pick the first matching track
+    for (ContainerAtom ca : moov.containerChildren) {
+        if (ca.type != Atom.TYPE_trak) continue;
+        Track t = CommonMp4AtomParsers.parseTrak(ca, mvhd);
+        if (trackMatchesMimeType(t)) {
+            track = t;
+            break;
+        }
+    }
   }
 
   private void onMoofContainerAtomRead(ContainerAtom moof) {
diff --git a/library/src/main/java/com/google/android/exoplayer/dash/DashChunkSource.java b/library/src/main/java/com/google/android/exoplayer/dash/DashChunkSource.java
index 2a1d768..d20abce 100644
--- a/library/src/main/java/com/google/android/exoplayer/dash/DashChunkSource.java
+++ b/library/src/main/java/com/google/android/exoplayer/dash/DashChunkSource.java
@@ -200,7 +200,7 @@ public class DashChunkSource implements ChunkSource {
       maxWidth = Math.max(formats[i].width, maxWidth);
       maxHeight = Math.max(formats[i].height, maxHeight);
       Extractor extractor = mimeTypeIsWebm(formats[i].mimeType) ? new WebmExtractor()
-          : new FragmentedMp4Extractor();
+          : new FragmentedMp4Extractor(formats[i].mimeType);
       representationHolders.put(formats[i].id,
           new RepresentationHolder(representations[i], extractor));
     }
diff --git a/library/src/main/java/com/google/android/exoplayer/smoothstreaming/SmoothStreamingChunkSource.java b/library/src/main/java/com/google/android/exoplayer/smoothstreaming/SmoothStreamingChunkSource.java
index 6e04658..d738434 100644
--- a/library/src/main/java/com/google/android/exoplayer/smoothstreaming/SmoothStreamingChunkSource.java
+++ b/library/src/main/java/com/google/android/exoplayer/smoothstreaming/SmoothStreamingChunkSource.java
@@ -166,7 +166,7 @@ public class SmoothStreamingChunkSource implements ChunkSource {
       int trackType = streamElement.type == StreamElement.TYPE_VIDEO ? Track.TYPE_VIDEO
           : Track.TYPE_AUDIO;
       FragmentedMp4Extractor extractor = new FragmentedMp4Extractor(
-          FragmentedMp4Extractor.WORKAROUND_EVERY_VIDEO_FRAME_IS_SYNC_FRAME);
+          FragmentedMp4Extractor.WORKAROUND_EVERY_VIDEO_FRAME_IS_SYNC_FRAME, null);
       extractor.setTrack(new Track(trackIndex, trackType, streamElement.timescale,
           initialManifest.durationUs, mediaFormat, trackEncryptionBoxes));
       extractors.put(trackIndex, extractor);

**Comment by hodzic** [comment]
That doesn't look good. How do I send the diff?

**Comment by hodzic** [comment]
http://content.intertrust.com/dash/sintel/cleartext-split/mpd.xml plays with that change, and fails without.

**Comment by ojw28** [comment]
Thanks. I'm pretty confused about how that fixes the problem. If there were actually samples from multiple tracks in the streams then I would still expect playback to fail. Does that mean the streams in the example contain multiple track definitions, but only samples for one of the tracks? Which is really weird. I'm not sure whether that's really valid or not.

**Comment by hodzic** [comment]
The latter. Video segments contain only video samples. Audio segments contain only audio samples. But each init segment, for both video and audio adaptation sets, include both audio and video track definition. I couldn't see that the MPEG DASH spec doesn't allow it.

**Comment by ojw28** [comment]
It feels more like a property of FMP4 than of DASH. And if you define a track in an FMP4 file and then don't include any samples for that track, I would say that's pretty likely to confuse media players (including ExoPlayer once we add proper multi-track support to FragmentedMp4Extractor, because we'll probably implement it in such a way to prevent playback from starting until we have at least one sample from each track).

I'd claim that whatever transcoded these streams is broken. The generated streams might not violate any specs, but if that's the case, it's more due to the fact that the specs are way too permissive than anything else. There are many ways to generate streams that don't violate specs but should be considered broken for all practical scenarios.

**Comment by hodzic** [comment]
In the case of DASH, multiple tracks are expressed in the MPD, through different adaptation sets and a player should rely on that for presenting multiple track selection to the user/client, IMO.

Currently, the FragmentedMp4Extractor takes the first track in the initialization segment, and doesn't match the subsequent media segment track IDs with the initialization segment track IDs. That's the fundamental problem here. A proper fix for the problem at hand, IMO, would be for the FragmentedMp4Extractor to slurp all the tracks from the initialization segment, and subsequent media segments to use the corresponding tracks based on the track ID...

You are right about the specs. DASH has quite a few redundancies between the MPD and the media files, allowing for inconsistencies and problems like this.

**Comment by ojw28** [comment]
- Well, the most fundamental problem is that the FMP4 streams shouldn't declare multiple tracks, given they don't actually contain multiple tracks. The proper fix is for whoever generated the streams to re-transcode them to not have this issue.

- The DASH manifest is supposed to indicate what each stream is, but the mime-type from the manifest should not be required for sample extraction, which is the dependency you're trying to introduce. That's indicative of something being wrong.

- I agree the FragmentedMp4Extractor should support multiple tracks, and use the track IDs properly to associate each fragment with the correct track. But that doesn't really solve the problem in this case, because FMP4 streams in DASH are supposed to only contain one track, and as per above, it shouldn't be necessary to use information from the manifest to determine which of multiple tracks in a stream is the correct one.

So yeah. I think we do want to add multi-track support to the extractor. But for this particular issue the content provider should fix their content. I've not seen any other examples of content with this issue, and if it's only a problem that's affecting streams generated by one provided, then I'd rather that provider fix their streams, rather than having every client that consumes those streams need to work around the problem.

**Comment by ojw28** [comment]
I opened #363 to track supporting multiple tracks. I don't think we want any mime-type passing workaround for this specific case, especially given we've only seen one example of this type of problematic media (and as such, it's better just to get the person generating it to generate it without the problem).

**Comment by hodzic** [comment]
OK
