### ISSUE TITLE
Handling Corrupted HLS response

### ISSUE THREAD

**Issue by orhunkupeli7** [google/ExoPlayer#3621]
As you may well know, hls consists file sequences and the tag value of the sequence must be incremented with 1 for every media. But what if it doesn't meet this requirement.

`if (chunkMediaSequence < mediaPlaylist.mediaSequence) {
      fatalError = new BehindLiveWindowException();
      return;
    }`
in here HlsChunkSource.java line 279 it decides the type of exception in that situation and player freezes. By using onPlayerError(ExoPlaybackException error) method I can handle that and then 

`player.prepare(mediaSourceWithAds);
player.setPlayWhenReady(true);`

call these two in order to make it continue to play. Am I doing it wrong or missing something? Or is there another way to handle that kind of situation?

**Comment by andrewlewis** [comment]
That sounds like the right way to handle this at the moment.

Assigning @AquilesCanta in case he has further/different suggestions for what to do in this case.

**Comment by AquilesCanta** [comment]
> As you may well know, hls consists file sequences and the tag value of the sequence must be incremented with 1 for every media. But what if it doesn't meet this requirement.

`BehindLiveWindowException` is not specifically intended to handle non-spec-compliant media sequences. Its purpose is to signal that the media buffering has fallen behind what the server offers for downloading. If the media sequence is not increasing correctly, the behavior is undefined. You might observe any of the following three behaviors:

- Long/endless buffering state.
- `PlaylistResetException`.
- `BehindLiveWindowException`.

For the last two, the suggested approach is showcased in the demo app's `PlayerActivity`. Have a look at `isBehindLiveWindow` method and its corresponding action (a similar approach can be used for `PlaylistResetException`). You will indeed need to re-prepare the player, but make sure you are not re-using any MediaSource instances. Maybe worth mentioning: playWhenReady state is persistent across player preparations. Another option is to prevent BehindLiveWindowExceptions by seeking or altering the playback speed before actually falling behind the live window. To detect this you will need to keep track of the buffering position, preventing it from becoming negative.

Hope this helps, feel free to reopen if your question is not answered.
