### ISSUE TITLE
Interlace issue on exo player - flash news

### ISSUE THREAD

**Issue by venkiheidi** [google/ExoPlayer#3628]
I am using Exo player 2.6 version.  While watching full hd news channels as multicast packet, found interlace issue on flash news (marquee format) which is not sharp.
 
Attached record .ts format for your reference. 
[deinterlace_ts_file_clr.zip](https://github.com/google/ExoPlayer/files/1581771/deinterlace_ts_file_clr.zip)

Please refer attached images .  Letters are not sharp cause of interlace issue.
![exo-interlace-issue](https://user-images.githubusercontent.com/34763203/34290840-7e945372-e71f-11e7-89b5-844f41e9f9c8.jpg)

Please help me to fix this issue or guide me to any parameters.

Rgds
Venkatesan K

**Comment by andrewlewis** [comment]
Postprocessing like deinterlacing is controlled by whatever codecs the device has, so this is not really an ExoPlayer issue. Please see also #2013.

**Comment by venkiheidi** [comment]
Hi Andrew

Thanks for your reply.  While playing same multicast tv channel using  amlogic multicast player , there is no interlace issue.

Rgds
Venkatesan K

**Comment by andrewlewis** [comment]
Is that a different device or the same device with different software?

If the device has another codec for the same format you could try using that: you can list codecs by running `adb shell cat /system/etc/media_codecs.xml`, and modify `MediaCodecUtil.isCodecUsableDecoder` to tell ExoPlayer not to pick the problematic decoder.

**Comment by venkiheidi** [comment]
There are two media player installed for checking.  There is no interlace issue on amlogic media player.  There is interlace issue on Exo player.

Thanks again for your support. Look forward to suggestions to fix.

Rgds

Venkatesh

**Comment by andrewlewis** [comment]
I don't think I have anything else to suggest apart from trying a different decoder on the same device (suggested above) or checking if this device has custom video `MediaFormat` keys for controlling postprocessing (suggested in #2013). Maybe the other player is bundling its own video codec. The core ExoPlayer library doesn't include decoders, so you get whatever the system provides on the device/build.

**Comment by ojw28** [comment]
Agreed this is likely to be a platform specific decoder issue. You really need to be reporting the issue to AmLogic, since they control the underlying platform.

**Comment by venkiheidi** [comment]
Interlace not encountered using Amlogic media player on same box.  While using Exo player encountered interlace issue.  Is any parameter to turn on / off de-interlace. In VLC, they given configuration 

Rgds

Venkatesh

**Comment by venkiheidi** [comment]
Gone through logcat, understand that Exo player didn’t choose hardware decoder  , selected software decoder.  Please validate this. If yes, how to configure hardware decoder always on Exo player.

 

Please refer attached logcat for your reference.

 

Rgds

Venkatesh
