### ISSUE TITLE
Can't play HLS link

### ISSUE THREAD

**Issue by chillsweet** [google/ExoPlayer#3632]
ExoPlayer 2.6.0

Problem is when I play HLS link with HlsMediaSource, it can prepare source by show duration of audio but it won't play when ready.

I'm not quite sure that it's about codec of file that effect to this problem? or something else.

problem link:
"https://live-s2.cocodemy.com/content2/a1.mp3/playlist.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9MTIvMjIvMjAxNyAwOToxNzoyOSBBTSZoYXNoX3ZhbHVlPUd6SnFQQkp0VnBia1FJcVlycGl4K3c9PSZ2YWxpZG1pbnV0ZXM9MTA="

playable link:
"https://live-s2.cocodemy.com/content2/p1.mp4/playlist.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9MTIvMjIvMjAxNyAwNDo0MDowNyBBTSZoYXNoX3ZhbHVlPUJJTW5IaFU1VzhqSkNoa1JSMFVYZUE9PSZ2YWxpZG1pbnV0ZXM9MTA="

sorry for my bad english.

**Comment by erdemguven** [comment]
Tried on dev branch HEAD, player stays in buffering state, no error log. Link plays fine on QuickTime player.

**Comment by chillsweet** [comment]
It's happen only audio file convert to m3u8

there are other links that get this problem too

https://live-s2.cocodemy.com/content2/a2.m4a/playlist.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9MDEvMDIvMjAxOCAwOTo0NTo1MSBBTSZoYXNoX3ZhbHVlPVU1eCtPZTYvN3hGVmhaMHlUeWNQeEE9PSZ2YWxpZG1pbnV0ZXM9MTA=

https://live-s2.cocodemy.com/content2/53.mp3/playlist.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9MDEvMDIvMjAxOCAwOTozNToyNCBBTSZoYXNoX3ZhbHVlPVoxWHpTQ011TzRJWllQQWN0OUwxdHc9PSZ2YWxpZG1pbnV0ZXM9MTA=

**Comment by ojw28** [comment]
The issue is that the media segments are mp3 segments, but they're named with a `.ts` file extension.

* Changing the segment file extensions to `.mp3` on the serving side (and updating the media playlist accordingly) will allow the content to be played successfully. If you control the serving side then this is by far the best way for you to resolve the issue, since the file extensions are incorrect.
* Using a custom `HlsExtractorFactory` that forces initialization of an `Mp3Extractor` would also allow the content to be played successfully, if you knew you were handling this type of content. You'd need to pass your custom factory when creating the `HlsMediaSource`.
* The fact we rely on the segment file extensions is considered a bug. This issue is tracked by https://github.com/google/ExoPlayer/issues/2025.

The only remaining thing here is that now we've made `TsExtractor` robust against malformed content, this case results in indefinite buffering rather than playback failure. It feels like we should fail eventually (e.g. If we've read a certain number of bytes without ever having encountered a valid TS packet. @AquilesCanta - Could we do something like that to ensure playback failure in this case?

**Comment by chillsweet** [comment]
@ojw28 thank you for your solution
I think choice 2 is the best solution now 
but I can't find any example code for implement `HlsExtractorFactory`.

Could you please give me an example about HlsExtractorFactory, so I can use it to finish my HlsMediaSource.

**Comment by tonihei** [comment]
Did you have a look at the interface here: [HlsExtractorFactory](https://github.com/google/ExoPlayer/blob/release-v2/library/hls/src/main/java/com/google/android/exoplayer2/source/hls/HlsExtractorFactory.java) 
And our default implementation: [DefaultHlsExtractorFactory](https://github.com/google/ExoPlayer/blob/release-v2/library/hls/src/main/java/com/google/android/exoplayer2/source/hls/DefaultHlsExtractorFactory.java).

You can provide your own implementation that forces the initialization of an `Mp3Extractor` as @ojw28 explained. To use this custom extractor factory, you'll also need to enable it by calling `.setExtractorFactroy` on the `HlsMediaSource.Factory` which creates your media source.

**Comment by chillsweet** [comment]
@tonihei 
I follow your suggestion and now I can play the mp3 link
Thank you so much 👍

**Comment by ojw28** [comment]
Issue needs to remain open to track this:

> The only remaining thing here is that now we've made TsExtractor robust against malformed content, this case results in indefinite buffering rather than playback failure. It feels like we should fail eventually (e.g. If we've read a certain number of bytes without ever having encountered a valid TS packet. @AquilesCanta - Could we do something like that to ensure playback failure in this case?

**Comment by AquilesCanta** [comment]
We can count the number of bytes read since the last successful sync, and throw if larger than a given threshold. A fix along these lines will be pushed soon. Thanks for your patience!

**Comment by giladna** [comment]
@ojw28 
@erdemguven 

Having a AES128 m3u8 stream where I get this exception on Exo 2.7.0 Demo app
(sending in mail with issue id)

This stream playes just fine in Exo 2.6.0  demo and in Safari
if I try to play the same stream not Encrypted it plays fine.
what do we miss?

Exception:
-----------

04-10 15:14:48.331 22911-23157/com.google.android.exoplayer2.demo I/ACodec: [OMX.google.aac.decoder] Now handling output port settings change
04-10 15:14:48.331 22911-23154/com.google.android.exoplayer2.demo D/SurfaceUtils: set up nativeWindow 0xc55e8008 for 640x368, color 0x105, rotation 0, usage 0x2900
04-10 15:14:48.332 22911-23154/com.google.android.exoplayer2.demo I/ACodec: [OMX.Exynos.avc.dec] configureOutputBuffersFromNativeWindow setBufferCount : 12, minUndequeuedBuffers : 4
04-10 15:14:48.334 22911-23157/com.google.android.exoplayer2.demo I/ACodec: [OMX.google.aac.decoder] Now Executing
04-10 15:14:48.337 22911-23154/com.google.android.exoplayer2.demo I/ACodec: [OMX.Exynos.avc.dec] Now Executing
04-10 15:14:48.345 22911-23143/com.google.android.exoplayer2.demo D/AudioTrack: Client defaulted notificationFrames to 4725 for frameCount 14176
04-10 15:14:48.346 22911-22911/com.google.android.exoplayer2.demo D/EventLogger: audioSessionId [1089]
04-10 15:14:48.352 22911-22911/com.google.android.exoplayer2.demo D/EventLogger: videoSizeChanged [640, 360]
04-10 15:14:48.369 22911-23151/com.google.android.exoplayer2.demo I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
04-10 15:14:48.369 22911-23151/com.google.android.exoplayer2.demo I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
04-10 15:14:48.379 22911-22911/com.google.android.exoplayer2.demo D/SurfaceView: Relayout returned: oldFrame=[0,48][720,1280] newFrame=[0,461][720,866] result=0x21 surface={Surface(name=null)/@0xf5ce1ae isValid=true -571623424}
04-10 15:14:48.381 22911-22911/com.google.android.exoplayer2.demo D/EventLogger: renderedFirstFrame [Surface(name=null)/@0x2097935]
04-10 15:14:48.493 22911-22911/com.google.android.exoplayer2.demo E/EventLogger: internalError [1.22, loadError]
                                                                                 com.google.android.exoplayer2.ParserException: Cannot find sync byte. Most likely not a Transport Stream.
                                                                                     at com.google.android.exoplayer2.extractor.ts.TsExtractor.read(TsExtractor.java:256)
                                                                                     at com.google.android.exoplayer2.source.hls.HlsMediaChunk.loadMedia(HlsMediaChunk.java:285)
                                                                                     at com.google.android.exoplayer2.source.hls.HlsMediaChunk.load(HlsMediaChunk.java:219)
                                                                                     at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:308)
                                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                                     at java.lang.Thread.run(Thread.java:762)
04-10 15:14:48.496 22911-23143/com.google.android.exoplayer2.demo E/ExoPlayerImplInternal: Source error.
                                                                                           com.google.android.exoplayer2.ParserException: Cannot find sync byte. Most likely not a Transport Stream.
                                                                                               at com.google.android.exoplayer2.extractor.ts.TsExtractor.read(TsExtractor.java:256)
                                                                                               at com.google.android.exoplayer2.source.hls.HlsMediaChunk.loadMedia(HlsMediaChunk.java:285)
                                                                                               at com.google.android.exoplayer2.source.hls.HlsMediaChunk.load(HlsMediaChunk.java:219)
                                                                                               at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:308)
                                                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                                               at java.lang.Thread.run(Thread.java:762)

**Comment by giladna** [comment]
@ojw28 
Could you please give a look why this fixed broke the HLS AES behaviour?

10x
Gilad.

**Comment by ojw28** [comment]
Please file a new issue, rather than tacking something onto a possibly unrelated issue from months ago. Deleting posts so this issue remains easy to read. Thanks!
