### ISSUE TITLE
No 5.1 Sound with Netflix and Amazon Video at Nvidia Shield TV

### ISSUE THREAD

**Issue by solvin90** [google/ExoPlayer#3633]
### Issue description
My soundbar is connected as follows: HDMI OUT Nvidia Shield TV -> HDMI IN soundbar -> HDMI OUT soundbar -> HDMI IN TV

The soundbar supports only DD and DTS. If I play a movie that includes a newer standard like Dolby TrueHD or DTS-HD with Kodi or Plex, than my soundbar can play the DD or DTS core. But if I play a movie from the Netflix or Amazon Video app (they use DD+), than my soundbar can only play stereo. Netflix is locking the 5.1 option. I can't choose that option. I know that Netflix and Amazon use the built in ExoPlayer. How I say: with Kodi and Plex it's possible and my soundbar shows me DD and DTS, but not with Netflix. Is that a issue from the ExoPlayer, Netflix-App or Shield?

### Version of ExoPlayer being used
I don't know. How can I see that on Shield?

### Device(s) and version(s) of Android being used
Geforce Experience 6.2 (Android TV 7.0).

**Comment by ojw28** [comment]
I don't think this is the right place to report end user app issues, sorry. Such issues should be reported to the app developers, who are the right people to investigate in the first instance. They can contact us if they believe there's an underlying issue in ExoPlayer (or the underlying Android platform).

>  I know that Netflix and Amazon use the built in ExoPlayer

I don't think this is accurate for Shield.
