### ISSUE TITLE
DefaultTrackSelector: disable automatic text track selection for sideloaded captions

### ISSUE THREAD

**Issue by qvk** [google/ExoPlayer#3639]
### Issue description
When sideloading multiple language subtitles (vtt) using `MergingMediaSource` (containing a few `SingleSampleMediaSource`s for subtitles, and a `DashMediaSource` referring to a dash manifest containing only video and audio adaptation sets), a subtitle track is selected by default, corresponding to which `TextRenderer.Output#onCues` callbacks are received.

The desired behavior is to not enable any text tracks unless selected during playback.

I am able to select the desired text track based on language during playback using `MappingTrackSelector#setSelectionOverride`, and before preparing the player using `DefaultTrackSelector.Parameters#withPreferredTextLanguage`. (I hope this is the correct approach?)

I am also able to disable captions altogether using `MappingTrackSelector#setRendererDisabled` during playback using the renderer index for `TRACK_TYPE_TEXT`.

However, I can't find a way to disable captions before preparing the player. I can't use the `MappingTrackSelector#setRendererDisabled` method since the renderer index isn't available yet. Also, using the no-arg constructor for `Parameters` or providing null to `Parameters#withPreferredTextLanguage` before preparing player doesn't work. 

I read [this](https://github.com/google/ExoPlayer/issues/2649) (although it refers to a hls source) and [this](https://github.com/google/ExoPlayer/issues/1882) and got the impression that a text track isn't selected by default, but one is being selected in this case (using sideloaded subtitles).

Is this the expected behavior? If so (or otherwise), is there a way to prevent automatic text track selection for sideloaded subtitles?

### Reproduction steps

```
// MediaSource for exoplayer
DashMediaSource dashSource = ...;
SingleSampleMediaSource textSource1 = ...;
SingleSampleMediaSource textSource2 = ...;
MergingMediaSource mergedMediaSource = new MergingMediaSource(dashSource, textSource1, textSource2);

// TrackSelector
DefaultTrackSelector trackSelector = new DefaultTrackSelector(new AdaptiveTrackSelection.Factory(...);
```

### Version of ExoPlayer being used
r2.4.4

Thanks :)

**Comment by qvk** [comment]
Following [the official guide](https://google.github.io/ExoPlayer/guide.html#side-loading-a-subtitle-file) and using `C.SELECTION_FLAG_AUTOSELECT` for `selectionFlags` parameter in `Format.createTextSampleFormat` when creating `Format` for `SingleSampleMediaSource` seems to do the trick (not automatically select any text track). 

But I'm not sure if this approach is correct or reliable. Documentation for `C.SELECTION_FLAG_AUTOSELECT` says 

> ...the player _may_ choose to play the track in absence of an explicit user preference

The desired behavior is that the player _definitely not_ choose to play the track in absence of an explicit user preference. Other selection flags (`C.SELECTION_FLAG_DEFAULT`, `C.SELECTION_FLAG_FORCED`) don't seem fit for what I'm trying to achieve.

Also, am I correct in assuming the _"user preference"_ refers to preferences imposed by `DefaultTrackSelector.Parameters` or any `TrackSelector` implementation?

**Comment by AquilesCanta** [comment]
Passing 0 as the selection flags for the track's format should do the trick. The SELECTION_FLAG_AUTOSELECT is currently ignored by the selector and only tracks that are marked as default or forced or whose language matches the preferred language are selected. If none of these happen, no text track will be selected. To sum up, make sure you don't have any preferred language selected in the default track selector, and pass 0 as the created formats' selection flags. Please reply below if you run into any issues.

**Comment by qvk** [comment]
That worked!

I was using `Format.NO_VALUE` for `selectionFlags` argument in `Format#createTextSampleFormat` earlier which didn't work as desired. Using `0` for `selectionFlags` for creating formats for all the text sources made sure no text tracks were automatically selected.

Thanks! :)
