### ISSUE TITLE
SmoothStreaming doen't support format VC1 

### ISSUE THREAD

**Issue by Ood-Tsen** [google/ExoPlayer#364]
ExoPlayer version 1.3.0 can't play this link 
http://playready.directtaps.net/smoothstreaming/TTLSS720VC1/To_The_Limit_720.ism/manifest .

It's video FOURCC is WMV1.
the audio FOURCE is WMAP.

and the function fourCCToMimeType doesn't handle corresponding format.
> SmothStreamingManifestParser.java
>    private static String fourCCToMimeType(String fourCC) {
> .....
> }

**Comment by ojw28** [comment]
Don't hold your breath for this ever being implemented. I could be wrong, but I don't think Android devices have the necessary hardware decoders. H264 strikes me as a better choice if you want to target anything wider than Microsoft controlled devices/services.
