### ISSUE TITLE
R2.5.4 ANR on Samsung Galaxy S6.

### ISSUE THREAD

**Issue by mukundrd** [google/ExoPlayer#3640]
### Issue description
Video in autoplay mode -> press back -> App results into ANR.
Witnessed in the included demo app as well.
Video in manual play mode -> tap on play -> press back -> App results into ANR
No Video played in both the cases.

### Reproduction steps
Demo App: Youtube Dash -> Google Glass (MP4, H264) -> No autoplay. Press back -> App non-responsive.

### Link to test content
Any video in the demo app.

### Version of ExoPlayer being used
2.5.0, 2.5.1. 2.5.6, 2.6.0.

### Device(s) and version(s) of Android being used
Samsung Galaxy s6 with Android 7.0.

### A full bug report captured from the device
[bugreport-2017-12-25-19-04-31.zip](https://github.com/google/ExoPlayer/files/1585881/bugreport-2017-12-25-19-04-31.zip)
[dumpstate_log-2017-12-25-19-04-31-5499.txt](https://github.com/google/ExoPlayer/files/1585882/dumpstate_log-2017-12-25-19-04-31-5499.txt)

**Comment by mukundrd** [comment]
Correction!!!
###Version of ExoPlayer being used
2.5.0, 2.5.1. 2.5.4, 2.6.0.

**Comment by ojw28** [comment]
@erdemguven - Can we see if we can reproduce this?

**Comment by erdemguven** [comment]
I can't reproduce it. @mukundrd do you still see the problem?
