### ISSUE TITLE
AudioTrack: Spurious audio timestamp

### ISSUE THREAD

**Issue by acaixuediananao** [google/ExoPlayer#3642]
`12-26 16:28:18.120 8360-8403/com.android_project_framework W/AudioTrack: Spurious audio timestamp (system clock mismatch): 242750, 1514276898089348, 22798622255, 5150166, 263168, 262811
12-26 16:28:18.630 8360-8403/com.android_project_framework W/AudioTrack: Spurious audio timestamp (system clock mismatch): 266602, 1514276898600376, 22799131781, 5647083, 289792, 288892
12-26 16:28:19.140 8360-8403/com.android_project_framework W/AudioTrack: Spurious audio timestamp (system clock mismatch): 290454, 1514276899111379, 22799639094, 6144000, 313344, 312744
12-26 16:28:19.640 8360-8403/com.android_project_framework W/AudioTrack: Spurious audio timestamp (system clock mismatch): 314973, 1514276899622383, 22800143430, 6654812, 337920, 337263
12-26 16:28:20.140 8360-8403/com.android_project_framework W/AudioTrack: Spurious audio timestamp (system clock mismatch): 341054, 1514276900133389, 22800646456, 7198166, 363520, 363344
12-26 16:28:20.670 8360-8403/com.android_project_framework W/AudioTrack: Spurious audio timestamp (system clock mismatch): 364906, 1514276900644532, 22801166102, 7695083, 388096, 387196
12-26 16:28:21.180 8360-8403/com.android_project_framework W/AudioTrack: Spurious audio timestamp (system clock mismatch): 388758, 1514276901155498, 22801679761, 8192000, 411648, 411048
12-26 16:28:21.690 8360-8403/com.android_project_framework W/AudioTrack: Spurious audio timestamp (system clock mismatch): 413277, 1514276901667096, 22802194610, 8702812, 436224, 435567
12-26 16:28:22.210 8360-8403/com.android_project_framework W/AudioTrack: Spurious audio timestamp (system clock mismatch): 437129, 1514276902177468, 22802711214, 9199729, 459776, 459419
12-26 16:28:22.730 8360-8403/com.android_project_framework W/AudioTrack: Spurious audio timestamp (system clock mismatch): 463210, 1514276902688472, 22803227968, 9743083, 486400, 485500
12-26 16:28:23.230 8360-8403/com.android_project_framework W/AudioTrack: Spurious audio timestamp (system clock mismatch): 487062, 1514276903199520, 22803737128, 10240000, 509952,`

when i play an file of mp4 , i got those logs; what's meaning? how to fix it?

**Comment by andrewlewis** [comment]
The `android.media.AudioTrack` is behaving in an unexpected way: it has provided a timestamp nano time that is not consistent with the device's clock. It's likely to be a device-specific issue. Please could you provide a full bug report captured with `adb bugreport`?

**Comment by ojw28** [comment]
Closing due to lack of information.
