### ISSUE TITLE
Variable speed not work well on android OS 6.0 devices. The  audio was sound to be discontinuous

### ISSUE THREAD

**Issue by Iftachbar** [google/ExoPlayer#3643]
Hi,
Changing the variable speed to less or more the 1.0 (for example 2.0 or 0.7), on android devices with OS version 6.0, cause the sound to be discontinuous.
Check on Exoplayer demo versions 2.4.x, 2.5.x, 2.6.0 (works well on Exoplayer demo versions 2.3.1), on devices Samsung note 4.0 (OS 6.0) and Samsung tab a (OS 6.0).
In order to change the speed, I add at file PlaybackControlView:
PlaybackParameters playbackParameters = player.getPlaybackParameters();
if (playbackParameters.speed != speed) {
	player.setPlaybackParameters(new PlaybackParameters(speed, playbackParameters.pitch));
}

For example I replaced the original preview method with:
private void previous() {
  if (speed == 1.0f) {
    speed = 0.5f;
  }
  else if (speed == 0.5f) {
    speed = 2.0f;
  }
  else if (speed == 2.0f) {
    speed = 1.0f;
  }
  PlaybackParameters playbackParameters = player.getPlaybackParameters();
  if (playbackParameters.speed != speed) {
   	player.setPlaybackParameters(new PlaybackParameters(speed, playbackParameters.pitch));
  }
}
private float speed = 1.0f;

and run the playlist Audio->video

The result was when the speed was 1.0, then the audio was play correctly, and when the speed was deferent the 1.0 (.07 or 2.0) then the audio was sound to be discontinuous. (on both the audio part and the video part)

Thanks

**Comment by ojw28** [comment]
This likely occurs on debug builds of your app only, as explained [here](https://github.com/google/ExoPlayer/issues/26#issuecomment-296133260). It's likely that release builds of your app are unaffected. Closing for now, but please let us know if this does occur when using a release build. Thanks!

**Comment by Iftachbar** [comment]
Yes, you are correct. At release build the bug disappeared!!!
Thank you very match!
