### ISSUE TITLE
ExoPlayer not supporting .mxg format.

### ISSUE THREAD

**Issue by ghost** [google/ExoPlayer#3658]
is it possible to play .mxg format in exoplayer ?

**Comment by tonihei** [comment]
Please take a look at [the list of supported formats.](https://google.github.io/ExoPlayer/supported-formats.html). Mxg is not part of the list and unless it's an alias for another format, we unfortunately don't support this at the moment. I suggest to convert your data to a more common format if possible.

Could you provide some more details what your files contain, or provide an example file? If it is a video/audio format we could mark this as an enhancement to support the format, although it's unlikely we're going to do this soon.

**Comment by ghost** [comment]
I have combined sequence of JPG file into .MXG format. I am able to play the video with VLC media player. But I am unable to play with ExoPlayer code

**Comment by tonihei** [comment]
ExoPlayer does not support playing images. Please have a look at #2874 or #3434 where similar questions have already been answered.
