### ISSUE TITLE
FLAC support

### ISSUE THREAD

**Issue by Nezz** [google/ExoPlayer#366]
Is it possible to add FLAC support or this is something that is generally not possible because of the lack of codecs? If its possible, what steps should I make?

**Comment by ojw28** [comment]
We'll be publishing a new simplified model for media extractors fairly soon, which will provide the foundation on which someone could do this. The task would be to implement a FLAC extractor in this new model. I'd advise waiting for that, rather than doing anything now.

**Comment by ojw28** [comment]
Note - The dev branch has the new Extractor model, and all existing extractors have been migrated. If you fancy contributing an Extractor for FLAC (or indeed any other container format), that would be great.

**Comment by ojw28** [comment]
The FLAC extension now implements both an extractor and a decoder for FLAC, so this enhancement is complete.
