### ISSUE TITLE
Failed to play encrypted stream.

### ISSUE THREAD

**Issue by weizhaoj** [google/ExoPlayer#3662]
### Issue description
Version: ExoPlayer-release-v2
I added below stream source for test:

{
    "name": "Playready 4.0 tests",
    "samples": [
      {
        "name": "MP4 CENC CBCS (clear)",
        "uri": "https://test.playready.microsoft.com/media/dash/APPLEENC_CBCS_BBB_1080p/clear/bbb_sunflower_1080p_60fps_normal.mp4"
      },
      {
        "name": "MPEG-DASH (protected)",
        "uri": "https://test.playready.microsoft.com/media/dash/APPLEENC_CBCS_BBB_1080p/1080p.mpd",
        "drm_scheme": "playready",
        "drm_license_url": "http://test.playready.microsoft.com/service/rightsmanager.asmx?cfg=(persist:false,sl:150)"
      },
    ]
  },

The first one -- bbb_sunflower_1080p_60fps_normal.mp4 is a clear stream which can play well.
But, the second one -- 1080p.mpd is encrypted with AES-CBCS. There is crash in Exoplayer when play this stream.

Below is the crash log. Could you help to reporduce with above link? Thanks a lot.

01-03 14:06:48.742  9827  9960 E LoadTask: Unexpected exception loading stream
01-03 14:06:48.742  9827  9960 E LoadTask: java.lang.NullPointerException: Attempt to read from field 'int com.google.android.exoplayer2.extractor.mp4.TrackEncryptionBox.**initializationVectorSize**' on a null object reference
01-03 14:06:48.742  9827  9960 E LoadTask: 	at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.parseSaiz(FragmentedMp4Extractor.java:630)
01-03 14:06:48.742  9827  9960 E LoadTask: 	at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.parseTraf(FragmentedMp4Extractor.java:566)
01-03 14:06:48.742  9827  9960 E LoadTask: 	at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.parseMoof(FragmentedMp4Extractor.java:535)
01-03 14:06:48.742  9827  9960 E LoadTask: 	at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.onMoofContainerAtomRead(FragmentedMp4Extractor.java:446)
01-03 14:06:48.742  9827  9960 E LoadTask: 	at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.onContainerAtomRead(FragmentedMp4Extractor.java:384)
01-03 14:06:48.742  9827  9960 E LoadTask: 	at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.processAtomEnded(FragmentedMp4Extractor.java:362)
01-03 14:06:48.742  9827  9960 E LoadTask: 	at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.readAtomPayload(FragmentedMp4Extractor.java:357)
01-03 14:06:48.742  9827  9960 E LoadTask: 	at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:254)
01-03 14:06:48.742  9827  9960 E LoadTask: 	at com.google.android.exoplayer2.source.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:112)
01-03 14:06:48.742  9827  9960 E LoadTask: 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
01-03 14:06:48.742  9827  9960 E LoadTask: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
01-03 14:06:48.742  9827  9960 E LoadTask: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
01-03 14:06:48.742  9827  9960 E LoadTask: 	at java.lang.Thread.run(Thread.java:764)

**Comment by weizhaoj** [comment]
[logcat.txt](https://github.com/google/ExoPlayer/files/1601905/logcat.txt)
Attached the whole log which contains crash log

**Comment by tonihei** [comment]
You are using a version of ExoPlayer which is about a year old and before we added support for CBCS encryption. You can try updating to the latest version to see if it solves your problem?

**Comment by weizhaoj** [comment]
Hi Tonihel,
Thanks for your support. 
Could you recommend one stable version which supports AES CENC CBCS well?

**Comment by weizhaoj** [comment]
I switch to the version of "Tag:r2.6.1". I met another issue when test clear stream:
https://test.playready.microsoft.com/media/dash/APPLEENC_CBCS_BBB_1080p/clear/bbb_sunflower_1080p_60fps_normal.mp4

That stream can play well on ExoPlayer-release-v2. But it failed on "Tag:r2.6.1" Below is full log and crash callstack.
[logcat.txt](https://github.com/google/ExoPlayer/files/1604403/logcat.txt)


01-04 10:34:24.489  2649  2766 E AudioTrack: Could not get audio output for session 49, stream type -1, usage 1, sample rate 48000, format 0x9000000, channel mask 0x3f, flags 0x1
01-04 10:34:24.490  2649  2766 E AudioTrack-JNI: Error -22 initializing AudioTrack
01-04 10:34:24.490  2649  2766 E android.media.AudioTrack: Error code -20 when initializing AudioTrack.
01-04 10:34:24.493  2649  2766 E ExoPlayerImplInternal: Renderer error.
01-04 10:34:24.493  2649  2766 E ExoPlayerImplInternal: com.google.android.exoplayer2.ExoPlaybackException
01-04 10:34:24.493  2649  2766 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(MediaCodecAudioRenderer.java:439)
01-04 10:34:24.493  2649  2766 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:998)
01-04 10:34:24.493  2649  2766 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:552)
01-04 10:34:24.493  2649  2766 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:560)
01-04 10:34:24.493  2649  2766 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:306)
01-04 10:34:24.493  2649  2766 E ExoPlayerImplInternal: 	at android.os.Handler.dispatchMessage(Handler.java:101)
01-04 10:34:24.493  2649  2766 E ExoPlayerImplInternal: 	at android.os.Looper.loop(Looper.java:164)
01-04 10:34:24.493  2649  2766 E ExoPlayerImplInternal: 	at android.os.HandlerThread.run(HandlerThread.java:65)
01-04 10:34:24.493  2649  2766 E ExoPlayerImplInternal: Caused by: com.google.android.exoplayer2.audio.AudioSink$InitializationException: AudioTrack init failed: 0, Config(48000, 252, 20480)
01-04 10:34:24.493  2649  2766 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.audio.DefaultAudioSink.initializeAudioTrack(DefaultAudioSink.java:1180)
01-04 10:34:24.493  2649  2766 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.audio.DefaultAudioSink.initialize(DefaultAudioSink.java:487)
01-04 10:34:24.493  2649  2766 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.audio.DefaultAudioSink.handleBuffer(DefaultAudioSink.java:544)
01-04 10:34:24.493  2649  2766 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(MediaCodecAudioRenderer.java:433)
01-04 10:34:24.493  2649  2766 E ExoPlayerImplInternal: 	... 7 more

**Comment by tonihei** [comment]
The support for CBCS for API levels 24+ was added in version 2.5.0 (see [release notes](https://github.com/google/ExoPlayer/blob/release-v2/RELEASENOTES.md)).

Do I understand correctly that your encrypted stream is playing well on the current version?

And the new error you are seeing is the same you reported two weeks ago (#3627). I'll reopen the other issue to track this there. Please provide a full bugreport  (`adb bugreport`) to the other issue so that we can take a closer look what is happening.

**Comment by weizhaoj** [comment]
Hi Tonihei,
Now I can test my encrypted stream with r2.6. version. There is some problem in my side, and I'm debugging on that.

For clear stream, yes it's same with #3627. I will provide necessary info to your dbeug.
Thanks a lot.

**Comment by ojw28** [comment]
Closing this for now, since the only known issue is tracked by #3627. Please respond here if/when you have more information about the encrypted stream specific issue.
