### ISSUE TITLE
Wrapping DynamicConcatenatingMediaSource

### ISSUE THREAD

**Issue by ncapdevi** [google/ExoPlayer#3663]
I know that `DynamicConcatenatingMediaSource` is final, but according to this issue #3400 you should be able to use composition. However, when I try that, and using  

`dcMediaSource.prepareSource(player, false) { source, timeline, manifest -> listener?.onSourceInfoRefreshed(source, timeline, manifest) }`

The media stays in buffering. Looking at the prepareSource for `DynamicConcatenatingMediaSource` it looks like it ignores isTopLevel.  Is this a bug? Is there anyway to wrap `DynamicConcatenatingMediaSource` ?

**Comment by tonihei** [comment]
Can you give some more details on what you're trying to achieve? Issue #3400 was actually about wrapping an `ExtractorMediaSource` (which is then used as a single item in a concatenation).

In any case, if you use composition for any `MediaSource` you need to make sure to forward all method calls to the relevant inner instance. For the `prepareSource` call in particular you need to use `false` for `isTopLevelSource` because it no longer is the top level source, and in the listener override you need to make sure to call `listener.onSourceInfoRefeshed` with the outer source not the inner one (`dcMediaSource` instead of `source` in your example). That's the reason your're seeing the buffering, as the player waits for the callback of the outer source but only receives one from the inner source.

**Comment by ncapdevi** [comment]
@tonihei Thanks for the feedback and help.  As far as what I'm trying to achieve, at this point it's primarily exploratory.  But the overarching goal is that my audio only player will be pulling down new tracks, and caching them as it goes, and if for some reason it fails to pull down a new track (bad connection or server issues), it should grab a track from cache to continue seamless playback, while continuing this process (get a new track from server if possible, if not, move to the next cached track).  So in order to implement that, I'm diving into the DynamicMediaSource to explore how it works, and possible manage keeping track of what is/isn't being cached there as well as when tracks start/stop.

   I tried following your advice and passing in the dcMediaSource, but still am getting stuck on Buffering with he following code

```
class MyAppDynamicMediaSource(context: Context, private val eventHandler: ExtractorMediaSource.EventListener) : MediaSource {


    private val datasourceFactory: DataSource.Factory = DefaultHttpDataSourceFactory(Util.getUserAgent(context, MyApp.getApplicationListener(context).appName))

    private val extractorsFactory: ExtractorsFactory = DefaultExtractorsFactory()
    private val dcMediaSource = DynamicConcatenatingMediaSource()

    fun addNewSong(fileURL: String): MediaSource {
        val extractorMediaSource = ExtractorMediaSource(Uri.parse(fileURL), datasourceFactory, extractorsFactory, null, eventHandler)
        dcMediaSource.addMediaSource(extractorMediaSource)
        return extractorMediaSource
    }

    override fun prepareSource(player: ExoPlayer?, isTopLevelSource: Boolean, listener: MediaSource.Listener?) {
        dcMediaSource.prepareSource(player, false) { _, timeline, manifest -> listener?.onSourceInfoRefreshed(dcMediaSource, timeline, manifest) }
    }

    override fun createPeriod(id: MediaSource.MediaPeriodId?, allocator: Allocator?): MediaPeriod {
        return dcMediaSource.createPeriod(id, allocator)
    }

    override fun releaseSource() {
        dcMediaSource.releaseSource()
    }

    override fun releasePeriod(mediaPeriod: MediaPeriod?) {
        dcMediaSource.releasePeriod(mediaPeriod)
    }

    override fun maybeThrowSourceInfoRefreshError() {
        dcMediaSource.maybeThrowSourceInfoRefreshError()
    }

}
```

Apologies if you aren't familiar with Kotlin, I can repost the code in Java if it helps at all. Any obvious things that I'm doing wrong that would prevent this from playing?

**Comment by tonihei** [comment]
Code looks fine to me. 
Just to make sure: I assume you prepare the player with player.prepare(myAppDynamicMediaSource) and you never call any of the media source methods directly (apart from addNewSong of course).

And to investigate the reason behind this buffering it would be helpful if you could use your media source  wrapper in the demo app and send a bug report or the logcat output of what happened when you are stuck in the buffering mode.

**Comment by ncapdevi** [comment]
Yes, I'm doing exactly as you had said. I'm able to successfully wrap the ExtractorMediaSource, but when wrapping this class, I get a onPlayerStateChanged call back for Idle, and for buffering, but then nothing else.  I'll try to get a version of it in the demo app to see if that helps at all.

**Comment by ncapdevi** [comment]
I receive the same issue with the DemoApp with the following conditions: On Branch dev-v2 (commit d9bee4d29c54eb12ca64b64e6f455add96d242ba). I have added this class

```
public class DemoDynConMediaSource implements MediaSource {
     DynamicConcatenatingMediaSource dcMediaSource = new DynamicConcatenatingMediaSource();

    @Override
    public void prepareSource(ExoPlayer player, boolean isTopLevelSource, final Listener listener){
        dcMediaSource.prepareSource(player, false, new Listener() {
            @Override
            public void onSourceInfoRefreshed(MediaSource source, Timeline timeline, @Nullable Object manifest){
                listener.onSourceInfoRefreshed(dcMediaSource,timeline,manifest);
            }
        });
    }

    @Override
    public void maybeThrowSourceInfoRefreshError() throws IOException{
        dcMediaSource.maybeThrowSourceInfoRefreshError();
    }

    @Override
    public MediaPeriod createPeriod(MediaPeriodId id, Allocator allocator){
        return dcMediaSource.createPeriod(id,allocator);
    }

    @Override
    public void releasePeriod(MediaPeriod mediaPeriod){
        dcMediaSource.releasePeriod(mediaPeriod);
    }

    @Override
    public void releaseSource(){
        dcMediaSource.releaseSource();
    }
}

```

And in PlayerActivity.java at line 360 adding

```
    DemoDynConMediaSource  dcMediaSource = new DemoDynConMediaSource();
    dcMediaSource.dcMediaSource.addMediaSource(mediaSource);
    player.prepare(dcMediaSource, !haveResumePosition, false);

```
The only possible debug log info I see is

```
01-05 14:31:16.906 7314-7314/com.google.android.exoplayer2.demo D/EventLogger: state [0.07, true, I]
01-05 14:31:16.924 7314-7314/com.google.android.exoplayer2.demo D/EventLogger: state [0.09, true, B]
```

If I instead use the standard DynamicConcatenatingMediaSource at lines 360 in PlayerActivity.java it works just fine. The one difference I seem to notice is that `onSourceInfoRefreshed` in ExoPlayerImplInternal.java is called only once with the wrapper class, but with the standard DynamicConcatenatingMediaSource it is called 3 times



Please let me know if there's anything else I can do to help debug this.

**Comment by ncapdevi** [comment]
@tonihei  was finally able to solve it by changing line 22 in `DemoDynConMediaSource.java` from:
`                listener.onSourceInfoRefreshed(dcMediaSource,timeline,manifest);`
 to:
                `listener.onSourceInfoRefreshed(DemoDynConMediaSource.this,timeline,manifest);`

Maybe you could help me understand why that makes sense in this case (but you don't do that for ExtractorMediaSource)?

**Comment by tonihei** [comment]
That's actually what I meant in my first post - you need to use the outer wrapping media source and not the inner one for the listener. This is to ensure the player gets a callback from the media source passed into `player.prepare(mediaSource)`. So ` dcMediaSource` is of course still the wrong one, because you need to return your `DemoDynConMediaSource` as you found out yourself. Sorry for the confusion.

I'll close the issue because it seems to be solved. Feel free to reopen if necessary.

**Comment by ncapdevi** [comment]
Perfect, thank you for your help
