### ISSUE TITLE
AdsLoader EventListener

### ISSUE THREAD

**Issue by giladna** [google/ExoPlayer#3672]
Hi right now not all IMA events are reflected to the event listener
is to possible to expose the ad events so it can be used by the app for business logic/statistics?

For example ImaAdsLoader onAdEvent will fire all the IMA ad Events that are passed to it

 public static enum AdEventType {
        ALL_ADS_COMPLETED,
        CLICKED,
        COMPLETED,
        CUEPOINTS_CHANGED,
        CONTENT_PAUSE_REQUESTED,
        CONTENT_RESUME_REQUESTED,
        FIRST_QUARTILE,
        LOG,
        AD_BREAK_READY,
        MIDPOINT,
        PAUSED,
        RESUMED,
        SKIPPED,
        STARTED,
        TAPPED,
        ICON_TAPPED,
        THIRD_QUARTILE,
        LOADED,
        AD_PROGRESS,
        AD_BREAK_STARTED,
        AD_BREAK_ENDED;

        private AdEventType() {
        }
    }

  Thanks,
Gilad

**Comment by andrewlewis** [comment]
Please see #3322.
