### ISSUE TITLE
avi playing sample

### ISSUE THREAD

**Issue by dirondir** [google/ExoPlayer#3674]
Hi!
I've seen the question https://github.com/google/ExoPlayer/issues/745
There is the phrase over there: "ExoPlayer doesn't include an Extractor for reading AVI containers, but the file may be readable using the platform MediaExtractor via FrameworkSampleSource"

Could you give any sample how to use FrameworkSampleSource with the current version of the ExoPlayer? Because in the current version there is no such a class as "FrameworkSampleSource". 

Thanks in advance for any help!

**Comment by ojw28** [comment]
We no longer support the platform MediaExtractor (and there is no FrameworkSampleSource) in the current version of ExoPlayer, sorry.
