### ISSUE TITLE
Technicolor STB: Issue with tunneled playback

### ISSUE THREAD

**Issue by ErezNe** [google/ExoPlayer#3675]
### Issue description
If I activate tunneled playback on standard exoplayer 2.5.4 with following line: 
trackSelector.setTunnelingAudioSessionId( C.generateAudioSessionIdV21( this ) );

called just after:
trackSelector = new DefaultTrackSelector(adaptiveTrackSelectionFactory);
in function initializePlayer.

I playback the Widevine DASH: MP4,H265 / Wv: Secure HD content, after seek I got a playback freeze. This is also reproduce inside of my app. I deactivate ( setTunnelingAudioSessionId ), It solves the problem.

when Video tunnel is  enable I can observer the following phenomenon：

( 1）video tunnel mode playback work successfully. No any abnormal.
( 2 ) There are two cases if we do seek

video freeze 3~10 seconds and when recovery playback. It is dependent on when ACode send es data to omx side
video freeze and don't recovery. I check this case and it is caused by no video data send to omx side(exoplayer UI also can display no any data send to low level side).

I also add the following patch (and it did not solve the problem) :

MediacodecVideoRender.java
protected void onQueueInputBuffer(DecoderInputBuffer buffer) {
if (Util.SDK_INT < 23 && tunneling) {
if (Util.SDK_INT >= 21 && tunneling) {
maybeNotifyRenderedFirstFrame(); // exoplayer need this notify in tunnel mode to set the renderedFirstFrame to true , otherwise the //MediacodecVideoRender will be never ready.
}
}

It seems that this issue is caused by exo-player's when it do seeking at tunnel mode. Exo-player pause but don't start after it do seeking.

### Link to test content
for send you a link I need your public IP due to GeoBlocking on my system
Please send it to my private mail 

### Version of ExoPlayer being used
Exo ver 2.5.4

### Device(s) and version(s) of Android being used
It was test on Technicolor STB with Synaptics's SoC 

Thx
Erez

**Comment by ojw28** [comment]
This is most likely a device specific issue, which you should report to the device manufacturer in the first instance. I'll keep this open for now, but it's unlikely we'll be able to look at it any time soon.

**Comment by ErezNe** [comment]
Hi ,
I enable once more tunnel mode on 2.5.4 version but this time the content was not encrypted ,With this configuration I have no problem to seek but I notice with a new issue:
Some times while enable the video tunnel and try to play the un-encrypted content I can not see and hear video and audio ! I just see black screen although the video is streaming.
Do you familiar with such an issue on ver 2.5.4   ?
Does some thing change \fix between ver 2.5.4 to 2.7.1 regarding Video tunnel ?

Erez

**Comment by ojw28** [comment]
The tunneled output path is mostly the responsibility of the device manufacturer. I'd suggest reporting the issue to Technicolor/Synaptics.
