### ISSUE TITLE
Audio modification - speed, volume boost

### ISSUE THREAD

**Issue by vandzi** [google/ExoPlayer#368]
Is it possible with ExoPlayer to change playback speed,  boost volume or other audio modifications? Thanks!

**Comment by ojw28** [comment]
- There's a discussion in #26 about changing playback speed. It's not something we're planning to support directly any time soon, although as discussed there, it's possible in theory to extend ExoPlayer to do this.
- You can adjust the volume using (this)[https://github.com/google/ExoPlayer/blob/master/library/src/main/java/com/google/android/exoplayer/MediaCodecAudioTrackRenderer.java#L63].
- You can attach effects by doing something similar to the 4th post in #252. Note that you may need to enable the workaround as described at the end of that thread if you want to do this.
