### ISSUE TITLE
When playing video, the video screen is jitter

### ISSUE THREAD

**Issue by ghost** [google/ExoPlayer#3681]
exoplayer version:
```
2.6.0
```

play url:
```
http://pl-ali.youku.com/playlist/m3u8?vid=XMzIwMzg4NTkyOA%3D%3D&type=hd2&ups_client_netip=70ff1e8a&ups_ts=1515465613&utid=jRnbEt0E%2FXUCAXD%2FHooZPOQv&ccode=0502&psid=8929e3cc0c51b812148c7ef41bd87d0f&duration=2727&expire=18000&ups_key=f4d4cde75f300fb003efe5b7ddbf12f4&advIds=812646961_81-803294200_1559
```

device:
```
AndroidTV 4.2
```

When playing video, the video screen is jitter like this

![default](https://user-images.githubusercontent.com/18097997/34702642-d00544f6-f529-11e7-8a26-e93fd24b832c.gif)

Forgive my English is not good, I hope I can express clearly.Thx

**Comment by ojw28** [comment]
The stream doesn't appear to be playable in ExoPlayer (I'm seeing HTTP 403 errors) or VLC (unable to determine the format of the segments). We need a working test stream to follow up on this. Please also provide a full bug report captured with `adb bugreport` shortly after encountering the issue, as described in the issue template.

**Comment by ghost** [comment]
This url is invalid.I will provide a new url.It maybe keep valid for a day.
```
http://pl-ali.youku.com/playlist/m3u8?vid=XMzIwMzg4NTkyOA%3D%3D&type=hd2&ups_client_netip=70e1e642&ups_ts=1516333262&utid=zlboEmGiC0gCAXDh5kI%2B9%2F7R&ccode=0502&psid=bf08b7faab03f821b5c5b74f1d6b5ca3&duration=2727&expire=18000&ups_key=98d0058781388ce276b626e4929fee05&advIds=812032864_81-803294200_1559
```
I have used VLC to play it,I did not see this issue.
Forgive my English is not good, I hope I can express clearly.Thx

**Comment by ojw28** [comment]
I see a completely empty media playlist (i.e. does not contain any media) when I request the newly provided URL:

```
#EXTM3U
#EXT-X-TARGETDURATION:-1
#EXT-X-VERSION:3
#EXT-X-ENDLIST
```

**Comment by ojw28** [comment]
Closing due to lack of information.
