### ISSUE TITLE
PreCaching a master m3u8

### ISSUE THREAD

**Issue by xiaoyepadzhang** [google/ExoPlayer#3682]
Hi,  I have a question about preCache.
**Issue description**
1. Can I precache a master m3u8(contain sub m3u8 by bandwidthMeter) url just like 
`DataSpec dataSpec = new DataSpec(url, 0, 1024 * 1024, null);`
`CacheUtil.cache(dataSpec)`
I often got a EOFException, seem like I had finish the preCache, But this means I just cache the **m3u8 list file** not the TS file ? 
2. Whether I need gain the url's first TS file, and use `CacheUtil.cache(dataSpec)` ?  If it's true, How can I got the first TS file? And I should consider the bandwidthMeter to choose the current TS file by master m3u8 ?

This is my test code:

```
    sThread = new Thread(new Runnable() {
      @Override
      public void run() {
        resetCounter();

        final DataSpec dataSpec = new DataSpec(mUri, 0, mPreCacheSize, null);
        
        isCaching = true;
        try {
          CacheUtil.cache(dataSpec, mSimpleCache, mCacheSourceFactory.createDataSource(),
              new byte[CacheUtil.DEFAULT_BUFFER_SIZE_BYTES], null, 1, mCachingCounters, true);
        } catch (EOFException e) {
          e.printStackTrace();
          mCounterHandler.sendEmptyMessage(CounterHandler.MSG_FINISH);
        } catch (InterruptedException e) {
          e.printStackTrace();
        } catch (IOException e) {
          e.printStackTrace();
        }  finally {
          isCaching = false;
        }

      }
    }, "cache_thread");
    sThread.start();
```

**Comment by xiaoyepadzhang** [comment]
@andrewlewis Hi

**Comment by sajjadjaved01** [comment]
Hi @xiaoyepadzhang, i'm also working working with M3U file. can u guide me a little bit

**Comment by xiaoyepadzhang** [comment]
@sajjad0321 what kind of guide,  about preCache?

**Comment by xiaoyepadzhang** [comment]
@erdemguven Hi , I see you add question for this issue, Means that the ExoPlayer not supported to preCache a m3u8 file yet ?

**Comment by erdemguven** [comment]
Hi, it means this issue is a question about how to use ExoPlayer. I'll answer your question with a sample HLS downloader code soon.

**Comment by xiaoyepadzhang** [comment]
@edwinwong Him How can I get the sample HLS downloader code?

**Comment by xiaoyepadzhang** [comment]
@erdemguven Hi, How can I get the sample HLS downloader code?

**Comment by erdemguven** [comment]
I'll share it with you when it's ready.

**Comment by xiaoyepadzhang** [comment]
@erdemguven I'm still  waiting for the code here~

**Comment by kimnamcham** [comment]
@xiaoyepadzhang Can your code precache success with other format video like mp4?
If yes,can you share me your code, thanks?

**Comment by xiaoyepadzhang** [comment]
@erdemguven Seem that  now I can use the downloader to precache the master m3u8 file, right ?

**Comment by xiaoyepadzhang** [comment]
@erdemguven Hi, when I click the download button in the exoplayer hls demo,  I find that I should choose the sub uri that in the master HlsList.  My question is that , Can I not choose the sub uri and it can auto choose the current uri  with adaptive bandwith.   And When I open the master hls again, It will play the cache video ,and not to adaptive the video again ?

**Comment by erdemguven** [comment]
@xiaoyepadzhang sorry for the late answer. For HLS downloading please see:
https://medium.com/google-exoplayer/downloading-adaptive-streams-37191f9776e

It isn't possible to use adaptive bitrate during download currently.
