### ISSUE TITLE
Stream goes to the start position and keep buffering when using ClippingMediaSource

### ISSUE THREAD

**Issue by Sara-Tareq** [google/ExoPlayer#3683]
### Issue description
When wrapping an HlsMediaSource in a ClippingMediaSource then seek forward after the stream starts put the app on the background then bring it back up to the foreground again the seekbar position return back to the start and the stream keeps buffering until another seek action is done. 

### Reproduction steps
 using the ExoPlayer demo app play the stream then seek forward then put the app in the background then bring it back up to the foreground again.

### Link to test content
sent to dev.exoplayer@gmail.com

### Version of ExoPlayer being used
2.6.1 release-v2 branch 

### Device(s) and version(s) of Android being used
Nexus 9 os version 7.1.1  and Nexus 6 os version 7.0 

### A full bug report captured from the device
using the demo app
[bugreport-N4F26Q-2018-01-09-11-00-54.zip](https://github.com/google/ExoPlayer/files/1614177/bugreport-N4F26Q-2018-01-09-11-00-54.zip)

**Comment by ojw28** [comment]
Is this specifically for a live stream? If so, could you clarify exactly what behavior you'd expect when clipping a moving window (let's say the live stream has a moving window that's 1 minute in length). I'm not really sure what I'd expect the behavior to be.

**Comment by Sara-Tareq** [comment]
@ojw28 it's happening for replay stream not live

**Comment by Sara-Tareq** [comment]
@ojw28 I tested the same stream url using the demo app connected to dev-v2 branch and it worked fine, this is happening when using the release version.

**Comment by ojw28** [comment]
Thanks, that's good to know! In that case I'm not sure there's much to do except to wait for a release that picks up the fix (2.7.0).

**Comment by Sara-Tareq** [comment]
But I have a release in the near future can I rely on the dev-v2?

**Comment by ojw28** [comment]
We don't have an eta for 2.7.0 yet, sorry. We may do further 2.6.X releases in the near future, but I don't think they will include the changes that fix this issue, unfortunately.

There's nothing preventing you from relying on the dev-v2 branch, or a snapshot of it. It's likely to be a little less stable, but on the flip side it fixes an issue that's important to you. It's ultimately the app developer's responsibility to decide what dependencies their app takes :).

**Comment by ojw28** [comment]
Closing because this is fixed in the dev-v2 branch.
