### ISSUE TITLE
I use exoplayer1.5.16 Demoplayer

### ISSUE THREAD

**Issue by wangjian199074** [google/ExoPlayer#3685]
this is my error 
`01-09 15:03:30.000: E/Unity(11656): OPENGL NATIVE PLUG-IN ERROR: GL_INVALID_ENUM: enum argument out of range

01-09 15:03:30.000: E/Unity(11656): 

01-09 15:03:30.000: E/Unity(11656): (Filename: ./Runtime/GfxDevice/opengles/GfxDeviceGLES.cpp Line: 370)
`
this is my code
`private void preparePlayer(boolean playWhenReady) {

        if (player == null) {

            player = new DemoPlayer(getRendererBuilder());

            player.addListener(this);

            player.setCaptionListener(this);

            player.setMetadataListener(this);

            player.seekTo(0L);

            playerNeedsPrepare = true;

        }
        if (playerNeedsPrepare) {

            player.prepare();

            playerNeedsPrepare = false;

        }
        player.setSurface(this.m_Surface);

        player.setPlayWhenReady(playWhenReady);

        LogUtil.d(player.getPlaybackState()+"preparePlayer");

    }`

**Comment by ojw28** [comment]
This error is not related to ExoPlayer (looks like a Unity error). Version 1.5.16 is also very old.
