### ISSUE TITLE
Exoplayer DASH + Widevine my app

### ISSUE THREAD

**Issue by admobwebmaster** [google/ExoPlayer#3688]
Hello guys
Friends have a project of my app and be running well with exoplayer but I wanted to integrate DASH + Widevine into my application and wanted to know if anyone could help?

Thank you

**Comment by ojw28** [comment]
This issue tracker is intended for more specific issues, questions and enhancement requests. For requests this general, you'd be best off asking elsewhere. If you have something specific that you're stuck with, please feel free to respond here and we'll do our best to help.
