### ISSUE TITLE
vast ad load time out issue.

### ISSUE THREAD

**Issue by ZohaibGhafoor** [google/ExoPlayer#3691]
```
ImaAdsLoader.Builder imaAdsLoaderBuilder = new ImaAdsLoader.Builder(this);
imaAdsLoaderBuilder.setVastLoadTimeoutMs(60000);
adsLoader = imaAdsLoaderBuilder.buildForAdTag(adTagUri);
```

i set the vastadloadtimeout to 60000 but i still get this error.

AdError [errorType: PLAY, errorCode: AdErrorCode [name: VAST_MEDIA_LOAD_TIMEOUT, number: 402], message: VAST media file loading reached a timeout of 8 seconds.]

**Comment by andrewlewis** [comment]
I think the VAST load timeout applies to the request for the ad tag XML, whereas the timeout you're seeing relates to loading the ad media. It looks like the Android IMA SDK currently doesn't provide a way to customize media load timeout.

I can file a feature request to be able to customize the media load timeout (though eight seconds sounds like a long time for users to wait for an ad to start!).

**Comment by andrewlewis** [comment]
[Internal reference: b/18444194]
