### ISSUE TITLE
IMA extension : Player skipped second ads 

### ISSUE THREAD

**Issue by Soulkey7** [google/ExoPlayer#3692]
Version : ExoPlayer 2.6.1

Reproducible with example ExoPlayer

1. Use this ad tag (2 pre-roll)

2. While playing first ad, to minimise app (home screen) and come back few seconds later.

After first ad ended, the second ad is not playing, and content plays.
Strange things is while playing first ad. 
onPause and onResume callback is called without interaction.

**Comment by Soulkey7** [comment]
Additionally, I could fix temporary to add 'VideoAdPlayer.VideoAdPlayerCallback'
However, somehow unlimited onPause and onResume is triggered until current ad is finished.

@Override
        public void onPause() {
            if (mAdsManager != null) {
                mAdsManager.pause();
            }
        }

@Override
        public void onResume() {
            if (mAdsManager != null) {
                mAdsManager.resume();
            }
        }

**Comment by andrewlewis** [comment]
We pause/resume the ads manager in `ImaAdsLoader` when the player is released/recreated, so this should work. Can you reproduce the issue in the ExoPlayer demo app? If it's specific to a particular ad tag please provide a link to it (looks like it's missing from your first comment). Thanks!

**Comment by Soulkey7** [comment]
Sorry that I miss to add adtag.

I could easily reproduce this issue with this tags.

https://pubads.g.doubleclick.net/gampad/ads?iu=/60035833/Seven/7tennis/app/android&vid=5379497663001&sz=400x300&ciu_szs=&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&ad_rule=1&vpos=preroll&cmsid=3753&vad_type=linear&scor=1515372225935&correlator=1515372225935&url=&cust_params=ssai%3Dfalse%26pod=0%26mstatus%3D%26excl_cat%3Dsmartads%26smad%3Dtrue%26device%3Dandroid%26ppid%3D787417d6-e75a-44fb-bdbe-869c6351442c%26currentprog%3DThe%20Morning%20Show%20Summer%20Series&ppid=787417d6-e75a-44fb-bdbe-869c6351442c

**Comment by andrewlewis** [comment]
This looks the same as #3704. I tried backgrounding and resuming and it worked as expected (though as noted on that issue, one of the ads seems to be empty).
