### ISSUE TITLE
IMA extension : Invalid tags to block Player

### ISSUE THREAD

**Issue by Soulkey7** [google/ExoPlayer#3697]
Hi,

[Version]
ExoPlayer 2.6.1

[Reproduce]
Second launch of the ExoPlayer Sample app with below AdTag, player is stopped and no way to play until restart the app with different AdTag or wait next available time.

https://pubads.g.doubleclick.net/gampad/ads?iu=/60035833/Seven/7tennis/web/&vid=5379493939001&sz=400x300&ciu_szs=&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&ad_rule=1&vpos=preroll&cmsid=3753&vad_type=linear&scor=1515713138475&correlator=1515713138475&url=&cust_params=ssai%3Dfalse%26pod=0%26mstatus%3D%26excl_cat%3Dsmartads%26smad%3Dtrue%26device%3D%26ppid%3Da1b2c3d4e5f60789%26currentprog%3DNBC%20Today&ppid=a1b2c3d4e5f60789

**Comment by Soulkey7** [comment]
Attached logs from our app to help understand of the issue.

W/ImaAdsLoader: onAdEvent: LOG
W/ImaAdsLoader:   type: adPlayError
W/ImaAdsLoader:   errorCode: 403
W/ImaAdsLoader:   errorMessage: Linear assets were found in the VAST ad response, but none of them matched the video player's capabilities.
W/ImaAdsLoader: onAdEvent: LOG
W/ImaAdsLoader:   type: adLoadError
W/ImaAdsLoader:   errorCode: 1009
W/ImaAdsLoader:   errorMessage: The response does not contain any valid ads.
W/ImaAdsLoader: onAdEvent: LOG
W/ImaAdsLoader:   type: adLoadError
W/ImaAdsLoader:   errorCode: 1009
W/ImaAdsLoader:   errorMessage: The response does not contain any valid ads.
W/ImaAdsLoader: onAdEvent: LOG
W/ImaAdsLoader:   type: adLoadError
W/ImaAdsLoader:   errorCode: 1009
W/ImaAdsLoader:   errorMessage: The response does not contain any valid ads.

**Comment by Soulkey7** [comment]
Additional information that I get this issue related smartAd functions.

**Comment by andrewlewis** [comment]
Looks the same as #3584. Please reopen if not.
