### ISSUE TITLE
How to start dash or hls video from lowest resolution then it shoult change auto while running ?

### ISSUE THREAD

**Issue by ZohaibGhafoor** [google/ExoPlayer#3698]
hls or dash video always try to start from highest resolution .how to start dash or hls video from lowest resolution like 140p 360p etc and then it should change it's resolution based on network automatically ?

**Comment by linhai326** [comment]
adaptiveTrackSelection.java:
DEFAULT_MAX_INITIAL_BITRATE change this value to the lowest bitrate you have in your source.

**Comment by ojw28** [comment]
Format selection is, by default, based on an estimate of the currently available bandwidth. The component responsible for providing this estimate is `DefaultBandwidthMeter`.

If you re-use the same `DefaultBandwidthMeter` instance from one playback to the next, as is the case in our demo app, then the bandwidth estimate obtained from playing the previous video is used to make the initial format selection for the next one. When on a fast network this effectively causes the highest quality to be selected at the start of each playback (note: the player will still adapt down into a lower quality if bandwidth is subsequently reduced). This behavior is, in my opinion, preferable to resetting back to a lower quality and adapting up for every playback. If you'd prefer everything to be fully reset then you can do this by creating a new player for each playback, and instantiating a new `DefaultBandwidthMeter` to use for it, hence discarding any bandwidth information derived from the previous playback.

At the start of the *very first* playback, initial format selection is made using an assumed bitrate. This is what `DEFAULT_MAX_INITIAL_BITRATE` is, as referenced by @linhai326 above.
