### ISSUE TITLE
hide play pause button while buffering.

### ISSUE THREAD

**Issue by ZohaibGhafoor** [google/ExoPlayer#3700]
how to hide play pause button while media is buffering and show when it is playing or in pause state ?

**Comment by bhoopendrayash** [comment]
player.addListener(new ExoPlayer.EventListener() {
            @Override
            public void onTimelineChanged(Timeline timeline, Object manifest) {
            }

            @Override
            public void onRepeatModeChanged(int repeatMode) {
            }

            @Override
            public void onTracksChanged(TrackGroupArray trackGroups, TrackSelectionArray trackSelections) {
            }

            @Override
            public void onLoadingChanged(boolean isLoading) {
            }

            @Override
            public void onPlayerStateChanged(boolean playWhenReady, int playbackState) {
                if (playWhenReady) {
                    // player is now ready to play and it may have in below state
                    switch (playbackState) {
                        case ExoPlayer.STATE_IDLE:
                            Play.setVisibility(View.GONE);
                            break;
                        case ExoPlayer.STATE_BUFFERING:
                            progressBar.setVisibility(View.VISIBLE);
                            break;
                        case ExoPlayer.STATE_READY:
                            Play.setVisibility(View.GONE);
                            break;
                        case ExoPlayer.STATE_ENDED:
                            Play.setVisibility(View.GONE);
                            
                            break;
                    }
                } else {
                    progressBar.setVisibility(View.GONE);
                }
            }
Just add the ExoPlayer.EventListener on player where you can get all event related to player playback State .and also can customize simple exoplayer ui with costume controls

**Comment by ZohaibGhafoor** [comment]
@bhoopendrayash here i am using exoplayer demo version and it is not working

       `@Override
        public void onPlayerStateChanged(boolean playWhenReady, int playbackState) {
            if (playbackState == Player.STATE_ENDED) {
                showControls();
            }
       
            else if (playbackState == Player.STATE_BUFFERING) {
                PlaybackControlView controlView = simpleExoPlayerView.findViewById(R.id.exo_controller);
                controlView.findViewById(R.id.exo_play).setVisibility(View.GONE);
                controlView.findViewById(R.id.exo_play).setVisibility(View.INVISIBLE);
                controlView.findViewById(R.id.exo_pause).setVisibility(View.GONE);
                controlView.findViewById(R.id.exo_pause).setVisibility(View.INVISIBLE);
                showProgressBar();
            } else {
                hideProbressBar();
            }
    
            updateButtonVisibilities();
        }`

**Comment by ojw28** [comment]
If you require custom UI behavior, you should look at creating your own views rather than relying on those provided by the library. Note that you can easily use the source code for the library provided views as a starting point, and modify them to change the behavior to match what you need.

**Comment by leeprohacker** [comment]
try and it is working     : 

_private void showProgressBarAndControlToggle(boolean isShow) {
        if (isShow) {
            progressBar.setVisibility(View.VISIBLE);
            imgPlay.setImageResource(0);
            imgPause.setImageResource(0);
        } else {
            progressBar.setVisibility(View.GONE);
            imgPlay.setImageResource(R.drawable.ic_play_arrow_black_64dp);
            imgPause.setImageResource(R.drawable.ic_pause_black_64dp);
        }
    }__
