### ISSUE TITLE
Enable Play/Pause control while showing IMA ads

### ISSUE THREAD

**Issue by vinayjoglekar** [google/ExoPlayer#3701]
Hi team,

Is there any way to show play/pause controls while ads are playing? I have tried to customize UI controls by overwriting "controller_layout_id" in xml layout, which works for content but not for ads.

Thanks in Advance!

**Comment by andrewlewis** [comment]
Probably the same as #3532. See the documentation on [`hide_during_ads`](https://github.com/google/ExoPlayer/blob/dev-v2-r2.6.1/library/ui/src/main/java/com/google/android/exoplayer2/ui/SimpleExoPlayerView.java#L99). Please reopen if this is different.
