### ISSUE TITLE
Error updating libs

### ISSUE THREAD

**Issue by admobwebmaster** [google/ExoPlayer#3702]
Hello budy, how are you!
Friends my error design in print line at the time I make upade of lib versions of firebase and google service for 11.8.0

Could someone help me fix this line of error

Thank you
![erro](https://user-images.githubusercontent.com/34076141/34906789-e5c51010-f852-11e7-8e09-d07085c5bdce.png)

**Comment by ojw28** [comment]
Closing because this question is unrelated to ExoPlayer.
