### ISSUE TITLE
Demo app IMA section - incorrect Title

### ISSUE THREAD

**Issue by giladna** [google/ExoPlayer#3703]
Hi @andrewlewis,

This ad json : VMAP pre-, mid- and post-rolls, single ads
contains VAST adtag which is same as for the first: Single inline linear
Looks like has to be removed  
 

{
        "name": "VMAP pre-, mid- and post-rolls, single ads",
        "uri": "https://storage.googleapis.com/exoplayer-test-media-1/mkv/android-screens-lavf-56.36.100-aac-avc-main-1280x720.mkv",
        "ad_tag_uri": "https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dlinear&correlator="
      },

**Comment by andrewlewis** [comment]
Thanks for reporting this. Should be fixed on the next push.
