### ISSUE TITLE
IMA extension : Player paused

### ISSUE THREAD

**Issue by Soulkey7** [google/ExoPlayer#3704]
Hi,

ExoPlayer 2.6.1

Reproducible on Demo ExoPlayer app

If user plays the below ad tag url, the player will be paused at the end of second Ads.
Also, first ad was skipped. 

I assume if the Ad format is wrong, it automatically loads the second and miscalculate of current play status.
Additionally, the second ads does not emit AD Event after THIRD_QUARTILE.

- Ad Tag

https://pubads.g.doubleclick.net/gampad/ads?iu=/60035833/Seven/7tennis/web/&vid=5379497663001&sz=400x300&ciu_szs=&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&ad_rule=1&vpos=preroll&cmsid=3753&vad_type=linear&scor=1515967542849&correlator=1515967542849&url=&cust_params=ssai%3Dfalse%26pod=0%26mstatus%3D%26excl_cat%3Dsmartads%26smad%3Dtrue%26device%3D%26ppid%3Da1b2c3d4e5f60789%26currentprog%3DSunrise&ppid=a1b2c3d4e5f60789

- Logs

01-15 09:09:33.864 18299-18299/com.google.android.exoplayer2.imademo E/AdEvent: AdEvent[type=**LOADED**, ad=Ad [adId=IntegralAds, creativeId=xxxxxx, creativeAdId=, universalAdIdValue=unknown, universalAdIdRegistry=unknown, title=IntegralAds VAST 2.0 Ad Wrapper, description=, contentType=, adWrapperIds=[4524287652], adWrapperSystems=[GDFP], adWrapperCreativeIds=[138222354267], adSystem=IntegralAds, advertiserName=, surveyUrl=null, dealId=, linear=true, skippable=false, width=0, height=0, traffickingParameters=, clickThroughUrl=, duration=15.0, adPodInfo=AdPodInfo [totalAds=2, adPosition=1, isBumper=false, maxDuration=60.0, podIndex=0, timeOffset=0.0], uiElements=[], disableUi=false, skipTimeOffset=-1.0]]

01-15 09:09:33.942 18299-18299/com.google.android.exoplayer2.imademo E/AdEvent: AdEvent[type=**LOADED**, ad=Ad [adId=406545791, creativeId=93860819, creativeAdId=, universalAdIdValue=unknown, universalAdIdRegistry=unknown, title=In-Stream Video, description=, contentType=video/mp4, adWrapperIds=[4450946567], adWrapperSystems=[GDFP], adWrapperCreativeIds=[138213346132], adSystem=DCM, advertiserName=, surveyUrl=null, dealId=, linear=true, skippable=false, width=0, height=0, traffickingParameters=, clickThroughUrl=https://adclick.g.doubleclick.net/pcs/click?xai=AKAOjsuDVt2bt6uRs1lZgv5gIH-fI7sDDRUo-GfVWdjsaLMJhUjqgT8g1rt5s38VVyKDOYs6vYXE1XB4hBWRSmIJP4fOydidaXVUYx6ucym-4JK9ROS5Wcme5GjI&sig=Cg0ArKJSzJ16h-15_AE-EAE&urlfix=1&adurl=http://record.nedsaffiliates.com.au/_IuPcGb_s96r9zAdpJxaFWGNd7ZgqdRLk/21/%3Fb%3DVIDEO250%26www.neds.com.au, duration=15.0, adPodInfo=AdPodInfo [totalAds=2, adPosition=2, isBumper=false, maxDuration=60.0, podIndex=0, timeOffset=0.0], uiElements=[], disableUi=false, skipTimeOffset=-1.0]]

01-15 09:09:33.974 18299-18299/com.google.android.exoplayer2.imademo E/AdEvent: AdEvent[type=**CONTENT_PAUSE_REQUESTED**, ad=Ad [adId=406545791, creativeId=93860819, creativeAdId=, universalAdIdValue=unknown, universalAdIdRegistry=unknown, title=In-Stream Video, description=, contentType=video/mp4, adWrapperIds=[4450946567], adWrapperSystems=[GDFP], adWrapperCreativeIds=[138213346132], adSystem=DCM, advertiserName=, surveyUrl=null, dealId=, linear=true, skippable=false, width=0, height=0, traffickingParameters=, clickThroughUrl=https://adclick.g.doubleclick.net/pcs/click?xai=AKAOjsuDVt2bt6uRs1lZgv5gIH-fI7sDDRUo-GfVWdjsaLMJhUjqgT8g1rt5s38VVyKDOYs6vYXE1XB4hBWRSmIJP4fOydidaXVUYx6ucym-4JK9ROS5Wcme5GjI&sig=Cg0ArKJSzJ16h-15_AE-EAE&urlfix=1&adurl=http://record.nedsaffiliates.com.au/_IuPcGb_s96r9zAdpJxaFWGNd7ZgqdRLk/21/%3Fb%3DVIDEO250%26www.neds.com.au, duration=15.0, adPodInfo=AdPodInfo [totalAds=2, adPosition=2, isBumper=false, maxDuration=60.0, podIndex=0, timeOffset=0.0], uiElements=[], disableUi=false, skipTimeOffset=-1.0]]

01-15 09:09:35.319 18299-18299/com.google.android.exoplayer2.imademo E/AdEvent: AdEvent[type=**STARTED**, ad=Ad [adId=406545791, creativeId=93860819, creativeAdId=, universalAdIdValue=unknown, universalAdIdRegistry=unknown, title=In-Stream Video, description=, contentType=video/mp4, adWrapperIds=[4450946567], adWrapperSystems=[GDFP], adWrapperCreativeIds=[138213346132], adSystem=DCM, advertiserName=, surveyUrl=null, dealId=, linear=true, skippable=false, width=0, height=0, traffickingParameters=, clickThroughUrl=https://adclick.g.doubleclick.net/pcs/click?xai=AKAOjsuDVt2bt6uRs1lZgv5gIH-fI7sDDRUo-GfVWdjsaLMJhUjqgT8g1rt5s38VVyKDOYs6vYXE1XB4hBWRSmIJP4fOydidaXVUYx6ucym-4JK9ROS5Wcme5GjI&sig=Cg0ArKJSzJ16h-15_AE-EAE&urlfix=1&adurl=http://record.nedsaffiliates.com.au/_IuPcGb_s96r9zAdpJxaFWGNd7ZgqdRLk/21/%3Fb%3DVIDEO250%26www.neds.com.au, duration=15.0, adPodInfo=AdPodInfo [totalAds=2, adPosition=2, isBumper=false, maxDuration=60.0, podIndex=0, timeOffset=0.0], uiElements=[UiElementImpl[name=adAttribution], UiElementImpl[name=countdown]], disableUi=false, skipTimeOffset=-1.0]]

01-15 09:09:39.085 18299-18299/com.google.android.exoplayer2.imademo E/AdEvent: AdEvent[type=**FIRST_QUARTILE**, ad=Ad [adId=406545791, creativeId=93860819, creativeAdId=, universalAdIdValue=unknown, universalAdIdRegistry=unknown, title=In-Stream Video, description=, contentType=video/mp4, adWrapperIds=[4450946567], adWrapperSystems=[GDFP], adWrapperCreativeIds=[138213346132], adSystem=DCM, advertiserName=, surveyUrl=null, dealId=, linear=true, skippable=false, width=0, height=0, traffickingParameters=, clickThroughUrl=https://adclick.g.doubleclick.net/pcs/click?xai=AKAOjsuDVt2bt6uRs1lZgv5gIH-fI7sDDRUo-GfVWdjsaLMJhUjqgT8g1rt5s38VVyKDOYs6vYXE1XB4hBWRSmIJP4fOydidaXVUYx6ucym-4JK9ROS5Wcme5GjI&sig=Cg0ArKJSzJ16h-15_AE-EAE&urlfix=1&adurl=http://record.nedsaffiliates.com.au/_IuPcGb_s96r9zAdpJxaFWGNd7ZgqdRLk/21/%3Fb%3DVIDEO250%26www.neds.com.au, duration=15.0, adPodInfo=AdPodInfo [totalAds=2, adPosition=2, isBumper=false, maxDuration=60.0, podIndex=0, timeOffset=0.0], uiElements=[UiElementImpl[name=adAttribution], UiElementImpl[name=countdown]], disableUi=false, skipTimeOffset=-1.0]]

01-15 09:09:42.756 18299-18299/com.google.android.exoplayer2.imademo E/AdEvent: AdEvent[type=**MIDPOINT**, ad=Ad [adId=406545791, creativeId=93860819, creativeAdId=, universalAdIdValue=unknown, universalAdIdRegistry=unknown, title=In-Stream Video, description=, contentType=video/mp4, adWrapperIds=[4450946567], adWrapperSystems=[GDFP], adWrapperCreativeIds=[138213346132], adSystem=DCM, advertiserName=, surveyUrl=null, dealId=, linear=true, skippable=false, width=0, height=0, traffickingParameters=, clickThroughUrl=https://adclick.g.doubleclick.net/pcs/click?xai=AKAOjsuDVt2bt6uRs1lZgv5gIH-fI7sDDRUo-GfVWdjsaLMJhUjqgT8g1rt5s38VVyKDOYs6vYXE1XB4hBWRSmIJP4fOydidaXVUYx6ucym-4JK9ROS5Wcme5GjI&sig=Cg0ArKJSzJ16h-15_AE-EAE&urlfix=1&adurl=http://record.nedsaffiliates.com.au/_IuPcGb_s96r9zAdpJxaFWGNd7ZgqdRLk/21/%3Fb%3DVIDEO250%26www.neds.com.au, duration=15.0, adPodInfo=AdPodInfo [totalAds=2, adPosition=2, isBumper=false, maxDuration=60.0, podIndex=0, timeOffset=0.0], uiElements=[UiElementImpl[name=adAttribution], UiElementImpl[name=countdown]], disableUi=false, skipTimeOffset=-1.0]]

01-15 09:09:46.604 18299-18299/com.google.android.exoplayer2.imademo E/AdEvent: AdEvent[type=**THIRD_QUARTILE**, ad=Ad [adId=406545791, creativeId=93860819, creativeAdId=, universalAdIdValue=unknown, universalAdIdRegistry=unknown, title=In-Stream Video, description=, contentType=video/mp4, adWrapperIds=[4450946567], adWrapperSystems=[GDFP], adWrapperCreativeIds=[138213346132], adSystem=DCM, advertiserName=, surveyUrl=null, dealId=, linear=true, skippable=false, width=0, height=0, traffickingParameters=, clickThroughUrl=https://adclick.g.doubleclick.net/pcs/click?xai=AKAOjsuDVt2bt6uRs1lZgv5gIH-fI7sDDRUo-GfVWdjsaLMJhUjqgT8g1rt5s38VVyKDOYs6vYXE1XB4hBWRSmIJP4fOydidaXVUYx6ucym-4JK9ROS5Wcme5GjI&sig=Cg0ArKJSzJ16h-15_AE-EAE&urlfix=1&adurl=http://record.nedsaffiliates.com.au/_IuPcGb_s96r9zAdpJxaFWGNd7ZgqdRLk/21/%3Fb%3DVIDEO250%26www.neds.com.au, duration=15.0, adPodInfo=AdPodInfo [totalAds=2, adPosition=2, isBumper=false, maxDuration=60.0, podIndex=0, timeOffset=0.0], uiElements=[UiElementImpl[name=adAttribution], UiElementImpl[name=countdown]], disableUi=false, skipTimeOffset=-1.0]]

**Comment by andrewlewis** [comment]
We get an ad load error "AdEvent: {errorMessage=The response does not contain any valid ads., errorCode=1009, type=adLoadError}" from IMA while loading the preroll ad. This is handled better on the latest development version and the player shouldn't get stuck (see #3584), but to get both ads to play I think you need to fix the ad tag so IMA loads a non-empty ad.
