### ISSUE TITLE
[Question] Public Roadmap and 3.0?

### ISSUE THREAD

**Issue by eneim** [google/ExoPlayer#3711]
Hope the title is clear enough. Does the team have a list of what to do next (the Roadmap) and any idea for 3.0 yet? It may be easier for us to contribute in right direction.

**Comment by AquilesCanta** [comment]
There is no public roadmap. A good reason for this is that priorities sometimes change, and it is really hard to keep up to expectations. For the same reason we strongly avoid setting release timelines.

> Does the team have a list of what to do next (the Roadmap) and any idea for 3.0 yet?

ExoPlayer 3 has not been discussed yet (AFAIK).

Anything marked as enhancement in the issue tracker is an opportunity to contribute, specially if it doesn't involve API modifications (extension of the API is usually ok).
