### ISSUE TITLE
Midroll issue

### ISSUE THREAD

**Issue by VMAXSDK** [google/ExoPlayer#3717]
### Issue description
For mid roll ad only Ad controls are visible without ad video on screen (content video playback noticed for Ad breaks)

### Reproduction steps
1. Download sample app [https://github.com/google/ExoPlayer/tree/release-v2/demos/main](url) 
2. Change  “ad_tag_url” to [https://img.vserv.mobi/vast/ima/sample4.xml](url)
3. Load the ad and wait till timeoffset for mid roll reaches 

### Link to test content
[https://img.vserv.mobi/vast/ima/sample4.xml](url)

### Version of ExoPlayer being used
2.6.1
'com.google.ads.interactivemedia.v3:interactivemedia:3.7.4'

### Device(s) and version(s) of Android being used
LG Nexus 5 (Android version 6.0.1)

### A full bug report captured from the device
![midrollissue](https://user-images.githubusercontent.com/26895724/34992525-7a4221a4-faf3-11e7-99eb-60977ecc842c.png)

**Comment by andrewlewis** [comment]
The postroll ad is listed before the midroll ad in the ad tag. The ads seem to play correctly if I swap the midroll and postroll.

Do you have any information about how common it is to include ad breaks out of order?

**Comment by andrewlewis** [comment]
This is the same underlying issue as #3716 so I'll mark this as a duplicate. We can sort the ad group times to fix both issues.
