### ISSUE TITLE
Quartile Event hits(First, Midpoint and Third) firing together for timeoffet end

### ISSUE THREAD

**Issue by VMAXSDK** [google/ExoPlayer#3718]
### Issue description
Quartile events(First, Midpoint and Third) are firing together at the start of the ad when timeoffset is end

### Reproduction steps
1. Download sample app [https://github.com/google/ExoPlayer/tree/release-v2/demos/main](url)   
2. Change  “ad_tag_url” to [https://img.vserv.mobi/vast/ima/sample3.xml](url) 
3. Load the ad and it will hit the first, midpoint and third quartile events together

### Link to test content
[https://img.vserv.mobi/vast/ima/sample3.xml](url)

### Version of ExoPlayer being used
2.6.1
'com.google.ads.interactivemedia.v3:interactivemedia:3.7.4'

### Device(s) and version(s) of Android being used
LG Nexus 5 (Android version 6.0.1)

### A full bug report captured from the device
![multipleeventhits](https://user-images.githubusercontent.com/26895724/34992689-f1f05e96-faf3-11e7-8043-c26c790c379d.png)

**Comment by andrewlewis** [comment]
Please could you set the `DEBUG` flag to true in `ImaAdsLoader`, reproduce the issue and send the output of `adb bugreport`? Then we can see when IMA is firing the events and check the device build, GMS and `WebView` versions.

**Comment by VMAXSDK** [comment]
Hi Andrew attaching adb bugreport as requested
[bugreport-2018-02-15-12-06-11.zip](https://github.com/google/ExoPlayer/files/1726620/bugreport-2018-02-15-12-06-11.zip)

**Comment by andrewlewis** [comment]
The bug report doesn't seem to include logging from `ImaAdsLoader`. Please follow the steps from the comment above to enable debug logging, reproduce the issue and then take the bug report. Thanks.

**Comment by VMAXSDK** [comment]
Hi Andrew,
We enabled the debug flag as below :

ImaSdkSettings settings=new ImaSdkSettings();
settings.setDebugMode(true);
ImaAdsLoader adsLoader = new ImaAdsLoader(context, Uri.parse(adTag),settings);

And after reproducing the issue we took the bug report from the "Take bug report" option available in Device Developer Option, attaching the same
[bugreport-2018-02-16-12-01-47.txt](https://github.com/google/ExoPlayer/files/1730434/bugreport-2018-02-16-12-01-47.txt)


Also attaching the logcat_logs files having the logs from Logcat section in Android Studio.
[logcat_logs.txt](https://github.com/google/ExoPlayer/files/1730435/logcat_logs.txt)

**Comment by andrewlewis** [comment]
Looking at the logcat, the reporting events happen roughly at the expected times for the first two ad playbacks but are grouped for the third ad playback.

The log line "02-16 11:57:07.742 9713-9713/com.google.android.exoplayer2.imademo I/SDK_LOG:ima.managers.VastVideoAdsManager: Playback error: AdError 202: VAST media file duration differs from the VAST response duration by 105.31 seconds." before the third ad playback looks supicious. If you have any control over the ad tag/media, please try making the durations match and see if that resolves the issue.

We provide the player position to the IMA SDK in `ImaAdsLoader.getAdProgress`. You could try putting some logging there to verify that the position is increasing at the correct rate. If it is, then the IMA JavaScript or WebView may be causing the batching of the events. You could also set the static final `DEBUG` flag in `ImaAdsLoader` to true (not the debug setting on `AdsRenderingSettings`) to see when the events are being notified to the Java layer.

**Comment by VMAXSDK** [comment]
We tried adding logs in ImaAdsLoader.getAdProgress(), found that the preroll and midroll ad are progressing properly but in case of postroll ad, the progress is random. Attaching the Logcat section logs from AndroidStudio.
[logcat_logs.txt](https://github.com/google/ExoPlayer/files/1735851/logcat_logs.txt)
Also we have set the static final DEBUG flag in ImaAdsLoader to true, attaching the BugReport from "DeveloperOptions" section for the same.
[bugreport-2018-02-19-13-06-51.txt](https://github.com/google/ExoPlayer/files/1735854/bugreport-2018-02-19-13-06-51.txt)

**Comment by andrewlewis** [comment]
Is the incorrect ad progress equal to the duration of the content? Does the postroll ad actually play?

**Comment by VMAXSDK** [comment]
Please find the comment inline
Is the incorrect ad progress equal to the duration of the content? 
=> yes
Does the postroll ad actually play?
=> yes, the postroll ad is getting played

**Comment by andrewlewis** [comment]
I tried to reproduce this but saw that the player position in the ad was returned as expected. Please could you try again on `dev-v2` and check you still see the same problem? Thanks.

**Comment by VMAXSDK** [comment]
Yes, it's working fine on dev-v2, but when we reported the issue it was from release -v2.

**Comment by andrewlewis** [comment]
If it's fixed on `dev-v2` it should make it into the next release. Thanks.
