### ISSUE TITLE
No Audio in AES-128 HLS stream with #EXT-X-MEDIA directive

### ISSUE THREAD

**Issue by andreimarinescu** [google/ExoPlayer#372]
Hi everyone, 

I'm having an issue where I don't get any audio in an encrypted HLS stream. Example test stream: http://vodstorage.arte.tv/movies/HLS/155892/HLS_155892_0-VOF.m3u8.

I've tested with both my ExoPlayer implementation and the Demo app, with the current master and dev branches, as well as older builds.

There are no error logs, and the player reports an available audio track (getTracks[1] contains 1 element), but no audio is played back. I'm wondering if this is linked to #73 (the problem seems to be identical to #133, but I was unable to find an issue with the stream itself).

Also, audio works with the native SDK MediaPlayer.

Thanks for any pointers or workarounds!

**Comment by ojw28** [comment]
Yes - This is the same request as #73. We're working on it.
