### ISSUE TITLE
Video reload

### ISSUE THREAD

**Issue by Gidex** [google/ExoPlayer#3720]
Why does video reload after rewind?

**Comment by AquilesCanta** [comment]
> Why does video reload after rewind?

Because ExoPlayer does not currently keep the buffered content for seeking back. Good news is that it is something that @ojw28 has been looking at. @ojw28, would you mind filling any gaps/pointing to the right resource?

Relevant: #2882.

**Comment by ojw28** [comment]
We do not cache persistently on disk by default, and we discard our in-memory buffer as we play over it. There are features in the dev branch that allow you to retain buffer after you've played it for a period of time, as described in #3583, however these features are not yet available in a release.
