### ISSUE TITLE
Showing videos like facebook timeline using exoplayer

### ISSUE THREAD

**Issue by meenukrishnamurthy** [google/ExoPlayer#3721]
Hi is there a way to get playing videos like on facebook using the exoplayer library.I need to play the video of the current visible item in the recycler view. Any suggestions would be of help??

**Comment by AquilesCanta** [comment]
Relevant resource: #867. There you will useful hints. @marcbaechinger did some work on this topic as well. However, it will be up to you to decide how to do it, unfortunately (good news is Facebook does it, so it is most definitely possible).

**Comment by eneim** [comment]
@meenukrishnamurthy not to PR, but you can take a look at [my helper library](https://github.com/eneim/toro) :3. Which will come next to it is to manage ExoPlayer instance using Object pool to optimize performance. Hope this helps.

**Comment by marcbaechinger** [comment]
Yes, this is currently not something with which the ExoPlayer library helps you much. You need to implement this yourself by now.

As Santiaog mentioned. Have a look at issue #867 There are a lot of useful hints already.

Some hints as inspiriation (which may be opinionated) from my expierience with the topic :)

- IMO the best approach is having a single ExoPlayer instance which you attach/detach to SimpleExoPlayerViews appearing and disappearing (look at the static `SimpleExoPlayerView.switchTargetView` for this). Using a single player works on all devices also on devices providing only one codec instance.

- You need to have a RecyclerView.OnChildAttachStateChangeListener which tries to attach and prepare the player as early as possible like as soon as the item is added (if the player is not yet attached already).

- You need a RecyclerView.OnScrollListener to check when the video view comes into the visible area. If there are more that two views visible you need to calculate the visible fraction and decide to which view to attach the player.

- You may want to choose to use a CacheDataSource and cache data once downloaded (you may want to precache as well)

- You may want to choose to grab a bitmap from the surface when the view disappears. Put it back as the placeholder when the view reappears (use some kind of a bitmap cache for this).

We can't provide more detailed guidance for the actual implementation I'm afraid.

**Comment by fahime-ghasemi** [comment]
@marcbaechinger I have a recyclerview that each items is a video. in this case, How can I prepare the player as early as possible ?  I think it's not possible in OnChildAttachStateChangeListener because if I prepare another video in this listener, what happen to current video playing?
