### ISSUE TITLE
*.m3u HLS streams error:

### ISSUE THREAD

**Issue by dim4ikhot** [google/ExoPlayer#3722]
I have the next stream URL:

http://yp.shoutcast.com/sbin/tunein-station.m3u?id=1749304

This stream by default returns type TYPE_OTHER, when I try to get correct  `MediaSource`, which lead to this issue:
`com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor) could read the stream.`

Then I tried manually set the correct `MediaSource` to `HlsMediaSource`, but it also doesn't want to play the stream and gives to me next error:
`com.google.android.exoplayer2.ParserException: Couldn't match #EXTINF:([\d\.]+)\b in #EXTINF:-1,The Mystery DJ's Slow Jamz`

How can I play this or similar streams? And can I play them at all?

I'm using Exoplayer 2.6.1

**Comment by AquilesCanta** [comment]
The issue (as per exception) is that EXTINF [has an invalid value](https://tools.ietf.org/html/draft-pantos-http-live-streaming-23#section-4.3.2.1) (-1).

On the other hand, the playlist does contain a stream inside (http://198.27.66.225:8006/stream) for which you can use `ExtractorMediaSource`.

**Comment by dim4ikhot** [comment]
I didn't fully understand. How can I get the stream, you mentioned above, from URL I attached in my question? I can get from server only the stream URLs, like in my question.

**Comment by ojw28** [comment]
We do not support playback of this type of m3u playlist. If you download the original URL and open the file with a text editor, you'll see that all it contains is:
```
#EXTM3U
#EXTINF:-1,The Mystery DJ's Slow Jamz
http://198.27.66.225:8006/stream
```
which is where you can get the actual stream URLs, that we do support.

**Comment by dim4ikhot** [comment]
I see. Thanks for the help.
