### ISSUE TITLE
HLS Streams - Key Rotation, Multiple EXT-X-KEY Tags

### ISSUE THREAD

**Issue by bearcattom** [google/ExoPlayer#3725]
Does ExoPlayer support HLS manifest with MULTIPLE EXT-X-KEY tags/encryption keys...whereby keys are refreshed during playback?

#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:5
#EXT-X-PROGRAM-DATE-TIME:2018-01-18T20:42:59+00:00
**#EXT-X-KEY:METHOD=AES-128,URI="https://foo.com/321630/keys/id/2348028",IV=0x66AA04B5A372A3D24D91A44C194BD050**
#EXT-X-MEDIA-SEQUENCE:259371
#EXTINF:5.005,
018/20/42/59_405.ts
**#EXT-X-KEY:METHOD=AES-128,URI="https://foo.com/321630/keys/id/2348028",IV=0xAD9A75768DADF6684C4A55AF649484F2**
#EXTINF:5.005,
018/20/43/04_410.ts
#EXTINF:5.005,
018/20/43/09_415.ts
#EXTINF:5.005,
018/20/43/14_420.ts
#EXTINF:5.005,
018/20/43/19_425.ts
#EXTINF:5.005,
018/20/43/24_430.ts
#EXTINF:5.005,
018/20/43/29_435.ts
**#EXT-X-KEY:METHOD=AES-128,URI="https://foo.com/321630/keys/id/2348028",IV=0xC4467EF6216F8E93A2D241FCAD2FC486**
#EXTINF:5.005,
018/20/43/34_440.ts
#EXTINF:5.005,
018/20/43/39_445.ts
#EXTINF:5.005,
018/20/43/44_450.ts
#EXTINF:5.005,
018/20/43/49_455.ts
#EXTINF:5.005,
018/20/43/54_460.ts
#EXTINF:5.005,
018/20/43/59_465.ts

**Comment by bearcattom** [comment]
I should add that I ran Charles Proxy and never see any calls to retrieve the keys:

https://foo.com/321630/keys/id/2348028

**Comment by AquilesCanta** [comment]
Yes, that kind of streams should work. If not, please provide all information requested in the issue template for us to look into the issue.

**Comment by bearcattom** [comment]
Sorry for the noise...I had a Charles Proxy issue w/ SSL handling.  These streams do work...thank you.
