### ISSUE TITLE
Does ExoPlayer 2.6.1 supports playback of HLS CMAF CBCS streams?

### ISSUE THREAD

**Issue by HugoSaintLaurent** [google/ExoPlayer#3727]
Does ExoPlayer 2.6.1 supports playback of HLS CMAF CBCS streams?

I’m running a 3rd party stream protected with Widevine using the demo app (Android 8, SDK 27). And I see the following exception when native_queueSecureInputBuffer() is called for the first time.

01/18 15:57:34: Launching demo
$ adb install-multiple -r -t /Users/hsaintlaurent/ExoPlayer-dev-v2-r2.6.1/demos/main/buildout/intermediates/split-apk/noExtensions/debug/slices/slice_9.apk /Users/hsaintlaurent/ExoPlayer-dev-v2-r2.6.1/demos/main/buildout/intermediates/split-apk/noExtensions/debug/slices/slice_4.apk /Users/hsaintlaurent/ExoPlayer-dev-v2-r2.6.1/demos/main/buildout/intermediates/split-apk/noExtensions/debug/slices/slice_3.apk /Users/hsaintlaurent/ExoPlayer-dev-v2-r2.6.1/demos/main/buildout/intermediates/split-apk/noExtensions/debug/slices/slice_2.apk /Users/hsaintlaurent/ExoPlayer-dev-v2-r2.6.1/demos/main/buildout/intermediates/split-apk/noExtensions/debug/slices/slice_6.apk /Users/hsaintlaurent/ExoPlayer-dev-v2-r2.6.1/demos/main/buildout/intermediates/split-apk/noExtensions/debug/slices/slice_0.apk /Users/hsaintlaurent/ExoPlayer-dev-v2-r2.6.1/demos/main/buildout/intermediates/split-apk/noExtensions/debug/slices/slice_1.apk /Users/hsaintlaurent/ExoPlayer-dev-v2-r2.6.1/demos/main/buildout/intermediates/split-apk/noExtensions/debug/dep/dependencies.apk /Users/hsaintlaurent/ExoPlayer-dev-v2-r2.6.1/demos/main/buildout/intermediates/split-apk/noExtensions/debug/slices/slice_5.apk /Users/hsaintlaurent/ExoPlayer-dev-v2-r2.6.1/demos/main/buildout/intermediates/split-apk/noExtensions/debug/slices/slice_8.apk /Users/hsaintlaurent/ExoPlayer-dev-v2-r2.6.1/demos/main/buildout/intermediates/split-apk/noExtensions/debug/slices/slice_7.apk /Users/hsaintlaurent/ExoPlayer-dev-v2-r2.6.1/demos/main/buildout/outputs/apk/noExtensions/debug/demo-noExtensions-debug.apk 
Split APKs installed
$ adb shell am start -n "com.google.android.exoplayer2.demo/com.google.android.exoplayer2.demo.SampleChooserActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -D
Waiting for application to come online: com.google.android.exoplayer2.demo | com.google.android.exoplayer2.demo.test
Waiting for application to come online: com.google.android.exoplayer2.demo | com.google.android.exoplayer2.demo.test
Connecting to com.google.android.exoplayer2.demo
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
W/ActivityThread: Application com.google.android.exoplayer2.demo is waiting for the debugger on port 8100...
I/System.out: Sending WAIT chunk
I/zygote: Debugger is active
I/System.out: Debugger has connected
I/System.out: waiting for debugger to settle...
Connected to the target VM, address: 'localhost:8778', transport: 'socket'
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: debugger has settled (1302)
I/InstantRun: starting instant run server: is main process
D/OpenGLRenderer: HWUI GL Pipeline
I/zygote: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
I/OpenGLRenderer: Initialized EGL, version 1.4
D/OpenGLRenderer: Swap behavior 1
W/OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
D/OpenGLRenderer: Swap behavior 0
D/EGL_emulation: eglCreateContext: 0x981dc060: maj 3 min 0 rcv 3
D/EGL_emulation: eglMakeCurrent: 0x981dc060: ver 3 0 (tinfo 0x981a81b0)
E/eglCodecCommon: glUtilsParamSize: unknow param 0x00008cdf
E/eglCodecCommon: glUtilsParamSize: unknow param 0x00008cdf
E/eglCodecCommon: glUtilsParamSize: unknow param 0x00008824
E/eglCodecCommon: glUtilsParamSize: unknow param 0x00008824
D/EGL_emulation: eglMakeCurrent: 0x981dc060: ver 3 0 (tinfo 0x981a81b0)
I/zygote: Do partial code cache collection, code=268B, data=30KB
I/zygote: After code cache collection, code=0B, data=30KB
I/zygote: Increasing code cache capacity to 128KB
W/zygote: Got a deoptimization request on un-deoptimizable method java.lang.Class java.lang.Class.classForName(java.lang.String, boolean, java.lang.ClassLoader)
I/chatty: uid=10079(com.google.android.exoplayer2.demo) identical 4 lines
W/zygote: Got a deoptimization request on un-deoptimizable method java.lang.Class java.lang.Class.classForName(java.lang.String, boolean, java.lang.ClassLoader)
W/zygote: Verification of void com.google.android.exoplayer2.DefaultRenderersFactory.buildAudioRenderers(android.content.Context, com.google.android.exoplayer2.drm.DrmSessionManager, com.google.android.exoplayer2.audio.AudioProcessor[], android.os.Handler, com.google.android.exoplayer2.audio.AudioRendererEventListener, int, java.util.ArrayList) took 114.182ms
I/ExoPlayerImpl: Init cb6ab50 [ExoPlayerLib/2.6.1] [generic_x86, Android SDK built for x86, Google, 27]
D/EventLogger: state [0.39, true, I]
W/zygote: Got a deoptimization request on un-deoptimizable method java.lang.Object java.lang.Class.newInstance()
D/EventLogger: state [0.52, true, B]
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
W/zygote: Got a deoptimization request on un-deoptimizable method void java.io.FileInputStream.open0(java.lang.String)
W/zygote: Got a deoptimization request on un-deoptimizable method java.net.InetAddress[] libcore.io.Linux.android_getaddrinfo(java.lang.String, android.system.StructAddrinfo, int)
D/EGL_emulation: eglMakeCurrent: 0x981dc060: ver 3 0 (tinfo 0x981a81b0)
W/zygote: Got a deoptimization request on un-deoptimizable method void libcore.io.Linux.connect(java.io.FileDescriptor, java.net.InetAddress, int)
W/zygote: Got a deoptimization request on un-deoptimizable method java.net.InetAddress[] libcore.io.Linux.android_getaddrinfo(java.lang.String, android.system.StructAddrinfo, int)
W/zygote: Got a deoptimization request on un-deoptimizable method java.net.InetAddress[] libcore.io.Linux.android_getaddrinfo(java.lang.String, android.system.StructAddrinfo, int)
W/zygote: Got a deoptimization request on un-deoptimizable method java.lang.Class java.lang.Class.classForName(java.lang.String, boolean, java.lang.ClassLoader)
I/chatty: uid=10079(com.google.android.exoplayer2.demo) HlsPlaylistTrac identical 1 line
W/zygote: Got a deoptimization request on un-deoptimizable method java.lang.Class java.lang.Class.classForName(java.lang.String, boolean, java.lang.ClassLoader)
D/EventLogger: sourceInfo [periodCount=1, windowCount=1
D/EventLogger:   period [1504729088.00]
D/EventLogger:   window [321.49, true, false]
D/EventLogger: ]
D/EventLogger: loading [true]
I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
D/EventLogger: Tracks [
D/EventLogger:   Renderer:0 [
D/EventLogger:     Group:0, adaptive_supported=N/A [
D/EventLogger:       [X] Track:0, id=0, mimeType=video/avc, supported=YES
D/EventLogger:     ]
D/EventLogger:   ]
D/EventLogger: ]
D/EventLogger: videoEnabled [2.82]
W/zygote: Got a deoptimization request on un-deoptimizable method java.net.InetAddress[] libcore.io.Linux.android_getaddrinfo(java.lang.String, android.system.StructAddrinfo, int)
W/zygote: Got a deoptimization request on un-deoptimizable method void libcore.io.Linux.connect(java.io.FileDescriptor, java.net.InetAddress, int)
W/zygote: Got a deoptimization request on un-deoptimizable method java.net.InetAddress[] libcore.io.Linux.android_getaddrinfo(java.lang.String, android.system.StructAddrinfo, int)
W/zygote: Got a deoptimization request on un-deoptimizable method java.net.InetAddress[] libcore.io.Linux.android_getaddrinfo(java.lang.String, android.system.StructAddrinfo, int)
I/OMXClient: Treble IOmx obtained
D/SurfaceUtils: connecting to surface 0x973a4008, reason connectToSurface
I/MediaCodec: [OMX.google.h264.decoder] setting surface generation to 31642625
D/SurfaceUtils: disconnecting from surface 0x973a4008, reason connectToSurface(reconnect)
D/SurfaceUtils: connecting to surface 0x973a4008, reason connectToSurface(reconnect)
E/ACodec: [OMX.google.h264.decoder] setPortMode on output to DynamicANWBuffer failed w/ err -1010
D/EventLogger: videoDecoderInitialized [14.37, OMX.google.h264.decoder]
D/EventLogger: videoFormatChanged [14.56, id=1, mimeType=video/avc, res=640x360]
D/EventLogger: drmKeysLoaded [14.73]
W/zygote: Got a deoptimization request on un-deoptimizable method void android.media.MediaCodec.native_queueSecureInputBuffer(int, int, android.media.MediaCodec$CryptoInfo, long, int)
E/ExoPlayerImplInternal: Internal runtime error.
                         android.media.MediaCodec$CodecException: Error 0x80000000
                             at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
                             at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:2542)
                             at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:747)
                             at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:553)
                             at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:560)
                             at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:306)
                             at android.os.Handler.dispatchMessage(Handler.java:102)
                             at android.os.Looper.loop(Looper.java:164)
                             at android.os.HandlerThread.run(HandlerThread.java:65)
E/EventLogger: playerFailed [23.91]
               com.google.android.exoplayer2.ExoPlaybackException
                   at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:360)
                   at android.os.Handler.dispatchMessage(Handler.java:102)
                   at android.os.Looper.loop(Looper.java:164)
                   at android.os.HandlerThread.run(HandlerThread.java:65)
                Caused by: android.media.MediaCodec$CodecException: Error 0x80000000
                   at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
                   at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:2542)
                   at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:747)
                   at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:553)
                   at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:560)
                   at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:306)
                   at android.os.Handler.dispatchMessage(Handler.java:102) 
                   at android.os.Looper.loop(Looper.java:164) 
                   at android.os.HandlerThread.run(HandlerThread.java:65) 

I’m running the demo app in the emulator on a Nexus 7. I tried with a Nexus 10 and a Google Pixel 2 XL too. And they all behaves the same way.

**Comment by AquilesCanta** [comment]
This issue is being closed because it does not adhere to our issue template, and/or because it omits information requested in the issue template that is required for us to investigate the problem efficiently. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

If you’re able to provide complete information as requested in the issue template, please do so below and we’ll re-open the issue. Thanks!

**Comment by HugoSaintLaurent** [comment]
### Issue description
Playing a 3rd  Party HLS CMAF stream protected with Widevine DRM and encrypted with AES-CBCS using a 1:9 pattern doesn’t not work properly with ExoPlayer demo  application. The stream plays fine using other applications.

01/18 15:57:34: Launching demo   $ adb install-multiple -r -t   /Users/hsaintlaurent/ExoPlayer-dev-v2-r2.6.1/demos/main/buildout/intermediates/split-apk/noExtensions/debug/slices/slice_9.apk   /Users/hsaintlaurent/ExoPlayer-dev-v2-r2.6.1/demos/main/buildout/intermediates/split-apk/noExtensions/debug/slices/slice_4.apk   /Users/hsaintlaurent/ExoPlayer-dev-v2-r2.6.1/demos/main/buildout/intermediates/split-apk/noExtensions/debug/slices/slice_3.apk   /Users/hsaintlaurent/ExoPlayer-dev-v2-r2.6.1/demos/main/buildout/intermediates/split-apk/noExtensions/debug/slices/slice_2.apk   /Users/hsaintlaurent/ExoPlayer-dev-v2-r2.6.1/demos/main/buildout/intermediates/split-apk/noExtensions/debug/slices/slice_6.apk   /Users/hsaintlaurent/ExoPlayer-dev-v2-r2.6.1/demos/main/buildout/intermediates/split-apk/noExtensions/debug/slices/slice_0.apk   /Users/hsaintlaurent/ExoPlayer-dev-v2-r2.6.1/demos/main/buildout/intermediates/split-apk/noExtensions/debug/slices/slice_1.apk   /Users/hsaintlaurent/ExoPlayer-dev-v2-r2.6.1/demos/main/buildout/intermediates/split-apk/noExtensions/debug/dep/dependencies.apk   /Users/hsaintlaurent/ExoPlayer-dev-v2-r2.6.1/demos/main/buildout/intermediates/split-apk/noExtensions/debug/slices/slice_5.apk   /Users/hsaintlaurent/ExoPlayer-dev-v2-r2.6.1/demos/main/buildout/intermediates/split-apk/noExtensions/debug/slices/slice_8.apk   /Users/hsaintlaurent/ExoPlayer-dev-v2-r2.6.1/demos/main/buildout/intermediates/split-apk/noExtensions/debug/slices/slice_7.apk   /Users/hsaintlaurent/ExoPlayer-dev-v2-r2.6.1/demos/main/buildout/outputs/apk/noExtensions/debug/demo-noExtensions-debug.apk   Split APKs installed   $ adb shell am start -n   "com.google.android.exoplayer2.demo/com.google.android.exoplayer2.demo.SampleChooserActivity"   -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -D   Waiting for application to come online: com.google.android.exoplayer2.demo \|   com.google.android.exoplayer2.demo.test   Waiting for application to come online: com.google.android.exoplayer2.demo \|   com.google.android.exoplayer2.demo.test   Connecting to com.google.android.exoplayer2.demo   Capturing and displaying logcat messages from application. This behavior can   be disabled in the "Logcat output" section of the   "Debugger" settings page.   W/ActivityThread: Application com.google.android.exoplayer2.demo is waiting   for the debugger on port 8100...   I/System.out: Sending WAIT chunk   I/zygote: Debugger is active   I/System.out: Debugger has connected   I/System.out: waiting for debugger to settle...   Connected to the target VM, address: 'localhost:8778', transport: 'socket'   I/System.out: waiting for debugger to settle...   I/System.out: waiting for debugger to settle...   I/System.out: waiting for debugger to settle...   I/System.out: waiting for debugger to settle...   I/System.out: waiting for debugger to settle...   I/System.out: waiting for debugger to settle...   I/System.out: waiting for debugger to settle...   I/System.out: waiting for debugger to settle...   I/System.out: waiting for debugger to settle...   I/System.out: waiting for debugger to settle...   I/System.out: waiting for debugger to settle...   I/System.out: waiting for debugger to settle...   I/System.out: waiting for debugger to settle...   I/System.out: debugger has settled (1302)   I/InstantRun: starting instant run server: is main process   D/OpenGLRenderer: HWUI GL Pipeline   I/zygote: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay   retrieved: 0   I/OpenGLRenderer: Initialized EGL, version 1.4   D/OpenGLRenderer: Swap behavior 1   W/OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED,   retrying without...   D/OpenGLRenderer: Swap behavior 0   D/EGL_emulation: eglCreateContext: 0x981dc060: maj 3 min 0 rcv 3   D/EGL_emulation: eglMakeCurrent: 0x981dc060: ver 3 0 (tinfo 0x981a81b0)   E/eglCodecCommon: glUtilsParamSize: unknow param 0x00008cdf   E/eglCodecCommon: glUtilsParamSize: unknow param 0x00008cdf   E/eglCodecCommon: glUtilsParamSize: unknow param 0x00008824   E/eglCodecCommon: glUtilsParamSize: unknow param 0x00008824   D/EGL_emulation: eglMakeCurrent: 0x981dc060: ver 3 0 (tinfo 0x981a81b0)   I/zygote: Do partial code cache collection, code=268B, data=30KB   I/zygote: After code cache collection, code=0B, data=30KB   I/zygote: Increasing code cache capacity to 128KB   W/zygote: Got a deoptimization request on un-deoptimizable method   java.lang.Class java.lang.Class.classForName(java.lang.String, boolean,   java.lang.ClassLoader)   I/chatty: uid=10079(com.google.android.exoplayer2.demo) identical 4 lines   W/zygote: Got a deoptimization request on un-deoptimizable method   java.lang.Class java.lang.Class.classForName(java.lang.String, boolean,   java.lang.ClassLoader)   W/zygote: Verification of void   com.google.android.exoplayer2.DefaultRenderersFactory.buildAudioRenderers(android.content.Context,   com.google.android.exoplayer2.drm.DrmSessionManager,   com.google.android.exoplayer2.audio.AudioProcessor[], android.os.Handler,   com.google.android.exoplayer2.audio.AudioRendererEventListener, int,   java.util.ArrayList) took 114.182ms   I/ExoPlayerImpl: Init cb6ab50 [ExoPlayerLib/2.6.1] [generic_x86, Android SDK   built for x86, Google, 27]   D/EventLogger: state [0.39, true, I]   W/zygote: Got a deoptimization request on un-deoptimizable method   java.lang.Object java.lang.Class.newInstance()   D/EventLogger: state [0.52, true, B]   D/NetworkSecurityConfig: No Network Security Config specified, using platform   default   W/zygote: Got a deoptimization request on un-deoptimizable method void   java.io.FileInputStream.open0(java.lang.String)   W/zygote: Got a deoptimization request on un-deoptimizable method   java.net.InetAddress[] libcore.io.Linux.android_getaddrinfo(java.lang.String,   android.system.StructAddrinfo, int)   D/EGL_emulation: eglMakeCurrent: 0x981dc060: ver 3 0 (tinfo 0x981a81b0)   W/zygote: Got a deoptimization request on un-deoptimizable method void   libcore.io.Linux.connect(java.io.FileDescriptor, java.net.InetAddress, int)   W/zygote: Got a deoptimization request on un-deoptimizable method   java.net.InetAddress[] libcore.io.Linux.android_getaddrinfo(java.lang.String,   android.system.StructAddrinfo, int)   W/zygote: Got a deoptimization request on un-deoptimizable method   java.net.InetAddress[] libcore.io.Linux.android_getaddrinfo(java.lang.String,   android.system.StructAddrinfo, int)   W/zygote: Got a deoptimization request on un-deoptimizable method   java.lang.Class java.lang.Class.classForName(java.lang.String, boolean,   java.lang.ClassLoader)   I/chatty: uid=10079(com.google.android.exoplayer2.demo) HlsPlaylistTrac   identical 1 line   W/zygote: Got a deoptimization request on un-deoptimizable method   java.lang.Class java.lang.Class.classForName(java.lang.String, boolean,   java.lang.ClassLoader)   D/EventLogger: sourceInfo [periodCount=1, windowCount=1   D/EventLogger: period [1504729088.00]   D/EventLogger: window [321.49, true, false]   D/EventLogger: ]   D/EventLogger: loading [true]   I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es   D/EventLogger: Tracks [   D/EventLogger: Renderer:0 [   D/EventLogger: Group:0, adaptive_supported=N/A [   D/EventLogger: [X] Track:0, id=0, mimeType=video/avc, supported=YES   D/EventLogger: ]   D/EventLogger: ]   D/EventLogger: ]   D/EventLogger: videoEnabled [2.82]   W/zygote: Got a deoptimization request on un-deoptimizable method   java.net.InetAddress[] libcore.io.Linux.android_getaddrinfo(java.lang.String,   android.system.StructAddrinfo, int)   W/zygote: Got a deoptimization request on un-deoptimizable method void   libcore.io.Linux.connect(java.io.FileDescriptor, java.net.InetAddress, int)   W/zygote: Got a deoptimization request on un-deoptimizable method   java.net.InetAddress[] libcore.io.Linux.android_getaddrinfo(java.lang.String,   android.system.StructAddrinfo, int)   W/zygote: Got a deoptimization request on un-deoptimizable method   java.net.InetAddress[] libcore.io.Linux.android_getaddrinfo(java.lang.String,   android.system.StructAddrinfo, int)   I/OMXClient: Treble IOmx obtained   D/SurfaceUtils: connecting to surface 0x973a4008, reason connectToSurface   I/MediaCodec: [OMX.google.h264.decoder] setting surface generation to 31642625   D/SurfaceUtils: disconnecting from surface 0x973a4008, reason   connectToSurface(reconnect)   D/SurfaceUtils: connecting to surface 0x973a4008, reason   connectToSurface(reconnect)   E/ACodec: [OMX.google.h264.decoder] setPortMode on output to DynamicANWBuffer   failed w/ err -1010   D/EventLogger: videoDecoderInitialized [14.37, OMX.google.h264.decoder]   D/EventLogger: videoFormatChanged [14.56, id=1, mimeType=video/avc,   res=640x360]   D/EventLogger: drmKeysLoaded [14.73]   W/zygote: Got a deoptimization request on un-deoptimizable method void   android.media.MediaCodec.native_queueSecureInputBuffer(int, int,   android.media.MediaCodec$CryptoInfo, long, int)   E/ExoPlayerImplInternal: Internal runtime error.   android.media.MediaCodec$CodecException: Error 0x80000000   at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)   at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:2542)   at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:747)   at   com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:553)   at   com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:560)   at   com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:306)   at android.os.Handler.dispatchMessage(Handler.java:102)   at android.os.Looper.loop(Looper.java:164)   at android.os.HandlerThread.run(HandlerThread.java:65)   E/EventLogger: playerFailed [23.91]   com.google.android.exoplayer2.ExoPlaybackException   at   com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:360)   at android.os.Handler.dispatchMessage(Handler.java:102)   at android.os.Looper.loop(Looper.java:164)   at android.os.HandlerThread.run(HandlerThread.java:65)   Caused by: android.media.MediaCodec$CodecException: Error 0x80000000   at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)   at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:2542)   at   com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:747)   at   com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:553)   at   com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:560)   at   com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:306)   at android.os.Handler.dispatchMessage(Handler.java:102)    at android.os.Looper.loop(Looper.java:164)    at android.os.HandlerThread.run(HandlerThread.java:65)

### Reproduction steps
Edit the Demo   application’s media.exolist.json to add the new stream. Stream information   will be provided with the link to the test content via email.

### Link to test content
A link to the test content will be emailed to dev.exoplayer@gmail.com

### Version of ExoPlayer being used
ExoPlayer 2.6.1.

### Device(s) and version(s) of Android being used
Nexus 7 emulator,   Android 8 SDK 27   Nexus 10 emulator,   Android 8 SDK 27   Google Pixel 2 XL   emulator, Android 8 SDK 27   Google Pixel phone,   Android 8 SDK 27
reproduced, and how   easily it reproduces. If possible, please test on multiple
devices and Android   versions.

### A full bug report captured from the device
The full bug report log will be attach to the email sent to dev.exoplayer@gmail.com

**Comment by orinda** [comment]
Is HLS Sample-AES CMAF CBCS for Widevine fully supported by ExoPlayer?

**Comment by AquilesCanta** [comment]
> Is HLS Sample-AES CMAF CBCS for Widevine fully supported by ExoPlayer?

Yes. You might run into device specific issues. Please let us know if that's the case (through a new issue including all information required in the issue template). If you think there is a specific aspect that is not supported, also let us know.
