### ISSUE TITLE
Offline Widevine DRM Downloaded but not alble to Play

### ISSUE THREAD

**Issue by HungamaSurat** [google/ExoPlayer#3730]
Issue description:
-----------------------
- We are trying to play Offline DRM Video(.mpd formated) Encoded with Widevine(Secure Expressplay URL). Here, 
We tried with updated ExoPlayer v2.6.0. Downloaded DRM content through below code.

//------------- Download code ----------------//
File tempFolder = Util.createTempDirectory(SampleChooserActivity.this, "ExoPlayerTest");
tempFolder.mkdir();
cache = new SimpleCache(tempFolder, new NoOpCacheEvictor());
DownloaderConstructorHelper constructorHelper = new DownloaderConstructorHelper(cache, new DefaultHttpDataSourceFactory("ExoPlayer", null));
DashDownloader dashDownloader = new DashDownloader(Uri.parse(path), constructorHelper);
dashDownloader.init();
dashDownloader.download(new Downloader.ProgressListener() {
@override
public void onDownloadProgress(Downloader downloader, float downloadPercentage, long downloadedBytes) {
Log.i("createDashDownloader","createDashDownloader::"+downloadPercentage);
}
});

It's generating .exo files and cached_content_index.exi file.
In demo app, There is no any option to test Offline DRM.

try {
DataSource dataSource = httpDataSourceFactory.createDataSource();
DashManifest dashManifest = DashUtil.loadManifest(dataSource,
Uri.parse(SampleChooserActivity.path));
DrmInitData drmInitData = DashUtil.loadDrmInitData(dataSource, dashManifest.getPeriod(0));
byte[] offlineAssetKeyId1 = offlineLicenseHelper.downloadLicense(drmInitData);
Log.i("OfflineKey", "OfflineKey");
} catch (IOException e) {
e.printStackTrace();
} catch (InterruptedException e) {
e.printStackTrace();
} catch (Exception e) {
e.printStackTrace();
}

Is there any code to play downloaded content (.exo or .exi)?

### Version of ExoPlayer being used
We are using latest ExoPlayer version. v2.6.0

### Device(s) and version(s) of Android being used
We are getting issue in all device which are above 4.1 OS. We tried with higher devices like Nexus 5 / Nexus 6 / Moto G4 etc.

### Check below issue for more details
https://github.com/google/ExoPlayer/issues/3204

**Comment by HungamaSurat** [comment]
Hello Erdem Guven,

Did you get chance to checkout this issue?
Please give me feedback as soon as possible.

Thanks

**Comment by erdemguven** [comment]
You need to create a CacheDataSource instance using the SimpleCache and use it with your player. Warning, please avoid creating multiple SimpleCache instances working on the same folder.

To use the offlined license you need to call: 
`drmSessionManager.setMode(DefaultDrmSessionManager.MODE_PLAYBACK, offlineLicenseKeySetId);`
Please check the demo app to see how drmSessionManager is created.
