### ISSUE TITLE
WebvttDecoder final and private :-(

### ISSUE THREAD

**Issue by toby78** [google/ExoPlayer#3732]
I would like to extend WebvttDecoder.
Unfortunately it is final and private.

Is there any particular reason for this?

**Comment by ojw28** [comment]
What is your use case for needing to do this? I don't think we'll have any particular objection to doing this, but we'd like to understand the use case and make sure there's not a better way for achieving the same thing. Thanks.

Aside: It actually public already on the `dev-v2` branch, although it's still final.

**Comment by ojw28** [comment]
Closed due to lack of additional information.
