### ISSUE TITLE
ExoPlayer is dark/faded when backgroundDimEnabled is set

### ISSUE THREAD

**Issue by ParkerK** [google/ExoPlayer#3733]
I just switched over to ExoPlayer from VideoView, and I love it, but for some reason the video appears dark / faded on some devices. It's as if there's a dark overlay on the video surface. None of the other components (images, appbar, etc) appear dark, it's just ExoPlayer. This issue happens on some devices like Android Emulator, LG, ZTE, etc, but doesn't seem to occur on others, like Samsung. 

This is on ExoPlayer 2.6.1 on Nougat

Edit: Found the culprit, it's when `android:backgroundDimEnabled` is set to true in the style. Is there any workaround for this? Or is there a way to get ExoPlayer to override this?

Screenshot of dark video:
![screenshot_1516470051](https://user-images.githubusercontent.com/464971/35186294-db3fe060-fddf-11e7-8054-9b8ef4e914a0.png)

**Comment by ParkerK** [comment]
Found the issue, it's due to `SurfaceView`: https://stackoverflow.com/questions/5161411/on-android-emulator-hw-too-an-activity-style-with-backgrounddimenabled-also-d

Casting `simpleExoPlayers.getVideoSurfaceView()` to `SurfaceView` and calling `setZOrderOnTop(true)` fixes this.

**Comment by ojw28** [comment]
Closing, since it sounds like you've found a way of avoiding the issue (and it's not an ExoPlayer issue).
