### ISSUE TITLE
Expose aspect ratio deformation

### ISSUE THREAD

**Issue by denizmveli** [google/ExoPlayer#3736]
### Feature request 

Expose the aspect ratio deformation in a useful way for our UI to know if we should show a button to toggle resize modes.

Scenario = 18:9 wide phones like the s8 / pixel 2 XL need a custom feature to allow users to toggle between resize modes (ZOOM and FIT). Similarly viewing 4:3 content on a 16:9 device. It's great that Exo supports these zoom modes....but....

I don't want to show a full screen resize button if the aspect ratio isn't deformed. I'd like to know if the video aspect ratio and the view aspect ratio are the same (within a given tolerance like `MAX_ASPECT_RATIO_DEFORMATION_FRACTION`).

The code for all this logic exists across `SimpleExoPlayerView` and `AspectRatioFrameLayout`. It's tricky to replicate.

Request would be for a property on the `SimpleExoPlayerView` called `aspectRatioDeformation()`

**Comment by denizmveli** [comment]
Any milestone planned for adding this?

**Comment by botaydotcom** [comment]
Hi @denizmveli, 
Sorry for the late update. This is currently being worked on and will be pushed to dev branch in the next few days.

**Comment by botaydotcom** [comment]
Hi @denizmveli,
The  mentioned change has now been pushed to dev-v2. Please help me to test it and see if it can solve your issue. Thank you.
