### ISSUE TITLE
AmLogic S905D - Cannot be seamless when switch videos from .webm to .mp4 

### ISSUE THREAD

**Issue by noah538** [google/ExoPlayer#3743]
### Issue description

“Transitions between sources are seamless. There is no requirement that the sources being concatenated are of the same format (e.g. it’s fine to concatenate a video file containing 480p H264 with one that contains 720p VP9).” - Medium
 
when videos change from .mp4 to .mp4  are seamless. 
But it is not seamless when change videos from .webm to .mp4. 
The result will be “reinitialize codec and cause a black screen flash.”

### Reproduction steps
By using demo application (already taken care shutterview set to INVISIBLE) to test seamless between vp9 and avc format. In media.exolist.json:

"playlist": [
  { "uri": "/sdcard/Movies/4k.mp4" },
  { "uri": "/sdcard/Movies/4k.webm" }
]
it will always return TRUE in:

boolean areAdaptationCompatible(boolean codecIsAdaptive, Format first, Format second)
 {
//run-time info:
// exoplayer version release-v2
// codecIsAdaptive=true
// first.sampleMimeType=”video/x-vnd.on2.vp9"
// second.sampleMimeType="video/avc”

 return first.sampleMimeType.equals(second.sampleMimeType) …  => TRUE
}

and the result is “reinitialize codec and cause a black screen flash.” (not seamless)

### Link to test content
N/A

### Version of ExoPlayer being used
ExoPlayer-release-v2

### Device(s) and version(s) of Android being used
An Amlogic S905D device capable to decode UHD video

### A full bug report captured from the device
There is nothing special in the logcat with this issue.

**Comment by ojw28** [comment]
* Codec re-initialization shouldn't result in a black screen flash. Is this issue specific to the Amlogic device, or can you reproduce on all devices? If it's device specific, you'll need to report the problem to the device manufacturer. If it's not device specific, please provide us with concrete reproduction steps, including sample media that reproduces the issue.
* You shouldn't need to do anything special to the shutter view for this use case. It should work as-is.

**Comment by noah538** [comment]
"Codec re-initialization shouldn't result in a black screen flash." Thanks for your useful information. 
I will try another pad and box (different chip) and report if it is a device specified issue.

**Comment by noah538** [comment]
I cannot reproduce this issue on another STB with different chip, so it is confirmed a device specific issue.
Thank you for your kindly help.

**Comment by ojw28** [comment]
Please report the issue to the device manufacturer. Thanks!
