### ISSUE TITLE
Request for comments on leap second handling

### ISSUE THREAD

**Issue by sandersaares** [google/ExoPlayer#3744]
DASH-IF has published document for community review.

LEAP SECOND HANDLING CLARIFICATIONS

* The change request against IOP v4.1 for [Community Review is accessible here](http://dashif.org/wp-content/uploads/2018/01/CR-leapseconds-community-review.pdf)
* Community review is open until April 15th, 2018. Addition to IOP is expected by Q2/2018.
* Comments may be submitted through the [public bugtracker](https://gitreports.com/issue/Dash-Industry-Forum/DASH-IF-IOP).
* This addition adds the following main features: Clarifies how to handle leap seconds and how to avoid common pitfalls

It would be very desirable to hear some feedback from player developers on this topic!

**Comment by ojw28** [comment]
I took a quick look at this a few weeks ago and it looked pretty sensible. I didn't spot anything obviously problematic. Having said that, I wasn't able to spend too long on it due to time constraints. Sorry to not be more helpful!
