### ISSUE TITLE
[Enhancement] make PlaybackControlView.hideAfterTimeout() public

### ISSUE THREAD

**Issue by yurilaguta** [google/ExoPlayer#3749]
### Issue description
When adding extra buttons to PlaybackControlView there is no public API to prevent controls to hide. It would be great for clients of the library who adding some buttons, to be able to extend hide time.

### Reproduction steps
Add custom button to SimpleExoPlayerView through app:controller_layout_id
keep clicking button until UI disappears default 5 seconds.

### Version of ExoPlayer being used
2.6.0

### Device(s) and version(s) of Android being used
Easily reproduced any device or version.

**Comment by ojw28** [comment]
@marcbaechinger - Probably worth making sure that your VisibilityManager change covers this case :).

**Comment by yurilaguta** [comment]
Actually after a bit deeper digging, SimpleExoPlayerView showController() covers this scenario.
