### ISSUE TITLE
SSMediaSource on load canceled calling load completed?

### ISSUE THREAD

**Issue by jorgevila** [google/ExoPlayer#3754]
Hi,

on SSMediaSource, I found that on method onLoadCanceled, the event being dispatched is onLoadCompleted.

Is that right?

https://github.com/google/ExoPlayer/blob/2b20780482a9c6b07416bcbf4de829532859d10a/library/smoothstreaming/src/main/java/com/google/android/exoplayer2/source/smoothstreaming/SsMediaSource.java#L432

  @Override
  public void onLoadCanceled(ParsingLoadable<SsManifest> loadable, long elapsedRealtimeMs,
      long loadDurationMs, boolean released) {
    eventDispatcher.loadCompleted(loadable.dataSpec, loadable.type, elapsedRealtimeMs,
        loadDurationMs, loadable.bytesLoaded());
  }

Best regards

**Comment by botaydotcom** [comment]
Thanks for spotting this. I think this is a slight mistake, which has been there for quite some time and no one noticed this. We will update the code to dispatch cancelled event here.

**Comment by jorgevila** [comment]
Cool! 

thank you!

**Comment by botaydotcom** [comment]
The fix has been submitted and will be pushed to dev-v2 soon.
