### ISSUE TITLE
[Question] Equivalent to Allocator.blockWhileTotalBytesAllocatedExceeds(int limit) in ExoPlayer 2?

### ISSUE THREAD

**Issue by kathylin** [google/ExoPlayer#3755]
Is there an equivalent call or blocks of calls to replace Allocator.blockWhileTotalBytesAllocatedExceeds(int limit) in ExoPlayer 2?  Migrating from ExoPlayer 1.5 to Exoplayer2 but can't find a proper way to implement blockWhileTotalBytesAllocatedExceeds(int  #limit).

**Comment by botaydotcom** [comment]
Hi @kathylin 
I don't think there's an equivalent call in ExoPlayerV2 for this purpose. Could you describe your use case: when do you need to call this?
If the use case is similar to our original `ExtractorSampleSource.ExtractingLoadable`, you can consider using an alternative, which we implemented for the V2 equivalent of `ExtractingLoadable` (please see: 
`ExtractorMediaPeriod.ExtractingLoadable`):

In this case, you can use a loading condition variable, which is checked on the loading thread (`ExtractingLoadable`), and prevents the `ExtractingLoadable` from advancing too far (it will block when the loading thread has advanced more than a given threshold). After the loading thread passes this threshold, it will post a callback `onContinueLoadingRequested` to allow the `LoadControl` to decide whether the loading thread can continue, and then block on the condition variable. When the `LoadControl` allows the `MediaPeriod` to continue, `MediaPerod.continueLoading()` method will being called, and in this method, you can re-open the loading condition variable and allow the loading thread to continue.

**Comment by kathylin** [comment]
@botaydotcom, thanks for your reply.  Yes, we use `Allocator.blockWhileTotalBytesAllocatedExceeds(int limit)` similar to the original 
`ExtractorSampleSource.ExtractingLoadable`.  We will try your suggestion and see if we can get the migration working.  Thanks!
