### ISSUE TITLE
[Question] Did "DRM vender –2967" error ever happen in ExoPlayer?

### ISSUE THREAD

**Issue by ghost** [google/ExoPlayer#3756]
This isn't an issue for Exoplayer. Just a question.

I implemented an Android player by using mediacodec directly. Sometimes it throws "DRM vender –2967" when using widevine drm on Pixel and some Samsung devices. This is a serious error. The playback can not recover until the system is rebooted. It may trigger a system level error. 

I just want to know if "DRM vender –2967" error ever happened in ExoPlayer. Do you get any issue or feedback about this error?

Thanks

**Comment by botaydotcom** [comment]
Hi @ycinfinity ,
I did a quick search on both Github issue list and internal issue list. There's one more report on DRM error -2967 happening with Widevine DRM on Pixel on our internal issue list ([Internal ref: 62486203]), although there is no mention of ExoPlayer on that bug.

@wvpaf : Did you encounter any other report for this error?

**Comment by ghost** [comment]
Hi, We can encounter this issue 2000 times a day from the android player of my company.  Then the user need to reboot the system. That's terrible.  Do you have any investigation on this error?

**Comment by wvpaf** [comment]
@botaydotcom, the only other report the one you found, that report went cold after a few months and was closed due to inactivity and the fact we were unable to repro in house.

@ycinfinity, it would be most helpful to have an ADB report from an affected device so we can better troubleshoot.

**Comment by ycinfinity** [comment]
This is the log which is related to the issue. 
[android.log](https://github.com/google/ExoPlayer/files/1676580/android.log)

**Comment by ojw28** [comment]
Can you provide a full bug report captured with `adb bugreport`, rather than a snippet of logcat? Thanks.

**Comment by ghost** [comment]
@ojw28  @wvpaf  I'm trying to reproduce the issue and collect a more detailed log.  Could you give an email address for further communication?

**Comment by ojw28** [comment]
Please use `dev.exoplayer@gmail.com`. Please also update this issue when you mail that address, so the right person knows to take a look. Thanks!

**Comment by wvpaf** [comment]
Any luck with the full adb bugreport?

**Comment by ghost** [comment]
Hi @wvpaf, I'm still trying to reproduce it in my own android phone to generate a full adb bugreport.
The error mostly happens in our user's client. It could be in a special situation. But I can't force the normal user to do the "adb bugreport". I will send the bugreport to you as soon as I reproduce the issue.

**Comment by ghost** [comment]
Hi @ojw28 @wvpaf , I reproduced it. And already sent the bugreport to dev.exoplayer@gmail.com.

Topic: Bugreport for DRM vender –2967 Address: ycinfinity@hotmail.com

**Comment by ghost** [comment]
@wvpaf , Any update about this issue? Do you need other information?

**Comment by wvpaf** [comment]
@ycinfinity got the logs via email. thanks. 
the team will take a look.

**Comment by wvpaf** [comment]
There is a fix for this has been checked into P. 
Else to workaround is reboot the device and/or stop and restart the mediaserver.

**Comment by ghost** [comment]
@wvpaf Thanks for fixing this issue. 

What do you mean "stop and restart the mediaserver"? 

Do you have a plan to fix this issue in the versions before Android P?  Rebooting the device and restarting the media server are not reasonable solutions for this issue.
