### ISSUE TITLE
Amazon Kindle low volume  

### ISSUE THREAD

**Issue by ouchadam** [google/ExoPlayer#3758]
## Issue Description

We're having reports from users that their Kindle devices have experienced a volume decrease after upgrading from exoplayer `r2.4.4`.

## Reproduction

We're able to reproduce consistently by playing any content in the current (r2.6.1) demo app and comparing the volume level against the MediaPlayer or the `r2.4.4` release.

The following Amazon Kindle devices are affected:

```
KFASWI FireOS 5.6.0.0 & FireOS 5.6.0.1  
KFSAWI FireOS 5.4.0.0

Reported by users, version unknown
KFTBWI
KFMEWI 
```

## Cause

It appears that ExoPlayer r2.5.0 introduced a separate v21+ audioTrack creation which changed the default audio contentType from [MUSIC to UNKNOWN](https://github.com/google/ExoPlayer/compare/cbffc14fa1ba2fa84379e95679f649cb8605e805...r2.5.0?diff=split&name=r2.5.0#diff-2716a5e2150b041bfac29ec067c43c0eL387).

## Potential Solution

Changing the default `AudioAttributes.contentType` [contentType = C.CONTENT_TYPE_UNKNOWN;](https://github.com/google/ExoPlayer/blob/dev-v2/library/core/src/main/java/com/google/android/exoplayer2/audio/AudioAttributes.java#L55) to `contentType = C.CONTENT_TYPE_MUSIC;` fixes the issue.

**Comment by andrewlewis** [comment]
You can just set your app's audio content type via `SimpleExoPlayer.setAudioAttributes`. If you're not using `SimpleExoPlayer` please consult that method's implementation to see how to set the audio attributes. Given we don't know the content type, `CONTENT_TYPE_UNKNOWN` seems like the right default.

**Comment by ouchadam** [comment]
thanks for pointing out that api, solves the problem!
