### ISSUE TITLE
Video not playing unless the audio track is turned off

### ISSUE THREAD

**Issue by zvonkokemperle** [google/ExoPlayer#376]
Hi,

Device: Sony Xperia C5303
OS version: 4.3
Exo Player version: master branch v1.2.3

When trying to play the video : 

http://shadowcdn-01.yumenetworks.com/ym/1349/EyQDMrmG_1600K_1280x720.mp4

The video will not start, unless I turn off the audio track, then the video starts to play. If I turn on the audo track again the the video stops

LogCat output:

04-01 08:43:16.186    5799-5799/com.google.android.exoplayer.demo I/ExoPlayerImpl﹕ Init 1.2.4
04-01 08:43:16.186    5799-5799/com.google.android.exoplayer.demo D/EventLogger﹕ start [0]
04-01 08:43:16.196    5799-5799/com.google.android.exoplayer.demo D/EventLogger﹕ state [0.00, false, P]
04-01 08:43:16.196    5799-5799/com.google.android.exoplayer.demo D/EventLogger﹕ state [0.00, true, I]
04-01 08:43:16.206    5799-5799/com.google.android.exoplayer.demo D/EventLogger﹕ state [0.01, true, P]
04-01 08:43:16.366    5799-6627/com.google.android.exoplayer.demo I/SampleTable﹕ There are reordered frames present.
04-01 08:43:16.366    5799-6627/com.google.android.exoplayer.demo D/QCUtils﹕ extended extractor not needed, return default
04-01 08:43:16.366    5799-5799/com.google.android.exoplayer.demo D/EventLogger﹕ state [0.18, true, B]
04-01 08:43:16.376    5799-6630/com.google.android.exoplayer.demo I/OMXClient﹕ Using client-side OMX mux.
04-01 08:43:16.526    5799-6636/com.google.android.exoplayer.demo I/OMXClient﹕ Using client-side OMX mux.
04-01 08:43:16.536    5799-6636/com.google.android.exoplayer.demo E/OMXMaster﹕ A component of name 'OMX.qcom.audio.decoder.aac' already exists, ignoring this one.
04-01 08:43:16.546    5799-6637/com.google.android.exoplayer.demo I/SoftAAC2﹕ Reconfiguring decoder: 0->44100 Hz, 0->2 channels, mNumChannels 2
04-01 08:43:16.556    5799-6636/com.google.android.exoplayer.demo I/OMXNodeInstance﹕ OMX_FreeBuffer for buffer header 0x5efc26a0 successful
04-01 08:43:16.556    5799-6636/com.google.android.exoplayer.demo I/OMXNodeInstance﹕ OMX_FreeBuffer for buffer header 0x5efc25a0 successful
04-01 08:43:16.556    5799-6636/com.google.android.exoplayer.demo I/OMXNodeInstance﹕ OMX_FreeBuffer for buffer header 0x5efc2488 successful
04-01 08:43:16.556    5799-6636/com.google.android.exoplayer.demo I/OMXNodeInstance﹕ OMX_FreeBuffer for buffer header 0x5efc2288 successful
04-01 08:43:16.726    5799-5799/com.google.android.exoplayer.demo D/EventLogger﹕ videoSizeChanged [1280, 720, 1.0]
04-01 08:43:16.726    5799-6630/com.google.android.exoplayer.demo I/QCUtils﹕ Calling native window update buffer geometry [1280 x 720]
04-01 08:43:16.766    5799-5799/com.google.android.exoplayer.demo D/EventLogger﹕ state [0.57, true, R]
04-01 08:43:19.389    5799-6629/com.google.android.exoplayer.demo I/NuCachedSource2﹕ ERROR_END_OF_STREAM

**Comment by zvonkokemperle** [comment]
The same also happens of ExoPlayer v1.2.4.Rc. Here is also the dump what happens if I turn the audio track off and then on again.

04-01 08:56:56.341    5799-5799/com.google.android.exoplayer.demo D/dalvikvm﹕ GC_FOR_ALLOC freed 3232K, 35% free 9700K/14756K, paused 11ms, total 11ms
04-01 08:56:58.103    5799-7611/com.google.android.exoplayer.demo I/OMXNodeInstance﹕ OMX_FreeBuffer for buffer header 0x5ee5bde8 successful
04-01 08:56:58.103    5799-7611/com.google.android.exoplayer.demo I/OMXNodeInstance﹕ OMX_FreeBuffer for buffer header 0x5ed71ca8 successful
04-01 08:56:58.103    5799-7611/com.google.android.exoplayer.demo I/OMXNodeInstance﹕ OMX_FreeBuffer for buffer header 0x5c94cd80 successful
04-01 08:56:58.113    5799-7611/com.google.android.exoplayer.demo I/OMXNodeInstance﹕ OMX_FreeBuffer for buffer header 0x5eeaa118 successful
04-01 08:56:58.113    5799-7611/com.google.android.exoplayer.demo I/OMXNodeInstance﹕ OMX_FreeBuffer for buffer header 0x5f127e30 successful
04-01 08:56:58.113    5799-7611/com.google.android.exoplayer.demo I/OMXNodeInstance﹕ OMX_FreeBuffer for buffer header 0x5f168618 successful
04-01 08:56:58.113    5799-7611/com.google.android.exoplayer.demo I/OMXNodeInstance﹕ OMX_FreeBuffer for buffer header 0x5ee63f10 successful
04-01 08:56:58.113    5799-7611/com.google.android.exoplayer.demo I/OMXNodeInstance﹕ OMX_FreeBuffer for buffer header 0x5c95fdc8 successful
04-01 08:56:58.353    5799-5890/com.google.android.exoplayer.demo I/qtaguid﹕ Failed write_ctrl(u 78) res=-1 errno=22
04-01 08:56:58.353    5799-5890/com.google.android.exoplayer.demo I/qtaguid﹕ Untagging socket 78 failed errno=-22
04-01 08:57:00.365    5799-5890/com.google.android.exoplayer.demo I/qtaguid﹕ Failed write_ctrl(u 81) res=-1 errno=22
04-01 08:57:00.365    5799-5890/com.google.android.exoplayer.demo I/qtaguid﹕ Untagging socket 81 failed errno=-22
04-01 08:57:00.375    5799-5890/com.google.android.exoplayer.demo I/qtaguid﹕ Failed write_ctrl(u 82) res=-1 errno=22
04-01 08:57:00.375    5799-5890/com.google.android.exoplayer.demo I/qtaguid﹕ Untagging socket 82 failed errno=-22
04-01 08:57:08.173    5799-7655/com.google.android.exoplayer.demo I/OMXClient﹕ Using client-side OMX mux.
04-01 08:57:08.183    5799-7655/com.google.android.exoplayer.demo E/OMXMaster﹕ A component of name 'OMX.qcom.audio.decoder.aac' already exists, ignoring this one.
04-01 08:57:08.183    5799-5799/com.google.android.exoplayer.demo D/EventLogger﹕ state [17.86, true, B]
04-01 08:57:08.203    5799-7656/com.google.android.exoplayer.demo I/SoftAAC2﹕ Reconfiguring decoder: 0->44100 Hz, 0->2 channels, mNumChannels 2
04-01 08:57:08.203    5799-7655/com.google.android.exoplayer.demo I/OMXNodeInstance﹕ OMX_FreeBuffer for buffer header 0x5f2b0fd8 successful
04-01 08:57:08.203    5799-7655/com.google.android.exoplayer.demo I/OMXNodeInstance﹕ OMX_FreeBuffer for buffer header 0x5f2b0f08 successful
04-01 08:57:08.203    5799-7655/com.google.android.exoplayer.demo I/OMXNodeInstance﹕ OMX_FreeBuffer for buffer header 0x5f14ed98 successful
04-01 08:57:08.203    5799-7655/com.google.android.exoplayer.demo I/OMXNodeInstance﹕ OMX_FreeBuffer for buffer header 0x5ee62b28 successful
04-01 08:57:08.213    5799-5799/com.google.android.exoplayer.demo D/EventLogger﹕ state [17.90, true, R]

**Comment by dnutcracker** [comment]
This also happens on LG G2

**Comment by ojw28** [comment]
- The MP4 file you link to is invalid. The specific issue is that there are negative sample offsets inside version 0 ctts boxes in the file. Version 0 ctts boxes only permit positive sample offsets; the boxes should probably be marked as version 1 instead.
- It's unclear if this issue is directly related to why these devices don't play the content. In any case, we're implementing an MP4 extractor in ExoPlayer, and using that will allow you to successfully play this (and similar) content. ETA to push an updated version is later this week, at which point you should just use that instead.

**Comment by zvonkokemperle** [comment]
Thanks, I will wait then for the updated version.

**Comment by ojw28** [comment]
Please try playing the sample using TYPE_MP4 on the latest dev. Does that work for you?

**Comment by zvonkokemperle** [comment]
Great, it is working thanks you very much.

**Comment by u3breeze** [comment]
Same issue:  Exo Player version: master branch r1.5.6
Can you tell me how to solve this issue detailed. 
"Please try playing the sample using TYPE_MP4 on the latest dev. Does that work for you?", how to use TYPE_MP4.
thanks.

**Comment by andrewlewis** [comment]
@u3breeze TYPE_MP4 was moved/renamed to Util.TYPE_OTHER. If you set this as the type for a sample in the demo app, the player will be built using [ExtractorRendererBuilder](https://github.com/google/ExoPlayer/blob/master/demo/src/main/java/com/google/android/exoplayer/demo/player/ExtractorRendererBuilder.java), which uses ExtractorSampleSource. This is the recommended source for playing MP4s and other multimedia containers in recent versions (not FrameworkSampleSource, which is now deprecated).

**Comment by u3breeze** [comment]
@andrewlewis thank you for your replay.  
Yes, i did it like you said.  but "Video not playing unless the audio track is turned off".
My test video is "http://pili-media.huacehuaban.com/10000009021459869533.mp4".
you can test it in the demo (latest master or dev branch) , can find the issue. 

can you help me? thanks.

**Comment by andrewlewis** [comment]
@u3breeze The audio/video tracks are not well interleaved in that MP4 file (the audio samples start at about 18 MB). This is the same issue as #1405, #1368.

**Comment by andrewlewis** [comment]
Correction: #1386 not #1368.
