### ISSUE TITLE
v2.4.0 Unable to play the video after pausing.

### ISSUE THREAD

**Issue by akshaygore06** [google/ExoPlayer#3760]
I am using exoplayer in my ReactNative App. I have upgraded the exo player version from 2.0.4 to 2.4.0 but facing an issue with the play button.

I am **unable to see the play button after pausing** the video.

The same video source works fine in 2.0.4 version

Video Plays normally 

![screen shot 2018-01-26 at 10 33 14 am](https://user-images.githubusercontent.com/9061850/35454842-878c9b44-0284-11e8-8a67-2297df407c89.png)

Play button is hidden after pausing the video

![screen shot 2018-01-26 at 10 33 32 am](https://user-images.githubusercontent.com/9061850/35454876-a54161ba-0284-11e8-8ae4-77a10763eacd.png)

Can you help me to understand why it is happening and solution to this issue?
Also, Is there any way to set the visibility of play and pause buttons of SimpleExoPlayerView?

@ojw28 @andrewlewis

**Comment by ojw28** [comment]
Unless this is reproducible with our demo app, then I can't really think how this could happen short of application code interfering with our UI component. Please see if you can reproduce in the demo app.

**Comment by ojw28** [comment]
Closing on the assumption this is an issue in application code.
