### ISSUE TITLE
How to get event when ad playing end ?

### ISSUE THREAD

**Issue by ZohaibGhafoor** [google/ExoPlayer#3761]
How to get event when ad playing end and content start.

**Comment by andrewlewis** [comment]
You can store the value returned by `player.isPlayingAd()` each time [`onPositionDiscontinuity`](https://github.com/google/ExoPlayer/blob/dev-v2-r2.6.1/library/core/src/main/java/com/google/android/exoplayer2/Player.java#L113) is called on your player event listener. If the value changes from true to false, that's a transition from ad to content.

(This will be a bit easier soon, as there will be a position discontinuity with the reason set to `DISCONTINUITY_REASON_AD_INSERTION` each time a discontinuity occurs as a result of transitioning between ad/content, but this is only on the development branch `dev-v2` for now.)

**Comment by ZohaibGhafoor** [comment]
@andrewlewis Sometimes we don't need content and want to only play the ad . but when i put empty string on content url then on ad end onPositionContiniuty not called. what should i do now ?

**Comment by andrewlewis** [comment]
Playing ads without content is tracked by #3774.
