### ISSUE TITLE
IMA resumes content if the player is paused when the first ad loads

### ISSUE THREAD

**Issue by andrewlewis** [google/ExoPlayer#3764]
Steps to reproduce:
1. Add a call `setPlayWhenReady(false)` in the demo app before preparing the player.
2. Play 'VMAP pre-roll single ad, mid-roll standard pods with 5 ads every 10 seconds'.

Observed: content resumes after a few seconds. Expected: the ad should remain visible in the paused state.

**Comment by andrewlewis** [comment]
I think this used to work, so it may be a regression in `ImaAdsLoader` or in the IMA SDK.

**Comment by andrewlewis** [comment]
[Internal reference: b/73123339]

**Comment by na-in-lee** [comment]
[2 ads - just linear vast not vmap midroll]
When the user presses the home button (background)  during play first ad, the player automatically paused, user screen turned on (foreground), The player shows only the first ad and goes to the content(without play the second ad)
Ad skins also become skip ad and change 1/2 to 2/2 while the first ad is playing.

When will it be fixed?

**Comment by andrewlewis** [comment]
@na-in-lee This issue tracks starting ads in the paused state, whereas your issue (ads skipped after resuming the app) is more similar to #4140. Please could you post your ad tag on that issue so we can reproduce the issue and follow up with the IMA team? Thanks.

**Comment by na-in-lee** [comment]
I Fixed issue.

#4153 fixes applied. then Added code below.

File : ImaAdsLoader.java

    private void handleAdEvent(AdEvent adEvent) {
            Ad ad = adEvent.getAd();
            switch (adEvent.getType()) {
                case LOADED:
                    // The ad position is not always accurate when using preloading. See [Internal: b/62613240].
                    if(imaPausedContent == true) return;    <--- added code.
[2 ads]
bug: firsts ad play > user skip ad click > contents play
fix : firsts ad play > user skip ad click > second ad play > skip ad click > contents play

**Comment by andrewlewis** [comment]
Testing with version 2.9.0 and IMA SDK 3.9.4 this seems to be fixed.
