### ISSUE TITLE
Sideload Multiple Subtitles and Switch between subtitle on  video play

### ISSUE THREAD

**Issue by rburade21** [google/ExoPlayer#3765]
I  managed to add single subtitle using MergingMediaSource(),
i am not getting how to add multiple subtitle file and to switch between them on playback
i tried demo app code but it is too complex for me.
Classes like TextRenderer,TextTrackRederee,SingleSampleMediaSource and methods like
DefaultUriDataSource(context, bandwidthMeter, userAgent); 
![untitled](https://user-images.githubusercontent.com/32266464/35510968-2f1e8690-0520-11e8-84de-294e91f3c906.png)

are not resolving at all.
plz post simple code snippet to get me out of this problem.

**Comment by ojw28** [comment]
If you got a single subtitle using `MergingMediaSource` working then you must be doing something like:
```
source = new MergingMediaSource(videoSource, subtitleSource);
```
Getting multiple subtitles working from that point is just a matter of adding more sources:
```
source = new MergingMediaSource(videoSource, subtitleSource1, subtitleSource2);
```

Regarding the demo app, just cloning this whole repository and then opening the project in Android Studio should get you into a state where you can compile and run the demo app.

**Comment by rburade21** [comment]
I already reached till
source = new MergingMediaSource(videoSource, subtitleSource1, subtitleSource2);

Now i have one video source and two subtitles sources...now the how to switch between these subtitles on playback
Thanks in Advance

**Comment by ojw28** [comment]
This is already demonstrated by the demo app. As noted above, it's easy to build the demo app just by cloning this repository and opening it in Android Studio. There are no additional steps required. Once you have the demo app building, it shouldn't be too difficult for you to figure out what's going on in order to display the track selection dialog.
