### ISSUE TITLE
ExoPlayer releaseSource and creating new player instance for playing random mp4 URL's on random Click

### ISSUE THREAD

**Issue by devramjava** [google/ExoPlayer#3768]
I have many list of URLs in a list view , trying to play video by clicking random URL's , i'm able to open the any(random position) URL  by selecting any random item in the list and i'm able to play next and previous videos but i'm not able to play the randomly selected second URL (and playing only the fist Selected Video) .
****** please help me with example code Thank You.**
**please check my below code:**

**Initialize and set data and prepare player** 

        public void to_play_video(){
        if (mExoPlayerView == null) {
            if(mVideoSource!=null)
                mVideoSource=null;
            mExoPlayerView = (SimpleExoPlayerView) findViewById(R.id.exoplayer);
            initFullscreenDialog();
            initFullscreenButton();
            String userAgent = Util.getUserAgent(VideoQsns_activity.this, getApplicationContext().getApplicationInfo().packageName);
            DefaultHttpDataSourceFactory httpDataSourceFactory = new DefaultHttpDataSourceFactory(userAgent, null, DefaultHttpDataSource.DEFAULT_CONNECT_TIMEOUT_MILLIS, DefaultHttpDataSource.DEFAULT_READ_TIMEOUT_MILLIS, true);
            DefaultDataSourceFactory dataSourceFactory = new DefaultDataSourceFactory(VideoQsns_activity.this, null, httpDataSourceFactory);
            try{
                if(mediaSources.length>0) {
                    List<MediaSource> list = new ArrayList<MediaSource>(Arrays.<MediaSource>asList(mediaSources));
                    list.removeAll(list);
                    mediaSources = list.toArray(new MediaSource[0]);
                }
            }catch (Exception e){

            }
            mediaSources=new MediaSource[items.size()];
            for (int i = 0; i < items.size(); i++) {
                mediaSources[i] =  new ExtractorMediaSource(Uri.parse(items.get(i).getqsnurl()), dataSourceFactory, new DefaultExtractorsFactory(),
                        null, new ExtractorMediaSource.EventListener() {
                    @Override public void onLoadError(IOException error) {

                    }
                });

            }
        }
        initExoPlayer();
        if (mExoPlayerFullscreen) {
            ((ViewGroup) mExoPlayerView.getParent()).removeView(mExoPlayerView);
            mFullScreenDialog.addContentView(mExoPlayerView, new ViewGroup.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT));
            mFullScreenIcon.setImageDrawable(ContextCompat.getDrawable(VideoQsns_activity.this, R.drawable.ic_fullscreen_skrink));
            mFullScreenDialog.show();
        }
        MediaSource mediaSource;
            mediaSource = mediaSources.length == 1 ? mediaSources[0]
                    : new ConcatenatingMediaSource(mediaSources);
        mExoPlayerView.getPlayer().prepare(mediaSource);
        mExoPlayerView.getPlayer().setPlayWhenReady(true);
    }
    private void initExoPlayer() {

        BandwidthMeter bandwidthMeter = new DefaultBandwidthMeter();
        TrackSelection.Factory videoTrackSelectionFactory = new AdaptiveTrackSelection.Factory(bandwidthMeter);
        trackSelector = new DefaultTrackSelector(videoTrackSelectionFactory);
        LoadControl loadControl = new DefaultLoadControl();
        player = ExoPlayerFactory.newSimpleInstance(new DefaultRenderersFactory(this), trackSelector, loadControl);
        mExoPlayerView.setPlayer(player);
        mExoPlayerView.getPlayer().addListener(new Player.EventListener() {
            @Override
            public void onTimelineChanged(Timeline timeline, Object manifest) {
            }
            @Override
            public void onTracksChanged(TrackGroupArray trackGroups, TrackSelectionArray trackSelections) {
                currentIndex = mExoPlayerView.getPlayer().getCurrentWindowIndex();
            }
            @Override
            public void onLoadingChanged(boolean isLoading) {
            }
            @Override
            public void onPlayerStateChanged(boolean playWhenReady, int playbackState) {
                switch(playbackState) {
                    case Player.STATE_BUFFERING:
                        break;
                    case Player.STATE_ENDED:
                        mExoPlayerView.getPlayer().stop();
                        mExoPlayerView.getPlayer().seekTo(0);
                        player.stop();
                        player.seekTo(0);
                        mExoPlayerView.getPlayer().setPlayWhenReady(true);
                        player.setPlayWhenReady(true);
                        break;
                    case Player.STATE_IDLE:
                        break;
                    case Player.STATE_READY:
                        break;
                    case PlaybackStateCompat.STATE_SKIPPING_TO_NEXT:
                        break;
                    case PlaybackStateCompat.STATE_SKIPPING_TO_PREVIOUS:
                        break;
                    default:
                        break;
                }
            }
            @Override
            public void onRepeatModeChanged(int repeatMode) {
            }
            @Override
            public void onPlayerError(ExoPlaybackException error) {
            }
            @Override
            public void onPositionDiscontinuity() {
                Log.e("-------------","onPositionDiscontinuity");
                int latestWindowIndex = mExoPlayerView.getPlayer().getCurrentWindowIndex();
                if (latestWindowIndex != lastWindowIndex) {
                    // item selected in playlist has changed, handle here
                    lastWindowIndex = latestWindowIndex;
                    // ...
                }
            }
            @Override
            public void onPlaybackParametersChanged(PlaybackParameters playbackParameters) {
            }
        });

**releasing player**

    private void releasePlayer() {
        Timeline timeline = mExoPlayerView.getPlayer().getCurrentTimeline();
        if (mExoPlayerView.getPlayer() != null) {
            if ( mExoPlayerView.getPlayer().getPlayWhenReady() &&  mExoPlayerView.getPlayer().getPlaybackState() != ExoPlayer.STATE_IDLE) {
                mResumeWindow = mExoPlayerView.getPlayer().getCurrentWindowIndex();
            }
            mResumePosition=mExoPlayerView.getPlayer().getCurrentPosition();
            shouldAutoPlay = mExoPlayerView.getPlayer().getPlayWhenReady();
            mExoPlayerView.getPlayer().prepare(null);
            mExoPlayerView.getPlayer().seekTo(0);
            mExoPlayerView.getPlayer().removeListener((Player.EventListener) 
            mExoPlayerView.getPlayer());
            mExoPlayerView.getPlayer().stop();
            mExoPlayerView.getPlayer().release();
            player.release();
            mExoPlayerView=null;
            player=null;
        }
    }

****releasing releaseSource****

    @Override
    public void releaseSource() {

        for (int i = 0; i < mediaSources.length; i++) {
            try{
                mediaSources[i].releaseSource();
            }catch(Exception e){
                Log.e("mediaSources","------------"+ mediaSources[i]);
            }
        }
    }

**Comment by ojw28** [comment]
Please could you clarify what the actual problem is that you're facing with the ExoPlayer library? Currently this reads like a request for help developing app code, which is unfortunately outside the scope of this issue tracker.

**Comment by devramjava** [comment]
i have listview and video player(exoplayer) when i select a list item i want play the mp4 URL for that particular  position (if we select the 1st one i will play the 1st mp4 URL in the array list , if i select any other position i want to play the perticular mp4 of the position )
my main problem is:
1. im not able to releaseSource (on selecting any position in the listview , im able to play only one URL not changing to the other URL ) 
2. i tried to create a new instance for the exoplayer but i could not  make it.

please help thank you

**Comment by ojw28** [comment]
You should just be able to build a new `MediaSource` and pass it to `player.prepare` each time the user selects a list item. This sounds more like a bug in your application code than an ExoPlayer issue. If you have a specific issue with the library itself, please let us know.

**Comment by devramjava** [comment]
thank you @ojw28 mistake in my application code and its solved now
