### ISSUE TITLE
Exoplayer does not switch HLS tracks when bandwidth change

### ISSUE THREAD

**Issue by Zeus64** [google/ExoPlayer#3772]
I have this simple .m3u8 file

```
#EXTM3U
#EXT-X-VERSION:5

#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio",NAME="English stereo",LANGUAGE="en"

#EXT-X-STREAM-INF:BANDWIDTH=1728000,CODECS="avc1.42c00d,mp4a.40.2",RESOLUTION=640x360,AUDIO="audio"
https://bitdash-a.akamaihd.net/content/MI201109210084_1/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa_video_360_800000.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=628000,CODECS="avc1.42c00d,mp4a.40.2",RESOLUTION=320x180,AUDIO="audio"
https://bitdash-a.akamaihd.net/content/MI201109210084_1/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa_video_180_250000.m3u8
```

With simpleExoplayer (last version 2.6.1) i load this stream like this :

```
// 1. Create a default TrackSelector
Handler mainHandler = new Handler();
BandwidthMeter bandwidthMeter = new DefaultBandwidthMeter();
TrackSelection.Factory videoTrackSelectionFactory =
    new AdaptiveTrackSelection.Factory(bandwidthMeter);
TrackSelector trackSelector =
    new DefaultTrackSelector(videoTrackSelectionFactory);

// 2. Create the player
SimpleExoPlayer player =
    ExoPlayerFactory.newSimpleInstance(context, trackSelector);

// Measures bandwidth during playback. Can be null if not required.
// Produces DataSource instances through which media data is loaded.
DataSource.Factory dataSourceFactory = new DefaultDataSourceFactory(context,
    Util.getUserAgent(context, "yourApplicationName"), bandwidthMeter);
// This is the MediaSource representing the media to be played.
MediaSource videoSource = new HlsMediaSource.Factory(dataSourceFactory)
    .createMediaSource(mp4VideoUri);
// Prepare the player with the source.
player.prepare(videoSource);
```

but even on high WIFI internet it's will always select the 2nd track with have a resolution of 320x180 and never switch to the higher track with have a resolution of 640x360. 

If i replace DEFAULT_MAX_INITIAL_BITRATE by maxInt then it's will select correctly the 1rt track (640x360) but if in the middle of the playback i cut off the wifi off to let the mobile use only the low 3G connection, then it's will never switch to the 2nd track (320x180) and playing will stuck every time

Is also check MediaCodecUtil.getDecoderInfo("video/avc", false).adaptive and it's return TRUE

What did i do wrong? does hls working properly in simpleExoPlayer ?

**Comment by marcbaechinger** [comment]
You should only use a single DefaultBandwidthMeter instance and pass it to the AdaptiveTrackSelection.Factory as a BandwidthMeter and to the DefaultDataSourceFactory as a TransferListener. 

More detailed answer in your StackOverflowQuestion:  https://stackoverflow.com/questions/48527829/why-exoplayer-does-not-switch-hls-tracks-when-bandwidth-change/48529359

**Comment by Zeus64** [comment]
Thanks marc, no it's not this i still have the problem :(

**Comment by marcbaechinger** [comment]
Ok. I'm sure that's not a bug in ExoPlayer though. May I ask you to verify your setup as follows and/or consult the main demo app as an example?

Firstly, make sure there is only one instance of `DefaultBandwidthMeter`. 

Secondly, you must make sure to pass this very instance to the `AdaptiveTrackSelection.Factory`, so it can take decisions based on this metered bandwidth. 

And lastly you need to make sure that data sources (which download media) are actually using this single instance of `DefaultBandwidthMeter` as a `TransferListener` to be notified about downloaded data. 


Log of playback of your HLS manifest:
01-30 22:20:11.594 24053-24053/com.google.android.exoplayer2.demo D/EventLogger: videoFormatChanged [0.72, id=1/27, mimeType=video/avc, res=320x180]
01-30 22:20:11.628 24053-24053/com.google.android.exoplayer2.demo D/EventLogger: videoSizeChanged [320, 180]
01-30 22:20:23.226 24053-24053/com.google.android.exoplayer2.demo D/EventLogger: videoFormatChanged [12.35, id=1/27, mimeType=video/avc, res=640x360]
01-30 22:20:23.671 24053-24053/com.google.android.exoplayer2.demo D/EventLogger: videoSizeChanged [640, 360]
01-30 22:20:51.248 24053-24053/com.google.android.exoplayer2.demo D/EventLogger: videoFormatChanged [40.37, id=1/27, mimeType=video/avc, res=320x180]
01-30 22:20:51.709 24053-24053/com.google.android.exoplayer2.demo D/EventLogger: videoSizeChanged [320, 180]
01-30 22:21:51.232 24053-24053/com.google.android.exoplayer2.demo D/EventLogger: videoFormatChanged [100.36, id=1/27, mimeType=video/avc, res=640x360]
01-30 22:21:51.663 24053-24053/com.google.android.exoplayer2.demo D/EventLogger: videoSizeChanged [640, 360]
01-30 22:22:11.247 24053-24053/com.google.android.exoplayer2.demo D/EventLogger: videoFormatChanged [120.37, id=1/27, mimeType=video/avc, res=320x180]
01-30 22:22:11.680 24053-24053/com.google.android.exoplayer2.demo D/EventLogger: videoSizeChanged [320, 180]

**Comment by Zeus64** [comment]
Marc, thanks it's was on my side ! it's because I don't use android studio, but i work on Delphi, and on delphi the conversion of class like `public final class DefaultBandwidthMeter implements BandwidthMeter, TransferListener<Object>` skip the implementation of the TransferListener part :( And the worse was that i have no error so didn't see it imediatly !

If someone come here and have similar problem, here how i resolve it :
https://stackoverflow.com/questions/48531698/how-to-convert-special-java-interface-to-pascal-interface?noredirect=1#comment84059899_48531698

you have a very good view !!
