### ISSUE TITLE
few OMX layer error and OpenGLES called with no current context on Nexus 6P

### ISSUE THREAD

**Issue by spaul13** [google/ExoPlayer#3777]
I am getting the errors while using video streaming on Nexus 6P not on google PIXEL XL. Can anyone please tell me what are the device-specific issues I am getting?

Error:
_01-30 09:27:37.537 27830-27847/? I/OpenGLRenderer: Initialized EGL, version 1.4
01-30 09:27:37.537 27830-27847/? D/OpenGLRenderer: Swap behavior 1
01-30 09:27:37.591 3768-3823/? I/ActivityManager: Displayed com.sunlh.avatardemo/com.unity3d.player.UnityPlayerActivity: +187ms (total +259ms)
01-30 09:29:10.259 2726-5635/? E/OMX-VDEC-1080P: Extension: OMX.google.android.index.storeANWBufferInMetadata not implemented
01-30 09:29:10.265 2726-2814/? E/OMX-VDEC-1080P: Extension: OMX.google.android.index.describeColorAspects not implemented
01-30 09:29:10.265 2726-5635/? E/OMX-VDEC-1080P: Extension: OMX.google.android.index.describeHDRStaticInfo not implemented
01-30 09:29:10.618 2726-5250/? E/OMX-VDEC-1080P: Extension: OMX.google.android.index.storeANWBufferInMetadata not implemented
01-30 09:29:10.624 2726-5756/? E/OMX-VDEC-1080P: Extension: OMX.google.android.index.describeColorAspects not implemented
01-30 09:29:10.624 2726-5250/? E/OMX-VDEC-1080P: Extension: OMX.google.android.index.describeHDRStaticInfo not implemented
01-30 09:31:36.372 2726-10397/? E/OMX-VDEC-1080P: Extension: OMX.google.android.index.storeANWBufferInMetadata not implemented
01-30 09:31:36.378 2726-5756/? E/OMX-VDEC-1080P: Extension: OMX.google.android.index.describeColorAspects not implemented
01-30 09:31:36.379 2726-6080/? E/OMX-VDEC-1080P: Extension: OMX.google.android.index.describeHDRStaticInfo not implemented
01-30 09:32:46.515 6483-28264/? E/libEGL: call to OpenGL ES API with no current context (logged once per thread)_

can anyone please help me how to resolve this?

**Comment by ojw28** [comment]
Please could you fill in the issue template? It's unclear whether this is related to ExoPlayer, or what the failure is. Please also provide a full bug report as requested in the issue template.

**Comment by spaul13** [comment]
Here I am providing the full bug report. I first tried for ijkplayer then the exoplayer but I found similar problem for both of them. I am using these with the easyMovieTexture to stream videos in unity game apk.

I am using the device **Nexus 6P**.  I didn't find this problem while using Google PIXEL XL.

**Specifically,
E/libEGL: call to OpenGL ES API with no current context (logged once per thread)
Along with other OMX layer errors.**

I am sending the full log file attaching in this. Is it still unclear? If it's still unclear please tell me. I am also mailing the log file as told.

Waiting to get responses from you.

[error_tobesent.pdf](https://github.com/google/ExoPlayer/files/1683041/error_tobesent.pdf)

**Comment by ojw28** [comment]
It's unclear what the actual problem is that you have. Something being logged is not in itself a problem. I assume there must be some kind of corresponding user visible issue for you to care. What is it, and what are the steps for reproducing it?

**Comment by spaul13** [comment]
I agree. But I am getting the error from the EGL library as I mentioned also few errors from the OMX layer before that.

For this reason, my mediaplayer is in MEDIA_ERROR state and this causes 
**Attempt to perform seekTo in wrong state: mPlayer=0xc80fe420, mCurrentState=0
E/MediaPlayer: error (-38, 0)**

**This restricts me to play the video stream as the current state is ERROR (seeking the frame from the wrong state).**

**I manually tried to make the mediaplayer_state = PLAYING or READY but that doesn't work either.It still throws me that error.**

This is the problem I am getting.

**Comment by ojw28** [comment]
MediaPlayer is unrelated to ExoPlayer. It sounds like you're trying a bunch of players and seeing the same error for all of them, which implies something is wrong either in your app code or some other library that you're using. This error:
```
E/libEGL: call to OpenGL ES API with no current context (logged once per thread)
```
possibly implies something is making a GL call from the wrong thread? You'd probably be best off asking this question to the author(s) of easyMovieTexture and/or somewhere Unity specific.

**Comment by spaul13** [comment]
Thanks a lot for your suggestions.

EasyMovieTexture is just using as a native plugin to the unity but I have been using ijkplayer and Exoplayer for decoding and streaming the video. Unity is just a platform to display that.

**But if I can that from a wrong thread, how it even worked for PIXEL XL?** 
and **can you tell me why I am getting those errors related to the OMX layer of the video decoder?**

**Comment by ojw28** [comment]
As noted above, a log message is not necessarily an actual error, or at least an error you should care about. As an example, the device I'm using logs the following at the start of every playback (but playback works fine):
```
E OMXNodeInstance: setConfig(12e0026f:Exynos.avc.dec, ConfigPriority(0x6f800002)) ERROR: UnsupportedIndex(0x8000101a)
E OMXNodeInstance: getConfig(12e0026f:Exynos.avc.dec, ConfigCommonOutputCrop(0x700000f)) ERROR: NotReady(0x80001010)
```
The specific logging in your case appears to be indicating that some extensions aren't supported, which feels like it could be expected. I don't know what `describeHDRStaticInfo` is, but if you're not trying to play HDR content it doesn't seem relevant.

**Comment by spaul13** [comment]
Thanks a lot. 
Then I should not be worried about the errors from the OMX layer but I need to focus on the why libEGL is giving me that error. I presume that's the failure. 
But I don't think EGL is called from a different thread.  
can you guess any other reason for getting that libEGL error and having the Media_Player in ERROR state?

Any suggestion will be very helpful. :)

**Comment by ojw28** [comment]
I think you really need to figure out what OpenGL ES call is causing the error to be generated. Once you know that, it should be relatively straightforward to validate whether or not it's being made from the correct thread. I don't think the problematic call is being made from either ExoPlayer or MediaPlayer. I think it's most likely being made from either your code or one of your other dependencies (possibly EasyMovieTexture).

We have tentative future plans to provide a Unity extension to make using ExoPlayer and Unity together more straightforward, so keep an eye out on our repository for that.

**Comment by spaul13** [comment]
Thanks a lot for having the future plan. it would be very much helpful for guys like me. 

I don't think EasyMovietexture openGLES calls making the problem as I have the debug statements throughout it to carefully observe the openGLES calls inside easyMovieTexture and it is giving me just while I run the game apk (start of playing). 

Do you think I need to add anything to the daydream-android.xml file to support something causes this device-specific issue?

How to check OpenGLES calls in other architecture specific libraries? Just adding debug statements there? It would be painful to do. If you have any other alternatives, Please do tell me. :)

**Comment by andrewlewis** [comment]
You've probably already done this, but for what it's worth: when using Unity it seems to be important to make sure that you run all your GL code on the thread Unity is using for rendering. We've been using [`GL.IssuePluginEvent`](https://docs.unity3d.com/ScriptReference/GL.IssuePluginEvent.html) for this.

In all cases where I've seen the log line `E/libEGL: call to OpenGL ES API with no current context (logged once per thread)` it's eventually turned out to be a bug where GL calls were being made on the wrong thread, or without a current GL context (as the error message suggests!).

**Comment by spaul13** [comment]
@andrewlewis thanks for your advice. but how can I exactly pinpoint which openGL call is interfering? I have debugged my native plugin code's openGL calls. They are not giving me the error. I am pretty sure unity's openGL calls giving the error. Can you tell how to find that exactly? then it will be easier me to use GL.IssuePluginEvent for that one.

**Comment by andrewlewis** [comment]
You could try removing code until the error goes away. I'm not sure if it was established that this GL logging was indicative of the underlying problem. I don't think there's anything else we can usefully suggest on this issue, I'm afraid.

**Comment by spaul13** [comment]
Hi @andrewlewis and @ojw28 ,
One more question, can you please tell me why I am getting this error?

**E/Unity: OPENGL NATIVE PLUG-IN ERROR: GL_INVALID_ENUM: enum argument out of range
(Filename: ./Runtime/GfxDevice/opengles/GfxDeviceGLES.cpp Line: 388)**

**Comment by ojw28** [comment]
These errors are unrelated to ExoPlayer. Could you ask them somewhere more suitable than the ExoPlayer issue tracker, like a Unity forum or something?
