### ISSUE TITLE
Scrubber is not visible for url's without duration.

### ISSUE THREAD

**Issue by rachitmishra** [google/ExoPlayer#3778]
Hello, I am using following sample url for streaming audio
`https://usa6.fastcast4u.com/proxy/wsjf?mp=/1`
The problem is that the seekbar scrubber is not visible, neither the buffered or played color is shown.

By looking at the code i understand the scrubber is not painted in case the duration <=0, I am curious how should i implement seeking in that case.

Kindly guide me to the right direction.

Thank you.

**Comment by ojw28** [comment]
Given it's not possible to seek in such a stream, what would you expect the behavior to be?

**Comment by rachitmishra** [comment]
Well, if I open the same url on FF or Safari, the url seems to seekable. I understand that might be by scanning or prefetching the content and setting the seek position accordingly. 

I expect the progress to be shown on the seekbar with respect to current played duration and same for the seekbar scrubber.

**Comment by ojw28** [comment]
I do not see a (working) scrubber in Safari (or Chrome, or VLC):

<img width="750" alt="screen shot 2018-01-31 at 7 13 38 pm" src="https://user-images.githubusercontent.com/7881572/35642416-f5e57f72-06ba-11e8-9720-5930f5aa8144.png">

**Comment by rachitmishra** [comment]
Yup! apologies! I was working on Firefox. I think it is due to pre-fetching the file. The scrubber is visible and seekable on it. Anyways, Is it possible to show the played duration on a `TimeBar` in case the duration ain't there? 

I explored forcing steam using `FLAG_ENABLE_CONSTANT_BITRATE_SEEKING` But alas! I guess it won't be possible with such urls.

**Comment by ojw28** [comment]
Played duration is already visible on the left side of the scrubber. We don't have any plans to support the kind of seeking Firefox enables for this stream type. If you control the server side and wish to support seeking, you should use a streaming standard that properly supports it (e.g. DASH, HLS, SmoothStreaming).

**Comment by rachitmishra** [comment]
Yes, agreed. that would be the right solution for this. I was just exploring if there was some workaround. Thanks a lot for the quick help. Good day!
