### ISSUE TITLE
HLS protection not flexible enough for decryption outside the ExoPlayer library

### ISSUE THREAD

**Issue by hodzic** [google/ExoPlayer#378]
In the current ExoPlayer library, HLS decryption is done as part of HlsChunkSource. Only the default AES-128 encryption method is supported.

Would like to add a new HlsDecryptionManager interface to be used by HlsChunkSource and HlsPlaylistParser, for processing the HLS key tag line, and decrypting HLS segment, outside the library.

I have the code for the HlsDecryptionManager interface and a HlsAes128DecryptionManager class that implements the interface to provide the current functionality, but outside the library, i.e. in the demo app.

Could I make such pull request?

**Comment by ojw28** [comment]
What's the actual use case? The HLS spec only defines NONE, AES-128 and SAMPLE-AES. If your end goal is playing content that uses SAMPLE-AES, which is the one we don't currently support, then I think any support should probably be added directly to the library, if we decide it's something we want to do. If you're trying to do something else, please clarify.

**Comment by hodzic** [comment]
The use case is Marlin DRM based HLS decryption.

**Comment by ojw28** [comment]
The HLS spec states that there are two defined methods for EXT-X-KEY, which, unless I've misunderstood, means that Marlin DRM, and other custom schemes, are excluded from the spec. This and presumably the lack of official support on iOS devices, makes this a pretty tough sell.

We don't want to add additional indirection to the library to support a mode that there isn't significant demand for. Doing so results in more code that we have to maintain, and worse, encourages further fragmentation of the video ecosystem.

**Comment by hodzic** [comment]
Marlin DRM is not custom in the way the HLS media is encrypted, it fully complies with the HLS spec. It provides protection for the key, i.e. provides key formats beyond the trivial "identity" defined by the spec.  

The spec defines KEYFORMAT attribute for the EXT-X-KEY tag, and the ExoPlayer library doesn't allow an application to process key in a more secure way than fetching it over HTTP/HTTPS.

The code would only get simpler to maintain by abstracting key handling and media decryption.

In the case of DASH, the library abstracts interaction with the Media DRM plugin, for handling the key and media decryption. Abstracting HLS key handling and media decryption would provide an analogous flexibility in the use of the ExoPlayer library.

**Comment by ojw28** [comment]
Ah. So what value does METHOD take for this use case?

**Comment by hodzic** [comment]
The whole EXT-X-KEY tag line can be passed through the interface to an HLS decryption manager and ExoPlayer library doesn't need to worry about parsing METHOD (of course there would be a default HLS decryption manager class that would handle the AES-128 METHOD and the identity KEYFORMAT in the library.)

**Comment by ojw28** [comment]
Right, but what is the value?

**Comment by hodzic** [comment]
How does it matter? Marlin DRM supports METHOD=AES-128 (and also METHOD=MARLIN-BBTS).

**Comment by hodzic** [comment]
Note that even with METHOD=AES-128, the key is protected by the DRM and does not come over HTTP/HTTPS from the location pointed to by the URI attribute. In this case, URI="urn:marlin-drm".

**Comment by canatella** [comment]
Verimatrix is also using the same kind of scheme. The fetching of the key and the decryption must be done using their own code, so this would be usefull for supporting Verimatrix DRM also.

**Comment by ojw28** [comment]
Apple have announced support for Common Encryption in HLS, and we're expecting the industry to move in this direction. Hence we have no plans to implement this enhancement. Sorry.
