### ISSUE TITLE
HLS CEA608 closed caption drops characters issue

### ISSUE THREAD

**Issue by linhai326** [google/ExoPlayer#3782]
### Issue description
The test HLS content has cea608 track and WebVtt track. Using demo player to stream this content, the WebVTT shows correctly while the cea608 track keeps dropping lines.

### Reproduction steps
start the test content link below, the issue can start to happen at 00:01:02 position. the cea608 will drop lines while webvtt can show correctly.

comparing with other players, like http://hlstester.com/, https://developer.jwplayer.com/tools/stream-tester/
 these players don't drop lines from cea608 track.

### Link to test content
http://vod-staging-msp-ops.mobitv.com/mm/hls5/vod/291/984111/VODSERVICE_1354/group=TG_W_4G,drm=native.m3u8?uid=45dd8d07-d953-4a2c-b823-edb138f5e604&sid=73119663582491516668432&i=0&nwk=&pk=1

### Version of ExoPlayer being used
this happens on all versions from 2.1.x to 2.6.1.

### Device(s) and version(s) of Android being used
on all devices: firetv stick gen2, LG-TP450, Samsung Note3...

### A full bug report captured from the device
a full adb log attached.
also i put log printout in cea608decoder.java in private void handleMiscCode(byte cc2) :
"
...
    if (captionMode == CC_MODE_UNKNOWN) {
      return;
    }
    System.out.println("TESTTEST cc2 event = " + Integer.toHexString(cc2));
    switch (cc2) {
      case CTRL_ERASE_DISPLAYED_MEMORY:
        cues = null;
        if (captionMode == CC_MODE_ROLL_UP || captionMode == CC_MODE_PAINT_ON) {
          resetCueBuilders();
        }
        break;
      case CTRL_ERASE_NON_DISPLAYED_MEMORY:
...
"
this gives out the cause of the lines dropped:
"
...
02-01 10:24:28.265 17371-17647/com.google.android.exoplayer2.demo I/System.out: TESTTEST append2: c
02-01 10:24:28.265 17371-17647/com.google.android.exoplayer2.demo I/System.out: TESTTEST append: a
02-01 10:24:28.265 17371-17647/com.google.android.exoplayer2.demo I/System.out: TESTTEST append2: t
02-01 10:24:28.265 17371-17647/com.google.android.exoplayer2.demo I/System.out: TESTTEST append: s
02-01 10:24:28.265 17371-17647/com.google.android.exoplayer2.demo I/System.out: TESTTEST append2: .
02-01 10:24:28.266 17371-17647/com.google.android.exoplayer2.demo I/System.out: TESTTEST cc2 event = 2c
02-01 10:24:31.288 17371-17647/com.google.android.exoplayer2.demo I/System.out: TESTTEST cc2 event = 2e
02-01 10:24:31.288 17371-17647/com.google.android.exoplayer2.demo I/System.out: TESTTEST append: H
02-01 10:24:31.288 17371-17647/com.google.android.exoplayer2.demo I/System.out: TESTTEST append2: e
02-01 10:24:31.288 17371-17647/com.google.android.exoplayer2.demo I/System.out: TESTTEST append: y
...
"
the CTRL_ERASE_NON_DISPLAYED_MEMORY command removed all characters before it and didn't display it.
why does the decoder do that?

**Comment by linhai326** [comment]
[cea608_decoder_log.txt](https://github.com/google/ExoPlayer/files/1686708/cea608_decoder_log.txt)
[fulllog.txt](https://github.com/google/ExoPlayer/files/1686709/fulllog.txt)

**Comment by linhai326** [comment]
Hi @AquilesCanta , any update/findings on this issue?

**Comment by ojw28** [comment]
This is an issue where we're not correctly keeping buffers with identical presentation timestamps in their original order. We will push a fix shortly.

**Comment by linhai326** [comment]
that's a great news, Thanks!
