### ISSUE TITLE
how releasing and recreating the player?

### ISSUE THREAD

**Issue by fenggit** [google/ExoPlayer#3784]
Before filing an issue:
-----------------------
### Issue description

how releasing and recreating the player?

I use list（RecyclerView） play video ，How to re-create after I release the resource ？

After I release ，  “sending message to a Handler on a dead thread”

Thanks

**Comment by ojw28** [comment]
* Recreating a player is no different to how you'd create the player the first time.
* “sending message to a Handler on a dead thread” can often be harmless, so by themselves are not indicative of a problem.
* There's a lot of information in https://github.com/google/ExoPlayer/issues/867 about how to get ExoPlayer working well within RecyclerView.
