### ISSUE TITLE
Gvr SDK Unity and ExoPlayer

### ISSUE THREAD

**Issue by HennessyTennessy** [google/ExoPlayer#3785]
I am working with GVR SDK, including ExoPlayer-r-1.5.11. I have problem with reproduce .mkv files with .AC3 codec. I know that I should to use fffmpeg extraction.
For now, I have:
1) Unity Project with GVR SDK, who can see ExoPlayer-r-1.5.11 library (library-release.aar)
2) I have ffmpeg extra librarty (extension-ffmpeg-release.aar)
How can I connect both library to Unity Projects?
Thx for any info.

**Comment by andrewlewis** [comment]
If you're trying to decode AC-3 in software using the ffmpeg extension, you'll need to switch to ExoPlayer v2, as the extension depends on v2 functionality. Unfortunately, I think the GVR SDK only provides support for ExoPlayer v1.

We plan to publish an extension for using ExoPlayer v2 from Unity soon, though no promises if/when this will happen yet.

For what it's worth, once you're at the stage of being able to use ExoPlayer v2 from Unity, using the ffmpeg extension should be a simple case of copying the AARs for the core library and the extension in the Unity project's assets. Then `DefaultRenderersFactory` should be able to load and instantiate an `FfmpegAudioRenderer` (or you can pass this `Renderer` directly to `ExoPlayerFactory.newInstance` if you don't want to use `SimpleExoPlayer`).

**Comment by HennessyTennessy** [comment]
Ahh. Thank much for quickly answer.
Yes, i tryied to copy library of ExoPlayer_v2 to Unity project with GVR SDK, and receive many errors in Log. Think that GVR SDK not support v2 too.
Sooo, as i understand, I have no way to use GVR SDK with .AC3 codec, and should create new own ExoPlayer_v2.plugin for Unity. Is it right?

**Comment by andrewlewis** [comment]
Yes. Or wait for us to publish one (probably soon but no promises).

**Comment by HennessyTennessy** [comment]
Okay:) Thank you)
