### ISSUE TITLE
IMA ImaAdsLoader not resuming content when preroll Ad is empty

### ISSUE THREAD

**Issue by fpittersacc** [google/ExoPlayer#3789]
### Issue description
ImaAdsLoader is entering an invalid state after getting an empty preroll Ad. When loading the sample URL that contains a playlist with an invalid Preroll Ad, playback is not resumed while the reported events by underlying IMA library are: CONTENT_RESUME_REQUESTED and ALL_ADS_COMPLETED.

### Reproduction steps
On IMA demo project, setup the Ad URL provided below.

### Link to test content
https://pubads.g.doubleclick.net/gampad/ads?correlator=%5Btimestamp%5D&custom_params=assetid%253D1288173%2526assettype%253Depisode%2526categoryid%253D604008482%2526categorytitle%253DSesong%252B1%2526dfpduration%253D7%2526duration%253D1381%2526free%253Dfalse%2526livechannel%253Dfalse&description_url=http%3A%2F%2Fwww.tv2.no%2Fv%2F1288173&duration=1381&env=vp&gdfp_req=1&hl=no&impl=s&iu=%2F5374%2FTV2video%2Fsumo%2Fprogrammer%2Funderholdning%2Fsophieelisesverden%2Fsesong1&output=vast&sz=640x480&unviewed_position_start=1&url=%5Breferrer_url%5D

### Version of ExoPlayer being used
2.6.1

### Device(s) and version(s) of Android being used
Nexus 5 (6.0.1), Samsung S7 (7.0)

### A full bug report captured from the device
[bugreport-2018-02-02-15-19-38.zip](https://github.com/google/ExoPlayer/files/1689693/bugreport-2018-02-02-15-19-38.zip)

### Relevant log
```
02-02 15:36:44.490 32391-32391/com.google.android.exoplayer2.imademo D/ImaAdsLoader: Initialized with ads rendering settings: AdsRenderingSettings [bitrate=-1, mimeTypes=[application/dash+xml, application/x-mpegURL, video/mp4, video/webm, video/3gpp, video/mpeg, audio/mp4, audio/mpeg], uiElements=null, enablePreloading=true, playAdsAfterTime=-1.0]
02-02 15:36:44.607 32391-32391/com.google.android.exoplayer2.imademo D/ImaAdsLoader: onAdEvent: LOG
02-02 15:36:44.609 32391-32391/com.google.android.exoplayer2.imademo I/ImaAdsLoader: Log AdEvent: {type=adLoadError, errorCode=1009, errorMessage=The response does not contain any valid ads.}
02-02 15:36:44.612 32391-32391/com.google.android.exoplayer2.imademo D/ImaAdsLoader: onAdEvent: LOG
02-02 15:36:44.612 32391-32391/com.google.android.exoplayer2.imademo I/ImaAdsLoader: Log AdEvent: {type=adLoadError, errorCode=1009, errorMessage=The response does not contain any valid ads.}
02-02 15:36:44.615 32391-32391/com.google.android.exoplayer2.imademo D/ImaAdsLoader: onAdEvent: CONTENT_RESUME_REQUESTED
02-02 15:36:44.624 32391-32391/com.google.android.exoplayer2.imademo D/ImaAdsLoader: onAdEvent: ALL_ADS_COMPLETED
```

### Possible solution
We are temporary solving the issue on ImaAdsLoader with:
```
case ALL_ADS_COMPLETED:
   for (int i = 0; i < adPlaybackState.adGroupCount; i++) {
      adPlaybackState.playedAdGroup(i);
   }
   updateAdPlaybackState();
   break;
```

**Comment by andrewlewis** [comment]
This will likely be fixed as part of the fix for #3584, which is coming soon.
