### ISSUE TITLE
Video distorted when tunneling enabled

### ISSUE THREAD

**Issue by okaymak** [google/ExoPlayer#3790]
### Issue description
After enabling tunneled video playback, video is distorted, see attached image.
![img_20180202_165223](https://user-images.githubusercontent.com/2102658/35742426-b55257a6-083a-11e8-8951-320c2e14fa71.jpg)

When I disable tunneling, the video is fine.
On an emulator the video is also fine with and without tunneling.

The distortion is happening on all videos within ExoPlayer's demo app, except with `H265`, `WebM` and `FMP4` video's. While the distortion is happening, ExoPlayer does not trigger `Player.STATE_ENDED` and the `position` label in the UI is advancing beyond the `duration`.

### Reproduction steps
Tested it with ExoPlayer demo app. I enabled tunnelling in the demo app by the following changes in PlayerActivity.java
```java
      trackSelector = new DefaultTrackSelector(adaptiveTrackSelectionFactory);
```
with 
```java
      trackSelector = new DefaultTrackSelector(adaptiveTrackSelectionFactory);
      trackSelector.setTunnelingAudioSessionId(C.generateAudioSessionIdV21(this));
```

### Link to test content
See the ExoPlayer demo app with above changes to enable tunneling.

### Version of ExoPlayer being used
2.6.1

### Device(s) and version(s) of Android being used
Philips QM164E (model 32PFS6402/12) running Android TV 5.1.1

### A full bug report captured from the device
Stepping through with the debugger, I can see it being enabled in `MappingTrackSelector#maybeConfigureRenderersForTunneling`.
According to the `media_codexs.xml` tunneling is supported on this device
```xml
<!-- MTK HW video decoder -->
<MediaCodec name="OMX.MTK.VIDEO.DECODER.AVC" type="video/avc" >
    <Quirk name="requires-allocate-on-input-ports" />
    <Feature name="adaptive-playback" />
    <Feature name="tunneled-playback" />
    <Limit name="size" min="64x64" max="1920x1088" />
    <Limit name="alignment" value="1x1" />
    <Limit name="block-size" value="16x16" />
    <Limit name="blocks-per-second" range="1-979200" />
    <Limit name="frame-rate" range="1-120" />
    <Limit name="bitrate" range="1-60000000" />
</MediaCodec>
<MediaCodec name="OMX.MTK.VIDEO.DECODER.AVC.secure" type="video/avc" >
    <Quirk name="requires-allocate-on-input-ports" />
    <Feature name="adaptive-playback" />
    <Feature name="tunneled-playback" />
    <Feature name="secure-playback" required="true" />
    <Limit name="size" min="64x64" max="1920x1088" />
    <Limit name="alignment" value="1x1" />
    <Limit name="block-size" value="16x16" />
    <Limit name="blocks-per-second" range="1-979200" />
    <Limit name="frame-rate" range="1-120" />
    <Limit name="bitrate" range="1-60000000" />
</MediaCodec>               
```

Is there an issue with this device and/or the ExoPlayer implementation, or am I missing something?

**Comment by okaymak** [comment]
Also noticed that on this device the `Player.STATE_ENDED` event does not get triggered while tunneling is enabled.

**Comment by AquilesCanta** [comment]
Could you please provide all the items requested in the issue [template](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE)? The bugreport and media link are specially important.

**Comment by okaymak** [comment]
Issue updated and bugreport sent by email.

**Comment by AquilesCanta** [comment]
Hi @okaymak, sorry for the delay on this. Two questions:

- Have you managed to make tunneling work on any other device?
- Have you tried contacting the manufacturer?

**Comment by AquilesCanta** [comment]
Hi @okaymak, are there any updates on this? Please comment below and we will reopen.
