### ISSUE TITLE
IMA sdk Audio-only ads?

### ISSUE THREAD

**Issue by ursusursus** [google/ExoPlayer#3795]
Hi, I have audio player app.
My question is generally about your IMA extension.

IMA website claims it supports audio-only ads (https://developers.google.com/interactive-media-ads/docs/sdks/android/compatibility), i.e. from what I understand, audio ads inbetween audiotracks, same like Spotify.

All examples of the extension deal with audio. Is audio-only supported?

Thanks

**Comment by andrewlewis** [comment]
The Android IMA SDK relies on having a WebView. Using a WebView with audio-only ads is probably fine if your app is in the foreground, but I'm not sure it will work while backgrounded in a Service (assuming your player can run in the background).

If you only want to play audio ads while your app is in the foreground it may just work. I haven't been able to verify this yet as I don't have an audio-only ad tag. If you try this out and it doesn't work, please email a link to your audio-only ad tag to dev.exoplayer@gmail.com and we can investigate further. Thanks.

**Comment by andrewlewis** [comment]
Please see also https://groups.google.com/d/msg/ima-sdk/H2tr4GPmeeE/v1mYj81gAAAJ.
