### ISSUE TITLE
FrameworkSampleSource fails to stop buffering and start playback

### ISSUE THREAD

**Issue by IanDBird** [google/ExoPlayer#38]
I'm having issues when i'm trying to play an MP4 but at a non-zero offset. I'm allowing the user to "Resume" their video where they last stopped playing, but occasionally (maybe 1 in 3), ExoPlayer refuses to start playback.

I don't think I am doing anything unusual when configuring the player, e.g.

```java
    m_player.prepare(renderers);
    m_player.seekTo(m_offset);
``` 

I can see from logging in the `onPlayerStateChanged` callback, that the video player goes through the following states: STATE_IDLE, STATE_PREPARING and STATE_BUFFERING. It then remains in the buffering state indefinitely.

The issue appears to be effected by the fact i'm trying to seek in the video. I'm yet to have it fail when starting the video at the beginning. Is this a known issue? Are there any workarounds to ensure that playback always begins?

**Comment by ojw28** [comment]
On the latest dev branch, you can use ExoPlayer's application level MP4 extractor to avoid this issue (in the demo app, use TYPE_MP4 rather than TYPE_OTHER).
