### ISSUE TITLE
Switching video source while ExoPlayer is running

### ISSUE THREAD

**Issue by dnutcracker** [google/ExoPlayer#380]
I'm looking for the quickest way to change the video that is currently playing.

Is it possible to replace the video source/videorenderer without stopping and re-preparing the ExoPlayer?

**Comment by ngoclinh49** [comment]
i have same broblem

**Comment by PrasadShirsath** [comment]
@ngoclinh49  can you share more about your solution to change video source? I'm facing same issue as @dnutcracker.

**Comment by ojw28** [comment]
You should stop and re-prepare the player to switch the content.
