### ISSUE TITLE
ExoPlayerImplInternal is occured on the NexusPlayer

### ISSUE THREAD

**Issue by KazumiHARADA** [google/ExoPlayer#3800]
### Issue description
Our application has played video on DASH format and WidevideDRM, but It was occurred the following error on the NexusPlayer only.

### Reproduction steps
Play live contents.

### Link to test content
N/A
If you need test content, I will send mail to dev.exoplayer@gmail.com

### Version of ExoPlayer being used
2.6.1

### Device(s) and version(s) of Android being used
Error occured device
Nexus Player, Android 8.0.0

No problem device
PIXELA, Android 7.0
Bravia, Android 7.0

**Comment by AquilesCanta** [comment]
Please provide all the information requested in the [issue template](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

**Comment by KazumiHARADA** [comment]
[bugreport-fugu-OPR2.170623.027-2018-02-06-13-43-43.zip](https://github.com/google/ExoPlayer/files/1697765/bugreport-fugu-OPR2.170623.027-2018-02-06-13-43-43.zip)

**Comment by AquilesCanta** [comment]
Please also send the link to dev.exoplayer@gmail.com.

**Comment by KazumiHARADA** [comment]
I've sent more info, please confirm it.

**Comment by AquilesCanta** [comment]
The provided stream gives me a different issue:

> `PolicyEngine::CanDecryptContent Key 'XXXXXXXXXXXXXXXXXXXXXXXXX' not in license`

Which sounds like a license provision issue. Are you sure the provided content is the correct one?

**Comment by KazumiHARADA** [comment]
Sorry, The content that I sent was needed "Authentication" header, but our token was set available limit. So I try sample live streams whether reproduct the issue.

I will send sample live stream url in a few days.

**Comment by ojw28** [comment]
Closing since we've not received a working test stream.
