### ISSUE TITLE
Leak memory on r.2.6.1 in RecycleView

### ISSUE THREAD

**Issue by ghost** [google/ExoPlayer#3808]
Hi . i have leak memory error in `ExpPlayer r.2.6.1` when using inside RecycleView. 
I searched for 6 days and got many issues in #3668 , #3028 , #1943 and etc  but i can't solve problem . 

Build gradle : 

> compile 'com.google.android.exoplayer:exoplayer:2.6.1'        
compile 'com.google.android.exoplayer:exoplayer-core:2.6.1'
compile 'com.google.android.exoplayer:exoplayer-dash:2.6.1'
compile 'com.google.android.exoplayer:exoplayer-ui:2.6.1'

My recycle view just have many SimpleExoPlayerViews and it isn't have any other views . 

RecycleView : 

`  

    @Override
    public RecyclerView.ViewHolder onCreateViewHolder(ViewGroup parent, int viewType){
        LayoutInflater inflater = LayoutInflater.from(parent.getContext());
        Item item = items.get( viewType );
                PostContent content = new PostContent(inflater , parent , R.layout.layout_home_post  ,
                        item , context.getString(R.string.home_fragment_name)  );
                final PostHolder holder = new PostHolder(content.getInflatedLayout());
                holder.content = content;
                return holder;
    }
    @Override
    public void onBindViewHolder(RecyclerView.ViewHolder h, int position) {
        try {
            final PostHolder holder = (PostHolder) h;
            holder.content.load();
        }catch (Exception ex){
            Log.ue(TAG , ex);
        }
    }
`

Here is `content.load()` : 

`

    public void load(){
          Utils.createExoPlayerConfig(getContext() , this.videoPost);
           this.videoPost.getPlayer().addListener(this);
           this.videoPost.setVisibility(View.VISIBLE);
           Utils.setVideo(getContext() , item ,  videoPost, true );
            this.videoPost.getPlayer().setPlayWhenReady(true);
      }
`

And this is `Utils.createExoPlayerConfig()` method : 

`

     public static SimpleExoPlayer createExoPlayerConfig(Context context, SimpleExoPlayerView simpleExoPlayerView){
             // 1. Create a default TrackSelector
             Handler mainHandler = new Handler();
             BandwidthMeter bandwidthMeter = new DefaultBandwidthMeter();
             TrackSelection.Factory videoTrackSelectionFactory =
                new AdaptiveTrackSelection.Factory(bandwidthMeter);
             TrackSelector trackSelector =
                new DefaultTrackSelector(videoTrackSelectionFactory);

         // 2. Create the player
             SimpleExoPlayer player =
                ExoPlayerFactory.newSimpleInstance(context, trackSelector);
             simpleExoPlayerView.setPlayer(player);
             return player;
         }

`

In another class i implement recycleListener for my RecycleView : 
`

          recycleView.setRecyclerListener(new RecyclerView.RecyclerListener() {
                @Override
                public void onViewRecycled(RecyclerView.ViewHolder holder) {
                    if (holder instanceof PostHolder){
                        ((PostHolder) holder).content.recycle();
                    }else{
                        Log.e(TAG ,">>>>> "+ holder.getClass().getName());
                    }
                }
            });
`

The `content.recycle()` is called all times . but it can't cleaned exoPlayer video from memory : 

`

    public void recycle(){
           Log.e(TAG , "onRecycleVideo");
           //videoPost is SimpleExoPlayer Object
            videoPost.getPlayer().setPlayWhenReady(false);
            videoPost.getPlayer().stop();
            videoPost.getPlayer().removeListener(this);
            videoPost.getPlayer().release();
            videoPost.setPlayer(null);
            Runtime.getRuntime().gc();
    }
`

And this is my xml : 

`

<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:id="@+id/layout_post"
    xmlns:app="http://schemas.android.com/apk/res-auto">

    <com.google.android.exoplayer2.ui.SimpleExoPlayerView
        android:id="@+id/home_player"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:visibility="visible"
        app:use_controller="false"
        app:controller_layout_id="@layout/exo_playback_control_view">

    </com.google.android.exoplayer2.ui.SimpleExoPlayerView>

</FrameLayout>
`

pay attention : just 1 video is playing each time .

After scrolling RecycleView i got leak memory Exception . can you help me ?

**Comment by AquilesCanta** [comment]
Unfortunately this is not something we can help with. There is no evidence of this being an ExoPlayer issue. It should not be hard to debug using the Android Studio profiler, really. It usually helps a lot to know what objects are being leaked.

**Comment by ghost** [comment]
@AquilesCanta thank you for answering . but when i delete `Utils.setVideo(getContext() , item ,  videoPost, true );` line all things is ok . it mean the memory leaking is for exoPlayer . I checked  Android Studio profiler and understand with exoPlayer `others memory is too high` and without exoPlayer `others memory is just 5 mg` .

**Comment by ojw28** [comment]
That's not particularly strong evidence of a leak. What's the maximum number of player instances that you have alive (i.e. prepared but not released) at any one time? Maybe you just have too many instances alive simultaneously? Additional notes:

* If ExoPlayer is genuinely leaking memory, it should be possible for you to recreate the same leak without also using RecyclerView. If you can only reproduce a leak with your usage of RecyclerView, that suggests the problem lies within your code.
* ExoPlayer allocates more memory within your process than MediaPlayer, but total memory allocated isn't too different in the two cases (MediaPlayer allocates memory in the mediaserver process instead).

**Comment by ojw28** [comment]
If you can reproduce the leak without your usage of RecyclerView, please let us know how. Thanks!
