### ISSUE TITLE
ExoPlayer PIP of several videos / Video Overlays (for  sign language interpreter and more)

### ISSUE THREAD

**Issue by Shailevy** [google/ExoPlayer#3809]
Hi,

Were looking for a way to play several videos at the same time at different places on the screen. (Picture In Picture).
Our main objective to provide deaf users with a small video of a sign language interpreter in it.
We have yet to see anything close to that in ExoPlayer, it's important for us that this wont be done in the UI layer or outside the context of the played video. We want it to be included in the bandwidth calculations and to be in complete sync with main video stream (think about the interpreter having to sync his lips movement with the audio)

The closest thing we found was the MergingMediaSource but we didn't find an easy way to extend/modify/use it in this manner.   

We have full control over the video and the source code, we also have the resources to change/extend/add ExoPlayer elements. 

If someone can please point us in the right "long term" direction for doing this

Thanks

**Comment by eneim** [comment]
@Shailevy sounds to be a good use case. Have you ever tried to use 2 SimpleExoPlayerView instances and succeed (in syncing them of course)?

**Comment by Shailevy** [comment]
@eneim this isn't what were looking for for many reasons, were working on a video delivery platform and we have long-run aspirations. Building over such a solution is a bit "hacky", in one example we will need to deal with several instances of the same hardware decoder working in the same time. It wil be match better to work with a single video renderer  or at least to bake this as an ExoPlayer extenstion/feature/library for easy integration.

**Comment by AquilesCanta** [comment]
Hi @Shailevy, this is not something ExoPlayer supports (nor is on the roadmap to be supported).

If you want to use a single decoder, while still being able to renderer to different surfaces, I suppose you will need to deliver the actual content along with the overlays in a single video, which later gets cropped and split into different surfaces. You could use a single custom video renderer which does this, using GL operations to do the cropping and moving around, and then conditionally overlaying the complementary content. It is not something trivial, but it is doable. The track selection part will need to be handled separately as well.
