### ISSUE TITLE
Playing encrypted media with prefixed IV

### ISSUE THREAD

**Issue by huttarl** [google/ExoPlayer#3815]
First, many thanks to @moagrius for sharing his research and results about "offlining video with encryption" (#2467).

We are in the same boat as he was, wanting to put encrypted media on a phone and then play the files in decrypted streams using a media player such as ExoPlayer. His insights such as NoPadding, and the sample code for `EncryptedFileDataSource`, probably made it possible for me to get it working when it very well might not have been possible otherwise.

One thing I would share with others from my experience: In the encrypted files that we need to play, the IV is prefixed as the first 8 bytes. So in order for EncryptedFileDataSource to work, I had to introduce an offset. In the constructor, I added an offset parameter, and in `setupInputStream()`, I added an instruction to skip over that many bytes: 

```
    /** Number of bytes to skip from beginning of stream, e.g. for IV. */
    private int mOffset;

    public EncryptedFileDataSource(Cipher cipher, int offset,
                                   TransferListener<? super EncryptedFileDataSource> listener) {
        mCipher = cipher;
        mTransferListener = listener;
        mOffset = offset;
    }
    ...
    private void setupInputStream() throws IOException {
        File encryptedFile = new File(mUri.getPath());
        FileInputStream fileInputStream = new FileInputStream(encryptedFile);
        fileInputStream.skip(mOffset);
        mInputStream = new StreamingCipherInputStream(fileInputStream, mCipher);
    }
```

So this isn't really a request for a fix or a feature, and I assume this issue will be closed soon. I just wanted to put this out there to acknowledge my debt to @moagrius and post my small contribution where it might help somebody. I would have added this as a comment on #2467 if it were open.

**Comment by AquilesCanta** [comment]
Thanks for your contribution!

**Comment by moagrius** [comment]
Thanks for the nice words and the update!

**Comment by rd7773** [comment]
@huttarl @moagrius First of all thanks to both of you for sharing the way.
@moagrius I have a similar requirement where we need to play a mpeg-cenc ecrypted video which is locally stored on phone but the encryption is done at server end using ffmpeg with encryption scheme cenc-aes-ctr and it seems ffmpeg internally uses 8 byte random iv while encrypting which is written to the senc box of mp4. I am following your demo app for this but i am confused what value of iv should i pass to get the cipher instance while decryption in this case ?
@huttarl It would be really helpful if you could help.
I have very limited cryptography knowledge, so any references to resources and library that could handle this requirement with or without any tweaks is welcomed.

**Comment by moagrius** [comment]
i'm not a crypto expert but, as far as i know, you have to have the IV for any decryption operation.  a quick google says that cenc-aes-ctr is basically the same thing as aes-ctr.  sorry, i can't help much beyond that.

**Comment by rd7773** [comment]
@moagrius i used ffmpeg command for encryption as below 
`ffmpeg -i cleanVideo.mp4 -vcodec copy -acodec copy -encryption_scheme cenc-aes-ctr -encryption_key 76a6c65c5ea762046bd749a2e632ccbb -encryption_kid a7e61c373e219033c21091fa607bf3b8 encryptedVideo.mp4`
We didn't pass any IV, ffmpeg writes random 8 bytes iv to senc box of mp4.
AFAIK CENC encrypts samples in between and not the whole file so we need to parse the mp4, extract the iv and decrypt individual samples instead of whole file. But i have no idea how to do that, any idea in this regards would help. Thank you for your time bdw.

**Comment by moagrius** [comment]
sorry, i have no idea how you'd decrypt without knowing the iv.
