### ISSUE TITLE
Closed caption (cea-608) on TS (Transport Stream) file how to make it work

### ISSUE THREAD

**Issue by kaemanspk** [google/ExoPlayer#3816]
IPTV Headend multicast (UDP) TV channel having cea-608 closed caption descriptor included on the stream.
Exoplayer can able to capture and list on the TEXT portion(find attached image). But when chose cea-608 closed caption not able to see subtitle text on the screen.

Attached the video (ts file) captured from the head end.

Exoplayer 2.6.0

### Reproduction steps
place the attached file in the sdcard/Download/ folder and list in the JSON file asset folder.

Able to get closed caption text in Android VLC player

### Link to test content
send link dev.exoplayer@gmail.com  id

### Device(s) and version(s) of Android being used
device: amlogic S 905 x
model:MBOX
[ro.product.brand]: [Amlogic]
[ro.product.cpu.abi]: [armeabi-v7a]
[ro.product.cpu.abi2]: [armeabi]
[ro.product.cpu.abilist]: [armeabi-v7a,armeabi]
[ro.product.cpu.abilist32]: [armeabi-v7a,armeabi]

**Comment by AquilesCanta** [comment]
Thanks for reporting! Will push a fix soon.

**Comment by kaemanspk** [comment]
Thank you, so it means version 2.6.0 does not support CC on TS(transport stream).
When can we expect fix of this.

**Comment by AquilesCanta** [comment]
> so it means version 2.6.0 does not support CC on TS(transport stream).

No. But this TS contains a specific provider id which was not being considered as 608. 

> When can we expect fix of this.

On the next dev push and later release.

**Comment by gautama** [comment]
Thank you, could you share the commit details. We would like to push a private fix to our deployment to fix customer dsat.

cc @kaemanspk

**Comment by ojw28** [comment]
Fix is now available in the dev-v2 branch.
