### ISSUE TITLE
Subtitles does not show on SimpleExoPlayer 2.6.1

### ISSUE THREAD

**Issue by GustenB** [google/ExoPlayer#3817]
Hi 

We are trying to set up SimpleExoPlayer 2.6.1 with subtitles. However, the subtilte will not show on the screen? Please, see render output below. We have used the ExoPlayer Demo class "texttrackhelper" to choose a texttrack but the subtitle will not show on the screen. Any idea what could be wrong? 

]                                                                                                                                           
Tracks [                                                                                                                                    
  Renderer:0 [                                                                                                                              
    Group:0, adaptive_supported=YES [                                                                                                       
      [X] Track:0, id=video=194000, mimeType=video/avc, bitrate=194000, res=320x180, fps=25.0, supported=YES                                
      [X] Track:1, id=video=484000, mimeType=video/avc, bitrate=484000, res=384x216, fps=25.0, supported=YES                                
      [X] Track:2, id=video=773000, mimeType=video/avc, bitrate=773000, res=512x288, fps=25.0, supported=YES                                
      [X] Track:3, id=video=1185000, mimeType=video/avc, bitrate=1185000, res=704x396, fps=25.0, supported=YES                              
      [X] Track:4, id=video=2175000, mimeType=video/avc, bitrate=2175000, res=1024x576, fps=25.0, supported=YES                             
      [X] Track:5, id=video=3953000, mimeType=video/avc, bitrate=3953000, res=1280x720, fps=25.0, supported=YES                             
    ]                                                                                                                                       
  ]                                                                                                                                         
  Renderer:1 [                                                                                                                              
    Group:0, adaptive_supported=YES_NOT_SEAMLESS [                                                                                          
      [ ] Track:0, id=audio_eng=48000, mimeType=audio/mp4a-latm, bitrate=48000, channels=2, sample_rate=48000, language=en, supported=YES   
      [ ] Track:1, id=audio_eng=128000, mimeType=audio/mp4a-latm, bitrate=128000, channels=2, sample_rate=48000, language=en, supported=YES 
      [X] Track:2, id=audio_eng=192000, mimeType=audio/mp4a-latm, bitrate=192000, channels=2, sample_rate=48000, language=en, supported=YES 
    ]                                                                                                                                       
  ]                                                                                                                                         
  Renderer:2 [                                                                                                                              
    Group:0, adaptive_supported=N/A [                                                                                                       
      [ ] Track:0, id=textstream_dan=1000, mimeType=application/ttml+xml, bitrate=1000, language=da, supported=YES                          
    ]                                                                                                                                       
    Group:1, adaptive_supported=N/A [                                                                                                       
      [ ] Track:0, id=textstream_fin=1000, mimeType=application/ttml+xml, bitrate=1000, language=fi, supported=YES                          
    ]                                                                                                                                       
    Group:2, adaptive_supported=N/A [                                                                                                       
      [ ] Track:0, id=textstream_nor=1000, mimeType=application/ttml+xml, bitrate=1000, language=no, supported=YES                          
    ]                                                                                                                                       
    Group:3, adaptive_supported=N/A [                                                                                                       
      [ ] Track:0, id=textstream_swe=1000, mimeType=application/ttml+xml, bitrate=1000, language=sv, supported=YES                          
    ]                                                                                                                                       
  ]                                                                                                                                         
]

**Comment by AquilesCanta** [comment]
This issue is being closed because it does not adhere to our issue template, and/or because it omits information requested in the issue template that is required for us to investigate the problem efficiently. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

If you’re able to provide complete information as requested in the issue template, please do so below and we’ll re-open the issue. Thanks!
