### ISSUE TITLE
Ended event is not fired if media vtt is identified by player as longer than video duration 

### ISSUE THREAD

**Issue by giladna** [google/ExoPlayer#3818]
Hi,

In this HLS media
http://cdnapi.kaltura.com/p/1740481/sp/174048100/playManifest/entryId/1_jimvnyp9/flavorIds/1_gvcbf42g,1_tkn15li1,1_3f38gi0r,1_686ra1j7/format/applehttp/protocol/http/a.m3u8

You can notice in the manifest that the video duration is 3:52 and also the vtt SUBTITLES english file segmented to 3:52

for some reason the player identifies that the Subtitles VTT is longer than the video and if seek to end is done, the ENDED state is not fired until player counts to 4:30

if I disable subtitles and seek to end player will fire the ENDED event.

this is happening  in 2.6.0 & 2.6.1 but not in 2.5.4 demo apps 

10x
Gilad. #

**Comment by ojw28** [comment]
The HLS media playlist [a.m3u8](http://cdnbakmi.kaltura.com/api_v3/index.php/service/caption_captionasset/action/serveWebVTT/captionAssetId/1_2fld3obp/ks/djJ8MTc0MDQ4MXyF7R2aVXtw-bAyLoWL-ccB1wrmoFiWlf8B9qvgXNZQwX-2s9mStHV0aVkjCeyLlsThCD-1UUTP_sZf8KG8AbJjwXcc5QOUOhDRLEEuK3ynW-S6PsYa7xRoleyz75qXM3hslv3T4SK5xrO3tlWFfD4luvRfGKqNI4OH4piFYWK96UgROzOs-yPiB45cNHAsdu2LANmes3WT2jINVPfrwJJqP6vNZ2xPpS7SLrK0odcwUJFJbk48f9j5flOfmuVw3PsietVZRo_EPvA5mFJOMKXi/a.m3u8) indicates the last VTT segment starts at 3:30 and ends at 3:52:
```
#EXTINF:30.0,
segmentIndex/1.vtt
#EXTINF:30.0,
segmentIndex/2.vtt
#EXTINF:30.0,
segmentIndex/3.vtt
#EXTINF:30.0,
segmentIndex/4.vtt
#EXTINF:30.0,
segmentIndex/5.vtt
#EXTINF:30.0,
segmentIndex/6.vtt
#EXTINF:30.0,
segmentIndex/7.vtt
#EXTINF:22.0,
segmentIndex/8.vtt
#EXT-X-ENDLIST
```

But the actual segment [8.vtt](http://cdnbakmi.kaltura.com/api_v3/index.php/service/caption_captionasset/action/serveWebVTT/captionAssetId/1_2fld3obp/ks/djJ8MTc0MDQ4MXyF7R2aVXtw-bAyLoWL-ccB1wrmoFiWlf8B9qvgXNZQwX-2s9mStHV0aVkjCeyLlsThCD-1UUTP_sZf8KG8AbJjwXcc5QOUOhDRLEEuK3ynW-S6PsYa7xRoleyz75qXM3hslv3T4SK5xrO3tlWFfD4luvRfGKqNI4OH4piFYWK96UgROzOs-yPiB45cNHAsdu2LANmes3WT2jINVPfrwJJqP6vNZ2xPpS7SLrK0odcwUJFJbk48f9j5flOfmuVw3PsietVZRo_EPvA5mFJOMKXi/segmentIndex/8.vtt) contains a caption that starts at 2:50 and ends at 4:30:
```
WEBVTT

00:02:50.000 --> 00:03:30.000
Second minute captions 11

00:03:50.000 --> 00:04:30.000
Third minute captions 12
```
So I think the content is broken.

**Comment by tonihei** [comment]
The [last VTT subtitle segment ](http://cdnbakmi.kaltura.com/api_v3/index.php/service/caption_captionasset/action/serveWebVTT/captionAssetId/1_2fld3obp/ks/djJ8MTc0MDQ4MXxMeLWBfVo41eSflrJyS3q654J9VhbAI0qhcOTCtMIMfKLljcjihD-NKAAfiHj6uR1kl58Bh7X935wDbepdOXEkJNApNBc51NSpZ4eGzG-Jn5ZRUTIKRd0mckG-lkys_2fFm-T6UZt5RRyh0DgZaUq3DPfel3t4tEL32_fsjMO8WAs9ZXU6yiNRzb0Y1sQ-K7J9Jhg2bqJCNkyoHeO6FIjcpmfwTEExJrDVd1zBgu28hL8T7IcQNS4zNgUpw11qBnMmQPcySHub6-avEq17U9Ee/segmentIndex/8.vtt)includes a subtitle from 03:50:00 to 04:30:00. The player keeps displaying this subtitle until the specified end time (and thus does not transition to the ended state). This is therefore working as intended. 

It seems the subtitle contents should match the specified duration of the segment for this to work correctly. Maybe @AquilesCanta can give further advice if that is indeed a HLS requirement.
