### ISSUE TITLE
Feature request for a getter method in MediaCodecInfo

### ISSUE THREAD

**Issue by ggabdol** [google/ExoPlayer#3820]
### Issue description
Feature request for a getter method in [com.google.android.exoplayer2.mediacodec.MediaCodecInfo](https://github.com/google/ExoPlayer/blob/deb9b301b2c7ef66fdd7d8a3e58298a79ba9c619/library/core/src/main/java/com/google/android/exoplayer2/mediacodec/MediaCodecInfo.java#L73)
```
public MediaCodecInfo.CodecCapabilities getCapabilities() {
    return capabilities;
}
```
[Link to the member field](https://github.com/google/ExoPlayer/blob/deb9b301b2c7ef66fdd7d8a3e58298a79ba9c619/library/core/src/main/java/com/google/android/exoplayer2/mediacodec/MediaCodecInfo.java#L73)

I'm trying to call the following method in android.media.MediaCodecInfo.CodecCapabilities that the MediaCodecInfo has as a member field, but it's private. Can we make a getter for this member?
[MediaCodecInfo.CodecCapabilities#getMaxSupportedInstances](https://developer.android.com/reference/android/media/MediaCodecInfo.CodecCapabilities.html#getMaxSupportedInstances())
```
/**
 * Returns the max number of the supported concurrent codec instances.
 * <p>
 * This is a hint for an upper bound. Applications should not expect to successfully
 * operate more instances than the returned value, but the actual number of
 * concurrently operable instances may be less as it depends on the available
 * resources at time of use.
 */
public int getMaxSupportedInstances() {
    return mMaxSupportedInstances;
}
```

### Version of ExoPlayer being used
r2.6.1

**Comment by ojw28** [comment]
Seems reasonable that we could:

* Make the capabilities field public (although note it can be null in the passthrough case)
* Make a `MediaCodecInfo.getMaxSupportedInstances` method that returns the maximum supported instances, or some default (e.g. -1) if unknown.
