### ISSUE TITLE
setPlaybackSpeed( float ) implementation

### ISSUE THREAD

**Issue by mwitchwilliams** [google/ExoPlayer#3821]
Trying to implement the _setPlaybackSpeed( float )_ method, but it appears it was never merged into ExoPlayer.
There is discussion at https://github.com/google/ExoPlayer/pull/2417 but this appears there may have been issues, and it's been close to a year.

Is there an alternative to this implementation?

**Comment by andrewlewis** [comment]
To change the playback speed, call `player.setPlaybackParameters` passing in a `PlaybackParameters` instance with the required speed.

There's also a [blog post with more information](https://medium.com/google-exoplayer/variable-speed-playback-with-exoplayer-e6e6a71e0343).
