### ISSUE TITLE
Exoplayer version 2.3.1 is going to buffering state in every 2, 3 seconds .

### ISSUE THREAD

**Issue by pals-ric** [google/ExoPlayer#3823]
### Logs

02-09 12:04:35.841 2539-2539/com.ideacellular.digitalvideo D/PlayerImplementation: focusChange: -1
02-09 12:04:35.913 2539-2539/com.ideacellular.digitalvideo E/PlayerImplementation: STATE_BUFFERING: 
02-09 12:04:35.913 2539-2539/com.ideacellular.digitalvideo D/PlayerState: player buffering.....
02-09 12:04:35.914 2539-2539/com.ideacellular.digitalvideo D/VideoControllerView: show: 3000
02-09 12:04:35.914 2539-2539/com.ideacellular.digitalvideo D/VideoControllerView: Set Replay Image: isPlaying
02-09 12:04:35.915 2539-2539/com.ideacellular.digitalvideo I/System.out: tag :MediaEventHungamaObject Buffer:startBuffer/////////////////// 1
02-09 12:04:35.915 2539-2539/com.ideacellular.digitalvideo E/MediaEventHungamaObject Buffer: startBuffer/////////////////// 1
02-09 12:04:35.915 2539-2539/com.ideacellular.digitalvideo I/System.out: tag :TimerMaster:startBuffer null
02-09 12:04:35.915 2539-2539/com.ideacellular.digitalvideo E/TimerMaster: startBuffer null
02-09 12:04:35.915 2539-2539/com.ideacellular.digitalvideo I/System.out: tag :MediaEventHungamaObject Buffer:0
02-09 12:04:35.915 2539-2539/com.ideacellular.digitalvideo E/MediaEventHungamaObject Buffer: 0
02-09 12:04:35.915 2539-2539/com.ideacellular.digitalvideo I/System.out: tag :MediaEventHungamaObject Play:0
02-09 12:04:35.915 2539-2539/com.ideacellular.digitalvideo E/MediaEventHungamaObject Play: 0
02-09 12:04:35.915 2539-2539/com.ideacellular.digitalvideo I/System.out: tag :MediaEventHungamaObject text:playWhenReady=true, playbackState=buffering
02-09 12:04:35.915 2539-2539/com.ideacellular.digitalvideo E/MediaEventHungamaObject text: playWhenReady=true, playbackState=buffering
02-09 12:04:35.915 2539-2539/com.ideacellular.digitalvideo D/EventLogger: state [2.09, true, B]
02-09 12:04:36.100 2539-2974/com.ideacellular.digitalvideo D/AudioTrack: Client defaulted notificationFrames to 3675 for frameCount 11025
02-09 12:04:36.163 3018-3018/com.android.providers.calendar I/CalendarProvider2: Sending notification intent: Intent { act=android.intent.action.PROVIDER_CHANGED dat=content://com.android.calendar flg=0x20000000 }
02-09 12:04:36.163 3018-3018/com.android.providers.calendar W/ContentResolver: Failed to get type for: content://com.android.calendar (Unknown URL content://com.android.calendar)
02-09 12:04:36.364 2539-2539/com.ideacellular.digitalvideo E/PlayerImplementation: STATE_READY: 
02-09 12:04:36.364 2539-2539/com.ideacellular.digitalvideo D/VideoControllerView: hide
02-09 12:04:36.365 2539-2539/com.ideacellular.digitalvideo D/VideoControllerView: show: 3000
02-09 12:04:36.366 2539-2539/com.ideacellular.digitalvideo D/VideoControllerView: Set Replay Image: isPlaying
02-09 12:04:36.367 2539-2539/com.ideacellular.digitalvideo D/VideoControllerView: Set Replay Image: isPlaying
02-09 12:04:36.367 2539-2539/com.ideacellular.digitalvideo I/System.out: tag :MediaEventHungamaObject Buffer:0
02-09 12:04:36.367 2539-2539/com.ideacellular.digitalvideo E/MediaEventHungamaObject Buffer: 0
02-09 12:04:36.367 2539-2539/com.ideacellular.digitalvideo I/System.out: tag :MediaEventHungamaObject Play:0
02-09 12:04:36.367 2539-2539/com.ideacellular.digitalvideo E/MediaEventHungamaObject Play: 0
02-09 12:04:36.367 2539-2539/com.ideacellular.digitalvideo I/System.out: tag :TimerMaster:stopBuffer
02-09 12:04:36.367 2539-2539/com.ideacellular.digitalvideo E/TimerMaster: stopBuffer
02-09 12:04:36.367 2539-2539/com.ideacellular.digitalvideo I/System.out: tag :TimerMaster:startPlay
02-09 12:04:36.367 2539-2539/com.ideacellular.digitalvideo E/TimerMaster: startPlay
02-09 12:04:36.367 2539-2539/com.ideacellular.digitalvideo I/System.out: tag :MediaEventHungamaObject text:playWhenReady=true, playbackState=ready
02-09 12:04:36.367 2539-2539/com.ideacellular.digitalvideo E/MediaEventHungamaObject text: playWhenReady=true, playbackState=ready
02-09 12:04:36.367 2539-2539/com.ideacellular.digitalvideo D/EventLogger: state [2.54, true, R]
02-09 12:04:36.404 2539-2539/com.ideacellular.digitalvideo I/System.out: tag :currentDuration:62048
02-09 12:04:36.404 2539-2539/com.ideacellular.digitalvideo E/currentDuration: 62048
02-09 12:04:36.414 2539-2539/com.ideacellular.digitalvideo D/EventLogger: positionDiscontinuity
02-09 12:04:36.414 2539-2539/com.ideacellular.digitalvideo E/VideoControllerView: onPlaybackProgress: 62048: currentTimeMs62048
02-09 12:04:36.478 2539-2539/com.ideacellular.digitalvideo E/PlayerImplementation: STATE_BUFFERING: 
02-09 12:04:36.478 2539-2539/com.ideacellular.digitalvideo D/PlayerState: player buffering.....
02-09 12:04:36.479 2539-2539/com.ideacellular.digitalvideo D/VideoControllerView: show: 3000
02-09 12:04:36.479 2539-2539/com.ideacellular.digitalvideo D/VideoControllerView: Set Replay Image: isPlaying
02-09 12:04:36.479 2539-2539/com.ideacellular.digitalvideo I/System.out: tag :TimerMaster:startBuffer
02-09 12:04:36.479 2539-2539/com.ideacellular.digitalvideo E/TimerMaster: startBuffer
02-09 12:04:36.479 2539-2539/com.ideacellular.digitalvideo I/System.out: tag :MediaEventHungamaObject Buffer:0
02-09 12:04:36.479 2539-2539/com.ideacellular.digitalvideo E/MediaEventHungamaObject Buffer: 0
02-09 12:04:36.479 2539-2539/com.ideacellular.digitalvideo I/System.out: tag :MediaEventHungamaObject Play:0
02-09 12:04:36.479 2539-2539/com.ideacellular.digitalvideo E/MediaEventHungamaObject Play: 0
02-09 12:04:36.479 2539-2539/com.ideacellular.digitalvideo I/System.out: tag :MediaEventHungamaObject text:playWhenReady=true, playbackState=buffering
02-09 12:04:36.479 2539-2539/com.ideacellular.digitalvideo E/MediaEventHungamaObject text: playWhenReady=true, playbackState=buffering
02-09 12:04:36.479 2539-2539/com.ideacellular.digitalvideo D/EventLogger: state [2.65, true, B]
02-09 12:04:36.727 2539-3083/com.ideacellular.digitalvideo I/System.out: tag :IncrementalEventPostTimer:MoviePlayedDuration
02-09 12:04:36.727 2539-3083/com.ideacellular.digitalvideo E/IncrementalEventPostTimer: MoviePlayedDuration
02-09 12:04:36.767 2539-2974/com.ideacellular.digitalvideo D/AudioTrack: Client defaulted notificationFrames to 3675 for frameCount 11025
02-09 12:04:36.970 2539-2539/com.ideacellular.digitalvideo E/PlayerImplementation: STATE_READY: 
02-09 12:04:36.971 2539-2539/com.ideacellular.digitalvideo D/VideoControllerView: hide
02-09 12:04:36.972 2539-2539/com.ideacellular.digitalvideo D/VideoControllerView: show: 3000
02-09 12:04:36.972 2539-2539/com.ideacellular.digitalvideo D/VideoControllerView: Set Replay Image: isPlaying
02-09 12:04:36.973 2539-2539/com.ideacellular.digitalvideo D/VideoControllerView: Set Replay Image: isPlaying
02-09 12:04:36.973 2539-2539/com.ideacellular.digitalvideo I/System.out: tag :MediaEventHungamaObject Buffer:0
02-09 12:04:36.973 2539-2539/com.ideacellular.digitalvideo E/MediaEventHungamaObject Buffer: 0
02-09 12:04:36.973 2539-2539/com.ideacellular.digitalvideo I/System.out: tag :MediaEventHungamaObject Play:0
02-09 12:04:36.973 2539-2539/com.ideacellular.digitalvideo E/MediaEventHungamaObject Play: 0
02-09 12:04:36.973 2539-2539/com.ideacellular.digitalvideo I/System.out: tag :TimerMaster:stopBuffer
02-09 12:04:36.973 2539-2539/com.ideacellular.digitalvideo E/TimerMaster: stopBuffer
02-09 12:04:36.973 2539-2539/com.ideacellular.digitalvideo I/System.out: tag :TimerMaster:startPlay
02-09 12:04:36.973 2539-2539/com.ideacellular.digitalvideo E/TimerMaster: startPlay
02-09 12:04:36.973 2539-2539/com.ideacellular.digitalvideo I/System.out: tag :MediaEventHungamaObject text:playWhenReady=true, playbackState=ready
02-09 12:04:36.973 2539-2539/com.ideacellular.digitalvideo E/MediaEventHungamaObject text: playWhenReady=true, playbackState=ready
02-09 12:04:36.973 2539-2539/com.ideacellular.digitalvideo D/EventLogger: state [3.15, true, R]
02-09 12:04:37.030 2539-2539/com.ideacellular.digitalvideo I/System.out: tag :currentDuration:62066
02-09 12:04:37.030 2539-2539/com.ideacellular.digitalvideo E/currentDuration: 62066
02-09 12:04:37.036 2539-2539/com.ideacellular.digitalvideo D/EventLogger: positionDiscontinuity
02-09 12:04:37.037 2539-2539/com.ideacellular.digitalvideo E/VideoControllerView: onPlaybackProgress: 62066: currentTimeMs62066
02-09 12:04:37.049 2539-2539/com.ideacellular.digitalvideo E/PlayerImplementation: STATE_BUFFERING: 
02-09 12:04:37.049 2539-2539/com.ideacellular.digitalvideo D/PlayerState: player buffering.....
02-09 12:04:37.050 2539-2539/com.ideacellular.digitalvideo D/VideoControllerView: show: 3000
02-09 12:04:37.050 2539-2539/com.ideacellular.digitalvideo D/VideoControllerView: Set Replay Image: isPlaying
02-09 12:04:37.052 2539-2539/com.ideacellular.digitalvideo I/System.out: tag :TimerMaster:startBuffer
02-09 12:04:37.052 2539-2539/com.ideacellular.digitalvideo E/TimerMaster: startBuffer
02-09 12:04:37.052 2539-2539/com.ideacellular.digitalvideo I/System.out: tag :MediaEventHungamaObject Buffer:0
02-09 12:04:37.052 2539-2539/com.ideacellular.digitalvideo E/MediaEventHungamaObject Buffer: 0
02-09 12:04:37.052 2539-2539/com.ideacellular.digitalvideo I/System.out: tag :MediaEventHungamaObject Play:0
02-09 12:04:37.052 2539-2539/com.ideacellular.digitalvideo E/MediaEventHungamaObject Play: 0
02-09 12:04:37.053 2539-2539/com.ideacellular.digitalvideo I/System.out: tag :MediaEventHungamaObject text:playWhenReady=true, playbackState=buffering
02-09 12:04:37.053 2539-2539/com.ideacellular.digitalvideo E/MediaEventHungamaObject text: playWhenReady=true, playbackState=buffering
02-09 12:04:37.053 2539-2539/com.ideacellular.digitalvideo D/EventLogger: state [3.22, true, B]
02-09 12:04:37.292 2539-2974/com.ideacellular.digitalvideo D/AudioTrack: Client defaulted notificationFrames to 3675 for frameCount 11025
02-09 12:04:37.482 2539-2539/com.ideacellular.digitalvideo E/PlayerImplementation: STATE_READY: 
02-09 12:04:37.482 2539-2539/com.ideacellular.digitalvideo D/VideoControllerView: hide
02-09 12:04:37.484 2539-2539/com.ideacellular.digitalvideo D/VideoControllerView: show: 3000
02-09 12:04:37.485 2539-2539/com.ideacellular.digitalvideo D/VideoControllerView: Set Replay Image: isPlaying
02-09 12:04:37.485 2539-2539/com.ideacellular.digitalvideo D/VideoControllerView: Set Replay Image: isPlaying
02-09 12:04:37.485 2539-2539/com.ideacellular.digitalvideo I/System.out: tag :MediaEventHungamaObject Buffer:1
02-09 12:04:37.485 2539-2539/com.ideacellular.digitalvideo E/MediaEventHungamaObject Buffer: 1
02-09 12:04:37.485 2539-2539/com.ideacellular.digitalvideo I/System.out: tag :MediaEventHungamaObject Play:0
02-09 12:04:37.485 2539-2539/com.ideacellular.digitalvideo E/MediaEventHungamaObject Play: 0
02-09 12:04:37.485 2539-2539/com.ideacellular.digitalvideo I/System.out: tag :TimerMaster:stopBuffer
02-09 12:04:37.485 2539-2539/com.ideacellular.digitalvideo E/TimerMaster: stopBuffer
02-09 12:04:37.485 2539-2539/com.ideacellular.digitalvideo I/System.out: tag :TimerMaster:startPlay
02-09 12:04:37.485 2539-2539/com.ideacellular.digitalvideo E/TimerMaster: startPlay
02-09 12:04:37.486 2539-2539/com.ideacellular.digitalvideo I/System.out: tag :MediaEventHungamaObject text:playWhenReady=true, playbackState=ready
02-09 12:04:37.486 2539-2539/com.ideacellular.digitalvideo E/MediaEventHungamaObject text: playWhenReady=true, playbackState=ready
02-09 12:04:37.486 2539-2539/com.ideacellular.digitalvideo D/EventLogger: state [3.66, true, R]
02-09 12:04:37.511 2539-2539/com.ideacellular.digitalvideo I/System.out: tag :currentDuration:62066
02-09 12:04:37.511 2539-2539/com.ideacellular.digitalvideo E/currentDuration: 62066
02-09 12:04:37.511 2539-2539/com.ideacellular.digitalvideo E/VideoControllerView: onPlaybackProgress: 62066: currentTimeMs62066
02-09 12:04:37.727 2539-3083/com.ideacellular.digitalvideo I/System.out: tag :IncrementalEventPostTimer:MoviePlayedDuration
02-09 12:04:37.727 2539-3083/com.ideacellular.digitalvideo E/IncrementalEventPostTimer: MoviePlayedDuration
02-09 12:04:37.727 2539-3083/com.ideacellular.digitalvideo I/System.out: tag :BufferedDuration 0:0
02-09 12:04:37.727 2539-3083/com.ideacellular.digitalvideo E/BufferedDuration 0: 0
02-09 12:04:37.727 2539-3083/com.ideacellular.digitalvideo I/System.out: tag :BufferedDuration 1:0
02-09 12:04:37.727 2539-3083/com.ideacellular.digitalvideo E/BufferedDuration 1: 0
02-09 12:04:37.727 2539-3083/com.ideacellular.digitalvideo I/System.out: tag :BufferedDuration last 1:0
02-09 12:04:37.727 2539-3083/com.ideacellular.digitalvideo E/BufferedDuration last 1: 0
02-09 12:04:37.727 2539-3083/com.ideacellular.digitalvideo I/System.out: tag :BufferedDuration:1
02-09 12:04:37.727 2539-3083/com.ideacellular.digitalvideo E/BufferedDuration: 1
02-09 12:04:37.727 2539-3083/com.ideacellular.digitalvideo I/System.out: tag :BufferedDuration last:0
02-09 12:04:37.727 2539-3083/com.ideacellular.digitalvideo E/BufferedDuration last: 0
02-09 12:04:38.428 2539-2539/com.ideacellular.digitalvideo I/System.out: tag :EventLogger:bandwidth [747014]
02-09 12:04:38.428 2539-2539/com.ideacellular.digitalvideo D/EventLogger: bandwidth [747014]
02-09 12:04:38.511 2539-2539/com.ideacellular.digitalvideo I/System.out: tag :currentDuration:63000
02-09 12:04:38.511 2539-2539/com.ideacellular.digitalvideo E/currentDuration: 63000
02-09 12:04:38.520 2539-2539/com.ideacellular.digitalvideo D/EventLogger: positionDiscontinuity
02-09 12:04:38.520 2539-2539/com.ideacellular.digitalvideo E/VideoControllerView: onPlaybackProgress: 63000: currentTimeMs63000
02-09 12:04:38.561 2539-2539/com.ideacellular.digitalvideo E/PlayerImplementation: STATE_BUFFERING: 
02-09 12:04:38.561 2539-2539/com.ideacellular.digitalvideo D/PlayerState: player buffering.....
02-09 12:04:38.566 2539-2539/com.ideacellular.digitalvideo D/VideoControllerView: show: 3000
02-09 12:04:38.566 2539-2539/com.ideacellular.digitalvideo D/VideoControllerView: Set Replay Image: isPlaying
02-09 12:04:38.566 2539-2539/com.ideacellular.digitalvideo I/System.out: tag :TimerMaster:startBuffer
02-09 12:04:38.566 2539-2539/com.ideacellular.digitalvideo E/TimerMaster: startBuffer
02-09 12:04:38.566 2539-2539/com.ideacellular.digitalvideo I/System.out: tag :MediaEventHungamaObject Buffer:1
02-09 12:04:38.566 2539-2539/com.ideacellular.digitalvideo E/MediaEventHungamaObject Buffer: 1
02-09 12:04:38.566 2539-2539/com.ideacellular.digitalvideo I/System.out: tag :MediaEventHungamaObject Play:1
02-09 12:04:38.566 2539-2539/com.ideacellular.digitalvideo E/MediaEventHungamaObject Play: 1
02-09 12:04:38.566 2539-2539/com.ideacellular.digitalvideo I/System.out: tag :MediaEventHungamaObject text:playWhenReady=true, playbackState=buffering
02-09 12:04:38.566 2539-2539/com.ideacellular.digitalvideo E/MediaEventHungamaObject text: playWhenReady=true, playbackState=buffering
02-09 12:04:38.566 2539-2539/com.ideacellular.digitalvideo D/EventLogger: state [4.74, true, B]
02-09 12:04:38.583 3050-3050/com.google.android.apps.messaging I/Bugle: BootAndPackageReplacedReceiver: run after reboot tasks
02-09 12:04:38.594 3214-3214/? W/art: Unexpected CPU variant for X86 using defaults: x86
02-09 12:04:38.599 1741-1754/system_process I/ActivityManager: Start proc 3214:com.google.android.apps.photos/u0a89 for broadcast com.google.android.apps.photos/.camerashortcut.CameraShortcutBroadcastReceiver
02-09 12:04:38.617 3214-3221/? E/art: Failed sending reply to debugger: Broken pipe
02-09 12:04:38.617 3214-3221/? I/art: Debugger is no longer active
02-09 12:04:38.617 3214-3221/? I/art: Starting a blocking GC Instrumentation

**Comment by AquilesCanta** [comment]
This issue is being closed because it does not adhere to our issue template, and/or because it omits information requested in the issue template that is required for us to investigate the problem efficiently. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

If you’re able to provide complete information as requested in the issue template, please do so below and we’ll re-open the issue. Thanks!
