### ISSUE TITLE
Add support for displaying video title in PlayerView

### ISSUE THREAD

**Issue by wezley98** [google/ExoPlayer#3824]
### Issue description
When using Google Media Framework there was support to pass a video title to the player view, but this feature doesn't seem to exist in ExoPlayer v2, I have checked the javadocs couldn't see any reference to a video title https://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/ui/SimpleExoPlayerView.html

Is this something you would consider adding or am I missing something?

### Version of ExoPlayer being used
v2.6.1

**Comment by AquilesCanta** [comment]
> When using Google Media Framework there was support to pass a video title to the player view

Could you point me to the documentation for this particular piece of the API? 

Could you also please clarify what the expected behavior for SimpleExoPlayerView video title would be?

**Comment by wezley98** [comment]
@AquilesCanta Thanks for replying,

This is the method sig: https://github.com/googleads/google-media-framework-android/blob/254e3574a550212acae3510bbbd02ccdb519801f/demo/src/main/java/com/google/googlemediaframeworkdemo/demo/adplayer/ImaPlayer.java#L362

You can see the video title in the screenshot here: https://github.com/googleads/google-media-framework-android

and instructions for use:
https://github.com/googleads/google-media-framework-android/wiki/Step-by-Step-Usage

Ideally just match what GMF did for video title. Place it at the top of the view match_parent etc.

**Comment by AquilesCanta** [comment]
Thanks for the resources. I'll propose it with the rest of the team as a PlayerView enhancement. In the meantime, you can extend PlayerView to add in a [similar way to what GMF does](https://github.com/googleads/google-media-framework-android/blob/master/googlemediaframework/src/main/java/com/google/android/libraries/mediaframework/layeredvideo/PlaybackControlLayer.java#L381).

**Comment by ojw28** [comment]
This is something an app could easily do itself using a view placed on top of the `PlayerView`, isn't it? Or by defining their own `exo_player_view.xml` containing an additional view. I don't think there's a strong case for the library providing direct support for this.
