### ISSUE TITLE
Application crash playing successive mp4s

### ISSUE THREAD

**Issue by bshellenberg** [google/ExoPlayer#3825]
### Issue description
Question more than anything. I'm using exoplayer in a very simple manner. A video plays from local storage. When it finishes, it plays another and so on. What is happening is the application crashes when trying to play the third video. The oddity is if I toggle invisibility before preparing the new video, the crash does not occur. Question being, what happens internally when setvisibility is toggled?

### Reproduction steps
The code I use is attached. In my app, I check for playing() and call setVideoPath() once the previous video is finished.

### Link to test content
https://verticals.starmont.ca/products/v1/clients/111/files/a0c87089403e5c6b35ab4cb16b47b00e.mp4
https://verticals.starmont.ca/products/v1/clients/111/files/7af91ad5042636b86e8f2a3f795ffa37.mp4
https://verticals.starmont.ca/products/v1/clients/111/files/b3fbb3498ca1795a421ea3220abfc18b.mp4

### Version of ExoPlayer being used
2.6.1

### Device(s) and version(s) of Android being used
Generic Amlogic S805 Cortex-A5 TV box
Android 4.4.2 (api 19)

### A full bug report captured from the device
adb logcat (when the crash occcurs) gives me:

02-09 06:48:01.012 E/ion     (  134): ioctl c0144900 failed with code -1: Out of memory
02-09 06:48:01.012 E/[Gralloc-ERROR](  134): int gralloc_alloc_buffer(alloc_device_t*, size_t, int, const native_handle_t**):119 Failed to ion_alloc from ion_client:20
02-09 06:48:01.012 W/GraphicBufferAllocator(  134): alloc(1920, 1080, 17, 20002900, ...) failed -1 (Operation not permitted)
02-09 06:48:01.012 E/        (  134): GraphicBufferAlloc::createGraphicBuffer(w=1920, h=1080) failed (Operation not permitted), handle=0x0
02-09 06:48:01.012 E/BufferQueue(  134): [SurfaceView] dequeueBuffer: SurfaceComposer::createGraphicBuffer failed
02-09 06:48:01.012 E/ACodec  ( 5890): dequeueBuffer failed.
02-09 06:48:01.012 F/ACodec  ( 5890): frameworks/av/media/libstagefright/ACodec.cpp:3317 CHECK_EQ( mCodec->submitOutputMetaDataBuffer(),(status_t)OK) failed: -1004 vs. 0
02-09 06:48:01.012 F/libc    ( 5890): Fatal signal 6 (SIGABRT) at 0x00001702 (code=-6), thread 6098 (CodecLooper)
0

The out of memory error occurs when starting to play the SECOND video. It is not present on playing the first. The app does not crash at this point, however.

[bugreport1.zip](https://github.com/google/ExoPlayer/files/1711454/bugreport1.zip)
[samplecode.zip](https://github.com/google/ExoPlayer/files/1711455/samplecode.zip)

**Comment by AquilesCanta** [comment]
I cannot find anything obviously wrong in the provided resources. Can you reproduce the issue using a ConcatenatingMediaSource or DynamicConcatenatingMediaSource? Maybe use that approach instead of the current one?

**Comment by bshellenberg** [comment]
I awaited 2.7.0 to see if any changes would fix this issue, but to no avail. Text from adb logcat when playing a video that causes the crash:

02-22 08:49:46.357 W/ALooperRoster( 1340): ALooper::handler_id ALooperRoster::registerHandler 6
02-22 08:49:46.357 W/ALooperRoster( 1340): ALooper::handler_id ALooperRoster::registerHandler 7
02-22 08:49:46.367 W/OmxLogConf(  138): Can not read property media.omx.log_levels, using 0
02-22 08:49:46.367 E/OmxVideoDecoder(  138):  reset input buffer:1036800
02-22 08:49:46.367 E/OmxVideoDecoder(  138): OMX.amlogic.avc.decoder.awesome: useBuffer 155 nPortIndex 0 pAppPrivate 0xb7730440 nSizeBytes 1036800 pBuffer 0xb12f0000
02-22 08:49:46.367 E/OmxVideoDecoder(  138): OMX.amlogic.avc.decoder.awesome: useBuffer 155 nPortIndex 0 pAppPrivate 0xb77303a0 nSizeBytes 1036800 pBuffer 0xb13ed200
02-22 08:49:46.367 E/OmxVideoDecoder(  138): OMX.amlogic.avc.decoder.awesome: useBuffer 155 nPortIndex 0 pAppPrivate 0xb7739160 nSizeBytes 1036800 pBuffer 0xb14ea400
02-22 08:49:46.367 E/OmxVideoDecoder(  138): OMX.amlogic.avc.decoder.awesome: useBuffer 155 nPortIndex 0 pAppPrivate 0xb7734010 nSizeBytes 1036800 pBuffer 0xb15e7600
02-22 08:49:46.367 E/OmxVideoDecoder(  138): OMX.amlogic.avc.decoder.awesome: useBuffer 155 nPortIndex 0 pAppPrivate 0xb7733d38 nSizeBytes 1036800 pBuffer 0xb16e4800
02-22 08:49:46.377 E/OmxVideoDecoder(  138): OMX.amlogic.avc.decoder.awesome: useBuffer 155 nPortIndex 0 pAppPrivate 0xb77315e0 nSizeBytes 1036800 pBuffer 0xb17e1a00
02-22 08:49:46.377 E/OmxVideoDecoder(  138): OMX.amlogic.avc.decoder.awesome: useBuffer 155 nPortIndex 0 pAppPrivate 0xb7734ad8 nSizeBytes 1036800 pBuffer 0xb18dec00
02-22 08:49:46.377 E/OmxVideoDecoder(  138): OMX.amlogic.avc.decoder.awesome: useBuffer 155 nPortIndex 0 pAppPrivate 0xb773b1f0 nSizeBytes 1036800 pBuffer 0xb19dbe00
02-22 08:49:46.377 E/OmxVideoDecoder(  138): OMX.amlogic.avc.decoder.awesome: useBuffer 155 nPortIndex 0x1 pAppPrivate 0xb7739e70 nSizeBytes 8 pBuffer 0xb3b1f000
02-22 08:49:46.377 E/OmxVideoDecoder(  138): OMX.amlogic.avc.decoder.awesome: useBuffer 155 nPortIndex 0x1 pAppPrivate 0xb77389d0 nSizeBytes 8 pBuffer 0xb3b1f020
02-22 08:49:46.377 E/OmxVideoDecoder(  138): OMX.amlogic.avc.decoder.awesome: useBuffer 155 nPortIndex 0x1 pAppPrivate 0xb773a9e8 nSizeBytes 8 pBuffer 0xb3b1f040
02-22 08:49:46.377 E/OmxVideoDecoder(  138): OMX.amlogic.avc.decoder.awesome: useBuffer 155 nPortIndex 0x1 pAppPrivate 0xb7734080 nSizeBytes 8 pBuffer 0xb3b1f060
02-22 08:49:46.377 E/OmxVideoDecoder(  138): OMX.amlogic.avc.decoder.awesome: useBuffer 155 nPortIndex 0x1 pAppPrivate 0xb7731250 nSizeBytes 8 pBuffer 0xb3b1f080
02-22 08:49:46.517 E/ion     (  135): ioctl c0144900 failed with code -1: Out of memory
02-22 08:49:46.517 E/[Gralloc-ERROR](  135): int gralloc_alloc_buffer(alloc_device_t*, size_t, int, const native_handle_t**):119 Failed to ion_alloc from ion_client:20
02-22 08:49:46.517 W/GraphicBufferAllocator(  135): alloc(1920, 1080, 17, 20002900, ...) failed -1 (Operation not permitted)
02-22 08:49:46.517 E/        (  135): GraphicBufferAlloc::createGraphicBuffer(w=1920, h=1080) failed (Operation not permitted), handle=0x0
02-22 08:49:46.517 E/BufferQueue(  135): [SurfaceView] dequeueBuffer: SurfaceComposer::createGraphicBuffer failed
02-22 08:49:46.517 E/ACodec  ( 1340): dequeueBuffer failed.
02-22 08:49:46.517 F/ACodec  ( 1340): frameworks/av/media/libstagefright/ACodec.cpp:3317 CHECK_EQ( mCodec->submitOutputMetaDataBuffer(),(status_t)OK) failed: -1004 vs. 0
02-22 08:49:46.517 F/libc    ( 1340): Fatal signal 6 (SIGABRT) at 0x0000053c (code=-6), thread 1495 (CodecLooper)

**Comment by bshellenberg** [comment]
I asked about the hide/show since it seems that does something to perhaps reset a buffer or a state somewhere that stops this from happening. Again, the application is a simple one. Play (as an example) 10 video files stored locally on the device in succession, then repeat over and over. If the sequence of videos is 2 videos, it does not crash. If I add a third, it crashes. Platform bug perhaps? I tried ConcatenatingMediaSource and it did the same thing.

**Comment by andrewlewis** [comment]
Are you calling `exoplayer.release()` somewhere? It looks like something is leaking and causing memory to run out.

**Comment by bshellenberg** [comment]
only when the application is finished. is it necessary to do so even when the object remains in use?

**Comment by andrewlewis** [comment]
No. I thought you were making a new player but actually you're just re-preparing it with a new source which should be fine.

Can you reproduce the failure on any other devices?

**Comment by andrewlewis** [comment]
Also, please could you post a bug report taken just after reproducing the crash? bugreport1.zip doesn't seem to include the logging above.

**Comment by bshellenberg** [comment]
I just checked on another device, and it runs without error. So likely a platform issue. I will upload another bug report shortly.

**Comment by bshellenberg** [comment]
[bugreport2.zip](https://github.com/google/ExoPlayer/files/1748990/bugreport2.zip)

**Comment by bshellenberg** [comment]
Taken right after the crash.

**Comment by andrewlewis** [comment]
This sounds like it might be a device-specific issue that Amlogic will need to investigate. Strangely bugreport2.zip also seems to be missing the error logging. If you see `E/ACodec ( 1340): dequeueBuffer failed.` output to logcat and then immediately take a bug report does that log line not appear in the logcat in the bug report?

**Comment by bshellenberg** [comment]
[bugreport3.zip](https://github.com/google/ExoPlayer/files/1776373/bugreport3.zip)
Hopefully this is better.

**Comment by andrewlewis** [comment]
I couldn't diagnose this further based on the bug report. There aren't any obvious signs of a leak caused by the application.

As it seems to be device-specific, please report the issue to the device manufacturer. Thanks!
