### ISSUE TITLE
The player sends multiple duplicate requests

### ISSUE THREAD

**Issue by enginebai** [google/ExoPlayer#3826]
## Expected behavior
Hi, we develop feed similar to Facebook or Instagram as a new feature in our app, the video will auto-play as the user scrolls the feed, the most visible item will resume the video and other items will pause.
Our video is DASH format and we use `ExoPlayer` in `RecyclerView` and use `OkHttp` as http client which also enables cache mechanism. 

## Problem
The video plays normally, and we don't do anything on the screen (i.e. scroll or click), but the player continue to send lots of duplicate requests while playing and replaying.
![developer_tools](https://user-images.githubusercontent.com/3387462/36035472-fb79c02c-0df1-11e8-9562-dc59550daeb3.jpeg)

The request and response:
![developer tools -_061](https://user-images.githubusercontent.com/3387462/36035543-2720e494-0df2-11e8-8331-a6068aa2e230.png)

And we check the cache files on the device, the cache files `8fbe8e466152eeef7e012d0521ef6308.0` and `8fbe8e466152eeef7e012d0521ef6308.1`:
![cache](https://user-images.githubusercontent.com/3387462/36035586-49bec142-0df2-11e8-9832-de66015a693c.jpeg)
Both files are end with tmp. and ``8fbe8e466152eeef7e012d0521ef6308.1`` is a empty file. We go through the cache directory, and several pair `.0` `.1` file are tmp, and `.1` file is always zero size.

#### OkHttpClient
```java
public synchronized static OkHttpClient buildPlayerHttpClient(Context context) {
	HttpLoggingInterceptor interceptor = new HttpLoggingInterceptor();
	interceptor.setLevel(HttpLoggingInterceptor.Level.BASIC);
	OkHttpClient.Builder builder = new OkHttpClient.Builder();
	if (((GlobalContext) context.getApplicationContext()).isDebugMode()) {
		builder.addInterceptor(interceptor);
		builder.addNetworkInterceptor(new StethoInterceptor());
	}
	List<Protocol> protocols = new ArrayList<>();
	protocols.add(Protocol.HTTP_2);
	protocols.add(Protocol.HTTP_1_1);
	builder.protocols(protocols);
	builder.cache(ApiHelper.getPlayerCacheInstance(context));
	ConnectionPool connectionPool = new ConnectionPool(1, 1, TimeUnit.SECONDS);
	builder.connectionPool(connectionPool);
	builder.connectTimeout(30, TimeUnit.SECONDS);
	builder.readTimeout(30, TimeUnit.SECONDS);

	builder.retryOnConnectionFailure(false);
	return builder.build();
}
```

#### Cache
```java
private volatile static Cache sPlayerCache;

public static Cache getPlayerCacheInstance(Context context) {
	synchronized (ApiHelper.class) {
		if (sPlayerCache == null) {
			long cacheSize = FirebaseRemoteConfig.getInstance().getLong(RemoteConfigKey.DASH_CACHE_SIZE);
			if (cacheSize <= 0)
				cacheSize = 1500 * 1024 * 1024; // 1.5 GB
			File file = new File(context.getCacheDir(), "media");
			if (!file.exists())
				file.mkdirs();
			sPlayerCache = new Cache(file, cacheSize);
			try {
				sPlayerCache.initialize();
			}
			catch (IOException e) {
				e.printStackTrace();
			}
		}
	}
	return sPlayerCache;
}
```

#### DataSource.Factory
```java
public static HttpDataSource.Factory buildHttpDataSourceFactory(
		OkHttpClient httpClient,
		String userAgent,
		String jwt,
		DefaultBandwidthMeter bandwidthMeter) {
	HttpDataSource.Factory factory =
			new OkHttpDataSourceFactory(
			httpClient,
			userAgent,
			bandwidthMeter);
	factory.getDefaultRequestProperties().set(ApiHelper.HEADER_AUTHORIZATION, "Bearer " + jwt);
	return factory;
}
```

#### Player
https://gist.github.com/enginebai/73a693ea038112d53c5d3ea9ec867165

#### MPD format
https://gist.github.com/enginebai/63cbdab32b3c643c5e66debfa52623d8

We will provide our video via email if you need it.

## ExoPlayer Version
The exoplayer modules are cloned from `release-v2` branch.
```
implementation project(':exoplayer-core')
implementation project(':exoplayer-ui')
implementation project(':exoplayer-dash')
compile('com.google.android.exoplayer:extension-okhttp:2.6.0')
implementation 'com.squareup.okhttp3:okhttp:3.8.1'
```

## Android devices and versions
Sony G3226, Android 7.0

How can we fix the problem? Thank you for your help.

**Comment by AquilesCanta** [comment]
Just to clarify: 

- The only caching mechanism being used is OkHttp's. 
- Repeated URL access are generated by preparing a player, then releasing it, and the preparing a new one with the same content.
- The expected behavior is that only one HTTP request per URL is made, since later requests should be fulfilled by the cache.

Are these statements right? If so, this sounds more like something that should be reported to OkHttp than ExoPlayer. If any of these is not right, could you correct me, please?

**Comment by enginebai** [comment]
@AquilesCanta Hi,
1. The only caching machanism is OkHttp's. We don't use any exoplayer builtin caching components.
2. `Repeated URL access ...`, sorry, I don't get it, could you explain more detail?
3. Yes, our problem is why there are so many duplicate requests in a short period of time and the caches seem to be not working.

**Comment by enginebai** [comment]
We create player pool (queue) containing multiple exoplayer instances used in feed, get from player pool and assign player to view holder when `onViewAttachedToWindow()`, stop player and retrun back to pool when `onViewDetachedFromWindow()`. I suspect that the player instance references are messed when  poping/pushing from queue. That is, in the begining, pool = (A, B, C) and after some scrolling, pool might be (A, A, C), and the most visible feed gets A player and prepare, it might send multiple duplicate requests.

Is it possible?

**Comment by AquilesCanta** [comment]
I suppose that calling prepare twice on A might generate duplicate GETs to whatever URL it is supposed to play, and similar for any subsequent requests for the media (like, say, media chunks in DASH). In any case, I don't think this is an ExoPlayer issue. If you find evidence suggesting otherwise post it below and we'll reopen the issue.

**Comment by enginebai** [comment]
## Expected behavior
Hi, we're still developing the same feature: feed as same as the above description, and to fix the multiple duplicate requests problem.

## Implementation
We initialize a player list with a fixed size (default = 4), when the user scrolls the feed, the callback `RecyclerView.onViewAttachedToWindow(FeedViewHolder holder)` is called, we perform the following tasks:

1. Try to get a available player from the player list and assign to the view holder.
2. Parse dash manifest file.
3. Call `player.prepare(MediaSource)`.
4. Decide which attached view holder is the most visible item to auto-play `player.setPlayWhenReady()`.
![feed2](https://user-images.githubusercontent.com/3387462/36625628-37968f50-195e-11e8-95b2-852b5011b00f.png)


```java
@Override
public void onViewAttachedToWindow(FeedViewHolder holder) {
	super.onViewAttachedToWindow(holder);

    mAttachedViewHolderList.add(holder);

    int availablePosition = mPlayerController.getAvailablePlayerPosition(); // find the available player index

    if (availablePosition == -1) {
        return;
    }

    holder.setPlayerPosition(availablePosition);
    holder.setPlayerToPlayerView(mPlayerController.startUsingPlayer(availablePosition)); // get the player instance from list

	if (shouldPreparePlayer) {
        holder.parseDashManifest(holder.getFeed()); // parse dash manifest and prepare
    }

	decideWhichAttachedPlayerToPlay(); // provided below
}
```

```java
public void decideWhichAttachedPlayerToPlay() {
	if (mAttachedViewHolderList.isEmpty()) {
		return;
	}

	Collections.sort(mAttachedViewHolderList, new Comparator<FeedViewHolder>() {
		@Override
		public int compare(FeedViewHolder viewHolder1, FeedViewHolder viewHolder2) {
			return -(getVisibilityPercents(viewHolder1.getRootView()) -
                    getVisibilityPercents(viewHolder2.getRootView()));
		}
	});

    // play the most visible view holder
    FeedViewHolder mostVisibleViewHolder = mAttachedViewHolderList.get(0);
    mPlayerController.resumePlayer(mostVisibleViewHolder.getPlayerPosition()) // call player.setPlayWhenReady(true);

    // pause other players
	for (int i = 1; i < mAttachedViewHolderList.size(); i++) {
		FeedViewHolder otherViewHolder = mAttachedViewHolderList.get(i);
		mPlayerController.pausePlayer(otherViewHolder.getPlayerPosition()); // call player.setPlayWhenReady(false);
	}
}
```

When the view holder is scrolled off the screen, the callback `RecyclerView.onViewDetachedFromWindow(FeedViewHolder holder)` is called, we perform the following tasks:

1. Remove player listener and stop the player `Player.stop()`
2. Make this player be available in player list
![feed1](https://user-images.githubusercontent.com/3387462/36625629-3c931640-195e-11e8-871b-168ac1e4651a.png)


```java
@Override
public void onViewDetachedFromWindow(FeedViewHolder holder) {
	super.onViewDetachedFromWindow(holder);

    mAttachedViewHolderList.remove(holder);
	mPlayerController.stopUsingPlayer(holder.getPlayerPosition());
    holder.setPlayerPosition(-1);
    holder.setPlayerToPlayerView(null);
}
```

## Problem
After the user scrolls faster or fling for a period of time, the player will send multiple duplicate requests (*.mp4 and *.m4s) when replaying (not happen every time, but frequently). We've tested the case of setting repeat mode to off, the problem will be gone. We change the way of repeat to use `player.seekTo(0);` according to [stackoverflow answer](https://stackoverflow.com/questions/32005855/how-to-restart-video-on-exoplayer-after-exoplayer-state-ended), the problem is still there.

If the user scroll fast enought, the player will stop, return to the list from previous view holder, and be used by the next view holder, prepare the different media source immediately. The following diagram shows that the play in _VH0_ stops, and prepare in _VH3_ immediately when fast scrolling.
![feed](https://user-images.githubusercontent.com/3387462/36625675-1402970e-195f-11e8-92ac-e3ade25647b0.png)

Is there any problem of the way we use the player list? We guess that `Player.stop()` is asynchrous operations and will not stop immediately, but we use the same player to prepare different media source right away, that caused this problem. Or in our case, how can we stop preparing correctly?

Thanks again for your help.

**Comment by enginebai** [comment]
## Expected behavior
Hi, we're still developing the same feature: feed as same as the above description, and to fix the multiple duplicate requests problem.

## Implementation
We initialize a player list with a fixed size (default = 4), when the user scrolls the feed, the callback `RecyclerView.onViewAttachedToWindow(FeedViewHolder holder)` is called, we perform the following tasks:

1. Try to get a available player from the player list and assign to the view holder.
2. Parse dash manifest file.
3. Call `player.prepare(MediaSource)`.
4. Decide which attached view holder is the most visible item to auto-play `player.setPlayWhenReady()`.
![feed2](https://user-images.githubusercontent.com/3387462/36625628-37968f50-195e-11e8-95b2-852b5011b00f.png)


```java
@Override
public void onViewAttachedToWindow(FeedViewHolder holder) {
	super.onViewAttachedToWindow(holder);

    mAttachedViewHolderList.add(holder);

    int availablePosition = mPlayerController.getAvailablePlayerPosition(); // find the available player index

    if (availablePosition == -1) {
        return;
    }

    holder.setPlayerPosition(availablePosition);
    holder.setPlayerToPlayerView(mPlayerController.startUsingPlayer(availablePosition)); // get the player instance from list

	if (shouldPreparePlayer) {
        holder.parseDashManifest(holder.getFeed()); // parse dash manifest and prepare
    }

	decideWhichAttachedPlayerToPlay(); // provided below
}
```

```java
public void decideWhichAttachedPlayerToPlay() {
	if (mAttachedViewHolderList.isEmpty()) {
		return;
	}

	Collections.sort(mAttachedViewHolderList, new Comparator<FeedViewHolder>() {
		@Override
		public int compare(FeedViewHolder viewHolder1, FeedViewHolder viewHolder2) {
			return -(getVisibilityPercents(viewHolder1.getRootView()) -
                    getVisibilityPercents(viewHolder2.getRootView()));
		}
	});

    // play the most visible view holder
    FeedViewHolder mostVisibleViewHolder = mAttachedViewHolderList.get(0);
    mPlayerController.resumePlayer(mostVisibleViewHolder.getPlayerPosition()) // call player.setPlayWhenReady(true);

    // pause other players
	for (int i = 1; i < mAttachedViewHolderList.size(); i++) {
		FeedViewHolder otherViewHolder = mAttachedViewHolderList.get(i);
		mPlayerController.pausePlayer(otherViewHolder.getPlayerPosition()); // call player.setPlayWhenReady(false);
	}
}
```

When the view holder is scrolled off the screen, the callback `RecyclerView.onViewDetachedFromWindow(FeedViewHolder holder)` is called, we perform the following tasks:

1. Remove player listener and stop the player `Player.stop()`
2. Make this player be available in player list
![feed1](https://user-images.githubusercontent.com/3387462/36625629-3c931640-195e-11e8-871b-168ac1e4651a.png)


```java
@Override
public void onViewDetachedFromWindow(FeedViewHolder holder) {
	super.onViewDetachedFromWindow(holder);

    mAttachedViewHolderList.remove(holder);
	mPlayerController.stopUsingPlayer(holder.getPlayerPosition());
    holder.setPlayerPosition(-1);
    holder.setPlayerToPlayerView(null);
}
```

## Problem
After the user scrolls faster or fling for a period of time, the player will send multiple duplicate requests (*.mp4 and *.m4s) when replaying (not happen every time, but frequently). We've tested the case of setting repeat mode to off, the problem will be gone. We change the way of repeat to use `player.seekTo(0);` according to [stackoverflow answer](https://stackoverflow.com/questions/32005855/how-to-restart-video-on-exoplayer-after-exoplayer-state-ended), the problem is still there.

If the user scroll fast enought, the player will stop, return to the list from previous view holder, and be used by the next view holder, prepare the different media source immediately. The following diagram shows that the play in _VH0_ stops, and prepare in _VH3_ immediately when fast scrolling.
![feed3](https://user-images.githubusercontent.com/3387462/36625769-de9adf84-1960-11e8-9e3c-72c0b743c9d6.png)



Is there any problem of the way we use the player list? We assume that `Player.stop()` is asynchrous operations and will not stop immediately, but we use the same player to prepare different media source right away, that caused this problem. Or in our case, how can we stop preparing correctly?

Thanks again for your help.

**Comment by genxstylez** [comment]
@AquilesCanta We continue to find problems stated above, can you help out? Thanks :)

**Comment by AquilesCanta** [comment]
Hi, I honestly appreciate the effort put in the issue description. But it is still not clear to me yet is why this is an ExoPlayer problem. Also, I am not sure how the OkHttp cache problem mentioned above is actually related.

> After the user scrolls faster or fling for a period of time, the player will send multiple duplicate requests 

Which player? A single player is sending multiple requests for the same chunk? Is it possible that more than one player is being prepared with the same media? Or alternatively that the same player is receiving multiple consecutive prepare calls for the same media? It should be easy to answer this questions by logging prepare and stop calls. Also, if the player list contains a single player, is the issue reproducible?

> We change the way of repeat to use player.seekTo(0); according to stackoverflow answer, the problem is still there.

Repeat modes are the way to go for this behavior, but that approach should work as well. If it doesn't, please open an issue explaining actual and expected behavior.
