### ISSUE TITLE
Reason for buildDataSourceFactory in DemoApplication?

### ISSUE THREAD

**Issue by clhols** [google/ExoPlayer#3827]
In PlayerActivity there is a reference to DemoApplication where buildDataSourceFactory and buildHttpDataSourceFactory is implemented. Is there a reason for this?

If these two methods in PlayerActivity instead contained the default implementation and was protected, then the consuming app could extend PlayerActivity and override the two methods instead of modifying the Application class.

That would also make updates easier when an app wants to use a newer ExoPlayer version.

What do you think?

**Comment by AquilesCanta** [comment]
The reason behind this is that we have an internal implementation (and manifest) to override the used DataSource and add some small tweaks. Regarding marking them as protected, I don't think the demo app was conceived for being used as a dependency so I guess the straightforward approach would be downloading the source and modifying in-place, I am actually surprised it is not final. I will try to find any relevant historic reasons, but hopefully this answers your question.

**Comment by clhols** [comment]
I am not using the demo app as a dependency, but copied PlayerActivity and modified it. But I don't want PlayerActivity to ref the Application class in my app, so I have changed that. But when you release a new version of ExoPlayer with a modified version of PlayerActivity I either have to understand what has changed and merge it manually or I could extend PlayerActivity and have easier merges, but the private methods makes it a little harder.
