### ISSUE TITLE
Is Exoplayer available for IOS ?

### ISSUE THREAD

**Issue by satyres** [google/ExoPlayer#3836]
Hi , thank you for this awesome library.
is there a version for IOS please
Thank you

**Comment by tonihei** [comment]
I'm afraid that's not something we support. iOS libraries need to be written in Objective-C and that's why our Java library can't be ported easily even if we were to replace all platform specific calls.

**Comment by satyres** [comment]
@tonihei  :+1:  thank you so much for your answer.
i hope there will be a version for IOS in the futur . it would be really nice.
Best regards

**Comment by tonihei** [comment]
Closing because question was answered.
