### ISSUE TITLE
Stack at buffering state when video ends and start again from udp stream

### ISSUE THREAD

**Issue by damaniosif** [google/ExoPlayer#3840]
Hi,
I try to play a udp stream with android using exoplayer. Stream plays well until the end of the video ans then it stacks to buffering state for about 30 seconds and then continues to play the stream. What could be cause this error or how i can solve this.

Thank you

**Comment by tonihei** [comment]
Can you please provide the information requested in the [issue template](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE) for us to take a look? Especially a link to the media you're trying to play would be helpful to investigate why you are seeing this error.

**Comment by ojw28** [comment]
Closing due to lack of information.
