### ISSUE TITLE
Video with HD audio (e.g. TrueHD) stuck buffering after seek

### ISSUE THREAD

**Issue by ebr11** [google/ExoPlayer#3845]
### Issue description
The player will get stuck in the "Buffering" state after SimpleExoPlayer.seekTo().  This appears to be somehow related to the HD audio as switching the very same video item to a normal (AC3) audio track will no longer reproduce the problem.

The problem isn't 100% consistent but a few seeks will almost always "stick" the player and it will sometimes "unstick" if you seek several more times.

### Reproduction steps
Play content with a TrueHD audio track such that it plays directly via the MatroskaExtractor and issue a few seekTo() commands.  The player will enter the buffering state and never get to ready again even though the frame on-screen updates to the proper frame.

### Link to test content
Samples are extremely large.  Can try to provide upon request

### Version of ExoPlayer being used
2.6.1 Dev-v2 branch (as of 2/13/18). 

### Device(s) and version(s) of Android being used
Reproduced on NVidia Shield TV Android 7.0 Shield experience 6.3.

### A full bug report captured from the device
Can attempt to produce upon request.

**Comment by andrewlewis** [comment]
Please could you provide a clip from the test content (enough so that we can reproduce the issue in the demo app)? Thanks.

**Comment by ebr11** [comment]
Link emailed.

Thanks!

**Comment by ebr11** [comment]
Hi.  Were you able to reproduce the problem with my link?

**Comment by ebr11** [comment]
I have discovered this problem may not be limited to HD audio as I have now seen other items get stuck in this condition.

**Comment by ebr11** [comment]
Hi.  This issue is still labeled as "Need more info" but I did provide content that easily reproduces the problem.  Are you still waiting for more info?

Thanks.

**Comment by andrewlewis** [comment]
Haven't got round to looking at this yet, I'm afraid.

You mentioned that this is not limited to HD audio. Could you provide some sample media for that too?

**Comment by ebr11** [comment]
I can't provide any other media that will definitely reproduce the issue like the one I did.  For other media, it is much less likely and hard to predict but I have seen it occur.

It is very predictable with the media I provided though.  Only one or two skips and it is going to get stuck.

Thanks.

**Comment by andrewlewis** [comment]
This should be fixed on `dev-v2`. Please try it out and let us know if you still have problems.

**Comment by ebr11** [comment]
Yes!  Appears fixed.

Thanks very much.
