### ISSUE TITLE
Failed to handle provision response: DRM vendor-defined error: -2976

### ISSUE THREAD

**Issue by alexkombo** [google/ExoPlayer#3846]
I have an app in production that plays dash audio with Widevine DRM protection. I've received numerous crash reports from devices that are unable to play the content with the following error:
**Fatal Exception: android.media.MediaDrm$MediaDrmStateException
Failed to handle provision response: DRM vendor-defined error: -2976**

Version of ExoPlayer being used
2.5.4

Device(s) and version(s) of Android being used
Android versions 5 and 6
Devices: Tecno C9S, C7, C8, C9, C5S, L8, L7 Plus, L8 Lite, N8S, N6S, W5 Lite, W3, J5 

I don't have the entire log; this is what's I've received from Firebase and Fabric:
```
android.media.MediaDrm.provideProvisionResponseNative (MediaDrm.java)
android.media.MediaDrm.provideProvisionResponse (MediaDrm.java:900)
com.google.android.exoplayer2.drm.FrameworkMediaDrm.provideProvisionResponse (FrameworkMediaDrm.java:127)
com.google.android.exoplayer2.drm.DefaultDrmSessionManager.onProvisionResponse (DefaultDrmSessionManager.java:468)
com.google.android.exoplayer2.drm.DefaultDrmSessionManager.access$100 (DefaultDrmSessionManager.java:51)
com.google.android.exoplayer2.drm.DefaultDrmSessionManager$PostResponseHandler.handleMessage (DefaultDrmSessionManager.java:682)
android.os.Handler.dispatchMessage (Handler.java:111)
android.os.Looper.loop (Looper.java:207)
android.os.HandlerThread.run (HandlerThread.java:61)
```
It seems like the issue is mostly isolated to Tecno devices although I've also had some cases in Infinix devices. I do my tests with the Tecno Phantom 6s running Android 6 and so far haven't encountered any problem. 

I would really love to find a solution to this problem since a large number of my user base uses Tecno devices.

**Comment by tonihei** [comment]
Sounds like an device-specific Widevine problem. I think it would be helpful if you can get hold on a full bugreport to simplify the debugging. 

@wvpaf Can you take a look?

**Comment by giladna** [comment]
@tonihei 
@ojw28 

Think it can be great if ExoPlayer can add DeviceCapailities check for DRM  Supported devices

We have done such a thing 

you can look at:

https://github.com/kaltura/playkit-android/blob/develop/playkit/src/main/java/com/kaltura/playkit/player/MediaSupport.java

the code is open source
```
   MediaSupport.initializeDrm(this, new MediaSupport.DrmInitCallback() {
            @Override
            public void onDrmInitComplete(Set<PKDrmParams.Scheme> supportedDrmSchemes, boolean provisionPerformed, Exception provisionError) {
                if (provisionPerformed) {
                    if (provisionError != null) {
                        Log.e("TAG", "DRM Provisioning failed", provisionError);
                    } else {
                        Log.d("TAG", "DRM Provisioning succeeded");
                    }
                }
                Log.d("TAG", "DRM initialized; supported: " + supportedDrmSchemes);

                // Now it's safe to look at `supportedDrmSchemes`

                if (supportedDrmSchemes.contains(PKDrmParams.Scheme.WidevineCENC)) {
                    Log.d("TAG", "DEVICE SUPPORTS WIDVINE MODULAR");
                }
                if (supportedDrmSchemes.contains(PKDrmParams.Scheme.WidevineClassic)) {
                    Log.d("TAG", "DEVICE SUPPORTS WIDVINE CLASSIC");
                }
            }
        });
```

**Comment by tonihei** [comment]
@giladna Did you have a look at [`DrmSessionManager.canAcquireSession`](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/drm/DrmSessionManager.java#L36)and its [default implementation](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/drm/DefaultDrmSessionManager.java#L350)?

**Comment by giladna** [comment]
@tonihei
Thanks!

The solution I suggest is static what makes it good for  launch time to get the device capabilty and the ability to decide if video playback in app can work from the first place on it or a specific feature

**Comment by wvpaf** [comment]
Hi @alexkombo the error indicates the device is having issue writing to the file system.
Any chance of getting an ADB Bugreport? 

Also if you are asking for more/better functionality from exoplayer please create a new case so we can keep bugs and features separate.

thanks.

**Comment by alexkombo** [comment]
I did some tests with one of the devices that exhibited the error and all i get now is this:

```
Fatal Exception: android.media.MediaDrm$MediaDrmStateException: Failed to handle provision response: General DRM error
       at android.media.MediaDrm.provideProvisionResponseNative(MediaDrm.java)
       at android.media.MediaDrm.provideProvisionResponse(MediaDrm.java:540)
       at com.google.android.exoplayer2.drm.FrameworkMediaDrm.provideProvisionResponse(FrameworkMediaDrm.java:127)
       at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.onProvisionResponse(DefaultDrmSessionManager.java:468)
       at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.access$100(DefaultDrmSessionManager.java:51)
       at com.google.android.exoplayer2.drm.DefaultDrmSessionManager$PostResponseHandler.handleMessage(DefaultDrmSessionManager.java:682)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:194)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by wvpaf** [comment]
@alexkombo any luck with an ADB Bugreport? that would be most helpful.

**Comment by wvpaf** [comment]
closing due to no response. please reopen if you are able to provide the information a full ADB bugreport.

**Comment by giladna** [comment]
@alexkombo

try installing Kaltura Device Info from play store

you can do there provisioning action that may fix it (else need to do factory reset :( )

and you can also see in the report if it helped or you still getting Exception
