### ISSUE TITLE
Exoplayer Input

### ISSUE THREAD

**Issue by spaul13** [google/ExoPlayer#3849]
I just want to know what exactly decoder takes as input only the I/P/B frames?

What I have seen exoplayer takes the videofile as input but while decoding using avcodec_decode, it takes a single frame to decode and then display. Am I correct?

Considering an encoded video stream, Can anyone please explain to me how an incoming P frame's dependency on I frame defined in the exoplayer module?

**Comment by tonihei** [comment]
This is handled by the decoder internally based on the order in which it receives the data. ExoPlayer just enqueues the input data to the encoder and then retrieves the decoded data in the output buffer (which is then used by the renderer to display the frame).

**Comment by spaul13** [comment]
Thanks a lot for the reply. so we are giving a complete video file as input to the player. One little query remaining.

Suppose for a particular seek_position in the video playback, if it's a B frame then for decoder it requires the I and P frames to be decoded. Then exoplayer enqueues the B frame along with the I and P frames on which B frame is dependent to the decoder?

**Comment by tonihei** [comment]
Yes, it does. When seeking, the decoder receives data from the last sync point (i.e. the last I frame), but we only use the decoded output from the seek position to prevent displaying data from before the requested position.

**Comment by spaul13** [comment]
@tonihei, can you please tell me what exactly the **last sync point** is? 
Did you want to imply the last time-stamped frame? But then why the last time-stamped frame be an I frame?

why only **last  I frame** it requires, it can be last I along with the previous P's on which the particular P frame is dependent on?

**Comment by tonihei** [comment]
Yes, that is what I was trying to say: Whenever we seek to a position, we start decoding from the last I frame (which I called sync point), decode all the following dependent frames until the position we actually seeked to.

Aside: We recently added s[eek parameters](https://github.com/google/ExoPlayer/blob/dev-v2/library/core/src/main/java/com/google/android/exoplayer2/ExoPlayer.java#L243) allowing you to customize this behavior. For example, you can choose to always seek to the previous I frame / sync point to speed up seeking for the user. This is currently only part of the dev-branch but will be added to a future release.

**Comment by spaul13** [comment]
But suppose if I recently decoded the position, it should be in the decoder memory.
Suppose I have a **I1P2P3P4 I2P5P6P7** (I and P frames) suppose I just decoded P4 and then I enter into the next GOP and decode P7 from I2. If I again need frame_id P4 corresponding to I1 what I need to do start from I1? Although I have the decoded frame 4 for P4 in the memory stored. 

Can u please tell me what decoder will do here?

**Comment by tonihei** [comment]
We will indeed start decoding again from I1. In most cases, playback will just continue forward and thus it would be very wasteful to keep the decoded frames.

**Comment by spaul13** [comment]
Just have a query in mind, does ijkplayer also do in the same fashion starting from I1 similarly like exoplayer?

can u tell me how to define the video buffer size for the decoder here?

**Comment by tonihei** [comment]
I'd suggest asking questions about ijkplayer on their page (looks like you already did that).

For detailed implementation questions, please also look at our code. This issue tracker is mostly for answering questions about how to use ExoPlayer. For general video playback questions, you are probably better off using Stackoverflow.
