### ISSUE TITLE
Consider allowing seeking before renderers prepared

### ISSUE THREAD

**Issue by IanDBird** [google/ExoPlayer#385]
I have a scenario where i'm trying to resume playback of a video using HLS. The HLS segments are created on the fly, rather than being prepared and simply available. The problem I have is that at the moment, I need to generate the first HLS segment so that I can then seek to the required offset. This is very inefficient, since starting to re-encode video at a new offset is an expensive operation.

Ideally, i'd like to be able to tell ExoPlayer the offset that i'm wanting to start playback from, and it would initially request the correct Chunk. As a temporary workaround, i've made the following addition to `HlsSampleSource` although I recognise it's not ideal:

```java
  public void setInitialPositionUs(long positionUs) {
    Assertions.checkState(prepared == false);
    downstreamPositionUs = positionUs;
    pendingResetPositionUs = positionUs;
  }
```

This is called in my `HlsRendererBuilder` and therefore when preparing, it will request the potentially non-zero initial chunk.

Is there any interest in supporting this feature?

**Comment by ojw28** [comment]
You should already be able to call ExoPlayer.seekTo before ExoPlayer.prepare. Does it not work?

**Comment by IanDBird** [comment]
I've had this working for DASH, but not for HLS. It appears that HLS will only start playback after the first chunk has been received, even if i've asked it to seek.

**Comment by IanDBird** [comment]
I think the issue is that `ExoPlayerImplInteranl`'s `incrementalPrepareInternal` requires the track renderers to complete "preparing" before it begins playback. If you follow this, this means that the `MediaCodecTrackRenderer` call's it's Sources `source.prepare();` My understanding from reading `HlsSampleSource`'s prepare method is that it wont complete until it's read a chunk. So since it's not been told about the seek, it's attempting to grab the first chunk. If this isn't available, it will never complete. Hence why my hack is working around it by shifting which chunk it attempts to initially load when preparing.

**Comment by ojw28** [comment]
Yeah, I see. So calling seekTo before prepare does work (i.e. the end result is playback starts from the position you're trying to start from). It's just that preparation fetches the first part of the first chunk, where-as it should be possible to prepare using the chunk you're actually trying to start playback from.

**Comment by IanDBird** [comment]
Yes, exactly. The problem for my specific scenario is that I don't have the first chunk.

**Comment by ojw28** [comment]
Yeah. Although even without in that scenario, it's wasteful in that we're downloading more than is necessary. The "proper" fix is to have the pending seek position propagated through prepare(). Touches quite a lot of files though, since it needs a change to both the TrackRenderer and SampleSource interfaces.

I think we'll try and get to this at some point fairly soon, but it's not massively high priority.

**Comment by ojw28** [comment]
I think I have a fix for this.

**Comment by dnutcracker** [comment]
Is calling seekTo before calling prepare+play is now a more recommended way of starting a player? Does it also improve the startup time of a player? (as in time it takes to render that 1st frame)

**Comment by ojw28** [comment]
It's always been best to call seekTo as early as possible. The change referenced above decreases start-up latency specifically in the HLS case where not starting from t=0. For other scenarios (e.g. DASH / SmoothStreaming / Anything else) performance is unchanged.
