### ISSUE TITLE
ffmpeg extension

### ISSUE THREAD

**Issue by HennessyTennessy** [google/ExoPlayer#3852]
Hi!
I am trying to add ffmpeg extension to my own ExoPlayer Project, but it seriously so hard to understand that "FFmpeg extension's Build instructions" for me...
For now I have Simple Android Project with this dependencies:
>     compile 'com.google.android.exoplayer:exoplayer:r2.4.0'
>     compile 'com.google.android.exoplayer:exoplayer-core:r2.4.0'
>     compile 'com.google.android.exoplayer:exoplayer-dash:r2.4.0'
>     compile 'com.google.android.exoplayer:exoplayer-hls:r2.4.0'
>     compile 'com.google.android.exoplayer:exoplayer-smoothstreaming:r2.4.0'
>     compile 'com.google.android.exoplayer:exoplayer-ui:r2.4.0'

MainActivity class:

> BandwidthMeter bandwidthMeter = new DefaultBandwidthMeter();
>             TrackSelector trackSelector = new DefaultTrackSelector(new AdaptiveTrackSelection.Factory(bandwidthMeter));
>             exoPlayer = ExoPlayerFactory.newSimpleInstance(this, trackSelector);
>             Uri videoURI = Uri.parse(videoURL);
>             DefaultDataSourceFactory dataSourceFactory = new DefaultDataSourceFactory(this, "exoplayer_video");
>             ExtractorsFactory extractorsFactory = new DefaultExtractorsFactory();
>             MediaSource mediaSource = new ExtractorMediaSource(videoURI, dataSourceFactory, extractorsFactory, null, null);
>             exoPlayerView.setPlayer(exoPlayer);
>             exoPlayer.prepare(mediaSource);
>             exoPlayer.setPlayWhenReady(true);

I know, that the extension is not provided via JCenter, and try to add this library to my Project,
but I dont understand absolutly how to build the extension's native components. All, what I can is this: setting following environment variables:(screenshot->>) [https://ibb.co/jgLuRS](url) (and I'm not sure this is the correct).
Have I a simple way to use ffmpeg in my App with ExoPlayer??

**Comment by tonihei** [comment]
Judging the screenshot, it seems you're trying to build the ffmpeg extension on Windows. Please correct me if I'm wrong here.

The instructions in our readme apply to Linux-based operating systems. As we are not officially supporting a Windows build, I unfortunately can't verify if and how the build works on there. Please also have a look at #3127 where this has been discussed.

Also, the `cd "<path to exoplayer checkout>"` in the readme does not mean you should set an environment variable named `cd` to the path, but it's rather the command to change the current directory in the console. The required environment variables follow down below (`EXOPLAYER_ROOT` and `FFMPEG_EXT_PATH`)

**Comment by HennessyTennessy** [comment]
Hmm, ok. Thx for quick answer! But I think I need more help)
Yes, i did it on Windows. I read #3127, but dont understand why i should to use Powershell, when i can setup environment variable in Computer properties, or i did someting wrong...
Also, I am very new in NDK development, but know how to assembler release in Android Studio. Now, i have this file: extension-ffmpeg-release.aar. As i undertand, it's native part of the extension, which nesessary for work with this extansion.
If i did wright, how can i use that file in my own AndroidProject? How can I add that extension-ffmpeg-release.aar, as library, to my own ExoPlayer?
P.S. When grandle built .aar, it noticed me:
```
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```
...and
```
Note: D:\AndroidDeveloper\AndroidStudioProjects\ExoPlayer2\ExoPlayer-release-v2\extensions\ima\src\main\java\com\google\android\exoplayer2\ext\ima\ImaAdsLoader.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```
...and
```
Note: there were 11 duplicate class definitions.
```
It will be a problem, when i will use this .aar??

**Comment by tonihei** [comment]
The deprecated API warnings are harmless. And the duplicated class definitions may also not be a problem. Did you test actually using the extension to play a ffmpeg audio file?

As I said, I can't verify how the build works on Windows. So it may be true that setting the environment variables in the Computer properties is enough to compile the ffmpeg library.

**Comment by HennessyTennessy** [comment]
I tried to test it, but not sure, that i did it right)
I copied and included that file (extension-ffmpeg-release.aar) as library, to my own project
```
dependencies {
...........
implementation files('libs/extension-ffmpeg-release.aar')
}
```
Then I edit code:
```
exoPlayer = ExoPlayerFactory.newSimpleInstance(this, trackSelector);
```
changed to:
```
RenderersFactory renderersFactory=new
DefaultRenderersFactory(this,null,EXTENSION_RENDERER_MODE_ON);
exoPlayer = ExoPlayerFactory.newSimpleInstance(renderersFactory,trackSelector);
```
Now my app **cant** play any films. Btw, without library app works good. Should i create .jar? May be it will be better than .aar?

**Comment by tonihei** [comment]
It's probably best to follow the build instructions in the ffmpeg readme file using either a Powershell or the WSL as proposed in #3127.   

If the extension loaded successfully you should see a "Loaded FfmpegAudioRenderer" in the logcat.

**Comment by AquilesCanta** [comment]
An easy way to know whether .so/.a's (depends on the linking being used) are being correctly bundled in your apk is to check whether FfmpegLibrary.isAvailable() is returning true. If it returns false, it means that your apk does not have the native objects bundled in. Which in turn means you have not successfully compiled the native part.

At the end of the compilation process, all objects should appear under extensions/ffmpeg/src/main/libs. So, having an .aar does not necessarily mean that you have successfully built the ffmpeg extension. Hope this helps!

**Comment by HennessyTennessy** [comment]
I understood that u work on Linux, but say me pls is Android Studio on Linux diferent from Android Studio on Windows? I really dont know=/ If its not, whats happend if u build ffmpeg-extansion through Android Studio on Linux by Gradle?(screenshot ->) https://ibb.co/bGZUbS
Btw, i heard AquilesCanta, and tried to **build** this extansion (not create .aar file). But Gradle build finished with 1 error and noticed me to read library/core/buildout/reports/tests/testDebugUnitTest/index.html
I found this:
Failed tests: AtomicFileTest.testWriteRead
Ignored tests: CacheDataSourceTest.disabledTestCacheAndReadUnboundedRequestUnknownLength
What that means?
P.S. I dont know how use PowerSell and its impossible to instal WSL for me.
I checked FfmpegLibrary.isAvailable(), its return false

**Comment by tonihei** [comment]
It sounds as if the build of the native libraries never succeeded. Were you able to follow to build instructions in the readme file? And if yes how far? You need to do this in order to build the native code which can be used by the library later on.

**Comment by HennessyTennessy** [comment]
I cant follow build instruction in the redmi file, because I failed with WSL installation, and dont want to install Ubuntu or something only for build ffmpeg(( 
I saw #3127, and didnt find any simple info for NDK building....

**Comment by tonihei** [comment]
I'd suggest to ask general NDK building questions on Stackoverflow or similar sites as this is beyond the scope of this issue tracker. You might also be able to ask @Crossady who seemed to have managed to build the extensions on Windows (#3127).
