### ISSUE TITLE
frame_id to particular bytes in video file mapping

### ISSUE THREAD

**Issue by spaul13** [google/ExoPlayer#3855]
If I have the frame-id, I have seen I can convert it to a milisec scale, from where I have to start searching in the video file. probably (1000*frame_id)/64 will be the seek_position in the video file. what will be then the duration for seeking the frame? Can anyone please tell me is it true?

**I want to know how can I map the frame_id which I want to get from the video file to the bytes need to be fetched from the video file (starting byte and the total number of bytes need to fetch for that particular frame)?**

How exoplayer is doing that? Can anyone please tell me?

**Comment by tonihei** [comment]
Could you be more specific of what type of video file you are talking about?

Depending on the type, our Extractors have this mapping internally. For example, the Mp4Extractor keep a table of timestamps, bytes offsets and sizes [here](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/extractor/mp4/TrackSampleTable.java). However, this data is usually not published externally. Can you give some details on what you are trying to achieve? Maybe there is another way of doing this.

**Comment by spaul13** [comment]
Thanks for the reply. Its an H.264 encoded MP4 file consists of I and P frames.

Suppose from the users' position, I calculate the frame_id needed to fetch, if my video stored in somewhere else. I need to fetch the bytes corresponding to the video store it on my android, then I call the Exoplayer.  For that reason, I want to know how that **mapping between frame_id and specific byte range [a,b] in the video file can be done.**

Let's assume, where a is the starting offset in the video file and b is the ending offset or (b-a) bytes will be the size of the read buffer.

and these **a and b also corresponds to some timestamp in the video file.** I also want to know that how to calculate those. Please ask for any further details.

One thing also this mapping will vary for the different encoding scheme or only dependent on the video file format?
[N.B. different encoding schemes imply H.264, H.265, VP9 for example]

**Comment by tonihei** [comment]
"if my video stored in somewhere else" - ExoPlayer allows you to specify various data sources to read from a file. Where is the file stored that you can't just load it as it is and seek to expected position? You also need to read the file to find the byte position of the frames, so there seems to be no way around this.

**Comment by spaul13** [comment]
can you tell me how exoplayer fetches bytes from a TCP server as required (on-demand) and decode and display after converting into a frame-texture? 
Actually, my video file is stored on the server and I have a simple TCP server code running on the server machine. All I need to do, fetch the video bytes as required as display it.

Can you (@tonihei ) please tell me how this can be achieved by specifying the path (where and how)?

**Comment by tonihei** [comment]
Please have a look at our [developer guide](http://google.github.io/ExoPlayer/guide.html) for the steps to setup a player and load media. You can also check our [demo app](https://github.com/google/ExoPlayer/blob/release-v2/demos/main/src/main/java/com/google/android/exoplayer2/demo/PlayerActivity.java#L365). ExoPlayer takes care of all the server connections, which exact bytes to fetch, how to decode them and how to display them to a texture. You shouldn't need to bother unless you're writing custom components for special use cases.
