### ISSUE TITLE
How to get advert duration and position?

### ISSUE THREAD

**Issue by pwiniars** [google/ExoPlayer#3857]
How can I get position of playing advert and it's total duration? I've set an AdEventListener and I need to send some analytics inside CONTENT_RESUME_REQUEST event. If there's no such possibility, could you consider adding such a feature?

ExoPlayer 2.6.1

**Comment by andrewlewis** [comment]
Please see #3322.

That should provide a way to handle ad events. We can also consider providing an easier to use callback for ad-related events but it probably won't happen for a while.
