### ISSUE TITLE
what is extension in exo demo app github project...and how can it work

### ISSUE THREAD

**Issue by abvaalgit** [google/ExoPlayer#3858]

**Comment by ojw28** [comment]
ExoPlayer extensions are additional components, most of which have dependencies on external libraries. For example the OkHttp extension has a dependency on the OkHttp library, and allows you to use that network stack to request the media played by ExoPlayer.

Each extension has its own README file that gives instructions on how to use it, for example the OkHttp one [here](https://github.com/google/ExoPlayer/tree/release-v2/extensions/okhttp).
