### ISSUE TITLE
Unexpected delay in fetching manifests

### ISSUE THREAD

**Issue by IanDBird** [google/ExoPlayer#386]
Branch: `dev`
Device: `Google Nexus Player`

I'm looking into a delay when playing some videos, and it appears that it's caused by an extermely slow request to fetch the manifest. My initial thought was that the server was taking far too long to respond. However, after looking through the server logs, and using Curl to manually hit the server, it's taking roughly 200-300ms to respond which doesn't explain why the manifest fetcher is taking over 8 seconds. After adding in lots of logging, i've found the following code to be the cause of the 8 second delay (in `DefaultHttpDataSource`):

```java
    // Check for a valid response code.
    int responseCode;
    try {
      Log.i("[IABI]", "getting response");
      responseCode = connection.getResponseCode();
      Log.i("[IABI]", "got response");
    } catch (IOException e) {
      throw new HttpDataSourceException("Unable to connect to " + dataSpec.uri.toString(), e,
          dataSpec);
    }
```

This seems to suggest that the network request is taking a long time to succeed. I hadn't noticed this issue on any other requests to the same server, so I decided to add my own AsyncTask which is executed on a separate scheduler to hit the server with the same URL. My own AsyncTask is completing the network request in 200-300ms, but the one used by the `DefaultHttpDataSource` continues to block.

Any thoughts on what might be the cause of this? I initially considered that it might be some type of connection caching issue, but subsequently added in a random UUID into the URL to make sure it changed between requests. This unfortunately did not resolve the issue

**Comment by ojw28** [comment]
Is this the initial manifest fetch (i.e. in the context of the demo app, is it equivalent to the fetch performed by DashRendererBuilder)? Does it happen if you attempt to play using the demo app, or only in the context of your own app?

We definitely haven't seen this as a widespread issue (otherwise all videos would take ~8s to start, which isn't something people are observing).

**Comment by IanDBird** [comment]
Yeah, it's the initial manifest fetch (e.g. the master HLS playlist). A number of the developers investigating the issue have all managed to reproduce it within the context of our application, and are struggling to identify the route cause. 

I'll confirm that whether it happens in the sample app, but as you suggest, I bet it doesn't. We've tried to test a number of things to see if we can identify the bottleneck, network, cpu, etc but nothing obvious has been found. I thought i'd raise this GHI to see if anyone else had experienced similar issues. As I mentioned, all of our own networking requests are being handled really responsive, it's just this one request done via the `Loader` that seems to be causing issues.

I'll update the ticket as I find out more, and retest the sample app.

**Comment by IanDBird** [comment]
I've tried to reproduce this issue in the sample application, and failed. I'm closing this as it's pointing to an issue in our own application. I've managed to make a workaround for it, but it still remains unclear what the root cause of the issue actually is.
