### ISSUE TITLE
Exo Player is can use chromecast??

### ISSUE THREAD

**Issue by DeevD** [google/ExoPlayer#3861]
Can i use chromecast in exo player for android??

**Comment by andrewlewis** [comment]
@AquilesCanta has been working on a cast extension that makes it easier to use the Cast SDK with ExoPlayer. You can have a look at the code on [the development branch](https://github.com/google/ExoPlayer/tree/dev-v2/extensions/cast) now. This will likely be included in the next release, at which point there will also be a post on our [blog](https://medium.com/google-exoplayer) describing how to use it.

**Comment by DeevD** [comment]
Thank you bro I love it :D
