### ISSUE TITLE
Rotating Exoplayer

### ISSUE THREAD

**Issue by AlirezaGhanbarinia** [google/ExoPlayer#3862]
I added exoplayer to my app.
I fixed the screen orientation to portrait for whole my app.
I need exoplayer to be rotated to landscape mode.

How can I handle this issue?
I just need to rotate the exo frame and not the whole fragment or activity.

**Comment by andrewlewis** [comment]
If the goal is to rotate the video output only, you could use a `TextureView` (e.g., by setting `app:surface_type="texture_view"` if you're using `SimpleExoPlayerView`) and set a transform matrix using [`setTransform`](https://developer.android.com/reference/android/view/TextureView.html#setTransform(android.graphics.Matrix)). If you're trying to do something different please elaborate. Thanks!
