### ISSUE TITLE
(dev-v2, 2.7.0 candidate?!) Player seems to buffer the resource even without calling start (first time setPlayWhenReady set to true).

### ISSUE THREAD

**Issue by eneim** [google/ExoPlayer#3864]
I tried latest dev-v2 and notice the following log shown in console:

```
onPlayerStateChanged() called with: playWhenReady = [false], playbackState = [2]
MyPlayer#play() <-- Client call, it will call Player#setPlayWhenReady with 'true'
onPlayerStateChanged() called with: playWhenReady = [true], playbackState = [2]
onPlayerStateChanged() called with: playWhenReady = [true], playbackState = [3]
```

When trying to comment out the MyPlayer#play(), the log is as below

```
onPlayerStateChanged() called with: playWhenReady = [false], playbackState = [2]
MyPlayer#play() <-- client call, just do nothing (Player#setPlayWhenReady is commented out)
onPlayerStateChanged() called with: playWhenReady = [false], playbackState = [3]
```

So we can see that the player will also be ready to play even the Client doesn't request to.

I suppose that Player will start buffering only when Player#setPlayWhenReady is called with 'true' (for at least once). I also doesn't see this on 2.6.1. Can someone enlighten me this change?

**Comment by ojw28** [comment]
ExoPlayer has always behaved this way. Buffering starts as soon as you call `prepare`. It's never been the case that `setPlayWhenReady(true)` is required for buffering to start.
