### ISSUE TITLE
ImaAdsLoader doesn't work with HLS content that uses EXT-X-PROGRAM-DATE-TIME

### ISSUE THREAD

**Issue by priscila225** [google/ExoPlayer#3865]
I'm running the demo app for v2.6.1 and I hardcoded it to play this HLS video:  https://content.uplynk.com/babd2bd748ee47c48e0fb6b492245eb9.m3u8

I'm trying to use this google sample vmap: "VMAP - Pre-roll Single Ad, Mid-roll Standard Pod with 3 ads, Post-roll Single Ad"

When the playback starts I see that the prerolls doesn't play, instead I get the 3 midrolls where the preroll should be. Also I can't see the post-roll ad working, it just keeps loading forever.

**Comment by andrewlewis** [comment]
The content media source has a window that is offset from zero, while the ad group times start from zero. This is not handled correctly in `Timeline` at the moment, which leads to the player identifying the wrong ad group to play.

We have a fix in review which will treat ad group times as relative to the window in `Timeline` (`ImaAdsLoader` already makes this assumption), so hopefully this will be fixed on the development branch soon.

**Comment by ojw28** [comment]
I think the new plan is to adjust `HlsMediaSource` so that the Timeline window and period are aligned for this type of media.

**Comment by priscila225** [comment]
@andrewlewis @ojw28 sounds good, let me know when you have a fix on HlsMediaSource to test it. Thank you!

**Comment by andrewlewis** [comment]
@priscila225 This should be fixed on the development branch. Please try it out and let us know if there are any further issues.

**Comment by priscila225** [comment]
@andrewlewis this is working fine for us. Thank you a lot! I confirmed using the sample with m3u8 links as well. Also the plan to have it on release, you have a date?

Just to know if we will wait too much to have the fix on final release.
I'll work for now with dev version! awesome

Thank you!

**Comment by ojw28** [comment]
The fix will land in 2.7.1 which will likely be released this week or early next week.
