### ISSUE TITLE
HLS Trickplay EXT-X-I-FRAME-STREAM-INF

### ISSUE THREAD

**Issue by kishan36** [google/ExoPlayer#3867]
I want get video frame image from HLS stream url. But I don't know how to get EXT-X-I-FRAME-STREAM-INF from hls url. Also I didn't found any specific code for it.I want to seek using trickplay.

**Comment by andrewlewis** [comment]
#474 tracks adding support for HLS trick play but I don't think we're planning to implement this soon.
