### ISSUE TITLE
Weird Arabic/Persian Subtitles Symbols

### ISSUE THREAD

**Issue by tamimattafi** [google/ExoPlayer#3871]
Hello ! I'm trying to create a video player with **Subtitles**. Everything is set up and working correctly , except for one thing. My **Arabic** subtitles are not showing correctly as they should be. They look so weird with **symbols** and **stuff**.. Something like this : 

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/Y5UWK.jpg

**Here's my ExoPlayer Setup with subtiltes** : 

    Uri srt = Uri.parse("http://download1651.mediafire.com/titdvyxje25g/j5wpodffdhn005r/Thor+3+.WEB+%28NoColored%29.srt");
        
        Handler mainHandler = new Handler();
        BandwidthMeter bandwidthMeter = new DefaultBandwidthMeter();
        TrackSelection.Factory videoTrackSelectionFactory =
                new AdaptiveTrackSelection.Factory(bandwidthMeter);
        TrackSelector trackSelector =
                new DefaultTrackSelector(videoTrackSelectionFactory);
        player =
                ExoPlayerFactory.newSimpleInstance(this, trackSelector);
        DefaultBandwidthMeter bandwidthMeter2 = new DefaultBandwidthMeter();
        DataSource.Factory dataSourceFactory = new DefaultDataSourceFactory(this,
                Util.getUserAgent(this, "yourApplicationName"), bandwidthMeter2);
        Format textFormat = Format.createTextSampleFormat(null, MimeTypes.APPLICATION_SUBRIP,
                null, Format.NO_VALUE, Format.NO_VALUE, "ar", null, Format.OFFSET_SAMPLE_RELATIVE);
        MediaSource videoSource = new ExtractorMediaSource.Factory(dataSourceFactory)
                .createMediaSource(Uri.parse(getVideoUri()));
        MediaSource textMediaSource = new SingleSampleMediaSource.Factory(dataSourceFactory)
                .createMediaSource(srt, textFormat, C.TIME_UNSET);
        MediaSource mediaSource = new MergingMediaSource(videoSource, textMediaSource);

        player.prepare(mediaSource);

i literally looked for it everywhere, but i seem not to find anything that would help. So is there any solution on how can i fix that ?

**Comment by andrewlewis** [comment]
As #3869 has the SRT file linked let's continue to use that issue to track this.
