### ISSUE TITLE
Can't play video with .m3u8 for several devices

### ISSUE THREAD

**Issue by Aptyp630** [google/ExoPlayer#3873]
Hi.

1. I use Exo Player v1 in my app, and everything was good with playing video except last new devices with API 8.0 and higher. E.g. Sony XZ API 8.0, HTC U11. My file .m3u8 cannot play for those devices. There is only sound without picture. I've tried use Exo Player v2 passing my link with .m3u8 and there was the same issue for the same devices. Could you help me to understand what is it the problem?

**Comment by andrewlewis** [comment]
We can't help unless you provide information requested in the [issue template](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

Let's use this issue to track the m3u8/HLS issue in (1). Please file a separate issue for the MP4 seeking issue (2).

**Comment by ojw28** [comment]
Closing due to lack of information.
