### ISSUE TITLE
How to display ads of previous player

### ISSUE THREAD

**Issue by michelecorrea3** [google/ExoPlayer#3874]
Hi!

My app:
I have an app that consists of a screen with a list of players with ads. (I am using RecyclerView).
When the user scrolls the main screen and a video was playing, I display this video in a smaller player at the bottom of the screen (like youtube).

To display the smaller video, I create a new player and update it with content position of previous player.

My problem:
When the user scrolls and an ads is playing, when updating the new player with content position of previous player, the ads starts to play from the beginning and not from the position that it had stopped in the other player. (I am reusing AdsLoader and )

My question:
I would like to know if there is any way I can display ads from the position it stopped in previously player. 

Can someone help me, please?

Some code:

```
MediaSource mediaSource = buildMediaSource(Uri.parse(url));
String adTag = getAdsUrl();

 if (adTag != null) {
    if (!reuseAds) {
         releaseAdsLoader();
         mAdsLoader = new ImaAdsLoader(context, Uri.parse(adTag));
    }
    mediaSource = new AdsMediaSource(mediaSource, new AdsMediaSourceFactory(), mAdsLoader, playerView.getOverlayFrameLayout(), null, null);
}

player.seekTo(position);
player.setPlayWhenReady(true);

player.prepare(mediaSource,false,false);
```

**Comment by andrewlewis** [comment]
Are you definitely using exactly the same `ImaAdsLoader` instance when creating the `AdsMediaSource` that is played in the new player? It's also important that the old player is released before creating the new one. I think this should just work, as the situation is very similar to background/resuming a player while playing ads.

**Comment by michelecorrea3** [comment]
It was the same ImaAdsLoader, but I wasn't releasing the old player before creating the new one. I released and it worked! Thank you so much :)

**Comment by andrewlewis** [comment]
Glad to hear it works!
