### ISSUE TITLE
DefaultHttpDataSourceFactory RequestProperties does not allow setting "known" headers

### ISSUE THREAD

**Issue by b77x** [google/ExoPlayer#3878]
I found a method to change headers ExoPlayer sends using this code

```
DefaultHttpDataSourceFactory defaultHttpDataSourceFactory;
defaultHttpDataSourceFactory = new DefaultHttpDataSourceFactory("user_agent");
defaultHttpDataSourceFactory.getDefaultRequestProperties().set("header", "header");
MediaSource videoSource = new ExtractorMediaSource(uri, defaultHttpDataSourceFactory, extractorsFactory, null, null);
```
This works just fine, however using a header like "ACCEPT_LANGUAGE" does not change anything when sending the request. 

Why is this, and what can I do?

**Comment by ojw28** [comment]
Just to clarify, if you're specifying it as a string constant it should be "Accept-Language" rather than "ACCEPT_LANGUAGE", right?

**Comment by b77x** [comment]
That was the issue, thank you.
