### ISSUE TITLE
HLS: adaptive stream switching freezes player on GS3 Mini (Android 4.1.2)

### ISSUE THREAD

**Issue by justinddunlap** [google/ExoPlayer#388]
When playing an HLS stream via ExoPlayer on the Galaxy S3 Mini (Android 4.1.2), the player freezes as soon as adaptive streaming causes a stream switch. This occurs both with ADAPTIVE_MODE_SPLICE and ADAPTIVE_MODE_ABRUPT. With ADAPTIVE_MODE_NONE, since no stream switching occurs, HLS streams play perfectly. The following log entries seem to be associated with the freeze-up:

04-10 17:13:36.484    7383-7392/? E/ENSWrapper? return OMX_ErrorNotImplemented - GetExtensionIndex OMX.ST.VFM.H264Dec h=0x42e51ae8  cParameterName=OMX.google.android.index.useAndroidNativeBuffer2 IndexType=unknown OMX_INDEXTYPE [ 0x00000000 ]
04-10 17:13:36.484    7383-7392/? D/MMHWBuffer? Open (aComponent=0x42e51ae8, aIndex=0x7fff0002)
04-10 17:13:36.484    7383-7392/? D/MMHWBuffer? bHandle=0x42de4048 AddBufferInfo(aBufferIndex=0, aLogAddr=0x439d5000, aSize=1384448)
04-10 17:13:36.484    7383-7392/? V/OMXCodec? [OMX.ST.VFM.H264Dec] registered graphic buffer with ID 0x42e52438 (pointer = 0x42e4ec90)
04-10 17:13:36.484    7383-7392/? E/ENSWrapper? return OMX_ErrorNotImplemented - GetExtensionIndex OMX.ST.VFM.H264Dec h=0x42e51ae8  cParameterName=OMX.google.android.index.useAndroidNativeBuffer2 IndexType=unknown OMX_INDEXTYPE [ 0x00000020 ]
04-10 17:13:36.484    7383-7392/? D/MMHWBuffer? Open (aComponent=0x42e51ae8, aIndex=0x7fff0002)
04-10 17:13:36.484    7383-7392/? D/MMHWBuffer? bHandle=0x42de4048 AddBufferInfo(aBufferIndex=1, aLogAddr=0x449db000, aSize=1384448)
04-10 17:13:36.484    7383-7392/? V/OMXCodec? [OMX.ST.VFM.H264Dec] registered graphic buffer with ID 0x4427e6c0 (pointer = 0x42d0d920)
04-10 17:13:36.494    7383-7392/? E/ENSWrapper? return OMX_ErrorNotImplemented - GetExtensionIndex OMX.ST.VFM.H264Dec h=0x42e51ae8  cParameterName=OMX.google.android.index.useAndroidNativeBuffer2 IndexType=unknown OMX_INDEXTYPE [ 0x4009e54c ]
04-10 17:13:36.494    7383-7392/? D/MMHWBuffer? Open (aComponent=0x42e51ae8, aIndex=0x7fff0002)

**Comment by ojw28** [comment]
- Which stream, specifically? Does this occur with the test streams?
- Are you sure you're not just trying to play video that's too high of a resolution for the device to handle? I'm not sure what the limits of that device are off the top of my head, but the fact that it's screen is only 800px tall suggests that you shouldn't be attempting to play 1080p content, for example.

**Comment by justinddunlap** [comment]
With this test stream, the video eventually freezes up but the audio does not, and the app itself does not freeze: https://devimages.apple.com.edgekey.net/streaming/examples/bipbop_4x3/bipbop_4x3_variant.m3u8 

With the actual streams I will be using, sometimes only the video freezes, sometimes the video and audio freeze, and sometimes the entire application freezes. The master streams do contain 1080p variants, but I have no control over how the streams are defined so I cannot exclude high-res video. I will see if I can link to one here.

Is there a way I can filter out the high-res streams via ExoPlayer? I see that in HlsChunkSource.filterVariants(...), the streams are filtered to only those that have playable video, but to add onto that would require modifying ExoPlayer.

**Comment by ojw28** [comment]
There are two parts to this:

1. Where the manifest includes optional RESOLUTION tags, we should automatically filter those that are at resolutions beyond that supported by the device.
2. It's (in my opinion) a flaw in the HLS spec that RESOLUTION tags are optional. When they're not included (as is the case in the example you give) the task is significantly more complicated. I'm not sure what we'll do about that case, if anything. Can you require that RESOLUTION tags are always included in the manifests that you're using? What is your use case, exactly?

**Comment by justinddunlap** [comment]
As I said, I have no control over the stream definitions - this is third-party content. However, it does have RESOLUTION tags - for example:

```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:BANDWIDTH=1106493,RESOLUTION=640x360,CODECS="avc1.4d401e,mp4a.40.2"
800/gbe431500003_800k_640x360_h264_800_aac_128.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1556913,RESOLUTION=960x540,CODECS="avc1.4d401f,mp4a.40.2"
1200/gbe431500003_1200k_960x540_h264_1200_aac_128.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=2869123,RESOLUTION=960x540,CODECS="avc1.4d401f,mp4a.40.2"
2400/gbe431500003_2400k_960x540_h264_2400_aac_128.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=3747066,RESOLUTION=1280x720,CODECS="avc1.4d401f,mp4a.40.2"
3200/gbe431500003_3200k_1280x720_h264_3200_aac_128.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=4850400,RESOLUTION=1920x1080,CODECS="avc1.4d4028,mp4a.40.2"
4200/gbe431500003_4200k_1920x1080_h264_4200_aac_128.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=5968545,RESOLUTION=1920x1080,CODECS="avc1.4d4028,mp4a.40.2"
5200/gbe431500003_5200k_1920x1080_h264_5200_aac_128.m3u8
```

**Comment by ojw28** [comment]
Ok, let's use this issue to track 1 then. 2 is a flaw in the HLS spec. I'm not sure how much effort we want to expend working around it (probably none).

**Comment by justinddunlap** [comment]
Thanks! To be clear, when you say "we should automatically filter those that are at resolutions beyond that supported by the device" - does that mean the code was supposed to already be doing that and it's failing to, or is it something that has not been implemented yet? I couldn't find any code that specifically tried to take into consideration the width and height of a Variant.

**Comment by ojw28** [comment]
It's not implemented for HLS yet, but it is implemented for DASH and SmoothStreaming. It would be good if you could check that those samples do play correctly, and also validate that they don't switch up to high resolution streams (you can read the video height from the debug line above the player in the demo app).

**Comment by justinddunlap** [comment]
I checked the DASH sample and it failed to filter out the 1080p stream, so I added an issue here: https://github.com/google/ExoPlayer/issues/393

The first SmoothStreaming example worked perfectly but the PlayReady one does not play due to content protection not being supported on Android 4.1.

**Comment by dmitriy-horpynchenko** [comment]
Have the same issue. Short freezing even when switching from 400x300 to 704x528. Devices Samsung Galaxy Tab 4 10.1 (1280x800), Samsung Galaxy Tab 3 10.1 (1280x800), Nexus 7 (2013)

**Comment by justinddunlap** [comment]
Is there anything I can do to facilitate a fix for the issue? What would a fix look like? Would filterVariants() check the screen size and disallow Variants that are larger than that size? 

I did notice that my Nexus 4 test device can play 1080p despite having a 720p screen, but I don't know how much of a use case there is for playing variants that are larger than the device's screen, or if Exoplayer should support eg Android devices connected to a larger external display. 

Is there a better way to determine the device's decoding capabilities beyond checking screen sizes?

**Comment by ojw28** [comment]
We have a fix for the DASH and SmoothStreaming case that introduces a VideoFormatSelectorUtil class that applies some better logic to figure out what formats the device will be able to play. It'll appear on dev branch tomorrow.

We'll then wire up HLS to the same util class, although note that filtering will only be possible in the case where the master playlist provides sufficient information (e.g. the width/height of each variant). Which is fine for the sample you pasted above, but is not mandated by the HLS spec.

**Comment by ojw28** [comment]
Where resolution information is available in the manifest, we filter as of https://github.com/google/ExoPlayer/commit/79cdd036828223bf2da29f8091252add27799aed.

**Comment by dmitriy-horpynchenko** [comment]
Hi, as I wrote earlier freezing appears even during switching from 400x300 to 704x528 so filtering can't help here. I don't understand why I can't find any mention  of this on the Internet, because it's clear even with "Apple master playlist" played on Samsung Galaxy Tab4. 
ojw28 do you familiar with this issue? Thank you
