### ISSUE TITLE
ExoPlayer slow when setting playback speed on some devices

### ISSUE THREAD

**Issue by danielgimenes** [google/ExoPlayer#3884]
I've managed to use SimpleExoPlayer to play HLS streams successfully and implemented a working way of selecting different playback speeds (1.25x, 1.5x, etc) by setting PlaybackParameters on the player. But in some devices, when I select any playback speed different than 1x, the player starts to skip a lot of frames and audio becomes a little distorted.

On the ExoPlayer release notes of 2.6.0 it says that when the renderer can't keep the pace, they start displaying only key-frames, which I suspect is what is happening. But I've seen that using playback speed of 2x on YouTube app on the same smartphone works perfectly, so I wonder if there is anything I can do to improve the performance of the ExoPlayer renderer. Maybe I'm not using HW decoding when setting playback speed? Is there any configuration for that?

I'm currently using ExoPlayer version 2.6.1. The objects I use are a SimpleExoPlayer instance with a DefaultRenderersFactory activating extensions (using EXTENSION_RENDERER_MODE_ON) and a DefaultTrackSelector. For media source, I'm using HlsMediaSource with a locally created Handler. If there is any other relevant information/code that I could provide to help understanding the context, please let me know.

**Comment by andrewlewis** [comment]
Please see ["Why doesn’t setPlaybackParameters work properly on some devices?"](https://google.github.io/ExoPlayer/faqs.html#why-doesnt-setplaybackparameters-work-properly-on-some-devices) and also https://github.com/google/ExoPlayer/issues/26#issuecomment-296133260.

**Comment by danielgimenes** [comment]
The release version worked perfectly. 

Thank you for the quick response
