### ISSUE TITLE
MP4 live stream video from server not playing but MP2 playing in exoplayer

### ISSUE THREAD

**Issue by guraymumun94** [google/ExoPlayer#3885]
I want to play mp4 live stream videos from my server but i cant and there is no errors. At the same time i can play mp3 live stream videos from same server. I'm using exoplayer 2.7.0.
This is my code:

        BandwidthMeter bandwidthMeter = new DefaultBandwidthMeter();
        TrackSelection.Factory videoTrackSelectionFactory = new 
        AdaptiveTrackSelection.Factory(bandwidthMeter);
        TrackSelector trackSelector = new DefaultTrackSelector(videoTrackSelectionFactory);
        LoadControl loadControl = new DefaultLoadControl();
        player = ExoPlayerFactory.newSimpleInstance(this, trackSelector);
        playerView.setPlayer(player);
        DataSource.Factory dataSourceFactory = new DefaultDataSourceFactory(context, Util.getUserAgent(context, "Some String"));

        player.addListener(new ExoPlayer.EventListener() {

            @Override
            public void onTimelineChanged(Timeline timeline, Object manifest, int reason) {
                Log.d("onTimelineChanged", "onTimelineChanged");
            }

            @Override
            public void onTracksChanged(TrackGroupArray trackGroups, TrackSelectionArray trackSelections) {
                Log.d("onTracksChanged", "onTracksChanged");
            }

            @Override
            public void onLoadingChanged(boolean isLoading) {
                Log.d("onLoadingChanged", isLoading ? "LOADING" : "NOT LOADING");
            }

            @Override
            public void onPlayerStateChanged(boolean playWhenReady, int playbackState) {
                Log.d("onPlayerStateChanged", "onPlayerStateChanged");
                switch (playbackState) {
                    case ExoPlayer.STATE_BUFFERING:
                        //You can use progress dialog to show user that video is preparing or buffering so please wait
                        Log.d("STATE_BUFFERING", "STATE_BUFFERING");
                        break;
                    case ExoPlayer.STATE_IDLE:
                        //idle state
                        Log.d("STATE_IDLE", "STATE_IDLE");
                        break;
                    case ExoPlayer.STATE_READY:
                        // dismiss your dialog here because our video is ready to play now
                        Log.d("STATE_READY", "STATE_READY");
                        break;
                    case ExoPlayer.STATE_ENDED:
                        // do your processing after ending of video
                        Log.d("STATE_ENDED", "STATE_ENDED");
                        break;
                }
            }

            @Override
            public void onRepeatModeChanged(int repeatMode) {
                Log.d("onRepeatModeChanged", "onRepeatModeChanged");
            }

            @Override
            public void onShuffleModeEnabledChanged(boolean shuffleModeEnabled) {
                Log.d("onShuffleMode", "onShuffleModeEnabledChanged");
            }

            @Override
            public void onPlayerError(ExoPlaybackException error) {
                Log.d("onPlayerError", "onPlayerError");
                // show user that something went wrong. I am showing dialog but you can use your way
                AlertDialog.Builder adb = new AlertDialog.Builder(context, android.R.style.Theme_Holo_Light_Dialog_NoActionBar);
                if (!isConnected()) {
                    adb.setTitle("Проблем с интернет!");
                    adb.setMessage(context.getString(R.string.no_internet));
                } else {
                    adb.setTitle("Грешка!");
                    adb.setMessage("Възникна грешка.\nМоля, опитайте отново.");
                }
                adb.setPositiveButton("OK", new DialogInterface.OnClickListener() {
                    @Override
                    public void onClick(DialogInterface dialogInterface, int which) {
                        dialogInterface.dismiss();
                    }
                });
                AlertDialog ad = adb.create();
                ad.show();
            }

            @Override
            public void onPositionDiscontinuity(int reason) {
                Log.d("onPositionDiscontinuity", "onPositionDiscontinuity");
            }

            @Override
            public void onPlaybackParametersChanged(PlaybackParameters playbackParameters) {
                Log.d("onPlayback", "onPlaybackParametersChanged");
            }

            @Override
            public void onSeekProcessed() {
                Log.d("onSeekProcessed", "onSeekProcessed");
            }
        });

            final MediaSource videoSource = new 
            ExtractorMediaSource.Factory(dataSourceFactory).createMediaSource(Uri.parse(movieLink));
            player.prepare(videoSource);
            player.setPlayWhenReady(true);

This is my Logcat:

02-22 16:57:57.702 9753-9753/bg.versaties.ott D/onPlayerStateChanged: onPlayerStateChanged
02-22 16:57:57.702 9753-9753/bg.versaties.ott D/STATE_BUFFERING: STATE_BUFFERING
02-22 16:57:57.796 9753-10127/bg.versaties.ott I/AudioTrack: ~AudioTrack, releasing session id from 9753 on behalf of 9753 mState/4
02-22 16:57:57.798 9753-10110/bg.versaties.ott I/omx_core: OMX_Deinit 96 gInitCount=0
02-22 16:57:58.003 9753-9753/bg.versaties.ott D/onTimelineChanged: onTimelineChanged
02-22 16:57:58.003 9753-9753/bg.versaties.ott D/onLoadingChanged: LOADING
02-22 16:57:59.524 9753-9915/bg.versaties.ott W/MediaCodecInfo: AssumedMaxChannelAdjustment: OMX.google.mp2.decoder, [1 to 30]
02-22 16:57:59.524 9753-9915/bg.versaties.ott W/MediaCodecInfo: AssumedMaxChannelAdjustment: OMX.google.mp2.decoder, [1 to 30]
02-22 16:57:59.526 9753-9753/bg.versaties.ott D/onTracksChanged: onTracksChanged
02-22 16:57:59.530 9753-10130/bg.versaties.ott I/OMXClient: Using client-side OMX mux.
02-22 16:57:59.541 9753-10129/bg.versaties.ott I/MediaCodec: [OMX.amlogic.avc.decoder.awesome] setting surface generation to 9987083
02-22 16:57:59.542 9753-10129/bg.versaties.ott V/MediaCodec: Found 2 pieces of codec specific data.
02-22 16:57:59.543 9753-10130/bg.versaties.ott E/ACodec: [OMX.amlogic.avc.decoder.awesome] storeMetaDataInBuffers failed w/ err -2147483648
02-22 16:57:59.545 9753-10130/bg.versaties.ott I/ACodec: codec does not support config priority (err -1010)
02-22 16:57:59.556 9753-10129/bg.versaties.ott V/MediaCodec: input buffers allocated
02-22 16:57:59.557 9753-10130/bg.versaties.ott D/SurfaceUtils: set up nativeWindow 0xef1b0a08 for 1920x1088, color 0x11, rotation 0, usage 0x2002900
02-22 16:57:59.558 9753-10130/bg.versaties.ott W/ACodec: [OMX.amlogic.avc.decoder.awesome] setting nBufferCountActual to 8 failed: -1010
02-22 16:57:59.558 9753-10130/bg.versaties.ott W/ACodec: [OMX.amlogic.avc.decoder.awesome] setting nBufferCountActual to 7 failed: -1010
02-22 16:57:59.571 9753-10129/bg.versaties.ott V/MediaCodec: output buffers allocated
02-22 16:57:59.577 9753-10133/bg.versaties.ott I/OMXClient: Using client-side OMX mux.
02-22 16:57:59.603 9753-10133/bg.versaties.ott I/omx_core: OMX_Init 66 gInitCount=1
02-22 16:57:59.603 9753-10133/bg.versaties.ott V/AML_all_components: --------------------------------
                                                                     ARCH = arm
                                                                     author:aml.sh multi-media team
                                                                     branch name:   * jb-mr1-amlogic
                                                                     git version:   5189f2d93e667b43abf3ad9f41d0acddd4910acc 
                                                                     last changed:  Date: Mon Oct 24 10:39:59 2016 +0800
                                                                     build-time:     Mon Oct 24 16:01:34 CST 2016
                                                                     build-name:     jiacheng.mei
                                                                     uncommitted-file-num:0
                                                                     cd /mnt/fileroot/jiacheng.mei/amlogic
                                                                     hostname droid05
                                                                     --------------------------------
02-22 16:57:59.603 9753-10133/bg.versaties.ott V/OmxComponentManagerImpl: loadLibrary:258 Loading OMX library libOmxVideo.so.
02-22 16:57:59.603 9753-10133/bg.versaties.ott E/omx_video: amvenc_avc open failed!set default instance number as 1,ret=-1,Permission denied(13)
02-22 16:57:59.603 9753-10133/bg.versaties.ott E/omx_video: /dev/HevcEnc open failed!set default instance number as 1,ret=-1,No such file or directory(2)
02-22 16:57:59.603 9753-10133/bg.versaties.ott I/omx_core: Core library has 15 components
02-22 16:57:59.603 9753-10133/bg.versaties.ott E/OMXMaster: A component of name 'OMX.google.h264.decoder' already exists, ignoring this one.
02-22 16:57:59.604 9753-10133/bg.versaties.ott E/OMXMaster: A component of name 'OMX.google.alac.decoder' already exists, ignoring this one.
02-22 16:57:59.618 9753-10133/bg.versaties.ott V/MediaCodec: Found 0 pieces of codec specific data.
02-22 16:57:59.618 9753-10133/bg.versaties.ott E/OMXNodeInstance: setConfig(1:google.mp2.decoder, ConfigPriority(0x6f800002)) ERROR: Undefined(0x80001001)
02-22 16:57:59.618 9753-10133/bg.versaties.ott I/ACodec: codec does not support config priority (err -2147483648)
02-22 16:57:59.620 9753-10133/bg.versaties.ott V/MediaCodec: input buffers allocated
02-22 16:57:59.620 9753-10133/bg.versaties.ott V/MediaCodec: output buffers allocated
02-22 16:57:59.624 9753-10133/bg.versaties.ott V/MediaCodec: output buffers allocated
02-22 16:57:59.629 9753-10133/bg.versaties.ott V/MediaCodec: output buffers allocated
02-22 16:57:59.630 9753-10133/bg.versaties.ott V/MediaCodec: codec output format changed
02-22 16:57:59.633 9753-9915/bg.versaties.ott I/AudioTrack: set(): streamType -1, sampleRate 48000, format 0x1, channelMask 0x3, frameCount 12000, flags #0, notificationFrames 0, sessionId 0, transferType 3, uid -1, pid -1
02-22 16:57:59.634 9753-9915/bg.versaties.ott I/AudioTrack: createTrack_l() output 2 mAfFrameCount 1024
02-22 16:57:59.634 9753-9915/bg.versaties.ott I/AudioTrack: createTrack_l() output 2 mAfSampleRate 48000

**Comment by guraymumun94** [comment]
Any suggestions?

**Comment by ojw28** [comment]
Without a link to some media that we can use to reproduce the issue, there is nothing we can do to help. Please provide one if you wish for us to help further. Thanks!

**Comment by guraymumun94** [comment]
Try this MP4 live stream link: [http://94.236.208.171:40668/udp/239.100.200.2:25000](http://94.236.208.171:40668/udp/239.100.200.2:25000)

**Comment by ojw28** [comment]
That is not an MP4 live stream. It's MPEG-TS. The problem is that the stream doesn't contain proper IDR keyframes. You can enable support for this type of stream manually by making a `DefaultExtractorsFactory` instance and enabling non-idr-keyframe support on it:
```
DefaultExtractorsFactory extractorsFactory = new DefaultExtractorsFactory();
extractorsFactory.setTsExtractorFlags(DefaultTsPayloadReaderFactory.FLAG_ALLOW_NON_IDR_KEYFRAMES);
```
Then pass this factory as an explicit argument when creating your `ExtractorMediaSource`. You can pass it through the now deprecated constructors, or set it on the factory that you're using to create the `ExtractorMediaSource` instance.

**Comment by guraymumun94** [comment]
It's working. Thank you!
