### ISSUE TITLE
Wrong segment of video getting played in HLS.

### ISSUE THREAD

**Issue by aatish1989** [google/ExoPlayer#3889]
**Issue Description :-**
I am using CacheDataSourceFactory for disk caching the video chunks. Intermittently I am seeing wrong video chunks are getting played. If I remove caching layer its working fine.

**Version of ExoPlayer being used:**
2.6.1

**Comment by aatish1989** [comment]
Sometime I am playing same url in two different videos views. Can it be because of that?

**Comment by ojw28** [comment]
We did fix a potential caching issue in `2.7.0`, so please try upgrading. Please also ensure you only have one `SimpleCache` instance pointing to a given cache directory. It's OK to have multiple `CacheDataSource` instances sharing the same `SimpleCache` instance, but it's not OK to have multiple `SimpleCache` instances accessing the same cache directory.

When trying out these suggestions, please make sure you wipe the cache directory to clear anything that might have been incorrectly written to it previously.

**Comment by ojw28** [comment]
Closing for now. Please let us know if you're still able to reproduce, in which case please provide concrete reproduction steps that we can use (without them there's not much we can do to help). Thanks!
