### ISSUE TITLE
Using .mp4 videos and .mp3 for HLS

### ISSUE THREAD

**Issue by quiKsilverItaly** [google/ExoPlayer#3892]
Hey there. 
Sorry for my low level question, but I am just getting into the videoplayer subject. 

After some research I decided to use Exoplayer for HLS on Android. 
I am getting .mp4 and .mp3 files from web, which I want to stream as HLS. 

As far I know I need to convert .mp4 to for example to .fmp4? Is that right? And does this even make sense? Thinking about it, it makes sense, when the backend provides the right format, so the app can download step by step the fragmented video.

This is no real issue, just a question. I hope someone can explain, thanks.

**Comment by ojw28** [comment]
How to prepare media for delivery is a bit out of the scope of this issue tracker. Lots of information about preparing HLS content for delivery can be found [here](https://developer.apple.com/streaming/). Else, StackOverflow is probably a better place to ask this type of question.
