### ISSUE TITLE
Does ExoPlayer have the OnSeekCompleteListener?

### ISSUE THREAD

**Issue by jclova** [google/ExoPlayer#3894]
MediaPlayer class has the OnSeekCompleteListener.

If not, I can work around it by checking the current position got updated or not after seeking.
For the cleanliness of my code, I was looking for the OnSeekCompleteListener but could not find it.

Does ExoPlayer not have the listener or I am just not finding it?

**Comment by ghost** [comment]
It's in Player.EventListener, there is a method called onSeekProcessed().

**Comment by jclova** [comment]
Thank you so much. 
I was using the older version of ExoPlayer so I could not find it.
