### ISSUE TITLE
No sound on Android 5

### ISSUE THREAD

**Issue by FelixMittermeier** [google/ExoPlayer#3898]
### Issue description
I want to play an audio file, which is stored on my server. It works just perfect on newer Android Versions like 7.1.2 etc., but on Android 5 there is absolutely no sound. Tried on different devices, but same issue.

### Reproduction steps
Code for playing audio file:
```
        renderersFactory = new DefaultRenderersFactory(getApplicationContext());
        bandwidthMeter = new DefaultBandwidthMeter();
        trackSelectionFactory = new AdaptiveTrackSelection.Factory(bandwidthMeter);
        trackSelector = new DefaultTrackSelector(trackSelectionFactory);
        loadControl = new DefaultLoadControl();

        player = ExoPlayerFactory.newSimpleInstance(renderersFactory, trackSelector, loadControl);

        dataSourceFactory = new DefaultDataSourceFactory(getApplicationContext(), "ExoplayerDemo");
        extractorsFactory = new DefaultExtractorsFactory();
        mainHandler = new Handler();
        mediaSource = new ExtractorMediaSource(Uri.parse(streamUrl),
                dataSourceFactory,
                extractorsFactory,
                mainHandler,
                null);

        player.prepare(mediaSource);

        player.setPlayWhenReady(true);
```
### Link to test content
https:/felix-mittermeier.de/storyban/voice/1.mp3

### Version of ExoPlayer being used
Version 2.7.0, but same behaviour on older versions

### Device(s) and version(s) of Android being used
E.g. Galaxy Alpha with Android 5.0.2, but also standard emulator

### A full bug report captured from the device
Sorry, I cannot create a bugreport due to issues with Android Studio, but here is the logcat:

02-25 17:28:26.502 4613-4613/com.example.exoplayerdemo I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.exoplayer2.video.MediaCodecVideoRenderer$OnFrameRenderedListenerV23>
02-25 17:28:26.502 4613-4613/com.example.exoplayerdemo I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.exoplayer2.video.MediaCodecVideoRenderer$OnFrameRenderedListenerV23>
02-25 17:28:26.504 4613-4613/com.example.exoplayerdemo I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.exoplayer2.video.MediaCodecVideoRenderer$OnFrameRenderedListenerV23>
02-25 17:28:26.505 4613-4613/com.example.exoplayerdemo I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.exoplayer2.video.MediaCodecVideoRenderer$OnFrameRenderedListenerV23>
02-25 17:28:26.505 4613-4613/com.example.exoplayerdemo I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.exoplayer2.video.MediaCodecVideoRenderer$OnFrameRenderedListenerV23>
02-25 17:28:26.516 4613-4613/com.example.exoplayerdemo I/ExoPlayerImpl: Init ExoPlayerLib/2.4.2 [generic_x86_64, Android SDK built for x86_64, unknown, 21]

**Comment by erdemguven** [comment]
Please try the latest code on dev-v2 branch and let us know if it makes any difference. I tried the test content with the latest code and it plays fine both on Android 5 device and emulator.

**Comment by FelixMittermeier** [comment]
Sorry for asking, but how can I load code from development branch?

Tried it like this: `compile 'com.google.android.exoplayer:exoplayer:dev-v2-r2.7.0'` but this doesn't work. 

Thanks for your answer.

**Comment by erdemguven** [comment]
Please follow these steps: [building exoplayer Locally](https://www.google.com/url?q=https://github.com/google/ExoPlayer/blob/release-v2/README.md%23locally&sa=D&source=hangouts&ust=1519738065224000&usg=AFQjCNFYO2hbiZ6JPTHoIdeeZw0L8X4OGA)

**Comment by FelixMittermeier** [comment]
I did it exactly the way described, but get always the same error:

Error:Unable to resolve dependency for ':app@releaseSdk/compileClasspath': Could not resolve project :exoplayer-library-core.

But if you say it is fixed with the latest code I believe you and wait for the next official release :)

**Comment by ojw28** [comment]
2.7.0 is identical to the current dev branch currently, so it's either going to work for both or for neither.

@erdemguven - Can we try reproducing on a Galaxy S5 to make sure this doesn't reproduce for us?

**Comment by ojw28** [comment]
Ignore the Galaxy S5 comment; I incorrectly combined "Android 5" and "Galaxy Alpha" :). Probably worth trying to reproduce on a Galaxy Alpha, if we have one.

**Comment by FelixMittermeier** [comment]
Oh okay, then it does not work, because I am already using latest 2.7.0 version.

**Comment by erdemguven** [comment]
The log you shared has "Init ExoPlayerLib/2.4.2" line, which I think means you use 2.4.2 not 2.7.0. Please make sure you use 2.7.0 release. 

Also please try to play the media using the exoplayer demo app. Once the demo app is installed on the device, you can play your media using:
`adb shell am start -a com.google.android.exoplayer.demo.action.VIEW -d https://felix-mittermeier.de/storyban/voice/1.mp3`

In the meantime if I can find a Samsung Galaxy Alpha, I'll try it myself.

**Comment by FelixMittermeier** [comment]
A bit strange why the log above shows the old version. I just cleaned the project, rebuild everything and startet again. Same behaviour, except the log contains the latest version number: (tested on Android 5 emulator - Android 7 emulator works just fine)

02-26 16:03:55.316 2965-2965/de.mittermeier.felix.storyban I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.exoplayer2.video.MediaCodecVideoRenderer$OnFrameRenderedListenerV23>
02-26 16:03:55.316 2965-2965/de.mittermeier.felix.storyban I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.exoplayer2.video.MediaCodecVideoRenderer$OnFrameRenderedListenerV23>
02-26 16:03:55.316 2965-2965/de.mittermeier.felix.storyban I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.exoplayer2.video.MediaCodecVideoRenderer$OnFrameRenderedListenerV23>
02-26 16:03:55.317 2965-2965/de.mittermeier.felix.storyban I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.exoplayer2.video.MediaCodecVideoRenderer$OnFrameRenderedListenerV23>
02-26 16:03:55.317 2965-2965/de.mittermeier.felix.storyban I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.exoplayer2.video.MediaCodecVideoRenderer$OnFrameRenderedListenerV23>
02-26 16:03:55.319 2965-2965/de.mittermeier.felix.storyban I/ExoPlayerImpl: Init 104af353 [ExoPlayerLib/2.7.0] [generic_x86_64, Android SDK built for x86_64, unknown, 21]
02-26 16:03:58.090 2965-3082/de.mittermeier.felix.storyban V/FA: Inactivity, disconnecting from the service
02-26 16:03:58.329 2965-3094/de.mittermeier.felix.storyban E/ExoPlayerImplInternal: Source error.

**Comment by erdemguven** [comment]
Have you tried the demo app?

Also note the emulators were broken prior to API level 23: http://google.github.io/ExoPlayer/faqs.html#does-exoplayer-support-emulators

So it's better to test on real devices.

**Comment by erdemguven** [comment]
I tested the demo app on Samsung Galaxy Alpha and plays fine your media.

**Comment by FelixMittermeier** [comment]
Hmm, I don't get it. Just send my updated app to the Galaxy Alpha user with Android 5 and there is still the same problem. Is there any difference in code between the one in the demo app and the one posted above?

**Comment by andrewlewis** [comment]
Is there a full stack trace in logcat close to `E/ExoPlayerImplInternal: Source error`? It would be useful to see the cause of the exception.

**Comment by FelixMittermeier** [comment]
Unfortunately no, it just shows this error multiple times:
`Rejecting re-init on previously-failed class java.lang.Class<com.google.android.exoplayer2.video.MediaCodecVideoRenderer$OnFrameRenderedListenerV23>`

**Comment by andrewlewis** [comment]
The 'Rejecting re-init' logging is expected and unrelated to this.

Please could you run `adb logcat`, reproduce the error, then attach the output here?

**Comment by FelixMittermeier** [comment]
The 'Rejecting re-init' logging doesn't appear when everything is working - just a side note.

I can't run `adb logcat` on Android 5, because I always get this error: `Failed to get bugreportz version: 'bugreportz -v' returned '/system/bin/sh: bugreportz: not found' (code 0).
If the device does not run Android 7.0 or above, try 'adb bugreport' instead.
`

**Comment by erdemguven** [comment]
I noticed on Android 5 "https:/felix..." (single slash) fails to play but Android 8 is fine with it. Can it be the problem? Please make sure you put double slashes after http(s).

**Comment by FelixMittermeier** [comment]
Yeah, this makes sense and is possible the solution for the problem, because now it's also working in the Android 5 emulator. I was not be able yet to test it on the Galaxy Alpha with Android 5, but I am quite sure it's working now. Thank you very much :)

If it is still not working as expected on the Alpha, I am going to reopen this issue.
