### ISSUE TITLE
Is TextTrackRenderer fully implemented?

### ISSUE THREAD

**Issue by anotherhale** [google/ExoPlayer#39]
I have started to look at the TextTrackRenderer, but do not see any examples or documentation on how to set it up.  I just wanted to ask if there is anything available before I dive in and start to figure out how to do it.

I assume that I can extend the functionality of the DefaultRendererBuilder to also support building the text renderer?
Does the TextTrackRenderer constructor just take a FrameworkSampleSource with the URI pointed to the appropriate TTML file?

Thanks,  Andy

**Comment by triwav** [comment]
Thought I would post this here since trying to find documentation on adding an external caption file is very hard:
https://gist.github.com/triwav/ba72e99e5181427f4645

And to use it I'm doing:
                        try
			{
				URL url = new URL(video.getClosedCaptionUrl());
				HttpSampleSource subtitleSource = new HttpSampleSource(url, "text/vtt");
				textRenderer = new TextTrackRenderer(subtitleSource, new WebvttParser(), this, getContext().getApplicationContext().getMainLooper());
				player.prepare(videoRenderer, audioRenderer, textRenderer);
			} catch (MalformedURLException e)
			{
				player.prepare(videoRenderer, audioRenderer);
			}

Note that I am having to pass in the mime type which is less than ideal but getTrackInfo could get called before the load has completed resulting in my case the webvtt file getting ignored by the subtitle parser. One bug is that when it gets to the end of the video it will just hang there. I'm currently dealing with this with this code in my onText method:
                // Bug manually dealing with for now
		int playerPosition = player.getCurrentPosition();
		if (previousOnTextTime == playerPosition)
		{
			player.setRendererEnabled(TYPE_TEXT, false);
		}

**Comment by Ood-Tsen** [comment]
Does ExoPlayer support loading vtt from external file ?

**Comment by triwav** [comment]
That's the purpose of this HttpSampleSource.

**Comment by ojw28** [comment]
It's also supported directly by the library if you use SingleSampleChunkSource. Basically the setup should be:

TextTrackRenderer->ChunkSampleSource->SingleSampleChunkSource

I don't think this approach has the issues that you describe above, so you may find it beneficial to switch from HttpSampleSource over to this approach. Effectively, you'll be replacing your custom HttpSampleSource with ChunkSampleSource->SingleSampleChunkSource.

Sorry, I'm aware documentation is poor around how to this kind of thing. I'm trying to find time to write some.

**Comment by triwav** [comment]
Thanks @ojw28. I tried messing with it. This is as far as I got:

LoadControl loadControl = new LoadControl()
			{

				@Override
				public boolean update(Object loader, long playbackPositionUs, long nextLoadPositionUs, boolean loading, boolean failed)
				{
					Debug.toString("update");
					return false;
				}


				@Override
				public void unregister(Object loader)
				{
					Debug.toString("unregister");

				}


				@Override
				public void trimAllocator()
				{
					Debug.toString("trimAllocator");

				}


				@Override
				public void register(Object loader, int bufferSizeContribution)
				{
					Debug.toString("register");

				}


				@Override
				public Allocator getAllocator()
				{
					Debug.toString("getAllocator");
					// TODO Auto-generated method stub
					return null;
				}
			};

			DataSource dataSource = new DataSource()
			{

				@Override
				public int read(byte[] buffer, int offset, int readLength) throws IOException
				{
					Debug.toString("read");
					return 0;
				}


				@Override
				public long open(DataSpec dataSpec) throws IOException
				{
					Debug.toString("open", dataSpec.uri);
					// TODO Auto-generated method stub
					return 0;
				}


				@Override
				public void close() throws IOException
				{
					// TODO Auto-generated method stub

				}
			};
			DataSpec dataSpec = new DataSpec(Uri.parse(video.getClosedCaptionUrl()));

			Format format = new Format("id", MimeTypes.TEXT_VTT, -1, -1, -1, -1, -1);

			MediaFormat mediaFormat = MediaFormat.createFormatForMimeType(MimeTypes.TEXT_VTT);

			SingleSampleChunkSource chunkSource = new SingleSampleChunkSource(dataSource, dataSpec, format, C.UNKNOWN_TIME_US, mediaFormat);
			SampleSource subtitleSource = new ChunkSampleSource(chunkSource, loadControl, 0, false);
			new TextTrackRenderer(subtitleSource, this, getContext().getApplicationContext().getMainLooper(), new WebvttParser());
			player.prepare(videoRenderer, audioRenderer, textRenderer);

However I'm getting a null Exception:

03-04 13:35:42.934: E/ExoPlayerImplInternal(6922): Internal runtime error.
03-04 13:35:42.934: E/ExoPlayerImplInternal(6922): java.lang.NullPointerException
03-04 13:35:42.934: E/ExoPlayerImplInternal(6922): 	at com.google.android.exoplayer.ExoPlayerImplInternal.prepareInternal(ExoPlayerImplInternal.java:253)
03-04 13:35:42.934: E/ExoPlayerImplInternal(6922): 	at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:191)
03-04 13:35:42.934: E/ExoPlayerImplInternal(6922): 	at android.os.Handler.dispatchMessage(Handler.java:95)
03-04 13:35:42.934: E/ExoPlayerImplInternal(6922): 	at android.os.Looper.loop(Looper.java:137)
03-04 13:35:42.934: E/ExoPlayerImplInternal(6922): 	at android.os.HandlerThread.run(HandlerThread.java:60)
03-04 13:35:42.934: E/ExoPlayerImplInternal(6922): 	at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
03-04 13:35:42.944: E/ExoPlayerImplInternal(6922): Stop failed.
03-04 13:35:42.944: E/ExoPlayerImplInternal(6922): java.lang.NullPointerException
03-04 13:35:42.944: E/ExoPlayerImplInternal(6922): 	at com.google.android.exoplayer.ExoPlayerImplInternal.ensureStopped(ExoPlayerImplInternal.java:593)
03-04 13:35:42.944: E/ExoPlayerImplInternal(6922): 	at com.google.android.exoplayer.ExoPlayerImplInternal.stopAndDisable(ExoPlayerImplInternal.java:510)
03-04 13:35:42.944: E/ExoPlayerImplInternal(6922): 	at com.google.android.exoplayer.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:499)
03-04 13:35:42.944: E/ExoPlayerImplInternal(6922): 	at com.google.android.exoplayer.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:479)
03-04 13:35:42.944: E/ExoPlayerImplInternal(6922): 	at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:237)
03-04 13:35:42.944: E/ExoPlayerImplInternal(6922): 	at android.os.Handler.dispatchMessage(Handler.java:95)
03-04 13:35:42.944: E/ExoPlayerImplInternal(6922): 	at android.os.Looper.loop(Looper.java:137)
03-04 13:35:42.944: E/ExoPlayerImplInternal(6922): 	at android.os.HandlerThread.run(HandlerThread.java:60)
03-04 13:35:42.944: E/ExoPlayerImplInternal(6922): 	at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
03-04 13:35:42.944: E/ExoPlayerImplInternal(6922): Release failed.
03-04 13:35:42.944: E/ExoPlayerImplInternal(6922): java.lang.NullPointerException
03-04 13:35:42.944: E/ExoPlayerImplInternal(6922): 	at com.google.android.exoplayer.ExoPlayerImplInternal.release(ExoPlayerImplInternal.java:525)
03-04 13:35:42.944: E/ExoPlayerImplInternal(6922): 	at com.google.android.exoplayer.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:500)
03-04 13:35:42.944: E/ExoPlayerImplInternal(6922): 	at com.google.android.exoplayer.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:479)
03-04 13:35:42.944: E/ExoPlayerImplInternal(6922): 	at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:237)
03-04 13:35:42.944: E/ExoPlayerImplInternal(6922): 	at android.os.Handler.dispatchMessage(Handler.java:95)
03-04 13:35:42.944: E/ExoPlayerImplInternal(6922): 	at android.os.Looper.loop(Looper.java:137)
03-04 13:35:42.944: E/ExoPlayerImplInternal(6922): 	at android.os.HandlerThread.run(HandlerThread.java:60)
03-04 13:35:42.944: E/ExoPlayerImplInternal(6922): 	at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
03-04 13:35:42.974: E/HlsVideoPlayer(6922): Playback failed
03-04 13:35:42.974: E/HlsVideoPlayer(6922): java.lang.NullPointerException

**Comment by triwav** [comment]
Thanks @ojw28. I tried looking into this but it seems pretty complicated to get setup. It seems like the Allocator requires some extra work to keep track of what's been loaded. If you or someone else provides some documentation I'll investigate further but at this point I think I'll stick with my existing solution.


LoadControl loadControl = new LoadControl()
		{

			@Override
			public boolean update(Object loader, long playbackPositionUs, long nextLoadPositionUs, boolean loading, boolean failed)
			{
				return true;
			}


			@Override
			public void unregister(Object loader)
			{
				Debug.toString("unregister");

			}


			@Override
			public void trimAllocator()
			{
				Debug.toString("trimAllocator");

			}


			@Override
			public void register(Object loader, int bufferSizeContribution)
			{
				Debug.toString("register");

			}


			@Override
			public Allocator getAllocator()
			{
				Debug.toString("getAllocator");
//				return null;
				return new Allocator()
				{
					
					@Override
					public void trim(int targetSize)
					{
						// TODO Auto-generated method stub
						Debug.toString("trim");

					}
					
					
					@Override
					public int getAllocatedSize()
					{
						// TODO Auto-generated method stub
						Debug.toString("getAllocatedSize");

						return 0;
					}
					
					
					@Override
					public Allocation allocate(int size)
					{
						// TODO Auto-generated method stub
						Debug.toString("allocate", size);

						return new Allocation()
						{
							
							@Override
							public void release()
							{
								Debug.toString("Allocation", "release");
								
							}
							
							
							@Override
							public int getFragmentOffset(int index)
							{
								Debug.toString("Allocation", "getFragmentOffset");
								return 0;
							}
							
							
							@Override
							public int getFragmentLength(int index)
							{
								Debug.toString("Allocation", "getFragmentLength");
								return 0;
							}
							
							
							@Override
							public byte[][] getBuffers()
							{
								Debug.toString("Allocation", "getBuffers");
								return null;
							}
							
							
							@Override
							public void ensureCapacity(int size)
							{
								Debug.toString("Allocation", "ensureCapacity");
								
							}
							
							
							@Override
							public int capacity()
							{
								Debug.toString("Allocation", "capacity");
								return 0;
							}
						};
					}
				};
			}
		};

		DataSource dataSource = new DataSource()
		{

			@Override
			public int read(byte[] buffer, int offset, int readLength) throws IOException
			{
				Debug.toString("read");
				return 0;
			}


			@Override
			public long open(DataSpec dataSpec) throws IOException
			{
				Debug.toString("open", dataSpec.uri);
				// TODO Auto-generated method stub
				return 1000;
			}


			@Override
			public void close() throws IOException
			{
				// TODO Auto-generated method stub

			}
		};

		Uri uri = Uri.parse(video.getClosedCaptionUrl());
		DataSpec dataSpec = new DataSpec(uri);

		Format format = new Format("id", MimeTypes.TEXT_VTT, -1, -1, -1, -1, -1);

		MediaFormat mediaFormat = MediaFormat.createFormatForMimeType(MimeTypes.TEXT_VTT);

		SingleSampleChunkSource chunkSource = new SingleSampleChunkSource(dataSource, dataSpec, format, C.UNKNOWN_TIME_US, mediaFormat);
		SampleSource subtitleSource = new ChunkSampleSource(chunkSource, loadControl, 0, false);
		textRenderer = new TextTrackRenderer(subtitleSource, this, getContext().getApplicationContext().getMainLooper(), new WebvttParser());

**Comment by priyankajagtap18** [comment]
Does Exoplayer support rtsp and rtmp ?
Any help will be appreciated
Thanks

**Comment by ojw28** [comment]
Yes, it is complicated to setup currently. I'm working on making it simpler.

**Comment by ojw28** [comment]
Simplifications (which will apply to all subtitle formats) are tracked by #587.

**Comment by andreimarinescu** [comment]
I got this working using the gist posted by @triwav (thanks for this, by the way!). I've created a new gist that is compatible with the latest dev version, I hope it's ok to post it here in case anyone else faces this issue until the simplifications in #587 are added. https://gist.github.com/andreimarinescu/9b2e6c1fed6bbaddb91b

**Comment by triwav** [comment]
Andre, I just updated my gist to what we're actually using in production today. There were a few weird bugs in that version of the code that this latest version should address. If you experience any bugs with your script feel free to take a look at my latest gist to see if that solves it for you.

**Comment by andreimarinescu** [comment]
Thanks! I'll have a look. We haven't yet deployed this into production yet, probably that's why we haven't hit any roadbumps yet.

**Comment by triwav** [comment]
Yeah the main things to check is turning on and off captions repeatedly, jumping to a different point in the video and behavior when the video finishes playing.

**Comment by abhiguru** [comment]
Tried the above and then
HttpSampleSource httpSampleSource = new HttpSampleSource(url , "text/vtt" );
TrackRenderer textRenderer = new TextTrackRenderer(httpSampleSource, player,
mainHandler.getLooper(), new WebvttParser());

The textRenderer that gets generated has no sources in it any idea why ? Here is the code I have https://gist.github.com/abhiguru/9fb26a51c4e8b57d3d48

and here is the error about null sources
Internal runtime error.
java.lang.NullPointerException: Attempt to invoke interface method 'boolean com.google.android.exoplayer.SampleSource$SampleSourceReader.prepare(long)' on a null object reference
at com.google.android.exoplayer.SampleSourceTrackRenderer.doPrepare(SampleSourceTrackRenderer.java:54)
at com.google.android.exoplayer.TrackRenderer.prepare(TrackRenderer.java:110)
at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(ExoPlayerImplInternal.java:281)
at com.google.android.exoplayer.ExoPlayerImplInternal.prepareInternal(ExoPlayerImplInternal.java:272)
at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:201)
at android.os.Handler.dispatchMessage(Handler.java:98)
at android.os.Looper.loop(Looper.java:135)
at android.os.HandlerThread.run(HandlerThread.java:61)
at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)

**Comment by ojw28** [comment]
You're getting the NullPointerException because you've implemented the `register` method to return `null`, which is in violation of the [contract of that method](https://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer/SampleSource.html#register()).

That aside, it's really quite easy to setup an external caption file in recent versions of ExoPlayer. You shouldn't need to be writing custom code. You can use `SingleSampleSource` and you should need about four lines of code, similar to those in the top post in https://github.com/google/ExoPlayer/issues/753.

**Comment by abhiguru** [comment]
Thanks for the reply, Eventually I found out about the SingleSampleSource and have been using it without a problem!  Maybe we can add that to the wiki for others who come looking ? #753 is a helpful thread thanks for pointing it out.
