### ISSUE TITLE
PlayReady Token Authentication

### ISSUE THREAD

**Issue by juanpef** [google/ExoPlayer#390]
Hi,
I am using ExoPlayerDemo for trying to play a video protected with PlayReady DRM. The authentication is by a token and I need to generate a file whose XML would be:

![capturaxml](https://cloud.githubusercontent.com/assets/9380321/7112269/62207540-e1c8-11e4-801c-ed810ac45dcb.PNG)

I have tryed changing SmoothStreamingTestMediaDrmCallback.java with:

HashMap<String, String> keyRequestProperties = new HashMap<String, String>();
    keyRequestProperties.put("Content-Type", "text/xml");
    keyRequestProperties.put("body", "<?xml version='1.0' encoding='utf-8'?><PlayReadyInitiator xmlns='http://schemas.microsoft.com/DRM/2007/03/protocols/'><LicenseServerUriOverride><LA_URL></LA_URL></LicenseServerUriOverride><SetCustomData><CustomData>AU_ZGAE6U_hyfH</CustomData></SetCustomData></PlayReadyInitiator>");

But it doesn´t work:

04-13 10:06:27.030: E/EventLogger(2486): internalError [0.08, rendererInitError]
04-13 10:06:27.030: E/EventLogger(2486): com.google.android.exoplayer.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 404
04-13 10:06:27.030: E/EventLogger(2486): 	at com.google.android.exoplayer.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:158)
04-13 10:06:27.030: E/EventLogger(2486): 	at com.google.android.exoplayer.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:94)
04-13 10:06:27.030: E/EventLogger(2486): 	at com.google.android.exoplayer.upstream.DataSourceInputStream.open(DataSourceInputStream.java:56)
04-13 10:06:27.030: E/EventLogger(2486): 	at com.google.android.exoplayer.upstream.NetworkLoadable.load(NetworkLoadable.java:92)
04-13 10:06:27.030: E/EventLogger(2486): 	at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:241)
04-13 10:06:27.030: E/EventLogger(2486): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
04-13 10:06:27.030: E/EventLogger(2486): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
04-13 10:06:27.030: E/EventLogger(2486): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
04-13 10:06:27.030: E/EventLogger(2486): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
04-13 10:06:27.030: E/EventLogger(2486): 	at java.lang.Thread.run(Thread.java:818)
04-13 10:06:27.039: E/EventLogger(2486): playerFailed [0.09]
04-13 10:06:27.039: E/EventLogger(2486): com.google.android.exoplayer.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 404
04-13 10:06:27.039: E/EventLogger(2486): 	at com.google.android.exoplayer.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:158)
04-13 10:06:27.039: E/EventLogger(2486): 	at com.google.android.exoplayer.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:94)
04-13 10:06:27.039: E/EventLogger(2486): 	at com.google.android.exoplayer.upstream.DataSourceInputStream.open(DataSourceInputStream.java:56)
04-13 10:06:27.039: E/EventLogger(2486): 	at com.google.android.exoplayer.upstream.NetworkLoadable.load(NetworkLoadable.java:92)
04-13 10:06:27.039: E/EventLogger(2486): 	at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:241)
04-13 10:06:27.039: E/EventLogger(2486): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
04-13 10:06:27.039: E/EventLogger(2486): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
04-13 10:06:27.039: E/EventLogger(2486): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
04-13 10:06:27.039: E/EventLogger(2486): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
04-13 10:06:27.039: E/EventLogger(2486): 	at java.lang.Thread.run(Thread.java:818)

Thanks

**Comment by ojw28** [comment]
I'm confused about what you're trying to do.

- Is this for AndroidTV? Other Android devices don't normally have PlayReady support.
- You can't set the body as a property. But in any case, the body is supposed to be generated by the underlying PlayReady MediaDrm plugin.
- The failure in your log is a 404, indicating that whatever URL you end up trying to connect to doesn't exist.

**Comment by juanpef** [comment]
* Is for a Nexus player that has PlayReady support.
* In other OS only generating this xml it works without problem. But I don´t know how to put this XML in the HashMap.
* I know that 404 is that error, but this URL exists.

Thanks

**Comment by ojw28** [comment]
- Probably the 404 is due to the way you're trying to add the body, which is incorrect.
- You shouldn't put the XML body in the HashMap at all. The body is the second argument passed to executePost in SmoothStreamingTestMediaDrmCallback. You'll see that it obtains the body from the KeyRequest by calling request.getData(). If you inspect the binary data here and turn it into text, you'll see that this is actually already an XML formatted PlayReady key request. Are you sure it doesn't just work as it is?
- If it doesn't then you can try replacing the second argument with your request (in binary form). I'm not sure whether this would work. Alternatively, you may need to take the existing request, convert it to XML, inject the CustomData element that you need to add, convert it back into binary form, and use that.

**Comment by juanpef** [comment]
* Is true, that I was putting the url in Samples.java badly: new Sample("Super speed (PlayReady)",
        "http://B33697.cdn.telefonica.com/33697/SPA_PR_SUBSD_EU_169__5719a2748b79405e20150209110043.ism/Manifest",
        DemoUtil.TYPE_SS),   I have changed it without "/Manifest" and it works now.
* I have done that you say and in the request.getData() there is an xml inwihch is not included CustomData element. How can put it? With: 
keyRequestProperties.put("CustomData","AU_ZGAE6U_hyfH");
?
Thanks for your help

**Comment by ojw28** [comment]
Unfortunately the PlayReady plugin doesn't support injection of CustomData at the moment, so unfortunately your options are:

1. Replace the XML with your own (converted into binary form) and see if that works. I'm not sure whether it will or not.
2. Parse the request.getData() data as XML, insert the CustomData yourself and convert back to binary again. This isn't really within the scope of ExoPlayer help. You'll need to use XML parsing APIs. This is probably a good place to start: http://developer.android.com/training/basics/network-ops/xml.html

**Comment by ojw28** [comment]
Turns out PlayReady does support CustomData, if you use the PRCustomData key. See the most recent replies on #339 for information.
