### ISSUE TITLE
Update PlayerView document to warn about textureview needs hardware acceleration

### ISSUE THREAD

**Issue by sodiqOladeni** [google/ExoPlayer#3901]
I need to display video in recyclerview so i used ToroPlayer which was built on  Exoplayer to play video in recyclerview, but the video is playing but it's not showing the video to the screen, i can only see blank and black screen playing sound. i have logged the issue in ToroPlayer repo and we have troubleshooted the issue together and we later concluded on the capability of Exoplayer on the device that i'm using for testing because he was able to play the video correctly on his own device.

video url: "https://storage.googleapis.com/material-design/publish/material_v_12/assets/0B14F_FSUCc01a05pM2FXWEN0b0U/responsive-01-durations-v1.mp4"
Device name: Samsung S5 and GioneeM5
Build Number: "MMB29M.G900FXXU1CRA2"
Android version: 6.0.1
ExoPlayer version 2.6.1

I will be glad if this issue can be attended to, you can also comment if you need further inquiry, Thanks

**Comment by erdemguven** [comment]
Please test your content using the latest ExoPlayer demo app on your device. If the issue continues, please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

**Comment by eneim** [comment]
@erdemguven Hi there, I'm helping him on this issue. What I found may be interested: he uses TextureView for SimpleExoPlayerView, while having "hardwareAccelerated" set to false in Application's manifest. We know that TextureView requires hardwareAccelerated to be usable, so changing either the manifest or the Surface type solves the problem.

What I think is, as SimpleExoPlayerView (and now PlayerView) supports TextureView as the Surface, one guidance on this may be helpful.
