### ISSUE TITLE
Multiple GTS tests failure on Freescale platform running Android 7.1.1 

### ISSUE THREAD

**Issue by saiyamd** [google/ExoPlayer#3902]
### Issue description
I am running GTS test suite on Freescale i.MX6 (armeabi-v7a) based device running Android 7.1.1. In "GtsExoPlayerTestCases" module total 12 tests are failing out of 33 and for failed tests the reason is similar as described below.

```
1. Fail reason - junit.framework.AssertionFailedError: Test timed out after 300000 ms.
com.google.android.exoplayer.gts.DashTest#testH264AdaptiveWithRendererDisabling
com.google.android.exoplayer.gts.DashTest#testH264AdaptiveWithSeeking
com.google.android.exoplayer.gts.DashTest#testH265AdaptiveWithRendererDisabling
com.google.android.exoplayer.gts.DashTest#testWidevineH264AdaptiveWithRendererDisabling
com.google.android.exoplayer.gts.DashTest#testWidevineH265AdaptiveWithRendererDisabling

2. Fail reason - junit.framework.AssertionFailedError: Codec(DashTest:Video) output 3813 buffers. Expected in range [3840, 3841]
com.google.android.exoplayer.gts.DashTest#testH265Adaptive
com.google.android.exoplayer.gts.DashTest#testWidevineH265Adaptive

3. Fail reason - junit.framework.AssertionFailedError: Total playing time: 157006. Expected: 128199
com.google.android.exoplayer.gts.DashTest#testVp9Adaptive

4. Fail reason - java.lang.Error: com.google.android.exoplayer2.ExoPlaybackException
com.google.android.exoplayer.gts.DashTest#testWidevineH264Adaptive
com.google.android.exoplayer.gts.DashTest#testWidevineH264AdaptiveWithSeekingCbc1
com.google.android.exoplayer.gts.DashTest#testWidevineH264AdaptiveWithSeekingCbcs
com.google.android.exoplayer.gts.DashTest#testWidevineH264AdaptiveWithSeekingCenc
```

### Reproduction steps
Running GTS_5.1_r2_4507047 from host and executing specific tests described as above.

### Link to test content
Default AV media of Exoplayer.

### Version of ExoPlayer being used
From logcat - ExoPlayerImpl: Release 7816815 [ExoPlayerLib/2.5.2]

### Device(s) and version(s) of Android being used
Device: Freescale i.MX6 based Nitrogen6x board
Android: Nougat 7.1.1

### A full bug report captured from the device
[bugreport-7.1.1_1.0.0-ga--2018-02-26-08-46-33.txt.zip](https://github.com/google/ExoPlayer/files/1757918/bugreport-7.1.1_1.0.0-ga--2018-02-26-08-46-33.txt.zip)
[testH264AdaptiveWithRendererDisabling.log](https://github.com/google/ExoPlayer/files/1757919/testH264AdaptiveWithRendererDisabling.log)
[testH265Adaptive.log](https://github.com/google/ExoPlayer/files/1757927/testH265Adaptive.log)

Please advise. Thanks.

**Comment by ojw28** [comment]
It sounds like there are multiple issues with the underlying platform. It's the platform manufacturer's responsibility to ensure their platform passes GTS. Have you tried reporting these issues to the platform manufacturer?

**Comment by saiyamd** [comment]
Hi @ojw28,

On the same platform, other tests of H264 and HEVC are getting passed and we are observing issues in above tests only. Moreover what I have observed is the audio/video plays up to end and after that test, failure is reported.

We are also in touch with NXP and awaiting a response. Moreover, I have also seen a similar issue https://github.com/google/ExoPlayer/issues/3473 on NXP platform.

Can you provide some pointers on what could be the issue?

**Comment by ojw28** [comment]
The platform manufacturer needs to diagnose and fix these kind of issues, however if I had to guess I'd say:

1. The first issue is indicative of a platform API call hanging.
1. The second issue is indicative of the H265 decoder incorrectly discarding away buffers internally, probably when performing adaptive switches.
1. The fourth issue is indicative of an incorrect DRM implementation/integration.

**Comment by ojw28** [comment]
Please report these issues to the device manufacturer.

**Comment by benjaminjrood** [comment]
Hello @saiyamd ,

I am facing the same situation while using the Freescale/NXP i.MX6Q platform.  Have you received any response from NXP yet?  These issues are standing in the way of getting our device certified by Google.
