### ISSUE TITLE
How to add chapter markers?

### ISSUE THREAD

**Issue by ArunkarthickNallasamy** [google/ExoPlayer#3903]
Hi,
 I would like to know how to add chapter markers on Exoplayer. The use case here is we will have a search in our app and search results will contain position of search text (Which will be location of search text from video) it has to be marked on exoplayer just like how we do for Ad's position. Any help?

**Comment by andrewlewis** [comment]
You might be able to use [`PlayerControlView.setExtraAdGroupMarkers`](https://github.com/google/ExoPlayer/blob/fd10a3c/library/ui/src/main/java/com/google/android/exoplayer2/ui/PlayerControlView.java#L405), although these are rendered exactly like the player's ad markers. If you need more flexibility, you could provide your own `TimeBar` implementation that can render multiple sets of markers and use that with `PlayerControlView`.
