### ISSUE TITLE
Pause/Resume download with HlsDownloader or DashDownloader

### ISSUE THREAD

**Issue by pmunizferreira** [google/ExoPlayer#3907]
Hi, I'm using `exoplayer2.source.hls.offline.HlsDownloader` and `exoplayer2.source.dash.offline.DashDownloader` to download videos that will be played offline later. I do not need an instance of Exoplayer at this time, just Downloader classes.
Are there ways to pause and resume the download?

A simple code to start download (working fine):
```
 val tempFolder = Util.createTempDirectory(context, "tempFolder");
 val cache = SimpleCache(tempFolder, NoOpCacheEvictor())
 val dataSourceFactory = CacheDataSourceFactory(context, 100 * 1024 * 1024, 5 * 1024 * 1024)

 val hlsDownloader = HlsDownloader(Uri.parse(videoUrl), DownloaderConstructorHelper(cache, dataSourceFactory))

 hlsDownloader.download(object: Downloader.ProgressListener {
    override fun onDownloadProgress(downloader: Downloader?, downloadPercentage: Float, downloadedBytes: Long) {
       ...
    }
  })
```
I've also tried the `exoplayer2.upstream.CacheUtil` class, but it also has no way to pause/resume downloads.
Maybe another class should be used to download videos? vov
thanks.

**Comment by erdemguven** [comment]
It's recommended to use recently released DownloadManager and DownloadService instead of Downloaders directly. DownloadManager has stopDownloads and startDownloads methods.

For Downloaders: You can interrupt the thread which the downloader or CacheUtil method is running:
`thread.interrupt();`
then the method will throw an InterruptedException. Next time you call the same method, it will continue from where it left.

**Comment by Waleedasim** [comment]
@pmunizferreira can you please tell me how you successfully download hls videos my mobile got hanged when onProgress called. here is my email address please contact
waleedasim08@gmail.com

**Comment by Waleedasim** [comment]
@erdemguven i am stuck at hls downloading your blog is not enough kindly tell me proper way for download video in mobile storage any working code example would be grate full but dont give me a link for demo app its too complicated

**Comment by erdemguven** [comment]
@Waleedasim sorry there isn't a simple hls download example currently. I'll write another post for downloading adaptive streams soon.

**Comment by Waleedasim** [comment]
Kindly do it as soon as possible really appreciate your efforts

**Comment by Waleedasim** [comment]
Thank you for response :)
