### ISSUE TITLE
Downgrading support-v4, play-services-ads library version in ima-extension

### ISSUE THREAD

**Issue by EvanHong1** [google/ExoPlayer#3910]
Hi, 
I am trying to use extension-ima library 2.6.1 as dependency.
In the extension library, it has
com.android.support:support-v4 27.0.0 and
com.google.android.gms:play-services-ads 11.4.2 dependency.

But as I already have support-v4 23.4.0 and play-services-ads 8.4.0 dependency in my app,
conflict occurs. But I don't want to update library version in my app for now.

So I want to resolve this conflict by force-downgrading library version in ima-extension to 23.4.0 and 8.4.0

Would it affect ad playing logic when I downgrade these library version??
It seems to work well when I play ads using VAST tag.

**Comment by andrewlewis** [comment]
Looks like play-services-ads 8.4.0 is from December 2015 so won't include preloading. We haven't done any testing on that version but if you only want preroll VAST ad playback you might be fine.
