### ISSUE TITLE
How to instanciate player with local chunks downloaded by HlsDownloader/DashDownloader?

### ISSUE THREAD

**Issue by pmunizferreira** [google/ExoPlayer#3912]
Hi,
I first consulted you on [how to pause/resume downloads using exoplayer2.source.hls.offline.HlsDownloader and exoplayer2.source.dash.offline.DashDownloader](https://github.com/google/ExoPlayer/issues/3907) . I have done what you have recommended and it is working.
But... these dowloaders save all chunks in the `.exo` format. There is no `m3u8` file that groups the chuncks.

Now my problem is: I need to pass a local path of any previously downloaded video to the exoplayer player, but just `.exo` files are not supported. Most of the questions on this are pointing to this [issue](https://github.com/google/ExoPlayer/issues/2643), that no tip resolved my case.  I can not use the same mediaSource instance used by the downloader because I can play video offline at any time.

Am I using `HlsDownloader` and `DashDownloader` in the wrong way?
Were these downloaders not designed for this purpose?
Should I expect a release with `DownloadManager` and `DownloadService` from exoplayer? Do you have an estimate for this release?
What is the ultimate question? 42.

sorry for so many questions...

**Comment by erdemguven** [comment]
You need to use a CacheDataSource and the same url to read files back from cache. CacheDataSource returns the data from cache if the file is caches/downloaded. You can create multiple CacheDataSource instances but create only one Cache object.

DownloadManager and Service are in the dev branch. Not sure when they will be in the release.

**Comment by Airforce327** [comment]
What about mediaSource, how to instanciate  MediaSource? any reply will be appreciated，Thanks!

**Comment by erdemguven** [comment]
@18795859305 please look at PlayerActivity in the demo app for an example for instantiating a MediaSource.

**Comment by Airforce327** [comment]
Thanks for your reply, i have tried to play cached content and it works. but i found that it needs network for a while when you try to play, latter you can turn off the network access, maybe the mpd file is not cached, is it the  desired behavior ?

**Comment by erdemguven** [comment]
This issue is closed. Please create new issues for new problems.

mpd file should be downloaded if you used DashDownloader. Network can be needed if a licence is needed and if you don't use an offline licence.
