### ISSUE TITLE
Preserve track selection in the demo app on resume

### ISSUE THREAD

**Issue by TarifHatoum** [google/ExoPlayer#3915]
Issue description
After playing the video and then minimized the app and then maximized it the text track is will not show.

Steps to replicate the issue

Load the Demo app and select the video
Enable text track captions.
Play the video on any text tracks .
Minimize the app and wait for 20 min 
Maximize the app and the video will continuous playing
Seek the video forward the caption will disappear

Version of ExoPlayer being used
ExoPlayer version used: 2.5.1

Device(s) and version(s) of Android being used
Tested with Google Pixel with Android 7.1

**Comment by erdemguven** [comment]
The demo app currently doesn't preserve the selected tracks on resume. So the selected text is deselected when maximized. We might implement a way to preserve the selection. Marking this issue as enhancement.

**Comment by TarifHatoum** [comment]
Kindly can you provide us with an estimated time frame since it effect most users.

Thanks

**Comment by erdemguven** [comment]
Sorry, it isn't likely to be implemented soon. When it's done we'll update this issue.

**Comment by TarifHatoum** [comment]
kindly when dis-selecting the video track and re-selecting it the caption is not working is there any turn around to make this work since it is an important feature. Best regards

**Comment by ojw28** [comment]
This will require making a whole bunch of classes implement `Parcelable`. In particular `TrackGroup`, `TrackGroupArray` and `MappingTrackSelector.SelectionOverride` and `DefaultTrackSelector.Parameters`. Once that's done, it'll be possible to implement saving/restoring the state of `DefaultTrackSelector` (e.g. in `onSaveInstanceState`).

We will also need to remove the `TrackSelection.Factory` from `MappingTrackSelector.SelectionOverride`, and have `MappingTrackSelector` have a single factory for generating adaptive selections instead. There's a minor loss of functionality here, in that it'll no longer be possible to simultaneously specify multiple overrides that use different factories. I can't think of a good use case for ever doing that, however, so I think this is OK.

**Comment by ojw28** [comment]
Hm, I guess having separate `TrackSelection.Factory` instances for each of the renderers is kinda required, at least.

**Comment by ojw28** [comment]
Track selections are now preserved in the demo app.
