### ISSUE TITLE
Exoplayer updation issue

### ISSUE THREAD

**Issue by pals-ric** [google/ExoPlayer#3916]
i am trying to update my player from version 1.5.12 to 2.6.1 , i am stuck to the supporting files of the player how they are dependent because all old supporting files got changed.
can any one tell which are the player dependent files i have to replace?

**Comment by erdemguven** [comment]
Which files are you asking about?

**Comment by pals-ric** [comment]
exoplayer version 1.5.12 is dependent on , DashRendererBuilder,DemoPlayer, ExtractorRendererBuilder, HlsRendererBuilder ,SmoothStreamingRendererBuilder. but in new version as i can see these files replaced with other files so i am having trouble in identifying the exact replacement of these files.

**Comment by erdemguven** [comment]
This post can be helpful: https://medium.com/google-exoplayer/exoplayer-2-x-new-package-and-class-names-ef8e1d9ba96f

Also you can check v2 demo app to see how v2 is used.

**Comment by pals-ric** [comment]
that link i have already checked as well as the demo app but in demo app i am not able to identify the replacement of the above mentioned files  . demo link  for version 
 2.6.1    https://github.com/google/ExoPlayer/blob/dev-v2/ 
my application is currently using below player files 
https://github.com/google/ExoPlayer/tree/r1.5.12/demo/src/main/java/com/google/android/exoplayer/demo/player 
so i want to replace updated files one by one.

**Comment by pals-ric** [comment]
i am new to the code of exoplayer so i want to know the process of updation if anyone has done that help me to upgrade this library.

**Comment by ojw28** [comment]
ExoPlayer 2 is quite different to ExoPlayer 1, with changes to the architecture and some of the core concepts. So the short answer is that it's not possible to upgrade by replacing things one by one. You need to understand how ExoPlayer 2 works (e.g. by looking at the demo app's usage) and go from there.

**Comment by pals-ric** [comment]
exoplayer version 1.5.12 is dependent on , DashRendererBuilder,DemoPlayer, ExtractorRendererBuilder, HlsRendererBuilder ,SmoothStreamingRendererBuilder. but in new version as i can see these files replaced with other files so i am having trouble in identifying the exact replacement of these files. can you help me to understand the dependancy of these files.
