### ISSUE TITLE
ENDED event is not fired by ExoPlayer if seek after pause media

### ISSUE THREAD

**Issue by giladna** [google/ExoPlayer#3918]
Hi,
Observed on Demo app 2.7.0

We try to seek to END after selecting pause on this media  ( HLS - Apple 16x9) (This media is multi audio)

https://devstreaming-cdn.apple.com/videos/streaming/examples/bipbop_16x9/bipbop_16x9_variant.m3u8

But Ended event is not fired 

For (HLS -  ID3 Metadata)  media the ended is fired for same scenario when pause and then seek to END 

http://devimages.apple.com/samplecode/adDemo/ad.m3u8 (HLS ID3 Metadata)

What can be the reason?

10x
Gilad.

**Comment by erdemguven** [comment]
Please give more information. How do you seek to the end? On what devices did you try?

**Comment by giladna** [comment]
@erdemguven 

Hi,
I am using Nexus 5  Android 6

I select the media with multi audio then pause in demo app then seeking with scrubber to end of stream

you will see ENDED is not fired 
only if you select play it will be fired 
in hls media without multi audio seek to end will be ended with ended event

it happens also in other  multi audio streams we have 

10x
GIlad.

**Comment by erdemguven** [comment]
It looks like there are couple of issues which prevents the transition to ENDED. One of them for this particular stream TextRenderer.isEnded() doesn't return true after the seek.

**Comment by giladna** [comment]
@erdemguven 
do you consider it bad media?
if ended is not fired for the text  why playback position is not getting updated (this is what I would expect the ended is fired only on the next play click so it means that there is length mismatch between tracks?)

I think that video ended event should be the only event for video playback 
do not see why there would be some more caption for ended video track...

thanks.
Gilad.

**Comment by OrenMe** [comment]
Hi @erdemguven have you gotten a chance to understand the issue? any possible fix?

**Comment by giladna** [comment]
@erdemguven 
@ojw28 

not sure exactly why renderersEnded is blocking here or if it has some wrong behaviour but...
The fix for this ENDED issue is just replacing && in || 

if (renderersEnded
        || (playingPeriodDurationUs == C.TIME_UNSET
            || playingPeriodDurationUs <= playbackInfo.positionUs)
        && playingPeriodHolder.info.isFinal) {
      setState(Player.STATE_ENDED);
      stopRenderers();
    }

**Comment by OrenMe** [comment]
@erdemguven @ojw28 any update on the matter? does @giladna's solution possible? should we open a PR?

**Comment by gamepro65** [comment]
As @erdemguven mentioned with TextRenderer I also noticed if using ClippingMediaSource while the player is playing it will continue playing and rendering captions past the clip end until it reads the last caption to finally trigger its isEnded flag.

**Comment by austin226** [comment]
> As @erdemguven mentioned with TextRenderer I also noticed if using ClippingMediaSource while the player is playing it will continue playing and rendering captions past the clip end until it reads the last caption to finally trigger its isEnded flag.

If anyone is still encountering this particular issue -- It was fixed in release 2.13.3: https://github.com/google/ExoPlayer/releases/tag/r2.13.3
