### ISSUE TITLE
Force ExoPlayer to enter the buffering state

### ISSUE THREAD

**Issue by mmbahaa** [google/ExoPlayer#3919]
How can I force ExoPlayer to enter the STATE_BUFFERING even if there's data that the renderers can render?

**Comment by erdemguven** [comment]
You can implement a custom LoadControl and return true from shouldContinueLoading() whenever you want the buffering to continue.

**Comment by mmbahaa** [comment]
I want to make the player get into BUFFERING state where it only passes when it has a specific amount of data, just like when shouldStartPlayback is called in the beginning but this time with rebuffering = true

**Comment by ojw28** [comment]
As you've probably discovered, you can configure how much media is required to exit the buffering state using `shouldStartPlayback`. There is no way to force the player to re-enter the buffering state whilst the renderers can still render. That's just not something we support, sorry.

**Comment by mmbahaa** [comment]
Ok thanks for being that clear.
