### ISSUE TITLE
How to play the DASH+PlayReady streaming on my own CDN using the demo player?

### ISSUE THREAD

**Issue by sunnite-tsar** [google/ExoPlayer#3922]
### Issue description
I edit the file 'media.exolist.json' in the demo app as following:
**********
        "name": "Super speed (PlayReady)",
        "uri": "http://playready.directtaps.net/smoothstreaming/SSWSS720H264PR/SuperSpeedway_720.ism",
        "drm_scheme": "playready"
 **********
replace uri using my own mpd or
**********
 "name": "WV: Secure SD & HD (MP4,H265)",
        "uri": "https://storage.googleapis.com/wvmedia/cenc/hevc/tears/tears.mpd",
        "drm_scheme": "widevine",
        "drm_license_url": "https://proxy.uat.widevine.com/proxy?provider=widevine_test"
**********
replace uri using my own mpd, replace drm_scheme using "playready", replace drm_license_url using my own playeady license url.

### Reproduction steps
build the demo and run on Andriod TV STB.

### Link to test content
NA

### Version of ExoPlayer being used
2..6.1

### Device(s) and version(s) of Android being used
SDMC Android TV STB

### A full bug report captured from the device
NA

**Comment by erdemguven** [comment]
Please provide a bug report using: adb bugreport

**Comment by xiaxiaotong** [comment]
I also have a problem，If may device palyReady，the exoPlayer  is supported Dash +playReady.

**Comment by ojw28** [comment]
Please see our [supported formats](http://google.github.io/ExoPlayer/supported-formats.html) page for information about what ExoPlayer supports. It's unclear what this issue is tracking. There doesn't seem to be a clear bug described, or a question that's clear enough for us to answer. Closing for now.
