### ISSUE TITLE
smooth play

### ISSUE THREAD

**Issue by RuijiePan** [google/ExoPlayer#3924]
I have many video need to play.As first video play 3000ms - 5000ms,then the second video play 2000ms - 4000ms, so I need to know the position current play and when first video play position more than 5000ms,I will seekto second video and set current time is 2000ms.It's useful but seekto need sometime to work.I want to know how can I do it can play the videos smoothly without seekto.Thanks

**Comment by tonihei** [comment]
Sounds as if you could use a [ClippingMediaSource](http://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/source/ClippingMediaSource.html) in a [concatenation](http://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/source/ConcatenatingMediaSource.html).  

For example: 
```
MediaSource mediaSource = 
  new ConcatenatingMediaSource(
    new ClippingMediaSource(firstVideoMediaSource, 3_000_000, 5_000_000),
    new ClippingMediaSource(secondVideoMediaSource, 2_000_000, 4_000_000));

**Comment by RuijiePan** [comment]
It's work, Thank!
