### ISSUE TITLE
"com.google.android.exoplayer2.source.MediaSourceEventListener " and "com.google.android.exoplayer2.source.ads.AdsMediaSource" is not found in exoplayer:r2.5.4

### ISSUE THREAD

**Issue by abvaalgit** [google/ExoPlayer#3929]
**"com.google.android.exoplayer2.source.MediaSourceEventListener ""**
and 
**com.google.android.exoplayer2.source.ads.AdsMediaSource;**

is not found in exoplayer:_r2.5.4_
****
this class is used in#  demo app that core api is existed in app..but i using lib r2.5.4
and this class not found ..where is it gone ..and  must i do what...
what is version is using in demo app

**Comment by ojw28** [comment]
You're using a version that predates either of the APIs you're trying to use. Try using the latest version (2.7.0).
