### ISSUE TITLE
Failed to resolve: com.google.android.exoplayer:exoplayer-core:r2.7.0 

### ISSUE THREAD

**Issue by 0x410c** [google/ExoPlayer#3930]
Android studio 3.0
gradle version 4.1

Unable to resolve 2.7.0 dependencies?

**Comment by FD-** [comment]
I'm not a project member, but according to the release notes, version names no longer contain the r.
`com.google.android.exoplayer:exoplayer-core:2.7.0` should work fine.

**Comment by 0x410c** [comment]
thanks brother. worked perfectly. i think they should change git readme.

**Comment by ojw28** [comment]
Which readme? It looks like we've already removed all the "r"s from the readme.
