### ISSUE TITLE
Pass DRM session id to MediaDrmCallback from DefaultDrmSession

### ISSUE THREAD

**Issue by FD-** [google/ExoPlayer#3934]
Hi,
I need to include the drm session id / scope in my key requests, so I am looking for a way to pass the session id from the `DrmSession` to the `MediaDrmCallback`.
As far as I understand the existing code, in order to implement that, I would have to:
* Create a custom `MediaDrmCallback`-like interface  that has the same methods as the existing one, except for the addition of a sessionId byte[] parameter
* Create an implementation for that new interface
* Create a custom `DrmSession` implementation that works exactly like `DefaultDrmSession` except it passes its id to the callback call
* Create a custom `DrmSessionManager` implementation that manages the custom sessions (and works exactly like `DefaultDrmSessionManager`...)

For offline license support, I'd also have to create my own implementation of `OfflineLicenseHelper` and so on.

To me, it seems overkill having to create that many custom implementations when all I actually want is a change in the `MediaDrmCallback`. I imagine this requirement isn't that uncommon.

Thus, I'm suggesting to change the `MediaDrmCallback` interface to accept the sessionId (at least) in the `executeKeyRequest` method (I only require them in the key requests, I'm not sure if there are any use cases that would require a session id in a provision request?) and adjust `DefaultDrmSession`, `DefaultDrmSessionManager` and the existing `MediaDrmCallback` implementations accordingly.

I'm willing to submit a pull request, I just wanted to hear your opinion first!

**Comment by ojw28** [comment]
Why does your `MediaDrmCallback` need the session id? Aren't session IDs just arbitrary values generated by the platform? And if so, why is knowing the value useful? What do you use it for, and if it's just for logging, why is it useful to log?

**Comment by FD-** [comment]
I'm writing this for an existing server system, so I don't have insights into the processing of the session id on the server. If you don't consider this a requirement common enough, I'd hope to see a possibility to implement it without having to create so many custom classes that are mostly copy-pastes of default classes.

**Comment by ojw28** [comment]
Until we have a concrete use case that explains why the session id is useful, I don't think we can spend any time on this. It's feels just as likely at this stage that the server doesn't do anything useful with it. Does playback still work if you generate some other random id and send that instead :)?

If you find out why the server needs the session id, please let us know and we'll take another look.

**Comment by ojw28** [comment]
Closing for now. Please let us know if you find out what the use case is.
