### ISSUE TITLE
Can not play video playlist in background mode

### ISSUE THREAD

**Issue by knighthedspi** [google/ExoPlayer#394]
Hi everyone!
I'm using ExoPlayer to implement my media player for my Android application. Now i'm facing with the new issue .When i try to play video playlist in background mode( when user tap home button , my application enters background mode, audio keeps playing and video turns off), the playlist can not be played continuos as in the normal mode!
After many investigations, i find this code in surfaceDestroyed() method
exoPlayer.blockingSendMessage(videoRenderer, MediaCodecVideoTrackRenderer.MSG_SET_SURFACE, null);
It blocks all other message event so onPlayerStateChanged method can not be called and that causes my playlist can not be played continous
Any solutions for my issue?
Any help will be greatly appreciated

**Comment by ojw28** [comment]
That doesn't sound right. Are you certain that blockingSendMessage is blocking *indefinitely*? It should only block until the message has been delivered, which shouldn't take long at all.

**Comment by knighthedspi** [comment]
blockingSendMessage is not blocking indefinitely but it block all other messages until the message has been delivered so if the set state message ( in setState() method ) is sent before this message delivered, it will be blocked, right?
After that, instead of using blockingSendMessage method , i use setRendererEnabled method and it works
exoPlayer.setRendererEnabled(HlsRendererBuilder.TYPE_VIDEO, false);
Anw, thanks for your reply!

**Comment by ojw28** [comment]
I'm still not following this. There should be two threads involved here - Your application's main thread that you're calling into ExoPlayer with and that ExoPlayer calls your ExoPlayer.Listener instance on, and ExoPlayer's internal rendering thread.

When you call blockingSendMessage from your application thread, it will block the main thread temporarily until the message is delivered and processed by the background thread. This should block the thread for no more than ~50ms or so. During this time onPlayerStateChanged wont be called, but as soon as blockingSendMessage finishes any state changes will be delivered by the player through this method.

So the only thing you should be experiencing is that sometimes player state changes are delivered up to ~50ms delayed late. That really shouldn't be causing you any problems though.

**Comment by saurabhkpatel** [comment]
@knighthedspi I am facing the same issue, above solution resolved your issue?
are you creating new ExoPlayer object when moving to next video from videoPlayList?
