### ISSUE TITLE
How to notice me when next video playback and get current playback file's URI at the same time ?

### ISSUE THREAD

**Issue by yibeiliu** [google/ExoPlayer#3943]
I try to find a listener that can notice me when the next or previous video playback.

for example: 

I have a List of uri by using *DynamicConcatenatingMediaSource* to ExoPlayer, when I click "next" button or auto play the next video, I hope to know this event and to know the current playback video's uri.

 I try to find some useful information from Demo App,but nothing.
please help me~

#### Version of ExoPlayer being used
2.6.1

**Comment by tonihei** [comment]
You can retrieve the `MediaSource` at each index in the playlist by calling `DynamicConcatenatingMediaSource.getMediaSource(index)`. Unfortunately, our media sources don't have a `.getUri()` method. To work around this you can keep a `Map<MediaSource, Uri>` or similar in your app to lookup the `Uri` from the `MediaSource`.

**Comment by yibeiliu** [comment]
Thank a lot! 

I've solved the problem as you said！
