### ISSUE TITLE
cannot resolve MediaSessionConnector

### ISSUE THREAD

**Issue by MohammadElKhatib** [google/ExoPlayer#3946]
I am using exoplayer v 2.6.1 but i am facing an issue that MediaSessionConnector is not working.

gradle exoplayer import:
    compile 'com.google.android.exoplayer:exoplayer:2.6.1'

**Comment by ojw28** [comment]
You need to also depend on `com.google.android.exoplayer:extension-mediasession:2.6.1`

**Comment by MohammadElKhatib** [comment]
@ojw28 yes you are right this was not clear in installation.
thank you
