### ISSUE TITLE
HTTPS keep-alive HttpDataSource for all HTTPS requests (Dash/HLS streaming)

### ISSUE THREAD

**Issue by hariszukanovic** [google/ExoPlayer#3947]
Is it supported to pass/reuse one HTTPS keep-alive connected HttpDataSource for all HTTP requests issued for a series of different Dash/HLS live streaming sessions? For example, while zapping through a list of live channels which all are served from the same base url...

**Comment by ojw28** [comment]
I think the underlying network stack will reuse sockets underneath the hood in this case, without you having to do anything special.

**Comment by hariszukanovic** [comment]
It sounds right. keep-alive does seem to work at a lower level.
However, when I zap, in the system I do see 3 connections active towards the same server.
My first guess would be they are different HTTP connections that are used for manifest, chunks and drm licence (all of them keep-alive but separate)

I will try to test this by creating the same HttpDataSource object and use for all of 3.

**Comment by ojw28** [comment]
`DefaultHttpDataSource` instances can only be used by one thing at once (i.e. they cannot make multiple requests at the same time). So trying to share a single instance will almost certainly cause things to break. Also, the underlying network stack will reuse sockets across different `DefaultHttpDataSource` instances anyway.

There are probably 3 connections because the player is making three requests in parallel. If you really want to try and pipeline them all to use the same socket then I think you'd have to implement a custom `DataSource` whose `open` method blocks if a request is already in flight. That kind of `DataSource` would be safe for use by multiple components, although note some requests will end up being queued behind others.

**Comment by hariszukanovic** [comment]
Thanx for your responses so far...

I'll leave out the DRM call at this point, to make it simpler... 
When not using DRM, I actually see only 2 connections towards the server. Also, I can confirm I see these 2 are keep-alive across a series of plays issued for different Dash URLs on the same server. 

My complete intention is to somehow have both keep-alive using a single TCP connection to the server and see pipelining of HTTP requests on it, but we could live without the pipelining part, for now, I'm sure :)
Perhaps I am trying to find some support for HTTP2 in Exo?

If I understand correctly, you have confirmed that to achieve this I need to use only 1 DataSource for all HTTP requests.

Now, if I should create a DataSource that supports concurrency (like you described, with blocking), can you help understand if it would be usable as such in DashMediaSource, namely the DashMediaSource seems to insist on using separate manifestDataSourceFactory and chunkSourceFactory?

The manifestDataSourceFactory is actually @Nullable but seem not work at all if I send in null.
To begin with, I was hoping that it would use the chunkSourceFactory to fetch the manifest... but...

`public Factory(
        DashChunkSource.Factory chunkSourceFactory,
        @Nullable DataSource.Factory manifestDataSourceFactory)`

**Comment by hariszukanovic** [comment]
Did not see it was closed.
Thanx

**Comment by ojw28** [comment]
You probably have demuxed audio and video chunks in your DASH content, in which case 2 connections is expected. Why would you want only one connection? I think you really want to be requesting audio and video in parallel.

To answer the questions near the end of your response, you'd just have to pass the same factory (or factories that provide the same DataSource instance) everywhere that needs one. We can't really provide further support on how to build this, unfortunately; it's not something we officially support.

**Comment by hariszukanovic** [comment]
Indeed. I have separate audio and video. Thank you for your answers
