### ISSUE TITLE
[Question] Is it bad to create/maintain large number of Renderers for a SimpleExoPlayer?

### ISSUE THREAD

**Issue by eneim** [google/ExoPlayer#3950]
This is a question.

My use case is: I want to support different DRM types using a single SimpleExoPlayer instance. The way I do is: extend DefaultRendererFactory, and feed it with more than one DrmSessionManager (so an array of size from 0 to many DrmSessionManagers). For each of that DrmSessionManager (one will support one DRM types/scheme/license url), I create an array of Video renderers (and Audio renderers) for it. In case of supporting 3 Drm types, there will be 10 Renderers in total (1 (non DRM), 3 (DRM) for Video, same 4 for Audio, 1 for Text, 1 for Meta). (The exact number may varies, but you got the point).

I read that creating Renderer is not expensive, I also acknowledge that the TrackSelector will pick the right Renderer for its track, so there will be no overlapped Renderers, but I wonder if maintaining a large number of Renderers using one SimpleExoPlayer instance is bad or not.

Thanks in advance.

**Comment by ojw28** [comment]
It's definitely unorthodox, but I can't think of any reason this would be fundamentally problematic, so if it works then go for it ;).

Another approach that might be cleaner would be to implement a `DrmSessionManager` that supports multiple DRM schemes. I wonder whether it's feasible to do this by creating a `DrmSessionManager` implementation that wraps multiple other `DrmSessionManager`s and then delegates to the one that can handle the content. That approach would probably be a lot simpler, if it works.

**Comment by eneim** [comment]
@ojw28 Oh the composition of DrmSessionManager sounds even better.

Sorry to jumping in detail, I made a quick draft as below, do you think it would work? 

Admit that I'm not super detailed in how Drm work, the order of methods calling and so on. What I concern is when many Managers involve, even if only one will support the incoming DrmInitData, I cannot make sure it will correctly behave.

```java
public class CompositeDrmSessionManager<T extends ExoMediaCrypto> implements DrmSessionManager<T> {

  private ArrayList<DrmSessionManager<T>> managers;

  // This is to cache the pair of DrmInitData and the Manager that can acquire a session for it.
  private Pair<DrmInitData, DrmSessionManager<T>> accepted;

  /** This method should only be called when prepare the Player. */
  public final void addDrmSessionManager(@NonNull DrmSessionManager<T> manager) {
    if (accepted != null) {
      throw new IllegalStateException("Cannot call this after canAcquireSession() is called");
    }

    if (this.managers == null) this.managers = new ArrayList<>();
    this.managers.add(ToroUtil.checkNotNull(manager));
  }

  /**
   * This method should only be called when prepare the Player. Maybe for managing the managers to
   * be add to final Player setup.
   */
  public final void removeDrmSessionManager(DrmSessionManager<T> manager) {
    if (this.managers == null) this.managers = new ArrayList<>();
    this.managers.remove(manager);
  }

  @Override public boolean canAcquireSession(DrmInitData drmInitData) {
    if (managers == null) return false;
    accepted = new Pair<>(null, null);
    for (DrmSessionManager<T> manager : managers) {
      if (manager.canAcquireSession(drmInitData)) {
        accepted = Pair.create(drmInitData, manager);
        break;
      }
    }

    return accepted.second != null;
  }

  @Override public DrmSession<T> acquireSession(Looper playbackLooper, DrmInitData drmInitData) {
    return accepted.second != null ? accepted.second.acquireSession(playbackLooper, drmInitData) : null;
  }

  @Override public void releaseSession(DrmSession<T> drmSession) {
    if (accepted.second != null) accepted.second.releaseSession(drmSession);
  }
}
```

**Comment by ojw28** [comment]
Only scanned it briefly:

* I think looping over the managers in `canAcquireSession` is the right approach.
* I'd have thought you'd want to do the same thing in `acquireSession` as well. Relying on `canAcquireSession` having been called first looks unnecessary and error-prone.
* I'm not sure you need the `accepted` member variable. What I do think you need is a `Map<DrmSession, DrmSessionManager>` that sessions you've returned from `acquireSession` back to the underlying manager from which they're obtained. In `releaseSession` you can use this map to find the corresponding manager to call through to. One caveat is that managers may issue the provide session multiple times. So you'll also need to reference count them to know when to remove an entry from the map. So you probably want `Map<DrmSession, Pair<Integer, DrmSessionManager>>`

Note that if done right, this approach should be flexible enough to play content containing audio and video tracks encrypted with different schemes simultaneously.

**Comment by eneim** [comment]
@ojw28 Thanks for the comment. The last one about different schemes really makes sense to me. 
Using Map was one of my first thought, though maybe keeping an 1 - 1 relationship is enough. But you are right, especially when it becomes more complicated. I think I would spend a bit more time on this Drm thing. Will close this issue for now.
