### ISSUE TITLE
Custom Extractor with FFmpeg. Is this feasible?

### ISSUE THREAD

**Issue by yibeiliu** [google/ExoPlayer#3957]
I have a user case to support some container like AVI etc... 

Exoplayer are not supported those container yet, so I think why not implement a custom extractor with FFmpegExtractor through JNI? 

Is this feasible? 

Please give me some advice for custom extractor,Thank very much!

**Comment by andrewlewis** [comment]
It's definitely possible. Giving detailed guidance on this is probably beyond the scope of this issue tracker, but as a starting point I'd recommend reading the documentation of [`Extractor`](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/extractor/Extractor.java) and the types referenced there. If you can implement an `Extractor` that uses FFmpeg then that can be used via the existing `ExtractorMediaSource`.

**Comment by ojw28** [comment]
As an additional point, if you're just looking to support one extra container, then it's probably easier just to write an `Extractor` for that container.
