### ISSUE TITLE
Is it possible to tell the ffmpeg extension to downmix to stereo?

### ISSUE THREAD

**Issue by ebr11** [google/ExoPlayer#3958]
I have examined the audio renderer implementation and cannot decipher a way to tell ffmpeg that I want everything to be output in stereo - regardless of input format.

I tried forcing an output format with 2 channels but that resulted in distorted and slow playback.

Is it possible to pass parameters of some sort to the ffmpeg decoder to tell it to only output 2 channels?

Thanks.

**Comment by andrewlewis** [comment]
Could you give a bit more detail about how you tried to force the output format to stereo? I'd expect setting `AV_CH_LAYOUT_STEREO` as the output channel layout in [ffmpeg_jni.cc](https://github.com/google/ExoPlayer/blob/release-v2/extensions/ffmpeg/src/main/jni/ffmpeg_jni.cc#L279) to work.

**Comment by ebr11** [comment]
Yes, we changed that and I also tried changing the channel count to 2 in the sample format creation.  This resulted in distorted sound and slow playback.

**Comment by andrewlewis** [comment]
This worked for me after another couple of changes: in addition to configuring the resampler to output stereo, the `bufferOutSize` calculation and `ffmpegGetChannelCount` both need to be updated to use the new output channel count (2).

I'm not sure it's worth adding support for setting the output channel count to the extension. The platform audio track should downsample multi-channel audio if required for output. If the inefficiency of decoding to multichannel then getting the output and downsampling further downstream is a concern, I think one could argue that the input media should be prepared with the right number of channels for the device in the first place. In any case, if you want this feature to be added it would be great if you could elaborate on your use case. If not, I'll close the issue. Thanks!

**Comment by ebr11** [comment]
I had done the modification to ffmpegGetChannelCount but not the one to bufferOutSize .  I'll try that.

The issue appears to only be on the Fire TV stick and, perhaps, only on the 1st gen one as that's what we tested.  On that device, multi-channel PCM is sent out when the attached equipment cannot handle it and the result is only the L/R channels playing - basically, no vocal track.

I know you will probably say that isn't a supported device anyway since it is not running true Android.  Thanks for your help.  I will see if we can make this happen on our end.

**Comment by andrewlewis** [comment]
Thanks for the info. Yes, as this isn't an Android device we won't implement a workaround. For what it's worth, I'd be surprised if we made substantial changes to this code any time soon, so maintaining a patch is unlikely to be much of a burden!
