### ISSUE TITLE
Wrong constructor in DefaultLoadControl

### ISSUE THREAD

**Issue by adrixgc** [google/ExoPlayer#3959]
### Issue description
Parameters passed in different order in DefaultLoadControl constructor with parameter DefaultAllocator.
The constructor  
```
public DefaultLoadControl(DefaultAllocator allocator) {
    this(
        allocator,
        DEFAULT_MIN_BUFFER_MS,
        DEFAULT_MAX_BUFFER_MS,
        DEFAULT_BUFFER_FOR_PLAYBACK_AFTER_REBUFFER_MS,
        DEFAULT_BUFFER_FOR_PLAYBACK_MS,
        DEFAULT_TARGET_BUFFER_BYTES,
        DEFAULT_PRIORITIZE_TIME_OVER_SIZE_THRESHOLDS);
  }
```
sets as 4th parameter `DEFAULT_BUFFER_FOR_PLAYBACK_AFTER_REBUFFER_MS` and as 5th parameter `DEFAULT_BUFFER_FOR_PLAYBACK_MS` . If you check the parameters of the constructor called with `this`
```
public DefaultLoadControl(
      DefaultAllocator allocator,
      int minBufferMs,
      int maxBufferMs,
      int bufferForPlaybackMs,
      int bufferForPlaybackAfterRebufferMs,
      int targetBufferBytes,
      boolean prioritizeTimeOverSizeThresholds) {
    this(
        allocator,
        minBufferMs,
        maxBufferMs,
        bufferForPlaybackMs,
        bufferForPlaybackAfterRebufferMs,
        targetBufferBytes,
        prioritizeTimeOverSizeThresholds,
        null);
  }
```
You can see that the 4th parameter is `bufferForPlaybackMs` and the 5th is `bufferForPlaybackAfterRebufferMs`. Therefore, a different order of parameters. First constructor is wrong.

### Version of ExoPlayer being used
2.6.1

### Device(s) and version(s) of Android being used
All

**Comment by ojw28** [comment]
It's fixed already (in 2.7.0).
