### ISSUE TITLE
Location-Tag in MPD-File, Replacing Manifest URL

### ISSUE THREAD

**Issue by stelma** [google/ExoPlayer#396]
We would like to adapt the ExoPlayer to use the Location-Tag according to DASH MPD Specification, in order to keep one session.
See as example: http://www.wowza.com/forums/content.php?508-How-to-do-MPEG-DASH-streaming#mpd_location

From taking a first look I think this should be feasible by making some slight changes to the MPD model, MPDParser.
The interesting question is where/at which point would you replace the Manifest-URL with the Session-URL?
Giving us a hint would be greatly appreciated.

**Comment by ojw28** [comment]
Regarding this issue (and pull request). Can you point to any specification documents that explain exactly how MPD.Location is supposed to be used? It's defined in ISO 23009-1, but it doesn't seem to include anything about actually using it. I'm particularly interested in relative resolution of media URLs. In the case where the MPD doesn't define a BaseURL at the top level, we currently resolve URLs relatively against connectionUrl. If an MPD.Location is defined, it's unclear whether you should resolve URLs relatively against connectionUrl or against MPD.Location.

**Comment by ojw28** [comment]
Ok, I found a bit of information in the DASH Interoperability and DVB documents:

http://dashif.org/w/2015/04/DASH-IF-IOP-v3.0.pdf
http://www.dvb.org/resources/public/standards/a168_dvb-dash.pdf

They don't say anything about using MPD.Location for resolving media URLs for the current manifest, so it looks like it should be used only for requesting the next manifest (which is what the pull request does, so I guess things are consistent!).

**Comment by stelma** [comment]
Alternatively to writing a MPD specific fetcher one could use the DashChunkSource and pass on the location-URL (from its currentManifest reference) as parameter to the ManifestFetcher.

**Comment by ojw28** [comment]
Yes. It would be nice to avoid having an MPD specific fetcher, primarily because you can equally well fetch the MPD with the general purpose fetcher. If you give people two ways of doing things, they're reasonably likely to pick the wrong one :).

**Comment by T-Pham** [comment]
@ojw28 The pull request has been updated.
Thanks for your suggestion, @stelma.

**Comment by sam2007** [comment]
Hi Guys, 

Is this feature already merged with the Master Branch?

Regards,

**Comment by ojw28** [comment]
I just merged this into the dev branch. It's not in the master branch yet; that will take a few weeks at least.

**Comment by ojw28** [comment]
I reworked this feature a little in 164d8b4242903aea3b984fc72277366418279228 and 49f4fe7810c3e049278223558422813bd4a709c4 to contain the redirection logic with ManifestFetcher. Please check it still works for you. Thanks!
