### ISSUE TITLE
problem with characters in .srt file

### ISSUE THREAD

**Issue by xoceunder** [google/ExoPlayer#3960]
![screenshot_14](https://user-images.githubusercontent.com/12431116/37129561-0013f2d8-2256-11e8-9d7e-f8e665a7db9e.png)
problem with characters in .srt file

**Comment by AquilesCanta** [comment]
This is most likely because the srt file is not encoded using utf-8. Try reencoding it and let us know whether it works. If it doesn't please provide the information requested in the issue template for us to take a better look at this. You can also find relevant information in #3869.

**Comment by xoceunder** [comment]
this my

```
                Format textFormat = Format.createTextSampleFormat(null, MimeTypes.APPLICATION_SUBRIP, Format.NO_VALUE, "en", null);
                MediaSource textMediaSource = new SingleSampleMediaSource(Uri.parse(subsURL), mediaDataSourceFactory, textFormat, C.TIME_UNSET);
                MediaSource mediaSourceWithText = new MergingMediaSource(mediaSource, textMediaSource);
                player.prepare(mediaSourceWithText, !isTimelineStatic, !isTimelineStatic);
```

and continues with the same error

**Comment by xoceunder** [comment]
[1520466818340.srt.txt](https://github.com/google/ExoPlayer/files/1796779/1520466818340.srt.txt)

**Comment by AquilesCanta** [comment]
I cannot reproduce the issue with the provide subtitles. The characters are rendered correctly.

**Comment by xoceunder** [comment]
I have problems with the characters

**Comment by AquilesCanta** [comment]
Is this the demo app? Which device and android version? Please have a look at the issue template [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE) and fill all information required there. Please don't omit any items.

**Comment by xoceunder** [comment]
version 1.6.0

**Comment by AquilesCanta** [comment]
This issue is being closed because it does not adhere to our issue template, and/or because it omits information requested in the issue template that is required for us to investigate the problem efficiently. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

If you’re able to provide complete information as requested in the issue template, please do so below and we’ll re-open the issue. Thanks!
