### ISSUE TITLE
How to switch to lower or higher variant when ever the current selected variant encountered with "Not a valid server response code".

### ISSUE THREAD

**Issue by pokuri3** [google/ExoPlayer#3964]
Whenever the current selected variant chunk returns 400 or 500 server response, Exoplayer trying to re-download at least 3 times and then throwing a playback error.
Is there any way to switch the playback variant whenever the current variant has encountered with bad server response or a corrupted chunk? Please suggested

**Comment by ojw28** [comment]
Servers probably shouldn't be providing "corrupted" chunks. They should provide valid chunks or nothing. For server response codes, we already automatically switch variant if the response code is a 404 or 410. Whether we should switch variant for other response codes is tracked by https://github.com/google/ExoPlayer/issues/2981.

**Comment by pokuri3** [comment]
Thanks @ojw28 .I verified that adding blacklist variant if the server error is 404 0r 410.By adding extra response codes solving my issue.
