### ISSUE TITLE
Is it possible to execute a .exo media file with exoplayer 2.6.1?

### ISSUE THREAD

**Issue by alineayres** [google/ExoPlayer#3965]
Is it possible to execute a media file .exo extension with exoplayer? If it is, how can I do this or is there an example in the repository?
In order to create the media source, I'm using the ExtractorMediaSource factory passing a DataSource.Factory and calling createMediaSource passing a single parameter the Uri of the source.

**Comment by erdemguven** [comment]
I guess this is an ExoPlayer cache file. If so you can playback the cached content using a CacheDataSource and use the original url of the content.

**Comment by alineayres** [comment]
@erdemguven Yes, it is an Exoplayer cache file of a media that I downloaded to my device using Exoplayer Downloader(HLS/Dash) classes. I tried to use a CacheDataSource, but the url/path I'm passing is from the internal storage. Is that supposed to work this way?

**Comment by erdemguven** [comment]
You should use the same url you used to download the content not the path to the internal storage.

**Comment by alineayres** [comment]
@erdemguven Is there an example code how to play offline a downloaded Exoplayer cache file?

**Comment by akkbo** [comment]
@alineayres 
@erdemguven show how to play download content at https://medium.com/google-exoplayer/downloading-streams-6d259eec7f95
https://gist.githubusercontent.com/erdemguven/01e029f170fdad47d032628c1a0bdcf7/raw/9ca99bf2b1270b888b142bc6bdfb2dad48029f7d/Playing%20downloaded%20content.java
