### ISSUE TITLE
onVideoSizeChanged not work

### ISSUE THREAD

**Issue by RuijiePan** [google/ExoPlayer#3970]
I have many vides need to play smooth,as first video play end auto switch to second video,but I found when the first video info such as (width = 1920, height = 1080, degrees = 0) and second video info such as (width = 1080, height = 1920, degress = 90), and then i can't get the onVideoSizeChanged() listener. So I can't update my surface rotation.  In addition, I get some information in onPositionDiscontinuity when reason is DISCONTINUITY_REASON_PERIOD_TRANSITION, but this is't synchronize with frame, so sometime will show pre video frame by rotated as second video's degree and then show the second video.may to tell what should I do if I want to rotate the video

**Comment by ojw28** [comment]
If you're not getting `onVideoSizeChanged` then it's likely we've rotated the second video for you when rendering it into the provided `Surface`. This means that as far as the app is concerned, both videos are `(width = 1920, height = 1080, degrees = 0)` and so it's correct that we haven't called `onVideoSizeChanged`.

If you're seeing an issue where the second video is not rotated, this is probably a bug where the player think it's rotated it, but actually hasn't. To investigate that we'll need the information requested in the issue template, including a full bug report captured with `adb bugreport` shortly after experiencing the issue, and two pieces of sample content that can be used to reproduce the problem.

**Comment by RuijiePan** [comment]
Issue description
I have three video.
first video : width = 1920, height = 1080, degrees = 270
second video : width = 1080, height = 1920, degrees = 0
third video : width = 1920, height = 1080, degrees = 90  
And then I play it smoothly.And I found exoplayer will rotate the video and think my three video is same width and same height, so onVideoSizeChanged() is not work.And then it will show second video rotate 90 and third video rotate 180.It is't I want because I need to rotate video.

Reproduction steps
just record three video and play it without rotate video and subscribe onVideoSizeChanged() is listener.

Version of ExoPlayer being used
exoplayer release 2.7.0

Device(s) and version(s) of Android being used
xiaomi MIX2

**Comment by ojw28** [comment]
I don't really understand the use case. If we're already rotating the video into its correct rotation, why do you also need to rotate it?

**Comment by RuijiePan** [comment]
Sorry for my poor English, You misunderstand what I said.I found

MediaCodecVideoRenderer.class line 377-394 

protected void onOutputFormatChanged(MediaCodec codec, MediaFormat outputFormat)  {
        boolean hasCrop = outputFormat.containsKey("crop-right") && outputFormat.containsKey("crop-left") && outputFormat.containsKey("crop-bottom") && outputFormat.containsKey("crop-top");
        this.currentWidth = hasCrop?outputFormat.getInteger("crop-right") - outputFormat.getInteger("crop-left") + 1:outputFormat.getInteger("width");
        this.currentHeight = hasCrop?outputFormat.getInteger("crop-bottom") - outputFormat.getInteger("crop-top") + 1:outputFormat.getInteger("height");
        this.currentPixelWidthHeightRatio = this.pendingPixelWidthHeightRatio;
        if(Util.SDK_INT >= 21) {
            if(this.pendingRotationDegrees == 90 || this.pendingRotationDegrees == 270) {
                int rotatedHeight = this.currentWidth;
                this.currentWidth = this.currentHeight;
                this.currentHeight = rotatedHeight;
                this.currentPixelWidthHeightRatio = 1.0F / this.currentPixelWidthHeightRatio;
            }
        } else {
            this.currentUnappliedRotationDegrees = this.pendingRotationDegrees;
        }
        setVideoScalingMode(codec, this.scalingMode);
    }

and line 584-593
private void maybeNotifyVideoSizeChanged() {
        if((this.currentWidth != -1 || this.currentHeight != -1) && (this.reportedWidth != this.currentWidth || this.reportedHeight != this.currentHeight || this.reportedUnappliedRotationDegrees != this.currentUnappliedRotationDegrees || this.reportedPixelWidthHeightRatio != this.currentPixelWidthHeightRatio)) {
            this.eventDispatcher.videoSizeChanged(this.currentWidth, this.currentHeight, this.currentUnappliedRotationDegrees, this.currentPixelWidthHeightRatio);
            this.reportedWidth = this.currentWidth;
            this.reportedHeight = this.currentHeight;
            this.reportedUnappliedRotationDegrees = this.currentUnappliedRotationDegrees;
            this.reportedPixelWidthHeightRatio = this.currentPixelWidthHeightRatio;
        }
    }

It's show that when degrees is 90 or 270, it will swap video width and height.So it will think width = 1080, height = 1920, degree = 0 and width = 1920, height = 1080, degree = 90 is same width and height.So onVideoSizeChanged is not work.But important is current my surface rotation is 0 when I play first video, so when it play to second video, I need to switch surface rotation to 90,but onVideoSizeChanged is not work this time so the surface rotation is incorrect.So I can't set surface rotation to 90.

**Comment by RuijiePan** [comment]
Then i try to using SimpleExoPlayerView to play the video, the rotation is correct. So I found that
when i using exoplayer.setVideoSurface(suface);  It's will not switch second video degrees correct automatically.When i using exoplayer.setTextureView(textureView). It's fine to switch degrees 
automatically. Beacuse I new to add some filter to GLsurfaceview, so I need to using surface as output.
