### ISSUE TITLE
Support lazy preparation in ConcatenatingMediaSource for long playlists

### ISSUE THREAD

**Issue by Khang-NT** [google/ExoPlayer#3972]
### Change request
I found this class is very useful `DynamicConcatenatingMediaSource.DeferredTimeline`, I think it is reusable, just like `DeferredMediaPeriod` class. Please make it public.

I need to use `DeferredTimeline` to create a class called `DeferredMediaSource`: https://gist.github.com/Khang-NT/985e12e1d73454a79a989165c9bd13fa . This class solves my problem when using `DynamicConcatenatingMediaSource`, because `DynamicConcatenatingMediaSource` prepare all child media source immediately, for instance, I have a playlist contains 100 DASH media, `DynamicConcatenatingMediaSource` will prepare/download 100 manifest file, but I just need to prepare current playing item, and prepare the next position for pre-buffering (similar with https://github.com/google/ExoPlayer/issues/3400)

### Version of ExoPlayer being used
*`2.7.0`*

**Comment by tonihei** [comment]
I think we can do this as it will also clean up some of the code in the already long `DynamicConcatenatingMediaSource` class.

More generally, the problem you are trying to solve is actually a useful feature especially for long playlists of DASH, HLS or SmoothStreaming media items where all manifests are downloaded immediately. The downside of not downloading the manifests is that the duration of the item stays unknown until you are beginning to play it. I think it would still be helpful to provide that as an option in the constructor of the DynamicConcatenatingMediaSource (which defaults to immediate child preparation). Assuming we would add such a feature, would you still need access to the DeferredTimeline class? Or would it be enough to leave it internal in this case?

**Comment by Khang-NT** [comment]
The problem above is my only use case of `DeferredTimeline`. It would be nice if `DynamicConcatenatingMediaSource` supports to solve that problem officially, then keep `DeferredTimeline` class as internal up to your design.

**Comment by Khang-NT** [comment]
`DynamicConcatenatingMediaSource` is deprecated from `2.8.0`. @tonihei, Does it support "lazy preparing" now?

**Comment by tonihei** [comment]
Not yet, sorry. It has just been merged with the existing `ConcatenatingMediaSource` because they had an almost identical feature set.

**Comment by tonihei** [comment]
Now available with the commit referenced above.
