### ISSUE TITLE
Dash - Downloaded representations sometimes don't work offline

### ISSUE THREAD

**Issue by pranit21** [google/ExoPlayer#3976]
Hi,

I am trying to download dash video using DashDownloader. There are various representations in my mpd file which I print using dashDownloader.getAllRepresentationKeys():
0.0.0 --> 240p
0.0.1 --> 360p
0.0.2 --> 480p
0.0.3 --> 540p
0.1.0 --> audio

According to the documentation, you should select any one representation. So I tried using all representations one by one. All downloaded correctly, but none was playing correctly in offline mode. Then I realised, I should also download audio representation. So I tried following combinations with different results:
0.0.0 & 0.1.0 --> downloaded but not working in offline
0.0.1 & 0.1.0 --> downloaded & working
0.0.2 & 0.1.0 --> downloaded but not working in offline
0.0.3 & 0.1.0 --> downloaded but not working in offline

I am using following url:
https://bae.sgp1.digitaloceanspaces.com/videos/118/dash/0c17f7c57b3b1b0aca48f49f9181484e.mpd

Below is my code to get MediaSource using CachedDataSource:
```
private MediaSource buildMediaSource(Uri uri) {
        File downloadFolder = getPrivateStorageDir(this, "10");
        SimpleCache cache = new SimpleCache(downloadFolder, new NoOpCacheEvictor());
        DefaultHttpDataSourceFactory factory = new DefaultHttpDataSourceFactory(Util.getUserAgent(this, "BAE"), null);

           return new DashMediaSource.Factory(
                    new DefaultDashChunkSource.Factory(new CacheDataSourceFactory(cache, factory, CacheDataSource.FLAG_BLOCK_ON_CACHE)),
                    buildCacheDataSourceFactory(cache)
            ).createMediaSource(uri);
    }

private DataSource.Factory buildCacheDataSourceFactory(SimpleCache cache) {
        return ((AppController) getApplication())
                .buildCacheDataSourceFactory(cache);
    }
```

In AppController.java
```
public DataSource.Factory buildCacheDataSourceFactory(SimpleCache cache) {
        return new CacheDataSourceFactory(cache, buildHttpDataSourceFactory(null), CacheDataSource.FLAG_BLOCK_ON_CACHE);
    }
```

For some videos it is working, but for some videos it is not. If I download all the representations, then it works perfectly. But that is not the solution.
Why is the behaviour different for different representations? Any help would be appreciated. Thanks!

**Comment by erdemguven** [comment]
You need to either force just the downloaded representation tracks to be selected or use DashManifest.copy() to create a copy of the manifest which only contains the downloaded representations.

**Comment by pranit21** [comment]
@erdemguven,

Thanks for the solution! I will try this and let you know.

**Comment by pranit21** [comment]
Hi @erdemguven,

Thank you so much! By forcing track to the downloaded representation solved my problem! Thanks a lot!
