### ISSUE TITLE
[Question] Can I force the security level down?

### ISSUE THREAD

**Issue by sophia-podo** [google/ExoPlayer#3979]
Hi,

I found the isL1WidevineAvailable() function at DashTestRunner.java.
(https://github.com/google/ExoPlayer/blob/eb9c67fbc58e4a9bf4f17580e988ab321752e364/playbacktests/src/androidTest/java/com/google/android/exoplayer2/playbacktests/gts/DashTestRunner.java#L111)
In DashTestRunner.java, If this function returns false, mediaDrm.setPropertyString(“securityLevel”, “L3") is called before mediaDrm.getKeyRequest().
(I found this code in DashTestRunner.DashHostedTest.buildDrmSessionManager() )

In some devices which guess L1 device, this function(isL1WidevineAvailable()) with “video/mp4” MIME parameter returns false. So the security level of the device is forced down.

1.Is it correct to change the Security Level according to the isL1WidevineAvailable return value?

2.What is Secure Decoder?
Is it determined by hardware? Or can it be improved with software updates or codec updates?

**Comment by AquilesCanta** [comment]
> Is it correct to change the Security Level according to the isL1WidevineAvailable return value?

Briefly explained, DRM protected content requires a specific security level. In general (not a requirement), if DRM protected, sub-HD requires L3, and HD and above requires L1. If the required level is not available, then it is not possible to play the content on the device, and there is nothing the app can do about it.

> What is Secure Decoder? Is it determined by hardware? 

You can find useful information [here](https://storage.googleapis.com/wvdocs/Widevine_DRM_Architecture_Overview.pdf). Higher levels of security require trusted execution environments, which usually involve dedicated hardware implementations.

Hope this answers your question. This probably falls outside the scope of this issue tracker, so I think a general Q&A site might be more suitable for general android questions.
