### ISSUE TITLE
How to listen video position

### ISSUE THREAD

**Issue by orhunkupeli7** [google/ExoPlayer#3980]
I'm using ExoPlayer 2.7.0 and I would like to listen player position in order to take actions. I couldn't find specific method for it. Could you please suggest me a proper solution?

Thanks

**Comment by tonihei** [comment]
You can query `player.getCurrentPosition()` as often as you like. The position is updated all the time, thus we can't send repeated updates in a callback. The progress bar in our UI module, for example, is updated by posting a message every 200ms.

**Comment by orhunkupeli7** [comment]
So, it is okay that to listen it with a handler.

**Comment by tonihei** [comment]
Yes, that's certainly possible.

**Comment by meikaiss** [comment]
Why not provide onProgressChangedListener?  handler is Very troublesome.

**Comment by tonihei** [comment]
The problem with a onProgressChangedListener is that the position changes about every 10 milliseconds. Sending such a huge amount of callbacks would use much more CPU time (and thus battery) than polling the progress infrequently. Most progress bars don't have a resolution which would allow you to show a 10ms difference either, thus it also wouldn't make sense for most purposes. 

Also, using a handler is not that troublesome:
```
public class ProgressTracker implements Runnable {
  
  private final Player player;
  private final Handler handler;

  public void ProgressTracker(Player player) {
    this.player = player;
    handler = new Handler();
    handler.post(this);
  }

  public void run() {
    long currentPosition = player.getCurrentPosition();
    handler.postDelayed(this, 200 /* ms */);
  }
}

**Comment by orhunkupeli7** [comment]
public class ProgressTracker implements Runnable {

    private final Player player;
    private final Handler handler;
    private PositionListener positionListener;
    private final static int DELAY_MS = 1000;

    protected ProgressTracker(Player player, PositionListener positionListener) {
        this.player = player;
        this.positionListener = positionListener;
        handler = new Handler();
        handler.post(this);
    }

    public void run() {
        int position = (int) player.getCurrentPosition();
        Log.e("Position::", String.valueOf(player.getCurrentPosition()));
        positionListener.progress(position);
        handler.postDelayed(this, DELAY_MS);
    }

    protected void purgeHandler() {
        handler.removeCallbacks(this);
    }
}

I did like that. However output of the log is:
24358
24358
25088
25088
25357
25368
26088

Why there are duplicates how can I get rid of them

**Comment by tonihei** [comment]
I guess because either the position hasn't changed (for example while buffering) or you have multiple active ProgressTrackers. 

In general, please direct these more generic programming question to StackOverflow or similar sites. This issue tracker is primarily for answering ExoPlayer specific questions.

**Comment by orhunkupeli7** [comment]
thanks, sorry for inconvenience.

**Comment by tonihei** [comment]
Closing because question seems to be answered. Feel free to reopen if not.
