### ISSUE TITLE
MergingMediaSource merge two LoopingMediaSource

### ISSUE THREAD

**Issue by feelfreelinux** [google/ExoPlayer#3982]
### Issue description
Is there option to merge two `LoopingMediaSources`? In my app I want to merge looped audio mediasource of different duration than looped video mediasource. How can I merge these two mediasources together?
### Reproduction steps
Create video and audio `LoopedMediaSource`, try to merge it with `MergingMediaSource` - results with video and audio stopping at end of the video.

**Comment by ojw28** [comment]
This is not supported.

It should be possible for you to achieve what you want with two separate player instances, one for audio and one for video, and a bit of co-ordination in your app code to start them both at the same time. You wont get completely accurate A/V sync with this approach, but the fact your audio is a different duration and loops implies you're not concerned about A/V sync anyway.
