### ISSUE TITLE
DASH cache options

### ISSUE THREAD

**Issue by 0c6a183d** [google/ExoPlayer#3984]
Hi. Quick question.

My App uses Exoplayer to play static content via adaptive bitrate dash audio. All works fine.

Are there cache options available where the player queries the cache prior to downloading each chunk?

A large portion of users listen to a track multiple times, it would be great if a portion of those chunk requests were fulfilled by their local cache.

I am aware that the whole stream can now be downloaded in full, but I am just interested in a basic cache that is transparent to the user and makes a few data savings for the client and server. The stream is running over https if that makes any difference?

I am aware of okhttp but would like confirmation that it is the correct path to be taking. If it is, is there a clear example somewhere, as I can only find dated and vague info?

Thanks for your time :-)

**Comment by erdemguven** [comment]
You need to use CacheDataSource with a Cache instance. Downloaders use Cache at the background as well.
