### ISSUE TITLE
Question: Display media subtitle using LeanbackPlayerAdapter 2.7.0

### ISSUE THREAD

**Issue by fadzleyhud** [google/ExoPlayer#3985]
Hi, 
I'm developing an android tv app using leanback with exoplayer 2.7.0. Everything working fine but how to display video subtitle if I use leanbackplayeradapter? Tq

**Comment by fadzleyhud** [comment]
Nevermind. For anybody curious how to do this, add exoplayer SubtitleView in your VideoFragment activity layout. Then pass the view to LeanbackPlayerAdapter, inside the adapter create new Listener implements TextOutput, initialize it like componentListener. 

onAttach and detach

    @Override
    public void onAttachedToHost(PlaybackGlueHost host) {
        if (host instanceof SurfaceHolderGlueHost) {
            surfaceHolderGlueHost = ((SurfaceHolderGlueHost) host);
            surfaceHolderGlueHost.setSurfaceHolderCallback(componentListener);
        }
        notifyStateChanged();
        player.addListener(componentListener);
        Player.VideoComponent videoComponent = player.getVideoComponent();
        Player.TextComponent textComponent = player.getTextComponent(); //add this
        if (videoComponent != null) {
            videoComponent.addVideoListener(componentListener);
        }
       //add the code below
        if (textComponent != null){
            textComponent.addTextOutput(textComponentListener);
        }
    }

    @Override
    public void onDetachedFromHost() {
        player.removeListener(componentListener);
        Player.VideoComponent videoComponent = player.getVideoComponent();
        Player.TextComponent textComponent = player.getTextComponent();// add this
        if (videoComponent != null) {
            videoComponent.removeVideoListener(componentListener);
        }
        //add this also
        if (textComponent != null){
            textComponent.removeTextOutput(textComponentListener);
        }

        if (surfaceHolderGlueHost != null) {
            surfaceHolderGlueHost.setSurfaceHolderCallback(null);
            surfaceHolderGlueHost = null;
        }
        hasSurface = false;
        Callback callback = getCallback();
        callback.onBufferingStateChanged(this, false);
        callback.onPlayStateChanged(this);
        maybeNotifyPreparedStateChanged(callback);
    }

and inside the listener at onCues add the SubtitleView you pass into the adapter

        @Override
        public void onCues(List<Cue> cues) {
            if (subtitleView != null){
                subtitleView.setCues(cues);
            }
        }

That's it. Thanks

**Comment by cgarcia55** [comment]
could you upload an example, I tried to follow the instructions but without success

**Comment by pjmdr11** [comment]
Can you provide an example. I am stuck in this as well
