### ISSUE TITLE
Can't import the project

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [google/ExoPlayer#399]
I keep getting this dialog:

![untitled20150418121028](https://cloud.githubusercontent.com/assets/5357526/7214794/fa5c18c4-e5c3-11e4-94d3-7d40bfc1055e.png)

How can I handle this correctly?

**Comment by ojw28** [comment]
It seems unlikely this is a library issue, unless it's specific to this library and importing any other project works. StackOverflow or some Android Studio resource is probably a better place to ask this question.

**Comment by AndroidDeveloperLB** [comment]
StackOverflow is used for asking how to import third party libraries, and Android-Studio is about issues and suggestions for general developing.
I'm asking about this library. How come I can't import it?

**Comment by ojw28** [comment]
There's no real distinction between a third party library and this one, for the purposes of asking a question. What I'm really saying is (a) I don't know because it works for me, and (b) you're much likely to get an answer if you ask on StackOverflow and pose it as a general "can't import project" problem, since there's a bigger footfall of people there.

It feels unlikely to be a problem with the project, since as far as I know no-one else has encountered this issue.

Probably also worth looking at what the IDE log actually says, seeing as that's what the error message suggests you do.

**Comment by AndroidDeveloperLB** [comment]
But I have no issue importing other projects too, so it has to be something here

**Comment by ojw28** [comment]
At least look in the IDE log to see what actually failed. Just saying it must be an issue here isn't actually going to help anyone answer the question.

**Comment by AndroidDeveloperLB** [comment]
I don't see any Help->show logs menu.
Only thing I see is Help->show logs in explorer.
I went there, and since I wanted to see what's really going on, I've deleted all temp files there, opened AS, imported the project, and.... Now it works ?! How could it be?

Anyway, now that the demo works, I'd like to ask some questions:
1. How come some of the videos don't play well (sometimes can't play, sometimes play audio, sometimes have glitches, sometimes always on paused mode) ? 
2. Does the demo shows the customizability of the library? I've read somewhere that drawing on the video is easier. Is that correct?

**Comment by ojw28** [comment]
- Most likely one of dependencies required a server that was temporarily unavailable, would be my guess.
- The first question is so generic that it's not possible to answer. You need to file a specific issue that says exactly what you're seeing, on what media, and on what device. Ideally with logs. There are brief pauses on resolution switching on some videos if the device doesn't have an adaptive decoder. If you don't want that, you'd need to configure to not resolution switch.
- The demo app provides a base that you could modify to suit your needs. It is easy to customize if you dig around a bit and figure out how things work.

**Comment by AndroidDeveloperLB** [comment]
1. ok, here's some more info:
Device: SGS3 I9300 . Rom: CM12.1-20150419 Android 5.1
videos with issue:
"Super speed(PlayReady)" - says the device doesn't support it.
"Apple AAC media playlist" and "Apple AAC 10s"- plays only audio, but I think AAC is just audio, so it's probably not an issue at all.
"Dizzy" and "Dizzy (https->http redirect)"- says it's ready, but doesn't play. It's just stuck on the video frame of the cat. I can skip frames, but it's always on paused mode.
Youtube-webM dash - "Google Glass" - has weird glitches at the bottom.

The rest just took some time so I was too impatient and thought they didn't work (just needed some time to buffer). 

2. it shows how to play videos from various sources?
