### ISSUE TITLE
Cannot use SimpleExoPlayerView nor PlaybackControlView in an existing UI

### ISSUE THREAD

**Issue by franklink** [google/ExoPlayer#3990]
Currently using ExoPlayer version 2.6.1 in my project.

I am unable to use SimpleExoPlayerView nor PlaybackControlView in my application's layout file. Neither will ever be shown and, to my knowledge, they are completely useless as an extensible view library. 

I have tried to implement these views in my app as well as in a sample app I created just to reproduce the issue. In no way are either of these inherited views able to be displayed in my app. I am using a CoordinatorLayout surrounding a FrameLayout as well as 3rd party bottom bar library.

Every time I attempt to implement the entire SimpleExoPlayerView into my layout it will take over the entire view even if I set the height to layout-height to 0dp. 

Attempting to implement PlaybackControlView only (which is my desired result) will result in nothing being displayed whatsoever. 

I would like to know how I can implement a customized PlaybackControlView as part of an already existing layout because I cannot seem to figure out how this is accomplished. If that isn't an option, I would like to be guided to the way one can implement a SimpleExoPlayerView which has only the controls view and no video/content view (I have an audio only app).

I will be happy to supply a layout xml file if this will help in the resolution of this issue. I just wanted to make it easy and assign my player to a custom playback control view. I hope this is possible or else I've wasted quite a bit of time.

Thanks

**Comment by ojw28** [comment]
* Prior to 2.7.0 you need to call `show()` on `PlaybackControlView` to make it visible when using it as a standalone component. This was fixed in https://github.com/google/ExoPlayer/commit/fd10a3cbb02ab41ef643e9cced40140bb79c6c1b. You also need to call `setShowTimeoutMs(0)` to prevent it from being hidden again, assuming you're wanting it to remain visible.
* No idea about the `SimpleExoPlayerView` issue. You'll need to provide access to a simple sample app if you want us to take a look.

**Comment by eneim** [comment]
@franklink A demo layout xml that produce the issue may help?

**Comment by franklink** [comment]
Thanks, @ojw28. I was pulling my hair out over that one because the SimpleExoPlayerView will show controls once a player is set (and maybe playing). I assumed this was the same for PlaybackControlView. That's what I get for assuming. I'm showing the playback controls now. I am going to be supplying my own custom playback controls layout so I'll try that next.
