### ISSUE TITLE
Exoplayer sequence for interacting with Widevine License Proxy Server

### ISSUE THREAD

**Issue by ottbasics** [google/ExoPlayer#3992]
Hi, this is a question and not an issue.

I am writing code to play a Widevine encrypted DASH content, through a Proxy License server which is used for authentication and authorization.

I went through the Exoplayer demo application (where direct License server is used) and understood the following sequence:
1. Create DrmSessionManager using the url of the Widevine License server.
2. Associate this session manager with an instance of SimpleExoPlayer.
3.  Then call player.prepare() and player.start().

I wanted to understand how would this sequence change, in case of Proxy License Server, where the Application first obtains the license from the server and then sets the license explicitly to the ExoPlayer.

I also wanted to understand:
- how to obtain the drmInitData required to be passed in the mediaDrm.getKeyRequest().
- how to set the License into ExoMediaDrm object.

Should I extend DefaultDrmSessionManager, or should I extend DefaultDrmSession?

Do we have any code samples for the same?

**Comment by linhai326** [comment]
i think all you need to do is to override MediaDrmCallback.executeKeyRequest().
in this function, you will send the request to your proxy server and receive the response and then return it.
The rest should be handled by exoplayer.
