### ISSUE TITLE
Making my own ABR algorithm in HLS

### ISSUE THREAD

**Issue by tedKim5178** [google/ExoPlayer#3993]
Hello,

I am making my own ABR algorithm class in HLS extended from BaseTrackSelection and I am facing with a problem. I need targetDuration in my class but there is no way I can get the information from the application level. Plus, I am making my own LoadController, and it needs bitrate information. In this case, is there simple way that I can pass these information to my class in application level?(like PlayerActivity) 

Thank you

**Comment by AquilesCanta** [comment]
`Player.EventListener#onTimelineChanged`  includes the manifest as one of the arguments. An `HlsManifest` includes a media playlist as one of its fields. Finally, HlsMediaPlaylist contains targetDurationUs. Hope this helps.

**Comment by AquilesCanta** [comment]
Sorry, I missed the bitrate part. Could you clarify the usecase for the bitrate? You can use the media source event listener to get load events to retrieve certain information. The master playlist will also include useful information (also obtainable through onTimelineChanged).

**Comment by tedKim5178** [comment]
Thanks for your reply. You solved my problem perfectly. Now I am using onTimelineChanged method to get targetDurationUs. Also, I found out onTrackSelected method in LoadControl. I can use this method to get bitrate. Thanks for your help!! Best Player ever!
