### ISSUE TITLE
Add callback for volume change

### ISSUE THREAD

**Issue by eneim** [google/ExoPlayer#3994]
I'm on ExoPlayer 2.7.0, this is kind of a feature request (if it is not there yet).

There is volume setting on ``SimpleExoPlayer`` and lower level, but I could not find a place where a successful or failure Volume update could be 'listened' to. Can this be added to the library, or how can I make it by my own, in a recommended way?

Thanks.

**Comment by botaydotcom** [comment]
Hi @eneim,
Could you please clarify your use-case here, or the issue you are facing with this?

I believe even though `setVolume()` is asynchronous, the delay is very small in most cases. Moreover, most of the time the call will succeed.
Are you trying to check when the call takes effect, or whether the call succeed?

**Comment by eneim** [comment]
Hi @botaydotcom , my use case is: I would like to implement custom PlayerControlView with Volume control. The actual volume setting can be set from anywhere out side of the View and the View will reactively update Volume position base on that setting. 

Another use case is to have consistent Volume value for a playback. Saying I have a database to store User config, I want to save/restore the Volume value as well.

I know that having traditional setter/getter should work as well, but this will ask for a code base where DB, UI and Business logic to be on the same layer, which doesn't sound well always.

**Comment by ojw28** [comment]
Implemented in `dev-v2`.
