### ISSUE TITLE
Identifying bottlenecks MPEG-TS/UDP

### ISSUE THREAD

**Issue by boulaycote** [google/ExoPlayer#3995]
Hi,

I'm back working on [this project (issue #2300)](https://github.com/google/ExoPlayer/issues/2300) and I want to make sure I fully use the advantages of temporal redundancy. That means making the I-frame a normal value and eliminating the blocking and tearing this causes.

I am not sure how to proceed on identifying bottlenecks, wether it be the network, extractors, readers, etc. Can I enable a tracing of some sort?

I have moved to ExoPlayer `2.7.1` added a `UDPDataSource` and got everything working back as it was. The synchronization part is already done. I am just trying to have a better looking image.

Here is the media I'm trying to play:

- UHD or HD (I can configure this)
- Any bitrate (configurable too)
- MPEG-TS/UDP over Ethernet
- I had to add `FLAG_DETECT_ACCESS_UNITS` to the TS Extractor to display the media

I read in the docs that without DAUs the TS extractor is slower, since I have access to the source can I make the extractor faster by hardcoding some values?

Weird thing is, CPU usage is quite low (under 20%) so I'm not sure what is causing the issues really. Network layer, but I don't see any buffering occurring..?

**Comment by andrewlewis** [comment]
- In general, if a video packet is dropped or isn't in order you will see error concealment artifacts from the decoder until the next synchronization sample (e.g., IDR frame). There isn't much you can do about this, except for switching to a reliable protocol. I'd guess that the overhead won't be too bad if there's a good wired ethernet connection to the server.
- Regarding bottlenecks: there is some tracing code in ExoPlayer for use with [systrace](https://developer.android.com/studio/command-line/systrace.html), but I'm not sure if this will be useful for you. What is the actual observable problem you're seeing?
- If the goal is to increase the picture quality can you just increase the bitrate of the video stream?
- Regarding detecting access units: you can make the operation of `TsExtractor`/`H264Reader` slightly cheaper by not enabling this flag and instead including access unit delimiters in your stream, but there's not much point unless the efficiency of parsing the stream is an issue.

**Comment by boulaycote** [comment]
Here's the observable problem:
In this image there is noticeable blocking
<img width="250" alt="screen shot 2018-03-16 at 11 34 42" src="https://user-images.githubusercontent.com/924077/37529738-41cbaeaa-290e-11e8-8657-b00c8b46f353.png">
And in this one it looks like two scenes are overlapping
<img width="250" alt="screen shot 2018-03-16 at 11 38 23" src="https://user-images.githubusercontent.com/924077/37529869-9bc3af5c-290e-11e8-9123-ef0f6e03f181.png">
There is also this error message coming from the decoder that seems to coincide with artifacts on the screen:
`E awplayer: <H264DecodeSliceHeader:1755>: here1: the first slice of the frame is not 0`
A quick search suggests [this code](https://github.com/allwinner-zh/media-codec/blob/a912bbe300d522e199001bd903bab22e54eff37b/sunxi-cedarx/SOURCE/plugin/vdecoder/h264/h264_nalu.c#L1538) from allwinner may have a similar structure, maybe there's a bug in the codec?

Increasing the bitrate makes these issues appear more, that's why my guess was there's a performance issue making it harder to decode the more data is streamed.

None of these issues happen when reading the stream from my laptop, ruling out the stream being problematic, no?

**Comment by AquilesCanta** [comment]
Are you aware of any discontinuities being detected by the TsExtractor? You could log them at [this point](https://github.com/google/ExoPlayer/blob/r2.7.0/library/core/src/main/java/com/google/android/exoplayer2/extractor/ts/TsExtractor.java#L292).

**Comment by boulaycote** [comment]
That depends on the TsMode doesn't it? I'm not sure which one to choose however, 
`MODE_SINGLE_PMT`, `MODE_MULTI_PMT` or `MODE_HLS`.

On both `SINGLE_PMT` and `MULTI_PMT` I indeed see discontinuities.

**Comment by AquilesCanta** [comment]
You shouldn't change the mode, it will not fix the issue. The distortions you are observing are due to the discontinuities in the packets (loss of order or dropped packets), which are in turn caused by the use of an unreliable transport protocol. The fix would be to make sure that the packets are fed to the extractor in the correct order.

**Comment by boulaycote** [comment]
Right. So then if on my laptop the stream is flawless, that suggests networking on the android device is problematic?

**Comment by andrewlewis** [comment]
@boulaycote is there anything actionable for us here? If so, I'll reopen this issue.

It looks like the distortion is caused by packets getting dropped/reordered and the decoder concealing the decoding errors resulting from this. A possible fix would be to switch to a reliable protocol or use some other kind of error correction.

**Comment by boulaycote** [comment]
@andrewlewis There is no packet loss on the laptop (checked with vlc). I don't understand why an android device is not able to display the same stream without issues. Or is vlc error correction better? Is it device performance? Network throughput of 10/100 too low?

**Comment by andrewlewis** [comment]
Unsure. I'd probably try dumping information on packets being read by ExoPlayer and compare this with what the laptop is receiving, to confirm that the corruption is definitely being caused by dropped or out-of-order packets.

**Comment by boulaycote** [comment]
Right. Weird thing is, the stream now is set at 19 mbps which is pretty high. Suggesting very high throughput, i-frame is still at 1 however. When I get back on the project, I'll come back here and report.

**Comment by AquilesCanta** [comment]
We can probably do a lot to improve our support for lossy streams, but unfortunately we don't have the bandwidth to dedicate exclusively to this right now. Of course, any contributions are welcome. It might be worth seeing if we can learn anything from VLC.
