### ISSUE TITLE
Videos stop being rendered after a few hours on specific Sony Bravia model.

### ISSUE THREAD

**Issue by directable** [google/ExoPlayer#3997]
### Issue description
We have an application that goes through the entire Create/Destruct cycle for PlayerView and Player for each video we play. We have noticed that after running this for a few hours or so, the Sony Bravia (SVP-DTV15, BRAVIA 4K 2015, Sony, 24, Android 7 )(recently updated to android 7) stops rendering videos and exoplayer gives an exception. We believe there is some sort of memory leak in the Sony media.codec process implementation (or the way Exoplayer uses it) as its memory use continues to grow. We don't see this problem on other devices. Sony recently upgraded the os for this device. 
SVP-DTV15, BRAVIA 4K 2015, Sony, 24 is what exoplayer reports.  We have included a sample app (emailed to dev.exoplayer@gmail.com) alias. We were hoping you could offer a workaround if there is one.

 Some random observations

-	Once the demo app stops showing videos, you can see the error as well as exoplayer exception in logcat.
-	Once the demo app stops displaying the 2 videos, force stopping the demo app and starting the youtube app fails to show videos.
-	The media.codec service continues to grow in memory
-	A Recent (feb 1st) commit, updated exoplayer to use getInput/OutputBuffer APIs if on API 21+. Not sure if this exposes some issue on the Sony Implementation of this code. The code runs fine on a Nexus Player with Android 8 so we don’t believe its an exoplayer issue but hoping for a workaround.

We ran all the runtime tests and they all pass, although it doesn't appear that any of them stress test the device the way we do.  It may be worth considering adding some stress tests to the current runtime tests.

Here is what we see in logcat:
```
03-12 18:44:13.795  6836 27854 E ExoPlayerImplInternal: Renderer error.
03-12 18:44:13.795  6836 27854 E ExoPlayerImplInternal: com.google.android.exoplayer2.ExoPlaybackException
03-12 18:44:13.795  6836 27854 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.throwDecoderInitError(MediaCodecRenderer.java:420)
03-12 18:44:13.795  6836 27854 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:407)
03-12 18:44:13.795  6836 27854 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:898)
03-12 18:44:13.795  6836 27854 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:469)
03-12 18:44:13.795  6836 27854 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:551)
03-12 18:44:13.795  6836 27854 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:518)
03-12 18:44:13.795  6836 27854 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:301)
03-12 18:44:13.795  6836 27854 E ExoPlayerImplInternal: 	at android.os.Handler.dispatchMessage(Handler.java:98)
03-12 18:44:13.795  6836 27854 E ExoPlayerImplInternal: 	at android.os.Looper.loop(Looper.java:154)
03-12 18:44:13.795  6836 27854 E ExoPlayerImplInternal: 	at android.os.HandlerThread.run(HandlerThread.java:61)
03-12 18:44:13.795  6836 27854 E ExoPlayerImplInternal: Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.MTK.VIDEO.DECODER.AVC, Format(1, null, video/avc, -1, null, [1920, 1080, -1.0], [-1, -1])
03-12 18:44:13.795  6836 27854 E ExoPlayerImplInternal: 	... 9 more
03-12 18:44:13.795  6836 27854 E ExoPlayerImplInternal: Caused by: android.media.MediaCodec$CodecException: Error 0x80001001
03-12 18:44:13.795  6836 27854 E ExoPlayerImplInternal: 	at android.media.MediaCodec.native_configure(Native Method)
03-12 18:44:13.795  6836 27854 E ExoPlayerImplInternal: 	at android.media.MediaCodec.configure(MediaCodec.java:1882)
03-12 18:44:13.795  6836 27854 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.configureCodec(MediaCodecVideoRenderer.java:428)
03-12 18:44:13.795  6836 27854 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:397)
03-12 18:44:13.795  6836 27854 E ExoPlayerImplInternal: 	... 8 more
```

### Reproduction steps
We have a demo app that i have provided that downloads 2 videos and simply alternates between the two videos.  I have emailed the project and debug apk to the dev alias. If you install and run it, you just have to wait the first time for it to download the 2 sample videos locally, once downloaded it continues to play them on 2 second intervals. The code of interest is in MainActivity.java , On this particular model of Bravia, after 2.5 to 3 hours you start to see the problem. Note a full reboot of the TV is needed to be able to play videos again.

### Link to test content
emailed sample app source and debug apk to dev.exoplayer@gmail.com

### Version of ExoPlayer being used
2.7.1

### Device(s) and version(s) of Android being used
SVP-DTV15, BRAVIA 4K 2015, Sony, 24, Android 7

### A full bug report captured from the device
Have emailed to dev alias of dev.exoplayer@gmail.com using a subject in the format "Issue #1234".

**Comment by directable** [comment]
Sony updated the OS on this. We are still seeing the problem but now it  can take a couple days to see the problem. This morning the TV was locked up so hard i had to pull the power on it. I was curious if you had a timeline on [#3948](https://github.com/google/ExoPlayer/issues/3948) regarding keeping system codecs etc, as that may solve our problem? 

thanks

**Comment by ojw28** [comment]
Better codec re-use will land in 2.10, and is available now on the `dev-v2` branch. You should avoid calling `stop` on the player between playing one video and the next, and pass the next video to the existing player instance by calling `prepare`.

Other than that, I think we can close this as a device specific issue not under our control. Hopefully Sony will continue to make stability improvements with future updates.
