### ISSUE TITLE
Unable to play 3gp

### ISSUE THREAD

**Issue by James2516** [google/ExoPlayer#3999]
### Issue description
I'm not able to play a `.3gp` audio recorded with `AMR_WB`, it throws the following error:
> com.google.android.exoplayer2.source.ExtractorMediaSource$UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor) could read the stream.

None of the above extractors is related to `3gp` or `awb`?

### Reproduction steps
https://snack.expo.io/B1Q6Li9FM

Source where `com.google.android.exoplayer2` is used: 
[SimpleExoPlayerData.java](https://github.com/expo/expo/blob/2a4739f6224919ec4e913d45cc7c2448747ebb18/android/expoview/src/main/java/versioned/host/exp/exponent/modules/api/av/player/SimpleExoPlayerData.java) and [SharedCookiesDataSourceFactory.java](https://github.com/expo/expo/blob/cae1534ba2fa20451a14d4237d87252e6a17b0c2/android/expoview/src/main/java/versioned/host/exp/exponent/modules/api/av/player/SharedCookiesDataSourceFactory.java)

### Device(s) and version(s) of Android being used
Samsung S8, Android 7.0
Nexus 5X API 26 Simulator

**Comment by AquilesCanta** [comment]
ExoPlayer does not provide support for 3GP. A link to sample content would be useful for someone to add support.

**Comment by AquilesCanta** [comment]
Actually, the mp4 extractor does check for 3gp in the ftyp box. So what we need is to look at the content.

**Comment by ojw28** [comment]
@James2516 - Please could you provide a link to a piece of test content that reproduces this issue? Or email one as an attachment to `dev.exoplayer@gmail.com`? Thanks.

**Comment by James2516** [comment]
Here's a sample `.3gp` audio file: https://files.fm/u/x7j8d4ez
Let me know if you require anything else!

**Comment by ojw28** [comment]
This file doesn't use the 3GP container. It's just an AMR file, which are not currently supported. Providing support is tracked by https://github.com/google/ExoPlayer/issues/2527.
