### ISSUE TITLE
Crash on ACoded while playing HLS

### ISSUE THREAD

**Issue by krok55** [google/ExoPlayer#400]
Hi,

I keep getting this issue while playing multi-variant HLS.
This is what I see in the log:

04-19 03:05:34.021: E/AudioTrack(2309): Discontinuity detected [expected 158885167, got 155903833]
04-19 03:05:37.561: A/ACodec(2309): frameworks/av/media/libstagefright/ACodec.cpp:741 CHECK_NE( (int)info->mStatus,(int)BufferInfo::OWNED_BY_DOWNSTREAM) failed: 3 vs. 3
04-19 03:05:37.561: A/libc(2309): Fatal signal 11 (SIGSEGV) at 0xdeadbaad (code=1), thread 2360 (MediaCodec_loop)

Please tell me what other info you need for debug.

Thanks.

**Comment by krok55** [comment]
Have more information on this:
It seems that the problem happens only when switching between variants.
When disabling the adaptive mode or when setting a very high boundary for changing variants, the problem doesn't occur.
I would like to try and fix this issue, but it would really help if you can guide me towards the relevant piece of code.

Thanks

**Comment by krok55** [comment]
Anyone please?

**Comment by ptran-gpfw** [comment]
I've seen a similar OWNED_BY_DOWNSTREAM error when I was using MediaCodec before ExoPlayer existed. What device and OS are you using? Custom ROM? I've seen codec reconfig issues when using non-stock ROM>

**Comment by krok55** [comment]
Hi,
I have two android mini-tv boxes: one is CX-919 with 4.2.2 "stock" ROM, the other one is MK808 with 4.1.
The problem happens on both devices with the same scenario, but with different symptoms:
On CX-919 you see the crash above, while on MK808 I see strange rendering artifacts (like split screen and snow during playback).
The scenario is always the same: use a multi-variant  HLS source (for example 0,1,2 - where 0 is the best-quality) and wait until a situation where ExoPlayer decided to switch from a lower-quality source to a higher one. 
I've also added some printings in HlsChuckSource::getChunkOperation() and I noticed that in the given scenario the player simply "ignores" higher quality chunks, and crashes (on Acodec) while reaching to the last chunk of the lower-quality sample.
I'm starting to suspect that maybe the higher-quality sample isn't perfectly aligned with the lower one.
For example: if the "lower" chunk contains video from 0 to 6000000us, then the "higher" one doesn't continue the video smoothly at 6000000us...
I really want to understand how to smooth-transition between different variants is designed to work, so I will be able to try to dig-in deeper in to this...

Any thought on this?

Thanks.

**Comment by krok55** [comment]
OK, I think I found a workaround.
The problem seems to be in HlsChunkSource.getChunkOperation()
By the end of this method, there are several lines that deal with reconfiguring the extractor in case of variant switch detection:
``` Java
   // Configure the extractor that will read the chunk.
    HlsExtractor extractor;
    if (previousTsChunk == null || segment.discontinuity || switchingVariant || liveDiscontinuity) {
      extractor = chunkUri.getLastPathSegment().endsWith(AAC_FILE_EXTENSION)
          ? new AdtsExtractor(switchingVariantSpliced, startTimeUs, bufferPool)
          : new TsExtractor(switchingVariantSpliced, startTimeUs, bufferPool);
    } else {
      extractor = previousTsChunk.extractor;
    }

    return new TsChunk(dataSource, dataSpec, extractor, enabledVariants[variantIndex].index,
        startTimeUs, endTimeUs, chunkMediaSequence, isLastChunk);
```

This code works fine, if `switchingVarinat` is set to true in the same call where the new variant index is set in line 263:
``` Java
variantIndex = nextVariantIndex;
```
However,
There are several exit points earlier in this method:
Lines 289-296:
``` Java
    int chunkIndex = chunkMediaSequence - mediaPlaylist.mediaSequence;
    if (chunkIndex >= mediaPlaylist.segments.size()) {
      if (mediaPlaylist.live && shouldRerequestMediaPlaylist(variantIndex)) {
        return newMediaPlaylistChunk(variantIndex);
      } else {
        return null;
      }
    }
```
And in lines 301-314:
``` Java
    // Check if encryption is specified.
    if (HlsMediaPlaylist.ENCRYPTION_METHOD_AES_128.equals(segment.encryptionMethod)) {
      Uri keyUri = Util.getMergedUri(mediaPlaylist.baseUri, segment.encryptionKeyUri);
      if (!keyUri.equals(encryptionKeyUri)) {
        // Encryption is specified and the key has changed.
        HlsChunk toReturn = newEncryptionKeyChunk(keyUri, segment.encryptionIV);
        return toReturn;
      }
      if (!Util.areEqual(segment.encryptionIV, encryptedDataSourceIv)) {
        initEncryptedDataSource(keyUri, segment.encryptionIV, encryptedDataSourceSecretKey);
      }
    } else {
      clearEncryptedDataSource();
    }
```

This causes the new variant index to be set, but without updating the corresponding extractor. (In the next call to `getChunkOperation` we won't set `switchingVariants` again).

I have a patched solution to this problem. If you want me to push - please instruct me where.

**Comment by ojw28** [comment]
Nice find; thanks! On the dev branch this code looks a bit different. It looks like it would have the same issue, but it also looks like it's easy to fix. There's this at line 265:

```formatIndex = nextFormatIndex;```

Fixing the issue should be as simple as moving that line down to be immediately before line 338, which is where it's first used. Could you confirm that this change fixes the problem for you on the dev branch? I can get a fix merged if that's the case. We're also finalizing a release back to master, so if we get it in soon it'll get picked up as part of that.

**Comment by krok55** [comment]
I'll test it on this weekend.
But I'm not sure this is the best solution:
First, are you sure that `formatIndex` is not being used in any other private methods? (that `getChunkOperation` invoke)
Second, if the method exits on any of the lines: 262, 294, 296 (dev branch) - you may still "miss" the variant switching point... (unless I'm missing something?)

**Comment by ojw28** [comment]
Fixed in a different way as ref'd above. Please let me know if this doesn't fix the problem for you.

**Comment by krok55** [comment]
I tested it today.
Unfortunately, instead of crashing, the video playback just freezes (while the sound continues)
The symptoms are the same, but it seems that the fix is not 100%...

Any ideas?
