### ISSUE TITLE
Exoplayer not release DirectByteBuffer,Hashmapentry,memoryref,codec Buffer 

### ISSUE THREAD

**Issue by Livekus** [google/ExoPlayer#4002]
Before filing an issue:
-----------------------
 in my application ,i fling the content which is showed with view pager each page have exoplayer for render a video, i believe releases each video correctly ,here my code below,

```
public  void releaseVideo(){
        try {
                if(player!= null) {
                    player.setPlayWhenReady(false);
                    player.stop();
                    player.setVideoSurface(null);
                    player.setVideoSurfaceHolder(null);
                    player.setVideoTextureView(null);
                    player.release();
                    player = null;
                }
                if(viewVideo != null){
                    if(viewVideo.getPlayer() != null){
                        Player simpleExoPlayer = viewVideo.getPlayer();
                        simpleExoPlayer.stop();
                        simpleExoPlayer.release();
                        viewVideo.setPlayer(null);
                    }
                }
                if(concatenatedSource != null){
                    for(int i = 0 ; i< concatenatedSource.getSize();i++){
                        concatenatedSource.removeMediaSource(i);
                    }
                    concatenatedSource.releaseSource();
                }
        }catch (Exception e){
            e.printStackTrace();
            writeException(mContext,e);
        }
    }
```

### Issue description
here is capture screen from my debuger
![mediacodecbuffer2](https://user-images.githubusercontent.com/10396116/37593714-835b525a-2ba5-11e8-8cf1-d44b4b2d0b99.png)
![memoryref](https://user-images.githubusercontent.com/10396116/37593562-fe69eaca-2ba4-11e8-9ddc-83de792edf6d.png)
![hashmap](https://user-images.githubusercontent.com/10396116/37593563-fe9ce51a-2ba4-11e8-88c0-39cf2ebbabbd.png)
![directbytebuffer](https://user-images.githubusercontent.com/10396116/37593565-feceea1a-2ba4-11e8-95d4-929008c36d26.png)

the memory stack from a little , untill app out of memory , (if i dont use this code 

`player.setVideoSurface(null);
                    player.setVideoSurfaceHolder(null);
                    player.setVideoTextureView(null);`)

### Version of ExoPlayer being used
2.7.0

### Device(s) and version(s) of Android being used
samsung galaxy s7

**Comment by AquilesCanta** [comment]
We'd love to help you with this, but unfortunately it is out of the scope of this issue tracker to debug apps. We need to ensure this is an ExoPlayer issue before we take a deeper look. To do this, if it is impossible to reproduce in the demo app, you could try coming up with a minimal setup which reproduces the issue. Note that an OutOfMemory exception does not necessarily mean there is a memory leak, if you try to buffer enough videos, you will eventually end up running out of memory. It'd be easy to rule this out by checking the number of players living simultaneously in memory (i.e. have not been released at a given point). If you find any information that points towards this being an ExoPlayer issue, please include it below and we'll reopen this. The same if I have missed anything obvious. 

Final comment: You shouldn't be calling releaseSource yourself (this is documented in MediaSource). This is done by the player.

**Comment by Livekus** [comment]
thanks you  for your reply and final comment i will apply it to my code

**Comment by Livekus** [comment]
Ok , now i having found that i must remove all Mediasource from DymamicConcatMediaSouce before i release player the graphic memory isn' t stacked 140 Mb again

**Comment by AquilesCanta** [comment]
You should not need to remove the elements from the ConcatMediaSource for the player to release memory allocations, calling Player#release is enough. I suggest you make sure release is being called on every Player instance. If this is not happening, any workaround will end up running into some resource being exhausted.
