### ISSUE TITLE
Close caption: Text are not match with the video its going Two second advanced

### ISSUE THREAD

**Issue by sathishkumar1392** [google/ExoPlayer#4003]
# ## Issue description
Close caption: Text are not matching with the video it's going Two seconds advanced, I'm using HLS streaming URL. The URL is coming from the Amazon with transcription made by my team. I'm trying on Android as my part. This issue occurs only on my side. How do I handle this issue?

# ### Reproduction steps
Parse HLS URL with transcription enabled to exoplayer

## Version of ExoPlayer being used

Exoplayer version 2.6.0

## Device(s) and version(s) of Android being used

Device: Samsung Galaxy S6,
OS: Android 5.0.2.

**Comment by AquilesCanta** [comment]
This issue is being closed because it does not adhere to our issue template, and/or because it omits information requested in the issue template that is required for us to investigate the problem efficiently. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

If you’re able to provide complete information as requested in the issue template, please do so below and we’ll re-open the issue. Thanks!

**Comment by sathishkumar1392** [comment]
**# **Issue description****
Close caption: Text are not matching with the video it's going Two seconds advanced, I'm using HLS streaming URL. The URL is coming from the Amazon with transcription made by my team. I'm trying on Android as my part. This issue occurs only on my side. How do I handle this issue?

**# **## Reproduction steps****
Parse HLS URL with transcription enabled to exoplayer

# **Version of ExoPlayer being used**
Exoplayer version 2.6.0

# **Device(s) and version(s) of Android being used**

Device: Samsung Galaxy S6,
OS: Android 5.0.2.

**Comment by ojw28** [comment]
There's nothing we can do to help debug this issue without a link to some content that reproduces the issue.

**Comment by sathishkumar1392** [comment]
# ## Reproduction steps
Parse HLS URL with transcription enabled to exoplayer

Audio closed caption  
https://s3-eu-west-1.amazonaws.com/cyrano-temp/test-audio/aa10a5e5-0d88-dac7-400f-f20a7dce6841.m3u8

Using this HLS URL  you can test it. I hope this URL is very useful to you

**Comment by AquilesCanta** [comment]
This does look like a bug. We'll look into it and let you know once we figure out what's wrong.

**Comment by sathishkumar1392** [comment]
@AquilesCanta : I'm waiting

**Comment by AquilesCanta** [comment]
Before I take a proper look at this, make sure that the behavior is not caused by the lack of [X-TIMESTAMP-MAP](https://tools.ietf.org/html/draft-pantos-http-live-streaming-23#section-3.5).

**Comment by sathishkumar1392** [comment]
@AquilesCanta : Sorry i cant get the  X-TIMESTAMP-MAP which this represent

**Comment by sathishkumar1392** [comment]
@AquilesCanta  i will upload sample Vtt file as zip format  pl z take and look and tell me its issue with player or Vtt file.
[000181d4-2b11-8702-0035-faa46e805470.vtt.zip](https://github.com/google/ExoPlayer/files/1829701/000181d4-2b11-8702-0035-faa46e805470.vtt.zip)

**Comment by AquilesCanta** [comment]
As mentioned above, the file is missing the [X-TIMESTAMP-MAP](https://tools.ietf.org/html/draft-pantos-http-live-streaming-23#section-3.5) tag. The linked specification contains examples of webvtt files. The value for the attribute MPEGTS depends on the PTSs in your TS files.

**Comment by sathishkumar1392** [comment]
@AquilesCanta Thanks  aquilescanta with your help we find out issue and fixed it. I hope this solutions works for us. once again thanks AquilesCanta
