### ISSUE TITLE
Forcing DASH HttpDataSourceException - Timeout values not working as expected

### ISSUE THREAD

**Issue by 0c6a183d** [google/ExoPlayer#4004]
I am using Exoplayer to stream DASH content. I am creating a scenario where the sever becomes unavailable mid-play so the app can react.

When building the HTTP media source(DefaultHttpDataSourceFactory) I set the connectTimeoutMillis to 5000 (Expecting this to be a 5 second TCP timeout).

I shut the server down whilst exoplayer is playing its buffered track, then seek forward way ahead of the buffer prompting Exoplayer to retrieve new chunks from the now unavailable server.

As expected I receive a $HttpDataSourceException: Unable to connect to https://server/file45.m4s

The problem is, a setting of 5000 takes 23 seconds to throw the exception, not 5 seconds.

I tried other settings and received unexpected pattern of results:

**Nokia 6 (7.1.2)**
40_000 = 2m 8s (connectTimeoutMillis = 40000, timeout exception takes 2m 8s to appear)
20_000 = 1M 23S
10_000 = 0M 43S
5_000   = 0m 23S
1_000   = 0M 7.5S
250 	    = 0m 5s
100 	    = 0M 4S

**AVD QVGA (4.4)**
Not as reliable as a physical device but appears to always be 10x the value
5_000 = 50 Seconds
3_000 = 30 seconds etc

Other parts of my app use http file download (okhttp) and the timeout happens to the second of the "connect timeout" value I set as expected, but Exoplayer seems very different. Is this by design, or should this not be happening?

Thanks for your help in advance.

**Comment by AquilesCanta** [comment]
The delay is probably due to the [retry logic](https://github.com/google/ExoPlayer/blob/r2.7.1/library/core/src/main/java/com/google/android/exoplayer2/upstream/Loader.java#L386) (please check this is the case, basically look for whichever onLoadError is being called). Allowing customization of whatever the player does when an error happens is a pending enhancement. In your case, you'd like to fail asap, but some users want to try adaptation set/variant blacklisting. This enhancement is tracked by #2844. The virtual device part is puzzling, if you manage to figure out why, please share it with us.

**Comment by 0c6a183d** [comment]
Thank you for your response.

After capturing the inbound packets on the firewall, I could see that Exoplayer was indeed retrying 4 additional TCP SYN connections after the initial [connectTimeoutMillis ](https://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/upstream/DefaultHttpDataSource.html#DEFAULT_CONNECT_TIMEOUT_MILLIS)had expired (with a few re-transmissions between). I was able to improve this issue by using [setMinLoadableRetryCount](https://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/source/dash/DashMediaSource.Factory.html#setMinLoadableRetryCount-int-)(1). 

This has reduced the TCP connect retries from the default 4, to 1, meaning a [connectTimeoutMillis ](https://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/upstream/DefaultHttpDataSource.html#DEFAULT_CONNECT_TIMEOUT_MILLIS)of 5000ms now takes 10 Seconds not 25(1 + 4 retries).

I have noticed that [setMinLoadableRetryCount](https://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/source/dash/DashMediaSource.Factory.html#setMinLoadableRetryCount-int-)(**0**) does the same as [setMinLoadableRetryCount](https://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/source/dash/DashMediaSource.Factory.html#setMinLoadableRetryCount-int-)(**1**) whereby Exoplayer will _always_ retry once. Is this the expected behavior? I think a setting of 0 would make sense to disable retries as it is still taking twice the time (of the value set in connectTimeoutMillis) to throw a timeout.

Thanks.
