### ISSUE TITLE
Low Latency RTMP (DefaultLoadControl)

### ISSUE THREAD

**Issue by Brianvdb** [google/ExoPlayer#4013]
I am trying to achieve low latency streaming (2~3secs) using rtmp. I am constructing the DefaultLoadControl like:

```java
 DefaultLoadControl loadControl = new DefaultLoadControl(defaultAllocator, 1000, 3000, 1000, 1000, -1, true);
```

This however brings an issue: sometimes it only shows the first frame of the livestream and then it just doesn't do anything (no warning or errors in the logs either).

This is my full code:
```java
        BandwidthMeter bandwidthMeter = new DefaultBandwidthMeter();
        TrackSelection.Factory videoTrackSelectionFactory = new AdaptiveTrackSelection.Factory(bandwidthMeter);
        TrackSelector trackSelector = new DefaultTrackSelector(videoTrackSelectionFactory);

        DefaultAllocator defaultAllocator = new DefaultAllocator(true, DEFAULT_BUFFER_SEGMENT_SIZE);
        DefaultLoadControl loadControl = new DefaultLoadControl(defaultAllocator, 1000, 3000, 1000, 1000, -1, true);

        SimpleExoPlayer player = ExoPlayerFactory.newSimpleInstance(new DefaultRenderersFactory(this, null, EXTENSION_RENDERER_MODE_OFF), trackSelector, loadControl);
        SimpleExoPlayerView simpleExoPlayerView = findViewById(R.id.exo_player);
        simpleExoPlayerView.setPlayer(player);

        RtmpDataSourceFactory rtmpDataSourceFactory = new RtmpDataSourceFactory();
        ExtractorsFactory extractorsFactory = new DefaultExtractorsFactory();

        ExtractorMediaSource mediaSource = new ExtractorMediaSource
                .Factory(rtmpDataSourceFactory)
                .setExtractorsFactory(extractorsFactory)
                .createMediaSource(Uri.parse("rtmp://174.138.0.196/myapp/mystream live=1"));


        player.prepare(mediaSource);
        player.setPlayWhenReady(true);
```

Basically I want the buffer to be like 2secs, interruptions are okay as long as i keep my low latency.

**Comment by AquilesCanta** [comment]
> it only shows the first frame of the livestream and then it just doesn't do anything

It gets stuck endlessly? Or does it just go to buffering state for a certain period of time?

> Basically I want the buffer to be like 2secs, interruptions are okay as long as i keep my low latency.

Can you clarify what latency means in this context? Do you mean the time it takes until playback starts?

By the way, the maximum buffer time (third argument in DefaultLoadControl) seems to me quite short, I wonder if that could cause issues when the GOP is long enough (I may be wrong). This value should not affect the start up latency if large, so I'd suggest using the default value for that parameter. The second argument wouldn't hurt if bigger as well. Might make sense to use all default values, except for the 4th (smaller should translate into a faster start, though might produce an immediate buffering state). If you also care about the start after buffering, then the 5th argument can get smaller.

**Comment by Brianvdb** [comment]
> It gets stuck endlessly? Or does it just go to buffering state for a certain period of time?

Stuck endlessly. But I 'fixed' this issue with the following custom loadcontrol: [https://github.com/rohitrfactor/ExoPlayer/blob/e3e37475140a8694fb93a576c2e15cd1a1427624/app/src/main/java/com/pinnacle/garorasu/exoplayer/PreviewLoadControl.java](https://github.com/rohitrfactor/ExoPlayer/blob/e3e37475140a8694fb93a576c2e15cd1a1427624/app/src/main/java/com/pinnacle/garorasu/exoplayer/PreviewLoadControl.java)

> Can you clarify what latency means in this context? Do you mean the time it takes until playback starts?

Yes. But with the load control above I have the following issue: playback sometimes starts after like 5 seconds and sometimes just 2 seconds. After that it plays just fine. When it starts after 5 seconds this happens:
- Audio plays after 1~2 seconds, first video frame is visible
- Video starts playing after 5 seconds.

In my app low latency is crucial, I need playback to start almost instantly (<2 sec latency) and buffering should not get higher then 2 seconds (that's why I am using rtmp). If it gets higher (due to slow connection), it should 'reconnect' even if this causes to drop frames. I wonder if this is possible by any chance. Basically it should not buffer at all and just render the incoming stream directly.

@AquilesCanta

**Comment by AquilesCanta** [comment]
Is this a live stream? If so, bandwidth may not be an issue, but rather the rate at which packets are produced by the server. As mentioned above, the size of the [GOP](https://en.wikipedia.org/wiki/Group_of_pictures) is an important aspect here. If long enough, it might mean the player needs to wait until the next frame. Also, is the container format transport stream? If so, some time may also be spent waiting for the PAT and PMT during preparation.

In conclusion, there are more variables here than just the loading policy. Unfortunately many of these aspects depend on server side behavior, and we do not count with the resources to diagnose third party setups. If at any point you manage to pinpoint the source of the delays, and there is anything we can do on our side to fix that, please let us know. But we will need you to diagnose the issue, as the information provided here is not nearly enough for us to do anything. I will try to point someone who knows more about RTMP to this issue.

**Comment by Brianvdb** [comment]
@AquilesCanta Yes it is a livestream and indeed the issue was the GOP as you mentioned. I decreased the GOP on the server side and now it starts playback almost immediately which results in the desirable latency of 2 seconds max.

However when testing on a bad internet connection the following happens:
- playback starts almost imnediately (< 2sec latency)
- after a little while it stops playing for a few seconds and then continues playing
This results in a larger latency.

Is there any way I can either:
- read the latency time
- force reconnect when the streams hangs
- drop frames instead of buffering to keep latency the same

**Comment by AquilesCanta** [comment]
@Brianvdb, I think you are in much better position than me to diagnose the cause of the buffering and therefore fix your issues. It is not within the scope of this issue tracker to provide advice on how to debug client/server interactions. As with the GOP size issue, this could be almost anything. And probably unrelated to exoplayer. If you have concrete steps to reproduce what you think is a bug, please file a new issue including all information requested in the issue template.

**Comment by a-alexeev-incrdbl** [comment]
I had the same issue, I was able to decrease latency to 2,5 seconds by passing a 'buffer=1000' parameter with stream url. 

`MediaSource mediaSource = new ExtractorMediaSource.Factory(mediaDataSourceFactory)
                .createMediaSource(
                        Uri.parse(url + " live=1 buffer=1000"),
                        mainHandler,
                        eventLogger
                );`

1000 may be to low, you have to expreiment what buffer size fits you best.

All available parameters are described here: https://github.com/ant-media/LibRtmp-Client-for-Android/blob/master/rtmp-client/src/main/cpp/librtmp/librtmp.3

It took me 3 days to figure out, that librtmp can also be configured.

**Comment by AdamGrzybkowski** [comment]
@Brianvdb Did you find a solution to somehow skip frames after buffering is done? I have a similar problem and the buffering increases the latency quite a lot when using slow network connection.

**Comment by Brianvdb** [comment]
@AdamGrzybkowski No not yet. Let me know if you have a solution.
