### ISSUE TITLE
Using VideoPlayerGlue (Leanback) but always a delay after playing...

### ISSUE THREAD

**Issue by jboisjo** [google/ExoPlayer#4015]
### Issue description
Whenever i'm playing a DASH playlist in the player, using PlaybackTransportRowPresenter...the video is State ready after being buffered, but still being stuck for 1-2 seconds before playing.

### Reproduction steps
Tried to recreate my LeanbackAdapterClass to verify the player.state, and it's ready to play but still waits for something.

### Link to test content
Provide a link to media that reproduces the issue. If you don't wish to post it
publicly, please submit the issue, then email the link to
dev.exoplayer@gmail.com using a subject in the format "Issue #1234".

### Version of ExoPlayer being used
2.7.0

### Device(s) and version(s) of Android being used
Shield TV

```
public class PlaybackTransportControlGlue<T extends PlayerAdapter>
        extends PlaybackBaseControlGlue<T> {

    static final String TAG = "PlaybackTransportGlue";
    static final boolean DEBUG = false;

    static final int MSG_UPDATE_PLAYBACK_STATE = 100;
    static final int UPDATE_PLAYBACK_STATE_DELAY_MS = 2000;

    PlaybackSeekDataProvider mSeekProvider;
    boolean mSeekEnabled;
```

Maybe in it's the PlaybackTransport, that static variable? that keeps give me a delay before playing.

I'm using the demo example of LeanbackPlayerAdapter.

So, the player load the playlist, changed state for Buffering and then...Ready to Play. But the image is still not being played in about 2 more seconds.

So it takes around 4 seconds to start a video everytime and it's pretty annoying.

**Comment by susnata1981** [comment]
Thanks for reporting this issue. The 2 second delay introduced by UPDATE_PLAYBACK_STATE_DELAY_MS seems like the issue. I believe this was introduced for synchronization purpose. I'll investigate and update this thread.

**Comment by AquilesCanta** [comment]
For some reason, I cannot assign you, @susnata1981. In any case, internal reference [b/76434032].

**Comment by jboisjo** [comment]
thank you :)

Also, i've been testing this issue on other device, and it looks worse on less performant device. If we try this on the MiBox or any other device, it will be longer...

**Comment by jboisjo** [comment]
One issue i have with leanback-exoplayer, is this library consume way more than just basic exo?

My cpu usage always go from 10-15% and before using this lib i was getting 3-5%.

And also, why is the player consuming that much?

**Comment by ojw28** [comment]
What `updatePeriodMs` are you specifying via the` LeanbackPlayerAdapter` constructor?

**Comment by jboisjo** [comment]
using the same delay as the sample which is 16.

https://github.com/googlesamples/androidtv-Leanback/blob/master/app/src/main/java/com/example/android/tvleanback/ui/PlaybackFragment.java

`private static final int UPDATE_DELAY = 16;`

**Comment by ojw28** [comment]
That value is, in my opinion, way too small, and likely to cause significant CPU overhead. I'd suggest something more in the region of 1000, which is what we use for our non-leanback player controls. If you set it to a larger value, do you see the CPU usage drop back down to expected levels?

**Comment by jboisjo** [comment]
Yes it's now at 3-5% :)

**Comment by ojw28** [comment]
@susnata1981 - Is it possible to set the delay in the sample to something more sensible? I remember expressing concerns at the time about CPU usage, and this now seems to be playing out for developers.

**Comment by jboisjo** [comment]
Also the delay introduced in this Leanback Library cause a long delay when we setup a DrmSessionManager. It takes way longer on less performance devices.

**Comment by jboisjo** [comment]
also we can't change the value outside the package, so don't have any access :(

<img width="765" alt="screen shot 2018-04-25 at 11 52 39 am" src="https://user-images.githubusercontent.com/18666345/39257332-430cb2f6-487f-11e8-8cae-0be15e1a7052.png">

**Comment by jboisjo** [comment]
I think i found a way to the problem, whenever i remove the DrmSessionManager in the buildAudioRenderers (DefaultRendersFactory) everything works perfectly, but i got no sound of course.

**Comment by jboisjo** [comment]
And it's only with leanback-exoplayer, same drmManager class and only with exoplayer, works fine, but i really don't know what cause that with leanback-exoplayer.

There's no example in the sample about a DRM included. I don't know if you have tried a DRM playlist with leanback-exoplayer but it really doesn't work that well.

**Comment by botaydotcom** [comment]
@jboisjo:
Could you please set-up a minimal project to show this problem, together with the URL of the content that you tried this on? If you don't wish to post these publicly, please email them to dev.exoplayer@gmail.com using a subject in the format "Issue #4015". That will help a lot in debugging/analyzing this issue. Thank you very much.

**Comment by AquilesCanta** [comment]
Hi, @jboisjo, please provide the information requested in the comment above and we will reopen the issue.
