### ISSUE TITLE
Audio playback stuck in buffering

### ISSUE THREAD

**Issue by Nezz** [google/ExoPlayer#402]
On certain devices audio tracks play for a split second, then stop. No error is on the output. Playback state is stuck in buffering. This is the event log:
```
I/ExoPlayerImpl(30964): Init 1.3.0
I/dalvikvm(30964): Could not find method android.media.AudioTrack.write, referenced from method com.google.android.exoplayer.audio.AudioTrack.writeNonBlockingV21
W/dalvikvm(30964): VFY: unable to resolve virtual method 980: Landroid/media/AudioTrack;.write (Ljava/nio/ByteBuffer;II)I
D/dalvikvm(30964): VFY: replacing opcode 0x6e at 0x0001
I/mono-stdout(30964): ExoPlayer state: Idle
I/dalvikvm(30964): Could not find method android.media.MediaCodecInfo$CodecCapabilities.getVideoCapabilities, referenced from method com.google.android.exoplayer.MediaCodecUtil.isSizeAndRateSupportedV21
W/dalvikvm(30964): VFY: unable to resolve virtual method 864: Landroid/media/MediaCodecInfo$CodecCapabilities;.getVideoCapabilities ()Landroid/media/MediaCodecInfo$VideoCapabilities;
D/dalvikvm(30964): VFY: replacing opcode 0x6e at 0x0019
I/OMXClient(30964): Using client-side OMX mux.
E/OMXMaster(30964): A component of name 'OMX.qcom.audio.decoder.aac' already exists, ignoring this one.
I/OMXClient(30964): Using client-side OMX mux.
E/OMXMaster(30964): A component of name 'OMX.qcom.audio.decoder.aac' already exists, ignoring this one.
I/SoftAAC2(30964): Reconfiguring decoder: 0->44100 Hz, 0->2 channels
I/mono-stdout(30964): ExoPlayer position: 102
I/mono-stdout(30964): ExoPlayer state: Preparing
I/mono-stdout(30964): ExoPlayer state: Buffering
I/mono-stdout(30964): ExoPlayer state: Ready
I/mono-stdout(30964): ExoPlayer position: 163
I/mono-stdout(30964): ExoPlayer position: 180
I/mono-stdout(30964): ExoPlayer position: 180
I/mono-stdout(30964): ExoPlayer position: 188
I/mono-stdout(30964): ExoPlayer position: 198
I/mono-stdout(30964): ExoPlayer position: 198
I/mono-stdout(30964): ExoPlayer position: 207
I/mono-stdout(30964): ExoPlayer position: 216
I/mono-stdout(30964): ExoPlayer position: 224
I/mono-stdout(30964): ExoPlayer position: 242
I/mono-stdout(30964): ExoPlayer position: 242
I/mono-stdout(30964): ExoPlayer position: 255
I/mono-stdout(30964): ExoPlayer position: 255
I/mono-stdout(30964): ExoPlayer state: Buffering
I/mono-stdout(30964): ExoPlayer position: 97391669
I/mono-stdout(30964): ExoPlayer position: 97391669
I/mono-stdout(30964): ExoPlayer position: 97391669
I/mono-stdout(30964): ExoPlayer position: 97391669
I/mono-stdout(30964): ExoPlayer position: 97391669
```

**Comment by ojw28** [comment]
"certain devices" isn't sufficient information to even start looking at this. Which devices, specifically? Which extractor are you using? What audio file?

**Comment by Nezz** [comment]
Observed on a Galaxy S6 running stock rom.
Also observed on **all** Amazon devices, but I know Fire OS is not officially supported.

**Comment by Nezz** [comment]
Tested with MP3s and MP4s (AAC). There was not a single song that worked on the affected devices.

`MediaCodecAudioTrackRenderer` was used to play back files from a `FrameworkSampleSource`.

**Comment by Nezz** [comment]
Problem occurs with both the stable and the dev versions, so this is not related to the new extractor model.

**Comment by ojw28** [comment]
I suggest you use ExtractorSampleSource with Mp4Extractor and Mp3Extractor instead. The platform underneath FrameworkSampleSource is pretty buggy, and we're trying to move away from it. I'd like to delete it completely at some point, since it's caused us a significant number of device specific issues.

**Comment by Nezz** [comment]
Thanks, I will have a look. Is there a way to automatically figure out with extractor to use?

**Comment by ojw28** [comment]
Not yet. Automatic sniffing of media type is on our list of things to do though. In the meantime, you may be able to use: http://developer.android.com/reference/android/media/MediaMetadataRetriever.html.

**Comment by Nezz** [comment]
How can I play back local files (using FileDescriptor)?

**Comment by Nezz** [comment]
I can still replicate it by playing back files from the storage device using ExtractorSampleSource. Any tips on debugging this?

**Comment by ojw28** [comment]
Provide a sample file and I'll try and look locally on an S6.

**Comment by ojw28** [comment]
Closing due to lack of information.
