### ISSUE TITLE
Black screen when trying to play m4a & m4v.

### ISSUE THREAD

**Issue by petersamokhin** [google/ExoPlayer#4020]
### Issue description
I'm trying to play `m4a` and `m4v` files from file. But I see only black screen (and no errors in logcat). These file received through saving `.mpd` broadcast. Detailed information you can see in `.txt` files below:

`exiftool audio.m4a > audio.txt` output:
[audio.txt](https://github.com/google/ExoPlayer/files/1837591/audio.txt)

`exiftool video.m4v > video.txt` output:
[video.txt](https://github.com/google/ExoPlayer/files/1837603/video.txt)

### Reproducing steps

My code:
```
val audioUri = Uri.fromFile(File("/sdcard/Movies/test_media/" + "audio.m4a"))
val videoUri = Uri.fromFile(File("/sdcard/Movies/test_media/" + "video.m4v"))

val dataSourceFactory = DefaultDataSourceFactory(context, "ExoPlayer/2.7.0 (Linux;Android 5.1) ExoPlayer/2.7.0", DefaultBandwidthMeter())
val audioSource = ExtractorMediaSource.Factory(dataSourceFactory).createMediaSource(audioUri)
val videoSource = ExtractorMediaSource.Factory(dataSourceFactory).createMediaSource(videoUri)

val mergedMediaSource = LoopingMediaSource(MergingMediaSource(videoSource, audioSource))

player.prepare(mergedMediaSource, true, true)
```

Tried to use another files (e.g. `mp3` & `mp4` samples from web) — all is ok (video and audio are playing).
Tried to use "good" `mp4` file with my `m4a` file — I can only see first frame of video. Audio or video isn't playing.

Converted my `m4a` and `m4v` to `mp3` and `mp4` with `ffmpeg -i audio.m4a audio.mp3` and `ffmpeg -i video.m4v video.mp4` — then used this files — and then all is ok, video and audio are playing.

### Link to test content
Sent files to dev.exoplayer@gmail.com with subject `Issue #4020` from contact@petersamokhin.com.

### Version of ExoPlayer being used
2.6.1

### Device(s) and version(s) of Android being used
Android version: 22 (Philips S309), 27 (google nexus emulator)

### A full bug report captured from the device
Sent `./adb bugreport > bugreport.txt` output to dev.exoplayer@gmail.com with subject `Issue #4020` from contact@petersamokhin.com.

**Comment by AquilesCanta** [comment]
This issue is being closed because it does not adhere to our issue template, and/or because it omits information requested in the issue template that is required for us to investigate the problem efficiently. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

If you’re able to provide complete information as requested in the issue template, please do so below and we’ll re-open the issue. Thanks!

**Comment by petersamokhin** [comment]
### Issue description
Available above.

### Reproducing steps 
Copy code above and run. 

### Link to test content
Can provide problem files if it necessary (but don't think so). These file received through saving `.mpd` broadcast. Detailed information you can see in `.txt` files above.

### Version of ExoPlayer being used
`com.google.android.exoplayer:exoplayer:2.6.1`

### Device(s) and version(s) of Android being used
Android version: 21, 27 (google nexus emulators)

### A full bug report captured from the device
I don't think this is necessary. No stacktrace or another error.

**Comment by petersamokhin** [comment]
@AquilesCanta issue updated.

**Comment by AquilesCanta** [comment]
I will have a look soon. By the way, do the troublesome files play by themselves (i.e. As standalone media sources)? What about the demo app? Does the demo app play the separate files correctly?

Note: Avoid making assumptions on what is necessary what is not (specially if specifically requested in the issue template, it is there for a reason). Much more than just a stacktrace can be found in a bugreport, like decoder information. It is much more likely that we take a look if we don't need to ask for additional information multiple times. Thanks for the update.

**Comment by petersamokhin** [comment]
@AquilesCanta 
1. Files are ok — you can play them on your machine (by any default player). 
2. ExoPlayer can't play `audio.m4a` / `video.m4v` / `Merging(audio.m4a+video.m4v)` / `Merging(audio.m4a` or `video.m4v` + `another audio or video`)
3. Updated first message, added info about bugreport (it sent to your email).
4. Demo app also can't play `audio.m4a` / `video.m4v`.

**Comment by ojw28** [comment]
I'm not sure the files are ok. If you try and play the audio file in Chrome or VLC, you'll see that although the media plays, the seek bar is messed up. I didn't look too closely, but it appears the duration is incorrect, the timestamps don't start from zero, and the timestamps exceed the specified duration. Nevertheless the file played fine in ExoPlayer V2 for me, aside from the seek bar being messed up in exactly the same way as Chrome and VLC.

For the video file, it appears to have the same issue. The difference here is that we're starting playback from t=0, so you'd have to wait approximately 47 minutes to reach the non-zero timestamp at which the video starts.

For the merged source, I do see that it plays both audio and video successfully. In this case the audio track snaps the playback position as in the audio only case, and the video samples play in sync.

Given the odd nature of this media and this being a single report, I don't think we're going to do anything about this. We'd normally expect timestamps to begin at 0 for standalone media files, in which case this wouldn't be an issue.

**Comment by petersamokhin** [comment]
So, thanks for answer in 4 months :) No longer relevant at this time.
