### ISSUE TITLE
Playback buffer value

### ISSUE THREAD

**Issue by kanthicn1** [google/ExoPlayer#4023]
I am writing a DASH video player using ExoPlayer demo app as the base for my application. How can I get the actual playback buffer size in seconds, without messing with the actual MediaSource and other  code libraries (and short of maintaining my own variable tracking media downloaded, played, paused and all that mess)? 
By actual playback buffer size, I mean the 'total duration duration of the video chunks that's already buffered' - 'total duration of the video chunks that's been watched'. 
For example, if the player has downloaded 60s worth of data and the renderer has already played 50s of this video, I want to know that there's 10 more seconds to go before the player might hit a re-buffer. I am trying to eventually get to a feature that minimizes re-buffering events.
I want to do this with minimal changes to the existing code and achieve this with event listeners, as much as possible. I know if I write my own trackSelector, this is easy to obtain. But, can I get it at the app layer?
Thanks for any pointers.

**Comment by tonihei** [comment]
`player.getBufferedPosition() - player.getCurrentPosition()` should give you what you want for most situations. 

The only exception is when the player pre-buffers the following items in a playlist. In this case the calculation would only give you the buffered duration in the current playlist item. But, we are planning to fix this soon.

**Comment by kanthicn1** [comment]
Thank you! This works perfectly for me right now. However, I want to understand the caveat in this solution that you mentioned. If the player pre-buffers the other items in the playlist, are you saying this method won't give me the buffer values of all the tracks? But, this method will always give me the correct buffer value of the track that is currently being played. Correct?

**Comment by tonihei** [comment]
Yes, that's correct. We are currently adding a new method the interface `Player.getTotalBufferedDuration()` which returns the total duration of buffered media across all playlist items.

**Comment by kanthicn1** [comment]
Great!
Thanks again for your help.
