### ISSUE TITLE
Can I insert ads in exoplayer while playing video

### ISSUE THREAD

**Issue by RadhikaBalla** [google/ExoPlayer#4025]
How to insert ads while playing video in exoplayer? Can I insert my own custom ads? Please help me out with a solution.

**Comment by andrewlewis** [comment]
- If you want to play VAST ads please have a look at the [IMA extension](https://github.com/google/ExoPlayer/tree/release-v2/extensions/ima).
- If you want to load ad media URIs yourself you can implement your own `AdsLoader` to replace the `ImaAdsLoader`. This is quite a bit of work but there is some information in #3664 and #3967. I'm afraid we don't have a detailed tutorial on doing this. Please have a look at the implementation of `ImaAdsLoader` and read the documentation of `AdsLoader` and `AdPlaybackState`.
- If you just want to play ads before/after some content like a normal playlist you can use `ConcatenatingMediaSource`. To insert midrolls you can join `ClippingMediaSource`s (for content clips) with media sources for your ads in a `ConcatenatingMediaSource`.
