### ISSUE TITLE
Support direct loading of media stored as assets in the application apk

### ISSUE THREAD

**Issue by dnutcracker** [google/ExoPlayer#403]
Scenario:
Providing the following
Uri videoUri = Uri.parse("android.resource://" + getActivity().getPackageName() + "/" + R.raw.video_file);
to the ExtractorSampleSource.

Result:
ExtractorSampleSource will fail since then open() method on the UriDataSource will mistakenly think the Uri is a remote uri since it doesn't start with the protocol "file://" resulting in an IOException: Unknown protocol android.resource"

**Comment by ojw28** [comment]
Does FileDataSource work properly for resources? If so then fine and we can have UriDataSource use that. I suspect it doesn't, however. It looks to me like Android resources aren't designed to allow random access, which will make it difficult to play them efficiently (although if it's a resource I'd hope it's small, so perhaps reading the whole thing repeatedly isn't much of an overhead).

**Comment by ojw28** [comment]
See e.g. http://www.codeitive.com/0zigWWgeVq/android-randomaccessfile-usage-from-resource.html, which essentially recommends copying the resource into the cache directory so that it's a normal file, and then using it from there.

**Comment by dnutcracker** [comment]
Copying the resource into a cache directory is the workaround I ended up
doing eventually.
Regarding the FileDataSource I'll check and update.

**Comment by ojw28** [comment]
It's probably possible to build a DataSource for loading assets directly, using this:

http://developer.android.com/reference/android/content/res/AssetManager.html#open(java.lang.String, int)

with accessMode = ACCESS_RANDOM. We might look at this at some point, but I'm not sure it's high priority. If you feel like looking yourself, we'd take a pull request with a DataSource that adds this!

**Comment by dnutcracker** [comment]
Alright. I'll have a look at it.

**Comment by andrewlewis** [comment]
@dnutcracker Did you make any progress with this yet? If not, I will try to get it done today.

**Comment by dnutcracker** [comment]
I made some progress - let me see if I can get it done today. If not - you can have it :)

**Comment by dnutcracker** [comment]
I have a pull request ready - do I need to have special permissions to push
it?

**Comment by dnutcracker** [comment]
I added a pull request #408
