### ISSUE TITLE
Custom listener to show playback controls

### ISSUE THREAD

**Issue by elnurvl** [google/ExoPlayer#4031]
Hi. I want to to show playback controls only when onTouch event is fired. How to prevent control buttons being showed up when on long pressing, dragging etc.?

**Comment by tonihei** [comment]
Our `PlayerView` class checks for `MotionEvent.ACTION_DOWN` to show the playback controls. 

If you like to have a custom behavior, you could extend `PlayerView` and override `onTouchEvent(MotionEvent ev)`. In there, you can call `showController()` or `hideController()` to achieve your intended effect.

**Comment by elnurvl** [comment]
I use ExoPlayerFactory to make a player object. I am not sure if it is the correct way to make a player object with new statement. Can't I set onTouchListener after player object being created?

**Comment by tonihei** [comment]
Yes, ExoPlayerFactory is the correct way to create the player. I think that's irrelevant for your problem though. For my suggestion, you'd need to overwrite `PlayerView` which is the UI component you may have put somewhere in your layout.

**Comment by elnurvl** [comment]
Sorry, I confused `PlayerView` with `ExoPlayer` object. So in this case I should create my own widget with custom `onTouchEvent` method and use it in my layout instead of standard `PlayerView`, right?

**Comment by tonihei** [comment]
Sounds right.

**Comment by elnurvl** [comment]
Thank you. It would be more convenient to do customization if a method like setOnTouchListener are added to PlayerView class in the next releases.

**Comment by elnurvl** [comment]
@tonihei , I am trying to implement your solution to customize the event which is responsiple for showing playback controls. Unfortunately it is not working. Because `controller` variable is private and I cannot access it in my own `PlayerView`. I cannot use `super` either, because it checks for `MotionEvent.ACTION_DOWN` implicitly as you said. What I need is to fire the event when a user single taps on the player. Isn't it possible to achieve it in ExoPlayer without changing the library files?

**Comment by tonihei** [comment]
You can change the visibility of the controller with `showController()` and `hideController()` and you can listen to its visibility with `setControllerVisibilityListener`. That means you don't actually need access to the `controller` variable to achieve your custom `onTouchEvent` handling.

To confirm that it's actually working, I tried to implement what you are trying to do with the following code.  Using this custom view, the playback controls are only shown or hidden for short taps. Dragging and long presses are filtered out.

```
public final class CustomPlayerView
    extends PlayerView implements PlayerControlView.VisibilityListener {

  private static final float DRAG_THRESHOLD = 10;
  private static final long LONG_PRESS_THRESHOLD_MS = 500;

  private boolean controllerVisible;
  private long tapStartTimeMs;
  private float tapPositionX;
  private float tapPositionY;

  public CustomPlayerView(Context context) {
    this(context, null);
  }

  public CustomPlayerView(Context context, AttributeSet attrs) {
    this(context, attrs, 0);
  }

  public CustomPlayerView(Context context, AttributeSet attrs, int defStyleAttr) {
    super(context, attrs, defStyleAttr);
    setControllerVisibilityListener(this);
  }

  @Override
  public boolean onTouchEvent(MotionEvent ev) {
    switch (ev.getActionMasked()) {
      case MotionEvent.ACTION_DOWN:
        tapStartTimeMs = SystemClock.elapsedRealtime();
        tapPositionX = ev.getX();
        tapPositionY = ev.getY();
        break;
      case MotionEvent.ACTION_MOVE:
        if (tapStartTimeMs != 0
            && (Math.abs(ev.getX() - tapPositionX) > DRAG_THRESHOLD
                || Math.abs(ev.getY() - tapPositionY) > DRAG_THRESHOLD)) {
          tapStartTimeMs = 0;
        }
        break;
      case MotionEvent.ACTION_UP:
        if (tapStartTimeMs != 0) {
          if (SystemClock.elapsedRealtime() - tapStartTimeMs < LONG_PRESS_THRESHOLD_MS) {
            if (!controllerVisible) {
              showController();
            } else if (getControllerHideOnTouch()) {
              hideController();
            }
          }
          tapStartTimeMs = 0;
        }
    }
    return true;
  }

  @Override
  public void onVisibilityChange(int visibility) {
    controllerVisible = visibility == View.VISIBLE;
  }
}
```

**Comment by elnurvl** [comment]
Thank you! Exactly what I was looking for.
