### ISSUE TITLE
Player returns negative value for live streaming.

### ISSUE THREAD

**Issue by mahesh2015** [google/ExoPlayer#4035]
Both method of player returning negative(minus) value with live stream

```
player.getDuration();
player.getCurrentPosition();
```

**Comment by tonihei** [comment]
The current position may report negative values for live streams if you, for example, pause playback and the position falls behind the current live window. The duration shouldn't normally be negative. 

Could you please fill out the [issue template](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE) for use to take a closer look? Especially example media would be helpful to reproduce the issue.

**Comment by mahesh2015** [comment]
https://github.com/amzn/exoplayer-amazon-port/issues/38

v2.6.1, Above is the link which i am using. Device in amazon FireTV gen-1, gen-2.

**Comment by tonihei** [comment]
The link above is to the same issue filed at the ExoPlayer Amazon port and not the live stream link?

**Comment by mahesh2015** [comment]
Sir,
I can't share my stream here. I have to get permission from my client first.

**Comment by tonihei** [comment]
Instead of sharing it here, you can also send it dev.exoplayer@gmail.com quoting "Issue #4035" in the subject.

**Comment by tonihei** [comment]
Thanks for sharing the streams. The first one plays perfectly fine in our demo app and has neither a negative position nor a negative duration. The second one is reporting 404 errors for me. 

I suspect your problem only occurs in the ExoPlayer Amazon port rather than ExoPlayer itself. Please follow up with the bug you filed on their site - or provide reproduction steps in our demo app if you think it's actually an ExoPlayer problem.

**Comment by mahesh2015** [comment]
Sir,
The URL  which returning 404 is time specific broadcaster(5 A.M. to 9 A.M. at GMT-4).

**Comment by tonihei** [comment]
Yes, indeed. I was now able to use the second URL too. However, it still has a valid positive duration and a positive position. Please follow up with Amazon if your problem persists on their ExoPlayer port only.

**Comment by mahesh2015** [comment]
Ok sir. 

thanks for your valuable support.
