### ISSUE TITLE
videoquality issue

### ISSUE THREAD

**Issue by pals-ric** [google/ExoPlayer#4036]
hi,
 List<Format> videoFormats = HlsRendererBuilder.VideoFormats;
can anyone tell that how can I get videoformat list for video quality in demo app.how can i get 
Format instance which will have all bitrate options.

**Comment by tonihei** [comment]
Each track (=bitrate option) is represented by a separate `Format` object. You'll be notified of available tracks in your [`Player.EventListener`](http://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/Player.EventListener.html) in `onTracksChanged`.

**Comment by pals-ric** [comment]
okay. I was simply making an logic for bit rates **low** ,**medium** ,**high** and **very high** quality and  if user select these one of these qualities that quality url will get call so i wanted to know how can i get all bitrate , which method will provide all the  bit rate availabilities along with the url.

**Comment by tonihei** [comment]
As I said, you will receive an update in `onTracksChanged` if the tracks become available or change. The first parameter (`trackGroups`) contains a list of all available tracks, while the second parameter gives you more information about the currently selected tracks for each renderer. If you want to set a specific track use [`TrackSelector.setSelectionOverride`](http://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/trackselection/MappingTrackSelector.html).  Please also have a look at our demo app where we do exactly [that](https://github.com/google/ExoPlayer/blob/release-v2/demos/main/src/main/java/com/google/android/exoplayer2/demo/TrackSelectionHelper.java).

**Comment by pals-ric** [comment]
that is my question in your demo app 
 MappedTrackInfo mappedTrackInfo = trackSelector.getCurrentMappedTrackInfo(); , having some value but for my app this is coming null i am not getting the reason and because of null value its crashing.

**Comment by pals-ric** [comment]
and i am playing m3u8 url and its working but mapped track info is null.

**Comment by tonihei** [comment]
The mapped track info will be null in the beginning before we know which tracks are available. You should be able to get a non-null value after the callback to onTracksChanged. Have you tried that?

**Comment by pals-ric** [comment]
now some value is coming but i am not getting the flow exactly what values of that method is giving and how to give the video qualty values to my popup to select the options for video quality.

    List<Format> videoFormats = HlsRendererBuilder.VideoFormats;

        if (videoFormats != null) {
            ArrayList<String> contentItems = new ArrayList<String>();

            if (videoFormats.size() > 0) {
                contentItems.add("Data Saver");
                contentItems.add("Auto");
            }

            if (bitRateList != null)
                bitRateList.clear();

            for (int i = 0; i < videoFormats.size(); i++) {
                Format videoFormat = videoFormats.get(i);
                int bitrate = videoFormat.bitrate / 1024;
                bitRateList.add(bitrate);

                if (bitrate <= 500) {
                    if (!contentItems.contains("Low"))
                        contentItems.add("Low");
                } else if (bitrate > 500 && bitrate <= 1500) {
                    if (!contentItems.contains("Medium"))
                        contentItems.add("Medium");
                } else if (bitrate > 3000) {
                    if (!contentItems.contains("High"))
                        contentItems.add("High");
                }
            }
            showDialog(contentItems);
        }

with this popup i am showing the available video qualities along with the url and if user selects the option it will change the content .

**Comment by pals-ric** [comment]
this is the code of my exoplayer 1, so i want to know how to get videoformat in this exoplayer 2.

**Comment by tonihei** [comment]
Please have a look at the TrackSelectionHelper class in our demo app. Especially the loop in [buildView](https://github.com/google/ExoPlayer/blob/release-v2/demos/main/src/main/java/com/google/android/exoplayer2/demo/TrackSelectionHelper.java#L146)  does the same as your code. The trackGroups it is using are obtained from the trackSelector.getCurrentMappedTrackInfo().getTrackGroups(rendererIndex).

**Comment by pals-ric** [comment]
okay , i checked it but i have an doubt what exactly **onTrackchanged()** is doing and in which method i am getting all the data available related to bitrates and video qualities and what is the Format class functionality because as i can see from that class we are getting all available videoformat, but in new version i dont know how to get all available format for videos.

**Comment by tonihei** [comment]
The `trackGroups` parameter in the `onTracksChanged` callback contains a list of `TrackGroup`s each containing a list of `Format`s. And each `Format` in turn has its own average bitrate.

**Comment by pals-ric** [comment]
okay now I am getting all the bitrates but while i am choosing any quality video is not getting changed.there is TrackSelector.setSelectionOverride in your demo  i think this is for that bitrate selection.

**Comment by tonihei** [comment]
Yes, you need to use setSelectionOverride if you want to set the Format manually.

**Comment by pals-ric** [comment]
i have tried set selection override method in my code but its crashing because of that line.
  player.setSelectedTrack(DemoPlayer.TYPE_VIDEO, selectedPosition); what should i can give in place of that line

**Comment by tonihei** [comment]
Can you give more details (i.e. at least a stacktrace and a error message) on how setSelectionOverride is crashing your app? Also, `setSelectedTrack` doesn't look like an ExoPlayer method.

**Comment by pals-ric** [comment]
its olderversion exoplayer method inwhich i was providing selected bitrate value like **low**, **medium**, **high**, **auto** and **data saver**  
   
          public void setSelectedBitrate(String resolution) {
          if (isOfflineMode)
            return;
           List<Format> videoFormats = HlsRendererBuilder.VideoFormats;

        if (videoFormats == null || videoFormats.size() <= 1)
            return;

        resolution = resolution.toLowerCase();
        int selectedPosition = 0;
    //        Log.d(TAG, "Selected Bitrate: " + selectedBitrate);

        ArrayList<Integer> bitRateList = new ArrayList<>();

        for (int i = 0; i < videoFormats.size(); i++) {
            Format videoFormat = videoFormats.get(i);
            int bitrate = videoFormat.bitrate / 1024;
            bitRateList.add(bitrate);
        }

        if (resolution.equals("auto")) {
            resolution = "medium";
            this.selectedBitrate = 0;
        }
        int dataSaverBitrate = 0;
        try {
            if (bitRateList != null && bitRateList.size() > 0)
                dataSaverBitrate = Collections.min(bitRateList);
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        Log.d(TAG, "setSelectedBitrate - DataSaver Bitrate:" + dataSaverBitrate);
        int minBitRate = resolution.equals("data saver") ? 0 : resolution.equals("low") ? dataSaverBitrate 
    : resolution.equals("medium") ? 500 : resolution.equals("high") ? 3000 : 3136;

    //        int maxBitRate = resolution.equals("low") ? 500 : resolution.equals("medium") ? 1500 : 
    resolution.equals("high") ? 3136 : 5928;
        for (int i = 0; i < bitRateList.size(); i++) {
            int bitrate = bitRateList.get(i);
            if (bitrate > minBitRate) {
                selectedPosition = i + 1;
                selectedBitrate = bitrate;
                break;
            }
    //            if (bitrate <= maxBitRate) {
    //                selectedPosition = i + 1;
    //                Log.d(TAG, "Selected Track Number: Selecting position: " + selectedPosition);
    //                selectedBitrate = bitrate;
    //            } else
    //                break;
        }
    //        Log.d(TAG, "Selected Track Number " + selectedPosition);

        // notify the Observable that selectedBitrate just changed
        mBitrateObservable.onNext(selectedBitrate);


        player.setSelectedTrack(DemoPlayer.TYPE_VIDEO, selectedPosition);
        Log.d(TAG, "setSelectedBitrate - Bitrate:" + selectedBitrate + ", Available Bitrates:" + 
    bitRateList.toString());

    //        Log.d(TAG, "Selected Track " + player.getSelectedTrack(DemoPlayer.TYPE_VIDEO) + ", 
    TrackCount: " + player.getTrackCount(DemoPlayer.TYPE_VIDEO));
    }

this is my old method. 
in resolution i am getting low , auto ,high and other in this method.

**Comment by pals-ric** [comment]
how can i give my selected resolution in this method and where to give trackselectionoverride.

**Comment by pals-ric** [comment]
can you tell according to my code what should i give in this method 
trackSelector.setSelectionOverride(0,trackGroups,override);

**Comment by tonihei** [comment]
As documented [here](http://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/trackselection/MappingTrackSelector.html), you need to pass a renderer index, the track groups you received from mappedTrackInfo.getTrackGroups(rendererIndex), and the override specifying the new selection.

In general, we don't have the resources the debug your application code. If you want help integrating this into your code, you are probably better off posting the question on StackOverflow or similar sites. But we are of course happy to answer specific ExoPlayer API questions.

**Comment by pals-ric** [comment]
okay i will try as you have suggested.

**Comment by pals-ric** [comment]
can you help me to set the selected bitrate 
this is my method to select the bitrate

     public void setSelectedBitrate(String resolution) {
        if (isOfflineMode)
            return;
        List<Format> videoFormats = HlsRendererBuilder.VideoFormats;

        if (videoFormats == null || videoFormats.size() <= 1)
            return;

        resolution = resolution.toLowerCase();
        int selectedPosition = 0;
    //        Log.d(TAG, "Selected Bitrate: " + selectedBitrate);

        ArrayList<Integer> bitRateList = new ArrayList<>();

        for (int i = 0; i < videoFormats.size(); i++) {
            Format videoFormat = videoFormats.get(i);
            int bitrate = videoFormat.bitrate / 1024;
            bitRateList.add(bitrate);
        }

        if (resolution.equals("auto")) {
            resolution = "medium";
            this.selectedBitrate = 0;
        }
        int dataSaverBitrate = 0;
        try {
            if (bitRateList != null && bitRateList.size() > 0)
                dataSaverBitrate = Collections.min(bitRateList);
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        Log.d(TAG, "setSelectedBitrate - DataSaver Bitrate:" + dataSaverBitrate);
        int minBitRate = resolution.equals("data saver") ? 0 : resolution.equals("low") ? dataSaverBitrate 
    : resolution.equals("medium") ? 500 : resolution.equals("high") ? 3000 : 3136;

    //        int maxBitRate = resolution.equals("low") ? 500 : resolution.equals("medium") ? 1500 : 
    resolution.equals("high") ? 3136 : 5928;
        for (int i = 0; i < bitRateList.size(); i++) {
            int bitrate = bitRateList.get(i);
            if (bitrate > minBitRate) {
                selectedPosition = i + 1;
                selectedBitrate = bitrate;
                break;
            }
    //            if (bitrate <= maxBitRate) {
    //                selectedPosition = i + 1;
    //                Log.d(TAG, "Selected Track Number: Selecting position: " + selectedPosition);
    //                selectedBitrate = bitrate;
    //            } else
    //                break;
        }
    //        Log.d(TAG, "Selected Track Number " + selectedPosition);

        // notify the Observable that selectedBitrate just changed
        mBitrateObservable.onNext(selectedBitrate);


        player.setSelectedTrack(DemoPlayer.TYPE_VIDEO, selectedPosition);
        Log.d(TAG, "setSelectedBitrate - Bitrate:" + selectedBitrate + ",Available Bitrates:" + 
     bitRateList.toString());
 
    //        Log.d(TAG, "Selected Track " + player.getSelectedTrack(DemoPlayer.TYPE_VIDEO) + ", 
    TrackCount: " + player.getTrackCount(DemoPlayer.TYPE_VIDEO));
      }

**Comment by pals-ric** [comment]
can you tell what is override?

**Comment by ojw28** [comment]
Closing because this falls beyond the scope of this issue tracker. There's only so much help we can provide on what are effectively application development issues, unfortunately. It also looks like you're still using ExoPlayer V1, which was replaced by V2 a long time ago now. When filing issues, please consider whether they are actual issues relating to ExoPlayer, or more general questions that are already answered in the demo app code.
