### ISSUE TITLE
Proguard Rule for HLS video

### ISSUE THREAD

**Issue by Kiran89kumar** [google/ExoPlayer#4037]
Video player is getting struck for pro-guard enable application while playing HLS video
What should be the proper proguard rule.

**Comment by tonihei** [comment]
You shouldn't need to configure Proguard for ExoPlayer yourself because it's already pre-configured. If you think there is an issue, please fill out the [issue template](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE) and add some more details on how to reproduce your problem.
