### ISSUE TITLE
Close caption: on off isssue

### ISSUE THREAD

**Issue by sathishkumar1392** [google/ExoPlayer#4046]
**Issue description**
Close caption: I have both audio and video m3u8 URL. Now the URL come with CC turn off  initial state  the URL is coming from the Amazon with transcription.I want to turn on CC by clicking CC button. They issue is  not showing CC.i shared my code below and shared hls stream url for audio.Can you test and tell me
My code was turn manually
trackSelector.setRendererDisabled(2, false);
trackSelector.clearSelectionOverrides(2);
**Reproduction steps**

https://s3-eu-west-1.amazonaws.com/cyrano-temp/test-audio/aa10a5e5-0d88-dac7-400f-f20a7dce6841.m3u8

**Version of ExoPlayer**

Exoplayer version 2.6.0

**Device(s) and version(s) of Android being used**
Device: Nexus 5x,
OS: Android 8.

**Comment by tonihei** [comment]
Tested your stream and it works perfectly (including the captions).

**Comment by ojw28** [comment]
Your code for manually enabling the subtitle is not sufficient. You're un-disabling the renderer and clearing the selection override, but unless you've previously disabled the renderer and/or set a selection override, you're not actually changing anything. You need to actually select the track you want. If you know the language you can do something like:
```
trackSelector.setParameters(
    trackSelector.getParameters().buildUpon().setPreferredTextLanguage("en").build());
```
Alternatively you can set an explicit selection override, which is what the demo app does.

As @tonihei mentions, the demo app allows selection of the text track in this case, and it appears to work fine. If you want to inspect what calls the demo app is making on the track selector when you enable the track in the UI, you should be able to do that fairly easily with a debugger.
