### ISSUE TITLE
Using ffmpeg to play eac3 and ac3 audio

### ISSUE THREAD

**Issue by loredana2314** [google/ExoPlayer#4048]
Issue description
I am trying to use ffmpeg extension in demo app of exoplayer version 2.3.1 (also tried with 2.7.1)
In my last attempt I used COMMON_OPTIONS="\
    --target-os=android \
    --enable-shared \
    --enable-avresample \
    --enable-decoder=vorbis \
    --enable-decoder=opus \
    --enable-decoder=flac \
	--enable-decoder=eac3 \
	--enable-decoder=ac3 \
    "
as I need eac3 and ac3 audio format.
I used Linux to fetch and build ffmpeg and windows to generate an apk with extensions.

Reproduction steps
After building I try to play https://tungsten.aaplimg.com/VOD/bipbop_adv_example_v2/master.m3u8 but it doesn't work.

Version of ExoPlayer being used
2.3.1
Device(s) and version(s) of Android being used
Quad-Core Enjoy TV Box, Android 5.1.1

**Comment by tonihei** [comment]
I tried building the ffmpeg extension with the parameters you used - and was also not able to play eac3 and ac3 audio formats. 

However, when using the COMMON_OPTIONS in our [README](https://github.com/google/ExoPlayer/blob/dev-v2/extensions/ffmpeg/README.md) with added "--enable-decoder=eac3 --enable-decoder=ac3", both formats work as expected. I assume some of the additional options make it work, although I can't pinpoint which one without testing them one by one. @andrewlewis may be able to give further insight.

**Comment by andrewlewis** [comment]
I'm not sure why it doesn't work with those options. The additional options in our readme only seem to be disabling features.

**Comment by loredana2314** [comment]
[exoplayerlogs1.txt](https://github.com/google/ExoPlayer/files/1855955/exoplayerlogs1.txt)
Thnx for the reply, I'm also sending the log file for more details. 
I can see from there that "Loaded FfmpegAudioRenderer" is reached, but I can't understand what happens next.

**Comment by andrewlewis** [comment]
Looking at the logs, the player is still trying to use `MediaCodecAudioRenderer`, which fails. This suggests that the ffmpeg extension isn't loading correctly, or that its renderer is not taking priority over `MediaCodecAudioRenderer`. Please try following the readme instructions as Toni suggested above, and make sure you use `EXTENSION_RENDERER_MODE_PREFER` (or equivalent if you're not using `DefaultRenderersFactory`).

It's not really relevant to this issue as it doesn't related to FFmpeg, but, for what it's worth, the `AudioTrack` initialization error suggests that the `AudioCapabilities` passed to the renderer are not consistent with the actual `AudioTrack` capabilities. This could be an app bug (passing the wrong capabilities) or it could be a device-specific issue where the encodings on the `ACTION_HDMI_AUDIO_PLUG` intent are inaccurate.

**Comment by loredana2314** [comment]
[exo_mode_prefer.txt](https://github.com/google/ExoPlayer/files/1856112/exo_mode_prefer.txt)
thank you,
Here are the logs after setting EXTENSION_RENDERER_MODE_PREFER. My device doesn't respond for some time when selecting audio/ac3 or eac3. If this is a device specific problem (since I am using demo app of exoplayer version 2.3.1 without modifications), can I do anything to solve it?

**Comment by andrewlewis** [comment]
The ffmpeg extension shouldn't be affected by device-specific issues. Are you using it, or are you now trying to get `MediaCodecAudioRenderer` to work? I had a quick look in the latest logs but it wasn't obvious.

**Comment by loredana2314** [comment]
I am setting EXTENSION_RENDERER_MODE_PREFER as a parameter in ExoPlayerFactory.newSimpleInstance(). According to the instructions that's all I got. After testing in another device (tablet), it works, but I want it in Quad-Core Enjoy TV Box. Thank you.

**Comment by andrewlewis** [comment]
It sounds like `MediaCodecAudioRenderer` is still being used in preference to `FfmpegAudioRenderer` on the TV box even though`EXTENSION_RENDERER_MODE_PREFER` is set. If that's correct, the next step is to figure out why the extension isn't being loaded properly.

Is it possible that FFmpeg wasn't compiled for the for the device's [ABI](https://developer.android.com/ndk/guides/abis.html)? You can run `adb shell getprop ro.product.cpu.abi` to find out what it is. The [README](https://github.com/google/ExoPlayer/blob/dev-v2/extensions/ffmpeg/README.md) instructions compile show how to compile for armeabi-v7a, arm64-v8a and x86.

**Comment by loredana2314** [comment]
After I run the command, I get armeabi-v7a. I tested also with tablet and other boxes (android 4.4.2 and 6). The audio plays in these other devices. Is there anything else that I have to check in my device?

**Comment by andrewlewis** [comment]
Assuming the problematic device has the same ABI as one of the devices that works, I think the next step is to find the place where the extension fails to load.

There isn't much information to go on here so you'll need to debug it yourself. Please try setting a breakpoint in `FfmpegLibrary.isAvailable` and stepping through. Is an exception thrown, so the library is unavailable? For completeness, please also set a breakpoint at the start of `FfmpegAudioRenderer.supportsFormatInternal` and verify that the renderer isn't chosen because the library isn't available.

**Comment by anandsingh2903** [comment]
Hi, i have also build ffmpeg extension in demo app for ac3 audio codec and i used COMMON_OPTIONS same as read me file with --enable-decoder=eac3 and --enable-decoder=ac3 and built the extension but the demo app still cannot play ac3 audio in HLS and i think that demo app is still using default audio codec renderer rather than Ffmpeg to decode audio even though demo app is using EXTENSION_MODE_PREFER by default.

**Comment by anandsingh2903** [comment]
I am not getting Loaded FFMPEGAUDIORENDERER in my logcat that means that my ffmpegaudiorenderer is not loading properly in demo app but i had successfully built the ffmpeg extension in demo app without any issues. can't seem to understand what is the problem here.
