### ISSUE TITLE
HLS video is distorted and black/white

### ISSUE THREAD

**Issue by edikfuks** [google/ExoPlayer#405]
Hello!

I am experiencing an issue on Samsung Galaxy S4 playing HLS video. I provided couple screenshots of what the user experiences.
![screenshot_2015-04-21-11-13-04](https://cloud.githubusercontent.com/assets/2530502/7259503/9077d022-e818-11e4-99d3-7837506518f4.png)

After about 10 seconds, ExoPlayer selects a higher quality track which result in correcting the image (See the image below).

![screenshot_2015-04-21-11-12-31](https://cloud.githubusercontent.com/assets/2530502/7259493/777b0422-e818-11e4-9d84-e3251a35b8bf.png)

S4 is the only device that fails to render the video initially. The other devices support video just fine.
We are using Texture View as the Surface

Do you guys have any suggestions what could cause this error?

Sincerely,
Edward

**Comment by ojw28** [comment]
Some devices had an issue when setting maximum video dimensions on the decoder in conjuction with using TextureView. The problem is discussed in https://github.com/google/ExoPlayer/issues/58. Unfortunately, you probably need to use SurfaceView instead on the affected devices.

**Comment by JanKokalj** [comment]
Are there any downsides to not using setMaxVideoDimensions method ? I Commented it out in library's HlsChunkSource class and now it works fine on S4.

**Comment by ojw28** [comment]
Some devices rely on the maximum video dimensions being passed (so yes, downsides include the decoder crashing).

**Comment by JanKokalj** [comment]
So one solution would be to manually set correct maxWidth & maxHeight for each quality stream? Is this possible?

**Comment by ojw28** [comment]
You can't change it without recreating the decoder, which wouldn't be completely seamless. You can see what it looks like by removing calls to setMaxVideoDimensions and then also ensuring codecIsAdaptive is set to false in MediaCodecTrackRenderer.

**Comment by JanKokalj** [comment]
That would work but It defeats the purpose of HLS. Maybe we will try to "blacklist" S4 from server and disable adaptive streaming for this device (and possible others if we find them)

**Comment by ojw28** [comment]
It doesn't really completely defeat the purpose of HLS. When I said "not completely seamless", what I meant is that you might get a few frames dropped across the format switch. It's still a much better experience than no adaptation, in which case you'll likely receive either sub-optimal quality or an elevated number of re-buffer events.
