### ISSUE TITLE
keep player playing even some of the renderer is not getting enough buffer

### ISSUE THREAD

**Issue by cool-benson** [google/ExoPlayer#4051]
### Issue description
Hi,
  My team is creating a VR Streaming app which utilize #2855 solution. And we want playback not to be blocked when only one renderer not getting enough buffer. For example we have six video renderer, one for each face of one cube, and we are looking at only face 1,2. Then when we don't have enough buffer on face 5 the play back status change to loading(I assume). 

**So is it possible to keep player playing even when some of the renderer is not getting enough buffer, and able to recover synchronized playback when getting enough buffer?**

Any pointers, suggestions is appreciated. Thanks

### Version of ExoPlayer being used
I git cloned the repo `commit b6155d2e08580dc07cd249d6439beacd99ca08b2 (HEAD -> release-v2, tag: r2.7.1, origin/release-v2, origin/HEAD)`

**Comment by tonihei** [comment]
The internal playback loop checks each renderer whether it's either ready to play (that usually corresponds to having enough buffer) or ended (that is, the last sample has been rendered). If you want to check the code for debugging, this happens [here](https://github.com/google/ExoPlayer/blob/b6155d2e08580dc07cd249d6439beacd99ca08b2/library/core/src/main/java/com/google/android/exoplayer2/ExoPlayerImplInternal.java#L518).

Only if all renderers report being ready or ended, the player stays (or enters) the ready state. So, assuming you follow the suggestion in #2855 of having multiple video renderers, you would need to ensure that all renderers report being ready even if some of them aren't actually ready. One way to change the default behaviour is to subclass `MediaCodecVideoRenderer` and to overwrite `isReady()`. 

A couple of points to think about if you do this:
- There may be cases where all of the renderers are not ready. So you probably need some logic to decide how many renderers are enough. 
- I never did such a tweak, but be aware that other methods of the renderer may assume a certain internal state which may be violated when you overwrite the `isReady` method. This might not be the case, but keep an eye on any unusual behavior.
- The renderer not getting enough buffer but still reported as ready will drop frames to catch up. Not sure about your synchronization requirements, but this may temporarily look odd and out of sync with the other cube faces.

If you get this running, it would be nice to share some feedback what else was needed to make this work in case other people have similar requirements.

**Comment by cool-benson** [comment]
Thanks for timely response, I'll try it out and update you. Thanks again!
