### ISSUE TITLE
Sniff FLAC files correctly if they have ID3 headers

### ISSUE THREAD

**Issue by tangmingscau** [google/ExoPlayer#4055]
On my side, I have a FLAC music format music, which has a ID3 head on the head of the format signature, which leads to FlacExtractor.sniff judgment error. He thinks he is not FLAC music.

I will send this FLAC music to you by mailbox

**Comment by ojw28** [comment]
The content provided doesn't download for me. When I click the link I get a spinner indefinitely. Please can you attach a sample directly to your email, or else use a file sharing service that works reliably (e.g. DropBox / Google Drive).

Note that ID3 tags at the start of FLAC files is not really a thing. As per the [FLAC FAQs](https://xiph.org/flac/faq.html#general__tagging):

> ... you should not expect any tags beside FLAC tags to be supported in applications; some implementations may not even be able to decode a FLAC file with ID3 tags

We'll take a look anyway if you're able to provide content we can access, and perhaps look into handling the case if it seems worthwhile.

**Comment by tangmingscau** [comment]
ok,there is link here.  
[https://note.youdao.com/share/?id=65c4866029e36626bd7b0f9e542fdcd7&type=note#/](url)

**Comment by ojw28** [comment]
@botaydotcom - This fits nicely under the "extractor stuff" umbrella. `Mp3Extractor` has code for sniffing/parsing id3 metadata, so it's probably a case of copying/sharing that with `FlacExtractor`. We should probably actually parse the metadata and put it into the `Format`, add a `FLAG_DISABLE_ID3_METADATA` flag as in `Mp3Extractor`, and plumb that through `DefaultExtractorsFactory`.

Implementation points:
* It's important to adhere to how `Extractor.sniff` is defined.
* It should not be assumed that `sniff` will be called (it's valid to only call `read`, if the calling code knows that it already has the correct extractor).

**Comment by tangmingscau** [comment]
Is it possible for me to understand that there will be a new version to solve this problem?
Thanks

**Comment by botaydotcom** [comment]
Yes, there will be a new version to solve this problem. However, this will not be worked on very soon because I'm working some other tasks on hand (expect ~1 month).
