### ISSUE TITLE
PlaybackNotificationManager: Allow option to hide play/pause icon (dev-2 branch)

### ISSUE THREAD

**Issue by vishal-i4gs** [google/ExoPlayer#4056]
I would also like to say that it would also be good if we could also omit the “PLAY”/”PAUSE” icon from the notification since all the rest are being able to be removed by certain function calls it would be great if this could be done too. Since we might need a custom action bar which has actions arranged in a certain manner and pattern.

```
public class PlayerNotificationManager {
protected List<String> getActions(Player player) {
if (player.getPlayWhenReady()) {
  stringActions.add(ACTION_PAUSE);
} else if (!player.getPlayWhenReady()) {
  stringActions.add(ACTION_PLAY);
}
```
It doesn't seem to guarded by any boolean or int variable like the others.

**Comment by ojw28** [comment]
Fixed in 301bb3ada44c2115819eb43582d8287a35d3fcad
