### ISSUE TITLE
can't parse some H.264 files

### ISSUE THREAD

**Issue by Ood-Tsen** [google/ExoPlayer#406]
The function parseAvcCFromParent in the file [AtomParsers.java] (https://github.com/google/ExoPlayer/blob/dev/library/src/main/java/com/google/android/exoplayer/extractor/mp4/AtomParsers.java) raise an exception.
>  private static List<byte[]> parseAvcCFromParent(ParsableByteArray parent, int position) {
>    parent.setPosition(position + Atom.HEADER_SIZE + 4);
>    // Start of the AVCDecoderConfigurationRecord (defined in 14496-15)
>    int nalUnitLength = (parent.readUnsignedByte() & 0x3) + 1;
>    if (nalUnitLength != 4) {
>      // readSample currently relies on a nalUnitLength of 4.
>      // TODO: Consider handling the case where it isn't.
>      throw new IllegalStateException();
>    }

But the nalUnitLength may not be 4 in some H.264 videos (e.q.  [video264_fr30.mp4](https://www.dropbox.com/s/2aw8p4asc7cj3qc/video264_fr30.mp4?dl=0)).

**Comment by ojw28** [comment]
Thanks for raising this issue. The new Extractor model in the dev branch actually allows us to support this pretty easily (which was not the case previously). We'll get this done.

**Comment by Ood-Tsen** [comment]
thanks for the quick fix.
