### ISSUE TITLE
Setting PlaybackParameters when paused 

### ISSUE THREAD

**Issue by komissarovdenis** [google/ExoPlayer#4064]
If set a new params via setPlaybackParameters() when player on pause and try to get them back via getPlaybackParameters() you will receive a previous one until playing.

In my case it all considering about playback speed.

lib version 2.7.2

**Comment by ghost** [comment]
@komissarovdenis how did you overcome this problem ?

**Comment by komissarovdenis** [comment]
@kadymuhammad I just read method's comment where they told about applying new params. And you should subscribe to listen changes

So, as a result I just keep params what I want to set and return them before applied

There's a java doc:

>  /**
>    * Attempts to set the playback parameters. Passing {@code null} sets the parameters to the
>    * default, {@link PlaybackParameters#DEFAULT}, which means there is no speed or pitch adjustment.
>    * <p>
>    * Playback parameters changes may cause the player to buffer.
>    * {@link EventListener#onPlaybackParametersChanged(PlaybackParameters)} will be called whenever
>    * the currently active playback parameters change. When that listener is called, the parameters
>    * passed to it may not match {@code playbackParameters}. For example, the chosen speed or pitch
>    * may be out of range, in which case they are constrained to a set of permitted values. If it is
>    * not possible to change the playback parameters, the listener will not be invoked.
>    *
>    * @param playbackParameters The playback parameters, or {@code null} to use the defaults.
>    */
