### ISSUE TITLE
Exoplayer is stuck after playing once even though setting to loop

### ISSUE THREAD

**Issue by lion4509** [google/ExoPlayer#4069]
### Issue description
Exoplayer is stuck after playing once even though setting to loop

### Reproduction steps
```
TrackSelection.Factory videoTrackSelectionFactory =
					new AdaptiveTrackSelection.Factory(BANDWIDTH_METER);
trackSelector = new DefaultTrackSelector(videoTrackSelectionFactory);
trackSelector.setTunnelingAudioSessionId(C.generateAudioSessionIdV21(this));
exoPlayer = ExoPlayerFactory.newSimpleInstance(this, trackSelector);
exoPlayer.addListener(this);

simpleExoPlayerView.setPlayer(exoPlayer);
exoPlayer.setPlayWhenReady(true);
exoPlayer.setRepeatMode(Player.REPEAT_MODE_ALL);
debugViewHelper = new DebugTextViewHelper(exoPlayer, debugTextView);
debugViewHelper.start();
			
String uri = "udp://224.1.1.2:1234";

DataSource.Factory udsf = new UdpDataSource.Factory() {
	@Override
	public DataSource createDataSource() {
		return new UdpDataSource(null, 3000, 100000);
	}
};

ExtractorMediaSource.Factory videoSource = new ExtractorMediaSource.Factory(udsf);
exoPlayer.prepare(videoSource.createMediaSource(Uri.parse(uri)));
exoPlayer.setPlayWhenReady(true);
```
### Link to test content
I uploaded stream file, IPStreamer, setting screenshot.
https://drive.google.com/open?id=1atVzsUmnVXDwLNZnUNcjgqdlMev-Voyg

### Version of ExoPlayer being used
implementation 'com.google.android.exoplayer:exoplayer:2.7.1'

### Device(s) and version(s) of Android being used
Android 8.0 (Oreo) device in development

### A full bug report captured from the device
04-02 16:31:57.361 D       12634    EventLogger                         state [0.00, true, I]
04-02 16:31:57.367 D       12634    EventLogger                         state [0.01, true, B]
04-02 16:31:57.391 D       12634    EventLogger                         sourceInfo [periodCount=1, windowCount=1
04-02 16:31:57.392 D       12634    EventLogger                           period [?]
04-02 16:31:57.392 D       12634    EventLogger                           window [?, false, false]
04-02 16:31:57.392 D       12634    EventLogger                         ]
04-02 16:31:57.392 D       12634    EventLogger                         loading [true]
04-02 16:32:00.395 D       12634    EventLogger                         videoEnabled [3.04]
04-02 16:32:00.396 D       12634    EventLogger                         audioEnabled [3.04]
04-02 16:32:00.396 D       12634    EventLogger                         Tracks [
04-02 16:32:00.396 D       12634    EventLogger                           Renderer:0 [
04-02 16:32:00.396 D       12634    EventLogger                             Group:0, adaptive_supported=N/A [
04-02 16:32:00.397 D       12634    EventLogger                               [X] Track:0, id=1/256, mimeType=video/mpeg2, res=1920x1080, supported=YES
04-02 16:32:00.397 D       12634    EventLogger                             ]
04-02 16:32:00.397 D       12634    EventLogger                           ]
04-02 16:32:00.397 D       12634    EventLogger                           Renderer:1 [
04-02 16:32:00.397 D       12634    EventLogger                             Group:0, adaptive_supported=N/A [
04-02 16:32:00.397 D       12634    EventLogger                               [X] Track:0, id=1/257, mimeType=audio/ac3, channels=2, sample_rate=44100, supported=YES
04-02 16:32:00.397 D       12634    EventLogger                             ]
04-02 16:32:00.397 D       12634    EventLogger                           ]
04-02 16:32:00.397 D       12634    EventLogger                         ]
04-02 16:32:00.402 D       12634    EventLogger                         videoDecoderInitialized [3.04, OMX.broadcom.video_decoder]
04-02 16:32:00.402 D       12634    EventLogger                         videoFormatChanged [3.04, id=1/256, mimeType=video/mpeg2, res=1920x1080]
04-02 16:32:00.403 D       12634    EventLogger                         audioDecoderInitialized [3.05, OMX.google.raw.decoder]
04-02 16:32:00.404 D       12634    EventLogger                         audioFormatChanged [3.05, id=1/257, mimeType=audio/ac3, channels=2, sample_rate=44100]
04-02 16:32:00.404 D       12634    EventLogger                         audioSessionId [113]
04-02 16:32:00.690 D       12634    EventLogger                         state [3.33, true, R]
04-02 16:32:21.503 D       12634    EventLogger                         state [24.15, true, B]
04-02 16:32:29.703 D       12634    EventLogger                         state [32.34, true, R]
04-02 16:32:59.597 D       12634    EventLogger                         state [62.24, true, B]

**Comment by andrewlewis** [comment]
I tried playing the provided TS stream in the demo app with `REPEAT_MODE_ALL` and it played back and looped fine on Nexus Player. This setup doesn't use `UdpDataSource`.

Please could you try playing the stream on another released device (not one that's in development) and also separately without `UdpDataSource`, so we can try to narrow down what's causing the failure? Please also provide a full bug report captured with `adb bugreport` (here or via email to `dev.exoplayer@gmail.com`). At the moment it's unclear how the player is 'stuck'; is it in the buffering state or stalled while ready?

**Comment by lion4509** [comment]
Please fine attached bugreport.
Thanks, 
-----Original Message-----

**Comment by lion4509** [comment]
It is in the buffering state after playing once. I sent the bug report to `dev.exoplayer@gmail.com`.

If using `VLC player` with `UdpDataSource`, it played back and looped fine but not `IPStreamer` tool.
It is necessary to use `IPStreamer` for manufacturing.

Do I need to edit my code or something else?

**Comment by andrewlewis** [comment]
Are you saying that the stream plays fine when it's served via VLC?

**Comment by lion4509** [comment]
Yes, it’s fine via VLC.

**Comment by lion4509** [comment]
Is there any updates?

**Comment by andrewlewis** [comment]
It seems likely that the problem is with IPStreamer, not ExoPlayer.

**Comment by lion4509** [comment]
Even with VLC player, buffering state is frequent. There are also occasions that only audio works but not video. (renderedOutputBufferCount for video is stopped / renderedOutputBufferCount for audio is increasing)

What about the source code that I wrote before? Is there any point to edit for playing UDP stream?

**Comment by lion4509** [comment]
And I tested this code on Nexus player.
The result is the same as before.

**Comment by lion4509** [comment]
Any updates?

**Comment by andrewlewis** [comment]
If I understand correctly, you've tried two options for serving the content: VLC and IPStreamer. With VLC the content plays fine with ExoPlayer but with IPStreamer it doesn't. I don't think we can offer much help here beyond suggesting that you figure out what's different in the behavior of IPStreamer vs VLC.

If you have evidence that there's a bug on the ExoPlayer side please provide information about what's going on and we can reopen. I'll close for now as I don't think there's anything else we can do.
