### ISSUE TITLE
Read cenc:pssh in a ContentProtection element in the MPD

### ISSUE THREAD

**Issue by pakerfeldt** [google/ExoPlayer#407]
From what I understand a ContentProtection tag in the DASH manifest may contain `<cenc-pssh>` element which in turn contains a pssh box. However, ExoPlayer seem unable to parse that information out. Should it handle those elements or can it be read through other means?

**Comment by ojw28** [comment]
I think the contents of a ContentProtection element are scheme/type specific. Could you paste just the ContentProtection part of the manifest that you're trying to use, and we'll take a look? Thanks!

**Comment by pakerfeldt** [comment]
I don't think it's scheme specific since it seems to be the same with PlayReady whereas we're using Widevine now, and also the pssh stuff is part of mp4 spec.

This is what is look like:
`<ContentProtection schemeIdUri="urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed">
          <cenc:pssh>...</cenc:pssh>
        </ContentProtection>`

**Comment by pakerfeldt** [comment]
I updated the xml snippet in previous comment with the entire AdaptationSet since I realized we have the ContentProtection per Representation. I haven't deep dived into the code yet but in ExoPlayer the AdaptationSet class have a List<ContentProtection> and Representation class doesn't seem to refer to ContentProtection at all. However, it successfully pulls out the ContentProtection tag and add it to the list of ContentProtections on the AdaptationSet. Not sure how I'm supposed to map a ContentProtection in AdaptationSet to a specific Representation though.

**Comment by ojw28** [comment]
- Ah, you're right about this applying to all schemes. Apparently the Section 11 of the Second Edition of ISO/IEC FDIS 23001-7:2014 defines this element for all ContentProtection descriptors.

- There's an interoperability recommendation made by the DASH IF that ContentProtection should only exist at the AdaptationSet level, and not at the Representation level. What tool did you use to generate the manifest? I know that edash-packager doesn't currently adhere to the recommendation, but my understanding is that it will be updated to do so soon. If you used another tool, it's worth pointing this out to them.

- MediaPresentationDescriptionParser does already handle bubbling up of ContentProtection elements from Representations to their parent AdaptationSets, provided they're consistent within an AdaptationSet, which you'll probably find to be the case for your example (if it's not you have bigger problems).

So there's not actually much work needed here. It's more or less just a case of parsing the PSSH box from the element, pulling out the data for the scheme UUID, and setting it as ContentProtection.data. Everything else is plumbed in already, so doing that should result in things working correctly.

**Comment by ojw28** [comment]
Can you paste in an example contents of the cenc:pssh element?

**Comment by pakerfeldt** [comment]
We're using edash-package. Will make sure we have it on AdaptationSet level instead. An example of open the cenc-pssh element can be found here: http://shaka-player-demo.appspot.com/assets/oops_cenc_pssh.mpd

**Comment by ojw28** [comment]
Do you happen to know what license server hands out licenses for that (assuming it's test content)? I've piped the data through (not yet pushed, but I have it locally), but can't test it without this information.

**Comment by pakerfeldt** [comment]
Not entirely sure, perhaps `http://widevine-proxy.appspot.com/proxy` work. Otherwise I could probably get back to you tomorrow on that. However, don't expect it to play. For other reasons, ExoPlayer can't seem to handle the segment urls in that mpd. Probably their weird baseURL that starts with `//`. If if's to any help, I'll happily try your local fix.

**Comment by ojw28** [comment]
It should just be a case of doing this: https://github.com/google/ExoPlayer/commit/089aafa526c28c649ba202b222a8b6eb32f34038

Please give it a try locally, and let me know if it works as expected!

**Comment by pakerfeldt** [comment]
I'll will try this tomorrow and get back to you. Thanks for swift response!

**Comment by pakerfeldt** [comment]
Ok, so I just tried it and it seem to extract the data part of the pssh box nicely. I'm not in a state where I can try to use this pssh data to do key requests just yet though. Playback still works but pssh is also in the mp4 init box.

While I have you on the line. What's the strategy for merging back to master (from dev)? Besides this of course, I'm also interested in the changes with passing a UriDataSource to ManifestFetcher for manifest requests that was added a while back.

**Comment by pakerfeldt** [comment]
Btw, this seems to be the license server for the previous mpd:
`http://dash-mse-test.appspot.com/api/drm/widevine?drm_system=widevine&amp;source=YOUTUBE&amp;video_id=03681262dc412c06&amp;ip=0.0.0.0&amp;ipbits=0&amp;expire=19000000000&amp;sparams=ip,ipbits,expire,source,video_id,drm_system&amp;signature=289105AFC9747471DB0D2A998544CC1DAF75B8F9.18DE89BB7C1CE9B68533315D0F84DF86387C6BB3&amp;key=test_key1`

**Comment by pakerfeldt** [comment]
I can confirm that I successfully managed to request license keys using the cenc-pssh element from the manifest using your commit.

**Comment by ojw28** [comment]
Thanks. I will merge a slight variant of that commit soon (there needs to be a null check in the DashChunkSource object to make sure pssh in the manifest is given preference).

**Comment by Pierpaolo1992** [comment]
Hi, i've a problem. I want to playback an encrypted mp4 file (crypted using MP4Box tool, and an drm.xml) using DASH.
But console tells me that error:
2Failed to generate a license request DOMException: No supported PSSH box found.

Well, this is drm.xml (used for encryption in MP4Box):

`<GPACDRM type="CENC AES-CTR">
 <DRMInfo type="pssh" version="0">
  <BS ID128="9A04F07998404286AB92E65BE0885F95"/>
  <BS data="application/data;base64:ACE125"/>
  <BS sourceFile="cenc_blob.bin"/>
 </DRMInfo>

 <DRMInfo type="pssh" version="1" cypherOffset="9" cypherKey="0x6770616363656E6364726D746F6F6C31" cypherIV="0x00000000000000000000000000000001">
  <BS ID128="6770616363656E6364726D746F6F6C31"/>
  <BS value="2" bits="32"/>
  <BS ID128="0x279926496a7f5d25da69f2b3b2799a7f"/>
  <BS ID128="0x676cb88f302d10227992649885984045"/>
  <BS bits="8" string="CID=Toto"/>
  <BS ID128="0xccc0f2b3b279926496a7f5d25da692f6"/>
  <BS ID128="0xccc0f2b3b279926496a7f5d25da692d6"/>
 </DRMInfo>
 
 <CrypTrack trackID="2" IsEncrypted="1" IV_size="16" first_IV="0x0a610676cb88f302d10ac8bc66e039ed" saiSavedBox="senc">
   <key KID="0x279926496a7f5d25da69f2b3b2799a7f" value="0xccc0f2b3b279926496a7f5d25da692f6"/>
 </CrypTrack>

</GPACDRM> `

This is .mpd (generated by MP4Box):

`<?xml version="1.0"?>

<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" minBufferTime="PT1.500S" type="static" mediaPresentationDuration="PT0H4M30.118S" maxSegmentDuration="PT0H0M3.994S" profiles="urn:mpeg:dash:profile:full:2011" xmlns:cenc="urn:mpeg:cenc:2013">
 <ProgramInformation moreInformationURL="http://gpac.io">
  <Title>audio-enc.mpd generated by GPAC</Title>
 </ProgramInformation>

 <Period duration="PT0H4M30.118S">
  <AdaptationSet segmentAlignment="true" lang="und">
   <ContentProtection schemeIdUri="urn:mpeg:dash:mp4protection:2011" value="cenc" cenc:default_KID="27992649-6a7f-5d25-da69-f2b3b2799a7f">
    <cenc:pssh>BASE64_PSSH</cenc:pssh>
    </ContentProtection>

   <Representation id="1" mimeType="audio/mp4" codecs="mp4a.40.2" audioSamplingRate="44100" startWithSAP="1" bandwidth="103460">
    <AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2"/>
    <SegmentList timescale="44100" duration="176400">
     <Initialization sourceURL="segment_audioinit.mp4"/>
	<cenc:pssh>BASE64_PSSH</cenc_pssh>
     <SegmentURL media="segments/segment_audio1.m4s"/>
     <SegmentURL media="segments/segment_audio2.m4s"/>
             .....

     <SegmentURL media="segments/segment_audio67.m4s"/>
     <SegmentURL media="segments/segment_audio68.m4s"/>
    </SegmentList>
   </Representation>
  </AdaptationSet>
 </Period>
</MPD>`

This is html page:



<!doctype html>
<html>
    <head>
        <title>Dash.js Rocks</title>
        <style>
            video {
                width: 640px;
                height: 360px;
            }
        </style>
    </head>
    <body>
        <div>
            <video id="videoPlayer" controls></video>
        </div>
        <script src="http://cdn.dashjs.org/latest/dash.all.min.js"></script>
        <script src="js/main.js"></script>

        <script>
            (function(){
                var url = "http://localhost:8080/prova-enc/audio-enc1.mpd";
                var player = dashjs.MediaPlayer().create();
                player.initialize(document.querySelector("#videoPlayer"), url, true);
            })();
        </script>
        <script src="lib/ga.js"></script>

    </body>
</html>

This is js/main.js:

`

  'use strict';

var KEY = new Uint8Array([

  0xcc, 0xc0, 0xf2, 0xb3, 0xb2, 0x79, 0x92, 0x64,   // this is key for MP4 file
  0x96, 0xa7, 0xf5, 0xd2, 0x5d, 0xa6, 0x92, 0xf6

]);

var config = [{
    initDataTypes:['cenc'],
    audioCapabilities: [{
    contentType: 'audio/mp4; codecs="mp4a.40.2"'
  }]
}];

var video = document.querySelector('video');
if(video) {
video.addEventListener('encrypted', handleEncrypted, false);
}

navigator.requestMediaKeySystemAccess('org.w3.clearkey', config).then(
  function(keySystemAccess) {
    return keySystemAccess.createMediaKeys();
  }
).then(
  function(createdMediaKeys) {
    return video.setMediaKeys(createdMediaKeys);
   console.log('Mediakeys=', createdMediaKeys);
  }
).catch(
  function(error) {
    console.error('Failed to set up MediaKeys', error);
  }
);
;

function handleEncrypted(event) {
  console.log('encrypted event:', event);
  var session = video.mediaKeys.createSession();
  session.addEventListener('message', handleMessage, false);
  session.generateRequest(event.initDataType, event.initData).catch(
    function(error) {
      console.error('Failed to generate a license request', error);
    }
  );
}

function handleMessage(event) {
  console.log('message event: ', event);
  // If you had a license server, you would make an asynchronous XMLHttpRequest
  // with event.message as the body.  The response from the server, as a
  // Uint8Array, would then be passed to session.update().
  // Instead, we will generate the license synchronously on the client, using
  // the hard-coded KEY at the top.
  var license = generateLicense(event.message);
  console.log('license: ', license);

  var session = event.target;
  session.update(license).catch(
    function(error) {
      console.error('Failed to update the session', error);
    }
  );
}

// Convert Uint8Array into base64 using base64url alphabet, without padding.
function toBase64(u8arr) {
  return btoa(String.fromCharCode.apply(null, u8arr)).
      replace(/\+/g, '-').replace(/\//g, '_').replace(/=*$/, '');
}

// This takes the place of a license server.
// kids is an array of base64-encoded key IDs
// keys is an array of base64-encoded keys
function generateLicense(message) {
  // Parse the clearkey license request.
  var request = JSON.parse(new TextDecoder().decode(message));
  // We only know one key, so there should only be one key ID.
  // A real license server could easily serve multiple keys.
  console.assert(request.kids.length === 1);

  var keyObj = {
    kty: 'oct',
    alg: 'A128KW',
    kid: request.kids[0],
    k: toBase64(KEY)
  };
  return new TextEncoder().encode(JSON.stringify({
    keys: [keyObj]
  }));
}

`

I think that there is something missing in .mpd.. but don't know what. Can you help me?

**Comment by Pierpaolo1992** [comment]
Hi, i've a problem. I want to playback an encrypted mp4 file (crypted using MP4Box tool, and an drm.xml) using DASH.
But console tells me that error:
Failed to generate a license request DOMException: No supported PSSH box found.

This is drm.xml:

```
<GPACDRM type="CENC AES-CTR">
 <DRMInfo type="pssh" version="0">
  <BS ID128="9A04F07998404286AB92E65BE0885F95"/>
  <BS data="application/data;base64:ACE125"/>
  <BS sourceFile="cenc_blob.bin"/>
 </DRMInfo>

 <DRMInfo type="pssh" version="1" cypherOffset="9" cypherKey="0x6770616363656E6364726D746F6F6C31" cypherIV="0x00000000000000000000000000000001">
  <BS ID128="6770616363656E6364726D746F6F6C31"/>
  <BS value="2" bits="32"/>
  <BS ID128="0x279926496a7f5d25da69f2b3b2799a7f"/>
  <BS ID128="0x676cb88f302d10227992649885984045"/>
  <BS bits="8" string="CID=Toto"/>
  <BS ID128="0xccc0f2b3b279926496a7f5d25da692f6"/>
  <BS ID128="0xccc0f2b3b279926496a7f5d25da692d6"/>
 </DRMInfo>
 
 <CrypTrack trackID="2" IsEncrypted="1" IV_size="16" first_IV="0x0a610676cb88f302d10ac8bc66e039ed" saiSavedBox="senc">
   <key KID="0x279926496a7f5d25da69f2b3b2799a7f" value="0xccc0f2b3b279926496a7f5d25da692f6"/>
 </CrypTrack>

</GPACDRM> 
```

This is .mpd (generated by MP4Box):

<?xml version="1.0"?>

<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" minBufferTime="PT1.500S" type="static" mediaPresentationDuration="PT0H4M30.118S" maxSegmentDuration="PT0H0M3.994S" profiles="urn:mpeg:dash:profile:full:2011" xmlns:cenc="urn:mpeg:cenc:2013">
 <ProgramInformation moreInformationURL="http://gpac.io">
  <Title>audio-enc.mpd generated by GPAC</Title>
 </ProgramInformation>

 <Period duration="PT0H4M30.118S">
  <AdaptationSet segmentAlignment="true" lang="und">
   <ContentProtection schemeIdUri="urn:mpeg:dash:mp4protection:2011" value="cenc" cenc:default_KID="27992649-6a7f-5d25-da69-f2b3b2799a7f">
    <cenc:pssh> J5kmSWp/XSXaafKzsnmafw== </cenc:pssh>
    </ContentProtection>

   <Representation id="1" mimeType="audio/mp4" codecs="mp4a.40.2" audioSamplingRate="44100" startWithSAP="1" bandwidth="103460">
    <AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2"/>
    <SegmentList timescale="44100" duration="176400">
     <Initialization sourceURL="segment_audioinit.mp4"/>
     <SegmentURL media="segments/segment_audio1.m4s"/>
             .....
     <SegmentURL media="segments/segment_audio68.m4s"/>
    </SegmentList>
   </Representation>
  </AdaptationSet>
 </Period>
</MPD>

This is html page:

```
<!doctype html>
<html>
    <head>
        <title>Dash.js Rocks</title>
        <style>
            video {
                width: 640px;
                height: 360px;
            }
        </style>
    </head>
    <body>
        <div>
            <video id="videoPlayer" controls></video>
        </div>
        <script src="http://cdn.dashjs.org/latest/dash.all.min.js"></script>
        <script src="js/main.js"></script>

        <script>
            (function(){
                var url = "http://localhost:8080/prova-enc/audio-enc1.mpd";
                var player = dashjs.MediaPlayer().create();
                player.initialize(document.querySelector("#videoPlayer"), url, true);
            })();
        </script>
        <script src="lib/ga.js"></script>

    </body>
</html>
```

This is js/main.js:


```

  'use strict';

var KEY = new Uint8Array([

  0xcc, 0xc0, 0xf2, 0xb3, 0xb2, 0x79, 0x92, 0x64,   // this is key for MP4 file
  0x96, 0xa7, 0xf5, 0xd2, 0x5d, 0xa6, 0x92, 0xf6

]);

var config = [{
    initDataTypes:['cenc'],
    audioCapabilities: [{
    contentType: 'audio/mp4; codecs="mp4a.40.2"'
  }]
}];

var video = document.querySelector('video');
if(video) {
video.addEventListener('encrypted', handleEncrypted, false);
}

navigator.requestMediaKeySystemAccess('org.w3.clearkey', config).then(
  function(keySystemAccess) {
    return keySystemAccess.createMediaKeys();
  }
).then(
  function(createdMediaKeys) {
    return video.setMediaKeys(createdMediaKeys);
   console.log('Mediakeys=', createdMediaKeys);
  }
).catch(
  function(error) {
    console.error('Failed to set up MediaKeys', error);
  }
);
;

function handleEncrypted(event) {
  console.log('encrypted event:', event);
  var session = video.mediaKeys.createSession();
  session.addEventListener('message', handleMessage, false);
  session.generateRequest(event.initDataType, event.initData).catch(
    function(error) {
      console.error('Failed to generate a license request', error);
    }
  );
}

function handleMessage(event) {
  console.log('message event: ', event);
  // If you had a license server, you would make an asynchronous XMLHttpRequest
  // with event.message as the body.  The response from the server, as a
  // Uint8Array, would then be passed to session.update().
  // Instead, we will generate the license synchronously on the client, using
  // the hard-coded KEY at the top.
  var license = generateLicense(event.message);
  console.log('license: ', license);

  var session = event.target;
  session.update(license).catch(
    function(error) {
      console.error('Failed to update the session', error);
    }
  );
}

// Convert Uint8Array into base64 using base64url alphabet, without padding.
function toBase64(u8arr) {
  return btoa(String.fromCharCode.apply(null, u8arr)).
      replace(/\+/g, '-').replace(/\//g, '_').replace(/=*$/, '');
}

// This takes the place of a license server.
// kids is an array of base64-encoded key IDs
// keys is an array of base64-encoded keys
function generateLicense(message) {
  // Parse the clearkey license request.
  var request = JSON.parse(new TextDecoder().decode(message));
  // We only know one key, so there should only be one key ID.
  // A real license server could easily serve multiple keys.
  console.assert(request.kids.length === 1);

  var keyObj = {
    kty: 'oct',
    alg: 'A128KW',
    kid: request.kids[0],
    k: toBase64(KEY)
  };
  return new TextEncoder().encode(JSON.stringify({
    keys: [keyObj]
  }));
}

```


I think that there is something missing in .mpd.. but don't know what. Can you help me?

**Comment by pakerfeldt** [comment]
How is that related to ExoPlayer?

**Comment by Pierpaolo1992** [comment]
@pakerfeldt It's not related to ExoPlayer, but to ContentProtection in DASH.

**Comment by ojw28** [comment]
@Pierpaolo1992 You'd be best off asking questions not related to ExoPlayer on either StackOverflow or some other tracker that's actually relevant.
