### ISSUE TITLE
Make Cache more extensible

### ISSUE THREAD

**Issue by FD-** [google/ExoPlayer#4070]
I'm trying to extend ExoPlayer's caching mechanism so that content for multiple keys can be stored in a single file. The goal is to be able to download HLS in a way that I obtain a result that can be played (and seeked through) in ExoPlayer and other players. In order to reach that goal, I'm hoping to modify ExoPlayer's cache so that all ts chunks of the HLS stream are stored sequentially in one file, so that the cache storage consists of the cache index file, the HLS m3u8 manifest and a single large ts file that contains all ts chunks. I would then be able to play the file in ExoPlayer with seek support (using the index structure from the cached m3u8 manifest) and in other players such as VLC (which supports seeking in ts files).

Now, the problem is that although the Cache system is extensible, it seems to be limited to cases where a single original file is split to one or many cache files, not the other way round. I am hoping to modify the Cache system to be more extensible in that regard. I'd imagine this would work by not directly passing `File`s around, but some kind of `CacheFile` class that offers an abstraction to the underlying storage, so that it's possible to provide `OutputStream`s and `InputStream`s that are offset from the file start.

Another motivation for this change would be that AFAICT, the current caching system doesn't allow caching to external storage such as external SD cards on devices running Android 5 or newer. This is because access to these locations is only allowed via `Uri`s and the `ContentResolver`.

I'm willing to invest some time into implementation and submitting a pull request if you could give me directions how a suitable implementation of such a change would look like.

**Comment by ojw28** [comment]
I think this would require some fairly in depth changes. It's probably easier just to implement some other downloading component from scratch, to be honest, since I can't think of any easy way to adapt the existing caching mechanism for this use case. Due to the in depth nature of the changes that would be needed, it's unfortunately not something we can provide guidance on at this point. Sorry!
