### ISSUE TITLE
Which HLS version does ExoPlayer (currently) support?

### ISSUE THREAD

**Issue by DavidMihola** [google/ExoPlayer#4073]
I am sorry if I am missing something obvious but: Is there any information about which version of HLS is supported by current ExoPlayer versions? Does the supported HLS version depend in any way on the Android version the app is running on? Or does ExoPlayer support the same HLS feature set regardless of the Android version, as long it is 4.1 or higher?

Thanks for any help!

David

**Comment by andrewlewis** [comment]
- ExoPlayer doesn't rely on the HLS support in the platform, so behavior should be consistent on different versions. However, it does rely on platform content protection support and `MediaCodec` for decoding extracted data. See [supported formats](https://google.github.io/ExoPlayer/supported-formats.html#hls) for more information.
- I think the implementation doesn't target a particular draft/spec version, but instead we've tried to keep up to date on the most important and widely used features. @ojw28 or @AquilesCanta will be able to confirm/correct this, or provide more information.
- The blog post on [HLS playback in ExoPlayer](https://medium.com/google-exoplayer/hls-playback-in-exoplayer-a33959a47be7) may be useful if you're trying to prepare your streams to give the best possible performance.

**Comment by AquilesCanta** [comment]
> the implementation doesn't target a particular draft/spec version, but instead we've tried to keep up to date on the most important and widely used features.

This is correct. We basically support the latest version, but also do out best to be backwards compatible. An example of this is `EXT-X-MEDIA-SEQUENCE`, which used to be optional, but later versions made it mandatory (if absent, 0 must be assumed). A best effort approach is used to support playlist without the tag.

Hopefully this confirms @andrewlewis's second point.

**Comment by DavidMihola** [comment]
Great, thanks a lot for your replies! I think we'll just experiment with all the features that our current streaming server is supporting (which is only HLS version 3 or 4 anyway) and check back with you if we run into any troubles!

Thanks again!

**Comment by zapjonny** [comment]
FWIW
Version 7 looks like it might work EXT-X-DATERANGE 
https://github.com/google/ExoPlayer/issues/3319
http://alexzambelli.com/blog/2016/05/04/understanding-hls-versions-and-client-compatibility/
