### ISSUE TITLE
How to resolve DataSource length  in the the middle of the playback to enable seek

### ISSUE THREAD

**Issue by izderadicka** [google/ExoPlayer#4074]
Hello I do have specific question on how implement this behavior in exoplayer.

I do have an application which is playing transcoded audio files - chapters of an audiobook ( live transcoding from any format to ogg+opus - so stream length is not know in advance - stream is chunk encoded HTTP response).
To enable best experience I use progressive download - I start to read transcoded file from server as quickly as possible and store it to local file and when some data are in that file I start the player. 
When whole file is downloaded I inform related components and I want to switch/restart playback  to exactly same place in the stream (ideally that no discontinuity is audible), but this time it should take into account known data length and enable to seek within whole file.

I have been looking around a bit and get started with `CacheDataSource` - but it's actually doing slightly different thing -   it caches data as they are consumed by player - so download lasts almost as long as the  playback. Also it does not support by default caching of streams with unknown  length, but it can be changed with a flag. But it still will not enable to download it as quickly as possible.

Now I created my own cache system and related `DataSource` -  which is backed by this cache. Basically it enables to write to cache item in a separate thread, while `DataSource` can consume it if there are some data and blocks to wait for more data, if they should still come.   Now when the download is complete I'd like to signal player to reload/reopen this `Datasource` from same position, but this time it'll also get total length of stream - so it should enable seek.  
Now it works manually - if I reopen the Source with new prepare call (after download finished in the other thread) I can seek within it.
But how to make it smooth and automatic?

I have been also looking at `DynamicConcatenatingMediaSource` -  here I suppose I could be able to replace currently playing item with new one - using same data source - but how to assure that it starts at exactly same position. I'm using MediaSession extension - so it has to play well with it too - ideally not to transmit change in metadata, but only change in `PlayState` - with current position, newly discovered total duration and seek actions enabled.

I usually try to find things by myself,  but exoplayer is pretty complex beast, so I'm afraid I'd might get seriously lost while seek right solution . So any advice from experts is very much welcomed.

**Comment by andrewlewis** [comment]
#4062 probably addresses most of this: you should be able to use `CacheDataSource` for playback and a `Downloader` for downloading the media at the same time, as long the content gets split up into multiple files when cached. Please try that first and let us know if anything else comes up. Thanks!
