### ISSUE TITLE
CdmEngine::OpenSession failed after long time stress testing

### ISSUE THREAD

**Issue by Qingkui9** [google/ExoPlayer#4077]
### Issue description
We are doing stress testing to the playback functionality of an Application which is using ExoPlayer.
During the stress testing, all the android devices(200 same android 7.1 tablets)  would lose the ability of drm playback.  Re-installing the application didn't help. But the drm functionality will recover after a device reboot. The issue is about he Session Opening of the CDM session.

**03-30 00:56:47.845 I/WVCdm   (  222): CdmEngine::OpenSession
30 00:56:47.864 E/WVCdm   (  222): d2i_PKCS8_PRIV_KEY_INFO_bio returned NULL.
03-30 00:56:47.865 E/WVCdm   (  222): LoadCertificatePrivateKey: OEMCrypto_LoadDeviceRSAKey error=30**

There were three stress test cases which were invoking the player to play **Widevine drm** content every 3, 5 and 10 minutes.
For the 3 minutes playback interval test, this issue happened in 4 hours.
For the 5 minutes one, it happened in 12 hours.
For the 10 minutes one, it can pass a 16 hours test.(But I assume if the test lasted longer, it might fail too)

And I have looking into the source code of Widevine CDM, noticed there is a **Mutex lock** in the **CryptoSession::LoadCertificatePrivateKey()**  method. This lock must be unlocked by the thread that locked it.
I think this issue was because one unlock process didn't happen properly. So all the following CDM Session could not be created.

Do you guys have any clue why would this happen? 
Any advice and suggestions will be greatly appreciated!

BTW, I don't know this piece of log mean, but it happened everytime when the drm session is open, no matter the drm session opening succeed  or failed. 
03-30 00:56:47.851 W/WVCdm   (  222): Could not read /data/mediadrm/IDM1013/ay64.dat2: No such file or directory

### Reproduction steps
The stress test described above.

### Version of ExoPlayer being used
ExoPlayer 2.4.3

### Device(s) and version(s) of Android being used
Android 7.1 Tablet
(Sorry, I don't have the make or model info)

### A full bug report captured from the device
03-30 00:56:47.681 I/ExoPlayerImpl( 2512): Init ExoPlayerLib/2.4.3 [cnt, Thales-ISD, boundary, 25]
03-30 00:56:47.683 D/EventLogger( 2512): state [0.00, true, I]
03-30 00:56:47.686 D/EventLogger( 2512): positionDiscontinuity
03-30 00:56:47.716 D/EventLogger( 2512): state [0.04, true, B]
03-30 00:56:47.825 D/EventLogger( 2512): sourceInfo [periodCount=1, windowCount=1
03-30 00:56:47.825 D/EventLogger( 2512):   period [6336.79]
03-30 00:56:47.825 D/EventLogger( 2512):   window [6336.79, true, false]
03-30 00:56:47.825 D/EventLogger( 2512): ]
03-30 00:56:47.845 I/WVCdm   (  222): CdmEngine::OpenSession
03-30 00:56:47.845 I/WVCdm   (  222): Level3 Library 4445 Mar 30 2016 13:23:54
03-30 00:56:47.851 W/WVCdm   (  222): Could not read /data/mediadrm/IDM1013/ay64.dat2: No such file or directory
03-30 00:56:47.862 D/WVCdm   (  222): OEMCrypto_Initialize Level 1 success. I will use level 1.
03-30 00:56:47.864 E/WVCdm   (  222): d2i_PKCS8_PRIV_KEY_INFO_bio returned NULL.
03-30 00:56:47.865 E/WVCdm   (  222): LoadCertificatePrivateKey: OEMCrypto_LoadDeviceRSAKey error=30
03-30 00:56:47.876 I/WVCdm   (  222): Level3 Library 4445 Mar 30 2016 13:23:54
03-30 00:56:47.881 W/WVCdm   (  222): Could not read /data/mediadrm/IDM1013/ay64.dat2: No such file or directory
03-30 00:56:47.890 D/WVCdm   (  222): OEMCrypto_Initialize Level 1 success. I will use level 1.
03-30 00:56:47.913 D/EventLogger( 2512): loading [true]
03-30 00:56:47.913 D/EventLogger( 2512): Tracks [
03-30 00:56:47.913 D/EventLogger( 2512):   Renderer:0 [
03-30 00:56:47.913 D/EventLogger( 2512):     Group:0, adaptive_supported=N/A [
03-30 00:56:47.913 D/EventLogger( 2512):       [X] Track:0, id=video-1, mimeType=video/avc, bitrate=1710559, res=854x480, fps=23.976025, supported=YES
03-30 00:56:47.913 D/EventLogger( 2512):     ]
03-30 00:56:47.913 D/EventLogger( 2512):   ]
03-30 00:56:47.914 D/EventLogger( 2512):   Renderer:1 [
03-30 00:56:47.914 D/EventLogger( 2512):     Group:0, adaptive_supported=N/A [
03-30 00:56:47.914 D/EventLogger( 2512):       [X] Track:0, id=audio-en-mp4a, mimeType=audio/mp4a-latm, bitrate=756830, channels=2, sample_rate=44100, language=eng, supported=YES
03-30 00:56:47.914 D/EventLogger( 2512):     ]
03-30 00:56:47.914 D/EventLogger( 2512):     Group:1, adaptive_supported=N/A [
03-30 00:56:47.914 D/EventLogger( 2512):       [ ] Track:0, id=audio-pt-mp4a, mimeType=audio/mp4a-latm, bitrate=756830, channels=2, sample_rate=44100, language=por, supported=YES
03-30 00:56:47.914 D/EventLogger( 2512):     ]
03-30 00:56:47.914 D/EventLogger( 2512):   ]
03-30 00:56:47.914 D/EventLogger( 2512): ]
03-30 00:56:47.915 D/EventLogger( 2512): videoEnabled [0.24]
03-30 00:56:47.915 D/EventLogger( 2512): audioEnabled [0.24]
03-30 00:56:47.927 W/art     ( 2512): Suspending all threads took: 7.200ms
03-30 00:56:47.929 I/chatty  (  489): uid=1000(system) android.display expire 1 line
03-30 00:56:47.948 E/ExoPlayerImplInternal( 2512): Renderer error.
03-30 00:56:47.965 I/MediaDrm( 2512): Drm event (1,0)
03-30 00:56:47.967 D/EventLogger( 2512): audioFormatChanged [0.29, id=audio-en-mp4a, mimeType=audio/mp4a-latm, bitrate=756830, channels=2, sample_rate=44100, language=eng]
03-30 00:56:47.967 D/EventLogger( 2512): videoFormatChanged [0.29, id=video-1, mimeType=video/avc, bitrate=1710559, res=854x480, fps=23.976025]
03-30 00:56:48.023 I/art     ( 2512): Background partial concurrent mark sweep GC freed 29951(2MB) AllocSpace objects, 164(9MB) LOS objects, 40% free, 8MB/13MB, paused 13.358ms total 260.387ms

**Comment by ojw28** [comment]
@wvpaf - please take a look

**Comment by wvpaf** [comment]
please attach a full ADBBugreport.
thanks.

**Comment by Qingkui9** [comment]
@wvpaf Hi, ADB log is attached. Please let me know if you need more info.
[192.100.9.1.logcat.zip](https://github.com/google/ExoPlayer/files/1876674/192.100.9.1.logcat.zip)

I will get and attach the ADBBugreport.

**Comment by Qingkui9** [comment]
[bugreport-118.05.01.00-2018-04-09-11-17-11.zip](https://github.com/google/ExoPlayer/files/1890573/bugreport-118.05.01.00-2018-04-09-11-17-11.zip)

@wvpaf Hi, bug report is attached. Please take a look and let me know if you need anything else.

**Comment by fredgc** [comment]
Unfortunately, there is a resource leak in the privacy mode code that results in the error "d2i_PKCS8_PRIV_KEY_INFO_bio returned NULL" when we try to load the service certificate.  The leak is related to thread local variables being created each time the plugin is loaded, and never released.

This has been fixed by using the new HAL interface for the plugin introduced inj Android Oreo,

The only work around that we can think of is to restart the mediadrm service.  The easiest way to do that is just reboot the device.

I am not seeing any problem with locks.  I think that might be a red herring.  If you are sure that is causing problems, please re-open this bug or open a new one.  Thanks.

**Comment by Qingkui9** [comment]
@fredgc Thank you for the response. Is it possible to restart the mediadrm service without rebooting the device?

**Comment by fredgc** [comment]
If the device is rooted, you can use adb to restart the service.  I don't know of another way.
