### ISSUE TITLE
maybe ffmpeg not work reasonable?

### ISSUE THREAD

**Issue by tangmingscau** [google/ExoPlayer#4081]
first use the EXTENSION_RENDERER_MODE_PREFER mode.
          I try to play FLAC music through ffmpeg, and ffmpeg has a FLAC decoder, 
      and if I don't compile the extension/flac library, exoplayer will report a mistake without a suitable extractor.
      If I compile the extension/flac library, but I delete the libFlac.so file, there is an error as well, 
      because flacDecoderJni is not working. Also, I tried to change the MimeTypes.AUDIO_RAW in the FlacExtractor.read () method to MimeTypes.AUDIO_FLAC, which did go to ffmpegAudioRender, but still failed to decode.
          The reason why I test so much is that I want to add ape format support in exoPlayer player through ffmpeg. So I want to understand the working process of ffmpegAudioRendener. But it's a little confused now.
        there is a test music 
      [http://note.youdao.com/noteshare?id=65c4866029e36626bd7b0f9e542fdcd7](url)
        could you give me some idea?

**Comment by andrewlewis** [comment]
It looks like `FlacExtractor` decodes the stream to PCM audio, so it's not possible to use this in conjunction with the ffmpeg extension.

Do you have the option to put the FLAC audio stream in a Matroska container (for example) instead of a .flac file? Then you could remove the dependency on the flac extension and just depend on the ffmpeg extension.

**Comment by tangmingscau** [comment]
Finally, I confirmed that the problem was that the APK installation of the ffmpeg so library failed, so that ffmpeg did not work properly, but it was true that a FLAC music file could not be played through ffmpeg, but an ordinary AAC music could be played through ffmpeg.
