### ISSUE TITLE
Share a video that is streaming from API

### ISSUE THREAD

**Issue by priyakar** [google/ExoPlayer#4087]
I have tried searching and I cannot find the answer anywhere and I really need to know whether or not ExoPlayer has the following functionality:
I am making an API call which has HLS stream that the exo player is loading and playing. I need to implement a feature to share this video. I need to know whether I can get access to these files exoplayer has downloaded so that I can convert it to a .mp4 format and share it out to other social media apps?

**Comment by ojw28** [comment]
This is not something we support, sorry!
