### ISSUE TITLE
DefaultTimeBar is not reacted on rotated view

### ISSUE THREAD

**Issue by YukihiroMori-Bascule** [google/ExoPlayer#4089]
I use PlayerView on rotated FrameLayout by setRotation.
Other component (ex. play/pause button) are reacted by touch event. But DefaultTimeBar is not working.

How to work it on the rotated View ?

**Comment by YukihiroMori-Bascule** [comment]
I tried to resume DefaultTimeBar. 
Maybe, DefaultTimeBar#resolveRelativeTouchPosition has to consider view rotation.

Because, DefaultTimeBar#onTouchEvent is called by Touch Event. And, then I change some output value, DefaultTimeBar worked on rotated View.

But, it is very restrictive deal.
```
Point touchPosition = resolveRelativeTouchPosition(event);
int x = touchPosition.x;
int y = touchPosition.y;
if(r == 90.0f){
    x = touchPosition.y;
    y = 60;
}
```

**Comment by YukihiroMori-Bascule** [comment]
I resolved it!
So, we have to consider rotation, and resume position.
```
Point touchPosition = resolveRelativeTouchPosition(event);
double rad = (360.0f - r)/ 180.0f * Math.PI;
int x = (int)(touchPosition.x * Math.cos(rad) - touchPosition.y * Math.sin(rad));
int y = (int)(touchPosition.x * Math.sin(rad) + touchPosition.y * Math.cos(rad));
```

**Comment by YukihiroMori-Bascule** [comment]
I resolved it!
So, we have to consider rotation, and resume position.
```
Point touchPosition = resolveRelativeTouchPosition(event);
double rad = (360.0f - r)/ 180.0f * Math.PI;
int x = (int)(touchPosition.x * Math.cos(rad) - touchPosition.y * Math.sin(rad));
int y = (int)(touchPosition.x * Math.sin(rad) + touchPosition.y * Math.cos(rad));
```

**Comment by andrewlewis** [comment]
To do this in general-purpose way, wouldn't we need to take into account the transform matrix of the `DefaultTimeBar` and the parent view matrices all the way up the view hierarchy? I'm not sure if there's a convenient way to do that.

**Comment by YukihiroMori-Bascule** [comment]
Thank you commented, andrewlewis.
I don't understand how to deal transform matrix, but I calculated rotation of this view considering all of the parent view.

It is my way of calculate rotation.
But, it might be not best practice.
```
float r = getRotation();
ViewParent parent = getParent();
while (parent != null && parent instanceof View){
    float pr = ((View) parent).getRotation();
    r += pr;
    r = r%360;
    parent = parent.getParent();
}
```

**Comment by andrewlewis** [comment]
I haven't tried it, but the best approach may be to iterate through the hierarchy like you're doing but to use `Matrix.mapPoints` with each `View`'s matrix. That should take into account all transformations, not just rotation. This is a bit like the code in `transformFromViewToWindowSpace` in [View.java](https://android.googlesource.com/platform/frameworks/base/+/oreo-mr1-release/core/java/android/view/View.java#21461).
