### ISSUE TITLE
excessive delay from STATE_PREPARING to STATE_BUFFERING

### ISSUE THREAD

**Issue by tresvecesseis** [google/ExoPlayer#409]
I'm seeing that it takes an anormal amount of time to go from STATE_PREPARING to STATE_BUFFERING is some circustances, from the logs it seems that when in an HLS stream the audio packets arrive before the video ones (the PCR is in the video PID) and the audio packets have a PTS counter that is less than the video ones (our audio track has a delay relative to video of up to -700 ms) a negative sampleTimeUs is assigned to the h264 samples and until the current sampleTimeUs doesn't reach the audio current timeUs the player doesn´t transition to STATE_BUFFERING , this can be a long time if ever and the player must be able to enter in STATE_BUFFERING, at most, in a time equal to the audio/video track delay as all the audio samples are queued in the buffer so when the current video PTS reach the first audio PTS in the buffer we are ready to start buffering.

the logs of a normal execution:
`04-22 16:45:01.722  25179-25179/com.google.android.exoplayer.demo I/ExoPlayerImpl﹕ Init 1.3.0
04-22 16:45:01.722  25179-25179/com.google.android.exoplayer.demo D/EventLogger﹕ start [0]
04-22 16:45:01.722  25179-25179/com.google.android.exoplayer.demo D/EventLogger﹕ state [0.00, false, P]
04-22 16:45:01.722  25179-25179/com.google.android.exoplayer.demo D/EventLogger﹕ state [0.00, true, P]
04-22 16:45:01.752  25179-25179/com.google.android.exoplayer.demo D/mali_winsys﹕ new_window_surface returns 0x3000
04-22 16:45:01.962   25179-3500/com.google.android.exoplayer.demo D/H264Reader﹕ sampleTimeUs :0
04-22 16:45:01.972  25179-25179/com.google.android.exoplayer.demo D/EventLogger﹕ state [0.25, true, B]`

and in the anormal execution:

`04-22 16:25:28.432  25179-25179/com.google.android.exoplayer.demo D/dalvikvm﹕ GC_FOR_ALLOC freed 1105K, 14% free 7587K/8752K, paused 22ms, total 22ms
04-22 16:25:28.442  25179-25179/com.google.android.exoplayer.demo I/ExoPlayerImpl﹕ Init 1.3.0
04-22 16:25:28.442  25179-25179/com.google.android.exoplayer.demo D/EventLogger﹕ start [0]
04-22 16:25:28.442  25179-25179/com.google.android.exoplayer.demo D/EventLogger﹕ state [0.00, false, P]
04-22 16:25:28.442  25179-25179/com.google.android.exoplayer.demo D/EventLogger﹕ state [0.00, true, P]
04-22 16:25:28.462  25179-25179/com.google.android.exoplayer.demo D/mali_winsys﹕ new_window_surface returns 0x3000
04-22 16:25:28.612  25179-27463/com.google.android.exoplayer.demo D/MpaReader﹕ timeUs :105267
04-22 16:25:28.612  25179-27463/com.google.android.exoplayer.demo D/MpaReader﹕ timeUs :129267
04-22 16:25:28.682  25179-27463/com.google.android.exoplayer.demo D/MpaReader﹕ timeUs :153267
04-22 16:25:28.682  25179-27463/com.google.android.exoplayer.demo D/MpaReader﹕ timeUs :177267
04-22 16:25:28.692  25179-27463/com.google.android.exoplayer.demo D/H264Reader﹕ sampleTimeUs :0
04-22 16:25:28.692  25179-27463/com.google.android.exoplayer.demo D/H264Reader﹕ sampleTimeUs :-160000
04-22 16:25:28.692  25179-27463/com.google.android.exoplayer.demo D/H264Reader﹕ sampleTimeUs :-240000
04-22 16:25:28.692  25179-27463/com.google.android.exoplayer.demo D/H264Reader﹕ sampleTimeUs :-280000
04-22 16:25:28.692  25179-27463/com.google.android.exoplayer.demo D/H264Reader﹕ sampleTimeUs :-200000
04-22 16:25:28.692  25179-27463/com.google.android.exoplayer.demo D/H264Reader﹕ sampleTimeUs :-80000
04-22 16:25:28.762  25179-27463/com.google.android.exoplayer.demo D/MpaReader﹕ timeUs :201267
04-22 16:25:28.762  25179-27463/com.google.android.exoplayer.demo D/MpaReader﹕ timeUs :225267
04-22 16:25:28.762  25179-27463/com.google.android.exoplayer.demo D/H264Reader﹕ sampleTimeUs :-120000
04-22 16:25:28.772  25179-27463/com.google.android.exoplayer.demo D/MpaReader﹕ timeUs :249267
04-22 16:25:28.772  25179-27463/com.google.android.exoplayer.demo D/MpaReader﹕ timeUs :273267
04-22 16:25:28.772  25179-27463/com.google.android.exoplayer.demo D/MpaReader﹕ timeUs :297267
04-22 16:25:28.772  25179-27463/com.google.android.exoplayer.demo D/H264Reader﹕ sampleTimeUs :-40000
04-22 16:25:28.822  25179-27463/com.google.android.exoplayer.demo D/MpaReader﹕ timeUs :321267
04-22 16:25:28.822  25179-27463/com.google.android.exoplayer.demo D/MpaReader﹕ timeUs :345267
...
...
...
04-22 16:25:31.282  25179-27463/com.google.android.exoplayer.demo D/MpaReader﹕ timeUs :3393267
04-22 16:25:31.282  25179-27463/com.google.android.exoplayer.demo D/MpaReader﹕ timeUs :3417267
04-22 16:25:31.282  25179-27463/com.google.android.exoplayer.demo D/H264Reader﹕ sampleTimeUs :3080000
04-22 16:25:31.282  25179-27463/com.google.android.exoplayer.demo D/H264Reader﹕ sampleTimeUs :3160000
04-22 16:25:31.312  25179-27463/com.google.android.exoplayer.demo D/dalvikvm﹕ GC_FOR_ALLOC freed 242K, 15% free 8993K/10572K, paused 25ms, total 25ms
04-22 16:25:31.312  25179-27463/com.google.android.exoplayer.demo D/H264Reader﹕ sampleTimeUs :3240000
04-22 16:25:31.362  25179-27463/com.google.android.exoplayer.demo D/MpaReader﹕ timeUs :3441267
04-22 16:25:31.362  25179-27463/com.google.android.exoplayer.demo D/MpaReader﹕ timeUs :3465267
04-22 16:25:31.422  25179-27463/com.google.android.exoplayer.demo D/H264Reader﹕ sampleTimeUs :3280000
04-22 16:25:31.432  25179-27463/com.google.android.exoplayer.demo D/MpaReader﹕ timeUs :3489267
04-22 16:25:31.432  25179-27463/com.google.android.exoplayer.demo D/MpaReader﹕ timeUs :3513267
04-22 16:25:31.432  25179-27463/com.google.android.exoplayer.demo D/MpaReader﹕ timeUs :3537267
04-22 16:25:31.432  25179-25179/com.google.android.exoplayer.demo D/EventLogger﹕ state [2.99, true, B]
04-22 16:25:31.432  25179-25179/com.google.android.exoplayer.demo D/EventLogger﹕ videoFormat [2.99, 0, 0]
04-22 16:25:31.432  25179-27487/com.google.android.exoplayer.demo I/OMXClient﹕ Using client-side OMX mux.
04-22 16:25:31.432  25179-27487/com.google.android.exoplayer.demo E/ACodec﹕ [OMX.rk.video_decoder.avc] storeMetaDataInBuffers failed w/ err -2147483648
04-22 16:25:31.432  25179-27487/com.google.android.exoplayer.demo W/ACodec﹕ [OMX.rk.video_decoder.avc] prepareForAdaptivePlayback failed w/ err -2147483648
04-22 16:25:31.432  25179-27463/com.google.android.exoplayer.demo D/MpaReader﹕ timeUs :3561267
04-22 16:25:31.442  25179-27463/com.google.android.exoplayer.demo D/MpaReader﹕ timeUs :3585267
04-22 16:25:31.472  25179-25179/com.google.android.exoplayer.demo D/EventLogger﹕ decoderInitialized [3.03]
04-22 16:25:31.472  25179-27494/com.google.android.exoplayer.demo I/OMXClient﹕ Using client-side OMX mux.
04-22 16:25:31.472  25179-27494/com.google.android.exoplayer.demo I/﹕ new RKOMXPlugin
04-22 16:25:31.482  25179-27463/com.google.android.exoplayer.demo D/H264Reader﹕ sampleTimeUs :3600000`

**Comment by tresvecesseis** [comment]
It seems that I was wrong, further testing reveals that not in every case the first h264 sample when it arrives after an audio sample have negative sampleTimeUs counters assigned, and only when we have negative values we have problems. I will try to print the real PTS to see how related are the audio and video PTS

**Comment by ojw28** [comment]
We transition from PREPARING to BUFFERING once we've discovered the media format for each of the tracks (i.e. audio and video). If PREPARING is taking a long time, that probably means the first chunk doesn't contain format information near the beginning, which typically suggests poor interleaving of audio and video in the chunk. If so, that's working as intended.

Why is PREPARING taking a long time actually an issue? I would have thought you'd treat it similarly for BUFFERING anyway (e.g. for the purposes of deciding whether to show a loading spinner, or something).

**Comment by tresvecesseis** [comment]
Our servers send in the firsts packets all the needed info to start decoding in tens of milliseconds, the first ip packet contains seven ts packets containing the PAT, PMT, PCR and the access unit delimeter,
sequence parameter set, picture parameter set, supplemental enhancement information (SEI), coded slice of an IDR picture NALUs for the first IDR frame and the audio frames are interleaved properly with the video frames. The problems seems to be related with the completion of the firsts frames, if the first frame to be completed is the video one (that has a PTS ahead of the audio frames) the decoding PREPARING state is reached in tens of miliseconds, but if the first completed sample is a audio one, the sampleTimeUS becomes negative and we only transitoin to the PREPARING state when the sampleTimeUs of the video frames catches the timeUS of the audio frames, I didn´t have time to check but i think is relate with the lastPts variable and the fact that the video PTS is greater than the audio one.

**Comment by tresvecesseis** [comment]
this is a TS that take 25 seconds to enter in state BUFFERING and it has all the needed:

https://drive.google.com/file/d/0Bzu4Z1WNC2rebTRiUVRwbTZVclk/view?usp=sharing

it begins with an I frame but an audio sample (with a proper PTS) interleaved with the video finishes before this first video frame, and the problem manifests

**Comment by ojw28** [comment]
Interesting. We're looking for an IDR frame and not finding one until ~8.5MB into the data. This chunk starts with an IFR frame with slice type 7 (I slice). The player doesn't consider it as a random access point.

I don't suppose you know exactly what properties this type of slice has. We've been discussing internally and our initial interpretation was that it could refer to data before itself, meaning it's (at least in theory) not a suitable starting point for decode. We have seen this issue elsewhere though, and it appears VLC plays this segment correctly.

**Comment by ojw28** [comment]
If we do interpret the IFR frame with slice type 7 as a keyframe then the segment plays correctly. We're just worried that this might not always be true, because we can't find that guarantee in a spec anywhere (if it is somewhere in a relevant spec, that would be very useful information to have).

**Comment by tresvecesseis** [comment]
I didn´t think it was related to no being an IDR cause almost all our I frames are not IDR frames and the problem occurs only occasionally,  I will check if all the working examples are streams beginning with IDR frames...

**Comment by ojw28** [comment]
Pretty sure it is. See here: [here](https://github.com/google/ExoPlayer/blob/dev/library/src/main/java/com/google/android/exoplayer/extractor/ts/H264Reader.java#L135). We don't play anything before the first keyframe, so if there aren't any IDR frames we wont play anything.

**Comment by tresvecesseis** [comment]
I have look specifically for this problem in a lot of channels of our service and you are right and my previous observations are not the cause of the problem but an effect of the problematic stream encoding, in any case all our STBs play the streams without problems and we want to replicate the behaviour in our Android TV boxes, it will be posible to introduce a flag to signal the desired behaviour in the official exoplayer library or I have to maintain this change private to my player?

**Comment by ojw28** [comment]
We're thinking about how best to handle this case. For now just handle it locally, but given we've seen at least one other example of this too, and that other players seem to handle it better, it's certainly possible that we'll figure out a way to provide support.

**Comment by tresvecesseis** [comment]
this patch solves my problem:

```java
diff --git a/library/src/main/java/com/google/android/exoplayer/extractor/ts/H264Reader.java b/library/src/main/java/com/google/android/exoplayer/extractor/ts/H264Reader.java
index 4627cb6..0bf6ca4 100644
--- a/library/src/main/java/com/google/android/exoplayer/extractor/ts/H264Reader.java
+++ b/library/src/main/java/com/google/android/exoplayer/extractor/ts/H264Reader.java
@@ -37,11 +37,14 @@ import java.util.List;

   private static final String TAG = "H264Reader";

+  private static final int NAL_UNIT_TYPE_NON_IDR = 1;
   private static final int NAL_UNIT_TYPE_IDR = 5;
   private static final int NAL_UNIT_TYPE_SEI = 6;
   private static final int NAL_UNIT_TYPE_SPS = 7;
   private static final int NAL_UNIT_TYPE_PPS = 8;
   private static final int NAL_UNIT_TYPE_AUD = 9;
+  private static final int SLICE_TYPE_I = 2;
+  private static final int SLICE_TYPE_I_ONLY = 7;
   private static final int EXTENDED_SAR = 0xFF;
   private static final float[] ASPECT_RATIO_IDC_VALUES = new float[] {
     1f /* Unspecified. Assume square */,
@@ -131,7 +134,8 @@ import java.util.List;
             samplePosition = totalBytesWritten - bytesWrittenPastNalUnit;
             sampleTimeUs = pesTimeUs;
             isKeyframe = false;
-          } else if (nalUnitType == NAL_UNIT_TYPE_IDR) {
+          } else if (nalUnitType == NAL_UNIT_TYPE_IDR ||
+                    (nalUnitType == NAL_UNIT_TYPE_NON_IDR && parseSliceType(dataArray, nextNalUnitOffset) == SLICE_TYPE_I_ONLY)) {
             isKeyframe = true;
           }

@@ -181,6 +185,13 @@ import java.util.List;
     }
   }

+  private int parseSliceType(byte[] data, int offset) {
+    ParsableBitArray bitArray = new ParsableBitArray(data);
+    bitArray.skipBits(offset * 8 + 32); // NAL Offset + NAL header
+    bitArray.readUnsignedExpGolombCodedInt(); // first_mb_in_slice
+    return bitArray.readUnsignedExpGolombCodedInt(); // slice_type
+  }
+
   private void parseMediaFormat(NalUnitTargetBuffer sps, NalUnitTargetBuffer pps) {
     byte[] spsData = new byte[sps.nalLength];
     byte[] ppsData = new byte[pps.nalLength];
```


the only remaining problem is that the player tries to reproduce all audio samples in the buffer, when I think the correct aproach will be to discard all the audio samples prior to the PTS of the first keyframe (audio PTS + sample duration < first keyframe PTS), what do you think? in our case we see the first keyframe during several seconds (less than one second with the patch above) until the audio reproduction consume all the audio samples and reaches the video keyframe.

**Comment by ojw28** [comment]
- Yeah, we have a patch that looks pretty much the same as that one. We're worried it'll cause video corruption for other content though; hence why we're thinking about it.
- There's also a chance that parseSliceType will read off the end of the data and crash in the code above. There's no guarantee about how data is divided up across calls to consume, so you need to handle the case where the slice type spans the boundary between the data passed in two (or theoretically multiple) calls.

**Comment by tresvecesseis** [comment]
you are right, it was only a rough draft to check the problem is gone, in our case is not a problem cause each PES start in a new IP packet and access unit delimeter,  sps,  pps, sei and the first bytes of the slice NALU all are in the same TS packet. In any case I´m more concerned about the video waiting for audio samples as described in my last posts, and if this can be related to some stuttering that I´m seeing when a lost or duplicate some audio samples (It´s a problem with our service architecture when we join different streams and we could have audio discontinuities in the join points)

**Comment by ojw28** [comment]
I'd argue that the correct approach is to always put a video keyframe at the start of every segment, which avoids the problem of the player playing out the audio that comes before it. Both DASH and SmoothStreaming guarantee this property. It's a shame that HLS doesn't, but my understanding is that many broadcasters ensure that the property holds for their streams. Note that you also need to ensure this property to avoid having to download-and-splice overlapping segments in two qualities whenever you want to do a seamless quality switch, which is very inefficient, particularly if you're trying to switch to a lower quality due to bandwidth constraints.

I don't think we're planning to change the behavior just for HLS, particularly given not putting a keyframe at the start of every segment is generally a bad thing to do.

**Comment by tresvecesseis** [comment]
The problem is not HLS related, is a TS thing, we don´t want to use HLS, we plan to use an HTTP datasource but for testing purposes we made an HLS manifest in order to quickly test our streams with the infrastructure we have developed for our smart TVs apps, we are no using adaptative streams but we need to build a single data stream from several contributors.

**Comment by ojw28** [comment]
Are these live TS streams then? If you have a test stream that would be really helpful (no need for a manifest or anything; it's actually quite easy to hack around in ExoPlayer to get it to play TS directly).

**Comment by tresvecesseis** [comment]
I have sent you privately the needed info to access our TS streams

**Comment by ojw28** [comment]
Hi. The dev branch now allows you to pass an additional argument (idrKeyframesOnly) into TsExtractor. If you do so, you should find that you're now able to play this type of content. Please take a look and see if it works for you.

**Comment by tresvecesseis** [comment]
It doesn´t seems to work, I checked with a channel with 40 seconds lasting
GOPs, and several times I got a preparing time of several seconds and my
first frame is always and I-frame.

This remembers me another problem, when we are in STATE_PREPARING we
continue buffering audio samples so when we transition to STATE_BUFFERING
we have to reproduce all the audio samples unitl we reach the video
timestamps, in the case when we stay in STATE_PREPARING during several
seconds, we get a static screen with the first frame when we enter in
STATE_BUFFERING and when we reach STATE_READY (usually in a hundreds of
milliseconds) we stay in this video frame until we reproduce all the queued
audio in the STATE_PREPARING.

**Comment by tresvecesseis** [comment]
On Tue, May 26, 2015 at 12:19 PM, Sergio Moreno <tresvecesseis@gmail.com>
wrote:

> This remembers me another problem, when we are in STATE_PREPARING we
> continue buffering audio samples so when we transition to STATE_BUFFERING
> we have to reproduce all the audio samples unitl we reach the video
> timestamps, in the case when we stay in STATE_PREPARING during several
> seconds, we get a static screen with the first frame when we enter in
> STATE_BUFFERING and when we reach STATE_READY (usually in a hundreds of
> milliseconds) we stay in this video frame until we reproduce all the queued
> audio in the STATE_PREPARING.
>
>
I think we need to reset the audio queues (or not buffer audio samples)
when we detect the first I-frame.

**Comment by ojw28** [comment]
Can you confirm it works correctly for the sample you linked further up this issue, at least? It works correctly for me (once I trim the file to be a whole number of TS packets). If you don't have that working then I'm obviously doing something different to what you're doing.

**Comment by tresvecesseis** [comment]
I was away the last week and I could not do any test, today I checked a
fresh tree and it seems to be working properly. Thanks
