### ISSUE TITLE
Recording live stream in mobile app using exoplayer

### ISSUE THREAD

**Issue by RadhikaBalla** [google/ExoPlayer#4090]
Hello,

 Can I record live stream, store it in mobile sdcard and play it back afterwards when ever I want to play using exoplayer? If it is not possible with exoplayer, can you please suggest me the ways to accomplish that task.

**Comment by andrewlewis** [comment]
Seems to be the same request as #3877. We don't support this at the moment and I don't have any recommendations for alternatives I'm afraid. Please subscribe to that issue if you want to receive updates.
