### ISSUE TITLE
Low deinterlacing quality on Sony Bravia Android TV and Mi Box Android TV

### ISSUE THREAD

**Issue by AlisaHevic** [google/ExoPlayer#4098]
Application: TVirl (https://play.google.com/store/apps/details?id=by.stari4ek.tvirl)
Sony Bravia Android TV:
![sonyandroidtv](https://user-images.githubusercontent.com/30731697/38453451-9b8fde78-3a5e-11e8-9c7f-ec51a3c5dfee.png)
Xiaomi Mi Box 2016 [Android TV]:
![mibox](https://user-images.githubusercontent.com/30731697/38453441-7a2030da-3a5e-11e8-8bb5-eae5396165db.png)
With Nvidia Shield TV it's ok:
![nvidiashieldtv](https://user-images.githubusercontent.com/30731697/38453457-cda263b8-3a5e-11e8-9250-90123b80592f.png)

More photos in users bug requests:
https://4pda.ru/forum/index.php?showtopic=725422&st=3040#entry71410261
https://4pda.ru/forum/index.php?showtopic=725422&st=2700#entry68320545
https://4pda.ru/forum/index.php?showtopic=725422&st=2640#entry68188170
https://community.sony.ru/t5/televizory/bag-sistemnogo-dekodera-na-vseh-televizorah-sony-android-tv-6-i-7/td-p/2432531

Stream for repeat:
http://hlstv.brn.211.ru/239.211.211.24/stream.m3u8

In other players (Kodi, MX player, Perfect player), there is no problem with deinterlacing on these platforms.

**Comment by andrewlewis** [comment]
Please see #2013. ExoPlayer relies on the platform (and the device) for any postprocessing like deinterlacing.
