### ISSUE TITLE
Problem playing AAC on API 21

### ISSUE THREAD

**Issue by thefenix1** [google/ExoPlayer#410]
On ExoPlayer example, I changed the "Apple AAC 10s" to a custom url I'm trying to play (HE-AACv2). It works perfect on API 19 on emulator but on my Galaxy S5 with API 21 It crashes with the following errors

04-22 15:34:59.333    2780-2889/com.google.android.exoplayer.demo E/NuCachedSource2﹕ readAt:Timeout ( player case )
04-22 15:35:01.338    2780-2889/com.google.android.exoplayer.demo E/NuCachedSource2﹕ readAt:Timeout ( player case )
04-22 15:35:03.338    2780-2889/com.google.android.exoplayer.demo E/NuCachedSource2﹕ readAt:Timeout ( player case )
04-22 15:35:05.338    2780-2889/com.google.android.exoplayer.demo E/NuCachedSource2﹕ readAt:Timeout ( player case )
04-22 15:35:07.343    2780-2889/com.google.android.exoplayer.demo E/NuCachedSource2﹕ readAt:Timeout ( player case )
04-22 15:35:08.193    2780-2890/com.google.android.exoplayer.demo A/libc﹕ Fatal signal 11 (SIGSEGV), code 1, fault addr 0x4 in tid 2890 (NuCachedSource2)

I'd prefer not to paste my production url here but I could send it to an email if necessary

Thanks

**Comment by thefenix1** [comment]
This doesn't happen on dev branch. When do you plan to move dev stuff to master?

Thanks

**Comment by ojw28** [comment]
We'll aim for ~2 weeks from now.
