### ISSUE TITLE
Is BUFFER_FLAG_DECODE_ONLY officially supported by AndroidTV

### ISSUE THREAD

**Issue by mmbahaa** [google/ExoPlayer#4102]
Hello,
In ExoPlayer this decoder flag BUFFER_FLAG_DECODE_ONLY is defined as (0x80000000). 
1. Is this flag officially supported by Google? 
2. Is there any policy to ensure that device manufacturers (especially AndroidTV) supports it? 
3. Is it tested in any test suite (e.g. CTS, GTS)?

**Comment by ojw28** [comment]
`BUFFER_FLAG_DECODE_ONLY` is specific to ExoPlayer and handled within the library. It's not fed to the underlying platform, and so there are no platform requirements.
