### ISSUE TITLE
ExoPlayer - H264 file does not play

### ISSUE THREAD

**Issue by barhom** [google/ExoPlayer#4103]
### Version of ExoPlayer being used
2.7.1

Hello,

I tried the following mpegts file in ExoPlayer with no luck of playing it back:
https://myfile.org/h8E6c3ecbc/h264.ts

Please note that I have stripped the audio from the file to be sure that the problem is not related to audio.

I have tried two different decoders;

OMX.amlogic.avc.decoder.awesome
OMX.google.h264.decoder

I have also tried the file with VLC (on android) and that works as expected.
Logs are pasted below, but they are mostly useless.

**Comment by barhom** [comment]
> 04-09 16:28:02.413 17405-17405/debug D/EventLogger: timelineChanged [periodCount=0, windowCount=0, reason=RESET
>     ]
> 04-09 16:28:02.414 17405-17405/debug D/EventLogger: state [93.72, true, B]
> 04-09 16:28:02.416 17405-17405/debug D/EventLogger: timelineChanged [periodCount=1, windowCount=1, reason=PREPARED
>       period [?]
>       window [?, false, false]
>     ]
> 04-09 16:28:02.417 17405-17405/debug D/EventLogger: loading [true]
> 
> 04-09 16:28:03.493 17405-17405/debug D/EventLogger: videoEnabled [94.80]
>     Tracks [
> 04-09 16:28:03.494 17405-17405/debug D/EventLogger:   Renderer:0 [
>         Group:0, adaptive_supported=N/A [
>           [X] Track:0, id=1/256, mimeType=video/avc, res=720x576, supported=YES
>         ]
>       ]
>       Renderer:2 [
>         Group:0, adaptive_supported=N/A [
>           [ ] Track:0, id=1/8448, mimeType=application/cea-608, supported=YES
>         ]
>       ]
>     ]
> 
> 04-09 16:28:03.538 17405-17770/debug I/OMXClient: MuxOMX ctor
> 04-09 16:28:03.547 17405-17769/debug I/MediaCodec: [OMX.amlogic.avc.decoder.awesome] setting surface generation to 17822724
> 04-09 16:28:03.548 17405-17770/debug D/ACodec_amlogic: query systemComposer 1
> 04-09 16:28:03.549 17405-17770/debug E/ACodec: [OMX.amlogic.avc.decoder.awesome] storeMetaDataInBuffers failed w/ err -2147483648
> 04-09 16:28:03.562 17405-17770/debug I/ACodec: codec does not support config priority (err -1010)
> 04-09 16:28:03.570 17405-17770/debug D/SurfaceUtils: set up nativeWindow 0xcb26a808 for 736x576, color 0x11, rotation 0, usage 0x5002900
> 04-09 16:28:03.571 17405-17770/debug W/ACodec: [OMX.amlogic.avc.decoder.awesome] setting nBufferCountActual to 8 failed: -1010
> 04-09 16:28:03.571 17405-17770/debug W/ACodec: [OMX.amlogic.avc.decoder.awesome] setting nBufferCountActual to 7 failed: -1010
> 04-09 16:28:03.609 17405-17405/debug D/EventLogger: videoDecoderInitialized [94.91, OMX.amlogic.avc.decoder.awesome]
>     videoFormatChanged [94.91, id=1/256, mimeType=video/avc, res=720x576]

**Comment by barhom** [comment]
> 04-09 16:33:07.927 18011-18011/ D/EventLogger: timelineChanged [periodCount=0, windowCount=0, reason=RESET
>     ]
> 04-09 16:33:07.928 18011-18011/ D/EventLogger: Tracks []
> 04-09 16:33:07.929 18011-18011/ D/EventLogger: loading [false]
> 04-09 16:33:07.930 18011-18011/ D/EventLogger: state [15.27, true, B]
> 04-09 16:33:08.230 18011-18011/ D/EventLogger: videoDisabled [15.57]
> 04-09 16:33:08.262 18011-18011/ D/EventLogger: audioDisabled [15.60]
> 04-09 16:33:08.266 18011-18011/ D/EventLogger: timelineChanged [periodCount=1, windowCount=1, reason=PREPARED
>       period [?]
> 04-09 16:33:08.267 18011-18011/ D/EventLogger:   window [?, false, false]
>     ]
> 04-09 16:33:08.269 18011-18011/ D/EventLogger: loading [true]
> 04-09 16:33:09.309 18011-18011/ D/EventLogger: videoEnabled [16.65]
> 04-09 16:33:09.312 18011-18011/ D/EventLogger: Tracks [
>       Renderer:0 [
>         Group:0, adaptive_supported=N/A [
>           [X] Track:0, id=1/256, mimeType=video/avc, res=720x576, supported=YES
>         ]
>       ]
>       Renderer:2 [
>         Group:0, adaptive_supported=N/A [
> 04-09 16:33:09.313 18011-18011/ D/EventLogger:       [ ] Track:0, id=1/8448, mimeType=application/cea-608, supported=YES
>         ]
>       ]
>     ]
> 04-09 16:33:09.313 18011-18011/ D/PlayerEventListener: Video started playing... (exoplayer)
> 04-09 16:33:09.320 18011-18134/ I/OMXClient: MuxOMX ctor
> 04-09 16:33:09.397 18011-18133/ I/MediaCodec: [OMX.google.h264.decoder] setting surface generation to 18443266
> 04-09 16:33:09.399 18011-18134/ D/ACodec_amlogic: query systemComposer 1
> 04-09 16:33:09.400 18011-18134/ E/ACodec: [OMX.google.h264.decoder] storeMetaDataInBuffers failed w/ err -1010
> 04-09 16:33:09.405 18011-18134/ I/ACodec: codec does not support config priority (err -1010)
> 04-09 16:33:09.423 18011-18011/ D/EventLogger: videoDecoderInitialized [16.76, OMX.google.h264.decoder]
>     videoFormatChanged [16.77, id=1/256, mimeType=video/avc, res=720x576]

**Comment by AquilesCanta** [comment]
Please see #1894. Seems you need to enable FLAG_ALLOW_NON_IDR_KEYFRAMES in DefaultTsPayloadReaderFactory.
