### ISSUE TITLE
Video renderer not getting called.

### ISSUE THREAD

**Issue by gevariya-ajit** [google/ExoPlayer#4105]
### Issue description
We build the datasource which provide buffer frames to draw into surface, but seems like our default `MediaCodecVideoRenderer` isn't working so had build our own to draw buffer on surface. but somehow our renderer isn't getting called or enabled by `ExoPlayerImplInternal`. My renderer is extending `BaseRenderer` and and trying to read buffer from `readSource` base renderer method.

I am not sure what i am missing since there is no document to create our own renderer. 

### Code
```            
            val mediaSource = ExtractorMediaSource
                    .Factory(FfmpegRtmpDatasource.FfmpegRtmpDatasourceFactory())
                    .setExtractorsFactory(MatroskaExtractor.FACTORY)
                    .createMediaSource(Uri.parse(streamUrl))

            player.createMessage(ffmpegRtmpRenderer)
                    .setType(100)
                    .setPayload(surfaceView.holder.surface)
                    .send()

            player.prepare(mediaSource)
            player.playWhenReady = true
```

### Version of ExoPlayer being used
2.7.0

### Device(s) and version(s) of Android being used
6.0

**Comment by erdemguven** [comment]
Please provide a full bug report using "adb bugreport".

**Comment by erdemguven** [comment]
It sounds like an implementation bug on your side. Sorry, we can't say much without seeing your code.
