### ISSUE TITLE
Last Cue in subtitle not considered when playing segmented subtitles

### ISSUE THREAD

**Issue by gvidda** [google/ExoPlayer#4106]
### Issue description
When playing DASH with segmented TTML and the last Cue overlaps the subtitle segment, subtitles are "cleared" and doesn't show any new until the next subtitle segments first Cue occurs. This is very visible when TTML segments have the same length as video segments.

### Link to test content
Emailed test media link to dev.exoplayer@gmail.com.

### Version of ExoPlayer being used
2.7.1 release

### Device(s) and version(s) of Android being used
Reproduced on all tested devices but mostly tested on Galaxy S9 Android 8.0 and Pixel 2 Android 8.1

**Comment by ojw28** [comment]
If you have 5s segments and a subtitle is to be displayed from 3s -> 6s, my understanding is that the first segment should include the subtitle with start/end timestamps 3s -> 5s, and that the second segment should also include the same subtitle with start/end timestamps 5s -> 6s. In this case I don't think the subtitle will disappear.

Please clarify whether your content does this. Thanks!

**Comment by gvidda** [comment]
I'll have to investigate if it's possible to duplicate the last Cue/sample into the next segment when encoding our media.
Right now it doesn't do that. In your above example the first segment have 3s -> 6s and the next segment nothing in that timespan.

**Comment by ojw28** [comment]
I'm pretty sure that's not the correct way to prepare media. Seeking cannot work properly when content is prepared as you describe, for example, because the player has no of knowing which previous segments might contain subtitles that are still supposed to be visible at the seek position. The player would have to download all segments up to the seek position to figure this out.

**Comment by gvidda** [comment]
I just wanted to get back regarding this issue (for historys sake if someone reads this and have the same problem) that this was ultimately solved for us in the backend/packager. The "bad media" subtitles worked in webplayers, but it was better to package it according to an EBU standard (like ojw28 described above).
