### ISSUE TITLE
Grabbing synchronized audio samples

### ISSUE THREAD

**Issue by kunaljathal** [google/ExoPlayer#4107]
Is it possible to grab _synchronized_ audio samples from a running ExoPlayer instance, without having to modify the source code?

Currently I'm getting the decoded audio samples inside of `processOutputBuffer` in `MediaCodecAudioRenderer`, but these don't seem to be in sync with the video.  Also this has required me to essentially write my own renderer (and subsequently my own `AudioSink`, since `DefaultAudioSink` is a `final` class). I tried grabbing them from `handleBuffer` in `DefaultAudioSink` instead, but again it seems like the samples I get there (just before the `writeNonBlockingV21` call) are kind of decoupled from the sync logic.

**Comment by andrewlewis** [comment]
During normal playback we synchronize video to the audio playout position, so I think the request here is to get a stream of PCM audio data that's synchronized with playout position of the underlying `AudioTrack` (but please correct me if I've misunderstood).

The platform `AudioTrack` keeps a buffer of data internally, which introduces latency, so it's not sufficient to output data at the moment it's written to the track. Instead, I think you'll need to keep a buffer of audio that's been written to the track, then output data from your own buffer based on the current playout position.

I'm afraid we don't have a built-in way to do this at the moment so some level of customization is necessary. There are lots of ways this could be done, but if you want to minimize the number of customized components I think it should be possible with only a custom `AudioProcessor` as follows.

- Instantiate a `DefaultAudioSink`, passing in a custom `AudioProcessor`, and set up the player with a `MediaCodecAudioRenderer` outputting to this sink.
- Each time the custom audio processor receives input, it should copy it to an output buffer, but also copy the bytes into an additional internal buffer. We are using it as a way to intercept the audio.
- At the same time as populating its internal buffer, we can also check the current playout position via `AudioSink.getCurrentPositionUs`, as we have a reference to the sink. The position can be converted into a frame count, which in turns maps onto a byte offset in the internal buffer, which is the position up to which audio has been played out. You can handle this portion of the internal buffer however you want, then compact the buffer.
- Note: all audio processor methods run on ExoPlayer's internal playback thread, so you may want to pass the data that's been output to an application thread.

**Comment by kunaljathal** [comment]
Okay, gotcha. A couple of preliminary clarifications:

> Instantiate a `DefaultAudioSink`, passing in a custom `AudioProcessor`, and set up the player with a `MediaCodecAudioRenderer` outputting to this sink.

I'm creating an instance of `SimpleExoPlayer` via `ExoPlayerFactory.newSimpleInstance`, so I'm assuming I can do what you're describing by simply overriding `DefaultRenderersFactory.buildAudioProcessors` (in the renderers factory that I pass to the constructor of `ExoPlayerFactory.newSimpleInstance`) with my custom `AudioProcessor`, right? Because this `AudioProcessor` then internally gets passed to the underlying `MediaCodecAudioRenderer`, which will then further pass it to it's `DefaultAudioSink`. Does this make sense?

> At the same time as populating its internal buffer, we can also check the current playout position via `AudioSink.getCurrentPositionUs`, as we have a reference to the sink.

I'm a bit confused here -- where's the reference? i.e. where in my custom `AudioProcessor` am I able to access the sink?

**Comment by andrewlewis** [comment]
You need to instantiate the `DefaultAudioSink` yourself so that you can provide a reference to it to your custom audio processor. This means you need to instantiate the `MediaCodecAudioRenderer` yourself, passing in the sink. Overriding `buildAudioRenderers` from `DefaultRenderersFactory` is a good way to do that.

**Comment by kunaljathal** [comment]
Okay, gotcha. I think my final clarification is the following:

>At the same time as populating its internal buffer, we can also check the current playout position via `AudioSink.getCurrentPositionUs`, as we have a reference to the sink. The position can be converted into a frame count, which in turns maps onto a byte offset in the internal buffer, which is the position up to which audio has been played out. You can handle this portion of the internal buffer however you want, then compact the buffer.

Does this imply that the buffer of data I'm getting in the `queueInput` call contains audio data, _a portion of which has already been played out_? Because, if I'm understanding correctly, what you're saying is that I can discard this portion, and collect the samples after it, which are representative of the samples that are about to be played out next (presumably soon after the `getOutputBuffer` call), and hence in sync with the video frames about to be played out next.

**Comment by andrewlewis** [comment]
The audio data just passed to `queueInput` has not been played out yet, as the `AudioTrack` is 'downstream' from the chain of audio processors. The audio data you've already buffered on previous invocations of `queueInput` may have been played out, though. The idea is to use `getCurrentPositionUs` to determine how many bytes of the input have been played out so far, which corresponds to a position in your internal buffer.

As the internal buffer can't grow indefinitely, when you determine that some of its audio has been played (based on the current position), you'll need to discard data up to there from your internal buffer, and update a stored offset for the start of the internal buffer. This offset should be reset on each call to `flush`.

One other caveat, which may not be relevant to your use case: speed/pitch/trim silence are applied after any custom `AudioProcessor`s at the moment, so the player position will reflect any offset/scaling applied for those.

**Comment by kunaljathal** [comment]
OK, I see. In the case of speed/pitch/trim etc applied _after_ the custom `AudioProcessor` -- is this factored into the position returned by `getCurrentPositionUs` ? To be clear, I'll be using ExoPlayer for streaming video most of the time i.e. the use case that's most relevant to me is interruptions in streaming -- in the case of network issues etc., if the video ends up momentarily lagging / pausing and resuming (i.e. buffering) for any reason, I would want to stop/re-play the audio at the correct positions, keeping it in sync with the video at all times. So if `getCurrentPositionUs` is going to incorporate all that, then that's enough for me.

**Comment by andrewlewis** [comment]
The position returned by `getCurrentPositionUs` will take into account playback parameters, buffering, pausing etc.. If you're not overriding the default playback speed it should work fine.

**Comment by kunaljathal** [comment]
Thanks, this worked.
