### ISSUE TITLE
Play a part of MediaSource

### ISSUE THREAD

**Issue by Sybergoth** [google/ExoPlayer#4116]
### Description
In our application we have a heavy usage of video files (Local) which need to be played from a certain start point to a certain end point that are known in advance. 

The way we achieve it now with Media Player is by preparing each video file when it should be played, seek to the start point and run an handler which is set to run for a duration of (endTime - startTime).

We're migrating all of our functionality of video playing to ExoPlayer now and would want to use the advantages of the Media Sources functionality it provides. We want to combine the video files using ConcatenatingMediaSource to have one seamless video stream.

After some search over the documentation I couldn't find any Media Source which allows to set a start & end time.

I was hoping you could give some insights on this topic.

### Version of ExoPlayer being used
ExoPlayer 2.6.1

**Comment by eneim** [comment]
@Sybergoth have not actually tried yet, but there is ``ClippingMediaSource`` where you feed it with an actual ``MediaSource``, along with ``startUs``, ``endUs`` so it sounds to fit your requirement. I'm seeing it in 2.7.3, but it was there in 2.6.1 I guess.

**Comment by Sybergoth** [comment]
@eneim  Thanks, exactly what I was looking for.
