### ISSUE TITLE
question youtube

### ISSUE THREAD

**Issue by SergiiGudym** [google/ExoPlayer#4117]
i have similar question like https://stackoverflow.com/questions/48543667/how-to-generate-or-obtain-youtube-dash-link-for-exoplayer

In sample you use dash. And now I can't found any solution how get dash link. 

Do you have any versions, which use direct link "...get_video_info?&video_id=..." ?

**Comment by erdemguven** [comment]
Sorry, ExoPlayer doesn't provide this functionality.
