### ISSUE TITLE
Slow down video playback (x0.5)

### ISSUE THREAD

**Issue by Joseph82** [google/ExoPlayer#4118]
I have seen that recently has been introduced the speed-up feature for speeding up the playback of the media. 

As remarked [here](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/PlaybackParameters.java#L48) it is only possible to increase the playback speed, and not to change arbitrary the speed.

I  was wondering if there is still a way for having a playback with a lower speed than x1.0
Is there any other, maybe hidden, functionality in ExoPlayer fo that? If not, what would be the best way for implementing such feature?

**Comment by andrewlewis** [comment]
Passing a speed between zero and one gives slowed down playback. One is realtime playback.

**Comment by Joseph82** [comment]
You cannot pass a value between 0 and 1. 

as per the speed parameter passed in the constructor [`PlaybackParameter` ](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/PlaybackParameters.java#L48):

> @param speed The factor by which playback will be sped up. Must be greater than zero.

**Comment by andrewlewis** [comment]
You can pass 0.5 (which is greater than zero) to play at half speed, for example.

**Comment by Joseph82** [comment]
oh God, sorry! I was probably drunk!
