### ISSUE TITLE
demo-ima - video will restart after resuming from background

### ISSUE THREAD

**Issue by giladna** [google/ExoPlayer#4119]
Hi @andrewlewis,

in v2.7.3
Using the following adtag which contains midroll/postroll

  <string name="ad_tag_url"><![CDATA[https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpostpodbumper&cmsid=496&vid=short_onecue&correlator=]]></string>

Go to the background in the very first the second that the midroll ad loading time  or during  the midroll playback.
The on resume action will result with preparing the player again without resuming ad playback and video will start from position 0

BR,
Gilad

**Comment by andrewlewis** [comment]
Backgrounding/resuming seems to work fine in the demo app using the sample ad tags.

Please could you provide your ad tag?

**Comment by giladna** [comment]
@andrewlewis 

in 2.7.3: ima-demo

You can use 
https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpost&cmsid=496&vid=short_onecue&correlator=

just go to bg in midroll you will see on resume content starts from pos 0

Gilad

**Comment by andrewlewis** [comment]
ima-demo is intended to be very simple and doesn't fully implement saving the content position (it doesn't override `onSaveInstanceState` or otherwise persist the position). Please try using the main demo app.
