### ISSUE TITLE
IMA Ad Load error when no connectivity

### ISSUE THREAD

**Issue by Veeyikpong** [google/ExoPlayer#4120]
Hi,
i've tried to implement ExoPlayer and it worked fine in every aspect. Very good player.
However, when i try to turn off my internet connection (while playing content), and when it try to load the next IMA ad, i can't catch the ad load error. I've tried using IMAAdsLoader.getAdsloader method to override the adsloader but still unable to catch the error and resume my content.

Below are some of my codes:

```
String adTag = context.getString(R.string.ad_tag_url);
        ImaAdsLoader imaAdsLoader = new ImaAdsLoader(context, Uri.parse(adTag));

        imaAdsLoader.getAdsLoader().addAdErrorListener(new AdErrorEvent.AdErrorListener() {
            @Override
            public void onAdError(AdErrorEvent adErrorEvent) {
                Log.i("IMAAds","ERROR");
            }
        });
        MediaSource mediaSourceWithAds =
                new AdsMediaSource(
                        contentSource,
            /* adMediaSourceFactory= */ this,
                        imaAdsLoader,
                        mPlayerView.getOverlayFrameLayout(),
            /* eventHandler= */ null,
            /* eventListener= */ null);

      
            player.prepare(mediaSourceWithAds);`
```
Please help on how to catch the load ad error when theres no connectivity.

Thank you.

**Comment by andrewlewis** [comment]
This looks like it should work. Does your `onAdError` callback never get called? Do you see any other errors (e.g., from the player's event listener)?

**Comment by ojw28** [comment]
Closing due to lack of updates.
