### ISSUE TITLE
ExoplayerImpl.java getDuration() returing differnt value but not the mediaPresentationDuration value incase of SegmentTmeline mpds.

### ISSUE THREAD

**Issue by pokuri3** [google/ExoPlayer#4121]
I am trying to test the clear DASH content in the exoplayer2 sample app and corresponding mpd file url is http://demo.unified-streaming.com/video/ateam/ateam.ism/ateam.mpd .

As per the above mpd file, the content duration is (mediaPresentationDuration="PT1M41.568367S") 101568000 micro sec. So when ever i request for the get exoplayerImpl.getDuration() i am expecting the same to show progress seek bar. But it is returning some delta value instead of actual mpd value which is 101476000.
I observed this behavior in Exoplayer 2.6.1 but i tried the same in Exoplayer 1.5 it is returning the correct value.If the mpd file contains SegmentBase instead of SegmentTimline then again seems returning correct value even in Exolayer2.6.1.

DebugLog:
DashMediaSource at PeriodSeekInfo construction, durationUs 101568000
Timeline.java durationUs set 101476000

**Comment by ojw28** [comment]
We calculate the actual duration for which media is provided, for all representations. Which in this case is shorter than the duration specified at the top level in the DASH manifest. For nicely produced content we'd expect the actual durations to match the top level duration in the manifest.

Note that there's a proposal to advise against "short representations" in DASH IOP. See https://github.com/Dash-Industry-Forum/DASH-IF-IOP/issues/178.
