### ISSUE TITLE
MIBOX3 only displays first frame of video playback.

### ISSUE THREAD

**Issue by jarrodoxical** [google/ExoPlayer#4123]
MIBOX3 (OMX.AMLOGIC.AVC.DECODER.AWESOME) only displays first frame of video playback.

### Issue description
On MIBOX3 using hardware codec OMX.AMLOGIC.AVC.DECODER.AWESOME fails to play ts video properly.

### Reproduction steps
Initialise SimpleExoPlayer
Prepare MediaSource
playing audio with first video frame remaining still or black screen (with no indication of errors in console)

### Link to test content
we are using mainly internal live ts streams with the same encoding as below
"uri": "https://devstreaming-cdn.apple.com/videos/streaming/examples/bipbop_4x3/gear1/fileSequence0.ts"

### Version of ExoPlayer being used
reproduced on Exoplayer 2.6.1 and below (including 2.5.3)
Previous Exoplayer versions did play the ts streams on this device (Exoplayer 2.4 via ExoMedia Library)

### Device(s) and version(s) of Android being used
Xiaomi MiBox MDZ-16-AB
Codec: OMX.AMLOGIC.AVC.DECODER.AWESOME
Model: android.os.Build.MODEL.toUpperCase().equals("MIBOX3")
Util.MANUFACTURER: "Xiaomi"
Util.DEVICE: "once"
Android TV version 6.0

### Workaround 
if we simply deny this amlogic codec manually from within our custom MediaCodecUtil class then OMX.google.h264.decoder is next in line and plays the same video stream as expected. However, choppy software playback is not suitable for this lower-end device at all. 

### Attempted fixes.
-adding the offending "awesome" codec to the workarounds in the exoplayer (codecNeedsSetOutputSurfaceWorkaround) result in no change.
-the ts flags added to the extractor have no effect on or off.

```
DefaultExtractorsFactory def =new DefaultExtractorsFactory();
                def.setTsExtractorFlags(DefaultTsPayloadReaderFactory.FLAG_DETECT_ACCESS_UNITS);
                def.setTsExtractorFlags(DefaultTsPayloadReaderFactory.FLAG_ALLOW_NON_IDR_KEYFRAMES);
                def.setTsExtractorMode(TsExtractor.TS_STREAM_TYPE_H264);
                return new ExtractorMediaSource.Factory(mediaDataSourceFactory).setExtractorsFactory(def)
                        .createMediaSource(uri, mainHandler, null);
```

### A full bug report captured from the device
[video-playback-failure-exoplayer-on-mibox-bug-report.zip](https://github.com/google/ExoPlayer/files/1906735/video-playback-failure-exoplayer-on-mibox-bug-report.zip)

**Comment by ojw28** [comment]
If playback works (albeit choppily) when using OMX.google.h264.decoder, then this sounds like a device specific issue related to OMX.AMLOGIC.AVC.DECODER.AWESOME. You should report this issue to Xiaomi.

**Comment by jarrodoxical** [comment]
Update: fixed by adding OMX.AMLOGIC.AVC.DECODER.AWESOME to the **codecNeedsSetOutputSurfaceWorkaround** function and forcing surfaceView. 

FWIW: When experiencing this same green screen issue on another device [ExoPlayerLib/2.6.1] [OMX.allwinner.video.decoder.avc] [PNDP70M7BLK, PNDP70M7BLK, Pendo, API 25] we found that textureView fixed the first playback but needed a surfacemanager class to change surfaces. Luckily the above codec workaround also fixed the issue entirely for that device.

Now, continuous playback works great with this workaround but there can be a big delay in switching surfaces (after initial playback start), which is very annoying as that is what our app does a lot of.

As a followup question, is there any way of improving the surface switching delay? 

When the surface workaround is engaged it seems to discard the entire video buffer data and only displays some faraway video frame until the sound catches up to that frozen frame. It provides a very jarring experience e.g. for fullscreen open and close.

**Comment by ojw28** [comment]
Currently `codecNeedsSetOutputSurfaceWorkaround` disables two things: Use of `setOutputSurfaceV23` and use of `DummySurface`. Could you try a more targeted workaround, which is to revert your change to `codecNeedsSetOutputSurfaceWorkaround` and instead return false from `shouldUseDummySurface`. This will disable use of `DummySurface` but still allow `setOutputSurfaceV23` for seamless switching between non-dummy surfaces. This may or may not work, depending on what the underlying issue is for this device.

> When the surface workaround is engaged it seems to discard the entire video buffer data and only displays some faraway video frame until the sound catches up to that frozen frame. It provides a very jarring experience e.g. for fullscreen open and close.

The problem is that when the workaround is enabled we need to tear down the codec and instantiate a new one when switching surface. A new codec can only start decoding from the next key-frame, and so the delay you see is a result of this. We're not actually discarding any buffer when we do this.

As a final point, please report this issue to the device manufacturer if you have yet to do so.

**Comment by tonihei** [comment]
Were you able to try the more targeted workaround as suggested by @ojw28 above?
