### ISSUE TITLE
Changing audio track if other track is still playing

### ISSUE THREAD

**Issue by marinica94** [google/ExoPlayer#414]
I am switching from mediaplayer to exoplayer in my project and because there is few documentation I wanted to ask some questions here.

I successfully created the player:

   exoPlayer = ExoPlayer.Factory.newInstance(1);
   playerControl = new PlayerControl(exoPlayer);

and the music starts playing when I click on my music list:

    musicList.addOnItemTouchListener(
            new RecyclerItemClickListener(getApplicationContext(), new RecyclerItemClickListener.OnItemClickListener() {
                @Override
                public void onItemClick(View view, final int position) {

                    mediaController.show(0);

                    currentPosition = position;
                    URL = musicUrl.get(position);

                    Uri uri = Uri.parse(URL);

                    sampleSource = new DefaultSampleSource(new FrameworkSampleExtractor(getApplicationContext(), uri, null), 2);
                    audioRenderer = new MediaCodecAudioTrackRenderer(sampleSource, null, true);

                    exoPlayer.prepare(audioRenderer);
                    exoPlayer.setPlayWhenReady(true);

                }
            })
    );

The problem is I don't know how to change the music if I click on another track on the list, if the track number 2 is playing if I click on track numer 6 to change to it.If anyone can guide me with this problem it will be perfect.

I really readed all topics from stackoverflow and I can't find the solution in theyr demo app because there is playing only 1 track, they don't change it.

**Comment by ojw28** [comment]
You should be able to call exoPlayer.stop() and then exoPlayer.prepare() with a renderer that you've built for the next URI.
