### ISSUE TITLE
Can't seek mp4 file in Nexus 6 device

### ISSUE THREAD

**Issue by wifiteamab** [google/ExoPlayer#4144]
### Issue description
Playing a mp4 file with ExoPlayer demo app, the video stopped and get "ExoPlayerImplInternal: Internal runtime error." when press the seek bar to seek video.

### Reproduction steps
1. Add the mp4 file local path uri into media.exolist.json and Run demo APP.
2. Start APP and press the video to play
3. When video playing, press the seek bar to seek video to any position.
4. The video stopped and log show 
"Internal runtime error" , "android.media.MediaCodec$CodecException: Error 0x80001009".

### Link to test content
[Video1.zip](https://github.com/google/ExoPlayer/files/1922332/Video1.zip)

### Version of ExoPlayer being used
r2.7.3

### Device(s) and version(s) of Android being used
Nexus 6, Android7.1.1

### A full bug report captured from the device
[bugreport1.txt](https://github.com/google/ExoPlayer/files/1922348/bugreport1.txt)

**Comment by tonihei** [comment]
Sorry for the late answer. I tried to play the file and can reproduce the problem on a Nexus 6. This is a known platform issue and already fixed. Please update your system to the latest release and the problem should go away.
