### ISSUE TITLE
When video begins to play, how can you reduce buffering time and play faster?

### ISSUE THREAD

**Issue by hahafamilia** [google/ExoPlayer#4147]
Before filing an issue:
-----------------------

When reporting a bug:
-----------------------

### Issue description
It takes more than 15 seconds for mp4 video to start playing.
I have tested it with a sample app that someone else has created.
The app plays faster.
https://play.google.com/store/apps/details?id=me.infimate.exoplayersample

### Link to test content
mail to dev.exoplayer@gmail.com 

### Version of ExoPlayer being used
2.7.3

### Device(s) and version(s) of Android being used
SM-A500L, Android 6.0.1

### A full bug report captured from the device

    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
      

        dataSourceFactory = new DefaultDataSourceFactory(this, BANDWIDTH_METER
                , new DefaultHttpDataSourceFactory(Util.getUserAgent(this, "SampleExoPlayer"), BANDWIDTH_METER));
        mainHandler = new Handler();

        setContentView(R.layout.activity_simple_exo_player);

        getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN, WindowManager.LayoutParams.FLAG_FULLSCREEN);
        Thread.setDefaultUncaughtExceptionHandler(new ExceptionHandler(this));

        playerView = (PlayerView) findViewById(R.id.player_view);
        debugTextView = findViewById(R.id.debug_text_view);

    }

private void initializePlayer(Uri mp4VideoUri) {

    // 1. Track Selector
    TrackSelection.Factory videoTrackSelectionFactory = new AdaptiveTrackSelection.Factory(BANDWIDTH_METER);
    trackSelector = new DefaultTrackSelector(videoTrackSelectionFactory);

    eventLogger = new EventLogger((MappingTrackSelector) trackSelector);

    DefaultRenderersFactory renderersFactory = new DefaultRenderersFactory(this, null,
            DefaultRenderersFactory.EXTENSION_RENDERER_MODE_PREFER);

    DefaultAllocator defaultAllocator = new DefaultAllocator(true, C.DEFAULT_BUFFER_SEGMENT_SIZE);
    loadControl = new DefaultLoadControl(defaultAllocator,
            DefaultLoadControl.DEFAULT_MIN_BUFFER_MS ,
            DefaultLoadControl.DEFAULT_MAX_BUFFER_MS,
            DefaultLoadControl.DEFAULT_BUFFER_FOR_PLAYBACK_MS,
            DefaultLoadControl.DEFAULT_BUFFER_FOR_PLAYBACK_AFTER_REBUFFER_MS,
            DefaultLoadControl.DEFAULT_TARGET_BUFFER_BYTES,
            DefaultLoadControl.DEFAULT_PRIORITIZE_TIME_OVER_SIZE_THRESHOLDS
    );

    // 2. Create the player
    player = ExoPlayerFactory.newSimpleInstance(renderersFactory, trackSelector, loadControl );
    player.addListener(new PlayerListener());
    player.addListener(eventLogger);
    player.addMetadataOutput(eventLogger);
    player.addAudioDebugListener(eventLogger);
    player.addVideoDebugListener(eventLogger);
    player.setPlayWhenReady(true);

    playerView.setPlayer(player);

    playerView.setPlaybackPreparer(this);
    debugViewHelper = new DebugTextViewHelper(player, debugTextView);
    debugViewHelper.start();

    DefaultExtractorsFactory extractorsFactory = new DefaultExtractorsFactory();

    MediaSource videoSource = new ExtractorMediaSource.Factory(dataSourceFactory).setExtractorsFactory(extractorsFactory)
            .createMediaSource(mp4VideoUri, mainHandler, eventLogger);

    // Prepare the player with the source.
    player.prepare(videoSource);

}

**Comment by hahafamilia** [comment]
I found it.
I do not know why, but building the APK file in release mode makes the video play faster.
debug build : 15 seconds or more
release build : About 3 to 4 seconds
The issue has been resolved.
But I am curious. Can you tell me why?

**Comment by botaydotcom** [comment]
Cool, glad that you have found out the issue. Normally debug build will enable a lot of debug-related stuffs, such as enable tracing (for using Systrace), more logging, and generally disable code optimization. Before you upload your app to PlayStore, you will have to build it in release mode, so this is intentional.
