### ISSUE TITLE
DRM onDrmSessionManagerError JSON body response

### ISSUE THREAD

**Issue by AlinaVoronkovaEpam** [google/ExoPlayer#4155]
### Issue description
I'm trying to get JSON body responce in `onDrmSessionManagerError` but there is no such info in `HttpDataSource.InvalidResponseCodeException` error. Could you please provide me info how can I get JSON body inside `DefaultDrmSessionManager.EventListener` `onDrmSessionManagerError` callback.
 
### Version of ExoPlayer being used
com.google.android.exoplayer:exoplayer:2.6.1

I'll appreciate a quick answer.
Thanks in advance.

**Comment by botaydotcom** [comment]
Hi @AlinaVoronkovaEpam,
I'm not sure about your specific situation (are you using `DefaultHttpDataSource`, `CronetDataSource`, or `OkHttpDataSource` for the DRM callback?), but I don't think this is supported by default.

One thing you may try is to debug and step into the place where the `InvalidResponseCodeException` was thrown - probably from the `open(DataSpec)` method of one of these data source classes. Try to inspect the response at that point to see if you can get the expected JSON body response in that case.

If you can get your expected JSON body there, one option is to subclass/encapsulate whatever `HttpDataSource` you are using into a new `HttpDataSource` implementation, catch when the `InvalidResponseCodeException` was thrown, and try to read from the connection at that point. Then you can inject that custom `HttpDataSource` in the `HttpMediaDrmCallback` yourself.

**Comment by brol1dev** [comment]
@botaydotcom I'm working with @AlinaVoronkovaEpam on this one. I was able to read the JSON by subclassing `DefaultHttpDataSource`. but I see that `InvalidResponseCodeException` doesn't accept a body as part of its arguments, so what do you think is the right approach? I'm thinking we should subclass `InvalidResponseCodeException` (in reality its parent since `InvalidResponseCodeException` is final) to add an extra field that will contain the JSON and that way we can read it on our callback accordingly.

**Comment by brol1dev** [comment]
BTW I was able to finish the whole workflow. I ended up extending `HttpDataSourceException` and adding a new field which contains the JSON response body and we can read that right when the error happens.

Thanks for the help @botaydotcom 👍

**Comment by brol1dev** [comment]
To add more details if anyone else has the same problem. We extended `OoyalaDrmHttpDataSource` and on the `open(DataSpec dataSpec)` method when we identify there's an error, we just parse the `connection.getErrorStream()` object which contains the response body that for our case it's a JSON text.

**Comment by botaydotcom** [comment]
Cool, glad that you can resolve your problem!

**Comment by AlinaVoronkovaEpam** [comment]
Thanks!
