### ISSUE TITLE
Live video is strucking in the middle

### ISSUE THREAD

**Issue by RadhikaBalla** [google/ExoPlayer#4158]
Hello,

I am using exoplayer-realase-v2 , and trying to play "http://my2.videodb.in:8081/medilifetv/golive/playlist.m3u8" this hls stream  in android marshmallow mobile. But While I am playing video it is getting struck in the middle and showing below errors. Could you please help me out. 

Following is the errors that I am getting in android logcat.

**E/ACodec: cannot find aac bit rate
Surface: getSlotFromBufferLocked: unknown buffer: 0x7f2804ffa0**

**Comment by botaydotcom** [comment]
Hi @RadhikaBalla,
I think the short error message you provided is not enough to analyse your issue. Can you please provide more information, including:
- What Android device you are using (which you mentioned that it run M)?
- A bug report captured after you encountered the error.

We will look into this once we receive more info. Thank you.

**Comment by kmoza** [comment]
How do media info like audio bit rate is fetched for live streams or streams hosted on url

**Comment by ojw28** [comment]
Closing due to lack of required information.
