### ISSUE TITLE
Cannot manage to read a DASH video from cache after downloading it

### ISSUE THREAD

**Issue by ArchOrn** [google/ExoPlayer#4159]
### Issue description
I am currently building a streaming application which uses the `ExoPlayer` DASH capabilities as my videos are using MPD manifests.
As the download management system offered by the `ExoPlayer` is still in development, I tried out myself to recreate one with less functionnalities using the `DashDownloader` provided in the library.
After downloading a DASH video in a specific `SimpleCache` object, I cannot find a way to use the CacheDataSource properly despite the examples I can find on these issues or on the sources tests.

### Reproduction steps
_The following code is written in Kotlin_

1. (WITH INTERNET ON) Use the `DashDownloader` to download a DASH media with a certain representation set (the lowest birate for test purposes) on a `SimpleCache` instance:
```
val cache = SimpleCache(File(context.externalCacheDir, "media"), NoOpCacheEvictor())
val okHttpClient = StreamUtil.buildDashOkHttpClient(...)
val downloaderConstructorHelper = DownloaderConstructorHelper(cache, OkHttpDataSourceFactory(okHttpClient, downloadManager.userAgent, null))
val dashDownloader = DashDownloader(manifestUrl.toUri(), downloaderConstructorHelper)
val representationKeys = StreamUtil.getRepresentationKeysFromDashManifest(DownloadManager.DOWNLOAD_BITRATE, ...)
dashDownloader.selectRepresentations(representationKeys)
dashDownloader.init()
dashDownloader.download(this)
```
2. (WITHOUT INTERNET) Create the `MediaSource` from the cache to read the downloaded video with the same `manifestUrl` as last step:
```
val dataSourceFactory = CacheDataSourceFactory(cache, DefaultDataSourceFactory(context, userAgent), CacheDataSource.FLAG_BLOCK_ON_CACHE)
val mediaSource = DashMediaSource.Factory(DefaultDashChunkSource.Factory(dataSourceFactory), dataSourceFactory).createMediaSource(manifestUrl.toUri(), handler, listener)
val currentParameters = trackSelector.parameters
val newParameters = currentParameters?.buildUpon()?.setMaxVideoBitrate(DownloadManager.DOWNLOAD_BITRATE)?.build()
trackSelector.parameters = newParameters
player = StreamUtil.buildExoPlayer(ctx, trackSelector, mediaType, drmSessionManager)
player?.playWhenReady = true
player?.prepare(mediaSource, true, true)
```

### Link to test content
I do not think for now that this is something related to the media itself. If it is then I will send the details by mail later on. For a bit more details, this is a DASH video file, using DRMs that I also store / use using `OfflineLicenseHelper`.

### Version of ExoPlayer being used
Here are my `ExoPlayer` dependencies:
```
api("com.google.android.exoplayer:exoplayer:2.7.3")
api("com.google.android.exoplayer:extension-okhttp:2.7.3")
```

### Device(s) and version(s) of Android being used
Testing on Pixel 2 (Android 8.1.0)

### A full bug report captured from the device
After the described steps, the video is not starting as intended, even if I select the downloaded representation set. I have the following errors from the different `ExoPlayer` listeners that I formatted:
```
E/ExoPlayerListener: MediaSourceEventListener onLoadError() | Unable to connect to <my_dash_manifest_url> | dataType: 4, trackType: -1, track.bitrate: null
E/ExoPlayerListener: MediaSourceEventListener onLoadError() | Unable to connect to <my_dash_manifest_url> | dataType: 4, trackType: -1, track.bitrate: null
E/ExoPlayerListener: MediaSourceEventListener onLoadError() | Unable to connect to <my_dash_manifest_url> | dataType: 4, trackType: -1, track.bitrate: null
E/ExoPlayerListener: MediaSourceEventListener onLoadError() | Unable to connect to <my_dash_manifest_url> | dataType: 4, trackType: -1, track.bitrate: null
E/ExoPlayerListener: MediaSourceEventListener onLoadCanceled() | dataType: 4, trackType: -1, track.bitrate: null
E/ExoPlayerListener: ExoPlayer onPlayerError() | null
```

On the last error, `null` is the exception message I should have.

---

Regarding everything I read throughout the different sources and those errors, I wonder if the `CacheDataSource` is extracting the `DashManifest` from the cache or if it tries to get it from the internet. Did I miss something and need to save the `DashManifest` myself ?

Thank you for your help,

Raphaël

**Comment by ArchOrn** [comment]
After some more investigations with a different DASH manifest (see: http://yt-dash-mse-test.commondatastorage.googleapis.com/media/feelings_vp9-20130806-manifest.mpd), it does exactly the same.
However, with this smaller example, I tried to download every representations instead of only the "smaller" ones and it works.

Now I am wondering what could be wrong with the representation keys I selected for my download, my goal being to select a specific video quality, the best audio (or the one corresponding to the equivalent bitrate) for each language, and all the subtitles available.

**Comment by ojw28** [comment]
I think the problem is that during playback the selector is trying to use tracks that were not downloaded.

Try using [FilteringDashManifestParser](https://github.com/google/ExoPlayer/blob/r2.7.3/library/dash/src/main/java/com/google/android/exoplayer2/source/dash/manifest/FilteringDashManifestParser.java) for playback, specifying only the representations that you've downloaded. You can do this by [setting the manifest parser](https://github.com/google/ExoPlayer/blob/r2.7.3/library/dash/src/main/java/com/google/android/exoplayer2/source/dash/DashMediaSource.java#L138) when creating your `DashMediaSource`. This makes it so the player will only see the downloaded representations.

**Comment by ArchOrn** [comment]
Thank you for your quick answer. I will try that right away! 😃

**Comment by ArchOrn** [comment]
After some tests with the full length movies I have to handle, it works now, even with the local DRM handling.
Thank you for your support and your awesome work to provide us this library.

Cheers!
