### ISSUE TITLE
Question about the Dolby Atmos support in 2.6.1

### ISSUE THREAD

**Issue by unext-wendong** [google/ExoPlayer#4165]
This is one question about the change to support Dolby Atmos in release 2.6.1.
https://github.com/google/ExoPlayer/commit/c3b92f84562aa55dc79d764f6fa4cd2e827f39e7

One of changed places is in file `MediaCodecUtil.java` when querying for the decoders available for the mime type, `audio/eac3-joc` is tried first then `audio/eac3`.

From the change itself and the comment there, it seems to be for decoders which are able to decode Dolby Atmos streams but do not list `audio/eac3-joc` as their supported mime type (in their configuration file e.g. `media_codecs.xml`).

I think we are seeing one of those decoders. It works fine with version 2.6.0, but errors out on version 2.6.1 during codec configuration i.e. `MediaCodec.configure(MediaFormat format, Surface surface, MediaCrypto crypto, int flags)`. It throws the `IllegalArgumentException` exception.

The reason seems to be that the passed in `MediaFormat format` in this method call contains `audio/eac3-joc` as the mime type instead of `audio/eac3` even though this decoder was queried by using `audio/eac3`.

Wanted to confirm if it is a miss in this change that it should be using the same mime type to configure the decoder as the one used to query it.

**Comment by andrewlewis** [comment]
This sounds like a bug. Please could you confirm that changing the MIME type of the format used to configure the codec to `audio/eac3` fixes this? Thanks.

**Comment by unext-wendong** [comment]
> Please could you confirm that changing the MIME type of the format used to configure the codec to audio/eac3 fixes this? Thanks.

Yes, with this change the issue is not reproduced.
