### ISSUE TITLE
Video block when switch between two textureViews on Redmi Note 4

### ISSUE THREAD

**Issue by tuesda** [google/ExoPlayer#4166]
### Issue description
Video block when switch between two texture views on Redmi Note 4

### Reproduction steps

1. Setup two texture views in a activity
2. Start play a video with first texture view
3. Set second texture view as video display view when click second texture view
4. You will find that audio is normal but frame block for a few seconds

### Link to test content
This issue is not related with video content

### Version of ExoPlayer being used
ExoPlayer version: 2.7.2 and 2.7.3
but 2.7.1 doesn't have this issue, so I think this issue occur with 2.7.2 firstly

### Device(s) and version(s) of Android being used
Redmi Note 4

**Comment by ojw28** [comment]
We disabled seamless surface switching on Redmi Note 4 because others were reporting that it caused ANR issues. See https://github.com/google/ExoPlayer/issues/4006 for details. Did surface switching always work reliably for you, on this device?

It may be that we need to target the workaround more specifically to cases where `DummySurface` is being used, since perhaps that's the only case to which the ANR issue applies.

**Comment by tuesda** [comment]
Thanks for your reply!
Is there a api for checking if the device  can seamless switching?
We don't find ANR issues for now.

**Comment by tuesda** [comment]
Is better dispatching a buffer state for devices like Redmi Note 4 when switching surfaces, rather than frame block while audio is normal playing.

Thanks

**Comment by ojw28** [comment]
> Is there a api for checking if the device can seamless switching?

No, however:
* It's not available on any device where `Util.SDK_INT < 23`.
* You can look at `MediaCodecVideoRenderer.codecNeedsSetOutputSurfaceWorkaround` to see where we're disabling it on devices for wihch `Util.SDK_INT >= 23`.

> Is better dispatching a buffer state for devices like Redmi Note 4 when switching surfaces, rather than frame block while audio is normal playing.

You can do this by triggering a seek call on the player at the same time as you swap the surface (the seek call should occur immediately afterwards).
