### ISSUE TITLE
Can't play audio for m3u8 play list (EXT-X-VERSION 2)

### ISSUE THREAD

**Issue by asos-pengjiang** [google/ExoPlayer#4167]
### Issue description
Can't play/detect audio for m3u8 play list for ```#EXT-X-VERSION:2```

If the video is segmented by the HLS tool version 3 ( like the one in the demo app https://devstreaming-cdn.apple.com/videos/streaming/examples/bipbop_4x3/gear1/prog_index.m3u8), it works. 

### Reproduction steps
Using ExoPlayer demo app, play the m3u8 playlist I sent to the dev.exoplayer@gmail.com 

### Link to test content
video link is sent to dev.exoplayer@gmail.com 

### Version of ExoPlayer being used
2.73

### Device(s) and version(s) of Android being used
Nexues 6P (Android 8.1.0)
Pixel (Android 8.1.0)

### A full bug report captured from the device
`adb bugreport`: 
[bugreport-angler-OPM3.171019.019-2018-04-23-14-36-31.zip](https://github.com/google/ExoPlayer/files/1938423/bugreport-angler-OPM3.171019.019-2018-04-23-14-36-31.zip)

`adb log`: 
```
04-23 14:35:53.442 602-15680/? E/OMX-VDEC-1080P: Enable/Disable allocate-native-handle allowed only on input port!
    set_parameter: Error: 0x80001019, setting param 0x7f000045
04-23 14:35:53.442 602-15680/? E/OMXNodeInstance: setParameter(0xf1b22744:qcom.decoder.avc, OMX.google.android.index.allocateNativeHandle(0x7f000045): Output:1 en=0) ERROR: UnsupportedSetting(0x80001019)
04-23 14:35:53.442 602-15680/? E/OMX-VDEC-1080P: Extension: OMX.google.android.index.storeANWBufferInMetadata not implemented
04-23 14:35:53.451 602-602/? E/OMX-VDEC-1080P: Extension: OMX.google.android.index.describeColorAspects not implemented
04-23 14:35:53.451 602-13188/? E/OMX-VDEC-1080P: Extension: OMX.google.android.index.describeHDRStaticInfo not implemented
04-23 14:35:53.452 602-2658/? E/OMX-VDEC-1080P: Extension: OMX.google.android.index.storeANWBufferInMetadata not implemented
    Extension: OMX.google.android.index.configureVideoTunnelMode not implemented
    Extension: OMX.google.android.index.useAndroidNativeBuffer is supported
    get_config: unknown param 1863319556
04-23 14:35:53.452 602-2658/? E/OMXNodeInstance: getConfig(0xf1b22744:qcom.decoder.avc, ConfigAndroidVendorExtension(0x6f100004)) ERROR: BadParameter(0x80001005)
04-23 14:35:53.475 602-3025/? E/OMX-VDEC-1080P: Extension: OMX.google.android.index.AndroidNativeBufferConsumerUsage not implemented
```

**Comment by ojw28** [comment]
The only playback I can see in the bugreport looks like it proceeded successfully. The log snippet does not appear in the bugreport. Are you sure you attached the right one, and generated it immediately after seeing the issue?

**Comment by ojw28** [comment]
Edit: The log snippet is in the bugreport after all. I can't see any playback failure though. What do you actually observe happening? Have you made any modifications to the demo app other than adding the sample?

**Comment by asos-pengjiang** [comment]
No, I just added the video URL in the play list ( I have sent to `dev.exoplayer@gmail.com`), and try to play with it. The demo app is from the branch `release-v2` commit https://github.com/google/ExoPlayer/commit/4b531dcc5211ef9cb1c2adea5c12642f549c4c78.

The video can be played, but there is no audio playback. In the demo app, it also doesn't show the audio label.

**Comment by ojw28** [comment]
Ah, I see the problem now, thanks! @AquilesCanta - Seems `TsExtractor` is not seeing the audio track (even when playing a single segment using `ExtractorMediaSource`).

**Comment by AquilesCanta** [comment]
Hi, the issue here is that the first PMT in the segment contains only video:

```
    TS contains Section...
    SI packet (length=21): 
        PID:  256 (0x0100)

        Guess table from table id...
        PMT-decoding....
        Table_ID: 2 (0x02)  [= Program Map Table (PMT)]
        section_syntax_indicator: 1 (0x01)
        (fixed '0'): 0 (0x00)
        reserved_1: 3 (0x03)
        Section_length: 18 (0x0012)
        Program_number: 1 (0x0001)
        reserved_2: 3 (0x03)
        Version_number: 0 (0x00)
        current_next_indicator: 1 (0x01)  [= valid now]
        Section_number: 0 (0x00)
        Last_Section_number: 0 (0x00)
        reserved_3: 7 (0x07)
        PCR PID: 8191 (0x1fff)
        reserved_4: 15 (0x0f)
        Program_info_length: 0 (0x0000)

        Stream_type loop: 

            Stream_type: 27 (0x1b)  [= AVC video stream as defined in ITU-T Rec. H.264 | ISO/IEC 14496-10 Video]
            reserved_1: 7 (0x07)
            Elementary_PID: 257 (0x0101)
            reserved_2: 15 (0x0f)
            ES_info_length: 0 (0x0000)

        CRC: 3229871463 (0xc083ed67)
```

After that, the next PMT declares an audio stream. So the fix for this is to remove the first PMT in the stream.

**Comment by asos-pengjiang** [comment]
@AquilesCanta the video can be played on iOS successfully with sound stream detected. With the same video, if I use HLS tool (version 3) to create m3u8 play list, it can also detect the audio stream. Do you think maybe `TsExtractor` only handle the version 3? I sent another video URL, just in case.

**Comment by AquilesCanta** [comment]
It's not about the HLS versioning. The [HLS spec](https://tools.ietf.org/html/draft-pantos-http-live-streaming-23) actually hints there should be a single PMT. 

I appreciate other players might handle this correctly, but you could maybe fork TS extractor to better handle your case. I just don't see an elegant solution for working around this, and with every workaround for bad media we add, our HLS implementation becomes harder and harder to maintain.
