### ISSUE TITLE
Allow processing of last output buffer in MediaCodecTrackRenderer drainOutputBuffer

### ISSUE THREAD

**Issue by ptran-gpfw** [google/ExoPlayer#417]
In my own usage of MediaCodec (separate from ExoPlayer) I have observed `dequeueOutputBuffer` return info on an output buffer that has both a) a valid buffer index and b) a flag bitfield that contains `MediaCodec.BUFFER_FLAG_END_OF_STREAM`.

In MediaCodecTrackRenderer `drainOutputBuffer` ([line 832](https://github.com/google/ExoPlayer/blob/dev/library/src/main/java/com/google/android/exoplayer/MediaCodecTrackRenderer.java#L832)), the detection of `BUFFER_FLAG_END_OF_STREAM` causes the method to return before the call to `processOutputBuffer`. This prevents processing of the last output buffer.

**Comment by ojw28** [comment]
Hm. Doesn't this depend on how you use BUFFER_FLAG_END_OF_STREAM when queuing input buffers? If you set it on the final real input buffer then I'd expect to see it when dequeuing the final real output buffer. If you set it separately on an input buffer that follows the final real one, then I wouldn't expect that. ExoPlayer does the latter, hence why we don't handle the output buffer on which it is set.

If you have a concrete example (media + device combination) where this happens, then we can/should fix it. I'm not yet convinced there's a problem though ;).

**Comment by ptran-gpfw** [comment]
I'll try to repro with exoplayer demo and post an update.

**Comment by ojw28** [comment]
Please re-open if you manage to repro this. Thanks!

**Comment by ojw28** [comment]
Turns out the standard Google AAC decoder does this, so we end up dropping the last frame of audio. Not particularly important, but we should fix it nevertheless.
