### ISSUE TITLE
Get the actual playing mp4 file from DashPlaylist?

### ISSUE THREAD

**Issue by jboisjo** [google/ExoPlayer#4179]
### Issue description
Question,

Where i can get the actual mp4 file playing in the player from my DashPlaylist?

I can get all files that they are loaded from the MediaSourceEventListener

```
override fun onLoadStarted(dataSpec: DataSpec?, dataType: Int, trackType: Int, trackFormat: Format?,
                               trackSelectionReason: Int, trackSelectionData: Any?, mediaStartTimeMs: Long,
                               mediaEndTimeMs: Long, elapsedRealtimeMs: Long) {
    }
```

and also those who are completed (downloaded)

```
override fun onLoadCompleted(dataSpec: DataSpec?, dataType: Int, trackType: Int, trackFormat: Format?,
                                 trackSelectionReason: Int, trackSelectionData: Any?, mediaStartTimeMs: Long,
                                 mediaEndTimeMs: Long, elapsedRealtimeMs: Long, loadDurationMs: Long,
                                 bytesLoaded: Long) {
    }
```

but i need the actual one that the player is playing. How could i get that?

Thank you!

**Comment by ojw28** [comment]
I don't really understand the question. A few questions that might help to clarify things:

* Are you playing on-demand DASH streams where each representation is a single segment, or do the DASH manifests define multiple segments (with different URLs) per representation?
* It would be good to pose the question in terms of what you're trying to do and why, from a feature perspective. What are you actually going to do once you know which URLs are being played?

**Comment by jboisjo** [comment]
Once i load initially the playlist, it downloads 3-4 chunks of 6 seconds like this.

```
04-25 09:03:59.371 26081-26081/“packagename” E/onLoadCompleted: …udp_audio_1_10_298385.mp4?m=1523493623
04-25 09:03:59.596 26081-26081/“packagename” E/onLoadCompleted: …udp_video_1_3_298385.mp4?m=1523493623
04-25 09:03:59.624 26081-26081/“packagename” E/onLoadCompleted: …udp_audio_1_10_298386.mp4?m=1523493623
04-25 09:03:59.739 26081-26081/“packagename” E/onLoadCompleted: …udp_video_1_3_298386.mp4?m=1523493623
04-25 09:03:59.765 26081-26081/“packagename” E/onLoadCompleted: …udp_audio_1_10_298387.mp4?m=1523493623
04-25 09:03:59.856 26081-26081/“packagename” E/onLoadCompleted: …udp_video_1_3_298387.mp4?m=1523493623
04-25 09:03:59.880 26081-26081/“packagename” E/onLoadCompleted: …udp_audio_1_10_298388.mp4?m=1523493623
04-25 09:04:00.014 26081-26081/“packagename” E/onLoadCompleted: …udp_video_1_3_298388.mp4?m=1523493623
04-25 09:04:00.040 26081-26081/“packagename” E/onLoadCompleted: …udp_audio_1_10_298389.mp4?m=1523493623
04-25 09:04:00.129 26081-26081/“packagename” E/onLoadCompleted: …udp_video_1_3_298389.mp4?m=1523493623
04-25 09:04:00.156 26081-26081/“packagename” E/onLoadCompleted: …udp_audio_1_10_298390.mp4?m=1523493623
04-25 09:04:00.234 26081-26081/“packagename” E/onLoadCompleted: …udp_video_1_3_298390.mp4?m=1523493623
```

and then, after 20-25 seconds, it gets the other next 3 chunks.

I want to know what chunk is currently display after it has been downloaded. 
We're trying to fix an issue that sometimes, i'm getting a source error and need to know if the player can't find the chunk or the chunk hasn't been created from the source!

Thank you !

**Comment by ojw28** [comment]
I don't understand what the difference between "player can't find" and "hasn't been created" is. Under what circumstances does the chunk exist but the player can't find it?

I'm also confused about why the currently playing chunk is going to help you. If the player is failing it should give you an error that's descriptive enough to allow you to figure out what went wrong. Are you seeing an error, and if so what does the stack trace look like?

**Comment by jboisjo** [comment]
Well maybe the chunk exist but it's corrupt for x reason so the player can't access it. That's what i'm trying to figure.

The error i'm getting it's always a 503 which is the segment doesn't exist but it's pretty random.

**Comment by ojw28** [comment]
If you're seeing 503 errors then you already know what the issue is (i.e. your server providing a "Service Unavailable" response code). If the chunk were corrupt then you'd see a different failure (e.g. in ExoPlayer's `Extractor` or `Renderer` components).
