### ISSUE TITLE
Grab Current Frame 

### ISSUE THREAD

**Issue by Schizo** [google/ExoPlayer#418]
I want to take snapshots of the paused video frame, is it currently possible to somehow access the frame? Or any possible workaround? I could extend the SurfaceView, but maybe there is a better solution, closer to the source pixels.

**Comment by ojw28** [comment]
This isn't something we plan to support any time soon; sorry. Although if you use TextureView, presumably you just have the current frame already in the texture (and can read it back using OpenGL).

**Comment by ptran-gpfw** [comment]
Would drawing to a Canvas work?
I.e.:

    Canvas canvas = new Canvas(bitmap);
    view.draw(canvas);

**Comment by Schizo** [comment]
I've already tried different approaches, but it doesn't seem to be easy to get the texture from a surfaceview. @ptran-gpfw Your suggestion results in a black frame either.

**Comment by Ood-Tsen** [comment]
I think there's a way to grab the frame of video.
1. Use software video decoder.
    The decoded buffer is not accessible while decode by hardware decoder.
2. The format of decoded buffer is YUV (e.q. NV21).
    Need to transform to RGB.

**Comment by ptran-gpfw** [comment]
@Schizo I just noticed TextureView has a few `getBitmap` methods:
http://developer.android.com/reference/android/view/TextureView.html#getBitmap(int,%20int)

**Comment by Schizo** [comment]
@ptran-gpfw But as i reas VideoSurfaceView is different from TextureView and Exoplayer uses a VideoSurfaceView. Did you try to grab a Frame of Exoplayers VideoSurfaceView?

@Ood-Tsen Transformation is not a big deal, i don't know how to grab a Frame.

**Comment by ptran-gpfw** [comment]
Demo code ships with SurfaceView but you can use TextureView, see issue #98 (there are additional links there with nice sample code).

**Comment by AshtonEngberg** [comment]
TextureView has a getBitmap call: however, you might want to verify
playback has occurred (currentPos > 100) otherwise you'll pull a black
square.
