### ISSUE TITLE
Dummy Media Source

### ISSUE THREAD

**Issue by Sybergoth** [google/ExoPlayer#4181]
### Issue description
I am creating a certain audio player which combines a number of tracks to play using exo player.
In the project I have a requirement that there can be a certain "blank" period between tracks.

For example:
Playing track no. 1 and then a 10 second pause and then playing track no. 2

I was wondering if there is any "blank" media source which I can configure with time and it will do nothing so I could concatenate all the tracks (and blanks) into one playback.

Thanks!

### Version of ExoPlayer being used
2.7.3

**Comment by ojw28** [comment]
We don't provide such a component, however it would probably not be too difficult for you to implement one yourself.

**Comment by Sybergoth** [comment]
Hey, thanks for the reply.

Before I dive in to learn how a media source is structured and implement it, do you have any references about how to write a custom media source and how should I tackle this problem?

**Comment by ojw28** [comment]
The Javadoc for the classes/interfaces that you need to implement should be your reference in the first instance.
