### ISSUE TITLE
Backward seek issue with HLS live stream

### ISSUE THREAD

**Issue by jaranflaath** [google/ExoPlayer#4187]
### Issue description
Working on the radio app for Denmark Radio, we discovered an issue with seeking in live HLS stream. We start playing a stream, then jump to about midways into the stream, then start skipping backwards. ExoPlayer will then have trouble skipping more than a second or two, perhaps managing to skip 15 seconds one time, before it gives up and start skipping _forward_ instead - eventually a minute or more for each click on the backward skip button. The issue has been reproduced in the demo app of the ExoPlayer library. 

### Reproduction steps
I have forked the library and modified the demo app to reproduce the issue. The fork is available here: https://github.com/jaranflaath/ExoPlayer/tree/live_stream_seeking_bug 

I have added a new HLS source, "DR Radio". To reproduce the issue, follow these steps:
1. Start the stream "DR Radio" under HLS in the demo app
2. Scrub the progress bar to around 12 minutes
3. Skip forward a few times - works fine
4. Skip backwards, and you will notice the progress is having problems skipping and will eventually start skipping forward in large chunks on up to 1.5 minutes. 

### Link to test content
Sent by email

### Version of ExoPlayer being used
Reproduced in versions 2.7.1->2.7.3. Works fine in 2.7.0

### Device(s) and version(s) of Android being used
Tested on Pixel 2 XL with Android 8.1, as well as emulator running Android 8.1 

### A full bug report captured from the device
Not relevant in this case.

**Comment by AquilesCanta** [comment]
This is indeed a regression. A fix will be provided in the next push.

**Comment by jaranflaath** [comment]
Looking forward to the fix :)
