### ISSUE TITLE
Not played VMAP ima ads with hls list + Subtitles in ExoPlayer2.6.1

### ISSUE THREAD

**Issue by na-in-lee** [google/ExoPlayer#4189]
### Issue description
create hls playlist with subtitles and create adsmediasource.
but can not play ima ads. 
Video and subtitles play well.

### Reproduction steps
in exoplayer 2.6.1 demo-ima

file : PlayerManager.java 
fuction: private void init() 

////// added code

    Uri[] uris= new Uri[2];
    MediaSource[] mediaSources = new MediaSource[2];
    for (int i = 0; i < 2; i++) {

      uris[i] = Uri.parse(uriStrings[i]);
      mediaSources[i] = buildMediaSource(uris[i], null, null);
      if(captionUrl != null) {
        Uri subtitleUri = Uri.parse(captionUrl);
        String mimeType = MimeTypes.APPLICATION_SUBRIP;
        if (captionUrl.endsWith(".vtt") == true)
          mimeType = MimeTypes.TEXT_VTT;

        Format subtitleFormat = Format.createTextSampleFormat(
                "0", // An identifier for the track. May be null.
                mimeType, // The mime type. Must be set correctly.
                Format.NO_VALUE, // Selection flags for the track.
                "kr");

        MediaSource textMediaSource = new SingleSampleMediaSource.Factory(mediaDataSourceFactory).createMediaSource(subtitleUri, subtitleFormat, C.SELECTION_FLAG_AUTOSELECT, null, null);
        mediaSources[i] = new MergingMediaSource(mediaSources[i], textMediaSource);
      }
    }
    MediaSource mediaSource = mediaSources.length == 1 ? mediaSources[0] : new ConcatenatingMediaSource(mediaSources);

    ////// added code end

### Link to test content 
Source:
https://github.com/na-in-lee/exo-player2-custom

### Version of ExoPlayer being used
exoplayer 2.6.1
build config : demo-ima

### Device(s) and version(s) of Android being used
device name : Galaxy S8
android version: 8.1

**Comment by ojw28** [comment]
Are you enabling the text track? If you follow your approach in the demo app, you should see a button that allows selection. Alternatively, if you want it to be selected by default, you can use the following when creating the format for your track:

```
Format subtitleFormat = Format.createTextSampleFormat(
    "0", mimeType, C.SELECTION_FLAG_AUTOSELECT, "kr");
```

Does that help?

**Comment by na-in-lee** [comment]
no..
VAST IMA play well.

VMAP Midroll can not play.



<vmap:VMAP xmlns:vmap="http://www.iab.net/videosuite/vmap" version="1.0">
    <vmap:AdBreak timeOffset="start" breakType="linear" breakId="preroll">
        <vmap:AdSource id="preroll-ad" allowMultipleAds="false" followRedirects="true">
            <vmap:AdTagURI templateType="vast3"><![CDATA[https://video-dev.netinsight.co.kr/NetInsight/vast/jtbc/vod/vod@vod?s.name=jtbc&d.os=WINDOWS&c.livestream=0&c.x.section=003&c.x.channel=J01&c.x.clip=J01_VO1013655&c.x.program=J01_PR10010189&c.len=120&d.devicetype=2&d.ifa=]]></vmap:AdTagURI>
        </vmap:AdSource>
    </vmap:AdBreak>
    <vmap:AdBreak timeOffset="00:00:34" breakType="linear" breakId="midroll">
        <vmap:AdSource id="ad" allowMultipleAds="false" followRedirects="true">
            <vmap:AdTagURI templateType="vast3"><![CDATA[https://video-dev.netinsight.co.kr/NetInsight/vast/jtbc/vod/vod@vod?s.name=jtbc&d.os=WINDOWS&c.livestream=0&c.x.section=003&c.x.channel=J01&c.x.clip=J01_VO1013655&c.x.program=J01_PR10010189&c.len=120&d.devicetype=2&d.ifa=]]></vmap:AdTagURI>
        </vmap:AdSource>
    </vmap:AdBreak>
    <vmap:AdBreak timeOffset="00:01:00" breakType="linear" breakId="midroll">
        <vmap:AdSource id="ad" allowMultipleAds="false" followRedirects="true">
            <vmap:AdTagURI templateType="vast3"><![CDATA[https://video-dev.netinsight.co.kr/NetInsight/vast/jtbc/vod/vod@vod?s.name=jtbc&d.os=WINDOWS&c.livestream=0&c.x.section=003&c.x.channel=J01&c.x.clip=J01_VO1013655&c.x.program=J01_PR10010189&c.len=120&d.devicetype=2&d.ifa=]]></vmap:AdTagURI>
        </vmap:AdSource>
    </vmap:AdBreak>
</vmap:VMAP>

**Comment by ojw28** [comment]
Does this have anything to do with subtitles, or does the issue occur regardless or whether they're added or not? Please provide a clear description of the problem. Thanks!

**Comment by na-in-lee** [comment]
Thank you for your answer.

Look at the source below.
 - https://github.com/na-in-lee/exo-player2-custom

Put ima ads on the source, it will not play. (Actually FATAL EXCEPTION)
Except for the ad, the video and subtitles come out well.

**Comment by andrewlewis** [comment]
Based on the [added code in PlayerManager](https://github.com/na-in-lee/exo-player2-custom/blob/master/demos/ima/src/main/java/com/google/android/exoplayer2/imademo/PlayerManager.java#L101), it looks like you're trying to insert ads with a content media source that's a concatenation. This is not supported at the moment. Adding support is tracked by #3693.

For now, you could try working around this limitation by playing just the first item in the concatenation with ads, then, when it finishes, prepare the player with the second item.
