### ISSUE TITLE
[Question] Caching audio file from HTTP datasource

### ISSUE THREAD

**Issue by laminsk** [google/ExoPlayer#419]
Hi,

I'm not an experience android developer, so please bear with me. Currently using Mediaplayer and custom http proxy for my project to read audio files from webserver and stream it back to the player. Basically I just want to save the buffered/cached data to internal storage.

I'm now switching to Exoplayer and trying to do the same without using http proxy. Tried searching Stackoverflow and gone through open/closed issues, but I couldn't find whether it's possible to achieve the same thing by using caching functionality provided by Exoplayer.

Any pointers would be greatly appreciated.

Thanks.

**Comment by ojw28** [comment]
This use case isn't supported yet. It's tracked by #420.
