### ISSUE TITLE
Can ExoPlayer support 360 DASH video? 

### ISSUE THREAD

**Issue by ChangSurrey** [google/ExoPlayer#4190]
I can see there is a GVR extension but it seems to be about spatial audio rather than video support? 

Also when I tried to stream a 360 video using the demo application, it didn't recognise its 360 format and just played it as is. 

Is there any way to tell the demo app whether a video is 360 or not?

**Comment by ojw28** [comment]
@erdemguven is working on this.

**Comment by ChangSurrey** [comment]
Thanks @ojw28 , so are you implying it is currently not supported? 

@erdemguven can I ask what's the rough timeline that you're planning for this feature?

**Comment by ojw28** [comment]
I think it's probably possible using [`VrVideoView`](https://developers.google.com/vr/reference/android/com/google/vr/sdk/widgets/video/VrVideoView) in the GVR SDK, which wraps a customized ExoPlayer instance. If that's sufficient for your needs, then great.

A shortcoming with that approach is that you can't probably control the ExoPlayer instance. What we'd rather have is a view component that you can call `setPlayer` on (like ExoPlayer's standard 2D `PlayerView), so you don't lose any control over the player instance.

**Comment by erdemguven** [comment]
It's probably best to use VrVideoView for now. We might improve it so you can configure the player or create our own widget which is similar to VrVideoView so you can switch to our widget when it's ready.

**Comment by erdemguven** [comment]
With ExoPlayer 2.9.0 a new surface type is added to PlayerView: spherical_view. This new surface type allows users to view 360º videos without a VR headset.
https://medium.com/google-exoplayer/playing-360-degree-videos-with-exoplayer-f3b48f8ea390

**Comment by ghost** [comment]
@erdemguven is it possible to make `spherical_view` programmatically or it's only possible in XML?
