### ISSUE TITLE
Text Track not available in track info

### ISSUE THREAD

**Issue by ghost** [google/ExoPlayer#4191]
I recently upgraded to 2.7.3, from 2.6.1, and noticed that setting a track override seems to have changed.  I was able to accomplish this on 2.6.1 using the following code to enable the text track, CEA-608 in TS:

```kotlin
val mapping = contentTrackSelector.currentMappedTrackInfo
        if (mapping != null) {
            val rendererIndex = (0 until mapping.length).firstOrNull { player.getRendererType(it) == C.TRACK_TYPE_TEXT }
            rendererIndex ?: return
            val trackGroups = mapping.getTrackGroups(rendererIndex)
            if (trackGroups.length > 0) {
                if (enable) {
                    //We currently only support a single text so it will always be the first group and track available to the text renderer
                    contentTrackSelector.setSelectionOverride(
                        rendererIndex,
                        trackGroups,
                        MappingTrackSelector.SelectionOverride(FIXED_TRACK_FACTORY, 0, 0)
                    )
                } else {
                    contentTrackSelector.clearSelectionOverride(rendererIndex, trackGroups)
                }
            }
        }
```

When looking at the track info, I noticed that it only shows video and audio tracks available.  I decided to load it up in the  Exoplayer demo project and when looking at the exact same stream, it shows a cea-608 track is available.  I have no way of providing a stream as short lived tokens are generated for the master playlist and have not control over it.

I'm genuinely confused as to what about this functionality has changed and how to update my code to use it correctly. 

Player initialization code:
```kotlin
    private val contentBandwidthMeter = DefaultBandwidthMeter()
    private val contentVideoTrackSelectionFactory = AdaptiveTrackSelection.Factory(contentBandwidthMeter)
    private val contentTrackSelector = DefaultTrackSelector(contentVideoTrackSelectionFactory)

    val player = ExoPlayerFactory.newSimpleInstance(ctx, contentTrackSelector)
```

**Comment by ojw28** [comment]
To clarify, are you saying that:

* You can successfully select the text track in the ExoPlayer demo app, both in 2.6.1 and 2.7.3
* In your app specifically, the override logic you have isn't working for 2.7.3

If so, that sounds strange. Can you hook up an `EventLogger` in your app (see `PlayerActivity` in the demo app for an example of what to register it to), and share what it outputs to logcat for a sample playback?

**Comment by ghost** [comment]
I seem to have found the culprit, myself.  I called `setAllowChunklessPreparation(true)` and clearly I didn't read the documentation enough to realize that captions need to be declared in the master playlist and id3 is not supported.

[Reference](https://medium.com/google-exoplayer/faster-hls-preparation-f6611aa15ea6) for future users

**Comment by AquilesCanta** [comment]
Good news is that ID3 in chunkless preparation is going to be made available in the dev branch in the next push. Closed caption should still be declared by the master playlist.
