### ISSUE TITLE
Issue playing a HLS stream

### ISSUE THREAD

**Issue by joshdvir** [google/ExoPlayer#4194]
Hi,

I found a weird issue might be a bug in the HLS.

### Issue description
I have a stream that I'm recording using the Nimble server and when I use the stream HLS endpoint directly it works, the stream is played no problem, but when I used the recording stream, it also produces a HLS file the stream is not been played.

### Reproduction steps
I managed to reproduce it using the demo application by adding:
```
{
        "name": "Nimble stream direct",
        "uri": "https://kt.syncil.live/l/glglz/playlist.m3u8"
      },
      {
        "name": "Nimble stream DVR",
        "uri": "https://kt.syncil.live/l/glglz/playlist_dvr_timeshift-7200.m3u8"
      },
```

to the media.exolist.json file in the HLS section, the direct link is working no problem and the dvr one is not working.

### Version of ExoPlayer being used
Specify the absolute version number. Avoid using terms such as "latest".

### Device(s) and version(s) of Android being used
I'm using the emulator version Oreo 8.1

### A full bug report captured from the device
```
04-30 20:21:44.146 10984-10984/com.google.android.exoplayer2.demo E/EventLogger: internalError [11.59, loadError]
    com.google.android.exoplayer2.ParserException: Cannot find sync byte. Most likely not a Transport Stream.
        at com.google.android.exoplayer2.extractor.ts.TsExtractor.read(TsExtractor.java:256)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.loadMedia(HlsMediaChunk.java:285)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.load(HlsMediaChunk.java:219)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:308)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
```

Thank you for your help.

**Comment by AquilesCanta** [comment]
For HLS segment playback, ExoPlayer selects the Extractor by file extension. The original segments are mp3 files, whereas the recorded ones are saved with ts extension, therefore the message `Cannot find sync byte. Most likely not a Transport Stream.` You can either configure the recording software to use the original file extension, or implement your own HlsExtractorFactory, to choose the used extractor manually.

**Comment by DeveloperMCD** [comment]
"For HLS segment playback, ExoPlayer selects the Extractor by file extension. The original segments are mp3 files, whereas the recorded ones are saved with ts extension, therefore the message Cannot find sync byte. Most likely not a Transport Stream. You can either configure the recording software to use the original file extension, or implement your own HlsExtractorFactory, to choose the used extractor manually."

I'm having a difficult time figuring out how to do this. Are there any code samples, examples, or documentation out there that can be easily followed? Thank you,

Matthew

**Comment by DeveloperMCD** [comment]
I tried modifying the .m3u8 to contain .mp4 fragments instead of a bunch of .ts files, but then I get a different error:

com.yusufcakmak.exoplayersample E/ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.ParserException: Skipping atom with length > 2147483647 (unsupported).
        at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.readAtomHeader(FragmentedMp4Extractor.java:411)

It is trying to play them as unencrypted Mp4s, even though they are actually AES encrypted?

**Comment by AquilesCanta** [comment]
Hi @DeveloperMCD, please file a new issue including all information requested in the issue template. 3 lines of logcat are rarely enough to diagnose an issue. Thanks!
