### ISSUE TITLE
[Question] Parsing ID3 timestamp and exposing to application

### ISSUE THREAD

**Issue by ldelossa** [google/ExoPlayer#4195]
Hello,

I'm attempting to create a software clock in an android device which needs to display the timestamp from metadata within the ID3 tag. We need a way to parse hls segments and the ID3 information which holds the source timestamp and then make this data available to some class responsible for displaying an on screen clock. 

Is this functionality available to me? I do not mind digging into the source to determine how to go about it, but would like some advice to make sure what I'm attempting is feasible.

**Comment by AquilesCanta** [comment]
If your player has a metadata renderer, and the ID3 track is selected (in general, the default track selector does it by default, but you should check), then you can get the id3 data from all metadata outputs you've set. This is showcased in the demo app. If you play the HLS stream titled "Apple 16x9 basic stream", you will get logcat output similar to the following, which is a representation of an ID3 TXXX frame.  

```
com.google.android.exoplayer2.demo D/EventLogger: metadata [5.13, 0.00, window=0, period=0, 
com.google.android.exoplayer2.demo D/EventLogger:   TXXX: value= *** THIS IS Timed MetaData @ -- 00:00:00.0 *** 
com.google.android.exoplayer2.demo D/EventLogger: ]
```
