### ISSUE TITLE
After LG G5 security update, WV secure DASH video only plays half screen (half screen black)

### ISSUE THREAD

**Issue by stellabei** [google/ExoPlayer#4198]
### Issue description
After LG G5 security patch February 1, 2018, when try to play a secure WV Dash content (SD or HD), the play screen is covered by a half screen black stripe. It only happens with secure content, non-secure video works.

### Reproduction steps
1. Have a LG G5 with February 1 security update
2. Play any secure Dash content in the Exoplayer demo app
3. Right after it starts the play, a half screen sized black strip covers from top to end in the screen "covers" half of the screen (sent to exoplayer dev email).

### Link to test content
You can use any secure Dash content in the Exoplayer demo app with the LG G5 security update and you can reproduce this problem.

### Version of ExoPlayer being used
Exoplayer 2.5.1

### Device(s) and version(s) of Android being used
Test Device: LG G5 LGUS992
Android OS: 7.0
Software version: US99226c
Kernel version: 3.18.31
security patch February 1, 2018

### A full bug report captured from the device
I will send the bug report to to dev.exoplayer@gmail.com using a subject in the format "Issue #4198".

**Comment by ojw28** [comment]
@wvpaf - Please could you follow up with LG about this? Thanks!

**Comment by paf-wv** [comment]
I have reached out to our LG contacts, but I am not sure how successful we will be, but we will try.

**Comment by stellabei** [comment]
@paf-wv @wvpaf 
This problem is actually more serious than just a "cosmetic" black tag. If you let it play for a while/rotates it exits the player, sometimes the phone reboots. Clearly is causing a crash in the linux level as well. Please let LG contacts know.

**Comment by ojw28** [comment]
@paf-wv - Any update from LG? Thanks.

**Comment by paf-wv** [comment]
Unfortunately, no updates.

**Comment by stellabei** [comment]
@paf-wv frequently when manufacturers upgrade to a new OS version, they got some kind of DRM problem. This LG G5 is one example, there was also a Motorola Droid Turbo 2 [https://github.com/google/ExoPlayer/issues/2648](url). Is there anything that can be done to improve this process? I know it is hard to manage communication with all the manufacturers, but maybe some kind of certification test need to be performed in order to give a "green" light to the upgrade?

For now, I'm using the work around to force it into L3.

**Comment by paf-wv** [comment]
@stellabei 
Understand about the OEM updates causing issues.
There is a suite of tests that they must pass however, with an open sourced platform things are not always in our control.

**Comment by paf-wv** [comment]
Unfortunately, LG acknowledged the regression and state the device is end of life but they are revisiting to determine if they can produce an MR.  Will update if that happens.

**Comment by paf-wv** [comment]
still waiting on device manufacturer.

**Comment by paf-wv** [comment]
Looks like LG is producing a patch for later in the year. Details on the release are vague at best. Sorry but at least there is a potential fix coming.

**Comment by stellabei** [comment]
Thanks @paf-wv for notifying!

**Comment by paf-wv** [comment]
Hello,
Thank you for your patience. LG has confirmed there is a new build and should be deployed soon to the end users.  Unfortunately there are no hard dates to report.
