### ISSUE TITLE
Dash encoding question

### ISSUE THREAD

**Issue by kanthicn1** [google/ExoPlayer#4199]
I searched on all questions and couldn't find this question definitively answered although it is discussed [here]([https://github.com/google/ExoPlayer/issues/605]).

Does ExoPlayer support playing streams self-initialized dash segments (which are segments which don't contain an initialization segment but, the encoder has added all related encoding information in each segment)?

**Comment by ojw28** [comment]
Do you mean using avc3 rather than avc1? I'm fairly sure at least one major provider uses avc3 with ExoPlayer, and so I'm confident we do support that. However the best way to check would be to transcode a sample stream and test it, since the devil is in the detail.

**Comment by ojw28** [comment]
I'm pretty sure we also support avc1 where the moov is placed at the start of each segment, rather than in an initialization segment. But as above, give it a try and see!
