### ISSUE TITLE
what protection or security DownloadManager use ?

### ISSUE THREAD

**Issue by ZohaibGhafoor** [google/ExoPlayer#4201]
Does ExoPlayer use any encryption for Progressive or Adaptive downloads. or the content can be play by any other parties or can i play downloaded content with other player? if not can we use any encryption method to secure content. Please explain me anyone.

**Comment by AquilesCanta** [comment]
> Does ExoPlayer use any encryption for Progressive or Adaptive downloads

ExoPlayer [supports](https://google.github.io/ExoPlayer/supported-formats.html) a number of DRM methods.

> the content can be play by any other parties or can i play downloaded content with other player?

Depends on the protection scheme. Some schemes are more secure than others. This depends on how hard it is to access the keys used to decrypt the content. The demo app has samples with widevine and playready protection. ExoPlayer also supports AES full segment encryption. Let me know if you have any specific questions.

**Comment by ZohaibGhafoor** [comment]
how can i use widevine and playready protection on my content please can you guide me step by step . Is it free or a paid service? or if you can share any complete guide link on from start to end tutorial from getting widevine and playready encryption key etc.

**Comment by AquilesCanta** [comment]
I think I misunderstood the initial question. There is some useful information [here](https://medium.com/google-exoplayer/downloading-streams-6d259eec7f95) but I am not sure it covers encrpytion. @erdemguven will be able to help better than I.

**Comment by AquilesCanta** [comment]
I deleted my first reply as it was more misleading than anything else.

**Comment by andrewlewis** [comment]
If you are trying to have the cached data be stored encrypted, you could try using [AesCipherDataSource](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/upstream/crypto/AesCipherDataSource.java) and [AesCipherDataSink](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/upstream/crypto/AesCipherDataSink.java) as the cache read/write data source/sink when you create your [SimpleCache](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/upstream/cache/CacheDataSource.java#L164). If that's not what you're trying to do please clarify.
