### ISSUE TITLE
How can i detect audio stream if track is already playing?

### ISSUE THREAD

**Issue by akhorevich** [google/ExoPlayer#4203]
I have in Activity an Exoplayer, and when I reopened it - the track is already playing. How can I detect it and continue current track? I tried to use exoPlayer.getCurrentWindowIndex()

`@Override
        public void onTracksChanged(TrackGroupArray trackGroups, TrackSelectionArray trackSelections) {
            Log.i(TAG,"onTracksChanged");
            Toast.makeText(PageActivity.this, "onTracksChanged", Toast.LENGTH_SHORT).show();
            int latestWindowIndex = exoPlayer.getCurrentWindowIndex();
            if (latestWindowIndex != lastWindowIndex) {
                // item selected in playlist has changed, handle here
                lastWindowIndex = latestWindowIndex;
            }
        }`

Thanks!

**Comment by linhai326** [comment]
onTracksChanged will give you trackSelections. And you can iterate this TrackSelectionArray  and find audio track using format.sampleMimeType.

**Comment by ojw28** [comment]
Please could you clarify exactly what the question is. Are you trying to resume playback from the position where you left off (i.e. trying to restore the position of the player) or are you trying to ensure the same tracks are selected (i.e. if there are multiple audio tracks and the user has selected one in a particular language, restoring that)?

Please also take a look at `PlayerActivity` in the main demo app, which may answer your question.

**Comment by akhorevich** [comment]
I create a demostrating video
https://drive.google.com/open?id=1CvRvdyZ5NXITFWZbc7ZU8HF-8SH0axZT

**Comment by ojw28** [comment]
Sorry, the issue is still not clear from the video.

**Comment by akhorevich** [comment]
I need to continue an audio track when I reopened an activity if it already was started earlier.

1. I open activity with player and click Play button

2. I go back to previous activity (track is already playing)

3. When I opening again activity with ExoPlayer - I want to detect playing track and continue it in Seekbar and etc.

Sorry, English isn't my native language

**Comment by ojw28** [comment]
Between step 2 and 3, is playback still happening, or not? If it is still happening then you must still have an `ExoPlayer` instance somewhere. When re-entering the activity you'd just need to bind your UI to that existing player instance.

**Comment by akhorevich** [comment]
Yes, its already playing between step and 3. Maybe I need to do ExoPlayer like a Singelton or something like it to have access from every activity without re-createating ExoPlayer?

**Comment by ojw28** [comment]
Yes, exactly that! If you're also intending to allow background playback, you should probably also have an Android Service, if you don't have one already.
