### ISSUE TITLE
Just buffer one track in exo audio source list

### ISSUE THREAD

**Issue by sn32247** [google/ExoPlayer#4208]
I add multiple tracks to exo audio source but I want to buffer just the track that is playing. How can I do this?

**Comment by ojw28** [comment]
Please provide your question in more detail. "I add multiple tracks to exo audio source" is not a detailed enough description for us to understand what you're doing.

**Comment by sn32247** [comment]
I pass list of audios to exo but when exo play an audio it buffers current track plus next track. but I don't want buffer next track. how can I control this?

**Comment by ojw28** [comment]
I think you should just not pass the player the next track if you don't want it to be buffered.
