### ISSUE TITLE
Seeking accurately with mp3 files

### ISSUE THREAD

**Issue by lonelyowlz** [google/ExoPlayer#4209]
Hi, I currently writing an mp3 player app. No streaming just playing the local storage files. I want to be able to seek accurately. From the documentation and from some of the issues, I learned that mp3 does not support exact seeking. I cannot force the users to convert their mp3 library to mp4. So, I am looking for another solution. On this issue:

https://github.com/google/ExoPlayer/issues/3233
 
@ojw28 said that it is theoretically possible to seek accurately in mp3 files. In the worst case the player could just download the whole stream, parse it and build its own sample accurate time to byte-offset index. 

How do I accomplish this? I do not care about streaming / podcasts, I just want to play the local files with exact seeking.

Thank you.

**Comment by ojw28** [comment]
> How do I accomplish this?

This is just not something we support, sorry. Is the existing best-effort support actually not good enough for your application?

**Comment by lonelyowlz** [comment]
Hi ojw28 and thanks for the reply. Can you point me in the right direction to developing your theoretical idea?

By best-effort support do you mean using the default ExtractorMediaSource which internally uses the MP3Extractor?

**Comment by ojw28** [comment]
> By best-effort support do you mean using the default ExtractorMediaSource which internally uses the MP3Extractor?

Correct.

> Can you point me in the right direction to developing your theoretical idea?

You'd probably need to modify (or modify a fork of) `Mp3Extractor` to consume the whole stream up front, build an accurate `SeekMap` from the data, output that, start reading back from the start of the stream again, and from that point operate as normal. We're not able to provide more detailed guidance than this, since this is not something we support. Good luck!
