### ISSUE TITLE
ExoPlayer Demo Process being killed automatically when playing a track in the background.

### ISSUE THREAD

**Issue by jjvargas** [google/ExoPlayer#421]
WindowState﹕ WIN DEATH: Window{42b8ed90 u0 com.google.android.exoplayer.demo/com.google.android.exoplayer.demo.PlayerActivity}

When playing an HLS audio track and selecting the option of "Play in Background" then clicking the home button, the music keeps playing but If I start opening other applications there is a point where it looks like the OS is killing the ExoPlayer Demo app automatically. I guess this is because of the Background Process Limit by the OS

In case we want to avoid this ,Do we need to use a Service for the player to keep playing in the background ? Any hints on this?

**Comment by ojw28** [comment]
In a real application you would want a (foreground) service to prevent process death, yes. We're trying to make the demo app simpler though, not more complicated, so we're unlikely to be doing this within the demo.

**Comment by saurabhkpatel** [comment]
When do you have the plan to create a demo with foreground service?
I am working on the same thing as like above, I have one small quick question, I have to create exoplayer instance in foreground service?
