### ISSUE TITLE
Bad buffering on old devices

### ISSUE THREAD

**Issue by marinica94** [google/ExoPlayer#422]
Hi ! First I want to thank you for your last reply to my question, I have solved the problem. Today I have tested my application on Samsung Galaxy S2 that is pretty old, untill now tested succesfully only on LG G3 and S4 mini, both of them runned the player list good. After testing on S2 I have noticed that on the start of file it's get stuck repeating some parts of the music untill get's buffer I think.

I will post some parts of my code:

        exoPlayer = ExoPlayer.Factory.newInstance(1);
        playerControl = new PlayerControl(exoPlayer);
        exoPlayer.setPlayWhenReady(true);

And on my list of music I use this:

                        exoPlayer.stop();
                        exoPlayer.seekTo(0);
                        sampleSource = new DefaultSampleSource(new FrameworkSampleExtractor(getApplicationContext(), uri, null), 1);
                        audioRenderer = new MediaCodecAudioTrackRenderer(sampleSource, null, true);
                        exoPlayer.prepare(audioRenderer);

Also I don't know why my listener is not working, my class implements ExoPlayer.Listener and on my method I try to play next song when current song ends:

    @Override
    public void onPlayerStateChanged(boolean playWhenReady, int playbackState) {

        if(playbackState == ExoPlayer.STATE_ENDED){
            Log.i("TEST","Finishing playback");
            URL = musicUrl.get(currentPosition+1);
            Uri uri = Uri.parse(URL);

            exoPlayer.stop();
            exoPlayer.seekTo(0);
            sampleSource = new DefaultSampleSource(new FrameworkSampleExtractor(getApplicationContext(), uri, null), 1);
            audioRenderer = new MediaCodecAudioTrackRenderer(sampleSource, null, true);
            exoPlayer.prepare(audioRenderer);
        }
    }

Thank you for the time and answers, this is the only source we can find about exoPlayer !

**Comment by ojw28** [comment]
If you're playing MP3 files then you should use Mp3Extractor on the dev branch. It's going to be a lot more reliable across all devices than anything that uses FrameworkSampleExtractor.

**Comment by marinica94** [comment]
What is the better way to achieve that ? Can you provide me an example ?

**Comment by ojw28** [comment]
The demo app demonstrates this (the sample has type TYPE_MP3). You'll need to prepare the player something like:

```
// Build the video and audio renderers.
DataSource dataSource = new DefaultUriDataSource(userAgent, null);
Mp3Extractor extractor = new Mp3Extractor();
ExtractorSampleSource sampleSource =
    new ExtractorSampleSource(uri, dataSource, extractor, 1, BUFFER_SIZE);
MediaCodecAudioTrackRenderer audioRenderer =
    new MediaCodecAudioTrackRenderer(sampleSource, null, true);
exoPlayer.prepare(audioRenderer);
```
