### ISSUE TITLE
Transport stream playback failure

### ISSUE THREAD

**Issue by garethfenn** [google/ExoPlayer#4224]
### Issue description
Exoplayer fails to playback TS stream captured from UK terrestrial feed. The stream itself was captured by enabling a debug record option in the Google LiveTV app; a single track in a TS container. Other players are able to cope OK.

### Reproduction steps
adb shell am start -a com.google.android.exoplayer.demo.action.VIEW -d http://.../17540_1525450653159_2926.ts

### Link to test content
Sent to dev.exoplayer@gmail.com

### Version of ExoPlayer being used
r2.7.3
4b531dcc5211ef9cb1c2adea5c12642f549c4c78

### Device(s) and version(s) of Android being used
Android TV (720p) API O (Virtual Device)
Broadcom Cypress reference platform, Oreo 8.1

### A full bug report captured from the device
Sent to dev.exoplayer@gmail.com

**Comment by tonihei** [comment]
I'm able to reproduce your problem. Our TsExtractor loops forever trying to find a payload reader. @AquilesCanta can you take a look?

**Comment by garethfenn** [comment]
Thanks. Looking into the TsExtractor, I was able to play back the stream by skipping over the second audio PID (6606) esinfo in the PMT. Unfortunately Google LiveTV only captures the one audio PID and doesn't modify the PMT accordingly. I'm not sure how this works for ATSC...

Are there any plans to support TS streams such as this?

**Comment by garethfenn** [comment]
A correction to the previous comment: Google Live TV app **does** record all audio tracks. In this case, the secondary audio track is audio description that is not always present (>20% of BBC content has AD) . I've recorded streams where it's mute but still getting some packets, and other times where there's nothing at all. (As was the case in the stream provided)

This behaviour appears to prevent Google LiveTV app from playing back UK Terrestrial broadcast.

**Comment by garethfenn** [comment]
After some investigation, it would appear that Exoplayer waits indefinitely in the prepare state until it receives at least one sample for each track referenced in the PMT. I've added a hack to progress from prepare after a timeout with a subset of all PMT referenced tracks which works well. But if the AD track only becomes active after prepare, it's never available for selection.

**Comment by AquilesCanta** [comment]
If the PMT references a track that has no PES packets, then the stream will get stuck in preparation. This is not something we plan to support as it's currently considered to be bad media. The best way to work around it is probably forking the extractor to give up waiting after some time (usually TV standards set some maximum packet interval, so that should help).
