### ISSUE TITLE
Sound button

### ISSUE THREAD

**Issue by prilaga** [google/ExoPlayer#4229]
Please add the sound on/off button to the player.
I can't find this UI element on `R.layout.exo_playback_control_view`
Thanks.

**Comment by tonihei** [comment]
We are currently not planning to add such a button to our UI. However, you can provide your own control view by providing a exo_player_control_view.xml as explained [here](http://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/ui/PlayerControlView.html). In there you can an extra element for toggling audio on and off. 
Note that we also recently added a [TrackSelectionView](http://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/ui/TrackSelectionView.html) to our UI module which allows you to choose the video and/or audio track.
