### ISSUE TITLE
ExoPlayer doesn't follow http->https / https->http redirects

### ISSUE THREAD

**Issue by Ood-Tsen** [google/ExoPlayer#423]
In the latest dev branch, I cannot play some dash links.

It seems the Default Http DataSource does not handle http redirect (http status code 301).

The log is as follows:
>E/EventLogger(20003): com.google.android.exoplayer.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 301
E/EventLogger(20003): 	at com.google.android.exoplayer.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:168)
E/EventLogger(20003): 	at com.google.android.exoplayer.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:94)
E/EventLogger(20003): 	at com.google.android.exoplayer.upstream.DataSourceInputStream.open(DataSourceInputStream.java:56)
E/EventLogger(20003): 	at com.google.android.exoplayer.upstream.UriLoadable.load(UriLoadable.java:92)
E/EventLogger(20003): 	at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:241)

**Comment by ojw28** [comment]
Hmm. Do they work on master? Are you sure that there isn't a redirect loop (which would cause this to occur after some limit on the number of redirects is reached)?

**Comment by Ood-Tsen** [comment]
Only redirect once.
It redirects from http to https.
This is the test link:
> http://www.test.com/D2-Service/D2-SB/D2-US/dash.mpd

**Comment by ojw28** [comment]
HttpURLConnection doesn't follow redirects that change the protocol. See (here)[http://developer.android.com/reference/java/net/HttpURLConnection.html], in particular: "This implementation doesn't follow redirects from HTTPS to HTTP or vice versa."

Whether we should follow them ourselves is an open question.

**Comment by ojw28** [comment]
Note that this is currently breaking the "Dizzy (https->http redirect)" sample in the ExoPlayer demo app.

**Comment by ojw28** [comment]
This is now supported, but you have to turn it on explicitly when creating a HttpDataSource or UriDataSource (there are new constructors that have an allowCrossDomainRedirects argument).

**Comment by TheCoinTosser** [comment]
I've created a StackOverflow post asking how exactly can I add that flag using an ExtractorMediaSource: http://stackoverflow.com/questions/41517440/exoplayer2-how-can-i-make-a-http-301-redirect-work

Could any of you please help me?
