### ISSUE TITLE
Add custom IMA ad cue points

### ISSUE THREAD

**Issue by khat33b** [google/ExoPlayer#4232]
Right now, the IMA extension only takes cue points from the VAST URL. A method should be added in the extension which allows developers to add custom cue points and show the same ad from the URL at user defined positions.

**Comment by andrewlewis** [comment]
It's possible to specify cue points and ad media yourself by implementing a custom `AdsLoader`, but the code in `ImaAdsLoader` expects ads loaded by IMA to be the only ads in the player timeline.

**Comment by khat33b** [comment]
It's possible to write a custom `AdsLoader ` but that would negate the whole point of using the IMA extension.

**Comment by andrewlewis** [comment]
Wouldn't it make more sense to add these cue points to the ad tag? It is possible to create an `ImaAdsLoader` using an ad tag provided by your app as a string using `ImaAdsLoader.Builder.buildForAdsResponse`, so perhaps you could try downloading the ad tag, inserting your extra ads and passing the result to that method.
