### ISSUE TITLE
How to pass custom data to DownloadService Notification?

### ISSUE THREAD

**Issue by ZohaibGhafoor** [google/ExoPlayer#4233]
how to pass title text or bigimage custom data from activity or fragment to DownloadManager / DownloadService to show in Notification ?

**Comment by erdemguven** [comment]
DownloadService/Manager doesn't create a notification itself. You need to create a subclass of DownloadService and implement the getForegroundNotification method. From that method you can return any notification you want to be showed. 

Please look at 
https://github.com/google/ExoPlayer/blob/release-v2/demos/main/src/main/java/com/google/android/exoplayer2/demo/DemoDownloadService.java#L53
as an example. 

Also read:
https://medium.com/google-exoplayer/downloading-streams-6d259eec7f95
