### ISSUE TITLE
Repackaging of PlayerNotificationManager

### ISSUE THREAD

**Issue by sergejsha** [google/ExoPlayer#4235]
Currently `PlayerNotificationManager` is packaged as a part of `core-ui` module. The fact is that `PlayerNotificationManager` is used inside a media service implementation, which is not a ui-module by its nature and which does not use any other `core-ui` classes either. Current packaging forces me to include whole player UI into my service library module, although only `PlayerNotificationManager` class is used from there.

I quickly checked `PlayerNotificationManager` implementation and it appears to have no dependency on UI classes at all. Does it make sense to move `PlayerNotificationManager` into a separate module? This could be an extension module or `player-service` or similar. What do you think?

**Comment by ojw28** [comment]
It's in the UI module because it uses drawables and strings that are part of the UI module.

**Comment by sergejsha** [comment]
Ah, you are right. How about restructuring it a bit, allowing separate usage of remote/service UI? Simplest option would be `exoplayer-ui -> exoplayer-service-ui`. Current users of `exoplayer-ui` won't see any difference. At the same time audio players with own UI could reference just `exoplayer-service-ui` module. I could also prepare a merge request for it if you would trust it.

**Comment by ojw28** [comment]
Your suggestion would work on a technical level, but it seems a little arbitrary in that it's optimal only for apps using the particular set of UI components that you're using. I could imagine someone else reporting an issue saying they're using only `PlaybackControlView`, and complaining that they have a transient dependency on `exoplayer-service-ui` that contains a class they don't need :).

I don't think we're going to change anything here. I would expect that proguard and resource shrinking should (or could) be used to remove anything that you're not actually using, so it's unclear whether there's actually any impact on end users.
