### ISSUE TITLE
Provide Kotlin versions of the demo apps

### ISSUE THREAD

**Issue by touseefbsb** [google/ExoPlayer#4237]
I am not sure whether this is the best kind of question to ask, but I am actually very new to android development but with this io18 conference I am sure of 1 thing that **kotlin and jetpack** are the future of android development, and they seem really powerful and exciting. I checked the io18 branch with the demos and those apps seem to be in **java**, ofcourse there are still more than 50 percent developers who develop android in java, but can we have kotlin samples as well?  would be a great starting point for all kotlin developers. Thankyou. I also had a look at the full demo apps, they also seem to be only in java.

**Comment by tonihei** [comment]
That's certainly something we should look into. Marked as an enhancement until we have some viable Kotlin demo.

**Comment by touseefbsb** [comment]
@tonihei  thankyou I appreciate it :)

**Comment by andrewlewis** [comment]
@touseefbsb https://github.com/google/ExoPlayer/pull/4257 has Kotlin versions of the io18 demo apps.

**Comment by touseefbsb** [comment]
@andrewlewis  thanks a lot, will have a look at them, but I still think all samples of exo player , being also in kotlin would be very useful. :)

**Comment by touseefbsb** [comment]
any update on its progress? @andrewlewis

**Comment by andrewlewis** [comment]
No updates on this, I'm afraid. We're not currently planning to translate the other demo apps to Kotlin in the short term.

**Comment by ojw28** [comment]
I thought Android Studio could automatically translate apps into Kotlin (although perhaps not in an optimal way).

**Comment by tonihei** [comment]
Superseded by #5854.
