### ISSUE TITLE
Live HLS stream buffers from incorrect start time

### ISSUE THREAD

**Issue by karyogamy** [google/ExoPlayer#4239]
### Issue description

Hi, I've just updated ExoPlayer from 2.7.3 to 2.8.0 and discovered some live hls streams cause the player to constantly buffer and never start playback. Specifically, live hls streams that have duration of a couple minutes or longer. 

When playing these streams, the player seems to load the stream from the start rather than the live edge or the current seek position. Perhaps this causes the playback to stall until the stream is completely buffered up to the seek position, since when I seek to position 0, the playback starts, albeit with older content. 

I suspect this might have something to do [this commit](https://github.com/google/ExoPlayer/commit/d412dc97dcf7b7e4789fb30520a439394bc15dd5), as when the change is reverted, the buffering problem is resolved. 

### Reproduction steps

- Replace the HLS sample stream url in `DemoUtil` under `demo-cast` with the link below. 
- Switch between dev r2.7.3 and r2.8.0 branches and try to play the changed stream on both.

The playback on r2.7.3 should start quickly while other will take a while, or not at all if impatient. 

### Link to test content

http://adultswim-vodlive.cdn.turner.com/off-the-air/stream.m3u8

or any live hls stream with sufficiently long (>5min) duration.

### Version of ExoPlayer being used

2.8.0, tested against 2.7.3

### Device(s) and version(s) of Android being used

Emulator

**Comment by andrewlewis** [comment]
Pretty sure this is fixed but @AquilesCanta can reopen it if not.

**Comment by AquilesCanta** [comment]
Please let us know if you still run into this issue with the current dev branch.

**Comment by karyogamy** [comment]
Works flawlessly now on 2.8.1. Thank you.

**Comment by AquilesCanta** [comment]
Thanks for confirming!
