### ISSUE TITLE
Can't get audio duration

### ISSUE THREAD

**Issue by Khaos116** [google/ExoPlayer#4240]
get duration is -9223372036854775807 
Audio url:
http://dev.storage.singworld.net/3/34/83215_LOW_20180324124008_0.aac

use mediaplayer is ok

**Comment by tonihei** [comment]
That's a duplicate of #3004.

Getting the duration of this file requires to load the entire file first. If you wait a while until the entire file played through, you'll be able to get the final duration.

**Comment by Khaos116** [comment]
thanks @tonihei
