### ISSUE TITLE
Clipping of HLS streams from non-keyframe position starts with audio only

### ISSUE THREAD

**Issue by na-in-lee** [google/ExoPlayer#4241]
### Issue description
If i seekto() and midroll ad skip, the audio and video syncs are not right in ExoPlayer2.6.1.

It is okay if i do not video seekto() or skip the midroll ad.
if i video seekto() and skip the midroll ad, the video is frozen while the audio is playing for 3 seconds.

### Reproduction steps

Test: play start > show preroll > skip preroll > play video(2sec) > move timebar(seekto(00:12:00)) > show midroll 1 > skip  ad (midroll 1)
 => result : just audio play and freezing video about 2~3sec 
 => If i did't seekto() and skip ad(midroll 1), it's OK.
 => if i seekto() and  didn't skip ad (midroll 1), it's OK.
* seek to () + Skip ad => Problem.
 
Video total time : 60 min
Preroll : 00:00:00
Midroll 1 position : 00:10:00
Midroll 2 position : 00:20:00
Midroll 3 position : 00:30:00
* all ad time( total time 30sec, skippable time: 3sec)

in exoplayer 2.6.1 demo
- hls file
- vmap midroll 
 : vast count 4
 : each mp4 file  total 25sec, skippable 3sec 
  * mp4 url : http://nitmus.fms.wecandeo.com/100/2063/2018/05/09/18/V7106262.mp4?key=W6cM7laUHEZ%2BlbXry53N7hYi9yfDrcQswMh6vs4iEXM8XPGGhEVFBelUvZs4lzjs6R%2BScruK2dJ%2F7JKFD6fk9ADyoeThB5VJfWXcW9QIxkQ%3D&px-bps=413748&px-bufahead=10&packageId=1007420&videoId=7379252

### Link to test content
Provide a link to media that reproduces the issue. If you don't wish to post it
publicly, please submit the issue, then email the link to
dev.exoplayer@gmail.com using a subject in the format "Issue #1234".

### Version of ExoPlayer being used
exoplayer 2.6.1
build config : demo

### Device(s) and version(s) of Android being used
device name : Galaxy S8
android version: 8.1

**Comment by tonihei** [comment]
Thanks for filing the issue. Could you please provide us with an ad tag to reproduce the issue? You can also send the link to dev.exoplayer@gmail.com if you don't want to post it publicly.

**Comment by na-in-lee** [comment]
I uploaded the original xml file.
check below xml files.

https://github.com/na-in-lee/sample


1. VMAP file
 - vmap_ex.xml
 : custom path line5, 12, 20 

2. Vast file (vamp tag)
- google_jtbcmp4.xml

**Comment by tonihei** [comment]
Seeking behind the ad + skipping works fine for me in our latest version with the described VMAP setup.
The problem may actually be related to the content media file. Can you provide us with an example of the content HLS playlist?

**Comment by na-in-lee** [comment]
Thanks for the answer.

1. http://api.jtbc.joins.com/news/NV10193538
2. Use "file" value (json parsing)
 - link has expired time about 3hours.
 ex)"file":"http://jtbcvod.fvod.skcdn.com/newsvod/F159283ABCAD91E93212DD7752EE9C2C695052F6387B5EFE6228A97AF21DB6BE072232BEDA54866AC138551899D05FACCF782DF2BD97F2CEA54655E36B18893523642AE5C116B9BF9A5561EFF4F83A4A/playlist.m3u8"

**Comment by tonihei** [comment]
I was able to reproduce your problem now. It's actually unrelated to ads loading and was caused by starting to play the HLS stream from a non-keyframe position. We are going to provide a fix soon.

**Comment by na-in-lee** [comment]
Thanks.

I confirmed and applied your commit. (https://github.com/google/ExoPlayer/commit/7b855e45e60a2932105c1ffbf091c937cf3b7679)

update version : 2.6.1 -> 2.8.1-rc

Close the issue.
