### ISSUE TITLE
Suppose i am downloading a video file. How to play this file while downloading in Exoplayer.

### ISSUE THREAD

**Issue by kunal52** [google/ExoPlayer#4245]
I am downloading a file into the phone I directly give the URI of the File but it through **E/LoadTask: Unexpected exception loading stream** How to do this or is this any way to pause the buffering of exoplayer while some data download.

**Comment by erdemguven** [comment]
You can play the content while downloading. It's hard to say something about your problem without more information. Please provide the info requested in the issue template, which can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).
