### ISSUE TITLE
Error  MtkOmxVdec: [0xb7b888b0] Input picture is over MAX, [0xb7b888b0] Insert PTS error

### ISSUE THREAD

**Issue by kristurek** [google/ExoPlayer#4246]
### Issue description
ExoPlayer crash when i try play stream IPTV on FireStick TV. 
On other devices like Samsung S6 Egde, Nexus 4, Samsung Galaxy Tab works perfect.

On lower resolution sample everything work ok, but on higher resolution (full hd) player crash after 2-5 seconds.

Maybe somebody know where can I increase MAX input size for picture (MtkOmxVdec: [0xb7b888b0] Input picture is over MAX.), and where can I find description of error bug [OMX.MTK.VIDEO.DECODER.AVC] ERROR(0x80001008)

05-02 09:16:42.285   165  7947 E MtkOmxVdec: [0xb7b888b0] Input picture is over MAX.
05-02 09:16:42.285   165  7947 E MtkOmxVdec: [0xb7b888b0] Insert PTS error
05-02 09:16:42.285   165  7947 E MtkOmxVdec: [0xb7b888b0] something wrong when decoding....
05-02 09:16:42.285   165  7947 D MtkOmxVdec: [0xb7b888b0] MtkOmxVdecDecodeThread terminated pVdec=0xB7B888B0
05-02 09:16:42.286  7788  7945 E ACodec  : [OMX.MTK.VIDEO.DECODER.AVC] ERROR(0x80001008)
05-02 09:16:42.286  7788  7945 E ACodec  : signalError(omxError 0x80001008, internalError -2147483648)
05-02 09:16:42.286  7788  7944 E MediaCodec: Codec reported err 0x80001008, actionCode 0, while in state 6

and

05-02 09:16:42.292  7788  7940 E ExoPlayerImplInternal: java.lang.IllegalStateException
05-02 09:16:42.292  7788  7940 E ExoPlayerImplInternal: 	at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
05-02 09:16:42.292  7788  7940 E ExoPlayerImplInternal: 	at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:1055)
05-02 09:16:42.292  7788  7940 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1064)
05-02 09:16:42.292  7788  7940 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:599)
05-02 09:16:42.292  7788  7940 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:522)
05-02 09:16:42.292  7788  7940 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:305)
05-02 09:16:42.292  7788  7940 E ExoPlayerImplInternal: 	at android.os.Handler.dispatchMessage(Handler.java:98)
05-02 09:16:42.292  7788  7940 E ExoPlayerImplInternal: 	at android.os.Looper.loop(Looper.java:135)
05-02 09:16:42.292  7788  7940 E ExoPlayerImplInternal: 	at android.os.HandlerThread.run(HandlerThread.java:61)

### Reproduction steps
Add to media.exolist.json downloaded sample and run demo, after 2-5s player crash.
`{
    "name": "Test stream",
    "samples": [
      {
        "name": "HD",
        "uri": "/storage/sdcard0/Download/hd.mp4"
      }
    ]
  },
`

### Link to test content
Sample stream https://www.dropbox.com/s/8yhtgwjx4jyo6vz/hd.mp4?dl=0

### Version of ExoPlayer being used
Current FireStick Software version Fire OS 5.2.6.2 (587700720)
Fire TV Home Version 6.0.0.4-101
Fresh ExoPlayer from GitHub 2.8.0 or ExoPlayer Amazon Port 2.7.1

### A full bug report captured from the device
Bugreport https://www.dropbox.com/s/1t5qrakqbmbkvfs/bugreport_tvp_hd_amazon.txt?dl=0
Log file https://www.dropbox.com/s/8yl3eag5fr2dy3r/log_amazon.txt?dl=0

Thanks for any help, and sorry for my english
Regards

**Comment by erdemguven** [comment]
For MP4s we normally set the max input size based on the size of the largest sample in the container so it should work fine.

Given you are using the Amazon port and it's an Amazon device, you might ask it on the Amazon port issue tracker: https://github.com/amzn/exoplayer-amazon-port/issues/new
