### ISSUE TITLE
Play files from google drive with ProgressiveDownload or Dash

### ISSUE THREAD

**Issue by marcovietovega** [google/ExoPlayer#4247]
This is more a question than an issue. I'm trying to play video or audio files directly from my google drive account. I'm using the google drive rest API to get the download link (webContentLink), but I keep getting this error "ExoPlayerImplInternal: Source error". I'm following the example that was made in the presentation in #io18 "Building feature-rich media apps with ExoPlayer", to use the progressive download, so I can files, while downloading, but it's not working only with google drive, if I try from other websites it works flawlessly.

**Comment by AquilesCanta** [comment]
Make sure that whatever your URL is pointing to is actually a media file. This is most likely not an ExoPlayer issue, but rather a source issue. Unfortunately, we cannot provide anymore assistance without the information requested in the [issue template](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

**Comment by marcovietovega** [comment]
I understand. Thanks for the answer. It would be great if some kind of integration with google drive were made.

**Comment by tonihei** [comment]
Using the `webContentLink` doesn't work because it is the link to a web page. Have you tried using the download version explained [here](https://developers.google.com/drive/v3/web/manage-downloads)?
