### ISSUE TITLE
Error "SurfaceUtils: Failed to connect to surface

### ISSUE THREAD

**Issue by nimdokai** [google/ExoPlayer#4251]
### Issue description
While playing any content. Going into multi-window cause error: "SurfaceUtils: Failed to connect to surface 0xc73e8008, err -19". As a result player is not starting to play content.

### Reproduction steps
Preconditions: 
- activity with player is set to screenOrientation="sensorLandscape"
- device in portrait position

Steps:
1. Start content
2. trigger multi-window
3. apps are open in portret orientation (because of precondition)
4. Error "SurfaceUtils: Failed to connect to surface 0xc73e8008, err -19" -> black screen

### Link to test content
https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8

### Version of ExoPlayer being used
ExoPlayer:2.6.0

### Device(s) and version(s) of Android being used
on the devices with version < 8 - everything works - **OK**
devices with version >= 8 error occurs - **NOT OK**
 
### A full bug report captured from the device
I know that "a log snippet is NOT sufficient."
But I can't send more information about bug:(   --> NDA 

[log_nimdokai.txt](https://github.com/google/ExoPlayer/files/2000202/log_nimdokai.txt)

**Comment by erdemguven** [comment]
Sorry for very late response. I tried the latest version of ExoPlayer and couldn't reproduce the issue. If you haven't already could you upgrade your ExoPlayer library and let us know if the issue is still producable.

**Comment by nimdokai** [comment]
thanks for respond. I haven no longer access to the code. Hope that upgrading to the latest version is sufficient solution.
