### ISSUE TITLE
HLS Streams Loading Significantly Slower on 2.8.0

### ISSUE THREAD

**Issue by Jogan** [google/ExoPlayer#4254]
### Issue description
After migrating from 2.6.0  to the latest version 2.8.0, I noticed a significant increase in load times for my HLS streams. I am talking greater than 20 secs. The streams eventually load with no errors present in the logs. On 2.6.0 my streams were loading in ~1 sec or less.  Reverting back to the commit before migrating resolves issue. Another note, once the stream loads its a lower quality track and never switches to higher quality.

Was there something significant that changed regarding the load controls? We are using default everything, including default track selectors. Its only an issue with HLS. Dash/Other streams load the same as before.

### Reproduction steps
Not reproducible on Demo player which points to a problem with my implementation :/

### Link to test content
Cannot provide due to licensing. 

### Version of ExoPlayer being used
2.8.0

### Device(s) and version(s) of Android being used
- Samsung S9+, Android 8.0
- ZTE Z981, Android 6.0.1

### A full bug report captured from the device
N/A - no errors in the logs

**Comment by AquilesCanta** [comment]
The best way for us to look quickly into this is to provide sample content. Although if this does not happen in the Demo app, it might be hard to diagnose. Also, if you could pinpoint a specific ExoPlayer version upgrade, that'd be really helpful as well. The main suspect is 2.8 (so could you try 2.7.3?).

If you don't want your content to be disclosed, you can send a link to dev.exoplayer@gmail.com.

**Comment by AquilesCanta** [comment]
It seems highly likely that the root cause is the same as #4239.

**Comment by Jogan** [comment]
@AquilesCanta I actually went back and tried replicating with our streams in the demo player and the same problem DOES exist also in the demo player (when using our stream). I'll shoot an email to dev.exoplayer@gmail.com to debug the issue. When I get some time I'll try reverting to 2.7.3. Thank you!

**Comment by AquilesCanta** [comment]
Just check whether your media playlists have an EXT-X-PROGRAM-DATE-TIME tag. If so, the fix will be pushed soon.

**Comment by AquilesCanta** [comment]
Please let us know if you still run into this issue with the current dev branch.

**Comment by Jogan** [comment]
@AquilesCanta issue resolved in 2.8.1 release. Thanks!

**Comment by AquilesCanta** [comment]
Thanks for the confirmation!
