### ISSUE TITLE
How to get the shuffled play queue after enabling the shuffle mode.

### ISSUE THREAD

**Issue by tuhin10** [google/ExoPlayer#4255]
After enabling the shuffle mode in SimpleExoPlayer (player.setShuffleModeEnabled(true)) how can I get the modified list?

**Comment by andrewlewis** [comment]
You can query the sequence of windows using [`Timeline.getNextWindowIndex`](https://github.com/google/ExoPlayer/blob/d4a03d3/library/core/src/main/java/com/google/android/exoplayer2/Timeline.java#L537), which takes the current window index (`Player.getCurrentWindowIndex`) and the repeat/shuffle modes.

**Comment by andrewlewis** [comment]
In case it's useful, you can also provide your own `ShuffleOrder` implementation when creating a `ConcatenatingMediaSource`, which might give you an easier way to manipulate and access the ordering. @tonihei will be able to comment on the best approach.

**Comment by tonihei** [comment]
Yes, @andrewlewis already pointed to the right options. You can query the current order with `Timeline.get(Next|Previous|First|Last)WindowIndex` and if you want to customize the shuffling, please provide your own `ShuffleOrder`. This also allows you to decide things like where new items are inserted etc.
