### ISSUE TITLE
IMA vast InLine ad 'Learn More'  button is not visible.

### ISSUE THREAD

**Issue by na-in-lee** [google/ExoPlayer#4265]
### Issue description
IMA ad play 'Learn More'  button is not visible.

### Reproduction steps
hls file
vast InLine ad

### Link to test content 
(vast InLine ad sample)
https://github.com/na-in-lee/sample/blob/master/more1.xml

### Version of ExoPlayer being used
exoplayer 2.6.1
build config : demo

### Device(s) and version(s) of Android being used
device name : Galaxy S8
android version: 8.1

**Comment by andrewlewis** [comment]
I can reproduce this with the HTML5 SDK too. It may be an issue with the IMA SDK or a problem with the ad tag.

**Comment by andrewlewis** [comment]
It looks like the end of the ClickThrough URL in the ad tag has been truncated (it ends "%E"). If I remove this the "Learn more" link appears. (Thanks to the IMA team for spotting this!)
