### ISSUE TITLE
Unable to play HLS videos on Lollipop v22 (demo app)

### ISSUE THREAD

**Issue by camilasousa** [google/ExoPlayer#427]
I am running the demo application, but I am unable to play the hls videos on my Nexus 4, Android 5.1. It works fine with an emulator, Android 4.2.2.

Stracktrace:
E/EventLogger(23062): internalError [1.36, decoderInitializationError]
E/EventLogger(23062): com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, MediaFormat(video/avc, -1, 400, 300, 1.0, -1, -1, -1, 1920, 1080)
E/EventLogger(23062): 	at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:322)
E/EventLogger(23062): 	at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:660)
E/EventLogger(23062): 	at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:369)
E/EventLogger(23062): 	at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:462)
E/EventLogger(23062): 	at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:442)
E/EventLogger(23062): 	at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:401)
E/EventLogger(23062): 	at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:203)
E/EventLogger(23062): 	at android.os.Handler.dispatchMessage(Handler.java:98)
E/EventLogger(23062): 	at android.os.Looper.loop(Looper.java:135)
E/EventLogger(23062): 	at android.os.HandlerThread.run(HandlerThread.java:61)
E/EventLogger(23062): 	at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
E/EventLogger(23062): Caused by: android.media.MediaCodec$CodecException: start failed
E/EventLogger(23062): 	at android.media.MediaCodec.native_start(Native Method)
E/EventLogger(23062): 	at android.media.MediaCodec.start(MediaCodec.java:612)
E/EventLogger(23062): 	at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:318)
E/EventLogger(23062): 	... 10 more
E/EventLogger(23062): playerFailed [1.38]
E/EventLogger(23062): com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, MediaFormat(video/avc, -1, 400, 300, 1.0, -1, -1, -1, 1920, 1080)
E/EventLogger(23062): 	at com.google.android.exoplayer.MediaCodecTrackRenderer.notifyAndThrowDecoderInitError(MediaCodecTrackRenderer.java:335)
E/EventLogger(23062): 	at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:322)
E/EventLogger(23062): 	at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:660)
E/EventLogger(23062): 	at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:369)
E/EventLogger(23062): 	at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:462)
E/EventLogger(23062): 	at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:442)
E/EventLogger(23062): 	at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:401)
E/EventLogger(23062): 	at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:203)
E/EventLogger(23062): 	at android.os.Handler.dispatchMessage(Handler.java:98)
E/EventLogger(23062): 	at android.os.Looper.loop(Looper.java:135)
E/EventLogger(23062): 	at android.os.HandlerThread.run(HandlerThread.java:61)
E/EventLogger(23062): 	at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
E/EventLogger(23062): Caused by: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, MediaFormat(video/avc, -1, 400, 300, 1.0, -1, -1, -1, 1920, 1080)
E/EventLogger(23062): 	... 11 more
E/EventLogger(23062): Caused by: android.media.MediaCodec$CodecException: start failed
E/EventLogger(23062): 	at android.media.MediaCodec.native_start(Native Method)
E/EventLogger(23062): 	at android.media.MediaCodec.start(MediaCodec.java:612)
E/EventLogger(23062): 	at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:318)
E/EventLogger(23062): 	... 10 more
D/EventLogger(23062): state [1.43, true, I]

**Comment by ojw28** [comment]
They work fine for me (on the dev branch at least). What build are you running, exactly? You can find out by going to Settings -> About phone, scrolling to the bottom. Everything under "Build number" is relevant.

**Comment by camilasousa** [comment]
Build Number: LMY47O

I tried the dev branch and got the same exception :/

**Comment by ojw28** [comment]
And which video(s) are you playing exactly? If you reboot the device does the problem persist? Thanks!

**Comment by camilasousa** [comment]
I played all the hsl videos. I rebooted the device and now it works! Thanks!
Will this happen again eventually?

**Comment by ojw28** [comment]
Sometimes devices get stuck in bad states, unfortunately. I'm not sure there's much we can do to work around it :(.
