### ISSUE TITLE
When a fragment gets recreated and the new fragment wants to play a video it shows the freezed last frame of the previous video

### ISSUE THREAD

**Issue by ChristianKleineidam** [google/ExoPlayer#4270]
For my app I want to play videos in a fragment. Whenever I want to play a new video I want to create a new fragment.
In Android versions lower than API Level 26 (Android 8), the first time I play the video everything goes well. If I however want to replay the video it doesn't work correctly, the sound plays but the video shows the last frame that was played in the previous video in a freezed fashion. All the while ExoPlayer doesn't show any errors. 

I created a minimized example and uploaded it to [Github ](https://github.com/ChristianKleineidam/VideoProblems)and also created a [StackOverflow question](https://stackoverflow.com/questions/50354202/when-i-play-a-second-video-only-a-freezed-frame-of-the-first-video-is-shown-and).

The main code that reproduces the problem is:

    public class MainActivity extends Activity {
        @Override
        protected void onCreate(Bundle savedInstanceState) {
            super.onCreate(savedInstanceState);
            setContentView(R.layout.activity_main);
            Button mButton = findViewById(R.id.button1);
            mButton.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {
                    createNewFragment();
                }
            });
        }
    
        private void createNewFragment() {
            FragmentTransaction ft = getFragmentManager().beginTransaction();
            ft.add(R.id.contentFragment, new VideoFragment());
            ft.commit();
        }
    }
    
    public class VideoFragment extends Fragment implements SurfaceHolder.Callback{
        private Context mContext;
        private SimpleExoPlayer mPlayer;
    
        @Override
        public View onCreateView(LayoutInflater inflater, ViewGroup container,
                                 Bundle savedInstanceState) {
            View view = inflater.inflate(R.layout.videolayout, container, false);
            SurfaceView mSurfaceView = (SurfaceView) view.findViewById(R.id.surface_view1);
            SurfaceHolder surfaceHolder = mSurfaceView.getHolder();
            surfaceHolder.setSizeFromLayout();
            surfaceHolder.addCallback(this);
    
            mContext = inflater.getContext();
    
            return view;
        }
    
        @Override
        public void surfaceCreated(SurfaceHolder holder) {
            BandwidthMeter bandwidthMeter = new DefaultBandwidthMeter();
            TrackSelection.Factory videoTrackSelectionFactory = new AdaptiveTrackSelection.Factory(bandwidthMeter);
            TrackSelector trackSelector = new DefaultTrackSelector(videoTrackSelectionFactory);
    
            mPlayer = ExoPlayerFactory.newSimpleInstance(mContext, trackSelector);
            mPlayer.setVideoSurfaceHolder(holder);
            mPlayer.setPlayWhenReady(true);
            playVideo(mContext);
        }
    
        private void playVideo(Context context){
            final RawResourceDataSource rawResourceDataSource = new RawResourceDataSource(context);
    
            int raw_res_id = context.getResources().getIdentifier(
                    "collect",
                    "raw",
                    context.getPackageName());
            DataSpec dataSpec = new DataSpec(RawResourceDataSource.buildRawResourceUri(raw_res_id));
            try {
                rawResourceDataSource.open(dataSpec);
    
                DataSource.Factory factory = new DataSource.Factory() {
                    @Override
                    public DataSource createDataSource() {
                        return rawResourceDataSource;
                    }
                };
                MediaSource media_source = new ExtractorMediaSource.Factory(factory).createMediaSource(rawResourceDataSource.getUri());
                mPlayer.prepare(media_source);
    
            } catch (RawResourceDataSource.RawResourceDataSourceException e) {
                e.printStackTrace();
            }
        }
    
        @Override
        public void surfaceChanged(SurfaceHolder holder, int format, int width, int height) {
        }
    
        @Override
        public void surfaceDestroyed(SurfaceHolder holder) {
        }
    }

**Comment by andrewlewis** [comment]
A few things stand out (though not all may be relevant to the reported issue):
1. When creating the `ExtractorMediaSource.Factory` you can just pass a `new DefaultDataSourceFactory` then pass `RawResourceDataSource.buildRawResourceUri(raw_res_id)` to `createMediaSource`. You don't need to call `open` or create a `DataSpec`.
1. `SimpleExoPlayer` can take care of handling the surface lifecycle for you. So it should work to create just one player instance, then each time you get a `SurfaceView` you can call `setVideoSurfaceView` to output to it (having prepared the player with the media you want to play).
1. At the moment it looks like the player isn't being released anywhere, which can cause resources to leak.
1. There may be issues stacking `SurfaceView`s on top of each other, so to diagnose what's going on it would be good to make sure you only have one of these visible at a time.

**Comment by ChristianKleineidam** [comment]
I integrated points 2/3/4 and while it simplified the code, the problem still exists in the same way:

public class VideoFragment extends Fragment{
    private Context mContext;
    private SimpleExoPlayer mPlayer;
    private SurfaceView mSurfaceView;

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        View view = inflater.inflate(R.layout.videolayout, container, false);
        mContext = inflater.getContext();

        mSurfaceView = view.findViewById(R.id.surface_view1);

        BandwidthMeter bandwidthMeter = new DefaultBandwidthMeter();
        TrackSelection.Factory videoTrackSelectionFactory = new AdaptiveTrackSelection.Factory(bandwidthMeter);
        TrackSelector trackSelector = new DefaultTrackSelector(videoTrackSelectionFactory);

        mPlayer = ExoPlayerFactory.newSimpleInstance(mContext, trackSelector);
        mPlayer.setVideoSurfaceView(mSurfaceView);
        mPlayer.setPlayWhenReady(true);
        playVideo(mContext);

        return view;
    }

    private void playVideo(Context context){
        final RawResourceDataSource rawResourceDataSource = new RawResourceDataSource(context);

        int raw_res_id = context.getResources().getIdentifier(
                "collect",
                "raw",
                context.getPackageName());
        DataSpec dataSpec = new DataSpec(RawResourceDataSource.buildRawResourceUri(raw_res_id));
        try {
            rawResourceDataSource.open(dataSpec);

            DataSource.Factory factory = new DataSource.Factory() {
                @Override
                public DataSource createDataSource() {
                    return rawResourceDataSource;
                }
            };
            MediaSource media_source = new ExtractorMediaSource.Factory(factory).createMediaSource(rawResourceDataSource.getUri());
            mPlayer.prepare(media_source);

        } catch (RawResourceDataSource.RawResourceDataSourceException e) {
            e.printStackTrace();
        }
    }

    @Override
    public void onDestroyView() {
        mPlayer.release();
        super.onDestroyView();
    }
}

When it comes to point 1 I tried to make it work but what I tried doesn't get a video to play. (When I google I can't find an explanation of how to do it better)
```
    private void playVideo(Context context){
        DataSource.Factory factory = new DefaultDataSourceFactory(
                mContext,
                Util.getUserAgent(mContext, context.getPackageName()) ) ;
        Uri uri= Uri.parse("android.resource://"+context.getPackageName()+"/raw/collect");
        MediaSource media_source = new ExtractorMediaSource.Factory(factory).createMediaSource(uri);
        mPlayer.prepare(media_source);
    }
```

I uploaded the updated version again to https://github.com/ChristianKleineidam/VideoProblems

**Comment by andrewlewis** [comment]
Do you need to create a new player each time `onCreateView` is called, or can you just have one player (created in your activity) and call `setVideoSurfaceView` each time you make a new fragment, to output to the new fragment? (This won't work if you're trying to play more than one video at once, though.)

Please try passing `RawResourceDataSource.buildRawResourceUri(raw_res_id)` to `createMediaSource`.

**Comment by ChristianKleineidam** [comment]
Thanks, passing `RawResourceDataSource.buildRawResourceUri(raw_res_id)` worked. 
I found the bug via StackOverflow. It seems that calling `.replace()` instead of `.add()` for the fragment change solved the issue.
