### ISSUE TITLE
SimpleExoPlayer.seekTo is ignore if it is called before ExoPlayer.STATE_READY is set

### ISSUE THREAD

**Issue by laurafuente** [google/ExoPlayer#4277]
If I called the method SimpleExoPlayer.seekTo before the player has reached the status ExoPlayer.STATE_READY becuase it is preparing, this called is ignore and the video starts at 0 position.

So if I called this method when player is ready it shown the first frame of the video and then it changes to the selected position.

I'm using exoplayer 2.4.4 and I can reproduce this issue at for examplesamsung S7 edge with android version 7.0

**Comment by erdemguven** [comment]
Please see #2197 and let us know if it solves your issue.

**Comment by laurafuente** [comment]
I've tried that fix but it's not working for me

**Comment by erdemguven** [comment]
Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).
