### ISSUE TITLE
Play h265 video coding, ACS3 audio encoding video without sound.

### ISSUE THREAD

**Issue by AlawnXu** [google/ExoPlayer#4279]
Play h265 video coding, ACS3 audio encoding video without sound. Trouble help to solve it, thank you!

**Comment by erdemguven** [comment]
Do you mean AC3? Android devices are not required to support AC3, and many devices do not do so. See the "Sample Formats" section of [this page](https://google.github.io/ExoPlayer/supported-formats.html) for mode details.
