### ISSUE TITLE
setDataSource is failing in case of FileDescriptor of a MemoryFile

### ISSUE THREAD

**Issue by devenkhari** [google/ExoPlayer#428]
Hi,

I'm using a MemoryFile in DefaultRendererBuilder and passing its FileDescriptor to FrameworkSampleExtractor constructor. When mediaExtractor.setDataSource is called inside the prepare method of FrameworkSampleExtractory, it fails with an exception, "Failed to instantiate extractor".

I'm basically creating this MemoryFile because I'm doing the decryption through my methods of the encrypted mp4. Is it the right thing to do or should I use the decryption provided by ExoPlayer. I tried it but couldn't make it work so I resorted to decrypt myself and I want to keep the decrypted content in memory, can not write into a file for security reasons.

Please help.

Thanks.

**Comment by ojw28** [comment]
You should use ExtractorSampleSource together with Mp4Extractor. When building your ExtractorSampleSource you'll need to pass a DataSource, which is where the data is requested from. You can implement a custom DataSource to perform whatever decryption you require.

**Comment by devenkhari** [comment]
Thanks for your response. 
I can't see the classes that you have mentioned rather I can see DefaultSampleSource, FrameworkSampleExtractor and MP4Util etc. Am I working with wrong version?

Regards

**Comment by ojw28** [comment]
Use the dev branch. We'll be pushing all changes from dev -> master late this week or early next.

**Comment by devenkhari** [comment]
Thanks! I will try that.

**Comment by devenkhari** [comment]
I have made changes in FileDataSource as below (it's not using MemoryFile yet, I just wanted to run the save filed first):
public long open(DataSpec dataSpec) throws FileDataSourceException {
    try {
      uri = dataSpec.uri.toString();

        if(uri.contains(".enc")){
            BVCrypto.Init(null);
            try {
                FileInputStream in = new FileInputStream(dataSpec.uri.getPath());
                uri = uri.substring(0, uri.lastIndexOf("."));
                FileOutputStream out = new FileOutputStream(uri);
                BVCrypto.decrypt(in, out);
                out.close();
            } catch (NoSuchAlgorithmException e) {
                e.printStackTrace();
            } catch (NoSuchPaddingException e) {
                e.printStackTrace();
            } catch (InvalidKeyException e) {
                e.printStackTrace();
            } catch (InvalidAlgorithmParameterException e) {
                e.printStackTrace();
            } catch (IOException e) {
                e.printStackTrace();
            }

            file = new RandomAccessFile(uri, "r");
        }else {
            file = new RandomAccessFile(dataSpec.uri.getPath(), "r");
        }
  .....
The problem is that this method is being called multiple times and it fails in some calls in the condition shown below:

      if (bytesRemaining < 0) {
        throw new EOFException();
      }

Why is this method being called multiple times? Is this method the correct place to make my changes?

Regards,
Deven

**Comment by devenkhari** [comment]
Some more details:
This method of FileDataSoruce is being called multiple time from the load method of ExtractorSample Source class.

**Comment by devenkhari** [comment]
Sorry, load method is the member of ExtractingLoadable class

**Comment by ojw28** [comment]
You're implementing the DataSource interface. A DataSource can be opened and closed multiple times to read ranges of the data, as specified by the DataSpec objects that are passed to DataSource.open. You'll need to spend some time familiarizing yourself with these two classes, and it's probably helpful to look at some of the implementations provided by the library to see how they're implemented.
