### ISSUE TITLE
Cannot extend PlayerControlView

### ISSUE THREAD

**Issue by xdeop** [google/ExoPlayer#4284]
Unable to extend the PlayerControlView class to create a custom control view as all the variables in the PlayerControlView class are private instead of protected.

I'd just would like to limit the timeBar's time-shifting to the minimum between the live stream's time-shifting and the show's starting time. For it, the updateProgress method should be overridden to add the limitation but when creating a child class of the PlayerControlView all the variables are inaccessible. There is another solution?

**Comment by ojw28** [comment]
The `updateProgress` is pretty complicated. How would you override it, exactly? If your plan is to copy the whole implementation and then tweak a few lines, that's probably not the best idea, because if we were to ever make further modifications to the method your overriding copy wouldn't pick those changes up.

> I'd just would like to limit the timeBar's time-shifting to the minimum between the live stream's time-shifting and the show's starting time.

Do you mean maximum (i.e. some content from a previous show is available in the source, but you don't want to allow seeking to it)? Or do you really mean minimum, in which case how will you be handling seeks to positions earlier than the start of the live window?

**Comment by xdeop** [comment]
I know is not the best solution but copying the PlayerControlView implementation is the ONLY possible way to override the updateProgress as there's no access to the parent's variables nor methods when extending from it (ex: LivePlayerControlView). I think that the PlayerControlView implementation should have protected variables and methods (also exposing the onScrubListener) to permit a progressbar customization.

What I'm trying to accomplish is having the live stream positioned in the progressbar referenced to a show's time interval:

start time ==============|------------------------- end time

current position (stream position referenced to show's interval)

**Comment by ojw28** [comment]
Allowing sub-classes to arbitrarily use and override whatever they want isn't a good design choice. It might work in the short term, but will make upgrading from one version to the next really difficult if we ever change anything in the `PlayerControlView` implementation. So I think you need to either:

1. Fork `PlayerControlView`. It's not actually that bad to do this, in my opinion.
1. Come up with a minimal set of properly thought out extension points, that can be made protected in `PlayerControlView`, that are sufficient to let you do what you need to do. If you have a proposal for how we might do this, in a way that's not just making everything protected, then we'd be happy to consider it.

**Comment by xdeop** [comment]
I was looking for #2 approach. 

As I'm running out of time in my development I haven't been able to think of a properly minimal set of protected vars and/or methods and just set all the ones I needed. 

Thanks.

**Comment by ojw28** [comment]
Unless you're going to propose a minimal set of extension points for us to add, there's nothing for us to do here. Closing for now. If you do come up with such a set, please send a pull request.
