### ISSUE TITLE
withMaxVideoBitrate does not exists anymore

### ISSUE THREAD

**Issue by billyjoker** [google/ExoPlayer#4287]
Hi, i've just updated to Exoplayer 2.8.0 and i get that the method from trackselector `withMaxVideoBitrate `does not exists, what is the alternative to this one?

Occurrs the same with `withPreferredAudioLanguage `and `MappingTrackSelector.SelectionOverride`

```
        trackSelector.setParameters(trackSelector.getParameters()
                .withMaxVideoBitrate(bitrate));
```

Thanks!!

**Comment by botaydotcom** [comment]
Hi @billyjoker,
I think in 2.8.0, you can use `DefaultTrackSelector.ParametersBuilder` for these functionalities.
The example in the doc was:
```
trackSelector.setParameters(
     trackSelector
         .buildUponParameters()
         .setMaxVideoSizeSd()
         .setPreferredAudioLanguage("deu"));
```
Please check out our demo app for further details.
