### ISSUE TITLE
HLS freezes every second on poor connection

### ISSUE THREAD

**Issue by Sybergoth** [google/ExoPlayer#4289]
### Issue description
I have a project where I stream HLS videos to an android app.
The videos are created with ffmpeg, h264, aac encoded and then segmented to TS segments.

Example of the index of the hls videos:

```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:16
#EXT-X-MEDIA-SEQUENCE:0
#EXTINF:15.023222,
index0.ts
#EXTINF:15.000000,
index1.ts
#EXTINF:7.560000,
index2.ts
#EXT-X-ENDLIST

```
I have a recyclerview which contains a number of such videos, but always only a single player is playing.
The code in the android app (kotlin) which runs the videos:

```
val videoTrackSelectionFactory = AdaptiveTrackSelection.Factory(DefaultBandwidthMeter())

val trackSelector = DefaultTrackSelector(videoTrackSelectionFactory)
mPlayer = ExoPlayerFactory.newSimpleInstance(context, trackSelector)
val dataSourceFactory = DefaultDataSourceFactory(mContext.get(), 
                                                      Util.getUserAgent(mContext.get(), "app"))

val hlsMediaSource = HlsMediaSource.Factory(dataSourceFactory).setAllowChunklessPreparation(true).createMediaSource(Uri.parse(url))

mPlayer?.prepare(hlsMediaSource)

```

The code works good on a fast internet connection. However, when the connection is poor/mediocre the exoplayer plays the videos for half a second than freezes than again for half a second and freezes and so on.

When playing the video with the same internet quality in a web browser the video is playing regularly.

How can I overcome this freezing problem? Does it has something to do with how exoplayer buffers and manages the segments? If so can I manipulate it?

Thanks. 

### Version of ExoPlayer being used
2.7.3

### Device(s) and version(s) of Android being used
Android Marshmallow, Android lollipop

**Comment by AquilesCanta** [comment]
Are you releasing players that are not currently playing? It would be good to trace network usage from the app, and compare it with the brower's usage.

**Comment by Sybergoth** [comment]
I really had another undesired player in the background.
Fixed it and now the streaming is better. Thank you!
