### ISSUE TITLE
set local address for cache file

### ISSUE THREAD

**Issue by AlirezaGhanbarinia** [google/ExoPlayer#4290]
Hi
I want to know is it possible to set the address manually for saving the cache file? If no, how can we access the address of the cached video file programmatically?

**Comment by erdemguven** [comment]
It's not advised to directly access to cache files. Instead you should use a CacheDataSource to read the data.

If you still want to access to the files (at your own risk):
Cached data is split into multiple cache files. File names are generated automatically.
You can find these files using: 
```
    String key = CacheUtil.generateKey(uri);
    NavigableSet<CacheSpan> cachedSpans = cache.getCachedSpans(key);
    for (CacheSpan cachedSpan : cachedSpans) {
      // do something with cachedSpan.file
    }
```

**Comment by AlirezaGhanbarinia** [comment]
thank you
I accessed the files. but why the file format is .exo? the url  i have set to player, is a mp4 file.

and another question, what are the problems we are going to confront ? since you said it has high risk.

**Comment by erdemguven** [comment]
It's the internal file format to store a span of cached data. Currently it contains only the cached data but this can change. If it changes your code may become broken.

**Comment by AlirezaGhanbarinia** [comment]
well thaks again.
Is it possible to download the file when playing the streaming file from url Simultaneously?
