### ISSUE TITLE
MediaSessionConnector - metadata for Samsung

### ISSUE THREAD

**Issue by izderadicka** [google/ExoPlayer#4292]
### Issue description
I use `TimelineQueueNavigator`  with  my media application on Samsung phones.
Queue get `MediaDescriptionCompat` from queue and maps it to `MediaMetadataCompat` which is then set in `MediaSession`. 
The main infomartion about media item is its title - now comes interesting part - connector maps description title into `MEDIA_KEY_DISPLAY_TITLE`  key,  but Samsung (in lock and AOD screens) does not care about this key it but looks only for `MEDIA_KEY_TITLE` key. 
So on Samsung phone I see "Unknown" on AOD and lock screen when my MediaSession is active.

Solution would be to set both `MEDIA_KEY_DISPLAY_TITLE`  and `MEDIA_KEY_TITLE` in `updateMediaSessionMetadata` method to fix this Samsung issue ( theoretically its their problem, but they are still big player and it's probably fair to expect   `MEDIA_KEY_TITLE`  to be always present and use the other one as an alternative)

I hope my description is not too confusing otherwise  please let me know and I can provide some more details. 

### Reproduction steps
Use app in Samsung 

Set to use Lock screen - e.g. lock at least to swipe

Look on Lock Screen or AOD screen media controls

### Version of ExoPlayer being used
master

### Device(s) and version(s) of Android being used
Samsung specific -  N and O versions

**Comment by DKillWorld** [comment]
This happenes on certain more devices I tested with. Certainly needs some quick fix.
