### ISSUE TITLE
Exoplayer and Rtp Multicast support

### ISSUE THREAD

**Issue by mateuszbm** [google/ExoPlayer#4294]
Hi,
I'm trying to integrate Rtp support from this pullrequest(https://github.com/google/ExoPlayer/pull/3244) into newest ExoPlayer version. I created necessary files and copy paste code in existing ones.
Everytihing seems to work good, project compile without any errors but when I'm trying to play video nothing happen.

Debug log code:
I/ExoPlayerImpl: Init 8e1481f [ExoPlayerLib/2.8.1] [p212, MAG410, Amlogic, 23]
D/EventLogger: state [0.03, 0.00, window=0, true, BUFFERING]
I/Choreographer: Skipped 42 frames!  The application may be doing too much work on its main thread.
D/EventLogger: timelineChanged [0.11, 0.00, window=0, periodCount=1, windowCount=1, reason=PREPARED
D/EventLogger:   period [?]
                 window [?, false, false]
               ]
D/EventLogger: mediaPeriodCreated [0.20, 0.00, window=0, period=0]
D/EventLogger: loading [0.21, 0.00, window=0, period=0, true]
I/art: Background partial concurrent mark sweep GC freed 45733(2MB) AllocSpace objects, 0(0B) LOS objects, 40% free, 10MB/18MB, paused 2.032ms total 103.607ms

I'm testing this on ExoPlayer demo app. 
Could you please give me any advice on what I'm doing wrong? Thanks.

**Comment by ojw28** [comment]
Please try asking the pull request authors directly on the pull request. We haven't really looked at that code in detail yet, and so are unable to answer questions about it here.
