### ISSUE TITLE
Playblack problem on Samsung Galaxy S2

### ISSUE THREAD

**Issue by marinica94** [google/ExoPlayer#430]
Hi ! I am using the mp3 extractor from the dev branch to stream mp3 playlist in my app.I have tested untill now on 6 devices but only on S2 I have bad response from library. After reading this thread: https://github.com/google/ExoPlayer/issues/273 I noticed the hardware decoding problem on S2 and I think that would be the problem. Is there a way to switch to software decoding or would this solve the problem ?

Also my BUFFER_SIZE is set to 10 * 1024 * 1024, what would be the best buffer size and how influence this the playblack.

        transferListener = new TransferListener() {
            @Override
            public void onTransferStart() {

            }

            @Override
            public void onBytesTransferred(int bytesTransferred) {

            }

            @Override
            public void onTransferEnd() {

            }
        };

                        mp3Extractor = new Mp3Extractor();
                        dataSource = new DefaultUriDataSource("musicStream", transferListener);
                        sampleSource = new ExtractorSampleSource(uri, dataSource, mp3Extractor, 1, BUFFER_SIZE);
                        MediaCodecAudioTrackRenderer audioRenderer =
                                new MediaCodecAudioTrackRenderer(sampleSource, null, true);
                        exoPlayer.prepare(audioRenderer);

The log from the samsung galaxy s2: http://pastebin.com/qLY4na6z

**Comment by marinica94** [comment]
I come back with a question: Does smoothstreaming support only Audio stream of MP3 files ? I tryed to change my player with  SmoothStreamingRendererBuilder but I couldn't make him play, if anyone could guide me with a basic Sample that would be perfect. Thanks !

**Comment by ojw28** [comment]
There's nothing actionable in this issue. If your problem still occurs on 1.5.0 or later, please file a new issue containing all of the information described [here](https://google.github.io/ExoPlayer/2015/10/01/reporting-issues.html). Thanks.
