### ISSUE TITLE
Can Exoplayer record the time played of  every file in playlist? 

### ISSUE THREAD

**Issue by kingofswing** [google/ExoPlayer#4301]
### Issue description
Actually It's a question in mind for several days after searched issues for the answer but with no luck. It's about statistics of playlist. What I want is to record the video name, video duration , time played ( normal transition to the next one or press next button ) and save to backend.     

I'm new to Exoplayer , and hope to use Exoplayer to do the job, any help or clue would be greatly appreciated!

**Comment by tonihei** [comment]
ExoPlayer offers a number of listeners to get this kind of information - e.g. `Player.EventListener` or the more detailed `AnalyticsListener`. You can listen to `onPositionDiscontinuity` events to calculate the time played, and listen to `onTimelineChanged` to retrieve the duration as soon as known (or check `player.getCurrentDuration()`. You can also set and get a custom tag for each `MediaSource`  (in the builder). This would allow you to track the video name. 

Besides that, we are planning to providing a listener implementation which gives playback stats (such as "total time played", and much more). But that's still work in progress.

**Comment by kingofswing** [comment]
Thanks for your quick reply, @tonihei , I’ll learn to how to make use of  these 2 listeners .

**Comment by hafiz013** [comment]
question, how to get total time for each media source that play in exoplayer?
