### ISSUE TITLE
Add option to show buffering view when setPlayWhenReady=false

### ISSUE THREAD

**Issue by Gidex** [google/ExoPlayer#4304]
private void updateBuffering() {
    if (bufferingView != null) {
      boolean showBufferingSpinner =
          showBuffering
              && player != null
              && player.getPlaybackState() == Player.STATE_BUFFERING
              && `player.getPlayWhenReady();`
      bufferingView.setVisibility(showBufferingSpinner ? View.VISIBLE : View.GONE);
    }
  }

I think PlayerView.getPlayWhenReady() should not interfere with the visibility of the bufferingView, since the player keeps buffering even when paused...

**Comment by botaydotcom** [comment]
Hi @Gidex,
I think the idea is to only show buffering view when user is watching/focusing on the player. If `player.getPlayWhenReady()` is false, the player is paused, and buffering is only done in the background. This is something user probably doesn't care about.
Is this something that's causing problem in your use case? Could you please clarify the problem you are facing in more details?

**Comment by ojw28** [comment]
I can confirm the current behavior is intentional. Displaying a buffering spinner when the user intention isn't to start playback immediately feels like extra UI noise that doesn't provide the user with useful information. We could probably make the behavior configurable, but I'm not convinced it's important.

**Comment by Gidex** [comment]
As a user, I find it common for the user to use the buffering spinner to know when the player is ready to play. When watching and the player starts buffering, if the user pauses and the buffering spinner disappears, he may think the player is ready, but if the buffering spinner appears again when playing, it may seem confusing. In slow or unstable connections it is common for the user to pause to wait for the player to load enough so that he can continue without problems, so if he pauses and leaves his cell phone on the couch to go to drink water, when he returns and does not see the buffering spinner, no doubt he will think that the player is ready to play.
I'm using `onPlayerStateChanged` to do this, but it would be great if `PlayerView.setShowBuffering` was configurable :)

**Comment by szaboa** [comment]
@ojw28 
Can I work on this or it is already in progress?

**Comment by ojw28** [comment]
Feel free to work on this! I think I'd envisage a new `PlayerView.setShowBuffering` method that takes an `IntDef` that can have three values (`SHOW_BUFFERING_NEVER` / `SHOW_BUFFERING_WHEN_PLAYING` / `SHOW_BUFFERING_ALWAYS`). You can then deprecate the old method and update it to call the new one in a way that maintains its current behavior:

```
public void setShowBuffering(boolean showBuffering) {
  setShowBuffering(
      showBuffering ? SHOW_BUFFERING_WHEN_PLAYING : SHOW_BUFFERING_NEVER
}
```

Open to other approaches also.

**Comment by szaboa** [comment]
Thank you, I do not see any better approach at the moment. 
Started to work on this, will do the PR once is done.

**Comment by szaboa** [comment]
@ojw28 
Pull request here: https://github.com/google/ExoPlayer/pull/4585

**Comment by ojw28** [comment]
This will be merged shortly. Let's use the pull request for tracking.
