### ISSUE TITLE
API to get the Buffer lenghth

### ISSUE THREAD

**Issue by rakesharyais** [google/ExoPlayer#4307]
### Issue description
I am using getBufferedPosition() to get the buffer length .
The value returned by this API is  is too high when i seek. The value is around 1456324 ms 
Is this the right API to get the buffer length ? or is Someother calculation is required

### Version of ExoPlayer being used
Exoplayer version is 2.8.1 and even we have the same issue in 2.7.1

### Device(s) and version(s) of Android being used
On Android O Nexus P device

**Comment by tonihei** [comment]
getBuffered**Position**() returns the position in the media up to which the player has buffered data. You probably want to subtract getCurrentPosition() to the get the length of the current buffer.

Note that we are also planning to add an API to do this directly (which also works correctly for prebuffering in playlists). This is most likely part of the next release.
