### ISSUE TITLE
HLS live frequent stuck and some time does not recover 

### ISSUE THREAD

**Issue by getashok2003** [google/ExoPlayer#4309]
Sting TV android box
Android version - 7.0
Scenario - HLS live content play
Always seeing this -YES
Exoplayer version - r2.8.1

**Use case-** tune to HLS live content
**Expected behavior-** Video should keep playing 
**Actual behavior-** Frequent video stuck are seen, some time video did not recover,
**Initial observation-** 
onLoadCompleted response -looks like download of bitrate .m3u8 file is not succeed because bytesLoaded: 98834 value is not changing in stuck case.
**onLoadingChanged: isLoading: false ,** isLoading is false in case of problem.
onLoadStarted: data call is not  seen for .TS download.
playbackState set to STATE_BUFFERING from STATE_READY.
**This issue is not seen in Exoplayer 2.6.1**

**Comment by AquilesCanta** [comment]
We will need content that reproduces the issue to diagnose this. The test streams we have do not reproduce the issue. We will reopen the issue once sample content is provided.
