### ISSUE TITLE
Proguard for r2.0.1

### ISSUE THREAD

**Issue by arushijain45** [google/ExoPlayer#4310]
I am using exo player version r2.0.1 but getting following error:
Warning:Exception while processing task java.io.IOException: Can't write [/.../build/intermediates/transforms/proguard/user/release/jars/3/1f/main.jar] (Can't read [/home/pw/.android/build-cache/19b040b601e1ecad3e7b1996c52b38484ce7ffc8/output/jars/classes.jar(;;;;;;**.class)] (Duplicate zip entry [com/google/android/exoplayer2/l.class == classes.jar:com/google/android/exoplayer2/LoadControl.class]))

PS: I could not find proguard for exoplayer r2.0.1 so I just use --dontwarn com.google.android.exoplayer2.**

**Comment by ojw28** [comment]
It looks like there are probably two versions of ExoPlayer in your binary. I'd suggest taking a look at what's causing that.
