### ISSUE TITLE
Can exoplayer play HLS video with MPGA audio format 

### ISSUE THREAD

**Issue by anandsingh2903** [google/ExoPlayer#4313]
As i am trying to play a HLS m3u8 video via my local network. The video is running fine but the audio is not coming and as i have checked the audio format is MPGA with i guess exoplayer HLS stream doesn't support. So is there any way that i can play MPGA format audio with HLS video using Exoplayer. Also when i tired to play SPTS type of Stream then the data was coming from my local network and my player is receiving data also as it is showing network speed usage but the video is not getting displayed.

**Comment by AquilesCanta** [comment]
You need to determine whether the container format or the compression format is the issue. If the issue is the container, then a new extractor needs to be implemented. If the codec is the issue, then you could use the ffmpeg extension to play audio. The logcat is enough to tell whether the track was detected / supported. 

You can look for something like this:

```
05-29 09:40:30.635 2061-2061/com.google.android.exoplayer2.demo D/EventLogger:   Renderer:0 [
05-29 09:40:30.635 2061-2061/com.google.android.exoplayer2.demo D/EventLogger:     Group:0, adaptive_supported=YES [
05-29 09:40:30.635 2061-2061/com.google.android.exoplayer2.demo D/EventLogger:       [X] Track:0, id=0, mimeType=video/avc, bitrate=232370, supported=YES
05-29 09:40:30.636 2061-2061/com.google.android.exoplayer2.demo D/EventLogger:       [X] Track:1, id=1, mimeType=video/avc, bitrate=649879, supported=YES
05-29 09:40:30.636 2061-2061/com.google.android.exoplayer2.demo D/EventLogger:       [X] Track:2, id=2, mimeType=video/avc, bitrate=991714, supported=YES
05-29 09:40:30.636 2061-2061/com.google.android.exoplayer2.demo D/EventLogger:       [X] Track:3, id=3, mimeType=video/avc, bitrate=1927833, supported=YES
05-29 09:40:30.637 2061-2061/com.google.android.exoplayer2.demo D/EventLogger:     ]
05-29 09:40:30.637 2061-2061/com.google.android.exoplayer2.demo D/EventLogger:   ]
05-29 09:40:30.637 2061-2061/com.google.android.exoplayer2.demo D/EventLogger:   Renderer:2 [
05-29 09:40:30.637 2061-2061/com.google.android.exoplayer2.demo D/EventLogger:     Group:0, adaptive_supported=N/A [
05-29 09:40:30.637 2061-2061/com.google.android.exoplayer2.demo D/EventLogger:       [X] Track:0, id=1/15, mimeType=audio/mp4a-latm, channels=2, sample_rate=22050, supported=YES
05-29 09:40:30.637 2061-2061/com.google.android.exoplayer2.demo D/EventLogger:     ]
05-29 09:40:30.637 2061-2061/com.google.android.exoplayer2.demo D/EventLogger:   ]
05-29 09:40:30.637 2061-2061/com.google.android.exoplayer2.demo D/EventLogger:   Renderer:6 [
05-29 09:40:30.638 2061-2061/com.google.android.exoplayer2.demo D/EventLogger:     Group:0, adaptive_supported=N/A [
05-29 09:40:30.638 2061-2061/com.google.android.exoplayer2.demo D/EventLogger:       [ ] Track:0, id=1/8219, mimeType=application/cea-608, supported=YES
05-29 09:40:30.638 2061-2061/com.google.android.exoplayer2.demo D/EventLogger:     ]
05-29 09:40:30.638 2061-2061/com.google.android.exoplayer2.demo D/EventLogger:   ]
05-29 09:40:30.638 2061-2061/com.google.android.exoplayer2.demo D/EventLogger:   Renderer:7 [
05-29 09:40:30.638 2061-2061/com.google.android.exoplayer2.demo D/EventLogger:     Group:0, adaptive_supported=N/A [
05-29 09:40:30.638 2061-2061/com.google.android.exoplayer2.demo D/EventLogger:       [X] Track:0, id=1/21, mimeType=application/id3, supported=YES
05-29 09:40:30.638 2061-2061/com.google.android.exoplayer2.demo D/EventLogger:     ]
05-29 09:40:30.638 2061-2061/com.google.android.exoplayer2.demo D/EventLogger:   ]
05-29 09:40:30.638 2061-2061/com.google.android.exoplayer2.demo D/EventLogger: ]
```

If no audio entry is available, then the container is most likely the issue. Otherwise, the codec is not supported.

**Comment by anandsingh2903** [comment]
How can i get this log about audio support as i am not getting any logs as shown above. Yes sometimes it give me something like unsupported video mime type but there's no logs for audio as such. do i need to implement something in EventLogger method.

**Comment by AquilesCanta** [comment]
The log attached above can be obtained by playing the media in the demo app.

**Comment by anandsingh2903** [comment]
can't play the media in the demo app. i am changing the links of HLS apple stream to my link in json file. but then HLS option doesn't load in the demo app.

**Comment by AquilesCanta** [comment]
Does it show a toast saying it failed to load? If so, then you possibly have an extra/missing comma/bracket.

**Comment by anandsingh2903** [comment]
Hi,

Asi played the HLS of my URL in demo App i am getting these in logs. and the audio is not coming.


06-09 09:20:44.187 828-1057/com.google.android.exoplayer2.demo W/VideoCapabilities: Unrecognized profile/level 1/32 for video/mp4v-es
    Unrecognized profile/level 32768/2 for video/mp4v-es
    Unrecognized profile/level 32768/64 for video/mp4v-es
06-09 09:20:44.193 828-1057/com.google.android.exoplayer2.demo W/VideoCapabilities: Unsupported mime video/mpeg
06-09 09:20:44.196 828-1057/com.google.android.exoplayer2.demo W/VideoCapabilities: Unrecognized profile/level 0/0 for video/mpeg2
    Unrecognized profile/level 0/2 for video/mpeg2
06-09 09:20:44.197 828-1057/com.google.android.exoplayer2.demo W/VideoCapabilities: Unrecognized profile/level 0/3 for video/mpeg2






Renderer:0 [
        Group:0, adaptive_supported=N/A [
          [X] Track:0, id=0, mimeType=video/avc, supported=YES
        ]
      ]
      Renderer:1 [
        Group:0, adaptive_supported=N/A [
          [ ] Track:0, id=1/129, mimeType=audio/ac3, channels=2, sample_rate=48000, language=hin, supported=NO_UNSUPPORTED_TYPE
        ]
      ]
      Renderer:2 [
        Group:0, adaptive_supported=N/A [
          [ ] Track:0, id=1/8219, mimeType=application/cea-608, supported=YES
        ]
      ]
      Renderer:3 [
06-09 09:20:44.296 828-828/com.google.android.exoplayer2.demo D/EventLogger:     Group:0, adaptive_supported=N/A [
          [X] Track:0, id=1/21, mimeType=application/id3, supported=YES
        ]
      ]
    ]

**Comment by AquilesCanta** [comment]
The logs indicate the audio is AC-3. It is not that common to find devices with AC-3 decoding. Your best shot at supporting it is using the ffmpeg extension, I think. Follow [these instructions](https://github.com/google/ExoPlayer/tree/dev-v2/extensions/ffmpeg) to build it, and it should just work.
