### ISSUE TITLE
Listening on play back progress

### ISSUE THREAD

**Issue by NitinSharma639** [google/ExoPlayer#4317]
Hello

I want to check the progress every second . Is there any method to check the progress of the playing video. I want to perform action when video is 50 percent complete

**Comment by tonihei** [comment]
You can query `player.getCurrentPosition()` to check the progress. And divide it by `player.getDuration()` to get the relative progress. Note that the duration may be `C.TIME_UNSET` as long as it is not known yet.

If you want to perform an action at a specific point in time, please consider using ExoPlayer's message sending options. For example by doing something like this:
```
player.createMessage(messageHandler)
  .setPosition(positionAt50Percent)
  .setHandler(callbackThreadHandler)
  .send();
```
Please have a look at the doc for [`PlayerMessage`](http://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/PlayerMessage.html) for further options.

**Comment by NitinSharma639** [comment]
Hello @tonihei 

I am using SimpleExoplayer library version 2.6.0. To update I have to change a lot of code .Can you suggest some solution.

**Comment by tonihei** [comment]
Unfortunately, this feature isn't available before 2.7.0. 

You can try to listen to the progress yourself (for example, by checking the current position every 500ms or so) and then do something once the required position is reached. 

Also, out of interest: What exactly makes you think that you'll to change a lot of code when upgrading? We usually try to keep as much of the API as possible when releasing new versions. The old API may be deprecated but should they still work as before.

**Comment by NitinSharma639** [comment]
Hello 

I have update the sdk to 2.8.1 but the event is working on some version of android but not all versions of android.

**Comment by tonihei** [comment]
Could you please more details and reproduction steps such that we can help you to find the issue?

Specifically, which "event" are you talking about? And what exactly is only working on some versions of Android? And which versions of Android?

**Comment by NitinSharma639** [comment]
Deleted the comment . Thanks for answer . Now its working properly. I will ask If i have any question.
