### ISSUE TITLE
HLS stucks when changing channel from server end directly.

### ISSUE THREAD

**Issue by anandsingh2903** [google/ExoPlayer#4318]
I am playing HLS m3u8 in exoplayer 2 and the video is working fine but when i change the channel from remote on server end itself then server starts providing me TS of new channel but my player stucks on old channel TS at the point where channel was changed but when i seek forward a little bit then the player changes the channel and starts playing new channel video. i can't seem to figure out how to solve this.

**Comment by AquilesCanta** [comment]
Is the server introducing a discontinuity tag?

**Comment by anandsingh2903** [comment]
No, i guess not. What value do i have to send through discontinuity tag?

**Comment by AquilesCanta** [comment]
No value is needed, the discontinuity tag is standalone. However, try to have the server include the discontinuity sequence number. This [post](https://medium.com/google-exoplayer/hls-playback-in-exoplayer-a33959a47be7) might provide useful pointers in general.

I'll close this thread now. Please fill the issue template if you run into any further issues, otherwise, I can only guess what's going on.

**Comment by anandsingh2903** [comment]
Ok, so i used discontinuity tag in my HLS stream and now when i am changing the channel, at first i am getting exception : Unable to connect to "hls_url" and then after 4-5 seconds channel changes in player also. then again i changed the channel and again same thing happened and when i changed the channel third time player gave me same error of unable to connect to hls url and then it gave same error again and again 4-5 times and then it gave playback failed exception.

I can't understand why this is happening.

**Comment by AquilesCanta** [comment]
This is probably because the server makes the url unavailable for 4-5 seconds when changing the content. Although this should be very easy to test using curl.

**Comment by anandsingh2903** [comment]
I think you are right. URL is not available for 4-5 seconds but what is happening when this error is coming again and again even after 4-5 sec and then playback fails?. what can be the possible reason of this happening

**Comment by anandsingh2903** [comment]
Still can't fix this. channel is changing 3-4 times but after that it stucks on the same channel and freezes and then gives playback error

**Comment by AquilesCanta** [comment]
Try using a bigger minLoadableRetryCount (see HlsMediaSource.Factory#setMinLoadableRetryCount). The current default is 3. If you observe the number of times the channel changes increases with this number, let us know.

**Comment by anandsingh2903** [comment]
ok so i tried increasing minLoadableRetryCount to 10 but now i observed that when i changed the channel it didn't change on player even once this time it got stucked on the first channel itself and i am getting data of new channel as my bandwidth is getting used but the player freezes on first channel until i seek forward or backward myself, then player plays new channel data.

**Comment by anandsingh2903** [comment]
and this time, i didn't got any unable to connect exception.

**Comment by anandsingh2903** [comment]
ok i tested it againby setting minLoadableRetryCount of 100 now,

when the channel changes player freezes and if i seek forward it starts playing new channel but if i don't seek forward and wait then after some random time like sometimes it takes 2 min and sometimes it took 12 sec and sometimes it took 4min to show the new channel and player starts playing and sometimes it just freezes and doesn't play new channel until i seek forward or backward.

**Comment by anandsingh2903** [comment]
I am not giving EXT-X-DISCONTINUITY-SEQUENCE tag in HLS. Playback stucks due to this?. Should i give EXT-X-DISCONTINUITY-SEQUENCE tag in HLS and at which point should i increment it. Can you please provide me a example or format or how show i insert discontinuity sequence tag

**Comment by AquilesCanta** [comment]
I don't have enough information to help you with this. It depends on what the server does when changing channels. Something that might help would be providing a series of playlist snapshots with a few channel changes in between. Regarding the discontinuity sequence, the [hls specification](https://tools.ietf.org/html/draft-pantos-http-live-streaming-23) provides a simple explanation.

**Comment by anandsingh2903** [comment]
Will get back to you after inserting discontinuity sequence and test the HLS.

**Comment by AquilesCanta** [comment]
In general, ExoPlayer works around it, but it is a good idea to add it anyway.
