### ISSUE TITLE
Will Exoplayer  support the 360-degree video in the future?

### ISSUE THREAD

**Issue by buptcoder** [google/ExoPlayer#432]
Hi,

I am investigating the 360 or panorama video player and I noticed that youtube has started to support the panorama video from this March.

So I am wondering that exoplayer will support the 360 degree video in the future?

Thanks!

**Comment by ojw28** [comment]
It's possible to build 360 video support on top of ExoPlayer, by rendering a spherical video into a GL texture and then presumably rendering that texture onto a sphere (I'm not familiar with the details). I don't think there are any near term plans to add support directly to the open source project.

**Comment by mjsibbald** [comment]
Yes working on it myself... Exoplayer is a good base to begin with. The rest of my framework is all opengl. Good stuff.

**Comment by buptcoder** [comment]
@mjsibbald  sounds amazing! Will you share your implementation in the future or any help for it?

**Comment by Ood-Tsen** [comment]
Hello @mjsibbald , do you have any 360 sample video ?

**Comment by Ood-Tsen** [comment]
Hi @buptcoder 

Google has release VR SDK.
https://github.com/googlevr/gvr-android-sdk

And in this sdk, it play video by using  [ExoPlayer](https://github.com/google/ExoPlayer) and also including an opengl renderer,

**Comment by buptcoder** [comment]
Great thanks! I  will check it right now.

**Comment by peteshort** [comment]
Hi @Ood-Tsen / @mjsibbald / everyone,

We are looking for a developer to create a VR video player for Gear VR which can handle 3GB videos (paid job). If you have the skills to do this, please contact me ASAP at admin@breakingfourth.com for the details.

Cheers,
Pete

**Comment by SrujithPoondla** [comment]
@Ood-Tsen if we want to develop a VR Player using ExoPlayer, are there any particular steps or methods we have to follow? If you have any info related to building a VR player using exoplayer please tell.

**Comment by tiger1990** [comment]
I have checked gvr-android-sdk sample,  Below are the modules i have implemented one by one.
 
In this (':samples:sdk-simplevideowidget') sample creator had provided its own widget and had not exposed full controls of child views.

Problems:
cancel click : take me from full screen back to normal screen, What if i have to go to previous app screen when i click cancel.

For some videos (.m3u8 hls stream video is not playing  (message pops up Error loading video.))

Sample 2:
 ':samples:sdk-videoplayer'  :: At first this sample shows me your device is incompatible, It is clearly visible it need daydream supported handset.

I was looking if google is planning to open-source what they have done in youtube. @ojw28 can you please help me out for this, If it is not open-source, your views or suggestions will be valuable for me.

**Comment by ojw28** [comment]
We plan to support 360, but we don't have an ETA at this point. We will not be able to provide guidance until we get around to adding official support.

**Comment by tiger1990** [comment]
@ojw28  I believe youtube is also using exoplayer and in exoplayer i have seen gvr extension, If you could give me some suggestion , how should i start building my own renderer on top of exoplayer.

**Comment by ojw28** [comment]
As per above, we are not able to provide guidance until we provide official support. We don't have sufficient time to do this currently.
