### ISSUE TITLE
Cannot access com.google.android.exoplayer2.offline.DownloadManager.Listener

### ISSUE THREAD

**Issue by ZohaibGhafoor** [google/ExoPlayer#4326]
whenever i call downloadTracker.addListner or downloadTracker.isDownloaded etc it gives me this error in my application.

Cannot access com.google.android.exoplayer2.offline.DownloadManager.Listener

**Comment by erdemguven** [comment]
Is this an exception? If so please share the whole exception message.

**Comment by ZohaibGhafoor** [comment]
@erdemguven i think not exception it gives me compile time error red line below downloadTracker.addListener. and whenever i try to hover my mouse on downloadTracker.addListener it shows me this error.

"Cannot access com.google.android.exoplayer2.offline.DownloadManager.Listener"

and whenever i try to compile it gives me this error

"error: cannot access DownloadManager
class file for com.google.android.exoplayer2.offline.DownloadManager not found"

**Comment by erdemguven** [comment]
Please make sure you followed the "Adding ExoPlayer as a dependency" instructions in https://google.github.io/ExoPlayer/guide.html.

**Comment by ojw28** [comment]
This sounds like an issue with your local setup rather than a problem with the library. As an additional point to @erdemguven 's point above, please make sure you're using version 2.8.0 or later.
