### ISSUE TITLE
Invalid position reported when playing static stream with SegmentTemplate.startNumber > 1

### ISSUE THREAD

**Issue by dmazar** [google/ExoPlayer#4327]
### Issue description
Player reports invalid position while playing static stream. Stream manifest is added below. Manifest is just exporting part of the larger stream and SegmentTemplate.startNumber is not 1.

### Reproduction steps
Unfortunately, stream is not available to the public, so it can not be reproduced by others. We can only post stream manifest, timeline build by the player and positions that player reports.

### Link to test content
Stream manifest:

    <?xml version="1.0" encoding="UTF-8"?>
    <MPD xmlns="urn:mpeg:dash:schema:mpd:2011" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" profiles="urn:mpeg:dash:profile:isoff-live:2011" type="static" minBufferTime="PT1S" xsi:schemaLocation="urn:mpeg:dash:schema:mpd:2011 DASH-MPD.xsd" mediaPresentationDuration="PT7802S">
      <Period start="PT0S">
        <AdaptationSet mimeType="video/mp4" startWithSAP="1" segmentAlignment="true" templateParsed="true">
          <SegmentTemplate timescale="1000" presentationTimeOffset="8681" duration="2000" startNumber="81975" media="$RepresentationID$_Segment-$Number$.m4v?playseek=20180530062459-20180530083501&amp;timezone=UTC&amp;hw_dash=1&amp;servicetype=3&amp;mount=1000001" initialization="20180528085231_$RepresentationID$_init.m4i?playseek=20180530062459-20180530083501&amp;timezone=UTC&amp;hw_dash=1&amp;servicetype=3&amp;mount=1000001"/>
          <Representation width="1024" height="576" frameRate="25" codecs="avc1.640029" scanType="progressive" id="Stream_2_1400000" bandwidth="1400000"/>
          <Representation width="1280" height="720" frameRate="25" codecs="avc1.640029" scanType="progressive" id="Stream_3_2400000" bandwidth="2400000"/>
          <Representation width="1280" height="720" frameRate="25" codecs="avc1.640029" scanType="progressive" id="Stream_4_3500000" bandwidth="3500000"/>
          <Representation width="480" height="270" frameRate="25" codecs="avc1.4d4029" scanType="progressive" id="Stream_0_500000" bandwidth="500000"/>
          <Representation width="640" height="360" frameRate="25" codecs="avc1.4d4029" scanType="progressive" id="Stream_1_900000" bandwidth="900000"/>
        </AdaptationSet>
        <AdaptationSet mimeType="audio/mp4" startWithSAP="1" lang="hrv" segmentAlignment="true" templateParsed="true">
          <SegmentTemplate timescale="1000" presentationTimeOffset="8681" duration="2000" startNumber="81975" media="$RepresentationID$_Segment-$Number$.m4a?playseek=20180530062459-20180530083501&amp;timezone=UTC&amp;hw_dash=1&amp;servicetype=3&amp;mount=1000001" initialization="20180528085231_$RepresentationID$_init.m4i?playseek=20180530062459-20180530083501&amp;timezone=UTC&amp;hw_dash=1&amp;servicetype=3&amp;mount=1000001"/>
          <Representation audioSamplingRate="48000" codecs="mp4a.40.2" id="Stream_5_128000" bandwidth="128000"/>
        </AdaptationSet>
      </Period>
    </MPD>

### Version of ExoPlayer being used
2.6.1 and 2.8.1

### Device(s) and version(s) of Android being used
Happens on all devices and Androids we had so far.

### A full bug report captured from the device

Player builds the following timeline:

    timeline: periods=1, wins=1
    - period 0: durationMs=7802000, posWinMs=0, winIdx=0
    - win 0: isDynamic=false, isSeekable=true, startMs=-9223372036854775807, durationMs=7802000, def posMs=0, presentationStartTimeMs=-9223372036854775807, firstPeriodIndex=0, lastPeriodIndex=0, posInFirstPeriodMs=0

But reports invalid position:

    getCurrentPosition() = 163947328
    getBufferedPosition() = 163952403
    getDuration() = 7802000

Any idea how to get correct position inside the window? We are not sure if the manifest is correct, but manifest is not under our control anyway and changing it may be challenging.

**Comment by ojw28** [comment]
> We are not sure if the manifest is correct, but manifest is not under our control anyway and changing it may be challenging.

I suspect the manifest in incorrect. My guess would be that the two `presentationTimeOffset` values in the manifest are wrong. They're probably the same as in the original full stream manifest, where-as they should probably be adjusted by the duration of media prior to the start of the part that's being played. In other words, I think `presentationTimeOffset` should be adjusted by `(81974 * 2000) = 163948000`.

**Comment by ojw28** [comment]
Note: The actual correct value for `presentationTimeOffset` depends on what the original non-zero `presentationTimeOffset`values were for. It might be that the correct value to use is `8681 + 163948000`, or it might be that using `163948000` directly is the correct value. Without having access to the media it's not possible to say.

**Comment by dmazar** [comment]
Thanks, it looks like you are right!

After adjusting presentationTimeOffset in overridden DashManifestParser by startNumber*duration, player can calculate correct position. Will do some more tests on different streams.

Thank you!

Edit:
It seems the correct fix for invalid manifest we are using is: presentationTimeOffset += (startNumber-1) * duration.
