### ISSUE TITLE
BehindLiveWindowException Exoplayer 2.8.1

### ISSUE THREAD

**Issue by jinfanzon** [google/ExoPlayer#4328]
I'm using the latest Exoplayer library. And I'm not able to decrease the number of BehindLiveWindowExceptions thrown. 

Our hls has 2 resolutions, and the .m3u8 file looks like:

`#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=576600,RESOLUTION=640x480,FRAME-RATE=25,CODECS="avc1.64001e,mp4a.40.2"
256_258/index.m3u8?sessId=12579
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=700552,RESOLUTION=720x540,FRAME-RATE=25,CODECS="avc1.64001e,mp4a.40.2"
257_258/index.m3u8?sessId=12579`

We've tried increasing the buffer to 120 seconds and the HLS segment size is 4 seconds.

I'll provide content url and full stacktrace to your inbox.

Regards

**Comment by AquilesCanta** [comment]
Hi @jinfanzon, there are [many issues](https://github.com/google/ExoPlayer/issues?q=is%3Aissue+BehindLiveWindowException) about BehindLiveWindow exceptions, and [some of them](https://github.com/google/ExoPlayer/issues/4009) include pointers on how to prevent it.

The logcat attached to the e-mail includes a PlaylistResetException which is an unrelated issue. It is thrown when the playlist tracker considers the server was reset. In this case, you can only re-prepare the player. Let me know if you have any specific questions.
