### ISSUE TITLE
Reading an mp4 from application resources

### ISSUE THREAD

**Issue by mjsibbald** [google/ExoPlayer#433]
When playing local resource videos with the dev branch fails for me.

E/ExoPlayerImplInternal﹕ Internal track renderer error.
    com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to android.resource://

Caused by: java.net.MalformedURLException: Unknown protocol: android.resource

I'm testing the demoplayer. So is there anything I'm missing in the ExtractorSampleSource or ExtractorRendererBuilder?

**Comment by eater2** [comment]
How do You format the url for the local file ?

**Comment by mjsibbald** [comment]
Mp4 h264. It’s working with online videos. but when I load from resource it’s not working.

**Comment by ojw28** [comment]
What's the actual use case for placing a video in the application resources? Can you put it in the assets directory instead? In which case you should be able to read it using AssetDataSource (not UriDataSource or DefaultHttpDataSource).

**Comment by mjsibbald** [comment]
i was just wondering why this changed from the master branch. It was possible to load from the android resource (raw). Guess I need to change to the asset folder?

Verstuurd vanaf mijn iPhone

**Comment by ojw28** [comment]
The whole model for playing MP4 has changed (from relying on MediaExtractor to instead relying on Mp4Extractor and ExtractorSampleSource). They use completely different code paths for loading data. So that probably accounts for the change in behavior.

**Comment by mjsibbald** [comment]
As long as its working better, it’s just a minor change for me. I’ll try this in the morning. 
Thanks for the feedback, saves me some hours to figure out something it wasn’t going to work anyways.

**Comment by mjsibbald** [comment]
You need to pass the assetmanager, so I did that. When I list the assets, it's showing my file(So I know it's there). Now to load the file using the AssetDataSource... I can't seem to get the right URI. I've tried: "file:///assets/" and "file:///android_asset/" But all it's saying is:  Failed to open file 'xxxxxxx.mp4'. (No such file or directory)
What am I missing?

**Comment by mjsibbald** [comment]
Just looked at the source...(facepalm)... just use "file:///xxxxxxx.mp4"

**Comment by eater2** [comment]
Reading MP4 video from local disk (video folder ie) - and not from the Asset , can be usefull if we want to pre-cache the videos and play them many times (as buffering works only for DASH).

**Comment by ojw28** [comment]
Closing this as it sounds like you have a solution.

**Comment by sasindroid** [comment]
@mjsibbald - I tried using "file:///xxxxxxx.mp4" but doesn't work. Can you please let me know how you succeeded with it? Thanks.

**Comment by sasindroid** [comment]
@mjsibbald - thanks. I got it sorted out. Should use "asset:///xxxxxxxxx.mp4" instead of "file:///xxxxxxx.mp4".

**Comment by mjsibbald** [comment]
Cool, just read the email.

Verstuurd vanaf mijn iPhone

**Comment by dlewanda** [comment]
My apologies if I'm dredging up an old issue, but we're facing the same problem here where we'd like the ExoPlayer to play files from the raw directory. We're using the same audio files for a couple different purposes in our app, one of which is to serve as a Notification reminder sound. It appears that there is no other option for the Notification's setSound but to use the `assets` folder. I'd really prefer not to have to duplicate the same files in both the `assets` and `raw` folders. Please let me know if I'm missing some way to refer to one or the other in either case.

**Comment by ojw28** [comment]
We recently added [RawResourceDataSource](https://github.com/google/ExoPlayer/blob/release-v2/library/src/main/java/com/google/android/exoplayer2/upstream/RawResourceDataSource.java) to v2, which will allow you to play files in the raw directory.

**Comment by dlewanda** [comment]
Thanks @ojw28 for the update. We are still on 1.5.7 at the moment. We'll definitely consider it when we move to v2 in the future.
