### ISSUE TITLE
android.media.MediaCodec field 'mNativeContext' is no longer declared in Android P

### ISSUE THREAD

**Issue by moacir69** [google/ExoPlayer#4330]
Good afternoon,
In Android P devices like the Google Pixel 2, the _android.media.MediaCodec_ field _mNativeContext_ is no longer declared and accessible through _MediaCodec.getClass().getDeclaredField("mNativeContext")_. Can you please tell me how can this field now be accessed? Is it declared in another class?
Warm regards,

Moacir Correia e Silva

**Comment by ojw28** [comment]
Application code shouldn't access internal platform components using reflection, and as of Android P the platform team are starting to enforce this. See [this blog post](https://android-developers.googleblog.com/2018/02/improving-stability-by-reducing-usage.html).

ExoPlayer doesn't access `mNativeContext` via reflection. If you're seeing this when using ExoPlayer then you're most likely using a custom fork of ExoPlayer, and you should report the issue to whoever provides this implementation. If you're using `mNativeContext` via reflection directly from your own application code, you should stop doing this.

**Comment by moacir69** [comment]
OK, thank you for the quick reply.
Kind regards,

Moacir Correia e Silva
