### ISSUE TITLE
EventListener isn't called in correct thread's looper

### ISSUE THREAD

**Issue by Khang-NT** [google/ExoPlayer#4332]
### Issue description
The document of method `Player#addListener` said:
> Register a listener to receive events from the player. **The listener's methods will be called on the thread that was used to construct the player. However, if the thread used to construct the player does not have a Looper, then the listener will be called on the main thread.**

I did construct new SimpleExoPlayer instance within my own Looper (which is not `Looper.mainLooper()`). But when I call `prepare()` media source on main thread, `ExoPlayer` callback to all listeners within main thread instead of using my looper to dispatch the event.

I can see the method [`ExoPlayerImpl#updatePlaybackInfo`](https://github.com/google/ExoPlayer/blob/2b55c91af0afd1f50f689adb1046f1cf78c887f6/library/core/src/main/java/com/google/android/exoplayer2/ExoPlayerImpl.java#L645-L692) invoke listener's methods within caller thread, regardless the thread was used to construct the player.

### Reproduction steps
- Create `HandlerThread` and then create `ExoPlayer` object within `HandlerThread#onLooperPrepared`
- Add a listener: `Player#addListener`
- Switch to main thread and call `Player#prepare`

### Link to test content
Can test with demo app.

### Version of ExoPlayer being used
**2.8.0**

**Comment by tonihei** [comment]
That's more or less working as intended. ExoPlayer also requires you to call all methods on the thread the player was created on (or the main thread if it doesn't have a looper). See also the points under "threading model" here: http://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/ExoPlayer.html.

The documentation is not as clear as it should be, and based on the discussion in #4278, we also just changed it to spell out the requirements more explicitly.

**Comment by ojw28** [comment]
Threading requirements were clarified in https://github.com/google/ExoPlayer/commit/2813c0699fef8a2e4df5a37534401cbdaa8af572. We'll also update the developer guide.

In addition, we're planning a change that will allow you to specify a `Looper` when instantiating the player, which will add a little more flexibility. Follow https://github.com/google/ExoPlayer/issues/4278 for updates.
