### ISSUE TITLE
Catch when media source is ended from ConcatenatingMediaSource

### ISSUE THREAD

**Issue by Anton111111** [google/ExoPlayer#4333]
This is a question. 
For example i create ConcatenatingMediaSource and add into it 3 MediaSources. How can i catch that first mediasource is ended ?

**Comment by tonihei** [comment]
Please have a look at [`EventListener.onPositionDiscontinuity`](http://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/Player.EventListener.html).
