### ISSUE TITLE
Concatenating Media Source loses window index when custom request headers added to data source

### ISSUE THREAD

**Issue by franklink** [google/ExoPlayer#4334]
I have an app which uses ConcatenatingMediaSource for the player's media source. Everything has been working flawlessly until I recently started hosting shows from my own server which require an "Authorization" header to play or gain access. This seems to work fine on its face but what I've found is that the media sources array that is passed into the ConcatenatingMediaSource constructor are scrambled or loaded in the incorrect order. Seeking to next window (track) will result in a random track from the media source being played.

This has been verified by trying media source lists which do not require the Authorization header versus ones which do. I can reproduce this at will.

Here is the code I am using to add request properties to my media source:

``DefaultHttpDataSourceFactory defaultHttpFactory = new DefaultHttpDataSourceFactory(Util.getUserAgent("myUserAgent"));
        if(track.getStreamURL().contains("mywebsite.com")) {
            defaultHttpFactory.getDefaultRequestProperties().set("Authorization", DatabaseConnection.getAuthorizationHeader(track.getStreamURL(), "GET", ""));
        }
        return new ExtractorMediaSource.Factory(defaultHttpFactory).createMediaSource(Uri.parse(track.getStreamURL()));``

Whenever the if block is reached, the resulting media source does not play nor seek correctly. I can only assume that there is some issue with loading the media source URI's in the background.

Please advise what the correct way to add an "Authorization" header might be when implementing a ConcatenatingMediaSource with the ExoPlayer. I have had nothing but a positive experience with this library until now.

Thanks in advance.

**Comment by tonihei** [comment]
That sounds really odd. But the way you set the authorization headers looks right.

Are you sure that your server is actually serving the right media with these headers? We could take a closer look but would need a way to reproduce this. Can you provide us with example media and reproduction steps? If don't want to post that publicly, you can also send it to dev.exoplayer@gmail.com quoting "Issue #4334" in the subject.
