### ISSUE TITLE
how to add player control ui in IO18 audio App demo.

### ISSUE THREAD

**Issue by bizkitj** [google/ExoPlayer#4338]
Hello ExoTeam

Thank you for such a great tool.

I am very new to android development. Please bear with me if I say something or do something stupid.

While I am following IO18 on youtube, especially the audio app part, I realize one thing, how do you pros add player control UI into this app?

e.g, while user tap on the notification, back to the MainActivity, there is nothing there, it's an empty screen, quesiton is, how do you add play control ui in here?

I have looked into https://github.com/googlesamples/android-UniversalMusicPlayer tyring to figure out this. However, the Universal Android Music Player Sample is using a giant notification (Not PlayerNotificationManager see on IO18)  and custom player ui (Not ExoPlayer out of box control UI) which is confusing me  a lot.

Please, please, please help. How to add player control ui in the following code,. If you can , please not only show me how you do it, I also need to know why did you do it? break into steps, As I am still on the path of learning. 

Thank you.
 
### Link to test content
https://github.com/bizkitj/MediaSessionExoPlayer/tree/ExoPlayerGoogleIO2018

### Version of ExoPlayer being used
`implementation 'com.google.android.exoplayer:exoplayer-core:2.8.0'
    implementation 'com.google.android.exoplayer:exoplayer-ui:2.8.0'
    implementation 'com.google.android.exoplayer:extension-mediasession:2.8.0'`

**Comment by ojw28** [comment]
This issue tracker is intended more for reporting issues with the library, rather than coding help. I'd suggest asking your question on StackOverflow. Sorry to not be more helpful, but we don't have sufficient time to answer this type of question.
