### ISSUE TITLE
Some streams fail with new TsExctractor

### ISSUE THREAD

**Issue by canatella** [google/ExoPlayer#434]
Since aed45bb2ca1a6e7b25a33cdc59ff1eb95c9c3a00, some streams are not played anymore. It seems on those streams, there is a  TS_STREAM_TYPE_DVB_AC3 track but it looks empty as the payload reader for that track is never read from. The player waits for all the renderers, the renderers waits for all tracks to have a format value and has there is no data in the DVB_AC3 track, the format method is never called by the Ac3Reader.

I don't now much about mpegts encoding, I suppose the stream is not correctly encoded, but it used to play.

**Comment by ojw28** [comment]
The immediate issue should be fixed. Adding DVB AC-3 support becomes a feature request.
