### ISSUE TITLE
Play/Pause button icons after end of file reached

### ISSUE THREAD

**Issue by strikemansan** [google/ExoPlayer#4349]
Hi
I have simple exo player view which show video. After video end's play button showing pause icon. How i can refresh play button after end of video in my DefaultEventListener?

Thanks

**Comment by ojw28** [comment]
We do this automatically as of 2.7.0, so it's likely you're using an older version. I'd suggest you update to a newer version to get this behavior.

**Comment by strikemansan** [comment]
@ojw28 Thanks for you reply
