### ISSUE TITLE
Getting estimated bitrate for HLS stream

### ISSUE THREAD

**Issue by myion8you** [google/ExoPlayer#435]
I'm in a situation where I need to get the bitrate for analytic purposes however I can't seen to find a working way.  The BandwidthMeter works for DASH streams but not HLS which is the format we are using.  Any help would be greatly appreciated.

**Comment by ojw28** [comment]
It definitely does on the dev branch. BandwidthMeter is used in the same way for HLS as it is for DASH.

**Comment by myion8you** [comment]
Odd because even in the demo bandwidth isn't being reported for HLS streams on master and dev.

**Comment by ojw28** [comment]
You'll need to provide more information about exactly what you're doing and what you're not seeing that you expect to see.

**Comment by myion8you** [comment]
I guess a more appropriate question is, How should I be getting the bitrate for the HLS stream?
