### ISSUE TITLE
Pause player after switch page in ViewPager

### ISSUE THREAD

**Issue by strikemansan** [google/ExoPlayer#4351]
Hi

I use simple exo player view as part of my recyclerView which contains video or photo.
My question: how i can stop video/recreate player after i switch page in PagerAdapter?

I used this in onPageChangedListener, but it doesn't always work

            _player.setPlayWhenReady(false);
            _player.getPlaybackState();
    

Thanks

**Comment by ojw28** [comment]
I don't really understand the question. In any case it's unclear whether this is an ExoPlayer question, as oppose to a general question about Android development. We (ExoPlayer) provide a player that can render into a `Surface`, and a few UI components to go along with it. How you integrate those components into your app's UI is probably beyond the scope of this issue tracker.
