### ISSUE TITLE
Build error related with project's gradle

### ISSUE THREAD

**Issue by workspace** [google/ExoPlayer#4353]
### Issue description
Got build error messages 
"exoplayer failed to resolve common", 
"Could not find common.jar (android.arch.core:common:1.0.0)." when I try to build ExoPlayer

### Reproduction steps
Just clone ExoPlayer repository and try to build

### Version of ExoPlayer being used
dev-v2 branch commit sha : cad3de91c92d835e3a438b39897115e992478196
Android Studio 3.1.2

However, I found solution which is very simple. Just change the orders of repositories in project's gradle file. After changing orders, it worked fine as I expected.

https://github.com/google/ExoPlayer/blob/dev-v2/build.gradle#L16
https://github.com/google/ExoPlayer/blob/dev-v2/build.gradle#L34

to
repositories {
    google() // make it first of order
    jcenter()
}

I don't know the reason that it is my own problem or some build tools's update affect to project.

**Comment by adesentenac** [comment]
I'm having the same issue, apparently some google artifacts disappeared from jcenter (support-core-ui:27.1.1, play-services-base-license:12.0.0...)

**Comment by ojw28** [comment]
Is this related to https://twitter.com/bintray/status/1004974875851685888? And do we expect it to resolve itself, or will we actually need to submit a change to swap the repository order around?

**Comment by adesentenac** [comment]
Yes, that seems related. It seems fixed now, I was able to build ExoPlayer from scratch again.
I'm not sure what's more reliable between google() and jcenter() to put first in build.gradle. I assume this kind of issue does not happen that often with jcenter().

**Comment by ojw28** [comment]
I think this was a transient issue. Closing.
