### ISSUE TITLE
MediaSessionConnector metadata update

### ISSUE THREAD

**Issue by loki666** [google/ExoPlayer#4356]
### Issue description
I don't know if the issue is in MediaSessionConnector or in https://github.com/googlesamples/android-media-controller,
But both disagree on the Metadata keys to use for the currently playing item.

`MediaSessionConnector::updateMediaSessionMetadata()` is using `MediaMetadataCompat.METADATA_KEY_DISPLAY_*` keys where the media controller app is looking for `MediaMetadataCompat.METADATA_KEY_TITLE` etc...

Should I add these keys myself in the `TimelineQueueNavigator::getMediaDescription()` implementation? Or am I missing sometinh

### Reproduction steps
Connect android-media-controller to a ExoPlayer MediaSessionConnector 
play something
android-media-controller doesn't display the metadata

### Version of ExoPlayer being used
version 2.8.1

**Comment by andrewlewis** [comment]
Please see #4292. As of two days ago we set both keys.

**Comment by loki666** [comment]
ok what about the other for the artist and the album ?

**Comment by andrewlewis** [comment]
Marc, could you comment any other relevant keys? Thanks!

**Comment by ojw28** [comment]
@loki666 - Can you be specific about exactly which keys you're referring to (i.e. list them all), so we can make sure we don't miss any? Thanks!

**Comment by loki666** [comment]
```
MediaMetadataCompat.METADATA_KEY_TITLE (String)
MediaMetadataCompat.METADATA_KEY_ARTIST (String)
MediaMetadataCompat.METADATA_KEY_ALBUM (String)
MediaMetadataCompat.METADATA_KEY_ALBUM_ART (Bitmap)
MediaMetadataCompat.METADATA_KEY_USER_RATING (RatingCompat)
MediaMetadataCompat.METADATA_KEY_RATING (RatingCompat)
```

**Comment by loki666** [comment]
why did I close this ???

**Comment by marcbaechinger** [comment]
We've added the interface MediaSessionConnector.MediaMetadataProvider which can be passed to the constructor of the MediaSessionConnector to provide custom metadata.

It's available in the dev-v2 branch.
