### ISSUE TITLE
Does exoplayer support MPEGA audio format in HLS Stream? if not, how can i play MPEGA audio format in my HLS Stream (playlist.m3u8)

### ISSUE THREAD

**Issue by anandsingh2903** [google/ExoPlayer#4357]
I am playing a playlist.m3u8 HLS Stream using exoplayer and the video is working fine but the audio is not coming in the HLS and as i have checked the audio format of HLS Stream. I think it's MPEGA (MPEG layer 1/2/3 format). how can i play the audio of this format in HLS Stream in exoplayer.

**Comment by ojw28** [comment]
Duplicate of #4313
