### ISSUE TITLE
Question - Exoplayer Privacy Policy

### ISSUE THREAD

**Issue by 0c6a183d** [google/ExoPlayer#4358]
Hi.

Is there a Privacy Policy that accompanies Exoplayer, or does it fall under the Google Privacy Policy?

Does Exoplayer feed back any usage information back to your Team or Google in general?

Thanks

**Comment by ojw28** [comment]
> Is there a Privacy Policy that accompanies Exoplayer, or does it fall under the Google Privacy Policy?

Google's open source projects are covered by the Google Privacy Policy.

> Does Exoplayer feed back any usage information back to your Team or Google in general?

ExoPlayer does not send any information back to Google. You can of course inspect the source code to verify this.

If you're using any of the extension modules then note that some of these depend on external libraries, and so you'd need to check on what those libraries do with respect to both of your questions, if this is a concern.
