### ISSUE TITLE
Expose language for audio/text tracks

### ISSUE THREAD

**Issue by ened** [google/ExoPlayer#437]
Given I want to use ExoPlayer.TrackInfo class to let a user select a subtitle / audio track
Then I would like to select the track by it's language.

Within `android.media.MediaPlayer.TrackInfo` (http://developer.android.com/reference/android/media/MediaPlayer.TrackInfo.html) this information is provided, but I was not able to find it in ExoPlayer.

**Comment by ojw28** [comment]
I don't think TrackInfo is the right class to be using. What's your use case (HLS / SmoothStreaming / DASH / SomethingElse), and where are your multiple tracks coming from? Thanks!

**Comment by ened** [comment]
My use case is to play offline files like MKV, Avi, MP4, whatever is stored on the device.
Also, I'm trying to integrate Exo into a DLNA renderer so it will play the same file via HTTP.

Basically replace MediaPlayer usage by ExoPlayer.

**Comment by Ood-Tsen** [comment]
Hi @ened ,

Currently, there are no mkv and avi extractors.
Are you using [MediaExtractor](http://developer.android.com/reference/android/media/MediaExtractor.html) ?

**Comment by ened** [comment]
Should be MediaExtractor as I'm using FrameworkSampleSource.

So the correct way would be to implement a custom MKV/AVI extractor?

**Comment by Ood-Tsen** [comment]
Yes @ened 
if TrackInfo comes from MediaExtractor , we have no chance to update it.

**Comment by Ood-Tsen** [comment]
Maybe we can use the funtion 'getTracks' in [DemoPlayer](https://github.com/google/ExoPlayer/blob/dev/demo/src/main/java/com/google/android/exoplayer/demo/player/DemoPlayer.java) to pass the languae ,
> public String[] getTracks(int type) {
>    return trackNames == null ? null : trackNames[type];
>  }

In the dash or smooth-streaming case, we can get the track name from  the manifest.
For the mp4 content, we have to parse the head of the file and pass it to the DemoPlayer.

**Comment by Ood-Tsen** [comment]
Hello @ened 
I just upload a simple example for [parse mp4 language header and show on demo app](https://github.com/Ood-Tsen/ExoPlayer/commit/b9b74fcbab00c6365aba8f5991487c3524361ce9)

The track's language can be read after download the mp4 heads.

**Comment by ened** [comment]
Hello @Ood-Tsen that looks quite good! Just tested & integrated your port. Thank you for this! By using MediaExtractor we also have a chance to read infos from all other formats a target device supports. Great.

**Comment by ened** [comment]
@Ood-Tsen will this be integrated into Exo?

**Comment by Ood-Tsen** [comment]
Hi @ened 
I can create a pull request,
but it should be after Google I/O.

**Comment by janegrytsenko** [comment]
@ened do you realize your own extractors for avi and other not supported yet formats?

**Comment by ened** [comment]
@janegrytsenko to retrieve the language? No. I'm not too sure how it could work despite being interested in it.

**Comment by janegrytsenko** [comment]
Sorry, I thought  you want to write custom extractors for different formats supporting (.avi, .mkv). I'm interested in it.

**Comment by ened** [comment]
@Ood-Tsen let's create the PR! :)

**Comment by ened** [comment]
@janegrytsenko https://github.com/Matroska-Org/jebml => this could be used / integrated to parse MKV

**Comment by janegrytsenko** [comment]
@ened thank you!

**Comment by ojw28** [comment]
Note that we've been enhancing the WebmExtractor to also parse MKV.

**Comment by janegrytsenko** [comment]
@ojw28 and what about .avi files? :)

**Comment by ened** [comment]
@Ood-Tsen will you still be able to help on this or do you need assistance?

**Comment by ojw28** [comment]
I'm unclear exactly where we are with this issue. In the dev branch a lot has changed since it was first raised. We're now exposing the MediaFormat of each track directly through the ExoPlayer interface. We populate the MediaFormat language when using FrameworkSampleSource (although please don't use FrameworkSampleSource unless you really need to), and also for text/subtitle tracks when using ExtractorSampleSource to play mp4 and fragmented mp4.

It will be trivial to support language for audio tracks for mp4 and fragmented mp4 too, if you can provide sample media that contains this type of track information. The same applies for audio and text tracks when playing MKV and WebM files using ExtractorSampleSource.

Please provide sample files if you have some, and we'll make these enhancements. Otherwise I propose closing this issue for now, until sample files can be provided. Thanks!

**Comment by ened** [comment]
Will provide samples to your Gmail address asap.

**Comment by ojw28** [comment]
The only remaining work here is to propagate language for audio tracks.

**Comment by ened** [comment]
This seems to be implemented now for subtitle tracks but not yet for audio tracks in MP4s (mime type is audio/mp4a-latm).
