### ISSUE TITLE
Does demo exoplayer uses ffmpeg extension for AC3 audio by default or do i need to implement ffmpeg extension by myself in demo app.

### ISSUE THREAD

**Issue by anandsingh2903** [google/ExoPlayer#4370]
Does demo exoplayer uses ffmpeg extension for AC3 audio by default or do i need to implement ffmpeg extension by myself in demo app.

**Comment by andrewlewis** [comment]
The demo app can use the ffmpeg extension. Please see the documentation for the [using extensions with the demo app](https://google.github.io/ExoPlayer/demo-application.html#including-extension-decoders).

**Comment by anandsingh2903** [comment]
Yes demo app can use the ffmpeg extension but i am asking do i need to implement the extension manually or demo app uses the ffmpeg by default for unsupported audio codecs like if i am playing AC3 audio in HLS and the audio is not coming. So, demo app is using ffmpeg already or i have to write some code for ffmpeg seperately to play AC3 audio.

**Comment by andrewlewis** [comment]
As described in the documentation linked above, the demo app won't use the ffmpeg extension unless the extension is built, the right build variant is used and the renderers are in the right order such that `FfmpegAudioRenderer` is used in preference to the audio renderers (if necessary). These don't involve writing code except possibly in the final step. If you haven't built the extension it won't be available.

**Comment by anandsingh2903** [comment]
Alright thanks
