### ISSUE TITLE
Enable software decoder extension to access platform DRM

### ISSUE THREAD

**Issue by unext-wendong** [google/ExoPlayer#4372]
Would like to talk about one feature request after seeing the post [Android Exoplayer Issues and Features Discussion](https://groups.google.com/forum/#!topic/cwip-discuss/SbnhwHvX7Ik) on CWIP group posted by the Widevine Team.

This is not part of the inconsistence between ExoPlayer and other players, but simply a feature that we hope can be added to the default ExoPlayer implementation.

Almost all of the newly released Android devices have Widevine DRM built in. For media applications, it's accessible through MediaDrm and MediaCodec API. This makes the deployment of Widevine based media services very easy on Android platform. And with ExoPlayer handling the interaction details with these APIs, it becomes even simpler for the service providers to apply Widevine.

However, because of how MediaDrm is implemented, its decrypt functionality is only exposed to MediaCodec in the native side. This is fine for applications that only use the platform decoders, but if a service has to use a software decoder of their own, e.g. the decoder extension in ExoPlayer, it's not easy then to apply Widevine or any other DRM schema that might be on the platform to their media.

We asked here one year ago if this was possible https://github.com/google/ExoPlayer/issues/2414. It seemed the application would have to build their own DRM module to do that.

This use case doesn't seem to be popular since we don't see anyone else asking about it here, even though it sounds quite reasonable to us. Looking at the implementation of ExoPlayer, it already has the ability to interact with the platform DRM and a structure for adding software decoder extensions, then won't it be great if these two can be connected? Well, it only makes sense if it's feasible.

One year ago, we needed to integrate the software decoder for Dolby audios into our player, and that was pretty straightforward thanks to the decoder extension structure in ExoPlayer. However, the problem was that we couldn't then protect these audio tracks using Widevine as we do to the video tracks and the other audio tracks. After asked the question here, we started to look for other options. Probably not designed for, but we noticed that the platform passthrough decoder could help achieve the task, as this decoder doesn't make any change to the passed in data and since it's accessed through MediaCodec the data going through would be decrypted. Functionally it's just like a decrypter.

Essentially, what we did was a) create a class to implement the SampleStream interface by simply passing the source samples through the passthrough decoder and b) wrap the orignal SampleStream passed to the extension renderer with the new class. It works well and we haven't noticed any performance issue. It's still being used in our service today.

There is a certain workaround nature in this solution, but hopefully it can help generate new ideas for a better solution. If needed, we can provide more information on the changes we did. Or if there is already a plan to support this, please also let us know.

Sorry for the long writing. Just wanted it to look convincing. However if due to the lack of general need for it, there will be no plan to support it, we understand.

**Comment by ojw28** [comment]
@jefftinker from Widevine is probably the right person to respond (or reassign as appropriate).

**Comment by ojw28** [comment]
@rrfrias - Are you the right person to comment on this?

**Comment by rrfrias** [comment]
I have opened an internal tracker to discuss and follow up.

**Comment by morganch01** [comment]
As discussed in #9137, it would be great if ExoPlayer can provide extension for both decryption or decoder, so that client would need less effort to integrate custom DRM.

**Comment by rrfrias** [comment]
Sorry, we lost track of this because it was not on the right hotlist. Will reevaluate the request. 

Internal ref: 158545155

**Comment by rrfrias** [comment]
This does allow for the potential that decrypted data is exposed to apps. While you find that the workaround resolves your immediate need, we cannot guarantee that this will continue to work in the future.
