### ISSUE TITLE
Pre-caching exoplayer

### ISSUE THREAD

**Issue by kakadiyahardik** [google/ExoPlayer#4373]
### Issue description
I am using SimpleExoPlayer for playing video that store in the cloud. I want to cache beginning part (1 MB) of the video so it will play smoothly in starting without buffering. for pre-caching video, I am using CacheUtil.cache() method but it's not working and not giving any error (If i give caching size less than video size then it's not working but if give caching size greater than video size then its working fine)
-> it's not caching partialy video
### Code
```
Thread thread = new Thread(new Runnable() {
  @Override
  public void run() {
    String videoUri = "video url";
    DataSpec dataSpec = new DataSpec(Uri.parse(videoUri), 0, 1 * 1024 * 1024, null);

    LeastRecentlyUsedCacheEvictor evictor = new LeastRecentlyUsedCacheEvictor(90 * 1024 * 1024);
    SimpleCache simpleCache = new SimpleCache(getCacheDir(), evictor);
    DataSource dataSource = buildMyDataSourceFactory().createDataSource();
    CacheUtil.CachingCounters counters = new CacheUtil.CachingCounters();
    try {
      CacheUtil.cache(dataSpec, simpleCache, buildDataSourceFactory().createDataSource(), counters);
      System.out.println("Done caching");
    } catch (Exception e) {
      System.out.println("Exception");
      e.printStackTrace();
    }
  }
});
thread.start();
```
### exoplayer version

exoplayer:2.6.0

**Comment by erdemguven** [comment]
Could you share the URL for the video you want to cache?

**Comment by kakadiyahardik** [comment]
http://dgtg95nrexj6j.cloudfront.net/cd929ce8-3063-4b6b-b49d-14386961616e_120px.mp4
This is the video URL

**Comment by erdemguven** [comment]
I tested your code and it works fine. 

One thing I noticed is you create the simpleCache in your thread. If you're creating another one out of the thread, this might cause problems. You should have only one instance of SimpleCache per cache folder.

**Comment by kakadiyahardik** [comment]
Can you send the code that you tested?
How to use cache after downloading because i am still not able to use the partially downloaded cache ( if i give cache size greater than the video in DataSpec then it's work)

### Here is my code for access cache in exoplayer


        dynamicConcatenatingMediaSource.addMediaSource(getVideoSource("video url"));
        player.prepare(dynamicConcatenatingMediaSource); // SimpleExoPlayer
        player.setPlayWhenReady(true);
 

private MediaSource getVideoSource(String videoUri) {

        DefaultBandwidthMeter bandwidthMeter = new DefaultBandwidthMeter();

        ExtractorsFactory extractorsFactory = new DefaultExtractorsFactory();

        return new ExtractorMediaSource(Uri.parse(videoUri), buildDataSourceFactory(), extractorsFactory, null, null);
    }

 public DataSource.Factory buildDataSourceFactory() {

        return new DataSource.Factory() {
            @Override
            public DataSource createDataSource() {
                LeastRecentlyUsedCacheEvictor evictor = new LeastRecentlyUsedCacheEvictor(90 * 1024 * 1024);

                SimpleCache simpleCache = new SimpleCache(getCacheDir(), evictor);

                DataSource dataSource = buildMyDataSourceFactory().createDataSource();
                return new CacheDataSource(simpleCache, dataSource, CacheDataSource.FLAG_BLOCK_ON_CACHE|CacheDataSource.FLAG_IGNORE_CACHE_ON_ERROR);
            }
        };
    }

private DefaultDataSource.Factory buildMyDataSourceFactory() {
        return new DefaultDataSourceFactory(this, "MyApp", new DefaultBandwidthMeter());
    }

**Comment by erdemguven** [comment]
There are two issues:
1- You create a new SimpleCache in your DataSource Factory. It recommended to use only one instance for downloading and playback.
2- The structure of your mp4 file. It has its moov box at the end of the file. So if the end of the file is missing then we can't play it. If you cache the end of the file too then the file plays fine:
```
DataSpec dataSpec = new DataSpec(Uri.parse(videoUri), 4 * 1024 * 1024, C.LENGTH_UNSET, null);
CacheUtil.cache(dataSpec, simpleCache, buildDataSourceFactory().createDataSource(), counters);
```
Another option is editing the file and somehow moving moov box to the beginning.
