### ISSUE TITLE
Does ima extension available in exo version 1 ?

### ISSUE THREAD

**Issue by RezaMortazavi** [google/ExoPlayer#4374]
I'm using exoplayer version 1 in my app:
`com.google.android.exoplayer:exoplayer:r1.5.9 `

for now i cant update it to V2..i wanted to add ima to player but it seems 
the repository not available for that version.
how can i include interactive media ad to my player?
thanks

**Comment by AquilesCanta** [comment]
No, unfortunately the IMA extension is not available on V1, and we are no longer working on V1 enhancements either.

> how can i include interactive media ad to my player?

It's possibly going to be easier to migrate to V2 than doing this on V1. The only thing I can suggest is defining what your requirements are and try to follow what V2 currently does, minus things you don't need. Ad insertion in ExoPlayer relies heavily on playlists, which are not supported by V1 so you'll probably not be able to do the same. I am sorry we can't be of much help here!

**Comment by andrewlewis** [comment]
You could also look at integrating with the IMA SDK directly. There are two main ways to do this: custom ad playback, where you control the player that shows ads, and SDK-owned player, in which IMA will create its own player for ads. The latter option is a bit less work and is [documented here](https://developers.google.com/interactive-media-ads/docs/sdks/android/).

Using IMA in this way requires more code than using the IMA extension and has some disadvantages (e.g., buffering when starting to play ads) but may be an option if you can't upgrade to V2.
