### ISSUE TITLE
FFMPEG extension didn't work for AC3 audio codec

### ISSUE THREAD

**Issue by anandsingh2903** [google/ExoPlayer#4377]
I have build the ffmpeg extension in demo app but the HLS which have AC3 audio codec still doesn't work. AC3 should be supported with FFMPEG extension right?. I have only build the exntension as shown in the instructions, do i need to something else also after building the extension? and how do i know that ffmpeg extension is now available to work after building. I can't see anything new in logs which can show me that FFMPEG extension is available and working.

**Comment by AquilesCanta** [comment]
Please see #4048.

**Comment by anandsingh2903** [comment]
Hi, i have also build ffmpeg extension in demo app for ac3 audio codec and i used COMMON_OPTIONS same as read me file with --enable-decoder=eac3 and --enable-decoder=ac3 and built the extension but the demo app still cannot play ac3 audio in HLS and i think that demo app is still using default audio codec renderer rather than Ffmpeg to decode audio even though demo app is using EXTENSION_MODE_PREFER by default.


I am not getting Loaded FFMPEGAUDIORENDERER in my logcat that means that my ffmpegaudiorenderer is not loading properly in demo app but i had successfully built the ffmpeg extension in demo app without any issues. can't seem to understand what is the problem here.
