### ISSUE TITLE
PlayerNotificationManager: Support forced updates

### ISSUE THREAD

**Issue by jossypaul** [google/ExoPlayer#4379]
MediaDescriptionAdapter is getting updated when there is a change in playback state. Let's say I want to update MediaDescriptionAdapter at some point without any playback state change. Is it possible?

**Comment by ojw28** [comment]
@marcbaechinger - Could we provide an `invalidate()` method on `PlayerNotificationManager` to allow forcing an update? I wonder whether we also need a similar API on any other components we have that allow the app to provide metadata?

**Comment by marcbaechinger** [comment]
invalidate() makes sense here and also for the MediaSessionConnector. Classic use case is when a bitmap which has been loaded asynchronously arrives the app wants to trigger an update.

**Comment by marcbaechinger** [comment]
We've added a public invalidate() method to the PlayerNotificationManager which allows you to trigger an update of the notification. It's on the dev-v2 branch. Please take a look.
