### ISSUE TITLE
ExtractorSampleSource should automatically detect the container format

### ISSUE THREAD

**Issue by ojw28** [google/ExoPlayer#438]
This makes it possible to avoid having to know the container type up front (which is currently required, since you have to inject the correct Extractor implementation into the ExtractorSampleSource constructor).

**Comment by srikieonline** [comment]
+1 
Similarly, are there any plans to detect HLS, SS and DASH content upfront - before we parse the manifest and build renderers. 

Is there a  timeline for auto-detection of container?

**Comment by zsmatyas** [comment]
+1
I would use it, too!

**Comment by ojw28** [comment]
@andrewlewis Is working on the ExtractorSampleSource side of things. Should be implemented relatively soon. We don't have any plans to auto-detect HLS/SS/DASH at this point in time.

**Comment by ojw28** [comment]
This is implemented in dev.

**Comment by Ood-Tsen** [comment]
Excellent !! , it's a huge improved for ExoPlayer.
