### ISSUE TITLE
SampleSource, MediaCodecAudioTrackRenderer,  ExoPlayer.Factory etc are not Found

### ISSUE THREAD

**Issue by TusharGogna** [google/ExoPlayer#4380]
### Issue description
My application is Live and was having an issue (IllegalStateException) [using version r1.5.1] which after reading several threads I realized that it was fixed in +2.x.x versions. So, I decided to migrate to the latest version.

I just migrated from version r1.5.1 to 2.7.0 and after that it is not able to find the following Classes and Methods:
Classes: SampleSource, MediaCodecAudioTrackRenderer, MediaCodecVideoTrackRenderer  ExoPlayer.Factory, CodecCounters, InitializationException,WriteException, MediaCodecTrackRenderer, TimeRange, TrackRenderer, DummyTrackRenderer, and few other classes.

Methods:  setSelectedTrack, getTrackCount, getTrackFormat, sendMessage, blockingSendMessage (in ExoPlayer) and few other methods.

I mean, were the names changed or these classes/methods were replaced with newer classes/methods?

### Reproduction steps
It is Compile time error which I explained above. 

### Version of ExoPlayer being used
compile 'com.google.android.exoplayer:exoplayer:2.7.0'

### Device(s) and version(s) of Android being used
Not relevant as it's compile time. 

### A full bug report captured from the device
In Kotlin Compiler:
symbol:   class MediaDrmCallback |  
symbol:   class MediaPresentationDescription |  
symbol:   class UtcTimingCallback |  
symbol:   class MediaDrmCallback |  
symbol: class TextRenderer |  
symbol:   class MediaDrmCallback |  
symbol:   class ManifestFetcher |  
symbol:   class MediaPresentationDescription |  
symbol:   class UriDataSource |  
symbol:   class MediaPresentationDescription |  
symbol:   class MediaDrmCallback |  
symbol:   class MediaPresentationDescription |  
symbol:   class UtcTimingElement |  
symbol:   class UtcTimingElement |  
symbol:   class StreamingDrmSessionManager |  
symbol:   class ExoPlayer |  
symbol:   class MediaCodecVideoTrackRenderer |  
symbol:   class MediaCodecAudioTrackRenderer |  
symbol:   class CodecCounters |  
symbol:   class Format |  
symbol:   class BandwidthMeter |  
symbol:   class MediaFormat |  
symbol:   class TrackRenderer |  
symbol:   class BandwidthMeter |  
symbol:   class Format |  
symbol:   class BandwidthMeter |  
symbol:   class CodecCounters |  
symbol:   class ExoPlaybackException |  
symbol:   class Format |  
symbol:   class Cue |  
symbol:   class TimeRange |  
symbol:   class Format |  
symbol:   class Format |  
symbol:   class Cue |  
symbol:   class Format |  
symbol:   class Format |  
symbol:   class Format |  
symbol:   class Format |  
symbol:   class TimeRange |  
symbol: class MediaCodecAudioTrackRenderer |  
symbol:   class SampleSource |  
symbol:   class SampleSource |  
symbol:   class SampleSource |  
symbol: class MediaDrmCallback |

**Comment by ojw28** [comment]
ExoPlayer changed significantly between V1 and V2 (i.e. there were major architectural changes). That's why the package name changed. So it's not possible to update your dependency to V2 and have everything just continue to work.

It's quite old now, but [this blog post](https://medium.com/google-exoplayer/exoplayer-2-x-new-package-and-class-names-ef8e1d9ba96f) describes some of the changes that were made.

**Comment by TusharGogna** [comment]
Oh alright, thanks for the time and link. I will look into it. So basically, it's going to be a painful process to migrate now.
