### ISSUE TITLE
What is the buffering policy for precaching next song with ConcatenatingMediaSource? Is there any api for customising that, lets say I want to prefetch next song as soon as current song is played 10 second.

### ISSUE THREAD

**Issue by harshitwynk** [google/ExoPlayer#4382]
I want to start precahing next song in ConcatenatingMediaSource when the current song is played 10 second(or any other duration).How can I achieve that? 
By default exoplayer starts precahing when current song is near its end.
Moreover what is the precahing policy, like can I define how many segments to precache for next song?

**Comment by tonihei** [comment]
Unfortunately, that's currently not possible, and already tracked by #3327.
