### ISSUE TITLE
No getController()

### ISSUE THREAD

**Issue by dzboot02** [google/ExoPlayer#4385]
Simply, how to get the controller from the PlayerView, the controller variable is there privately, but no way to access it.

**Comment by ojw28** [comment]
We could add a `getController` method if it makes sense to do so, but what's the use case that this would be needed for? Thanks!

**Comment by dzboot02** [comment]
Because of this:


```
   @Override
   public void onBackPressed() {

      if (playerView.getControllerView().isVisible()) {
         playerView.hideController();
      } else {
         super.onBackPressed();
      }
   }
```

Hide the controller when users pressed back button and the controller is visible. There is no way to access this method from the playerView. That's where I needed it, for me, maybe other things for other users.

**Comment by ojw28** [comment]
That makes sense; thanks! I think we'd prefer to just expose a `PlayerView.isControllerVisible` method, or similar. Would that work for you?

**Comment by dzboot02** [comment]
Not for me. When I encountered this problem, I just used ExoPlayer locally, and I changed it as I needed.
I don't know if this would be enough, people may need other things in the future, but you do what you have to do for your excellent library to work flawlessly :)

**Comment by ojw28** [comment]
I don't think we want to expose the whole controller through `PlayerView`. We'll add `isControllerVisible` for now, which should do what you need.
