### ISSUE TITLE
ExoPlayer not working with AndroidX?

### ISSUE THREAD

**Issue by ghost** [google/ExoPlayer#4387]
### Issue description
Compilation failed to complete:
`Program type already present: android.support.v4.app.INotificationSideChannel$Stub
Message{kind=ERROR, text=Program type already present: android.support.v4.app.INotificationSideChannel$Stub, sources=[Unknown source file], tool name=Optional.of(D8)}`

dependencies {
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner :1.1.0-alpha3'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.0-alpha3'
    
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlinVersion"
    implementation 'com.google.android.material:material:1.0.0-alpha3'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.2'
    implementation 'com.google.android.exoplayer:exoplayer-core:2.7.3'
    implementation 'com.google.android.exoplayer:exoplayer-ui:2.7.3'
}

### Version of ExoPlayer being used
2.7.3

**Comment by ojw28** [comment]
Are you sure this is related to using ExoPlayer? People seem to encounter the error you refer to who are not using ExoPlayer. For example: https://github.com/material-components/material-components-android/issues/110. Does that help?

**Comment by ghost** [comment]
It seems ExoPlayer does not work with androidx packages. I decided not to use the androidx packages, no more problems

**Comment by ojw28** [comment]
Perhaps some of the dependencies ExoPlayer has on the (old) support library don't mix well with the (new) androidx libraries. In which case this issue will be resolved by ExoPlayer migrating to use androidx dependencies.

**Comment by ghost** [comment]
Thanks for answer!

**Comment by ojw28** [comment]
Turns out you can use libraries that use the (old) support library with the (new) androidx libraries. See [here](https://github.com/google/ExoPlayer/issues/4484#issuecomment-403600793) for details.
