### ISSUE TITLE
How to stop at a specific time?

### ISSUE THREAD

**Issue by darkjun99** [google/ExoPlayer#4388]
Hello.
I want to make my users watch a specific span repeatedly.
Now I implemented this with seekTo() and Handler().postDelayed methods.
What my code do is
seek to a start position, play a video, and stop after a specific time.
However, this approach is not reliable when users' internet connection is bad.
It usually stops early because of downloading, buffering, or something.
I want to know that is there any other approach I can do?
Or should I add that feature to ExoPlayer?
If that's the case, please let me know how I can do, and where to start.
Any tips would be greatly appreciated because I'm not familiar with the ExoPlayer library.
Thank you very much.

**Comment by andrewlewis** [comment]
You can prepare the player with a `ClippingMediaSource` wrapping your content media source to play a portion of a stream between specified start/end points, and use `player.setRepeatMode(Player.REPEAT_MODE_ALL)` to loop the clip repeatedly.
