### ISSUE TITLE
Is it possible to disable all notifications for a DownloadService?

### ISSUE THREAD

**Issue by laurencedawson** [google/ExoPlayer#4389]
ExoPlayer v2.8.1

I'm currently trying to setup ExoPlayer to cache a few videos in the background using the DownloadService. However, when I extend DownloadService I'm still seeing progress updates for download. Is there a way to disable all updates as I handle these internally.

Thanks

**Comment by erdemguven** [comment]
Displaying notification is necessary to keep the service alive if the app goes to background. I can add an option to disable it but you should call service.startForeground(...) yourself if you can to keep the service alive.

**Comment by laurencedawson** [comment]
That would be great thanks. I'm using it to pre cache videos so it's not
essential that all downloadeds are completed.

**Comment by ojw28** [comment]
Closing as fixed.
