### ISSUE TITLE
Can exoplayer play dash video with audio/video both in same file

### ISSUE THREAD

**Issue by rashmichaudhari** [google/ExoPlayer#439]
Hi, I have dash video chunks created using mp4box which have both audio and video in same chunk.
I was referring to demo app of exoplayer, but all samples in demo app have different segmentLists for audioChunkSource and videoChunkSource. 
 As i have single segmentlist for both audio and video, I tried using same segmentList for audio and video renderer, which lead to exception
 "Internal runtime error.
  java.lang.NullPointerException
  	at android.media.MediaFormat.getInteger(MediaFormat.java:282)
  	at com.google.android.exoplayer.audio.AudioTrack.reconfigure(AudioTrack.java:363)
  	at com.google.android.exoplayer.audio.AudioTrack.reconfigure(AudioTrack.java:344)
  	at com.google.android.exoplayer.MediaCodecAudioTrackRenderer.onOutputFormatChanged(MediaCodecAudioTrackRenderer.java:173)
  	at com.google.android.exoplayer.MediaCodecTrackRenderer.drainOutputBuffer(MediaCodecTrackRenderer.java:825)
  	at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:487)
  	at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:422)
  	at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:211)
  	at android.os.Handler.dispatchMessage(Handler.java:98)
  	at android.os.Looper.loop(Looper.java:136)
  	at android.os.HandlerThread.run(HandlerThread.java:61)
  	at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:43) "

Also, if I pass only video renderer to player, video plays smoothly without audio.

Stream info of my dash chunck using ffprobe is 
{ [STREAM]
index=0
codec_name=h264
codec_long_name=H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
profile=unknown
codec_type=video
codec_time_base=1/32000
codec_tag_string=avc1
codec_tag=0x31637661
width=640
height=360
has_b_frames=2
sample_aspect_ratio=0:1
display_aspect_ratio=0:1
pix_fmt=unknown
level=-99
timecode=N/A
id=N/A
r_frame_rate=32000/2
avg_frame_rate=0/0
time_base=1/16000
start_pts=N/A
start_time=N/A
duration_ts=0
duration=0.000000
bit_rate=N/A
nb_frames=N/A
nb_read_frames=N/A
nb_read_packets=N/A
DISPOSITION:default=0
DISPOSITION:dub=0
DISPOSITION:original=0
DISPOSITION:comment=0
DISPOSITION:lyrics=0
DISPOSITION:karaoke=0
DISPOSITION:forced=0
DISPOSITION:hearing_impaired=0
DISPOSITION:visual_impaired=0
DISPOSITION:clean_effects=0
DISPOSITION:attached_pic=0
TAG:language=und
TAG:handler_name=VideoHandler
[/STREAM]
[STREAM]
index=1
codec_name=aac
codec_long_name=AAC (Advanced Audio Coding)
profile=unknown
codec_type=audio
codec_time_base=1/22050
codec_tag_string=mp4a
codec_tag=0x6134706d
sample_fmt=fltp
sample_rate=22050
channels=1
bits_per_sample=0
id=N/A
r_frame_rate=0/0
avg_frame_rate=0/0
time_base=1/22050
start_pts=N/A
start_time=N/A
duration_ts=0
duration=0.000000
bit_rate=N/A
nb_frames=N/A
nb_read_frames=N/A
nb_read_packets=N/A
DISPOSITION:default=0
DISPOSITION:dub=0
DISPOSITION:original=0
DISPOSITION:comment=0
DISPOSITION:lyrics=0
DISPOSITION:karaoke=0
DISPOSITION:forced=0
DISPOSITION:hearing_impaired=0
DISPOSITION:visual_impaired=0
DISPOSITION:clean_effects=0
DISPOSITION:attached_pic=0
TAG:language=und
TAG:handler_name=SoundHandler
[/STREAM]
}

Is there any way i can use same segmentList for playing dash??

PS: I checked stream info of AUDIO chunks from http://www-itec.uni-klu.ac.at/dash/ddash/mpdGenerator.php?segmentlength=6&type=full, MP4 dash chunk for AUDIO representation in this example had stream 0 as audio stream, whereas in my example stream 0 is video and stream 1 is audio.. Can this be source of problem..??

**Comment by ojw28** [comment]
ExoPlayer only supports DASH using demuxed (i.e. single track) fragmented mp4. Having audio and video muxed in the same stream has many disadvantages with respect to flexibility, and no real advantages that I can think of. So you should have mp4box output demuxed streams instead.

**Comment by rashmichaudhari** [comment]
okay.. Are you thinking to bring support for muxed streams in future, or already ruled it out?

**Comment by ojw28** [comment]
It's very low priority, because all major streaming services we know of that are moving to DASH are (rightly) using de-muxed streams.

**Comment by bascel** [comment]
One note on the use-case of muxed mp4 in DASH: This makes sense when using DASH over broadcast, where only one quality representation is used anyway. There, separate video/audio segments only make things more complicated, and (depending on the system design) might require an extra delay of the playback, increasing with the segment duration.
But i admit that it is not the typical use-case for DASH, and adaptive HTTP streaming in general.

**Comment by Marco-ST** [comment]
Hi

Is there any improvment on this ticket?
Actually I am facing the same issue.
Cheers
Marco

**Comment by ojw28** [comment]
No. The use cases for this seem to be pretty niche to me. It's nearly always better to deliver audio and video separately.

**Comment by Marco-ST** [comment]
Hi Oliver
Thanks a lot for your quick answer

In fact It is quite used I think when broadcast live are encoded in realtime with mpeg dash.

I am facing same problem actually with a customer that can’t play some mp4 file with video and audio in same file…

The mpd is like this :


<?xml version="1.0"?>



<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" minBufferTime="PT1.500000S" type="static" mediaPresentationDuration="PT0H2M31.85S" profiles="urn:mpeg:dash:profile:isoff-live:2011">

 <ProgramInformation moreInformationURL="http://gpac.sourceforge.net">

  <Title>dashevc-live-2s-4k.mpd generated by GPAC</Title>

  <Copyright>Provided by 4Ever Project; Distributed under Creative Common (CC BY NC ND); Generated by GPAC MP4Box - GPAC version 0.5.2-DEV-rev40-gd978dd3-master</Copyright>

 </ProgramInformation>


 <Period duration="PT0H2M31.85S">

  <AdaptationSet segmentAlignment="true" maxWidth="3840" maxHeight="2160" maxFrameRate="60" par="16:9" lang="und">

   <SegmentTemplate timescale="60" media="dashevc-live-2s-$RepresentationID$n$Number$.m4s" startNumber="1" duration="118" initialization="dashevc-live-2s-$RepresentationID$n.mp4"/>

   <Representation id="v9" mimeType="video/mp4" codecs="hvc1.1.6.L153.90" width="3840" height="2160" frameRate="60" sar="1:1" startWithSAP="1" bandwidth="10598669">

   </Representation>

   <Representation id="v10" mimeType="video/mp4" codecs="hvc1.1.6.L153.90" width="3840" height="2160" frameRate="60" sar="1:1" startWithSAP="1" bandwidth="13539471">

   </Representation>

   <Representation id="v11" mimeType="video/mp4" codecs="hvc1.1.6.L153.90" width="3840" height="2160" frameRate="60" sar="1:1" startWithSAP="1" bandwidth="18363977">

   </Representation>

  </AdaptationSet>

  <AdaptationSet segmentAlignment="true" lang="fr">

   <SegmentTemplate timescale="24000" media="dashevc-live-2s-$RepresentationID$n$Number$.m4s" startNumber="1" duration="46707" initialization="dashevc-live-2s-$RepresentationID$n.mp4"/>

   <Representation id="a1" mimeType="audio/mp4" codecs="mp4a.40.1" audioSamplingRate="24000" startWithSAP="1" bandwidth="129483">

    <AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2"/>

   </Representation>

  </AdaptationSet>

 </Period>

</MPD>%




Any hint is welcome
But your prompt answer is really appreciated!
Thanks again !

Cheers
Marco

**Comment by ojw28** [comment]
On what evidence are you basing your statement that it's commonly used? To effectively deliver DASH content the broadcaster should be taking the feed and transcoding it into multiple qualities for delivery. It looks like they're already doing this, from the manifest you provide. They should demux the audio and video into separate streams at the same time, and deliver them as separate components. This shouldn't be too difficult, and the broadcasters that we've worked with directly all do this. There are multiple benefits in doing this.

Note also that many Android devices wont be capable of playing 18Mbit/s 4K 60fps video streams. Unless they're targeting very specific devices, they'll need to be providing lower resolution 30fps transcodes as well.

**Comment by Marco-ST** [comment]
In fact I just rely on what customer give me in the hands to get it working :)

But I fully agree with you actually…

I am working on device that can do 4K/60fps/10bits actually (for TV market)

Cheers

**Comment by Marco-ST** [comment]
Hi

I succeed to decode 4K streams with MPEG DASH and Exoplayer ! Great!

For my personal stuff, do you have a readme file or something like that provide the list of parameters we can set when launching exoplayer from command line?
Thanks in advance.

Cheers
Marco


From: Marco <marc.chappellier@st.com<mailto:marc.chappellier@st.com>>
Date: Thursday 24 September 2015 18:09
To: google/ExoPlayer <reply@reply.github.com<mailto:reply@reply.github.com>>, google/ExoPlayer <ExoPlayer@noreply.github.com<mailto:ExoPlayer@noreply.github.com>>
Subject: Re: [ExoPlayer] Can exoplayer play dash video with audio/video both in same file (#439)

In fact I just rely on what customer give me in the hands to get it working :)

But I fully agree with you actually…

I am working on device that can do 4K/60fps/10bits actually (for TV market)

Cheers
