### ISSUE TITLE
 M3u8 Not Playing after first ts segment.

### ISSUE THREAD

**Issue by Akash1034** [google/ExoPlayer#4390]
Hi all,

I have been trying to play a m3u8 file with segments having byte ranges. The file works smoothly till end if no action is performed(pause/play). But when pausing and playing the file, it doesn't play or even when you seek the audio, it doesn't resumes. This is happening only in case of **audio**.

The issue can be reproduced by playing the file for more than 10 secs(each segment is 10 secs), and then pause/play the file. The issue can also be reproduced by seeking the file as well.

When debugged, found that when the first segment is playing(around first 10 secs), any action(pause/play) can be done it works fine, but when the second segment is loaded after that no actions can be done as the exoplayer stuck and never recovers. The Exoplayer stays in **STATE_BUFFERING** state and doesn't recovers to **STATE_READY** state after first segment is over and any action is performed after it(After first segment).

On further debugging, we found that **TsExtractor** class was not able to extract the segments as the **payloadReader** was getting **NULL** after first segment, might be **tsPayloadReaders** is not working properly. There could be a issue with the m3u8 file as well.

There's no further clue to solve this issue, kindly help me resolving this issue. 
Exoplayer version: **r2.2.0** . Tried on 2.6.0 and 2.8.1 also, but facing the same issue.

**Comment by AquilesCanta** [comment]
Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

**Comment by koshtubh1095** [comment]
Hi @AquilesCanta ,

### Issue Description: 

I have been trying to play a m3u8 file(audio) with segments having byte ranges. The file works smoothly till end if no action is performed(pause/play). But when pausing and playing the file, it doesn't play or even when you seek the audio, it doesn't resumes. This is happening only in case of audio which is m3u8 format. Sample audio M3u8 file has been attached in previous comment done by @Akash1034 .



### Reproduction steps:

The issue can be reproduced by playing the file for more than 10 secs(each segment is 10 secs), and then pause/play the file. The issue can also be reproduced by seeking the file as well.

When debugged, found that when the first segment is playing(around first 10 secs), any action(pause/play) can be done it works fine, but when the second segment is loaded after that no actions can be done as the exoplayer stuck and never recovers. The Exoplayer stays in STATE_BUFFERING state and doesn't recovers to STATE_READY state after first segment is over and any action is performed after it(After first segment).


**Please find the pseudo code through which we are trying to play the audio**:

_To initiate the player_:
private void initPlayer() {

        trackSelector = new DefaultTrackSelector();
        renders=renderer();
        exoPlayer = ExoPlayerFactory.newInstance(renders, trackSelector, new CustomLoadControl(new DefaultAllocator(true, C.DEFAULT_BUFFER_SEGMENT_SIZE), 50000,50000,5000,10000,10000, true));
        exoPlayer.addListener(mlistener);
    }

_To prepare the player_:

public void prepare() {
 exoPlayer.prepare(buildMediaSource(Uri.parse(mUrl),""),true,true);
 }

_To pause the audio_:
public void pause(long posMs) {
        exoPlayer.setPlayWhenReady(false);
        Logger.d("Constant", posMs);
}

_To play the audio_:
public void play(String url,long posMs,int peerId) {
        mUrl = url;
         command= SpConstants.ACTION_PLAY;
        _peerId=peerId;
        exoPlayer.setPlayWhenReady(false);
        prepare();
        exoPlayer.seekTo(posMs);
}


### Version of exoplayer used:
Tried with 2.2.0, 2.6, 2.8.1.

### P.S  :
For more details refer to the statement above provided by @Akash1034 . Please ping in comments for any further clarifications.

**Comment by koshtubh1095** [comment]
Hey,

things are working fine now. We fixed this issue by removing the seekTo and setting player to ready as true while resuming the content after pause and its working fine now.
So probably this issue can be closed.

Thanks
