### ISSUE TITLE
How to put sliding gestures on player screen to control volume.

### ISSUE THREAD

**Issue by anandsingh2903** [google/ExoPlayer#4393]
I want to put a feature in exoplayer which will enable the user to slide up on player screen to increase volume and slide down to decrease volume. how can i achieve that?.

**Comment by tonihei** [comment]
That's a very generic Android question and better asked on sites like StackOverflow or similar. 

For setting the volume - there's `SimpleExoPlayer.setVolume` (and also `.getVolume`) to achieve that.
