### ISSUE TITLE
Stuck in BUFFERING after changing quality.

### ISSUE THREAD

**Issue by EusebioMorell** [google/ExoPlayer#4394]
### Issue description

Playing a specific HLS stream on the ExoPlayer demo app, the video freezes shortly after start, and player state gets stuck at BUFFERING, even if having > 30 seconds video buffer.

Expected behaviour should be not entering BUFFERING state, or just resuming playback, since video buffer is OK.

### Reproduction steps

I provided a link to the HLS master playlist that reproduces the issue.

This HLS stream consists of several representations, each one with 2 alternative URLs (I assume this is for backup, so I will name them "normal" and "backup" URLs). Also, in the "normal" and "backup" media playlists, the values of the #EXT-X-MEDIA-SEQUENCE tag are really out of sync (I'm not sure if this violates the HLS spec, or might be related to the issue).

I have found that the issue happens after ExoPlayer changes video quality several times. If the selected URL just happens to change between a "normal" and "backup" one, back and forth, several times, then video playback may freeze and ExoPlayer gets stuck in BUFFERING state, or else keeps playing but reported video buffer is really huge.

To reproduce the issue I recommend downloading the master playlist, performing custom changes and (for example) serving it from a PC.

I have verified that when all URLs are of the same kind ("normal" or "backup"), the problem doesn't happen.

You can remove most representations and URLs, to increase the chances of ExoPlayer jumping between "normal" and "backup" URLs.

### Link to test content

https://nhkworld.webcdn.stream.ne.jp/www11/nhkworld-tv/global/263941/live_wa_s.m3u8

### Version of ExoPlayer being used

I tested ExoPlayer demo apps, versions: 2.6.0 and 2.8.1

### Device(s) and version(s) of Android being used

Device: BQ Aquaris U Plus.
Android: 6.0.1.

### A full bug report captured from the device

I attach the output from the "adb bugreport" command: [bugreport.zip](https://github.com/google/ExoPlayer/files/2115611/bugreport.zip)

**Comment by AquilesCanta** [comment]
We have an internal fix for a similar condition. Once we push to GitHub, a reference to the commit will appear here. Once it's available, please try to reproduce and let us know if it's still a problem. Thanks for reporting.

**Comment by EusebioMorell** [comment]
Thanks for the quick answer. I'm glad to help.

**Comment by ojw28** [comment]
Please could you test with the fix ref'd above, which is now on our dev branch, and confirm whether or not it fixes the issue.

**Comment by EusebioMorell** [comment]
I'm testing the commit right now. Unfortunately, video still freezes. It behaves the same as I described.

**Comment by AquilesCanta** [comment]
I am finding it really hard to reproduce.

Would it be possible for you to get a log of the HTTP requests done by the player along with a logcat for that same run? That would be a good starting point for me to diagnose the issue.

> I have verified that when all URLs are of the same kind ("normal" or "backup"), the problem doesn't happen.

This is really strange to me, since the playlist pairs seem to match perfectly (including segments). 

> the values of the #EXT-X-MEDIA-SEQUENCE tag are really out of sync

I couldn't find any misalignment between any of the media sequences. Is it possible that the server is introducing changes to the playlists?

I'll leave the stream playing in the hopes of reproducing the issue, but we will need help from you to diagnose this, unfortunately. I will update the issue if I find anything else.

**Comment by EusebioMorell** [comment]
Attached a full Android Studio console logcat, and a shorter log with just the EventLogger messages (including HTTP requests): [logs-01.zip](https://github.com/google/ExoPlayer/files/2123400/logs-01.zip)

As you will see in the logs, I used a custom master playlist. I just removed most renditions from the original playlist, to increase the chances of requesting a "backup" stream.

My custom master playlist is:

    #EXTM3U
    #EXT-X-VERSION:3
    #EXT-X-INDEPENDENT-SEGMENTS
    #EXT-X-STREAM-INF:BANDWIDTH=1298000,AVERAGE-BANDWIDTH=1298000,CODECS="avc1.4d401f,mp4a.40.5",RESOLUTION=1280x720,FRAME-RATE=29.970
    https://nhkwtvglobal-i.akamaihd.net/hls/live/263941/nhkwtvglobal/index_1180.m3u8
    #EXT-X-STREAM-INF:BANDWIDTH=1298000,AVERAGE-BANDWIDTH=1298000,CODECS="avc1.4d401f,mp4a.40.5",RESOLUTION=1280x720,FRAME-RATE=29.970
    https://b-nhkwtvglobal-i.akamaihd.net/hls/live/263941-b/nhkwtvglobal/index_1180.m3u8
    
    #EXT-X-STREAM-INF:BANDWIDTH=990000,AVERAGE-BANDWIDTH=990000,CODECS="avc1.42c01e,mp4a.40.5",RESOLUTION=640x360,FRAME-RATE=29.970
    https://nhkwtvglobal-i.akamaihd.net/hls/live/263941/nhkwtvglobal/index_900.m3u8
    #EXT-X-STREAM-INF:BANDWIDTH=990000,AVERAGE-BANDWIDTH=990000,CODECS="avc1.42c01e,mp4a.40.5",RESOLUTION=640x360,FRAME-RATE=29.970
    https://b-nhkwtvglobal-i.akamaihd.net/hls/live/263941-b/nhkwtvglobal/index_900.m3u8

About the misaligned media sequences, I'm getting values like this from the media playlists themselves:

    $ curl -s https://nhkwtvglobal-i.akamaihd.net/hls/live/263941/nhkwtvglobal/index_1180.m3u8 | grep MEDIA-SEQUENCE
    #EXT-X-MEDIA-SEQUENCE:45944
    
    $ curl -s https://b-nhkwtvglobal-i.akamaihd.net/hls/live/263941-b/nhkwtvglobal/index_1180.m3u8 | grep MEDIA-SEQUENCE
    #EXT-X-MEDIA-SEQUENCE:46544
    
    $ curl -s https://nhkwtvglobal-i.akamaihd.net/hls/live/263941/nhkwtvglobal/index_900.m3u8 | grep MEDIA-SEQUENCE
    #EXT-X-MEDIA-SEQUENCE:45944
    
    $ curl -s https://b-nhkwtvglobal-i.akamaihd.net/hls/live/263941-b/nhkwtvglobal/index_900.m3u8 | grep MEDIA-SEQUENCE
    #EXT-X-MEDIA-SEQUENCE:46544

I hope this is of any help. Let me know if you need further info / more logs.

**Comment by AquilesCanta** [comment]
I think that the backup playlists are not properly synchronized with the main ones.

This is what I did:
```
curl https://nhkwtvglobal-i.akamaihd.net/hls/live/263941/nhkwtvglobal/index_1180.m3u8
#EXTM3U
#EXT-X-VERSION:4
#EXT-X-TARGETDURATION:7
#EXT-X-MEDIA-SEQUENCE:47823
#EXT-X-PROGRAM-DATE-TIME:2018-06-21T23:46:21.932Z
#EXTINF:6.00600,
20180618T155919/index_1180/00015/index_1180_02823.ts
#EXT-X-PROGRAM-DATE-TIME:2018-06-21T23:46:27.938Z
#EXTINF:6.00600,
20180618T155919/index_1180/00015/index_1180_02824.ts
#EXT-X-PROGRAM-DATE-TIME:2018-06-21T23:46:33.944Z
#EXTINF:6.00600,
20180618T155919/index_1180/00015/index_1180_02825.ts
#EXT-X-PROGRAM-DATE-TIME:2018-06-21T23:46:39.950Z
#EXTINF:6.00600,
20180618T155919/index_1180/00015/index_1180_02826.ts
#EXT-X-PROGRAM-DATE-TIME:2018-06-21T23:46:45.956Z
#EXTINF:6.00600,
20180618T155919/index_1180/00015/index_1180_02827.ts
#EXT-X-PROGRAM-DATE-TIME:2018-06-21T23:46:51.962Z
#EXTINF:6.00600,
20180618T155919/index_1180/00015/index_1180_02828.ts
#EXT-X-PROGRAM-DATE-TIME:2018-06-21T23:46:57.968Z
#EXTINF:6.00600,
20180618T155919/index_1180/00015/index_1180_02829.ts
#EXT-X-PROGRAM-DATE-TIME:2018-06-21T23:47:03.974Z
#EXTINF:6.00600,
20180618T155919/index_1180/00015/index_1180_02830.ts
#EXT-X-PROGRAM-DATE-TIME:2018-06-21T23:47:09.980Z
#EXTINF:6.00600,
20180618T155919/index_1180/00015/index_1180_02831.ts
#EXT-X-PROGRAM-DATE-TIME:2018-06-21T23:47:15.986Z
#EXTINF:6.00600,
20180618T155919/index_1180/00015/index_1180_02832.ts
```

and

```
curl https://b-nhkwtvglobal-i.akamaihd.net/hls/live/263941-b/nhkwtvglobal/index_1180.m3u8
#EXTM3U
#EXT-X-VERSION:4
#EXT-X-TARGETDURATION:7
#EXT-X-MEDIA-SEQUENCE:48423
#EXT-X-PROGRAM-DATE-TIME:2018-06-21T23:46:24.532Z
#EXTINF:6.00600,
20180618T145919/index_1180/00016/index_1180_00423.ts
#EXT-X-PROGRAM-DATE-TIME:2018-06-21T23:46:30.538Z
#EXTINF:6.00600,
20180618T145919/index_1180/00016/index_1180_00424.ts
#EXT-X-PROGRAM-DATE-TIME:2018-06-21T23:46:36.544Z
#EXTINF:6.00600,
20180618T145919/index_1180/00016/index_1180_00425.ts
#EXT-X-PROGRAM-DATE-TIME:2018-06-21T23:46:42.550Z
#EXTINF:6.00600,
20180618T145919/index_1180/00016/index_1180_00426.ts
#EXT-X-PROGRAM-DATE-TIME:2018-06-21T23:46:48.556Z
#EXTINF:6.00600,
20180618T145919/index_1180/00016/index_1180_00427.ts
#EXT-X-PROGRAM-DATE-TIME:2018-06-21T23:46:54.562Z
#EXTINF:6.00600,
20180618T145919/index_1180/00016/index_1180_00428.ts
#EXT-X-PROGRAM-DATE-TIME:2018-06-21T23:47:00.568Z
#EXTINF:6.00600,
20180618T145919/index_1180/00016/index_1180_00429.ts
#EXT-X-PROGRAM-DATE-TIME:2018-06-21T23:47:06.574Z
#EXTINF:6.00600,
20180618T145919/index_1180/00016/index_1180_00430.ts
#EXT-X-PROGRAM-DATE-TIME:2018-06-21T23:47:12.580Z
#EXTINF:6.00600,
20180618T145919/index_1180/00016/index_1180_00431.ts
#EXT-X-PROGRAM-DATE-TIME:2018-06-21T23:47:18.586Z
#EXTINF:6.00600,
20180618T145919/index_1180/00016/index_1180_00432.ts
```

Then I got two segments that correspond to similar points in time.


index_1180_02829.ts  -> #EXT-X-PROGRAM-DATE-TIME:2018-06-21T23:46:57.968Z

and

index_1180_00428.ts -> #EXT-X-PROGRAM-DATE-TIME:2018-06-21T23:46:54.562Z

that should be around three seconds apart. Then I obtained the first few PTSs from the video streams. This yields:

```
$ dvbsnoop -s ts -if index_1180_02829.ts -tssubdecode  -N 300 481 | grep pts -i
PTS: 83331275 (0x04f788cb)  [= 90 kHz-Timestamp: 0:15:25.9030]
```

and:

```
$ dvbsnoop -s ts -if index_1180_00428.ts -tssubdecode  -N 300 481 | grep pts -i
PTS: 407114735 (0x184413ef)  [= 90 kHz-Timestamp: 1:15:23.4970]
```

From the [spec](https://tools.ietf.org/html/draft-pantos-http-live-streaming-23#section-6.2.4):

> Matching content in Variant Streams MUST have matching timestamps. This allows clients to synchronize the media.

So I'm inclined to think that the media is not aligned properly. I had also noticed some differences in the EXT-X-PROGRAM-DATE-TIME tags before, but couldn't observe again. Either I messed up (highly possible) or the server is doing changes. Also the low sequence number in the segment names makes me think the second option is a possibility. Anyway, if you find evidence pointing at ExoPlayer behaving incorrectly, let us know.

Extra point: I am not sure why your app is adapting automatically to the back up playlist, since it has the same bitrate as the first one. I'd expect the default apaptive track selection to not select it. Unless you are overriding the track selection, which would explain the behavior.

**Comment by EusebioMorell** [comment]
I'm not touching the track selection, actually.

To find out why it's choosing the backup stream first, i've just added some log messages in AdaptiveTrackSelection, SlidingPercentile and DefaultBandwidthMeter.

Here is the trace: [trace-01.zip](https://github.com/google/ExoPlayer/files/2128094/trace-01.zip).

I used my custom master playlist, as before:

    #EXTM3U
    #EXT-X-VERSION:3
    #EXT-X-INDEPENDENT-SEGMENTS
    #EXT-X-STREAM-INF:BANDWIDTH=1298000,AVERAGE-BANDWIDTH=1298000,CODECS="avc1.4d401f,mp4a.40.5",RESOLUTION=1280x720,FRAME-RATE=29.970
    https://nhkwtvglobal-i.akamaihd.net/hls/live/263941/nhkwtvglobal/index_1180.m3u8
    #EXT-X-STREAM-INF:BANDWIDTH=1298000,AVERAGE-BANDWIDTH=1298000,CODECS="avc1.4d401f,mp4a.40.5",RESOLUTION=1280x720,FRAME-RATE=29.970
    https://b-nhkwtvglobal-i.akamaihd.net/hls/live/263941-b/nhkwtvglobal/index_1180.m3u8
    
    #EXT-X-STREAM-INF:BANDWIDTH=990000,AVERAGE-BANDWIDTH=990000,CODECS="avc1.42c01e,mp4a.40.5",RESOLUTION=640x360,FRAME-RATE=29.970
    https://nhkwtvglobal-i.akamaihd.net/hls/live/263941/nhkwtvglobal/index_900.m3u8
    #EXT-X-STREAM-INF:BANDWIDTH=990000,AVERAGE-BANDWIDTH=990000,CODECS="avc1.42c01e,mp4a.40.5",RESOLUTION=640x360,FRAME-RATE=29.970
    https://b-nhkwtvglobal-i.akamaihd.net/hls/live/263941-b/nhkwtvglobal/index_900.m3u8

I hope this throws some light on this issue.

**Comment by AquilesCanta** [comment]
The only possibility I can think of is that some urls are getting blacklisted. In any case, the issue with alignment is not something we can work around. It might make sense for you to make sure that track selections never pick a back up url that are known to have a different alignment. One way of achieving this would be providing your own track selection implementation or overriding the default track selector.
