### ISSUE TITLE
Does ExoPlayer have full screen PlayerControl template for audio

### ISSUE THREAD

**Issue by thisd** [google/ExoPlayer#4395]
Hi, I wonder if ExoPlayer has an .xml template that supports audio or I need to create it myself. I am talking about the one available in audio players with the cover art covering 2/3 of the screen and playback controls (play, previous, next, shuffle, etc.) covering the rest. Something like this:

http://static.freemake.com/blog/wp-content/uploads/2013/11/Poweramp.png

Thank you.

Edit: I think I have realized that what I wanted is the PlayerView which incorporates the PlayerControl. I will confirm this and close this right after.

**Comment by tonihei** [comment]
Our PlayerView is already able to display controls and cover art (if provided as metadata in the file). Did you try using that?

**Comment by thisd** [comment]
Thanks tonihei. It seems like I have originally though. Thanks for confirming, though.
