### ISSUE TITLE
ANR on some devices when changing Surface during playback

### ISSUE THREAD

**Issue by aarondib** [google/ExoPlayer#4397]
### Issue description
ANR on some devices after setting Surface during playback.

### Reproduction steps
During video playback set Surface to "null" and after creating new Surface set a new one. Video will not scaled correctly (small picture on the left-upper corner with the rest space in green). Then ANR on player.release().

### Link to test content
Any  video.

### Version of ExoPlayer being used
Used versions: 2.6.1 and 2.8.1.

### Device(s) and version(s) of Android being used
1)
Model: INVIN X2 (s905x018)
Manufacturer: Amlogic
Board: s905x018
Hardware: amlogic
Android: 6.0.1

2)
Model: x96 (p212)
Manufacturer: Amlogic
Board: p212
Hardware: amlogic
Android: 6.0.1

**Comment by tonihei** [comment]
Sounds like a problem similar to #4006 or #3724.

There is workaround filter which we can activate for these devices. See [here](https://github.com/google/ExoPlayer/blob/2b55c91af0afd1f50f689adb1046f1cf78c887f6/library/core/src/main/java/com/google/android/exoplayer2/video/MediaCodecVideoRenderer.java#L1172).
For that, it would be great if you can tell use the decoder name which causes the problem and the exact value of Build.DEVICE and/or Build.MODEL.

**Comment by ojw28** [comment]
It looks like `p212` and `s905x018` are the `Build.DEVICE` values, so we can add those to the workaround. I'll do this as part of #4468.

**Comment by aarondib** [comment]
@ojw28 that would be great, thanks!
