### ISSUE TITLE
When will the "Skip Silence" feature be released?

### ISSUE THREAD

**Issue by fusionseek** [google/ExoPlayer#4401]
Dear Sir/Madam,

Glad to e-meet with you here.

Based on your response to this question, https://github.com/google/ExoPlayer/issues/2635 saying that the "Skip Silence" feature has been built to the dev-v2 branch, then I'd like to know, when will this feature be released? Is there a specific date?

Looking forward to your kind response.

Thank you very much for the support!

Best,
Raymond at Castbox

**Comment by tonihei** [comment]
It's already released.  As mentioned in #2635 you can turn it on with:
```
player.setPlaybackParameters(
    new PlaybackParameters(/* speed= */ 1, /* pitch= */ 1, /* skipSilence= */ true));
```
