### ISSUE TITLE
how to get download progress and downloaded size in activity

### ISSUE THREAD

**Issue by RicardoJiang** [google/ExoPlayer#4402]
ExoPlayer v2.8.1

hello,I'm using DownloadService and DownloadManager to download hls videos,may I ask
how to get download progress and downloaded size in activitys,I can get these in Downloadservice,
but you used startService and not bindService ,so how to get these in activitys expect broadcast.

thanks

**Comment by erdemguven** [comment]
If you keep a reference to your DownloadManager in a static field (like com.google.android.exoplayer2.demo.DemoApplication#downloadManager) then you can access it from your activity. You can use DownloadManager.getTaskState() or getAllTaskStates() method to get the progress information. Note, you should be accessing DownloadManager from the same thread as DownloadService which is the main (UI) thread.
