### ISSUE TITLE
Suspicious null in method overload

### ISSUE THREAD

**Issue by Manuiq** [google/ExoPlayer#4403]
In overloaded `cache` method instead of passing `@Nullable AtomicBoolean isCanceled` argument this method just passes `null` next. So now modifying the AtomicBoolean doesn't cancel the caching.
https://github.com/google/ExoPlayer/blob/000f3f23056aae30a98ac74fb30e484844548b3e/library/core/src/main/java/com/google/android/exoplayer2/upstream/cache/CacheUtil.java#L135

**Comment by tonihei** [comment]
That looks indeed suspicious. @erdemguven Can you take a look?

**Comment by andrewlewis** [comment]
My bad in a0b15595f45cb500d30017cd0d1fe0ac38d218e9. I'll make a fix to use the passed in flag. Thanks for reporting this.
