### ISSUE TITLE
OOM issue caused at om.google.android.exoplayer2.upstream.DefaultAllocator.allocate(DefaultAllocator.java:102)

### ISSUE THREAD

**Issue by harini113** [google/ExoPlayer#4405]
When I try to play a 4K clip with exoplayer based V2 Release, I see the images are distorted and the logcat shows OOM memory/memory allocation errors. The clip is in /sdcard/Music. This happens only with certain 4K clips.

LoadTask: OutOfMemory error loading stream
06-15 05:26:22.500  7182  7207 E LoadTask: java.lang.OutOfMemoryError: Failed to allocate a 65552 byte allocation with 41576 free bytes and 40KB until OOM, max allowed footprint 100663296, growth limit 100663296
06-15 05:26:22.500  7182  7207 E LoadTask: 	at com.google.android.exoplayer2.upstream.DefaultAllocator.allocate(DefaultAllocator.java:102)
06-15 05:26:22.500  7182  7207 E LoadTask: 	at com.google.android.exoplayer2.source.SampleQueue.preAppend(SampleQueue.java:622)
06-15 05:26:22.500  7182  7207 E LoadTask: 	at com.google.android.exoplayer2.source.SampleQueue.sampleData(SampleQueue.java:546)
06-15 05:26:22.500  7182  7207 E LoadTask: 	at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readSample(Mp4Extractor.java:515)
06-15 05:26:22.500  7182  7207 E LoadTask: 	at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:191)
06-15 05:26:22.500  7182  7207 E LoadTask: 	at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:860).

This is on SDK 28. I am currently unable to share mediafiles/logcat in public forum. 

Thanks

**Comment by tonihei** [comment]
Can you please send an example media file to dev.exoplayer@gmail.com with subject "Issue #4405"? This would allow us to reproduce the problem.

**Comment by harini113** [comment]
Done. Sent an email.

**Comment by tonihei** [comment]
The stream you sent by mail only has a resolution of 320x180 - which isn't 4K ;) 
It also plays fine in our demo app without using any unusual amount of memory.

**Comment by harini113** [comment]
Hi Yes, while I agree its not a 4K clip but with the latest exoplayer lib used in my apk I am finding issue even with that. I am hoping for some kind of direction to debug this further. Is that possible or do you need anyfurther info on the code?

**Comment by tonihei** [comment]
Did you try playing the same file in our demo app on this device? If it plays fine in the demo app,  then it's probably an issue with your app.

**Comment by harini113** [comment]
Will update this thread once I try it. Thanks

**Comment by harini113** [comment]
Yes the demo app works but with my app even with changes from 2.8.2 I hear audio but now on video it is just black screen. Iearlier had a routine setDisplay which used sendmessage to set the surface. Now with this apk deprecated, I am not sure how to proceed

Thanks

**Comment by tonihei** [comment]
That's seems totally unrelated to the OOM error above.

But in general, the deprecated methods should still work. You can try switching to the new `player.createMessage(...).send()` setup. Or if you just want to set the surface, please consider using `SimpleExoPlayer.setVideoSurface` or `.setVideoTextureView` or `.setVideoSurfaceView`.

**Comment by harini113** [comment]
I switched to createMessage with the following

PlayerMessage message =
_exoplayer.createMessage(_videoRenderer).setType(C.MSG_SET_SURFACE).setPayload(surface);


and when I play my clip the screen is black and errors out with status
being set to STATE_BUFFERING

**Comment by tonihei** [comment]
Did you send the message with `message.send()`?

**Comment by tonihei** [comment]
Closing for now, as we didn't receive any information for the original problem. Please reopen if you sent further information as requested.

**Comment by harini113** [comment]
PlayerMessage message = _exoplayer.createMessage(_videoRenderer).setType(C.MSG_SET_SURFACE).setPayload(surface);
        PlayerMessage msg;
        boolean block = false;

        try {
             msg = message.send();
            block = message.blockUntilDelivered();
            Log.i(TAG, "block = " + block);
