### ISSUE TITLE
Switching between AdaptiveTrackSelection and FixedTrackSelection

### ISSUE THREAD

**Issue by pstambrecht** [google/ExoPlayer#4409]
Is it possible to switch from AdaptiveTrackSelection to FixedTrackSelection without player re-initialisation? 

When I use AdaptiveTrackSelection I can not force higher video track (quality always depends on internet connection speed). When I use FixedTrackSelection adaptive quality selection not working (correctly). Does exist any TrackSelection which combines AdaptiveTrackSelection and FixedTrackSelection? What is the best way how to switch between them without re-initialisation?

Thanks.

**Comment by tonihei** [comment]
If you are using [`DefaultTrackSelector` ](http://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/trackselection/DefaultTrackSelector.html), you can specify track selection overrides there (see the linked doc). If the override contains just one track, `DefaultTrackSelector` automatically creates a `FixedTrackSelection` for that. As soon as more than one track is allowed, it creates an `AdaptiveTrackSelection`. This all happens on the fly during playback without re-initialisation.

**Comment by tonihei** [comment]
You can also look at #2250 and #2371 which are about the potential rebuffer that occurs when setting a new SelectionOverride. There is currently no easy way to get around that.

**Comment by pstambrecht** [comment]
@tonihei Thanks a lot for your answers. I'll try it.
