### ISSUE TITLE
how to cache an mp4 when using DefaultRendererBuilder

### ISSUE THREAD

**Issue by kherink** [google/ExoPlayer#441]
I'd like to cache the media (eg: http://html5demos.com/assets/dizzy.mp4 from samples) on the disk to avoid multiple downloads.
I think that this would be easy enough if this sample used the SmoothStreamingRendererBuilder or DashRendererBuilder where i could decorate the UriDataSource as a CacheDataSource. However, I am struggling to find a good way of doing something similar when using the DefaultRendererBuilder.
What is the correct way to approach this?

**Comment by nzer** [comment]
There's more versatile cache in development (hopefully)

**Comment by ojw28** [comment]
This is tracked by #420
