### ISSUE TITLE
4K Video of MP4 Format was not playing in the Exoplayer

### ISSUE THREAD

**Issue by DM-Android2017** [google/ExoPlayer#4410]
### Issue description
When try to play the 4k mp4 format video in the Exoplayer, it will play the audio alone and not the video it  shows the black screen.Is that exoplayer will play the video of 24fps alone?

### Reproduction steps
Just try to load the sample 4K Video (MP4 Format) in the Exoplayer

### Link to test content
http://osc.techaffinity.com/mobile/test/Honey%20Bees%2096fps%20In%204K%20(ULTRA%20HD)(4ksamples.com).mp4
Sample video uploaded in our server

### Version of ExoPlayer being used
Latest and 2.0.4

### Device(s) and version(s) of Android being used
Nexus 7 Tablet  2013 Model - Android v 6.0.1
Android TV Box- MINIX - Android v 6.0.1

### A full bug report captured from the device
It just play the 4K audio alone not video. no content in the logcat related to it.

**Comment by tonihei** [comment]
The file above doesn't work as it has a size of 0 bytes. Can you try to reupload the file or send it to dev.exoplayer@gmail.com with "Issue #4410" in the subject?

**Comment by ojw28** [comment]
Closing due to lack of information.
