### ISSUE TITLE
Closed Captions windowColor drawing inconsistencies 

### ISSUE THREAD

**Issue by BetweenTwoBits** [google/ExoPlayer#4412]
### Issue description
Noticed that window color doesn't always render the same way depending on the caption type.

On a stream with ttml+xml captions, the windowColor(Green) draws like this:
![full_width_window_color](https://user-images.githubusercontent.com/3139045/41746583-13cfa6fe-7568-11e8-8f1f-8f0efabe65f1.png)

On a stream with cea-608 captions, the windowColor(Green) draws like this:
![short_window_color](https://user-images.githubusercontent.com/3139045/41746586-151000ae-7568-11e8-9d26-92bd655658f3.png)

### Reproduction steps
Set system caption options:

Accessibility->Captions->On->Caption style->Custom->Caption window color->Any color
Playing the assets in the linked test content.

### Link to test content
ttml+xml Asset
http://rdmedia.bbc.co.uk/dash/ondemand/elephants_dream/1/client_manifest-all.mpd

cea-608 Asset
N/A (Asset used is internal and can't be shared 😢 )

### Version of ExoPlayer being used
2.8.1

### Device(s) and version(s) of Android being used
Pixel C, Android 8.1.0

### A full bug report captured from the device
N/A

**Comment by ojw28** [comment]
The content is able to define the window region, so I think it's expected that the filled area might be different?

**Comment by BetweenTwoBits** [comment]
As I understand it, this content is missing all styling attributes. I am not sure if that is how the window region is defined, but I can take a look to ensure its not the content doing this.

**Comment by ojw28** [comment]
Closing this for now, because it's unclear that there's anything actionable for us to do. Please reply here if you're able to be more concrete about the issue. Thanks!
