### ISSUE TITLE
DRM streams failed on Asus Zenfone2 

### ISSUE THREAD

**Issue by hongfeih** [google/ExoPlayer#4413]
### Issue description
Got color bars when playing DRM streams on Asus Zenfone2

### Reproduction steps
Using the ExoPlayer demo app to play any DRM streams

### Link to test content
N/A

### Version of ExoPlayer being used
2.8.1

### Device(s) and version(s) of Android being used
Asus Zenfone2 (ASUS_Z00AD), Android 5.0

### A full bug report captured from the device
[asus_drm_failed.log](https://github.com/google/ExoPlayer/files/2128449/asus_drm_failed.log)
![asus_drm_failed](https://user-images.githubusercontent.com/2166532/41788303-3a21392e-7619-11e8-9104-4c038df643cc.jpeg)

**Comment by tonihei** [comment]
@hongfeih Could you try to capture a full [bugreport](https://developer.android.com/studio/debug/bug-report) and not just the log output?

@paf-wv Please take a look. It looks like a device issue where the device can't handle the change in resolution.

**Comment by tonihei** [comment]
We will push a workaround which forces to use Widevine L3 on this device. Though not ideal, it helps to get around this issue.

**Comment by paf-wv** [comment]
@hongfeih have you been able to play back clear content of the same encode that was WV DRM protected?  Just trying to determine if it is a platform issue that fails on resolution change as @tonihei pointed out.
Also, I have asked for a rep to reach out to Asus for assistance.

**Comment by ojw28** [comment]
Not sure if this is clear already, but since the output paths are different for non-secure and secure playbacks, I think it's possible for issues around resolution changes to only affect one path or the other (and I think we've seen this on other devices in the past).

**Comment by hongfeih** [comment]
@paf-wv we've tried clear contents in exoplayer demo, all worked. And we saw playback of first 10 seconds clear content of that DRM protected stream. 
@ojw28 I think you're right, Will try this, but no way to fix it instead of a workaround?

**Comment by ojw28** [comment]
We've forced this device to L3. Unfortunately I think that's the best we can do, unless Asus OTA the device.

**Comment by paf-wv** [comment]
Asus confirmed no new OTAs.
