### ISSUE TITLE
video play stuck on some device

### ISSUE THREAD

**Issue by Caij** [google/ExoPlayer#4415]
Version: 3.8.1     （2.7.3 is no problem） 
device： xiaomi note 3  android 7.1.1,    xiaomi 5sp android 7.0

source file:
https://github.com/Caij/OkHttpDownDemo/blob/master/00404Kfhjx07bvNox0Ev010f11001zyG0k01.mp4

problem video record：
https://github.com/Caij/OkHttpDownDemo/blob/master/Screenrecorder-2018-06-22-18-11-59-960.mp4
https://github.com/Caij/OkHttpDownDemo/blob/master/Screenrecorder-2018-06-25-09-58-16-601%20-%20%E5%89%AF%E6%9C%AC.mp4

**Comment by andrewlewis** [comment]
The video plays fine for me using a recent version. Could you elaborate on what you mean by the video being stuck? Could you describe what you saw, and what you expected to see?

It would also be useful to have a bug report from the device, captured with `adb bugreport`. Thanks!

**Comment by Caij** [comment]
the problem you can see I recorded video， You pay attention to the progress bar and screen.


https：//github.com/Caij/OkHttpDownDemo/blob/master/Screenrecorder-2018-06-22-18-11-59-960.mp4 
https://github.com/Caij/OkHttpDownDemo/blob /master/Screenrecorder-2018-06-25-09-58-16-601%20-%20%E5%89%AF%E6%9C%AC.mp4

**Comment by andrewlewis** [comment]
Is this just a case of the player pausing to buffer media, or is there something else going on? As requested in my previous comment, please attach a bug report captured with `adb bugreport`.

**Comment by RubenSaucedo** [comment]
Caji, I have replicated the project and I cannot see what the error is.
Please attach the errors or a bug report to check it so I can take a look on it.

**Comment by Caij** [comment]
This is user feedback, and I have not found this problem. That is not a network buffer, that is stuck.
So this problem is very difficult to check, only certain phones will have problems.

**Comment by onecoders** [comment]
Problems also happen on OPPO R7 Plus(version:2.7.3)

**Comment by andrewlewis** [comment]
@Caij How did you verify that the pause was not due to buffering if it's from a user feedback? So far there isn't enough information here for us to investigate. If you can provide a bug report and steps to reproduce please file a new issue.
