### ISSUE TITLE
Replace 2.x.x with the actual latest version in docs

### ISSUE THREAD

**Issue by sri-new** [google/ExoPlayer#4416]
Scouring the internet just to get the latest version is not really ideal while looking to add the library as a dependency.

**Comment by ojw28** [comment]
I don't particularly want to have to update our documentation every time we do a release for this. So we can either:

1. Link to the release notes (or equivalent; anything that's naturally updated to show the latest version).
1. Find a way of filling it in automatically.

**Comment by sri-new** [comment]
Yes, that will be nice! Thanks!

**Comment by DKillWorld** [comment]
Just look at the ReleaseNotes in root branch of project. It will reflect latest release with changelog.

**Comment by ojw28** [comment]
On reflection, I'm not sure if makes sense to use the latest version. There are legitimate reasons for wanting to use an older version. As @DKillWorld notes above, you can look at the release notes if you want to find the latest version. Or look on BinTray.

**Comment by sri-new** [comment]
Yes, agree on the part about not needing to use the latest version. However, having the latest release number readily available in the README would benefit all who want to try out the library.
