### ISSUE TITLE
minSdkVersion 9

### ISSUE THREAD

**Issue by farfromrefug** [google/ExoPlayer#442]
In the build.gradle you mention that ExoPlayer has a minSdkVersion of 9 which is great!
However ExoPlayer uses [MediaExtractor](http://developer.android.com/reference/android/media/MediaExtractor.html) which only appeared in API 16.
So what is it going to be:
- dropping support under 16?
- adding MediaExtractor to ExoPlayer?

Thanks

**Comment by nzer** [comment]
There's wiki page which explains that. Main limitation is ability to play video.

**Comment by brillenheini** [comment]
Please see https://github.com/google/ExoPlayer/issues/31.

There is also an explanation in AndroidManifest.xml but it probably should be in build.gradle (that is where I was looking first):
https://github.com/google/ExoPlayer/blob/master/library/src/main/AndroidManifest.xml

**Comment by ojw28** [comment]
The explanation is added in build.gradle too on the dev branch.

**Comment by farfromrefug** [comment]
Wow i am really sorry about not seeing this before :s
@nzer you mention the main limitation is for video. Right now i am only using the Exoplayer for audio. But MediaCodecAudioTrackRenderer relies on it.
Looking at the code it could be made compatible with SDK 9 with some ifs. Am i wrong?

**Comment by ojw28** [comment]
The main dependency is the use of MediaCodec, which requires API level 16 and is used for both audio and video.

**Comment by farfromrefug** [comment]
@ojw28 So it requires API 16 :D There is now way to have it work with 9?

**Comment by ojw28** [comment]
You can replace pretty much all of the standard components in ExoPlayer with other implementations, so the library is useful for API level 9. For example it's possible to implement your own TrackRenderer that doesn't use MediaCodec, and hooks into a software decoder that you bundle into your apk. If you were to do that, you could go back to API level 9 and happily play both audio and video (I don't recommend you bother trying to do this; this is just an example).

**Comment by farfromrefug** [comment]
@ojw28 thanks for the explanation it makes sense ;)
