### ISSUE TITLE
HLS: Support variable substitution

### ISSUE THREAD

**Issue by ronak2121** [google/ExoPlayer#4422]
Hi,

We would like to reduce the size of our HLS manifests and there are really only two ways to do it:

Use relative paths
Use hls variable substitution

I was wondering if Exoplayer supports hls variable substitution and if not, if support can be added.

**Comment by ojw28** [comment]
1. Pretty sure we support relative paths, in that we'll resolve paths against that of the media playlist URL, after any redirection. @AquilesCanta can confirm.
1. We don't support variable substitution. It looks like that was recently added to the HLS spec? We can use this issue to track adding support.

**Comment by AquilesCanta** [comment]
> Pretty sure we support relative paths, in that we'll resolve paths against that of the media playlist URL, after any redirection.

Correct.

Didn't know about variable substitution. Thanks!

**Comment by szaboa** [comment]
@ojw28 Does somebody already work on this? 
If not, what would you say about the difficulty of this enhancement? 

Based on a quick look to the code I would start like this:

Key-value pairs after the EXT-X-DEFINE tags needs to be saved from the master playlist, and when parsing the hls I would check if a line contains any of the key (in a correct form {$<key>}) and just replace it with the corresponding value. This would take N checks per line, where N is the size of the hash map in which the key-value pairs are stored.

Note. rookie here, this would be my seconds contribution to ExoPlayer

**Comment by ojw28** [comment]
That's a question for @AquilesCanta

**Comment by AquilesCanta** [comment]
> Does somebody already work on this?

Yes, I have been looking at it. I am currently working a different small feature for HLS, but will look into this right after.

**Comment by szaboa** [comment]
@AquilesCanta Got it!

**Comment by ojw28** [comment]
Support was added in 2.9.0.
