### ISSUE TITLE
PlayerNotificationManager not displaying notification

### ISSUE THREAD

**Issue by a-v-ebrahimi** [google/ExoPlayer#4428]
I am using code below to displaying play progress in notification bar and lock screen, it's working properly on all devices except Huawei Mate 10 Pro, which doesn't display notification **at all**:

```
...
playerNotificationManager = PlayerNotificationManager(
                this,
                CHANNEL_ID,
                MEDIA_NOTIF_ID,
                DescriptionAdapter())
playerNotificationManager.setPlayer(player)
...

```

Device : Huawei Mate 10 Pro
Device OS is Android 8.0.0

**Comment by vickyponraj** [comment]
Having the same Problem

**Comment by a-v-ebrahimi** [comment]
@vickyponraj 
Found solution: add channelID
