### ISSUE TITLE
Exoplayer with youtube

### ISSUE THREAD

**Issue by samradhs** [google/ExoPlayer#4429]
Hi,

I want to make a video player that can play videos both from my given urls and youtube. Is it possible to achieve it with exoplayer ?

Thanks,
Samradh

**Comment by andrewlewis** [comment]
The [YouTube Android Player API](https://developers.google.com/youtube/android/player/) is the official way to play YouTube videos as noted in #2160. You could try switching between your own player based on ExoPlayer and the YouTube Android Player API player depending on the type of video, but you can't use ExoPlayer for both.

**Comment by AndroidDeveloperLB** [comment]
Interesting, but will it play ads of YouTube? Even if the video was created by the developer or something?

**Comment by ojw28** [comment]
The uploader of the video sets whether that video is monetized (i.e. may display ads) or not.

**Comment by AndroidDeveloperLB** [comment]
I didn't know this, but why would anyone wish to put ads? Do they get a cut of the revenues?

**Comment by ojw28** [comment]
Yes. This is something you can pretty easily research yourself, for example [here](https://creatoracademy.youtube.com/page/course/channel-revenue?hl=en-GB).

**Comment by AndroidDeveloperLB** [comment]
OK thank you
