### ISSUE TITLE
exo_play and seekbar related id's not getting reset after player.release()

### ISSUE THREAD

**Issue by zishanj** [google/ExoPlayer#4432]
I am using ver 2.7. While playing the audio, if I `release` the player the play button with id `exo_play` and seekbar related id's `exo_position`, `exo_duration`, `exo_progress` does not get automatically reset. I was expecting them to change to `pause` and reset the values for seekbar related id's.

Is there any workaround to this?

**Comment by ojw28** [comment]
Does it work if you call `stop()` and then `release()`?
