### ISSUE TITLE
Support manually stopping/starting download when using DownloadService

### ISSUE THREAD

**Issue by makvasic** [google/ExoPlayer#4433]
Is there any preferred way of doing pause and resume manually on active download?
I am looking at `DownloadManager.stopDownloads()` and `DownloadManager.startDownloads()` which seems to do that.
When `stopDownloads()` download is stopped and notification is removed which is OK,   
when `startDownloads()` download is resumed but notification is nowhere to be seen.
Is that desired behavior?
I was expecting same behavior like after connection failure for example.

Tested stream _HLS -> Apple 4x3 basic stream_ in _DemoApp_

Thanks and awesome job with DownloadManager!

**Comment by erdemguven** [comment]
Currently stopping/starting downloads manually while using DownloadService isn't supported. When you call stopDownloads() DownloadService is stopped as well. You need to restart the service to be able to see the notifications. 
Even if you manually stop/start downloads, they can be started/stopped again automatically when the requirements are met or not.

**Comment by YukiMatsumura** [comment]
> Even if you manually stop/start downloads, they can be started/stopped again automatically when the requirements are met or not.

When stopping the download with stopDownload(), I want to prevent the download from starting automatically even if the requirement is met.

Is there any way I could ...?

**Comment by ojw28** [comment]
This is now supported in `dev-v2`, and will be in the `2.10.0` release.

* You can pause/resume all downloads with `DownloadManager.pauseDownloads` and `DownloadManager.resumeDownloads`.
* You can stop/unstop an individual download with `DownloadManager.setStopReason`.
* If using `DownloadService`, then these commands can also be sent to the service using intents (there are corresponding helper methods for building and sending these).
