### ISSUE TITLE
exo_buffering is not showing when playWhenReady is false

### ISSUE THREAD

**Issue by ThomasWilliamMarsh** [google/ExoPlayer#4445]
Hey guys, 

when determining if the buffering logo should show, we have the following condition:

```
      boolean showBufferingSpinner =
          showBuffering
              && player != null
              && player.getPlaybackState() == Player.STATE_BUFFERING
              && player.getPlayWhenReady();
```

Why are we checking if playWhenReady is set to true? in the case of the video being paused, and the user scrubs the timeline to another point, the buffering logo is not showing, although it is buffering. Should we not remove this?

**Comment by ojw28** [comment]
Duplicate of #4304
