### ISSUE TITLE
How to get all downloaded media list ?

### ISSUE THREAD

**Issue by ZohaibGhafoor** [google/ExoPlayer#4446]
i want to get all media media list in a fragment to play them offline in my app how to get all downloaded  media files ?

**Comment by erdemguven** [comment]
Currently there is no such a functionality. You need to store what has been downloaded, yourself.  Please see for an example about how to this: 
https://github.com/google/ExoPlayer/blob/release-v2/demos/main/src/main/java/com/google/android/exoplayer2/demo/DownloadTracker.java
Note, DownloadTracker isn't part of the main library but it's a part of the demo app.

**Comment by ojw28** [comment]
This is addressed in `dev-v2` and will be in the `2.10` release.
