### ISSUE TITLE
Head orientation update is delayed when using GvrAudioProcessor 

### ISSUE THREAD

**Issue by chw0239** [google/ExoPlayer#4447]
I am using [GvrAudioProcessor](http://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/ext/gvr/GvrAudioProcessor.html) to render a HLS audio stream. In order to update the head orientation, I've used the following code in onNewFrame (I am using GvrView.StereoRenderer):
```
private float[] headRotation;
@Override
public void onNewFrame(HeadTransform headTransform) {
  // ...
  if (gvrAudioProcessor != null) {
    headTransform.getQuaternion(headOrientation, 0);
    gvrAudioProcessor.updateOrientation(headOrientation[0], headOrientation[1],
        headOrientation[2], headOrientation[3]);
  }
  // ...
}
```
It works, except that the head orientation update is delayed about 0.5s.
For example, when I turn the smartphone from left to right, it takes about 0.5s before the audio output update to the new orientation. I've considered that it might be due to the stream I've used, so I've tried some other HLS stream sources, as well as other type of input such as DASH and local video file. However, there is always the same issue. 
I would like to know if it is normal to have this delay with ExoPlayer. Are there any possible solution?

**Comment by andrewlewis** [comment]
Please could you try reducing the size of the `AudioTrack`'s buffer, and see if that resolves this? With the default buffer size, the maximum delay could be up to 750 ms. Lower buffer sizes can increase the chance of audio underruns, so you'll need to experiment.

Note: if you have sources checked out you can experiment with this by modifying the buffer size passed to `audioSink.configure` in `MediaCodecAudioRenderer.onOutputFormatChanged`. If you don't want to check out sources you'll need to subclass `MediaCodecAudioRenderer`, add a constructor that instantiates a `DefaultAudioSink` and keeps a reference to it, then override `onOutputFormatChanged` to configure that audio sink with the buffer size you want to try. Then subclass your `DefaultRenderersFactory` to pass this to the player, for example.

If reducing the buffer size doesn't help, please reply here and I'll investigate further.

**Comment by chw0239** [comment]
Thank you very much, I have tried modifying the buffer size to the minimum suggested in the code, and the delay was reduced significantly, it is now acceptable.
That's what I have done: 
DefaultAudioSink.java
```
      int minBufferSize = AudioTrack.getMinBufferSize(sampleRate, channelConfig, outputEncoding);
      Assertions.checkState(minBufferSize != ERROR_BAD_VALUE);
      int multipliedBufferSize = minBufferSize * BUFFER_MULTIPLICATION_FACTOR;
      int minAppBufferSize = (int) durationUsToFrames(MIN_BUFFER_DURATION_US) * outputPcmFrameSize;
      int maxAppBufferSize = (int) Math.max(minBufferSize,
          durationUsToFrames(MAX_BUFFER_DURATION_US) * outputPcmFrameSize);
      bufferSize = minAppBufferSize;
      //bufferSize = Util.constrainValue(multipliedBufferSize, minAppBufferSize, maxAppBufferSize);
```

**Comment by andrewlewis** [comment]
Great. There is a greater risk of the audio track underrunning after this change, so please keep an eye out for that. Thanks!
