### ISSUE TITLE
Android React-Native-Video/ExoPlayer "Unrecognized media format" - MP4

### ISSUE THREAD

**Issue by Jvheaney** [google/ExoPlayer#4449]
### Issue description
I have react-native-video added to my react-native apps for both iOS and Android. Upon trying to stream video on demand (not livestream) from servers, I run into some issues:

These websites hosting MP4 videos will load fine in ExoPlayer:
[https://d23dyxeqlo5psv.cloudfront.net/big_buck_bunny.mp4](https://d23dyxeqlo5psv.cloudfront.net/big_buck_bunny.mp4)
[https://www.sample-videos.com/video/mp4/720/big_buck_bunny_720p_1mb.mp4](https://www.sample-videos.com/video/mp4/720/big_buck_bunny_720p_1mb.mp4)

But once I take the exact same video clip from those websites (Right clicked, "Save Video As") and upload them to my own server, the ExoPlayer spits out the following error:

```
error: {
"" : "Unable to connect to https://www.kilocast.com/videos/bunny_short.mp4"
errorString : "Unrecognized media format"
}
```

My test video files on my server are found at:
[https://kilocast.com/videos/big_buck_bunny.mp4](https://kilocast.com/videos/big_buck_bunny.mp4)
[https://kilocast.com/videos/bunny_short.mp4](https://kilocast.com/videos/bunny_short.mp4)

If these videos are local instead of served externally, they work with no issues.

Obviously this is quite odd because 1) iOS recognizes the video files both times **and plays without issues regardless of the server host**, 2) It's the same video file served from both my server and the third party ones, and 3) Android/ExoPlayer obviously have the codec available to deal with .mp4 files.

Here's my exact code used:
```
          <Video
          repeat
          paused={false}
          source={{uri: "https://www.kilocast.com/videos/bunny_short.mp4"}}
          style={{
            width: screenWidth,
            height: 215
          }}
          onError={err => requestAnimationFrame(() => {
            console.log(err);
          }
        ) } />
```

### Reproduction steps
1. Substitue my server's URL (from above code snippet) to the third party hosts to see it work; vise versa for it stop working.

### Link to test content
(Working) Third party test files:
[https://d23dyxeqlo5psv.cloudfront.net/big_buck_bunny.mp4](https://d23dyxeqlo5psv.cloudfront.net/big_buck_bunny.mp4)
[https://www.sample-videos.com/video/mp4/720/big_buck_bunny_720p_1mb.mp4](https://www.sample-videos.com/video/mp4/720/big_buck_bunny_720p_1mb.mp4)

(Not Working) Same test files on my server:
[https://kilocast.com/videos/big_buck_bunny.mp4](https://kilocast.com/videos/big_buck_bunny.mp4)
[https://kilocast.com/videos/bunny_short.mp4](https://kilocast.com/videos/bunny_short.mp4)

### Version of ExoPlayer being used
Unfortunately I cannot find the version of ExoPlayer, but I am using version 2.3.1 of the [React-Native-Video](https://www.npmjs.com/package/react-native-video) module.

### Device(s) and version(s) of Android being used
Samsung S8 (Physical), Android 7.0.1
Nexus 5 (Simulator), Android 6.0.0

**Comment by andrewlewis** [comment]
When I try to access the streams from your server I get a certificate error. Are you using a self-signed certificate? Are you sure the server is configured correctly?

Please provide a bug report captured with `adb bugreport` just after seeing the error.

**Comment by andrewlewis** [comment]
When I download the stream from your server and push the file locally it plays fine. If you see an error about the certificate in logcat when trying to play the videos from your server, please read [Security with HTTPS and SSL](https://developer.android.com/training/articles/security-ssl#CommonProblems).

**Comment by Jvheaney** [comment]
> When I try to access the streams from your server I get a certificate error. Are you using a self-signed certificate? Are you sure the server is configured correctly?

I think you may have hit it right on the nose. I am using self-signed certificates and I do see an error about the certificate in logcat. I'm reading up on the website you linked above and will try those steps for using myself as a CA.

Hopefully that solves it, I'll update with any progress I make; Thanks for the quick response!

**Comment by Jvheaney** [comment]
You know, doing some reading about this is actually making me second guess myself. I use LetsEncrypt, which I believe means it's signed by their CA? A lot of posts I am reading seem to suggest that LetsEncrypt should work for this sort of thing.

**Comment by andrewlewis** [comment]
I'd expect it to work fine with Let's Encrypt, but it looks like some "extra" configuration might be required compared to other platforms. Search for "android let's encrypt" or similar and you'll find issues like [this one](https://community.letsencrypt.org/t/lets-encrypt-cert-not-trusted-by-android/58867). Caveat: I'm not sure what the implications of the changes they're suggesting are so please be careful :)

Please update this issue if you find a way to make it work so others can benefit. Thanks!
