### ISSUE TITLE
How to dispaly subtitle

### ISSUE THREAD

**Issue by halil-raso** [google/ExoPlayer#4453]
I am developing a streaming app. I used for this purpose exoplayer2. I am using HLS streaming protocol. I need to show subtitle when streaming my videos. Everything goes well except subtitle. My player doesn't show the sample subtitle. My code is as following:

        uri = Uri.parse(url);
    videoSource = new HlsMediaSource.Factory(DATA_SOURCE_FACTORY).createMediaSource(uri);
    Uri uri1 = Uri.parse("https://bitdash-a.akamaihd.net/content/sintel/hls/subtitles_en.vtt");

    Format subtitleFormat = Format.createTextSampleFormat(
            null, // An identifier for the track. May be null.
            MimeTypes.APPLICATION_SUBRIP, // The mime type. Must be set correctly.
            Format.NO_VALUE, // Selection flags for the track.
            "en");

    DefaultBandwidthMeter bandwidthMeter2 = new DefaultBandwidthMeter();
     DefaultDataSourceFactory dataSourceFactory =  new DefaultDataSourceFactory(this,
            Util.getUserAgent(this, "ExoCastDemoPlayer"), bandwidthMeter2);
    subtitleSource = new SingleSampleMediaSource.Factory(dataSourceFactory).createMediaSource(uri1,subtitleFormat, C.TIME_UNSET);
    MergingMediaSource mergedSource = new MergingMediaSource(videoSource, subtitleSource);
    player.prepare(mergedSource);
    player.seekTo(currentPosition);
    player.setPlayWhenReady(true);
    player.addListener(new IPlayerEventListener(this));
    dropdown = findViewById(R.id.exo_resolution);
    adapter = new SpinnerAdapter(this, items);
    dropdown.setAdapter(adapter);
    dropdown.setOnItemSelectedListener(new SpinnerOnItemSelectedListener());

Please could anyone help me 

thanks in advance

**Comment by RubenSaucedo** [comment]
Hi Halil-raso,

SimpleExoPlayerView has SubtitleView as child. 
I have code the following on the demo-ima and it works:

```java
// This is the MediaSource representing the content media (i.e. not the ad).
String contentUrl = context.getString(R.string.content_url);
MediaSource contentMediaSource = buildMediaSource(Uri.parse(contentUrl));
MediaSource[] mediaSources = new MediaSource[2]; //The Size must change depending on the Uris
mediaSources[0] = contentMediaSource; // uri

//Add subtitles
SingleSampleMediaSource subtitleSource = new SingleSampleMediaSource(Uri.parse("https://www.iandevlin.com/html5test/webvtt/upc-video-subtitles-en.vtt"), mediaDataSourceFactory,
            Format.createTextSampleFormat(null, MimeTypes.TEXT_VTT, Format.NO_VALUE, "en", null),
            C.TIME_UNSET);

mediaSources[1] = subtitleSource;

MediaSource mediaSource = new MergingMediaSource(mediaSources);

// Prepare the player with the source.
player.seekTo(contentPosition);
player.prepare(mediaSource);
player.setPlayWhenReady(true);
```
I'va made some changes on the code based on the following question:
https://github.com/google/ExoPlayer/issues/2256
Take a look of it and also could help you.

**Comment by andrewlewis** [comment]
It looks like the MIME type in the first code snippet above is wrong (it should be `MimeTypes.TEXT_VTT` as in the second code snippet). Please try changing that and let us know if it's still broken.

**Comment by halil-raso** [comment]
Hi @resid9406 
Thank you for your help. I tried your code but it did not work either. Also I checked #2256 but for nothing...
what should I do in such case. It is important for me....

**Comment by halil-raso** [comment]
Hi @andrewlewis  
Thanks for your help. I tried it also but for nothing.

**Comment by halil-raso** [comment]
@resid9406 @andrewlewis thank you so much now it is working perfectly.
