### ISSUE TITLE
SSL handshake error on cellular network

### ISSUE THREAD

**Issue by armanhi** [google/ExoPlayer#4454]
### Issue description
We're trying to play a HLS content through https. It works when playing using Wi-FI, but not using a cellular network. It's important to say we're not getting a trust anchor error and I've tested the certificate at https://www.ssllabs.com/ssltest/analyze.html. I'm also sending it in the email.

### Reproduction steps
We just try to play the content using a DefaultDataSourceFactory

### Link to test content
Sent in email

### Version of ExoPlayer being used
2.8.1

### Device(s) and version(s) of Android being used
Samsung S8, Android 8.0.0

### A full bug report captured from the device
Sent in email

**Comment by andrewlewis** [comment]
Does this affect all cellular networks, or just a particular network? It could be that the ISP is interfering with the connection.

**Comment by ojw28** [comment]
This doesn't sound like an ExoPlayer issue. The stream provided via email works over both WiFi and cellular for me, so it's likely an issue with the cellular network provider that you're using.
