### ISSUE TITLE
What should be done if I want to use it inside live wallpaper?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [google/ExoPlayer#4457]
After all, it doesn't have views...
I want to put it and view it in various scaling methods, but for now I've found out only how to do it with the normal MediaPlayer, and it scales it by stretching, which isn't nice:
https://stackoverflow.com/q/50091878/878126

**Comment by eneim** [comment]
@AndroidDeveloperLB there is "resize_mode" in the attribute list of PlayerView, can you take a look?

**Comment by AndroidDeveloperLB** [comment]
Again, live wallpaper can't have a view. It doesn't even have a layout...

**Comment by eneim** [comment]
Ohh sorry I missed the point. I’m not familiar with Wallpaper, what do you use to render the Video? There is callback for Video size, can it be used to change that “render surface” size?

**Comment by AndroidDeveloperLB** [comment]
@eneim I don't know. I tried so many things, and all fail (crash or do nothing).
Here's a Github repository to play with, that I've made:
https://github.com/AndroidDeveloperLB/MovieLiveWallpaper

**Comment by andrewlewis** [comment]
The `SurfaceHolder` from the `WallpaperService.Engine` can be passed to ExoPlayer using `SimpleExoPlayer.setSurfaceHolder`. To keep the aspect ratio, please try `SimpleExoPlayer.setVideoScalingMode(C.VIDEO_SCALING_MODE_SCALE_TO_FIT_WITH_CROPPING)`. Here's the [documentation](https://developer.android.com/reference/android/media/MediaCodec.html#VIDEO_SCALING_MODE_SCALE_TO_FIT_WITH_CROPPING) for that setting, and I think `MediaPlayer` supports it too.

This assumes that the pixel aspect ratio of the video is 1:1. If you need to support non-1:1 content or a different transformation then you'd need to copy from a video decoder output surface to the wallpaper surface using GLES, which is going to be more complicated.

**Comment by AndroidDeveloperLB** [comment]
Not all video files have 1:1 aspect ratio. In fact most of them don't.
Why don't the ExoPlayer have aspect ratio functions?
How come it can't support other aspect ratios? I'm confused. It doesn't make sense...

**Comment by andrewlewis** [comment]
The limitation is around the pixel aspect ratio, not the video aspect ratio. So the solution outlined above should work fine with a 1280×720 video (with square pixels!) for example, as long as you don't mind it being scaled up to the screen size with the edges cropped off.

**Comment by AndroidDeveloperLB** [comment]
Pixel aspect ratio? I wasn't aware this even exists. Why would any OEM create one that is not 1:1 ? It would make things weirder otherwise.
Actually now that I think about it, there are many devices that have a horizontal density that's different from the vertical one. 
So you mean that on this library, it will have issues with non 1:1 pixel aspect ratio? 
I think there are quite a lot of them, no? 
Will the cropping be symmetric, at least? Maybe most users won't be able to notice it?

**Comment by andrewlewis** [comment]
The pixel aspect ratio refers to the video content (not the device screen). I'd be surprised if you need to worry about content with non-square pixels. If you control the content you can just make sure you don't set a non-1:1 pixel aspect ratio when encoding the video.

As noted in the documentation "The content is scaled, maintaining its aspect ratio, the whole surface area is used, content may be cropped.".

**Comment by AndroidDeveloperLB** [comment]
There is even pixel aspect ratio in the video file? That's even weirder...
About the docs, do I have a function to change the scaling type though?
Meaning not just center-crop, as you've written (scale to fill entire view and allow to crop if needed), but others?

**Comment by andrewlewis** [comment]
You're limited to stretching and zoom/crop maintaining aspect ratio via the `MediaCodec` scaling modes when using a `Surface` without a layout.

To get more flexibility you'd need to copy from a video decoder output surface to the wallpaper surface using GLES, which is going to be more complicated. It's beyond the scope of this issue tracker to give more detailed guidance on that I'm afraid.

**Comment by AndroidDeveloperLB** [comment]
But the basic, most common ones of ImageView exist here too?
I'm talking about those (all keep aspect ratio) :
center-crop - fits to 100% of the container (the screen in this case), cropping on sides (top&bottom or left&right) when needed. Doesn't stretch anything. This means the content seems fine, but not all of it might be shown.
fit-center - stretch to fit width/height
center-inside - set as original size, centered, and stretch to fit width/height only if too large.

**Comment by andrewlewis** [comment]
Hm, I'm not sure where those options are available. Could you elaborate on where "here" is? I was thinking of `MediaCodec.setVideoScalingMode` which takes either `VIDEO_SCALING_MODE_SCALE_TO_FIT` or `VIDEO_SCALING_MODE_SCALE_TO_FIT_WITH_CROPPING`.

**Comment by AndroidDeveloperLB** [comment]
Here, as in this repository. Of course the terms might be different, but the ideas are the same. 
So VIDEO_SCALING_MODE_SCALE_TO_FIT  is fit-center ?
And VIDEO_SCALING_MODE_SCALE_TO_FIT_WITH_CROPPING is center-crop?
What about center-inside ?

**Comment by andrewlewis** [comment]
As far as I can see, unless you implement your own code for copying to the output surface using GLES you're going to be limited to the two scaling modes defined on `MediaCodec` (as noted above). They're documented [here](https://developer.android.com/reference/android/media/MediaCodec.html#VIDEO_SCALING_MODE_SCALE_TO_FIT).

**Comment by AndroidDeveloperLB** [comment]
Docs show as if those are the only scaling types. Which is the default? 
I think you should consider other types. There are various video players (on Android and on PC) that offer more...

**Comment by andrewlewis** [comment]
I think it stretches by default. The vast majority of apps can use ExoPlayer's `AspectRatioFrameLayout` which has more modes. The options are more limited in this specific case because you can't use a layout when implementing a live wallpaper.

**Comment by AndroidDeveloperLB** [comment]
That's too bad. Can you please consider adding them somehow, in a more general form?
The AspectRatioFrameLayout can use the general form.

**Comment by andrewlewis** [comment]
We will consider it, though it's unlikely to help you any time soon because it would probably require a change in the platform media framework.

**Comment by AndroidDeveloperLB** [comment]
ok thanks, and to make it more official, here's this request:
https://github.com/google/ExoPlayer/issues/4464
