### ISSUE TITLE
Abnormal display of the duration while using EXO Player

### ISSUE THREAD

**Issue by fusionseek** [google/ExoPlayer#4458]
Dear Sir/Madam,

I'm writing to inquire about some info regarding the EXO Player. 

Our team keeps using EXO Player, which is in **v2.8** now. Recently, some problems have been found out from users' feedback. For some RSS feeds, while using EXO Player to play, the total time duration displayed is much longer than that on other players. 

For example, this feed https://s3.castbox.fm/a3/44/b0/8ee87445d2b518916be8fa0249.mp3, the duration displayed on EXO Player is **3:24:25**.

![image](https://user-images.githubusercontent.com/1260653/42156332-5fc6992e-7e1d-11e8-8307-be5f6abdce3f.png)

![image](https://user-images.githubusercontent.com/1260653/42156406-92483aba-7e1d-11e8-992f-ec4fc1418dc1.png)

however, if we download this audio file, it only has **38 minutes** on other players.

![image](https://user-images.githubusercontent.com/1260653/42156434-a2a484ae-7e1d-11e8-86a9-983be7d964e2.png)

Therefore, I'd like to know, why does this issue happen? What should I do to resolve it? Is there any parameter I need to set? Or is it relevant to the problem of the feed itself?

Looking forward to your kind response. Any help will be very much appreciated.

Thank you very much!

Best,

**Comment by botaydotcom** [comment]
Haven't looked at this in details, but I guess the cause is similar to #4071.

**Comment by tonihei** [comment]
I can confirm what @botaydotcom already guessed. The file has a variable bitrate but doesn't contain seek headers.
