### ISSUE TITLE
Asking users questions: showing radio buttons over player

### ISSUE THREAD

**Issue by halil-raso** [google/ExoPlayer#4462]
Hi 

I am developing an app that let users to watch videos. some of these videos is exam videos so I need to ask users to answer questions given in radio button, checkbox or text field and displayed over player. 
Could anybody help me in 
1- Showing such radiobutton and checkbox over player.
2- Get users' selections (what they selected from such checkbox and radiobuttons).

Thanks in advance.

**Comment by tonihei** [comment]
That's more of a generic Android question. I'd suggest to ask that on StackOverflow or similar sites as this issue tracker is primarily for bugs, feature requests and ExoPlayer-specific questions.
