### ISSUE TITLE
SimpleCache: get download percentage against an URL and resume if not fully downloaded

### ISSUE THREAD

**Issue by joecizac** [google/ExoPlayer#4465]
Hi,
I have cached videos using CacheDataSourceFactory.
Now I want to check whether the video was downloaded completely and also resume or restart the download if not completed.
How can I go about it? Please help me with this.

**Comment by tonihei** [comment]
For a general guide to downloading content, I'd recommend reading [this blog post](https://medium.com/google-exoplayer/downloading-streams-6d259eec7f95). 

If you downloaded data on the fly with a CacheDataSource, you should be able to query the status with `CacheUtil.getCached(new DataSpec(uri), cache, cachingCounters)`. And then check `cachingCounters.alreadyCachedBytes` and `cachingCounters.contentLength`. Note that this only works for simple files which are not chunk-based.

**Comment by joecizac** [comment]
Hey thanks for the quick reply.
Yup I referred [this](https://medium.com/google-exoplayer/downloading-streams-6d259eec7f95) and [this](https://medium.com/google-exoplayer/pre-caching-downloading-progressive-streams-in-exoplayer-3a816c75e8f6) to download the stream.
Yes, my cache is segmented and not a raw file cache. 
Anyways I will check your solution.

Thanks once again.

**Comment by joecizac** [comment]
Hey thanks it worked.
I misunderstood when you said "only works for simple files which are not chunk-based".
My file that I need to cache is a simple raw file and not chunk-based.
I thought you were referring to the cache which is segmented (not a whole file) when downloaded using CacheDataSourceFactory or DownloadService.

Another extended question is, whether the using  CacheDataSourceFactory and DownloadService will lead to cache corruption? Coz both both the APIs cache the file in similar fashion.

**Comment by tonihei** [comment]
> Another extended question is, whether the using CacheDataSourceFactory and DownloadService will lead to cache corruption? Coz both both the APIs cache the file in similar fashion.

@erdemguven: Can you comment on that?

**Comment by erdemguven** [comment]
As long as they use the same Cache object it should be fine.
