### ISSUE TITLE
ConcatinatingMediaSource showing frame of last video on when skipped to next one...

### ISSUE THREAD

**Issue by tashariko** [google/ExoPlayer#4467]
exoplayer is showin the frame of last video whenever im skipping in exoplayer playlist(ConcatinatingMediaSource). it shows it for sometimes then it shows the frame of second video...

**Comment by tonihei** [comment]
When you skip to the next playlist item it takes some time to load the video before we are able to show the first frame. Until then, the previously shown frame is still shown. What would you expect to happen?

**Comment by tashariko** [comment]
it should not show the last frame of previous video, i want to show black screen dere...

**Comment by tashariko** [comment]
btw...im changing the timeline by seekto() for skipping the video...

**Comment by tonihei** [comment]
You could try removing the surface before calling seekTo() and adding it back after the seek. `SimpleExoPlayer` has `set/clearVideoTextureView` and `set/clearVideoSurfaceView` for that.

**Comment by tashariko** [comment]
there is clearVideoSurfaceView, dat one?...if i do that, then when to to make it visible again?...or on skipping it will automatically show the video surface for next video?

**Comment by tonihei** [comment]
Yes, that one. There is also setVideoSurfaceView to attach the surface to the player again.

**Comment by tashariko** [comment]
yeah..i am doing dat..but when to use setVideoSurfaceView? ...so that it will always show frame when next video starts?....

**Comment by tashariko** [comment]
i tried doing it in playbackstatechanged(), onRenderedFirstFrame(), onTimelineChanged() but not working properly...

**Comment by tonihei** [comment]
Could you try adding it back immediately after calling seekTo?
Alternatively, you can try onSeekProcessed.

**Comment by tashariko** [comment]
yeah tried that..its not working..it is still showin the frame...

**Comment by tashariko** [comment]
By seekto() im movin to the next timeline...dat is triggering the frame thing...im not going to next video by next button, im goin from this onTimelineChanged() method...

**Comment by tonihei** [comment]
Well, I tried clearing and adding the surface when pressing the next button and that works fine. I just did something like:
```
player.clearVideoTextureView(view);
player.seekTo(nextWindowIndex, C.TIME_UNSET);
player.setVideoTextureView(view);
```

The `onTimelineChanged` method is totally unrelated to seeking or moving to the next item. You'll usually only get `onPositionDiscontinuity` for the seek and `onSeekProcessed` once the player acknowledged the seek. However, if you want to clear the surface before seeking, you can't do this in a callback because the callback is only called after the seek.

**Comment by tashariko** [comment]
i tried with clearVideoSurfaceView(), its not working with dat...any help in that?...i did this only...
` manager.getPlayer().clearVideoSurface()
skipFile(Player.REPEAT_MODE_OFF);
manager.getPlayer().setVideoSurfaceView((SurfaceView) exoPlayerVideoView.getVideoSurfaceView());`

**Comment by tonihei** [comment]
The code snippet you show contains a lot of custom app code. Unfortunately, we don't have enough resources to help you debug your app. 

But in general this approach looks right and it worked perfectly fine when I tried this.

**Comment by tashariko** [comment]
how to use clearVideoTextureView()?...
