### ISSUE TITLE
Removing downloads foreground notification shows whene download completed

### ISSUE THREAD

**Issue by basettoni89** [google/ExoPlayer#4469]
**ISSUE DESCRIPTION**

With ExoPlayer demo app I start to download an asset. 
During download I kill the app, DownloadService continue working correctly and foreground notification with progress is shown.
When the download is completed the download notification disappear and then a "Removing downloads" foreground notification is shown.

If I try the above steps without killing the the app the "Removing downloads" notification is not shown.

**Version of ExoPlayer being used**
2.8.1

**Device(s) and version(s) of Android being used**
Samsung Galaxy S9+ - Android 8.0.0
Sony Xperia Z Ultra (C6833) - Android 5.1.1

**Comment by FauziAmth** [comment]
this is also happen as long as download service bound to activity/fragment. so "Removing downloads"  will also appear even when app not killed.

**Comment by ojw28** [comment]
Fixed in `dev-v2`. As per discussion on the change, you shouldn't be binding to the download service (it would probably be a good idea to enforce this, which we may do at some point).
