### ISSUE TITLE
ExoPlayer logo wanted [not a bug]

### ISSUE THREAD

**Issue by tim4dev** [google/ExoPlayer#4470]
Where can I get the ExoPlayer logo for use in `exo_controller:default_artwork`? 
Icon `ic_launcher` is too small.

**Comment by tonihei** [comment]
We currently don't have the logo publicly available. But we'll push it to https://github.com/google/ExoPlayer/blob/gh-pages/images/exoplayer-logo.png soon.

**Comment by ojw28** [comment]
Pushed. You should be able to retrieve the logo from the link above.
