### ISSUE TITLE
Add method getQueueItems() in CastPlayer class [New Feature]

### ISSUE THREAD

**Issue by mrHerintsoaHasina** [google/ExoPlayer#4474]
Hi, it would be useful if the CastPlayer class has a method getQueueItems() as following :

```
  /**
   * Returns the list of MediaQueueItem as an unmodifiable list
   * @return The list of MediaQueueItem, or null if no cast session
   */
  public List<MediaQueueItem> getQueueItems() {
    return isCastSessionAvailable() ? remoteMediaClient.getMediaStatus().getQueueItems() : null;
  }

```

**Comment by tonihei** [comment]
Please have a look at `CastPlayer.getItem(periodId)`. I think that should allow you to query all available queue items.

**Comment by mrHerintsoaHasina** [comment]
But how can we get the `periodId` of all the available queue items from the CastPlayer ?

**Comment by tonihei** [comment]
You can query the current `timeline` with `castPlayer.getCurrentTimeline()` or listen to updates with a `Player.EventListener` and wait for `onTimelineChanged(...)`. 
In this timeline, you'll find as many periods as queue items. Check out `timeline.getPeriodCount()` and `timeline.getPeriod(periodIndex, new Period())`. The latter method gives you a `Period` object with further information about the period. `period.id` is the one you are looking for.

**Comment by mrHerintsoaHasina** [comment]
Thanks ! It is worked.
