### ISSUE TITLE
Q- Is there a way to know if device can play HD stream without loading player 

### ISSUE THREAD

**Issue by giladna** [google/ExoPlayer#4475]

**Comment by tonihei** [comment]
You can try instantiating a `MediaCodecRenderer` and then call `renderer.supportsFormat(format)`. And create `format` with one of the `Format.createVideoSampleFormat` methods filling the format data as close as possible to what you would actually get. Note that the return value of `supportsFormat` is a set of [flags.](https://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/RendererCapabilities.html#supportsFormat-com.google.android.exoplayer2.Format-)

**Comment by tonihei** [comment]
Closing because the question is answered. If there are follow-up questions, feel free to reopen.
