### ISSUE TITLE
Support reading stream duration and seeking for MPEG-PS streams.

### ISSUE THREAD

**Issue by botaydotcom** [google/ExoPlayer#4476]
Split from issue: #4406.

**Comment by botaydotcom** [comment]
This is done now.

**Comment by cncb-gh** [comment]
Can this be extended to MPEG-TS or is it too different? Thanks.

**Comment by ojw28** [comment]
It's already extended to TS.

**Comment by cncb-gh** [comment]
So, the newest build now supports seeking in TS?  Great!

**Comment by ojw28** [comment]
The latest `dev-v2` branch does. This functionality will be in the `2.9.0` release.

**Comment by cncb-gh** [comment]
Excellent.  Is there a release timeline posted somewhere? Many thanks to you, @botaydotcom, @andrewlewis, and anyone else working on this fantastic project!
