### ISSUE TITLE
[Question] Playback is failing on certain DASH streams with TTMLs (taken from DashIF site)

### ISSUE THREAD

**Issue by islor** [google/ExoPlayer#4477]
### Issue description
I've copied the some dash stream urls from the [DashIF](http://reference.dashif.org/dash.js/v2.8.0/samples/dash-if-reference-player/index.html) demo site and put them into the demo app. The stream plays well until I select one of the TTML tracks, then it shows "Playback failed"
What is the issue here? Log shows the inputstream is causing the problem, but why is it playing well in the demo site?

### Link to test content
Tested these links:
http://vm2.dashif.org/livesim/testpic_2s/multi_subs.mpd
http://vm2.dashif.org/livesim/testpic_2s/cea608_and_segs.mpd

### Version of ExoPlayer being used
2.8.1

### Error log captured
[logcat.txt](https://github.com/google/ExoPlayer/files/2168996/logcat.txt)

Let me know if you need more info! Thanks.

**Comment by tonihei** [comment]
Looks like the initialization chunk of the text track is malformed.
I looked at http://vm2.dashif.org/livesim/testpic_2s/sub_eng/init.mp4 and it has:
 - track_id=1 in moov -> mvex -> trex and
 - track_id=3 in moov -> trak -> tkhd. 

ISO 14496-12 says for the track_id in the trex box that _"track_id identifies the track; this shall be the track ID of a track in the Movie Box"_. And for the trex box in general: _"Quantity: Exactly one for each track in the Movie Box"_.

**Comment by tonihei** [comment]
We'll post a workaround for the issue because it's quite easy to do. 

For the second stream above, there is actually yet another problem when switching the track selection from an embedded text track to a primary text track. That is a bug in our DashMediaPeriod. Will provide a fix for that too.

**Comment by islor** [comment]
The commit seems to have fixed the problem. Thanks!

**Comment by tonihei** [comment]
Closing because the second bug mentioned above (changing text tracks from embedded to primary) is also fixed now.
