### ISSUE TITLE
How to improve network speed(Wifi) when playback?

### ISSUE THREAD

**Issue by ssorttang** [google/ExoPlayer#4478]
Hi, 
I try to exoplayer on Gvrf(GearVR Framework).
but, I found some network problem when playback.
Network speed(Wifi) is decreasing when playback(56mb bit rate media).
I also compare to android mediaplayer. but network speed being decrease when using exoplayer..

So, How can I improve this problem?
I used mqtt protocol with node.js server.

And media specification is 
format : HEVC
bit rate : 56.0mb
Frame rate : 30 FPS
resolution : 4096 * 2048

**Comment by tonihei** [comment]
I'm not entirely sure what you mean by "network speed is decreasing". Do you mean that the file loads slowly? Given the high bitrate I think you need a very fast connection to play that over network.

**Comment by ssorttang** [comment]
Sorry. My English is not good. 
Actually, my application is doing communication with server every time.
So, I always checking network deviation between application and server.
But, Network deviation being increased after added Exoplayer. (eventhough not playback or loading)
I did change media player to Exoplayer. So I want know that problem's reason

**Comment by tonihei** [comment]
Are you checking the time difference between app and server? If yes, I don't think that is ExoPlayer related. It's probably an issue in your app with how you measure the difference.
