### ISSUE TITLE
Audio Stops playing after 1-2 seconds

### ISSUE THREAD

**Issue by drusak** [google/ExoPlayer#4479]
### Issue description
Some users of the app start complaining on playback problem. Audio stopped playing after 1-2 seconds of init playback. On some devices video working fine, but audio failing.
It started after upgrade ExoPlayer from 2.6.1 to 2.8.2

### Reproduction steps
I tried on my devices and it works fine. 
We're using SimpleCache in implementation probably it may lead to such behavior. 
So playback starts and in 1-2 second stops..
File container is mp4 mostly

### Version of ExoPlayer being used
issue starts after upgrade from 2.6.1 to 2.8.2

### Device(s) and version(s) of Android being used
Known devices:
Samsung S8 with Android 8.0
Samsung Galaxy S7 Edge with Android 7.0
Huawai LLD-L31 with Android 8.0.0

### A full bug report captured from the device

> 23:54:13:670 (UTC) | seekStarted [3.61, 0.00, window=0]
> 23:54:13:670 (UTC) | positionDiscontinuity [3.61, 0.00, window=0, SEEK]
> 23:54:13:677 (UTC) | state [3.61, 0.00, window=0, true, IDLE]
> 23:54:13:678 (UTC) | state [3.61, 0.00, window=0, true, BUFFERING]
> 23:54:13:681 (UTC) | timelineChanged [3.62, 0.00, window=0, periodCount=1, windowCount=1, reason=PREPARED
> 23:54:13:681 (UTC) |   period [?]
> 23:54:13:681 (UTC) |   window [?, false, false]
> 23:54:13:681 (UTC) | ]
> 23:54:13:681 (UTC) | seekProcessed [3.62, 0.00, window=0]
> 23:54:13:751 (UTC) | mediaPeriodCreated [3.69, 0.00, window=0, period=0]
> 23:54:13:751 (UTC) | loading [3.69, 0.00, window=0, period=0, true]
> 23:54:14:541 (UTC) | timelineChanged [4.48, 0.00, window=0, period=0, periodCount=1, windowCount=1, reason=DYNAMIC
> 23:54:14:541 (UTC) |   period [152.40]
> 23:54:14:541 (UTC) |   window [152.40, true, false]
> 23:54:14:541 (UTC) | ]
> 23:54:14:620 (UTC) | decoderEnabled [4.56, 0.00, window=0, period=0, audio]
> 23:54:14:620 (UTC) | tracksChanged [4.56, 0.00, window=0, period=0, []]
> 23:54:14:621 (UTC) | mediaPeriodReadingStarted [4.56, 0.00, window=0, period=0]
> 23:54:14:720 (UTC) | decoderInitialized [4.66, 0.00, window=0, period=0, audio, OMX.google.aac.decoder]
> 23:54:14:721 (UTC) | decoderInputFormatChanged [4.66, 0.00, window=0, period=0, audio, id=1, mimeType=audio/mp4a-latm, channels=2, sample_rate=48000, language=und]
> 23:54:14:721 (UTC) | downstreamFormatChanged [4.66, 0.00, window=0, period=0, id=1, mimeType=audio/mp4a-latm, channels=2, sample_rate=48000, language=und]
> 23:54:14:721 (UTC) | state [4.66, 0.00, window=0, period=0, true, READY]
> 23:54:14:788 (UTC) | audioSessionId [4.72, 0.00, window=0, period=0, 8801]
> 23:54:14:789 (UTC) | state [4.72, 0.00, window=0, period=0, false, READY]
> 23:54:14:908 (UTC) | loading [4.84, 0.00, window=0, period=0, false]
> 23:54:20:021 (UTC) | state [9.96, 0.00, window=0, period=0, true, READY]
> 23:54:20:078 (UTC) | state [10.01, 0.00, window=0, period=0, false, READY]
> 23:54:20:355 (UTC) | state [10.29, 0.01, window=0, period=0, true, READY]
> 23:54:20:420 (UTC) | state [10.36, 0.10, window=0, period=0, false, READY]
> 23:54:20:570 (UTC) | state [10.51, 0.10, window=0, period=0, true, READY]
> 23:54:20:635 (UTC) | state [10.57, 0.19, window=0, period=0, false, READY]
> 23:54:20:769 (UTC) | state [10.70, 0.20, window=0, period=0, true, READY]
> 23:54:20:833 (UTC) | state [10.77, 0.29, window=0, period=0, false, READY]
> 23:54:23:729 (UTC) | state [13.66, 0.29, window=0, period=0, true, READY]
> 23:54:23:786 (UTC) | state [13.72, 0.44, window=0, period=0, false, READY]
> 23:54:24:181 (UTC) | state [14.12, 0.44, window=0, period=0, true, READY]
> 23:54:24:239 (UTC) | state [14.18, 0.56, window=0, period=0, false, READY]
> 23:54:24:396 (UTC) | state [14.33, 0.56, window=0, period=0, true, READY]
> 23:54:24:451 (UTC) | state [14.39, 0.65, window=0, period=0, false, READY]
> 23:54:24:563 (UTC) | state [14.50, 0.66, window=0, period=0, true, READY]
> 23:54:24:618 (UTC) | state [14.55, 0.69, window=0, period=0, false, READY]
> 23:54:24:762 (UTC) | state [14.70, 0.70, window=0, period=0, true, READY]
> 23:54:24:824 (UTC) | state [14.76, 0.83, window=0, period=0, false, READY]
> 23:54:24:946 (UTC) | state [14.88, 0.85, window=0, period=0, true, READY]
> 23:54:25:004 (UTC) | state [14.94, 0.92, window=0, period=0, false, READY]
> 23:54:25:117 (UTC) | state [15.05, 0.93, window=0, period=0, true, READY]
> 23:54:25:172 (UTC) | state [15.11, 1.03, window=0, period=0, false, READY]
> 23:54:25:280 (UTC) | state [15.22, 1.03, window=0, period=0, true, READY]
> 23:54:25:338 (UTC) | state [15.27, 1.13, window=0, period=0, false, READY]
> 23:54:25:482 (UTC) | state [15.42, 1.14, window=0, period=0, true, READY]
> 23:54:25:541 (UTC) | state [15.48, 1.27, window=0, period=0, false, READY]
> 23:54:25:664 (UTC) | state [15.60, 1.28, window=0, period=0, true, READY]
> 23:54:25:720 (UTC) | state [15.66, 1.36, window=0, period=0, false, READY]
> 23:54:25:848 (UTC) | state [15.78, 1.36, window=0, period=0, true, READY]
> 23:54:25:906 (UTC) | state [15.84, 1.46, window=0, period=0, false, READY]
> 23:54:26:031 (UTC) | state [15.97, 1.47, window=0, period=0, true, READY]
> 23:54:26:088 (UTC) | state [16.02, 1.57, window=0, period=0, false, READY]
> 23:54:26:200 (UTC) | state [16.14, 1.57, window=0, period=0, true, READY]
> 23:54:26:254 (UTC) | state [16.19, 1.67, window=0, period=0, false, READY]

**Comment by tonihei** [comment]
The state changes in your log look like you are constantly calling `player.setPlayWhenReady(true);` and `player.setPlayWhenReady(false);` in a loop. Can you check where these calls are coming from? I guess that's the reason you are not seeing any progress.

**Comment by drusak** [comment]
thank you for the answer! I'll check it out. 
Strange thing that on major devices it works pretty well.

**Comment by drusak** [comment]
That was a very weird behavior in the app... So it is implementation issue. Thanks for pointing me in the  right direction
