### ISSUE TITLE
Background playback and notification

### ISSUE THREAD

**Issue by a-v-ebrahimi** [google/ExoPlayer#4482]
1) To keep audio playback alive in background, I need to start a foreground service or just displaying **PlayerNotificationManager** notification is enough and it puts my service in **whitelist** (see this for whitelist definition https://developer.android.com/about/versions/oreo/background)?
2) If I should start a foreground service, startForeground(id,notification) method needs a Notification. I am using PlayerNotificationManager.createWithNotificationChannel to add a notification to player, but I can't use this notification in startForeground (it's not public). Shall I display 2 notifications?!

**Comment by ojw28** [comment]
1. You do need a foreground service. The notification alone is not sufficient.
1. `PlayerNotificationManager` has callbacks that it invokes when it starts and stops showing a notification. You can use these to put your service into (and out of) the foreground. There's an example of this [here](https://github.com/google/ExoPlayer/blob/io18/audio-app/src/main/java/com/google/android/exoplayer/audiodemo/AudioPlayerService.java#L110).

**Comment by ojw28** [comment]
You may also find [this talk](https://www.youtube.com/watch?v=svdq1BWl4r8) helpful, which walks through much of the example I've linked to in my post above.
