### ISSUE TITLE
Make errors more human readable for debugging purposes

### ISSUE THREAD

**Issue by Nefcanto** [google/ExoPlayer#4486]
I have an application that works just fine and plays videos. I copy/pasted ExoPlayer to a new app, of course with different design, different layout resources, different logic, etc., and all of a sudden I get a cryptic message and it fails playing the video.

The same URL would be played nicely on the old app. So whatever the error is, it's related to the new app. But error messages are so cryptic and jibberish that it's almost impossible for me to find out the problem. I'm doing trial and error for 2 days now, changing everything from nesting in different layouts, up to changing configuration of ExoPlayer and no result. 

Can you please help developers by making errors more readable and more helpful by providing clear text on what's wrong and what we should do to make it work?

Here's my logcat, and red lines (errors I guess) are specified at the end of line:

```
I/ExoPlayerImpl: Init dc6a5c8 [ExoPlayerLib/2.8.2] [generic_x86, Android SDK built for x86, Google, 27]
D/SoftwareRenderer: setting dataspace on output surface to #104
D/AudioTrack: Client defaulted notificationFrames to 6000 for frameCount 12000
D/EGL_emulation: eglCreateContext: 0xb1065f40: maj 2 min 0 rcv 2
D/EGL_emulation: eglMakeCurrent: 0xb1065f40: ver 2 0 (tinfo 0x945ffcd0)
E/EGL_emulation: eglQueryContext 32c0  EGL_BAD_ATTRIBUTE // red line here
E/EGL_emulation: tid 31097: eglQueryContext(1777): error 0x3004 (EGL_BAD_ATTRIBUTE) // red line here
D/SurfaceUtils: connecting to surface 0x94306008, reason connectToSurface
I/MediaCodec: [OMX.google.h264.decoder] setting surface generation to 31719426
D/SurfaceUtils: disconnecting from surface 0x94306008, reason connectToSurface(reconnect)
D/SurfaceUtils: connecting to surface 0x94306008, reason connectToSurface(reconnect)
D/SurfaceUtils: disconnecting from surface 0x96e60008, reason disconnectFromSurface
I/zygote: Do partial code cache collection, code=499KB, data=277KB
I/zygote: After code cache collection, code=499KB, data=277KB
I/zygote: Increasing code cache capacity to 2MB
D/EGL_emulation: eglMakeCurrent: 0xa9405ea0: ver 2 0 (tinfo 0xa9403650)
I/chatty: uid=10089(com.hamrahfarda.amoozeshyar) RenderThread identical 1 line
D/EGL_emulation: eglMakeCurrent: 0xa9405ea0: ver 2 0 (tinfo 0xa9403650)
I/OMXClient: Treble IOmx obtained
D/SurfaceUtils: connecting to surface 0x96e6d008, reason connectToSurface
I/MediaCodec: [OMX.google.h264.decoder] setting surface generation to 31719427
D/SurfaceUtils: disconnecting from surface 0x96e6d008, reason connectToSurface(reconnect)
D/SurfaceUtils: connecting to surface 0x96e6d008, reason connectToSurface(reconnect)
E/ACodec: [OMX.google.h264.decoder] setPortMode on output to DynamicANWBuffer failed w/ err -1010 // red line here
I/ACodec: codec does not support config priority (err -1010)
I/OMXClient: Treble IOmx obtained
I/ACodec: codec does not support config priority (err -2147483648)
D/EGL_emulation: eglMakeCurrent: 0xa9405ea0: ver 2 0 (tinfo 0xa9403650)
D/AudioTrack: Client defaulted notificationFrames to 6000 for frameCount 12000
D/MediaCodec: [OMX.google.h264.decoder] setting dataspace on output surface to #104
D/SoftwareRenderer: setting dataspace on output surface to #104
D/EGL_emulation: eglMakeCurrent: 0xa9405ea0: ver 2 0 (tinfo 0xa9403650)
I/chatty: uid=10089(com.hamrahfarda.amoozeshyar) RenderThread identical 4 lines
D/EGL_emulation: eglMakeCurrent: 0xa9405ea0: ver 2 0 (tinfo 0xa9403650)
D/EGL_emulation: eglMakeCurrent: 0xa9405ea0: ver 2 0 (tinfo 0xa9403650)
I/chatty: uid=10089(com.hamrahfarda.amoozeshyar) RenderThread identical 23 lines
D/EGL_emulation: eglMakeCurrent: 0xa9405ea0: ver 2 0 (tinfo 0xa9403650)
D/AudioTrack: stop() called with 254976 frames delivered
D/EGL_emulation: eglMakeCurrent: 0xa9405ea0: ver 2 0 (tinfo 0xa9403650)
D/AudioTrack: stop() called with 254976 frames delivered
D/EGL_emulation: eglMakeCurrent: 0xa9405ea0: ver 2 0 (tinfo 0xa9403650)
D/EGL_emulation: eglMakeCurrent: 0xa9405ea0: ver 2 0 (tinfo 0xa9403650)
```
I read your template, and I tried to follow your guidelines, but no success. Can you help me figure out what the problem might be?

**Comment by botaydotcom** [comment]
Hi @nefcanto,
It seems to me you are trying the app on an emulator? Did you try the old app on the same emulator as well? If possible, can you try to run this on a real device to see if you encounter the same problem?

In any case, in the brief log section you provided, there was no error log from ExoPlayer, so I don't think we can change anything from our error logs here. Both red lines you highlight come from the underlying platform, and we have no authority over these logs unfortunately.

If you would like to get help in this case, please provide the required info from the bug template, including: the full bug report captured from the device, the device(s) and version(s) of Android used, and the link to the used test content. Thank you very much.

**Comment by Nefcanto** [comment]
Yeah, I'm trying to run it on emulator. But the other app also works on emulator and it works fine. I thought those logs are related to your library. Thank you for your feedback and clarification. But however, it would be very helpful if you _wrap the underlying problems and provide more meaningful messages_. That's possible. That's what we do for example for database errors. We wrap it, we get the exceptions it throws, and we provide better explanation for most common exceptions.

However, regarding this issue, let me try it first on a real device, and then I'll send the required info. I also appreciate your response.

**Comment by ojw28** [comment]
> But however, it would be very helpful if you wrap the underlying problems and provide more meaningful messages. That's possible.

Not necessarily. It's only possible if the underlying platform provides enough information in whatever error it throws to us, such that we can map it onto something more meaningful. If the underlying platform just throws `IllegalStateException` with no explanation, then there's not much we can really do. It's unclear what error is thrown to us here, or what error we end up propagating to you (i.e. the application), because neither is shown in the log snippet.

**Comment by Nefcanto** [comment]
That's why I hate android and Google. Develop applications with Microsoft platform, and you understand what I mean. Errors are truly descriptive and guide developers towards solving them. Such a stupid platform Google has created. OK guys, thank you so much for clarification.
