### ISSUE TITLE
How to show Multiple Notifications Download Progress for Multiple Downloads ?

### ISSUE THREAD

**Issue by ZohaibGhafoor** [google/ExoPlayer#4494]
i am using ExoPlayer demo Download. but when i start multiple download tasks they shows the progress of download in one download notification. So how i can show multiple notification progress for multiple downloads in demo app ?

**Comment by erdemguven** [comment]
From DemoDownloadService.getForegroundNotification() you can return whatever notification you want. This can be a notification for only one of the downloads too. You need to create other notifications manually for the other downloads.
