### ISSUE TITLE
Dropped Frames on DASH Widevine 60fps dynamic MPDs

### ISSUE THREAD

**Issue by zachmanc** [google/ExoPlayer#4496]
### Issue description
DASH dynamic 60 fps widevine encrypted content drops frames when playing back on some devices. The same stream url is able to play successfully using chrome and other Android devices.

### Reproduction steps
Sample project attached to the bug report email. We tried setting the `MediaFormat.KEY_OPERATING_RATE` and that did not help. Default renderers also show the problem

Here is a side-by-side comparison of two devices consuming the same 720p, 60FPS stream @3879kbps.
At the top is an LG-K210.
At the bottom is a Pixel XL 1st gen.
https://www.dropbox.com/s/f5toi3k4odyhbsf/IMG_1356.MOV?dl=1

Also attached is a screenshot of both devices’ decoding capabilities
https://www.dropbox.com/s/a18ar82jbxfeh5m/pixelxl-lgk210.jpg?dl=0

Screenshot of profiler showing high usage
https://www.dropbox.com/s/ee1luccbkmmsb8v/profileImage.png?dl=0

### Link to test content
Test content has been sent in the bug report email. 

### Version of ExoPlayer being used
2.8.2

### Device(s) and version(s) of Android being used
Not working
Pixel XL - Android 8.1.0
LG G3 - Android 7.0
Pixel - Android 8.1

Working
Pixel 2
LG-K210

### A full bug report captured from the device
Full bug report has been sent in the bug report email

**Comment by ojw28** [comment]
It looks like Chrome is using L3 to play the content. The following log line gets printed when it forces into L3 mode at the start of playback:
```
E cr_media: Security level: current L1, new L3
```

If we force ExoPlayer into L3 as well, using
```
mediaDrm.setPropertyString("securityLevel", "L3");
```
then we see better performance, as in Chrome.

@paf-wv / @jefftinker - Why is L1 worse than L3 in terms of performance on Pixel 1? And is it generally true that this is the case?

**Comment by paf-wv** [comment]
The team is looking into this now. There are other similar reports so reproducing it next steps for us internally.

**Comment by KarlGallagher** [comment]
This is also reproducible on the Samsung Galaxy Tab S3 (Snapdragon 820)
Android 8.0

Happens with both L1 and L3 here.

[bugreport-2018-07-25-14-06-39.zip](https://github.com/google/ExoPlayer/files/2227992/bugreport-2018-07-25-14-06-39.zip)

I have also sent an example stream and Widevine license proxy to dev.exoplayer@gmail.com

**Comment by KarlGallagher** [comment]
@ojw28 

Just a quick query...

I am given the impression from other discussions on this tracker that ExoPlayer based tests form part of the Android device certification process?

If so, is it worth considering adding a test for this specific use case (Widevine/720p/60fps)to the test lineup ?

**Comment by mayankchhajed** [comment]
@paf-wv - Do we have update on this ? 
We are running into this same issue when playing back DASH/WV stream on our Arcadyan box running ExoPlayer 2.5.x

Seeing jitters especially on the CNN Ticker

**Comment by KarlGallagher** [comment]
Is there any available update on this ticket?

**Comment by rrfrias** [comment]
Sorry for the delay. We are looking into this. While Widevine encrypted playback of 720p @ 60 fps should be supported, we do not have device compliance tests to verify this particular configuration, so YMMV. We are in the process of adding these tests.

**Comment by paf-wv** [comment]
We have verification tests for this type of content for Android TV but not for mobile devices at this time. However we are coming up with some tests in the near future for mobile.
