### ISSUE TITLE
How to playback 4K media on Oculus Go?

### ISSUE THREAD

**Issue by ssorttang** [google/ExoPlayer#4497]
Hi,
I try to exoplayer on Gvrf(GearVR Framework).
And I tried playback 4K media. 
But, that media wan't playback. I only can saw green screen in the Oculus Go.
I already playback this media which GearVR(Galaxy S8).
So, How can I playback on the Oculus Go?
I also tried using Samsung VR, Skybox Apps. but occurred same issue.

4K media specification is
Format : AVC
bit rate : 80.0mb
Frame rate : 30 FPS
Resolution : 4096 * 4096
File size : 393MB

**Comment by ojw28** [comment]
We don't have an Oculus Go to test this. You'd probably be best off reporting it to the Oculus team.

**Comment by ojw28** [comment]
As per comment above, I'd suggest you contact the Oculus team about this, in the first instance.
