### ISSUE TITLE
AAC：when play a AAC format file，seekTo method can't be supported

### ISSUE THREAD

**Issue by CHNfred** [google/ExoPlayer#4499]
when play a AAC format file，after call seekTo method，however, play it again！

**Comment by botaydotcom** [comment]
Currently we [don't support seeking](https://google.github.io/ExoPlayer/supported-formats.html) for ADTS (AAC), because it's not efficient to do so. We are looking into ways to do this, but unfortunately I can't provide any timeline when this will be done.
