### ISSUE TITLE
missing proguard file

### ISSUE THREAD

**Issue by nschwermann** [google/ExoPlayer#45]
I see that the recommended proguard settings for this project are on the gitignore list. I think it would be helpful to add this to the repository.

**Comment by simware** [comment]
I would like to have a proguard example as well, would be great!

**Comment by michalliu** [comment]
some extension class seems needs to be keeped since they are using native code

**Comment by michalliu** [comment]
I searched for string "Class.forName" through the whole project found that you should at least keep `com.google.android.exoplayer2.ext.*`

**Comment by ojw28** [comment]
Proguard is clever enough to handle `Class.forName(stringConstant)` automatically. What is the actual problem you're seeing?

**Comment by michalliu** [comment]
No problem, just want to enable proguard to make our app smaller. I am searching for proguard recommention and found this thread.
