### ISSUE TITLE
Adding parameter to m3u8 url to all ts

### ISSUE THREAD

**Issue by SystemRestored** [google/ExoPlayer#4501]
I have a m3u8 which is suppose like this, http://domain/hls/video.m3u8?token=variable.  Now the thing is when exoplayer opens, the url passes as it is, however the ts files when fetched, doesnot contain token and also the aes key url when fetched doesnot contain the token.  Inside the m3u8, no files includes token so is there any way to add the token at the behind of eache ts and aes token?

**Comment by AquilesCanta** [comment]
The right way would be to generate standalone playlists server side.

That being said, you could implement your own HlsPlaylistParser, and add them. Or implement your own HlsDataSourceFactory and add them when segments are requested. I think the safer way is to add them to the playlist parser. The latter way is a more ad hoc approach, although it should be considered as well, depending on how dynamic the tokens are.

Please close if this answers your question.

**Comment by ojw28** [comment]
The segment (and key) URLs are resolved against the base URL of the playlist as per RFC-3986. The query parameter specified in the base URL is not kept as part of this resolution. As mentioned above, the correct approach would be for your server to generate a playlist where the query parameter is copied into each of the contained URLs.
