### ISSUE TITLE
How to use okhttpclient in this code?

### ISSUE THREAD

**Issue by SystemRestored** [google/ExoPlayer#4503]
**Hello, I am sharing my current exoplayer code. Just need a okhttpclient to intercept the media source and add   .addQueryParameter("apikey", "your-actual-api-key")   to pass this query in every url exoplayer plays.  help please**

    public class exoplayer extends AppCompatActivity implements VideoRendererEventListener {

    private static final String TAG = "exoplayer";
    private SimpleExoPlayerView simpleExoPlayerView;
    private SimpleExoPlayer player;

    private static final DefaultBandwidthMeter bandwidthMeter = new DefaultBandwidthMeter();
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        requestWindowFeature(Window.FEATURE_NO_TITLE);
        getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);
        super.onCreate(savedInstanceState);
        getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN, WindowManager.LayoutParams.FLAG_FULLSCREEN);
        setContentView(R.layout.activity_exoplayer);

        TrackSelection.Factory videoTrackSelectionFactory = new AdaptiveTrackSelection.Factory(bandwidthMeter);
        TrackSelector trackSelector = new DefaultTrackSelector(videoTrackSelectionFactory);

        LoadControl loadControl = new DefaultLoadControl();

        player = ExoPlayerFactory.newSimpleInstance(this, trackSelector, loadControl);
        simpleExoPlayerView = new SimpleExoPlayerView(this);
        simpleExoPlayerView = (SimpleExoPlayerView) findViewById(R.id.player_view);

        simpleExoPlayerView.setUseController(true);
        simpleExoPlayerView.requestFocus();

        simpleExoPlayerView.setPlayer(player);

        Uri url = this.getIntent().getData();
        String streamUrl = url.toString();
        Uri mp4VideoUri =Uri.parse(streamUrl); 
     DefaultHttpDataSourceFactory dataSourceFactory = new DefaultHttpDataSourceFactory(Util.getUserAgent(this, "ExoPlayerDemo"), bandwidthMeter);
        dataSourceFactory.getDefaultRequestProperties().set("YOUR KEY", "YOUR VALUE");

        ExtractorsFactory extractorsFactory = new DefaultExtractorsFactory();

        MediaSource videoSource = new HlsMediaSource(mp4VideoUri, dataSourceFactory, 1, null, null);
        final LoopingMediaSource loopingSource = new LoopingMediaSource(videoSource);

        player.prepare(loopingSource);

        player.setPlayWhenReady(true); //run file/link when ready to play.
        player.setVideoDebugListener(this); //for listening to resolution change and  outputing the resolution
    }//End of onCreate

    @Override
    public void onVideoEnabled(DecoderCounters counters) {

    }

    @Override
    public void onVideoDecoderInitialized(String decoderName, long initializedTimestampMs, long initializationDurationMs) {

    }

    @Override
    public void onVideoInputFormatChanged(Format format) {

    }

    @Override
    public void onDroppedFrames(int count, long elapsedMs) {

    }

    @Override
    public void onVideoSizeChanged(int width, int height, int unappliedRotationDegrees, float pixelWidthHeightRatio) {
        Log.v(TAG, "onVideoSizeChanged ["  + " width: " + width + " height: " + height + "]");

    }

    @Override
    public void onRenderedFirstFrame(Surface surface) {

    }

    @Override
    public void onVideoDisabled(DecoderCounters counters) {

    }

    @Override
    protected void onStop() {
        super.onStop();
        Log.v(TAG, "onStop()...");
    }

    @Override
    protected void onStart() {
        super.onStart();
        Log.v(TAG, "onStart()...");
    }

    @Override
    protected void onResume() {
        super.onResume();
        Log.v(TAG, "onResume()...");
    }

    @Override
    protected void onPause() {
        super.onPause();
        Log.v(TAG, "onPause()...");
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        Log.v(TAG, "onDestroy()...");
        player.release();
    }
   }

**Comment by botaydotcom** [comment]
Hi @subhanjankayet,
You can make use of [ExoPlayer's OkHttp extension](https://github.com/google/ExoPlayer/tree/release-v2/extensions/okhttp).
Replace:
```
DefaultHttpDataSourceFactory dataSourceFactory =
    new DefaultHttpDataSourceFactory(
        Util.getUserAgent(this, "ExoPlayerDemo"), bandwidthMeter);
```
With:
```
OkHttpClient okHttpClient = new OkHttpClient();
HttpDataSourceFactory dataSourceFactory =
    new OkHttpDataSourceFactory(
        okHttpClient, Util.getUserAgent(this, "ExoPlayerDemo"), bandwidthMeter);
```
And you can do anything you want with the OkHttpClient.
