### ISSUE TITLE
HLS streams don't change quality

### ISSUE THREAD

**Issue by petermoser** [google/ExoPlayer#4508]
### Issue description
When I'm playing HLS media using ExoPlayer it keeps getting stuck in the lowest resolution track in the m3u8 playlist although the bandwidth would allow playing it at the highest bitrate.
When playing the same .m3u8 file on a iOS device the track with the correct bitrates are selected.

This issue also happen when using the Demo App.

To mitigate the issue we are setting the initial bitrate estimate to a number, e.g.:
bandwidthMeterBuilder.setInitialBitrateEstimate(2800000);
Now the highest bitrate track is displayed initially but when we are throttling the network connection (using Android Studio Simulator) or using Charles Proxy it doesn't switch to a lower bitrate track.

### Reproduction steps
1. Add the test content below to media.exolist.json in the HLS section.
2. Play the content.
3. Debug and set a breakpoint in AdaptiveTrackSelection determineIdealSelectedIndex. Note that the effectiveBitrate is stuck at the initialBitrateEstimate and the lowest bitrate HLS track is selected, even with full network speed. 

### Link to test content
http://cdn-dev.spotlight.social/uclips0318/peterpop_2018_38_11_11_38_46.m3u8

### Version of ExoPlayer being used
2.8.2

### Device(s) and version(s) of Android being used
Moto 4E
Pixel 2 (Siumlator)

**Comment by botaydotcom** [comment]
Hi @petermoser,
I have tested using the stream you provided, and the reason here is most likely because your test content is too short. In the default `AdaptiveTrackSelection` implementation, most switch up/ switch down decision takes into account the existing buffer size. So in your two cases:
- When you don't set any initial bit-rate estimation, the initial bit-rate estimation is 1 Mbps, which is only enough for your slowest resolution. After 1-2 chunks are loaded, the bit-rate estimation is probably revised, but the default implementation requires at least 10s of buffered media before switch up to a higher quality (to avoid chance of re-buffering when switch up). With your 15s content, it's mostly too late before the player can switch.
- On the second case, it's the other direction. The player probably detects that it needs to switch down after loading 1-2 chunks (and being throttled), but most likely it has already buffered the high quality chunks, and will not discard those.

To properly test the adaptation logic, please use a longer stream (there are a few HLS streams with longer duration in our sample list that you can try out).

**Comment by petermoser** [comment]
@botaydotcom thank you for your quick response! 
Unfortunately all our videos are very short, they are usually between 10-30s in length, so we need to have a bit-rate adaption within seconds.
 
For faster track selection we are using the values:

```
float bandwithFraction = .8f;
final int minDurationForQualityIncreaseMs = 1000;
final int minDurationForQualityDecreaseMs = 2000;
final int minDurationToRetainAfterDiscardMs = 2000;
trackSelectionFactory = new AdaptiveTrackSelection.Factory(BANDWIDTH_METER, minDurationForQualityIncreaseMs, minDurationForQualityDecreaseMs, minDurationToRetainAfterDiscardMs, bandwithFraction);
```
Although we are setting these values, the bitrate is not adapted during playback of the video.
Are there any other values that we have to configure to achieve a faster bit rate adaption?

**Comment by tonihei** [comment]
Just checking: have you passed the same bandwidth meter to the data source in HlsMediaSource?

**Comment by petermoser** [comment]
For testing I'm using the ExoPlayer Demo app, the only modification right now is the invocation of AdaptiveTrackSelection.Factory to increase the speed of the track selection (as described in previous message).

**Comment by tonihei** [comment]
Can't reproduce your problem. Just tested your stream with the parameter given above and it switches up fine after about 8.5 seconds.

**Comment by petermoser** [comment]
Interesting, @tonihei would you be able to give us some information on your test environment?

**Comment by tonihei** [comment]
I've been using a Nexus 6P in a good Wifi network. Could you please check whether your code ever reaches this line: https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/upstream/DefaultBandwidthMeter.java#L199

If not, then the bandwidth meter doesn't have enough information to provide a suitable estimate for the track selection. To reach this line you need to transfer at least 512 KB worth of data and the total transfer time needs to be at least 2 seconds.

**Comment by petermoser** [comment]
@tonihei, onTransferEnd is called, I attached the screenshot below. The bitrate is 2343113.
![image](https://user-images.githubusercontent.com/5367107/42705479-4b1fac86-8688-11e8-828a-01f0faaff513.png)

Right after that, getBitrateEstimate is called from AdaptiveTrackSelection::determineIdealSelectedIndex, see screenshot below:
![image](https://user-images.githubusercontent.com/5367107/42705691-fd7a04d0-8688-11e8-86fe-283a0a5e9f92.png)
The bitrate is 1000000! So the selected track in determineIdealSelectedIndex always stays the lowest bitrate track.

**Comment by petermoser** [comment]
@tonihei when debugging do you see the same? bitrateEstimate seems to be is back to the value of initialBitrateEstimate.

**Comment by AquilesCanta** [comment]
The only option I see is that in both cases you are looking at different instances. Is that a possibility?

**Comment by petermoser** [comment]
Every single call to getBitrateEstimate returns 100000. That would explain why the tracks are not changing.

**Comment by ojw28** [comment]
It sounds very much like you have multiple instances of `BandwidthMeter` floating around, rather than using the same one everywhere. If you're certain that's not the case, please provide a minimal patch to the demo app that allows us to reproduce what you're seeing.

**Comment by tonihei** [comment]
You need to make sure you use the same BandwidthMeter as a listener for the DataSource.Factory and in the TrackSelection.Factory. It sounds as this isn't the case here.

**Comment by petermoser** [comment]
Yes, @tonihei that was the problem, we needed to pass BandwidthMeter as a listener to DataSource.Factory:

```
...

    mDataSourceFactory = new DefaultDataSourceFactory(this, bandwidthMeter, buildHttpDataSourceFactory(bandwidthMeter));
    videoSource = new HlsMediaSource.Factory(mDataSourceFactory).createMediaSource(uri);

...

    // Build Http Data Source Factory using DefaultBandwidthMeter
    private HttpDataSource.Factory buildHttpDataSourceFactory(DefaultBandwidthMeter bandwidthMeter){
        return new DefaultHttpDataSourceFactory( "spotlight", bandwidthMeter);
    }
```

Thank you guys for the great support!
