### ISSUE TITLE
DashDownloader Playback error

### ISSUE THREAD

**Issue by basisworldwide** [google/ExoPlayer#4509]
Version of Exo: 2.7.3

Description

Attempting to playback an offline DASH using a stored widevine key. I'm able to complete all the pieces, and have a valid key and I see all the content being downloaded into the directory. However, when attempting playback i'm getting an error.

Sample Code:

//download method

      `  java.io.File downloadFolder = new java.io.File("/data/user/0/files/testt/");
        SimpleCache cache = new SimpleCache(downloadFolder, new NoOpCacheEvictor());

        DefaultHttpDataSourceFactory factory = new DefaultHttpDataSourceFactory("EXO Player");
        com.google.android.exoplayer2.offline.DownloaderConstructorHelper helper = new com.google.android.exoplayer2.offline.DownloaderConstructorHelper(cache, factory);
        com.google.android.exoplayer2.source.dash.offline.DashDownloader dashDownloader = new com.google.android.exoplayer2.source.dash.offline.DashDownloader(Uri.parse("https://test.com/example.mpd"), helper);

         //dashDownloader.selectRepresentations(new RepresentationKey[] {new RepresentationKey(0, 0, 0)});

         dashDownloader.download(new com.google.android.exoplayer2.offline.Downloader.ProgressListener() {
             @Override
             public void onDownloadProgress(com.google.android.exoplayer2.offline.Downloader downloader, float downloadPercentage, long downloadedBytes) {
              // Invoked periodically during the download.
                 Log.v("hi", "hi");
            }
         });`

//playback method

` java.io.File downloadFolder2 = new java.io.File("/data/user/0/files/testt/");
            DefaultHttpDataSourceFactory upstreamDataSourceFactory = new DefaultHttpDataSourceFactory("ExoPlayer", null);
            SimpleCache downloadCache = new SimpleCache(downloadFolder2, new NoOpCacheEvictor());
            CacheDataSourceFactory dataSourceFactory = new CacheDataSourceFactory(downloadCache, upstreamDataSourceFactory);
            ExtractorMediaSource mediaSource = new ExtractorMediaSource.Factory(dataSourceFactory)
                    .createMediaSource(Uri.parse("https://test.com/example.mpd"));
`

Current Error:

E/ExoPlayerImplInternal: Source error.
                         com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor) could read the stream.
                             at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractorHolder.selectExtractor(ExtractorMediaPeriod.java:924)
                             at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:846)
                             at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:308)
                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                             at java.lang.Thread.run(Thread.java:764)

**Comment by botaydotcom** [comment]
Hi @basisworldwide,
The error message points out that you are using `ExtractorMediaSource` for a DASH stream. Please use `DashMediaSource` for such case.
