### ISSUE TITLE
Offline playback still requires online connection

### ISSUE THREAD

**Issue by basisworldwide** [google/ExoPlayer#4512]
//Version
2.7.3

//Description
So we have the logic to do the offline playback...but when i go offline after the download the playback fails...but if I'm connected it plays back without issue. This seems to be the demo code, and if I swap out the HttpDataSource with a DefaultDataSource i'm getting errors

//Sample Code Download
```
        java.io.File downloadFolder = new java.io.File("/data/user/0/testing/");
        SimpleCache cache = new SimpleCache(downloadFolder, new NoOpCacheEvictor());

        DefaultHttpDataSourceFactory factory = new DefaultHttpDataSourceFactory("EXO Player");
        com.google.android.exoplayer2.offline.DownloaderConstructorHelper helper = new com.google.android.exoplayer2.offline.DownloaderConstructorHelper(cache, factory);
        com.google.android.exoplayer2.source.dash.offline.DashDownloader dashDownloader = new com.google.android.exoplayer2.source.dash.offline.DashDownloader(Uri.parse("https://test.com/test.mpd"), helper);

         //dashDownloader.selectRepresentations(new RepresentationKey[] {new RepresentationKey(0, 0, 0)});

         dashDownloader.download(new com.google.android.exoplayer2.offline.Downloader.ProgressListener() {
             @Override
             public void onDownloadProgress(com.google.android.exoplayer2.offline.Downloader downloader, float downloadPercentage, long downloadedBytes) {
              // Invoked periodically during the download.
                 Log.v("hi", "hi");
            }
         });
```

//Sample Code Offline Playback
```
            java.io.File downloadFolder2 = new java.io.File("/data/user/0/testing/");
            SimpleCache cache2 = new SimpleCache(downloadFolder2, new NoOpCacheEvictor());
            DefaultHttpDataSourceFactory factory2 = new DefaultHttpDataSourceFactory("ExoPlayer", null);
            DefaultDataSourceFactory defaultDataSource = new DefaultDataSourceFactory(this, "ExoPlayer");
            CacheDataSourceFactory mediaDataSourceFactory = new CacheDataSourceFactory(cache2, factory2, CacheDataSource.FLAG_BLOCK_ON_CACHE);
            DashMediaSource mediaSource = new DashMediaSource.Factory(
                    new DefaultDashChunkSource.Factory(defaultDataSource),
                    new CacheDataSourceFactory(cache2, factory2, CacheDataSource.FLAG_BLOCK_ON_CACHE)
            ).createMediaSource(Uri.parse("https://test.com/test.mpd"));
```

**Comment by basisworldwide** [comment]
Same issue when doing the following:

```
            FileDataSourceFactory fileDataSource = new FileDataSourceFactory();

            DashMediaSource mediaSource = new DashMediaSource(
                    Uri.parse("https://perksocial.com/splash/mpd.mpd"),
                    new CacheDataSourceFactory(
                        cache2, fileDataSource, CacheDataSource.FLAG_BLOCK_ON_CACHE),
                    new DefaultDashChunkSource.Factory(defaultDataSource),
                    null,
                    null
                    );
```

**Comment by erdemguven** [comment]
Looks like the https://perksocial.com/splash/mpd.mpd stream is drm protected. To be able to play it offline you need an offline licence. You can use OfflineLicenseHelper.downloadLicense to get one and for offline playback use com.google.android.exoplayer2.drm.DefaultDrmSessionManager#setMode method.

**Comment by basisworldwide** [comment]
@erdemguven it is a protected stream. I am currently calling the downloadLicense and playing it back for playback. Even with that call I don't get any error it just hangs, and if I remove it completely it just hangs the same way and doesn't give an errors.

I can give the  code in full if that might help.

```
//Download license code
DataSource dataSource = httpDataSourceFactory.createDataSource();
        DashManifest dashManifest = DashUtil.loadManifest(dataSource,
                Uri.parse("https://perksocial.com/splash/mpd.mpd")); //movie url
        DrmInitData drmInitData = DashUtil.loadDrmInitData(dataSource, dashManifest.getPeriod(0));
        offlineLicenseKeySetId = offlineLicenseHelper.downloadLicense(drmInitData);

//Set the playback
DefaultDrmSessionManager<FrameworkMediaCrypto> drmManager = buildDrmSessionManager("Hello Agent");

drmManager.setMode(DefaultDrmSessionManager.MODE_PLAYBACK, offlineLicenseKeySetId);

            // 1. Create a default TrackSelector
            BandwidthMeter bandwidthMeter = new DefaultBandwidthMeter();
            TrackSelection.Factory videoTrackSelectionFactory = new AdaptiveTrackSelection.Factory(bandwidthMeter);
            TrackSelector trackSelector = new DefaultTrackSelector(videoTrackSelectionFactory);

            // 2. Create a default LoadControl
            LoadControl loadControl = new DefaultLoadControl();

            // 3. Create the player
            player = ExoPlayerFactory.newSimpleInstance(this, trackSelector, loadControl, drmManager);
```

**Comment by erdemguven** [comment]
Please provide all of the information requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

**Comment by basisworldwide** [comment]
@erdemguven 

### Issue description
When I already have a saved offline key, and saved content I get the timeline to show and no error messages but the content never plays. If I attempt to the use the same piece of content while still connected to the internet everything is playback fine. I'm not getting any errors related to the key or anything.

### Reproduction steps
Describe how the issue can be reproduced, ideally using the ExoPlayer demo app.

### Link to test content
```

		//get the license
		widevineLicenseUrl = "https://perksocial.com/splash/proxy?content_id=1111"; //not real
		httpDataSourceFactory = new DefaultHttpDataSourceFactory("EXO TEST");
		offlineLicenseHelper = OfflineLicenseHelper.newWidevineInstance(widevineLicenseUrl, httpDataSourceFactory);
        DataSource dataSource = httpDataSourceFactory.createDataSource();
        DashManifest dashManifest = DashUtil.loadManifest(dataSource,
                Uri.parse("https://perksocial.com/splash/mpd.mpd")); //movie url
        DrmInitData drmInitData = DashUtil.loadDrmInitData(dataSource, dashManifest.getPeriod(0));
        byte[] offlineLicenseKeySetId = offlineLicenseHelper.downloadLicense(drmInitData);

        //download the content
		java.io.File downloadFolder = new java.io.File("/data/user/0/com.ayalus.exoplayer2example/ppparty/");
        SimpleCache cache = new SimpleCache(downloadFolder, new NoOpCacheEvictor());

        DefaultHttpDataSourceFactory factory = new DefaultHttpDataSourceFactory("EXO Player");
        com.google.android.exoplayer2.offline.DownloaderConstructorHelper helper = new com.google.android.exoplayer2.offline.DownloaderConstructorHelper(cache, factory);
        com.google.android.exoplayer2.source.dash.offline.DashDownloader dashDownloader = new com.google.android.exoplayer2.source.dash.offline.DashDownloader(Uri.parse("https://perksocial.com/splash/mpd.mpd"), helper);

        dashDownloader.download(new com.google.android.exoplayer2.offline.Downloader.ProgressListener() {
             @Override
             public void onDownloadProgress(com.google.android.exoplayer2.offline.Downloader downloader, float downloadPercentage, long downloadedBytes) {
                 Log.v("hi", "hi");
            }
        });

		//!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
        //MANUALLY DISCONNECT INTERNET CONNECTION IN DEBUGGER HERE
		//!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


		//read up from the local system
		java.io.File downloadFolder2 = new java.io.File("/data/user/0/com.ayalus.exoplayer2example/ppparty/");
        SimpleCache cache2 = new SimpleCache(downloadFolder2, new NoOpCacheEvictor());

        DefaultDataSourceFactory defaultDataSource = new DefaultDataSourceFactory(this, "ExoPlayer");

        //same result for this testing code block
        /*
        DashMediaSource mediaSource = new DashMediaSource.Factory(
            new DefaultDashChunkSource.Factory(defaultDataSource),
            new CacheDataSourceFactory(cache2, defaultDataSource, CacheDataSource.FLAG_BLOCK_ON_CACHE)
        );//.createMediaSource(Uri.parse("https://perksocial.com/splash/mpd.mpd"));
        */

        FileDataSourceFactory fileDataSource = new FileDataSourceFactory();

        DashMediaSource mediaSource = new DashMediaSource(
                Uri.parse("https://perksocial.com/splash/mpd.mpd"),
                new CacheDataSourceFactory(
                    cache2, fileDataSource, CacheDataSource.FLAG_BLOCK_ON_CACHE),
                new DefaultDashChunkSource.Factory(defaultDataSource),
                null,
                null
                );

        //get the drm session
        DefaultDrmSessionManager<FrameworkMediaCrypto> drmManager = buildDrmSessionManager("Hello Agent");

        drmManager.setMode(DefaultDrmSessionManager.MODE_PLAYBACK, offlineLicenseKeySetId);

        // 1. Create a default TrackSelector
        BandwidthMeter bandwidthMeter = new DefaultBandwidthMeter();
        TrackSelection.Factory videoTrackSelectionFactory = new AdaptiveTrackSelection.Factory(bandwidthMeter);
        TrackSelector trackSelector = new DefaultTrackSelector(videoTrackSelectionFactory);

        // 2. Create a default LoadControl
        LoadControl loadControl = new DefaultLoadControl();

        // 3. Create the player
        player = ExoPlayerFactory.newSimpleInstance(this, trackSelector, loadControl, drmManager);
        simpleExoPlayerView = new SimpleExoPlayerView(this);
        simpleExoPlayerView = (SimpleExoPlayerView) findViewById(R.id.player_view);

        //Set media controller
        simpleExoPlayerView.setUseController(true);
        simpleExoPlayerView.requestFocus();

        //play the asset - Josh
        player.prepare(mediaSource);

        // Bind the player to the view.
        simpleExoPlayerView.setPlayer(player);
```

### Version of ExoPlayer being used
2.7.1

### Device(s) and version(s) of Android being used
This is only tested in the emulator, but we will be using a new device which hasn't been released yet....Using Pixel 2 XL in the emulator

**Comment by basisworldwide** [comment]
This is from logcat when playing back

###Logcat
07-16 10:42:36.639 6965-6965/com.blah.exotest I/InstantRun: starting instant run server: is main process
07-16 10:42:37.070 6965-6965/com.blah.exotest W/oplayer2exampl: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (light greylist, reflection)
07-16 10:42:37.071 6965-6965/com.blah.exotest W/oplayer2exampl: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (light greylist, reflection)
07-16 10:42:37.135 6965-6965/com.blah.exotest D/OpenGLRenderer: Skia GL Pipeline
07-16 10:43:09.787 6965-6965/com.blah.exotest W/oplayer2exampl: Accessing hidden method Landroid/media/AudioTrack;->getLatency()I (light greylist, reflection)
07-16 10:43:09.802 6965-6965/com.blah.exotest I/ExoPlayerImpl: Init 9421d49 [ExoPlayerLib/2.7.3] [generic_x86, Android SDK built for x86, Google, 28]
07-16 10:43:09.941 6965-6965/com.blah.exotest V/MainActivity: onStart()...
07-16 10:43:09.943 6965-6965/com.blah.exotest V/MainActivity: onResume()...
07-16 10:43:10.018 6965-6965/com.blah.exotest V/StudioProfiler: StudioProfilers agent attached.
07-16 10:43:10.067 6965-7330/com.blah.exotest V/StudioProfiler: Acquiring Application for Events
07-16 10:43:10.140 6965-6965/com.blah.exotest V/StudioProfiler: Transformed class: java/net/URL
07-16 10:43:10.140 6965-6965/com.blah.exotest W/oplayer2exampl: Current dex file has more than one class in it. Calling RetransformClasses on this class might fail if no transformations are applied to it!
07-16 10:43:10.150 6965-7317/com.blah.exotest W/VideoCapabilities: Unrecognized profile 4 for video/hevc
07-16 10:43:10.213 6965-7317/com.blah.exotest I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
07-16 10:43:10.287 6965-7334/com.blah.exotest D/NetworkSecurityConfig: No Network Security Config specified, using platform default
07-16 10:43:10.547 6965-6965/com.blah.exotest V/StudioProfiler: Memory control stream started.
07-16 10:43:10.549 6965-6965/com.blah.exotest I/Choreographer: Skipped 37 frames!  The application may be doing too much work on its main thread.
07-16 10:43:10.646 6965-7319/com.blah.exotest I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
    android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
07-16 10:43:10.646 6965-7319/com.blah.exotest I/OpenGLRenderer: Initialized EGL, version 1.4
07-16 10:43:10.646 6965-7319/com.blah.exotest D/OpenGLRenderer: Swap behavior 1
07-16 10:43:10.647 6965-7319/com.blah.exotest W/OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
07-16 10:43:10.647 6965-7319/com.blah.exotest D/OpenGLRenderer: Swap behavior 0
07-16 10:43:10.647 6965-7319/com.blah.exotest D/EGL_emulation: eglCreateContext: 0xe434d200: maj 3 min 0 rcv 3
07-16 10:43:10.651 6965-7319/com.blah.exotest D/EGL_emulation: eglMakeCurrent: 0xe434d200: ver 3 0 (tinfo 0xe43679d0)
07-16 10:43:10.776 6965-7319/com.blah.exotest D/EGL_emulation: eglMakeCurrent: 0xe434d200: ver 3 0 (tinfo 0xe43679d0)
07-16 10:43:11.906 6965-7342/com.blah.exotest V/StudioProfiler: Live memory tracking disabled.
07-16 10:43:11.908 6965-7342/com.blah.exotest V/StudioProfiler: Live memory tracking enabled.
    JNIEnv not attached
07-16 10:43:12.100 6965-7342/com.blah.exotest V/StudioProfiler: Loaded classes: 11556
07-16 10:43:12.266 6965-7342/com.blah.exotest V/StudioProfiler: Tracking initialization took: 357999000ns
07-16 10:43:53.701 6965-7317/com.blah.exotest E/ExoPlayerImplInternal: Source error.

**Comment by erdemguven** [comment]
Could you provide real test content url and licence url so I can test?

**Comment by basisworldwide** [comment]
@erdemguven I have just sent the information to dev.exoplayer@gmail.com

Please let me know if you need anything else

**Comment by erdemguven** [comment]
I modified the demo app to download the license on startup and added your media to list of samples. I downloaded the media and put the device in airplane mode then started playback. Video plays fine on both real pixel 2 XL and emulator pixel XL.
Here is the patch:
https://gist.github.com/erdemguven/8c5fb4d87f084456c81245f553ba3a2f

**Comment by basisworldwide** [comment]
@erdemguven I just emailed the full source...the solution you provided I already had in place. I did swap out some of the data sources and got the first screen to show. However, I'm getting an internal error when trying to start playback.

The only thing I can think that could be preventing playback is i'm not passing any of the representation keys for what I wanted played back...but I would assume if that is empty it would just playback the first item similar to how the online version works.

**Comment by erdemguven** [comment]
Did you try the demo app with my patch? Did it work for you?

**Comment by basisworldwide** [comment]
I did not try that yet because the flow was slightly different. I didn’t see if your version downloads the asset for offline if so I can give that a try today.

Also did that use version 2.7.3 or a different version?

**Comment by erdemguven** [comment]
I used latest development version of ExoPlayer. You might need to do modifications to make it work for 2.7.*

Btw, I tried your code. To make it work you need to use CacheDataSource for loading chunks too:
```
            DashMediaSource mediaSource = new DashMediaSource(
                    Uri.parse("https://perksocial.com/splash/mpd.mpd"),
                    new CacheDataSourceFactory(
                            cache2, getDataSourceFactory(false), CacheDataSource.FLAG_BLOCK_ON_CACHE),
                    new DefaultDashChunkSource.Factory(new CacheDataSourceFactory(
                        cache2, getDataSourceFactory(false), CacheDataSource.FLAG_BLOCK_ON_CACHE)),
                    null,
                    null
            );
```
It works fine with this fix.

**Comment by basisworldwide** [comment]
It is still not working for me....I'm getting the following issue:

07-19 10:19:16.412 5134-5164/com.ayalus.exoplayer2example
E/ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.ParserException:
org.xmlpull.v1.XmlPullParserException: unterminated entity ref
(position:TEXT @3:458 in java.io.InputStreamReader@11d678b)
        at
com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parse(DashManifestParser.java:105)
        at
com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parse(DashManifestParser.java:58)
        at
com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:130)
        at
com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:308)
        at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: org.xmlpull.v1.XmlPullParserException: unterminated entity
ref (position:TEXT @3:458 in java.io.InputStreamReader@11d678b)
        at org.kxml2.io.KXmlParser.readEntity(KXmlParser.java:1220)
        at org.kxml2.io.KXmlParser.readValue(KXmlParser.java:1402)
        at org.kxml2.io.KXmlParser.next(KXmlParser.java:393)
        at org.kxml2.io.KXmlParser.next(KXmlParser.java:313)
        at
com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parse(DashManifestParser.java:98)
        at
com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parse(DashManifestParser.java:58)
        at
com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:130)
        at
com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:308)
        at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)

**Comment by erdemguven** [comment]
I tried your code on emulator (Pixel XL) and a real device (Nexus 6), and as far as I can see it works. Sorry, I don't think there's anything else we can do. You might want to try on real devices.

**Comment by erdemguven** [comment]
One small detail, I forgot to mention, is as the code you shared with us was missing the getDataSourceFactory() method I defined it as 
```
private DefaultHttpDataSourceFactory getDataSourceFactory(boolean b) {
    return new DefaultHttpDataSourceFactory("ExoPlayerPlaybackTests");
}
```
Hope that helps.
