### ISSUE TITLE
Bandwidth Listener

### ISSUE THREAD

**Issue by shri-hari93** [google/ExoPlayer#4515]
@ojw28 
Question: 
I'm interested in tracking the bitrate periodically when I play my dash source in exo player.
What I'm currently doing to achieve this is, by creating a bandwidth listener class that implements BandwidthMeter.Eventlistener where I override the method onbandwidthsample method. 
Then I create a bandwidthmeter object for the player with the bandwidthListener.

The problem that I'm facing is, onbandwidthsample is never being called when the dash source is being played. Is this an issue? or am I doing something wrong here?

Check below for my code:

```
private class BandwidthListener implements BandwidthMeter.EventListener{
        @Override
        public void onBandwidthSample(int elapsedMs, long bytes, long bitrate){
            Log.d("inside bandwidth:", String.valueOf(bitrate));
        }
    }

Handler mainHandler = new Handler();
BandwidthListener bandwidthListener = new BandwidthListener();
TrackSelection.Factory adaptiveTrackSelectionFactory =
                    new AdaptiveTrackSelection.Factory(new DefaultBandwidthMeter(mainHandler, bandwidthListener));
player = ExoPlayerFactory.newSimpleInstance(new DefaultRenderersFactory(this),
                    new DefaultTrackSelector(adaptiveTrackSelectionFactory), new DefaultLoadControl());
```

**Comment by sravan1213** [comment]
@shri-hari93 Are you passing same BandwidthMeter in you dataSourceFactory ??

example -
 `dataSourceFactory = new OkHttpDataSourceFactory(builder.build(), Util.getUserAgent(context,""), bandwidthMeter);`


`adaptiveTrackSelection = new AdaptiveTrackSelection.Factory(bandwidthMeter)`,

**Comment by ojw28** [comment]
@sravan1213 is probably correct (you're probably not passing the same `BandwidthMeter` instance).
