### ISSUE TITLE
Downloading Dash with side loaded subtitle text tracks

### ISSUE THREAD

**Issue by GustenB** [google/ExoPlayer#4518]
Hi!

When streaming online in our application we are side loading text tracks. In other words we are not using the text tracks which are declared in the manifest (this is stupid I know). As we are working on a dash download feature for offline view, I am wondering if there is solution to download the side loaded test tracks when downloading dash? How to handle the representation keys, as the filter parsing method will not provide correct data.

**Comment by erdemguven** [comment]
If you want to keep the subtitle in the cache as well, you can download the subtitle file using CacheUtil.cache(...) methods. I don't understand the problem with handling the representation keys.

**Comment by GustenB** [comment]
Thanks for your input, I guess this can help me?
https://medium.com/google-exoplayer/pre-caching-downloading-progressive-streams-in-exoplayer-3a816c75e8f6
or is there any other good example available?

**Comment by erdemguven** [comment]
Unfortunately there is no other example we provide for that method but it should be fairly easy to use.

One other way of downloading single files is using ProgressiveDownloader, which uses CacheUtil.cache(). This way you can use DownloadManager/Server.
