### ISSUE TITLE
Exoplayer video does not scale when SurfaceView is scaled

### ISSUE THREAD

**Issue by iceteahh** [google/ExoPlayer#452]
i'm using `Exoplayer` library to create video player application. I'm trying to make a feature like youtube: drag video player to bottom and i will be scaled to smaller size. To do that, i have used [ViewDragHelper](https://developer.android.com/reference/android/support/v4/widget/ViewDragHelper.html) When player is dragging, i scale it size like this:

     public void onViewPositionChanged(View changedView, int left, int top, int dx, int dy) {
            mTop = top;

            mDragOffset = (float) top / mDragRange;

            mVideoView.setPivotX(mHeaderView.getWidth());
            mVideoView.setPivotY(mHeaderView.getHeight());
            mVideoView.setScaleX(1 - mDragOffset / 2);
            mVideoView.setScaleY(1 - mDragOffset / 2);

            mDescView.setAlpha(1 - mDragOffset);
            requestLayout();
        } 
`mVideoView` is a `SurfaceView`, and player take `SurfaceView` to render it content. The `SurfaceView` scale correctly but it's content doesn't.

**Question: how can scale `SurfaceView` and it's content too?**

**Comment by ened** [comment]
@iceteahh can you try the same thing with a TextureView? From my understanding, SurfaceView is quite limited.

**Comment by ojw28** [comment]
TextureView may well work for this purpose, although does consume more power. I've also heard anecdotal evidence that calling SurfaceView.getHolder().setFixedSize() may resolve the issue, although I'm not entirely sure what values should be passed. Might be something to experiment with in any case.

**Comment by oleynikd** [comment]
Have you figured out how to solve this issue?
Thanks.
