### ISSUE TITLE
DASH - Position of Representation in MPD makes Exoplayer not read subtitles

### ISSUE THREAD

**Issue by pscplayco** [google/ExoPlayer#4524]
While testing subtitles on a DASH streaming with Exoplayer v1.5, I noticed the position of the Representation within the adaptation set in an MPD Manifest can lead Exoplayer to not be able to read subtitles. More specifically, 

1) If Representation is set in the Manifest before the SegmentTemplate --> Exoplayer doesn't read subtitles.
2) If Representation is set after the SegmentTemplate --> Exoplayer gets the subtitles properly

I've tested the DASH_IF player with option 1) and 2), and subtitles works fine with either. I don't have the DASH specification to get to know if something is said regarding the position of those elements, but found nothing in Internet. I will leave here links to both Manifest versions:

http://dev-cdn-lb.parsifalentertainment.com/Tests/Bento4_BENTO4TESTSUBS5_NoDrm/Representation_before_SegmentTemplate.mpd

http://dev-cdn-lb.parsifalentertainment.com/Tests/Bento4_BENTO4TESTSUBS5_NoDrm/Representation_after_SegmentTemplate.mpd

Is there any version update maybe fixing this issue? Thanks in advance

**Comment by ojw28** [comment]
My reading of the DASH specification is that only order (2) is valid. The syntax for adaptation sets is defined using `xs:sequence`, which I think means they need to be in the specified order (if present):

```
<xs:sequence>
   ...
   <xs:element name="SegmentTemplate" type="SegmentTemplateType" minOccurs="0"/>
   <xs:element name="Representation" type="RepresentationType" minOccurs="0" .../>
   ...
</xs:sequence>
```
