### ISSUE TITLE
Playing a MP4 file F.frameRate always return -1

### ISSUE THREAD

**Issue by qeadsw** [google/ExoPlayer#4525]
implements AnalyticsListener
onDecoderInputFormatChanged(EventTime eventTime, int type, Format format)
format.bitrate and format.frameRate always -1

My Version 2.8.2

**Comment by ojw28** [comment]
This information isn't always available for all stream types, and is documented to be `Format.NO_VALUE` (which equals -1) in such cases.

Specifically for HLS we're adding bitrate information soon. This is tracked by https://github.com/google/ExoPlayer/issues/3297. For regular MP4 files the information is just not available, sorry.

**Comment by qeadsw** [comment]
Will it be supported in a later release ？

**Comment by ojw28** [comment]
We don't have any plans to support this.
