### ISSUE TITLE
How to reduce increasing latency for RTMP live stream

### ISSUE THREAD

**Issue by AdamGrzybkowski** [google/ExoPlayer#4526]
I'm having issues with increasing latency over time when playing RTMP stream.

The problem occurs only when the stream needs to be buffered during playback. Every time this happens the latency increases. 

I'm aware this is not an issue with ExoPlayer itself, but maybe you could help me how to handle that? 

I know that LoadControl is responsible for buffer strategy but in overall I would like to get rid of this buffer. Not like totally but whenever we need to buffer we should skip all frames and start buffering the latest frames so that the latency will not increase.

I could listen for `Player.STATE_BUFFERING` state and when this occurs call `player.seekToDefaultPosition()` but I'm not sure if this is the right approach.

**Comment by ojw28** [comment]
If the approach you mention works, then I'd probably suggest doing that. ExoPlayer doesn't skip forward to the live edge automatically.

**Comment by AdamGrzybkowski** [comment]
@ojw28 looks like this solution works fine, thanks :) You can close the issue
