### ISSUE TITLE
TrackSelectionView: Provide option to hide Unknown text tracks

### ISSUE THREAD

**Issue by paavalan** [google/ExoPlayer#4527]
want to hide **Unknown** Track in subtitles.

![image](https://user-images.githubusercontent.com/8317058/42833033-b12da074-8a10-11e8-997e-8cf0b1a9baa8.png)

ExoPlayer : v2.8.2

**Comment by ojw28** [comment]
You'd need to fork or enhance `TrackSelectionView` to support that. Please feel free to send us a pull request if you want to add this functionality.

**Comment by paavalan** [comment]
@ojw28 now i am hiding via 

dialogPair.second.removeViewAt(4);

Sure. i will implement a function in TrackSelectionView  and send pull request

**Comment by ojw28** [comment]
If you want to send us a pull request for this then you're still welcome, but I'm going to close this because we're not planning on ever looking at it ourselves.
