### ISSUE TITLE
I tried to monitor the online video rate, but there was no trigger.

### ISSUE THREAD

**Issue by qeadsw** [google/ExoPlayer#4529]
I'm using version 2.8.2. Maybe I'm too stupid. Could you please help me modify it and send it to me completely? Thank you very much.
------------------------------------------------------------------------------------------------------------------------
    	DefaultBandwidthMeter.Builder builder = new DefaultBandwidthMeter.Builder();
        builder.setEventListener(new Handler(), new BandwidthMeter.EventListener() {
            @Override
            public void onBandwidthSample(int elapsedMs, long bytes, long bitrate) {
                Log.i("TAG", "onBandwidthSample: " + elapsedMs + "_" + bytes + "_" + bitrate);
            }
        });
        DefaultBandwidthMeter defaultBandwidthMeter = builder.build();
        AdaptiveTrackSelection.Factory factory = new AdaptiveTrackSelection.Factory(defaultBandwidthMeter);

        DataSource.Factory defaultDataSourceFactory = new DefaultDataSourceFactory(context, name, defaultBandwidthMeter);
        ExtractorMediaSource.Factory emsf = new ExtractorMediaSource.Factory(defaultDataSourceFactory);
        TrackSelector trackSelector = new DefaultTrackSelector(factory);
        SimpleExoPlayer simpleExoPlayer = ExoPlayerFactory.newSimpleInstance(context, trackSelector);
        simpleExoPlayer.setVideoSurfaceView(surfaceView);
        Uri U = Uri.parse(urlmp4);
        ExtractorMediaSource EMS = emsf.createMediaSource(U);
        simpleExoPlayer.prepare(EMS);
        simpleExoPlayer.setPlayWhenReady(true);

**Comment by ojw28** [comment]
The code looks fine, but you may get very infrequent bit-rate updates (possibly only at the end of playback, depending on the type of source).

The bandwidth meter is really designed for adaptive playback cases (DASH, SmoothStreaming, HLS), where bit-rate measurements can actually be used for something useful in the player (i.e. adapting to a different quality stream). When doing a DASH/SS/HLS playback you should see frequent bandwidth updates.

**Comment by qeadsw** [comment]
@ojw28 

I want to get the video real-time network speed is there any relevant interface or method?

**Comment by ojw28** [comment]
This isn't something we really support for non-adaptive playbacks. It's unclear what you'd actually do with that information.

**Comment by qeadsw** [comment]
@ojw28 

I want to know the real-time data flow when playing,
Is there a corresponding method?

In other words, I want to know the network resources of video in real time, and only for video.

**Comment by ojw28** [comment]
This question is already answered by my response above.
