### ISSUE TITLE
HDCP and Secure Path Supported in L3?

### ISSUE THREAD

**Issue by Mamietti** [google/ExoPlayer#4530]
I'm attempting to implement Widevine L3 into an Android phone, but whenever HDCP and Secure Path are needed, Exoplayer (withExtensionsDebug, version 2.8.0) tests fail after 12 seconds. These ones pass:
WV: HDCP not specified
WV: HDCP not required
WV: 30s licence duration(fails at ~30sec)

The documentation provided in my issue does not explicitly specify what is supported in L3, the Google documentation just vaguely tells "Run Widevine DASH Policy Tests successfully", and the support has been unresponsive.

However, there have been several similar issues in here that point to hardware security being unavailable.

https://github.com/google/ExoPlayer/issues/2776
"Failure is expected when using L3 Widevine if the license policy requires an HDCP level"
 
https://github.com/google/ExoPlayer/issues/1457
"(Nexus 10 is) a level 3 (no hardware DRM support) device, if your policy specifies HDCP required or a secure data path, you will get this error."

I need explicit confirmation, so I know whether I am doing something wrong or it's just working as intended.

**Comment by ojw28** [comment]
I can explicitly confirm this is working as intended.
