### ISSUE TITLE
EOFException, when I play mp4 file

### ISSUE THREAD

**Issue by junburg** [google/ExoPlayer#4531]
I am now creating a DataSource that can be decoded every 4096 bytes of video. So I implemented the following logic. The decryption logic has not yet been inserted. It was to see if the original video was driven from the following sources. However, the original video does not go back after coding as below.

> 
> public class CustomDataSource implements DataSource {
> 
>     private long fileLength;
>     private ByteBuffer bb;
>     ScatteringByteChannel sbc ;
>     private long read;
>     private ByteBuffer encBuffer;
>     private Uri uri;
>     private EnDecryptVideo enDecryptVideo;
>     private DataSpec dataSpec;
> 
>     public CustomDataSource(DataSpec dataSpec, EnDecryptVideo enDecryptVideo) {
>         this.enDecryptVideo = enDecryptVideo;
>         this.dataSpec = dataSpec;
>     }
>     @Override
>     public long open(DataSpec dataSpec) throws IOException {
>         FileInputStream ios = new FileInputStream(dataSpec.uri.getPath());
>         fileLength = dataSpec.length;
>         bb = ByteBuffer.allocate(4096);
>         sbc = ios.getChannel();
>         read = 0;
>         uri = dataSpec.uri;
> 
>         return fileLength;
>     }
> 
>     public int read() throws IOException {
>         if(read == 0) {
>             read = sbc.read(bb);
>             encBuffer = ByteBuffer.wrap(bb.array());
>         }
> 
>         if(read > 0) {
>             read-=1;
>             return encBuffer.get();
>         } else {
>             return -1;
>         }
>     }
> 
>     @Override
>     public int read(byte[] b, int off, int len) throws IOException {
>         if (b == null) {
>             throw new NullPointerException();
>         } else if (off < 0 || len < 0 || len > b.length - off) {
>             throw new IndexOutOfBoundsException();
>         } else if (len == 0) {
>             return 0;
>         }
> 
>         int c = read();
> 
>         if (c == -1) {
>             return -1;
>         }
> 
>         b[off] = (byte) c;
> 
>         int i = 1;
> 
>         try {
>             for (; i < len ; i++) {
>                 c = read();
>                 if (c == -1) {
>                     break;
>                 }
>                 b[off + i] = (byte) c;
>             }
>         } catch (IOException ee) {
>         }
>         return i;
>     }
> 
>     @Override
>     public Uri getUri() {
>         return uri;
>     }
> 
>     @Override
>     public void close() throws IOException {
>         if(sbc != null) {
>             sbc.close();
>         }
>         sbc = null;
>     }
> }
> 

I need to adjust the buffer size because I have to decode every 4096 bytes. yes, I'm using my own logic. Errors will result in an EOFException dropping.

> 
> 07-18 21:16:58.304 31271-31430/com.example.junburg.exoplayerpractice2 E/ExoPlayerImplInternal: Source error.
>     java.io.EOFException
>         at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFromDataSource(DefaultExtractorInput.java:265)
>         at com.google.android.exoplayer2.extractor.DefaultExtractorInput.skipFully(DefaultExtractorInput.java:102)
>         at com.google.android.exoplayer2.extractor.DefaultExtractorInput.skipFully(DefaultExtractorInput.java:110)
>         at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:349)
>         at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:186)
>         at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:860)
>         at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:317)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
>         at java.lang.Thread.run(Thread.java:762)

So, what is the problem, How can this logic work?

**Comment by ojw28** [comment]
Debugging your own custom components is not within the scope of this issue tracker, sorry.
