### ISSUE TITLE
After an online mp4 cache is finished, how to export the cache file to a standard mp4 file.

### ISSUE THREAD

**Issue by qeadsw** [google/ExoPlayer#4540]
If the cache is complete what if I export a standard video file?

**Comment by qeadsw** [comment]
Tracking this method is always 49 bytes less.  "CachedContent.getCachedBytesLength()"

**Comment by ojw28** [comment]
Our caching components are not designed for exporting video files, and we make no guarantee as to the format of the files on disk (e.g. we may write extra metadata into the files, and we may change the format over time). If you want this kind of functionality then you should implement your own code to download files.
