### ISSUE TITLE
Default Simultaneous Downloads bug.

### ISSUE THREAD

**Issue by ZohaibGhafoor** [google/ExoPlayer#4544]
in DownloadManager DEFAULT_MAX_SIMULTANEOUS_DOWNLOADS = 1; but when i start downloads multiple media like 6 or 7 it downloads 2 media same time not 1;

**Comment by erdemguven** [comment]
I don't see any problem in the code and can't repeat the issue.
Please provide the information asked in the issue template: https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE

**Comment by ZohaibGhafoor** [comment]
@erdemguven for example when i start 5 multiple downloads then in getForegroundNotification taskStates variable has 2 started downloads and 3 queued. but DEFAULT_MAX_SIMULTANEOUS_DOWNLOADS = 1. so it should download 1 media at a time not 2 .

**Comment by erdemguven** [comment]
How do you create DownloadManager? If you're using the DemoDownloadService code, it sets maxSimultaneousDownloads parameter to 2.

**Comment by ZohaibGhafoor** [comment]
@erdemguven no it isn't . yes i am using DemoDownloadService it sets to 1 not 2 . if it is 2 then can you please give me reference of file and line number.

**Comment by ZohaibGhafoor** [comment]
@erdemguven aaahhh ok got it it is defined in DemoApplication file. let me solve my issue and check Thankyou so much for help and solving my biggest problem.
