### ISSUE TITLE
Bug: unable to avoid interruption of audio by phone call

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [google/ExoPlayer#4546]
I'm trying to have a behavior on an app that plays a video, to continue playing without interruptions (including audio), even if there is a phone call.

For this, I tried to use:

        player!!.audioAttributes = AudioAttributes.Builder().setFlags(C.FLAG_AUDIBILITY_ENFORCED).setUsage(C.USAGE_NOTIFICATION_RINGTONE).setContentType(C.CONTENT_TYPE_SPEECH).build()

But when the video plays, and I get an incoming phone call, I can hear both the phone ringtone and the video (thought the video volume is very low it's almost not heard).

Please fix this bug, and if the code is wrong, please let me know how to fix it .

Attached sample project to show issue.
Tested on Pixel 2 with Android P DP4.
[ExoPlayerTest.zip](https://github.com/google/ExoPlayer/files/2216908/ExoPlayerTest.zip)

To reproduce:
1. Open app. Let video play (it plays in a loop). Make sure you hear its audio
2. Have an incoming call while the video plays.
3. Listen

**Comment by AndroidDeveloperLB** [comment]
In case I just do something wrong in code, I decided to write about this here:

https://stackoverflow.com/q/51464531/878126

**Comment by ojw28** [comment]
Can you please explain your use case (i.e. why do you want to do this)? Allowing an app to suppress the ringtone sounds like a bad idea to me (and I'd hope that it's not possible, at least without some kind of special permission).

**Comment by AndroidDeveloperLB** [comment]
Why a bad idea? Apps can do so much more than this. Apps can even turn on Do-not-disturb, if the user grants them this permission. I don't see what's wrong here.

My use case is as I wrote. To show a video that will continue playing with audio, without having incoming calls interrupting. 

For the app I was given to develop, I need to actually play a video (with sound) when there is an incoming call, as a replacement of the ringtone. Of course, I don't want to do something that will affect the OS system wide, because this will lead to new issues, especially if the app would crash or be uninstalled. That's why I prefer not to use DND or audio-mute, if possible.

**Comment by ojw28** [comment]
It's not something I'd want apps to be able to do, as a user. Just my personal opinion. At least with do-not-disturb mode, that would be reflected to the user in the notification bar.

That aside, I don't think it's possible to configure ExoPlayer (or MediaPlayer) in a way that it will cause it to suppress the ringtone. You may or may not be able to suppress the ringtone some other way via Android APIs (it sounds like you've researched this a bit), but that wouldn't really be an ExoPlayer question/feature. @andrewlewis might be able to confirm.

**Comment by AndroidDeveloperLB** [comment]
First of all, just because you see something in the notification bar, you don't know which app did this.
If at all, it should have shown a notification of which app has changed it.
Just like what I think should be done for other cases.

But anyway, this is wrong to say "It's not something I'd want apps to be able to do, as a user". There are so many users out there, and you didn't see the app yet and you already say you won't want it. Imagine that instead of a static photo of the person you know of, you'd see his video while he's calling you, or some video clip that is related to him (example : "Cotton eye joe" if his name is "Joe").

Many users think such a thing is cool, and I see it on various apps on the Play Store. Just because you don't like some feature, doesn't mean others won't like it too.
The API exists for people to use it, for various cool ideas. 

Same thing occurred this year about accessibility services. Google didn't like the fact that so many apps use it, even though it's not quite for "disabled" people. But tons of websites and users talked about how useful it is for the special cases (example: automation tools such as Tasker might need it), so Google left it alone for now (or so it seems). 

Why do you say it might not be possible? So why does this API exist if not for focus of audio to the current app? Only to give others focus? But then what's the point of these various flags related to ringtones and calls?

Can you at least consider adding this on Android P, if such a thing doesn't exist?

**Comment by andrewlewis** [comment]
I'm not aware of a way to suppress the ringtone, though you might get a more authoritative answer on the AOSP issue tracker.

If your use case is to play a video when there's an incoming call, perhaps implementing a custom calling app would be better. This seems to be supported since Marshmallow: see [Build a calling app](https://developer.android.com/guide/topics/connectivity/telecom/selfManaged). I'm not sure whether this allows for customization of the 'incoming call' screen, but it's probably worth a try!

**Comment by AndroidDeveloperLB** [comment]
Can you please check it out though? The docs seem to mean that it is possible?

I mean, what do the flags I used (in the first post) mean, if not that? 

About building a calling app, I'm aware of this (and I've found a nice sample for it, [**here**](https://github.com/arekolek/simple-phone)), and suggested this solution too. It does replace the whole UI of the calls, and I think it's very cool, and that I don't know of any app out there that does it. The link you've provided seems nice, but does it have a full working sample (I can't see it), which includes handling of all cases?

However, it's a huge amount of work, because we need to implement all types of calls and their operations (video calls, conference, ...) , and so this caused a different direction of decisions by the team managers, to show on-top view instead, that might or might not show in full screen.

I wanted to find a solution for the huge amount of work. Some solution in the middle, that if the user can't see the needed feature on our app (example : video call) , he could go to the built-in app, but I couldn't find an API for this, so I requested it [**here** ](https://issuetracker.google.com/issues/110862208) and [**here**](https://issuetracker.google.com/issues/110894922). I also don't like the fact that in order to change just the UI, we have to really be a dialer app (even more work), so I requested to be more modular about it, [**here** ](https://issuetracker.google.com/issues/110887179). I even went far for immersive mode, as I know for sure many users hate the heads-up notification of phone calls, and requested to have control about it, [**here** ](https://issuetracker.google.com/issues/110862206) and [**here**](https://issuetracker.google.com/issues/111154123)

Maybe because of the huge amount of work and the responsibility of it, no other app has done it so far.

**Comment by andrewlewis** [comment]
I suspect your app's audio is automatically being ducked if you're using a build from API 26 onwards, though I'm not certain (you could see what happens on an earlier API version to check this, if you want).

A custom calling app seems like the right way to achieve the result you're aiming for. As it's not an ExoPlayer bug or feature request, we can't provide further guidance here I'm afraid.

**Comment by AndroidDeveloperLB** [comment]
It's related to ExoPlayer, since it's a part of the API that the ExoPlayer provides, including the docs, which are from the fraemework, and used on ExoPlayer.

Can you please explain the meaning and the purpose of the flags I've used, then? 
If it's not for calls and ringtones ([**USAGE_NOTIFICATION_RINGTONE** ](https://developer.android.com/reference/android/media/AudioAttributes.html#USAGE_NOTIFICATION_RINGTONE), [**CONTENT_TYPE_SPEECH**](https://developer.android.com/reference/android/media/AudioAttributes.html#CONTENT_TYPE_SPEECH)) , and not for forcing audio focus on the player ([**FLAG_AUDIBILITY_ENFORCED**](https://developer.android.com/reference/android/media/AudioAttributes.html#FLAG_AUDIBILITY_ENFORCED)) , then what are those used for? 

Are there other, more suitable flags, perhaps? 

Since it's a part of the framework, I consider this a bug. See, it really exists on ExoPlayer, and it doesn't even have docs there :

https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/C.java

**Comment by andrewlewis** [comment]
Our docs are linking to the javadoc on the framework constants which you've found already.

Assuming your ringtones contain speech, those settings look fine to me, but you'll need to use them in your custom calling app not in a media playback app that isn't integrated into the telecom subsystem.

**Comment by AndroidDeveloperLB** [comment]
Again, the docs don't explain it well. Not sure that the linking works, but it's probably because I have compileSdk 28.

What are ringtones that contain speech? Those that tell who's the caller, using text-to-speech ? 

Are there better flags to use in this case, that will work for ExoPlayer even if the current app isn't the current dialer? 

It's too bad that even if I do need to replace the UI of calling, I can't do it without being the default dialer, and I can't use the built in dialer for cases that weren't implemented yet.

Replacing the dialer also requires API 26 and above, BTW, which isn't so popular :
https://developer.android.com/reference/android/Manifest.permission#MANAGE_OWN_CALLS
Yet somehow I see it's possible from API 23, as done on the sample project I wrote about. Anyway, I've requested a demo for the docs, [here ](https://issuetracker.google.com/issues/111722620).

**Comment by andrewlewis** [comment]
> What are ringtones that contain speech? Those that tell who's the caller, using text-to-speech ?
> Are there better flags to use in this case, that will work for ExoPlayer even if the current app isn't the current dialer?

I don't think so. You mentioned audio attributes with `CONTENT_TYPE_SPEECH` above, but for a ringtone sound effect this should probably be `CONTENT_TYPE_SONIFICATION` instead (I doubt it will make any difference to what happens when there's an incoming call, though).

**Comment by AndroidDeveloperLB** [comment]
That's too bad.
Can you please consider adding this, then?
Here:
https://issuetracker.google.com/issues/111785360
