### ISSUE TITLE
Support multiple tracks and at arbitrary insert points

### ISSUE THREAD

**Issue by JofArnold** [google/ExoPlayer#4549]
Hi. Just to confirm I dug through the code, issues, API and SO posts (caveat: my Java is weak) and I can't find if you support this feature.

I wish to make a video editing tool where I can insert video and audio at any point in time, trim video and audio, and layer multiple audio tracks (see sketch). This has to happen in realtime so ffmpeg isn't an option. This is fairly straightforward to do in iOS via `AVMutableComposition` etc but appears not possible without low level work in Android. The files are to be read from the filesystem and I have control over their encoding ahead of time. I do not need to persist the final result to the filesystem.

If ExoPlayer can support this, I'd love to know. If not, consider this a feature request :)

Potential workaround: I'm currently considering solutions involving concatenating 1second "blank" placeholder mp3 and mp4 files using `ConcatenatingMediaSource` to fill in the gaps. That doesn't solve the multitrack requirement though - especially as some video files will come with their own audio tracks - so any other thoughts here very much welcome!

Here is a sketch to clarify. One video track from two videos with gap in middle, 2 audio tracks. "audio3" could, for instance, be the audio track from the video.

Thank you.

```
------------------------------------------------
|                                              |
|   [-- audio1.mp3 --]  [-- audio2.mp3 --]     |
|                                              |
| [------ audio3.mp3 --------------------]     |
|                                              |
|[----- video1.mp4 ----]   [-- video2.mp4 --]  |
|                                              |
------------------------------------------------
```

**Comment by AquilesCanta** [comment]
Unfortunately, this is not something we support.

In terms of media composition, you should look at ClippingMediaSource, ConcatenatingMediaSource and MergingMediaSource. We don't support silence insertion. Our track architecture would not fit well in the described scenario. For example, for merging media sources, we enforce media period count matching. Finally, there are a few issues in this tracker about multi audio track synchronization. For example, #4261.

I'd suggest you try to distill more fine-grained requests out of this. It's not perfectly clear what the feature is. I can see quite a few different lines of work. Admittedly, this escapes a bit the main aim of exoplayer, which is media streaming. Feel free to open new feature requests for more specific and well defined features.

**Comment by andrewlewis** [comment]
In addition to what @AquilesCanta said, here are some tips that might help setting this up. It's likely to end up being a lot of work, and we won't be able to provide much more detailed guidance at the moment I'm afraid.
- To work around the limitations with merging media with start/end times that don't match up, you could set up a separate player for the audio streams.
- Then you can synchronize the player positions by making the video-only player's renderer provide a media clock to its player that references the audio player's position (which will be used instead of a standalone realtime media clock).
- It's possible to implement a custom media source that outputs silent raw audio if you need to insert that in the audio concatenation.

**Comment by JofArnold** [comment]
Thanks for the details. That makes sense. 

My concern about running multiple concurrent media players was that I read there’s a limit to how many instances can run at the same time. Do you know if this is the case? I need to support back to 5.0 and I can imagine some devices of that era are quite memory limited, for instance.

Note the players do not (and in fact should not) interact with the read of the OS with notifications and so forth. That may be a useful factor.

**Comment by andrewlewis** [comment]
> My concern about running multiple concurrent media players was that I read there’s a limit to how many instances can run at the same time. Do you know if this is the case? I need to support back to 5.0 and I can imagine some devices of that era are quite memory limited, for instance.

Yes. However, this is generally more of a problem when using multiple video decoders where hardware-accelerated codecs are used (see also #1286), whereas audio decoding will use software codecs. There is a limit on the total amount of audio track buffer size that can be allocated by all players, but I expect you won't encounter this with just a few players.
