### ISSUE TITLE
Youtube Embedded url  not playing 

### ISSUE THREAD

**Issue by sreereddymenon** [google/ExoPlayer#455]
Hello .

I am using ExoPlayer Library in my app.

My url looks like : 
" https://www.youtube.com/embed/OZScqcKFK_E"

Its not playing  . i have used all the types of RendererBuilder..Thanks

**Comment by ojw28** [comment]
- The initial vimeo URL you posted plays fine for me with TYPE_MP4.
- YouTube embed URLs aren't valid things that standalone media players can play (unless they just open a browser or WebView to play them).
