### ISSUE TITLE
How to get available seek range on a Dash live stream?

### ISSUE THREAD

**Issue by islor** [google/ExoPlayer#4550]
I'm trying to get the seekable range for a live stream from the player.
Can someone point me to the right direction? Do I use getCurrentTimeline? If so, what should I do next?
I need the range because my team has already implemented our own control view for our generic video player. So we're not going to be using the PlayerControlView. I've seen it mentioned that this is implemented but can't seem to find any guide for it.

Thanks!

**Comment by tonihei** [comment]
Please have a look at the explanation of our media model [here](https://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/Timeline.html).
In particular, the "window" should be the seekable range in the live stream. You can access the information about the relative position of the window to the period by using `window.positionInFirstPeriodUs` and `period.positionInWindowUs`. Please note that ExoPlayer's `seekTo` operations use the window as the time base, so `player.seekTo(0)` seeks to the start of the current window.

**Comment by islor** [comment]
@tonihei what's the difference between positionInFirstPeriodUs and positionInFirstPeriodMs? In particular, what does Us denote?

**Comment by tonihei** [comment]
Microseconds (typically "μs", but using Greek letters in code is of course a bit difficult, so "us")

**Comment by islor** [comment]
Oh right, thanks! let me try out your suggestions
