### ISSUE TITLE
Error while playing encrypted streams on S7 Edge : Error decrypting data: unspecified error

### ISSUE THREAD

**Issue by fredduarte** [google/ExoPlayer#4552]
### Issue description
We are having an issue with DASH playback of protected content with Widevine Modular DRM
when playing any of our streams on our customer app.

Whenever we play protected content with the DASH and DRM specs from above,
we get the following error message:
```
Message: com.google.android.exoplayer2.ExoPlaybackException
com.google.android.exoplayer2.ExoPlaybackException
at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:765)
at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:568)
at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:518)
at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:301)
at android.os.Handler.dispatchMessage(Handler.java:98)
at android.os.Looper.loop(Looper.java:154)
at android.os.HandlerThread.run(HandlerThread.java:61)
Caused by: android.media.MediaCodec$CryptoException: Error decrypting data: unspecified error
at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:2478)
at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:756)
... 6 more
```

This issue is always happening with Samsung Galaxy S7 Edge (**SM-G935F**) running on Android 7.0.

### Reproduction steps
Playing any stream from our customer app with S7 Edge.

### Link to test content
I can provide a link to the content via email if it's required.

### Version of ExoPlayer being used
Tested with ExoPlayer 2.7.0

### Device(s) and version(s) of Android being used
Samsung Galaxy S7 Edge - **SM-G935F**

### A full bug report captured from the device
FULL bug report from device: [bugreport-2018-07-18-13-32-27.zip](https://github.com/google/ExoPlayer/files/2218716/bugreport-2018-07-18-13-32-27.zip)

Charles Proxy Logs: [encrypted_ssl_samsung_s7_edge.zip](https://github.com/google/ExoPlayer/files/2218820/encrypted_ssl_samsung_s7_edge.zip)

**Comment by AquilesCanta** [comment]
Please provide the sample stream, it might be useful. @paf-wv, could you take a look?

**Comment by fredduarte** [comment]
Hi, @AquilesCanta @paf-wv .

In order to play one of our streams we have an authentication process
that needs to be done every time.
I will create an temp user for you to test.

Is there an email which i can send you a small list of steps
on how to play the stream?

**Comment by AquilesCanta** [comment]
dev.exoplayer@gmail.com

Thanks

**Comment by rrfrias** [comment]
@fredduarte, are you seeing playback of this stream failing on devices other than the S7?

**Comment by hp197** [comment]
@rrfrias not that we are aware of yet.
Maybe on the S8 or S9 (we couldn't verify).
We have verified with the S6 and that worked as expected.

Please also note that bug report is from a S7 Edge (while I dont think the edge option does make any difference).

**Comment by rrfrias** [comment]
Thanks for that information. Can you can send repro steps to dev.exoplayer@gmail.com?

**Comment by fredduarte** [comment]
I've just sent the email with the steps. If you have any questions on it, let me know.

**Comment by rrfrias** [comment]
We were able to play the test stream without issue on two versions of ExoPlayerV2.  
- The first ExoPlayerV2 is a very old version (>1 year old)
- The second is a newer ExoPlayerV2 version pulled from github on June 18th. The stream on this version played for ~90 minutes without issue.

This might be an issue with that particular device rather than all versions of Samsung Galaxy S7 Edge? We can still follow up with Samsung. Are you seeing this on more than one device?

This is the device info:
Device: Samsung Galaxy S7 Edge
OS Version: Android 7.0 (N)
OS Build #: hero2lte:7.0/NRD90M/G935FXXU1DQB7:user/release      
CDM: v4.0.0-android     
OEMCrypto (L1): Version 11
OEMCrypto (L3): Version 11
SoC: Samsung Exynos 8890

**Comment by fredduarte** [comment]
Hi, again.
Thank you for looking into the issue for us, we really appreciate it.

First, yes it was happening on all versions of the S7 Edge, but, it was just this device.

We’ve continued looking into the issue and we’ve made a configuration change
in the Widevine license.

The issue was solved by changing the securityLevel from “HW_SECURE_ALL” to “SW_SECURE_CRYPTO” in the HD track type in the Widevine license.
So it's not happening anymore.

Again, thank you for helping us investigate this.

**Comment by paf-wv** [comment]
We have not been able to repro internally. Closing.
