### ISSUE TITLE
Cannot play RTSP and M3U8 format video!

### ISSUE THREAD

**Issue by qeadsw** [google/ExoPlayer#4554]
This is the address that provides the test.

rtsp://184.72.239.149/vod/mp4://BigBuckBunny_175k.mov
http://live.hkstv.hk.lxdns.com/live/hks/playlist.m3u8

**Comment by qeadsw** [comment]
@aquilescanta @ojw28

**Comment by AquilesCanta** [comment]
The HLS stream seems to be working fine. 
For RTSP support, see #55.
