### ISSUE TITLE
Build codecs string from SPS data when unavailable elsewhere

### ISSUE THREAD

**Issue by mkarthick92** [google/ExoPlayer#4555]
Hi,
 We are facing issue in playing the URL, which was working fine 
 but the audio and seek bar is working but the video is not working, below URL 
"https://sprngpodmw.igolgi.net:8080/webdav/index/index.m3u8"
The video URL is some computer VLC player but not play the some one and face the same issue ..

The above URL is not getting played in any android version. Please send your suggestions to resolve this issue

If i play the video URL in latest ExoPlayer at that time select the track selection to click the video and the view like below image 

![device-2018-07-24-124123](https://user-images.githubusercontent.com/41435481/43122549-198f164c-8f3f-11e8-8754-b7f36e818add.png)

the audio and seek-bar works after the video option is selected none.

**Comment by AquilesCanta** [comment]
@tonihei, would you mind looking at this? The issue is only reproducible after a several loops of repeat mode, increasingly noticeable. It's caused by the audio track somehow drifting from the video. If you disable the audio, the issue does not reproduce. If you don't think it's related to repeat mode, just assign back to me.

**Comment by AquilesCanta** [comment]
[Internal ref: b/111782123]. The video uses a profile that is not supported on Android:

```
Video: h264 (High 4:2:2) ([27][0][0][0] / 0x001B), yuv422p(progressive), 720x480 [SAR 32:27 DAR 16:9], 29.97 fps, 29.97 tbr, 90k tbn, 59.94 tbc
```

I am going to use this issue to build the codecs string from SPS data. 

@mkarthick92 Unfortunately there is no more we can do if the encoding is not supported by the underlying platform.

**Comment by AquilesCanta** [comment]
If the track is now detected as unsupported, then there is not much else we can do. Thanks for reporting.
