### ISSUE TITLE
SelectionOverride parameters

### ISSUE THREAD

**Issue by vinayjoglekar** [google/ExoPlayer#4562]
Hi,
I am completely confused between parameters given for **DefaultTrackSelector.SelectionOverride** method and `parametersBuilder.setSelectionOverride` method.

`DefaultTrackSelector.SelectionOverride override = new DefaultTrackSelector.SelectionOverride(int groupIndex, int... tracks);`

`DefaultTrackSelector.ParametersBuilder parametersBuilder = mDefaultTrackSelector.buildUponParameters();
        parametersBuilder.setRendererDisabled(rendererIndex, isDisabled);
            parametersBuilder.setSelectionOverride(rendererIndex, mDefaultTrackSelector.getCurrentMappedTrackInfo().getTrackGroups(rendererIndex), override);`

What is groupIndex,  int... tracks & rendererIndex?

Thanks.

**Comment by AquilesCanta** [comment]
Hi @vinayjoglekar, each method contains a bit of useful javadoc that might help narrow down questions. It's not the purpose of this issue tracker to document stuff. If we take out an improvement opportunity out of the questions, we'll update the javadocs, but we cannot provide a full blown tutorial here.

The [developer guide](https://google.github.io/ExoPlayer/guide.html) will probably clear some doubts. Once you understand what a renderer is, the index should make sense. 

TrackGroups are the way tracks (audio, video, subtitles, etc) are represented in ExoPlayer. They are grouped according to adaptability. A non-adaptive track (example: The audio track in an mp3 file) is a track group with a single track. The track group and track indices refer to specific tracks. The [default track selector's javadoc](https://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/trackselection/DefaultTrackSelector.html) includes lots of info as well.

Hopefully this helps.

**Comment by vinayjoglekar** [comment]
Thanks, @AquilesCanta 

Can these methods be used to toggle between multiple subtitles tracks?

```
if (object.getSubtitles().size() > 0) {
            MediaSource[] mediaSources = new MediaSource[object.getSubtitles().size() + 1];
            mediaSources[0] = videoMediaSource;
            int i = 1;
            for (String language : object.getSubtitles().keySet()) {
                String subtitleUrl = object.getSubtitles().get(language).get(0).getSrc();
                Format subtitleFormat = Format.createTextSampleFormat(null, MimeTypes.APPLICATION_SUBRIP, C.SELECTION_FLAG_DEFAULT, language);
                mediaSources[i] = new SingleSampleMediaSource.Factory(new DefaultHttpDataSourceFactory(userAgent, BANDWIDTH_METER)).createMediaSource(Uri.parse(subtitleUrl), subtitleFormat, C.TIME_UNSET);
                i++;
            }
            mMergedMediaSource = new MergingMediaSource(mediaSources);
        }
```


```
MappingTrackSelector.MappedTrackInfo mappedTrackInfo =mDefaultTrackSelector.getCurrentMappedTrackInfo();
TrackGroupArray rendererTrackGroups = mappedTrackInfo == null ? null : mappedTrackInfo.getTrackGroups(SUBTITLE_TRACK_GROUP_INDEX);
DefaultTrackSelector.SelectionOverride selectionOverride = new DefaultTrackSelector.SelectionOverride(SUBTITLE_TRACK_GROUP_INDEX, mCaptionsTrackIndex);
mDefaultTrackSelector.setParameters(mDefaultTrackSelector.buildUponParameters().setSelectionOverride(SUBTITLE_TRACK_GROUP_INDEX, rendererTrackGroups, selectionOverride));
```

In above code, SUBTITLE_TRACK_GROUP_INDEX is 2 which is track group number from trackselector for subtitles and mCaptionsTrackIndex is index within rendererTrackGroups which needs to be selected. 
The above code always selects first element from rendererTrackGroup array even if mCaptionsTrackIndex changes.
