### ISSUE TITLE
Add a way to force update DownloadService notification

### ISSUE THREAD

**Issue by ZohaibGhafoor** [google/ExoPlayer#4563]
in Demo App how i can set or update Download Notification Large Icon Asynchronously when it retrive from server ?

**Comment by erdemguven** [comment]
DownloadNotificationUtil doesn't support setting large icon currently. You need build your notification yourself to set a large icon. What do you mean by setting asynchronously?

**Comment by ZohaibGhafoor** [comment]
@erdemguven asynchronously means when getForegroundNotification show notification. then in getForegroundNotification method i also fetch bitmap from remote server when image bitmap comes back i need to update the notification large_icon or any other data to show on the notification.

**Comment by erdemguven** [comment]
I think you need to create a new notification and replace the existing one using Service.startForeground() method or you can just wait until the next time getForegroundNotification is called and return the new notification.

**Comment by ojw28** [comment]
Do we want `DownloadService` sub-classes calling `startForeground` directly? It probably works, but it seems slightly error prone (e.g. I think they might have to make sure not to do this immediately after `DownloadService.stop` is called), and mildly inconvenient (e.g. they have to keep a copy of `foregroundNotificationId`, and probably the `taskStates` most recently passed to `getForegroundNotification`). 

Perhaps we should add a protected `DownloadService.invalidateForegroundNotification` method, that sub-classes can call when they want to provide a new foreground notification. Calling this method would cause `getForegroundNotification` to be invoked again, but only when appropriate (e.g. not if the service is being stopped).

What do you think?
