### ISSUE TITLE
Freeze when playing IMA ads with mid-roll

### ISSUE THREAD

**Issue by EusebioMorell** [google/ExoPlayer#4565]
### Issue description

When playing HLS live streams with IMA ads with pre-roll and mid-roll, ExoPlayer freezes at the beginning of the ad, in BUFFERING state. I expected the ad to be shown and the video to continue normally.

If calling 'seekTo' at the beginning, ExoPlayer manages to play the pre-roll ad, but it still freezes in the mid-roll ad.

I reproduced this on "demo-ima" app.

### Reproduction steps

In the 'demo-ima' app:

Modified the following lines in the 'strings.xml' file, like this:

`<string name="content_url"><![CDATA[http://skynews-go-hls.ak-cdn.skydvn.com/skynews/1404/latest.m3u8]]></string>`

`<string name="ad_tag_url"><![CDATA[https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpostpod&cmsid=496&vid=short_onecue&correlator=]]></string>`

Calling 'seekTo' after 'setPlayWhenReady' may help to show the pre-roll, but will still freeze in mid-roll.

### Link to test content

HLS stream URL:

http://skynews-go-hls.ak-cdn.skydvn.com/skynews/1404/latest.m3u8

Ads URLs:

From IMA samples page: https://developers.google.com/interactive-media-ads/docs/sdks/html5/tags

Used "VMAP Pre-, Mid-, and Post-rolls, Single Ads":

[VMAP Pre-, Mid-, and Post-rolls, Single Ads](https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpostpod&cmsid=496&vid=short_onecue&correlator=)

### Version of ExoPlayer being used

ExoPlayer version 2.8.2.

### Device(s) and version(s) of Android being used

Device: Motorola Phone (Moto G4).
Android version: 6.0.1

**Comment by AquilesCanta** [comment]
@andrewlewis, would you mind having a look?

**Comment by AquilesCanta** [comment]
The HLS stream seems to work ok without ads.

**Comment by andrewlewis** [comment]
Using IMA to insert midroll ads in live streams isn't a use case we support at the moment, I'm afraid. The ad tags have fixed cue points and it's unclear how to handle the player position when resuming the live stream after playing a midroll. It's better to use server-side ad insertion or in-stream metadata about ad breaks for this use case.

**Comment by Maneesh528** [comment]
I am also trying to integrate HLS and IMAads but I am facing issue
