### ISSUE TITLE
ExoPlayer dash multistream support

### ISSUE THREAD

**Issue by deniotokiari** [google/ExoPlayer#4566]
Does exoplayer supports multistreaming of few secured dash streams? 
For example I have to implement screen with two or more video views with different streams.

**Comment by AquilesCanta** [comment]
I don't think ExoPlayer imposes any limitations in this sense. As far as I know, this depends on platform resource availability. The best way to know is to experiment around in, I think. You might encounter issues depending on the number of available decoders in the device.
