### ISSUE TITLE
HLS Download selecting quality

### ISSUE THREAD

**Issue by armanhi** [google/ExoPlayer#4567]
Hi, I'm trying to accomplish exactly what's described in issue https://github.com/google/ExoPlayer/issues/4177, but I haven't managed to do so even using an HlsDownloader to list qualities to the user.

Can you give me any hint on how it can be done?

Thanks!

**Comment by erdemguven** [comment]
Please take a look at this post: https://medium.com/google-exoplayer/downloading-adaptive-streams-37191f9776e

**Comment by armanhi** [comment]
Oh, haven't seen it. Thank you very much!
