### ISSUE TITLE
How to use transportControls.playFromUri

### ISSUE THREAD

**Issue by Lukaaaa** [google/ExoPlayer#4572]
I just want to start an audio live stream. How can this be achieved, i have tried:
``` transportControls.playFromUri(Uri.parse("http://mp3stream2.apasf.apa.at:8000/"), null) ```

and also implemented the method in UampPlaybackPreparer
```
override fun onPrepareFromUri(uri: Uri?, extras: Bundle?) {
            val mediaSource = ExtractorMediaSource.Factory(dataSourceFactory).createMediaSource(uri));
            exoPlayer.prepare(mediaSource)
}
```
onPrepareFromUri is never called and requested stream does not start. 
Could you provide a short snipped/explanation how to play an audio livestream from static URL.

**Comment by marcbaechinger** [comment]
You are doing the right thing. The snippet you show should work. 

If you've taken the code from UAMP, I think you may also have taken over `getSupportedPrepareActions()` which returns the actions the `UampPlaybackPreparer` supports. UAMP does not support all actions. So you may want to add the                     `PlaybackStateCompat.ACTION_PLAY_FROM_URI `to the method to make sure the connector calls the preparer when `transportControls.playFromUri` is called:

    override fun getSupportedPrepareActions(): Long =
            PlaybackStateCompat.ACTION_PREPARE_FROM_MEDIA_ID or
                    PlaybackStateCompat.ACTION_PLAY_FROM_MEDIA_ID or
                    PlaybackStateCompat.ACTION_PREPARE_FROM_SEARCH or
                    PlaybackStateCompat.ACTION_PLAY_FROM_SEARCH or
                    PlaybackStateCompat.ACTION_PLAY_FROM_URI

https://github.com/googlesamples/android-UniversalMusicPlayer/blob/master/media/src/main/java/com/example/android/uamp/media/UampPlaybackPreparer.kt#L52

**Comment by Lukaaaa** [comment]
@marcbaechinger yes, took the sample code from UAMP. Thx a lot it works (ACTION was missing in getSupportedPrepareActions) !! And this is the right way to play audio livestrem?
