### ISSUE TITLE
App crashing exoplayer

### ISSUE THREAD

**Issue by chetan8378** [google/ExoPlayer#4577]
07-26 12:44:10.666 498-529/? E/InputDispatcher: channel '424fc288 com.pinnacle.karaoke/com.pinnacle.karaoke.activity.VideosFromSDCardActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
07-26 12:44:10.666 498-529/? E/InputDispatcher: channel '425654e8 com.pinnacle.karaoke/com.pinnacle.karaoke.activity.VideoPlaybackActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
07-26 12:44:10.666 131-2244/? E/OMXNodeInstance: !!! Observer died. Quickly, do something, ... anything...
07-26 12:44:10.696 131-3362/? E/ThreadWorker: Worker is already running.
07-26 12:44:11.226 3377-3377/com.pinnacle.karaoke E/dalvikvm: Could not find class 'android.app.job.JobScheduler', referenced from method com.google.android.gms.internal.zzcfp.zzazu
07-26 12:44:11.236 3377-3377/com.pinnacle.karaoke E/dalvikvm: Could not find class 'android.app.job.JobScheduler', referenced from method com.google.android.gms.internal.zzcfp.zzs
07-26 12:44:11.356 3377-3377/com.pinnacle.karaoke E/dalvikvm: Could not find class 'android.graphics.drawable.RippleDrawable', referenced from method android.support.v7.widget.AppCompatImageHelper.hasOverlappingRendering
07-26 12:44:11.586 3377-3377/com.pinnacle.karaoke E/yonghe: SerialPortService onCreate....

**Comment by AquilesCanta** [comment]
This issue is being closed because it does not adhere to our issue template, and/or because it omits information requested in the issue template that is required for us to investigate the problem efficiently. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

If you’re able to provide complete information as requested in the issue template, please do so below and we’ll re-open the issue. Thanks!

**Comment by chetan8378** [comment]
Please check out with this log


08-04 11:48:54.327 1820-2820/com.pinnacle.karaoke E/omx_video: amvenc_avc open failed!set default instance number as 1,ret=-1,Permission denied(13)
08-04 11:48:54.327 1820-2820/com.pinnacle.karaoke E/OMXMaster: A component of name 'OMX.google.alac.decoder' already exists, ignoring this one.
08-04 11:48:54.467 130-239/? E/ion: ioctl c0144900 failed with code -1: Out of memory
08-04 11:48:54.467 130-239/? E/[Gralloc-ERROR]: int gralloc_alloc_buffer(alloc_device_t*, size_t, int, const native_handle_t**):119 Failed to ion_alloc from ion_client:20
08-04 11:48:54.467 130-239/? E/BufferQueue: [SurfaceView] dequeueBuffer: SurfaceComposer::createGraphicBuffer failed
08-04 11:48:54.467 1820-2817/com.pinnacle.karaoke E/ACodec: dequeueBuffer failed.
08-04 11:48:59.157 1820-2815/com.pinnacle.karaoke A/libc: Fatal signal 11 (SIGSEGV) at 0x321e0bf8 (code=1), thread 2815 (Loader:Extracto)
08-04 11:48:59.607 502-531/? E/InputDispatcher: channel '41df7fe0 com.pinnacle.karaoke/com.pinnacle.karaoke.activity.VideosFromSDCardActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
08-04 11:49:00.047 2838-2838/com.pinnacle.karaoke E/dalvikvm: Could not find class 'android.app.job.JobScheduler', referenced from method com.google.android.gms.internal.zzcfp.zzazu
08-04 11:49:00.047 2838-2838/com.pinnacle.karaoke E/dalvikvm: Could not find class 'android.app.job.JobScheduler', referenced from method com.google.android.gms.internal.zzcfp.zzs
08-04 11:49:00.177 2838-2838/com.pinnacle.karaoke E/dalvikvm: Could not find class 'android.graphics.drawable.RippleDrawable', referenced from method android.support.v7.widget.AppCompatImageHelper.hasOverlappingRendering
