### ISSUE TITLE
Get the time we connect to a live stream

### ISSUE THREAD

**Issue by rohangoqii** [google/ExoPlayer#4578]
How do I retrieve the time of the video that I connect to a live stream? 

Let's say I connect to a live stream on two different devices, both have connected to the live stream at different times, one connects 20 sec into a stream the other 40 seconds into the stream. I want to be able to show the different time on each device(actual time into the video). How do I achieve this?

**Comment by AquilesCanta** [comment]
What kind of stream are you playing? I think the only way to achieve this is to provide timing metadata in your stream. In HLS, this can be achieved with EXT-X-PROGRAM-DATE-TIME. In DASH, I think the equivalent is roughly availabilityStartTimeMs. 

If the media does not signal that 20 or 40, I don't see a way for the player to know. Please comment below if this is not what you meant and I'll reopen.
