### ISSUE TITLE
QA: Any plan to add SAMPLE-AES support for HLS

### ISSUE THREAD

**Issue by unext-wendong** [google/ExoPlayer#4579]
Thanks,
Wendong

**Comment by AquilesCanta** [comment]
Unfortunately there are no plans to support it. The alternatives are full segment encryption and Widevine. Playready will be added soon.

EDIT: Note that both Widevine and Playready require Content Decryption Module support.

**Comment by unext-wendong** [comment]
Thanks for the confirmation.
