### ISSUE TITLE
Does ExoPlayer support QUIC for youtube links ?

### ISSUE THREAD

**Issue by Ood-Tsen** [google/ExoPlayer#458]
When we test the YouTube dash example in demo app.
>    new Sample("Google Glass",
        "http://www.youtube.com/api/manifest/dash/id/bf5bb2419360daf1/source/youtube?"
        + "as=fmp4_audio_clear,webm2_sd_hd_clear&sparams=ip,ipbits,expire,source,id,as&ip=0.0.0.0&"
        + "ipbits=0&expire=19000000000&signature=249B04F79E984D7F86B4D8DB48AE6FAF41C17AB3."
        + "7B9F0EC0505E1566E59B8E488E9419F253DDF413&key=ik0", DemoUtil.TYPE_DASH),

I find the response header has including the "Alternate-Protocol" as following.

> I/HttpDataSource(24744):  headers (Alternate-Protocol)[80:quic,p=0]

Does ExoPlayer will support [quic] (https://www.chromium.org/quic) or [spdy] (https://www.chromium.org/spdy/spdy-whitepaper) protocol in the future  ?

**Comment by ojw28** [comment]
By default, ExoPlayer's DefaultHttpDataSource sits on top of HttpUrlConnection in the platform, and the platform provides the network stack underneath that.

- Recent Android releases have used okhttp as the underlying stack, which has support for spdy. I'm not sure whether it automatically enables it where possible though.
- For quic you'd need to use a different network stack, at least at the moment. It's certainly possible to support quic by implementing your own HttpDataSource implementation that bridges onto a different network stack. The obvious choice for quic being Cronet.

**Comment by Ood-Tsen** [comment]
Thanks for the reply.

I search a older issue #56 , it's possible to add specific network stack in HttpDataSource to support these protocol.

But for now,  I didn't find a example to play quic video on android, even on Chrome.
