### ISSUE TITLE
ClippedMediaSource ends sooner than expected when using REPEAT_MODE_ALL or ConcatenatingMediaSource

### ISSUE THREAD

**Issue by MateusZitelli** [google/ExoPlayer#4583]
### Issue description
Clipped video playback ends sooner than expected when repeat mode is Player.REPEAT_MODE_ALL or when it is combined with other clips using ConcatenatingMediaSource.

#### Setup a simple ExoPlayer instance:

```kotlin
val trackSelector = DefaultTrackSelector()
val renderersFactory = DefaultRenderersFactory(context)
val loadControl = DefaultLoadControl()
val player = ExoPlayerFactory.newSimpleInstance(renderersFactory, trackSelector, loadControl)
player.repeatMode = Player.REPEAT_MODE_ALL
val extractorMediaSourceFactory = ExtractorMediaSource.Factory(dataSourceFactory)

val startMs = 300
val endMs = 1000
val path = "/sdcard/Movies/probe-video.mp4"

val videoUri = Uri.parse(path)
val extractorMediaSource = extractorMediaSourceFactory.createMediaSource(videoUri)
val clippingMediaSource = ClippingMediaSource(
    extractorMediaSource,
    startMs * 1000,
    endMs * 1000)

val concatenatingMediaSource = ConcatenatingMediaSource()
concatenatingMediaSource.addMediaSources(listOf(mediaSource, mediaSource))
```

#### Logging player.currentPosition

```kotlin
Observable
    .interval(10, TimeUnit.MILLISECONDS)
    .observeOn(AndroidSchedulers.mainThread())
    .subscribe { Log.d("PlayerPresenter", "${player.currentPosition}") }
```

##### With `Player.REPEAT_MODE_OFF` or `player.prepare(clippingMediaSource)`

PlayerPresenter: 0
PlayerPresenter: 14
PlayerPresenter: 14
PlayerPresenter: 14
PlayerPresenter: 14
...
PlayerPresenter: 686
PlayerPresenter: 706
PlayerPresenter: 706

##### With `Player.REPEAT_MODE_ALL` or `player.prepare(concatenatingMediaSource)`

PlayerPresenter: 14
PlayerPresenter: 14
...
PlayerPresenter: 400
PlayerPresenter: 400
PlayerPresenter: 400
PlayerPresenter: -300
PlayerPresenter: -300
PlayerPresenter: -300
PlayerPresenter: -300

### Link to test content

I was able to reproduce this issue with any local mp4.

### Version of ExoPlayer being used
2.8.2

### Device(s) and version(s) of Android being used

- Essential phone w/ Android 8.1
- Samsung Note 8 w/ Android 7.1
However it doesn't seem to be a device specific issue.

**Comment by tonihei** [comment]
Thanks for reporting! We'll provide a fix for that.

**Comment by MateusZitelli** [comment]
Great! Is there any time estimate for that fix? Also, if you could provide some guidance I am happy to try to solve it. Thanks for your attention.

**Comment by MateusZitelli** [comment]
Debugging ExoPlayer it seems like the next media period preparation finishes before the actual period playback. Then the next period playback starts when the preparation finishes, skipping the last ms of the first period. However, I am not sure how to proceed to fix it.

**Comment by andrewlewis** [comment]
The fix should be pushed to the development branch soon.

**Comment by MateusZitelli** [comment]
The commit did the job, thanks for the great work!
