### ISSUE TITLE
Should I Use PlayReady for Android TV?

### ISSUE THREAD

**Issue by davidmullis1983** [google/ExoPlayer#4587]
### Issue description
More of a question than an issue, so apologies if I'm in the wrong place for this. If I am, then I would appreciated being pointed in the right direction.
My question is about something in the DRM doc here:
https://google.github.io/ExoPlayer/drm.html
It seems to specifically point to PlayReady and the DRM encoding to be used for ExoPlayer on Android TV.
I have an Android TV/Fire TV app using Widevine. Should I use PlayReady instead?
I'm just wondering if using Widevine here is going to cause me problems in the future.
What's the reason PlayReady is specifically called out for Android TV?

Thanks in Advance.

**Comment by AquilesCanta** [comment]
> It seems to specifically point to PlayReady and the DRM encoding to be used for ExoPlayer on Android TV.

Android devices are not required to support PlayReady. But Android TV devices are. There are no recommendations on what Platform to use on that page. 

> What's the reason PlayReady is specifically called out for Android TV?

Because Android TVs are required to support it.

Hope this answers your questions.

**Comment by davidmullis1983** [comment]
Hi. Thanks for the prompt reply.
So is my app required to support it? Or is there an advantage to using PlayReady over Widevine?

**Comment by AquilesCanta** [comment]
> So is my app required to support it?

No. Your app can use whatever content you wish, as long as it's supported by the platform. PlayReady happens to be supported on Android TV.

> Or is there an advantage to using PlayReady over Widevine?

I don't have an answer for this unfortunately. Besides, it falls outside the scope of the issue tracker.

**Comment by davidmullis1983** [comment]
Ok. That's pretty much what I wanted to know.
Thanks for your help.
