### ISSUE TITLE
FLAC audio - getCurrentPosition() return incorrect value which is increased by 2 seconds

### ISSUE THREAD

**Issue by dylantran09** [google/ExoPlayer#4588]
Hi,

I got issues with SimpleExoPlayer.getCurrentPosition() function when trying play high quality audio (FLAC type), it returns the value **increased by 2 seconds** when I tried to update the progress timer every second.

This caused the current time higher than song duration.

I tested on Android device:
Huawei Mate 10
OS: Android 8.0
Network: 4G

This does not happen on my other devices and MP4 audio.

Any ideas on why this happens and how we can eliminate it? Is this problem from FlacExtractor or FlacDecoder?
I'm using ExoPlayer version 2.8.2.

Thanks!

**Comment by botaydotcom** [comment]
Hi @dylantran09:
Could you provide us with some test media that you found this issue on? You can post a link here, or send it to dev.exoplayer@gmail.com using the subject "Issue #4588". Thank you very much.

**Comment by dylantran09** [comment]
Hi ExoPlayer team,

Thanks for looking at my issue.

Please find the test media and video reproduction in google drive link
below:
FLAC content (1411 bitrate):
https://drive.google.com/open?id=12_EoMD0PJXC1ul1TBYPnF2nLHLJsUoFw
Video reproduce:
https://drive.google.com/open?id=1q2hoRnOFg6je87cEATOc2wgvDkYADSB_

When I tried to prepare then seekTo middle of the audio, it sometimes
return currentPosition increased by 2 seconds.

Please let me know if you need any further information.

Thanks!
Dylan

**Comment by botaydotcom** [comment]
Couldn't find anything from this yet. @erdemguven: Please help me to take a look. Thank you.

**Comment by tonihei** [comment]
@erdemguven Any updates for this issue?

**Comment by tonihei** [comment]
@andrewlewis That also sounds like a problem with FLAC extension. The position seems to to advance twice as fast as real-time on this device. Have you seen that before?

**Comment by andrewlewis** [comment]
@dylantran09 Sorry for the delay. Could you confirm that the problem is that the player position is offset from the expected value after a seek? If so, I'm not able to reproduce this in the demo app (tried seeking to a variety of positions).
