### ISSUE TITLE
AES-128 key external from manifest (set the URI/IV on player/mediaSource for decryption)

### ISSUE THREAD

**Issue by VladTE** [google/ExoPlayer#4590]
Hello,

I want to know if there is any way to set #EXT-X-KEY:METHOD=AES-128 params (URI and IV) outside the manifest file (for all the parts of the playlist). For now I am receiving an M3U8 file which contains the information for a playlist (master playlist, details below), but if someone finds a way to intercept that link, I think the encryption is not that useful anymore because all the data to download/decrypt the files are on the manifest. I know that HlsMediaSource has a class like Aes128DataSource used to decrypt the files, but it is used directly by HlsMediaSource and can/should not be used (create a new instance and set as a property) by the app separated. 

I searched and found this issues : #378  reported a few years ago and I was wondering if there is any updates or other methods on how I could secure the files on server, so that only the link to the HLS manifest URL would not be enough to play the stream (need an external extra key to be decoded).

`
#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=72000,CODECS="mp4a.40.5"
********.m3u8
`

**Comment by AquilesCanta** [comment]
Hi @VladTE, 

>EXT-X-KEY:METHOD=AES-128 params (URI and IV) outside the manifest file (for all the parts of the playlist)

I don't know of any spec-compliant alternatives. Without discussing whether the intended approach is an effective security measure, you can implement your own HlsPlaylistParser and inject the information yourself, as if it were part of the original playlist. Also possible, you can implement your own HlsPlaylistTracker to achieve the same effect. The only difference is that it's a more complex interface to implement, but with more context to work with. The first suggestions should be enough. 

> other methods on how I could secure the files

You can use widevine.

Hope this helps!
