### ISSUE TITLE
Feature request: MIDI support.

### ISSUE THREAD

**Issue by motornyimaksym** [google/ExoPlayer#4592]
I want to be able to play MIDI files. Even MediaPlayer from standard Android SDK is able to do that.

**Comment by erdemguven** [comment]
Related: #4285

**Comment by szaboa** [comment]
@erdemguven 
How hard to do this in your opinion? I am hesitating whether to try to implement this or not :)
Edit. I see it is already assigned to you, so nevermind

**Comment by nicoalurralde** [comment]
Oh please, Id love some MIDI support

**Comment by nicoalurralde** [comment]
@szaboa can you give it a try? It's been a while

**Comment by AquilesCanta** [comment]
This will be looked at this year.

**Comment by Waldmann375** [comment]
Do it please, I really need this feature.

**Comment by AquilesCanta** [comment]
We cannot provide any timelines, but we are making progress and hope to publish something during the end of August.

**Comment by LajosNeto** [comment]
Hello @AquilesCanta ! Is there any update on that?
Thanks!

**Comment by tonihei** [comment]
MIDI support has been added a while ago and will be part of the 1.2.0 release

**Comment by LajosNeto** [comment]
@tonihei Thanks for the quick reply!
I checked on release notes for 1.2.0 that the support for MIDI will be added based on Jsyn library to synthesize audio. Do you have any information about soundfonts support or if there is a default one to be used when playing MIDI files?
Thanks!

**Comment by christosts** [comment]
I'm not a MIDI expert so I'll need some assistance :)

We do configure Jsyn with a default sound bank but the code at the moment does not allow the app to configure Jsyn differently, and we don't parse XMF files which may have the sound bank embedded in the file. 

Does this answer the question?
