### ISSUE TITLE
Question about supporting  HLS tags: EXT-X-SESSION-DATA

### ISSUE THREAD

**Issue by hanchen999** [google/ExoPlayer#4594]
As the title said, we want to fetch the EXT-X-SESSION-DATA information from HLS manifest. I want to know whether that is possible

**Comment by AquilesCanta** [comment]
Could you expand on the usecase? You can obtain the tags included in the master playlist via Player.EventListener#onTimelineChanged. This will let you access the playlist's tags, from which you can obtain the requested tag.

**Comment by hanchen999** [comment]
Thank you for your response. Yep, I just figure out that case after I read the source code. I think we could close this issue now.
