### ISSUE TITLE
How to update buffer policy parameters during playback in LoadControl

### ISSUE THREAD

**Issue by harshitwynk** [google/ExoPlayer#4596]
Hi

I have a use case where I'm having different buffer policy params (minBufferMs,maxBufferMs) for different network conditions.
Lets say for a 4G network I,m having minBufferMs = 30000 & maxBufferMs = 60000 . and for a 3G or lower network minBufferMs = 60000 & maxBufferMs = 300000.

So my question is we have to set the buffer policy params in LoadControl which we set while creating the ExoPlayer instance. Then how will I update the buffer params during playback when the network conditions change as there is no setter method or update method on LoadControl API.

ExoPlayer version used - 2.8.2

**Comment by erdemguven** [comment]
duplicate #2804
