### ISSUE TITLE
Recording livestream video loacaly as mp4 file 

### ISSUE THREAD

**Issue by AbdullahAyman** [google/ExoPlayer#4597]
Hello All,
### I would like to record a live stream video from exoplayer on spot (like recording a goal in a football match from live streaming url)
I am using exoPlayer as a video player in my application (works for mobile and TV platforms). while using the exoplayer in viewing the video I want to be able to click a button to start recording the played video till I stop the recording (without a predefined start and end micro-Seconds like in ClippingMediaSource class )

### Version of ExoPlayer is the latest version 2.8.2
Specify the absolute version number. Avoid using terms such as "latest".

### Device(s) and version(s) of Android being used
this issue appears on all devices I have used to test on (sony, infinix, huwaui, and Samsung)

**Comment by andrewlewis** [comment]
ExoPlayer doesn't support recording streams so you'd need to implement this in your app. It's outside the scope of this tracker to give detailed guidance on that I'm afraid.
