### ISSUE TITLE
Extension MediaSession, MediaSessionConnector: wrong default constructor?

### ISSUE THREAD

**Issue by eneim** [google/ExoPlayer#4598]
This line should not use "null" in place of "PlaybackController" instance?

The doc says:

```
Equivalent to {@code MediaSessionConnector(mediaSession, new DefaultPlaybackController())}.
```

while the constructor is 

```java
this(mediaSession, null);
```

[Please check this and the javadoc](https://github.com/google/ExoPlayer/blob/release-v2/extensions/mediasession/src/main/java/com/google/android/exoplayer2/ext/mediasession/MediaSessionConnector.java#L352)

**Comment by AquilesCanta** [comment]
Note that API-wise the statement is correct. The constructor at the bottom does:

```
this.playbackController =
        playbackController != null ? playbackController : new DefaultPlaybackController();

```
