### ISSUE TITLE
Bug: unable to play mp4 files via URL ? 

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [google/ExoPlayer#4599]
I've found an mp4 file that I wanted to just test to play it:

http://file-examples.com/wp-content/uploads/2017/04/file_example_MP4_480_1_5MG.mp4

On the PC and on video player apps it plays fine, but when I try to play it using ExoPlayer, it fails, even though a sample mkv URL works fine for me:

https://www.sample-videos.com/video/mkv/720/big_buck_bunny_720p_2mb.mkv

Same goes for other mp4 urls I've found:
http://standaloneinstaller.com/blog/big-list-of-sample-videos-for-testers-124.html

Attached sample project:
[ExoPlayerTest.zip](https://github.com/google/ExoPlayer/files/2244245/ExoPlayerTest.zip)

Looking at the logs, there seems to be a weird connection error:

```
2018-07-31 10:56:25.566 30040-30346/com.example.user.myapplication E/ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to http://mirrors.standaloneinstaller.com/video-sample/P6090053.mp4
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:194)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:147)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:848)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:317)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.io.IOException: Cleartext HTTP traffic to mirrors.standaloneinstaller.com not permitted
        at com.android.okhttp.HttpHandler$CleartextURLFilter.checkURLPermitted(HttpHandler.java:115)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:458)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:429)
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:350)
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:192)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:147) 
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:848) 
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:317) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764)
``` 

How could it be? Anything wrong with the code?

Tested on Pixel 2 with Android P DP5

**Comment by erdemguven** [comment]
I have tried to play the mp4 sample you shared using ExoPlayer Demo app and it works fine.

One thing I noticed in the exception log is:
`Cleartext HTTP traffic to mirrors.standaloneinstaller.com not permitted`
Perhaps you need find a way to allow your app to work with not secure network connections if you want to play those streams.

Closing the issue as it isn't ExoPlayer related.

**Comment by AndroidDeveloperLB** [comment]
It seems like a thing on Android P:
https://www.digicert.com/blog/android-p-will-default-https-connections-apps/

And indeed, when I ran it on Android 8.0, it works fine.
To me it seems a very drastic change, and changing the targetSdk to 27 doesn't help. It affects all apps.

Please update the library to support all kinds of urls.

Also, why close this issue? You didn't even allow me to answer before closing it...

**Comment by AndroidDeveloperLB** [comment]
Since I think it's a too drastic decision, that even ExoPlayer library is affected and isn't ready to it, I've written about it here:
https://issuetracker.google.com/issues/112019040

**Comment by ojw28** [comment]
> and changing the targetSdk to 27 doesn't help

I strongly suspect you are mistaken. Many thousands of existing apps would be broken on the P developer preview if this were the case. Which would create a lot of noise on the Android issue tracker. Which there isn't any of. I suggest you double check that you really set this correctly, and that the setting definitely propagated through to the apk you tested with.

> To me it seems a very drastic change

This is completely dependent on whether disabling non-secure connections is conditioned on bumping the app's target API level to P. We're pretty confident that it is, in which case the change isn't drastic at all. Existing apps will continue to work. You can also still bump your target API level to P and use non-secure connections, by adding a network security configuration file, which looks pretty straightforward.

**Comment by AndroidDeveloperLB** [comment]
Odd. I've checked it before, and now it works fine on targetSdk 27.

OK, can you please show how to make it work fine on ExoPlayer, even if targetSdk is indeed 28?
And maybe add a function on ExoPlayer to allow http connections too?

I can see that the current repository of ExoPlayer targets API 27...
Why not 28? Android P will soon be officially out to all users ...

What's straightforward about adding a configuration file exactly? Is there any UI for this on the IDE? 
Isn't there a way to let an entire library (such as ExoPlayer) reach all http connections, and have the rest as usual ?

**Comment by ojw28** [comment]
> OK, can you please show how to make it work fine on ExoPlayer, even if targetSdk is indeed 28?

This is already explained if you follow the links in the page you referenced above (i.e. you need to add a network security configuration file). This is something you need to do at the application level.

> I can see that the current repository of ExoPlayer targets API 27

I think that our target API level is unrelated to your app's target API level. Unless your target API level is lower than our one, I think. Why does this matter to you?

**Comment by AndroidDeveloperLB** [comment]
As I wrote, the docs aren't clear.
The only thing I've seen is this:
https://android-developers.googleblog.com/2018/04/protecting-users-with-tls-by-default-in.html?m=1

What should I do to allow a specific library (like ExoPlaer) to access http connections, for example?
Where do I put this weird new file?
Can I somehow allow the app to access all http connections?
Is it this:

      <base-config cleartextTrafficPermitted="true" />

?

How can I allow http connections without this file, but in code instead? Seems much better, as I can put specific places in the code to allow it. However, I can't find such a thing. 
Seems to me that it's an all-or-nothing in this case.

**Comment by ojw28** [comment]
See https://issuetracker.google.com/issues/112019040

**Comment by AndroidDeveloperLB** [comment]
Yes thanks

**Comment by AndroidDeveloperLB** [comment]
But still, the sample project here should be updated to support this. If the sample can access a URL, it should support all URLs.

**Comment by ojw28** [comment]
We will update the sample project one way or another when we update its target API level to 28, however the update will most likely remove all non-secure samples (and support for playing non-secure samples unless you edit the demo app to allow it).

Using non-secure connections is considered bad practice, and the industry is moving away from them (e.g. according to the page you referenced, iOS has disabled them by default since 2015, Chrome now explicitly marks websites using non-secure connections as "not secure", etc). I don't think we want our demo app to go against that trend.

**Comment by AndroidDeveloperLB** [comment]
Imagine what would happen if Chrome would block such websites, unless the user sets a flag in the settings.
Seems very drastic change to me.
That's how it is on Android P.
What's so wrong with http? Isn't https used mainly for login, payment, and such.... If it's simple browsing (just reading, watching videos and looking at images), I don't see anything wrong with that.

Why do it on Android apps themselves? It's not that all apps are web browser apps...
What could go wrong if you use http for playing a video on ExoPlayer? It's a non-active thing to do (meaning viewing content, and not really running it). Why not update the sample for it too? Or at least allow on Android, via API, to exclude ExoPlayer library from this restriction ? 

And speaking of IOS, I find it annoying to see things being copied from them. It's not the first time bad things are being copied. Even on the hardware part: no sd-cards and no IR on Google devices (useful even for development alone), glass back (fragile), no headphone jack (even though Google itself bragged of having it in [its ad](https://youtu.be/Rykmwn0SMWU?t=47)) no replaceable battery (what about thinking of the environment?), rounded corners and the notch (both ruin the experience of the screen).

Why not copy the good things? Why not copy long updates? Nexus 4, 5, 5x, 6p... All got updates for about 2 years top. Even Pixel devices only got promises for updates for just 3 years. And I really hope things will get better now with Project Treble, especially on non-Google devices, which are much worse in this.
And what about availability of the Pixel devices? I had to fix a perfectly new Pixel XL privately in a lab for almost 200$ , just because Google fails to support it in my country.

And that's mostly for the hardware part...

There are some cases where it was a good thing to copy. One of them is leaving Flash, for HTML5.

**Comment by ojw28** [comment]
> What's so wrong with http? ... I don't see anything wrong with that.

Is it more likely that (a) many large companies are spending a lot of time and effort doing something that's a "bad thing", or (b) that you don't fully understand the topic? It's relatively easy to research this topic online (e.g. [by reading this](https://https.cio.gov/everything/)). It's also relatively easy to fully read documentation before claiming it doesn't answer your questions, as opposed to creating more work for us on this issue tracker.

A few specific examples as to why using HTTP for video playbacks is not good practice:

* Leaking of sensitive information (e.g. exactly what videos your app's users are watching). What counts as "sensitive" is rarely a judgement call that you should be making on behalf of an app's users, since it depends significantly on context.
* Malicious man-in-the-middle (MITM) attacks. For example a MITM deliberately serving the user with different content than what they've requested. Whether or not this poses a risk is rarely a judgement call that you should be making on behalf of an app's users.
* Well intentioned but unwanted MITM attacks. For example a MITM re-encoding a video stream on-the-fly into a lower quality, so as to save bandwidth/cost along a link they're responsible for. This general category of attack can do things like introduce arbitrary differences in app behavior depending on what ISP or mobile network operator the end user subscribes to.
* Well intentioned but incorrectly implemented MITM attacks. For example where a MITM attempts to re-encode a video stream on-the-fly as above, but messes up their implementation so badly they end up serving completely the wrong content to the user instead.
