### ISSUE TITLE
DEFAULT_MIN_BUFFER_MULTIPLICATION_FACTOR in AudioTrackRenderer

### ISSUE THREAD

**Issue by saiday** [google/ExoPlayer#46]
I found that if `DEFAULT_MIN_BUFFER_MULTIPLICATION_FACTOR` is greater than `1`, resume the playback that remaining time is in a short time (0 ~ 1 sec) won't play.

What we are concerned to have `DEFAULT_MIN_BUFFER_MULTIPLICATION_FACTOR` factor, thanks!

**Comment by ojw28** [comment]
There's a small issue around trying to play from very close to the end when using FrameworkSampleSource. I'm pretty sure it doesn't have anything to do with the multiplication factor. If it did, I would expect the issue to reproduce with DASH streams, but I've never seen that. Have you?
