### ISSUE TITLE
How do i add custom view to MediaController ?

### ISSUE THREAD

**Issue by drayan85** [google/ExoPlayer#460]
How do i add custom view to the MediaController to add full screen button and change the style of seekbar.

**Comment by bsysop** [comment]
You need create your own MediaController in your own class, then you can change: "mediaController = new MediaController(this);" for "mediaController = new VideoControllerView(this);"...

In this case "VideoControllerView" is the name of your own class.

You can use this http://dajver.blogspot.com.br/2014/10/custom-mediacontroller-android.html
(Just have to change a little)

**Comment by drayan85** [comment]
Thanks for the reply.

Manage to get it done using your suggested link.

**Comment by bsysop** [comment]
No problem, any question just comment here!.

Regards.

**Comment by thevoiceless** [comment]
@drayan85 Please close this if it's no longer an issue
