### ISSUE TITLE
Does ExoPlayer update duration of in-progress recordings?

### ISSUE THREAD

**Issue by chrisfillmore** [google/ExoPlayer#4603]
I am trying to understand ExoPlayer's behaviour when playing in-progress recordings. I have a ticket filed with Shaka team about support for playback of such content with an increasing `mediaPresentationDuration`: https://github.com/google/shaka-player/issues/1513 . Shaka does not support this at this time; it needs to know the duration at the start of playback, but it appears Exo is able to update duration throughout playback.

Here are the circumstances:
- In-progress recordings are `type="dynamic"` manifests with `mediaPresentationDuration`
- `mediaPresentationDuration` is increased by one segment length with each manifest
- Once the recording is complete, the stream is converted to `type="static"`

So my question is, does ExoPlayer dynamically set duration throughout playback of such content? Is that how playback of such in-progress recordings is provided?

Thank you!

**Comment by erdemguven** [comment]
You can easily try to play your stream using [ExoPlayer demo app](https://github.com/google/ExoPlayer/tree/release-v2/demos/main). Let us know if it doesn't work as expected.

**Comment by ojw28** [comment]
> content with an increasing `mediaPresentationDuration`

Are you sure that's the right thing to do? My reading of the spec is that `mediaPresentationDuration` should be omitted until the point at which you can convert the manifest type to `static`. It's documented to be "the duration of the entire media presentation", and you don't know what that duration is until the recording is complete. I don't think it's valid to set it to the duration of the partial media presentation before it's complete point. I think @TheModMaker on the shaka bug is probably alluding the same thing.

If you omit `mediaPresentationDuration` then I'd expect the right thing to happen, and the duration to grow as you expect. If you include `mediaPresentationDuration` as you are doing then I'm not sure. One implication is that we'll incorrectly determine a known duration for the last period in a dynamic manifest. I'm not sure what the implications of that would be.

**Comment by chrisfillmore** [comment]
Reading from ISO/IEC 23009-1:2014(E), 5.3.1.2 Semantics, Table 3:

> @mediaPresentationDuration specifies the duration of the entire Media Presentation. If the attribute is not present, the duration of the Media Presentation is unknown.
This attribute shall be present when neither the attribute MPD@minimumUpdatePeriod nor the Period@duration of the last Period are present.

Also in IOP 4.2, section 4.6.4 Transition Phase between Live and On-Demand
 
> In the scenario for which the same MPD URL is used for live and On-Demand content, once the URL and publish time of the last Segment is known for the live service, and the duration of the service is known as well, the service provider acts as defined in clause 4.4.3.1, i.e.,
>- adds the attribute MPD@mediaPresentationDuration

I agree with you. Thanks for the feedback!
