### ISSUE TITLE
Exo player mixed mimeadaptiveness cannot resolve

### ISSUE THREAD

**Issue by SystemRestored** [google/ExoPlayer#4606]
I am currently using the exoplayer version 2.7.3
I am going to play an master m3u8 which contain two types of m3u8 one is avc type codec and another hevc. The problem is only the avc is playing if my master file contains two types m3u8. 

if I play separately both plays.

I found mixedmimetype adaptiveness by using:
trackSelector = new DefaultTrackSelector(adaptiveTrackSelectionFactory);
trackSelector.setParameters(trackSelector.getParameters().withAllowMixedMimeAdaptiveness(true));

but in my case its coming cannot resolve withAllowMimeAdaptiveness. I tried  .setAllowMixedMimeAdaptiveness also but its not working.  

My exoplayer library's DefaultTrackSelector is:  
    /**
     * See {@link Parameters#allowMixedMimeAdaptiveness}.
     *
     * @return This builder.
     */
    public ParametersBuilder setAllowMixedMimeAdaptiveness(boolean allowMixedMimeAdaptiveness) {
      this.allowMixedMimeAdaptiveness = allowMixedMimeAdaptiveness;
      return this;
    }

    /**

I tried setting many parameters, but I cannot set a single parameter in exoplayer. I am using the demo player code.

**Comment by SystemRestored** [comment]
finally made it by:   

trackSelector = new DefaultTrackSelector(adaptiveTrackSelectionFactory);
            DefaultTrackSelector.Parameters currentParameters = trackSelector.getParameters();
            // Build the resulting parameters.
            DefaultTrackSelector.Parameters newParameters = currentParameters
                    .buildUpon()
                    .setAllowMixedMimeAdaptiveness(true)
                    .build();
            // Set the new parameters.
            trackSelector.setParameters(newParameters);


now the problem is stream starts playing but hevc url has 128 aes key thats not loading and stream not playing for that... but avc key loading and playing..  that means in two type of codec , key is not loading for second type.

**Comment by erdemguven** [comment]
Please provide a test content.

@AquilesCanta could you take a look at this.

**Comment by AquilesCanta** [comment]
This issue is being closed because it does not adhere to our issue template, and/or because it omits information requested in the issue template that is required for us to investigate the problem efficiently. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

If you’re able to provide complete information as requested in the issue template, please do so below and we’ll re-open the issue. Thanks!
