### ISSUE TITLE
Problem with some HLS audio streams

### ISSUE THREAD

**Issue by satyres** [google/ExoPlayer#4608]
Hi , 
this stream : http://newcap-hls.leanstream.co/newcap/CJMOFM.stream/playlist.m3u8
works in VLC but not in Exoplayer .
Any explanation please ?

this is the error in the logcat : 
UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor, AmrExtractor) could read the stream.

**Comment by AquilesCanta** [comment]
Please see https://google.github.io/ExoPlayer/faqs.html.
