### ISSUE TITLE
Best way to insert a virtual freeze-frame into an ExoPlayer video?

### ISSUE THREAD

**Issue by droidoit** [google/ExoPlayer#4609]
My overall usage of ExoPlayer is pretty simplistic, just playing back local videos, and I'm new to the library, and still coming to grips with how Sources/Timelines/Periods/etc all work together.

I'd like to insert a virtual freeze-frame into an arbitrary video on the Android device.

For example, say I just loaded in a 1 minute clip and I want to insert a 10 second freeze frame at the 30 second mark and have the video (from the point of view of the UI/player bar) appear to now be a single 1 minute 10 second video with continuous playback, when played back the single frame at the 30 second mark in the original video plays for 10 seconds instead of for just a single frame period, but the UI bar scrubs over it at the same continuous rate as any other period of the video.

A combination of ClippingMediaSource and ConcatinatingMediaSource seems like a decent fit for this, say by clipping the video to a StartSource, EndSource, and MidSource (which is the freeze-frame part).  

The way I've approached this problem thus far was to extract a bitmap image of the frame I want to freeze and either encode this into its own video (pretty heavy weight), or hack up the UI layer code to display it as an image over the player view while some correct-length, but dummy MidSource plays.   

Both of these are fairly messy executions and the frame extracted (using MediaMetadataRetriever.getFrameAtTime, even with OPTION_CLOSEST) doesn't always present a good match what exoplayer is actually displaying at that time, so it usually causes a bit of jumpiness as the sources are switched over while playing the ConcatinatingMediaSource.

Is there a conceptually simpler way to do this that I'm missing by not yet being deeply versed in how ExoPlayer works?  Would a custom MediaSource with its own custom Timeline be a good fit for this? and if so, any general pointers on how to achieve this functionality without becoming an ExoPlayer expert first?

**Comment by erdemguven** [comment]
@tonihei could you look at this?

**Comment by tonihei** [comment]
That's an interesting question and there seem to be multiple ways to address this:
- If it's possible for you, the simplest way is probably the encode the video with the freeze frame. Either in the middle of the original video or as as a separate video which can be combined with the other videos as you describe. 
- Note that ExoPlayer has no native support for image display (although such a feature has been requested several times: e.g. #3434, #2874). You can add such a feature by adding a `Renderer` for images and then load your image with a `SingleSampleMediaSource`. Again, such a source can be concatenated into the clipped start and end source of the video.
- If you are having issues finding the correct frame, you can try to use ExoPlayer's new metadata and frame retrieval classes which will be added in one of the next releases (unfortunately, not yet in dev-v2 branch).
- You may also try to just the pause the player at the intended position and provide your own UI progress bar showing the additional duration.

**Comment by tonihei** [comment]
Closing the issue as the question is supposedly answered. If not, please feel free to reopen.
