### ISSUE TITLE
UI - DefaultTimeBar accessibility issue

### ISSUE THREAD

**Issue by asanChina** [google/ExoPlayer#4611]
DefaultTimeBar has problem with accessibility issue
check the screenshot I got https://photos.app.goo.gl/qMTmTDzyG2M2yL3HA.
I am using app "Accessibility Scanner" (developed by Google, you can download it from play store) to scan the UI element in the screen

**Comment by andrewlewis** [comment]
At the moment we're setting the `AccessibilityNodeInfo` class name to the custom view class name, but it looks like it needs to be the name of the most similar widget from the Android SDK or support library (probably `android.widget.SeekBar`). See also https://support.google.com/accessibility/android/answer/7661305.
