### ISSUE TITLE
But: Possible issue when using support library 28 

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [google/ExoPlayer#4614]
When using this:

        implementation 'com.android.support:appcompat-v7:28.0.0-beta01'

You get this error in building:

![image](https://user-images.githubusercontent.com/5357526/43615174-211102c2-96bf-11e8-8d59-9417f4be3ec9.png)

You can ignore it though. 
Attached sample project
[ExoPlayerTest.zip](https://github.com/google/ExoPlayer/files/2256145/ExoPlayerTest.zip)

**Comment by erdemguven** [comment]
I think as the warning suggest you should just use the same version of the support library.

**Comment by AndroidDeveloperLB** [comment]
Why close this issue?
Using a newer version of the support library is something that should be supported, always.
Especially if this is a library created by Google. Google should present an example to others, that we should always support future versions.
Saying that I should use older versions is like saying I shouldn't use Android P.

**Comment by ojw28** [comment]
> Using a newer version of the support library is something that should be supported, always.

It is supported. If you Google the issue you'll easily find instructions on how you can configure your app to use any version of the support library that's equal to or more recent than the one ExoPlayer is using. For example [the top StackOverflow issue](https://stackoverflow.com/questions/42374151/all-com-android-support-libraries-must-use-the-exact-same-version-specification). This is another example where doing a bit of research before posting here would save us some time.
