### ISSUE TITLE
DASH: Add support for automatic gap and/or discontinuity jumping

### ISSUE THREAD

**Issue by KarlGallagher** [google/ExoPlayer#4616]
Hi,

As far as I can see the DASH-IOP does not explicitly define behavior with respect to gaps or discontinuities in a stream.

In practical terms however, a live stream that is fed from a lossy source (such as DVB linear broadcast) may experience gaps in the timeline from time to time.
Also in practical terms,when live streaming at a reasonable time length  (say 1 hour) transient network quality degradation may result in buffering latency  - which can eventually build up and push the players playhead behind the servers live window.

In both cases  - this causes the fatal 'BehindLiveWindowException'

I realize that this has been discussed many times on this bug tracker, and the prevailing wisdom is to either handle this exception and restart or preempt  it and seek closer to the live edge. 

There are two limitations to these approaches however

1.)Depending on the live window length you could end up skipping by a large duration which can be annoying for the end-user
2.)Discontinuities due packet loss at the input source can not be preempted by the application.

Both Shaka-Player and DASH-IF reference player support automatic 'gap jumping' to deal with this. I believe this is implemented by seeking across the discontinuity.

Would it be possible to add similar support in ExoPlayer please?

Thanks.

**Comment by anril** [comment]
[This example of controller](https://shaka-player-demo.appspot.com/docs/api/lib_media_gap_jumping_controller.js.html)  can help to solve the issue.

**Comment by zoard25** [comment]
@ojw28 do you have in plan to add support regarding this in the near future? If not could you please give us some hint on how to do it in a proper way? Thanks.

**Comment by alfonsoramosa** [comment]
@ojw28 Are you planning add support for discontinuities and gaps soon?

**Comment by ojw28** [comment]
I think DASH-IF are moving toward forbidding gaps, because doing this greatly simplifies client implementations. It's true that there may be gaps in an incoming live feed, but the server should be capable of inserting some kind of placeholder media in such cases, rather than leaving gaps in the timeline.

**Comment by ojw28** [comment]
For reference, please see [this doc](https://dashif-documents.azurewebsites.net/DASH-IF-IOP/pull/210/DASH-IF-IOP.html). In particular:

> There SHALL NOT be gaps or overlapping media segments in a representation.

**Comment by ojw28** [comment]
I've filed https://github.com/google/ExoPlayer/issues/6152 to track the second part of the original issue description.
