### ISSUE TITLE
Http Headers and Subtitles in Cast Extension

### ISSUE THREAD

**Issue by marcovietovega** [google/ExoPlayer#4617]
Hello,

This is not an issue, I saw in the cast demo that they are using a URL as contentID when creating the mediaitem.

```
private static MediaQueueItem buildMediaQueueItem(DemoUtil.Sample sample) {
    MediaMetadata movieMetadata = new MediaMetadata(MediaMetadata.MEDIA_TYPE_MOVIE);
    movieMetadata.putString(MediaMetadata.KEY_TITLE, sample.name);
    MediaInfo mediaInfo = new MediaInfo.Builder(sample.uri)
        .setStreamType(MediaInfo.STREAM_TYPE_BUFFERED).setContentType(sample.mimeType)
        .setMetadata(movieMetadata).build();
    return new MediaQueueItem.Builder(mediaInfo).build();
  }
```
But I want to know if there is a way to use http headers like in a httpdatasource, and how to add subtitles.

**Comment by AquilesCanta** [comment]
> But I want to know if there is a way to use http headers like in a httpdatasource

I am not aware of any way of doing this using the default receiver app. You could implement a custom app and add the custom message to retrieve the http headers. 

> and how to add subtitles

Same. If you find a way of doing it with the default receiver app, please let us know and we'll add support for it. 

It might be worth trying your luck [here](https://github.com/googlecast/CastReferencePlayer).

**Comment by marcovietovega** [comment]
Sorry to answer late. I found that you can download the video and serve it with nanohttpd to cast it. I still trying to do it. Maybe you could implement it exoplayer or as plugin like cast.
