### ISSUE TITLE
Saving Clipped Media Source

### ISSUE THREAD

**Issue by ntohill95** [google/ExoPlayer#4618]
I am having an issue when trying to save a video after using ClippingMediaSource. I want to be able to store the clip after it has been trimmed. Can this be done?

Is ClippingMediaSource simply only to playback a section of the MediaSource or can it be used to trim a clip?

**Comment by andrewlewis** [comment]
Could you elaborate on what you mean by saving/storing a video? As you say, `ClippingMediaSource` is intended for playing back part of another media source. If you want to cache the clip I think that should just work in the normal way with `CacheDataSource`.

**Comment by ntohill95** [comment]
I want to edit a video clip and save the new trimmed version to storage. Thank you for the quick response i will investigate CacheDataSource

**Comment by andrewlewis** [comment]
I'm afraid ExoPlayer doesn't provide a way to save media streams to storage. For example, if you wanted to produce an MP3 file with the first thirty seconds removed, ExoPlayer does not support that. `CacheDataSource` will cache media in its own internal format, so it won't help with this.
