### ISSUE TITLE
Embedded MKV Subtitles not displaying in Leanback/Android TV

### ISSUE THREAD

**Issue by cncb-gh** [google/ExoPlayer#4619]
I have copied the Leanback demo app playback: https://github.com/googlesamples/androidtv-Leanback.  Playing the Kodi MKV sample files (https://kodi.wiki/view/Samples, #19 and 20 under #3 Codecs, Framerates and Subtitles), neither SRT nor PGS embedded subtitles will display in the player.  I have confirmed that these text tracks are being selected by default.  Is there something I am missing to get subtitles to display in the Leanback player?  I have tested both in the emulator and on my NVidia Shield TV.

**Comment by andrewlewis** [comment]
ExoPlayer handles this subtitle format, but see #3985 regarding getting subtitles to appear when using leanback.
