### ISSUE TITLE
video dimmed when opened in bottomsheet fragment

### ISSUE THREAD

**Issue by kingofswing** [google/ExoPlayer#4620]
Before filing an issue:
-----------------------
I Have searched existing issues, including issues that are closed but no luck.

### Issue description
I managed to setup a recyclerview of video list, my plan is to preview the video in 
a bottom sheet fragment after long-click an item in the recyclerview video list.  almost done 
but the screen is dimmed when playing in bottomsheet fragment.  

### Version of ExoPlayer being used
exoplayer:2.7.2

### Device(s) and version(s) of Android being used
HuaWei P7 customized version of Android 5.1.1

Has anyone have done this before? or is it a bad experience previewing a video in a popup bottomsheet fragment ? 

TIA .

**Comment by andrewlewis** [comment]
I haven't heard of screen appearing dimmed before. It might be worth checking your layout in the Android Studio layout inspector to see if there's a translucent view on top.

This sounds like an app issue, which would be beyond the scope of this issue tracker to investigate. If you can reproduce the issue on a non-customized build in the ExoPlayer demo app please provide a full bug report and we can investigate further.

**Comment by kingofswing** [comment]
thank your for your quick replay. but found issue closed.  I mean I tried to get video played in bottom sheet fragment through normal steps. the point may be mask layer between the popup bottomsheet fragment and the recyclerview list.  if put some textview or input textbox or button, the layout is ok, but after exoplayerview put in layout of bottom sheet , when video starts to play, the video screen is mixed with the mask layer, so the screen is dimmed

**Comment by abdurahmanadilovic** [comment]
@kingofswing how did you resolve this issue? I have the same issue in my app

**Comment by kingofswing** [comment]
> 
> 
> @kingofswing how did you resolve this issue? I have the same issue in my app

When I test my app using the old HUAWEI P7 (bought in 2015.2), the video screen is sure dimmed , It seems due to the mask layer.  but several weeks ago I bought a new phone, which is VIVO Y71, it's an customized Android 8.1 phone, with 3GB memory and 32GB storage, when tested , it is surprised to me that the video is normal , not dimmed this time.

Sorry for the later reply.
