### ISSUE TITLE
Question, is there a way to add widevine plugin to devices which has no support?

### ISSUE THREAD

**Issue by islor** [google/ExoPlayer#4621]
Might not be related to Exoplayer, but you guys might be more familiar with this. 
To elaborate, I have a set top box that is running android 4.4 but gets the UnsupportedDrmException.REASON_UNSUPPORTED_SCHEME error when playing a Widevine content with Exoplayer.

Is there a way to add the drm support on the app level? Or is this only possible through device/chipset manufacturers? It seems to be the latter based on this http://www.widevine.com/getting_started.html

Appreciate your inputs!

**Comment by andrewlewis** [comment]
The short answer is not at the moment, I'm afraid. In-app DRM is limited in the level of protection that can be provided anyway. I've heard that some other player SDKs provide content protection without dependencies on platform DRM support. @ojw28 may want to add more information.
