### ISSUE TITLE
QA: how to add private DRM into ExoPlayer to play HLS encrypted stream?

### ISSUE THREAD

**Issue by jzhoubupt** [google/ExoPlayer#4623]
Hi,
This is a question instead of a issue report.
I'm evaluating using ExoPlayer SDK in product. 
A typical feature is to play HLS encrypted stream with private DRM instead of using device Widevine or Playready.
This private DRM module provides:
1. license management
2. AES-128 decryption

The HLS encrypted  stream is standard AES-128 CBC mode which means the whole segment is encrypted and the decryption should happen (by private DRM) before demuxing while ExoPlayer is fully implemented based on MediaCodec and MediaDrm and decryption is done in the MediaCodec by device CDM.

To implement this feature based on ExoPlayer a possible solution is to extend some interfaces defined in ExoPlayer drm package and insert data decryption so data sent to demuxer
and decoder is clear data.

Could the ExoPlayer development team (or anybody who has related experience) give a hint which interfaces are designed for private DRM extension?

Best regards,
Jianhua

**Comment by ojw28** [comment]
> Could the ExoPlayer development team (or anybody who has related experience) give a hint which interfaces are designed for private DRM extension?

We don't provide any interfaces designed to support custom full-segment decryption. Your best bet would be to look at how AES-128 full segment decryption is supported in the HLS module, see if you can find a way to adapt it to your needs, and if you manage to get that working, think about how it might be possible to inject the custom pieces. If that can be done by adding some very minimal hooks then we'd consider a pull request that adds them.

I don't think this is something we're going to look at proactively supporting. The scheme you describe doesn't sound secure enough to satisfy many premium content providers (e.g. movie studios), even for SD playback. So even if the scheme is useful for you, it likely wont be useful for the majority of developers. The industry has already moved significantly away from full-segment encryption and toward sample encryption.

As an aside, we do support a way of implementing custom sample decryption, which can be done by providing an `ExoMediaDrm` implementation together with software decoders that incorporate a decryption step (although actually implementing this is definitely an advanced topic!).

**Comment by jzhoubupt** [comment]
Thanks a lot for your confirmation.
Will keep you update if get private DRM integration into ExoPlayer in a well modulized solution.

For this feature (full segment decryption) indeed there is security concern from the industry and i completely understand. However there are still lots of video streaming solution running on these private DRM systems on open devices so the market requirement for this feature support can't be ignored. That's why my department evaluate technical solution even we have support for Widevine and Playready.

Jianhua
