### ISSUE TITLE
Not able to playback the MPEG TS content (Error : Media includes audio tracks, but none are playable by this device)

### ISSUE THREAD

**Issue by shushank22** [google/ExoPlayer#4624]
### Issue description
When i am trying to playback the MPEG TS (.ts.mpg) file in Exo-Player, using the demo APP it shows me error "Media includes audio tracks, but none are playable by this device".
I am trying to play it on Android TV(720 P) API P emulator and Pixel XL API 28 emulator.

When I Play it on Samsung Galaxy s7, it gives me error "Media includes video tracks, but none are playable by this device", and I am able to listen Audio but no Video Displays.

### Reproduction steps
1) Using adb, push the content to emulator, 
    adb push e:\content.TS.mpg /sdcard/Movies/
2) Add content in "media.exolist.json"
    {sz
    "name": "Local SD Card Content",
    "samples": [
      {
        "name": "content.TS.mpg",
        "uri" : "/sdcard/Movies/content.TS.mpg"
      }
  },

### Link to test content
Cannot provide the content, but detail of stream is:
General
ID                                       : 1 (0x1)
Complete name                            : E:\content.mpg
Format                                   : MPEG-TS
File size                                : 45.9 MiB
Duration                                 : 1 min 35 s
Overall bit rate mode                    : Constant
Overall bit rate                         : 4 034 kb/s
FileExtension_Invalid                    : ts m2t m2s m4t m4s tmf ts tp trp ty

Video
ID                                       : 17 (0x11)
Menu ID                                  : 1 (0x1)
Format                                   : MPEG Video
Format version                           : Version 2
Format profile                           : Main@Main
Format settings                          : CustomMatrix / BVOP
Format settings, BVOP                    : Yes
Format settings, Matrix                  : Custom
Format settings, GOP                     : Variable
Format settings, picture structure       : Frame
Codec ID                                 : 2
Duration                                 : 1 min 35 s
Bit rate mode                            : Constant
Bit rate                                 : 3 640 kb/s
Maximum bit rate                         : 3 444 kb/s
Width                                    : 720 pixels
Height                                   : 480 pixels
Display aspect ratio                     : 4:3
Frame rate                               : 29.970 (30000/1001) FPS
Standard                                 : NTSC
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Interlaced
Scan order                               : Top Field First
Compression mode                         : Lossy
Bits/(Pixel*Frame)                       : 0.351
Time code of first frame                 : 00:00:00;00
Time code source                         : Group of pictures header
GOP, Open/Closed                         : Open
GOP, Open/Closed of first frame          : Closed
Stream size                              : 41.3 MiB (90%)

Audio
ID                                       : 18 (0x12)
Menu ID                                  : 1 (0x1)
Format                                   : MPEG Audio
Format version                           : Version 1
Format profile                           : Layer 2
Codec ID                                 : 3
Duration                                 : 1 min 35 s
Bit rate mode                            : Constant
Bit rate                                 : 192 kb/s
Channel(s)                               : 2 channels
Sampling rate                            : 48.0 kHz
Frame rate                               : 41.667 FPS (1152 SPF)
Compression mode                         : Lossy
Delay relative to video                  : 18 ms
Stream size                              : 2.18 MiB (5%)

### Version of ExoPlayer being used
I download and build source code, using commit ID:
    commit f7ed789fc3841b2536f5629c6bb10f4cb4ee5130
    Merge: 2b55c91af d880fac58
    Author: ojw28 <olly@google.com>
    Date:   Tue Jun 26 15:54:16 2018 +0100

        Merge pull request #4434 from google/dev-v2-r2.8.2

        r2.8.2

### Device(s) and version(s) of Android being used
1) Android TV (720p) API P
2) Pixel XL API 28
3) Samsung Galaxy s7 (Android Version 8.0.0)

**Comment by shushank22** [comment]
@andrewlewis @canatella @kiall @talklittle @jcable 
Hi,
Can someone help me on this as this very urgent to me,
and I am not finding any solution of it,

Please guide me.

**Comment by andrewlewis** [comment]
It looks like these devices just don't have codecs for the given format. For example, it appears that the Samsung Galaxy S7 doesn't have an MPEG-2 video decoder.

Please read the [supported formats page](https://google.github.io/ExoPlayer/supported-formats.html) for more information.

**Comment by shushank22** [comment]
@andrewlewis 
So, If device/emulator doesn't support MPEG-2 video/audio decoder, 
Is there any way we can play that content on Exo-Player with Android TV Emulator.

**Comment by andrewlewis** [comment]
I'm afraid not. The Android CDD strongly recommends including an MPEG-2 video decoder for Android TV devices from Android Marshmallow onwards, but it is not required.
