### ISSUE TITLE
2.8.3Where do upgrade logs look?

### ISSUE THREAD

**Issue by qeadsw** [google/ExoPlayer#4625]
What problems have been added or fixed?
There was no update to Bintray!

**Comment by ojw28** [comment]
It's been updated now; thanks.

**Comment by ojw28** [comment]
I'm not sure exactly where you're looking on Bintray, but if it's not updated you can find the release notes [here](https://github.com/google/ExoPlayer/blob/release-v2/RELEASENOTES.md).
