### ISSUE TITLE
ClippingMediaSource in CastPlayer

### ISSUE THREAD

**Issue by Sara-Tareq** [google/ExoPlayer#4627]
I want to ask if there is a way to clip the stream running in the CastPlayer as it's shown in the normal player as clipped but when changing to CastPlayer it starts from a different position

**Comment by AquilesCanta** [comment]
Have a look at the [MediaQueueItem.Builder docs](https://developers.google.com/android/reference/com/google/android/gms/cast/MediaQueueItem.Builder). Hopefully this addresses your issue.
