### ISSUE TITLE
multiple audio codecs in HLS manifest

### ISSUE THREAD

**Issue by daamumbai** [google/ExoPlayer#4628]
Hi,
Our manifest has multiple audio codecs. We tried using ExoPlayer v2.8.0 and it is trying to get only the first audio codec. If the first audio codec is not supported on the device, then there is audio mute issue. We expect, the second audio codec to be picked up and played. We are not seeing this issue with same manifest using MxPlayer.

Please note that below URL's are for illustration purpose only.

#EXTM3U
#EXT-X-VERSION:3
#EXT-X-INDEPENDENT-SEGMENTS
#EXT-X-STREAM-INF:BANDWIDTH=1337600,AVERAGE-BANDWIDTH=1337600,CODECS="avc1.66.30,ec-3,mp4a.40.2",RESOLUTION=640x360,FRAME-RATE=25.000
https://hlsingest2-i.cdnhd.net/hls/live/5012/testhd/master_360p.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1056000,AVERAGE-BANDWIDTH=1056000,CODECS="avc1.42c015,ec-3,mp4a.40.2",RESOLUTION=480x270,FRAME-RATE=25.000
https://hlsingest2-i.cdnhd.net/hls/live/5012/testhd/master_270p1.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=774400,AVERAGE-BANDWIDTH=774400,CODECS="avc1.42c015,ec-3,mp4a.40.2",RESOLUTION=480x270,FRAME-RATE=25.000
https://hlsingest2-i.cdnhd.net/hls/live/5012/testhd/master_270p2.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=492800,AVERAGE-BANDWIDTH=492800,CODECS="avc1.42c00c,ec-3,mp4a.40.2",RESOLUTION=320x180,FRAME-RATE=25.000
https://hlsingest2-i.cdnhd.net/hls/live/5012/testhd/master_180p1.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=352000,AVERAGE-BANDWIDTH=352000,CODECS="avc1.42c00c,ec-3,mp4a.40.2",RESOLUTION=320x180,FRAME-RATE=25.000
https://hlsingest2-i.cdnhd.net/hls/live/5012/testhd/master_180p2.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=281600,AVERAGE-BANDWIDTH=281600,CODECS="avc1.42c00c,ec-3,mp4a.40.2",RESOLUTION=320x180,FRAME-RATE=25.000
https://hlsingest2-i.cdnhd.net/hls/live/5012/testhd/master_180p3.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=3027200,AVERAGE-BANDWIDTH=3027200,CODECS="avc1.42c01f,ec-3,mp4a.40.2",RESOLUTION=1280x720,FRAME-RATE=25.000
https://hlsingest2-i.cdnhd.net/hls/live/5012/testhd/master_720p.m3u8

**Comment by AquilesCanta** [comment]
Do the streams include both audio streams? If not, why not fix the manifest to include only the muxed-in codecs?

If they do include both audio streams, then please see #2014. However, if they have different codecs, they should just work, so please provide a sample stream so we can have a look. We will reopen once the missing information is available below.

**Comment by daamumbai** [comment]
Thanks so much for your reply. In our case, the ts contains all 3 streams i.e. 1 video, 2 audio (ec-3, AAC).
As per the case #2014, I understand that it is not officially supported and in order to support it then we need to go for "alternate renditions". I believe it is supported in HLSv4. We will proceed with that approach.

" I don't think it's officially supported in HLS to mux multiple streams of the same type into TS chunks. This is supported in straightforward MPEG-TS because the pid for each stream is guaranteed to be constant, but in HLS the pid can change from one chunk to the next, which makes supporting multiple streams of the same type problematic in the general case. HLS officially supports multiple audio via HLS master playlists with alternate renditions."

-Nanda

**Comment by daamumbai** [comment]
Another question.

As per the case the case #2014, "but in HLS the pid can change from one chunk to the next". Can you please give me real time example to understand how pid can change from one chunk to next in case of HLS?

**Comment by AquilesCanta** [comment]
> Can you please give me real time example to understand how pid can change from one chunk to next in case of HLS?

If there is a discontinuity tag, the program map table could change, as far as I can see. The issue with this is mapping the tracks from one chunk to the next. Specially if there is no metadata, like the language. Also, we consider that the demuxed approach is the way to go, since allows better signaling in the master plalyist, plus it saves the bandwidth of the non-selected tracks.
