### ISSUE TITLE
Add Player.isPlaying()

### ISSUE THREAD

**Issue by ghost** [google/ExoPlayer#4629]
Hi there geniuses,

`Player.isPlayingAd()` is pretty hot and useful.

Could you geniuses add `Player.isPlaying()`? Because `Player.getPlaybackState()` doesn't know if it's playing or not.

I know you're all google's soldiers. So you must be very proud of `Player.isPlayingAd()`, right? But when you make some open source, could you geniuses temporarily forget about ads? And add that hotter `Player.isPlaying()`? I think it could be more hotter, more useful, more geniussy, more elegant, more brilliant.

**Comment by andrewlewis** [comment]
`player.getPlaybackState() == Player.STATE_READY && player.getPlayWhenReady()` tells you whether the player is playing. I'm not sure if it's worth providing an `isPlaying()` method that returns this. Could you describe your use case for this function? Thanks.
