### ISSUE TITLE
Playing more than one mp4 (one after another) with ExoPlayer 1.3.1

### ISSUE THREAD

**Issue by raylee4204** [google/ExoPlayer#463]
Since I upgraded the ExoPlayer to 1.3.1, it doesn't play another song after it plays the first one.

To explain more about the state, when ExoPlayer initially prepares a source, it plays fine but when i try to play another song after that, it gets stuck in Prepare state.

Here's the modified version of ExtractorRendererBuilder sample:
```java
    private static final int BUFFER_SIZE = 5 * 1024 * 1024;

    private final Context mContext;
    private final Extractor mExtractor;
    private Uri mUri;

    public ExtractorRendererBuilder(Context context, Extractor extractor) {
        mContext = context;
        mExtractor = extractor;
    }

    @Override
    public void setUri(Uri uri) {
        mUri = uri;
    }

    @Override
    public void buildRenderers(RithmPlayer player, RithmPlayer.RendererBuilderCallback callback) {
        // Build the audio renderer.
        DataSource dataSource = new DefaultUriDataSource(Util.getUserAgent(mContext, "ExoPlayer"), null);
        ExtractorSampleSource sampleSource = new ExtractorSampleSource(mUri, dataSource, mExtractor, 1,
                BUFFER_SIZE, ExtractorSampleSource.DEFAULT_MIN_LOADABLE_RETRY_COUNT_ON_DEMAND);
        MediaCodecAudioTrackRenderer audioRenderer = new MediaCodecAudioTrackRenderer(sampleSource,
                null, true, player.getMainHandler(), player);

        // Invoke the callback.
        TrackRenderer[] renderers = new TrackRenderer[RithmPlayer.RENDERER_COUNT];
        renderers[RithmPlayer.TYPE_AUDIO] = audioRenderer;
        callback.onRenderers(null, null, renderers);
    }
```

setUri is called in DemoPlayer which looks like the following
```java
    public void prepare(Uri uri) {
        if (rendererBuildingState == RENDERER_BUILDING_STATE_BUILT) {
            player.stop();
        }
        if (builderCallback != null) {
            builderCallback.cancel();
        }
        multiTrackSources = null;
        rendererBuildingState = RENDERER_BUILDING_STATE_BUILDING;
        maybeReportPlayerState();
        builderCallback = new InternalRendererBuilderCallback();
        rendererBuilder.setUri(uri);
        rendererBuilder.buildRenderers(this, builderCallback);
    }
```

The sample source of the song yon can try :   https://stream.svc.7digital.net/stream/subscription?trackId=40875019&shopid=1756&formatId=56&userId=qa-856&clientId=b7ecc46696d4f1e484c225b4b33abf0366d82de&oauth_consumer_key=7dwqyampfmhr&oauth_nonce=1431708820045&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1431708820&oauth_signature=EYEJUY9jE7eL2vxEa74pBIJlOgI%3D

**Comment by ojw28** [comment]
You need to create a new Mp4Extractor for each playback, rather than re-using the same one. Please try and see if this fixes the problem for you.

**Comment by raylee4204** [comment]
Thanks.

That fixes it. Is it required to create a new extractor to only change a source?

**Comment by ojw28** [comment]
What does it mean to change a source?

**Comment by raylee4204** [comment]
I mean change source of audio without creating a new instance of extractor

**Comment by ojw28** [comment]
I don't really understand. How would you achieve that in code? How is it different to playing a new MP4?

**Comment by softlion** [comment]
An extractor extracts. A source get samples. Changing a property of the source (the url) should work without having to recreate a new extractor.
