### ISSUE TITLE
SimpleExoPlayerView and SimpleExoPlayer play video blank screen when resume video

### ISSUE THREAD

**Issue by hafiz013** [google/ExoPlayer#4632]
### Issue description
Hi dear developer, I am using com.google.android.exoplayer:exoplayer:r2.5.1 which is play for video from internet (link url). The problem happen when i resume the video sometimes, exoplayer attach to simpleexoplayer view play blank video but run audio only.  

### Reproduction steps
Describe how the issue can be reproduced, ideally using the ExoPlayer demo app.
1) When pause the video no issue but when resume the video sometimes blank screen with audio is playing.

### Link to test content
Provide a link to media that reproduces the issue. If you don't wish to post it
publicly, please submit the issue, then email the link to
dev.exoplayer@gmail.com using a subject in the format "Issue #1234".
sample media : "https://archive.org/download/BigBuckBunny_328/BigBuckBunny_512kb.mp4"

### Version of ExoPlayer being used
Specify the absolute version number. Avoid using terms such as "latest".
version : r2.5.1

### Device(s) and version(s) of Android being used
Specify the devices and versions of Android on which the issue can be
reproduced, and how easily it reproduces. If possible, please test on multiple
devices and Android versions.
device : lenovo tb2- x 30L and android version 6.0.1

### A full bug report captured from the device
Capture a full bug report using "adb bugreport". Output from "adb logcat" or a
log snippet is NOT sufficient. Please attach the captured bug report as a file.
If you don't wish to post it publicly, please submit the issue, then email the
bug report to dev.exoplayer@gmail.com using a subject in the format
"Issue #1234".
E/IzatSvc_PassiveLocListener: E/Exiting with error virtual void izat_manager::IzatPassiveLocationListener::onLocationChanged(const izat_manager::IzatLocation*, izat_manager::IzatLocationStatus) line 113 "1"

Only this one show.

**Comment by andrewlewis** [comment]
Please provide a full bug report as requested in the template, then we can investigate further. Thanks.

**Comment by hafiz013** [comment]
Problem solve when i use com.google.android.exoplayer:exoplayer:2.8.2, replace SimpleExoPlayerView with PlayerView and replace depreciate function ExtractorMediaSource with ExtractorMediaSource.Factory(dataSourceFactory).setExtractorsFactory
                (new DefaultExtractorsFactory()).createMediaSource(Uri.parse(pathVideo));

Please make it this issue survive as guideline to others.

**Comment by ojw28** [comment]
It sounds like you resolved the problem just by updating to a more recent version, which is kind of a default thing to try. I don't think we need to explicitly document this.

**Comment by hafiz013** [comment]
please open back this issue since it still persistent happen again but sometimes.
