### ISSUE TITLE
One question about playing HLS stream with multi audio codecs

### ISSUE THREAD

**Issue by ybai001** [google/ExoPlayer#4638]
Issue:
When playing a HLS stream with multi audio codecs (i.e. one AAC + one Dolby EAC3), ExoPlayer will take more time in startup process than those with only one audio track.  The startup time is calculated by ExoPlayer status from STATE_IDLE to STATE_READY. And the more audio tracks exist in HLS, the more obvious this issue is.  
However, Apple devices don’t have this issue with the same HLS streams. A test report with comparing result of ExoPlayer and iOS can be accessed by emailing Yanning.Bai@dolby.com (I also send the report to dev.exoplayer@gmail.com.

Question:
For a HLS stream with multi audio tracks,  it looks like ExoPlayer will select the audio track to be played only after all the audio media playlist files are loaded and parsed. And meanwhile,  all the audio track contents are buffered until the selected audio track has buffered enough data for the time of bufferForPlaybackMs.

Since the HLS manifest file has already all the audio track information,  why doesn’t exoplayer select audio track before downloading media playlist file and content? The purpose of this question is to check whether there is a possibility to optimize the startup time of ExoPlayer when playing HLS stream with multi audio codecs.

Version of ExoPlayer:
2.8.2 demo app

Reproduction steps:
The issue can be reproduced in the demp app by playing two HLS streams to compare. One stream is a video with one audio track, the other is the same video content with multi-codec audio tracks.

Android device:
Pixel2  with Android 8.1

**Comment by AquilesCanta** [comment]
Hi @ybai001, please have a look at our [medium post](https://medium.com/google-exoplayer/faster-hls-preparation-f6611aa15ea6) about HLS preparation. If this does not help, please provide a sample stream, so we can know what the stream looks like.
