### ISSUE TITLE
how to show thumbnails

### ISSUE THREAD

**Issue by hafiz013** [google/ExoPlayer#4639]
Hai, may i know how to show thumbnail of video before can play and pause as show in attachment. For your information, i use PlayerView, SimpleExoPlayer and custom controller_layout.

Note: I do research some say use setDefaultArtwork but still not working.
than you.

![content rodeo tablet movies](https://user-images.githubusercontent.com/6707224/43952510-c0fee0d8-9cc8-11e8-8b62-31d6f9330a6f.png)

**Comment by andrewlewis** [comment]
Can you show an `ImageView` on top of your `PlayerView` with the bitmap you want to display, then hide it when you want to show the player view?

**Comment by hafiz013** [comment]
ok note
