### ISSUE TITLE
Rockchip miniTV - Video freezes while switching variants in HLS

### ISSUE THREAD

**Issue by krok55** [google/ExoPlayer#464]
Hello,

Following this bug: https://github.com/google/ExoPlayer/issues/400

I have the following problem with version 1.3.1 (on Rockchip miniTV device):
While switching variants (from higher to lower), `getChunkOperation()` tries to load the corresponding playlist.
Following that event, the picture freezes while the sound continues to play.
After several more minutes the sound stops too.

I've tried to apply all the patches that fixed the problem above for me in version 1.2.3 - no luck this time.
I suspect that this time it's something else...
Have any idea what change could have caused this?

Thanks.

**Comment by krok55** [comment]
Hello,

I think I found the bug:

In `MediaCodecTrackRenderer`, method `onInputFormatChanged`:
You have the following lines:
```java
      if (codecHasQueuedBuffers) {
        // Signal end of stream and wait for any final output buffers before re-initialization.
        codecReinitializationState = REINITIALIZATION_STATE_SIGNAL_END_OF_STREAM;
      } else {
        // There aren't any final output buffers, so perform re-initialization immediately.
        releaseCodec();
        maybeInitCodec();
      }
```

As far as I understand, this piece of code is intended to allow some sort of buffer draining before switching variants (and re-initializing the codec)

However, the code that was supposed to finally release the old codec was not executed on my device. I'm talking about the method `drainOutputBuffer`:

```java
    if ((outputBufferInfo.flags & MediaCodec.BUFFER_FLAG_END_OF_STREAM) != 0) {
      processEndOfStream();
      return false;
    }
``` 

It seems that the "if" condition doesn't become true on relatively old android versions (mine is 4.2.2).
Since 
```java
outputBuffers = codec.getOutputBuffers();
```
uses the depricated method `getOutputBuffers()`.

Can you please elaborate on the reason behind this "buffer draining" mechanism? (was initially added on Pull Request #221 
I'm trying to think what is the best solution here...
Currently I just commented out the condition in OnInputFormatChanged and everything works fine on my device.

**Comment by ojw28** [comment]
We saw similar behaviour on Tesco's HUDL device, and fixed it with a workaround detailed (here)[https://github.com/google/ExoPlayer/blob/master/library/src/main/java/com/google/android/exoplayer/MediaCodecTrackRenderer.java#L954]. 

In the demo app (use a new release, like current master or dev branch), do you observe that DASH playbacks freeze quite quickly when they go to switch up to a higher format? Do you also observe that playbacks never transition to the ENDED state once playback has finished (you'll see the elapsed time continue to increase indefinitely)? If so, then it's likely to be the same issue.

If you make the method linked above so that it returns true on the affected device (i.e. indicating that the workaround is required) then you'll probably find that things start working correctly. If so, we should add a line there to enable the workaround for the problematic decoder on the affected device.

**Comment by krok55** [comment]
This seems to be a different issue.
I can easily reproduce it with the latest dev version.
I also have the code you mentioned (```codecNeedsEndOfStreamWorkaround```) in my ```MediaCodecTrackRenderer``` - and it doesn't resolve the issue above.

It works quite well for me without the "end-of-stream-codec-draining" logic - what was the original need/bug behind those lines?

**Comment by ojw28** [comment]
The description of the change you reference describes what it fixes. The second bullet point in that description is about waiting for all buffers to be output from a decoder before it's released to instantiate the next one (previously the code would tear down the decoder without waiting for this to happen, which would result in some frames being dropped).

codecNeedsEndOfStreamWorkaround is there to workaround issues related to the change. It's not enough to just have that code. You need to modify that method to return true on the problematic device. Currently it only returns true on HUDL devices.

**Comment by krok55** [comment]
OK... now I understand.
My device name (as indicated by Util.DEVICE is: "rk31sdk")
I've changed the ```codecNeedsEndOfStreamWorkaround``` method to be:

```java```
  private static boolean codecNeedsEndOfStreamWorkaround(String name) { 
	  Log.d("ExoPlayer", "device="+Util.DEVICE);
	  return Util.SDK_INT <= 17 && ("ht7s3".equals(Util.DEVICE) || "rk31sdk".equals(Util.DEVICE)) // Tesco HUDL
        && "OMX.rk.video_decoder.avc".equals(name);
    
  }
```

I have two questions left:
1. Why do you limit the workaround only for API <= 17? Do we know for sure that the problem won't occur on later versions?
2. Do you plan to commit this change into the latest "dev" branch? 

Thanks a lot for the help.

**Comment by ojw28** [comment]
Does that change resolve the issue on your device? We don't know for sure what devices or API levels it affects, but it makes sense to target the rule as specifically as possible and expand it as needed.

It's possible (although unproven) that it affects all API level 17 devices using the OMX.rk.video_decoder.avc decoder.

**Comment by krok55** [comment]
Yes. It resolves the issue on my device.

**Comment by ojw28** [comment]
This should be fixed on dev by the change above. Please test, and let us know if this is not the case.

**Comment by krok55** [comment]
Hi,

I just tested this issue on another Rockchip device with custom ROM installed on it.
The problem reoccurs there, but the device doesn't identifies itself as "rk30sdk" but as "i9100".

I have a feeling that the problem is not device-dependent, but will reoccur on all devices with SDK <= 17 and constantly adding more and more Chinese devices - will make this workaround very hard to maintain (such Chinese devices are getting more and more popular in my country and many others)

Maybe it is better just to leave the first two conditions without checking the device identification?

**Comment by ojw28** [comment]
Yeah, probably. We'll discuss + probably push a change to dev to do that. Thanks!
