### ISSUE TITLE
Show two player view with one stream in same time

### ISSUE THREAD

**Issue by AryaNyx** [google/ExoPlayer#4640]
I need to transfer a exoplayer to a dialog and show it till dialog is showing and after dismiss remove it from dialog. i have done it with remove view from parent and add it to dialog view , but i need both in same time , for example i need to show video in main view with blur effect while dialog with same video is showing on screen. how can i do it , i don't want to add two player and request stream for both of them seperatly. it will consume network bandwidth. Any one has any idea ? Thanks in advanced.

**Comment by andrewlewis** [comment]
I don't think the Android view system provides a way to show surface output in two views at the same time like this. It's possible to implement it yourself by passing the decoder a surface from a `SurfaceTexture` so it can render off-screen, then copying from there to two different output `SurfaceView`s using GLES. The blurring effect could also be applied as part of the copy shader for one of the videos.
