### ISSUE TITLE
Back buffer implementation

### ISSUE THREAD

**Issue by kanthicn1** [google/ExoPlayer#4644]
In ExoPlayer 2.8.2, there are two new interfaces `retainBackBufferFromKeyframe` and `getBackBufferDurationUs`, which, according to the comments in `LoadControl.java` and my experiments, retain `getBackBufferDurationUs` worth of buffer *behind* the playback position. I implemented my own `LoadControl` and returned `100*1000*1000`us for the call `getBackBufferDurationUs`. But, when I seek back in my video, why do I still significant (order of 1-2s) of rebuffering time? I have verified there's no new segment downloaded for the playback to start. So, the player definitely has these 'seemed' segments in its buffer. I am unable to figure out what ExoPlayer is doing for ~1s before switching the player back to playing state. Has any body played with this brand new interface? Please share any insights.

Thanks

**Comment by andrewlewis** [comment]
If you're playing video and using frame-exact seeking (the default), one possible explanation for the 1--2 second pause is that the video decoder is decoding from the previous keyframe and this is taking some time. If you're using a large keyframe interval the decoder may need to process a lot of data before it can render the frame at the requested seek position. If you see that input is queued to the video decoder immediately after seeking but it takes a while for the first frame to be rendered this is probably what's going on. To avoid the pause, you could decrease the keyframe interval (GOP size) or set seek parameters that allow adjusting seeks to keyframes.

**Comment by kanthicn1** [comment]
This is a great tip for me. Thanks @andrewlewis. It would be great if you could tell me if there's a way I can see whether "input is queued to the video decoder immediately after seeking". Are there any callbacks or debug statements that I can look for?

**Comment by andrewlewis** [comment]
@AndroidRocks I don't think there's a way to verify this based on existing logging but you could add some logging in `MediaCodecVideoRenderer.skipOutputBuffer` or set a breakpoint there, and see whether it is hit immediately after requesting a seek (versus after the pause, in which case something else is going on).

**Comment by kanthicn1** [comment]
Thanks @andrewlewis . I added a debug and tracked this. Once the "seek is processed", i.e., my listeners have received the "onSeekProcessed" event, the debug statement from `skipOutputBuffer` starts. It is repeated several times and then the first frame is rendered very soon (< 20ms) after the last debug statement of `skipOutputBuffer` appears. So, what you said checks out that the player is spending most of the time decoding and discarding frames before it starts playback again. 

I have an additional question, if you don't mind. Shouldn't back-seek perform strictly better in a player with a non-zero (seek-duration+ delta) back buffer configured than a player that doesn't have any back buffer configured? The context of this question is : if I execute 30 back seeks on a video with ExoPlayer-with-backbuffer (let's call with withBB) and repeat this with 30 back seeks in Exoplayer-without-backbuffer (withoutBB), the average rebuffering time per seek is "some times"* worse in  withBB. The seek duration is always less than the BB duration. Under what circumstances of bandwidth and video can withoutBB perform better than withBB?

Thank you very much for your patience and insights!

**Comment by andrewlewis** [comment]
Assuming seeking is always to the same frame: whether you hit the network or not you always have to decode up to the frame-exact seek destination, so I'd expect seeking to take the same or longer time without a back buffer.

If the seek destination was not always the same frame in your experiment, that might explain the surprising result: the cost of the decoding step depends on how many frames are between the preceding keyframe and the seek destination, so if you have to load from the network but then the seek destination is on a keyframe that could lead to an overall lower seek duration compared to the case where you don't load from the network but have to decode lots of frames to get to the seek destination. For the decoding step, in the best case you're seeking to a keyframe so the decoding has very low cost, and in the worst case you have to decode an entire group of pictures. The worst case with back buffer could take longer than the best case without a back buffer.

[Aside: I guess another thing to bear in mind is that here I'm thinking about the time taken until the first frame gets rendered when seeking. If the user requested to seek while the player was ready and the seek was serviced from the back buffer, I'd expect the video renderer to be ready as soon as it has rendered the seek destination frame (the player's future buffered duration is now even longer than it was before the seek). If the seek can't be serviced from the back buffer we also need to wait until the player has enough media buffered to transition from the buffering to ready state.]

**Comment by kanthicn1** [comment]
Thanks @andrewlewis. I can't guarantee that the seeks are to the same frame in both cases. But, from your answer what I take away is that my minimal sample set of 30 seeks is not making sure that "on an average the seeks are to the same location". I should probably execute many more seeks for the law of large numbers to kick in (and also make sure the video and throughput are the same to rule out decoding time differences because of content differences and download time differences).

I really appreciate your help. Thank you.
