### ISSUE TITLE
Not able to add custom headers to offline DRM key request

### ISSUE THREAD

**Issue by danha306** [google/ExoPlayer#4647]
### Issue description
When requesting an offline Widevine key with our key provider (DRMToday) requires the header field "x-dt-custom-data" with associated information. I can find no way of doing that with the OfflineLicenseManager, as the "optionalKeyRequestParameters" seems to add the field to the body instead of the header. Packet sniffing with Charles shows that the "x-dt-custom-data" field is not included in the headers.

### Reproduction steps
Request an offline license from a provider that requires custom data in the request header

### Version of ExoPlayer being used
2.8.0

### Device(s) and version(s) of Android being used
Tested on OnePlus 5T running 8.1.0

**Comment by danha306** [comment]
I accidentally pressed "post" instead of backspace... I can't seem to delete this.

**Comment by workspace** [comment]
I recommend to set keyRequestProperties for [HttpMediaDrmCallback](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/drm/HttpMediaDrmCallback.java). If you  open [this lines](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/drm/DefaultDrmSession.java#L510-L516), you can find callback executes actual requests to your drm license server.

**Comment by danha306** [comment]
We use HttpMediaDrmCallback in other parts of the app and setting custom headers works fine there. The problem is that the [OfflineLicenseManager](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/drm/OfflineLicenseHelper.java) does use HttpMediaDrmCallback as well, but doesn't give me any possibility to set custom headers or modify the HttpMediaDrmCallback. I could of course download the source code and modify the OfflineLicenseManager class, but if possible I'd like to avoid that.

**Comment by workspace** [comment]
Use this [constructor](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/drm/OfflineLicenseHelper.java#L117). you can pass your own callback for OfflineLicenseHelper and it will work fine.

**Comment by danha306** [comment]
Thank you, that seems to have worked!
