### ISSUE TITLE
ABR is not working on Android version 4.4.2

### ISSUE THREAD

**Issue by gauravbarthwal** [google/ExoPlayer#4648]
Hi There,

I am using ExoPlayer 2.8.2 and ABR is not working on Android 4.4.2. If video starts with lower bit rate then it keeps on playing on the same bitrate, but on the devices above Android version 5.0. Previously I was using ExoPlayer version 2.6.1, I could able to set minimum bitrate value but with 2.8.2 in AdaptiveTrackSelection.Factory parameter is been removed.

Any suggestion what would I do for the problem.

Thanks in Advance.

**Comment by erdemguven** [comment]
maxInitialBitrate parameter is removed from AdaptiveTrackSelection, do you mean that? In the latest version you can set it in DefaultBandwidthMeter.Builder.

I have tested ABR on a 4.1.1 device and it works fine. I'll try on a 4.4.2 device too.

**Comment by erdemguven** [comment]
It works fine on 4.4.2 as well.

**Comment by gauravbarthwal** [comment]
@erdemguven I am testing it on Android STB which is 4.4.2 and on that device if the video starts playing on lower bitrate then it is not getting changed.

I have updated determineIdealSelectedIndex() in AdaptiveTrackSelection to play higher bitrate everytime.

**Comment by erdemguven** [comment]
Sorry for late response. Could you play one of the ["YouTube DASH" samples](https://github.com/google/ExoPlayer/blob/release-v2/demos/main/src/main/assets/media.exolist.json) from ExoPlayer demo app, on your device and send us a bug report.

**Comment by gauravbarthwal** [comment]
Sorry @erdemguven, I got to know that the device has some issues and I had to include some libraries to get ABR work.
Thank you for your reply.
