### ISSUE TITLE
AnalyticsListener.onBandwidthEstimate() is not called

### ISSUE THREAD

**Issue by noamtamim** [google/ExoPlayer#4649]
### Issue description
I've started using the new `AnalyticsListener`, with the hope of replacing multiple metrics-collection listener with a single one. Everything seems to work fine, except that `onBandwidthEstimate()` is never called.

### Reproduction steps
Using the main demo app:
1. In ExoPlayer's `EventLogger`, find `onBandwidthEstimate()` and replace the first line from `// Do nothing.` to something like `logd("onBandwidthEstimate");`. 
2. Play any video. The text is never logged to logcat.

### Link to test content
Use any sample in the demo app.

### Version of ExoPlayer being used
2.8.3 (release-v2 at the time of writing).

### Device(s) and version(s) of Android being used
Emulator with Android 27.

### A full bug report captured from the device
No relevant.

**Comment by noamtamim** [comment]
The same is true for other `AnalyticsListener` events. For example, `onViewportSizeChange()` and `onNetworkTypeChanged()`. For those two, `AnalyticsCollector` has `notifyViewportSizeChanged()` and `notifyNetworkTypeChanged()` respectively. These methods are currently only called from test code - they are probably meant to be called from an internal listener.

**Comment by erdemguven** [comment]
I can confirm that on dev-v2 branch they work fine. Btw, onNetworkTypeChanged was removed and onViewportSizeChange was renamed to onSurfaceSizeChanged.

**Comment by noamtamim** [comment]
Thanks @erdemguven. Any chance of getting it fixed in the 2.8.x series as well (probably without the rename). Assuming there's going to be a 2.8.4, of course. The update from ExoPlayer 2.x to 2.y is typically breaking APIs and changing things that require extensive QA on our side.

Alternatively, if you can tell me how to capture `onViewportSizeChange` myself from a different source it will be great. `onBandwidthEstimate` is already available as `BandwidthMeter.EventListener.onBandwidthSample()`, so I have a workaround there.

**Comment by ojw28** [comment]
We don't have any plans to back-port the fix, sorry.

**Comment by noamtamim** [comment]
@ojw28 thanks, I asked two months ago :-)
By now we'll soon upgrade to 2.9.x anyway, so we're good. Thanks again.
