### ISSUE TITLE
Question: is it possible to play a video while also downloading it to a file?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [google/ExoPlayer#4650]
This can be very important for caching, in case we wish to view the video again later.

**Comment by erdemguven** [comment]
If you mean downloading a media using DownloadManager then yes, it's possible. It's recommended to not set FLAG_BLOCK_ON_CACHE on your player CacheDataSource so it isn't blocked in case it tries to play the same block the downloader downloads.

**Comment by AndroidDeveloperLB** [comment]
Maybe. Perhaps I will try to explain why I ask this:

I mean that supposed I have some URL that is directly to mp4 or mkv file, and I ask if it's possible to play the URL video while also saving it to a file.
It's not exactly like normal cache, because normal cache means it might automatically (or manually) be removed some time later, and I want full control of the file, to make it available for as long as I wish in the app.

Of course, it could also be useful to know how to save to cache, but that's not exactly what I asked.

**Comment by erdemguven** [comment]
Content downloaded by DownloadManager isn't removed automatically if you use NoOpCacheEvictor while creating your Cache instance (which is recommended setup for normal offlining cases).

**Comment by AndroidDeveloperLB** [comment]
Why close it?

Is there a way to download the content that's shown?

**Comment by erdemguven** [comment]
Closed as I think I answered the question. Do you see a problem with the recommended solution?

**Comment by AndroidDeveloperLB** [comment]
@erdemguven I don't understand. I've tried to explain the question, but I didn't see a solution.
Do you want me to explain it more?
I want the player to also download the content into a file while playing, for long-time caching (because videos take a lot of bandwidth).

**Comment by linhai326** [comment]
i think @erdemguven gave you a very clear answer. You may want to check the exoplayer demo app and see how offline downloader work. The downloaded segments are saved on disk in a exoplayer cache format: it is persistent.

**Comment by AndroidDeveloperLB** [comment]
@linhai326 You mean this:
https://github.com/google/ExoPlayer/issues/4650#issuecomment-413511224

Have you tried it? I don't even understand what he means, and whether or not he understood my question...

**Comment by AndroidDeveloperLB** [comment]
@linhai326 I've now tried to import the project, and it got this error 

```
Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10.1/userguide/command_line_interface.html#sec:command_line_warnings
```

And I'm using the latest of the latest versions of the IDE, so should work well.
It works, but it has this error.

**Comment by AndroidDeveloperLB** [comment]
I've tested the sample. I don't see any file in the app's folder, after playing various video files :

![image](https://user-images.githubusercontent.com/5357526/46256975-01a02100-c4bb-11e8-957f-196737a967e5.png)

**Comment by linhai326** [comment]
did you click the download icon on menu/play item screen? that will start the downloader and after you select the track, content will be saved to this folder.

**Comment by AndroidDeveloperLB** [comment]
@linhai326 There is no icon anywhere while playing a video.
See example:

![image](https://user-images.githubusercontent.com/5357526/46317473-c21d2600-c5db-11e8-9424-67a966702a19.png)

Again, what I asked, is download while playing a video, as you play it. Together.

It would be bad for 2 threads/processes to download the same video twice (once for playback and once into a file)

**Comment by linhai326** [comment]
![img_20181001_153037](https://user-images.githubusercontent.com/19922136/46319520-2d8cd680-c58f-11e8-9c59-7f0e74a70b25.jpg)

**Comment by linhai326** [comment]
If you need to do the streaming and downloading together, you need to impl this feature by yourself. Demo app's downloader can be a guide.
Actually, in real world, the usage cases can be more complicated if you have multiple adaptive tracks: just think about when bandwidth is low, do you still want to save the low quality of content the user streams? You might want to give the user  the best quality, then you have to separate the download from stream...

**Comment by AndroidDeveloperLB** [comment]
@linhai326 About the screenshot, this is just for downloading. When I click on it, it doesn't play anything. Only downloads. I asked about playback that includes downloading. 

About adaptive tracks, do you mean like on YouTube, that as you play, the quality might change?
We just want to show a video that will most likely be used later, so we want to save it.

My question was if it's possible. You said it's done on the sample. I don't see it there. Please explain what to do. Can't I just have a listener of the stream that it handles, and save it to a file, or something?

**Comment by erdemguven** [comment]
@AndroidDeveloperLB If you create a SimpleCache and use it through a CacheDataSource whatever the user streams will be stored locally on the cache. While you create your SimpleCache instance, if you use a NoOpCacheEvictor, it won't remove anydata from cache automatically.

If you want to download the whole video not just the part user watches then you should use DownloadManager.

**Comment by AndroidDeveloperLB** [comment]
@erdemguven Using the way you wrote, when will the file be ready? Only after the user watched 100% of it? Or near the end of watching, as the buffer doesn't need anything more to download? Or does it continue to download even after stopped playing?

Does the way of using DownloadManager allows to play while downloading the same file, without using multiple connections ?

**Comment by erdemguven** [comment]
If you use DownloadManager, it will download the whole video. If you just plug in a cache to your normal playback, it only stores what has been read from server, so if user watches 10 minutes you have 10 minutes stored on the cache.

If you use DownloadManager, and the user tries to seek to a position not yet downloaded another connection to server is set up.

**Comment by AndroidDeveloperLB** [comment]
@erdemguven So if I want to play and download, and continue to download, I need to use DownloadManager, right? But how do I let ExoPlayer play the video from the file that's being downloaded, as it downloads?

About the cache solution, I think that if the user watched 10 minutes, the file might take a bit more than 10 minutes, no? It caches an extra few seconds for smoother playback, that will be important in case there is a very temporary Internet issue.

I don't understand the last sentence. Seems like it's cut. What happens when the user tries to seek to a position it didn't download yet?

**Comment by erdemguven** [comment]
https://medium.com/google-exoplayer/downloading-streams-6d259eec7f95
https://medium.com/google-exoplayer/downloading-adaptive-streams-37191f9776e
In these blog posts you can find out how to play downloaded content. 

> About the cache solution, I think that if the user watched 10 minutes, the file might take a bit more than 10 minutes, no? It caches an extra few seconds for smoother playback, that will be important in case there is a very temporary Internet issue.

Correct.

> I don't understand the last sentence. Seems like it's cut. What happens when the user tries to seek to a position it didn't download yet?

If the download is just started and the user wants to watch end of the video as the required data isn't available in the cache yet, the player starts reading it from server. To prevent multiple connections to server you can create a PriorityTaskManager instance and pass it your LoadControl and DownloadManager. PriorityTaskManager would stop DownloadManager while the player buffers.

**Comment by AndroidDeveloperLB** [comment]
@erdemguven Not sure I understand how to make it work. Do you have a sample, perhaps?

**Comment by AndroidDeveloperLB** [comment]
Wrote this question here:

https://stackoverflow.com/questions/53692452/how-to-download-a-video-while-playing-it-using-exoplayer
