### ISSUE TITLE
Question: How to detect if the given dash stream has subtitles?

### ISSUE THREAD

**Issue by userdimi** [google/ExoPlayer#4651]
I want to display my subtitles buttons dynamically depends if a the dash stream has subtitles or not. How can I detect this inside the Exoplayer?

**Comment by erdemguven** [comment]
You can check the ExoPlayer demo app to see how the subtitle (text) button is displayed dynamically:
com.google.android.exoplayer2.demo.PlayerActivity#updateButtonVisibilities
