### ISSUE TITLE
Request: add option to avoid having black content while loading, if shown something else before

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [google/ExoPlayer#4652]
Suppose I view some video file, and then I want to view another video file. 

At the moment of loading the new video file, I've noticed it shows a black content for a very short time (probably the caching mechanism from storage to RAM).

Please grant a way to prevent this, meaning to show the previous video on paused state (or just an image of it at this point) till the new one is played.

Maybe, suppose I have a cached image of what is supposed to be on the video (first frame) , I could tell ExoPlayer to show the image till it actually starts playing?

For reference, this is how to initialize the player:

```
        player = ExoPlayerFactory.newSimpleInstance(context, DefaultTrackSelector())
        player!!.volume =0f
        playerView.player = player
        player!!.addListener(...)
        player!!.playWhenReady = true
        player!!.repeatMode = Player.REPEAT_MODE_ALL
        viewTreeObserver.addOnWindowFocusChangeListener { hasFocus -> player?.playWhenReady = hasFocus }
```

And then to play a video file, I use this:

```
fun SimpleExoPlayer.playVideoFile(context: Context, file: File) {
    val uri = Uri.fromFile(file)
    val dataSourceFactory = DefaultDataSourceFactory(context, getUserAgent(context))
    val mediaSource = ExtractorMediaSource.Factory(dataSourceFactory).createMediaSource(uri)
    prepare(mediaSource)
}
```

```
        @JvmStatic
        fun getUserAgent(context: Context): String? {
            val packageName = context.packageName
            val info = context.packageManager.getPackageInfo(packageName, 0)
            val appName = info.applicationInfo.loadLabel(context.packageManager).toString()
            val versionName = info.versionName
            return "$appName/$versionName (Linux;Android ${Build.VERSION.RELEASE}) ${ExoPlayerLibraryInfo.VERSION_SLASHY}"
        }
```

**Comment by erdemguven** [comment]
If you use a playlist, this should be handled automatically. You can even use a dynamic playlist now:
https://medium.com/google-exoplayer/dynamic-playlists-with-exoplayer-6f53e54a56c0

**Comment by AndroidDeveloperLB** [comment]
I don't use a playlist. Well at least not in the same sense of a video/audio playlist as on normal apps.

The thing is that there is a manual trigger (user presses on an item from a list) that will play a video that's related to what was chosen, repeatedly (same video).

It means something like master-view or gallery&preview: There is a list of thumbnails, and each of them will play a different video, repeatedly. Some of the items will trigger showing an image or something else, instead of a video. but that's probably out of the scope for telling you about it :)

**Comment by ojw28** [comment]
Does calling `PlayerView.setKeepContentOnPlayerReset(true)` do what you're looking for? I suspect that calling this on your `PlayerView` might just give you the behavior you're looking for.

The only case I'm aware of where you'd still expect to see black during loading is when playing DRM protected content, which I think is a platform limitation related to the way that the secure video path works.

**Comment by ojw28** [comment]
You can also use the `keep_content_on_player_reset` attribute, if the `PlayerView` is specified in a layout xml. See the [Javadoc](https://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/ui/PlayerView.html) for details.

**Comment by AndroidDeveloperLB** [comment]
OK I will try it.
Say, if this doesn't work, will ViewAnimator work? Meaning having 2 PlayerViews, while one pauses as the other starts playing?
Is it ok to have multiple views for playing video?

**Comment by AndroidDeveloperLB** [comment]
Seems it fixed the issue.
Still I wonder : would having ViewAnimator with 2 PlayerViews work ?

**Comment by ojw28** [comment]
No idea, but it doesn't sound like as good of a solution. `PlayerView.setKeepContentOnPlayerReset(true)` is designed specifically for this purpose.

**Comment by AndroidDeveloperLB** [comment]
Well, it doesn't allow to have an animation between the 2 states, for example. It's just a boolean flag...

**Comment by ojw28** [comment]
At the lowest level, ExoPlayer just outputs video to a surface. I'm sure it's possible to make two player instances, have them output to separate `TextureView`s (note: `SurfaceView`'s don't generally animate so well, so `TextureView` would be preferable for this kind of thing), and then animate between them.

How to do that is a general Android UI question. It would probably be the same whatever the `TextureView`'s were displaying, whether video or something completely different. Hence it's outside the scope of this issue tracker, and is also not something we're particularly expert in.

**Comment by AndroidDeveloperLB** [comment]
Wait, so PlayerView uses SurfaceView instead of TextureView? Isn't TextureView superior?
How can I make it use TextureView instead?

**Comment by ojw28** [comment]
It can use either. Please see `surface_type` as documented [here](https://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/ui/PlayerView.html). Our [FAQs](https://google.github.io/ExoPlayer/faqs.html#should-i-use-surfaceview-or-textureview) page documents the trade-off between `SurfaceView` and `TextureView`.

**Comment by AndroidDeveloperLB** [comment]
So in short, it's not superior, and it's actually better only if I animate it or let it be in scrollable container.
OK thanks.
