### ISSUE TITLE
Exoplayer Buffer state freezes the UI

### ISSUE THREAD

**Issue by dmitriisemeniuc** [google/ExoPlayer#4653]
How to avoid the freeze of UI while Exoplayer stays in Buffering state?

Please read my [full question](https://stackoverflow.com/questions/51731941/exoplayer-buffer-state-freezes-the-ui)

**Comment by erdemguven** [comment]
@ojw28 could you look at this?

**Comment by ojw28** [comment]
This sounds like an application issue (and we don't generally have sufficient time to debug application code). I doubt anything ExoPlayer is doing is blocking the main thread. If your UI is freezing, you probably need to attach a debugger, or similar, and work out what the application's main thread is doing during that period.

**Comment by ojw28** [comment]
If you're able to reproduce with our demo app, or can diagnose an actual issue with the library, then please do let us know.
