### ISSUE TITLE
mp4 media file is not playing with exoplayer 2.7.2 in fragment

### ISSUE THREAD

**Issue by Soumyajit19** [google/ExoPlayer#4655]
Exoplayer 2.7.2 is unable to play video from the below mentioned url: 
https://www.dropbox.com/s/1zmwcwvbz207qp8/agility%20900%20mid%20jr%20-%20001%20---%20Expires%20on%2020-07-2022.mp4 

My code snippet
          
        simpleExoPlayerView.requestFocus()
        val bandwidthMeter = DefaultBandwidthMeter()
        val videoTrackSelectionFactory = AdaptiveTrackSelection.Factory(bandwidthMeter)
        val trackSelector = DefaultTrackSelector(videoTrackSelectionFactory)
        player = ExoPlayerFactory.newSimpleInstance(activity!!.applicationContext, trackSelector)
        simpleExoPlayerView.player = player
        player.playWhenReady = true
        val extractorsFactory = DefaultExtractorsFactory()
        val mediaDataSourceFactory = DefaultDataSourceFactory(activity!!.applicationContext,
                Util.getUserAgent(activity!!.applicationContext, "My_APP"), bandwidthMeter as TransferListener<in DataSource>)
        val mediaSource = ExtractorMediaSource(Uri.parse(video_url_2),
                mediaDataSourceFactory, extractorsFactory, null, null)
        player.prepare(mediaSource)

**Comment by erdemguven** [comment]
I tried the given video on ExoPlayer demo app 2.7.2 and it plays fine. Please try on different device.

**Comment by Soumyajit19** [comment]
I tried with different device still getting the same error. Please find the log.

com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor) could read the stream.
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractorHolder.selectExtractor(ExtractorMediaPeriod.java:924)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:846)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:308)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:760)

Still I will try with different devices from different manufacturers.

**Comment by erdemguven** [comment]
Do you try to stream the video from link you gave? It's a link to a Dropbox page. You need a direct link to mp4 file to be able to play it.

**Comment by Soumyajit19** [comment]
This is the actual video link : http://players.brightcove.net/3415345270001/default_default/index.html?videoId=ref:p1520466_1
When I tried playing this video with exoplayer 2.7.2 I got the same issue as mentioned earlier. Then I downloaded the video and put it in dropbox and used dropbox shareable link of the video. Still same thing is happening.

**Comment by erdemguven** [comment]
The last link you shared still points to a html page not the video.
