### ISSUE TITLE
C is what?

### ISSUE THREAD

**Issue by ghost** [google/ExoPlayer#4656]
Heelo Mr. PHDs,

Didn't you look in the mirror to evaluate your face? Couldn't see that you were pretty much arrogant? `C` is an arrogant class name, can't you see that? If you "design" a public api, don't name it `A`, or `B`. And don't name it `C`. That is an arrogant name.

For god sake, it's a public api. Rename it to `Constants` instead. You will look much less arrogant. Still. But much less.

Next time, don't name it `E`, `F`.

Next time of next time, don't name it `G`, `H` or `I`. Also tell your kids not to name it `J` or `K`.

Tell your dogs not to name it `L`, `M` or `N`. Make sure to tell your dogs to remind you cats not to name it `O`, or `P`.

PHDs are everywhere. If you watch f.r.i.e.n.d.s show, you know what I mean.

**Comment by erdemguven** [comment]
Thanks for your comment. We'll consider this in the future.
