### ISSUE TITLE
Subtitle rendering in Exoplayer

### ISSUE THREAD

**Issue by junaid24** [google/ExoPlayer#4657]
I developed a basic video player using Exoplayer and added subtitle support to my player using the following code

`Format textFormat = Format.createTextSampleFormat(null, MimeTypes.APPLICATION_SUBRIP,
            null, Format.NO_VALUE, Format.NO_VALUE, "ar", null);
    Uri subtUri = Uri.parse(subtUrl);
    MediaSource subtitleSource = new SingleSampleMediaSource(subtUri,dataSourceFactory, textFormat, C.TIME_UNSET);`
Now what I want is that I should be able to translate subtitles to any language using google translate API. For this what I have done is I was creating an `AsyncTask `and was downloading the complete subtitle file from the URL and then `onPostExecute()` method I was passing that to google translate API for getting new subtitles.

This is the `AsyncTask `that I have created.
```
private class AsyncClass extends AsyncTask<String,Void,String>{

        private String parseResponseFromServer(HttpResponse response) throws IllegalStateException, IOException {
            // TODO Auto-generated method stub
            BufferedReader reader=new BufferedReader(new InputStreamReader(response.getEntity().getContent()));
            String line_read=null;
            StringBuilder builder=new StringBuilder();
            while((line_read=reader.readLine())!=null){
                builder.append(line_read);
                builder.append('\n');
             }

            return builder.toString();
        }


        @Override
        protected String doInBackground(String... url)
        {

            HttpClient client =new DefaultHttpClient();
            HttpGet getreq =new HttpGet(url[0]);

            HttpResponse resp= null;
            try
            {
                resp = client.execute(getreq);
                return parseResponseFromServer(resp);
            } catch (IOException e)
            {
                e.printStackTrace();
                return null;
            }



            //above line will pass the control to onPostExecute()
        }

        @Override
        protected void onPostExecute(String result) {
            // TODO Auto-generated method stub
             try
            {
                saveFile(result);
            } catch (FileNotFoundException e)
            {
                e.printStackTrace();
            }
            subtitleFile = result;
            String newLanguage = "fr";
            subtitleConverter subtitleConverter = new subtitleConverter();
            subtitleConverter.execute(newLanguage);
            //HERE the result will be the response from the server.

        }
    }
```
Here in background I am parsing the subtitle file from URL, saving it and then passing it to google translate. So what I want now is that instead of explicitly downloading subtitles, I should be able to get subtitle from the text renderer of subtitle and then there I can directly pass subtitle to my API and get the result.

Is there any method by which I can get the content of the subtitles using the exoplayer because in first code exoplayer is playing video along with subtitles so somewhere it is getting those subtitle and rendering it I want to know how it is doing and how can I get to that part?

Your help will be appreciated.

**Comment by erdemguven** [comment]
If you're using PlayerView, it adds PlayerView.ComponentListener as text output using TextComponent.addTextOutput() in setPlayer(). 
When PlayerView.ComponentListener.onCues is called it calls subtitleView.onCues(cues).
Cue class has text field. You can translate it and create a new Cue object with the translation and pass to subtitleView.

**Comment by junaid24** [comment]
Thank you mate. I am getting it now.

**Comment by junaid24** [comment]
Hi @erdemguven 
In the above approach getting subtitles from subtitleView.onCues(cues) method of PlayerView class creates a new problem because this is happening just before subtitles are displayed on screen. Here  I am taking subtitles from there translating it and passing to subtitle View but that creates a synchronization issue between the audio and text(Subtitles are coming with a little delay).
So is there any method that I can get subtitle from the renderer itself before coming onto PlayerView so that the next subtitles which are about to come on screen I can translate them beforehand so there will be no synchronization isssues.

**Comment by erdemguven** [comment]
One option:
1. implement a wrapper SubtitleDecoder which wraps another SubtitleDecoder
2. implement a custom SubtitleDecoderFactory which wraps SubtitleDecoderFactory.DEFAULT
3. In your SubtitleDecoderFactory.createDecoder create your SubtitleDecoder which wraps whatever object SubtitleDecoderFactory.DEFAULT.createDecoder returns.
4. In your SubtitleDecoder.dequeueOutputBuffer do the translation on the SubtitleOutputBuffer object returned by the wrapped SubtitleDecoder.
