### ISSUE TITLE
HLS adaptative bitrate video stuck on buffering state on ExoPlayer

### ISSUE THREAD

**Issue by maxcollada** [google/ExoPlayer#4659]
### Issue description
I have HLS ABR streams I am trying to play using ExoPlayer. The player initializes and displays video controls, with the debug overlay info displaying **playWhenReady=true** and **playBackState=buffering** and successfully displaying content's duration, but stays there and no playback happens. 

### Reproduction steps
Load up the linked test content into ExoPlayer's demo app.

### Link to test content
http://video.ocean.com/abr/_definst_/smil:v2/video/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/36D64B7D46B8498494460EAB891AAFC1/93C69734057745FCAD595BD34902B10F.v2.eng.smil/playlist.m3u8

### Version of ExoPlayer being used
ExoPlayer 2.82

### Device(s) and version(s) of Android being used
Pixel XL 2, Android 9 (28)

### Errors and log output
No exception or error is thrown. Following the logger's output the player simply stalls between the following logs:

`D/EventLogger: state [0.06, true, I]`
`D/player: onPlayerStateChanged with playWhenRead=true and playbackState=buffering`
`D/EventLogger: state [0.08, true, B]`
`D/NetworkSecurityConfig: No Network Security Config specified, using platform default`
`D/EventLogger: timelineChanged [periodCount=1, windowCount=1, reason=PREPARED`
`D/EventLogger:   period [36.30]`
`D/EventLogger:   window [36.30, true, false]`
`D/EventLogger: ]`
`D/EventLogger: loading [true]`

From comparing with normal playing HLS streams, the next callback that should trigger that is never reached is **onVideoEnabled**. From inspecting ExoPlayer's handling of the stream, all segments and tags are succesfully parsed.

**Comment by erdemguven** [comment]
@AquilesCanta could you look at this.

I can reproduce the issue. Also I tried to play the stream on VLC, although it starts playback, it stops after a few seconds.

**Comment by AquilesCanta** [comment]
This is not HLS compliant.

The master playlist points to a media playlist, which is fine. However, each segment url points to a new media playlist, while it should point to a media segment. Please clarify if I got something wrong and we will reopen the issue.

**Comment by maxcollada** [comment]
@AquilesCanta To add a bit more, we can play this media using VLC, HLS players like those on the Apple TV and Roku platforms, and with some browser based players, it is ExoPlayer specifically we are having issues with. And after debugging the process using the source code, I can watch all of the Master Playlists being parsed correctly, with each of the ts segments also parsed. The difference with a playing content lies on the call to the `onLoadCompleted` callback, a normal stream will keep the **prepared** boolean true after its initial set on the `onTracksEnded` callback, but this one, when onLoadCompleted is called again, prepared is once again false.

Our team has analyzed each sublink off the master playlist. The master playlist contains links to what Wowza calls chunklists, which are media playlists. Each of the urls in the chunklist retrieves an actual media segment. The tslemurs HLS checker is giving good details about what it is parsing to get all the video data for all bitrates, and it parses one master playlist, then one media playlist per bitrate. While we aren't ruling out that perhaps something subtle in our server configuration is wrong, we are using well known server software (Wowza) specifically capable of creating and serving correct HLS streams. What you're describing (two levels of media playlist) is in the area of behavior completely controlled by Wowza, and we don't believe they're getting it that wrong. What you describe isn't something we are seeing when we test it. If you're certain you are seeing it, could you show us which media playlist contains links to other media playlists?

**Comment by ojw28** [comment]
For what it's worth, playback works if you set `FLAG_IGNORE_AAC_STREAM` in `DefaultTsPayloadReaderFactory`. I didn't look further, but I'd guess the TS variants declare that they contain AAC streams, when they do not, and the player gets stuck trying to read some of those streams to determine their formats.

This theory could also explain why VLC defaults to playing with no sound on my Mac. It's selecting an audio track that it thinks exists, but there's no audio. I need to manually select the other audio stream to get audio as part of the playback.

**Comment by maxcollada** [comment]
@ojw28 That seems to be indeed the source of the problem we can play the content now. Of course more research is needed to spot the root issue exactly, but is an amazing find, thank you very much!

**Comment by maxcollada** [comment]
@AquilesCanta Although it is true that applying the flag solves the issue and allows for playback, this is not an issue with Apple players, which seem to handle the missing AAC stream. It seems ExoPlayer should be able to detect the problem and at least fail in a less silent way, right now it does not throw a warning or an exception or nothing, it simply stays on buffering state. It seems like ExoPlayer should be able to apply the flag on its own on such a case. Although this particular case might be solved, the underlying issue is still pretty much open correct?
