### ISSUE TITLE
How buffer works in ExoPlayer?

### ISSUE THREAD

**Issue by paulocoutinhox** [google/ExoPlayer#4662]
Hi,

We need understand this behaviour in ExoPlayer to understand a problem in our server about file consumption.

So, when i set a mp3 file to play in ExoPlayer, how buffer works (ex: http://mysite.com/file.mp3)?

1 - The player download entire file before start play.
2 - The player download entire file while playing.
3 - The player download file but using current time + X (bytes/seconds/whatever)
4 - Other behaviour

Can anyone help me understand it?

**Comment by erdemguven** [comment]
It's the third one. You might find this video helpful: https://youtu.be/jAZn-J1I8Eg?t=25m1s

**Comment by paulocoutinhox** [comment]
Thanks. This solve our doubt.
