### ISSUE TITLE
Crop & display pieces of stream video in multiple view?

### ISSUE THREAD

**Issue by caominhhoang** [google/ExoPlayer#4664]
I have a MPEG-DASH stream video with 5.1 audio, so I'm going to learn how to independent control each channel volume with ExoPlayer. However in parallel with that, I also need to crop the video screen into 4 pieces, and display each piece in a different view. I have not learned much about ExoPlayer and have no idea to do these things. Does anybody have some clues? Any advice and suggestions will be greatly appreciated. Thank you.

**Comment by erdemguven** [comment]
Duplicate #4658
