### ISSUE TITLE
RTSP Error - Frame Decoding

### ISSUE THREAD

**Issue by amrakshay** [google/ExoPlayer#4667]
I am using following settings in DVR
Bitrate - 128
Resolution - 640x480
FPS - 6

I am facing below RTSP Error
Error is shown in Red Text

![image 1](https://user-images.githubusercontent.com/19661888/44205353-b4b6f400-a173-11e8-98ad-01d87b231aba.png)
![image](https://user-images.githubusercontent.com/19661888/44205355-b4b6f400-a173-11e8-922b-174c73441000.png)
![error](https://user-images.githubusercontent.com/19661888/44206304-f4cba600-a176-11e8-847e-ccc8689244a7.jpg)

Any Suggestions pls ?

**Comment by Ratnadeep22** [comment]
I am also getting the same error while trying to process on images by fetching it from CCTV camera with RTSP

**Comment by andrewlewis** [comment]
Are you using the RTSP support from #3854? It looks like the H.264 bitstream being fed to the decoder is not valid.

**Comment by ojw28** [comment]
RTSP is not officially supported. Adding support is tracked by https://github.com/google/ExoPlayer/issues/55
