### ISSUE TITLE
Unable to connect to local mp4 file by ExtractorSampleSource

### ISSUE THREAD

**Issue by edikfuks** [google/ExoPlayer#467]
Hello!

I am updating the ExoPlayer to 1.3.1 and I am experiencing the issue with  the playback of the local MP4 files:
com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to /storage/emulated/0/Android/data/com.getvictorious.staging.eatyourkimchi/files/DCIM/Video/Video-20150518_142803.mp4

I am passing the uri to the ExtractorSampleSource: 
ExtractorSampleSource sampleSource = new ExtractorSampleSource(uri, dataSource, extractor, 2,
                BUFFER_SIZE);

Please advise what could cause this exception.

Thank you in advance!
Edward

**Comment by ojw28** [comment]
What are you passing as the dataSource when you make your ExtractorSampleSource? You're either not passing the right thing, or you're not formatting your local URI correctly. Covering both points:

- Use DefaultUriDataSource, which will work for both local and network URIs
- Your URI should be formatted to start with file:///

**Comment by ojw28** [comment]
Note: DefaultUriDataSource no longer requires file:// (on the dev branch). If you omit a scheme completely, we'll assume file://.

**Comment by edikfuks** [comment]
Thank you very much!
