### ISSUE TITLE
ParserException: Multiple Segment elements not supported

### ISSUE THREAD

**Issue by nikedlab** [google/ExoPlayer#4671]
Hello!
What, actually mean "ParserException: Multiple Segment elements not supported"?
The task what I try to implement is abnormal, but I try to find solution.
The aim is video streaming from NDK to java code. The file with some.mkv plased on SD card, in c++ code I read file by blocks (2048) and this block passed to Java code via JNI call. On Java side I want to collect received bytes to buffer and play it with ExoPlayer. But I meet error "ParserException: Multiple Segment elements not supported" and don't understand where is root of my mistake.
Below my custom data source

```
class InputStreamDataSource: DataSource {

    private lateinit var inputStream: PipedInputStream
    private lateinit var outputStream: PipedOutputStream
    private var bytesRemaining: Long = 0
    private var opened = false

    override fun open(dataSpec: DataSpec?): Long {
        @NativeCall
        bytesRemaining = readVideoFile()
        outputStream = PipedOutputStream()
        inputStream = PipedInputStream()
        outputStream.connect(inputStream)
        return bytesRemaining
    }

    @NativeResponse
    fun videoReceiver(bytes: ByteArray) {
        println(">>>>>>>>>>>>>> videoReceiver: ${bytes.size}")
        try {
            outputStream.write(bytes)
        } catch (e: IOException) {
            println("InputStreamDataSource#videoReceiver error: ${e.message}")
        }
    }

    override fun getUri(): Uri? {
        return null
    }

    override fun close() {
        if (opened) {
            inputStream.close()
            outputStream.close()
            opened = false
        }
    }

    override fun read(buffer: ByteArray, offset: Int, readLength: Int): Int {
        if (readLength == 0) {
            return 0
        } else if (bytesRemaining == 0L) {
            return C.RESULT_END_OF_INPUT
        }

        val bytesToRead: Int = if (bytesRemaining == C.LENGTH_UNSET.toLong()) {
            readLength
        } else {
            (Math.min(bytesRemaining, readLength.toLong())).toInt()
        }

        var bytesRead = C.RESULT_END_OF_INPUT
        try {
            bytesRead = inputStream.read(buffer, offset, bytesToRead)
        } catch (e: IOException) {
            println("InputStreamDataSource#read error: ${e.message}")
        }

        if (bytesRead == C.RESULT_END_OF_INPUT) {
            if (bytesRemaining != C.LENGTH_UNSET.toLong()) {
                throw IOException(EOFException())
            }
            return C.RESULT_END_OF_INPUT
        }

        if (bytesRemaining != C.LENGTH_UNSET.toLong()) {
            bytesRemaining -= bytesRead
        }
        return bytesRead
    }

    companion object {
        init {
            System.loadLibrary("facade")
        }
    }

    @Native
    private external fun readVideoFile(file: String): Long

    @Native
    private external fun stopReadVideoFile()
}
``` 
Need your assistance. Maybe the way I go is completely wrong

**Comment by ojw28** [comment]
It means that ExoPlayer's Matroska extractor has seen multiple segment elements. This is a violation of the [Matroska spec](https://matroska.org/technical/specs/index.html), which says:

> A Matroska file is composed of 1 Segment.

The root problem is that you haven't implemented the `DataSource` interface correctly. In particular you're ignoring the `dataSpec` argument that's being passed to `open`, which contains, among other things, the offset into the data that the caller is asking to read.

More generally I'm confused by your approach. ExoPlayer can already play files on the sdcard directly simply by giving it a `file:///` uri to play. Why don't you just do that?

**Comment by nikedlab** [comment]
> Why don't you just do that?

Unfortunately it's not up to me.. C++ logic should make some actions with video stream. I cannot explain what because I not familiar with it. On my side I should only collect bytes and play them 

> The root problem is that you haven't implemented the DataSource interface correctly. 

Ok. But DataSource need URI and I have not it. 

After code modification video still not playing, only black screen
````
class InputStreamDataSource(filePath: String, private val listener: IDataSourceListener): DataSource {

    private var inputStream: PipedInputStream
    private var outputStream: PipedOutputStream
    private var opened = false
    private var fileLength: Long = 0
    private var bytesReaded: Long = 0

    init {
        @NativeCall
         readVideoFile(filePath)
        outputStream = PipedOutputStream()
        inputStream = PipedInputStream()
        outputStream.connect(inputStream)
    }

    override fun open(dataSpec: DataSpec): Long {
        try {
            val skipped = inputStream.skip(dataSpec.position)
            if (skipped < dataSpec.position) {
                throw EOFException()
            }
            fileLength = if (dataSpec.length >= 0) {
                dataSpec.length
            } else {
                inputStream.available().toLong()
            }
        } catch (e: IOException) {
            println("InputStreamDataSource#open: ${e.message}")
            throw DataSourceException(1)
        }

        opened = true
        return fileLength
    }

    @NativeResponse
    fun videoReceiver(bytes: ByteArray) {
        println(">>>>>>>>>>>>>> videoReceiver: ${bytes.size}")
        try {
            outputStream.write(bytes)
        } catch (e: IOException) {
            println("InputStreamDataSource#videoReceiver error: ${e.message}")
        }
        bytesReaded += bytes.size
        if (bytesReaded == 4096L) {
            listener.canStart()
        }
    }

    override fun getUri(): Uri? {
        return null
    }

    override fun close() {
//        if (opened) {
//            inputStream.close()
//            outputStream.close()
//            opened = false
//        }
    }

    override fun read(buffer: ByteArray, offset: Int, readLength: Int): Int {
        if (readLength == 0) {
            return 0
        } else if (bytesRemaining == 0L) {
            return C.RESULT_END_OF_INPUT
        }

        val bytesToRead: Int = if (bytesRemaining == C.LENGTH_UNSET.toLong()) {
            readLength
        } else {
            (Math.min(bytesRemaining, readLength.toLong())).toInt()
        }

        var bytesRead = C.RESULT_END_OF_INPUT
        try {
            bytesRead = inputStream.read(buffer, offset, bytesToRead)
        } catch (e: IOException) {
            println("InputStreamDataSource#read error: ${e.message}")
        }

        if (bytesRead == C.RESULT_END_OF_INPUT) {
            if (bytesRemaining != C.LENGTH_UNSET.toLong()) {
                throw IOException(EOFException())
            }
            return C.RESULT_END_OF_INPUT
        }

        if (bytesRemaining != C.LENGTH_UNSET.toLong()) {
            bytesRemaining -= bytesRead
        }
        return bytesRead
    }

    companion object {
        init {
            System.loadLibrary("facade")
        }
    }

    @Native
    private external fun readVideoFile(file: String): Long

    @Native
    private external fun stopReadVideoFile()
}

**Comment by ojw28** [comment]
> Unfortunately it's not up to me.. C++ logic should make some actions with video stream. I cannot explain what because I not familiar with it. On my side I should only collect bytes and play them

Hmm. You have a file path. If you have a file path, I don't really see why you can't just give that path to ExoPlayer in the form of a file uri.

That aside, the implementation still doesn't look correct. For example (but not limited to):

* Every call to `open` assumes that `inputStream` starts from the beginning of the file, however this is only true for the first call. If the `DataSource` is later re-opened to read from some position, I don't think the implementation will read the correct data, because it just skips forward from whatever position it happens to be in as a result of the previous read.
* `open` is supposed to return the number of bytes that can be read from the position at which it's opened, not the total length of the file.

It's not really in the scope of this issue tracker to debug custom code. It's really up to you to get your `DataSource` implementation to correctly adhere to the API. Note you can test it by comparing the return values and data read through it with what happens when you use `FileDataSource`. If it behaves differently then it's not doing the right thing.
