### ISSUE TITLE
Stuck in buffering state after the midroll ads finish playing

### ISSUE THREAD

**Issue by objectiveCarlo** [google/ExoPlayer#4681]
### Issue description
On Android 8.0 and above after the none skippable midroll ads completed playing the player will just buffer

### Reproduction steps
1. Scrub to the nearest midroll cue
2. If the ads is skippable it will work so try and try to get none skippable ads

### Version of ExoPlayer being used
ExoPlayer 2.8.4 and 2.8.1
First observed at 2.8.1
And tried to update at 

### Device(s) and version(s) of Android being used
Pixel 2 Android 9.0
Samsung Phone Android 8.0
Pixel 2 Android 8.0

This issue is reproducible in the sample app by using the following parameters:
I emailed it to: dev.exoplayer@gmail.com 
Thanks

**Comment by andrewlewis** [comment]
I think there may be a combination of two different issues here.

The first is that the this ad tag has two empty midroll ad breaks. Handling of those should be fixed on `dev-v2` (see #4030), so please could you try this out on that branch and see if that issue is fixed?

The second is that if I seek past the third midroll we don't seem to get any notification from IMA that the ad break is empty (I see `[ima.adslist.AdBreak] Destroying the ad break, 992` in IMA's debug logging but this doesn't seem to be surfaced via the public API). This may be an IMA bug or a problem with the ad tag.

It would help with both issues if you could depend on the development branch, set `ImaAdsLoader.DEBUG` to true and reproduce both issues so I can check we're seeing the same thing. Thanks!

**Comment by objectiveCarlo** [comment]
OK.

But when I tried dev-v2 Im getting this error:

`* What went wrong:
Could not resolve all files for configuration ':extension-ima:debugCompileClasspath'.
> Could not find play-services-ads.jar (com.google.android.gms:play-services-ads:15.0.1).
  Searched in the following locations:
      https://jcenter.bintray.com/com/google/android/gms/play-services-ads/15.0.1/play-services-ads-15.0.1.jar
`

**Comment by andrewlewis** [comment]
Do you have both `google()` and `jcenter()` listed in the repositories in your root project?

**Comment by asolis90** [comment]
I'm having a similar issue in which if pre-roll is empty and first mid-roll from adgroup is empty it skips the preroll correctly but whenever it gets to the midroll it just gets stuck into a buffering state. Tried with dev-v2 and release-v2 branch with the latest version being 2.8.4 and it didn't seemed to be fixed.

**Comment by objectiveCarlo** [comment]
Also not working for me.

**Comment by CipherGit** [comment]
I've also encountered the issue with the dev-v2 branch and I've set `ImaAdsLoader.DEBUG` to true. Here's the relevant logs:

> 08-21 14:14:43.893 14210-14210/com.google.android.exoplayer2.imademo D/ImaAdsLoader: onAdEvent: LOADED
08-21 14:14:43.894 14210-14210/com.google.android.exoplayer2.imademo D/ImaAdsLoader: Loaded ad 1 of 2 in group 1
08-21 14:14:43.927 14210-14210/com.google.android.exoplayer2.imademo D/ImaAdsLoader: onAdEvent: LOG
08-21 14:14:43.927 14210-14210/com.google.android.exoplayer2.imademo I/ImaAdsLoader: AdEvent: {errorMessage=Linear assets were found in the VAST ad response, but none of them matched the video player's capabilities., errorCode=403, type=adPlayError}
08-21 14:14:43.942 14210-14210/com.google.android.exoplayer2.imademo D/ImaAdsLoader: onAdEvent: LOADED
08-21 14:14:43.943 14210-14210/com.google.android.exoplayer2.imademo D/ImaAdsLoader: Loaded ad 2 of 2 in group 1
08-21 14:14:43.967 14210-14210/com.google.android.exoplayer2.imademo D/ImaAdsLoader: loadAd in ad group 1
08-21 14:14:43.976 14210-14210/com.google.android.exoplayer2.imademo D/ImaAdsLoader: onAdEvent: CONTENT_PAUSE_REQUESTED
08-21 14:14:43.990 14210-14210/com.google.android.exoplayer2.imademo D/ImaAdsLoader: playAd
08-21 14:14:45.291 14210-14210/com.google.android.exoplayer2.imademo D/ImaAdsLoader: onAdEvent: STARTED
08-21 14:14:49.085 14210-14210/com.google.android.exoplayer2.imademo D/ImaAdsLoader: onAdEvent: FIRST_QUARTILE
08-21 14:14:52.731 14210-14210/com.google.android.exoplayer2.imademo D/ImaAdsLoader: onAdEvent: MIDPOINT
08-21 14:14:56.581 14210-14210/com.google.android.exoplayer2.imademo D/ImaAdsLoader: onAdEvent: THIRD_QUARTILE

**Comment by andrewlewis** [comment]
@asolis90, @CipherGit Please could you send the ad tags and full logcat after reproducing the issue with `ImaAdsLoader.DEBUG` set to true to dev.exoplayer@gmail.com with subject "Issue #4681"? If you're using dev-v2 there should be some logging from chromium when you do that, so I don't think the logs in the previous comment are complete. In my testing I found that the issue with getting stuck buffering when reaching a midroll after an empty ad break was fixed, but it sounds like this is still reproducible. It would be great if you could provide some more information so I can diagnose this. Thanks.

**Comment by andrewlewis** [comment]
I've got a possible fix for these issues (please see the update on #4622) but the ad tag provided via email seems to have only empty ad breaks. Is that expected? Thanks.

**Comment by objectiveCarlo** [comment]
We will send you another ad tag. Because I think the ads already expired on our side.

**Comment by objectiveCarlo** [comment]
If we remove the empty ad break will it work?

**Comment by andrewlewis** [comment]
An ad tag without empty ad breaks shouldn't exhibit this issue.

**Comment by andrewlewis** [comment]
@objectiveCarlo, @asolis90, @CipherGit This should be fixed on the dev-v2 branch. Please could you try it out and let us know if you see any issues? Thanks.

**Comment by objectiveCarlo** [comment]
Right now we don't have the same ad tags anymore cause I think our backend guys did some tweaking. Ill try to get a sample ad tag from them and let you know. Thank you!

**Comment by andrewlewis** [comment]
Closing as playback of ad tags with empty ad groups is now working for the various test ad tags I've tried. There is a remaining issue with playback of ad tags where some ads within a non-empty ad group are empty: #5006.
