### ISSUE TITLE
widevine offline but playback failed with no internet

### ISSUE THREAD

**Issue by mical892524** [google/ExoPlayer#4682]
### Issue description
I follow the erdemguven's https://gist.github.com/erdemguven/8c5fb4d87f084456c81245f553ba3a2f in exoplayer demo app. when I download the dash success, it can play success but playback fail with no internet.  why the widevine offline can not play without internet?  I have see more exoplayer issues about widevine offline play, but these can not help me.

### test content
test dash sample:
{
        "name": "Widevine test",
        "uri": "https://storage.googleapis.com/exoplayer-test-media-1/gen-4/screens/dash-vod-single-segment/manifest-h264-enc.mpd",
        "drm_scheme": "widevine",
        "drm_license_url": "https://proxy.uat.widevine.com/proxy?provider=widevine_test&video_id=exoplayer_test_1"
}

### Version of ExoPlayer being used
2.8.4

### Device(s) and version(s) of Android being used
device: huawei honor v9
android version: 8.0

device: sumsang tablet
android version: 7.0

**Comment by erdemguven** [comment]
I think it doesn't play because of the license duration is too short. If you try a different widevine sample it works.

**Comment by mical892524** [comment]
I have try other samples, it can works now. thank you.
