### ISSUE TITLE
Using same instance of exoplayer, makes the UI controller to be invisible.

### ISSUE THREAD

**Issue by ritwik1994** [google/ExoPlayer#4684]
Hi,
I am creating the instance of SimpleExoPlayer and setting it in customPlayerView. I am making setControllerHideOnTouch(false) so that the controller does not get closed. After that when i call setPlayWhenReady(true) it starts to play. 
Problem arises when i go to another activity and set the same exoplayer instance into other playerview. Controller becomes black and when I Touches it again then the player is seen. Problem only arises when I click on play on first activity and wanted to continue in other activity. The song continues but the player controller turns black. Problem does not arrives when i Pressed pause state.

**Comment by ojw28** [comment]
This doesn't sound like an ExoPlayer issue, but without proper reproduction steps there's not much we can do to look at it / check. Please provide reproduction steps. Probably in the form of a small GitHub project that reproduces the issue.

**Comment by ojw28** [comment]
Closing due to lack of information. If you can provide the required information please respond with it here, and we'll re-open the issue. Thanks!
