### ISSUE TITLE
How to listen event of AdsMediaSource

### ISSUE THREAD

**Issue by symphonicz** [google/ExoPlayer#4685]
Hi, I have problem

I use exoplayer with ima extension and add **AdsMediaSource.EventListener()** to **EventListener** in **AdsMediaSource()** to Tracking state of **Ads** like this

                mediaSource = new AdsMediaSource(buildMediaSource(Uri.parse(data.file())), new AdsMediaSource.MediaSourceFactory() {
                @Override
                public MediaSource createMediaSource(Uri uri, @Nullable Handler handler, @Nullable MediaSourceEventListener listener) {
                    return buildMediaSource(uri);
                }

                @Override
                public int[] getSupportedTypes() {
                    return new int[]{C.TYPE_DASH, C.TYPE_HLS, C.TYPE_OTHER};
                }
            }, imaAdsLoader, playerView.getOverlayFrameLayout(), null, new AdsMediaSource.EventListener() {
                @Override
                public void onAdLoadError(IOException error) {
                    Log.e(TAG, "onAdLoadError: " + error.getMessage());
                }

                @Override
                public void onInternalAdLoadError(RuntimeException error) {
                    Log.e(TAG, "onInternalAdLoadError: " + error.getMessage());
                }

                @Override
                public void onAdClicked() {
                    Log.e(TAG, "onAdClicked");
                }

                @Override
                public void onAdTapped() {

                    Log.e(TAG, "onAdTapped");
                }

                @Override
                public void onLoadStarted(DataSpec dataSpec, int dataType, int trackType, Format trackFormat, int trackSelectionReason, Object trackSelectionData, long mediaStartTimeMs, long mediaEndTimeMs, long elapsedRealtimeMs) {

                    Log.e(TAG, "onLoadStarted");
                }

                @Override
                public void onLoadCompleted(DataSpec dataSpec, int dataType, int trackType, Format trackFormat, int trackSelectionReason, Object trackSelectionData, long mediaStartTimeMs, long mediaEndTimeMs, long elapsedRealtimeMs, long loadDurationMs, long bytesLoaded) {

                    Log.e(TAG, "onLoadCompleted");
                }

                @Override
                public void onLoadCanceled(DataSpec dataSpec, int dataType, int trackType, Format trackFormat, int trackSelectionReason, Object trackSelectionData, long mediaStartTimeMs, long mediaEndTimeMs, long elapsedRealtimeMs, long loadDurationMs, long bytesLoaded) {

                    Log.e(TAG, "onLoadCanceled");
                }

                @Override
                public void onLoadError(DataSpec dataSpec, int dataType, int trackType, Format trackFormat, int trackSelectionReason, Object trackSelectionData, long mediaStartTimeMs, long mediaEndTimeMs, long elapsedRealtimeMs, long loadDurationMs, long bytesLoaded, IOException error, boolean wasCanceled) {

                    Log.e(TAG, "onLoadError");
                }

                @Override
                public void onUpstreamDiscarded(int trackType, long mediaStartTimeMs, long mediaEndTimeMs) {

                    Log.e(TAG, "onUpstreamDiscarded");
                }

                @Override
                public void onDownstreamFormatChanged(int trackType, Format trackFormat, int trackSelectionReason, Object trackSelectionData, long mediaTimeMs) {

                    Log.e(TAG, "onDownstreamFormatChanged");
                }
            });`

but nothing to appear on console log

What should i do to handle callback from ads

i want to track ads like this

ADS_START
ADS_SKIPPED
ADS_COMPLETE
ADS_ERROR

help me pls.

**Comment by ojw28** [comment]
You need to pass a non-null `Handler` as the 5th argument to the `AdsMediaSource` constructor. You're currently passing `null`.

Note that the constructor you're calling is also deprecated, although this depends on whether you're using a recent version or not. If you are using a recent version, instructions on what to do instead can be found [here](https://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/source/ads/AdsMediaSource.html#AdsMediaSource-com.google.android.exoplayer2.source.MediaSource-com.google.android.exoplayer2.source.ads.AdsMediaSource.MediaSourceFactory-com.google.android.exoplayer2.source.ads.AdsLoader-android.view.ViewGroup-android.os.Handler-com.google.android.exoplayer2.source.ads.AdsMediaSource.EventListener-).

**Comment by symphonicz** [comment]
Thank for reply.

I use exoplayer version 2.8.4 now. But i dont know how to implement listener to callback ads.

Could you explain me how to implement it

**Comment by ojw28** [comment]
I've already explained what you're doing wrong right above (i.e. pass a valid handler, not null). You should then follow the instructions I linked to to move away from the deprecated methods, but you can do that as a separate step.
