### ISSUE TITLE
Bugs in exoplayer version 2.8.4

### ISSUE THREAD

**Issue by hafiz013** [google/ExoPlayer#4687]
Hi there, if found the bugs when i want to play video ads locally from phone file instead of ima  as shown in code below 
`mediaSourceWithAds =
                new AdsMediaSource(mVideoSource,
                        dataSourceFactory, new AdsLoader() {
                    @Override
                    public void setSupportedContentTypes(int... contentTypes) {

                    }

                    @Override
                    public void attachPlayer(ExoPlayer player, EventListener eventListener, ViewGroup adUiViewGroup) {
                        Log.e("videAds", "yeah");
                        ///storage/emulated/0/AdsFolder/mcd.mp4

                        //addgroup.count, 30 * C.MICROS_PER_SECOND
                        //addgroup = new AdPlaybackState.AdGroup();
                        adPlaybackState = new AdPlaybackState(10 * C.MICROS_PER_SECOND);

                        for (int i = 0; i < listOfFiles.length; i++) {
                            Log.e("file:", pathVideo+"/"+listOfFiles[i].getName());
                            if (listOfFiles[i].isFile()) {
                               // addgroup.withAdUri(Uri.parse(pathAds+"/"+listOfFiles[i].getName()), i);
                            fileadstring = pathAds+"/"+listOfFiles[i].getName();
                            }
                        }
                        adPlaybackState = adPlaybackState.withAdUri(0, 0, Uri.parse(fileadstring));
                       // adPlaybackState = adPlaybackState.withAdUri(0, 0, Uri.parse(pathAds+"/"+listOfFiles[i].getName()));
                        eventListener.onAdPlaybackState(adPlaybackState);

                        player.addListener(ViewVideo.this);
                    }

                    @Override
                    public void detachPlayer() {

                    }

                    @Override
                    public void release() {

                    }

                    @Override
                    public void handlePrepareError(int adGroupIndex, int adIndexInAdGroup, IOException e) {
                        Log.e("handlePrepareError", e.toString());
                    }
                }, videoView.getOverlayFrameLayout());`

` exoPlayer.prepare(mediaSourceWithAds);
        //exoPlayer.setPlayWhenReady(true);
        videoView.setPlayer(exoPlayer);`
when reach at 10 second content video play then video stop play and ads not display.

**Comment by hafiz013** [comment]
![whatsapp image 2018-08-20 at 6 02 59 pm](https://user-images.githubusercontent.com/6707224/44334158-5c4d6280-a4a3-11e8-8544-889a4cd220af.jpeg)

**Comment by ojw28** [comment]
This appears to be under discussion already in https://github.com/google/ExoPlayer/issues/4680. Please don't file multiple issues for the same thing. Thanks!

**Comment by hafiz013** [comment]
@ojw28 the comment from myself but still not working coding that i post.
