### ISSUE TITLE
Don't want Retry when Load Error

### ISSUE THREAD

**Issue by ZINK-FU** [google/ExoPlayer#4689]
Don't want Retry when Load Error，But i can‘t found a method to do this

**Comment by AquilesCanta** [comment]
Please have a look at the [LoadErrorHandlingPolicy](https://github.com/google/ExoPlayer/tree/dev-v2/library/core/src/main/java/com/google/android/exoplayer2/upstream) on the dev branch. You can provide your own implementation to whichever MediaSource you are using. Please give it a try and let us know if it works for you.

**Comment by ZINK-FU** [comment]
```java
    @Override
    public long getRetryDelayMsFor(
            int dataType, long loadDurationMs, IOException exception, int errorCount) {
        if (exception instanceof HttpDataSource.InvalidResponseCodeException) {
            HttpDataSource.InvalidResponseCodeException exc = (HttpDataSource.InvalidResponseCodeException) exception;
            if (exc.responseCode == 403) {
                return C.TIME_UNSET;
            }
        }

        return exception instanceof ParserException
                ? C.TIME_UNSET
                : Math.min((errorCount - 1) * 1000, 5000);
    }
```
it works for me, thank you @AquilesCanta

**Comment by AquilesCanta** [comment]
Glad to hear that.
