### ISSUE TITLE
Question: get notified when ExoPlayer is buffering

### ISSUE THREAD

**Issue by arazabishov** [google/ExoPlayer#4691]
I was wondering if there is a callback or a listener which can help tracking when ExoPlayer starts / ends buffering? I.e. has anything changed since this answer: https://github.com/google/ExoPlayer/issues/815

**Comment by ojw28** [comment]
What does "start / end buffering" mean to you, exactly? Do you mean user visible buffering (e.g. so you can show / hide a buffering spinner), or are you interested in when the player actually starts / stops filling its buffer internally (which is not typically user visible)?

**Comment by arazabishov** [comment]
To be more precise, we have to use cases for measuring playback performance (analytics):
 - To check how long it takes from starting to buffer until we can start playing.
 - To check when buffer underrun occurs and when it ends.

I guess, it could be nice to generalize both of those use cases and just provide a listener which gives  size of the buffer and position of player within it (what is being played now). Maybe having a status flag which says whether buffering is happening at the moment or not. It should be enough (based on my limited knowledge of all possible use cases of exoplayer) :)

**Comment by ojw28** [comment]
We already provide ways of getting all of this information. You should implement `AnalyticsListener` and override methods corresponding to the events you're interested in. For example:

* `onLoadingChanged` - Tells you when the player starts and stops loading data internally.
* `onPlayerStateChanged` - Tells you when a user visible change in state occurs, including transitioning to/from the user visible buffering state.

Then call `SimpleExoPlayer.addAnalyticsListener` to register your implementation to receive events. You can also just query the player directly (e.g. to get the buffered duration) if you want to determine the current state.

**Comment by arazabishov** [comment]
Thanks!
