### ISSUE TITLE
Does onTracksChanged gets called when video track changes due to ABR ?

### ISSUE THREAD

**Issue by sravan1213** [google/ExoPlayer#4692]
onTracksChanged is not getting called when video changes due to ABR. I tried getting updated track using `getCurrentTrackSelections`, but it is not returning updated list.

`player.getVideoFormat()` is giving right format selected, but has incorrect values about bitrate.
example -  getting bitrate as -1, track id is wrong.

What is the best way to get notified and get all track related info when video track changes.

**Comment by ojw28** [comment]
`onTracksChanged` only gets called when the available tracks change, not when the adaptive selection changes. You should use `getVideoFormat`. You can also register an `AnalyticsListener` that overrides `onDecoderInputFormatChanged` to be notified when a change occurs.

You should see the bitrate and track id set correctly for DASH and SmoothStreaming adaptive playbacks. HLS we made some recent improvements in how this information is propagated, so you may have to try the `dev-v2` branch and/or wait for the 2.9.x release. Please give that a try and let us know if you're still not seeing the data you expect.

**Comment by tonihei** [comment]
Just to add to this, you may prefer to use `onVideoSizeChanged` which gives the selected video format specifically. That makes a difference if using HLS and `onDecoderInputFormatChanged` has a muxed audio and video format.

**Comment by sravan1213** [comment]
@ojw28 @tonihei thanks for the help.
It is working as expected in `dev-v2` for both HLS and DASH streams.
