### ISSUE TITLE
Enhancement for managing cache files (sub cache)

### ISSUE THREAD

**Issue by workspace** [google/ExoPlayer#4694]
I received a lot of feedbacks from my service's users about managing downloaded files. They had a problem with deleting cache. I investigated status and behaviors of their devices and found some reasons.
First, all chunks are saved in the same folder, so ExoPlayer's implementation is deleting them one by one. In my case, 50 minutes video includes 3000 video/audio chunks. For example, if I delete it, 3000 File I/O tasks will be executed and it takes very long time(about several minutes). If there are downloading/deleting task, tasks compete for using file I/O for the same folder. 

So, I suggest sub cache to manage caches. If I want to delete some video's cache, It can be achieved by deleting folder which video's cache uses. Also, there are not competition for using file I/O. In conclusion I think implementing sub cache will brings a lot of performance enhancement in ExoPlayer's cache.
Similar discussions are in #4253 . Thank you!

**Comment by erdemguven** [comment]
This issue is tracked in #4253. Please don't create new issues.
