### ISSUE TITLE
How to display the same video in multiple TextureView?

### ISSUE THREAD

**Issue by ttm-hoangcm** [google/ExoPlayer#4695]
I'm newbie in android & ExoPlayer. Is there have any example? Thanks a lot.

**Comment by ttm-hoangcm** [comment]
Any clues? Or its impossible?

**Comment by vipulim** [comment]
There is no direct way of doing this.
You can follow @ojw28 instruction from [this](https://github.com/google/ExoPlayer/issues/2855#issuecomment-303465454) issue.

Basically you need to create your custom `RenderersFactory `and `TrackSelector  `and using `MergingMediaSource `you can achieve this.

**Comment by tonihei** [comment]
Closing, because the linked issue answers the question.
