### ISSUE TITLE
Question: is it possible to have a special in&out animation when choosing to loop a video?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [google/ExoPlayer#4699]
Suppose I wish to loop a video file. I use this:

`player!!.repeatMode = Player.REPEAT_MODE_ALL`

But, sometimes the input video isn't meant to be loop-able, so we would like to have some kind of in&out animation for when about to end the current video playback and starting of the next (even though both are the exact same video file).

Is it possible? Maybe it's even possible between different videos?

Or should I have a ViewAnimator of 2 PlayerView instances? Thing is that I don't think it would be efficient using 2 PlayerView instances, and it might have issues of syncing between them.

**Comment by ojw28** [comment]
This is not something we support directly, sorry.

As already stated [here](https://github.com/google/ExoPlayer/issues/4652#issuecomment-414152075), it's probably possible to cross-fade video, but how to do this is beyond the scope of this issue tracker, and isn't something we officially support. Also, I agree that synchronization might be challenging. Good luck!

**Comment by AndroidDeveloperLB** [comment]
Yes, cross-fade is probably the name for this effect, and might be the best one for this case.
Can you please add this feature though?
You've marked it as "self-assigned" and even "enhancement  question", but it's also marked as "closed"...

 It could even be nice for audio loop or switching to other files.

**Comment by ojw28** [comment]
Support for cross-fade is tracked by https://github.com/google/ExoPlayer/issues/3438. That issue is more in the context of audio, but most likely the changes required are common enough that they should be treated together. Note this is not a high priority issue for us, and we're unlikely to add support any time soon.
