### ISSUE TITLE
Is there a function for reloading the cache information to refresh?

### ISSUE THREAD

**Issue by qeadsw** [google/ExoPlayer#4704]
When the cached information is loaded, the cached file is deleted for reasons such as cleaning up the garbage file, which means the cached information does not change.
Is there any way to redo it? I have read some source code and found that the function SimpleCache. Initialize () is not exposed.

**Comment by erdemguven** [comment]
SimpleCache updates itself automatically when it finds out a file is deleted. The only way to do it manually is releasing the cache instance and creating a new one.
