### ISSUE TITLE
Question: Exoplayer instance for video playback (and background audio) in Foreground service?

### ISSUE THREAD

**Issue by ursusursus** [google/ExoPlayer#4706]
Hi,
I have used ExoPlayer before to play audio with background playback supported, meaning architecture was rather simple -> foreground service within which sat ExoPlayer instance.

_Now Id like to add video playback._ and audio should still continue to play while in background

**Is such architecture still viable when PlayerView.setPlayer wants the ExoPlayer instance directly?** 
I noticed Surface is Parcelable but newVideoComponent.setVideoTextureView((TextureView) surfaceView) wants the actual view and then extracts the surface from that.

So my question is: What is the recommended architecture for such (video only fg, audio fg and bg) playback? Should I just have a "empty" foreground service along side this to just keep app from getting killed in the background? Or is there a way to make it work via intents (parcelable arguments) to that given service, which would hold the reference to the player?

Thanks!

**Comment by ojw28** [comment]
> Is such architecture still viable when PlayerView.setPlayer wants the ExoPlayer instance directly?

Yes.

> So my question is: What is the recommended architecture for such (video only fg, audio fg and bg) playback? Should I just have a "empty" foreground service along side this to just keep app from getting killed in the background?

Assuming your service is in the same process, I'd recommend avoiding having to parcel everything. One simple solution is just to make the player static in the foreground service, and provide a static accessor to allow activities to get hold of it.

It is possible to put the service in a different process and do everything through intents / binding, but in that case I think you'd need to implement your own UI components, `setVideoSurface` directly on the player, and come up with a way of parceling player state.
