### ISSUE TITLE
How to know when an audio track added with ConcatenatingMediaSource has finished playing

### ISSUE THREAD

**Issue by esecoder** [google/ExoPlayer#4707]
So I have created the an audio player and added the media sources as ConcatenatingMediaSource, but it seems to play in succession without my control, but yet doesn't seem to send event reports especially when a track ends. Which I need to know so I can update the UI accordingly. Please how do I get to know when a track has finished playing when using ConcatenatingMediaSource.

MediaSource mediaSources[] = new MediaSource[playListSongs.length];
        int i = 0;
        while (i < playListSongs.length) {
            MediaSource mediaSource = new ExtractorMediaSource.Factory(dataSourceFactory)
                    .createMediaSource(Uri.parse(playListSongs[i].getSongFile()),
                            new PlayerHandler(),
                            this);
            mediaSources[i] = (mediaSource);
            i++;
        }

        if (mExoPlayer != null) {
            mExoPlayer.addListener(this);
            mExoPlayer.prepare(new ConcatenatingMediaSource(mediaSources));
            mExoPlayer.setPlayWhenReady(true);

**Comment by ojw28** [comment]
`EventListener.onPositionDiscontinuity` will be called with `DISCONTINUITY_REASON_PERIOD_TRANSITION` when playback transitions from one piece of media to the next. You can use `Player.getCurrentWindowIndex` and `Player.getCurrentTag` to query which piece of media is currently playing. Note that you can set tags on each piece of media when building the `ExtractorMediaSource` instances, by calling `ExtractorMediaSource.Factory.setTag`.

**Comment by BrainCrumbz** [comment]
Sorry to detour this issue, it might be somehow related though: is there an API to get the tag associated to a given `MediaSource`? After its creation, I mean. Something like `MediaSource#getTag()`.

We had a look at the docs but could not find any. Thanks

**Comment by tonihei** [comment]
That's currently not supported because of the way our MediaSources are designed. See [this comment](https://github.com/google/ExoPlayer/issues/4693#issuecomment-414377097).

**Comment by BrainCrumbz** [comment]
Thanks for reply. Just wondering: isn't tag Object stored somewhere inside the MediaSource, right after source is created (and thus before being added to a playlist or directly *prepare*-d on a player)?

**Comment by tonihei** [comment]
It is, but we could only add such a method for particular media source implementations which support it, not to the MediaSource interface.

**Comment by BrainCrumbz** [comment]
Could you share which is that implementation? So maybe we can try a cast and if positive, extract the tag from that?

**Comment by tonihei** [comment]
This is getting slightly off-topic :) 
Can you open a new issue explaining what you'd like to achieve and why you need to get the tag back from the media source? Maybe there is a better way to support that.
