### ISSUE TITLE
AdsMediaSource: can adUiViewGroup be on-demand instead of final/fixed?

### ISSUE THREAD

**Issue by eneim** [google/ExoPlayer#4708]
This is a question, also be a feature request if it fits the context.

Consider the following scenario: I have a PlayerView playing ads, the App is in portrait orientation. User rotates the App, and this App allows the landscape orientation. The implementation doesn't use the "configChange" in manifest, so the Activity will be recreated, making its Views are re-inflated as well.

Because AdsMediaSource requires a final adUiViewGroup, to make the Video/PlayerView play again, I need to: [1] Cache the current position of Player, AdsMediaSource, [2] in onCreated of the Activity, re-create the AdsMediaSource, prepare it again with the saved playback position, and finally start it again.

This will result in a gap in playback (so not smooth UX), and I don't know if the AdsLoader will correctly start the Ads from where it stops in previous Activity's lifecycle.

I see that the ```AdDisplayContainer``` from IMA use the Ads ViewGroup dynamically, can we bring this to AdsMediaSource?

Thanks in advance.

**Comment by andrewlewis** [comment]
When the activity is recreated there will be a new surface view for video decoder output so I don't think the UX is going to be completely smooth everywhere anyway (unless you handle the configuration change yourself), but resetting the player will introduce a longer pause so we should try to fix this.

One part I'm not sure about yet is how to get IMA to start using the new view group, and whether this is possible without making a new ads request, which would reset information about what ads have been played.

**Comment by eneim** [comment]
@andrewlewis As the surface will eventually be recreated, Video stream will definitely be interrupted. But at least Audio can be kept playing during the transition. Lately I observe the same from YouTube App. If I keep the Player playing during the transition, once the new Surface is created, it will be immediately fed by new frames, which reduces the gap of playback.

After investigating the source code of IMA (obfuscated everywhere ...), I figure out that the ViewGroup may not as flexible as I thought. The ViewGroup is used to place a WebView on top of it, so once set, and ad is requested, it should stay there for a while. 

If we recreate the Activity, the WebView and all other ads-related resource will also be refreshed and the Ad will start all over again (which is by intend I think).

Though, the ability to reuse the AdsMediaSource and just replacing the ViewGroup at runtime will be beautiful. It is fine to close this, but I still expect it to be possible :D. (If I can have a voice to IMA dev, I would definitely request for a dynamic AdDisplayContainer).

**Comment by andrewlewis** [comment]
Revisiting this, I don't think this going to be feasible in the IMA model as all state relating to ad playback will be thrown away when the `WebView` gets destroyed, and I think there are no plans to change how this works. IMA has a feature called manual ad playback where the app controls whether each ad group is played, but AFAIK this can't be used in conjunction with preloading.

I'll therefore close this as infeasible. The best option is probably to handle configuration changes yourself.
