### ISSUE TITLE
How to use DownloadManager with multi directories 

### ISSUE THREAD

**Issue by morkovkin** [google/ExoPlayer#4709]
Hello! How i can use DownloadManager with multi directories ? For example i try download 2 hls media files (using queues from manager) to different directories. I would like to make a directory like this - 

Downloads
-- mediafiles1
---- cached_content_index1
-- mediafiles2
---- cached_content_index2
-- ...
-- mediafilesN
---- cached_content_indexN
-- actions
-- tracked_actions

I use DownloadManager like in example. But i can't found resolution to change cache from DownloaderConstructorHelper and don't recreate  DownloadManager. When i try to recreate new one new manager just lost download queues. My sqlite save states and local directories for media content. In theory i wanna play offline content just put offline media directory in cacheFactory and so on 

 Сould you give an example how can this be done?  Thanks!

**Comment by erdemguven** [comment]
Currently this isn't supported. #4253 tracks this feature request.
