### ISSUE TITLE
Multiple post roll Ads not played properly using Exoplayer v 2.8.4 & IMA SDK v3.9.4

### ISSUE THREAD

**Issue by psiddaraj** [google/ExoPlayer#4710]
We are  testing multiple pre, mid & post roll Ads using Exoplayer 2.8.4 & IMA SDK v 3.9.4

Reproduction Steps:
1. Load the Exoplayer with VMAP configuration with multiple ore, post & mid roll Ads using an Ad Tag URI 
2. Exoplayer plays pre & mid roll Ads without any issues.
3. Exoplayer UI is stuck after first post-roll Ad is played & doesn't switch to the next post roll Ad. 

This issue is always reproducible. 
VMAP & Video of the logs are sent to Exoplayer team via mail.

**Comment by andrewlewis** [comment]
@psiddaraj This should be fixed on the dev-v2 branch. Please could you try it out and let us know if you see any issues? Thanks.

**Comment by psiddaraj** [comment]
Thanks @andrewlewis. The issue is fixed dev-v2 branch. Could you please let me know, when this patch or fix would be available in release branch ?

**Comment by andrewlewis** [comment]
It will probably be in 2.9.0, but we don't have a solid ETA for that yet.
