### ISSUE TITLE
Is it possible to get Dash stream sizes before starting a download?

### ISSUE THREAD

**Issue by danha306** [google/ExoPlayer#4714]
We are developing an app that among other things lets users download (Widevine-protected) Dash content to their devices for later playback offline. Since our video assets can reach a considerable  size we would like to prompt the user with the file sizes for each representation before starting a download, so the user can select the appropriate representation to download. The use case is as follows:

> The user wants to download a video for later playback. They press the download button and is prompted with a selection dialog, where the different resolutions and their respective file size is displayed. The user decides that the highest available resolution takes up too much space, and selects the second highest resolution which is then downloaded to the device.

We have been able to get other information from the manifest such as resolution and bitrate, but not video duration or file size. If we knew the former we could (roughly) calculate the latter, but we have been unable to extract any of these two before starting the download. Is there a way to do this that we have missed and if that's not the case, are there plans to implement functionality like this in the future?

**Comment by erdemguven** [comment]
There is a code in DashDownloader which calculates the whole download size using manifest only (If the segment sizes are defined in it). The code is only called when the download is started but we can make it accessible without downloading. Still it would work only if manifest has the necessary information.

Also DashManifest.durationMs contains the total duration of the video but again only if the it's defined in the manifest.

**Comment by ojw28** [comment]
`DashManifest.durationMs` combined with the representation bitrates seems sufficient for this use case. Closing on this basis, but please feel free to comment or clarify if you're still stuck!
