### ISSUE TITLE
Add support for forwarding / rewinding single frames

### ISSUE THREAD

**Issue by ened** [google/ExoPlayer#4716]
This feature request is for seeking by single video frames.

The user would play a recording & put the player in a paused state once a particular moment has been reached. Then they would repeatedly tap a `previous frame`, `next frame` until the target frame has been reached.

PS: Is this something which can already be done using the seekTo API (given the correct math for the FPS / ms calculation)?

**Comment by ffdez** [comment]
Up! I also need this behavior.

**Comment by ojw28** [comment]
We don't have any near-term plans to support this functionality.
