### ISSUE TITLE
Add "open" button to Example App

### ISSUE THREAD

**Issue by ened** [google/ExoPlayer#4717]
For non-adb connected use cases (in which we can use intents), it would be nice if the example app could have a little "open" button to find a file on the phone storage and play it.

https://developer.android.com/guide/topics/providers/document-provider 

I will get to it later, unless someone would like to pick this up.

**Comment by ojw28** [comment]
I think we really don't want to add any extra complexity into the demo app. It's already too complicated.

**Comment by ened** [comment]
Understand your concern about growing complexity, however I would like to note that from "quick test" use case point of view it's rather limiting because:
- Other apps can't simply feed data into the demo app (intent filter)
- No way to place demo files on dedicated SD card folder
- List of media in demo app is fixed

**Comment by ojw28** [comment]
Could you elaborate on what the actual use case is. Who is the user, and what are they trying to test?

Note that the demo app can receive media specified via intent if you describe it in the form of a `exolist.json` file, as documented [here](https://google.github.io/ExoPlayer/demo-application.html). This enables use cases like content providers wanting to load a list of their test media into the demo app.

**Comment by ened** [comment]
Noted the demo app is already flexible to play arbitrary media. 

Say a user wants to open files from his SD card, or other sources like files stored in other directories or within apps like Dropbox, then they would be required to write a second app. That app does nothing but show the file provider ui as documented in the OP, receive the URI and construct the media json and forward that to the demo app.

Possible, but for that usecase highly inconvenient. I think the demo app can do that inline, most hard work is already done by the framework anyway.

My point is that the demo app is installed at time A (using `adb`), but you want might want to check sample files on the go, without pc tethering. Happens to me at least all the time. And I would like to give the demo app to customers to test on their phones.

How about I prepare a PR and you can take a look & decide.

**Comment by ojw28** [comment]
The demo app isn't intended to distribute to end users. It doesn't even have translations (i.e. only works in English), and we don't want to provide end user support for it. If you want to create a simple demo app, I'd suggest you fork it, make it a bit more user friendly, and distribute that instead.

It's still somewhat unclear to me what the use case is. I can understand developers wanting to use the demo app for testing, but I don't understand why it would make sense to distribute it to end users.

**Comment by ened** [comment]
I'll go with the separate app approach. Easier. 👍
