### ISSUE TITLE
BehindLiveVideoException while playing the HLS video url

### ISSUE THREAD

**Issue by gerahimanshu** [google/ExoPlayer#4723]
Hi, 
I am trying to play an HLS video url and able to play it for a few seconds and then getting the following error:
```
com.google.android.exoplayer2.source.BehindLiveWindowException
        at com.google.android.exoplayer2.source.hls.HlsChunkSource.getNextChunk(HlsChunkSource.java:290)
        at com.google.android.exoplayer2.source.hls.HlsSampleStreamWrapper.continueLoading(HlsSampleStreamWrapper.java:539)
        at com.google.android.exoplayer2.source.CompositeSequenceableLoader.continueLoading(CompositeSequenceableLoader.java:78)
        at com.google.android.exoplayer2.source.hls.HlsMediaPeriod.continueLoading(HlsMediaPeriod.java:224)
        at com.google.android.exoplayer2.MediaPeriodHolder.continueLoading(MediaPeriodHolder.java:157)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.maybeContinueLoading(ExoPlayerImplInternal.java:1542)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleContinueLoadingRequested(ExoPlayerImplInternal.java:1525)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:322)
        at android.os.Handler.dispatchMessage(Handler.java:104)
        at android.os.Looper.loop(Looper.java:166)
        at android.os.HandlerThread.run(HandlerThread.java:65)
```
Please Help!

**Comment by ojw28** [comment]
`BehindLiveVideoException` is fairly well documented on this issue tracker and elsewhere. Have you tried searching existing issues, and if so why do they not answer your question (i.e. what is specifically different about your case)?

If you believe there's something different, then you need to properly full out the issue template for us to look at this.

**Comment by lricardo** [comment]
I have this problem with a stream from a CDN (akamai) with versions 2.8.0 and 2.9.0. Normally, the stream would play without further problem in 8 minutes (on Nexus 5X, API 27), meanwhile in other devices such as P20 and OnePlus 5T achieved 12 minutes until that error.

After a few days trying possible solutions that I found in the issue tracker, I decided to add the version release-v2 (at the date, with fa9d7d5e3eb1a0bf5362d5c80b0c5b33a8b6151b) to the android project as a gradle module (git clone and etc). It almost fixes my problem (the playback continues for more than 40 minutes).

**Comment by AquilesCanta** [comment]
Just in case this is not clear: BehindLiveWindowException (BLWE) is not a bug in the library. It shouldn't be device specific either. Please have a look at #1074 for an explanation on what the exception means. If this is not clear to you, let me know and I'll try to clarify further.

It might be the case that some changes we have made mitigate the occurence, but it's certainly not something we have _fixed_ (or will fix).

I don't know what your app is doing when the player surfaces a BLWE, but a way to handle this is to re-prepare the media source. The ExoPlayer Demo App re-prepares the media source when a BLWE is thrown. If you are using [chunkless preparation](https://medium.com/google-exoplayer/faster-hls-preparation-f6611aa15ea6) in HLS, re-preparing should be relatively cheap.

You can also track the loading position, and prevent it from becoming negative by seeking forward (or setting a higher playback speed, if the bandwidth is healthy). This is a way of preventing BLWE from happening, unlike re-preparing which is just a reactive solution. Hope this helps a bit.

**Comment by lricardo** [comment]
@AquilesCanta Thank you very much for your comment. It will be very helpful.

**Comment by lricardo** [comment]
> You can also track the loading position, and prevent it from becoming negative by seeking forward (or setting a higher playback speed, if the bandwidth is healthy). This is a way of preventing BLWE from happening, unlike re-preparing which is just a reactive solution. Hope this helps a bit.

@AquilesCanta I'm repreparing it but it still stucks. How can I track the loading position? I have been looking to exoplayer documentation but I could not find any information about it. Thanks in advance.

**Comment by AquilesCanta** [comment]
Try using Player#getBufferedPosition. It's also a more conservative possibility to use the playback position (getCurrentPosition).

**Comment by lricardo** [comment]
I should do that using onTimelineChanged callback or using a handler instead?

**Comment by AquilesCanta** [comment]
`onTimelineChange` could be a good place to make these decisions, since it gets called whenever a new playlist snapshot is loaded. A new snapshot could be discarding old segments from the playlist, which is the cause of behind live window exceptions.

**Comment by lricardo** [comment]
Hello again. Know that I have digested this a little bit and successfully solved the problem, I would like to thank you. That's solved! 😃

For those who are with doubts respecting to this:
* Tracking the buffering position is enough. You can log this value on `onTimelineChange` callback, using android logger. In my case, I set that the video should seek to the default position if the buffered position gets lower than a given value. This helps a lot preventing BLWE but it's not strictly necessary and can prevent the track from changing on different bandwidth conditions.

```
player?.bufferedPosition.let {
    if (it != null) {
        if (it <= -2000) {
            Log.i("ExoPlayerTrait.kt", "Seek to default position [BFRP < 0]")
            player?.seekToDefaultPosition()
        }
    }
}
```
* Also, I noticed that the re-preparation is a kind of a hack that I would like to see more documented. I can help with that. In my understanding, giving the developer the power to deal with a problem is good, but then the responsibility for what happens next is from the developer too. This might be very tricky in the situation when the provider uses some sort of authentication. In my case, the provider  is using Akamai (which is one of the most popular CDNs out there) gives, first, a url for the master playlist of a live stream. That URL expires in 5 minutes. If we need re-prepare the player, we need to re-prepare a new `MediaSource` and as such, give the master playlist url again. That will prompt a 403 forbidden, as expected. Given that this is a typical authentication use-case, why can't the MediaSource and ExoPlayer itself deal with that? For those having the same problem, I was capable of overcoming this by writing an OkHttp Interceptor, caching the last used playlist URL with the token as query parameter and then, feed it back to the player when a re-preparation is needed.
