### ISSUE TITLE
Get width & height of player?

### ISSUE THREAD

**Issue by ttm-hoangcm** [google/ExoPlayer#4729]
Does ExoPlayer have these methods, like getVideoHeight() & getVideoWidth() of MediaPlayer. Because I need something same to its while use ExoPlayer with other library. Thanks.

**Comment by ojw28** [comment]
There are multiple ways of getting the video width and height, and being notified when it changes:
* If you just want to query the current dimensions, you can use `SimpleExoPlayer.getVideoFormat`, and then look at its `width` and `height` fields. Note that the format may be null if it's not yet known.
* To known when the video size becomes known or changes, you can use `AnalyticsListener.onVideoSizeChanged`. You can add an `AnalyticsListener` using `SimpleExoPlayer.addAnalyticsListener`.
* To known when the video size becomes known or changes, you can also use `VideoListener.onVideoSizeChanged`. You can add an `VideoListener` using `SimpleExoPlayer.addVideoListener`.
