### ISSUE TITLE
Handling the player inside ViewPager

### ISSUE THREAD

**Issue by ArcherEmiya05** [google/ExoPlayer#4730]
Is there any sample on how to handle correctly the video playback if it is in ViewPager? For example play will be triggered if and only if the PlayerView gets visible in screen or ViewPager. If the user swipe to next page the previous video will stop or destoyed.

**Comment by ArcherEmiya05** [comment]
I do not want to use FragmentStatePagerAdapter or FragmetPagerAdapter since it may cause overhead.

**Comment by ened** [comment]
What means "may cause overhead" in this case?

Anyway, perhaps check https://stackoverflow.com/a/20657022/375209 and ask on SO instead?

**Comment by AquilesCanta** [comment]
> Is there any sample on how to handle correctly the video playback if it is in ViewPager? 

None that is part of the demo app. 

You are probably better off asking in a general Q&A site, as @ened points out. This falls out of the scope of this issue tracker. Sorry and good luck!
