### ISSUE TITLE
Dash Content with 4 Resolution

### ISSUE THREAD

**Issue by abbasiehsan1991** [google/ExoPlayer#4735]
I have a  Dash content that has a video with 4 different resolution. I'm playing the video like this:

```
DataSource.Factory dataSourceFactory =
      new DefaultDataSourceFactory(this, Util.getUserAgent(this, "yaramobile.com.app.viedotest"));

    Uri uri = Uri.parse(videoUrl);

    DashMediaSource dashMediaSource = new DashMediaSource(uri, dataSourceFactory,
      new DefaultDashChunkSource.Factory(dataSourceFactory), null, null);

    BandwidthMeter bandwidthMeter = new DefaultBandwidthMeter();

    TrackSelector trackSelector = new DefaultTrackSelector(new AdaptiveTrackSelection.Factory(bandwidthMeter));

    player = ExoPlayerFactory.newSimpleInstance(this, trackSelector);

    simpleExoPlayerView.setPlayer(player);
    player.prepare(dashMediaSource);

```
I want to get all resolutions  and show it to the user
But I can't get 4 available qualities in `Exoplayer r2.5.3` Before I used `player.getTrackCount(0)` to get all qualities in `Exoplayer r1.5.8`.
I am really confused and I got nothing with my searches.
I really appreciate your help.

**Comment by AquilesCanta** [comment]
The Demo app supports manual resolution selection. In the PlayerActivity, have a look at the Video button. When you press it, a list of resolutions will pop up. This is handled by the TrackSelectionView. Please have a look. Good luck!
