### ISSUE TITLE
Issue with RTMP Live Stream MetaData Injection and receive on Android ExoPlayer

### ISSUE THREAD

**Issue by sandmanDev** [google/ExoPlayer#4737]
I am facing an issue with RTMP live stream MetaData injection and trigger it on client side. While using Wowza Stream Server I successfully inject metadata according to https://www.wowza.com/docs/how-to-inject-cue-points-or-metadata .

On client side using Exo Player for RTMP I add these listeners

    exoPlayer.addMetadataOutput(new MetadataOutput() {
        @Override
        public void onMetadata(Metadata metadata) {
        }
    });

    exoPlayer.addTextOutput(new TextOutput() {
        @Override
        public void onCues(List<Cue> cues) {     
        }
    });
These trigger doesn't called. I can explain further if this doesn't clear the picture.

Thanks Best Regards

**Comment by AquilesCanta** [comment]
This is not enough information for us to help you. Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE). Please don't skip any items.

**Comment by AquilesCanta** [comment]
We will reopen once the missing information is provided. Please post below to let us know you've filled the missing information.
