### ISSUE TITLE
setPlayWhenReady() crashes

### ISSUE THREAD

**Issue by komissarovdenis** [google/ExoPlayer#4738]
After update from 2.7.3 up to 2.8.4 I have seen rare bunch of crashes from fabric. There're two stacks related to `setPlayWhenReady()` method:

`
Fatal Exception: java.util.NoSuchElementException
       at java.util.ArrayDeque.removeFirst(ArrayDeque.java:263)
       at com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo(ExoPlayerImpl.java:682)
       at com.google.android.exoplayer2.ExoPlayerImpl.setPlayWhenReady(ExoPlayerImpl.java:201)
       at com.google.android.exoplayer2.SimpleExoPlayer.setPlayWhenReady(SimpleExoPlayer.java:693)
`

`
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.notifyListeners()' on a null object reference
       at com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo(ExoPlayerImpl.java:681)
       at com.google.android.exoplayer2.ExoPlayerImpl.setPlayWhenReady(ExoPlayerImpl.java:201)
       at com.google.android.exoplayer2.SimpleExoPlayer.setPlayWhenReady(SimpleExoPlayer.java:693)
`

At this point I have no idea about steps. But same code works fine on previous version of lib.

Looks like inconsistency of pendingPlaybackInfoUpdates in `ExoPlayerImpl`

`
    while (!pendingPlaybackInfoUpdates.isEmpty()) {
      pendingPlaybackInfoUpdates.peekFirst().notifyListeners();
      pendingPlaybackInfoUpdates.removeFirst();
 }
`

Thanks.

**Comment by Tolriq** [comment]
You need to have all calls on the same thread that created ExoPlayer or MainThread is your thread have no looper.

In 2.8.0 they added some internals that will triggers potential race conditions much more often and require proper enforcement of the threading model required for ExoPlayer.

**Comment by komissarovdenis** [comment]
Thank you @Tolriq, I'll check my code.

**Comment by breewf** [comment]
I have the same problem, but my player is used in the main thread. How did you solve it?

**Comment by tonihei** [comment]
@breewf Please update to 2.9.0 and check if you see warning about using the player on the wrong thread. It may be that you created the player on a background thread instead of the main thread?

**Comment by swapnilgt** [comment]
@komissarovdenis  Any updates on this? Were you able to solve this?

**Comment by davidaik** [comment]
I've been getting the same issue. My app plays music in a Service which is in a separate process of its own and I know that the ExoPlayer instance is accessed on the main thread of that process. I'm on 2.9.3.

**Comment by tonihei** [comment]
@davidaik @swapnilgt Please ensure that all player access is happening on the same thread and that this is the thread the player was created on. If you want to use another thread, there is also the option to specify a Looper in one of the `ExoPlayerFactory` methods.

**Comment by davidaik** [comment]
@tonihei Okay I investigated further and I found that IPC calls are not executed on the remote Service's main thread. I guess my issue is caused by concurrent modification and access of the pendingPlaybackInfoUpdates variable.

**Comment by tonihei** [comment]
You also get a logcat warning with a stack trace at the point where the access from the wrong thread is happening (from 2.9.0). So it should be easy to find the culprit code in theory.
