### ISSUE TITLE
The cache encryption method doesn't seem to work!

### ISSUE THREAD

**Issue by qeadsw** [google/ExoPlayer#4740]
Before filing an issue:
-----------------------

exoplayer 2.8.4

I want to use SimpleCache() to encrypt the cached file, which sets the password through the parameter "secretKey."

But the cached files can still be played on other ### ### players.

The default format for cached files is similar to "0.12346545678. V3.exo"

**Comment by AquilesCanta** [comment]
This issue is being closed because it does not adhere to our issue template, and/or because it omits information requested in the issue template that is required for us to investigate the problem efficiently. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

If you’re able to provide complete information as requested in the issue template, please do so below and we’ll re-open the issue. Thanks!

**Comment by erdemguven** [comment]
@qeadsw as @AquilesCanta pointed you haven't answered many questions which are in the issue template. Please provide as much information as you can so we can answer your question quickly.

**Comment by qeadsw** [comment]
@erdemguven Is my latest description detailed enough

**Comment by qeadsw** [comment]
@AquilesCanta @erdemguven

**Comment by qeadsw** [comment]
Didn't I describe it enough? Or is there a problem? Is there any difference between me and question #4730

**Comment by qeadsw** [comment]
@erdemguven

**Comment by qeadsw** [comment]
@erdemguven It looks like I can't add a tag myself

**Comment by qeadsw** [comment]
@erdemguven I have tried my best to improve the problem, may I ask where is not clear enough?

**Comment by erdemguven** [comment]
secretKey parameter in SimpleCache constructor is for encrypting the cache index file. To encrypt cached media files (exo files) you need to use AesCipherDataSink and AesCipherDataSource to encrypt and decrypt while you create your CacheDataSource.

**Comment by erdemguven** [comment]
For an example you can check com.google.android.exoplayer2.upstream.cache.CacheDataSourceTest2#buildCacheDataSource code.

**Comment by qeadsw** [comment]
@erdemguven Thank you very much. Please forgive me for the vague description of the problem.
