### ISSUE TITLE
How do I encrypt content written to or read the cache?

### ISSUE THREAD

**Issue by qeadsw** [google/ExoPlayer#4742]
I want to encrypt the cached file, Pass in the password by SimpleCache method "byte[]secretKey"
However, fragments of cached files can still be played normally on other players.

**Comment by AquilesCanta** [comment]
Please don't open duplicate issues and provide the requested information in #4740.

**Comment by qeadsw** [comment]
@AquilesCanta Then you point out the template

**Comment by AquilesCanta** [comment]
The link is in the comment.

**Comment by ojw28** [comment]
I think that only encrypts the cache index, not the actual content. @erdemguven - Can you provide some information about how to encrypt the content as well?

**Comment by ojw28** [comment]
Ignore; this was answered in #4740.
