### ISSUE TITLE
The cache encryption method doesn't seem to work!

### ISSUE THREAD

**Issue by qeadsw** [google/ExoPlayer#4744]
Before filing an issue:
-----------------------
version:2.8.4

I want to use SimpleCache() to encrypt the cached file, which sets the password through the parameter "secretKey."

But cached files can still be played by other players.

**Comment by qeadsw** [comment]
I don't know if this question meets the template, please point out thank you.

**Comment by qeadsw** [comment]
@ojw28 Please give advice or comments！

**Comment by AquilesCanta** [comment]
Closing as duplicate of #4742.
