### ISSUE TITLE
m3u8 subtitles are not supported

### ISSUE THREAD

**Issue by srikanthsunkari** [google/ExoPlayer#4745]
Hi,
I am facing a problem with m3u8 links for displaying subtitles, are m3u8 links are not supported with v2.2.0.
Trying to construct the media source like:

```
Format englishSubsFormat = Format.createTextSampleFormat(null, MimeTypes.APPLICATION_M3U8, null, Format.NO_VALUE, Format.NO_VALUE, "eng", null);
            MediaSource englishSubSource = new SingleSampleMediaSource(Uri.parse(englishSubtitleLink), mediaDataSourceFactory, englishSubsFormat, C.TIME_UNSET);
            MergingMediaSource mergedSource = new MergingMediaSource(videoSource, englishSubSource);
````

EventLogger shows below logs,

> Renderer:None [
08-27 15:35:51.903 27269-27269/com.myplex.vodafonestaging D/EventLogger: Group:0 [
[ ] Track:0, id=null, mimeType=application/x-mpegURL, language=English, supported=NO
]

Please let me know if anything wrong with Format creation.
Note: englishSubtitleLink is "m3u8" link.

**Comment by AquilesCanta** [comment]
Try replacing your single sample media source with an HlsMediaSource. 

The only way to reproduce m3u8 files is to use HlsMediaSource. SingleSampleMediaSource is only used for media which is made up by a single sample. For example, subtitle files (example: vtt, srt, etc). Note that m3u8 files themselves are not subtitles, but may contain a list of subtitles.

Depending on the type of `videoSource`, it might make more sense including subtitles as part of the original media. For example, if videoSource is an HlsMediaSource, then try referring to your subtitles m3u8 from an EXT-X-MEDIA. Please provide more context below (media links, for example), if this does not answer your question.

**Comment by srikanthsunkari** [comment]
Thank you @AquilesCanta, I am able to show subtitles with HlsMediaSource now.
      
The subtitle hls source is different from the video source, though the video source is also an hls source and each language subtitle has its own m3u8 link. 

Though being able to show subtitles, constructing HlsMediaSource for a specific subtitle will not allow me to specify the format id or language code except track group index, whereas with SingleSameMediaSource expects format and we can specify the language code in Format. 

 It would be great if there is a way to identify the Format belonging to a specific language using HlsMediaSource. Please let me know if I am missing anything here or is there any other way.

**Comment by AquilesCanta** [comment]
No, there is no straightforward way to do it. I insist that the right way is to include the subtitles as part of the original master playlist (which would allow you to provide a language as well). You could potentially pass a custom playlist parser that injects the subtitle rendition client side. So, basically you could wrap the default playlist parser, and once the master playlist is parsed, you add your subtitle link to the `subtitles` field. Hope this helps.

**Comment by srikanthsunkari** [comment]
Thank you @AquilesCanta, It is not possible to include subtitles as part of an original master playlist. Well, for now, I get it managed with the positions of added subtitles. I will sure do look into constructing custom playlist parser for customizing.
Thank you again for the help.

**Comment by srikanthsunkari** [comment]
Hi @AquilesCanta, I observed playback is not in sync with the subtitles. I see that subtitles are displayed earlier than the usual point. Is this an issue with the subtitle link or am I missing anything?

**Comment by srikanthsunkari** [comment]
Please let me know if any info is required from my end, or If it is required to raise a new Issue? If you feel that originally raised issue has closed.

**Comment by AquilesCanta** [comment]
> I observed playback is not in sync with the subtitles

Which approach are you using?

I am going to assume the subtitles are webvtt. Then the files should start with

WEBVTT
X-TIMESTAMP-MAP=MPEGTS:XXXXXXX,LOCAL:00:00:00.000

You need to make sure is that the MPEGTS value equals the first PTS in the TS files. This is the way in which HLS ensures the subtitles are in sync. If this does not work for you, you can still go with the MergingMediaSource approach, combined with custom playlist tracker (in the HlsMediaSource of the subtitles playlist) that wraps the default one and injects the language to the getMasterPlaylist method. In this case you don't need a custom playlist parser, just a custom tracker.

**Comment by srikanthsunkari** [comment]
Yes, I am following the WEBVTT approach with MergingMediaSource and custom tracker.
I don't see
> WEBVTT
>  X-TIMESTAMP-MAP=MPEGTS:XXXXXXX,LOCAL:00:00:00.000


Sample m3u8 file look like :

> #EXTM3U
> #EXT-X-VERSION:3
> #EXT-X-TARGETDURATION:5859
> #EXT-X-MEDIA-SEQUENCE:0
> #EXT-X-PLAYLIST-TYPE:VOD
> #EXTINF:5859
> XYZ-cap_eng.vtt
> #EXT-X-ENDLIST
> 

Video source and multiple m3u8 subtitles media source with MergingMediaSource

```
`               int mediaSourceArraySize = subtitles.values.size() + 1;
                MediaSource[] mediaSourceArray = new MediaSource[mediaSourceArraySize];
                int i = 0;
                mediaSourceArray[i] = videoSource;
                i++;
                for (SubtitleItem subtitleItem :
                        subtitles.values) {
                    String mimeType = MimeTypes.APPLICATION_TTML;
                    MediaSource subTitleSource;
                    //builds HlsMediaSource similar to video source
                    subTitleSource = buildMediaSource(Uri.parse(subtitleItem.link_sub),null);
                    mediaSourceArray[i] = subTitleSource;
                    i++;
                }
                MergingMediaSource mergedSource = new MergingMediaSource(mediaSourceArray);
                player.prepare(mergedSource, true, false);
            }
`
```
Below is first subtitle to be displayed:

> 
> WEBVTT
> 
> 00:00:31.398 --> 00:00:35.402
> <i>I get to work before the sun comes up
> </i>and I leave long after it's gone down.
> 

Whereas it is displaying as soon as playback starts.

**Comment by srikanthsunkari** [comment]
Hi @AquilesCanta, waiting for your reply on subtitles duration issue, Please let me know if in case you want me to raise a new issue.

**Comment by srikanthsunkari** [comment]
Raised new issue for playback sync with subtitles #4758 .
