### ISSUE TITLE
HLS loading is very slow on Oreo & Pie

### ISSUE THREAD

**Issue by adesentenac** [google/ExoPlayer#4750]
### Issue description
Playing the HLS examples in the demo app takes a very long time to load (and sometimes do not load at all) on Oreo and Pie devices.

### Reproduction steps
Run the demo
Expand HLS
Click on "Apple 4x3 basic stream"

### Link to test content
Content in the demo

### Version of ExoPlayer being used
2.8.4 (also reproduced in 2.8.1)

### Device(s) and version(s) of Android being used
Pixel 2 XL Android 9
Nexus 6P Android 8.1.0
LG G6 Android 8.0.0

Note: Works correctly on a HTC One A9 Android 7.0

### A full bug report captured from the device
[bugreport.txt](https://github.com/google/ExoPlayer/files/2332826/bugreport.txt)
Start at 08-29 11:51:46.893

**Comment by AquilesCanta** [comment]
Would you kindly try using the Cronet extension and see if that works?

**Comment by AquilesCanta** [comment]
Note for later: This only seems to happen with https streams (http equivalents play correctly).

**Comment by adesentenac** [comment]
I will try with the Cronet extension.
Also as a note that might give some insight, I tried to target API 28 and I had to add a network security configuration to allow clear text traffic to apple.com to be able to play the https stream (but with the same slowness as mentioned here).

**Comment by ojw28** [comment]
Is this specific to the Apple samples? If samples are streaming fine from elsewhere, does that suggest the issue is unlikely to be client side, and more likely to be a server issue (triggered by something legitimate that the network stack on Oreo/Pie does?

**Comment by adesentenac** [comment]
It does seem related to Apple samples, and using the Cronet extension does fix the issue.

**Comment by ojw28** [comment]
Probably related to https://github.com/google/ExoPlayer/issues/5103
