### ISSUE TITLE
How does the ExoPlayer works when switching the SampleStream exposed from different MediaSource?

### ISSUE THREAD

**Issue by Romantic-LiXuefeng** [google/ExoPlayer#4752]
I am Chinese with poor English. I am confused that when playing playlist with ConcatenatingMediaSource, how does the MediaCodecRenderer works between advance reading media period and advance playing media period?  
I know that when the all renderers have read the end of streams, that is the SampleQueue is empty .
at this time , need to advance the reading period.  My questions are: 
1. Hope you tell me what the mediacodec renderer do after renderer replace stream? 
2. When to advance the playing period?
Thanks very much! Hoping you can give more information how does ExoPlayer works on blog. @canatella @kiall @talklittle @andrewlewis @jcable

**Comment by AquilesCanta** [comment]
Hi @Romantic-LiXuefeng, this question falls outside the scope of this issue tracker, the questions are very broad. I think your best shot is adding some logging to the media codec renderers (and potentially ExoPlayerImplInternal) and running a few samples that show what you want to analyze. @andrewlewis and @ojw28 may be able to provide more guidance.

**Comment by Romantic-LiXuefeng** [comment]
Thanks a lot. By reading the source code,  I found the steps are that while player is playing playlist:
1. When the player is playing the first media period, maybe the first media period is already fully 
    buffered. At this time, advance loading period pointer, to pointing the second media period, then 
   the load thread begins buffering to the SampleQueue under controlled by LoadControl.
2. The renderers loops read from the first media period SampleQueue. When all renderers have read 
   end of stream of first media period, that means the first media  period  SampleQueue is empty. At 
   this time, advance reading period pointer, to pointing the second media period, and the renderers 
   may set final or replace stream,  then video renderer reads the format changed from second 
   SampleQueue.
3. When video renderer reads the format changed, first judge the format is supported reconfigure 
    codec.
    If true,  support reconfigure codec :
    (1).codecReconfigurationState sets RECONFIGURATION_STATE_WRITE_PENDING, 
    (2) next loop sets RECONFIGURATION_STATE_QUEUE_PENDING and supply the all reconfiguration 
    data at the start of the buffer.(3).next loop, append the first frame in the new format to the buffer,
    then feed into decoder.
    If false, re-initialization codec:
    (1).codecReinitializationState set REINITIALIZATION_STATE_SIGNAL_END_OF_STREAM, 
    and  set empty buffer with EOS flag to decoder. and then break the loop, the renderer will stop 
    reading from second SampleQueue.  (2). the decoder loops renderer the output buffers until read 
    the  output buffer with EOS flag,  indicates that the renderer have render to the  end.  
   (3) re-initialization codec with new format.
4. When all renderers  have rendered  to the  end.  then advance playing period pointer,  to pointing 
   the second media period. then update the renderers, maybe some renderer disable, or re-enable,
   or nothing todo.  
5. As of this date，the player begins playing the second period, the player state may buffering or 
   ready.
@andrewlewis @ojw28  is the steps correct ? and is some steps missing?  
 Between advance reading period and advance playing period, whether the decoder just renderer 
 output buffer ? If so, how to get the size of the MediaCodec input buffer and output buffer ?
