### ISSUE TITLE
Playing only local files when device becomes offline

### ISSUE THREAD

**Issue by gbirk** [google/ExoPlayer#4754]
I'm migrating my music player app from MediaPlayer to ExoPlayer2. So far everything is working flawlessly. I'm initializing the player using a **DefaultLoadControl** and a **DefaultTrackSelector**. I'm using **ConcatenatingMediaSource** as media source, containing mp3 URLs and also local files. I would like to know the best way to make ExoPlayer play only the local files when the device is offline. Any **DefaultTrackSelector.Parameters** that I can use to support this? Or should I create another ConcatenatingMediaSource containing only the local files? I'm fairly new to ExoPlayer.

**Comment by tonihei** [comment]
Your second proposed solution should work best for now. If you can easily distinguish between remote and local files, please just add the local files to the ConcatenatingMediaSource and you should be fine.

Automatically skipping remote files when they fail to load is not supported yet. Issue #4343 is tracking a feature request to skip failing files. As soon as that is supported, the remote mp3s should be automatically skipped as they fail to load when offline.
