### ISSUE TITLE
Stream video on WiFi only

### ISSUE THREAD

**Issue by abredykhin** [google/ExoPlayer#4756]
I'm looking for ways how to limit ExoPlayer to only stream HSL video on WiFi. I've found the `PlatformScheduler` class with corresponding `Requirements`, but it doesn't look like they're being used anywhere. 

I plan to listen to change in network connectivity and then manually stop/restart ExoPlayer depending on whether it's WiFi or LTE. Is there a more efficient way to deal with this?

**Comment by AquilesCanta** [comment]
I don't think you need to use a Scheduler for this. [Have a look here](https://developer.android.com/training/basics/network-ops/managing) for info about detecting network changes. From there you can stop/restart the player. Does this help?

**Comment by abredykhin** [comment]
Well, that was my original plan, I know how to detect changes in network in Android. Was hoping to find some additional support from ExoPlayer for this.
