### ISSUE TITLE
How to know Hardware Accelerated Video Decoders ?

### ISSUE THREAD

**Issue by manishPatwari** [google/ExoPlayer#4757]
Hi,

Is there anyway we can get to know, which all Video decoders are Hardware accelerated ? I have seen the [MediaCodeUtil](https://github.com/google/ExoPlayer/blob/09d1e3e35d98fd02c31391ac1c891f0c73e76375/library/core/src/main/java/com/google/android/exoplayer2/mediacodec/MediaCodecUtil.java#L241) which depend on the framework to give best decoder _"MediaCodecList is sorted by the framework such that the best decoders come first_.". 

I have played Multi-Codec DASH file in [Vivo V9](https://www.devicespecifications.com/en/model/c3ed4935) ["Video file formats/codecs"] mobile which has hardware acceleration for H265 & VP9 but still it played video in H264 codec. 
Is there anyway I can play the video in best codec which is Hardware Accelerated, preference would be "V9" or "H265" and then "H264".

**Comment by AquilesCanta** [comment]
In the case of a multi-codec adaptive stream, the first thing you need to look at is the TrackSelector. The TrackSelector will select the tracks from which the adaptive algorithm will pick chunks. If you want to choose tracks with a specific mime type (e.g: video/hevc), then you can do that by implementing your own TrackSelector. Maybe overriding the default track selector is an option for you.

Second point: To implement the track selection criteria (for instance, prefer HEVC over AVC) you might then want to look into the codec list. MediaCodecUtil might help with that. Also have a [look around](https://stackoverflow.com/questions/37715529/how-to-know-android-decoder-mediacodec-createdecoderbytypetype-is-hardware-or) for information about codecs being HW or SW.

Does this help?

**Comment by manishPatwari** [comment]
@AquilesCanta  Thanks for the quick reply.

As per the Stackoverflow post, `codec.getName().startsWith("OMX.google.")` is Software encoder, but it doesn't seems correct. 

In the below screenShoot, I was doing CPU profiling in Moto E2, and the codec used for HEVC is "le.hevc.decoder" & for VP9 "gle.vp9.decoder" is used. If we go with definition  `codec.getName().startsWith("OMX.google.")`  then this codecs should be Hardware Accelerated. But the CPU usage is huge. 

Is there anyway we can avoid such cases and always use the optimised decoder ?

<img width="1399" alt="screen shot 2018-08-30 at 7 30 15 pm" src="https://user-images.githubusercontent.com/11611899/44908761-5cb6ea80-ad3a-11e8-9774-dc64420d3157.png">

**Comment by AquilesCanta** [comment]
> codec.getName().startsWith("OMX.google.") then this codecs should be Hardware Accelerated

If I am reading correctly, the SO post suggests the contrary, right?

```
MediaCodec codec = MediaCodec.createDecoderByType(type);
if (codec.getName().startsWith("OMX.google.")) {
    // Is a software codec
}
```

Also, is it possible that at some point the profiler is suffixing the last 15 characters? This would go in line with the SO post:

We have le.hevc.decoder and gle.vp9.decoder: I am tempted to think they are both 15 character suffixes of the entire name, which is actually OMX.goog**le.hevc.decoder** and OMX.goo**gle.vp9.decoder**. Which would explain why they are software (and using lots of CPU). Please check whether the codecs are appearing as in the profiler and it's not just some visualization name tweak.

Makes sense?

**Comment by manishPatwari** [comment]
@AquilesCanta  Awesome... it completely make sense and true. Thanks alot for your kind help.

**Comment by ojw28** [comment]
Note: Upcoming Google software decoders are likely to start with the `c2.android.` prefix, rather than `OMX.google.`. So you should probably check for that case as well.
