### ISSUE TITLE
Playback is not in sync with the HLS subtitles

### ISSUE THREAD

**Issue by srikanthsunkari** [google/ExoPlayer#4758]
Hello, Playback and subtitles are not in sync with WEBVTT format subtitles. I'm following the MergingMediaSource approach for multiple HlsMediaSource for subtitles rendition with the video HlsMediaSource.

Sample m3u8 file look like :

> 
> #EXTM3U
> #EXT-X-VERSION:3
> #EXT-X-TARGETDURATION:5859
> #EXT-X-MEDIA-SEQUENCE:0
> #EXT-X-PLAYLIST-TYPE:VOD
> #EXTINF:5859
> XYZ-cap_eng.vtt
> #EXT-X-ENDLIST

Video source and multiple m3u8 subtitles media source with MergingMediaSource

```
`               int mediaSourceArraySize = subtitles.values.size() + 1;
                MediaSource videoSource = new HlsMediaSource(videoUri, buildDataSourceFactory(bandwidth_meter), 2, mainHandler, eventLogger);
MediaSource[] mediaSourceArray = new MediaSource[mediaSourceArraySize];
                int i = 0;
                mediaSourceArray[i] = videoSource;
                i++;
                for (SubtitleItem subtitleItem :
                        subtitles.values) {
                    mediaSourceArray[i] = new HlsMediaSource(Uri.parse(subtitleItem.sub_link), buildDataSourceFactory(bandwidth_meter), 2, mainHandler, eventLogger);;
                    i++;
                }
                MergingMediaSource mergedSource = new MergingMediaSource(mediaSourceArray);
                player.prepare(mergedSource, true, false);
            }
`
```
Below is the first subtitle to be displayed:

> WEBVTT
> 
> 00:00:31.398 --> 00:00:35.402
> I get to work before the sun comes up
> and I leave long after it's gone down.
> 

Whereas first subtitle is displaying as soon as playback starts, I can see the first title is supposed to show at the position of 31st sec. 
I will be sharing the m3u8 link to your email for your reference. Please let me know if any info other info required.

**Version of ExoPlayer : v2.2.0**

**Comment by AquilesCanta** [comment]
I will paste what I commented in the previous post:

===============

I am going to assume the subtitles are webvtt. Then the files should start with

WEBVTT
X-TIMESTAMP-MAP=MPEGTS:XXXXXXX,LOCAL:00:00:00.000

You need to make sure is that the MPEGTS value equals the first PTS in the TS files. This is the way in which HLS ensures the subtitles are in sync. 

If this does not work for you, you can still go with the MergingMediaSource approach, combined with custom playlist tracker (in the HlsMediaSource of the subtitles playlist) that wraps the default one and injects the language to the getMasterPlaylist method. In this case you don't need a custom playlist parser, just a custom tracker.

===============

As you show in the pasted snippet, the file does not contain the X-TIMESTAMP-MAP. As the spec states:

```
   If a WebVTT segment does not have the X-TIMESTAMP-MAP, the client
   MUST assume that the WebVTT cue time of 0 maps to an MPEG-2 timestamp
   of 0.

```

So I suppose your TS files start with a PTS larger than 0 (I have commonly seen 90000 as starting value). Please try one of the approaches suggested in the original comment.

**Comment by srikanthsunkari** [comment]
I hope your suggestion will resolve the subtitle track language problem, by supplying language to the HlsMediaSource, is that look like below?

`    playlistTracker.getMasterPlaylist().subtitles.get(0).format.language = subtitleItem.language;`

**Comment by AquilesCanta** [comment]
Something that came to mind, if your playlist just has one file in it, why not use that internal VTT file to create a SingleSampleMediaSource?

**Comment by srikanthsunkari** [comment]
Yes, In this case, my playlist just has only one track, and I'm already using the single .vtt file and is working. we can close this since it is a bad media.
Thanks for the support.
