### ISSUE TITLE
Cast mp4 with basic auth

### ISSUE THREAD

**Issue by gerard87** [google/ExoPlayer#4760]
### Issue description
I have a server serving mp4 video files.

Using the demo cast example in this repository:

If I disable the basic authentication on the server, both exoplayer and casting to chromecast works fine adding my files as samples in DemoUtil class.

When I enable the auth, I can play the videos on exoplayer adding requestproperties on defaulthttpdatasourcefactory:

`DATA_SOURCE_FACTORY.getDefaultRequestProperties().set("Authorization","Basic " + encodeduserpass);`

But cast to chromecast is not working, and show the error:
`W/MediaControlChannel: received unexpected error: Invalid Request.`

I think because auth property is not attached to the cast request.

There is any option to attach the authorization properly to the cast stuff?
Thank you.

### Version of ExoPlayer being used
Exoplayer 2.8.4

### Device(s) and version(s) of Android being used
Pixel 2 XL
Android 9 Pie

**Comment by fabiosoft** [comment]
news?

**Comment by AquilesCanta** [comment]
Hi, sorry for the delay. There is no Android API to set the HTTP headers that the receiver will use for requests. 

To implement authentication, you'll need to implement a custom receiver app that does it. More info about how to do this in the receiver app [here](https://developers.google.com/cast/docs/reference/caf_receiver/cast.framework.PlaybackConfig#segmentRequestHandler).
