### ISSUE TITLE
CENTER_CROP in TextureView

### ISSUE THREAD

**Issue by ArcherEmiya05** [google/ExoPlayer#4762]
When using SurfaceView          player.setVideoScalingMode(C.VIDEO_SCALING_MODE_SCALE_TO_FIT_WITH_CROPPING) is working as expected, unfortunately when I use TextureView by providing a surface_type in xml it is not working. Is this a bug or this is a expected behavior.

**Comment by ojw28** [comment]
It's a platform limitation (or just expected platform behavior) that scaling mode only applies when using `SurfaceView`. If you're using `PlayerView`, you could try to see if `PlayerView.setResizeMode` does what you want. Valid values are the `AspectRatioFrameLayout.RESIZE_MODE_*` constants (we need to improve our Javadoc to make this more obvious). If you're using `TextureView` directly, you can look at `TextureView.setTransform`.

**Comment by AndroidDeveloperLB** [comment]
@ojw28 What is the transform matrix that should be used for centerCrop on TextureView?
