### ISSUE TITLE
How to fix rotate incorrect problem with under Android 4.0 device?

### ISSUE THREAD

**Issue by ghostknow** [google/ExoPlayer#4763]
As title, The video play with Android 5.0+ is correct orientation. How to fix it with Android 4.0 device.
Thanks.

**Comment by tonihei** [comment]
Please provide the information requested in the [issue template](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE) for us to take a closer look. Thanks!

**Comment by tonihei** [comment]
This is probably also a duplicate of #91. Please have a look at the `unappliedRotationDegrees` reported through the `VideoListener.onVideoSizeChanged` callback.
