### ISSUE TITLE
How to manually select stream from HLS ?

### ISSUE THREAD

**Issue by swapps** [google/ExoPlayer#4764]
Hi,

is there a way to list the available quality streams from an hls and manually select one of them ?

thanks,

Cyril

**Comment by tonihei** [comment]
The preferred way is to set restrictions in the parameters of [`DefaultTrackSelector`](https://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/trackselection/DefaultTrackSelector.html). Alternatively, you can wait until the track information becomes available (listen to `eventListener.onTracksChanged`) and then set an `SelectionOverride` to the `DefaultTrackSelector`. Please read the documentation of `DefaultTrackSelector` for all the details.

**Comment by tonihei** [comment]
Closing as the question was answered. Please feel free to reopen if not.
