### ISSUE TITLE
is there any way to save the error log???

### ISSUE THREAD

**Issue by RaymanMartin** [google/ExoPlayer#4767]
In my case, something the player may throw some errors when i play with url.....like 404 resource not found or decode error or something else...how can i catch these error to local file???

**Comment by tonihei** [comment]
You can add a listener to the player with `player.addListener` and listen to `onPlayerError` events. The exception is passed as parameter to this callback and you can log it to file or wherever you want.

**Comment by RaymanMartin** [comment]
thank you...

**Comment by RaymanMartin** [comment]
em~some time the video will freeze when i play with mp4...but just some video.not the most of them...but there's no any error, but just freeze...

**Comment by tonihei** [comment]
If you have an specific issue with a file, please fill you out the [issue template](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE) with reproduction steps, test media etc.

**Comment by tonihei** [comment]
Closing as the original question has been answered.
