### ISSUE TITLE
Investigate discontinuity reason for ad skipping

### ISSUE THREAD

**Issue by gerardiandrea** [google/ExoPlayer#4768]
Is there a method in ima-extensions to know if the ad in playback is a pre-roll, mid-roll or post-roll?
Thanks

**Comment by tonihei** [comment]
You can query the ad group positions by getting the timeline period with `player.getCurrentTimeline().getPeriod(0, new Period())` and then look at `period.adPlaybackState.adGroupTimes`. If the ad group time is 0, it's a pre-roll ad, if it's `C.TIME_END_OF_SOURCE`, it's a post-roll ad, and all other values indicate a mid-roll ad.

If the ad is currently playing, you can also check `player.getContentPosition()` to get the position of the content. This is either 0 for pre-roll, the duration of the content for post-roll or a value inbetween for mid-roll ads.

**Comment by gerardiandrea** [comment]
Thanks but...
player.getCurrentTimeline().getPeriod(0, new Period()) throw exception "java.lang.IndexOutOfBoundsException"
(player.getCurrentTimeline().getPeriodCount() return 0)

and 'period' in version 2.8.4 does not have a method or variable 'adPlaybackState'

can you give me some more info on why I have the exception?
thanks

**Comment by tonihei** [comment]
The information is not available immediately but only after the ad data has been loaded. Please listen to `onTimelineChanged` events and check the timeline to see whether the required information is available. Note that initially, before anything is known, the timeline is empty (check for `timeline.isEmpty()`) and accessing the period with index 0 will throw an IndexOutOfBoundsException.

Sorry for the `adPlaybackState` - this information is private in the class. Please use `period.getAdGroupCount()` to get the number of ad groups and `period.getAdGroupTimeUs(index)` to get the time of a specific ad group.

**Comment by gerardiandrea** [comment]
Thanks for the directions.
I have another problem now. To know the current ad in playing I'm using "player.getCurrentAdGroupIndex()" but in the case of post-roll it returns -1.

is it an error or can I always consider -1 a post-roll?
Thanks

**Comment by tonihei** [comment]
That shouldn't be the case. Are you sure the post-roll is still playing? `player.isPlayingAd()` should be true if that's the case.

**Comment by gerardiandrea** [comment]
in fact player.isPlayingAd () returns false, I tried to insert the logic both in "onTimelineChanged" and in "VideoAdPlayer.VideoAdPlayerCallback - onPlay" but in the case of post-roll I always have player.isPlayingAd() false.

What is the best callback to track the transition from an advertisement to content and vice-versa?

**Comment by tonihei** [comment]
You need to listen to `eventListener.onPositionDiscontinuity` for that. The specified reason will be `DISCONTINUITY_REASON_AD_INSERTION`.

**Comment by gerardiandrea** [comment]
I was also trying 'onPositionDiscontinuity' but it seems to me that it is not always called, while 'onTracksChanged' is called regularly between an ad and the content and vice-versa

**Comment by tonihei** [comment]
`onPositionDiscontinuity` should always be called. The only exception is that when the transition happens because the timeline changed. In this case only `onTimelineChanged` will be called.

**Comment by gerardiandrea** [comment]
onPositionDiscontinuity  - DISCONTINUITY_REASON_AD_INSERTION is not called when I skip the ad

**Comment by tonihei** [comment]
Yes indeed. As noted above, the transition can also happen as part of a `onTimelineChanged` event. When you skip the ad, the timeline is changed because the ad is marked as played. And because we suppress reporting discontinuities if the timeline changed, you'll only get this one event.

Admittedly, this is really confusing and I was expecting to receive the onPositionDiscontinuity too in this case. Will have a look whether we should report DISCONTINUITY_REASON_AD_INSERTION as well in such a case. Marking it as an enhancement.

**Comment by marcbaechinger** [comment]
This [commit](https://github.com/google/ExoPlayer/commit/dc4148d5767b634c91e33bb27751756c921fe271) that landed in dev-v2 deprecates the old [`onPositionDiscontinuity`](https://github.com/google/ExoPlayer/blob/dev-v2/library/common/src/main/java/com/google/android/exoplayer2/Player.java#L597) callback in favor of a new version that has two additional parameters for the old and new `PositionInfo`. 

This is relevant for detecting discontinuities that involve ads in the following:

* the new callback has two additional arguments `oldPosition` and `newPosition` of type [`PositionInfo`](https://github.com/google/ExoPlayer/blob/dev-v2/library/common/src/main/java/com/google/android/exoplayer2/Player.java#L708). The position info contains information about the window, period and position as well as whether the position is within an ad or content period.
* The reason `DISCONTINUITY_REASON_AD_INSERTION` has been removed. Transitions from content to ad, ad to content or ad to ad periods are reported with reason `DISCONTINUITY_REASON_AUTO_TRANSITION`.
* The reason `DISCONTINUITY_REASON_SKIP` has been added. It indicates when an ad that was being played has been skipped by the user (in case ad playback is implemented with an `AdsMediaSource` like the IMA extension does).
