### ISSUE TITLE
Authentication for HLS

### ISSUE THREAD

**Issue by Arqu** [google/ExoPlayer#477]
Is it possible to use a similar approach for HLS as with SmoothStreaming where we use the cookie handler and executePost method make requests with additional request parameters for .m3u8 files? This way we could implement authentication and content protection as per Apple guidelines (https://developer.apple.com/library/ios/qa/qa1661/_index.html).

**Comment by ojw28** [comment]
If this is just a question, then I think the answer is yes? If you're implying something is missing that means you can't do this, can you specify what :)?

**Comment by Arqu** [comment]
Just checking up, I'll try to push a commit in the following days when I come around to doing it.

**Comment by ojw28** [comment]
Closing this for now, because it's unclear what it's actually tracking.
