### ISSUE TITLE
ExoPlayer calls onPlayerError method in EventListener after changing video quality

### ISSUE THREAD

**Issue by AlexDundar** [google/ExoPlayer#4776]
I use Exoplayer library in my android app for playing some live HLS videos (.m3u8 format). The version is 2.8.4. I need to make functional in which the user can change video quality of live stream during watching it.

For this I use the followng method (I took it from exoplayer example project):

```
Pair<AlertDialog, TrackSelectionView> dialogPair = TrackSelectionView.getDialog(this, title, trackSelector, rendererIndex);
    dialogPair.second.setShowDisableOption(true);
    dialogPair.second.setAllowAdaptiveSelections(allowAdaptiveSelections);
    dialogPair.first.show();
```

When I select some video quality, I see that new quality, but often (sometimes very often) after few seconds exoplayer throws an error in Player.EventListener in onPlayerError(ExoPlaybackException error) method. ExoPlaybackException always has TYPE_SOURCE and null messages. And I also noticed, when I see live videos in auto quality, it doesnt change quality to low when my internet connection goes down, I see the same exoplayer error with TYPE_SOURCE.

Here is my code for initializing player:

```
bandwidthMeter = new DefaultBandwidthMeter();
    AdaptiveTrackSelection.Factory videoTrackSelectionFactory = new AdaptiveTrackSelection.Factory(bandwidthMeter);
    trackSelector = new DefaultTrackSelector(videoTrackSelectionFactory);

    player = ExoPlayerFactory.newSimpleInstance(
            new DefaultRenderersFactory(getActivity()),
            trackSelector,
            new DefaultLoadControl());
    exoPlayerOnline.setPlayer(player);
    MediaSource mediaSource = buildMediaSource(Uri.parse(videoStreamUrl));  
    player.prepare(mediaSource, true, false);
    player.setPlayWhenReady(playWhenReady);
```

and method buildMediaSource():

```
private MediaSource buildMediaSource(Uri uri) {
        DefaultHttpDataSourceFactory httpDataSourceFactory = new DefaultHttpDataSourceFactory(userAgent,
                bandwidthMeter,
                20 * 1000,
                20 * 1000,
                true);
        DefaultDataSourceFactory defaultDataSourceFactory = new DefaultDataSourceFactory(getActivity(),
                bandwidthMeter,
                httpDataSourceFactory);
        OkHttpDataSourceFactory okHttpDataSourceFactory = new OkHttpDataSourceFactory(okHttpClient,
                userAgent,
                bandwidthMeter);

    int type = Util.inferContentType(uri);
    switch (type) {
        case C.TYPE_SS:
            return new SsMediaSource.Factory(new DefaultSsChunkSource.Factory(defaultDataSourceFactory), okHttpDataSourceFactory)
                    .createMediaSource(uri);
        case C.TYPE_DASH:
            return new DashMediaSource.Factory(new DefaultDashChunkSource.Factory(defaultDataSourceFactory), okHttpDataSourceFactory)
                    .createMediaSource(uri);
        case C.TYPE_HLS:
            return new HlsMediaSource.Factory(okHttpDataSourceFactory)
                    .createMediaSource(uri);
        case C.TYPE_OTHER:
            return new ExtractorMediaSource.Factory(okHttpDataSourceFactory)
                    .createMediaSource(uri);
        default:
            Toast.makeText(getActivity(), "Unsupported video type", Toast.LENGTH_LONG).show();
            return null;
    }
}
```
So, help me please, how to solve this problem?

**Comment by tonihei** [comment]
Can you check the type of `exoPlaybackException.getSourceException()`? Or even better, attach an `EventLogger` (as in the demo app) and report the full stack trace of the error. 

My best guess would be that the error you are seeing is a [`BehindLiveWindowException`](https://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/source/BehindLiveWindowException.html) in which case you can just try to restart playback with `player.prepare(sameMediaSource, false, false)`.

**Comment by AlexDundar** [comment]
The type of exception is TYPE_SOURCE

**Comment by tonihei** [comment]
I meant the class type of `exoPlaybackException.getSourceException()` and not `exoPlaybackException.type`.

**Comment by AlexDundar** [comment]
@tonihei thanks. Yes, the type of SourceException is com.google.android.exoplayer2.source.BehindLiveWindowException.
But reinitializing videoplayer every time when this exceptions throws looks too strange.

**Comment by tonihei** [comment]
If the bandwidth is too slow to catch up with the live window, there is no alternative to restarting playback in the current live window.

**Comment by AlexDundar** [comment]
Ok, thanks. I also can show also the full body of this BehindLiveWindowException:

`{"stackTrace":[{"declaringClass":"com.google.android.exoplayer2.source.hls.HlsChunkSource","fileName":"HlsChunkSource.java","lineNumber":290,"methodName":"getNextChunk"},{"declaringClass":"com.google.android.exoplayer2.source.hls.HlsSampleStreamWrapper","fileName":"HlsSampleStreamWrapper.java","lineNumber":539,"methodName":"continueLoading"},{"declaringClass":"com.google.android.exoplayer2.source.CompositeSequenceableLoader","fileName":"CompositeSequenceableLoader.java","lineNumber":78,"methodName":"continueLoading"},{"declaringClass":"com.google.android.exoplayer2.source.hls.HlsMediaPeriod","fileName":"HlsMediaPeriod.java","lineNumber":224,"methodName":"continueLoading"},{"declaringClass":"com.google.android.exoplayer2.source.DeferredMediaPeriod","fileName":"DeferredMediaPeriod.java","lineNumber":201,"methodName":"continueLoading"},{"declaringClass":"com.google.android.exoplayer2.MediaPeriodHolder","fileName":"MediaPeriodHolder.java","lineNumber":157,"methodName":"continueLoading"},{"declaringClass":"com.google.android.exoplayer2.ExoPlayerImplInternal","fileName":"ExoPlayerImplInternal.java","lineNumber":1542,"methodName":"maybeContinueLoading"},{"declaringClass":"com.google.android.exoplayer2.ExoPlayerImplInternal","fileName":"ExoPlayerImplInternal.java","lineNumber":1525,"methodName":"handleContinueLoadingRequested"},{"declaringClass":"com.google.android.exoplayer2.ExoPlayerImplInternal","fileName":"ExoPlayerImplInternal.java","lineNumber":322,"methodName":"handleMessage"},{"declaringClass":"android.os.Handler","fileName":"Handler.java","lineNumber":102,"methodName":"dispatchMessage"},{"declaringClass":"android.os.Looper","fileName":"Looper.java","lineNumber":193,"methodName":"loop"},{"declaringClass":"android.os.HandlerThread","fileName":"HandlerThread.java","lineNumber":65,"methodName":"run"}],"suppressedExceptions":[]}`

**Comment by tonihei** [comment]
Closing the issue as the question is already answered above. If not, please feel free to reopen.
