### ISSUE TITLE
Frame rate limited track selection

### ISSUE THREAD

**Issue by nicklasl** [google/ExoPlayer#4777]
I am missing the feature to limit/filter the track selection based on the format frame rate. We are currently seeing issues with dropped frames on some devices when using DASH+Widevine combined with a higher framerate (50fps). 
Suggestion is to add frame rate to `TrackSelector` parameters?

**Comment by tonihei** [comment]
That's certainly possible. Marking as an enhancement. 

If you are happy to give it try, we are always happy to accept pull requests. Otherwise, you'd need to wait until we get around to add this.

**Comment by tonihei** [comment]
Closing as the pull request is already merged.
