### ISSUE TITLE
Hls Caching Problem?

### ISSUE THREAD

**Issue by mahyarMeibodi** [google/ExoPlayer#4778]
hi
i'm having problem with **caching** in Hls protocol.
dose exoplayer provide any **caching** system for hls or should i try another way to cache my video?
@tonihei

**Comment by tonihei** [comment]
Yes, if you use the `CacheDataSourceFactory`, caching also works for HLS. 

If you would like to download the video before playing it (and not only caching it while playing), please have a look at [this](https://medium.com/google-exoplayer/downloading-streams-6d259eec7f95) and [this](https://medium.com/google-exoplayer/downloading-adaptive-streams-37191f9776e) blog post.

**Comment by jjimenez0611** [comment]
Someone with a basic example to caching HLS? 
I new in exoplayer, I only need a basic example to caching a video in HLS protocol...
If somebody can help me I really appreciate..
my email is jjimenez@soin.co.cr

**Comment by tonihei** [comment]
Please have a look at the blog posts mentioned above.

**Comment by tonihei** [comment]
Closing for now as the question is answered.
