### ISSUE TITLE
Detect/Switch Qualities on DASH and HLS

### ISSUE THREAD

**Issue by ldimitroff** [google/ExoPlayer#478]
I have ExoPlayer currently running HLS and DASH streams, but they are running as Adaptive videos.
On Hls I have to manually download the manifest and parse it to detect the levels and feed the player with the level url to play a video's quality.
On DASH seems that I can't do that. I found that the videoAdaptationSet on the example, contains representations, and this representations are the qualities for that video. The only thing that I found similar to a url is pointing to a ".dash" file, witch ExoPlayer can't play on the same way as DASH.
Is there a way to do this or a workaround that I can use?

**Comment by ojw28** [comment]
I'm not sure what this question is asking. You don't need to manually parse the HLS manifest; HLS and DASH work in much the same way in ExoPlayer (and both are adaptive).

**Comment by ldimitroff** [comment]
Yes, the are both adaptive and working great. 
The question is: Is there a way to select a quality and stick to it (disable the adaptive feature). On hls I am parsing the manifest, because I can feed ExoPlayer with the level that I want. 
Maybe there is a better way to do it. Same thing goes for DASH, how to detect and switch (and keep only one quality) in order to provide a quality selector to the user.

**Comment by ojw28** [comment]
In DashRendererBuilder of the demo app there's an array called videoRepresentationIndices that contains the allowed format indices. In HlsRendererBuilder there's variantIndices, which does the same thing. You should be able to replace those with arrays of length 1 that contain just the index of the format you want.

Alternatively, for DASH, you can implement a FormatEvaluator that doesn't change quality (we're working on hooking this up to HLS too, but we're not there yet).

**Comment by crossle** [comment]
@ojw28  How to manual switch  variant  in HLS? or provider a interface?
