### ISSUE TITLE
Can Pixel XL 1, after updating to 9.0 Pie, reproduce a 10-bit hevc file using hardware decoding?

### ISSUE THREAD

**Issue by zevr** [google/ExoPlayer#4784]
Can Pixel XL 1, after updating to 9.0 Pie, reproduce a 10-bit hevc file using hardware decoding?
After reading the post on May 12.
https://github.com/google/ExoPlayer/issues/3537
Is it possible to enable hardware decoding?

**Comment by ojw28** [comment]
I don't think Pie changes the last comment on the issue you reference. So no, I don't believe so.
