### ISSUE TITLE
how to use ClippingMediaSource to implement mid_roll?

### ISSUE THREAD

**Issue by Romantic-LiXuefeng** [google/ExoPlayer#4785]
I use ClippingMediaSource to split the content video into two content videos. and then add a mid_roll ad between them.   Sample code like this:
// pre_roll + content1 + mid_roll + content2
ClippingMediaSource content1 = 
                      new ClippingMediaSource(mediaSources[1], 0, 15000000);
ClippingMediaSource content2 =
                     new ClippingMediaSource(mediaSources[1], 15000000, C.TIME_END_OF_SOURCE);
 mediaSource = new ConcatenatingMediaSource(
                  mediaSources[0],      // pre_roll
                  content1,                    // content1[0 ~ 15s]
                  mediaSources[2],      // mid_roll
                  content2);                  // content2[15s ~ end]
But I can't get the duration of the content video before splitting .Is there any api can get the duration? If not, hope give me some advices to implement this function.

**Comment by tonihei** [comment]
You could sum up the durations of all content parts yourself. Listen to timeline updates (`eventListener.onTimelineChanged`) and wait until all the duration of all the content windows are known.

We are currently also working on a metadata retriever which can be used to load media information without playing the media. This will be part of a future release and is not yet available. As soon as this metadata retriever is available, you could also query the content (without clipping) to get its duration.

**Comment by tonihei** [comment]
Also note that inserting midrolls this way doesn't work well with our existing UI components. The preferred way to do this is still the custom `AdsLoader` as discussed in #4769.

**Comment by Romantic-LiXuefeng** [comment]
If the content video container formats are mp4 or mkv in the playlist, when call it's perpareChild()  it's first timeline with unkown duration.  it's duration become knowns until the video before it fully loaded and then load it's media information  . so i think wait until all the duration of all the content windows are known is not a right way.
