### ISSUE TITLE
Widevine-encrypted content playback failure on Amlogic STB with Android 6.0.1

### ISSUE THREAD

**Issue by okycelt** [google/ExoPlayer#4786]
### Issue description
We're having some issues playing Widevine-encrypted content on Amlogic STB with Android 6.0.1. When playing Widevine-encrypted DASH containing video with resolution higher than 720p, it shows the following error when processing the first license request response.

```
09-06 10:37:15.519 3760-4613/? I/WVCdm: CdmEngine::AddKey
09-06 10:37:15.694 3760-4613/? E/WVCdm: PolicyEngine::SetLicense Key ''
PolicyEngine::SetLicense Key '30303030303030303030303030303033'
PolicyEngine::SetLicense Key '30303030303030303030303030303032'
PolicyEngine::SetLicense Key '30303030303030303030303030303030'
PolicyEngine::SetLicense Key '30303030303030303030303030303037'
PolicyEngine::SetLicense Key '30303030303030303030303030303031'
PolicyEngine::SetLicense Key '30303030303030303030303030303034'
PolicyEngine::SetLicense Key '30303030303030303030303030303035'
PolicyEngine::SetLicense Key '30303030303030303030303030303036'
```

When trying to switch to video higher than 720p, eg. 1080p, the player crashes with following error.

```
09-06 10:37:25.673 7529-7529/com.google.android.exoplayer2.demo D/EventLogger: decoderInputFormatChanged [11.97, 9.56, window=0, period=0, video, id=4, mimeType=video/avc, bitrate=18320008, res=1920x856, fps=24.0]
09-06 10:37:25.674 7529-7529/com.google.android.exoplayer2.demo D/EventLogger: downstreamFormatChanged [11.97, 9.56, window=0, period=0, id=4, mimeType=video/avc, bitrate=18320008, res=1920x856, fps=24.0]
09-06 10:37:27.910 3760-7611/? D/AmlogicVideoDecoderAwesome: omx output size changed from 320*142 to 1920*856
09-06 10:37:27.912 3760-3760/? D/AmlogicVideoDecoderAwesome: get native buffer info NV:w:320,h:142..
09-06 10:37:27.912 3760-4614/? D/OmxVideoDecoder: getConfig 1001 0x700000f
getConfig 1004 nIndex 0x700000f
getConfig OMX_IndexConfigCommonOutputCrop pRect->nWidth=1920, pRect->nHeight=856
09-06 10:37:27.917 3760-4153/? E/WVCdm: height_ 856, security_level_ 3, 21-1b-a-bc
09-06 10:37:27.939 3760-4154/? E/WVCdm: height_ 856, security_level_ 3, 21-1b-f-ff
09-06 10:37:27.956 3760-3760/? E/WVCdm: height_ 856, security_level_ 3, 0-0-0-1
video return unknown_error
Decrypt error result in session sid2 during unencrypted block: 1
09-06 10:37:27.962 7529-7586/com.google.android.exoplayer2.demo E/ExoPlayerImplInternal: Playback error.
com.google.android.exoplayer2.ExoPlaybackException
at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:771)
at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:574)
at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:518)
at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:301)
at android.os.Handler.dispatchMessage(Handler.java:98)
at android.os.Looper.loop(Looper.java:148)
at android.os.HandlerThread.run(HandlerThread.java:61)
Caused by: android.media.MediaCodec$CryptoException: Unknown Error
at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:2292)
at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:762)
at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:574) 
at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:518) 
at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:301) 
at android.os.Handler.dispatchMessage(Handler.java:98) 
at android.os.Looper.loop(Looper.java:148) 
at android.os.HandlerThread.run(HandlerThread.java:61)
```

This is happening with both our content and Widevine test content present in ExoPlayer demo application.

We're not having this issue anywhere else except the Amlogic with Android 6.0.1. We have exactly the same implementation in mobile android application and it's playing on devices with Android 6.0.1. 

I realize this might be a device specific issue, we've already reported it to the STB vendor. But I would like to make sure that this error is not related to ExoPlayer.

### Reproduction steps
- Checkout r2.8.2 (There is more information in the log than r2.8.4)
- Play one of the Widevine encrypted videos, eg. Widevine DASH: MP4,H264 -> WV: Secure SD & HD (cenc,MP4,H264) using the ExoPlayer demo application
- Switch to a video track higher than 720p or wait for player to adapt to that bitrate.

### Link to test content
Content included in the ExoPlayer demo application will do.

### Version of ExoPlayer being used
2.8.2 (also happening on 2.7.3, 2.8.4)

### Device(s) and version(s) of Android being used
Amlogic STB with Android 6.0.1

### A full bug report captured from the device
Sent by email

**Comment by tonihei** [comment]
That sounds very much like a device-specific problem. 

Unfortunately, we don't have this device for available for testing. But it sounds as if we could add a workaround for the device which blacklists all formats higher than 720p. Maybe the device codec claims support for these formats where in fact it shouldn't. Can you provide us with the values of `Build.DEVICE` and `Build.MODEL` to add such a workaround?

**Comment by okycelt** [comment]
I'm not sure that blacklisting is the right way to handle this. 

Could the issue be related to the fact that the device is L3, not L1?

**Comment by tonihei** [comment]
Sorry for the late reply, I missed your answer.

If the device doesn't support L1, then this is probably the reason you can't play the stream with HD  resolutions. This actually means the we should automatically prevent playing encrypted HD streams on L3-only devices. However, this isn't true for all content and it's therefore difficult to do. 

Can you tell us the values of `Build.DEVICE` and `Build.MODEL` as requested above? That would allow us to provide a more targeted workaround if that's an issue with that device specifically.

**Comment by okycelt** [comment]
The stb vendor managed to solve this even on an L3 by a firmware update. I'm closing the issue for now.
