### ISSUE TITLE
 Video freezes in short periods  

### ISSUE THREAD

**Issue by erenbakac** [google/ExoPlayer#4787]
### Issue description
DRMed dash  streams are not played smoothly in Samsung Galaxy S6(SM-G920FQ). Streams are played well for a few seconds then it starts freezing in short periods . I attached bugreport file. Stream starts at 11:22 am in logs

### Reproduction steps
-

### Link to test content
Sorry. I cant provide a link . 

### Version of ExoPlayer being used
2.8.4

### Device(s) and version(s) of Android being used

Samsung Galaxy S6(SM-G920FQ) 7.0 

[bugreport-2018-09-07-11-23-27.zip](https://github.com/google/ExoPlayer/files/2360872/bugreport-2018-09-07-11-23-27.zip)

**Comment by tonihei** [comment]
Would it be possible to send a link with test content to dev.exoplayer@gmail.com with "Issue #4787" in the subject?

Besides that, I can't open the attached bug report as it fails to extract.

**Comment by erenbakac** [comment]
Sorry. I cant provide a link  for now. But i will try to get a link... I attached file again.


[bugreport-2018-09-07-11-23-27.zip](https://github.com/google/ExoPlayer/files/2365705/bugreport-2018-09-07-11-23-27.zip)

**Comment by tonihei** [comment]
Thanks, I can open the report now. However, I can't see anything suspicious. 

If you can't get the link for now, it would be great if you can add an event logger with `player.addAnalyticsListener(new EventLogger(trackSelector))` to get more detailed information about potential problems.

**Comment by tonihei** [comment]
Closing this issue due to lack of information. If you have something you can share, please reopen.
