### ISSUE TITLE
Disable seeking in Exoplayer

### ISSUE THREAD

**Issue by shubham-arora-18** [google/ExoPlayer#4789]
How do I prevent my exoplayer from seeking videos ?
How do I disable my scrubber ?

**Comment by tonihei** [comment]
You can disable to scrubbing functionality by calling `DefaultTimeBar.setEnabled(false)`. If you also want to hide the scrubber, you can set its size to zero by using:
```
app:scrubber_enabled_size="0dp"
app:scrubber_disabled_size="0dp"
app:scrubber_dragged_size="0dp"
```

**Comment by tonihei** [comment]
Closing, as I think the question has been answered. Feel free to reopen if not.
