### ISSUE TITLE
SRT - two or more cues/phrases at the same time aren't displayed

### ISSUE THREAD

**Issue by anonym24** [google/ExoPlayer#4794]
I often find subtitles which can contain more than one caption for the same time point (e.g., YouTube uses such captions very often)

Normally all players can display all those captions except ExoPlayer (MX Player, VLC, video players for Desktop)

![screenshot_3](https://user-images.githubusercontent.com/8851301/45257468-8eb9f380-b3af-11e8-883e-8e278aa2c61e.png)

![screenshot_2](https://user-images.githubusercontent.com/8851301/45257469-937ea780-b3af-11e8-83f5-55a92ebb775a.png)

ExoPlayer will show only first caption ("_they're almost in our garrison keep it_" in our case)

**SRT file source example**

```
1
00:00:18,560 --> 00:00:24,350
they're almost in our garrison keep it

2
00:00:21,960 --> 00:00:24,350
moving

3
00:00:45,410 --> 00:00:48,860
we can spot it

4
00:01:00,899 --> 00:01:08,399
in any case they were damn lucky to get

5
00:01:04,449 --> 00:01:08,399
you to the base alive and well mr. Okubo
```

**Comment by anonym24** [comment]
Also `getNextEventTimeIndex` method has to be modified to take indexes into account

![screenshot_4](https://user-images.githubusercontent.com/8851301/45258080-0e4cc000-b3ba-11e8-8dff-7ba8bb6b0150.png)

current time (timeUs) is 21961000 and we also display second caption with first caption at the time (so we at index 2)

but method will return index 1 (cause 24350000 at 1 is bigger than 21961000  at 2)

getNextEventTimeIndex has to be modified and return 2 in this case if check 21961000 that has bigger index than 24350000 at index 1

**Comment by anonym24** [comment]
and we can't even use `Arrays.binarySearch` method here 

> The array must be sorted (as by the sort(long[]) method) prior to making this call. If it is not sorted, the results are undefined.

**Comment by anonym24** [comment]
also this issue is the same as https://github.com/google/ExoPlayer/issues/4725

it doesn't matter if srt or ass subtitles, not ordered time of captions isn't supported in Cue/Subtitle ExoPlayer classes

**Comment by icbaker** [comment]
This should now work by default from media3 `1.4.0-alpha02` (and the same behaviour can be enabled in 1.3.0 with `DefaultMediaSourceFactory.experimentalParseSubtitlesDuringExtraction(true)`).
