### ISSUE TITLE
how can we set width , height and resize mode of simpleexoplayerview programmatically

### ISSUE THREAD

**Issue by pawaom** [google/ExoPlayer#4795]
I want to rotate simpleexoplayerview programmatically

i have used this in 

<com.google.android.exoplayer2.ui.SimpleExoPlayerView
                android:id="@+id/player_view"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                app:resize_mode="fixed_width"
                app:surface_type="texture_view"
                 />

but how can we do the same programmatically , (width, height)like we can do with a relativelayout , linearlayout

**Comment by ojw28** [comment]
It's just a normal view, so it should be possible to size it programmatically in the same way as you'd size any other view, at which point this isn't an ExoPlayer specific question.

If you have code that resizes any other view successfully, but doesn't resize `PlayerView`/`SimpleExoPlayerView`, please could you provide details of that. Else I'd suggest asking about sizing views programmatically somewhere less specific, such as on StackOverflow.

**Comment by pawaom** [comment]
I have posted a question on stackolverflow

https://stackoverflow.com/questions/52256396/fit-simpleexoplayerview-within-a-rotated-relative-layout

could you help

**Comment by ojw28** [comment]
Closing as out of scope for this issue tracker.
