### ISSUE TITLE
exoplayer play amr but can not seek 

### ISSUE THREAD

**Issue by chenqingru** [google/ExoPlayer#4797]
exoplayer plays amr but can not seek . when i use seek,it just restarts playing.
The version i use is 2.8.4

**Comment by ojw28** [comment]
Please see the [supported formats](http://google.github.io/ExoPlayer/supported-formats.html) page for some comments on seeking. We have enable seeking for some additional formats in the `dev-v2` branch though, so you should take a look at that. Some details on the improvements can be found in the [release notes](https://github.com/google/ExoPlayer/blob/dev-v2/RELEASENOTES.md) for 2.9.0, which will be released soon.

**Comment by chenqingru** [comment]
thanks
