### ISSUE TITLE
IllegasStateException in ExoPlaybackException

### ISSUE THREAD

**Issue by edikfuks** [google/ExoPlayer#480]
I am trying to play a video (HLS or MP4) on some devices such as Samsung Galaxy Note 4 and I am receiving the following exception, which results in the black screen:

05-21 15:43:39.421  12664-15417/com.creator E/Surface﹕ getSlotFromBufferLocked: unknown buffer: 0x9ef06470
05-21 15:43:39.421  12664-15417/com.creator E/Surface﹕ getSlotFromBufferLocked: unknown buffer: 0x9ef064e0
com.google.android.exoplayer.ExoPlaybackException: java.lang.IllegalStateException

I am using 1.3.1 Exoplayer version

Do you have any suggestions?
Thank you!

**Comment by ojw28** [comment]
Please provide more information. The last line that you paste is probably the first line of a full stack trace (and just the first line isn't useful).
