### ISSUE TITLE
Question: Analytics Listener Play Status + Detect Replay

### ISSUE THREAD

**Issue by ghost** [google/ExoPlayer#4802]
Using: Exoplayer 2.8.4

I am trying to implement some tracking from our analytics team, and there are two tracking events that I'm having trouble finding a way to track through the Analytics Listener.

Firstly, is it possible to detect replays if the video is set to loop when it completes? I tried to listen to:

```
override fun onPlayerStateChanged(
        eventTime: AnalyticsListener.EventTime?,
        playWhenReady: Boolean,
        playbackState: Int
    )
```

but it doesn't appear as though this event is fired with state ENDED (or anything for that matter) when the video replays.

Secondly, we would like to track how far into a video a user has watched at certain intervals (e.g. 1s, 5s, 10s, 30s). Is it possible to receive callbacks at certain points in the media's playback? As far as I can see, there's no way to receive callbacks once every second or so. I was thinking that I could implement this via a timer that runs alongside the video, but the problem with that approach is that the second the video has to spend time buffering or the user has seeked, the timer will no longer be accurate to the actual video position.

Thanks

**Comment by tonihei** [comment]
For looping ("replay"), you should receive a `onPositionDiscontinuity` event with reason `DISCONTINUITY_REASON_PERIOD_TRANSITION`.

For the regular timer, you can either:
- Call a Handler method in regular intervals (every x seconds in real time) and then check the current position with `player.getCurrentPosition()`.
- Or send messages at pre-defined media positions. You can do that by calling `player.createMessage(messageHandler).setPosition(position).setHandler(appHandler).send()`. You may also want to add `setDeleteAfterDelivery(false)` to resend the message even if the user seeks back.

**Comment by ghost** [comment]
The replay check you mentioned does work, so thank you.

I've done the below for play time tracking and it doesn't ever seem to fire back to the message target. In the below, `recordPlayTime` is never called.

```
private fun createMessageAtPosition(videoPlayer: SimpleExoPlayer, position: Int, handler: Handler) {
        val positionInMilliseconds = position.toLong() * 1000
        Log.v(TAG, "createMessageAtPosition, Adding message at ${positionInMilliseconds}ms")
        videoPlayer.createMessage { _: Int, _: Any -> recordPlayTime(position) }
            .setPosition(positionInMilliseconds)
            .setDeleteAfterDelivery(false)
            .setHandler(handler)
            .send()
    }

    private fun recordPlayTime(position: Int) {
        analyticsLogger.playTime(position)
    }
```

**Comment by tonihei** [comment]
I just tried and added the following lines to our demo app:
```
player
    .createMessage((type, payload) -> Log.d("POSITION", "message triggered at 5 seconds."))
    .setPosition(5000)
    .setDeleteAfterDelivery(false)
    .setHandler(new Handler())
    .send();
```
This works fine and logs the message every time I play past the 5 second mark. Can you check what is different in your app? Especially whether the position is actually in milliseconds.

**Comment by ghost** [comment]
For some reason, this started working after I forced the handler to and message to be created on the main thread. Unsure of why exactly that worked, since technically the UI should only be created on the main thread. 

Also worth noting: PlayerMessage.Target is missing nullity parameters and Kotlin incorrectly assumes these fields will be non-null, which caused a crash since payload is null

```
public interface Target {
    void handleMessage(int messageType, Object payload) throws ExoPlaybackException;
  }
```

Thank you for your help, closing.

**Comment by tonihei** [comment]
Thanks for noting the missing annotations! We'll add them to the PlayerMessage class.
