### ISSUE TITLE
Android and API version requirements for ExoPlayer v2

### ISSUE THREAD

**Issue by cwilcox-mersive** [google/ExoPlayer#4809]
I'm a Senior Software Engineer for Mersive Technologies. We are currently using ExoPlayer v1 for media playback in our Android-based hardware product. With the next revision of our product, we're running into a need to set the playback rate. My understanding is that this can be done via the StandaloneMediaClock for video playback, or via the MediaClock in AudioTrack (SetPlaybackParams). However, both of these require at least API 23 and thus Android 6. We're currently using Android 5.1.1 and API 22.

As a result, I'm looking into either upgrading our Android and API version, or moving to ExoPlayer v2, which appears to have the ability to set playback rate via the player interface. My question is what version of Android and API is required to run ExoPlayer v2?

**Comment by ojw28** [comment]
> My question is what version of Android and API is required to run ExoPlayer v2?

Unless you're doing something unusual, the API level requirements are the same as V1 (i.e. API level 16 for audio/video playback).
