### ISSUE TITLE
Player not able to display ASS subtitle.

### ISSUE THREAD

**Issue by sidkasundra** [google/ExoPlayer#4810]
Actually this player provide support for ASS file but when i try to render in video at that time subtitle not shown.
So i want to confirm that When EXOplayer Actually start supporting ASS subtitle

**Comment by ojw28** [comment]
You can answer this type of question by looking at the [release notes](https://github.com/google/ExoPlayer/blob/release-v2/RELEASENOTES.md):

> Captions: Initial support for SSA/ASS subtitles (#889).

In 2.5.0.

**Comment by sidkasundra** [comment]
Actually It support ASS subtitle by using set TYPE Text as SSA but when i run the application it convert side-by-side to just single subtitle.
Please help me to figure out this problem.

**Comment by ojw28** [comment]
That's a duplicate of https://github.com/google/ExoPlayer/issues/4725. Please use that issue for tracking.
