### ISSUE TITLE
Exoplayer 'Forward', 'Rewind' programmatically

### ISSUE THREAD

**Issue by vinitkr28** [google/ExoPlayer#4815]
I have exoplayer in my Android app and want to do 'Forward', 'Rewind' programmatically and these two buttons are not in the control view layout.

This two-button are outside exoplayer view, but in the screen and when user will click on "Forward" or "Rewind" it will work accordingly.

Some blogs given solution but all are for control view, for example:

`app:fastforward_increment="30000"`
`app:rewind_increment="30000"`

But in my case button are completely outside of the player view.

The same question was asked earlier [here](https://stackoverflow.com/questions/44223575/how-to-add-listener-for-next-previous-rewind-and-forward-in-exoplayer), but there was no proper solution.

Tried following code but not getting any impact:

`//switch case onClick listener for 'Forward' and 'Rewind'`
`case R.id.text_view_rewind:`
   ` simpleExoPlayerView.setRewindIncrementMs(5000);`
    `break;`
`case R.id.text_view_forward:`
     `simpleExoPlayerView.setFastForwardIncrementMs(5000);`
     `break;`

**Comment by vinitkr28** [comment]
Following is the screenshot of my app and 'Rewind', 'Forward' is outside the player view.
When user will click on 'Rewind' then track position will rewind to 10 or 5 second and for 'Forward' trackposition will forward to 10 or 5 second.

![capture](https://user-images.githubusercontent.com/12389479/45548310-79c2e180-b841-11e8-82c0-c471f2c983cf.JPG)

**Comment by ojw28** [comment]
If you want to change the player position, you should be calling methods directly on the player (i.e. one of the `player.seekTo` methods.
