### ISSUE TITLE
Listener for Video output

### ISSUE THREAD

**Issue by raihanabbas232** [google/ExoPlayer#4816]
Hi, I am using ExoPlayer for a TV app which downloads the mp4 videos and plays them one after other like a playlist. I am setting the source of next video in on End event of the first video.
It has been observed that black screen appears during video playback with audio playing in the background.
Does ExoPlayer support any functionality which can allow us to monitor video output?
I am looking forward to re-instantiating the view of ExoPlayer on a black screen occurrence.
I am using onSurfaceTextureUpdated(SurfaceTexture surface) for this which does not seem to be a good workaround.
### Reproduction steps
Can reproduce anytime
### Link to test content
I believe the issue occur if some corrupt mp4 is given to the ExoPlayer.

### Version of ExoPlayer being used
v2.8.4
### Device(s) and version(s) of Android being used
mecool octa core TV Box
CPU: Amlogic S912 64 bit

### A full bug report captured from the device
Not available yet. I am trying to reproduce it so that I can get Logcat details.

**Comment by ojw28** [comment]
Closing due to lack of information.
