### ISSUE TITLE
How to implement offline save video in .exo format and only playable by my app(like youtube app) 

### ISSUE THREAD

**Issue by sudhirs745** [google/ExoPlayer#4821]
i am working on an android app which can download the video from server and store it in SD card in .exo format and plays it while the app is in offline mode. but i want the add one more functionality to my app.(like youtube app).

**Comment by ojw28** [comment]
Please can you try and explain what you're trying to do more clearly? I don't understand the question.

**Comment by sudhirs745** [comment]
I'm working on an android app which can download the video from server and store it in SD card. and plays it while the app is in offline mode. but i want the add one more functionality to my app. now the videos downloaded by app can be played by any video player in the device. But i want to restrict that functionality.so the videos downloaded by my app can only playable by my app(like youtube app).

I'm totally new to this functionality .. any ideas and approaches to achieve this ?

**Comment by erdemguven** [comment]
To encrypt cached media files (exo files) you need to use AesCipherDataSink and AesCipherDataSource to encrypt and decrypt while you create your CacheDataSource. For an example you can check com.google.android.exoplayer2.upstream.cache.CacheDataSourceTest2#buildCacheDataSource code.
