### ISSUE TITLE
DefaultTrackselector doesn't get subtitle information

### ISSUE THREAD

**Issue by hereisclient** [google/ExoPlayer#4824]
Before filing an issue:
-----------------------
- Search existing issues, including issues that are closed.

### Issue description
hi i'm using exoplayer very well by now.
but i found special issue while i was developing about subtitle
that issue is i can't get subtitle information from defaulttrackselector.

i checked onTracksChanged event:

here is the result

[EventLogger] onTracksChanged()[350] >>   Renderer:None [
    [EventLogger] onTracksChanged()[352] >>     Group:0 [
 [EventLogger] onTracksChanged()[358] >>       		[ ] Track:0, id=0, mimeType=null, bitrate=1145, language=ger, supported=NO
 [EventLogger] onTracksChanged()[364] >>     	]
 [EventLogger] onTracksChanged()[352] >>     	Group:1 [
 [EventLogger] onTracksChanged()[358] >>       		[ ] Track:1, id=0, mimeType=null, bitrate=1170, language=ger, supported=NO
 [EventLogger] onTracksChanged()[364] >>     	]
    [EventLogger] onTracksChanged()[352] >>     Group:2 [
 [EventLogger] onTracksChanged()[358] >>       		[ ] Track:2, id=0, mimeType=null, bitrate=1155, language=eng, supported=NO
    [EventLogger] onTracksChanged()[364] >>     ]
 [EventLogger] onTracksChanged()[366] >>   	]

RendererType is None but i expected rendererType is TEXT
and  actually this manifest file has two subtitles infomation.

so there is nothing i can just wait to reply about this 

my dev env

transferprotocol  : smooth streaming
subtitle location :  in manifest file 

### Device(s) and version(s) of Android being used
device : xiomi mibox 3
android version : 8.0

### Link to test content
i will send you link with issue number

### Version of ExoPlayer being used
exoplayer version: 2.8.3

**Comment by ojw28** [comment]
The problem is that we don't handle `FourCC="DFXP"`. We expect `FourCC="TTML"`. It's easy to check for the `DFXP` too, so we'll do that.
