### ISSUE TITLE
App being killed because of high CPU usage

### ISSUE THREAD

**Issue by gbirk** [google/ExoPlayer#4829]
My app is being constantly killed after some time of playback. ExoPlayer is running within a foreground service. A WifiLock and a PowerLock are being held. I already confirmed using **adb shell dumpsys** that the service is marked as foreground and both locks are active. For the ExoPlayer setup I'm using a **DefaultLoadControl**, setting the buffer duration in MS to 
**minBufferMs** as 2 * 60 * 1000 and **maxBufferMs** as 6 * 60 * 1000. Also using a **DefaultTrackSelector**, **DefaultRenderersFactory**, **DefaultDataSourceFactory** with a **DefaultBandwidthMeter** and a **ConcatenatingMediaSource** for the playlist. I've never had this problem before while using MediaPlayer. The image below reflects the CPU usage for ExoPlayerImplInternal and MediaCodec, and you can see that both are responsible for the high CPU usage.

This is being tested on a Pixel 2 running Android 9 and ExoPlayer **v2.8.3**, but it seems to happen on other devices as well.

![screen shot 2018-09-17 at 3 00 04 pm](https://user-images.githubusercontent.com/23461430/45644369-99e5e100-ba8b-11e8-99d7-fe84f7629759.png)

This is the log message received when the app is being killed: **09-14 13:27:42.449 1155-1201/? I/ActivityManager: Killing 30863:[package.name]/[pid] (adj 700): excessive cpu 32590 during 300128 dur=653049 limit=10**

Am I missing any configuration?

**Comment by andrewlewis** [comment]
Please could you take a full bug report (`adb bugreport`) and attach it here or send it to `dev.exoplayer@gmail.com`?

**Comment by andrewlewis** [comment]
Looks like the process is getting killed in [ActivityManagerService.java](https://android.googlesource.com/platform/frameworks/base/+/97995da6e1d40a053402cc120944e3738a18d1a0/services/core/java/com/android/server/am/ActivityManagerService.java#24367), but this should only happen for processes that have a state >= [`ActivityManager.PROCESS_STATE_HOME`](https://android.googlesource.com/platform/frameworks/base/+/97995da6e1d40a053402cc120944e3738a18d1a0/core/java/android/app/ActivityManager.java#531). This suggests that the process isn't actually running a foreground service at the time when it's killed.

I think a bug report taken just before the app gets killed will probably help figure out what's going on, and it might also be worth checking your code for starting the service.

**Comment by gbirk** [comment]
I'll work on the logs and double check the service state when the app is being killed. Thanks!

**Comment by gbirk** [comment]
Looks like you were right andrewlewis. There was a specific scenario where stopForeground() was being called, resulting on the app being killed when in BG. Closing this.
