### ISSUE TITLE
Change time exo_rew and exo_ffwd

### ISSUE THREAD

**Issue by Angelk90** [google/ExoPlayer#4830]
### Issue description
Is there any way to change the time of exo_rew and exo_ffwd?

exo_rew allows you to go back 5 sec
exo_ffwd allows you to go ahead of 15 sec

### Version of ExoPlayer being used
`com.google.android.exoplayer:exoplayer:2.8.1
`
### Device(s) and version(s) of Android being used
Android 7

**Comment by andrewlewis** [comment]
The `rewind_increment` and `fastforward_increment` attributes on `PlayerControlView` (and `PlayerView`) let you set the duration of the seek applied when tapping those buttons.
