### ISSUE TITLE
Make DefaultTrackSelector prefer more efficient video codecs (everything else being equal)

### ISSUE THREAD

**Issue by ojw28** [google/ExoPlayer#4835]
If there are multiple video `TrackGroup`s that are roughly equivalent except for the codec used, `DefaultTrackSelector` should prefer to select the `TrackGroup` that uses the most efficient codec*.

* An exception would be if a less efficient codec appears to have a hardware decoder, where-as the more efficient codec does not.

**Comment by manishPatwari** [comment]
@ojw28 Hello, Any update on this?

**Comment by juechemparathy** [comment]
@ojw28  - Any updates on this? Thanks.

**Comment by ScottPierce** [comment]
Any update on this?

**Comment by kevinscroggins-youi** [comment]
Should in theory be able to work around this by hooking up the setPreferredAudio/VideoMimeType APIs on the DefaultTrackSelector.
https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/trackselection/DefaultTrackSelector.ParametersBuilder.html#setPreferredVideoMimeType(java.lang.String)
