### ISSUE TITLE
VP9 ext crash from libvpx 1.7.0

### ISSUE THREAD

**Issue by blueslabs** [google/ExoPlayer#4836]
It seems libvpx 1.7.0 has more neon code added. There was error when I run config. By adding -mfloat-abi=softfp -mfpu=neon to cflag, I have managed to get the so file compiled. However, after the first frame is decoded, the sample app always crashes with: 

com.google.android.exoplayer2.demo A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x10 in tid 18160 (Thread-1825)

My ExoPlayer version is 2.8.2. The working libvpx is 1.6.2, which is from Jan 2017.

**Comment by andrewlewis** [comment]
I think the errors that occur during configuration might not actually be problematic. What do you see if you just ignore the errors during configuration? I tried building with libvpx 1.7.0, ignoring the errors and playing a video with the vp9 extension and it worked.

**Comment by blueslabs** [comment]
Thanks! Did a clean build, it works now. -mfloat-abi=softfp -mfpu=neon is actually only required for the current master, otherwise build can fail. 1.7.0 can build without this.
