### ISSUE TITLE
Glitches with certain videos on Pixel 2

### ISSUE THREAD

**Issue by sergeich** [google/ExoPlayer#4837]
### Issue description
I experience strange glitches on my Pixel 2 (and only Pixel 2) while playing the video with TextureView rendering.
Everything is ok with `surface_type="surface_view"`, but SurfaceView doesn't meet our needs.
Some of the videos is working as expected, some -- with glitches. 
Tested on the demo app with the same result.

![Illustration](https://i.imgur.com/mNMLKTy.png)

### Reproduction steps
Set surface type of PlayerView to `texture_view` and try to play one of test videos
Sent the patch with changes to dev.exoplayer@gmail.com

### Link to test content
Sent to dev.exoplayer@gmail.com

### Version of ExoPlayer being used
2.8.4
Also tested on current dev-v2 branch with the same result

### Device(s) and version(s) of Android being used
Pixel 2, Android 9
AFAIK Android 8 is also affected.
Couldn't reproduce the issue on other devices, tested on Nexus 5, Samsung Galaxy Note 8 and some others.

### A full bug report captured from the device
Sent to dev.exoplayer@gmail.com

**Comment by andrewlewis** [comment]
Do you find that particular video resolutions are broken while others work? The resolution of the first provided test stream is 448 by 252 pixels (height is not a multiple of 16, which can be problematic).

I've filed [internal: b/116190096] to ask the relevant team to take a look. Thanks.

**Comment by sergeich** [comment]
>Do you find that particular video resolutions are broken while others work?

Yes, most of the working videos has multiple of 16 height (1080, 720, 480). But some of them has resolution 640x360 and works too. `360 / 16 = 22.5`. So I don't know could it be the reason or not.

**Comment by andrewlewis** [comment]
According to the internal bug Qualcomm merged a fix for this issue though it's not clear exactly which devices were included. So this may be fixed for devices that are still receiving updates.
