### ISSUE TITLE
Unable to play HLS on Nexus 7

### ISSUE THREAD

**Issue by rdgRmCore** [google/ExoPlayer#484]
I just pulled the latest master yesterday: commit 888d9db3e92bf4605c7be5cf61da52db0c75bdee

I am running on a Nexus 7 Android Version 4.4.4 Kernel Version 3.1.10-g1e42d16

I get the following error when trying to play back the Apple master playlist HLS sample:

<pre>
05-22 09:20:53.770    2161-2161/com.google.android.exoplayer.demo I/dalvikvm﹕ Could not find method android.media.MediaCodecInfo$CodecCapabilities.getVideoCapabilities, referenced from method com.google.android.exoplayer.MediaCodecUtil.isSizeAndRateSupportedV21
05-22 09:20:53.770    2161-2161/com.google.android.exoplayer.demo W/dalvikvm﹕ VFY: unable to resolve virtual method 87: Landroid/media/MediaCodecInfo$CodecCapabilities;.getVideoCapabilities ()Landroid/media/MediaCodecInfo$VideoCapabilities;
05-22 09:20:53.770    2161-2161/com.google.android.exoplayer.demo D/dalvikvm﹕ VFY: replacing opcode 0x6e at 0x0019
05-22 09:20:53.780    2161-2161/com.google.android.exoplayer.demo I/OMXClient﹕ Using client-side OMX mux.
05-22 09:20:54.000    2161-2161/com.google.android.exoplayer.demo E/OMXNodeInstance﹕ OMX_GetExtensionIndex OMX.google.android.index.storeMetaDataInBuffers failed
05-22 09:20:54.000    2161-2161/com.google.android.exoplayer.demo W/OMXNodeInstance﹕ OMX_GetExtensionIndex OMX.google.android.index.prepareForAdaptivePlayback failed
05-22 09:20:54.090    2161-2161/com.google.android.exoplayer.demo D/libEGL﹕ loaded /system/lib/egl/libEGL_tegra.so
05-22 09:20:54.120    2161-2161/com.google.android.exoplayer.demo D/libEGL﹕ loaded /system/lib/egl/libGLESv1_CM_tegra.so
05-22 09:20:54.140    2161-2161/com.google.android.exoplayer.demo D/libEGL﹕ loaded /system/lib/egl/libGLESv2_tegra.so
05-22 09:20:54.190    2161-2161/com.google.android.exoplayer.demo D/OpenGLRenderer﹕ Enabling debug mode 0
05-22 09:21:11.050    2161-2161/com.google.android.exoplayer.demo I/dalvikvm﹕ Could not find method android.view.accessibility.CaptioningManager$CaptionStyle.hasForegroundColor, referenced from method com.google.android.exoplayer.text.CaptionStyleCompat.createFromCaptionStyleV21
05-22 09:21:11.050    2161-2161/com.google.android.exoplayer.demo W/dalvikvm﹕ VFY: unable to resolve virtual method 254: Landroid/view/accessibility/CaptioningManager$CaptionStyle;.hasForegroundColor ()Z
05-22 09:21:11.050    2161-2161/com.google.android.exoplayer.demo D/dalvikvm﹕ VFY: replacing opcode 0x6e at 0x0002
05-22 09:21:11.050    2161-2161/com.google.android.exoplayer.demo D/dalvikvm﹕ DexOpt: couldn't find field Landroid/view/accessibility/CaptioningManager$CaptionStyle;.windowColor
05-22 09:21:11.060    2161-2161/com.google.android.exoplayer.demo I/dalvikvm﹕ DexOpt: unable to optimize instance field ref 0x0026 at 0x18 in Lcom/google/android/exoplayer/text/CaptionStyleCompat;.createFromCaptionStyleV21
05-22 09:21:11.120    2161-2161/com.google.android.exoplayer.demo I/ExoPlayerImpl﹕ Init 1.3.2
05-22 09:21:11.120    2161-2161/com.google.android.exoplayer.demo D/EventLogger﹕ start [0]
05-22 09:21:11.120    2161-2161/com.google.android.exoplayer.demo D/EventLogger﹕ state [0.00, false, P]
05-22 09:21:11.130    2161-2161/com.google.android.exoplayer.demo D/EventLogger﹕ state [0.01, true, P]
05-22 09:21:11.160    2161-2426/com.google.android.exoplayer.demo D/dalvikvm﹕ GC_FOR_ALLOC freed 174K, 3% free 7944K/8156K, paused 17ms, total 21ms
05-22 09:21:11.460    2161-2161/com.google.android.exoplayer.demo E/EventLogger﹕ internalError [0.34, rendererInitError]
05-22 09:21:11.480    2161-2161/com.google.android.exoplayer.demo E/EventLogger﹕ playerFailed [0.36]
05-22 09:21:11.480    2161-2161/com.google.android.exoplayer.demo D/EventLogger﹕ state [0.36, true, I]
</pre>

**Comment by Ood-Tsen** [comment]
The method "isSizeAndRateSupportedV21" is for api level 21.
But target device is api level 19 (Android 4.4.4).

**Comment by ojw28** [comment]
I don't think the message about `isSizeAndRateSupportedV21` is relevant. It's just an informational message that the method wasn't found. It doesn't indicate that the library actually tried calling the method (which is when it would be a problem - you'd get a proper full stack trace if that were to happen).

**Comment by rdgRmCore** [comment]
Hello,

Thanks for looking at this. I have done some more testing and found the following.

The internalError and playerFailed messages were caused by turning the wifi off. 

The hls playback works when there is a good network connection.

Sorry for any confusion. (I was testing on multiple devices in the morning and did not realize that the Nexus had the wifi off until later in the afternoon. The Nexus was being used to test a usb to ethernet adapter.)

**Comment by ojw28** [comment]
That sounds working as intended in that case. When the player fails in this scenario, you should be able to figure out that the failure was due to network connectivity (e.g. by looking at the cause of the playback failure exception). You can/should then show the user a corresponding error message.
