### ISSUE TITLE
Exoplayer ima extension does not play type="audio/mp3" ad url

### ISSUE THREAD

**Issue by mustafasevgi** [google/ExoPlayer#4840]
Hello, 

Our vast url has different mime type  like "audio/mp3", "audio/mpeg". 

If media file type="audio/mpeg", ad play normally. if media file type="audio/mp3", ad can not play and exoplayer throw excaption:
 > "error = [com.google.android.exoplayer2.source.ads.AdsMediaSource$AdLoadException: java.io.IOException: Failed to load ad group 0], wasCanceled = [true]"

vast response:

```
<MediaFiles>
<MediaFile width="1" height="1" bitrate="400" type="audio/mp3" delivery="progressive">
<![CDATA[
http://res.reklamport.com/2018/9/14/Ford_Transit.mp3
]]>
</MediaFile>
</MediaFiles>
```

When i replace vast xml response type="audio/mp3" to "audio/mpeg"  with charles tool, it can play.

What is the problem if type="audio/mp3"?

exoplayer version: 2.8.4
exoplayer ima extension version: 2.8.4

device: Huawei Nexus 6P
android os version:8.1.0

Can you help please,
Thanks

**Comment by andrewlewis** [comment]
The IMA SDK appears to support the following media MIME types:
- DASH: 'application/dash+xml'
- HLS: 'application/x-mpegURL'
- MP4: 'video/mp4'
- MPEG: 'video/mpeg'
- Ogg: 'video/ogg'
- 3GPP: 'video/3gpp'
- WebM: 'video/webm'
- MP3: 'audio/mpeg'
- MP4 audio: 'audio/mp4'

So you'll need to use one of those for IMA to recognize the format.
