### ISSUE TITLE
Allow to (easily) disable audio pass-through in MediaCodecAudioRenderer

### ISSUE THREAD

**Issue by goffioul** [google/ExoPlayer#4841]
I'm facing a scenario where I would like to disable the automatic audio pass-through in MediaCodecAudioRenderer without having to override a bunch of components. But it seems there's no flag that I can toggle to turn off this behavior.

My scenario is running the ExoPlayer demo app on a low-end set-top box running Android 7.1.2 (not Android TV). Playing video with AC3 content creates various problems.

1) Android will force-declare support for AC3 encoding on HDMI output *by default*, since this change:
https://android.googlesource.com/platform/frameworks/av/+/07ac114%5E%21/#F0
and that's true even if the connected HDMI display does not support AC3 audio (which is my case). It doesn't seem like this default behavior can be disabled with a simple platform overlay, and this setting is only exposed to the user in app TvSettings, which is not present on my device. Also, the fact that this auto-enforce-AC3 is by default can easily be overlooked by OEM.

2) Even if the HDMI display supports AC3 encoding, the audio volume cannot be controlled anymore using the regular Android volume (e.g. in my case, the remote provided with the device). I'm working in healthcare environment, and it's not really an option to hand over 2 remotes to patients and telling them that sometimes they may have to use remote A or remote B, depending on the content being played.

3) Even if you manage to solve the remote problem, it seems ExoPlayer does not take the declared max number of channels into account to decide whether pass-through is possible. So when I connect my device to a TV that supports AC3 stereo-only, I can play video containing stereo AC3, but playing video containing 5.1 AC3 leads to an exception:

```
09-19 16:08:24.732  4109  4109 W APM_AudioPolicyManager: getOutput() could not find output for stream 3, samplingRate 48000,format 150994944, channels 3f, flags 1
09-19 16:08:24.732  9182  9201 E AudioTrack: Could not get audio output for session 9, stream type -1, usage 1, sample rate 48000, format 0x9000000, channel mask 0x3f, flags 0x1
09-19 16:08:24.732  9182  9201 E AudioTrack-JNI: Error -22 initializing AudioTrack
09-19 16:08:24.732  9182  9201 E android.media.AudioTrack: Error code -20 when initializing AudioTrack.
09-19 16:08:24.734  9182  9201 E ExoPlayerImplInternal: Playback error.
09-19 16:08:24.734  9182  9201 E ExoPlayerImplInternal: com.google.android.exoplayer2.ExoPlaybackException
09-19 16:08:24.734  9182  9201 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(MediaCodecAudioRenderer.java:467)
09-19 16:08:24.734  9182  9201 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1068)
09-19 16:08:24.734  9182  9201 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:567)
09-19 16:08:24.734  9182  9201 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:522)
09-19 16:08:24.734  9182  9201 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:305)
09-19 16:08:24.734  9182  9201 E ExoPlayerImplInternal: 	at android.os.Handler.dispatchMessage(Handler.java:98)
09-19 16:08:24.734  9182  9201 E ExoPlayerImplInternal: 	at android.os.Looper.loop(Looper.java:154)
09-19 16:08:24.734  9182  9201 E ExoPlayerImplInternal: 	at android.os.HandlerThread.run(HandlerThread.java:61)
09-19 16:08:24.734  9182  9201 E ExoPlayerImplInternal: Caused by: com.google.android.exoplayer2.audio.AudioSink$InitializationException: AudioTrack init failed: 0, Config(48000, 252, 20480)
09-19 16:08:24.734  9182  9201 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.audio.DefaultAudioSink.initializeAudioTrack(DefaultAudioSink.java:1220)
09-19 16:08:24.734  9182  9201 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.audio.DefaultAudioSink.initialize(DefaultAudioSink.java:517)
09-19 16:08:24.734  9182  9201 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.audio.DefaultAudioSink.handleBuffer(DefaultAudioSink.java:574)
09-19 16:08:24.734  9182  9201 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(MediaCodecAudioRenderer.java:461)
09-19 16:08:24.734  9182  9201 E ExoPlayerImplInternal: 	... 7 more
```

**Comment by andrewlewis** [comment]
You can force ExoPlayer not to use passthrough support advertised by the platform by passing `AudioCapabilities.DEFAULT_AUDIO_CAPABILITIES` (or `null`) when constructing `MediaCodecAudioRenderer`. Please try that and let me know if there are any issues.

As you've noted we should be checking the channel count. I'll use #4690 to track that. Thanks!

**Comment by goffioul** [comment]
But I'm not constructing `MediaCodecAudioRenderer`, `DefaultRenderersFactory` does. To implement your suggestion, I need to create my own renderers factory, override `buildAudioRenderers` and insert a (second) `MediaCodecAudioRenderer` in the returned array, making sure to take into account `extensionRendererMode`. Or is there an easier way?

**Comment by andrewlewis** [comment]
If you need extension renderers, that sounds right. If not you can get away with overriding the method and just returning a `MediaCodecAudioRenderer` (without calling the super implementation).

Note: if you're actually trying to play an AC3 stream using extension renderers I think you can simply set the factory to prefer extension renderers. They will be used in preference to MediaCodecAudioRenderer.

**Comment by goffioul** [comment]
I need the extension renderers. The app is targeted at multiple devices, some of which have an AC3 decoder (or MP2 for that matters), others don't. The app should prefer to use the platform codecs when available; hence the suggestion to prefer the extension renderers is not really practical (or I'd need to make that setting platform-dependent). Thanks for the information anyway.
