### ISSUE TITLE
Change the color of text and background and the subtitle font

### ISSUE THREAD

**Issue by Angelk90** [google/ExoPlayer#4842]
### Issue description
Is there a way to change the color of text and background and the subtitle font?
I tried on github, internet, stackoverflow, I could not find answers.

### Version of ExoPlayer being used
`com.google.android.exoplayer:exoplayer:2.8.1
`
### Device(s) and version(s) of Android being used
Android 7

**Comment by zsmatyas** [comment]
Isn't exoPlayer rendering with the font returned by the [CaptioningManager](https://developer.android.com/reference/android/view/accessibility/CaptioningManager) ? In that case, you can set the font in the device settings and it influences all applications at the same time. 
Note: there are no setters for the device fonts, they are only adjustable from the settings.

If you do not want to use the device fonts, you can set something here:
https://github.com/google/ExoPlayer/blob/8cbcfd669db0595ad8c84425b7a99f62d55e3569/library/ui/src/main/java/com/google/android/exoplayer2/ui/SubtitleView.java#L325

**Comment by andrewlewis** [comment]
Yes, `PlayerView` will use the style/size from the `CaptioningManager` to initialize its `SubtitleView`'s output style. `SubtitleView` also has various methods for customizing how subtitles get rendered, including `setStyle` and `setFractionalTextSize`.

**Comment by Angelk90** [comment]
@zsmatyas , @andrewlewis :
I use an app, which allows you to customize the subtitles, I realized that when I changed them, they were also changed those that were shown on exoplayer.

Here are some pictures of what you can do, that's what I would like to do.

![](https://i.imgur.com/AbcEqeM.jpg)

![](https://i.imgur.com/ystcYfB.jpg)

![](https://i.imgur.com/6ULt5Bn.jpg)

![](https://i.imgur.com/FdXG5zw.jpg)


To set up subtitles, I simply use this:

```
Format textFormat = Format.createTextSampleFormat(null, MimeTypes.APPLICATION_SUBRIP, null, 
Format.NO_VALUE, Format.NO_VALUE, "en", null, Format.OFFSET_SAMPLE_RELATIVE);

MediaSource textMediaSource = new SingleSampleMediaSource.Factory(dataSourceFactory)
.createMediaSource(Uri.parse(String.valueOf(sub)), textFormat, C.TIME_UNSET);

videoSource = new MergingMediaSource(videoSource, textMediaSource);
```

For example, SubtitleView does not use it in my code.

Some advice, I would like to realize what you see in the images.

**Comment by andrewlewis** [comment]
If you're using `PlayerView` you should be able to use `findViewById(R.id.exo_subtitles)` to get the `SubtitleView` instance, then use the methods I mentioned above to customize rendering.

**Comment by ojw28** [comment]
If you're using `PlayerView` you can just use [`getSubtitleView`](https://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/ui/PlayerView.html#getSubtitleView--) to get the `SubtitleView` instance ;).
