### ISSUE TITLE
How to seperate default time bar

### ISSUE THREAD

**Issue by hafiz013** [google/ExoPlayer#4843]
hi there, i am looking for default time bar separated even though i make media source ConcatenatingMediaSource. For example, like play music list supposed current bar show only time of current music play instead of combine them all together in on line timeba.

**Comment by andrewlewis** [comment]
The default behavior is to show each song separately (one at a time). If you call `playerView.setShowMultiWindowTimeBar(true)` then the time bar will show the concatenation of the songs as if they were one long track, but see also #4727 for limitations of this.

**Comment by hafiz013** [comment]
so in that case how to play next media source programmatically in stead of next button from controller.

**Comment by andrewlewis** [comment]
Is this the same as #4863 or a different question? If you pass the player a concatenation it should advance automatically from one item to the next.

**Comment by hafiz013** [comment]
different question.playerView.setShowMultiWindowTimeBar(false) make time bar separated media source even though already concatenation. thank for info.
