### ISSUE TITLE
subtitleview is not shown.

### ISSUE THREAD

**Issue by hereisclient** [google/ExoPlayer#4849]
### Issue description
now i'm trying to show subtitle on my application.
but i can't see subtitle on exoplayer.
i guess my layout affects subtitle.
my layout is based on exoplayer demo app.
here is my layout and i just added SurfaceView in orignal layout.
and i added below java code.

    mIcsSurfaceView = (SurfaceView) findViewById(R.id.surface_ics);
    mIcsSurfaceView.setZOrderMediaOverlay(true);
    mIcsSurfaceHolder = mIcsSurfaceView.getHolder();
    mIcsSurfaceHolder.setFormat(PixelFormat.RGBA_8888);

because my application needs transparent surfaceview on exoplayer.
my main goal is that my application must draw image on exoplayer showing subtitle.
but i tried it in many ways but  failed .

you know, exoplayer can show subtitle without surfaceview but my cases, everythings is ok except subtitle can't be seen.

i really want know how to show subtitle in my case.

exo_player_view.xml

<?xml version="1.0" encoding="UTF-8"?>
    <FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
        android:id="@+id/root"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <com.google.android.exoplayer2.ui.PlayerView
            android:id="@+id/player_view"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            />
       <SurfaceView
        android:id="@+id/surface_ics"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        />
        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:background="#88000000"
            android:orientation="vertical">

            <TextView android:id="@+id/debug_text_view"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:paddingLeft="4dp"
                android:paddingRight="4dp"
                android:textSize="10sp"
                tools:ignore="SmallSp"/>
            <LinearLayout android:id="@+id/controls_root"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:orientation="horizontal"
                android:visibility="gone"/>
            </LinearLayout>
       </LinearLayout>
</FrameLayout>

### Version of ExoPlayer being used
exoplayer : 2.8.3

### Device(s) and version(s) of Android being used
os       :  8.0
device : mibox3

**Comment by andrewlewis** [comment]
> because my application needs transparent surfaceview on exoplayer.

I don't think `SurfaceView` can be made transparent. You should probably be using `TextureView` instead if you need this behavior.

Subtitles are shown with the ExoPlayer demo app, so using that as a starting point it should be possible to figure out which part of the changes you've made caused subtitles not to show up.
