### ISSUE TITLE
some playbacks are jumpy when it changes speed of playback

### ISSUE THREAD

**Issue by KazumiHARADA** [google/ExoPlayer#4851]
### Issue description
Implementing a feature of slow and fast playback with Playback Parameters.class,
there are some videos which are very jumpy.
As a result of our comfirming, it seems to be occurred only with DRM protected contents.

### Reproduction steps
Please let you modify following class and json file on the ExoPlayer demo project.

ExoPlayer-release-v2/demos/main/src/main/java/com/google/android/exoplayer2/demo/PlayerActivity.java > initializePlayer
```
player =
    ExoPlayerFactory.newSimpleInstance(renderersFactory, trackSelector, drmSessionManager);
player.addListener(new PlayerEventListener());
player.setPlayWhenReady(startAutoPlay);
player.addAnalyticsListener(new EventLogger(trackSelector));
player.setPlaybackParameters(new PlaybackParameters(1.5f,1.5f)); // <--- I added this code!!
playerView.setPlayer(player);
playerView.setPlaybackPreparer(this);
debugViewHelper = new DebugTextViewHelper(player, debugTextView);
debugViewHelper.start();
```

ExoPlayer-release-v2/demos/main/src/main/assets/media.exolist.json
```
{
    "name": "Widevine DASH Policy Tests (GTS)",
    "samples": [
      { // I added this sample!!
        "name": "WV: Big Buck Bunny",
        "uri": "http://amssamples.streaming.mediaservices.windows.net/622b189f-ec39-43f2-93a2-201ac4e31ce1/BigBuckBunny.ism/manifest(format=mpd-time-csf).mpd",
        "drm_scheme": "widevine",
        "drm_license_url": "https://amssamples.keydelivery.mediaservices.windows.net/Widevine/?KID=1ab45440-532c-4399-94dc-5c5ad9584bac"
      },
      {
        "name": "WV: HDCP not specified",
        "uri": "https://storage.googleapis.com/wvmedia/cenc/h264/tears/tears.mpd",
        "drm_scheme": "widevine",
        "drm_license_url": "https://proxy.uat.widevine.com/proxy?video_id=d286538032258a1c&provider=widevine_test"
      },
      ...
  }
```

### Link to test content

```
"uri": "http://amssamples.streaming.mediaservices.windows.net/622b189f-ec39-43f2-93a2-201ac4e31ce1/BigBuckBunny.ism/manifest(format=mpd-time-csf).mpd",
"drm_scheme": "widevine",
"drm_license_url": "https://amssamples.keydelivery.mediaservices.windows.net/Widevine/?KID=1ab45440-532c-4399-94dc-5c5ad9584bac"
```
### Version of ExoPlayer being used
2.6.1

### Device(s) and version(s) of Android being used
N/A
we can reproduce all having devices.

### A full bug report captured from the device
The issue is not a crash.  If you want to logcat data, we will attach immediately.

**Comment by andrewlewis** [comment]
I think we've seen issues before where playing protected content increased the time cost of decoding substantially compared to clear content, and could result in dropped frames. When playback is jumpy do you see the dropped frame counter labeled "db" at the top of the screen in the demo app increasing?

It would be useful to see logcat with logging from the demo app if you have it available. Thanks.

**Comment by KazumiHARADA** [comment]
That's right. I've confirmed that "db" count had been increased when playback is jumpy.

Please take a look an attached text file which recorded logs with logcat.
[BigBuckBunny1.5xLog.txt](https://github.com/google/ExoPlayer/files/2418425/BigBuckBunny1.5xLog.txt)

**Comment by KazumiHARADA** [comment]
Please let me know progress this issue.

**Comment by andrewlewis** [comment]
The renderer is repeatedly dropping 50 frames. I think what you're seeing is that the renderer is repeatedly finding that it's far behind the player position, and to catch up it drops source frames up to the next keyframe. That keyframe then gets rendered, giving a jumpy appearance.

One possibility is that that decoding is just too slow on this device. You could try reducing the frame rate or resolution. However, given that this is specific to DRM, it may be related to an issue where queueing secure input buffers for L3 DRM playback is slow. I think this only happened on certain devices. If you want to experiment you could try modifying the [drain/feed loops](https://github.com/google/ExoPlayer/blob/b79156c/library/core/src/main/java/com/google/android/exoplayer2/mediacodec/MediaCodecRenderer.java#L649) in `MediaCodecRenderer` to break early if more than ~10 ms has elapsed. Please update here if you try that and find that it helps.
