### ISSUE TITLE
how to increase the simpleCache chunks space?

### ISSUE THREAD

**Issue by sajjadyousefnia** [google/ExoPlayer#4855]
By default, the space of simplecache is exactly 2MB, I want to increse it to more, how can I do it?? please help, thanks for your attention

**Comment by erdemguven** [comment]
Using `CacheDataSource(com.google.android.exoplayer2.upstream.cache.Cache, com.google.android.exoplayer2.upstream.DataSource, int, long)` constructor you can specify maxCacheFileSize.
