### ISSUE TITLE
Video is not seekable why?

### ISSUE THREAD

**Issue by khizar1556** [google/ExoPlayer#4856]
when i am trying to play HD videos resolution 1080 or above from my sd card video is started everything is fine but when i am seek forward it will play from start position why? if i am try to pay that uri to exo player demo application then timebar is disable can anyone please help me to sort out this problem

**Comment by khizar1556** [comment]
Anyone please help me what is wrong with hd files even 4k video playing well just when i use seekto then video starts from 0 mean to say its started again from start point seekto not working on HD video of local memory

**Comment by khizar1556** [comment]
@ojw28 @andrewlewis @AquilesCanta Can you please solve my problem or guide me what to do

**Comment by andrewlewis** [comment]
Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

**Comment by khizar1556** [comment]
@andrewlewis here is link of the video in which when i open file using uri from local storage you can see in this video the video is running but seekbar is disabled 
here is the link of the video 
please see this video
[https://drive.google.com/file/d/0ByLOrcoj9o3UNk81aUxXWlNfLTQyTWc4Y05MYTRSUjVGN2xB/view?usp=sharing ](https://drive.google.com/file/d/0ByLOrcoj9o3UNk81aUxXWlNfLTQyTWc4Y05MYTRSUjVGN2xB/view?usp=sharing )

i put these lines into json file that is in the assets folder of exoplayer demo app
`{
  "name": "Local",
  "samples": [
    {
      "name": "4k",
      "uri": "file:///storage/emulated/0/Alarms/Ggg.MKV"
    }`
{
  "name": "Local",
  "samples": [
    {
      "name": "4k",
      "uri": "file:///storage/emulated/0/Alarms/Ggg.MKV"
    }

And when i debug it the media source is like this in this picture please download picture from this link
[https://drive.google.com/file/d/1HFrmnirfaIgZcRo_jaPKVcypc3zkKYBI/view?usp=sharing](https://drive.google.com/file/d/1HFrmnirfaIgZcRo_jaPKVcypc3zkKYBI/view?usp=sharing)
![smpl](https://user-images.githubusercontent.com/32544554/45967419-6684f280-c047-11e8-9fab-2332ad8e5b95.png)
is this information is enough for this issue?

**Comment by andrewlewis** [comment]
Could you also provide the file `Ggg.MKV`? It's likely that cues are missing or incomplete due to the way the file was created. To investigate yourself, look at references to `SeekMap.Unseekable` in [MatroskaExtractor.java](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/extractor/mkv/MatroskaExtractor.java).

**Comment by khizar1556** [comment]
@andrewlewis Yes ofcourse here is video file named Ggg.MKV
[https://drive.google.com/file/d/1j0RoqFJpMksdLhfIhKbhTH0Y8Aaq6kaw/view?usp=sharing](https://drive.google.com/file/d/1j0RoqFJpMksdLhfIhKbhTH0Y8Aaq6kaw/view?usp=sharing)
download this file and change the file path according to your mobile directory 

i will also investigate it but please help me to make it correct sir i will be thankfull to you

**Comment by andrewlewis** [comment]
The cues do indeed appear to be missing. You will need to change how you produce the file to make it seekable (for example, if you remux using a tool like ffmpeg I think you'll find that cues get added to the file).

**Comment by khizar1556** [comment]
@andrewlewis sir i am trying too much can you please help me how to do it with ffmpeg i will thankfull to you if you help me please

**Comment by khizar1556** [comment]
sir i run two files now one that is seekable and other is not seekable i debug it in this calss  MatroskaExtractor.java you give the refrence both are the same and both has the cues now what can i do  here ?
