### ISSUE TITLE
Different duration between MediaMetadataRetriever and ExoPlayer

### ISSUE THREAD

**Issue by CoXier** [google/ExoPlayer#4858]
As title says, I use two ways to get duration of a video on Android Device.  

```
var mMetadataRetriever: MediaMetadataRetriever
mMetadataRetriever!!.extractMetadata(MediaMetadataRetriever.METADATA_KEY_DURATION).toLong()
```
Then I got `10031` milliseconds.

Then  I use ExoPlayer to get duration like this:

```
private var mediaPlayer: SimpleExoPlayer
mediaPlayer.getDuration()
```
I got `9970` milliseconds.

**Comment by khizar1556** [comment]
when i am trying to play HD videos resolution 1080 or above from my sd card video is started everything is fine but when i am seek forward it will play from start position why? if i am try to pay that uri to exo player demo application then timebar is disable can anyone please help me to sort out this problem

**Comment by CoXier** [comment]
Why do you comment your question in this issue ?

**Comment by khizar1556** [comment]
i thought you know about my question.No one is answering so i asked you this

**Comment by andrewlewis** [comment]
Please could email a link to the media to `dev.exoplayer@gmail.com`?

**Comment by CoXier** [comment]
Ok. FFmpeg returns as same duration as `ExoPlayer`. So I think there is a bug in  Android MediaMetadataRetriever.

**Comment by andrewlewis** [comment]
Please could you file an issue on the [Android issue tracker](https://source.android.com/setup/contribute/report-bugs)? Thanks!
