### ISSUE TITLE
Pause / stop a single download, not all (Offline)

### ISSUE THREAD

**Issue by Mariovc** [google/ExoPlayer#4860]
### Issue description
When downloading HLS / DASH videos for offline mode, can I stop a single download while having all the rest downloading?
I've found a similar issue "[Pause/Resume download with HlsDownloader or DashDownloader](https://github.com/google/ExoPlayer/issues/3907)" where the solution is stopping all downloads, using `stopDownloads` from `DownloadManager` class. But can I stop only one selected download? 
In case a user wants to download a queued video without losing progress on the current downloading video. It is a nice feature to have, if it doesn't exist.

### Version of ExoPlayer being used
2.8.4

**Comment by erdemguven** [comment]
It isn't possible currently. We'll consider supporting it.

**Comment by ojw28** [comment]
Support will be added in `2.10`.

**Comment by marcovietovega** [comment]
Do you have an estimate on when 2.10 will be released?
