### ISSUE TITLE
Exoplayer demo-ima app cookie problem

### ISSUE THREAD

**Issue by mustafasevgi** [google/ExoPlayer#4865]
Hello,

this my preJingle url: http://ad.reklamport.com/rpgetad.ashx?tt=t_fizyradyo_jingle_1x1&vast=1&country=TR&lang=EN&operator=operator

when i try to play this jingle at demo-ima app, i can not see cookie for uniq user like btguid. So Every event(firstQuartile,midpoint etc.) return different cookie(btguid). 

Player does not accept Set-Cookie.

btguid is unique id for user.

exoplayer version: 2.8.4
exoplayer ima extension version: 2.8.4

device: Huawei Nexus 6P
android os version:8.1.0

demo-ima app branch: release-v2

Can you help please,
Thanks.

**Comment by andrewlewis** [comment]
If this is a request to be able to set cookies on ad requests: reading https://groups.google.com/forum/#!topic/ima-sdk/9UQBKLjRbgg it sounds like the Android IMA SDK doesn't currently provide a way to do this.

You may get a more helpful answer if you post your question in the [IMA SDK forum](https://groups.google.com/forum/#!forum/ima-sdk). Thanks.

**Comment by mustafasevgi** [comment]
Thank you for quick answer @andrewlewis .

Can i intercept event request(start, firstQuartile, midpoint) with okhttp interceptor and add cookie values?

Thanks,

**Comment by andrewlewis** [comment]
I'm not familiar with okhttp interceptors, but the requests will come from the `WebView` that the IMA SDK creates which uses the cronet network stack.

If it doesn't work another thing you could try would be to intercept loads via a `WebViewClient` (though this is a bit hacky, and you'd need to make sure it doesn't interfere with the IMA SDK's own interaction with the `WebView`).
