### ISSUE TITLE
How to play live video HLS

### ISSUE THREAD

**Issue by Mono-Mobile** [google/ExoPlayer#4876]
Hello, I have problem.

My app implement ExoPlayer and play video HLS in VOD it's work but when i use streaming video url .m3u8 it return error `Unable to connect to "stream-url"`

how to fix it.
thank you.

**Comment by AquilesCanta** [comment]
It would seem to me that the playlist contains the string "stream-url" where an actual url is expected. But I cannot help with the provided information.

Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).
