### ISSUE TITLE
How to add subtitles from Uri

### ISSUE THREAD

**Issue by PDACN** [google/ExoPlayer#4879]
Hi,
I am using ExoPlayer r2.8.4 version,
but I don't know how and where add MediaSource for Subtitles in initializePlayer(),
I should take subtitles from an Uri (subtitles.vtt)

**Comment by erdemguven** [comment]
I guess you're using PlayerActivity from demo app code. At around line 447 mediaSource is set. There you can create your subtitle MediaSource and merge with video MediaSource, like described here:
https://google.github.io/ExoPlayer/guide.html#side-loading-a-subtitle-file
