### ISSUE TITLE
Dash-Mpeg in a TvBox play Audio but not Video!.

### ISSUE THREAD

**Issue by bsysop** [google/ExoPlayer#488]
Hi, i using the code perfect for play DASH, working very good in Mobile (Every supported versions and models), but when put in a TvBox (This use CPU AmLogic and GPU Mali-450), this got some error, just play Audio but not Video, and LogCat give me this error:

05-23 06:59:05.453: W/ContainerMediaChunk(2168): Ignoring unexpected seekMap
05-23 06:59:05.873: D/EventLogger(2168): bandwidth [36.01, 65547, 0.42, 1290817]
05-23 06:59:06.663: W/ContainerMediaChunk(2168): Ignoring unexpected seekMap
05-23 06:59:07.043: D/EventLogger(2168): bandwidth [37.17, 65567, 0.38, 1304796]
05-23 06:59:07.743: W/ContainerMediaChunk(2168): Ignoring unexpected seekMap
05-23 06:59:08.163: D/EventLogger(2168): bandwidth [38.29, 65527, 0.42, 1290817]
05-23 06:59:08.963: W/ContainerMediaChunk(2168): Ignoring unexpected seekMap
05-23 06:59:09.373: D/EventLogger(2168): bandwidth [39.50, 65633, 0.41, 1296454]

Are this a Bug?

**Comment by zarej** [comment]
I have the same problem, everything works perfect on handset but on TVBox make problems I can hear only audio, video is black. Here is my log: http://pastebin.com/5diLmpjq
And here are specification for my box: http://www.rshtech.cn/en/productshow.asp?bid=11&tid=21&sid=21&id=27

If you need anything more I will gladly contribute to fix this problem.

**Comment by bsysop** [comment]
I forget to say, my Android are 4.4.2, and your Zarej?

(PlayBack MP4 works on TvBox, just i see this problem with MPEG-DASH)

**Comment by bsysop** [comment]
Hello, anyone have some Hint? Where begin to find?

**Comment by brianchu** [comment]
Same here. Amlogic S802 Android 4.4. (http://www.tinydeal.com/Android-44-16G-Quad-Core-4K-TV-Box-w-WiFi-HDMIBluetoothXBMC-p-129131.html)

I know it's not Android CTS. but what is the way to workaround it (how to fall back to native engine or software rendering, etc) ? Please advise. Thanks.

**Comment by zarej** [comment]
If you want to return to default decoder, which will work but with lower performance, do the following:

Go to /system/etc/media_codecs.xml and remove following line in Decoders tag:
<MediaCodec name="OMX.amlogic.avc.decoder.awesome" type="video/avc" />

Or place it after
<MediaCodec name="OMX.google.h264.decoder" type="video/avc" />

Just note that you must do remount /system in rw so you can do above changes with following command:
mount -o remount,rw /system

**Comment by bsysop** [comment]
Hi @zarej, you 100% right +1 for you, this works and play the video h264!
Why you says this have lower performance? What exactly will be worst?

**Comment by zarej** [comment]
I've tested with my HLS streams (not tested with dash, except with streams that are come in demo app which are working fine), and there are freezes of video sometimes. Also 3rd party players after doing above modification can have the same freezing problems, because they use the same codec.

**Comment by bsysop** [comment]
If the stream are small no much problems, problem are when large streaming, i tried with Dash and HLS and always freezing :(

I revert the changes, so i using "OMX.amlogic.avc.decoder.awesome" again, then i do a try, using WebView(Chromium)+HTML5 DASH Player... And this works perfect, of course i want to use Exoplayer but i don't know why Exoplayer don't like to use this Codec, i will still checking about that.

**Comment by bsysop** [comment]
Clues by now:
HLS h264 play but freeze.
Dash h264 play but with no video.
Dash h264 (In player HTML5) play perfect.

And this is what make strange, because if play in Player HTML5 it means have to play in ExoPlayer.

**Comment by bsysop** [comment]
Well, finally i made my Dash play in this TvBox with a simple new "MediaPlayer();", and then this run ok... but can't play with exoplayer. (This means a little dirty, i have two players, one for mobile/tablet, another for Amlogic TvBox).

 - AmLogic using a called AmFFMPEG and some own decoders, they have own libDash for decode this.
 - This Dash can't have different bitrates in the manifest, so... Do not help so much, but works smooth.

I have debugged the Exoplayer and i can see Exoplayer do not create "Surface", maybe he thinks "OMX.amlogic.avc.decoder.awesome" is a no valid decoder, that point i can't check.

Amlogic is growing in the market, so will be interesting fix that, maybe can i try to do that, but i need some orientation because i have wasted 3 days in that and maximum i can say is surface not created (I have checked that do not go to MediaCodecVideoTrackRenderer because Surface is no created).

**Comment by bsysop** [comment]
After some time testing, i found my poor solution more poor than i think...

This Video+Audio get desynchronized :(

I have a question, can i built-in some Video codec (Example omx.google or some Lib_h264) in APK?

Thank you!.

**Comment by bsysop** [comment]
Finally i got this @brianchu  @zarej , i using **Amlogic S805/Mali450**, 
For me in this device, with my exactly configuration, HLS Works with Hardware decoder (**OMX.amlogic.avc.decoder.awesome**) if Single bitrate, if adaptive this simple do not works, When Software decoder (**OMX.Google**) this freezes, i sure in software decoder he just dropping frames, it means not enough power (CPU) to play media.

Then i check about this Hardware decoder capabilities, and this don't have Adaptive.
```
08-18 02:36:02.477: I/SampleChooserActivity(2648): Examinig decoder: OMX.amlogic.avc.decoder.awesome
08-18 02:36:02.487: I/SampleChooserActivity(2648): supports adaptive playback: false
```

@ojw28 Will be great if in future have prepared some snippets like this to people check they system before create some issue, or maybe they execute your snippet when your guys needs (I know this is special case, but of course can helps).
Check CodecCapabilities.
```
int numCodecs = MediaCodecList.getCodecCount();
for (int i = 0; i < numCodecs; i++) {
    MediaCodecInfo codecInfo = MediaCodecList.getCodecInfoAt(i);
    String name = codecInfo.getName();
    Log.i(TAG, "Examinig " + (codecInfo.isEncoder() ? "encoder" : "decoder") + ": " + name);
    for(String type: codecInfo.getSupportedTypes()) {
        boolean ap = codecInfo.getCapabilitiesForType(type).isFeatureSupported(MediaCodecInfo.CodecCapabilities.FEATURE_AdaptivePlayback);
        Log.i(TAG, "supports adaptive playback: " + ap);
    }
}
```

**Comment by bsysop** [comment]
Finally i work directly with AmLogic staff, i was in they office in China and now i know exactly what happens, they just don't have Adaptive decoder! They have problems in they old software/firmware (and actual published) versions, but very soon they will be perfect, better than many another manufactor (I tested that by my self)

**SO: This is no EXOPLAYER Issue!**

Sorry by that! Thanks for the support!.

For all guys, i recommend for moment use another hardware, 3-6 months later, use Amlogic but check if you have last AmLogic Software, if not you will still have this problem.

Thanks @brianchu @zarej
