### ISSUE TITLE
MediaSessionConnector.RatingCallback: No way to get the extras bundle

### ISSUE THREAD

**Issue by hacker1024** [google/ExoPlayer#4885]
### Issue description
There's no way to get an extras bundle in the `MediaSessionConnector`'s `RatingCallback`. I want to do this to rate items in the queue from my UI.

### Reproduction steps
The Android Support Library's `MediaSessionCompat.Callback` has two rating callback functions:
```
/**
 * Override to handle the item being rated.
 *
 * @param rating The rating being set.
 */
public void onSetRating(RatingCompat rating) {
}

/**
 * Override to handle the item being rated.
 *
 * @param rating The rating being set.
 * @param extras The extras can include information about the media item being rated.
 */
public void onSetRating(RatingCompat rating, Bundle extras) {
}
```

But the `MediaSessionConnector.RatingCallback` interface only has a function that takes the player and rating as parameters.
```void onSetRating(Player player, RatingCompat rating);```

### Proposed solution
I made a pull request [here](https://github.com/google/ExoPlayer/pull/4884) that adds a function with the extras parameter to the callback, and calls it at the appropriate time.

### Version of ExoPlayer being used
2.8.4

**Comment by ojw28** [comment]
@hacker1024 , @marcbaechinger - The pull request looks fine, although I wonder whether we really need both methods in our `RatingCallback` interface:

* If the platform (or support library) calls exactly one of them each time an item is rated, how does it choose which one? Do we need both methods in our `RatingCallback` interface, or could we just have the one that takes the bundle, and use an empty bundle if the platform calls the no-bundle version?
* If the platform calls both methods on the assumption app code will only override one of them, then we should probably just implement the case that includes the bundle?

Please clarify, and we'll figure out how to get the change merged. Thanks!

**Comment by hacker1024** [comment]
I just [tested it](https://hastebin.com/toburazitu.kt), and calling `setRating(RatingCompat)` on the `MediaSessionCompat`'s transport controls will call the `onSetRating(RatingCompat)` function in the callback, and calling `setRating(RatingCompat, Bundle)` on the `MediaSessionCompat`'s transport controls will call the `onSetRating(RatingCompat, Bundle)` function in the callback.

> could we just have the one that takes the bundle, and use an empty bundle if the platform calls the no-bundle version?

This is possible, but isn't it a bit of a waste of memory to create an empty bundle when one isn't provided?

**Comment by ojw28** [comment]
> isn't it a bit of a waste of memory to create an empty bundle when one isn't provided?

How often is it actually called? Seems negligible to me, unless it's called way more often than I think it's called.

Still, it seems like there are two variants end-to-end, so I guess we should just plumb it through as-is, rather than try and merge.

**Comment by ojw28** [comment]
#4884 has been merged.
