### ISSUE TITLE
Updating TrackSelector w/o ExoPlayer recreation

### ISSUE THREAD

**Issue by png6** [google/ExoPlayer#4888]
Is it possible to reset or update a `TrackSelector` without creating a new instance of `ExoPlayer`? Or perhaps a way to update a `DefaultTrackSelector`’s  `TrackSelection.Factory`?

I currently have a shared instance of ExoPlayer but have certain conditions prior to playback that may have a `DefaultTrackSelector` with specific implementation of the `TrackSelection.Factory`. It would be ideal if I did not have to recreate the ExoPlayer instance when this occurs.

**Comment by erdemguven** [comment]
I think you can have a custom TrackSelection.Factory which would let you configure which type of TrackSelection to return.

**Comment by ojw28** [comment]
Closing as answered.
