### ISSUE TITLE
play video failed when switched between two page, some device

### ISSUE THREAD

**Issue by shoyu666** [google/ExoPlayer#4891]
version:2.6.0 or 2.9.0
device: only in  Xiaomi Redmi Note 4 
  (i hava test same huawei device,it works fine)
step:
1: Activity A use SimpleExoPlayer(instance a) play video (play well )
2: jump to Activity B use SimpleExoPlayer(instance b )play video too
    in Activity A onPause (call setPlayWhenReady(false))
3:get exception 
4:press back to Activity  A 
  on Actiivty A  onResume call setPlayWhenReady(true)   (never play )

result:
Actiivty A play well first time
Actiivty A never play again after jump to Activity B 
 Activity B can play well when jump to  Activity B from A

exception log:

 java.lang.IllegalArgumentException
        at android.media.MediaCodec.native_setSurface(Native Method)
        at android.media.MediaCodec.setOutputSurface(MediaCodec.java:1810)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.setOutputSurfaceV23(MediaCodecVideoRenderer.java:1014)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.setSurface(MediaCodecVideoRenderer.java:422)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.handleMessage(MediaCodecVideoRenderer.java:387)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.deliverMessage(ExoPlayerImplInternal.java:871)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.sendMessageToTarget(ExoPlayerImplInternal.java:842)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.sendMessageInternal(ExoPlayerImplInternal.java:824)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:333)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:207)
        at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by shoyu666** [comment]
more log 


`09-29 16:59:38.926 20466-21074/xxxxxxx D/ACodec: [OMX.MTK.VIDEO.DECODER.AVC] Now Idle->Executing
09-29 16:59:38.931 20466-21074/xxxxxxx D/ACodec: [OMX.MTK.VIDEO.DECODER.AVC] submitting output meta buffer ID 13 for graphic buffer 0xda1049e0
09-29 16:59:38.934 20466-20466/xxxxxxx D/EventLogger:       [X] Track:0, id=1, mimeType=video/avc, res=1280x720, supported=YES
09-29 16:59:38.935 20466-21074/xxxxxxx D/ACodec: [OMX.MTK.VIDEO.DECODER.AVC] submitting output meta buffer ID 12 for graphic buffer 0xda104bc0
09-29 16:59:38.940 20466-21074/xxxxxxx D/ACodec: [OMX.MTK.VIDEO.DECODER.AVC] submitting output meta buffer ID 11 for graphic buffer 0xda104e40
09-29 16:59:38.940 20466-21074/xxxxxxx D/ACodec: [OMX.MTK.VIDEO.DECODER.AVC] Now Executing
09-29 16:59:38.941 20466-21074/xxxxxxx D/ACodec: [OMX.MTK.VIDEO.DECODER.AVC] onInputBufferFilled ID 1 w/ time 0 eos 0 mode 1 err 0
09-29 16:59:38.941 20466-21074/xxxxxxx I/ACodec: [OMX.MTK.VIDEO.DECODER.AVC] received csd settings.
09-29 16:59:38.941 20466-21074/xxxxxxx D/ACodec: [OMX.MTK.VIDEO.DECODER.AVC] calling emptyBuffer 1 w/ codec specific data
09-29 16:59:38.941 20466-21074/xxxxxxx D/ACodec: [OMX.MTK.VIDEO.DECODER.AVC] onInputBufferFilled ID 2 w/ time 0 eos 0 mode 1 err 0
09-29 16:59:38.941 20466-21074/xxxxxxx I/ACodec: [OMX.MTK.VIDEO.DECODER.AVC] received csd settings.
09-29 16:59:38.941 20466-21074/xxxxxxx D/ACodec: [OMX.MTK.VIDEO.DECODER.AVC] calling emptyBuffer 2 w/ codec specific data
09-29 16:59:38.945 20466-21074/xxxxxxx D/ACodec: [OMX.MTK.VIDEO.DECODER.AVC] onInputBufferFilled ID 3 w/ time 0 eos 0 mode 1 err 0
09-29 16:59:38.946 20466-21074/xxxxxxx D/ACodec: [OMX.MTK.VIDEO.DECODER.AVC] onInputBufferFilled ID 4 w/ time 33511 eos 0 mode 1 err 0
09-29 16:59:38.947 20466-20466/xxxxxxx I/SurfaceView: updateWindow -- OnPreDrawListener, mHaveFrame = true, this = android.view.SurfaceView{128a7a V.E...... ......I. 0,0-1080,600}
09-29 16:59:38.949 20466-21074/xxxxxxx D/ACodec: [OMX.MTK.VIDEO.DECODER.AVC] onInputBufferFilled ID 5 w/ time 67022 eos 0 mode 1 err 0
09-29 16:59:38.949 20466-21074/xxxxxxx D/ACodec: [OMX.MTK.VIDEO.DECODER.AVC] onInputBufferFilled ID 6 w/ time 100522 eos 0 mode 1 err 0
09-29 16:59:38.951 20466-21074/xxxxxxx D/ACodec: [OMX.MTK.VIDEO.DECODER.AVC] onInputBufferFilled ID 7 w/ time 134022 eos 0 mode 1 err 0
09-29 16:59:38.952 20466-21074/xxxxxxx D/ACodec: [OMX.MTK.VIDEO.DECODER.AVC] onInputBufferFilled ID 8 w/ time 167522 eos 0 mode 1 err 0
09-29 16:59:38.957 20466-21073/xxxxxxx I/MediaCodec: [OMX.MTK.VIDEO.DECODER.AVC] setting surface generation to 20957199
09-29 16:59:38.969 20466-21074/xxxxxxx D/ACodec: [OMX.MTK.VIDEO.DECODER.AVC] Now handling output port settings change
09-29 16:59:38.970 20466-21074/xxxxxxx D/ACodec: [OMX.MTK.VIDEO.DECODER.AVC] cancelBuffer on buffer 13, mGraphicBuffer 0xda1049e0
09-29 16:59:38.972 20466-21074/xxxxxxx D/ACodec: [OMX.MTK.VIDEO.DECODER.AVC] cancelBuffer on buffer 12, mGraphicBuffer 0xda104bc0
09-29 16:59:38.974 20466-21074/xxxxxxx D/ACodec: [OMX.MTK.VIDEO.DECODER.AVC] cancelBuffer on buffer 11, mGraphicBuffer 0xda104e40
09-29 16:59:38.977 20466-21074/xxxxxxx D/ACodec: [OMX.MTK.VIDEO.DECODER.AVC] Output port now disabled.
09-29 16:59:38.982 20466-21054/xxxxxxx I/MediaCodec: [OMX.MTK.VIDEO.DECODER.AVC] setting surface generation to 20957200
09-29 16:59:38.984 20466-21074/xxxxxxx W/ACodec: [OMX.MTK.VIDEO.DECODER.AVC] setting nBufferCountActual to 15 failed: -2147483648
09-29 16:59:38.984 20466-21074/xxxxxxx W/ACodec: [OMX.MTK.VIDEO.DECODER.AVC] setting nBufferCountActual to 14 failed: -2147483648
09-29 16:59:38.985 20466-21074/xxxxxxx W/ACodec: [OMX.MTK.VIDEO.DECODER.AVC] setting nBufferCountActual to 13 failed: -2147483648
09-29 16:59:38.985 20466-21052/xxxxxxx E/ExoPlayerImplInternal: Internal runtime error.
    java.lang.IllegalArgumentException
        at android.media.MediaCodec.native_setSurface(Native Method)
        at android.media.MediaCodec.setOutputSurface(MediaCodec.java:1810)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.setOutputSurfaceV23(MediaCodecVideoRenderer.java:1014)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.setSurface(MediaCodecVideoRenderer.java:422)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.handleMessage(MediaCodecVideoRenderer.java:387)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.deliverMessage(ExoPlayerImplInternal.java:871)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.sendMessageToTarget(ExoPlayerImplInternal.java:842)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.sendMessageInternal(ExoPlayerImplInternal.java:824)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:333)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:207)
        at android.os.HandlerThread.run(HandlerThread.java:61)
09-29 16:59:38.986 20466-21052/xxxxxxx I/MediaCodec: [stop]line:597 [OMX.MTK.VIDEO.DECODER.AVC]+++
09-29 16:59:38.986 20466-21055/xxxxxxx D/ACodec: [OMX.MTK.VIDEO.DECODER.AVC] Executing::kWhatShutdown keepComponentAllocated 1
09-29 16:59:38.986 20466-21055/xxxxxxx D/ACodec: [OMX.MTK.VIDEO.DECODER.AVC] Now Executing->Idle
09-29 16:59:38.986 20466-21055/xxxxxxx D/ACodec: [OMX.MTK.VIDEO.DECODER.AVC] onInputBufferFilled ID 3 w/ time -1 eos 0 mode 0 err 0
09-29 16:59:38.986 20466-21055/xxxxxxx D/ACodec: [OMX.MTK.VIDEO.DECODER.AVC] onInputBufferFilled ID 4 w/ time -1 eos 0 mode 0 err 0
09-29 16:59:38.986 20466-21055/xxxxxxx D/ACodec: [OMX.MTK.VIDEO.DECODER.AVC] onOutputBufferDrained ID d
09-29 16:59:38.986 20466-21055/xxxxxxx D/ACodec: [OMX.MTK.VIDEO.DECODER.AVC] onOutputBufferDrained ID 16
09-29 16:59:38.986 20466-21055/xxxxxxx D/ACodec: [OMX.MTK.VIDEO.DECODER.AVC] onOutputBufferDrained ID 17
09-29 16:59:38.986 20466-21055/xxxxxxx D/ACodec: [OMX.MTK.VIDEO.DECODER.AVC] onOutputBufferDrained ID 18
09-29 16:59:38.995 20466-21074/xxxxxxx D/ACodec: [OMX.MTK.VIDEO.DECODER.AVC] Allocating 12 meta buffers on output port
09-29 16:59:38.996 20466-21074/xxxxxxx D/ACodec: [OMX.MTK.VIDEO.DECODER.AVC] allocated meta buffer with ID 14 (pointer = 0xeea3d000)
09-29 16:59:38.997 20466-21074/xxxxxxx D/ACodec: [OMX.MTK.VIDEO.DECODER.AVC] allocated meta buffer with ID 15 (pointer = 0xeea3d020)
09-29 16:59:38.997 20466-21074/xxxxxxx D/ACodec: [OMX.MTK.VIDEO.DECODER.AVC] allocated meta buffer with ID 16 (pointer = 0xeea3d040)
09-29 16:59:38.998 20466-21074/xxxxxxx D/ACodec: [OMX.MTK.VIDEO.DECODER.AVC] allocated meta buffer with ID 17 (pointer = 0xeea3d060)
09-29 16:59:38.998 20466-21074/xxxxxxx D/ACodec: [OMX.MTK.VIDEO.DECODER.AVC] allocated meta buffer with ID 18 (pointer = 0xeea3d080)
09-29 16:59:38.999 20466-21074/xxxxxxx D/ACodec: [OMX.MTK.VIDEO.DECODER.AVC] allocated meta buffer with ID 19 (pointer = 0xeea3d0a0)
09-29 16:59:38.999 20466-21074/xxxxxxx D/ACodec: [OMX.MTK.VIDEO.DECODER.AVC] allocated meta buffer with ID 20 (pointer = 0xeea3d0c0)
09-29 16:59:39.000 20466-21074/xxxxxxx D/ACodec: [OMX.MTK.VIDEO.DECODER.AVC] allocated meta buffer with ID 21 (pointer = 0xeea3d0e0)
09-29 16:59:39.001 20466-21074/xxxxxxx D/ACodec: [OMX.MTK.VIDEO.DECODER.AVC] allocated meta buffer with ID 22 (pointer = 0xeea3d100)
09-29 16:59:39.001 20466-21074/xxxxxxx D/ACodec: [OMX.MTK.VIDEO.DECODER.AVC] allocated meta buffer with ID 23 (pointer = 0xeea3d120)
09-29 16:59:39.002 20466-21074/xxxxxxx D/ACodec: [OMX.MTK.VIDEO.DECODER.AVC] allocated meta buffer with ID 24 (pointer = 0xeea3d140)
09-29 16:59:39.002 20466-21074/xxxxxxx D/ACodec: [OMX.MTK.VIDEO.DECODER.AVC] allocated meta buffer with ID 25 (pointer = 0xeea3d160)
09-29 16:59:39.003 20466-21073/xxxxxxx I/MediaCodec: [onMessageReceived]line:1303 [OMX.MTK.VIDEO.DECODER.AVC][what=kWhatBuffersAllocated][state 6][msg='AMessage(what = 'codc', target = 44) = {
      int32_t what = 1634495587
      int32_t portIndex = 1
      RefBase *portDesc = 0xd7464e70
    }' ]
09-29 16:59:39.003 20466-21074/xxxxxxx D/ACodec: [OMX.MTK.VIDEO.DECODER.AVC] Output port now reenabled.`

**Comment by AquilesCanta** [comment]
Please provide a bugreport as requested in the issue template.

**Comment by ojw28** [comment]
Closed due to lack of required information.
