### ISSUE TITLE
How to cache more songs files, but do not bring the problem of memory soaring.

### ISSUE THREAD

**Issue by tangmingscau** [google/ExoPlayer#4893]
I have a requirement that I need to cache songs all at once. My current approach is to change some of the DefaultLoadControl parameters and change the minbufferus to 5min, but this brings a performance problem with memory soaring. I hope to implement a solution that caches more song files and only a few songs. The file is in memory and the rest is on the disk. Can you give me some advice?

**Comment by AquilesCanta** [comment]
@erdemguven, this seems to be a task for downloads. Mind taking a look?

**Comment by erdemguven** [comment]
If the files are progressive stream (like mp3) you can precache or download them easily. Please look at this blog post:
https://medium.com/google-exoplayer/pre-caching-downloading-progressive-streams-in-exoplayer-3a816c75e8f6
