### ISSUE TITLE
Exoplayer returns the mp3 file's length incorrectly , but other players returns the correct length .

### ISSUE THREAD

**Issue by kimdohyung5** [google/ExoPlayer#4894]
### Issue description
Exoplayer returns the mp3 file's length incorrectly , but other players returns the correct length .
I made this very simple app for this test with "EventLogger" class attached.
I expected that the player returns the 3:03 length for this mp3 but it returns the length 04:18.
I think that there is something wrong going on.

### Reproduction steps
when you run this sample app, you will see the length 4:18 but, it does show fake length.

### Link to test content
http://download.think-u.co.kr/TEST/ROOM/LENGTHWRONG.MP3

### Version of ExoPlayer being used
com.google.android.exoplayer:exoplayer-core:2.8.2
com.google.android.exoplayer:exoplayer-ui:2.8.2

### Device(s) and version(s) of Android being used
"SAMSUNG SM-A520K android 8.0.0 API26" mobile phone
"SAMSUNG SM-T536 Android 6.0.1, API23"  pad.

### A full bug report captured from the device
when you run the app, you can see the result.

[ExoTesting.2018.10.01.zip](https://github.com/google/ExoPlayer/files/2432718/ExoTesting.2018.10.01.zip)

**Comment by AquilesCanta** [comment]
Thanks for filling the issue template.

It would seem to me that the Xing header contains wrong frameCount, from which the wrong duration is calculated. If you set the frame count in the file to 0, ExoPlayer actually estimates the right duration.

Also worth noting: Not all other players calculate it "correctly". Media info output:
```
General
Complete name                            : LENGTHWRONG.MP3
Format                                   : MPEG Audio
File size                                : 2.08 MiB
Duration                                 : 4 min 17 s
Overall bit rate mode                    : Constant
Overall bit rate                         : 96.0 kb/s
Writing library                          : LAME3.98.4

Audio
Format                                   : MPEG Audio
Format version                           : Version 1
Format profile                           : Layer 3
Format settings                          : Joint stereo / MS Stereo
Duration                                 : 4 min 17 s
Bit rate mode                            : Constant
Bit rate                                 : 96.0 kb/s
Channel(s)                               : 2 channels
Sampling rate                            : 44.1 kHz
Frame rate                               : 38.281 FPS (1152 SPF)
Compression mode                         : Lossy
Stream size                              : 2.95 MiB
Writing library                          : LAME3.98.4
```

Same duration is calculated by chrome when playing the file. Unfortunately the only fix I can think on is changing the media to reflect the proper duration. Please do let me know if you think any conclusion is wrong.

**Comment by AquilesCanta** [comment]
I'll add a flag to Mp3Extractor which you can enable on DefaultExtractorsFactory to ignore the Xing information. This way, using the default configuration, the duration should be estimated ~correctly.

A referenced to said commit will appear below.

**Comment by AquilesCanta** [comment]
After some discussion, we have decided that the way to go is to fix the media. Sorry for the inconvenience caused.
