### ISSUE TITLE
Question: can I download only a part of a progressive stream?

### ISSUE THREAD

**Issue by eneim** [google/ExoPlayer#4896]
This is a question, can be a feature request.

This is not limited to progressive stream, but I would like to start from there. Assuming I would like to preload 1/4 or the mp4 file only (so User can start playback immediately on demand, but the App doesn't need to download the whole video), how can I make this done with current Downloader mechanism? If it is not supported yet, do you have any idea about how it can be done?

Sorry if this question is answered before. I did a search but found nothing relevant.

Thanks in advance!

**Comment by erdemguven** [comment]
It isn't possible to do with Downloader but for progressive streams only you can use CacheUtil.cache() methods. They get a DataSpec in which you can specify the range you can to download.
For an example:
https://medium.com/google-exoplayer/pre-caching-downloading-progressive-streams-in-exoplayer-3a816c75e8f6

**Comment by eneim** [comment]
@erdemguven Got it. Do you have any suggestion for non-Progressive stream (HLS/DASH, etc)?

**Comment by erdemguven** [comment]
Unfortunately there is currently no way. #1497 tracks this feature.
