### ISSUE TITLE
Is there any way to get an AndroidTV device Widevine Modular version?

### ISSUE THREAD

**Issue by rishun-fsi** [google/ExoPlayer#4897]
Hello,

I have a question about AndroidTV device Widevine Modular version.
Is it possible to get the Widevine Modular version by useing exoplayer api on the device?
If it is possible, could you tell me how to get it?

Thank you in advance.

**Comment by alexey-y** [comment]
Hi,

Sort of... It depends what are u looking for. U can get "oemCryptoApiVersion":

String oemCryptoApiVersion = new MediaDrm(UUID.fromString("edef8ba9-79d6-4ace-a3c8-27dcd51d21ed")).getPropertyString("oemCryptoApiVersion");

The value u get is version of the API implemented by CDM "11".

If u are looking for actual version of CDM - i.e. "v5.0.0-android", this is something which is not exposed on the client, but can be extracted from the license request on the Widevine License server...

Hope it helps...

**Comment by rishun-fsi** [comment]
@alexey-y Thank for your response. 
I tested on my device nexus player 8.0 as what you said.
Below is the result.
oemCryptoApiVersion = 11
widevine_cdm_version = v5.0.0-android

Also, I can get the follwing version = 1.0, could you tell me what the version is
String version = new MediaDrm(UUID.fromString("edef8ba9-79d6-4ace-a3c8-27dcd51d21ed")).getPropertyString(MediaDrm.PROPERTY_VERSION);

By the way, I have another question.
Is it possible to get the client PlayReady version on the device?

Thank you in advance.

**Comment by alexey-y** [comment]
Hi again,

Unfortunately, it seems that Playready didn't expose these (or at least didn't document them) via the same API. See here: https://docs.microsoft.com/en-us/playready/specifications/playready-plugin-for-android-specification. The only attribute which is there seems to be "securityLevel"...

U can get some stuff directly from the keyRequest inside your MediaDrmCallback.executeKeyRequest - if u parse the XML of the request on the client:

<"CLIENTINFO"><"CLIENTVERSION">2.5.0.1778</"CLIENTVERSION"></"CLIENTINFO">

On the server-side, you have all the info from the license request... Such as: 
ClientInformation.ClientVersion: 2.5.0.1778
ClientCertificate.SecurityLevel: 2000
ClientCertificate.GetSupportedFeatures: SecureClock,RevocationLists
CertificateInfo.ModelName: PlayReady SL2000 Device + Link Root CA

Regards,
Alexey

**Comment by AquilesCanta** [comment]
I'll close this issue under the assumption that this question is answered. In any case, I think it's more fitting for a general Android Q&A.
