### ISSUE TITLE
Find the content protection element of a DASH manifest

### ISSUE THREAD

**Issue by rs146** [google/ExoPlayer#4901]
Hi,

I've been trying find the content protection element of a DRM protected manifest. I wondered if that's possible. So far, I can see it's possible with [Smooth Streaming](https://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/source/smoothstreaming/manifest/SsManifest.ProtectionElement.html). Is there a way to get this in the `DashManifest`?

At the moment, I'm using a simple URL reader that reads the content to test whether the "ContentProtection" element exists. But like with Smooth Streaming - it would be nice if this was available in the ExoPlayer code.

**Comment by AquilesCanta** [comment]
I think what you are looking for is in 

DashManifest -> Period(s) -> AdaptationSet -> Representation -> Format -> DrmInitData (contains all Content protection elements that affects the given representation, or null if the representation is not encrypted).

Please let me know if this is what you need. If not, please clarify your use case so I may understand the requirement.
