### ISSUE TITLE
Improve support for low-latency DASH live streams

### ISSUE THREAD

**Issue by ojw28** [google/ExoPlayer#4904]
This issue tracks allowing playback of DASH live streams with lower latency (i.e. closer to the live edge). It's spun out from #4839. See in particular: https://github.com/google/ExoPlayer/issues/4839#issuecomment-426784093 which lists some items, although I'm not promising they're all correct! The referenced patch may also be helpful as a guide.

**Comment by jyiu-harmonicinc** [comment]
Hi @ojw28 

When playing CMAF close to live edge, segments will be downloaded when it's not complete. 
Therefore, time to download whole segment is likely to be duration of segment.

This makes defaultDandwidthMeter underestimate bandwidth as it's estimation logic is (segment size) / (elapsed time), and eventually exoplayer will drop video quality.

Do you have any plan to implement bandwidth estimation logic for CMAF?

**Comment by tonihei** [comment]
We'll look into supporting low-latency live streaming techniques soon. The problem you mention is one of things that need to be solved. We'll post this issue once we have better support for low-latency DASH streams.

**Comment by tonihei** [comment]
We published our [design doc](https://docs.google.com/document/d/1z9qwuP7ff9sf3DZboXnhEF9hzW3Ng5rfJVqlGn8N38k) on our webpage - open for comments!

**Comment by julianD77** [comment]
It will be great to have this support for live streams - is there any update on the planned timeline for delivery of these feature??

**Comment by tonihei** [comment]
We moved this feature a bit further down our priority list and will probably only get around to finish the started work later this year. Please subscribe to this issue to see any updates. Thanks.

**Comment by tonihei** [comment]
Closing this feature request as it's fully implemented and will be released in 2.13.0.

**Comment by RamilGabdrakhmanov** [comment]
Hi! I tested and received latency around 3-4 sec! That is good! But, i tested with high speed connection.

I'm interesting in ABR manager and LL playback. Did you develop "Trial-and-error approaches" or "Falling back using the playback speed control to get a new bandwidth estimate in regular intervals" technics mentioned in [design doc](https://docs.google.com/document/d/1z9qwuP7ff9sf3DZboXnhEF9hzW3Ng5rfJVqlGn8N38k) ?

**Comment by tonihei** [comment]
@RamilGabdrakhmanov None of the two approaches actually. Playback will automatically fall back if the network speed isn't sufficient, so we will get new bandwidth estimates for slower networks and the player can switch down to a lower quality. But there is currently no mechanism to check whether switching up to a better quality is possible. We just rely on the bandwidth measurements we get from non-latency segments. For example we get some bandwidth estimate at the beginning of playback, which allows to start (or to quickly adapt) to a better quality if possible. But if your conditions improve considerably in the middle of playback while we are only loading low-latency segments, the player wouldn't notice at the moment.

**Comment by RamilGabdrakhmanov** [comment]
Thank you! That is clear
Do you have plans to develop something like [L2A](https://github.com/unifiedstreaming/Learn2Adapt-LowLatency) ?

**Comment by tonihei** [comment]
We have no immediate plans to develop or implement a more advanced algorithm for this. It's also worth noting that we need to be careful to not over-specialize our approach here as it needs to work for all kinds of live streams with unknown combinations of bitrates etc.
