### ISSUE TITLE
Access currently playing HLS segment

### ISSUE THREAD

**Issue by BurakDurmus** [google/ExoPlayer#4905]
When grabbing an `HlsMediaPlaylist `with `getCurrentManifest()`  is it possible to obtain the HLS segment that is currently being played (for logging data)?

**Comment by AquilesCanta** [comment]
No, this is not supported unfortunately. If you want to have a look at implementing this yourself, you might want to look into `HlsSampleStreamWrapper#readData`. There is one HlsSampleStreamWrapper per segment stream (for example, one for video and one for audio, if they are demuxed; or a single HlsSampleStreamWrapper if all content is muxed).

Each `HlsSampleStreamWrapper` may have in turn multiple sample queues, depending on whether multiple tracks are muxed in its segment stream. For demuxing these tracks, `HlsSampleStreamWrapper#readData` takes a sampleQueueIndex which identifies the track. Finally, you'll find in `HlsSampleStreamWrapper#readData` a local variable called chunkUid which is set in `HlsSampleStreamWrapper#init`. From there you can track the id to identify each segment.

I don't think we can realistically commit to adding support for this.

**Comment by swardharia** [comment]
Hi @AquilesCanta ,

I was also looking for the same support on the ExoPlayer, trying to get information about the current HLS segment being played in order to track some information. 

Is there any update on this support being looked at in future ?

**Comment by AquilesCanta** [comment]
No plans, sorry.

**Comment by AquilesCanta** [comment]
For future readers, there are now ways of achieving this. For example, adding an [AnalyticsListener](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/analytics/AnalyticsListener.html) to the [player](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/SimpleExoPlayer.html#addAnalyticsListener-com.google.android.exoplayer2.analytics.AnalyticsListener-). And listening for load events. You'll have to identify the ones that belong to media segments.
