### ISSUE TITLE
Concatenating and MergingMediaSource with subtitles not working as mentioned

### ISSUE THREAD

**Issue by AniLabXTeam** [google/ExoPlayer#4906]
### Issue description
I have some not standart situation. I need to play video parts as one file from remote server with subtitles. This task can be done using Concatenating and MergingMediaSource. But, as devs say to me earlier - i need "split" subtitles for each part because ia have two parts of video and one vtt file for whole movie.
So, i write small code for splitting subs and correcting time for each window that ConcatenatingMediaSource creating. In code first i'm creating MergingMediaSource (video part + subs part) for each video part and then concatenate them. All working fine... except seeking on all windows except first. If user uses seek - exo loads subtitles from first window. But if player playing first part of video and switching to second - subs loads as mentioned. Used seek? Reset subs to first. And exj don't cares if user used seek between windows or in one window - subs always resets to first.

### Reproduction steps
Im' provide code that i'm using for creating MediaSources and all links that i'm using for testing 
```java
// Creating media source for all video parts
MediaSource[] mediaSources = new MediaSource[videoUriPartsList.size()];
for (int i = 0; i < videoUriPartsList.size(); i++) {
    MediaSource mediaSource;

    if (videoUriPartsList.get(i).contains(MPD_EXTENSION)) {
        mediaSource = new DashMediaSource(Uri.parse(videoUriPartsList.get(i)), mediaDataSourceFactory, new DefaultDashChunkSource.Factory(mediaDataSourceFactory), null, null);
    } else if (videoUriPartsList.get(i).contains(M3U8_EXTENSION)) {
        mediaSource = new HlsMediaSource.Factory(mediaDataSourceFactory).createMediaSource(Uri.parse(videoUriPartsList.get(i)));
    } else {
        mediaSource = new ExtractorMediaSource.Factory(mediaDataSourceFactory).createMediaSource(Uri.parse(videoUriPartsList.get(i)));
    }
    mediaSources[i] = mediaSource;
}

// If has subtitles parts - merge each part with with mediasources that we previously created
MergingMediaSource[] mergedMediaSources = null;
if (videoSubtitlesParts != null) {
    if (videoSubtitlesParts.size() == mediaSources.length) {
        mergedMediaSources = new MergingMediaSource[videoSubtitlesParts.size()];
        for (int i = 0; i < videoSubtitlesParts.size(); i++) {
            subtitlesAvailable = true;
            Format textFormat;
            if (videoSubtitles.contains(ASS_EXTENSION)) {
                textFormat = Format.createTextSampleFormat(null, MimeTypes.TEXT_SSA,
                        null, Format.NO_VALUE, Format.NO_VALUE, null, null, 0);
            } else {
                textFormat = Format.createTextSampleFormat(null, MimeTypes.TEXT_VTT,
                        null, Format.NO_VALUE, Format.NO_VALUE, null, null, 0);
            }

            Uri uri = Uri.parse(videoSubtitles);
            MediaSource subtitleSource = new SingleSampleMediaSource.Factory(mediaDataSourceFactory).createMediaSource(uri, textFormat, C.TIME_UNSET);

            mergedMediaSources[i] = new MergingMediaSource(mediaSources[i], subtitleSource);
        }
    } else {
        Toast.makeText(context, R.string.toast_subtitles_not_supported, Toast.LENGTH_LONG).show();
    }
}

// Concatenate all parts - with or without subtitles
ConcatenatingMediaSource concatenatedMediaSource;
if (mergedMediaSources == null) {
    concatenatedMediaSource = new ConcatenatingMediaSource(mediaSources);
} else {
    concatenatedMediaSource = new ConcatenatingMediaSource(mergedMediaSources);
}

exoPlayer.prepare(concatenatedMediaSource);
```

### Link to test content
Video parts:
https://mangawatcherx.com/exotest/part1.mp4
https://mangawatcherx.com/exotest/part2.mp4
Subs parts:
https://mangawatcherx.com/exotest/sub1.vtt
https://mangawatcherx.com/exotest/sub2.vtt

### Version of ExoPlayer being used
2.9.0

### Device(s) and version(s) of Android being used
Xiaomi Redmi 4X - Android 8.1 AOSP - test device
Users with many others devices reported about this issue

**Comment by AquilesCanta** [comment]
It would seem to me that you are using the same URI for each SingleSampleMediaSource. Can you check that is not the case?

**Comment by AniLabXTeam** [comment]
> It would seem to me that you are using the same URI for each SingleSampleMediaSource. Can you check that is not the case?

It fixed problem. In code i have other block that merge subtitles for whole movie part so this var "leaked" into this code. Thank you!
