### ISSUE TITLE
adaptive bitrate

### ISSUE THREAD

**Issue by ummerakbar45** [google/ExoPlayer#4909]
How can I check adaptive bitrate or resulation like youtube shows 144 , 240 etc.
I mean how can I check video changes bitrate.
I have hls videos but exoplayer start buffering without switching to low bitrate

**Comment by AquilesCanta** [comment]
There are two questions here, I suppose:

> How can I check adaptive bitrate or resulation like youtube shows 144 , 240 etc.
I mean how can I check video changes bitrate.

Have a look at the DemoApp. When you play a video, at the top of the screen you will see a short text in white with black background. The code that backs this can be found in `DebugTextViewHelper#getVideoString`. Also relevant is `VideoListener#onVideoSizeChanged`.

> I have hls videos but exoplayer start buffering without switching to low bitrate

Depends on the initial bitrate estimate that the Player is using, but this is not inherently an issue. Please fill the [issue template](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE) if you think there is a bug in ExoPlayer.

**Comment by ummerakbar45** [comment]
Thanks for your reply please provide link for DebugTextViewHelper.
How can I convert 560kb/s to resulation , I mean what bit rate is equal to
144 , 240 and so on.
Is it possible , I add my own url in demo app and tested is bitrate
switching based on bandwidth, if yes please provide steps.

**Comment by AquilesCanta** [comment]
Here is a link to [DebugTextViewHelper](https://github.com/google/ExoPlayer/blob/release-v2/library/ui/src/main/java/com/google/android/exoplayer2/ui/DebugTextViewHelper.java). The resolution will be available in the video format if the manifest declares the resolution.
