### ISSUE TITLE
Support for Redundant Streams

### ISSUE THREAD

**Issue by jpearl** [google/ExoPlayer#4914]
Is there any reason (historical or otherwise) that Exo can't or shouldn't support [redundant streams](https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/StreamingMediaGuide/UsingHTTPLiveStreaming/UsingHTTPLiveStreaming.html#//apple_ref/doc/uid/TP40008332-CH102-SW22)?

It appears that track selection is done purely by bandwidth for adaptive bitrate

**Comment by AquilesCanta** [comment]
You can always customize track selection to pick whichever track you want. Also worth checking out this [blogpost](https://medium.com/google-exoplayer/load-error-handling-in-exoplayer-488ab6908137) about load error handling. In the case of blacklisting, ExoPlayer may very well pick a redundant stream. If you think this is not the case, please fill the issue template.
