### ISSUE TITLE
Seeking in radio streams

### ISSUE THREAD

**Issue by harris914** [google/ExoPlayer#4917]
I'm working on ExoPlayer 2.6.0 for a Radio streaming app. Radio is playing is fine, but when i try to add seekTo for +/-30 seconds it always starts the streaming from 0. In the debug mode, player seeks to +30 seconds but as soon as setPlayWhenReady() is set it goes back to start from 0. It has been a long time i've been looking for this solution so decided to ask here. I will post my code here to if needed. Any help will be appreciated. Thanks

**Comment by harris914** [comment]
**This is my code for +30 seconds implementation.**
ivForward.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                try {
                    if (exoPlayer != null && Constants.isMediaPlaying) {
                        exoPlayer.setPlayWhenReady(false);
                        Constants.isMediaPlaying = false;
                        long bufferPosition = exoPlayer.getBufferedPosition();
                        long currentPosition = exoPlayer.getCurrentPosition();
                        if ((currentPosition + 30000) < bufferPosition + 50) {
                            exoPlayer.seekTo(exoPlayer.getCurrentWindowIndex(), currentPosition + 30000);
                            exoPlayer.setPlayWhenReady(true);
                            Constants.isMediaPlaying = true;
                        }
                    }
                } catch (Exception e) {
                    MakeToast.show("Error moving forward");
                }
            }
        });

**Comment by ojw28** [comment]
Most likely you're trying to play a type of stream that doesn't support seeking. For live streams, you'll normally need them to be HLS or DASH with a well defined live window for seeking to work.

**Comment by ojw28** [comment]
Note that it's technically possible to support backward seeking in progressive radio streams, if the client has already played the target seek position and if it caches the stream locally. However this is not something we support (or have any near term plans to support). Proper support for seeking in live streams can be provided by the broadcaster using HLS / DASH if they want to support this use case.

**Comment by harris914** [comment]
I'm using Shoutcast APIs for the radio streams. and according to the APIs. the streams are MP3(mpeg) or AAC. Now can you tell me does Exoplayer support these media types? and as far as i have searched, MPEG is Dash. Please correct me if i'm wrong.

**Comment by ojw28** [comment]
We support seeking in on-demand MP3 and (to a limited extent) AAC files, but we do not support seeking in live MP3 or AAC streams.

> and as far as i have searched, MPEG is Dash. Please correct me if i'm wrong.

MP3 is not the same as MPEG DASH.

https://en.wikipedia.org/wiki/Moving_Picture_Experts_Group
https://en.wikipedia.org/wiki/MP3
https://en.wikipedia.org/wiki/Dynamic_Adaptive_Streaming_over_HTTP

**Comment by harris914** [comment]
Can you please let me know how to program ExoPlayer to continue playback till buffered position if the internet gets turned off? For example, i have set 20 seconds to BUFFER BEFORE before actually starting the playback. Now if the buffered position is around 40 seconds and payback was around, say, 12 seconds and internet got turned off, now playback should continue till the buffered position i.e. 40 seconds before turning off. How can i achieve this thing? I'm attaching the loadControl object that i have used in my code. 'bufferBefore' is the value in seconds that a user can choose. 
`loadControl = new DefaultLoadControl(
                new DefaultAllocator(true, C.DEFAULT_BUFFER_SEGMENT_SIZE),
                DEFAULT_MIN_BUFFER_MS,
                DEFAULT_MAX_BUFFER_MS,
                bufferBefore * 1000,
                DefaultLoadControl.DEFAULT_BUFFER_FOR_PLAYBACK_AFTER_REBUFFER_MS
        );`

**Comment by ojw28** [comment]
This was fixed in `2.7.0`.

**Comment by harris914** [comment]
So you're saying i should move to 2.7.0 and this will work fine?

**Comment by ojw28** [comment]
I'm saying moving to 2.7.0 will cause playback to continue till buffered position if the internet gets turned off (without you having to do anything special). Seeking in this type of stream remains unsupported as per my comment above.

**Comment by harris914** [comment]
Yes i have tried it, it works even i turned off my internet. Can you please tell me on which parameter should i place my paramater for BEFORE BUFFER that user will enter and the boolean "prioritizeTimeOverSizeThresholds" should be true or false?

**Comment by ojw28** [comment]
I don't really understand the question. If in doubt, just use the default values.

**Comment by harris914** [comment]
In my application we have given user an option BUFFER BEFORE in seconds. This is basically pre-buffer before playing. So i user selects, say, 15 seconds buffer before value then player should load 15 seconds of stream before actually starting the playback. So where should i use this value in DefaultLoadControl constructor?

**Comment by ojw28** [comment]
```
* @param bufferForPlaybackMs The duration of media that must be buffered for playback to start
*     or resume following a user action such as a seek, in milliseconds.
* @param bufferForPlaybackAfterRebufferMs The default duration of media that must be buffered
*     for playback to resume after a rebuffer, in milliseconds. A rebuffer is defined to be
*     caused by buffer depletion rather than a user action.
```

**Comment by harris914** [comment]
Also can you tell me how to keep a buffer while playing the stream? We have an option of BUFFER SIZE, which means when user selects selects a value for it, the player should keep a buffer of that much time while the playback is working. Any option for this in ExoPlayer?

**Comment by ojw28** [comment]
`DefaultLoadControl.Builder` is pretty well documented:
```
minBufferMs - The minimum duration of media that the player will attempt to ensure is
    buffered at all times, in milliseconds.
maxBufferMs - The maximum duration of media that the player will attempt to buffer, in
    milliseconds.
```
Please [read the Javadoc](https://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/DefaultLoadControl.Builder.html) for more details.

**Comment by harris914** [comment]
I faced a problem. That when the internet gets turned off, then as per our discussion the music plays for the buffered time now, but it does not resume when the internet is back on. Can you guide me how to do it?

**Comment by ojw28** [comment]
If playback hasn't failed then it should resume when the internet is back on. Please provide concrete reproduction steps if you want us to take a look. If playback has failed then you need to re-prepare the player.

**Comment by harris914** [comment]
Thank you i was able to perform this functionality. During playback, if my device gets locked the playback stops. and as soon as i unlock the device it resumes. And it is a device specific issue as far as i have looked into. On Android MArshmallow device it stopped, but on Android 5.1 , Android Oreo and Android Pie it worked fine. Can you tell me how to overcome it?

**Comment by ojw28** [comment]
Please see [this FAQ](https://google.github.io/ExoPlayer/faqs.html#how-do-i-keep-audio-playing-when-my-app-is-backgrounded).

**Comment by harris914** [comment]
I created a foreground service as mentioned in the FAQ but still the problem persists in some devices. Wakelock is also necessary for it?

**Comment by ojw28** [comment]
The FAQ already provides an answer to that question :).
