### ISSUE TITLE
HLS aac audio stream cant play, player's state stays buffering

### ISSUE THREAD

**Issue by xpleemoon** [google/ExoPlayer#4918]
### Issue description
I have HLS aac (HE-AACv2) streams and try to play using ExoPlayer. The player initializes and displays video controls, with the debug overlay info displaying playWhenReady=true and playBackState=buffering and successfully displaying content's duration, but stays there and no playback happens.

> I found [#4184](https://github.com/google/ExoPlayer/issues/4184) and try to use [DefaultHlsExtractorFactory](https://github.com/google/ExoPlayer/commit/e50214a5a1fd378d66db0ab088f1d9a4f2ccb2d9#diff-261f61e52c2b73f5d4389826e532b86c)( [FLAG_ALLOW_NON_IDR_KEYFRAMES](https://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/extractor/ts/DefaultTsPayloadReaderFactory.html#FLAG_ALLOW_NON_IDR_KEYFRAMES)), but state does not change.

### Link to test content
content: [http://open.ls.qingting.fm/live/386/24k.m3u8](http://open.ls.qingting.fm/live/386/24k.m3u8)

> I can play the content, with browser

### Version of ExoPlayer being used
ExoPlayer 2.9.0

### Device(s) and version(s) of Android being used
Device: vivo Y66i A
OS version: Android 7.1.2

### Playback event log output
The onDecoderX() methods does not be invoked，with using `EventLogger`. No exception or error is thrown. Following the logger's output the player simply stalls between the following logs:
```
D/EventLogger: state [22.75, 0.00, window=0, true, BUFFERING]
D/EventLogger: timelineChanged [23.36, 35.20, window=0, periodCount=1, windowCount=1, reason=PREPARED
      period [?]
D/EventLogger:   window [56.32, true, true]
D/EventLogger: ]
D/EventLogger: mediaPeriodCreated [23.40, 35.20, window=0, period=0]
D/EventLogger: loading [23.41, 35.20, window=0, period=0, true]
D/EventLogger: timelineChanged [31.60, 28.16, window=0, period=0, periodCount=1, windowCount=1, reason=DYNAMIC
      period [?]
D/EventLogger:   window [56.32, true, true]
    ]
D/EventLogger: timelineChanged [43.94, 21.12, window=0, period=0, periodCount=1, windowCount=1, reason=DYNAMIC
      period [?]
D/EventLogger:   window [56.32, true, true]
    ]
D/EventLogger: timelineChanged [54.39, 7.04, window=0, period=0, periodCount=1, windowCount=1, reason=DYNAMIC
D/EventLogger:   period [?]
D/EventLogger:   window [56.32, true, true]
    ]
```

**Comment by tonihei** [comment]
I can reproduce the issue and it seems the HlsSampleStreamWrapper isn't finishing preparation because the H264Reader never reports its format. Given that this is supposed to be an audio-only stream, it's unclear to me where this H264 track is coming from. @AquilesCanta can you take a look? Even if this is bad media, I think it shouldn't continue buffering forever bur rather throw an exception at some point.

**Comment by AquilesCanta** [comment]
Try using FLAG_IGNORE_H264_STREAM instead of FLAG_ALLOW_NON_IDR_KEYFRAMES.

It seems to me that the PMT declares a video stream (on PID 256) for which there are no TS packets.
