### ISSUE TITLE
Why does not exoplayer pauses background music when video plays

### ISSUE THREAD

**Issue by ummerakbar45** [google/ExoPlayer#4919]
This is not issue but question
Why does not my video app stops background musics apps.
Wyink app is playing music, I want when I open my app and plays any video(on exoplayer 2.9.0) , song on wyink should pause, but this is not happening.

I did same test on wyink and youtube and when video plays on youtube, wyink paused video

**Comment by ojw28** [comment]
Your app should be requesting audio focus, which I'm guessing it's not doing. Note that your app should also pause itself if it subsequently loses audio focus. We recently made managing audio focus when using ExoPlayer much easier. Read [this blog post](https://medium.com/google-exoplayer/easy-audio-focus-with-exoplayer-a2dcbbe4640e) for details.
