### ISSUE TITLE
Ads dont play in Exoplayer with ImaAdsLoader

### ISSUE THREAD

**Issue by AlexDundar** [google/ExoPlayer#4920]
I`m trying to play ads in my video. I have url (I obtain it from backend) for obtaining vast xml file. And i put it to adsLoader in my code:

>     private MediaSource buildMediaSourceWithAds(Uri uri) {
>         ImaSdkSettings imaSdkSettings = ImaSdkFactory.getInstance().createImaSdkSettings();
>         imaSdkSettings.setAutoPlayAdBreaks(true);
>         imaSdkSettings.setDebugMode(true);
>         
>         adsLoader = new ImaAdsLoader.Builder(this)
>                 .setImaSdkSettings(imaSdkSettings)
>                 .setMediaLoadTimeoutMs(30 * 1000)
>                 .setVastLoadTimeoutMs(30 * 1000)
>                 .buildForAdTag(Uri.parse(videoAdsUrl)); // here is url for vast xml file
> 
> 
>         return new AdsMediaSource(
>                 buildMediaSource(uri),
>                 this,
>                 adsLoader,
>                 simpleExoPlayerView.getOverlayFrameLayout());
>     }

But when I start my app there is no ads in my exo video player.  Prerolls are just skipped, midrolls and postrolls stop video (when their time has come) and i cannt resume video and cannt see ads, only with reloading screen.
 Sometimes I see error "1009, The response does not contain any valid ads", sometimes another (with enabed debug mode).
I attached file with example vast xml, that doest play ads in exoplayer. 
[Not working Ad.txt](https://github.com/google/ExoPlayer/files/2455604/Not.working.Ad.txt)

Help me please, hot to fix this bug? How to make playing ads well, or, as a last resort, play video without stopping when ads cannt play? Thanks.

**Comment by AlexDundar** [comment]
Hm, I noticed that in all  `adEvent `objects in `AdEventListener ` in my example `adEvent.getAd().isLinear()` is always `false`, but in xml  `breakType="linear"` . Is there bug of `Exoplayer `of bug of `ImaAdsLoader`? Perhaps this is the reason of freezing video player when ads time has come?

**Comment by andrewlewis** [comment]
Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

**Comment by AlexDundar** [comment]
@andrewlewis  Ok.
**Issue description and reproduction steps :** I start Activiy with ExoPlayerView for playing video wth VAST video ads. When time for ads has come, video freezes and player stops. I must to move player seekbar and press play\stop for watching video after this. Or I must to reload activity. If ad is preroll video doesnt start.
**Version of ExoPlayer being used:** 2.8.4 and 2.9.0. The behavior is the same
**Link to test content:** I attached file with vast xml (2 prerolls, video cannt play it and freezes): 
[ADS not working.txt](https://github.com/google/ExoPlayer/files/2459468/ADS.not.working.txt) and file 
with AdEvent object in json [AdEvent.txt](https://github.com/google/ExoPlayer/files/2459478/AdEvent.txt)
**Device(s) and version(s) of Android being used:** Google pixel with android 9.0, Xiaomi Redmi note 5 with android 8.1. I think this issue doest depend on the device and os version.

**Comment by andrewlewis** [comment]
Closing this issue on the assumption we're now using #4941 to track it. If that's a separate issue please let me know and I'll reopen this one.
