### ISSUE TITLE
How to build .jar with the exoplayer module?

### ISSUE THREAD

**Issue by Romantic-LiXuefeng** [google/ExoPlayer#4927]
I have a old  project which is developed with the ide Eclipse, The project just needs the hls,core,ui three libraries. How to build the .jar s? Hope to give me some help! 
I use the least release branch V2.9.0

**Comment by ojw28** [comment]
> I have a old project which is developed with the ide Eclipse

We don't support this. You really need to be using Android Studio and aars at this point.
