### ISSUE TITLE
ExoPlayer doesnt play one local mp4 file

### ISSUE THREAD

**Issue by AlexDundar** [google/ExoPlayer#4928]
I tested on device Samsung galaxy s6 edge+. OS version is 7.0.
I have local mp4 file in `raw `folder. Here is the file: https://cdn.shanahanparker.bid/media/5/5/v55115125630675_141.mp4 and
it plays well from browser. But when I download it, put into `raw ` folder and play on `exoplayer ` I see only gray background instead of video and I hear sound of this video.

Here is my code for playing local video:

```
DefaultHttpDataSourceFactory httpDataSourceFactory = new DefaultHttpDataSourceFactory(userAgent,
                    bandwidthMeter,
                    20 * 1000,
                    20 * 1000,
                    true);
            DefaultDataSourceFactory defaultDataSourceFactory = new DefaultDataSourceFactory(getActivity(),
                    bandwidthMeter,
                    httpDataSourceFactory);
            DataSpec dataSpec = new DataSpec(RawResourceDataSource.buildRawResourceUri(R.raw.localvideo));
            RawResourceDataSource rawResourceDataSource = new RawResourceDataSource(getActivity());
            rawResourceDataSource.open(dataSpec);
            MediaSource mediaSource = new ExtractorMediaSource.Factory(defaultDataSourceFactory)
                    .createMediaSource(rawResourceDataSource.getUri());
            player.prepare(mediaSource, false, false);
```

**Comment by tonihei** [comment]
The file also fails to play in the browser and on two other devices. The failure is happening on a decoder level which indicates that the media itself is likely to be malformed.
