### ISSUE TITLE
SubtitleView throw a NPE.

### ISSUE THREAD

**Issue by Ood-Tsen** [google/ExoPlayer#493]
After I merge the code of path [ Step towards enhanced Webvtt parser to support HTML-rich captions and… ](https://github.com/google/ExoPlayer/commit/658a7ffba59b94f028b5e3a0b51ad853ab3781d2).

After I open a HLS link and enable text render,  I got a NPE (Null Point Exception).

The test link is in the demo app.

>    new Sample("Apple master playlist",
        "https://devimages.apple.com.edgekey.net/streaming/examples/bipbop_4x3/"
        + "bipbop_4x3_variant.m3u8", DemoUtil.TYPE_HLS),

The call stack of the Exception is in the following.

> D/AndroidRuntime( 4165): Shutting down VM
E/AndroidRuntime( 4165): FATAL EXCEPTION: main
E/AndroidRuntime( 4165): Process: com.google.android.exoplayer.demo, PID: 4165
E/AndroidRuntime( 4165): java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
E/AndroidRuntime( 4165): 	at android.text.StaticLayout.<init>(StaticLayout.java:49)
E/AndroidRuntime( 4165): 	at com.google.android.exoplayer.text.SubtitleView.computeMeasurements(SubtitleView.java:236)
E/AndroidRuntime( 4165): 	at com.google.android.exoplayer.text.SubtitleView.onMeasure(SubtitleView.java:193)
E/AndroidRuntime( 4165): 	at android.view.View.measure(View.java:17536)

**Comment by ojw28** [comment]
I think this is fixed already, in https://github.com/google/ExoPlayer/commit/ac54b4f696d65fe03533af6e7428c751ceb51b35#diff-e9fd670327a94df1ab96714b095f4985R233

**Comment by Ood-Tsen** [comment]
yes, it fixed.
