### ISSUE TITLE
Is there any sample ExoPlayer + OpenGL for 360 video?

### ISSUE THREAD

**Issue by JamesXu20150314** [google/ExoPlayer#4932]
Hello,

Who can share a sample ExoPlayer + OpenGL for 360 video?

Thanks.

**Comment by tonihei** [comment]
There are some 360 videos in our demo app under the "360" header.
See here: [media.exolist.json](https://github.com/google/ExoPlayer/blob/release-v2/demos/main/src/main/assets/media.exolist.json#L563)
