### ISSUE TITLE
Exoplayer does not take the AdaptationSet with the highest bitrate on default

### ISSUE THREAD

**Issue by userdimi** [google/ExoPlayer#4933]
I try to play this [DASH ](https://demo.unified-streaming.com/video/tears-of-steel/tears-of-steel-multikey-cenc.ism/.mpd)File in the Exoplayer example app. When I start the video, the Exoplayer does not play the AdaptionSet with the highest bitrate.

Expected: AdaptationSet id=5 with maxBandwith 2223000 should be played on default
Actual: AdaptationSet id= 4 with maxBandwith 1018000 is playing on default

How can I configurate the Exoplayer to play allways the AdaptationSet with the highest bitrate on default?

**Comment by tonihei** [comment]
Please have a look at the [forceHighestSupportedBitrate](https://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/trackselection/DefaultTrackSelector.Parameters.html#forceHighestSupportedBitrate) parameter of the [DefaultTrackSelector](https://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/trackselection/DefaultTrackSelector.html). Does that solve your issue?

**Comment by ojw28** [comment]
The solution suggested above might select the highest bitrate stream, but it wont then allow adaptation to any of the lower quality streams in the other adaptation set

Why are there two video adaptation sets to start with? One of the goals of DASH is to allow seamless adaptation between representations, but this requires the manifest to indicate that such adaptation is possible. There are two ways I'm aware of to indicate that seamless adaptation is possible. The first is to put all of the video representations into a single adaptation set. The second is to use the `urn:mpeg:dash:adaptation-set-switching:2016` as described in [DASH IF IOP Section 3.8](https://dashif.org/docs/DASH-IF-IOP-v4.2-clean.pdf).

If the reason you're splitting into two adaptation sets is to specify different content protection elements on the higher quality streams, then IIRC two video adaptation sets is correct, but you should look at using `urn:mpeg:dash:adaptation-set-switching:2016` to indicate support for switching between them. Doing this will likely resolve your problem.

**Comment by userdimi** [comment]
@ojw28  Thank you  for your quick response. As you already suspected, I split the stream in two adaptation set for the security reasons, to play out SD or HD content depend if security requirements are met or not. I will take a look inside the document that you send me. I hope, I will find the solution for my problem there.

**Comment by tonihei** [comment]
Just to add to that: even if you allow adaption between the sets, you may still see adaptation set 4 selected initially depending on the initial bandwidth estimate. If you always want to start in the highest quality immediately but keep the option open to switch down later if the bandwidth is not enough, you can override the initial bandwidth estimate in the `DefaultBandwidthMeter.Factory` instead.

**Comment by ojw28** [comment]
I'm going to close this on the assumption that `urn:mpeg:dash:adaptation-set-switching:2016` is what you need to fix this. Please feel free to respond here if you found that was not the case.
