### ISSUE TITLE
IMA SDK AdEventType.STARTED event is not always triggered 

### ISSUE THREAD

**Issue by mustafasevgi** [google/ExoPlayer#4938]
Hello,

I try to play ad audio pre-roll jingle with hls stream. AdEventType.STARTED event is not always triggered on the AdEvent.AdEventListener.onAdEvent. So player play jingle(2-3 ms) and after skip media. You can see log below.

Logcat output:

> Unexpected loadAd in an ad group with no remaining unavailable ads
> ad event type: LOADED
> ad event type: LOADED
> W/ImaAdsLoader: Unexpected loadAd in an ad group with no remaining unavailable ads
> ad event type: CONTENT_PAUSE_REQUESTED
> W/ImaAdsLoader: Unexpected playAd without stopAd
> ad event type: CONTENT_RESUME_REQUESTED
> D/SDK_DEBUG: Destroying NativeVideoDisplay
> ad event type: ALL_ADS_COMPLETED

```
exoplayer version: 2.8.4
exoplayer ima extension version: 2.8.4

device: Huawei Nexus 6P
android os version:8.1.0

demo-ima app branch: release-v2
```

Can you help please,
Thanks.

**Comment by andrewlewis** [comment]
Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE). In particular, please provide the ad tag you're trying to play here, or via email to dev.exoplayer@gmail.com.

**Comment by andrewlewis** [comment]
I don't think we received further information or the ad tag, so closing. Please provide the requested information if you want us to investigate this.
