### ISSUE TITLE
"Google Glass" link is dead ?

### ISSUE THREAD

**Issue by Ood-Tsen** [google/ExoPlayer#494]
When I play the test link "Google Glass " ,

>    new Sample("Google Glass",
        "http://www.youtube.com/api/manifest/dash/id/bf5bb2419360daf1/source/youtube?"
        + "as=fmp4_audio_clear,fmp4_sd_hd_clear&sparams=ip,ipbits,expire,source,id,as&ip=0.0.0.0&"
        + "ipbits=0&expire=19000000000&signature=51AF5F39AB0CEC3E5497CD9C900EBFEAECCCB5C7."
        + "8506521BFC350652163895D4C26DEE124209AA9E&key=ik0", DemoUtil.TYPE_DASH),
    new Sample("Google Play",

I got a SocketTimeoutException, is this link dead ?

> E/EventLogger(30959): com.google.android.exoplayer.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to http://r2---sn-45gx5nuvox-u2x6.c.youtube.com/videoplayback?id=bf5bb2419360daf1&itag=140&source=youtube&ratebypass=yes&mime=audio/mp4&gir=yes&clen=2176903&lmt=1429785882767638&dur=135.557&signature=22EF61B4856C510C9268F98A66393095AC39E876.0EE05B3C88833D17C46FDA1F781ECFE746029338&key=cms1&ip=39.9.153.33&ipbits=0&expire=2147483647&sparams=clen,dur,expire,gir,id,ip,ipbits,itag,lmt,mime,mm,mn,ms,mv,pcm2cms,pl,ratebypass,source&mm=31&mn=sn-45gx5nuvox-u2x6&ms=au&mt=1432563455&mv=m&pcm2cms=yes&pl=21
E/EventLogger(30959): 	at com.google.android.exoplayer.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:196)
E/EventLogger(30959): 	at com.google.android.exoplayer.upstream.DefaultUriDataSource.open(DefaultUriDataSource.java:160)
E/EventLogger(30959): 	at com.google.android.exoplayer.chunk.InitializationChunk.load(InitializationChunk.java:174)
E/EventLogger(30959): 	at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:242)
E/EventLogger(30959): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
E/EventLogger(30959): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/EventLogger(30959): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/EventLogger(30959): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/EventLogger(30959): 	at java.lang.Thread.run(Thread.java:818)
E/EventLogger(30959): Caused by: java.net.SocketTimeoutException

**Comment by ojw28** [comment]
This is working fine for me. It may have been a temporary issue.
