### ISSUE TITLE
Disable buffer in Exoplayer for HLS

### ISSUE THREAD

**Issue by anandsingh2903** [google/ExoPlayer#4942]
How can i disable buffer in Exoplayer for playing HLS.

**Comment by tonihei** [comment]
What do you mean by "disable buffer"? You need a buffer to play the media.

**Comment by anandsingh2903** [comment]
I am playing HLS stream it is playing fine in Exoplayer but when I change the channel the server starts throwing new channel HLS stream but my exoplayer gets stuck on previous video and doesn't start playing new HLS data stream.

**Comment by anandsingh2903** [comment]
What should i do in this case. I can see Discontinuity detected log in Exoplayer logs but the playlist.m3u8 which is coming from the network has ex-discontinuity tag.

**Comment by tonihei** [comment]
I'm not an expert on how HLS playlists are supposed to look like in such a case. Maybe @AquilesCanta can advise further.

**Comment by anandsingh2903** [comment]
Thanks. I can share the code with you if needed.

**Comment by AquilesCanta** [comment]
Can you provide a snapshot of a media playlist that includes a discontinuity along with its segments?

Once this is included, we will reopen the issue. We need to be able to reproduce ourselves to help you.
