### ISSUE TITLE
Is there a way to seek frames precisely ?

### ISSUE THREAD

**Issue by LightSun** [google/ExoPlayer#4943]
ExoPlayer Version: 2.9.0
Device:  nexus6p
---------------------------------------------------
i used exoplayer to play '.mp4' file. but seek has problems.
I want to seek frames precisely, is there a way to do it with exoplayer ?

**Comment by tonihei** [comment]
ExoPlayer does seek precisely except for formats which don't support exact seeking. See this [FAQ](https://google.github.io/ExoPlayer/faqs.html#why-are-some-media-files-not-seekable), and issues #328 and #3233.

**Comment by LightSun** [comment]
@tonihei is there a sample code ?  i used exoplayer to play '.mp4' file. but seek has problems.

**Comment by tonihei** [comment]
Seeking in mp4 files should be pretty accurate. Please explain your problem in more detail with reproduction steps and example media.

**Comment by LightSun** [comment]
@tonihei thanks.i fixed. Sorry,  It is my reason.
