### ISSUE TITLE
ExoPlayer2 vs ExoPlayer2 Amazon Port

### ISSUE THREAD

**Issue by marcochin** [google/ExoPlayer#4947]
There was a comment two years ago for another issue that the Amazon Port is not recommended due to quality issues that didn't look safe. I also saw in 2.8.3 release notes of the original ExoPlayer2 that there was FireOS compatibility improvements. Is this still the case today? Thanks.

**Comment by ojw28** [comment]
I would suggest that you always try and use vanilla ExoPlayer first. We made some compatibility improvements in 2.8.3 that minimized the difference between plain ExoPlayer and the Amazon fork, therefore reducing the need for it. 

It's pretty easy to see what's different between the two versions by looking at the changes Amazon patch on top, [here](https://github.com/amzn/exoplayer-amazon-port/commits/amazon/r2.8.4), of which there are now 8:

* FTVPI-1559 and the README update aren't important
* FIREFIVE-123614 and FTVPI-2218 both look like they add functionality that's disabled by default, so unless you've been explicitly turning it on, those don't do anything either
* FTVPI-1552 if I remember correctly is for very old tablets only, but I could be mistaken
* FTVPI -2396, FTVPI-2081, FTVPI-1553 all related to Dolby and Surround Sound. I think playback probably degrades gracefully to stereo without them, but I'm not sure about that

So probably vanilla ExoPlayer is fine unless Dolby/SurroundSound is super important to you.
