### ISSUE TITLE
NON IDR frames VIDEOS playing with alot of PIXELS on exoplayer

### ISSUE THREAD

**Issue by littlelitleStar** [google/ExoPlayer#4951]
I had a problem that EXO player wasnt playing non IDR frames videos, but i fixed it by adding the "FLAG_ALLOW_NON_IDR_KEYFRAMES" FLAG.

Afer adding that, Channels are playing good. But then i saw that those NON IDR KEYFRAME channels , are playing good in MOBILE SCREEN, but in Android boxes and Emulators like bluestacks. Its playing the video with a lot of pixels. Like this PHOTO. taken from an example

![image](https://user-images.githubusercontent.com/21010751/46908441-14870c80-cf23-11e8-8efc-ca9b3d40ef26.png)

Does anyone knows how to fix it. ?

Thank you

**Comment by andrewlewis** [comment]
Setting `FLAG_ALLOW_NON_IDR_KEYFRAMES` makes the player assume that all I-frames are synchronization points, but this assumption is not valid for all cases. This is probably an example of a stream where I-frames are not all synchronization points.

I think @AquilesCanta had a plan to handle some additional signaling for synchronization points via particular SEI NAL units, which might help, but it hasn't been implemented yet. We may want to mark this as an enhancement to support that if there's no existing issue.

**Comment by littlelitleStar** [comment]
Can we figure out any solution about this ?

**Comment by littlelitleStar** [comment]
The Thing that drives me crazy is that , On my mobile PHONE ,is working perfectly..

But on Android Boxes and Emulators , You cant watch them ,, too many PIXELS. image is too bad

**Comment by AquilesCanta** [comment]
I am not 100% sure that the SEI handling will help your issue, @psycomani. There is not much we can do about this, unfortunately. We don't have the time to properly investigate this right now.

**Comment by AquilesCanta** [comment]
Let's use #2841 to track handling of SEI recovery points. I cannot think of a solution for the device-specific decoding issue, though.

**Comment by littlelitleStar** [comment]
@AquilesCanta Ithink its a problem of DECODING the image.

I dont know why but in Android BOXES , and EMULATORS its not working.

But in PHONES ( small screen ) , its working perfectly ?

**Comment by AquilesCanta** [comment]
Yes, I understand, but I don't have the bandwidth to investigate this, unfortunately. First, I'll try to implement support for SEI recovery points. After that, we can see whether ExoPlayer can do something about this.

**Comment by AquilesCanta** [comment]
Actually, I'll close this issue. Please track #2841 and once support is pushed, give it a try. If rendering is still not working correctly, please file a new issue including all the information in the issue template.
