### ISSUE TITLE
Reset Exoplayer when AudioTrack Discontinuity is detected

### ISSUE THREAD

**Issue by anandsingh2903** [google/ExoPlayer#4956]
How can I reset the exoplayer whenever there's a audio track Discontinuity detected.

**Comment by andrewlewis** [comment]
There isn't a way to listen for this event directly at the moment (you'd need a custom audio sink). Could you provide some more details about when you see the discontinuities and why the built-in behavior of resynchronizing is not sufficient? Thanks.

**Comment by anandsingh2903** [comment]
I think built in behavior is working correctly, it's just that maybe i am testing recorded feed and the player is getting stuck when the feed starts again from same loop. Now i am trying to test it on Live Feed. Will report if the issue exists in the live feed also.
