### ISSUE TITLE
Unable to resolve dependency for exoplayer-library-core

### ISSUE THREAD

**Issue by anandsingh2903** [google/ExoPlayer#4958]
I have created a new project in latest android studio and when I am adding exoplayer locally as shown on github then I am getting unable to resolve dependency for exoplayer-library-core and same for HLS, UI, DASH

**Comment by andrewlewis** [comment]
Are you following the steps [here](https://github.com/google/ExoPlayer#locally)? Do you see the modules appearing as part of the project?

**Comment by anandsingh2903** [comment]
Yes, i followed exact steps but i guess something went wrong. Created new project and implemented the library again. Now it's working.
