### ISSUE TITLE
Is it possible to download only specific .ts files of HLS playlist?

### ISSUE THREAD

**Issue by AndreyAsadchy** [google/ExoPlayer#4959]
For example this playlist:

`#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:13
#ID3-EQUIV-TDTG:2018-10-10T20:51:50
#EXT-X-PLAYLIST-TYPE:EVENT
#EXT-X-MEDIA-SEQUENCE:0
#EXTINF:12.500,
0.ts
#EXTINF:12.500,
1.ts
#EXTINF:12.500,
2.ts
#EXTINF:12.500,
3.ts
#EXTINF:12.500,
4.ts
#EXTINF:12.500,
5.ts
#EXTINF:12.500,
6.ts
#EXTINF:12.500,
7.ts
#EXTINF:12.500, ...
1786.ts
#EXTINF:6.500, 
1787.ts
#EXT-X-ENDLIST
`

Can i download only from 100th to 400th?

**Comment by andrewlewis** [comment]
Support for partially downloading an adaptive stream is tracked by #1497.
