### ISSUE TITLE
Fixed resolution can only be formats[0]

### ISSUE THREAD

**Issue by crushonme** [google/ExoPlayer#496]
I have do some work on fixed evaluator for more resolution. However in my method， I have to deliver height parameter to FixedEvaluator from UI. Does anybody have better way?

**Comment by ojw28** [comment]
If you're playing on-demand (i.e. not live) content, then you could equally easily change DashRendererBuilder so that its videoRepresentationIndices only contains a single index. This will select a single stream for use at the start of playback. You can then use the normal FixedEvaluator.
