### ISSUE TITLE
Will the ExoPlayer Cast Extension be updated to use play-services-cast-framework:16.0.2?

### ISSUE THREAD

**Issue by jrw95** [google/ExoPlayer#4960]
### Question:
On behalf of our customer, is there a plan to update the ExoPlayer Cast extension to use this newer version of the Cast Sender framework?

### Issue description
A customer of ours has reported that some of their users are experiencing a bug that is apparently caused by an IllegalStateException thrown with play-services-cast-framework:16.0.1, in devices running Android 8.0 or greater. A description of the problem as fixed by Google in the Cast Sender v16.0.2 is available [here](https://developers.google.com/cast/docs/release-notes#spetember-5-2018).

### Reproduction steps
The customer themselves are unable to reproduce the crash, and are relying on Crashlytics logs. We have requested logs from the customer. We are also unable to reproduce the crash.

### Link to test content
None available at this time.

### Version of ExoPlayer being used
v2.7.0. We note that the latest release and dev versions of ExoPlayer (v2.9.0) also depend on Cast Sender v16.0.1.

### Device(s) and version(s) of Android being used
We are requesting hardware specifics, but the customer has noted that this crash happens on devices running Android 8.0 or greater.

### A full bug report captured from the device
We are unable to obtain an adb bugreport from the customer (as they can not obtain it from their users), but have requested Crashlytics logs.

**Comment by AquilesCanta** [comment]
The next version will depend on 16.0.3. Thanks!
