### ISSUE TITLE
Player becomes null on orientation change

### ISSUE THREAD

**Issue by Faiyyaz** [google/ExoPlayer#4962]
Hi,

I have to show different layout for different orientation so i have created 2 layout files for the same but the issue is if i toggle orientation then the player is recreated rather using the old player object & it leads to Decoder init failed: OMX.qcom.video.decoder.avc error.

So please help me what to do in this case

**Comment by Faiyyaz** [comment]
This has been solved by me :)

**Comment by ErAmrit** [comment]
Hi Faiyyaz, 

I am facing same issue, can you help me out please. On Device Lenovo k33a42

**Comment by Faiyyaz** [comment]
Try using this

```android:configChanges="orientation|screenSize|layoutDirection"```
