### ISSUE TITLE
Cannot compile ffmpeg extension for exoplayer

### ISSUE THREAD

**Issue by vuongxuanhong** [google/ExoPlayer#4963]
I tried to compile ffmpeg extension for exoplayer, but face to this problem

```code
/Users/vuongxuanhong/Library/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-gcc is unable to create an executable file.
C compiler test failed.

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.
```
I open the log file and this is the error:

```code
BEGIN /var/folders/fb/wwv_4h7d4ls30_gqbkhfm0lm0000gn/T//ffconf.nPojmj5F/test.c
    1	int main(void){ return 0; }
END /var/folders/fb/wwv_4h7d4ls30_gqbkhfm0lm0000gn/T//ffconf.nPojmj5F/test.c
/Users/vuongxuanhong/Library/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-gcc --sysroot=/Users/vuongxuanhong/Library/Android/sdk/ndk-bundle/platforms/android-27/arch-arm/ -march=armv7-a -mfloat-abi=softfp -march=armv7-a -c -o /var/folders/fb/wwv_4h7d4ls30_gqbkhfm0lm0000gn/T//ffconf.nPojmj5F/test.o /var/folders/fb/wwv_4h7d4ls30_gqbkhfm0lm0000gn/T//ffconf.nPojmj5F/test.c
/Users/vuongxuanhong/Library/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-gcc -Wl,--fix-cortex-a8 --sysroot=/Users/vuongxuanhong/Library/Android/sdk/ndk-bundle/platforms/android-27/arch-arm/ -march=armv7-a -pie -o /var/folders/fb/wwv_4h7d4ls30_gqbkhfm0lm0000gn/T//ffconf.nPojmj5F/test /var/folders/fb/wwv_4h7d4ls30_gqbkhfm0lm0000gn/T//ffconf.nPojmj5F/test.o
ld: unknown option: --sysroot=/Users/vuongxuanhong/Library/Android/sdk/ndk-bundle/platforms/android-27/arch-arm/
clang: error: linker command failed with exit code 1 (use -v to see invocation)
C compiler test failed.
```
I execute the code in README of ffmpeg extension. 

```code
COMMON_OPTIONS="\
    --target-os=android \
    --disable-static \
    --enable-shared \
    --disable-doc \
    --disable-programs \
    --disable-everything \
    --disable-avdevice \
    --disable-avformat \
    --disable-swscale \
    --disable-postproc \
    --disable-avfilter \
    --disable-symver \
    --disable-swresample \
    --enable-avresample \
    --enable-decoder=vorbis \
    --enable-decoder=opus \
    --enable-decoder=flac \
    " && \
cd "${FFMPEG_EXT_PATH}/jni" && \
(git -C ffmpeg pull || git clone git://source.ffmpeg.org/ffmpeg ffmpeg) && \
cd ffmpeg && \
./configure \
    --libdir=android-libs/armeabi-v7a \
    --arch=arm \
    --cpu=armv7-a \
    --cross-prefix="${NDK_PATH}/toolchains/arm-linux-androideabi-4.9/prebuilt/${HOST_PLATFORM}/bin/arm-linux-androideabi-" \
    --sysroot="${NDK_PATH}/platforms/android-27/arch-arm/" \
    --extra-cflags="-march=armv7-a -mfloat-abi=softfp" \
    --extra-ldflags="-Wl,--fix-cortex-a8" \
    --extra-ldexeflags=-pie \
    ${COMMON_OPTIONS} \
    && \
make -j4 && make install-libs && \
make clean && ./configure \
    --libdir=android-libs/arm64-v8a \
    --arch=aarch64 \
    --cpu=armv8-a \
    --cross-prefix="${NDK_PATH}/toolchains/aarch64-linux-android-4.9/prebuilt/${HOST_PLATFORM}/bin/aarch64-linux-android-" \
    --sysroot="${NDK_PATH}/platforms/android-27/arch-arm64/" \
    --extra-ldexeflags=-pie \
    ${COMMON_OPTIONS} \
    && \
make -j4 && make install-libs && \
make clean && ./configure \
    --libdir=android-libs/x86 \
    --arch=x86 \
    --cpu=i686 \
    --cross-prefix="${NDK_PATH}/toolchains/x86-4.9/prebuilt/${HOST_PLATFORM}/bin/i686-linux-android-" \
    --sysroot="${NDK_PATH}/platforms/android-27/arch-x86/" \
    --extra-ldexeflags=-pie \
    --disable-asm \
    ${COMMON_OPTIONS} \
    && \
make -j4 && make install-libs && \
make clean
```

How can i solve this problem ? I do on Mac OS Mojave

**Comment by andrewlewis** [comment]
Which NDK version are you using? Currently we only support up to r15c. See also #4940.

**Comment by vuongxuanhong** [comment]
Currently I used version 18, i changed to ndk r15c, and it works. Thanks @andrewlewis

**Comment by banic** [comment]
I also have a problem with build, with this error(same as above, but for linux ubuntu):

home/android-ndk-r15c/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc is unable to create an executable file.
C compiler test failed.


I tried with NDK versions 15c and 14b and it's always the same problem.

@andrewlewis Can you help? Thanks!

**Comment by andrewlewis** [comment]
@banic Do the detailed logs associated with the error describe what is going wrong?

**Comment by banic** [comment]
@andrewlewis 
I build it successfully.

Buti still not have audio with ac3.

Here is my log from logcat:

04-07 21:40:53.558 6472-6490/com.example.brankoriznic.exo_fmpg W/MediaCodecInfo: AssumedMaxChannelAdjustment: OMX.google.ac3.decoder, [1 to 6]
    AssumedMaxChannelAdjustment: OMX.google.ac3.decoder, [1 to 6]
04-07 21:40:53.571 6472-6554/com.example.brankoriznic.exo_fmpg I/OMXClient: MuxOMX ctor
04-07 21:40:53.576 6472-6553/com.example.brankoriznic.exo_fmpg I/MediaCodec: [OMX.amlogic.avc.decoder.awesome] setting surface generation to 6627331
04-07 21:40:53.577 6472-6554/com.example.brankoriznic.exo_fmpg D/ACodec_amlogic: query systemComposer 1
04-07 21:40:53.578 6472-6554/com.example.brankoriznic.exo_fmpg E/ACodec: [OMX.amlogic.avc.decoder.awesome] storeMetaDataInBuffers failed w/ err -2147483648
04-07 21:40:53.584 6472-6554/com.example.brankoriznic.exo_fmpg I/ACodec: codec does not support config priority (err -1010)
04-07 21:40:53.591 6472-6554/com.example.brankoriznic.exo_fmpg D/SurfaceUtils: set up nativeWindow 0xd1c07008 for 1920x1080, color 0x11, rotation 0, usage 0x2002900
04-07 21:40:53.591 6472-6554/com.example.brankoriznic.exo_fmpg W/ACodec: [OMX.amlogic.avc.decoder.awesome] setting nBufferCountActual to 8 failed: -1010
04-07 21:40:53.592 6472-6554/com.example.brankoriznic.exo_fmpg W/ACodec: [OMX.amlogic.avc.decoder.awesome] setting nBufferCountActual to 7 failed: -1010
04-07 21:40:53.637 6472-6558/com.example.brankoriznic.exo_fmpg I/OMXClient: MuxOMX ctor
04-07 21:40:53.761 6472-6558/com.example.brankoriznic.exo_fmpg I/ACodec: audio_extendformat:0
04-07 21:40:53.766 6472-6558/com.example.brankoriznic.exo_fmpg I/ACodec: codec does not support config priority (err -2147483648)
04-07 21:40:53.767 6472-6558/com.example.brankoriznic.exo_fmpg I/ACodec: codec does not support config operating rate (err -2147483648)
04-07 21:40:53.800 6472-6490/com.example.brankoriznic.exo_fmpg D/AudioTrack: Client defaulted notificationFrames to 8208 for frameCount 16416

**Comment by andrewlewis** [comment]
The logging about `OMX.google.ac3.decoder` suggests that `MediaCodecAudioRenderer` is still being used. Please make sure you've [enabled the right decoder](https://google.github.io/ExoPlayer/supported-formats.html#ffmpeg-extension) before building ffmpeg, and the renderers factory is [set up to use the extension](https://github.com/google/ExoPlayer/blob/release-v2/extensions/ffmpeg/README.md#using-the-extension).
