### ISSUE TITLE
Add support for gapless audio playback

### ISSUE THREAD

**Issue by th3hamm0r** [google/ExoPlayer#497]
Hi,
I have to implement a music player which plays media sequentially without gaps. I've implemented a prototype that uses multiple (at least two) ExoPlayer instances, which starts the next ExoPlayer instance for the following audio file only milliseconds before the currently playing instance finishes, just to avoid the gap. But of course this is far from perfect!

Is there a cleaner and more reliable solution for this with ExoPlayer?
I think of MediaPlayer's setNextMediaPlayer() (http://developer.android.com/about/versions/android-4.1.html#Gapless).

I want to use the ExoPlayer even for simple audio playback because of its extensibility (caching, streaming bytes from any source,...) and to avoid hacking around with [local proxies](http://stackoverflow.com/q/12701249/1394330) just to allow playing from custom byte streams for example.

**Comment by andrewlewis** [comment]
We don't currently have support for gapless playback. I'll use this issue as a tracking bug for the enhancement. Thanks!

**Comment by andrewlewis** [comment]
We now extract gapless playback metadata, so the remaining work for this is tracked by #1270 (playlist support).

**Comment by boywithk9** [comment]
Is ogg now gapless also? You only mentioned mp3/mp4.

**Comment by andrewlewis** [comment]
@boywithk9 It looks like the decoding process for Ogg Vorbis trims padding, so it should work already.

**Comment by th3hamm0r** [comment]
@boywithk9 @andrewlewis fyi: I'm already using the ExoPlayer for gapless playback of ogg and mp3 files. For mp3 of course, you have to add the correct metadata for gapless playback (something like: `ffmpeg -i input.ogg -f wav - | lame -V 2 --noreplaygain - output.mp3`)

**Comment by boywithk9** [comment]
OGG is not gapless with Mediaplyaer.
