### ISSUE TITLE
Getting the resolution(1080p,430p etc) when a video is played in "AUTO" in quality

### ISSUE THREAD

**Issue by meenukrishnamurthy** [google/ExoPlayer#4971]
Is there a way in which we can show the resolution when auto is selected in quality.I just want to show if auto is selected the resolution its selecting to play the video

**Comment by tonihei** [comment]
Please add a `VideoListener` to `SimpleExoPlayer.addVideoListener`. The callback `onVideoSizeChanged` notifies you when the currently displayed size changes. 

If you need the `Format` object of the selected quality, please add an `AnalyticsListener` and listen to `onDownStreamFormatChanged` which is similar but gives you the `Format` object and selection reason and other data.

**Comment by meenukrishnamurthy** [comment]
I am actually using an older fork.Have added exoplayer as library in my app.There is no analytics listener in it.I just want to know which track is being selected while playing Auto.My video format is HLS

**Comment by tonihei** [comment]
You can use `addVideoDebugListener` on older versions with the same callback. 

Note that for HLS specifically, the `Format` reported in `onDownStreamFormatChanged` may include both video and audio if they are muxed together. In this case you'll only get the actual video size when listening to `onVideoSizeChanged`. Depends on what information you need.

**Comment by meenukrishnamurthy** [comment]
thanks i used onVideoSizeChanged.Its working
