### ISSUE TITLE
Bug: unable to play videos anymore using direct URL ?!

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [google/ExoPlayer#4972]
I have no idea what went wrong, but I remember it worked fine before.

What I've tried:
- playing multiple URLs, including both http and https ones.
- setting to targetSdk 27 (because of [this issue](https://github.com/google/ExoPlayer/issues/4599))
- adding the xml file as written [here ](https://developer.android.com/training/articles/security-config), but the IDE has put an error mark on the content for some reason. Reported about this [here](https://issuetracker.google.com/issues/117855274).
- using both stable and newer versions of gradle file.
- tried running on Pixel 2 with Android P, and on Nexus 4 with Android 4.4.x
- tried converting to android-x
- tried updating to 2.9.0 version of exoplayer, but then I get an exception of Error inflating class com.google.android.exoplayer2.ui.PlayerView . 

Here's the code (available in attached file too : [ExoPlayerTest.zip](https://github.com/google/ExoPlayer/files/2486955/ExoPlayerTest.zip) ) : 

```
class MainActivity : AppCompatActivity() {
    private var player: SimpleExoPlayer? = null
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
    }

    override fun onStart() {
        super.onStart()
        player = ExoPlayerFactory.newSimpleInstance(this, DefaultTrackSelector())
        playerView.player = player
        val dataSourceFactory = DefaultDataSourceFactory(this, getUserAgent(this))
//        val url="http://file-examples.com/wp-content/uploads/2017/04/file_example_MP4_480_1_5MG.mp4"
        val url="https://www.sample-videos.com/video/mkv/720/big_buck_bunny_720p_2mb.mkv"
        val mediaSource = ExtractorMediaSource.Factory(dataSourceFactory).createMediaSource(Uri.parse(url))
        player!!.prepare(mediaSource)
        playerView.useController = false
        player!!.playWhenReady = true
        player!!.repeatMode = Player.REPEAT_MODE_ALL
    }

    override fun onStop() {
        super.onStop()
        playerView.player = null
        player!!.release()
        player = null
    }

    companion object {
        @JvmStatic
        fun getUserAgent(context: Context): String {
            val packageManager = context.packageManager
            val info = packageManager.getPackageInfo(context.packageName, 0)
            val appName = info.applicationInfo.loadLabel(packageManager).toString()
            return Util.getUserAgent(context, appName)
        }
    }
}
```

**Comment by AndroidDeveloperLB** [comment]
I've tried now to modify the "demo-ima" sample of the repository, to play just the video, without ads, and it also failed.

See here:

[ExoPlayer.zip](https://github.com/google/ExoPlayer/files/2487263/ExoPlayer.zip)

Also tried to make a minimal sample for playing a video using latest API, and failed:
[MyApplication4.zip](https://github.com/google/ExoPlayer/files/2487487/MyApplication4.zip)

**Comment by AndroidDeveloperLB** [comment]
Seems this might be an issue with the URLs I've tried, as I've found now a url that works fine:

https://archive.org/download/big_buck_bunny_201801/big_buck_bunny.mp4

Probably all were server issues.

But how can I try http URLs? I've tried as instructed, and it didn't accept to be built.

Here are some video URLs that are supposed to be fine:

     "http://mirrors.standaloneinstaller.com/video-sample/TRA3106.3gp",
                "http://mirrors.standaloneinstaller.com/video-sample/P6090053.3gp",
                "http://mirrors.standaloneinstaller.com/video-sample/star_trails.3gp"

And it seems this issue is on Android P, but not on 4.4. Very odd that I got errors on both before. Probably server error.

**Comment by AndroidDeveloperLB** [comment]
Adding `android:usesCleartextTraffic="true"` into the manifest works fine.

But the instructions of `network-security-config` didn't work at all.

I wish I could know if it's possible to set it to work just for ExoPlayer, instead of the whole app.

**Comment by andrewlewis** [comment]
I don't think this can be set just for ExoPlayer if you're using standard HTTP stacks. It has to be at the app-level. It looks like you can do per domain configuration though, which might be useful.

**Comment by AndroidDeveloperLB** [comment]
@andrewlewis Is there an official way to check if it's http or https ?
Or would just checking the beginning of the URL (as string) suffice?

**Comment by andrewlewis** [comment]
I'd check [`uri.getScheme`](https://developer.android.com/reference/android/net/Uri.html#getScheme()).

**Comment by AndroidDeveloperLB** [comment]
@andrewlewis Thank you. Good idea.
