### ISSUE TITLE
Why the ts video format can't get the duration?

### ISSUE THREAD

**Issue by Romantic-LiXuefeng** [google/ExoPlayer#4977]
The ts url:
http://trnvd.cloud.ottcn.com/ts/20M/H265/2018/10/11/8ce88f1e63f74d4497ce380ebc4aacda_h26420000000aac256_1_20M.ts

**Comment by Romantic-LiXuefeng** [comment]
I use the Android MediaPlayer which can get the duration. But the ExoPlayer only play at the edge of the end which can get the duration. Is there any function to get the ts format duration when the ts format video size is large.

**Comment by Romantic-LiXuefeng** [comment]
I test the ts url which can get duration .(this ts video's size is not large enough)  http://srcvd.cloud.ottcn.com/wuxi/newmedia/2018/09/13/4eec143a809246a8bfb56827ade504e4_H2644500000aac128.ts
I am confused whether the ts video format size cause this .

**Comment by Romantic-LiXuefeng** [comment]
I used the latest release version 2.9.0.

**Comment by ojw28** [comment]
I tried the second test stream above with 2.9.0 in the demo app, and the duration is determined correctly. So I think you're mistaken.

**Comment by Romantic-LiXuefeng** [comment]
This test stream can't get the duration. http://trnvd.cloud.ottcn.com/ts/20M/H265/2018/10/11/8ce88f1e63f74d4497ce380ebc4aacda_h26420000000aac256_1_20M.ts

**Comment by ojw28** [comment]
That link doesn't work for me. Please could you provide a working test stream? Alternatively please mail the file as an attachment to `dev.exoplayer@gmail.com`, and update this issue to say that you've done so. Thanks!

**Comment by ojw28** [comment]
Closing due to lack of information.
