### ISSUE TITLE
Showing trackselector as 360p ,480p, 720p etc

### ISSUE THREAD

**Issue by Faiyyaz** [google/ExoPlayer#4982]
### Issue description
I am using trackselector component in one of the app but i want to show the quality as 360p, 480p, 720p rather than the resolution

### Version of ExoPlayer being used
2.9.0

**Comment by tonihei** [comment]
You can use `TrackSelectionView.setTrackNameProvider` to set your own provider of track names. The custom track name provided can map the format values to whatever you like them to be. For your specific question, it's probably best to override DefaultTrackNameProvider and just replace `buildResolutionString`.

**Comment by tonihei** [comment]
Closing because the question was answered. Feel free to reopen if not.
