### ISSUE TITLE
How to know if exoplayer detects any EXT-DISCONTINUITY tag in HLS stream

### ISSUE THREAD

**Issue by anandsingh2903** [google/ExoPlayer#4983]
Is there a method which gets executed whenever exoplayer detects a ext-x-Discontinuity tag.

How can reset the player at the point where exoplayer detects ext-discontinuity tag.

**Comment by andrewlewis** [comment]
I don't think there's a callback for this at the moment, though it shouldn't be necessary to reset the player when reaching a discontinuity. Over to @AquilesCanta to confirm/deny.

**Comment by anandsingh2903** [comment]
I get AudioTrack : Discontinuity Detected log in the exoplayer logs. Sometimes channel gets changed even though at that time also.. Audio changes immediately but the video changes after some seconds and sometimes player just gets stuck in buffering state even though when I seek forward or backward. Player starts playing changed video then.

**Comment by AquilesCanta** [comment]
I cannot think of a way to do this using the public APIs, unfortunately. As @andrewlewis points out, this shouldn't be necessary unless there is a non-supported track change in the channels. We might be able to provide more assistance with a media sample with which we can reproduce ourselves. If you provide a media sample, we'll reopen the issue.
