### ISSUE TITLE
export file(mp4 ,mp3) after download service completed

### ISSUE THREAD

**Issue by mupm1** [google/ExoPlayer#4990]
i want export final file from stream cache or download service complete.is it impossible?
if that isn't impossible, can i download a media file with other downloader and play that when download in progress and file not complete?

thanks.

**Comment by erdemguven** [comment]
It isn't possible to export files from cache but you can use a custom DataSink with TeeDataSource to write the data to a file. You should handle cases where file end is streamed before the data preceding it.

If you externally download the file and try to play it during download, the file would be only played until the point where it was downloading when the playback started.

**Comment by natario1** [comment]
@erdemguven could you please tell me if my understanding is correct - one could write the custom `DataSink`,  pass it to a `DownloaderConstructorHelper` that is used to construct a `DownloadManager`, and request a download using the download service.

In this case, as I see,
- There is no need to worry about data being streamed before the data preceding it
- There is no need to use `TeeDataSource` as the downloader task is to pass data to the cache thus to our custom sink

Is this correct? 

I'm also not sure if the data passed by the downloader to the cache sink is the actual buffer coming from the source, or if it is decoded/altered in any way. But I guess it's the source buffer.
