### ISSUE TITLE
Casting offline content

### ISSUE THREAD

**Issue by JanStoltman** [google/ExoPlayer#4995]
Does ExoPlayer Cast extension support casting offline content? I've followed [this](https://medium.com/google-exoplayer/downloading-adaptive-streams-37191f9776e) example and now I would like to cast one of the downloaded streams to Chromecast.
Can this be done from ExoPlayer's level or do I have to implement some kind of local server so that receiver app can request segments from this server?

**Comment by AquilesCanta** [comment]
> I have to implement some kind of local server so that receiver app can request segments from this server

This is correct. Note that this might not be possible with DRM-protected content.
