### ISSUE TITLE
Generate Signed Demo APK Fails

### ISSUE THREAD

**Issue by giladna** [google/ExoPlayer#4997]
Hi,

in order to avoid errors thrown  during Signing APK process
"Failed to resolve: play-services-basement"

in this build.gradle file 
https://github.com/google/ExoPlayer/blob/r2.9.0/build.gradle

It is required to  switch the order or the repositories in the buildscript and in the allprojects keys:

Working for me:

repositories {
        google()
        jcenter()
    }

BR
Gilad

**Comment by GonziMalaga** [comment]
I have the same problem, but is not only when signing, is with building the APK. 

I've openend another issue because I didn't see yours since I entered github one hour ago and didn't refresh it before creating the new issue.

**Comment by tonihei** [comment]
We had the same problem in the past when it solved itself after a while, see #4353. Worth checking again tomorrow to see if it's only temporary.

**Comment by GonziMalaga** [comment]
Okk for me it works changing the order...
```
    repositories {
        jcenter()
        google()
    }
```
to this
```
    repositories {
        google()
        jcenter()
    }
```

**Comment by ojw28** [comment]
We should probably do that in the pieces of documentation we have + our own gradle files, given this has happened again?

**Comment by jerrychong25** [comment]
Thanks @GonziMalaga, your solution works!

**Comment by YunanChen** [comment]
Thanks very much @GonziMalaga

**Comment by Mastrom10** [comment]
Worked for me!!!

**Comment by clickboxmobile** [comment]
For me worked like this

```
buildscript {
    repositories {
        maven {
            url "https://maven.google.com"
        }
        jcenter()
    }

    // Switch the Android Gradle plugin version requirement depending on the
    // installed version of Gradle. This dependency is documented at
    // http://tools.android.com/tech-docs/new-build-system/version-compatibility
    // and https://issues.apache.org/jira/browse/CB-8143
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.3'
    }
}

// Allow plugins to declare Maven dependencies via build-extras.gradle.
allprojects {
    repositories {
        maven {
            url "https://maven.google.com"
        }
        jcenter()
    }
}
```
