### ISSUE TITLE
CAN NOT COMPILE  (Error: Could not find play-services-basement.aar )

### ISSUE THREAD

**Issue by GonziMalaga** [google/ExoPlayer#4999]
Hi, I have a problem when compiling, with this error:

```
Could not find play-services-basement.aar (com.google.android.gms:play-services-basement:15.0.1).
Searched in the following locations:
    https://jcenter.bintray.com/com/google/android/gms/play-services-basement/15.0.1/play-services-basement-15.0.1.aar
```

It seems that is a problem from Google but maybe you know if there is any tip to avoid this message. One month ago it didn't appear.

**Comment by tonihei** [comment]
See #4997.

**Comment by GonziMalaga** [comment]
Yes sorry, I've openend another issue because I didn't see the previous one since I entered github one hour ago and didn't refresh the page before creating the new issue.

**Comment by tonihei** [comment]
Seems to be same issue still. We also had a similar issue in the past: #4353

**Comment by tonihei** [comment]
Closing this one and using the other issue to track.
