### ISSUE TITLE
ExoPlayer Audio Playback speed issue

### ISSUE THREAD

**Issue by Khushwant-singh** [google/ExoPlayer#50]
Hi,

I have used ExoPlayer in my app to stream live audio and it is working quite well. I have got complaints from few of the users that the playback speed is double than normal. I am still waiting to get the list of devices that are having this issue. Any idea why some of the devices have this issue??

I have used a very basic code to play audio

Uri builtUri = Uri.parse(BASE_URL);

```
    // Build the sample source
    FrameworkSampleSource sampleSource = new FrameworkSampleSource(this,
            builtUri, null, 1);

    // Build the track renderers
    TrackRenderer audioRenderer = new MediaCodecAudioTrackRenderer(
            sampleSource, null, true);

    // Build the ExoPlayer and start playback
    exoPlayer = ExoPlayer.Factory.newInstance(1);
    exoPlayer.prepare(audioRenderer);
    exoPlayer.setPlayWhenReady(true);
    exoPlayer.addListener(this);
```

Please note that I have tested ExoPlayer on Samsung and HTC phones and it does work very well.

Any help will be highly appreciated.

Thanks

**Comment by Ph1b** [comment]
We have the same problem [here](https://github.com/Ph1b/MaterialAudiobookPlayer/issues/129) and had a larger discussion about that issue.
There seems to be a larger group of devices that have this issue. Maybe exoplayer should check if as well if the device is supported in forehand and throw a DeviceNotSupportedException to make clear what is happening.
