### ISSUE TITLE
Full HD HLS streams are not playing in android exoplayer-v2

### ISSUE THREAD

**Issue by sankeertana** [google/ExoPlayer#5001]
Hello team,

         Exoplayer is not playing full hd hls streams, But I am able to play 720p Streams. Do I need to add some extra code for playing HD Streams of resolution 1920x1080.

**Comment by erdemguven** [comment]
Have you tried another device? We disable tracks which are not playable by device.

If you still can't play the streams, please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).
