### ISSUE TITLE
Looking for HLS spec around livestream window size mentioned in one of the comment

### ISSUE THREAD

**Issue by abhishekredspace** [google/ExoPlayer#5002]
Hi, exoplayer team,
I followed the comments in https://github.com/google/ExoPlayer/issues/1074 and have opened a ticket with my backend team based on it.  
Do you have any HLS spec to support this comment https://github.com/google/ExoPlayer/issues/1074#issuecomment-168541212

**Comment by ojw28** [comment]
I'm not sure I understand the question. I don't think the specification dictates how long the live window should be. But it's always going to be the case that if the window is too short, players are going to have a harder time performing well.
