### ISSUE TITLE
DownloadManager stopDownloads being ignored sometimes

### ISSUE THREAD

**Issue by Mariovc** [google/ExoPlayer#5007]
### Issue description
When stopping downloads sometimes this action is being ignored. The downloads keep downloading.

### Reproduction steps
I couldn't reproduce it with the same steps, so its not 100% reproducible

### Version of ExoPlayer being used
2.8.4

### Device(s) and version(s) of Android being used
Nexus 5 Android 6.0.1

I've seen some code was changed on `stop()` but I haven't seen any issue or release note regarding this bug. Was it solved on 2.9.0?

**Comment by erdemguven** [comment]
We fixed couple of issues but this wasn't one of them. It might still be fixed with the latest version so please try it.

**Comment by Mariovc** [comment]
I upgraded to 2.9.0 and I didn't get this error.
Probably using `cancelDownload()` instead of directly use `thread.interrupt();` solved this.
