### ISSUE TITLE
Not seekable audio

### ISSUE THREAD

**Issue by vicpinm** [google/ExoPlayer#5008]
### Issue description
I'm trying to play this audio:

http://audios.esradio.fm/espana/18/10/23/tertulia-de-herrero-el-congreso-rechaza-suspender-la-venta-de-armas-a-arabia-saudi-129520.mp3

This audio is not seekable, as isCurrentWindowSeekable() returns false. I assume there is something wrong with this audio, but native MediaPlayer is able to perform seek with the same url. 

### Link to test content
http://audios.esradio.fm/espana/18/10/23/tertulia-de-herrero-el-congreso-rechaza-suspender-la-venta-de-armas-a-arabia-saudi-129520.mp3

### Version of ExoPlayer being used
2.9.0

### Device(s) and version(s) of Android being used
Android version: Any
Devices: Samsung, Motorola, Oneplus, Xiaomi...

**Comment by ojw28** [comment]
Please see our [FAQs page](http://google.github.io/ExoPlayer/faqs.html#why-are-some-media-files-not-seekable).
