### ISSUE TITLE
Remove Learn More text

### ISSUE THREAD

**Issue by ummerakbar45** [google/ExoPlayer#5010]
### Issue description
Learn more navigates to specific url mentioned in VAST tag.
I want to remove/hide LEARN MORE text

### Reproduction steps
No steps

### Link to test content
No Data

### Version of ExoPlayer being used
IMA latest sdk
### Device(s) and version(s) of Android being used
in all version
### A full bug report captured from the device
How to remove/hide learn more text

**Comment by andrewlewis** [comment]
I'm afraid this isn't currently supported by the IMA SDK. See also this [forum post](https://groups.google.com/d/msg/ima-sdk/thFbzMOjbKk/UmGj6PpyCwAJ).
