### ISSUE TITLE
Improve support for low-latency HLS live streams

### ISSUE THREAD

**Issue by amirzandi** [google/ExoPlayer#5011]
We are creating a player to play HLS live streams on both iOS and Android devices. The problem is, when an iOS user opens the player, videos starts with not latency unlike EXOPLAYER on an Android device. 
EXOPlayer is not synced with the stream server, iOS player is synced but there is a 15 seconds delay on Android EXOPlayer which means when the performer raise a hand, it displays timely on iOS AVNPlayer but after 

Is there any solution?

**Comment by AquilesCanta** [comment]
#4904 tracks latency improvement for DASH live streams. I guess we can use this issue to track the same in HLS. This is not an aspect we have worked explicitly on. Something that is worth checking is the position in the live window. Stream characteristics also affect how close to the live edge the player gets. What happens if you seek to the very live edge, for instance?

**Comment by heff** [comment]
## Support LHLS (Low-latency HLS)

There's [a spec in process for "LHLS"](https://github.com/video-dev/hlsjs-rfcs/pull/1) which follows the Periscope and Twitch pattern for advertising segments before they're fully transcoded.

* [Demuxed Talk from HLS.js maintainer John Bartos](https://www.twitch.tv/videos/326087400)
* [Periscope's intro at the SF Video meetup](https://www.youtube.com/watch?v=RbH_2l77Pm8)

It'd be great if someone familiar with ExoPlayer's HLS implementation could review the details for any issues and consider supporting it.

**Comment by ojw28** [comment]
Some interesting views on what Apple came up with:
https://mux.com/blog/the-community-gave-us-low-latency-live-streaming-then-apple-took-it-away/

**Comment by kevleyski** [comment]
Thanks for working on this, will mention your efforts at the preso tomorrow. If I find some time and convince the right people I’ll try and help out
https://tinyurl.com/yyr2rz8m

**Comment by tonihei** [comment]
We published our [design doc](https://docs.google.com/document/d/1z9qwuP7ff9sf3DZboXnhEF9hzW3Ng5rfJVqlGn8N38k) on our webpage - open for comments!

**Comment by johndeu** [comment]
@tonihei  any updates on if you will take LL HLS (Pantos official spec) in the coming 6-12 months?

**Comment by tonihei** [comment]
We don't usually provide fixed time estimates and it's best to just subscribe to this issue to see updates. But "in the coming 6-12 months" is vague enough to say yes :)

**Comment by andrealvaradodearaujo** [comment]
any update?

**Comment by tonihei** [comment]
Closing this feature request as it's fully implemented and will be released in 2.13.0.

**Comment by RamilGabdrakhmanov** [comment]
Could you add samples in demo app?

**Comment by natario1** [comment]
Does this include support for both community and Apple LL HLS? It's not very clear from the design doc - it mentions both but then says that Apple implementation is going to take more work. Thanks!

**Comment by tonihei** [comment]
@natario1  Just Apple's version of LL HLS. If you specifically need support for the community variant, you might want to open a new issue to ensure it's tracked as a feature request. Happy to receive PRs for this as well :)
