### ISSUE TITLE
setRemoteMediaClient() in CastPlayer class never gets call in some scenario

### ISSUE THREAD

**Issue by opaquewarellc** [google/ExoPlayer#5012]
### Issue description
The RemoteMediaClient Listeners never get initialize, if the Cast Session is started (user pressed & started the cast button) before the CastPlayer was instantiated.

### Reproduction steps
I have a media list view in a main activity and start the ExoPlayer in another activity. So user can optionally start the cast session before selecting which media to play, casting without first playing locally.

### Link to test content
any content

### Version of ExoPlayer being used
Release 2.8.4

### Device(s) and version(s) of Android being used
not device specific.

**Comment by AquilesCanta** [comment]
Hi, apologies for not looking into this before. Can you please provide very clear repro steps for this issue? I don't think I have had issues with Listeners not working in the past, and I don't remember users reporting such issues either. Please don't forget to include a clear explanation of what the expected and observed behaviors are.
