### ISSUE TITLE
How get list of subtitles and switch between them while video is playing in exoPlayer

### ISSUE THREAD

**Issue by ArezooNazer** [google/ExoPlayer#5016]
I'm using exoplayer for playing different stream types (hls, dash, smoothStream) and I want to switch between the unknown number of subtitles. It means that the number of subtitles depends on server response so how merge a list of subtitles? and how switch between them?

version of exoplayer : 2.9.0
my implementation repo : [https://github.com/ArezooNazer/AndroidVideoPlayer/blob/playerModule/player/src/main/java/com/example/player/util/VideoPlayer.java](url)

**Comment by ojw28** [comment]
Please take a look at our [demo app](https://github.com/google/ExoPlayer/tree/release-v2/demos/main), which has this functionality? The short section of the developer guide about track selection [here](http://google.github.io/ExoPlayer/guide.html#track-selection) should also give you an entry point into working out how to do this.

**Comment by ArezooNazer** [comment]
I did this by the following code 
```
public void setSelectedSubtitle(String subtitle) {
        MergingMediaSource mergedSource;
        if (subtitle != null) {
            this.subtitleUri = Uri.parse(subtitle);

            Format subtitleFormat = Format.createTextSampleFormat(
                    null, // An identifier for the track. May be null.
                    MimeTypes.APPLICATION_SUBRIP, // The mime type. Must be set correctly.
                    Format.NO_VALUE, // Selection flags for the track.
                    "en"); // The subtitle language. May be null.

            DefaultDataSourceFactory dataSourceFactory = new DefaultDataSourceFactory(context,
                    Util.getUserAgent(context, CLASS_NAME), new DefaultBandwidthMeter());


            subtitleSource = new SingleSampleMediaSource
                    .Factory(dataSourceFactory)
                    .createMediaSource(subtitleUri, subtitleFormat, C.TIME_UNSET);


            mergedSource = new MergingMediaSource(mediaSource, subtitleSource);
            player.prepare(mergedSource, false, false);
            resumePlayer();

        } else {
            Toast.makeText(context, "there is no subtitle", Toast.LENGTH_SHORT).show();
        }
    }

```
the subtitle will be selected from the dialog by user.

**Comment by AskMeCode** [comment]
hello Dear @ArezooNazer i make  you example but the subtitle not switch for the second add subtitle all time show just the first subtitle
thanks in advance

**Comment by ArezooNazer** [comment]
@lachguer9  before adding a new subtitle to your video source, first you should remove the old subtitle:
```
           int videoId = player.getCurrentWindowIndex(); 
           //merge new subtitleSource with current videoSource
           mergedSource = new MergingMediaSource(videoSource, subtitleSource); 
           //remove the previous concatenate source
           concatenatingMediaSource.removeMediaSource(videoId);
           //add new one
           concatenatingMediaSource.addMediaSource(videoId, mergedSource);  
```
check [setSelectedSubtitle()](https://github.com/ArezooNazer/AndroidVideoPlayer/blob/playerModule/player/src/main/java/com/example/player/util/VideoPlayer.java) function in my videoPlayer for more detail

**Comment by AskMeCode** [comment]
Thank you dear @ArezooNazer  but i'm not us ConcatenatingMediaSource i us just 
`mediaSource = new MergingMediaSource(sampleSource, textMediaSource);`
how i can remove the old textMediaSource from mediaSource

i use Exoplayer 2.7.0
Best regard
