### ISSUE TITLE
Show live position on progress bar when player paused

### ISSUE THREAD

**Issue by NazikSoft** [google/ExoPlayer#5023]

**Comment by NazikSoft** [comment]
Hi. How can I show live position on progress bar when I paused a player. Thanks

**Comment by ojw28** [comment]
This should already happen for DASH / SS / HLS streams. For progressive live streams (e.g. MP3) this is not supported.

**Comment by NazikSoft** [comment]
I play a video stream (live tv), I guess it's HLS  stream. After pause, user play from last position, but I want show current live position on progressBar. Maybe I can get it from method player.seekToDefaultPosition()?

**Comment by ojw28** [comment]
Calling `seekToDefaultPosition` will seek the player to the live edge. I don't understand what it means to show the "current live position on progressBar". The current live position is by definition the far right of the progress bar.

**Comment by ojw28** [comment]
Closing due to lack of clarification.
