### ISSUE TITLE
Player does not recover from BehindLiveWindowException after preparing again.

### ISSUE THREAD

**Issue by abhishekredspace** [google/ExoPlayer#5027]
### Issue description
I have followed https://github.com/google/ExoPlayer/issues/1074 completely and based on that I opened a ticket with my backend team. 
I can assure you that in my case this is not the server side error. I have worked closely with the server team and I can definitely say video chunk files that are in the manifest are long lived and will only get deleted from the system after 24 hours. 

I decided to make a fix at my client side by catching the BehindLiveWindowException as described in #1074. Preparing the player again and passing new mediaSource. I can assure here as well that I am creating new mediaSource. 
`player.prepare(mediaSourceFactory, false, false);`
I want to start from the current position of live stream after player recovers and user has enough bandwidth to play.

### Reproduction steps
Throttle the bandwidth, so exoplayer throws BehindLiveWindowException.

### Link to test content
I have emailed the test link. 

### Version of ExoPlayer being used
2.4.1

### Device(s) and version(s) of Android being used
Huawei Nexus 6p API 6.0
Huawei Nexus 6p API 7.0

### Player does not recover
Even after preparing the player again after BehindLiveWindowException is thrown. The player does not recover. I am not sure what step I am missing here. This is an ongoing production issue for us. Any help in debugging would be appreciated.

**Comment by tonihei** [comment]
Have you tried calling `player.prepare(mediaSourceFactory, /*resetPosition*/ true, /*resetState*/ false);`?

If you don't reset the position, it will attempt start from the previous position again (which is still behind the live window).

**Comment by abhishekredspace** [comment]
I have tried both the ways i.e.
`player.prepare(mediaSourceFactory.get(), true, false);`
`player.prepare(mediaSourceFactory.get(), true, true);`
but no luck.

**Comment by abhishekredspace** [comment]
Here is some more information:
I did some debug in the exoplayer code and found that in `ExoPlayerImplInternal.java` in the method `doSomeWork()`, `playingPeriodHolder` is `null` and hence I guess it is not recovering.

```
if (playingPeriodHolder == null) {
      // We're still waiting for the first period to be prepared.
      maybeThrowPeriodPrepareError();
      scheduleNextWork(operationStartTimeMs, PREPARING_SOURCE_INTERVAL_MS);
      return;
    }
```

**Comment by tonihei** [comment]
I just tried to test your stream, but it's no longer valid (I'm getting a 400 response code).

Also tested with another live HLS stream and it works well. I reduced the bandwidth, waited until a BehindLiveWindowException and then the player gets reprepared with `player.prepare(mediaSource, true, false);`. Can you try updating to the latest version to see if something if it's fixed? Maybe something was broken back in version 2.4.1

**Comment by abhishekredspace** [comment]
I cannot update to latest at this moment as we are dealing with time-critical deadlines and we do not  have space for regression testing after the update. After I prepare(...), I see the player state is changing to Buffering but never gets to Ready state. So to be clear, below handling is working for you. Can you share the livestream which is working for you? Also if it is not much of a pain, is it possible for you check on 2.4.1 version that it is working for you?
```
@Override public void onPlayerError(ExoPlaybackException e) { 
	final IOException exception = e.getSourceException();
	if (ioException instanceof BehindLiveWindowException) {
               PLog.w(TAG, "BehindLiveWindowException is thrown. Preparing player again");
               player.prepare(mediaSourceFactory.get(), true, false);
               return;
}
```

**Comment by abhishekredspace** [comment]
I am seeing in one case where it is working which is if I put a debug point at the `prepare` call. If I am in debug mode and this exception occurs, player does recover. Now I am thinking is there some thread issue?

**Comment by abhishekredspace** [comment]
I think the problem was at my end. I am able to make it work. Sorry and thanks for the help!!
