### ISSUE TITLE
Can't play certain HLS streams Samsung S3

### ISSUE THREAD

**Issue by kkatani** [google/ExoPlayer#504]
I am using version 1.3.3 and can play most of the HLS streams except the following:

URL: http://manoto1_live-lh.akamaihd.net/i/Manoto1_0@50710/index_756_av-b.m3u8?sd=10&rebase=on
This works fine with VLC and VXG players.
Error Log:
05-28 22:40:50.370     V/MediaPlayer-JNI? release
05-28 22:40:50.545     I/ExoPlayerImpl? Init 1.3.3
05-28 22:40:50.545     D/EventLogger? start [0]
05-28 22:40:50.550     D/EventLogger? state [0.00, false, P]
05-28 22:40:50.550     D/EventLogger? state [0.00, true, P]
05-28 22:40:50.615     E/EventLogger? internalError [0.07, rendererInitError]
05-28 22:40:50.620     E/EventLogger? playerFailed [0.07]
05-28 22:40:50.620     D/EventLogger? state [0.07, true, I]

I am running Android 4.1.1

**Comment by ojw28** [comment]
Please see reply number 7 at:

https://code.google.com/p/android/issues/detail?id=37577

In other words, if that's your own stream then please change the URL to not have an underscore in it. If it's not, you should recommend whoever does own the stream change their URL, or else accept that it might not work on some devices.
