### ISSUE TITLE
Audio out of sync problem

### ISSUE THREAD

**Issue by nuoyan2** [google/ExoPlayer#5041]
Thank you for sharing video is network video MP4 format set infinite loop setLooping(integer.max_value) loop playing for 2 hours is ok but if it is more than 8 hours there is an audio out-of-sync problem  My English is not good enough to use the translation software

**Comment by andrewlewis** [comment]
Are you using ExoPlayer 2.9.0? #4559 may be relevant. Please attach the MP4 if you want us to investigate further.

**Comment by nuoyan2** [comment]
是的 几个小时前找到了这个方法  ＃4559  现在已经不出现音频不同步问题了 感谢

**Comment by nuoyan2** [comment]
Yes, I found this method a few hours ago, # 4559. Now there is no audio out-of-sync problem, thank you
