### ISSUE TITLE
Need support for IGMP protocol

### ISSUE THREAD

**Issue by rakki-cbe** [google/ExoPlayer#5046]

**Comment by rakki-cbe** [comment]
I used android api level 23 
Exo- player version : 2.7.2
Our device supports multi casting

**Comment by ojw28** [comment]
This is not a use case we support currently. Marking as an enhancement, but it will likely be considered low priority.

**Comment by ojw28** [comment]
We do not see any significant demand for this feature, and have no plans to add support.
