### ISSUE TITLE
Wrong current position after seeking multiple times (playback continues after duration)

### ISSUE THREAD

**Issue by mzj** [google/ExoPlayer#5049]
### Issue description
When playing longer mp3 files in demo player, after using seek bar multiple times, playback continues (with normal sound) even after the current time gets bigger than duration. Best reproduced on longer, local files.

Related to buffering because after using DefaultLoadControl with bigger min and max BufferMs time mismatch is reduced from ~10 seconds to max 5 seconds.

Opening again #2608 because @andrewlewis wrote: "If you're seeing the position increase more than a few seconds past the duration this is likely a different issue, so please provide detailed steps to reproduce. Thanks!" And I seeing duration mismatch with more than couple of seconds.

### Reproduction steps
Download the mp3 file from the following url https://serialpodcast.org/season-one/3/leakin-park (Bit Rate 64000 non variable [**Link to mp3 file info**](https://drive.google.com/file/d/1LcBMcccmgrBldFWK4rRfpnDU9BzjIRQQ/view?usp=sharing)), then add it into json playlist file:

```json
{
    "name": "Playlists",
    "samples": [
      {
        "name": "Cats -> Dogs",
        "playlist": [
          {
            "uri": "https://html5demos.com/assets/dizzy.mp4"
          },
          {
            "uri": "https://storage.googleapis.com/exoplayer-test-media-1/mkv/android-screens-lavf-56.36.100-aac-avc-main-1280x720.mkv"
          }
        ]
      },
      {
        "name": "BugList",
        "playlist": [
          {
            "uri": "file:///storage/emulated/0/Podcasts/serial-s01-e03.mp3"
          }
        ]
      }
    ]
}
```

While the file is playing, use the seek bar to jump around backwards and forwards multiple times, after that jump near the end of the file, and observe how the playback continues even after the timestamp gets bigger than duration.

### Link To Test Content
Download mp3 file from here https://serialpodcast.org/season-one/3/leakin-park. Just one of the examples.

### Version of ExoPlayer being used
2.9.0, 2.2.0 and 2.3.1

### Device(s) and version(s) of Android being used
Samsung S7 Edge (Android 8)

**Comment by ojw28** [comment]
I suspect this is the same as #2608, but @andrewlewis can confirm.

**Comment by andrewlewis** [comment]
It looks the same as that issue: the time-to-byte mapping we derive from a Xing header may be inexact. If load control causes the entire stream to be buffered from the start then we will derive an exact timestamp for every sample because we know the timestamp is zero at the start and the exact duration of every frame that gets loaded.
