### ISSUE TITLE
MPEG DASH Playback on Nexus 4 failure

### ISSUE THREAD

**Issue by prasadsvss** [google/ExoPlayer#505]
We are trying to play a MPEG DASH Stream on Nexus 4 and it is failing with DecoderInitializaitonException. Incidentally the Same content stream with Exoplayer works well on few other tablets/phones. (Nexus 7, Micromax, Samsung S4).

But the failure is also observed on Samsung S3, CherryGem W370, Intex Aqua N11. The Nexus 4 is running the Android Lollipop, while the rest are on Kitkat.

Are there specific set of devices/chipsets that are not supported yet by Exoplayer. BTW we are using the latest version 1.3.3

The following is the sample of the exceptions we are seeing

On Nexus 4
----------------

    com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, MediaFormat(video/avc, -1, 400, 224, 1.0, -1, -1, -1, 1920, 1080)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:374)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:735)
            at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:369)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:516)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:496)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:401)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:203)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
     Caused by: android.media.MediaCodec$CodecException: start failed
            at android.media.MediaCodec.native_start(Native Method)
            at android.media.MediaCodec.start(MediaCodec.java:612)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:367)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:735)
            at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:369)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:516)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:496)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:401)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:203)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at 

On Intex N11

D/ACodec  ( 8864): @debug: useBuffer[8], mBufferID(0x41f27178)

D/ACodec  ( 8864): @debug: Buffer[8], 0x56e4e000

D/MtkOmxAudioDecBase(  135): MtkOmxAudioDecodeThread cannot decode when port re-config is in progress

D/ACodec  ( 8864): [OMX.MTK.AUDIO.DECODER.AAC] Now Executing

D/MtkOmxAudioDecBase(  135): GetParameter (0x02000001)

D/MtkOmxAudioDecBase(  135): GetParameter (0x04000002)

E/ExoPlayerImplInternal( 8864): Internal runtime error.

E/ExoPlayerImplInternal( 8864): java.lang.IllegalStateException

E/ExoPlayerImplInternal( 8864): 	at android.media.MediaCodec.dequeueOutputBuffer(Native Method)

E/ExoPlayerImplInternal( 8864): 	at com.google.android.exoplayer.MediaCodecTrackRenderer.drainOutputBuffer(MediaCodecTrackRenderer.java:732)

E/ExoPlayerImplInternal( 8864): 	at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:448)

E/ExoPlayerImplInternal( 8864): 	at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:401)

E/ExoPlayerImplInternal( 8864): 	at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:203)

E/ExoPlayerImplInternal( 8864): 	at android.os.Handler.dispatchMessage(Handler.java:103)

E/ExoPlayerImplInternal( 8864): 	at android.os.Looper.loop(Looper.java:194)

E/ExoPlayerImplInternal( 8864): 	at android.os.HandlerThread.run(HandlerThread.java:60)

E/ExoPlayerImplInternal( 8864): 	at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)

D/MtkOmxVdec(  135): MtkOmxVdec::SendCommand cmd=OMX_CommandStateSet

D/MtkOmxVdec(  135): set MTK_OMX_VDEC_IDLE_PENDING

D/MtkOmxVdec(  135): # Got general command (OMX_CommandStateSet)

**Comment by ojw28** [comment]
Please can you provide a link to the problematic stream?

**Comment by prasadsvss** [comment]
I can share the link to the stream, butnot in a public forum though, any other avenues pls let me know, I can share the link to the google drive with the content.

**Comment by ojw28** [comment]
Please email olly.exoplayer@gmail.com. Thanks.

**Comment by prasadsvss** [comment]
the email with the stream has been sent yesterday. Thx

**Comment by ojw28** [comment]
Please provide access to the link you provided. Thanks.

**Comment by prasadsvss** [comment]
The link has universal access. Can you please check again.

Thx

**Comment by ojw28** [comment]
The sample content you attached works fine for me in the demo application, on a Nexus 4 running LRX21T (Lollypop). Is it possible your application isn't correctly releasing previous player instances? Does this happen after a clean reboot of the device, when played through the demo app?

If so, what's the exact build that you're using?

**Comment by dpkirchner** [comment]
For whatever it is worth I have the same problem on my Nexus 4. I'm pretty sure it's a hardware issue, but I can't rule out software. I've had it since KitKat. YouTube also uses ExoPlayer and throws the same exception.

```
06-22 09:21:49.110    8713-8713/? E/YouTube﹕ (unknown) Error with ExoPlayer video decoder initialization.
    dja: Decoder init failed: OMX.qcom.video.decoder.avc, MediaFormat(video/avc, -1, 480, 360, 1.0, -1, -1, 982728144, 640, 480)
```

Rebooting the phone clears the error, sometimes.

This is a known issue tracked on the Android bug tracker, mistakenly(?) marked ["Released"](https://code.google.com/p/android/issues/detail?id=79316#c362) without a comment. It's a real bummer.

The only thing I can suggest is blacklisting the Nexus 4.

**Comment by Neoklosch** [comment]
I have the same Issue:

```
I/OMXClient(16088): Using client-side OMX mux.
E/OMXMaster(16088): A component of name 'OMX.qcom.audio.decoder.aac' already exists, ignoring this one.
I/OMXClient(16088): Using client-side OMX mux.
E/OMX-VDEC-1080P(  189): Omx_vdec::Comp Init Returning failure, errno 1
E/        (  189): 
E/        (  189):  Destroy C2D instance
E/        (  189): 
E/        (  189):  Destroy C2D instance
E/OMX     (  189): FAILED to allocate omx component 'OMX.qcom.video.decoder.avc'
W/ACodec  (16088): Allocating component 'OMX.qcom.video.decoder.avc' failed, try next one.
E/ACodec  (16088): Unable to instantiate codec 'OMX.qcom.video.decoder.avc'.
E/ACodec  (16088): signalError(omxError 0x80001003, internalError -2147483648)
E/MediaCodec(16088): Codec reported err 0xfffffffe, actionCode 0, while in state 1
W/MediaCodec-JNI(16088): try to release MediaCodec from JMediaCodec::~JMediaCodec()...
W/MediaCodec-JNI(16088): done releasing MediaCodec from JMediaCodec::~JMediaCodec().
E/ExoPlayerImplInternal(16088): Internal track renderer error.
E/ExoPlayerImplInternal(16088): fuh: fvd: Decoder init failed: OMX.qcom.video.decoder.avc, MediaFormat(1, video/avc, -1, -1, 854, 480, 0, 1.0, -1, -1, null, 2093440000, false, 1280, 720, -1, -1, -1)
E/ExoPlayerImplInternal(16088): 	at fuz.a(SourceFile:414)
E/ExoPlayerImplInternal(16088): 	at fuz.o(SourceFile:400)
E/ExoPlayerImplInternal(16088): 	at fuz.a(SourceFile:768)
E/ExoPlayerImplInternal(16088): 	at fvl.a(SourceFile:333)
E/ExoPlayerImplInternal(16088): 	at fuz.a(SourceFile:11524)
E/ExoPlayerImplInternal(16088): 	at oqm.a(SourceFile:134)
E/ExoPlayerImplInternal(16088): 	at fvx.a(SourceFile:129)
E/ExoPlayerImplInternal(16088): 	at fuo.handleMessage(SourceFile:1434)
E/ExoPlayerImplInternal(16088): 	at android.os.Handler.dispatchMessage(Handler.java:98)
E/ExoPlayerImplInternal(16088): 	at android.os.Looper.loop(Looper.java:135)
E/ExoPlayerImplInternal(16088): 	at android.os.HandlerThread.run(HandlerThread.java:61)
E/ExoPlayerImplInternal(16088): 	at ghm.run(SourceFile:40)
E/ExoPlayerImplInternal(16088): Caused by: fvd: Decoder init failed: OMX.qcom.video.decoder.avc, MediaFormat(1, video/avc, -1, -1, 854, 480, 0, 1.0, -1, -1, null, 2093440000, false, 1280, 720, -1, -1, -1)
E/ExoPlayerImplInternal(16088): 	... 11 more
E/ExoPlayerImplInternal(16088): Caused by: java.lang.IllegalArgumentException: Failed to initialize OMX.qcom.video.decoder.avc, error 0xfffffffe
E/ExoPlayerImplInternal(16088): 	at android.media.MediaCodec.native_setup(Native Method)
E/ExoPlayerImplInternal(16088): 	at android.media.MediaCodec.<init>(MediaCodec.java:486)
E/ExoPlayerImplInternal(16088): 	at android.media.MediaCodec.createByCodecName(MediaCodec.java:470)
E/ExoPlayerImplInternal(16088): 	at fuz.o(SourceFile:386)
E/ExoPlayerImplInternal(16088): 	... 10 more
E/YouTube (16088): Error with ExoPlayer video decoder initialization.
E/YouTube (16088): fvd: Decoder init failed: OMX.qcom.video.decoder.avc, MediaFormat(1, video/avc, -1, -1, 854, 480, 0, 1.0, -1, -1, null, 2093440000, false, 1280, 720, -1, -1, -1)
E/YouTube (16088): 	at fuz.o(SourceFile:400)
E/YouTube (16088): 	at fuz.a(SourceFile:768)
E/YouTube (16088): 	at fvl.a(SourceFile:333)
E/YouTube (16088): 	at fuz.a(SourceFile:11524)
E/YouTube (16088): 	at oqm.a(SourceFile:134)
E/YouTube (16088): 	at fvx.a(SourceFile:129)
E/YouTube (16088): 	at fuo.handleMessage(SourceFile:1434)
E/YouTube (16088): 	at android.os.Handler.dispatchMessage(Handler.java:98)
E/YouTube (16088): 	at android.os.Looper.loop(Looper.java:135)
E/YouTube (16088): 	at android.os.HandlerThread.run(HandlerThread.java:61)
E/YouTube (16088): 	at ghm.run(SourceFile:40)
E/YouTube (16088): Caused by: java.lang.IllegalArgumentException: Failed to initialize OMX.qcom.video.decoder.avc, error 0xfffffffe
E/YouTube (16088): 	at android.media.MediaCodec.native_setup(Native Method)
E/YouTube (16088): 	at android.media.MediaCodec.<init>(MediaCodec.java:486)
E/YouTube (16088): 	at android.media.MediaCodec.createByCodecName(MediaCodec.java:470)
E/YouTube (16088): 	at fuz.o(SourceFile:386)
E/YouTube (16088): 	... 10 more
```

My Device:
Nexus 4
Android 5.1.1
Kernel: 3.4.0-perf-gdffc258
Build-Number: LMY48T

A reboot clears the error like as @dpkirchner said. If the ExoPlayer crashes with this error, all apps which are using the lib are no longer working. 

For example an other app logs this:

```
W/MediaCodec-JNI(24599): done releasing MediaCodec from JMediaCodec::~JMediaCodec().
E/OMX-VDEC-1080P(  189): Omx_vdec::Comp Init Returning failure, errno 1
E/        (  189): 
E/        (  189):  Destroy C2D instance
E/        (  189): 
E/        (  189):  Destroy C2D instance
E/OMX     (  189): FAILED to allocate omx component 'OMX.qcom.video.decoder.avc'
W/ACodec  (24599): Allocating component 'OMX.qcom.video.decoder.avc' failed, try next one.
E/ACodec  (24599): Unable to instantiate codec 'OMX.qcom.video.decoder.avc'.
E/ACodec  (24599): signalError(omxError 0x80001003, internalError -2147483648)
E/ExoPlayerImplInternal(24599): Internal track renderer error.
E/ExoPlayerImplInternal(24599): com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, MediaFormat(1, video/avc, -1, 37212, 480, 854, 0, 1.0, -1, -1, null, 6466666, false, -1, -1)
E/ExoPlayerImplInternal(24599): 	at com.google.android.exoplayer.MediaCodecTrackRenderer.notifyAndThrowDecoderInitError(MediaCodecTrackRenderer.java:388)
E/ExoPlayerImplInternal(24599): 	at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:374)
E/ExoPlayerImplInternal(24599): 	at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:729)
E/ExoPlayerImplInternal(24599): 	at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:334)
E/ExoPlayerImplInternal(24599): 	at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:496)
E/ExoPlayerImplInternal(24599): 	at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:479)
E/ExoPlayerImplInternal(24599): 	at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:129)
E/ExoPlayerImplInternal(24599): 	at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431)
E/ExoPlayerImplInternal(24599): 	at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
E/ExoPlayerImplInternal(24599): 	at android.os.Handler.dispatchMessage(Handler.java:98)
E/ExoPlayerImplInternal(24599): 	at android.os.Looper.loop(Looper.java:135)
E/ExoPlayerImplInternal(24599): 	at android.os.HandlerThread.run(HandlerThread.java:61)
E/ExoPlayerImplInternal(24599): 	at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
E/ExoPlayerImplInternal(24599): Caused by: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, MediaFormat(1, video/avc, -1, 37212, 480, 854, 0, 1.0, -1, -1, null, 6466666, false, -1, -1)
E/ExoPlayerImplInternal(24599): 	... 12 more
E/ExoPlayerImplInternal(24599): Caused by: java.lang.IllegalArgumentException: Failed to initialize OMX.qcom.video.decoder.avc, error 0xfffffffe
E/ExoPlayerImplInternal(24599): 	at android.media.MediaCodec.native_setup(Native Method)
E/ExoPlayerImplInternal(24599): 	at android.media.MediaCodec.<init>(MediaCodec.java:486)
E/ExoPlayerImplInternal(24599): 	at android.media.MediaCodec.createByCodecName(MediaCodec.java:470)
E/ExoPlayerImplInternal(24599): 	at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:360)
E/ExoPlayerImplInternal(24599): 	... 11 more
E/MediaCodec(24599): Codec reported err 0xfffffffe, actionCode 0, while in state 1
W/MediaCodec-JNI(24599): try to release MediaCodec from JMediaCodec::~JMediaCodec()...
W/MediaCodec-JNI(24599): done releasing MediaCodec from JMediaCodec::~JMediaCodec().
E/ExoPlayerImplInternal(24599): Internal track renderer error.
```

**Comment by ojw28** [comment]
This is an underlying platform issue and there's not much we can really do to fix it at the ExoPlayer level.
