### ISSUE TITLE
A long cycle of playing 10 video cards in a frame.

### ISSUE THREAD

**Issue by hunanqi** [google/ExoPlayer#5054]
### Issue description
A long cycle of playing 10 video cards in a frame.
The same equipment, some appear, some do not appear, I am not sure whether it does not appear 
because the critical value was not measured. However, there are more than 1 bug devices.

The location of the video is U disk.

### Reproduction steps
1.Prepare 10 video screens.
2.set up REPEAT_MODE_ALL
3.Wait for more than 1 days.
4.The video card is in a frame.

### Version of ExoPlayer being used
2.9.0

### Device(s) and version(s) of Android being used
4.2.1

### A full bug report captured from the device
https://raw.githubusercontent.com/hunanqi/Android6.0FengZhuang/master/log.log

day:11-03 20:43:45.054

**Comment by AquilesCanta** [comment]
Please provide a bugreport as requested in the issue template, I suspect the provided log is just a logcat.

I don't understand what

> The location of the video is U disk

or

> 4. The video card is in a frame.

mean.

Not yet clear which device you are testing on. Have you also tried on other devices?

We will reopen the issue once the issue template is correctly filled and the requested clarifications addressed. Thanks!

**Comment by hunanqi** [comment]
@AquilesCanta 
mean:External hard disk for USB interface  and  frame frozen appears
I provided the logs for the entire device.There is no obvious error report.
I doubt it is related to 4559.
Sorry, no other equipment has been tried. My equipment is of the same type.

**Comment by hunanqi** [comment]
@AquilesCanta 
Time of error occurrence：this logcat  11-03 20:43:45.054

**Comment by AquilesCanta** [comment]
Please provide all elements requested in the [issue template](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE). The bugreport, the tested device and the media to reproduce are missing.

**Comment by AquilesCanta** [comment]
Also, it's still not clear to me what the issue is. Can you clarify what the "expected behavior vs actual behavior" looks like?

**Comment by hunanqi** [comment]
@AquilesCanta  
adb bugreport  is need android 7.0  ，this devices  is 百视通 R1400-m  ，

**Comment by hunanqi** [comment]
@AquilesCanta  The similarity between these 2 questions is that the same steps are taken, and the results are the same when bug comes out.

**Comment by hunanqi** [comment]
@AquilesCanta   this bugreport is need android 7.0  this device is  百视通 r1400-m

**Comment by hunanqi** [comment]
@AquilesCanta  
bugreport
https://raw.githubusercontent.com/hunanqi/Retrofit_Two/master/bug.txt

and  
device：百视通r1400-m

The similarity lies in the same steps, the same phenomenon.

**Comment by hunanqi** [comment]
@AquilesCanta   
[buq.txt](https://github.com/google/ExoPlayer/files/2560951/buq.txt)

this device is 百视通 R1400-m  4.2.1

The similarity lies in the same steps, the same phenomenon.

**Comment by hunanqi** [comment]
@AquilesCanta 

New

[log.log](https://github.com/google/ExoPlayer/files/2561186/log.log)
[buq.txt](https://github.com/google/ExoPlayer/files/2561187/buq.txt)

The following is the log after bug.

11-08 17:55:40.625 1005-2166/com.ttgg.newbox E/LoadTask: OutOfMemory error loading stream
    java.lang.OutOfMemoryError
        at com.google.android.exoplayer2.upstream.DefaultAllocator.allocate(DefaultAllocator.java:102)
        at com.google.android.exoplayer2.source.SampleQueue.preAppend(SampleQueue.java:626)
        at com.google.android.exoplayer2.source.SampleQueue.sampleData(SampleQueue.java:546)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readSample(Mp4Extractor.java:531)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:185)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:898)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:379)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
        at java.lang.Thread.run(Thread.java:856)
11-08 17:55:40.970 1005-2166/com.ttgg.newbox E/dalvikvm-heap: Out of memory on a 65552-byte allocation.

**Comment by AquilesCanta** [comment]
I cannot find the OutOfMemory stacktrace snippet in the provided log files.

A few thoughts:
- It's still not clear to me what the issue is. I assume, considering the stacktrace, that your app is crashing.
- Having 10 videos buffering at the same time might be cause enough for an out of memory exception. However, you mentioned that it takes more than a day to reproduce, so I am more inclined to think it's a memory leak. Have you tried playing fewer videos? Does the issue still reproduce, eventually?
- We haven't had any memory leak reports, and we don't have the bandwidth to debug specific usecases. There are too many variables involved. For us to look into this in more detail, we will need you to provide some evidence this is actually an ExoPlayer issue, and not a bug in the app. You should be able to do this by memory-dumping after a long time, before it crashes. You should be able so see something suspicious at that point (assuming the cause is a memory leak). It might also be worth comparing with a memory dump at the start of playback from the same run. By doing an early memory dump you can easily compare the two of them, and find any object that might be being leaked.

Hope this helps. If you find anything concrete pointing at ExoPlayer being the source of your issue, please reach back. Try to explain your issue in the most detailed way possible.

**Comment by hunanqi** [comment]
@AquilesCanta 
1.I cannot find the OutOfMemory stacktrace snippet in the provided log files. 
It's because I stopped copying logs when I found bugs, and the logs came a few minutes after the bugs appeared.
2.my app is Normal, in addition to other normal video playback, including the main thread.
3.When I reduced the number of video to 4, there were still problems.
4.https://raw.githubusercontent.com/hunanqi/Android6.0FengZhuang/master/log.log

my app  log,
11-02 18:01:42.852 I/内存  (23098): 384  (Log.i("内存", Runtime.getRuntime().maxMemory()/1024/1024 + "");)

11-02 18:01:42.852 I/内存  (23098): 41(Log.i("内存", Runtime.getRuntime().totalMemory()/1024/1024 +"");)

For a long time, my app has plenty of memory and a great difference from the maximum memory. So I doubt it is the exoplayer problem. Strangely enough, my test version of APP did not find bug, or found that bug was much more difficult than the official version. The 2 version is different. One is HTTPS and the other is http. This should not be related to playback. There really is no way out.

**Comment by AquilesCanta** [comment]
I think I would start by discarding a memory leak. I'll paste again my comment above:

> You should be able to do this by memory-dumping after a long time, before it crashes. You should be able so see something suspicious at that point (assuming the cause is a memory leak). It might also be worth comparing with a memory dump at the start of playback from the same run. By doing an early memory dump you can easily compare the two of them, and find any object that might be being leaked.
