### ISSUE TITLE
HlsPlaylistTracker triggers a playlist load when getPlaylistSnapshot is called

### ISSUE THREAD

**Issue by AquilesCanta** [google/ExoPlayer#5059]

**Comment by ojw28** [comment]
Fixed in `dev-v2`.

**Comment by LoyalAbbas** [comment]
Hi Oliver,
I am trying to play m3u8 videos in exoplayer but it also fetching same resolution file in each case.
this is my m3u8 file 
#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=452000,RESOLUTION=400x224,CODECS="avc1.42001e,mp4a.40.2"
output/hls/HLS400rendition-1547544971562.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1068000,RESOLUTION=640x360,CODECS="avc1.4d001f,mp4a.40.2"
output/hls/HLS1000rendition-1547544971562.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2117000,RESOLUTION=1024x576,CODECS="avc1.4d001f,mp4a.40.2"
output/hls/HLS1500rendition-1547544971562.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2110000,RESOLUTION=1280x720,CODECS="avc1.4d001f,mp4a.40.2"
output/hls/HLS2000rendition-1547544971562.m3u8

it rendering HLS400rendition always. I wants to change file according to net speed. please help me how can i fix this issue in android. I am using 2.9.3 version of exoplayer.

**Comment by ojw28** [comment]
I don't understand what this means. In any case, it's off topic. Please file a new issue and properly fill out the issue template.

**Comment by LoyalAbbas** [comment]
Oliver i wants to play .m3u8 video url using exoplayer in my android app. When ever i pass .m3u8 url in HlsMediaSource but this url play always same resolution file from url. i wants to change video resolution with internet speed. Please let me know how to handle this problem in my app
