### ISSUE TITLE
How create semicircle on double-tap gesture?

### ISSUE THREAD

**Issue by Kadanza** [google/ExoPlayer#5062]
I have application with exoplayer on Android. I have create youtube's double-tap gesture to jump 10 seconds forward or backward with animation! How create this semicircle on double tab with ripple effect?

![il0retw](https://user-images.githubusercontent.com/35968229/48070243-75cf9200-e1e8-11e8-9866-10ccdb49e36a.png)

https://zippy.gfycat.com/MessyTemptingDove.webm

Do you have example code with this effect somewhere?

**Comment by AquilesCanta** [comment]
We don't have any code samples for that, sorry. This is also out of the scope of this issue tracker.
