### ISSUE TITLE
Media Service stops randomly

### ISSUE THREAD

**Issue by DKillWorld** [google/ExoPlayer#5064]
### Issue description
I have an music playback app migrated to Exoplayer from Mediaplayer. Everything works fine, but the service stops abruptly and randomly. When returned to the activity, all exoplayer controls seems to be frozen and not working at all.

### Reproduction steps
Its random.

### Link to test content
I have screenshot of the bug report. I will email if you say so 

### Version of ExoPlayer being used
2.8.2

### Device(s) and version(s) of Android being used
It happenes on all devices running on android 8.0+ but randomly. Not all devices are having such issue.

### A full bug report captured from the device
Dont have it yet. Will email if required.

**Comment by DKillWorld** [comment]
https://ibb.co/mM1WHq

This is a bug report from a device.

**Comment by AquilesCanta** [comment]
Hi @DKillWorld. Log images are rarely useful. Please provide a bug report as requested in the issue template: 

>Capture a full bug report using "adb bugreport". Output from "adb logcat" or a
log snippet is NOT sufficient. Please attach the captured bug report as a file.
If you don't wish to post it publicly, please submit the issue, then email the
bug report to dev.exoplayer@gmail.com using a subject in the format
"Issue #1234".

**Make sure the stacktraces are not obfuscated.**

Also, it is worth reading about [services on oreo](https://developer.android.com/about/versions/oreo/background).

We will re-open the issue once the missing information is provided.

**Comment by DKillWorld** [comment]
Thanks. I logged it myself and figured it out that new Android O background execution limits killed service after few minutes randomly.
Searching from hours but didnt got a solution yet.
