### ISSUE TITLE
TimelineQueueNavigator.getSupportedQueueNavigatorActions() ignores shuffle

### ISSUE THREAD

**Issue by kkuepper** [google/ExoPlayer#5065]
Currently getSupportedQueueNavigatorActions() does not take into account if shuffle is enabled or not. That leads to that ActionSkipToNext or ActionSkipToPrevious is disabled in wrong situations.

### Reproduction steps
- play a list of tracks
- enable shuffle
- skip to next track until you hit the latest item the list
-> ActionSkipToNext is disabled even though not all songs have been shuffled through

**Comment by ojw28** [comment]
This will be fixed in `2.9.1`.
