### ISSUE TITLE
When the playback transition from the mid ad to the content , the player drops frames continuously for a  little while.

### ISSUE THREAD

**Issue by Romantic-LiXuefeng** [google/ExoPlayer#5068]
This is reproducible as below configured in the media.exolist.json.
####
{
   "name": "VMAP pre-, mid- and post-rolls, single ads",
   "uri": "http://n2.vod01.icntvcdn.com/newtv2/2016/11/01/hanzhan2/hanzhan2.m3u8",
   ""ad_tag_uri": "https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpost&cmsid=496&vid=short_onecue&correlator=""
}
#####

The EventLogger looks like this:
11-07 D/EventLogger: droppedFrames [39.10, 15.57, window=0, period=0, 50]
11-07 D/EventLogger: droppedFrames [39.66, 16.14, window=0, period=0, 50]
11-07 D/EventLogger: droppedFrames [43.25, 19.65, window=0, period=0, 47]

But if the content begins to play, and then I seek to a position which after the mid_ad insert position.
in this case, when transition from the mid_ad to the seek position, the player doesn't drop frames.

**Comment by AquilesCanta** [comment]
@andrewlewis mind having a look at this?

**Comment by andrewlewis** [comment]
The midroll ad is at 15 seconds, so when transitioning from the midroll ad back to the content we effectively have to do a frame-exact seek to 15 seconds in the content. There is no keyframe at 15 seconds, so doing this seek involves decoding frames from the previous keyframe up to the requested position (about 5 seconds' worth of frames that are never shown). By the time those frames have been decoded the player position has moved forward, which means that some frames get dropped while the decoder catches up.

It should be possible to avoid this problem by making sure midroll ad positions and keyframes line up (either ensuring there are keyframes in the content at the positions where you want to have ads, or by making ad break times match keyframe positions in the existing content).

**Comment by Romantic-LiXuefeng** [comment]
Why not the content frames before 15 seconds just decode, but not renderer.  Just like the seek operate in the HLS. @andrewlewis

**Comment by tonihei** [comment]
When doing seeks, we enter the buffering state (and stop the clock), that's why it doesn't happen there. Whereas for midrolls, we ideally like to continue playback smoothly and therefore continue running the clock (at the expense of risking dropped frames). Or to put it in another way: We only enter the buffering state and stop the clock if we don't have any buffer left. But if we have enough buffered data which just can't keep up with the playback speed, we drop buffers instead.

**Comment by Romantic-LiXuefeng** [comment]
@tonihei @andrewlewis  Thanks for your replies.
I find that, after transitioning from the midroll ad back to the content ,then if doing seeks in the content, there also exist  drop frames.
This is reproducible using my supplied url. 
#### 
D/EventLogger: seekStarted [45.01, 21.56, window=0, period=0]
D/EventLogger: positionDiscontinuity [45.01, 675.75, window=0, period=0, SEEK]
D/EventLogger: droppedFrames [45.03, 675.75, window=0, period=0, 6]
D/EventLogger: loading [45.03, 675.75, window=0, period=0, true]
D/EventLogger: state [45.03, 675.75, window=0, period=0, true, BUFFERING]
D/EventLogger: seekProcessed [45.05, 675.75, window=0, period=0]
D/EventLogger: renderedFirstFrame [45.22, 675.75, window=0, period=0, Surface(name=null)/@0x3ce56853]
D/EventLogger: state [46.51, 675.77, window=0, period=0, true, READY]
D/EventLogger: droppedFrames [47.18, 676.38, window=0, period=0, 50]
D/EventLogger: droppedFrames [47.92, 677.12, window=0, period=0, 50]
D/EventLogger: droppedFrames [48.46, 677.66, window=0, period=0, 50]
D/EventLogger: droppedFrames [48.81, 678.01, window=0, period=0, 50]
