### ISSUE TITLE
Question : I would like to find the way how to add parameters to chunk files(like .ts)

### ISSUE THREAD

**Issue by kimsh3933** [google/ExoPlayer#5069]
Hello
I have to add parameter to chunk files(.ts and inner m3u8 files) because of server's condition.
However I cannot find the way how to add paramter to chunk files.
Could you please let me know the way?
Thanks.

main m3u8 file
http://~/file.m3u8?key=1234

in file.m3u8
- file1.m3u8  <- inner m3u8 file
  - chunk1.ts <- chunk file
- file2.m3u8 <- inner m3u8 file
  - chunk2.ts <- chunk file

**Comment by AquilesCanta** [comment]
You could inject a custom DataSource (using [HlsDataSourceFactory](https://google.github.io/ExoPlayer/doc/reference/index.html?com/google/android/exoplayer2/source/hls/HlsDataSourceFactory.html)) which intercepts the URL for DATA_TYPE_MEDIA and adds the parameters you need. Let me know if that works for you.

**Comment by kimsh3933** [comment]
Thanks for your advice. I modified DataSource.open method. I changed DataSpec's uri.
