### ISSUE TITLE
PlayReady SmoothStreaming

### ISSUE THREAD

**Issue by ilike69** [google/ExoPlayer#507]
Dear authors,
Current version can not play Playready SmoothStreaming DRM-ed contents.
PlayReady test server: http://playready.directtaps.net/smoothstreaming/
Tested on HTC M9, Galaxy S4, Galaxy S5, Nexus 4,  Nexus 5, LG G2, LG 2 pro  and others having isCryptoSchemeSupported() returns true.
BTW, have you play successfully PlayReady SmoothStreaming DRM content in the included sample link ? If had, could you please provide me the device names you used to test the function ? 
Regards,

**Comment by ojw28** [comment]
MediaDrm.isCryptoSchemeSupported(StreamingDrmSessionManager.PLAYREADY_UUID) definitely returns false on my Nexus 5 (and I would guess the same is true for the other devices you've been looking at). Are you sure you're passing the correct UUID for PlayReady?

In any case, as far as I'm aware AndroidTV devices, like Nexus Player and the new Sony TVs, are the only devices that currently provide PlayReady support.

**Comment by ilike69** [comment]
Yeah, I reused exactly the StreamingDrmSessionManager.PLAYREADY_UUID. MediaDrm.isCryptoSchemeSupported returns false on all nexus devices. On my Samsung S6 and S6 Edge, it returns true.

**Comment by ojw28** [comment]
I'll try and find out whether Samsung intended to provide PlayReady support on the S6. For now, I think you should work on the assumption that they didn't intend to do so.
