### ISSUE TITLE
turn on /off subtitle in exoplay leanback 

### ISSUE THREAD

**Issue by andymishisha05** [google/ExoPlayer#5071]
I am developing an Android app for TV using the Leanback library. I have an video with an srt subtitle from a URI. I am using ExoPlayer version 2.6.1 as used in this example app. I created my MediaSource using:

private MediaSource onCreateMediaSource(Uri uri, Uri subtitleUri) {
    String userAgent = Util.getUserAgent(mContext, "ExoPlayerAdapter");
    MediaSource videoSource = new HlsMediaSource(uri,
            new DefaultDataSourceFactory(mContext, userAgent),
            null,
            null);
    Format subtitleFormat = Format.createTextSampleFormat(
            "1", MimeTypes.APPLICATION_SUBRIP, 0, "en");
    MediaSource subtitleSource = new SingleSampleMediaSource(
            subtitleUri,
            new DefaultDataSourceFactory(mContext, userAgent),
            subtitleFormat, C.TIME_UNSET);

    MergingMediaSource mergedSource =
            new MergingMediaSource(videoSource, subtitleSource);
    return mergedSource;
}
In my PlaybackTransportControlGlue, I have a PlaybackControlsRow.ClosedCaptioningAction. When this button is clicked, what do I write in the action dispatcher to toggle the closed captions?

I tried this:

@Override
public void onActionClicked(Action action) {
   if (action==mClosedCaptioningAction){
            ExoPlayerAdapter playerAdapter = new ExoPlayerAdapter(activity,2);

            DefaultTrackSelector trackSelector = playerAdapter.getTrackSelector();
            int rendererIndex = 0;
            if (mClosedCaptioningAction.getIndex() == PlaybackControlsRow.ClosedCaptioningAction.INDEX_ON) {
                MappingTrackSelector.MappedTrackInfo mappedTrackInfo = trackSelector.getCurrentMappedTrackInfo();
                TrackGroupArray textGroups = mappedTrackInfo.getTrackGroups(rendererIndex);
                int groupIndex = 0;
                int trackIndex = 2;
                int[] tracks = getTracksAdding(new MappingTrackSelector.SelectionOverride(
                                new FixedTrackSelection.Factory(), groupIndex, trackIndex),
                        trackIndex
                );
                TrackSelection.Factory factory = tracks.length == 1
                        ? new FixedTrackSelection.Factory()
                        : new AdaptiveTrackSelection.Factory(new DefaultBandwidthMeter());

                trackSelector.setRendererDisabled(rendererIndex, false);
                MappingTrackSelector.SelectionOverride override =
                        new MappingTrackSelector.SelectionOverride(factory, groupIndex, 0);
                trackSelector.setSelectionOverride(rendererIndex, textGroups, override);
            } else {
                trackSelector.setRendererDisabled(rendererIndex, true);
                trackSelector.clearSelectionOverrides();
            }                
I got this crash in app

A bugreport. : 
W: java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.android.exoplayer2.trackselection.MappingTrackSelector$MappedTrackInfo com.google.android.exoplayer2.trackselection.DefaultTrackSelector.getCurrentMappedTrackInfo()' on a null object reference
W:     at com.ebn.hazem.movie.media.ExoPlayerAdapter.prepareMediaForPlaying(ExoPlayerAdapter.java:338)
W:     at com.ebn.hazem.movie.media.ExoPlayerAdapter.setDataSource(ExoPlayerAdapter.java:283)
W:     at com.ebn.hazem.movie.ui.tvui.fragment.VideoExoPlayerFragment.onCreate(VideoExoPlayerFragment.java:101)
W:     at android.app.Fragment.performCreate(Fragment.java:2593)
W:     at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1234)
W:     at android.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2415)
W:     at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2194)
W:     at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2148)
W:     at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2049)
W:     at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3044)
W:     at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2991)
W:     at android.app.FragmentController.dispatchActivityCreated(FragmentController.java:178)
W:     at android.app.Activity.performCreateCommon(Activity.java:6969)
W:     at android.app.Activity.performCreate(Activity.java:6977)
W:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
W:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
W:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
W:     at android.app.ActivityThread.-wrap11(Unknown Source:0)
W:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
W:     at android.os.Handler.dispatchMessage(Handler.java:105)
W:     at android.os.Looper.loop(Looper.java:164)
W:     at android.app.ActivityThread.main(ActivityThread.java:6541)
W:     at java.lang.reflect.Method.invoke(Native Method)
W:     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
W:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

Media samples to reproduce the issue.
 https://api.yamsonline.com/playmovie?id=16703&username=essam&password=essam1&name=ImaikkaaNodigal4K.mp4
 https://api.yamsonline.com/playmovie?id=16703&username=essam&password=essam1&name=ImaikkaaNodigal4K.srt

**Comment by AquilesCanta** [comment]
Note that the [documentation](https://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/trackselection/MappingTrackSelector.html#getCurrentMappedTrackInfo--) clarifies that a null value may be returned:

>Returns the mapping information for the currently active track selection, or null if no selection is currently active.

Make sure you are calling `getCurrentMappedTrackInfo` when a track selection is active. From the stack trace, I assume you are calling `getCurrentMappedTrackInfo` right after preparing. You should wait until [onTracksChanged](https://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/Player.EventListener.html#onTracksChanged-com.google.android.exoplayer2.source.TrackGroupArray-com.google.android.exoplayer2.trackselection.TrackSelectionArray-) is called by the player.

Let me know if this does not answer your question.

**Comment by andymishisha05** [comment]
can u give me example

**Comment by AquilesCanta** [comment]
Have a look at what the [EventLogger](https://github.com/google/ExoPlayer/blob/fa9d7d5e3eb1a0bf5362d5c80b0c5b33a8b6151b/library/core/src/main/java/com/google/android/exoplayer2/util/EventLogger.java#L175) does in `onTracksChanged`.
