### ISSUE TITLE
Why does sample app dramatically change in every last one of releases?

### ISSUE THREAD

**Issue by nightwolf738** [google/ExoPlayer#5073]
I know this is not an issue but this SDK is the hardest one to update. I have quitted updating the SDK since 1.5.9 because I always have guide with the sample app but it changes dramatically in each release. 

It takes my whole day to update my code to avoid errors. Today I decided to update it once again to play Rtmp streams, but almost nothing resolved about exoplayer in my project. 😢 

I wish I am following the wrong way, I looked at developer guide but I think if sample app changes that much I also need to update my code a lot.

Any ideas, any guide which might make my work easier than ever will be very appreciated.

Kind regards.

**Comment by ojw28** [comment]
ExoPlayer 2 was a pretty big architectural change. I think it's more reasonable to consider it as a new API that was designed to replace the old one. This is reflected by the fact that the package name changed.

For ExoPlayer 2, we're trying to get better about breaking the API less frequently, particularly the parts of it that are used by the majority of use cases. We do still break things from time to time in the name of progress. In particular, if the API has a design issue that prevents us from fixing or implementing something, and the choice is just to "not do that" or break the API to unlock forward progress, we will most likely opt for the latter.
