### ISSUE TITLE
contributing two personal extensions

### ISSUE THREAD

**Issue by michalliu** [google/ExoPlayer#5079]
Sry, This is not an issue. cz i cant find a better place to publish.

1. exoplayer2-mediaplayer-extension
https://github.com/michalliu/exoplayer2-mediaplayer-extension
This extension provide consistent api with android stock mediaplayer backed by ExoPlayer in order to migrate existing code much easier, faster and safer. Since it's backed by exoplayer. It aslo supports adjusting playbackspeed, concating play media files, etc. You might take a look at the main source file [here](https://github.com/michalliu/exoplayer2-mediaplayer-extension/blob/exo2.7.1/extension-mediaplayer/src/main/java/com/google/android/exoplayer2/ext/mediaplayer/ExoMediaPlayer.java)  

2. exoplayer2-hevc-extension
https://github.com/michalliu/exoplayer2-hevc-extension
This extension provide soft decode hevc videos using [OpenHEVC](https://github.com/OpenHEVC/openHEVC), the backbone is borrowed from VP9 extension.

Hope it is helpful to someone. 
Sorry for the spam, just want to share.

**Comment by AquilesCanta** [comment]
Thanks a lot for this contibution! I'm sure someone will find this useful. We will keep this in mind in case someone asks for something similar.

**Comment by michalliu** [comment]
Thanks,the hevc soft decoding extension is working pretty good currently.We still have a few issues to resolve though still WIP.I'll publish my progress in this thread.
The mediaplayer extension is mature, we already use it at our production environment with billions of users.

**Comment by michalliu** [comment]
UPDATE: Great news, we have resolved most major problems of hevc soft decoding extension. The hevc extension works pretty good now. The issue status has been updated as following:

1. ~~playable but not smooth~~ (STATUS: DONE. due to  pts not correct set)
1. ~~video renderring is not correct sometimes when seeking is performed)~~ (STATUS: DONE. due to needs flush decoder when seek performed)
1. potential frame drop at play ends (STATUS: WIP)
1. seek in video is very slow (STATUS: WIP)
1. more yuv format support, only YUV420 is handled currently

**Comment by Romantic-LiXuefeng** [comment]
I used  ndk version is r15c . 
```
NDK_PATH="/Users/../Library/Android/sdk/android-ndk-r15c"
cd "${HEVC_EXT_PATH}"/jni
${NDK_PATH}/ndk-build APP_ABI=all -j4   
```
```
47 warnings and 18 errors generated.
make: *** [/Users/lixuefeng/Downloads/ExoPlayer-release-v2.9.0/extensions/hevc/src/main/obj/local/arm64-v8a/objs/openhevc/libavcodec/hevc_cabac.o] Error 1
make: *** Waiting for unfinished jobs....
22 warnings generated.
49 warnings generated.
50 warnings generated.
```
@michalliu  Hope you tell me what's your ndk version. Thanks!

**Comment by michalliu** [comment]
I'm using r13b, I don't think this error is related to ndk version, what's the error message exactly?

**Comment by Romantic-LiXuefeng** [comment]
Thanks, It's true the error is not related to ndk version. 
`${NDK_PATH}/ndk-build APP_ABI=armeabi-v7a -j4
`
I set the APP_ABI=armeabi-v7a, it compiles successfully.  Set the APP_ABI = arm64-v8a  or x86 or mips. The error always is instruction invalid.

**Comment by Romantic-LiXuefeng** [comment]
@michalliu  My Xiaomi box's cpu info:
```
shell@kungfupanda:/ $ cat /proc/cpuinfo                                        
Processor       : AArch64 Processor rev 2 (aarch64)
processor       : 0
BogoMIPS        : 26.00

processor       : 1
BogoMIPS        : 26.00

processor       : 2
BogoMIPS        : 26.00

processor       : 3
BogoMIPS        : 26.00

processor       : 4
BogoMIPS        : 26.00

processor       : 5
BogoMIPS        : 26.00

Features        : fp asimd aes pmull sha1 sha2 crc32 
CPU implementer : 0x41
CPU architecture: AArch64
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 2
```

I only compile the  APP_ABI=armeabi-v7a, When loadLibrary("hevcdec") ,  it occurs link error.
Is there any way to compile the APP_ABI = arm64-v8a?

**Comment by michalliu** [comment]
> @michalliu My Xiaomi box's cpu info:
> 
> ```
> shell@kungfupanda:/ $ cat /proc/cpuinfo                                        
> Processor       : AArch64 Processor rev 2 (aarch64)
> processor       : 0
> BogoMIPS        : 26.00
> 
> processor       : 1
> BogoMIPS        : 26.00
> 
> processor       : 2
> BogoMIPS        : 26.00
> 
> processor       : 3
> BogoMIPS        : 26.00
> 
> processor       : 4
> BogoMIPS        : 26.00
> 
> processor       : 5
> BogoMIPS        : 26.00
> 
> Features        : fp asimd aes pmull sha1 sha2 crc32 
> CPU implementer : 0x41
> CPU architecture: AArch64
> CPU variant     : 0x0
> CPU part        : 0xd03
> CPU revision    : 2
> ```
> I only compile the APP_ABI=armeabi-v7a, When loadLibrary("hevcdec") , it occurs link error.
> Is there any way to compile the APP_ABI = arm64-v8a?

What's the error message?
