### ISSUE TITLE
ExoPlayer not playing H264 on certain devices

### ISSUE THREAD

**Issue by Ltty** [google/ExoPlayer#508]
Hi,
it seems that the ExoPlayer is unable to play H264 streams on some devices such as the ZTE Blade L2, the Lenovo A7600-H or Aquaris E5 HD. It seems that these devices have issues with the video/avc codec.

We added a check to verify if a codec for video/avc is present on these devices and it seems that there isn't. So I was wondering if there is anything we can do to support these devices. Does ExoPlayer support software codecs? I could imagine that if there is not any codec for video/avc available, providing a proper SW codec could solve this issue. For example, we know that we use FFMPEG or VLC to play these streams, we do not see this issue, but using FFMPEG increases the size of the app tremendously.

Best regards,
Florian

**Comment by ojw28** [comment]
Please could you specify exactly what media you're trying to play (ideally links to the actual media, or samples in the demo app that don't work correctly)?

**Comment by Ltty** [comment]
Actually, we are streaming from an IP camera. It is a H.264 encoded stream with audio AAC. We are streaming over UDP using the RTP protocol. We strip the RTP header extract the 188 byte large segments and write them directly to the EXO player. This works well on most devices but on some it fails. I can provide playback data as a reference if you like.

**Comment by ojw28** [comment]
As in, every sample provided by your SampleSource is 188 bytes long? That's not a valid way to provide samples, and whilst some decoders may be permissive enough to still function, that's not the correct way to provide data and it's expected that a decoder can fail when fed data in this way.

You need to properly segment the data into whole sample. `H264Reader` contains code that does this, so you can likely take a look at that and re-use much of it. I suspect that once you properly segment the data, playback will work correctly on all devices.

**Comment by Ltty** [comment]
Yes I know, and that's what we actually do. So we receive 188 byte long segments from the RTP stream, then we queue them and create a whole sample which is much larger. 

However, the problem is not how we implement the stream because it is working perfectly with our camera. The issue is that on the devices named above, not a single H.264 stream is playing, the screen stays black. We also tried with HLS demo streams from Apple or the NASA stream for example.

**Comment by Ltty** [comment]
Hi @ojw28,
I think that the issue is maybe related to https://github.com/google/ExoPlayer/issues/143. Because the Lenovo devices we mentioned are equipped with MTK chipsets as well. Unfortunately, I have a hard time providing more detailed information as I currently do not have an affected device here.

**Comment by ojw28** [comment]
The issue in #143 was that we weren't setting the initialization data (i.e. sps, pps) in the video format. The corresponding change was: https://github.com/google/ExoPlayer/commit/0a888a0d4f11356f6021e63e5ba473d9c0a5fd77.
So if you're not doing that in your own source, that could be why.

In any case, this sounds like an issue with how you're feeding data to the player rather than an issue with ExoPlayer itself, so closing for now. Please re-open if you disagree, or if you can reproduce with the ExoPlayer demo app in a way that we can reproduce. Thanks!
