### ISSUE TITLE
(Gradle project sync failed) Failed to resolve: play-services-basement

### ISSUE THREAD

**Issue by ghost** [google/ExoPlayer#5080]
I am trying to complie ecoplayer using android studio. However, the log shows there are unsolved dependencies. The log information is shown as follow:

Failed to resolve: play-services-basement a href="openFile:D:/Android/AndroidProject/ExoPlayer/demos/cast/build.gradle" Open File /a

Failed to resolve: play-services-basement a href="openFile:D:/Android/AndroidProject/ExoPlayer/extensions/cast/build.gradle" Open File /a

Failed to resolve: play-services-basement a href="openFile:D:/Android/AndroidProject/ExoPlayer/extensions/ima/build.gradle" Open File /a

Could you please what should I do?

**Comment by AquilesCanta** [comment]
Duplicate of #5047.
