### ISSUE TITLE
Reverse Playback Support

### ISSUE THREAD

**Issue by keremkusmezer** [google/ExoPlayer#5084]
### Issue description
My application requires full reverse playback on media also i need a boomerang style video display in my application. Which in case requires a reverse playback therefore.

On IOS part i can implement that feature with ease because IOS AVPlayer support negative values on playback using Avplayer.rate parameter and it is a must have on my application.

### Reproduction steps
I have seen several branches implemented by other members of the community , but the implementations are either on 2.0 or 2.1 and cannot be easly back ported to the current version because of the massive api changes.

**Comment by AquilesCanta** [comment]
Please see #2191.
