### ISSUE TITLE
Player states when losing/gaining audio focus

### ISSUE THREAD

**Issue by hieplpwork** [google/ExoPlayer#5087]
### Issue description
I am using built-in ExoPlayer audio focus support. My app UI is based on the Android-UniversalMusicPlayer which uses an animator to play the progress during playback. I want to receive Exoplayer states when the app audio focus is lost/gained in order to update the player progress bar accordingly. But it seems this feature has not been supported, or please let me know how to use this feature properly if it's already available in the package.
Basically, when the player audio focus is lost/gained, I expect to receive the player state, for example AUDIO_FOCUS_STATE_LOST_FOCUS, AUDIO_FOCUS_STATE_LOSS_TRANSIENT, or AUDIO_FOCUS_STATE_HAVE_FOCUS...

### Reproduction steps
- Launch the Exoplayer app and its progress bar is being updated properly. 
- When the device receives a phone call, my app player audio focus is lost, then it pauses but the player state does not change.
- When the phone call ends, the player continues playing again, but Exoplayer does not send out a state on which I can rely to update progress bar UI accordingly.

### Version of ExoPlayer being used
2.9.0

### Device(s) and version(s) of Android being used
Samsung Galaxy Note 8, Android 7.1.1

**Comment by AquilesCanta** [comment]
@nic0lette mind having a look at this? If this is not your area, please assign back to me!

**Comment by tonihei** [comment]
Marking as enhancement because such a callback is currently missing (i.e. the player can silently switch state without letting the app know).

**Comment by hieplpwork** [comment]
Hello,
Thanks for your consideration on this issue. Could I expect this feature
support in the next library version? If yes, do you have  a timeline for
the new version release?

Best Regards,
Hiep

**Comment by ojw28** [comment]
It will be in the next release. We don't have a timeline.

**Comment by ojw28** [comment]
Oh wait, sorry, I thought this was a different issue. Please disregard my statement above.

**Comment by ojw28** [comment]
Duplicating onto https://github.com/google/ExoPlayer/issues/6203, since there's more information in that one.
