### ISSUE TITLE
How show all segments of one video from sdcard in one seekbar with total time of segments

### ISSUE THREAD

**Issue by majidebrahimii** [google/ExoPlayer#5093]
How show all segments of one video from sdcard in one seekbar whit total time of segments. I user ConcatenatingMediaSource but it play segment One after another but i want play all segments in one play. like when play from link hls. At first, I saved all the segments in a one file and showed exo player but could not get the all time, and the seekbar was hidden too.

**Comment by tonihei** [comment]
Please try the [multi-window timebar option](https://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/ui/PlayerControlView.html#setShowMultiWindowTimeBar-boolean-) to enable this. Note however, that it doesn't work well with ExtractorMediaSources (see #4727).

**Comment by ojw28** [comment]
For MPEG-TS you're probably going to be better off concatenating the files, as you were exploring in https://github.com/google/ExoPlayer/issues/5090.

**Comment by majidebrahimii** [comment]
@tonihei @ojw28  i use setShowMultiWindowTimeBar but seek bar and total time not correct. I initially decided to put all the segments in a file and play it(#5090 ), but it showed the total time zero and the seek bar was disabled(but MX Player play file very good). I decided to download the parts without altering and show that in this case, The exoplayer has a problem and the total time and seek bar are wrong. I confused and I probably have to forget to download and play HLS(m3u8) files.

**Comment by ojw28** [comment]
Let's use #5090 to track doing this the right way.
