### ISSUE TITLE
IllegallStateException when playing DASH and HLS

### ISSUE THREAD

**Issue by bexheti** [google/ExoPlayer#5095]
I am experiencing issues when playing H264 streams transported using DASH or HLS using ExoPlayer.
Searched for similar issues, but none of the proposed solutions/workarounds seem to work in my case.

### Issue description
When trying to play DASH or HLS streams I get an IllegalStateException at android MediaCodec.dequeueInputBuffer(Native Method).
I tried to blacklist the problematic decoder codec for that specific mime type (OMX.google.h264.decoder - video/avc), but since that is the only codec that my device supports for the video/avc mime-type, video playback fails.
Note that I have no problems playing the same content with android's native MediaPlayer. The reason why I want to use ExoPlayer is because of the support for closed captions.

### Link to test content
https://bitmovin-a.akamaihd.net/content/MI201109210084_1/mpds/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.mpd
I also tested with a DASH stream from another service that I am subscribed to. Same issue.

### Version of ExoPlayer being used
2.7.3 (tried also newer versions, but still same issue)

### Device(s) and version(s) of Android being used
Android TV Box: Geniatech ATV 400 running on Android 4.1.2 (https://www.geniatech.com/product/atv400/)
I think it is a device specific issue, as the tested videos play fine using a Nexus 5X.

### A full bug report captured from the device
[bug.txt](https://github.com/google/ExoPlayer/files/2573402/bug.txt)

Shorter logcat:
11-12 20:34:39.009 13163-13206/agon.personal.aatv E/OMXNodeInstance: OMX_GetExtensionIndex failed
11-12 20:34:39.019 13163-13207/agon.personal.aatv E/SoftAVC: Decoder failed: -2
11-12 20:34:39.019 13163-13206/agon.personal.aatv E/ACodec: [OMX.google.h264.decoder] ERROR(0x80001001)
11-12 20:34:39.019 13163-13206/agon.personal.aatv E/MediaCodec: Codec reported an error. (omx error 0x80001001, internalError -2147483648)
11-12 20:34:39.029 13163-13196/agon.personal.aatv E/ExoPlayerImplInternal: Internal runtime error.
    java.lang.IllegalStateException
        at android.media.MediaCodec.dequeueInputBuffer(Native Method)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:633)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:570)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:522)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:305)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:137)
        at android.os.HandlerThread.run(HandlerThread.java:60)
11-12 20:34:39.039 13163-13163/agon.personal.aatv D/Listener: exoPlayerError()

Thanks for the great work you are doing to support ExoPlayer.

**Comment by tonihei** [comment]
There is probably nothing we can do about that error. As you already pointed out, it's a device specific issue. We have a couple of workarounds for known device specific issues but none looks likely to apply in this case.
