### ISSUE TITLE
ExoPlayer takes too much time to stop/release while in state other than STATE_READY

### ISSUE THREAD

**Issue by Khushwant-singh** [google/ExoPlayer#51]
Hi,

After calling setPlayWhenReady(true), the ExoPlayer goes through many states. But before it reaches the ready state (STATE_READY), if "stop" gets called on the current ExoPlayer object, it takes too much (5-6 seconds) to release the resources and this could hang the app. (In case play and stop buttons are dependent on ExoPlayer state.)

In the exact same scenario, MediaPlayer does update the states immediately.

Any efficient way to handle this scenario.

Thanks,
Khushwant Singh

**Comment by ojw28** [comment]
FrameworkSampleSource is deprecated (and we wont be fixing it further). Closing.
