### ISSUE TITLE
 The customer provides a ts stream, exoplayer can not play, but vlc can play normally, how to solve

### ISSUE THREAD

**Issue by zhangabvc** [google/ExoPlayer#5101]
I uploaded the test stream to the URL, and you can download the ts stream from this website http://file.yiyuen.com/detail.html?id=884. I found that the order of the stream is to first output the audio data and then the video data, and then loop.
Who can know why?
![test-ts](https://user-images.githubusercontent.com/44994911/48400274-df0f5200-e760-11e8-9c8b-b036f5a07ccd.png)

**Comment by tonihei** [comment]
There seem to be some issues with the m3u8 playlist file:
- As you provided it as a zip file, it's not updating automatically and thus I needed to add a #EXT-X-ENDLIST to be able to play it at all. (May not be an issue if it comes from an actual live stream)
- The playlist includes the same ts files twice. This is allowed, but needs a #EXT-DISCONTINUITY tag between them to work correctly.

@AquilesCanta may be able to add further details.

**Comment by zhangabvc** [comment]
> There seem to be some issues with the m3u8 playlist file:
> 
> * As you provided it as a zip file, it's not updating automatically and thus I needed to add a #EXT-X-ENDLIST to be able to play it at all. (May not be an issue if it comes from an actual live stream)
> * The playlist includes the same ts files twice. This is allowed, but needs a #EXT-DISCONTINUITY tag between them to work correctly.
> 
> @AquilesCanta may be able to add further details.
The original is a live stream, I downloaded a ts stream, what you said is not a problem.
The live stream is http://45.248.164.201:80/AASTHA/index.m3u8
