### ISSUE TITLE
How does downloading HLS m3u8 files work?

### ISSUE THREAD

**Issue by ofuwape** [google/ExoPlayer#5102]
This is a question about documentation.
I did not find this on the blog or in the developer guide. Is there documentation that explains how the m3u8 file is downloaded? Are the ts chunks downloaded in parallel? or sequentially?
Are the ts chunks merged after all downloaded chunks are successful?
Is there a possibility of having the option to select the maximum number of ts chunks that can be downloaded in parallel?

**Comment by tonihei** [comment]
Did you read [this blog post ](https://medium.com/google-exoplayer/downloading-adaptive-streams-37191f9776e )by any chance? It explains how the HLS variants for downloading are selected.

The number of simultaneous downloads can be specified when creating the DownloadManager (default is 1, that is sequential downloads). All the chunks will be downloaded separately and not merged together.

**Comment by ofuwape** [comment]
@tonihei Thanks for the feedback. I see DEFAULT_MAX_SIMULTANEOUS_DOWNLOADS is 1 but that is when one is trying to download several different videos.
A single HLS m3u8 can contain multiple ".ts" chunks, so I am referring to the option to be able to download multiple chunks of 1 HLS file in parallel.

**Comment by ofuwape** [comment]
I am looking at the SegmentDownloader from the HlsDownloader class and it seems to be downloading segments sequentially:
<img width="740" alt="exoplayer_hlsdownloader_segmentdownloader" src="https://user-images.githubusercontent.com/7673320/48486054-6c49b980-e7e8-11e8-9e7c-e4b53d404711.png">

**Comment by tonihei** [comment]
I don't think there is such an option right now. 

@erdemguven Do you reckon we should add one in the future and mark this as an enhancement? Or is there a good reason not to support this?

**Comment by ofuwape** [comment]
@ojw28 any ideas?

**Comment by ofuwape** [comment]
Closing the issue now. Found a similar open issue here: https://github.com/google/ExoPlayer/issues/4273
