### ISSUE TITLE
Downloading hls offline video without using download action

### ISSUE THREAD

**Issue by meenukrishnamurthy** [google/ExoPlayer#5104]
I am using the latest version of exoplayer and i want to implement offline download fucntionality.I have checked your example in the demo app.You have used download action for selecting which stream has to be downloaded(i.e 1080p or 480p etc).Can it be done in any other way as i dont wish to use download action.In the youtube app also the have not used download action i guess because i have not seen any action file in their downloads folder in local storage.Can please provide me a solution for implementing offline download without using download action.

**Comment by tonihei** [comment]
Videos can also be cached while playing the video just by using CacheDataSource. What exactly is the problem with using DownloadAction?

**Comment by meenukrishnamurthy** [comment]
There is no problem actuallu.I just wanted to know the use of downlaod action.What is the purpose of using it.

**Comment by tonihei** [comment]
It's used to define what DownloadManager is supposed to do (e.g. download media, remove media, etc.). Please have a look at the demo app to see how it can be used.

**Comment by tonihei** [comment]
I'll close the issue because the question was answered. Feel free to reopen if that's not the case.
