### ISSUE TITLE
AdsMediaSource isn't documented in the developer guide.

### ISSUE THREAD

**Issue by BetweenTwoBits** [google/ExoPlayer#5105]
The developer guide has a wonderful section on [MediaSources](https://google.github.io/ExoPlayer/guide.html#mediasource), but doesn't mention the AdsMediaSource. Having docs around the benefits and use cases would be immensely useful.

**Comment by tonihei** [comment]
Good point. I'll mark this as an enhancement to add a section about ad playback in general.

**Comment by ajonno** [comment]
I was trying to understand how to use AdsMediaSource today as we are currently building a large podcast app (1M+ users from our existing user base) but no such luck :-(   Can you point me to some info/examples etc ? Many thanks

**Comment by andrewlewis** [comment]
The original [blog post about the IMA extension](https://medium.com/google-exoplayer/playing-ads-with-exoplayer-and-ima-868dfd767ea) still has some useful information and may be a starting point. The ExoPlayer demo app also integrates with the IMA extension so you could take a look at that as well. Resolving this issue by adding proper documentation to the developer guide is still work in progress I'm afraid.

Edit: given your issue #6891 is a different use case from the IMA extension, this answer isn't relevant. Please have a look at #6814 which I think does what you need.

**Comment by ojw28** [comment]
There is a section on ad insertion now, [here](https://exoplayer.dev/ad-insertion.html).

**Comment by BetweenTwoBits** [comment]
Thank you for following up @ojw28!
