### ISSUE TITLE
Should AudioTrackUtilV19.updateTimestamp deal with overflow issue?

### ISSUE THREAD

**Issue by david2658** [google/ExoPlayer#511]
In AudioTrackUtilV19, updateTimestamp() deals with the overflow issue. When a wrapped around of rawFramePosition detected, increase rawTimestampFramePositionWrapCount. 
The [63:32] bits of  lastTimestampFramePosition is rawTimestampFramePositionWrapCount and the [31:0] bits of lastTimestampFramePosition  is rawFramePosition. But the AudioTimestamp.framePosition(rawFramePosition) is a long. I think it do not need to deal the overflow issue.

**Comment by ojw28** [comment]
I'm pretty sure that although it's a long, the actual values returned only advance up to 0xFFFFFFFF and then roll over. Feel free to test this, and re-open if you discover that this is not the case.
