### ISSUE TITLE
Required output protections are not active

### ISSUE THREAD

**Issue by SystemRestored** [google/ExoPlayer#5110]
I am playing a widevine drm dash stream. In android 4.4 its working and in most other devices its not working.  In pie android 9.0 I observed the error code:  

`[OMX.google.h264.decoder] setPortMode on output to DynamicANWBuffer failed w/ err -1010
   Required output protections are not active`

what's the meaning of this and how to solve it?

**Comment by andrewlewis** [comment]
Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

In particular it would be useful to have a full bug report output by `adb bugreport` to see what's going on. It looks weird that a software decoder is in use (`OMX.google.h264.decoder`) yet requires output protections. (I'm not 100% sure but normally I'd expect to see that only when using a decoder with a secure output path.)

**Comment by SystemRestored** [comment]
The problem is the streams require L1 widevine drm and the device was L3.
