### ISSUE TITLE
Playing Partly Encrypted File.

### ISSUE THREAD

**Issue by MickeyBadBad** [google/ExoPlayer#5112]
I find exoplayer can play fully aes encrypted mp4 file. 
I implement the FileDataSource Class to play a partly encrypted mp4 file, the file size is like 100mb, head part is decrypted, head size is 5mb. my code can play the file now, but seeking time to the head part will trap in a dead loop (open read close) loop.
ExoPlayer Version: 2.7.1
Device: Mi 8
I think the problem is in try command in read func. I'm stuck with it, any suggestion?

`public final class OriginDataSource implements DataSource {

    /**
     * Thrown when IOException is encountered during local file read operation.
     */
    public static class OriginDataSourceException extends IOException {

        OriginDataSourceException(IOException cause) {
            super(cause);
        }

    }

    private final TransferListener listener;

    private RandomAccessFile file;
    private Uri uri;
    private long bytesRemaining;
    private boolean opened;
    private byte[] head = new byte[App.size];
    private ByteArrayInputStream bis;

    private static final String HEXES = "0123456789ABCDEF";

    private static String getHex(byte[] raw) {
        final StringBuilder hex = new StringBuilder(2 * raw.length);
        for (final byte b : raw) {
            hex.append(HEXES.charAt((b & 0xF0) >> 4)).append(HEXES.charAt((b & 0x0F)));
        }
        return hex.toString();
    }

    OriginDataSource() {
        this(null);
    }

    /**
     * @param listener An optional listener.
     */
    private OriginDataSource(TransferListener listener) {
        this.listener = listener;
    }

    @Override
    public void addTransferListener(TransferListener transferListener) {

    }

    @Override
    public long open(DataSpec dataSpec) throws OriginDataSourceException {
        try {
            uri = dataSpec.uri;
            file = new RandomAccessFile(dataSpec.uri.getPath(), "rw");
            try {
                file.seek(0);
                file.read(head);
                Cipher cipher = Cipher.getInstance(App.algorithm);
                cipher.init(Cipher.DECRYPT_MODE,
                        new SecretKeySpec(App.keyValue.getBytes(), "AES"),
                        new IvParameterSpec(App.ivValue.getBytes()));
                byte[] s = cipher.update(head);
                byte[] tail = new byte[App.size];
                file.read(tail);
                file.seek(0);
                ByteArrayOutputStream bos = new ByteArrayOutputStream();
                bos.write(s);
                bos.write(tail);
                bis = new ByteArrayInputStream(bos.toByteArray());
                Log.e("Case Hex : ", getHex(s));
                Log.e("Case Opening : ", "True");

            } catch (Exception e) {
                e.printStackTrace();
            }
            file.seek(dataSpec.position);
            bytesRemaining = dataSpec.length == C.LENGTH_UNSET ? file.length() - dataSpec.position
                    : dataSpec.length;
            if (bytesRemaining < 0) {
                throw new EOFException();
            }
        } catch (IOException e) {
            throw new OriginDataSourceException(e);
        }

        opened = true;
        if (listener != null) {
            listener.onTransferStart(this, dataSpec,false);
        }

        return bytesRemaining;
    }

    @Override
    public int read(byte[] buffer, int offset, int readLength) throws IOException {
        if (readLength == 0) {
            return 0;
        } else if (bytesRemaining == 0) {
            return C.RESULT_END_OF_INPUT;
        } else {
            int bytesRead;
            try {
                if (file.getFilePointer() < App.size ) {
                    Log.e("In Enc : ","True");
                    bytesRead = bis.read(buffer, offset, (int) Math.min(bytesRemaining, readLength));
                } else {
                    Log.e("In Enc : ","False");
                    bytesRead = file.read(buffer, offset, (int) Math.min(bytesRemaining, readLength));
                }
            } catch (IOException e) {
                throw new OriginDataSourceException(e);
            }
            if (bytesRead > 0) {
                bytesRemaining -= bytesRead;
                if (listener != null) {
                    listener.onBytesTransferred(this, dataSpe,false,bytesRead);
                }
            }
            return bytesRead;
        }
    }

    @Override
    public Uri getUri() {
        return uri;
    }

    @Override
    public Map<String, List<String>> getResponseHeaders() {
        return null;
    }

    @Override
    public void close() throws OriginDataSourceException {
        uri = null;
        Log.e("Case Closing : ", "True !");
        try {
            bis.close();
            if (file != null) {
                file.close();
            }
        } catch (IOException e) {
            throw new OriginDataSourceException(e);
        } finally {
            file = null;
            if (opened) {
                opened = false;
                if (listener != null) {
                    listener.onTransferEnd(this,dataSpe,false);
                }
            }
        }
    }
}
`

**Comment by tonihei** [comment]
Your code looks roughly right, but please be aware that we can't debug any custom app code in detail. I'd suggest to step through with a debugger to see why your code stopping or doing weird things.

**Comment by tonihei** [comment]
Closing for now. Feel free to reopen if you have find a specific problem we should look into.
