### ISSUE TITLE
OfflineLicenseHelper doesn't support customer drm callback anymore

### ISSUE THREAD

**Issue by AchibanaUkyo** [google/ExoPlayer#5115]
Hi, From the commit c661ed42de666cbd6043dc6d43acd24058b67e8a the mediaDrmCallback has been removed from the OfflineLicenseHelper newWidevineInstance and application can't access the callback created inside the OfflineLicenseHelper, then we can't send customer http header for the license request.
Anyone knows how to pass the specific header when requesting the offline license then?
Thanks

**Comment by marcbaechinger** [comment]
To add custom http headers for the license request you can use 

```
newWidevineInstance(
      String defaultLicenseUrl,
      boolean forceDefaultLicenseUrl,
      Factory httpDataSourceFactory,
      HashMap<String, String> optionalKeyRequestParameters)
```
The last parameter is a map of optional parameters used when doing the key request.

https://github.com/google/ExoPlayer/blob/f7ed789fc3841b2536f5629c6bb10f4cb4ee5130/library/core/src/main/java/com/google/android/exoplayer2/drm/OfflineLicenseHelper.java#L94

**Comment by ojw28** [comment]
I don't think that's quite the same thing, because those parameters go into the key request rather than being sent as HTTP headers.  You can still do what you need by using the `OfflineLicenseHelper` constructor directly, rather than the `newWidevineInstance` static method. For example:

```
new OfflineLicenseHelper(
    C.WIDEVINE_UUID,
    FrameworkMediaDrm.newInstance(C.WIDEVINE_UUID),
    yourCustomMediaDrmCallback,
    optionalKeyRequestParameters);
```

**Comment by AchibanaUkyo** [comment]
Yes, thanks, that's doable:)
BTW, the optionalKeyRequestParameters is really ambiguous... I missunderstood is same with @marcbaechinger . even the playlist uses "drm_key_request_properties" but it's the http headers.
