### ISSUE TITLE
Why does PlayerControlView disappear in screen

### ISSUE THREAD

**Issue by JokerLi** [google/ExoPlayer#5116]
### Issue description
We embed ExoPlayer into our app, and play online videos, sometimes the PlayerControlView may disappear. we look for the reason by hierarchy viewer, and find out that the measuredWidth and measuredHeight of PlayerControlView are 0, but the visibility is VISIBLE. We tried to change many different version, but this problem always exist.

### Version of ExoPlayer being used
r2.5.0, r2.5.4, 2.6.0, 2.7.3.

### Device(s) and version(s) of Android being used
Xiaomi Redmi Note 4X, Android N

**Comment by marcbaechinger** [comment]
The PlayerControlView consists of nested LinearLayouts which all have a layout_height attribute of wrap_content. So it will have the height of the contents contained in the layouts.

When it disappears with a measuredHeight of 0, what's contained in the PlayerControlView when you look into the hierarchy viewer? Did you apply any customization of the content of the PlayerControlView?

**Comment by JokerLi** [comment]
There are TextViews, ImageButtons and ImageViews in this PlayerControlView. And we didn't apply any  customization of content.

**Comment by JokerLi** [comment]
Nobody can solve this problem, so... i gived up. Thanks!

**Comment by cnting** [comment]
@JokerLi try set `playerControlView.showTimeoutMs = -1`

**Comment by christopherperry** [comment]
I'm experiencing the same issue. The controls display at first but as soon as the video starts to play they disappear, but the visibility is VISIBLE.

For anyone else having this problem, the issue was that the video resize mode made the view resize and push the controls down outside the visible drawing area of the view.
