### ISSUE TITLE
Player stops when in background in Android O and Pie

### ISSUE THREAD

**Issue by Eyliss** [google/ExoPlayer#5117]
### Issue description
My application uses Exoplayer for playing music streams and I have noticed that, after a while, the player stops running when the application is on background for Android Oreo and Pie. I have already migrate the implementation for starting the player service on foreground according the Android background execution limits.

Since I haven't experience the issue in the exoplayer demo nor some others applications, I would like to know how is this handle in the exoplayer project.

### Reproduction steps

With the battery optimization mode enabled:

1. Open the app and select a channel
2. The stream will start being played
3. Put the application on background
4. After a while the stream stops

### Version of ExoPlayer being used
Exoplayer 2.5.1

### Device(s) and version(s) of Android being used
Android Oreo and Pie

**Comment by marcbaechinger** [comment]
Seems like the system is killing your service. Do you find something in the logs when this happens?

Since Oreo you need to start the service with [Context.startForegroundService](https://developer.android.com/reference/android/content/Context#startForegroundService(android.content.Intent)) and then in the service call [Service.startForeground(int, android.app.Notification)](https://developer.android.com/reference/android/app/Service#startForeground(int,%20android.app.Notification)). This should actually do the trick for foreground services.

**Comment by Eyliss** [comment]
We have already migrated the service implementation to the Android O background requirements, so it is done as you mentioned and you are right, it is the system which kills the service when the battery optimization is enabled. 

However, we get complaints about the stream stops from time to time and, since I haven't been able to reproduce it in your demo, I was wondering if there was something else that you have taken into account and I'm not aware of.

Thank you for your time.

**Comment by marcbaechinger** [comment]
Do you find something in the logs when this happens?

**Comment by marcbaechinger** [comment]
Please can you have a look at this FAQ entry?

https://google.github.io/ExoPlayer/faqs.html#how-do-i-keep-audio-playing-when-my-app-is-backgrounded

If this does not help, can you please provide a bug report (taken right after the service has been interrupted) so we can look into the logs?

**Comment by Eyliss** [comment]
My concern is that I haven't been able to reproduce the issue on my devices (Samsung 7 with Android O and Pixel 2 XL with Android P) but we get a lot of users complains about it since Android 8 was released.

Will take a look to WifiLock and WakeLock and will come back when the results.

Thank you so much.

**Comment by DKillWorld** [comment]
I have a media app, that used foreground service. And only O and Pie devices were killing service. What I was doing wrong is I stop foreground service once the playback is paused via notification and reenabling it once playback starts. But actually after pausing foreground service, it never come back in foreground state even with same notification passed. And after 5 mins approx, system kills services logging in logcat that "Killing service XYZ : App inactivity".

I fixed it by never pausing foreground service, instead I put a button to close app and stop service altogether. I tried many solutions, but this effectivly solved it.

**Comment by SunielNayak** [comment]
create a notification and this notification passed in startForeground() method.
and set permission in manifest ->

<uses-permission android:name="android.permission.FOREGROUND_SERVICE" />

code->

  Notification notification = new Notification.Builder(this, NotificationMyChannel.ID)

                    .setContentIntent(pendingactivity)
                    .setSmallIcon(R.mipmap.radio1)
                    .setContentTitle(MainActivity.Rname)
                    .setStyle(new Notification.DecoratedMediaCustomViewStyle())
                    .setCustomContentView(remoteViews)
                    .build();
            startForeground(1, notification);
            NotificationManagerCompat notificationManagerCompat = NotificationManagerCompat.from(this);
            notificationManagerCompat.notify(1, notification);
