### ISSUE TITLE
will you please share the entire code related to switching between multiple subtittle languages,I am new to Exoplayer

### ISSUE THREAD

**Issue by MNGsulochana** [google/ExoPlayer#5118]
will you please share the entire code related to switching between multiple subtittle languages,I am new to Exoplayer

**Comment by marcbaechinger** [comment]
The demo app does this and has all the code for selecting tracks. It uses the TrackSelectionView to create a SelectionOverride in [TrackSelectionView.onTrackViewClicked](https://github.com/google/ExoPlayer/blob/afba6386d333b993777ba74a81d7d8c9d2f808f7/library/ui/src/main/java/com/google/android/exoplayer2/ui/TrackSelectionView.java#L298)

I'd suggest to add your stream containing text tracks to the demo app and then start the PlayerActivity of the demo app with your stream. When you select a certain language in the UI, investigate what happens in the TrackSelectionView/DefaultTrackSelector.
