### ISSUE TITLE
Sensor Type in SphericalSurfaceView class

### ISSUE THREAD

**Issue by Sylvain-interactive** [google/ExoPlayer#5119]
Hi,
Would it be possible to choose the Sensor type between TYPE_GAME_ROTATION_VECTOR and TYPE_ROTATION_VECTOR or change the way it is selected in the SphericalSurfaceView class by checking if the TYPE_GAME_ROTATION_VECTOR is present in the device.

Because my device, a Samsung SM-T700 API 23 does not possess the  TYPE_GAME_ROTATION_VECTOR but your check "Util.SDK_INT >= 18 ? Sensor.TYPE_GAME_ROTATION_VECTOR : Sensor.TYPE_ROTATION_VECTOR" return the TYPE_GAME_ROTATION_VECTOR so there is only the touch mode that is enabled but with the TYPE_ROTATION_VECTOR it works. So could it be possible to set to TYPE_ROTATION_VECTOR ? 

Thank you for your concern.

**Comment by ojw28** [comment]
If `TYPE_GAME_ROTATION_VECTOR` is optional and we're not implementing a fallback, I'd consider this a bug?

**Comment by Sylvain-interactive** [comment]
It is not a bug, I ask if it is possible to choose the type of sensor used by the SphericalSurfaceView, like choose the TYPE_ROTATION_VECTOR when the TYPE_GAME_ROTATION_VECTOR is not available in the device.

**Comment by ojw28** [comment]
Why shouldn't the code just automatically fall back to `TYPE_ROTATION_VECTOR` if `TYPE_GAME_ROTATION_VECTOR` is not available? I don't understand why application code should need (or want) to choose.

**Comment by NicoIM** [comment]
TYPE_ROTATION_VECTOR is an exemple. On some of our devices the TYPE_GAME_ROTATION_VECTOR is not supported, we have to use another rotation vector. 

We would like to be able to chose any type of rotation vector to use instead of the TYPE_GAME_ROTATION_VECTOR.

**Comment by ojw28** [comment]
I'm not convinced there's a good use case for choosing an arbitrary type. There's probably always a correct type to be using, and it's probably `TYPE_GAME_ROTATION_VECTOR` if it exists, and `TYPE_ROTATION_VECTOR` otherwise. In which case the library should just do that for you. In practice are you actually going to want to set it to a different value, and if so, what's the use case for doing so?

**Comment by NicoIM** [comment]
Yes that would be perfect.

The fact is in the SphericalSurfaceView the code that chose the rotation vector is:
`    int type = Util.SDK_INT >= 18 ? Sensor.TYPE_GAME_ROTATION_VECTOR : Sensor.TYPE_ROTATION_VECTOR;
`

It doesn't check if device supports it or not. It only check it's sdk version.

**Comment by ojw28** [comment]
I assume `orientationSensor` ends up being null if the device doesn't support it?

**Comment by Sylvain-interactive** [comment]
yes it's null
