### ISSUE TITLE
HLS/DASH streams only select a bitrate once, at the start. How do I get exoplayer to adapt during playback?

### ISSUE THREAD

**Issue by zapper64** [google/ExoPlayer#5120]
Using exoplayer v2.9.1 on Android 8.0

I'm playing a wide range of live and fixed HLS and DASH streams over ethernet. Here's a synopsis of the exoplayer setup code:

    bandwidthMeter = new DefaultBandwidthMeter();
    mediaDataSourceFactory = new DefaultHttpDataSourceFactory(Util.getUserAgent(mActivity, "ottExoPlayer"), (TransferListener) bandwidthMeter);
    hlsMediaFactory = new HlsMediaSource.Factory(mediaDataSourceFactory);
    dashMediaFactory = new DashMediaSource.Factory(mediaDataSourceFactory);
    TrackSelection.Factory videoTrackSelectionFactory = new AdaptiveTrackSelection.Factory();
    DefaultTrackSelector trackSelector = new DefaultTrackSelector(videoTrackSelectionFactory);
    DefaultRenderersFactory rf = new DefaultRenderersFactory(mAppContext);
    LoadControl lc = new DefaultLoadControl();
    PlayerView playerView = new PlayerView(this);
    playerView.setShutterBackgroundColor(Color.TRANSPARENT);
    mLayout.addView(playerView);
    SimpleExoPlayer mPlayer = ExoPlayerFactory.newSimpleInstance(this, rf, trackSelector, lc, null);
    playerView.setPlayer(mPlayer);
    mPlayer.addListener(new PlayerEventListener());
    mPlayer.setPlayWhenReady(true);
    MediaSource mediaSource = hlsMediaFactory.createMediaSource(Uri.parse("http://some-url.m3u8"));
    DefaultTrackSelector.ParametersBuilder pb = trackSelector.buildUponParameters();
    pb.clearSelectionOverrides();
    pb.setMaxVideoBitrate(35000000);
    pb.setMaxVideoSize(4000, 2500);
    trackSelector.setParameters(pb);
    mPlayer.prepare(mediaSource, true, true);

The streams all play, with good AV sync and are generally well behaved. However, the video track never changes after the initial automatic selection. The first stream played uses the lowest bitrate track and does not move off that, even though the available bandwidth being reported by bandwidthMeter is 20x as high. The next stream to be played chooses an appropriate track, making use of the available bandwidth, but again it never changes, even if the available bandwidth changes very significantly, enough that it should definitely move to a lower or higher bitrate track.

Can someone point to how I should be setting this up differently, or if there is a bug that needs fixing in exoplayer. I see exactly the same behaviour with DASH and live or fixed makes no difference. One other bit of information is that if I play a fixed asset with looping enabled, it will re-assess the track to use at each loop point.

**Comment by marcbaechinger** [comment]
There have been some changes regarding the injection of the bandwidth meter for v2.9.1. It should actually be easier than before, but there is a change.

Can you please look into the Medium post "[Simplified bandwidth meter usage](https://medium.com/google-exoplayer/https-medium-com-google-exoplayer-simplified-bandwidth-meter-usage-17d8189f978b)" and see if this sheds some more light on your issue?

**Comment by tonihei** [comment]
The code looks right though as far as I can see. Creating the BandwdithMeter and adding it as a listener to the data source is no longer needed (but harmless).

Have you considered that the adaptive changes don't take place immediately but only if we have a minimum buffer available to safely switch up? By default we need at least 10 seconds of buffered data before we try switching up.

Also worth checking that the other formats are actually part of the track selection. Can you add an EventLogger to the player (`player.addAnalyticsListener(new EventLogger(trackSelector))`) to get some more details about the available, supported and selected tracks?

**Comment by zapper64** [comment]
I've had quite a lot of diagnostics in this over the days. For example I know I can force it on to any specific track if I want to using code like this:
DefaultTrackSelector.ParametersBuilder pb = trackSelector.buildUponParameters();
pb.clearSelectionOverrides();
DefaultTrackSelector.SelectionOverride so = new DefaultTrackSelector.SelectionOverride(0, forcedIndex);
pb.setSelectionOverride(0, tga, so);
trackSelector.setParameters(pb);
and that works consistently. So all the tracks I list are available to the track selector. Also, as I noted above, if I play a fixed asset on loop, it does make a track change at each loop point.
I've also monitored the amount of buffered data being held, and that frequently heads over 30 seconds worth if it's started on the lowest profile so I think it definitely has enough data to make the assessment. I've also added a log output line in the bandwidth meter whenever it updates it's estimate and this tells me that it definitely is able to compute the estimate and that the figures it has should definitely be triggering a switch.

**Comment by tonihei** [comment]
It's difficult to find out what's wrong without knowing all the details. Can you please provide the requested output from the EventLogger, or even better, provide some example media so that we can check ourselves.

**Comment by zapper64** [comment]
Unfortunately I can't share the streams as they are the property of the client, but we also tested with this 4K DASH url, which demonstrates the problem.
http://amssamples.streaming.mediaservices.windows.net/634cd01c-6822-4630-8444-8dd6279f94c6/CaminandesLlamaDrama4K.ism/manifest(format=mpd-time-csf)
Here's a log from my test app, which shows the available profiles and one and a bit times through the asset on loop. You can see it stick on the lowest profile all the way through the first iteration, then switch up when it loops.
[log-llama-21nov2018.txt](https://github.com/google/ExoPlayer/files/2604427/log-llama-21nov2018.txt)

**Comment by tonihei** [comment]
I just tested the stream above in our demo app and it adapts well to the available bandwidth. I'd suggest to compare the demo app code with your player setup again to see if there is a difference.

Also note that `onTracksChanged` is only called when the set of available tracks changed, not when the individual selected track changed. Maybe there's just a logging problem and the quality is in fact adapting fine for you as well? Please listen to onVideoSizeChanged to get informed of a change in video size.

**Comment by zapper64** [comment]
Many thanks. You are correct, it is adapting. Where can I put my face?! :-)

**Comment by tonihei** [comment]
Glad it was that easy to solve. Closing the issue.
