### ISSUE TITLE
Exoplayer Cast Extension live streaming end of buffer position

### ISSUE THREAD

**Issue by jinfanzon** [google/ExoPlayer#5121]
### Issue description

I've built a player that streams live channels. So I've implemented the Cast extension, but I'm having a hard time to make the stream start at the end of the buffer position, since it is live stream.

Currentlty I'm starting from the beginning of the buffer, but I need to be the closest as I can to live:

`PendingResult result = mCastPlayer.loadItem(new MediaQueueItem.Builder(loadCastMediaInfo()).build(), 0);`

### Version of ExoPlayer being used
2.9.0

### Device(s) and version(s) of Android being used

Android Nougat

**Comment by AquilesCanta** [comment]
Hi @jinfanzon, If using the media item info start time or seeking do not work, there is not much else we can do.

The behavior depends on the default receiver which we do not control. FYI, we are currently working on a custom receiver which should fix most of the issues that the default receiver currently presents. We will release a medium post once it's ready to use.
