### ISSUE TITLE
[PR offer] Always call onCompletion in ConcatenatingMediaSource.moveMediaSource

### ISSUE THREAD

**Issue by BrainCrumbz** [google/ExoPlayer#5125]
### Issue description
In `moveMediaSource` method in `ConcatenatingMediaSource` class, [at this line](https://github.com/google/ExoPlayer/blob/r2.9.0/library/core/src/main/java/com/google/android/exoplayer2/source/ConcatenatingMediaSource.java#L365), when there's actually no source to move (current and new index are the same), the `onCompletion` action is **not** invoked:

```java
if (currentIndex == newIndex) {
    return;
}
```

That is somehow a different behavior than e.g. `removeMediaSourceRange`, where completion callback is invoked right away when there's nothing to remove.

Also, that forces callers to always check for this special scenario, basically requiring a wrapper around this specific operation.

Would you consider a PR changing `moveMediaSource` behavior, so that it always calls completion callback?

We understand this can be considered a breaking change in API, as client code in its own logic may rely on this *missing invocation*. Maybe you could make the new behavior as an opt-in, like an additional method signature on `ConcatenatingMediaSource`, e.g. `moveMediaSource(int currentIndex, int newIndex, @Nullable Runnable actionOnCompletion, bool alwaysComplete)`.

Thanks for your attention

### Reproduction steps
Not Applicable

### Link to test content
Not Applicable

### Version of ExoPlayer being used
2.9.0

### Device(s) and version(s) of Android being used
Not Applicable

### A full bug report captured from the device
Not Applicable

**Comment by tonihei** [comment]
Happy to accept that PR :)  It's definitely a bug and not meant to work like that. The ground truth to determine whether it's an API change or not should be how the method is documented, because that's the contract we are giving to the user of this method. Based on that it's not a breaking API change.
