### ISSUE TITLE
Question: Lowest latency multicast UDP over wifi settings

### ISSUE THREAD

**Issue by whyvas** [google/ExoPlayer#5128]
I am trying to implement gesture based camera controls via a wireless tablet using gestures similar to google maps. I have a makito XCR video encoder sending multicast mpeg-ts video over UDP. What would be the best settings to achieve the lowest possible latency using exoplayer? I just need something that plays the bleeding edge over the buffer.
Previous posts mention that UDP wasn't a valid use case for Exoplayer, has that changed by chance? I've been scrounging the internet for a few weeks and I can't seem to find any examples of low latency UDP streaming setups. Ideally, I would have sub 100ms from glass to glass.

**Comment by marcbaechinger** [comment]
I think UDP is a valid use case as there is a UdpDataSource in the ExoPlayer library. 

There are two existing issues where latency is discussed:

https://github.com/google/ExoPlayer/issues/3995
https://github.com/google/ExoPlayer/issues/3995

**Comment by whyvas** [comment]
Thanks for the quick response. Apologies for my lack of knowledge but here's my code:

```
package com.whyvas.yammr.myapplication;

import android.app.Activity;
import android.net.Uri;
import android.os.Bundle;
import android.view.SurfaceView;

import com.google.android.exoplayer2.ExoPlayerFactory;
import com.google.android.exoplayer2.SimpleExoPlayer;
import com.google.android.exoplayer2.source.ExtractorMediaSource;
import com.google.android.exoplayer2.source.MediaSource;
import com.google.android.exoplayer2.upstream.DefaultBandwidthMeter;
import com.google.android.exoplayer2.upstream.DefaultDataSourceFactory;
import com.google.android.exoplayer2.upstream.UdpDataSource;
import com.google.android.exoplayer2.util.Util;

public class MainActivity extends Activity {
    SimpleExoPlayer player = null;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        player = ExoPlayerFactory.newSimpleInstance(this);
        SurfaceView playerView = findViewById(R.id.surfaceview);
        DefaultBandwidthMeter defaultBandwidthMeter = new DefaultBandwidthMeter();
        UdpDataSource.Factory udpDataSource = new DefaultDataSourceFactory(this, Util.getUserAgent(this, "MainActivity"), defaultBandwidthMeter);
        Uri uri = Uri.parse("udp://239.18.36.42:4300");
        MediaSource videoSource = new ExtractorMediaSource.Factory(udpDataSource).createMediaSource(uri);
        player.setVideoSurfaceView(playerView);
        player.prepare(videoSource);
        player.setPlayWhenReady(true);
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        player.release();

    }

}
```

But I get this error:
```
2018-12-01 14:15:48.242 13151-13185/com.whyvas.yammr.myapplication E/ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to udp://239.18.36.42:4300
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:281)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:250)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:885)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.net.MalformedURLException: unknown protocol: udp
        at java.net.URL.<init>(URL.java:597)
        at java.net.URL.<init>(URL.java:487)
        at java.net.URL.<init>(URL.java:436)
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:426)
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:279)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:250) 
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83) 
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:885) 
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) 
```
I can't seem to find any examples of the UdpDataSource, can anyone steer me in the right direction?

**Comment by fougere-mike** [comment]
I suspect you may need to use a wildcard address. Try: `udp://0.0.0.0:4300`

**Comment by whyvas** [comment]
I tried that address and I got the same result unfortunately. It's very weird, I can't seem to find any UDP examples on the internet.

**Comment by whyvas** [comment]
Ok, so I finally managed to get the stream working. My only remaining issue is that the buffering is around 2500ms, is there any way to get it to 100ms or less? Here is the current code:


 playerV = view.findViewById(R.id.exoPlayerView);
        player = ExoPlayerFactory.newSimpleInstance(this.getContext());
        UdpDataSource.Factory test = buildDataSourceFactory();
        ExtractorsFactory extractorsFactory = new DefaultExtractorsFactory();
        ExtractorMediaSource mediaSource = new ExtractorMediaSource
                .Factory(test)
                .setExtractorsFactory(extractorsFactory)
                .createMediaSource(Uri.parse("udp://@239.255.0.1:1234"));
        playerV.setPlayer(player);
        player.prepare(mediaSource);
        player.setPlayWhenReady(true);`

**Comment by murat-mehmet** [comment]
I'm having the same issue and I see that you could solve this. Can you please share what is in `buildDataSourceFactory()` function. I am using `new DefaultDataSourceFactory(ctx, userAgent);` but apparently you have used something else because everything else seems same.

**Comment by santhosind** [comment]
@whyvas 

I am also facing same issue. could you share buildDataSourceFactory() function.

**Comment by whyvas** [comment]
Apologies for the delay gents, here's the buildDataSourceFactory:

` private DataSource.Factory buildDataSourceFactory() {
        return new UdpDataSource.Factory() {
            @Override
            public DataSource createDataSource() {
                return new UdpDataSource(3000, 100000);
            }
        };
    }`

**Comment by whyvas** [comment]
I am down to about 200ms of latency now. If you're going over wifi, some routers have a very poor implementation of multicasting over wifi, keep that in mind. If you can control your encoder, setting a low GOP and a low TTL made a big difference for me.

**Comment by banic** [comment]
@whyvas 
I also have the same problem with latency. Actually, video latency is about 2 seconds, but audio start 
immediately, before video.
How you solve latency problem? Thanks.

**Comment by tonihei** [comment]
According to https://github.com/google/ExoPlayer/issues/5128#issuecomment-476424469, it seems the original question was resolved. Closing this issue, but feel free to reopen if there is something we need to address.
