### ISSUE TITLE
Is it possible to play an IMA ad at a position in playback

### ISSUE THREAD

**Issue by rs146** [google/ExoPlayer#5130]
Hi,

I have a question regarding Google IMA ads. Is it possible to play an ad at a specific point in playback rather than the VMAP specifying when the ad should be played? I am thinking that AdRules can help in this regard but I'm not fully sure about that.

Thanks.

**Comment by andrewlewis** [comment]
The way the IMA SDK works requires ads to be played at the content positions specified in the ad tag I'm afraid.

One possible workaround is to download the ad tag in your app code and modify the document to change the ad positions as desired, then pass the modified ad tag via `ImaAdsLoader.Builder.buildForAdsResponse`. However, from a policy standpoint, I don't know whether ad servers permit this kind of modification so you'd need to check that.

I'm also not sure about ad rules, but reading [the documentation](https://developers.google.com/interactive-media-ads/docs/sdks/android/ad-rules) it sounds like this is intended to give the ad server control over ad positions, not the player app.
