### ISSUE TITLE
MediaSource identification

### ISSUE THREAD

**Issue by LowLevelSubmarine** [google/ExoPlayer#5131]
Is there a way of identifiying a MediaSource? Im trying to get the title of the current track as an example.
So I thought i could solve my problem by giving each queued MediaSource a specific id so that I can find the corrisponding track data (Title, Url , Image... ) internally with that id. 
ConcatinatingMediaSource.getMediaSource(0) returns me the current media source (I assume that) but I cant find a way of setting the media source apart from the others.

**Comment by LowLevelSubmarine** [comment]
For others: U can use the tag of the current window to identify a track ;)

**Comment by ojw28** [comment]
Yes. the `Factory` classes for the various `MediaSource`s have `setTag(Object)` methods that allow you to set an arbitrary tag object (you could even put the metadata directly into the tag object, if it makes sense for your use case). You can then retrieve the tag associated with the currently playing source by calling `getCurrentTag` on the player.

**Comment by tonihei** [comment]
One further note: Please be aware that the tag is only available in the `Timeline` or from `getCurrentTag` if the media has been prepared. That means right after calling `player.prepare` or after adding a new source to the `ConcatenatingMediaSource`, this will still return null. That's not optimal and we should be probably fix this in the future.
