### ISSUE TITLE
How to add ffmpeg module to exoplayer

### ISSUE THREAD

**Issue by zhangabvc** [google/ExoPlayer#5132]
Exoplayer does not support some audio formats, such as mpga. Ffmpeg supports many audio formats if you add the ffmpeg module to exoplayer？

**Comment by marcbaechinger** [comment]
There is an ffmpeg extension. The readme explains how you can build ffmpef and how to use the extension. Talke a look at it here:

https://github.com/google/ExoPlayer/tree/release-v2/extensions/ffmpeg

**Comment by zhangabvc** [comment]
> There is an ffmpeg extension. The readme explains how you can build ffmpef and how to use the extension. Talke a look at it here:
> 
> https://github.com/google/ExoPlayer/tree/release-v2/extensions/ffmpeg

     I have tried unsuccessfully, what do I need to do after generating the library？

**Comment by marcbaechinger** [comment]
Can you give some more details on what you did and what went wrong? If you have an error message or an stack trace while building/running the app this kind of information would be useful.

Basically you need to use the FfmpegAudioRenderer to play audio files with the ffmpeg extension. So you need to tell ExoPlayer to use that renderer.

There are several ways to set this up, as the [readme of the extension](https://github.com/google/ExoPlayer/tree/release-v2/extensions/ffmpeg) explains.  

In case you are using the DefaultRenderersFactory you need to pass the appropriate ExtensionRenderersMode to the constructor of the [DefaultRenderersFactory](https://github.com/google/ExoPlayer/blob/b5beb32618ac99adc58b537031a6f7c3dd761b9a/library/core/src/main/java/com/google/android/exoplayer2/DefaultRenderersFactory.java#L116). This will be EXTENSION_RENDERER_MODE_PREFER if you want ExoPlayer to always use the rendered based on ffmpeg. If you are using a more custom way to instantiate exoPlayer, please consult the readme for more info.
