### ISSUE TITLE
Could support partial request with http header Range?

### ISSUE THREAD

**Issue by tuesda** [google/ExoPlayer#5133]
For example to load a mp4 video with ExtractorMediaSource 
setting http header "Range:bytes=0-65535" "Range:bytes=65536-131071" ...
like this we can load 65k every time which can preventing from loading from start when connect close at middle of video.

**Comment by tonihei** [comment]
We already do that as far as possible. See [here](https://github.com/google/ExoPlayer/blob/b5beb32618ac99adc58b537031a6f7c3dd761b9a/library/core/src/main/java/com/google/android/exoplayer2/upstream/DefaultHttpDataSource.java#L512).

**Comment by tuesda** [comment]
@tonihei I seen this. but this range is determined by DataSpec's position and length, and length always be C.LENGTH_UNSET that means request  as much as possible, See [here](https://github.com/google/ExoPlayer/blob/b5beb32618ac99adc58b537031a6f7c3dd761b9a/library/core/src/main/java/com/google/android/exoplayer2/source/ExtractorMediaPeriod.java#L884) 
If there is a max size for every request that will be great.

**Comment by tonihei** [comment]
I don't understand yet how this would make things better. For the situation you mentioned, when the connection failed during the load, we would set the DataSpec's position to the next load position and continue from there. So we won't load from the start again.

**Comment by tuesda** [comment]
Yes, you are right! the issue that load from start again when connection fail may be caused by that I removing all headers of http including Range. Thanks a lot for your response which save my whole day.
