### ISSUE TITLE
Question: How to know if QUIC was used or used fallback

### ISSUE THREAD

**Issue by adrixgc** [google/ExoPlayer#5134]
I am using the Cronet extension to play a video using QUIC and the OkHttp extension to use it in case QUIC cannot be used:

        OkHttpDataSourceFactory okHttpDataSourceFactory = new OkHttpDataSourceFactory(new OkHttpClient(), Util.getUserAgent(context, "ExoPlayerDemo"), bandwidthMeter);

        CronetEngine cronetEngine = new CronetEngine.Builder(context).enableQuic(true).build();
        return new CronetDataSourceFactory(new CronetEngineWrapper(cronetEngine),
                Executors.newSingleThreadExecutor(),
                null,
                okHttpDataSourceFactory);

How to know if **QUIC was actually used** or if it failed and it started using TCP (OkHttp)?

**Comment by tonihei** [comment]
The fallback data source factory is only used if the CronetEngine is unavailable. As you specifically provide a CronetEngine in the constructor, it's never used.

**Comment by tonihei** [comment]
Note that Cronet also falls back to traditional Http automatically if QUIC is not available. If you control the server, you should be able to find out what the server supports. 

In case you want to know client-side which protocol is used, you could also fork CronetDataSource and check `UrlResponseInfo.getNegotiatedProtocol()` at the end of the `DataSource.open` call. Can you provide some information why this is needed? We were wondering if the `UrlResponseInfo` should be made available as a protected member for subclasses if there is a use case for that.

**Comment by adrixgc** [comment]
I am trying to play a video of a server I don't own, let's call it, YouVideo ;)
I know the provider allows QUIC, but actually I have no knowledge if that was the protocol I used during the playback. I might "force" QUIC, but there are external problems that can cause QUIC to fail (e.g. UDP blocking). That is why it is very interesting to know which protocol was used during the playback.

**Comment by tonihei** [comment]
If it's just for testing purposes, please consider forking CronetDataSource as described above.

**Comment by adrixgc** [comment]
Unfortunately, it is not for testing. It's for a real-world app and that use case is very demanded

**Comment by tonihei** [comment]
We can look into making this information available for Cronet and possibly for OkHttp as well.

**Comment by ojw28** [comment]
Can you elaborate on what exactly is a very demanded feature? What end user feature would you actually implement with this functionality?

**Comment by adrixgc** [comment]
Can't say much, but the app is performing network traffic analysis of different video providers, therefore knowing the protocol used for the video playback is crucial

**Comment by tonihei** [comment]
Still sounds pretty niche. Anyway, it's easy to make available, so we can do that in our next release.

**Comment by adrixgc** [comment]
That would be fantastic. Any candidate release date?

**Comment by adrixgc** [comment]
Question should be closed since the release was performed. Thanks

**Comment by adrixgc** [comment]
I've been checking the new release (2.9.2). However, I can't find the way to access the new methods created since I am using CronetDataSourceFactory insted of CronetDataSource. Here's my code:
```
HttpDataSource.Factory httpDataSourcefactory = new CronetDataSourceFactory(new CronetEngineWrapper(cronetEngine),
                    Executors.newSingleThreadExecutor(),
                    null,
                    okHttpDataSourceFactory);
                    
DataSource.Factory dataSourcefactory = new DefaultDataSourceFactory(context, bandwidthMeter, httpDataSourcefactory);

DashMediaSource dashMediaSource = new DashMediaSource.Factory(dataSourceFactory).createMediaSource(uri);
dashMediaSource.addEventListener(new Handler(), this);

player.prepare(dashMediaSource);
```

As you can see, I'm always using Factories. How can I access those methods? Would it be possible to have a debug event listener to react to the Transport Protocol change?

**Comment by tonihei** [comment]
You need to overwrite CronetDataSource and read the protocol after opening the source:
```
public class MyCronetSource extends CronetDataSource {
  public MyCronetSource(CronetEngine cronetEngine) {
    super(cronetEngine, Executors.newSingleThreadExecutor(), null);
  }

  @Override
  public long open(DataSpec dataSpec) throws IOException {
    long result = super.open(dataSpec);
    // Use getCurrentUrlResponseInfo() here and in any other method of the data source.
    // This method is call ed on the background loading thread.
    return result;
  }
}
```

And to set up the player just create your data source in a factory:
```
DataSource.Factory factory = () -> new MyCronetDataSource(cronetEngine);
```

**Comment by adrixgc** [comment]
But the parameter to create a CronetDataSourceFactory is a CronetEngineWrapper, not a CronetDataSource

**Comment by tonihei** [comment]
Just use the cronet engine directly in the data source. The wrapper is useless anyway if you provide your own engine.

**Comment by adrixgc** [comment]
Yeah, I got it. I implemented your way and it's fantastic. However, I found 2 different behaviours when it comes to different protocols:

- **Playback via QUIC** (logcat):
```
2018-12-11 18:21:42.717 25169-26587/com.mycompany W/Transport Procotol: h2
2018-12-11 18:21:43.289 25169-26596/com.mycompany W/Transport Procotol: http/2+quic/39
2018-12-11 18:21:43.302 25169-26595/com.mycompany W/Transport Procotol: http/2+quic/39
2018-12-11 18:21:43.490 25169-26596/com.mycompany W/Transport Procotol: http/2+quic/39
2018-12-11 18:21:43.529 25169-26595/com.mycompany W/Transport Procotol: http/2+quic/39
2018-12-11 18:21:44.109 25169-26596/com.mycompany W/Transport Procotol: http/2+quic/39
2018-12-11 18:21:46.903 25169-26595/com.mycompany W/Transport Procotol: http/2+quic/39
2018-12-11 18:21:47.032 25169-26596/com.mycompany W/Transport Procotol: http/2+quic/39
2018-12-11 18:21:47.096 25169-26595/com.mycompany W/Transport Procotol: http/2+quic/39
2018-12-11 18:21:48.559 25169-26596/com.mycompany W/Transport Procotol: http/2+quic/39
```
First row: Manifest retrieved by http. Correct!
Rest of rows: QUIC transport protocol, one per open() call. Correct!

- **Playback via TCP** (logcat):
```
2018-12-11 18:33:08.165 27517-28792/com.mycompany W/Transport Procotol: h2
2018-12-11 18:33:09.127 27517-28797/com.mycompany W/Transport Procotol: unknown
2018-12-11 18:33:09.248 27517-28796/com.mycompany W/Transport Procotol: unknown
2018-12-11 18:33:09.450 27517-28797/com.mycompany W/Transport Procotol: unknown
2018-12-11 18:33:09.657 27517-28796/com.mycompany W/Transport Procotol: unknown
2018-12-11 18:33:10.097 27517-28797/com.mycompany W/Transport Procotol: unknown
2018-12-11 18:33:10.280 27517-28796/com.mycompany W/Transport Procotol: unknown
2018-12-11 18:33:10.288 27517-28797/com.mycompany W/Transport Procotol: unknown
2018-12-11 18:33:10.571 27517-28796/com.mycompany W/Transport Procotol: unknown
```
First row: Manifest retrieved by http. Correct!
Rest of rows: **unknown**, one per open() call. Weird behaviour. **Is this an expected behaviour?**

**Edit:** This question's subject is different from the title. If you think it should be a new issue ticket, tell me.

**Comment by tonihei** [comment]
This is specific to Cronet and not something we can answer here. 

But a quick look at the [doc](https://developer.android.com/guide/topics/connectivity/cronet/reference/org/chromium/net/UrlResponseInfo.html#getNegotiatedProtocol()) shows that it returns an "empty string if no protocol was negotiated, the protocol is not known, or when using plain HTTP or HTTPS."
