### ISSUE TITLE
Issue playing PlayReady media

### ISSUE THREAD

**Issue by TheDiamondPicks** [google/ExoPlayer#5137]
### Issue description
I am developing a native Android application based upon a HBBTV app. It contains PlayReady protected content, which I would like to play. However, it contains an invalid KID (which I fixed by adding a dash), but even with that fixed, it throws a MissingSchemeDataException.

### Reproduction steps
I added the following to DashManifestParser#424:
`defaultKidStrings[i] = defaultKidStrings[i].substring(0, 23) + "-" + defaultKidStrings[i].substring(23);`
But apart from that playing the video clip on an Android TV device causes this error.

### Link to test content
https://pastebin.com/R5quLPPW

### Version of ExoPlayer being used
ExoPlayer dev-2 dd2cba0

### Device(s) and version(s) of Android being used
Xiaomi Mi Box - Android 8.0 (TV)

### A full bug report captured from the device
https://pastebin.com/YLWc7zCP
If you need a full bug report I can provide one, but I suspect the issue is with the content - not the player.

If you need more information, I am happy to provide it

**Comment by marcbaechinger** [comment]
If the kid is wrong in your manifest, wouldn't the best way to fix this be to fix it in the manifest? 

I don't think this stream would work with any other DASH player, so I doubt it's worth changing ExoPlayer's manifest parser to fix it. I recommend fixing the manifest and then try playing the stream again. Currently ExoPlayer is complaining that your content is not PlayReady enabled.

Best would be to have a manifest of which you know it works with your KID. Like one which plays well on another platform so you can validate you have all the uuids right.

**Comment by TheDiamondPicks** [comment]
I am not in control of the manifest - ideally I would change it. The only other platform that I have been able to get it working on is the HBBTV app. At the end of the day if the media is completely unworkable I can probably find some Widevine stuff to use, which I know works in other players, however it requires significantly more API calls at it comes from a different provider - so not ideal.

**Comment by ojw28** [comment]
It looks like the manifest is using `79f0049a-4098-8642-ab92-e65be0885f95` as the UUID for PlayReady. It seems this is the UUID for PlayReady V10, where-as original PlayReady has the UUID `9a04f079-9840-4286-ab92-e65be0885f95`. ExoPlayer currently only handles the latter.

I'm not even sure whether PlayReady V10 is supported at the platform level. I don't know what the difference is between the two, but I'd assume there was most likely a breaking change given a different UUID is used?

I'd suggest you try adding `"urn:uuid:79f0049a-4098-8642-ab92-e65be0885f95"` as an additional case [here](https://github.com/google/ExoPlayer/blob/r2.9.1/library/dash/src/main/java/com/google/android/exoplayer2/source/dash/manifest/DashManifestParser.java#L430), in case it just happens to work.

**Comment by TheDiamondPicks** [comment]
It kinda works. It doesn't throw any exceptions anymore, however there seems to be issues with the audio track:
https://pastebin.com/B75EhhhF
This means there is no audio. Additionally, video seems to be extremely 'stuttery' (if it plays at all), with a large green bar at the top. I can't screenshot it (or get a decent photo), but if it necessary, I can send one through.
Here's the ExoPlayer video information up the top:
![screen](https://user-images.githubusercontent.com/15665219/48958119-0a483b80-efc2-11e8-8e22-3a45e88bf21b.png)
Thanks for your help so far as well, I appreciate it.

Edit: In case it is necessary, here's Exo's output when playing:
![screen](https://user-images.githubusercontent.com/15665219/48958200-6ca13c00-efc2-11e8-98d8-1f5cea583a8f.png)

**Comment by ojw28** [comment]
I don't think there's anything more we can do to help without proper reproduction steps. There's no way for us to reproduce currently (I don't think we have any details of the license server, for example).

**Comment by TheDiamondPicks** [comment]
Unfortunately, the videos have very short token times on them - so it would be difficult to be able to get you guys to reproduce it. Thanks for your help nevertheless.
