### ISSUE TITLE
show_buffering IntDef values are wrongly updated in a commit.

### ISSUE THREAD

**Issue by eneim** [google/ExoPlayer#5139]
Long story short, I think this commit has made the IntDef wrong ...

[check this](https://github.com/google/ExoPlayer/commit/32bd69d4b273869056f384fa81e0c685d38a80ce)

Screenshot below: 
- SHOW_BUFFERING_ALWAYS is changed from 1 to 2.
- SHOW_BUFFERING_WHEN_PLAYING is changed from 2 to 1.

<img width="1430" alt="screen shot 2018-11-23 at 17 02 23" src="https://user-images.githubusercontent.com/1776230/48932939-9e25f300-ef41-11e8-803a-d6f330c724ec.png">

**Comment by tonihei** [comment]
Not sure this makes it wrong. The idea of IntDefs is to use constants instead of number literals when working with these states. So changing the numbers shouldn't make a difference. Can you explain why this is a problem for your code?

**Comment by eneim** [comment]
@tonihei Actually, the real issue is when you set this from xml layout with these enum: [link to attrs.xml](https://github.com/google/ExoPlayer/blob/release-v2/library/ui/src/main/res/values/attrs.xml#L54), it will be recognized here: [link to PlayerView.java](https://github.com/google/ExoPlayer/blob/release-v2/library/ui/src/main/java/com/google/android/exoplayer2/ui/PlayerView.java#L357).

So setting "when_playing" in xml will result in the value to be 2, and in PlayerView.java, it will be compared to "ALWAYS" so this is the wrong behaviour: [link to usage](https://github.com/google/ExoPlayer/blob/release-v2/library/ui/src/main/java/com/google/android/exoplayer2/ui/PlayerView.java#L1210)

**Comment by tonihei** [comment]
Ah, thanks for explaining. We'll fix that.
