### ISSUE TITLE
 How to switch between subtitles in my custom dialog i have used SingleSampleMediaSource 

### ISSUE THREAD

**Issue by Sathish-Kumar-Kanagaraj** [google/ExoPlayer#5143]
I want to switch between subtitles in my custom dialog ,I have parsed single subtitle file using SingleSampleMediaSource but while switching between different subtitles how to handle it without restarting the video, where can i see the piece of code in demo app

**Comment by ojw28** [comment]
You can add any number of subtitle `SingleSampleMediaSource`s to the `MergingMediaSource` that you pass to the player. So if you know where the subtitles are in advance, set them all up before starting playback, and pass them all into the `MergingMediaSource`. This will cause the player to list each one as an available track. This will cause a corresponding track for each of them to become available (e.g. you'll be able to select between them in the demo app). Setting up in this way is very cheap; we don't load the data or parse the subtitle data unless the track is actually selected.

If you don't know the location of the subtitles in advance, and want to add a location mid playback, then that's unfortunately not supported currently. Supporting this is tracked by https://github.com/google/ExoPlayer/issues/1649.
