### ISSUE TITLE
Subtiles Application CEA-608 with DASH, from outside of manifest

### ISSUE THREAD

**Issue by maxTanquerel** [google/ExoPlayer#5148]
### Issue description
I am trying to add subtitles to a dash media source. I get subtitle url from outside the manifest. Subtitles url will return a file that looks like this :

```
[{
	"Id": 0,
	"Action": 0,
	"Line": null,
	"TimeIn": 0,
	"TimeOut": 0
}, {
	"Id": 1,
	"Action": 1,
	"Line": "♪ ♪ ♪",
	"TimeIn": 5672,
	"TimeOut": 14047
}, {
	"Id": 2,
	"Action": 0,
	"Line": null,
	"TimeIn": 14047,
	"TimeOut": 14047
}, {
	"Id": 3,
	"Action": 1,
	"Line": "- Hello guys",
	"TimeIn": 14147,
	"TimeOut": 16583
}, {
	"Id": 4,
	"Action": 1,
	"Line": "Welcome to our famous radio station",
	"TimeIn": 14547,
	"TimeOut": 16583
}, {
	"Id": 5,
	"Action": 0,
	"Line": null,
	"TimeIn": 16583,
	"TimeOut": 16583
...
```

I try to load the subtitles url like this :

```
    val mediaSource = DashMediaSource
                .Factory(DefaultDashChunkSource.Factory(mediaDataSourceFactory), manifestDataSourceFactory)
                .createMediaSource(uri) 

    val textFormat = Format.createTextSampleFormat(
            "en",
            MimeTypes.APPLICATION_CEA608,
            SELECTION_FLAG_DEFAULT,
            "en")

    val subtitlesUri = Uri.parse(closedCaption.url)

    val subtitleSource = Factory(mediaDataSourceFactory).createMediaSource(subtitlesUri, textFormat, C.TIME_UNSET)

    mergedMediaSource = MergingMediaSource(mediaSource, subtitleSource)
    ...
```

I can successfully see and select the track using the TrackSelection dialog provide by exoplayer. **But there is no subtitles display.** I checked in the Cea608Decoder.java class. I can break in the decode method. At the end of the method there is :

```
    if (captionDataProcessed) {
      if (!isRepeatableControl) {
        repeatableControlSet = false;
      }
      if (captionMode == CC_MODE_ROLL_UP || captionMode == CC_MODE_PAINT_ON) {
        cues = getDisplayCues();
      }
    }
```
captionDataProccessed is equal to true and I can break on the captionMode check line. But captionMode is still equal to CC_MODE_UNKNOWN. I don't know if it's a normal or not.

### Conclusion
I can download and decode the file without any error in the logcat window. I can load the track from the TrackSelection dialog. But I cannot see any subtitles on the screen.

Any idea what I am missing ?

### Version of ExoPlayer being used
I am using the exo player version 2.8.2 with Android 9 on Pixel 2

Thank you,

**Comment by ojw28** [comment]
What format is that subtitle file (beyond it being a JSON file)? I'm pretty sure it's not a format we support, in any case.

**Comment by maxTanquerel** [comment]
Thank you for your quick answer.

Backend guys told me it's CEA-608, can you give me an exemple of CEA-608 file that I can show them ?

**Comment by ojw28** [comment]
It's definitely not CEA-608. Maybe it was derived from 608, but as far as I can tell that's just an arbitrary JSON format. Unless it's a known format, I wouldn't expect any player to handle it.

CEA-608 is a binary format embedded directly in the video bitstream. It can also be carried as a track in QuickTime files. I don't think there's such a thing as a standalone CEA-608 file.

**Comment by maxTanquerel** [comment]
Ok, I see. What kind of format, can we use as standalone subtitle file ?

**Comment by ojw28** [comment]
See the "Standalone Subtitle Formats" part of the [supported formats](http://google.github.io/ExoPlayer/supported-formats.html) page.

**Comment by maxTanquerel** [comment]
Thank you for your answers
