### ISSUE TITLE
How to set contentUri in ExoPlayer with AsyncTask

### ISSUE THREAD

**Issue by kinhdang** [google/ExoPlayer#515]
Dear All !

I have tested demo ExoPlayer with m3u8 working properly, but we want to get stream url from service, Anybody know Please help ?

-----call in MainActivity-----
          @Override
	  public void onCreate(Bundle savedInstanceState) {
	    super.onCreate(savedInstanceState);  
	    new getChannel().execute();
         }

-----AsyncTask get stream url -----
class getChannel extends AsyncTask<String, String, String> {
		    
		  
		  protected void onPreExecute() {
				super.onPreExecute();   
		  }
		  
		  //https://www.hurl.it/		  
		  protected String doInBackground(String... args) {    
				return Utilities.getChannel("channel_id");
		  }
		  	
		  protected void onPostExecute(final String url_get) {  				 
				// updating UI from Background Thread
				runOnUiThread(new Runnable() {
					public void run() {					  
						try {   
							contentUri = Uri.parse(url_get); 
							releasePlayer();
							preparePlayer();
						} catch (Exception e) {
							// TODO Auto-generated catch block
							e.printStackTrace();
						}	 
					}
				});					
			} 
	  }

Problems : 06-03 11:31:43.206: E/EventLogger(1973): com.google.android.exoplayer.upstream.DefaultUriDataSource$UnsupportedSchemeException: Unsupported URI scheme: "http ........................

**Comment by ojw28** [comment]
If the service is in your own process, then you should (in my opinion) just not do this. If it isn't, then ExoPlayer should work fine with content URIs of the form `content://authority/path/123`.

**Comment by kinhdang** [comment]
Hello, 

If we set this.contentUri = Uri.parse(stream_url) direct in  public void onCreate(Bundle savedInstanceState) {
	    super.onCreate(savedInstanceState);
.........................
} then Project  working properly
but if we get stream_url from service after assigned in 

protected void onPostExecute(String url_get) {  				 
				// updating UI from Background Thread 				  
				try {   
      MainActivity.this.contentUri = Uri.parse(stream_url) 
				} catch (Exception e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}	 				
			}  


Error :
06-03 16:34:00.377: E/EventLogger(3885): internalError [0.09, rendererInitError]
06-03 16:34:00.377: E/EventLogger(3885): com.google.android.exoplayer.upstream.DefaultUriDataSource$UnsupportedSchemeException: Unsupported URI scheme: "http
06-03 16:34:00.377: E/EventLogger(3885): 	at com.google.android.exoplayer.upstream.DefaultUriDataSource.open(DefaultUriDataSource.java:157)
06-03 16:34:00.377: E/EventLogger(3885): 	at com.google.android.exoplayer.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:97)
06-03 16:34:00.377: E/EventLogger(3885): 	at com.google.android.exoplayer.upstream.DataSourceInputStream.open(DataSourceInputStream.java:56)
06-03 16:34:00.377: E/EventLogger(3885): 	at com.google.android.exoplayer.upstream.UriLoadable.load(UriLoadable.java:92)
06-03 16:34:00.377: E/EventLogger(3885): 	at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:242)
06-03 16:34:00.377: E/EventLogger(3885): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
06-03 16:34:00.377: E/EventLogger(3885): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
06-03 16:34:00.377: E/EventLogger(3885): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
06-03 16:34:00.377: E/EventLogger(3885): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
06-03 16:34:00.377: E/EventLogger(3885): 	at java.lang.Thread.run(Thread.java:818)
06-03 16:34:00.397: E/EventLogger(3885): playerFailed [0.12]
06-03 16:34:00.397: E/EventLogger(3885): com.google.android.exoplayer.upstream.DefaultUriDataSource$UnsupportedSchemeException: Unsupported URI scheme: "http
06-03 16:34:00.397: E/EventLogger(3885): 	at com.google.android.exoplayer.upstream.DefaultUriDataSource.open(DefaultUriDataSource.java:157)
06-03 16:34:00.397: E/EventLogger(3885): 	at com.google.android.exoplayer.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:97)
06-03 16:34:00.397: E/EventLogger(3885): 	at com.google.android.exoplayer.upstream.DataSourceInputStream.open(DataSourceInputStream.java:56)
06-03 16:34:00.397: E/EventLogger(3885): 	at com.google.android.exoplayer.upstream.UriLoadable.load(UriLoadable.java:92)
06-03 16:34:00.397: E/EventLogger(3885): 	at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:242)
06-03 16:34:00.397: E/EventLogger(3885): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
06-03 16:34:00.397: E/EventLogger(3885): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
06-03 16:34:00.397: E/EventLogger(3885): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
06-03 16:34:00.397: E/EventLogger(3885): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
06-03 16:34:00.397: E/EventLogger(3885): 	at java.lang.Thread.run(Thread.java:818)



How to use EXOPlayer in this situation ?

**Comment by ojw28** [comment]
That log suggests two things:
- Your using an out-dated version of the library. Please update it. UnsupportedSchemeException doesn't even exist in the latest version.
- The URI you're building may or may not be malformed. What's the actual URI you're trying to use?

**Comment by kinhdang** [comment]
Thank for your help,

How to get lasted exoplayer jar file.

thank again,

**Comment by kinhdang** [comment]
Update exoplayer lib was resolve this problems.

Thanks all,
