### ISSUE TITLE
Use case: internet disappeared during playback

### ISSUE THREAD

**Issue by goodibunakov** [google/ExoPlayer#5150]
Where i have to progressbar.setvisibility(VISIBLE) if internet disappeared during playback?
I tried to do this in onPlayerError but this method only works after a while.

**Comment by andrewlewis** [comment]
Currently we don't listen for network connectivity changes inside the player so you'll need to do this in your app. Please see the documentation on [managing network usage](https://developer.android.com/training/basics/network-ops/managing), and in particular the sections [Check a device's network connection](https://developer.android.com/training/basics/network-ops/managing#check-connection) and [Detect connection changes](https://developer.android.com/training/basics/network-ops/managing#detect-changes). ExoPlayer has some code that uses these APIs in its [RequirementsWatcher](https://github.com/google/ExoPlayer/blob/e25b7d2/library/core/src/main/java/com/google/android/exoplayer2/scheduler/RequirementsWatcher.java) which may also be helpful to look at.

**Comment by goodibunakov** [comment]
@andrewlewis Thanks!
