### ISSUE TITLE
ExoPlayer zooming on full screen like xplayer?  

### ISSUE THREAD

**Issue by taimoorMalik** [google/ExoPlayer#5152]
I'm currently facing a problem regarding full screen zoom i have working file the only issue is when i zoom the surface it don't zoom on the full screen and crop upper and lower area (landscape video player in portrait) 

In exoplayer : https://drive.google.com/file/d/1TbJfuiIeZrEZMz9kfGGQqfaQkDcuHmRl/view?usp=sharing

In xplayer : https://drive.google.com/file/d/1m5aLz1x_EDcvtj6mVhYgm3gGF_n62cdw/view?usp=sharing

i set the resize mode to zoom and it start zooming on full screen but it zoomed video initially to cover on full screen, i want the video to have aspect ratio FIT but when i want to zoom it zoom on full screen, please help me as i stuck here, thanks

**Comment by andrewlewis** [comment]
It should work if you set up your layout like in the demo app: have a `PlayerView` with width/height set to `match_parent` in the activity's `FrameLayout`, then call `playerView.setResizeMode(AspectRatioFrameLayout.RESIZE_MODE_ZOOM);` when you want to switch to zooming to fill the screen. This causes the video to zoom to fill the screen while remaining in the correct aspect ratio.

If that doesn't work you can probably debug what's going on in your app with the [layout inspector](https://developer.android.com/studio/debug/layout-inspector).

**Comment by taimoorMalik** [comment]
Well when i set it to playerView.setResizeMode(AspectRatioFrameLayout.RESIZE_MODE_ZOOM); it zoomed video to fill screen automatically i want to stay as it is and when user pinch it will zoom accordingly.

**Comment by andrewlewis** [comment]
`PlayerView` doesn't support pinch to zoom I'm afraid. Maybe https://github.com/Manuiq/ZoomableTextureView will do what you need, or can be used as inspiration, though I haven't tried it.

**Comment by taimoorMalik** [comment]
i'm using it Zoomabletextureview, and zoom working but i want result as above screenshots!

**Comment by andrewlewis** [comment]
This doesn't seem to be an issue with the ExoPlayer library so we can't do much to help here. I suggest checking that the zoomable view is filling the parent (like the `PlayerView` in ExoPlayer's demo app) and debugging the layout using the layout inspector as suggested above.

**Comment by taimoorMalik** [comment]
ok thanks
