### ISSUE TITLE
Video corruption when playing a live DASH stream

### ISSUE THREAD

**Issue by xpouyat** [google/ExoPlayer#5158]
### Issue description
When playing a live DASH stream (coming from Azure Media Services), we see some corruption on the video. It does happen time to time, with some bitrates. To reproduce, it is needed to select a mid range bitrate and wait for a few minutes.

Please note that we don't experience such issue on PC (Edge/Chrome) using DASH, or iOS devices using HLS.

### Reproduction steps
It can be reproduced with ExoPlayer demo app. Run the DASH stream provided and select a specific bitrate. For example 1280x720 @ 4 Mbps. Wait for a few minutes and observe the video.
I will send you a video capture of the issue and a source URL to test.

### Link to test content
Sent to dev.exoplayer@gmail.com

### Version of ExoPlayer being used
2.9.1

### Device(s) and version(s) of Android being used
Issue reproduced on several Android phones and set top boxes.
Reproduced for example on Android S9+. Android version 8.0.0

### A full bug report captured from the device
Sent to dev.exoplayer@gmail.com

**Comment by xpouyat** [comment]
Here is the logcat output when video is corrupted. We see EventLogger: droppedFrames and signalFlush events.

11-28 16:04:54.637 23725 23725 D EventLogger: timelineChanged [876.32, 502.16, window=0, period=0, periodCount=1, windowCount=1, reason=DYNAMIC
11-28 16:04:54.637 23725 23725 D EventLogger:   period [?]
11-28 16:04:54.637 23725 23725 D EventLogger:   window [536.00, true, true]
11-28 16:04:54.637 23725 23725 D EventLogger: ]
11-28 16:04:59.739 23725 23725 D EventLogger: timelineChanged [881.43, 501.18, window=0, period=0, periodCount=1, windowCount=1, reason=DYNAMIC
11-28 16:04:59.739 23725 23725 D EventLogger:   period [?]
11-28 16:04:59.740 23725 23725 D EventLogger:   window [535.91, true, true]
11-28 16:04:59.740 23725 23725 D EventLogger: ]
11-28 16:05:04.648 23725 23725 D EventLogger: timelineChanged [886.34, 502.17, window=0, period=0, periodCount=1, windowCount=1, reason=DYNAMIC
11-28 16:05:04.648 23725 23725 D EventLogger:   period [?]
11-28 16:05:04.648 23725 23725 D EventLogger:   window [536.00, true, true]
11-28 16:05:04.648 23725 23725 D EventLogger: ]
11-28 16:05:09.779 23725 23725 D EventLogger: timelineChanged [891.47, 501.30, window=0, period=0, periodCount=1, windowCount=1, reason=DYNAMIC
11-28 16:05:09.779 23725 23725 D EventLogger:   period [?]
11-28 16:05:09.779 23725 23725 D EventLogger:   window [536.00, true, true]
11-28 16:05:09.779 23725 23725 D EventLogger: ]
11-28 16:05:10.225 23725 23725 D EventLogger: droppedFrames [891.91, 501.75, window=0, period=0, 50]
11-28 16:05:12.594 23725 23725 D EventLogger: droppedFrames [894.28, 504.11, window=0, period=0, 71]
11-28 16:05:12.595 23725 14821 I ACodec  : [OMX.Exynos.avc.dec] signalFlush
11-28 16:05:12.595 23725 14822 I ACodec  : [OMX.Exynos.avc.dec] ExecutingState flushing now (codec owns 1/5 input, 10/16 output).
11-28 16:05:12.596 23725 14822 I ACodec  : [OMX.Exynos.avc.dec] Now Flushing
11-28 16:05:12.600 23725 14822 I ACodec  : [OMX.Exynos.avc.dec] FlushingState onOMXEvent(0,1,0)
11-28 16:05:12.626 23725 14822 I ACodec  : [OMX.Exynos.avc.dec] FlushingState onOMXEvent(0,1,1)
11-28 16:05:12.626 23725 14822 I ACodec  : [OMX.Exynos.avc.dec] Now Executing
11-28 16:05:14.634 23725 23725 D EventLogger: timelineChanged [896.32, 502.15, window=0, period=0, periodCount=1, windowCount=1, reason=DYNAMIC
11-28 16:05:14.634 23725 23725 D EventLogger:   period [?]
11-28 16:05:14.634 23725 23725 D EventLogger:   window [536.00, true, true]
11-28 16:05:14.634 23725 23725 D EventLogger: ]
11-28 16:05:14.856 23725 14821 I ACodec  : [OMX.Exynos.avc.dec] signalFlush
11-28 16:05:14.857 23725 14822 I ACodec  : [OMX.Exynos.avc.dec] ExecutingState flushing now (codec owns 3/5 input, 8/16 output).
11-28 16:05:14.859 23725 14822 I ACodec  : [OMX.Exynos.avc.dec] Now Flushing
11-28 16:05:14.861 23725 14822 I ACodec  : [OMX.Exynos.avc.dec] FlushingState onOMXEvent(0,1,0)
11-28 16:05:14.866 23725 14822 I ACodec  : [OMX.Exynos.avc.dec] FlushingState onOMXEvent(0,1,1)
11-28 16:05:14.866 23725 14822 I ACodec  : [OMX.Exynos.avc.dec] Now Executing
11-28 16:05:15.008 23725 23725 D EventLogger: droppedFrames [896.70, 502.53, window=0, period=0, 50]
11-28 16:05:19.765 23725 23725 D EventLogger: timelineChanged [901.45, 501.29, window=0, period=0, periodCount=1, windowCount=1, reason=DYNAMIC
11-28 16:05:19.766 23725 23725 D EventLogger:   period [?]
11-28 16:05:19.766 23725 23725 D EventLogger:   window [536.00, true, true]
11-28 16:05:19.766 23725 23725 D EventLogger: ]
11-28 16:05:20.749 23725 14821 I ACodec  : [OMX.Exynos.avc.dec] signalFlush
11-28 16:05:20.750 23725 14822 I ACodec  : [OMX.Exynos.avc.dec] ExecutingState flushing now (codec owns 0/5 input, 8/16 output).
11-28 16:05:20.750 23725 23725 D EventLogger: droppedFrames [902.44, 502.27, window=0, period=0, 57]
11-28 16:05:20.751 23725 14822 I ACodec  : [OMX.Exynos.avc.dec] Now Flushing
11-28 16:05:20.755 23725 14822 I ACodec  : [OMX.Exynos.avc.dec] FlushingState onOMXEvent(0,1,0)
11-28 16:05:20.760 23725 14822 I ACodec  : [OMX.Exynos.avc.dec] FlushingState onOMXEvent(0,1,1)
11-28 16:05:20.761 23725 14822 I ACodec  : [OMX.Exynos.avc.dec] Now Executing
11-28 16:05:24.670 23725 23725 D EventLogger: timelineChanged [906.36, 502.19, window=0, period=0, periodCount=1, windowCount=1, reason=DYNAMIC
11-28 16:05:24.671 23725 23725 D EventLogger:   period [?]
11-28 16:05:24.671 23725 23725 D EventLogger:   window [536.00, true, true]

**Comment by xpouyat** [comment]
We have been able to mitigate the issue by disabling the “dynamic_sub_gop” feature in the Elemental live encoder.

**Comment by andrewlewis** [comment]
Thanks for the information!
