### ISSUE TITLE
Question: Fallback to TCP when QUIC is suddenly blocked

### ISSUE THREAD

**Issue by adrixgc** [google/ExoPlayer#5160]
I am using the Cronet ExoPlayer extension and I want to test the fallback from QUIC to TCP. For that, I am doing the 2 following cases:

1. With a **rooted** phone, when the playback is started with QUIC, I am blocking udp with the following instruction:
`iptables -A INPUT -p 17 --sport 443 -j REJECT`
That way, QUIC is blocked and it should fall back to TCP (same as YouTube native app is doing).

2. With a **non-rooted** phone, I am playing a video with QUIC and **cellular data**, when half buffered, I am enabling WiFi and it is connecting to a network in which UDP is blocked. In this case, it should also fall back to TCP.

In both cases, the fallback is not happening, and I am getting an exception:
`com.google.android.exoplayer2.ext.cronet.CronetDataSource$OpenException: org.chromium.net.impl.QuicExceptionImpl: Exception in CronetUrlRequest: net::ERR_QUIC_PROTOCOL_ERROR, ErrorCode=10, InternalErrorCode=-356, Retryable=false, QuicDetailedErrorCode=25`

**Is there a way to make this work?** (should be, since YouTube native app is doing it)

**Comment by andrewlewis** [comment]
Did you enable HTTP/2 as well as QUIC? When I tried using your iptables command to block UDP, I found that playback continued with protocol `http/2+quic/39`. Anyway, I'm not sure how to check the fallback but maybe someone else can help, or you may get a better answer by posting this on a Cronet-related forum as it's not really related to the ExoPlayer library.

**Comment by adrixgc** [comment]
Yes, I enabled HTTP/2 as well as QUIC. When playback starts with QUIC and the iptables command is run, the playback stops (you can see the buffer decreasing) until onPlayerError is triggered (when it should fallback to TCP and keep the buffer). Did you manage to make it work?
