### ISSUE TITLE
I am getting an id:1/8219 in subtitle track list other than the tracks i given

### ISSUE THREAD

**Issue by Sathish-Kumar-Kanagaraj** [google/ExoPlayer#5161]
**Description**
      when i pass the hls url to stream video data along with that i am sending subtitle uri's using Merging Media source but unfortunately i am getting a **id:1/8219** added in that subtitle track list ,while i am choosing it the subtitle is getting disable.But i also written functionality to disable subtitle option using None Option along with that getting this id:1/8219 unknown one added in the track list.Kindly help me with it.How can i remove this id:1/8219 from my subtitles track list.

**Issue Reproduce Steps:**
       I am using auto quality feature also,when the data streaming in auto is happening at 240p .At that point of time i am getting this subtitle id in the track list permanently for that video.

I am Using Exoplayer Latest Version 2.9.0

**Comment by andrewlewis** [comment]
Are you sure this is a text track not a metadata track? Please could you play your stream with the demo app and provide the logcat output from `EventLogger` for `tracksChanged`, as this will show the IDs and formats of tracks?

**Comment by ojw28** [comment]
Closing due to lack of follow up.
