### ISSUE TITLE
How to use use decode_mode, headers and secure_uri tags in Exoplayer?

### ISSUE THREAD

**Issue by jmimohsin** [google/ExoPlayer#5163]
Hi,

Using latest version 2.9.1

Now I want to play a url which is playing in MxPlayer if we pass these tags else not playing. I want to use that tags in ExoPlayer too, If possible please let me know.

like this:-
```java
intent.putExtra("decode_mode", (byte) 2);
intent.putExtra("headers", new String[]{"User-Agent", this.userAgent, "Extra-Header", "911"});
intent.putExtra("secure_uri", true);
```
Thanks.

**Comment by andrewlewis** [comment]
For selection of software vs hardware decoders see #3039. For most use cases it's preferable to leave this up to the platform.

`DefaultHttpDataSourceFactory` allows for setting the user agent and custom HTTP headers (request properties) via its constructor and methods.

The current versions of ExoPlayer's provided UI components do not show the media URI.

**Comment by jmimohsin** [comment]
Thanks for help, Video is working but now no sound. I use this one too:-
```kotlin
val rf = DefaultRenderersFactory(this@SinglePlayerActivity, DefaultRenderersFactory.EXTENSION_RENDERER_MODE_PREFER)
exoPlayer = ExoPlayerFactory.newSimpleInstance(this@SinglePlayerActivity, rf, trackSelector)
```

I am able to play video but sound is not coming now.

**Comment by andrewlewis** [comment]
Hard to say what's the cause without more information but you can probably remove `DefaultRenderersFactory.EXTENSION_RENDERER_MODE_PREFER` (unless you really do want to use extensions, in which case you'll need to build them by following the instructions in the READMEs).

**Comment by jmimohsin** [comment]
Thanks for help.
