### ISSUE TITLE
Calling setPlayWhenReady(false) while Player is in Player.STATE_ENDED will send another Player.STATE_ENDED to onPlayerStateChanged callback

### ISSUE THREAD

**Issue by marcochin** [google/ExoPlayer#5167]
### Issue description
Calling `SimpleExoPlayer.setPlayWhenReady(false)` while the Player is in `Player.STATE_ENDED` state will trigger the `onPlayerStateChanged` callback again with another `Player.STATE_ENDED` state. 
Is this intentional behavior?

### Reproduction steps
1) Let a video play to the end so it hits the Player.STATE_ENDED state. 
2) Try to pause the video by calling SimpleExoPlayer.setPlayWhenReady(false).
3) Player.STATE_ENDED is sent again in the onPlayerStateChanged callback.

### Version of ExoPlayer being used
2.9.1

### Device(s) and version(s) of Android being used
Nvidia Shield, 8.0

**Comment by ojw28** [comment]
`onPlayerStateChanged` is documented as:

> Called when the value returned from either Player.getPlayWhenReady() or Player.getPlaybackState() changes.

So yes it is correct, provided `playWhenReady` was previously set to true, because the value returned from `getPlayWhenReady` changes.
