### ISSUE TITLE
the usage of CachedContentIndex 

### ISSUE THREAD

**Issue by NgWaiKong** [google/ExoPlayer#5168]
What is the role of CachedContentIndex? Why do we still need to do a mapping of id and key in it? What bugs might there be if we don't do this mapping?

**Comment by erdemguven** [comment]
Normally you don't need to use CachedContentIndex directly. It is used by SimpleCache. Nothing happens if you don't use it directly :)

**Comment by NgWaiKong** [comment]
Excuse me, is this CacheContentIndex for performance optimization? I see that I will store a copy of the file "cached_content_index.exi", which seems to be optimized for performance.

**Comment by ojw28** [comment]
`CachedContentIndex` serves multiple roles:
* Storing metadata associated with each key, such as the content length (of the entire piece of content; so this is different to the size of the cached file(s) unless the content is fully cached) and the URI after redirection. This metadata is used in `CacheDataSource`.
* The mapping of id to key provides the ability to encrypt the content keys, although this is not enabled by default.

**Comment by NgWaiKong** [comment]
> `CachedContentIndex` serves multiple roles:
> 
> * Storing metadata associated with each key, such as the content length (of the entire piece of content; so this is different to the size of the cached file(s) unless the content is fully cached) and the URI after redirection. This metadata is used in `CacheDataSource`.
> * The mapping of id to key provides the ability to encrypt the content keys, although this is not enabled by default.

Actually, when the CacheSpan update triggers the  CachedContentIndex 's store( ) , and the function is time-consuming, and because the data stream is synchronized, which increases the time-consuming of data transfer throughout the playback process. Cached Content Index Store takes 10 ms to 50 ms (on Nexus 6) at a time. Are there any plans for optimization? Such as limiting the update time of store( )

**Comment by ojw28** [comment]
Yes, we plan to reduce the cases where `store()` is called, and also optimize it to be faster for the remaining cases.
