### ISSUE TITLE
The player returns an incorrect value for the current position when using ConcatenatingMediaSource and ExtractorMediaSource.

### ISSUE THREAD

**Issue by vorobyovda** [google/ExoPlayer#5172]
Hi

I'm running ExoPlayer 2.9.1 on Pixel 2 with Android 8.1.0

In this sample, I connected empty video fragments twice using ConcatenatingMediaSource and ExtractorMediaSource.   
When we start the application, the logs show that, in the end of the first video, the player returns an incorrect value (slightly less than the current video position) for 1 second. 
Here’s a link to the repository with the sample: https://github.com/vorobyovda/exoplayer_test

Any ideas on why this happens and how I can eliminate it?

Thanks!

**Comment by andrewlewis** [comment]
The MP4 you're trying to play seems to have one minute of video but only one second of audio. Could you try making the audio and video track durations match and seeing whether that fixes the issue?
