### ISSUE TITLE
Content failed after bitrate switch to HD with HDCP V 1.0

### ISSUE THREAD

**Issue by rajeshghosh1978** [google/ExoPlayer#5174]
### Issue description
We are trying to play a content with HDCP: 1.0 .Sometime, It played for the first few seconds in SD but it failed when it switches to HD, sometime it desn't play at all  (When it starts with HD directly). Though this is a valid scenario as our DRM policy is only allowed to play SD content with HDCP v1.0. But why Exopayer tries to switch to an upper bitrate when it knows the device doesn't have those capacities. Is this the similar reason of my another issue #5166 (Closed)  

### Reproduction steps
I can't share the link of our content. DRM policy is only allowed to play SD content with HDCP v1.0.

### Link to test content
I can't share the content link in anyways.

### Version of ExoPlayer being used
2.9.2

### Device(s) and version(s) of Android being used
Galaxy S8
Model Number : SM-G950U1
Android Version :8.0

### A full bug report captured from the device
Can't capture log while connected to HDMI as it is playing in device at the same time.

**Comment by andrewlewis** [comment]
Could you clarify how this differs from #5166?

**Comment by rajeshghosh1978** [comment]
Is there any option to detect connected HDCP version for ANdroid API level 19

**Comment by andrewlewis** [comment]
[FLAG_SUPPORTS_PROTECTED_BUFFERS](https://developer.android.com/reference/android/view/Display#FLAG_SUPPORTS_PROTECTED_BUFFERS) will be set on the output display if L1 playback is supported, which is probably what you need (although it's not exactly telling you whether HDCP is in use or not).
