### ISSUE TITLE
[Question] Custom implementation for raw H.264 Annex B support

### ISSUE THREAD

**Issue by TroyStopera** [google/ExoPlayer#5175]
#### Scenario
We are opening a web socket to our backend which is providing a raw H.264 stream. The backend is already splitting the stream into NAL units, so the messages we receive through the socket are already properly split at the NAL headers (0x00000001). What we are trying to do is create custom components that will enable ExoPlayer to play our stream.

#### What We've Tried
We did some research and found that #3503 is similar to our situation. Following the advice there, we have successfully created a `DataSource` which wraps a web socket and is receiving the NAL units. We also created an `Extractor` that is modeled after the `Ac3Extractor` but uses an `H264Reader`, as suggested by the previously mentioned issue. Our `Extractor` is receiving the bytes from the `DataSource` and passing them to `H264Reader.consume(ParsableByteArray)`.

#### Our Problem
After finding the first SPS, PPS, and IDR NAL units, the player plays a single frame, but that is all. The `DataSource` and `Extractor` keep running and receiving bytes, but it seems the `H264Reader` is failing to work. Issue #3503 states there are "...a few more details to work out, like how to set timing information on output samples." We believe our issue relates to these "details" but are unsure what these details are. We have tried calling `H264Reader.packetStarted(Long, Boolean)` but that doesn't seem to do anything, so we may be dong it incorrectly. What are these "details" and how should we go about implementing them?

I can provide code samples as well as samples of our byte stream if that would be helpful. Looking forward to hearing back!

**Comment by andrewlewis** [comment]
`packetStarted` sets the presentation timestamp for the next NAL unit started from `consume`. I don't think you get timing information in the Annex B bytestream, so you probably need to get frame timestamps from some other source (e.g., by assuming a constant frame rate). If you don't do this all the samples will end up with timestamp 0. If your stream doesn't have access unit delimiters you will need to set the `detectAccessUnits` flag to true at construction time.

I think a good step to debugging this is to set a breakpoint at the call to `sampleMetadata` and check that the sample timestamps and sizes look correct.

**Comment by TroyStopera** [comment]
Thanks for the quick reply!

I have tried what you suggested. At the breakpoint, the timestamp appears to be accurate, and the size of the NAL unit is correct as well. Our stream doesn't have access unit delimiters so I set `detectAccessUnits` to true. 

However, the video is still not playing. The `currentPosition` of the `ExoPlayer` instance is counting up correctly, but still only one frame is playing, then nothing else.

**Comment by andrewlewis** [comment]
In `MediaCodecRenderer.feedInputBuffer` you can check that the buffers are being queued to the decoder as expected, and in `MediaCodecVideoRenderer.processOutputBuffer` you can see how the output is being handled.

**Comment by TroyStopera** [comment]
I followed your advice and put some debug print statements in those methods. It turns out that we were using `H264Reader.packetStarted(Long, Boolean)` incorrectly. We were passing a timestamp, which was increased with each successive packet, but it turns out we needed to start at 0 rather than the actual timestamp of the video. Once we did this the video began playing correctly. 
##### For future people running into similar issues, make sure to start your first packet at 0.

**Comment by tishion** [comment]
@TroyStopera  I have a question for implementation of Extractor, you said you used H264Reader but I don't know how to construct the H264Reader instance. Where to get the SeiReader?

**Comment by TroyStopera** [comment]
@tishion Sorry for only just seeing this. I started by using reflection to get an instance (not my favorite, but it worked). I ended up, however, copying the code from `H264Reader`'s source and adapting it to my needs. Our stream has no SEI data, so in my custom implementation I just did away with the `SeiReader`.

**Comment by tishion** [comment]
@TroyStopera  thanks for replying. I finally gave up the extractor implementation. and I just construct the FLV stream with the raw H264 data and fill this stream to Exoplayer.
