### ISSUE TITLE
Auto quality does not work properly

### ISSUE THREAD

**Issue by majidebrahimii** [google/ExoPlayer#5178]
I used the example and version 2.9.1. The selected auto quality is not properly selected and does not match the speed of the Internet. How to fix it, or how can I display the quality on other qualities.

**Comment by ojw28** [comment]
Closing because insufficient information has been provided. Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).
