### ISSUE TITLE
How to get header information of HLS videos chunks?

### ISSUE THREAD

**Issue by sachinbhanot** [google/ExoPlayer#518]
Hi, 

I am playling HLS video. I need the header information of video chunk .
How to get header information of HLS videos chunks?

**Comment by ojw28** [comment]
What's the use case? There's no way to do this currently.

**Comment by Arqu** [comment]
You can rip up the TsExtractor, there are a few functions regarding parsing headers from TS chunks, if that is what you need.

**Comment by nurne** [comment]
@Arqu can you please point out to a specific callback?

**Comment by Arqu** [comment]
No, not really, there is a bunch of code in the Extractor and Readers. If your into this maybe you should take a look at MPEG TS and its encoding scheme. However considering you opened this issue:
https://github.com/google/ExoPlayer/issues/541, while it is possible for you to look at the ts chunks and based on their header info determine if it is a video or audio chunk, I wouldn't suggest that. First its way too low level and given the chance you might end up with a lot of audio only chunk anyways from a stream even if it has video. To check if a HLS stream has any video, I'd suggest looking at the Playlist parser or maybe at track creation.

**Comment by ojw28** [comment]
I have no idea what this issue is actually about at this stage, so marking it as closed.
