### ISSUE TITLE
OkHttp extension 2.9.2 missing from jcenter

### ISSUE THREAD

**Issue by talklittle** [google/ExoPlayer#5184]
### Issue description
https://jcenter.bintray.com/com/google/android/exoplayer/extension-okhttp/ shows up to 2.9.1 but missing 2.9.2.

Other artifacts (core and extensions) have 2.9.2, for example https://jcenter.bintray.com/com/google/android/exoplayer/extension-cast/2.9.2/

### Reproduction steps
Add dependency `implementation 'com.google.android.exoplayer:extension-okhttp:2.9.2'`

### Version of ExoPlayer being used
2.9.2

**Comment by ojw28** [comment]
Thanks for letting us know. This should now be fixed.

**Comment by Tolriq** [comment]
@ojw28 Same issue with 2.9.6 for OkHttp

**Comment by ojw28** [comment]
Thanks for letting us know. This should now be fixed.
