### ISSUE TITLE
How can i change Notification Ui?

### ISSUE THREAD

**Issue by Naguchennai** [google/ExoPlayer#5185]
How can i change Notification Ui?
after watching thisw video https://www.youtube.com/watch?v=svdq1BWl4r8
how can i design or change notification ui?

**Comment by erdemguven** [comment]
Could you be more specific about your question.? Do you mean player notifications or download notifications?

**Comment by Naguchennai** [comment]
need more info???  i understand.. so its not possible ... u must be say straight answer...

**Comment by gowthamgts** [comment]
@naguchennai: Please be polite and civil while asking questions towards open source communities. They are not entitled to answer your questions.

**Comment by ojw28** [comment]
Closing because it's unclear what the question is. Or at least, the question is not specific enough to be within the scope of this issue tracker.
