### ISSUE TITLE
no video, only audio (ts files)

### ISSUE THREAD

**Issue by tipoc123** [google/ExoPlayer#5186]
### Issue description
Exoplayer plays audio, but no video (black screen).

### Link to test content
http://stand.netup.tv/downloads/T1515_SD.ts
http://stand.netup.tv/downloads/T1515_HD.ts
Please wait while the exoplayer starts to play video. The bug is reproduced on both links.

### Version of ExoPlayer being used
2.9.1

### Device(s) and version(s) of Android being used
STB GIEC MP1113 (chip Amlogic s905x), Smartphone Google Nexus 5
Android 6.0.1 (on both devices)

### A full bug report captured from the device

[out.txt](https://github.com/google/ExoPlayer/files/2639808/out.txt) (for T1515_SD.ts) - from STB device
[out2.txt](https://github.com/google/ExoPlayer/files/2639816/out2.txt) (for T1515_HD.ts) - from STB device

**Comment by erdemguven** [comment]
I tried both streams and I got no video or audio. 
```
D: tracksChanged [3.82, 0.00, window=0, period=0, 
D:   Renderer:0 [
D:     Group:0, adaptive_supported=N/A [
D:       [X] Track:0, id=1010/1011, mimeType=video/avc, codecs=avc1.4D401E, res=720x576, supported=YES
D:     ]
D:   ]
D:   Renderer:2 [
D:     Group:0, adaptive_supported=N/A [
D:       [ ] Track:0, id=1010/1012, mimeType=audio/mpeg-L2, channels=2, sample_rate=48000, language=rus, supported=NO_UNSUPPORTED_TYPE
D:     ]
D:   ]
D:   Renderer:6 [
D:     Group:0, adaptive_supported=N/A [
D:       [ ] Track:0, id=1010/9203, mimeType=application/cea-608, supported=YES
D:     ]
D:   ]
D: ]
```
This is from shared log files:
```
tracksChanged [0.46, 0.00, window=0, period=0,
  Renderer:0 [
    Group:0, adaptive_supported=N/A [
      [X] Track:0, id=1010/1011, mimeType=video/avc, avc1.4D401E, res=720x576, supported=YES
    ]
  ]
  Renderer:1 [
    Group:0, adaptive_supported=N/A [
      [X] Track:0, id=1010/1012, mimeType=audio/mpeg-L2, channels=2, sample_rate=48000, language=rus, supported=YES
    ]
  ]
  Renderer:2 [
    Group:0, adaptive_supported=N/A [
      [ ] Track:0, id=1010/9203, mimeType=application/cea-608, supported=YES
    ]
  ]
]
```
@AquilesCanta could you look at this.

**Comment by AquilesCanta** [comment]
Please see our [FAQs](https://google.github.io/ExoPlayer/faqs.html#why-do-some-mpeg-ts-files-fail-to-play).

**Comment by tipoc123** [comment]
Thanks. It's working with FLAG_ALLOW_NON_IDR_KEYFRAMES. 

How can I set this flag also for HLS streams? Is it possible?

**Comment by AquilesCanta** [comment]
Yes, have a look at ExoPlayer V2.9.1's DefaultHlsExtractorFactory's constructors and inject it using the HlsMediaSource.Builder.
