### ISSUE TITLE
Thow ExoPlayer.Listener.onPlayerError event in case HLS is unreachable

### ISSUE THREAD

**Issue by agalera-nice** [google/ExoPlayer#519]
Hi, in case a manifest is not reachable, I think the callback ExoPlayer.Listener.onPlayerError should be called.

In the documentation, it is stated that this callback is only called when some error avoids the video to be played correctly; and I think this is the case.

The internal callbacks are called correctly.

So, step to reproduce this issues:
1) With the original demo, add another source that points to an invalid manifest, in my case:

            new Sample("ERROR!!",
                    "http://www.youtube.com/api/manifest/dash/id/3aa39fa2cc27967f/source/youtuaaabe?"
                            + "as=fmp4_audio_clear,fmp4_sd_hd_clear&sparams=ip,ipbits,expire,source,id,as&ip=0.0.0.0&"
                            + "ipbits=0&expire=19000000000&signature=A2716F75795F5D2AF0E88962FFCD10DB79384F29."
                            + "84308FF04844498CE6FBCE4731507882B8307798&key=ik0", DemoUtil.TYPE_DASH),

This URL will results in a 403 Forbidden HTTP response

2) Try to play that video
3) Internal callbacks can be seen as exceptions in logcat, however ExoPlayer.Listener.onPlayerError is not called

**Comment by ojw28** [comment]
This is working as intended currently. The initial fetching of the manifest is done outside of the player in the demo app, so if it fails then the failure occurs before the player is even prepared. Note that DemoPlayer.onError is invoked, as you would expect.

We may move initial manifest fetching inside of the player in the future, but this is TBC.

**Comment by agalera-nice** [comment]
OK, Thank you so much for your reply. However, how could I detect this error? I'm programming an analytics plugin for this player, and ideally the only object I will have access would be the player.

Doing some experiments, I could see that for each format supported you have to write a piece of software that generate the renders, but, are there any standardized interfaces of the event Listeners for each format? Or any of them has independent listeners?

I was thinking of maybe doing some java reflection techniques I can have acces to some of those listeners.

Any help will be appreciated

**Comment by ojw28** [comment]
You should definitely not be doing anything with reflection. The demo project already demonstrates how to do this. Typically you'd wrap an ExoPlayer in a slightly higher level API (in the demo project this is called DemoPlayer) that will report these events in addition to the ones from the underlying player. You'd then have your analytics code depend on DemoPlayer, rather than directly on ExoPlayer.
