### ISSUE TITLE
issue updating playernotificationmanager

### ISSUE THREAD

**Issue by HighA** [google/ExoPlayer#5190]
### Issue description
I use PlayerNotificationManager to create the notification used to control my exoplayer based app, which plays an online stream. But of course the notification don't update itself when the current title changes, as it is a stream. Using invalidate(), I managed to manually force the update of the current tile in the notification. But I don't understand why, the large icon does not update this way. if I click pause, or if exoplayer enters buffering state, then it updates perfectly, but not when using the invalidate() method, although the title and artist update normally.

### Reproduction steps
I don't really know how you can reproduce it, so here's the code for my notification :

```
public class NotificationService extends Service
 {

    static PlayerNotificationManager playerNotificationManager;
    static Bitmap notification_artwork;

    @Override
    public void onCreate() {
        super.onCreate();
        final Context context = this;

        playerNotificationManager = PlayerNotificationManager.createWithNotificationChannel(
                context, PLAYBACK_CHANNEL_ID, R.string.playback_channel_name, PLAYBACK_NOTIFICATION_ID,
                new PlayerNotificationManager.MediaDescriptionAdapter(){
                    @Override
                    public String getCurrentContentTitle(Player player) {
                        return notification_artist;
                    }

                    @Nullable
                    @Override
                    public PendingIntent createCurrentContentIntent(Player player) {
                         return;
                    }

                    @Nullable
                    @Override
                    public String getCurrentContentText(Player player) {
                        return notification_title;
                    }

                    @Nullable
                    @Override
                    public Bitmap getCurrentLargeIcon(Player player, PlayerNotificationManager.BitmapCallback callback)
                    {
                        Uri uri = Uri.parse(cover_url);
                        try {
                            notification_artwork = Glide.with(getApplicationContext())
                                    .asBitmap()
                                    .load(uri)
                                    .submit(1000,1000).get();
                        } catch (Throwable t) {
                            if (t instanceof ExecutionException) {
                                t = t.getCause();                          
                            }
                        }
                        return notification_artwork;
                    }
                }
        );

        playerNotificationManager.setVisibility(VISIBILITY_PUBLIC);
        playerNotificationManager.setUseNavigationActions(false);
        playerNotificationManager.setFastForwardIncrementMs(0);
        playerNotificationManager.setRewindIncrementMs(0);
        playerNotificationManager.setStopAction(null);        
        playerNotificationManager.setUseChronometer(false);
        playerNotificationManager.setSmallIcon(R.drawable.notification_icon);
        playerNotificationManager.setBadgeIconType(BADGE_ICON_NONE);
        playerNotificationManager.setPriority(NotificationCompat.PRIORITY_LOW);       
        playerNotificationManager.setNotificationListener(new PlayerNotificationManager.NotificationListener()
        {
            @Override
            public void onNotificationStarted(int notificationId, Notification notification) {
                startForeground(notificationId,notification);
            }

            @Override
            public void onNotificationCancelled(int notificationId) {
                stopSelf();
            }
        });
        playerNotificationManager.setPlayer(MediaPlayerService.player);
```

### Link to test content
https://youtu.be/QVHBIrfDEtE
on this video you can see that the invalidate() method called on current song change works perfectly for the artist & title on the notification, but not on the large icon artwork which needs to pause/start or any other player state change to get updated successfully

### Version of ExoPlayer being used
ExoPlayer 2.9.0

### Device(s) and version(s) of Android being used
between API Versions 21-27, tested on android studio emulator and Huawei P8 Lite

### A full bug report captured from the device
I will provide a bug report as soon as possible

**Comment by marcbaechinger** [comment]
I think that when you are using the bitmap with glide this happens asynchronously. So you need to use the PlayerNotificationManager.BitmapCallback when the async method returns and pass the large icon to it. 

With the current code you return the notification_artwork before it has been updated by the async code.

**Comment by HighA** [comment]
Sorry I didn't see your answer thanks a lot for helping I'll try this out

Edit : for the record and whoever this might help the problem wasn't coming from notificationPlayerUpdate or the BitmapCallback, but Glide which acts strangely with asBitmap, I don't really understand why but I just did it a simplier way using : (BitmapDrawable)imageView.getDrawable()).getBitmap(); 
since the image I need to convert into bitmap and use in my notification is already used in an ImageView.

Guess I just made a simple thing complicated but I'm a beginner and self learning so I do dumb things...

**Comment by makazemi** [comment]
> I think that when you are using the bitmap with glide this happens asynchronously. So you need to use the PlayerNotificationManager.BitmapCallback when the async method returns and pass the large icon to it.
> 
> With the current code you return the notification_artwork before it has been updated by the async code.

If is it possible please put an example code. I don't know how to use PlayerNotificationManager.BitmapCallback?

**Comment by sc231997** [comment]
@makazemi you can use the following example :

```
public Bitmap getCurrentLargeIcon(Player player, PlayerNotificationManager.BitmapCallback callback) {

    Thread thread = new Thread(() -> {
        try {
            Uri uri = Uri.parse(cover_url);
            Bitmap bitmap = Glide.with(context)
                    .asBitmap()
                    .load(uri)
                    .submit().get();
            callback.onBitmap(bitmap);
        } catch (ExecutionException e) {
            e.printStackTrace();
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    });
    thread.start();

    return null;
}
```
