### ISSUE TITLE
Play EVENT playlist from the beggining

### ISSUE THREAD

**Issue by tipoc123** [google/ExoPlayer#5194]
How can I play HLS EVENT playlist from the beginning (not third chunk from the end)? What class should I modify?

**Comment by AquilesCanta** [comment]
The easiest way would be to include a [EXT-X-START](https://tools.ietf.org/html/rfc8216#section-4.3.5.2) tag server-side. Otherwise, you might want to inject a custom parser or playlist tracker that does this for you client-side.

**Comment by tipoc123** [comment]
Yes, EXT-X-START is a good feature. It has helped us.
