### ISSUE TITLE
Audio only rtsp , use branch ExoPlayer-dev-v2-rtsp

### ISSUE THREAD

**Issue by zettyfactory** [google/ExoPlayer#5196]
I am testing rtps with the demonstration app of ExoPlayer-dev-v2-rtsp branch
All of the URLs in the demo will work fine.
Ex) rtsp: //213.58.156.180/live/ch00_0

However, the url I added is not executed.
ex) rtsp://115.68.15.116/efm,  
rtsp://live.febc.or.kr/LiveFm

One thing in common is the radio with audio data only.
In other apps, everything is a well-executed url.

What is the problem? I need help.

**Comment by erdemguven** [comment]
RTSP is not officially supported. Adding support is tracked by #55

**Comment by portizb** [comment]
> I am testing rtps with the demonstration app of ExoPlayer-dev-v2-rtsp branch
> All of the URLs in the demo will work fine.
> Ex) rtsp: //213.58.156.180/live/ch00_0
> 
> However, the url I added is not executed.
> ex) rtsp://115.68.15.116/efm,
> rtsp://live.febc.or.kr/LiveFm
> 
> One thing in common is the radio with audio data only.
> In other apps, everything is a well-executed url.
> 
> What is the problem? I need help.

@zettyfactory The RTSP dev branch only support G.711, AAC and AC3 audio codecs (over RTP). You are trying playback urls which contains audio track with WMA2 (Windows Media Audio). Sorry but that audio codec is not supported.
