### ISSUE TITLE
Ts format can't get duration and the audio track is not supported.

### ISSUE THREAD

**Issue by Romantic-LiXuefeng** [google/ExoPlayer#5198]
This is reproducible with this 
 uri : http://video.a045.ottcn.com/ftp_upload/data/video/hdhbzsj100300409.ts

**Comment by erdemguven** [comment]
Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

**Comment by Romantic-LiXuefeng** [comment]
@erdemguven  Thanks!
I used the release-v2 branch. The issue is as described by the title.  which can reproducible with this uri : http://video.a045.ottcn.com/ftp_upload/data/video/hdhbzsj100300409.ts.

> 

Now I use the extension FFmpeg audio decoder, we can play the audio . but I still can't duration  even I increase the `TsDurationReader.DURATION_READ_PACKETS` as described in 
Support seeking for a wider range of MPEG-TS streams (#5097).

**Comment by erdemguven** [comment]
@AquilesCanta please look at this.

**Comment by erdemguven** [comment]
I can repeat the issue on latest development branch.

**Comment by ojw28** [comment]
@AquilesCanta - For the duration part, this is probably a duplicate of https://github.com/google/ExoPlayer/issues/5097. It can likely be worked around by making the `TIMESTAMP_SEARCH_BYTES` constant in `TsDurationReader` even larger. Although to what extent that's a good idea I'm not sure...

**Comment by ojw28** [comment]
Marking as a duplicate of #5097.
