### ISSUE TITLE
Implement DASH Live support

### ISSUE THREAD

**Issue by TobbeMobiTV** [google/ExoPlayer#52]
I've made a test live source for DASH-IF that is available at  http://54.201.151.65/livesim/testpic_2s/Manifest.mpd.

The DASH-IF reference player dash.js can run this content for IE11 on Windows 8.1 and in Chrome 38.0.2 and later.

Some more information is available at http://54.201.151.65/dashifserver.html
Since this is a synthetic live source it is very stable and reliable.

It would be great if you can use this content as a test source as the live support is being further developed. If you have any questions or suggestions, don't hesitate to contact me.

**Comment by AlexVanWolf** [comment]
I wanted to test DASH live support of ExoPlayer and tried with the MPD from DASH-IF suggested in this thread (http://54.201.151.65/livesim/testpic_2s/Manifest.mpd) but receive the error message - Playback failed. The MPD worked with my desktop client.

Are there any flags which one has to set? Or is there a working live example available?

**Comment by ojw28** [comment]
That URL works fine on the dev branch for me. Please try the dev branch, if you aren't already doing so. Did you add it to the ExoPlayer demo app? If so, how exactly?

**Comment by AlexVanWolf** [comment]
Thank you for the hint, works fine using the dev branch.
