### ISSUE TITLE
How to set full screen in Exoplayer

### ISSUE THREAD

**Issue by kinhdang** [google/ExoPlayer#520]
Dear all  !
In Exoplayer Lib, how to set full screen when play hls file.

Thanks.

**Comment by bsysop** [comment]
Hi dude, that not ExoPlayer condition, but Android condition...

Do that in OnCreate:
this.requestWindowFeature(Window.FEATURE_NO_TITLE); //Remove title bar
    this.getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN, WindowManager.LayoutParams.FLAG_FULLSCREEN); //Remove notification bar

**Comment by bsysop** [comment]
If this enough for you, please close this "issue"!

**Comment by kinhdang** [comment]
Thanks bsysop, we will checki'm trying ....

**Comment by bsysop** [comment]
No problem, something else, just write here.

**Comment by kinhdang** [comment]
wonderful 
![tongue](https://cloud.githubusercontent.com/assets/9839084/7989217/3e6e5414-0b12-11e5-96cc-e91c6f8a3770.gif)

**Comment by kinhdang** [comment]
Hi all !

How to set media stream full screen,  play hls with exoplayer.

Thanks.
