### ISSUE TITLE
Replace Apple HLS/TS/AAC test streams in demo app 

### ISSUE THREAD

**Issue by ojw28** [google/ExoPlayer#5202]
Apple seem to have a certificate issue (see https://github.com/google/ExoPlayer/issues/5103#issuecomment-440322017). More generally, it would be good to host samples ourselves, so that we can fix them if there's a server-side problem.

We should generate some equivalent HLS/TS/AAC test streams based on Big Buck Bunny or similar, and use these to replace the Apple ones. Does anyone want to volunteer to help generate the content? We're happy to host it, once it's generated!

**Comment by giladna** [comment]
@ojw28 

We can provide folder with downloaded content + the  relative m3u8


does it work for you?

Gilad.

**Comment by noamtamim** [comment]
@ojw28 in addition to the content generated by Kaltura that @giladna will provide, do you know if Apple's test streams are copyrighted? Maybe we can just download the entire sample and host it on Google.

**Comment by giladna** [comment]
@ojw28 
is it still relevant?

**Comment by ojw28** [comment]
Yes

**Comment by giladna** [comment]
@ojw28 
Sharing with you link to drive containing the chunks and the manifest
if any issues with server upload and playback we can share link to our servers

**Comment by ojw28** [comment]
Where did you send the link? I didn't receive one. Thanks.

**Comment by giladna** [comment]
@ojw28  shared it to you via google drive

**Comment by ojw28** [comment]
I cannot see this anywhere (either in drive directly, or in email saying that something was shared). What email address are you sharing to? In any case, please double check it's shared with `dev.exoplayer@gmail.com`, and perhaps also send an email to that address with a link to the drive folder. Thanks!

**Comment by giladna** [comment]
done

**Comment by Tomyancnus** [comment]
hi Giladna, @giladna 
Could you also share the link to me ?

**Comment by Tomyancnus** [comment]
@ojw28  Could you estimate when this issue #5202 be solved ?

**Comment by ojw28** [comment]
Sorry, we haven't found time to do this yet. Note that it's not actually a library issue. It's only an issue with Apple's test streams (and replacing the links in the demo app with content we're hosting ourselves). Hence the issue still being open should not be blocking you from doing anything related to your own application.

**Comment by ojw28** [comment]
Sorry we didn't ever follow through on this. Apple appears to have fixed their test streams at some point, which removed any sense of urgency. I'm going to go ahead and duplicate this to https://github.com/google/ExoPlayer/issues/7265, which tracks the more general goal of hosting all of our demo app sample content in a single place.
