### ISSUE TITLE
onRenderedFirstFrame not called after ad track change

### ISSUE THREAD

**Issue by MongeziNombewu** [google/ExoPlayer#5206]
### Issue description
When playing an ad (IMA), the **onTracksChanged()** from Player.EventListener and **onRenderedFirstFrame()** from VideoListener are called at the start of the ad. This behaviour is expected as it's a new period, but for some reason when the ad runs it's course and the following video content is started, only **onTracksChanged()** is called and not **onRenderedFirstFrame()**. The expected behaviour seems to occur when playing a skippable ad,  and clicking on the "_Skip Ad_" button, then the next video content recieved the expected callbacks for onTracksChanged() and onRenderedFirstFrame()

### Reproduction steps
The issue can be replicated by using the sample app, and playing the IMA skippable inline ad.
Case 1:
1. Play the video ad and let the ad run to completion
2. Check that the onRenderedFirstFrame() of the attached VideoListener is called when the next video content plays
3. You will notice onRenderedFirstFrame() is not called

Case 2:
1. Play the video ad and press "Skip Ad" button when available
2. Check that the onRenderedFirstFrame() of the attached VideoListener is called when the next video content plays
3. You will notice onRenderedFirstFrame() is called as expected

### Link to test content
Sample App, with VideoListener
https://drive.google.com/open?id=1Km0VU6EUaQEpYUCjHzqz57JffSiNuUdF

### Version of ExoPlayer being used
Tested on versions 2.8.4 and 2.9.0

### Device(s) and version(s) of Android being used
Samsung SM-P555,  Android 7.1.1
Stylo S61 JAZZ, Android 7.0

**Comment by erdemguven** [comment]
onRenderedFirstFrame is called when a frame is rendered for the first time since setting the surface, and when a frame is rendered for the first time since the renderer was reset. A renderer reset can occur for various reasons like resolution change or video skipped. So if when ad is skipped onRenderedFirstFrame is called but if switching between ad and following video doesn't require renderer reset then it isn't called.
