### ISSUE TITLE
checker-compat-qual

### ISSUE THREAD

**Issue by tipoc123** [google/ExoPlayer#5208]
Where can I download checker-compat-qual's sources? My project doesn't compile because of it.

I'm using exoplayer from source (not from gradle). We cannot use gradle.

checker-framework-2.5.8 contains checker-qual, no checker-compat-qual.

**Comment by tipoc123** [comment]
For example, TrackSelectorResult uses:
```
import org.checkerframework.checker.nullness.compatqual.NullableType;
```

**Comment by tipoc123** [comment]
I've downloaded https://checkerframework.org/checker-framework-2.5.8.zip

**Comment by erdemguven** [comment]
Have you followed the steps in https://google.github.io/ExoPlayer/guide.html#getting-started? Dependency should be resolved automatically.

**Comment by tipoc123** [comment]
> I'm using exoplayer from source (not from gradle)

**Comment by ojw28** [comment]
https://github.com/google/ExoPlayer/issues/5208#issuecomment-444901191 suggests this is resolved. Although regardless, this is not an ExoPlayer issue.
