### ISSUE TITLE
MPEG Audio layer1/2(mpga)

### ISSUE THREAD

**Issue by zhangabvc** [google/ExoPlayer#5212]
If Exoplayer add  ffmpeg-extension , Whether to support this format （MPEG Audio layer1/2(mpga)）

![11111111111111111](https://user-images.githubusercontent.com/44994911/49632452-b2cdb500-fa30-11e8-8ba1-0397bbd00d4f.jpg)

**Comment by andrewlewis** [comment]
Duplicate of #5204
