### ISSUE TITLE
Playing Some HLS Playback failed.

### ISSUE THREAD

**Issue by JiannaiJ** [google/ExoPlayer#5214]
### Issue description
Some HLS video plays normally, while some HLS video cannot play. Video is processed by FFMPEG, and the computer verifies that the play is normal. VideoView and IJKPLAYER can play normally, but Exo cannot play. HLS source video is AVC + aac-lc + 2 Menu.

### Reproduction steps
Use Demo App to add an HLS video url.

### Link to test content
NONE

### Version of ExoPlayer being used
Version r2.9.2 (use demo app)

### Device(s) and version(s) of Android being used
Android 5.1 (Android TV  amlogic)

### A full bug report captured from the device
12-07 16:02:53.577 6169-6169/? I/art: Late-enabling -Xcheck:jni
12-07 16:02:53.601 6169-6179/? E/art: Failed sending reply to debugger: Broken pipe
12-07 16:02:53.602 6169-6179/? I/art: Debugger is no longer active
12-07 16:02:53.667 6169-6169/? W/ContextImpl: Failed to ensure directory: /storage/sdcard1/Android/data/com.google.android.exoplayer2.demo/files
12-07 16:02:53.784 6169-6169/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.exoplayer2.video.MediaCodecVideoRenderer$OnFrameRenderedListenerV23>
12-07 16:02:53.785 6169-6169/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.exoplayer2.video.MediaCodecVideoRenderer$OnFrameRenderedListenerV23>
12-07 16:02:53.796 6169-6169/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.exoplayer2.video.MediaCodecVideoRenderer$OnFrameRenderedListenerV23>
12-07 16:02:53.800 6169-6169/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.exoplayer2.video.MediaCodecVideoRenderer$OnFrameRenderedListenerV23>
12-07 16:02:53.800 6169-6169/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.exoplayer2.video.MediaCodecVideoRenderer$OnFrameRenderedListenerV23>
12-07 16:02:53.819 6169-6169/? I/ExoPlayerImpl: Init 20a2c6ad [ExoPlayerLib/2.9.1] [p321, Ainetv-2017s, amlogic, 22]
12-07 16:02:53.849 6169-6169/? D/EventLogger: state [0.01, 0.00, window=0, true, BUFFERING]
12-07 16:02:53.857 6169-6194/? D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: false
12-07 16:02:53.866 6169-6169/? D/Atlas: Validating map...
12-07 16:02:53.909 6169-6194/? I/OpenGLRenderer: Initialized EGL, version 1.4
12-07 16:02:53.911 6169-6194/? D/OpenGLRenderer: Enabling debug mode 0
12-07 16:02:53.925 6169-6169/? D/EventLogger: surfaceSizeChanged [0.09, 0.00, window=0, 1920, 1080]
12-07 16:02:53.999 6169-6169/? D/EventLogger: timelineChanged [0.16, 0.00, window=0, periodCount=1, windowCount=1, reason=PREPARED
12-07 16:02:53.999 6169-6169/? D/EventLogger:   period [8861.98]
12-07 16:02:53.999 6169-6169/? D/EventLogger:   window [8861.98, true, false]
12-07 16:02:53.999 6169-6169/? D/EventLogger: ]
12-07 16:02:54.009 6169-6169/? D/EventLogger: mediaPeriodCreated [0.17, 0.00, window=0, period=0]
12-07 16:02:54.015 6169-6169/? D/EventLogger: loading [0.18, 0.00, window=0, period=0, true]
12-07 16:02:54.085 6169-6190/? I/VideoCapabilities: Unsupported profile 2 for video/mp4v-es
12-07 16:02:54.085 6169-6190/? I/VideoCapabilities: Unsupported profile 2 for video/mp4v-es
12-07 16:02:54.085 6169-6190/? I/VideoCapabilities: Unsupported profile 2 for video/mp4v-es
12-07 16:02:54.085 6169-6190/? I/VideoCapabilities: Unsupported profile 2 for video/mp4v-es
12-07 16:02:54.085 6169-6190/? I/VideoCapabilities: Unsupported profile 2 for video/mp4v-es
12-07 16:02:54.085 6169-6190/? I/VideoCapabilities: Unsupported profile 2 for video/mp4v-es
12-07 16:02:54.085 6169-6190/? I/VideoCapabilities: Unsupported profile 2 for video/mp4v-es
12-07 16:02:54.085 6169-6190/? I/VideoCapabilities: Unsupported profile 2 for video/mp4v-es
12-07 16:02:54.085 6169-6190/? I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
12-07 16:02:54.085 6169-6190/? I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
12-07 16:02:54.085 6169-6190/? I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
12-07 16:02:54.085 6169-6190/? I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
12-07 16:02:54.085 6169-6190/? I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
12-07 16:02:54.085 6169-6190/? I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
12-07 16:02:54.085 6169-6190/? I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
12-07 16:02:54.085 6169-6190/? I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
12-07 16:02:54.085 6169-6190/? I/VideoCapabilities: Unsupported profile 8 for video/mp4v-es
12-07 16:02:54.085 6169-6190/? I/VideoCapabilities: Unsupported profile 8 for video/mp4v-es
12-07 16:02:54.085 6169-6190/? I/VideoCapabilities: Unsupported profile 8 for video/mp4v-es
12-07 16:02:54.085 6169-6190/? I/VideoCapabilities: Unsupported profile 8 for video/mp4v-es
12-07 16:02:54.085 6169-6190/? I/VideoCapabilities: Unsupported profile 8 for video/mp4v-es
12-07 16:02:54.085 6169-6190/? I/VideoCapabilities: Unsupported profile 8 for video/mp4v-es
12-07 16:02:54.085 6169-6190/? I/VideoCapabilities: Unsupported profile 8 for video/mp4v-es
12-07 16:02:54.085 6169-6190/? I/VideoCapabilities: Unsupported profile 8 for video/mp4v-es
12-07 16:02:54.085 6169-6190/? I/VideoCapabilities: Unsupported profile 16 for video/mp4v-es
12-07 16:02:54.085 6169-6190/? I/VideoCapabilities: Unsupported profile 16 for video/mp4v-es
12-07 16:02:54.085 6169-6190/? I/VideoCapabilities: Unsupported profile 16 for video/mp4v-es
12-07 16:02:54.085 6169-6190/? I/VideoCapabilities: Unsupported profile 16 for video/mp4v-es
12-07 16:02:54.085 6169-6190/? I/VideoCapabilities: Unsupported profile 16 for video/mp4v-es
12-07 16:02:54.085 6169-6190/? I/VideoCapabilities: Unsupported profile 16 for video/mp4v-es
12-07 16:02:54.085 6169-6190/? I/VideoCapabilities: Unsupported profile 16 for video/mp4v-es
12-07 16:02:54.085 6169-6190/? I/VideoCapabilities: Unsupported profile 16 for video/mp4v-es
12-07 16:02:54.085 6169-6190/? I/VideoCapabilities: Unsupported profile 32 for video/mp4v-es
12-07 16:02:54.085 6169-6190/? I/VideoCapabilities: Unsupported profile 32 for video/mp4v-es
12-07 16:02:54.085 6169-6190/? I/VideoCapabilities: Unsupported profile 32 for video/mp4v-es
12-07 16:02:54.085 6169-6190/? I/VideoCapabilities: Unsupported profile 32 for video/mp4v-es
12-07 16:02:54.085 6169-6190/? I/VideoCapabilities: Unsupported profile 32 for video/mp4v-es
12-07 16:02:54.085 6169-6190/? I/VideoCapabilities: Unsupported profile 32 for video/mp4v-es
12-07 16:02:54.085 6169-6190/? I/VideoCapabilities: Unsupported profile 32 for video/mp4v-es
12-07 16:02:54.085 6169-6190/? I/VideoCapabilities: Unsupported profile 32 for video/mp4v-es
12-07 16:02:54.085 6169-6190/? I/VideoCapabilities: Unsupported profile 64 for video/mp4v-es
12-07 16:02:54.085 6169-6190/? I/VideoCapabilities: Unsupported profile 64 for video/mp4v-es
12-07 16:02:54.085 6169-6190/? I/VideoCapabilities: Unsupported profile 64 for video/mp4v-es
12-07 16:02:54.085 6169-6190/? I/VideoCapabilities: Unsupported profile 64 for video/mp4v-es
12-07 16:02:54.085 6169-6190/? I/VideoCapabilities: Unsupported profile 64 for video/mp4v-es
12-07 16:02:54.086 6169-6190/? I/VideoCapabilities: Unsupported profile 64 for video/mp4v-es
12-07 16:02:54.086 6169-6190/? I/VideoCapabilities: Unsupported profile 64 for video/mp4v-es
12-07 16:02:54.086 6169-6190/? I/VideoCapabilities: Unsupported profile 64 for video/mp4v-es
12-07 16:02:54.086 6169-6190/? I/VideoCapabilities: Unsupported profile 128 for video/mp4v-es
12-07 16:02:54.086 6169-6190/? I/VideoCapabilities: Unsupported profile 128 for video/mp4v-es
12-07 16:02:54.086 6169-6190/? I/VideoCapabilities: Unsupported profile 128 for video/mp4v-es
12-07 16:02:54.086 6169-6190/? I/VideoCapabilities: Unsupported profile 128 for video/mp4v-es
12-07 16:02:54.086 6169-6190/? I/VideoCapabilities: Unsupported profile 128 for video/mp4v-es
12-07 16:02:54.086 6169-6190/? I/VideoCapabilities: Unsupported profile 128 for video/mp4v-es
12-07 16:02:54.086 6169-6190/? I/VideoCapabilities: Unsupported profile 128 for video/mp4v-es
12-07 16:02:54.086 6169-6190/? I/VideoCapabilities: Unsupported profile 128 for video/mp4v-es
12-07 16:02:54.086 6169-6190/? I/VideoCapabilities: Unsupported profile 256 for video/mp4v-es
12-07 16:02:54.086 6169-6190/? I/VideoCapabilities: Unsupported profile 256 for video/mp4v-es
12-07 16:02:54.086 6169-6190/? I/VideoCapabilities: Unsupported profile 256 for video/mp4v-es
12-07 16:02:54.086 6169-6190/? I/VideoCapabilities: Unsupported profile 256 for video/mp4v-es
12-07 16:02:54.086 6169-6190/? I/VideoCapabilities: Unsupported profile 256 for video/mp4v-es
12-07 16:02:54.086 6169-6190/? I/VideoCapabilities: Unsupported profile 256 for video/mp4v-es
12-07 16:02:54.086 6169-6190/? I/VideoCapabilities: Unsupported profile 256 for video/mp4v-es
12-07 16:02:54.086 6169-6190/? I/VideoCapabilities: Unsupported profile 256 for video/mp4v-es
12-07 16:02:54.086 6169-6190/? I/VideoCapabilities: Unsupported profile 512 for video/mp4v-es
12-07 16:02:54.086 6169-6190/? I/VideoCapabilities: Unsupported profile 512 for video/mp4v-es
12-07 16:02:54.086 6169-6190/? I/VideoCapabilities: Unsupported profile 512 for video/mp4v-es
12-07 16:02:54.086 6169-6190/? I/VideoCapabilities: Unsupported profile 512 for video/mp4v-es
12-07 16:02:54.086 6169-6190/? I/VideoCapabilities: Unsupported profile 512 for video/mp4v-es
12-07 16:02:54.086 6169-6190/? I/VideoCapabilities: Unsupported profile 512 for video/mp4v-es
12-07 16:02:54.086 6169-6190/? I/VideoCapabilities: Unsupported profile 512 for video/mp4v-es
12-07 16:02:54.086 6169-6190/? I/VideoCapabilities: Unsupported profile 512 for video/mp4v-es
12-07 16:02:54.086 6169-6190/? I/VideoCapabilities: Unsupported profile 1024 for video/mp4v-es
12-07 16:02:54.086 6169-6190/? I/VideoCapabilities: Unsupported profile 1024 for video/mp4v-es
12-07 16:02:54.086 6169-6190/? I/VideoCapabilities: Unsupported profile 1024 for video/mp4v-es
12-07 16:02:54.086 6169-6190/? I/VideoCapabilities: Unsupported profile 1024 for video/mp4v-es
12-07 16:02:54.086 6169-6190/? I/VideoCapabilities: Unsupported profile 1024 for video/mp4v-es
12-07 16:02:54.086 6169-6190/? I/VideoCapabilities: Unsupported profile 1024 for video/mp4v-es
12-07 16:02:54.086 6169-6190/? I/VideoCapabilities: Unsupported profile 1024 for video/mp4v-es
12-07 16:02:54.086 6169-6190/? I/VideoCapabilities: Unsupported profile 1024 for video/mp4v-es
12-07 16:02:54.086 6169-6190/? I/VideoCapabilities: Unsupported profile 2048 for video/mp4v-es
12-07 16:02:54.086 6169-6190/? I/VideoCapabilities: Unsupported profile 2048 for video/mp4v-es
12-07 16:02:54.086 6169-6190/? I/VideoCapabilities: Unsupported profile 2048 for video/mp4v-es
12-07 16:02:54.086 6169-6190/? I/VideoCapabilities: Unsupported profile 2048 for video/mp4v-es
12-07 16:02:54.086 6169-6190/? I/VideoCapabilities: Unsupported profile 2048 for video/mp4v-es
12-07 16:02:54.086 6169-6190/? I/VideoCapabilities: Unsupported profile 2048 for video/mp4v-es
12-07 16:02:54.086 6169-6190/? I/VideoCapabilities: Unsupported profile 2048 for video/mp4v-es
12-07 16:02:54.086 6169-6190/? I/VideoCapabilities: Unsupported profile 2048 for video/mp4v-es
12-07 16:02:54.086 6169-6190/? I/VideoCapabilities: Unsupported profile 4096 for video/mp4v-es
12-07 16:02:54.086 6169-6190/? I/VideoCapabilities: Unsupported profile 4096 for video/mp4v-es
12-07 16:02:54.086 6169-6190/? I/VideoCapabilities: Unsupported profile 4096 for video/mp4v-es
12-07 16:02:54.086 6169-6190/? I/VideoCapabilities: Unsupported profile 4096 for video/mp4v-es
12-07 16:02:54.086 6169-6190/? I/VideoCapabilities: Unsupported profile 4096 for video/mp4v-es
12-07 16:02:54.086 6169-6190/? I/VideoCapabilities: Unsupported profile 4096 for video/mp4v-es
12-07 16:02:54.086 6169-6190/? I/VideoCapabilities: Unsupported profile 4096 for video/mp4v-es
12-07 16:02:54.086 6169-6190/? I/VideoCapabilities: Unsupported profile 4096 for video/mp4v-es
12-07 16:02:54.087 6169-6190/? I/VideoCapabilities: Unsupported profile 8192 for video/mp4v-es
12-07 16:02:54.087 6169-6190/? I/VideoCapabilities: Unsupported profile 8192 for video/mp4v-es
12-07 16:02:54.087 6169-6190/? I/VideoCapabilities: Unsupported profile 8192 for video/mp4v-es
12-07 16:02:54.087 6169-6190/? I/VideoCapabilities: Unsupported profile 8192 for video/mp4v-es
12-07 16:02:54.087 6169-6190/? I/VideoCapabilities: Unsupported profile 8192 for video/mp4v-es
12-07 16:02:54.087 6169-6190/? I/VideoCapabilities: Unsupported profile 8192 for video/mp4v-es
12-07 16:02:54.087 6169-6190/? I/VideoCapabilities: Unsupported profile 8192 for video/mp4v-es
12-07 16:02:54.087 6169-6190/? I/VideoCapabilities: Unsupported profile 8192 for video/mp4v-es
12-07 16:02:54.087 6169-6190/? I/VideoCapabilities: Unsupported profile 16384 for video/mp4v-es
12-07 16:02:54.087 6169-6190/? I/VideoCapabilities: Unsupported profile 16384 for video/mp4v-es
12-07 16:02:54.087 6169-6190/? I/VideoCapabilities: Unsupported profile 16384 for video/mp4v-es
12-07 16:02:54.087 6169-6190/? I/VideoCapabilities: Unsupported profile 16384 for video/mp4v-es
12-07 16:02:54.087 6169-6190/? I/VideoCapabilities: Unsupported profile 16384 for video/mp4v-es
12-07 16:02:54.087 6169-6190/? I/VideoCapabilities: Unsupported profile 16384 for video/mp4v-es
12-07 16:02:54.087 6169-6190/? I/VideoCapabilities: Unsupported profile 16384 for video/mp4v-es
12-07 16:02:54.087 6169-6190/? I/VideoCapabilities: Unsupported profile 16384 for video/mp4v-es
12-07 16:02:54.087 6169-6190/? W/VideoCapabilities: Unrecognized profile/level 32768/2 for video/mp4v-es
12-07 16:02:54.097 6169-6190/? W/VideoCapabilities: Unsupported mime video/mpeg2
12-07 16:02:54.101 6169-6190/? W/VideoCapabilities: Unsupported mime video/vc1
12-07 16:02:54.101 6169-6190/? W/Utils: could not parse long range '1-'
12-07 16:02:54.105 6169-6190/? W/VideoCapabilities: Unsupported mime video/wvc1
12-07 16:02:54.105 6169-6190/? W/Utils: could not parse long range '1-'
12-07 16:02:54.108 6169-6190/? W/VideoCapabilities: Unsupported mime video/wmv3
12-07 16:02:54.111 6169-6190/? W/VideoCapabilities: Unsupported mime video/mjpeg
12-07 16:02:54.121 6169-6190/? W/AudioCapabilities: Unsupported mime audio/aac-adif
12-07 16:02:54.123 6169-6190/? W/AudioCapabilities: Unsupported mime audio/aac-latm
12-07 16:02:54.125 6169-6190/? W/AudioCapabilities: Unsupported mime audio/adts
12-07 16:02:54.130 6169-6190/? W/AudioCapabilities: Unsupported mime audio/adpcm-ima
12-07 16:02:54.131 6169-6190/? W/AudioCapabilities: Unsupported mime audio/adpcm-ms
12-07 16:02:54.135 6169-6190/? W/AudioCapabilities: Unsupported mime audio/alac
12-07 16:02:54.136 6169-6190/? W/AudioCapabilities: Unsupported mime audio/wma
12-07 16:02:54.140 6169-6190/? W/AudioCapabilities: Unsupported mime audio/wmapro
12-07 16:02:54.141 6169-6190/? W/AudioCapabilities: Unsupported mime audio/ape
12-07 16:02:54.143 6169-6190/? W/AudioCapabilities: Unsupported mime audio/truehd
12-07 16:02:54.144 6169-6190/? W/AudioCapabilities: Unsupported mime audio/ffmpeg
12-07 16:02:54.156 6169-6190/? W/VideoCapabilities: Unrecognized level 16 for video/x-vnd.on2.vp8
12-07 16:02:54.156 6169-6190/? W/VideoCapabilities: Unrecognized level 32 for video/x-vnd.on2.vp8
12-07 16:02:54.156 6169-6190/? W/VideoCapabilities: Unrecognized level 64 for video/x-vnd.on2.vp8
12-07 16:02:54.156 6169-6190/? W/VideoCapabilities: Unrecognized level 128 for video/x-vnd.on2.vp8
12-07 16:02:54.156 6169-6190/? W/VideoCapabilities: Unrecognized level 256 for video/x-vnd.on2.vp8
12-07 16:02:54.156 6169-6190/? W/VideoCapabilities: Unrecognized level 512 for video/x-vnd.on2.vp8
12-07 16:02:54.156 6169-6190/? W/VideoCapabilities: Unrecognized level 1024 for video/x-vnd.on2.vp8
12-07 16:02:54.156 6169-6190/? W/VideoCapabilities: Unrecognized level 2048 for video/x-vnd.on2.vp8
12-07 16:02:54.156 6169-6190/? W/VideoCapabilities: Unrecognized level 4096 for video/x-vnd.on2.vp8
12-07 16:02:54.156 6169-6190/? W/VideoCapabilities: Unrecognized level 8192 for video/x-vnd.on2.vp8
12-07 16:02:54.156 6169-6190/? W/VideoCapabilities: Unrecognized level 16384 for video/x-vnd.on2.vp8
12-07 16:02:54.156 6169-6190/? W/VideoCapabilities: Unrecognized level 32768 for video/x-vnd.on2.vp8
12-07 16:02:54.162 6169-6190/? W/VideoCapabilities: Unsupported mime video/x-vnd.on2.vp6
12-07 16:02:54.165 6169-6190/? W/VideoCapabilities: Unsupported mime video/x-vnd.on2.vp6a
12-07 16:02:54.167 6169-6190/? W/VideoCapabilities: Unsupported mime video/x-vnd.on2.vp6f
12-07 16:02:54.170 6169-6190/? W/VideoCapabilities: Unsupported mime video/rm10
12-07 16:02:54.174 6169-6190/? W/VideoCapabilities: Unsupported mime video/rm20
12-07 16:02:54.177 6169-6190/? W/VideoCapabilities: Unsupported mime video/rm40
12-07 16:02:54.179 6169-6190/? W/VideoCapabilities: Unsupported mime video/wmv2
12-07 16:02:54.182 6169-6190/? W/VideoCapabilities: Unsupported mime video/wmv1
12-07 16:02:54.185 6169-6190/? W/AudioCapabilities: Unsupported mime audio/ac3
12-07 16:02:54.186 6169-6190/? W/AudioCapabilities: Unsupported mime audio/eac3
12-07 16:02:54.190 6169-6190/? W/AudioCapabilities: Unsupported mime audio/mpeg-L2
12-07 16:02:54.194 6169-6190/? W/AudioCapabilities: Unsupported mime audio/dtshd
12-07 16:02:54.202 6169-6190/? I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
12-07 16:02:54.225 6169-6169/? D/EventLogger: decoderEnabled [0.39, 0.00, window=0, period=0, video]
12-07 16:02:54.227 6169-6169/? D/EventLogger: decoderEnabled [0.39, 0.00, window=0, period=0, audio]
12-07 16:02:54.228 6169-6169/? D/EventLogger: tracksChanged [0.39, 0.00, window=0, period=0, 
12-07 16:02:54.228 6169-6169/? D/EventLogger:   Renderer:0 [
12-07 16:02:54.228 6169-6169/? D/EventLogger:     Group:0, adaptive_supported=N/A [
12-07 16:02:54.229 6169-6169/? D/EventLogger:       [X] Track:0, id=0, mimeType=video/avc, codecs=avc1.640028, res=1920x1012, supported=YES
12-07 16:02:54.229 6169-6169/? D/EventLogger:     ]
12-07 16:02:54.229 6169-6169/? D/EventLogger:   ]
12-07 16:02:54.229 6169-6169/? D/EventLogger:   Renderer:1 [
12-07 16:02:54.229 6169-6169/? D/EventLogger:     Group:0, adaptive_supported=N/A [
12-07 16:02:54.229 6169-6169/? D/EventLogger:       [X] Track:0, id=1/15, mimeType=audio/mp4a-latm, channels=0, sample_rate=48000, language=eng, supported=YES
12-07 16:02:54.229 6169-6169/? D/EventLogger:     ]
12-07 16:02:54.229 6169-6169/? D/EventLogger:   ]
12-07 16:02:54.229 6169-6169/? D/EventLogger:   Renderer:2 [
12-07 16:02:54.229 6169-6169/? D/EventLogger:     Group:0, adaptive_supported=N/A [
12-07 16:02:54.229 6169-6169/? D/EventLogger:       [ ] Track:0, id=1/8219, mimeType=application/cea-608, supported=YES
12-07 16:02:54.229 6169-6169/? D/EventLogger:     ]
12-07 16:02:54.229 6169-6169/? D/EventLogger:   ]
12-07 16:02:54.229 6169-6169/? D/EventLogger:   Renderer:3 [
12-07 16:02:54.229 6169-6169/? D/EventLogger:     Group:0, adaptive_supported=N/A [
12-07 16:02:54.229 6169-6169/? D/EventLogger:       [X] Track:0, id=1/21, mimeType=application/id3, supported=YES
12-07 16:02:54.229 6169-6169/? D/EventLogger:     ]
12-07 16:02:54.229 6169-6169/? D/EventLogger:   ]
12-07 16:02:54.229 6169-6169/? D/EventLogger: ]
12-07 16:02:54.230 6169-6169/? D/EventLogger: loading [0.39, 0.00, window=0, period=0, false]
12-07 16:02:54.230 6169-6169/? D/EventLogger: mediaPeriodReadingStarted [0.39, 0.00, window=0, period=0]
12-07 16:02:54.231 6169-6169/? D/EventLogger: downstreamFormatChanged [0.40, 0.00, window=0, period=0, id=0, mimeType=null]
12-07 16:02:54.234 6169-6201/? I/OMXClient: retry time 0 ms
12-07 16:02:54.235 6169-6201/? I/OMXClient: Using client-side OMX mux.
12-07 16:02:54.437 6169-6201/? E/ACodec: [OMX.amlogic.avc.decoder.awesome] storeMetaDataInBuffers failed w/ err -2147483648
12-07 16:02:54.452 6169-6201/? W/ACodec: [OMX.amlogic.avc.decoder.awesome] setting nBufferCountActual to 8 failed: -1010
12-07 16:02:54.453 6169-6201/? W/ACodec: [OMX.amlogic.avc.decoder.awesome] setting nBufferCountActual to 7 failed: -1010
12-07 16:02:54.474 6169-6169/? D/EventLogger: decoderInitialized [0.64, 0.00, window=0, period=0, video, OMX.amlogic.avc.decoder.awesome]
12-07 16:02:54.475 6169-6169/? D/EventLogger: decoderInputFormatChanged [0.64, 0.00, window=0, period=0, video, id=0, mimeType=video/avc, codecs=avc1.640028, res=1920x1012]
12-07 16:02:54.477 6169-6204/? I/OMXClient: retry time 0 ms
12-07 16:02:54.477 6169-6204/? I/OMXClient: Using client-side OMX mux.
12-07 16:02:54.508 6169-6204/? I/omx_core: OMX_Init 66 gInitCount=1
12-07 16:02:54.509 6169-6204/? V/AML_all_components: --------------------------------
    ARCH = arm
    author:aml.sh multi-media team
    branch name:   * jb-mr1-amlogic
    git version:   4be65a8ac742e707a2de5b80ec20f4f67823be5d 
    last changed:  Date: Tue Nov 29 13:07:31 2016 +0800
    build-time:     Wed Nov 30 15:40:23 CST 2016
    build-name:     jintao.xu
    uncommitted-file-num:0
    cd /mnt/fileroot/jintao.xu/5.1.p200
    hostname droid07
    --------------------------------
12-07 16:02:54.509 6169-6204/? V/OmxComponentManagerImpl: loadLibrary:258 Loading OMX library libOmxVideo.so.
12-07 16:02:54.510 6169-6204/? E/omx_video: amvenc_avc open failed!set default instance number as 1,ret=-1,Permission denied(13)
12-07 16:02:54.510 6169-6204/? E/omx_video: /dev/HevcEnc open failed!set default instance number as 1,ret=-1,No such file or directory(2)
12-07 16:02:54.510 6169-6204/? I/omx_core: Core library has 15 components
12-07 16:02:54.510 6169-6204/? E/OMXMaster: A component of name 'OMX.google.h264.decoder' already exists, ignoring this one.
12-07 16:02:54.510 6169-6204/? E/OMXMaster: A component of name 'OMX.google.alac.decoder' already exists, ignoring this one.
12-07 16:02:54.520 6169-6169/? D/EventLogger: decoderInitialized [0.68, 0.00, window=0, period=0, audio, OMX.google.aac.decoder]
12-07 16:02:54.520 6169-6208/? W/SoftAAC2: aacDecoder_ConfigRaw decoderErr = 0x0005
12-07 16:02:54.521 6169-6169/? D/EventLogger: decoderInputFormatChanged [0.69, 0.00, window=0, period=0, audio, id=1/15, mimeType=audio/mp4a-latm, channels=0, sample_rate=48000, language=eng]
12-07 16:02:54.521 6169-6204/? E/ACodec: [OMX.google.aac.decoder] ERROR(0x80001001)
12-07 16:02:54.521 6169-6204/? E/ACodec: signalError(omxError 0x80001001, internalError -2147483648)
12-07 16:02:54.521 6169-6204/? E/MediaCodec: Codec reported err 0x80001001, actionCode 0, while in state 6
12-07 16:02:54.523 6169-6190/? E/ExoPlayerImplInternal: Internal runtime error.
    java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueInputBuffer(Native Method)
        at android.media.MediaCodec.dequeueInputBuffer(MediaCodec.java:987)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:887)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:664)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:536)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:303)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:135)
        at android.os.HandlerThread.run(HandlerThread.java:61)
12-07 16:02:54.629 6169-6169/com.google.android.exoplayer2.demo D/EventLogger: decoderDisabled [0.79, 0.00, window=0, period=0, video]
12-07 16:02:54.633 6169-6204/com.google.android.exoplayer2.demo I/omx_core: OMX_Deinit 96 gInitCount=0
12-07 16:02:54.836 6169-6190/com.google.android.exoplayer2.demo E/ExoPlayerImplInternal: Stop failed.
    java.lang.IllegalStateException
        at android.media.MediaCodec.native_stop(Native Method)
        at android.media.MediaCodec.stop(MediaCodec.java:632)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.releaseCodec(MediaCodecRenderer.java:608)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onDisabled(MediaCodecRenderer.java:562)
        at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.onDisabled(MediaCodecAudioRenderer.java:539)
        at com.google.android.exoplayer2.BaseRenderer.disable(BaseRenderer.java:153)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.disableRenderer(ExoPlayerImplInternal.java:983)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:771)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:742)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:358)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:135)
        at android.os.HandlerThread.run(HandlerThread.java:61)
12-07 16:02:54.838 6169-6169/com.google.android.exoplayer2.demo D/EventLogger: decoderDisabled [1.00, 0.00, window=0, period=0, audio]
12-07 16:02:54.840 6169-6169/com.google.android.exoplayer2.demo D/EventLogger: mediaPeriodReleased [1.00, 0.00, window=0, period=0]
12-07 16:02:54.841 6169-6169/com.google.android.exoplayer2.demo E/EventLogger: playerFailed [1.00, 0.00, window=0]
    com.google.android.exoplayer2.ExoPlaybackException: java.lang.IllegalStateException
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:359)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:135)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueInputBuffer(Native Method)
        at android.media.MediaCodec.dequeueInputBuffer(MediaCodec.java:987)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:887)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:664)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:536)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:303)
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
12-07 16:02:54.842 6169-6169/com.google.android.exoplayer2.demo D/EventLogger: state [1.01, 0.00, window=0, true, IDLE]

**Comment by AquilesCanta** [comment]
There is not much we can do without a sample stream. Make your you try setting FLAG_ALLOW_NON_IDR_KEYFRAMES (see #5108 for instructions on how to do it).

**Comment by JiannaiJ** [comment]
@AquilesCanta  FLAG_ALLOW_NON_IDR_KEYFRAMES has been set up.

**Comment by JiannaiJ** [comment]
@AquilesCanta  FLAG_IGNORE_AAC_STREAM can play without sound,  FLAG_ALLOW_NON_IDR_KEYFRAMES  can't play.
