### ISSUE TITLE
FULL HD HLS Stream error

### ISSUE THREAD

**Issue by RadhikaBalla** [google/ExoPlayer#5215]
**Problem:**
      Stream is getting stopped after playing one frame and giving following error in android logcat in case of HD HLS Streams. But for SD(720p,360p) streams it is working fine.

Android Error in logcat:  E/ACodec: [OMX.google.h264.decoder] setPortMode on output to DynamicANWBuffer failed w/ err -1010

**Exoplayer code:**
            bandwidthMeter = new DefaultBandwidthMeter();
            videoTrackSelectionFactory = new AdaptiveTrackSelection.Factory(bandwidthMeter);
            trackSelector = new DefaultTrackSelector(videoTrackSelectionFactory);
            loadControl = new DefaultLoadControl();
            player = ExoPlayerFactory.newSimpleInstance(getActivity(), trackSelector, loadControl);
            simpleExoPlayerView = new SimpleExoPlayerView(getActivity());
            simpleExoPlayerView = (SimpleExoPlayerView) v.findViewById(R.id.player_view);
            simpleExoPlayerView.setUseController(true);
            simpleExoPlayerView.requestFocus();

            simpleExoPlayerView.setPlayer(player);
            mp4VideoUri = url;

            bandwidthMeterA = new DefaultBandwidthMeter();
            dataSourceFactory = new DefaultDataSourceFactory(getActivity(), Util.getUserAgent(getActivity(), "exoplayer2example"), bandwidthMeterA);

            DefaultHlsExtractorFactory defaultHlsExtractorFactory =
                    new DefaultHlsExtractorFactory(DefaultTsPayloadReaderFactory.FLAG_ALLOW_NON_IDR_KEYFRAMES);
            MediaSource mediaSource =
                    new HlsMediaSource.Factory(dataSourceFactory)
                            .setExtractorFactory(defaultHlsExtractorFactory)
                            .createMediaSource(mp4VideoUri);
            loopingSource = new LoopingMediaSource(mediaSource);
            player.prepare(loopingSource);

**Exoplayer version:** com.google.android.exoplayer:exoplayer:2.9.1

**Comment by AquilesCanta** [comment]
Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).
