### ISSUE TITLE
Metadata isn't shown on Samsung devices lock screen

### ISSUE THREAD

**Issue by MurtadhaS** [google/ExoPlayer#5223]
Hello,
So, I am trying to implement a music player, but on Samsung I am getting Unknown Unknown as a track name and artist name.
First, I thought the issue of metadata was solved here:
https://github.com/google/ExoPlayer/issues/4292
But, after digging in, I found this issue :
https://github.com/google/ExoPlayer/issues/4356
With a direction from one of the contributors saying:

 **We've added the interface MediaSessionConnector.MediaMetadataProvider which can be passed to the constructor of the MediaSessionConnector to provide custom metadata.

It's available in the dev-v2 branch.**

I tried to do so (i.e. adding a custom action, but nothing happened).
I would appreciate any help.

My code to add the custom action is:
	
```
mediaSessionConnector.setPlayer(mediaPlayer, new MusicPlaybackPreparer(), new MediaSessionConnector.CustomActionProvider() {
			@Override
			public void onCustomAction(String action, Bundle extras) {

			}

			@Override
			public PlaybackStateCompat.CustomAction getCustomAction() {
				PlaybackStateCompat.CustomAction customAction = new PlaybackStateCompat.CustomAction.Builder(MediaMetadataCompat.METADATA_KEY_TITLE, queueController.getCurrentTrack().getTitle(), R.drawable.ic_cd_player).build();
				return customAction;
			}
		});

```

**Comment by marcbaechinger** [comment]
Samsung apparently is using different metatdata keys than other vendors, at least in case of the title. 

The MediaSessionConnector does copy metadata entries available in the MediaDescriptionCompat of a selected queue item to MediaMetadataCompat.Builder to give the media session information about the item currently being played. There is no officially specified mapping for properties of the MediaDescriptionCompat and the MediaMetadataCompat. What the connector does is best effort only.

For the title the mapping is pretty obvious, and we provided a fix to copy what we get from mediaDescriptionCompat.getTitle() to both MediaMetadataCompat.METADATA_KEY_TITLE and MediaMetadataCompat.METADATA_KEY_DISPLAY_TITLE which should make this work for the title of the track. (https://github.com/google/ExoPlayer/blob/release-v2/extensions/mediasession/src/main/java/com/google/android/exoplayer2/ext/mediasession/MediaSessionConnector.java#L739)

There is no attribute 'artist' which we can get from the MediaDescriptionCompat. So If you want to add additional metadata or change the current mapping you need to use a MediaSessionConnector.MediaMetadataProvider and map everything yourself. The is called when the active queue item changes and the MediaMetadataCompat object which is returned by the provider is set to the session.

**Comment by ojw28** [comment]
> I tried to do so (i.e. adding a custom action, but nothing happened)

That's not what the quote you quoted says that you should do. It says you should provide a `MediaMetadataProvider`, which can be passed to the `MediaSessionConnector` constructor. For example:

```
MediaSessionConnector connector = new MediaSessionConnector(
    mediaSession,
    .... other args ....
    new MediaSessionConnector.MediaMetadataProvider() {
      @Override
      public MediaMetadataCompat getMetadata(Player player) {
        .... build and return custom metadata object here ....
      }
    });
```

The keys Samsung are using are `MediaMetadataCompat.METADATA_KEY_TITLE` (for the top line) and `MediaMetadataCompat.METADATA_KEY_ARTIST` (for the second line).

**Comment by MurtadhaS** [comment]
@ojw28 I ended up adding the metadata (not by constructor as you mentioned though), and it worked.
Thanks for both of you guys.
