### ISSUE TITLE
[Question] how to fetch uri for mediasource dynamically just before playing it

### ISSUE THREAD

**Issue by mayankgrover** [google/ExoPlayer#5224]
Hi, 

I am trying to play a playlist using ConcatenatingMediaSource (everything is HLS audio stream). Problem is the way our legacy backend server system is constructed is that when a user wants to play a playlist, for each song it sends url which the app needs to hit to get the actual url that is valid only for the next 10 seconds. So if I have 5 songs, each 1 min long, then while calling player.prepare I can not pass actual urls for all the songs as songs 2 to 5 will become invalid buy the time exoplayer gets to playing those  songs.

I have tried to look for a possible approach but no luck yet. Any help/suggestions would be highly appreciated. 

Thanks!

**Comment by tonihei** [comment]
That sounds almost exactly like the question asked here: #3661.

You should probably provide the non-expiring urls to the playlist and use your own `DataSource` wrapper which resolves the url each time the player wants to load something.

**Comment by mayankgrover** [comment]
Thanks @tonihei. you are correct, the use case sounds very similar. will give that solution a shot. Much appreciated.
