### ISSUE TITLE
Type 'com.google.android.exoplayer2.upstream.TransferListener' does not have type parameters

### ISSUE THREAD

**Issue by AliceZhuZhu** [google/ExoPlayer#5231]
![7e41c66e-0959-414b-86fa-81976f4d15ed](https://user-images.githubusercontent.com/36066123/49725146-009f2300-fca6-11e8-93e9-b3f42e211106.png)

**Comment by AliceZhuZhu** [comment]
`implementation 'com.google.android.exoplayer:extension-okhttp:2.9.2'`

and

`allprojects {
    repositories {
        google()
        jcenter()
        maven {
            url 'https://google.bintray.com/exoplayer/'
        }
    }
}`

**Comment by tonihei** [comment]
That's correct, it really doesn't have the type parameter any more. It got removed in 2.9.

**Comment by tonihei** [comment]
There's also no need to provide a TransferListener to the data source any more, see this [blog post](https://medium.com/google-exoplayer/https-medium-com-google-exoplayer-simplified-bandwidth-meter-usage-17d8189f978b) for details.

**Comment by AliceZhuZhu** [comment]
Thanks @tonihei !
