### ISSUE TITLE
MediaSessionConnector - How can i get next button clicked

### ISSUE THREAD

**Issue by Naguchennai** [google/ExoPlayer#5232]
mediaSession = new MediaSessionCompat(context, "audio_demo");
        mediaSession.setActive(true);
        playerNotificationManager.setMediaSessionToken(mediaSession.getSessionToken());
        mediasessionconector = new MediaSessionConnector(mediaSession);
        mediasessionconector.setPlayer(player, null);

In audio streaming on notification how can get call back if click next or privies button?

**Comment by marcbaechinger** [comment]
There is no way to get the actual clicks on the buttons in the notification. These clicks result in an Intent which is received by the BroadcastReceiver which is part of the PlayerNotificationManager (see https://github.com/google/ExoPlayer/blob/release-v2/library/ui/src/main/java/com/google/android/exoplayer2/ui/PlayerNotificationManager.java#L1029). That's how these clicks arrive at the PlayerNotificationManager.

When the broadcast receiver receives an ACTION_NEXT or ACTION_PREVIOUS it checks whether there is a next or previous window available in the current timeline. If so the call is delegated to ControlDispatcher.dispatchSeekTo(player, nextWindowIndex, C.TIME_UNSET).

If you want to customize the behaviour of what the control dispatcher is doing you can set your own by setting PlaybackNotificationManager.setControlDispatcher() and passing your own ControlDispatcher which might subclass [DefaultControlDispatcher](https://github.com/google/ExoPlayer/blob/f7ed789fc3841b2536f5629c6bb10f4cb4ee5130/library/core/src/main/java/com/google/android/exoplayer2/DefaultControlDispatcher.java).

I'm not sure what your use case is and hence whether the above approach is useful for you. If it does not help, please shed a bit more light on what yo are trying to achieve.
