### ISSUE TITLE
Could not find com.google.android.exoplayer:exoplayer:2.8.2

### ISSUE THREAD

**Issue by jokermonn** [google/ExoPlayer#5236]
> * What went wrong:
Could not resolve all files for configuration ':app:debugCompileClasspath'.
> Could not find com.google.android.exoplayer:exoplayer:2.8.2.
  Searched in the following locations:
      https://dl.google.com/dl/android/maven2/com/google/android/exoplayer/exoplayer/2.8.2/exoplayer-2.8.2.pom
      https://dl.google.com/dl/android/maven2/com/google/android/exoplayer/exoplayer/2.8.2/exoplayer-2.8.2.jar
      https://jcenter.bintray.com/com/google/android/exoplayer/exoplayer/2.8.2/exoplayer-2.8.2.pom
      https://jcenter.bintray.com/com/google/android/exoplayer/exoplayer/2.8.2/exoplayer-2.8.2.jar
      https://google.bintray.com/com/google/android/exoplayer/exoplayer/2.8.2/exoplayer-2.8.2.pom
      https://google.bintray.com/com/google/android/exoplayer/exoplayer/2.8.2/exoplayer-2.8.2.jar

It looks like exoplayer is in maven { url 'https://google.bintray.com/exoplayer' } instead of google()/jcenter()?

**Comment by LazyBonesLZ** [comment]
the same 2.8.3

**Comment by MarcusCwl** [comment]
Same issue happend with 2.4.0
And also happend when dependence to Facebook-audience sdk

**Comment by jokermonn** [comment]
Duplicate of #5225
