### ISSUE TITLE
How to play AAC 5.1 channel HLS ？ 

### ISSUE THREAD

**Issue by JiannaiJ** [google/ExoPlayer#5237]
HLS contains AAC 5.1 channel audio tracks, which cannot be played as long as the audio tracks are loaded. Is there any way for ExoPlayer to support it?

**Comment by ojw28** [comment]
I think I would expect this to just work. Please properly fill out the issue template if you want us to investigate further.

**Comment by ojw28** [comment]
Closing due to lack of follow up.
