### ISSUE TITLE
Crashing video ; Fatal signal 11 (SIGSEGV) ; (MediaCodec_loop)

### ISSUE THREAD

**Issue by stefanwuest** [google/ExoPlayer#5241]
### Issue description
I am using ExoPlayer with `react-native-video` and the application crashes when play a m3u8 stream. The behaviour is consistent regardless whether ExoPlayer or Android MediaPlayer is used. The behaviour is not happening on all devices. I can reproduce it on an Android Emulator — see device config below:

### Reproduction steps
Example with `react-native` and `react-native-video`
```
# example repository that demonstrates the error
$ git clone https://github.com/stefanwuest/rnvideo_exoplayer_error.git
```

```
$ cd rnvideo_exoplayer_error
```

```
$ npm install
```

```
# start the emulator (fill in the name of your emulator)
$ emulator -avd Nexus6
```

```
$ react-native run-android
```

### Link to test content
See sample repo: ```https://player.vimeo.com/external/194959977.m3u8?s=dd020fc4f4951b6a5f6f1caf8ff0ffd01ba96852```
(This is not my video, I can provide my own content via email if necessary)

### Version of ExoPlayer being used
```implementation('com.google.android.exoplayer:exoplayer:2.9.1')```

### Device(s) and version(s) of Android being used
```
Device: Nexus 6
CPU/ABI: Intel Atom (x86_64)
Target: Android 6.0 (API level 23)
Skin: 1440x2560
hw.dPad: no
hw.accelerometer: yes
vm.heapSize: 64
skin.dynamic: no
hw.device.manufacturer: Google
hw.gps: yes
hw.audioInput: yes
tag.id: default
hw.camera.back: none
hw.mainKeys: none
hw.camera.front: none
hw.lcd.density: 560
hw.ramSize: 2048
hw.trackBall: no
hw.battery: yes
hw.sdCard: yes
tag.display: Default
hw.keyboard: yes
hw.sensors.proximity: yes
disk.dataPartition.size: 200M
hw.sensors.orientation: yes
avd.ini.encoding: UTF-8
hw.gpu.enabled: yes
```

### A full bug report captured from the device
[bugreport.txt](https://github.com/google/ExoPlayer/files/2666975/bugreport.txt)

**Comment by ojw28** [comment]
What real device does the issue occur on? Are you sure it's not just a problem with the emulator?

**Comment by stefanwuest** [comment]
@ojw28 I have reports from the following devices:

```
Xiao Mi A2 Lite: Android 8.1.0
Huawei Nova: Android 6.0
Samsung Galaxy S7: Android 8.0
```

The users report that the video is not shown, but only audio is played.

**Comment by stefanwuest** [comment]
@ojw28 I got a hold of a physical device — the behaviour is different from what I've described. In the case of the device it was actually a different issue, so this one can be closed.
