### ISSUE TITLE
Publish old releases to GMaven/google() (in addition to jcenter)

### ISSUE THREAD

**Issue by ojw28** [google/ExoPlayer#5246]
As per title. Spun out from https://github.com/google/ExoPlayer/issues/5225.

**Comment by ZacSweers** [comment]
JCenter has a long history of artifact integrity issues and we try to avoid it at all costs. I recognize that maven central's publishing process is sometimes considered more tedious, but this signing/verification process is part of why it's preferred.

https://blog.autsoft.hu/a-confusing-dependency/
https://twitter.com/jakewharton/status/1073102730443526144?lang=en

Maven.google.com is another option.

**Comment by gabrielittner** [comment]
JCenter is getting shut down in May https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by ojw28** [comment]
Yes, thanks for bringing this to our attention! We need to prioritize this migration.

**Comment by TacoTheDank** [comment]
> Yes, thanks for bringing this to our attention! We need to prioritize this migration.

Absolutely!

**Comment by barnhill** [comment]
Any update on this?

**Comment by dejan2609** [comment]
Latest development: JFrog partially reversed their decision: they decided to serve artifacts via JCenter until **_February 1st 2022_** (but they will stop receiving new artifacts after March 31st 2021). https://www.infoq.com/news/2021/02/jfrog-jcenter-bintray-closure

> ### Update 8th Feb
> 
> #### JFrog have released an update to their original blog post to clarify that the date has been extended:
> 
> > _**UPDATE:** To better support the community in this migration, JFrog has extended the JCenter new package versions submission deadline through March 31st 2021._
> > 
> > _To clarify, the JCenter repository will keep serving packages for 12 months until February 1st 2022. Only the JCenter REST API and UI will be sunsetted on May 1st 2021._
> 
> (You may have to [refresh the post](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter) if since it may have been cached by your browser since you last visited in order to see the update.)

**Comment by barnhill** [comment]
Let's be proactive and get ahead of this. As of May 1st dependency updates won't happen till moved

**Comment by dulmandakh** [comment]
Or publish to Jitpack https://jitpack.io

**Comment by TacoTheDank** [comment]
Exoplayer's too fancy for Jitpack ;)

**Comment by Will5** [comment]
Will all versions be migrated, or only the most recent?

**Comment by andrewlewis** [comment]
@Will5 We'll probably be able to migrate all versions but I can't confirm for definite yet.

There is an in progress discussion about mirroring old versions, but if that doesn't pan out we have a backup plan that will allow copying artifacts at least back to ExoPlayer 2.11.5, which is the earliest version where the IMA extension dependency is available in GMaven. (And if we can get older IMA SDK versions into GMaven or find a way to remove the requirement that they are in the same repository we can go further back.)

**Comment by ag2s20150909** [comment]
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by shekibobo** [comment]
Jcenter is trial running the shutdown on today (12 April 2021) and 26 April 2021 to raise awareness. Are there any updates on publishing to google's maven repo? The commit is there with instructions, but the library does not exist yet.

**Comment by andrewlewis** [comment]
@shekibobo Is jcenter artifact serving included in the planned brown-outs? I thought that applied only to other services.

We are ready to try use maven.google.com for our next release.

**Comment by shekibobo** [comment]
I don't know if it's planned exactly, but it's happening to us today and I don't really have a workaround.

**Comment by maxirosson** [comment]
Don't worry guys, we have more time.

> To clarify, the JCenter repository will keep serving packages for 12 months until February 1st 2022. Only the JCenter REST API and UI will be sunsetted on May 1st 2021.

https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by shekibobo** [comment]
@maxirosson Yes, but today and on the 26th, it looks like people are going to have a problem building using their CI pipelines unless they come up with a workaround. Which yeah, it'll all start working again tomorrow, most likely, but it's blocking a lot of productivity today. They're doing this as a warning, likely so that people depending on these repos will contact library publishers about the problem.

**Comment by ojw28** [comment]
> Yes, but today and on the 26th, it looks like people are going to have a problem building using their CI pipelines unless they come up with a workaround.

What are you basing this on? According to JFrog, the service brown-outs scheduled for today and the 26th only affect the services that are going away on May 1st. Serving of artefacts from JCenter is not going away on May 1st, so should not be subject to these brown-outs.

**Comment by shekibobo** [comment]
Looks like that was a misunderstanding on my part. We had several dependencies failing that were hosted on bintray, but under account-specific repositories. Looks like those are going away soon, then, but I hadn't dug deep enough, and just removed all of jcenter as well as those other repositories. Looks like Jcenter *is* still working, just not account specific repos. Sorry to interrupt. Carry on. 
![giphy](https://user-images.githubusercontent.com/293858/114440725-7a0def80-9b98-11eb-8108-9a7711a9bed1.gif)

**Comment by westy92** [comment]
It looks like artifacts are being published to Google's Maven Repository starting with version 2.13.3 for now! 🎉 
https://maven.google.com/web/index.html?q=exoplayer

**Comment by ojw28** [comment]
Should we keep this open to track uploading previous versions as well?

**Comment by eneim** [comment]
I would love to see the binary for old versions being stored on google() or some non-jcenter repositories.

**Comment by mattahorton** [comment]
It's 2022 and exoplayer can't be found on MavenCentral. What's up?

**Comment by hafizMDM** [comment]
Is there a plan to migrate previous version 2.11.4 as well ?

**Comment by TacoTheDank** [comment]
> Is there a plan to migrate previous version 2.11.4 as well ?

Tbh I wouldn't bet on it. Your best choice would probably be to migrate apps over to 2.13.3 or newer.

**Comment by hafizMDM** [comment]
> > Is there a plan to migrate previous version 2.11.4 as well ?
> 
> Tbh I wouldn't bet on it. Your best choice would probably be to migrate apps over to 2.13.3 or newer.

**Comment by hafizMDM** [comment]
> > Is there a plan to migrate previous version 2.11.4 as well ?
> 
> Tbh I wouldn't bet on it. Your best choice would probably be to migrate apps over to 2.13.3 or newer.

Yes. You are right, I was using another library that has that dependency.

**Comment by andrewlewis** [comment]
Jcenter will be a read-only repository indefinitely according to [this post](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/), so the old releases will remain available.
