### ISSUE TITLE
use_controller true with Proguard causing IncompatibleClassChangeError

### ISSUE THREAD

**Issue by bbincybbaby** [google/ExoPlayer#5247]
```
java.lang.IncompatibleClassChangeError: The method 'void com.google.android.
exoplayer2.ui.PlayerControlView.hideAfterTimeout()' was expected to be of type 
direct but instead was found to be of type virtual (declaration of 'com.google.
android.exoplayer2.ui.PlayerControlView' appears in 
/data/app/com.XXXX-IFhXhTzYLArCtfPSiPQGhw==/base.apk)
```

Am getting the above error when using custom controller_layout with Proguard. Please help me out

**Comment by bbincybbaby** [comment]
https://stackoverflow.com/q/53706184/4639479

**Comment by bbincybbaby** [comment]
@andrewlewis

**Comment by bbincybbaby** [comment]
@ojw28

**Comment by bbincybbaby** [comment]
https://stackoverflow.com/q/53739196/4639479

**Comment by bbincybbaby** [comment]
@tonihei

**Comment by bbincybbaby** [comment]
@ojw28 @andrewlewis

**Comment by kiall** [comment]
Please.do not ping people by name like this. It is incredibly rude and unnecessary. ... Especially when you edit the posts to cycle through names to ping.

**Comment by bbincybbaby** [comment]
please someone help me out, it was so urgent. that's why
