### ISSUE TITLE
Does ExoPlayer need a separate service?

### ISSUE THREAD

**Issue by FastDr1v3r** [google/ExoPlayer#525]
I'm wondering if I should use a separate service for ExoPlayer to play music, currently, I have a method in the MainActivity class which starts the music, do I need to create another service and to put the method inside there? It affects the main thread the way I'm playing music now (like using too many resources)? On Android Developer the documentation about ExoPlayer is not very good so I'm asking here if ExoPlayer needs a separate service (or if this is a recommended way to play the music, and to handle the stuff), if so, would be a Bound Service a good idea?

**Comment by ojw28** [comment]
Deciding whether you should run ExoPlayer in a service is no different to deciding whether to run anything else in a service. If you want audio playback to continue whilst your app is in the background, for example, then you should use a service. If you don't, then it's probably not necessary.
