### ISSUE TITLE
How can I switch the video source while exoplayer is runing?

### ISSUE THREAD

**Issue by qjh5606** [google/ExoPlayer#5251]
I am working on the project that needs to switch the video source,which depends on user's viewpoint. 
so I'm looking for the quickest way to change the video that is currently playing.
the Issue like this : https://github.com/google/ExoPlayer/issues/380.

I am currently try to replace the `ExtractorSampleSource` 's uri with the new one, and call `restartFrom(0)`. but it did not work out. 
`
Uri localUri = Uri.parse(new String("/storage/emulated/0/Download/3D_Rio_shark.mp4"));
uri = localUri;
restartFrom(0);
`

**Comment by tonihei** [comment]
Looks like you are still using ExoPlayer v1 which isn't supported anymore. Please consider switching to v2. 

But generally, you need call player.prepare(source) again with the new source and the player will switch to the new video.

**Comment by qjh5606** [comment]
> Looks like you are still using ExoPlayer v1 which isn't supported anymore. Please consider switching to v2.
> 
> But generally, you need call player.prepare(source) again with the new source and the player will switch to the new video.

Thank you. I will try it using ExoPlayerv2.
