### ISSUE TITLE
Audio Player Repeat Mode 

### ISSUE THREAD

**Issue by Sathish-Kumar-Kanagaraj** [google/ExoPlayer#5253]
I am Using Exoplayer Latest Version(2.9) For Audio Player.
I want to loop or repeat the songs based on single song or list of song.
how can i use the playbackstatecompat for it.
Whether the Exoplayer release v2 code contains audio player related functionalities  like shuffle mode or repeat mode codes.

**Comment by ojw28** [comment]
I don't understand how `PlaybackStateCompat` is relevant. If you have an `ExoPlayer` instance, you can just call `setRepeatMode` and `setShuffleModeEnabled` on the instance to control repeat and shuffle modes (see [here](http://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/Player.html#setRepeatMode-int-))..
