### ISSUE TITLE
Preview seekbar like youtube

### ISSUE THREAD

**Issue by meenukrishnamurthy** [google/ExoPlayer#5254]
Hi i would like to implement a preview seekbar like youtube.Can anyone tell me how to go about it.
A view appears above the seekbar when we are seeking showing a thumbnail of the video at that sec.

**Comment by ojw28** [comment]
YouTube implement this by extracting thumbnail images from the videos on the server side. They then request these images out-of-band to display in their UI during seeking. In other words, their solution is entirely independent of the player.

It's quite difficult to implement this type of feature using the media stream directly (i.e. without separately extracting thumbnails). Even if I were implementing this on the client, I think I'd design something to extract thumbnail images, cache those locally in my app, and then use them to implement a similar solution to YouTube's. The details of how to build this are outside the scope of this issue tracker, however.

Note that for DASH specifically, there is some built in thumbnail support if the media is prepared in a particular way. Supporting this is tracked by https://github.com/google/ExoPlayer/issues/3752.
