### ISSUE TITLE
CODEC_VIDEO_ES_DEVICE vs CODEC_VIDEO_DVAVC_DEVICE

### ISSUE THREAD

**Issue by okycelt** [google/ExoPlayer#5255]
We are using ExoPlayer to play transport streams either from a .ts file or as a UDP multicast. On one of the boxes, a 50 fps stream is laggy in ExoPlayer but okay in MediaPlayer. The stb vendor says MediaPlayer uses `CODEC_VIDEO_ES_DEVICE`, while ExoPlayer uses `CODEC_VIDEO_DVAVC_DEVICE` and asked us if we can force ExoPlayer to use `CODEC_VIDEO_ES_DEVICE` like MediaPlayer does. We didn't find any reference about this though. We can only choose between `OMX.amlogic.avc.decoder.awesome` and `OMX.google.h264.decoder`. Is this even possible?

Thanks.

**Comment by ojw28** [comment]
I don't understand what the STB vendor is saying. Those constants don't seem to be part of the Android SDK. I think you'll need to get them to clarify, preferably in the context of what we should be doing differently when using the `MediaCodec` API (which is the defined API through which we access video decoder).

Note: We always select what we believe is the best video decoder that's exposed to us. If there's a more performant one on this particular device that's not being selected, then it's possible that the vendor is not correctly exposing it.

**Comment by okycelt** [comment]
Thanks for a quick reaction. As for the constants, they've also sent us this [list](https://user-images.githubusercontent.com/26062845/49935598-be5a2980-fed1-11e8-8b36-9649f2de154d.png). I'll ask the STB vendor for more information and post it here, if I manage to get some.

**Comment by ojw28** [comment]
Right. They need to explain what they think ExoPlayer is doing wrong in terms of its interaction with the `MediaCodec` API. Or they need to properly expose their decoders through this API in the correct order (best to worst). I suspect those constants are internal to their own vendor specific code, in which case there's no way ExoPlayer would know about them. Thanks!

**Comment by ojw28** [comment]
Closing for now. If you receive further information please still post it in this issue, and we'll reopen as necessary. Thanks!
