### ISSUE TITLE
Playing live stream has been stopped when the timing of switched the order of audio track which is described on manifests file

### ISSUE THREAD

**Issue by KazumiHARADA** [google/ExoPlayer#5256]
### Issue description
The issue is occurred only specific DASH live stream. It may be there are fundamentaly cause in broadcast setting, but we hope to know the cause of this issue on client side.

Unfortunately, this issue isn't always occurred, so we found that it occurred when the timing of switched the order of audio track which is described on manifests file.

Could you please tell me, if you have some knowledge.

### Reproduction steps
1. add test content at `demo > assets > media.exolist.json`
---
[
  {
    "name": "TEST",
    "samples": [
      {
        "name": "test content",
        "uri": ...,
        "extension": "mpd"
      }
    ]
  },
  ...
]
---
2. Play the test content.
-> It was shown the `Playback failed`, after we play the test content a little time.

### Link to test content
Currently, we are making the test stream.
I'll send the url to the mail later.

### Version of ExoPlayer being used
2.6.1

### Device(s) and version(s) of Android being used
Specify the devices and versions of Android on which the issue can be
reproduced, and how easily it reproduces. If possible, please test on multiple
devices and Android versions.

Device name: AirStick 4K
OS version: 7.1.2

### A full bug report captured from the device
I'll send the data to the mail later.

**Comment by ojw28** [comment]
> Unfortunately, this issue isn't always occurred, so we found that it occurred when the timing of switched the order of audio track which is described on manifests file.

If it's hard for you to provide a test stream, it's probably sufficient for you to just provide two manifests showing how the ordering changes.

It's unclear at exactly which level the ordering is changing. Is it a re-ordering of `AdaptationSet` elements within a `Peroid`, or of `Representation` elements within an `AdaptationSet`? And do the things that swap order have identifiers?

The details above might make a bit of a difference, but fundamentally re-ordering sounds highly undesirable. I think pretty much all live streams we see manage to keep everything in the same order across manifest updates. I'd suggest you work to ensure the same.

**Comment by KazumiHARADA** [comment]
we aware that `AdaptationSet` ids is re-ordered, but `Representation` ids is fixed. so we have recorded `http archive file`, then.
In just case, I've send the har file, so please take a look manifest requests.
Is it wrong that such manifest?

**Comment by ojw28** [comment]
I don't think it's valid to change the `AdaptationSet` ids across manifest updates. That defeats the purpose of what an id is supposed to be for.

In addition, ExoPlayer currently requires that the `AdaptationSet` elements remain in the same order across manifest updates. So if you fixed the ids but still swapped the order of the `AdaptationSet`s, I think playback would still break. I can't see anything in the spec that says swapping the order isn't allowed, but I've proposed to DASH-IF that they forbid it in their interoperability points [here](https://github.com/Dash-Industry-Forum/DASH-IF-IOP/issues/243). It seems like unnecessary complexity for clients to handle, particularly given `AdaptationSet@id` is optional. It also seems very unnecessary that a server would ever need to do this, rather than keeping them in the same order.

So to conclude: If you want your content to play correctly, keep the `AdaptationSet`s in the same order across manifest updates.

**Comment by KazumiHARADA** [comment]
I think so too, so I've sent fix request to support of broadcasting service.
However, we hope to fix the issue as soon as possible.
Therefore, temporarily fix on ExoPlayer, by following code, we can resolve this issue.
Please take a look this code and tell me your opinion.

`DefaultDashChunkSource.java`
```
@Override
  public void updateManifest(DashManifest newManifest, int newPeriodIndex) {
    try {

      manifest = newManifest;
      periodIndex = newPeriodIndex;

      //AdaptationSets of latest manifest
      List<AdaptationSet> adaptationSets = manifest.getPeriod(periodIndex).adaptationSets;

      // AdaptationSets id at zero
      String representationIndexFirst = representationHolders[0].representation.format.id;

      // retrieve collectly `Representations ` by stored representation ids
      List<Representation> representations = getRepresentations();
      for (int i = 0; i < adaptationSets.size(); i++) {
        List<Representation> newRepresentations = adaptationSets.get(i).representations;
        ArrayList<String> representationList = new ArrayList<>();
        for (int j = 0; j < newRepresentations.size(); j++) {
          representationList.add(newRepresentations.get(j).format.id);
          int representationIndex = representationList.indexOf(representationIndexFirst);
          if(representationIndex >= 0) {
            representations = newRepresentations;
          }
        }
      }

      long periodDurationUs = manifest.getPeriodDurationUs(periodIndex);
      for (int i = 0; i < representationHolders.length; i++) {
        Representation representation = representations.get(0);

               String id = representationHolders[i].representation.format.id;
        for (int j = 0; j < representations.size(); j++) {
          if(representations.get(j).format.id.equals(id)) representation = representations.get(j); //dirty code
        }

        representationHolders[i] = representationHolders[i].copyWithNewRepresentation(periodDurationUs, representation);
      }
    } catch (BehindLiveWindowException e) {
      fatalError = e;
    }
  }
```

**Comment by ojw28** [comment]
Closing as bad media. Reviewing app specific code is outside the scope of this issue tracker.
