### ISSUE TITLE
Why does ExoPlayer cant play some of the streams of same type with different bitrates ?

### ISSUE THREAD

**Issue by ckchamara** [google/ExoPlayer#5259]
Ex -
http://108.61.34.50:7130/              ---> 96kbs ===> Playable
http://s3.voscast.com:8408             ---> 64kbs ===> Not Playable
http://220.247.227.20:8000/citystream  ---> 128kbs ===> Not Playable
all above are mpga type

 i used DefaultHttpDataSourceFactory & ExtractorMediaSource..

**Comment by ojw28** [comment]
All three work fine for me. Please include complete information as requested by the issue template.

**Comment by ckchamara** [comment]
**Version of ExoPlayer being used**
2.9.2

**Device(s) and version(s) of Android being used**
Huawei Y5 (2017)
Android 6.0 (Marshmallow)
https://www.gsmarena.com/huawei_y5_(2017)-8640.php

**A full bug report captured from the device**
sent to dev.exoplayer@gmail.com

**Comment by ojw28** [comment]
I think this is probably a device specific issue, but unfortunately the bug report doesn't contain enough information to figure out what's gone wrong.

Please could you try playing one of the problematic streams with the ExoPlayer demo app on the same device, capturing the output of `adb logcat` whilst you do this, and mail or attached the captured logcat. You should see quite a log of logcat with the tag `EventLogger`, if you've captured what we need.

Thanks!

**Comment by ckchamara** [comment]
Thank you for response. you are correct. i also tested on other devices and they are just doing fine...then downloaded other apps that use ExoPlayer and tested on that failed device. none of the apps working properly.

**Comment by ojw28** [comment]
I'd suggest you report this issue to the device manufacturer.
