### ISSUE TITLE
Player randomly stops when downloading into the same cache I am using for playback (and same uri)

### ISSUE THREAD

**Issue by kvillnv** [google/ExoPlayer#5260]
Hello,
ExoPlayer version: 2.9.2
Android TV 7.1.1
Custom Broadcom based Device
Issue happens on any source.

Explanation:
My streams have a live edge and many hours of buffer. They can be rewinded, and can be downloaded just after the manifest contains all the required segments.
Until now playback works fine and download works fine.

Now, I am trying to optimize bandwidth.
A user wants to download a stream, and they also want to watch it before it is downloadable:
For playback, I build the DashMediaSource.Factory on a CacheDataSourceFactory, using the same cache in which I will download the stream. The CacheDataSourceFactory will automatically read from the UpStreamFactory while watching and save in the cache. The manifestDataSourceFactory is a HttpDataSourceFactory, this way, the manifest is periodically updated. 
As a result, if the user has watched the whole show live, when the downloadManager will start the downloadTask, it will instantaneously reach 100%.

I really want to keep this feature, this works well and saves a lot of bandwidth.
However there is an issue: 
If the download starts and the playback of the same stream (same uri) has not finished yet, the player will stop at a random instant (it simply freezes on a frame, without crashing) and the seekbar becomes empty and in onPlayerStateChanges the state goes to BUFFERING.
I get these logs:

> E/EventLogger: audioTrackUnderrun [137.62, 2772223.50, window=0, period=0, 48000, 250, 28482]]
>  E/AudioTrack: Discontinuity detected [expected 2772223515333, got 108116980]

Pressing play/pause or seeking does nothing.
But after like 20seconds the state goes back to READY and seekbar is not empty anymore and it is not playing, but then if I seek, it triggers back the player, and everything is normal again.

Why does it stop the player? Why does it work again with a seek action after a few seconds? 

I have tried to use flags on CacheDataSourceFactory, but it does not help.
I am not sure this should be solved with some cache parameters or if this is exoplayer that needs to handle this situation (looks like the player still thinks it is playing, but it is not).

* This does not happen when I am not downloading.
* While downloading it does not happen if I play using a HttpDataSource, but I loose the benefit of saving in cache like CacheDataSource does.
* This does not happen if the download is finished (and the mediaSource will be entirely local). 
* And of course, this does not happen if the uri I am downloading and the uri I am watching are not the same.

Any help would be appreciated.
Thanks

**Comment by erdemguven** [comment]
It sounds like player is blocked because both the player and the downloader try to write to the same cache segment. Please make sure you don't set CacheDataSource.FLAG_BLOCK_ON_CACHE when you create the player CacheDataSource.

**Comment by kvillnv** [comment]
@erdemguven that is exactly what I thought.
Yes I confirm, my original settings are not using CacheDataSource.FLAG_BLOCK_ON_CACHE
Should I be using any other flag in my player's cacheDataSourceFactory?
Or any other idea?

And what about the CacheDataSource generated in the DownloadManager's DownloadConstructorHelper ? I noticed it is using the CacheDataSource.FLAG_BLOCK_ON_CACHE

**Comment by erdemguven** [comment]
During downloading we don't want to skip cache that's why the flag set so it's correct.

This issue may happen if the downloaded segments and the streamed segments use different cache keys.

Do you use  a custom CacheKeyFactory?

**Comment by kvillnv** [comment]
No, I don't use a custom CacheKeyFactory

**Comment by ojw28** [comment]
The logging you see might indicate an invalid transformation of the DASH manifest when the stream changes from live to on-demand. Can you provide a few snapshots of a DASH manifest toward the end of it being a live stream, and then a snapshot of the same DASH manifest after its final update.

It's somewhat hard to tell with the limited information provided. *Please* properly fill in the issue template and provide all of the requested information when filing issues; not doing so only delays how quickly and efficiently we can help. But my guess is this is more likely a content issue than an issue with the cache.

**Comment by kvillnv** [comment]
Hello, 
I just got back on this task today.
It was indeed a manifest issue: the solution was to set the packager to not set a endtime to my Live manifest. Thank you for the hint @ojw28
With my API this implies to use a different Uri than the one used for the On-demand. Initially I thought that using different Uris would not allow the downloader to recognize the cached content. But it actually works.
Everything looks good, I can play without interruption, and when the download starts, it benefits from the content already cached on playback.
