### ISSUE TITLE
How custom quality selection layout

### ISSUE THREAD

**Issue by majidebrahimii** [google/ExoPlayer#5261]
How can i customize selection layout. like change language, text, button, layout style and ... .
I'm use version 2.9.0. 
[http://s9.picofile.com/file/8345781934/photo_2018_12_15_11_17_21.jpg](url)

**Comment by ojw28** [comment]
If you want to make significant modifications then you should just make your own UI component. You can use the code for the one provided by the library as a starting point. App specific UI is outside the scope of this issue tracker.
