### ISSUE TITLE
How to Determine if exoplayer is playing from cache or Network 

### ISSUE THREAD

**Issue by mathemandy** [google/ExoPlayer#5264]
### Question
I use Simple Cache in my app to stream app.  I want to be able to know when exoplayer plays a song from cache or direct from the Network. I am trying to send events and would want to be able to track this. 
Is there already a listener that can tell me if  exoplayer is playing from Cache or Internet.
Thanks.

**Comment by tonihei** [comment]
You could add a `TransferListener` to the `CacheDataSource` and listen to the events in there. They contain a reference to the actual underlying data source which reads the data and a flag telling you whether the transfer is using a network connection.

**Comment by tonihei** [comment]
Closing as answered.
