### ISSUE TITLE
Stretching video on Huawei

### ISSUE THREAD

**Issue by ghost** [google/ExoPlayer#5265]
I have issue with video stretch on Huawei devices:
Huawei Mate 10 pro 8.0.0
Huawei P10 lite 8.0.0

here is video link:
https://firebasestorage.googleapis.com/v0/b/the-wonder-weeks-app.appspot.com/o/videos%2Fitsy_bitsy_spider.mp4?alt=media&token=1f205a0d-a6f7-412c-86a9-be50b851e6d0

here is issue video
https://drive.google.com/file/d/18jhu5w_dmWR2v_YJRkIYcU59O2_Qi13B/view?usp=sharing

Issue is only manifesting on Huawei devices randomly.
Tried this setup with no luck:
setResizeMode(AspectRatioFrameLayout.RESIZE_MODE_FIT)
setVideoScalingMode(C.VIDEO_SCALING_MODE_SCALE_TO_FIT)

Exoplayer versions 2.9.0, 2.9.2.

**Comment by erdemguven** [comment]
Can you repeat the issue using ExoPlayer demo app?

**Comment by erdemguven** [comment]
I tried using ExoPlayer 2.9.2 demo app on Huawei Mate 10 pro 8.0.0 but couldn't reproduce the issue. I think it's likely that the issue is caused by application's code.

**Comment by qsdigor** [comment]
We tried exo player demo app and video works. It seams it is our code, we are using exo player in simple instance. Here is how we are initialize it.

https://pastebin.com/QejF9rkA

**Comment by qsdigor** [comment]
Found issue. 
When creating activity I was setting it fullscreen and exoplayer view did not load correctly sometime, maybe issue is with calculating width and height. 
Calling "setFullscreen" before setContentView fixed stretching.
