### ISSUE TITLE
Lip sync issue on DASH LIVE

### ISSUE THREAD

**Issue by luckylook** [google/ExoPlayer#5266]
we have an issue of Lip sync on Mpeg DASH LIVE channels. it seems that audio appearing before video in a difference of 1-2 sec.  which parameter can we adjust on the Exo player in order to handle that sync issue and align the video with audio timing for DASH LIVE ? thanks.
we're on Exo version 2.9.2

**Comment by ojw28** [comment]
It's highly likely that your source is out of sync. In which case you should fix the source, not look for client features to offset the sync back to where it should be. If you believe it to be a client (i.e. ExoPlayer) issue, please properly fill out the issue template.

**Comment by ojw28** [comment]
Closing on the assumption this is a content issue. We do not provide functionality for shifting back into sync on the client. If you believe the content is correct and the client is playing it out of sync, please let us know and provide sample media.
