### ISSUE TITLE
"WV: Secure video path required" does not playback normally

### ISSUE THREAD

**Issue by Hongjae** [google/ExoPlayer#527]
I have tested the Exoplayer of the r1.3.3.
But Only "WV: Secure video path required" in the item of "WIDEVINE GTS DASH" does not playback normally.
Devices I tested, Widevine security level 1.

The following is a log of when is fails to playback.

06-09 10:37:59.716 11626 11626 E EventLogger: internalError [8.17, rendererInitError]
06-09 10:37:59.716 11626 11626 E EventLogger: com.google.android.exoplayer.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to http://www.youtube.com/api/manifest/dash/id/cf74bf361c2e79a3/source/youtube?as=fmp4_audio_cenc,fmp4_sd_hd_cenc&sparams=ip,ipbits,expire,as&ip=0.0.0.0&ipbits=0&expire=19000000000&signature=8979A9B6271A9FE5D2AF9465D0817B039F940F72.2AB9171CA5A108230976FB7F7F4925299B7E6C1F&key=ik0
06-09 10:37:59.716 11626 11626 E EventLogger: 	at com.google.android.exoplayer.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:196)
06-09 10:37:59.716 11626 11626 E EventLogger: 	at com.google.android.exoplayer.upstream.DefaultUriDataSource.open(DefaultUriDataSource.java:136)
06-09 10:37:59.716 11626 11626 E EventLogger: 	at com.google.android.exoplayer.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:97)
06-09 10:37:59.716 11626 11626 E EventLogger: 	at com.google.android.exoplayer.upstream.DataSourceInputStream.open(DataSourceInputStream.java:56)
06-09 10:37:59.716 11626 11626 E EventLogger: 	at com.google.android.exoplayer.upstream.UriLoadable.load(UriLoadable.java:92)
06-09 10:37:59.716 11626 11626 E EventLogger: 	at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:242)
06-09 10:37:59.716 11626 11626 E EventLogger: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
06-09 10:37:59.716 11626 11626 E EventLogger: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
06-09 10:37:59.716 11626 11626 E EventLogger: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
06-09 10:37:59.716 11626 11626 E EventLogger: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
06-09 10:37:59.716 11626 11626 E EventLogger: 	at java.lang.Thread.run(Thread.java:818)
06-09 10:37:59.716 11626 11626 E EventLogger: Caused by: java.net.SocketTimeoutException
06-09 10:37:59.716 11626 11626 E EventLogger: 	at java.net.PlainSocketImpl.read(PlainSocketImpl.java:488)
06-09 10:37:59.716 11626 11626 E EventLogger: 	at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:37)
06-09 10:37:59.716 11626 11626 E EventLogger: 	at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
06-09 10:37:59.716 11626 11626 E EventLogger: 	at com.android.okio.Okio$2.read(Okio.java:120)
06-09 10:37:59.716 11626 11626 E EventLogger: 	at com.android.okio.RealBufferedSource.indexOf(RealBufferedSource.java:154)
06-09 10:37:59.716 11626 11626 E EventLogger: 	at com.android.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:101)
06-09 10:37:59.716 11626 11626 E EventLogger: 	at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:196)
06-09 10:37:59.716 11626 11626 E EventLogger: 	at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:103)
06-09 10:37:59.716 11626 11626 E EventLogger: 	at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:677)
06-09 10:37:59.716 11626 11626 E EventLogger: 	at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:403)
06-09 10:37:59.716 11626 11626 E EventLogger: 	at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:347)
06-09 10:37:59.716 11626 11626 E EventLogger: 	at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:515)
06-09 10:37:59.716 11626 11626 E EventLogger: 	at com.google.android.exoplayer.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:193)
06-09 10:37:59.716 11626 11626 E EventLogger: 	... 10 more

**Comment by ojw28** [comment]
Working fine for me. Likely just a temporary issue on the server side.

**Comment by Hongjae** [comment]
It is not still playing normally. So I analyzed the source in more detail.
Eventually I found one that strange.

"ExoPlayer/demo/src/main/java/com/google/android/exoplayer/demo/Samples.java"
In my opinion, seems to URI is wrong when create new sample in "Widevine GTS Sample".
'?' is missing in "WV: Secure video path required" uri.
Latest version previously had been included '?' in "WV: Secure video path required".

following "Widevine GTS Sample"'s URI - r1.3.3
1. "WV: HDCP not specified"
  - Begin with "http://www.youtube.com/api/manifest/dash/id/d286538032258a1c/source/youtube?" 
2. "WV: HDCP not required"
  - Begin with "http://www.youtube.com/api/manifest/dash/id/48fcc369939ac96c/source/youtube?"
3. "WV: HDCP required"
  - Begin with "http://www.youtube.com/api/manifest/dash/id/e06c39f1151da3df/source/youtube?"
4. "WV: Secure video path required"
  - Begin with "http://www.youtube.com/api/manifest/dash/id/0894c7c8719b28a0/source/youtube?"
5. "WV: HDCP + secure video path required"
  - Begin with "http://www.youtube.com/api/manifest/dash/id/efd045b1eb61888a/source/youtube"
6. "WV: 30s license duration (fails at ~30s)"
  - Begin with "http://www.youtube.com/api/manifest/dash/id/f9a34cab7b05881a/source/youtube?"

No.5 -> '?' is missing after "youtube".
After adding a '?', A result of the test, working fine.

Please check this.
Thanks for your support.

**Comment by ojw28** [comment]
Right, so it's the "WV: HDCP + secure video path required" one that fails, not the one mentioned in the title/body of this report. I'll get this fixed.
