### ISSUE TITLE
Merge two TrackGroups 

### ISSUE THREAD

**Issue by userdimi** [google/ExoPlayer#5270]
In my DASH video file I have two adaptation sets for the video. One for SD and one for HD.  When I try to play the file the renderer select only the SD TrackGroup. (Please take a look at the logs) The same behavior I can reproduce with my video settings in the Exoplayer Demo App. So the question is, how can I merge the SD and HD TrackGroups to one TrackGroup to load the HD tracks also?

 
![bildschirmfoto 2018-12-18 um 08 17 37](https://user-images.githubusercontent.com/2900264/50138061-85d59980-029d-11e9-88cf-ae8ae5ae0b01.png)

**Comment by ojw28** [comment]
If the adaptation sets present the same content and can be adapted between, you should indicate this in the manifest using the `urn:mpeg:dash:adaptation-set-switching:2016` supplemental property, as described in [DASH IF IOP Section 3.8](https://dashif.org/docs/DASH-IF-IOP-v4.2-clean.pdf). If you do this, ExoPlayer will merge the tracks into a single group.

**Comment by userdimi** [comment]
Thank you for the quick response. I will optimize the dash manifest in this way.
