### ISSUE TITLE
IMA extension and Open Measurement

### ISSUE THREAD

**Issue by grajzer** [google/ExoPlayer#5271]
Is there a way we can see VAST response when using IMA extension?

More specifically, I'd like to get contents of Extensions node (or Verification node, VAST 4.0) in order to implement Open Measurement.

We're in the the process of certifying our Android SDK with the Google team and implementing Open Measurement is one of the requirements.

**Comment by andrewlewis** [comment]
I'm not aware of any way to get VAST responses from IMA. @ypavlotsky will be able to confirm and perhaps advise on implementing Open Measurement with the IMA SDK.

If it's not possible, a potential workaround would be to load the ad tag yourself and pass it to `ImaAdsLoader.Builder.buildForAdsResponse`.

**Comment by ocorso** [comment]
There's not a way to retrieve the VAST response via IMA as IMA is designed to manage/handle all of the VAST parsing for you ;)

However, you may be able to view the network traffic (and the VAST response therein) via a web proxy like Charles:
https://medium.com/@hackupstate/using-charles-proxy-to-debug-android-ssl-traffic-e61fc38760f7

Hope this helps :)

**Comment by grajzer** [comment]
Thank you for your help!
