### ISSUE TITLE
Repeat and Shuffle Mode in Audio Player i am using UAMP 

### ISSUE THREAD

**Issue by Sathish-Kumar-Kanagaraj** [google/ExoPlayer#5273]
Hi i am using UAMP app for My Music player
Kindly explain me
How can i enable the repeat mode when i click on the repeat icon in the ui i am using.
I am seeing method called setRepeat Mode in Exoplayer ,Playback State compat and also Local playback classes but how can i trigger that repeat function on a button click

**Comment by ojw28** [comment]
@nic0lette - Could you please respond to this :)?

**Comment by ojw28** [comment]
I'm not really sure what this question is asking. ExoPlayer has `Player.setRepeatMode` and `Player.setShuffleModeEnabled`, so you should wire up your button to those.

For UAMP questions, please ask on the [UAMP issue tracker](https://github.com/android/uamp/issues).
