### ISSUE TITLE
Persistent progressbar over video

### ISSUE THREAD

**Issue by luizguilhermefr** [google/ExoPlayer#5275]
### Issue description

I am trying to reproduce a MP4 video through `ExtractorMediaSource`, however, a persistent ProgressBar is displayed over the video. I have already tried to use `app:show_buffering="never"` and set a whole custom layout, but no success.

![screenshot_1545152921](https://user-images.githubusercontent.com/6135939/50170542-41ff8600-02d7-11e9-8941-3ff965ef3c21.png)
![screenshot_1545152914](https://user-images.githubusercontent.com/6135939/50170543-42981c80-02d7-11e9-9c34-d0485c473e63.png)

### Reproduction steps

```java
String appName = getApplicationInfo().loadLabel(getPackageManager()).toString();
mViewHolder.playerView.setVisibility(View.VISIBLE);
Uri videoUri = Uri.parse(videoFile.getLink());
DataSource.Factory dataSourceFactory = new DefaultDataSourceFactory(LessonActivity.this, Util.getUserAgent(LessonActivity.this, appName));
MediaSource videoSource = new ExtractorMediaSource.Factory(dataSourceFactory).createMediaSource(videoUri);
SimpleExoPlayer player = ExoPlayerFactory.newSimpleInstance(
  LessonActivity.this,
  new DefaultRenderersFactory(LessonActivity.this),
  new DefaultTrackSelector(),
  new DefaultLoadControl()
);
mViewHolder.playerView.setPlayer(player);
player.prepare(videoSource);
player.setPlayWhenReady(true);
```

```xml
<com.google.android.exoplayer2.ui.PlayerView
  android:id="@+id/video_player"
  android:layout_width="match_parent"
  android:layout_height="match_parent"
  android:visibility="gone"
/>
```

### Version of ExoPlayer being used

`'com.google.android.exoplayer:exoplayer:2.9.1'`

### Device(s) and version(s) of Android being used

Nexus 5X API 27 emulator

**Comment by droidwave** [comment]
Very Easy you just hide and show progress bar inside frame while the video is buffering 
https://androidwave.com/video-streaming-exoplayer-in-android/
```
@Override
    public void onPlayerStateChanged(boolean playWhenReady, int playbackState) {
        switch (playbackState) {
 
            case Player.STATE_BUFFERING:
                spinnerVideoDetails.setVisibility(View.VISIBLE);
                break;
            case Player.STATE_ENDED:
                // Activate the force enable
                break;
            case Player.STATE_IDLE:
 
                break;
            case Player.STATE_READY:
                spinnerVideoDetails.setVisibility(View.GONE);
 
                break;
            default:
                // status = PlaybackStatus.IDLE;
                break;
        }
    }

```

**Comment by luizguilhermefr** [comment]
@droidwave The problem is that I don't have this spinner.

In the example you gave, a separate spinner is declared within the view, so it can be hide and showed. In my case, an undesired spinner is shown. I'd like to know how to hide it, as I already tried declaring a custom XML for the player and to disable the entire controls. The spinner keeps over my video.

Here is the custom XML I am using for the player (note that there is no spinner at all):

```xml
<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <ImageButton
        android:id="@+id/exo_play"
        android:layout_width="70dp"
        android:layout_height="70dp"
        android:layout_gravity="center"
        android:padding="10dp"
        android:scaleType="fitXY"
        app:srcCompat="@drawable/ic_play" />

    <ImageButton
        android:id="@+id/exo_pause"
        android:layout_width="70dp"
        android:layout_height="70dp"
        android:layout_gravity="center"
        android:padding="10dp"
        android:scaleType="fitXY"
        app:srcCompat="@drawable/ic_pause" />

    <com.google.android.exoplayer2.ui.DefaultTimeBar
        android:id="@+id/exo_progress"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_gravity="bottom"
        android:layout_margin="15dp"
        app:buffered_color="@color/colorAccent"
        app:played_color="@color/colorPrimary"
        app:scrubber_color="@color/colorPrimaryDark"
        app:unplayed_color="@color/colorLightGrey" />

</FrameLayout>
```

**Comment by ojw28** [comment]
Are you certain the spinner is coming from ExoPlayer code? It looks pretty clear from our `PlayerView` code that we wont display the buffering spinner unless application code has specifically enabled it (by calling `setShowBuffering`).

**Comment by luizguilhermefr** [comment]
@ojw28 I inspected the layout via Android Studio. Here is what I've found. There is a `exo_progress_view` with a `progress_bar` child.

![image](https://user-images.githubusercontent.com/6135939/50301849-89b91580-046f-11e9-97db-0ac8d84d0dd8.png)

**Comment by ojw28** [comment]
I don't think we have any views with those ids (`exo_progress_view` or `progress_bar`) anywhere in the ExoPlayer library. Searching Google, it seems such views exist in [this SDK](https://github.com/sambatech/player_sdk_android). Are you using it? If so, your issue is with the SDK, not with ExoPlayer. If not, can you point to anywhere in the ExoPlayer codebase from which you believe these views could be originating? Thanks!

**Comment by luizguilhermefr** [comment]
Yes, I am using along with the ExoPlayer itself. I have the raw ExoPlayer and this other player for other scenarios. I'd never think other library would be the problem. Thank you very much!
