### ISSUE TITLE
How to set scrubberDrawable in kotlin ?

### ISSUE THREAD

**Issue by hanhmh1203** [google/ExoPlayer#5279]
I want to custom scrubberDrawable with my icon, 
How to change scrubberDrawable realtime ?
Thank for support

**Comment by erdemguven** [comment]
You can set scrubber_drawable attribute of the DefaultTimeBar when used in a layout XML file.
Currently it isn't possible to change the drawable on the fly but perhaps using a custom drable you can change the bitmap.
