### ISSUE TITLE
ANR during blockingSendMessage of MSG_SET_SURFACE

### ISSUE THREAD

**Issue by trandroid** [google/ExoPlayer#528]
In my app I am seeing ANR reports about 40% of the time when exiting video playback.
 
The main thread is waiting during the callback for TextureView’s SurfaceTextureListener
`onSurfaceTextureDestroyed`.
 
My implementation for onSurfaceTextureDestroyed is similar to your demo PlayerActivity’s `surfaceDestroyed`.
It ends up performing a blocking sendMessage, i.e.

```
                mExoPlayer.blockingSendMessage(videoRenderer, MediaCodecVideoTrackRenderer.MSG_SET_SURFACE, surface);
```
 
However, in my app about 2 out of 5 times the blockingSendMessage never returns. I assume it has to do with the `wait()` in ExoPlayerImplInternal#`blockingSendMessage`:
```
  public synchronized void blockingSendMessage(ExoPlayerComponent target, int messageType,
      Object message) {
    if (released) {
      Log.w(TAG, "Sent message(" + messageType + ") after release. Message ignored.");
      return;
    }
    int messageNumber = customMessagesSent++;
    handler.obtainMessage(MSG_CUSTOM, messageType, 0, Pair.create(target, message)).sendToTarget();
    while (customMessagesProcessed <= messageNumber) {
      try {
        wait();
      } catch (InterruptedException e) {
        Thread.currentThread().interrupt();
      }
    }
  }
```
 
 
Q1) Why its getting stuck here?

Q2) A more general question: onSurfaceTextureDestroyed is called on main thread. Should I therefore be calling the non-blocking version of pushSurface?

**Comment by ptran-gpfw** [comment]
Also, I am creating ExoPlayer in `onStart()` and calling ExoPlayer `release()` in `onStop()`.
I am not doing 'backgrounding' like what is done in DemoPlayer `setBackgrounded()`.

**Comment by ojw28** [comment]
Being a "good citizen" in the Android ecosystem requires that you release the video decoder in onPause (or before), so ideally you should create the player in ```onResume``` and release it in ```onPause```.

If you're seeing ANRs then you've probably implemented something that uses a different threading model to the rest of the player. The idea of the threading model is that nothing should block the player's internal playback thread for any significant period of time. Specifically, this thread should never be blocked on network or disk IO. If you look at how the standard components in ExoPlayer work, all network IO is delegated to background loading threads. These load data into a buffer, and the playback thread consumes from the read side of the buffer in a non-blocking way.

Provided you continue to ensure this property in your own components, you shouldn't see any ANRs. Both release and blockingSendMessage will block on the playback thread, but the playback thread itself will be able to respond very quickly.

**Comment by ptran-gpfw** [comment]
Thanks for the guidance on releasing decoder resource in onPause. It makes sense now that I think about it.

Another question, why is the blocking version of `pushSurface` called (in surfaceDestroy)?

It seems either a) the video decoder is released in onPause or b) the video track renderer is disabled in onPause. So it seems safer to call the non-blocking `pushSurface`.

**Comment by ojw28** [comment]
If you look at the surfaceDestroyed documentation, you'll find this:

"After returning from this call, you should no longer try to access this surface. If you have a rendering thread that directly accesses the surface, you must ensure that thread is no longer touching the Surface before returning from this function."

You have to block to guarantee this property. There's nothing unsafe about blocking, providing guidance is followed.

**Comment by ojw28** [comment]
Feel free to re-open if you have further questions. Thanks!
