### ISSUE TITLE
MultiWindowTimeBar for PlayerNotificationManager

### ISSUE THREAD

**Issue by imecstamas** [google/ExoPlayer#5281]
Hi!

I want to show all the mediaSources of a ConcatenatingMediaSource in a single timeBar as a notification. Do you plan to integrate this support for MultiWindowTimeBar in case of notifications via the PlayerNotificationManager? If not, how can I achieve this? 

Thanks,
Tamas

**Comment by tonihei** [comment]
That's a duplicate of #4868.

**Comment by marcbaechinger** [comment]
The options of UI elements you can put in notifications is quite limited. There is no way to put arbitrary UI elements in a notification as far as I know. Instead actions are defined which then are rendered by the system in the notifications as buttons.
