### ISSUE TITLE
How to create AudioProcessor to boost volume

### ISSUE THREAD

**Issue by izderadicka** [google/ExoPlayer#5282]
I read issues #3657 where @andrewlewis  is saying that to increase volume above normal limits  one should implement custom AudioProcessor.

I've made couple of test, but not sure how to implement it, key problem is that input PCM data (16 bit PCM) into my AudioProcessor are already normalized to 16 bit range (so values are already in range 32768 - 32767) , so there is no space to increase amplitude more.

I tried to change output encoding to PCM 32 bits to have some space for increase, but then got unhanded configuration exception 

(And generally it looks like only PCM 16 bit is supported.
Custom AudioProcessors seem to be used before standard processors - especially SilenceSkippingAudioProcessor, which requires PCM 16 bit as it's input -  so I guess if I'll change resolution to 24 or 32 bits it'll not be working.)

Can you provide bit more detailed advice how to implement AudioProcessor to boost volume? Or is there any other trick I can use? Any ideas are welcomed.
Thanks

**Comment by izderadicka** [comment]
I've made another attempt - now going to platform LoudnessEnhancer AudioEffect, which will be applied after exoplayer AudioProcessors.    I have simple code below plugged to player
```kotlin
private class VolumeBooster(enabled: Boolean): AudioListener {
    var enabled: Boolean = false
        set(value) {
            field = value
            this.booster?.apply {
                enabled = value
            }
        }
    private var booster: LoudnessEnhancer? = null
    init {
        this.enabled = enabled
    }
    override fun onAudioSessionId(audioSessionId: Int) {
        Log.d(LOG_TAG, "Audio session id is ${audioSessionId}, supported gain ${LoudnessEnhancer.PARAM_TARGET_GAIN_MB}")
        booster?.release()
        booster = LoudnessEnhancer(audioSessionId)
        booster?.apply {
            this@VolumeBooster.enabled
            setTargetGain(3000)
        }

    }

}
```

and it's plugged to player like this:
```kotlin
volumeBooster = VolumeBooster(boostEnabled)
player.audioComponent?.addAudioListener(volumeBooster)
```

But this also does not work - the result is that track in initially boosted for second or two (but not always) and  then volume returns to normal level.  Not sure why this is happening.

So I'd welcome any ideas, experiences in this area, as it's hard to find any reliable information. Thanks.

**Comment by izderadicka** [comment]
Any ideas anybody?  I'm stuck on what I described above. Thanks

**Comment by andrewlewis** [comment]
Regarding using audio processing for this: #3657 is about amplifying quiet sources rather than increasing volume beyond "normal limits" so perhaps not relevant to what you're trying to do. I don't think the bit depth of the PCM audio is going to make a difference to the audio volume. If your audio is already at full volume I wonder if you can do a non-linear transformation that still boosts volume for quite sections, but this may cause distortion!

For the loudness enhancer approach: in the code snippet above does the new `LoudnessEnhancer` actually get stored in the field? I vaguely recall a problem when trying to use audio effects previously where the effect was getting garbage collected unless I kept a reference to it.

**Comment by izderadicka** [comment]
@andrewlewis - Thanks that might be it! I did not notice that I used local var instead of field. Will check.

**Comment by izderadicka** [comment]
@andrewlewis - this was it - thanks a million. What a stupid error, I indeed wantedit  to be field of my class, just put there val by mistake and was it. Poor `LoudnessEnhancer` got shredded. I updated the code above to correct one, if someone in future has similar question.
