### ISSUE TITLE
Unexpectedly large number of "finalize() timed out after xx seconds" crash while playing video ads with ExoPlayer

### ISSUE THREAD

**Issue by crashTestGitHub** [google/ExoPlayer#5284]
I'm using the Google Mobile Ads SDK in my Android apps to request and display interstitial ads. The ads SDK is using ExoPlayer for video playback. Recently I've noticed an unexpectedly large number of this crash: http://crashes.to/s/9f68c47e186 . 

This "finalize() timeout" crash is a well-known issue on Android (explained here https://stackoverflow.com/questions/24021609/how-to-handle-java-util-concurrent-timeoutexception-android-os-binderproxy-fin ). While the issue itself is hard to fix and can only be mitigated, its number is closely related to Java Heap memory usage. Frequent memory allocation on Java Heap, and hence frequent GCs, will result in larger number of this crash. Based on limited frequency of ad-show activities in my apps compared to number of this crash, I believe ad video playback does bring an extensive pressure on memory.

Could you please give me more information on pattern of memory usage of ExoPlayer (eg. pattern of memory allocation in the video decoder) to start an investigation on this issue?

**Comment by andrewlewis** [comment]
Looking at the error report, in particular `com.google.android.gms.ads.internal.webview.v.finalize() timed out after 20 seconds` and the frames under `com.google.android.gms.ads.exoplayer1` I think this is a bug in the ads SDK and not ExoPlayer.

I'm going to close this now as I don't think going through details of memory allocation is going to be an efficient way to resolve the issue, so this isn't really actionable for us. However, I have filed an [internal issue: b/121304125] and will update here if/when I hear back.

**Comment by andrewlewis** [comment]
The fix for this is being rolled out gradually at the moment.
