### ISSUE TITLE
DASH YouTube Live stream stops after 5 seconds

### ISSUE THREAD

**Issue by adrixgc** [google/ExoPlayer#5285]
### Issue description
ExoPlayer 2.9.2 stops after playing 5 seconds in YouTuve live video

### Reproduction steps
Using the ExoPlayer demo app, change the media.exolist.json "YouTube DASH" first link (Google Glass) to the following url:
https://manifest.googlevideo.com/api/manifest/dash/ei/HnMbXJawLJG_VKu7o8AI/id/gld7L9HSHzI.1/gcr/es/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/ipbits/0/pacing/0/expire/1545324414/source/yt_live_broadcast/playlist_type/DVR/signature/105787E0D1BBC8D3903B925F382DF29EC4C942E2.23899A7DAF5FD6BE26479B6935E3FE3EBEDA0B15/key/yt6/ip/195.235.15.200/sparams/as%2Cei%2Cgcr%2Cid%2Cip%2Cipbits%2Citag%2Cplaylist_type%2Crequiressl%2Csource%2Cexpire/requiressl/yes/itag/0

The video plays for 5 seconds, after that, it stops. If you click on Play button again, it plays the next 5 seconds, but again, it stops.
It happens in my implementation of ExoPlayer as well as in the Demo app provided by ExoPlayer team. I've also tried with different YouTube Live videos and it happens the same with all of them. Perfectly working with regular videos (not Live ones).

**Comment by ojw28** [comment]
The manifest (in particular the way it updates) isn't valid.

**Comment by adrixgc** [comment]
Any idea on how to overcome this issue? YouTube native app is able to reproduce the video seamlessly with this same MPD file.

**Comment by ojw28** [comment]
Do you have a legitimate use case? My understanding is that YouTube only provides streams for its own clients.
