### ISSUE TITLE
Audio and video asynchrony on Android L

### ISSUE THREAD

**Issue by joechan-cq** [google/ExoPlayer#5286]
### Issue description(the same as [issue](https://github.com/google/ExoPlayer/issues/3368))
On Android L, video is frozen with the later frame but audio is playing asynchrony. when the position of audio is equal to the position of the video, the video resumes.

Above Android L, it's ok.

### Reproduction steps
play video in a normal activity, then pause the video and touch home button to return to Mobile Launcher App, and then resume the app. The video is paused, but you can find that the frame bitmap is not matched with the frame when you paused the video. after click to play the video, the audio plays normally, but the video is frozen.

### Version of ExoPlayer being used
2.8.3

### Device(s) and version(s) of Android being used
MX5 or other Android L devices.

### A full bug report captured from the device
I uploaded my screen record video.
[device-2018-12-21-095202.mp4.zip](https://github.com/google/ExoPlayer/files/2701202/device-2018-12-21-095202.mp4.zip)

**Comment by erdemguven** [comment]
I tried on Nexus 6 Android L using the latest ExoPlayer and couldn't reproduce the issue. Could you try the latest ExoPlayer version and let us know the result. It can be a device specific issue.

**Comment by joechan-cq** [comment]
@erdemguven I clone the Demo Application with the newest version(2.9.4), and I found the code
![image](https://user-images.githubusercontent.com/9456005/51966013-47d7b200-24a6-11e9-81ef-49422b03c47f.png)

So if below Api 23, it will release the player and reInit when it resumed. If you note the code that in the screenshot, just pause the video before making the app background, you can produce the issue.

**Comment by erdemguven** [comment]
Yes, I can reproduce the issue when that code is deleted but obviously the code is there for a reason :) Probably you should copy the same code into your app.

**Comment by joechan-cq** [comment]
Yes, I have done this as what you say. Thanks for supporting.
