### ISSUE TITLE
Video buffers ahead of time in demo app, but very slow buffer in my app (Jellybean)?

### ISSUE THREAD

**Issue by marcochin** [google/ExoPlayer#5287]
So when an hls video or any video is playing, the video should buffer ahead of time and when playback position catches up to the buffer position the video should buffer some more. This is observed in the demo app with the same hls stream, but in my app once the the playback position catches the buffer position it doesn't buffer anymore/has slow buffer, making the video enter the buffering state frequently.

For example: With a 1 minute video, the demo app will buffer up to the 45 second mark before waiting for the playback position to catch up. In my app the video only buffers to the 10 second mark and once the playback pos reaches close to the 10 sec mark it doesnt buffer anymore.

This is happening on Google Nexus Jellybean 4.1.1. As I said this only happens in my app, the demo app seems to buffer correctly. 
Also my app seems to buffer correctly on the Google Pixel.

Does anyone have clues as to why this may be happening?

This is how im creating the player.
```
mExoPlayer = ExoPlayerFactory.newSimpleInstance(mContext);
mExoPlayer.addListener(mPlaybackEventListener);
mExoPlayer.addVideoListener(mVideoListener);

MediaSource mediaSource = MediaUtils.getMediaSource(mContext, mVideoSource);
mExoPlayer.prepare(mediaSource);
mExoPlayer.setPlayWhenReady(true);

public MediaSource getMediaSource(Context context, VideoSource videoSource){
        String type = videoSource.getType();
        switch (type) {
            case VideoSource.TYPE_DASH:
                return new DashMediaSource.Factory(buildDataSourceFactory(context))
                        .createMediaSource(Uri.parse(videoSource.getUrl()));

            case VideoSource.TYPE_SS:
                return new SsMediaSource.Factory(buildDataSourceFactory(context))
                        .createMediaSource(Uri.parse(videoSource.getUrl()));

            case VideoSource.TYPE_HLS:
                return new HlsMediaSource.Factory(buildDataSourceFactory(context))
                        .setAllowChunklessPreparation(true)
                        .createMediaSource(Uri.parse(videoSource.getUrl()));

            case VideoSource.TYPE_OTHER: // Used for MP4 files
                return new ExtractorMediaSource.Factory(buildDataSourceFactory(context))
                        .createMediaSource(Uri.parse(videoSource.getUrl()));

            default:
                throw new IllegalStateException("Unsupported type: " + type);
        }

private DataSource.Factory buildDataSourceFactory(Context context){
        // Produces DataSource instances through which media data is downloaded.
        return new DefaultDataSourceFactory(context, buildHttpDataSourceFactory(context));
}

private HttpDataSource.Factory buildHttpDataSourceFactory(Context context){
        // Need HttpDataSourceFactory so we can have crossProtocolRedirect -> http to https and vice versa.
        return new DefaultHttpDataSourceFactory(
                context.getString(R.string.app_name),
                DefaultHttpDataSource.DEFAULT_CONNECT_TIMEOUT_MILLIS,
                DefaultHttpDataSource.DEFAULT_READ_TIMEOUT_MILLIS,
                true);
}
```

**EDIT:** I think how im creating the player is fine. There something in my app that is causing exoplayer to have reduced performance.

### Version of ExoPlayer being used
2.9.2

### Device(s) and version(s) of Android being used
Google Nexus Jellybean 4.1.1

**Comment by erdemguven** [comment]
Sorry, we can't help with this as it doesn't happen on the demo app.
