### ISSUE TITLE
Blue screen on android box

### ISSUE THREAD

**Issue by SystemRestored** [google/ExoPlayer#5290]
Hello I am using exoplayer 2.7.2 and currently facing some issues in android box AlfawiseA8   oreo 8.1
Screen coming blue layer on playing but its gone while the control view is open. I cant figure out the issue can anyone help? I am using default exoplayer demoapp code. 
https://tinypng.com/web/output/mtacqwc0j33p5abzjtjxgekyvg6jh6h6/bluescreen.jpg

**Comment by erdemguven** [comment]
Do you mean video appears normal when the control view is visible? 
Does the problem occurs on all streams? If not please specify the stream name.
Also please provide a bug report:
### A full bug report captured from the device
Capture a full bug report using "adb bugreport". Output from "adb logcat" or a
log snippet is NOT sufficient. Please attach the captured bug report as a file.
If you don't wish to post it publicly, please submit the issue, then email the
bug report to dev.exoplayer@gmail.com using a subject in the format
"Issue #1234".

**Comment by SystemRestored** [comment]
Its happening to every streams on that device. Sample video: https://www.youtube.com/watch?v=lsYJD0CLx-w   but other app having no issues.

**Comment by erdemguven** [comment]
Does this happen on unmodified ExoPlayer demo application?

**Comment by SystemRestored** [comment]
yes on demo app too...

**Comment by SystemRestored** [comment]
The issue is also there in exoplayer 2.9.3 user reported on AlfawiseA8

**Comment by SystemRestored** [comment]
update: My friend using same exoplayer version and he is using his custom layout and exoplayer activity code he has no issue. I just gave the demo application code for testing without any modification and the issue persists. Seems this is due to some layout issue in demo application codes. check please

**Comment by SystemRestored** [comment]
I am now using simpleexoplayer view and the issue is resolved. It seems the focus color of exoplayer controls (blue) is somehow overlapping on those devices.
