### ISSUE TITLE
Infinite Buffering when the first initialization is with live content

### ISSUE THREAD

**Issue by gerardiandrea** [google/ExoPlayer#5292]
### Issue description

If I try to play a .m3u8 content the player stays in buffering state, but if I play a .mp4 content and then try to play the same .m3u8 content it plays correctly.

I have this bug with the ExoPlayer version > 2.8.4 but with the 2.8.4 I don't have this problem

**Comment by erdemguven** [comment]
Have you tried to play the same content using ExoPlayer demo app. If the same thing happens using the demo app, please provide a link to test content:
Provide a link to media that reproduces the issue. If you don't wish to post it
publicly, please submit the issue, then email the link to
dev.exoplayer@gmail.com using a subject in the format "Issue #1234".

**Comment by gerardiandrea** [comment]
Thanks, I have the same problem with the ExoPlayer demo app. It is worked only after a few minutes of buffering.
I have send to email the test url

**Comment by AquilesCanta** [comment]
It seems to me that you need to align the EXT-X-PROGRAM-DATE-TIME tags across variants, as per [spec](https://tools.ietf.org/html/rfc8216#section-6.2.4).
