### ISSUE TITLE
AndroidTV STB : Incorrect volume in tunneling mode

### ISSUE THREAD

**Issue by Arayldan** [google/ExoPlayer#5295]
### Issue description
When I play a live DASH stream in tunneling mode on an AndroidTV STB, it always ignores the STB volume (i.e. plays at 100% volume) until I increase or decrease the STB volume. Then the STB volume will be ignored again after a few seconds or a pause/resume.

### Reproduction steps
1. Add tunneling in the ExoPlayer demo app.
2. Set your STB volume to around 5%.
3. Play the DASH live stream. It's played at maximum volume (directly scaled to the TV volume).
4. Increase or decrease the STB volume. The volume is scaled back to the Android volume.
5. If you pause/play the stream or after a few seconds, the sound will scale back to the TV volume (i.e. 100% volume on the STB).

### Link to test content
Sent to dev.exoplayer@gmail.com.

### Version of ExoPlayer being used
2.9.3

### Device(s) and version(s) of Android being used
EBoxTv diw387eb (SoC: Broadcom BCM7271)
Android 7.1.1

### A full bug report captured from the device
Sent to dev.exoplayer@gmail.com.

**Comment by erdemguven** [comment]
Does it just happen for live DASH content but not for any other type of content?

**Comment by Arayldan** [comment]
It also happens for non-live DASH content. For example : 
```
{
    "name": "Angel One DASH Widevine",
    "uri": "https://storage.googleapis.com/shaka-demo-assets/angel-one-widevine/dash.mpd",
    "drm_scheme": "widevine",
    "drm_license_url": "https://cwip-shaka-proxy.appspot.com/no_auth"
}
```

**Comment by andrewlewis** [comment]
Can you reproduce this on any other devices when using video tunneling? It sounds like a device-specific issue that would need to be reported to and fixed by Broadcom, especially if the device has a notion of volume that isn't controlled by the Android OS.

**Comment by Arayldan** [comment]
We tested on other devices (Nvidia Shield, Xiaomi Mi Box, etc) but they don't support tunneling.
Do you have a list of devices with tunneling codecs ?

**Comment by Arayldan** [comment]
We weren't able to reproduce that issue on another device with tunneling support (Amino Amigo 7X).
It seems to be device specific.
