### ISSUE TITLE
M3u8 failed to play

### ISSUE THREAD

**Issue by HappyGhostz** [google/ExoPlayer#5296]
Issue description
exo demo can not play my hls live channel.but I can play it  on my cumputer.

Reproduction steps
add a source:`
http://media-ali.wanmen.org/1cf514ed-1f5c-4dfe-8b06-1ac9141cd78d_mobile_low.m3u8?sign=3ef64a296ea2c130cd63ef0c4a3f4a55&t=5c1cd759&r=33ffd0ec907cee57d8fff8fe9de72fb2
`
Version of ExoPlayer being used
2.9.1

**Comment by HappyGhostz** [comment]
ExoPlaybackException:com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 301

**Comment by erdemguven** [comment]
You need to set allowCrossProtocolRedirects to true while creating DefaultHttpDataSourceFactory. For the demo app, you can change the buildHttpDataSourceFactory in DemoApplication.java to:
```
  public HttpDataSource.Factory buildHttpDataSourceFactory() {
    return new DefaultHttpDataSourceFactory(userAgent, null, DefaultHttpDataSource.DEFAULT_CONNECT_TIMEOUT_MILLIS,
            DefaultHttpDataSource.DEFAULT_READ_TIMEOUT_MILLIS, true);
  }
```

**Comment by HappyGhostz** [comment]
thank you
