### ISSUE TITLE
Failed to resolve: support-media-compat

### ISSUE THREAD

**Issue by RichardDivid** [google/ExoPlayer#5297]
when i add dependency of exoplayer,it occur this error,please help me how to resolve it,thank you.

**Comment by dev-graduan** [comment]
I've also got this error, any help will be appreciated

**Comment by dev-graduan** [comment]
I managed to solved it by put google() dependencies in first order

```
buildscript {
    repositories {
        google()
        jcenter()
        maven {
            url 'https://maven.fabric.io/public'
        }
    }
```

```
allprojects {
    repositories {
        google()
        jcenter()
        maven { url "https://jitpack.io" }
    }
}
```

**Comment by RichardDivid** [comment]
> I managed to solved it by put google() dependencies in first order
> 
> ```
> buildscript {
>     repositories {
>         google()
>         jcenter()
>         maven {
>             url 'https://maven.fabric.io/public'
>         }
>     }
> ```
> ```
> allprojects {
>     repositories {
>         google()
>         jcenter()
>         maven { url "https://jitpack.io" }
>     }
> }
> ```

thank you very much,it's really can resolved it

**Comment by AquilesCanta** [comment]
I assume there is no need to keep this open. Please let me know otherwise.

**Comment by Bartoloni** [comment]
this is a valid solution :) thank you.
