### ISSUE TITLE
Player will keep downloading first TS chunk if first chunk doesn't have any key frame

### ISSUE THREAD

**Issue by b95505017** [google/ExoPlayer#530]
Here is an example:
http://130.211.242.171/239955_back/video/1433828834chunklist.m3u8

In r1.2.4, player can play this HLS well, but later version of player.
Player will keep downloading first TS, state will stuck at preparing. Is there a way to follow old version's player behavior?

Thanks!

**Comment by ojw28** [comment]
Can you confirm that changing this line:
https://github.com/google/ExoPlayer/blob/dev/library/src/main/java/com/google/android/exoplayer/hls/HlsSampleSource.java#L365

To:

```if (enabledTrackCount > 0 || !prepared) {```

Fixes the issue for you?

**Comment by b95505017** [comment]
Yes, it works!

**Comment by b95505017** [comment]
Will this fix commit to dev branch? Thanks!

**Comment by ojw28** [comment]
We'll be merging a slightly different fix shortly.

**Comment by b95505017** [comment]
Thanks for fixing this so quickly!!
Hope we could get the new release with this fix ASAP.

**Comment by Arqu** [comment]
Just pull the dev branch, should work just fine. I actually just copied the few lines into my code by hand earlier, works like a charm.

**Comment by ojw28** [comment]
Yeah, best bet is just to copy the lines across by hand. We probably wont be doing another release for a couple of weeks.
