### ISSUE TITLE
ffmpeg extension, but compile failed.

### ISSUE THREAD

**Issue by ghost0906** [google/ExoPlayer#5305]
I want to use the extension of ffmpeg.
I did everything according README.md except the last step, cd "${FFMPEG_EXT_PATH}"/jni && \
${NDK_PATH}/ndk-build APP_ABI="armeabi-v7a arm64-v8a x86" -j4. 
The error message as below:
mkdir: cannot create directory `/libs': Permission denied
[armeabi] Prebuilt       : libavcodec.so <= ffmpeg/android-libs/armeabi/

Who can help me ?

**Comment by andrewlewis** [comment]
The `libs` directory should be under the ExoPlayer checkout in `extensions/ffmpeg/src/main/libs`. Please check you are running the command from the right place and have followed all of the steps in the readme carefully.

**Comment by ghost0906** [comment]
I tried all of the steps in the readme many times, but it still shows the same error:
mkdir: cannot create directory `/libs': Permission denied
make: *** [/libs/armeabi-v7a] Error 1
make: *** Waiting for unfinished jobs....
[armeabi-v7a] Prebuilt       : libavutil.so <= jni/ffmpeg/android-libs/armeabi-v7a/

The Exoplayer version is 2.6.0, I download the zip from the website and unzip it on my linux server.
Is anything wrong with my project？

**Comment by ghost0906** [comment]
I tried all of the steps in the readme many times, but it still shows the same error:
mkdir: cannot create directory `/libs': Permission denied
make: *** [/libs/armeabi-v7a] Error 1
make: *** Waiting for unfinished jobs....
[armeabi-v7a] Prebuilt       : libavutil.so <= jni/ffmpeg/android-libs/armeabi-v7a/

The Exoplayer version is 2.6.0, I download the zip from the website and unzip it on my linux server.
Is anything wrong with my project？

**Comment by andrewlewis** [comment]
I wonder if the shell used on your server is incompatible with the instructions. Could you try running `bash` first?
