### ISSUE TITLE
"Playback Notifications with ExoPlayer" Medium Article is not Working

### ISSUE THREAD

**Issue by lobothijau** [google/ExoPlayer#5306]
I use ExoPlayer in my project and would like to add a notification with playback. I'm following this medium article https://medium.com/google-exoplayer/playback-notifications-with-exoplayer-a2f1a18cf93b but got stuck in creating the `DescriptionAdapter`. 

![screenshot from 2018-12-24 22-11-24](https://user-images.githubusercontent.com/34962330/50402389-e64a6680-07c8-11e9-9368-39172e2f1c94.png)

It seems that the code structure is changing from MediaDescriptionAdapter. How can I rewrite the adapter to make the code example works? Thank you in advance.

**Comment by ojw28** [comment]
I don't think the structure has changed. I think the methods in red are application specific methods that you need to implement yourself (or do something equivalent).
