### ISSUE TITLE
AudioTrack-JNI: audioTrack continuously zero data counter

### ISSUE THREAD

**Issue by sergejsha** [google/ExoPlayer#5308]
After migration from `v.2.8.4` to `v.2.9.3` playback of some mp3-files causes appearance of the following two lines in logcat repeatedly:

```
2018-12-24 18:20:00.368 20073-20531/de.halfbit.a3.debug I/AudioTrack-JNI: audioTrack continuously zero data counter >= 10, send pause/stop state to pg, counter: 0
2018-12-24 18:20:00.428 20073-20531/de.halfbit.a3.debug I/AudioTrack-JNI: audioTrack send start state to pg
```

There are no hearable issues with playback and no exceptions, just those two lines spamming the logcat output. Is this anything known? Is this anything to be fixed? Should I maybe apply some special configuration to ExoPlayer to get rid of those messages?

[ExoPlayerLib/2.9.3] [HWFRD, FRD-L09, HUAWEI, 24]
Android 7.0

**Comment by ojw28** [comment]
Given there are no audible issues, I doubt there's anything actually wrong here. It's likely just unintentional log spam. I can't find "continuously zero data counter' or "send start state to pg" anywhere in AOSP Android, so it's likely it's something Huawei have added. There's nothing we can really do about it, if so. If you think the logging is coming from AOSP Android or anything under our control, please point us to where you think it's coming from, and we'll look at removing it.

Closing on the assumption this is Huawei log spam and there's nothing actionable on our side.
