### ISSUE TITLE
Some problems for ExoPlayer play avi/rmvb video.

### ISSUE THREAD

**Issue by ghost0906** [google/ExoPlayer#5309]
I built a new instance of extractor with native ffmpeg to play the unsupported  format video such as avi and rmvb. setDataSource to native ffmpeg, and get demuxed packets form native.
But there are some questions:
1. The avi video packet has no pts, so the exoplayer can't sync and output the images, Should I need to change the pts in native?
2. Exoplayer plays some video with Mp3Extractor  in **selectExtractor** before my Extractor. The video has audio in mp3 format. My ffmpeg extractor is the last one in extractors. I don't want to change the order. What should I do to make it not happen?
3. The rmvb video has audio in **cook** codec and video in **rv40** codec, I can't find the corresponding mimetype in MimeTypes, which the sampleMimeType in  **createVideoSampleFormat** .
Does it means the mediacodec can't decoder rmvb or rv video?

Who can help me?

**Comment by ojw28** [comment]
For (1) - Implementing `Extractor` requires that you provide a (sensible) timestamp with each sample. How you do that in your own custom `Extractor` implementation is beyond the scope of this issue tracker.

For (2) - It's right that extractors should be ordered with those likely to produce false positives being further down the list. So I think you should change the order.

For (3) - All Android devices are required to support certain codecs. As documented [here](https://developer.android.com/guide/topics/media/media-formats#core). Device manufacturers may optionally support additional codecs if they wish to do so. The codecs you mention are not required to be supported. Furthermore, I very much doubt any manufacturer chooses to support them as optional extras.

**Comment by ghost0906** [comment]
Thanks.
