### ISSUE TITLE
How to switch between the original song and the accompaniment like a karaoke

### ISSUE THREAD

**Issue by RichardDivid** [google/ExoPlayer#5316]
now i have a demand,use exoplayer to playback mkv file and it has two audio track, one audio track with original and the other is accompanient, it‘s like karaoke,’i will use a button to switch between the original song and the accompaniment, please help me,thank you very much

**Comment by AquilesCanta** [comment]
There are a few ways to do this. As an initial approach, I would try using track selection. Note that in this case the transition would not be seamless. It is not clear to me whether this would be an issue. You can play the media in the demo app to see what the final result would look like (press the audio button at the top to change the selected audio track).

If you want to achieve a more smooth transition, you will most likely need to use [AudioProcessors](https://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/audio/AudioProcessor.html). For example, you could pack each track in a different channel, and then route the correct one to the sink according to the button state. 

If _channel-splitting_ is not an option, then you'll have to create one Audio Renderer per track, and correctly map each audio track to an audio renderer (see [MappingTrackSelector](https://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/trackselection/MappingTrackSelector.html)). There is some relevant info in #4261 (also look around in the issue tracker for this). You will eventually need to select which samples get output to the audio sink according to your selected track, and the best way I can think of is using an AudioProcessor.

@andrewlewis might be able to add some insight.

**Comment by andrewlewis** [comment]
That all sounds right to me. If you can transcode the media to put the different audio tracks in separate channels of the same track, I think using an audio processor based on [ChannelMappingAudioProcessor](https://github.com/google/ExoPlayer/blob/e87e231/library/core/src/main/java/com/google/android/exoplayer2/audio/ChannelMappingAudioProcessor.java) would give good results. You'd need to fork this to add support for setting the channel map from your application's thread (at the moment it assumes the map is set from the playback thread).
