### ISSUE TITLE
How to get single Local video resource path with all downloaded chunks by Exo Downloader?

### ISSUE THREAD

**Issue by ashishbhandari** [google/ExoPlayer#5318]
I am trying to playback all cache downloaded contents which is dowloaded in .exo format in device memory.

I need to get a local path of any previously downloaded video using exoplayer offline lib. I can not use the mediaSource instance used by the downloader because I need to play downloaded chunks in some other third party player which only accepts and understand local video resource file.

As I can see CacheDataSource read files from cache using the same Url as a key. CacheDataSource returns the data from cache if the file is caches/downloaded which can work easily on ExoPlayer. But problem is that I can not pass this mediaSource object to other player as they wont be able to understand that this needs to download from offline or online. So I would be required single local video path where all chunks are available.

So it is possible to achieve the same using Exo? or any further future plan.

**Comment by ojw28** [comment]
ExoPlayer's caching functionality does not support this use case (i.e. providing a single file path for a piece of downloaded content). We don't even make any strong guarantees about the format of cache files, or how many files a piece of content might be fragmented across.

The only officially supported way of reading cached data back is to do so through ExoPlayer's own components, such as `CacheDataSource`. Note that this does allow applications to do various things to expose the cached data to other processes. For example it would be possible to write a `ContentProvider` that allows another process to read the cached data. I'm not sure whether that would be sufficient for your use case.

If not, you'll most likely just have to write your own downloading functionality instead. Sorry!
