### ISSUE TITLE
Playing mp4 video - for android from local raw/assets folder

### ISSUE THREAD

**Issue by sasindroid** [google/ExoPlayer#532]
Hello, I am trying to play an mp4 file using exoplayer. I have the mp4 file on my android "raw" folder and it can be moved to "assets" folder if needed. 

I have tried modifying the demo app - "SampleChooserAcitivity" as below:

		sampleAdapter.add((Object) new Sample("My Video", path,
				DemoUtil.TYPE_MP4));

I have tried the variable "path" with the below options and none of them work for me.

Option 1 (from assets folder)
		path = "file:///video.mp4";

Option 2 (from assets folder)
		path = "file:///android_asset/video.mp4";

Option 3 (from raw folder)
                path = "android.resource://" + getPackageName() + "/" + R.raw.video;

Please suggest. Thanks!

**Comment by ojw28** [comment]
See the documentation for: http://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer/upstream/DefaultUriDataSource.html

**Comment by sasindroid** [comment]
Great, thanks. Works like a charm.

**Comment by zsoltboldizsar** [comment]
@sasindroid have you managed to play a video that's located in the raw folder?

**Comment by sasindroid** [comment]
@zsoltboldizsar - yes I did. 
The documentation @ http://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer/upstream/DefaultUriDataSource.html details it.

**Comment by zsoltboldizsar** [comment]
As you can see the reference above, one of the owners told me to move the files to assets instead. How did you managed to get them from res/raw folder anyway?

**Comment by sasindroid** [comment]
Oops, I meant "assets" folder. I did some work on playing the video from "raw" initially, but no luck.
I had to move to the "assets" folder to use Exo.

**Comment by zsoltboldizsar** [comment]
Well yeah. I also moved my files to assets. Thanks for your response anyway.

**Comment by yuvaraj119** [comment]
http://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer/upstream/DefaultUriDataSource.html  this link is not working now

**Comment by nguyentuanviet** [comment]
the link is not working...please update it!

**Comment by ojw28** [comment]
http://google.github.io/ExoPlayer/doc/reference/index.html?com/google/android/exoplayer2/upstream/DefaultDataSource.html

Note - In general just go to http://google.github.io/ExoPlayer/doc/reference/ if you can't find documentation for a class. It's all there and pretty easy to navigate.
