### ISSUE TITLE
ExoPlayer can't play particular m4a files

### ISSUE THREAD

**Issue by davidaik** [google/ExoPlayer#5320]
I am building an offline music player app using ExoPlayer and things are working fine. It can play all m4a files except two particular files that I have.

https://www.dropbox.com/s/mxxwarmf43j5pjc/Unlike%20Pluto%20-%20Someone%20New.m4a?dl=0
https://www.dropbox.com/s/zy6rbllusz1j0r2/Vanic%20-%20Hypnotic.m4a?dl=0

These files can be played on Google Play Music and other music player apps. It also plays on an older version of my app that implements `MediaPlayer`.

When I try to **prepare** these files in my app using `SimpleExoPlayer`, `onPlayerStateChanged()` is immediately called and the playback state is `Player.STATE_ENDED`. Sometimes, the state is `Player.STATE_READY`, but `ExoPlayer.getDuration()` gives me 0 and `ExoPlayer.getCurrentPosition()` updates as if the file is normally playing but there is no sound.

What's special about these files is that when I was playing these files in another music player app which had an automatic artwork downloader, the app downloaded and set artwork to these files. I think that the change in metadata done at that time is what makes these files unplayable in ExoPlayer.

I suspect that ExoPlayer is not able to handle a specific "configuration" of metadata that is found in these files. I hope that it is investigated to make ExoPlayer more reliable.

**Comment by AquilesCanta** [comment]
We are failing to sniff the file as a fragmented mp4 file. The reason is that the meta box is big, and makes us exceed the sniffing size before we find evidence that the file is fragmented. I will update this issue once I have an update on this.

**Comment by davidaik** [comment]
Thank you. I was just considering moving back to MediaPlayer, but I'll be sticking around and hopefully this bug gets fixed soon.

**Comment by ojw28** [comment]
Fixed in `dev-v2`

**Comment by davidaik** [comment]
Thanks, it works.
