### ISSUE TITLE
How to force play the current m3u8 line in the main m3u8 playList

### ISSUE THREAD

**Issue by xiaoyepadzhang** [google/ExoPlayer#5321]
This issue is not related with any devices, just a usage of exoplayer, Thank you.

My demand is that , I want exoplayer  play the current m3u8(quality) file in the main playList at first loading and switch the quality just by myself.
For example that I have a main m3u8 file like:

`#EXTM3U
#EXT-X-STREAM-INF:BANDWIDTH=451858,AVERAGEBANDWIDTH=135401,CODECS="avc1.42001f,mp4a.40.2",NAME="540p"`
`https://pathxxxx`
`#EXT-X-STREAM-INF:BANDWIDTH=656684,AVERAGEBANDWIDTH=169841,CODECS="avc1.4d001f,mp4a.40.2",NAME="720p"`
`https://pathxxxx2`

when I start play the video, exoplayer will auto switch to the "720P" m3u8, because of the setting of
 `TrackSelection.Factory videoTrackSelectionFactory =
          new AdaptiveTrackSelection.Factory(BANDWIDTH_METER);`
     `mTrackSelector = new DefaultTrackSelector(videoTrackSelectionFactory);`
      `mLoadControl = new CustomLoadControl();`
     ` player = ExoPlayerFactory.newSimpleInstance(getContext(), mTrackSelector, mLoadControl);`
But I don't want Exoplayer auto switch the quality ,  I want it can switch the quality by myself,
I just know the execute code :
`private void override(TrackGroupArray groups, int trackIndex){
    ParametersBuilder parametersBuilder = mTrackSelector.buildUponParameters();`
   `SelectionOverride override = new SelectionOverride(0, trackIndex);`
   `parametersBuilder.setSelectionOverride(0, groups, override);`
   `mTrackSelector.setParameters(parametersBuilder);`
`}`

I try to override the method  `selectTracks` in `DefaultTrackSelector.java` , But the method is `final`, 
So I copy of `DefaultTrackSelector.java` and remove the `final` and overide the medthod. Before call `super.selectTracks()`, I `setParameters` to the track index that I want.  But if I set the track index > 0, I finded that exoplayer will download the fist track , and then download the current track that I setted,

My question is, How can I find the best time to set override parameters(I must get the MappedTrackInfo to set with it), and let the Exoplayer don't  download any unnecessary quality file.

Thanks!!

**Comment by xiaoyepadzhang** [comment]
@ojw28 can you help me?

**Comment by ojw28** [comment]
Please don't ping issues less than a day after you've filed them. If you've filed an issue we've seen it, and we'll answer it when we have a chance.

**Comment by tonihei** [comment]
ExoPlayer automatically chooses the best quality based on the current network speed estimate. If you want to force the lowest possible resolution you should set the `forceLowestBitrate` parameter of `DefaultTrackSelector`. If you want to switch to another quality later on, just change the parameters to something else.

**Comment by xiaoyepadzhang** [comment]
@tonihei I means that I just want exoplayer choose the quality that I told him.
For example, I want it start play the second quality(whatever the second quality is what), and never load the first quality(Infact now exoplayer will request the first quality always) or other quality except the second quality.
My Features is about manual control the quality not auto switch, How can I carry out it ?

**Comment by tonihei** [comment]
Can you describe in more detail what you are trying to achieve? Selecting things like the "second quality" sounds arbitrary from a player point of view and only makes sense if you already know how the qualities look like before loading the playlist.

`DefaultTrackSelector` also has other options to pre-define the selection, e.g. `maxVideoHeight` or `maxVideoBitrate`. If you want to disable automatic selection and only use the highest supported format according to your constraints, you can also set `forceHighestSupportedBitrate` to true.

**Comment by xiaoyepadzhang** [comment]
@tonihei 
I parse `Object manifest` params int `onTimelineChanged`  method, and I will get the main m3u8 list, and then get the `NAME="XXXp"` quality list(this is a agreement with out server), the list will display to the User to switch.

At first I will `setParameters(parametersBuilder)`(track == 0), And Exoplayer will play the first quality track and never auto switch(this is the result that I want)
But if a user back see a video that had manual switched the quality, I want the video to load with the record quality. So I use the same way, `setParameters(parametersBuilder)`(track > 0) at first, But  It will first load the fist track and then load the current track that I set(I found in Charles).

All the `setParameters(parametersBuilder)` action is execute after `selectTracks ` method in `DefaultTrackSelector ` is callback.

You said that use `maxVideoHeight ` or `maxVideoBitrate ` to  pre-define the selection. Actually I just know the bitrate that I want to force play at first, the bitrate is current, and will be any index in this video.

So I want to achieve:
1. Start loading just with the track that I told him.(never waste bandwidth)
2. Exoplayer can switch by manual all the time. 

Thank you very much.

**Comment by tonihei** [comment]
`HlsMediaSource` starts loading the first variant to figure out which formats are available. I think this may be what you are seeing. Can you try calling `setAllowChunklessPreparation(true)` on the `HlsMediaSource.Factory`? This will only read the formats from the master playlist if possible.

**Comment by xiaoyepadzhang** [comment]
@tonihei Thank you, I use`setAllowChunklessPreparation(true) ` solved the problem

**Comment by tonihei** [comment]
Closing as solved.
