### ISSUE TITLE
Fatal Exception: java.lang.InternalError Thread starting during runtime shutdown okhttp3.ConnectionPool.put

### ISSUE THREAD

**Issue by AliceZhuZhu** [google/ExoPlayer#5324]
Fatal Exception: java.lang.InternalError
Thread starting during runtime shutdown.

-----------------------
### Issue description
There was an error playing the video.
`private VideoView vvViewedDetail;`
..........
![image](https://user-images.githubusercontent.com/36066123/50534068-cffa2d00-0b71-11e9-8426-a84f49dd3944.png)

`implementation 'com.squareup.okhttp3:okhttp:3.10.0'
    implementation 'com.squareup.okio:okio:1.14.0'
    implementation 'com.devbrackets.android:exomedia:4.1.0'
    implementation 'com.google.android.exoplayer:extension-okhttp:2.7.3'`

### Device(s) and version(s) of Android being used
SM-N950U  android 8.0.0

### A full bug report captured from the device
```
Fatal Exception: java.lang.InternalError
Thread starting during runtime shutdown
java.lang.Thread.nativeCreate (Thread.java)
java.lang.Thread.start (Thread.java:733)
java.util.concurrent.ThreadPoolExecutor.addWorker (ThreadPoolExecutor.java:970)
java.util.concurrent.ThreadPoolExecutor.execute (ThreadPoolExecutor.java:1388)
okhttp3.ConnectionPool.put (SourceFile:153)
okhttp3.OkHttpClient$1.put (SourceFile:168)
okhttp3.internal.connection.StreamAllocation.findConnection (SourceFile:266)
okhttp3.internal.connection.StreamAllocation.findHealthyConnection (SourceFile:135)
okhttp3.internal.connection.StreamAllocation.newStream (SourceFile:114)
okhttp3.internal.connection.ConnectInterceptor.intercept (SourceFile:42)
okhttp3.internal.http.RealInterceptorChain.proceed (SourceFile:147)
okhttp3.internal.http.RealInterceptorChain.proceed (SourceFile:121)
okhttp3.internal.cache.CacheInterceptor.intercept (SourceFile:93)
okhttp3.internal.http.RealInterceptorChain.proceed (SourceFile:147)
okhttp3.internal.http.RealInterceptorChain.proceed (SourceFile:121)
okhttp3.internal.http.BridgeInterceptor.intercept (SourceFile:93)
okhttp3.internal.http.RealInterceptorChain.proceed (SourceFile:147)
okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept (SourceFile:126)
okhttp3.internal.http.RealInterceptorChain.proceed (SourceFile:147)
okhttp3.internal.http.RealInterceptorChain.proceed (SourceFile:121)
okhttp3.RealCall.getResponseWithInterceptorChain (SourceFile:200)
okhttp3.RealCall.execute (SourceFile:77)
com.google.android.exoplayer2.ext.okhttp.OkHttpDataSource.open (SourceFile:162)
com.google.android.exoplayer2.upstream.TeeDataSource.open (SourceFile:42)
com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource (SourceFile:372)
com.google.android.exoplayer2.upstream.cache.CacheDataSource.open (SourceFile:215)
com.google.android.exoplayer2.upstream.DefaultDataSource.open (SourceFile:147)
com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load (SourceFile:841)
com.google.android.exoplayer2.upstream.Loader$LoadTask.run (SourceFile:308)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1162)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:636)
java.lang.Thread.run (Thread.java:764)
```

Thanks for any suggestions!

**Comment by ojw28** [comment]
This doesn't really look like an ExoPlayer issue. I'd suggest you search on the OkHttp issue tracker; for example https://github.com/square/okhttp/issues/1153. There are also quite a lot of results for "Thread starting during runtime shutdown" on Google.

It seems like the application is shutting down anyway when this error occurs, so it's likely there's no user impact. If you're seeing it reported via Crashlytics or similar, you can probably safely ignore it. If you're able to reproduce it and see that it does have user impact, it would be good to understand what it is, and what the reproduction steps are.

Closing as answered for now, but feel free to post more information here if you have any.
