### ISSUE TITLE
[Question] How to mute and unmute programatically in Exoplayer.

### ISSUE THREAD

**Issue by SystemRestored** [google/ExoPlayer#5327]
Hello I am using the latest exoplayer 2.9.3
I want to implement a mute unmute button to it. I have achieved the mute portion, but while unmuting the sound goes to full , not in its previous position. can anyone tell me how to unmute to previous postion.

To mute I am using:
`audiomanager.adjustStreamVolume(AudioManager.STREAM_MUSIC, AudioManager.ADJUST_MUTE, 0);`

to unmute from above  tried:
`mAlramMAnager.adjustStreamVolume(AudioManager.STREAM_MUSIC, AudioManager.ADJUST_UNMUTE,0);`

but did not worked,

later I tried:

```
float currentvolume;
                currentvolume = player.getVolume();
                currentvolume = currentvolume*100;
                int volume = Math.round(currentvolume);
  mAlramMAnager.setStreamVolume(AudioManager.STREAM_MUSIC,
                        volume, 0);
```

It sets the value to full volume. Help me

**Comment by ojw28** [comment]
Using `AudioManager.adjustStreamVolume` doesn't sound right. Just adjust the volume directly on the player, using [`SimpleExoPlayer.setVolume`](https://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/SimpleExoPlayer.html#setVolume-float-).

**Comment by ojw28** [comment]
Closing as answered, but feel free to follow up here if you have further questions (there's no need to file a new issue).
