### ISSUE TITLE
DRM docs & code have different system requirements

### ISSUE THREAD

**Issue by cobarx** [google/ExoPlayer#5329]
### Issue description
The [DRM docs](https://google.github.io/ExoPlayer/drm.html) indicate that DRM is only supported on Android 4.4 and higher , however in the [demo app](https://github.com/google/ExoPlayer/blob/release-v2/demos/main/src/main/java/com/google/android/exoplayer2/demo/PlayerActivity.java#L379) the minimum version is 4.3. Issue #1330 indicates that Widevine modular will work on Nexus 5 devices running 4.3, so that may be the reason the code has that exemption.

This has caused some confusion in our implementation of [ExoPlayer DRM for react-native-video](https://github.com/react-native-community/react-native-video/pull/1382) about which versions we can support. It would be ideal to either update the demo code or add clarification to the DRM page.

### Version of ExoPlayer being used
2.9.3

**Comment by ojw28** [comment]
As you figured out, the reason for the discrepancy is that some Nexus devices got support in API level 18, but wider support was not required until API level 19.

Given there are very few such devices still in circulation (i.e. Nexus devices that have modular DRM support, and that are still running API level 18 as opposed to having received a subsequent update), it seems fine to update the demo app to check against 19, just to reduce confusion.

**Comment by ojw28** [comment]
Actually, I think it's better to leave it how it is. There's a difference between checking whether the `MediaDrm` API exists, and checking whether a specific content decryption module (CDM) can be accessed through it.

The API level check in the demo app is to establish whether the `MediaDrm` API exists before trying to use it. The documentation you refer to documents which CDMs you can expect to be accessible when you do this. So they're not referring to the same thing. The only point of confusion is why the demo app bothers on API level 18 given the documentation doesn't indicate that any CDMs can be expected. That's pretty easily answered though: OEMs were (and still are) free to put optional CDMs underneath `MediaDrm` prior to them being a requirement, and the Nexus devices having the Widevine CDM on API level 18 is an example of this.
