### ISSUE TITLE
switching between streams using default rendererbuilder getting exception

### ISSUE THREAD

**Issue by suresh777** [google/ExoPlayer#533]
I have set of downloaded song files,using default renderer builder i am playing song file,but when i switch fast between song files i am getting crash
06-10 13:30:11.388: E/NuCachedSource2(19352): source returned error -1, 1 retries left
06-10 13:30:14.394: E/NuCachedSource2(19352): source returned error -1, 0 retries left
06-10 13:30:14.418: E/ExoPlayerImplInternal(19352): Internal track renderer error.
06-10 13:30:14.418: E/ExoPlayerImplInternal(19352): com.google.android.exoplayer.ExoPlaybackException: java.io.IOException: Failed to instantiate extractor.
06-10 13:30:14.418: E/ExoPlayerImplInternal(19352): 	at com.google.android.exoplayer.MediaCodecTrackRenderer.doPrepare(MediaCodecTrackRenderer.java:223)
06-10 13:30:14.418: E/ExoPlayerImplInternal(19352): 	at com.google.android.exoplayer.TrackRenderer.prepare(TrackRenderer.java:115)
06-10 13:30:14.418: E/ExoPlayerImplInternal(19352): 	at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(ExoPlayerImplInternal.java:267)
06-10 13:30:14.418: E/ExoPlayerImplInternal(19352): 	at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:195)
06-10 13:30:14.418: E/ExoPlayerImplInternal(19352): 	at android.os.Handler.dispatchMessage(Handler.java:98)
06-10 13:30:14.418: E/ExoPlayerImplInternal(19352): 	at android.os.Looper.loop(Looper.java:135)
06-10 13:30:14.418: E/ExoPlayerImplInternal(19352): 	at android.os.HandlerThread.run(HandlerThread.java:61)
06-10 13:30:14.418: E/ExoPlayerImplInternal(19352): 	at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
06-10 13:30:14.418: E/ExoPlayerImplInternal(19352): Caused by: java.io.IOException: Failed to instantiate extractor.
06-10 13:30:14.418: E/ExoPlayerImplInternal(19352): 	at android.media.MediaExtractor.nativeSetDataSource(Native Method)
06-10 13:30:14.418: E/ExoPlayerImplInternal(19352): 	at android.media.MediaExtractor.setDataSource(MediaExtractor.java:143)
06-10 13:30:14.418: E/ExoPlayerImplInternal(19352): 	at android.media.MediaExtractor.setDataSource(MediaExtractor.java:117)
06-10 13:30:14.418: E/ExoPlayerImplInternal(19352): 	at com.google.android.exoplayer.source.FrameworkSampleExtractor.prepare(FrameworkSampleExtractor.java:104)
06-10 13:30:14.418: E/ExoPlayerImplInternal(19352): 	at com.google.android.exoplayer.source.DefaultSampleSource.prepare(DefaultSampleSource.java:63)
06-10 13:30:14.418: E/ExoPlayerImplInternal(19352): 	at com.google.android.exoplayer.MediaCodecTrackRenderer.doPrepare(MediaCodecTrackRenderer.java:218)

**Comment by ojw28** [comment]
Please see the documentation about FrameworkSampleSource and why it's deprecated. We're unable to fix issues such as this one. In most cases, you can use ExtractorSampleSource instead.

http://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer/FrameworkSampleSource.html
