### ISSUE TITLE
Seeking Issue

### ISSUE THREAD

**Issue by ranakhizar1556** [google/ExoPlayer#5331]
why 4k mkv file matroska file format is seekable in media player library but when i am trying to do this in exoplayer it is not seekable why if frame rate is not available for that video why media player is give seeking for that video and why exoplayer dont give this

**Comment by ojw28** [comment]
Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE). Closing the issue until complete information is provided.
