### ISSUE TITLE
Buffering issues with HTTP but more reliable buffer with HTTPS

### ISSUE THREAD

**Issue by marcochin** [google/ExoPlayer#5335]
### Issue description
I have a user who is having trouble with video streaming. I can't reproduce the issue on my side, but it seems with http:// links it'll buffer a bit and the video will play, but once the playback catches up the buffering progress, it won't buffer anymore. 

We tried switching http:// to https:// and most videos will play fine and buffer correctly, but not foolproof. Occasionally you'll encounter a video that won't buffer correctly.

In his bug report there may be some interesting logs, but don't know for certain of what is causing it. Maybe you guys can help me?

### Link to test content
Links in a separate email.

### Version of ExoPlayer being used
2.9.2

### Device(s) and version(s) of Android being used
Nvidia Shield Android 8.0

### A full bug report captured from the device
BugReport in a separate email.

**Comment by marcbaechinger** [comment]
I can not reproduce this behaviour either. When playing the URLs you sent with the demo app it just runs fine. It actually never catches up with the buffered data.  I tried on a very slow network as well and there the player behaves as expected. After a long buffering phase it plays a bit, then falls into buffering state again. But the app is responsive all the time.

What is the reported behaviour exactly? You wrote, "but once the playback catches up the buffering progress, it won't buffer anymore." I understand it does not load data anymore after the initial buffering.

The bug report does not show any network specific problems, except for some CroNet things but I think that's not your app.

Do you have a some more precise description of the faulty behaviour?
Do you know whether your user is trying on a mobile network which might be slow or shaky?
