### ISSUE TITLE
Offline download for mulltiple users

### ISSUE THREAD

**Issue by meenukrishnamurthy** [google/ExoPlayer#5337]
Hi, in my app i need to implement offline download for multiple users.I have used the code from your demo project.When i try to download the same video for multiple users its not happening.Can u help me out here.

**Comment by ojw28** [comment]
ExoPlayer doesn't know anything about users, so I don't see how this falls inside the scope of this issue tracker. ExoPlayer provides caching and downloading components that you could choose to share or have separate instances of per user, but the whole concept of multiple users and how you would do that is entirely the responsibility of the application developer and application code.
