### ISSUE TITLE
Playing mp4 video from assets

### ISSUE THREAD

**Issue by DionataFerraz** [google/ExoPlayer#5339]
I'm trying to use a video that is inside the assets directory, but I always take an exception 
 com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to assets://vid.mp4
```
ExtractorMediaSource.Factory(DefaultDataSourceFactory(context, BuildConfig.USER_AGENT_VALUE)).createMediaSource(Uri.parse("assets://vid.mp4"))
```

**Comment by andrewlewis** [comment]
Does `asset://...` work?

**Comment by marcbaechinger** [comment]
Or you need to prefix your path with android_asset. So for your example it would be:

file:///android_asset/vid.mp4

**Comment by DionataFerraz** [comment]
I've tried, but throws an exception that the file was not found
    com.google.android.exoplayer2.upstream.AssetDataSource$AssetDataSourceException: java.io.FileNotFoundException: 

package assets is inside the main, should it be somewhere else?

I put the package assets in the singular and also did not work, it throws the same exception above

I tried putting it in the package raw inside the res and it does not work either

i try 
```
ExtractorMediaSource.Factory(DefaultDataSourceFactory(context, BuildConfig.USER_AGENT_VALUE))
.createMediaSource(Uri.parse("android.resource://com.dionata.player.dev/raw/video.mp4"))
```

**Comment by DionataFerraz** [comment]
if I try with the Android VideoView I can play the video using that path
`android.resource://com.video.player.dev/raw/video`

I'm using version 2.9.3

**Comment by andrewlewis** [comment]
If it's stored as a resource rather than an asset then try `RawResourceDataSource.buildRawResourceUri(R.raw.video)`.

**Comment by DionataFerraz** [comment]
Thanks
I did it here and it worked.
```
ExtractorMediaSource.Factory(DefaultDataSourceFactory(context, BuildConfig.USER_AGENT_VALUE))
                .createMediaSource(RawResourceDataSource.buildRawResourceUri(R.raw.videog))
```

Thank you very much
