### ISSUE TITLE
How to use the alternative to set/get of audioStreamType ?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [google/ExoPlayer#5342]
Currently the getter&setter of "audioStreamType" is deprecated .

It says I should use `getAudioAttributes` , `setAudioAttributes` instead.

But I don't see it is talked about here and over the Internet. How should I use those?

For now, I've tried to just copy the code of the deprecated functions instead, so instead of the getter, I use this:

`    val currentAudioStreamType = Util.getStreamTypeForAudioUsage(audioAttributes.usage)
`
Seems to work fine.

However, for the setter, I tried this:

```
    @C.AudioUsage val usage = Util.getAudioUsageForStreamType(audioStreamType)
    @C.AudioContentType val contentType = Util.getAudioContentTypeForStreamType(audioStreamType)
    val audioAttributes = AudioAttributes.Builder().setUsage(usage).setContentType(contentType).build()
    setAudioAttributes(audioAttributes)
```

Yet now it says that "setAudioAttributes" is deprecated ... 
Here's a screenshot of this code:

```
fun SimpleExoPlayer.setAudioStreamTypeIfNeeded(@C.StreamType audioStreamType: Int) {
    val currentAudioStreamType = Util.getStreamTypeForAudioUsage(audioAttributes.usage)
    if (currentAudioStreamType == audioStreamType)
        return
    @C.AudioUsage val usage = Util.getAudioUsageForStreamType(audioStreamType)
    @C.AudioContentType val contentType = Util.getAudioContentTypeForStreamType(audioStreamType)
    val audioAttributes = AudioAttributes.Builder().setUsage(usage).setContentType(contentType).build()
    setAudioAttributes(audioAttributes)
}
```

![image](https://user-images.githubusercontent.com/5357526/50772633-21ec3280-1297-11e9-8b6e-4e56b4c49867.png)

How could it be? What is the correct way to set/get the audioStreamType?

**Comment by andrewlewis** [comment]
As documented on `setAudioAttributes(AudioAttributes audioAttributes)`, you should use `setAudioAttributes(AudioAttributes, boolean)` instead, passing in whether to handle audio focus as the boolean.

**Comment by AndroidDeveloperLB** [comment]
What about the getter?

**Comment by AndroidDeveloperLB** [comment]
And why are all of those deprecated anyway? Seems like they work well, easier to understand, and shorter...

**Comment by hosseiniSeyRo** [comment]
setAudioAttributes has only one parameter! why?

**Comment by andrewlewis** [comment]
@zoho1381 In the latest release 2.9.6 it takes two parameters [here](https://github.com/google/ExoPlayer/blob/r2.9.6/library/core/src/main/java/com/google/android/exoplayer2/Player.java#L120).
