### ISSUE TITLE
after player become STATE_IDLE, player.prepare() causes endless buffering

### ISSUE THREAD

**Issue by jy617lee** [google/ExoPlayer#5343]
I'm using 2.9.1v now. 
After player become idle (onPlayerStateChanged of AnalyticsListener is called and playbackState equals STATE_IDLE), I call player.prepare(). 
But this causes endles buffering.

Is this bug or there's other proper way to re-prepare idle player?

```
   @Override
    public void onPlayerStateChanged(AnalyticsListener.EventTime eventTime, boolean playWhenReady, int playbackState) {
        Log.d(TAG, "onPlayerStateChanged");
        switch (playbackState) {
            case STATE_IDLE: {
                Log.d(TAG, "state = STATE_IDLE");
                player.prepare(videosource);
                player.setPlayWhenReady(true);
                player.getPlaybackState();
                break;
            }
            case STATE_BUFFERING :{
                Log.d(TAG, "state = STATE_BUFFERING");
                break;
            }
        }
    }
```

**Comment by jy617lee** [comment]
additionally,
1. I added player.release() before player.prepare()
2. initialize new player in activity and start()

but neither of them works.. anyone can help?

**Comment by tonihei** [comment]
This exact code works fine for me in our demo app. 

I assume you want to restart playback after it failed? If so, you may see "constant buffering" because your media can't be played and is constantly failing.

The way I tested this is:
1. Enable airplane mode during playback
2. Wait until the player fails, changes to IDLE and re-prepares
3. Disable airplane mode again.

**Comment by jy617lee** [comment]
thank you @tonihei !!

but I don't want to restart playback after it failed. 
Player just normally plays the media at first, but after it goes to STATE_IDLE I cannot retrieve player. When I try to retrieve player after once player goes to STATE_IDLE, constant buffering comes even though media was played normally before it goes to STATE_IDLE.

**Comment by tonihei** [comment]
The player only changes to STATE_IDLE if playback failed or you explicitly call `player.stop`. One of these two events must have happened.

**Comment by jy617lee** [comment]
thank you @tonihei 
It was memory leak problem that makes player call STATE_IDLE!
