### ISSUE TITLE
Exoplayer Custom Notification

### ISSUE THREAD

**Issue by Avijit-Bose** [google/ExoPlayer#5344]
Hello Exoplayer Team,

I am using PlayerNotificationManager in exoplayer.

Please let us all know the followings...
1. How to set custom image in Exoplayer Notification with action handler.
2. How to set subtext in Exoplayer Notification.
Will be of great help. Thank you.

**Comment by marcbaechinger** [comment]
> How to set subtext in Exoplayer Notification.

When you construct the PlayerNotificationManager you need to pass an implementation of PlayerNotificationManager.MediaDescriptionAdapter to the constructor. The implementation of the media description adapter provides an implementation of getCurrentContentTitle() and getCurrentContentText(). The strings returned by these methods are internally passed to the NotificationCompat.Builder as contentTitle and contentText. The title is the text in first row in the notification while the text is the second row:

https://developer.android.com/reference/android/support/v4/app/NotificationCompat.Builder#setcontenttext

> How to set custom image in Exoplayer Notification with action handler.

If you are referring to a custom button in the notification which the user can press, then you need to implement a [CustomActionReceiver](https://github.com/google/ExoPlayer/blob/b5beb32618ac99adc58b537031a6f7c3dd761b9a/library/ui/src/main/java/com/google/android/exoplayer2/ui/PlayerNotificationManager.java#L147) which then is passed to the [constructor of the PlayerNotificationManager](https://github.com/google/ExoPlayer/blob/b5beb32618ac99adc58b537031a6f7c3dd761b9a/library/ui/src/main/java/com/google/android/exoplayer2/ui/PlayerNotificationManager.java#L380).

**Comment by Avijit-Bose** [comment]
""When you construct the PlayerNotificationManager you need to pass an implementation of PlayerNotificationManager.MediaDescriptionAdapter to the constructor. The implementation of the media description adapter provides an implementation of getCurrentContentTitle() and getCurrentContentText(). The strings returned by these methods are internally passed to the NotificationCompat.Builder as contentTitle and contentText. The title is the text in first row in the notification while the text is the second row:""
Ans: I am doing this. I need to place additional text as subtext in the notification. Shown as rectangle in the screenshot. 
Here is my code snippet:
--------------------------------
    private void initMediaPlayer(int AUDIO_INDEX){
        Log.e("AUDIO_INDEX", ""+AUDIO_INDEX);
        AudioAttributes audioAttributes = new AudioAttributes.Builder()
                .setUsage(com.google.android.exoplayer2.C.USAGE_MEDIA)
                .setContentType(com.google.android.exoplayer2.C.CONTENT_TYPE_MUSIC)
                .build();

        player = ExoPlayerFactory.newSimpleInstance(this, new DefaultTrackSelector());
        DataSource.Factory dataSourceFactory = new DefaultDataSourceFactory(this,
                Util.getUserAgent(this, getString(R.string.app_name)));


        ConcatenatingMediaSource concatenatingMediaSource = new ConcatenatingMediaSource();
        for(i=0; i<mPositionalAlbumDetailDataModel.size(); i++){
            MediaSource mediaSource = new ExtractorMediaSource.Factory(dataSourceFactory)
                    .createMediaSource(Uri.parse(mPositionalAlbumDetailDataModel.get(i).getDATA()));
            concatenatingMediaSource.addMediaSource(mediaSource);
        }

        player.prepare(concatenatingMediaSource, true, false);
        player.setAudioAttributes(audioAttributes, /* handleAudioFocus= */ true);
        player.setPlayWhenReady(true);
        player.seekTo(currentWindow, playbackPosition);
        player.addListener(mEventListener);

        playerNotificationManager = PlayerNotificationManager.createWithNotificationChannel(
                this,
                PLAYBACK_CHANNEL_ID,
                R.string.playback_channel_name,
                PLAYBACK_NOTIFICATION_ID,
                new MediaDescriptionAdapter() {
                    @Override
                    public String getCurrentContentTitle(Player player) {
                        return mPositionalAlbumDetailDataModel.get(player.getCurrentWindowIndex()).getTITLE();
                    }

                    @Nullable
                    @Override
                    public PendingIntent createCurrentContentIntent(Player player) {
                        return null;
                    }

                    @Nullable
                    @Override
                    public String getCurrentContentText(Player player) {
                        return mPositionalAlbumDetailDataModel.get(player.getCurrentWindowIndex()).getARTIST();
                    }

                    @Nullable
                    @Override
                    public Bitmap getCurrentLargeIcon(Player player, BitmapCallback callback) {
                        return getBitmap(getBaseContext(), mPositionalAlbumDetailDataModel.get(player.getCurrentWindowIndex()).getALBUM_ART());
                    }
                }
        );
        playerNotificationManager.setNotificationListener(new NotificationListener() {
            @Override
            public void onNotificationStarted(int notificationId, Notification notification) {
                startForeground(notificationId, notification);
            }

            @Override
            public void onNotificationCancelled(int notificationId) {
                stopSelf();
            }
        });
        playerNotificationManager.setFastForwardIncrementMs(0);
        playerNotificationManager.setRewindIncrementMs(0);
        playerNotificationManager.setPlayer(player);

        mediaSession = new MediaSessionCompat(this, MEDIA_SESSION_TAG);
        mediaSession.setActive(true);
        playerNotificationManager.setMediaSessionToken(mediaSession.getSessionToken());

        mediaSessionConnector = new MediaSessionConnector(mediaSession);
        mediaSessionConnector.setQueueNavigator(new TimelineQueueNavigator(mediaSession) {
            @Override
            public MediaDescriptionCompat getMediaDescription(Player player, int windowIndex) {
                Bundle extras = new Bundle();
                Bitmap bitmap = getBitmap(getBaseContext(), mPositionalAlbumDetailDataModel.get(windowIndex).getALBUM_ART());
                extras.putParcelable(MediaMetadataCompat.METADATA_KEY_ALBUM_ART, bitmap);
                extras.putParcelable(MediaMetadataCompat.METADATA_KEY_DISPLAY_ICON, bitmap);
                return new MediaDescriptionCompat.Builder()
                        .setMediaId(mPositionalAlbumDetailDataModel.get(windowIndex).get_ID())
                        .setIconBitmap(bitmap)
                        .setTitle(mPositionalAlbumDetailDataModel.get(windowIndex).getTITLE())
                        .setDescription(mPositionalAlbumDetailDataModel.get(windowIndex).getARTIST())
                        .setSubtitle(mPositionalAlbumDetailDataModel.get(windowIndex).getSIZE() + " " +
                                mPositionalAlbumDetailDataModel.get(windowIndex).getDURATION())
                        .setExtras(extras)
                        .build();
            }
        });
        mediaSessionConnector.setPlayer(player, null);
        //mediaSessionConnector.setPlayer(player, null, customAction1.class);
    }
--------------------------------

Here is the screenshot... pls enlarge the image in the browser when viewing.

![screenshot_20190109-065124_edited](https://user-images.githubusercontent.com/46467333/50871664-4f91c280-13e2-11e9-99e6-4750e4603ede.jpg)

"" If you are referring to a custom button in the notification which the user can press, then you need to implement a CustomActionReceiver which then is passed to the constructor of the PlayerNotificationManager.""
Ans: I am doing this but unable to implement. Here is my code snippet:
-----------------------------------------------
PlayerNotificationManager.CustomActionReceiver customAction.class -> in the constructor

Internal class...

    private class customAction implements PlayerNotificationManager.CustomActionReceiver{
        @Override
        public Map<String, NotificationCompat.Action> createCustomActions(Context context, int instanceId) {
            NotificationCompat.Action action = new NotificationCompat.Action(context.getResources().getIdentifier("music_clear","drawable",context.getPackageName()),"closeBar",null);
            Map<String, NotificationCompat.Action> actionMap = new HashMap<>();
            actionMap.put("closeBar",action);
            return actionMap;
        }

        @Override
        public List<String> getCustomActions(Player player) {
            List<String> customActions = new ArrayList<>();
            customActions.add("closeBar");
            return customActions;
        }

        @Override
        public void onCustomAction(Player player, String action, Intent intent) {
            Log.e("onCustomAction","action: "+action);
        }
    }

Pls provide me with complete code if possible. Thank you.
-----------------------------------------------

**Comment by Avijit-Bose** [comment]
Hello,
Now I am able to get the additional image/icon in the notification as shown in the screenshot (Favorite image) 
![screenshot_20190109-095235](https://user-images.githubusercontent.com/46467333/50876941-94732480-13f5-11e9-8002-daa77ff85c3a.png)

but not getting the "onCustomAction" called. My code snippet in the PlayerNotificationManager instantiation and customAction call:
-------------------------------------
playerNotificationManager = new PlayerNotificationManager(
                this,
                PLAYBACK_CHANNEL_ID,
                PLAYBACK_NOTIFICATION_ID,
                new MediaDescriptionAdapter() {
                    @Override
                    public String getCurrentContentTitle(Player player) {
                        return mPositionalAlbumDetailDataModel.get(player.getCurrentWindowIndex()).getTITLE();
                    }

                    @Nullable
                    @Override
                    public PendingIntent createCurrentContentIntent(Player player) {
                        return null;
                    }

                    @Nullable
                    @Override
                    public String getCurrentContentText(Player player) {
                        return mPositionalAlbumDetailDataModel.get(player.getCurrentWindowIndex()).getARTIST();
                    }

                    @Nullable
                    @Override
                    public Bitmap getCurrentLargeIcon(Player player, BitmapCallback callback) {
                        return getBitmap(getBaseContext(), mPositionalAlbumDetailDataModel.get(player.getCurrentWindowIndex()).getALBUM_ART());
                    }
                },
                new customAction()
        );
------------------------------------- 
-------------------------------------

    private class customAction implements PlayerNotificationManager.CustomActionReceiver{
        @Override
        public Map<String, NotificationCompat.Action> createCustomActions(Context context, int instanceId) {
            NotificationCompat.Action action1 = new NotificationCompat.Action(
                    R.drawable.ic_favorite_deeporange_400_24dp,
                    "fav",
                    pendingIntent
            );
            /*
            NotificationCompat.Action action = new NotificationCompat.Action(context.getResources()
                    .getIdentifier("music_clear",
                            "drawable",context.getPackageName()),"closeBar",null);
            */
            Map<String, NotificationCompat.Action> actionMap = new HashMap<>();
            actionMap.put("fav",action1);
            return actionMap;


        }

        @Override
        public List<String> getCustomActions(Player player) {
            List<String> customActions = new ArrayList<>();
            customActions.add("fav");
            Log.e("getCustomActions","action: "+ player.getCurrentWindowIndex());
            return customActions;
        }

        @Override
        public void onCustomAction(Player player, String action, Intent intent) {
            Log.e("onCustomAction","action: "+ intent.getAction() + action);
        }
    }
-------------------------------------

Pls help me getting the action when clicking the favorite icon/image. Thank you.

**Comment by marcbaechinger** [comment]
Ah, ok thanks! I wasn't aware of the subtext. But there is currently no way to set the subtext of the notification I'm afraid. I think it would be nice to add this for a later release. It could be used for various things like the current position in the queue or other things. I give it a think what's the best way to provide this. 

For the question why your custom action is not called. I'm not sure what's the problem. Your code does not show how the pendingIntent is created which you pass to the constructor of the NotificationCompat.Action in createCustomActions. It worked for me when I did it like this:

```
Intent intent = new Intent(actionName).setPackage(context.getPackageName());
PendingIntent pendingIntent = PendingIntent.getBroadcast(
        context, instanceId, intent, PendingIntent.FLAG_CANCEL_CURRENT);
NotificationCompat.Action myStopAction = new NotificationCompat.Action(
        R.drawable.exo_icon_stop,
        actionName,
        pendingIntent);
```

**Comment by Avijit-Bose** [comment]
Dear Marc,

Your code snippet has worked for me. Thank you.

""I think it would be nice to add this for a later release. It could be used for various things like the current position in the queue or other things. I give it a think what's the best way to provide this.""

Ans: Definitely yes. I am on the same page with you. If you can make/suggest this change in Exoplayer 2.9.4, then it will be of great help. As you suggested, I also want to show the audio duration and size in that subtext for more info to the users.
Once again a very sincere thank you very much for your kind help. You may like to close this now. God bless all.
