### ISSUE TITLE
Question about sampleData and sampleMetadata?

### ISSUE THREAD

**Issue by ghost0906** [google/ExoPlayer#5345]
The exoplayer use the sampleData and sampleMetadata to get the demuxed data from extractors. What does the **offset** in **sampleMetadata** really means? As for the video in h264 format, does it means the size of the start code?

**Comment by ojw28** [comment]
It's [fairly well documented in the class reference](https://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/extractor/TrackOutput.html#sampleMetadata-long-int-int-int-com.google.android.exoplayer2.extractor.TrackOutput.CryptoData-). Is it unclear, or does that answer your question?

**Comment by ghost0906** [comment]
### ****

**Comment by ghost0906** [comment]
thanks
