### ISSUE TITLE
Custom cast control doesn't response when connect with Chromecast from another activity

### ISSUE THREAD

**Issue by enigmadevs** [google/ExoPlayer#5348]
### Issue description
I've implemented exoplayer cast extension in my app using custom controls for local and cast player. My code is based on PlayerManager from castdemo: https://github.com/google/ExoPlayer/blob/release-v2/demos/cast/src/main/java/com/google/android/exoplayer2/castdemo/PlayerManager.java

My app allows user to connect with chromecast anywhere in the app. If user connect with Chromecast in player activity all works fine, but if user connect with Chromecast in another activity, it connect with chromecast, the user selects a video,  it began to play but the custom controls has no response. If i click in play, pause, forward or reward it happens nothing.

I transformed PlayerManager into a singleton a put the SessionAvailabilityListener listener at the application file (this listener call playermanager when it conecct or disconnect from chromecast) but i didn't resolve it.

As i said when i connect from player activity i get response from all control's buttons. I thought when i connect from main activity (i have two activities: main and player activity) exoplayer din't link correctly the custom controls with its listeners.

### Reproduction steps
Connecting with Chromecast before entering at player activity and start playing.

### Link to test content
It happens with any video.

### Version of ExoPlayer being used
2.9.3

### Device(s) and version(s) of Android being used
Xiaomi mi a2 lite with 8.1.

### A full bug report captured from the device
I didn't get any bug or warning, It's just control's buttons do anything, i can't play, pause...

**Comment by ojw28** [comment]
This sounds like an issue with your application code. I'm not sure this is something we can help with.

**Comment by enigmadevs** [comment]
ok, i understand. I debugged all i could and i saw nothing wrong in my code but maybe i missed something.

I will continue to cast sdk 3 :_(
