### ISSUE TITLE
Playing the encrypted HLS 

### ISSUE THREAD

**Issue by cho1231** [google/ExoPlayer#5349]
Hi,
I am looking for an example of playing the encrypted HLS. (I use AWS)
I succeeded in playing the non-encrytped HLS.
But I don't know where and how to set KEY.
I have been searching an example about it for 2 days but I have failed.
I test with exoplayer:2.8.2 with Android Studio.
Please let me know how to set KEY and where to find an example about it.

Thank you in advance.

**Comment by AquilesCanta** [comment]
Could you clarify what you mean with how to set KEY? Do you mean the [EXT-X-KEY](https://tools.ietf.org/html/draft-pantos-http-live-streaming-23#section-4.3.2.4) tag? If EXT-X-KEY is correctly set, your stream should just work without any extra work. With the provided information there is nothing I can do to help. If you provide a stream sample and, maybe a bugreport as well (captured after playing the stream) we might be able to proceed a bit. Thanks! I will reopen once the missing information is provided.

**Comment by cho1231** [comment]
Hi, 
Thank you for replying quickly!
The KEY that I call means Encryption Key, Encryption Key MD5 and Encryption Initialization Vector.

I have only the partial source code which was only for DASH 
(so I added "return new HlsMediaSource.Factory(mediaDataSourceFactory).createMediaSource(uri);" in buildMediaSource()).

        MediaSource mediaSource = buildMediaSource(uri);
        player.prepare(mediaSource);

I think that the initialization of 3 keys will be in front of buildMediaSource().
Thank you for your kindness.

**Comment by AquilesCanta** [comment]
Just follow the HLS spec to provide these. There is nothing you need to do programmatically, just make your manifest HLS compliant.

Note we don't support key or initialization vector provision out of band. That would also be non-recommendable from a interoperability standpoint. If you want to do it out of band, you could try injecting a custom DataSource implementation for chunks. See [HlsDataSourceFactory](https://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/source/hls/HlsDataSourceFactory.html) to get started.

**Comment by cho1231** [comment]
Thank you for your help.
I'll try it.

In fact, I wanted to see how it works and downloaded ExoPlayer-release-v2.zip.
But it had a gradle problem. (Do I have to edit something?)
I struggled to solve the problem, but I couldn't.
If I solve it, I'll try your advice.

Thank you very much.
