### ISSUE TITLE
ExoPlayer SEEK event

### ISSUE THREAD

**Issue by agalera-nice** [google/ExoPlayer#535]
Hello! I am trying to detect a SEEK event in ExoPlayer, however I revised the demo app and perform several tests in order to check if it is informed to the event logger and I cannot see it.

Is there any way that a SEEK in the ExoPlayer can be detected through any event?

The only thing I could observed is that the player enters the buffering state as soon as the seek begins.

Thank you so much

**Comment by ojw28** [comment]
ExoPlayer will only seek when you tell it to, so you should know when seeks occur without having to listen to the player.

Is your wish to have this just for convenience (i.e. because you want to register a bunch of things as listeners to the player, and see when seek gets called without having to track something else separately)?

**Comment by agalera-nice** [comment]
I would like to listen to the seek event because we we're developing an analytics plugin where the only access to the player that we will have it's the player instance itself. So, we would not have access to any application code (Renders, etc..) and all the information we can get from the player will be obtained thanks to an ExoPlayer.Listener defined inside the plugin.

Is there any chance you could include the seek event in the next releases? Otherwise, I think we can make some workaround to detect this situation

Thank you

**Comment by Arqu** [comment]
If it helps you, you can just extend PlayerControl and override the seekTo function to insert your own callback something like:
```
@Override
  public void seekTo(int timeMillis) {
    callback.seekEvent(timeMillis);
    super.seekTo(timeMillis);
  }
```

**Comment by jpshelley** [comment]
@agalera-nice is this a public analytics project you are creating? I'm currently testing out different android players and need to perform some analysis of my own. Do you have recommendations for such tools?

**Comment by ojw28** [comment]
The best solution as things stand would be for you to provide a thin wrapper around an ExoPlayer instance, which itself could implement ExoPlayer, and require that applications using your analytics project wrap their players and access them through the wrapper. You could then intercept the seek.

We may add a seek callback in the future, but have no immediate plans to do so.
