### ISSUE TITLE
ConcatenatingMediaSource using useLazyPreparation lost start offset for MP4 videos

### ISSUE THREAD

**Issue by catbaxter** [google/ExoPlayer#5350]
1. Issue description

ConcatenatingMediaSource using useLazyPreparation losts start offset for MP4 videos

2. Reproduction steps

Take com.google.android.exoplayer2.demo.PlayerActivity.java.
Change the line no. 447

mediaSource =mediaSources.length == 1 ? mediaSources[0] : new ConcatenatingMediaSource(mediaSources);

to 

mediaSource = new ConcatenatingMediaSource(true, true,
              new ShuffleOrder.DefaultShuffleOrder(0),
              mediaSources);
      startWindow = 0;
      startPosition = 5 * 1000;

and run the example using Misc -> Dizzy (MP4). You'll see the 5 seconds start offset on the timeline, but right after the zero offset.

3. Version of ExoPlayer being used

2.9.3

**Comment by tonihei** [comment]
Thanks for reporting. I can reproduce the issue and we'll take a look soon.

**Comment by tonihei** [comment]
Closing as fixed.
