### ISSUE TITLE
ConcatMediaSource is failing to restore when ClippingMediaSource is used.

### ISSUE THREAD

**Issue by sravan1213** [google/ExoPlayer#5351]
### Reproduction steps
1 . Create a ConcatMediaSource with ClippingMediaSource.
2.  Play content using above mediaSource.
3.  Do `player.stop(false)`
4.  Restore above player instance using `player.prepare(mediaSource, false, false)`. 
5. Observation media doesn't restore

Probable fix - `listenerNotificationScheduled = false;` in `releaseSourceInternal` of `ConcatenatingMediaSource`

**Comment by vinodkputta** [comment]
@ojw28 Could you please check this issue?

**Comment by tonihei** [comment]
Thanks for reporting. We'll provide a fix soon.

**Comment by tonihei** [comment]
Closing as fixed.
