### ISSUE TITLE
Question: How to perform an analytics task on a poll?

### ISSUE THREAD

**Issue by NathanSass** [google/ExoPlayer#5352]
I am building an audio player service and I am looking to perform a given analytics task at a particular poll. Ex. report listening progress every 1s.

I would like to leverage some sort of Exoplayer component for this such as `AnalyticsListener` in order to do this. However, it does not provide any way to get the current `EventTime` and since it is a listener only, it is not guaranteed to be called at any regular interval.

I am familiar with how to report reading progress using a poll and I could dream up a similar situation for this use-case but I was hoping that I am missing something that exoplayer already provides.

**Comment by tonihei** [comment]
We don't provide a built-in way to do this, but you can easily create a Handler which calls a method in regular intervals to record the position:
```
handler.post(() -> {
  reportPosition(player.getCurrentPosition());
  handler.postDelayed(this, 1000);
});
```

Besides that, it would to interesting to know why you want to report the position every second? 
If have two consecutive events, let's say at time=10 with position=200 and at time=20 with position=210, you already know that you played all the positions between 200 and 210 without any additional callbacks and events.

**Comment by NathanSass** [comment]
> We don't provide a built-in way to do this, but you can easily create a Handler which calls a method in regular intervals to record the position:

Unfortunately there is no method on the `AnalyticsListener` where i could query the `EventTime`. Having one would solve my problem. In order to implement something similar to the code sample you provided, I would have to provide my `AnalyticsListener` with my player instance. This seems like a circular reference.

> Besides that, it would to interesting to know why you want to report the position every second?

We want to report reading progress to the server every 15 seconds in order to keep the user's audiobook synced across multiple devices.

What I want is `AnalyticsListener.getEventTime` but I see how this may compromise the integrity of the listener.

**Comment by tonihei** [comment]
> We want to report reading progress ... to keep the user's audiobook synced across multiple devices.

Wouldn't it be enough to sync for each reported position? You'll get a new event whenever something changes. So it should be enough to listen to `onPlayerStateChanged`, `onPositionDiscontinuity` and `onTimelineChnaged` to get a full picture of all position movements. 

If you want to ensure that the last position is reported even if the user leaves the app, you may want add a player.stop call before player.release to ensure you get a final state change event.

> This seems like a circular reference.

The proposed Handler is directly created after the player was created and is totally independent of the AnalyticsListener.

> What I want is AnalyticsListener.getEventTime 

That's unfortunately not possible because it's just a passive listener which gets events from the player.

**Comment by NathanSass** [comment]
> Wouldn't it be enough to sync for each reported position?

You would think so - but it depends on network conditions. So we want to be very careful and try to do it often in case the user looses connection (we support offline as well)

I came up with a pretty good solution. But I just wanted to check with you all.
