### ISSUE TITLE
Question: Use cast extension while downloading the source on the phone

### ISSUE THREAD

**Issue by X-Kent** [google/ExoPlayer#5353]
Hello.
I have a question regarding exoplayer cast extension for HLS. I am currently using exoplyer 2.9.2.

Is it possible to use the extension cast so that the remote HLS is in fact downloaded by the android device running the exoplayer and then sent to the target device ?

In my situation, the target cast device will not be able to download the stream on it's own as I need to tunnel it, that tunnel that is only available at the Android side. Connections from the target cast device will fail.

Of course two devices are on the same network and can communicate with each other. The only problem is that I my app can download the content while the cast device will not be able to.

A possible solution is implementing a web server and then telling the cast device to stream from "http://<phone_ip_on_local_network>:<high_port>/stream.m3u8" and manually feeding it the segments... I wanted to know if there is any other possibility that I can make it work.

Thank you !

**Comment by marcbaechinger** [comment]
The cast extension uses the standard Cast SDK for casting to a cast device. With this the content is downloaded by the cast device rather than the Android sender app. 

There are not facilities on ExoPlayer library side which would help you much to stream from your device to the cast device.
