### ISSUE TITLE
How to extend the format of the individual media samples for exoplayer?

### ISSUE THREAD

**Issue by ghost0906** [google/ExoPlayer#5357]
My device supports the sample formats like rv40/cook,  and I built a new instance of extractor to demux the container into raw video data and audio data, but the exoplayer can not play it.
Is there any solutions I can make exoplayer to play it?

**Comment by andrewlewis** [comment]
It sounds like the device has a decoder that can handle these formats, accessible via `MediaCodec`. So at a high level you'll need to pass a factory for your custom `Extractor` when building your `ExtractorMediaSource`, then set the relevant decoder's supported MIME type when outputting a format from your extractor. You can register custom MIME types (see #4264). If this doesn't help please could you give a bit more information about what is not working? Thanks.
