### ISSUE TITLE
DefaultDashChunkSource create negative  bufferedDurationUs

### ISSUE THREAD

**Issue by ghost** [google/ExoPlayer#5358]
Hello,
In my own ExoPlayer version (with some changes), i was encountered in wired issue.
DefaultDashChunkSource class were:
`long bufferedDurationUs = loadPositionUs - playbackPositionUs;`
the bufferedDurationUs is negative! How it could be? what can be the reason?

Thank you!

**Comment by tonihei** [comment]
This shouldn't happen I think. Could you provide some example values for `loadPositionUs `and `playbackPositionUs` and also the `MediaChunk.startTimeUs` and `MediaChunk.endTimeUs` values of the `MediaChunks` in the `queue` parameter? Please also try to describe the exact situation when this happens.

> own ExoPlayer version (with some changes)

If any of these changes involved DefaultDashChunkSource and related classes we probably can't help you debug issues with your custom code. If not, we are happy to take a look to see if that issue may also occur in default ExoPlayer. If possible, it would be good if you can try the default ExoPlayer to see if the same issue occurs there under the same conditions.

**Comment by ghost** [comment]
playbackPositionUs = 6123367000
loadPositionUs = 6122945000

I have  only 1 chunk in the queue:
endTimeUs = 6122945000
startTimeUs = 6122445000

**Comment by ghost** [comment]
You can see this values that i print at the first line of DefaultDashChunkSource.getNectChunk() method.
![image](https://user-images.githubusercontent.com/46018420/50976204-121f5900-14f8-11e9-91a8-367f21e97b63.png)

**Comment by tonihei** [comment]
Can you explain what changes you made to ExoPlayer? It would really be helpful if you can try and see if the same happens in our demo app.

**Comment by ghost** [comment]
Solved! The bug was in server side (Video encoder). Thank you.
