### ISSUE TITLE
TimelineQueueNavigator of mediasession doesn't honour the shuffle order 

### ISSUE THREAD

**Issue by loki666** [google/ExoPlayer#5360]
### Issue description
TimelineQueueNavigator of mediasession ext doesn't honour the shuffle order in publishFloatingQueueWindow

The it iterate over the windowsIndex sequentially, where it should aske the timeline for next windowIndex

### Reproduction steps
Play a queue and check the order of the items in the mediasession queue.
They match the order in which the ConcatenatingMediaSource was created even if the player is shuffleEnabled

### Version of ExoPlayer being used
2.9.2 and 2.9.3

### Device(s) and version(s) of Android being used
Not device specific

### A full bug report captured from the device
No crash

**Comment by marcbaechinger** [comment]
Thanks for reporting! 

Yes , that's not working as it should. We look into this. The order of the queue published to the media session must be the same as the internal shuffle order of the concatenating media source with which the player has been prepared.

**Comment by loki666** [comment]
If you hint me on this one, I can have a look and PR

**Comment by ojw28** [comment]
Closing as fixed in dev-v2 (please correct me if I'm wrong).
