### ISSUE TITLE
Play encrypted hls in exoplayer using encrypted keys Ask

### ISSUE THREAD

**Issue by tushar09** [google/ExoPlayer#5362]
Hi there,

This is not an issue. Its a question about playing the aes-128 hls. I stored my video and playlist in aws and got 3 keys **(Encryption Key, Encryption Key MD5, Encryption Initialization Vector)** from there. But I can not understand how to use these keys in exoplayer. I could not make use of `Aes128DataSource` and `DrmSessionManager`. The code I am using can play non encrypted hls smoothly. How can I get the decryption key from license accusation url? How to call the url and get the response? I could not found any tutorial, from or blog on it. Please help.

Here is the code:
```
String VIDEO_URL = "https://s3.amazonaws.com/######.###.##/videos/mobiletest/mobilemaster.m3u8";

            //Create a default TrackSelector
            BandwidthMeter bandwidthMeter = new DefaultBandwidthMeter();
            TrackSelection.Factory videoTrackSelectionFactory = new AdaptiveTrackSelection.Factory(bandwidthMeter);
            TrackSelector trackSelector = new DefaultTrackSelector(videoTrackSelectionFactory);

            // Create a default LoadControl
            LoadControl loadControl = new DefaultLoadControl();
            //Bis. Create a RenderFactory
            RenderersFactory renderersFactory = new DefaultRenderersFactory(this);


            //Create the player
            player = ExoPlayerFactory.newSimpleInstance(renderersFactory, trackSelector, loadControl);
            simpleExoPlayerView = new SimpleExoPlayerView(this);
            simpleExoPlayerView = (SimpleExoPlayerView) findViewById(R.id.player_view);


            //Set media controller
            simpleExoPlayerView.setUseController(true);
            simpleExoPlayerView.requestFocus();

            // Bind the player to the view.
            simpleExoPlayerView.setPlayer(player);

            // Set the media source
            Uri mp4VideoUri = Uri.parse(VIDEO_URL);

            //Measures bandwidth during playback. Can be null if not required.
            DefaultBandwidthMeter bandwidthMeterA = new DefaultBandwidthMeter();

            //Produces DataSource instances through which media data is loaded.
            DefaultDataSourceFactory dataSourceFactory = new DefaultDataSourceFactory(this, Util.getUserAgent(this, "PiwikVideoApp"), bandwidthMeterA);

            //Produces Extractor instances for parsing the media data.
            ExtractorsFactory extractorsFactory = new DefaultExtractorsFactory();

            //FOR LIVE STREAM LINK:
            MediaSource videoSource = new HlsMediaSource(mp4VideoUri, dataSourceFactory, 1, null, null);
            final MediaSource mediaSource = videoSource;


            player.prepare(videoSource);
```

**Comment by shgrg1712** [comment]
Hello Tushar, 
                     I have same requirement. I have AES encrypted video content. I want to pass the content to exoplayer with decryption key.

Is exoplayer able to decrypt the data and play it?

DId you find any solution for this problem.

**Comment by andrewlewis** [comment]
If the media segments are fully encrypted using AES-128 I think the manifest should be signaling that segments are encrypted using `#EXT-X-KEY:METHOD=AES-128` along with URI/IV attributes for the key, and ExoPlayer will take care of instantiating an `Aes128DataSource` for you. See the HLS RFC for more details on the syntax. This is not the same as DRM so I don't think `DrmSessionManager` is relevant. @AquilesCanta or @ojw28 will be able to confirm/correct this.

**Comment by shgrg1712** [comment]
Hello Andrew, 
                      I have checked this link for ecrypted media content play on exoplayer 
https://github.com/moagrius/EncryptedExoPlayerDemo

It has logic to download normal mp4 file from web and then encrypt it.

Later we use same file to decrypt and play on exoplayer 

But in this case, we are downloading whole content first then sending it to decrypt. But I want to decypt the content buffer at runtime. I donot want to save the content in a file first. Can we directly decrypt the byte data and send it to exoplayer for play.

I need to save memory if I have very large file mp4 file.

Regards 
Sheetal Garg

**Comment by andrewlewis** [comment]
@shgrg1712 If you're dealing with an MP4 rather than an HLS stream then it sounds unrelated to this issue. You may find some existing issues like #4201 and #5193 helpful, but if not please file a new issue.

**Comment by shgrg1712** [comment]
Hello Andrew 
                     I have seen #4201 and #5193 . These are helpful.But still I could not understand the whole logic. I was trying to do these things locally so I was using mp4 just to test the logic of exoplayer with encryption. But at the end, I need HLS stream only in my app. 

Requirement is as follow
1. I have one HLS stream which is streaming 200 MB data.
2. I donot want to store this 200MB file in the system.
3. I want to stream bytes then decrypt it .
4. Show decrypted data on exoplayer 

Stream File(200MB) ->Download a small chunk(lets say 2MB) ->Decrypt it ->Show on exoplayer. 

Do this process until whole data stream ->decrypt->show completly

**Comment by shgrg1712** [comment]
Hello Andrew,
                      Below is piece of code I have written to play encrypted content using Exoplayer.

 SecureRandom secureRandom = new SecureRandom();
    byte[] key = new byte[16];
    byte[] iv = new byte[16];
    secureRandom.nextBytes(key);
    secureRandom.nextBytes(iv);
    mSecretKeySpec = new SecretKeySpec(key, AES_ALGORITHM);
    mIvParameterSpec = new IvParameterSpec(iv);
   mCipher = Cipher.getInstance(AES_TRANSFORMATION);

DefaultBandwidthMeter bandwidthMeter = new DefaultBandwidthMeter();
    TrackSelection.Factory videoTrackSelectionFactory = new AdaptiveVideoTrackSelection.Factory(bandwidthMeter);
    TrackSelector trackSelector = new DefaultTrackSelector(videoTrackSelectionFactory);
    LoadControl loadControl = new DefaultLoadControl();
    SimpleExoPlayer player = ExoPlayerFactory.newSimpleInstance(this, trackSelector, loadControl);
    mSimpleExoPlayerView.setPlayer(player);
    DataSource.Factory dataSourceFactory = new EncryptedFileDataSourceFactory(mCipher, mSecretKeySpec, mIvParameterSpec, bandwidthMeter);
    ExtractorsFactory extractorsFactory = new DefaultExtractorsFactory();
    try {
      Uri uri = Uri.fromFile(mEncryptedFile);
      MediaSource videoSource = new ExtractorMediaSource(uri, dataSourceFactory, extractorsFactory, null, null);
      player.prepare(videoSource);
      player.setPlayWhenReady(true);

In this piece of code , mEncryptedFile denotes the file which has encrypted content which we are passing to exoplayer. But I donot want to store the content in any file.

My requirement is not keep the encrypted file on system but need to stream the data from server in such a way that exoplayer decrypt bytes and play it by itself. 

Please help to suggest any solution.

Thanks
Sheetal Garg

**Comment by andrewlewis** [comment]
@shgrg1712 This issue is about signaling AES-128 encryption with HLS. You're asking about something different so I'm going to mark these posts as off-topic. Please could you post your replies to #5375 or a separate new issue if they are different from that one?

**Comment by tushar09** [comment]
@shgrg1712 
I have found a solution. The trick you need to do is to create you own custom data sources. You need to create a class that extends `HttpDataSource.BaseFactory` and add some code from `DefaultHttpDataSourceFactory`. I know it sounds crazy, but I have solved it this way. Dont worry, I am pasting here the whole code of that custom class.

```
import android.support.annotation.Nullable;

import com.google.android.exoplayer2.upstream.DefaultHttpDataSource;
import com.google.android.exoplayer2.upstream.HttpDataSource;
import com.google.android.exoplayer2.upstream.TransferListener;

public class CustomDataSourcesFactory extends HttpDataSource.BaseFactory{
    private final String userAgent;
    private final @Nullable
    TransferListener listener;
    private final int connectTimeoutMillis;
    private final int readTimeoutMillis;
    private final boolean allowCrossProtocolRedirects;

    /**
     * Constructs a DefaultHttpDataSourceFactory. Sets {@link
     * DefaultHttpDataSource#DEFAULT_CONNECT_TIMEOUT_MILLIS} as the connection timeout, {@link
     * DefaultHttpDataSource#DEFAULT_READ_TIMEOUT_MILLIS} as the read timeout and disables
     * cross-protocol redirects.
     *
     * @param userAgent The User-Agent string that should be used.
     */
    public CustomDataSourcesFactory(String userAgent) {
        this(userAgent, null);
    }

    /**
     * Constructs a DefaultHttpDataSourceFactory. Sets {@link
     * DefaultHttpDataSource#DEFAULT_CONNECT_TIMEOUT_MILLIS} as the connection timeout, {@link
     * DefaultHttpDataSource#DEFAULT_READ_TIMEOUT_MILLIS} as the read timeout and disables
     * cross-protocol redirects.
     *
     * @param userAgent The User-Agent string that should be used.
     * @param listener An optional listener.
     */
    public CustomDataSourcesFactory(String userAgent, @Nullable TransferListener listener) {
        this(userAgent, listener, DefaultHttpDataSource.DEFAULT_CONNECT_TIMEOUT_MILLIS,
                DefaultHttpDataSource.DEFAULT_READ_TIMEOUT_MILLIS, false);
    }

    /**
     * @param userAgent The User-Agent string that should be used.
     * @param connectTimeoutMillis The connection timeout that should be used when requesting remote
     *     data, in milliseconds. A timeout of zero is interpreted as an infinite timeout.
     * @param readTimeoutMillis The read timeout that should be used when requesting remote data, in
     *     milliseconds. A timeout of zero is interpreted as an infinite timeout.
     * @param allowCrossProtocolRedirects Whether cross-protocol redirects (i.e. redirects from HTTP
     *     to HTTPS and vice versa) are enabled.
     */
    public CustomDataSourcesFactory(
            String userAgent,
            int connectTimeoutMillis,
            int readTimeoutMillis,
            boolean allowCrossProtocolRedirects) {
        this(
                userAgent,
                /* listener= */ null,
                connectTimeoutMillis,
                readTimeoutMillis,
                allowCrossProtocolRedirects);
    }

    /**
     * @param userAgent The User-Agent string that should be used.
     * @param listener An optional listener.
     * @param connectTimeoutMillis The connection timeout that should be used when requesting remote
     *     data, in milliseconds. A timeout of zero is interpreted as an infinite timeout.
     * @param readTimeoutMillis The read timeout that should be used when requesting remote data, in
     *     milliseconds. A timeout of zero is interpreted as an infinite timeout.
     * @param allowCrossProtocolRedirects Whether cross-protocol redirects (i.e. redirects from HTTP
     *     to HTTPS and vice versa) are enabled.
     */
    public CustomDataSourcesFactory(
            String userAgent,
            @Nullable TransferListener listener,
            int connectTimeoutMillis,
            int readTimeoutMillis,
            boolean allowCrossProtocolRedirects) {
        this.userAgent = userAgent;
        this.listener = listener;
        this.connectTimeoutMillis = connectTimeoutMillis;
        this.readTimeoutMillis = readTimeoutMillis;
        this.allowCrossProtocolRedirects = allowCrossProtocolRedirects;
    }

    @Override
    protected HttpDataSource createDataSourceInternal(
            HttpDataSource.RequestProperties defaultRequestProperties) {
        DefaultHttpDataSource defaultHttpDataSource = new DefaultHttpDataSource(userAgent, null, listener, connectTimeoutMillis,
                readTimeoutMillis, allowCrossProtocolRedirects, defaultRequestProperties);
        defaultHttpDataSource.setRequestProperty("your header", "your token");
        return defaultHttpDataSource;
    }
}
```

You see the method `createDataSourceInternal`? I am returning a `DefaultHttpDataSource` object initialised with a header key and a token `defaultHttpDataSource.setRequestProperty("your header", "your token");`. So now your exoplayer will hit the accusation url with this header key and token value which will be checked by your server side in order to verify the valid request. Your hls playlist(`.m3u8`) contains the accusation url. Exoplayer uses this url automatically. All you need to do is to tell the player to use the validation keys.

So again here is the usage code of Your custom data sources:
```
//ExoPlayer implementation
        //Create a default TrackSelector
        BandwidthMeter bandwidthMeter = new DefaultBandwidthMeter();
        TrackSelection.Factory videoTrackSelectionFactory = new AdaptiveTrackSelection.Factory(bandwidthMeter);
        TrackSelector trackSelector = new DefaultTrackSelector(videoTrackSelectionFactory);

        // Create a default LoadControl
        LoadControl loadControl = new DefaultLoadControl();
        //Bis. Create a RenderFactory
        RenderersFactory renderersFactory = new DefaultRenderersFactory(this);


        //Create the player
        player = ExoPlayerFactory.newSimpleInstance(renderersFactory, trackSelector, loadControl);
        simpleExoPlayerView = new SimpleExoPlayerView(this);
        simpleExoPlayerView = (SimpleExoPlayerView) findViewById(R.id.player_view);


        //Set media controller
        simpleExoPlayerView.setUseController(true);
        simpleExoPlayerView.requestFocus();

        // Bind the player to the view.
        simpleExoPlayerView.setPlayer(player);

        // Set the media source
        Uri mp4VideoUri = Uri.parse(VIDEO_URL);

        //DefaultHttpDataSource source = new DefaultHttpDataSource(Util.getUserAgent(this, "appAgent"), null);
        //source.setRequestProperty("header", "user token");

        //Measures bandwidth during playback. Can be null if not required.
        DefaultBandwidthMeter bandwidthMeterA = new DefaultBandwidthMeter();

        //DefaultDataSourceFactory o = new DefaultDataSourceFactory(this, null, new DefaultHttpDataSourceFactory(Util.getUserAgent(this, "appAgent"), bandwidthMeterA));
        CustomDataSourcesFactory o = new CustomDataSourcesFactory("Exoplayer");

        //Produces DataSource instances through which media data is loaded.
        DefaultDataSourceFactory dataSourceFactory = new DefaultDataSourceFactory(this, Util.getUserAgent(this, "PiwikVideoApp"), bandwidthMeterA);

        //Produces Extractor instances for parsing the media data.
        ExtractorsFactory extractorsFactory = new DefaultExtractorsFactory();

        //FOR LIVE STREAM LINK:
        MediaSource videoSource = new HlsMediaSource(mp4VideoUri, o, 1, null, null);
        final MediaSource mediaSource = videoSource;


        player.prepare(videoSource);
``` 

This problem was too much critical for me because I could not found any tutorial, resources or idea to solve this. I am writing this because I dont want other noob people like me to suffer from this. 

If you are not clear enough, feel free to ask here. I will assist you further. I have also the server side code in order to generate the decryption key from AWS encrypted key.

**Comment by andrewlewis** [comment]
Just a side note: I think you can avoid adding `CustomDataSourcesFactory` by instead using `DefaultHttpDataSourceFactory` and calling `DefaultHttpDataSourceFactory.getDefaultRequestProperties().set(header, token)` to set the token.

**Comment by cho1231** [comment]
I am a beginner of ExoPlayer.
I have been looking for this solution!

I have two questions.
Q1) I don't know what the parameters of header and token are.
Q2) And I don't know where 3 keys(Encryption Key, Encryption Key MD5, Encryption Initialization Vector) are located.  Do I have to set them in my App?

Thank you for a valuable information.

**Comment by tushar09** [comment]
Q1) Talk to your backend developer.

Q2) When your Elastic transcoder finishes the job, you find it hovering the mouse on the lock icon. Picture link is attached:
https://i.stack.imgur.com/736z5.png

**Comment by cho1231** [comment]
Thank you for your quick and kind response!!!

Q1) Unfortunately, I am the only developer. Please let me know the meaning of header and token.

Q2) I understand that there are 3 keys on the server and I don't need to set them in my App, right?

**Comment by tushar09** [comment]
Here is the thing: Your m3u8 file contains the accusation url. Your player will hit the url to get the decryption key. Now whoever have this key, will be able to play the video. So the accusation url is your server. Now for easy example lets say an user created profile in your app. The user have username and password. Exoplayer will hit the accuasation url with the username and password. Your server will check the password, if its match then it will return the decryption key, otherwise not. This way you can make sure the secure streaming. **Now here this username and password is acting like header value and token**.  You do not set the 3 keys in your app. 

Now come to the other point. Again lets say your server found that the username and password are valid and need to return the decryption key. Now, how the server get it? You need to decrypt the **Encryption Key** using your aws iam role key. Then you will get the actual decryption key of the video chunk, which is needed by the exoplayer. This is how it works.

**Comment by cho1231** [comment]
Thank you very very much for your wonderful explanation!!

**Comment by cho1231** [comment]
Thanks for your explanation, I've just succeeded in making an encrypted HLS video file.
If the key is shown in my License Acquisition URL, I can see my video.

Now, I tried to use **the header value and token**.
    defaultHttpDataSource.setRequestProperty("username", "1111");
And my PHP code starts like below.
   if(isset($_REQUEST['username'])==false)
        return;
   $username = $_REQUEST["username"];
   if($username==null || strcmp($username, "1111")!=0)
        return;

If I use this code, I couldn't see my video.
Could you help me?

**Comment by tushar09** [comment]
Note that exoplayer will request your accusation url for the key and the request type will be **GET** method. So you should check the header values in PHP like this:  
```
<?php

foreach (getallheaders() as $name => $value) {
    // check values if it match or not.
    // if match, then return the decryption key.
}

?>
```

**Comment by cho1231** [comment]
I greatly appreciate your help!!!
You saved my time!
You are my Hero!

**Comment by tushar09** [comment]
Thank you. Did it work properly?

**Comment by cho1231** [comment]
Yes! It works perfectly thanks for your CustomDataSourcesFactory, your explanation and PHP code!
You are awesome!

**Comment by mohfa24** [comment]
Hi there . What about if I want to play a **local encrypted file** (**AES 128 , mp4**) ?
How do I change the code to do it ?
