### ISSUE TITLE
UDP Startup Delay

### ISSUE THREAD

**Issue by fougere-mike** [google/ExoPlayer#5365]
### Issue description
Initial playback of UDP video seems to buffer excessively.

I have a server transmitting an h.264 stream via UDP to my client. When playback begins, I see the first frame of the video almost immediately. However, the player continues to buffer for 2-3 seconds after this point.

This buffering time is not affect by switching between WiFi / ethernet. My guess is that ExoPlayer is waiting for some buffer to be filled, or for some number of frames to be available, etc.

It would be awesome if this delay could be shortened or eliminated. I'm willing to modify source if necessary, just need some guidance.

Note: I've tested the same server with mpv on linux, and the playback starts almost instantaneously. 

### Reproduction steps
1. Modify the ExoPlayer demo app and add a UDP sample source.
2. Modify the ExoPlayer demo app initialise a UdpDataSource for samples with `udp://` uri scheme.
3. Launch the demo and play the UDP sample.
4. Observe the first frame is displayed several seconds before motion begins.

### Link to test content
Unfortunately my content is not available publicly. 

I am testing with an mpegts file containing a single h264 video track, and AAC audio. Following is the output from `ffmpeg -i` as it may be useful for reproduction:
```
Input #0, mpegts, from '00001.ts':
  Duration: 00:00:02.02, start: 0.515711, bitrate: 2768 kb/s
  Program 1 
    Stream #0:0[0x31]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], Closed Captions, 29.97 fps, 29.97 tbr, 90k tbn, 59.94 tbc
    Stream #0:1[0x34]: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 255 kb/s
```

I suggest using netcat or similar to send the mpegts file over UDP.

### Version of ExoPlayer being used
r2.9.0

### Device(s) and version(s) of Android being used
Currently, this has only been tested on the NVIDIA SHIELD.

**Comment by andrewlewis** [comment]
Please have a look at [`DefaultLoadControl`](https://github.com/google/ExoPlayer/blob/r2.9.3/library/core/src/main/java/com/google/android/exoplayer2/DefaultLoadControl.java) especially `DefaultLoadControl.Builder.setBufferDurationsMs` where you can set the duration of media that needs to be buffered before the player transitions from the buffering state to the ready state.

**Comment by fougere-mike** [comment]
Perfect, thanks :+1:
