### ISSUE TITLE
can we get update of current subtitle cue if captions are embeded in the mp4 ?

### ISSUE THREAD

**Issue by MuVen** [google/ExoPlayer#5368]
can we get update of current subtitle cue if captions are embeded in the mp4 ?

If video has inbulit subtitles can we get the update of current subtitle cue ?

**Comment by ojw28** [comment]
It depends what track type is used for the captions. It should "just work" if it's one of the embedded track types we support, which I think are `tx3g`, `wvtt`, `stpp` and `c608`. I'd suggest trying to play the content in our demo app. If you can enable the caption there then you should see that it works fine. If the option to enable the caption isn't there then it's likely the embedded track is not one of our supported types.
