### ISSUE TITLE
Video frames are stuck for few seconds [only on versions >= 2.8.3]

### ISSUE THREAD

**Issue by raunakyadav** [google/ExoPlayer#5370]
### Issue description
The video frames seem stuck for 1-2 seconds if the player is detached and attached within the same activity.

### Reproduction steps
 We have a use case where the app feed contains videos. If tapped it opens in a separate fragment but the playerView is simply detached and added to the new fragment in order to have a seamless video experience for the user.
When the player is added to the fragment, the frames are stuck for couple of seconds.

### Link to test content 
Demo app  : (https://drive.google.com/open?id=14-BVnaGv4qhUBG3xURXXlau8a55GbpQS). 
Used sample video : http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4

### Version of ExoPlayer being used
Issue occurs in all versions >=2.8.3.
Previous versions work fine.

### Device(s) and version(s) of Android being used
Does not occur on all devices. 
Moto E4 Plus - Android OS 7 - Issue always occurs
Samsung Galaxy S6, OnePlus 6 - No issue

### A full bug report captured from the device
Will mail the full bug report to dev id.

Noticed these logs on device with bug :
W/cr_MediaCodecUtil: Codec OMX.MTK.VIDEO.ENCODER.AVC is disabled due to SDK version 25
W/cr_MediaCodecUtil: HW encoder for video/avc is not available on this device.
E/OMXNodeInstance: setParameter(1450166:MTK.DECODER.AVC, ParamPortDefinition(0x2000001)) ERROR: BadParameter(0x80001005)
W/ACodec: [OMX.MTK.VIDEO.DECODER.AVC] setting nBufferCountActual to 24 failed: -2147483648
E/OMXNodeInstance: setParameter(1450166:MTK.DECODER.AVC, ParamPortDefinition(0x2000001)) ERROR: BadParameter(0x80001005)
W/ACodec: [OMX.MTK.VIDEO.DECODER.AVC] setting nBufferCountActual to 23 failed: -2147483648

**Comment by andrewlewis** [comment]
I don't think we've received the bug report yet. Please send it with subject line "Issue #5370".

Based on the observed behavior, it sounds like the problematic devices are not able to use `DummySurface`, which means that we get a fresh decoder on reattaching the view  and need to decode forward from the previous keyframe, which introduces a delay. Quite a few devices were excluded in 2.8.3, but strangely not Moto E4 Plus. If you want to investigate yourself, it would be helpful if you could step through `MediaCodecVideoRenderer.codecNeedsSetOutputSurfaceWorkaround` to see whether the devices where you're seeing the issue need the workaround

**Comment by raunakyadav** [comment]
Thanks @andrewlewis. I have mailed the bug report. Please check now. Lenovo Vibe Android 6 too has the same issue.
I will check the code you mentioned and update here.

**Comment by raunakyadav** [comment]
Moto E4 Plus ((Util.DEVICE = nicklaus_f) is present in the excluded devices list and so MediaCodecVideoRenderer.codecNeedsSetOutputSurfaceWorkaround returns true for it. Hence, the issue.
I removed it from the list and found the player switch flow working seamlessly as before. But will this mean that the other issues mentioned above this method will come back. (Although we never saw those issues in QA testing or in Fabric reports.) If yes, then this looks like a UI vs performance pick. :(

**Comment by andrewlewis** [comment]
@raunakyadav Thanks for the update. There is the option of overriding the method in your app to remove it from the workaround and seeing if any other issues get reported.

It may not be viable for your use case, but another option may be to rearrange the app's layout so that the player view is on top of other elements then transform it as needed to create the same effect as if it was nested in the layout.
