### ISSUE TITLE
Exoplayer Default Player Icon Change

### ISSUE THREAD

**Issue by Avijit-Bose** [google/ExoPlayer#5372]
Is it possible to change the default exoplayer media player icons like PLAY, PAUSE etc in NOTIFICATION. If yes, could you pls. let us all know how to achieve that.

**Comment by andrewlewis** [comment]
You can override the icons used by `PlayerNotificationManager` by redefining the resources in your app's resources. They notification icons are defined in the UI module [here](https://github.com/google/ExoPlayer/blob/afd11de/library/ui/src/main/res/values/drawables.xml#L9), so (for example) you could add a drawables.xml in your app that overrides one of these like:

```
<?xml version="1.0" encoding="utf-8"?>
<resources>
  <drawable name="exo_notification_pause">@drawable/my_pause_icon</drawable>
</resources>
```

**Comment by Avijit-Bose** [comment]
Thank you. A belated Merry Christmas and a very happy new year.
