### ISSUE TITLE
Play encrypted content using Exoplayer - AES encryption

### ISSUE THREAD

**Issue by shgrg1712** [google/ExoPlayer#5375]
Hello Team,
                  Greetings :)

I have one question in which I need to know if we can play encrypted content using exoplayer and encryption key.

Here the major concern is to pass the encrypted data to exoplayer and also encryotion key. Exoplayer play the content directly. It should do decryption internally.

I have seen one link which has similar concern, but no reply yet so I am starting new thread here.
Play encrypted hls in exoplayer using encrypted keys Ask #5362 

Please help

Regards
Sheetal Garg

**Comment by erdemguven** [comment]
Duplicate of #5362
