### ISSUE TITLE
m3u8 does not play

### ISSUE THREAD

**Issue by LittleSunZ** [google/ExoPlayer#5376]
This m3u8 does not play, how to do?
http://open.ls.qingting.fm/live/386/24k.m3u8?deviceid=867451023307124
![default](https://user-images.githubusercontent.com/20589218/51106320-6000cd80-1826-11e9-9668-73c43d6fe930.png)

**Comment by erdemguven** [comment]
ExoPlayer demoapp can't play the stream.

**Comment by AquilesCanta** [comment]
Please fill the full issue template next time you report an issue. 

I ran into 3 different problems and I don't know which one you are running into. That would have not been confusing if a bugreport and an issue description had been included. That being said:

1. Every now and then I run into a Socket connection timeout, which I think is solely a server-side issue. It helped me using a different device id as a url parameter. Might have just been a coincidence.
2. The Segment URLs are missing the scheme. So please append "http:" to each URI.
3. The segments declare a video stream, but don't actually include any video packets, so the player hangs waiting for video packets. You can either fix the content or work around it by injecting a DefaultHlsExtractorFactory which ignores the missing track. Like so:

```
new HlsMediaSource.Factory(dataSourceFactory)
    .setExtractorFactory(
        new DefaultHlsExtractorFactory(
            DefaultTsPayloadReaderFactory.FLAG_IGNORE_H264_STREAM))
    .createMediaSource(uri);
```

Hope this helps.
