### ISSUE TITLE
SmoothStreaming TTML fMP4 crashes player

### ISSUE THREAD

**Issue by icetronics** [google/ExoPlayer#5378]
### Issue description
After enabling the subtitle track during encrypted playback, the player crashes.
**Setup**: SmoothStreaming with PlayReady DRM, TTML in fMP4 (not encrypted)
**Comparison**: DRM-free SmoothStr with same subtitle setup plays flawlessly.

### Link to test content
Manifest URL sent via email.
Might not be possible to play as the DRM license request requires a special header which includes an OAuth token that expires after a time.

### Version of ExoPlayer being used
2.9.2

### Device(s) and version(s) of Android being used
FireTV (any generation)
FireOS 5.2.6.8

### A full bug report captured from the device
Sent via email.

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.exoplayer2.util.ParsableByteArray.readBytes(byte[], int, int)' on a null object reference
        at com.google.android.exoplayer2.source.SampleQueue.sampleData(SampleQueue.java:561)
        at com.google.android.exoplayer2.source.chunk.ChunkExtractorWrapper$BindingTrackOutput.sampleData(ChunkExtractorWrapper.java:206)
```

**Comment by ojw28** [comment]
This is related to confusion around how subtitles are handled in DRM protected SmoothStreaming. An attempt was made to assume they're always unprotected in https://github.com/google/ExoPlayer/issues/4838 (which is the case in the sample provided). But it looks like the solution for doing so wasn't quite complete. It's easy to fix; we'll use this issue for tracking.

**Comment by ojw28** [comment]
Fixed in `dev-v2`. Please verify if you have a chance.

**Comment by icetronics** [comment]
Thanks a lot for the quick action, @ojw28! I'll try to verify it this week and get back to you. Can you please forecast which version could incorporate this fix?

**Comment by ojw28** [comment]
It'll be in 2.9.4.

**Comment by icetronics** [comment]
Hi @ojw28, just came back to let you know that your fix is working marvelously. Many thanks for the prompt action!

**Comment by ojw28** [comment]
Glad to hear it; thanks for confirming!
