### ISSUE TITLE
Incorrect duration for AAC and TS content?

### ISSUE THREAD

**Issue by elixiroflife4u** [google/ExoPlayer#538]
I found this issue within the demo player for the 1.3.3 release. The samples marked "Apple AAC 10s" and "Apple TS 10s" under misc incorrectly report the content duration.
Seems like this is a problem within the extractors/renders and not a bug with the demo player alone.

(on a side note, the Apple AAC media playlist under HLS does show a duration value).

**Comment by ojw28** [comment]
In short, this is working as intended. In more detail:

Raw AAC/ADTS and MPEG-TS streams don't contain index structures for allowing seeking, or the duration of their duration. Hence the only way to seek or determine the duration of such a stream is to download the whole thing and linearly scan through the entire file to see what's there.

For this reason, these formats are usually only used where an index is provided separately (as is the case in HLS, where the playlist file serves as an index into small chunks of media in these formats), or for live streaming with no DVR window (where seeking isn't possible and the duration is unknown anyway).
