### ISSUE TITLE
Audio live stream clients falling behind when paused from notification controls and played again?

### ISSUE THREAD

**Issue by v1sd3v** [google/ExoPlayer#5383]
I have an app that streams live audio from a URI. Lately, I've noticed that when a user pauses the audio from Android **notification controls** and they play again after a while, the stream is behind but what I need is for the stream to be always caught up. Inside the application, it's easier to fix because I just use `seekTo(0)`  whenever the play function is called and it works fine.

**Comment by marcbaechinger** [comment]
The actions in the notification are created by the PlayerNotificationManager which delegates to a DefaultControlDispatcher which then calls appropriate method on the player instance.

So in your case for ACTION_PLAY the controlDispatcher.dispatchSetPlayWhenReady(player, true) is dispatched to player.playWhenReady(true) to continue playback.

If I understand correctly you want to have called player.seekTo(0) in addition to playing again. You can do this by setting your own ControlDispatcher with [playerNotificationManager.setControlDispatcher(yourControlDispatcher).](https://github.com/google/ExoPlayer/blob/b5beb32618ac99adc58b537031a6f7c3dd761b9a/library/ui/src/main/java/com/google/android/exoplayer2/ui/PlayerNotificationManager.java#L474) You custom version can inherit from DefaultControlDispatcher and overwrite the onDispatchPlayWhenReady(true).

**Comment by v1sd3v** [comment]
I created a custom control dispatcher and it did the trick! Thank you!

**Comment by v1sd3v** [comment]
I created a custom control dispatcher and it did the trick! Thank you!
