### ISSUE TITLE
Request: allow to set PlayerView's surface-type at runtime

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [google/ExoPlayer#5387]
It is advised to use `app:surface_type="texture_view"` on when it's really needed. For example when the Android version is too low, or when you need to show the video being cut in one way or another :

https://google.github.io/ExoPlayer/faqs.html

https://github.com/google/ExoPlayer/issues/2837

![image](https://user-images.githubusercontent.com/5357526/51184089-ee835680-18db-11e9-875f-fe9d9d382d85.png)

But, as I've noticed, this can only be set in XML. I can't find how to set it programmatically . 

So if I have a special condition for setting it, currently I have to make 2 almost-identical layout files that only have the PlayerView inside of them. One with it set to `texture_view` and one without.

Can you please let us set it ourselves? I know it has to decide about the type as quickly as possible, but this is quite annoying to handle this way. And what if there are even more fields that work this way? I would have needed to create more and more XML layout files just because of it...

**Comment by marcbaechinger** [comment]
I think you can do this as a version aware layout file, so that Android handles this for you:

https://developer.android.com/training/backward-compatible-ui/using-component

**Comment by AndroidDeveloperLB** [comment]
@marcbaechinger If you mean the solution of multiple layouts, I've already written that this is a bad solution.

**Comment by ojw28** [comment]
There's no setter for the surface type because it doesn't really make sense to switch surface type during usage of `PlayerView`. It's a decision that should be made when the view is created.

Given this, having two small layout files seems like an acceptable solution to the problem. We could also provide `PlayerView` constructors that let you pass the surface type when you're instantiating a view directly in code, however I think it's normally preferable to inflate views from layout files, which gets back to just having two small layout files again.

**Comment by AndroidDeveloperLB** [comment]
It's not switching between them. It's initializing right when inflating the view.
We know which type to use, but it's just at runtime. 

Having multiple layouts doesn't make sense, because if there are more attributes that work this way, not allowing to initialize at runtime, it will take 2^numberOfSuchAttributes layout files. If the attribute has more possible values, the "2" will be even higher.

And it gets worse if more views take this approach,  even if you have 2 instances of PlayerView . But in this case we could have 2 (or more, depending on attribute possible values) layout per instance.

Still, this is extremely inconvenient, no matter how you look at it.

**Comment by ojw28** [comment]
> Having multiple layouts doesn't make sense, because if there are more attributes that work this way, not allowing to initialize at runtime, it will take 2^numberOfSuchAttributes layout files. If the attribute has more possible values, the "2" will be even higher.

There are no other `PlayerView` attributes that work this way, and I don't think it's likely we'll need to add any. I don't see any reason for us to address a hypothetical future problem, when we've no reason to believe it's going to happen. If it does happen, we can address it when it happens.

> And it gets worse if more views take this approach, even if you have 2 instances of PlayerView . But in this case we could have 2 (or more, depending on attribute possible values) layout per instance.

I don't understand what this means.

**Comment by AndroidDeveloperLB** [comment]
Just because currently there are no more attributes that need to be set right away only in XML, doesn't mean there won't be more. Same goes for thinking that ExoPlayer is the only one that has such an attribute that must be set only in layout XML file.

It's not hypothetical . It can easily happen. I can easily use the same approach and make a custom view that has such an attribute that must be set only in layout XML file.

About the last part, I mean that you can have multiple instances of PlayerView on the same Activity/Fragment. If I want to have all possible combinations of surfaceType for each, I might need to create 4 layouts instead of just 1 that I can set it at runtime.

**Comment by AndroidDeveloperLB** [comment]
I think that given that you don't see how important it it not to force initialization only in XML, the only way to truly handle it is avoid XML usage of the PlayerView, except just for these values, and always use a wrapper View (FrameLayout) that will contain the PlayerView, and will need all of the other initialization done from it.

Still, very annoying.

**Comment by AndroidDeveloperLB** [comment]
Another possible solution is to add the TextureView/SurfaceView at runtime, and assign the SimpleExoPlayer  to it. Would be much more work too.

**Comment by ojw28** [comment]
I think you're inventing a problem where a problem doesn't really exist. It's unlikely that other components will need this type of unusual attribute, because the vast majority attributes are well suited to setters that can be used throughout the component's lifecycle. Sure, you _could_ implement your own custom view that has such an attribute. But do you _need_ to to achieve something? If you don't then you don't have a real problem.

Note that even if you do end up in a scenario where you have multiple UI components with this type of attribute, you can solve the problem in a couple of minutes simply by inflating the desired `PlayerView` in code and attaching it at the right place in your view hierarchy. I wouldn't exactly describe it as "very annoying":
```
int playerViewLayoutId = yourCondition
    ? R.layout.texture_player_view
    : R.layout.surface_player_view;
PlayerView playerView = LayoutInflater.from(context).inflate(playerViewLayoutId, ... );
// Attach playerView where you want it in your hierarchy
```
I wouldn't exactly describe this as "very annoying".

**Comment by AndroidDeveloperLB** [comment]
It is annoying because for each layout that was supposed to have just a PlayerView, now I have 3 layouts: the container, and 2 more for each of the values of `app:surface_type` . And all of this just because there isn't a function for initialization of the view.

The solution you wrote is exactly what I wrote that's annoying. 3 layouts instead of just one.

**Comment by ojw28** [comment]
You probably only need two extra layouts that you can share between multiple other layouts (if you have them). This really isn't a big problem.

**Comment by AndroidDeveloperLB** [comment]
@ojw28 Incorrect. If I have more layouts that need a player, I will have to generate it for them as well.
2 layouts for each layout that has a player.
Why not just allow us to set the type at runtime? Or at least have a CTOR with this option? Why force us to use it only in one place, in the XML layout file? 
And why close this?

**Comment by ojw28** [comment]
I closed it because we're not planning to make any changes in response to this issue. The existing way of resolving the issue in application code takes literally a couple of minutes, and we've received zero other reports mentioning this as an issue.

> Incorrect

Once you've defined two layout files for `PlayerView`, one with each surface type, you can re-use those with multiple other layouts.

**Comment by AndroidDeveloperLB** [comment]
"Once you've defined two layout files for PlayerView, one with each surface type, you can re-use those with multiple other layouts.
"
Incorrect. You assume that all of the other attributes are the exact same for all layouts that have the PlayerView. That's a wrong assumption. You can't re-use those with multiple other layouts, unless the usage is identical in 100% of the cases, which is wrong to assume.

If you wish to re-use with multiple other layouts, the base ones would include the bare minimal (or default), and the rest would be needed to be changed in code, which loses the whole point of using layout XML files. 
So your solution is correct only if we actually use code to set all the attributes (when needed) instead of putting them all in the layouts files.

**Comment by ojw28** [comment]
As we've already established, all other attributes can be set in code, so you can just set them to what you want after inflation.

The use case where you have many different places that need a `PlayerView`, all of which need different attribute configurations, also seems extremely fanciful. As already stated, we've received zero other reports mentioning this as an issue. What does that suggest, in terms of how seriously app developers are genuinely inconvenienced by this problem?
