### ISSUE TITLE
Question: How to handle drag&drop?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [google/ExoPlayer#5389]
It seems that by using `setOnDragListener` on a view that contains PlayerView of ExoPlayer, the content of the shadow for it becomes black.

Is there a way to overcome it?

**Comment by erdemguven** [comment]
Please add more information and make it clearer.

**Comment by AndroidDeveloperLB** [comment]
@erdemguven When I drag the PlayerView or a container of it, it doesn't show its content on the dragged shadow. It's as if the PlayerView doesn't exist.

Check the attached project. Drag the CardView that contains the PlayerView (initiate by long pressing), and you will see only the TextView that's on top of the PlayerView.

Also attached sample video to show the issue.

[ExoPlayerTest.zip](https://github.com/google/ExoPlayer/files/2775604/ExoPlayerTest.zip)

[device-2019-01-19-162411.zip](https://github.com/google/ExoPlayer/files/2775603/device-2019-01-19-162411.zip)

**Comment by erdemguven** [comment]
I don't know if this is possible but apparently we don't support it yet so marking as enhancement.

**Comment by AndroidDeveloperLB** [comment]
@erdemguven Maybe it's possible that upon starting to drag, I will get a bitmap of the ExoPlayer (of exactly how it looks), set it to be drawn?
Is it possible on ExoPlayer? To pause and get the current frame as a bitmap? I think it could be the correct solution.
I also think that the issue here is that ExoPlayer doesn't really draw to a normal canvas like other Views , so it requires a bit more sophisticated solution.

**Comment by ojw28** [comment]
I don't really understand what this is tracking or why it's marked as an enhancement. What would the enhancement be that would close this issue?

> I also think that the issue here is that ExoPlayer doesn't really draw to a normal canvas like other Views

Probably. Although if this is the problem then it's not really ExoPlayer specific. It's just a general Andorid question about drag & drop in conjuction with `SurfaceView`. Probably using `TextureView` fixes it.

**Comment by AndroidDeveloperLB** [comment]
@ojw28 Didn't work.

**Comment by erdemguven** [comment]
I investigated the issue. It looks like it isn't possible to use SurfaceView or TextureView for dragging.
You can get a bitmap easily if you useTextureView:
```
val textureView = playerView.getVideoSurfaceView() as TextureView
val bitmap = textureView.bitmap
```

**Comment by AndroidDeveloperLB** [comment]
And then what?

**Comment by erdemguven** [comment]
and then you can use the bitmap to draw the shadow. 
Please see this document for how to draw a custom shadow:
https://developer.android.com/guide/topics/ui/drag-drop.html#StartDrag

**Comment by AndroidDeveloperLB** [comment]
You mean to show an ImageView on top, with this bitmap while hiding the player, and letting it drag&drop ?
