### ISSUE TITLE
Documentation: HLS grammatical error

### ISSUE THREAD

**Issue by jpshelley** [google/ExoPlayer#539]
Currently under the HLS Section the documentation says:

> "A **HlsSampleSource** requires a **DataSource** to be injected through its constructor, through which the media data can be loaded."

I believe it should say:

> "A **HlsChunkSource** requires a **DataSource** to be injected through its constructor, through which the media data can be loaded."

**Comment by ojw28** [comment]
Correct. Thanks!

**Comment by ojw28** [comment]
Fixed
