### ISSUE TITLE
Exoplayer can't play some MP4 video, issue same as 5162

### ISSUE THREAD

**Issue by xiaoxixi615** [google/ExoPlayer#5392]
We really need to see the MP4 or at least the whole moov box. You can attach it here or send it to `dev.exoplayer@gmail.com` with subject line "Issue #5162".

_Originally posted by @andrewlewis in https://github.com/google/ExoPlayer/issues/5162#issuecomment-442422734_

I got the similar issue when playing a .mkv file,  exoplayer selected the MP4Extractor, but couldn't play the file. I found that in AtomParsers.java, when invoking the following snippet, the  "fixedSampleSize"  and 
"sampleCount"  both were 0, and I dumped the profile, and attached it. It can be played on PC normally.
Please help to take a look, thanks.

    public StszSampleSizeBox(Atom.LeafAtom stszAtom) {
      data = stszAtom.data;
      data.setPosition(Atom.FULL_HEADER_SIZE);
      fixedSampleSize = data.readUnsignedIntToInt();
      sampleCount = data.readUnsignedIntToInt();
    }

**Comment by xiaoxixi615** [comment]
@andrewlewis 
I have shared the video file via google drive,  as it has a large size(1.4G). 
[sony.txt](https://github.com/google/ExoPlayer/files/2763602/sony.txt)

seems the stsz sample_count invalid, please have a look ,thanks
          [stsz] size=12+8
            sample_size = 0
            sample_count = 0

**Comment by andrewlewis** [comment]
@xiaoxixi615 It looks like the file is a fragmented MP4 (not MKV) and it appears to play fine in the demo app on the dev branch (including the fix to remove assertions in #5162). Could you clarify what's actionable for us here? Or can this be closed?

**Comment by xiaoxixi615** [comment]
Thanks for your quick reply, the video can now be played with exoplayer, Please help to close this issue.
