### ISSUE TITLE
Subtitle  issue

### ISSUE THREAD

**Issue by MuVen** [google/ExoPlayer#5393]
I have a video (Narco) which has Spanish and English content.

The video has embedded subtitles for Spanish content. Whenever users speak Spanish English subtitles are being displayed.

Now I have synced external SRT file which displays subtitles for Spanish and English conversation. But I cant see the subtitles during English conversations. I think subtitle file which I tried to sync on top of existing subtitles is not overridden. Can some one help me on this.

**Comment by MuVen** [comment]
Narco video has subtitle of inbuilt TEXT_SSA textrenderer.

Im trying to add merge  SRT file, how to override existing subtitles.

      trackSelector = new DefaultTrackSelector(trackSelectionFactory);
      trackSelectorParameters = new DefaultTrackSelector.ParametersBuilder().build();
      trackSelector.setParameters(trackSelectorParameters);
      DefaultDrmSessionManager<FrameworkMediaCrypto> drmSessionManager = null;
      player =
                ExoPlayerFactory.newSimpleInstance(
                        /* context= */ this, renderersFactory, trackSelector, drmSessionManager);


      Format subtitleFormat = Format.createTextSampleFormat(null, MimeTypes.APPLICATION_SUBRIP, C.SELECTION_FLAG_FORCED, null);
      MediaSource subtitleSource = new SingleSampleMediaSource.Factory(dataSourceFactory).createMediaSource(uri, subtitleFormat, duration);
      mediaSource = new MergingMediaSource(videoSource, subtitleSource);
      player.prepare(mediaSource, false, false);

**Comment by erdemguven** [comment]
Displaying multiple subtitles at the same time isn't supported by default. See #5192.

**Comment by MuVen** [comment]
I dont want to show multiple subtitles at the same time but I want to
override the existing embedded subtitles with subtitles on my device

**Comment by MuVen** [comment]
@ojw28 

wrt your comment

""As a bit of extra context:

The use case that we've normally seen this question come up is around forced vs optional subtitles. For example if there's a sci-fi film where an alien says something in their alien language, the corresponding subtitle should always be shown (assuming it's intended that the viewer understand what's being said). Where-as when a human says something in a human language, the corresponding caption/subtitle is probably optional depending on the user selection."

How can i force subtitles selected from the internal storage to be shown instead of captions displayed while aliens speak their language.

can you help me where to tweak in the code please ...

**Comment by tonihei** [comment]
Please have a look at our guide for [track selection](https://google.github.io/ExoPlayer/guide.html#track-selection) and the documentation of the referenced classes. You can set the preferred language in the `trackSelectorParameterBuilder.setPreferredTextLanguage(...)` or directly select a specific track after creation by using  `trackSelectorParametersBuilder.setSelectionOverride(...)`.

**Comment by tonihei** [comment]
Closing as answered.
