### ISSUE TITLE
Question: any way to scale-crop the video not in the center?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [google/ExoPlayer#5394]
Background
--
We record a video of the user's face, and usually the face is located at the upper half.
Later we wish to view the video, but the aspect ratio of the `PlayerView` might be different than the one of the video.

The problem
--
The only way I've found to scale the `PlayerView` so that it won't stretch, is by using `app:resize_mode="zoom"` . But this is only for the center, meaning it takes a point of 0.5x0.5 of the video, and scale-crops from that point.

The question
--
Is there a way to specify the location on the video (in percentage, preferably) to start the scale-cropping?

Or at least to do it from the top?

Is it available on the API, or do I have to implement it myself?

If that's not the best place to ask this, I've posted the same question here:

https://stackoverflow.com/q/54216273/878126

**Comment by ojw28** [comment]
You currently need to do this yourself. I suspect the best way is to use `TextureView` directly, along with `TextureView.setTransform` to get the desired transformation.

**Comment by AndroidDeveloperLB** [comment]
@ojw28 I see. Can you please consider adding it? Or at least consider answering the question on StackOverflow, of how to do it?

**Comment by ojw28** [comment]
You can put a `TextureView` into your layout, and provide it directly to `SimpleExoPlayer` using `SimpleExoPlayer.setVideoTextureView`. `TextureView.setTransform` is then exactly an API for specifying a transformation for scaling and translating how the video is displayed within the view.

We don't have any plans to support this feature directly, I'm afraid.

**Comment by AndroidDeveloperLB** [comment]
Which transformation is suited for top-centerHorizontal-crop (like center-crop, but at the top, in the middle) ? 

Can you please consider adding it? Even ImageView has more scale/crop options...

**Comment by ojw28** [comment]
Not unless there's significant demand for it, which we don't have evidence of currently. I suspect that for most people, by the time they get to needing something as advanced as custom cropping, they also need/want to implement their own player UI from scratch regardless, to have full control over the experience.

**Comment by AndroidDeveloperLB** [comment]
I see. Is there an available transformation for this, or do I have to make one myself?
Assuming I've never done it, how much time could it take ? I have multiple tasks and this is one of them, and I need to guess how much time it will take me, as it might have a lower priority task than the others, maybe depending on how hard it is to implement it.

**Comment by ojw28** [comment]
You should do some proper research into `TextureView.setTransform`, figure out what you need to do, and come up with your own estimate.
