### ISSUE TITLE
exoplayer is playing from starting position when app closed and opened

### ISSUE THREAD

**Issue by Maneesh528** [google/ExoPlayer#5400]
Hello Team, 

Issue flow : Play the video --> pause --> close the App (now Android life cycle is in Pause state)--> Reopen --> Video is playing from starting point.

How to handle this issue. Can any one help.

**Comment by marcbaechinger** [comment]
You need to store the current window, the current position and possibly the state of playWhenReady each in a variable, so you can resume the player properly in onStart(). 

Have a look at [how the demo app is doing it](https://github.com/google/ExoPlayer/blob/release-v2/demos/main/src/main/java/com/google/android/exoplayer2/demo/PlayerActivity.java#L562). The values stored in this method are then [used to initialize the player](https://github.com/google/ExoPlayer/blob/release-v2/demos/main/src/main/java/com/google/android/exoplayer2/demo/PlayerActivity.java#L465).
