### ISSUE TITLE
Request: add nullability annotations for functions

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [google/ExoPlayer#5402]
For example, to SimpleExoPlayer.getVideoFormat() , which could return null:

```
  /**
   * Returns the video format currently being played, or null if no video is being played.
   */
  public Format getVideoFormat() {
    return videoFormat;
  }
```

This is especially important when developing using Kotlin, as the IDE doesn't consider Java returned values as nullable by default when writing on Kotlin.

**Comment by tonihei** [comment]
Thanks for reporting. We'll fix that one. 

Note that we added all the nullable annotations only recently and we may have missed some parts of the most used APIs.

**Comment by AndroidDeveloperLB** [comment]
Thank you.
Speaking of Kotlin, does it also make sense to make the library in Kotlin, or is it a useless thing to do?

**Comment by tonihei** [comment]
Java and Kotlin are interoperable, so there is no point in having the library in both languages.

**Comment by AndroidDeveloperLB** [comment]
That's not entirely true. They work fine with each other, but when coding via the IDE, you will notice issues between them, that the IDE doesn't help you with, as opposed to when writing only in Kotlin on both cases.

For example this case. On Kotlin you'd have to set nullability, but on Java, you don't have to, and since the IDE still can't handle nullability issues between them, it can always be an issue.

**Comment by tonihei** [comment]
Well, we do try to make sure it can be used in Kotlin and Java in the same way, that's why we are adding the annotations. We also did a few other things (e.g. moving Runnables to the last argument in each method to allow usages of the improved Kotlin syntax).

Besides that, the code is running fine in both languages and all improvements are only around ease of use and not actual functionality.

**Comment by AndroidDeveloperLB** [comment]
Of course.
I just asked if it might be better, because as much as I like Java, Kotlin helps more in those things
:)

**Comment by tonihei** [comment]
Closing as fixed.

**Comment by AndroidDeveloperLB** [comment]
@tonihei Thank you!
