### ISSUE TITLE
Question: Does ExoPlayer support "Motion Photos"? 

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [google/ExoPlayer#5405]
The camera app is able to create JPEG files that contain MP4 content within, called "Motion photos". I was wondering if ExoPlayer is able to handle such files. Here's how it's done, in case anyone is wondering:

https://android.jlelse.eu/working-with-motion-photos-da0aa49b50c

**Comment by andrewlewis** [comment]
It doesn't support them with the JPEG prefix. I think if you remove that, the remainder of the file should be a valid MP4 that can be loaded by ExoPlayer.

**Comment by AndroidDeveloperLB** [comment]
By "prefix" you mean the inner content of the file?
But this isn't the same as showing the content directly, as it will create new files. One for the video and one for the image. 
I already know those can be opened.
I asked if it's possible for ExoPlayer to open the video directly within such files.
As it's Google which made those files, it should be possible to use Google's library to open them directly.

**Comment by andrewlewis** [comment]
> By "prefix" you mean the inner content of the file?

I mean the start of the file, which is a JPEG as discussed in the blog post.

> But this isn't the same as showing the content directly, as it will create new files. One for the video and one for the image.

I'm not sure what you mean by 'it will create new files'. It's probably possible to implement an ExoPlayer `DataSource` that skips the prefix of the file without creating a separate MP4 stream on disk.

> I asked if it's possible for ExoPlayer to open the video directly within such files.

In that case the answer is no. You need to do a bit of extra work to remove the JPEG prefix.

**Comment by AndroidDeveloperLB** [comment]
The post I've shown talks about how to get to the parts of the MP4 content within the file.
I don't want to modify or create any new file. I want to play the file directly. The content is already available.
Is it possible for ExoPlayer to open the part of the file that is of MP4 content? To skip the JPEG part and play directly the part of the MP4 ?

That's the question.

**Comment by andrewlewis** [comment]
It should work if you implement a `DataSource` that skips the right amount of data from the start of the file.

**Comment by AndroidDeveloperLB** [comment]
So it is possible...
Cool. 
Thank you. I wonder if there are some samples I can work with. Is this really the term I should look for ("Motion Photos") ? Or does it have a more official one? Searching for it, I find GIF animations...

**Comment by andrewlewis** [comment]
The product name is "Motion Photos".

Probably worth mentioning: if there isn't a public specification/standard for this file format, I wouldn't want to rely on the format not changing in future (it's more like an implementation detail of whatever software produced the streams).

**Comment by AndroidDeveloperLB** [comment]
So it's something that's not official? But Google made it in its own products...
Does Google plan on using something else instead? What are the most popular formats for video-in-image-file?

**Comment by andrewlewis** [comment]
> So it's something that's not official? But Google made it in its own products...
> Does Google plan on using something else instead?

I'm afraid I can't really answer these questions as I don't work on Google Photos. It's also off-topic for this issue tracker. Sorry not to be more helpful!

> What are the most popular formats for video-in-image-file?

[HEIF](https://en.wikipedia.org/wiki/High_Efficiency_Image_File_Format) is probably a popular format for this.

**Comment by AndroidDeveloperLB** [comment]
HEIF became popular?
Isn't it mostly on IOS, as it costs money for the license of creating those?

I wish you guys talked to the Google Photos developers. You can achieve more by working together. Google Photos app shows video too, after all, as well as images and in between (animations) ...
