### ISSUE TITLE
Is there any way to specific video decode width/height for decoder?

### ISSUE THREAD

**Issue by tuesda** [google/ExoPlayer#5406]
as title

**Comment by erdemguven** [comment]
@tonihei could you look at this.

**Comment by tonihei** [comment]
I'm not sure I completely understand the question, but this is about selecting the video resolution to play, please have a look at our [track selection documentation.](https://google.github.io/ExoPlayer/guide.html#track-selection)

**Comment by tuesda** [comment]
@tonihei I read the documentation and found that is not what I need. My questions is for example If I have a video which dimension is 1920 x 1080, is there any way in Exoplayer to render this video with 960 x 540 dimension. Because I noticed that MediaCodec can specific video render dimension with MediaFormat, and Exoplayer is based on MediaCodec so I wonder if Exoplayer can do so too.

tks!

**Comment by tonihei** [comment]
If the video is 1920x1080, you have to send samples of this size to the MediaCodec. Note that this doesn't mean the displayed video can't be smaller. That depends on the surface size and the output is automatically scaled to surface size.

Can you explain what you would like to achieve?

**Comment by tonihei** [comment]
Closing as we haven't received further input.

**Comment by tuesda** [comment]
Sorry for delay reply.
I met a issue that a video dimensions is 3840 x 2160 and MediaCodec video dimension limit is 1920 x 1080, so I wonder is there some way to resize video in Exoplayer?

**Comment by ojw28** [comment]
ExoPlayer will decode video in its original resolution. The decoded buffers can then be rendered into any size `SurfaceView`/`TextureView` in your application UI during playback.

I don't really understand the question. If you're asking whether it's possible to use the library to resize a video file to create a new video file with a different resolution, then no that's not something we support.

**Comment by tuesda** [comment]
OK，thks your support
