### ISSUE TITLE
cache m3u8 

### ISSUE THREAD

**Issue by coderain1** [google/ExoPlayer#5408]
Cache the m3u8 file. The ts link in the m3u8 file is followed by a token. I want to remove the ts link after token as the key of the ts video streams cache.

**Comment by coderain1** [comment]
Each ts link in the m3u8 file will be followed by the information of a token. If the ts link with token is directly used as the key of the cache, the information of the later token will change, but the ts video will not change. In this way, the local ts cache will be invalidated and the ts video will be downloaded again. Therefore, to generate custom rules for the cached key, use the ts link with token removed as the cached key for this ts video.

**Comment by ojw28** [comment]
I do not understand if there's a question here, or what it is. Please clarify. Thanks.

**Comment by coderain1** [comment]
So, I would like to ask how to define the cache key of video for each ts in the local cache of m3u8 video；

**Comment by ojw28** [comment]
You can use a `CacheKeyFactory` for that. @erdemguven can provide more information if needed.

**Comment by yangwuan55** [comment]
Can I make a hlsmediasource with a native m3u8 file?
like this:

```

createMediaSource(Uri.parse("/file/path.m3u8"))

```
