### ISSUE TITLE
Distinguishing between Video and Audio-only HLS streams

### ISSUE THREAD

**Issue by nurne** [google/ExoPlayer#541]
Hey,

I want to distinguish between an HLS stream that has Video and Audio, and between an HLS stream that has only Audio.

The motivation here is that sometimes on low connectivity, the media server sends my Exo player an audio-only stream, and I want to be able to show an appropriate message to the user in this case

Can I somehow read the HLS chunks header?
Maybe assume audio-only stream when mime-type is audio-only for a few times?

Thanks your help!

**Comment by ojw28** [comment]
It will be possible to query the tracks in the media once #518 is implemented. Once that's done, you'll be able to query the tracks of the video renderer. If there are none, it's an audio only stream. I suggest following along that issue to track when the feature is delivered.

**Comment by nurne** [comment]
@ojw28 Understood. So can you please leave one of the tickets open for reference? ( #518  or #541 ) Thank you!

**Comment by ojw28** [comment]
You can now use the ExoPlayer.getRendererHasMedia method to determine whether or not each track has something to play.
