### ISSUE TITLE
Bug ( on either the emulator or ExoPlayer) : playing videos could be rotated even though it shouldn't

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [google/ExoPlayer#5411]
On the docs it says:
http://google.github.io/ExoPlayer/doc/reference-v1/com/google/android/exoplayer/MediaCodecVideoTrackRenderer.EventListener.html#onVideoSizeChanged-int-int-int-float-

> unappliedRotationDegrees - For videos that require a rotation, this is the clockwise rotation in degrees that the application should apply for the video for it to be rendered in the correct orientation. This value will always be zero on API levels 21 and above, since the renderer will apply all necessary rotations internally. On earlier API levels this is not possible. Applications that use TextureView can apply the rotation by calling TextureView.setTransform(android.graphics.Matrix). Applications that do not expect to encounter rotated videos can safely ignore this parameter.

And indeed it's always 0 as I've noticed, including on the emulator.
However, if I play the video on the emulator, it could be rotated compared to real device, even if I use API 28 there.

Please check it out. Run the sample of here:

https://github.com/AndroidDeveloperLB/ExoPlayerScaleCrop/

See attached images, showing how it looks like on emulator vs real device (Pixel 2 with Android P) :

![image](https://user-images.githubusercontent.com/5357526/51459942-cb84f680-1d62-11e9-9a5b-0fc1adca0610.png)

![image](https://user-images.githubusercontent.com/5357526/51459954-d3449b00-1d62-11e9-9d2b-d85401965454.png)

If you think it's an emulator issue, please report here:
https://issuetracker.google.com/issues

**Comment by AndroidDeveloperLB** [comment]
OK reported here in case it's related more to emulator:
https://issuetracker.google.com/issues/123222826

**Comment by ojw28** [comment]
This will be an emulator issue, not an issue with the library.

**Comment by AndroidDeveloperLB** [comment]
@ojw28 Thank you for checking it out. Please tell the emulator guys to handle this.
