### ISSUE TITLE
Exoplayer audio streming not work after upgrate andorid 9

### ISSUE THREAD

**Issue by itzikdev** [google/ExoPlayer#5413]
Issue #1234 
Exoplayer  (only audio streaming)not work on android 9 its always detected onPlayerError throw exception:
"com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect"
but lower android version 9 its work perfectly.

**Comment by ojw28** [comment]
Please provide complete information as requested in the issue template. It's also unclear what "upgrade" means in this context. Are you upgrading the device, or upgrading the target API level of the application?

**Comment by itzikdev** [comment]
hi ,
"upgrade" mean to Exoplayer api i used 2.9.3 last version that i see its work all android 5 - 8.1 
but same code on device android 9 its no working when i want play url streaming its always detected  onPlayerError and the cause of exception error: "com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect" and i do not know why.

**Comment by ojw28** [comment]
If you properly fill in the issue template then we will help investigate your issue.

**Comment by itzikdev** [comment]
**### Issue description**
Exoplayer ( audio stream ) not playing in device android 9 but working perfectly in version 5-8.1
in device android 9 always callback onPlayerError(ExoPlaybackException error) : error : "com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect" 

**### Link to test content**
http://glzwizzlv.bynetcdn.com/glglz_mp3

**### Version of ExoPlayer being used**
ExoPlayer 2.9.3

**### Device(s) and version(s) of Android being used**
xiaomi mi 8 android 9
OnePlus ONEPLUS A6003 android 9


**### Errors and log output**
No exception or error is thrown but callback onPlayerError always when buffering stream 
"onPlayerError: error? com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to http://glzwizzlv.bynetcdn.com/glglz_mp3"

thanks

**Comment by ojw28** [comment]
Please see [this blog post](https://android-developers.googleblog.com/2018/04/protecting-users-with-tls-by-default-in.html) about TLS being enabled by default as of Android 9. If you can't use `https://` you'll need to enable `http://` in your network security config.
