### ISSUE TITLE
Encrypted Video Playback with Exoplayer - AES/CBC & AES/CTR

### ISSUE THREAD

**Issue by shgrg1712** [google/ExoPlayer#5414]
Hello Team, 
                  I am using exoplayer for encrypted video playback . Following are the details

Case 1 :- 

Algorithm/mode/padding - AES/CBC/PKCS5Padding

Result :- Encryption is ok, Decryption is ok, But exoplayer unable to find MediaExtractor for the same.

Final  Result :- Video play fail

 
Case 2. 

Algorithm/mode/padding - AES/CTR/NoPadding

Result :- Encryption is ok, Decryption is ok. MediaSource for exoplayer is ok

Final  Result :- Video play success

Below is the error for case 1
com.google.android.exoplayer2.source.ExtractorMediaSource$UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor) could read the stream.

But same is working If I change the Encoding scheme.

I have checked other links on this forum but I could not get the answer to my question that why mode and padding is making this issue. 

Please help.

**Comment by shgrg1712** [comment]
More Information
  Encryption key size 16
  Initialization vector size 16

**Comment by ojw28** [comment]
You can't just change the scheme and expect everything to continue working (assuming you're editing the scheme in `AesFlushingCipher`). The scheme in that file is chosen specifically because it works well with random access (which is helpful for media - for example when seeking to the middle of the file).

If you change to a different scheme you most likely need to implement your own `DataSource` from scratch. If the scheme you choose doesn't allow random access, you'll most likely need to implement random access by reading and decrypting from the start of the stream (which is likely very slow and expensive, if you're streaming progressive media).

**Comment by shgrg1712** [comment]
Yes you are right. New Data soruce has been written . You can check this link for my source code

https://github.com/moagrius/EncryptedExoPlayerDemo

Only difference is in my code that encrypted file is already present on one URL and I am passing this encrypted file URL in this code 

String streamUrl ; //This url points to encrypted media
 new DownloadAndEncryptFileTask(streamUrl, mEncryptedFile, encryptionCipher).execute();

In DownloadAndEncryptFileTask, downloadAndEncrypt API I am doing this 

  InputStream inputStream = connection.getInputStream();
    FileOutputStream fileOutputStream = new FileOutputStream(mFile);
   // CipherOutputStream cipherOutputStream = new CipherOutputStream(fileOutputStream, mCipher);

    byte buffer[] = new byte[1024 * 1024];
    int bytesRead;
    while ((bytesRead = inputStream.read(buffer)) != -1) {
      Log.d(LOG_TAG,"downloadAndEncrypt: downloading");
      Log.d(getClass().getCanonicalName(), "reading from http...");
      fileOutputStream.write(buffer, 0, bytesRead);

    }

**Comment by ojw28** [comment]
If you want to use a different encryption scheme, and implement custom code to decrypt it, then that falls outside the scope of this issue tracker. The fact the player can't detect the format of the media indicates that your decryption code isn't working correctly.

**Comment by shgrg1712** [comment]
I got your point. May be code for open/read in Data source factory is not able to decrypt AES/CBC data but it is able to decrypt AES/CTR data. 

I have tried other things also. But all in vain. I know this forum is for Exoplayer so Data source class questions should not be asked here. But can you help me to find the implementation of DataSource for AES/CBC data or you can share me the forum which I can use to ask these questions

If possible , Please let me know. Otherwise no problem

Thanks 
Sheetal Garg

**Comment by ojw28** [comment]
I'd suggest you try on StackOverflow.

**Comment by shgrg1712** [comment]
Hello Oliver,
                   Can you help me in Exoplayer Demo App. 

I have downloaded application from https://github.com/google/ExoPlayer

I want to check the logic behind HLS encrypted play using Exoplayer. Please help me to configure the application or Let me know how to use it for this purpose if no configuration is required.

Thanks 
Sheetal Garg

**Comment by shgrg1712** [comment]
I have done cloning in Android Studio. I am running demo-ima app in the project.
