### ISSUE TITLE
Downloading not starting as expected in Hls offline downloads

### ISSUE THREAD

**Issue by meenukrishnamurthy** [google/ExoPlayer#5415]
I am downloading offline videos to be played in local.When i pause a download using stopDownloads() method,the download is stopped.When i try to resume the downloads using startDownloads() method of DownloadManager it does not start.I have also checked in the demo app it does not work there as well.Is there anything else i need to be doing other than calling this method.Please help.

**Comment by erdemguven** [comment]
Do you use DownloadService? If so unfortunately currently it isn't supported:
Support manually stopping/starting download when using DownloadService #4433
But we're working on it and should be fixed in a few weeks.

**Comment by meenukrishnamurthy** [comment]
Yes im using DownloadService.Is there any other way to achieve this.I actually want to pause and resume download when pause is clicked in my app.

**Comment by erdemguven** [comment]
Unfortunately there is no way currently. Please follow #4433 as it'll be updated when this feature is implemented.
