### ISSUE TITLE
Video pauses  playback when audio is not available

### ISSUE THREAD

**Issue by pawaom** [google/ExoPlayer#5418]
Video stops playback when audio is not available

I have a video it is 2 mins long, it has audio from start to 1 min 5 seconds, the video plays only till
1 min 5 seconds, and after that is pauses 

if we move to other position using 'player.seekTo' beyond 1 min 5 seconds,it goes to that position but its still paused

but if move to other position using 'player.seekTo' below 1 min 5 seconds,it goes to that position  and plays to 1 min 5 seconds

the video has has no audio beyond 1 min 5 seconds(not even a silent track)

I have tried other apps , the video does play beyond 1 min 5 seconds in those apps (they may not have a exoplayer)

the question is how to continue to play video beyond 1 min 5 seconds

**Comment by ojw28** [comment]
It's impossible for us to help with this unless you provide proper reproduction steps (e.g. sample media, a small patch to the demo app to reproduce the problem, etc). Please properly fill out the issue template.

**Comment by pawaom** [comment]
here is the file

https://ufile.io/56hru

**Comment by ojw28** [comment]
The video plays all the way through for me (using 2.9.3). Seeking past 1:05 also works fine. You may be using a very old version of ExoPlayer. In any case, we can't help further unless you properly fill out the issue template.

**Comment by pawaom** [comment]
ok thanks for the help yes I am using an old version of  exoplayer :r2.5.1, will chekc on the new exoplayer 

thanks again
