### ISSUE TITLE
How To Stream RTMP live in ExoPlayer ?

### ISSUE THREAD

**Issue by tarek360** [google/ExoPlayer#542]
hi :)
How can i stream RTMP live in ExoPlayer?

this is a RTMP sample:
rtmp://livestreaming.itworkscdn.net/smc4sportslive/smc4tv_360p

thanks

**Comment by ojw28** [comment]
We don't support RTMP.

**Comment by mandagod** [comment]
@ojw28 
I will later try it, do some extra work to support RTMP and RTMPT, do you have any suggest?
