### ISSUE TITLE
How to let Exo Player buffer a local file

### ISSUE THREAD

**Issue by prasadamsaiteja** [google/ExoPlayer#5420]
Am new to Exo player, trying to play a video. I want the Exo player to buffer the video file where the video file is parallelly downloading from the internet. I know Exo player supports streaming from an HTTP source, but my requirement is to stick to a local file currently.

Exo player is throwing this Loader Exception when seeking to a position which hasn't been downloaded.

> E/ExoPlayerImplInternal: Source error. com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected IllegalStateException: No valid varint length mask found

**Comment by erdemguven** [comment]
Do you use the DownloadManager to the download? If you do the download in a custom way and directly play the local file, there is no way for ExoPlayer to know the download hasn't been finished yet.
Check this post for an explanation on how to use DownloadManager and play downloaded content:
https://medium.com/google-exoplayer/downloading-streams-6d259eec7f95

**Comment by prasadamsaiteja** [comment]
My requirement isn't an HTTP source, it is a Torrent Protocol so am forced to use a custom way to download the file.

**Comment by erdemguven** [comment]
Some questions to clarify the problem:
* Do you do sequential download of torrent files, so they can be played during download?
* You want to play the files, not just buffer, right? I didn't understand the significance of buffering.

**Comment by erdemguven** [comment]
You can develop your own DataSource and if the seeked location isn't available you can priorite the download of that section and wait until it's downloaded. Some points to keep in mind:
1. DataSource reads need to return valid data
2. The file data may be requested non-sequentially (so downloading sequentially and blocking for data is quite likely to not be a good experience)
For (2), formats like matroska we often need to get data right from the end of the file before we can play anything.

**Comment by prasadamsaiteja** [comment]
Yes, I download the torrent file (single video file) sequentially, so the exoplayer plays fine until the user the seek to position where the file hasn't been downloaded. Thus exoplayer throws an error.

Can you please attach some reference on building a custom data source?

**Comment by erdemguven** [comment]
You can check out existing subclasses of DataSource:
[library/core/src/main/java/com/google/android/exoplayer2/upstream/ByteArrayDataSource.java](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/upstream/ByteArrayDataSource.java)
is one of the simplest DataSources but it doesn't do any IO.
[library/core/src/main/java/com/google/android/exoplayer2/upstream/FileDataSource.java](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/upstream/FileDataSource.java)
[library/core/src/main/java/com/google/android/exoplayer2/upstream/cache/CacheDataSource.java](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/upstream/cache/CacheDataSource.java)
