### ISSUE TITLE
Make it easier to play clear lead without waiting for DRM keys

### ISSUE THREAD

**Issue by noamtamim** [google/ExoPlayer#5421]
In DRM-protected files, usually there's a Clear Lead -- the first few seconds are clear. It allows playback to start without having to wait for license response, improving video start time (and user experience).
For example, in the first Widevine asset in media.exolist.json (https://storage.googleapis.com/wvmedia/cenc/h264/tears/tears.mpd), the first 10 seconds are clear.

In ExoPlayer, the state is never ready before the license is acquired.

Is there a flag to enable this? I didn't find any, and it's certainly not enabled in the demo app.

**Comment by ojw28** [comment]
The renderer (`MediaCodecVideoRenderer`/`MediaCodecAudioRenderer`) classes take a `playClearSamplesWithoutKeys` constructor argument that lets you enable this.

It's a bit awkward to change the value currently, since you'll probably need to provide your own `RenderersFactory`. We should perhaps make a method to turn it on on `DefaultRenderersFactory`, which would make it a lot easier. Marking as an enhancement to track doing that, although note you can already do what you want (it just requires more effort).

**Comment by noamtamim** [comment]
I've enabled `playClearSamplesWithoutKeys`, and the result is not as expected.
Now the first frame of the video shows immediately, but the video only starts playing after `HttpMediaDrmCallback.executeKeyRequest()` has finished.

To debug this issue I took the latest ExoPlayer+demo (2.9.4) and made the following changes.

### DefaultRenderersFactory
Set the above flag to true when creating `MediaCodecVideoRenderer`.

### ExoPlayerImplInternal
Changed `shouldTransitionToReadyState` to the following (adding logs):

```java
  private boolean shouldTransitionToReadyState(boolean renderersReadyOrEnded) {
    if (enabledRenderers.length == 0) {
      // If there are no enabled renderers, determine whether we're ready based on the timeline.
      return isTimelineReady();
    }
    if (!renderersReadyOrEnded) {
      Log.d("QQQ", "shouldTransitionToReadyState: !renderersReadyOrEnded");
      return false;
    }
    if (!playbackInfo.isLoading) {
      // Renderers are ready and we're not loading. Transition to ready, since the alternative is
      // getting stuck waiting for additional media that's not being loaded.
      return true;
    }
    // Renderers are ready and we're loading. Ask the LoadControl whether to transition.
    MediaPeriodHolder loadingHolder = queue.getLoadingPeriod();
    boolean bufferedToEnd = loadingHolder.isFullyBuffered() && loadingHolder.info.isFinal;
    final long totalBufferedDurationUs = getTotalBufferedDurationUs();
    final boolean shouldStartPlayback = loadControl.shouldStartPlayback(
            totalBufferedDurationUs, mediaClock.getPlaybackParameters().speed, rebuffering);

    Log.d("QQQ", "shouldStartPlayback=" + shouldStartPlayback + "; totalBufferedDuration=" + totalBufferedDurationUs/1000000f);

    return bufferedToEnd
        || shouldStartPlayback;
  }
```

### HttpMediaDrmCallback
Modify the last line of `executeKeyRequest()` from:
```java
return executePost(dataSourceFactory, url, request.getData(), requestProperties);
```

To:
```java
    final byte[] bytes = executePost(dataSourceFactory, url, request.getData(), requestProperties);
    Log.d("QQQ", "executeKeyRequest finished - sleeping for 1000ms");
    Thread.sleep(1000);
    Log.d("QQQ", "done sleeping");
    return bytes;
```

Logging that the license response is ready and sleeping for 1000ms, emulating latency in the network stack).


When playing a **clear** asset ("Google Glass (MP4,H264)"), and filtering the log on "QQQ", this is what I see:

```
QQQ: shouldTransitionToReadyState: !renderersReadyOrEnded
... [repeats ~15 times]
QQQ: shouldTransitionToReadyState: !renderersReadyOrEnded
QQQ: shouldStartPlayback=true; totalBufferedDuration=3.003
```

At this point playback begins.

However, when playing a **DRM** asset ("WV: HDCP not specified"), the renderers are not even ready before `executeKeyRequest()` returns:

```
QQQ: shouldTransitionToReadyState: !renderersReadyOrEnded
... [repeats ~20 times]
QQQ: shouldTransitionToReadyState: !renderersReadyOrEnded
QQQ: shouldStartPlayback=false; totalBufferedDuration=0.0
QQQ: shouldTransitionToReadyState: !renderersReadyOrEnded
QQQ: shouldTransitionToReadyState: !renderersReadyOrEnded
QQQ: shouldTransitionToReadyState: !renderersReadyOrEnded
QQQ: shouldTransitionToReadyState: !renderersReadyOrEnded
QQQ: executeKeyRequest finished - sleeping for 1000ms
QQQ: shouldTransitionToReadyState: !renderersReadyOrEnded
QQQ: shouldTransitionToReadyState: !renderersReadyOrEnded
QQQ: shouldTransitionToReadyState: !renderersReadyOrEnded
QQQ: shouldTransitionToReadyState: !renderersReadyOrEnded
QQQ: done sleeping
QQQ: shouldTransitionToReadyState: !renderersReadyOrEnded
QQQ: shouldStartPlayback=true; totalBufferedDuration=19.624
```

I expected the first 10 seconds to play even while waiting for `executeKeyRequest()` to finish. Is there anything else I need to enable to make it work?

**Comment by noamtamim** [comment]
If it helps, here's a patch with the changes mentioned above.
[patch.diff.txt](https://github.com/google/ExoPlayer/files/2784478/patch.diff.txt)

**Comment by ojw28** [comment]
What about audio?

**Comment by noamtamim** [comment]
We found the issue -- we changed `playClearSamplesWithoutKeys` to true in MediaCodec**Video**Renderer but not in MediaCodec**Audio**Renderer. So the playback was waiting for keys to decrypt the audio even though the video was ready to play.

**Comment by szaboa** [comment]
@ojw28 

> We should perhaps make a method to turn it on on DefaultRenderersFactory, which would make it a lot easier

If only this needs to be done, and nobody already did that then I can implement this.

**Comment by ojw28** [comment]
@szaboa - That would be great. How would you feel about making a slightly larger change that also adds setter methods for `drmSessionManager`, `extensionRendererMode` and `allowedVideoJoiningTimeMs`, and deprecates all of the constructors except for the one that takes just the `Context`? These methods could return `this`, so you could chain like:
```
DefaultRenderersFactory factory = new DefaultRenderersFactory(context)
    .setDrmSessionManager(xxx)
    .setPlayClearSamplesWithoutKeys(yyy)
    ...
```
I do think you should add `playClearSamplesWithoutKeys` as a parameter to `buildVideoRenderers` and `buildAudioRenderers`, which is a slightly unfortunate API change. Seems worth doing though, to make it clear to anyone overriding these methods what parameters they're supposed to be using.

Feel free to give this a go anyway! Thanks.

**Comment by szaboa** [comment]
Sure thing, thank you.

**Comment by szaboa** [comment]
@ojw28 
Pull request is created.
