### ISSUE TITLE
Response code 403

### ISSUE THREAD

**Issue by alexeyr15** [google/ExoPlayer#5422]
### Issue description
ExoPlayer reports InvalidResponseCodeException with response code 403 on fast switching between some live streams. I can assume that it is not exactly ExoPlayer issue but rather some specific server behaviour. So, I just wondeing is there some efficient way to work around this in ExoPlayer?

### Reproduction steps
1. Add links to live streams provided in email to media.exolist.json file of the demo app. Name them "Stream 1" and "Stream 2", for eaxmple.
2. Start the demo app and open Stream 1.
3. After Stream 1 is started to playback, immediately go back to the media list and open Stream 2.
4. After Stream 2 is started to playback, immediately go back to the media list and open Stream 1.
5. The demo app displays eror message "Playback failed" and logcat shows "InvalidResponseCodeException: Response code: 403".
Note that sometimes you need to repeat steps 3 and 4 multiple times to reproduce the issue but usually it is reproduced quite quickly. Also issue is not reporduced if you switch between streams after some delay, reproduced only on fast switching.

### Link to test content
Provided by email.

### Version of ExoPlayer being used
2.9.4

### Device(s) and version(s) of Android being used
Emulator Nexus 5X API 27, Pixel 2XL Android 9

**Comment by ojw28** [comment]
The exact same thing happens requesting the streams from the command line on my desktop machine (using `wget`). It's the server that's returning the 403 (forbidden) response. You'd have to ask whoever hosts the streams to find out why.

**Comment by asadmukhtar28** [comment]
@ojw28 i`m using youtube url and extract the data from url and make it like hls url but exoplayer didn`t able to play that url, it gives me the same error 403.

**Comment by ojw28** [comment]
YouTube do not allow direct playback of YouTube streams outside of YouTube, except via their [own SDKs](https://developers.google.com/youtube/android/player/).
