### ISSUE TITLE
Can you provide a m3u8 template for playready?

### ISSUE THREAD

**Issue by zhangabvc** [google/ExoPlayer#5423]
Exoplayer play failed when  this stream is choosed. 
[GANTZOpr.zip](https://github.com/google/ExoPlayer/files/2782316/GANTZOpr.zip)

Can you provide a m3u8 template for playready?

**Comment by ojw28** [comment]
Please provide complete information. For example an actual playable stream (just the media playlist isn't sufficient), the license server so we can request the keys, and a full bug report as requested in the issue template; captured shortly after playback failure.

**Comment by ojw28** [comment]
Closing due to lack of required information.
