### ISSUE TITLE
TrackSelector setPreferredTextLanguage and setPreferredAudioLanguage many tracks

### ISSUE THREAD

**Issue by WilliamGrondin** [google/ExoPlayer#5429]
If a media source has many subtitle/audio tracks in the same language, `setPreferredTextLanguage` and `setPreferredAudioLanguage` methods select the first track with the language or don't select anything.
How to select another track with the same language ?
MimeType:language tracks sample from the same media source :
`audio/true-hd:eng` 
`audio/vnd.dts:eng` 
`audio/ac3:eng` 
`application/pgs:eng` 
`application/x-subrip:eng` 
`application/pgs:fre` 
`application/x-subrip:fre`

**Comment by ojw28** [comment]
What's different about the multiple tracks (with the same type and language)? Is there anything in the track `Format` objects that allows them to be disambiguated from one another?

**Comment by WilliamGrondin** [comment]
HI,

If the audio tracks have the same language, they don't use the same audio codec. The user should choose the audio codec according to his audio system : TrueHd 7.1, DTS or AC3 2.0 for example.

It is about the TrackSelector class and its methods : setPreferredTextLanguage or setPreferredAudioLanguage.
This is the partial code allowing to select `eng` audio track  :
```
trackSelector.setParameters(
     trackSelector
         .buildUponParameters()
         .setPreferredAudioLanguage("eng"));
```
In the in the example list, this automatically select the "audio/true-hd:eng" audio track and works fine.
The question is : How to select another `eng` audio track as "audio/vnd.dts:eng" for example ?
Is there an alternative method to select audio track or subtitle track ?

**Comment by ojw28** [comment]
ExoPlayer will already be looking at the platform capabilities and selecting tracks that it thinks is supported. Although the extent to which the platform is aware of the audio system's capabilities might depend on how it's connected. I _think_ if it's via HDMI, then the platform should know, but @andrewlewis can confirm. So perhaps you don't need to do anything in your application code?

To answer the question itself: You can use selection overrides for specific track selections. See [this documentation](http://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/trackselection/DefaultTrackSelector.html). It may also be an option to add `setPreferred[Audio|Video|Text]Codec` type methods to `DefaultTrackSelector`, if that would help. I'm not sure how they would interact with all the other preferences though; it becomes quite hard to define the logic once you have multiple preferences that can compete with one another.

**Comment by WilliamGrondin** [comment]
I gave the audio codec for example, but this is the same problem for subtitles.
The media source can have multiple subtitle tracks in the same language and mimetype.
Some accessible media can contain :
english subtitle same as the audio
english subtitle containing non-speech information
english subtitle positioned to convey who is speaking
etc...

Thank you for your answer

**Comment by ojw28** [comment]
You can use selection overrides for that. Although it depends on whether you can disambiguate between these subtitles somehow. If you're not able to do so, but you know there's some flag in the media container that indicates the type of each track, then let us know and we can look at getting it into `Format` objects.

**Comment by ojw28** [comment]
Closing due to lack of further information.
