### ISSUE TITLE
Request: allow PlayerView to be clickable

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [google/ExoPlayer#5433]
This is a tiny request.

I've noticed that if I set an `OnClickListener` on the `PlayerView` (even if I add `android:clickable="true" android:focusable="true"` in the layout file), it doesn't respond to click events.

Please allow the view to be clickable, maybe even touchable...

The only solution for this, is to set the `OnClickListener` on the container, or a view that's on top of the `PlayerView` .

**Comment by ojw28** [comment]
I added the following code to the ExoPlayer demo app (in `PlayerActivity`), and clicks were received and logged fine, except in the case they were specifically handled by one of the view's interactive components (e.g. the seek bar and the playback control buttons):
```
playerView.setOnClickListener(new OnClickListener() {
   @Override
  public void onClick(View v) {
    Log.e("XXX", "onClick");
  }
});
```
So I'm not sure there's anything to do here.

**Comment by AHuminskyi** [comment]
Yeah, I also see that this question is opened. So i'm implemented a work around :)  I based my playerView under the view **(playerContainer)** . It will intercept all touch events including onClick() 

`playerContainer.setOnClickListener {
            if (videoPlayer.playWhenReady && videoPlayer.playbackState == Player.STATE_READY) {
                videoPlayer.playWhenReady = false
                play.visibility = View.VISIBLE
            }
        }
`

**Comment by AndroidDeveloperLB** [comment]
@ojw28 To me it doesn't work. Tested on Pixel 2 with Android P.
Check attached project and video to show issue.

[ExoPlayerTest.zip](https://github.com/google/ExoPlayer/files/2799843/ExoPlayerTest.zip)

**Comment by ojw28** [comment]
Ah... It looks like this is fixed already in `dev-v2`, but the fix hasn't been included in any release yet. I think it was fixed in 0a7745bc03c93709e178c578a4649eb534e8a9e0, which changed how `PlayerView` handles touch events to fix a warning. It likely didn't get cherry-picked into a minor `2.9.x` release because we didn't realize it was actually fixing something other than the Android Studio warning.

Leaving this issue open just to track getting the fix cherry-picked into a `2.9.5`, if there is one. Else it will be in `2.10.0`.

**Comment by AndroidDeveloperLB** [comment]
@ojw28 Can you please explain what is the origin of this issue? Why is there even something that changed the default behavior of View being clicked?

**Comment by ojw28** [comment]
Why don't you look in the referenced commit, if you're interested? `PlayerView` has logic for handling touches because it needs to display the player controls when this happens.

**Comment by AndroidDeveloperLB** [comment]
@ojw28 I see. Thank you

**Comment by eneim** [comment]
Also have this 'issue' before, my workaround is also to wrap it by a FrameLayout ... Really appreciate a 'fix' :D.

**Comment by ojw28** [comment]
Cherry-picked into the 2.9.5 release branch (which isn't released yet, but will be soon).

**Comment by ojw28** [comment]
Release branch commit: https://github.com/google/ExoPlayer/commit/e5bf47e8cfba66209a12d2e15312d66cc14dac5d

**Comment by naimishvinchhi** [comment]
Clickable in version 2.9.5. Thanks!
