### ISSUE TITLE
How to hide the notification bar when downloading in DemoDownloadService

### ISSUE THREAD

**Issue by EspoirX** [google/ExoPlayer#5436]
The DemoDownloadService in the demo has the related operation of the notification bar. When the download is completed, there will be a notification bar prompt, but in the actual project, I don't want to have such a prompt, but if the relevant code of the notification bar is removed, an error will be reported. Don't tell the bar when downloading, what should I do?

**Comment by ojw28** [comment]
I'm not entirely sure what the question is here. Are you saying you don't want a notification whilst the download is ongoing? Or you don't want a notification when the download is completed? Or something different? I don't really understand what you mean by a "prompt". Please clarify.

**Comment by EspoirX** [comment]
yes,I don't want a notification whilst the download is ongoing

**Comment by ojw28** [comment]
A notification is required for the service to be in the foreground, and the service is required to be in the foreground to ensure the process doesn't get killed. See the [Android foreground service documentation](https://developer.android.com/guide/components/services#Foreground) for mode details.

If you really do want to run the service in the background without a notification, then you can pass `FOREGROUND_NOTIFICATION_ID_NONE` as `foregroundNotificationId` to the `DownloadService` constructor. See [this documentation](https://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/offline/DownloadService.html#DownloadService-int-) for details. In the demo app, you can do this by changing [this line](https://github.com/google/ExoPlayer/blob/r2.9.4/demos/main/src/main/java/com/google/android/exoplayer2/demo/DemoDownloadService.java#L36) to use `FOREGROUND_NOTIFICATION_ID_NONE`. If you also want to get rid of notifications when download complete or fail, you need to modify `onTaskStateChanged` in the same class to not generate these notifications. Note that if the service is run in the background, the process may be killed by the underlying platform.
