### ISSUE TITLE
Audio discontinuity detected and faster playback

### ISSUE THREAD

**Issue by natario1** [google/ExoPlayer#5437]
I am recording mp4 videos by passing them to android MediaMuxer, then reproducing them with ExoPlayer. What happens is that I get a bunch of these logs:

```
2019-01-25 15:32:37.427 E/AudioTrack: Discontinuity detected [expected 1091337, got 1303242]
2019-01-25 15:32:38.586 E/AudioTrack: Discontinuity detected [expected 2464240, got 2676235]
2019-01-25 15:32:39.508 E/AudioTrack: Discontinuity detected [expected 3628253, got 3829002]
2019-01-25 15:32:40.865 E/AudioTrack: Discontinuity detected [expected 5175760, got 5398662]
2019-01-25 15:32:42.429 E/AudioTrack: Discontinuity detected [expected 7124338, got 7336242]
2019-01-25 15:32:43.586 E/AudioTrack: Discontinuity detected [expected 8497240, got 8709235]
2019-01-25 15:32:44.505 E/AudioTrack: Discontinuity detected [expected 9661253, got 9862002]
2019-01-25 15:32:45.865 E/AudioTrack: Discontinuity detected [expected 11208759, got 11431662]
2019-01-25 15:32:47.339 E/AudioTrack: Discontinuity detected [expected 13157338, got 13369242]
2019-01-25 15:32:48.506 E/AudioTrack: Discontinuity detected [expected 14530240, got 14742235]
```

And playback speed is faster than it should. I guess this is intended behavior but I would like to know

- Why is ExoPlayer doing this - increasing playback speed?
- Can this behavior be disabled?
- What does this tell about the video file/muxing process?

I am logging timestamps right before `muxer.writeSampleData()` and they all seem consistent, monotonic (for a single track. I'm hoping that MediaMuxer deals with synching audio & video). Am I passing wrong metadata to the codec, maybe?

If I mux video only, the playback goes as it should. & the audio encoding part is pretty much taken [from here](https://github.com/Kickflip/kickflip-android-sdk/blob/master/sdk/src/main/java/io/kickflip/sdk/av/MicrophoneEncoder.java).

**Comment by andrewlewis** [comment]
> What does this tell about the video file/muxing process?

It looks like the duration of audio data contained in the audio samples written to the AudioTrack is less than the duration implied by their timestamps.

**Comment by natario1** [comment]
Thanks for your answer @andrewlewis , is this the only possible cause? I am now computing each sample duration as follows (mono):

```java
int sampleFrequency = 44100; // sample/sec
int sampleBytes = 2; // bytes/sample (PCM16)
int byteRate = sampleFrequency * sampleBytes; // bytes/sec

while (...) {
    int frameBytes = read(...); // Typically 1024
    long frameUs = 1000000L * frameBytes / byteRate;
    totalUs += frameUs;
}
```

Which leads me to another situation where there are no error logs from ExoPlayer, no fast playback, but still audio is played faster than it should.

Just for "fun" I have tried applying a multiplier to this frameUs. If I make it big enough (> 1.1), I fall again into the `Discontinuity detected` case with fast playback. When smaller, I just have fast audio.

I even used the built-in `audioRecord.getTimestamp()` (API 24) instead of my computation. They do not differ so much. But the final video is still messed up as I said. I would be tempted to say that this doesn't look like a timestamp issue. I would appreciate any hint.

**Comment by ojw28** [comment]
It's highly likely there is something wrong with the media files you're trying to play. If you provide a sample file then we can tell you what's wrong with it. Without one, I'm not sure there's much we can do.

Aside: The sample code above is going to under-count time slightly, because each `frameUs` is rounded down, and then you accumulate those values. I doubt that's your actual problem though!

**Comment by natario1** [comment]
I have uploaded [a video](https://drive.google.com/open?id=15S4-75pIxKzewNymcMl36I65lP54kzU5) of about 20 seconds. I had a counter while recording. Each second I simultaneously tapped the notebook with my hand, and counted a number (in my language, sorry). You can see that

- video is OK (though prob. not smooth as it is when I record without audio)
- audio is faster than it should
- no ExoPlayer logs

This happens when computing timestamps as said above. If I use the official `audioRecord.getTimestamp()`, it gets a bit worse (discontinuities + faster playback).
I appreciate your answers, I understand that this is not really an ExoPlayer question anymore, so feel free to close if you can't take a look. Thank you!

**Comment by natario1** [comment]
I managed to make this work by improving threading a lot. My record thread was doing extra work thus losing some audio.

The way AudioRecord works is very confusing to me, but won't go into this here. Thanks to the team!
