### ISSUE TITLE
Guidance on decimating sample queue to reduce playback frame rate

### ISSUE THREAD

**Issue by trandroid** [google/ExoPlayer#544]
I have an MP4 with high (120fps) frame rate that I would like to play back at 30fps.
It seems like I could extend `ExtractorSampleSource` and override `readData()`. It would call `sampleQueue.getSample()` not once but rather in a loop, discarding video samples until it found one with a timestamp that matched the desired 30fps frame rate.
I would also have to make sure sync frames are injected when needed.

Is this a reasonable way to go?

**Comment by trandroid** [comment]
Maybe something like this in`readData()`? :
```
        if(mVideoTrack == -1
                && sampleQueue.getFormat().mimeType.startsWith("video")) {
            mVideoTrack = track;
        }

        if(mVideoTrack == track
                && mVideoLastSampleTimeUs != -1L) {
            sampleQueue.discardUntil(mVideoLastSampleTimeUs + mVideoDesiredIntervalUs);
        }

        if (sampleQueue.getSample(sampleHolder)) {
            boolean decodeOnly = frameAccurateSeeking && sampleHolder.timeUs < lastSeekPositionUs;
            sampleHolder.flags |= decodeOnly ? C.SAMPLE_FLAG_DECODE_ONLY : 0;
            if (havePendingNextSampleUs) {
                // Set the offset to make the timestamp of this sample equal to pendingNextSampleUs.
                sampleTimeOffsetUs = pendingNextSampleUs - sampleHolder.timeUs;
                havePendingNextSampleUs = false;
            }
            sampleHolder.timeUs += sampleTimeOffsetUs;
            if(mVideoTrack == track) {
                mVideoLastSampleTimeUs = sampleHolder.timeUs;
            }
            return SAMPLE_READ;
        }
```

**Comment by Ood-Tsen** [comment]
@trandroid 
Each [P frame](https://en.wikipedia.org/wiki/Inter_frame) require previous decoded picture.
We can't skip any one of those.

**Comment by Arqu** [comment]
However we can skip B frames as far as I understand, right? In that case we can play only I and P frames to speed things up, if that is not enough, we can move to I frames only and so on.

**Comment by Ood-Tsen** [comment]
@arqu, yes , B frames can be discarded.

Actually,  [Scalable Video Coding](http://ieeexplore.ieee.org/xpl/login.jsp?tp=&arnumber=4317636&url=http%3A%2F%2Fieeexplore.ieee.org%2Fxpls%2Fabs_all.jsp%3Farnumber%3D4317636) support change frame rate on runtime. But in my information, there is no product implements this option.

**Comment by ojw28** [comment]
As above, you can't just throw away frames, unless you know there aren't any inter-frame decoding dependencies or unless you carefully work out which frames to discard. You can set the C.SAMPLE_FLAG_DECODE_ONLY on a sample to still feed it to the decoder but then not render it, but that would still imply the decoder would need to be capable of decoding at 120fps, which is unlikely to be true on most Android hardware.

If there's a server involved anywhere in this setup, you should really transcode the content to a more appropriate frame-rate on the server-side

**Comment by Arqu** [comment]
Yes, server side transcoding is a viable option for those who want a fixed playback speed, however if you want to implement fast forwards, reverse or any kind of trick play, you have to get involved with manipulating which frames are fed into the decoder, which is more or less what I'm focusing on at the moment to implement for I-FRAME playback support for HLS, however it would be a nifty feature for other types of streams too, probably easily ported since it would run around the decoder, independent from how the data is acquired. In my opinion this part should be developed a bit further to enable a more fine grained control over which frames to decode and render. We all know that youtube feature to set speed to 1.25 or 2.0 to speed up playback (I'm ignoring audio at the moment, there are solutions for that too) which is great if you want to watch a video that you don't have enough time but don't want to skip over anything.

**Comment by trandroid** [comment]
Good tip for server-side transcoding. However, for the time being I have to deal with legacy servers that will serve original MP4. Unfortunately this results in the loader downloading many bytes that end up being thrown away.

Here's my updated ExtractorSampleSource code that *only* plays I-frames. 
```
   if(mVideoTrack == track) {
        do {
            sampleHolder.flags = 0;
            if(!sampleQueue.getSample(sampleHolder))
                break;
        } while(!sampleHolder.isSyncFrame());
        
        if (sampleHolder.isSyncFrame()) {
            ...
            return SAMPLE_READ;
        }

```

**Comment by Arqu** [comment]
Do you mind posting more of your code, or sending me the class per email since that snippet does nothing for me currently.
