### ISSUE TITLE
DefaultBandwidthMeter.Builder without context used in release-v2

### ISSUE THREAD

**Issue by clhols** [google/ExoPlayer#5440]
I can see that the dev-2 branch passes context to DefaultBandwidthMeter.Builder here:
https://github.com/google/ExoPlayer/blob/923aa420dfe6eb19eb05647d90d7c5aff62198fb/library/core/src/main/java/com/google/android/exoplayer2/ExoPlayerFactory.java#L443

But that has not been included in the two latest releases. Why is that?

**Comment by ojw28** [comment]
It's quite common for changes to not be picked up in minor releases (i.e. releases where only the bottom number of the version changes). The change will be in 2.10.0.
