### ISSUE TITLE
local video unseekable

### ISSUE THREAD

**Issue by xiaoxixi615** [google/ExoPlayer#5445]
@andrewlewis 

I'm testing a local video with ExoPlayer, and it can be played well but unseekable, I have searched some related issues and found a similar case #4856

but i don't know how to verify whether the cues are missing or incomplete due to the way the file was created.  Is my issue same as #4856?

Please help to figure out what problem my video is,and how to fix it. Thank you very much.

### Issue description
local video file can be played, but unseekable

### Reproduction steps
play the local video using ExoPlayer, the fast-forward button is disabled, and progress-bar is gray.

### Link to test content
try the following video:
https://drive.google.com/file/d/13hsMglgYnQv3wMMKRpZ3RXbgLX8t3gKf/view?usp=sharing

### Version of ExoPlayer being used
ExoPlayer version 2.9.4

### Device(s) and version(s) of Android being used
Nexus 6P 
100% reproduciable

**Comment by AquilesCanta** [comment]
>  Is my issue same as #4856?

Seems so to me. I'm sorry I cannot provide more assistance than what #4856 includes. You should try re-packaging the content in a seeking-friendly format. For instance, you can run

ffmpeg -i sony.mkv -c copy seek.mkv

Good luck.
