### ISSUE TITLE
Does Exoplayer support to play HLS audio only ?

### ISSUE THREAD

**Issue by shgrg1712** [google/ExoPlayer#5446]
Hello Team, 
                  I am using Exoplayer demo app to play HLS Audio only file. But it is showing "Can't sync bytes. May be not a transport stream".  I have checked internet websites but could not get good source of information.

Following Issue IDs , I have checked.   #73 , #1283

We have taken mp3 file to convert it into HLS media. But we are not able to play normal ts file 
 by exoplayer.

command 
ffmpeg -i 1.mp3 -hls_time 300 -hls_flags single_file audio.m3u8

Please help.

Thanks 
Sheetal Garg

**Comment by AquilesCanta** [comment]
Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).
