### ISSUE TITLE
Current state of HDR support on Android

### ISSUE THREAD

**Issue by davibe** [google/ExoPlayer#5448]
Sorry if this is not a reproducible issue. I need some help to figure things out. I started with a sample HDR video (which unfortunately I can't share). It's an hevc main10 HDR hls video. I tried to play it on a Google Pixel 3 (which is supposed to support HDR). If i play it using exoplayer on a GLSurfaceView colors are grayed out, which is typical when the screen does not reproduce correctly the HDR colors. If however I use a SurfaceView the colors are great. This suggests that HDR is working fine with the SurfaceView.

The strange thing is that reading here

- https://medium.com/google-exoplayer/tunneled-video-playback-in-exoplayer-84f084a8094d
- https://source.android.com/devices/tech/display/hdr.html

looks like tunneling is needed in order for HDR to work fine. However, if i debug the exoplayer code while running, I can see that [tunneling mode is NOT enabled](https://github.com/google/ExoPlayer/blob/b5beb32618ac99adc58b537031a6f7c3dd761b9a/library/core/src/main/java/com/google/android/exoplayer2/trackselection/DefaultTrackSelector.java#L1982) and [no video codec supports tunneling mode](https://github.com/google/ExoPlayer/blob/1c4ea26ff0ff530a1282398377a2cddfceefc3f6/library/core/src/main/java/com/google/android/exoplayer2/mediacodec/MediaCodecUtil.java#L142-L173) (I inspected all MediaCodecInfo instances - see my attached media_codecs.xml which i copied from the Pixel 3).

[media_codecs.xml.zip](https://github.com/google/ExoPlayer/files/2803746/media_codecs.xml.zip)

So why HDR is working on the Pixel 3 (or seems to be) ?

I also tried the same code (with the SurfaceView) on a Samsung S8 [(which is supposed to support HDR)](https://3g.co.uk/guides/hdr-mobile#) and in this case colors are washed out, not vivid and brilliant. So HDR is not working for sure

How do i know wether the device is actually showing HDR content or i need to fallback to a non-hdr variant ?

**Comment by andrewlewis** [comment]
https://source.android.com/devices/tech/display/hdr should address some parts of this, so please have a look at that and reply here if there are remaining questions. Thanks!

**Comment by davibe** [comment]
@andrewlewis that's the second link from my question. It's the first thing I have read. I try to update my questions to make them more clear.

**Comment by andrewlewis** [comment]
Quoting from that link:

> In Android 7.0, only HDR playback via tunneled mode is defined, but devices may add support for playback of HDR on SurfaceViews using opaque video buffers. In other words:
> * There is no standard Android API to check if HDR playback is supported using non-tunneled decoders.
> * Tunneled video decoders that advertise HDR playback capability must support HDR playback when connected to HDR-capable displays.
> * GL composition of HDR content is not supported by the AOSP Android 7.0 release.

Does the Samsung Galaxy S8 have a video decoder with tunneling?

**Comment by davibe** [comment]
Ok, thank you. So basically the Pixel 3 does HDR without tunneling. If a flagship phone such as the Pixel 3 does this I suspect many other phones do.

On the S8 after debugging it seems to me no video decoder supports tunneling. Additionally, I checked `Display.HdrCapabilities` and the array of supported HDR modes is empty. This is very strange.. Even youtube seems to support HDR on the S8.

The problem for me is: I need to know if the device supports or is playing HDR so i can fallback to a SDR manifest. How do you think this can be done ?

**Comment by andrewlewis** [comment]
I'd expect it would be sufficient to check for the presence of an HDR profile in the codec [profileLevels](https://developer.android.com/reference/android/media/MediaCodecInfo.CodecCapabilities.html#profileLevels) for the relevant codec and check the `Display.HdrCapabilities`. However, this is at odds with the documentation "There is no standard Android API to check if HDR playback is supported using non-tunneled decoders". @medialajos could you confirm if/how an app can choose whether to play HDR on Android N?

Agreed it's strange if the S8 is not declaring HDR support yet another app is using it, and there are no tunneled codecs. I wonder whether the app is doing tone mapping to produce SDR output from the HDR decoder output.

**Comment by davibe** [comment]
@andrewlewis I also noticed that exoplayer tries to play hevc even on older devices using sowftware decoders with terrible results. For example this is a Samsung Galaxy S4 with Android 5.0.1

![img_1040](https://user-images.githubusercontent.com/123929/52330773-8b767280-29f6-11e9-8c9d-7a1f7814908e.jpeg)

It's doing 1 frame every 10 seconds and its badly cropped with greenish colors :)

**Comment by andrewlewis** [comment]
We should check if this decoder is advertising support for a format that it can't play. It would be good if you could take a bug report after playing the stream in the demo app. Please file a separate issue for that and attach the bug report so we can keep this on the topic of 'current state of HDR support'.

**Comment by andrewlewis** [comment]
To follow up on the earlier point about detecting HDR support: on Android N particular devices may support HDR without tunneling, but this is not standardized so there is no standard way that capabilities may be reported. (I'm also not aware if there are non-standard ways that capabilities are reported in practice, and this would be up to individual vendors.)

**Comment by davibe** [comment]
Just to add some noise. I am testing HDR mode on Huawei devices like the P30 PRO. With the ExoPlayer demo (2.9.5), as well as my app, hdr works fine in landscape mode but it stops working as soon as i switch ti portrait. The colors become grayed out as if the display was not hdr capable.
