### ISSUE TITLE
Download Encrypted HLS media on device and Convert it into MP4 file

### ISSUE THREAD

**Issue by shgrg1712** [google/ExoPlayer#5449]
Hello Team,
                  I have new requirement in which I need to download encrypted HLS media from Amazon s3 server which means download m3u8 and ts files. After downloading the encrypted HLS media , I need to convert the data into normal mp4 (First do decryption) file on device. 

I am posting this requirement on exoplayer forum because I have seen one post which shows that exoplayer support such functionality. URL of post is mentioned below.

https://medium.com/google-exoplayer/downloading-streams-6d259eec7f95

Can you provide me step by step guide to  implement this functionality.

Thanks
Sheetal Garg

**Comment by AquilesCanta** [comment]
ExoPlayer does not support transmuxing contents. ExoPlayer only supports downloading, as described in the post. Implementing transmuxing in ExoPlayer falls out of the scope of this issue tracker, sorry.

**Comment by shgrg1712** [comment]
Hello Santiago ,
                         Thanks for reply. I am appreciating your feedback on my question. 
That's OK if Exoplayer does not support transmuxing But when I am trying to download using exoplayer demo app I am not getting downloaded content. I am getting any exception either. Player is able to play the content but I could not find any downloaded file.

Here are the details.
App used is as follows
https://github.com/google/ExoPlayer

PlayerActivity.java
I have changed the temp URL in buildMediaSource for HLS media. 

After that I have played the demo app .
HLS -> Apple TS Media playlist

After that I have checked the folder Android\data\com.google.android.exoplayer2.demo\files\download

But it was empty. Is there any other thing need to do in exoplayer to get the downloaded file.

**Comment by AquilesCanta** [comment]
@erdemguven, would you kindly assist @shgrg1712?

**Comment by shgrg1712** [comment]
Hello Erdem,
                    I have resolved the download issue .Now I am able to download the HLS stream using exoplayer demo app.

After download complete, when I opened the file explorer to check downloaded files then it is showing files with extension .exo 

Also one more file is present in download directory cached_content_index.exi. 

Please tell me about these files. As per my understanding .exo files are similar to .ts files and cached_content_index.exi is similar to .m3u8 file.

Help me to understand these files.

Can I convert the downloaded data into normal file or not. By using other tool or SDK. Since I donot know about these files So I could not find about the conversion of these files.

Best regards
Sheetal Garg

**Comment by shgrg1712** [comment]
Hello Erdem,
                    Kindly update .

Thanks 
Sheetal Garg

**Comment by shgrg1712** [comment]
Hello Erdem,
                    I have gathered the information about HLS media download in form of exo and exi files. I am able to play the video offline also since data is available in cache.

But I am facing one issue. If I play the video offline , video is getting stuck in last 35 seconds
For example 
Total Duration: 10 minutes 35 seconds
Video Played till :- 10 minutes

Video is unable to play for last 35 seconds. This is happening with every video . Last 35 seconds are unable to play.

I want to know if this is known issue in demo app or this may be issue related to media content we have made.

Please help to reply on this issue. I got stuck over here. I am not getting any failure logs also regarding this matter.
You can also tell me if I need to check special logs for this issue.

Thanks 
Sheetal Garg

**Comment by AquilesCanta** [comment]
Please @shgrg1712 keep the issue well scoped. If you have encountered a bug, please file a new issue including all information requested in the issue template.

**Comment by erdemguven** [comment]
During download ExoPlayer split downloaded files into smaller files. [The default size](https://github.com/google/ExoPlayer/blob/1c4ea26ff0ff530a1282398377a2cddfceefc3f6/library/core/src/main/java/com/google/android/exoplayer2/upstream/cache/CacheDataSource.java#L58) of the these files is 2MB but can be overwritten using [CacheDataSource constructor](https://github.com/google/ExoPlayer/blob/1c4ea26ff0ff530a1282398377a2cddfceefc3f6/library/core/src/main/java/com/google/android/exoplayer2/upstream/cache/CacheDataSource.java#L198). If the size is bigger than your ts files then the files won't be split and you can assume each exo == 1 ts file.

On the development branch we made changes so that HLS, DASH, Smooth Streaming are not split anymore so you don't need to do anything.

exi file is the index file which holds the content metadata.

**Comment by ojw28** [comment]
As a more general point, you should avoid making any assumptions about the files and their formats. We make no guarantees not to make breaking changes in the future. The only safe way to read cached or downloaded data is back through ExoPlayer's own components. You should not try to read the files directly from disk.
