### ISSUE TITLE
 com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 502

### ISSUE THREAD

**Issue by iikimamhambali** [google/ExoPlayer#5450]
Good evening,

We want to asking about exo player using the HLS media source, in case we using m3u8 file. Only several url play normally, but we found url m3u8 file can't play with this error message : 

"com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 502"

Hope you can help us to solve this issue, thank you

Best regards,

**Comment by AquilesCanta** [comment]
That means the server you are hitting is responding with a [502](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#5xx_Server_Error).  There is not much we can do about it. Without any more information, I can only assume it's a server-side issue. Have you managed to play with any other player? If so, please fill the [issue template](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE) and we can go from there.
