### ISSUE TITLE
Issues by playing DASH Widevine DRM HD content on Google Pixel C

### ISSUE THREAD

**Issue by userdimi** [google/ExoPlayer#5451]
**Issue description**
I'm trying to play DASH Widevine DRM HD content with the exoplayer demo app on Google Pixel C. But after a few seconds the video is stopping and only the audio is running in the background. 

**Reproduction steps**
Start the video from the sample chooser. Click on the button "video". Check the "1280 x 720 5,80 Mbit/s" or "1920 x 1080, 7,80 Mbit/s" checkbox.  Apply my choice with ok button. 

**Expected behavior**
The player plays the video and audio

**Actual behavior**
The screen is black and the player don't play video or audio

**Link to test content**
Will be send to dev.exoplayer@gmail.com with a subject  "Issue #5451".

**Version of ExoPlayer being used**
2.9.4 release-v2

**Device(s) and version(s) of Android being used**
Google Pixel C (Android 8.1.0 Api 27)

**A full bug report captured from the device**
Will be send to dev.exoplayer@gmail.com with a subject  "Issue #5451".
Here is my [logcat](url) snippet

**Comment by AquilesCanta** [comment]
Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

Sample media and a full bugreport (run `adb bugreport` briefly after the issue occurs) are particularly important here.

**Comment by userdimi** [comment]
@AquilesCanta Thank you for your quick response. I've updated my issue.

**Comment by AquilesCanta** [comment]
Hi, I have reported the issue to the internal media team. I cannot make any promises, specially considering it is a device specific device. Please make sure the stream keeps running, until they get to see it. I will write back once they provide a reply.

**Comment by userdimi** [comment]
Hey @AquilesCanta  thank you very much.

**Comment by ojw28** [comment]
Internal ref: b/123697481

**Comment by userdimi** [comment]
any updates on this issue?

**Comment by rrfrias** [comment]
Unfortunately the device is End-of-Lifed. Android 8.1.0 was the last release for the Pixel C and we are unable to provide updates.
