### ISSUE TITLE
Dead lock issue during playback in Tunnel mode

### ISSUE THREAD

**Issue by KaiYeYang** [google/ExoPlayer#5456]
[Issue description]
I'm testing DASH stream in Tunnel mode, the ExoPlayer produce a dead lock issue when calling setVideoScalingMode function on frame rendered event.
 
[Reproduction steps]
1. Configure ExoPlayer play mode to Tunnel mode, configure code as follow.
      trackSelector = new DefaultTrackSelector(trackSelectionFactory);
      trackSelector.setParameters(trackSelectorParameters);
      **trackSelector.setTunnelingAudioSessionId(C.generateAudioSessionIdV21(getApplicationContext()));**
      lastSeenTrackGroupArray = null;
2. Compile the ExoPlayer apk and play a DASH stream.
3. Sometime the ExoPlayer will produce the dead lock issue during playback.

[Version of ExoPlayer being used]
2.9.0 release-v2, Android P
 
[Analysing]
In MediaCodec.java, the handleMessage and postEventFromNative functions will require a same lock(mListenerLock), if the handleMessage function got the lock on EVENT_FRAME_RENDERED event, and it's calling the setVideoScalingMode function, this operation will call awaitResponse in ALooper.cpp and wait the setVideoScalingMode finish. But on this time, the ALooper is delivering the next EVENT_FRAME_RENDERED event to MediaCodec.java, and it cann't get the lock(mListenerLock), it had been blocked by getting mListenerLock lock, so the ALooper cann't deliver setVideoScalingMode message, and the setVideoScalingMode operation also be blocked.
 
[Simple sequence as follow]
== ALooper.cpp[deliver(render message)] -> MediaCodec.java[postEventFromNative](trying to get mListenerLock).
== MediaCodec.java[handleMessage[EVENT_FRAME_RENDERED]](had got mListenerLock lock) -> MediaCodecVideoRender.java[processOutputFormat] -> MediaCodec.java[setVideoScalingMode] -> ALooper.cpp[awaitResponse].

I didn't found a good solution to fix this issue, I think calling the setVideoScalingMode on frame render event maybe not suitble, can anybody give some advise?

Thanks!

**Comment by AquilesCanta** [comment]
I'll try to reproduce and reach back.

**Comment by AquilesCanta** [comment]
Hi @KaiYeYang, could you please provide a bugreport? Have you tried more than one device/android version? Is it possible it is device specific? Also please:

* Provide more precise reproduction steps.
* Clarify how easy it is to reproduce.

I have tried to reproduce with no luck.

**Comment by KaiYeYang** [comment]
Hi @AquilesCanta , thanks for your reply. I had do more analyse and draw a event process sequeue diagram as follow link:
[https://drive.google.com/file/d/1DHQMf4u-cmrqtw3CkmuB7fpVZ4_lG5OE/view?usp=sharing](url)

In this diagram, there are three threads:
1. Thread One: ACodec Message Deliver: this thread proccess the codec message and post these message to MediaCodec.
2. **Thread Two:** MediaCodec&JNI Message Deliver(C++ framework): this thread proccess all messages which in MediaCodec&JNI ALooper message queue, like frame rendered message, setparameter, ......
3. **Thread Three:** MediaCodec JNI handlemessage(MediaCodec Java): this thread handle all messages which in MediaCodec.java, like frame rendered message.

When play some 4K streams in Tunnel-mode, the thread two was blocked in Step 17(it was because the mListenerLock had been gotted by thread three first), and the thread three was blocked in Step 38. Step 38 can only be waked in Step 27, but thread two had been blocked, it cann't deliver setParameters message. 
**Thread three**: had got mListenerLock and do RepliesCondition.wait and wait thread two to proccess setParameters message.
**Thread two**: cann't get mListenerLock and cann't deliver setParameters message.
These two threads were blocked by each other, the ExoPlayer is in dead lock status, and cann't proccess any user command except kill the proccess.

I think this is the limit of rendered frame event of MediaCodec, we cann't call MediaCodec functions on this event.

Thanks!

**Comment by KaiYeYang** [comment]
Hi, @AquilesCanta , I delete the codec.setVideoScalingMode(scalingMode) in processOutputFormat function in MediaCodecVideoRenderer.java file, this issue won't produce.

**Comment by AquilesCanta** [comment]
Thanks for the precise description. Would you kindly provide the stream with which you are reproducing? If you wouldn't like it to be public, please send it to dev.exoplayer@gmail.com. Thanks!

**Comment by KaiYeYang** [comment]
Hi, @AquilesCanta , I am so sorry that I cann't provide the stream to you, but I will try to find a public stream to reproduce this issue and will share it to you.

Thanks!

**Comment by AquilesCanta** [comment]
No, thank you for the effort you are putting into this. I'll try again once I have a stream which which your are able to reproduce.

**Comment by AquilesCanta** [comment]
Also, please do include a bugreport obtained after reproducing the issue. You can also send that to dev.exoplayer@gmail.com.

**Comment by KaiYeYang** [comment]
Hi, @AquilesCanta , I had found a public stream which can reproduce this issue, please download the stream and configure the test enviroment as follow:
Step1: download the public stream, the link is:
  [http://dash.edgesuite.net/dash264/TestCasesUHD/2a/1/](url)
Step2: download the http server tool, the link is:
  [https://drive.google.com/file/d/1BWQo8WX2RpsMSCooFfzpEi4iK6eBoUbj/view?usp=sharing](url)
Step3: run the http server tool, and add a virtual link of the test stream which download in Step1.
Step4: configure the http download limit speed(1050KB/s) by following picture.
![http server config](https://user-images.githubusercontent.com/47199525/52893193-c043b000-31d4-11e9-8c15-02df91921b7c.png)
Step5: play this test stream in tunnel mode, the it can reproduce the issue.

Thanks!

**Comment by KaiYeYang** [comment]
Hi, @AquilesCanta , What's the bugreport content should I provide? thanks!

**Comment by KaiYeYang** [comment]
Hi, @AquilesCanta , can you reproduce this issue? thanks!

**Comment by AquilesCanta** [comment]
Hi @KaiYeYang, just now I get to see this. I'll try to reproduce and reach back. Hopefully I'll be able to try this week. Thanks for your patience!

**Comment by AquilesCanta** [comment]
Hi @KaiYeYang, how long does it usually for the deadlock to occur? Do you have any advice for me to increase the chances of the issue occurring?

As requested above, please provide a full bugreport. You can obtain a bugreport by executing `adb bugreport` shortly after reproducing the issue.

**Comment by AquilesCanta** [comment]
I'll close this due to lack of activity and a bugreport. I'll reopen if the required information is provided below.
