### ISSUE TITLE
Using custom receiver in cast with exoplayer

### ISSUE THREAD

**Issue by meenukrishnamurthy** [google/ExoPlayer#5458]
Hi i am having a question with regards to using cast with exoplayer.
We are planning to write a custom receiver for cast.The cast sdk mentions that we need to send the receiver app id from the sender app(android app).Where is this to be provided if we are using exoplayer cast extension.

**Comment by AquilesCanta** [comment]
The app id is provided by the OptionsProvider, which is in turn defined in the AndroidManifest of your app. Have a look at AndroidManifest.xml in the demo app. You'll find a line like:

```
<meta-data android:name="com.google.android.gms.cast.framework.OPTIONS_PROVIDER_CLASS_NAME"
        android:value="com.google.android.exoplayer2.ext.cast.DefaultCastOptionsProvider" />
```

And then in DefaultCastOptionsProvider there is

```
  @Override
  public CastOptions getCastOptions(Context context) {
    return new CastOptions.Builder()
        .setReceiverApplicationId(CastMediaControlIntent.DEFAULT_MEDIA_RECEIVER_APPLICATION_ID)
        .setStopReceiverApplicationWhenEndingSession(true).build();
  }
```

You can replace the id. It's worth mentioning we are releasing the initial version of our own receiver app in approximately 2 weeks. It would be great if you could help us test it once it's pushed to the public repo.

**Comment by meenukrishnamurthy** [comment]
Sure will do the needful.

**Comment by meenukrishnamurthy** [comment]
Thanks for the quick response.
