### ISSUE TITLE
Can I play YouTube video in ExoPlayer

### ISSUE THREAD

**Issue by androidpk** [google/ExoPlayer#5466]
I want to play YouTube video in ExoPlayer.  Does it support.

**Comment by ojw28** [comment]
No. The [YouTube Android Player API](https://developers.google.com/youtube/android/player/) is the official way to play YouTube videos on Android. Please see https://github.com/google/ExoPlayer/issues/4429 and https://github.com/google/ExoPlayer/issues/2160 for more information.
