### ISSUE TITLE
explorer2 subtitle arabic not readable

### ISSUE THREAD

**Issue by AskMeCode** [google/ExoPlayer#5467]
explorer2 subtitle arabic not readable.

`String mSrtUri ="http://ddl3.data.hu/get/287029/11669682/TadTheLostExplorer.srt";`

`textFormat = Format.createTextSampleFormat(null, MimeTypes.APPLICATION_SUBRIP, Format.NO_VALUE, "ar");`
`textMediaSource = new SingleSampleMediaSource(Uri.parse(mSrtUri), dataSourceFactory,textFormat, C.TIME_UNSET);`
`sampleSource = new HlsMediaSource(Uri.parse(mUri), dataSourceFactory, mHandler, this);`
`mediaSource = new MergingMediaSource(sampleSource, textMediaSource);`

if some one give me example please to help

**Comment by ojw28** [comment]
You need to provide a sample subtitle file for us to provide guidance on this.

**Comment by AskMeCode** [comment]
Thank you dear @ojw28  I have add a link.

**Comment by ojw28** [comment]
This is a duplicate of #3644. In this case the file uses Windows-1256 encoding.

If you have control over the subtitle files themselves, changing them to use UTF-8 should fix the problem, and is generally recommended as per the [Windows-1256 Wikipedia page](https://en.wikipedia.org/wiki/Windows-12560).

**Comment by AskMeCode** [comment]
Thank you dear @ojw28. :)
