### ISSUE TITLE
ExoPlayer keeps playing even when the delta between playbackPositionUs and startTimeUs of the next chunk is relatively small for fetching new data

### ISSUE THREAD

**Issue by alex-tilkin** [google/ExoPlayer#5468]
### Issue description
I have modified the method `evaluateQueueSize` of `AdaptiveTrackSelection` so it always returns the minimum size (two elements, the second is the one that currently being played, satisfying the condition `if(queue.get(i).startTimeUs <= playbackPositionUs && queue.get(i).endTimeUs) >= playbackPositionUs)`). I'm trying to make the player executing the most aggresive queue discaring it can do.

After the `evaluateQueueSize` method I'm measuring `queue(2).startTimeUs-playbackPositionUs` (let's call it DELTA) which varies from ~0ms to the size of the chunk in which in my case is 500ms (make sense).

After the queue evaluation, queue update etc.. there are several major steps that happening for populating the queue again (`getNextChunk` of `ChunkSource`, `load` of `ContainerMediaChunk`, `read` of `Extractor` etc.), in other words, it takes time (I have measured it) to populate the `queue` and update the `SampleQueue` again for the `MediaCodec` to read it again.

My question, how can it be that sometimes the DELTA is less than 50ms yet the player doesn't freeze (enters rebuffering process)?

This is the graph describing the delta:
<img width="705" alt="screen shot 2019-02-03 at 11 21 40" src="https://user-images.githubusercontent.com/4203651/52175020-f11ff000-27a5-11e9-9fbd-fe9d21f94730.png">

### Reproduction steps
N/A

### Link to test content
N/A

### Version of ExoPlayer being used
Latest

### Device(s) and version(s) of Android being used
SAMSUNG Galaxy S6 Edge

### A full bug report captured from the device
N/A

**Comment by tonihei** [comment]
There is no apparent problem with a short buffer. The player can continue to play the remaining 50ms of buffer if they are available before it would enter the buffering state.

In general, if you want to set an upper bound on the buffer size, please use the `LoadControl` for that and not the `evaluateQueueSize` method as the load control prevents buffering in the first place while `evaluateQueueSize` discards already buffered data, which is extremely wasteful.

**Comment by tonihei** [comment]
Closing due to lack of further information.
