### ISSUE TITLE
Question about widevine and playready

### ISSUE THREAD

**Issue by ThorAsgardDev** [google/ExoPlayer#5469]
Hello,

I have a stream provider that provides smooth streams that must be decoded using widevine.
The problem is that the smooth manifests are not correct, they contains a playready UUID and its corresponding "protection tag" (it contains a WRMHEADER tag).
If I try to play the file directly using ExoPlayer, no compatible renderer are found on my Android devices because ExoPlayer is looking for a renderer that supports playready (and playready is rarely supported on Android devices (except for Android TV)).
So, inside the manifest, I have replaced the playready UUID by the widevine UUID (I didn't modify the protection tag).
Now compatible renderers are found, but I have another problem. The challenge (request.getData()) from the mediaDrmCallback seems to be incorrect (it is not accepted by the license server). I think that the challenge is not correct because it contains the playready WRMHEADER from the manifest protection tag.

I would like to "convert" the playready protection tag contents to a widevine one, but I don't find any information about the expected protection tag format for Widevine smooth streams.
Could you please tell me if my hypothesis is correct (my problem comes from the playready protection tag) and if yes how to "convert" it to a widevine one.

Thanks a lot for your time.

**Comment by ojw28** [comment]
If the manifest claims to support only PlayReady, on what basis are you assuming that it also supports Widevine? In any case:
* If the manifests are incorrect then you should ask the stream provider to fix them.
* As per our [supported formats page](https://google.github.io/ExoPlayer/supported-formats.html) ExoPlayer doesn't support Widevine for SmoothStreaming in any case. It's a combination that we haven't seen any significant streaming providers using. You should consider asking the provider for DASH streams, if possible.

**Comment by ojw28** [comment]
I'm not even sure Widevine for SmoothStreaming is a thing. It could probably be made to work, but I can't find any documentation about it anywhere. All I've found is someone from Widevine saying it's not a thing, in https://github.com/google/ExoPlayer/issues/1622.

**Comment by ThorAsgardDev** [comment]
Thanks for the reply.
I know that is support widevine because I can play these streams on Kodi using widevine.
I don't know why but Kodi gives me a correct challenge whereas ExoPlayer doesn't. Kodi probably doesn't care about the UUID and protection tag info from the manifest.

I can't ask nothing to the provider so dash format or update manifest to be correct for widevine is not possible... :(

**Comment by ojw28** [comment]
How do you know that Kodi is using Widevine? If you don't have a relationship with the streaming provider then what license server are you using? This sounds quite unusual.

**Comment by ThorAsgardDev** [comment]
I know that Kodi uses Widevine because I have programmed it to use Widevine and it can play on my Android devices that don't support playready.
I pay for this stream service but the application of the provider is totally bugged. So I just want to make a good one for me.
What I don't really understand is the link between the protection tag from the manifest and the challenge. I can see from the ExoPlayer code that the protection tag is put in a psshbox and the KID is also read from this protection tag, but then i'm lost.

**Comment by ojw28** [comment]
It's possible Kodi has a software PlayReady implementation, and is using that. It sounds very unlikely that a provider is distributing SmoothStreaming streams that work with Widevine. As above, I can't find anything to suggest this combination is a thing. That aside, this sounds beyond the scope of this issue tracker, sorry.

**Comment by ThorAsgardDev** [comment]
Kodi has a very basic implementation of drm.
Thanks for your help.
Is there any place to live chat with ExoPlayer developpers ? irc ? slack ? other ?
