### ISSUE TITLE
Examples for adding external subtitle sources

### ISSUE THREAD

**Issue by scan** [google/ExoPlayer#547]
I'm trying switch from a non-working `MediaPlayer` to ExoPlayer. Playback runs fine, and I need to add subtitles/closed captions to the HLS stream. In the demo, `Eia608TrackRenderer` is used to render subtitles encoded in the manifest.

However, in the setup I have to use, the subtitles are not in the manifest, but are WebVTT files provided as URIs. I was trying to figure out how to add these to the existing `HlsRendererBuilder` from the demo app, but failed.

Is there a sample code or a hint on how to exactly add external WebVTT-Urls to that RendererBuilder? What I have is a list of language-Url pairs, so I hope it's possible to add several different sources to the player for the subtitles.

**Comment by ojw28** [comment]
Not implemented yet, and tracked by #151
