### ISSUE TITLE
Incomplete playback on downloaded Encrypted HLS stream 

### ISSUE THREAD

**Issue by shgrg1712** [google/ExoPlayer#5471]
Hello Erdem,
I have gathered the information about HLS media download in form of exo and exi files. I am able to play the video offline also since data is available in cache.

But I am facing one issue. If I play the video offline , video is getting stuck in last 35 seconds
For example
Total Duration: 10 minutes 35 seconds
Video Played till :- 10 minutes

Video is unable to play for last 35 seconds. This is happening with every video . Last 35 seconds are unable to play.

I want to know if this is known issue in demo app or this may be issue related to media content we have made.

Please help to reply on this issue. I got stuck over here. I am not getting any failure logs also regarding this matter.
You can also tell me if I need to check special logs for this issue.

// ExoPlayer version and version code.
    releaseVersion = '2.9.4'
    releaseVersionCode = 2009004

Device :- Nokia 5.1
Android Version - 9

I had raised same concern in this issue 5449 but as per comment by AquilesCanta submitting new issue.

Thanks
Sheetal Garg

**Comment by shgrg1712** [comment]
Hello Santiago ,
                         Please help to reply.
Thanks 
Sheetal Garg

**Comment by AquilesCanta** [comment]
Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE). We will reopen once all required information is available.
