### ISSUE TITLE
Obsolete API Warning

### ISSUE THREAD

**Issue by KellzCodes** [google/ExoPlayer#5477]
### Issue description
The project syncs and runs fine. There is a warning that reads "API 'variant.getJavaCompile()' is obsolete and has been replaced with 'variant.getJavaCompileProvider()'"

The obsolete method call can be found in ExoPlayer\javadoc_library.gradle:24

### Reproduction steps
1. Upgrade gradle tools to 3.3.0
2. Add 'android.debug.obsoleteApi=true' to gradle.properties file which will log error with a more details
3. Sync project again

### Link to test content
https://stackoverflow.com/questions/52470044/warning-api-variant-getjavacompile-is-obsolete-and-has-been-replaced-with

### Version of ExoPlayer being used
branch dev-v2

### Device(s) and version(s) of Android being used
com.android.tools.build:gradle:3.3.0
The project syncs and runs fine. It is a warning, not an error. But here is what I am using to run the project:
Motorola Moto Z Play Droid - Motorola XT1635-01(Android 8.0.0, API 26)

### A full bug report captured from the device
This is the full warning after the debug line is added to the gradle.properties file.

WARNING: API 'variant.getJavaCompile()' is obsolete and has been replaced with 'variant.getJavaCompileProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
REASON: Called from: ExoPlayer\javadoc_library.gradle:24
WARNING: Debugging obsolete API calls can take time during configuration. It's recommended to not keep it on at all times.
Affected Modules: extension-cast

**Comment by tonihei** [comment]
I tried upgrading and got the same warning.

However, even after I fixed the issue in javadoc_library.gradle and javadoc_combined.gradle (*), I still get this warning pointing to an unhelpful gradle stack trace. I guess we still have some time to fix this until the end of 2019, so I'll leave this open until we figure out what else needs to be changed.

(*) I replaced all 3 occurances of `variant.javaCompile` with `variant.javaCompileProvider.get()`.

**Comment by ojw28** [comment]
I think the remaining errors might be due to the com.novoda:bintray-release plugin. Which we should really stop using before the end of 2019 anyway (https://github.com/google/ExoPlayer/issues/5246).

**Comment by tonihei** [comment]
Closing as fixed.

**Comment by SumalathaBareddy** [comment]
it's not working for me
