### ISSUE TITLE
WebM not working

### ISSUE THREAD

**Issue by brianchu** [google/ExoPlayer#548]
Trying to play webm file (actually its is part of the VAST response):

http://redirector.gvt1.com/videoplayback/id/8bd2c53a3e15469d/itag/43/source/gfp_video_ads/ip/0.0.0.0/ipbits/0/expire/1434417203/sparams/ip,ipbits,expire,id,itag,source/signature/221733AF5E082110BFB37E7FAAA7EFCB3F939AB3.AB741EE4448CB71461E9A9D5AC4D7A8E408FD9F7/key/ck2/file/file.webm

I try 1.3.3, dev. branch, same problem.

Problem: No video, just audio. and the log has this error:
06-15 12:48:53.848  28948-29526/com.google.android.exoplayer.demo E/ACodec﹕ [OMX.SEC.vp8.dec] storeMetaDataInBuffers failed w/ err -2147483648

full log:
06-15 12:48:46.461  28948-28948/? I/SELinux﹕ Function: selinux_android_load_priority [0], There is no sepolicy file.
06-15 12:48:46.461  28948-28948/? I/SELinux﹕ Function: selinux_android_load_priority [1], There is no sepolicy version file.
06-15 12:48:46.471  28948-28948/? I/SELinux﹕ Function: selinux_android_load_priority , priority version is VE=SEPF_SAMSUNG-SGH-I747_4.4.2_0016
06-15 12:48:46.471  28948-28948/? I/SELinux﹕ selinux_android_seapp_context_reload: seapp_contexts file is loaded from /seapp_contexts
06-15 12:48:46.491  28948-28948/? D/dalvikvm﹕ Late-enabling CheckJNI
06-15 12:48:46.771  28948-28948/com.google.android.exoplayer.demo D/AbsListView﹕ Get MotionRecognitionManager
06-15 12:48:46.791  28948-28948/com.google.android.exoplayer.demo I/dalvikvm﹕ Could not find method android.media.MediaCodecInfo$CodecCapabilities.getVideoCapabilities, referenced from method com.google.android.exoplayer.MediaCodecUtil.isSizeAndRateSupportedV21
06-15 12:48:46.791  28948-28948/com.google.android.exoplayer.demo W/dalvikvm﹕ VFY: unable to resolve virtual method 86: Landroid/media/MediaCodecInfo$CodecCapabilities;.getVideoCapabilities ()Landroid/media/MediaCodecInfo$VideoCapabilities;
06-15 12:48:46.791  28948-28948/com.google.android.exoplayer.demo D/dalvikvm﹕ VFY: replacing opcode 0x6e at 0x0019
06-15 12:48:46.801  28948-28948/com.google.android.exoplayer.demo I/OMXClient﹕ Using client-side OMX mux.
06-15 12:48:46.801  28948-28948/com.google.android.exoplayer.demo E/OMXMaster﹕ A component of name 'OMX.qcom.audio.decoder.aac' already exists, ignoring this one.
06-15 12:48:46.821  28948-28948/com.google.android.exoplayer.demo W/linker﹕ libsxqk.so has text relocations. This is wasting memory and is a security risk. Please fix.
06-15 12:48:46.821  28948-28948/com.google.android.exoplayer.demo W/linker﹕ libarac.so has text relocations. This is wasting memory and is a security risk. Please fix.
06-15 12:48:46.841  28948-28948/com.google.android.exoplayer.demo E/OMXNodeInstance﹕ OMX_GetExtensionIndex OMX.google.android.index.storeMetaDataInBuffers failed
06-15 12:48:46.841  28948-28948/com.google.android.exoplayer.demo W/OMXNodeInstance﹕ OMX_GetExtensionIndex OMX.google.android.index.prepareForAdaptivePlayback failed
06-15 12:48:46.841  28948-28948/com.google.android.exoplayer.demo I/OMX﹕ instance freeNode
06-15 12:48:46.921  28948-28948/com.google.android.exoplayer.demo W/Adreno-GSL﹕ <get_panel_settings:3802>: Android framework reported version 2. So, don't force ES30
06-15 12:48:46.931  28948-28948/com.google.android.exoplayer.demo I/Adreno-EGL﹕ <qeglDrvAPI_eglInitialize:381>: EGL 1.4 QUALCOMM build: AU_LINUX_ANDROID_KK_2.7_RB1.04.04.00.007.018_msm8960_KK_2.7_RB1_CL3869936_release_AU (CL3869936)
    OpenGL ES Shader Compiler Version: 17.01.10.SPL
    Build Date: 12/09/13 Mon
    Local Branch: mybranch2092625
    Remote Branch: quic/kk_2.7_rb1.15
    Local Patches: NONE
    Reconstruct Branch: AU_LINUX_ANDROID_KK_2.7_RB1.04.04.00.007.018 +  NOTHING
06-15 12:48:46.941  28948-28948/com.google.android.exoplayer.demo D/OpenGLRenderer﹕ Enabling debug mode 0
06-15 12:48:52.647  28948-28948/com.google.android.exoplayer.demo I/dalvikvm﹕ Could not find method android.view.accessibility.CaptioningManager$CaptionStyle.hasForegroundColor, referenced from method com.google.android.exoplayer.text.CaptionStyleCompat.createFromCaptionStyleV21
06-15 12:48:52.647  28948-28948/com.google.android.exoplayer.demo W/dalvikvm﹕ VFY: unable to resolve virtual method 259: Landroid/view/accessibility/CaptioningManager$CaptionStyle;.hasForegroundColor ()Z
06-15 12:48:52.647  28948-28948/com.google.android.exoplayer.demo D/dalvikvm﹕ VFY: replacing opcode 0x6e at 0x0002
06-15 12:48:52.657  28948-28948/com.google.android.exoplayer.demo D/dalvikvm﹕ DexOpt: couldn't find field Landroid/view/accessibility/CaptioningManager$CaptionStyle;.windowColor
06-15 12:48:52.657  28948-28948/com.google.android.exoplayer.demo I/dalvikvm﹕ DexOpt: unable to optimize instance field ref 0x002a at 0x18 in Lcom/google/android/exoplayer/text/CaptionStyleCompat;.createFromCaptionStyleV21
06-15 12:48:52.697  28948-28948/com.google.android.exoplayer.demo D/ProgressBar﹕ setProgressDrawable drawableHeight = 32
06-15 12:48:52.707  28948-28948/com.google.android.exoplayer.demo D/AbsSeekBar﹕ AbsSeekBar Constructor: misSeebarAnimationAvailable = false
06-15 12:48:52.717  28948-28948/com.google.android.exoplayer.demo I/ExoPlayerImpl﹕ Init 1.3.3
06-15 12:48:52.717  28948-28948/com.google.android.exoplayer.demo D/EventLogger﹕ start [0]
06-15 12:48:52.717  28948-28948/com.google.android.exoplayer.demo D/EventLogger﹕ state [0.00, false, P]
06-15 12:48:52.727  28948-28948/com.google.android.exoplayer.demo I/dalvikvm﹕ Could not find method android.media.MediaCodec.releaseOutputBuffer, referenced from method com.google.android.exoplayer.MediaCodecVideoTrackRenderer.renderOutputBufferTimedV21
06-15 12:48:52.727  28948-28948/com.google.android.exoplayer.demo W/dalvikvm﹕ VFY: unable to resolve virtual method 81: Landroid/media/MediaCodec;.releaseOutputBuffer (IJ)V
06-15 12:48:52.727  28948-28948/com.google.android.exoplayer.demo D/dalvikvm﹕ VFY: replacing opcode 0x6e at 0x0008
06-15 12:48:52.737  28948-28948/com.google.android.exoplayer.demo I/dalvikvm﹕ Could not find method android.media.AudioTrack.write, referenced from method com.google.android.exoplayer.audio.AudioTrack.writeNonBlockingV21
06-15 12:48:52.737  28948-28948/com.google.android.exoplayer.demo W/dalvikvm﹕ VFY: unable to resolve virtual method 64: Landroid/media/AudioTrack;.write (Ljava/nio/ByteBuffer;II)I
06-15 12:48:52.737  28948-28948/com.google.android.exoplayer.demo D/dalvikvm﹕ VFY: replacing opcode 0x6e at 0x0001
06-15 12:48:52.737  28948-28948/com.google.android.exoplayer.demo D/EventLogger﹕ state [0.02, true, I]
06-15 12:48:52.747  28948-28948/com.google.android.exoplayer.demo D/EventLogger﹕ state [0.03, true, P]
06-15 12:48:53.828  28948-28948/com.google.android.exoplayer.demo D/EventLogger﹕ state [1.10, true, B]
06-15 12:48:53.828  28948-29485/com.google.android.exoplayer.demo I/OMXClient﹕ Using client-side OMX mux.
06-15 12:48:53.848  28948-29526/com.google.android.exoplayer.demo I/OMXClient﹕ Using client-side OMX mux.
06-15 12:48:53.848  28948-29526/com.google.android.exoplayer.demo E/ACodec﹕ [OMX.SEC.vp8.dec] storeMetaDataInBuffers failed w/ err -2147483648
06-15 12:48:53.858  28948-28948/com.google.android.exoplayer.demo D/EventLogger﹕ decoderInitialized [1.14, OMX.SEC.vp8.dec]
06-15 12:48:53.858  28948-29485/com.google.android.exoplayer.demo I/OMXClient﹕ Using client-side OMX mux.
06-15 12:48:53.868  28948-29485/com.google.android.exoplayer.demo E/OMXMaster﹕ A component of name 'OMX.qcom.audio.decoder.aac' already exists, ignoring this one.
06-15 12:48:53.918  28948-29485/com.google.android.exoplayer.demo W/linker﹕ libsxqk.so has text relocations. This is wasting memory and is a security risk. Please fix.
06-15 12:48:53.918  28948-29485/com.google.android.exoplayer.demo W/linker﹕ libarac.so has text relocations. This is wasting memory and is a security risk. Please fix.
06-15 12:48:53.928  28948-29485/com.google.android.exoplayer.demo I/OMX﹕ instance freeNode
06-15 12:48:53.959  28948-29537/com.google.android.exoplayer.demo I/OMXClient﹕ Using client-side OMX mux.
06-15 12:48:53.959  28948-29537/com.google.android.exoplayer.demo E/OMXMaster﹕ A component of name 'OMX.qcom.audio.decoder.aac' already exists, ignoring this one.
06-15 12:48:53.989  28948-29537/com.google.android.exoplayer.demo W/linker﹕ libsxqk.so has text relocations. This is wasting memory and is a security risk. Please fix.
06-15 12:48:53.989  28948-29537/com.google.android.exoplayer.demo W/linker﹕ libarac.so has text relocations. This is wasting memory and is a security risk. Please fix.
06-15 12:48:54.029  28948-28948/com.google.android.exoplayer.demo D/EventLogger﹕ decoderInitialized [1.30, OMX.google.vorbis.decoder]
06-15 12:48:54.069  28948-29537/com.google.android.exoplayer.demo I/OMXNodeInstance﹕ OMX_FreeBuffer for buffer header 0x61215b00 successful
06-15 12:48:54.069  28948-29537/com.google.android.exoplayer.demo I/OMXNodeInstance﹕ OMX_FreeBuffer for buffer header 0x61215ce0 successful
06-15 12:48:54.069  28948-29537/com.google.android.exoplayer.demo I/OMXNodeInstance﹕ OMX_FreeBuffer for buffer header 0x61215df8 successful
06-15 12:48:54.069  28948-29537/com.google.android.exoplayer.demo I/OMXNodeInstance﹕ OMX_FreeBuffer for buffer header 0x61215ef8 successful
06-15 12:48:54.099  28948-28948/com.google.android.exoplayer.demo D/EventLogger﹕ videoSizeChanged [640, 360, 1.0]
06-15 12:48:54.159  28948-28948/com.google.android.exoplayer.demo D/EventLogger﹕ state [1.44, true, R]
06-15 12:49:46.294  28948-28948/com.google.android.exoplayer.demo D/EventLogger﹕ state [53.57, true, E]
06-15 12:49:46.374  28948-28948/com.google.android.exoplayer.demo D/ProgressBar﹕ updateDrawableBounds: left = 0
06-15 12:49:46.374  28948-28948/com.google.android.exoplayer.demo D/ProgressBar﹕ updateDrawableBounds: top = 0
06-15 12:49:46.384  28948-28948/com.google.android.exoplayer.demo D/ProgressBar﹕ updateDrawableBounds: right = 480
06-15 12:49:46.384  28948-28948/com.google.android.exoplayer.demo D/ProgressBar﹕ updateDrawableBounds: bottom = 64
06-15 12:49:46.384  28948-28948/com.google.android.exoplayer.demo D/ProgressBar﹕ updateDrawableBounds: mProgressDrawable.setBounds()
06-15 12:50:10.010  28948-28948/com.google.android.exoplayer.demo D/dalvikvm﹕ GC_FOR_ALLOC freed 2975K, 29% free 12897K/17992K, paused 84ms, total 84ms
06-15 12:50:35.397  28948-28948/com.google.android.exoplayer.demo D/dalvikvm﹕ GC_FOR_ALLOC freed 1777K, 29% free 12858K/17992K, paused 72ms, total 77ms
06-15 12:51:00.874  28948-28948/com.google.android.exoplayer.demo D/dalvikvm﹕ GC_FOR_ALLOC freed 1727K, 29% free 12856K/17992K, paused 73ms, total 76ms
06-15 12:51:26.121  28948-28948/com.google.android.exoplayer.demo D/dalvikvm﹕ GC_FOR_ALLOC freed 1724K, 29% free 12856K/17992K, paused 71ms, total 72ms

**Comment by brianchu** [comment]
Device: Samsung S3 (4.4.2) SGH-I747

**Comment by andrewlewis** [comment]
This looks like a device-specific issue. I don't have the particular variant of the Samsung Galaxy S3 you mentioned here, but I was able to test another version. Unfortunately, it hasn't received an update to 4.4.2, and I wasn't able to reproduce the issue on its current build -- playback worked fine.

Do you know if this is reproducible on any other device/build combinations? If so, please could you reply with their build fingerprints, output by 'adb shell getprop ro.build.fingerprint'? Thanks!

**Comment by brianchu** [comment]
Samsung Galaxy S4 mini Android 4.4.2
The link is dead, but it should not matter, seems any webM will reproduce the problem.
I will also find a webm file and ... upload somewhere (you know a place for free hosting media file?)

**Comment by 4a-j** [comment]
Confirmed audio and no video for webm played on Verizon/d2vzw/d2vzw:4.4.2/KOT49H/I535VRUDNE1:user/release-keys

**Comment by brian-chu-twc** [comment]
Trying Samsung S3 with version 1.5.0, still have the same problem. so my phone probably not exclude in #548 changes. here are some info.:
[ril.deviceOffRes]: [0]
[ro.board.platform]: [msm8960]
[ro.boot.hardware]: [qcom]
[ro.boot.serialno]: [7f16281f]
[ro.build.version.sdk]: [19]
[ro.hardware]: [qcom]
[ro.product.brand]: [samsung]
[ro.product.device]: [d2att]
[ro.product.manufacturer]: [samsung]
[ro.product.model]: [SAMSUNG-SGH-I747]
[ro.product.name]: [d2uc]
[ro.revision]: [16]
[ro.serialno]: [7f16281f]

**Comment by giladna** [comment]
Happens on Galaxy S4 and Galaxy Tab3 too

**Comment by billyjoker** [comment]
This issue with webm videos (audio is playing but video is a black screen) is also happening with:

Device: Samsung Galaxy Tab 4 (SM-T230)
Android **4.4.2**
Exoplayer r1.5.13

@ojw28  thanks for still working on this issue!!

**Comment by ojw28** [comment]
Seeing the same symptoms isn't sufficient evidence to confirm that the underlying issue is the same. If you want us to investigate any further devices:
- Please provide a full bugreport (i.e. the full output of "adb bugreport") captured immediately after reproducing the problem.
- Please try making the workaround apply to the affected device yourself, and confirm that it does indeed fix the issue. As you can see from the commits referenced above, this is pretty trivial. It's just a matter of adding an extra `|| Util.DEVICE.startsWith("XXX")` into the workaround condition, where XXX is the value of `Util.DEVICE` on the affected device.
- If the workaround is successful, please just send us a pull request and we'll happily merge it. Pull requests should be made to the `dev-v2` branch.
