### ISSUE TITLE
[Question] Stop playing ads when user seeks back.

### ISSUE THREAD

**Issue by sravan1213** [google/ExoPlayer#5481]
We have implemented our own custom AdsLoader. Everything is working fine. I have a use case which i am not able to figure out whether it is achievable using AdPlaybackState.

Lets says I have 5 midroll ads Ad1, Ad2, Ad3, Ad4 and Ad5.
when user seeks to a position between Ad4 and Ad5, Ad4 starts plays immediately as expected.

now when user seeks back before Ad4, from current postion i.e to a position between Ad3 and Ad4, Ad3 starts playing immediately. In this case I don't want the ad to start immediately.. (I dont want ads to be played when user seeks back. Ads should be played only during forward seek)

can we achieve this using AdPlaybackState.?

**Comment by andrewlewis** [comment]
I think it should be possible: if your `AdsLoader` keeps a player listener you can be notified of the seek in `onPositionDiscontinuity` with reason `DISCONTINUITY_REASON_SEEK`, and mark any ads preceding the last ad before the seek position that are not already in the played/error states as skipped. After updating the `AdPlaybackState` those ads shouldn't be played any more. Please try this and let us know how you get on.

**Comment by sravan1213** [comment]
Thanks for the quick response. I've tried this but there is one problem I'm facing.
How can I mark them as unplayed ads if user seeks back again to a position before this ad.

**Comment by sravan1213** [comment]
@andrewlewis I got this worked out. I am marking previous ads skipped as you suggested. When user seeks back I am changing the state of skipped ads to unPlayAds which are ahead of the current position.

**Comment by andrewlewis** [comment]
@sravan1213 Glad you got it worked out, but are you sure the approach of marking ads that were previously marked as skipped as unplayed works? I think there's a check that the ad whose state is changing is in the unavailable/available state. We are planning to add more flexibility for this soon.

**Comment by sravan1213** [comment]
@andrewlewis yes it is working as expected. I am not building the new state using `with` helper functions. I am saving initial state of adPlaybackState when I first build it. When user seek back again i am doing following hack for ads which are skipped earlier :).
`adPlaybackState.adGroups[adGroup] = initialAdPlaybackState.adGroups[adGroup]`

Good to hear that you are mode flexibility to `AdPlaybackState`
