### ISSUE TITLE
[Question] CastPlayer state changes

### ISSUE THREAD

**Issue by CodeRedDev** [google/ExoPlayer#5484]
### Issue description
I'm using the CastPlayer to stream audio to a ChromeCast device by `castPlayer.loadItem(...)`. This seems to work for just starting the player cause it almost instantly starts playing the audio on the CC device. Unfortunately I do not get any player status changes cause the player stays on `STATUS_IDLE`. 

From the docs I read 

> If no session is available, the player state will remain unchanged [...]

 but that seems to make no sense to me cause a session should be available if I'm able to play the audio, right?

I need the the state change callback to then handle UI changes and other app behaviour.

### Reproduction steps
Instead of using the MediaRouteButton I am using a self made routing "dialog" (discover available devices and add them to a list in the apps drop down menu). On the users route selection I connect to the device via 
```
MediaRouter router = MediaRouter.getInstance(getContext());
router.selectRoute(chromecastDiscoveryResult.getRouteInfo());
```
ChromecastDiscoveryResult is a class that holds some info about the discovered devices e.g. the MediaRouter.RouteInfo that's needed for selecting the devices.

### Version of ExoPlayer being used
2.9.3

### Device(s) and version(s) of Android being used
Samsung Galaxy A5 - Android 8.0
HTC U11+ - Android 8.0

**Comment by tonihei** [comment]
There will be a new completely rewritten Cast extension soon (see #5486) and we won't investigate issues with the old one anymore. All things similar to what you describe will probably be fixed in the new version.
