### ISSUE TITLE
Release ExoCastPlayer and ExoCast receiver app

### ISSUE THREAD

**Issue by AquilesCanta** [google/ExoPlayer#5486]
TODO list:

- Include a link to medium post here.
- Point existing default receiver issues to this issue.
- Close existing Cast receiver issues that may be fixed by the new receiver.

**Comment by jhowens89** [comment]
Would it be possible to give a ballpark timeline on this issue? Not looking for anything concrete -- I've been watching this issue closely and pushing off my app's chromecast implementation after reading through the back and forth around the issues surrounding the old version. If it's still a bit off, that's fine, but I would be super grateful for that knowledge. Thanks!

**Comment by AquilesCanta** [comment]
Hi @jhowens89, sorry for all confusion and delays around this. Just before releasing this, we had a setback, and this release is suspended for now. I will resume work on the original CastPlayer, and I'll try to fix existing issues with the assistance of the Cast team. If we don't manage to get CastPlayer to properly implement Player in an acceptable timeline, we will revisit the possibility of releasing our custom receiver app. I'm sorry to cause this this inconvenience. We are working on providing the best Cast integration we can.

**Comment by ojw28** [comment]
Closing because we've decided to try and improve the existing Cast extension instead.
