### ISSUE TITLE
PlaylistStuckException period duration customization

### ISSUE THREAD

**Issue by tipoc123** [google/ExoPlayer#5487]
When do you plan to implement your "TODO: Allow customization of stuck playlists handling."?

https://github.com/google/ExoPlayer/blob/6b0e1758b22994a2725a2aa1ec9125e83aa58419/library/hls/src/main/java/com/google/android/exoplayer2/source/hls/playlist/DefaultHlsPlaylistTracker.java#L618

**Comment by tipoc123** [comment]
When there are no new chunks in EVENT playlist we need to wait for more time instead of throwing PlaylistStuckException. In our case may be different time between STB and server (where chunks are located). Now when a user seeks to the end of playlist PlaylistStuckException is thrown.

**Comment by tonihei** [comment]
@AquilesCanta  Any plans to do that in the near future?

**Comment by tipoc123** [comment]
Any news?

**Comment by AquilesCanta** [comment]
No plans so far, sorry. Can you describe specifically what you'd like to achieve? Is it basically increasing the period of waiting time before throwing PlaylistStuckException?

**Comment by tipoc123** [comment]
> Is it basically increasing the period of waiting time before throwing PlaylistStuckException?

Yes. You understood correctly.

**Comment by tipoc123** [comment]
Do you have any updates?

**Comment by ojw28** [comment]
We will post an update here when there is an update. The lack of one means there is no update. Thanks.

**Comment by tipoc123** [comment]
Thanks!
