### ISSUE TITLE
Migrate to JetPack / AndroidX

### ISSUE THREAD

**Issue by ojw28** [google/ExoPlayer#5489]
As per title, we should migrate to JetPack.

**Comment by ojw28** [comment]
This should be fixed in the `dev-v2` branch, although is relatively untested. It's a bit complicated because internally we're still using the old support library, with the migration happening on-the-fly as part of the process by which we sync our internal and external trees. Let us know if there are any issues!

**Comment by vlad-roid** [comment]
This seems to be live since 2.10.0 but wasn't documented in the release notes. Why is that?
