### ISSUE TITLE
will it support video list ,like youku.com?

### ISSUE THREAD

**Issue by nameryan** [google/ExoPlayer#549]
I haven't found the interface like (below code is from another player project):

/**
   * Set the segments source url
   * @param segments the array path of the url e.g. Segmented video list
   * @param cacheDir e.g. getCacheDir().toString()
   */</br>
  public void setDataSegments(String[] uris, String cacheDir) {
  	_setDataSegmentsSource(uris, cacheDir);
  }

so current is maybe not supported , but will this be in schedual?

**Comment by ojw28** [comment]
I don't understand what you're asking here.

**Comment by nameryan** [comment]
sorry for my poor english first :cry: 

the normal use of setDataSource maybe :
public final void setDataSource(String url, Map<String, String> headers)
the url in the params is one single url.
in some situation, a video source can been seperate to several urls , one url after another url , all the urls make the full video.
so there should be another setDataSource like :
public final void setDataSource(String urllist[], Map<String, String> headers)
the player will play the url list in order.
will exoplayer support url list ?

**Comment by ojw28** [comment]
We don't have any plans to support playing a single video from multiple URLs. That's just an inefficient way to distribute media. For example you'd need to request the head of each of them separately before you could determine the duration of the video. Why would you not locate the whole video at a single URL?

We do eventually want to support seamless transition from one video to the next, which is different in the sense that the progress bar would show the progress of the current part only, not of the whole video.
