### ISSUE TITLE
ProgressiveDownloadAction show as deprecated in ExoPlayer 2.9.3

### ISSUE THREAD

**Issue by babkouew** [google/ExoPlayer#5495]
I have implemented DownloadManager features as described in the medium posts, everything works fine but my ProgressiveDownloadAction shows as deprecated. Is there a new way to go around about stuff?

**Comment by ojw28** [comment]
Whenever we deprecate something, the Javadoc tells you what to use instead. See [here](http://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/offline/ProgressiveDownloadAction.html#ProgressiveDownloadAction-android.net.Uri-boolean-byte:A-java.lang.String-).
