### ISSUE TITLE
Not work gapless playing between two HLS Audio Streaming

### ISSUE THREAD

**Issue by jeho1335** [google/ExoPlayer#5500]
Hi. I am developing an audio streaming application using ExoPlayer v2.

To implement gapless playback during playback of consecutive tracks within an album, the MediaSource of the next song is inserted into ConcatenatingMediaSource before the currently playing track ends.

It is confirmed on the Profiler that the next song is loaded via network communication before the actual playing track ends. After the onTrackChanged () method is called, the playback will be skipped over with the next preloaded song, but this will cause a gap of 0.2 to 0.3 seconds

How can i remove a 0.2 to 0.3 seconds gap??

Thanks and sorry for my english.

exoplayer version : 2.9.4

### Issue description
1. Make a MediaSource from HlsMediaSource.Factory with drm
2. Before the first track ends, create a second MediaSource and add ConcatenatingMediaSource
3. When first track is ended, i can receive a callback onTrackChanged
4. Gap occurs for 0.2 ~ 0.3 seconds until the second track is reproduced normally

### Version of ExoPlayer being used
2.9.4

### Device(s) and version(s) of Android being used
Samsung galuxy s8 and android 8.1

**Comment by marcbaechinger** [comment]
Do you also see the same behaviour, if you initially setup the ConcatentatingMediaSource with more than one MediaSource, or does this only happen when you kind of dynamically add the MediaSources before the track ends (which is the approach you are describing)?

I also wonder if this somehow involves gapless media? Does the stream you are adding have gapless metadata which the player needs to honour?

Best would be if you can send us some sample streams for reproducing. If you don't wish to post it
publicly, please email the link to dev.exoplayer@gmail.com using a subject in the format "Issue #5500".

**Comment by jeho1335** [comment]
1. Yes. The media source is being dynamically added to the ConcatenatingMediaSource before the currently playing track ends.

2. This is part of the specific track metadata that you try to play with gapless playback.
(Important information is obscured.)

#EXTM3U
#EXT-X-VERSION:3
#EXT-X-KEY:METHOD=AES-128,URI="****",IV=***
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-ALLOW-CACHE:NO
#EXT-X-TARGETDURATION:11
#EXTINF:10.007811,
***>000.ts
#EXTINF:10.007811,
***.001.ts
......
......
......
#EXTINF:5.479911,
***.017.ts
#EXT-X-ENDLIST

**Comment by marcbaechinger** [comment]
Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).
