### ISSUE TITLE
play the audio error when reached 22 secs position

### ISSUE THREAD

**Issue by caprice** [google/ExoPlayer#5502]
from the error stack:

```
.videoplayer.player.PlayErrorException:play https://qiniu.yunjilink.com/7sVsQSyLqgl8tJY8qgJBa_DKh44=/lpKV7HFasjjp4ZMUhWkiT1LO7f9X error,
......
--
Caused by:
java.lang.IllegalStateException:
android.media.MediaCodec.releaseOutputBuffer(Native Method)
android.media.MediaCodec.releaseOutputBuffer(MediaCodec.java:2752)
com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(MediaCodecAudioRenderer.java:641)
com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1355)
```
The audio https://qiniu.yunjilink.com/7sVsQSyLqgl8tJY8qgJBa_DKh44=/lpKV7HFasjjp4ZMUhWkiT1LO7f9X can be played at any position but not at 22 secs. 

Btw, **the issue can only reproduced in one device** in my hand,
![image](https://user-images.githubusercontent.com/2981114/52692776-d3216f00-2f9f-11e9-9b98-17b80cbf5bc1.png)

**Comment by marcbaechinger** [comment]
The streams plays fine for me. It loads about 2 minutes of audio data into the buffers and passes 22 seconds without stopping playback or any log statements.

As you said this seems to be a device specific issue.

I'm pretty sure if we could look into a bug report, we could confirm this. Please provide complete information as requested in the issue template, if you want me to do that. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

**Comment by caprice** [comment]
Thanks for looking into this question. Here is the more detailed [error log](https://github.com/google/ExoPlayer/files/2865342/error.log) per your request.

**Comment by marcbaechinger** [comment]
Can you take a bug report right after the error occurred? 

You can do in the console with a

```
adb bugreport
```

Here is some detailed information on how you can capture a bug report: https://developer.android.com/studio/debug/bug-report
