### ISSUE TITLE
MPEG-4 file is played with sound but without picture

### ISSUE THREAD

**Issue by dirondir** [google/ExoPlayer#5503]
### Issue description
file is played with sound but without picture (I see black screen). 

### Reproduction steps
That's my code to initialize the player and set the media path

```
private var playerView: PlayerView? = null
private var player: SimpleExoPlayer? = null

...

private fun initializePlayer() {

        if (player == null) {
            // a factory to create an AdaptiveVideoTrackSelection
            val adaptiveTrackSelectionFactory = AdaptiveTrackSelection.Factory()
            // using a DefaultTrackSelector with an adaptive video selection factory
            mTrackSelector = DefaultTrackSelector(adaptiveTrackSelectionFactory)
            val builder = DefaultTrackSelector.ParametersBuilder().setTunnelingAudioSessionId(C.generateAudioSessionIdV21(this))
            mTrackSelector?.parameters = builder.build() 

            val extensionRendererMode = DefaultRenderersFactory.EXTENSION_RENDERER_MODE_ON

            val renderersFactory = DefaultRenderersFactory(this, extensionRendererMode)

            player = ExoPlayerFactory.newSimpleInstance(this, renderersFactory,
                    mTrackSelector,
                    DefaultLoadControl.Builder().createDefaultLoadControl())

            player?.addListener(componentListener)
            playerView?.player = player
            playerView?.controllerHideOnTouch = true
            player?.playWhenReady = playWhenReady   

        }

    }
```
then

```
mediaDataSourceFactory = DefaultDataSourceFactory(this, null,
                DefaultHttpDataSourceFactory(userAgent, null, 3000, 3000, true))

private fun buildMediaSource(uri: Uri): MediaSource {
        return ExtractorMediaSource.Factory(mediaDataSourceFactory)
                    .createMediaSource(uri)

    }
```
and then

```
val media = buildMediaSource(...)
player?.prepare(media, true, true)
```

### Link to test content
It has been sent to dev.exoplayer@gmail.com

### Version of ExoPlayer being used
2.9.4

### Device(s) and version(s) of Android being used
nvidia shield 2017, Android TV 8.0.

### A full bug report captured from the device
It has been sent to dev.exoplayer@gmail.com

**Comment by marcbaechinger** [comment]
Thanks for reporting. I'll try to reproduce this on a device.

Can you confirm this happens only when you enable tunneling? Does it happen on other devices than Nvidia shield 2017 as well?

**Comment by dirondir** [comment]
I tried with NVidia Shield 2017 (Android 8.0, API 26), Google Pixel 2 (Android 9.0 with all current updates, API 28) and Android Emulator (I use it with API 27)
Result is the same for all devices regardless of tunneling (if you meant using the setTunnelingAudioSessionId function)

**Comment by marcbaechinger** [comment]
I looked into the matroska file you sent us. It seems to me that the codec inside the container is XVID according to the FOUR_CC. That's a codec which is not necessarily supported by Android.  I checked 

ExoPlayer supports all [formats which are supported by the Android Media Framwork](https://developer.android.com/guide/topics/media/media-formats). It might be that some devices have such a codec. I would say that the devices you are mentioning do not have the codec included.

If you want me to confirm this you can send me the media_codecs_xml file of your device, so I can check for this.

**Comment by dirondir** [comment]
How can I get the media_codecs_xml file for a device?

**Comment by marcbaechinger** [comment]
You need to know where it is located on your device. :)

This is normally /etc/media_codecs.xml or similar. For my Pixel phone on which I test it's under /vendor/etc/media_codecs.xml. 

If you need to check where it is, you can do the following command to get a shell on the device:

```
adb shell
```

and then check where the file is like: /etc/media_codecs.xml

Once you found the location, you can download the file from the device to your computer by the following command:

```
adb pull /etc/media_codecs.xml
```

**Comment by dirondir** [comment]
Thank you for help :)
Maybe is there an extension for Exo Player to add XVID codec?

**Comment by marcbaechinger** [comment]
There are no plan fur such an extension now and in the near future. Maybe the existing ffmpeg extensions can help you doing this in software. But I frankly don't know whether ffmpeg support this.

**Comment by ojw28** [comment]
Aside: The existing FFmpeg extension is audio only, so it wont help with this.

**Comment by dirondir** [comment]
Hi again!
You know but now I think it's a bug of ExoPlayer. 
The problem is with the function 
`private static Pair<String, List<byte[]>> parseFourCcPrivate(ParsableByteArray buffer)` in MatroskaExtractor.java

The description says: "VC1 and H263 are the only supported compression types."
For all other types the function returns `new Pair<>(MimeTypes.VIDEO_UNKNOWN, null)`

if you set correct mime-type there (for my case MimeTypes.VIDEO_MP4V) everything works well

**Comment by andrewlewis** [comment]
@dirondir Are you sure it's valid to pass a DivX stream to a video/mp4v-es decoder in general (and, if so, please could you link to a spec or more information about this)?

I am wondering whether the MIME type in your content might actually be set incorrectly, or perhaps this particular device's decoder supports a wider set of codecs than are signaled via its supported MIME types.

The comment about H.263 is inaccurate on the dev branch so I will make a fix for that.

**Comment by dirondir** [comment]
@andrewlewis Unfortunatelly I have no such information. I've got the result by experimenting. 
I'm not very experienced in working with video, but the solution works for both Google Pixel 2 (Android 9) and Nvidia Shield (Android 8.0) where I tried to play this video. 
The Shield has the XVid and DivX codecs on board (https://www.nvidia.com/en-us/shield/specs/)
But I can't say the same about Pixel 2 (https://developer.android.com/guide/topics/media/media-formats)

**Comment by andrewlewis** [comment]
It seems quite possible that your input media is actually in MPEG-4 format not DivX, but I'm not familiar enough with these formats to verify this.

Note: Nvidia Shield's codecs don't appear to advertise support for video/divx (in /system/vendor/odm/etc/media_codecs.xml), so I don't think we have a way of knowing that this format is supported. Some devices do advertise support for video/divx explicitly and separately from MPEG-4 video. If we find out that all video/mp4v-es decoders also support video/divx then we can just get rid of the extra MIME type for DivX, but I don't think we have evidence for that yet.

If you learn more please update here or file a new issue, but for now I don't think this is actionable.
