### ISSUE TITLE
How to customize playerNotificationManager

### ISSUE THREAD

**Issue by pawaom** [google/ExoPlayer#5505]
### Issue description
How can we customize notification shown by Exoplayer

### Reproduction steps
 I have referred this code 

https://www.youtube.com/watch?v=svdq1BWl4r8

https://github.com/google/Exoplayer/tree/io18

### Link to test content
 this is the code I have used

```
playerNotificationManager = PlayerNotificationManager.createWithNotificationChannel(PlayerService.this,
                PLAYBACK_CHANNEL_ID, R.string.app_name, PLAYBACK_NOTIFICATION_ID,
                new PlayerNotificationManager.MediaDescriptionAdapter() {
                    @Override
                    public String getCurrentContentTitle(Player player) {
                        return TITLE.get(player.getCurrentWindowIndex());
                    }
                    @Nullable
                    @Override
                    public PendingIntent createCurrentContentIntent(Player player) {
                        Intent intent = new Intent(PlayerService.this, MainActivity.class);
                        return PendingIntent.getActivity(PlayerService.this, 0,
                                intent, PendingIntent.FLAG_UPDATE_CURRENT);
                    }
                    @Nullable
                    @Override
                    public String getCurrentContentText(Player player) {
                             return DISPLAY.get(player.getCurrentWindowIndex());
                    }
                    @Nullable
                    @Override
                    public Bitmap getCurrentLargeIcon(Player player, PlayerNotificationManager.BitmapCallback
                            callback) {

                        return getAlbumImage(ALBUM_ART.get(player.getCurrentWindowIndex()));
                    }
                });
        playerNotificationManager.setNotificationListener(new PlayerNotificationManager.NotificationListener() {
            @Override
            public void onNotificationStarted(int notificationId, Notification notification) {
                startForeground(notificationId, notification);
            }

            @Override
            public void onNotificationCancelled(int notificationId) {
                stopSelf();
            }
        });
```

I know to customize notification we use this

```
[NotificationCompat.Builder notificationBuilder = new NotificationCompat.Builder(context)
                .setSmallIcon(R.mipmap.ic_launcher)
                .setLargeIcon(BitmapFactory.decodeResource(context.getResources(),
                        R.mipmap.ic_launcher))
                .setContentTitle(title)
                .setContentText(message)
                .setAutoCancel(true)
                .setSound(defaultSoundUri)
                .setContentIntent(pendingIntent);

        android.app.NotificationManager notificationManager =
                (android.app.NotificationManager) context.getSystemService(Context.NOTIFICATION_SERVICE);

        notificationManager.notify(0 /* ID of notification */, notificationBuilder.build());](url)
```

### Version of ExoPlayer being used
   implementation 'com.google.android.exoplayer:exoplayer-core:2.9.3'
    implementation 'com.google.android.exoplayer:exoplayer-ui:2.9.3'
    implementation 'com.android.support:support-media-compat:28.0.0'
    implementation 'com.google.android.exoplayer:extension-mediasession:2.9.3'

### Device(s) and version(s) of Android being used
 lenovo A7000 Android 5.0
moto c plus  Android™ 7.0

### A full bug report captured from the device
 What happens

first when we see notification 
![20190213_152536_rmedited](https://user-images.githubusercontent.com/28686824/52707770-7c6f6180-2fae-11e9-8b58-e71507bd299c.jpg)

when we drag the notification 

![20190213_152604_rmedited](https://user-images.githubusercontent.com/28686824/52707796-8b561400-2fae-11e9-9dec-d3b74deaa3a4.jpg)

What I want 

 
![20190213_164621_rmedited](https://user-images.githubusercontent.com/28686824/52708106-5c8c6d80-2faf-11e9-9819-f585dc891f32.jpg)

**Comment by marcbaechinger** [comment]
The PlayerNotificationManager creates a MediaStyle notification which is rendered by the platform. Besides the properties which you can set on the PlayerNotificationManager and are delegated to the builder there is no other customization I'm aware of. It seems to me that we expose pretty much all properties which can be set to the builder which makes the MediaStyle notification.

A media style notification is rendered by the platform and may look different on different API levels.

Can you tell me how you created the notification "What I want"? Which properties of the builder did you set? Also it would be interesting to know which API levels the screenshots are from.

**Comment by marcbaechinger** [comment]
One thing came to my mind which may change the appearance of the notification is whether you set the media session token or not with [setMediaSessionToken(MediaSessionCompat.Token token)](https://github.com/google/ExoPlayer/blob/1c4ea26ff0ff530a1282398377a2cddfceefc3f6/library/ui/src/main/java/com/google/android/exoplayer2/ui/PlayerNotificationManager.java#L579):

`playerNotificationManager.setMediaSessionToken(mediaSessionCompat.getSessionToken());`

Your gradle imports show you are importing the media session extension but the code snippet does not set the token. So if you are using a MediaSession you should set the token.

**Comment by pawaom** [comment]
yes it required `setMediaSessionToken ` working fine now that I Have added it thanks for the help
