### ISSUE TITLE
Feature Request Can we translate Subtitles

### ISSUE THREAD

**Issue by pawaom** [google/ExoPlayer#5506]
Feature Request Can we translate Subtitles

Can we translate subtitles which are being shown may be using google translate etc

also another request is for  Localization we need to create multiple strings.xml files which leads to increasing apk size, can it be auto translated

**Comment by marcbaechinger** [comment]
#4657

**Comment by marcbaechinger** [comment]
Thanks for your request. I think this is not something we are going to support from ExoPlayer library side anytime soon.

Please see issue #4657 about the same topic.
