### ISSUE TITLE
How to dynamically add subtitles after player has been prepared

### ISSUE THREAD

**Issue by xiaoxixi615** [google/ExoPlayer#5509]
When playing a local video using exoplayer,  i want to play the subtitles along with the video.  
The subtitle files are placed somewhere in sdcard, and I can select them from a file browser.

My question is: 
       1、When I am playing a video(maybe played some minutes), can I select and apply a subtitle dynamicly without re-preparing the source video again? because re-preparing seems to lead a black screen for a short second, this is a bad user experience.
      2、When playing the video with a default subtitle(jp), can I dynamicly select and replace the default subtitle with another one(en)? and the replacement should be seamless.

Thanks a lot

**Comment by marcbaechinger** [comment]
You can sideload subtitles as described in the [developer guide](https://google.github.io/ExoPlayer/guide.html#side-loading-a-subtitle-file). Once you've done this you should be able to select text tracks and switch between the languages you sideloaded. 

Can you have a look and let me know whether this is what you are looking for?

**Comment by marcbaechinger** [comment]
In case you want to add subtitles after you have prepared the player, then this is not yet supported. Please refer to the tracking issue #1649 in this case.

**Comment by xiaoxixi615** [comment]
Thank you very much for your quick reply.  It do seems like issue #1649. 
My case is that when I am playing a video,  I am able to download an online subtitle from server and apply it directly during the video playing. As the media has been started to play, I don't want to prepare it again(re-buffering may interfere the normal playing process)

Have you a plan to enhance this issue in the near future?  Or Can you give some advice on how to deal with this issue?

**Comment by marcbaechinger** [comment]
Issue #1649 is marked as enhancement and will be updated accordingly. I close this issue as a duplicate. Please reopen if you think I can add something here. Many thanks!
