### ISSUE TITLE
DASH content test stream which has "indexRange" but has no "Initialization range", the player played it fail.

### ISSUE THREAD

**Issue by KaiYeYang** [google/ExoPlayer#5510]
**Issue description**
Attach DASH content test stream which has "indexRange" but has no "Initialization range", the player played it fail.

**Reproduction steps**
1. Download the attach test content, and make it as a http link, exp: http://ip:port/mp4-onDemand/mp4-onDemand-mpd-AV.mpd.
2. Use exoplayer to play this content.

**Link to test content**
[https://drive.google.com/open?id=17CTa92HnjwT8K_6oFtpAuJrwrBUaa-02](url)

**Version of ExoPlayer being used**
2.9.0 release-v2, Android P.

**Analysing**
The mpd content as follow:
    **SegmentBase indexRangeExact="true" indexRange="860-1611"**
1. Because this mpd content only has indexRange, the player won't read the 0~859 initial data.
2. If I delete the "SegmentBase indexRangeExact="true" indexRange="860-1611"", the player can play this content normally.

I am trying to modify the InitializationChunk to play attach content as follow, but I think this is not a good idea, please give some suggestion, thanks!

```
  protected Chunk newInitializationChunk(
      RepresentationHolder representationHolder,
      DataSource dataSource,
      Format trackFormat,
      int trackSelectionReason,
      Object trackSelectionData,
      RangedUri initializationUri,
      RangedUri indexUri) {
    RangedUri requestUri;
    **long position = 0, length = 0;**
    String baseUrl = representationHolder.representation.baseUrl;
    if (initializationUri != null) {
      // It's common for initialization and index data to be stored adjacently. Attempt to merge
      // the two requests together to request both at once.
      requestUri = initializationUri.attemptMerge(indexUri, baseUrl);
      if (requestUri == null) {
        requestUri = initializationUri;
      }
      **position = requestUri.start;
      length = requestUri.length;**
    } else {
      requestUri = indexUri;
      **position = 0;
      length = requestUri.start + requestUri.length;**
    }
    DataSpec dataSpec = new DataSpec(requestUri.resolveUri(baseUrl), **position**,
        **length**, representationHolder.representation.getCacheKey());
    return new InitializationChunk(dataSource, dataSpec, trackFormat,
        trackSelectionReason, trackSelectionData, representationHolder.extractorWrapper);
  }
```

**Comment by marcbaechinger** [comment]
The link to the mpd seems to be broken. Can you please check and correct so we can look at it?

**Comment by KaiYeYang** [comment]
Hi, @marcbaechinger , thanks for your reply, please download the mpd and media file by using this link:
[https://drive.google.com/file/d/17CTa92HnjwT8K_6oFtpAuJrwrBUaa-02/view?usp=sharing](url)

thanks!

**Comment by marcbaechinger** [comment]
Many thanks!. I was able to download and can confirm the described behaviour. 

The player parses the manifest and reads the `indexRange` which tells in what byte range the index has to be expect. 

`
<SegmentBase indexRangeExact="true" indexRange="860-1611"/>
`

Like your code snippet shows, `DefaultDashChunkSource` then attempts to read initialization and index data according to this description (start=860, length=752). This seems to fail and the player never leaves the buffer state. 

It works, if the indexRange and the `indexRangeExact` attributes are removed and the default values are used do create the `SingleSegmentBase` by the `DashManifestParser`. This results in the same, what your workaround does, which is a range request for initialization with requestUri.start=0, requestUri.length=0. 

The mp4 alone plays fine. Can you confirm that the declared `indexRange` is correct for the given media file?

**Comment by KaiYeYang** [comment]
Hi, @marcbaechinger , I had check the declared indexRage is correct, as the attached picture:
Offset 860 is the start position of 'sidx' box and the offset 1611 is the end position of 'sidx' box. After 'sidx' box is 'moof' box.

![indexrange start position](https://user-images.githubusercontent.com/47199525/52837218-ced48d80-3128-11e9-8a8b-3bde1645c7cb.png)
![indexrange end position](https://user-images.githubusercontent.com/47199525/52837219-cf6d2400-3128-11e9-90bc-3b0dca0de887.png)

Thanks!

**Comment by KaiYeYang** [comment]
```
protected Chunk newInitializationChunk(
      RepresentationHolder representationHolder,
      DataSource dataSource,
      Format trackFormat,
      int trackSelectionReason,
      Object trackSelectionData,
      RangedUri initializationUri,
      RangedUri indexUri) {
    RangedUri requestUri;
    long position = 0, length = 0;
    String baseUrl = representationHolder.representation.baseUrl;
    if (initializationUri != null) {
      // It's common for initialization and index data to be stored adjacently. Attempt to merge
      // the two requests together to request both at once.
      requestUri = initializationUri.attemptMerge(indexUri, baseUrl);
      if (requestUri == null) {
        requestUri = initializationUri;
      }
      position = requestUri.start;
      length = requestUri.length;
    } else {
      requestUri = indexUri;
      **// If it hasn't initialization uri or 'Initialization range' in mpd file, try to get initialization data
      // from offset 0 of the media file.**
      position = 0;
      length = requestUri.start + requestUri.length;
    }
    DataSpec dataSpec = new DataSpec(requestUri.resolveUri(baseUrl), position,
        length, representationHolder.representation.getCacheKey());
    return new InitializationChunk(dataSource, dataSpec, trackFormat,
        trackSelectionReason, trackSelectionData, representationHolder.extractorWrapper);
  }
```

**Comment by marcbaechinger** [comment]
Ok, thanks @KaiYeYang! I'll look into this an see whether we should fallback to start position 0 and length of zero in case of a missing initializationUri. It sounds a bit odd to me to disregard the explicit SegmentBase declaration of the index. 

I look into this to see whether we are doing the right thing. Thanks for reporting and explanation.

**Comment by ojw28** [comment]
The `initializationRange` should really just be included in the content. Note that DASH-IF is going to start making this a requirement for on-demand content to be considered interoperable (see https://github.com/Dash-Industry-Forum/DASH-IF-IOP/issues/242). The vast majority of existing on-demand content includes it. I don't think there's a sufficiently large problem with existing content to justify us doing anything in the client when it's omitted.

**Comment by KaiYeYang** [comment]
Thanks
