### ISSUE TITLE
Ads UI is not removed if player is reused for a different mediaSource

### ISSUE THREAD

**Issue by raunakyadav** [google/ExoPlayer#5514]
### Issue description
Ads UiElements(Learn More, Timer) from an AdsMediaSource are not removed if we replace the mediaSource in exoplayer. 

### Reproduction steps
Play an AdsMediaSource in exoplayer. -> Update the player (without releasing) with new MediaSource. -> Check UI
Scenario : We have a RecyclerView that may show video cards at certain intervals. We are trying to re-use the same exoplayer in all these cards. It works fine if all mediaSources are non-ads.
If an AdsMediaSource is playing the ad, and then we scroll and reuse the player for a new mediaSource, the ad UIelements displayed for previous video are still visible. The whole player state(controller, touch, Learn More, timer) is as if the ad was playing. 

We do not want to release exoplayer and then create a new one to avoid performance hit. Is there a way to cleanly reset an exoplayer?

### Link to test content
 1st Video url = http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4
AdUrl = https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples" + "&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpost&cmsid=496&vid=short_onecue&correlator=
2nd Video Url = http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4

Demo App : https://drive.google.com/open?id=1WXUbU93tXryQmzRGcfHDMn8S2-9Y0xN9

### Version of ExoPlayer being used
2.9.1

### Device(s) and version(s) of Android being used
Samsung Galaxy S6 (Android 7)

### A full bug report captured from the device
Will mail it separately.

**Comment by andrewlewis** [comment]
Are you releasing the `ImaAdsLoader` when switching to a media source without ads? I would have expected that `adsManager.destroy()` in `ImaAdsLoader` would cause the ad UI to go away. If it doesn't work like that, we may need to call `adDisplayContainer.getAdContainer().removeAllViews();` in `ImaAdsLoader.release()`.

**Comment by raunakyadav** [comment]
Just releasing the ImaAdsLoader removed the UiElements but the controller still did not come up. Calling l `adDisplayContainer.getAdContainer().removeAllViews();` fixed the problem. 
Thanks for quick fix.

**Comment by ojw28** [comment]
@andrewlewis - Can this be closed now, or is there something for us to do on our side? Thanks!
