### ISSUE TITLE
Skipping introduction/credits part of the video

### ISSUE THREAD

**Issue by SumukhaK** [google/ExoPlayer#5515]
Hi, I would like to implement features "Skip intro" and "Next episode" like it is in Netflix. Let's say the total duration of the vide is 00:15:12(HH:mm: ss) and I want to skip starting 18 seconds and give a button for Next episode once video exceeds 00:14:42. How can I achieve this? Thanks.

**Comment by marcbaechinger** [comment]
I think you want to receive a message or an event at a given position of a stream. 

After the duration of the intro has elapsed, you want to remove the button and a minute before the end you want to add the 'next episode' button.

What you can do is sending a message at a given position, similar to the snippet below:

```
Handler handler = new Handler();
long introDurationMs = 18 * 1000;
player.createMessage((messageType, payload) -> Log.d("TAG", "At the end of the intro."))
          .setPosition(inbtroDurationMs).setHandler(handler).send();
long noticeBeforeEndMs = 60 * 1000;
player.createMessage((messageType, payload) -> Log.d("TAG", "We are almost at the end"))
          .setPosition(player.getDuration() - noticeBeforeEndMs).setHandler(handler).send();
```
However, these messages are only sent when the given position is actually played. When the user manually seek beyond this position, it's not fired. So you also need to listen to seeks specifically for the 'skip intro' case. When the user seeks beyond introDurationMs you need to remove the button yourself.

I still think this is the easiest way I'm aware of. If you setup your own timers you need much more housekeeping to start/stop timers when the user does a seek/pause/play/etc.

**Comment by SumukhaK** [comment]
Thank you for the response. I agree with "easiest way" part, however, I'm new to all this and I'm afraid I didn't understand the message part of your explanation.
I'm using Java to code my android application which plays .mpd(DASH) files and when it comes to "Message" part of the Exoplayer I kind of lost it. Where can I read about it more? I'm not sure what is "messageType" what is "payload" part in your code snippet.

**Comment by marcbaechinger** [comment]
In the simplest case you don't need these two arguments at all. The default `PlayerMessage.getType() `is 0 and the default `PlayerMessage.getPayload()` is null, as it would be in the example snippet above..

The `messageType` and the `payload` can be set to whatever you want it to be. It's specific to the message you are sending. It is used to transport data from the sender of the message to the target of the message. 

The target has the callback `handleMessage(messsageType, payload)`  where you can decide what to do when a message of a given type arrives. The payload can be used to send  data from the sender to the target.

You can read more about messages sent between ExoPlayer components [in the developer guide](https://google.github.io/ExoPlayer/guide.html#sending-messages-to-components). The JavaDoc of [ExoPlayer.createMessage](http://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/ExoPlayer.html#createMessage-com.google.android.exoplayer2.PlayerMessage.Target-) has some information too, and links to  the classes involved like the [PlayerMessage](http://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/PlayerMessage.html) itself or the [PlayerMessage.Target](http://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/PlayerMessage.Target.html).

**Comment by SumukhaK** [comment]
Okay, I have one minor question.
 If I write method and paste your code snippet in it, where do I call it from? My hunch was to call it after STATE_READY but as I'm playing a playlist of videos and if the first video runs the natural course and second video start playing,  my player will not be entering STATE_READY part of the code.

**Comment by marcbaechinger** [comment]
I'd say you need to be aware of some events in which you need to think whether you need to create the message for a given position or add/remove a button:

After you prepare the player for the first time and start playback. I think best is to wait for the first call of `Player.EventListener.onTracksChange`. From that moment you are sure to have the actual duration of the stream available.

When the player transitions automatically to the next timeline window in the playlist. This calls `Player.EventListener.onPositionDiscontinuity(@Player.DiscontinuityReason int reason)` with reason `Player.DISCONTINUITY_REASON_PERIOD_TRANSITION`.

When the user manually seeks within a window or across windows (skip to next/previous). This will also call 
`Player.EventListener.onPositionDiscontinuity(@Player.DiscontinuityReason int reason)` but with reason `Player.DISCONTINUITY_REASON_SEEK`.

**Comment by SumukhaK** [comment]
I guess I have everything I need. Thanks a lot. In the upcoming version, it will be nice if we can get a flag when the video reaches a particular duration of the video. (Because here I have to re-evaluate the value of _noticeBeforeEndMs_ every time the user seeks within the video).  With a lot of other features in my project, this adds a bit more complexity to the code. Anyway, it is just my opinion and a request though. I appreciate your time and effort in helping me out. Thanks again.

**Comment by bhaskarraj** [comment]
Hello, @marcbaechinger I am trying to getPayload using the PlayerMessage class but the problem that I am facing is in the constructor part.

`new PlayerMessage()` there are sender, target, timeline, defaultWindowIndex and handler.  What are the sender and target in this case? Could you please tell me how it can be passed in the constructor. I have gone through the above docs that you have listed but still, I am confused.

**Comment by ojw28** [comment]
> In the upcoming version, it will be nice if we can get a flag when the video reaches a particular duration of the video. (Because here I have to re-evaluate the value of noticeBeforeEndMs every time the user seeks within the video)

`PlayerMessage` already does what you want. The position you pass to `PlayerMessage.setPosition` is the position in the media at which the `Target` will be called. There's no need to re-evaluate this position when a seek occurs, as far as I can see. You just need to do something like:

```
PlayerMessage message = player.createMessage(new PlayerMessage.Target() {
  @Override
  public void handleMessage(int messageType, @Nullable Object payload)
      throws ExoPlaybackException {
    // Implement what you want to happen here.
  }
});
message.setPosition(playbackPosition) // Set the position in the media at which the target is called
    .setDeleteAfterDelivery(false) // Make it so the target is called every time the position is reached
    .send(); // Send the message
```
