### ISSUE TITLE
Selecting one subtitle among merged resources

### ISSUE THREAD

**Issue by BROUDING** [google/ExoPlayer#5522]
(Question)
I'm getting into this library slowly, but thoroughly due to achieve what I want..

So far so good, just the fact that there is no callback method for failing to getting subtitle file..? (Please let me know if there is)

Anyway, I have "a video" and "subtitles in 3 different languages", I could find that I can merge them into one mediaSource.

And now, I want, people to choose which language subtitle they want right?

And I couldn't find a method for this.. I was kind of understanding "TrackSelector" but it just feels like it's not a method for subtitle..?

How can I set one subtitle to play..?

Thank you.

**Comment by BROUDING** [comment]
If I want to make people to choose subtitles...kinda feels like I should be able to merge subtitle sources with at least one string like (Korean, English, etc...)

**Comment by BROUDING** [comment]
FYI, choosing subtitles Dialog in Netflix is what I want to achieve...

**Comment by marcbaechinger** [comment]
If you sideload your text tracks with a `MergingMediaSource` as [described in the developer guide](https://google.github.io/ExoPlayer/guide.html#side-loading-a-subtitle-file), you can select text tracks by using the `DefaultTrackSelector`. The developer guide has a [section around track selection](https://google.github.io/ExoPlayer/guide.html#track-selection) which covers the `DefaultTrackSelector`.

You can use `DefaultTrackSelector.Parameters` to set the preferred language:

```
trackSelector.setParameters(
  trackSelector
      .buildUponParameters()
      .setPreferredTextLanguage("deu")
      .build());
```

The UI module of the library already has a [TrackSelectionView](https://github.com/google/ExoPlayer/blob/release-v2/library/ui/src/main/java/com/google/android/exoplayer2/ui/TrackSelectionView.java) which builds a view from the track information in a generic way.

**Comment by BROUDING** [comment]
Thanks for giving me updates on current assignment! (I guess I'll work on
something else for few days...? Hahah)

Now I kinda get feelings of how to deal with things, I totally missed "id"
and "language" parameters.

But still... So the selection string on the dialog will be "language"..?
(It doesn't seem like it..)
It'd be great if you can customize that text..! (I can do pull-request but,
Since you guys are working on it right now-)


Have a good day!

2019년 2월 18일 (월) 오전 3:21, Marc Baechinger <notifications@github.com>님이 작성:

**Comment by BROUDING** [comment]
I haven't tried showing selection dialog yet, now I'm working on "default subtitle language when player plays"

So far I've tried... `selectionFlag` parameter in `Format.createTextSampleFormat` seems like the decider.. when I merge more than 2 subtitles into one mediaSource, I set the `selectionFlag` to `C.SELECTION_FLAG_DEFAULT` and the player choose that subtitle to play as default.

Is this how it should be?

>>>> [#3639](https://github.com/google/ExoPlayer/issues/3639)

**Comment by BROUDING** [comment]
Okay.. I've dug deeper and figured out.. the core of this function so far is debugging the whole project...

Though, I think the guide could be more generous...

Anyway, the parameter I should have looked at for changing subtitles after merging them was,
`rendererIndex` in `val dialogPair = TrackSelectionView.getDialog(this, title, trackSelector, rendererIndex)`

`rendererIndex` Choices are-
_0 == Video
1 == Audio
2 == Subtitle_

Thank you, now I understand this library more... :) 👍
Now the issue is customizing the dialog..

1. In callback method `onTracksChanged`, I can get changed parameter `trackSelection`, and the length of it is weird..(for me, it's always 5) and it's pretty tricky to get which language of subtitle I chose...
For usage, I'd like to save the language that user selected and set that data as a default later.

2. How can I customize the view of the dialog?
For example in Netflix, they provide one dialog to change bandwidth & subtitle.

**Comment by marcbaechinger** [comment]
I'd use the `DefaultTrackSelector` to build your dialog. You can use `C.TRACK_TYPE_TEXT` to get the text tracks, so you don't need integer literals. Then iterate through the trackGroups of the text track to get the format of each available track and build up the UI for each entry. You can iterate as follows:

```
MappedTrackInfo mappedTrackInfo = defaultTrackSelector.getCurrentMappedTrackInfo();
int trackType = mappedTrackInfo.getRendererType(rendererIndex);
if (trackType == C.TRACK_TYPE_TEXT) {
  TrackGroupArray trackGroups = mappedTrackInfo.getTrackGroups(rendererIndex);
  for (int i = 0; i < trackGroups.length; i++) {
    for (int j = 0; j < trackGroups.get(i).length; j++) {
      Format format = trackGroups.get(i).getFormat(j);
      Log.d("TAG", "language: " + format.language);
    }
  }
}
```

To select a given language when the user has chosen it, I'd use  `defaultTrackSelector.setPreferredTextLanguage(format.language)` to select the subtitle language.

**Comment by BROUDING** [comment]
Thanks for the updats, but this is what I was talking about [here](https://github.com/google/ExoPlayer/pull/5532)

`C.TRACK_TYPE_TEXT` is 3.
And `rendererIndex` should be 2 to get those data in `getTrackGroups`

**Comment by marcbaechinger** [comment]
Yes, you are right, there is another indirection to check the track type. I corrected the snippet above

**Comment by BROUDING** [comment]
Speaking of this issue..
Most of people are just using integer value for `rendererIndex`.. 
What do you think of adding Integer constant values?
Just like `C.RENDERER_TYPE_VIDEO = 0`, `C.RENDERER_TYPE_AUDIO = 1`, `C.RENDERER_TYPE_TEXT = 2`

**Comment by marcbaechinger** [comment]
I think it makes sense how it is and to not make the assumption that a given renderer index is always of the same type. This would come for the price of being less flexible, while not paying really much.

I close this issue for know. Please reopen if you think I need to add something. Many thanks!

**Comment by BROUDING** [comment]
Many thanks to you!
I learned a lot, but also leaving some guidance about these on "Developer
Guide page" would be really helpful for the future fellows and save your
time..? :)

Take care!

2019년 2월 22일 (금) 오전 6:53, Marc Baechinger <notifications@github.com>님이 작성:
