### ISSUE TITLE
Question: Supporting audio and video mux content stream of MpegDash

### ISSUE THREAD

**Issue by KaiYeYang** [google/ExoPlayer#5526]
**Issue description**
Attach Dash content which has four representations and one adaptionset. In each representation, it has two tracks(audio and video), the player cann't support this content stream.
![mp4-live-mux](https://user-images.githubusercontent.com/47199525/52937584-799fb280-339a-11e9-8bf2-9555b31a2591.png)

**Reproduction steps**
1. Download the attach test content, and make it as a http link, exp: http://ip:port/mp4-live-mux/mp4-live-mux-mpd-AV-BS.mpd.
2. Use exoplayer to play this content.

**Link to test content**
[https://drive.google.com/file/d/1Y5aeOQFtq2mgohYlG7wG-gzd6BaxXwsV/view?usp=sharing](url)
this content stream download from: 
[http://download.tsi.telecom-paristech.fr/gpac/DASH_CONFORMANCE/TelecomParisTech/mp4-live-mux/?C=N;O=D](url)

**Version of ExoPlayer being used**
2.9.0 release-v2, Android P.

**Analysing**
The player will failed in checkContentTypeConsistency function.
`private static int checkContentTypeConsistency(int firstType, int secondType) {
    if (firstType == C.TRACK_TYPE_UNKNOWN) {
      return secondType;
    } else if (secondType == C.TRACK_TYPE_UNKNOWN) {
      return firstType;
    } else {
      Assertions.checkState(firstType == secondType);
      return firstType;
    }
  }`

please give some advise of supporting this content, thanks!

**Comment by ojw28** [comment]
We do not support muxed audio/video streams in DASH, and I don't think such content is generally considered interoperable.
