### ISSUE TITLE
Expose FLAC VORBIS_COMMENT block in metadata

### ISSUE THREAD

**Issue by nlgtuankiet** [google/ExoPlayer#5527]
Is there a way to pull out .flac file metadata (title, album name...)? I tried the EventLogger in the sample app, It work for .mp3 .m4a but not for .flac. I believe the default FlacExtractor already enable peekId3Data.
Not sure this feature is implemented or not.

**Comment by andrewlewis** [comment]
If it's stored as ID3 data at the start of the file and isn't disabled via `FLAG_DISABLE_ID3_METADATA` this should work. If you provide the media you're trying to play we'll take a look (see the [issue template](https://github.com/google/ExoPlayer/issues/new)).

**Comment by nlgtuankiet** [comment]
Sure, I have tried to retrieve the title with MediaMetadataRetriever, it works, so it definitely in there, I just don't know the proper way to get it 
[Muon Ruou To Tinh.zip](https://github.com/google/ExoPlayer/files/2884270/Muon.Ruou.To.Tinh.-.BigDaddy_.Emily.zip)

**Comment by andrewlewis** [comment]
This stream does not have an ID3 prefix, but after the STREAMINFO block at the start there is a PICTURE block and a VORBIS_COMMENT block. The latter has a title and artist, but I don't think we're parsing it at the moment. (It looks like we only handle STREAMINFO and SEEKTABLE in our libflac wrapper.)

I will mark this as a enhancement to store the vorbis comment payload in the metadata but it's low priority for now. I think we'd also be happy to accept a pull request for this.

**Comment by szaboa** [comment]
@ojw28 
I'd like to solve this, if there is no ongoing work on this currently.

**Comment by ojw28** [comment]
This is being worked on already, I think by @vavadhani or one of his colleagues. We expect support to be added soon.

**Comment by szaboa** [comment]
Alright, then I will search for something else :)
