### ISSUE TITLE
HLS Stream - Audio/No Video - but plays via VideoView

### ISSUE THREAD

**Issue by iNdieboyjeff** [google/ExoPlayer#553]
Managed to get ExoPlayer working for playback of HLS streams.  However, when running some tests I discovered that one HLS stream, which plays fine via VideoView, simply plays audio-only via ExoPlayer - whether on 3G, 4G, WiFi, Ethernet.

The stream in question is http://www.bbc.co.uk/mediaselector/playlists/hls/mobile_wifi/ak/bbc1.m3u8 (which is geoblocked to the UK) which I usually find to be a good test stream to work against when I have issues with my own streams.

Any idea why there is no video for this stream?  It seems to play back fine via VideoView, in VLC, etc.

**Comment by ojw28** [comment]
I believe that the stream is faulty (although some other players are more tolerant to the error). Specifically, the first stream appears to only contain audio, however declares in the master playlist that it contains both audio and video.
