### ISSUE TITLE
A mp4 video can not play

### ISSUE THREAD

**Issue by yonglili** [google/ExoPlayer#5533]
http://172.16.1.114:8081/IXC9901eda9103fe51cfde3e2c8d729324a_172.17.156.115/openplat/resource/201901/31/2e58d8744c6f5179a86afd34bf3c70ac.mp4

This video can be played in chrome, but not in ExoPlay demo.

**Comment by marcbaechinger** [comment]
I think 172.16.... is a private IP range.

Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

**Comment by ojw28** [comment]
Closing due to lack of further information.
