### ISSUE TITLE
udp stream play video but can't play audio 

### ISSUE THREAD

**Issue by MuthuKrishnanO** [google/ExoPlayer#5542]
02-21 01:00:45.816 30850-31511/com.example.user.iptv_ridapps I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
02-21 01:00:45.834 30850-31521/com.example.user.iptv_ridapps I/OMXClient: Using client-side OMX mux.
02-21 01:00:45.838 30850-31520/com.example.user.iptv_ridapps I/MediaCodec: MediaCodec::setState == > mCrypto.clear
02-21 01:00:45.841 30850-31521/com.example.user.iptv_ridapps E/ACodec: [OMX.hisi.video.decoder.avc] storeMetaDataInBuffers failed w/ err -2147483648
02-21 01:00:45.841 30850-31521/com.example.user.iptv_ridapps I/ACodec: [OMX.hisi.video.decoder.avc] prepareForAdaptivePlayback(528x576)
02-21 01:00:45.848 30850-31521/com.example.user.iptv_ridapps I/ACodec: [OMX.hisi.video.decoder.avc] Allocating 4 buffers of size 2097152 on input port
02-21 01:00:45.854 30850-31521/com.example.user.iptv_ridapps I/ACodec: [OMX.hisi.video.decoder.avc] will output to SurfaceView
02-21 01:00:45.854 30850-31521/com.example.user.iptv_ridapps I/ACodec: Output will queue to overlay.
02-21 01:00:45.855 30850-31521/com.example.user.iptv_ridapps I/ACodec:  isVideoBypass -- omxBypass = 0, queuesToNativeWindow = 1
02-21 01:00:45.855 30850-31521/com.example.user.iptv_ridapps I/ACodec: [OMX.hisi.video.decoder.avc] Allocating 7 buffers from a native window of size 456192 on output port
![bug](https://user-images.githubusercontent.com/22496015/53093614-e8694100-353d-11e9-93a0-5b11f758b61b.png)

**Comment by MuthuKrishnanO** [comment]
I'm using udpdatasource  to play the video  in  exoplayerview   .

**Comment by andrewlewis** [comment]
Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/ISSUE_TEMPLATE).

**Comment by andrewlewis** [comment]
Note: the logging provided is not necessarily indicative of a problem, so please provide a full bug report.

Ideally, it would be helpful if you could modify the ExoPlayer demo app to load the UDP stream and take the bugreport just after attempting to play it.

**Comment by MuthuKrishnanO** [comment]
now using  the Exoplayer Demo app .but can't install apk to  android SETOFBOX,  it shows the bug like that 

> Failed to find byte code for android/media/MediaDrm$OnKeyStatusChangeListener

**Comment by MuthuKrishnanO** [comment]
connect set-top box  using adb plugin

**Comment by OLIMUTH** [comment]
`02-22 19:05:02.834 23619-23619/? E/libprocessgroup: failed to make and chown /acct/uid_10183: Read-only file system
02-22 19:05:02.834 23619-23619/? W/Zygote: createProcessGroup failed, kernel missing CONFIG_CGROUP_CPUACCT?
02-22 19:05:02.836 23619-23619/? I/art: Late-enabling -Xcheck:jni
02-22 19:05:02.850 23619-23619/? E/Environment: canonicalPath = /storage/sdcard
02-22 19:05:02.858 23619-23631/? E/art: Failed sending reply to debugger: Broken pipe
02-22 19:05:02.858 23619-23631/? I/art: Debugger is no longer active
02-22 19:05:02.981 23619-23650/? D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: false
02-22 19:05:02.987 23619-23619/? D/Atlas: Validating map...
02-22 19:05:03.028 23619-23650/? I/OpenGLRenderer: Initialized EGL, version 1.4
02-22 19:05:03.033 23619-23650/? D/OpenGLRenderer: Enabling debug mode 0
02-22 19:05:03.038 23619-23650/? D/mali_winsys: EGLint new_window_surface(egl_winsys_display*, void*, EGLSurface, EGLConfig, egl_winsys_surface**, egl_color_buffer_format*, EGLBoolean) returns 0x3000
02-22 19:05:14.603 23619-23650/com.google.android.exoplayer2.demo D/mali_winsys: EGLint new_window_surface(egl_winsys_display*, void*, EGLSurface, EGLConfig, egl_winsys_surface**, egl_color_buffer_format*, EGLBoolean) returns 0x3000
02-22 19:05:19.494 23619-23619/com.google.android.exoplayer2.demo I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.exoplayer2.video.MediaCodecVideoRenderer$OnFrameRenderedListenerV23>
02-22 19:05:19.494 23619-23619/com.google.android.exoplayer2.demo I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.exoplayer2.video.MediaCodecVideoRenderer$OnFrameRenderedListenerV23>
02-22 19:05:19.504 23619-23619/com.google.android.exoplayer2.demo I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.exoplayer2.video.MediaCodecVideoRenderer$OnFrameRenderedListenerV23>
02-22 19:05:19.506 23619-23619/com.google.android.exoplayer2.demo I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.exoplayer2.video.MediaCodecVideoRenderer$OnFrameRenderedListenerV23>
02-22 19:05:19.507 23619-23619/com.google.android.exoplayer2.demo I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.exoplayer2.video.MediaCodecVideoRenderer$OnFrameRenderedListenerV23>
02-22 19:05:19.515 23619-23619/com.google.android.exoplayer2.demo I/DefaultRenderersFactory: Loaded LibvpxVideoRenderer.
02-22 19:05:19.522 23619-23619/com.google.android.exoplayer2.demo I/DefaultRenderersFactory: Loaded LibopusAudioRenderer.
02-22 19:05:19.523 23619-23619/com.google.android.exoplayer2.demo I/DefaultRenderersFactory: Loaded LibflacAudioRenderer.
02-22 19:05:19.524 23619-23619/com.google.android.exoplayer2.demo I/DefaultRenderersFactory: Loaded FfmpegAudioRenderer.
02-22 19:05:19.526 23619-23619/com.google.android.exoplayer2.demo I/ExoPlayerImpl: Init 35f6cffe [ExoPlayerLib/2.9.3] [Hi3798CV200, Hi3798CV200, Hisilicon, 22]
02-22 19:05:19.547 23619-23619/com.google.android.exoplayer2.demo D/EventLogger: state [0.00, 0.00, window=0, true, BUFFERING]
02-22 19:05:19.555 23619-23619/com.google.android.exoplayer2.demo D/EventLogger: timelineChanged [0.01, 0.00, window=0, periodCount=1, windowCount=1, reason=PREPARED
02-22 19:05:19.555 23619-23619/com.google.android.exoplayer2.demo D/EventLogger:   period [?]
02-22 19:05:19.555 23619-23619/com.google.android.exoplayer2.demo D/EventLogger:   window [?, false, false]
02-22 19:05:19.555 23619-23619/com.google.android.exoplayer2.demo D/EventLogger: ]
02-22 19:05:19.584 23619-23650/com.google.android.exoplayer2.demo D/mali_winsys: EGLint new_window_surface(egl_winsys_display*, void*, EGLSurface, EGLConfig, egl_winsys_surface**, egl_color_buffer_format*, EGLBoolean) returns 0x3000
02-22 19:05:19.604 23619-23619/com.google.android.exoplayer2.demo D/EventLogger: surfaceSizeChanged [0.06, 0.00, window=0, 1920, 1080]
02-22 19:05:19.720 23619-23619/com.google.android.exoplayer2.demo D/EventLogger: mediaPeriodCreated [0.18, 0.00, window=0, period=0]
02-22 19:05:19.721 23619-23619/com.google.android.exoplayer2.demo D/EventLogger: loading [0.18, 0.00, window=0, period=0, true]
02-22 19:05:19.795 23619-23650/com.google.android.exoplayer2.demo D/OpenGLRenderer: endAllStagingAnimators on 0xa2e70f80 (ExpandableListView) with handle 0xa2d55850
02-22 19:05:19.878 23619-23696/com.google.android.exoplayer2.demo W/VideoCapabilities: Unrecognized profile/level 32768/2 for video/mp4v-es
02-22 19:05:19.890 23619-23696/com.google.android.exoplayer2.demo W/VideoCapabilities: Unrecognized level 0 for video/x-vnd.on2.vp9
02-22 19:05:19.890 23619-23696/com.google.android.exoplayer2.demo W/VideoCapabilities: Unrecognized profile 0 for video/x-vnd.on2.vp9
02-22 19:05:19.893 23619-23696/com.google.android.exoplayer2.demo W/VideoCapabilities: Unsupported mime video/mpeg2
02-22 19:05:19.933 23619-23696/com.google.android.exoplayer2.demo I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
02-22 19:05:19.945 23619-23696/com.google.android.exoplayer2.demo W/VideoCapabilities: Unsupported mime video/mpeg2
02-22 19:05:19.955 23619-23619/com.google.android.exoplayer2.demo D/EventLogger: decoderEnabled [0.41, 0.00, window=0, period=0, video]
02-22 19:05:19.958 23619-23619/com.google.android.exoplayer2.demo D/EventLogger: tracksChanged [0.41, 0.00, window=0, period=0, 
02-22 19:05:19.958 23619-23619/com.google.android.exoplayer2.demo D/EventLogger:   Renderer:0 [
02-22 19:05:19.958 23619-23619/com.google.android.exoplayer2.demo D/EventLogger:     Group:0, adaptive_supported=N/A [
02-22 19:05:19.958 23619-23619/com.google.android.exoplayer2.demo D/EventLogger:       [X] Track:0, id=1/3603, mimeType=video/mpeg2, res=720x576, supported=YES
02-22 19:05:19.958 23619-23619/com.google.android.exoplayer2.demo D/EventLogger:     ]
02-22 19:05:19.958 23619-23619/com.google.android.exoplayer2.demo D/EventLogger:   ]
02-22 19:05:19.958 23619-23619/com.google.android.exoplayer2.demo D/EventLogger:   Renderer:2 [
02-22 19:05:19.958 23619-23619/com.google.android.exoplayer2.demo D/EventLogger:     Group:0, adaptive_supported=N/A [
02-22 19:05:19.958 23619-23619/com.google.android.exoplayer2.demo D/EventLogger:       [ ] Track:0, id=1/3504, mimeType=audio/mpeg-L2, channels=2, sample_rate=48000, supported=NO_UNSUPPORTED_TYPE
02-22 19:05:19.958 23619-23619/com.google.android.exoplayer2.demo D/EventLogger:     ]
02-22 19:05:19.958 23619-23619/com.google.android.exoplayer2.demo D/EventLogger:   ]
02-22 19:05:19.958 23619-23619/com.google.android.exoplayer2.demo D/EventLogger:   Renderer:6 [
02-22 19:05:19.958 23619-23619/com.google.android.exoplayer2.demo D/EventLogger:     Group:0, adaptive_supported=N/A [
02-22 19:05:19.958 23619-23619/com.google.android.exoplayer2.demo D/EventLogger:       [ ] Track:0, id=1/11795, mimeType=application/cea-608, supported=YES
02-22 19:05:19.958 23619-23619/com.google.android.exoplayer2.demo D/EventLogger:     ]
02-22 19:05:19.958 23619-23619/com.google.android.exoplayer2.demo D/EventLogger:   ]
02-22 19:05:19.958 23619-23619/com.google.android.exoplayer2.demo D/EventLogger: ]
02-22 19:05:19.964 23619-23700/com.google.android.exoplayer2.demo I/OMXClient: Using client-side OMX mux.
02-22 19:05:19.969 23619-23699/com.google.android.exoplayer2.demo I/MediaCodec: MediaCodec::setState == > mCrypto.clear
02-22 19:05:19.974 23619-23700/com.google.android.exoplayer2.demo E/ACodec: [OMX.hisi.video.decoder.mpeg2] storeMetaDataInBuffers failed w/ err -2147483648
02-22 19:05:19.974 23619-23700/com.google.android.exoplayer2.demo I/ACodec: [OMX.hisi.video.decoder.mpeg2] prepareForAdaptivePlayback(720x576)
02-22 19:05:19.980 23619-23700/com.google.android.exoplayer2.demo I/ACodec: [OMX.hisi.video.decoder.mpeg2] Allocating 4 buffers of size 2097152 on input port
02-22 19:05:19.986 23619-23700/com.google.android.exoplayer2.demo I/ACodec: [OMX.hisi.video.decoder.mpeg2] will output to SurfaceView
02-22 19:05:19.986 23619-23700/com.google.android.exoplayer2.demo I/ACodec: Output will queue to overlay.
02-22 19:05:19.987 23619-23700/com.google.android.exoplayer2.demo I/ACodec:  isVideoBypass -- omxBypass = 0, queuesToNativeWindow = 1
02-22 19:05:19.988 23619-23700/com.google.android.exoplayer2.demo I/ACodec: [OMX.hisi.video.decoder.mpeg2] Allocating 7 buffers from a native window of size 622080 on output port
02-22 19:05:19.988 23619-23619/com.google.android.exoplayer2.demo D/EventLogger: mediaPeriodReadingStarted [0.45, 0.00, window=0, period=0]
02-22 19:05:19.989 23619-23619/com.google.android.exoplayer2.demo D/EventLogger: downstreamFormatChanged [0.45, 0.00, window=0, period=0, id=1/3603, mimeType=video/mpeg2, res=720x576]
02-22 19:05:20.100 23619-23650/com.google.android.exoplayer2.demo D/mali_winsys: EGLint new_window_surface(egl_winsys_display*, void*, EGLSurface, EGLConfig, egl_winsys_surface**, egl_color_buffer_format*, EGLBoolean) returns 0x3000
02-22 19:05:20.153 23619-23650/com.google.android.exoplayer2.demo V/RenderScript: 0x9fc9e600 Launching thread(s), CPUs 4
02-22 19:05:20.204 23619-23619/com.google.android.exoplayer2.demo D/EventLogger: decoderInitialized [0.66, 0.00, window=0, period=0, video, OMX.hisi.video.decoder.mpeg2]
02-22 19:05:20.204 23619-23619/com.google.android.exoplayer2.demo D/EventLogger: decoderInputFormatChanged [0.66, 0.00, window=0, period=0, video, id=1/3603, mimeType=video/mpeg2, res=720x576]
02-22 19:05:20.250 23619-23619/com.google.android.exoplayer2.demo D/EventLogger: videoSizeChanged [0.71, 0.00, window=0, period=0, 720, 576]
02-22 19:05:20.251 23619-23619/com.google.android.exoplayer2.demo D/EventLogger: renderedFirstFrame [0.71, 0.00, window=0, period=0, Surface(name=null)/@0x20ebee0a]
02-22 19:05:22.142 23619-23619/com.google.android.exoplayer2.demo D/EventLogger: state [2.60, 0.00, window=0, period=0, true, READY]`

**Comment by andrewlewis** [comment]
Looking at the logcat provided via email: this device (Hisilicon Hi3798CV200 API 22) is not advertising support for the audio format: ` D/EventLogger: [ ] Track:0, id=1/3504, mimeType=audio/mpeg-L2, channels=2, sample_rate=48000, supported=NO_UNSUPPORTED_TYPE`.
