### ISSUE TITLE
#5003 Issue fix broke G9X Amlogic Box - Results in black screen

### ISSUE THREAD

**Issue by giridharkannan** [google/ExoPlayer#5545]
### Issue description
OMX.amlogic.avc.decoder.awesome Codec specific patch (refer #5003)  which got released on ExoPlayer v2.9.4 makes the android view completely go blank, when playing Video

### Reproduction steps
Play any mp4 video that is stored locally

### Version of ExoPlayer being used
ExoPlayer v2.9.4 and v2.9.5

### Device(s) and version(s) of Android being used
This is device specific issue
Device - G9X
Manifacturer - ShiningWorth
Android SDK - 23
Hardware - Amlogic

As I commented on #5003, Please do change the method `codecNeedsMaxVideoSizeResetWorkaround` in `MediaCodecVideoRenderer` from private static to protected, so that it would be easy to override the code flow.

**Comment by ojw28** [comment]
I've re-opened #5003. Let's use that for tracking.
