### ISSUE TITLE
Question: Using C.SELECTION_FLAG_DEFAULT to enable subtitles

### ISSUE THREAD

**Issue by HimanshuNarang** [google/ExoPlayer#5546]
Could you try replacing 0 with C.SELECTION_FLAG_DEFAULT in the call to `createTextSampleFormat`? (You need to pass one of the `C.SelectionFlags` constants to [Format.createTextSampleFormat](https://github.com/google/ExoPlayer/blob/dev-v2-r2.5.3/library/core/src/main/java/com/google/android/exoplayer2/Format.java#L289).)

_Originally posted by @andrewlewis in https://github.com/google/ExoPlayer/issues/3324#issuecomment-334720896_

**Comment by HimanshuNarang** [comment]
My code is 

```           DefaultDataSourceFactory dataSourceFactory = new 
            DefaultDataSourceFactory(VideoPlayerApp.getContext(), "MusicOphileVideoPlayer");
            MediaSource[] playlist = null;
            int videoCount = videoPaths.length;

            playlist = new MediaSource[videoCount];

            for (int index = 0; index < videoCount; index++) {
                Uri uri = Uri.parse(videoPaths[index]);
                //Media Source - what type of media to play
                MediaSource mediaSource = new ExtractorMediaSource.Factory(dataSourceFactory).createMediaSource(uri);

                if(index == 0){
                    Format textFormat = Format.createTextSampleFormat(null, MimeTypes.APPLICATION_SUBRIP, null, Format.NO_VALUE, C.SELECTION_FLAG_DEFAULT, "en", null, Format.OFFSET_SAMPLE_RELATIVE);
                    Uri parse = Uri.parse("http://www.storiesinflight.com/js_videosub/jellies.srt");
                    MediaSource textMediaSource = new SingleSampleMediaSource.Factory(dataSourceFactory).createMediaSource(parse, textFormat, C.TIME_UNSET);
                    playlist[index] = new MergingMediaSource(mediaSource, textMediaSource);
                }else{
                    playlist[index] = new MergingMediaSource(mediaSource);
                }
            }

            // Plays the first video, then the second video.
            concatenatedSource = new ConcatenatingMediaSource(playlist);
            player.addTextOutput(new TextOutput() {
                @Override
                public void onCues(List<Cue> cues) {
                    MyLog.d("cues");
                }
            });
            player.prepare(concatenatedSource, true, true);
```

But still subtitle is not showing

**Comment by ojw28** [comment]
It's hard to say what's going wrong in your app, but I tried adding the following four lines to the ExoPlayer demo app, immediately before the `player.prepare` call in `PlayerActivity`, and it worked fine for me. Note these lines are pretty much identical the the four you're using, so I think you're probably doing something wrong elsewhere in your code.

```
Format textFormat = Format.createTextSampleFormat(null, MimeTypes.APPLICATION_SUBRIP, null, Format.NO_VALUE, C.SELECTION_FLAG_DEFAULT, "en", null, Format.OFFSET_SAMPLE_RELATIVE);
Uri parse = Uri.parse("http://www.storiesinflight.com/js_videosub/jellies.srt");
MediaSource textMediaSource = new SingleSampleMediaSource.Factory(dataSourceFactory).createMediaSource(parse, textFormat, C.TIME_UNSET);
mediaSource = new MergingMediaSource(mediaSource, textMediaSource);
```

If you think there's a library issue, please try reproducing the problem in our demo app, and provide us a small patch that would allow us to reproduce.

**Comment by HimanshuNarang** [comment]
As I can debug onUpdate method not get called of TextRenderer and TextRendere is not in ExoPlayerInternalImpl's enabledRenderers array. Am I debugging on the right place?

**Comment by ojw28** [comment]
You'd really be best off starting by looking at the ExoPlayer demo app, and then working out what your code is doing differently. You shouldn't need to debug any internals of the library to work this out.
