### ISSUE TITLE
Does exoplayer can run/support MoPub ads

### ISSUE THREAD

**Issue by hafiz013** [google/ExoPlayer#5549]
Hi may I know is it exoplayer can run ads/ support ads from MoPub?  For you info MoPub similar like dfp but only different is that not from google. You can refer to this [https://www.mopub.com/publishers/platform/](url)

**Comment by andrewlewis** [comment]
The IMA extension should work with VAST and VMAP ad tags, so you can just use that if the provider will produce standard ad tags in those formats.

If not, you'd need to implement your own `AdsLoader` (or find one elsewhere), if you want to leverage the same ad playback functionality that the IMA extension uses.

**Comment by andrewlewis** [comment]
https://developers.mopub.com/docs/ui/creatives/direct-sold-vast/ might possibly help.

**Comment by hafiz013** [comment]
ok thanks bro.
