### ISSUE TITLE
Unable to play MP4 or webm in android 4.1.2 on samasung galaxy duos. 

### ISSUE THREAD

**Issue by amitsamal** [google/ExoPlayer#555]
I am trying to play AD using google ima sdk along with exoplayer. The current ad settings render ads in mp4 and webm formats. But i am unable to play it using exoplayer in samsung galaxy duos phone. The surface view is destroyed throwing this error.
Unable to instantiate decoder 'OMX.qcom.video.decoder.avc'.
06-17 15:44:38.611  26146-26965/com.erosnow E/MediaCodec﹕ Codec reported an error. (omx error 0x80001003, internalError -2147483648)
06-17 15:44:38.611  26146-26928/com.erosnow A/libc﹕ Fatal signal 11 (SIGSEGV) at 0x00000008 (code=1), thread 26928 (ExoPlayerImplIn)

It happens for both formats. Currently we are using mp4Extractor and webmextractor. 
Even tested the exoplayer-dev and exoplayer-master demo there also In MISC section the dizzy mp4 plays but the Big bunny mp4 doesn't throwing the same error. 

Please help.

**Comment by ojw28** [comment]
What's the exact device? There are multiple Samsung devices with names very similar to this one. Ideally provide the model number and/or a link. Thanks!

**Comment by amitsamal** [comment]
The model no is GT-I8552 Android version 4.1.2

**Comment by ojw28** [comment]
Thanks. It looks like it might be device specific. I'll try and get hold of this model and see if I can reproduce.

**Comment by ojw28** [comment]
I think this device might just be very under-powered. If you query the decoder capabilities, it doesn't claim to support much at all. The Android compatibility definition document only requires that devices are able to play up to 720x480 (i.e. 480p) baseline profile level 3 at 30fps. It does appear to be able to do this. The media you're playing is probably main or high profile, if I had to guess.

**Comment by ptran-gpfw** [comment]
@ojw28 What's the canonical way to query decoder capabilities? [MediaCodecInfo](http://developer.android.com/reference/android/media/MediaCodecInfo.html) ?

**Comment by ojw28** [comment]
Yup, that's the one. ExoPlayer has a helper class called MediaCodecUtil, that you may find easier to use.
