### ISSUE TITLE
ConcatenatingMediaSource playback does not advance on Xiaomi Redmi Note3

### ISSUE THREAD

**Issue by johnshazhu** [google/ExoPlayer#5550]
### Issue description
use ConcatenatingMediaSource to play video list as a video, but it can not auto play next video.
if disable audio render, it runs ok.

### Reproduction steps
1.use exoplayer demo project
2.open file media.exolist.json, then replace Playlists's(Cats->Dogs) playlist with test content as follows
3.compile demo app and run, then open exoplayer demo app
4.click Playlists item and select Cats->Dogs menu

### Link to test content
    "name": "Playlists",
    "samples": [
      {
        "name": "Cats -> Dogs",
        "playlist": [
          {
            "uri": "http://video.qn.ivybaby.me/video/1Second/2018-06-04/86/88ae0083795d401c8d5be20781ddb346.mp4"
          },
          {
            "uri": "http://video.qn.ivybaby.me/video/1Second/2018-06-06/86/000f497d31214bfbbea1ece3e98a118e.mp4"
          }
        ]
      }

### Version of ExoPlayer being used
2.9.5

### Device(s) and version(s) of Android being used
device : Xiaomi Redmi Note3
version : 6.0.1
rate : 100%
on other devices such as SamSung S8(8.0.0)、Xiaomi MI 6(8.0.0) and vivo X9(6.0.1), it runs ok

### A full bug report captured from the device
[log.txt](https://github.com/google/ExoPlayer/files/2888517/log.txt)

**Comment by andrewlewis** [comment]
This sounds like a device-specific issue with end-of-stream handling.

**Comment by tonihei** [comment]
Closing as there is nothing we can do about this.

**Comment by johnshazhu** [comment]
After use FfmpegAudioRenderer replace default audio render, i found the method readSource in class BaseRenderer return C.RESULT_NOTHING_READ when the problem occured, the return value will be used in method feedInputBuffer in class SimpleDecoderAudioRenderer. Is it correct to change the call sequence `if (inputBuffer.isEndOfStream())` before `if (result == C.RESULT_NOTHING_READ) `, i resolve the problem by this way.
