### ISSUE TITLE
com.google.android.exoplayer2.ExoPlaybackException happens when multiple player instance created.

### ISSUE THREAD

**Issue by pollux-** [google/ExoPlayer#5556]
I have Exoplayer instance inside a ViewPager, which perfectly works in most of the devices, but in Samsung Galaxy 570F model it's failing with below exception. 

> error com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.Exynos.avc.dec, Format(2, null, null, video/avc, null, -1, null, [1280, 720, -1.0], [-1, -1])

After checking the issues list, I got to know that, its the limitation of creating multiple hardware decoder at the same time. How can I switch to s/w decoder, if that fails? How can I gracefully play the video, if it fails?

[bugreport-2019-02-22-15-23-54.zip](https://github.com/google/ExoPlayer/files/2893424/bugreport-2019-02-22-15-23-54.zip)

**Comment by andrewlewis** [comment]
If the error occurs during initialization of the hardware accelerated codec, you could try using the media codec selector with fallback. Please see the discussion in #5173 for more info.
