### ISSUE TITLE
Playing mp3 - for Android from raw folder

### ISSUE THREAD

**Issue by zsoltboldizsar** [google/ExoPlayer#556]
I've seen some clarifications regarding my problem here (https://github.com/google/ExoPlayer/issues/532) but not directly pointing to raw folder. Raw folder is not mentioned in the docs either (http://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer/upstream/DefaultUriDataSource.html)

Is there any possibility to achieve this? I would like to maintain the media files in raw folder instead of moving them to assets.

**Comment by ojw28** [comment]
Why would you like to use the raw folder instead of moving them to assets?

**Comment by zsoltboldizsar** [comment]
Read that parsing the assets takes more time than from raw folder. http://stackoverflow.com/questions/9563373/the-reason-for-assets-and-raw-resources-in-android
But I'll move them to assets if there's no other possibility.

**Comment by ojw28** [comment]
It's doubtful there's a significant difference, and it's unlikely to make a difference anyway because media is streamed (you'll always be able to load it way faster than you need to to play it back, given it's a local file). So just use assets ;).

**Comment by zsoltboldizsar** [comment]
Thanks for your response.
