### ISSUE TITLE
EXOplayer fails to play m3u8 links !

### ISSUE THREAD

**Issue by littlelitleStar** [google/ExoPlayer#5562]
hello !

I amusing explayer on my app.
implementation 'com.google.android.exoplayer:exoplayer:2.8.2'

till now i used .ts links and it worked good . but now im chaning them to m3u8.

But it seems that exoplayer doesnt play them .
How can i fix this ?

**Comment by AquilesCanta** [comment]
Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/content_not_playing.md).
