### ISSUE TITLE
Question: Is it possible to copy file from cache?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [google/ExoPlayer#5569]
I know it looks similar to this question:
https://github.com/google/ExoPlayer/issues/2711
But I think it's a bit different question nevertheless.

Suppose I have a screen that allows the user to choose from a list of sound-urls, and each clicking on an item plays it while using `SimpleCache` class:
```
     audioPlaybackCache = SimpleCache(..., LeastRecentlyUsedCacheEvictor(MAX_PREVIEW_CACHE_SIZE_IN_BYTES))
    ...
    val factory = CacheDataSourceFactory(audioPlaybackCache , DefaultHttpDataSourceFactory(userAgent)
    val mediaSource = ExtractorMediaSource.Factory(factory).createMediaSource(uri)
    ...
```

Now, when the user has finally chosen a url (for later usage) and exited the screen, I want to try to avoid re-downloading the file from the url, if possible. This means, if the cache already finished downloading it, I will just copy the file to a safe place that I could do something with it.
But if the file is not finished or doesn't exist, I will download it by myself.

Is it possible to do it, or should I re-download all the time? If it's possible, how do I do it ?

**Comment by AquilesCanta** [comment]
@erdemguven, would you kindly look into this?

**Comment by AndroidDeveloperLB** [comment]
@AquilesCanta 

For now, what I did is as such:

```
val cacheSpan: CacheSpan? = cache.getCachedSpans(url).pollFirst()
val cachedFile = cacheSpan?.file
if (cacheSpan?.isCached == true && cachedFile?.exists() == true) {
   // file is cached and ready to be used
   }
```

Is it correct? Or I can't really use it this way?

**Comment by erdemguven** [comment]
It's highly discouraged to access cache files directly. ojw28's response in #2711 is still true and right way to get the cached data.

**Comment by AndroidDeveloperLB** [comment]
@erdemguven It seems very unclear to me, and I can't write there to explain.
Can you please provide a sample for how to do it?
Given the URL of the audio (or video on other cases), how can I get the file from the cache and copy/move it to somewhere more stable ?

**Comment by AndroidDeveloperLB** [comment]
@erdemguven If the URL is of a file we have control of, and I've reached a phase that the player won't need to use the cache anymore (since in my case the user is supposed to choose an item, but he already finished), can I assume that if the file exists, it's ready to be read from ?

**Comment by erdemguven** [comment]
Here is a sample code to read the whole content of a media into a byte array:
```
    DataSource dataSource = new CacheDataSource(myCache, myUpstreamDataSource);
    DataSource dataSource =
        new CacheDataSource(
            myCache,
            // If the cache doesn't have the whole content, the missing data will be read from upstream
            myUpstreamDataSource,
            new FileDataSource(),
            // Set this to null if you don't want the downloaded data from upstream to be written to cache
            new CacheDataSink(cache, CacheDataSink.DEFAULT_FRAGMENT_SIZE),
            /* flags= */ 0,
            /* eventListener= */ null);
    dataSource.open(new DataSpec(myUriToOnlineContent));
    try {
      byte[] data = new byte[1024];
      int position = 0;
      int bytesRead = 0;
      while (bytesRead != C.RESULT_END_OF_INPUT) {
        if (position == data.length) {
          data = Arrays.copyOf(data, data.length * 2);
        }
        bytesRead = dataSource.read(data, position, data.length - position);
        if (bytesRead != C.RESULT_END_OF_INPUT) {
          position += bytesRead;
        }
      }
      byte[] bytes = Arrays.copyOf(data, position);
    } finally {
      dataSource.close();
    }
```

**Comment by AndroidDeveloperLB** [comment]
Thank you.

Where is the `url` that I had? Is it `myUriToOnlineContent` ?
Is it possible to just "pour" the data from the `data` variable into a file? It's a bit odd to save it all in `bytes` array ... Or was it just for demonstration?

**Comment by erdemguven** [comment]
> Where is the `url` that I had? Is it `myUriToOnlineContent` ?

Yes.
> Is it possible to just "pour" the data from the `data` variable into a file? It's a bit odd to save it all in `bytes` array ... 

Yes.
> Or was it just for demonstration?

Yes :)

**Comment by AndroidDeveloperLB** [comment]
OK, but now that I look at it, it seems I still don't understand something of what you wrote:
What is "myUpstreamDataSource" ? 

Currently, what I use in order to load content from URL, is this:

```
fun SimpleExoPlayer.prepareToPlayVideoFromUrl(context: Context, url: String, cache: Cache? = null) = prepareToPlayVideoFromUri(context, Uri.parse(url), cache)

fun SimpleExoPlayer.prepareToPlayVideoFromUri(context: Context, uri: Uri, cache: Cache? = null) {
    val factory = if (cache != null)
        CacheDataSourceFactory(cache, DefaultHttpDataSourceFactory(ExoPlayerEx.getUserAgent(context)))
    else
        DefaultDataSourceFactory(context, ExoPlayerEx.getUserAgent(context))
    val mediaSource = ExtractorMediaSource.Factory(factory).createMediaSource(uri)
    prepare(mediaSource)
}
```
The cache is created as :

```
audioPlaybackCache = SimpleCache(cacheFolder, LeastRecentlyUsedCacheEvictor(MAX_PREVIEW_CACHE_SIZE_IN_BYTES))
```

So, to prepare the player to play from a URL, I just use:

```
                player = ExoPlayerFactory.newSimpleInstance(this, DefaultTrackSelector())
                player!!.prepareToPlayVideoFromUrl(this, url, audioPlaybackCache)
```
Should I change the preparations somehow?

**Comment by erdemguven** [comment]
If the cache doesn't have the whole content, the missing data will be read from myUpstreamDataSource which can be a DefaultHttpDataSource.

**Comment by AndroidDeveloperLB** [comment]
@erdemguven I used the solution that was suggested here:
https://stackoverflow.com/a/55260753/878126
Is it ok?

**Comment by erdemguven** [comment]
As far as I can see it looks OK.

**Comment by AndroidDeveloperLB** [comment]
@erdemguven I see. Thank you!

**Comment by AndroidDeveloperLB** [comment]
I suggest to offer a similar sample here too.
