### ISSUE TITLE
Support for multiple periods in DASH

### ISSUE THREAD

**Issue by chakkarss** [google/ExoPlayer#557]
Currently, I see that the Exoplayer is capable of playing only the first period in the mpd.
Are there any plans to support multiple periods in DASH? 
That would be quite useful to realise Ad Insertion.

**Comment by ryanbateman** [comment]
Just a +1 - this would be a useful enhancement.

**Comment by ryanbateman** [comment]
+1

**Comment by NikhilBN1988** [comment]
+1

**Comment by david2658** [comment]
+1

**Comment by xrigau** [comment]
:+1:

**Comment by david2658** [comment]
Hi. When will this feature land on dev branch?

**Comment by ojw28** [comment]
The `dev-v2` branch now provides full multi-period DASH support.
