### ISSUE TITLE
How to add custom own video ads (mp4) in ImaAdsLoader?

### ISSUE THREAD

**Issue by raikk** [google/ExoPlayer#5570]
I am trying to add my own video url ads of mp4 or any format (e.g lenght of 10 to 20sec) in Exo Player.
IMA ads is working and trying with custom video url. 
I was trying the code from many  git issues but not able to implement it.
Please suggest some example code. i am trying to implement in DashMediaSource.

**Comment by AquilesCanta** [comment]
@andrewlewis, would you kindly look into this?

**Comment by andrewlewis** [comment]
It sounds like you need to produce a VAST/VMAP ad tag that refers to your ads, but we aren't in a position to give guidance on authoring ad tags on this issue tracker I'm afraid.

**Comment by raikk** [comment]
Thanks @andrewlewis . i got some idea for my solution. I need to convert mp4 to VAST/VMAP format for my own ads and needs ads server like revive-ads server. But Free Revive-ads server does not support to convert VAST. we need to use commercial plugin for VAST ad tag.
