### ISSUE TITLE
Build MediaSource from ByteArrayDataSource without the need for any Uri

### ISSUE THREAD

**Issue by ciaranodc** [google/ExoPlayer#5571]
I am aware there are similar questions on this forum (e.g. [#4149](https://github.com/google/ExoPlayer/issues/4149)) but I still can't solve my problem. I have read through ExoPlayer documentation but I can't see how to do this or if it is possible.

I am retrieving an audio file over NDN (http://named-data.net) which does not use URIs. It comes down as an NDN Blob object which then gets converted into an array of bytes. I am creating ByteArrayDataSource using the array of bytes but I have no Uri I can use in this data source. I was attempting to use just a dummy Uri (e.g. "byte:///audio") but it seems a Uri is actually required within ByteArrayDataSource despite the byte array already being added. Is there any way I can remove the need for the Uri or some way I can use a Uri that points to the byte array? Any help much appreciated.

This is how I'm trying to create the MediaSource. It keeps returning null.

    private MediaSource createMediaSourceFromByteArray(byte[] data) {
        ByteArrayDataSource byteArrayDataSource = new ByteArrayDataSource(data);
        Uri bytesUri = Uri.parse("byte:///audio");
        DataSpec dataSpec = new DataSpec(bytesUri);
        try {
            byteArrayDataSource.open(dataSpec);
        } catch (IOException e) {
            e.printStackTrace();
        }

        DataSource.Factory factory = new DataSource.Factory() {
            @Override
            public DataSource createDataSource() {
                return byteArrayDataSource;
            }
        };

        MediaSource mediaSource = new ExtractorMediaSource.Factory(factory)
                .setExtractorsFactory(new DefaultExtractorsFactory())
                .createMediaSource(byteArrayDataSource.getUri());

        return mediaSource;
    }

**Comment by AquilesCanta** [comment]
> This is how I'm trying to create the MediaSource. It keeps returning null.

What keeps returning null?

> Is there any way I can remove the need for the Uri

You don't need to remove the need for the Uri. You should be able to pass an empty uri.

Probably unrelated, you don't need to/shouldn't open the data source. So basically you should remove the 

```
try {
        byteArrayDataSource.open(dataSpec);
    } catch (IOException e) {
        e.printStackTrace();
    }
```

block, plus use something like `Uri.EMPTY` for the createMediaSource invocation.

Please also provide a bugreport captured briefly after trying to play your content. The more information you provide, the faster I'll be able to provide assistance.

**Comment by ciaranodc** [comment]
Hi Aquiles. I updated my method as per you suggestions and my mediaSource that I return at the end of the method is no longer null! So this proves a valid Uri is NOT required to build the MediaSource. Thanks for your help! 

    private MediaSource createMediaSourceFromByteArray(byte[] data) {
        ByteArrayDataSource byteArrayDataSource = new ByteArrayDataSource(data);
        DataSource.Factory factory = new DataSource.Factory() {
            @Override
            public DataSource createDataSource() {
                return byteArrayDataSource;
            }
        };
        MediaSource mediaSource = new ExtractorMediaSource.Factory(factory)
                .setExtractorsFactory(new DefaultExtractorsFactory())
                .createMediaSource(Uri.EMPTY);

        return Objects.requireNonNull(mediaSource, "MediaSource cannot be null");
    }
