### ISSUE TITLE
ExoPlayer Video not playing for Android version 4.2.1

### ISSUE THREAD

**Issue by palakRpatel** [google/ExoPlayer#558]
I have one issue while using android ExoPlayer for streaming url. Here I have attached sample URL: 

It is working in some device, but not not working for Android version 4.2.1 (Micromax canvas 116) It shows buffering video, but not playing. If I select video option as OFF then it plays, but only audio comes no pictures visible.

```
new Sample("Super speed (PlayReady)", "xyz.ism", DemoUtil.TYPE_SS),
```

**Comment by kthangvd** [comment]
I have same problem,
On android 4.2.1 with OMX.MTK.VIDEO.ENCODER.AVC

07-20 16:20:48.202  11190-11190/? E/MtkOmxVdec﹕ OMX_GoogleAndroidIndexEnableAndroidNativeBuffers enable(1)
07-20 16:20:48.269      138-840/? E/IMGSRV﹕ :0: gralloc_device_alloc: attach special flag :Format101.
07-20 16:20:48.271      138-138/? E/IMGSRV﹕ :0: gralloc_device_alloc: attach special flag :Format101.
07-20 16:20:48.273    138-19440/? E/IMGSRV﹕ :0: gralloc_device_alloc: attach special flag :Format101.
07-20 16:20:48.276     138-4946/? E/IMGSRV﹕ :0: gralloc_device_alloc: attach special flag :Format101.
07-20 16:20:48.282    138-19440/? E/IMGSRV﹕ :0: gralloc_device_alloc: attach special flag :Format101.
07-20 16:20:48.287      138-840/? E/IMGSRV﹕ :0: gralloc_device_alloc: attach special flag :Format101.
07-20 16:20:48.312     138-2344/? E/IMGSRV﹕ :0: gralloc_device_alloc: attach special flag :Format101.
07-20 16:20:48.315    138-19440/? E/IMGSRV﹕ :0: gralloc_device_alloc: attach special flag :Format101.
07-20 16:20:48.319      138-587/? E/IMGSRV﹕ :0: gralloc_device_alloc: attach special flag :Format101.
07-20 16:20:48.323      138-840/? E/IMGSRV﹕ :0: gralloc_device_alloc: attach special flag :Format101.
07-20 16:20:48.326     138-4946/? E/IMGSRV﹕ :0: gralloc_device_alloc: attach special flag :Format101.
07-20 16:20:48.336     138-4946/? E/IMGSRV﹕ :0: gralloc_device_alloc: attach special flag :Format101.
07-20 16:20:48.339      138-840/? E/IMGSRV﹕ :0: gralloc_device_alloc: attach special flag :Format101.
07-20 16:20:48.345     138-4946/? E/IMGSRV﹕ :0: gralloc_device_alloc: attach special flag :Format101.
07-20 16:20:48.349    138-19440/? E/IMGSRV﹕ :0: gralloc_device_alloc: attach special flag :Format101.
07-20 16:20:48.352      138-138/? E/IMGSRV﹕ :0: gralloc_device_alloc: attach special flag :Format101.
07-20 16:20:48.355     138-4946/? E/IMGSRV﹕ :0: gralloc_device_alloc: attach special flag :Format101.
07-20 16:20:48.358    138-19440/? E/IMGSRV﹕ :0: gralloc_device_alloc: attach special flag :Format101.
07-20 16:20:48.361      138-138/? E/IMGSRV﹕ :0: gralloc_device_alloc: attach special flag :Format101.
07-20 16:20:48.365    138-19440/? E/IMGSRV﹕ :0: gralloc_device_alloc: attach special flag :Format101.
07-20 16:20:48.367      138-138/? E/IMGSRV﹕ :0: gralloc_device_alloc: attach special flag :Format101.
07-20 16:20:48.391   19540-1368/com.google.android.exoplayer.demo E/ACodec﹕ cannot find aac bit rate
07-20 16:20:48.392  11190-11190/? E/OMXNodeInstance﹕ OMX_GetExtensionIndex failed
07-20 16:20:48.408   11190-1366/? E/MtkOmxVdec﹕ VAL_CHIP_NAME_MT6589
07-20 16:20:48.410   11190-1366/? E/VDO_LOG﹕ [Err] ? un-support type of NAL
07-20 16:20:48.474   11190-1366/? E/VDO_LOG﹕ [Err] ? un-support type of NAL
07-20 16:20:48.476   11190-1366/? E/VDO_LOG﹕ [Err] ? un-support type of NAL
07-20 16:20:48.476   11190-1366/? E/VDO_LOG﹕ [Err] ? un-support type of NAL
07-20 16:20:48.476   11190-1366/? E/VDO_LOG﹕ [Err] ? un-support type of NAL
...

Please help me!!

**Comment by ashwithraja** [comment]
Same issue. please help me

**Comment by ojw28** [comment]
I'm not really sure what this issue is tracking. The original post states it attaches a sample URL, but there isn't one. Hence we cannot reproduce. If this is still an issue on the latest release, please file a new issue with all of the information requested [here](https://google.github.io/ExoPlayer/2015/10/01/reporting-issues.html).
