### ISSUE TITLE
Failed to find byte code for android/media/MediaDrm$OnKeyStatusChangeListener 

### ISSUE THREAD

**Issue by userdimi** [google/ExoPlayer#5581]
### [REQUIRED] Issue description
I have downloaded the latest Exoplayer version from github (2.9.6 -> branch = release v2) 
When I try to run the demo application on any devices running on SDK 22 Android 5.1.1  (virtual or physical devices, I'm getting this error

`Failed to find byte code for android/media/MediaDrm$OnKeyStatusChangeListener`

### [REQUIRED] Reproduction steps
Checkout latest exoplayer version from github
start virtual device running SDK 22 Android 5.1.1
press Run button in Android Studio

### [REQUIRED] Link to test content
not needed in this case

### [REQUIRED] A full bug report captured from the device
not needed in this case

### [REQUIRED] Version of ExoPlayer being used
2.9.6

### [REQUIRED] Device(s) and version(s) of Android being used
Android SDK 22 / 5.1.1
Android SDK 21 / 5.0.2
- virtual device: Nexus 5 Api 22 5.1.1
- physical device: Samsung Galaxy Tab 4 SM-T530  Api 21 5.0.2

**Comment by AquilesCanta** [comment]
Hi, I have just cloned the repo and checked out 2.9.6 and successfully played a DASH video on a Nexus 5 emulator running API 22.

Fingerprint: Android/sdk_google_phone_x86/generic_x86:5.1.1/LMY48X/5056529:userdebug/test-keys

If you can provide steps to reproduce the issue, including fetching the code from the repository, I'll reopen the issue. Cloning, checking out 2.9.6 and running the demo app on an API 22 emulator works as expected for me.

**Comment by simon20190306** [comment]
I have the same problem!

**Comment by simon20190306** [comment]
When I close the instant run, the problem is solved.
