### ISSUE TITLE
On the 4.4 system, when there is Chinese in the song link, a 404 error will be reported. What is the solution?

### ISSUE THREAD

**Issue by EspoirX** [google/ExoPlayer#5586]
![afe1d659b01dc52784ccb85aee5de31f](https://user-images.githubusercontent.com/16240767/53611404-64801a80-3c09-11e9-8ed8-3f86008468a0.png)

**Comment by AquilesCanta** [comment]
Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md).
