### ISSUE TITLE
How to show subtitle in android ExoPlayer

### ISSUE THREAD

**Issue by palakRpatel** [google/ExoPlayer#559]
Hello All,

I am using Exoplayer for streaming url.
I want to add .srt file in exoplayer.
but i think player not support srt file
so i put my file content in 1 variable.
Now my question is,
How to show subtitles in android exoplayer.

**Comment by bsysop** [comment]
I don't know if this is right, but works perfect for me.

case ExoPlayer.STATE_PREPARING:
    	  Log.e(TAG, "playbackState: preparing");
    	  if (SubtitleReady == false && haveTracks(DemoPlayer.TYPE_TEXT)) {
    		  Log.e(TAG, "Configuring Subtitles track 0");
    		  SubtitleReady = true;
    		  player.selectTrack(DemoPlayer.TYPE_TEXT, 0);
    	  }
        break;

"player.selectTrack(DemoPlayer.TYPE_TEXT, 0);"
- Force to show Subtitles.

"SubtitleReady"
- Is my private var to don't do this job again!

**Comment by palakRpatel** [comment]
I want to show the subtitle. where to show it.
there is interface available SubtitleParser but i don't know hoe to implement and were to use it.
Can you please help me how to use SubtitleParserHelper in my activity

**Comment by ojw28** [comment]
Let's use #587 to track this.

**Comment by palakRpatel** [comment]
I got the solution. I convert srt file into ttf file using TimedTextFileFormat Below is my code to convert srt to TTML,

private Subtitle subttl;

private void parseSubtitile(String subtitle) {

// subtitle is the srt file content
            // TODO Auto-generated method stub
            // StringBuilder buf = new StringBuilder();

InputStream json = null;
json = null;
        json = new ByteArrayInputStream(subtitle.getBytes());
    // FormatTTML formate = new FormatTTML();
    InputStream is = null;
    try {
        // TimedTextObject ttmlObj=formate.parseFile("Testing", json);
        TimedTextFileFormat ttff = new FormatSRT();
        TimedTextObject tto = ttff.parseFile("Test", json);
        // IOClass.writeFileTxt("test1", tto.toTTML());

        String data = tto.toTTML();
        is = new ByteArrayInputStream(data.getBytes());
        Log.d("web", data.toString());
    } catch (IOException e1) {
        // TODO Auto-generated catch block
        e1.printStackTrace();
    } catch (FatalParsingException e1) {
        // TODO Auto-generated catch block
        e1.printStackTrace();
    }

    TtmlParser parser = new TtmlParser();
    try {
        subttl = parser.parse(is, null, 0);
    } catch (IOException e) {
        // TODO Auto-generated catch block
        e.printStackTrace();
    }
}
Then in player activity pass subtitle to respected builder, In this i am sending to HlsRendererBuilder.

private RendererBuilder getRendererBuilder() {
        String userAgent = Util.getUserAgent(this, "ExoPlayerDemo");
        switch (contentType) {

    case DemoUtil.TYPE_HLS:
        return new HlsRendererBuilder(this, userAgent,
                contentUri.toString(), debugTextView, audioCapabilities,
                    subttl);
}
And from HlsRendererBuilder class pass it to TrackRenderer, // Build the debug renderer.

TrackRenderer debugRenderer = debugTextView != null
    ? new DebugTrackRenderer(debugTextView, player, videoRenderer,context,subttl) : null;
And in DebugTrackRenderer class in run method use below code,

public void run() {
    String data1 = subttl.getText(getCurrentPositionUs());

    player.onText(String.valueOf(data1));


}

**Comment by palakRpatel** [comment]
I got the solution. I convert srt file into ttf file using TimedTextFileFormat Below is my code to convert srt to TTML,

private Subtitle subttl;

private void parseSubtitile(String subtitle) {
// subtitle is the srt file content
            // TODO Auto-generated method stub
            // StringBuilder buf = new StringBuilder();
InputStream json = null;
json = null;
        json = new ByteArrayInputStream(subtitle.getBytes());
    // FormatTTML formate = new FormatTTML();
    InputStream is = null;
    try {
        // TimedTextObject ttmlObj=formate.parseFile("Testing", json);
        TimedTextFileFormat ttff = new FormatSRT();
        TimedTextObject tto = ttff.parseFile("Test", json);
        // IOClass.writeFileTxt("test1", tto.toTTML());
String data = tto.toTTML();
        is = new ByteArrayInputStream(data.getBytes());
        Log.d("web", data.toString());
    } catch (IOException e1) {
        // TODO Auto-generated catch block
        e1.printStackTrace();
    } catch (FatalParsingException e1) {
        // TODO Auto-generated catch block
        e1.printStackTrace();
    }
 TtmlParser parser = new TtmlParser();
    try {
        subttl = parser.parse(is, null, 0);
    } catch (IOException e) {
        // TODO Auto-generated catch block
        e.printStackTrace();
    }
}
Aftre that in player activity pass subtitle to respected builder, In this i am sending to HlsRendererBuilder.

private RendererBuilder getRendererBuilder() {
        String userAgent = Util.getUserAgent(this, "ExoPlayerDemo");
        switch (contentType) {
             case DemoUtil.TYPE_HLS:
        return new HlsRendererBuilder(this, userAgent,
                contentUri.toString(), debugTextView, audioCapabilities,
                    subttl);
}

From HlsRendererBuilder class pass it to TrackRenderer, // Build the debug renderer.

TrackRenderer debugRenderer = debugTextView != null
    ? new DebugTrackRenderer(debugTextView, player, videoRenderer,context,subttl) : null;

And in DebugTrackRenderer class in run method use below code,

public void run() {
    String data1 = subttl.getText(getCurrentPositionUs());
player.onText(String.valueOf(data1));
}

**Comment by kunalbhatia** [comment]
Hi  @palakRpatel, can you send a example for the same using wetransfer.

Please, much appropriated.

**Comment by palakRpatel** [comment]
Please check Exoplayer bundle in following weTranfer link
http://we.tl/b3j7giV1If

**Comment by edsphinx** [comment]
@palakRpatel Can you upload that sample again please?, is not longer available in wetransfer.
