### ISSUE TITLE
Widewine DRM catch-up content not playing

### ISSUE THREAD

**Issue by prakash-khandelwal** [google/ExoPlayer#5590]
We are having a single live channel dash stream which plays a live content when played directly and catch-up content when sending a **begin** and **end** time parameters. Content is encrypted with widewine drm.
When we try to play live content, it decrypts and plays seamlessly without any issues but when we try to play catch-up content, exoplayer is failing playback and giving below error log with NPE-

```
2019-03-03 13:31:56.065 12357-13361/com.google.android.exoplayer2.demo E/LoadTask: Unexpected exception loading stream
    java.lang.NullPointerException: Attempt to read from field 'int com.google.android.exoplayer2.extractor.mp4.TrackEncryptionBox.perSampleIvSize' on a null object reference
        at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.parseSaiz(FragmentedMp4Extractor.java:745)
        at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.parseTraf(FragmentedMp4Extractor.java:680)
        at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.parseMoof(FragmentedMp4Extractor.java:648)
        at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.onMoofContainerAtomRead(FragmentedMp4Extractor.java:529)
        at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.onContainerAtomRead(FragmentedMp4Extractor.java:454)
        at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.processAtomEnded(FragmentedMp4Extractor.java:432)
        at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.readAtomPayload(FragmentedMp4Extractor.java:427)
        at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:313)
        at com.google.android.exoplayer2.source.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:135)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:379)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```

I tried looking for this issue but didn't find much information on this. It will be of great help if someone can provide a way forward.

**Exoplayer Version: 2.9.0
Android Version: 9.0 Pie (Android TV)**

I'm sorry but I can't provide content url and drm license url due to confidentiality and NDA with client.

**Comment by ojw28** [comment]
> We are having a single live channel dash stream which plays a live content when played directly and catch-up content when sending a begin and end time parameters.

It's almost certainly the case that they're simply not generating a valid DASH manifest when you're setting the begin and end parameters. We've seen a lot of issues where content providers will generate DASH manifests that don't have their timelines setup correctly when doing this kind of thing.

**Comment by ojw28** [comment]
Deleted unrelated comment (sorry). Still, this is most likely a content issue. Without being able to look at the content, there's not a whole lot we can do to help.

**Comment by prakash-khandelwal** [comment]
@ojw28 can you tell me what all details you would need? I would try from my side how much details I can provide without compromising the NDA.

**Comment by ojw28** [comment]
There is little alternative but to provide a working test stream, if you want us to help.

**Comment by prakash-khandelwal** [comment]
@ojw28 Hi, I tried looking more deep through Charles, what happens when we try to play a drm enabled catch-up content. My observation found that for drm catch-up, exoplayer makes partial content request and gets into 206 response from server but doesn't play. I tried with google provided drm catch-up test links, in that case also exoplayer is making partial content request and gets into 206 response but plays seamlessly.

I also noticed that for non-drm catch-up content, exoplayer makes a full content request and gets 200 response code and plays successfully. All other configuration (drm and non-drm live content) also gets 200 response and plays seamlessly.

I have below queries-

1. Why do Exoplayer behave different for drm enabled catcu-up content?
2. Is it because of some CDN / Cache server setting or its the way of Exoplayer to handle drm catch-up?
3. Is there any way where I can tell Exoplayer to make full content request and not partial request?
4. If not, what could be the server (CDN / Cache / DRM) side setting which can resolve this issue?

**Comment by ojw28** [comment]
I think you're focusing on the wrong thing. There's no evidence here that ExoPlayer is doing anything wrong by making range requests (rather than full requests), or that it's related to the actual problem of the content not playing.

ExoPlayer doesn't decide whether to make range requests based on whether the content is catch-up or not, or whether it has DRM. In all cases ExoPlayer will simply make the requests that it needs to play the content. For DASH, these may or may not be range requests, depending on things like whether the content is single segment, or whether it uses `SegmentTimeline` and/or `SegmentTemplate`. Whatever requests are made, those are the correct ones for the media. A setting to change the requests to something else wouldn't make sense.

I think it's more likely that the content you're trying to play is malformed. As I've already said, there is nothing we can do to assist without a working test stream. I'm going to close this issue for now. If you're able to provide a working test stream, please respond here and we'll take a look.

**Comment by giladna** [comment]
@ojw28  I face same exception on our live dash DRM stream
sending url and license in the exo gmail

the exception is occuring o the Demo app of v2.10 when switching bitrates

sending bug report as well

10x
Gilad

**Comment by ojw28** [comment]
The stream is just giving 403 response codes for me. Please can you make sure it's accessible?
