### ISSUE TITLE
Please embed codec audio/mpeg-L2, because many device not have this codec

### ISSUE THREAD

**Issue by yunusalam** [google/ExoPlayer#5591]
Before filing a feature request:
-----------------------
I have searched, but found this features request.

When filing a feature request:
-----------------------
Fill out the sections below, leaving the headers but replacing the content. If
you're unable to provide certain information, please explain why in the relevant
section. We may close issues if they do not include sufficient information.

### [REQUIRED] Use case description
I want to play these stream:
1. http://103.89.63.168:9016
2. http://103.89.63.168:9017
3. http://103.89.63.168:9018

### Proposed solution
I going to start free IPTV in our city, so, we required a player to play above stream. I can not purchase expensive software, because, I have no budget for free IPTV solution and I am starting period, that cause I want to use ExoPlayer, it is good solution for us, but it is not support on all devices audio/mpeg-L2.

kindly add any codec for  audio/mpeg-L2,

### Alternatives considered
I can donate some amount for it.

**Comment by ojw28** [comment]
I think you can already do this with the FFmpeg extension, however there's some extra work involved to build it. Build instructions are [here](https://github.com/google/ExoPlayer/tree/release-v2/extensions/ffmpeg). As per the [supported formats page](https://google.github.io/ExoPlayer/supported-formats.html), you should use `--enable-decoder=mp3` when building (I think the FFmpeg MP3 decoder includes `audio/mpeg-L2` support).
