### ISSUE TITLE
Show all audio tracks in one view

### ISSUE THREAD

**Issue by mhajhassan** [google/ExoPlayer#5594]
When filing a question:
-----------------------
Fill out the sections below, leaving the headers but replacing the content. If
you're unable to provide certain information, please explain why in the relevant
section. We may close issues if they do not include sufficient information.

### [REQUIRED] Searched documentation and issues
I already looked in the documentation but didn't find how.
### [REQUIRED] Question
How can I show the audio track in one [dialog], when I have a video with 2 audio tracks, the app will create 2 buttons in debugRootView, for each audio track, this has been tested in the demo app.
![1](https://user-images.githubusercontent.com/20266380/53795203-bd192580-3f31-11e9-93c6-bbef4891d10f.png)
![2](https://user-images.githubusercontent.com/20266380/53795205-bd192580-3f31-11e9-8f58-40b14a56a36d.png)
![3](https://user-images.githubusercontent.com/20266380/53795206-bdb1bc00-3f31-11e9-808a-70d23a0c927e.png)

**Comment by ojw28** [comment]
There is no requirement for you to use ExoPlayer's out of the box UI components, and you're free to build your own UI that does something different. Note that you can look at the source code for our UI components to see how they do things like querying and listing the available tracks, and then implement similar logic yourself that builds the UI you want.

This seems like more of a general question about Android development, and so falls outside the scope of this issue tracker. I'd suggest you ask on StackOverflow if you can't work out what to do.
