### ISSUE TITLE
I want to get video frame_rate, ExoPlayer.getVideoFormat().frameRate is always -1

### ISSUE THREAD

**Issue by tanpuer** [google/ExoPlayer#5598]
But when is use MediaExtractor directly, I can get frame_rate is 24.
mMediaExtractor.setDataSource(file.toString())
        val numTracks = mMediaExtractor.trackCount
        for (i in 0..numTracks) {
            val mediaFormat = mMediaExtractor.getTrackFormat(i)
            val mime = mediaFormat.getString(MediaFormat.KEY_MIME)
            if (mime.startsWith("video/")) {
                mVideoTrack = i
                break
            }
        }
        if (mVideoTrack == -1) {
            throw RuntimeException("file contains no video track, please check")
        }
        mMediaExtractor.selectTrack(mVideoTrack)
        mMediaFormat = mMediaExtractor.getTrackFormat(mVideoTrack)
        mVideoWidth = mMediaFormat.getInteger(MediaFormat.KEY_WIDTH)
        mVideoHeight = mMediaFormat.getInteger(MediaFormat.KEY_HEIGHT)

![image](https://user-images.githubusercontent.com/16443498/53853374-27989700-4000-11e9-92a7-e93f8b7c545f.png)

**Comment by tanpuer** [comment]
By the way, can I get total video frames and current frame index?

**Comment by ojw28** [comment]
> By the way, can I get total video frames and current frame index?

This is not something we plan to support. What use case do you have for it?

> ExoPlayer.getVideoFormat().frameRate is always -1

We don't derive a frame rate unless it's specified in the container (or for adaptive content, the manifest that defines the stream), and have no plans to do so. What use case do you have for it?

If you're able to provide a piece of sample content then we can look to see whether the frame rate is specified in the container in a place that we can easily parse it from.

**Comment by tanpuer** [comment]
[trailer.mp4.zip](https://github.com/google/ExoPlayer/files/2936079/trailer.mp4.zip)
I use this classical video to test.

I need current frameRate because i need to record while playing(like RecordFBOActivity in grafika). And I need to do clipping and add shader effect.

**Comment by ojw28** [comment]
We're now filling in frame rate for MP4 videos.
