### ISSUE TITLE
When I try to pay this video, the screen blurred in  sixth seconds.(Android 8.1 Pixl2)

### ISSUE THREAD

**Issue by www586089** [google/ExoPlayer#5599]
Issue description
When I try to pay this video, the screen blurred in the sixth seconds

Reproduction steps
first use mediamuxer to merge two video(a protrait video and a landscape video ), the 
Just use code simpleExoPlayer = ExoPlayerFactory.newSimpleInstance(this); to create a player and play the merge video with this player.
I don't know why this happen, could you please help find why and what can do with this problem ?(I can play this video with QQ brower android app or some other player)

Link to test content
https://drive.google.com/file/d/1JTuuKyjzz0OwPx6idkuz_P5CECqVNh32/view?usp=sharing

Version of ExoPlayer being used
version 2.9.6

Device(s) and version(s) of Android being used
Android 8.1 pixel2

A full bug report captured from the device
[2926bugreport.txt](https://github.com/google/ExoPlayer/files/2934137/2926bugreport.txt)

**Comment by ojw28** [comment]
The test content doesn't play correctly in Chrome, Safari or VLC on my Mac, so I think the content is broken. Marking as such.
