### ISSUE TITLE
Condition always false in getPlaybackState()

### ISSUE THREAD

**Issue by xorgate** [google/ExoPlayer#560]
https://github.com/google/ExoPlayer/blob/acee5660abe84311473817042f3c15f953356b3a/demo/src/main/java/com/google/android/exoplayer/demo/player/DemoPlayer.java#L376

Not sure what the idea here is...

**Comment by ojw28** [comment]
It's true in exactly the edge case that's documented 2 lines below the line you've linked to. This only occurs for a very brief period of time whilst a few messages are passed between threads.
