### ISSUE TITLE
Crash app after updating ExoPlayer to 2.9.6

### ISSUE THREAD

**Issue by haihack** [google/ExoPlayer#5600]
### Issue description
App crashes when I update ExoPlayer version from 2.8.4 to 2.9.6 and it occurs on android version 7.1 and 8.1 (I haven't tested on other versions but I worked normally on android 6)

### Code

```
private void init() {
        bandwidthMeter = new DefaultBandwidthMeter();
        trackSelectionFactory = new AdaptiveTrackSelection.Factory(bandwidthMeter);
        trackSelector = new DefaultTrackSelector(trackSelectionFactory);

        OkHttpClient client = new OkHttpClient.Builder()
//                .readTimeout(10000, TimeUnit.MILLISECONDS)
//                .writeTimeout(10000, TimeUnit.MILLISECONDS)
                .build();

        dataSourceFactory = new ShoutcastDataSourceFactory(
                client,
                Util.getUserAgent(context, context.getString(R.string.app_name)),
                null,
                this);

        player = ExoPlayerFactory.newSimpleInstance(context, trackSelector);
        player.setPlayWhenReady(true);
        player.addListener(eventListener);
    }

public void prepareMediaSource() {
        MediaSource mediaSource = new ExtractorMediaSource.Factory(dataSourceFactory)
                .setExtractorsFactory(new DefaultExtractorsFactory())
                .createMediaSource(Uri.parse(AZStreamManager.getInstance().getCurrentStation().getStreamURL()));
        player.prepare(mediaSource);
        AppLogger.i(">>Playing station: " + AZStreamManager.getInstance().getCurrentStation().getName());
    }
```

### A full bug report captured from the device

```
E/AndroidRuntime: FATAL EXCEPTION: ExoPlayerImplInternal:Handler
    Process: com.bar.foo, PID: 1882
    java.lang.AbstractMethodError: abstract method "void com.google.android.exoplayer2.upstream.DataSource.addTransferListener(com.google.android.exoplayer2.upstream.TransferListener)"
        at com.google.android.exoplayer2.source.ExtractorMediaSource.createPeriod(ExtractorMediaSource.java:381)
        at com.google.android.exoplayer2.MediaPeriodHolder.<init>(MediaPeriodHolder.java:82)
        at com.google.android.exoplayer2.MediaPeriodQueue.enqueueNextMediaPeriod(MediaPeriodQueue.java:149)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.maybeUpdateLoadingPeriod(ExoPlayerImplInternal.java:1523)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.updatePeriods(ExoPlayerImplInternal.java:1392)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:506)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)
```

### Version of ExoPlayer being used
2.9.6

### Device(s) and version(s) of Android being used
Android 7.1 & 8.1

**Comment by ojw28** [comment]
As of ExoPlayer 2.9.0 you need to enable Java 8 support in your app when using ExoPlayer. To do this, add the following to the `android` section of all `build.gradle` files that depend on ExoPlayer modules:
```
compileOptions {
  targetCompatibility JavaVersion.VERSION_1_8
}
```
You can see an example in our demo app [here](https://github.com/google/ExoPlayer/blob/r2.9.6/demos/main/build.gradle#L21).

**Comment by haihack** [comment]
I had done. It was not the point.
```
compileOptions {
        targetCompatibility 1.8
        sourceCompatibility 1.8
}
```

**Comment by ojw28** [comment]
In nearly all cases it turns out this is what's wrong, for this type of error. Are you sure you have added the correct thing, in the correct place, in the correct `build.gradle` files? I'm not sure if the way you've done it is functionally identical, but note use of `1.8` (without any quotes) is not exactly the same as in our demo app or guide instructions, where `JavaVersion.VERSION_1_8` is used.

If you're still having issues, I think you'll need to provide us with a small demonstration project that shows the issue.

**Comment by tonihei** [comment]
These issues also occurred in the past if Android Studio failed to update
the dependency code correctly and it helped to re-build the project from
scratch (File -> Invalidate Caches and Build->Rebuild Project). Can you try
that too?

**Comment by jmar777** [comment]
I don't think I'll be able to reduce this to a small sample app, but I thought I'd voice that we're running into this issue as well.

Per the developer guide, we have added...

```
  compileOptions {
    targetCompatibility JavaVersion.VERSION_1_8
  }
```

...to our gradle configs. We're on v2.9.6.
