### ISSUE TITLE
Subtitles not showed

### ISSUE THREAD

**Issue by gerardiandrea** [google/ExoPlayer#5603]
Hi,

I'm trying to reproduce content with subtitle but I have some problems with AndroidTV.

I have two srt file, one has content-type "application/octet-stream" and works fine but the other file has content-type "text/plain; charset=UTF-8" and the tv not shows the subtitle but it works fine with smartphone.

Do you know if the indicated content-type can be the problem?

### [REQUIRED] Version of ExoPlayer being used
I used ExoPlayer 2.9.3

Thanks!

**Comment by ojw28** [comment]
As indicated by the @google-oss-bot, this issue does not follow our template and omits nearly all of the information we need, like concrete reproduction steps. Please fill out the issue template completely, and provide a concrete way for us to reproduce the problem.
