### ISSUE TITLE
Sbox8G40C Android 4.4.2 stability issues

### ISSUE THREAD

**Issue by zhouxuemeng1988** [google/ExoPlayer#5606]
**Issue description**
SIGSEGV(SEGV_MAPERR): When play youtube DASH with exoplayer2.9.5 for a long time

 **Reproduction steps**
It is not a bug that must be present, but playing dash for a long time will happen frequently.

**Link to test content**
[https://testweex.oss-cn-hangzhou.aliyuncs.com/test/youtube_6dc36dede15753cb18474ff496351c5b.mpd.txt](https://testweex.oss-cn-hangzhou.aliyuncs.com/test/youtube_6dc36dede15753cb18474ff496351c5b.mpd.txt)

**A full bug report captured from the device**
Sbox8G40C Android 4.4.2,level 19
ROM：HiSTBAndroidV5/Hi3798MV100
CPU：armeabi-v7a
crash process: com.gochinatv.ad#Loader:ChunkSam(934)

 **Version of ExoPlayer being used**
2.9.5

[crash.log](https://github.com/google/ExoPlayer/files/2939262/crash.log)

**Comment by zhouxuemeng1988** [comment]
I user exoplayer demo 2.9.6, and set playmode to Player.REPEAT_MODE_ALL,then i click YouTube Dash-->Google Glass (MP4,H264) ,then it play failed. Code and log are as follows.
`player =
                    ExoPlayerFactory.newSimpleInstance(
                            /* context= */ this, renderersFactory, trackSelector, drmSessionManager);
            player.addListener(new PlayerEventListener());
            player.setPlayWhenReady(startAutoPlay);
            player.setRepeatMode(Player.REPEAT_MODE_ALL);
            player.addAnalyticsListener(new EventLogger(trackSelector));
            playerView.setPlayer(player);
            playerView.setPlaybackPreparer(this);
            debugViewHelper = new DebugTextViewHelper(player, debugTextView);
            debugViewHelper.start();
MediaSource[] mediaSources = new MediaSource[uris.length];
            for (int i = 0; i < uris.length; i++) {
                mediaSources[i] = buildMediaSource(uris[i], extensions[i]);
            }
            mediaSource =
                    mediaSources.length == 1 ? mediaSources[0] : new ConcatenatingMediaSource(mediaSources);

boolean haveStartPosition = startWindow != C.INDEX_UNSET;
        if (haveStartPosition) {
            player.seekTo(startWindow, startPosition);
        }
        player.prepare(mediaSource, !haveStartPosition, false);
        updateButtonVisibilities();`

log: 

03-08 10:12:22.189 26497-26834/com.google.android.exoplayer2.demo **A/libc: invalid address or address of corrupt block 0x4b0b24c0 passed to dlfree**
03-08 10:12:22.189 26497-26834/com.google.android.exoplayer2.demo **A/libc: Fatal signal 11 (SIGSEGV) at 0xdeadbaad (code=1), thread 26834 (Loader:ChunkSam)**

[exoplaydemo.log](https://github.com/google/ExoPlayer/files/2944184/exoplaydemo.log)

**Comment by ojw28** [comment]
See also https://github.com/google/ExoPlayer/issues/5609 which affects the same device.

**Comment by ojw28** [comment]
It seems this device has stability issues in the underlying platform. You will most likely need to report these to the device manufacturer.
