### ISSUE TITLE
How to get the current actual bitrate?

### ISSUE THREAD

**Issue by coderain1** [google/ExoPlayer#5607]
I can get the BandwidthEstimate by onBandwidthSample function，but how do I get the current actual bitrate

**Comment by ojw28** [comment]
There are quite a few of things "current actual bitrate" could mean here. Please provide more details about exactly what you mean, and what your use case for needing this functionality is.

**Comment by coderain1** [comment]
I want to show real time Internet speeds when the player plays video; For example, when playing video of HLS type, the result seen from the log printed in Charles and Android studio is that each time a ts file is downloaded, the onBandWidthSample method will be called to inform the caller of the calculated network speed. If the current network speed is slow or each ts file is large, the caller will not be notified of the onBandWidthSample method for a long time.

**Comment by ojw28** [comment]
We only update our bitrate estimate at the end of each chunk request. You can see where this happens in `DefaultBandwidthMeter`, which only updates the estimate in `onTransferEnd`.

We don't support more frequent updates, and nor do we plan to do so. However if you wanted to implement it yourself, you could do so by writing your own `BandwidthMeter` implementation, in which you could update the bitrate estimate in `onBytesTransferred`, which is called frequently as each chunk request progresses. You could then inject an instance of your custom implementation when creating the player.

**Comment by coderain1** [comment]
Thanks for your solution
