### ISSUE TITLE
Audio Focus issue

### ISSUE THREAD

**Issue by ArcherEmiya05** [google/ExoPlayer#5612]
### [REQUIRED] Searched documentation and issues
I already followed what is in this article : https://medium.com/google-exoplayer/easy-audio-focus-with-exoplayer-a2dcbbe4640e

### [REQUIRED] Question
The AudioAttributes works but the problem is when I am playing a audio file using built-in music player then open and start playing a video in my app using Exoplayer the music player stop and never return to play again even when I stop the video in my app.

**Comment by ojw28** [comment]
What you describe is how audio focus is supposed to work at the system level. The music player is not supposed to resume playback automatically when the video in your app stops. 

You should see the same behavior when using other apps as well (e.g. try starting a YouTube video when the music player is playing, and observe music does not resume when the YouTube video is stopped).
