### ISSUE TITLE
only one live dash stream on android P in tunneling mode gets stuck in buffering

### ISSUE THREAD

**Issue by abdul-ali98** [google/ExoPlayer#5618]
All channels work fine on all android versions even if tunneling mode is enabled or disabled. France24 channel works fine on all modes, devices and android versions except "android P && tunneling && france24" if the tunnelling mode disabled, it works fine.
What exactly happens ?
After approximately 2 mins the stream freezes but no errors callbacks are called, no paused or stopped methods called, the app doesn't freeze or crashed. If set the show_buffering="always" it will be shown for infinity. 

I don't know what causes this stranger behaviour as everything "the same code" work fine with all other dash streams on all devices and different android versions.

When the player state is buffering. I can call the method seekTo(0). It makes the player resumes but its insufficient solution specially sometimes the screen turns black for a second before continuing playing  
If there is any recommendation to do, I will really appreciate it

### [REQUIRED] Content description
It is a live dash stream for france 24 channel.

### [REQUIRED] Link to test content
Can't provide a test content for now due to company's privacy. However, I just asking if someone faced this issue before or there is 

### [REQUIRED] Version of ExoPlayer being used
2.9.4

### [REQUIRED] Device(s) and version(s) of Android being used
only android P has the problem
on all stb devices run P
sagemcom
Technicolor

**Comment by andrewlewis** [comment]
Just to confirm, are you saying that video tunneling is working fine, except for when playing one specific stream on an Android P build?

I don't think we've seen such an issue, and without the stream or a bug report (`adb bugreport`) there's not much hope of figuring out what's going. If you don't want to post it here you can alternatively email a link to dev.exoplayer@gmail.com with subject 'Issue #5618'.

**Comment by abdul-ali98** [comment]
Yes exactly, noted that on android O the same stream works fine. The problem on android P ONLY

**Comment by abdul-ali98** [comment]
I have sent the bug report to the mentioned email.

Actually, this issue could be produced on SagemCom and Technicolor stb devices which run android P. 
When the stream in buffering state, after one time or two times its gets stuck in the buffering state.
If I called seekToDefaultPosition() while the stream in the buffering state, its continue after showing the buffering progress bar. this pause not exceed 1 second usually. 
If I called seekTo(0) instead seekToDefaultPosition() , after some while the player's screen turns into black for a second before continuing and so on.

It is supposed that seekTo(0) and seekToDefaultPosition() has the same behaviour since the windowIndex is always 0
Also, I have a stable internet connections and the other live streams never go into buffering state once its started playing. It is only happens with this stream.
Remember : this streams works fine with android N.

**Comment by andrewlewis** [comment]
The only obvious tunneling-related logging in the bug report is:

```
03-13 12:15:12.251  1046  3791  9233 W bomx_buffer_tracker: [OMX.broadcom.video_decoder.tunnel.secure] PTS 1658199848 not in tracker
03-13 12:15:12.251  1046  3791  9233 I bomx_video_decoder: Unable to find tracker entry for pts 0x62d61f28
03-13 12:15:12.252  1046  3791  9233 D bomx_video_decoder: stats decErr:0 decDrop:0 dispDrop:0 dispUnder:0 ptsErr:0
```

I'm not sure what to make of this, but given that this is logged at 'warning' level it may not even indicate an actual issue. Tunneling mode is implemented by the OEM rather than in the framework, so I suggest following up with the chipset manufacturer for the devices where you see the issue (Broadcom?).

Regarding seeking: if this is a live stream then I'd expect `seekToDefaultPosition` to seek to a position based on the live edge, which generally won't be the same as the start of the live window.

**Comment by andrewlewis** [comment]
@abdelrahman-ali98 I don't think there's anything else we can do here so I will close this. Please let us know if you contacted Broadcom and received more information that would help diagnosing this.
