### ISSUE TITLE
How can I create different DRM Sessions for ConcatenatingMediaSource?

### ISSUE THREAD

**Issue by musooff** [google/ExoPlayer#5619]
I have a `ConcatenatingMediaSource` with 3 mediaSources. I have have to create separate `DrmSessionManagers` as drm content requires id of each content for acquiring drmSession.

I suppose as of now ExoPlayer doesn't support such feature (#2394). If I am wrong and its possible to create several DrmSessionMangers how can I do it? If yes, it doesn't support, are you planning to bring such feature?

**Comment by AquilesCanta** [comment]
This is still not supported, but we are currently working on it. I'll use this issue to track progress on this.

**Comment by eneim** [comment]
@AquilesCanta I'm interested in this too, can you give a bit of detail? Like your roadmap to support this?

**Comment by kgrevehagen** [comment]
@AquilesCanta I'm very interested in this as well. Any status update or ETA? Are there workarounds you can think of that we can do in the meantime?

**Comment by AquilesCanta** [comment]
Working on it.

**Comment by AquilesCanta** [comment]
As of [this commit](https://github.com/google/ExoPlayer/commit/6a122f4740ef5da4e23445309a20762da2f95639) (and a bit earlier too), this should be supported. Please give it a try and reach back if you encounter any issue.

Thanks for your patience! I expect DRM changes to be available in 2.11.0.
