### ISSUE TITLE
SLDP extension for ExoPlayer

### ISSUE THREAD

**Issue by WMSPanel** [google/ExoPlayer#5620]
### [REQUIRED] Searched documentation and issues
I've looked at this github repo and at related Medium publications, as well as general Google search.

### [REQUIRED] Question
Our company created a low latency media streaming protocol called  [SLDP](https://softvelum.com/sldp/). It's based on WebSockets and it delivers media with sub-second latency.
It's being used by a big number of customers and we plan opening this technology to wider audience.
Some of our customers who use ExoPlayer for other protocols already, they ask if we could provide an extension for ExoPlayer. This would allow extending their apps' existing playback experience with our protocol.

So the question is: if we create an extension for SLDP, would we be able to add it to ExoPlayer repo? Are there any requirements for this inclusion?

Thank you.

**Comment by AquilesCanta** [comment]
In general we take high-quality contributions that go in line with ExoPlayer's direction. There are [license requirements](https://cla.developers.google.com/clas) that must be met. I am pretty sure we cannot make any decisions without looking at the overall structure of the pull request. Assigning @ojw28 in case I forgot anything important.

**Comment by ojw28** [comment]
What form would such an extension take? Would it just be a `DataSource`, or would it be something larger and more involved? Is there a reason why it would need to be part of the ExoPlayer repo, as opposed to your own GitHub project? 

In general I don't think we want to be responsible for (and hence need to maintain) this kind of thing, unless we see very strong developer demand, which we've not seen for SLDP to date. So I think our preference would be for you to host such an extension yourself. If SLDP were to gain significant traction in the industry then at that point it would make sense to move the extension into the ExoPlayer repo and have us support it officially, if that's something you'd still want to do at that point.

**Comment by WMSPanel** [comment]
Regarding the implementation, this will probably be DataSource implementation, similar to existing RTMP extension. And of course we'll keep supporting SLDP extension once it's taken into the main repo.

Let us get back to this question as soon as we have some source code to discuss.

Thank you!

**Comment by ojw28** [comment]
Closing for now, since all immediate questions have been answered. I still think our preference would be for you to host such an extension yourself, unless we see very strong developer demand.
