### ISSUE TITLE
Prebuffer next MediaSource in dynamic ConcatenatingMediaSource

### ISSUE THREAD

**Issue by nicolausYes** [google/ExoPlayer#5621]
### [REQUIRED] Searched documentation and issues
> You can call any of these methods before and after playback has started, no matter which item is currently playing. Access to these methods is thread-safe. And you can also rest assured that ExoPlayer pre-buffers the next playlist items to ensure gapless playback.

I've found only this general description about prebuffering on Medium, want to get into more details.

### [REQUIRED] Question
I compose a playlist dynamically with ConcatenatingMediaSource and want to ensure that the next MediaSource is prebuffered after it's added with addMediaSource().

For example, there is 1 source in ConcatenatingMediaSource that is currently playing. I add a second one with addMediaSource().

When a player will start to prebuffer it?

- Immediately after adding? 
- Or should I call SimpleExoPlayer.prepare() after adding without reseting position/state?- 
- How about default caching behavior, if the currently playing MediaSource is not buffered to the end at the moment, will the added MediaSource will start buffering after adding?

**Comment by marcbaechinger** [comment]
The player will start buffering as soon as its needed. So when it gets towards the end of the first window (MediaSource), the player notices that there is a second item and starts filling the buffers for this item. 

To answer your questions concretely:

Q1) It does not necessarily start immediately after adding. Given the first item is eg. 5 minutes before the end and you add a second media source, the player will just wait until playback is close to the end and then start loading for the second item.

Q2) You do need to call prepare() only once with the ConcatenatingMediaSource. After you have done this you can add and remove media sources as you wish. No need to call prepare again.

Q3) In this case the player would buffer to the end of the first item first and then continuing to buffer for the second item as soon as it's indicated to do so.

**Comment by nicolausYes** [comment]
@marcbaechinger so prebuffering of the next MediaSource roughly depends on a playback position of a currently playing MediaSource.

Is there a way to force prebuffer of the next MediaSource? 
For example, if the first MediaSource playing somewhere in the middle, I want to have the next MediaSource to be prebuffered if the user decides to play the Next track.

**Comment by marcbaechinger** [comment]
No, that's currently not possible. There is #3327 which is the enhancement tracking bug for this feature. AFAIK we haven't started with this though.

**Comment by nicolausYes** [comment]
#3327 is exactly what I'm talking about. Will follow updates there, thanks. Closed.
