### ISSUE TITLE
Getting HLS livestream in sync across devices 

### ISSUE THREAD

**Issue by sergiupuhalschi** [google/ExoPlayer#5622]
Hi guys,

We are currently using ExoPlayer for one of our applications, which is very similar to the HQ Trivia app, and we use HLS as the streaming protocol.

Due to the nature of the game, we are trying to keep all the viewers of this stream to have the same latency, basically to keep them in sync.

We noticed that with the current backend configuration the latency is somewhere between 6 and 10 seconds. Based on this fact, we assumed that it would be safe to “force” the player to play at a bigger delay (15 seconds, further off the live edge), this way achieving the same (constant) delay across all the devices.

We’re using EXT-X-PROGRAM-DATE-TIME tag to get the server time of the currently playing content and we also have a master clock with the current time (NTP). We’re constantly comparing the 2 clocks to check the current latency. We’re pausing the player until it reaches the desired delay, then we’re resuming the playback.

The problem with this solution is that the latency might get worse (accumulating delay) over time and we don’t have other choice than restarting the playback and redo the steps described above if the delay gets too big (steps over a specified threshold). Before restarting the player we’re also trying to slightly increase the playback speed until it reaches the specified delay.

The exoPlayer instance is setup with a DefaultLoadControl, DefaultRenderersFactory, DefaultTrackSelector and the media source uses a DefaultDataSourceFactory.

The server-side configuration is as follows:
cupertinoChunkDurationTarget: 2000 (default: 10000)
cupertinoMaxChunkCount: 31 (default: 10)
cupertinoPlaylistChunkCount: 15 (default: 3)

My first question would be if this is even achievable with a protocol like HLS? Why is the player drifting away accumulating more and more delay?
Is there a better setup for the exoPlayer instance considering our specific use case?
Is there a better way to achieve a constant playback delay across all the playing devices? How important are the parameters on the server side in trying to achieve such a behaviour?

I would really appreciate any kind of help because I have reached a dead-end. :)

Thanks,
Sergiu

**Comment by tonihei** [comment]
The playback clock is mostly determined by the position of the audio track and not the real time on the device. Ideally, these two are in sync, but I think there may be a slight drift over time. @andrewlewis may be able to comment further if that is a potential issue. There may also be issues with buffering, where one player needs to buffer longer than another one before playback can be started or restarted, introducing some delay. 

In general, adjusting playback speed to control the synchronization sounds like a good idea and should probably even out all differences without requiring to pause the playback.

Also, I think the server configuration is probably irrelevant for the player timing.

**Comment by sergiupuhalschi** [comment]
@tonihei  What do you mean the playback clock is mostly determined by the position of the audio track? Also, do you know if the player takes into consideration the EXT-X-PROGRAM-DATE-TIME and makes some default playback adjustments based on it?

You're right about the playback speed adjusting to control the synchronization, I didn't specify it, but already have it implemented, so that we pause the player only when the difference between players is too big.

Thanks for your reply.

**Comment by tonihei** [comment]
> What do you mean the playback clock is mostly determined by the position of the audio track? 

The player needs to ensure audio and video play in sync to each other. Video frames can be shown at any point in time because are basically independent pictures, whereas audio samples need to be played in a timed continuous fashion to make them audible in the right way. That's way ExoPlayer lets the system audio track play the audio samples and adjusts the timing of the video frames to the reported timestamps of the currently playing audio. 

> do you know if the player takes into consideration the EXT-X-PROGRAM-DATE-TIME and makes some default playback adjustments based on it

I think we only use these tags to set up the media with the right timestamps relative to each other and also to correctly define a live window (if applicable), but these tags are not used to influence the actual playback.

**Comment by tonihei** [comment]
Closing the issue for issue for now because we received no further follow-up question.
