### ISSUE TITLE
Player show empty white screen when try to run live video on real device

### ISSUE THREAD

**Issue by amiraelsayed** [google/ExoPlayer#5623]
Hello

I am facing a real problem, after I finish the development of TV android app and test it on emulator, when install the app on real device, all video files is working but all live video show white screen and none of the video or the audio running

I am using the same code in the demo that provide in github

this is the link of the code : https://github.com/google/ExoPlayer/tree/release-v2/demos/main/src/main/java/com/google/android/exoplayer2/demo

can you please advice as soon as you can ?

**Comment by AquilesCanta** [comment]
I'd suggest you try to check media is supported in the demo app itself, without modifications. If any of the streams don't work and you don't know the cause, then you can file an issue including [all information required in the issue template](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/content_not_playing.md). Please don't skip any items. If media plays correctly in the demo app, then maybe you are missing something in your app, but we cannot help you with that.
