### ISSUE TITLE
HLS Playback issues on x86 devices

### ISSUE THREAD

**Issue by Appostrophe** [google/ExoPlayer#563]
I have replaced the HLS stream of the demo app the m3u8
#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=561000,RESOLUTION=512x288,CODECS="avc1.66.30, mp4a.40.2"
https://toutvuniver1-vh.akamaihd.net/i/012/mp4/p/2015-05-12_21_00_00_penelope_0358_,500,800,1200,.mp4.csmil/index_0_av.m3u8?null=&id=AgCfIUDYuDLuBREog1VSxcSBtuQGLapxXS9PkheLUTBiDXhUtt0focMzxYdNiG1N4CxQlQjxNcqKZA%3d%3d
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=925000,RESOLUTION=640x360,CODECS="avc1.66.30, mp4a.40.2"
https://toutvuniver1-vh.akamaihd.net/i/012/mp4/p/2015-05-12_21_00_00_penelope_0358_,500,800,1200,.mp4.csmil/index_1_av.m3u8?null=&id=AgCfIUDYuDLuBREog1VSxcSBtuQGLapxXS9PkheLUTBiDXhUtt0focMzxYdNiG1N4CxQlQjxNcqKZA%3d%3d
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1325000,RESOLUTION=852x480,CODECS="avc1.77.30, mp4a.40.2"
https://toutvuniver1-vh.akamaihd.net/i/012/mp4/p/2015-05-12_21_00_00_penelope_0358_,500,800,1200,.mp4.csmil/index_2_av.m3u8?null=&id=AgCfIUDYuDLuBREog1VSxcSBtuQGLapxXS9PkheLUTBiDXhUtt0focMzxYdNiG1N4CxQlQjxNcqKZA%3d%3d

I intermittently get the following error when I start the video
    06-18 16:10:00.699  12295-12295/com.google.android.exoplayer.demo E/EventLogger﹕ internalError [14.04, rendererInitError]
    06-18 16:10:00.719  12295-12295/com.google.android.exoplayer.demo E/EventLogger﹕ playerFailed [14.06]

Do you know what might cause this error and how can I troubleshoot it?

**Comment by gongshoudao** [comment]
Exoplayer do not support x86,Because there is no Tracker in System SDK on x86 devices.You can use jni like this implemention : [https://github.com/google/ExoPlayer/tree/master/extensions/vp9]

**Comment by ojw28** [comment]
I don't really understand the comment above. What does "tracker in system sdk" mean? ExoPlayer supports all Android devices, regardless of their architecture.

That said, there is insufficient information provided here to help debug the issue. The issue template provides a list of the information that you need to provide for us to follow up on the report. Please file a new issue with complete information if this is still a problem for you. Thanks!
