### ISSUE TITLE
IMA - time between two ads

### ISSUE THREAD

**Issue by ThomasCZ** [google/ExoPlayer#5631]
Ads server are providing VASTs for ad breaks. I am merging many VASTs into one VMAP and using it as response (_buildForAdsResponse_). When I jump to position behind the first ad break, ad is played. Immediately after the first ad is completed, I will jump to position behind the second ad break and the second ad is played. How can I specify a minimum time between two ads to be played? It means, I do not want to play two ads more often than, lets say, five minutes. Thanks!

**Comment by andrewlewis** [comment]
This is not currently supported with ImaAdsLoader I'm afraid.

In case you want to experiment/investigate further: you could try calling AdsManager.discardAdBreak right after an ad break loads if you've played an ad more recently than a certain threshold. The IMA extension uses preloading, and the behavior of this API may not be well defined when preloading is enabled, but I think it's worth a try if you are keen to get this behavior. I'm afraid we can't provide more detailed guidance here. If you do try it it would be good if you could post your findings here.
