### ISSUE TITLE
Ad Pod- player freezing after first Ad

### ISSUE THREAD

**Issue by irttri** [google/ExoPlayer#5632]
Hi,
  I have a requirement to call ad when specific timed metadata comes during a live stream. I tried to use  the following code for ad request at a specific time.My ad tag is an ad pod containing 3 ads when ad get loaded only the first get played ( that too only its sound) then player goes to freeze state and never comes back. Can any one please direct me what  I am missing here.

        adsLoader=imaAdsLoader.getAdsLoader();

        request = sdkFactory.createAdsRequest();
        request.setAdTagUrl("https://pubads.g.doubleclick.net/gampad/ads?slotname=/124319096/external/ad_rule_samples&sz=640x480&ciu_szs=300x250&unviewed_position_start=1&output=xml_vast3&impl=s&env=vp&gdfp_req=1&ad_rule=0&cue=15000&vad_type=linear&vpos=midroll&pod=2&mridx=1&pmnd=0&pmxd=31000&pmad=-1&vrid=6616&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpostoptimizedpod&url=https://developers.google.com/interactive-media-ads/docs/sdks/html5/tags&video_doc_id=short_onecue&cmsid=496&kfa=0&tfcd=0");
        request.setAdDisplayContainer(adDisplayContainer);
        request.setContentProgressProvider(new ContentProgressProvider() {
            @Override
            public VideoProgressUpdate getContentProgress() {
                if (player == null || player.getDuration() <= 0) {
                    return VideoProgressUpdate.VIDEO_TIME_NOT_READY;
                }
                return new VideoProgressUpdate(player.getCurrentPosition(),
                        player.getDuration());
            }
        });
        adsLoaderOld.requestAds(request);

**Comment by AquilesCanta** [comment]
Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md).

**Comment by tonihei** [comment]
Closing as no further information has been provided.
