### ISSUE TITLE
No Playback on Samsung Galaxy S9/9+ as of Feb Update

### ISSUE THREAD

**Issue by adjustnox** [google/ExoPlayer#5634]
Before filing a content issue:
------------------------------
- Search existing issues, including issues that are closed.
- Consult our supported formats page, which can be found at
  https://google.github.io/ExoPlayer/supported-formats.html.
- Try playing your content in the ExoPlayer demo app. Information about the
  ExoPlayer demo app can be found here:
  http://google.github.io/ExoPlayer/demo-application.html.

When reporting a content issue:
-----------------------------
Fill out the sections below, leaving the headers but replacing the content. If
you're unable to provide certain information, please explain why in the relevant
section. We may close issues if they do not include sufficient information.

### [REQUIRED] Content description
This is an HLS stream. We're providing 2 assets, with and without subtitles.

### [REQUIRED] Link to test content
I will be emailing this for client confidentiality.

### [REQUIRED] Version of ExoPlayer being used
Sorry to do this, but my guess is this is r1.5.16. We only have the jar file. It was last modified on May 7, 2017, which I am guessing is when they converted it.

### [REQUIRED] Device(s) and version(s) of Android being used
Customers with the Samsung Galaxy S9/S9+ are reporting there was an update (information on update below) that has since caused video to not show up within the app, clients state that there is just a large white space where the video/image should be and do not have an option to play video.

Update details:
Android 9 Pie
Release date: 02/25/2019
Android Security Patch Level: February 1, 2019
Software Version: PPR1.180610.011.G960USQS3CSAG

**Comment by AquilesCanta** [comment]
Have you sent the e-mail with the content and bugreport?

**Comment by adjustnox** [comment]
Yes. I sent the email to **dev.exoplayer@gmail.com**, subject is **Issue #5634**

**Comment by AquilesCanta** [comment]
The e-mail doesn't contain a bugreport.

I can play the streams correctly on a Pixel XL running Pie, using DefaultHttpDataSource. With the given information there is nothing else I can do to help. Things that may be worth doing:

+ Contacting the device manufacturer.
+ Updating the ExoPlayer version and reaching back to us with all the information required by the issue template. Please don't skip the bugreport.
