### ISSUE TITLE
Playing ads without content

### ISSUE THREAD

**Issue by bryandunbar42** [google/ExoPlayer#5635]
Is it possible to use AdsMediaSource without a ContentMediaSource?

**Comment by andrewlewis** [comment]
Please see #3774.

**Comment by bryandunbar42** [comment]
Thanks for the response,  but i don’t think AdMob is a viable solution if you want to use vast tags (as far as I know). The real use case here is inserting ads into a playlist. Since that is not currently implemented it would be nice to simply prefetch an ad with ImaAdsLoader then switch source to play simply the add, then switch source back to the playlist. There would be some buffering but it’s the cleanest workaround i can think of. 

I guess I could also implement a “dummymediasource” or attach the ad to a 1 second black video

**Comment by andrewlewis** [comment]
I see. If you follow along #3750 that should be updated when we get round to supporting concatenation of ImaAdsLoaders (hopefully soon!).

**Comment by bryandunbar42** [comment]
Yep. I’m following that one. I’ll need to try a workaround for now. I’m going to try writing a dummy media source first. I’ll report back if it works out.
