### ISSUE TITLE
PlayerControlView updatePlayPauseButton not in ui thread(crash)

### ISSUE THREAD

**Issue by shoyu666** [google/ExoPlayer#5644]
```java
version:
com.google.android.exoplayer:exoplayer:2.9.6
```
```java
device:xiaomi max,huawei ...
more than 5 device
```

```java
simpleExoPlayer.setAudioAttributes(audioAttributes,true)
let exo handle audiofocus
```
```java
when audio lost focus
expected:  not crash
observed:  crash  ( Only the original thread that created a view hierarchy can touch its views.)
```
```java
info
AudioFocusListener  call back in LocalIOWorker thread ,it change view in LocalIOWorker thread direct
```

**Comment by tonihei** [comment]
This is still omitting quite a lot from the issue template.

Besides that, it sounds as if you are calling setAudioAttributes on the wrong thread. Please check if can see "Player is accessed on the wrong thread." warnings in the logcat to know where these calls are coming from.

**Comment by shoyu666** [comment]
```java
thanks for you reply
it seem: we have multi exoplayer instance in project
other people init exoplayer in 'LocalIOWorker ' thread without bind any view,
and my exoplayer init in main thread bind a controll view
when Focus occur,my exoplayer will callback in 'LocalIOWorker  ' not in main thread。
i will Keep on understanding    thanks very much

```

**Comment by nitinglobal** [comment]
I am also facing the same issue , I have implemented the audio focus for audio and integrated the audioattributes for video in version 2.9.6 when i play audio and try to play video then same crash i get. May i know how i can fix this issue,i am creating and executing all commands of exoplayer on single application thread only.
