### ISSUE TITLE
need help with stream from .json file, advertising and cast to chromecast

### ISSUE THREAD

**Issue by MehmanDadashov** [google/ExoPlayer#5648]
Hello, I need help in developing an application. 
3 in 1 to get all 3 demos in one Demo/IMA/Cast in one app.
I want to build an application that Streams are broadcast from a .json playlist, as in the ExoPlayer demo, and support ads like admob / IMA, and want that application will be able to cast to chromecast. 
Please help me with my problem and show examples if they exist some.
I tried to build ExoPlayer from the demo, but I failed.

**Comment by tonihei** [comment]
Unfortunately, we can't help you build your own app and this issue tracker is for specific bugs and questions around ExoPlayer only. 

We already have the demo apps you mentioned with all the functionality and if you need help for particular issues which fall into generic Android development, please use platforms such as StackOverflow or similar to get help from others.
