### ISSUE TITLE
Connection Pooling and Reuse + Parallel Chunk Loading

### ISSUE THREAD

**Issue by Arqu** [google/ExoPlayer#565]
I've done some testing and it seems like the player doesn't utilise connection reuse and pooling and loads all segments sequentially instead of attempting to do multiple parallel requests. Am I missing something or has this not been implemented yet. This would increase playback quality dramatically in my opinion.

**Comment by ojw28** [comment]
The underlying network stack should be re-using the open sockets unless you or the server are explicitly doing something to prevent this. What layer are you looking at when you're testing this? You need to be using something like wireshark to see what's actually going on at the network level.

**Comment by Arqu** [comment]
I went and re-checked my claims, if the streaming is done via HTTP connections are reused nicely, via HTTPS it opens a few more than via HTTP but nothing insane, works just fine too regarding connection reuse (tested both DefaultHttpDataSource and somebodies OkHttpDataSource). However it still does requests only sequentially and never in parallel, id rather have 3 connections open and have them pull in parallel to preload more chunks in time than 1 sequential "fast" one. This is mostly an issue when you have lots of rather short chunks.

**Comment by ojw28** [comment]
We considered parallel chunk fetching and ultimately concluded that we're better off with the sequential approach.

Sequential fetching has the obvious benefit of always requesting bytes in the exact order in which they're required. With parallel fetching this is not true, and so it's possible that fetching bytes that are required further into the future will introduce additional startup latency and/or re-buffering events by impeding transfer of bytes that you need more urgently. Sequential fetching is also simpler to manage from an implementation and correctness point of view. Implementing responsive adaptive bit-rate logic is also more straightforward with a sequential approach.

Parallel fetching is beneficial primarily when (a) round trip time is large (so the overhead in starting each request is large, even with socket re-use) (b) chunks are short (meaning the overhead is incurred often) and (c) throughput is still good enough for streaming. In practice it's doubtful how often (a) and (c) would both be true at once. Media providers should be making chunks a sensible size, also.

**Comment by Arqu** [comment]
True, however, I think that a good approach would be probably the best of both worlds or at least make it configurable to accommodate to more network and stream variations. Using 2 or 3 requests to prefetch the next chunk and the one after would be manageable but also provide better robustness. I do understand that it could undermine switching, but considering that switching is done when the buffer exceeds a given amount, this would only signal the variant switch earlier, at least thats how I understand it currently. Also this would provide middle ground between on demand loading and preloading the entire content for stable playback in "weird" network  and stream conditions.

**Comment by ojw28** [comment]
If you define robustness to mean that the playback doesn't fail, then it's always possible to be equally robust using either approach (in the extreme case you can design the player to retry indefinitely in both cases, and hence achieve 0% failures). If you define robustness to mean the playback not re-buffering, then it can be debated which is better or worse.

As above, we believe that parallel loading is better only under network conditions that occur rarely in practice. Or at least, we believe that sequential loading will perform better in the majority of cases. We have no plans to support parallel loading. Doing so would significantly increase complexity throughout a large part of the code-base for marginal gain.

**Comment by Arqu** [comment]
I agree, it would add a lot of unnecessary complexity and I also agree that it is arguable which scenario plays out better overall. However I would like to have the possibility to at least use the loader to immediately load the next chunk instead of waiting till the "end" of the last one.

**Comment by ojw28** [comment]
I'm unclear as to what that means that's different to parallel loading (and how it would avoid the unnecessary complexity where-as parallel loading would not)?

**Comment by Arqu** [comment]
Well currently the loader waits thill almost the end of the current chunk before it loads the next one, while I would like to just keep buffering for more chunks without waiting too much or at least reduce the waiting.

**Comment by ojw28** [comment]
So, loading in parallel basically?

**Comment by Arqu** [comment]
No, sequentially but without waiting before requesting the next chunk.
Currently its like [Chunk][wait till we use up most of the chunk][Request new chunk] and I would prefer
[Req. Chunk][Req. Chunk][Req. Chunk]...

**Comment by ojw28** [comment]
Ah. We already implement the behavior that you describe. We don't wait until we're consuming a chunk before we request the next one. That would imply that the buffer never grows to more than about 5 seconds, which I agree would be terrible.

**Comment by Arqu** [comment]
Hmmmm, I still have those "in between" periods. Here is the IO graph for the Vevo HLS stream:
![iodump](https://cloud.githubusercontent.com/assets/1760977/8260639/484a83cc-16c5-11e5-94f9-17c61fbf37a7.png)
Notice the drop at 20 seconds, and the subsequent jumps, this happens every time regardless of network conditions (I've tested multiple times on multiple networks in the last couple days) and it becomes more pronounced the shorter the chunks are. This graph is for fairly normal sized chunks of around 6 seconds. On 5+ second segments it is not a real issue and works, but when you shorten the chunks or have lower throughput it starts making issues. Any idea why it might be happening? I'd love to see a bit more performance/utilisation of the network.

**Comment by ojw28** [comment]
- Once the buffer is full we'll utilize the network at a lower rate, because at that point we can only fetch media at approximately the same rate as it's being consumed. So you're probably seeing a utilization drop simply because the buffer is as full as it can be (which is a good thing!).
- Once the buffer becomes full, we do implement some fill/drain logic that allows the buffer to drain out for a while before it starts re-filling. We start start re-filling again well before it's nearly empty though. I believe there are some battery and mobile-carrier-network related reasons for doing this.
- Both the buffer size and fill/drain logic can be controlled when creating the player. Buffer size can be controlled by changing the buffer contribution values passed to HlsSampleSource. The fill/drain logic can be controlled by using a different constructor when instantiating the DefaultLoadControl, which allows passing of additional control parameters. You can also replace DefaultLoadControl with your own implementation.
- To allow maximal usage of network until the entire stream is downloaded would require us to extend the buffer from memory into flash storage. We've opted not to do this for the time-being. It's definitely not always ideal behaviour. If you're operating at scale then there are negative cost and network load implications of doing this. Flash storage is also a tricky area in general to get right (e.g. not using too much of it, handling read/write failures etc).

**Comment by Arqu** [comment]
Thanks for the elaborate answer, clarifies a lot of things, however for the last chart I had a buffer size of 4096 set in my renderer builder at 64 segments. Also the drop after 20 seconds is not because the buffer is necessarily full but because I've increased the minBuffer to 20000 when creating a new instance of the player and if I reduced, it just starts jumping sooner. Also I've noted that it buffers more by "content time" than by size, tell me if I'm wrong, and on some streams where the PTS are not really the best it seems to miscalculate the required buffer size. In any case I will keep looking at this a bit longer and report if/what I find, care to keep this one open a couple of days more?

Also regarding the battery reason, true, you put the network in kind of a sleep mode to save battery.

**Comment by ojw28** [comment]
DefaultLoadControl uses a combination of buffered media duration and size to determine when it considers the buffer full. You can control the parameters for each dimension when you create the DefaultLoadControl, by using the constructor that takes the most arguments.
