### ISSUE TITLE
Question: How to use setConstantBitrateSeekingEnabled on v2.9.5 ?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [google/ExoPlayer#5651]
### [REQUIRED] Searched documentation and issues
I've found these, but they look like they are used for older API which isn't used anymore:

- https://github.com/google/ExoPlayer/issues/4797
- https://github.com/google/ExoPlayer/issues/2650
- http://google.github.io/ExoPlayer/supported-formats.html
- https://github.com/google/ExoPlayer/issues/2197

### [REQUIRED] Question
I'm using v2.9.5 :

    implementation 'com.google.android.exoplayer:exoplayer-core:2.9.5'
    implementation 'com.google.android.exoplayer:exoplayer-ui:2.9.5'

And I want to be able to seek the player using `seekTo` function. However, it seems that for some file formats (AMR for example), I need to use `setConstantBitrateSeekingEnabled`  function, but I can't find out how to call it.

Here are the various functions I use to prepare the player to play  :

```
fun SimpleExoPlayer.prepareToPlayVideoFromAssets(context: Context, assetFilePath: String) {
    when {
        assetFilePath.startsWith("/android_asset/") or assetFilePath.startsWith("asset:///") -> prepareToPlayVideoFromUrl(context, assetFilePath)
        assetFilePath.startsWith("/") -> prepareToPlayVideoFromUrl(context, "/android_asset$assetFilePath")
        else -> prepareToPlayVideoFromUrl(context, "/android_asset/$assetFilePath")
    }
}

fun SimpleExoPlayer.prepareToPlayVideoFromRawResource(context: Context, @RawRes rawVideoRes: Int, loopIterationCount: Int = Integer.MAX_VALUE) {
    val dataSpec = DataSpec(RawResourceDataSource.buildRawResourceUri(rawVideoRes))
    val rawResourceDataSource = RawResourceDataSource(context)
    rawResourceDataSource.open(dataSpec)
    val factory: DataSource.Factory = DataSource.Factory { rawResourceDataSource }
    prepare(LoopingMediaSource(ExtractorMediaSource.Factory(factory).createMediaSource(rawResourceDataSource.uri), if (loopIterationCount <= 0) Integer.MAX_VALUE else loopIterationCount), false, true)
}

fun SimpleExoPlayer.prepareToPlayVideoFromUrl(context: Context, url: String, cache: Cache? = null) = prepareToPlayVideoFromUri(context, Uri.parse(url), cache)

fun SimpleExoPlayer.prepareToPlayVideoFromFile(context: Context, file: File) = prepareToPlayVideoFromUri(context, Uri.fromFile(file))

fun SimpleExoPlayer.prepareToPlayVideoFromUri(context: Context, uri: Uri, cache: Cache? = null) {
    val factory = if (cache != null)
        CacheDataSourceFactory(cache, DefaultHttpDataSourceFactory(ExoPlayerEx.getUserAgent(context)))
    else
        DefaultDataSourceFactory(context, ExoPlayerEx.getUserAgent(context))
    val mediaSource = ExtractorMediaSource.Factory(factory).createMediaSource(uri)
    prepare(mediaSource, false, true)
}

object ExoPlayerEx {
    @JvmStatic
    fun getUserAgent(context: Context): String {
        val packageManager = context.packageManager
        val info = packageManager.getPackageInfo(context.packageName, 0)
        val appName = info.applicationInfo.loadLabel(packageManager).toString()
        return Util.getUserAgent(context, appName)
    }

    @JvmStatic
    fun convertPlaybackStateToString(playbackState: Int?): String {
        return when (playbackState) {
            Player.STATE_IDLE -> "STATE_IDLE"
            Player.STATE_BUFFERING -> "STATE_BUFFERING"
            Player.STATE_READY -> "STATE_READY"
            Player.STATE_ENDED -> "STATE_ENDED"
            else -> "unknown"
        }
    }
}

```

Example sample code (without the seeking and without using amr file) available [here](https://github.com/AndroidDeveloperLB/ExoPlayerCacheSample).

Can anyone please help me? Where do I add this?

**Comment by tonihei** [comment]
As documented on the guide page you linked above, this feature can be enabled by calling `DefaultExtractorsFactory.setConstantBitrateSeekingEnabled(true)` and then using this `DefaultExtractorsFactory` in `ExtractorMediaSourc.Factory.setExtractorsFactory(...)`.

**Comment by AndroidDeveloperLB** [comment]
@tonihei I don't see it available in any of the classes I've used.
Where exactly can I enable it for all of those?
I don't even use this class. Should I use it here somehow? Or is there an alternative that fits in what I used?

**Comment by tonihei** [comment]
My comment above already describes which classes you need to use. Please give it a try first!

**Comment by AndroidDeveloperLB** [comment]
@tonihei It was confusing as you wrote it as if it's a static function, or something that I can't use.

I think you mean like this:


```
fun SimpleExoPlayer.prepareToPlayVideoFromRawResource(context: Context, @RawRes rawVideoRes: Int, loopIterationCount: Int = Integer.MAX_VALUE) {
    val dataSpec = DataSpec(RawResourceDataSource.buildRawResourceUri(rawVideoRes))
    val rawResourceDataSource = RawResourceDataSource(context)
    rawResourceDataSource.open(dataSpec)
    val factory: DataSource.Factory = DataSource.Factory { rawResourceDataSource }
    prepare(LoopingMediaSource(ExtractorMediaSource.Factory(factory)
            .setExtractorsFactory(DefaultExtractorsFactory().setConstantBitrateSeekingEnabled(true))
            .createMediaSource(rawResourceDataSource.uri), if (loopIterationCount <= 0) Integer.MAX_VALUE else loopIterationCount), false, true)
}

fun SimpleExoPlayer.prepareToPlayVideoFromUri(context: Context, uri: Uri, cache: Cache? = null) {
    val factory = if (cache != null)
        CacheDataSourceFactory(cache, DefaultHttpDataSourceFactory(ExoPlayerEx.getUserAgent(context)))
    else
        DefaultDataSourceFactory(context, ExoPlayerEx.getUserAgent(context))
    val mediaSource = ExtractorMediaSource.Factory(factory)
            .setExtractorsFactory(DefaultExtractorsFactory().setConstantBitrateSeekingEnabled(true)).createMediaSource(uri)
    prepare(mediaSource, false, true)
}
```

I think it works. Is that the correct way? 

Why isn't seeking enabled by default for all supported formats? Is there any disadvantage of using what was added now?

I just use some file format for recording and playback of this recording.
Maybe I should use `OutputFormat.MPEG_4&AudioEncoder.AAC` instead ? Is it better ? Which is more common/supported/popular ? 

Does "AMR" include both `OutputFormat.THREE_GPP&AudioEncoder.AMR_NB` and `OutputFormat.AMR_NB&AudioEncoder.AMR_NB` on the table? Both work the same?

**Comment by tonihei** [comment]
Yes, that's the correct way of using it. I assumed you'd be able to interpret my pseudo code given your familiarity with the ExoPlayer code base :)

The disadvantage is that seeking in that way is not accurate because the media doesn't say exactly where we need to seek to. And if you have a choice, you should always prefer a format which allows accurate seeking by default (e.g. aac/mp4, or mp3 with xing headers).

**Comment by tonihei** [comment]
Closing because the question has been answered and we can't provide detailed advice on the encoding part for your media anyway.

**Comment by AndroidDeveloperLB** [comment]
So aac is better for this anyway...
Thank you guys. 
I wish you could make multiple tiny samples of various use cases. Could be nice to have instead of one huge project.

About the formats, I meant that the table has only "AMR", but I don't get if it includes both types I've mentioned.
