### ISSUE TITLE
VTT caption file download

### ISSUE THREAD

**Issue by andresdiez** [google/ExoPlayer#5652]
### [REQUIRED] Searched documentation and issues
I been looking every where but not success finding appropriated solution

### [REQUIRED] Question
exoplayer r2.4.  In a hls stream with multiple vtt captions files why exoplayer loads the same file after seek back to the beginning of the stream. ie content start playback from 0 position and plays for 3 minutes and 3 .vtt files download for that period, then a user interaction set the content back to 0 and content resume and plays for the same 3 minutes and download the same files again. Is there a way to make exoplayer cache the already  downloaded vtt files?

**Comment by tonihei** [comment]
That's possible using a `new CacheDataSourceFactory(new SimpleCache(fileDir, evictor), normalDataSource)` as the data source factory for your `MediaSource`. Please also have a look at similar questions on this issue tracker and other websites.

**Comment by andresdiez** [comment]
That work, thank you.
