### ISSUE TITLE
SimpleExoPlayer.prepare(com.google.android.exoplayer2.source.MediaSource)' on a null object reference

### ISSUE THREAD

**Issue by huang122124** [google/ExoPlayer#5655]
### [REQUIRED] Searched documentation and issues
null

### [REQUIRED] Question
when I init the  SimpleExoPlayer player.the method SimpleExoPlayer.prepare()  will  return a null 
object reference.My uri has no problem,Whyyyyyyyy?

private void initPlayer() {
        if (player!=null) {
            player = ExoPlayerFactory.newSimpleInstance(
                    getActivity(), new DefaultRenderersFactory(getActivity()), new DefaultTrackSelector(), new DefaultLoadControl());
            playerView.setPlayer(player);
            player.setPlayWhenReady(playWhenReady);
            player.seekTo(currentWindow, playbackPosition);
        }
        //创建wav文件
        Uri uri=Uri.parse(Environment.getExternalStorageDirectory()+"/msc/test.wav");
        DefaultDataSourceFactory dataSourceFactory = new DefaultDataSourceFactory(getActivity(), Util.getUserAgent(getContext(),"MyApplication"));
        MediaSource mediaSource=new ExtractorMediaSource.Factory(
                dataSourceFactory).createMediaSource(uri);
        if (mediaSource!=null) {
            player.prepare(mediaSource, false, true);
        }else {
            showTip("mediaSource   null");
        }

    }

**Comment by huang122124** [comment]
My ExoPlayer version is 2.9.3   Android 8.0    XiaoMi PAD 4

**Comment by tonihei** [comment]
You should probably check for `player==null` on the second line in your snippet. 

But please be advised that we do not intent to give generic programming advice. Closing this issue for this reason.

**Comment by huang122124** [comment]
Thank you
