### ISSUE TITLE
Multiple CC tracks support in DASH

### ISSUE THREAD

**Issue by michal-dcc** [google/ExoPlayer#5656]
### [REQUIRED] Use case description
We want to be able to select any CC track defined in Accessibility tag.
See dash manifest: https://vm2.dashif.org/dash/vod/testpic_2s/cea608.mpd

We can only check if any CC track is present in the stream. ExoPlayer uses only the first one language track from "value" attribute of the tag which defines CC tracks (parseCea608AccessibilityChannel function).

The value attribute from CC accessibility tag can be retrieved from DASH manifest object that comes in onTimelineChanged event. However, there is no possibility to choose other track than the one that ExoPlayer has chosen.

### Proposed solution
(none)

### Alternatives considered
n/a

**Comment by tonihei** [comment]
@ojw28  Can you comment on how this is supposed to work and if and what we should do for such a manifest?

**Comment by kfrydel** [comment]
Hi all,
http://reference.dashif.org/dash.js/v2.6.7/samples/dash-if-reference-player/index.html shows that both CC languages can be selected for the manifest: eng and swe and they are displayed fine.

**Comment by ojw28** [comment]
We would need to add support for this in `DashMediaPeriod`.

In particular `identifyEmbeddedTracks` will need to use more than just a boolean to indicate whether a track has an embedded 608 track. `buildPrimaryAndEmbeddedTrackGroupInfos` will then need to build tracks for each of the embedded tracks, setting the format's `accessibilityChannel` to the correct value in each case. (e.g. 1 and 3 in this example).

**Comment by ojw28** [comment]
This is supported in the `dev-v2` branch (it'll be in the 2.10 release).
