### ISSUE TITLE
Quick H.265 Clarification

### ISSUE THREAD

**Issue by TroyStopera** [google/ExoPlayer#5659]
### [REQUIRED] Searched documentation and issues
I have searched the ExoPlayer docs as well as past issues. I may have found the answer I'm looking for, but I'd like clarification.

### [REQUIRED] Question
The official docs [list the numerous different container formats](https://google.github.io/ExoPlayer/supported-formats.html) supported by ExoPlayer. They also reference back to Android's [supported formats and codecs](https://developer.android.com/guide/topics/media/media-formats#video-formats). In the Android docs, it only guarantees H.265 support for `.mp4` containers. I believe that, since ExoPlayer uses the Android codec for the _sample formats_, ExoPlayer is not constrained to `.mp4` alone. Is it true that, on Android 5.0+, ExoPlayer can play any H.265 videos that are in an ExoPlayer-supported container? If so, it may be helpful to explicitly state that in the ExoPlayer docs. 

Thanks!

**Comment by tonihei** [comment]
That's correct, as long as the container format is supported and the device supports decoding of H.265 samples, ExoPlayer can play the stream.

The [ExoPlayer docs](https://google.github.io/ExoPlayer/supported-formats.html) also clearly divide between container and sample formats already. I think the linked [platform sample format support page ](https://developer.android.com/guide/topics/media/media-formats#video-formats) refers to the platform MediaPlayer support. With regards to ExoPlayer, only the sample formats are relevant on this page. And the link to this page also says " Sample formats supported by Android devices are documented here." How would you propose to improve that documentation?

**Comment by ojw28** [comment]
I think the real confusion here is that the Android's [supported formats and codecs](https://developer.android.com/guide/topics/media/media-formats#video-formats) documentation doesn't split out sample and container formats. Given Android provides low level codec access via `MediaCodec`, for which the container is irrelevant, the documentation should do this. I'll file a bug asking that they improve this page, and close this issue.

**Comment by ojw28** [comment]
[Internal ref: 130046184]
