### ISSUE TITLE
How to set media stream full screen, play hls with exoplayer.

### ISSUE THREAD

**Issue by kinhdang** [google/ExoPlayer#566]
Hi all !

How to set media stream full screen, play hls with exoplayer.

Thanks.

**Comment by ojw28** [comment]
This is exactly the same as #520. Please don't open new issues for the same thing.

For what it's worth ExoPlayer doesn't has anything directly to do with the UI. It just renders onto a surface. You should look for general resources about achieving fullscreen mode within Android applications, like https://developer.android.com/training/system-ui/immersive.html.
