### ISSUE TITLE
Execution failed for task ':app:transformClassesAndResourcesWithProguardForRelease'.

### ISSUE THREAD

**Issue by zwonb** [google/ExoPlayer#5661]
Warning: there were 1 unresolved references to program class members.
         Your input classes appear to be inconsistent.
         You may need to recompile the code.
         (http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedprogramclassmember)
Warning: Exception while processing task java.io.IOException: Please correct the above warnings first.
Thread(Tasks limiter_15): destruction
> Task :app:transformClassesAndResourcesWithProguardForRelease FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesAndResourcesWithProguardForRelease'.
> Job failed, see logs for details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s

**Comment by tonihei** [comment]
It's impossible to say what went wrong here. Please try what the error message suggests: run with --debug to get more log output. That should tell you what's wrong with the setup and how to fix it.

**Comment by zwonb** [comment]
It is a problem with my project.It is ok now! thx
