### ISSUE TITLE
HLS: Chunkless Preparation breaks certain byte-ranged HLS content

### ISSUE THREAD

**Issue by SukritGupta17** [google/ExoPlayer#5667]
### Issue description

Testing byte-ranged HLS content(fMP4 or TS) with the chunkless preparation feature turned on, the player fails to initialise the content and throws a `player failed` error, To confirm that the content is valid and not the culprit here, we turned off chunkless preparation and re-ran the test, the content played as expected.

### Reproduction steps

- Get the ExoPlayer demo application:
  - `git clone https://github.com/google/ExoPlayer.git.`
  - checkout to latest tagged release `git checkout tags/r2.9.6`
  - open the demo app found in `demo/main` under the HLS section.

- Turn on chunkless preparation:
  - In `PlayerActivity` under `buildMediaSource` add `.setAllowChunklessPreparation(true)` to the HlsMediaSource.Factory() function.
  - Add the test content in the `media.exolist.json` file found under `demo/assets`:
    - Add 
    ```
    {
    "name": "test content",
    "uri":  <use the URI emailed to dev.exoplayer@gmail.com>
    }
    ```
    under the HLS section.

- Play the video.
  - execute the demo app 
  - choose the HLS drop down from the menu list.
  - select the video titled "test content"

You will observe that the video playback fails.

- Now setAllowChunklessPreparation(false) and run again, you will observe the video plays successfully.

### Link to test content

Link to the test content has been emailed to dev.exoplayer@gmail.com under the subject line "issue #NUMBER". 

### A full bug report captured from the device

bug report sent to dev.exoplayer@gmail.com using subject "Issue #NUMBER".

### Version of ExoPlayer being used

ExoPlayer version 2.9.6

### Device(s) and version(s) of Android being used
- LG G6 Android version 7
- LG G6 Android version 8
- Pixel 2 XL Emulator version 9

**Comment by AquilesCanta** [comment]
This is a different instance of #5596, please track that issue for a fix. Thanks for the proper issue report!
