### ISSUE TITLE
Removing None option in PickList AdaptiveTrackSelection

### ISSUE THREAD

**Issue by namespace7** [google/ExoPlayer#5668]
Is it possible to remove None option from Picklist, Any hint will be appreciated ! Here is my code to fetch the supported bitrate from the URL?

    MappingTrackSelector.MappedTrackInfo mappedTrackInfo = selector.getCurrentMappedTrackInfo();
    if (mappedTrackInfo != null) {
        int rendererIndex = 0;
        int rendererType = mappedTrackInfo.getRendererType(rendererIndex);
        boolean allowAdaptiveSelections =
                rendererType == C.TRACK_TYPE_VIDEO
                        || (rendererType == C.TRACK_TYPE_AUDIO
                        && mappedTrackInfo.getTypeSupport(C.TRACK_TYPE_VIDEO)
                        == MappingTrackSelector.MappedTrackInfo.RENDERER_SUPPORT_NO_TRACKS);
        Pair<AlertDialog, TrackSelectionView> dialogPair =
                TrackSelectionView.getDialog(VideoStream.this, "Available Quality", (DefaultTrackSelector) selector, rendererIndex);
        dialogPair.second.setShowDisableOption(true);
        dialogPair.second.setAllowAdaptiveSelections(allowAdaptiveSelections);
        dialogPair.first.show();
    }

![Output Image](https://user-images.githubusercontent.com/29954682/54808167-6dfb2080-4ca5-11e9-9fb5-382e8ab5c0fe.png)

**Comment by tonihei** [comment]
Having you tried removing the `setShowDisableOption(true)`? This statement enables the "None" option.

**Comment by namespace7** [comment]
it does the job! thanks 🗡
