### ISSUE TITLE
Android Architecture Framework connect to default android DB

### ISSUE THREAD

**Issue by Avijit-Bose** [google/ExoPlayer#5670]
Could you please let me know how to connect, retrieve, update and delete data to android default database table like "ContactsContract.Contacts" using android architecture component using Room and Livedata.

Presently I am using getLoaderManager() with CursorLoader, which is deprecated. I want to update my working code with android architecture components and AndroidX.

A simple example will be very useful.
Thank you.

**Comment by ojw28** [comment]
This has nothing to do with ExoPlayer.
