### ISSUE TITLE
REPEAT_MODE_ALL with DefaultHttpDataSourceFactory keeps downloading the video indefinitely

### ISSUE THREAD

**Issue by ninodrop** [google/ExoPlayer#5677]
### [REQUIRED] Searched documentation and issues
I had a look at the [docs](https://google.github.io/ExoPlayer/guide.html) and also at some [stackoverflow questions](https://stackoverflow.com/search?q=ExoPlayer+cache), but I couldn't find an answer.

### [REQUIRED] Question
I am using ExoPlayer to stream a video and I need to repeat the video indefinitely.
The code below is the one I used to set up the player:
```
val player = ExoPlayerFactory.newSimpleInstance(context, DefaultRenderersFactory(context), DefaultTrackSelector(), DefaultLoadControl())
        video_view.player = player
        player?.playWhenReady = true
        player?.repeatMode = Player.REPEAT_MODE_ALL

        val mediaSource = ExtractorMediaSource.Factory(DefaultHttpDataSourceFactory("ua"))
                      .setExtractorsFactory(DefaultExtractorsFactory())
                      .createMediaSource(Uri.parse(video_url))

        player?.prepare(mediaSource)
```

Is it the correct behaviour here to download the video every time it's repeated?
This causes a high data usage if an app is left open with a video looped indefinitely.
What could be the right solution here? To cache the video and set a cache data source?
Is there any documentation available about that?

**Comment by marcbaechinger** [comment]
Yes, you are on the right track by using a CacheDataSource which caches the video when it plays the first time. Every further iteration can then get the data from the cache.

Using a CacheDataSource is explained in the recording of the ExoPlayer session of the last I/O. Starting from about minutes 26 it should give you an impression of how this works: https://youtu.be/svdq1BWl4r8?t=1560

**Comment by ninodrop** [comment]
I tried a similar approach, but probably I set up the cache not correctly since only the first part of the video was cached. 
I might have made a mistake with the size of the cache now that I think of it. 

Generally speaking, how do I make sure that my video will be cached entirely and then no further downloads will be required? Is it enough to set up a cache with a max size big enough for my video?

Also, is there any limitations in using the application specific cache instead of a folder in the external memory?
Thanks in advance for your help!

**Comment by marcbaechinger** [comment]
Yes, I'd say making sure that there is enough storage space available for the cache is sufficient in case you are sure that you only setup the cache for that given file (or you do play that single file only).

For the second question I think using the cache dir is the best option. When using the SimpleCache you can specify the directory when constructing the simple cache. It's plausible for me to use a directory within the directory you get by `context.getCacheDir()`. The system may clear the cache if in need and the user can delete what it's the cache by using the settings page of your app. So from a user perspective this would probably be the preferred choice.

Some further reasons to choose one over the other can be found here: https://developer.android.com/training/data-storage/files

**Comment by ninodrop** [comment]
That makes totally sense and it works fine apparently.
I have to stream a few videos and it's no problem at all if the system clears the cache if/when needed, my only concern was on how to avoid multiple downloads of the same video.
You can mark the question as solved and thank you for your help.
