### ISSUE TITLE
QVBR support

### ISSUE THREAD

**Issue by simoneventurini** [google/ExoPlayer#5678]
[REQUIRED] Searched documentation and issues
I've looked for into the exoplayer [DOC](https://google.github.io/ExoPlayer/) but i've found nothing about it. 
[REQUIRED] Question
I would like know if Exoplayer support Quality-Defined Variable Bitrate (QVBR)?

Thank you.

**Comment by marcbaechinger** [comment]
Can you provide us with a sample stream of content with such a QVBR? For what formats is such a QVBR applicable and how would this manifest in bit stream of the format which supports this? In general there are formats which do have a variable bit rate.

**Comment by ojw28** [comment]
Elemental's [QVBR documentation](https://www.elemental.com/applications/quality-defined-variable-bitrate-qvbr-control) says:

> Quick start: Player changes not required

which implies players don't need to do anything to support it. So I suspect the answer is that QVBR content works fine with ExoPlayer.
