### ISSUE TITLE
Handling of saiz box with no samples

### ISSUE THREAD

**Issue by PaulRutland** [google/ExoPlayer#5684]
### [REQUIRED] Issue description
FragmentedMp4Extractor function parseSaiz() throws a ParserException if the 'saiz' sample count does not match the TrackFragment sample count.

ISO 14496-12 says that the number of samples "must be the same as, or less than" than the number of samples in the track. If the value is less than the number of samples, then "auxiliary information is supplied for the initial samples, and the remaining samples have no associated auxiliary information."

Why does ExoPlayer require the sample count in the 'saiz' box matches the number of samples?

**Comment by marcbaechinger** [comment]
Can you please comment on this, Olly?

**Comment by ojw28** [comment]
It looks like our code is assuming that the auxiliary information referenced by the `saiz` is encryption information, for which it probably doesn't make sense for there to be fewer samples than the number of samples in the track.

From the spec it looks like it would be valid to have `saiz` atoms referencing arbitrary auxiliary information. So we should probably be checking the auxiliary information type and skipping the atom if it's not the type we're looking for. Given this hasn't come up before, I suspect usage of `saiz` to reference other auxiliary information must be very rare.

@PaulRutland - Do you have a stream for which this is problematic? If so, could you please provide it.

**Comment by ojw28** [comment]
@PaulRutland - Please can you update this?

**Comment by ojw28** [comment]
Closing due to lack of requested test stream. If you're able to provide one then please respond with it here, and we'll reopen the issue.
