### ISSUE TITLE
Support of the full ISO/IEC 13818-1, section 2.4.3.6 spec (PES) in .ts segments

### ISSUE THREAD

**Issue by moacir69** [google/ExoPlayer#5685]
### [REQUIRED] Searched documentation and issues
I have searched through the related issues, but I could not find a suitable answer

### [REQUIRED] Question
Is it possible to retrieve the data of the ECM PES packets when using .ts files? If not, is it because the support of the full ISO/IEC 13818-1, section 2.4.3.6 spec (PES) in .ts segments is not fully implemented? In ExoPlayer 2.9.6 it seems that only the following fields are handled:
- packet_start_code_prefix
- stream_id
- PES_packet_length
- '10'
- PES_scrambling_control
- PES_priority
- data_alignment_indicator
- copyright
- original_or_copy
- PTS_DTS_flags
- ESCR_flag
- ES_rate_flag
- DSM_trick_mode_flag
- additional_copy_info_flag
- PES_CRC_flag
- PES_extension_flag
- PES_header_data_length

In this case, when PesReader.consume() is called, there are only null bytes in the payload although the payload size is reported correctly.
Passing MODE_MULTI_PMT to the TsExtractor constructor did not help and caused internal NPEs.
Thank you,

Moacir

**Comment by marcbaechinger** [comment]
Santiago, may I ask you to comment on this ts related question?

**Comment by AquilesCanta** [comment]
Hi @moacir69, you can inject custom [TsPayloadReaders](https://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/extractor/ts/TsPayloadReader.html) through the [PayloadReader Factory](https://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/extractor/ts/TsPayloadReader.Factory.html) interface. You can then implement parsing in the app, so you should be able to access any information you need.

ECM parsing is not yet supported in the library.

>In this case, when PesReader.consume() is called, there are only null bytes in the payload although the payload size is reported correctly.
Passing MODE_MULTI_PMT to the TsExtractor constructor did not help and caused internal NPEs

Please file issues for these including all information required in the issue template. We cannot help in any way with this amount of information.

**Comment by moacir69** [comment]
Ok, thanks for the feedback.
Indeed a reader is being added to DefaultTsPayloadReaderFactory.createPayloadReader(), but when it is called inside PesReader.consume() only the header and extended header bytes are available, the payload bytes are filled with null bytes...

Moacir

**Comment by moacir69** [comment]
For the same PID, the PES related TS packets with 'payload_unit_start_indicator' with value 0 were not being handled and the missing bytes could be found in there.
Thanks,

Moacir

**Comment by AquilesCanta** [comment]
I can't help with this information. If you think there is an ExoPlayer bug, please follow the normal approach.
