### ISSUE TITLE
Video Freeze after looping for 1-2 days

### ISSUE THREAD

**Issue by akurni** [google/ExoPlayer#5687]
### [REQUIRED] Issue description
This bug is similar to #4559 and #3829, but this happens on exoplayer 2.9.6 and I tried to use FLAG_WORKAROUND_IGNORE_EDIT_LISTS and it still freezes after looping for a while

### [REQUIRED] Reproduction steps
loop the video for 1-2 days and the video will freeze 

### [REQUIRED] Link to test content
https://www.dropbox.com/s/1m7117ls4v7x0cg/7e6caaa057bddaec2d2ea55cc6befe1c577229a5aaeff58d00c6a66fd7d145f7.mp4?dl=0

### [REQUIRED] A full bug report captured from the device
I included both bugreport with and without the IGNORE edit list flag
[bugreport.txt](https://github.com/google/ExoPlayer/files/3011628/bugreport.txt)
[bugreport_GAPLESS_FLAG_ENABLED.txt](https://github.com/google/ExoPlayer/files/3011629/bugreport_GAPLESS_FLAG_ENABLED.txt)

### [REQUIRED] Version of ExoPlayer being used
2.9.6

### [REQUIRED] Device(s) and version(s) of Android being used
Orange Pi PC Plus Android v4.4

**Comment by ojw28** [comment]
Is this a device specific issue, or are you seeing it across all devices?

**Comment by marcbaechinger** [comment]
Closing due to inactitvity. Please reopen if you provided additional information.
