### ISSUE TITLE
HLS: Multiple duplicate initialisation segment download for HLS fMP4 content

### ISSUE THREAD

**Issue by SukritGupta17** [google/ExoPlayer#5695]
### [REQUIRED] Issue description
ExoPlayer version 2.9.6, with HLS fMP4 content playback, the player makes a request and downloads the initialisation segment every time before downloading a new segment even if the initialisation segment is common for every segment of that particular quality. In contrast, with the previous ExoPlayer version tested (version 2.7.3), the initialisation segment is only downloaded once, after the manifest for the quality is downloaded. This issue with version 2.9.6 seems to stem from a feature implementation for supporting multiple `EXT-X-MAP` tags as described in [issue 4182](https://github.com/google/ExoPlayer/issues/4182) with [commit ddef32c](https://github.com/google/ExoPlayer/commit/ddef32c9e2f8d754d46af58566229f179bb00bc8).  

### [REQUIRED] Reproduction steps
- Get the ExoPlayer demo application:
  - git clone https://github.com/google/ExoPlayer.git.
  - checkout to latest tagged release `git checkout tags/r2.9.6`
  - open the demo app found in `demo/main` under the HLS section.

- Add the test content in the `media.exolist.json` file found under `demo/assets`:
  - Add:
  ```json
  {
  "name": "Bitmovin Sample content (fMP4)",
  "uri": "https://bitmovin-a.akamaihd.net/content/MI201109210084_1/m3u8s-fmp4/f08e80da- 
  bf1d-4e3d-8899-f0f6155f6efa.m3u8"
  }
  ```
  under the HLS section

- Turn on advance profiling from run configuration. (only needed for phones on API version < 26)
- Open the profiler from view → tool windows → profiler
- Play the video:
  - execute the demo app 
  - choose the HLS drop down from the menu list.
  - select the video titled "Bitmovin Sample Content (fMP4)"
- Select the network profiling section
  - After 30 seconds, select the timeline for 30 seconds
  - The connection view will list the files requested and downloaded. It would look similar to the images attached [Archive.zip](https://github.com/google/ExoPlayer/files/3015957/Archive.zip)

- (Optional) Repeat the process with ExoPlayer version 2.7.3 for comparison.

### [REQUIRED] Link to test content

```json
{
"name": "Bitmovin Sample content (fMP4)",
"uri": "https://bitmovin-a.akamaihd.net/content/MI201109210084_1/m3u8s-fmp4/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8"
}
```

### [REQUIRED] A full bug report captured from the device
No bug report required as the player does not produce any errors.

### [REQUIRED] Version of ExoPlayer being used
ExoPlayer version 2.9.6 and version 2.7.3

### [REQUIRED] Device(s) and version(s) of Android being used
- LG G6 android version 7
- LG G6 android version 8
- Pixel 2 XL android emulator version 9

**Comment by AquilesCanta** [comment]
Hi @SukritGupta17, could you please try the dev-branch? This issue should be fixed by [this commit](https://github.com/google/ExoPlayer/commit/0ceff589b33992a98db0e439b24aea75f772e6ef). It will be available in the 2.10 release. Thanks for the finely crafted issue report!
