### ISSUE TITLE
Local video playback stuck in buffering

### ISSUE THREAD

**Issue by rantianhua** [google/ExoPlayer#5696]
### [REQUIRED] Issue description
Play a mp4 local video, but there isn't any audio and video is shown. I have seen the log we collected and it showed that ExoPlayer got stuck in buffering state all the time. If play the video with a ass format subtitle file, this problem would arise more frequently.

### [REQUIRED] Reproduction steps
Sorry, our users met this problem, but I cannot reproduce it. I play the video like this way:
```
val rendersFactory = DefaultRenderersFactory(this)
val bandWidthMeter = DefaultBandwidthMeter()
val videoTrackSelectionFactory = AdaptiveTrackSelection.Factory(bandWidthMeter)
val trackSelector = DefaultTrackSelector(videoTrackSelectionFactory)
val player = ExoPlayerFactory.newSimpleInstance(rendersFactory, trackSelector)
val dataSourceFactory = DefaultDataSourceFactory(this, "xxx")
val videoSource = ExtractorMediaSource(Uri.parse("file:///xxx.mp4"), dataSourceFactory, DefaultExtractorsFactory(), null, null)
player.prepare(videoSource)
player.playWhenReady = true
```

I play video with subtitle just like this way:
```
val videoSource = ...
val textFormat = Format.createTextSampleFormat("MySubtitle", MimeTypes.TEXT_SSA, C.SELECTION_FLAG_DEFAULT, null)
val subtitleSource = SingleSampleMediaSource(Uri.parse("file:///xxx.ass"), dataSourceFactory, textFormat, C.TIME_UNSET)
val mediaSource = MergingMediaSource(videoSource, subtitleSource)
player.prepare(mediaSource)
player.playWhenReady = true
```

And the log is like this:
```
[2019-03-27 22:37:21.509][6231, 6231*][play xxx.mp4 start]
[2019-03-27 22:37:21.510][6231, 6231*][onPlayerStateChanged playWhenReady = true playbackState = 1]
[2019-03-27 22:37:21.533][6231, 6231*][onPlayerStateChanged playWhenReady = true playbackState = 2]
[2019-03-27 22:37:21.538][6231, 6231*][onLoadingChanged isLoading = true]
[2019-03-27 22:37:30.479][6231, 6231*][onPlayerStateChanged playWhenReady = false playbackState = 2]
```
You can see that the player got stuck in buffering state after 2019-03-27 22:37:21.533, and the user pause the player at 2019-03-27 22:37:30.479. The user cannot see or listen anything during the approximately 16 seconds.

### [REQUIRED] Link to test content
I will send an email.

### [REQUIRED] A full bug report captured from the device
Our QA seems to have reproduced this problem, but I got the device and pull the bug report file on the second day. So, I am not sure the report I captured can provide useful information for you guys. I will send an email.

### [REQUIRED] Version of ExoPlayer being used
ExoPlayer 2.6.0

### [REQUIRED] Device(s) and version(s) of Android being used
This problem occurred at these devices:
PAR-AL00 Build/HUAWEIPAR-AL00 Android 9
JKM-AL00a Build/HUAWEIJKM-AL00a Android 8.1.0
HUAWEI RNE-AL00 Android 8.0.0
OPPO R15 Android 8.1.0
MEIZU Pro 7 Android 7.0
HUAWEI nova3 Android 9

**Comment by marcbaechinger** [comment]
Thanks for sending the video and the subtitle file. I tested this with the demo application and it works fine. The video plays and after I have selected the subtitle track the video plays with the subtitles as expected:

![cat](https://user-images.githubusercontent.com/584321/55153865-62977180-514b-11e9-9e02-de56efd9e769.png)

In your code, you are using this expression for the uri: `Uri.parse("file:///xxx.mp4")` I assume you did replace the actual file name for the sake of a public sample. In any case, if your file is locally on the device I suspect the filename should be different. I recommend to put that file in the assets directory of your app module for testing purpose. Then use something like: `Uri.parse("file:///android_asset/5696.mp4")`  (please note the android_asset part of the url.

May I ask you to review your code and check whether you pasted the correct code. Because when you are saying that your QA team found that issue, I wonder whether you really have the file:/// url in use. So the bug raport probably does not match with the code you sent?

**Comment by rantianhua** [comment]
The video and subtitle file are downloaded from network, so I cannot put the files into asset. The problem presents occasionally and I cannot reproduce it too, that's the worst part. 

I am sure that the files exit, otherwise I will find `FileNotFoundException`, but there is not any error message and the player gets stuck in buffering state.

**Comment by marcbaechinger** [comment]
You've named this issue "Local video playback stuck in buffering", used a file:// uri and you sent us two files so it was looking like you were referring to local playback.

However, those files play when read from local storage which is usually a good test to see whether it works without the need to care around network issues.

The intermittent behavior you are describing actually indicates that there are network issues. When in buffering state then it's maybe just loading very slowly? As an aside you don't need to watch out for a FileNotFoundException if you are loading from the network. But I agree there should be a stake trace or similar reporting about network issue.

If you want me to look into this you can send me the urls for those files so I can test with network involved. You may also look into the network traffic yourself by using the [network profiler of Android Studio](https://developer.android.com/studio/profile/network-profiler). This should give you an idea of what is going on when the player is loading.

**Comment by rantianhua** [comment]
This is totally local playback. I download files to local storage and then play it locally, so it's not about network. Is it possible that there are some known buffering issues that will cause this case?

**Comment by rantianhua** [comment]
This is a really confused problem and I'm intent to read buffering relevant code carefully, hope to have some usefully discoveries.

**Comment by marcbaechinger** [comment]
Ok, cool. I'm not aware of buffering problems when reading from local files. As mentioned above, I tried this out with your sample files and it worked as expected.

I don't want to discourage you in reading our 'buffering relevant code'. Please let us know in case you find something. I'd, however, first try to reproduce the problem on a device you are having. If it's still true that you only have reports from your QA I would first try to reproduce it on a device which your have under control. Further I don't assume that the code above is the one from which your QA gets the report. So it seems beneficial to test with the same code like the person runs from which your QA got the error report.

**Comment by guil18** [comment]
Hi,
Just in case, I had the same issue of mediaItems stuck in BUFFERING state for local audio files with version 2.9.6.
Version 2.9.5 does not have this issue.
Best regards,

**Comment by marcbaechinger** [comment]
@guil18 Many thanks for your report. 

Can you provide us with a way to repro this? What are the similarities with the case above? Are you using subtitles as well? Can you repro in the demo app?

Can you please provide us with a test media file and in case subtitle so I can try to repro? If you have a bug report please upload here so we can investigate.

Any input appreciated.

**Comment by rantianhua** [comment]
@marcbaechinger I reproduced the problem eventually. The real cause is that the video file is not been downloaded completely. If an incomplete file is prepared by ExoPlayer, the player will stuck in buffering state.

To reproduce this problem, just play this file:

[bad_video.mp4.zip](https://github.com/google/ExoPlayer/files/3279395/bad_video.mp4.zip)

You can use UltraEdit to see that the latter part of the file is empty.

At last, I'm thinking that can ExoPlayer throw an exception in this case?
