### ISSUE TITLE
ExoPlayer cache

### ISSUE THREAD

**Issue by vmtrue** [google/ExoPlayer#57]
Can give me sample how cache video. And How do play video from cache. I have found CacheDataSource, but I don't know how it use.

**Comment by ilansas** [comment]
@fisher3421 did you finally make it ? I'm interested in this, I spent the all day searching for an answer, but didn't find anything on cache subject in ExoPlayer...

**Comment by master255** [comment]
@fisher3421 you can use my project https://github.com/master255/ImmortalPlayer   for caching

**Comment by ilansas** [comment]
I know thank you but I really need to use ExoPlayer for different reasons.

**Comment by jjvargas** [comment]
Does anyone have an example of how to use CacheDataSource on HLS ?

**Comment by ojw28** [comment]
It's not possible to do this (yet). I've filed a tracking issue here: #322.

**Comment by ilansas** [comment]
Are you sure ? Because the doc seems to say it's possible, just there are no example on the Internet...

**Comment by ojw28** [comment]
Yes, I am sure.

**Comment by voghDev** [comment]
Did a failed implementation that was looking good. Still investigating it. If you want to know more see [this thread] (http://stackoverflow.com/questions/28700391/using-cache-in-exoplayer)

**Comment by master255** [comment]
@voghDev hey i wrote a super proxy named ImmortalPlayer for resolving this problem! This sample code can use with any player. Enjoy: https://github.com/master255/ImmortalPlayer
