### ISSUE TITLE
Play video files from phone memory issue

### ISSUE THREAD

**Issue by drayan85** [google/ExoPlayer#570]
I have implemented a player using exoplayer library project. Playing online streaming videos working perfectly. But When i try to play some files from phone memory (local files) it is not starting play video by itself. If i drag the seek bar little bit then it start to play.

Any guess to over come this issue, would be really a great helpful.

Thank you in advance.

**Comment by drayan85** [comment]
LOG
====

 D/ViewRootImpl﹕ ViewPostImeInputStage ACTION_DOWN
 I/ExoPlayerImpl﹕ Init 1.2.4
 D/EventLogger﹕ start [0]
 D/EventLogger﹕ state [0.00, false, P]
 D/EventLogger﹕ state [0.00, true, I]
 D/EventLogger﹕ state [0.01, true, P]
 D/EventLogger﹕ state [0.06, true, B]
 I/ACodec﹕ [] Now uninitialized
 I/OMXClient﹕ Using client-side OMX mux.
 I/ACodec﹕ [OMX.qcom.video.decoder.avc] Now Loaded
 E/ACodec﹕ onConfigureComponent mime.c_str() = video/avc
 E/ACodec﹕ [OMX.qcom.video.decoder.avc] storeMetaDataInBuffers failed w/ err -2147483648
 I/ACodec﹕ [OMX.qcom.video.decoder.avc] DRC Mode: Port Reconfig Mode
 I/ExtendedCodec﹕ Decoder will be in frame by frame mode
 I/ACodec﹕ [OMX.qcom.video.decoder.avc] OMX_QCOM_FramePacking_OnlyOneCompleteFrame is setting
 W/ACodec﹕ do not know color format 0x7fa30c03 = 2141391875
 I/ACodec﹕ TimeStampReoder feature is working!
 I/ACodec﹕ [OMX.qcom.video.decoder.avc] Now Loaded->Idle
 I/ACodec﹕ [OMX.qcom.video.decoder.avc] configureOutputBuffersFromNativeWindow setBufferCount : 22, minUndequeuedBuffers : 4
 I/ACodec﹕ [OMX.qcom.video.decoder.avc] Allocating 22 buffers from a native window of size 229376 on output port
 I/ACodec﹕ [] Now uninitialized
 I/ACodec﹕ [OMX.qcom.video.decoder.avc] Now Idle->Executing
 I/OMXClient﹕ Using client-side OMX mux.
 I/ACodec﹕ [OMX.SEC.aac.dec] Now Loaded
 I/ACodec﹕ [OMX.qcom.video.decoder.avc] Now Executing
 E/ACodec﹕ onConfigureComponent mime.c_str() = audio/mp4a-latm
 I/OMXCodec﹕ OMXCodec::AudioConfigAdd 1, 2
 I/ACodec﹕ ACodec::configureCodec OutCh  2 + 2, Err : 0 ++
 I/ACodec﹕ [OMX.SEC.aac.dec] Now Loaded->Idle
 I/ACodec﹕ [OMX.qcom.video.decoder.avc] Now handling output port settings change
 I/ACodec﹕ [OMX.SEC.aac.dec] Now Idle->Executing
 I/ACodec﹕ [OMX.SEC.aac.dec] Now Executing
 I/ACodec﹕ [OMX.qcom.video.decoder.avc] configureOutputBuffersFromNativeWindow setBufferCount : 9, minUndequeuedBuffers : 4
 I/ACodec﹕ [OMX.qcom.video.decoder.avc] Allocating 9 buffers from a native window of size 229376 on output port
 E/AudioTrack﹕ AudioTrack::set : Exit
 I/ACodec﹕ [OMX.qcom.video.decoder.avc] Now Executing
 W/ACodec﹕ do not know color format 0x7fa30c03 = 2141391875
 D/EventLogger﹕ videoSizeChanged [480, 270, 1.0]
 D/EventLogger﹕ state [0.32, true, R]

**Comment by ojw28** [comment]
I doubt this has anything to do with whether you're streaming or playing locally. Unless you're testing the exact same content in both cases, the comparison isn't fair. Are you? If not, it's likely just a problem playing the specific media that you're trying to play locally (whether it's played locally or streamed).

**Comment by drayan85** [comment]
I have tried same media files in both cases (online streaming & playing locally). Still the issue is there. Is there anything you can see from the log which i have left above ?

**Comment by ojw28** [comment]
No. You'd probably need to make the test media available.

**Comment by drayan85** [comment]
Sorry I have update my last comment, could you please have look the updated one. thanks!

**Comment by ojw28** [comment]
The amount of memory consumed by a device update should have no effect on the ability to play media or on the speed of the device.

Are you using FrameworkSampleSource as part of your ExoPlayer? If so, please see the warning documented for that class, and try ExtractorSampleSource instead. If you're still experiencing the issue, you'll need to provide the media for us to debug.

Thanks!

**Comment by drayan85** [comment]
Thanks for the reply After update the library and started Use ExtractorSampleSource instead of FrameworkSampleSource, problem is got resolved.

Thanks a ton once again.
