### ISSUE TITLE
onPlayerStateChanged is only called once in other Looper

### ISSUE THREAD

**Issue by imcloud** [google/ExoPlayer#5701]
### [REQUIRED] Issue description
I am running exoplayer in single thread and I find that the onPlayerStateChanged will only be called once, and state is 2(buffering).
<img width="761" alt="屏幕快照 2019-03-29 10 19 20" src="https://user-images.githubusercontent.com/7680469/55205030-27a94280-520c-11e9-8c52-38618afde774.png">

### [REQUIRED] Reproduction steps
```kotlin
Completable.complete()
                .observeOn(Schedulers.single())
                .subscribe {
                    Looper.prepare()

                    val mp4VideoUri = Uri.parse("/sdcard/download/bbb.mp3")

                    exoPlayer = ExoPlayerFactory.newSimpleInstance(applicationContext)
                    val dataSourceFactory = DefaultDataSourceFactory(applicationContext,
                            Util.getUserAgent(applicationContext, "yourApplicationName"))
                    val videoSource = ExtractorMediaSource.Factory(dataSourceFactory)
                            .createMediaSource(mp4VideoUri)
                    exoPlayer.prepare(videoSource)
                    exoPlayer.playWhenReady = true
                    exoPlayer.addListener(object : Player.EventListener {
                        override fun onPlayerStateChanged(playWhenReady: Boolean, playbackState: Int) {
                            Log.d("findandroidusbmanager", "EventListener -> playbackState = ${playbackState}!!!")
                        }

                        override fun onPositionDiscontinuity(reason: Int) {
                            Log.d("findandroidusbmanager", "onPositionDiscontinuity reason = $reason")
                        }
                    })
                    exoPlayer.addAnalyticsListener(object : AnalyticsListener{
                        override fun onPlayerStateChanged(eventTime: AnalyticsListener.EventTime?, playWhenReady: Boolean, playbackState: Int) {
                            Log.d("findandroidusbmanager", "AnalyticsListener -> playbackState = ${playbackState}!!!")
                        }
                    })
                }
```

### [REQUIRED] Link to test content
playback a local mp3 file
[bbb.mp3.zip](https://github.com/google/ExoPlayer/files/3020794/bbb.mp3.zip)

### [REQUIRED] A full bug report captured from the device

[bugreport-FindPiano-OPM1.171019.011-2019-03-29-05-57-33.txt.zip](https://github.com/google/ExoPlayer/files/3020791/bugreport-FindPiano-OPM1.171019.011-2019-03-29-05-57-33.txt.zip)
full files too big, 36m, can not upload, If you need other, I will upload it separately.

### [REQUIRED] Version of ExoPlayer being used
2.9.6

### [REQUIRED] Device(s) and version(s) of Android being used
a Qualcomm board,  version 8.1.0

**Comment by marcbaechinger** [comment]
Thanks for your report.

Can you be a little bit more specific in what your expectation is and what actually happened? Please describe what you did and what happened an how this differs from your expectation.

I'm not quite sure what the Completable is and how it works. I can't really advise on how to integrate with RxAndroid or similar. In general I'd recommend to simply make sure you create the ExoPlayer instance on the main thread as well as you call all the method on ExoPlayer on the main thread. 

Please also upload the full bugreport, so we can look into this. The current part is not helpful as it's only a part of it leaving the entire log out. It, for instance, does not contain the log statements for which you provided us with a screenshot If you want to help us some further you can use the `EventLogger`, which would log useful information to the log, which allows to interpret what the player is doing.

**Comment by ojw28** [comment]
I see two state changes when I play this sample in the demo app. This suggests to me that this is an issue with application code, which is outside the scope of this issue tracker.

I don't fully understand the code above, but calling `Looper.prepare` inside subscribe looks pretty weird. Is that turning a thread you don't necessarily own into a `Looper` thread, because if so then I don't think you should do that. I'd also expect to see a `Looper.loop` call, else I'm not sure the `Looper` thread is really being setup properly to process messages delivered to it.

Closing because this is highly likely to be an application code issue.
