### ISSUE TITLE
Buffer issue in HLS format videos

### ISSUE THREAD

**Issue by ummerakbar45** [google/ExoPlayer#5702]
### [REQUIRED] Content description
We have Video App implemented for different platforms like Roku, ioS, FireTv, and Android.
In Android, we are using Exo Player and our Media content is of HLS format.
In Android, we are facing a buffer issue.
The issue is not in Content because other platform uses the same content.

### [REQUIRED] Link to test content
```
private void initializePlayer() {
        //Handler mainHandler = new Handler();
        bandwidthMeter = new DefaultBandwidthMeter();
        videoTrackSelectionFactory = new AdaptiveTrackSelection.Factory(bandwidthMeter);
        trackSelector = new DefaultTrackSelector(videoTrackSelectionFactory);
        trackSelector.setParameters(new DefaultTrackSelector.ParametersBuilder()
                .setRendererDisabled(C.TRACK_TYPE_VIDEO, true)
                .build()
        );

        // Create the player
        player = ExoPlayerFactory.newSimpleInstance(this,
                new DefaultRenderersFactory(this),
                trackSelector, new DefaultLoadControl());
        playerView.getSubtitleView().setStyle(new CaptionStyleCompat(Color.WHITE, Color.TRANSPARENT, Color.TRANSPARENT, CaptionStyleCompat.EDGE_TYPE_NONE, Color.WHITE, null));
     
    }
```
Hls media source

```
private MediaSource buildHLSMediaSource(final String url, final String ccPath) {


        DataSource.Factory dataSourceFactory = new DefaultDataSourceFactory(MediaPlayerActivity.this,
                Util.getUserAgent(MediaPlayerActivity.this, "videoApp"), bandwidthMeter);
// This is the MediaSource representing the media to be played.
        //url="http://qthttp.apple.com.edgesuite.net/1010qwoeiuryfg/sl.m3u8";
        HlsMediaSource hlsMediaSource = new HlsMediaSource.Factory(dataSourceFactory)
                .createMediaSource(Uri.parse(url));

        if (StringUtils.isNotBlank(ccPath)) {

            Format subtitleFormat = Format.createTextSampleFormat(
                    "0", // An identifier for the track. May be null.
                    MimeTypes.APPLICATION_SUBRIP, // The mime type. Must be set correctly.
                    Format.NO_VALUE, // Selection flags for the track.
                    "En"); // The subtitle language. May be null.
            MediaSource subtitleSource = new SingleSampleMediaSource.Factory(dataSourceFactory).createMediaSource(Uri.parse(ccPath), subtitleFormat, C.TIME_UNSET);
            //SingleSampleMediaSource singleSampleMediaSource =Factory(dataSourceFactory)
            MergingMediaSource mergedSource =
                    new MergingMediaSource(hlsMediaSource, subtitleSource);


            return mergedSource;
        } else {
            return hlsMediaSource;
        }

    }
```

### [REQUIRED] Version of ExoPlayer being used
Exoplayer 2.9.0

### [REQUIRED] Device(s) and version(s) of Android being used
Any Android Device and version >21

**Comment by marcbaechinger** [comment]
Thanks for your report. 

Can you please provide us with a url for both the HLS stream and the subrip file which you want to merge? We need this for testing. It may well be that your content is correct but we are having a problem with a specific aspect of the content which we haven't seen yet. So for looking into this, it would be of great value to have the same content as you. You can send it to dev.exoplayer@gmail.com if you don't want to post it here in public.

It would also be great if you can elaborate a bit on "we are facing a buffer issue". I reckon you mean that the player falls into buffering state and never gets out of it. Can you describe a little of when this happens? Best of course would be you provide us with a bug report which does illustrate your expectations which haven't been met.

**Comment by marcbaechinger** [comment]
Sorry, I did not spot the url in the source code above: http://qthttp.apple.com.edgesuite.net/1010qwoeiuryfg/sl.m3u8

When adding the url to the demo app it plays fine. Your code merges a subtitle track with the HLS stream when `ccPath` is provided as an argument of the method. Did you see the buffering behaviour with the merged media source? I can look into this if you provide me the url of the subtitle.
