### ISSUE TITLE
Video lags wen playing video in 2.0 speed

### ISSUE THREAD

**Issue by ItsRay** [google/ExoPlayer#5703]
### [REQUIRED] Issue description
I played a HLS video in 1.0 speed and it acts normally. But when I played the same video in `2.0 speed`, the the playback position is not growing in 2.0 speed , and it seems some frames were dropped.
I expect this videos were played without frame dropped and the playback position is growing in 2.0 speed.
This happens on many devices when I use my project to play a video which uses ExoPlayer version `r2.5.2`. But when I use the ExoPlayer demo project in version `2.9.6`, it only happens on device `OPPO A77`.

### [REQUIRED] Reproduction steps
Add the following line after SimpleExoPlayer is created and play any HLS content provided in ExoPlayer demo project. 

```
player.setPlaybackParameters(new PlaybackParameters(2.0f));
```

### [REQUIRED] Link to test content
Many links in ExoPlayer demo project, here is one of them:
```
      {
        "name": "Apple master playlist advanced (TS)",
        "uri": "https://devstreaming-cdn.apple.com/videos/streaming/examples/img_bipbop_adv_example_ts/master.m3u8"
      }
```

### [REQUIRED] A full bug report captured from the device
Sent by email.

### [REQUIRED] Version of ExoPlayer being used
2.9.6

### [REQUIRED] Device(s) and version(s) of Android being used

Device: OPPO A77
Android version: 6.0

**Comment by andrewlewis** [comment]
If frames are dropping during faster than realtime playback that suggests that decoding is too slow and can't keep up with the player position.

Could you try selecting only the lowest quality version of the video stream, or setting a lower playback speed like 1.5, and let us know if that works? If the issue is indeed that decoding is too slow, I'm afraid there's probably not much we can do.

**Comment by andrewlewis** [comment]
The bug report is from a device running Marshmallow, so using a debuggable APK could also explain what you're seeing. See this [blog post](https://medium.com/google-exoplayer/variable-speed-playback-with-exoplayer-e6e6a71e0343) for more information.

**Comment by ItsRay** [comment]
Thank you for the answer!!
It does fix the problem on OPPO A77. But It's still not smooth on some devices. But I can't reproduce it by the sources in ExoPlayer sample, it seems only happens in high resolution contents. So I have created another [issue](https://github.com/google/ExoPlayer/issues/5752).
