### ISSUE TITLE
Delete device cert to test executeProvisionRequest

### ISSUE THREAD

**Issue by simhavenkat** [google/ExoPlayer#5707]
### Question
I am trying to proxy executeProvisionRequest and for testing purposes i need to make this callback happen all the time. The call only seems to be happening once per device - also on some devices its already present and this call doesn't happen.

Is there a way to delete the device cert?

**Comment by andrewlewis** [comment]
I'm not aware of a way to force reprovisioning, or if it is even theoretically possible for devices where provisioning happens at the factory like for Widevine L1. @ojw28 and @AquilesCanta will be able to confirm or correct this.

If you really need this for testing, perhaps you can inject fake/mock components to simulate getting EVENT_PROVISION_REQUIRED every time.

**Comment by andrewlewis** [comment]
@ojw28 mentioned there's a file one can delete to clear provisioning data on rooted devices (this doesn't work for factory-provisioned devices though). Hopefully he can provide some more details here :)

**Comment by ojw28** [comment]
If you have a rooted device and want to force re-provisioning for testing purposes, you can delete the files under `/data/mediadrm/`. This should force re-provisioning. Note that, to the best of my knowledge, factory-provisioned devices don't need provisioning. So those devices wont generate provisioning requests no matter what you do.
