### ISSUE TITLE
playback encrypted multicast video

### ISSUE THREAD

**Issue by kenodevel** [google/ExoPlayer#5709]
### Question
Hello, i am new to Exoplayer. I just tried playback a clear multicast video stream successfully and would like to explore if i can play encrypted multicast video also.
Would anyone suggest a way where can i get & modify/decrypt the ts packets by some external library?

**Comment by andrewlewis** [comment]
I don't think there are enough details about what you're trying to do for us to help here. Depending on how the input is encrypted, you may be able to use a custom `DataSource` (like `AesCipherDataSource`) or a custom `TsPayloadReader.Factory` to achieve the result you are aiming for.

**Comment by kenodevel** [comment]
I would like to decrypt the video/audio payload inside those TS packet

**Comment by andrewlewis** [comment]
Please try the suggestion in my previous comment. We can't help further unless you provide detailed information about what is needed, so I will close this for now. If you discover some ExoPlayer limitation that prevents you doing what you need to do please describe it here and I'll reopen the issue.

**Comment by kenodevel** [comment]
Thanks, i try to create a custom DataSource and i can touch those raw bytes from multicast. It seems i can only modify the data inside the read method. Is there anyway to drop some unwanted ts packet?

**Comment by kenodevel** [comment]
I think i solved my problem as i overlook the "the call will block until at least one byte of data has been read and the number of bytes read is returned" of read.
