### ISSUE TITLE
Frame rendering timing with MediaClock

### ISSUE THREAD

**Issue by Arqu** [google/ExoPlayer#571]
Considering the new implementation of MediaClock, the timing of frames rendered seems no longer to be handled by MediaCodecVideoTrackRendered but more by the the MediaCodecAudioTrackRenderer with the MediaClock implementation. Since I need to "adjust" the frame rate on my own in some of my cases (I know this is a bit unrelated to the general implementation), I wonder how can we manage playback speed/rendering timing now (currently it is ok to disable or distort the audio for me).

**Comment by ojw28** [comment]
There hasn't been any functional change in terms of how timing is implemented. MediaCodecAudioTrackRenderer has always driven the timing. Previously it indicated this by returning true from isTimeSource. Now it does so by returning a clock instance from getMediaClock. This is solely a restructuring of the code, not a change in how it works.

Given your use cases are custom, you'll have to figure them out on your own!

**Comment by Arqu** [comment]
Thanks managed to figure it out with getMediaClock and getPositionUs().
