### ISSUE TITLE
How to prebuffer HLS stream

### ISSUE THREAD

**Issue by LaurentiuSimionescu** [google/ExoPlayer#5710]
Hi,

I have a list of m3u8 files on a server, in my app I have an ExoPlayer and a next button. ExoPlayer can play videos with default options, however there is a small delay when I skip videos.

**What I want** is to play the next video instantly.

Things I tried:
- Using ConcatenatingMediaSource, (this doesn't help me because it only pre-buffers next video if the current video is almost finishing, I don't what to use .next() or .previous() methods.
- Download master playlist, download a playlist file, download first segment, replace path for the first segment with local path. This works really fast, but I don't want to modify any playlist.
- Download first segment of a playlist, Intercept requests with OkHttp and if the requested segment is downloaded, return a mock response with the local file. This works, but is not fast at all, (2-3 seconds to load a 3 seconds segment). Any suggestions how can I make it faster ?

Things I want to know:
- If I use **CacheUtil.cache()** how does ExoPlayer know what is cached ?
- What is the best way to pre-buffer/pre-cache a list of HLS, and when I press next button to instantly play the video ?

**Comment by andrewlewis** [comment]
#3327 tracks supporting pre-buffering of future concatenation items, which I think is what you really need for this.

> If I use CacheUtil.cache() how does ExoPlayer know what is cached ?

The cache has an index representing what pieces of media have been stored, alongside the cached media.

> What is the best way to pre-buffer/pre-cache a list of HLS, and when I press next button to instantly play the video ?

Have you tried creating a single cache for both playback and downloading, and implementing logic in the app to download the next HLS stream at the same time that playback is progressing?

**Comment by LaurentiuSimionescu** [comment]
> Have you tried creating a single cache for both playback and downloading, and implementing logic in the app to download the next HLS stream at the same time that playback is progressing?
>

I didn't succeed with this approach. Any documentation/articles/examples please ?

> Download master playlist, download a playlist file, download first segment, replace path for the first segment with local path. This works really fast, but I don't want to modify any playlist.
> 

I have implemented this, I am caching all the first segments from all playlists in a master playlist. And adding the local path instead of remote path. When I play the video there is still a small delay (2-3).
I have a RecyclerView and when I swipe I am preparing the local file and play it.

**Comment by andrewlewis** [comment]
> I didn't succeed with this approach. Any documentation/articles/examples please ?

I don't think we have any detailed documentation about this, but @erdemguven may be able to provide guidance.

Could you describe in more detail what went wrong? If you have a downloader and player pointing at the same cache my understanding is that this should just work for segmented media, but maybe I am missing something.

**Comment by LaurentiuSimionescu** [comment]
> Have you tried creating a single cache for both playback and downloading, and implementing logic in the app to download the next HLS stream at the same time that playback is progressing?
> 
Finally this worked. I took [ExoPlayer](https://github.com/google/ExoPlayer/tree/release-v2/demos/main) example. This example handles the cache part very nicely.
Than I used [Toro](https://github.com/eneim/toro) for handling ExoPlayer in RecyclerView.
All good. If anyone needs help, please let me know.

**Comment by geniusmanish** [comment]
@LaurentiuSimionescu  Can you please explain how you achieved PreCaching with ExoPlayer. 
When i am trying PreCaching and playing video in loop . It goes in infinite buffering state after playing for 25 minutes .

**Comment by shubhamvashisht** [comment]
@LaurentiuSimionescu can you share some info how did you pre-buffer working?
