### ISSUE TITLE
How to verify the checksum of downloaded widevine encrypted MPD DASH

### ISSUE THREAD

**Issue by kushalgupta0565** [google/ExoPlayer#5715]
I have sucessfully downloaded the encrypted widevine DASH video, now i need to verify the checksum i.e video is downloaded sucessfully or not.

Can anyone please suggest me a way to verify it.

**Comment by andrewlewis** [comment]
Please see #2711. It's not safe to assume that the representation of cached data matches the original files on the server. You may still be able to do some processing if you can operate on data read back from the cache using `CacheDataSource`.

**Comment by ojw28** [comment]
As a general point, it seems unnecessary to do this. If you're downloading over https there's no reason to expect that a download would be corrupt (and if you're not downloading over https, you probably should be).
