### ISSUE TITLE
How to extract custom EXT tag and sequence number from HLS stream?

### ISSUE THREAD

**Issue by souravbasu14** [google/ExoPlayer#5716]
How to extract custom EXT tag and sequence number from HLS stream?

In our streaming server we've put some custom EXT tag for each media fragment & we need to read that data when a media fragment is loaded in player.

We tried to add MediaSourceEventListener and try to get the information from onLoadCompleted callback. But LoadEventInfo and MediaLoadData doesn't provide the same information.
To give a reference, in [hls.js](https://github.com/video-dev/hls.js) we get the below information when a fragment is loaded. Need the similar info in exoplayer .
Please suggest which interface can provide those information.

![Screen Shot 2019-04-02 at 12 02 02 AM](https://user-images.githubusercontent.com/10879439/55390223-58fb7880-5554-11e9-81f6-bef1c6733abb.png)

**Comment by andrewlewis** [comment]
If you handle the `onTimelineChanged` event from the player, the second parameter `manifest` should be an instance of `HlsManifest` when using `HlsMediaSource`. It looks like the information you need is contained within there.

**Comment by souravbasu14** [comment]
@andrewlewis Thanks for the reply. With this we are able to get all the segments which are been downloaded. But how do i know which particular segment it is currently playing ? Similar to this [link](https://github.com/video-dev/hls.js/issues/524)

**Comment by andrewlewis** [comment]
Looks like this information isn't readily available I'm afraid (see also #4905).
