### ISSUE TITLE
Headset Fastforward and Rewind not working

### ISSUE THREAD

**Issue by zjamshidi** [google/ExoPlayer#5719]
Hello All
I have a music player app using ExoPlayer, PlayerNotificationManager, MediaSessionCompat, and MediaSessionConnector. Everything works fine, the music gets played, the notification is shown. Even I can play/pause the player using headset buttons but rewind and fastforward are not working. 

here is my code:
```
// initializing exoPlayer
			exoPlayer = ExoPlayerFactory.newSimpleInstance(this);

            DataSource.Factory dataSourceFactory = ((StoryShotsApp) getApplication()).buildDataSourceFactory();

            ExtractorsFactory extractorsFactory = new DefaultExtractorsFactory().setConstantBitrateSeekingEnabled(true);

            // This is the MediaSource representing the media to be played.
            MediaSource audioSource = new ExtractorMediaSource.Factory(dataSourceFactory)
                    .setExtractorsFactory(extractorsFactory)
                    .createMediaSource(uri);
            exoPlayer.addListener(eventListener);
            exoPlayer.prepare(audioSource);
```
and
```
// initializing mediaSession and mediaSessionConnector
			mediaSession = new MediaSessionCompat(this, getPackageName());
            mediaSession.setActive(true);

            mediaSessionConnector =
                    new MediaSessionConnector(mediaSession, new DefaultPlaybackController(10000, 10000,
                            MediaSessionConnector.DEFAULT_REPEAT_TOGGLE_MODES) {

                        @Override
                        public void onPlay(Player player) {
                            checkAndSetPlayPause(true);
                        }

                        @Override
                        public void onPause(Player player) {
                            setPlayPause(false);
                        }

                        @Override
                        public void onFastForward(Player player) {
                            seekBy(+10);
                        }

                        @Override
                        public void onRewind(Player player) {
                            seekBy(-10);
                        }

                        @Override
                        public long getSupportedPlaybackActions(Player player) {
                            if (player == null || player.getCurrentTimeline().isEmpty()) {
                                return 0;
                            }
                            return PlaybackStateCompat.ACTION_PLAY_PAUSE
                                    | PlaybackStateCompat.ACTION_PLAY
                                    | PlaybackStateCompat.ACTION_PAUSE
                                    | PlaybackStateCompat.ACTION_FAST_FORWARD
                                    | PlaybackStateCompat.ACTION_REWIND;
                        }
                    });
            mediaSessionConnector.setPlayer(exoPlayer, null, null);
```

### [REQUIRED] Searched documentation and issues
https://medium.com/google-exoplayer/the-mediasession-extension-for-exoplayer-82b9619deb2d
https://developer.android.com/guide/topics/media-apps/mediabuttons

### [REQUIRED] Question
As you see I made the player seekable. I implemented the fast-forward and rewind methods. I expect to fast forward the player by double tapping on headset button and rewind by triple tapping it. What should I add to my code? Do i need MediaButtonReceiver? Do you have any sample?

**Comment by marcbaechinger** [comment]
The `MediaSessionConnector` behaves like the default `MediaSessionCompat.Callback` implementation behaves. This means a single click on the media button is handled as a play/pause event. A double click on the media button is handled as a skipToNext event. Besides this there are no further mappings.

To provide a consistent default behavior, this behavior is intentional according to https://developer.android.com/guide/topics/media-apps/mediabuttons , the link to the docs you added above. To change this default behaviour you'd have to override `MediaSession.Callback.onMediaButtonEvent`. Because the callback is provided by the `MediaSessionConnector` you can not do this in the current release version. But we have already synced a change to the dev-2 branch, which allows you to provide your own `MediaButtonEventHandler` and make use of it by setting it with the [setMediaButtonEventHandler](https://github.com/google/ExoPlayer/blob/dev-v2/extensions/mediasession/src/main/java/com/google/android/exoplayer2/ext/mediasession/MediaSessionConnector.java#L462).

**Comment by zjamshidi** [comment]
Thanks Marc for your response. I will try overriding SkipToNext and let you know the result.

**Comment by zjamshidi** [comment]
Overriding SkipToNext works perfectly. Thanks...
I will wait for next release to implement rewind.

Good Luck

**Comment by zjamshidi** [comment]
Actually, rewind is very important for us. Do you have any estimate about when would you release the next version?

**Comment by zjamshidi** [comment]
@marcbaechinger  would you please help me again? Rewind functionality is very important for us.
do you have any estimation when would you release next version with "setMediaButtonEventHandler" method?
I just pulled dev-v2 branch, but it seems dev-v2 branch is not meargable with release-v2. I got lots of compile error. how could I use this new  "MediaSessionConnector" before next release?

thanks in advance...
