### ISSUE TITLE
Video duration not reported correctly if HLS video is played directly from Media Playlist

### ISSUE THREAD

**Issue by Arqu** [google/ExoPlayer#572]
If you play an HLS Video that doesn't have a MasterPlaylist, that is you directly start with a media playlist (for example the sample in the demo Apple TS media playlist) it reports the duration 0 because setMediaPlaylist is never called in the HLSChunkSource, I tested a quick fix by adding `durationUs = variantPlaylists[0].durationUs;` to the `if (playlist.type == HlsPlaylist.TYPE_MEDIA) {` in the constructor.

**Comment by ojw28** [comment]
This was a recent regression. Thanks for the report.
