### ISSUE TITLE
Controller layout visual glitch  on Xiaomi redmi not 5 pro 

### ISSUE THREAD

**Issue by amjadmasri** [google/ExoPlayer#5722]
Issue description
we have a simple activity with a full screen player view, everything works well, but one user with a Xiaomi Redmi note 5 pro reported a visual glitch 
![img_20190403](https://user-images.githubusercontent.com/26228083/55474970-4d26b980-561b-11e9-87f9-20388425e28c.png)

when it is supposed to look like this 
![Screenshot_20190403-135036](https://user-images.githubusercontent.com/26228083/55474997-6465a700-561b-11e9-94b7-71f77ed16a2a.png)

the controller layout is being duplicated on the black background on the sides. 
is this a bug on this specific device ?
and what is the reason  this is happening ? 

this is the XMLof the activity
```
<android.support.constraint.ConstraintLayout 
   xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".vod.activities.PlayerActivity">
    <com.google.android.exoplayer2.ui.PlayerView
        android:id="@+id/player_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:controller_layout_id="@layout/exo_playback_control_view"
        app:player_layout_id="@layout/go_player_layout"
        app:show_buffering="always"
        app:show_timeout="10000"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent">
    </com.google.android.exoplayer2.ui.PlayerView>
</android.support.constraint.ConstraintLayout> 
```

Version of ExoPlayer being used
2.9.4

 Device(s) and version(s) of Android being used
Xiaomi Redmi note 5 pro with android 8.1.0

**Comment by ojw28** [comment]
This looks like a device specific issue (probably related to the compositor). I'm not sure there's much we can do about it, and you should probably report it to the device manufacturer. One thing you should check is whether you're setting any video backgrounds to transparent. I've seen cases where this causes problems before.

Closing, since I don't think this is an ExoPlayer issue.

**Comment by amjadmasri** [comment]
thank you, the issue was as you said, the activity had a null background 
and when changed to a black background the issue was solved
many thanks.
