### ISSUE TITLE
Exoplayer - Change different UI for Audio and Video at runtime

### ISSUE THREAD

**Issue by varun7952** [google/ExoPlayer#5723]
I am using Exoplayer in Recyclerview where i am playing Audio and Video files successfully without any issue but i need to change layout of Exoplayer at minimal like this
https://i.stack.imgur.com/MrKvK.png

My current layout look like this which is same when audio or video is playing.i also tried in XML set surface_type=none but that's doesn't even help.
https://i.stack.imgur.com/9YNU2.png
Exoplayer V 2.9

**Comment by marcbaechinger** [comment]
I think you need to do that by having two different views/viewHolders for video and audio and act accordingly in your `RecyclerView.Adapter`. You can find a [Medium article around customizing the UI of ExoPlayer](https://medium.com/google-exoplayer/customizing-exoplayers-ui-components-728cf55ee07a). 

So when the recycler view calls `onCreateViewHolder` you need to decide whether it's audio or video and then inflate your layout for the given item in your `RecyclerView.Adapter`. So you have two different layout files which you inflate for either audio or video. You can then configure each layout file with the hints provided by the Medium post above.

**Comment by varun7952** [comment]
So that's means i can't make it with single one ?

**Comment by marcbaechinger** [comment]
You can probably use a single layout file with two `PlayerViews`. In `onBindViewHolder` you can then hide/show one or the other according to the file type. 

For the audio file you can either set an artwork for the player view (for MP3/MP4 metadata artwork are shown) or use only the `PlayerControlView` instead of the `PlayerView`.

**Comment by varun7952** [comment]
```
player = ExoPlayerFactory.newSimpleInstance(context);
            playerView.setPlayer(player);
            playerView.setUseArtwork(true);  // SHOULD I REMOVE THIS FOR AUDIO      
            player.addListener(componentListener);
            player.setPlayWhenReady(playWhenReady);
            player.seekTo(currentWindow,playbackPosition);
            player.clearVideoSurface();
            MediaSource mediaSource = buildMediaSourceNew(uri);
            player.prepare(mediaSource);
```

**Comment by marcbaechinger** [comment]
The documentatin says:

```
 Sets whether artwork is displayed if present in the media.
```

So if you have artwork in the media you want to set true here.

**Comment by varun7952** [comment]
I need to set artwork but in minimal layout like this 
https://i.stack.imgur.com/MrKvK.png
which i am not able to achieve with exoplayer which shows black screen when audio is playing. Can i get google play music like minimal layout with Exoplayer?

**Comment by varun7952** [comment]
I need to show minimal layout in recyclerview with single Exoplayer layout/instance for audio (Video is working fine) like this https://i.stack.imgur.com/MrKvK.png. So whenever there is an audio file exoplayer turn into minimal layout without black screen which is currently like this  https://i.stack.imgur.com/9YNU2.png need to achieve like this  https://i.stack.imgur.com/MrKvK.png

**Comment by marcbaechinger** [comment]
If you want to have the view for audio look like the notification you posted in the screenshot above you are probably better off to just use the `PlayerControlView`. 

Create a layout file with both, a 'PlayerView' and a 'PlayerControlView'. Both have a `setPlayer(Player) ` method. So if you need to play a video you set the player in the `PlayerView` and hide the `PlayerControlView`. In the other case you hide the `PlayerView` and show the `PlayerControlView` to which you set the player.

You can customize the look of the `PlayerControlView` as explained in the [medium article about customizing UI compnents](https://medium.com/google-exoplayer/customizing-exoplayers-ui-components-728cf55ee07a).

Alternatively you can make your adapter create different `ViewHolders` for audio or video.

If you search the web for "Android recycler view multiple view types" you will find stackoverflow articles or tutorials around the topic. I can't really help you some further with UI development I'm afraid.

**Comment by varun7952** [comment]
Can you please share some examples for audio layout like above screen shot on stack or on web?
