### ISSUE TITLE
Can't cache ManifestFetcher

### ISSUE THREAD

**Issue by osemen-remit** [google/ExoPlayer#573]
`ManifestFetcher` takes `UriDataSource` as a param but `CacheDataSource` extends `DataSource` so it can't be used by `ManifestFetcher`.

**Comment by ojw28** [comment]
Why don't you just hold on to the parsed manifest object in memory? That seems more efficient than parsing it repeatedly from local storage to me?

Or is the goal to cache between the process being killed and later restarted? In which case how long would you cache them for, given they may change on the server, or would you use the http response headers to determine that?

Thanks!

**Comment by osemen-remit** [comment]
My aim is to do disc caching for video and make it possible to watch recently played videos in offline mode. In case video is chunked video itself might be cached but it is not possible to play it in offline because playlist can't be downloaded. 

Of course it should work if app was killed. In our case video does not change. It might be deleted in this case we cleanup url to playlist from db.

**Comment by edisonw** [comment]
You can just use OkHttpDataSource with an interceptor and Cache to do that.

**Comment by ojw28** [comment]
I'm somewhat unclear whether ExoPlayer 2.x resolves this issue for you, but things have changed so much in this area that I'm going to close it as obsolete. Please file a new issue if functionality is still lacking in 2.x. Thanks!
