### ISSUE TITLE
New bug on Android P: Offline DRM License error

### ISSUE THREAD

**Issue by kvillnv** [google/ExoPlayer#5730]
### Issue description
I am getting an error while trying to play Downloaded Dash content with Widevine offline Drm License. This occurs only on Android P.
The same content works on Android N and O using the same App.
We have never seen this error before.

```
2019-03-15 12:02:34.567 1075-15018/? E/DefaultDrmSession: Error trying to restore Widevine keys.
    android.media.MediaDrm$MediaDrmStateException: Failed to restore keys: General DRM error
        at android.media.MediaDrm.restoreKeys(Native Method)
        at com.google.android.exoplayer2.drm.FrameworkMediaDrm.restoreKeys(FrameworkMediaDrm.java:183)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.restoreKeys(DefaultDrmSession.java:367)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.doLicense(DefaultDrmSession.java:328)
        at com.google.android.exoplayer2.drm.DefaultDrmSession.acquire(DefaultDrmSession.java:164)
        at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.acquireSession(DefaultDrmSessionManager.java:559)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1075)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:552)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:536)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:303)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)
```
(see attached log files)

### Version of ExoPlayer being used
Exoplayer 2.9.6

### Device(s) and version(s) of Android being used
5 Android TV devices: 
* 1 on android N (No Error)
* 2 on Android O (No Error)
* 2 on Android P (Errors occurs only on these devices)

### Reproduction steps
I ran our app our 5 Android TV devices:
I Downloaded the same Dash contents and their Widevine offlineLicenseKeySetIds, using only Exoplayer library (DownloadService, DashUtils, OfflineLicenseHelper, etc..)
Everything was downloaded at the same time.
Then I played the content offline using cacheDataSource and DefaultDrmSessionManager with MODE_PLAYBACK and offlineLicenseKeySetId. 
(We have been successfully doing this process for almost 1 year on Android N and O devices.)

* On the Android N device and the 2 Android O devices, 100% of the downloaded videos is playable (as usual)
* On the 2 Android P devices more than 50% of videos is not working and give the attached error logs. 
The video and audio tracks are 100% downloaded. 
The error only occurs in the DRM decryption process.
If a video does not work, even after a restart it will not work. And videos that work always work.
We can have one Video working on a P device, and not working on the other P device, but always working on the N and O.

**-Have you ever seen this error ?
-Do you have an explanation about what is actually happening?**

Any help/fix would be appreciated,
Thanks.

[Debug Version with exoplayer logs.txt](https://github.com/google/ExoPlayer/files/3045053/Debug.Version.with.exoplayer.logs.txt)

[Detailed android logs.txt](https://github.com/google/ExoPlayer/files/3045062/Detailed.android.logs.txt)

**Comment by andrewlewis** [comment]
```
04-04 13:37:40.668  3132  6236 E drm_wvoemcrypto_tl: drm_WVOemCrypto_DeriveKeysFromSessionKey - Command was sent successfully to DeriveKeysFromSessionKey but actual operation failed (0x01050004),wvRC = 0
04-04 13:37:40.672  3132  6236 E drm_wvoemcrypto_tl: drm_WVOemCrypto_LoadKeys - widevine return code (0x0000001e)
04-04 13:37:40.672  3132  6236 E drm_wvoemcrypto_tl: drm_WVOemCrypto_LoadKeys - Load Key command failed due to SAGE issue (basicOut[0] = 0x01050004)
04-04 13:37:40.672  3132  6236 E oemcrypto_brcm_tl: [OEMCrypto_Loadkeys(SID=00000004): failed]
04-04 13:37:40.672  3132  6236 E WVCdm   : [crypto_session.cpp(845):LoadKeys] CryptoSession::LoadKeys: OEMCrypto_LoadKeys error=30
04-04 13:37:40.672  3132  6236 E WVCdm   : [cdm_engine.cpp(401):RestoreKey] CdmEngine::RestoreKey: restore offline session failed = 113
04-04 13:37:40.672  3132  6236 W WVCdm   : Returns UNKNOWN error for legacy status: 113
04-04 13:37:40.672  5761  8252 E MediaDrm-JNI: Illegal state exception: Failed to restore keys: General DRM error (-2000)
```

**Comment by andrewlewis** [comment]
@fredgc Please could you take a look at the error above? Thanks.

**Comment by ojw28** [comment]
Widevine issues go to @jefftinker now.

**Comment by kvillnv** [comment]
@jefftinker please let me know if there is anything else I can do to help.
And what's your first thought about this particular issue on P?

**Comment by fredgc** [comment]
You said that this happens on several devices, can you tell us which devices this happens on?

We would like clarification on what you mean by it always happens for a video.  If you download a license and find that it fails to load, can you delete that license and re-download it and play successfully?  Or do you think there is something special about a particular device and a particular content?

Are you able to capture the logcat from when the license is downloaded, and also when you try to replay it?  The problem probably happened when you first downloaded the license.

Are you willing to share the content with us?  It might be easiest if you send us the changes you made to ExoPlayer.
 
You can send it to dev.exoplayer@gmail.com and put "Issue #5730" in the subject.

**Comment by kvillnv** [comment]
We were able to confirm it was not an exoplayer bug.

**Comment by asw0697** [comment]
Basically, Android TV is a smart platform from Google built around the Android operating system. Users can stream content to your TV via apps, both free and paid, using your internet connection. Nowadays [Sony TV Repair Dubai](https://f2help.com/sony-tv-repair/) use to provide all the user guide and helpdesk for Smart TV.

**Comment by shanosh** [comment]
@kvillnv we're facing the same issue in our app. are you able to share with us how you managed to solve this? thanks :)
