### ISSUE TITLE
Generate module POM files to include licenses node

### ISSUE THREAD

**Issue by ToxicBakery** [google/ExoPlayer#5731]
### Issue description
Currently, the Maven POM is generated without a licenses node for all modules. Because of this, it's difficult for consumers to properly display licensing when attempting to do so by displaying the modules defined license information.

### Reproduction steps
Review the pom files of various ExoPlayer modules on Bintray such as the main module and note the lack of a licenses node.

https://bintray.com/google/exoplayer/exoplayer/2.9.6

### Link to test content
N/A

### A full bug report captured from the device
N/A

###  Version of ExoPlayer being used
2.9.6

###  Device(s) and version(s) of Android being used
N/A

**Comment by ToxicBakery** [comment]
Off topic but semi-related, this issue would have been easier to resolve and likely would never have occurred if the maven-publish plugin was used directly. Additionally, it's disappointing to see that Bintray clearly doesn't care if artifacts are well defined by their POM files. I guess I'll continue to keep avoiding jcenter as much as possible in my builds.

**Comment by andrewlewis** [comment]
We're hoping to move to Google Maven soon (#5246).
