### ISSUE TITLE
Add Gaps/Empty SilenceMediaSource with custom duration to ConcatenatingMediaSource

### ISSUE THREAD

**Issue by shaji-Dev** [google/ExoPlayer#5735]
Hi,

I'm building a ConcatenatingMediaSource for audio tracks that are placed in a timeline. I need to put Gaps or Silent tracks with custom duration between them, does the library provide a DummyMediaSource of some sort with custom duration that I can concatenate between the tracks in order to have these gaps? 

If not, could you suggest a solution for this problem. Thank you.

**Comment by andrewlewis** [comment]
It's possible to write a `SilenceMediaSource` that inserts silence with a given duration, but we don't provide such a component currently. I'll mark this as an enhancement to add one to the core library.

**Comment by shaji-Dev** [comment]
In the meanwhile if you have any suggestion on how to implement my own SilenceMediaSource that inserts silence would be much appreciated.

Thank you.
