### ISSUE TITLE
ClippingMediaSource with delay or start window offset

### ISSUE THREAD

**Issue by shaji-Dev** [google/ExoPlayer#5737]
Hi,

It would be nice to have a parameter that adds a delay to the ClippingMediaSource, apart from clipping it, tell when to start.

Let's say we have a ConcatenatingMediaSource with multiple ClippingMediaSource in it. I would like to add a delay to the first and third ClippingMediaSource. It would be great to have:

`ClippingMediaSource(mediaSource, startPositionUs, endPositionUs, startOffsetUs)`
startOffsetUs - Microseconds until the window starts.

Thanks.

**Comment by tonihei** [comment]
Can you clarify what `startOffsetUs` is supposed to do exactly?

Is it a period of silence before the next video starts? If so, please see #5735.
Or is it the start position in the clipped window. For example, clipped from 10 to 50, but playback starts at 30.

**Comment by shaji-Dev** [comment]
It is what's described in the other feature request you referred to. Sorry for the confusion. I will close this issue then.
