### ISSUE TITLE
2.8.0 memory leak

### ISSUE THREAD

**Issue by barron9** [google/ExoPlayer#5738]
Memory usage soars after some start stops,even a proper "release" and "null"ing the player. Anyone experiencing this on 2.8.0?

Regards

**Comment by ojw28** [comment]
Closing due to lack of required information. If you're going to file an issue, please take the time to fill out the issue template correctly. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md).
