### ISSUE TITLE
downstreamRendererCount at HLS documentation code should be 2

### ISSUE THREAD

**Issue by tai2** [google/ExoPlayer#574]
Below is a code fragment from the developer guide.

```
DefaultBandwidthMeter bandwidthMeter = new DefaultBandwidthMeter();
DataSource dataSource = new DefaultUriDataSource(userAgent, bandwidthMeter);
HlsChunkSource chunkSource = new HlsChunkSource(dataSource, url, manifest, bandwidthMeter,
    variantIndices, HlsChunkSource.ADAPTIVE_MODE_SPLICE, audioCapabilities);
HlsSampleSource sampleSource = new HlsSampleSource(chunkSource, true, 3, REQUESTED_BUFFER_SIZE,
    REQUESTED_BUFFER_DURATION_MS);
MediaCodecVideoTrackRenderer videoRenderer = new MediaCodecVideoTrackRenderer(sampleSource,
    MediaCodec.VIDEO_SCALING_MODE_SCALE_TO_FIT);
MediaCodecAudioTrackRenderer audioRenderer = new MediaCodecAudioTrackRenderer(sampleSource);
```

If I figured out correctly, HlsSampleSource's *downstreamRendererCount* should be 2, because two renderers are attached to the source in this case.

And the same thing is found in the demo sample code. HlsSampleSource is used from 4 renderers, but only 2 of those are MediaCodecTrackRenderer. So downstreamRendererCount should be 2 as well, right? Or please tell me what *downstreamRendererCount* means. It's undocumented.

**Comment by ojw28** [comment]
downstreamRendererCount no longer exists in the dev branch. We got rid of it because it was error-prone to set it correctly (as demonstrated in the developer guide - as you rightly point out!).

We'll update the developer guide to remove the count when we next release.

**Comment by ojw28** [comment]
I've fixed this to be correct in the meantime, since it might be a non-trivial amount of time before the next release to master. Thanks!
