### ISSUE TITLE
Ability to customize a Socket

### ISSUE THREAD

**Issue by ened** [google/ExoPlayer#5745]
### [REQUIRED] Use case description
ExoPlayer could be used in Apps that support multi-path networking, which means part of the applications data comes from network A, while other data comes from network B.

A typical use case could be a WiFi connection with a network camera, while the rest of the system still uses 4G for notifications & other Apps.

On Android, you can bind the entire process to a networkId. This, however, kills any future Sockets that connect to hosts on other networks.

Instead, developers could use the [bindSocket](https://developer.android.com/reference/android/net/Network.html#bindSocket(java.net.Socket)) method to selectively bind sockets to network IDs.

Currently, ExoPlayer seems to create Sockets based on the default [SocketFactory](https://developer.android.com/reference/javax/net/SocketFactory#getDefault()).

### Proposed solution

A way to specify a custom, ExoPlayer only, SocketFactory which is used in all network-based players. 

### Alternatives considered

It could be done using the **okhttp** extension.

**Comment by ojw28** [comment]
You can already implement your own `HttpDataSource.Factory` or `DataSource.Factory` to customize what happens in the network layer. Is that not sufficient for some reason?

**Comment by ened** [comment]
Yes that should be covering it. Apologies I didn't check that in detail.
