### ISSUE TITLE
Automatically show closed captioning/hard of hearing track based on accessibility settings

### ISSUE THREAD

**Issue by sobbe81** [google/ExoPlayer#5749]
Hi,

I'm using ExoPlayer for playback of DASH-content. I'm looking for a way to 
 * Pick a certain language as default for subtitles, now done by using setPreferredTextLanguage
 * Pick cc/hard of hearing track if this setting in accessibility settings is enabled.   

The DefaultTrackSelector has an API to setPreferredTextLanguage which works fine for displaying subtitle tracks.

However, my app needs to support both subtitles and closed captions and my problem is that if I use setPreferredTextLanguage it will always display the closed captions since these are using the same language code.

The CaptioningManager, https://developer.android.com/reference/android/view/accessibility/CaptioningManager, offers an API to read accessibility settings. From what I understand, ExoPlayer uses this setting to determine the styling of the closed captions but not to determine whether text should be shown or not. 

Is there any way to get the ExoPlayer automatically enable closed captioning based on accessibility settings? And that setPreferredTextLanguage only applies to subtitles and not closed captions?

Thanks,
Martin

**Comment by tonihei** [comment]
Thanks for the detailed description of the problem. I think there are two enhancements in here that need to be addressed:

 1. Automatically select closed captions if `CaptioningManager.isEnabled()` is true. This should only be done if a closed caption track for `CaptioningManager.getLocale()` is available. Or the closed caption track has no language and the `selectUndeterminedTextLanguage` option is enabled.
 2. If the `preferredTextLanguage` option is set and multiple matching text tracks are found, choose the closed caption track if `CaptioningManager.isEnabled()` is true, and the subtitle track otherwise.

Does that summarize your proposal correctly?

**Comment by sobbe81** [comment]
Yes, that's sounds like it would solve my problem.

Just a clarification for one scenario:
if `CaptioningManager.isEnabled()` is false and `preferredTextLanguage` is set to "swe" and there is a closed captioning track, i.e. AdaptationSet with role=caption, available with language code "swe" this track would not be displayed. Correct?

**Comment by tonihei** [comment]
Yes, that's my understanding of the `isEnabled` flag.

**Comment by sobbe81** [comment]
Great!

**Comment by ojw28** [comment]
It should also be possible for apps to do everything that they need in the case where they get subtitle/caption settings from somewhere other than `CaptioningManager` (e.g. for API levels prior to 19, where `CaptioningManager` doesn't exist, or for apps that store their users' preferences in the cloud to sync them across multiple platforms).

So I think `setPreferredTextLanguage` probably needs generalizing somehow to also allow preferred (and/or allowed) role flags. Exactly how that's done probably requires some thought. Once it's done, apps should be able to easily map `CaptioningManager` settings onto this generalized API. Whether we change the default behavior of `DefaultTrackSelector` is then somewhat less important (although quite possibly still worth doing!).

**Comment by tonihei** [comment]
This is auto-enabled now and also be set triggered manually by using `setPreferredTextLanguageAndRoleFlagsToCaptioningManagerSettings`.
