### ISSUE TITLE
droppedFrames happens in 2.0 playback speed

### ISSUE THREAD

**Issue by ItsRay** [google/ExoPlayer#5752]
### [REQUIRED] Content description
When I play my video source in 2.0 playback speed by adding this line `
player.setPlaybackParameters(new PlaybackParameters(2.0f));
`, the video is not smooth and `droppedFrames` shows in log. 
According to this [reply](https://github.com/google/ExoPlayer/issues/5703#issuecomment-480488209), I have tried building a release apk. This works fine for some devices. Videos in `OPPO A77` are very smooth now, but some devices still have this problem. And I think some of these devices have better performance than `OPPO A77`. 

When I played the provided content in playback 2.0 speed on some devices which have this problem, the time showed in the video goes in unpredictable speed, whether it always goes in the same speed on other devices. 

I checked the memory usage and CPU usage is not really high in this devices. CPU usage is about 15% and memory usage is about 85MB. But I am not sure if this is important.

### [REQUIRED] Link to test content
Some of 1080p source. A sample is provided by email.

### [REQUIRED] Version of ExoPlayer being used
2.9.6

### [REQUIRED] Device(s) and version(s) of Android being used

Devices: 
  - Moto Nexus 6 (Android 7.1.1)
  - SONY Xperia Z5 E665 (Android 7.1.1)
  - Mi Note 2 (Android 8.0.0)

**Comment by ojw28** [comment]
This is most likely just a performance limitation of the devices in question. Closing for now.
