### ISSUE TITLE
Problem with mp4 in 2.9.6 works in 2.8.4

### ISSUE THREAD

**Issue by makvasic** [google/ExoPlayer#5753]
On 2.8.4 mp4 stream was working fine after updating to 2.9.6 I get `UnrecognizedInputFormatException: None of the available extractors...`
It's basic implementation of exoplayer in my code
```
ExtractorMediaSource.Factory(defaultDataSourceFactory)   
        .createMediaSource(Uri.parse(videoUrl))
```
But the same behavior is in demo app.

This is the [link](http://multimedia.dizajn-akademija.com/sr///Advanced_JavaScript_i_Ajax/multimedijaFinal/AJSAJ_04_01.mp4?key=e6e23905b11a87887c8b6872060a2705_ita_18&idie=4203195) in question.

**Comment by ojw28** [comment]
The link provided gives a 404 for me. Please provide a working test stream; thanks!

**Comment by ojw28** [comment]
Closing because a working test stream wasn't provided.
