### ISSUE TITLE
Access-Control-Allow-Origin' header  error in IMA Extention

### ISSUE THREAD

**Issue by DasJhaman** [google/ExoPlayer#5754]
### [REQUIRED] Searched documentation and issues

No solution found.

### [REQUIRED] Question

I am using IMA extention in exoplayer for Ads, getting following error while loading ads.
The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'

Some time its working some time its not working.

We have remove wildcard from Access control allow origin, still i am facing this issue.

Kindly any one help me out whats going wrong

**Comment by andrewlewis** [comment]
Please see https://developers.google.com/interactive-media-ads/docs/sdks/html5/cors (this is for the HTML5 IMA SDK but it should apply here too). If you've followed those instructions and it still doesn't work, maybe the response is being cached somewhere?
