### ISSUE TITLE
exoplayer.dev certificate is not trusted

### ISSUE THREAD

**Issue by bjitivo** [google/ExoPlayer#5758]
### [REQUIRED] Issue description
Describe the issue in detail, including observed and expected behavior.

On multiple systems I am using, I am finding it impossible to view exoplayer documentation from exoplayer.dev due to an security certificate issue.

I had previously been able to view the classes reference doc, which I believe must have been hosted on exoplayer.dev previously since I get to it via the README.md file of the exoplayer github source and that has not changed in several months.

### [REQUIRED] Reproduction steps
Describe how the issue can be reproduced, ideally using the ExoPlayer demo app
or a small sample app that you’re able to share as source code on GitHub.

Attempt to view:

https://exoplayer.dev/doc/reference

On any of these configurations:

- Firefox on Linux
- Google Chrome on Linux
- Safari on Mac OS X

Observe a security error rather than seeing the documentation.

**Comment by bjitivo** [comment]
Hm, I am thinking that this may be due to some kind of corporate network configuration that is messing up certificates.

**Comment by tonihei** [comment]
Just for you information: We did change our domain on Wednesday (10 April) from google.github.io/ExoPlayer to exoplayer.dev. So this is indeed a new change. It may be that the certificates haven't been updated yet everywhere and that's the reason for the issue you were seeing?

**Comment by bjitivo** [comment]
Thank you, yes it's working now, so I guess some information just needed some time to propogate its way through the internet to my corporate network ...
