### ISSUE TITLE
Player is accessed on the wrong thread

### ISSUE THREAD

**Issue by star-andy** [google/ExoPlayer#5759]
#### Refer to the address below  ,  Callbacks that want to increase frame time。
[https://blog.csdn.net/u010302327/article/details/79788705](https://blog.csdn.net/u010302327/article/details/79788705)

#### The figure below will prompt after adding。I would like to ask whether it will affect the program?
![image](https://user-images.githubusercontent.com/15726024/56009142-585fa080-5d11-11e9-98bc-ea34075eb609.png)

**Comment by erdemguven** [comment]
Yes, it will cause issues. ExoPlayer instances need to be accessed from a single thread only. In most cases, this should be the application’s main thread. 
https://exoplayer.dev/faqs.html#what-do-player-is-accessed-on-the-wrong-thread-warnings-mean

**Comment by ojw28** [comment]
We may also turn these warnings into crashes in a future release, to force developers to use our API correctly.
