### ISSUE TITLE
SimpleExoPlayerView - Hiding buffering in seekbar 

### ISSUE THREAD

**Issue by furkansenharputlu** [google/ExoPlayer#5765]
Version: 2.7.3

I don't want to see buffering in seekbar. How can I hide it ?

I just use default `SimpleExoPlayerView`:

```
playerView = findViewById(R.id.video_view);
```
```
<com.google.android.exoplayer2.ui.SimpleExoPlayerView
        android:id="@+id/video_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />
```

<img width="208" alt="Ekran Resmi 2019-04-13 19 48 29" src="https://user-images.githubusercontent.com/25665432/56082768-73233980-5e25-11e9-9a78-177b8894e467.png">

Thanks!

**Comment by mwolfe38** [comment]
You should update to use  PlayerView (SimplePlayerView is deprecated) and then turn showBuffering off via attribute
https://github.com/google/ExoPlayer/blob/release-v2/library/ui/src/main/java/com/google/android/exoplayer2/ui/PlayerView.java
See line 370 and 444

**Comment by ojw28** [comment]
It's a bit of a hack, but you can do it like this:
```
DefaultTimeBar timeBar = (DefaultTimeBar) playerView.findViewById(R.id.exo_progress);
timeBar.setBufferedColor(0x33FFFFFF);
```
In a future release we'll make it so you can set the buffered color as an attribute on `PlayerView`.
