### ISSUE TITLE
Stop trying to access AudioTrack.getLatency

### ISSUE THREAD

**Issue by SewizChow** [google/ExoPlayer#5769]
I use veridex to scan the apk,find in exoplayer is in greylist-max-p  
Reflection greylist-max-p Landroid/media/AudioTrack;->getLatency use(s):
       Lcom/google/android/exoplayer2/audio/AudioTrackPositionTracker;-><init>(Lcom/google/android/exoplayer2/audio/AudioTrackPositionTracker$Listener;)V

 public AudioTrackPositionTracker(Listener listener) {
    this.listener = Assertions.checkNotNull(listener);
    if (Util.SDK_INT >= 18) {
      try {
        getLatencyMethod = AudioTrack.class.getMethod("getLatency", (Class<?>[]) null);//this line
      } catch (NoSuchMethodException e) {
        // There's no guarantee this method exists. Do nothing.
      }
    }
    playheadOffsets = new long[MAX_PLAYHEAD_OFFSET_COUNT];
  }
can remove this ?..

**Comment by ojw28** [comment]
@andrewlewis - I think we should just stop trying to access getLatency on Q and above. It should be fine to rely on `AudioTrack.getTimestamp`. If it's not for certain use cases then (a) we should file platform bugs, and (b) I doubt getLatency is of much help for those use cases either.

**Comment by andrewlewis** [comment]
It seems to be quite common for devices not to provide an `AudioTimestamp` when beginning audio playback from a cold start. For example, we may not have a timestamp for hundreds of milliseconds when starting playout to a Bluetooth audio device. We don't currently have a good alternative to using the method.

`getLatency` will remain hidden but accessible to apps when Q launches (though it's restricted in Q preview -- see #5763 and [Internal: b/112561552]). The framework team are considering making it public and improving the way it works in the future (see [Internal: b/130237544]). I'll therefore close this issue as I don't think any action is required on the ExoPlayer side for now.

**Comment by SewizChow** [comment]
> considering

thanks..
