### ISSUE TITLE
Calling release() method in onPause sometimes blocks indefinitely

### ISSUE THREAD

**Issue by ptran-gpfw** [google/ExoPlayer#577]
[ExoPlayer#release()](https://github.com/google/ExoPlayer/blob/master/library/src/main/java/com/google/android/exoplayer/ExoPlayer.java#L330) sometimes doesn't return.

We have a log message for the state in the listener ExoPlayer.Listener@onPlayerStateChanged and its STATE_BUFFERING. Just to clarify, when we see STATE_BUFFERING sometimes release() works fine and sometimes it doesn't return. The test sequence is to start playback and then immediately tap Back to trigger onPause.

**Comment by ojw28** [comment]
Isn't this essentially the same as #528 (i.e. it's likely that you have custom components in your player that are incorrectly blocking the playback thread)?

**Comment by ptran-gpfw** [comment]
Question: In a worker thread (separate from main video player using ExoPlayer) I have another decoding session with some code that is decoding using MediaCodec directly (not via ExoPlayer). Is it possible this could interfere with ExoPlayer's playback thread?

**Comment by ptran-gpfw** [comment]
I thought I had solved #528 but I think you're right and its something in my code. I'm digging into the sequence of ExoPlayer calls that lead up to release(). This issue can be closed.
