### ISSUE TITLE
end of playback don't detected for a simple .mp4 media url

### ISSUE THREAD

**Issue by makazemi** [google/ExoPlayer#5773]
I have a playlist of mp4 and mp3 media file. I build mediaSource like this:
` DataSource.Factory dataSourceFactory = new DefaultDataSourceFactory(this,
                Util.getUserAgent(this, getString(R.string.app_name)));
        cacheDataSourceFactory = MyApplication.getInstance().buildDataSourceFactory();
        concatenatingMediaSource = new ConcatenatingMediaSource();
        for (int i = 0; i < getUris().size(); i++) {
            MediaSource mediaSource = new ExtractorMediaSource.Factory(cacheDataSourceFactory).
                    createMediaSource(getUris().get(i));
            concatenatingMediaSource.addMediaSource(mediaSource);
        }
`
My url of media are like this:
https://hw7.cdn.asset.aparat.com/aparat-video/0669e0a249abeede3774df5d246c9cab14037526-144p__78903.mp4
onPlayerStateChanged listener didn't detect STATE_ENDED.

**Comment by ojw28** [comment]
There is not enough information for us to provide help here. Please provide proper reproduction steps. Ideally in the form of a minimal demo app, provided as source code on GitHub, that reproduces the problem.

I did try playing the sample file you provided. It worked fine for me, including the transition to ended.

**Comment by makazemi** [comment]
I put my code in Github. https://github.com/makazemi/basicExoPlayer

**Comment by ojw28** [comment]
The project does not compile (e.g. it references classes that aren't present in the project, such as `com.struct.red.alltolearn.Utils.DownloadTracker`).

**Comment by makazemi** [comment]
Please Compile this project. This project compile correctly. https://github.com/makazemi/SampleExoPlayer

**Comment by ojw28** [comment]
This project compiles. I don't understand what the issue is though; everything seems to be working correctly, including transition to `STATE_ENDED` at the end of the last video.

Are you trying to detect when playback moves from one item to the next? If so then it's working as intended that the player doesn't transition to `STATE_ENDED` (because it's still playing something). See https://github.com/google/ExoPlayer/issues/4728 for more details.

**Comment by makazemi** [comment]
I though that every video of playlist has `STATE_ENDED` state. But I realized that when last video seek to end, STATE_ENDED` state is triggered. Is there a way that I implement complete listener for playback?

**Comment by ojw28** [comment]
`STATE_ENDED` is the state of the player, not the state of a video. If the player still has content to play, it is not ended. As per my answer above, #4728 provides more details and explains how to detect playback moving from one item to the next in a playlist.
