### ISSUE TITLE
Long Delay happens after seek

### ISSUE THREAD

**Issue by AlphaCircle** [google/ExoPlayer#5777]
### [REQUIRED] Searched documentation and issues
Tell us where you’ve already looked for an answer to your question. It’s
important for us to know this so that we can improve our documentation.

### [REQUIRED] Question
Describe your question in detail.

Hello
I have one issue of slow play of exoplayer after seek operation. I am running 2 players. One player runs and pause in certain place, then the second player seeks to the place of the file the 1st one paused and start play from the place. I am playing the local file in a local storage, not from network.

Roughly it works fine. But one issue happens. The 2nd exoplayer gets slow at the 2nd and/ or 3rd frame and them get back to normal speed. Specifically the video has, for instance, 60 fps, then one frame time is roughly 17 ~ 20 ms. The 2nd exoplayer shows the 1st frame after seek fast but the 2nd or 3rd frame is shown after  roughly 200 ~ 300 ms, and then it comes to normal speed of 17 ~ 20ms. When I look at the buffering, no problem. It has already has the buffered data of 2nd and 3rd frame. But why it gets slow at 2nd or 3rd frame? It is related to codec? With various buffing time, that seems not related to this issue. 

The video image seems paused a little bit and runs normal again. It is annoying. Please help me out to find the reason.

Thanks.

**Comment by ojw28** [comment]
Is the fact there are two players relevant, or does the issue also happen when seeking with one player?

**Comment by AlphaCircle** [comment]
First of all, I am using the version 2.9.4.

That happens in either way. For instance, 1) A player (current player) --> B player (later player) or 2) B player (current player) --> A player (later player).  In 1) case, B player shows the slow frames. In 2) case, A player shows the slow frames. When I look at the issue of #2533, which is similar question to mine, I thought that might be related to Surface operation. But I don't see why the surface of later player gets slow. 

When I give a delay between 1st rendering of later player and its start, I realized that the later player goes into Ready in Pause after 1st rendering callback. In this case, I keep the current player still running before the later player fires to start.

Thanks
Tasik

**Comment by ojw28** [comment]
A few more questions:
* What about if you only have one player, and you perform a seek?
* Does disabling audio help. Obviously there will be no audio if you do this. The question is whether it fixes the issue affecting the rendering of the 2nd and 3rd frames. You can disable audio with the following, where `trackSelector` is a `DefaultTrackSelector` instance:

```
DefaultTrackSelector.ParametersBuilder parameters =
    trackSelector.getParameters().buildUpon();
for (int i = 0; i < player.getRendererCount(); i++) {
  if (player.getRendererType(i) == C.TRACK_TYPE_AUDIO) {
    parameters.setRendererDisabled(i, true);
  }
}
trackSelector.setParameters(parameters);
```

**Comment by ojw28** [comment]
Closing due to lack of follow-up.
