### ISSUE TITLE
Stop playing on manifest update

### ISSUE THREAD

**Issue by DarkAnakin** [google/ExoPlayer#5778]
Before filing a content issue:
------------------------------
- Search existing issues, including issues that are closed.
- Consult our supported formats page, which can be found at
  https://google.github.io/ExoPlayer/supported-formats.html.
- Try playing your content in the ExoPlayer demo app. Information about the
  ExoPlayer demo app can be found here:
  http://google.github.io/ExoPlayer/demo-application.html.

When reporting a content issue:
-----------------------------
Fill out the sections below, leaving the headers but replacing the content. If
you're unable to provide certain information, please explain why in the relevant
section. We may close issues if they do not include sufficient information.

### [REQUIRED] Content description
Live dash streaming

### [REQUIRED] Link to test content
I cannot provide a link but you can find the logcat with the manifests requested by exoplayer with timestamp and naming manifest_xxxx.mpd.
[logcat.txt](https://github.com/google/ExoPlayer/files/3095996/logcat.txt)
[manifest_1555599136232.mpd.txt](https://github.com/google/ExoPlayer/files/3096012/manifest_1555599136232.mpd.txt)
[manifest_1555599136327.mpd.txt](https://github.com/google/ExoPlayer/files/3096013/manifest_1555599136327.mpd.txt)
[manifest_1555599136395.mpd.txt](https://github.com/google/ExoPlayer/files/3096014/manifest_1555599136395.mpd.txt)
[manifest_1555599138448.mpd.txt](https://github.com/google/ExoPlayer/files/3096015/manifest_1555599138448.mpd.txt)
[manifest_1555599140435.mpd.txt](https://github.com/google/ExoPlayer/files/3096016/manifest_1555599140435.mpd.txt)
[manifest_1555599142446.mpd.txt](https://github.com/google/ExoPlayer/files/3096017/manifest_1555599142446.mpd.txt)
[manifest_1555599144419.mpd.txt](https://github.com/google/ExoPlayer/files/3096018/manifest_1555599144419.mpd.txt)
[manifest_1555599146426.mpd.txt](https://github.com/google/ExoPlayer/files/3096019/manifest_1555599146426.mpd.txt)
[manifest_1555599148437.mpd.txt](https://github.com/google/ExoPlayer/files/3096020/manifest_1555599148437.mpd.txt)

### [REQUIRED] Version of ExoPlayer being used
2.9.6

### [REQUIRED] Device(s) and version(s) of Android being used
nvidia shield tablet 7.1.1, nexus 5X

Hi, exoplayer stop playing live content on manifest update because it consider it ended.
Manifest change occured on manifest_1555599136232.mpd and manifest_1555599140435.mpd

Thanks

**Comment by ojw28** [comment]
The way the manifest is updating is invalid. In particular, the `Period@start` and `SegmentTemplate@presentationTimeOffset` values should not be changing across manifest updates. 

There was some confusion around this previously, specifically in the DASH IF IOP, however this has now been clarified. See this issue for more detail: https://github.com/google/ExoPlayer/issues/3457

**Comment by ojw28** [comment]
You can also take a look at the [DASH IF IOP 4.3 doc](https://dashif.org/docs/DASH-IF-IOP-v4.3.pdf), which says:

> MPD@availabilityStartTime and Period@start shall not be changed over MPD updates.

**Comment by DarkAnakin** [comment]
Thanks for the quick response
