### ISSUE TITLE
Different Location played by two Players with one position provided

### ISSUE THREAD

**Issue by AlphaCircle** [google/ExoPlayer#5781]
Hello.

I am using Version 2.9.4, the latest version and I am running 2 players (A and B player). The scenario is simple; A player runs and a certain event happens, then the position of A player with an additional value, for instance, 100ms, ( that is, "next position" = current A's position + 100ms) is provided to B player. B player is in Pause state till the next position is arrived by A player. When the A player arrives at the position, B player do the "seek to the position & start".  I am using the default Seek Parameter. 

When doing this test, I recognize B player is playing always a little bit lagged frame, comparing to the frame A player was showing at "the next position". The amount of lagging time is about 100 ~ 200ms. Is there something I need to do to compensate the current position of A or B player? Do I have to put an additional time (position in ms) to B player? Please help me out.

Thanks
Tasik

**Comment by ojw28** [comment]
I think you'd need to provide a small demo app (shared as source on GitHub) for us to be able to reproduce the problem and assist further.

**Comment by AlphaCircle** [comment]
Hello ojw28
I dug out this application and found that there is mistake in the media file. So I asked the person to regenerate the file with the supporting audio sampling and bit rate. This is not an issue of Exoplayer. 

Thanks for your support.
