### ISSUE TITLE
Correctly detect pause event when using PlayerControlView

### ISSUE THREAD

**Issue by rinav** [google/ExoPlayer#5783]
### [REQUIRED] Searched documentation and issues
- Searched all issues, but did not find the answer. #2627  #3397

### [REQUIRED] Question
Describe your question in detail.

When Using PlayerControlView How to properly detect Pause event?
        Can we intercept play, pause, rewind, fastforward, previous, next and seek before and then pass/call the default behaviour?

 When using Player.EventListener onPlayerStateChanged to detect pause, **Pause is also triggered when rewind, ff, next, previous and seek**

    case Player.STATE_READY:
        status = playWhenReady ? PlaybackStatus.PLAYING : PlaybackStatus.PAUSED;

         if (status.equals(PlaybackStatus.PAUSED)) {
            //Timber.d("PPPPPPAAAAAAUUUUUUSSSSSSEEEEEE");
         }
         break; 

Also there is no way to add clickListeners on exo controller UI components for `exo_rew, exo_ff, exo_play, exo_pause` etc... If I override it, then I loose the default behavior and click events does not work.

**Comment by ojw28** [comment]
Does this do what you need:
```
playerView.setControlDispatcher(new DefaultControlDispatcher() {
  @Override
  public boolean dispatchSetPlayWhenReady(Player player, boolean playWhenReady) {
    // You can modify this code to call through to the player or not.
    player.setPlayWhenReady(playWhenReady);
    // Return true if you called through to the player, and false otherwise.
    return true;
  }
});
```
Note you can also override other methods in `DefaultControlDispatcher` to intercept other types of calls on the player.
