### ISSUE TITLE
Synchronizing ExoPlayers with multiple DASH sources to different SurfaceViews

### ISSUE THREAD

**Issue by rishun-fsi** [google/ExoPlayer#5787]
Hello,

I want to be able to play media from multiple DASH sources to different SurfaceViews.

I've been able to play the sample using separate SimpleExoPlayer instances, but there isn't a way to synchronize them. 

Here is my sample code. 
[exo-multi-test.zip](https://github.com/google/ExoPlayer/files/3102628/exo-multi-test.zip)

Is there a way I can synchronize VideoView (SimpleExoPlayer) instances from my sample code?

Thanks in advance for any help!

**Comment by AquilesCanta** [comment]
Hi @rishun-fsi, there is no out-of-the-box functionality to do this. 

I suggest you look around in the issue tracker, there is some material about this already. For example, #2855 and #4261. If you have more specific questions, please post them below and I will reopen the issue, but the question is a bit broad to address in this issue tracker. A general Q&A site like StackOverflow may also be a good idea.
