### ISSUE TITLE
Losing PTS info due to adjusted timeUs

### ISSUE THREAD

**Issue by ferrytanu** [google/ExoPlayer#579]
PTS value is important to synch between ts frame and closed caption in webvtt format, as mentioned in the specification (https://tools.ietf.org/html/draft-pantos-http-live-streaming-16):
_Within each WebVTT header there MUST be an X-TIMESTAMP-MAP metadata header.  This header synchronizes the cue timestamps in the WebVTT file with the MPEG-2 (PES) timestamps in other renditions of the variant stream._

When missing PTS, it failed when MPEGTS > 0, and failed miserably in Live Video.

https://github.com/google/ExoPlayer/blob/dev/library/src/main/java/com/google/android/exoplayer/extractor/ts/TsExtractor.java#L192

Removing the timestampOffsetUs below, fix the problem. However, I believe there's must a good reason for this adjustment. Appreciate any explanation, so that I didn't make "blind" fix.
```
// Record the adjusted PTS to adjust for wraparound next time.
    lastPts = pts;
    return timeUs + timestampOffsetUs;
```

**Comment by ojw28** [comment]
I'm curious how you're getting live HLS to work with WebVTT in the first place, because we haven't added support for that yet (this issue is one of the things we'll be tackling when we do get around to adding this feature).

There is indeed a good reason for that; removing it will break playback when the PTS timestamps wrap, I believe.

**Comment by ferrytanu** [comment]
I'm still working on getting WebVtt playlist (m3u8) works for HLS live and VOD, using ChunkSampleSource, and defined a new ChunkSource implementation. Setting timeUs to PTS makes the WebVtt works for HLS live, and WebVtt with MPEGTS > 0 for VOD.

However, it breaks time indicator (progress bar) on VOD, as it jump to PTS, it does not break the playback though.

I'm wondering how we can store and pass timestampOffsetUs to renderer (esp. TextTrackRenderer), without a lot of changes. Extending SampleHolder may require TrackOutput.sampleMetadata and ElementaryStreamReader.consume to change, which is not ideal.

I'm pretty sure you have better solution :)

**Comment by ojw28** [comment]
Supporting VTT for HLS is tracked by #151, so this is essentially an issue about something that we haven't implemented yet. Please use #151 to track delivery.
