### ISSUE TITLE
Video Not pausing after focus change

### ISSUE THREAD

**Issue by ganeshgarad** [google/ExoPlayer#5790]
I'm using this library in recycler view for social media which contain image and video post. But when focus change on video it is not stopping or continuously playing in background. Application need to stop video when focus not on this video.

**Comment by nitinglobal** [comment]
@ganeshgarad  which lib  version you are using ? from 2.9.0 exoplayer can handle the focus automatically with small piece of code where you need to set the audio attribute.

**Comment by ganeshgarad** [comment]
2.9.2

**Comment by ojw28** [comment]
It's unclear what this question is about. What type of focus are you talking about? If you're talking about UI focus (e.g. the view holding the video is scrolled so it's no longer visible), then you need to handle this yourself (i.e. by detecting when the player should be stopped, and calling appropriate methods on the player to stop it).
