### ISSUE TITLE
Exoplayer cast for DASH widevine

### ISSUE THREAD

**Issue by SystemRestored** [google/ExoPlayer#5793]
I want to make exoplayer casting widevine dash video, I read it needs custom receiver to play. I couldnot find any code to make it. Anyone guide me how to make it?

**Comment by AquilesCanta** [comment]
Hi, unfortunately providing assistance around how to implement a custom receiver falls out of the scope of this issue tracker. [This is probably the best place to start](https://developers.google.com/cast/docs/caf_receiver/advanced#drm).

**Comment by J6ey** [comment]
`            mediaItemBuilder.setDrmSchemes(
                Collections.singletonList(
                    new MediaItem.DrmScheme(
                        sample.drmSchemeUuid, new MediaItem.UriBundle(sample.licenseServerUri))));`

Are you telling me this setup does not work for Widevine DRM?

**Comment by ojw28** [comment]
@J6ey - What does that have to do with this issue, which doesn't mention DRM at all? Marking off topic. Please file a new issue if you have a different question.
