### ISSUE TITLE
Allow pre-warming decoders ahead of time if app provides format hints

### ISSUE THREAD

**Issue by ojw28** [google/ExoPlayer#5795]
### [REQUIRED] Use case description
This enhancement is aimed at reducing the startup latency of the first playback, specifically when the application is able to provide hints as to the expected format of the content ahead of time. This is normally possible for applications where the app developer controls the content being played.

### Proposed solution
Provide a mechanism for the app to hint to a player instance what format(s) it will be used to play, in advance of starting the first playback. When such a hint is received, the player instance can setup the required decoders ahead of the first playback.

### Alternatives considered
N/A

**Comment by PratimMallick** [comment]
Hi @ojw28 . This really makes sense to have and can greatly benefit any app using exoplayer. Additionally another thing which can be done is setting up both video and audio decoders in parallel instead of sequential as it is now. 

When can we expect the release for pre warming of decoder to happen?

**Comment by ojw28** [comment]
I'm fairly sure it's possible for an app developer to pre-warm codecs now, if they have the necessary information. This can be done by injecting a custom `MediaCodecAdapter.Factory` into the `MediaCodec`-based renderers at construction time, where the factory can provide a pre-initialized decoder the first time it's asked for one.

@christosts may be able to provide further information.
