### ISSUE TITLE
Investigate alternate threading models

### ISSUE THREAD

**Issue by ojw28** [google/ExoPlayer#5796]
### [REQUIRED] Use case description
ExoPlayer currently sets audio and video decoders up one after the other. This enhancement tracks exploring setting them up in parallel, to reduce playback startup latency.

### Proposed solution
Setup audio and video decoders in parallel, rather than one after the other.

### Alternatives considered
N/A

**Comment by ojw28** [comment]
Generalized this issue to track running the renderers in parallel during playback, rather than just during decoder initialization.

**Comment by ojw28** [comment]
Generalize further to track investigating:
* Parallel decoder initialization
* Running renderers of different threads during playback
* Using separate threads for the input and output side of decoders

**Comment by christosts** [comment]
For those who may be getting updates of this issue, we have pushed an experimental feature on the dev-v2 branch for improving rendering performance. We posted details on our [blog](https://medium.com/google-exoplayer/improved-rendering-performance-operating-mediacodec-in-asynchronous-mode-and-asynchronous-buffer-3026207850b2). Please feel free to grab the dev-v2 branch and try it out.

**Comment by christosts** [comment]
I'm closing this issue as we are going to release asynchronous queueing 7a2c7c3.

More information on this [comment](https://github.com/google/ExoPlayer/issues/6348#issuecomment-934292402) on #6348.
