### ISSUE TITLE
Does exoplayer support vpaid ads

### ISSUE THREAD

**Issue by meenukrishnamurthy** [google/ExoPlayer#5797]
Vpaid ads are not getting played using the ima-extension for exoplayer.Does exoplayer support VPAID 2.0 ads.
The following the ad url:
https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dlinearvpaid2js&correlator=

**Comment by AquilesCanta** [comment]
Hi @andrewlewis, could you provide advise here?

**Comment by andrewlewis** [comment]
The Android IMA SDK which the IMA extension is built on does not support VPAID 2 (HTML5) so I'm afraid the answer is no (see [IMA SDK for Android Support and Compatibility](https://developers.google.com/interactive-media-ads/docs/sdks/android/compatibility)).

**Comment by yogesh37** [comment]
Hi @AquilesCanta  ,  is there any player support for VPAID ads?
