### ISSUE TITLE
com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.Exynos.avc.dec, Format(1, null, null, video/avc, null, -1, null, [640, 360, -1.0], [-1, -1])

### ISSUE THREAD

**Issue by Secretbox1987** [google/ExoPlayer#5799]
Hi! I have issue: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.Exynos.avc.dec, Format(1, null, null, video/avc, null, -1, null, [640, 360, -1.0], [-1, -1])
It happens when I init too many players

**Comment by linhai326** [comment]
most devices have a limit number of decoder instances at the same time. 
You might reach the limit. And also it is possible that your app fails to release old exoplayer while creating new one.

**Comment by AquilesCanta** [comment]
@linhai326 is on point here. If you have evidence this is an ExoPlayer issue, please provide all information required in the [issue template](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md) and we will reopen.

**Comment by joechan-cq** [comment]
> most devices have a limit number of decoder instances at the same time.
> You might reach the limit. And also it is possible that your app fails to release old exoplayer while creating new one.

Do all the apps in the phone share the limitation of the decoder? If so, does that mean my app can't init the decoder if the limitation has been reached. Is there someway I can release the decode held by the other apps?

**Comment by AquilesCanta** [comment]
> If so, does that mean my app can't init the decoder if the limitation has been reached

True. But that doesn't mean that every time there is an initialization error, it means the limit has been reached. Make sure there is not a different error ocurring.

> Is there someway I can release the decode held by the other apps?

I don't think there is (@ojw28?). I think the best you can do is retry later.

**Comment by ojw28** [comment]
If your app is in the foreground and the holding app is not, then I think there's logic in the platform that's supposed to reclaim the resource so that it can be given to the (more important) foreground app.

**Comment by joechan-cq** [comment]
Thanks for your reply. In my app, i somtimes receive the feedback from the users that they can't play the video. I found the error msg is about DecoderInitializationException, i tried everyway, however, i can't produce the bug. So i come here to find out the reason or information。
Maybe i need to add auto-retry function in my app.

**Comment by kgrajan12** [comment]
same problem for me too
