### ISSUE TITLE
WebvttParser failed on ignoring "#" for comments

### ISSUE THREAD

**Issue by ferrytanu** [google/ExoPlayer#580]
Some webvtt for live video streaming contains comment (indicated by "#"), as shown below
```
WEBVTT	#Elemental Media Engine(TM) Live
```

This will failed the following checking:
```
if (!line.equals("WEBVTT") && !line.equals("\uFEFFWEBVTT")) {
```
https://github.com/google/ExoPlayer/blob/dev/library/src/main/java/com/google/android/exoplayer/text/webvtt/WebvttParser.java#L119

**Comment by ojw28** [comment]
Yes, thanks. The WebVTT spec seems to allow arbitrary "stuff" to come after WEBVTT in the header line (technically there has to be a space or tab following WEBVTT). I think it would be fine just to change `equals` to `startsWith`; explicitly checking that the next character is a space or tab seems unnecessary. Thoughts?

**Comment by ojw28** [comment]
I guess it's not so hard to do it properly. The regular expression would be `^\uFEFF??WEBVTT((\\u0020|\u0009).*)??$`. I'll get this pushed to dev tomorrow.
