### ISSUE TITLE
Customize TsDurationReader's behavior

### ISSUE THREAD

**Issue by dushicai** [google/ExoPlayer#5802]
playback normal but can't get the duration

exo version 2.9.0

the ts url:https://drive.google.com/file/d/1gjsd8qPEd41M3TpUBjGuL-3ZstfZaDZR/view?usp=sharing

Duration: 00:04:44.95, start: 1.466667, bitrate: 3587 kb/s
Program 1 
Metadata:
      service_name    : LIVE
      service_provider: KSYUN
    Stream #0:0[0x100]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(progressive), 720x480 [SAR 8:9 DAR 4:3], 30 fps, 30 tbr, 90k tbn, 60 tbc
    Stream #0:1[0x101]: Audio: mp2 ([3][0][0][0] / 0x0003), 48000 Hz, stereo, fltp, 384 kb/s
    Stream #0:2[0x102]: Audio: mp2 ([3][0][0][0] / 0x0003), 48000 Hz, stereo, fltp, 384 kb/s

**Comment by AquilesCanta** [comment]
The issue can be solved by increasing the number of sniffed packets [here](https://github.com/google/ExoPlayer/blob/748a29e8f5ddf808d8da43f284b1c6227aa77e87/library/core/src/main/java/com/google/android/exoplayer2/extractor/ts/TsDurationReader.java#L39), but I don't think we want to end up with an ever increasing number here. I'll use this issue to track customization of the TsDurationReader behavior.

**Comment by ojw28** [comment]
Note: This is also part of what #5097 is tracking, so it might make sense to duplicate to that issue and add any extra ideas that you have to that one?

**Comment by AquilesCanta** [comment]
Ok, let's mark this as a duplicate then.
