### ISSUE TITLE
How to use a string Arraylist containing urls as a exoplayer playlist ?

### ISSUE THREAD

**Issue by CreeschYT** [google/ExoPlayer#5805]
Hi, so I'm trying to develop a HLS Live stream app using Exoplayer 2 which should play a string Arraylist containing urls. I thought about using a ConcatenatingMediaSource, but do NOT want to define every one of them, because  there are more than 100 urls in my Arraylist. So is there  a way to do that ? Thanks for helping

**Comment by tonihei** [comment]
There is no limit to the number of sources you can add to a ConcatenatinMediaSource. If you are worried about media preparation taking place at the same time, please use the `useLazyPreparation` flag in the ConcatenatingMediaSource constructor to ensure that media preparation only takes place when actually needed.

**Comment by CreeschYT** [comment]
Yes but I don't want to define every url in a Media Source.

**Comment by tonihei** [comment]
There is no real overhead involved in that. It's just creating a 100 objects (which should be fine) and can be done in a single loop.

Note that we are also looking into playing urls automatically by detecting their stream type (see #3165). If that is implemented, you should also be able to add urls to a playlist directly.

**Comment by CreeschYT** [comment]
Yes thank you for your answer, but I am searching for another way to do that. Is there another way a much easier way ?

**Comment by tonihei** [comment]
I don't really understand the problem. Why exactly do you need another way to do that?

**Comment by CreeschYT** [comment]
Ok so to understand the problem. Like I said I am developing a HLS (m3u) Streaming App  and want people to download my app. So now I'm going to explain what's the problem: I have a Button which opens a  MaterialFileChooser. Works fine. The user now has to choose a m3u file. Works fine. Because exoplayer can't play m3u files I used a BufferedReader to read all the lines. To actually play the channels I have to put every line that startswith "h"(url) in a List. In this case an Arraylist. Now I'm struggeling with converting that Arraylist full of urls to a Playlist for Exoplayer. I can't define every url because I don't know what m3u the user has chosen or what the urls are. I hope everyone now understands. 


Here's how an m3u file looks like:
`#EXTINF:-1,Channel name 1 
http://foviptv.shop:8080/WJILAyPvOz/ueYmlOtJQC/3561 (url1)
#EXTINF:-1,Channel name 2
http://foviptv.shop:8080/WJILAyPvOz/ueYmlOtJQC/3563 (url2)
#EXTINF:-1,Channel name 3
http://foviptv.shop:8080/WJILAyPvOz/ueYmlOtJQC/3557 (url3)

`

**Comment by tonihei** [comment]
You can just use a loop to create the MediaSources?

```
List<HlsMediaSource> mediaSources = new ArrayList<>();
for (String url : urlList) {
  mediaSources.add(new HlsMediaSource.Factory(dataSourceFactory).createMediaSource(url));
}
```

**Comment by CreeschYT** [comment]
Oh thank you very much. But it gave me an error at Factory. I'm very sorry for using your time but as you can tell I'm a newbie.
![Result](https://user-images.githubusercontent.com/49997316/56909223-2176e200-6aa8-11e9-9411-9cda60836270.png)

**Comment by tonihei** [comment]
I'm sorry, but we can't debug your app. Please direct questions around general usage of Android Studio and generic code problems to StackOverflow and similar sites. 

Based on your screenshot I'd suggest to include the Factory and/or make sure you are using an ExoPlayer version in which this class exists.
