### ISSUE TITLE
Stop streaming Dash video

### ISSUE THREAD

**Issue by dorcatty** [google/ExoPlayer#5809]
Dear all,
Recently, we are working on Dash video and Exoplayer with Unity game engine.
While we are playing a sample Dash video provided by Google, the stream never stopped. 
However, we converted our captured video to mpd Dash format, the video can be played smoothly with VLC player on MacOS, But with Exoplayer in Android, apk file compiled with Unity,  the streaming stops after 1min play.  no buffer is coming. 
Anyone has the same issue here ?or have any hints to fix it ?
thanks

**Comment by ojw28** [comment]
It sounds like an issue with the content. There is no way anyone can help unless you provide the problematic sample.

**Comment by dorcatty** [comment]
thanks a lot for your reply.
Here is the problematic sample
https://storage.googleapis.com/mydashcontent/test2/Scene_1_dash.mpd
Could you figure me out how to fix this?

**Comment by ojw28** [comment]
I only took a brief look, but I think the media is broken. In particular, it looks like the manifest claims that each video segment is 1s long, but they appear to be 2s long. As a result the manifest also thinks there are twice as many video segments as there actually are, which causes the player to try and request non-existent segments if seeking past half way through the content.

**Comment by dorcatty** [comment]
thanks a lot for your help:
here is the command i used to generate the manifest file:
MP4Box -dash 1000 -frag 1000 -rap -frag-rap -profile live filename.mp4
Do you have any suggestions to fix that ?
change chunk to 2000 ?
thanks a lot

**Comment by ojw28** [comment]
Questions about generating content are outside the scope of this issue tracker. I'd suggest you ask on an MP4Box forum or similar.
