### ISSUE TITLE
Wrong translation

### ISSUE THREAD

**Issue by Khang-NT** [google/ExoPlayer#5811]
### [REQUIRED] Issue description
"Text" doesn't mean "SMS"
https://github.com/google/ExoPlayer/blob/4bc79c9465abd00e29ff576c5f7a7517be632f5a/library/ui/src/main/res/values-cs/strings.xml#L23

### [REQUIRED] Reproduction steps
N/A

### [REQUIRED] Link to test content
N/A

### [REQUIRED] A full bug report captured from the device
N/A

### [REQUIRED] Version of ExoPlayer being used
`2.9.6`

### [REQUIRED] Device(s) and version(s) of Android being used
N/A

**Comment by ojw28** [comment]
Fixed in f4968e1a8e39563603a4b8528d8e826ee8c504ca.
