### ISSUE TITLE
get list of hls chunks

### ISSUE THREAD

**Issue by tipoc123** [google/ExoPlayer#5813]
### [REQUIRED] Searched documentation and issues
ExoPlayer issues, Google

### [REQUIRED] Question
How to get a list of all HLS chunks in the playlist?

**Comment by AquilesCanta** [comment]
Please see #2537. You can access HLS playlists through [Player.EventListener#onTimelineChanged](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/Player.EventListener.html#onTimelineChanged-com.google.android.exoplayer2.Timeline-java.lang.Object-int-). You need to cast the manifest object to [HlsManifest](https://exoplayer.dev/doc/reference/index.html?com/google/android/exoplayer2/source/hls/HlsManifest.html).

**Comment by tipoc123** [comment]
@AquilesCanta, thanks! You are the best!
