### ISSUE TITLE
FFmpeg transcoding

### ISSUE THREAD

**Issue by nbonamy** [google/ExoPlayer#5817]
### [REQUIRED] Searched documentation and issues
Did not find any post related to transcoding in documentation or issues.

### [REQUIRED] Question
I am trying to implement playback audio transcoding using the FFmpeg extension: my goal would be to read a video with DTS audio and transcode to AC3 audio (thanks Sonos). This would allow me to keep a 5.1 format instead of downscaling to PCM.

I compiled ffmpeg by adding --enable-encoder=ac3 and try to update FFmpegAudioRenderer.getOutputFormat by:
- setting encoding to ENCODE_AC3
- setting the mime type accordingly

But this does not work: video playback does not start. Is this even possible? If yes, what am I doing wrong?

Thanks

**Comment by andrewlewis** [comment]
I'm afraid it's not possible as things stand. The ffmpeg extension is designed for decoding to PCM only (not encoding).

**Comment by nbonamy** [comment]
@andrewlewis Is it a big change? If anyone can give some high level guidelines I can try my luck on it.

**Comment by andrewlewis** [comment]
At a high level I think you'll need a custom audio renderer that can output the AC-3 encoded data to the DefaultAudioSink (FfmpegAudioRenderer is designed to output PCM always, but you can probably use it as a starting point). For the transcoding part I'd start by forking the native part of the FFmpeg extension and figure out how to use FFmpeg's encoding APIs to process the PCM output that is currently generated in there. It's not in scope for this tracker to go into more detail I'm afraid.
