### ISSUE TITLE
Adding MediaSource to ConcatinatingMediaSource, exoplayer blinks

### ISSUE THREAD

**Issue by rjmohit4693** [google/ExoPlayer#5819]
First time when I play video
using      concatenatingMediaSource =  new ConcatenatingMediaSource(MediaSource);

second time when I add video (when exoplayer is already playing 1st video)
using     concatenatingMediaSource.addMediaSource(MediaSource);

exoplayer blink & sometimes show white screen

Please check this video

https://drive.google.com/open?id=1MgJTOCBBIye5c1wIkCPlpm27kjsfYZHQ

**Comment by tonihei** [comment]
Can you please provide example media so that we can reproduce the problem?

**Comment by rjmohit4693** [comment]
https://drive.google.com/file/d/1KSPfMXEkYb9DjfTtGOGYI__MYu7wkOuG/view?usp=sharing

https://drive.google.com/file/d/1SJzfIVZB1-yCyXAJek6GmHJeKMAhCU9E/view?usp=sharing

https://drive.google.com/file/d/1KfHFYkCbrT9M6wGmXPs6BUayRofC_C0a/view?usp=sharing

**Comment by rjmohit4693** [comment]
Also my app only supports tablet devices

**Comment by tonihei** [comment]
Thanks. I can reproduce your problem. 

The reason for this is that the player already sent the full first stream to the platform decoders and also indicated that this is the end of the stream. Only after this happened, you add a the second video. Unfortunately, we can't undo this end-of-stream signal, so we need to wait until all the data has been decoded and rendered, and only then re-enable the decoders from scratch. This re-enabling is the short blink you can see. The white background is potentially the shutter color in PlayerView. 

To work around this problem, you can try to set the new source before the decoders read the entire first stream. They usually read only a few seconds ahead (depending on the device), so it's best to set the new source as early as possible.

**Comment by rjmohit4693** [comment]
OK, I will try to set new source before the decoders read the entire first stream.
Thanks
