### ISSUE TITLE
Exoplayer doesn't play url playlist.

### ISSUE THREAD

**Issue by CreeschYT** [google/ExoPlayer#5820]
###  Description
Hi, I'm currently developing a HLS (m3u) Livestream app which should play a chosen hls file. I have a Button which opens a MaterialFileChooser. Works fine. The user now has to choose a m3u file. Works fine. Because exoplayer can't play m3u files I used a BufferedReader to read all the lines. To actually play the channels I have to put every line that startswith "h"(url) in a List. In this case an Arraylist. I made a Mediasource for every url with a for loop and put them into a concatenatingMediaSource. I expected to play the multiple urls, but unfortunately exoplayer isn't playling anything there's just a black screen.

This is the code I used:

```

try {
                BufferedReader br = new BufferedReader(new FileReader(filePath));
                String line;



                while ((line = br.readLine()) != null) {
                   if (line.startsWith("h")){
                       lineStore.add(line);

            
           DefaultHttpDataSourceFactory dataSourceFactory = new DefaultHttpDataSourceFactory("exoplayer_video");
BandwidthMeter bandwidthMeter = new DefaultBandwidthMeter();
        TrackSelector trackSelector = new DefaultTrackSelector(new AdaptiveTrackSelection.Factory(bandwidthMeter));
        exoPlayer = ExoPlayerFactory.newSimpleInstance(this, trackSelector);




                       for (String url : lineStore) {
                           mediaSources.add(new HlsMediaSource.Factory(dataSourceFactory).createMediaSource(Uri.parse(url)));
                       }

                       ConcatenatingMediaSource concatenatingMediaSource = new ConcatenatingMediaSource(mediaSources.toArray(new MediaSource[mediaSources.size()]));



                       exoPlayerView.setPlayer(exoPlayer);
                       exoPlayer.prepare(concatenatingMediaSource);
                       exoPlayer.setPlayWhenReady(true);
```

###  Files I used
I can't really give a link because every selected file is different but I could give you the file I used for testing. 
[richtiges m3u.zip](https://github.com/google/ExoPlayer/files/3143560/richtiges.m3u.zip)

###  Version of ExoPlayer being used
Currently I'm using Exoplayer 2.6.1

### Device(s) and version(s) of Android being used
I expected my app to run on a minimum of Android version 5.0. I also have tested my App on my phone (Samsung S6, Android 7.0) and on a (Samsung s4 mini, Android 6.0)

**Comment by tonihei** [comment]
That's impossible to say without all the required information in the issue template. Please fill it out completely and especially provide example media and reproduction steps so that we can reproduce the problem.

**Comment by CreeschYT** [comment]
I now have edited my description so it contains all the required information.

**Comment by CreeschYT** [comment]
I think there is a problem in (Uri.parse(url) because i stored the urls in an arraylist

**Comment by tonihei** [comment]
I think the issue is that the links in the m3u playlist are not HLS playlists but progressive stream and you need to use `ProgressiveMediaSource` (or `ExtractorMediaSource` on older ExoPlayer versions) to read them. 

Note that we also have an enhancement to implement parsing of m3u playlists internally and detect the stream type automatically, so you don't have to do this. See #4066.

**Comment by CreeschYT** [comment]
Can I get an example please because I'm really confused right now

**Comment by tonihei** [comment]
Just replace HlsMediaSource with ExtractorMediaSource.

**Comment by CreeschYT** [comment]
It worked, but not quite. So it worked it played the urls in Exoplayer version 2.6.1, but the player sometimes crashes, the audio is terrible sometimes, the previous button has to be clicked twice to play the previous item, and my phone crashed trying to open a m3u file with 100 urls. In Exoplayer version 2.8 and above it just plays sound and I can't go next or previous. So I'm looking forward to use a `ProgressiveMediaSource` ,but it gave me the 'cannot resolve' error. So now I'm using version 2.9.1. I'm sorry,  but as you can tell I'm quite new.

**Comment by tonihei** [comment]
This is likely due to an app bug and we unfortunately can't help you debug your app. I tested your example in our demo app and everything works fine without problems.

**Comment by CreeschYT** [comment]
Ok last question, so there are no problems with that code, right?
```
   List<ExtractorMediaSource> mediaSources = new ArrayList<>();
            ConcatenatingMediaSource concatenatingMediaSource;


            try {
                BufferedReader br = new BufferedReader(new FileReader(filePath));
                String line;

                while ((line = br.readLine()) != null) {
                   if (line.startsWith("h")){
                       lineStore.add(line);

                       DefaultHttpDataSourceFactory dataSourceFactory = new DefaultHttpDataSourceFactory("exoplayer_video");


                       BandwidthMeter bandwidthMeter = new DefaultBandwidthMeter();
                       TrackSelector trackSelector = new DefaultTrackSelector(new AdaptiveTrackSelection.Factory(bandwidthMeter));
                       exoPlayer = ExoPlayerFactory.newSimpleInstance(this, trackSelector);

                       for (String url : lineStore) {
                           mediaSources.add(new ExtractorMediaSource.Factory(dataSourceFactory).createMediaSource(Uri.parse(url)));

                       }



                       ConcatenatingMediaSource concatenatingMediaSource = new ConcatenatingMediaSource(mediaSources.toArray(new MediaSource[mediaSources.size()]));



                       exoPlayerView.setPlayer(exoPlayer);
                       exoPlayer.prepare(concatenatingMediaSource);
                       exoPlayer.setPlayWhenReady(true);

```

**Comment by tonihei** [comment]
I think you shouldn't create the MediaSources and prepare the player inside the loop while you are reading the lines.

But please note again that we don't have the resources to debug your app code and you are probably better off asking questions around that on sites like StackOverflow.
