### ISSUE TITLE
resolution and bandwidth adaptation with Exoplayer

### ISSUE THREAD

**Issue by dorcatty** [google/ExoPlayer#5822]
Dear developers,

i have a questions regarding to Exoplayer/Bandwidth with Android system.
I have 2 DASH mpd files with different resolution settings:
A has 4 diff resolutions: 960px, 1440px, 2160px and 2560px
B has 2 diff resolutions: 2160px and 2560px

Both mpd files can be played with VLC or IINA with highest resolution on MacOS (2560px in my case)

But with Exoplayer on Samsung S9+,
with A (4 resolutions), the resolution 1440px is played even higher bandwidth is available.
https://storage.googleapis.com/mydashcontent/diffresolution/4res/basic_eye_contact_scene_0_dash.mpd

with B (2 resolutions), the 2160px resolution is fluently played as well.
https://storage.googleapis.com/mydashcontent/diffresolution/2res/basic_eye_contact_scene_0_dash.mpd

My questions is how the Exoplayer deals with bandwidth and reslutions?
or how can I have a real adapted functions to play the highest resolution while high internet speed is available?
thanks

**Comment by tonihei** [comment]
ExoPlayer makes an initial guess at the bandwidth based on your network type and country and chooses the initial format based on this guess. It then starts to measure the actual bandwidth and switches up or down accordingly. Note that it only switches up if at least 10 seconds of media is buffered at the point where the next decision is made. So you may need to wait some seconds before the higher resolution is chosen. I tested the first stream in the demo app and this process works fine.
