### ISSUE TITLE
Get video url as soon as new video plays in playlist android

### ISSUE THREAD

**Issue by akanksha-hegde** [google/ExoPlayer#5824]
I'm creating an analytics sdk which requires to collect stream details using exoplayer listeners. 
In a playlist scenario I want to get the video url of the video currently playing. As soon as a next video starts in a playlist I need a callback which gives information of the new stream url.

Please let me know if there is a way to get this stream url without having the app to pass the array of playlist urls to my sdk.

**Comment by tonihei** [comment]
The easiest way is to set the tag of each `MediaSource` in the playlist to the stream url. There is a `setTag` method on all `MediaSource` builder classes for that.

You will get a `onPositionDiscontinuity` callback with reason `DISCONTINUITY_REASON_PERIOD_TRANSITION` every time the player automatically transitions from one content to the next. You can check the `player.getCurrentTag()` in this callback to get the tag of the currently playing item. This would be the stream url if you set it as the tag as described above.
