### ISSUE TITLE
Single-period static manifest with non-zero start fails to play

### ISSUE THREAD

**Issue by barrote** [google/ExoPlayer#5826]
Issue description
When using a multiperiod DASH manifest of type static and isoflive profile that only contains one period. If the @start of the period is not 0, the playout fails. Debugging indicates play start calculated beyond period duration.
The same works if there is more than one period.

Reproduction steps
Issue can be reproduced with the demo app.

Link to test content
Content is not available unfortunately, but here is a snippet of the start of the manifest:

```
<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" profiles="urn:mpeg:dash:profile:isoff-live:2011" type="static" availabilityStartTime="1970-01-01T00:00:00Z" mediaPresentationDuration="PT5M2S" maxSegmentDuration="PT2.016S" minBufferTime="PT3S">
<Period id="0" start="PT432464H29M58.767S">
<AssetIdentifier schemeIdUri="urn:eidr" value="md:cid:EIDR:10.5240%2f0000-65A0-2900-0000-0000-C"/>
```

Version of ExoPlayer being used
// ExoPlayer version and version code.
    releaseVersion = '2.9.5'
    releaseVersionCode = 2009005

Device(s) and version(s) of Android being used
Used Android emulator. Happens 100% of the times.

**Comment by ojw28** [comment]
Why would that ever be the case? I'd expect `@start` to always be 0 for static manifests. You can (and should) use `@presentationTimeOffset` to account for the timestamps embedded inside the media segments not starting from 0.

**Comment by barrote** [comment]
@ojw28 in our case if the profile is on demand, the start is indeed 0, if is live, then it means that some live event that is currently being watched has ended while the viewer is still watching at an earlier point of the stream. In this case the manifest switches from dynamic to static. The anchor time of the manifest is still 0, so the reference should be correct, but the start time is calculated incorrectly. If we have more than one period, then it works fine.

**Comment by ojw28** [comment]
> The anchor time of the manifest is still 0, so the reference should be correct, but the start time is calculated incorrectly

Could you clarify what this means. I'm not sure what anchor-time, the-reference and start-time are referring to exactly. Did you mean to include a snippet of the manifest above, because I don't see one :).

One additional question: Whilst the live event is still live, are segments being removed from the start? Or are segments only ever being added?

**Comment by ojw28** [comment]
Ah, the manifest snippet is there. It's just GitHub is interpreting it as something else, which makes it invisible. I've edited your post to have the snippet in a code block, which fixes it.
