### ISSUE TITLE
Streaming issue in Arabic language.

### ISSUE THREAD

**Issue by kmadhukishore** [google/ExoPlayer#585]
If you set the device to Arabic, streaming does not work with multiple bit rate DASH videos.

Steps to Reproduce:
1) Set the device language to Arabic.
2) Play DASH video using URL - http://www.bok.net/dash/tears_of_steel/cleartext/stream.mpd
3) Outcome: Video doesn't play
4) Change device language to English and play same video.
5) Outcome: Video plays.

Fix suggestion:
1) Open com\google\android\exoplayer\dash\mpd\UrlTemplate.java
2) Go to buildUri method
3) Change three String.format API usage from String.format(String format, Object... args) to String.format(Locale locale, String format, Object... args) with locale as Locale.US.

**Comment by ojw28** [comment]
Thanks!
