### ISSUE TITLE
Widevine Dash stream playback jumps on Pie devices on security level L3

### ISSUE THREAD

**Issue by samuuh** [google/ExoPlayer#5850]
### [REQUIRED] Content description
We noticed some of our streams became choppy on devices that only support Widevine's security level L3 after they were updated to Android 9.0 (Pie). We were able to reproduce this behaviour on the Exoplayer Demo Application `cenc,MP4,H264` streams. This can be verified easiest by the `WV: Secure UHD (cenc,MP4,H264)` stream.

All streams worked well before the update. On Pie devices supporting L1 the playback works as expected when L1 is used but when L3 is forced the same jumping can be seen.

This lack of L1 security level support seems to affect quite a few popular devices from what we have been able to see. Is there any settings that could possibly affect / fix this behaviour?

### [REQUIRED] Link to test content
Default Demo App sample streams. At least following:
{
  "name": "WV: Secure SD & HD (cenc,MP4,H264)",
  "uri": "https://storage.googleapis.com/wvmedia/cenc/h264/tears/tears.mpd",
  "drm_scheme": "widevine",
  "drm_license_url": "https://proxy.uat.widevine.com/proxy?provider=widevine_test"
},
{
  "name": "WV: Secure UHD (cenc,MP4,H264)",
  "uri": "https://storage.googleapis.com/wvmedia/cenc/h264/tears/tears_uhd.mpd",
  "drm_scheme": "widevine",
  "drm_license_url": "https://proxy.uat.widevine.com/proxy?provider=widevine_test"
}

### [REQUIRED] Version of ExoPlayer being used
2.9.6

### [REQUIRED] Device(s) and version(s) of Android being used
Issue is seen on Huawei Honor 9 and OnePlus5 without modifications to the demo app.
Similar behaviour can be seen on Nokia 6 and Pixel Google Pixel 2 XL when L3 security level is “forced” in Demo App with `mediaDrm.setPropertyString("securityLevel", "L3”);` on PlayerActivity -> buildDrmSessionManagerV18(..)
 
We have not observed this behaviour on Android 8.1 devices or earlier.

**Comment by ojw28** [comment]
@jefftinker - Are you aware of any performance regressions for L3 Widevine in P?

**Comment by fredgc** [comment]
We haven't noticed this.  We'll have our tester do a comparison and see if we can reproduce.

**Comment by fredgc** [comment]
Our tester does see worse performance on the L3 for Android P compared to O.  This is a regression.  We have not isolated the cause, but we expect it to be the same general behavior on most Android L3 devices.  We will investigate root cause and possible fixes.

**Comment by rrfrias** [comment]
We have addressed some of the performance regressions that you mention and have made them available to OEMs on Android P. There have been additional performance improvements for L3 on Android 10. If you notice performance issues with Android 10 feel free to reopen the tracker.
