### ISSUE TITLE
How to get information about chunks being played ?

### ISSUE THREAD

**Issue by swardharia** [google/ExoPlayer#5851]
I am trying to get information about the chunks ( url of the media segment ) that is currently being played on the player. I see that we get these information about the current chunk being downloaded [ inside the method onChunkLoadCompleted(Chunk chunk) ]. But I want to track the same chunk when it starts playing and when the player is done playing that chunk. Where can I find this information ?

**Comment by swardharia** [comment]
What other information do I need to provide ?

**Comment by marcbaechinger** [comment]
The `Chunk` object which is passed to `onChunkLoadCompleted` gives you the information about the chunk which has been loaded. 

The fields `startTimeUs` and `endTimeUs` tells the start and end time of the media contained by the chunk (see javadoc for more details on the [Chunk](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/source/chunk/Chunk.html) object). 

There is no event which tells you when a given chunk starts or ends playing I'm afraid. Can you be more specific about the use case you are trying to achieve?

**Comment by swardharia** [comment]
I am trying to keep track of what chunks are finished playing or being played currently to calculate the percentage of a particular video is played, if there are multiple (seperate) linear video streams in the manifest.

**Comment by marcbaechinger** [comment]
Do you want to trigger a behaviour after a given percentage of the video is reached or similar?

**Comment by swardharia** [comment]
Yes I am looking for similar behavior in case of dynamic manifest. I want trigger specific function calls (keep logs in the player) whenever given percentage of media is played. I am keeping track of those media segments in a data structure when the chunks are loaded inside onChunkLoadCompleted(), but I could not relate to the same chunks during playback.

**Comment by marcbaechinger** [comment]
If you want to run some code after 50 percent of the duration of a video you can do something like this;

```
player.createMessage((type, payload) -> doSomething())
  .setPosition(duration / 2)
  .setHandler(playerHandler)
  .send();
```

**Comment by swardharia** [comment]
Thanks for the respose @marcbaechinger :)

I think "duration" here means the length of the entire video content. Is it true ?

I am working with live HLS and DASH streams. And also, I am trying to get information about the progress of current video program ( can be a group of chunks forming a program ) within the entire stream. Is it possible to track this at playback, if I have the 'start URL' and 'end URL' of the program stored while parsing the manifest ?

**Comment by marcbaechinger** [comment]
Yes, correct. The `duration` is the duration of the media. In the example it is just used to calculate the position at which the message should be triggered. You can of course calculate that position in any way you want, like getting it from the information you get from a `MediaSourceEventListener`.

The `MediaSourceEventListener` which has callbacks like the one below which is called when data starts loading:

```
void onLoadStarted(
      int windowIndex,
      @Nullable MediaPeriodId mediaPeriodId,
      LoadEventInfo loadEventInfo,
      MediaLoadData mediaLoadData);
```
The `LoadEventInfo` and the `MediaLoadData` gives you information about what has been loaded and where in he media time it belongs to.

**Comment by swardharia** [comment]
Ok thanks. And one more question, is this onLoadStarted(), the eventListener for media segment being downloaded or the media segment that is being played by the Player interface ?

**Comment by marcbaechinger** [comment]
According to the method it's the chunk which has been started or completed downloading. You can get the media time at which it will be played from the MediaLoadData. So you can for nstance get the media time of the chunk you are interested in and then create a message to be triggered at the expected position.

**Comment by swardharia** [comment]
Sounds good. The timing information from the Chunk will help me in tracking that chunk during playback. Thanks for the responses :)

**Comment by marcbaechinger** [comment]
Cool. Closing for now. :) Please reopen if you think it's needed.

**Comment by swardharia** [comment]
Hi @marcbaechinger ,

I tried to add the 'messageHandler' to my class but now it's giving out "**Player is accessed on the wrong thread**" exception and Logcat is overflowed with this error before it stops printing more logs.

I am trying to call createMessage() function whenever the start segment of media is loaded to send a message to player for tracking that media. I am creating this DemoThread object from main application thread : 

```
class DemoThread {

private static Handler playerHandler;
private static SimpleExoPlayer player;

public DemoThread(SimpleExoplayer player) {
     this.player = player;
    playerHandler = new Handler();
}

public static void createMessage(Media current_media) {
    player.createMessage(boundaryHandler)
        .setPosition(current_media.getStart_time() + current_media.getDuration()/2)
            .setHandler(playerHandler)
            .send();
  }

static PlayerMessage.Target boundaryHandler = new PlayerMessage.Target() {
    @Override
    public void handleMessage(int messageType, Object payload) {
      Log.d("debug-log", "player media 50% completed");
    }
  };
}
```

Also, I read that player interface should only be accessed from the Main Application thread. How to access the player interface defined in main thread, from my DemoThread() class if I want to keep track of the current playback position and call the handler ?
