### ISSUE TITLE
Live content SmoothStreaming+PlayReady with Sony AndroidTV 2019

### ISSUE THREAD

**Issue by juanpef** [google/ExoPlayer#5855]
Hello,
We are trying to play a live content (Smoothstreaming+PlayReady) on a Sony AndroidTV device KD55AF9 (2019) and we are getting:
```
2019-05-07 17:57:50.326 31833-32005/com.orange.es.androidtv E/ACodec: [OMX.MTK.VIDEO.DECODER.AVC.secure] setPortMode on output to DynamicANWBuffer failed w/ err -1010
2019-05-07 17:57:50.543 31833-31993/com.orange.es.androidtv E/ExoPlayerImplInternal: Playback error.
   com.google.android.exoplayer2.ExoPlaybackException
       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:767)
       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:570)
       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:524)
       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:307)
       at android.os.Handler.dispatchMessage(Handler.java:101)
       at android.os.Looper.loop(Looper.java:164)
       at android.os.HandlerThread.run(HandlerThread.java:65)
    Caused by: android.media.MediaCodec$CryptoException: Crypto key not available
       at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
       at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:2532)
       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:758)
       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:570)
       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:524)
       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:307)
       at android.os.Handler.dispatchMessage(Handler.java:101)
       at android.os.Looper.loop(Looper.java:164)
       at android.os.HandlerThread.run(HandlerThread.java:65)
```
Other VOD encrypted contents are played without problems also.

We are using last ExoPlayer version. These videos are working without any problem on other devices, including Sony AndroidTV (2018/2017 models) and Nvidia Shield. So, this problem is only reproduced on these particular Sony models (KD55AF9)

Can you help me, please?

Regards

**Comment by juanpef** [comment]
Any help? Sony has noticed me this issue could be related with the use of PlayReady SL3000 on these devices, and "it occurs only when audio is encrypted with the same key as the video". But it has no sense because we use the same architecture on VOD and Live contents, and devices doesn't play live content, but VOD playbacks works properly.

Regards

**Comment by ojw28** [comment]
At the platform level the media framework has no concept of whether a stream being played is live or not. So it seems likely that something is different between the setup of your VOD and Live streams, other than the fact that one is VOD and the other is Live. If that were the only difference then they'd appear to be identical from the media framework's perspective.

There's not much we can do to help without a publicly available test stream (with a publicly available license server) that reproduces the issue. Although as an aside, we'd recommend using Widevine rather than PlayReady on Android devices, including AndroidTV, whenever possible.

**Comment by juanpef** [comment]
Thank you for your answer,
Could this error be caused by buffer settings? Maybe ExoPlayer is trying to play live video before getting the encryption key? How can we change these adjusts on ExoPlayer Demo project?
We can we try to use SmoothStreaming + Widevine, because our platform supports it. But I would need to do some changes on ExoPlayer. How can I test this combination on ExoPlayer Demo?

Regards

Juan Pedro

**Comment by ojw28** [comment]
> Could this error be caused by buffer settings? Maybe ExoPlayer is trying to play live video before getting the encryption key?

It's very unlikely. The components that decide this kind of thing don't know whether the content is live or not.

This error occurs when we've completed the key request and loaded keys into the underlying platform, go to decrypt a sample, and the underlying platform says that the key needed for decryption is not present.

**Comment by juanpef** [comment]
But we get Crypto key not available:

```
05-16 12:37:18.211 1473-5463/? E/PlayReadyDrmPlugin: provideKeyResponse >> scope = PlayReadySession1a, response (3980 bytes)
    provideKeyResponse sessionId: ( PlayReadySession1a )
05-16 12:37:18.211 1473-5463/? E/PlayReadyUtil: extractNonce >>
05-16 12:37:18.211 1473-5463/? E/PlayReadySession: processLicenseResponse,288:found drmHeader for given license response
05-16 12:37:18.211 1473-5463/? E/Playready30: processLicenseResponse() was called with license(3980 bytes)
05-16 12:37:18.248 1473-5463/? E/Playready30: [PR30]DRM_LEVL_PerformOperationsXMR, f_eOperation = 3
    DRM_LEVL_PerformOperationsXMR(1062):[PR30]5_XMR_IS_EXPIRATION_VALID-dwEndDate:
    2019-5-19 13:37:20
    DRM_LEVL_PerformOperationsXMR(1063):[PR30]5_XMR_IS_EXPIRATION_VALID curtime:
    2019-5-16 10:37:18
    [PR30]DRM_LEVL_PerformOperationsXMR, lReasonForFail = 0
    [PR30]DRM_LEVL_PerformOperationsXMR, f_eOperation = 1
    DRM_LEVL_PerformOperationsXMR(967):[PR30]4_XMR_IS_EXPIRATION_VALID-dwEndDate:
    2019-5-19 13:37:20
    DRM_LEVL_PerformOperationsXMR(968):[PR30]4_XMR_IS_EXPIRATION_VALID curtime:
    2019-5-16 10:37:18
    [PR30]DRM_LEVL_PerformOperationsXMR, lReasonForFail = 0
    [PR30]this license is persisted licenses
05-16 12:37:18.252 1473-5463/? E/Playready30: [PR30]DRM_LEVL_PerformOperationsXMR, f_eOperation = 3
05-16 12:37:18.253 1473-5463/? E/Playready30: DRM_LEVL_PerformOperationsXMR(1062):[PR30]5_XMR_IS_EXPIRATION_VALID-dwEndDate:
    2019-5-20 13:37:20
    DRM_LEVL_PerformOperationsXMR(1063):[PR30]5_XMR_IS_EXPIRATION_VALID curtime:
    2019-5-16 10:37:18
    [PR30]DRM_LEVL_PerformOperationsXMR, lReasonForFail = 0
    [PR30]DRM_LEVL_PerformOperationsXMR, f_eOperation = 1
    DRM_LEVL_PerformOperationsXMR(967):[PR30]4_XMR_IS_EXPIRATION_VALID-dwEndDate:
    2019-5-20 13:37:20
    DRM_LEVL_PerformOperationsXMR(968):[PR30]4_XMR_IS_EXPIRATION_VALID curtime:
    2019-5-16 10:37:18
    [PR30]DRM_LEVL_PerformOperationsXMR, lReasonForFail = 0
    [PR30]this license is persisted licenses
05-16 12:37:18.257 1473-5463/? E/Playready30: [PR] m_oBatchID NULL, persist license
05-16 12:37:18.257 1473-5463/? E/PlayReadySession: processLicenseResponse There are many KIDs!
05-16 12:37:18.257 1473-5463/? E/PlayReadyDrmPlugin: has (2)kids
05-16 12:37:18.257 1473-5463/? E/PlayReadySession: get kids
    get kids
05-16 12:37:18.257 1473-5463/? E/Playready30: f_index(1) >= cbKIDs(1)
05-16 12:37:18.257 1473-5463/? E/PlayReadyDrmPlugin: provideKeyResponse <<<< END
05-16 12:37:18.258 27043-27043/com.google.android.exoplayer2.demo D/EventLogger: drmKeysLoaded [0.95]
05-16 12:37:18.259 1473-5463/? E/PlayReadySession: getDecryptContext,417: cannot find kid , index(-2), kid size(16)  
05-16 12:37:18.259 1473-5463/? E/PlayReadyCryptPlugin: video decryptContext = NULL, get from kid again
05-16 12:37:18.259 1473-5463/? E/PlayReadySession: [bindLicenseWithKID,188]: The key index:-2  !!
    [bindLicenseWithKID,192]: The key is unvaluable  !!
05-16 12:37:18.259 1473-5463/? E/PlayReadyCryptPlugin: decrypt,189: session id(PlayReadySession1a) bindLicenseWithKID failed!
05-16 12:37:18.262 27043-27166/com.google.android.exoplayer2.demo E/ExoPlayerImplInternal: Playback error.
    com.google.android.exoplayer2.ExoPlaybackException
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:765)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:568)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:522)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:305)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: android.media.MediaCodec$CryptoException: Crypto key not available
        at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
        at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:2532)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:756)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:568) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:522) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:305) 
        at android.os.Handler.dispatchMessage(Handler.java:101) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.os.HandlerThread.run(HandlerThread.java:65)
```

**Comment by ojw28** [comment]
> But we get Crypto key not available

This is consistent with what I'm saying happens:

> This error occurs when we've completed the key request and loaded keys into the underlying platform, go to decrypt a sample, **and the underlying platform says that the key needed for decryption is not present**.

_Some_ keys have been loaded, but the platform thinks that it doesn't have the key that it needs.

**Comment by juanpef** [comment]
Thank you very much. 

I'm going to test it with SmoothStreaming +Widevine, that is supported by our servers (We don't have Dash). How can I adapt the ExoPlayer demo code to get it?

Regards

**Comment by johnsim** [comment]
Earlier in the thread https://github.com/google/ExoPlayer/issues/5855#issuecomment-492179782 it was suggested this occurs with SL3000 PlayReady using the same key for audio and video decryption. Is that correct? Have you tried using different keys for audio and video? It is generally a bad security practice to use the same key for both when you are trying to acheive a higher level of content protection, since the audio decode/decrypt path might be outside the TEE.

**Comment by ojw28** [comment]
> I'm going to test it with SmoothStreaming +Widevine, that is supported by our servers (We don't have Dash). How can I adapt the ExoPlayer demo code to get it?

According to Widevine, SmoothStreaming+Widevine is not a thing. See https://github.com/google/ExoPlayer/issues/1622#issuecomment-233767777. We don't provide support for this case in ExoPlayer, as per our [supported formats page](https://exoplayer.dev/supported-formats.html). So moving to Widevine probably requires moving to DASH.

**Comment by ojw28** [comment]
It may be that you can work around the problem with Sony devices by setting `multiSession = true` when instantiating `DefaultDrmSessionManager`. I'd suggest you give that a try.

**Comment by juanpef** [comment]
Thank you. 

It hasn't worked...
It is very strange that it is happening just on Live channels, but VOD channels, whose audio and video tracks are encrypted on the same way, and is using the same Licenser, are working properly.

**Comment by juanpef** [comment]
Is there some way to play only one video track using ExoPlayerDemo? So, I can test if the problem is totally related with audio encryptiion.

Regards

**Comment by ojw28** [comment]
Yes. Just change the track selection during playback. It should be fairly self explanatory how to select just a single track, disable tracks etc.

Edit: I think you can also do this after playback has failed, and then press the play button to restart playback with the new selection.

**Comment by juanpef** [comment]
If I do it after playback, customData is the same and server considers it as reused...so, I cannot play and then disabled audio track. Could I disabled it by default for the first playback?

**Comment by ojw28** [comment]
There is no easy way to do that in the demo app.

**Comment by johnsim** [comment]
in discussions here at Microsoft - two observations;
1) PlayReady will block returning samples from an SL3000 license in the clear, so if the audio license is SL3000, you won’t be able to get clear samples to your audio renderer – decryption will simply fail. That is required by the compliance rules.

2) The guess here is the most likely root cause of your issue is that you are issuing a single SL2000 license for VOD but a single SL3000 for Live, so the former works and the latter doesn’t. 

I hope that helps.
