### ISSUE TITLE
ExoPlayer device orientation does not change the Surface view

### ISSUE THREAD

**Issue by manojMadarasingha** [google/ExoPlayer#5859]
Hi,

I am new to Android. I was trying to build a 360 video player using ExoPlayer SDK.

I set the  **app:surface_type="spherical_view"** PlayerView in Activity_main.xml and added

**((SphericalSurfaceView) playerView.getVideoSurfaceView()).setDefaultStereoMode(C.STEREO_MODE_TOP_BOTTOM)**;

to the MainActiviy.java where the activity runs. 

I could change the view by touching the screen, but can not change the view while altering the device orientation. However, in the Exo-Player Demo app it works fine.  I examined the Demo app code but could not find any issue related to my code.

Are there any other change that I have to do inorder to get the device orientation feedback?

Thank you.

**Comment by marcbaechinger** [comment]
I think you need to just call `playerView.onResume()` and `playerView.onPause()` in the corresponding lifecycle method of your activity.

Take a look at [onResume()](https://github.com/google/ExoPlayer/blob/release-v2/demos/main/src/main/java/com/google/android/exoplayer2/demo/PlayerActivity.java#L215) of the PlayerActivity of the demo app.

**Comment by chamaraManoj** [comment]
Thank you. 
Adding `playerView.onResume()` and function and `playerView.onPause` worked. 
In the meanwhile I had  to change the Imported Exo Player version in the build.gradle file to a version like V 2.10.0

**Comment by marcbaechinger** [comment]
Cool! Thanks for letting us know!
