### ISSUE TITLE
Playing hls offline

### ISSUE THREAD

**Issue by moallemi** [google/ExoPlayer#586]
How should I init ExoPlayer to play a local directory that contains .m3u8 file and all media (*.ts) files within it?
Does ExoPlayer currently support file Uri?

**Comment by HamedGh** [comment]
I have the same question! did you find any answer?

**Comment by AquilesCanta** [comment]
@HamedGh this should work well if you just use the playlist file as the path. But make sure the relative paths, if any, point to the proper files.

**Comment by HamedGh** [comment]
@AquilesCanta could you show me your code?

**Comment by ojw28** [comment]
Implementing offline support for HLS is tracked by https://github.com/google/ExoPlayer/issues/2643. You should track that issue. We wont be providing sample code prior earlier than that issue being updated.
