### ISSUE TITLE
DVB Subtitles not working with SDK 28

### ISSUE THREAD

**Issue by P4FK47A** [google/ExoPlayer#5862]
Hello,

i just found out that DVB subtitles from MPEG-TS stream are not showing when using SDK 28 to compile the app. Since ExoPlayer version 2.10.0 uses AndroidX, i needed to update my app to SDK 28 and then i noticed this problem. I have tested this on Android 9 Pie on Samsung Galaxy Note 9 and on Android emulator and the results are the same.

When i use my old app version with ExoPlayer 2.9.6 and SDK 27 it works just fine.

In the logcat i can see that the subtitles are supported:
`D/EventLogger: [ ] Track:0, id=57/575, mimeType=application/dvbsubs, language=bul, supported=YES`

But when i select them manually from track selector, this happens:
`java.lang.IllegalArgumentException: Invalid Region.Op - only INTERSECT and DIFFERENCE are allowed`

I found out that the issue is in DvbParser.java at row 166:
`canvas.clipRect(baseHorizontalAddress, baseVerticalAddress, clipRight, clipBottom,
          Region.Op.REPLACE);`

I downloaded ExoPlayer demo source and same thing happens there, but when i remove `Region.Op.REPLACE` it seems to work, but it only shows subtitles for 2-5 seconds and then they are gone.

I am looking forward for a fix regarding this, because dvb subtitles are essential part of the streams i use for my project.

**Comment by marcbaechinger** [comment]
Thanks for reporting. We will provide a fix for this asap.
