### ISSUE TITLE
Is there any demo on how to play video from google dfp

### ISSUE THREAD

**Issue by hafiz013** [google/ExoPlayer#5863]
hi guys, I just want to know is there any tutorial/demo on how to play video from google dfp with it custom targeting and etc. tq.

**Comment by marcbaechinger** [comment]
There is a [demo app for the IMA extension](https://github.com/google/ExoPlayer/tree/release-v2/demos/ima) with you can use use an [IMA ad tag](https://developers.google.com/interactive-media-ads/docs/sdks/android/tags). There is also a [blog post](https://medium.com/google-exoplayer/playing-ads-with-exoplayer-and-ima-868dfd767ea) about how to use the IMA extension.

I'm not sure if this is what you are looking for though. If 'video from Google dfp' is something else than a ad tag, can you provide us with a sample?

**Comment by hafiz013** [comment]
Hi thank for reply, this [blog(https://medium.com/google-exoplayer/playing-ads-with-exoplayer-and-ima-868dfd767ea) is already out of dated since currently, exoplayer move to 2.9.6. by the way the demo app for the ima extension is really help. Thanks for sharing information. @marcbaechinger

**Comment by marcbaechinger** [comment]
Cool. Thanks for letting us know! I close for now. Please reopen if needed.
