### ISSUE TITLE
Dash with "Unmatched track of type" Problem

### ISSUE THREAD

**Issue by wow5109** [google/ExoPlayer#5864]
Hi,

Sorry for poor English.

### Content description
I play video use DASH and DRM.
Can play the movie normally.
but when i turn on the HTTP CACHE ,
can't play video with error log 
`BaseMediaChunkOutput :Unmatched track of type:  1 ` or
`BaseMediaChunkOutput :Unmatched track of type:  2` .
I see the EventLogger onLoadCompleted , the mpd and chunk nothing strange.
Why will this heppend, please for help,thanks.

### Version of ExoPlayer being used
Version of ExoPlayer is 2.9.6 

### Device(s) and version(s) of Android being used
Lg g6 running Android 8.0.0

**Comment by marcbaechinger** [comment]
You are mentioning HTTP CACHE. Do you mean you are using a CacheDataSource wrapped around your data source?

Can you provide us with a content url and a bug report which has been taken right after the problem occurs? This way we can look into the logs ourself.

**Comment by wow5109** [comment]
@marcbaechinger 
i email to telecom carrier , they change the CDN setting,
then solve my problem .
Thanks for reply.
