### ISSUE TITLE
use glSurfaceView causes green pixelation

### ISSUE THREAD

**Issue by dushicai** [google/ExoPlayer#5865]
exo version:2.9.6
MediaPlayer:
![MediaPlayer](https://user-images.githubusercontent.com/16698336/57502603-01081c80-731f-11e9-81bc-4bdf43e29d34.png)
ExoPlayer:
![ExoPlayer](https://user-images.githubusercontent.com/16698336/57502618-0b2a1b00-731f-11e9-82a6-ac58b109e99c.png)

**Comment by marcbaechinger** [comment]
Can you please provide us with some steps on how to reproduce this?

**Comment by dushicai** [comment]
Android 4.4  SOC: Allwinner Quad-core H3

The same problem with using this project：
https://github.com/roxlu/2018-016-android-exoplayer-with-gltexture

video resource:
https://drive.google.com/open?id=1l0XuEfyrPsE-jg98kndVlpfzcqkKSmFH

**Comment by ojw28** [comment]
Is this happening only with the specific device (Android 4.4 SOC: Allwinner Quad-core H3)? If so then it's likely a device specific issue, which you should report to the manufacturer.
