### ISSUE TITLE
How can I use 2 cache instances at the same time

### ISSUE THREAD

**Issue by rishabh876** [google/ExoPlayer#5867]
### Searched documentation and issues
I referred `Downloading Streams` Medium post by Erdem Guven [here](https://medium.com/google-exoplayer/downloading-streams-6d259eec7f95)
Also checked similar issue https://github.com/google/ExoPlayer/issues/4062. Couldn't find a clear solution.

### Question
I have two cache, 1 for playback and 1 for downloads (Both have different Evictor rules, so different folders). I can't find a way to use both cache at the same time. Am I doing something wrong here? If I use only one cache what will my evictor rules look like. How will I support both download and playback caches?

**Comment by marcbaechinger** [comment]
They only way I can think of is that you keep track of the cache keys which are downloaded and then have an eviction strategy which works like the `LeastRecentlyUsedCacheEvictor` except for downloaded keys.

I assigned to Erdem as he may have a better idea how this can be done. 

@erdemguven May I ask you to please comment on this?

**Comment by erdemguven** [comment]
You need to create and chain two CacheDataSources:
- playbackCDS : reads from HttpDataSource and writes to the playback cache.
- downloadCDS: Read-only accesses the download cache. Uses playbackCDS as upstream DataSource.

When you read from downloadCDS if the data is in the download cache, it's read from the cache. If not, it's read from playbackCDS.

**Comment by rishabh876** [comment]
Sounds exactly what I am looking for. Do we have documentation or a code sample for this? may be just a gist.

**Comment by erdemguven** [comment]
In ExoPlayer [demo app](https://github.com/google/ExoPlayer/blob/release-v2/demos/main/src/main/java/com/google/android/exoplayer2/demo/DemoApplication.java), you can replace [buildDataSourceFactory](https://github.com/google/ExoPlayer/blob/release-v2/demos/main/src/main/java/com/google/android/exoplayer2/demo/DemoApplication.java#L68) with this:
```
  public DataSource.Factory buildDataSourceFactory() {
    DefaultDataSourceFactory upstreamFactory =
        new DefaultDataSourceFactory(this, buildHttpDataSourceFactory());
    return buildReadOnlyCacheDataSource(
        new CacheDataSourceFactory(getPlaybackCache(), upstreamFactory), getDownloadCache());
  }
```
You can implement getPlaybackCache() similar to getDownloadCache().

**Comment by rishabh876** [comment]
Thank you so much. I have tested this code. Working as expected.
