### ISSUE TITLE
Is there an eventListener for subtitles?

### ISSUE THREAD

**Issue by BROUDING** [google/ExoPlayer#5871]
I figured how to load subtitle and merge with `MediaSource`.

But I'm wondering if there is an eventListner for loading subtitles.
Here's how I load subtitle

```
SingleSampleMediaSource.Factory(DefaultHttpDataSourceFactory("ua"))
   .createMediaSource(Uri.parse( subtitleUri ), vttFormat, C.TIME_UNSET)
```

How can I set the loadFailedListener....?

Thank you !

**Comment by marcbaechinger** [comment]
There is another `createMediaSource` method which offers two additional parameters which are a `Handler` and a `MediaSourceEventListener`. Is this what you are looking for?

```
public SingleSampleMediaSource createMediaSource(
        Uri uri,
        Format format,
        long durationUs,
        @Nullable Handler eventHandler,
        @Nullable MediaSourceEventListener eventListener) 
```

**Comment by BROUDING** [comment]
That should work, thank you!
