### ISSUE TITLE
With 2.10.0, how do I get the track URLs from the DASH Manifest for cache checking?

### ISSUE THREAD

**Issue by Gensoukyou1337** [google/ExoPlayer#5879]
### [REQUIRED] Searched documentation and issues
https://github.com/google/ExoPlayer/issues/5770

### [REQUIRED] Question
Right now, since I'm still using the LRU Cache strategy limited to 20 MB, I need to find a way to detect whether all parts of the downloaded stream exist in cache. The issue above is related, since it asks the question of the `DownloadIndex` not detecting when some of the .exo files are deleted.

Right now I'm thinking of a solution that fetches the URL of the tracks from the manifest using the manifest URL and the chosen stream keys. The `DownloadTracker` only keeps info of the track formats, not the track URLs, and I'm also thinking of using the `DashManifestParser` without binding it into a `MediaSource`. The plan after getting the track URLs is to do the usual `totalSpanLengths / contentLength` comparison.

How do I get the track URLs from the Manifest/download components?

**Comment by ojw28** [comment]
`DownloadManager`, `DownloadService` etc are intended for proper download use cases, where a `NoOpCacheEvictor` should be used. They are not designed for use with an evicting cache.
