### ISSUE TITLE
ADAPTIVE_MODE_ABRUPT results into video stutter when resolution switches

### ISSUE THREAD

**Issue by srikieonline** [google/ExoPlayer#588]
Branch: Master (1.3.3)
Test stream: Apple master playlist advanced

Issue: After around 9 secs (Duration of each chunk is around 9-10 secs) when the player switches the variant, we see that for around 2 seconds the video is not rendered - however audio continues to play - and then after 2 seconds video starts rendering. There are no frame drops and no skipped frames (from the logs).

Root cause: 
In MediaCodecTrackRenderer, I put logs at queueInputBuffer for video track and I saw that before the resolution switch, the presentationTimeUs is around 9.9 sec

**MediaCodecTrackRenderer: queueInputBuffer:bufferSize = 720 presentationTimeUs = 9943277**

And then just after the resolution switch, the timestamp jumps to 11.9 sec.

**MediaCodecTrackRenderer: queueInputBuffer:  bufferSize = 114939 presentationTimeUs = 11978600**

Note: These logs are for video track only. I've filtered out the audio logs - so no confusion.

In case of Audio, since there is no adaptive mode, it continues to queue frames with contiguous time-stamps.

So clearly, the HLSSampleSource jumps 2 second ahead. This causes the video not render for 2 seconds due to A/V sync logic.

**Comment by ojw28** [comment]
Did you read the documentation for ADAPTIVE_MODE_ABRUPT:

```For this mode to perform seamless switches, the source content is required to have keyframes positioned at the start of each segment. If this is not the case a visual discontinuity may be experienced when switching from one variant to another.```

Apple's test streams don't position keyframes in this way (although content providers are highly encouraged to both do so and use ADAPTIVE_MODE_ABRUPT, since it will result in better switching performance).
