### ISSUE TITLE
Downloading same videos independently 

### ISSUE THREAD

**Issue by bychkovdmitry** [google/ExoPlayer#5880]
### Searched documentation and issues
Checked CacheKeyFactory documentation, searched for similar questions.

### Question
Due to constraints on our testing environment we have several assets pointing to exactly the same Dash manifest url. We want these assets to be downloaded / deleted independently.  Currently, each DataSpec is saved to cache with key = dataspec.url.toString(). Therefore, when we try to download asset with the same url, it completes immediately. Things get even worse when we remove one of the assets: cached data is wiped out and is no longer available for another asset.  
Could you suggest workaround for that? Tried to introduce custom cache key factory, but this solution does not work because some operations which use Cache might be executed in parallel (downloading, removal, playback from cache). Thanks in advance.
 

```
class StateFullCacheKeyFactory : CacheKeyFactory {

    private var downloadId: String? = null

    fun setDownloadId(downloadId: String) {
        this.downloadId = downloadId
    }

    override fun buildCacheKey(dataSpec: DataSpec): String {
        val originalKey = if (dataSpec.key != null) {
            dataSpec.key
        } else {
            dataSpec.uri.toString()
        }
        return if (downloadId == null) originalKey!! else "$originalKey&$downloadId"
    }
}

```

**Comment by ojw28** [comment]
> Due to constraints on our testing environment we have several assets pointing to exactly the same Dash manifest url

I think you just need to fix your testing environment, because this sounds kinda broken. By definition (from Wikipedia):

> A Uniform Resource Identifier (URI) is a string of characters that **unambiguously** identifies a particular resource
