### ISSUE TITLE
how to set particular index in list of media sources in exo player?

### ISSUE THREAD

**Issue by hemanth-sp** [google/ExoPlayer#5881]
i am unable to set 5th song in 10 songs size
 app contain list of 10 songs i assume click on 5th song need play that 

https://stackoverflow.com/questions/56111776/how-to-set-particular-index-in-list-of-media-souces-in-exo-player?noredirect=1#comment98857725_56111776

**Comment by ojw28** [comment]
You should be using:
```
player.seekTo(/* windowIndex= */ 4, C.TIME_UNSET)
```
to seek to the 5th song (note that `windowIndex` starts at 0, so you should use 4 rather than 5).

**Comment by hemanth-sp** [comment]
hi 
i think  player.seekTo solution not working , when i call the service it always start with 0th song
this is current my code 
`for (ModelRadio sample : modelRadios) {
            MediaSource mediaSource = new ExtractorMediaSource.Factory(dataSourceFactory)
                    .createMediaSource(Uri.parse(sample.get_radio_url()));
            concatenatingMediaSource.addMediaSource(mediaSource);
        }
        player.seekTo(4, C.INDEX_UNSET);
        player.prepare(concatenatingMediaSource);
        player.setPlayWhenReady(true);`

`player.getCurrentWindowIndex()` shows 0th index

**Comment by tonihei** [comment]
Note that it should be `C.TIME_UNSET` in the seek command. I edited the post above.

Also, you need to ensure not to reset the position when preparing if you want to keep the seek position:
```
player.prepare(mediaSource, /* resetPosition */ false, /* resetState */ false)
```

**Comment by hemanth-sp** [comment]
hi, this code working fine i was need to change the order of the paper and seekTo

`import com.google.android.exoplayer2.C;

player.prepare(concatenatingMediaSource);

player.seekTo(5, C.INDEX_UNSET);

player.setPlayWhenReady(true);`

**Comment by tonihei** [comment]
Changing the order is potentially less efficient. Please consider calling `seekTo` first and then `prepare` with not resetting the position.

**Comment by hemanth-sp** [comment]
player.prepare(mediaSource, /* resetPosition */ false, /* resetState */ false) this helped without changing order . this also working fine
