### ISSUE TITLE
is exoplayer will be stopped if system kill the app for any reason while player notifciationmanager is used for notification

### ISSUE THREAD

**Issue by geeta4** [google/ExoPlayer#5886]
i have used playernotificationmanager to show notification what will happen if my app in background and system requires memory ? my app will be killed and player will be stopped?
and one more thing how to handle if we manually kill our app form stack tray what callback will be called and what when system kill our app? i have not used any service i am using playernotificationmanager to show notification

**Comment by marcbaechinger** [comment]
You should assume that the life-cycle methods of your app are called as described in the doc around [activity lifecycle](https://developer.android.com/guide/components/activities/activity-lifecycle) or [service lifecycle](https://developer.android.com/guide/components/services). That's actually all you can do to have a good user experience.

If the system gets low on memory, you should still assume the life cycle methods are called as described in that doc. If not, the system is in a very bad state already and you can't exactly know what happens. 

In any case the player will be stopped if the system kills your app/activity/service and the notification is removed. I don't think you need to think about this too much though. The important thing is that you release properly assuming the system is in a good state. 

This means that you must always release the player and the `PlayerNotificationManager` properly in the lifecycle methods of your components. You can not assume that the system does this for you. The `PlayerActivity`of [the demo app](https://github.com/google/ExoPlayer/blob/release-v2/demos/main/src/main/java/com/google/android/exoplayer2/demo/PlayerActivity.java#L212) does exemplify how you should call initialize and release according to the API level of the app.

**Comment by ojw28** [comment]
If the system kills your app you don't get any callback. The system will kill you if it needs to reclaim the resources you hold, so it doesn't make sense that it would leave you around for a bit longer whilst you do something in a callback.

You don't need to do anything special to handle this case. The platform will remove the notification for you at the time it kills the process.
