### ISSUE TITLE
Question: How to skip the ad with our custom FixedAdsLoader, not using IMA extension

### ISSUE THREAD

**Issue by Romantic-LiXuefeng** [google/ExoPlayer#5888]
### [REQUIRED] Question
I have implemented a custom FixedAdsLoader advised in the issue-4769 [https://github.com/google/ExoPlayer/issues/4769] to adapt our own ad server.  Now I need to add a product requirement. When the user is VIP, I want to add a skip button when playing ads, so that the user can skip the ad.  I want to know when user click the skip button, what the player need to do?

**Comment by Romantic-LiXuefeng** [comment]
I have searched the  `ImaAdsLoader`, has not found useful message, How the IMA skip a ad or a ad group?

,

**Comment by andrewlewis** [comment]
The custom `AdsLoader` implementation needs to mark the ad group as skipped ([like this](https://github.com/google/ExoPlayer/blob/0622afe/extensions/ima/src/main/java/com/google/android/exoplayer2/ext/ima/ImaAdsLoader.java#L1197)) and pass the updated the ad playback state to the ads loader listener.
