### ISSUE TITLE
playernotifcation is playing sound and vibration while it is a silet notification

### ISSUE THREAD

**Issue by geeta4** [google/ExoPlayer#5890]
playernotification manager is playing sound and vibration and showing popup on app while it is silent notification it shoul not do all these things. it should be in notification tray silently

**Comment by marcbaechinger** [comment]
This is determined by the importance of the channel. 

In case you are using the static method `createWithNotificationChannel` the channel is created with [`NotificationManager.IMPORTANCE_LOW`](https://developer.android.com/reference/android/app/NotificationManager#IMPORTANCE_LOW) which does not make any noise if I'm not mistaken.

```
public static PlayerNotificationManager createWithNotificationChannel(
      Context context,
      String channelId,
      @StringRes int channelName,
      int notificationId,
      MediaDescriptionAdapter mediaDescriptionAdapter)
```

If you create the channel yourself you should use a similar constant. You can find detailed information about creating a channel in in the [training doc of the official docs](https://developer.android.com/training/notify-user/channels).  It boils down to something like the snippet below:

```
int importance = NotificationManager.IMPORTANCE_LOW;
NotificationChannel channel = new NotificationChannel(CHANNEL_ID, name, importance);
```
