### ISSUE TITLE
playing media from ui and pushed notification using Playernotificationmanager with customactionreciever when app is in background then player will work all time and notification action will work all time

### ISSUE THREAD

**Issue by geeta4** [google/ExoPlayer#5897]
Playing media from activity and pushed notification using Playernotificationmanager with customactionreciever. When app is in background then player will work all time and notification action will work all time. Is there will be any issue with playing media from notification after any time. Do i need service to work notification interaction all time? and what to do if i want to remove notification when app is deleted from recently opened app stack?

**Comment by ojw28** [comment]
If you want to play media in the background then you should use a `Service`. If you only need foreground playback, you do not.

Please bear in mind we are a small team, and are unable to answer such a large volume of questions. Most of these questions are general Android development questions (i.e. they'd apply equally regardless of which media player you're using. Please direct such questions to StackOverflow. Thanks.
