### ISSUE TITLE
in which callback i should release exoplayer when my app is deleted from opened app tray

### ISSUE THREAD

**Issue by geeta4** [google/ExoPlayer#5899]
in which callback i should release exoplayer when my app is deleted from opened app stack tray.
i need to play media if my app is in background but in opened app list . i have played from activity. so what is best way to play and release in this scenario. and i need to remove notification if my app is deleted from recently opened app tray?

**Comment by ojw28** [comment]
I don't think you get a callback when the app is deleted from the app stack tray.

Please bear in mind we are a small team, and are unable to answer such a large volume of questions. Most of these questions are general Android development questions (i.e. they'd apply equally regardless of which media player you're using. Please direct such questions to StackOverflow. Thanks.
