### ISSUE TITLE
Do exoplayer support RSS?

### ISSUE THREAD

**Issue by hafiz013** [google/ExoPlayer#5900]
hi new here, may i know the exoplayer can support/ integrate with [RSS feeds.](https://www3.uol.com.br/xml/midiaindoor/economia.xml)?

Any info for sharing is really help. T.q

**Comment by andrewlewis** [comment]
We don't have plans for adding support for RSS feeds at the moment. I'm not sure it really makes sense as a player library feature anyway -- if there are playable streams referenced by an RSS feed presumably you could parse them in your app and set up the player without much difficulty.

Note: this seems rather different to supporting m3u playlists (#4066) as there may be entries in an RSS feed that don't contain playable media and it's unclear how those should be handled.
