### ISSUE TITLE
User Agent

### ISSUE THREAD

**Issue by alfayedoficial** [google/ExoPlayer#5901]
Question:
-----------------------
- There's way to change user agent ? 
- There's way to hide user agent ?

**Comment by andrewlewis** [comment]
See the documentation on [preparing the player](https://exoplayer.dev/hello-world.html#preparing-the-player) for an example of passing a user agent string to the `DefaultDataSourceFactory` constructor. I'm not sure what you mean by hiding the user agent, but you can set it to the string of your choice, which should be sufficient. If not please provide more details about what you're trying to do.
