### ISSUE TITLE
Seeking support in Exoplayer with MPEG

### ISSUE THREAD

**Issue by rehmanmuradali** [google/ExoPlayer#5909]
Hi, I am using live radio stream: http://149.56.195.94:8322/bolpunjabiradio
I am trying to seek backward and forward. Is seeking supported in this stream ?
I found its content type audio/mpeg

**Comment by rehmanmuradali** [comment]
Hi, I am using live radio stream: http://149.56.195.94:8322/bolpunjabiradio
I am trying to seek backward and forward. Is seeking supported in this stream ? 
I found its content type audio/mpeg

**Comment by andrewlewis** [comment]
I'm afraid we don't support seeking in this stream as it's a live MP3. Please see also #4917.
