### ISSUE TITLE
How can I play a link that contains a header?

### ISSUE THREAD

**Issue by Marx-Hong** [google/ExoPlayer#5911]
### [REQUIRED] Question
How can I play a link that contains a header?
This is my code：
```
DefaultHttpDataSourceFactory dataSourceFactory = new DefaultHttpDataSourceFactory(Util.getUserAgent(context, context.getResources().getString(R.string.app_name)));
dataSourceFactory.getDefaultRequestProperties().set("Referer", (String) dataSource.headerMap.get("Referer"));
```
It does not work.
but it is work with MediaPlayer in android.
[ExoPlayerLib/2.10.0] [platina, MI 8 Lite, Xiaomi, 28]

**Comment by ojw28** [comment]
There's not enough context here for us to help you with your problem. The 2 lines of code in particular. It's unclear what `dataSource.headerMap.get("Referer")` is, and what you end up doing with `dataSourceFactory`.

**Comment by Marx-Hong** [comment]
```
RenderersFactory renderersFactory = new DefaultRenderersFactory(context);
        simpleExoPlayer = ExoPlayerFactory.newSimpleInstance(VideoMgr.getCurrentVideoView().getContext(), renderersFactory, trackSelector, loadControl);
        // Produces DataSource instances through which media data is loaded.
        DefaultHttpDataSourceFactory dataSourceFactory = new DefaultHttpDataSourceFactory(Util.getUserAgent(context, context.getResources().getString(R.string.app_name)));
        dataSourceFactory.getDefaultRequestProperties().set(Utils.USER_AGENT, (String) dataSource.headerMap.get(Utils.USER_AGENT));
        if (dataSource.headerMap.get("Referer") != null) {
            dataSourceFactory.getDefaultRequestProperties().set("Referer", (String) dataSource.headerMap.get("Referer"));
        }
        String currUrl = dataSource.getCurrentUrl().toString();
        if (currUrl.contains(".m3u8")) {
            videoSource = new HlsMediaSource.Factory(dataSourceFactory).createMediaSource(Uri.parse(currUrl), mainHandler, null);
        } else if (currUrl.contains(".mpd")) {
            videoSource = new DashMediaSource.Factory(dataSourceFactory).createMediaSource(Uri.parse(currUrl));
        } else {
            videoSource = new ExtractorMediaSource.Factory(dataSourceFactory).createMediaSource(Uri.parse(currUrl));
        }
        simpleExoPlayer.prepare(videoSource);
        simpleExoPlayer.addVideoListener(this);
        simpleExoPlayer.addListener(this);
```
"Referer" is a request header.I want to know if the request header is set correctly. thank you!

**Comment by ojw28** [comment]
I think the code you have should work fine, for setting the "Referer" header to whatever `dataSource.headerMap.get("Referer")` is giving you.

**Comment by Marx-Hong** [comment]
Thank you for your reply, it may be other issues

**Comment by ojw28** [comment]
Closing for now.

**Comment by Marx-Hong** [comment]
Hi,  It does not work but it is work with MediaPlayer in android.  
this is the video link:https://upos-hz-mirrorcosu.acgvideo.com/upgcxcode/66/36/93613666/93613666-1-30032.m4s?e=ig8euxZM2rNcNbUgnwdVhoMBhb4VhwdEto8g5X10ugNcXBlqNxHxNEVE5XREto8KqJZHUa6m5J0SqE85tZvEuENvNC8xNEVE9EKE9IMvXBvE2ENvNCImNEVEK9GVqJIwqa80WXIekXRE9IMvXBvEuENvNCImNEVEua6m2jIxux0CkF6s2JZv5x0DQJZY2F8SkXKE9IB5QK==&deadline=1560773586&gen=playurl&nbs=1&oi=1901539096&os=cosu&platform=pc&trid=bf8dbd79b97249a5886b3019c385b0e1&uipk=5&upsig=9b05bf2d1823320855ca9febfbef322b&uparams=e,deadline,gen,nbs,oi,os,platform,trid,uipk&mid=0
and the header: {"key":"Referer", "value":"https://www.bilibili.com/video/av53510611?spm_id_from=333.334.b_62696c695f646f756761.6"}
thanks

**Comment by ojw28** [comment]
The provided link doesn't work for me using MediaPlayer either (with the Referer request header set). Although this could be because the link has expired?

**Comment by Marx-Hong** [comment]
yes, I just updated the link, thanks

**Comment by ojw28** [comment]
I still see an HTTP 403 response, which is also what @marcbaechinger saw in #6021. I think your stream might be geo-restricted or something, which is stopping us from getting as far as the issue you're actually seeing.

You'll need to provide a stream that's not geo (or otherwise) restricted for us to help with this.

**Comment by Marx-Hong** [comment]
it maybe expired. Actually, i don't know how long it will expire. i can‘t control
