### ISSUE TITLE
What is the right way to access dash segments, make some changes to it, and replace back the new segments in the buffer?

### ISSUE THREAD

**Issue by GaureeshA** [google/ExoPlayer#5913]
### [REQUIRED] Searched documentation and issues
Tried searching a lot on StackOverflow and also the issues under github/exoplayer.

### [REQUIRED] Question
Any tips on how to proceed so that I can access the dash segments in real-time, make some changes(something like Super Resolution) and replace the segments back in the buffer. Which class/method should I focus upon?

**Comment by erdemguven** [comment]
What kind of changes you want to do?

**Comment by GaureeshA** [comment]
I have a Deep Learning model on the client side. I need to fetch segments while the video is playing from the buffer, perform super resolution, replace these new segments back in the buffer so that new frames are displayed.

**Comment by ojw28** [comment]
I don't really understand what "super resolution" is, but this level of customization is beyond what we can provide detailed guidance on, sorry. Depending on whether "super resolution" is performed on compressed or decompressed samples, you should take a look at the the components under `DashMediaPeriod` or `MediaCodecVideoRenderer` respectively.

**Comment by ojw28** [comment]
Clarification on terminology:
* compressed sample == a media sample before it's fed through the decoder (i.e. as it's stored in the container)
* decompressed sample == a sample after it's been fed through the decoder (i.e. a video frame ready for display, or a PCM audio sample)

**Comment by GaureeshA** [comment]
Thank you! We are most probably looking for the compressed form. As you mentioned about "DashMediaPeriod", where can I find the bytes of the compressed sample so that I can save it locally and make some changes to it. I can find the class called "Chunk", but how do I access the bytes? Thanks again.

**Comment by ojw28** [comment]
This level of customization is not something we provide an API for, and goes beyond what we're reasonably able to provide advice on through this issue tracker. You should probably take a look at `SampleQueue` as a starting point.
