### ISSUE TITLE
ExoPlayer.retry(): Return boolean indicating if retry was possible

### ISSUE THREAD

**Issue by AndrazP** [google/ExoPlayer#5916]
### [REQUIRED] Use case description
[ExoPlayer.retry()](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/ExoPlayer.html#retry--) can simply retry a failed or stopped playback **in some cases**, but their is no indication if method was successful.
We would like to know if ExoPlayer.retry() was sufficient or do we need to call ExoPlayer.prepare() again to retry playback.

### Proposed solution
[Original](https://github.com/google/ExoPlayer/blob/44293e8f45fc62ff918001b4425c44d0ded5ffc9/library/core/src/main/java/com/google/android/exoplayer2/SimpleExoPlayer.java#L888)
Proposed change:
```java
@Override
public boolean retry() {
    verifyApplicationThread();
    if (mediaSource != null
            && (getPlaybackError() != null || getPlaybackState() == Player.STATE_IDLE)) {
        prepare(mediaSource, /* resetPosition= */ false, /* resetState= */ false);
        return true;
    }
    return false;
}
```

### Alternatives considered
/

**Comment by ojw28** [comment]
> ExoPlayer.retry() can simply retry a failed or stopped playback in some cases

It can retry in all cases where playback has failed or stopped, unless the player has been reset. The condition in `retry()` is just checking that the player is actually in that state. So from the application's point of view there shouldn't be any ambiguity here...

Please could you provide more information about what the issue you're facing is? When is it ambiguous as to whether `retry()` will do something or not?

**Comment by AndrazP** [comment]
In some rare cases retry will not work. For example if PlaybackPreparer fails to prepare new media.
I was hoping to simplfy logic in [PlayerView.html#setPlaybackPreparer](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/ui/PlayerView.html#setPlaybackPreparer-com.google.android.exoplayer2.PlaybackPreparer-) to something like:
```java
if (!exoPlayer.retry()) {
    // Retry was not successful, prepare a new source.
    playbackPreparer....(..)
}
```
Currently I have something like:
```java
if (exoPlayer.playbackError != null) {
    // Retry is possible
    exoPlayer.retry()
} else {
    // Prepare a new source.
    playbackPreparer....(..)
}
```

**Comment by ojw28** [comment]
This doesn't seem particularly important. I've no particular objection though. Re-assigning to @tonihei to consider in the context of the `Player` interface.

**Comment by tonihei** [comment]
`PlayerView` only invokes the `PlaybackPreparer` interface if the playback state is PLAYER_IDLE. How did you get into a situation where the playback can't be retried?

**Comment by ojw28** [comment]
Closing due to lack of importance & follow up.
