### ISSUE TITLE
Is there any difference between 2.10.0.alpha1 and 2.10.0

### ISSUE THREAD

**Issue by rajeshghosh1978** [google/ExoPlayer#5917]
### [REQUIRED] Searched documentation and issues
I have tried in this forum and also tried to compare the versions below. But failed to get the alpha1 codebase.

### [REQUIRED] Question
We are using 2.10.0.alpha1 , and would like to use the same for the production build. But I can see you already release 2.10.0 , which we can't use right now. I have also tried to compare the code changes but failed to compare as I can't find the alpha1 codebase. Could you please tell me the differences between the alpha1 and the 2.10.0.

**Comment by ojw28** [comment]
> Could you please tell me the differences between the alpha1 and the 2.10.0.

The changes submitted to https://github.com/google/ExoPlayer/commits/dev-v2-r2.10.0 more recently than April 19th.

You should just switch to 2.10.0.
