### ISSUE TITLE
[Flutter][Video_player_plugin] Using ClippingMediaSource, it always shows the first frame first.

### ISSUE THREAD

**Issue by yjoo9317** [google/ExoPlayer#5918]
###  Searched documentation and issues
JavaDoc for Exoplayer, ClippingMediaSource and searched for issues related to the subject

### Question
I am developing an app using Flutter and the app involves in playing videos.
I am using video_plugin for flutter and I added a feature to play a specific range.
For that feature, I am using ClippingMediaSource.
The problem I have is that when it plays a specific range, it always shows the first frame then plays from the starting period of that range.
Here is the snippet before playing the sequence.
The video is just 8second long video. If I set the range from 3 ~ 5sec, then I expected duration of the clippingmedia to be 2 sec but the duration from exo player still says 8sec at the last log at the bottom.
Only solution (more like bandaid and which is not good at all) I've found so far is delaying the play for 200~300ms not to expose the first frame.
Note: Video source contains key frame at every second.
```
        MediaSource newMediaoSource = buildMediaSource(mediaUri, dataSourceFactory, context);
        if (newStartPosition >= 0 && newEndPosition >= 0) {
          newStartPosition = TimeUnit.MILLISECONDS.toMicros(newStartPosition);
          newEndPosition = TimeUnit.MILLISECONDS.toMicros(newEndPosition);
          newMediaoSource = new ClippingMediaSource(newMediaoSource, newStartPosition, newEndPosition, false, false, false);
          Log.i(TAG, "setting range: " + startPosition + ", " + endPosition);
        }
        this.startPosition = newStartPosition;
        this.endPosition = newEndPosition;
        exoPlayer.prepare(newMediaoSource, true, false);
        Log.i(TAG, "ClippingMedia duration: "+exoPlayer.getDuration());
```

**Comment by erdemguven** [comment]
This sounds like a bug.
Please provide complete information as requested in the bug template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md).

**Comment by yjoo9317** [comment]
The strange thing is that I just created a simple android app to play a video and put the exactly same code there. It didn't happen there.
Underlying code is same, I wonder why video player in Flutter has always (not 100%, but 90%) the first frame in place. 
@erdemguven do you still think it could be a ExoPlayer bug?

**Comment by erdemguven** [comment]
Perhaps it's a Flutter bug then, please fill a bug on https://github.com/flutter/flutter/issues
