### ISSUE TITLE
Allow ExoPlayer to use MediaPlayer internally

### ISSUE THREAD

**Issue by jackjohnsonn** [google/ExoPlayer#5919]
### [REQUIRED] Searched documentation and issues
I have realized that ExoPlayer does not support flac by default. After searching I have found the extra extension for flac playback. My issue with the extension is that even though it has an APACHE license, the components that it uses have licenses that would require me to release my commercial project's source which I do not want.

### [REQUIRED] Question
Since MediaPlayer already has support for flac, I have decided to use it for flac playback. Is it possible for ExoPlayer to internally use MediaPlayer for flac playback? Is there any extension that allows ExoPlayer to use MediaPlayer internally?

Thanks for your time.

**Comment by jackjohnsonn** [comment]
I have also realized that the end result of the extension is a 1MB file which is too large.

**Comment by andrewlewis** [comment]
We thought about implementing this kind of fallback to MediaPlayer in the context of using audio offload before Android Q, but it's unclear that it's worth the extra complication and it seems infeasible to make the fallback invisible to apps. For example, there is no way to switch between player implementations while keeping the same AudioTrack for playlist use cases, and various ExoPlayer features wouldn't be supported when using AudioTrack (e.g., playback parameters adjustment before Android M).

I think FLAC should be available via MediaCodec from Android O. I wonder if making an APK split based on API version is an option, so you'd only ship the extension for devices running earlier versions. That might mitigate the problem of APK size increase.

**Comment by ojw28** [comment]
An in-between option would be to have a wrapper around `MediaPlayer` that implements our `Player` interface. It wouldn't achieve transparent fallback because you'd still have to pick which player to use, but it would let you switch easily between the two at the app layer, and use both with ExoPlayer's standard UI widgets and other components that operate on a `Player`. You could use `ExoPlayer` for FLAC on Android O and above, and `MediaPlayer` on earlier API versions, and then drop the `MediaPlayer` wrapper with minimal effort when it's finally no longer required.

I don't think we have any plans to implement a wrapper ourselves, but it's something you could do in your app code, if you were sufficiently motivated to do so.

**Comment by jackjohnsonn** [comment]
Thank you so much for the detailed information, @andrewlewis @ojw28

I was actually hoping the newer APIs would have support for FLAC by default and that I would not have to ship the FLAC compiled extension with their APKs. So, I ran my project on an Android Pie emulator, without the FLAC extension. I have received the same error like the one on the other APIs:

UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor, AmrExtractor, Ac4Extractor) could read the stream.

I can only play the FLAC files, if I add the compiled FLAC extension which is the case for other APIs. Am I missing something? 

Could not ExoPlayer just use a JAVA FLAC decoder library instead of relying on a compiled source?

Does the ExoPlayer FLAC extension here use the libFLAC/libFLAC++ libraries only making it BSD licensed or does it use the extras making it GPL licensed, instead.

Thanks a lot for your time.

**Comment by andrewlewis** [comment]
Regarding Android O and later support for FLAC: I think there is support for decoding FLAC sample data, so it should work without the extension if you can mux your FLAC streams into a Matroska container for example, but for reading .flac files the FLAC extension is still needed.

A MediaExtractor wrapper may be a more feasible option to investigate, as we can control rendering in that case. We used to provide one but it had issues (e.g., #38, #47, #51, #247), however, maybe we should revisit this for FLAC specifically.

**Comment by jackjohnsonn** [comment]
Thanks for the information, andrewlewis. I have realized that ExoPlayer is also missing support for MIDI and some specific files. So, I am going to start a request issue for a MediaPlayer wrapper for ExoPlayer and hope for the best. Maybe you guys will consider it in the future.
