### ISSUE TITLE
Write better Javadoc for DemoPlayer in the demo app

### ISSUE THREAD

**Issue by brianchu** [google/ExoPlayer#592]
Lot of javadoc in the latest version of DemoPlayer is gone. Nice to see if they can be kept, some of them do explain things and it's good to have. :)

**Comment by ojw28** [comment]
I don't think we've deleted any Javadoc. What Javadoc do you think has been removed?

**Comment by brianchu** [comment]
You're right. I am confused with the one GMF added (they did add comments: https://github.com/googleads/google-media-framework-android/blob/50fbcb4d0bfd9858cb099b5f5f1416737880615f/googlemediaframework/src/main/java/com/google/android/libraries/mediaframework/exoplayerextensions/ExoplayerWrapper.java).

By the way, are these comments valid? If yes, I want to merge them back.

**Comment by ojw28** [comment]
Changing this to a feature request to better document DemoPlayer. I'd rather write the comments from scratch to make absolutely sure they're correct.

**Comment by brianchu** [comment]
Thanks!

**Comment by ojw28** [comment]
`DemoPlayer` no longer exists in the [2.x.x experimental branch](https://github.com/google/ExoPlayer/tree/dev-2.X.X-experimental), and hence this is fixed by omission in 2.x!
