### ISSUE TITLE
2.10.0 can't play two players with 60 fps media.

### ISSUE THREAD

**Issue by AlphaCircle** [google/ExoPlayer#5921]
### [REQUIRED] Issue description
I am using LG V30 Android 8.0.0, API 26 and testing 2 players of Exoplayer. There was no issue in running 2 players with 60 fps mp4 file till version 2.9.6, but when the library has been upgraded to 2.10.0, I found an error message from exoplayer listener like this.
```
player error: com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, null, video/avc, null, -1, null, [3840, 2160, 59.94006], [-1, -1])
```
As a try to debug this issue, I tested 2 ways.
1) Looking at this message, I tried to change the mp4 which has 30 fps. Then the test app using 2 players runs good. 
2) I changed the phone to Samsung S8 (having Exynos, not Qualcom). The test app runs good.

Reading those results, I got to the presumption is the new version of 2.10.0 seems not working like 2.9.6 in handling codec and has missing points from 2.9.6. 

### [REQUIRED] Reproduction steps
Describe how the issue can be reproduced, ideally using the ExoPlayer demo app
or a small sample app that you’re able to share as source code on GitHub.

### [REQUIRED] Link to test content
Provide a JSON snippet for the demo app’s media.exolist.json file, or a link to
media that reproduces the issue. If you don't wish to post it publicly, please
submit the issue, then email the link to dev.exoplayer@gmail.com using a subject
in the format "Issue #1234". Provide all the metadata we'd need to play the
content like drm license urls or similar. If the content is accessible only in
certain countries or regions, please say so.

### [REQUIRED] A full bug report captured from the device
Capture a full bug report using "adb bugreport". Output from "adb logcat" or a
log snippet is NOT sufficient. Please attach the captured bug report as a file.
If you don't wish to post it publicly, please submit the issue, then email the
bug report to dev.exoplayer@gmail.com using a subject in the format
"Issue #1234".

### [REQUIRED] Version of ExoPlayer being used
2.10.0
Works on 2.9.6

### [REQUIRED] Device(s) and version(s) of Android being used
LG V30 Android 8.0.0
Works on Samsung S8 (having Exynos, not Qualcom)

**Comment by AlphaCircle** [comment]
Hello Ojw28
Sorry, I been away for a while because of another urgent things. I have read the newest version of 2.10.1 and tested that, too. But the result is same; video with fps = 60 does not work. 

Any progress or update about it?

**Comment by phhusson** [comment]
You have the two players running at the same time?

LG V30's Snapdragon 835 isn't capable of decoding two 4K 60fps videos at the same time, hence my question.
I'm seeing two possibilities:
- you're not running 2 players at the same time, and the problem is that because of "Improved decoder reuse" in exoplayer 2.10's changelog, players might not free their mediacodec instantly.
- the streams you're playing are not 4k, which would mean exoplayer opens mediacodec with too high capabilities.

**Comment by ojw28** [comment]
I can't see anything obvious that would have changed this between 2.9.6 and 2.10.0. Are you sure you didn't change something else at the same time as upgrading?

If you want us to investigate further, I think you'd need to provide concrete reproduction steps, which would probably require providing a small demo app (as source code) that demonstrates the issue.
