### ISSUE TITLE
Is there a way to know whether an IMA ad being played is Pre-roll, Mid-roll, Post-roll?

### ISSUE THREAD

**Issue by rs146** [google/ExoPlayer#5925]
### Content Description

I would like to find out if there is a way to know if the ad currently being played is Pre-roll, Mid-roll or Post-roll. I can't seem to find a listener that exposes this information.
I am currently using the IMA ads event listener on the `ImaAdsLoader`:

```
imaAdsLoader.addCallback(VideoAdPlayer.VideoAdPlayerCallback);
```
### ExoPlayer Version
2.9.2

**Comment by andrewlewis** [comment]
Sorry for being slow to reply. The easiest way is probably via the player API: if `player.isPlayingAd()` returns true, you can get the ad group time via `player.getCurrentTimeline().getAdGroupTimeUs(player.getCurrentAdGroupIndex())`; a returned value of 0 means a preroll is playing, `C.TIME_END_OF_SOURCE` means a postroll is playing and any other value indicates a midroll.

**Comment by rs146** [comment]
Hi @andrewlewis ,
I can't see a method called `getAdGroupTimeUs()` in the `Timeline`. How can I access this? I've upgraded ExoPlayer to the latest version as well but this method does not exist.

**Comment by andrewlewis** [comment]
Sorry, please try: `player.getCurrentTimeline().getPeriod(player.getCurrentPeriodIndex(), new Timeline.Period()).getAdGroupTimeUs(player.getCurrentAdGroupIndex())` -- the method is on `Timeline.Period` not `Timeline`.

**Comment by rs146** [comment]
Hi @andrewlewis,

This works for pre-roll and mid-roll ads. However with post roll ads, it crashes with the following stack trace. (I'm using DASH with widevine DRM).

```
Caused by: java.lang.ArrayIndexOutOfBoundsException: length=3; index=-1
        at com.google.android.exoplayer2.Timeline$Period.getAdGroupTimeUs(Timeline.java:402)
```

To produce this crash I'm using the following code:
```
Timeline timeline = playerView.getPlayer().getCurrentTimeline();
Timeline.Period period = timeline.getPeriod(playerView.getPlayer().getCurrentPeriodIndex(), new Timeline.Period());

long adGroupTime = period.getAdGroupTimeUs(playerView.getPlayer().getCurrentAdGroupIndex());
```

**Comment by andrewlewis** [comment]
Are you sure `player.isPlayingAd()` returned true at the moment you run that code?

I tried to reproduce using one of the sample ad tags with a postroll in the demo app, but the ad group index was correct and the associated ad group time was `C.TIME_END_OF_SOURCE` as expected.

**Comment by rs146** [comment]
Hi @andrewlewis,

Yes - you are correct. I need to use something like this to determine if the player is playing an ad:

```
public void onPositionDiscontinuity(int reason) {
        if (reason != DISCONTINUITY_REASON_SEEK) {
            adIsPlayingState.onNext(player.isPlayingAd());
        }
    }
```
The only problem with this is that is does not fire for pre-rolls which is why I have used the `VideoAdPlayer.VideoAdPlayerCallback#onPlay()` to determine if an ad is playing (as it fires the event for Preroll, Midroll and Postroll ads). When we use the `VideoAdPlayer.VideoAdPlayerCallback#onPlay()` to determine if an ad is playing, then we experience this crash.
