### ISSUE TITLE
Is exoplayer-extension-ima build.gradle missing a dependency for androidx.annotation:annotation:1.0.2 ?

### ISSUE THREAD

**Issue by aburksdev** [google/ExoPlayer#5926]
### [REQUIRED] Searched documentation and issues
Searched the exoplayer issues for the error "cannot find symbol class Nullable" and did not find it.
Searched the exoplayer dev site https://exoplayer.dev/ for "cannot find symbol class Nullable" and did not find it.

### [REQUIRED] Question
I am building an exoplayer app and cloning the repository and depending on the modules locally as described here: https://github.com/google/ExoPlayer#locally .   When I build the app, I get these errors when ExoPlayer\extensions\ima\src\main\java\com\google\android\exoplayer2\ext\ima\ImaAdsLoader.java is compiled:

error: cannot find symbol class IntDef
error: cannot find symbol class VisibleForTesting
error: cannot find symbol class Nullable

Interestingly, if I clone Exoplayer from github and build it, I do not see these errors.  It is only when I build my app that depends on the local exoplayer libraries that I get the errors.   I noticed that several other exoplayer extensions, such as exoplayer-extension-okhttp, also use the Nullable symbol from androidx.annotation:annotation:1.0.2.  However, the other extensions include the dependency

implementation 'androidx.annotation:annotation:1.0.2'

in their build.gradle file.

If I add implementation 'androidx.annotation:annotation:1.0.2' to the exoplayer-extension-ima build.gradle file, my app builds with no errors.

**Comment by andrewlewis** [comment]
Thanks for reporting. It looks like the dependency needs to be added.
