### ISSUE TITLE
Exoplayer offline download consumes more data than file size

### ISSUE THREAD

**Issue by ruthwikkk** [google/ExoPlayer#5927]
**[REQUIRED] Searched documentation and issues**
I am using ExoPlayer version 2.9.6 to stream video content in one of my project. Recently I added download video feature to my app using ExoPlayer's in built download manager. The problem with download is that it consumes more data while downloading. For a 18 MB video (the size is determined by checking the size of ExoPlayer's download folder after download) , it takes about 140 MB (this is variable in each try) of network data. I am using DASH to stream videos.  I checked the same with Demo App provided and the results are almost same.

**[REQUIRED] Question**
Any one know why this is happening.? Is there any improvements needed in my code ?

**Comment by erdemguven** [comment]
How do you measure the used network data?
Could you share the measurement you did using the ExoPlayer demo app?

**Comment by ruthwikkk** [comment]
> How do you measure the used network data?
> Could you share the measurement you did using the ExoPlayer demo app?

I noticed this issue only after some of our users started reporting. I measured the network data using GlassWire network monitor app. I have downloaded a 37 MB video using ExoPlayer Demo app and here I am attaching the screenshot from data monitor app

![Screenshot_20190522-203711](https://user-images.githubusercontent.com/25474982/58186234-19d6e180-7cd2-11e9-9155-419989c71878.png)

**Comment by erdemguven** [comment]
I can confirm the issue now. Soon a fix will be committed. Thanks for reporting.
