### ISSUE TITLE
IMA extension having issues when loading tags with mid-rolls but no pre-rolls

### ISSUE THREAD

**Issue by foodpoison** [google/ExoPlayer#5928]
### [REQUIRED] Issue description

When loading tags that have mid-rolls but no pre-rolls, playback can get stuck:

  1. Playing video with no pre-roll from the beginning, starts fine, but once we get to and play past the first mid-roll, it can get stuck in what seems like an endless loop and can't get out.
  2. Playing video with no pre-roll from position between first mid-roll and second mid-roll directly (by `seekTo()` before `prepare()`), just gets stuck, sometimes doesn't even play the first mid-roll with snapback.

If we use a video with pre-rolls with the above conditions, everything would seem to work like normal.

### [REQUIRED] Reproduction steps

I have made a forked branch that illustrates this issue: https://github.com/foodpoison/ExoPlayer/tree/tweak/failing_conditions_when_no_prerolls
In the `demo-ima`'s `PlayerManager`, I've setup a couple of flags that you can use to toggle between the conditions, also drew an ASCII chart of the working/failing conditions in as comments. Current `GET_PREROLL_ADS` is set to `true`, which should work OK; change it to `false` and you'll go into the first failing situation. Filter logcat with word `ImaAdsLoader`.

**NOTE: please VPN to Malaysia for the Ads to work, sorry I don't have control over them, perhaps you guys have more resources to replicate their settings to get something that would work for you**

### [REQUIRED] Link to test content

The forked branch above had been updated with test contents.

### [REQUIRED] A full bug report captured from the device

[bugreport-2019-05-23-10-55-26.zip](https://github.com/google/ExoPlayer/files/3209898/bugreport-2019-05-23-10-55-26.zip)

### [REQUIRED] Version of ExoPlayer being used

ExoPlayer - `r2.10.1` and `r2.9.6`, combined with IMA `3.11.2` and `3.10.9` respectively, had been tested to have this issue.

### [REQUIRED] Device(s) and version(s) of Android being used

Using the demo app branch I provided above, and if the Ads are loading properly (VPN could slow network down, so increased the timeouts in the code) it was pretty easy to reproduce, my current dev device is Samsung J7 Prime (Android 8.1.0), but also reports from my company's QA team's all their test devices have shown this issue, which covers a decent version range.

**Comment by foodpoison** [comment]
Thanks bot. Updated ticket descriptions.

**Comment by foodpoison** [comment]
Fix to this issue PR #5998 , please review :)

**Comment by ojw28** [comment]
@foodpoison - Thanks very much for your help on this!
