### ISSUE TITLE
IMA Extension video freezes on Huawei: seek to trigger midroll and seek before midroll position

### ISSUE THREAD

**Issue by fpittersacc** [google/ExoPlayer#5929]
### [REQUIRED] Issue description
On Huawei devices with 8.1.0, when playing content with midroll, perform a seek operation that triggers the midroll (see steps below) and then return to a position previous to the midroll position. The video gets frozen while audio keeps playing.

We couldn't reproduce the issue on other Samsung or Xiaomi devices.

### [REQUIRED] Reproduction steps
On a Huawei device, modify IMA demo with content & Ad uri shared below.

1. Start the app and let preroll to finish.
2. Seek to a position that triggers midroll (> 15s). Wait midroll to finish.
3. Seek to a position previous to midroll [0 - 15s].
4. Audio playback continues but video is frozen.

* If we don't perform the first seek that triggers midroll and let playback to reach that position the issue is not reproduced. 

### [REQUIRED] Link to test content
Content: https://storage.googleapis.com/wvmedia/clear/h264/tears/tears_hd.mpd
Ad: https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpost&cmsid=496&vid=short_onecue&correlator=

We couldn't reproduce the issue with MKV content set by default on the demo.

### [REQUIRED] A full bug report captured from the device
Enabling ImaAdsLoader.DEBUG 
[bugreport-SNE-LX1-HUAWEISNE-LX1-2019-05-22-14-33-49.zip](https://github.com/google/ExoPlayer/files/3207485/bugreport-SNE-LX1-HUAWEISNE-LX1-2019-05-22-14-33-49.zip)

### [REQUIRED] Version of ExoPlayer being used
2.10.1 and 2.9.6

### [REQUIRED] Device(s) and version(s) of Android being used
Huawei Mate 20 Lite Android 8.1
Huawei P20 Pro Android 8.1

We haven't tested any other Huawei devices with different version.

**Comment by andrewlewis** [comment]
@fpittersacc Sorry for the long delay. I don't have a Huawei device here to try to reproduce this. It would be helpful if you could check out `dev-v2`, set `ImaAdsLoader.DEBUG = true`, try to reproduce the issue using the main demo app (the IMA demo has been removed as it was redundant) and attach a bug report if it's still reproducible. By testing in the main demo app we should be able to tell if video frames are getting dropped based on `EventLogger` output.

**Comment by fpittersacc** [comment]
Thanks, we'll give a try and let you know

**Comment by andrewlewis** [comment]
@fpittersacc Any luck getting the new bug report?

**Comment by fpittersacc** [comment]
@andrewlewis, sorry for the delay.

We have been checking on Huawei devices and latest 2.11.6 it's performing well on every case.

Thanks, closing!
