### ISSUE TITLE
Playback periodically pausing

### ISSUE THREAD

**Issue by annetube** [google/ExoPlayer#5930]
### [REQUIRED] Content description
I'm trying to play and M3U link. It works but i got each 20 seconds / minutes it depends a pause, i dont know if its a problem of  codec or not, i would like have some help how to solve these issue because i got absolutely no errors on ffplay on desktop Thanks.

This is the logcat:

> > 2019-05-22 23:28:43.172 21171-25983/my.app.com I/OMXClient: IOmx service obtained
> 2019-05-22 23:28:43.214 21171-25982/my.app.com D/SurfaceUtils: connecting to surface 0x7b648a3010, reason connectToSurface
> 2019-05-22 23:28:43.216 21171-25982/my.app.com I/MediaCodec: [OMX.qcom.video.decoder.avc] setting surface generation to 21679110
> 2019-05-22 23:28:43.216 21171-25982/my.app.com D/SurfaceUtils: disconnecting from surface 0x7b648a3010, reason connectToSurface(reconnect)
> 2019-05-22 23:28:43.216 21171-25982/my.app.com D/SurfaceUtils: connecting to surface 0x7b648a3010, reason connectToSurface(reconnect)
> 2019-05-22 23:28:43.253 21171-25983/my.app.com D/SurfaceUtils: set up nativeWindow 0x7b648a3010 for 320x184, color 0x7fa30c06, rotation 0, usage 0x20002900
> 2019-05-22 23:28:43.271 21171-25987/my.app.com I/OMXClient: IOmx service obtained
> 2019-05-22 23:28:43.277 21171-25987/my.app.com I/ACodec: codec does not support config priority (err -2147483648)
> 2019-05-22 23:28:50.818 21171-25949/my.app.com D/AudioTrack: correcting timestamp time for pause, currentTimeNanos: 206327401937703 < limitNs: 206330708092285 < mStartNs: 206330788092285
> 2019-05-22 23:28:50.828 21171-25949/my.app.com D/AudioTrack: correcting timestamp time for pause, currentTimeNanos: 206327401937703 < limitNs: 206330708092285 < mStartNs: 206330788092285
> 2019-05-22 23:28:50.848 21171-25949/my.app.com I/chatty: uid=10728(my.app.com) ExoPlayerImplIn identical 2 lines
> 2019-05-22 23:28:50.858 21171-25949/my.app.com D/AudioTrack: correcting timestamp time for pause, currentTimeNanos: 206327401937703 < limitNs: 206330708092285 < mStartNs: 206330788092285
> 2019-05-22 23:28:50.868 21171-25949/my.app.com W/AudioTrack: getTimestamp() location moved from kernel to server
> 2019-05-22 23:29:14.764 21171-21171/my.app.com W/SystemServiceRegistry: getService(power) service=android.os.PowerManager@5d4d0bc
> 2019-05-22 23:29:14.764 21171-21171/my.app.com W/SystemServiceRegistry: getService(keyguard) service=android.app.KeyguardManager@1e3f3d1
> 2019-05-22 23:29:14.783 21171-25949/my.app.com D/AudioTrack: correcting timestamp time for pause, currentTimeNanos: 206336503606658 < limitNs: 206354676323630 < mStartNs: 206354756323630
> 2019-05-22 23:29:14.793 21171-25949/my.app.com D/AudioTrack: correcting timestamp time for pause, currentTimeNanos: 206336503606658 < limitNs: 206354676323630 < mStartNs: 206354756323630
> 2019-05-22 23:29:14.813 21171-25949/my.app.com I/chatty: uid=10728(my.app.com) ExoPlayerImplIn identical 2 lines
> 2019-05-22 23:29:14.824 21171-25949/my.app.com D/AudioTrack: correcting timestamp time for pause, currentTimeNanos: 206336503606658 < limitNs: 206354676323630 < mStartNs: 206354756323630
> 2019-05-22 23:29:14.835 21171-25949/my.app.com W/AudioTrack: getTimestamp() location moved from kernel to server
> 2019-05-22 23:29:30.971 21171-25949/my.app.com D/AudioTrack: correcting timestamp time for pause, currentTimeNanos: 206367869041125 < limitNs: 206370862115603 < mStartNs: 206370942115603
> 2019-05-22 23:29:30.981 21171-25949/my.app.com D/AudioTrack: correcting timestamp time for pause, currentTimeNanos: 206367869041125 < limitNs: 206370862115603 < mStartNs: 206370942115603
> 2019-05-22 23:29:31.001 21171-25949/my.app.com I/chatty: uid=10728(my.app.com) ExoPlayerImplIn identical 2 lines
> 2019-05-22 23:29:31.011 21171-25949/my.app.com D/AudioTrack: correcting timestamp time for pause, currentTimeNanos: 206367869041125 < limitNs: 206370862115603 < mStartNs: 206370942115603
> 2019-05-22 23:29:31.021 21171-25949/my.app.com D/AudioTrack: correcting timestamp time for pause, currentTimeNanos: 206367869041125 < limitNs: 206370862115603 < mStartNs: 206370942115603
> 2019-05-22 23:29:31.033 21171-25949/my.app.com W/AudioTrack: getTimestamp() location moved from kernel to server

and my code (basic):

```
      DefaultHttpDataSourceFactory dataSourceFactory = new DefaultHttpDataSourceFactory("Mozilla");
       MediaSource mediaSource;
        if(!hls_url.contains("mpd")) {
             mediaSource = new HlsMediaSource.Factory(dataSourceFactory)

                     .setAllowChunklessPreparation(true).setExtractorFactory(new DefaultHlsExtractorFactory())
                    .createMediaSource(Uri.parse(hls_url));
        }
        else {
             mediaSource = (MediaSource) new DashMediaSource.Factory(dataSourceFactory).createMediaSource(Uri.parse(hls_url));
            
        }
        
        player.prepare(mediaSource);
        player.setPlayWhenReady(true);
```
Tanks for your help 
### [REQUIRED] Link to test content
[https://stream-02.sv6.dailymotion.com/sec(3ftLdWES0pUbXTKGx4u-k79-7YjSd1y1D3LFKdVkLQI)/dm/3/xkxbzc/d/live-0.m3u8](url)

Link might expires 
### [REQUIRED] Version of ExoPlayer being used
2.9.4
### [REQUIRED] Device(s) and version(s) of Android being used
Android 8 ON Xiaomi mi8

**Comment by erdemguven** [comment]
The link looks like expired. Could you share another link? Ideally, a link that doesn't expire for a long time.

Please try to play on of the HLS streams from [here](https://github.com/google/ExoPlayer/blob/release-v2/demos/main/src/main/assets/media.exolist.json#L343) and let us know if the same thing happens.

**Comment by annetube** [comment]
> The link looks like expired. Could you share another link? Ideally, a link that doesn't expire for a long time.
> 
> Please try to play on of the HLS streams from [here](https://github.com/google/ExoPlayer/blob/release-v2/demos/main/src/main/assets/media.exolist.json#L343) and let us know if the same thing happens.

Thanks for your answer, i already tried and i got same errors on demo, the new link : 

https://stream-09.dc3.dailymotion.com/sec(3ftLdWES0pUbXTKGx4u-k_dLu_fNvX0AKB1qK5ttS-c)/dm/3/xkxbzc/d/live-0.m3u8
--



if its expired you can get a new one with streamlink doing on command streamlink -j https://www.dailymotion.com/video/xkxbzc

**Comment by annetube** [comment]
Any news ? I got same problems with this Dash link https://vosgestv.hdr-tv.com/live/vosgestv/livestream/manifest.mpd

**Comment by annetube** [comment]
@erdemguven

**Comment by ojw28** [comment]
Please could you describe the problem more clearly. I don't think the"codec does not support config priority" warnings in the logs are relevant to your issue.

So I think your issue is that you're seeing periodic pauses in playback. It's unclear whether you're seeing them every 20 seconds or 20 minutes from your description. It's also unclear whether this is happening only on the specific device you reference, or across all devices. Please clarify, and also send us a full bug report captured with `adb bugreport` shortly after encountering the issue.
