### ISSUE TITLE
Set custom duration and position in HLS live videostream

### ISSUE THREAD

**Issue by Shadkirill** [google/ExoPlayer#5931]
**Searched documentation and issues**
https://github.com/google/ExoPlayer/issues/2560
https://github.com/google/ExoPlayer/issues/2118
https://github.com/google/ExoPlayer/issues/3550

**Question**
I have a live HLS videostream and it contains chunks with metadata, which contains start and end position. When every chunk is loaded, its duration (close to 10 sec) and position are showed in updated timeline seekbar. The question is how i can customize duration and position to show timeline of current TV-show that is shown in that live HLS videostream?
P.S. I assume that i need to extend HLSMediaSource or HLSTimeLine or wrap my HLSMediaSource into other mediasource but i cant find information how to do it.
P.S.S. Im developing Android TV application with leanback features and i use LeanbackPlayerAdapter from com.google.android.exoplayer:extension-leanback:2.8.0 gradle dependency.

**Comment by Shadkirill** [comment]
Up

**Comment by ojw28** [comment]
I'm assuming you get information about the TV shows out of band (i.e. not in the HLS playlists themselves, but through some separate requests). Is that correct? Is the idea that if you're 10 minutes into a 30 minute TV show:

* You want to show a 30 minute seek bar
* Only the portion of the seek bar for which media is actually available in the HLS media playlists would be seekable

Does that sound right? If not, please clarify. Thanks!

**Comment by Shadkirill** [comment]
Yes, that's how it is.

**Comment by ojw28** [comment]
For now, you need to implement your own player control UI to do this. I've reopened https://github.com/google/ExoPlayer/issues/2213 to track adding support in our default UI components.
