### ISSUE TITLE
How to specify texture resolution when using MSG_SET_SURFACE

### ISSUE THREAD

**Issue by M-Pixel** [google/ExoPlayer#5937]
### [REQUIRED] Searched documentation and issues
There are numerous issues about selecting quality/resolution from multi-track streams - none are applicable to this question which is about scaling.  My particular use case is an on-disk file.

#5406 is very similar to my question, however the suggestion to use `SurfaceView` or `TextureView` is not applicable.

I've tried using `SurfaceTexture.setDefaultBufferSize(int, int)`, however it did not work.  The documentation does state, "The image producer may override the buffer size, in which case the producer-set buffer size will be used, not the default size set by this method", but I was unable to figure out _how_ this is done in order to intervene.

### [REQUIRED] Question
I'm using ExoPlayer with Unity as such:

1. A texture is created with `GLES20.glBindTexture(TextureHandle.GL_TEXTURE_EXTERNAL_OES, videoTextureId)`
2. A `Surface` is created from a `SurfaceTexture` that is created from the above.  This is supplied to ExoPlayer via `MSG_SET_SURFACE`.
3. In Unity, a `Texture2D` is created using the pointer that was returned by `glBindTexture`

The texture resolution ends up being identical to the source video resolution.  Is it possible for me to specify a resolution anywhere in the ExoPlayer render pipeline, such that I end up with a texture of the target size, scaled in a filtered manner from the source material?

Obviously, I can take the texture produced by ExoPlayer and run it through a filtered scaling algorithm, then pass that to Unity, however I can see this as being potentially redundant or otherwise inefficient.

**Comment by erdemguven** [comment]
As mentioned in #5406 ExoPlayer will decode video in its original resolution. You need to scale it after it's drawn to the texture.
