### ISSUE TITLE
How to determine whether the player is actually playing media

### ISSUE THREAD

**Issue by JayceKing** [google/ExoPlayer#5939]
public boolean isPlaying() {
        return (simpleExoPlayer != null) && simpleExoPlayer.isPlayingAd() && playerView.getPlayer().getPlayWhenReady();
    }

How to get whether the player is playing, the above code does not correctly get the status of the player.

**Comment by marcbaechinger** [comment]
You can consult our developer website which has a page about player events and a code snippet to this question:
https://exoplayer.dev/listening-to-player-events.html#player-state-changes
