### ISSUE TITLE
HD content playback not working anymore - Error decrypting data: requested key has not been loaded

### ISSUE THREAD

**Issue by DarioOl** [google/ExoPlayer#5941]
Hello, 

### [REQUIRED] Issue description
I'm having an issue while playing newly encrypted HD content on our device.
Depending on the content, it is played only for 6 to 16 seconds and then I get this exception :

> 
> 05-24 09:34:23.857   670  7547 E WVCdm   : PolicyEngine::CanDecrypt Key 'A12516B7E203579B87C9B43F7871E3BD' not in license.
> 05-24 09:34:23.857   670  7547 E WVCdm   : Decrypt error result in session sid48 during encrypted block: 5
> 05-24 09:34:23.863  1751  7813 E ExoPlayerImplInternal: Playback error.
> 05-24 09:34:23.863  1751  7813 E ExoPlayerImplInternal: com.google.android.exoplayer2.ExoPlaybackException
> 05-24 09:34:23.863  1751  7813 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:765)
> 05-24 09:34:23.863  1751  7813 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:568)
> 05-24 09:34:23.863  1751  7813 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:522)
> 05-24 09:34:23.863  1751  7813 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:305)
> 05-24 09:34:23.863  1751  7813 E ExoPlayerImplInternal: 	at android.os.Handler.dispatchMessage(Handler.java:98)
> 05-24 09:34:23.863  1751  7813 E ExoPlayerImplInternal: 	at android.os.Looper.loop(Looper.java:148)
> 05-24 09:34:23.863  1751  7813 E ExoPlayerImplInternal: 	at android.os.HandlerThread.run(HandlerThread.java:61)
> 05-24 09:34:23.863  1751  7813 E ExoPlayerImplInternal: Caused by: android.media.MediaCodec$CryptoException: Error decrypting data: requested key has not been loaded
> 05-24 09:34:23.863  1751  7813 E ExoPlayerImplInternal: 	at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
> 05-24 09:34:23.863  1751  7813 E ExoPlayerImplInternal: 	at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:2292)
> 05-24 09:34:23.863  1751  7813 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:756)
> 05-24 09:34:23.863  1751  7813 E ExoPlayerImplInternal: 	... 6 more
> 05-24 09:34:23.866  1751  1751 D EventLogger: droppedFrames [5.63, 9]
> 05-24 09:34:23.927   670   670 I OMX-VDEC-1080P: omx_vdec::component_deinit() complete
> 05-24 09:34:23.933   670   670 I OMX-VDEC-1080P: Exit OMX vdec Destructor: fd=47
> 05-24 09:34:23.934   670   670 I OMX-VDEC-1080P: Video slvp perflock released
> 05-24 09:34:23.952   670  1326 I WVCdm   : CdmEngine::CloseSession
> 05-24 09:34:23.955  1751  1751 D EventLogger: videoDisabled [5.72]
> 05-24 09:34:23.970  1751  1751 D EventLogger: audioDisabled [5.74]
> 05-24 09:34:23.979  1751  1751 E player_activity: An unknown playback error occurred class android.media.MediaCodec$CryptoException
> 05-24 09:34:23.982  1751  1751 I config  : GradingExperience enabled : true
> 05-24 09:34:23.987  1751  1751 E EventLogger: playerFailed [5.75]
> 05-24 09:34:23.987  1751  1751 E EventLogger: com.google.android.exoplayer2.ExoPlaybackException
> 05-24 09:34:23.987  1751  1751 E EventLogger: 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:765)
> 05-24 09:34:23.987  1751  1751 E EventLogger: 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:568)
> 05-24 09:34:23.987  1751  1751 E EventLogger: 	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:522)
> 05-24 09:34:23.987  1751  1751 E EventLogger: 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:305)
> 05-24 09:34:23.987  1751  1751 E EventLogger: 	at android.os.Handler.dispatchMessage(Handler.java:98)
> 05-24 09:34:23.987  1751  1751 E EventLogger: 	at android.os.Looper.loop(Looper.java:148)
> 05-24 09:34:23.987  1751  1751 E EventLogger: 	at android.os.HandlerThread.run(HandlerThread.java:61)
> 05-24 09:34:23.987  1751  1751 E EventLogger: Caused by: android.media.MediaCodec$CryptoException: Error decrypting data: requested key has not been loaded
> 05-24 09:34:23.987  1751  1751 E EventLogger: 	at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
> 05-24 09:34:23.987  1751  1751 E EventLogger: 	at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:2292)
> 05-24 09:34:23.987  1751  1751 E EventLogger: 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:756)
> 05-24 09:34:23.987  1751  1751 E EventLogger: 	... 6 more
> 05-24 09:34:23.987  1751  1751 D EventLogger: state [5.75, true, I]

The thing is that if I try to play older HD encrypted content ont this same device it works perfectly.
Also, when I play the same content but in SD on another device, it works.
We work only with offline licenses.

### [REQUIRED] Reproduction steps
This issue is reproduced on ExoPlayer 2.7.3

### [REQUIRED] Link to test content
I can't link the content as this is critical.

### [REQUIRED] A full bug report captured from the device
Here are the only logs I have when this error occurs : ```

> 
> 05-24 09:34:23.857   670  7547 E WVCdm   : PolicyEngine::CanDecrypt Key 'A12516B7E203579B87C9B43F7871E3BD' not in license.
> 05-24 09:34:23.857   670  7547 E WVCdm   : Decrypt error result in session sid48 during encrypted block: 5
> 05-24 09:34:23.863  1751  7813 E ExoPlayerImplInternal: Playback error.
> 05-24 09:34:23.863  1751  7813 E ExoPlayerImplInternal: com.google.android.exoplayer2.ExoPlaybackException
> 05-24 09:34:23.863  1751  7813 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:765)
> 05-24 09:34:23.863  1751  7813 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:568)
> 05-24 09:34:23.863  1751  7813 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:522)
> 05-24 09:34:23.863  1751  7813 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:305)
> 05-24 09:34:23.863  1751  7813 E ExoPlayerImplInternal: 	at android.os.Handler.dispatchMessage(Handler.java:98)
> 05-24 09:34:23.863  1751  7813 E ExoPlayerImplInternal: 	at android.os.Looper.loop(Looper.java:148)
> 05-24 09:34:23.863  1751  7813 E ExoPlayerImplInternal: 	at android.os.HandlerThread.run(HandlerThread.java:61)
> 05-24 09:34:23.863  1751  7813 E ExoPlayerImplInternal: Caused by: android.media.MediaCodec$CryptoException: Error decrypting data: requested key has not been loaded
> 05-24 09:34:23.863  1751  7813 E ExoPlayerImplInternal: 	at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
> 05-24 09:34:23.863  1751  7813 E ExoPlayerImplInternal: 	at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:2292)
> 05-24 09:34:23.863  1751  7813 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:756)
> 05-24 09:34:23.863  1751  7813 E ExoPlayerImplInternal: 	... 6 more
> 05-24 09:34:23.866  1751  1751 D EventLogger: droppedFrames [5.63, 9]
> 05-24 09:34:23.927   670   670 I OMX-VDEC-1080P: omx_vdec::component_deinit() complete
> 05-24 09:34:23.933   670   670 I OMX-VDEC-1080P: Exit OMX vdec Destructor: fd=47
> 05-24 09:34:23.934   670   670 I OMX-VDEC-1080P: Video slvp perflock released
> 05-24 09:34:23.952   670  1326 I WVCdm   : CdmEngine::CloseSession
> 05-24 09:34:23.955  1751  1751 D EventLogger: videoDisabled [5.72]
> 05-24 09:34:23.970  1751  1751 D EventLogger: audioDisabled [5.74]
> 05-24 09:34:23.979  1751  1751 E player_activity: An unknown playback error occurred class android.media.MediaCodec$CryptoException
> 05-24 09:34:23.982  1751  1751 I config  : GradingExperience enabled : true
> 05-24 09:34:23.987  1751  1751 E EventLogger: playerFailed [5.75]
> 05-24 09:34:23.987  1751  1751 E EventLogger: com.google.android.exoplayer2.ExoPlaybackException
> 05-24 09:34:23.987  1751  1751 E EventLogger: 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:765)
> 05-24 09:34:23.987  1751  1751 E EventLogger: 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:568)
> 05-24 09:34:23.987  1751  1751 E EventLogger: 	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:522)
> 05-24 09:34:23.987  1751  1751 E EventLogger: 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:305)
> 05-24 09:34:23.987  1751  1751 E EventLogger: 	at android.os.Handler.dispatchMessage(Handler.java:98)
> 05-24 09:34:23.987  1751  1751 E EventLogger: 	at android.os.Looper.loop(Looper.java:148)
> 05-24 09:34:23.987  1751  1751 E EventLogger: 	at android.os.HandlerThread.run(HandlerThread.java:61)
> 05-24 09:34:23.987  1751  1751 E EventLogger: Caused by: android.media.MediaCodec$CryptoException: Error decrypting data: requested key has not been loaded
> 05-24 09:34:23.987  1751  1751 E EventLogger: 	at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
> 05-24 09:34:23.987  1751  1751 E EventLogger: 	at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:2292)
> 05-24 09:34:23.987  1751  1751 E EventLogger: 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:756)
> 05-24 09:34:23.987  1751  1751 E EventLogger: 	... 6 more
> 05-24 09:34:23.987  1751  1751 D EventLogger: state [5.75, true, I]

### [REQUIRED] Version of ExoPlayer being used
ExoPlayer 2.7.3

### [REQUIRED] Device(s) and version(s) of Android being used
SD version working on a Samsung Galaxy S4 Android 5.1.
HD version not working on a Android 6 custom device.

**Comment by ojw28** [comment]
It seems unlikely this is an ExoPlayer issue. The underlying platform is saying that the key required for decryption isn't in the license response you received, which points to a content encryption or license configuration issue.

> 05-24 09:34:23.857 670 7547 E WVCdm : PolicyEngine::CanDecrypt Key 'A12516B7E203579B87C9B43F7871E3BD' not in license.

**Comment by DarioOl** [comment]
@ojw28 Thanks for the quick answer, what I can't understand is that after comparing the two emitted licenses (old HD content working and new HD content not working) the only difference is in the pssh_data that do not contain any "key_id": [] but we have it in the supported_tracks field :

```
    "supported_tracks": [
        {
            "key_id": "key id for HD track",
            "type": "HD"
        }
    ]
```

**Comment by ojw28** [comment]
The obvious question is whether everything just works if you revert back to however you used to be generating the content. Perhaps the CDM (or the specification itself) requires `key_id` to be set.

**Comment by ojw28** [comment]
Closing on the assumption `key_id` should be set.
