### ISSUE TITLE
Plumb MediaCodecRenderer.enableDecoderFallback through DefaultRenderersFactory

### ISSUE THREAD

**Issue by ojw28** [google/ExoPlayer#5942]
### [REQUIRED] Use case description
Enable decoder fallback without having to subclass DefaultRenderersFactory, as requested
[here](https://github.com/google/ExoPlayer/commit/401e20d9c8caf5f96e4ff2651cd14f46f1c35517#commitcomment-33659440).

@andrewlewis - Is there a reason we didn't expose the possibility of fallback for the audio renderer as well?

**Comment by andrewlewis** [comment]
As discussed I don't think there's a reason not to expose fallback for audio (I was going on the assumption that audio decoders are generally not hardware-accelerated so are much less likely to fail to initialize transiently). I will do that as part of this enhancement.
