### ISSUE TITLE
AdsMediaSource causes the Player.contentPosition to be incorrect when switching to contentMediaSource

### ISSUE THREAD

**Issue by buttss** [google/ExoPlayer#5943]
## Content description
When trying to play an IMA preroll ad by creating a AdsMediaSource and passing an HLS media source, or any other media source, when the preroll ad finishes, the currentPosition of the player is incorrect (not 0:00). I've seen the currentPosition vary from 3 - 20 seconds off from the default starting position.

## Link to test content
Replace the json in media.exolist.json file in the sample app with this JSON:
```
[
    {
        "name": "Test",
        "samples": [
            {
                "name": "Test Sample",
                "uri": "https://content.uplynk.com/402f4bffbe254c83bd3810b2255cff40.m3u8",
                "ad_tag_uri": "https://pubads.g.doubleclick.net/gampad/ads?env=vp&gdfp_req=1&impl=s&output=vast&sz=1x1000&hl=en&url=https://x-default-stgec.uplynk.com/ausw/slices/402/909259e3532a4e018299e5b1fe27ac9a/402f4bffbe254c83bd3810b2255cff40/402f4bffbe254c83bd3810b2255cff40_g.mp4&unviewed_position_start=1&iu=/6088/app.wcpo/uncategorized&ad_rule=2&correlator=&cust_params=402f4bffbe254c83bd3810b2255cff40_g.mp4&description_url=https://x-default-stgec.uplynk.com/ausw/slices/402/909259e3532a4e018299e5b1fe27ac9a/402f4bffbe254c83bd3810b2255cff40/402f4bffbe254c83bd3810b2255cff40_g.mp4"
            }
        ]
    }
]
```
Notice after the ad plays, the start position of the player is past 0:00. I've seen it vary from between 3 - 20 seconds off. This does not happen when creating a HLSMediaSource without ads. Even seeking back to the beginning will cause the PlayerControlView's Timebar to jump to the wrong position.

## Version of ExoPlayer being used
2.10.1

## Device(s) and version(s) of Android being used
Google Pixel, Android Version 9
Happens on any device.

**Comment by buttss** [comment]
After investigating the issue a little more. It seems like the currentPosition increments while the ad is loading. I'm basing this off the fact that the starting offset greatly increases when stepping through the code in a debugger, essentially delaying callbacks to the player

**Comment by ojw28** [comment]
@andrewlewis - Is this still an issue in 2.11.5?

**Comment by andrewlewis** [comment]
Yes, this is still reproducible at tip-of-tree.

If I play the content HLS stream without ads, seeking to 0 while paused leads to the player position jumping to 2 seconds. It seems likely that this is not directly related to ad insertion, but perhaps the extra delay due to loading ad tags makes the problem worse.

**Comment by andrewlewis** [comment]
The linked HLS stream is a VOD stream but `#EXT-X-PROGRAM-DATE-TIME` advances on successive requests. On seeking the value we derive for `startOfPlaylistInPeriodUs` in `HlsChunkSource` is non-zero and matches the amount by which the player position jumps forwards on seeking to zero. It looks like what is going on is that we end up mapping segments for the same piece of media to offset positions.

See also https://tools.ietf.org/html/rfc8216#section-6.2.4 "If any Media Playlist in a Master Playlist contains an EXT-X-PROGRAM-DATE-TIME tag, then all Media Playlists in that Master Playlist MUST contain EXT-X-PROGRAM-DATE-TIME tags with consistent mappings of date and time to media timestamps." Thanks to @AquilesCanta for diagnosing this.
