### ISSUE TITLE
Unable to play 360 dash / tiled content.

### ISSUE THREAD

**Issue by sr1990** [google/ExoPlayer#5946]
Hi,
### [REQUIRED] Content description
I am trying to play 360 video content with equirectangular projection and DASH of the same content. I am not able to play the DASH content and 360 HEVC tiled DASH content.  
"spherical_stereo_mode" is set to "mono". 

Are there plans to support the mentioned content? 

### [REQUIRED] Version of ExoPlayer being used
2.10

### [REQUIRED] Device(s) and version(s) of Android being used
Pixel 2 xl

Thanks

**Comment by erdemguven** [comment]
Please share a link to test content so we can investigate the issue.

**Comment by sr1990** [comment]
@erdemguven Have sent H.264 DASH 360 content at dev.exoplayer@gmail.com

**Comment by erdemguven** [comment]
I can't access to the file, permission denied.

**Comment by sr1990** [comment]
@erdemguven Can you access now? I changed the drive permissions.

**Comment by ojw28** [comment]
@erdemguven - Please could you check the provided content?

**Comment by tonihei** [comment]
I still can't access the file. Can you check the permissions again?
