### ISSUE TITLE
How to get current playing mediaMetaDataCompat to update the UI while using concatenatingmediasource.

### ISSUE THREAD

**Issue by praveenraikar** [google/ExoPlayer#5947]
I have using ConcatenatingMediaSource to implement queue. Once media starts playing I will get the current media source index in exoplyer callback using mSimpleExoPlayer.currentWindowIndex and can fetch the corresponding media source.
But in order to update the UI I need mediaMetaDataCompat object which holds all info related to the current playing audio file. How to get the mediaMetaDataCompat object of current playing audio file?

**Comment by marcbaechinger** [comment]
You need to provide the `MediaMetadataCompat` object yourself by using a [`MediaMetadataCompat.Builder`](https://developer.android.com/reference/android/support/v4/media/MediaMetadataCompat.Builder.html). 

You need to do some kind of book keeping in your backing data to be able to match the `currentWindowIndex` with the index in your data and then create a metadata object with a builder.

If you have metadata in the media you can add a metadata output by using SimpleExoPlayer.addMetadataOutput(). You can refer to the [EventLogger](https://github.com/google/ExoPlayer/blob/44293e8f45fc62ff918001b4425c44d0ded5ffc9/library/core/src/main/java/com/google/android/exoplayer2/util/EventLogger.java#L264), which logs the arriving metadata to the console as text. You can convert this metadata into a `MediaMetadataCompat` object this way if you have all that data available in the media.
