### ISSUE TITLE
Should I change the DownloadService from an ordinary service to a JobService for Android O and above?

### ISSUE THREAD

**Issue by Gensoukyou1337** [google/ExoPlayer#5950]
### [REQUIRED] Searched documentation and issues
https://github.com/google/ExoPlayer/issues/5539

### [REQUIRED] Question
Before I go on, I'm on Exoplayer v2.9.6.

I got the same error from the above issue, and then I started thinking whether turning the DownloadService into a JobService would solve things, since it depends on work conditions than time (and would probably be canceled or stopped when the app goes into the background).

As of now, I've moved the `onStartCommand()` code to the `onStartJob()` block, since it seemed logical, and my startWithAction() code now looks like:

    Bundle extras = buildTransientBundleExtrasForDownload(downloadAction, foreground);

        JobScheduler jobScheduler = (JobScheduler) context.getSystemService(JOB_SCHEDULER_SERVICE);
        ComponentName componentName = new ComponentName(context, clazz);
        JobInfo jobInfo = new JobInfo.Builder(1, componentName)
                .setOverrideDeadline(0)
                //.setRequiresCharging(true)
                .setTransientExtras(extras)
                .build();
        jobScheduler.schedule(jobInfo);

The code seemingly works fine, but for some reason the DownloadManager won't notify when the download is completed (it won't call `onTaskStateChanged()` returning `STATE_COMPLETE`, only `STATE_QUEUED` or `STATE_STARTED`). The download does complete, however - the cache for the file was complete.

Am I missing something, or is this an unreasonable move from the start?

**Comment by ojw28** [comment]
Why don't you just start the service in the foreground to avoid this problem?

**Comment by ojw28** [comment]
Closing due to lack of follow up.
