### ISSUE TITLE
DASH: Support last segment message (lmsg)

### ISSUE THREAD

**Issue by srampur** [google/ExoPlayer#5952]
Hi,
  ExoPlayer does not have implementation for the lmsg to indicate the last segment as per [https://dashif.org/docs/DASH-IF-IOP-v4.3.pdf] _4.4.3.5. Last Segment Message_ .

Reason to go with this approach is that the player to server communication would be more with shorter minimumUpdatePeriod, so will make minimumUpdatePeriod as random number and indicate using lmsg (last segment) to do the mpd request from client to server.

 Could you please give some details on how to achieve and implement.

Tried to invoke mpd refresh/download from DefaultDashChunkSource class but unable to find the function to invoke.

Apologies, creating as a bug could not find tag to make it as Feature.

**Comment by ojw28** [comment]
Marking as an enhancement.

**Comment by ojw28** [comment]
I filed https://github.com/Dash-Industry-Forum/DASH-IF-IOP/issues/345 to request clarification on `lmsg` with DASH-IF. It's unclear why it's really needed.

**Comment by ojw28** [comment]
Marking as low priority because DASH-IF are also skeptical of this feature and whether there's a valid use case for it.

**Comment by ojw28** [comment]
This feature doesn't seem to have any industry traction, so I think we can go ahead and close the request.
