### ISSUE TITLE
getCurrentWindow() for CastPlayer gives always 1

### ISSUE THREAD

**Issue by mkaflowski** [google/ExoPlayer#5955]
When I use CastPlayer with multiple sources, seek track and the track finishes for every next track getCurrentWindow() gives 1.

I believe that `remoteMediaClient.getMediaStatus().getIndexById()` gives wrong results.
I can get the right result by:
`Arrays.binarySearch(remoteMediaClient.getMediaQueue().getItemIds(),remoteMediaClient.getMediaStatus().getCurrentItemId() )`

Changing the method fetchCurrentWindowIndex() works for me:
```java
private int fetchCurrentWindowIndex(@Nullable MediaStatus mediaStatus) {
        Integer currentItemId = mediaStatus != null
                ? Arrays.binarySearch(remoteMediaClient.getMediaQueue().getItemIds(),remoteMediaClient.getMediaStatus().getCurrentItemId() ) : null;
        return currentItemId != null ? currentItemId : -1;
    }
```

It can be the bug in MediaStatus from com.google.android.gms.cast.

**Comment by AquilesCanta** [comment]
This is another manifestation of #4964. A fix will be referenced below this comment soon.

**Comment by AquilesCanta** [comment]
This should be fixed in the dev branch. Please try it out, and let me know if you encounter any issues.
