### ISSUE TITLE
onVideoInputFormatChanged vs onDownstreamFormatChanged

### ISSUE THREAD

**Issue by andresdiez** [google/ExoPlayer#5956]
Just wanted to know the difference between onDownstreamFormatChanged and onVideoInputFormatChanged. On my project Im trying to get bitrate from format but bitrate on format from onVideoInputFormatChanged is always -1 but the one from onDownstreamFormatChanged contains a valid bitrate.

**Comment by ojw28** [comment]
I think the bitrate should be set correctly in most cases, as of 2.9.0. What version are you using?

The difference is the reporting component. Data flows from a `MediaSource` to `Renderer`s in ExoPlayer. `onDownstreamFormatChanged` is reported by the `MediaSource`. `onVideoInputFormatChanged` is reported by the video `Renderer`. There is also `onAudioInputFormatChanged` which is reported by the audio `Renderer`.

Note that in the case of muxed media, there may be one `onDownstreamFormatChanged` (for audio+video muxed into a single stream), where-as there would be two corresponding events from the `Renderer`s (`onVideoInputFormatChanged` and `onAudioInputFormatChanged`), which receive the individual components of the stream after demuxing.

For your use case, using `onDownstreamFormatChanged` is probably easier.

**Comment by AfanasievAnton** [comment]
Isn`t it more safe to extract current bitrate from onTrackChanged() by getting the selected format from the renderer that we are interested?
And if no, what is the main difference, between this two approaches?

Thanks

**Comment by andresdiez** [comment]
ojw28 we are using r2.4.1

**Comment by ojw28** [comment]
> Isn`t it more safe to extract current bitrate from onTrackChanged() by getting the selected format from the renderer that we are interested?

I'm not really sure exactly what you mean by this, but it seems preferable get everything you need through a single event (which I think is what `onDownstreamFormatChanged` will give you), rather than having to query the tracks and the renderers and tie the data back together.
