### ISSUE TITLE
same format,one support and another one one not support

### ISSUE THREAD

**Issue by longtengyiyu** [google/ExoPlayer#5958]
not supported
ID                                       : 1
文件格式                                     : AVC
文件格式/信息                                  : Advanced Video Codec
格式简介                                     : Main@L5.1
格式设置, CABAC                              : 是
格式设置, ReFrames                           : 2 frames
格式设置, GOP                                : M=2, N=60
编码设置ID                                   : avc1
编码设置ID/信息                                : Advanced Video Coding
长度                                       : 34秒 900ms
Source_Duration/String                   : 35秒 900ms
码率模式                                     : VBR
码率                                       : 12.2 Mbps
最大码率                                     : 768 Kbps
画面宽度                                     : 1 524像素
画面高度                                     : 2 708像素
画面比例                                     : 0.563
帧率模式                                     : 可变
帧率                                       : 60.000 fps
最小帧率                                     : 30.000 fps
最大帧率                                     : 60.000 fps
原始帧率                                     : 25.000 fps
色彩空间                                     : YUV
色度抽样                                     : 4:2:0
位深度                                      : 8位
扫描方式                                     : 逐行扫描
bits/(pixel*frame)(数据密度)                 : 0.049
大小                                       : 50.9 MiB (100%)
Source_StreamSize/String                 : 50.9 MiB (100%)
标题                                       : Core Media Video
编码日期                                     : UTC 2017-12-07 08:14:21
标记日期                                     : UTC 2017-12-07 08:14:55
colour_range                             : Limited
颜色初选                                     : BT.709
传输特质                                     : BT.709
矩阵系数                                     : BT.709
supported
ID                                       : 1
文件格式                                     : AVC
文件格式/信息                                  : Advanced Video Codec
格式简介                                     : High@L4
格式设置, CABAC                              : 是
格式设置, ReFrames                           : 4 frames
编码设置ID                                   : avc1
编码设置ID/信息                                : Advanced Video Coding
长度                                       : 7分 3秒
码率                                       : 2 180 Kbps
画面宽度                                     : 1 920像素
画面高度                                     : 1 080像素
画面比例                                     : 16:9
帧率模式                                     : 恒定
帧率                                       : 30.000 fps
色彩空间                                     : YUV
色度抽样                                     : 4:2:0
位深度                                      : 8位
扫描方式                                     : 逐行扫描
bits/(pixel*frame)(数据密度)                 : 0.035
大小                                       : 108 MiB (94%)
编码函数库                                    : x264 core 148
编码设置                                     : cabac=1 / ref=3 / deblock=1:0:0 / analyse=0x3:0x113 / me=hex / subme=7 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=1 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=6 / lookahead_threads=1 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=3 / b_pyramid=2 / b_adapt=1 / b_bias=0 / direct=1 / weightb=1 / open_gop=0 / weightp=2 / keyint=250 / keyint_min=25 / scenecut=40 / intra_refresh=0 / rc_lookahead=40 / rc=abr / mbtree=1 / bitrate=2180 / ratetol=1.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / ip_ratio=1.40 / aq=1:1.00
语言                                       : English

**Comment by ojw28** [comment]
This issue is being closed because it doesn't contain sufficient information. Please fill out the issue template in full when filing an issue.
