### ISSUE TITLE
how can i get the current playing video url？

### ISSUE THREAD

**Issue by jaychou2012** [google/ExoPlayer#5960]
when i was playing video, which method i will listen to get the current video url？

And how can i get the current playing video url？

Thanks very much

**Comment by ojw28** [comment]
You pass the URL to the player (indirectly, by building a `MediaSource`). So you should already know what it is. If the question is specifically in the context of playlists, please see [this documentation](https://exoplayer.dev/playlists.html#identifying-playlist-items).

**Comment by catbaxter** [comment]
Ok, the following situation - there is a redirect and I would like to know the redirected url
