### ISSUE TITLE
Trying to access downloaded segment data of a dash stream before it is plays. 

### ISSUE THREAD

**Issue by sr1990** [google/ExoPlayer#5961]
Exoplayer question: 
Trying to access downloaded segment data

### [REQUIRED] Searched documentation and issues
Github issues

### [REQUIRED] Question
I need to access data  for DASH stream that resembles the entire segment after it is downloaded but before it is played. 
In onChunkLoadCompleted, I am able to get the uri and bytes read but not the data. 
So tried to expose the buffer from read() method in StatsDataSource to onChunkLoadCompleted, but not sure if I am getting the correct data/ the entire segment. 
Can someone please let me know how to access the entire segment data or if I should look somewhere else?

Thanks

**Comment by ojw28** [comment]
> I need to access data for DASH stream that resembles the entire segment after it is downloaded but before it is played.

ExoPlayer starts playing the segment before it's fully downloaded, so this is not possible.

It's unclear what you're trying to do here. Please could you phrase it more in terms of what feature you're trying to implement, and why accessing the data in this way is necessary to support that feature.

**Comment by sr1990** [comment]
I wanted to access the entire segments (compressed sample) to do something similar to bug #5913. I will take a look at SampleQueue and get back to you if I have any questions. 
Thanks for your time. Closing for now.

**Comment by ChetanTayal138** [comment]
> I wanted to access the entire segments (compressed sample) to do something similar to bug #5913. I will take a look at SampleQueue and get back to you if I have any questions.
> Thanks for your time. Closing for now.

Hello , have you been able to make any sort of progress on this? I am trying to achieve something similar and it would be really helpful if you could send me in the right direction. Thanks
