### ISSUE TITLE
DPAD ui navigation - dispatchKeyEvent doesn't reset the timer for hiding player controller

### ISSUE THREAD

**Issue by sviety** [google/ExoPlayer#5963]
### [REQUIRED] Issue description
I'm updating exoplayer version in my TV application from 2.6 to the newer version (2.9+) and i noticed that during navigation using DPAD PlaybackControlView auto hide timer is not being reset on key events.
Older version (2.6) was working properly - PlaybackControlView was being hiden after few moments since last KeyEvent. I'm using simmilar implementation as demo applcation for handling key events, so the dispatchKeyEvent method in Activity is handled in a same fashion.

### [REQUIRED] Reproduction steps
Use demo application on devices with AndroidTV and use DPAD to navigate on player components.

### [REQUIRED] Link to test content
N/A

### [REQUIRED] A full bug report captured from the device
N/A

### [REQUIRED] Version of ExoPlayer being used
2.10.1 and 2.9.2

### [REQUIRED] Device(s) and version(s) of Android being used
Xiami MI BOX Android 8.0
emulator Android TV 8.0

**Comment by ojw28** [comment]
Fixed by https://github.com/google/ExoPlayer/commit/6e7012413bf0f6ae7f3885caa1001988cc5d5f89.
