### ISSUE TITLE
Track selections

### ISSUE THREAD

**Issue by andresdiez** [google/ExoPlayer#5967]
I Looked every where but the is not concrete answer

Exoplayer 2.4
In a master.m3u8 with 7 renditions available will exoplayer select renditions based on device capabilities, is so how do I get this list? I know exoplayer has onTracksChanged which provide a TrackGroupArray of the renditions available on the master.m3u8 but i'm actually looking for the list of renditions that a device is capable of playing. Ie: if a device is capable of rendering resolution 720x640 but master.m3u8 contains a list from 540x480 up to 1920x1080. how do I know if resolutions over 720x640 where not selected.

**Comment by ojw28** [comment]
> will exoplayer select renditions based on device capabilities

Yes, and also based on any constraints that you've specified on `DefaultTrackSelector`. Please see the [Track selection page](https://exoplayer.dev/track-selection.html) of our developer site for more information about setting constraints.

> I know exoplayer has onTracksChanged which provide a TrackGroupArray of the renditions available on the master.m3u8 but i'm actually looking for the list of renditions that a device is capable of playing.

`MappedTrackInfo` is a good source of this information. Take a look at `EventLogger.onTracksChanged` to see how you can query it. If you use the demo app you can see what `EventLogger.onTracksChanged` outputs in the logs. For example:

```
EventLogger: tracksChanged [2.32, 0.00, window=0, period=0,
EventLogger:   Renderer:0 [
EventLogger:     Group:0, adaptive_supported=YES [
EventLogger:       [X] Track:0, id=133, mimeType=video/avc, bitrate=261112, codecs=avc1.4d4015, res=426x240, fps=30.0, supported=YES
EventLogger:       [X] Track:1, id=134, mimeType=video/avc, bitrate=671331, codecs=avc1.4d401e, res=640x360, fps=30.0, supported=YES
EventLogger:       [X] Track:2, id=135, mimeType=video/avc, bitrate=1204535, codecs=avc1.4d401f, res=854x480, fps=30.0, supported=YES
EventLogger:       [X] Track:3, id=160, mimeType=video/avc, bitrate=112329, codecs=avc1.4d400c, res=256x144, fps=30.0, supported=YES
EventLogger:       [X] Track:4, id=136, mimeType=video/avc, bitrate=2400538, codecs=avc1.4d401f, res=1280x720, fps=30.0, supported=YES
EventLogger:     ]
EventLogger:   ]
EventLogger:   Renderer:1 [
EventLogger:     Group:0, adaptive_supported=YES_NOT_SEAMLESS [
EventLogger:       [ ] Track:0, id=139, mimeType=audio/mp4a-latm, bitrate=48582, codecs=mp4a.40.5, channels=2, sample_rate=22050, supported=YES
EventLogger:       [X] Track:1, id=140, mimeType=audio/mp4a-latm, bitrate=127868, codecs=mp4a.40.2, channels=2, sample_rate=44100, supported=YES
EventLogger:     ]
EventLogger:   ]
EventLogger: ]
```

Where [X] means a track has been selected for use, and `supported=Y` indicates the level of support.that the device provides for the track.
