### ISSUE TITLE
Why method for getting information needs to be called on main thread

### ISSUE THREAD

**Issue by tprochazka** [google/ExoPlayer#5969]
Why methods like these:

  @Override
  public long getDuration() {
    verifyApplicationThread();
    return player.getDuration();
  }

  @Override
  public long getCurrentPosition() {
    verifyApplicationThread();
    return player.getCurrentPosition();
  }

needs to be called on main thread?
It doesn't touch ani view, it just returns a variable value?

I'm calling this from WebVia via @JavascriptInterface and it is on a different thread, but still just on one thread.

There is no reason to write this warning for all the methods, ale where it is not necessary.
Or I miss something?

Related to version: 2.10.1

**Comment by ojw28** [comment]
> It doesn't touch any view, it just returns a variable value?

If you look into what `player.getDuration()` and `player.getCurrentPosition()` do, they do a lot more than just returning variable values. They are not safe to call on arbitrary threads. ExoPlayer's threading model is described [here](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/ExoPlayer.html). Note that it's not a hard requirement that the main thread is used. Although it is a hard requirement that the thread has an associated `Looper`:

> ExoPlayer instances must be accessed from a single application thread. For the vast majority of cases this should be the application's main thread. Using the application's main thread is also a requirement when using ExoPlayer's UI components or the IMA extension. The thread on which an ExoPlayer instance must be accessed can be explicitly specified by passing a `Looper` when creating the player. If no `Looper` is specified, then the `Looper` of the thread that the player is created on is used, or if that thread does not have a `Looper`, the `Looper` of the application's main thread is used. In all cases the `Looper` of the thread from which the player must be accessed can be queried using Player.getApplicationLooper().

**Comment by tprochazka** [comment]
Thanks. So it means that I can directly use the thread used by WebView. I just need to create Player itself on the same thread and this thread must have a looper. I will try to go this way.
