### ISSUE TITLE
MP4 video is stopping exactly at same point consistently

### ISSUE THREAD

**Issue by devenkhari** [google/ExoPlayer#597]
Hi,

I've been consistently observing that the my mp4 files stop at a particular point and that point if different for different files. Once it is stuck, nothing can be done like forward, rewind, retry, etc. I'm not able to debug it as the emulators are not able to play the files, I can only play them on the device.
The files are large about 20+ MB. If I run a smaller file, less than 5mb, it runs completely.

Pls suggest what could be going wrong or how can I debug?

Regards,
Deven

**Comment by ojw28** [comment]
Is this using ExtractorSampleSource? Does it only happen with your files, or with all content? Could you provide a sample that exhibits the issue?

As for debugging, it's perfectly possible to attach a debugger to the process running on a real device; you shouldn't need to use an emulator at all if you have a physical device.

**Comment by devenkhari** [comment]
I did not make changes in ExtractorSampleSource although I would need to for the purpose of decryption of the encrypted video file. Currently, I'm calling PlayerActivity with contentURI of a decrypted mp4 file in sdcard and problem is in playing it. The same decrypted file plays fine in other standard video player on android.
I'm developing on linux (ubuntu) and the device I have is not recognized on linux so can't directly debug with the device.

Thanks for helping.

Regards,
Deven

**Comment by devenkhari** [comment]
Yes, it is with using ExtractorSampleSource.

**Comment by devenkhari** [comment]
Please find a sample video to reproduce the problem at my public repository https://github.com/devenkhari/Test

The player stops after playing for 42 seconds of this video while other standard players on Android are playing this file completely without any problem.

Regards,
Deven

**Comment by andrewlewis** [comment]
When I add the linked file as a sample in the demo app with TYPE_MP4 it seems to play back correctly all the way through (about four minutes).

If you're using the master branch, please could you check whether you see the same behavior on the dev branch? Is it reproducible for you when playing that video from the demo app?

**Comment by ojw28** [comment]
Please re-open if you can still reproduce as per the instructions above.
