### ISSUE TITLE
Exoplayer v2 playerView.hideController() not hiding controllers

### ISSUE THREAD

**Issue by anandsingh2903** [google/ExoPlayer#5972]
Exoplayer v2 playerView.hideController() not hiding controllers.

```
if (type.equalsIgnoreCase("live")) {
			/*DefaultTimeBar timeBar = controlView.findViewById(R.id.exo_progress);
			timeBar.setVisibility(View.GONE);
			//LinearLayout buttonControls = controlView.findViewById(R.id.lay_button_controls);
			//buttonControls.setVisibility(View.GONE);
			TextView startTime = controlView.findViewById(R.id.exo_position);
			startTime.setVisibility(View.GONE);
			TextView endTime = controlView.findViewById(R.id.exo_duration);
			endTime.setVisibility(View.GONE);*/
			mVideoView.hideController();
		}
		else {
			//System.out.println("jef");
			//mVideoView.showController();
		}
```

**Comment by ojw28** [comment]
I tried changing `PlayerActivity.onClick` to hide the controller when the track selection button gets pressed, as an experiment, and the controller is hidden correctly.

I think this is probably an issue with your application code. If you can create a small patch to the ExoPlayer demo app illustrating that it really is an ExoPlayer issue, please do so and share it here.

**Comment by ojw28** [comment]
Closing due to lack of information.
