### ISSUE TITLE
Allow OfflineLicenseHelper to be configured in Widevine L3 mode

### ISSUE THREAD

**Issue by KarlGallagher** [google/ExoPlayer#5974]
### [REQUIRED] Use case description
Some applications force use of Widevine L3 for protected playback.
In offline use-cases, persistent keys must therefore also be acquired via a L3 DRM session given that L1 keys cannot be restored to L3 session and vice-versa 

### Proposed solution
Extend the static constructor(s) to accept configuration param related to the desired DRM robustness setting.

### Alternatives considered
None

**Comment by ojw28** [comment]
I think this is already possible. To force use of L3 for playback, you are probably calling something like:
```
drmSessionManager.setPropertyString("securityLevel", "L3")
```
On `OfflineLicenseHelper` you can do the [same thing](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/drm/OfflineLicenseHelper.html#setPropertyString-java.lang.String-java.lang.String-). Please clarify if this doesn't work for you.

**Comment by KarlGallagher** [comment]
@ojw28 

My bad, just noticed this.
