### ISSUE TITLE
Not able to get the duration/progress of the video, in playing HEVC. The total duration seems to come negative.

### ISSUE THREAD

**Issue by rahulpsingh123** [google/ExoPlayer#5977]
Not able to get the duration/progress of the video, in playing HEVC. The total duration seems to come negative. Any help in this regard would be highly appreciated.

That's the URL that I've been trying to play:
https://d3sko9ovoyz71z.cloudfront.net/video/hevc-0/BAC78AB8-330B-4696-86A1-6CD22D776BF3.mp4

the video plays, but, I cannot show the proper progress bar, as it doesn't return the current duration correctly.

**Comment by ojw28** [comment]
The duration looks fine to me in the ExoPlayer demo app. The file isn't seekable because for some reason it's an FMP4 file that doesn't contain a sidx atom. It should probably have one, which would allow seeking.
