### ISSUE TITLE
Exoplayer not working for Android 6.0 and below

### ISSUE THREAD

**Issue by 1604020** [google/ExoPlayer#5983]
I am using Exoplayer to play videos from a URL. It works like a charm for Android 7.0 and above but the player freezes and gives error 400 while playing in Android 6.0. Please help

**Comment by AquilesCanta** [comment]
Can you please provide the URL for us to look? We will, at least, need to reproduce the issue in order to help.

**Comment by AquilesCanta** [comment]
You can send it to dev.exoplayer@gmail.com if you don't want to post it here.

**Comment by abhishekBansal** [comment]
I can reproduce this issue as well. Only for Android 6.0 and below.
Here is more info
I am trying to play an audio clip. Sending audio clip url to dev.exoplayer@gmail.com. Same audio clip plays for Android 7 and above devices.

Library versions
```
    api 'com.google.android.exoplayer:exoplayer-core:2.10.4'
    api 'com.google.android.exoplayer:exoplayer-ui:2.10.4'
```

Device Details
Its reproducible on emulator running android 6 as well. Other then that it got reproduced on `LG-X230I` running Android 6.

Let me know if more details are needed.

**Comment by ojw28** [comment]
It's because you have spaces in your URL (which is discouraged pretty much in all cases; if you want a separator you should use a dash). If you must have spaces in your URLs, you should encode them as `%20`. If you replace each space with `%20` in the link you provided then playback works fine in the demo app.

**Comment by abhishekBansal** [comment]
Seems like that was the issue, thanks! Still wondering why it was not working only on Android 6 and below.

**Comment by ojw28** [comment]
The most likely possibility is that the network stack implementation was changed to also handle non-escaped spaces in newer releases.

**Comment by tonihei** [comment]
See also #5334 for a similar issue

**Comment by abhishekBansal** [comment]
Okay Thanks! Please close the issue as I don't seem to have that access.
