### ISSUE TITLE
Getting the current track: getCurrentWindowIndex() returns wrong index

### ISSUE THREAD

**Issue by shailesh9898** [google/ExoPlayer#5985]
Getting the current track: getCurrentWindowIndex() returns wrong index

**Comment by AquilesCanta** [comment]
Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md).

If this refers to the cast extension, please track #5955.

**Comment by ojw28** [comment]
Closing due to lack of information.
