### ISSUE TITLE
When I play the HTTP URL, I find a bug 

### ISSUE THREAD

**Issue by Programmer-Jared** [google/ExoPlayer#5987]
Hello, I have a problem using EXOplayer! When I play the url, play until the last few seconds, occasional error: "com. Google. Android. Exoplayer2. Upstream. FileDataSource $FileDataSourceException: Java. IO. FileNotFoundException: : open failed: ENOENT (No to the file or directory)"

Test environment: android6.0, android 5.0;

I need your help. Thank you.

**Comment by AquilesCanta** [comment]
That would mean that the file you are trying to play is not there. 

Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/content_not_playing.md).

I will reopen the issue once the missing information is provided.

**Comment by AquilesCanta** [comment]
Please fill the [issue template](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/content_not_playing.md) by updating the original post and commenting below, or directly filing in a new comment.

**Comment by ojw28** [comment]
Closing due to lack of information.
