### ISSUE TITLE
Exoplayer 2.10.1 - Download retro-compatibility and performance

### ISSUE THREAD

**Issue by kvillnv** [google/ExoPlayer#5989]
**EDIT**: Initially, I opened this thread for a question about retro-compatibility. Since then I found a solution, and wrote it in my **2nd** message, and still would like to have your feedback, as I found that retro-compatibility with ActionFileUpgradeUtil does not seem to be optimum.
And now, there are new questions about critical issues in my **3rd** message.

Hello,
I would like to know if the method `ActionFileUpgradeUtil.upgradeAndDelete(...)` is supposed to migrate all the finished downloads to the new `DownloadIndex` or only the ones that are QUEUED/DOWNLOADING?

It seems that it is not the case.  
If so, how can we add all the previous `Download` to the new `DownloadIndex`?
This would allow us to also read our old downloads with the new `DownloadHelper.createMediaSource` method.

By previous Downloads, I mean finished downloads made using ActionFile on Exoplayer v2.9.6 and before.  

**Edit:**
So from my understanding, in the demo, the DownloadActions of finished recordings were saved in the TRACKER_ACTION_FILE.. We thought this tracker was your way on the demo to show information about Downloads. But for our case, our app has its own database for tracking downloads and their metadata, but no DownloadAction saved.
**As it was mentioned in the documentation (see below)**
So now I understand that because we don't have this file, we cannot do the `upgradeAndDelete` on our previous downloads?

Here is a copy of the documentation of the DownloadTracker class in your previous versions:
`Tracks media that has been downloaded.
Tracked downloads are persisted using an {@link ActionFile}, however in a real application
  it's expected that state will be stored directly in the application's media database, so that it
  can be queried efficiently together with other information about the media. `

Please let me know how to generate Downloads or DownloadRequests linked to my previously downloaded content, or generate TRACKER_ACTION_FILE with all the Finished Downloads. 
Or any other suggestion to handle previous downloads would be appreciated.

Thanks

**Comment by kvillnv** [comment]
I think I've got my solution: I don't want to take the risk of losing data because of missing indexation, and I am thinking about compatibility with next versions as well.
**Your feedback would be appreciated**. Here is what I did:

I was able to create `DownloadRequests` and `Downloads` from the data of the old downloads I saved in my app and add them in the `DownloadIndex,` but my data is not really indexed and is deleted by the SimpleCache. So I didn't try more.
And as you might remember I have a custom implementation with multi-folder, different to yours and working with just 1 actionFile. (see #4253 for reference)
But now that the cache management has been upgraded in exoplayer, I prefer of course to move to your version without any customization. 
So this is possible for me to use at 100% the new exoplayer version for all my next downloads.
And my solution for reliable retro-compatibility is to keep my previous downloads' sub-folders in a separate folder. This way I can manually build my MediaSources.
As they are not in the DownloadIndex, I will not be able play them with `DownloadHelper.createMediaSource` and I will also delete them with an alternate method.

Adding the internal Database to Exoplayer is really great for sure. I just feel like If in early versions of exoplayer-offline the actionFile and trackerActionFile were internal as well, the transition to the new Exoplayer version would be better. 

However, if you think there is a way for me to get the indexation for all my downloads folders, and if you think this is not risky for the data and future versions, please let me know.
If not, my current solution is reliable and works.

@ojw28 , about your last post in #4253: I can confirm the new cache management is good now, playback loading time is lightning fast compared to the previous single-folder cache management.
**EDIT:** **Oops I spoke too quick: It seems that I am getting a lot of garbage collector processes when DownloadManager is using the cache with 2 parallel downloads, then I get OOMs (the device just reboots), but my cache is barely 300GB.
Are the commits #5986 going to fix this on 2.10.2?**

Thanks for the hard work guys!

PS: We can save in cache live streams during playback. So I was wondering if you would consider creating a new downloader able to cache live streams without the need to play at the same time? (Download live dash stream with widevine protection)

**Comment by AquilesCanta** [comment]
Please @erdemguven have a look.

**Comment by kvillnv** [comment]
Hi, 
The new issues mentioned below are critical, for now I will not use the download feature from exoplayer's 2.10.x.
Please let me know if 2.10.2 is has fixes for these:

**1.**
Have you noticed that now the SimpleCache seems to trigger a lot of GC, and OOMs/hard reboots?
To reproduce it, try to have more than 300GB of downloaded assets on an external storage.

(copy from my last message:
It seems that I am getting a lot of garbage collector processes when DownloadManager is using the cache with 2 parallel downloads, then I get OOMs (the device just reboots), but my cache is barely 300GB.
Are the commits #5986 going to fix this on 2.10.2?)

**2.**
Also I noticed that the SimpleCache initialization is slow for the first playback after starting the app (40 seconds to start playing a 1GB asset with 2MB chunks. With a total of 300GB of DASH assets downloaded). As long as you don't restart the app, the next playbacks are fine on any other asset.

**NOTE:**
With Exoplayer versions before 2.10 and a custom implementation of multi-folder download (1 folder per asset, 1 SimpleCache instance per folder). With up to 500GB of downloads none of these issues ever happened.

**Comment by kvillnv** [comment]
Please see my previous messages. I am still postponing exoplayer update in my project.

**Comment by kvillnv** [comment]
Any updates? specially about the performance issues

**Comment by kvillnv** [comment]
@ojw28 @erdemguven @AquilesCanta

**Comment by ojw28** [comment]
Apologies for the lack of update on this issue. We are very busy at the moment, and have not had a chance to take an in depth look at this yet.

Please note that your personal top priorities my not always be aligned with the project's top priorities. Note also that we update issues when we have updates, so the lack of an update by definition means there is no update. There's no need to repeatedly ping the issue tracker. Thanks!

**Comment by ojw28** [comment]
Closing as suggested on https://github.com/google/ExoPlayer/issues/7567.
