### ISSUE TITLE
Video at 0:00 plays audio that is supposed to be at 0:08 mark. Video speeds up to try to sync with the audio.

### ISSUE THREAD

**Issue by marcochin** [google/ExoPlayer#5990]
### [REQUIRED] Content description
The video starts with audio that is supposed to play at the 0:08 second mark so it almost feels like it skips a sound segment. The video for the first few seconds speeds up so that it tries to sync up with the audio. Since timing is off, the video freezes prematurely at the end. Tried it with the demo app and behavior is seen there as well. This behavior is not exhibited when video is played with quicktime player/ safari.

### [REQUIRED] Link to test content
This is a HLS video.
Sent link to dev.exoplayer@gmail.com

### [REQUIRED] Version of ExoPlayer being used
2.10.1, 2.10

### [REQUIRED] Device(s) and version(s) of Android being used
Nvidia Shield, Google Pixel

**Comment by AquilesCanta** [comment]
Playlists are not aligned, at least two of them have different program-date-times. You'll have to fix the content:

#EXT-X-PROGRAM-DATE-TIME:2019-05-22T14:28:26.068000+00:00
#EXT-X-PROGRAM-DATE-TIME:2019-05-22T14:28:33.477000+00:00

**Comment by marcochin** [comment]
We understand the problem now, but based on the spec here (https://tools.ietf.org/html/draft-pantos-http-live-streaming-13), "The client MUST NOT depend upon the correctness or the consistency of the value of the EXT-X-PROGRAM-DATE-TIME tag." Is that the correct guidelines for hls? For us, unfortunately the encoding of these files is being done by someone else and we have no control.

**Comment by ojw28** [comment]
That part of the spec seems to have been dropped from version 19 onward. In my opinion it didn't make much sense to begin with, since if a client can't rely on it being correct then its existence isn't particularly useful.

**Comment by AquilesCanta** [comment]
@marcochin, you may consider injecting your own playlist parser and dropping the EXT-X-PROGRAM-DATE-TIME tags. For VOD content, it shouldn't affect playback.

**Comment by marcochin** [comment]
Yea, we're gonna remove the EXT-X-PROGRAM-DATE-TIME tags server side. Thanks!
