### ISSUE TITLE
Redmi Note-4 is under-reporting video playback capabilities

### ISSUE THREAD

**Issue by GouravSna** [google/ExoPlayer#5991]
**Question:** On Redmi Note-4, `getTrackSupport` in `TrackSelectionView` class does not return the device capability result properly. 

I added all the tracks available for the following media, then I could see that device is capable enough to play the 10.29 Mbps(4k) media.

**Issue:** `getTrackSupport` should return the proper device capable tracks. Is there some issue in this method or should i use any other method to get the results correct.

**Comment by GouravSna** [comment]
One more question:

Can we achieve this by checking the track codec with the deviceSupported codec types ?

Ex:

`MediaCodecList.getCodecCount()` // Total codec count

Then by looping over all the codec counts,
```

final MediaCodecInfo codecInfo = MediaCodecList.getCodecInfoAt(i);
     for (String supportedType : codecInfo.getSupportedTypes()) {
```
then if codec is supported then shall we decide that the device is capable to play the video/audio ?

**Comment by GouravSna** [comment]
@ojw28 , please suggest.

**Comment by AquilesCanta** [comment]
I am assuming the track is reported as "NO_EXCEEDS_CAPABILITIES". If that's the case it's possible that the device is under-reporting capabilities. I don't think we work around these issues on the ExoPlayer side. You can implement a custom Track Selector that does overrides this selection for you. You can also contact the device manufacturer about this issue. Any input on this @ojw28?

**Comment by ojw28** [comment]
Without proper, complete and precise reproduction steps, there's nothing we can do to efficiently look at this issue. Please provide some.

**Comment by GouravSna** [comment]
**Steps to reproduce:**
**Media Stream URL:** https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8 
**Branch:** dev-v2

**Steps:**

1. In `TrackSelectionView` class, line ~274

_Replace:_ 
`if (mappedTrackInfo.getTrackSupport(rendererIndex, groupIndex, trackIndex)
            == RendererCapabilities.FORMAT_HANDLED) {
          trackView.setFocusable(true);
          trackView.setTag(Pair.create(groupIndex, trackIndex));
          trackView.setOnClickListener(componentListener);
        } else {
          trackView.setFocusable(false);
          trackView.setEnabled(false);
        }`

_with this,_
`
 /*  if (mappedTrackInfo.getTrackSupport(rendererIndex, groupIndex, trackIndex)
            == RendererCapabilities.FORMAT_HANDLED) {*/
          trackView.setFocusable(true);
          trackView.setTag(Pair.create(groupIndex, trackIndex));
          trackView.setOnClickListener(componentListener);
        /*} else {
          trackView.setFocusable(false);
          trackView.setEnabled(false);
        }*/
`

2. In Select tracks dialog, select the bottom video track,

4096 * 1744, 10.29 Mbps 

3. Press OK.

**Result:**

On **Moto G6**, it fails with decoder init failed, which is fine because device is not capable enough to play this.

`     Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(7, null, null, video/avc, avc1.4D4033, 10285391, null, [4096, 1744, -1.0], [-1, -1])
`

On **Redmi Note-4 Snapdragron**, it plays this video tracks although `if (mappedTrackInfo.getTrackSupport(rendererIndex, groupIndex, trackIndex)
            == RendererCapabilities.FORMAT_HANDLED)` return `false`; so by this means this device should not be capable enough.

**Comment by ojw28** [comment]
Please disregard the @google-oss-bot comment above.

**Comment by ojw28** [comment]
Closing as an obsolete device specific issue.
