### ISSUE TITLE
How To Wait Player Until Load MetaData ?

### ISSUE THREAD

**Issue by Navidhp** [google/ExoPlayer#5992]
i use HlsMedia in exoplayer , some time metaData not loaded completely It causes controller have a problem (duration movie not completely show , pause and play hide when touched) , i guess unloading metadata causes problems , how to wait player until meta data load completely ? thanks

**Comment by AquilesCanta** [comment]
I don't know what the issue is here. Please fill this [template](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md) including precise reproduction steps, expected and actual behavior.

**Comment by Navidhp** [comment]
@AquilesCanta this is my mistake i solved
