### ISSUE TITLE
DialogFragement

### ISSUE THREAD

**Issue by MicahSphelele** [google/ExoPlayer#5994]
**ExoPlayer does not display video when playing from DialogFragment (FullScreen Dialog) on my P20 Lite**

**Comment by AquilesCanta** [comment]
Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/content_not_playing.md).

**Comment by ojw28** [comment]
Closing due to lack of required information.
