### ISSUE TITLE
Requirements for being able to use ProgressiveMediaSource

### ISSUE THREAD

**Issue by nametable** [google/ExoPlayer#5999]
### [REQUIRED] Searched documentation and issues
I have looked at a question on stackoverflow related to my problem I'm having: https://stackoverflow.com/questions/56118614/why-cant-i-locate-progressivemediasource. On github I don't see any issues directly related to the problem I'm having.

### [REQUIRED] Question
My [question](https://stackoverflow.com/questions/56463793/how-to-make-progressivemediasource-usable-in-exoplayer-symbol-not-found) is what the requirements are to be able to use ProgressiveMediaSource? In my app after including ExoPlayer 2.10.1 in gradle, I get an error when trying to import the library. 
`import com.google.android.exoplayer2.source.ProgressiveMediaSource;`
Have I missed something about this in the documentation? Could this be an AndroidX related issue (somehow having some remaining com.android.support libs)? I do have some other libraries as dependencies - is it possible that they could be conflicting?

**Comment by AquilesCanta** [comment]
What kind of error are you getting? I can't assist much with the provided information. 

> Could this be an AndroidX related issue (somehow having some remaining com.android.support libs)?

I doubt it. I wouldn't expect an issue in ProgressiveMediaSource, which is pretty much stand-alone.

> My question is what the requirements are to be able to use ProgressiveMediaSource? 

Importing ExoPlayer from gradle should be enough. I suggest you start a fresh project and depend on ExoPlayer from there, so you can see how it's supposed to work. Then you can add dependencies until you narrow down the possible source of the issue.

**Comment by nametable** [comment]
Error was due to human transcription error. I had typed progessive instead
of progressive and never noticed until much later 😫

Lesson: if a symbol can't be found, make sure you spelled it correctly.
