### ISSUE TITLE
How do I determine the currently selected stream (HLS)

### ISSUE THREAD

**Issue by palakRpatel** [google/ExoPlayer#600]
I have successfully integrated player in my project. Now I want to check which URI it is picking for HLS on various network types (3G,2G etc). But I am not able to trace exact location in the code. Can you please let me know where can I get the same?

**Comment by palakRpatel** [comment]
also please let me know how to read manifest.xml

**Comment by ojw28** [comment]
If you're using the demo app as a starting point, you'll see that DemoPlayer.InfoListener has an onVideoFormatEnabled method. This method is invoked whenever the format changes, and a Format object is passed containing information about the format that was selected.
