### ISSUE TITLE
Exoplayer play one url until the last few seconds,this url doesn't play anymore

### ISSUE THREAD

**Issue by Programmer-Jared** [google/ExoPlayer#6001]
[REQUIRED] Searched documentation and issues
I have looked at a question on stackoverflow related to my problem .On github I don't see any issues directly related to the problem I'm having.
[REQUIRED] Question
Hello,I have a problem using EXOplayer!
When I play the url, play until the last few seconds,occasional error:
Detail log information：
"com. Google. Android. Exoplayer2. Upstream. FileDataSource $FileDataSourceException: Java. IO. FileNotFoundException: : open failed: ENOENT (No to the file or directory)"
Test environment:
android6.0, android 5.0 has this problem.
I need your help. Thank you.

**Comment by AquilesCanta** [comment]
Please don't file duplicate issues. Follow the instructions provided in #5987.
