### ISSUE TITLE
removeListener not wokring in android 5.1 and 6.1

### ISSUE THREAD

**Issue by web30india** [google/ExoPlayer#6003]
### [REQUIRED] Issue description
I am using Exo Player for Url Video play. its working fine in higher version of Android, but when I am trying to play video with Android version 5.1 and 6.1, once video play in my activity and I go to back activity then video sound not stop its playing continues and when I open other video and again go to back activity then multiple video sound play in my current activity. I have also use removeListener and all needed code, but still, I am facing the same issue. so please help me for the same.

### Reproduction steps
I have used Exo player in my application

### Reproduction steps
initialize player with given URL (i will send you video URL in email)

### Version of ExoPlayer being used
2.7.3

 ### Device(s) and version(s) of Android being used
Android 5.1 and 6.1 version in my Samsung, vivo, and Mi mobile

**Comment by AquilesCanta** [comment]
Sounds like you are not correctly releasing the player when you are transitioning out of the activity. It is not in the scope of the issue tracker to debug apps. Make sure you are cleaning up resources, like illustrated in the DemoApp's [PlayerActivity](https://github.com/google/ExoPlayer/blob/release-v2/demos/main/src/main/java/com/google/android/exoplayer2/demo/PlayerActivity.java).
