### ISSUE TITLE
ExoPlayer misreporting position of mp3

### ISSUE THREAD

**Issue by MelvinKellner** [google/ExoPlayer#6005]
### [REQUIRED] Issue description
ExoPlayer seems to return the incorrect position during playback.

### [REQUIRED] Reproduction steps
1: Start audio playback
2: Seek to a certain time. (it gets more noticeable the further you seek)
3: Compare audio at that position with another audio player.

### [REQUIRED] Link to test content
https://downloads.sensotec.be/OnlineDaisy/9bfb_0005.mp3

### [REQUIRED] A full bug report captured from the device
None

### [REQUIRED] Version of ExoPlayer being used
2.10.1

### [REQUIRED] Device(s) and version(s) of Android being used
Every device

**Comment by tonihei** [comment]
See https://exoplayer.dev/troubleshooting.html#why-are-some-media-files-not-seekable and similar issues, e.g. https://github.com/google/ExoPlayer/issues/328#issuecomment-168532148 .
