### ISSUE TITLE
Identify IMA postroll ads in stream 

### ISSUE THREAD

**Issue by akanksha-hegde** [google/ExoPlayer#6008]
I'm creating an analytics sdk which requires to collect stream details using exoplayer listeners. We have IMA ads integrated with streams. Is there a way to identify if there are postroll ads in the video?

**Comment by AquilesCanta** [comment]
Is the information in [Timeline.Period](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/Timeline.Period.html) sufficient? Also see [Timeline](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/Timeline.html) for more useful info.

**Comment by akanksha-hegde** [comment]
With the Timeline we can get the periods but is there way to identify it has postroll or not?

**Comment by AquilesCanta** [comment]
Apologies. I've just realized that I was looking at a non-released version of the javadoc. 

See [getAdGroupTimeUs](https://github.com/google/ExoPlayer/blob/624bb6b8d1709852e8cffc5c67eb7d5debd9e848/library/core/src/main/java/com/google/android/exoplayer2/Timeline.java#L402)'s javadoc in the dev branch:

> The time of the ad group at the index, in microseconds, or {@link C#TIME_END_OF_SOURCE} for a post-roll ad group.

This javadoc will be available in the next release, but the behavior of the method is already there.
