### ISSUE TITLE
Midroll ads freeze frame after playing

### ISSUE THREAD

**Issue by meenukrishnamurthy** [google/ExoPlayer#6009]
### [REQUIRED] Content description
Play a video with midroll ad,seek beyond the point of midroll ad,then the midroll ad is played and the video playing resumes after ad.If we seek backward the frame freezes.

### [REQUIRED] Link to test content
Video Url : http://184.72.239.149/vod/smil:BigBuckBunny.smil/playlist.m3u8
Ads url : https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpost&cmsid=496&vid=short_onecue&correlator=
### [REQUIRED] Version of ExoPlayer being used
Version : Exoplayer 2.9.6.I have also checked with the 2.10.0 version.Same issue exists

### [REQUIRED] Device(s) and version(s) of Android being used
Honor View 10,API 28

**Comment by tonihei** [comment]
I can reproduce a slightly different problem using the same reproduction steps, but  I think they both have the same underlying reason. 

Under the given setup, we end up with negative renderer timestamps and not all platform decoders handle negative timestamps well. In my case, the decoder made rounding errors, changing the frame timestamps by 1 microsecond each, which results in a lot of dropped frames after the seek. I guess the "frozen" frame is a similar problem based on how the Honor View decoder is handling the negative timestamps.
