### ISSUE TITLE
ExoPlayer stalling when playing 4K H265 files

### ISSUE THREAD

**Issue by Leondev7** [google/ExoPlayer#6010]
### Searched documentation and issues
I have searched the ExoPlayer docs as well as all issues i've found here related with H265 and 4K formats, but I'm not able to find the solution.

### Question
Hi I'm currently working in a multi player project and we are using ExoPlayer for video and audio playing purposes.
Right now I'm working in the prototype and testing how far the player can go.
The problem I've encountered it's that the ExoPlayer stalls and stops at some frames when playing a 4k H265 encoded video both in local and streaming. 
The video is this one
https://www.libde265.org/hevc-bitstreams/bbb-3840x2160-cfg02.mkv

I've tried with my own implementation and with the ExoPlayer demo and it stalls in both of them.
I've also tried to play the video with the following applications:
-VLC (Does not play)
-Kodi (Plays smoothly)
-MXPlayer (Plays smootly)

The device I'm testing with is a Motorola G5 Plus with Android 8.1 but we plan to provide this application with a Quad-core ARM Cortex-A53 CPU up to 1.5GHz & Quad-core Mali450 GPU based device. (I will provide data as soon as I have it)

Code
```
 private val defaultBandwidthMeter = DefaultBandwidthMeter.Builder(context).build()

    private val dataSourceFactory: DefaultDataSourceFactory

    private val extractorsFactory = DefaultExtractorsFactory()	 

    private val renderersFactory = buildRenderersFactory(useExtensionRenderers = true, 
    preferExtensionRenderer = true)

    val exoPlayer :SimpleExoPlayer =  ExoPlayerFactory.newSimpleInstance(
    context, renderersFactory,  DefaultTrackSelector(), DefaultLoadControl())

    val dataSourceFactory = DefaultDataSourceFactory(context,
    defaultBandwidthMeter,DefaultHttpDataSourceFactory(  Util.getUserAgent(context, 
    "MKDPlayer"), 	defaultBandwidthMeter))

    val mediaSource = ProgressiveMediaSource.Factory(dataSourceFactory,extractorsFactory)
            .setCustomCacheKey("ExoPlayerAdapter")
            .createMediaSource(uri)
        exoPlayer.prepare(mediaSource)
```
The question is if MXPlayer and Kodi can play the video, what can I do to improve the video playback quality with ExoPlayer. Do I need to provide exoplayer with faster decoders? Is there a problem with my code? Do I need to reduce the framerate of the video? Thanks in advance for the library it's so much better than the Android stock one

**Comment by tonihei** [comment]
I think both mentioned player apps use their own bundled decoders and not the system decoders as ExoPlayer. I can also observe the same performance problems on an older device (Nexus 6P), but it plays smoothly on a new device (Pixel 3). So I would conclude that the platform decoders on the tested device are just not performant enough to cope with the stream whereas more recent devices should be able to handle the load well.

**Comment by tonihei** [comment]
Closing because the question was probably answered.
