### ISSUE TITLE
DefaultTimeBar with rounded corners

### ISSUE THREAD

**Issue by Kelmatou** [google/ExoPlayer#6011]
### [REQUIRED] Searched documentation and issues
I've search in Github issues, Exoplayer documentation, googled my question and looked on stackoverflow

### [REQUIRED] Question
I'm looking for a way to get rounded corners on DefaultTimeBar. I couldn't find how to create my custom DefaultTimeBar.
Maybe there is already a way to achieve it so for now I'm just asking you the question.

**Comment by tonihei** [comment]
You can customize all elements of our UI module to your needs. Please have a look at https://exoplayer.dev/ui-components.html#overriding-layout-files.

**Comment by Kelmatou** [comment]
Yes I've read about that and I am already customizing the different layout elements.
But I cannot find how to make DefaultTimeBar corners rounded.
I've tried android:radius="10dp" but it doesn't change anything

**Comment by tonihei** [comment]
Creating customized UI elements is out of scope for this issue tracker. It's best to ask such question on StackOverflow or similar sites. If you think that ExoPlayer can't supported a type of custom UI following the guidelines above, please let us know.
