### ISSUE TITLE
is X-TIMESTAMP-MAP necessary for sync caption with video ? (HLS)

### ISSUE THREAD

**Issue by Navidhp** [google/ExoPlayer#6012]
in hls video when change seek or progress video , caption not sync video and 2 second latter video , is X-TIMESTAMP-MAP necessary for sync caption with video ? or another way to fix this ? thanks

exoplayer-version : 2.9.6

**Comment by AquilesCanta** [comment]
> X-TIMESTAMP-MAP necessary for sync caption with video

Depends. In general, yes. As per [spec](https://tools.ietf.org/html/rfc8216#section-3.5):

`If a WebVTT segment does not have the X-TIMESTAMP-MAP, the client
   MUST assume that the WebVTT cue time of 0 maps to an MPEG-2 timestamp
   of 0.`
