### ISSUE TITLE
How to set default video quality to higher one?

### ISSUE THREAD

**Issue by BROUDING** [google/ExoPlayer#6013]
I've searched many places, but I couldn't really get the right answer for me..

So my player have a custom button to "set High quality bitrate", and when the user click that button, I find the highest bitrate within the `currentMappedTrackInfo` and override that index via `setSelectionOverride(RENDERER_TYPE_VIDEO, trackGroups, override)`. (As I understood, default value is "Auto" and video plays as the user device's bandwidth goes)

It works all fine and pretty easy.

But now I want to set High quality bitrate as a default bitrate, basically I want to initialize the player with higher bitrate. As you can see, for now, I'm overriding selection after initializing the video..... How can I initialize the player with higher bitrate...?  

(Feels like the solutions would be setting minimum bitrate as higher value....)

Thank you !!

**Comment by Navidhp** [comment]
@BROUDING i have problem like you but i solved like this , when run this your player ready and manifest has been loaded : 

`MappingTrackSelector.MappedTrackInfo` `mappedTrackInfo=trackSelector.getCurrentMappedTrackInfo();`
        `if (mappedTrackInfo != null) {`
            `TrackGroupArray trackGroupArray;`
           ` for (int i = 0; i < mappedTrackInfo.getTrackGroups(indexVideoRendered).length; i++) {`
                `trackGroupArray = mappedTrackInfo.getTrackGroups(i);`
                `for (int j = 0; j < trackGroupArray.get(i).length; j++) {`
                  `if(i == trackGroupArray.get(i).length - 1) {`
                   `DefaultTrackSelector.Parameters newParameters = 
           trackSelector.buildUponParameters().setMaxVideoBitrate(trackGroupArray.get(i).getFormat(j).bitrate).build();`
                  ` trackSelector.setParameters(newParameters);`
                  `       }`
               `      }`
          `       }`
       `     }`


sorry for my bad english

**Comment by tonihei** [comment]
We have a parameter in the `DefaultTrackSelector` called `forceHighestSupportedBitrate` which selects the highest supported bitrate for audio and video in all cases. Is that what you are looking for? Note that it will then always play the highest supported bitrate independent of the bandwidth; that is, it won't switch down automatically if the network isn't fast enough.

**Comment by tonihei** [comment]
Closing because the question was probably answered.
