### ISSUE TITLE
API 'variantOutput.getPackageLibrary()' is obsolete and has been replaced with 'variant.getPackageLibraryProvider()

### ISSUE THREAD

**Issue by Siletskiy** [google/ExoPlayer#6016]

**Comment by Siletskiy** [comment]
WARNING: API 'variantOutput.getPackageLibrary()' is obsolete and has been replaced with 'variant.getPackageLibraryProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variantOutput.getPackageLibrary(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
Affected Modules: extension-cast

**Comment by tonihei** [comment]
I can't find this call anywhere in our gradle files nor can I see this warning when syncing or building our code. Could you please provide more detailed reproduction steps and information about which versions of gradle, ExoPlayer etc are used?

**Comment by ojw28** [comment]
This only happens when `exoplayerPublishEnabled = true` is set in the root `build.gradle`, and is due to https://github.com/novoda/bintray-release/issues/260. I don't think you need to worry about it. I'll flip the flag to false in the release branches to stop this from being visible to developers.
