### ISSUE TITLE
playback aes 128 ctr  MinuteTimer.mp4   stream

### ISSUE THREAD

**Issue by mehdirouhandeh** [google/ExoPlayer#6018]
Hi team..I want to play an encrypted stream(aes 128 ctr).
one time I try to use AesCipherDataSource class to do that but I got an error
how can I decrypt and play that..?

**Comment by mahdi302** [comment]
is there anyone to help me..please.

**Comment by tonihei** [comment]
Please fill out the issue template and provide all the requested information when filing an issue.
