### ISSUE TITLE
Player currentPosition is 0 on PlayerNotificationManager.onNotificationCancelled

### ISSUE THREAD

**Issue by AleksandarKovachev** [google/ExoPlayer#6020]
### [REQUIRED] Issue description

The currentPosition is 0 on dismissing the player from the PlayerNotificationManager with method onNotificationCancelled. Also in the EventListener.onPlayerStateChanged the currentPosition is 0.

### [REQUIRED] Reproduction steps

1. Start the ExoPlayer with PlayerNotificationManager
2. Release the player from the notification
3. Check the currentPosition of the player on dismissing the notification and releasing the player.

###  [REQUIRED] Link to test content

-

### [REQUIRED] A full bug report captured from the device

-

### Version of ExoPlayer being used
ExoPlayer version 2.10.1

### Device(s) and version(s) of Android being used
Android API 28

**Comment by marcbaechinger** [comment]
The `PlayerNotificationManager` uses roughly `Player.add/removeEventListener` and setters methods of the player which is passed to `PlayerNotificationManager.setPlayer(player)`. These do not affect the playback position. Besides this no other methods are called, which potentially could affect the position of the player.

I added the `PlayerNotificationManager` to `PlayerActivity` of the demo app. Then I paused at 0:20, dismissed the notification and then continued playback at 0:20 in the player activity. The playback position has not been reset to 0.

Can you provide some code around what you do in `onNotificationCancelled` of your notification listener. I don't exactly understand what you mean with step 2 and 3?

**Comment by AleksandarKovachev** [comment]
I am running the player in foreground service. In the foreground service, I have EventListener and in the EventListener.onPlayerStateChanged I am saving the currentPosition in shared preferences. When I am dismissing the PlayerNotification (clicking the stop button) while still playing, the method EventListener.onPlayerStateChanged is called with 0 currentPosition.

**Comment by marcbaechinger** [comment]
When the `PlayerNotificationManager` receives the `ACTION_STOP` action, it calls `controlDispatcher.dispatchStop(player, /* reset= */ true)`. This resets the player, which means the position is reset to 0. 

You can intercept this call by using your own `ControlDispatcher`. Something like this:

```
playerNotificationManager.setControlDispatcher(new DefaultControlDispatcher() {
      @Override
      public boolean dispatchStop(Player player, boolean reset) {
        // store current position to shared preferences now.
        return super.dispatchStop(player, reset);
      }
});
```

**Comment by AleksandarKovachev** [comment]
Perfect! This helped me a lot. Thank you!
