### ISSUE TITLE
Adaptive streams not working in Android Pie

### ISSUE THREAD

**Issue by waakobrian** [google/ExoPlayer#6023]
### [REQUIRED] Content description
When testing adaptive streams on versions lower than API 28, adaptive streams work perfectly well. But when testing on API level 28, i get a playback error in the onPlayerError callback and nothing plays.
Tested on Samsung A30

### [REQUIRED] Link to test content
http://qthttp.apple.com.edgesuite.net/1010qwoeiuryfg/sl.m3u8

### [REQUIRED] Version of ExoPlayer being used
`implementation 'com.google.android.exoplayer:exoplayer:2.8.2'`

### [REQUIRED] Device(s) and version(s) of Android being used
```
    compileSdkVersion 28
    defaultConfig {
        minSdkVersion 19 
        targetSdkVersion 28
    }
```

**Comment by marcbaechinger** [comment]
This plays for me on a Pixel and the emulator with API 28.

Can you please provide a bug report taken on the Samsung A30, which includes the playback error which you mention? Please add your uri above to the demo app of the most recent version and provide the bug report for playing it in the [demo app](https://exoplayer.dev/demo-application.html) so we can rule out other isssues.

**Comment by waakobrian** [comment]
Solved by allowing clear text traffic in manifest.

```
<application
        android:usesCleartextTraffic="true"
....
```
