### ISSUE TITLE
Add a way to set proxy for the individual media streams

### ISSUE THREAD

**Issue by mvenkat3272** [google/ExoPlayer#6024]
my content is delivered from the gateway at a particular port and not on HTTP port. I need to configure the player to contact a proxy server running in the gw . my understanding is that currently there is no mechanism to do that. Can this be added ?

**Comment by tonihei** [comment]
It's slightly unclear from your question what the requirements are exactly, but ExoPlayer already handles all URIs including HTTP ports and also follows server redirects. This is happening by default without any further configuration required.

In case you need to change the URI for each request dynamically (e.g. to insert to port into an existing URI), you can use a `ResolvingDataSource` which will be added in 2.10.2, or implement one yourself similar to the example in #5779.
