### ISSUE TITLE
Questions on implementation of https://github.com/google/ExoPlayer/issues/4780

### ISSUE THREAD

**Issue by letianxu** [google/ExoPlayer#6025]
### [REQUIRED] Searched documentation and issues
I have looked the forum issues list.

### [REQUIRED] Question
The question is about #2 implementation in issue: https://github.com/google/ExoPlayer/issues/4780

2. Have DefaultDashChunkSource set endOfStream based on whether the period duration is known. It shouldn't be necessary to look at manifest.dynamic, manifest.durationMs or whether it's the last period in the manifest. I think just looking at the period duration being known covers all of these cases.

Because endOfStream is decided as following:

long periodDurationUs = representationHolder.periodDurationUs;
boolean periodEnded = periodDurationUs != C.TIME_UNSET;

And we know for some live manifest, it is possible period duration is set, so periodEnded is true, and the endOfStream is set to true, as a result the live stream will not continue to load segment, is that safe if we add !manifest.dynamic  back to endOfStream:

out.endOfStream = periodEnded && !manifest.dynamic;

**Comment by tonihei** [comment]
@ojw28 Can you take a look and check whether the request makes sense in the context of the DASH specs?

**Comment by ojw28** [comment]
> is that safe if we add !manifest.dynamic back to endOfStream

I don't think so, because it wont work for the multi-period manifest case.

Can you provide more detail about the use case. When would the period duration be known for a period prior to it ending? Is this a live event use case where you know the duration in advance, or similar?
