### ISSUE TITLE
Add tunneling option in demo app

### ISSUE THREAD

**Issue by gramound** [google/ExoPlayer#6026]
### [REQUIRED] Use case description
Give access to enabling/disabling tunneling from the demo app UI.

### Proposed solution
Add it to the corner options menu of SampleChooserActivity.

### Alternatives considered
Calling setTunnelingAudioSessionId unconditionally (use it if available). Would that be simpler or cause trouble?

**Comment by tonihei** [comment]
Unfortunately, we can't include all possible features in our demo app, as this would make it harder to follow the most important bits. Note that we are planning to provide more specialist demo apps for different use cases in the future and we should consider adding a tunneling option to at least one of them (see #5854). 

If you want to try out the tunneling feature yourself, you can just set the `tunnelingAudioSessionId` in the `Parameters` of `DefaultTrackSelector`. It won't be used if the renderers can't support it.
