### ISSUE TITLE
Does Exoplayer work out the best hardware supported stream?

### ISSUE THREAD

**Issue by LukasRoper** [google/ExoPlayer#6028]
Hi,

I'm using an external plugin for a Unity project (AvPro) and we're using HLS streaming to play 360 video. The stream contains a 4k version, 1080p version, etc.

Probably a bit of a beginner question but on older devices that can't decode 4k video, does the exoplayer manage to exclude that quality of stream from being used and revert instead to a lower quality version? Finding it difficult to find anything that determines if we have to manage that in any fashion?

Thanks,

**Comment by tonihei** [comment]
Yes, that's handled automatically. If you are using HLS (or any other adaptive streaming format), the player selects the quality based on device capabilities and measured network speed (if applicable).

**Comment by tonihei** [comment]
Closing because the question was probably answered.
