### ISSUE TITLE
NullPointerException when invoking method on player view

### ISSUE THREAD

**Issue by ardinh** [google/ExoPlayer#6035]
```
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.exoplayer2.ui.SimpleExoPlayerView.setPlayer(com.google.android.exoplayer2.Player)' on a null object reference
```

**Comment by marcbaechinger** [comment]
Seems like you are having a `NullPointerException` when calling `setPlayer` on the player view. 

You can fix this yourself by making sure you found the ui component by id and then assign it to the variable before calling the method. Also make sure the player view is included in the layout file you are using.

**Comment by ardinh** [comment]
private void initializePlayer() {
        if (player == null) {
            // 1. Create a default TrackSelector
            LoadControl loadControl = new DefaultLoadControl(
                    new DefaultAllocator(true, 16),
                    VideoPlayerConfig.MIN_BUFFER_DURATION,
                    VideoPlayerConfig.MAX_BUFFER_DURATION,
                    VideoPlayerConfig.MIN_PLAYBACK_START_BUFFER,
                    VideoPlayerConfig.MIN_PLAYBACK_RESUME_BUFFER, -1, true);

            BandwidthMeter bandwidthMeter = new DefaultBandwidthMeter();
            TrackSelection.Factory videoTrackSelectionFactory =
                    new AdaptiveTrackSelection.Factory(bandwidthMeter);
            TrackSelector trackSelector =
                    new DefaultTrackSelector(videoTrackSelectionFactory);
            // 2. Create the player
            player = ExoPlayerFactory.newSimpleInstance(new DefaultRenderersFactory(this), trackSelector, loadControl);
            videoFullScreenPlayer.setPlayer(player);
        }
    }

this is my code an the error is on videoFullScreenPlayer.setPlayer(player);
