### ISSUE TITLE
Playing non-raw asset local file giving EACCESS (Permission denied) even though it exists

### ISSUE THREAD

**Issue by darrinps** [google/ExoPlayer#6039]
This is similar to https://github.com/google/ExoPlayer/issues/1321 but I have verified that both read and write external permissions have been granted and the issue still persists. I can play from the raw-assets folder fine as well as stream a video but I cannot get ExoPlayer to play any local .mp4 video. I downloaded the standard "bunny" video to verify it was a valid video and played it outside of Exoplayer to be certain. So I know the video can be played.

This is the exception being thrown:

```
2019-06-14 11:01:11.688 4965-5051/com.android.myapp E/ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.upstream.FileDataSource$FileDataSourceException: java.io.FileNotFoundException: /storage/emulated/0/Download/SampleVideo_1280x720_2mb.mp4: open failed: EACCES (Permission denied)
        at com.google.android.exoplayer2.upstream.FileDataSource.open(FileDataSource.java:73)
```

This is an example code snippet to reproduce it. Note that playing from assets works fine.

```        
         player = ExoPlayerFactory.newSimpleInstance(this, DefaultTrackSelector())
        playerView.player = player
        player?.addListener(this)

        val dataSource = DefaultDataSourceFactory(this, Util.getUserAgent(this, "Exoplayer"))
        var path: String = ""
        var mediaSource: ExtractorMediaSource

        if (passedUrl == PLAY_TUTORIAL) {
            path = "asset:///tutorial_video.mp4"
            mediaSource = ExtractorMediaSource.Factory(dataSource).createMediaSource(Uri.parse(path))
        } else {
            path = passedUrl
            val file = File(path)
            val uriPath = Uri.fromFile(file)
            file.setReadable(true, false);

            Timber.d("Path is $uriPath and that file exists = ${file.exists()} can read =${file.canRead()} size = ${file.length()}")

            mediaSource = ExtractorMediaSource.Factory(dataSource).createMediaSource(uriPath)
        }

        player?.prepare(mediaSource)
```
When I execute that code, the file does exist but can read returns false. The file size is as expected. 

Note that I have been testing this on a Pixel 3XL device with Android Q beta loaded. Perhaps that is the issue? Has something changed on Q that is causing this?

**Comment by darrinps** [comment]
Here is a sample output from a run of the code

```
2019-06-14 11:01:02.404 4965-4965/com.android.myapp I/MainInteractionActivity: Permission to read external storage is already granted
2019-06-14 11:01:02.404 4965-4965/com.android.myapp I/MainInteractionActivity: Permission to write external storage is already granted
2019-06-14 11:01:08.652 4965-4965/com.android.myapp D/ViewTutorialActivity: Path is file:///storage/emulated/0/Download/SampleVideo_1280x720_2mb.mp4 and that file exists = true can read =false size = 2107842
```

**Comment by tonihei** [comment]
It sounds as if it is related to https://developer.android.com/preview/privacy/scoped-storage#filtered-view .
Can you check if changing the target sdk version back down solves the issue?

**Comment by darrinps** [comment]
This is what I had: 

```
android {
    compileSdkVersion 29
    defaultConfig {
        applicationId "com.android.myapp"
        minSdkVersion 26
        targetSdkVersion 29
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
```

I changed the targetSdkVersion to 26. That didn't help though. Same thing as before exactly.

**Comment by tonihei** [comment]
Might be that changing the target version doesn't help. Can you try this as well: https://developer.android.com/preview/privacy/scoped-storage#opt-out-of-filtered-view ?

**Comment by darrinps** [comment]
I tried this:

```
    <application
            android:name=".MyApp"
            android:requestLegacyExternalStorage="true"
            android:allowBackup="true"
            android:icon="@mipmap/ic_launcher"
```

Doing that didn't help, but I am going to go through the entire article and try other things next

**Comment by darrinps** [comment]
So I've got good news, and I have bad news. The good news is that when I used an emulator targeting SDK 25, it works (2019-06-14 19:07:14.688 13963-13963/com.android.myapp D/ViewTutorialActivity: Path is file:///storage/emulated/0/Download/SampleVideo_1280x720_5mb.mp4 and that file exists = true can read =true size = 5253880.....notice the can read = TRUE!)

The bad news of course is that what you have now is going to fail on every Q device that tries to read locally like I did. Is there a procedure you can think of? What I did by following Google's suggestions (the link provided above) did not work.

**Comment by darrinps** [comment]
Here is the setup for the record that works for me running on an emulator of a Nexus with Android version 7.

```
android {
    compileSdkVersion 29
    defaultConfig {
        applicationId "com.android.myapp"
        minSdkVersion 25
        targetSdkVersion 29
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
```

**Comment by tonihei** [comment]
I just tried it out myself and `android:requestLegacyExternalStorage="true"` seems to fix the issue. Note that you need to uninstall the app first for this parameter to take effect. Also note that this parameter is only temporary to ease the transition and will likely stop working in the future

Closing as this is a generic Android development problem and access to storage needs to be fixed for targeting Android Q anyway.

**Comment by tonihei** [comment]
Filed #6045 to address this problem in our demo app.
