### ISSUE TITLE
Video is not displayed in LG google TV (Jelly Bean)

### ISSUE THREAD

**Issue by aravinds03** [google/ExoPlayer#604]
Hi,
I have integrated latest version of exoPlayer in my app and it performs really well in all mobile and tablet devices. It also worked well in amazon fire devices. But, it did not work in LG google tv (running jelly bean). The issue is that video is not displayed, but audio is playing. It happens for all .m3u8 files.

**Comment by bsysop** [comment]
Can you post some verbose log?

**Comment by ojw28** [comment]
It's unlikely we'll invest any effort in fixing this if it's a specific to this device or to GoogleTV devices. GoogleTV is quite an old platform at this point.

**Comment by aravinds03** [comment]
Hi,
LG google tv is running on android version with api 19 and above. So, it is not old version.
Since new android version does not have permission to read entire logs including framework, I manage to get logs that my app is recording from the customer device and it is available here https://www.dropbox.com/s/5yz356fs442whtc/logs.txt?dl=0 .

Please investigate the logs and provide your comments.

**Comment by aravinds03** [comment]
Since this issue is closed, I have opened new one https://github.com/google/ExoPlayer/issues/660 
Let me know if there is capability to reopen this issue, so that I can close other one.
