### ISSUE TITLE
Multi-Period Dash MPD with alternating video codecs (avc3, avc1)

### ISSUE THREAD

**Issue by hyunsang123** [google/ExoPlayer#6050]
Does ExoPlayer support live multi-period DASH manifests with alternating video codecs?

Specifically, the first period is avc3, second is avc1, and so on.

Our live stream breaks at the period boundaries, and we are trying to determine if the breakage is due to the changing video codecs.

**Comment by marcbaechinger** [comment]
This should work AFAIK. 
Can you provide us with a test stream so we can reproduce?
