### ISSUE TITLE
Slow playback speed on Xiaomi Device

### ISSUE THREAD

**Issue by nlgtuankiet** [google/ExoPlayer#6053]
### [REQUIRED] Content description
Slow playback (about 0.3x speed) on some source like Apple 3x4, Youtube Dash but not with Screen 1080p, 480p. Log just say Init and that's it, nothing useful

### [REQUIRED] Link to test content
Demo app

### [REQUIRED] Version of ExoPlayer being used
2.9.6

### [REQUIRED] Device(s) and version(s) of Android being used
Xiaomi Redmi Note 6 Pro, Android 8.1.0
CPU: Snapdragon 636

**Comment by marcbaechinger** [comment]
Can you please take a bug report just a couple of seconds after you started playback and upload here? That would be useful for us, specifically because it seems to be a device specific issue. Many thanks.

**Comment by nlgtuankiet** [comment]
Turn out reset the device fix the problem. Thank for your time though
