### ISSUE TITLE
Cant find prepare() method

### ISSUE THREAD

**Issue by Sulistyarif** [google/ExoPlayer#6058]
Somebody can tell me ?
Why i cant find method prepare() ?
After mediasource created, i must set player to prepare to mediasource, but i cant find prepare() method.

**Comment by marcbaechinger** [comment]
There is the `Player` interface and the `ExoPlayer` interface. The prepare methods are defined by the `ExoPlayer` interface (which extends the `Player` interface).

When you create a player with `ExoPlayerFactory` you get an instance of `SimpleExoPlayer` which implements the `ExoPlayer` interface and hence has two prepare methods:

```
SimpleExoPlayer simpleExoPlayer = ExoPlayerFactory.newSimpleInstance(this);
...
simpleExoPlayer.prepare(mediaSource);
```

Take a look in the [initializePlayer of the demo app ](https://github.com/google/ExoPlayer/blob/release-v2/demos/main/src/main/java/com/google/android/exoplayer2/demo/PlayerActivity.java#L413)also.
