### ISSUE TITLE
No audio on HLS v4 playback

### ISSUE THREAD

**Issue by seventhmoon** [google/ExoPlayer#606]
When the HLS is in v4 format. There will have no audio output.

Tested on Nexus 5 running Android 5.1

Testing source:
http://b028.wpc.azureedge.net/80B028/Samples/a38e6323-95e9-4f1f-9b38-75eba91704e4/5f2ce531-d508-49fb-8152-647eba422aec.ism/Manifest(format=m3u8-aapl)

**Comment by ojw28** [comment]
This issue is effectively tracked by #73, since the only audio track available in this stream is a separate de-muxed audio stream.
