### ISSUE TITLE
Why reused audio decoders can reduce the probability of frame drops when transitions occur?

### ISSUE THREAD

**Issue by Romantic-LiXuefeng** [google/ExoPlayer#6060]
From [https://medium.com/google-exoplayer/improved-decoder-reuse-in-exoplayer-ef4c6d99591d](url)
> Enabling audio decoders to be reused reduces the amount of work that the player has to do when transitioning from one piece of media to the next in a playlist, reducing the probability of frame drops when transitions occur.

I can't understand why Enabling audio decoders to be reused can reduce the probability of frame drops when transitions occur. 

In my opinion, when transition occur in a playlist, if the next media video stream is't starting with key frame, the video decoder need to look for key frame, at the same time, using the reused decoder, the audio stream already played.  Maybe causing drop video frames.  Hope you give a suit condition.

**Comment by ojw28** [comment]
> Why reused audio decoders can reduce the probability of frame drops when transitions occur?

Because releasing and re-instantiating an audio decoder when the transition occurs is extra work, which takes time, CPU cycles etc. Freeing those cycles up allows them to be used for video rendering, and in some cases this may be the difference between dropping frames or not dropping them.
