### ISSUE TITLE
How to implement timing subtitle ?

### ISSUE THREAD

**Issue by herudi** [google/ExoPlayer#6061]
i have subtitle and video but not sync. how to implement timing subtitle like faster or slower  time subtitle ?

`00:00:05,000 --> 00:00:15,000
Test sub`

I will show subtitle in subtitleView like so :

`00:00:35,000 --> 00:00:45,000
Test sub`

how to implement timing subtitle ?
thanks for advanced :+1:

**Comment by marcbaechinger** [comment]
If you want to sideload a subtitle file with a video media file you can do this by using a `MergingMediaSource`. [This is documented in the Developer Guide](https://exoplayer.dev/media-sources.html#side-loading-a-subtitle-file), so please take a look and see whether this helps.

I'm not sure what you mean with "faster or slower time subtitle". If the above is not helpful, please give me some more details on what you are trying to do.

**Comment by herudi** [comment]
i'm sorry.... i'm success to implement play video and subtitle with MergingMediaSource. but sometimes video and subtitle not sync time. 
how to change subtitle time ? 
for example 
`00:00:05,000 --> 00:00:15,000`
to
`00:00:35,000 --> 00:00:45,000`

thanks for advanced... :+1:

**Comment by marcbaechinger** [comment]
Ah ok, I understand. :)
Sorry that's currently not possible easily. There is an enhancement #854 around this. 
As of now I think you need to fix the subtitle files and change the timestamps in that file.

I'm closing as a duplicate referring to #854. Please re-open if you thing it needed.

**Comment by herudi** [comment]
ok thanks :)
