### ISSUE TITLE
How to calculate RMS from streaming audio buffer

### ISSUE THREAD

**Issue by nguyenhuy3588** [google/ExoPlayer#6063]
Hi i've successfully streamed audio with ExoPlayer2 core library and HLS plugin, now i want to get the RMS feedback from audio data while ExoPlayer is streaming, i've implemented a custom renderer to receive audio buffer but can't see any params for RMS value, do we have this implemented by default? If yes, how can i use it?

Here i can get the buffer from my custom renderer:

![image](https://user-images.githubusercontent.com/16719961/59754967-5ab21e00-92b1-11e9-8f81-0b1b5362c5a3.png)

**Comment by andrewlewis** [comment]
Assuming getting RMS feedback means you want to calculate the root mean square energy of the PCM audio data (if not please clarify): a more convenient way to do this might be to implement a `TeeAudioProcessor.AudioBufferSink` and do the calculation in there. See #5268. If you don't also want to play the audio you can just set the player volume to zero.

**Comment by nguyenhuy3588** [comment]
Thanks @andrewlewis , i have gone to this

![image](https://user-images.githubusercontent.com/16719961/59758530-50dfe900-92b8-11e9-94e4-7ab4068359e3.png)

I will calculate the rms and feedback to this issue after this.

**Comment by nguyenhuy3588** [comment]
Hi @andrewlewis , i have tried many times, but it seem like only the flush callback get called but not handleBuffer, here is my full setup code:

![image](https://user-images.githubusercontent.com/16719961/59760862-7f13f780-92bd-11e9-9297-1f0705f7b100.png)
![image](https://user-images.githubusercontent.com/16719961/59760907-8f2bd700-92bd-11e9-86e2-d8a4efa8964e.png)

Please help me if i'm wrong.

**Comment by andrewlewis** [comment]
Are you sure `handleBuffer` isn't being called? I think you need to read the bytes between `buffer.position()` and `buffer.limit()`, not between 0 and `buffer.position()`.

**Comment by nguyenhuy3588** [comment]
thanks @andrewlewis , i get it called now, trying to calculate rms, will feedback to us soon.

**Comment by nguyenhuy3588** [comment]
Hi, I have successfully calculated rms value from our ByteBuffer follow the code on [GeeksForGeeks](https://www.geeksforgeeks.org/program-to-calculate-root-mean-square/) and edit it to compatible with ByteBuffer, here the implementation:

![image](https://user-images.githubusercontent.com/16719961/59915260-6a16a000-9446-11e9-81db-1711f814a71f.png)

And full setup code as following @andrewlewis guide:

![image](https://user-images.githubusercontent.com/16719961/59915309-86b2d800-9446-11e9-9fd2-700c7c0c0bcb.png)

Thank you so much.
