### ISSUE TITLE
Support for internal subtitles

### ISSUE THREAD

**Issue by AniLabXTeam** [google/ExoPlayer#6064]
### Question
Does ExoPlayer supports internal subtitles (that included into video container)? 

I can't find any relevant info about it.
For example, i have small mp4 video file with two integrated subtitle tracks- https://drive.google.com/file/d/1Ug-09BXe88VmgTeJ3_5Vf1ZcXkPRiUgH/view

On PC in VLC player, for example, i have ability to select subtitle track. But in exoplayer i can't find a way to load at least first track to use MergedVideoSource. My player implementation succesfully work with external subtitles, so i need info about creating Format object from internal sub.

I will be grateful for any information about this.

### Link to test content
https://drive.google.com/file/d/1Ug-09BXe88VmgTeJ3_5Vf1ZcXkPRiUgH/view

**Comment by marcbaechinger** [comment]
Yes, this is supported.

When I play your media in the ExoPlayer demo app it shows me the following tracks:

```
tracksChanged [0.31, 0.00, window=0, period=0, 
   Renderer:0 [
     Group:0, adaptive_supported=N/A [
       [X] Track:0, id=1, mimeType=video/avc, res=1280x528, fps=29.969791, supported=YES
     ]
   ]
   Renderer:2 [
     Group:0, adaptive_supported=N/A [
       [X] Track:0, id=2, mimeType=audio/mp4a-latm, channels=2, sample_rate=48000, language=eng, supported=YES
     ]
     Metadata [
       TSSE: value=HandBrake 1.2.2 2019022300
     ]
   ]
   Renderer:6 [
     Group:0, adaptive_supported=N/A [
       [ ] Track:0, id=3, mimeType=application/x-quicktime-tx3g, language=rus, supported=YES
     ]
     Group:1, adaptive_supported=N/A [
       [X] Track:0, id=4, mimeType=application/x-quicktime-tx3g, language=eng, supported=YES
     ]
   ]
 ]
```

To enable the English subtitle included in the media in the demo app I did:

```
trackSelector = new DefaultTrackSelector(trackSelectionFactory);
      trackSelector.setParameters(
          trackSelectorParameters.buildUpon().setPreferredTextLanguage("eng"));
```

There is a page about track selection in the developer website:
https://exoplayer.dev/track-selection.html

**Comment by AniLabXTeam** [comment]
@marcbaechinger wow! Such easy solution. Thank you very much :)
