### ISSUE TITLE
Setting margins to standard UI components programmatically

### ISSUE THREAD

**Issue by olenasol** [google/ExoPlayer#6068]
I am trying to set a bit different controls layout when player i in landscape than when it is in portrait. After some searching? I have found issue #4700, where it is stated that you  cannot change   controller_layout_id programmatically. But all I need is to change some margins, but margin on custom components is not changing too, when I set it in code. Is there a way to achieve this with standard components?

**Comment by marcbaechinger** [comment]
Why do you think you can't change margins on custom components? I can for instance change the margins of the `PlayerControlView` like this:

```
FrameLayout.LayoutParams layoutParams = (FrameLayout.LayoutParams) 
    findViewById(R.id.exo_controller).getLayoutParams();
layoutParams.setMargins(120, 120, 120, 120);
```

What layout change do you want to achieve on which component of the `PlayerView` or `PlayerControlView`?

**Comment by olenasol** [comment]
Sorry if the question was unclear. I want to have slightly different controls layouts in landscape and portrait(to achieve this it is enough to change margins).I have tried out the snippet you have provided and it is working. However I am unable to set margin on exo_position and exo_progress in method onConfigurationChanged. To handle orientation changes I am using ConstrainLayoutStates.

**Comment by marcbaechinger** [comment]
This snippet works for me:

```
  @Override
  public void onConfigurationChanged(Configuration newConfig) {
    super.onConfigurationChanged(newConfig);
    LinearLayout.LayoutParams layoutParams = (LinearLayout.LayoutParams)
        findViewById(R.id.exo_position).getLayoutParams();
    if (newConfig.orientation == Configuration.ORIENTATION_LANDSCAPE) {
      layoutParams.setMargins(120, 120, 120, 120);
    } else {
      layoutParams.setMargins(0, 0, 0, 0);
    }

    layoutParams = (LinearLayout.LayoutParams)
        findViewById(R.id.exo_progress).getLayoutParams();
    if (newConfig.orientation == Configuration.ORIENTATION_LANDSCAPE) {
      layoutParams.setMargins(120, 120, 120, 120);
    } else {
      layoutParams.setMargins(0, 0, 0, 0);
    }
  }
```
I see in the Layout Inspector that the margins are applied and the view also shows with the margins applied.

> However I am unable to set margin on exo_position and exo_progress in method onConfigurationChanged. 

Can you elaborate on what is not working? Did you check in the Layout Inspector whether the margins have been applied on the views?

**Comment by olenasol** [comment]
I am sorry it took me so long to respond, I have been on vacation. Your snippet works for me too, but I cannot set margins on exo_progress and exo_position. I have checked the LayoutInspector, it says that margins are not set, but programmatically I am setting them.
Also attaching code that I am using to set margins and what it looks like in portrait and in landscape. As you can see margins on ImageView with id ivScreenSize are setting correctly.
Code:
```java
override fun onConfigurationChanged(newConfig: Configuration) {
        super.onConfigurationChanged(newConfig)
        val newOrientation = newConfig.orientation
        if (newOrientation == Configuration.ORIENTATION_LANDSCAPE) {
             constraintLayoutParent.setState(
                R.id.constraintStateLandscape,
                newConfig.screenWidthDp,
                newConfig.screenHeightDp
            )
            activity?.window?.setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_PAN)
            changeControlsView(true)
        } else if (newOrientation == Configuration.ORIENTATION_PORTRAIT) {
            constraintLayoutParent.setState(
                R.id.constraintStatePortrait,
                newConfig.screenWidthDp,
                newConfig.screenHeightDp
            )
            activity?.window?.setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE)
            changeControlsView(false)
        }
 }
private fun changeControlsView(isLandscape: Boolean) {
        if (isLandscape) {
            exo_progress.setMargins(148, 0, 148, 0)
            exo_position.setMargins(4, 0, 0, 4)
            ivScreenSize.setMargins(0, 0, 4, 4)
        } else {
            exo_progress.setMargins(0, 0, 0, 0)
            exo_position.setMargins(18, 0, 0, 18)
            ivScreenSize.setMargins(0, 0, 18, 18)
        }
    }
fun <T: View> T.setMargins(left:Int, top:Int, right:Int, bottom:Int){
    if (this.layoutParams is ViewGroup.MarginLayoutParams) {
        val p = this.layoutParams as ViewGroup.MarginLayoutParams
        p.setMargins(left, top, right, bottom)
        this.requestLayout()
    }
}
```
Portrait:
![portrait](https://user-images.githubusercontent.com/25776310/61596974-d1289f80-ac12-11e9-9d38-521f7f12f697.png)

Landscape(screenshots are edited but you can still see the point):
![landscape](https://user-images.githubusercontent.com/25776310/61596965-bfdf9300-ac12-11e9-9c2e-662cf3944233.png)

**Comment by olenasol** [comment]
Never mind, found the issue. I was using  Kotlin synthetics and it did not find the correct element but was not showing any error. The correct way to find this was
```java
controls.findViewById<PreviewTimeBar>(R.id.exo_progress).setMargins(148, 0, 148, 0)
```
