### ISSUE TITLE
Bug 2.10.1 com.google.android.exoplayer2.audio.AudioSink$InitializationException: AudioTrack init failed: 0, Config(44100, 12, 44100)

### ISSUE THREAD

**Issue by HiJohn** [google/ExoPlayer#6069]
### Issue description
play failed when run demo app

###  Reproduction steps
run demo app , open youtobe dash video , or anthers .
tips show : Playback failed

### Link to test content
JSON snippet : 
```
  {
    "name": "YouTube DASH",
    "samples": [
      {
        "name": "Google Glass (MP4,H264)",
        "uri": "https://www.youtube.com/api/manifest/dash/id/bf5bb2419360daf1/source/youtube?as=fmp4_audio_clear,fmp4_sd_hd_clear&sparams=ip,ipbits,expire,source,id,as&ip=0.0.0.0&ipbits=0&expire=19000000000&signature=51AF5F39AB0CEC3E5497CD9C900EBFEAECCCB5C7.8506521BFC350652163895D4C26DEE124209AA9E&key=ik0",
        "extension": "mpd"
      },
      {
        "name": "Google Play (MP4,H264)",
        "uri": "https://www.youtube.com/api/manifest/dash/id/3aa39fa2cc27967f/source/youtube?as=fmp4_audio_clear,fmp4_sd_hd_clear&sparams=ip,ipbits,expire,source,id,as&ip=0.0.0.0&ipbits=0&expire=19000000000&signature=A2716F75795F5D2AF0E88962FFCD10DB79384F29.84308FF04844498CE6FBCE4731507882B8307798&key=ik0",
        "extension": "mpd"
      },
      {
        "name": "Google Glass (WebM,VP9)",
        "uri": "https://www.youtube.com/api/manifest/dash/id/bf5bb2419360daf1/source/youtube?as=fmp4_audio_clear,webm2_sd_hd_clear&sparams=ip,ipbits,expire,source,id,as&ip=0.0.0.0&ipbits=0&expire=19000000000&signature=249B04F79E984D7F86B4D8DB48AE6FAF41C17AB3.7B9F0EC0505E1566E59B8E488E9419F253DDF413&key=ik0",
        "extension": "mpd"
      },
      {
        "name": "Google Play (WebM,VP9)",
        "uri": "https://www.youtube.com/api/manifest/dash/id/3aa39fa2cc27967f/source/youtube?as=fmp4_audio_clear,webm2_sd_hd_clear&sparams=ip,ipbits,expire,source,id,as&ip=0.0.0.0&ipbits=0&expire=19000000000&signature=B1C2A74783AC1CC4865EB312D7DD2D48230CC9FD.BD153B9882175F1F94BFE5141A5482313EA38E8D&key=ik0",
        "extension": "mpd"
      }
    ]
  }
```

###  A full bug report captured from the device
event log : 

[exoplayerlog.txt](https://github.com/google/ExoPlayer/files/3310236/exoplayerlog.txt)

###  Version of ExoPlayer being used
 latest version ,

###  Device(s) and version(s) of Android being used
Google Pixel ,Android 9.0 , targetSdkVersion 28

**Comment by umangsaini** [comment]
Similar to [#954](https://github.com/google/ExoPlayer/issues/954)
"adb shell dumpsys media.audio_flinger" may help.

**Comment by HiJohn** [comment]
[media_audio_flinger_log.txt](https://github.com/google/ExoPlayer/files/3310662/media_audio_flinger_log.txt)

**Comment by umangsaini** [comment]
There are no PIDs listed in "Clients:" section. It is odd that no application is using audio sink.
Please check if system sounds and audio is working correctly in other applications.

**Comment by marcbaechinger** [comment]
Can you take a full bug report just after the failure and upload it here? Like umangsaini is saying it might be a general problem with audio on that device.

**Comment by HiJohn** [comment]
like umangsaini  said ,  system sounds and audio is not working correctly 
i don`t know when this problem happened in this device, may be after upgrade os version from 8.0 to 9.0
[app_full_log.txt](https://github.com/google/ExoPlayer/files/3312764/app_full_log.txt)
thank you for reply
