### ISSUE TITLE
MediaPlayer Controller play/pause button postion

### ISSUE THREAD

**Issue by drayan85** [google/ExoPlayer#607]
How can change play/pause button position to the center of the video surface. I have setAnchorView to the FrameLayout as in demo and in the media_controller layout, i set the layout_height for root LinearLayout to match parent and the gravity to center. Suppose to both play/pause button and seek bar to be in the middle of the video surface but didn't.

**Comment by ojw28** [comment]
You should just implement your own player UI (i.e. do not use PlayerControl or MediaController).

**Comment by Schizo** [comment]
What do you mean by do not use Playercontrol or Mediacontrol, dont derive from them?

**Comment by drayan85** [comment]
<img width="932" alt="screen shot 2015-07-15 at 7 24 35 pm" src="https://cloud.githubusercontent.com/assets/4456232/8697388/3769cfa6-2b27-11e5-8323-1c972be468e5.png">

**Comment by drayan85** [comment]
I am using custom media controller layout.

**Comment by bsysop** [comment]
@Schizo, @ojw28 said to do not use ORIGINAL PlayerControl/MediaController... But you can use Brightec implementation, just adapt this for Exoplayer... I do that and works perfect.

In that change MediaController for PlayerControl (Exoplayer) and this will be great, also small changes in .create()/.show() you should do for be perfect.

**Comment by Schizo** [comment]
There is a missmatch in the datatype when setting setMediaPlayer(player.getPlayerControl)
 how did you solve this? It expect a MediaPlayerControl but Exoplayers method returns a PlayerControl Object. I tried changing the custom views function to take in PlayerControl.... but at the end the layout was not showing up when playing files.

**Comment by bsysop** [comment]
Please check my code and try that:
![captura de tela 2015-07-16 as 03 35 29](https://cloud.githubusercontent.com/assets/9998303/8716892/d25457e0-2b6b-11e5-9e51-7c44ffabc35a.png)
![captura de tela 2015-07-16 as 03 35 39](https://cloud.githubusercontent.com/assets/9998303/8716891/d2513bbe-2b6b-11e5-9856-59a49691ca92.png)

**Comment by Schizo** [comment]
Are you casting PlayerControl  in Playeractivity?: mediaController.setMediaPlayer((VideoControllerView.PlayerControl)player.getPlayerControl())

**Comment by bsysop** [comment]
You have to:
`private VideoControllerView mediaController;`

And then:
![captura de tela 2015-07-16 as 03 58 47](https://cloud.githubusercontent.com/assets/9998303/8717179/230def90-2b6f-11e5-9852-2c3066215068.png)

`SeekEnable`
Is my own variable of control, you don't need to use that.

Also the original VideoControllerView don't have `Create(0)`, you should use `show(0)`, i have customized that because my player are a little boring :), but that not a big deal for you.

**Comment by Schizo** [comment]
Why do you need Create(0) This wasn't implemented in the default MediaController as well? By the way, a side effect of this new controller is, that video updates while scrubbing due to the implemented function onProgressChanged()

**Comment by bsysop** [comment]
Well, i have customized VideoControllerView for do exactly what i need, then i make like this. Maybe you don't need.

Its ok for you now?

**Comment by drayan85** [comment]
yeah thanks i have got to manage to make it work. thanks.

**Comment by bsysop** [comment]
:)

**Comment by billyjoker** [comment]
Hi, i did all successfully but my mediacongtroller is showing always on top instead bottom though i put the params bottom.... Any idea why this behaviour ? Thx!!

**Comment by drayan85** [comment]
Could you please share your layout xml and media controller xml

**Comment by nguyenhoanglam** [comment]
I implemented @bsysop and http://www.brightec.co.uk/ideas/custom-android-media-controller guide but it returns default MediaController view instead of VideoControllerView. What's wrong here? Here is my code:
....
 mediaController = new VideoControllerView(context);
 mediaController.setAnchorView((ViewGroup) root);
...
