### ISSUE TITLE
Exoplayer Trackselection issue Trackselection Dialog show but all track are disable mode.Not able to swich other language audio.

### ISSUE THREAD

**Issue by Saranginfotech** [google/ExoPlayer#6070]
Exoplayer Trackselection issue Trackselection Dialog show but all track are disable mode.Not able to swich other language audio.
![Screenshot_2019-06-21-00-46-11-753_com videoplayer](https://user-images.githubusercontent.com/52050045/59875846-6db31400-93bf-11e9-9bfd-272b4287b83c.png)

**Comment by marcbaechinger** [comment]
Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md).

We need a sample uri and a bugreport so we can look into your issue and help.

**Comment by shailesh9898** [comment]
> Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md).
> 
> We need a sample uri and a bugreport so we can look into your issue and help.

i am play local video

**Comment by marcbaechinger** [comment]
We still need the media to investigate this. 
Can you please upload the media somewhere and provide a link to access it from there or download?

**Comment by shailesh9898** [comment]
> We still need the media to investigate this.
> Can you please upload the media somewhere and provide a link to access it from there or download?

ok i will upload

**Comment by shailesh9898** [comment]
https://drive.google.com/file/d/1sl05JKBPTHq6O9raF1pAkPu_N5Nlk503/view?usp=sharing

**Comment by marcbaechinger** [comment]
The audio tracks which can not select are in AC3 format which not supported by platform decoders. This is what the demo app gives you in the log when you play your media file:

```
Renderer:2 [
  Group:0, adaptive_supported=N/A [
    [ ] Track:0, id=2, mimeType=audio/ac3, channels=6, sample_rate=44100, language=tel, supported=NO_UNSUPPORTED_TYPE
  ]
  Group:1, adaptive_supported=N/A [
    [ ] Track:0, id=3, mimeType=audio/ac3, channels=6, sample_rate=44100, language=tam, supported=NO_UNSUPPORTED_TYPE
  ]
  Group:2, adaptive_supported=N/A [
    [ ] Track:0, id=4, mimeType=audio/ac3, channels=6, sample_rate=44100, language=hin, supported=NO_UNSUPPORTED_TYPE
  ]
  Group:3, adaptive_supported=N/A [
    [X] Track:0, id=5, mimeType=audio/mp4a-latm, channels=2, sample_rate=48000, language=eng, supported=YES
  ]
]
```

If you want ac3 support you need to include the [ffmpeg extension](https://github.com/google/ExoPlayer/tree/release-v2/extensions/ffmpeg) with your app.

**Comment by shailesh9898** [comment]
can  you please explain how  to use ffmpeg extension

**Comment by shailesh9898** [comment]
i am not understand you given link   ffmpeg extension

**Comment by marcbaechinger** [comment]
Sorry, I can't give you much more support upfront than what's on the [README of the extension](https://github.com/google/ExoPlayer/tree/release-v2/extensions/ffmpeg). Try to work through the README, I think it shouldn't be too difficult.
