### ISSUE TITLE
Dolby Atmos can't be played on DD+ only device (Since v2.10.0)

### ISSUE THREAD

**Issue by ybai001** [google/ExoPlayer#6073]
### [REQUIRED] Issue description
Play a Dolby Atmos content (DD+JOC) on a DD+ only device (e.g. LG G6, this device supports audio/eac3 but doesn't support audio/eac3-joc). There is no sound output. The ExoPlayer version should be v2.10.0 to v2.10.2. ExoPlayer v2.9.x has no problem. 

**I have found the root cause and the proposed bug fix is provided. Please check below info.**

### [REQUIRED] Reproduction steps
1. Play a Dolby Atmos content (DD+JOC) on a DD+ only device (e.g. LG G6, this device supports audio/eac3 but doesn't support audio/eac3-joc).
2. No sound output.

### [REQUIRED] Link to test content
Any DD+JOC content is OK. If you don't have this kind of content, please let me know and I'll email to you. Due to the copyright limitation, I can't upload it public.

### [REQUIRED] A full bug report captured from the device
Originally, this bug was fixed by Google in ExoPlayer v2.8.0 (https://github.com/google/ExoPlayer/issues/4165.) If you use an ExoPlayer version later than that, this issue should NOT occur.
But I find this issue is introduced by Google AGAIN. This issue can be reproduced since ExoPlayer dev-v2-r2.10.0. If you use the version before that (e.g. dev-v2-r2.9.6, the latest version of 2.9.x), everything is OK.

Bug fix proposal:
**File**: library/core/src/main/java/com/google/android/exoplayer2/mediacodec/MediaCodecUtil.java
**Method**: public static synchronized List<MediaCodecInfo> getDecoderInfos()
**Solution**: Change line 179 as below (change the third parameter from mimeType to MimeTypes.AUDIO_E_AC3)
```
if (MimeTypes.AUDIO_E_AC3_JOC.equals(mimeType)) {
      // E-AC3 decoders can decode JOC streams, but in 2-D rather than 3-D.
      CodecKey eac3Key = new CodecKey(MimeTypes.AUDIO_E_AC3, key.secure, key.tunneling);
      ArrayList<MediaCodecInfo> eac3DecoderInfos =
          getDecoderInfosInternal(eac3Key, mediaCodecList, MimeTypes.AUDIO_E_AC3);
      decoderInfos.addAll(eac3DecoderInfos);
    }
```

Issue analysis:
In v2.9.6,
```
    if (MimeTypes.AUDIO_E_AC3_JOC.equals(mimeType)) {
      // E-AC3 decoders can decode JOC streams, but in 2-D rather than 3-D.
      CodecKey eac3Key = new CodecKey(MimeTypes.AUDIO_E_AC3, key.secure);
      ArrayList<MediaCodecInfo> eac3DecoderInfos =
          getDecoderInfosInternal(eac3Key, mediaCodecList, mimeType);    // eac3Key.mimeType is AUDIO_E_AC3, mimeType is AUDIO_E_AC3_JOC.
      decoderInfos.addAll(eac3DecoderInfos);
    }
```

Check getDecoderInfosInternal() method,

```
private static ArrayList<MediaCodecInfo> getDecoderInfosInternal(CodecKey key,
      MediaCodecListCompat mediaCodecList, String requestedMimeType) throws DecoderQueryException {
…
      String mimeType = key.mimeType;
……
          for (String supportedType : codecInfo.getSupportedTypes()) {
            if (supportedType.equalsIgnoreCase(mimeType)) {              // !!! The key point here is mimeType is used, which is equal to AUDIO_E_AC3.
……
                 decoderInfos.add(MediaCodecInfo.newInstance(codecName, mimeType, capabilities,
                      forceDisableAdaptive, false));                                            // EAC3 decoder is added.
……
      return decoderInfos;
```

In v2.10.x

The code to handle DD+JOC play on DD+ only device is as below:
```
    if (MimeTypes.AUDIO_E_AC3_JOC.equals(mimeType)) {
      // E-AC3 decoders can decode JOC streams, but in 2-D rather than 3-D.
      CodecKey eac3Key = new CodecKey(MimeTypes.AUDIO_E_AC3, key.secure, key.tunneling);
      ArrayList<MediaCodecInfo> eac3DecoderInfos =
          getDecoderInfosInternal(eac3Key, mediaCodecList, mimeType);     // eac3Key.mimeType is AUDIO_E_AC3, mimeType is AUDIO_E_AC3_JOC. It is same as v2.9.6
      decoderInfos.addAll(eac3DecoderInfos);
   }
```

Check getDecoderInfosInternal() method,

```
private static ArrayList<MediaCodecInfo> getDecoderInfosInternal(CodecKey key,
      MediaCodecListCompat mediaCodecList, String requestedMimeType) throws DecoderQueryException {           // input requestedMimeType is AUDIO_E_AC3_JOC
…
String mimeType = key.mimeType;
…
        String supportedType =
            getCodecSupportedType(codecInfo, name, secureDecodersExplicit, requestedMimeType);               // !!! Here E_AC3_JOC is used, so supportedType is null ! The result is eac3decoder can’t be added to decoderInfos list.
        if (supportedType == null) {
          continue;
        }
```

### [REQUIRED] Version of ExoPlayer being used
v2.10.0 to v2.10.2

### [REQUIRED] Device(s) and version(s) of Android being used
A DD+ support but not DD+JOC support device, e.g. LG G6.

**Comment by andrewlewis** [comment]
@ybai001 Thanks for reporting. Just had a quick look and I think this might be fixed already on the dev-v2 branch. See [MediaCodecAudioRenderer](https://github.com/google/ExoPlayer/blob/dev-v2/library/core/src/main/java/com/google/android/exoplayer2/audio/MediaCodecAudioRenderer.java#L360). If you have a minute to check that would be useful.

**Comment by andrewlewis** [comment]
There are a few commits for improving codec selection (e.g., 2347bd2c9901cb679979dd4b292c6b1ef18cd65c) that are still only on the development branch, and the commit that (I think!) fixed this bug is among them.

@ojw28 Shall I do a one-liner fix on dev-v2-2.10.2 (on GH only) as proposed above, if we don't want to bring in the codec selection changes in a point release?

**Comment by ybai001** [comment]
> @ybai001 Thanks for reporting. Just had a quick look and I think this might be fixed already on the dev-v2 branch. See [MediaCodecAudioRenderer](https://github.com/google/ExoPlayer/blob/dev-v2/library/core/src/main/java/com/google/android/exoplayer2/audio/MediaCodecAudioRenderer.java#L360). If you have a minute to check that would be useful.

Sure, I'll check it and feedback to you ASAP.

**Comment by ybai001** [comment]
@andrewlewis I tested the latest dev-v2 branch on LG G6 phone. Same as your thought, this issue is fixed. I think you can close this ticket. Thank you very much for your quick and clear response. Have a good weekdend.

**Comment by andrewlewis** [comment]
The commit referenced should match your suggestion and will go into 2.10.2. The existing fix on the development branch should make it into a later release that includes the more significant changes to decoder selection. Thanks!
