### ISSUE TITLE
Exoplayer local video allowAdaptiveSelections audio show dialog but not able to switch audio to other track show in dialog.

### ISSUE THREAD

**Issue by shailesh9898** [google/ExoPlayer#6074]
Exoplayer allowAdaptiveSelections audio show dialog but not able to switch audio to other track show in dialog.

   if (mappedTrackInfo != null) {
                    //CharSequence title = ((Button) view).getText();
                    int rendererIndex = 1;
                    int rendererType = mappedTrackInfo.getRendererType(rendererIndex);
                    boolean allowAdaptiveSelections =
                            rendererType == C.TRACK_TYPE_VIDEO
                                    || (rendererType == C.TRACK_TYPE_AUDIO
                                    && mappedTrackInfo.getTypeSupport(C.TRACK_TYPE_VIDEO)
                                    == MappingTrackSelector.MappedTrackInfo.RENDERER_SUPPORT_NO_TRACKS);
                    Pair<AlertDialog, TrackSelectionView> dialogPair =
                            TrackSelectionView.getDialog(activity, "dsdsdsdsd", trackSelector, rendererIndex);
                    dialogPair.second.setShowDisableOption(true);
                    dialogPair.second.setAllowAdaptiveSelections(allowAdaptiveSelections);

                    dialogPair.first.show();

                }

![59875846-6db31400-93bf-11e9-9bfd-272b4287b83c](https://user-images.githubusercontent.com/39123310/59908666-8822d700-942b-11e9-8a8e-d3ccd41d6a26.png)

**Comment by marcbaechinger** [comment]
Let's stick with #6070.
