### ISSUE TITLE
Cache-Control: no-cache

### ISSUE THREAD

**Issue by tanpuer** [google/ExoPlayer#6076]
I request some videos with http response: "Cache-Control: no-cache". I hope exoplayer will not cache this video using CacheDataSource, but it didn't. So should I custom another DataSource or modify some code?

**Comment by tanpuer** [comment]
![image](https://user-images.githubusercontent.com/16443498/59918086-465b5600-9456-11e9-986b-460e58ed36eb.png)
Can i add a judgement before dataSink.write(buffer, offset, bytesRead) ?

**Comment by marcbaechinger** [comment]
Yes, do not wrap your data source with `CacheDataSource` for those streams you don't want to cache.

**Comment by tanpuer** [comment]
@marcbaechinger I must always use CacheDataSource and later determine whether to cache according to Cache-Control in response header.

**Comment by kgrevehagen** [comment]
@marcbaechinger Is this a duplicate of 4188? If yes, do you have any status or ETA on when this will be implemented?

**Comment by marcbaechinger** [comment]
Closing this due to duplicate #4188
