### ISSUE TITLE
The Exoplayer can not play the m3u8

### ISSUE THREAD

**Issue by lsgfly** [google/ExoPlayer#6077]

**Comment by lsgfly** [comment]
I use the Exoplayer to play the url　　　http://hbsh.chinashadt.com:2036/live/8.stream/chunklist_w693062733.m3u8 .
It can not be played successful, but no error occured. 
But when I get the ts from m3u8 file, It can be played successful.

**Comment by lsgfly** [comment]
[REQUIRED] Issue description

I use the Exoplayer to play the url　　　http://hbsh.chinashadt.com:2036/live/8.stream/chunklist_w693062733.m3u8 .
It can not be played successful, but no error occured.
But when I get the ts from m3u8 file, It can be played successful.

[REQUIRED] Reproduction steps
play the url http://hbsh.chinashadt.com:2036/live/8.stream/chunklist_w693062733.m3u8 .

[REQUIRED] A full bug report captured from the device


[REQUIRED] Version of ExoPlayer being used
2.8.2

[REQUIRED] Device(s) and version(s) of Android being used
android 9.0 vivo X27

**Comment by umangsaini** [comment]
For Android 9.0 and above, you would have to add following line in <application> tag to your AndroidManifest.xml.
> android:usesCleartextTraffic="true"

There is a warning shown when app is run on newer Android OS.
> "Cleartext traffic not permitted"

Refer to this documentation [link](https://developer.android.com/guide/topics/manifest/application-element#usesCleartextTraffic). HTTPS links will not face this issue.
