### ISSUE TITLE
How to set audio pass-through(AC3/DTS/Dolby) ?

### ISSUE THREAD

**Issue by JiannaiJ** [google/ExoPlayer#6080]
### [REQUIRED] Searched documentation and issues
[https://github.com/google/ExoPlayer/issues/2148](url)

### [REQUIRED] Question
I've included the ffmpeg extension and enabled all support decoder, tv-box connect power amplifiers with HDMI.  I need to configure use pass-through or not, pass-through is preferred. I search some issues and test,but it is still impossible to achieve this function. It's better to have an example. Thank you very much！

**Comment by andrewlewis** [comment]
Please see this [comment on issue 2832](https://github.com/google/ExoPlayer/issues/2832#issuecomment-301833679). Feel free to reply here if that doesn't address what you're trying to do and I'll reopen the issue.
