### ISSUE TITLE
Poor video quality after scaling up a small video with Skia renderer?

### ISSUE THREAD

**Issue by raymondctc** [google/ExoPlayer#6084]
It is found that video has poor quality on Skia renderer after scaling up on Android Pie, in which the default renderer is Skia.

The result is quite obvious, with OpenGL, video looks smoother

### Link to test content
Original video: https://img-9gag-fun.9cache.com/photo/aerBX7j_460svvp9.webm

With OpenGL:
---
![Screenshot_20190620-181601_9GAG](https://user-images.githubusercontent.com/13764117/59985823-45990e80-9666-11e9-8ef4-cfc82c909415.jpg)
![Screenshot_20190620-181606_9GAG](https://user-images.githubusercontent.com/13764117/59985824-45990e80-9666-11e9-84be-2624947c9a62.jpg)

With Skia:
---
![Screenshot_20190620-181514_9GAG](https://user-images.githubusercontent.com/13764117/59985813-3ca83d00-9666-11e9-8efd-aad20626ec01.jpg)
![Screenshot_20190620-181518_9GAG](https://user-images.githubusercontent.com/13764117/59985815-3ca83d00-9666-11e9-8358-0eadcee9b947.jpg)

**Comment by andrewlewis** [comment]
What device(s) do you see this behavior on? Is the app pictured using `TextureView`?

It sounds like the same issue as [issuetracker.google.com/124593215](https://issuetracker.google.com/124593215). If so, I think the best way forward is for you to provide information on that bug as there isn't a good way for us to fix this in ExoPlayer. Thanks.

**Comment by raymondctc** [comment]
Yes, `TextureView` is used.

Screenshot was taken from Samsung Galaxy Tab A, it's been tried on Xiaomi Mi 9 (Pie) and Nokia 7 Plus (Pie), similar result is obtained.

**Comment by andrewlewis** [comment]
I wonder whether `SurfaceView` is an option for your use case and wouldn't be affected by the same issue.

**Comment by raymondctc** [comment]
Oh, switching to `SurfaceView` can resolve the pixelated issue. Why it would be the case?

**Comment by andrewlewis** [comment]
I think it's just a bug that affects `TextureView` on certain devices, but can be fixed via system update (I'm not sure what devices will receive updates or when, though).

See choosing a [surface type](https://exoplayer.dev/ui-components.html#choosing-a-surface-type) for background information on `SurfaceView` vs `TextureView`. Unless you need to call `TextureView.getBitmap`, `SurfaceView` can be used from API 24 onwards.
