### ISSUE TITLE
does exoplayer rerequest the url when we set currentseekpos

### ISSUE THREAD

**Issue by geeta4** [google/ExoPlayer#6091]
i prepepare mediasource and wile playing i change position of media and call setcurrentpos of sinpleexoplayer so it rerequest the url why it is happening if i already prepared mediasource and i knew it because we tracking the hits of url. the code i write it is as below:

```
if (simpleExoPlayer != null) {
            return;
        }

        Context context = AppController.getInstance();
        DefaultRenderersFactory renderersFactory = new DefaultRenderersFactory(
                context,
                null,
                DefaultRenderersFactory.EXTENSION_RENDERER_MODE_OFF
        );
        TrackSelector trackSelector = new DefaultTrackSelector();

        simpleExoPlayer = ExoPlayerFactory.newSimpleInstance(AppController.getInstance(), renderersFactory, trackSelector);

        userAgent = Util.getUserAgent(context, context.getString(R.string.app_name));
        setPlaybackParam();
        simpleExoPlayer.addListener(new ComponentListener());
        AudioAttributes audioAttributes = new AudioAttributes.Builder()
                .setUsage(com.google.android.exoplayer2.C.USAGE_MEDIA)
                .setContentType(C.CONTENT_TYPE_SPEECH)
                .build();
        simpleExoPlayer.setAudioAttributes(audioAttributes, true);
        simpleExoPlayer.seekTo(currentSeekPos);

simpleExoPlayer.prepare(getHttpMediaSource(mediaMetaData));
simpleExoPlayer.setPlayWhenReady(true);

    private MediaSource getHttpMediaSource(MediaMetaData mediaMetaData) {
        return new ExtractorMediaSource(
                Uri.parse(mediaMetaData.getMediaUrl()),
                new DefaultHttpDataSourceFactory(
                        userAgent,
                        null /* listener */,
                        DefaultHttpDataSource.DEFAULT_CONNECT_TIMEOUT_MILLIS,
                        DefaultHttpDataSource.DEFAULT_READ_TIMEOUT_MILLIS,
                        true /* allowCrossProtocolRedirects */),
                new DefaultExtractorsFactory(),
                null,
                null
        );
    }
```
and when i change position i call
```
simpleExoPlayer.seekTo(calPos);
```
when i call ablove line it rehit the url 
ehit the
how can i resolve so it to stop rehit the url

**Comment by marcbaechinger** [comment]
If you seek to another position while playback and the player does not have the data available to play that position, then the player needs to download the data from the server. 

If you want to download all the data beforehand you need to use a `CacheDataSource` and [download everything and then play the file offline](https://exoplayer.dev/downloading-media.html).

**Comment by geeta4** [comment]
if data is playing continously from url then it does not rehit that url in my tracking if while playing i set at specific position then it rehit that url again in my tracking. so please tell me the solution

**Comment by geeta4** [comment]
i dont want to download all the data beforehand if it is not happenening while continously playing why happening setting different seekpos what is the logic actually? while continoiuslly playing it also  dont download all the data beforehand.

**Comment by marcbaechinger** [comment]
What kind of media stream are you playing?
