### ISSUE TITLE
Is there a way to preload new mediasource without ConcatenatingMediaSource?

### ISSUE THREAD

**Issue by mansurrrr** [google/ExoPlayer#6092]
### [REQUIRED] Searched documentation and issues
I'm already using `ConcatenatingMediaSource`

### [REQUIRED] Question
I want to preload new MediaSource without `ConcatenatingMediaSource`,
there is no callback for completion of current `MediaSource`.
`onPositionDiscontinuity` only works when next `MediaSource` starts.

1. Can I get a callback when the current video ends?
2. If not, Is there a way to preload new MediaSource without ConcatenatingMediaSource?

**Comment by jakoss** [comment]
As of 1 point - you can listen to `onPlayerStateChanged(boolean playWhenReady, int playbackState)` if `playbackState == STATE_ENDED`.

As of 2 - i think you could just create second player and start buffering in it, but i never tried this.

**Comment by tonihei** [comment]
Can you explain what you are trying to achieve exactly? What is it that prevents you from using ConcatenatingMediaSource? That might help to better understand what this is about and what alternatives ways there could be.

In case your goal is to pause the current video at the end without automatically continuing to the next video, this is a duplicate of #5660.
