### ISSUE TITLE
MediaSession extension play() not resuming a player in READY state

### ISSUE THREAD

**Issue by loki666** [google/ExoPlayer#6093]
### [REQUIRED] Issue description
Using the mediasession extension, the play doesnt works if the player is in READY state.

### [REQUIRED] Reproduction steps
Prepare the player, and call TransportControls.play()
nothing is happening because the MediaSessionCompat.Callback.play() does nothing when the player is in READY state.
Same goes if you pause() a playing player. Pausing the player works, but it's impossible to resume it.

### [REQUIRED] Link to test content
any content will do

### [REQUIRED] A full bug report captured from the device
no crash

### [REQUIRED] Version of ExoPlayer being used
2.10.2

### [REQUIRED] Device(s) and version(s) of Android being used
any device / emulator

**Comment by tonihei** [comment]
@marcbaechinger Can you take a look?

**Comment by marcbaechinger** [comment]
Yep, that's wrong.  I'll provide a fix asap.

**Comment by georgi-neykov-hub** [comment]
@marcbaechinger , is it possible to just match the logic in [PlayerControlView#1232](https://github.com/google/ExoPlayer/blob/release-v2/library/ui/src/main/java/com/google/android/exoplayer2/ui/PlayerControlView.java#L1232)? Or maybe, just call `controlDispatcher.dispatchSetPlayWhenReady(player, true)` if the current player's state is `Player.STATE_READY`?
