### ISSUE TITLE
Is it possible to play MPEG-TS from sequential memory buffers rather than a complete file?

### ISSUE THREAD

**Issue by pearleye** [google/ExoPlayer#6095]
### [REQUIRED] Searched documentation and issues
https://exoplayer.dev/

### [REQUIRED] Question
Does expo player support playing a MPEG-TS from sequential memory buffers rather than a existing complete MPEG-TS file ?

### A full bug report captured from the device
NA

### Link to test content
NA

**Comment by ojw28** [comment]
ExoPlayer supports streamed MPEG-TS (e.g. over a network), so there's no requirement to have a complete file in advance. If you're trying to stream data from a non-standard source (e.g. some memory buffers), then the right way to do that is to implement a custom `DataSource` that'll provide the data to the player.

**Comment by pearleye** [comment]
Yes we will be receiving streamed data from a non-standard source (memory buffers), so do you know if there is an example available or anything very close to my requirement ?

**Comment by ojw28** [comment]
I'm not aware of an example; it sounds like a niche case that's specific to your application. You'll need to look into implementing a custom `DataSource` for this.

**Comment by pearleye** [comment]
@ojw28 Thanks, but could you share some reference where a custom DataSource has been implemented ?

**Comment by ojw28** [comment]
It's a pretty simple API to implement. I'd suggest looking at the Javadoc of `DataSource`. You can also inspect the source code of all the implementations already in the library (e.g. `FileDataSource` might be a good one to look at). We don't have any documentation beyond that.

**Comment by soorajdevs** [comment]
Does the ExoPlayer support reading from camera device?
I wonder if we can use the player to directly read from the device which is generating the AV stream.

**Comment by ojw28** [comment]
> Does the ExoPlayer support reading from camera device?

No.

**Comment by soorajdevs** [comment]
> > Does the ExoPlayer support reading from camera device?
> 
> No.

Ok Thanks
