### ISSUE TITLE
Нет звука

### ISSUE THREAD

**Issue by jonkryl** [google/ExoPlayer#6102]
Нет звука. Использую демо приложение для проверки. Не работает только на некоторых устройствах.
![Screenshot_20190627-185949_ExoPlayer](https://user-images.githubusercontent.com/13360676/60266043-68028480-9911-11e9-95f5-01c2039a6e9a.jpg)
![IMG_20190627_192821_914](https://user-images.githubusercontent.com/13360676/60266170-b152d400-9911-11e9-934c-b8bf455929d9.jpg)
![IMG_20190627_192814_892](https://user-images.githubusercontent.com/13360676/60266171-b1eb6a80-9911-11e9-82bc-4b936c1a0400.jpg)

**Comment by jonkryl** [comment]
`{
    "name": "Misc",
    "samples": [
      {
        "name": "Nashe Radio",
        "uri": "http://nashe1.hostingradio.ru/nashe-128.mp3"
      },
      {
        "name": "Nashe Radio2",
        "uri": "http://nashe1.hostingradio.ru/nashe20-128.mp3"
      },
      {
        "name": "Nashe Radio3",
        "uri": "http://nashe1.hostingradio.ru/nasheekt128.mp3"
      },
      {
        "name": "Nashe Radio4",
        "uri": "http://nasheekt.hostingradio.ru/nashespb128.mp3"
      },
      {
        "name": "Nashe Radio5",
        "uri": "http://nashe1.hostingradio.ru/nasheclassic.mp3"
      },
      {
        "name": "Nashe Radio6",
        "uri": "http://nashe1.hostingradio.ru/nashepunks.mp3"
      },
      {
        "name": "Nashe Radio7",
        "uri": "http://nashe1.hostingradio.ru/nashesongs.mp3"
      }
    ]
  }`

**Comment by catbaxter** [comment]
Тебе надо добавить в манифест приложения (AndroidManifest.xml) строку, которая разрешает трафик через http:

```
<?xml version="1.0" encoding="utf-8"?>
<manifest ...>
    <uses-permission android:name="android.permission.INTERNET" />
    <application
        ...
        android:usesCleartextTraffic="true"
        ...>
        ...
    </application>
</manifest>
```

**Comment by jonkryl** [comment]
> Нужно добавить в манифест приложения (AndroidManifest.xml), который разрешает трафик через http:
> 
> ```
> <?xml version="1.0" encoding="utf-8"?>
> <manifest ...>
>     <uses-permission android:name="android.permission.INTERNET" />
>     <application
>         ...
>         android:usesCleartextTraffic="true"
>         ...>
>         ...
>     </application>
> </manifest>
> ```

Спасибо, это помогло. Но почему большая часть устройств работала без этого разрешения?

**Comment by catbaxter** [comment]
Это требование Android 9, что вся коммунникация идет через https, если http - то надо прописывать исключения ручками или ставить для всех разрешение в манифесте.

**Comment by tonihei** [comment]
The question seems to be answered now. It's also a duplicate of #6077.
