### ISSUE TITLE
HLS support for OPUS

### ISSUE THREAD

**Issue by nlgtuankiet** [google/ExoPlayer#6104]
### [REQUIRED] Use case description
Music streaming platform which supports adaptive bitrate streaming for poor network condition. While Opus performs exceptionally well at low bitrates, Opus inside HLS is not really a standardized payload

### Proposed solution
I don't have any

### Alternatives considered
.m4a format works well for us at > 128k, but at 64k (which is our target) it performs poorly when compared to opus. I believe there was a time when SoundCloud replace their legacy 128k mp3 which 64k opus (for streaming) which prove that this is 100% possible

**Comment by ojw28** [comment]
We don't have any plans (or see any particular demand) for this. This will likely remain true for as long as it's not part of the HLS specification. We support Opus carried in DASH adaptive streams, which may be a satisfactory alternative for you.
