### ISSUE TITLE
Parent View click events are consumed by PlayerView [2.10.2]

### ISSUE THREAD

**Issue by greyski** [google/ExoPlayer#6109]
### [REQUIRED] Searched documentation and issues
There was no mention of why click handling is being overridden by the `PlayerView` via `onTouchEvent`

### [REQUIRED] Question
We recently upgraded from exoplayer **2.8** to **2.10.2** and noticed not all of our Views hosting an exoplayer were clickable. Looking at the source shows that in **2.10.2** PlayerView consumes all touch events upon it's surface:
```
  @Override
  public boolean onTouchEvent(MotionEvent event) {
    switch (event.getAction()) {
      case MotionEvent.ACTION_DOWN:
        isTouching = true;
        return true;
      case MotionEvent.ACTION_UP:
        if (isTouching) {
          isTouching = false;
          performClick();
          return true;
        }
        return false;
      default:
        return false;
    }
  }
```
Whereas in **2.8** it would still allow touch/click events to be propagated to it's parent container unless the controller was present:
```
  @Override
  public boolean onTouchEvent(MotionEvent ev) {
    if (!useController || player == null || ev.getActionMasked() != MotionEvent.ACTION_DOWN) {
      return false;
    }
    if (!controller.isVisible()) {
      maybeShowController(true);
    } else if (controllerHideOnTouch) {
      controller.hide();
    }
    return true;
  }
```
Is this intended behavior? It seems like a bug since it prevents any parent view from performing a click event if the tapped surface is within a PlayerView's bounds.
### A full bug report captured from the device
n/a

### Link to test content
n/a

**Comment by marcbaechinger** [comment]
I don't see a reason why these touch events should be consumed in case we no-op.

Marking as bug for now.

**Comment by marcbaechinger** [comment]
Looking at the change which introduced this, makes me think that we changed to the standard Android behaviour. The touch event is delegated to performClick which triggers OnClickListeners of the given view.

Can you check whether we also consume the click to which `performClick()` delegate the touch event?

**Comment by tonihei** [comment]
We shouldn't consume the event if no controller is present. That part of the change was unintentional. Marking as bug again to fix that.
