### ISSUE TITLE
Exoplayer Decoding H264 Parameters

### ISSUE THREAD

**Issue by Schizo** [google/ExoPlayer#611]
How is Android Handling the Decoding Process of H264 Streams? Basically i would like to pass in arguments for the Decoding process like setting B-Frames to 0. Is this possible ?

**Comment by andrewlewis** [comment]
Could you elaborate on what you mean by 'setting B-Frames to 0'?

**Comment by Schizo** [comment]
When doing zerolatency streaming, you ignore Bidirectional-Frame prediction when encoding. At the decoders side you can disable it by setting the parameter --bframes 0.

https://x265.readthedocs.org/en/default/presets.html at the bottom of this page unde zerolatency you can see the parameter i am talking about.
(This is x265 but should be similar to x264)

**Comment by andrewlewis** [comment]
Playing back a stream that doesn't have B-frames should work fine without any extra configuration -- the slice type information is present in the encoded bitstream.

As I understand it, the documentation is suggesting that you pass --bframes 0 to the encoder. The result will be that the decoder does not need to do frame reordering when it decodes the stream, which can reduce latency.

**Comment by Schizo** [comment]
Oh so this is not a Option in the Decoder? I thought this is an option at the Decoders side to skip checking for B-Frames.

**Comment by andrewlewis** [comment]
Correct. I think it only really makes sense as an encoder option.
