### ISSUE TITLE
How to loop a video instead of playing the next video when the video ends ?

### ISSUE THREAD

**Issue by CreeschYT** [google/ExoPlayer#6110]
###  Searched documentation and issues
I searched on StackOverflow, but found nothing

###  Question
I'm developing an m3u player which asks the user to choose an m3u file. The m3u urls are put in a ConcatenatingMediaSource the urls work fine. When the user presses 'Next' the next url should play which works. There are two timers one on the left and on the right. The one on the left counts. The one on the right stays at zero (because of m3u livestreaming). Sometimes the timer on the right displays a random time between 0:00 and 1:00 after some time. When the timer is at lets say 0:53 after 53 seconds the next video plays, despite of being a LIVE stream. It's a common issue in m3u players and I thought about looping the video when the video ends, but unfortunately my code didn't work, it just played the next video when the video ends:

 ```
exoPlayer.addListener(new ExoPlayer.DefaultEventListener() {
              
  
@Override
                public void onPlayerStateChanged(boolean playWhenReady, int playbackState) {

         
                   if (playbackState == exoPlayer.STATE_ENDED){
                       exoPlayer.setRepeatMode(Player.REPEAT_MODE_ALL);
                 }

```

### A full bug report captured from the device
there is neither an error nor a bug report. When the video ends it just plays the next one. 

### Link to test content
[File I used.zip](https://github.com/google/ExoPlayer/files/3341726/File.I.used.zip)

**Comment by ojw28** [comment]
I don't really understand the issue. I think you're saying that you're seeing a live stream spuriously ending, which is presumably something that shouldn't happen. Isn't that the issue that should be fixed here?

As a workaround, you could try setting `player.setRepeatMode(Player. REPEAT_MODE_ONE)`. You should do this when you initially configure the player, not conditionally on seeing `STATE_ENDED`. Does that help?

**Comment by CreeschYT** [comment]
Thank you for the reply,
Um, yeah so sometimes the streams are ending. I added a screenshot of what happens. I'm now going to try `player.setRepeatMode(Player. REPEAT_MODE_ONE)` in the `onPlayerStateChanged` Event
![Screenshot_20190630-181939](https://user-images.githubusercontent.com/49997316/60399428-5a910880-9b64-11e9-8910-dbd3bd2d4d06.png)

**Comment by CreeschYT** [comment]
Ok, player.setRepeatMode(Player. REPEAT_MODE_ONE) worked.
