### ISSUE TITLE
Cannot open m3u8 stream

### ISSUE THREAD

**Issue by kaiv2000** [google/ExoPlayer#6112]
Exoplayer v 2.10.2 cannot open m3u8 stream, error not showing in debugger and player continuosly trying to play this stream (Embedded Android video player open this stream correctly):
Example stream with this issue:
http://vps.guru.ua/hls/ratusha.m3u8

**Comment by ojw28** [comment]
Similar to https://github.com/google/ExoPlayer/issues/3158, this stream declares an audio track that it does not actually contain. The media should be fixed to not declare this track.

If you know that the streams you're playing do not contain audio, then you can work around this problem by creating the `HlsMediaSource` using `FLAG_IGNORE_AAC_STREAM`, like:

```
return new HlsMediaSource.Factory(dataSourceFactory).setExtractorFactory(
    new DefaultHlsExtractorFactory(
        DefaultTsPayloadReaderFactory.FLAG_IGNORE_AAC_STREAM, false))
    .createMediaSource(uri);
```
