### ISSUE TITLE
How to Exoplayer play video with sdcard path to Array?

### ISSUE THREAD

**Issue by peapea27566** [google/ExoPlayer#6114]
How to Exoplayer play video with sdcard path to Array?

  var path = (Environment.getExternalStorageDirectory().path + "/ads/")
        var directory = File(path)
        var url = directory.listFiles()

how to play video Exoplayer to url path help me !!

**Comment by tonihei** [comment]
Using `DefaultDataSource`, as described in our [Hello World example](https://exoplayer.dev/hello-world.html#preparing-the-player), already handles file URIs automatically.

**Comment by peapea27566** [comment]
you Have enough  a sample code for me

**Comment by tonihei** [comment]
I already linked an example above.
