### ISSUE TITLE
"Unknown" audio track when using chunkless preparation

### ISSUE THREAD

**Issue by alexeyr15** [google/ExoPlayer#6116]
### [REQUIRED] Issue description
ExoPlayer demo app displays "Unknown" audio track when using chunkless preparation.

### [REQUIRED] Reproduction steps
1. Open the provided test stream in ExoPlayer demo app
2. Select tracks -> Audio -> Audio track is displayed with correct language and type ("stereo")
3. Add `setAllowChunklessPreparation(true)` to `buildMediaSource` method for `HlsMediaSource`
4. Open the stream
5. Select tracks -> Audio -> Audio track is displayed as "Unknown"

### [REQUIRED] Link to test content
Provided by email.

### [REQUIRED] A full bug report captured from the device
N/A

### [REQUIRED] Version of ExoPlayer being used
2.10.2

### [REQUIRED] Device(s) and version(s) of Android being used
Google Pixel 2 XL, Android 9

**Comment by ojw28** [comment]
@AquilesCanta - Please take a look at this. Thanks!

**Comment by AquilesCanta** [comment]
Hi, sorry for the delay on this. Could you check the stream? It's timing out for me.

**Comment by alexeyr15** [comment]
I can't reproduce this issue at the moment. I will recreate the issue if I will be able to reproduce it again.
