### ISSUE TITLE
Audio focus is permanently lost

### ISSUE THREAD

**Issue by Tumbler0809** [google/ExoPlayer#6118]
### [REQUIRED] Use case description
I need a player that plays the video silently, it never holds the audio focus, just plays the video without sound.

**Comment by tonihei** [comment]
The audio focus is not requested unless you explicitly use `SimpleExoPlayer.setAudioAttributed` to set the audio attributes. Could that be the problem? If not, please describe the question in more details following the issue template.

**Comment by Tumbler0809** [comment]
The SimpleExoPlayer.setAudioAttributed method is not called

AudioManager.isMusicActive() returns true when playing a mute video，I want it to return false，Because I don't use audio resources. I just want to play a video screen.

**Comment by tonihei** [comment]
This means that either something else in the system is playing audio, or the video actually contains  audio data and ExoPlayer is playing it.

If your video contains audio data and you just set the volume to zero, it would be better to turn off audio completely. There are two ways to do this:
1. [preferred] Remove the audio renderers by overriding `DefaultRenderersFactory.buildAudioRenderers` with an empty method.
2. Or disable audio tracks with `DefaultTrackSelector.ParametersBuilder.setRendererDisabled` using the audio renderer index.

**Comment by Tumbler0809** [comment]
yes,the video actually contains audio data and ExoPlayer is playing it,I will try the method you provided, thank you
