### ISSUE TITLE
Audio not stopped when the Video stops

### ISSUE THREAD

**Issue by QuaQuaAndroid** [google/ExoPlayer#6120]
I'm facing an issue in 360 video player, when I exit the Video, audio keeps playing even when I exit the App(until it gets cleared from Backend).

Releasing the player in onPause & onStop methods in Activity & Creating again in onStart & onResume.

Can some one help me out to solve this issue.?

**Comment by tonihei** [comment]
Please provide all the requested information in the [issue template](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md) for us to take a look. Thanks you.
