### ISSUE TITLE
Decrypting data source question

### ISSUE THREAD

**Issue by maskedpatel** [google/ExoPlayer#6122]
### [REQUIRED] Searched documentation and issues
https://exoplayer.dev/downloading-media.html
Exoplayer github issues
stackoverflow 
FileDataSource, CacheDataSource, AesCipherDataSource, Aes128DataSource, SimpleCache, relevant other abstract/base classes/interfaces
Olly's medium posts
Erdem's approach in https://github.com/google/ExoPlayer/issues/5193 was one of our main resources. This is pretty much the approach we used besides using a slight tweak on AesCipherDataSource.
### [REQUIRED] Question
Hello, we are attempting to use exoplayer for decrypting and playing video messages. We are currently using SimpleCache for storing downloaded files (using DownloadManager and DownloadService) and CacheDataSource with our decrypting data source (which is identical to exoplayer's AesCipherDataSource, but we use our own custom IV instead of their generated one) to load the MediaSource. This is the chain of upstreams used: CacheDataSource (cacheReadUpstream) -> Our decrypting data source (upstream) -> FileDataSource.
This approach works with small files ( < 5 MB) since no fragmentation occurs in the cache. When the file is > 5 MB and fragmentation does occur, the following error occurs. Attached are images of our data source and the way we use exoplayer's components. It seems like we are missing something really obvious here... but we just aren't able to pick it up. Any help would be greatly appreciated, thanks!
![Screen Shot 2019-07-02 at 11 08 28 AM](https://user-images.githubusercontent.com/7097316/60536726-cd60c780-9cbb-11e9-9f93-c96d5ffb7517.png)
![Screen Shot 2019-07-02 at 11 08 39 AM](https://user-images.githubusercontent.com/7097316/60536745-da7db680-9cbb-11e9-8e03-7fc2bbe7d774.png)
![Screen Shot 2019-07-02 at 11 09 19 AM](https://user-images.githubusercontent.com/7097316/60536764-e36e8800-9cbb-11e9-8145-64205422c60d.png)
The VoxerCipher used in the above image is identical to exoplayer's AesFlushingCipher, except we use theIV we passed into the constructor input rather than generating it in the cipher based on the nonce. I'd be glad to add that if needed as well. 
### A full bug report captured from the device
Attached. I called the adb command right after the exception was thrown in logcat.
[bugreport-2019-07-02-11-10-00.zip](https://github.com/google/ExoPlayer/files/3351752/bugreport-2019-07-02-11-10-00.zip)

### Link to test content
It's encrypted and is a 17.2MB file, meaning fragmentation occurs in the SimpleCache: 
https://www.googleapis.com:443/storage/v1/b/voxer_media_prod/o/1562090449597_7991128201_c751b3d4.mp4?alt=media

This one is also encrypted, but its under 5 MB, so no fragmentation in cache. This one does play properly and we are able to decrypt it using exoplayer's factories/data sources:
https://www.googleapis.com:443/storage/v1/b/voxer_media_prod/o/1562090643943_761000658_c751b3d4.mp4?alt=media

**Comment by maskedpatel** [comment]
Also should add, the error occurs on the following breakpointed line of Exoplayer's CacheDataSource.java file:
![Screen Shot 2019-07-02 at 11 46 00 AM](https://user-images.githubusercontent.com/7097316/60538263-1c5c2c00-9cbf-11e9-9741-5af305ce9284.png)
We tried debugging it ourselves for a while. It seems like the readPosition of CacheDataSource isnt being set properly by us. For an unencrypted version of the problematic video file (using FileDataSource as the cacheReadUpstream), the readPosition goes from 0 -> 17.2 MB -> 32 Bytes -> 5 MB -> 10 MB -> 15 MB -> Finish and play (on open() recursive calls).
For the encrypted file with the decryption data source in between CacheDataSource and FileDataSource, the readPosition goes from 0 -> 17.2MB -> Way too big of a number (~ 2 GB) -> Crash at breakpoint above.

**Comment by tonihei** [comment]
It's slightly difficult to say what's happening without the option to step through the code. 

Did you implement exactly the same code as in #5193? Including the AesCipherDataSink with the default buffer parameter?

**Comment by maskedpatel** [comment]
Nope we didn't use data sinks yet. We wanted to implement just the data source portion initially since we are operating under multiple clients (web, ios, android) and their encryptors are already implemented. 
The weird thing is that the decryption process works for smaller than 5 MB files (without cache fragmentation) which leads me to believe this is data sink independent. Anything greater than 5 MB (with fragmentation) causes the exception shown above. 
Also not all clients have exoplayer, and I'm guessing the datasource decryption implementation still supports standard decryption as long as they use the same underlying implementation (AES).
Any thoughts? We can try with data sink and just keep it in-android for a quick test if you think that would shed some light.

**Comment by tonihei** [comment]
As far as I know, using the AesCipherDataSink is required to get that to work correctly. If you want to decrypt the file when reading, you also need to encrypt it in a consistent way when writing it to disk.

I'm slightly confused about the setup though, because you write that "encryptors are already implemented". Can you explain in more detail how you write the data to the cache?

**Comment by maskedpatel** [comment]
Sure. We use the same underlying algorithm that the AesCipherDataSink uses in its cipher (AES, CTR, No padding) and the same libraries for encrypting the files.
On our android client we receive the URI for the remote encrypted file, then we use our overridden implementations of exoplayer's DownloadManager/DownloadService to retrieve the remote file via URI and store it into an instance of exoplayer's SimpleCache(pretty much the same way shown in https://exoplayer.dev/downloading-media.html for progressive downloads, minus the download trackers. I.e. using the sendAddDownload method in the link). 
The SimpleCache instance fragments the encrypted files if they are > 5 MB (another potential solution for our problem would be finding a way to increase the fragmentation limit to the max video size limit we support... though obviously a less optimal solution), which is where our issue occurs when attempting to decrypt.

**Comment by tonihei** [comment]
I just tried to reproduce the problem somehow, but everything works fine for me.

1. I encrypted the upstream http data source on the client. This is to simulate your server-side encryption.
``` 
upstreamFactory = 
  new AesEncryptingDataSource(secretKey, new DefaultHttpDataSource(userAgent));
```
`AesEncryptingDataSource` is a copy of AesCipherDataSink returning the encrypted data during read, instead of writing it somewhere. See below for details.

2. I created a cache read-only data source that decrypts on cache file reads:
```
cacheReadOnlyFactory = 
  new CacheDataSourceFactory(
        cache,
        upstreamFactory,
        () -> new AesCipherDataSource(secretKey, new FileDataSource()),
        /* cacheWriteDataSinkFactory= */ null,
        CacheDataSource.FLAG_IGNORE_CACHE_ON_ERROR,
        /* eventListener= */ null);
```
This data source factory is used for playback.

3. I created the `DownloadConstructorHelper` for the `DownloadManager` like that:
```
downloaderConstructorHelper =
          new DownloaderConstructorHelper(
              cache,
              upstreamFactory,
              cacheReadOnlyFactory,
              new CacheDataSinkFactory(getDownloadCache(),  // no extra encryption here.
              CacheDataSink.DEFAULT_FRAGMENT_SIZE),
              /* priorityTaskManager= */ null);
```

Using these 3 steps, I can successfully download a stream, which is stored encrypted because the upstreamFactory already sends me encrypted data, and can be played back using the cacheReadOnlyFactory, which does the decryption. This works independent of the cache fragmentation (I tried with one fragment vs many).  So, I think the remaining questions is: Is my `AesEncryptingDataSource` doing the same as your server-side encryption? That's the code for reference:

```
public final class AesEncryptingDataSource implements DataSource {

  private final DataSource upstream;
  private final byte[] secretKey;
  private final byte[] scratch;

  @Nullable private AesFlushingCipher cipher;

  public AesCipherDataSource2(byte[] secretKey, DataSource upstream) {
    this.upstream = upstream;
    this.secretKey = secretKey;
    scratch = new byte[1024];
  }

  @Override
  public void addTransferListener(TransferListener transferListener) {
    upstream.addTransferListener(transferListener);
  }

  @Override
  public long open(DataSpec dataSpec) throws IOException {
    long dataLength = upstream.open(dataSpec);
    long nonce = CryptoUtil.getFNV64Hash(dataSpec.key);
    cipher = new AesFlushingCipher(Cipher.DECRYPT_MODE, secretKey, nonce,
        dataSpec.absoluteStreamPosition);
    return dataLength;
  }

  @Override
  public int read(byte[] data, int offset, int readLength) throws IOException {
    if (readLength == 0) {
      return 0;
    }
    int read = upstream.read(data, offset, readLength);
    if (read == C.RESULT_END_OF_INPUT) {
      return C.RESULT_END_OF_INPUT;
    }
    int bytesProcessed = 0;
    while (bytesProcessed < read) {
      int bytesToProcess = Math.min(read - bytesProcessed, scratch.length);
      castNonNull(cipher)
          .update(data, offset + bytesProcessed, bytesToProcess, scratch, /* outOffset= */ 0);
      System.arraycopy(scratch, 0, data, offset + bytesProcessed, bytesToProcess);
      bytesProcessed += bytesToProcess;
    }
    return read;
  }

  @Override
  @Nullable
  public Uri getUri() {
    return upstream.getUri();
  }

  @Override
  public Map<String, List<String>> getResponseHeaders() {
    return upstream.getResponseHeaders();
  }

  @Override
  public void close() throws IOException {
    cipher = null;
    upstream.close();
  }
}
```

**Comment by maskedpatel** [comment]
Thanks for the descriptive response. 
So the main difference between our encryption method and the AesEncryptingDataSource is that:
Given a file we generate an aes key and iv and encrypt the file. We then bundle the key, iv, and encrypted file and encrypt that entire bundle and send it out the client. The client will decrypt the bundle and then have access to the aes key, iv, and encrypted file which is where exoplayer comes in.

The thing is we know our encrypting/decrypting of the overall bundle works since it works for all other media and it even works for video with small enough file sizes. 
I tried your approach for creating the downloadManager via a rather hacky implementation on our part since we have a different iv + aes key for each video message played. The hackiness is that whenever we receive the video message we statically store the key + iv which will be used in initDownloadManager (latestkey, latestIv). Will find a better solution later, but for now we are passing the correct key/iv to all the required methods, and it still works for <5MB files but not for > 5MB. 

Heres what we did:
```
/// Constructor helper you used to create the downloadManager. These are all singletons so we 
/// tested one video at a time (since the key/iv change for different videos)
@Synchronized
    internal fun initDownloadManager() {
        if (downloadManager == null) {
            val index = DefaultDownloadIndex(getDatabaseProvider())
            val downloadConstructorHelper = DownloaderConstructorHelper(
                    getDownloadCache(),
                    buildHttpDataSourceFactory(),
                    getCacheReadFactory(key = latestKey, iv = latestIv),
                    CacheDataSinkFactory(getDownloadCache(), CacheDataSink.DEFAULT_FRAGMENT_SIZE),
                    null)
            downloadManager = DownloadManager(
                    application,
                    index,
                    DefaultDownloaderFactory(downloadConstructorHelper))
        }
    }

fun getCacheReadFactory(sha256: String? = "", iv: String?, key: String?): DataSource.Factory {
        if (cacheReadFactory == null) {
            cacheReadFactory = buildReadOnlyCacheDataSource(buildHttpDataSourceFactory(),
                    getDownloadCache(), sha256, iv, key)
        }
        return cacheReadFactory!!
    }

///Used by download service
override fun getDownloadManager(): DownloadManager {
        initDownloadManager()
        return downloadManager!!
    }

/// Our upstream
private fun buildHttpDataSourceFactory(): HttpDataSource.Factory {
        return DefaultHttpDataSourceFactory(userAgent)
    }

    /**
     * Creates and returns the cache used by this video manager's application
     */
    @Synchronized
    override fun getDownloadCache(): Cache {
        if (downloadCache == null) {
            val downloadContentDirectory = File(getDownloadDirectory(), DOWNLOAD_DIRECTORY)
            downloadCache = SimpleCache(downloadContentDirectory, NoOpCacheEvictor(),
                    getDatabaseProvider())
        }
        return downloadCache!!
    }

    fun getCacheReadFactory(sha256: String? = "", iv: String?, key: String?): DataSource.Factory {
        if (cacheReadFactory == null) {
            cacheReadFactory = buildReadOnlyCacheDataSource(buildHttpDataSourceFactory(),
                    getDownloadCache(), sha256, iv, key)
        }
        return cacheReadFactory!!
    }

    /// application is class variable storing context of app
    internal fun getDatabaseProvider(): DatabaseProvider {
        if (databaseProvider == null) {
            databaseProvider = ExoDatabaseProvider(application)
        }
        return databaseProvider!!
    }

    /**
     * Initializes and returns the download directory
     */
    internal fun getDownloadDirectory(): File {
        if (downloadDirectory == null) {
            downloadDirectory = application.getExternalFilesDir(null)
            if (downloadDirectory == null) {
                downloadDirectory = application.filesDir
            }
        }
        return downloadDirectory!!
    }
```

And for actually playing the video, we do the following:
```
/// Result of this is passed into buildMediaSource as the dataSourceFactory input
@SuppressLint("SyntheticAccessor")
    override fun buildDataSourceFactory(sha256: String?, iv: String?, key: String?): DataSource.Factory {
        val upstreamFactory = DefaultDataSourceFactory(application, buildHttpDataSourceFactory())
        return buildReadOnlyCacheDataSource(upstreamFactory, getDownloadCache(), sha256, iv, key)
    }

internal fun buildReadOnlyCacheDataSource(
                upstreamFactory: DataSource.Factory,
                cache: Cache,
                sha256: String?,
                iv: String?,
                key: String?):
                CacheDataSourceFactory {
            return CacheDataSourceFactory(cache, upstreamFactory,
                    encryptingFactory(sha256, iv, key), null,
                    CacheDataSource.FLAG_IGNORE_CACHE_ON_ERROR, null)
        }

        private fun encryptingFactory(sha256: String? = null,
                                      iv: String? = null, key: String? = null): DataSource.Factory {
            return if (isEncrypted(sha256, iv, key)) {
                // Important part for github issue
                DataSource.Factory {
                    CustomDataSource(FileDataSource(), key!!, iv!!)
                }
            } else {
                // Works
                FileDataSourceFactory()
            }
        }

        private fun isEncrypted(sha256: String?, iv: String?, key: String?): Boolean {
            return !iv.isNullOrEmpty() && !key.isNullOrEmpty()
        }

    private fun buildMediaSource(uri: Uri, dataSourceFactory: DataSource.Factory): MediaSource {
        return ProgressiveMediaSource.Factory(dataSourceFactory).createMediaSource(uri)
    }
```

Used as followed:
```
dataSourceFactory = videoManager!!.buildDataSourceFactory(sha256, iv, encKey)
videoManager?.playDownloadedVideo(playerView, uri, dataSourceFactory!!)
```

Now as I mentioned we do have an IV and AES key instead of generating it in our decryption implementation (unlike the exoplayer cipher). The rest is pretty much the same. Heres how we do it:
```
class CustomDataSource(val upstream: DataSource, val secretKey: String, val iv: String): DataSource {
    var cipher: CustomCipher? = null
    override fun addTransferListener(transferListener: TransferListener?) {
        upstream.addTransferListener(transferListener)
    }

    override fun open(dataSpec: DataSpec?): Long {
        val dataLength = upstream.open(dataSpec)
        cipher = CustomCipher(Cipher.DECRYPT_MODE, Base64.decode(secretKey), dataSpec!!.absoluteStreamPosition,
                Base64.decode(iv))
        return dataLength
    }

    override fun read(buffer: ByteArray?, offset: Int, readLength: Int): Int {
        if (readLength == 0) {
            return 0
        }
        val read = upstream.read(buffer, offset, readLength)
        if (read == C.RESULT_END_OF_INPUT) {
            return C.RESULT_END_OF_INPUT
        }
        cipher!!.updateInPlace(buffer, offset, read)
        return read
    }

    override fun getUri(): Uri? {
        return upstream.uri
    }

    override fun getResponseHeaders(): MutableMap<String, MutableList<String>> {
        return upstream.responseHeaders
    }

    override fun close() {
        cipher = null
        upstream.close()
    }
}

public final class CustomCipher {

    private final Cipher cipher;
    private final int blockSize;
    private final byte[] zerosBlock;
    private final byte[] flushedBlock;

    private int pendingXorBytes;

    public CustomCipher(int mode, byte[] secretKey, long offset, byte[] iv) {
        try {
            cipher = Cipher.getInstance("AES/CTR/NoPadding");
            blockSize = cipher.getBlockSize();
            zerosBlock = new byte[blockSize];
            flushedBlock = new byte[blockSize];
            int startPadding = (int) (offset % blockSize);
            cipher.init(
                    mode,
                    new SecretKeySpec(secretKey, "AES"),
                    new IvParameterSpec(iv));
            if (startPadding != 0) {
                updateInPlace(new byte[startPadding], 0, startPadding);
            }
        } catch (NoSuchAlgorithmException | NoSuchPaddingException | InvalidKeyException
                | InvalidAlgorithmParameterException e) {
            // Should never happen.
            throw new RuntimeException(e);
        }
    }

    public void updateInPlace(byte[] data, int offset, int length) {
        update(data, offset, length, data, offset);
    }

    public void update(byte[] in, int inOffset, int length, byte[] out, int outOffset) {
        // If we previously flushed the cipher by inputting zeros up to a block boundary, then we need
        // to manually transform the data that actually ended the block. See the comment below for more
        // details.
        while (pendingXorBytes > 0) {
            out[outOffset] = (byte) (in[inOffset] ^ flushedBlock[blockSize - pendingXorBytes]);
            outOffset++;
            inOffset++;
            pendingXorBytes--;
            length--;
            if (length == 0) {
                return;
            }
        }

        // Do the bulk of the update.
        int written = nonFlushingUpdate(in, inOffset, length, out, outOffset);
        if (length == written) {
            return;
        }

        // We need to finish the block to flush out the remaining bytes. We do so by inputting zeros,
        // so that the corresponding bytes output by the cipher are those that would have been XORed
        // against the real end-of-block data to transform it. We store these bytes so that we can
        // perform the transformation manually in the case of a subsequent call to this method with
        // the real data.
        int bytesToFlush = length - written;
        Assertions.checkState(bytesToFlush < blockSize);
        outOffset += written;
        pendingXorBytes = blockSize - bytesToFlush;
        written = nonFlushingUpdate(zerosBlock, 0, pendingXorBytes, flushedBlock, 0);
        Assertions.checkState(written == blockSize);
        // The first part of xorBytes contains the flushed data, which we copy out. The remainder
        // contains the bytes that will be needed for manual transformation in a subsequent call.
        for (int i = 0; i < bytesToFlush; i++) {
            out[outOffset++] = flushedBlock[i];
        }
    }

    private int nonFlushingUpdate(byte[] in, int inOffset, int length, byte[] out, int outOffset) {
        try {
            return cipher.update(in, inOffset, length, out, outOffset);
        } catch (ShortBufferException e) {
            // Should never happen.
            throw new RuntimeException(e);
        }
    }
}
```

I really feel it must be something small we are missing since cache fragmentation is the only case where we aren't able to decrypt.

**Comment by tonihei** [comment]
The only notable diffference I can see is that ExoPlayer's AesFlushingCipher creates the IV using `ByteBuffer.allocate(16).putLong(nonce).putLong(counter).array()` where `nonce` is the same for all requests and `counter` is `dataSpec.absoluteStreamPosition / cipher.blockSize()`. In your example you always use the same IV irrespective of the absoluteStreamPosition. I'm no expert in how these ciphers work internally, but I wonder whether this may cause differences if the absoluteStreamPosition is not 0?

I think another potential problem is that the fragmented files may not start or end with a full cipher block? Not sure if that can cause issues.

**Comment by tonihei** [comment]
Closing this issue now due to inactivity.
