### ISSUE TITLE
Set Surface type in exo_player_view.xml to allow all PlayerViews to inherit specified surface type  [2.10.2]

### ISSUE THREAD

**Issue by greyski** [google/ExoPlayer#6123]
### [REQUIRED] Use case description
Related to https://github.com/google/ExoPlayer/issues/5387

The current problem we're running into is that `SurfaceView` is causing odd UI issues that we haven't found a solution for (videos from a previous `Fragment` visually overlapping/overdrawing videos on another `Fragment`), however we noticed that `TextureView` resolves the issue. We want to be able to specify that ALL `PlayerView`'s within our application use `TextureView`, but in order to do that we have to:

1) Write a lint rule that errors when developers create a `PlayerView` in xml to ALWAYS include
`app:surface_type="texture_view"`

2) Make the `constructor(context)` *private* to prevent developers from dynamically creating `PlayerView` and instead require they use `PlayerView.from(context)` that behind the scenes does `return LayoutInflator.from(context).inflate(R.layout.texture_player_view, . . .)` which populates a simple xml layout something like:
```
<?xml version="1.0" encoding="utf-8"?>
<PlayerView
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    app:surface_type="texture_view"
    />
```
### Proposed solution
I noticed in `PlayerView` we rely on the `contentFrame` being set as `AspectRatioFrameLayout` and is required for the `Surface` to be even created:
```
    // Create a surface view and insert it into the content frame, if there is one.
    if (contentFrame != null && surfaceType != SURFACE_TYPE_NONE) {
```

In theory, we could move the `surface_type` field INTO an exoplayer style for the underlying `contentFrame` so in the `exo_player_view.xml` developers are allowed to customize the surface type for ALL of their `PlayerView`'s ala:
```
<?xml version="1.0" encoding="utf-8"?>
<merge xmlns:android="http://schemas.android.com/apk/res/android">

    <com.google.android.exoplayer2.ui.AspectRatioFrameLayout
        android:id="@id/exo_content_frame"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_gravity="center"
        app:surface_type="texture_view">
/ . . etc . . /
</merge>
```

### Alternatives considered

n/a

**Comment by ojw28** [comment]
I don't understand how the proposal actually ensures what you want, which is

> We want to be able to specify that ALL PlayerView's within our application use TextureView

The developer could still just use the constructor that doesn't have the `surfaceType` argument, or pass a `surfaceType` value that's not the one you want to use. Please clarify.

**Comment by greyski** [comment]
@ojw28 Updated title and description, does this idea make sense?

**Comment by ojw28** [comment]
It looks like the request is now just to have a way of changing the default `surfaceType` value to `textureView`, so that all `PlayerViews` inflated by your app will use that default unless they explicitly specify otherwise. Exactly how that default is changed probably doesn't matter too much to you, as long as you have a way to change it. Is that correct?

I'm not sure we need a style for this. We could probably define a resource constant that you could override instead. I'd need to check this though - it's been a while since I touched UI code so I'm not certain whether this would work.

**Comment by greyski** [comment]
```
all PlayerViews inflated by your app will use that default unless they explicitly specify otherwise
```
^That's the dream.

Apologies I misspoke regarding using `style`, but instead adding an attribute to `AspectRatioFrameLayout` that allows us to specify the default `surface_type` for the `PlayerView`.

Just to pitch the idea a bit more, I feel this makes sense because of how closely dependent the two UI objects are on each other (more-so Surface to `AspectRatioFrameLayout`). Here's a snipped from the `PlayerView` constructor source:
```
    . . . etc . . .
// Content frame.
    contentFrame = findViewById(R.id.exo_content_frame);
    if (contentFrame != null) {
      setResizeModeRaw(contentFrame, resizeMode);
    }

   . . . etc . . .

    // Create a surface view and insert it into the content frame, if there is one.
    if (contentFrame != null && surfaceType != SURFACE_TYPE_NONE) {
      ViewGroup.LayoutParams params =
          new ViewGroup.LayoutParams(
              ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT);
      switch (surfaceType) {
        case SURFACE_TYPE_TEXTURE_VIEW:
          surfaceView = new TextureView(context);
          break;
        case SURFACE_TYPE_MONO360_VIEW:
          SphericalSurfaceView sphericalSurfaceView = new SphericalSurfaceView(context);
          sphericalSurfaceView.setSingleTapListener(componentListener);
          surfaceView = sphericalSurfaceView;
          break;
        default:
          surfaceView = new SurfaceView(context);
          break;
      }
      surfaceView.setLayoutParams(params);
      contentFrame.addView(surfaceView, 0);
    } else {
      surfaceView = null;
    }
```
^ The `PlayerView` only creates a surface *if* there is a `contentFrame` available. Not only that, but the `contentFrame` *must* be of type `AspectRatioFrameLayout`. Only then does a surface become both created and attached to the underlying `contentFrame`.

I feel this example highlights how `AspectRatioFrameLayout` should be allowed to set what type of `Surface` it adds as a child.

How it would do this, is up for interpretation. One idea is adding a new attribute like I've mentioned earlier:
```
<com.google.android.exoplayer2.ui.AspectRatioFrameLayout
        android:id="@id/exo_content_frame"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_gravity="center"
        app:surface_type="texture_view">
```
Then in the `PlayerView` constructor we could do something like:
```
    // Content frame.
    contentFrame = findViewById(R.id.exo_content_frame);
    if (contentFrame != null) {
      setResizeModeRaw(contentFrame, resizeMode);
      surfaceType = contentFrame.getSurfaceType(surfaceType);
    }
```
Meanwhile in `AspectRatioFrameLayout` we do:
```
  private int surfaceType;

  public AspectRatioFrameLayout(Context context, AttributeSet attrs) {
    super(context, attrs);
    resizeMode = RESIZE_MODE_FIT;
    if (attrs != null) {
      TypedArray a = context.getTheme().obtainStyledAttributes(attrs,
          R.styleable.AspectRatioFrameLayout, 0, 0);
      try {
        resizeMode = a.getInt(R.styleable.AspectRatioFrameLayout_resize_mode, RESIZE_MODE_FIT);
        surfaceType = a.getInt(R.styleable.AspectRatioFrameLayout_surface_type, SURFACE_TYPE_NONE);
      } finally {
        a.recycle();
      }
    }

   public int getSurfaceType(int defaultSurfaceType) {
      if (surfaceType == SURFACE_TYPE_NONE) {
          surfaceType = defaultSurfaceType;
      }
      return surfaceType;
   }
```
^Okay, so maybe it's not the most elegant solution, but it's totally doable.

**Comment by ojw28** [comment]
What's the value of plumbing it through `AspectRatioFrameLayout`? We could do that, but we could probably also just define a resource value that `PlayerView` reads directly. If that works, isn't it a much simpler way of doing pretty much the same thing?

**Comment by greyski** [comment]
Technically we already do have a value in `PlayerView` called `surface_type` that can be set to either `texture_view`, `surface_view`, or `none`. [See doc on PlayerView.](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/ui/PlayerView.html)

However, we are unable to utilize these attributes in the required `exo_player_view.xml` file as the structure uses the `<merge>` tag which, if I remember correctly, does not inherit any attributes of its inflating parent View.

`exo_player_view.xml` example:
```
<?xml version="1.0" encoding="utf-8"?>
<merge xmlns:android="http://schemas.android.com/apk/res/android"
   xmlns:app="http://schemas.android.com/apk/res-auto"
   app:surface_type="texture_view"> <!-- Is not passed into PlayerView -->

    <com.google.android.exoplayer2.ui.AspectRatioFrameLayout
        android:id="@id/exo_content_frame"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_gravity="center">

        <!-- Video surface will be inserted as the first child of the content frame. -->

        <View
            android:id="@id/exo_shutter"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:background="@android:color/transparent"/>

        <com.google.android.exoplayer2.ui.SubtitleView
            android:id="@id/exo_subtitles"
            android:layout_width="match_parent"
            android:layout_height="match_parent"/>

        <ProgressBar
            android:id="@id/exo_buffering"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:indeterminate="true"
            android:layout_gravity="center"/>

        <TextView
            android:id="@id/exo_error_message"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_gravity="center"
            android:gravity="center"
            android:background="@color/exo_error_message_background_color"
            android:padding="16dp"/>

    </com.google.android.exoplayer2.ui.AspectRatioFrameLayout>

    <FrameLayout
        android:id="@id/exo_overlay"
        android:layout_width="match_parent"
        android:layout_height="match_parent"/>

    <com.testing.SimplePlayerControlView
        android:id="@+id/exo_controller"
        android:layout_width="match_parent"
        android:layout_height="match_parent"/>
</merge>
```

**Comment by greyski** [comment]
By only exposing this attribute at the `PlayerView` level it limits our ability to explicitly set the `surface_type` across ALL instances of `PlayerView` for our app. We would essentially have to do:
```
<PlayerView
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    app:surface_type="texture_view" <-- This -->
    />
```
For every location we create a `PlayerView` in XML. It also becomes even MORE of a hassle if we want to dynamically create the `PlayerView` in code as the `surface_type` cannot be set at runtime.

**Comment by greyski** [comment]
I agree that plumbing it into `AspectRatioFrameLayout` isn't exactly elegant, but it was the most immediate solution I noticed when looking at the inner-workings of the `PlayerView` source.

**Comment by eneim** [comment]
@greyski If PlayerView to support default style via the 4th constructor parameter (which I think should be the way to solve this problem), you can define the style in your theme and PlayerView can automatically apply that.

Ref: https://developer.android.com/reference/android/content/res/Resources.Theme.html#obtainStyledAttributes(android.util.AttributeSet,%20int[],%20int,%20int)

For example this is how CardView is created with default style:

https://android.googlesource.com/platform/frameworks/support/+/refs/heads/androidx-master-dev/cardview/src/main/java/androidx/cardview/widget/CardView.java#123

**Comment by eneim** [comment]
@greyski Just find this [theme setup](https://github.com/google/ExoPlayer/blob/release-v2/demos/main/src/main/res/values/styles.xml#L27) in demo app. Using this theme will automatically apply this ``surface_type`` to your PlayerView unless you set it again in layout xml.

**Comment by ojw28** [comment]
Yeah, it seems this "just works" already by setting `<item name="surface_type">texture_view</item>` in the style that your activities are using.

**Comment by tonihei** [comment]
Am I right in assuming this question has been solved? Closing under this assumption. Feel free to reopen if that's not the case.

**Comment by greyski** [comment]
~Just closing the loop on this for other peeps reading this. In order to achieve this "theme" support for you need to add the `surface_type`s you want into your app's `attrs.xml` (copied from ExoPlayer demo app):~
If your app has it's themes in an isolated module that doesn't import the ExoPlayer library, you'll need to copy the attributes from the lib source (probably not a great idea, but it works):
```
    <!-- Must be kept in sync with PlayerView -->
    <attr name="surface_type" format="enum">
        <enum name="none" value="0"/>
        <enum name="surface_view" value="1"/>
        <enum name="texture_view" value="2"/>
        <enum name="spherical_view" value="3"/>
    </attr>
```
Then in your app's `styles.xml` you'll label the `surface_type` as so:
```
    <!-- App-wide theme -->
    <style name="Theme.MyApp" parent="Theme.AppCompat.Whatever">
        <item name="surface_type">texture_view</item>
    </style>
```
Thanks @eneim!

~My only ask is to expose these attributes in the ExoPlayer library to avoid misalignment with any changes in the `surface_type` values of `PlayerView` as requiring devs to duplicate these attributes into their own apps could cause issues if the `surface_type` API were to change.~

**Edit:** My mistake, we have our styles defined in a separate module that doesn't import the ExoPlayer project, which requires us to extract these attributes.

**Comment by ojw28** [comment]
When I tried this I was just able to do the second part directly. Are you sure the first part is necessary? Note that the demo app is also able to do this without having to do anything in `attrs.xml` (https://github.com/google/ExoPlayer/blob/release-v2/demos/main/src/main/res/values/styles.xml#L27).

**Comment by greyski** [comment]
@ojw28 Good catch, this is related to our own project's module structure (our app's base `styles.xml` are in a module that doesn't import the ExoPlayer library). I updated my above comment to reflect this.

**Comment by greyski** [comment]
Adding a note, including this field to your apps theme will only apply to `PlayerView`'s created via XML. Dynamically created `PlayerView` components **will not** inherit these attributes, as shown in the `PlayerView` constructor source:
```
    if (attrs != null) {
      TypedArray a = context.getTheme().obtainStyledAttributes(attrs, R.styleable.PlayerView, 0, 0);
```
The themes attributes will never reach the underlying fields unless `attrs` is non-null (e.g. inflated via XML).
