### ISSUE TITLE
Change stream quality without dialog

### ISSUE THREAD

**Issue by annetube** [google/ExoPlayer#6125]
### [REQUIRED] Searched documentation and issues
I already look on demodev site and code of TraselectionView

### [REQUIRED] Question
Hello, i would want to know how can i change manualy the quality of an adaptive stream without dialog, i looked about how the trackselectorview do, but its confusing to how the which var is been used...

I want to that for idealy select the desirred quality of the stream before playing it before playing ,
the boolean setForceLowestBitrate or highest are not fiting my requierements because i would want keep by default the quality (or the closest one if the exact quality is not available) choosed previously by user on the previous mediasource.

Thanks for your help

**Comment by tonihei** [comment]
Please have a look at the [guide page for track selection](https://exoplayer.dev/track-selection.html) to see how specifying selection constraints works in general. 

The track selection parameters also offer options to set the maximum bitrate or the maximum video size, which sounds like something you would need for your use case.

**Comment by coveroid** [comment]
Thanks for your answer, unfortunately it's not what I want, I already tried it, i don't want the maximum or minimum I would want the closest, I've already the algorithm (to choose the right one between the child tracks of the master) do that, what I miss, it's just select this track and play it (without dialog)

**Comment by tonihei** [comment]
You should still be able to set the maximum bitrate. For example, if your user select "720p" from the UI, you can set the maximum to video height to 720, or if you worry about slightly different sizes, you could set it 800 or something like that. If you additionally want to prevent switching down automatically, you can also set the `forceHighestSupportedBitrate` option to `true`.

**Comment by coveroid** [comment]
Thanks for your answer, I think, i understand how you see things but it
doesnt work like I would want to :

Video A 360 480 720
Video B  180, 520

Lets say user choose on video À the 480 version, and after he decides to
choose the video B, with what you suggest me (480 max +highest) ,he's gonna
get the video b on 180, and i would like he gets the closest one of 480 so
the 520 version of video B.

As I said previously, the algorithm works, i just would like to be able to
switch between stream quality without UI.

Thanks you

**Comment by tonihei** [comment]
You can always switch quality after the stream has been created with setting an `SelectionOverride` to the `DefaultTrackSelector` parameters. But that will cause a reload at the current position and I assume you are looking for a way to immediately start with the correct formats. 

There is an open enhancement for the option to filter formats dynamically without affecting playback (tracked by #5082 and #2250 with slightly different focus respectively). This feature would also help for this case.

Otherwise, I'm not entirely convinced that choosing the "closest" format is a common requirement. Most apps that let the user choose a resolution imply that this is the maximum and if that's not available a lower resolution is used. In your example, you could set the maximum height to 719 if the user selects 480, if you think that the user would accept any format as long as it's smaller than the next one in the list (720). That's still not the "closest" in all cases, but I assume it would work in practice.

**Comment by annetube** [comment]
Tanks for your answer, i'm gonna finally mix your approach with mine. To do that i'm using the player listener when video is resize with a boolean. its probably not clear for you but the only thing missing is to be able to set this boolean  when a bitrate is selected from dialog :
but the onclick method always return me -1

I need this boolean on the player Activity, so i tried to override the interface onclick but it always return me -1 for the int which ...

```
TrackSelectionDialog trackSelectionDialog =new TrackSelectionDialog();
                TrackSelectionDialog mytrackselection= TrackSelectionDialog.createForMappedTrackInfoAndParameters(R.string.app_name,
                        mappedTrackInfo, trackSelector.getParameters(), false, false, new DialogInterface.OnClickListener() {
                            @Override
                            public void onClick(DialogInterface dialog, int which) {
                                 DefaultTrackSelector.SelectionOverride selectionOverride = new DefaultTrackSelector.SelectionOverride(0,which);
                                trackSelector.setParameters(
                                        trackSelector
                                                .buildUponParameters()
                                                .setSelectionOverride(0, trackSelector.getCurrentMappedTrackInfo().getTrackGroups(0), selectionOverride));
            resizemanual=true;

                            }


                        }, new DialogInterface.OnDismissListener() {
                            @Override
                            public void onDismiss(DialogInterface dialog) {

                            }
                        }
                );

                mytrackselection.show(getSupportFragmentManager(), /* tag= */ null);
            }
    }
```



Like this i can make the difference between a difference of quality because the video has been changed or because the video bitrate has been change manually or not =>

```
  @Override
    public void onVideoSizeChanged(int width, int height, int unappliedRotationDegrees, float pixelWidthHeightRatio) {
        if (resizemanual) {
            resolution_width = String.valueOf(width);
            resolution_height = String.valueOf(height);
            resizemanual=false;
        }
    }
```



Can you help me to solve this problem ?

**Comment by tonihei** [comment]
Is this still related to the original issue? I can't really follow what the problem actually is.

**Comment by coveroid** [comment]
It's a bit related, the code I showed is the code of a onclick button from
my player activity.

I need to change the quality from the player activity not from
TrackSelectiondialog

I tried to implement the onclick interface of the TrackSelectiondialog
inside the player activity (on my onclick button)

But the int "which" of this interface implementation, return - 1, so when i
tried to switch to the trackselector desired bitrate. I got
indexoutofbounds error

**Comment by tonihei** [comment]
If that is the `TrackSelectionDialog` of our demo app, please have a look at [how we handle track selection during playback in there](https://github.com/google/ExoPlayer/blob/1ab402cf27ab3c52d671ef15b25a1cdde1fe84c8/demos/main/src/main/java/com/google/android/exoplayer2/demo/TrackSelectionDialog.java#L98).

The `which` argument is the button being clicked and `-1` is the value for `DialogInterface.BUTTON_POSITIVE`.

**Comment by coveroid** [comment]
Thanks for your support, I've been able to do what I wanted,
