### ISSUE TITLE
Add VR button for the Player & Enable when clicked(for 360 videos)

### ISSUE THREAD

**Issue by QuaQuaAndroid** [google/ExoPlayer#6126]
Enable VR mode for 360 videos

**Comment by tonihei** [comment]
It's unclear what this actually refers to. Our demo app already supports 360° videos and you can start playing your own by specifying the "spherical_stereo_mode" parameter in the sample list or providing an extra with the same name to the PlayerActivity.

If that question is about something else, please clarify.

**Comment by QuaQuaAndroid** [comment]
> It's unclear what this actually refers to. Our demo app already supports 360° videos and you can start playing your own by specifying the "spherical_stereo_mode" parameter in the sample list or providing an extra with the same name to the PlayerActivity.
> 
> If that question is about something else, please clarify.

@tonihei : Thanks for the update. I'm playing 360 videos using "spherical_view".
All I need is to add a VR button to the Player, by clicking on it VR mode should be enabled to the User.
Can you please help me out with this requirement.?

**Comment by tonihei** [comment]
What do you mean by enabling it? A video with 360° looks rather strange if you don't use the spherical_view - so you always need to enable it by default for such videos. 

There is the option to set different stereo modes (mono, top/bottom, left/right) as [shown in our demo app](https://github.com/google/ExoPlayer/blob/1ab402cf27ab3c52d671ef15b25a1cdde1fe84c8/demos/main/src/main/java/com/google/android/exoplayer2/demo/PlayerActivity.java#L186), if that is what you are looking for.

**Comment by QuaQuaAndroid** [comment]
@tonihei : All I need is a button to enable Virtual Reality(VR) mode for 360 videos in Exoplayer.
So, user can enable VR mode using that button.
I need help to integrate it for 360 videos in my Application.
