### ISSUE TITLE
How do I download HLS file with cookies?

### ISSUE THREAD

**Issue by chanbbong** [google/ExoPlayer#6127]
I play HLS file with the cookie using getDefaultRequestProperties().
but If I download HLS file with cookies using DownloadManager, DownloadTracker, DownloadService, getDefaultRequestProperties, I will get 403 error.

`Failed to start download
    com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403`

**Comment by tonihei** [comment]
I'm not entirely sure I understand the full issue, but I assume you are setting a cookie for the HTTP connection by using `DefaultHttpDataSource.Factory.setDefaultRequestProperty`. 

This should work in the same way for downloading. You can specify the upstream (HTTP) data source factory  when creating the `DownloadManager` (as shown on [this page](https://exoplayer.dev/downloading-media.html#creating-a-downloadmanager)). If you use the same factory as for playback, everything should work as expected. If not, please provide more detailed reproduction steps and example media.

**Comment by chanbbong** [comment]
I'm sorry. I was too dependent on demo.
I need to create flow to init DownloadManager after cookie is loaded.
thanks.
