### ISSUE TITLE
Hardware Accelerated H264

### ISSUE THREAD

**Issue by Schizo** [google/ExoPlayer#613]
I couldn't find any Information regarding the Hardware Codec in mobile devices. Is Exoplayer taking advantage of that? Is it possible to activate/deactivate it?

**Comment by andrewlewis** [comment]
Yes. We use the first listed codec that can play the input format, which should be the most preferred one. It will be a hardware codec if one is available. Have a look at MediaCodecUtil to see how this works.

You can change this behavior by overriding MediaCodecTrackRenderer.getDecoderInfo(), returning a DecoderInfo with the name of the OMX component you want to use, like "OMX.google.h264.decoder". Note that device vendors don't have to include any particular named components in general, so it is important to make sure the OMX component is present, otherwise creating it may fail.

**Comment by Schizo** [comment]
Thank you!

**Comment by dnutcracker** [comment]
This is not really possible since DecoderInfo constructor has package visability - so while overriding getDecoderInfo() is possible - you cannot create a DecoderInfo by yourself.
See here - 
https://github.com/google/ExoPlayer/issues/938

**Comment by andrewlewis** [comment]
Good point. It seems reasonable to have a way for apps to override the default codec in case they need to work around some app-specific issue, but in almost all cases the choice of what OMX component to use should be left up to the framework (as implemented in MediaCodecUtil). For example, a device could in theory create several efficient 'hardware' decoders concurrently before running out of resources and falling back to creating software decoders.

**Comment by dnutcracker** [comment]
Yep - that's exactly my point - an easy entry point for special cases.
Btw, from my experience at least, mixing software and hardware decoders is a bit messy, especially when there's rotation to apply and each implementation (even h264 decoders) does something different.

**Comment by kneep** [comment]
Is there any update for this issue? I ran into the same problem. In most cases the framework chooses the right decoder. But sometimes, maybe for debug purpose, we need to switch to a specific decoder to see if it behaves the same as another decoder. I think currently it is possible but not that easy. Codec selectors are tightly coupled with the constructor of SimpleExoPlayer, which makes it hard to subclass SimpleExoplayer only to use another codec selector but still to keep other handy features of SimpleExoPlayer.

**Comment by andrewlewis** [comment]
In ExoPlayer 2, it should be quite straightforward to subclass SimpleExoPlayer and override buildVideoRenderers/buildAudioRenderers to pass your own implementation of MediaCodecSelector to the renderer constructors. This should be very little extra code, especially if you miss out the code for building extension renderers.

**Comment by kneep** [comment]
I saw the changes in version 2.4. That is better and that is exactly what I would suggest - we don't have to subclass SimpleExoPlayer only in order to pick a different decoder.
