### ISSUE TITLE
How to add full screen mode button to ExoPlayer, by clicking it should enable full screen mode(change orientation like YouTube)

### ISSUE THREAD

**Issue by QuaQuaAndroid** [google/ExoPlayer#6131]
How to add full screen mode button to ExoPlayer, by clicking it should enable full screen mode(change orientation like YouTube).
Portrait to Landscape and Vice-versa.

**Comment by tonihei** [comment]
Duplicate of #1845.  There unfortunately no easy way to implement such a button for all Android devices.

**Comment by tiendatit92** [comment]
This is my project. You can follow in there
https://github.com/tiendatit92/ExoplayerFullscreenLandcapse
