### ISSUE TITLE
Exoplayer doesn't play Widevine HLS (no errors, no callbacks, only black screen)

### ISSUE THREAD

**Issue by tipoc123** [google/ExoPlayer#6134]
### [REQUIRED] Issue description
Exoplayer doesn't play Widevine HLS content (Axinom DRM). It shows only a black screen.

There are no errors in logcat. None of drm callbacks (onDrmSessionAcquired, onDrmSessionManagerError, onDrmKeysRestored, onDrmKeysRemoved, onDrmKeysLoaded, onDrmSessionReleased) are called (only onLoadStarted and onLoadCompleted).

The same content as Widevine DASH works fine.

### [REQUIRED] Reproduction steps
Play content protected by Axinom DRM.

### [REQUIRED] Link to test content
Sorry, no publicly available link, only playlists (mpd and m3u8 files):
[playlists.zip](https://github.com/google/ExoPlayer/files/3360518/playlists.zip)

### [REQUIRED] A full bug report captured from the device
[bugreport.txt](https://github.com/google/ExoPlayer/files/3360509/bugreport.txt)

### [REQUIRED] Version of ExoPlayer being used
2.10.0

### [REQUIRED] Device(s) and version(s) of Android being used
Android 6.0.1
STB GIEC MP1113 (chip Amlogic s905x)

**Comment by tipoc123** [comment]
I can send you mp4 files if you need it.

**Comment by tonihei** [comment]
It sounds as if the key requests are not working for the Axinom servers for some reason. There are currently no callback events telling you that. This is tracked by #5399 and may be the reason why you don't see any events related to that. 

If you can provide us with a working example (you can send it to dev.exoplayer@gmail.com), we can take a look and verify if that's the issue. Otherwise, you can also try to debug it yourself by checking which DrmSession calls are actually being made.

**Comment by tipoc123** [comment]
I've logged invokes of `executeKeyRequest` and `executeProvisionRequest` (methods in `HttpMediaDrmCallback`).
1) Widevine DASH - there are `executeKeyRequest` calls
2) Widevine HLS - there are NO `executeKeyRequest` calls

What else should I log?

**Comment by tonihei** [comment]
Looking at the provided HLS playlist, it seems to me that is does not contain any #EXT-X-KEY tag to define the initialization vector. You need to add this to support encryption.

**Comment by tipoc123** [comment]
You can see #EXT-X-KEY in `stream_0.m3u8` and `stream_1.m3u8` files.

**Comment by tonihei** [comment]
Sorry, you're right. I was looking at the wrong place.

Could that be related to the issue in #6130? If the initialization segments don't load, the player will never reach the point where it tries to make the key requests.

**Comment by tipoc123** [comment]
> Sorry, you're right. I was looking at the wrong place.
> 
> Could that be related to the issue in #6130? If the initialization segments don't load, the player will never reach the point where it tries to make the key requests.

No, we've already resolved that issue :)

**Comment by tonihei** [comment]
Is it at all possible to get a publicly accessible example? There could be many issues which are difficult to see without actually stepping through the code ourselves.

**Comment by tipoc123** [comment]
> Is it at all possible to get a publicly accessible example? There could be many issues which are difficult to see without actually stepping through the code ourselves.

I've sent you an email.

**Comment by tonihei** [comment]
I managed to play both the provided DASH and HLS streams without any issues. In both cases I used the same drm configuration as discusses in the email thread. Given that it works fine in the ExoPlayer demo app, it's probably an app issue of some sort.

**Comment by tipoc123** [comment]
OK. I'll try again later and give you an answer.

**Comment by tipoc123** [comment]
Now it's working. The problem was in our playlist.
