### ISSUE TITLE
How does the decoding take place inside exoplayer?

### ISSUE THREAD

**Issue by GaureeshAnvekar** [google/ExoPlayer#6136]
Is there a codec algorithm implemented inside exoplayer library? I need to access the decoded frames along with metadata like "syntax elements" for H264.

### [REQUIRED] Searched documentation and issues
I have already gone through the exoplayer official documentation. But scarce information is available.

### [REQUIRED] Question
I need to access the "Syntax elements" and decoded frames and perform further processing on the frames before display.

**Comment by tonihei** [comment]
The decoding itself is forwarded to the Android platform `MediaCodec` classes. 

If you are aiming to modify the decoded frames (e.g. to apply effects), please read the comments in this issue: https://github.com/google/ExoPlayer/issues/5860#issuecomment-491347115. 

It's probably difficult to obtain the "syntax elements" though. What are you trying to achieve with that?

**Comment by andrewlewis** [comment]
Just a note about accessing syntax elements: although this is not really something we intend to support, you may find the utility methods in [`NalUnitUtil`](https://github.com/google/ExoPlayer/blob/e25b7d2/library/core/src/main/java/com/google/android/exoplayer2/util/NalUnitUtil.java) and/or [`ParsableNalUnitBitArray`](https://github.com/google/ExoPlayer/blob/e25b7d2148caabe0db75d541662eb99df3ed8080/library/core/src/main/java/com/google/android/exoplayer2/util/ParsableNalUnitBitArray.java) useful for writing your own code to parse the compressed (input) H.264 bitstream. If you specifically want something from the SPS/PPS then there are methods for getting some limited information from them in `NalUnitUtil`.
