### ISSUE TITLE
Correct order of tracks related events

### ISSUE THREAD

**Issue by AfanasievAnton** [google/ExoPlayer#6143]
### [REQUIRED] Searched documentation and issues
Source code + Issues 

### [REQUIRED] Question
Is there any possible scenario where onDownstreamFormatChanged() triggered before onTracksChanged() ? We are using exo 2.4.1 and we have some wrappers around this events. Also we kind of "rely" on the order this events dispatched (first onTracksChanged then onDownstreamFormatChanged)
Just want to know if on your side onDownstreamFormatChanged will always be called after onTracksChanged
### A full bug report captured from the device
No

### Link to test content
I do not believe that it is content related.

**Comment by tonihei** [comment]
Yes, that is guaranteed for the start of the playback. 

Note that further onTracksChanged and onDownstreamFormatChanged events can happen independently and in any order.
