### ISSUE TITLE
[CAST EXTENSION] Audio Streaming and Default Receiver App customization

### ISSUE THREAD

**Issue by JonathanImperato** [google/ExoPlayer#6148]
### [REQUIRED] Searched documentation and issues
I have been looking on Github, issue, demo app, Medium Articles and Offical Website docs.

### [REQUIRED] Question
Is it possible to choose an Image (or even a WebImage as for the logo) to display in the background while casting only audio content?

### A full bug report captured from the device
NONE

### Link to test content
NONE

**Comment by ojw28** [comment]
I think you should be building a custom cast receiver for this kind of thing, which isn't really in the scope of this issue tracker. I'd suggest you start [here](https://codelabs.developers.google.com/codelabs/cast-receiver/#0).

**Comment by JonathanImperato** [comment]
I asked here because I saw that you can set some WebImage(s) when creating the MediaQueueItem with the MediaInfo...By the way I will have a look at it. Thanks anyway.
