### ISSUE TITLE
Start playing a live stream with a certain offset from the live edge

### ISSUE THREAD

**Issue by okycelt** [google/ExoPlayer#6149]
### Searched documentation and issues
https://exoplayer.dev, #1268, #4187

### Question
Is there a possibility to seek from the live edge on prepare time in a live stream? Our use case is basically the same as in #1268, to resume a live content playback. Our current solution is based on #1268, we seek to `player.getDuration() - offset` on `Player.STATE_READY`. But this is not ideal. We'd like to achieve this on prepare time. Are we missing something? 

For example ShakaPlayer allows to specify a negative offset during preparation, which will cause the playback to start several seconds before live edge. https://github.com/google/shaka-player/issues/1178

**Comment by ojw28** [comment]
By default we'll start playback at the offset specified in the content itself. You can override it with `builder.setLivePresentationDelayMs` though, where `builder` is a `DashMediaSource.Builder`, `HlsMediaSource.Builder` or `SsMediaSource.Builder`. Does that do what you need?

**Comment by okycelt** [comment]
Yes, that's exactly what we need. Thanks for a quick reply.
