### ISSUE TITLE
Live: Add option to keep on the live edge (e.g. after re-buffering

### ISSUE THREAD

**Issue by ojw28** [google/ExoPlayer#6152]
### Use case description
For some live streams, it's preferable to avoid falling behind the live edge on buffering. This can be achieved by skipping ahead, or by adjusting the playback rate to slightly greater than 1x to catch up. It's possible to implement skipping ahead at the application layer, but it's a bit fiddly. We should provide a way for applications to configure the preferred behaviour directly on the player.

### Proposed solution
Allow the player to be configured with preferred behaviour when buffering is encountered on a live stream. We may also want to move `setLivePresentationDelay` out of the `MediaSource` builders are into this configuration.

**Comment by Richjard** [comment]
estoy usando android tv 
public class PlaybackVideoFragment extends VideoSupportFragment {

    private PlaybackTransportControlGlue<MediaPlayerAdapter> mTransportControlGlue;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        final Movie movie =
                (Movie) getActivity().getIntent().getSerializableExtra(DetailsActivity.MOVIE);

        VideoSupportFragmentGlueHost glueHost =
                new VideoSupportFragmentGlueHost(PlaybackVideoFragment.this);

        MediaPlayerAdapter playerAdapter = new MediaPlayerAdapter(getContext());
        playerAdapter.setRepeatAction(PlaybackControlsRow.RepeatAction.INDEX_NONE);

        mTransportControlGlue = new PlaybackTransportControlGlue<>(getContext(), playerAdapter);
        mTransportControlGlue.setHost(glueHost);
        mTransportControlGlue.setTitle(movie.getTitle());
        mTransportControlGlue.setSubtitle(movie.getDescription());
        mTransportControlGlue.playWhenPrepared();
        playerAdapter.setDataSource(Uri.parse(movie.getVideoUrl()));


    }

    @Override
    public void onPause() {
        super.onPause();
        if (mTransportControlGlue != null) {
            mTransportControlGlue.pause();
        }
    }
}

**como puedo reemplazarlo por exoplayer**

**Comment by jmar777** [comment]
Hey, I'm preparing to implement this logic external to the player, but I wanted to make sure that this hasn't already been started in one of the dev branches?

Assuming not, would the recommended solution effectively come down to a polling handler that inspects delay / updates playback rate on an interval?

Many thanks for this amazing library!

**Comment by ojw28** [comment]
> Hey, I'm preparing to implement this logic external to the player, but I wanted to make sure that this hasn't already been started in one of the dev branches?

We haven't started work on this yet, I'm afraid.

> Assuming not, would the recommended solution effectively come down to a polling handler that inspects delay / updates playback rate on an interval?

An external solution would probably look something like that, yes. Note that you don't really need to poll the delay continuously, since you should be able to assume that for as long as the player is in the "normal" state of playing at 1x speed, the delay will remain constant. It should therefore be possible to listen to events from the player and determine more intelligently when a check is necessary (e.g., if the player transitions into the buffering state and then back into the ready state, then you know that playback will have fallen behind). Whether it's worth the additional complexity is an open question!

**Comment by ojw28** [comment]
I believe this is fully implemented now. @tonihei can provide some details (or links).

**Comment by tonihei** [comment]
Yes, that's fully implemented and enabled by default for low-latency streams. See https://exoplayer.dev/live-streaming.html#customizing-the-playback-speed-adjustment-algorithm for explanations and configuration options.
