### ISSUE TITLE
format.language returns und for unknown locales

### ISSUE THREAD

**Issue by Romadro** [google/ExoPlayer#6153]
### Issue description
`format.language` returns "und" for unknown locales on Sony C6603, but on other devices at the same case `format.language` returns original value from "lang" attribute. 

### Reproduction steps
Parse Dash manifest where `AdaptationSet` tag have "lang" attribute with "hello" value

### Link to test content
I have no public link

### Version of ExoPlayer being used
2.10.1

### Device(s) and version(s) of Android being used
Sony C6603 (android 5.1.1)

**Comment by ojw28** [comment]
@tonihei - IIRC you looked at language tag normalization recently. Could you take a look at this (it sounds OS version or device specific, but we have some Xperia Z devices to test on).

**Comment by tonihei** [comment]
Problem was fixed by the commit above.
