### ISSUE TITLE
can it play videos uploaded on firebase?

### ISSUE THREAD

**Issue by HaiderSaleem** [google/ExoPlayer#6156]
i'm trying to play videos uploaded on firebase, by passing their url to player.

**Comment by marcbaechinger** [comment]
Yes, if you have a url you can stream media from there. 

Check the ExoPlayer developer website, where you can find how to [setup the player](https://exoplayer.dev/hello-world.html) with a `ProgressiveMediaSource`.

**Comment by HaiderSaleem** [comment]
i dont know what was happening before, i might be testing with youtube links.
its working perfectly now with exoplayer 2 imademo, thanks a lot for your time mate. 👍
