### ISSUE TITLE
BufferOverflowException on Nexus 10

### ISSUE THREAD

**Issue by ferrytanu** [google/ExoPlayer#616]
It happens when switching to higher bitrate on Nexus 10 or Samsung device only (so far). The root cause is due to different implementation of the codec, with combination of ExoPlayer code.

# Root Cause
1. It only happens on Samsung devices (so far), or device that use the Exynos chip. Reproducible on Nexus 10.

2. The following line of code may cause putting a data bigger than the ByteBuffer.remaining() that cause the BufferOverflowException: 
https://github.com/google/ExoPlayer/blob/dev/library/src/main/java/com/google/android/exoplayer/extractor/RollingSampleBuffer.java#L284
    ```
int toCopy = Math.min(remaining, allocationLength - positionInAllocation);

// when target.remaining() < toCopy --> BufferOverflowException thrown
target.put(allocation.data, allocation.translateOffset(positionInAllocation), toCopy);
    ```

3. The codec.configure result differently on Qualcom chip vs Exynos. Qualcom will always return the max  capacity when code.getInputBuffers called, as opposed to Exynos return based on the width x height passed via MediaFormat.
https://github.com/google/ExoPlayer/blob/dev/library/src/main/java/com/google/android/exoplayer/MediaCodecTrackRenderer.java#L366
    ```
configureCodec(codec, decoderName, format.getFrameworkMediaFormatV16(), mediaCrypto);
...
inputBuffers = codec.getInputBuffers();
    ```

## Based on my testing:
__Non Samsung device with video codec: OMX.qcom.video.decoder.avc__
* HTC One M8, always returns input buffer with size 7086080
* Nexus 5, always returns input buffer with size 11059200

__Samsung devices with video codec: OMX.Exynos.AVC.Decoder__
* Input buffer size 149760, with MediaFormat:
> {csd-1=java.nio.ByteArrayBuffer[position=0,limit=8,capacity=8], mime=video/avc, max-height=576, com.google.android.videos.pixelWidthHeightRatio=1.0, height=__234__, width=__416__, csd-0=java.nio.ByteArrayBuffer[position=0,limit=36,capacity=36], max-width=1024}

* Input buffer size 497664, with MediaFormat:
> {csd-1=java.nio.ByteArrayBuffer[position=0,limit=8,capacity=8], mime=video/avc, max-height=360, com.google.android.videos.pixelWidthHeightRatio=1.0, height=__432__, width=__768__, csd-0=java.nio.ByteArrayBuffer[position=0,limit=38,capacity=38], max-width=640}

# Solution
Passing the maximum resolution (width and height) that was available on stream list.

https://github.com/google/ExoPlayer/blob/dev/library/src/main/java/com/google/android/exoplayer/MediaFormat.java#L146
```
// remove the final keyword on width and heigh attribute
public void setMaxVideoDimensions(int maxWidth, int maxHeight) {
    this.width = maxWidth;
    this.height = maxHeight;
    this.maxWidth = maxWidth;
    this.maxHeight = maxHeight;
    if (frameworkMediaFormat != null) {
      maybeSetMaxDimensionsV16(frameworkMediaFormat);
    }
  }
```

**Comment by ojw28** [comment]
What media reproduces this problem? Is it reproducible in the demo app at all, and on what builds of Android? Thanks.

**Comment by ferrytanu** [comment]
I'm using dev branch, and didn't test on demo app. However I'm pretty sure we can easily reproduce it on demo app in conditioned env, or by modifying the code.
Tested when playing HLS Live, (never tested on VOD yet though). I'm not sure if the problem may occur on DASH too. Unless we call configureCodec for every Format change, the problem may occur.

The workaround that set the max video resolution the player might play works pretty good so far. Hence, I'm not sure whether it's worth the extra complexity of re-configuring the code for adaptive streaming scenario.

**Comment by ojw28** [comment]
Does setting a larger maxInputSize on the MediaFormat help? That would be a better (and more technically correct) fix.

**Comment by ferrytanu** [comment]
I tried to set the maxInputSize, to random number like ~1Mb on Nexus 10, and it crash the OS. 

However the work around to set the width and height to max, breaks Samsung S3, which has OMX.SEC.avc.dec. It will show garbage when switching bitrate.

So for now, I will only set to max for Exynos codec. 

I'm wondering why we don't use google codec? OMX.google.h264.decoder
What's the different between google codec vs others?

**Comment by ojw28** [comment]
The Google codec runs entirely on the CPU, where-as the vendor provided decoders are typically hardware accelerated (normally meaning better performance and lower battery consumption).

**Comment by johanlindquist** [comment]
We've seen the same issue - any drawbacks if a reconfiguration of the codecs are forced for each bitrate change apart from the apparent "glitch"?

**Comment by ferrytanu** [comment]
We override the configureCodec method on MediaCodecVideoTrackRenderer when codecName is "OMX.Exynos.AVC.Decoder", by setting the format's width and height to the format's max width and max height respectively. It works fine so far.

**Comment by johanlindquist** [comment]
@ferrytanu Sorry, just updated the comment to be clearer - I see the S3 garbage output.

**Comment by ferrytanu** [comment]
I don't have S3 with me right now, does setting the format's width and height to max value solve your problem? (not reconfigure the codecs)

**Comment by johanlindquist** [comment]
@ferrytanu No, with the fixes suggested for the BufferOverflowException in this ticket, the behaviour is worse.  

Without settings the format's heigth/width to max value, the S3 happily switches up in resolution.  However, switching down again will break it (and output is garbage).

**Comment by ferrytanu** [comment]
@johanlindquist ah, what am I thinking? yes, putting max width for S3 will cause garbage output, I have put that in my comment previously.

Basically what I did now is, to keep the S3 alone, as it does not suffer BufferOverflowException. Did you encounter BufferOverflowException on S3?

**Comment by ojw28** [comment]
Tracking with #714
