### ISSUE TITLE
RTMP extension dependency: Dependent libraries not downloaded?

### ISSUE THREAD

**Issue by guodongAndroid** [google/ExoPlayer#6164]
依赖了 implementation 'com.google.android.exoplayer:extension-rtmp:2.9.6'
但是没有自动下载 rtmp的依赖库。
请问如何解决

**Comment by ojw28** [comment]
This should just work (i.e. gradle should be pulling the dependent libraries in automatically). Please could you be more specific about what error you're seeing?

**Comment by guodongAndroid** [comment]
The program can be compiled normally without errors.
The following method solved my problem.
```groovy
implementation('com.google.android.exoplayer:extension-rtmp:2.9.6') {
    exclude group: 'net.butterflytv.utils', module: 'rtmp-client'
}
implementation 'net.butterflytv.utils:rtmp-client:3.0.1'
```

gradle plugin version:
``` groovy
classpath 'com.android.tools.build:gradle:3.4.2'
```

kotlin-gradle-plugin version:
```groovy
classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.31"
```
