### ISSUE TITLE
Skip segment and request next segment when 404 or 410 Exception occurs Exoplayer

### ISSUE THREAD

**Issue by akanksha-hegde** [google/ExoPlayer#6169]
Im trying to run a broadcast stream. But in cast of broadcast, usually in between certain segments may not reach the player. 

Currently I have defined an Error retry policy where in case of an error it will re-request 5 times. But after 5 times if the segment is still not available Player throws 404/410 error and stop.
Instead I want the player to skip that segment and request for next segment. Please do help me out with this use case.

**Comment by akanksha-hegde** [comment]
Can anyone help me out with this/

**Comment by ojw28** [comment]
Is this about HLS or DASH? Please provide complete information. Thanks!

**Comment by akanksha-hegde** [comment]
This will be only DASH stream.

**Comment by ojw28** [comment]
DASH-IF are moving toward disallowing inter-operable content from having gaps. See [here](https://github.com/google/ExoPlayer/issues/4616#issuecomment-509632578) for a bit more detail. So it seems likely that service providers will need to start filling in the gaps on the server-side for their content to be considered inter-operable.

Note that we already handle individual representations having a segment 404 or 410 by switching to a different representation. If all representations 404 or 410 at the same segment then playback will fail. As per the comment above, the direction seems to be toward disallowing gaps.

For HLS we allow segment skipping where segments are marked with the `EXT-X-GAP` tag. I'm not sure if a similar concept for explicit gap signalling exists in DASH. I suspect not (one option would probably be to start a new `Period` when a gap occurs, which probably works). If there is an in-Period way to explicitly signal a gap, we'd be open to supporting that.
