### ISSUE TITLE
Audio Playback seems to give me 1 frame at a time. Is there a way to get more?

### ISSUE THREAD

**Issue by ericatfelix** [google/ExoPlayer#6171]
We are using custom audio processor to decode an mkv with 8 audio tracks. The queueInput method is called with samples. 

Despite the fact that load control is set to:
	loadControlBuilder.setBufferDurationsMs(DefaultLoadControl.DEFAULT_MIN_BUFFER_MS*3,
				DefaultLoadControl.DEFAULT_MAX_BUFFER_MS*3,
				DefaultLoadControl.DEFAULT_BUFFER_FOR_PLAYBACK_MS*3,
			   DefaultLoadControl.DEFAULT_BUFFER_FOR_PLAYBACK_AFTER_REBUFFER_MS*3);

we receive audio frame by frame. Is there a way to change that?

**Comment by ojw28** [comment]
The buffer parameters that you refer to only affect the _total_ size of the buffer, not the granularity of the samples within it. There's no support in the library for changing the latter, sorry.
