### ISSUE TITLE
Using ExoPlayer infra to download a segment of an .mp4 audio file

### ISSUE THREAD

**Issue by brAzzi64** [google/ExoPlayer#6172]
Hi,

I'm trying to see if there's a way to use ExoPlayer infra (extractors / sample sources) to download only a specific segment of an .mp4 audio file from a server, having it hand me over  directly the final decoded samples.

I found this: https://github.com/google/ExoPlayer/issues/2130

And learned there about the "accept-ranges" header, and verified that my CDN returns "accept-ranges: bytes", then tried out passing a request header like "Range: bytes=1024-2047" and it indeed works well.

I've used ExoPlayer before with a custom MediaCodecAudioRenderer to get ahold of the decoded samples to process them and generate a waveform, but I'm trying to figure out if there's a "simpler" way to do this without relying on an actual ExoPlayer instance running.

In noticed BaseRenderer.java uses a "SampleStream" object, and the interface looks like exactly what I'd be looking for:
https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/source/SampleStream.html

Would you guys know of a way to get a SampleStream instance like this, that would query the "right" ranges of the network endpoint for me, as it figures out the .mp4 structure, etc?

Appreciate any tips!

**Comment by ojw28** [comment]
The library is not designed to support this use case, sorry. You could probably figure out a way to do it by adapting the source code, but guidance on this is beyond the scope of this issue tracker.
