### ISSUE TITLE
Real-time preview of video frames, drop the B frame before decode.

### ISSUE THREAD

**Issue by Romantic-LiXuefeng** [google/ExoPlayer#6173]
### [REQUIRED] Question
I want to optimize the seek operation to real-time preview the video frame on the seekbar.
Now in the MetadataQueue, there is a flag(`BUFFER_FLAG_KEY_FRAME`) indicates the video packet is or not KEY_FRAME, I want to know the video packet whether is the B frame.
So I can drop the B frame before decode.

**Comment by ojw28** [comment]
This is not a feature we support, sorry.
