### ISSUE TITLE
Load all Clipping MediaSource parts

### ISSUE THREAD

**Issue by BelousAlex** [google/ExoPlayer#6175]
Good day. I have a URL with mp4 video. I cut it using the ClippingMediaSource, how can I load all the parts at once, so that at any moment of the switch not to wait for buffering?

**Comment by ojw28** [comment]
Sorry for the delay responding to this. I'm not sure I quite follow what you're doing. Are you then adding the `ClippingMediaSource` instances to a `ConcatenatingMediaSource`? If so, the player should start to per-buffer the next item before the current one ends.

Please clarify your use case and provide more concrete information. Thanks!

**Comment by ojw28** [comment]
Closing due to lack of follow up.
