### ISSUE TITLE
Public RFC: Bandwidth estimation analysis

### ISSUE THREAD

**Issue by tonihei** [google/ExoPlayer#6177]
This Request For Comments (RFC) analyzes our current bandwidth estimation method and proposed options to improve it. Please find the [document on Google Drive](https://docs.google.com/document/d/1e3jVkZ6nxNWgCqTNibqV8uJcKo8d597XVl3nJkY7P8c) and leave your comments.

### [REQUIRED] Use case description
ExoPlayer's `DefaultBandwidthMeter` measures network bandwidth using samples obtained from data transfers and also provides the most likely estimate using a [sliding percentile](https://en.wikipedia.org/wiki/Moving_average) approach. This approach has many different kinds of problems, which are analyzed here together with potential mitigation strategies.

**Comment by stevemayhew** [comment]
Thanks @tonihei I vote for publishing the number of samples and the standard deviation of the samples to give a quality of the estimate in the bandwidth estimate API.
