### ISSUE TITLE
[question] Is there such thing as AdaptiveEvaluator for HLS?

### ISSUE THREAD

**Issue by brianchu** [google/ExoPlayer#618]
DASH and SmoothStreaming has AdaptiveEvaluator. How about HLS?

How can we change the adaptive behaviour of Exoplayer HLS?

Thanks!

I did read https://github.com/google/ExoPlayer/issues/388 and realize there are codes to help choosing the right format according to the resolution. However, what happen if we want to, say, pick the lowest bandwidth first?

**Comment by ojw28** [comment]
HlsChunkSource currently implements the equivalent logic directly. We'd like to migrate HLS across to using the same FormatEvaluator interface as DASH and SmoothStreaming at some point, but there's a complication around having to download overlapping segments when switching qualities in HLS, which is not the case for DASH and SmoothStreaming. It's unclear at this stage whether a single interface is suitable for both cases.
