### ISSUE TITLE
Top bit not zero when playing MP4 (STBL/STTS)

### ISSUE THREAD

**Issue by drexel-ue** [google/ExoPlayer#6182]
I have had a similar issue to #3384. I recorded a video on Samsung Galaxy S7 Edge and the video file contains a STTS table with signed integers. The original ticket references CTTS table.

```
E/LoadTask( 6546): Unexpected exception loading stream
E/LoadTask( 6546): java.lang.IllegalStateException: Top bit not zero: -110607978
E/LoadTask( 6546): 	at com.google.android.exoplayer2.util.ParsableByteArray.readUnsignedIntToInt(ParsableByteArray.java:397)
E/LoadTask( 6546): 	at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseStbl(AtomParsers.java:179)
E/LoadTask( 6546): 	at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.getTrackSampleTables(Mp4Extractor.java:457)
E/LoadTask( 6546): 	at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.processMoovAtom(Mp4Extractor.java:398)
E/LoadTask( 6546): 	at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.processAtomEnded(Mp4Extractor.java:360)
E/LoadTask( 6546): 	at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:351)
E/LoadTask( 6546): 	at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:182)
E/LoadTask( 6546): 	at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:898)
E/LoadTask( 6546): 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
E/LoadTask( 6546): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
E/LoadTask( 6546): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
E/LoadTask( 6546): 	at java.lang.Thread.run(Thread.java:764)
```

The line the error occur's on is:
https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/extractor/mp4/AtomParsers.java#L179

Which seems a similar problem to the original issue, please check the comments in the code in this commit.
https://github.com/google/ExoPlayer/commit/298a66fc0e2fd6c9309b8c526418651673bed5eb

### [REQUIRED] Link to test content

https://drive.google.com/file/d/1tsSOksRZ48CNqSVuuZFRY_hCPnJBtNda/view?usp=sharing

### [REQUIRED] Version of ExoPlayer being used

`2.9.6`
As shown here: https://github.com/flutter/plugins/blob/master/packages/video_player/android/build.gradle#L54

### [REQUIRED] Device(s) and version(s) of Android being used

Samsung Galaxy S7 Edge, running Android 8.0

**Comment by ojw28** [comment]
Was the video recorded using the default camera, or something else?

**Comment by ojw28** [comment]
Note that I can't play this video file correctly in VLC or Chrome (I've actually yet to find something that _will_ play it). So I think it's fine to class this as broken media and not worry about fixing it.

**Comment by drexel-ue** [comment]
@ojw28 i apologize for the late response. things have been hecktic.
i will work on recreating the error.
this first started with videos that were confirmed to have played. since the error arose, videos that have been recorded have not been working properly, as you've experienced. 
the issue what was first noticed, though, with videos that were working...

**Comment by lifenautjoe** [comment]
Why was this closed @ojw28 ? Still seeing an issue on my end with mp4 files. They're non playable if they're recorded with the device.

**Comment by ojw28** [comment]
It's explained above why the issue is closed. I.e. The media is broken, and doesn't play correctly in other widely used video players either. The issue also doesn't clearly explain how to reproduce the problem, or how these videos were created, and we were unable to reproduce the problem.

If you're seeing the same or a similar problem, it's probably better if you file a new issue, filling in all of the information requested in the issue template.
