### ISSUE TITLE
Palybackstate does not change to end

### ISSUE THREAD

**Issue by star-andy** [google/ExoPlayer#6184]
hello  
### [REQUIRED] Issue description
Then RK3288 chip board play 3300*1856 resolution video video play normal, but after the end
Palybackstate is still ready。 The same program and video to vivo mobile phone running everything is normal
### [REQUIRED] Reproduction steps
The official demo used, video cannot be uploaded temporarily due to company reasons

### [REQUIRED] Device(s) and version(s) of Android being used
Android  rk3288  SDK 7.1 
exoplayer:2.9.6

**Comment by ojw28** [comment]
The problem can probably be solved by having `MediaCodecRenderer.codecNeedsEosPropagationWorkaround` return true for the video decoder on the affected device. We already have this workaround return true for `OMX.rk.video_decoder.avc`. I'm guessing the version of Rockchip device you're using has a similar issue, but that the decoder has a different name.

Please could you find out what the name of the video decoder is. You should see it in the logs shortly after starting a playback. And please could you also confirm that enabling `codecNeedsEosPropagationWorkaround` for that decoder fixes the issue? Thanks!

**Comment by star-andy** [comment]
@ojw28  Thank you very much for your answer 
I have found the cause of the problem，
https://github.com/google/ExoPlayer/blob/51acd8150c25a2064c3e0c49e04540bd4e2db6f9/library/core/src/main/java/com/google/android/exoplayer2/mediacodec/MediaCodecRenderer.java#L1440
because  outputIndex ==-1  
So I added below the red box code to solve this problem，
But I don't know if this is one of the most appropriate solution.
I will try your solution tomorrow,
see if I can solve this problem
![image](https://user-images.githubusercontent.com/15726024/61216032-fd3daf80-a73e-11e9-9e39-f021249a3539.png)

**Comment by ojw28** [comment]
Making `codecNeedsEosPropagationWorkaround` return true for the the affected decoder will do the same thing, but targeted only at the problematic problematic decoder. It's good to target it because on devices that don't have the underlying issue, processing end of stream in this way is non-ideal vs the way the renderer will handle it by default.

**Comment by star-andy** [comment]
@ojw28  hello  
Today I tried the solution you mentioned yesterday. Debug is shown in the figure below.
```OMX.rk.video_decoder.avc``` The name is the same ,But the SDK is bigger than 17.
I changed to ```Util.SDK_INT <= 25```  it works normally
I would like to ask why ```Util.SDK_INT <= 17``` ?
![image](https://user-images.githubusercontent.com/15726024/61258294-75d85680-a7a7-11e9-87e6-2a3feb7eec46.png)
![image](https://user-images.githubusercontent.com/15726024/61258298-7ffa5500-a7a7-11e9-8d4b-2b12f8f3bb07.png)

**Comment by ojw28** [comment]
> I would like to ask why Util.SDK_INT <= 17

It's preferable to not have this workaround enabled, unless a device really _needs_ it.

We limited to API levels we knew were affected in the hope that the device manufacturer would fix the problem for newer devices. It sounds as though this hasn't happened, and we should increase `17` to `25`. Can you confirm that changing `codecNeedsEosPropagationWorkaround` to the following fixes the issue:

```
private static boolean codecNeedsEosPropagationWorkaround(MediaCodecInfo codecInfo) {
  String name = codecInfo.name;
  return (Util.SDK_INT <= 25
          && "OMX.rk.video_decoder.avc".equals(name))
      || (Util.SDK_INT <= 17
          && "OMX.allwinner.video.decoder.avc".equals(name))
      || ("Amazon".equals(Util.MANUFACTURER) && "AFTS".equals(Util.MODEL) && codecInfo.secure);
}
```

If so, we can go ahead and make that change. Thanks!

**Comment by star-andy** [comment]
@ojw28 
Thank you very much for your help this time
I changed 17 to 25 to solve this problem, and the equipment can work normally
But there is a problem, rk3399 is also SDK 25, but I don't know if this omx.rk.video_decoder.avc has been fixed.
I have no rk3399 device here, so I can't test it. I don't know whether the modification to 25 will have any impact on 3399

**Comment by ojw28** [comment]
We will merge a change that bumps the value to 25. The other device will also get the workaround. That'll be a little sub-optimal in the case that the other device doesn't need it, but it shouldn't cause any huge issues. In absence of being able to test, it's better to fix the broken device and risk the other one having the unnecessary workaround than it is to leave the broken device broken :).

**Comment by star-andy** [comment]
@ojw28 Thank you very much for your answers these days
