### ISSUE TITLE
Cannot play some rtmp streams

### ISSUE THREAD

**Issue by kaiv2000** [google/ExoPlayer#6187]
Exoplayer v.2.10.3 still cannot open next rtmp streams:

rtmp://ms.mix.net.ua:1935/live/camera130.stream
rtmp://ms.mix.net.ua:1935/live/camera171.stream
rtmp://ms.mix.net.ua:1935/live/camera172.stream

I try to open them using next code:

```
RtmpDataSourceFactory rtmpDataSourceFactory = new RtmpDataSourceFactory();
MediaSource mediaSource = new ExtractorMediaSource.Factory(rtmpDataSourceFactory).createMediaSource(url);
```

Tested on Android 9, Galaxy S9 device.

**Comment by vavadhani** [comment]
Duplicate of #4319 

Fix is in progress in librtmp-client.

**Comment by ojw28** [comment]
Closing as duplicate. Thanks @vavadhani .
