### ISSUE TITLE
Apple Low-Latency HLS support

### ISSUE THREAD

**Issue by kevleyski** [google/ExoPlayer#6188]
I’m researching for a presentation on low-latency streaming media solutions 
https://tinyurl.com/yyr2rz8m
What I’m trying to find out is whether ExoPlayer is actively working on changes to support partial segments tags and media playlist deltas
Or maybe focus is more towards the standard CMAF DASH mediaRange model
Or maybe neither

**Comment by tonihei** [comment]
Yes, we are actively working on it. Efforts are tracked by #4904 for DASH and #5011 for HLS.

**Comment by kevleyski** [comment]
Ah that’s great, thanks @tonihei
