### ISSUE TITLE
How to solve music catton problem when underruns appear in playing audio

### ISSUE THREAD

**Issue by Programmer-Jared** [google/ExoPlayer#6193]
When I used exoplayer to play url, in m4a format, on a low-end device, and when other applications were using too much CPU, underrun appeared on my app player. How do I avoid underun? I tried to enlarge the buffer size, but I felt that this was not the root of the problem. I hope you can help me as soon as possible. thank you Otherwise, I would abandon exoplayer and use Mediaplayer. Very urgent. Please help me.

**Comment by AquilesCanta** [comment]
Could you please provide:
- Sample content that reproduces the issue.
- A bugreport captured shortly after reproducing the issue.
- A precise description of the steps you take to reproduce the issue.

Thanks!
