### ISSUE TITLE
Keep connect a livestream video for a specific time

### ISSUE THREAD

**Issue by namnh-0652** [google/ExoPlayer#6194]
Hi, my context is that when a `livestreamer` is streaming, he has network problem (or any reason) so the streaming is disconnected for a minute, after that he can continue streaming normally with the same url. From another side, a viewer is viewing normally, however because the streaming has broken for a while the video is ending, how to keep a viewer continue listening that livestream video with exo? so that, he can play the video without ending the streaming. (I can limit the time for viewer that he can continue viewing the streaming).

**Comment by AquilesCanta** [comment]
> the video is ending

So the player transitions to ended state? If that's the case it may be worth visiting the possibility of fixing it on the server side, to avoid reaching the end of input.

Client-side, if you are reaching the end of input, you can re-prepare the player.

If this doesn't help, please clarify the question, and I will re-open the issue.

**Comment by namnh-0652** [comment]
> So the player transitions to ended state?

Yes, it does. But, could you clarify me whenever the player is going to ended state? how does it know the stream is ended?

> If that's the case it may be worth visiting the possibility of fixing it on the server side, to avoid reaching the end of input

I will consider about this.

**Comment by AquilesCanta** [comment]
> Yes, it does. But, could you clarify me whenever the player is going to ended state? how does it know the stream is ended?

Depends on the type of media. I am assuming you are using a progressive file (for example, Transport Stream, MP4, etc). If you are indeed using a progressive stream, the player transitions to ended state when the end of input is reached. If you are using a different type of streaming (for example, HLS or DASH) then it depends on the published playlist, but the same suggested approach applies (repreparing).

If there is anything you are not sure about, please include more precise information about your issue. The [issue template](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/content_not_playing.md) is a good guidance of what we need.
