### ISSUE TITLE
Add a Scheduler that uses WorkManager for

### ISSUE THREAD

**Issue by noamtamim** [google/ExoPlayer#6195]
### [REQUIRED] Use case description
For downloading media you provide two implementations of the Scheduler interface, one that uses JobScheduler from API 21 and another that uses Firebase (which requires Google Play Services). 
Both options are not ideal - we support API 17, and we're reluctant to add a dependency on something like Firebase (and Play Services).

### Proposed solution
[WorkManager](https://developer.android.com/topic/libraries/architecture/workmanager/) from JetPack seems to solve the same problem, but in a backwards compatible way.

**Comment by ojw28** [comment]
See https://github.com/google/ExoPlayer/tree/dev-v2/extensions/workmanager, which will be included in a future release.

**Comment by noamtamim** [comment]
Thanks @ojw28. In its current state (https://github.com/google/ExoPlayer/blob/dev-v2/extensions/workmanager/src/main/java/com/google/android/exoplayer2/ext/workmanager/WorkManagerScheduler.java), is this class ready for testing? 

In other words, can I copy it directly into my library and use it when JobScheduler is not available? QA is on me, of course :-).

**Comment by ojw28** [comment]
It's complete and no further changes are planned.

**Comment by noamtamim** [comment]
Ok, one last question on this topic: since WorkManager uses JobScheduler when it's available, and it adds features on top of that, would you recommend using WorkManagerScheduler anyway (even on API 21+)?

**Comment by ojw28** [comment]
Yeah, I think so!

**Comment by noamtamim** [comment]
@ojw28 Please consider using `WorkManagerScheduler` in the demo app. Then it will be clear how to use it (in particular, the `workName` parameter to the constructor).
