### ISSUE TITLE
TransportControls.skipToQueueItem not working after shuffle

### ISSUE THREAD

**Issue by jakoss** [google/ExoPlayer#6196]
### Issue description
I have issue when using `MediaSession` to set shuffle and then trying to navigate through new queue. `TransportControls.skipToQueueItem` seems to be translated to wrong windows index.

### Reproduction steps
First - i create playlist using `ConcatenatingMediaSource`. Using `MediaControllerCompat.Callback` i'm updating tracks queue in view like that:
```kotlin
override fun onQueueChanged(queue: MutableList<MediaSessionCompat.QueueItem>?) {
            queue?.let {
                val tracks = it.map {track ->
                    track.description.extras?.getParcelable("track") as Track?
                        ?: throw Exception("Track not found in extras")
                }
                playlistChange.postValue(Playlist(tracks))
            }
        }
```
Now, when user wants to shuffle i call `mediaController.transportControls.setShuffleMode(PlaybackStateCompat.SHUFFLE_MODE_ALL)`. My queue gets updated. When i do `Previous` and `Next` actions in `TransportControls` it all works fine. But i want to handle click from user on track list. So i do something like this:
```kotlin
// id is unique track identifier that i store in view and in mediaId field
val position = mediaController.queue.indexOfFirst { it.description.mediaId?.toInt() == id }
mediaController.transportControls.skipToQueueItem(position.toLong())
```
And this code seems to be broken. It jumps through queue like it wasn't shuffled at all. Do i do something wrong or `MediaSession` implementation doesn't take this into account?

### Version of ExoPlayer being used
2.10.3

### Device(s) and version(s) of Android being used
All tested devices (Samsung Galaxy S7 Edge, Nokia 8, Xiomi Mi 5a) and emulators (android versions 6 to 9)

**Comment by jakoss** [comment]
Code:
```kotlin
val queueId = mediaController.queue.find { it.description.mediaId?.toInt() == id }?.queueId
queueId?.let {
    mediaController.transportControls.skipToQueueItem(it)
 }
```
Seems to be working fine. Is it right behavior?

**Comment by AquilesCanta** [comment]
@marcbaechinger, could you please take a look?

**Comment by chvp** [comment]
(Disclaimer: not affiliated with this project.)

As far as I know, you need to pass the item's `queueId` instead if the item's position. So your code should be something like:
```kotlin
val queueId = mediaController.queue.find { it.description.mediaId?.toInt() == id }?.queueId
mediaController.transportControls.skipToQueueItem(queueId)
```

**Comment by marcbaechinger** [comment]
@charvp That's perfectly right. Thanks! :)

@Nekromancer 
The solution with the queueId is the right way to go. When using shuffle mode the position of the item in the data structure remains the same. So you need to use the queueId instead.

**Comment by jakoss** [comment]
Ok, thanks
