### ISSUE TITLE
How to show the default audio track checkedtextview selected

### ISSUE THREAD

**Issue by Sathish-Kumar-Kanagaraj** [google/ExoPlayer#6199]
I am using exoplayer and hls url
I want to show the audio popup with the default audio with checked tick mark
How can i get the DEFAULT key value yes in the hls url that audio to be checked
How to do it?

**Comment by AquilesCanta** [comment]
See [Format.selectionFlags](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/Format.html#selectionFlags): one of the possible flags is [C.SELECTION_FLAG_DEFAULT](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/C.html#SELECTION_FLAG_DEFAULT).

**Comment by Sathish-Kumar-Kanagaraj** [comment]
Thanks for the reply .
I am getting 5 as selection flag for the default audio track
Is it correct whether default audio track int= 5 ?

**Comment by AquilesCanta** [comment]
Don't rely on the values. Check whether the flag is set, like so:

`boolean isDefault = (format.selectionFlags & C.SELECTION_FLAG_DEFAULT) != 0;`

**Comment by Sathish-Kumar-Kanagaraj** [comment]
Thank u so much .boolean worked fine

**Comment by Sathish-Kumar-Kanagaraj** [comment]
I am facing another one issue with this multiple audios.
I am getting surround and streo both the type of audio with same category language in the hls url.
How can i change it to single language streaming and based on adaptive bit rate making it choose stereo or surround internally
Kindly provide me with a solution.

Sample Link:https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8
