### ISSUE TITLE
Support for AC3/EAC3 in HLS

### ISSUE THREAD

**Issue by Srinidhikandi** [google/ExoPlayer#620]
Hi,

Currently i notice that there is no audio heard  for AC3/EAC3 codecs in HLS.

Is it  supported? If no, is there a plan to support.?

Thanks in Advance

**Comment by andrewlewis** [comment]
Android L supports passthrough of encoded audio over HDMI to an A/V receiver that can decode the format. ExoPlayer supports this feature, but for HLS we only read AC-3 as per the ATSC A/52 specification, not DVB.

So AC-3 playback will only work if the device can output encoded data to an A/V receiver over HDMI, and for HLS the stream must be using the ATSC stream type.

For the relatively few devices that do include AC-3 decoders, we plan to add support for on-device decoding at some point.
