### ISSUE TITLE
How does downloading and playback at the same time work?

### ISSUE THREAD

**Issue by chvp** [google/ExoPlayer#6204]
### [REQUIRED] Searched documentation and issues
https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/DefaultLoadControl.html  
https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/upstream/cache/SimpleCache.html  
https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/upstream/PriorityDataSource.html  
https://exoplayer.dev/downloading-media.html  

### [REQUIRED] Question
I'm making a music app that loads audio files from the network. I would like to immediately download all tracks in the playlist to a (file-based) cache sequentially when the user starts playing music (or, if possible, a set amount of tracks). To accomplish this behaviour right now, I added a custom LoadControl to my SimpleExoPlayer where the `minBufferMs` and `maxBufferMs` properties are set to `MAX_INT`. This works but doesn't really feel right, as I'm assuming that Exoplayer will add the tracks to both the file cache and its internal memory cache. So I would like to do something similar to the DownloadService, where I preload all the files to the (file-based) cache instead of  also loading them to Exoplayer's memory cache. My `DataSource` is a `CacheDataSource` that wraps a `HttpDataSource`. I looked at wrapping the `HttpDataSource` in a `PriorityDataSource` but I couldn't figure out from the documentation how to use it (or if it is even something that can be used for this).

**Comment by AquilesCanta** [comment]
@erdemguven, can you take a look?

**Comment by tonihei** [comment]
You can use the same underlying cache for downloading and playback at the same time. So the best solution is to start the download to the cache and then start playback using the same cache in `CacheDataSource`. Have you tried that?

**Comment by chvp** [comment]
I've tried that, but the Player and the DownloadService are in contention about who gets to write to the cache. Somehow the cache is also losing the cache information if I do this, because if I use `CacheUtil` to check the cached length for a file that returned that it was fully cached, after a while it reverts to 0 bytes downloaded and unknown content length.

**Comment by tonihei** [comment]
The cache used for playback needs to be read-only for this case, so that they don't both try to write to the same cache. See #5867 for the same question.

I noted that our documentation doesn't mention how downloading and playback at the same time works. So marking as a documentation candidate to improve that.

**Comment by chvp** [comment]
I did try to make the playback cache read-only, but this still made both playback and caching download the same stream. It also didn't solve the issue where the cache entries seemingly disappeared.

**Comment by tonihei** [comment]
What type of `MediaSource` are you using? I need to try again myself to see how this works to figure out what may be wrong here. 

> cache entries seemingly disappeared.

Are you using the `NoOpCacheEvictor` to ensure cache entries are not deleted?

**Comment by chvp** [comment]
I'm using `ProgressiveMediaSource`'s. Might be important that for technical reasons I can't serve byte ranges on the server side.

Even if I use the `NoOpCacheEvictor` the entries dissappear as well.

**Comment by tonihei** [comment]
> Might be important that for technical reasons I can't serve byte ranges on the server side.

That sounds not ideal in general, but in theory should be fine for caching purposes. 

> I need to try again myself to see how this works to figure out what may be wrong here.

It took me a while to figure out how that actually works. The solution is to set the `CacheDataSource.FLAG_BLOCK_ON_CACHE` in the read-only playback data source. This ensures we don't attempt to load the data again but rather wait until we can read it from the downloaded cache. Note that this also means playback start needs to wait until the download has written its first file to the cache, so you may want to decrease the cache fragmentation size to allow faster startup.
