### ISSUE TITLE
我在播放本地视频的时候出现了错误

### ISSUE THREAD

**Issue by NiuXiaoGuang** [google/ExoPlayer#6207]
![image](https://user-images.githubusercontent.com/30843465/61583334-696a4a00-ab69-11e9-9ec6-c03b898ff1b4.png)
shi'p
视频的时长都能获取到

**Comment by ojw28** [comment]
Please provide all of the information requested in the [issue template](https://github.com/google/ExoPlayer/issues/new?assignees=&labels=bug%2C+needs+triage&template=bug.md&title=). Closing this for now. Please reply here if you're able to provide complete information, and we'll re-open the issue.
