### ISSUE TITLE
TS file streamed over DVB-T broadcaster

### ISSUE THREAD

**Issue by ashwinprasadmr** [google/ExoPlayer#6209]
### [REQUIRED] Content description
Currently i am trying to use the Exoplayer in my application where i need to display the video data which is fetched from a DVB-T tuner(dongle). The video is streamed from a DVB-T broadcaster and the application uses a dongle and fetches the video data via the USB interfaces and dumps the data into a local bytebuffer queue. The queue data is sent across to the Exoplayer via a local NanoHTTP implementation. The video (ts) file plays without any issues if i directly play the file either locally or through a local apache server. However if the video data is fetched via the DVB-T dongle route the video does not play and gives **UnrecognizedInputFormatException** error.

### [REQUIRED] Link to test content
[File Link](https://drive.google.com/file/d/1cVKDQjxMeCSuQumeAj8lt9MdCd6oFDgs/view?usp=sharing)

### [REQUIRED] Version of ExoPlayer being used
Version 2.9.3
It is tested on the demo application as well my application.

### [REQUIRED] Device(s) and version(s) of Android being used
Moto G6 - Android 8.0

### [REQUIRED] A full bug report captured from the device
```
2019-07-23 11:17:37.750 10742-10820 E/ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor, AmrExtractor) could read the stream.
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractorHolder.selectExtractor(ExtractorMediaPeriod.java:973)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:891)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)

```

**Comment by ojw28** [comment]
If it works when played as a file but throws the error above when played via your NanoHTTP path, then the only possibility is that different data is being fed into the player in each case (i.e. incorrect data in the case of the NanoHTTP path). That's an issue with your application code, which you'll need to debug on your side.

As an aside, it's quite inefficient to setup a local HTTP server for this. You should be able to implement a custom `DataSource` to allow ExoPlayer to read the incoming data directly, and remove the layer of indirection. I'd probably suggest you get your existing approach working first, and then look at removing the indirection after that.
