### ISSUE TITLE
Pre Buffering entire video

### ISSUE THREAD

**Issue by PranjalDesai** [google/ExoPlayer#6212]
Hello,

I was wondering if there was any way to buffer the entire video before playing it. I dont want to download the video but want it to be buffered from a url.

Thanks in advance 🙏🙏🙏

**Comment by umangsaini** [comment]
You may customize parameters of Allocator used by LoadControl to set a larger buffer ([Link](https://exoplayer.dev/customization.html)). 

When setPlayWhenReady() is not set for playback to start, you may start playback after waiting for getContentBufferedPosition() to be same as total duration.
