### ISSUE TITLE
How to implement object detection plugin module

### ISSUE THREAD

**Issue by WeiChungChang** [google/ExoPlayer#6218]
### [REQUIRED] Searched documentation and issues
Find NONE in current issue list.

### [REQUIRED] Question
If I want to implement object detection; where can I start from?

I have checked the issue list and find nothing about this topic.

For my purpose, there are two ways to get it.
1. apply deep learning - is there any document about how to connect EXOPlayer with Android Neural Networks API (NNAPI)?  or how to plugin EXOPplayer with extra module of Object detection?
How about if my implementation does NOT need NN HW accelerator for now (if so, is Android Neural Networks API (NNAPI) still in need )?

2.  apply traditional (non-deep learning) algorithm:
Is there any document to describe how to capture the decoded video frame & apply a customized filter (for my case, a image processing filter pipeline is inserted between decoder & renderer).

Thanks

**Comment by jakoss** [comment]
I'm not sure why are you trying to connect deep learning with media player. It's purpose is to play video/audio. I think you should be looking at decoding media yourself. Using, for example, [MediaCodec](https://developer.android.com/reference/android/media/MediaCodec.html)

**Comment by erdemguven** [comment]
We don't support object detection. For getting the frame bitmap you check these issues: #5076, #5519
