### ISSUE TITLE
java.net.SocketTimeoutException

### ISSUE THREAD

**Issue by CNXiDaDa** [google/ExoPlayer#6219]
when I play dash files,sometimes the exoplayer case error k=like "java.net.SocketTimeoutException",how do i resolve this problem,thank you,the log like this:
07-24 00:19:31.216 E/EventLogger(32179): com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: java.net.SocketTimeoutException
07-24 00:19:31.216 E/EventLogger(32179): 	at com.google.android.exoplayer2.ext.okhttp.OkHttpDataSource.read(OkHttpDataSource.java:214)
07-24 00:19:31.216 E/EventLogger(32179): 	at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFromDataSource(DefaultExtractorInput.java:257)
07-24 00:19:31.216 E/EventLogger(32179): 	at com.google.android.exoplayer2.extractor.DefaultExtractorInput.read(DefaultExtractorInput.java:59)
07-24 00:19:31.216 E/EventLogger(32179): 	at com.google.android.exoplayer2.extractor.DefaultTrackOutput.sampleData(DefaultTrackOutput.java:484)
07-24 00:19:31.216 E/EventLogger(32179): 	at com.google.android.exoplayer2.source.chunk.ChunkExtractorWrapper$BindingTrackOutput.sampleData(ChunkExtractorWrapper.java:179)
07-24 00:19:31.216 E/EventLogger(32179): 	at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.readSample(FragmentedMp4Extractor.java:1111)
07-24 00:19:31.216 E/EventLogger(32179): 	at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:260)
07-24 00:19:31.216 E/EventLogger(32179): 	at com.google.android.exoplayer2.source.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:112)
07-24 00:19:31.216 E/EventLogger(32179): 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
07-24 00:19:31.216 E/EventLogger(32179): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
07-24 00:19:31.216 E/EventLogger(32179): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
07-24 00:19:31.216 E/EventLogger(32179): 	at java.lang.Thread.run(Thread.java:818)
07-24 00:19:31.216 E/EventLogger(32179): Caused by: java.net.SocketTimeoutException
07-24 00:19:31.216 E/EventLogger(32179): 	at java.net.PlainSocketImpl.read(PlainSocketImpl.java:484)
07-24 00:19:31.216 E/EventLogger(32179): 	at java.net.PlainSocketImpl.-wrap0(PlainSocketImpl.java)
07-24 00:19:31.216 E/EventLogger(32179): 	at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
07-24 00:19:31.216 E/EventLogger(32179): 	at okio.Okio$2.read(Okio.java:140)
07-24 00:19:31.216 E/EventLogger(32179): 	at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
07-24 00:19:31.216 E/EventLogger(32179): 	at okio.RealBufferedSource.read(RealBufferedSource.java:47)
07-24 00:19:31.216 E/EventLogger(32179): 	at okhttp3.internal.http1.Http1Codec$AbstractSource.read(Http1Codec.java:363)
07-24 00:19:31.216 E/EventLogger(32179): 	at okhttp3.internal.http1.Http1Codec$FixedLengthSource.read(Http1Codec.java:407)
07-24 00:19:31.216 E/EventLogger(32179): 	at okio.RealBufferedSource$1.read(RealBufferedSource.java:440)
07-24 00:19:31.216 E/EventLogger(32179): 	at com.google.android.exoplayer2.ext.okhttp.OkHttpDataSource.readInternal(OkHttpDataSource.java:366)
07-24 00:19:31.216 E/EventLogger(32179): 	at com.google.android.exoplayer2.ext.okhttp.OkHttpDataSource.read(OkHttpDataSource.java:212)
07-24 00:19:31.216 E/EventLogger(32179): 	... 11 more

**Comment by erdemguven** [comment]
SocketTimeoutException happens when the server doesn't return data in a certain time. You need better connection with the server.
