### ISSUE TITLE
Bufferlength and Buffertime in RTMP Stream

### ISSUE THREAD

**Issue by Schizo** [google/ExoPlayer#622]
JWPlayer has the following options to reduce latency in RTMP Streamings:

bufferLength: 0,
bufferTime: 0,

Are those parameters parametrized in Exoplayer and can they be set? This seems to be a client-side argument, the NGINX documentation says, that the client sends the "set_buflen" request.

**Comment by ojw28** [comment]
ExoPlayer doesn't support RTMP.
