### ISSUE TITLE
play mpd file from sdcard exoplayer

### ISSUE THREAD

**Issue by azhar5678** [google/ExoPlayer#6220]
MP4Box -dash 4000 -frag 4000 -rap -segment-name segment_
 f:/vkkk.mp4 -out d:/dashvedio/mm.mpd

how to play .mpd file created above from sdcard android exoplayer
 i want to know complete process of creating mpd file which exoplayer understand.
demuxed , muxed, what to follow.

**Comment by ojw28** [comment]
ExoPlayer supports playing DASH content stored on the SD card. It's not the purpose of this issue tracker to provide detailed advice on creating content. You can read what styles of DASH ExoPlayer supports [here](https://exoplayer.dev/supported-formats.html#dash).

**Comment by azhar5678** [comment]
I solved it
