### ISSUE TITLE
Puase button not showing with 'androidx.constraintlayout:constraintlayout:2.0.0-beta2'

### ISSUE THREAD

**Issue by fichna** [google/ExoPlayer#6221]
When I updated ConstraintLayout to new beta (I know, it is beta...) the exo_pause button isn't showing anymore when playing.
So if you are searching where is the bug - it is your 'androidx.constraintlayout:constraintlayout:2.0.0-beta2'.

**Comment by ojw28** [comment]
There isn't anything we can do without more complete information (e.g. you could provide a small demo app as source code, which reproduces the problem). Closing for now. Please also note that we have an [issue template](https://github.com/google/ExoPlayer/issues/new?assignees=&labels=bug%2C+needs+triage&template=bug.md&title=).
