### ISSUE TITLE
exo_ad_overlay must be present for ad playback exoplaer

### ISSUE THREAD

**Issue by DasJhaman** [google/ExoPlayer#6223]
Hell every one, previously i was using **2.9.4** version of exoplayer, after updating exoplayer dependencies to **2.10.3** i am getting this erro while playing ads on player.

Following is my code.
    
      `adsLoader = new ImaAdsLoader(this, Uri.parse(advertisementEntity.getAdvertisementVastURL()));
        adsLoader.setPlayer(player);
        playerView.setPlayer(player);

        MediaSource adsMediaSource =
                new AdsMediaSource(mediaSource,/* adMediaSourceFactory= */this, adsLoader, playerView);

        player.seekTo(startWindow);
        player.prepare(adsMediaSource);
        player.setPlayWhenReady(true);`

Following is logcat.
` java.lang.NullPointerException: exo_ad_overlay must be present for ad playback
        at com.google.android.exoplayer2.util.Assertions.checkNotNull(Assertions.java:130)
        at com.google.android.exoplayer2.ui.PlayerView.getAdViewGroup(PlayerView.java:1137)
        at com.google.android.exoplayer2.ext.ima.ImaAdsLoader.start(ImaAdsLoader.java:595)
        at com.google.android.exoplayer2.source.ads.AdsMediaSource.lambda$prepareSourceInternal$0(AdsMediaSource.java:220)
        at com.google.android.exoplayer2.source.ads.-$$Lambda$AdsMediaSource$zcXBZahV9F-k_KJACPO-bl_WWX0.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:192)
        at android.app.ActivityThread.main(ActivityThread.java:6806)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:445)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:867)`

Please help me out whats going wrong.

**Comment by andrewlewis** [comment]
Have you customized the player view in a way that removes `exo_ad_overlay`? The code is passing the `playerView` as an `AdViewProvider` when creating the `AdsMediaSource`, and when doing that there needs to be a frame layout with id `exo_ad_overlay` in the player view (like in the default `PlayerView` layout).

Alternatively you can pass a custom implementation of `AdsLoader.AdViewProvider` when creating the `AdsMediaSource`.

**Comment by DasJhaman** [comment]
yea i have customized my player view. Could you please let me know how can i fix this issue.

**Comment by andrewlewis** [comment]
One way is to add

```
  <FrameLayout android:id="@id/exo_ad_overlay"
    android:layout_width="match_parent"
    android:layout_height="match_parent"/>
```

... on top of the main player view in your custom layout.

**Comment by DasJhaman** [comment]
I have set the id on Framelayout still same exception. 

Following is my xml layout.

`<?xml version="1.0" encoding="UTF-8"?>
      <androidx.coordinatorlayout.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/root"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fitsSystemWindows="true"
    android:keepScreenOn="true"
>


    <FrameLayout
        android:id="@id/exo_ad_overlay"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="horizontal">


        <com.google.android.exoplayer2.ui.PlayerView
            android:id="@+id/player_view"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:controller_layout_id="@layout/exoplayer_controllers_channels"
            app:show_buffering="always" />


        <RelativeLayout
            android:id="@+id/relativeLayout_chat"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:visibility="gone">

            <androidx.recyclerview.widget.RecyclerView
                android:id="@+id/recycler_view_chat"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:stackFromBottom="true"
                android:layout_above="@id/view_chat">

            </androidx.recyclerview.widget.RecyclerView>

            <ImageView
                android:id="@+id/btn_close"
                android:layout_width="24dp"
                android:layout_height="24dp"
                android:tint="@color/white"
                android:layout_alignParentRight="true"
                android:src="@drawable/cancel_new" />

            <View
                android:id="@+id/view_chat"
                android:layout_width="match_parent"
                android:layout_height="1dp"
                android:layout_above="@+id/linearLayout_send"
                android:background="@color/white"></View>

            <LinearLayout
                android:id="@+id/linearLayout_send"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_alignParentBottom="true"
                android:layout_gravity="bottom"
                android:background="@drawable/item_chat_bg"

                android:orientation="horizontal"
                android:weightSum="1">

                <EditText
                    android:id="@+id/editTextMessage"
                    android:layout_width="0dp"
                    android:layout_height="match_parent"
                    android:layout_weight=".8"
                    android:imeOptions="flagNoFullscreen"
                    android:textColor="@color/white" />

                <View
                    android:layout_width="1dp"
                    android:layout_height="48dp"
                    android:background="@color/white">

                </View>


                <Button
                    android:id="@+id/btnSend"
                    android:layout_width="0dp"
                    android:layout_height="match_parent"
                    android:layout_weight=".2"
                    android:background="@drawable/item_chat_bg"
                    android:text="send"
                    android:textColor="@color/white" />
            </LinearLayout>
        </RelativeLayout>


        <LinearLayout
            android:id="@+id/controls_root"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="horizontal"
            android:visibility="gone" />


    </FrameLayout>

    <include
        android:id="@+id/ad_player_container"
        layout="@layout/ad_banner"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="bottom|center_horizontal"
        android:visibility="gone" />

</androidx.coordinatorlayout.widget.CoordinatorLayout>
`

**Comment by andrewlewis** [comment]
I think you might need to add the `FrameLayout` in `exoplayer_controllers_channels.xml`.

**Comment by andrewlewis** [comment]
The `exo_ad_overlay` should be an empty `FrameLayout`.

Please take a look at how the default layout works in the ui module. I wonder if you have a layout called `exo_simple_player_view.xml` already in your project that's overriding the default one.

**Comment by DasJhaman** [comment]
Hello following code is not present in `exo_simple_player_view.xml`

` <FrameLayout
        android:id="@id/exo_ad_overlay"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />`

By putting this one, issue was fixed.
