### ISSUE TITLE
Stuttering audio with url from a specific site

### ISSUE THREAD

**Issue by mzonov** [google/ExoPlayer#6227]
So, my app plays radio stations from the Internet. And all is fine except of playing radio stations from 101.ru. Music is stuttering and I can't say that there are any equal time intervals between stutters.
I'm using ExoPlayer library v2.8.0.

**What have I tried to fix it:**

- To update ExoPlayer to 2.10.3 - no result 
- To experiment with the buffer size of Exoplayer - no result or worst (few hours of experiments)

**My code of ExoPlayer init:**

    IcyHttpDataSourceFactory factory = new IcyHttpDataSourceFactory.Builder(Util.getUserAgent(context, userAgent))
                .setIcyHeadersListener(this)
                .setIcyMetadataChangeListener(this).build();
    dataSourceFactory = new DefaultDataSourceFactory(context, null, factory);

    RenderersFactory renderersFactory = new DefaultRenderersFactory(context);
    TrackSelection.Factory trackSelectionFactory = new AdaptiveTrackSelection.Factory(new DefaultBandwidthMeter());
    DefaultTrackSelector trackSelector = new DefaultTrackSelector(trackSelectionFactory);
    LoadControl loadControl = new DefaultLoadControl();

    player = ExoPlayerFactory.newSimpleInstance(renderersFactory, trackSelector, loadControl);
    player.addListener(this);

**My code of ExoPlayer play from url:**

    player.prepare(generateMediaSource(Uri.parse(url)));

    private MediaSource generateMediaSource(Uri uri) {
        return new ExtractorMediaSource.Factory(dataSourceFactory)
                .setExtractorsFactory(new DefaultExtractorsFactory())
                .createMediaSource(uri);
    }

So, 101.ru has about 80 radio stations and about 90% of them are stuttering. However, other 100-200 radio stations from another sources have an excellent quality.
What can I do to fix it? Thanks

**Comment by ojw28** [comment]
I tried playing a 101.ru radio stream in the regular ExoPlayer demo app and I do not see this problem. I think it's quite likely that the problem is caused by `IcyHttpDataSource`, which is not a component we provide or support.

Note that there's no reason to use `IcyHttpDataSource` when using ExoPlayer 2.10.3, since we now [provide direct ICY support](https://medium.com/google-exoplayer/exoplayer-2-10-whats-new-15d344eaa8b9).

**Comment by ojw28** [comment]
Marking as an app issue for now.

**Comment by mzonov** [comment]
Yes, you're right. I've removed `IcyHttpDataSource` and it works without any stuttering.
