### ISSUE TITLE
Video fails while loading and throws Loader$UnexpectedLoaderException

### ISSUE THREAD

**Issue by naseeb8950925214** [google/ExoPlayer#6228]
### [REQUIRED] Issue description
When we try to play video in loop, sometimes we face this issue where video playback fails and throws **com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected IllegalArgumentException**

### [REQUIRED] Reproduction steps
Just add one video and play it in loop for few hours say 3-4 hours. This issue can occur randomly any time.

### [REQUIRED] Link to test content
Please find the link below:
https://drive.google.com/file/d/1-3LcpETTELeo6oqU-7LPB54tHJ_eRqHk/view?usp=sharing

### [REQUIRED] A full bug report captured from the device
    VideoPlayerFragment - [2019-07-21 11:17:36.129] updateVideo --->VideoPlayerFragment{25d2898 #0 id=0x32 com.panasonic.android_app.fragments.VideoPlayerFragment}
	Line 2305: 2019.07.21 11:11:45.181 DEBUG [main] com.panasonic.android_app.fragments.VideoPlayerFragment - [2019-07-21 11:17:36.140] PlayerEventListener onPlayerStateChanged playWhenReady : true playbackState : 1 VideoPlayerFragment{25d2898 #0 id=0x32 com.panasonic.android_app.fragments.VideoPlayerFragment}
	Line 2305: 2019.07.21 11:11:45.181 DEBUG [main] com.panasonic.android_app.fragments.VideoPlayerFragment - [2019-07-21 11:17:36.140] PlayerEventListener onPlayerStateChanged playWhenReady : true playbackState : 1 VideoPlayerFragment{25d2898 #0 id=0x32 com.panasonic.android_app.fragments.VideoPlayerFragment}
	Line 2305: 2019.07.21 11:11:45.181 DEBUG [main] VideoFragment - [2019-07-21 11:17:36.140] PlayerEventListener onPlayerStateChanged playWhenReady : true playbackState : 1 VideoPlayerFragment{25d2898 #0 id=0x32 VideoFragment}
	Line 2308: 2019.07.21 11:11:45.192 DEBUG [main] VideoFragment - [2019-07-21 11:17:36.151] startPlayer uri from filePath : /storage/emulated/0/Android/data/video/files/Download/63.mp4
	Line 2313: 2019.07.21 11:11:45.205 DEBUG [main] VideoFragment - [2019-07-21 11:17:36.164] logContentPlayBackModel
	Line 2323: 2019.07.21 11:11:45.234 DEBUG [main] VideoFragment - [2019-07-21 11:17:36.194] startPlayer displayMode : STRETCH-TO-FIT
	Line 2326: 2019.07.21 11:11:45.296 DEBUG [main] VideoFragment - [2019-07-21 11:17:36.255] initializeExoPlayer Video
	Line 2329: 2019.07.21 11:11:45.325 DEBUG [main] VideoFragment - [2019-07-21 11:17:36.284] initializeExoPlayer Video same video player is being used mPlayer :com.google.android.exoplayer2.SimpleExoPlayer@7a3e09f
	Line 2331: 2019.07.21 11:11:45.337 DEBUG [main] VideoFragment - [2019-07-21 11:17:36.293] playVideoByExoplayer uri : storage/emulated/0/files/Download/63.mp4
	Line 2333: 2019.07.21 11:11:45.352 DEBUG [main] VideoFragment - [2019-07-21 11:17:36.311] muteUnMuteExoplayer VideoPlayerFragment{25d2898 #0 id=0x32 VideoFragment} isMute :true
	Line 2333: 2019.07.21 11:11:45.352 DEBUG [main] VideoFragment - [2019-07-21 11:17:36.311] muteUnMuteExoplayer VideoPlayerFragment{25d2898 #0 id=0x32 VideoFragment} isMute :true
	Line 2333: 2019.07.21 11:11:45.352 DEBUG [main] VideoFragment - [2019-07-21 11:17:36.311] muteUnMuteExoplayer VideoPlayerFragment{25d2898 #0 id=0x32 VideoFragment} isMute :true
	Line 2335: 2019.07.21 11:11:45.356 DEBUG [main] VideoFragment - [2019-07-21 11:17:36.315] buildMediaSource uri : storage/emulated/0/files/Download/63.mp4
	Line 2337: 2019.07.21 11:11:45.360 DEBUG [main] VideoFragment - [2019-07-21 11:17:36.320] buildMediaSource TYPE_OTHER
	Line 2339: 2019.07.21 11:11:45.364 DEBUG [main] VideoFragment - [2019-07-21 11:17:36.324] buildDataSourceFactory build DataSourceFactory
	Line 2340: 2019.07.21 11:11:45.366 DEBUG [main] VideoFragment - [2019-07-21 11:17:36.326] buildDataSourceFactory encryption type: null
	Line 2341: 2019.07.21 11:11:45.368 DEBUG [main] VideoFragment - [2019-07-21 11:17:36.327] buildDataSourceFactory returned already created data source factory
	Line 2342: 2019.07.21 11:11:45.370 DEBUG [main] VideoFragment - [2019-07-21 11:17:36.329] stopPlayer isReset : false mExoPlayer : com.google.android.exoplayer2.SimpleExoPlayer@7a3e09f
	Line 2343: 2019.07.21 11:11:45.372 DEBUG [main] VideoFragment - [2019-07-21 11:17:36.332] startPlayer uri from filePath : /storage/emulated/0/Android/data/panasonic.digital.signage.pionpremises2/files/Download/63.mp4
	Line 2344: 2019.07.21 11:11:45.374 DEBUG [main] VideoFragment - [2019-07-21 11:17:36.334] logContentPlayBackModel
	Line 2349: 2019.07.21 11:11:45.384 DEBUG [main] VideoFragment - [2019-07-21 11:17:36.343] startPlayer displayMode : STRETCH-TO-FIT
	Line 2351: 2019.07.21 11:11:45.388 DEBUG [main] VideoFragment - [2019-07-21 11:17:36.348] initializeExoPlayer Video
	Line 2353: 2019.07.21 11:11:45.393 DEBUG [main] VideoFragment - [2019-07-21 11:17:36.352] initializeExoPlayer Video same video player is being used mPlayer :com.google.android.exoplayer2.SimpleExoPlayer@7a3e09f
	Line 2355: 2019.07.21 11:11:45.397 DEBUG [main] VideoFragment - [2019-07-21 11:17:36.357] playVideoByExoplayer uri : storage/emulated/0/files/Download/63.mp4
	Line 2357: 2019.07.21 11:11:45.401 DEBUG [main] VideoFragment - [2019-07-21 11:17:36.360] muteUnMuteExoplayer VideoPlayerFragment{25d2898 #0 id=0x32 VideoFragment} isMute :true
	Line 2357: 2019.07.21 11:11:45.401 DEBUG [main] VideoFragment - [2019-07-21 11:17:36.360] muteUnMuteExoplayer VideoPlayerFragment{25d2898 #0 id=0x32 VideoFragment} isMute :true
	Line 2357: 2019.07.21 11:11:45.401 DEBUG [main] VideoFragment - [2019-07-21 11:17:36.360] muteUnMuteExoplayer VideoPlayerFragment{25d2898 #0 id=0x32 VideoFragment} isMute :true
	Line 2358: 2019.07.21 11:11:45.403 DEBUG [main] VideoFragment - [2019-07-21 11:17:36.363] buildMediaSource uri : storage/emulated/0/files/Download/63.mp4
	Line 2360: 2019.07.21 11:11:45.407 DEBUG [main] VideoFragment - [2019-07-21 11:17:36.367] buildMediaSource TYPE_OTHER
	Line 2361: 2019.07.21 11:11:45.409 DEBUG [main] VideoFragment - [2019-07-21 11:17:36.369] buildDataSourceFactory build DataSourceFactory
	Line 2362: 2019.07.21 11:11:45.411 DEBUG [main] VideoFragment - [2019-07-21 11:17:36.371] buildDataSourceFactory encryption type: null
	Line 2363: 2019.07.21 11:11:45.414 DEBUG [main] VideoFragment - [2019-07-21 11:17:36.373] buildDataSourceFactory returned already created data source factory
	Line 2365: 2019.07.21 11:11:45.419 DEBUG [main] VideoFragment - [2019-07-21 11:17:36.378] PlayerEventListener onTracksChanged VideoPlayerFragment{25d2898 #0 id=0x32 VideoFragment}
	Line 2365: 2019.07.21 11:11:45.419 DEBUG [main] VideoFragment - [2019-07-21 11:17:36.378] PlayerEventListener onTracksChanged VideoPlayerFragment{25d2898 #0 id=0x32 VideoFragment}
	Line 2365: 2019.07.21 11:11:45.419 DEBUG [main] VideoFragment - [2019-07-21 11:17:36.378] PlayerEventListener onTracksChanged VideoPlayerFragment{25d2898 #0 id=0x32 VideoFragment}
	Line 2367: 2019.07.21 11:11:45.464 DEBUG [main] VideoFragment - [2019-07-21 11:17:36.423] PlayerEventListener onPlayerStateChanged playWhenReady : true playbackState : 2 VideoPlayerFragment{25d2898 #0 id=0x32 VideoFragment}
	Line 2367: 2019.07.21 11:11:45.464 DEBUG [main] VideoFragment - [2019-07-21 11:17:36.423] PlayerEventListener onPlayerStateChanged playWhenReady : true playbackState : 2 VideoPlayerFragment{25d2898 #0 id=0x32 VideoFragment}
	Line 2367: 2019.07.21 11:11:45.464 DEBUG [main] VideoFragment - [2019-07-21 11:17:36.423] PlayerEventListener onPlayerStateChanged playWhenReady : true playbackState : 2 VideoPlayerFragment{25d2898 #0 id=0x32 VideoFragment}
	Line 2368: 2019.07.21 11:11:45.468 DEBUG [main] VideoFragment - [2019-07-21 11:17:36.427] playVideoByExoplayer player is prepared
	Line 2369: 2019.07.21 11:11:45.478 DEBUG [main] VideoFragment - [2019-07-21 11:17:36.437] playVideoByExoplayer player is prepared
	Line 2370: 2019.07.21 11:11:45.492 DEBUG [main] VideoFragment - [2019-07-21 11:17:36.450] PlayerMediaSourceEventListener onMediaPeriodCreated VideoPlayerFragment{25d2898 #0 id=0x32 VideoFragment}
	Line 2370: 2019.07.21 11:11:45.492 DEBUG [main] VideoFragment - [2019-07-21 11:17:36.450] PlayerMediaSourceEventListener onMediaPeriodCreated VideoPlayerFragment{25d2898 #0 id=0x32 VideoFragment}
	Line 2370: 2019.07.21 11:11:45.492 DEBUG [main] VideoFragment - [2019-07-21 11:17:36.450] PlayerMediaSourceEventListener onMediaPeriodCreated VideoPlayerFragment{25d2898 #0 id=0x32 VideoFragment}
	Line 2371: 2019.07.21 11:11:45.563 DEBUG [main] VideoFragment - [2019-07-21 11:17:36.522] PlayerMediaSourceEventListener onLoadStarted VideoPlayerFragment{25d2898 #0 id=0x32 VideoFragment}
	Line 2371: 2019.07.21 11:11:45.563 DEBUG [main] VideoFragment - [2019-07-21 11:17:36.522] PlayerMediaSourceEventListener onLoadStarted VideoPlayerFragment{25d2898 #0 id=0x32 VideoFragment}
	Line 2371: 2019.07.21 11:11:45.563 DEBUG [main] VideoFragment - [2019-07-21 11:17:36.522] PlayerMediaSourceEventListener onLoadStarted VideoPlayerFragment{25d2898 #0 id=0x32 VideoFragment}
	Line 2372: 2019.07.21 11:11:45.624 DEBUG [main] VideoFragment - [2019-07-21 11:17:36.583] logContentPlayBackModel
	Line 2377: 2019.07.21 11:11:45.643 ERROR [main] VideoFragment - [2019-07-21 11:17:36.602] PlayerMediaSourceEventListener onLoadError e : com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected IllegalArgumentException: null
	Line 2393:  VideoPlayerFragment{25d2898 #0 id=0x32 VideoFragment}
	Line 2393:  VideoPlayerFragment{25d2898 #0 id=0x32 VideoFragment}
	Line 2400: 2019.07.21 11:11:45.836 DEBUG [main] VideoFragment - [2019-07-21 11:17:36.796] releasePlayer mExoPlayer : com.google.android.exoplayer2.SimpleExoPlayer@7a3e09f

### [REQUIRED] Version of ExoPlayer being used
2.9.4

### [REQUIRED] Device(s) and version(s) of Android being used
OS: Android marshmellow 6.0
Device: Rockchip Quad 162

**Comment by ojw28** [comment]
This is not sufficient logging for us to tell you (or us!) what's going wrong:

```
Line 2377: 2019.07.21 11:11:45.643 ERROR [main] VideoFragment - [2019-07-21 11:17:36.602] PlayerMediaSourceEventListener onLoadError e : com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected IllegalArgumentException: null
```

You're going to need to add some more logging, for example to output the full stack trace that shows where the error actually occurs. If you were to use the `EventLogger` provided by the library, then I'd expect the stack trace to be logged, similar to this logging for an error that I caused artificially in code:

```
07-26 11:44:59.731 24431 24431 E EventLogger: internalError [0.67, 0.00, window=0, period=0, loadError]
07-26 11:44:59.731 24431 24431 E EventLogger: com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected IllegalArgumentException: Oops
07-26 11:44:59.731 24431 24431 E EventLogger: 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:403)
07-26 11:44:59.731 24431 24431 E EventLogger: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
07-26 11:44:59.731 24431 24431 E EventLogger: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
07-26 11:44:59.731 24431 24431 E EventLogger: 	at java.lang.Thread.run(Thread.java:764)
07-26 11:44:59.731 24431 24431 E EventLogger: Caused by: java.lang.IllegalArgumentException: Oops
07-26 11:44:59.731 24431 24431 E EventLogger: 	at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:330)
07-26 11:44:59.731 24431 24431 E EventLogger: 	at com.google.android.exoplayer2.source.chunk.InitializationChunk.load(InitializationChunk.java:89)
07-26 11:44:59.731 24431 24431 E EventLogger: 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
07-26 11:44:59.731 24431 24431 E EventLogger: 	... 3 more
```

Please update this issue when you have further logging that more accurately pinpoints the problem.
