### ISSUE TITLE
Low latency streaming with ExoPlayer?

### ISSUE THREAD

**Issue by Schizo** [google/ExoPlayer#623]
Sorry for proposing this question here, but i was successfully using ExoPlayer as a main VOD Video-Player and i am really happy about it. Now i was going to use it to play Video-Streams but unfortunately exoplayer supports only DASH, HLS and Smoothstreaming. 

But are those formats good for low-latency-streaming? Or how is the standard way of Streaming a "dash" file to a server, to browse it with a mobile phone? What are the minimum available Segment Durations. Can i set it to frames? 

Please enlighten me.

**Comment by ojw28** [comment]
ExoPlayer supports a bunch of formats in addition to the ones you mention (MP4, MP3, WebM, Matroska, Mpeg-TS, ADTS-AAC).

For DASH/HLS/SS you probably wouldn't want chunks any shorter than 2 seconds. For low latency streaming you'd probably want something like RTMP, which ExoPlayer doesn't support. The idea of single (or few) frame latency across the internet isn't realistic though, so I'm wondering exactly what you're trying to achieve.

**Comment by Schizo** [comment]
I don't want to achieve this latency over internet but in a intranet lan network. with RTMP the current latency is about 6 Frames, with UDP about 4 Frames. All in Local Network.

**Comment by ojw28** [comment]
ExoPlayer isn't really geared to this use case (i.e. local playback with very low latency). We don't currently support RTMP/UDP.

**Comment by winlinvip** [comment]
Hi, I think the low-latency for ExoPlayer is possible, if streaming server support HTTP-FLV/HTTP-TS to replace RTMP.
@ojw28 Can you re-open this issue, seems the #828 and HTTP-TS is supported by ExoPlayer.

I think the low-latency or realtime player need another important feature, the MaxBufferLength, which limit the max buffer length in seconds, drop packet or change the fps if exceed.

However, I think it's a very awesome feature for ExoPlayer to support realtime, eventhough without the MaxBufferLength.

**Comment by winlinvip** [comment]
BTW, I want to introduce more about the HTTP-FLV low latency live streaming for Android.
I have start a Android encoder, which fetch the image from camera and encode by MediaCodec and send to [SRS](https://github.com/simple-rtmp-server/srs) over HTTP POST, that is [srs-sea](https://github.com/simple-rtmp-server/srs-sea).
I plan to start a player named srs-spa, but I found ExoPlayer and this pull request, thanks very much, I have canceled the srs-spa project and linked to ExoPlayer.

It's very very important feature for low latency live streaming on Android, user can use [srs-sea](https://github.com/simple-rtmp-server/srs-sea) to publish stream to [SRS](https://github.com/simple-rtmp-server/srs) and  play with ExoPlayer, the latency is 1s+, it's awesome~

I use ExoPlayer to play the http://ossrs.net:8081/live/livestream.ts, it works~

I test the latency, use srs-sea to publish and exoplayer to play, the latency is 1s - 3s:
![sea exoplayer](https://cloud.githubusercontent.com/assets/2777660/10747895/7655950a-7c95-11e5-92ad-40e4037b9035.jpg)

**Comment by winlinvip** [comment]
Great ExoPlayer, I love this project, :+1: :+1: :+1:

**Comment by erkand-imeri** [comment]
Does ExoPlayer support RTMP links? Is it better than  Vitamio to use?

**Comment by winlinvip** [comment]
@erkand-imeri Why RTMP? You can use server to remux the RTMP to HTTP-FLV.

BTW: Vitamio is not open-source, right?

**Comment by erkand-imeri** [comment]
Aha, great. I think Vitamio is not open-source. It's free to  use  for  non-commercial purposes. @winlinvip: Do you think ExoPlayer is the best Android media library  to use  for  live streaming?

**Comment by winlinvip** [comment]
@erkand-imeri I am the author of [srs](https://github.com/ossrs/srs), which can used to remux rtmp to http-flv and/or hls. I think ExoPlayer is the one for android player for live streaming.
