### ISSUE TITLE
Cached stream won't play in offline mode

### ISSUE THREAD

**Issue by srikanthsunkari** [google/ExoPlayer#6232]
### Searched documentation and issues
I have used the exoplayer demo application cache implementation with few changes of,

i. Using LeastRecentlyUsedCacheEvictor

`new SimpleCache(downloadContentDirectory, new LeastRecentlyUsedCacheEvictor(DEFAULT_MAX_CACHE_FILE_SIZE * 5));
`

ii. And removed the DatabaseProvider. 

iii. Applied CacheDataSink()

                `new CacheDataSinkFactory(cache, DEFAULT_MAX_CACHE_FILE_SIZE * 5),`

iv. And the Modified download directory

```
      if (downloadDirectory == null) {
            downloadDirectory = getExternalCacheDir();
            if (downloadDirectory == null) {
                downloadDirectory = getCacheDir();
            }
        }
```

### Questions

**1. Is the expected behavior of this implementation would be like of cached stream playback would happen in offline as well Or It will only happen in online mode?** 

**2. If I want to make the playback of the cached stream to happen in offline as well what are the changes that I need to do?**

**3. Also when I use NoOpCacheEvictor without the maxCacheSize, there are more than 10 .exo files of size 2mb are created, but when I use LeastRecentlyUsedCacheEvictor and CacheDataSinkFactory with each 10mb It creates only two .exo files with each of 5mb size are created. How can I make sure that each stream cache .exo file got created only once and entire cache won't exceed the max cache size?**

Apologies, I am newB to the caching implementation.

Thank you for the amazing work.

**Comment by marcbaechinger** [comment]
When you are using a CacheDataSource your app will read data from the cache in offline and online mode. The CacheDataSource is not aware of a network state. It just checks whether the data is available in the cache and reads from it when available. If no data is available loading data is delegated to the wrapped upstream datasource.

So if it works in online mode then you don't need to apply changes to support offline.

**Comment by srikanthsunkari** [comment]
Thanks for the reply @marcbaechinger 
> When you are using a CacheDataSource your app will read data from the cache in offline and online mode. The CacheDataSource is not aware of a network state. It just checks whether the data is available in the cache and reads from it when available. If no data is available loading data is delegated to the wrapped upstream datasource.

you are absolutely right, I assumed the same, that It should also stream in offline when there is a cache available using CacheDataSource.

>So if it works in online mode then you don't need to apply changes to support offline.

I didn't do any specific changes to support in offline mode but I am unable to play offline mode ?

**Comment by marcbaechinger** [comment]
Is this still an issue or can we close this?
