### ISSUE TITLE
How to remove PlayerNotificationManager.NotificationListener

### ISSUE THREAD

**Issue by abhishekredspace** [google/ExoPlayer#6236]
Hello Exoplayer team, 
I have created an audio player as a service and I have tied a notification to it. Now I want to remove the notification after the user has paused on user swipe. I am able to achieve the functionality but not 100% correctly. I took a look at 
https://github.com/google/ExoPlayer/issues/5792#issuecomment-486269001 and followed it. 

Issue: When my app goes to the background and user pauses the playback and dismisses the notification. Here is my code, everything works fine and notification gets dismissed but only after 2-3 seconds, the notification appears again and I can see 
```onNotificationPosted(notificationId: Int, notification: Notification?, ongoing: Boolean)``` is called again. 

```
viewModel.getState().observe(this, Observer {
            // https://github.com/google/ExoPlayer/issues/5792#issuecomment-486269001
            if (it == StreamState.STOPPED) {
                this.stopForeground(false)
            }
            else if (it == StreamState.STARTED) {
                viewModel.createNotification(
                    { notificationId, notification -> startForeground(notificationId, notification) },
                    { notificationId, dismissedByUser ->
                        if (!dismissedByUser) {
                            stopSelf()
                        }
                        cancelNotification(notificationId)
                        viewModel.removeNotification()
                    },
                    ContextCompat.getColor(application.applicationContext, R.color.app_background)
                )
            }
        })
    }
```

```
fun createNotification(onNotificationPosted: (id: Int, notification: Notification?) -> Unit,
                           onNotificationCancelled: (notificationId: Int, dismissedByUser: Boolean) -> Unit,
                           notificationColor: Int) {
        val channelId = "media_playback_channel"
        exoNotificationListener = ExoNotificationListener(onNotificationPosted, onNotificationCancelled, this)
        notificationChannel = PlayerNotificationManager.createWithNotificationChannel(
            application.applicationContext,
            channelId,
            R.string.media_playback_notification,
            R.string.media_playback_notification_id,
            mcNotificationManager,
            exoNotificationListener
        )


        // TODO: Remove android stuff.
        notificationChannel?.setColor(notificationColor)

        bindPlayer(notificationChannel)
    }
 ```

 ```
 inner class ExoNotificationListener(private val onNotificationPosted: (id: Int, notification: Notification?) -> Unit,
                                        private val onNotificationCancelled: (notificationId: Int, dismissedByUser: Boolean) -> Unit)
        : PlayerNotificationManager.NotificationListener {
        override fun onNotificationPosted(notificationId: Int, notification: Notification?, ongoing: Boolean) {

            state.observeForever {
                if (it == StreamState.STARTED && ongoing)
                    onNotificationPosted.invoke(notificationId, notification)
            }
        }

        override fun onNotificationCancelled(notificationId: Int, dismissedByUser: Boolean) {
            onNotificationCancelled.invoke(notificationId, dismissedByUser)
        }
    }
```

```
fun removeNotification() {
        playerNotificationManager?.setPlayer(null)
        exoNotificationListener = null
        playerNotificationManager = null
    }
```

What I am exactly looking for is how I should remove the `PlayerNotificationManager.NotificationListener`.

**Comment by abhishekredspace** [comment]
Little more update here: I am working on Livestream and after some debugging in the exoplayer code, I found that after I dismiss the notification, it is triggered from 
```
@Override
    public void onTimelineChanged(Timeline timeline, @Nullable Object manifest, int reason) {
      startOrUpdateNotification();
    }
```
The reason is 2 which is 
```
/**
   * Timeline or manifest changed as a result of an dynamic update introduced by the played media.
   */
  int TIMELINE_CHANGE_REASON_DYNAMIC = 2;
```

**Comment by marcbaechinger** [comment]
Yes, this makes sense. The live stream is updating the manifest which triggers a source refresh with a new timeline. The player notification manager does not really know what has changed and updates the notification.

As a quick solution for you, I think you need to null the player of the notification manager. This unregisters all event handlers. If you start playback again you can just set the player again:

```
public void onNotificationCancelled(int notificationId, boolean dismissedByUser) {
    /// do stuff as before
    playbackNotificationManager.setPlayer(null);
}
```

then if resume playback you set the player again:

```
playbackNotificationManager.setPlayer(player);
```

**Comment by abhishekredspace** [comment]
Thanks for your reply. I am already setting the player as null on playbackNotificationManager but still see the issue. 
I call the below method when notificationCancelled is received. 
```
fun removeNotification() {
        playerNotificationManager?.setPlayer(null)
        exoNotificationListener = null
        playerNotificationManager = null
    }
```

**Comment by marcbaechinger** [comment]
This sounds odd indeed. 

When calling `setPlayer(null)` the event listener is removed from the player. So I wonder why you are still seeing `onTimelineChanged` being called afterwards. Can you verify with a debugger that setPlayer(null) is called as you expect it?

**Comment by abhishekredspace** [comment]
Yes, I can assure that setPlayer(null) is called after `onNotificationCancelled`. 
<img width="1621" alt="Screen Shot 2019-08-01 at 9 16 34 AM" src="https://user-images.githubusercontent.com/16784627/62293039-11232a00-b43e-11e9-8ce0-30c82a35a1af.png">

Do I need to call the exoplayer.stop() as well? If that is true, in that case I would have to re-prepare the same content when the user comes back into the app and in that case, need to start from the same position at which the user paused and dismissed.

**Comment by abhishekredspace** [comment]
So I found the bug, it is in my code. Somehow there was a bug in my event listener which was triggering Started multiple times and consequently, createNotification was getting triggered more than once. So even after player was set to null, there were other instance attached to it. Thanks for your help and inputs.
