### ISSUE TITLE
Exception while trying to play Multicast MPEG/TS UDP Stream

### ISSUE THREAD

**Issue by voipworld** [google/ExoPlayer#6240]
### [REQUIRED] Searched documentation and issues
ExoPlayer Dev Website, StackOverFlow, github issues
### [REQUIRED] Question
i am trying to play a multicast stream, the source is a software encoding from SAT to IP (MumuDVB), and issue is:
ataching bug reports & code...
### A full bug report captured from the device
```
01-01 10:29:50.456 10773 11191 E ExoPlayerImplInternal: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to udp://239.1.4.3:1234                                                                
01-01 10:29:50.456 10773 11191 E ExoPlayerImplInternal: Caused by: java.net.MalformedURLException: unknown protocol: udp
```
###Example Code
```
package io.tm.openview.activitys;

import android.app.Activity;
import android.net.Uri;
import android.os.Bundle;
import android.view.SurfaceView;
import com.google.android.exoplayer2.DefaultRenderersFactory;
import com.google.android.exoplayer2.RenderersFactory;
import com.google.android.exoplayer2.upstream.BandwidthMeter;
import com.google.android.exoplayer2.trackselection.AdaptiveTrackSelection;
import com.google.android.exoplayer2.trackselection.TrackSelection;
import com.google.android.exoplayer2.trackselection.DefaultTrackSelector;
import com.google.android.exoplayer2.trackselection.TrackSelectionArray;
import com.google.android.exoplayer2.trackselection.TrackSelector;

import com.google.android.exoplayer2.LoadControl;
import com.google.android.exoplayer2.DefaultLoadControl;
import com.google.android.exoplayer2.ExoPlayerFactory;
import com.google.android.exoplayer2.SimpleExoPlayer;
import com.google.android.exoplayer2.source.ExtractorMediaSource;
import com.google.android.exoplayer2.source.MediaSource;
import com.google.android.exoplayer2.upstream.DefaultBandwidthMeter;
import com.google.android.exoplayer2.upstream.DefaultDataSourceFactory;
import com.google.android.exoplayer2.upstream.UdpDataSource;
import com.google.android.exoplayer2.util.Util;
import io.tm.openview.R;

public class CastActivity extends Activity {
    SimpleExoPlayer player = null;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_cast);
DefaultBandwidthMeter defaultBandwidthMeter = new DefaultBandwidthMeter();
RenderersFactory renderersFactory = new DefaultRenderersFactory(this);
TrackSelection.Factory videoTrackSelectionFactory = new AdaptiveTrackSelection.Factory(defaultBandwidthMeter);
TrackSelector trackSelector = new DefaultTrackSelector(videoTrackSelectionFactory);
LoadControl loadControl = new DefaultLoadControl();
player=ExoPlayerFactory.newSimpleInstance(renderersFactory, trackSelector, loadControl);
        SurfaceView playerView = findViewById(R.id.surface_view);
UdpDataSource.Factory udpDataSource = new DefaultDataSourceFactory(this, Util.getUserAgent(this, "CastActivity"), defaultBandwidthMeter);
MediaSource videoSource = new ExtractorMediaSource.Factory(udpDataSource).createMediaSource(Uri.parse(getIntent().getStringExtra("EXTRA_URL")));
        player.setVideoSurfaceView(playerView);
        player.prepare(videoSource);
        player.setPlayWhenReady(true);
}
    @Override
    protected void onDestroy() {
        super.onDestroy();
        player.release();
}
}
```

**Comment by marcbaechinger** [comment]
The debug snippet says

```
com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to udp://239.1.4.3:1234
```

Can you check why this is coming from a `HttpDataSource`? In the snippet above you are using an `DefaultDataSourceFactory` which should resolve the datasource to a `UdpDataSource` according to the scheme of the url. Can you for instance put a break point in `DataSourceFactory.open` and verify what data source is created?

**Comment by voipworld** [comment]
can you give me the exact line to try please? i am lost in this world
of data sources. 3 days of trying and tryying, single our of sleeping.

**Comment by voipworld** [comment]
i got the same result with ExoMedia VideoView, exactly the same Exception, full code provided:
layout:
<RelativeLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@android:color/black">

    <com.devbrackets.android.exomedia.ui.widget.VideoView
        android:id="@+id/videoview"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:useDefaultControls="true"/>
</RelativeLayout>
MainActivity:
package pro.islamzone.playout;

import android.annotation.SuppressLint;
import androidx.appcompat.app.AppCompatActivity;
import android.os.Bundle;
import android.content.Intent;
import android.content.Context;
import android.widget.Toast;
import android.net.Uri;
import android.view.SurfaceView;
import android.view.KeyEvent;
import android.view.View;
import com.devbrackets.android.exomedia.ExoMedia;
import com.devbrackets.android.exomedia.ui.widget.VideoControls;
import com.devbrackets.android.exomedia.ui.widget.VideoView;

public class MainActivity extends AppCompatActivity {
private Context c;
private VideoView mVideoView;
@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
c=MainActivity.this;
Intent intent = getIntent();
String action = intent.getAction();
String type = intent.getType();
       if (!action.equals(Intent.ACTION_VIEW)) {
finish();
} else {
Uri data = intent.getData();
String URL=data.toString();
mVideoView= (VideoView)findViewById(R.id.videoview);
mVideoView.setVideoURI(data);
mVideoView.start();
}
}
}
gradle dependencies:
api 'com.devbrackets.android:exomedia:4.3.0'
please note that this code capture the UDP uri from a intent filter...
thanks.

**Comment by voipworld** [comment]
Issue Fixed!
migrated to EXOPlayer R2.10.3 and the UDP is playing well...!
fun...
;)

**Comment by voipworld** [comment]
Please Migrate any existing code or new code that need multicast UDP/RTP to 2.10.3.
