### ISSUE TITLE
Subtitles are not displayed properly for SMPTE-TT Bitmap subtitles ( One line of subtitle at the bottom is half visible )

### ISSUE THREAD

**Issue by himaswetha** [google/ExoPlayer#6243]
### [REQUIRED] Issue description
For SMPTE-TT subtitles subtitles are getting displayed but from the two lines which are displayed the second line at the bottom is half visible.

### [REQUIRED] Reproduction steps
It can be easily reproducible with 2.10.3  version of Exoplayer in demo app.

### [REQUIRED] Version of ExoPlayer being used
2.10.3 

### [REQUIRED] Device(s) and version(s) of Android being used
**Tested on SAMSUNG LED TV, Model No: LT24E310AR/XL / 2018, Screen size: 60 cm. Attached the image which contains the device details on which this is tested and issue is happened and android version of the setup box is 7.1.1.** 

**This issue is not seen in other model of SAMSUNG TV - 'SAMSUNG Screensize:80cm Model No:UA32M5570AULXL / 2018**

**This issue is not seen in Android 1ft device - Samsung galaxy S8.**

**Comment by himaswetha** [comment]
Anyone looking into this issue please need help ASAP.

**Comment by marcbaechinger** [comment]
When I add the subtitle file you attached to a video nothing is displayed. When I copy the base64 pdf in the file and convert to PNG I get a 1080x1920 bitmap which is blank (all pixel transparent). That's also what I see what is retrieved and rendered by the `SubtitleView`.

May I ask you to look into the file you attached here and check whether that's what you expect?

Another thought is that the positioning of the text within the bitmap can't really be adjusted by the SubtitleView. The bitmap is 1080x1920. The subtitle view may need to scale accordingly but the position of the text within that bitmap is probably fixed. The screenshot you attached shows that the text is centered properly so it does not appear to be a scaling issue. I wonder how the overscan of that TV is an issue and the positioning needs to be adjusted in the bitmap for TVs?

Can you please check the subtitle file to see if it contains what you expect?

**Comment by himaswetha** [comment]
Sent the content url link to dev.exoplayer@gmail.com. Can you please check the mail and use that url to play the content directly in Demo app?
--

**Comment by himaswetha** [comment]
Link for the asset to reproduce the issue. Please do not share this
link with any one.


{
  "name": "osmovie LIVE  ",
  "uri": "https://vsppstreamer.osim.mr.tv3cloud.com:5554/sdash/LIVE$2100011276/index.mpd/Manifest?device=DASH&start=LIVE&&end=END",
  "extension": "mpd"
},

**Comment by himaswetha** [comment]
Hi @marcbaechinger any update on this issue?

**Comment by ojw28** [comment]
This is an AVKO box connected to the Samsung TV, presumably via HDMI, right?

Are you sure this is specific to subtitles? It seems likely that the whole of the bottom of the display is just being cut off when this box is connected to the Samsung TV.

**Comment by himaswetha** [comment]
Yes it's avko box connected with HDMI cable.

Yes issue seems to be specific to subtitles. Because other assets are
playing fine. Issue is seen only with this particular asset. But Not sure
why the issue is only with this particular type of TV. In some other model
of TV which I mentioned this issue is not seen.

**Comment by ojw28** [comment]
Is the video itself being clipped, in addition to the subtitles? Can you capture the same frame of the video on a device where this isn't a problem, for example the Galaxy S8, for comparison?

**Comment by himaswetha** [comment]
I think video itself its clipped when compared to Samsung TV and Galaxy S8. Sent you the frames for TV and Mobile for comparision.

**Comment by ojw28** [comment]
I don't think this is an ExoPlayer issue. It sounds like a problem with either the device or the TV. Possibly some kind of overscan problem?

**Comment by himaswetha** [comment]
So what should be the possible solution?

**Comment by ojw28** [comment]
I think you should try connecting other devices to this TV. If it's cropping the output for all of them, then it might just be an overscan setting on the TV that you need to adjust. If it's specific to this device connected to this TV, you probably need to follow up with the device manufacturer. Debugging this kind of issue is out of scope of this issue tracker, since it doesn't sound like an ExoPlayer specific problem.

**Comment by himaswetha** [comment]
Thanks after adjusting the screen size settings its working properly now.
