### ISSUE TITLE
Image break when textureview is used instead of surface view

### ISSUE THREAD

**Issue by bumdream** [google/ExoPlayer#6244]
- I'm sorry for creating another issue, and thank you for reading it. 

### Searched documentation and issues
- I've looked up the google and issue as much as I can, but I can't find the correct answer, so I'll eventually register the issue. 

### Question
- In the same environment, I replaced the `surface_type` from surface_view to texture_view, but the image of the image is broken. Is there anything else I need to do with textureview?
(We need to use textureview below N version..)

## Test
> Device : Galaxy S10 (9.0), Galaxy S4 (4.4.2)
### when using SurfaceView
![Screenshot_20190731-102047_Dev Debug](https://user-images.githubusercontent.com/21086676/62177523-276ab080-b380-11e9-8c2d-469cbfbe425d.jpg)

### when using TextureView
![Screenshot_20190731-102653_Dev Debug](https://user-images.githubusercontent.com/21086676/62177521-26398380-b380-11e9-808e-76ec9b036403.jpg)
- If you zoom in, you'll see that the image is broken.

### The xml we use is as follows.
```xml
<merge
    xmlns:android="http://schemas.android.com/apk/res/android" xmlns:app="http://schemas.android.com/apk/res-auto">
    <com.google.android.exoplayer2.ui.PlayerView
        android:id="@+id/playerView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:resize_mode="fixed_width"
        app:use_controller="false"
        app:surface_type="texture_view" --> only change this property.
    />
</merge>
```

### The code sets the settings as shown below.
```kotlin
class PlayerContainer @JvmOverloads constructor(context: Context, attrs: AttributeSet? = null, defStyleAttr: Int = 0): FrameLayout(context, attrs, defStyleAttr) {

    init {
        LayoutInflater.from(context).inflate(R.layout.video_viewer_layout, this)
        ...
        initPlayer()
    }    

    fun initplayer() {
         playerView?.player = ExoPlayerFactory.newSimpleInstance(...)
    }

    // ...

    override fun onMeasure(width: Int, height: Int) {
        super.onMeasure(width, height)
        setMeasuredDimension(measuredWidth, measuredHeight)
    }
}
```

Thank you for your time.

**Comment by andrewlewis** [comment]
This looks the same as #6084. To resolve the issue on the newer device you can probably switch to using `SurfaceView` for devices running Android N and later.
