### ISSUE TITLE
how i know exoplayer is not playing due to audiofocus change  becuse phone call 

### ISSUE THREAD

**Issue by geeta4** [google/ExoPlayer#6246]
i want to know exoplayer is paused due to audiofocus change becuse of phone call becuse i give to exoplayer to handle
by simpleExoPlayer.setAudioAttributes(audioAttributes, true);

but i need to handle something at time of pause due to focus change so what is the way so i can know this value exoplayer will resume after disconnect call

**Comment by ojw28** [comment]
This is not possible currently. It's being tracked by https://github.com/google/ExoPlayer/issues/6203.
