### ISSUE TITLE
DefaultLoadControl.Builder constructor - wrong constant?

### ISSUE THREAD

**Issue by KosmoGalaxy** [google/ExoPlayer#6247]
DefaultLoadControl.java
line 88
**minBufferVideoMs = DEFAULT_MAX_BUFFER_MS;**
```
public Builder() {
  minBufferAudioMs = DEFAULT_MIN_BUFFER_MS;
  minBufferVideoMs = DEFAULT_MAX_BUFFER_MS;
  maxBufferMs = DEFAULT_MAX_BUFFER_MS;
  bufferForPlaybackMs = DEFAULT_BUFFER_FOR_PLAYBACK_MS;
  bufferForPlaybackAfterRebufferMs = DEFAULT_BUFFER_FOR_PLAYBACK_AFTER_REBUFFER_MS;
  targetBufferBytes = DEFAULT_TARGET_BUFFER_BYTES;
  prioritizeTimeOverSizeThresholds = DEFAULT_PRIORITIZE_TIME_OVER_SIZE_THRESHOLDS;
  backBufferDurationMs = DEFAULT_BACK_BUFFER_DURATION_MS;
  retainBackBufferFromKeyframe = DEFAULT_RETAIN_BACK_BUFFER_FROM_KEYFRAME;
}
```
Shouldn't minBufferVideoMs be set to DEFAULT_MIN_BUFFER_MS?

**Comment by tonihei** [comment]
This is intended. DEFAULT_MAX_BUFFER_MS is defined as:

_The default maximum duration of media that the player will attempt to buffer, in milliseconds.
**For playbacks with video, this is also the default minimum duration of media that the player
will attempt to ensure is buffered.**_

Effectively this means that the player will always try to keep a buffer of DEFAULT_MAX_BUFFER_MS for video playbacks.

**Comment by KosmoGalaxy** [comment]
My bad, waisted time, sorry.
