### ISSUE TITLE
Akamai Auth Token based protected media playback using Exoplayer

### ISSUE THREAD

**Issue by amitsamal** [google/ExoPlayer#625]
Hi Team,

Currently we are implementing Akamai token based protected media playback in our HLS streams. Does Exoplayer support this feature.
Our current setup - Streaming url is fetched using the REST API ex: http://www.example.com/directory1/directory2/ media.m3u8?hdnts=st=1370627194~exp=1370627409~acl=/ *~hmac=6a10b3f602ffde88c02cd1b89665bfdfdc0fc84c3cf7049752931ad732654fab

Where the hdnts represent the token and it is shortlived token with specific expiry time. 
Once the player gets the streaming url it would do the HTTP request to server. Server takes up the token and in return validates and sends back a long life token in cookie for the media segment to the player.
The player now should use the same token returned in cookie for each subsequent request for media segment for playback.
Can you please help us understand if exoplayer supports this kind of authentication based protected media streaming by accepting cookies out of the box or we need to do some specific customizations in the player.

Regards
Amit Samal

**Comment by gitanuj** [comment]
I think you're talking about the cookie authentication feature provided by
Akamai for distributing HLS media. You just need to make sure that all the
HTTP connections you make for a particular media file should use the same
cookie store. This can be easily done by tweaking DefaultHttpDataSource.

**Comment by ojw28** [comment]
I think that's correct, yes. Depending on your application, you may be able to do something even simpler and just install a default cookie manager to be used everywhere. The demo application does this in PlayerActivity, with its call to:

```DemoUtil.setDefaultCookieManager();```

**Comment by amitsamal** [comment]
I think i am looking at a similar solution of modifying the DefaultHttpDataSource as my HLS stream will return cookies to the player for each streamed segment. @gitanuj  would be helpful if u have any sample code or modification example on DefaultHttpDataSource ?

**Comment by gitanuj** [comment]
@amitsamal I don't have any sample code for that. But the easiest solution would be to use default cookie store for everything (as suggested above).

**Comment by Michal-easycore** [comment]
Hey,
I am having the same problem. I have Token Authorization on Akamai enabled and from that moment HLS streams stops working. Even if I disable Token auth temporary. Using Cookie policy like in DemoPlayer didn't help.

I tested following:
- Latest ExoPlayer version not working on any devices and versions. ExoPlayer won't give me any error, it just stays in buffering stage. 
- Nexus 5 Android 5.1.1 Chrome Browser 43.0.2357.93 HLS working
- Samsung S3 Android 4.3.0 Chrome Browser 43.0.2357.93 HLS not working

I try to ask my contractor to share the HLS link, so it could be more helpful.

**Comment by Kening** [comment]
I am hitting the same problem with Akamai generated HLS master playlist with auth token. I can play the video the first time, and then I can't play it unless I clear app data and run the app again, so somewhere someone is persisting stuff, maybe a CookieStore, I can't find it where, the DemoUtils.setDefaultCookieManager() way doesn't fix it. 

When it fail, the ExoPlayer code is trying to fetch a TsChunk, and DefaultHttpDataSource.getContentLength() will always return "0".

**Comment by Kening** [comment]
this may be a problem with the cookie path, I see this in CookieManager
 /**
     * Returns a cookie-safe path by truncating everything after the last "/".
     * When request path like "/foo/bar.html" yields a cookie, that cookie's
     * default path is "/foo/".
     */
    static String pathToCookiePath(String path) {
        if (path == null) {
            return "/";
        }
        int lastSlash = path.lastIndexOf('/'); // -1 yields the empty string
        return path.substring(0, lastSlash + 1);
    }

And in CookieStoreImpl, it's using a HashMap with a URI key, that URI key is a URI with a fixed scheme as "http", and host, without path.

 private URI cookiesUri(URI uri) {
        if (uri == null) {
            return null;
        }
        try {
            return new URI("http", uri.getHost(), null, null);
        } catch (URISyntaxException e) {
            return uri; // probably a URI with no host
        }
    }

I am playing with a customized CookieStore and see if I can get around this problem, no fruit yet.

**Comment by amitsamal** [comment]
@Kening can you mention the sample code on how u are setting the cookie to exoplayer ??? As defaulthttpDataSource internally uses httpurl connection does just setting the cookie manager and cookie store handle things automatically ?

**Comment by Kening** [comment]
@amitsamal I think I need to work with my backend team to get to know more about how Akamai cookie authentication work in this case. 

I first take the ExoPlayer demo app's approach, set a default cookie manager at my activity's onCreate. So if all http connection goes through HttpUrlConnection (I assume ManifestFetcher, and the code to fetch each stream, and fetch each chunk) then all cookie read/write will go through this cookie manager. This doesn't fix my problem. 

Then I look at the CookieManager's default CookieStore implementation, it's a simple map, and it's all in memory. This is the part that baffles me. The symptom I see is that after I install my app fresh, I can play a specific HLS video the very first time, and then if I try to load it again, it fails. And if I clear app data and play it again, it works. That suggest this is something related to some data persisted. But this CookieStore is transient, all in memory, this that doesn't sound like my problem. 

But I have no other clue. So I keep thinking down this path that it may be a cookie related problem. Then I see the CookieManager is trying to process the URI in a certain way to set the cookie path. And the default CookieStore implementation (that map) is using a key that is a URI with only scheme=http and host, so I guess that means all URLs within the same host share the same cookie. I think that may be a problem. I do see a lot of cookie add with name "_alid_" with a different value for every TsChunk fetch, not sure if this is how Akamai works, but I was thinking maybe when we fetch the manifest, server response gives us a "_alid_" in response cookie, and then we need to pass that back in the request to fetch the stream, and in return we get another "_alid_", and we need to pass that back when we request the first ts chunk, and this go on and on. So the idea is probably all these request they have the same host name so the CookieStore's map will just have one instance that's keep updating when it receive an update response cookie with a new "_alid_" value? This is purely my guess.

**Comment by Kening** [comment]
find this post, maybe this is an Akamai problem 
https://community.akamai.com/thread/1846

**Comment by ojw28** [comment]
It's unclear whether the post above is related, because it's primarily referring to Android's built in media player. I suggest requesting some guidance from Akamai at this stage. It should be fairly easy for them to help, since they will know exactly how this setup is supposed to work (and can also easily add a test stream to the demo player and take a look to see what's going wrong).

Re-opening the issue for tracking.

**Comment by Kening** [comment]
Working with Akamai now. 

One other strange finding is that if I don't use Picasso to load image in my app (my app basically shows a grid, each grid cell has an image, I am using Picasso to load the image, and I am also using ExoPlayer to play the video on the cell that's centered, the video is layered on top of the image). Once I get rid of the image loading part, everything works, I don't even have to do any of the workaround like encode "/" as "%2F", etc. Still digging and trying to figure out why.

**Comment by amitsamal** [comment]
@Kening : Basically no change to the sample code available on Exoplayer demo done to make the cookie token based authentication of akamai to work or you introduced cookiemanager and cookie store in the DefaultHttpDataSource implementation ??

**Comment by ojw28** [comment]
Interesting. Thanks for the update! I wonder if Picasso is doing something itself related to the cookie manager, that could be having an interfering effect. It's probably worth grepping through their source code for cookie related stuff, if you haven't done so already.

**Comment by Kening** [comment]
@amitsamal I used to have a customized cookiemanager and cookiestore, and i also used to have some code to massage the manifest url, i removed all those. just by removing the Picasso image fetching code, the playback start to work. 

@ojw28  a preliminary search of "cookie" in Picasso's source doesn't yield any result, I am going to try some other image loader, maybe Volley and Fresco, and see if the other image loader also cause the problem.

**Comment by Kening** [comment]
Picasso is using OkHttp, looking at OkHttp now.

**Comment by Kening** [comment]
I am able to get my problem fixed by doing this in onCreate() of my application class (I extends Application class).

        CookieManager defaultCookieManager = new CookieManager();
        CookieHandler.setDefault(defaultCookieManager);
        OkHttpClient client = new OkHttpClient();
        client.setCookieHandler(defaultCookieManager);
        OkHttpDownloader downloader = new OkHttpDownloader(client);
        new Picasso.Builder(getApplicationContext()).downloader(downloader).build();

basically using the DemoUtil.setDefaultCookieManager() fix, but on top of that passing the CookieManger instance to OkHttpClient instance that Picasso is using. 

@amitsamal  @Michal-easycore I am not sure if you are also using Picasso or OkHttp, but if not, maybe look at any other library that you use that may be using java.net.HttpURLConnection and see if there's a way you can make sure they all use the same CookieManager instance. So far I have not figure out what part in OkHttp that's causing this Akamai token problem. Picasso or OkHttp is not calling CookieHandler.setDefault() to use a different CookieManager, so it must be somewhere in Picasso or OkHttp that's calling CookieHandler.getDefault(), grabbing that CookieManager and somehow modifying the values it stores.

**Comment by amitsamal** [comment]
@Kening : we are also using picasso lib, would try out the solution in our setup and see if it works . Thanks for the information.

**Comment by amitsamal** [comment]
@Kening : Now i think you also will face the same issue using a default cookie manager as in okHttp the cookie is flushed out of memory if one person minimizes the app and goes out. And next time trying to resume the same video which is akamai token authenticated won't play, as cookie isn't present. I am trying now persistence of cookie using OkHttp which should solve the issue.

**Comment by Kening** [comment]
BTW, more info from Akamai, they mention that making sure all the HTTP request bear the same user agent, because they will use the user agent as the salt when generating token, I don't have more info about this, but just need to make sure the call to get the manifest, the call to get the stream playlist and the call to get the TS chunk need to bear the same user agent.

**Comment by dbqwe** [comment]
I have the same problem with wmspanel, it works for some time then stops, in another player stream opens without problems. Any solution yet? What if to remove cookie?What can be the disadvantages?

**Comment by ojw28** [comment]
It's somewhat unclear whether users of Akamai or Akamai ever figured this out, but I'm going to close this due to inactivity.

**Comment by brillenheini** [comment]
I am successfully using Akamai with ExoPlayer. There were some problems with cookies at first, when using the `java.net.CookieManager`, switching to `OkHttpDataSource` (an ExoPlayer extension which uses OkHttp3) resolved all.

OkHttp3 has its own cookie implementation and requires a custom cookie store implementing the `CookieJar` interface. There is no built-in CookieJar implementation (yet?).

**Comment by swratten** [comment]
@brillenheini Is this still valid? I am looking into getting the latest version of ExoPlayer into our app and we are using Akamai Token authentication on the server, I cant seem to find any solutions online except this thread.

**Comment by brillenheini** [comment]
@swratten I am still using ExoPlayer 1 for this but it should work with the latest version as well using the OkHttp extension.

**Comment by swratten** [comment]
@brillenheini thanks for the advice, have you got any code examples on how to get this working? Even with Exoplayer 1. The current okhttpdatasource in the exoplayer extension expects a Call.Factory in its constructor, I have no idea what to do with that or how to get a reference to one?
