### ISSUE TITLE
What is ExoPlayer's buffering speed?

### ISSUE THREAD

**Issue by francois-cabrol** [google/ExoPlayer#6250]
Hi,

I am trying to simulate a fleet of ExoPlayer-based video players streaming MPEG-DASH streams from the same set of servers, for a performance study.
I am familiar with how the **DefaultLoadControl** works (and [this video](https://www.youtube.com/watch?v=jAZn-J1I8Eg&feature=youtu.be&t=25m1s) helped a lot), but I have no idea about the size of the chunks requested from the server while buffering. Does ExoPlayer immediately try to get **minBufferMs** bytes in one HTTP request at startup, for example? Or does it send several smaller requests? What algorithm (or series of algorithms) determines at what speed the buffer is filled? Is it the same behavior during normal playback? After a seekTo()?

Also, what are the variables this buffering rate depends on? Does ExoPlayer use information from the MPD manifest for example?

What class should I investigate in order to understand more?

Thank you very much!

**Comment by ojw28** [comment]
> I have no idea about the size of the chunks requested from the server while buffering

For DASH, the chunk size is a property of the media, not ExoPlayer. So it depends on the content. ExoPlayer will request one chunk at a time for video, and (in parallel) one chunk at a time for audio, with some logic in place to stop one loading too far ahead of the other. Whilst the buffer is being filled, the player will download each chunk as quickly as possible, and the request for the next chunk will be made as soon as the request for the previous chunk is completed.

If you want to understand what requests are being made, you'd probably be best off sniffing the network connection and looking at what happens. Using the [OkHttp extension with Stetho](https://medium.com/google-exoplayer/enabling-stetho-on-exoplayer-2-demo-application-126807a37cb3) is one good way of doing this. It looks like Android Studio's profiling tools also provide support for [inspecting network traffic](https://developer.android.com/studio/profile/network-profiler).

**Comment by francois-cabrol** [comment]
Thank you very much!
