### ISSUE TITLE
How to install the Demo apk using the Android studio ( Error is shown even the previous apk is removed manually )

### ISSUE THREAD

**Issue by himaswetha** [google/ExoPlayer#6251]
### [REQUIRED] Searched documentation and issues
Searched in github didnt get any related questions 

### [REQUIRED] Question
How to install the demo apk using the Android studio. Error when installing the Exoplayer demo apk (Even the demo apk is already removed its still showing the error)

### A full bug report captured from the device
 Launching demo
$ adb push /Users/demo-noExtensions-debug.apk /data/local/tmp/com.google.android.exoplayer2.demo
$ adb shell pm install -t -r "/data/local/tmp/com.google.android.exoplayer2.demo"
Failure [INSTALL_FAILED_UPDATE_INCOMPATIBLE: Package com.google.android.exoplayer2.demo signatures do not match the previously installed version; ignoring!]
$ adb shell pm uninstall com.google.android.exoplayer2.demo
DELETE_FAILED_INTERNAL_ERROR
Error while Installing APK

### Link to test content
Not required

**Comment by baechinger** [comment]
Seems like like the app is installed on the device already. 

I thought Android Studio could handle this. Android Studio usually ask me whether it is ok to uninstall the former version. Can you try uninstall the app on the device manually and do the adb commands again?

**Comment by himaswetha** [comment]
Tried the commands manually also. Also the Exoplayer is not visible in Apps it means already the Exoplayer was uninstalled. So I can see that apk is already uninstalled but still getting the same error. Tried forceful methods also to install the apk but still getting the same error.

**Comment by baechinger** [comment]
You see the package when doing?

```
adb shell pm list packages -f | grep exoplayer
```

That's odd. Not a very sophisticated response of me, but I guess you already restarted the device?

**Comment by himaswetha** [comment]
Following is the output from my machine
 adb shell pm list packages -f | grep exoplayer
package:/system/priv-app/ArcChecker/ArcChecker.apk=com.google.android.exoplayer2.demo

adb uninstall com.google.android.exoplayer2.demo
Failure [DELETE_FAILED_INTERNAL_ERROR]


Can you please send me the detail steps to uninstall and install the demo apk?
Tried following ways
adb root
adb remount
adb uninstall com.google.android.exoplayer2.demo
adb reboot
adb push demo.apk
adb install demo.apk

**Comment by baechinger** [comment]
> Failure [DELETE_FAILED_INTERNAL_ERROR]

I don't think you need to uninstall because I think you never installed it successfully.  I also get this failure when I try to uninstall an apk which is not installed, like

```
adb uninstall does.not.exist
```

Installing is just the following:

```
adb install -r demo-noExtensions-debug.apk 
```

I don't think you need to push command as you listed above. (see [adb install](http://adbshell.com/commands/adb-install))

**Comment by himaswetha** [comment]
So if apk is not installed and packages are not there then even adb install
is showing the error. Then that case how we can install?

**Comment by ojw28** [comment]
This doesn't really sound like an ExoPlayer issue. It sounds like you have a problem installing apks on your device, for which StackOverflow is probably a better place to ask for help.

If it's specific to the ExoPlayer demo app then I think you must have done something strange to have ended up in this state, such as trying to push the demo app into the system partition or something. You should never need `adb root` to install the ExoPlayer demo app, and if you tried to do something that needed it, you might have done something that you probably shouldn't have done. If this is a test device then I'd suggest you re-flash it to make sure the system partition is in the correct state. Then use `adb install -r demo-noExtensions-debug.apk` going forward.
