### ISSUE TITLE
new TrackSelection not updated in HlsChunkSource

### ISSUE THREAD

**Issue by stevemayhew** [google/ExoPlayer#6256]
### Issue description
When playing back adaptive HLS content if you change the playback speed the `AdaptiveTrackSelection` should level down to a lower bitrate track to avoid stalls, it does not because the `playbackSpeed` update is missed since the `HlsChunkSource` that calls this method references a stale `TrackSelection`.  

The code that handles this is:

```Java
  @SuppressWarnings("unused")
  protected boolean canSelectFormat(
      Format format, int trackBitrate, float playbackSpeed, long effectiveBitrate) {
    return Math.round(trackBitrate * playbackSpeed) <= effectiveBitrate;
  }
```

### Reproduction steps
Playback using any HLS content (I used the Mango Open Source video: https://mango.blender.org, I'll email an S3 bucket with an HLS version of this).  Then:

1. Disable the audio track
2. Print or observer with a debugger the `TrackSelection` object reference in `HlsChunkSource`, it should change to match that in `MediaPeriodHolder`

### Triage 
This is easy to reproduce by just disabling the audio track.  This forces a invalidate (`TrackSelector.invalidate()` called).  The invalidate creates a new `AdaptiveTrackSelection` object, via `TrackSelection.Factory.createTrackSelection()`

The updated `TrackSelection` instance is stored in the `MediaPeriodHolder` but not updated in the `HlsChunkSource`.  This is because of logic to avoid re-creating the SampleStream (a good thing) in `HlsSampleStreamWrapper`

### Link to test content
Mango Open Source - Tears of Steel (I'll send a link)

### A full bug report captured from the device
I'll send it, probably useless though, the issue is a logic issue not platform specific.

### Version of ExoPlayer being used
dev-v2-r2.10.3 - 1275217bca00184d52f0c374d59db985ebf070c1

### Device(s) and version(s) of Android being used
Evolution IPA-1104HDH-01.  SDK 26

**Comment by tonihei** [comment]
Thanks for reporting. It looks this bug also affects other streaming types where we save a reference to the TrackSelection (e.g. DASH).

**Comment by stevemayhew** [comment]
You're more than welcome!  Here's a proposed fix that is working for me locally:  https://github.com/stevemayhew/ExoPlayer/commit/ddfaa97c952e944cca49f6f5bd1700599bda3c4f

I am working from dev-v2-r2.10.3 so it will not directly merge with a pull.   

I looked to write a test case, but that would entail building out test cases for the whole of `HlsSampleStreamWrapper`.  We can talk about that project later if it's a worthy undertaking (lots of big methods would need to be split up to make the logic more testable, a bigger job then I would attempt with my experience current experience with the class).

If this is good, I'll move the change to base off dev-v2 and submit it as a pull.

**Comment by tonihei** [comment]
Thanks for the proposal. I re-implemented this in a slightly different way to move the update further down where we keep the streams.

**Comment by stevemayhew** [comment]
Cool, thanks.  I’ll look for the change and test it.

**Comment by ojw28** [comment]
Fix merged into `dev-v2` and `dev-v2-r2.10.4`. If you could give it a quick test, that would be great.

**Comment by stevemayhew** [comment]
I’ll do it tomorrow, planning to move our branch forward from 2.10.3
anyway.

The iFrame playlist parsing is ready to push a branch too, our CI is in the
queue
