### ISSUE TITLE
how to show Video player notification when video is in background

### ISSUE THREAD

**Issue by RavanaAbhi** [google/ExoPlayer#6258]
my video is playing in Exoplayer and when i click on home then the video is play like audio in notification. how can i do that using Exoplayer?

**Comment by ojw28** [comment]
You need to put the player inside an Android `Service` to ensure that it stays alive. When your activity goes into the background you should detach it from whatever UI component it's holding. So for example, if you're using `PlayerView`, you should call `playerView.setPlayer(null)`. When the activity comes back into the foreground, re-attach the UI component.
