### ISSUE TITLE
Is there a way to prefetch the video content based on device capacity without decoder initialisation?

### ISSUE THREAD

**Issue by manishPatwari** [google/ExoPlayer#6259]
### [REQUIRED] Searched documentation and issues
Did a search in Google and didn't find any relevant answere.

### [REQUIRED] Question

We need to show video in Viewpage and whenever user switches the video we need to play it immediately. Hence currently I do prepare the video player, which is allocating decoder also and resulting in exceeding the allowed decoder count (  com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: ).

So, can I still pre-download the video files based on the device capacity (like decoder, screen density, bandwidth, etc) and avoid decoder allocation.

**Comment by manishPatwari** [comment]
@ojw28  Please help me with some solution.

**Comment by ojw28** [comment]
This is not currently supported, I'm afraid.
