### ISSUE TITLE
Function player.getVideoFormat().frameRate yields null reference, when is it ready?

### ISSUE THREAD

**Issue by Schizo** [google/ExoPlayer#626]
To retrieve the frameRate i am calling the getVideoFormat() Function when the Movie is in the ready state, expecting that the MetaData is available at this time. But it yields

```Attempt to read from field 'float com.google.android.exoplayer.chunk.Format.frameRate' on a null object reference```

*Code where i am calling the function:*
```
case ExoPlayer.STATE_READY:
player.getVideoFormat().frameRate
````

When do i have to call the function to make sure its ready to read?

**Comment by ojw28** [comment]
You should wait for `InfoListener.onVideoFormatEnabled` to be called before retrieving the format. You can figure most of these questions out by spending a couple of minutes reading the source.

**Comment by Schizo** [comment]
I am asking because  the implemented Method onVideoFormatEnabled in EventLogger.java  is not triggering? Shouldn't this function get called when a video is playing/played ? (I am talking about the demo exoplayer example from github)

```
   @Override
  public void onVideoFormatEnabled(Format format, int trigger, int mediaTimeMs) {
    Log.d(TAG, "videoFormat [" + getSessionTimeString() + ", " + format.id + ", "
        + Integer.toString(trigger) + "]");
  }
```
