### ISSUE TITLE
PlayerView.toggleControllerVisibility() has a bug on version 2.10.3

### ISSUE THREAD

**Issue by brucewuu520** [google/ExoPlayer#6260]
Version: 2.10.3

when i not use default PlayerControlView，when click PlayerView application is error
error log:
 com.google.android.exoplayer2.ui.PlayerView.toggleControllerVisibility(PlayerView.java:1156)
        at com.google.android.exoplayer2.ui.PlayerView.performClick(PlayerView.java:1075)

in PlayerView method：

   private boolean toggleControllerVisibility() {
    if (!controller.isVisible()) {
      maybeShowController(true);
    } else if (controllerHideOnTouch) {
      controller.hide();
    }
    return true;
  }

has not check useController

but in version 2.10.2：

   private boolean toggleControllerVisibility() {
    if (!useController || player == null) {
      return false;
    }
    if (!controller.isVisible()) {
      maybeShowController(true);
    } else if (controllerHideOnTouch) {
      controller.hide();
    }
    return true;
  }

**Comment by tonihei** [comment]
Thanks for reporting. Looks like we don't check for custom controller when performClick is called directly.
