### ISSUE TITLE
Publish testutil package via jCenter

### ISSUE THREAD

**Issue by rcavaltw** [google/ExoPlayer#6267]
### [REQUIRED] Searched documentation and issues
This question is a follow up to #3810.

### [REQUIRED] Question
We are developing a lib that wraps around exoplayer. It is somewhat hard to write unit test for `Player.EventListener`, for example, without loading a real video, thread sleeping, etc. From #3810 I noticed there's a way to emulate portions of exoplayers's behavior and was wondering if the way to go would be for us to just copy your testutil classes or if there are plans to expose them as actual testing libs, analogous to spring-test, that provides helpers and stubs for http function.

**Comment by tonihei** [comment]
I don't see anything speaking against publishing these modules as they are. 

Note that we are unlikely to provide new features just for testing external usages though. If you want to get started on unit tests involving the full player, please have a look at [ExoPlayerTest](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/test/java/com/google/android/exoplayer2/ExoPlayerTest.java) for example, which uses [ExoPlayerTestRunner](https://github.com/google/ExoPlayer/blob/release-v2/testutils/src/main/java/com/google/android/exoplayer2/testutil/ExoPlayerTestRunner.java).

**Comment by tonihei** [comment]
Code prepared for publication. I leave this issue open until we actually ensured it's available on jCenter

**Comment by ojw28** [comment]
This has been requested (for `2.11.0`). It's pending approval, and will hopefully be available soon.
