### ISSUE TITLE
demo app can not detect error when use DefaultProguardFile "proguard-android-optimize.txt" and gradle:3.4.2

### ISSUE THREAD

**Issue by rishun-fsi** [google/ExoPlayer#6268]
When I change some settings as following, then run the release demo app, the error never called on airplane mode.
Could you explain what happens when I use "proguard-android-optimize.txt" or changes gradle:3.4.0 to gradle:3.4.2?

1)use the lastest release
51acd8150 (HEAD -> release-v2, tag: r2.10.3)

2)changes demos/main/build.gradle
release {
    shrinkResources true
    minifyEnabled true
    useProguard true // added
    proguardFiles = [
        "proguard-rules.txt",
        getDefaultProguardFile('proguard-android-optimize.txt') // modified
    ]
}

3)changes Exoplayer/build.gradle
dependencies {
    classpath 'com.android.tools.build:gradle:3.4.2' // modified
    classpath 'com.novoda:bintray-release:0.9'
    classpath 'com.google.android.gms:strict-version-matcher-plugin:1.1.0'
}

4)build release apk

5)test device : emulator (Pixel 2)

6-1) test the demo app (set DefaultProguardFile "proguard-android-optimize.txt" and gradle:3.4.2)
a) trun on airplane mode
b) launch demo app
c) tap 「YouTube DASH」
d) tap 「Google Glass (MP4,H264)」
e) 「Playback failed」 error message not show  (Issue happens)

6-2) test the demo app (set DefaultProguardFile "proguard-android.txt" and gradle:3.4.2)
a) trun on airplane mode
b) launch demo app
c) tap 「YouTube DASH」
d) tap 「Google Glass (MP4,H264)」
e) 「Playback failed」 error message showed  (OK)

6-3) test the demo app (set DefaultProguardFile "proguard-android-optimize.txt" and gradle:3.4.0)
a) trun on airplane mode
b) launch demo app
c) tap 「YouTube DASH」
d) tap 「Google Glass (MP4,H264)」
e) 「Playback failed」 error message showed  (OK)

7)happens real device and emulator

**Comment by ojw28** [comment]
`useProguard` is deprecated and replaced by `minifyEnabled`, which is already in `demos/main/build.gradle`. Does everything work fine if you remove the `useProguard true` line that you've added? If so then that's the correct solution.

Note that from 3.5.0 of the gradle plugin, `useProguard` will [start being ignored even if you set it](https://androidstudio.googleblog.com/2019/04/android-studio-35-canary-12-available.html).

**Comment by rishun-fsi** [comment]
I think this is not a good solution, because I want use proguard-rules.txt (In my case for some reason I need use proguard-rules.txt). If I remove  "useProguard true",  ProGuard does not work.
Please see the following different build logs.
And another question is why demo app use proguard-android.txt instead of proguard-android-optimize.txt? Did it on purpose?

$ ./gradlew assemblenoExtensionsRelease ( remove "useProguard true")
---------------------------------------------------------------------
...

R8 is the new Android code shrinker. If you experience any issues, please file a bug at
https://issuetracker.google.com, using 'Shrinker (R8)' as component name. You can
disable R8 by updating gradle.properties with 'android.enableR8=false'.
Current version is: 1.4.94 (build 390954928f0db9c3b888a367f7f128ce3bbfb160 from go/r8bot (luci-r8-ci-archive-0-5g74)).


D8: The rule `-keep public class * extends androidx.versionedparcelable.VersionedParcelable {
  <init>();
}` uses extends but actually matches implements.
C:\share\ExoPlayer2\library\core\buildout\intermediates\runtime_library_classes\release\classes.jar: D8: Type `com.google.android.exoplayer2.upstream.cache.ContentMetadata$-CC` was not found, it is required for default or static interface methods desugaring of `long com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(com.google.android.exoplayer2.upstream.DataSpec)`
D8: synthesized for lambda desugaring: Type `com.google.android.exoplayer2.trackselection.TrackBitrateEstimator$-CC` was not found, it is required for default or static interface methods desugaring of `int[] com.google.android.exoplayer2.trackselection.-$$Lambda$TrackBitrateEstimator$2lQ5lBvmOkJuNPw2qehuzXBInmI.getBitrates(com.google.android.exoplayer2.Format[], java.util.List, com.google.android.exoplayer2.source.chunk.MediaChunkIterator[], int[])`
D8: synthesized for lambda desugaring: Type `com.google.android.exoplayer2.trackselection.TrackSelection$Factory$-CC` was not found, it is required for default or static interface methods desugaring of `com.google.android.exoplayer2.trackselection.TrackSelection com.google.android.exoplayer2.trackselection.-$$Lambda$TrackSelection$Factory$9mnNWe-5kFFae0E_IiLXrOzpdtA.createAdaptiveTrackSelection(com.google.android.exoplayer2.trackselection.TrackSelection$Definition)`
D8: synthesized for lambda desugaring: Type `com.google.android.exoplayer2.upstream.HttpDataSource$-CC` was not found, it is required for default or static interface methods desugaring of `boolean com.google.android.exoplayer2.upstream.-$$Lambda$HttpDataSource$fz-i4cgBB9tTB1JUdq8hmlAPFIw.evaluate(java.lang.Object)`
Removed unused resources: Binary resource data reduced from 879KB to 845KB: Removed 3%

...
---------------------------------------------------------------------




$ ./gradlew assemblenoExtensionsRelease (add "useProguard true")
---------------------------------------------------------------------

...

ProGuard, version 6.0.3
Reading input...
Reading program jar [C:\Users\rishun\.gradle\caches\transforms-2\files-2.1\cc2b4f0ecb05aef6cf29f250c742f16e\jars\classes.jar] (filtered)
Reading program jar [C:\Users\rishun\.gradle\caches\transforms-2\files-2.1\6177a452d3a7553497b3717fe4ae44df\jars\classes.jar] (filtered)
Reading program jar [C:\Users\rishun\.gradle\caches\transforms-2\files-2.1\9325563ba0338a4b5957e4334ea38bab\jars\classes.jar] (filtered)
Reading program jar [C:\Users\rishun\.gradle\caches\transforms-2\files-2.1\7c7b15c5617c8c6661154c3f6b705a9b\jars\classes.jar] (filtered)
Reading program jar [C:\Users\rishun\.gradle\caches\transforms-2\files-2.1\93b529dc4d7ff1f20a783220903c6c23\jars\classes.jar] (filtered)
Reading program jar [C:\Users\rishun\.gradle\caches\transforms-2\files-2.1\80a4d2269dd2c1357181d2cf74665a03\jars\classes.jar] (filtered)
Reading program jar [C:\Users\rishun\.gradle\caches\transforms-2\files-2.1\06c2b322ba8cd281310c3959e42d8793\jars\classes.jar] (filtered)
Reading program jar [C:\Users\rishun\.gradle\caches\transforms-2\files-2.1\3564b17f767616fbaf7ba5fd87d90382\jars\classes.jar] (filtered)
Reading program jar [C:\Users\rishun\.gradle\caches\transforms-2\files-2.1\96c64f5181edf51c7639d8ae5630801a\jars\classes.jar] (filtered)
Reading program jar [C:\Users\rishun\.gradle\caches\transforms-2\files-2.1\25296829ea2ecd05457d044cefa9304f\jars\classes.jar] (filtered)
Reading program jar [C:\Users\rishun\.gradle\caches\transforms-2\files-2.1\9df4cfed3781459305a5bc1043a1ecf9\jars\classes.jar] (filtered)
Reading program jar [C:\Users\rishun\.gradle\caches\transforms-2\files-2.1\2b702c1cc47c2bbc766de84bd40f0c3e\jars\classes.jar] (filtered)
Reading program jar [C:\Users\rishun\.gradle\caches\transforms-2\files-2.1\7a2a8a5f05f1565a12cf3c8665abd32a\jars\classes.jar] (filtered)
Reading program jar [C:\Users\rishun\.gradle\caches\transforms-2\files-2.1\bb1df735a949508a91942f91e7d61e18\jars\classes.jar] (filtered)
Reading program jar [C:\Users\rishun\.gradle\caches\transforms-2\files-2.1\87664b825ad2ecee0d5acd5b4081567e\jars\classes.jar] (filtered)
Reading program jar [C:\Users\rishun\.gradle\caches\transforms-2\files-2.1\bca7378a2a0a6e4080f893e06403d64d\jars\classes.jar] (filtered)
Reading program jar [C:\Users\rishun\.gradle\caches\transforms-2\files-2.1\d5f70466d74f1b90cfbc97020a666bb4\jars\classes.jar] (filtered)
Reading program jar [C:\Users\rishun\.gradle\caches\transforms-2\files-2.1\acb2cf6f1acbf69c5666006b59a944af\jars\classes.jar] (filtered)
Reading program jar [C:\Users\rishun\.gradle\caches\transforms-2\files-2.1\4ba8b455543be9bda04cf9246d4e90b9\jars\classes.jar] (filtered)
Reading program jar [C:\Users\rishun\.gradle\caches\transforms-2\files-2.1\6fdfd14ed2a637944a768f5e67acfb32\jars\classes.jar] (filtered)
Reading program jar [C:\Users\rishun\.gradle\caches\transforms-2\files-2.1\7305a870e671cfe74869e7f2dea8d5bb\jars\classes.jar] (filtered)
Reading program jar [C:\Users\rishun\.gradle\caches\transforms-2\files-2.1\22e0432bd512e2f5af2bb016066e5e5b\jars\classes.jar] (filtered)
Reading program jar [C:\Users\rishun\.gradle\caches\transforms-2\files-2.1\6e20019893d20f820c3ca51da13df7d4\jars\classes.jar] (filtered)
Reading program jar [C:\Users\rishun\.gradle\caches\transforms-2\files-2.1\2d4e34b88838a97b85d3c79b5d5ee32e\jars\classes.jar] (filtered)
Reading program jar [C:\Users\rishun\.gradle\caches\modules-2\files-2.1\androidx.collection\collection\1.0.0\42858b26cafdaa69b6149f45dfc2894007bc2c7a\collection-1.0.0.jar] (filtered)
Reading program jar [C:\Users\rishun\.gradle\caches\transforms-2\files-2.1\81e8d3e319fd8392c69e9795a8d8d45e\jars\classes.jar] (filtered)
Reading program jar [C:\Users\rishun\.gradle\caches\transforms-2\files-2.1\2ba167ab5a0739c06e27920985080545\jars\classes.jar] (filtered)
Reading program jar [C:\Users\rishun\.gradle\caches\transforms-2\files-2.1\75c004ebffe3dc740a846e9a929bb870\jars\classes.jar] (filtered)
Reading program jar [C:\Users\rishun\.gradle\caches\transforms-2\files-2.1\e9b70126ba88cc821745fc027a6230a8\jars\classes.jar] (filtered)
Reading program jar [C:\Users\rishun\.gradle\caches\transforms-2\files-2.1\1f731fca9a38ee288fcb52ba42a6768f\jars\classes.jar] (filtered)
Reading program jar [C:\Users\rishun\.gradle\caches\transforms-2\files-2.1\f72fd84a64a52327144b6d78e0973839\jars\classes.jar] (filtered)
Reading program jar [C:\Users\rishun\.gradle\caches\transforms-2\files-2.1\cc1450f990273a5357397d4194394645\jars\classes.jar] (filtered)
Reading program jar [C:\Users\rishun\.gradle\caches\modules-2\files-2.1\androidx.arch.core\core-common\2.0.0\bb21b9a11761451b51624ac428d1f1bb5deeac38\core-common-2.0.0.jar] (filtered)
Reading program jar [C:\Users\rishun\.gradle\caches\modules-2\files-2.1\androidx.lifecycle\lifecycle-common\2.0.0\e070ffae07452331bc5684734fce6831d531785c\lifecycle-common-2.0.0.jar] (filtered)
Reading program jar [C:\Users\rishun\.gradle\caches\modules-2\files-2.1\androidx.annotation\annotation\1.0.2\2f1d597d48e5309e935ce1212eedf5ae69d3f97\annotation-1.0.2.jar] (filtered)
Reading program jar [C:\share\ExoPlayer2\library\dash\buildout\intermediates\runtime_library_classes\release\classes.jar] (filtered)
Reading program jar [C:\share\ExoPlayer2\library\hls\buildout\intermediates\runtime_library_classes\release\classes.jar] (filtered)
Reading program jar [C:\share\ExoPlayer2\library\smoothstreaming\buildout\intermediates\runtime_library_classes\release\classes.jar] (filtered)
Reading program jar [C:\share\ExoPlayer2\library\ui\buildout\intermediates\runtime_library_classes\release\classes.jar] (filtered)
Reading program jar [C:\share\ExoPlayer2\library\core\buildout\intermediates\runtime_library_classes\release\classes.jar] (filtered)
Reading program directory [C:\share\ExoPlayer2\demos\main\buildout\intermediates\javac\noExtensionsRelease\compileNoExtensionsReleaseJavaWithJavac\classes] (filtered)
Reading program jar [C:\share\ExoPlayer2\demos\main\buildout\intermediates\transforms\mergeJavaRes\noExtensions\release\0.jar] (filtered)
Reading library jar [C:\Users\rishun\AppData\Local\Android\Sdk\platforms\android-28\android.jar]
Reading library jar [C:\Users\rishun\AppData\Local\Android\Sdk\build-tools\28.0.3\core-lambda-stubs.jar]
Reading library jar [C:\Users\rishun\AppData\Local\Android\Sdk\platforms\android-28\optional\org.apache.http.legacy.jar]
Reading library jar [C:\Users\rishun\AppData\Local\Android\Sdk\platforms\android-28\optional\android.test.mock.jar]
Reading library jar [C:\Users\rishun\AppData\Local\Android\Sdk\platforms\android-28\optional\android.test.base.jar]
Reading library jar [C:\Users\rishun\AppData\Local\Android\Sdk\platforms\android-28\optional\android.test.runner.jar]
Initializing...
Note: com.google.android.exoplayer2.util.Util: can't find dynamically referenced class android.os.SystemProperties
Note: the configuration keeps the entry point 'com.google.android.exoplayer2.offline.SegmentDownloader { SegmentDownloader(android.net.Uri,java.util.List,com.google.android.exoplayer2.offline.DownloaderConstructorHelper); }', but not the descriptor class 'com.google.android.exoplayer2.offline.DownloaderConstructorHelper'
Note: the configuration keeps the entry point 'com.google.android.exoplayer2.ui.AspectRatioFrameLayout { void setAspectRatioListener(com.google.android.exoplayer2.ui.AspectRatioFrameLayout$AspectRatioListener); }', but not the descriptor class 'com.google.android.exoplayer2.ui.AspectRatioFrameLayout$AspectRatioListener'
Note: the configuration keeps the entry point 'com.google.android.exoplayer2.ui.PlayerControlView { void setPlayer(com.google.android.exoplayer2.Player); }', but not the descriptor class 'com.google.android.exoplayer2.Player'
Note: the configuration keeps the entry point 'com.google.android.exoplayer2.ui.PlayerControlView { void setVisibilityListener(com.google.android.exoplayer2.ui.PlayerControlView$VisibilityListener); }', but not the descriptor class 'com.google.android.exoplayer2.ui.PlayerControlView$VisibilityListener'
Note: the configuration keeps the entry point 'com.google.android.exoplayer2.ui.PlayerControlView { void setProgressUpdateListener(com.google.android.exoplayer2.ui.PlayerControlView$ProgressUpdateListener); }', but not the descriptor class 'com.google.android.exoplayer2.ui.PlayerControlView$ProgressUpdateListener'
Note: the configuration keeps the entry point 'com.google.android.exoplayer2.ui.PlayerControlView { void setPlaybackPreparer(com.google.android.exoplayer2.PlaybackPreparer); }', but not the descriptor class 'com.google.android.exoplayer2.PlaybackPreparer'
Note: the configuration keeps the entry point 'com.google.android.exoplayer2.ui.PlayerControlView { void setControlDispatcher(com.google.android.exoplayer2.ControlDispatcher); }', but not the descriptor class 'com.google.android.exoplayer2.ControlDispatcher'
Note: the configuration keeps the entry point 'com.google.android.exoplayer2.ui.PlayerView { void setPlayer(com.google.android.exoplayer2.Player); }', but not the descriptor class 'com.google.android.exoplayer2.Player'
Note: the configuration keeps the entry point 'com.google.android.exoplayer2.ui.PlayerView { void setErrorMessageProvider(com.google.android.exoplayer2.util.ErrorMessageProvider); }', but not the descriptor class 'com.google.android.exoplayer2.util.ErrorMessageProvider'
Note: the configuration keeps the entry point 'com.google.android.exoplayer2.ui.PlayerView { void setControllerVisibilityListener(com.google.android.exoplayer2.ui.PlayerControlView$VisibilityListener); }', but not the descriptor class 'com.google.android.exoplayer2.ui.PlayerControlView$VisibilityListener'
Note: the configuration keeps the entry point 'com.google.android.exoplayer2.ui.PlayerView { void setPlaybackPreparer(com.google.android.exoplayer2.PlaybackPreparer); }', but not the descriptor class 'com.google.android.exoplayer2.PlaybackPreparer'
Note: the configuration keeps the entry point 'com.google.android.exoplayer2.ui.PlayerView { void setControlDispatcher(com.google.android.exoplayer2.ControlDispatcher); }', but not the descriptor class 'com.google.android.exoplayer2.ControlDispatcher'
Note: the configuration keeps the entry point 'com.google.android.exoplayer2.ui.PlayerView { void setAspectRatioListener(com.google.android.exoplayer2.ui.AspectRatioFrameLayout$AspectRatioListener); }', but not the descriptor class 'com.google.android.exoplayer2.ui.AspectRatioFrameLayout$AspectRatioListener'
Note: the configuration keeps the entry point 'com.google.android.exoplayer2.ui.SubtitleView { void setStyle(com.google.android.exoplayer2.text.CaptionStyleCompat); }', but not the descriptor class 'com.google.android.exoplayer2.text.CaptionStyleCompat'
Note: the configuration keeps the entry point 'com.google.android.exoplayer2.ui.TrackSelectionView { void setTrackNameProvider(com.google.android.exoplayer2.ui.TrackNameProvider); }', but not the descriptor class 'com.google.android.exoplayer2.ui.TrackNameProvider'
Note: the configuration keeps the entry point 'com.google.android.exoplayer2.ui.spherical.SphericalSurfaceView { void setVideoComponent(com.google.android.exoplayer2.Player$VideoComponent); }', but not the descriptor class 'com.google.android.exoplayer2.Player$VideoComponent'
Note: the configuration keeps the entry point 'com.google.android.exoplayer2.ui.spherical.SphericalSurfaceView { void setSingleTapListener(com.google.android.exoplayer2.ui.spherical.SingleTapListener); }', but not the descriptor class 'com.google.android.exoplayer2.ui.spherical.SingleTapListener'
Note: the configuration keeps the entry point 'com.google.android.material.bottomnavigation.BottomNavigationMenuView { void setPresenter(com.google.android.material.bottomnavigation.BottomNavigationPresenter); }', but not the descriptor class 'com.google.android.material.bottomnavigation.BottomNavigationPresenter'
Note: the configuration keeps the entry point 'com.google.android.material.bottomnavigation.BottomNavigationView { void setOnNavigationItemSelectedListener(com.google.android.material.bottomnavigation.BottomNavigationView$OnNavigationItemSelectedListener); }', but not the descriptor class 'com.google.android.material.bottomnavigation.BottomNavigationView$OnNavigationItemSelectedListener'
Note: the configuration keeps the entry point 'com.google.android.material.bottomnavigation.BottomNavigationView { void setOnNavigationItemReselectedListener(com.google.android.material.bottomnavigation.BottomNavigationView$OnNavigationItemReselectedListener); }', but not the descriptor class 'com.google.android.material.bottomnavigation.BottomNavigationView$OnNavigationItemReselectedListener'
Note: the configuration keeps the entry point 'com.google.android.material.chip.Chip { void setChipDrawable(com.google.android.material.chip.ChipDrawable); }', but not the descriptor class 'com.google.android.material.chip.ChipDrawable'
Note: the configuration keeps the entry point 'com.google.android.material.chip.Chip { void setTextAppearance(com.google.android.material.resources.TextAppearance); }', but not the descriptor class 'com.google.android.material.resources.TextAppearance'
Note: the configuration keeps the entry point 'com.google.android.material.chip.Chip { void setShowMotionSpec(com.google.android.material.animation.MotionSpec); }', but not the descriptor class 'com.google.android.material.animation.MotionSpec'
Note: the configuration keeps the entry point 'com.google.android.material.chip.Chip { void setHideMotionSpec(com.google.android.material.animation.MotionSpec); }', but not the descriptor class 'com.google.android.material.animation.MotionSpec'
Note: the configuration keeps the entry point 'com.google.android.material.chip.ChipGroup { void setOnCheckedChangeListener(com.google.android.material.chip.ChipGroup$OnCheckedChangeListener); }', but not the descriptor class 'com.google.android.material.chip.ChipGroup$OnCheckedChangeListener'
Note: the configuration keeps the entry point 'com.google.android.material.circularreveal.CircularRevealFrameLayout { void setRevealInfo(com.google.android.material.circularreveal.CircularRevealWidget$RevealInfo); }', but not the descriptor class 'com.google.android.material.circularreveal.CircularRevealWidget$RevealInfo'
Note: the configuration keeps the entry point 'com.google.android.material.circularreveal.CircularRevealGridLayout { void setRevealInfo(com.google.android.material.circularreveal.CircularRevealWidget$RevealInfo); }', but not the descriptor class 'com.google.android.material.circularreveal.CircularRevealWidget$RevealInfo'
Note: the configuration keeps the entry point 'com.google.android.material.circularreveal.CircularRevealLinearLayout { void setRevealInfo(com.google.android.material.circularreveal.CircularRevealWidget$RevealInfo); }', but not the descriptor class 'com.google.android.material.circularreveal.CircularRevealWidget$RevealInfo'
Note: the configuration keeps the entry point 'com.google.android.material.circularreveal.CircularRevealRelativeLayout { void setRevealInfo(com.google.android.material.circularreveal.CircularRevealWidget$RevealInfo); }', but not the descriptor class 'com.google.android.material.circularreveal.CircularRevealWidget$RevealInfo'
Note: the configuration keeps the entry point 'com.google.android.material.circularreveal.cardview.CircularRevealCardView { void setRevealInfo(com.google.android.material.circularreveal.CircularRevealWidget$RevealInfo); }', but not the descriptor class 'com.google.android.material.circularreveal.CircularRevealWidget$RevealInfo'
Note: the configuration keeps the entry point 'com.google.android.material.circularreveal.coordinatorlayout.CircularRevealCoordinatorLayout { void setRevealInfo(com.google.android.material.circularreveal.CircularRevealWidget$RevealInfo); }', but not the descriptor class 'com.google.android.material.circularreveal.CircularRevealWidget$RevealInfo'
Note: the configuration keeps the entry point 'com.google.android.material.floatingactionbutton.FloatingActionButton { void setShowMotionSpec(com.google.android.material.animation.MotionSpec); }', but not the descriptor class 'com.google.android.material.animation.MotionSpec'
Note: the configuration keeps the entry point 'com.google.android.material.floatingactionbutton.FloatingActionButton { void setHideMotionSpec(com.google.android.material.animation.MotionSpec); }', but not the descriptor class 'com.google.android.material.animation.MotionSpec'
Note: the configuration keeps the entry point 'com.google.android.material.navigation.NavigationView { void setNavigationItemSelectedListener(com.google.android.material.navigation.NavigationView$OnNavigationItemSelectedListener); }', but not the descriptor class 'com.google.android.material.navigation.NavigationView$OnNavigationItemSelectedListener'
Note: the configuration keeps the entry point 'com.google.android.material.snackbar.BaseTransientBottomBar$SnackbarBaseLayout { void setOnLayoutChangeListener(com.google.android.material.snackbar.BaseTransientBottomBar$OnLayoutChangeListener); }', but not the descriptor class 'com.google.android.material.snackbar.BaseTransientBottomBar$OnLayoutChangeListener'
Note: the configuration keeps the entry point 'com.google.android.material.snackbar.BaseTransientBottomBar$SnackbarBaseLayout { void setOnAttachStateChangeListener(com.google.android.material.snackbar.BaseTransientBottomBar$OnAttachStateChangeListener); }', but not the descriptor class 'com.google.android.material.snackbar.BaseTransientBottomBar$OnAttachStateChangeListener'
Note: the configuration keeps the entry point 'com.google.android.material.tabs.TabLayout { void setOnTabSelectedListener(com.google.android.material.tabs.TabLayout$BaseOnTabSelectedListener); }', but not the descriptor class 'com.google.android.material.tabs.TabLayout$BaseOnTabSelectedListener'
Note: the configuration keeps the entry point 'com.google.android.material.textfield.TextInputLayout { void setTextInputAccessibilityDelegate(com.google.android.material.textfield.TextInputLayout$AccessibilityDelegate); }', but not the descriptor class 'com.google.android.material.textfield.TextInputLayout$AccessibilityDelegate'
Note: there were 38 unkept descriptor classes in kept class members.
      You should consider explicitly keeping the mentioned classes
      (using '-keep').
      (http://proguard.sourceforge.net/manual/troubleshooting.html#descriptorclass)
Note: there were 1 unresolved dynamic references to classes or interfaces.
      You should check if you need to specify additional program jars.
      (http://proguard.sourceforge.net/manual/troubleshooting.html#dynamicalclass)
Ignoring unused library classes...
  Original number of library classes: 4803
  Final number of library classes:    1493
Printing kept classes, fields, and methods...
Inlining subroutines...
Shrinking...

...
---------------------------------------------------------------------

**Comment by ojw28** [comment]
> I think this is not a good solution, because I want use proguard-rules.txt (In my case for some reason I need use proguard-rules.txt). If I remove "useProguard true", ProGuard does not work.

I don't really understand this statement. The R8 compiler's minify functionality is a replacement for using ProGuard. It does the same tasks of obfuscation, minification and optimization, as documented in some detail [here](https://developer.android.com/studio/build/shrink-code). Note that it uses the ProGuard files that are specified using `proguardFiles`, like ProGuard does. As in my previous response, use of Proguard for these tasks is deprecated, and `useProguard` is going to be ignored from 3.5.0 of the gradle plugin.

**Comment by rishun-fsi** [comment]
If use R8 instead of ProGuard, why do not remove "proguard-rules.txt"?
As I know, File proguard-rules.txt does not seem to be used.

If I remove "proguard-rules.txt", demo app still works well.
Is it necessary using file proguard-rules.txt?

 release {
     shrinkResources true
     minifyEnabled true
       proguardFiles = [
           // "proguard-rules.txt", // remove
           getDefaultProguardFile('proguard-android-optimize.txt')
       ]
 }

**Comment by ojw28** [comment]
I don't understand the question. R8 uses whatever proguard configuration you specify, just like the ProGuard tool did. How to shrink/obfuscate/optimize is covered in detail [here](https://developer.android.com/studio/build/shrink-code).

I'm going to close this issue. It's not an ExoPlayer issue.
