### ISSUE TITLE
Play button gets disabled after load error

### ISSUE THREAD

**Issue by aazam-nouri** [google/ExoPlayer#6269]
Play button gets disabled after getting error (load error) but I want the player gets paused instead of getting disabled or stuck and I can retry that by pressing play button, How can I do this?

**Comment by ojw28** [comment]
The ExoPlayer demo app behaves exactly as you describe, so take a look at that. You should set a `PlaybackPreparer` via `PlayerView.setPlaybackPreparer` to handle the retry, as is done in the demo app's `PlayerActivity` class.
