### ISSUE TITLE
HLS stream cannot be opened

### ISSUE THREAD

**Issue by kaiv2000** [google/ExoPlayer#6271]
Please check why this HLS stream cannot be played by exoplayer:

https://s1.worldcam.live:8082/pgkroscienko1/index.m3u8

using:
new HlsMediaSource.Factory(datasourceFactory).createMediaSource(videoUrl);
and:
mediaSource = new HlsMediaSource.Factory(dataSourceFactory).setExtractorFactory(new DefaultHlsExtractorFactory(DefaultTsPayloadReaderFactory.FLAG_IGNORE_AAC_STREAM, false)).createMediaSource(Uri.parse(videoUrl));

And both methods cannot play this stream. VLC player open it correctly.

Thank you very much!

**Comment by ojw28** [comment]
Please see [this troubleshooting page](https://exoplayer.dev/troubleshooting.html#why-do-some-mpeg-ts-files-fail-to-play).
```
return new HlsMediaSource.Factory(dataSourceFactory).setExtractorFactory(
    new DefaultHlsExtractorFactory(
        DefaultTsPayloadReaderFactory.FLAG_ALLOW_NON_IDR_KEYFRAMES, false))
    .createMediaSource(uri);
```
