### ISSUE TITLE
Top bit not zero: HEVC/H265 Stream parsed through fragmented MP4 extractor is not played by Exoplayer

### ISSUE THREAD

**Issue by anony-tech** [google/ExoPlayer#6272]
### [REQUIRED] Issue description
We have HEVC/H265 stream buffers that needs to be streamed and played by Exo-player for our project use. We have the sample buffers captured from middle ware and it is played through VLC player as expected. But when it fed into Exo player, only the first frame is rendered, that is all. We face the issue **'Top bit not zero: -1180838209'**
Below is the log captured when we played the stream buffer.

I referred the issue #652 but it does not give right pointers for us to find out the issue. Please check the stream and let us know if anything is missing.

```
08-08 14:50:19.159 15915 16057 E LoadTask: Unexpected exception loading stream
08-08 14:50:19.159 15915 16057 E LoadTask: java.lang.IllegalStateException: Top bit not zero: -1180838209
08-08 14:50:19.159 15915 16057 E LoadTask: 	at com.google.android.exoplayer.util.ParsableByteArray.readUnsignedIntToInt(ParsableByteArray.java:299)
08-08 14:50:19.159 15915 16057 E LoadTask: 	at com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.readSample(FragmentedMp4Extractor.java:932)
08-08 14:50:19.159 15915 16057 E LoadTask: 	at com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:197)
08-08 14:50:19.159 15915 16057 E LoadTask: 	at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:837)
08-08 14:50:19.159 15915 16057 E LoadTask: 	at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
08-08 14:50:19.159 15915 16057 E LoadTask: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
08-08 14:50:19.159 15915 16057 E LoadTask: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
08-08 14:50:19.159 15915 16057 E LoadTask: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
08-08 14:50:19.159 15915 16057 E LoadTask: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
08-08 14:50:19.159 15915 16057 E LoadTask: 	at java.lang.Thread.run(Thread.java:764)
08-08 14:50:19.161 15915 15915 E EventLogger: internalError [17.29, loadError]
08-08 14:50:19.161 15915 15915 E EventLogger: com.google.android.exoplayer.upstream.Loader$UnexpectedLoaderException: Unexpected IllegalStateException: Top bit not zero: -1180838209
08-08 14:50:19.161 15915 15915 E EventLogger: 	at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:222)
08-08 14:50:19.161 15915 15915 E EventLogger: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
08-08 14:50:19.161 15915 15915 E EventLogger: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
08-08 14:50:19.161 15915 15915 E EventLogger: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
08-08 14:50:19.161 15915 15915 E EventLogger: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
08-08 14:50:19.161 15915 15915 E EventLogger: 	at java.lang.Thread.run(Thread.java:764)
08-08 14:50:19.161 15915 15915 E EventLogger: Caused by: java.lang.IllegalStateException: Top bit not zero: -1180838209
08-08 14:50:19.161 15915 15915 E EventLogger: 	at com.google.android.exoplayer.util.ParsableByteArray.readUnsignedIntToInt(ParsableByteArray.java:299)
08-08 14:50:19.161 15915 15915 E EventLogger: 	at com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.readSample(FragmentedMp4Extractor.java:932)
08-08 14:50:19.161 15915 15915 E EventLogger: 	at com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:197)
08-08 14:50:19.161 15915 15915 E EventLogger: 	at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:837)
08-08 14:50:19.161 15915 15915 E EventLogger: 	at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
```
### [REQUIRED] Reproduction steps
Play the HEVC/H.265 stream buffer through Exo player.  

### [REQUIRED] Link to test content
I share to dev.exoplayer@gmail.com. Please check

### [REQUIRED] A full bug report captured from the device
I share to dev.exoplayer@gmail.com. Please check.

### [REQUIRED] Version of ExoPlayer being used
2.10.0

### [REQUIRED] Device(s) and version(s) of Android being used
Android 8.1.0, Motorola G5S plus.

**Comment by ojw28** [comment]
I don't really understand what a "buffer file" is or how this data is being streamed to ExoPlayer. The attached file doesn't not seem to be a valid and complete mp4, doesn't play more than one frame in VLC, or at all in Chrome, or reproduce the issue described above when played using ExoPlayer.

Please clarify. We need clear reproduction steps to investigate further.

**Comment by ojw28** [comment]
The stack trace above also doesn't appear to match up with the 2.10.0 source code.

**Comment by anony-tech** [comment]
@ojw28 
I mean if we input the 'test' file to VLC player, we can see the file is playing for few seconds, whereas the Exo player displays only a first frame(like still image) and no playback is observed. 
Sorry for the inconvenience. Exo player version used is 1.5.9. 
Thanks

**Comment by anony-tech** [comment]
Hi Oliver,

I mean if we input the 'test' file to VLC player, we can see the file is
playing for few seconds, whereas the Exo player displays only a first
frame(like still image) and no playback is observed.

Exo player version used is 1.5.9, sorry it is not 2.10.0

Thanks
Tamil

**Comment by ojw28** [comment]
> I mean if we input the 'test' file to VLC player, we can see the file is
playing for few seconds

I do not see this for the version of VLC I'm using (3.0.7-0-g86cee31099). I only see a single frame. The file doesn't work at all in Chrome.

More generally, I'm confused about where this file has come from and how such files are being fed into the player. Since it doesn't seem to be a valid and complete media file, I don't think trying to play it in isolation is a valid thing to do, which effectively means we don't have sufficient reproduction steps for a valid use case. In summary - It feels like there may well be some important missing context.

ExoPlayer 1.5.9 is also _really_ old. We're not spending time actively supporting ExoPlayer V1 at this point.

**Comment by anony-tech** [comment]
We recieve this file from live streaming whose media is given by one of our customers. 
We used Totem movie player that it is inbuilt with ubuntu OS. We wonder the 'test' file is played using this player as well.

**Comment by andrewlewis** [comment]
ffplay shows errors about NAL unit sizes and an invalid QP delta, so it seems likely the media is invalid or corrupted. Also, it has multiple `traf` boxes in a single `moof` which we do not handle currently (see [`FragmentedMp4Extractor`](https://github.com/google/ExoPlayer/blob/5da4c67/library/core/src/main/java/com/google/android/exoplayer2/extractor/mp4/FragmentedMp4Extractor.java#L666)).
