### ISSUE TITLE
Encrypted HLS content offline playback

### ISSUE THREAD

**Issue by armanhi** [google/ExoPlayer#6273]
# [REQUIRED] Searched documentation and issues
#6231 
#6122
#5362
#5193

### [REQUIRED] Question
Hi.

I'm currently having a problem with cache + encrypted HLS streams. If user has internet everything works perfectly: .m3u8 is requested, .key is requested and then all chunks (.ts) files, if not yet cached.

The problem happens when user does not have internet access. Since, I guess, .key can't be downloaded, playback doesn't work, raising a "Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to [KEY ADDRESS]". Is it possible for me to download the.key file, store it and pass it to Exoplayer if needed? Or is there any other way to make ir work?

My cache implementation is the following:

return CacheDataSourceFactory(cache, DefaultDataSourceFactory(context, bandwidthMeter, DefaultHttpDataSourceFactory(userAgent, bandwidthMeter)),
                FileDataSourceFactory(), CacheDataSinkFactory(cache, CacheDataSource.DEFAULT_MAX_CACHE_FILE_SIZE),
                CacheDataSource.FLAG_IGNORE_CACHE_ON_ERROR, object : CacheDataSource.EventListener {
            override fun onCachedBytesRead(cacheSizeBytes: Long, cachedBytesRead: Long) {
            }

            override fun onCacheIgnored(reason: Int) {
            }
        }).createDataSource()

### Link to test content
It's kinda hard to send a link since it's tokenized and expires in 10 minutes, but the .m3u8 has the following content:

#EXTM3U
#EXT-X-VERSION:3
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-TARGETDURATION:6
#EXT-X-KEY:METHOD=AES-128,URI="1529060014851.key",IV=0x5a05e1fd5c251a572cc4c170abaaf927
#EXTINF:5.000,
1529060014851-1.ts
#EXTINF:5.720,
1529060014851-2.ts
[...]
#EXTINF:2.240,
1529060014851-40.ts
#EXT-X-ENDLIST

**Comment by AquilesCanta** [comment]
If you have the keys and can correctly map them to their URI, then you can inject a custom [HlsDataSourceFactory](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/source/hls/HlsDataSourceFactory.html) which returns a custom DataSource implementation for type C.DATA_TYPE_DRM, so that when needed, the cached key is returned. Hope this helps!
