### ISSUE TITLE
DASH SegmentURLs and the +1 off issue

### ISSUE THREAD

**Issue by ronak2121** [google/ExoPlayer#6274]
### [REQUIRED] Content description

We are trying to play an MPEG DASH stream, using the main profile, with an FMP4 container, with an LC-AAC codec. There is no video. The audio is LC-AAC, stereo, 44.1kHz, 32kbps.

We use Signed URLs for our streams, with different signatures for each URL.
Therefore, we use SegmentList & SegmentURLs with media and mediaRange attributes.
We are noticing that Exoplayer makes requests differently from dash.js, by adding 1 to the end range header.

For example, dash.js makes a request like so:

(url).m4s?(signature)

with range header = 0-748

However, Exoplayer makes requests like so:

DataSpec[GET (url)?(signature), null, 0, 0, 749, null, 0]

The problem seems to be that Exoplayer is adding 1 to the mediaRange, instead of just using the values as they are provided in the DASH manifest.

This leads to crashing in Exoplayer where it's unable to properly parse the init fragment and other segments.

### [REQUIRED] Link to test content

I'll email this to you separately.

### [REQUIRED] Version of ExoPlayer being used

2.10.3

### [REQUIRED] Device(s) and version(s) of Android being used
Emulator

### [REQUIRED] A full bug report captured from the device

I'll email this to you separately.

**Comment by ojw28** [comment]
> The problem seems to be that Exoplayer is adding 1 to the mediaRange, instead of just using the values as they are provided in the DASH manifest.

This isn't what's happening. `DataSpec[GET (url)?(signature), null, 0, 0, 749, null, 0]` is just the `toString()` representation of the `DataSpec`, where `749` is the length, which corresponds to a range `0-748` range header. ExoPlayer will construct the expected `0-748` range header [here](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/upstream/DefaultHttpDataSource.java#L533), and you can attach a debugger to verify this is the case.

I'm fairly confident the off-by-one error is in the manifest. If you look at the underlying stream using an [MP4 box viewer](http://download.tsi.telecom-paristech.fr/gpac/mp4box.js/filereader.html) you'll see that the first boxes are:
```
ftype  size=24 bytes   position=0
moov   size=724 bytes  position=24
moof   size=184 bytes  position=748
```
This means the manifest should specify a range of `0-747` for the initialization segment, and a range starting at `748` for the first media segment. Note that end positions in range requests are inclusive as per [RFC7233](https://tools.ietf.org/html/rfc7233).
