### ISSUE TITLE
How to handle MediaDrmResetException? What can cause a crash in a mediaserver process from ExoPlayer's perspective?

### ISSUE THREAD

**Issue by ggabdol** [google/ExoPlayer#6280]
### Searched documentation and issues
Issue #5217, Issue #3018
https://developer.android.com/reference/android/media/MediaDrmResetException.html
https://developer.android.com/reference/android/media/MediaDrm

### [REQUIRED] Question
We're seeing a lot of playback failures caused by the following exception from our error reporting tool.
```
com.google.android.exoplayer2.drm.DrmSession$DrmSessionException: android.media.MediaDrmResetException: mediaserver died
at com.google.android.exoplayer2.drm.DefaultDrmSession.onError(SourceFile:443)
at com.google.android.exoplayer2.drm.DefaultDrmSession.openInternal(SourceFile:294)
at com.google.android.exoplayer2.drm.DefaultDrmSession.acquire(SourceFile:163)
at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.acquireSession(SourceFile:559)
at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(SourceFile:1089)
at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(SourceFile:552)
at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(SourceFile:651)
at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(SourceFile:537)
at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(SourceFile:303)
at android.os.Handler.dispatchMessage(Handler.java:101)
at android.os.Looper.loop(Looper.java:164)
at android.os.HandlerThread.run(HandlerThread.java:65)
Caused by: android.media.MediaDrmResetException: mediaserver died
at android.media.MediaDrm.openSession(Native Method)
at com.google.android.exoplayer2.drm.FrameworkMediaDrm.openSession(SourceFile:112)
at com.google.android.exoplayer2.drm.DefaultDrmSession.openInternal(SourceFile:282)
... 10 more
```
The stream format is MPEG-DASH, and we're using ExoPlayer 2.9.4.
Here are the questions:
1. #### What can cause the exception?
I checked the API documentation of [MediaDrmResetException](https://developer.android.com/reference/android/media/MediaDrmResetException.html), and it says,
> This exception is thrown when the MediaDrm instance has become unusable due to a restart of the mediaserver process.

Also, according to [MediaDrm](https://developer.android.com/reference/android/media/MediaDrm),
> In the event of a mediaserver process crash or restart while a MediaDrm object is active, MediaDrm methods may throw MediaDrmResetException

So, I presume that there was a crash or a problem causing a mediaserver process to restart before MediaDrmResetException is thrown. So, the question is, **what can cause a crash in a mediaserver process, or can make the mediaserver process restart from ExoPlayer's perspective?**

2. #### Is there a recommended way to handle this exception?
As the documentation recommends, we're looking for ways to retry to open a DRM session by releasing the unusable MediaDrm object, and then creating and initializing a new one.

https://developer.android.com/reference/android/media/MediaDrmResetException.html
> To continue, the app must release the MediaDrm object, then create and initialize a new one.

https://developer.android.com/reference/android/media/MediaDrm
> To recover, the app must release the MediaDrm object, then create and initialize a new one.

The problem is that DefaultDrmSessionManager doesn't seem to allow the MediaDrm object to be released and to create a new one.
https://github.com/google/ExoPlayer/blob/51acd8150c25a2064c3e0c49e04540bd4e2db6f9/library/core/src/main/java/com/google/android/exoplayer2/drm/DefaultDrmSessionManager.java#L93
https://github.com/google/ExoPlayer/blob/51acd8150c25a2064c3e0c49e04540bd4e2db6f9/library/core/src/main/java/com/google/android/exoplayer2/drm/FrameworkMediaDrm.java#L58
Is there a recommended way to handle this exception?

### A full bug report captured from the device
We're unable to get a full bug report because our reporting tool doesn't support android bug report and there are no known steps to reproduce the issue.

### Link to test content
There is no way for your team to play our contents without a valid account served by our platform because the license is not given with a simple license URL. In addition, it's not 100% reproduced.

**Comment by AquilesCanta** [comment]
I would attempt to diagnose the underlying cause of the issue and try to mitigate whatever is causing the exception. I wouldn't aim to handle the exception gracefully.

On the exoplayer side, I think the only current way to handle `MediaDrmResetException` is to re-prepare the player, unfortunately.

> As the documentation recommends, we're looking for ways to retry to open a DRM session by releasing the unusable MediaDrm object, and then creating and initializing a new one.

I don't think it's possible to continue playback seamlessly without heavy refactoring in the entire library, specially now that key acquisition is part of the loading side.
