### ISSUE TITLE
Play playing automatically

### ISSUE THREAD

**Issue by admobwebmaster** [google/ExoPlayer#6281]
Guys my exoplayer is playing the video automatically when clicking on the video, as I have to press the player to be able to play the video manually.

Thank you guys!

**Comment by AquilesCanta** [comment]
Use [setPlayWhenReady](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/Player.html#setPlayWhenReady-boolean-) to configure whether you want to player to play or not. The way you wire the UI to calls of setPlayWhenReady is up to you.
