### ISSUE TITLE
Problem with mediaDescriptionAdapter

### ISSUE THREAD

**Issue by thrashedbrain** [google/ExoPlayer#6285]
Hi! Thanks for this awesome library. But i have a little problem.
I create a new MediaDescriptionAdapter for PlayerNotification Manager.

```
PlayerNotificationManager.MediaDescriptionAdapter mediaDescriptionAdapter = new PlayerNotificationManager.MediaDescriptionAdapter() {
            @Override
            public String getCurrentContentTitle(Player player) {
                return intent.getStringExtra(intent.getStringExtra("radio_name"));
            }

            @Nullable
            @Override
            public PendingIntent createCurrentContentIntent(Player player) {
                return null;
            }

            @Nullable
            @Override
            public String getCurrentContentText(Player player) {

                return intent.getStringExtra(intent.getStringExtra("radio_name"));
            }

            @Nullable
            @Override
            public Bitmap getCurrentLargeIcon(Player player, PlayerNotificationManager.BitmapCallback callback) {
                return bitmap1;
            }
        };
```

and create notification with channel:

```
playerNotificationManager = PlayerNotificationManager.createWithNotificationChannel(
                    this,
                    NOTIFICATION_CHANNEL_ID,
                    NOTIFICATION_CHANNEL_NAME,
                    NOTIFICATION_ID,
                    mediaDescriptionAdapter

            );
```

but notification have only app name. What i am doing wrong?
Also have question, in notification i need only one play/pause button, how i can do this? 

Thanks!

**Comment by marcbaechinger** [comment]
Sorry, I missed this issue.

This should work. Have you verified that the code with which you get text out of the intent is correct. Seems like duplicating thing to me:

```
intent.getStringExtra(intent.getStringExtra("radio_name"))
```

**Comment by marcbaechinger** [comment]
>  i need only one play/pause button, how i can do this?

The [class level java doc of the PlayerNotificationManager](https://github.com/google/ExoPlayer/blob/85c10b02567b66ecfaaaacfd0ba9389b41bf919e/library/ui/src/main/java/com/google/android/exoplayer2/ui/PlayerNotificationManager.java#L72) explains, how you can hide/show buttons in the notification.
