### ISSUE TITLE
Play encrypted .m3u8 stream

### ISSUE THREAD

**Issue by AlexDundar** [google/ExoPlayer#6293]
I use `ExoPlayer `in my `Android `app for playing .m3u8 video and audio streams. It works well. But now I want to add the ability to play encrypted(aes encryption on server-side) videos. For example, I obtain from backend the next parameters:

```
streamUrl: "https://some_stream.m3u8",
aes_key: "16symbols_key",
aes_iv: "16symbols_IV",
```
decrypt the stream and play it in my ExoPlayer. How can I make this?

**Comment by AquilesCanta** [comment]
Please read the [corresponding section](https://tools.ietf.org/html/rfc8216#section-4.3.2.4) in the HLS specification. You need to update your content so that the playlists include the required tags.
