### ISSUE TITLE
Add 2.10.X-specific offline documentation

### ISSUE THREAD

**Issue by armanhi** [google/ExoPlayer#6295]
### [REQUIRED] Searched documentation and issues
Haven't found anything related.

### [REQUIRED] Question
We've successfully implemented download using the APIs from version 2.9.6. Today, when trying to update to version 2.10.4, I've seen a lot of breaking changes (such as TaskState class gone). Could you please guide me through porting it? Also, are there any new API changes expected in next releases?

**Comment by AquilesCanta** [comment]
I think the best resource I can point you to is the [official documentation](https://exoplayer.dev/downloading-media.html). I am not aware of any specific porting guide. 

If you have any specific questions, post them below and I will reopen the issue. Or file a new issue.

**Comment by rinav** [comment]
Can we have a simpler sample for only downloads/offline caching with the recent changes in 2.10.4. 
The documentation is not sufficient as it does not match with the sample demo app. 

Also if there would be a official video or an article on this topic would be very helpful; similar to io18 demo (but now its deprecated) [IO2018 Demo](https://www.youtube.com/watch?v=svdq1BWl4r8&t=1175s)

**Comment by AquilesCanta** [comment]
> The documentation is not sufficient as it does not match with the sample demo app.

Would you kindly point me to the documentation that does not match the Demo app? I can help with that, but I cannot write a tutorial on downloading, unfortunately. 

@ojw28 will be able to tell whether 2.10.x-specific offline documentation exists.

**Comment by ojw28** [comment]
@rinav - Which documentation does not match with the sample demo app? Thanks.
