### ISSUE TITLE
DASH: Support <Label>text</Label> element for adaptation sets

### ISSUE THREAD

**Issue by ssenanayake** [google/ExoPlayer#6297]
### [REQUIRED] Issue description
Currently in Exoplayer "DashManifestParser" the "label" is treated as an attribute in "AdaptationSet". Based on the DASH Spec it's a node of "Label"

### [REQUIRED] Reproduction steps
Current Exoplayer DASH parser: https://github.com/google/ExoPlayer/blob/release-v2/library/dash/src/main/java/com/google/android/exoplayer2/source/dash/manifest/DashManifestParser.java   Line 275

DASH Spec:  https://dashif-documents.azurewebsites.net/DASH-IF-IOP/master/DASH-IF-IOP.pdf

DASH XSD:  https://standards.iso.org/ittf/PubliclyAvailableStandards/MPEG-DASH_schema_files/DASH-MPD.xsd

### [REQUIRED] Link to test content
N/A - This is to indicate that "label" is not an attribute of "AdaptationSet"

Sample from dashif:  https://dash.akamaized.net/dash264/TestCasesIOP41/MultiTrack/alternative_content/6/manifest_alternative_lang.mpd

### [REQUIRED] A full bug report captured from the device
N/A

### [REQUIRED] Version of ExoPlayer being used
2.10.4

### [REQUIRED] Device(s) and version(s) of Android being used
N/A

**Comment by ojw28** [comment]
If I remember correctly, labels weren't defined anywhere when we added support for them. Support was added by an external contribution: https://github.com/google/ExoPlayer/pull/2904, which turned into https://github.com/google/ExoPlayer/pull/4391.

Do you know where the `Label` node is defined? It doesn't seem to be defined in the schema you've linked to. The DASH-IF doc you've linked to defines its existence, but not what it is. It's unclear what the actual structure of a `Label` node is supposed to be. The sample MPD you've linked to doesn't seem to use the `Label` node for its intended purpose, which is to provide a textual description of the content, and appears to contain redundant information (i.e. `lang`, which is defined directly on the `AdaptationSet`). So the sample doesn't really clarify how these nodes are supposed to be defined.

If you could clarify or ask DASH-IF to clarify, that would be great!

**Comment by ssenanayake** [comment]
Please refer to section 3.9.2 ("Adaptation Set Labeling Options for Selection") of https://dashif.org/docs/DASH-IF-IOP-v4.2-clean.htm#_Toc511040753


"Label | 0 � N | See ISO/IEC 23009-1 [4], clause 5.3.7.2 Table 9. This element enables to provide a textual description of the content. This element should be used if content author expects that clients supports UI for selection. However, this element must not be used as the sole differentiating element as at start-up no user interaction is available."

**Comment by ojw28** [comment]
ISO/IEC 23009-1 [4], clause 5.3.7.2 Table 9 doesn't define `Label` though :(. Seems like an error in the DASH-IF document.

**Comment by ojw28** [comment]
I filed https://github.com/Dash-Industry-Forum/DASH-IF-IOP/issues/383 for clarification.

**Comment by ojw28** [comment]
Clarification provided on the issue ref'd above. We'll add support for parsing `<Label>text</Label`. We'll keep support for `@label` as an attribute as well. If both are present then the former (i.e. standardized) version will win.
