### ISSUE TITLE
Access denied finding property "OMX_VIDEO_DEC.DEC

### ISSUE THREAD

**Issue by pearleye** [google/ExoPlayer#6299]
### [REQUIRED] Searched documentation and issues
https://exoplayer.dev/

### [REQUIRED] Question
We see the below access denied error while watching content in Android Live TV applicaiton in 
a custom device which has Android TV (Pie 9) version ported. We use ExoPlayer to play content when there is a request from LiveTV application.

08-13 20:22:35.123  1751  9311 **E libc    : Access denied finding property "OMX_VIDEO_DEC.DEC"**
08-13 20:22:35.146  1751  9311 **E libc    : Access denied finding property "OMX_VDEC_COMMON.HEX"**

Has anyone come across such denials or any idea like where and how I can provide a permission to overcome this ?

### A full bug report captured from the device
NA

### Link to test content
NA

**Comment by tonihei** [comment]
Does this result in any actual player error or is this just a log message you've seen?

**Comment by pearleye** [comment]
It's just a log message we see as of now, not sure if it causing any side effect. So wanted to better understand this denial!

**Comment by tonihei** [comment]
I think that's just log spam and can be ignored.
