### ISSUE TITLE
FfmpegAudioRenderer compiling errors

### ISSUE THREAD

**Issue by Dniel97** [google/ExoPlayer#6300]
### [REQUIRED] Issue description
I imported the folder: `com/google/android/exoplayer2/ext/ffmpeg/` into my existing android project and got several compiling errors inside `FfmpegAudioRenderer.java`:

- line 33: error: package org.checkerframework.checker.nullness.qual does not exist
- line 47: error: cannot find symbol class MonotonicNonNull

To fix this I imported `androidx.annotation.NonNull` and replaced `@MonotonicNonNull` with `@NonNull`
After this I got another compiling error:

line 141: `Collections.emptyList(),` error: incompatible types: List<Object> cannot be converted to List<byte[]>

But I don't know how to fix this compiling error.

### [REQUIRED] Reproduction steps

1. Clone the ExoPlayer repository and copy the `com` folder from `/extensions/ffmpeg/src/main/java/` into my android project java folder
2. Import `androidx.annotation.NonNull` and replace `@MonotonicNonNull` with `@NonNull` inside `com/google/android/exoplayer2/ext/ffmpeg/FfmpegAudioRenderer.java`
3. Build the project

### [REQUIRED] Link to test content
No media/content required.

### [REQUIRED] A full bug report captured from the device
Not device related.

### [REQUIRED] Version of ExoPlayer being used
ExoPlayer 2.10.4

### [REQUIRED] Device(s) and version(s) of Android being used
Samsung Galaxy S7 - Android 8.0.0

**Comment by AquilesCanta** [comment]
I don't think this is an ExoPlayer issue, but rather an issue with the way the project is being imported/modified. You are in a much better position than I am to diagnose this issue. If you have evidence suggesting this is an issue with ExoPlayer, please post it below and I will reopen the issue.

**Comment by Dniel97** [comment]
`FfmpegAudioRenderer.java` overrides the method `getOutputFormat()` which returns a Format. The function `createAudioSampleFormat` [Format (ExoPlayer library)](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/Format.html#createAudioSampleFormat-java.lang.String-java.lang.String-java.lang.String-int-int-int-int-int-java.util.List-com.google.android.exoplayer2.drm.DrmInitData-int-java.lang.String-) needs as the 9th parameter `List<byte[]> initializationData` but the `FfmpegAudioRenderer` uses the function `Collections.emptyList()` which returns a `List<Object>` instead of the needed `Collections.<byte[]>emptyList()` which returns the right `List<byte[]>` list.
So you just need to replace line 141 inside [FfmpegAudioRenderer.java](https://github.com/google/ExoPlayer/blob/release-v2/extensions/ffmpeg/src/main/java/com/google/android/exoplayer2/ext/ffmpeg/FfmpegAudioRenderer.java#L141) with `Collections.<byte[]>emptyList(),`.

**Comment by AquilesCanta** [comment]
Perhaps you are not using java 8 features in your project? Any reason not to enable them?

**Comment by Dniel97** [comment]
Inside my` build.gradle` I'm using
`    compileOptions {
        targetCompatibility JavaVersion.VERSION_1_8
    }` to enable Java 8.

**Comment by Dniel97** [comment]
EDIT: You are right, I just needed to add `sourceCompatibility JavaVersion.VERSION_1_8` and it's working fine.

**Comment by AquilesCanta** [comment]
Great!
