### ISSUE TITLE
Dynamically change ConcatenatingMediaSource

### ISSUE THREAD

**Issue by 3-BodyCoding** [google/ExoPlayer#6302]
I used ConcatenatingMediaSource to play a list of videos, but after I removed or added the ConcatenatingMediaSource, the actual playlist of the exoplayer did not change. I had to call exoPlayer.prepare again, but the playback would be stopped. How do I dynamically add or remove a playlist? Thank you.

**Comment by jakoss** [comment]
Just to be sure. You added new `ConcatenatingMediaSource` to existing `ConcatenatingMediaSource`? I don't think that's supported. You can add any single `MediaSource` to `ConcatenatingMediaSource`, but i'm not sure how nested `ConcatenatingMediaSource` could work

**Comment by tonihei** [comment]
@Nekromancer  Nested `ConcatenatingMediaSource` are supported and it should work just fine. 

@AndroidJohnsonWang Can you clarify what you mean by "the actual playlist of the exoplayer did not change"? The way it's currently implemented means that all dynamic playlist changes are not immediately visible in the `Timeline` you get from the callback and `Player.getCurrentTimeline`. If you'd like to do something as a result of a playlist operation, you can pass in a `Runnable` as the last parameter to `addMediaSource` for example, which gets executed once the playlist operation has been done.

Note that we are currently reworking our playlist API to integrate it better with the rest of the player. See the RFC in #6161.

**Comment by 3-BodyCoding** [comment]
@tonihei I've seen the new API documentation. I think the new exoplayer playlist API is better than the current API. Now, using exoPlayer.prepare(ConcatenatingMediaSource), it's not a good idea to change the ConcatenatingMediaSource.
When is the new Api version updated? Thank you

**Comment by tonihei** [comment]
The update should happen as part of the next major release (2.11.0), but we don;t have exact dates yet.

**Comment by tonihei** [comment]
Closing because the question was answered
