### ISSUE TITLE
Does Exo player support to set error time out?

### ISSUE THREAD

**Issue by VeiZhang** [google/ExoPlayer#6304]
When exo player happend `timeout` or `socket timeout` exception, inner player will retry soon, the problem is how can I set the error retry time? Because inner player retry fastly.

**Comment by tonihei** [comment]
I'm not entirely sure what kind of timeout or delay you mean, but there are multiple ways to customize the loading behavior:
- `DefaultHttpDataSourceFactory` allows you to set a `connectTimeoutMillis` and a `readTimeoutMillis` for the connection and reading timeout respectively. You can your customized data source factory in the `MediaSource` builders. 
- Every `MediaSource` builder allows you to set a `LoadErrorHandlingPolicy` to define how the player handles errors. You can for example specify the delay before a load is retried (or if it's retried at all).

**Comment by VeiZhang** [comment]
@tonihei Thanks for your help. I found when playing error, exo player will retry to play more times, I want it retry once or don't retry.
Follow your help, I find the way, maybe it can. I will try.
```
DefaultLoadErrorHandlingPolicy#minimumLoadableRetryCount
```

**Thanks again**

**Comment by tonihei** [comment]
Please have a look at `LoadErrorHandlingPolicy.getRetryDelayMsFor`. If you return `C.TIME_UNSET` from this method, it stops retrying. Otherwise, you can also specify the number of time to retry with `minimumLoadableRetryCount`.

**Comment by VeiZhang** [comment]
@tonihei Thanks
