### ISSUE TITLE
How to keep the minimumBufferMs short initially and later increase it

### ISSUE THREAD

**Issue by shubhamvashisht** [google/ExoPlayer#6305]
How to keep the minimumBufferMs short initially so that track starts playing immediately and increase it later so that we have enough data in buffer to play if connection gets lost.

**Comment by fgl27** [comment]
try to understand how [DefaultLoadControl](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/DefaultLoadControl.html#DefaultLoadControl-com.google.android.exoplayer2.upstream.DefaultAllocator-int-int-int-int-int-int-boolean-int-boolean-) and [setBufferDurationsMs](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/DefaultLoadControl.Builder.html#setBufferDurationsMs-int-int-int-int-) works

what you wanna is a very low **bufferForPlaybackMs** a bigger **minBufferMs** (bigger than **bufferForPlaybackMs**) and even bigger **maxBufferMs** (bigger than **minBufferMs**), no need to change anything later just to understand how to use **setBufferDurationsMs** at the start of it playback, **bufferForPlaybackAfterRebufferMs** can be equal to **bufferForPlaybackMs**.

you can use **[player.getTotalBufferedDuration()](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/Player.html#getTotalBufferedDuration--)** to see the buffer state.

**Comment by shubhamvashisht** [comment]
@fgl27 is there any obvious drawback of setting ```bufferForPlaybackMs``` lower , say 500(ms)?

**Comment by fgl27** [comment]
Is something you need to test, depends on what you wanna to play and how reliable is the connection to it.

I have tested lower values and I don't see a noticeable difference from 100 to 1000 in relation to how fast it starts.

But I do notice a problem when it doesn't work when the buffer is to low, as the buffer is so small it may loop doing this when you first start playing something... Buffering > starting playing > instantly buffer is depleted > buffering > stay like this for ever...

This is a issue of a "lag" on the connection that may happen on any internet connection randomly.

So test and if is something that may be affected by internet, you can add a simple way to change the value from the user side.

**Comment by shubhamvashisht** [comment]
@fgl27 thank you for the quick response. it helped.
