### ISSUE TITLE
How to check if chunkless preparation is enabled. 

### ISSUE THREAD

**Issue by shubhamvashisht** [google/ExoPlayer#6306]
i looked in docs but could not find.
How to check whether the chunkless preparation is happening after setting ```allowChunklessPreparation()``` to true.

**Comment by AquilesCanta** [comment]
Assuming you are setting allowChunklessPreparation to true, chunkless preparation will occur if, and only if, the CODECS attribute in EXT-X-STREAM-INF tags is present. 

There is no straightforward way of checking. If you really want to programmatically know whether chunkless preparation is happening, you can:
- Inject a custom HlsDataSourceFactory so as to inject a custom DataSource for C.DATA_TYPE_MEDIA(_INITIALIZATION).
- Wrap HlsMediaSource and HlsMediaPeriod to know when MediaPeriod.Callback#onPrepared is being called by HlsMediaPeriod.

If HTTP connections for C.DATA_TYPE_MEDIA are being opened before MediaPeriod.Callback#onPrepared is being called, then chunkless preparation is not working (you can also check whether the codecs attribute for the variants is populated. If it is, please report an issue!

Hope this helps!
