### ISSUE TITLE
how to do range request?

### ISSUE THREAD

**Issue by chaangliu** [google/ExoPlayer#6309]
Hi, this question may be silly, I wanna ask how to do range request while loading an .mp4 video from server? Meaning that when start playing I only want to load a small part of the video and will load more when reaching the unloaded part, like youtube. I googled and searched the issues but did not find out a solution.
![image](https://user-images.githubusercontent.com/6789406/63225389-dec94900-c201-11e9-81c2-00bb441b6378.png)
I also noticed [this post](https://github.com/google/ExoPlayer/issues/5133), seems I need to set http header, but after reading the source code I didn't figure out how to do that.

thank you

**Comment by umangsaini** [comment]
Please look at the [Customization](https://exoplayer.dev/customization.html) options for [Progressive](https://exoplayer.dev/progressive.html) playback in developer documentation. 

You may customize parameters of Allocator used by **LoadControl** to set required buffering parameters. DefaultLoadControl has DEFAULT_MAX_BUFFER_MS set to 30000 i.e. maximum 30 seconds is buffered currently. Open Big Buck Bunny (MP4 Video) from Misc section of Demo application. Pause the video, it will buffer up to 30 seconds ahead of current position.

Look for examples which create Exoplayer with custom LoadControl using following API ([Link](https://github.com/google/ExoPlayer/blob/85c10b02567b66ecfaaaacfd0ba9389b41bf919e/library/core/src/main/java/com/google/android/exoplayer2/ExoPlayerFactory.java#L125))

`newSimpleInstance(RenderersFactory renderersFactory,
      TrackSelector trackSelector, LoadControl loadControl)`

**Comment by chaangliu** [comment]
> Please look at the [Customization](https://exoplayer.dev/customization.html) options for [Progressive](https://exoplayer.dev/progressive.html) playback in developer documentation.
> 
> You may customize parameters of Allocator used by **LoadControl** to set required buffering parameters. DefaultLoadControl has DEFAULT_MAX_BUFFER_MS set to 30000 i.e. maximum 30 seconds is buffered currently. Open Big Buck Bunny (MP4 Video) from Misc section of Demo application. Pause the video, it will buffer up to 30 seconds ahead of current position.
> 
> Look for examples which create Exoplayer with custom LoadControl using following API ([Link](https://github.com/google/ExoPlayer/blob/85c10b02567b66ecfaaaacfd0ba9389b41bf919e/library/core/src/main/java/com/google/android/exoplayer2/ExoPlayerFactory.java#L125))
> 
> `newSimpleInstance(RenderersFactory renderersFactory, TrackSelector trackSelector, LoadControl loadControl)`

this is exactly what I want; thank you for your kind reply!
