### ISSUE TITLE
Audio/Video is not sync if Audio codec is EAC-3 on TCL Parcee Android TV with Amazon Fire Stick

### ISSUE THREAD

**Issue by GouravSna** [google/ExoPlayer#6311]
Again referring to the same issue https://github.com/google/ExoPlayer/issues/6213; so if the audio track will under run if we decrease the buffer size and eventually we will not be able to play the Dolby track then it is an issue which needs to be fixed. Right ?

**Comment by andrewlewis** [comment]
@GouravSna Let's continue discussion on #6213 to keep this in one place.
