### ISSUE TITLE
Adding parameters for playing encrypted .m3u8 stream

### ISSUE THREAD

**Issue by AlexDundar** [google/ExoPlayer#6312]
I have some encrypted (AES-128) `.m3u8` stream in my `Android` app and I want to play it in `ExoPlayer`. I have for this two variables: 

    val secretKey = "a4cd9995a1aa91e1"
    val initVector = "0000000000000000"

As I read in docs https://tools.ietf.org/html/rfc8216#section-4.3.2.4 I need to add `URI` and `IV` parameters into source file. After adding I have the next one: 

        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-TARGETDURATION:6
        #EXT-X-MEDIA-SEQUENCE:0
        #EXT-X-DISCONTINUITY
        #EXT-X-KEY:METHOD=AES-128,URI="data:text/plain;charset=utf-8,a4cd9995a1aa91e1",IV=0x30303030303030303030303030303030
        #EXTINF:6.0,
        media_b525000_0.ts
        #EXTINF:6.0,
        media_b525000_1.ts
        #EXTINF:6.0,
        media_b525000_2.ts
        *other .ts segments...*

where I added two lines: `#EXT-X-DISCONTINUITY` and `#EXT-X-KEY`. But the player doesnt play the stream and I have the next exception:

    com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Malformed URL

What did I do wrong? And how can I to decrypt stream when I have `secretKey` and `initVector`?

**Comment by tonihei** [comment]
The URI parameter should be a URI and "data:text/plain;charset=utf-8,a4cd9995a1aa91e1" isn't one, so the error message is correct in saying that the URI is malformed.

**Comment by AlexDundar** [comment]
> The URI parameter should be a URI and "data:text/plain;charset=utf-8,a4cd9995a1aa91e1" isn't one, so the error message is correct in saying that the URI is malformed.

Ok, what should it look like? How can I get it with only a variable secretKey?

**Comment by tonihei** [comment]
Mmh, actually, ignore my previous comment. This should be a valid data URI. :)

**Comment by tonihei** [comment]
The actual issue in your case is that the key request is executed by a `HttpDataSource` and should actually use a `DataSchemeDataSource`.

Can you check what kind of `DataSource.Factory` you provide to the `HlsMediaSource.Factory`? It should either be a `DefaultDataSource.Factory` that is able to load both over network and from data URIs or you need to inject your own `HlsDataSourceFactory` that can return a different kind of data source for `C.DATA_TYPE_DRM`.

**Comment by AlexDundar** [comment]
@tonihei yes, here is my code for building media source:

```
private fun buildMediaSource(uri: Uri): MediaSource {

        val httpDataSourceFactory = DefaultHttpDataSourceFactory(
            userAgent,
            bandwidthMeter,
            DefaultHttpDataSource.DEFAULT_CONNECT_TIMEOUT_MILLIS,
            DefaultHttpDataSource.DEFAULT_READ_TIMEOUT_MILLIS,
            true
        )
        val defaultDataSourceFactory = DefaultDataSourceFactory(
            this,
            bandwidthMeter,
            httpDataSourceFactory
        )

        val okHttpDataSourceFactory = OkHttpDataSourceFactory(playerOkHttpClient, userAgent, bandwidthMeter)

        when (Util.inferContentType(uri)) {
            C.TYPE_SS -> return SsMediaSource.Factory(
                DefaultSsChunkSource.Factory(defaultDataSourceFactory),
                defaultDataSourceFactory
            )
                .createMediaSource(uri)
            C.TYPE_DASH -> return DashMediaSource.Factory(
                DefaultDashChunkSource.Factory(defaultDataSourceFactory),
                defaultDataSourceFactory
            )
                .createMediaSource(uri)
            C.TYPE_HLS -> {
                return HlsMediaSource.Factory(okHttpDataSourceFactory)
                    .createMediaSource(uri)
            }
            else -> return ProgressiveMediaSource.Factory(defaultDataSourceFactory)
                .createMediaSource(uri)  // C.TYPE_OTHER
        }
    }
```

For HlsMediaSource.Factory I provide okHttpDataSourceFactory (with okHttpClient for decrypting m3u8 stream from backend).

**Comment by AlexDundar** [comment]
And here is the `Interceptor` for `playerOkHttpClient` (in `okHttpDataSourceFactory`):

```
class PlayerInterceptor (val context: Context) : Interceptor {

    val secretKey = "16SymbolsKey"
    val initVector = "16SymbolsIV"

    override fun intercept(chain: Interceptor.Chain): Response {

        val request = chain.request()
        val requestUrl = request.url.toUrl().toString()

        val responseOriginal = chain.proceed(chain.request())
        val responseBodyOriginal = responseOriginal.body
        
        return responseOriginal.newBuilder()
                .body(
                    ResponseBody.create(
                        responseBodyOriginal?.contentType(),
                        decrypt(secretKey, initVector, responseBodyOriginal?.bytes())
                    )
                ).build()
    }

    private fun decrypt(
        key: String,
        iv: String,
        responseBodyBytes: ByteArray?,
        needInitVector: Boolean = true
    ): String {

        return try {
            val keyBytes = key.toByteArray()
            val ivBytes = iv.toByteArray()

            val secretKeySpec = SecretKeySpec(keyBytes, "AES")
            val cipher = Cipher.getInstance("AES/CBC/PKCS5Padding")

            if (needInitVector) {
                cipher.init(Cipher.DECRYPT_MODE, secretKeySpec, IvParameterSpec(ivBytes))
            } else {
                cipher.init(Cipher.DECRYPT_MODE, secretKeySpec)
            }

            val resultBytes = cipher.doFinal(responseBodyBytes)
            var decrypted = String(resultBytes)

            decrypted = decrypted.replaceFirst(
                "#EXTINF",
                "#EXT-X-KEY:METHOD=AES-128,URI=\"data:text/plain;charset=utf-8,$secretKey\",IV=0x${IV_in_hexadecimal}" +
                        "\n#EXTINF",
                true
            )
            
            decrypted

        } catch (e: Exception) {
            ""
        }
    }

}
```

**Comment by tonihei** [comment]
That actually confirms what I wrote in https://github.com/google/ExoPlayer/issues/6312#issuecomment-522511378.  You need to use either a `DefaultDataSourceFactory` with your special `OkHttpDataSourceFactory` OR implement `HlsDataSourceFactory` interface and return different implementations depending on the type of media (i.e. your custom OkHttp one for everything and a `DataSchemeDataSource.Factory` for C.DATA_TYPE_DRM.)

**Comment by AlexDundar** [comment]
@tonihei If I understand correctly, I already use the first option you wrote: in my code you can see:
```

        val defaultDataSourceFactory = DefaultDataSourceFactory(
            this,
            bandwidthMeter,
            httpDataSourceFactory
        )
        val okHttpDataSourceFactory = OkHttpDataSourceFactory(playerOkHttpClient, userAgent, bandwidthMeter)
...
    return HlsMediaSource.Factory(okHttpDataSourceFactory)
                    .createMediaSource(uri)
```

And I make manipulations with response (stream bytes) in the `Interceptor `in my `OkHttpClient`. Maybe I’ve made a mistake somewhere and don’t understand where:( And nowhere is there an example of the implementation of this functionality, unfortunately

**Comment by tonihei** [comment]
You also need to use the `DefaultDataSourceFactory` in your `HlsMediaSource.Factory`, otherwise it doesn't have any effect.

**Comment by AlexDundar** [comment]
@tonihei Ok, I made it. 

```
        val okHttpDataSourceFactory = OkHttpDataSourceFactory(playerOkHttpClient, userAgent, bandwidthMeter)

        val defaultDataSourceFactory = DefaultDataSourceFactory(
            this,
            bandwidthMeter,
            okHttpDataSourceFactory
        )

    when (Util.inferContentType(uri)) {
             C.TYPE_HLS -> {
                return HlsMediaSource.Factory(defaultDataSourceFactory)
                    .createMediaSource(uri)
            }

    }
```
OkHttpDataSourceFactory is the class from `com.google.android.exoplayer:extension-okhttp:2.10.3`.
And I removed method `replaceFirst` from my `OkHttpInterceptor` (you can see this class above).

But it doesnt work 😞 When I provide url with encrupted `.m3u8` stream, I see in logs (logger is wrote in `PlayerInterceptor`):
1) decrypted `.m3u8` stream that looks like
```
    #EXTM3U
    #EXT-X-VERSION:3
    #EXT-X-STREAM-INF:BANDWIDTH=525000,RESOLUTION=428x240,CLOSED-CAPTIONS=NONE
    chunklist_b525000.m3u8
    #EXT-X-STREAM-INF:BANDWIDTH=750000,RESOLUTION=640x360,CLOSED-CAPTIONS=NONE
    chunklist_b750000.m3u8
...
```
2) Decrypted `chunklist_b525000.m3u8` :
```

    #EXTM3U
    #EXT-X-VERSION:3
    #EXT-X-TARGETDURATION:6
    #EXT-X-MEDIA-SEQUENCE:0
    #EXTINF:6.0,
    media_b525000_0.ts
    #EXTINF:6.0,
    media_b525000_1.ts
    #EXTINF:6.0,
    media_b525000_2.ts
    #EXTINF:6.0,
    media_b525000_3.ts
    #EXTINF:6.0,
    media_b525000_4.ts
    #EXTINF:6.0,
    media_b525000_5.ts
```
3) Decrypted `/media_b525000_0.ts` :

```
G@������������������6��=�����������������������������������������������������������������������������������������������������������������������������������������������������������������������GO����<�����������%��ID3 �ID3 ������&��ID3 �ID3 ��������������������������������������������������������������������������������������������������������������������������������������GA��1���������~������n��
    1��!����������	������gd����A������@������@����ŋe�������h��,����������E���H��,� �#��x264 - core 155 r2901 7d0ff22 - H.264/MPEG-4 AVC codec - Copyleft 2003-2018 - http:/G��/www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 G��deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=7 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_G��adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=0 intra_refresh=0 rc_lookahead=40 rc=abr mbtree=1 bitrate=350 ratetol=1.0 qcomp=0.60 qpmin=0 G��qpmax=69 qpstep=4 vbv_maxrate=400 vbv_bufsize=1200 nal_hrd=none filler=0 ip_ratio=1.40 aq=1 ...
```

4) I obtain error:
`com.google.android.exoplayer2.ParserException: Cannot find sync byte. Most likely not a Transport Stream.`

I tried to use class `Aes128DataSource` (I copied it from `exoplayer `sdk because it is not public) but it had no effect. I tried to use `DataSchemeDataSource` but I did not understand how. This class doesnt have `Factory`.

**Comment by AlexDundar** [comment]
I made custom `HlsDataSourceFactory`  with using `DataSchemeDataSource` for `DATA_TYPE_DRM`:
```
public class CustomHlsDataSourceFactory implements HlsDataSourceFactory {

    private Context context;
    private TransferListener listener;
    private DataSource.Factory baseDataSourceFactory;

    public CustomHlsDataSourceFactory(
            Context context,
            TransferListener listener,
            DataSource.Factory baseDataSourceFactory) {
        this.context = context.getApplicationContext();
        this.listener = listener;
        this.baseDataSourceFactory = baseDataSourceFactory;
    }

    @Override
    public DataSource createDataSource(int dataType) {

        if (dataType == C.DATA_TYPE_DRM) {
            showLog("createDataSource DATA_TYPE_DRM");
            return new DataSchemeDataSource();
        } else {
            DefaultDataSource dataSource = new DefaultDataSource(context, baseDataSourceFactory.createDataSource());
            if (listener != null) {
                dataSource.addTransferListener(listener);
            }
            showLog("createDataSource default");
            return dataSource;
        }

    }
}
```
And I provided it to `HlsMediaSource.Factory` :

```
val okHttpDataSourceFactory = OkHttpDataSourceFactory(playerOkHttpClient, userAgent, 
    bandwidthMeter)

val customHlsDataSourceFactory = CustomHlsDataSourceFactory(
            this,
            bandwidthMeter,
            okHttpDataSourceFactory
        )

when (Util.inferContentType(uri)) {
 C.TYPE_HLS -> {
                return HlsMediaSource.Factory(customHlsDataSourceFactory)
                    .createMediaSource(uri)
            }
}
```

But it was no effect, unfortunately. I obtained error
`com.google.android.exoplayer2.ParserException: Cannot find sync byte. Most likely not a Transport Stream.`

**Comment by tonihei** [comment]
Just to clarify: The original issue has been solved, right? The DRM keys can now be loaded from the data URI? 

The other issue sounds like an issue with your decryption customization. We probably can't spent much time debugging your custom code, so it would be good to see if the setup works without your custom component.

**Comment by AlexDundar** [comment]
@tonihei , thank you for your reply!

Maybe I wasn’t clear with the initial issue

1. Backend dev and me are building our own custom DRM with own licence server (not widevine or something else). And I didn’t have o problem of receiving the key from the Data URI (at this stage of development I can have them as open data (just copy/paste them) )
2. The initial problem was and still is that I cannot inject this key and initvector to decrypt .ts segments properly.

**Comment by AlexDundar** [comment]
Maybe we are doing something wrong. I decrypt m3u8 and receive this
```
    #EXTM3U
    #EXT-X-VERSION:3
    #EXT-X-TARGETDURATION:6
    #EXT-X-MEDIA-SEQUENCE:0
    #EXTINF:6.0,
    media_b525000_0.ts
    #EXTINF:6.0,
    media_b525000_1.ts
    #EXTINF:6.0,
    media_b525000_2.ts
    #EXTINF:6.0,
    media_b525000_3.ts
    #EXTINF:6.0,
    media_b525000_4.ts
...
```
We also developing web-player, and it is enough to be able to play this segments , but EXO returns an error 
`com.google.android.exoplayer2.ParserException: Cannot find sync byte. Most likely not a Transport Stream.`

That is why I thouht I should do forced injection of `#EXT-X-KEY` tag to this  file (to make EXO play it). But still got the same error. 

Plz, need you recommendation here.

**Comment by tonihei** [comment]
I don't think you can use `#EXT-X-KEY` to decrypt the entire stream. You'd need to use some form of custom `DataSource` to do the decryption when reading from the network.
