### ISSUE TITLE
Ima Ad Skip Button Text 

### ISSUE THREAD

**Issue by RezaMortazavi** [google/ExoPlayer#6313]
How can i change the text of skip button in IMA ads?

**Comment by tonihei** [comment]
The skip button is provided by the IMA SDK and you need to [change the language in the IMA SDK settings](https://developers.google.com/interactive-media-ads/docs/sdks/android/v3/api/reference/com/google/ads/interactivemedia/v3/api/ImaSdkSettings.html#setLanguage(java.lang.String)) to do that. The `ImaAdsLoader.Builder` in ExoPlayer allows you to set your own setting by calling `setImaSdkSettings`.

**Comment by RezaMortazavi** [comment]
Thanks..but in this way i can only set the language..i need to use custom text and font..i mean i need to access the button view..is there any way to do that?

**Comment by andrewlewis** [comment]
See also [this post from the IMA forum](https://groups.google.com/forum/#!searchin/ima-sdk/customize$20skip|sort:date/ima-sdk/c9Ed45PedFk/dErEDgndIQAJ). At least when that was written, customizing the UI elements was against policy. If you want to check whether this is still the case, you could post another message in that group.
