### ISSUE TITLE
Release codec resources hold by other apps

### ISSUE THREAD

**Issue by rafakob** [google/ExoPlayer#6318]
### [REQUIRED] Searched documentation and issues
Topics: #5799, #6107, #5516, #5219

### [REQUIRED] Question
We've recently started to see increased rate of following error:
```
MediaCodecRenderer$DecoderInitializationException: Decoder init failed (AVC)
```  
This occurs mostly on Huewei devices so we started to investigate there. I've came across above mentioned topics. It looks like a problem with releasing decoder resources, so I've looked at our code which is responsible for releasing the player and it looks ok. 

It turns out that eg. for Huawei P20 Pro there's only one shared AVC decoder instance available -> I've made a quick test:

1. Play video in our app -> **works fine**
2. Run eg. [TED](https://www.ted.com) application
3. Start video in TED app
4. Minimize TED app
5. Go back to our app
6. Try to play video -> **fail DecoderInitializationException**
7. Kill TED app
8. Go back to our app
9. Try to play video -> **works fine**

Is there any way to release programatically codec resources which are used by another app? This is quite a significant problem for us.

**Comment by tonihei** [comment]
I can reproduce the issue. When I minimize the TED app it continues to play in the background and thus needs to hold onto the decoder instance. 

There is unfortunately also no way to stop another app from using the decoders to play media. It seems to me though that TED should disable the video decoders when backgrounding the app. This would not only save battery life but would also allow you to play another video at the same time. You could potentially ask to user to stop other media playing apps when you encounter this exception in your app?

**Comment by rafakob** [comment]
Indeed, when TED is minimized the audio is playing in the background (it starts foreground service). I need to check how other popular apps behave.

As you said, when this error occurs we need to show user a detailed explanation what is a probable cause. Our customer support could also ask users if they have any other streaming app opened.

It's sad that a device like P20 Pro (recent flagship after all) has such a restrictive policy. Shame on you Huawei!

**Comment by rafakob** [comment]
One more question @tonihei. Is there any other reason why this exception might be thrown?
```
com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.hisi.video.decoder.avc.secure, Format(video=288000, null, null, video/avc, avc1.4D401F, 288000, null, [480, 270, 25.0], [-1, -1])
```
Since this happening on production and we can't reproduce this (apart from this TED app scenario) I can't provide a bug report. **Is there anything else that we could check in our app?** Could we log some additional data when this exception happens? (I'm thinking about logging value of `MediaCodecInfo.CodecCapabilities.getMaxSupportedInstances`)

**Comment by tonihei** [comment]
> Is there any other reason why this exception might be thrown?

Yes, there may be also be other reasons. This exception is always thrown when the decoder can't be initialized, so if it fails without another app using the decoder, you'll still get the same error.

**Comment by tonihei** [comment]
> Indeed, when TED is minimized the audio is playing in the background (it starts foreground service). I need to check how other popular apps behave.

We also tried to reach out to the TED developers to make them aware of the issue.

**Comment by rafakob** [comment]
Oddly enough on Huawei P20 Pro `getMaxSupportedInstances` returns `2` so in theory it should work. I've tested the "TED scenario" on Huawei P10 and it's working fine (it also returns `2` for max instances). Ehhh "The Android Dev" life...

**Comment by andrewlewis** [comment]
`getMaxSupportedInstances` returning `2` does not provide a guarantee that playback will succeed, unfortunately -- please see also https://github.com/google/ExoPlayer/issues/1286#issuecomment-200854838.

**Comment by rafakob** [comment]
Thank you, guys! I think I got everything I needed.
