### ISSUE TITLE
Add support for upstream discard to HLS

### ISSUE THREAD

**Issue by stevemayhew** [google/ExoPlayer#6322]
### Use case description
It is undesirable to leave poor quality buffered video samples in place when sufficient higher quality samples exist to replace them.

Two cases this can happen:
1. Adaptation in live playlists can leave substantial low quality data buffered, particularly in the channel change case where low bit rate initial selection facilitates rapid channel change.
2. When switching from trick-play (low frame rate) tracks to regular frame rate.

### Proposed solution
Implement the existing `SequenceableLoader#reevaluateBuffer()` method in library-hls.

The work on this is in a pending pull request https://github.com/google/ExoPlayer/pull/6321

### Alternatives considered
Using a separate SampleStreamWrapper and TrackGroup for the trick-play tracks.  The more elegant solution of including these tracks with the balance of the adaptation set necessitates this.

**Comment by tonihei** [comment]
Thanks for filing the tracking issue. Can you let us know when #6321 is ready for review?

**Comment by stevemayhew** [comment]
Will do, thank you for the input... Saving the first sample index in
HlsMediaChunk definitely looked like the simple road.  Agreed HLS is much
nastier with both muxed and demuxed tracks

**Comment by ojw28** [comment]
If I remember correctly, it's also nastier because there's no guarantee that segments are aligned across variants, or (in the case of TS) that they start with a keyframe.

**Comment by stevemayhew** [comment]
Probably best to restrict this to playlists that indicate `EXT-X-INDEPENDENT-SEGMENTS` then.

**Comment by tonihei** [comment]
This is now supported with PR #7244.
