### ISSUE TITLE
How to setContentUrl in AdRequest for Contextual ads

### ISSUE THREAD

**Issue by vindhyapratap** [google/ExoPlayer#6323]
I want contextual ads but AdRequest of IMA Ads does not support to setContentUrl

Here is feature detail
https://support.google.com/admob/answer/6270563?hl=en

Thanks

**Comment by andrewlewis** [comment]
Is this feature supported in the IMA SDK? The linked page relates to AdMob and `setContentUrl` is not part of [`AdsRequest`](https://developers.google.com/interactive-media-ads/docs/sdks/android/v3/api/reference/com/google/ads/interactivemedia/v3/api/AdsRequest.html). If you could point to exactly what functionality needs to be exposed via `ImaAdsLoader` that would be useful. Thanks!

**Comment by vindhyapratap** [comment]
Actually , I want ads related to my content, i.e. contextually relevant ads. So is there any method in IMA Ads Loader to map my content or pass my content url so that google will serve ads relevant to my content as it does in Admob AdRequest.setContentUrl i.e. is in below link
https://support.google.com/admob/answer/6270563?hl=en

Thanks!

**Comment by andrewlewis** [comment]
I'm not aware of a way to do this at the moment. Could you ask the IMA team directly at the [IMA SDK forum](https://groups.google.com/forum/#!forum/ima-sdk)? If they have suggestions it would be great if you could reply here and we can look at integrating those into the IMA extension. Thanks.

**Comment by vindhyapratap** [comment]
Thanks for you support!!! @andrewlewis

**Comment by ojw28** [comment]
Closing for now because it sounds like the IMA SDK would need to be modified to support this. Please open a new issue if and when the underlying support is available for us to build on top of. Thanks!
