### ISSUE TITLE
PlayerNotificationManager icon state when player is in STATE_ENDED

### ISSUE THREAD

**Issue by abouda** [google/ExoPlayer#6324]
### [REQUIRED] Issue description
Using `com.google.android.exoplayer2.ui.PlayerNotificationManager`, when ExoPlayer's state changes to STATE_ENDED, the pause icon in the notification does not change to play. (It does change in the expanded notification).

### [REQUIRED] Reproduction steps
- Start playing a stream
- Wait for ExoPlayer to reach end (STATE_ENDED)
- Check the notification

### [REQUIRED] Link to test content
Any content that can end.

### [REQUIRED] A full bug report captured from the device
No bug report since it is a UI issue.

### [REQUIRED] Version of ExoPlayer being used
2.10.4

### [REQUIRED] Device(s) and version(s) of Android being used
Tested on Emulators and devices. Android versions 7/8/9.

![player-ended-notification](https://user-images.githubusercontent.com/4817549/63347868-5c06d200-c358-11e9-9552-498b80646833.gif)

**Comment by tonihei** [comment]
@marcbaechinger  Can you take a look?

**Comment by ojw28** [comment]
I think `PlayerNotificationManager.getActionIndicesForCompactView` needs to use `isPlaying()` to decide which action to display, rather than `playWhenReady`.

**Comment by ojw28** [comment]
Fixed in https://github.com/google/ExoPlayer/commit/eedf50fdcad5263fa3509db2fc702f79b88f0810
