### ISSUE TITLE
Videos Not playing on pre-L devices

### ISSUE THREAD

**Issue by harshmittal29** [google/ExoPlayer#6327]
I am trying to run the videos on pre-L emulator. But it is always throwing following exception
Exception on Android 4.1, 4.2, 4.3 : 
> Caused by: javax.net.ssl.SSLException: Connection closed by peer
>         at org.apache.harmony.xnet.provider.jsse.NativeCrypto.SSL_do_handshake(Native Method)
>         at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:371)
>         at libcore.net.http.HttpConnection.setupSecureSocket(HttpConnection.java:209)
>         at libcore.net.http.HttpsURLConnectionImpl$HttpsEngine.makeSslConnection(HttpsURLConnectionImpl.java:478)
>         at libcore.net.http.HttpsURLConnectionImpl$HttpsEngine.connect(HttpsURLConnectionImpl.java:442)
>         at libcore.net.http.HttpEngine.sendSocketRequest(HttpEngine.java:289)
>         at libcore.net.http.HttpEngine.sendRequest(HttpEngine.java:239)
>         at libcore.net.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:80)
>         at libcore.net.http.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:165)
>         at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:556)
>         at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:443)
>         at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:285)
>         at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:257) 
>         at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83) 
>         at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:102) 
>         at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:65) 
>         at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:170) 
>         at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381) 
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076) 
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569) 
>         at java.lang.Thread.run(Thread.java:856) 

Exception on Android 4.4

> com.google.android.exoplayer2.ExoPlaybackException: java.lang.IllegalStateException
>         at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:397)
>         at android.os.Handler.dispatchMessage(Handler.java:98)
>         at android.os.Looper.loop(Looper.java:136)
>         at android.os.HandlerThread.run(HandlerThread.java:61)

Does exoplayer support videos playing in pre-L devices?

**Comment by tonihei** [comment]
ExoPlayer supports devices from Jellybean onward. There are known issues with video playback on emulators though and you should test on a real device to verify. See https://exoplayer.dev/supported-devices.html (at the bottom under "Emulators")

**Comment by harshmittal29** [comment]
Is javax.net.ssl.SSLException also part of Emulator or does it has to do TLS 1.2 enabling on Android 4.1?

**Comment by tonihei** [comment]
I don't know unfortunately. Please use a real device to verify before we can take a look.
