### ISSUE TITLE
getDuration return error time

### ISSUE THREAD

**Issue by VeiZhang** [google/ExoPlayer#6330]
Before filing a bug:
-----------------------
- Search existing issues, including issues that are closed:
  #6241  #6238 

### [REQUIRED] Issue description
Using ExoPlayer to play some videos, I found some of them get the wrong duration, always return -1, so I can't seek.

### [REQUIRED] Reproduction steps
Using the ExoPlayer demo app, replace `Cats -> Dogs` uri in `media.exolist.json` playlist with the test link content.

### [REQUIRED] Link to test content
I couldn't upload to my repository, please download from https://mbf.me/Tqk7HX , it is a local video file, not online

### [REQUIRED] Version of ExoPlayer being used
the latest.

### [REQUIRED] Device(s) and version(s) of Android being used
Amlogic, android7.1

**Comment by tonihei** [comment]
Some streams don't provide the duration or seek information in the header data and that's why we need to play to the end before knowing the actual duration.

The actual value of getDuration is `C.TIME_UNSET` as documented on the method.
