### ISSUE TITLE
LoadErrorHandlingPolicy in DefaultDrmSession/DefaultDrmSessionManager

### ISSUE THREAD

**Issue by kgrevehagen** [google/ExoPlayer#6334]
### Use case description
I don't want to retry 4xx errors for the DRM license key requests, but 5xx errors I would like to retry with exponential backoff, just as it is already done inside `DefaultDrmSession`.

### Proposed solution
Inject a `LoadErrorHandlingPolicy` to `DefaultDrmSession` via `DefaultDrmSessionManager`, similarly to how `initialDrmRequestRetryCount` is added.

### Alternatives considered
- Write own implementation of `DrmSession` and `DrmSessionManager`, but I don't want to duplicate all of this logic into my own classes just to change one private method.
- Set `initialDrmRequestRetryCount` to 0 and handle it myself inside an implementation of MediaDrmCallback, but this feels kinda backwards.

**Comment by AquilesCanta** [comment]
This should be available in the next release. A commit reference will appear in this issue once the change is pushed to the dev-branch. Once that happens, please give it a try and reach back if you encounter any issues.

**Comment by AquilesCanta** [comment]
We still need to allow custom implementations.
