### ISSUE TITLE
Exoplayer HLS AES Segments Custom URI  intercepting

### ISSUE THREAD

**Issue by Random786** [google/ExoPlayer#6338]
Hello team,  I had a HLS media Url  

"**http://somedomian.name/channel/name_800.m3u8**" 
it had a response output as shown below.  I need to add  some extra characters after **.key**. Before its play in exoplayer

Initially URI = **"https://tv.media.com/streams_live/chnnel_name_800-1566721726000.key"**

After i need to change like this = **"https://tv.media.com/streams_live/channel_name_800-1566721726000.key?token=value"**

and again pass the entire playlist to the Player  how can i fix it kindly please help...  anyone

**Right now getting Response like this :**

#EXTM3U
    #EXT-X-VERSION:3
    #EXT-X-MEDIA-SEQUENCE:6603
    #EXT-X-TARGETDURATION:6
    #EXT-X-KEY:METHOD=AES-128,URI="https://tv.media.com/streams_live/channel_name_800-1566721726000.key",IV=0x00000000000000000000016CC7E45630
    #EXTINF:6.000,
    Sony_HD_800-1566721744000.ts
    #EXTINF:6.000,
    Sony_HD_800-1566721750000.ts
   ..................................................

But i need to pass token after .key link before its go to Exoplayer  like this... 

#EXTM3U
    #EXT-X-VERSION:3
    #EXT-X-MEDIA-SEQUENCE:6603
    #EXT-X-TARGETDURATION:6
    #EXT-X-KEY:METHOD=AES-128,URI="https://tv.media.com/streams_live/channel_name_800-1566721726000.key?token=value",IV=0x00000000000000000000016CC7E45630
    #EXTINF:6.000,
    Sony_HD_800-1566721744000.ts
    #EXTINF:6.000,
    Sony_HD_800-1566721750000.ts
   ..................................................

**Comment by AquilesCanta** [comment]
You can inject a custom [HlsDataSourceFactory](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/source/hls/HlsDataSourceFactory.html) which returns a custom DataSource implementation for type C.DATA_TYPE_DRM which adds the token to the URIs when executing the key requests.

**Comment by tonihei** [comment]
Just to add to what @AquilesCanta already said: You should probably use a `ResolvingDataSource` (on its own or within a `HlsDataSourceFactory`) for this case to inject a custom `Resolver` that adds the token to the URI. This makes the implementation easier and less error-prone than implementing a full custom `DataSource`.

**Comment by Random786** [comment]
@tonihei Can you please show some sample code how it can be done thank you in advance
