### ISSUE TITLE
Provide instructions on local build for Gradle Kotlin DSL in README

### ISSUE THREAD

**Issue by turastory** [google/ExoPlayer#6339]
### [REQUIRED] Use case description
Gradle provides both way to write build script - Groovy, and Kotlin.
While both languages are perfectly fine to write typical build logic, they have different APIs in some cases.

To build locally in Kotlin, one should use `gradle.extra` - `ExtraPropertiesExtension`, which is not defined in the class definition of Gradle.

```kotlin
// ExtraPropertiesExtensions.kt
val ExtensionAware.extra: ExtraPropertiesExtension
    get() = extensions.extraProperties
```

```java
// Gradle.java
public interface Gradle extends PluginAware
```

But Gradle instance **is** ExtensionAware, as the following code shows.

```kotlin
gradle is ExtensionAware == true
```

Guess it is because duck-typing is possible in Groovy - runtime implementation of traits?
So for those who use Kotlin DSL, appropriate instructions are needed.

### Proposed solution
In `settings.gradle.kts`:
```kotlin
if (gradle is ExtensionAware) {
    val extension = gradle as ExtensionAware
    extension.extra["exoplayerRoot"] = "path/to/exoplayer"
    extension.extra["exoplayerModulePrefix"] = "exoplayer-"
    apply(from = File(extension.extra["exoplayerRoot"].toString(), "core_settings.gradle"))
}
```

**Comment by marcbaechinger** [comment]
Where would you expect developers using a Kotlin build script to look for this information?

**Comment by turastory** [comment]
If you're saying where to put this information, then it should be [README](https://github.com/google/ExoPlayer#locally), of course.

Other stuff are not quite different than Groovy's so those are not a big deal, but translating  `gradle.ext` into Kotlin can be hard.

I suggest put this information below the `Locally` section in README.

**Comment by ojw28** [comment]
All of our documentation assumes Groovy. Admittedly other parts are easier to convert (e.g. `implementation 'dependency:version'` to `implementation("dependency:version")`), but it would seem a bit strange to document both just for this specific case. To document both everywhere would be quite noisy. As of writing, [Android Studio's documentation](https://developer.android.com/studio/build#build-files) also only references Groovy.

For the time-being I think it's reasonable that if someone wants to use Kotlin DSL, they can figure out how to do the conversion. The good news is that there's plenty of information available, including information for resolving this specific issue (e.g. by searching for things like "kotlin DSL gradle.ext").

I will keep this issue open, but mark it as low priority for now. We will revisit it as and when there's a clearer demand for Kotlin DSL specific instructions.
