### ISSUE TITLE
Fetch DRM Keys during buffering

### ISSUE THREAD

**Issue by kgrevehagen** [google/ExoPlayer#6341]
### Searched documentation and issues
- [Developer Guide](https://exoplayer.dev/drm.html)
- [GitHub Issue Tracker](https://github.com/google/ExoPlayer/issues)
- [Medium](https://medium.com/google-exoplayer)

### Question
When playing DRM protected content we need to implement `MediaDrmCallback` and especially `executeKeyRequest()` to actually get the license key. This seems to be called when ExoPlayer starts reading the track we want to play, more precise in `onInputFormatChanged` in `MediaCodecRenderer.java`. I'm wondering why this can't happen at the time the `MediaSource` gets prepared, because I think we should have all necessary information at that time and we should then be 100% ready to play when the license is fetched. This doesn't matter when you first play a track, but when playing subsequent tracks in a `ConcatenatingMediaSource`.

From 2.11.0 `DrmSessionManager` should be injected into the `MediaSource`. Since this holds the `MediaDrmCallback`, it makes sense to tie the `DrmSessionManager` and the lifecycle of getting the license key to the same lifecycle as a `MediaSource`. Is there a reason this is not the case?

I feel getting the license key for playback is just as well part of the preparing and buffering phase.

### A full bug report captured from the device
N/A

### Link to test content
N/A

**Comment by marcbaechinger** [comment]
We are working on some changes which will address this issue I think.
@AquilesCanta Can you please quickly comment with a bit more detail?

**Comment by AquilesCanta** [comment]
As @marcbaechinger points out. It's something we are working on. Thanks for your patience.

**Comment by ojw28** [comment]
Duplicating onto https://github.com/google/ExoPlayer/issues/4133, which I've clarified to be tracking all cases where we need to load different DRM keys during playback.
