### ISSUE TITLE
Dash streaming interruptions

### ISSUE THREAD

**Issue by ferglezt** [google/ExoPlayer#6344]
Our application uses two instances of SimpleExoPlayer to support crossfading effect. While one player is playing a track, the other prepares the next so crossfade is available when the first track is finishing. However, we noticed some brief audio interruptions when player one starts to play and player two prepares. This is not a consistent behaviour among all devices, it only happens in certain Huawei and Xiaomi devices; it only happens when playing dash content (MP3 content plays without errors using the same 2-player architecture); and it only happens when the first player is prepared and starts to play while a second instance of ExoPlayer is created and prepared at the same time.

EDIT: The audio interruption also happens during a license download using OfflineLicenseHelper, so I guess this issue is related to DRM session.

EDIT 2: After debugging the application, I noticed that one of the audio interruptions is caused when native MediaDrm.provideKeyResponse is called. I'd like to know if there's an explanation for this and how to avoid it.

We're using ExoPlayer 2.9.1.

This is how we setup each player: 

```
public MediaSource getMediaSource(@NonNull Uri uri) throws MalformedURLException {
	
		DataSource.Factory dataSourceFactory = DataSourceUtil.buildCacheDataSourceFactory(mContext);

		DashMediaSource.Factory dashFactory = new DashMediaSource.Factory(dataSourceFactory);
		if (serializedDownloadAction != null) {
			InputStream inputStream = new ByteArrayInputStream(serializedDownloadAction);
			try {
				DownloadAction downloadAction = DownloadAction.deserializeFromStream(DownloadAction.getDefaultDeserializers(), inputStream);
				dashFactory.setManifestParser(new FilteringManifestParser<>(new DashManifestParser(), downloadAction.getKeys()));
			} catch (IOException e) {
				GeneralLog.e(e);
			}
		}
		return dashFactory.createMediaSource(uri);
	}
```

```
private void getPlayer(String url, Boolean playWhenReady) {
		release();
		Utils.trustEveryone();
		TrackSelection.Factory trackSelection = new AdaptiveTrackSelection.Factory();
		DefaultTrackSelector trackSelector = new DefaultTrackSelector(trackSelection);
		try {
			exoPlayer = ExoPlayerFactory.newSimpleInstance(mContext, getRender(url), trackSelector, buildDrmSessionManager(url));
			exoPlayer.addListener(listener);
			exoPlayer.setVolume(volume);
			exoPlayer.setPlayWhenReady(playWhenReady);
			exoPlayer.prepare(getMediaSource(url));
		} catch (Exception e) {
			GeneralLog.e(e);
			onError(e);
		}
	}
```

And this is a recording where the audio interruptions are noticeable: 

[Evidence](https://i0001.clarodrive.com/s/X9QXsKf5Cydy267)

**Comment by marcbaechinger** [comment]
Can you please do a bug report right after the interruptions? This is kind of hard to reproduce on our side so any information we can get is useful. The bugreport may help us.

I think your thoughts around DRM license make sense. Can you confirm that this does not happen with MP3 because there is no DRM involved? Also, do you have the chance to get the dash stream without DRM so you can test whether this does happen with DASH without DRM?

**Comment by ferglezt** [comment]
> Can you please do a bug report right after the interruptions? This is kind of hard to reproduce on our side so any information we can get is useful. The bugreport may help us.
> 
> I think your thoughts around DRM license makes sense. Can you confirm that this does not happen with MP3 because there is no DRM involved? Also, do you have the chance to get the dash stream without DRM so you can test whether this does happen with DASH without DRM?

- MP3 content plays without interruptions.
- Non licensed Dash content plays without interruptions aswell.

So I guess the problem is caused by how DRM keys are handled internally by Android. Even if I download a license with a different MediaDrmCallback, audio interruptions still happen.

**Comment by ojw28** [comment]
I suspect `provideKeyResponse` is very slow on the affected devices, that decryption is blocked for the duration of the call because the trusted execution environment is single threaded, and that this results in the audio buffer underflowing, causing the audible interruption.

@rrfrias - Could you suggest some next steps for this? Do we have device certification tests that try and ensure `provideKeyResponse` is performant enough?

**Comment by rrfrias** [comment]
> I suspect provideKeyResponse is very slow on the affected devices, that decryption is blocked for the duration of the call because the trusted execution environment is single threaded, and that this results in the audio buffer underflowing, causing the audible interruption.

This is possible. We have made some changes in android 10 to to avoid blocking the decrypt thread while a provideKeyResponse is being processed.  

@ferglezt can you please (email dev.exoplayer@gmail.com)
(a) let us know which devices (make/model) and OS builds/releases you experience the problems with. If there are those that do not exhibit the problem, do let us know that as well.
(b) can you share a bugreport taken on one of the affected devices, after this problem occurs.
(c) if possible share a test app, and a stream for us to test.
