### ISSUE TITLE
HDR playback freeze when surfaceview is attached too late on Huawei P30 PRO (also p20 and other huawei)

### ISSUE THREAD

**Issue by davibe** [google/ExoPlayer#6345]
I attach a patch that allows to reproduce the problem using the official demo of exoplayer 2.9.5.

I added a sample HDR content. When playing on Huawei P30 pro, wait 10 seconds so that the surfaceView is added. Only one frame will be displayed then the video playback freezes while audio goes on.

If you try to go back in the previous screen the app may become unresponsive and occasionally crash.

May be related to #6331 ?

[hdrhuawei.patch.zip](https://github.com/google/ExoPlayer/files/3545174/hdrhuawei.patch.zip)

**Comment by marcbaechinger** [comment]
Can you please provide us with a full bug report taken right after the video freezes? With this we can check some more closely.

**Comment by davibe** [comment]
@marcbaechinger it does not freeze just the video. The entire app becomes unresponsive and after a while it crashes. Next week I see if I can get my hands on the device and create a report
