### ISSUE TITLE
General DRM Error ~ 2000 : Failed to handle key response

### ISSUE THREAD

**Issue by nishantkp** [google/ExoPlayer#6349]
### Content description
I have an issue with playing live stream DRM content (Dash + Widevine).

All the other DRM content will play just fine, but when I try to play live stream with the same flow, ExoPlayer throws an error saying `Failed to handle key response: General DRM error (-2000)`

I am not sure what's wrong.

### Version of ExoPlayer being used
2.10.4

### Device(s) and version(s) of Android 
- Emulator/Any device with API >= 21

### A full bug report
[bugreport](https://github.com/google/ExoPlayer/files/3551365/bugreport-sdk_gphone_x86-QPP3.190404.015.A1-2019-08-28-09-57-16.zip)

**Comment by marcbaechinger** [comment]
Can you provide us with the content url and drm properties so we can look into that?

I've investigated the bug report but it's reporting the native exception only:  Failed to handle key response: General DRM error (-2000)

I also think that the report is from the emulator. Best would be to have the content, if this is not possible, can you provide a bug report from a real device also.

**Comment by gokulkalagara** [comment]
I got the same issue?

**Comment by semuvex** [comment]
I'm facing the same issue with Exoplayer version `2.10.0`. It's happening for live and VOD content.
Actual device is a `Nexus 5X` with OS version `8.1`.
