### ISSUE TITLE
Attempt to invoke virtual method 'int java.io.InputStream.read(byte[], int, int)' on a null object reference

### ISSUE THREAD

**Issue by star-andy** [google/ExoPlayer#6356]
hello 
I play a video from raw and occasionally get errors
webview GONE   to TextureView  VISIBLE  ，You get the following error
![image](https://user-images.githubusercontent.com/15726024/63939337-a3e4d200-ca99-11e9-95e1-934882869cca.png)

![image](https://user-images.githubusercontent.com/15726024/63939273-7009ac80-ca99-11e9-8ba3-5b5bc2bd715a.png)
Android device   RK3288  7.1

**Comment by marcbaechinger** [comment]
I think you should move the entire creation of the data source into the factory. These 2 lines in you try-block which are above 

`DataSource.Factory factory = ...`

should be inside the `createDataSource` method of the factory. Do not call `open` youself. This should be done by the media source on demand.

**Comment by star-andy** [comment]
My personal reasons have been solved. Thank you very much
