### ISSUE TITLE
How to play several musics at the same time

### ISSUE THREAD

**Issue by itchenning** [google/ExoPlayer#6358]
I want to create several player, but only one player can play.
Help me, thanks a lot!

Sample:
```
// I want to play 3 musics at the same time, and can set volume for each one anytime.
val player1 = SimpleExoPlayer()
val player2 = SimpleExoPlayer()
val player3 = SimpleExoPlayer()
   ...
   ...
player1.volume = 1F
player2.volume = 1F
player3.volume = 1F

player1.start()
player2.start()
player3.start()
   ...
   ...
fun onVolChange(player: SimpleExoPlayer, vol: Float) {
   player.volume = vol
}
```

**Comment by marcbaechinger** [comment]
You are saying 'only one player can play'. This can happen if there are not enough media codec instances available. Each player requires an instance so these three players compete with each other. 

There may be ways to make this work with software decoders which do not have the same restrictions like hardware decoders. Unfortunately the information you provide is not sufficient to verify that my guess from above is correct and help you some further. Can you provide us with a bug report which you create right after playback fails? This will allow me to check.

**Comment by itchenning** [comment]
Like these code below, if I replace Exoplayer  as MediaPlayer , it can work ,  it can play 3 rings at the same time.But use Exoplayer ,  it only play 1 ring. the ring is rondom choice.


     for (ringinfo in mMixInfo.ringList) {
            val player = ExoPlayerFactory.newSimpleInstance(this , DefaultTrackSelector())
            val defaultDataSourceFactory = DefaultDataSourceFactory(this , "audio/mpeg")
            val concatenatingMediaSource = ConcatenatingMediaSource()
            val path = ConfigManager.getRingPath(ringinfo.ringID)
            val mediaSource = ProgressiveMediaSource.Factory(defaultDataSourceFactory) //
                .createMediaSource(Uri.parse(path))
            concatenatingMediaSource.addMediaSource(mediaSource)
            val vol = ringinfo.vol / 100F
            player.volume = vol
            player.playWhenReady = true
            player.prepare(concatenatingMediaSource)
            mPlayers.add(player)
        }

**Comment by marcbaechinger** [comment]
Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/question.md).
