### ISSUE TITLE
Can I use ClippingMediaSource on a ConcatenatingMediaSource?

### ISSUE THREAD

**Issue by dexterleng** [google/ExoPlayer#6359]
I have an audiobook but it is split into multiple mp3 files arbitrarily:

```
[ "file01.mp3", "file02.mp3" ]
```

The chapters in the audiobook are represented by the file and the offset in milliseconds the chapter starts on:

```
[{ name: "chapter one: something, file: "file01.mp3", offset: 0 },
{ name: "chapter two: something, file: "file01.mp3", offset: 900 },
{ name: "chapter three: something, file: "file02.mp3", offset: 10 },
...]
```

Is it possible to use ConcatenatingMediaSource to put multiple files together and them trim the start and end with ClippingMediaSource so that it represents a chapter? This will allow me to use ConcatenatingMediaSource again to join all the ClippingMediaSources to represent the audiobook.

The documentation for ClippingMediaSource says that it only works with single-period. Does this mean no ConcatenatingMediaSource support?

**Comment by marcbaechinger** [comment]
Currently ClippingMediaSource supports only media sources with a single period. So the ConcatenatingMediaSource is not supported. See also #6234 around this topic.

I mark this issue as a duplicate and close. Please comment on the other issue or reopen if you think it's required.

**Comment by dexterleng** [comment]
@marcbaechinger would it be possible to clip and then join them?

For example:

file01.mp3 is split into chapter1, chapter2 (first chunk),

file02.mp3 is split into chapter2 (second and last chunk), and chapter3.

I would then join the two chunks to form chapter 2.

**Comment by tonihei** [comment]
@dexterleng  That should be possible. However, note that the items are still treated separately in our UI for example. There is #4868 to improve support for this.
