### ISSUE TITLE
Not able to build for 4.2.2

### ISSUE THREAD

**Issue by sgavali** [google/ExoPlayer#636]
I'm getting lots of error related to methods and API used which are Android 5.x.
Does TOT ExoPlayer works only for API level 21 ? How to build for API level 16 ?

**Comment by ojw28** [comment]
You need to build using the most recent SDK and API level. That doesn't mean that it wont run on earlier API levels, it just means that it'll make use of features on more recent versions when running on newer devices.

**Comment by sgavali** [comment]
Thanks, app built on 5.x looks to be working on 4.x device.
