### ISSUE TITLE
Failed to handle key response: General DRM error (-2000)

### ISSUE THREAD

**Issue by gokulkalagara** [google/ExoPlayer#6363]
While playing in exo-player mpd video (DRM WIDEVINE + DASH)

ExoPlayerImplInternal: Playback error.
com.google.android.exoplayer2.drm.DrmSession$DrmSessionException: android.media.MediaDrm$MediaDrmStateException: Failed to handle key response: General DRM error

**Comment by marcbaechinger** [comment]
Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md).

**Comment by gokulkalagara** [comment]
```
E/MediaDrm-JNI: Illegal state exception: Failed to handle key response: General DRM error (-2000)

E/ExoPlayerImplInternal: Playback error.
com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.drm.DrmSession$DrmSessionException: android.media.MediaDrm$MediaDrmStateException: Failed to handle key response: General DRM error
```

**DRMCallBack**

```
 HttpMediaDrmCallback httpMediaDrmCallback = new HttpMediaDrmCallback(
 "https://test.frostech.in/cms-test/05E5F765721CCD6F01682B2E2B0B3EC10B3DF63D2C76DB85",
                    false,factory);
 httpMediaDrmCallback.setKeyRequestProperty("customdata",AUTH_TOKEN);
         

DrmSessionManager<FrameworkMediaCrypto> drmSessionManager = new DefaultDrmSessionManager<>(
                    C.WIDEVINE_UUID,
                    FrameworkMediaDrm.newInstance( C.WIDEVINE_UUID),
                    httpMediaDrmCallback,
                    null,true);

player = ExoPlayerFactory.newSimpleInstance(activity(),
                    new DefaultRenderersFactory(activity()),
                    trackSelector, new DefaultLoadControl(),drmSessionManager);
```

**Dash Media source**
```
 return new DashMediaSource.Factory(dashChunkSourceFactory, manifestDataSourceFactory)
                    .createMediaSource(uri);
```

**Comment by marcbaechinger** [comment]
As the issue templates states, it would be very valuable if you could send us a link to the test content (along with the required DRM properties). If this is not possible for some reasons, can you please create a bug report right after the exception happened as well as some information on which devices and OS versions this has been observed.

You can find the issue template [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md) for further reference.
