### ISSUE TITLE
Add asset for exo_controls_shuffle_off rather than applying transparency in code

### ISSUE THREAD

**Issue by pawaom** [google/ExoPlayer#6364]
Before filing a question:
-----------------------
how to change color of Shuffle and Repeat Toggle button in exo_playback_control_view  when selected

The way to change color for Shuffle button is 

```
<ImageButton
            android:layout_weight="1"
            android:id="@id/exo_shuffle"
            android:tint="@android:color/holo_orange_light"    
            style="@style/ExoMediaButton.Shuffle" />
```

when its clicked the transparency changes to 0.3f 

But I want to change the color to White , when the button is selected 

how can this be done

thanks in advance

**Comment by marcbaechinger** [comment]
The [logic to apply the transparency is in code](https://github.com/google/ExoPlayer/blob/85c10b02567b66ecfaaaacfd0ba9389b41bf919e/library/ui/src/main/java/com/google/android/exoplayer2/ui/PlayerControlView.java#L819). You can not change this easily without changing the source code of PlayerControlView.

The style of the button is [defined in a style](https://github.com/google/ExoPlayer/blob/85c10b02567b66ecfaaaacfd0ba9389b41bf919e/library/ui/src/main/res/values/styles.xml#L54). You can customize the existing style or apply another style. It's possible to change the background color of the button or the tint of the icon on the button:

For example: 

```
  <style name="ExoMediaButton.Shuffle">
    <item name="android:background">#FFFF0000</item>
    <item name="android:tint">#FF00FF00</item>
    <item name="android:src">@drawable/exo_controls_shuffle</item>
    <item name="android:contentDescription">@string/exo_controls_shuffle_description</item>
  </style>
```

With the style above, the background of the button is red and the shuffle icon is tinted green. Besides my color choice being ugly, that works fine and you can customize as you want. 

There is [a blog post around customizing the UI on Medium](https://medium.com/google-exoplayer/customizing-exoplayers-ui-components-728cf55ee07a) if you want more details about customizing the UI.

**Comment by pawaom** [comment]
thanks for the reply, can this feature be added in future updates

**Comment by marcbaechinger** [comment]
Which feature are you referring to? The things I explained above are already included?
What change do you suggest to be put in the next release?

**Comment by ojw28** [comment]
@marcbaechinger - I think we should add an `exo_controls_shuffle_off` asset that has the transparency baked in. It's inconsistent that we're applying the transparency in code just for this case. We already have `exo_controls_repeat_off` for the equivalent repeat mode, for example.

As a separate point, we should also try and move the transparency in `setButtonEnabled` into a style or resource somehow.

**Comment by ojw28** [comment]
Fixed by: https://github.com/google/ExoPlayer/commit/a12c6641d9a3c49a6d36ab89da7ac6888aedcfa6, https://github.com/google/ExoPlayer/commit/e4eb6b7ea90cf273591f47a9ed19f2439d74a8f7, https://github.com/google/ExoPlayer/commit/e567f8edd0ddb5075a8fccd88abb4171eaa5a25c
