### ISSUE TITLE
How to disable AV sync and allow Audio and video to free run independently? 

### ISSUE THREAD

**Issue by pearleye** [google/ExoPlayer#6365]
### [REQUIRED] Searched documentation and issues
https://exoplayer.dev/

### [REQUIRED] Question
How to disable AV sync and allow Audio and video to free run independently?
We are using a custom video Data source which has DVB MPEG TS data.

### A full bug report captured from the device
NA

### Link to test content
NA

**Comment by andrewlewis** [comment]
Audio will play in real time (assuming you aren't using speed adjustment). The audio track position is used as the player position by default. To override this behavior you can subclass the audio renderer and return `null` from `getMediaClock`. Having done that you can rely on rendering based on wallclock time (but A/V sync may drift as the audio position may not advance perfectly linearly), or have another renderer (for example, a `NoSampleRenderer`) be the clock for the player. You may also want to override `MediaCodecVideoRenderer.processOutputBuffer` to change the logic used to present video frames.
