### ISSUE TITLE
Custom derived values for timebar?

### ISSUE THREAD

**Issue by dexterleng** [google/ExoPlayer#6368]
Is there a way I can override some functions in PlayerControlView so that the timebar duration and progress are different? I have offsets in my mp3 files to denote start of a track. I have to calculate duration and progress relative to those offsets.

**Comment by ojw28** [comment]
It's not a final class, so in theory you can extend it and override methods.

Whether there's a method for the specific thing is that you want to do is a different question. It's somewhat unlikely; it's not possible for us to anticipate all of the types of customization that anyone would want to do. If you want to propose a method that you can override that'll enable what you need, please feel free to send a pull request to the `dev-v2` branch. You can also just fork the class into your own code-base and edit it directly, for cases where you need custom behavior.
