### ISSUE TITLE
Black Screen Video playback | Audio Playback working Fine | DRM Content | One plus Android 9

### ISSUE THREAD

**Issue by prashant-prajapati** [google/ExoPlayer#6369]
A black screen is displaying while playing live stream DRM protected content of the low resolution. While High-resolution stream is working fine. No error logs and not crash.

**Comment by ojw28** [comment]
We need you to fill out the [issue template](https://github.com/google/ExoPlayer/issues/new?assignees=&labels=content+not+playing%2C+needs+triage&template=content_not_playing.md&title=) completely to investigate this type of issue. Please do so (in this issue, rather than filing a new one).
