### ISSUE TITLE
Android API version 15

### ISSUE THREAD

**Issue by drayan85** [google/ExoPlayer#637]
Build app using ExoPlayer library support only Android API version 16 and above. We would to like to support API version from 15 and found 'MediaCodecs' is the one causing issue.

Is there any way to work around to support API version 15.

thanks you in advance.

**Comment by ojw28** [comment]
There is no easy way of doing this. The hard way is to write your own TrackRenderer implementations for audio and video, that bridge onto software decoders (e.g. ffmpeg) that you could then bundle inside your apk. The VP9 and Opus extensions are examples of this approach (and could be used if VP9 and Opus are acceptable codecs for your use case).
