### ISSUE TITLE
 java.lang.AbstractMethodError (DataSource.addTransferListener)

### ISSUE THREAD

**Issue by Random786** [google/ExoPlayer#6372]
I am facing a issue with this code getting an error related to **java.lang.AbstractMethodError: abstract method "void com.google.android.exoplayer2.upstream.DataSource.addTransferListener(com.google.android.exoplayer2.upstream.TransferListener)"** 

Previously i am using 2.8.1 Its working amazing without any error i upgraded to latest version in this i am facing this issue even i did not done any changes in codes.. Playing in 2.8.1 but not playing in 2.9.6 

Anyone please fix the code.....  Explanation please i read lots of articles and ExoPlayer Devs website but nothing i got informative..

My ExoPlayer Version Codes:
```
  implementation 'com.squareup.okhttp3:okhttp:4.1.0'
    implementation 'com.google.android.exoplayer:exoplayer:2.9.6'
    implementation 'com.squareup.okhttp3:logging-interceptor:4.1.0'
    implementation 'com.google.android.exoplayer:extension-okhttp:2.6.0'


    OkHttpClient okHttpClient; = new OkHttpClient
                .Builder()
                .connectTimeout(1, TimeUnit.MINUTES)
                .readTimeout(1,TimeUnit.MINUTES)
                .retryOnConnectionFailure(false)
                .addInterceptor(new Interceptor() {
                    @NonNull
                    @Override
                    public Response intercept(@NonNull Chain chain) throws IOException {
                      .................
                    return request;
                   } })
                .build();
    dataSourceFactory = new OkHttpDataSourceFactory(okHttpClient, agent, null, 
     CacheControl.FORCE_NETWORK);
       MediaSource hlsMediaSource = new 
        HlsMediaSource.Factory(dataSourceFactory).createMediaSource(Uri.parse(PlayLink));
          player.prepare(hlsMediaSource, true, false);
            player.setPlayWhenReady(true);
```

**Crash Report:** :    

```
--------- beginning of crash
2019-09-02 19:19:46.039 13121-13167/com.inapp.simplejio E/AndroidRuntime: FATAL EXCEPTION: ExoPlayerImplInternal:Handler
    Process: com.inapp.simplejio, PID: 13121
    java.lang.AbstractMethodError: abstract method "void com.google.android.exoplayer2.upstream.DataSource.addTransferListener(com.google.android.exoplayer2.upstream.TransferListener)"
        at com.google.android.exoplayer2.source.hls.HlsChunkSource.<init>(HlsChunkSource.java:151)
        at com.google.android.exoplayer2.source.hls.HlsMediaPeriod.buildSampleStreamWrapper(HlsMediaPeriod.java:514)
        at com.google.android.exoplayer2.source.hls.HlsMediaPeriod.buildAndPrepareMainSampleStreamWrapper(HlsMediaPeriod.java:446)
        at com.google.android.exoplayer2.source.hls.HlsMediaPeriod.buildAndPrepareSampleStreamWrappers(HlsMediaPeriod.java:353)
        at com.google.android.exoplayer2.source.hls.HlsMediaPeriod.prepare(HlsMediaPeriod.java:131)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.maybeUpdateLoadingPeriod(ExoPlayerImplInternal.java:1529)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.updatePeriods(ExoPlayerImplInternal.java:1392)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:506)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:198)
        at android.os.HandlerThread.run(HandlerThread.java:65)
```

**Comment by ojw28** [comment]
As of 2.9.0 you need to enable Java 8, as per the [release notes](https://github.com/google/ExoPlayer/blob/release-v2/RELEASENOTES.md). See also the [developer guide](https://exoplayer.dev/hello-world.html), and in particular the need to add the following to the right place in your build.gradle file(s):
```
compileOptions {
  targetCompatibility JavaVersion.VERSION_1_8
}
```

**Comment by Random786** [comment]
I already had Java 8 in my build.gradle file     the problem is something with this lines
```
  DefaultBandwidthMeter bandwidthMeter = new DefaultBandwidthMeter();
        dataSourceFactory = new OkHttpDataSourceFactory(okHttpClient, agent, null, CacheControl.FORCE_NETWORK);
        MediaSource hlsMediaSource = new HlsMediaSource.Factory(dataSourceFactory).createMediaSource(Uri.parse(PlayLink));
        player.prepare(hlsMediaSource);
        player.setPlayWhenReady(true);
```
in this 4 lines of codes getting error app closing..

**Comment by ojw28** [comment]
* Please can you share your full `build.gradle` file for the module that experiences this issue?
* If you modify the ExoPlayer demo app to include the same lines of code, does that fail in the same way? If not, that would still point toward the way your application's build is configured.

**Comment by Random786** [comment]
apply plugin: 'com.android.application'

android {
    compileSdkVersion 29
    buildToolsVersion "29.0.1"
    defaultConfig {
        applicationId "com.inapp.simplejio"
        minSdkVersion 16
        targetSdkVersion 29
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.appcompat:appcompat:1.0.2'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.2.0'

    implementation 'com.amitshekhar.android:android-networking:1.0.2'

    implementation 'com.squareup.picasso:picasso:2.71828'
    implementation 'com.squareup.okhttp3:okhttp:3.12.1'
    //implementation 'com.google.android.exoplayer:exoplayer:2.8.4'
    implementation 'com.google.android.exoplayer:exoplayer:2.9.6'
    implementation 'com.squareup.okhttp3:logging-interceptor:4.1.0'
    implementation 'com.google.android.exoplayer:extension-okhttp:2.6.0'
    implementation 'androidx.recyclerview:recyclerview:1.0.0'
    implementation 'androidx.cardview:cardview:1.0.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'


    //API calling
    implementation 'com.android.volley:volley:1.1.1'
}




    **I thought the problem created by Bandwidth meter** 
**Error:**:  j

> ava.lang.AbstractMethodError: abstract method "void com.google.android.exoplayer2.upstream.DataSource.addTransferListener(com.google.android.exoplayer2.upstream.TransferListener)"

        //this is the line that's  working .... in 2.8.1 & 2.8.4 working without any issues But not working above 2.8.4 versions.. i checked 2.9.0 and 2.9.1 and 2.9.3 and 2.9.6 
        dataSourceFactory = new OkHttpDataSourceFactory(okHttpClient,  CustomUserAgent, new DefaultBandwidthMeter());


   MediaSource hlsMediaSource = new 
    HlsMediaSource.Factory(dataSourceFactory).createMediaSource(Uri.parse(PlayLink));
      player.prepare(hlsMediaSource, true, false);
        player.setPlayWhenReady(true);


    }


    private LoopingMediaSource buildMediaSource(Uri uri) {

        return buildMediaSource(uri, null);
    }

    private LoopingMediaSource buildMediaSource(Uri uri, @Nullable String overrideExtension) {


        return new LoopingMediaSource(new HlsMediaSource.Factory(dataSourceFactory).createMediaSource(uri));

    }

**Comment by ojw28** [comment]
Setting Java 8 looks correct. I'm not really sure what's going on in the post above. It's so poorly formatted it's extremely difficult to read. Please could you clean it up and fix the formatting so that it's a bit more readable?

For us to investigate this further I think we'll probably need concrete reproduction steps. Is it possible for you to make a small demo project that reproduces the problem, which you can share with us?
