### ISSUE TITLE
how to switch dynamically between hls and dash in exoPlayer ?

### ISSUE THREAD

**Issue by Navidhp** [google/ExoPlayer#6374]
hi , we have several server streams. Some servers have HLS and some others have DASH. can I write switch between HLS and DASH dynamically when a movie is played with a player ?

```
Exoplayer Version : 2.10.3
```

**Comment by ojw28** [comment]
You would have to re-prepare the player to switch from one to the other, which is not seamless. We do not support seamlessly switching between HLS and DASH.
