### ISSUE TITLE
Unable to launch the Application using exo player 2.10.0

### ISSUE THREAD

**Issue by namespace7** [google/ExoPlayer#6378]
The application crashes every time i launch it on Android Q .

**Comment by namespace7** [comment]
Logcat 

   --------- beginning of crash
2019-09-03 18:38:29.672 25158-25158/com.namespace.av1test E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.namespace.av1test, PID: 25158
    java.lang.NoSuchMethodError: No static method metafactory(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/CallSite; in class Ljava/lang/invoke/LambdaMetafactory; or its super classes (declaration of 'java.lang.invoke.LambdaMetafactory' appears in /apex/com.android.runtime/javalib/core-oj.jar)
        at com.google.android.exoplayer2.util.SlidingPercentile.<clinit>(SlidingPercentile.java:38)
        at com.google.android.exoplayer2.upstream.DefaultBandwidthMeter.<init>(DefaultBandwidthMeter.java:260)
        at com.google.android.exoplayer2.upstream.DefaultBandwidthMeter.<init>(DefaultBandwidthMeter.java:243)
        at com.namespace.av1test.videoStream.<init>(videoStream.java:52)
        at java.lang.Class.newInstance(Native Method)
        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
        at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:43)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1243)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3182)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by namespace7** [comment]
Code sample 

public class videoStream extends AppCompatActivity {
    private PlayerView simpleExoPlayerView;
    private SimpleExoPlayer player;
    private View loading;
    private ImageButton changeQuality;
    private TrackGroupArray trackGroups;
    private TrackSelector trackSelector;
    private  MappingTrackSelector selector;
    private  TrackSelection.Factory videoTrackSelectionFactory;
    String space= "\n";
    Uri URL;
    private DefaultBandwidthMeter bandwidthMeter = new DefaultBandwidthMeter();

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        getSupportActionBar().hide();
        this.getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN, WindowManager.LayoutParams.FLAG_FULLSCREEN); //will hide the status bar
        setContentView(R.layout.activity_video_switch);
        setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE); //will rotate the screen
        URL = Uri.parse("http://192.168.2.5/output.mpd");
        //  URL = Uri.parse("http://www.bok.net/dash/tears_of_steel/cleartext/stream.mpd");  //dash
        // URL = Uri.parse("http://cbsnewshd-lh.akamaihd.net/i/CBSNHD_7@199302/index_700_av-p.m3u8"); hls link
        Log.e("URL________________ ", String.valueOf(URL));
        initializePlayer(bandwidthMeter);
        // Toast.makeText(getBaseContext(), "Player launched!", Toast.LENGTH_LONG).show();
        player.addListener(new ExoPlayer.EventListener() {

            @Override
            public void onTimelineChanged(Timeline timeline, Object manifest, int reason) {
            }

            @Override
            public void onTracksChanged(TrackGroupArray trackGroups, TrackSelectionArray trackSelections) {
                Log.d("_____________________ ", String.valueOf(space));

            }
            @Override
            public void onLoadingChanged(boolean isLoading) {
            }

            @Override
            public void onPlayerStateChanged(boolean playWhenReady, int playbackState) {
                switch (playbackState) {
                    case ExoPlayer.STATE_READY:
                        loading.setVisibility(View.GONE);
                        break;
                    case ExoPlayer.STATE_BUFFERING:
                        loading.setVisibility(View.VISIBLE);
                        break;
                }
                if (playbackState == Player.STATE_IDLE || playbackState == Player.STATE_ENDED ||
                        !playWhenReady)
                {

                    simpleExoPlayerView.setKeepScreenOn(false);
                } else {
                    // This prevents the screen from getting dim/lock
                    simpleExoPlayerView.setKeepScreenOn(true);
                }
            }
            @Override
            public void onRepeatModeChanged(int repeatMode) {

            }


            @Override
            public void onShuffleModeEnabledChanged(boolean shuffleModeEnabled) {
            }

            @Override
            public void onPlayerError(ExoPlaybackException error) {
                Toast.makeText(getBaseContext(), "Error Occurred While Fetching the Url,Please check the Url ", Toast.LENGTH_LONG).show();
                player.stop();
                player.setPlayWhenReady(true);
                initializePlayer(bandwidthMeter);
            }
            @Override
            public void onPositionDiscontinuity(int reason) {
            }

            @Override
            public void onPlaybackParametersChanged(PlaybackParameters playbackParameters) {
            }

            @Override
            public void onSeekProcessed() {
            }

        });
        player.setPlayWhenReady(true); //run file/link when ready to play.
    }
    private void initializePlayer(DefaultBandwidthMeter bandwidthMeter) {
        loading = findViewById(R.id.loading);
        changeQuality = findViewById(R.id.change_quality);
        videoTrackSelectionFactory = new AdaptiveTrackSelection.Factory(bandwidthMeter);
        trackSelector = new DefaultTrackSelector(videoTrackSelectionFactory);
        player = ExoPlayerFactory.newSimpleInstance(this, trackSelector);
        selector = (MappingTrackSelector) trackSelector;
        simpleExoPlayerView = new SimpleExoPlayerView(this);
        simpleExoPlayerView = (SimpleExoPlayerView) findViewById(R.id.player_view);
        simpleExoPlayerView.setUseController(true);//set to true or false to see controllers
        simpleExoPlayerView.requestFocus();
        simpleExoPlayerView.setPlayer(player);
        DataSource.Factory dataSourceFactory = new DefaultDataSourceFactory(this, Util.getUserAgent(this, "StreamTest"), bandwidthMeter);
        // MediaSource videoSource = new HlsMediaSource(URL, dataSourceFactory, 1, null, null);  //for hls stream
        //   player.prepare(videoSource);
        //dash configuration

        DashMediaSource dashMediaSource = new DashMediaSource(URL, dataSourceFactory,
                new DefaultDashChunkSource.Factory(dataSourceFactory), null, null);
        player.prepare(dashMediaSource);
        changeQuality.setOnClickListener(new View.OnClickListener() {
            public void onClick(View v) {
                //change_Quality();
            }
        });
    }

    private void change_Quality() {

    }

    private void hideSystemUi() {
        simpleExoPlayerView.setSystemUiVisibility(View.SYSTEM_UI_FLAG_LOW_PROFILE
                | View.SYSTEM_UI_FLAG_FULLSCREEN
                | View.SYSTEM_UI_FLAG_LAYOUT_STABLE
                | View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY
                | View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION
                | View.SYSTEM_UI_FLAG_HIDE_NAVIGATION);
    }
    @Override
    protected void onStop() {
        super.onStop();
        player.release();

    }
    @Override
    protected void onStart() {
        super.onStart();

    }
    @Override
    protected void onResume() {
        super.onResume();
        hideSystemUi();
    }

    @Override
    protected void onPause() {
        super.onPause();

    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        player.release();
    }

}

**Comment by namespace7** [comment]
the url contains the Dash stream.
suggestion will be appreciated

**Comment by ojw28** [comment]
Have you enabled Java 8 in your `build.gradle` file? This has been a requirement since 2.9.0, as per the [release notes](https://github.com/google/ExoPlayer/blob/release-v2/RELEASENOTES.md).

**Comment by namespace7** [comment]
enabling java 8 does the job , but only the sound is been played(no video).
I'm trying to test Av1 codec stream on android Q
as mentioned here
**https://medium.com/google-exoplayer/exoplayer-2-10-whats-new-15d344eaa8b9**

**Comment by ojw28** [comment]
Please provide complete information if you want us to investigate the AV1 issue.

**Comment by namespace7** [comment]
File:
[demo.zip](https://github.com/google/ExoPlayer/files/3570189/demo.zip)

What I'm trying to do?
This file contains the AV1 codec dash stream which I'm trying to play, in android Q emulator, using Exo Player library  version 2.10.0.
the application is only playing the audio(no video) from the stream file url.

does the file actually contains both audio as well as video ?
Well,yes . the file plays perfectly on VLC as well as using ffplay
Screenshot 
![image](https://user-images.githubusercontent.com/29954682/64186992-62836680-ce8d-11e9-8ef5-88de7ae0b303.png)

**Comment by ojw28** [comment]
I think the emulator doesn't include an AV1 decoder yet. Please try testing on a physical device.
