### ISSUE TITLE
Does not support s263 video.

### ISSUE THREAD

**Issue by Ood-Tsen** [google/ExoPlayer#638]
Hi,
I found that the AtomParser does not handle the atom 's263' properly.

The player can't identified s263 track to video track.

Is there any plan to support it ?

We can download it from this link.

https://drive.google.com/open?id=0B7AjFwY8h0HrTjdITW9JeGl2SDQ

**Comment by Ood-Tsen** [comment]
I just add a quick fix for s263.

https://github.com/google/ExoPlayer/pull/643

**Comment by ojw28** [comment]
Merged, so marking fixed!
