### ISSUE TITLE
Vivo Z1 Pro - Frequent MediaCodec.CodecException.ERROR_RECLAIMED failure

### ISSUE THREAD

**Issue by sharish** [google/ExoPlayer#6381]
Searches:
-----------------------

1. [q=MediaCodec.CodecException](https://github.com/google/ExoPlayer/issues?utf8=%E2%9C%93&q=MediaCodec.CodecException) - No result

2. [q=0xffffffe0](https://github.com/google/ExoPlayer/issues?utf8=✓&q=0xffffffe0)

Issue #5649 - Not related
Issue #3896 - Stale
Issue #1036 & Issue #978 - Outdated

### [REQUIRED] Issue description

Facing MediaCodec.CodecException.ERROR_RECLAIMED after 2-3 minutes of video playback on DRM protected content

**Exception Log:**
```
E ExoPlayerImplInternal: Internal runtime error.
E ExoPlayerImplInternal: android.media.MediaCodec$CodecException: Error 0xffffffe0
E ExoPlayerImplInternal: 	at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
E ExoPlayerImplInternal: 	at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:2608)
E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1113)
E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:654)
E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:575)
E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:326)
E ExoPlayerImplInternal: 	at android.os.Handler.dispatchMessage(Handler.java:102)
E ExoPlayerImplInternal: 	at android.os.Looper.loop(Looper.java:224)
E ExoPlayerImplInternal: 	at android.os.HandlerThread.run(HandlerThread.java:65)
I MediaCodec: kWhatStop or kWhatRelease
E EventLogger: playerFailed [209.88, 176.18, window=0, period=0]
E EventLogger: com.google.android.exoplayer2.ExoPlaybackException: android.media.MediaCodec$CodecException: Error 0xffffffe0
E EventLogger: 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:397)
E EventLogger: 	at android.os.Handler.dispatchMessage(Handler.java:102)
E EventLogger: 	at android.os.Looper.loop(Looper.java:224)
E EventLogger: 	at android.os.HandlerThread.run(HandlerThread.java:65)
E EventLogger: Caused by: android.media.MediaCodec$CodecException: Error 0xffffffe0
E EventLogger: 	at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
E EventLogger: 	at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:2608)
E EventLogger: 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1113)
E EventLogger: 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:654)
E EventLogger: 	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:575)
E EventLogger: 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:326)
E EventLogger: 	... 3 more
```
### [REQUIRED] Reproduction steps
1. Build sample demo app from v2.10.4 Exo or [download this apk](https://github.com/sharish/BugReferences/blob/master/ExoplayerIssue_6381/Exo_2.10.4.demo-noExtensions-debug.apk?raw=true)
2. Expand `Widevine DASH Policy Test (GTS)`
3. Open `WV: HDCP not specified`
4. Play the video for a while approx 3 minutes

### [REQUIRED] Link to test content
```json
[
  {
    "name": "Widevine DASH Policy Tests (GTS)",
    "samples": [
      {
        "name": "WV: HDCP not specified",
        "uri": "https://storage.googleapis.com/wvmedia/cenc/h264/tears/tears.mpd",
        "drm_scheme": "widevine",
        "drm_license_url": "https://proxy.uat.widevine.com/proxy?video_id=d286538032258a1c&provider=widevine_test"
      }
    ]
  }
]
```

### [REQUIRED] A full bug report captured from the device
1. [Bug report](https://github.com/sharish/BugReferences/blob/master/ExoplayerIssue_6381/Vivo-bugreport-1951-PKQ1.181030.001-2019-09-04-13-38-07.zip?raw=true)
2. [Logcat logs](https://raw.githubusercontent.com/sharish/BugReferences/master/ExoplayerIssue_6381/vivo_logcat.txt)

### [REQUIRED] Version of ExoPlayer being used
v2.10.4

### [REQUIRED] Device(s) and version(s) of Android being used
Personally reproduced: 
Vivo Z1 Pro - Android 9 - **100% reproducible**
User reports  :
Samsung Galaxy Tab A 8.0 - Android 7.1.1
Samsung SM-J415F - Android 8.1.0
Vivo 1806 - Android 9

**Comment by ojw28** [comment]
I would expect `ERROR_RECLAIMED` to occur something else requires the same resource and is deemed higher priority by the underlying platform.

* Is it possible that there's an app that's behaving very badly on your Vivo Z1 Pro test device. Does factory resetting the device and installing only your app make the problem go away? Do other apps such as Netflix and Play Movies, both of which also play DRM protected content, work correctly on this device?
* Is it possible that your application is doing something that could be causing this issue?

Note that we've not received any significant volume of this issue from other uses, so it seems most likely to be specific to your device (possibly sporadic across other devices but with a low occurrence rate), or specific to your application.

**Comment by sharish** [comment]
@ojw28 Thanks for your input.

1. _Is it possible that there's an app that's behaving very badly on your Vivo Z1 Pro test device. Does factory resetting the device and installing only your app make the problem go away?_

    No. This was a newly bought device with no apps (expect system and default apps). We bought this device purely based on crashlytics non-fatals.

2. _Does factory resetting the device and installing only your app make the problem go away?_

   No. Tried factory reset and installed **only** exoplayer demo application and was still facing the same. 

3. _Do other apps such as Netflix and Play Movies, both of which also play DRM protected content, work correctly on this device?_

- Netflix plays smoothly. Tried to play few videos for more than an hour without a single interruption
- Play Movies - able to replicate the issue. However, I could notice that player gets reset and re-initialized once this error is encountered and continue streaming from where it left.

   - [Play movies bugreport](https://github.com/sharish/BugReferences/blob/master/ExoplayerIssue_6381/Vivo-PlayMovies-bugreport-1951-PKQ1.181030.001-2019-09-12-11-51-58.zip?raw=true)
  - [Play movies logcat](https://raw.githubusercontent.com/sharish/BugReferences/master/ExoplayerIssue_6381/play-movies-logcat.txt)

4. _Is it possible that your application is doing something that could be causing this issue?_

   No. Btw, the application reference I'm mentioning is **exo player demo application** which is based on commit https://github.com/google/ExoPlayer/commit/85c10b02567b66ecfaaaacfd0ba9389b41bf919e. This is not version-specific issue as I'm able to replicate on `v2.9.6` as well.

Few points to add,

1. Based on crashlytics non-fatal reports, 77% of users encountered this issue came from devices manufactured by `Vivo` and among those, 95% of them came from `Vivo Z1 Pro`. This matches what you said in note section.

2. We are fixing this issue like the workaround done by `Play Movies` - Kill and re-initialize the player. However there is an experience lag as this re-initialization takes some time and buffers are also destroyed. Also, license cost overhead is also to be considered as we are nearly hitting 30license calls for an hour video through this workaround(Offline licensing is another workaround to solve this which is a problem for another time)

Questions:

> I would expect ERROR_RECLAIMED to occur something else requires the same resource

Would like to know what resource the player is abusing as I tried looking into memory patterns which were totally fine. I'm clueless what happens at the native DRM level where this problem likely to take place

**Comment by ojw28** [comment]
Thanks for the additional context. We'll get hold of a Vivo Z1 Pro and see if we can reproduce on our side. Marking as a device specific issue for now (I know other devices are affected, but the Z1 Pro accounts for around three quarters of all occurrences, so we should focus on that first).

> Would like to know what resource the player is abusing as I tried looking into memory patterns which were totally fine.

I don't think the player is abusing any resources. It's more likely that something else on this device is behaving incorrectly.

**Comment by ojw28** [comment]
We've ordered a Vivo Z1 Pro device to try and reproduce this, but it's going to take a while for it to be delivered. We'll update this issue once we've received it and tried to reproduce.

**Comment by ojw28** [comment]
I got hold of a device with an almost identical build fingerprint:
```
vivo/1951/1951:9/PKQ1.181030.001/compiler08262240:user/release-keys
```
compared to your device:
```
vivo/1951/1951:9/PKQ1.181030.001/compiler08262240:user/release-keys
```

Unfortunately, I cannot reproduce the issue. I tried following the reproduction steps with the ExoPlayer demo app, and also playing content in Play Movies whilst looking in logcat for any signs of a codec exception. In both cases playback seems to work fine.

Please could you try installing all updates for your device, just in case the issue was fixed by a security patch or similar?

Given we're unable to reproduce this on our side, I think it'll be quite difficult for us to make further progress on the issue, unfortunately.

**Comment by sharish** [comment]
@ojw28 Thanks for procuring and trying to figure out the issue. Unfortunately, we are also not able to reproduce the issue since the day you commented. I assume some silent patch has been done from Vivo as we have not done any os upgrade. 

Also to note that our analytics indicate that the error rate from this device, for this reason, dropped from ~280 per day to ~30 per day gradually. I assume that the issue is solved by the manufacturer.

Thanks for your time debugging the issue. Very much appreciated.
