### ISSUE TITLE
ControlPlayerView above ViewPager with playerviews = Hide/Dismiss not working

### ISSUE THREAD

**Issue by nbourdin** [google/ExoPlayer#6382]
### [REQUIRED] Searched documentation and issues
I search in some stackoverflow and questions in the ExoPlayer repo.
I also browsed the ExoPlayer source code

### [REQUIRED] Question
Hello

For my project I have some architecture constraints :
My exoplayer version is 2.8.4

Activity code
```
class Activity {

	exoPlayerInstance: ExoPlayer

	control.player = exoPlayerInstance

	pager.onCurrentPagerChanged { currentFragment ->
		currentFragment.playerView.player = exoPlayerInstance
		currentFragment.prepareNewMedia()
	}
}
```
Activity layout
```
<Activity>
	<ViewPager as pager/>
	<PlayerControlView as control
		height=« match_parent »
		width=« match_parent » 	
	/>
</Activity>
```

Layout fragment in the viewpager
```
<Fragment>
	<PlayerView
		useController:false
	/>
</Fragment>
```

I also create the file exo_player_control_view.xml to override the control UI.
To sum up, I need to have a single `PlayerControlView` above my view pager with multiple fragments

My problem is the following : 

When I swipe the view pager, 
the player control above is rightly updated with the new prepared media (thanks to the 'currentFragment.playerView.player = exoPlayerInstance’)
	exo_duration, exo_progress, play/pause are ok

But when I tap on the current displayed player view, in the view pager, the controller doesn’t dismiss rightly such as the default behavior (5000ms show timeout)

I tried to tweak some attributes in the xml/code :
In the playerControlView, When I put 
- `show_timeout:2000` -> the controller is dismissed after 2000ms but never be shown again after a screen tap
- `show_timeout:0` -> the controller is always visible and cannot be hidden when I tap the screen

Is it possible to link dynamically my `ControlPlayerView` instance and a set of `PlayerView` ?

**Comment by andrewlewis** [comment]
If you think it's a bug in ExoPlayer's widgets please could you provide a minimal sample project so we can reproduce the issue? Otherwise, I'm afraid we don't really have resources to debug issues with custom layouts. Thanks.
