### ISSUE TITLE
Calculate RMS while streaming sometimes cause the audio to be corrupted

### ISSUE THREAD

**Issue by nguyenhuy3588** [google/ExoPlayer#6383]
Hi all, thanks for your helps, i successfully calculated RMS value for visualizing while streaming HLS audio in the previous post: [RMS calculate while streaming](https://github.com/google/ExoPlayer/issues/6063). With the previous solution, now i sometimes faces this issue when streaming audio, it look like calculating RMS in handleBuffer callback of TeeAudioProcessor make the streaming processing slow so that the playing audio is corrupted. I have tried to make the calculating into another thread but the audio ByteBuffer is not accessible. Here i post 2 pieces of code that currently i'm trying.

- The previous code that i used to calculate RMS value:

![image](https://user-images.githubusercontent.com/16719961/64246478-0c6afd80-cf37-11e9-95b0-9004aa0307d6.png)

![image](https://user-images.githubusercontent.com/16719961/64246500-18ef5600-cf37-11e9-9fd4-0ae07d2f9fe3.png)

- The one that i have tried to move calculating process into other thread but ByteBuffer inaccessible:

![image](https://user-images.githubusercontent.com/16719961/64246635-5ce25b00-cf37-11e9-89e7-3496e2536562.png)

![image](https://user-images.githubusercontent.com/16719961/64246651-65d32c80-cf37-11e9-9b5c-8c66360fb83b.png)

Is there any solution that i can process the RMS but not slow down the processing time of streaming? Thanks for reading.

**Comment by andrewlewis** [comment]
I think you'd need to copy the data out of the buffer to make this work, but I'm afraid we don't have time to give detailed guidance on this kind of niche use case.
