### ISSUE TITLE
Documentation error: setId3Output should be setMetadataOutput

### ISSUE THREAD

**Issue by root-ansh** [google/ExoPlayer#6385]
###  Searched documentation and issues  
- [x] documentation  
- [x] issues 

###  Question
I am new to exoplayer and video streaming in general. I was following the basic docs [here](https://exoplayer.dev/hello-world.html#attaching-the-player-to-a-view), when i found this:  

![image](https://user-images.githubusercontent.com/31290636/64253658-5a820000-cf3b-11e9-8d65-e7520914262d.png)  

What is id3 meta data and where can we find `setId3Output ` ? is that a function made by developer or is that a library's function? Also, I did not find `setTextOutput(..)` function but rather `addTextOutput(...) function`

### A full bug report captured from the device
n.a  

### Link to test content
n.a

**Comment by ojw28** [comment]
It's a documentation error. It should say `setMetadataOutput`.

**Comment by ojw28** [comment]
Sorry, I mean `addMetadataOutput` :).

**Comment by root-ansh** [comment]
Oh i get it. thanks, @ojw28 !

**Comment by root-ansh** [comment]
fixed both names in prs #6386  and #6387
