### ISSUE TITLE
How can I change default controller buttons programatically?

### ISSUE THREAD

**Issue by officialsachinverma** [google/ExoPlayer#6389]
The requirement is if I select a song it started playing and if I am selecting same song again it is paused. but I want the play/pause button in controller to get changed as well.
I am not able to find any way to do it.

**Comment by ojw28** [comment]
This is not something we support. It's not possible for us to write off-the-shelf UI components that also support all arbitrary customizations that developers want to make. For this type of feature, you probably need to implement your own UI component. Feel free to fork the ones from the ExoPlayer library as a starting point.
