### ISSUE TITLE
Video source skips in Concatenate media source

### ISSUE THREAD

**Issue by gb103** [google/ExoPlayer#6393]
### [REQUIRED] Content description
Trying to play multiple video clips using ConcatenatingMediaSource in LOOPING (although issue is without looping too), if the clip count is less than 3 then everything is fine but if it is more than 3 then 4th video always skips and go to first media source in the first iteration irrespective of total clip count (4 or 5 or 6) and then from 2nd iteration it becomes right.
No ERROR logs found.

### [REQUIRED] Link to test content
The code snipped which I am using is like below :
for (int i = 0; i < uris.length; i++) {
    mediaSources[i] = buildMediaSource(uris[i], null, chunkless);
}
MediaSource mediaSource = mediaSources.length == 1 ? mediaSources[0]
        : new ConcatenatingMediaSource(false, true, mediaSources);

### [REQUIRED] Version of ExoPlayer being used
v2.9.3

### [REQUIRED] Device(s) and version(s) of Android being used
Have checked on multiple devices with OS 9.0 and 8.0

### [REQUIRED] A full bug report captured from the device
Logs confidential (Will try to send on email)

**Comment by ojw28** [comment]
@tonihei - PTAL

**Comment by gb103** [comment]
this is the function definition which I used for concatenateMediaSource,
 /**
   * @param mediaSources The {@link MediaSource}s to concatenate. 
   * @param isAtomic Whether the concatenating media source will be treated as atomic,
   * @param useLazyPreparation Whether playlist items are prepared lazily. If false, all manifest
  public ConcatenatingMediaSource(boolean isAtomic, boolean useLazyPreparation, MediaSource... mediaSources) {
    this(/* isAtomic= */ isAtomic, useLazyPreparation, new DefaultShuffleOrder(0), mediaSources);
  }

**Comment by gb103** [comment]
One more thing which I observed, It is after some fix time or fix amount of data, at which it skips only in 1st iteration. can  it be anything with LoadControl ?

**Comment by tonihei** [comment]
Would it be possible to provide the files you are using for playback? We use the same basic set-up in our demo app and that's working fine.

**Comment by gb103** [comment]
@google-oss-bot @tonihei This issue has been resolved and it's wrong at my side to assume that it is skipping the video. Because of some code logic, video (with 4 clips in concatenateMediaSource) is getting restarted, which usually happening when it is in progress of playing 3rd clip, which give impression to me that is skipping the clip at fixed time. Thanks for your support.
