### ISSUE TITLE
Add Seekbar in MediaStyle notifications for Android 10 devices

### ISSUE THREAD

**Issue by pawaom** [google/ExoPlayer#6394]
Add Seekbar in MediaStyle notifications for Android 10 devices

While going through new features of android 10 I came across a feature of  Seekbar in MediaStyle notifications here: 

https://developer.android.com/about/versions/10/features#media-notifications

please add this feature to Exoplayer notifications also

**Comment by marcbaechinger** [comment]
This already works if you are setting a valid `MediaSessionCompat` token to the `PlayerNotificationmanager`:

```
mediaSession = new MediaSessionCompat(this, "ExoPlayer");
mediaSession.setActive(true);
notificationManager.setMediaSessionToken(mediaSession.getSessionToken());
```

To make this work the [media session needs the required information](https://developer.android.com/about/versions/10/features#media-notifications):

1) `playbackState.position` must have a valid value
2) the metadata object which is set to the media session for the item currently being played must have the duration set with `MediaMetadata.METADATA_KEY_DURATION`
3) The media session must advertise support for `ACTION_SEEK_TO`

You can either provide these media session properties yourself, in case you are maintaining the media session yourself. 

The probably easier alternative is making use of the `MediaSessionConnector` of the [media session extension ](https://github.com/google/ExoPlayer/tree/release-v2/extensions/mediasession) of the ExoPlayer library. There is a [blog post on Medium which introduces to the media session extension](https://medium.com/google-exoplayer/the-mediasession-extension-for-exoplayer-82b9619deb2d).

With the extension all required properies are automaitaclly set and the notification shows the seekbar.
