### ISSUE TITLE
Live HD channels not playing correctly

### ISSUE THREAD

**Issue by anandsingh2903** [google/ExoPlayer#6395]
I am trying to play live HD channels but the stream is not playing correctly.
Video is showing one frame and then after 1 or few milliseconds later just switches to another static frame.

I have also enabled FLAG_ALLOW_NON_IDR_KEYFRAMES but still facing this issue.

Here is the link of the stream : http://korbafiagi.mediantbroadband.com/live/ch5/playlist.m3u8

**Comment by ojw28** [comment]
Please properly fill in the issue template.
