### ISSUE TITLE
FLAC in mp4 typo in AtomParsers

### ISSUE THREAD

**Issue by kgrevehagen** [google/ExoPlayer#6396]
### [REQUIRED] Issue description
When trying to play FLAC in mp4, it goes through the `AtomParsers.java` and near the bottom in `parseAudioSampleEntry()` there is a check if `childAtomSize == Atom.TYPE_dfLa`. It seems like a typo and it should be `childAtomType == Atom.TYPE_dfLa` instead, just as all the others. This is where it sets the initializationData, so obviously this condition will never be hit.

### [REQUIRED] Reproduction steps
Try to play a FLAC in mp4(e.g. using DASH) and observe that the `initializationData` in `FlacDecoder` is never set.

### [REQUIRED] Link to test content
I don't have any testable content to send at the moment, but I can probably create a test file if you need it.

### [REQUIRED] A full bug report captured from the device
N/A

### [REQUIRED] Version of ExoPlayer being used
2.10.4

### [REQUIRED] Device(s) and version(s) of Android being used
100% reproducible on Pixel 3 with Android 9

**Comment by andrewlewis** [comment]
Thanks for reporting! We will submit a fix.
