### ISSUE TITLE
AspectRatioFrameLayout.RESIZE_MODE_FIT not working on smarttv with pie

### ISSUE THREAD

**Issue by SystemRestored** [google/ExoPlayer#6401]
**[REQUIRED] Issue description**
The recent update in MI TV 4a pro 32 inch with android Pie, having issues with the aspectrationframelayout.resize_mode_fit, resize_mode_zoom.  Until previous version, it was working fine. The latest update given and now its not functioning at all.

**[REQUIRED] Reproduction steps**
On MI tv 4a pro use the exoplayer demo app with simple exoplayerview and aspectratio fame layout.
make a button to resize the screen to zoom or fit  using playerView.setResizeMode(AspectRatioFrameLayout.RESIZE_MODE_ZOOM); or
playerView.setResizeMode(AspectRatioFrameLayout.RESIZE_MODE_FIT);

The screen is on same size on PIE.

**[REQUIRED] Link to test content**
[
  {
    "name": "Widevine DASH Policy Tests (GTS)",
    "samples": [
      {
     "name": "Apple 4x3 basic stream",
        "uri": "https://devstreaming-cdn.apple.com/videos/streaming/examples/bipbop_4x3/bipbop_4x3_variant.m3u8"
      }
    ]
  }
]

**[REQUIRED] Version of ExoPlayer being used**
v2.9.3

**[REQUIRED] Device(s) and version(s) of Android being used**

MI TV 4A PRO

**Comment by andrewlewis** [comment]
Can you reproduce this on any other devices? Is only DRM playback affected?

**Comment by SystemRestored** [comment]
all streams are affected. Only this happening with MI tv with pie edition. There is no effect on playback but that view AspectRatioFrameLayout resize modes are not working at all.

**Comment by andrewlewis** [comment]
Have you reported this issue to Xioami? I don't think there's much we can do here unless you see the issue on other devices.
