### ISSUE TITLE
Audio only on some phones when playing Widevine DASH content with night mode activated

### ISSUE THREAD

**Issue by danha306** [google/ExoPlayer#6402]
### Issue description
On some phones no video streams are being shown when the phone is in "night mode" and Widevine protected DASH content is being played. The audio plays normally, but no video is showing. Disabling "night mode" causes the player to behave correctly with video being displayed. Playing content that is not protected by Widevine works as expected with "night mode" activated.

### Reproduction steps
The issue has been reproduced by a remote team member using a OnePlus 7 Pro running OxygenOS 9.5.11.GM21BA, using the ExoPlayer 2.10.4 demo app and the default demo app content. We only have a few other phones available to us with "night mode" capabilities, but none of them could reproduce the issue.

The issue could be reproduced with the "WV: Secure HD (cenc,MP4,H264)" stream in the "Widevine DASH: MP4, Hs64" category, and possibly other Widevine encrypted streams but those were not tested.

### Link to test content
As mentioned above, it could be reproduced with the content provided in the 2.10.4 demo app so we have no content to link here.

### A full bug report captured from the device
Since the team member who can reproduce the issue is working remotely and is not an Android developer we have had some issues getting a full bug report. Since it can be reproduced with the demo app we hope that a full report might not be needed at this point, but otherwise we will try to get a full bug report available as soon as possible.

### Version of ExoPlayer being used
2.10.4

### Device(s) and version(s) of Android being used
Device tested with "night mode" experiencing the issue:
OnePlus 7 Pro, using OxygenOS 9.5.11.GM21BA (Android 9)

Devices tested with "night mode" without issues:
OnePlus 5T, using OxygenOS 9.0.8 (Android 9)
Samsung SM-A5200F, using Android 8.0.0
Huawei CLT-L29, using Android 8.1.0

**Comment by andrewlewis** [comment]
Have you contacted the OxygenOS developers about this? It sounds like a limitation in how they've implemented night mode.

There probably isn't much we can do here, and this doesn't sound like an ExoPlayer issue.

**Comment by danha306** [comment]
We have not yet contaced the OxygenOS developers since we were not sure if the issue was with their OS or ExoPlayer. However if you believe the issue lies with them we'll contact them as soon as possible.

**Comment by andrewlewis** [comment]
I think it's likely that the problem is further down the stack than ExoPlayer, probably in the OS.
