### ISSUE TITLE
Standard UI for front and back buttons in Notification and Lockscreen with player.hasNext() and player.hasPrevious()

### ISSUE THREAD

**Issue by pawaom** [google/ExoPlayer#6404]
Standard UI for front and back buttons in Notification and Lockscreen with player.hasNext() and player.hasPrevious()

When we use player.hasNext() and player.hasPrevious() the following behavior is observed

when there is no further song for player.hasNext() 

on the player it shows

![20190906_165441_rmedited](https://user-images.githubusercontent.com/28686824/64424636-381ced80-d0c7-11e9-8cd9-1d9cc4bd4bb5.jpg)

and in notification it shows 

![20190906_165519_rmedited](https://user-images.githubusercontent.com/28686824/64424649-43701900-d0c7-11e9-9958-8025703cdf9a.jpg)

But when there is no prior song for player.hasPrevious() 

in player 
![20190906_165341_rmedited](https://user-images.githubusercontent.com/28686824/64424705-639fd800-d0c7-11e9-8700-c3242ebe31d1.jpg)
it shows

and notification 

![20190906_165413_rmedited](https://user-images.githubusercontent.com/28686824/64424729-74504e00-d0c7-11e9-81e5-d3f34bae427f.jpg)

can we have a standard behavior for both the cases

**Comment by andrewlewis** [comment]
@marcbaechinger Please could you take a look?

**Comment by pawaom** [comment]
can we force to show the next button in the first case

**Comment by marcbaechinger** [comment]
This should be in sync indeed. 

The behavior for the PREVIOUS button is that it needs to be active in all cases. In case there is no previous media item it does seek to the start of the current window. So regarding the screenshots above the behavior in the notification is correct, while the `PlayerControlView` is wrong.

I wonder though why it isn't in sync. I can not repro this with the demo app.

When checking the conditions for enabling the button in the player control view and including the action in the notification I see the following expression:

PlayerControlView:
```   
   boolean isSeekable = window.isSeekable;
   enablePrevious = isSeekable || !window.isDynamic || player.hasPrevious();
```
PlayerNotificationManager:
```
   enablePrevious = window.isSeekable || !window.isDynamic || player.hasPrevious();
```

So this look as it works as it should.

I noticed that the order of the button in the player view in your screenshot is not the one defined by the standard layout file exo_playback_control_view. It seem like you customized the order. Can you verify that it is the ExoPlayer library code which does define the state of the button in the player control view? Or do you apply your own logic? Did you change ids of the ui components within that layout file?

It would be helpful if you can post the layout file you are using to customize the UI. This way I can check for instance whether the ids are correct. Can you post this file here?

**Comment by ojw28** [comment]
Note: We also made [some fixes](https://github.com/google/ExoPlayer/commit/eb6859e436b5ef7735b83d3e38b94b6826c97c7e) for consistency of navigation across UI components in 2.10.0, so if you're using an earlier version you may find that updating to 2.10.0 or later is sufficient to resolve this issue.
