### ISSUE TITLE
Changing ad source in runtime (Exoplayer IMA extension)

### ISSUE THREAD

**Issue by root-ansh** [google/ExoPlayer#6409]
### [REQUIRED] Searched documentation and issues   
Yes

### [REQUIRED] Question
is There a way to change Ad source XML  while the ad is running? For eg, if i created an ad source before the actual playback (using  `Uri adXMLUri =Uri.parse(AD_XML_URL)`, `imaAdsLoader = new ImaAdsLoader(this,adXMLUri )` and  `AdsMediaSource adsMediaSource = new AdsMediaSource( mediaSource, dataSourceFactory, imaAdsLoader,adViewProvider)` ),
is there a way i could run them all again and change this `AD_XML_URL`  everytime the ad runs completely?will exoplayer be able to catch this change and update its ads/video stream and player ui accordingly? I also know there is some way to add  adEventListener , as discussed in #3322 , but i am unable to figure out how. would be great to get some insights for that too.

### A full bug report captured from the device
Not Applicable.

### Link to test content
Not Applicable.

**Comment by root-ansh** [comment]
Can i have an update on this? I would be very much grateful.

**Comment by root-ansh** [comment]
Can i have an update on this? I would be very much grateful.
@ojw28 , @andrewlewis

**Comment by andrewlewis** [comment]
If you want to change the ad tag, currently you'd need to create a new `ImaAdsLoader` instance and re-prepare the player with a new source. That will interrupt playback, though, so it's probably better to make a VMAP ad tag that has all the ad breaks you need in it. Is that possible? Or if you're trying to achieve something else could you describe it in a bit more detail? Thanks.

`ImaAdsLoader.Builder` lets you set an `AdEventListener`.

**Comment by root-ansh** [comment]
@andrewlewis  We need to change ads at fixed intervals. But These ads are not predefined, and would be fetched from the server at run time, just a few seconds before the the scheduled time.  

I am  thinking of a solution in which we(The dev) will control ad playback .  Like, for eg if I need to show an ad a 20 seconds from the start of content, There will be callback that will aware some function  at 20th second, which will further stop the content , start the ad playback and then resume the content

**Comment by root-ansh** [comment]
any update on this?  @andrewlewis

**Comment by root-ansh** [comment]
You know, I am perfectly fine with `ImaAdLoader`'s current working and i can provide an empty vmap response like String with just the ad points, but i want to have a observer-publisher kind of functionality: The exoplayer should run the content and vmap as usual, but should fire an event for requesting vast tag (via an interface) from the observer (i.e the activity/fragment implementing such interface)    

From what i could guess, exoplayer loads all the ads in vmap  at the start of playback only and just  runs those loaded ads when an adpoint comes.

**Comment by andrewlewis** [comment]
@root-ansh Sorry for the delayed response. My understanding is that in the VMAP specification your top level ad tag can point to other ad tags which are loaded just before playback reaches the corresponding cue point.

It sounds like you may be trying to implement this on the client rather than having an ad server that provides a VMAP ad tag as described. In that case you probably need to implement a custom `AdsLoader`, but I'm afraid we don't have detailed documentation on how to do that yet.

**Comment by andrewlewis** [comment]
#4680 will likely solve this request once we get round to it (and even if it doesn't, it will likely provide a good starting point for doing what's described here), so I will close this.
