### ISSUE TITLE
Optimize DefaultExtractorsFactory sniffing order

### ISSUE THREAD

**Issue by lsgfly** [google/ExoPlayer#6410]
when we select extractor, we makes a pass through all of the available extractor util we find the 
correct extractor. I find the sniff of MatroskaExtractor will cost 25ms. 
80% of our videos are in MP4 format.
Can I  put the Mp4Extractor as the first  place.  
```
public Extractor selectExtractor(ExtractorInput input, Uri uri)
        throws IOException, InterruptedException {
      for (Extractor extractor : extractors) {
        try {
          if (extractor.sniff(input)) {
            this.extractor = extractor;
            break;
          }
        } catch (EOFException e) {
          // Do nothing.
        } finally {
          input.resetPeekPosition();
        }
      }
}
```
```
  public synchronized Extractor[] createExtractors() {
    Extractor[] extractors = new Extractor[FLAC_EXTRACTOR_CONSTRUCTOR == null ? 12 : 13];
    extractors[0] = new MatroskaExtractor(matroskaFlags);
    extractors[1] = new FragmentedMp4Extractor(fragmentedMp4Flags);
    extractors[2] = new  Mp4Extractor(mp4Flags);
    extractors[3] = new Mp3Extractor(mp3Flags);
    extractors[4] = new AdtsExtractor();
    extractors[5] = new Ac3Extractor();
    extractors[6] = new TsExtractor(tsMode, tsFlags);
    extractors[7] = new FlvExtractor();
    extractors[8] = new OggExtractor();
    extractors[9] = new PsExtractor();
    extractors[10] = new WavExtractor();
    extractors[11] = new AmrExtractor();
    if (FLAC_EXTRACTOR_CONSTRUCTOR != null) {
      try {
        extractors[12] = FLAC_EXTRACTOR_CONSTRUCTOR.newInstance();
      } catch (Exception e) {
        // Should never happen.
        throw new IllegalStateException("Unexpected error creating FLAC extractor", e);
      }
    }
    return extractors;
  }
```

**Comment by ojw28** [comment]
There is nothing stopping you from doing this yourself by injecting your own `ExtractorsFactory` when building a `ProgressiveMediaSource` (using [this API](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/source/ProgressiveMediaSource.Factory.html#setExtractorsFactory-com.google.android.exoplayer2.extractor.ExtractorsFactory-)).

As mentioned on https://github.com/google/ExoPlayer/issues/6325#issuecomment-526294126, we should also revisit the sniffing order:

> At some point we should also revisit the sniffing order. In particular, I don't think we've ever looked at how much data each extractor sniffs, on average, before establishing the media is not in its own format. If there are extractors that have to sniff a lot of data to do this, we should consider whether it's possible to push them down in the order without increasing the chances of false positives.

Let's use this issue to track doing that. @andrewlewis - Please reassign within your team as appropriate.

**Comment by ojw28** [comment]
In addition to the commit referenced above, further improvements were made in https://github.com/google/ExoPlayer/commit/7df99381c1be7df680c61f35cc3ec798c26ed1a7 and https://github.com/google/ExoPlayer/commit/1f17756ad2cb4f427bac57de8d0911147307cd06.
