### ISSUE TITLE
Playback of a file that's still being written

### ISSUE THREAD

**Issue by steveford-obs** [google/ExoPlayer#6411]
### [REQUIRED] Searched documentation and issues
I've found a similar question from 2016 (https://github.com/google/ExoPlayer/issues/2095), which I assume was resolved as the original poster didn't come back, but am not sure if what was described there should still be all that's required.

### [REQUIRED] Question
I'm trying to play a file (MPEG TS) that's still being written and have implemented my own DataSource by copying FileDataSource, modifying it so that open() doesn't store the size of the file and returns C.LENGTH_UNSET, with read() returning 0 if the end of file is reached, so C.RESULT_END_OF_INPUT isn't returned from the function.

What I'm finding is that if playback is delayed by 3 seconds, to allow time for some data to be written to the file, then only 3 seconds will be played before playback freezes. Likewise if playback is delayed by 10 seconds then only 10 seconds will be played.

This is how ExoPlayer is being set up:
```
        TrackSelector trackSelector = new DefaultTrackSelector();
        DefaultLoadControl loadControl = new DefaultLoadControl();

        SimpleExoPlayer player = ExoPlayerFactory.newSimpleInstance(this, trackSelector, loadControl);
        ExtractorsFactory extractorsFactory = TsExtractor.FACTORY;
        DataSource.Factory dataSourceFactory = new MyFileDataSource.Factory();

        ExtractorMediaSource.Factory mediaFactory = new ExtrcatorMediaSource.Factory(dataSourceFactory, extractorsFactory);

        Uri uri = Uri.parse("file:////test.ts");
        ExtractorMediaSource mediaSource = mediaFactory.createMediaSource(uri);

        PlayerView playerView = findViewById(R.id.player_view);
        playerView.setPlayer(player);
        player.setPlayWhenReady(true);
        player.prepare(mediaSource);
```
From what I can tell from the exoplayer code, despite the DataSource returning C.LENGTH_UNSET when opened, the ExtractorMediaPeriod still seems to be attempting to load the whole file.

So....should subclassing DataSource still be all that's required to get this use-case to work, or do we need to also implement our own MediaSource (and MediaPeriod?) classes as well?

**Comment by ojw28** [comment]
> So....should subclassing DataSource still be all that's required to get this use-case to work

I think so, yes.

> with read() returning 0 if the end of file is reached

This violates the contract of the interface you're implementing, [which says](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/upstream/DataSource.html#read-byte:A-int-int-):

> Otherwise, the call will block until at least one byte of data has been read and the number of bytes read is returned.

You can only return 0 if the `readLength` input argument is 0, which wont be the case here. Hence, when you're waiting for more data, you need to block in `read` rather than return 0. I'd suggest you give that a try and see if it resolves your problem.

**Comment by steveford-obs** [comment]
Thanks for the quick reply sorry I missed the fact that read() shouldn't return 0 unless requested.
I've modified the DataSource read() so it waits to read data, if EOF is reached, before returning, but the behaviour is the same.

On a superficial scan of the code, it looks as though the ExtractorMediaPeriod is attempting to load the entire file before it starts playing, but is this being controlled by the LoadControl, and so could we reduce the amount of data it's attempting to load at the start by implementing our own LoadControl and reducing the buffer sizes (in particular DEFAULT_MAX_BUFFER_MS, given the file includes video data)?

**Comment by ojw28** [comment]
> it looks as though the ExtractorMediaPeriod is attempting to load the entire file before it starts playing

We don't do this. It wouldn't work for large files, because we'd run out of memory. `LoadControl` requires some minimum amount of media to be loaded before playback starts, but that should just delay the playback starting until your `DataSource` has allowed that amount to be read.

Do you see multiple `open()` and `close()` calls being made on the `DataSource`, or do you just see a single `open()` call? The only thing I can think of is that we think it's a live stream, and so re-open from position=0. I think you'll need to find a way for us to reproduce in order for us to investigate further.

**Comment by steveford-obs** [comment]
> We don't do this. It wouldn't work for large files, because we'd run out of memory.

Yes, that's what I thought.

> LoadControl requires some minimum amount of media to be loaded before playback starts, but that should just delay the playback starting until your DataSource has allowed that amount to be read.

Yes and the minimum with video appears to be 50 seconds, hence the question about reducing this so playing will start sooner, given that fresh data will be written to the file frequently. So should providing our own LoadControl, with suitably reduced buffer sizes, result in less data being read initially before playback is started?

I will have to get back to you about the multiple calls to open/close and as you may have gathered by now, this is a live stream, so making it reproducible isn't going to be easy but will give it some thought.

Ultimately, writing data to a file is a short term solution while learning about exoplayer, in the hope that once it works with a file then replacing it with a DataSource that feeds the data in directly will be fairly easy.

**Comment by ojw28** [comment]
> Yes and the minimum with video appears to be 50 seconds

The minimum for playback to start is `DEFAULT_BUFFER_FOR_PLAYBACK_MS`, which is `2.5s`.

> this is a live stream

How is the data fetched? If it's over http(s) then it should work just to give the URL directly to the player, without doing anything special.

**Comment by steveford-obs** [comment]
2.5s should be fine; I was thinking it was defined by:

```
/**
 * The default maximum duration of media that the player will attempt to buffer, in milliseconds.
 * For playbacks with video, this is also the default minimum duration of media that the player
 * will attempt to ensure is buffered.
 */
 public static final int DEFAULT_MAX_BUFFER_MS = 50000;
```

No, it's not over http, which is why it won't be easy, but I can't say any more than that, sorry.

**Comment by steveford-obs** [comment]
Sorry for the delay in updating this ticket. I now have an environment in which I can try things, so I've been verifying the problem was reproducible, and I now have some logs and more info.

The following is using a modified version of FileDataSource that returns C.LENGTH_UNSET for open() and is using a newInputStream for the file itself.

What I'm seeing is that until the read() of the data source returns C.RESULT_END_OF_INPUT, playback doesn't start and the player is in the STATE_BUFFERING until this time.

Here are some excerpts from logcat:

2019-08-21 14:25:42.805 prepare file:////storage/self/primary/Movies/file.ts
2019-08-21 14:25:42.812 onPlayerStateChanged: playWhenReady=true, state=1
2019-08-21 14:25:42.813 onPlayerStateChanged: playWhenReady=true, state=2
2019-08-21 14:25:42.840 open //storage/self/primary/Movies/file.ts, position=0, length=-1

I then see read() being called continually, which always returns with at least some of the requested amount of data, and in this case the player state never changes to STATE_READY.
If I add a limit to the amount of data that's returned by read() and at this point return C.RESULT_END_OF_INPUT (the limit was set to 5MB, but the actual value doesn't affect the result), the following then appears in logcat at this point:

2019-08-21 14:26:04.370 Ending at 5MB
2019-08-21 14:26:04.370 close //storage/self/primary/Movies/file.ts
2019-08-21 14:26:04.378 onPlayerStateChanged: playWhenReady=true, state=3

And playback now starts.

**Comment by ojw28** [comment]
Did you mean to attach the modified `FileDataSource`, and ideally the test file you're using as well, so that we can reproduce? We need concrete reproduction steps to investigate the issue.

**Comment by steveford-obs** [comment]
I can share the modified DataSource, but the data file is very large and, as implied by the topic, it isn't a fixed size, it grows as time goes on. Is there any way to do this privately?

**Comment by ojw28** [comment]
You can email `dev.exoplayer@gmail.com`.

> If I add a limit to the amount of data that's returned by read() and at this point return C.RESULT_END_OF_INPUT (the limit was set to 5MB, but the actual value doesn't affect the result)

Given this is part of the reproduction steps, the fact the file grows over time doesn't see relevant. You just need to provide a sample file that's larger than a limit with which we can reproduce the problem (30 seconds of media would be more than enough).

**Comment by ojw28** [comment]
I replied by email with a root cause and a number of possible ways in which you can fix this. Please close this issue if this is sufficient. Thanks!

**Comment by steveford-obs** [comment]
Thank you very much, Olly. I tried your first suggestion and that proved that it could be made to work.
