### ISSUE TITLE
[Feature request] Support setAllowedCapturePolicy in AudioAttributes for Android 10

### ISSUE THREAD

**Issue by Ethan1983** [google/ExoPlayer#6413]
### [REQUIRED] Use case description
Android 10 added setAllowedCapturePolicy in SDK's AudioAttributes for apps to disable/enable audio capture for each track independently in Android 10.

https://developer.android.com/reference/android/media/AudioAttributes.Builder.html?hl=en#setAllowedCapturePolicy(int)

### Proposed solution
Please add a similar/same API to com.google.android.exoplayer2.audio.AudioAttributes.

### Alternatives considered
The only workaround is to request use global AudioManager API (AudioManager.setAllowedCapturePolicy) to update the preference before each and every playback request.

https://developer.android.com/reference/android/media/AudioManager.html?hl=en#setAllowedCapturePolicy(int)

**Comment by ojw28** [comment]
We already have a pending change for this. It'll be pushed to `dev-v2` shortly.

**Comment by Ethan1983** [comment]
Thanks for the update.

**Comment by ojw28** [comment]
Support added in https://github.com/google/ExoPlayer/commit/73b922ee59fa565a1fabaf5411bdea7ca81ee3fc.
