### ISSUE TITLE
Views on top, overlapping SurfaceView during pause

### ISSUE THREAD

**Issue by GensaGames** [google/ExoPlayer#6414]
### [REQUIRED] Issue description
All views on top, will be overlapping `SurfaceView` during pause. For ex. create and show any Dialog on top of `SurfaceView` and then hide. After hiding `Dialog` view still overlap the `SurfaceView` of the Video. 

This ticket is duplicated from the closed [3160](https://github.com/google/ExoPlayer/issues/3160). But problem still exist on **some** devices! This issue is specific for us. In our case, it's custom board, based on Android P, which pass all the CTS and GTS among with Google certification. 

### [REQUIRED] Reproduction steps
1. To reproduce the issue, we need to use clean Surface View with DRM streams. 2. Disable network and let `ExoPlayer` fail. 3. Create and hide any View on top of `SurfaceView`. [Issue] Views will be overlapping on the `SurfaceView`, after it's hiding. 

It's also possible to reproduce with ExoPlayer sample app. For this purpose, need to remove `ShutterView` in `ExoPlayerView`. Some workarounds from the linked ticket is working for us. For ex. one of them, which is specific for linked bug (3160) still exist [in latest version](https://github.com/google/ExoPlayer/blob/51acd8150c25a2064c3e0c49e04540bd4e2db6f9/library/ui/src/main/java/com/google/android/exoplayer2/ui/PlayerView.java#L585). What we would like to know, it's possible reasons for that. 

### [REQUIRED] Link to test content

<a href="https://ibb.co/LYFj4pj"><img src="https://i.ibb.co/KbP4Cy4/adb-screencap-device-2019-08-07-160919.png" alt="adb-screencap-device-2019-08-07-160919" border="0"></a><br /><a target='_blank' href='https://ru.imgbb.com/'>Photo of the ADB ScreenCap</a><br />

<a href="https://ibb.co/d4W6xpm"><img src="https://i.ibb.co/GQxkNMH/same-screen-photo-2019-08-07-160919.jpg" alt="same-screen-photo-2019-08-07-160919" border="0"></a><br /><a target='_blank' href='https://ru.imgbb.com/'>The same photo from Camera</a><br />

### [REQUIRED] A full bug report captured from the device
TBD.

### [REQUIRED] Version of ExoPlayer being used
ExoPlayer versions 2.8.x and 2.10.x were used for tests. The results are same. 

### [REQUIRED] Device(s) and version(s) of Android being used
In our case, it's custom TV board, based on Android P, which pass all the CTS and GTS among with Google certification.

**Comment by ojw28** [comment]
This seems to be a (seemingly quite severe) problem with the underling platform, that's specific to the particular device you're testing on. You need to reach out to whoever is providing the custom TV board.
