### ISSUE TITLE
How to switch channel mapping on the fly

### ISSUE THREAD

**Issue by laszlo1337** [google/ExoPlayer#6415]
###Searched documentation and issues:
Docs, Stackoverflow, this repo GitHub issues

###Question
How to switch channel mapping on the fly? 
I need to implement audio channel mapping using ExoPlayer so that I can listen to one channel from both earphones at the time.

For that I am using [ChannelMappingAudioProcessor](https://github.com/google/ExoPlayer/blob/e87e231/library/core/src/main/java/com/google/android/exoplayer2/audio/ChannelMappingAudioProcessor.java) and it works (kind of, more about that at the end), except I need to be able to change the mapping on the fly.

The thing is, you can define the processors when creating an instance of the ExoPlayer (I do it with Dagger and I inject it into the ViewModel) but once instance is created, there is no way (afaik) to get the processor/renderer from the instance and modify it.

player creation:
```
    @Provides
    @Singleton
    fun provideMediaPlayer(application: Application): SimpleExoPlayer {
        return ExoPlayerFactory.newSimpleInstance(
            application,
            object : DefaultRenderersFactory(application) {
                override fun buildAudioProcessors(): Array<AudioProcessor> {
                    return arrayOf(ChannelMappingAudioProcessor().apply {
                        setChannelMap(intArrayOf(0, 1))
                        configure(DEVICE_AUDIO_SAMPLE_RATE, 2, C.ENCODING_PCM_16BIT)
                    })
                }
            },
            DefaultTrackSelector(),
            DefaultLoadControl.Builder()
                .setBufferDurationsMs(10, 10, 4, 10)
                .createDefaultLoadControl()
        )
    }
```

player usage:
```
//stream audio from remote raspberry PI device
player.playStream(url)

//playStream()
fun SimpleExoPlayer.playStream(address: String) {
    val mediaUri = Uri.parse(address)
    val mediaSource = ProgressiveMediaSource.Factory(
        DefaultHttpDataSourceFactory(
            "${BuildConfig.APP_NAME}/${BuildConfig.VERSION_NAME} (Linux;Android ${Build.VERSION.RELEASE}) ${ExoPlayerLibraryInfo.VERSION_SLASHY}"
        )
    ).createMediaSource(mediaUri)
    this.prepare(mediaSource)
    this.playWhenReady = true
}
```

I want to be able to access the ChannelMappingAudioProcessor and reconfigure it on the fly, so that I can change the channel mapping at runtime. From what [this guy](https://github.com/google/ExoPlayer/issues/2659#issuecomment-384319998) said here, it should be possible somehow. 

Another issue I have is with the ChannelMappingAudioProcessor itself. 
If I use the mapping [0,1] the audio plays with no problem until the end
but when I use [0,0] the audio only plays for 5 seconds.
My impl of ChannelMappingAudioProcessor converted to Kotlin (maybe I did a mistake there)
```
class ChannelMappingAudioProcessor : BaseAudioProcessor() {

    private var pendingOutputChannels: IntArray? = null

    private var active: Boolean = false
    private var outputChannels: IntArray? = null

    fun setChannelMap(outputChannels: IntArray) {
        pendingOutputChannels = outputChannels
    }

    @Throws(UnhandledFormatException::class)
    override fun configure(sampleRateHz: Int, channelCount: Int, @C.PcmEncoding encoding: Int): Boolean {
        val outputChannelsChanged = !Arrays.equals(pendingOutputChannels, outputChannels)
        outputChannels = pendingOutputChannels

        val outputChannels = this.outputChannels
        if (outputChannels == null) {
            active = false
            return outputChannelsChanged
        }
        if (encoding != C.ENCODING_PCM_16BIT) {
            throw UnhandledFormatException(sampleRateHz, channelCount, encoding)
        }
        if (!outputChannelsChanged && !setInputFormat(sampleRateHz, channelCount, encoding)) {
            return false
        }

        active = channelCount != outputChannels.size
        for (i in outputChannels.indices) {
            val channelIndex = outputChannels[i]
            if (channelIndex >= channelCount) {
                throw UnhandledFormatException(sampleRateHz, channelCount, encoding)
            }
            active = active or (channelIndex != i)
        }
        return true
    }

    override fun isActive(): Boolean {
        return active
    }

    override fun getOutputChannelCount(): Int {
        return if (outputChannels == null) channelCount else outputChannels!!.size
    }

    override fun queueInput(inputBuffer: ByteBuffer) {
        val outputChannels = Assertions.checkNotNull(this.outputChannels)
        var position = inputBuffer.position()
        val limit = inputBuffer.limit()
        val frameCount = (limit - position) / (2 * channelCount)
        val outputSize = frameCount * outputChannels.size * 2
        val buffer = replaceOutputBuffer(outputSize)
        while (position < limit) {
            for (channelIndex in outputChannels) {
                buffer.putShort(inputBuffer.getShort(position + 2 * channelIndex))
            }
            position += channelCount * 2
        }
        inputBuffer.position(limit)
        buffer.flip()
    }

    override fun onReset() {
        outputChannels = null
        pendingOutputChannels = null
        active = false
    }

}
```

**Comment by andrewlewis** [comment]
If the output format from the mapping is staying the same (including the same number of channels) you can just keep a reference to your audio processor when you create it, and interact with it from your app. You will need to make sure you synchronize access to its dynamic configuration because ExoPlayer will use the processor on its internal playback thread. Note: the audio track buffer is downstream from the audio processor so modifications won't be reflected in output audio instantly.

For the issue where audio stops after five seconds, it would be useful to have minimal steps to reproduce this in a modified ExoPlayer demo app. That should be tracked in a separate bug.
