### ISSUE TITLE
Disable Seekbar for LIVE content in MediaStyle notifications for Android 10 devices 

### ISSUE THREAD

**Issue by curlyfrie** [google/ExoPlayer#6416]
With Android 10 the media style notification (notification created with Echoplayers PlayerNotificationManager and added to foreground service) adds a seek bar which is great for seekable content.
Our HLS live stream has a 2 minute live window and is therefore kind of seekable but this is our buffer zone and we don't want to show this option to the user (since the downsides and confusion outweigh the benefits)

I can disable the seek actions by setting the _setEnabledPlaybackActions_ of MediaSessionConnector. But this way I only achieve a non-seekable progress bar, because the player duration is not UNSET or -1 here:

_public MediaMetadataCompat getMetadata(Player player)_

`MediaMetadataCompat.METADATA_KEY_DURATION,
          player.getDuration() == C.TIME_UNSET ? -1 : player.getDuration());`

Is there a way to achieve this, no seek bar for live content, in any way at the moment (besides overriding it or something similiar)?

It would be nice to enable, disable this via MediaSessionConnector (or PlayerNotificationManager, but since it is a MediaStyle Feature probably the former) I guess.

Thanks in advance.

**Comment by marcbaechinger** [comment]
The seek bar for live streams should clearly be avoided in the notification. Ideally this happens automatically in some way or there should be at least an option for apps to turn it off on demand.

We look into this. Thanks for reporting!

**Comment by curlyfrie** [comment]
another kind of related problem to this is that the `DefaultMediaMetadataProvider` => `getMetadata` overrides the metadata if no `activeQueueItem` is set.

eventhough if I manually set an item (also if I don't necessarily need one because no queue, only one item) it is reset in `invalidateMediaSessionPlaybackState` because I don't provide a `queueNavigator` :

```
long activeQueueItemId =
        queueNavigator != null
            ? queueNavigator.getActiveQueueItemId(player)
            : MediaSessionCompat.QueueItem.UNKNOWN_ID;
    extras.putFloat(EXTRAS_PITCH, player.getPlaybackParameters().pitch);
    builder
        .setActions(buildPrepareActions() | buildPlaybackActions(player))
        .setActiveQueueItemId(activeQueueItemId)
````

Maybe also use `long activeQueueItemId = mediaController.getPlaybackState().getActiveQueueItemId();`?

Otherwise I guess the only way is to use a `CustomMediaMetadataProvider` or not at all `setMediaMetadataProvider(null)`, since the necessary data has to be set anyways (and since there's no queue..).

Or implement the queueNavigator although I don't need it.


Also, for LIVE content, updating the metadata, playbackState everytime onTimeLineChanged might overdo it (every couple seconds, since it dynamic).

----------
Please correct me if I'm wrong and/or missed something.

Thanks.

**Comment by marcbaechinger** [comment]
We will provide a fix which avoid the seekbar for live streams soon.

Regarding the `activeQueueItemId` I think the idea is to provide a `QueueNavigator`. If you are using the `TimelineQueueNavigator` that should be straightforward. This makes sense even with a single item as it solves the points you are raising above. Is there a reason for you not using a QueueNavigator?

```
new TimelineQueueNavigator(mediaSession) {
    @Override
    public MediaDescriptionCompat getMediaDescription(Player player, int windowIndex) {
        return new MediaDescriptionCompat.Builder()
           .setDescription(getCurrentMediaItemDescription())
           .setTitle(getCurrentMediaItemTitle())
           .setSubtitle(getCurrentMediaItemSubtitle())
           .build();
  }
}
```

I will look into the problem with live streams updating the notification often to see if we have can provide a solution for this.

**Comment by curlyfrie** [comment]
> We will provide a fix which avoid the seekbar for live streams soon.

Cool thx. For now it works for me to use a custom meta data provider (or null) and set the duration to -1

> Regarding the `activeQueueItemId` I think the idea is to provide a `QueueNavigator`. If you are using the `TimelineQueueNavigator` that should be straightforward. This makes sense even with a single item as it solves the points you are raising above. Is there a reason for you not using a QueueNavigator? 
 
Ok I understand. I could work with that.. although I think resetting, overriding the metadata if no `mediaMetadataProvider` or in the default metadata provider if no active item is available might no be the most intuitive implementation (instead of leaving the in my case already set metadata if one would just like to use the media session and player state connection functionality). On the other hand it is really no big deal to implement this provider of course (just had to figure out these dependencies across the sessions).

> I will look into the problem with live streams updating the notification often to see if we have can provide a solution for this.

Maybe it is also no big deal or also necessary. It is only every couple of seconds. But for me I guess the invalidation of metadata and playback state ever timeline change would not be necessary and I could manually trigger an update of the meta data (if the next program is played)

Thx in advance.
