### ISSUE TITLE
OEM testing Command line step refers to the wrong test runner

### ISSUE THREAD

**Issue by dwhea** [google/ExoPlayer#6418]
### [REQUIRED] Issue description
https://exoplayer.dev/oems.html Command line step refers to the wrong test runner:

adb shell am instrument -w -r -e debug false \
  -e package com.google.android.exoplayer2.playbacktests.gts \
  com.google.android.exoplayer2.playbacktests.test/android.test.InstrumentationTestRunner

It should refer to androidx.test.runner.AndroidJUnitRunner to align with latest release-v2 tag (r2.10.4)

### [REQUIRED] Reproduction steps
Follow current https://exoplayer.dev/oems.html steps:

$ ./gradlew :playbacktests:installDebug
$ adb shell am instrument -w -r -e debug false \
  -e package com.google.android.exoplayer2.playbacktests.gts \
  com.google.android.exoplayer2.playbacktests.test/android.test.InstrumentationTestRunner

### [REQUIRED] Link to test content
N/A

### [REQUIRED] A full bug report captured from the device
N/A

### [REQUIRED] Version of ExoPlayer being used
r2.10.4

### [REQUIRED] Device(s) and version(s) of Android being used
N/A

**Comment by tonihei** [comment]
Thanks for reporting. We'll fix that.
