### ISSUE TITLE
Version 16 build issues

### ISSUE THREAD

**Issue by VishwanathPatil** [google/ExoPlayer#642]
I am having 1.2.4 versions , i have applied few patches taking from master ( Ignoring commits after major surgery ) . But when i compile it in Eclipse it gives me error because of non-existing API's and final field's mainly in mediaCodec. should be using Android Studio only for compile ?

**Comment by ojw28** [comment]
You need to use the latest SDK.

**Comment by VishwanathPatil** [comment]
Can you elaborate , i pick up proper jar for 4.4.1 and eclipse shows me errors like android.media.MediaFormat.KEY_BIT_RATE doesn't exist.

**Comment by VishwanathPatil** [comment]
thanks , i went through this #636 i could get some idea.
