### ISSUE TITLE
Wear OS Smartwatch with usable hardware decoder & ExoPlayer video?

### ISSUE THREAD

**Issue by whyvas** [google/ExoPlayer#6420]
### [REQUIRED] Searched documentation and issues

A bunch of google & github searches. I bought a 5th Gen Fossil Wear OS watch and tried to get ExoPlayer playing an h264 video but it simply wouldn't work. I got the progress bar & controls but black screen otherwise. I believe this watch doesn't support hardware decoding so I tried to force software decoding but that didn't work either. I also tried a couple of different surfaces with the same result.
I installed a few other video playing apps from the app store and one actually got video on the screen but it was horrifically out of sync and running at maybe 2fps which seems to support my theory of no hardware decoding on this particular hardware.
Samsung's offerings seem to run on Tizen OS which Android Studio doesn't support so that's out.

### [REQUIRED] Question
Does anyone know of a specific smartwatch that has Wear OS, has hardware decoding for h264 and can play videos with relative ease using ExoPlayer?

### A full bug report captured from the device
No bug report, from what I could tell in logcat, the video was playing happily.

### Link to test content
I was using video files from: http://jell.yfish.us/ for testing.

**Comment by ojw28** [comment]
I don't think there's a requirement that Wear devices include any video decoders in the platform. The only way I've seen video playback implemented on Wear devices is by bundling software decoders within the app itself. For example I've seen a demo of video playback on a Wear device using ExoPlayer's VP9 extension. This isn't something we can really provide guidance on, however.

**Comment by whyvas** [comment]
Yeah, I saw your previous posts about VP9 on the subject. I figured even though hardware decoding isn't required that some models would have it.

**Comment by ojw28** [comment]
I could be wrong, but I think nearly all Wear devices use the same one or two chipsets. Since it's the chipset that normally determines whether there are hardware decoders, I wouldn't expect much variation across the different devices.
