### ISSUE TITLE
How to connect AudioPlayerService in audio-app example to activity with UI controls 

### ISSUE THREAD

**Issue by jjimenez0611** [google/ExoPlayer#6423]
The audio-app example is a good example to start a project. But I have some doubts, for example I want to have in my activity controls like play/pause/stop and have a progress bar, how can I connect the exoplayer service with this controls in my activity? And how can I listen the track time to update the progress bar in my activity?

**Comment by ojw28** [comment]
Note: This question refers to the IO18 demo app [here](https://github.com/google/ExoPlayer/tree/io18/audio-app).

**Comment by marcbaechinger** [comment]
> how can I connect the exoplayer service with this controls in my activity?

You can have a static field in your service and expose the player instance. That's probably not a nice design but it's simple and works. It has also the advantage that you can use the ExoPlayer UI components in your activity.

As an alternative and a proper design approach for remotely accessing playback from various clients and potentially accross process boundaries, the service in the mentioned demo app does make use of the `MediaSessionConnector` of the medias session extension. So it would make sense to pass the `MediaSessionCompat.Token` to your activity and then use the controller to send commands to the service:

```
MediaControllerCompat controller = new MediaControllerCompat(context, token);
controller.getTransportControls().play();
```

> And how can I listen the track time to update the progress bar in my activity?

You can get the playbackState from the MediaSessionController to get current position and duration:

```
long position = controller.getPlaybackState().getPosition()
long duration = controller.getMetadata().getLong(MediaMetadataCompat.METADATA_KEY_DURATION);
```

With position and duration you can do a seekbar and start a thread which updates the UI every second.

**Comment by jjimenez0611** [comment]
@marcbaechinger thanks for the explanation...
Yes, I have a Binder in the service and singleton of the player, in this way I access to the player. :) 
I think use a Observer maybe with RXjava to get some events..
I try to use the MedaiControllerCompat but that was unsuccessful. Thanks a lot
