### ISSUE TITLE
The video has not AUD in H.264  cannot play by exoplayer

### ISSUE THREAD

**Issue by arlimm318** [google/ExoPlayer#6426]
we have a video,has not AUD,  cannot play by exoplayer.
  I want to know how does this video figure out the end of the picture in h.264 . But I tried using other players, such as VLC and Android mediaplayer, to play video without AUD in h.264.They all play success. 
  Why don't  exoplayer  support video like this.

**Comment by AquilesCanta** [comment]
See [the FAQ section](https://exoplayer.dev/troubleshooting.html#why-do-some-mpeg-ts-files-fail-to-play). If this doesn't solve your issue, please fill all the information required by the [issue template](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/content_not_playing.md).

**Comment by arlimm318** [comment]
Thanks. I added a  flagDefaultTsPayloadReaderFactory.FLAG_DETECT_ACCESS_UNITS to the class TsExtractor,The  Problem solved.

my code:
    private static TsExtractor createTsExtractor(
      Format format, List<Format> muxedCaptionFormats, TimestampAdjuster timestampAdjuster) {
.....................
.....................
.....................
    return new TsExtractor(
        TsExtractor.MODE_HLS,
        timestampAdjuster,
        new DefaultTsPayloadReaderFactory(esReaderFactoryFlags | DefaultTsPayloadReaderFactory.FLAG_DETECT_ACCESS_UNITS, muxedCaptionFormats));
