### ISSUE TITLE
HLS + FMP4 + WV + 3 encryption keys fails to playback with decryption error.

### ISSUE THREAD

**Issue by TheJohnBowers** [google/ExoPlayer#6427]
### [REQUIRED] Issue description
HLS + Widevine + FMP4 playback fails with "com.google.android.exoplayer2.ExoPlaybackException: android.media.MediaCodec$CryptoException: Error decrypting data: requested key has not been loaded" error when attempting to playback content secured with 3 different keys. (Audio + SD + HD)
The same configuration works find when using one key for Audio + SD, and another key for HD, or when using only a single key for AUDIO SD and HD.

### [REQUIRED] Reproduction steps
Reproduced in ExoPlayer demo app.  I will give examples of Single, 2 key and 3 key configs.
See the next section
### [REQUIRED] Link to test content
      {
        "name": "Succeeds -- VZ Media HLS + FMP4 + WV - Single Key",
        "uri": "https://content.uplynk.com/160fbcf73ac744e49327fe04e81cb6bb.m3u8?rmt=wv&vcodec=avc&m4fenctype=cenc",
        "drm_scheme": "widevine",
        "drm_license_url": "https://content.uplynk.com/wv",
        "drm_multi_session": true
      },
      {
        "name": "Succeeds -- VZ Media HLS + FMP4 + WV - Dual Key",
        "uri": "https://content.uplynk.com/f6301a01d7dd4c8592abb833fe68116e.m3u8?rmt=wv&vcodec=avc&m4fenctype=cenc",
        "drm_scheme": "widevine",
        "drm_license_url": "https://content.uplynk.com/wv",
        "drm_multi_session": true
      },
      {
        "name": "Fails -- VZ Media HLS + FMP4 + WV - 3 Key",
        "uri": "https://content.uplynk.com/1ed196b315094f03b0502778367c8db8.m3u8?rmt=wv&vcodec=avc&m4fenctype=cenc",
        "drm_scheme": "widevine",
        "drm_license_url": "https://content.uplynk.com/wv",
        "drm_multi_session": true
      },
### [REQUIRED] A full bug report captured from the device
[bugreport-2019-09-13-10-20-36.zip](https://github.com/google/ExoPlayer/files/3610863/bugreport-2019-09-13-10-20-36.zip)

### [REQUIRED] Version of ExoPlayer being used
2.10.0

### [REQUIRED] Device(s) and version(s) of Android being used
Bug report is from samsung galaxy S8, but i have tried on several other android devices, and have seen no difference in behavior.

**Comment by AquilesCanta** [comment]
Thanks for the high quality issue report!

It seems to me the media is malformed. Both video and audio are tagged as using `KEYID=0x777cdd24a4da40dc90bffa0acac92576`, and the key updates happen for said key. However, audio samples (video samples are ok, content works if you disable audio) are associated to key id 0x431b60d8720f438b9a7020779ec137d1, which explains why the key of this last key id is not available.

Please reach back if I got something wrong, or if you have evidence pointing at exoplayer doing something wrong.
