### ISSUE TITLE
Play a specific portion of a video but display the whole video?

### ISSUE THREAD

**Issue by PranjalDesai** [google/ExoPlayer#6428]
## Searched documentation and issues
I have looked at ClippingMediaSource.

## Question
I want to play a video from url. The whole video shows on the seek bar and player but it starts playing from a specific point and pauses at a specific point. The user can press play and continue watching the rest of the video. How can I achieve that?

**Comment by tonihei** [comment]
> it starts playing from a specific point 

You can call `player.seekTo` before `player.prepare` to ensure the video starts from the desired position.

> and pauses at a specific point.

You can send a message that gets triggered at this point and pauses the player:
```
player.createMessage((type, payload) -> player.setPlayWhenReady(false))
  .setHandler(new Handler()).setPositionMs(pausePosition).send();
```
> The user can press play and continue watching the rest of the video.

That just works with the method above because the video is paused in the normal way.

**Comment by PranjalDesai** [comment]
That works for a single video but if you have multiple videos being passed as ConcatenatingMediaSource than how do you handle starting point for each video?

**Comment by tonihei** [comment]
That's unfortunately not yet supported but tracked by #6373. 

If you need such a feature urgently, you can make it (mostly) work by writing a `MediaSource` wrapper that returns a `Timeline` wrapper that sets your start position as `windowDefaultStartPositionUs`.

**Comment by PranjalDesai** [comment]
Awesome thanks!
