### ISSUE TITLE
MP4 file with empty avcC box fails to play

### ISSUE THREAD

**Issue by Yourbadman** [google/ExoPlayer#6434]
```
ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.upstream.DataSourceException
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:238)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:844)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:320)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:760)
```

**Comment by Yourbadman** [comment]
[mp4dump.txt](https://github.com/google/ExoPlayer/files/3621424/mp4dump.txt)

**Comment by AquilesCanta** [comment]
Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/content_not_playing.md).

**Comment by Yourbadman** [comment]
### [REQUIRED] Content description
can't play mp4 video.

![image](https://user-images.githubusercontent.com/10590406/65101842-e98f1d80-d9fb-11e9-8dc8-87c93e94a4bf.png)

### [REQUIRED] Link to test content
 Will send mp4 video attached to dev.exoplayer@gmail.com 

### [REQUIRED] Version of ExoPlayer being used
com.google.android.exoplayer:exoplayer-core:2.8.2

### [REQUIRED] Device(s) and version(s) of Android being used
Android 7.1
Android 9

### [REQUIRED] A full bug report captured from the device
Will send bugreport attached to dev.exoplayer@gmail.com

**Comment by ojw28** [comment]
Marking as bad media (because it is), and also as a bug (for if the intention is to work around it).

**Comment by AquilesCanta** [comment]
I think that the spec ISO/IEC 14496-15 forbids the avcC box to be empty. Note that other players may  support the file but we cannot aim to support all malformed media out there, unfortunately.

If you have evidence suggesting an empty avcc box is ok, please post it here and we will review this issue.
