### ISSUE TITLE
Exoplayer Multithreading issue

### ISSUE THREAD

**Issue by kmrinmoy07** [google/ExoPlayer#6437]
I have already looked in GIthub, Stackoverflow and many more.

I am developing an android application of streaming music with the help of exoplayer2 where the app gets data from server.

The application sometimes gets this crash `java.lang.IndexOutOfBoundsException` when I start the player. 
You can get my error log [here](https://drive.google.com/open?id=1lX7kXdRITzTHR55xz6wqipqnw4N43NM5)

My problem is same as [this](https://github.com/google/ExoPlayer/issues/4641) and learned that this is the problem of multi threading. 

[Here](https://drive.google.com/open?id=1n3D902CAb1zFpYbwJTiO6lrEGSGlbMyv) you can find some files of my project. Could you please help me how to remove this problem of multi threading as I am not very experienced in android development.

**Comment by AquilesCanta** [comment]
I am sorry, but we cannot spend resources debugging third party apps. If you have any evidence pointing at this being an ExoPlayer issue, please provide reproduction steps, plus all items requested in the issue template, and we will look into this.
