### ISSUE TITLE
A SQLiteConnection object for database was leaked!  Please fix ...

### ISSUE THREAD

**Issue by dariush-fathie** [google/ExoPlayer#6438]
I used `DatabaseProvider` for creating an instance of `SimpleCache` like below : 

`cache = SimpleCache(File(context.cacheDir, "media"), evictor, exoPlayerDatabaseProvider)`

And the `ExoPlayerDatabaseProvider` is : 

```
class ExoPlayerDatabaseProvider @Inject constructor(context: Context) : DatabaseProvider {
    private val databaseAbsPath = context.applicationInfo.dataDir + "/databases/"
    private val dbName = "EPDB"

    override fun getWritableDatabase(): SQLiteDatabase {
        return SQLiteDatabase.openOrCreateDatabase(databaseAbsPath + dbName, null, null)
    }
    override fun getReadableDatabase(): SQLiteDatabase {
        return SQLiteDatabase.openOrCreateDatabase(
            databaseAbsPath + dbName,
            null, null
        )
    }
}
```

But I think it's on ExoPlayer to open or close connections . anyway , anyone can help me where|when i most close connections ?

**Comment by ojw28** [comment]
Your implementation shouldn't be creating a new `SQLiteDatabase` whenever `getReadableDatabase` and `getWritableDatabase` are called. As described by [the documentation](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/database/DatabaseProvider.html), there are very specific expected behaviors around caching that your implementation needs to adhere to. The required behavior is the same as [`SQLiteOpenHelper`](https://developer.android.com/reference/android/database/sqlite/SQLiteOpenHelper.html#getReadableDatabase()).

Note that the library already contains two implementations of `DatabaseProvider`. We expect they should cover pretty much all valid use cases. Why does `DefaultDatabaseProvider` not work for your case?
