### ISSUE TITLE
ExoPlaybackException: Media requires a DrmSessionManager

### ISSUE THREAD

**Issue by randeeppr** [google/ExoPlayer#644]
Hi,
We are trying to play a Widevine Modular DRM encrypted MPEG DASH video in exoplayer.

We have updated WidevineTestMediaDrmCallback.java and Samples.java as follows. 

private static final String WIDEVINE_GTS_DEFAULT_BASE_URI = "http://xxx.xxx.xx.xx/proxy";
new Sample("Widevine Test", "5C756b75765f6461726h6b6e69676875", "http://domain.com/media.mpd", DemoUtil.TYPE_DASH)

But when we try to play the video, we are getting the following error.

I/PlayerActivity( 2518): User Agent: ExoPlayerDemo/1.2.3 (Linux;Android 4.4.2) ExoPlayerLib/1.2.3
I/PlayerActivity( 2518):  TYPE is DASH
I/ExoPlayerImpl( 2518): Init 1.2.3
D/EventLogger( 2518): start [0]
D/EventLogger( 2518): state [0.00, false, P]
I/DemoPlayer( 2518): prepare()
I/DashRendererBuilder( 2518): buildRenderers()
I/ExoPlayerImplInternal( 2518): handleMessage: MSG_SEEK_TO
D/EventLogger( 2518): state [0.00, true, P]
I/ExoPlayerImplInternal( 2518): handleMessage: MSG_SET_PLAY_WHEN_READY
I/3g_intf ( 1380): HI_3G_ScanCard(): scan card failed, ret = -4!
D/dalvikvm( 2518): GC_CONCURRENT freed 149K, 6% free 3830K/4052K, paused 2ms+7ms, total 32ms
I/ActivityManager( 1803): Displayed com.google.android.exoplayer.demo/.PlayerActivity: +769ms
W/SurfaceFlinger( 1382): couldn't log to binary event log: overflow.
I/AudioPolicyManagerBase( 1385): ----FORCE_none: AudioPolicyManagerBase.cpp
I/AudioPolicyManagerBase( 1385): ----FORCE_none: AudioPolicyManagerBase.cpp
I/AudioPolicyManagerBase( 1385): ----FORCE_none: AudioPolicyManagerBase.cpp
I/AudioPolicyManagerBase( 1385): ----FORCE_none: AudioPolicyManagerBase.cpp
I/AudioPolicyManagerBase( 1385): ----FORCE_none: AudioPolicyManagerBase.cpp
I/3g_intf ( 1380): HI_3G_ScanCard(): scan card failed, ret = -4!
I/MediaPresentationDescriptionParser( 2518): parse: input stream contains a MPD file
I/ManifestFetcher( 2518): onLoadCompleted()
I/DashRendererBuilder( 2518): onManifest()
I/OMXClient( 2518): Using client-side OMX mux.
D/HIOMX_CORE( 1385): OMX_GetHandle :: enter!
D/HIOMX_CORE( 1385): OMX_GetHandle :: component name:OMX.hisi.video.decoder !
D/HIOMX_CORE( 1385): OMX_GetHandle :: prepare to load  libOMX.hisi.video.decoder.so
D/HIOMX_CORE( 1385): OMX_GetHandle :: load  libOMX.hisi.video.decoder.so ok
D/HISI_OMXVDEC( 1385): Init OMX component OMX.hisi.video.decoder
E/HISI_OMXVDEC( 1385): get_supported_profile_level: ProfileIndex(48) exceed!
E/HISI_OMXVDEC( 1385): get_extension_index: OMX.google.android.index.storeMetaDataInBuffers not implemented!
E/OMXNodeInstance( 1385): OMX_GetExtensionIndex OMX.google.android.index.storeMetaDataInBuffers failed
E/HISI_OMXVDEC( 1385): get_extension_index: OMX.google.android.index.prepareForAdaptivePlayback not implemented!
W/OMXNodeInstance( 1385): OMX_GetExtensionIndex OMX.google.android.index.prepareForAdaptivePlayback failed
V/OMXNodeInstance( 1385): calling destroyComponentInstance
V/OMXNodeInstance( 1385): destroyComponentInstance returned err 0
V/OMXNodeInstance( 1385): OMXNodeInstance going away.
I/MediaCodecTrackRenderer( 2518): MediaCodecTrackRenderer: drmSessionManager is NULL
I/MediaCodecTrackRenderer( 2518): MediaCodecTrackRenderer: drmSessionManager is NULL
I/ExoPlayerImplInternal( 2518): handleMessage: MSG_CUSTOM
I/ExoPlayerImplInternal( 2518): handleMessage: MSG_SET_PLAY_WHEN_READY
D/EventLogger( 2518): state [1.96, false, I]
I/ExoPlayerImplInternal( 2518): handleMessage: MSG_SET_RENDERER_ENABLED
I/ExoPlayerImplInternal( 2518): handleMessage: MSG_CUSTOM
I/ExoPlayerImplInternal( 2518): handleMessage: MSG_SET_RENDERER_ENABLED
I/ExoPlayerImplInternal( 2518): handleMessage: MSG_SET_PLAY_WHEN_READY
D/EventLogger( 2518): state [1.97, true, I]
I/ExoPlayerImplInternal( 2518): handleMessage: MSG_SET_RENDERER_ENABLED
I/ExoPlayerImplInternal( 2518): handleMessage: MSG_PREPARE
I/ExoPlayerImplInternal( 2518): handleMessage: MSG_INCREMENTAL_PREPARE
I/ExoPlayerImplInternal( 2518): handleMessage: MSG_DO_SOME_WORK
I/ExoPlayerImplInternal( 2518): handleMessage: MSG_DO_SOME_WORK
D/EventLogger( 2518): bandwidth [2.66, 1749, 0.00, 13992000]
I/ExoPlayerImplInternal( 2518): handleMessage: MSG_DO_SOME_WORK
D/EventLogger( 2518): videoFormat [2.69, 1, 0]
E/ExoPlayerImplInternal( 2518): Internal track renderer error.
E/ExoPlayerImplInternal( 2518): com.google.android.exoplayer.ExoPlaybackException: Media requires a DrmSessionManager
E/ExoPlayerImplInternal( 2518): at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:292)
E/ExoPlayerImplInternal( 2518): at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:671)
E/ExoPlayerImplInternal( 2518): at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:369)
E/ExoPlayerImplInternal( 2518): at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:473)
E/ExoPlayerImplInternal( 2518): at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:453)
E/ExoPlayerImplInternal( 2518): at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:410)
E/ExoPlayerImplInternal( 2518): at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:207)
E/ExoPlayerImplInternal( 2518): at android.os.Handler.dispatchMessage(Handler.java:98)
E/ExoPlayerImplInternal( 2518): at android.os.Looper.loop(Looper.java:136)
E/ExoPlayerImplInternal( 2518): at android.os.HandlerThread.run(HandlerThread.java:61)
E/ExoPlayerImplInternal( 2518): at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
E/EventLogger( 2518): playerFailed [2.71]
E/EventLogger( 2518): com.google.android.exoplayer.ExoPlaybackException: Media requires a DrmSessionManager
E/EventLogger( 2518): at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:292)
E/EventLogger( 2518): at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:671)
E/EventLogger( 2518): at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:369)
E/EventLogger( 2518): at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:473)
E/EventLogger( 2518): at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:453)
E/EventLogger( 2518): at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:410)
E/EventLogger( 2518): at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:207)
E/EventLogger( 2518): at android.os.Handler.dispatchMessage(Handler.java:98)
E/EventLogger( 2518): at android.os.Looper.loop(Looper.java:136)
E/EventLogger( 2518): at android.os.HandlerThread.run(HandlerThread.java:61)
E/EventLogger( 2518): at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)

Regards,
Randeep

**Comment by ojw28** [comment]
DashRendererBuilder doesn't think the content is protected, and so doesn't instantiate a StreamingDrmSessionManager, which is required for playback of protected content. This is probably because your MPD doesn't define any content protection elements.

To fix this, you can either fix the MPD to contain content protection elements, or alternatively you could try with your existing MPD if you hardcode hasContentProtection to true in that class.

**Comment by randeeppr** [comment]
In  our mpd file content protection details are there,

    Representation id="1" bandwidth="949240" codecs="avc1.4d401f" mimeType="video/mp4" width="1280" height="720">
    <ContentProtection schemeIdUri="urn:mpeg:dash:mp4protection:2011" value="cenc"/>
    <ContentProtection schemeIdUri="urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed"/>
    <BaseURL>testfilm_enc_1000_video.mp4</BaseURL>

**Comment by ojw28** [comment]
- You'll need to spend some time debugging why hasContentProtection is false in DashRendererBuilder (assuming that it is false).
- Note that it's recommended that ContentProtection elements be children of the AdaptationSet element, not of the individual Representation elements. We should handle both cases though.

**Comment by randeeppr** [comment]
I'll check with my developers. 
Widevine's default packager, inserts the ContentProtection elements in Representation block only. May be they have done for enabling different DRMs for different streams. 

My doubts was whether the syntax we used in WidevineTestMediaDrmCallback.java and Samples.java are right or not.

    private static final String WIDEVINE_GTS_DEFAULT_BASE_URI = "http://xxx.xxx.xx.xx/proxy";
    new Sample("Widevine Test", "5C756b75765f6461726h6b6e69676875", "http://domain.com/media.mpd", DemoUtil.TYPE_DASH)

Do we need to pass the ContentID in all the request? Any idea?

**Comment by randeeppr** [comment]
Hi,
We were able to fix this issue by changing the hasContentProtection variable to true.
Thank you.

Regards,
Randeep

**Comment by ojw28** [comment]
The fact it wasn't set to true automatically suggests something about your manifest is wrong (or the ExoPlayer parser has an issue). You might want to look into that.

**Comment by randeeppr** [comment]
Is there anyway to give you the mpd file privately??

**Comment by ojw28** [comment]
You should be able to debug the code yourself to work out why it's not being set to true. Just attach a debugger and start tracing the code back to the mpd parser, and you should find out what's going on.
