### ISSUE TITLE
Using Tag EXT-X-DISCONTINUITY to insert a mid ad, not playing correctly.

### ISSUE THREAD

**Issue by Romantic-LiXuefeng** [google/ExoPlayer#6444]
### [REQUIRED] Issue description &&  Reproduction steps
Step1. Using the `Shaka-Packager` convert mp4 to HLS stream with ad cues at 60s. 
 ```
$ packager 'in=/media/google_io_2017.mp4,stream=video,segment_template=/media/mp4_to_hls/h264_1080p/h264/$Number$.ts,playlist_name=/h264_1080p/h264.m3u8' \
	   'in=/media/google_io_2017.mp4,stream=audio,segment_template=/media/mp4_to_hls/h264_1080p/aac/$Number$.aac,playlist_name=/h264_1080p/aac.m3u8' \
	    --ad_cues 60 \
            --segment_duration 10 \
	    --hls_master_playlist_output /media/mp4_to_hls/h264_master.m3u8
```
 Step2: Because of the `Shaka-Packager` not supporting to mux audio and video into the same ts container. So I demux the ts format mid ad into separate auido ts and video ts. 

Step3: Replace #EXT-X-PLACEMENT-OPPORTUNITY with EXT-X-DISCONTINUITY and Ad segment as described in [https://github.com/google/shaka-packager/issues/650](url).

Can't play the mid ad.  But if I disable the audio, only play the video, the playback is well.

The content I has sent to you to [dev.exoplayer@gmail.com](url).

**Comment by Romantic-LiXuefeng** [comment]
#https://github.com/google/shaka-packager/issues/650

**Comment by Romantic-LiXuefeng** [comment]
I have played the steam with Safari browser, the playback is well.

**Comment by AquilesCanta** [comment]
A fix will be pushed soon, and a reference will appear in this thread. Thanks for reporting!
