### ISSUE TITLE
Not playing video by exoPlayer

### ISSUE THREAD

**Issue by gelbertgel** [google/ExoPlayer#6445]
I have exoPlayer last version (2.10.4) and I applied to all exoPlayer documentation (https://exoplayer.dev/) but video is not playing.

    private void playVideo(Uri uri, boolean autoPlay){

           this.playerView = ViewUtil.findById(this, R.id.video_view);
           this.exoControls = new PlayerControlView(getContext()); 
    
           player = ExoPlayerFactory.newSimpleInstance(getContext());
           player.addListener(this);
           playerView.setPlayer(player);
           exoControls.setPlayer(player);
    
           DataSource.Factory dataSourceFactory = new DefaultDataSourceFactory(getContext(), Util.getUserAgent(getContext(), getContext().getString(R.string.app_name)));
           DefaultExtractorsFactory extractorsFactory = new DefaultExtractorsFactory();
           extractorsFactory.setMp4ExtractorFlags(Mp4Extractor.FLAG_WORKAROUND_IGNORE_EDIT_LISTS);
           MediaSource videoSource = new ProgressiveMediaSource.Factory(dataSourceFactory, extractorsFactory).createMediaSource(uri);
    
           player.prepare(videoSource);
           player.setPlayWhenReady(autoplay);
    }

My video player xml:

    <?xml version="1.0" encoding="utf-8"?>
    <FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:app="http://schemas.android.com/apk/res-auto"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical">
    
        <com.google.android.exoplayer2.ui.PlayerView
            android:id="@+id/video_view"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_gravity="center"
            android:gravity="center"
            app:player_layout_id="@layout/media_preview_exoplayer_layout"
            app:surface_type="texture_view" />
    
    </FrameLayout>

Error codes in logcat:

> E/ACodec: [OMX.google.aac.decoder] ERROR(0x80001001) E/ACodec:
> signalError(omxError 0x80001001, internalError -2147483648)
> E/MediaCodec: Codec reported err 0x80001001, actionCode 0, while in
> state 6 E/ExoPlayerImplInternal: Internal runtime error.
>     java.lang.IllegalStateException
>         at android.media.MediaCodec.native_queueInputBuffer(Native Method)
>         at android.media.MediaCodec.queueInputBuffer(MediaCodec.java:2359)
>         at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1115)
>         at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:654)
>         at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:575)
>         at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:326)
>         at android.os.Handler.dispatchMessage(Handler.java:102)
>         at android.os.Looper.loop(Looper.java:214)
>         at android.os.HandlerThread.run(HandlerThread.java:65)

Device Info : Samsung Note 8
Sdk : 9.0

**Comment by AquilesCanta** [comment]
Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/content_not_playing.md).
