### ISSUE TITLE
Parsing Vast Tags With ImaAds extension.

### ISSUE THREAD

**Issue by RezaMortazavi** [google/ExoPlayer#6447]
I am showing vast ads with Ima extension. i need to parse the vast xml to load some custom views on the player. how can i get the tags inside the VAST file?

**Comment by RezaMortazavi** [comment]
I am playing vast ads with Ima extension. i need to parse the vast xml to load some custom views on the player. how can i get the tags inside the VAST file?

**Comment by AquilesCanta** [comment]
@andrewlewis would you mind answering this?

**Comment by RezaMortazavi** [comment]
Anyone?

**Comment by andrewlewis** [comment]
I don't think the IMA SDK provides a way to get the contents of the ad tag XML. You'd probably need to load and parse the ad tag yourself.

For what it's worth, the IMA SDK does expose some ad metadata in the `Ad` instance passed to the `AdEventListener` for the LOADED event. You can supply one of these listeners when building the `ImaAdsLoader`. I'm not sure if this includes the information you need though.
