### ISSUE TITLE
Support for custom UrlRequest.Callback in CronetDataSource

### ISSUE THREAD

**Issue by Surendra7878** [google/ExoPlayer#6449]
### [REQUIRED] Use case description
I like to have my custom UrlRequest.Callback class so that I can monitor and log information of network request, failures, etc. But [CronetDataSource](https://github.com/google/ExoPlayer/blob/release-v2/extensions/cronet/src/main/java/com/google/android/exoplayer2/ext/cronet/CronetDataSource.java) is not providing me that option as it uses it's own implementation of UrlRequest.Callback class.

### Proposed solution
Provide a new constructor where it accepts UrlRequest.Callback object. 

### Alternatives considered
None.

**Comment by christosts** [comment]
Have you considered using an [`AnalyticsListener`](https://github.com/google/ExoPlayer/blob/35e030f56b4e3312e863e44a1e8fe27aef4310b7/library/core/src/main/java/com/google/android/exoplayer2/analytics/AnalyticsListener.java) which provides callbacks like 
- [`onLoadStarted`](https://github.com/google/ExoPlayer/blob/35e030f56b4e3312e863e44a1e8fe27aef4310b7/library/core/src/main/java/com/google/android/exoplayer2/analytics/AnalyticsListener.java#L223)
- [`onLoadCompleted`](https://github.com/google/ExoPlayer/blob/35e030f56b4e3312e863e44a1e8fe27aef4310b7/library/core/src/main/java/com/google/android/exoplayer2/analytics/AnalyticsListener.java#L233)
- [`onLoadCanceled`](https://github.com/google/ExoPlayer/blob/35e030f56b4e3312e863e44a1e8fe27aef4310b7/library/core/src/main/java/com/google/android/exoplayer2/analytics/AnalyticsListener.java#L243)
- [`onLoadError`](https://github.com/google/ExoPlayer/blob/35e030f56b4e3312e863e44a1e8fe27aef4310b7/library/core/src/main/java/com/google/android/exoplayer2/analytics/AnalyticsListener.java#L256)

Can you see if it fits your needs and if not, can you provide us with a use case on that is not covered already?

**Comment by Surendra7878** [comment]
I considered using [AnalyticsListener](https://github.com/google/ExoPlayer/blob/35e030f56b4e3312e863e44a1e8fe27aef4310b7/library/core/src/main/java/com/google/android/exoplayer2/analytics/AnalyticsListener.java) but it provides callbacks while loading the video in exoplayer, but I need to know the actual time it took to download a video, protocol type, network layer exceptions(if any) which I can get by extending UrlRequest.Callback.

**Comment by christosts** [comment]
Just to clarify on the use cases:
> time it took to download a video

The [LoadEventInfo](https://github.com/google/ExoPlayer/blob/44293e8f45fc62ff918001b4425c44d0ded5ffc9/library/core/src/main/java/com/google/android/exoplayer2/source/MediaSourceEventListener.java#L40) has two fields (elapsedRealtimeMs and loadDurationMs) that you can use to get download time. Is it not enough?

> protocol type

The LoadEventInfo also has the URI used, so you can parse it and get the schere

> network layer exceptions

You get errors in the [onLoadError](https://github.com/google/ExoPlayer/blob/35e030f56b4e3312e863e44a1e8fe27aef4310b7/library/core/src/main/java/com/google/android/exoplayer2/analytics/AnalyticsListener.java#L256) event. The passed parameters include the error, passed as IOException. By inspecting the source for the [CronetDataSource](https://github.com/google/ExoPlayer/blob/bef130ad17f11ab3997548653f2466e50bd6eb27/extensions/cronet/src/main/java/com/google/android/exoplayer2/ext/cronet/CronetDataSource.java) you can see exactly what is the type of exceptions thrown. For example, the [InvalidResponseCodeException](https://github.com/google/ExoPlayer/blob/bef130ad17f11ab3997548653f2466e50bd6eb27/library/core/src/main/java/com/google/android/exoplayer2/upstream/HttpDataSource.java#L291) contains the HTTP response from the server. In your load error handler you can cast the exception accordingly and get more details. Basically, this requires you to write an `if-else` block where you check the type of the `error` via `instance of`, maybe not the  best way, but isn't this sufficient for the uses you mentioned?
