### ISSUE TITLE
How to support CE-608 in Exoplayer

### ISSUE THREAD

**Issue by dhanapal20** [google/ExoPlayer#6451]
Hi
I want to support CE-608 and CE-708 subtitles from MPG2-TS 
Could you provide me sample code to enable subtitle along with A/V tracks.

Based on previous answered issues, I used below code of exo player start but unable to decode subtitles 
-----------------------------------------------------------------------------------------------
```java 
// 1. Create a default TrackSelector
BandwidthMeter bandwidthMeter = new DefaultBandwidthMeter();
TrackSelection.Factory videoTrackSelectionFactory = 
    new AdaptiveTrackSelection.Factory(bandwidthMeter);
TrackSelector trackSelector = new DefaultTrackSelector(videoTrackSelectionFactory);

// 2. Create a default LoadControl
LoadControl loadControl = new DefaultLoadControl();

((DefaultTrackSelector) trackSelector).setParameters(
    ((DefaultTrackSelector) trackSelector)
        .getParameters()
        .buildUpon()
        .setPreferredTextLanguage("en")
        .build());

// 3. Create the player
mExoPlayer = ExoPlayerFactory.newSimpleInstance(this, trackSelector, loadControl);
```

----------------------------------------------------------
If I get any documents or sample code on How to configure CE-608/708 subtitle and dynamic On/Off selection, it will be helpful for me. Since this is my first approach in exoplayer to enable CC in my project.

**Comment by icbaker** [comment]
I think we need more info about how you're wiring the player up to actually output to the UI.

* Are you using `PlayerView` from our [UI Components](https://exoplayer.dev/ui-components.html)?
* You say the app is "unable to decode subtitles" - does this mean the subtitles just aren't being rendered? Or you're actually able to observe that the decoding in particular is failing?
* Can you share the media you're using to test this?

**Comment by dhanapal20** [comment]
Hi Thanks for your response, please find the required details as below
- Yes, We are using PlayerView from UI Components
- Subtitles not at all rendered on any of text in the screen
- Since this media stream is in full encrypted MPEG-2 TS format, so we can't able to deliver (but decrypted playback is working fine for video and audio)

**Comment by icbaker** [comment]
I'm afraid there still isn't really enough info to fully answer. This isn't an exhaustive list of questions, anything you think might be relevant that you're willing to share could help.

* Is the SubtitleView visible in your app? (e.g. when you debug and use the Layout Inspector from Android Studio)
* Do subtitles appear for unencrypted content?
* Are there any errors that look suspicious in logcat?
* Can you set some breakpoints and see how far the decoding is getting?
  * Maybe in `Cea608Decoder#decode` or `Cea708Decoder#decode`. And/or `TextRenderer#render`
* Can you see the subtitle track being selected in the `EventLogger` in logcat?
   Add the `EventLogger` like this:
   ```
   mExoPlayer.addAnalyticsListener(new EventLogger(trackSelector));
   ```
   Then when you start playback it will print the tracks it's extracted from the stream, and indicate which are selected with `[X]` (unselected ones with `[ ]`).

**Comment by dhanapal20** [comment]
Hi Thanks for your valuable hints,
By using EventLogger, I can see that following Renderers and  selection details

```
Renderer:0 [
        Group:0, adaptive_supported=YES [
          [X] Track:0, id=0, mimeType=video/avc, bitrate=664000, supported=YES
          [X] Track:1, id=1, mimeType=video/avc, bitrate=664000, supported=YES
        ]
      ]
D/EventLogger:   Renderer:1 [
        Group:0, adaptive_supported=N/A [
          [X] Track:0, id=1/15, mimeType=audio/mp4a-latm, channels=2, sample_rate=48000, supported=YES
        ]
      ]
      Renderer:2 [
        Group:0, adaptive_supported=N/A [
          [ ] Track:0, id=1/8219, mimeType=application/cea-608, supported=YES
        ]
D/EventLogger:   ]
      Renderer:3 [
        Group:0, adaptive_supported=N/A [
          [X] Track:0, id=1/21, mimeType=application/id3, supported=YES
        ]
      ]
    ]
```

From above log, Renderer:3 (mimeType=application/id3) is selected and Renderer:2 (mimeType=application/cea-608) is not selected. Also it seems that no valid data present for "application/id3" in PES
By using below code to select undetermined language, I can able to select Renderer:2 and CC data is properly displayed in screen
```
trackSelector.setParameters(trackSelector)	
    .getParameters().buildUpon().setSelectUndeterminedTextLanguage(true).build()); 
```
As I know that in Closed Caption representation mimeType ID3 used for metatadata and CEA-608 used for text
If both are present in stream, 
  - Both are receiving same data?
  - By default which one is priority to select in player?
  - Options provided to user for selection of CEA-608 and ID3 ?
Could you help me to understand about above questions

**Comment by icbaker** [comment]
As you said, ID3 is 'metadata' rather than 'data' (or specifically 'text' in the case of cea-608).

That means the contents of the ID3 track will get output to MetadataOutput (which you can access by registering a callback with `SimpleExoPlayer#addMetadataOutput`).

> If both are present in stream,
> * Both are receiving same data?

I highly doubt they're carrying equivalent data, and ExoPlayer doesn't provide any direct way to display the contents of the ID3 track in the SubtitleView on the screen (because it's not expected to contain subtitle data). It's obviously impossible to say with certainty though without access to your media.

> * By default which one is priority to select in player?

They're different types of track, so the TrackSelector shouldn't be picking between them. It's not about priority. The reason the text track *wasn't* picked originally is because it doesn't seem to declare its language as `en`, so the TrackSelector was trying to fulfil your `preferredTextLanguage` and couldn't find one. It seems you've solved this by allowing undetermined language tracks to be selected.

> * Options provided to user for selection of CEA-608 and ID3 ?

As above, it's unlikely these are carrying equivalent data, so we don't provide any easy way to select between them.

I'm going to close this now, as it seems you've got text to show on the screen. Feel free to re-open or file a new issue though if there are still unanswered questions!
