### ISSUE TITLE
Internet Connection Failure autoplay

### ISSUE THREAD

**Issue by sachinharne** [google/ExoPlayer#6452]
Exo player is not reconnecting to network and plays videos automatically, even after reconnect when I press play button this also not working.
Exo player version 2.10.4

**Comment by andrewlewis** [comment]
Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md).
