### ISSUE TITLE
How to show multi subtitle and multi audio list

### ISSUE THREAD

**Issue by aazam-nouri** [google/ExoPlayer#6455]
How can I show multi subtitle and multi audio list and let the user switch between subtitles or audios?

**Comment by icbaker** [comment]
Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/question.md).

Specifically it would be useful to know whether you are using the ExoPlayer [UI components](https://exoplayer.dev/ui-components.html).

**Comment by tonihei** [comment]
Please also have a look at our demo app, which already provides a way to select audio and subtitles.

**Comment by aazam-nouri** [comment]
My problem was solved by sample code, Thanks to [tonihei ](https://github.com/tonihei)
