### ISSUE TITLE
Can we set a default start index for ShuffleOrder  

### ISSUE THREAD

**Issue by pawaom** [google/ExoPlayer#6456]
We can create a custom ShuffleOrder but how can we set a default start index  

I have 9 songs, a,b,c,d,e,f,g,h,i, I want to set a ShuffleOrder  of , c,a,b,d,g,f,h,i,e , 

The current player status is RepeatAll, and the current song being played is, e, that is , index of 4,

now when the user selects Shuffle, the player can shuffle using the  ShuffleOrder  , how can we set the next song to start playing from c. that is the index of 2 , that is the starting index of the ShuffleOrder

**Comment by tonihei** [comment]
You can create a new ShuffleOrder with a custom ordering using the constructor that takes an `int[]`. That allows you to configure the order in any way you like. To make the player use this shuffle order, you can then set it in `ConcatenatingMediaSource.setShuffleOrder`.
