### ISSUE TITLE
How to get the current bitrate and resolution of HLS Video?

### ISSUE THREAD

**Issue by sachinbhanot** [google/ExoPlayer#646]
Is it possible to get current bitrate and resolution of playing HLS Video ? when the bit rate is switched and fetch the current bitrate ?

**Comment by VishwanathPatil** [comment]
As I know yoy should listen to DefaultBandwidthMeter . It is shown in
Demoplayer.java onBandwidthSample would give you bitrate information.

**Comment by sachinbhanot** [comment]
but its never come on onBandwidthSample .. unable to fetch bitrate

**Comment by Phani-nunna** [comment]
DefaultBandwidthMeter     bandwidth_meter  = new DefaultBandwidthMeter(new Handler() , new BandwidthMeter.EventListener() {
            @Override
            public void onBandwidthSample(int elapsedMs, long bytes, long bitrate) {
                               // bitrate
                }
            }
        });

**Comment by VishwanathPatil** [comment]
As I can see through , hlsRenderBuilder has defaultBandwidthMeter
1) you should get the callback how internally it propgates to player .
2) or onRenderers in Demoplayer has bandwidthmeter which you can use to get
bitrateestimate a public method in DefaultBandwidthMeter

**Comment by crossle** [comment]
+1

**Comment by ojw28** [comment]
You should be listening to DemoPlayer.InfoListener.onVideoFormatEnabled. The format is passed to that method whenever the selection changes. Format.bitrate is the bitrate as declared in the master playlist. Format.width and Format.height are the dimensions as declared in the master playlist by RESOLUTION tags. Note that if RESOLUTION tags are omitted from the master playlist then these fields may be set to -1.

You can also use DemoPlayer.Listener.onVideoSizeChanged to determine when the resolution changes.

**Comment by crossle** [comment]
@ojw28  How about manual switch the bitrate not auto?

**Comment by ojw28** [comment]
See #676

**Comment by piterwilson** [comment]
@ojw28 thanks for the information on how to get the indicated bitrate. How about getting the actual observed bitrate? `onBandwidthSample.bitrateEstimate` looks promising, but i'm unable to confirm this is what i'm looking for.
