### ISSUE TITLE
Is there an API that returns the overall watch duration? (excludes time spent buffering)

### ISSUE THREAD

**Issue by greyski** [google/ExoPlayer#6460]
### [REQUIRED] Searched documentation and issues
Yes, I didn't find an API in ExoPlayer that returns this value.

### [REQUIRED] Question
We're working on logging metrics for our videos across both Android and iOS and found we couldn't find an ExoPlayer API that paralleled iOS in regards to tracking the watched duration. This watched duration value returns the video watch time of the user and automatically excludes time spent buffering. Is there a way to accurately track this value using callbacks from `AnalyticsListener`?

API for reference: https://developer.apple.com/documentation/avfoundation/avplayeritemaccesslogevent/1388200-durationwatched?language=objc

### A full bug report captured from the device
n/a

### Link to test content
n/a

**Comment by tonihei** [comment]
We'll add an `PlaybackStatsListener` in our next major release (2.11) that will give you all the analytics stats you can wish for. That includes the totalPlayTime, i.e. all the time the player spent actively playing (neither rebuffering nor paused). Would that solve your issue?

**Comment by greyski** [comment]
That sounds like exactly what we need. Thanks @tonihei, looking forward to the release.
