### ISSUE TITLE
Does Exoplayer V2 supports HLS widevine DRM encrypted Multisegmented Transport stream?

### ISSUE THREAD

**Issue by SharanKumarReddyKambham** [google/ExoPlayer#6464]
**Searched documentation and issues**
https://github.com/google/ExoPlayer/issues/4021

 **Question**

I am unable to play widevine encrypted HLS stream, which is a multisegmented TS stream
Does Exoplayer V2 support HLS widevine DRM encrypted Multisegmented Transport stream?

**Version Used**

Exoplayer 2.10.0

**Comment by AquilesCanta** [comment]
DRM-wise, we only support full sample encryption in Transport Stream. CDMs (Widevine, PlayReady, etc) are not supported. Please track #4021 for support for widevine in TS.
