### ISSUE TITLE
How can i set tag on MediaSource created by DownloadHelper?

### ISSUE THREAD

**Issue by emilsob** [google/ExoPlayer#6466]
### Searched documentation and issues
[Docs](https://exoplayer.dev/downloading-media.html)
Offline playback related issues
MediaSource related issues

### Question
How can I set tag on media source created by `DownloadHelper` utility class? I can easily achieve this by using `setTag` on `XMediaSource.Factory`, but i cannot find a similar way of doing this when using helper mentioned earlier.

Thanks in advance

**Comment by tonihei** [comment]
That's unfortunately not possible. The `DownloadHelper.createMediaSource` method is meant as a convenience method for the basic use case. If you need more advanced control (like setting a tag), you can just create the `MediaSource` on your own. The only important thing you need to do is to call `setStreamKeys(downloadRequest.streamKeys)` on the `MediaSource.Factory` to ensure that only the downloaded tracks are selected.

**Comment by emilsob** [comment]
Thanks a lot. This solves my issue, this part in particular: `setStreamKeys(downloadRequest.streamKeys)`
