### ISSUE TITLE
Encrypted videos are not playing after reboot

### ISSUE THREAD

**Issue by randeeppr** [google/ExoPlayer#647]
Hi,

I'm trying to play a Widevine Modular DRM encrypted MPEG Dash video in Exoplayer. We are using a hardware set top box  with Android 4.4 kitkat. Exoplayer plays the video first time when we play it after the board flashing. Second time, sometimes it plays and third time its not playing at all. If we restart the board after the first time playback also next time its not playing. 

What can be the issue. We have disabled the can_persist option of the license in policy. So everytime it should request for the new license. But when the videos are not playing, there is no calls(logs) coming in license proxy. 

Please see the logs below. 

Can we know whether the license is there in the system or exoplayer is trying to make a new call or anything?

--------- beginning of /dev/log/main
D/shafa   ( 2175): ***endAutoDownloadUpdateFile() startAutoDownloadUpdateFile
D/shafa   ( 2175): ***cancelAutoDownloadUpdateFile()  run
I/ActivityManager( 1814): Waited long enough for: ServiceRecord{41e66808 u0 com.android.calendar/.alerts.InitAlarmsService}
I/AudioPolicyManagerBase( 1357): ----FORCE_none: AudioPolicyManagerBase.cpp
I/AudioPolicyManagerBase( 1357): ----FORCE_none: AudioPolicyManagerBase.cpp
I/AudioTrack( 1814): AudioTrack::AudioTrack
I/AudioPolicyManagerBase( 1357): ----FORCE_none: AudioPolicyManagerBase.cpp
I/AudioPolicyManagerBase( 1357): AudioPolicyManagerBase::checkAndSetVolume 11,0.289578
I/AudioTrack( 1814): AudioTrack::~AudioTrack
I/ActivityManager( 1814): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=
com.google.android.exoplayer.demo/.SampleChooserActivity} from pid 2378

I/ActivityManager( 1814): Start proc com.google.android.exoplayer.demo for activity com.google.android.exoplayer.demo/.Sample
ChooserActivity: pid=2589 uid=10022 gids={50022, 3003, 1028, 1015}
D/dalvikvm( 2589): GC_CONCURRENT freed 61K, 5% free 3148K/3280K, paused 4ms+4ms, total 32ms
I/OMXClient( 2589): Using client-side OMX mux.
D/HIOMX_CORE( 2589): OMX_Init :: enter!
D/HIOMX_CORE( 2589): OMX_Init :: exit!
D/HIOMX_CORE( 2589): OMX_ComponentNameEnum :: g_ComponentTable[0].name: OMX.hisi.video.decoder 
D/HIOMX_CORE( 2589): OMX_ComponentNameEnum :: g_ComponentTable[1].name: OMX.hisi.video.decoder.secure 
D/HIOMX_CORE( 2589): OMX_ComponentNameEnum :: g_ComponentTable[2].name: OMX.hisi.video.encoder 
E/OMXNodeInstance( 2589): OMX_GetExtensionIndex OMX.google.android.index.storeMetaDataInBuffers failed
W/OMXNodeInstance( 2589): OMX_GetExtensionIndex OMX.google.android.index.prepareForAdaptivePlayback failed
V/OMXNodeInstance( 2589): calling destroyComponentInstance
V/OMXNodeInstance( 2589): destroyComponentInstance returned err 0
V/OMXNodeInstance( 2589): OMXNodeInstance going away.
D/OpenGLRenderer( 2589): Enabling debug mode 0
I/ActivityManager( 1814): Displayed com.google.android.exoplayer.demo/.SampleChooserActivity: +712ms
D/InitAlarmsService( 2311): Clearing and rescheduling alarms.
I/ActivityManager( 1814): Killing 1974:com.android.externalstorage/u0a5 (adj 15): empty #17
I/AudioTrack( 1814): AudioTrack::AudioTrack
I/AudioPolicyManagerBase( 1357): ----FORCE_none: AudioPolicyManagerBase.cpp
I/AudioPolicyManagerBase( 1357): startOutput() output 2, stream 1, session 9
I/AudioPolicyManagerBase( 1357): ----FORCE_none: AudioPolicyManagerBase.cpp
I/AudioPolicyManagerBase( 1357): startoutput ------- setOutputDevice ----
I/AudioPolicyManagerBase( 1357): ----FORCE_none: AudioPolicyManagerBase.cpp
I/AudioPolicyManagerBase( 1357): AudioPolicyManagerBase::checkAndSetVolume 11,0.289578
I/AudioTrack( 1814): AudioTrack::~AudioTrack
I/ActivityManager( 1814): START u0 {dat=http://test.domain.com/dark_knight/DARK_KNIGHT.mpd cmp=com.
google.android.exoplayer.demo/.PlayerActivity (has extras)} from pid 2589
D/dalvikvm( 2589): GC_CONCURRENT freed 69K, 4% free 3513K/3656K, paused 3ms+1ms, total 24ms
I/ExoPlayerImpl( 2589): Init 1.2.3
D/EventLogger( 2589): start [0]
D/EventLogger( 2589): state [0.00, false, P]
D/EventLogger( 2589): state [0.01, true, P]
I/ActivityManager( 1814): Displayed com.google.android.exoplayer.demo/.PlayerActivity: +364ms
D/dalvikvm( 2589): GC_CONCURRENT freed 126K, 5% free 3832K/4032K, paused 2ms+20ms, total 98ms

D/DnsProxyListener( 1352): argv[0]=getaddrinfo
D/DnsProxyListener( 1352): argv[1]=test.domain.com
D/DnsProxyListener( 1352): argv[2]=^
D/DnsProxyListener( 1352): argv[3]=1024
D/DnsProxyListener( 1352): argv[4]=0
D/DnsProxyListener( 1352): argv[5]=1
D/DnsProxyListener( 1352): argv[6]=0
D/DnsProxyListener( 1352): argv[7]=^
D/DnsProxyListener( 1352): GetAddrInfoHandler for test.domain.com / [nullservice] / [nulliface] / 2
589 / 10022
D/DnsProxyListener( 1352): GetAddrInfoHandler, now for test.domain.com / (null) / (null)
D/dalvikvm( 1814): GC_CONCURRENT freed 265K, 6% free 6238K/6580K, paused 2ms+4ms, total 92ms
W/SurfaceFlinger( 1354): couldn't log to binary event log: overflow.
I/AudioPolicyManagerBase( 1357): ----FORCE_none: AudioPolicyManagerBase.
D/WVCdm   ( 1357): Instantiating CDM.
I/WVCdm   ( 1357): Level3 Library Nov 20 2013 18:09:31
W/WVCdm   ( 1357): Could not load liboemcrypto.so. Falling Back to L3.  dlopen failed: library "liboemcrypto.so" not found
I/WVCdm   ( 1357): CdmEngine::QueryStatus
I/OMXClient( 2589): Using client-side OMX mux.
D/HIOMX_CORE( 1357): OMX_GetHandle :: enter!
D/HIOMX_CORE( 1357): OMX_GetHandle :: component name:OMX.hisi.video.decoder !
D/HIOMX_CORE( 1357): OMX_GetHandle :: prepare to load  libOMX.hisi.video.decoder.so
D/HIOMX_CORE( 1357): OMX_GetHandle :: load  libOMX.hisi.video.decoder.so ok
D/HISI_OMXVDEC( 1357): Init OMX component OMX.hisi.video.decoder
E/HISI_OMXVDEC( 1357): get_supported_profile_level: ProfileIndex(48) exceed!
E/HISI_OMXVDEC( 1357): get_extension_index: OMX.google.android.index.storeMetaDataInBuffers not implemented!
E/OMXNodeInstance( 1357): OMX_GetExtensionIndex OMX.google.android.index.storeMetaDataInBuffers failed
E/HISI_OMXVDEC( 1357): get_extension_index: OMX.google.android.index.prepareForAdaptivePlayback not implemented!
W/OMXNodeInstance( 1357): OMX_GetExtensionIndex OMX.google.android.index.prepareForAdaptivePlayback failed
V/OMXNodeInstance( 1357): calling destroyComponentInstance

V/OMXNodeInstance( 1357): destroyComponentInstance returned err 0
V/OMXNodeInstance( 1357): OMXNodeInstance going away.
D/EventLogger( 2589): state [5.63, false, I]
D/EventLogger( 2589): state [5.63, true, I]
D/EventLogger( 2589): state [5.67, true, P]
D/EventLogger( 2589): state [5.68, true, B]

D/dalvikvm( 2589): GC_CONCURRENT freed 261K, 8% free 4029K/4368K, paused 3ms+3ms, total 49ms
D/EventLogger( 2589): bandwidth [6.63, 13276, 0.30, 358810]
D/DnsProxyListener( 1352): argv[0]=getaddrinfo
D/DnsProxyListener( 1352): argv[1]=test.domain.com
D/DnsProxyListener( 1352): argv[2]=^
D/DnsProxyListener( 1352): argv[3]=1024
D/DnsProxyListener( 1352): argv[4]=0
D/DnsProxyListener( 1352): argv[5]=1
D/DnsProxyListener( 1352): argv[6]=0
D/DnsProxyListener( 1352): argv[7]=^
D/DnsProxyListener( 1352): GetAddrInfoHandler for test.domain.com / [nullservice] / [nulliface] / 2
589 / 10022
D/EventLogger( 2589): videoFormat [6.67, 1, 0]
D/DnsProxyListener( 1352): GetAddrInfoHandler, now for test.domain.com / (null) / (null)
I/WVCdm   ( 1357): CdmEngine::OpenSession
I/WVCdm   ( 1357): CdmEngine::QueryKeyControlInfo
I/WVCdm   ( 1357): CdmEngine::GenerateKeyRequest
D/EventLogger( 2589): bandwidth [6.72, 7845, 0.09, 358810]
D/WVCdm   ( 1357): PrepareKeyRequest: nonce=4175182594
I/WVCdm   ( 1357): CdmEngine::QuerySessionStatus
D/DnsProxyListener( 1352): argv[0]=getaddrinfo
D/DnsProxyListener( 1352): argv[1]=test.domain.com
D/DnsProxyListener( 1352): argv[2]=^
D/DnsProxyListener( 1352): argv[3]=1024
D/DnsProxyListener( 1352): argv[4]=0
D/DnsProxyListener( 1352): argv[5]=1
D/DnsProxyListener( 1352): argv[6]=0
D/DnsProxyListener( 1352): argv[7]=^
D/DnsProxyListener( 1352): GetAddrInfoHandler for test.domain.com / [nullservice] / [nulliface] / 2
589 / 10022
D/DnsProxyListener( 1352): GetAddrInfoHandler, now for test.domain.com / (null) / (null)
I/OMXClient( 2589): Using client-side OMX mux.
D/HIOMX_CORE( 1357): OMX_GetHandle :: enter!
D/HIOMX_CORE( 1357): OMX_GetHandle :: component name:OMX.hisi.video.decoder !
D/HIOMX_CORE( 1357): OMX_GetHandle :: prepare to load  libOMX.hisi.video.decoder.so
D/HIOMX_CORE( 1357): OMX_GetHandle :: load  libOMX.hisi.video.decoder.so ok
D/HISI_OMXVDEC( 1357): Init OMX component OMX.hisi.video.decoder
E/HISI_OMXVDEC( 1357): get_extension_index: OMX.google.android.index.storeMetaDataInBuffers not implemented!
E/OMXNodeInstance( 1357): OMX_GetExtensionIndex OMX.google.android.index.storeMetaDataInBuffers failed
E/ACodec  ( 2589): [OMX.hisi.video.decoder] storeMetaDataInBuffers failed w/ err -2147483648
E/HISI_OMXVDEC( 1357): get_extension_index: OMX.google.android.index.prepareForAdaptivePlayback not implemented!
W/OMXNodeInstance( 1357): OMX_GetExtensionIndex OMX.google.android.index.prepareForAdaptivePlayback failed
W/ACodec  ( 2589): [OMX.hisi.video.decoder] prepareForAdaptivePlayback failed w/ err -2147483648
D/HISI_OMXVDEC( 1357): [OmxState] Loaded --> Idle_Pending
D/HISI_OMXVDEC( 1357): [OmxState] Idle_Pending --> Idle
D/HISI_OMXVDEC( 1357): [OmxState] Idle --> Executing_Pending
D/HISI_OMXVDEC( 1357): [OmxState] Execute_Pending --> Executing
D/EventLogger( 2589): audioFormat [6.92, 0, 0]
I/OMXClient( 2589): Using client-side OMX mux.
D/HIOMX_CORE( 2589): OMX_Init :: enter!
D/HIOMX_CORE( 2589): OMX_Init :: exit!
D/HIOMX_CORE( 2589): OMX_ComponentNameEnum :: g_ComponentTable[0].name: OMX.hisi.video.decoder 
D/HIOMX_CORE( 2589): OMX_ComponentNameEnum :: g_ComponentTable[1].name: OMX.hisi.video.decoder.secure 
D/HIOMX_CORE( 2589): OMX_ComponentNameEnum :: g_ComponentTable[2].name: OMX.hisi.video.encoder 
V/OMXNodeInstance( 2589): calling destroyComponentInstance
V/OMXNodeInstance( 2589): destroyComponentInstance returned err 0
V/OMXNodeInstance( 2589): OMXNodeInstance going away.
I/OMXClient( 2589): Using client-side OMX mux.
D/HIOMX_CORE( 2589): OMX_Init :: enter!
D/HIOMX_CORE( 2589): OMX_Init :: exit!
D/HIOMX_CORE( 2589): OMX_ComponentNameEnum :: g_ComponentTable[0].name: OMX.hisi.video.decoder 
D/HIOMX_CORE( 2589): OMX_ComponentNameEnum :: g_ComponentTable[1].name: OMX.hisi.video.decoder.secure 
D/HIOMX_CORE( 2589): OMX_ComponentNameEnum :: g_ComponentTable[2].name: OMX.hisi.video.encoder 
D/dalvikvm( 2589): GC_CONCURRENT freed 122K, 6% free 4298K/4572K, paused 3ms+1ms, total 34ms
D/dalvikvm( 2589): WAIT_FOR_CONCURRENT_GC blocked 28ms
D/dalvikvm( 2589): GC_FOR_ALLOC freed <1K, 6% free 4554K/4844K, paused 12ms, total 12ms
D/dalvikvm( 2589): GC_FOR_ALLOC freed 1K, 6% free 4872K/5184K, paused 13ms, total 13ms
D/dalvikvm( 2589): GC_FOR_ALLOC freed <1K, 5% free 5321K/5592K, paused 12ms, total 12ms
I/SoftAAC2( 2589): Reconfiguring decoder: 0->44100 Hz, 0->2 channels
I/AudioPolicyManagerBase( 1357): ----FORCE_none: AudioPolicyManagerBase.cpp
I/AudioTrack( 2589): AudioTrack::AudioTrack
I/AudioPolicyManagerBase( 1357): ----FORCE_none: AudioPolicyManagerBase.cpp
D/EventLogger( 2589): videoSizeChanged [1280, 720, 1.0]
I/AudioPolicyManagerBase( 1357): startOutput() output 2, stream 3, session 10
I/AudioPolicyManagerBase( 1357): ----FORCE_none: AudioPolicyManagerBase.cpp
I/AudioPolicyManagerBase( 1357): startoutput ------- setOutputDevice ----
I/AudioPolicyManagerBase( 1357): ----FORCE_none: AudioPolicyManagerBase.cpp
I/AudioPolicyManagerBase( 1357): AudioPolicyManagerBase::checkAndSetVolume 11,0.425354
I/AudioPolicyManagerBase( 1357): ----FORCE_none: AudioPolicyManagerBase.cpp
D/EventLogger( 2589): state [8.86, true, R]
D/EventLogger( 2589): bandwidth [9.32, 423907, 1.90, 1782994]
D/DnsProxyListener( 1352): argv[0]=getaddrinfo
D/DnsProxyListener( 1352): argv[1]=test.domain.com
D/DnsProxyListener( 1352): argv[2]=^
D/DnsProxyListener( 1352): argv[3]=1024
D/DnsProxyListener( 1352): argv[4]=0
D/DnsProxyListener( 1352): argv[5]=1
D/DnsProxyListener( 1352): argv[6]=0
D/DnsProxyListener( 1352): argv[7]=^
D/DnsProxyListener( 1352): GetAddrInfoHandler for test.domain.com / [nullservice] / [nulliface] / 2
589 / 10022
D/DnsProxyListener( 1352): GetAddrInfoHandler, now for test.domain.com / (null) / (null)
D/EventLogger( 2589): bandwidth [11.54, 1168522, 2.22, 4210890]
D/DnsProxyListener( 1352): argv[0]=getaddrinfo
D/DnsProxyListener( 1352): argv[1]=test.domain.com
D/DnsProxyListener( 1352): argv[2]=^
D/DnsProxyListener( 1352): argv[3]=1024
D/DnsProxyListener( 1352): argv[4]=0
D/DnsProxyListener( 1352): argv[5]=1
D/DnsProxyListener( 1352): argv[6]=0
D/DnsProxyListener( 1352): argv[7]=^
D/DnsProxyListener( 1352): GetAddrInfoHandler for test.domain.com / [nullservice] / [nulliface] / 2
589 / 10022
D/DnsProxyListener( 1352): GetAddrInfoHandler, now for test.domain.com / (null) / (null)
D/EventLogger( 2589): bandwidth [15.86, 165890, 1.85, 4210890]
D/dalvikvm( 2589): GC_CONCURRENT freed 205K, 5% free 5916K/6208K, paused 3ms+2ms, total 38ms
D/dalvikvm( 2589): WAIT_FOR_CONCURRENT_GC blocked 32ms
D/dalvikvm( 2589): GC_FOR_ALLOC freed 3K, 5% free 6681K/7024K, paused 13ms, total 14ms
D/EventLogger( 2589): bandwidth [18.39, 597243, 2.41, 1980084]
D/EventLogger( 2589): bandwidth [19.94, 1050811, 1.55, 5427041]
D/DnsProxyListener( 1352): argv[0]=getaddrinfo
D/DnsProxyListener( 1352): argv[1]=test.domain.com
D/DnsProxyListener( 1352): argv[2]=^
D/DnsProxyListener( 1352): argv[3]=1024
D/DnsProxyListener( 1352): argv[4]=0
D/DnsProxyListener( 1352): argv[5]=1
D/DnsProxyListener( 1352): argv[6]=0
D/DnsProxyListener( 1352): argv[7]=^
D/DnsProxyListener( 1352): GetAddrInfoHandler for test.domain.com / [nullservice] / [nulliface] / 2
589 / 10022
D/DnsProxyListener( 1352): GetAddrInfoHandler, now for test.domain.com / (null) / (null)
D/EventLogger( 2589): state [20.03, true, B]
I/AudioFlinger( 1357): BUFFER TIMEOUT: remove(4098) from active list on thread 0xb5130008
I/AudioPolicyManagerBase( 1357): ----FORCE_none: AudioPolicyManagerBase.cpp
I/AudioPolicyManagerBase( 1357): ----FORCE_none: AudioPolicyManagerBase.cpp
D/EventLogger( 2589): bandwidth [24.34, 9764, 0.35, 5427041]
D/dalvikvm( 2589): GC_CONCURRENT freed 204K, 4% free 7744K/8040K, paused 3ms+3ms, total 24ms
D/dalvikvm( 2589): WAIT_FOR_CONCURRENT_GC blocked 19ms
D/dalvikvm( 2589): GC_FOR_ALLOC freed 3K, 4% free 9150K/9468K, paused 13ms, total 13ms
D/dalvikvm( 2589): GC_FOR_ALLOC freed 7K, 3% free 10945K/11236K, paused 13ms, total 13ms
D/EventLogger( 2589): bandwidth [26.83, 427401, 1.81, 5427041] 

Regards,
Randeep

**Comment by ojw28** [comment]
Has the device passed Android CTS (i.e. is it officially an Android device)? What device is it exactly?

**Comment by randeeppr** [comment]
It is an OTT device with Widevine Level 3 drm support enabled. Chipset is from HiSilicon company and Google has given them this particular software suite.

**Comment by randeeppr** [comment]
The issue is sometimes the video is playing. Sometime not. It is showing no errors in the log. Video just get stuck after 10s(first 10s are not encrypted)

**Comment by tajoumal** [comment]
Hi, we have the same issue on Samsung devices, any clue?

**Comment by halibegic** [comment]
@randeeppr Do you mind sharing your solution to this issue? I have the same problem with AMLogic device. Problem occured on ExoPlayer v2.3.1 and v2.1.1, other versions are not tested.
