### ISSUE TITLE
Image stuck on video after going back to app from background on Android 10

### ISSUE THREAD

**Issue by patrycjasosnowska** [google/ExoPlayer#6473]
### [REQUIRED] Issue description
I use ExoPlayer in Android app to record and play video files. Since I don't want to pause playback when app goes to background, when I play video and move app to the background sound is still heard. When I am going back to my app, and bind player to new playerView sound is heard, but image in video is stopped at this moment, which I move app to the background. After usage of seekBar image in video works well again. 

### [REQUIRED] Reproduction steps
-record video file
-play video
-while video is playing go to background
-go back to app
-sound is heard but image in video stops

### [REQUIRED] Link to test content
--

### [REQUIRED] A full bug report captured from the device
--

### [REQUIRED] Version of ExoPlayer being used
I use ExoPlayer v2.10.0.

### [REQUIRED] Device(s) and version(s) of Android being used
It happens on multiple devices with Android 10 version only. On other devices with lower OS version everything works fine.

**Comment by tonihei** [comment]
Can you provide more details on how your background playback is working?

In particular:
- Are you using a foreground service?
- Are you making any changes to the `DefaultTrackSelector` (e.g. disable the video track)?
- Are you unbinding the player from the previous `PlayerView`? 
- What kind of view are you using? (SurfaceView, TextureView, ..)
- Also, what kind of `MediaSource` are you using? And can you provide an example stream in case it's media related?
