### ISSUE TITLE
about RTP  and RTSP supported

### ISSUE THREAD

**Issue by arlimm318** [google/ExoPlayer#6474]
My project needs to support both RTP and RTSP,But I see that the RTP and RTSP support libraries  int two branches ,What should I do with these 2 branches?Do I need to merge two branches into one?That would be complicated.
I need a branch that supports both RTP and RTSP.

**Comment by icbaker** [comment]
ExoPlayer doesn't currently support RTP or RTSP.

Pull request #3854 adds this, but it hasn't been merged.

There are no RTP or RTSP branches in this repository. Possibly you're referring to the source of the above pull request, which has both dev-v2-rtp and dev-v2-rtsp: https://github.com/tresvecesseis/ExoPlayer

If you have questions about how to use the RT(S)P implementations from that fork, I suggest you ask over there.
