### ISSUE TITLE
Consider extracting duration via TSExtractor for standalone MPEGTS files

### ISSUE THREAD

**Issue by IanDBird** [google/ExoPlayer#648]
This is a feature request, after doing some testing on how well ExoPlayer handles HEVC via various file formats. A significant number of samples (available from http://demo-uhd3d.com/categorie.php?tag=hevc) are standalone mpegts files. When these are played back via ExoPlayer, they work fine except the player doesn't provide a duration, or allow seeking.

I understand that the MPEGTS file format isn't really designed for this type of standalone files, but it's not uncommon. I believe a "standard" way to extract this information is to read the first several packets, then seek to ~250KB before EOF, then locate the start of a packet and read to the end to get the last packet's timestamp. This allows the calculation to be `last + last.duration - first`.

As a point of reference, libavformat's `estimate_timings_from_pts` provides something similar (`avformat/utils.c`).

Is this something that would be considered?

**Comment by ojw28** [comment]
TBD, but I doubt we'll do this. If someone wants their file to be seekable, they should really use an appropriate container format.

**Comment by IanDBird** [comment]
I completely understand...

Out of interest, what if the duration was actually known already by the application/player. Is there any clean way for the app to provide this information so that it can be used by ExoPlayer?

**Comment by ojw28** [comment]
There would still no clean way to seek, because there's no index and no guarantee that the bitrate is constant. If the application had an index then that would work. You could have the application build a HLS variant playlist with each segment defined by byte ranges (which serves as the index), and then play the content as HLS.

**Comment by VishwanathPatil** [comment]
I feel , keeping local playback as interest along with streaming . player
should support playback of local files.

**Comment by ojw28** [comment]
The player does support playback of local files.
