### ISSUE TITLE
UnrecognizedInputFormatException for mp4 url

### ISSUE THREAD

**Issue by ksc91u** [google/ExoPlayer#6481]
### [REQUIRED] Content description
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'live_ef0ad394-8826-4aea-9421-439501068140_Rw2jK.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    creation_time   : 2019-09-01T14:01:23.000000Z
    encoder         : Lavf57.25.100
  Duration: 02:00:29.21, start: 0.000000, bitrate: 118 kb/s
    Stream #0:0(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 114 kb/s (default)
    Metadata:
      creation_time   : 2019-09-01T14:01:23.000000Z
      handler_name    : SoundHandler

### [REQUIRED] Link to test content
sent via email

### [REQUIRED] Version of ExoPlayer being used
2.10.4 in our app,
https://github.com/google/ExoPlayer.git @release-v2 commit 1d3d92ee4

### [REQUIRED] Device(s) and version(s) of Android being used
Pixel 3 Android 10 QP1A.190711.020.c3

### [REQUIRED] A full bug report captured from the device
sent via email

**Comment by ksc91u** [comment]
I can play the media with r2.8.4, last working version 2.9.3

**Comment by kim-vde** [comment]
I tried to reproduce the issue but I couldn't.

Can you be more specific about which version of ExoPlayer you are using (release tag or commit)? Release tag r2.10.4 and commit 1d3d92e do not correspond.

Can you reproduce the issue in ExoPlayer demo app?

**Comment by ksc91u** [comment]
Hi, I push demo app here

https://github.com/ksc91u/ExoPlayer/tree/fail-demo

could not play 
Misc - Fail m4a from google storage
Misc - Fail m4a from cloudflare

thanks

**Comment by kim-vde** [comment]
I can play the audio you sent by email without issue. Do you have troubles playing it?

About the 2 audio files you added in daae325, you get an error because they are malformed for the reason explained in #6441.

**Comment by ksc91u** [comment]
I can play the file I send you via email, sorry I sent the wrong link.

Thank you for the explanation

**Comment by kim-vde** [comment]
Duplicate of #6441.
