### ISSUE TITLE
Pixel 1 camera captured video has artifact bars on each side

### ISSUE THREAD

**Issue by lukepighetti** [google/ExoPlayer#6486]
### [REQUIRED] Content description
Playing video on Pixel 1 (Android 10) that was captured on same device causes artifacts to appear on the left and right of the screen.

### [REQUIRED] Link to test content
Literally any video captured on a Pixel 1 on Android 10 with the default built-in camera and app.

### [REQUIRED] Version of ExoPlayer being used
`video_player: ^0.10.2+1` on Flutter

### [REQUIRED] Device(s) and version(s) of Android being used
Pixel 1, Android 10, Flutter 1.10.4-pre.30, video_player: 0.10.2+1

### [REQUIRED] A full bug report captured from the device
There is no bug report captured from the device?

![IMG_610A6B0E450E-1](https://user-images.githubusercontent.com/666539/65834156-40bbaa80-e2a6-11e9-8047-8b9d2721a1f7.jpeg)

![IMG_610A6B0E450E-1](https://user-images.githubusercontent.com/666539/65834179-6ea0ef00-e2a6-11e9-8614-eebed94f52a4.jpeg)

**Comment by kim-vde** [comment]
Could you try to reproduce the issue on the ExoPlayer demo app?
