### ISSUE TITLE
Managing the UI in a HLS Video with a dynamic DVR window

### ISSUE THREAD

**Issue by sejalis** [google/ExoPlayer#6487]
### Searched documentation and issues
I didnt find anything on that in the documentation. Some Issues were it was mentioned:
https://github.com/google/ExoPlayer/issues/87   (second case)
https://github.com/google/ExoPlayer/pull/1394#issuecomment-203254269

### Question
Hello! I'm a quite new Android Developer who is working on a TV Project for VOD and Livestreams on FireTV. We are using the amazon Exoplayer com.amazon.android:exoplayer:2.10.1 with its ima Extension 2.10.1. The app is using a custom playback controller
`app:controller_layout_id="@layout/layout_playback_control"`
I have two questions relating to a HLS Stream with a 5h DVR window. 

1. Is it possible to set the Position relative to the Duration of the Stream? The issue 87 #2 requests that feature, but I was not able to find any solution to this. The Streams have a 5h window with 6 seconds segments. When I start the stream it seeks to the latest window, showing the position with e.g. 4:59:38 (I've set an offset to have a better buffering behaviour). Every time it loads a new segment, for example at 4:59:44, the stream position jumps back to 4:58:38. What I'm required to do is, to implement a relative position to the live - moment. So when I rewind 20 seconds it would show -00:20 for example. I was trying to set the text of the duration manually by having an observable (Rx) which checks it manually, but the duration gets overwritten from the player. 
Is there something I can set inside the exoplayer to behave differently in case of a livestream? 

2. I want to disable the forward button when the user is close to live. I manage that by an observable, which sets it's visibility

`val forwardLiveImage = videoPlayer?.playerView?.findViewById<ImageView>(R.id.forward_live)
        val exoFwdButton = videoPlayer?.playerView?.findViewById<ImageView>(R.id.exo_ffwd)`

        `if (isLiveStream) {
            forwardLiveImage?.onClick { videoPlayer?.seekToNearLive() }

            nearLiveDisposable.safeDispose()
            nearLiveDisposable = Observable.interval(0, 1, TimeUnit.SECONDS)
                .subscribeOn(Schedulers.newThread())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe {
                    val isLive = videoPlayer?.isNearLive() == true
                    logv { "isLive $isLive" }

                    // @see selector_live_status.xml
                    // isLive = disabled, else = enabled
                    // focusable when we are NOT Live
                    forwardLiveImage?.isEnabled = !isLive
                    forwardLiveImage?.isFocusable = !isLive

                    // disable forward button, when live
                    exoFwdButton?.isVisible = !isLive
                    exoFwdButton?.isFocusable = !isLive
                }
        }`
so this works while it's inside of a 6-sec-segment when it is live. Once it loads a new segment/ the onTimeLineChanged function gets called, the ffwd image is shown for a brief period of time, after it gets invisible again. I am managing the visibility of this button only here, so my question is, is there some kind of ui reset which i can override? I was thinking about renaming the buttons id, but I'm not sure if I would lose the exoplayers functionalities.
Sorry for the long read and thank you in advance!

**Comment by kim-vde** [comment]
There is no trivial way to implement what you need. I added the enhancement label to potentially add this feature in the future.

What you could do for now is to fork ExoPlayer class `PlayerControlView` and update it to meet your needs.

**Comment by sejalis** [comment]
Even if I do fork it, I still don't know where and why the visibility of the views gets reset (2.), could you provide more information?

**Comment by kim-vde** [comment]
I meant that you could fork `PlayerControlView` for both issues and avoid using observables.

The forward button probably gets re-enabled in method `updateNavigation`.

**Comment by sejalis** [comment]
ok, will try. Thank you!

**Comment by ojw28** [comment]
For the feature request itself, let's merge this into #2213, which we'll use to track the general request for increased UI flexibility for live playbacks.
