### ISSUE TITLE
Is it possible to play a mp4 video in loop using the ExtractorRendererBuilder

### ISSUE THREAD

**Issue by SilkSama** [google/ExoPlayer#649]
Hi,

I need to play short videos in loop from a server. I try to use the seek method to replay the video when the ExoPlayer.STATE_ENDED is reached but the video is play from the server again (no kind of cache).
Are there specific parameters to be defined to play a video in loop without reload it from server again and again or I need to download the video before and play it from the local file system ?

Thank you in advance for your help.

**Comment by ojw28** [comment]
This is not currently supported as a built in feature. You could write your own DataSource implementation to cache the video data on disk the first time it's requested (and serve it from disk for subsequent requests). We have a related request that would add support to this directly to the library here: #420. You could alternatively just download the video first and play it from a local file uri as you suggest.
