### ISSUE TITLE
RTMP problem with play time.

### ISSUE THREAD

**Issue by SFocus** [google/ExoPlayer#6495]
### Content description
The problem is that there is an amazon server that streams the mp3 file via RTMP. The exoplayer only plays 1 minute or more but not the full file. 

###  Link to test content
rtmp://s22x225isx33fy.cloudfront.net:1935/cfx/st/1.mp3

### Version of ExoPlayer being used
exoplayer_version = '2.10.5'
exoplayer_rtmp_version = '2.9.6'

###  Device(s) and version(s) of Android being used
Samsung S9+ Android 9.0

### Code 
`val mediaSourceFactory = ProgressiveMediaSource.Factory(RtmpDataSourceFactory())
  val concatenatingMediaSource = ConcatenatingMediaSource()
   for (song in songs) {
            val mediaSource = mediaSourceFactory.createMediaSource(Uri.parse(song.songLink))
            concatenatingMediaSource.addMediaSource(mediaSource)
        } 
player.prepare(concatenatingMediaSource)
player.playWhenReady = true`

**Comment by tonihei** [comment]
Sorry for the delayed reply.  I tried to play the stream, but I immediately get RTMP error -6, which is DNS_NOT_REACHABLE if I [read the code](https://github.com/ant-media/LibRtmp-Client-for-Android/blob/c361f5da14d3bf7ed1affb4ea0ff41b53ba9d41c/rtmp-client/src/main/java/net/butterflytv/rtmp_client/RtmpClient.java#L58) correctly. Can you check if the stream is still working?

**Comment by SFocus** [comment]
@tonihei, unfortunately, I can not help anything, we gave up RTMP and moved to HLS. Thanks for the help! Sorry for the long answer.
