### ISSUE TITLE
Increasing HLS DVR size?

### ISSUE THREAD

**Issue by developer244** [google/ExoPlayer#6507]
Hey everyone,

Usually I found out that ExoPlayer support HLS DVR or in other words rewind and forward live stream using HLS format, it's working great but the limit of the timeshift is only 1 minute, is it possible to increase it?

Already tried increasing the buffering and the cache size, but none helped.
Any ideas?

**Comment by AquilesCanta** [comment]
The seeking window contains whatever the media playlist advertises. So, you'll need to fix this on the server side, by extending the live window. We don't currently support recording live streams. Track #3877 for more info on downloading live streams.
