### ISSUE TITLE
Mp4 not playing from Storage

### ISSUE THREAD

**Issue by polaris0227** [google/ExoPlayer#6508]
### [REQUIRED] Content description
I can't play the video from storage which is downloaded from below link.
I tried below code for mediasource
`DataSource.Factory dataSourceFactory = new DefaultDataSourceFactory(App.getApp(), "ua");
            return new ExtractorMediaSource.Factory(dataSourceFactory).createMediaSource(uri);`

### [REQUIRED] Link to test content
https://drive.google.com/open?id=1GIYSqLF3dvqJr0LE0H2oKE1vhvtuVUiM

### [REQUIRED] Version of ExoPlayer being used
2.9.6

### [REQUIRED] Device(s) and version(s) of Android being used
Samsung Galaxy 5.1

### [REQUIRED] A full bug report captured from the device
[log.txt](https://github.com/google/ExoPlayer/files/3688299/log.txt)

**Comment by kim-vde** [comment]
It seems the media is malformed. The box of type mdat starts at offset 18041 while the udta box indicates that is should start at offset 18039.

We don't know how the other players overcome this. Feel free to fix this if you have any idea.
