### ISSUE TITLE
How to change color in the player?

### ISSUE THREAD

**Issue by halilozel1903** [google/ExoPlayer#6509]
`app:played_color="#401955"`

I'm using in layout but it doesn't change color.

Help me please

**Comment by ojw28** [comment]
It's very unclear what this question means. What colour are you trying to change?

**Comment by halilozel1903** [comment]
![Screenshot_1570429010](https://user-images.githubusercontent.com/22895813/66288794-4e46e500-e8e3-11e9-890d-fcca9808565d.png)

@ojw28 I want to change the color of the player field 
default color : blue

**Comment by ojw28** [comment]
Setting `app:played_color="#401955"` on `PlayerView` works fine for me.  Note that for this to work, you must be using ExoPlayer 2.10.2 or later.

**Comment by ojw28** [comment]
Closing on the assumption that you're using an earlier version of ExoPlayer, and that's why it's not working for you. Note that you may also want to adjust `app:scrubber_color`, `app:buffered_color` and `app:unplayed_color` to get things looking the way you want them.

**Comment by halilozel1903** [comment]
@ojw28 thanks for help
