### ISSUE TITLE
PlayerView attach/detach Memory Leak 

### ISSUE THREAD

**Issue by x0rb0t** [google/ExoPlayer#6511]
### Issue description
Memory leak when the PlayerView is detached and re-attached to window
It usually happens when PlayerView is used in RecyclerView
Memory usage grows each time when prepare() called after PlayerView was detached and attached from window

### Reproduction steps
Demo app without using RecyclerView:
https://github.com/x0rb0t/ExoPlayerMemoryLeak

Memory usage log if PlayerView is removing and adding to the layout + call prepare media souce (N times), then player released
![Screenshot_1570294402](https://user-images.githubusercontent.com/4983411/66258435-87793b00-e7a5-11e9-9225-307cc73e14f9.png)

Memory usage log if just prepare media source called (N times), then player released
![Screenshot_1570296141](https://user-images.githubusercontent.com/4983411/66258434-87793b00-e7a5-11e9-85db-0092a62efd34.png)

### Link to test content
Content is stored in assets directory of demo app

### Version of ExoPlayer being used
implementation 'com.google.android.exoplayer:exoplayer-core:2.10.5'
implementation 'com.google.android.exoplayer:exoplayer-ui:2.10.5'

### Device(s) and version(s) of Android being used
Android Emulator (affected by this bug):
CPU/ABI: Google APIs Intel Atom (x86)
Target: google_apis [Google APIs] (API level 28)
hw.device.name: Nexus 5X

Huawei and Samsung looks like is not affected with this bug

**Comment by ojw28** [comment]
Have you managed to reproduce this on any real device? If not, I suspect this is an emulator bug rather than a problem with ExoPlayer.

**Comment by x0rb0t** [comment]
No, this bug I've managed to reproduce only on the Emulator.

But I found some other problem on real device with very high memory usage with two instances of 4 second video (SampleQueue$AllocationNode retained size 62 923 178 476 (sic!), ExoPlayerImpInternal retained size 459 379 314). I will open issue when get more info.

**Comment by ojw28** [comment]
I filed https://issuetracker.google.com/142528714 to track what's likely a memory leak in the emulator implementation. I will close this one. Thanks!
