### ISSUE TITLE
Player does not react when stream changes on same url for RTMP live video

### ISSUE THREAD

**Issue by Deepak1202** [google/ExoPlayer#6514]
[REQUIRED] Issue description
Playing a RTMP link which plays a live feed and in sometime stream gets ended and starts a new live video on same url, but player doesnot react this change and when stream changes it gets stuck in buffering state.

[REQUIRED] Reproduction steps
Start a RTMP stream and stream a video and after sometime stop the stream and start a new one on same url.

[REQUIRED] Version of ExoPlayer being used 
2.10.3

[REQUIRED] Device(s) and version(s) of Android being used
Device: Fire Stick
Android: Fire OS 5.2.7.1(Equivalent to Android 5.1.1 Lollipop)

**Comment by christosts** [comment]
Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md). If you're unable to share bug reports or test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Please also update this issue to indicate you’ve done this.

**Comment by Deepak1202** [comment]
I have updated the question in required format.

**Comment by christosts** [comment]
Hi @Deepak1202,

I have performed some basic tests with RTMP on a Lollipop device (**not** a Fire Stick). At this point, may I ask you to:
- provide me with the RTMP link that is causing the behavior you are observing
- clarify exactly what is happening: the ticket title says "stream changes on same url" and the ticket description mentions to start and stop. Is it that you start streaming, then exit playback from your app, then start again with the same RTMP stream? Or is the stream doing something else?
- have you tried the RTMP stream with our demo app?
- can you share any logs from the device?

If any of the above cannot be shared publicly, you can send them to dev.exoplayer@gmail.com using this ticket's number as a subject (detailed instructions were given on the comment [above](https://github.com/google/ExoPlayer/issues/6514#issuecomment-539441733))

Last, but not least, I need to mention that Fire OS devices are not supported by ExoPlayer, please see [Supported Devices](https://exoplayer.dev/supported-devices.html). Therefore we might not be able to assist in full.

**Comment by Deepak1202** [comment]
Thanks for the response @christosts,

- I can provide you the rtmp stream link, unfortunately the stream will get accessed locally to my network.
- Actually I have launched player with a rtmp stream and I don't do exit or anything which interrupts player. From the stream server only it gets stopped and starts again with the new video.
- I have tried with demo app it is having the same issue.
- I also observed the logs and I found below line when stream stuck, and it gets printed continuously.
E/AudioTrack: Discontinuity detected [expected 2464315, got 2264000]

If I get the Discontinuity detected callback in my app from player, then I can manage it accordingly like I can reinitialize the player to make it work. If we have such callback then please let us know or somehow we can achieve the same.

**Comment by christosts** [comment]
From

>From the stream server only it gets stopped and starts again with the new video.

and 

> E/AudioTrack: Discontinuity detected [expected 2464315, got 2264000]

from the player perspective, it looks like the stream is malformed. The audio timestamp goes back by 2464315 - 2264000 = 200315 ~= 200 seconds. 

Can you check why the stream does that? Not sure the player can internally react to this.
