### ISSUE TITLE
extractor to decode raw H264 video stream

### ISSUE THREAD

**Issue by takizuki** [google/ExoPlayer#6519]
### [REQUIRED] Searched documentation and issues
https://github.com/google/ExoPlayer/issues/3503
https://github.com/google/ExoPlayer/issues/5175
https://github.com/google/ExoPlayer/issues/5604
https://stackoverflow.com/questions/50217980/how-to-play-raw-nal-units-in-android-exoplayer

### [REQUIRED] Question
I've implemented raw H.264 stream decoder by using MediaCodec directly.
I'm implementing ExoPlayer Plugin to play the stream.
I made custom Extractor,DataSource DataSourceFactory, H264Reader.
when I execute my app, the first frame is visible. but next frame doesn't come.
my problem might be same as TroyStopera asked last year.
https://github.com/google/ExoPlayer/issues/5175

could you teach me how to implement Extractor class and
what value is good for argument of H264Reader.packetStarted(Long, Boolean)?
I already tried 0 and System.nanoTime()/1000.

**Comment by christosts** [comment]
I see that you have already found similar issues describing a similar situation. May I ask if you are something different than the issues already listed, and if yes, what exactly?
