### ISSUE TITLE
FragmentedMp4Extractor does not correctly handle atomSize==1

### ISSUE THREAD

**Issue by markniebur** [google/ExoPlayer#652]
I'm trying to play some fmp4 video and am getting the following stack track:
```
07-20 18:05:57.021  31070-32725/? E/LoadTask﹕ Unexpected exception loading stream
java.lang.IllegalStateException: Top bit not zero: -268435456
at com.google.android.exoplayer.util.ParsableByteArray.readUnsignedIntToInt(ParsableByteArray.java:240)
at com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.readSample(FragmentedMp4Extractor.java:628)
at com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:162)
at com.google.android.exoplayer.chunk.ChunkExtractorWrapper.read(ChunkExtractorWrapper.java:93)
at com.google.android.exoplayer.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:155)
at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)

at java.lang.Thread.run(Thread.java:818)
```

This video plays fine in the dash-if player and in QT/vlc.  Any idea what could be causing this exception?
Video is at: https://drive.google.com/file/d/0B7NmnUABUz_FS3VxRGFVRU1UVzg/view?usp=sharing

**Comment by VishwanathPatil** [comment]
You have moov fragment in that file ?
On Jul 24, 2015 12:51 AM, "markniebur" <notifications@github.com> wrote:
>
> I'm trying to play some fmp4 video and am getting the following stack
track:
> ```07-20 18:05:57.021 31070-32725/? E/LoadTask﹕ Unexpected exception
loading stream
> java.lang.IllegalStateException: Top bit not zero: -268435456
> at
com.google.android.exoplayer.util.ParsableByteArray.readUnsignedIntToInt(ParsableByteArray.java:240)
> at
com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.readSample(FragmentedMp4Extractor.java:628)
> at
com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:162)
> at
com.google.android.exoplayer.chunk.ChunkExtractorWrapper.read(ChunkExtractorWrapper.java:93)
> at
com.google.android.exoplayer.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:155)
> at
com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
> at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
> at java.util.concurrent.FutureTask.run(FutureTask.java:237)
> at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
> at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
>
> at java.lang.Thread.run(Thread.java:818)```
>
> This video plays fine in the dash-if player and in QT/vlc. Any idea what
could be causing this exception?

**Comment by markniebur** [comment]
No, the moov box is needed, mostly to pass in video encoding parameters to the player.  There is no video described in the moov, only in the moof boxes afterwards.

**Comment by VishwanathPatil** [comment]
Then how you will specify codec specific data , do you have manifest ?
On Jul 24, 2015 4:34 AM, "markniebur" <notifications@github.com> wrote:
>
> No, the moov box is needed, mostly to pass in video encoding parameters
to the player. There is no video described in the moov, only in the moof
boxes afterwards.

**Comment by markniebur** [comment]
What do you mean by codec specific data?  Relevant part of manifest is below, I am using a SegmentTemplate which needs an initialization attribute which points to the moov box.  I have been seeing this in all of the dash examples online and at the youtube dash-mse test page and the dash-if test pages as well.

```
    <AdaptationSet mimeType="video/mp4" segmentAlignment="true" startWithSAP="1">
      <Role schemeIdUri="urn:mpeg:dash:role:2011" value="main"/>
      <SegmentTemplate initialization="format-bmff-track-video-bandwidth-$Bandwidth$-repid-$RepresentationID$-header.mp4" media="format-bmff-track-video-bandwidth-$Bandwidth$-repid-$RepresentationID$-frag-$Number$.mp4" timescale="90000" startNumber="1">
        <SegmentTimeline>
          <S d="180180" r="4093"/>
        </SegmentTimeline>
      </SegmentTemplate>
      <Representation id="259389" bandwidth="259389" codecs="avc1.4d401f" width="320" height="180"/>
      <Representation id="360657" bandwidth="360657" codecs="avc1.4d401f" width="320" height="180"/>
      <Representation id="564629" bandwidth="564629" codecs="avc1.4d401f" width="512" height="288"/>
      <Representation id="819549" bandwidth="819549" codecs="avc1.4d401f" width="640" height="360"/>
      <Representation id="1278615" bandwidth="1278615" codecs="avc1.4d401f" width="768" height="432"/>
      <Representation id="1849600" bandwidth="1849600" codecs="avc1.4d401f" width="1024" height="576"/>
      <Representation id="2849600" bandwidth="2849600" codecs="avc1.4d4020" width="1280" height="720"/>
      <Representation id="4299600" bandwidth="4299600" codecs="avc1.640028" width="1280" height="720"/>
    </AdaptationSet>
```

**Comment by ojw28** [comment]
The issue is that FragmentedMp4Extractor assumes samples are packed tightly into their MDAT boxes. In this particular stream, it looks like each MDAT box starts with 8 bytes of non-sample data. We try and read this data as the start of the first sample, which leads to the failure.

We do have a patch internally that handles this case, but we didn't ever submit it because we were unsure whether it was worth supporting, given it's pretty messy to do so. This is the second sample we've seen that adds extra data into the MDAT boxes, so I guess we should probably clean the patch up and get it supported.

Out of interest, do you know what those 8 extra bytes at the start of each MDAT box are for? Is there a legitimate reason for them?

**Comment by markniebur** [comment]
According to the mpeg4 base media file format spec, 14496-12:2012 section 4.2, if the size field of a box is given as 1, then the first 8 bytes are used for the size and then data continues after that.  Since the mdat box may contain data that is larger than 4GB, rather than deal with that on a case by case basis, I am just using the largesize field unconditionally.  This is OK according to the spec.

**Comment by ojw28** [comment]
Ah right, so this is actually a slightly different issue. Thanks for the info. Yes, we should handle that case. 

Note however that in fragmented mp4 you probably have a new mdat box for every segment anyway, and they're not nested inside any other parent boxes, so I don't think it's ever going to be the case that boxes get remotely near to being 4GB. In other words, you can probably just safely not use largesize at all.

**Comment by ojw28** [comment]
And if the above is correct, you explicitly are a little better off not using largesize (because it wastes a small number of bytes for every box, and because in general it's a good idea to "do what everyone else does").

**Comment by markniebur** [comment]
I was able to verify that when I don't use the largesize, exoplayer works correctly.  Thanks for your help!

**Comment by ojw28** [comment]
largesize should also now work on the dev branch (although I'd recommend not using it).
