### ISSUE TITLE
Exoplayer development music player does not support Ape format

### ISSUE THREAD

**Issue by ZTMIDGO** [google/ExoPlayer#6520]
I recently used Exoplayer to develop a music player, but I found that Exoplaye does not support the Ape format. Even though I have extended Ffmpeg, flac, and opus to Exoplayer, I think Exoplayer should support Ape. MediaPlayer supports more audio formats than Exoplayer.

**Comment by andrewlewis** [comment]
#3751 tracks adding support for APE.

> MediaPlayer supports more audio formats than Exoplayer.

If you are thinking of other formats apart from APE, it would be nice if you could list the ones you're interested in having support for in ExoPlayer. Thanks.

**Comment by ZTMIDGO** [comment]
> [＃3751](https://github.com/google/ExoPlayer/issues/3751)跟踪添加对APE的支持。
> 
> > MediaPlayer比Exoplayer支持更多的音频格式。
> 
> 如果您正在考虑除APE之外的其他格式，那么可以列出对ExoPlayer的支持感兴趣的格式。谢谢。
Thank, can you give me some alternatives?

**Comment by ZTMIDGO** [comment]
> #3751 tracks adding support for APE.
> 
> > MediaPlayer supports more audio formats than Exoplayer.
> 
> If you are thinking of other formats apart from APE, it would be nice if you could list the ones you're interested in having support for in ExoPlayer. Thanks.

Thank, I check if there are other alternatives
