### ISSUE TITLE
androidx.media2 usage with ExoPlayer

### ISSUE THREAD

**Issue by jakoss** [google/ExoPlayer#6521]
### Searched documentation and issues
I searched in issues and in code directly

### Question
I'm trying to use some library (that is using `androidx.media2`) within existing app based on ExoPlayer and it's integration with `androidx.legacy:legacy-support-v4`. 

In [media 2 documentation](https://developer.android.com/jetpack/androidx/releases/media2) there is a statement `Media2 is the next generation of following Media APIs: MediaSession, MediaController, MediaBrowser, MediaBrowserService, VideoView, and MediaControlView.`. Is there any particular reason why ExoPlayer isn't depending on it right now? Is there any plan to migrate APIs. I imagine that such change might require library users to migrate too, hence the question.

**Comment by andrewlewis** [comment]
We plan to publish an extension that connects media2's `SessionPlayer` interface with ExoPlayer, allowing you to use ExoPlayer with a media2 `MediaSession` and media2 widgets. I'll mark this as an enhancement for now so you can track the status of that.

As far as other existing library modules are concerned, in the short term we don't have plans to make them depend on media2. Over the coming year we are looking into ways to have closer integration between ExoPlayer and these other media APIs.

**Comment by toXel** [comment]
Are there any updates on this?

**Comment by andrewlewis** [comment]
We'll update this issue when the media2 extension is published.

**Comment by PaulWoitaschek** [comment]
@andrewlewis It seems you can close this issue now and update the issue that the media2 extension was published. :tada:

**Comment by andrewlewis** [comment]
Thanks. Just for reference, 02f8cdf1d9c277a38377bacd5f9e2b3cf7ca8041 was the first commit related to this.
