### ISSUE TITLE
Buffering for radio

### ISSUE THREAD

**Issue by stifutkin** [google/ExoPlayer#6522]
The server allows to request only the last 5 seconds of the stream. How can I create a 30s buffer even if the user has to wait 25s before starting playback?

**Comment by fgl27** [comment]
you can technically override [DefaultLoadControl setBufferDurationsMs](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/DefaultLoadControl.Builder.html#setBufferDurationsMs-int-int-int-int-)

example
https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/trackselection/BufferSizeAdaptationBuilder.java#L245

and set **minBufferMs** and **bufferForPlaybackMs** to a minimum of 30000

remember maxBufferMs >= minBufferMs

check https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/DefaultLoadControl.html#DEFAULT_MIN_BUFFER_MS

for more detailed description of it value

Maybe you have a use for it, but I think 5s is more than enough for most playback, you can even set a lower value for **bufferForPlaybackMs**  let say 1s and let **minBufferMs** be 5s the playback will start after 1s has be buffered (not the time that will take but the size in time of the buffer) and the buffer will fill up with up to 5s, but you can't do that for the 30s if 30s isn't available you must set as I wrote before and wait 25s buffering.

use [player.getTotalBufferedDuration()](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/Player.html#getTotalBufferedDuration--) to see how long in time is the buffer

**Comment by christosts** [comment]
Hi @stifutkin 

The response of @fgl27 is in the correct direction. Please try that and let me know if it worked. If you still need assistance, please provide me with an example of a manifest that 

> allows to request only the last 5 seconds of the stream

so that I can test and respond with more details.
