### ISSUE TITLE
IMA Extension Ads Not Working 

### ISSUE THREAD

**Issue by ArcherEmiya05** [google/ExoPlayer#6526]
## [REQUIRED] Issue description
The VAST ads from IMA SDK Google page sample are working fine, but after a few weeks or months the player no longer finish the buffering. No ads no actual video is playing. The suspicious part here is when I clear the data or cache then uninstall and reinstall the app it works again even with CORS message on logs. What I speculate is the IMA SDK is being cache or having conflict with cache after prolong use. This happens to me on 3 devices during 2 separate app development. I see no error logs on both 3 so I have no stacktrace to show, it just really never stop buffering.

### [REQUIRED] Reproduction steps
Play any VAST or VPAID ads with Exoplayer using IMA SDK Extension library on Android device frequently and for a long period of time.

### [REQUIRED] Link to test content
https://developers.google.com/interactive-media-ads/docs/sdks/html5/tags

### [REQUIRED] A full bug report captured from the device
Still work before even with this message.
Receiving "Access to XMLHttpRequest at from origin 'https://imasdk.googleapis.com' has been blocked by CORS policy: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'.

### [REQUIRED] Version of ExoPlayer being used
2.9.6

### [REQUIRED] Device(s) and version(s) of Android being used
LG K10 K430dsy, Huawei Nova 3i, Sony Xperia XA1

**Comment by andrewlewis** [comment]
Could you elaborate on "What I speculate is the IMA SDK is being cache or having conflict with cache after prolong use.", and provide some more detail on the specific steps we'd need to take to reproduce the issue? I think it's likely that the IMA SDK JavaScript is getting cached but I'm not sure how this causes playback to get stuck buffering. Thanks.

**Comment by ArcherEmiya05** [comment]
All I really got is non stop buffering when a VAST ad was used for a long period of time. Meaning it works fine if I clear data or cache the app or uninstall then reinstall which is really suspicious to think. If the ad will not work then that's it but if the ad works fine then after a long period of time stops working then that is something really disturbing. Even the sample Single Skippable Inline https://developers.google.com/interactive-media-ads/docs/sdks/html5/tags behaves the same.

[log.txt](https://github.com/google/ExoPlayer/files/3727424/log.txt)

**Comment by ArcherEmiya05** [comment]
`
I/ExoPlayerImpl: Init 2644d68 [ExoPlayerLib/2.9.6] [m253, LG-K430, LGE, 23]
I/AudioManagerEx: AudioManagerEx created
I/WebViewFactory: Loading com.google.android.webview version 73.0.3683.90 (code 368309000)
I/cr_LibraryLoader: Time to load native libraries: 1 ms (timestamps 581-582)
I/chromium: [INFO:library_loader_hooks.cc(50)] Chromium logging enabled: level = 0, default verbosity = 0
I/cr_LibraryLoader: Expected native library version number "73.0.3683.90", actual native library version number "73.0.3683.90"
I/cr_BrowserStartup: Initializing chromium process, singleProcess=true
D/ConnectivityManager.CallbackHandler: CM callback handler got msg 524290
D/ConnectivityManager.CallbackHandler: CM callback handler got msg 524290
E/libEGL: validate_display:255 error 3008 (EGL_BAD_DISPLAY)
W/cr_media: Requires BLUETOOTH permission
V/AudioManager: requestAudioFocus() Request Package = com.bitwise.manilaaidandsafetyapp
    requestAudioFocus() flags = 0 Request Package = com.bitwise.manilaaidandsafetyapp
D/ConnectivityManager.CallbackHandler: CM callback handler got msg 524290
D/ConnectivityManager.CallbackHandler: CM callback handler got msg 524290
W/AudioCapabilities: Unsupported mime audio/x-lg-flac
W/AudioCapabilities: Unsupported mime audio/adpcm
W/AudioCapabilities: Unsupported mime audio/g726
W/AudioCapabilities: Unsupported mime audio/mp4a-adts-1seg
W/AudioCapabilities: Unsupported mime audio/mp4a-latm-1seg
W/AudioCapabilities: Unsupported mime audio/lg-wma-voice
W/AudioCapabilities: Unsupported mime audio/x-lg-ms-wma
W/VideoCapabilities: Unsupported mime video/theora
W/VideoCapabilities: Unsupported mime video/mjpg
W/AudioCapabilities: Unsupported mime audio/x-adpcm-ms
W/AudioCapabilities: Unsupported mime audio/x-adpcm-dvi-ima
W/VideoCapabilities: Unrecognized profile/level 32768/2 for video/mp4v-es
W/VideoCapabilities: Unsupported mime video/xvid
I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
W/cr_MediaCodecUtil: Codec OMX.MTK.VIDEO.ENCODER.AVC is disabled due to SDK version 23
    HW encoder for video/avc is not available on this device.
I/art: Background partial concurrent mark sweep GC freed 39686(1838KB) AllocSpace objects, 11(13MB) LOS objects, 31% free, 34MB/50MB, paused 2.507ms total 107.378ms
`

So why it is stuck at loading and no longer proceed to play the actual video. It was really good to have IMA SDK extension for the Exoplayer but it really seems to be unstable and it has a huge impact in production.

**Comment by andrewlewis** [comment]
The logging in your previous comment looks okay (I don't think it indicates a problem).

I haven't heard about problems with the IMA SDK after a long period of use. One thing that might help track down what's going on is if you could set `ImaAdsLoader.DEBUG` to true then replicate the issue where playback gets stuck, run `adb bugreport` and send us the resulting bug report at `dev.exoplayer@gmail.com`. Beyond that I'm not sure there's anything else we can suggest here.
