### ISSUE TITLE
can't play mp4    (Unexpected exception loading stream)

### ISSUE THREAD

**Issue by imfondof** [google/ExoPlayer#6532]
exoplayer: 
2.7.0
 
url:   
http://filesystem1.bbtree.com/2019/10/11/cms/5673cc33-eeb8-440d-aeae-f30900b7b0fe.mp4

error:
 E/LoadTask: Unexpected exception loading stream
    java.lang.IllegalArgumentException
        at com.google.android.exoplayer2.util.Assertions.checkArgument(Assertions.java:37)
        at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseStbl(AtomParsers.java:264)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.processMoovAtom(Mp4Extractor.java:408)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.processAtomEnded(Mp4Extractor.java:364)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:355)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:186)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:853)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:308)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)

**Comment by imfondof** [comment]
can play in google and mediaplayer, but can't paly in exoplayer

**Comment by ashish-dhiman** [comment]
I added  android:usesCleartextTraffic="true" inside application tag in manifest. I was getting : Android 8: Cleartext HTTP traffic not permitted. Works in my exoplayer sample.

![image](https://user-images.githubusercontent.com/38856909/66650917-5f7b5300-ec4f-11e9-88ed-fcbab058c16f.png)

**Comment by imfondof** [comment]
thank you ! i will try

**Comment by ashish-dhiman** [comment]
public class MainActivity extends AppCompatActivity implements EventListener{

    private SimpleExoPlayer player;
    private DefaultDataSourceFactory defaultDataSourceFactory;
    private MediaSource mediaSource;
    private SimpleExoPlayerView playerView;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        playerView=findViewById(R.id.playerView);
        try {
            BandwidthMeter bandwidthMeter= new DefaultBandwidthMeter();
            TrackSelector trackSelector= new DefaultTrackSelector(new AdaptiveTrackSelection.Factory(bandwidthMeter));
            player = ExoPlayerFactory.newSimpleInstance(this, trackSelector);
            Uri video= Uri.parse(Constants.FILE_LINK);
            DefaultHttpDataSourceFactory dataSourceFactory=new DefaultHttpDataSourceFactory("exoplayervideo");
            ExtractorsFactory extractorsFactory= new DefaultExtractorsFactory();
            MediaSource mediaSource=new ExtractorMediaSource(video, dataSourceFactory,extractorsFactory,null,null);
            playerView.setPlayer(player);
            player.prepare(mediaSource);
            player.setPlayWhenReady(true);
        }catch (Exception e){

        }
      }
    }

**Comment by Imfondof** [comment]
I use the same code in my project,
but it can't work , and Report the same mistake
do you have another config?

**Comment by imfondof** [comment]
> ```
> public class MainActivity extends AppCompatActivity implements EventListener{
> 
> private SimpleExoPlayer player;
> private DefaultDataSourceFactory defaultDataSourceFactory;
> private MediaSource mediaSource;
> private SimpleExoPlayerView playerView;
> 
> @Override
> protected void onCreate(Bundle savedInstanceState) {
>     super.onCreate(savedInstanceState);
>     setContentView(R.layout.activity_main);
>     playerView=findViewById(R.id.playerView);
>     try {
>         BandwidthMeter bandwidthMeter= new DefaultBandwidthMeter();
>         TrackSelector trackSelector= new DefaultTrackSelector(new AdaptiveTrackSelection.Factory(bandwidthMeter));
>         player = ExoPlayerFactory.newSimpleInstance(this, trackSelector);
>         Uri video= Uri.parse(Constants.FILE_LINK);
>         DefaultHttpDataSourceFactory dataSourceFactory=new DefaultHttpDataSourceFactory("exoplayervideo");
>         ExtractorsFactory extractorsFactory= new DefaultExtractorsFactory();
>         MediaSource mediaSource=new ExtractorMediaSource(video, dataSourceFactory,extractorsFactory,null,null);
>         playerView.setPlayer(player);
>         player.prepare(mediaSource);
>         player.setPlayWhenReady(true);
>     }catch (Exception e){
> 
>     }
>   }
> }
> ```

I use the same code in my project,
but it can't work , and Report the same mistake
do you have another config?

the problem is that    **the video can't play with 2.7.0exoplayer**
here is my code :    https://github.com/Imfondof/exospecialdemo

**Comment by imfondof** [comment]
to see [issues 6536](https://github.com/google/ExoPlayer/issues/6536)
