### ISSUE TITLE
UDP Multicast latency

### ISSUE THREAD

**Issue by tipoc123** [google/ExoPlayer#6534]
### [REQUIRED] Issue description
ExoPlayer slowly loads some multicast streams (more than 5 seconds to move from STATE_IDLE to STATE_READY).

### [REQUIRED] Reproduction steps
Try to play the multicast stream from a dump.

### [REQUIRED] Link to test content
Dump:
[dump.zip](https://github.com/google/ExoPlayer/files/3717942/dump.zip)
The command for broadcast:
multicat -uU dump.ts 224.10.10.10:1234

### [REQUIRED] A full bug report captured from the device
[bugreport.txt.zip](https://github.com/google/ExoPlayer/files/3717956/bugreport.txt.zip)

### [REQUIRED] Version of ExoPlayer being used
2.9.6

### [REQUIRED] Device(s) and version(s) of Android being used
Rockchip RK3229
Android 7.1.2

**Comment by Samrobbo** [comment]
Hi, 

I've assigned this to the relevant person, but in the meantime, have a look at #5128 , it may provide some information, as it appears to a similar issue.

**Comment by tipoc123** [comment]
> Hi,
> 
> I've assigned this to the relevant person, but in the meantime, have a look at #5128 , it may provide some information, as it appears to a similar issue.

No, default buffer is OK for us (DEFAULT_MAX_PACKET_SIZE = 2000 in UdpDataSource). We receive  packets with 1316 bytes size (1316 = 7 * 188).

**Comment by tipoc123** [comment]
We solved the problem by changing the UDP start buffer size from 2500 to 1000 ms. Code:
```
import static com.google.android.exoplayer2.DefaultLoadControl.DEFAULT_BUFFER_FOR_PLAYBACK_AFTER_REBUFFER_MS;
import static com.google.android.exoplayer2.DefaultLoadControl.DEFAULT_MAX_BUFFER_MS;
import static com.google.android.exoplayer2.DefaultLoadControl.DEFAULT_MIN_BUFFER_MS;

...

@C.ContentType int type = Util.inferContentType(uri, null);
LoadControl loadControl;
if (type == C.TYPE_OTHER && uri.getScheme().equals("udp")) {
    DefaultLoadControl.Builder builder = new DefaultLoadControl.Builder();
    int bufferForPlaybackMs = 1000;
    Log.d(TAG, "bufferForPlaybackMs="+bufferForPlaybackMs);
    builder.setBufferDurationsMs(DEFAULT_MIN_BUFFER_MS, DEFAULT_MAX_BUFFER_MS, bufferForPlaybackMs, DEFAULT_BUFFER_FOR_PLAYBACK_AFTER_REBUFFER_MS);
    loadControl = builder.createDefaultLoadControl();
} else {
    loadControl = new DefaultLoadControl();
}
player = ExoPlayerFactory.newSimpleInstance(context, renderersFactory, trackSelector, loadControl, drmSessionManager);

```
