### ISSUE TITLE
ExoPlayer jumps to local video end immediately

### ISSUE THREAD

**Issue by rickyManalo** [google/ExoPlayer#6539]
### [REQUIRED] Issue description
ExoPlayer plays just a few seconds of the end of a video or ends immediately even when it can play some of the local videos just fine.

### [REQUIRED] Reproduction steps
Let the video get downloaded. When the app plays a LOCAL FILE, that's when the issue appears. This is the github repo I made for testing. https://github.com/rickyManalo/streamerexoplayer

### [REQUIRED] Link to test content
Please create an API that returns the value that looks like the media.exolist.json that I provided. 

### [REQUIRED] A full bug report captured from the device
Added a adb bugreport.txt on my repo

### [REQUIRED] Version of ExoPlayer being used
com.google.android.exoplayer:exoplayer:2.9.1

### [REQUIRED] Device(s) and version(s) of Android being used
Jlinksz N960, Xiaomi Redmi Note 3

**Comment by Samrobbo** [comment]
Hi,

Unfortunately, all your test content is internally hosted, therefore we can not access it. This is because your test content is at `192.168.151.33`.

Please provide a link to your test content that can be accessed from a different network to the one hosting it.

- You mentioned that ExoPlayer can play local videos fine, but then you elaborate by saying the issue appears when the app plays a local file, please can you elaborate?
- Please can you clarify the versions of android being used.

**Comment by rickyManalo** [comment]
For the video content, you can use any video. Our internal network can't be accessed outside so I don't think I can provide a test content.

My app before uses DownloadManager to download the videos to the Downloads folder of a device. After the download finishes, I save the local path of video so I can use it for the URI of the video if I need to play it. Everything works fine back then, ExoPlayer plays every local video just fine. Now, I changed my code. I removed DownloadManager because it doesn't support LAN. Now, I used the code on my DownloadHelper to download the videos. That's when the issue appears. It seems like ExoPlayer doesn't want to play some of the videos or plays just a bit of the video's end(like about 6 seconds). And sometimes ExoPlayer just plays a video once then skips it the next time my app needs to play it or just skips everything. What happens when ExoPlayer skips a video is it enters STATE_BUFFERING then STATE_ENDED instantly.

Both devices are running Lollipop

Just added a logs of what happens to my app on the repo I shared. I promise I didn't edit it (except for the package name).

**Comment by rickyManalo** [comment]
Hi, I kinda found a fix to my issue. Before I play a video again, I call `exoplayer.seekTo(0)`. But it kinda got some issue of it's own. Because I called `seekTo()` before replacing the video, it plays a bit of the start of the previous video first then plays the next video after.

**Comment by Samrobbo** [comment]
Hi,

From your comment, it appears that the original issue is no longer a problem.

For this new problem, filling out a new issue detailing what is happening will be the best way for you to get assistance. Please include a reference back to this issue.

Closing as issue fixed.

**Comment by rickyManalo** [comment]
But it still wasn't fixed as far as I'm concerned. I haven't gotten any help from your team yet. What I just did is a silly excuse of a work-around. I don't even feel good about what I did.

**Comment by tonihei** [comment]
Based on the information you provided, it sounds as if you are calling `player.prepare` with `resetPosition=false`. That's potentially why it starts at an unexpected position (or ends immediately) and seeking to zero helps.

**Comment by rickyManalo** [comment]
Man, thanks @tonihei. It worked. After a week, finally got an answer without reasons about stuff not given to them.
