### ISSUE TITLE
seekTo(sameValue) yields frameJump +/-

### ISSUE THREAD

**Issue by Schizo** [google/ExoPlayer#654]
When i call ```mplayer.seekTo(1000);``` multiple times, it is not staying on the frame but is moving +1 Frame everytime i call it.

**Comment by almozavr** [comment]
The other concern I'm investigating is to how to achieve the same smooth (non-buffering?) seeking frame-by-frame as it happens when you `seekTo(player.getCurrentPosition())`?..

**Comment by ojw28** [comment]
As a related point, we're planning on making ```seekTo(player.getCurrentPosition())``` be a no-op (i.e. "do nothing").

**Comment by Schizo** [comment]
This should solve the problem.
