### ISSUE TITLE
HLS reevaluateBuffer

### ISSUE THREAD

**Issue by lifawei** [google/ExoPlayer#6540]
HlsSampleStreamWrapper.reevaluateBuffer()
 Util.removeRange(mediaChunks, chunkIndex, mediaChunks.size()); 
throw AudioTrack: Discontinuity detected [expected 55024000, got 15002666]

**Comment by Samrobbo** [comment]
Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md). If you're unable to share bug reports or test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Please also update this issue to indicate you’ve done this.
