### ISSUE TITLE
How to enable subtitles on dash stream?

### ISSUE THREAD

**Issue by luna-vulpo** [google/ExoPlayer#6541]
ExoPlayer 2.9.1
I run exoPlayer on AndroidTV with leanback support.

my configuration
```
ExoPlayerFactory.newSimpleInstance(
            context,
            DefaultRenderersFactory(context),
            trackSelector,
            DefaultLoadControl(),
            defaultDrmSessionManager
        )
```
and I switch tracks using below method:

```
    fun setTrack(model: FormatUiModel) {
        val newParams = trackSelector.buildUponParameters()

        when (model.formatType) {
            FormatUiModel.Type.VIDEO -> {
                newParams.setMaxVideoBitrate(model.format.bitrate)
                newParams.setMaxVideoSize(model.format.width, model.format.height)
            }
            FormatUiModel.Type.AUDIO -> {
                newParams.setPreferredAudioLanguage(model.format.language)
            }
            FormatUiModel.Type.TEXT -> {
                newParams.setRendererDisabled(C.TRACK_TYPE_VIDEO, false)
                newParams.setPreferredTextLanguage(model.format.language)
            }
        }
        trackSelector.parameters = newParams.build()
    }
```

it works fine for video and audio. But subtitles/text are not displaying but I can see that text track is selected.

All available tracks:

```
com.tv.uat D/ExoPlayerAdapter: getFormatsFromTrackGroups 0, 0 Format(video=1001000, null, video/mp4, video/avc, avc1.640028, 1001000, null, [1024, 576, 25.0], [-1, -1])
com.tv.uat D/ExoPlayerAdapter: getFormatsFromTrackGroups 0, 1 Format(video=2001000, null, video/mp4, video/avc, avc1.640028, 2001000, null, [1280, 720, 25.0], [-1, -1])
com.tv.uat D/ExoPlayerAdapter: getFormatsFromTrackGroups 0, 2 Format(video=5001000, null, video/mp4, video/avc, avc1.640028, 5001000, null, [1920, 1080, 25.0], [-1, -1])
com.tv.uat D/ExoPlayerAdapter: getFormatsFromTrackGroups 0, 0 Format(audio_eng=128000, null, audio/mp4, audio/mp4a-latm, mp4a.40.2, 128000, en, [-1, -1, -1.0], [2, 48000])
com.tv.uat D/ExoPlayerAdapter: getFormatsFromTrackGroups 1, 0 Format(audio_lav=128000, null, audio/mp4, audio/mp4a-latm, mp4a.40.2, 128000, lv, [-1, -1, -1.0], [2, 48000])
com.tv.uat D/ExoPlayerAdapter: getFormatsFromTrackGroups 2, 0 Format(audio_lit=128000, null, audio/mp4, audio/mp4a-latm, mp4a.40.2, 128000, lt, [-1, -1, -1.0], [2, 48000])
com.tv.uat D/ExoPlayerAdapter: getFormatsFromTrackGroups 0, 0 Format(textstream_est=1000, null, application/mp4, application/ttml+xml, stpp, 1000, et, [-1, -1, -1.0], [-1, -1])
com.tv.uat D/ExoPlayerAdapter: getFormatsFromTrackGroups 1, 0 Format(textstream_lav=1000, null, application/mp4, application/ttml+xml, stpp, 1000, lv, [-1, -1, -1.0], [-1, -1])
com.tv.uat D/ExoPlayerAdapter: getFormatsFromTrackGroups 2, 0 Format(textstream_rus=1000, null, application/mp4, application/ttml+xml, stpp, 1000, ru, [-1, -1, -1.0], [-1, -1])
```

Can someone shows how to implement selecting text tracks? Or point me to right doc.

**Comment by ojw28** [comment]
Provided there exists a track with language `model.format.language`, I think `setPreferredTextLanguage(model.format.language)` should be sufficient. I don't understand what the line of code above that is doing; it looks a bit like it shouldn't be there?

If that's not working, please provide sample media for us to reproduce.

**Comment by luna-vulpo** [comment]
firstly I did not have ```newParams.setRendererDisabled(C.TRACK_TYPE_VIDEO, false)```
but read here: https://stackoverflow.com/a/51787632/1461568
that it should help. But not help at all. 

Should I set or add something to enable rendering subtitle with exoplayer2?

(I will try to prepare such stream)

**Comment by ojw28** [comment]
I tried using this sample in our demo app:
https://dash.akamaized.net/dash264/CTA/imsc1/IT1-20171027_dash.mpd

And confirmed that the following was sufficient to enable the captions:
```
trackSelector.setParameters(
    trackSelector.buildUponParameters().setPreferredTextLanguage("en"));
```

This suggests there's either a problem with your media, or a problem with your application code. If you provide a test sample of media then we can check the former.

**Comment by luna-vulpo** [comment]
I was tried you sample and I don't see any subtitles. So now I'm sure that is on my app side error.

I use: ```DefaultRenderersFactory(context)``` is it render subtitles on screen by default? or I should pass TextView or similar  to enable to render subtitles?

**Comment by ojw28** [comment]
Are you using our `PlayerView` UI component?

It takes care of rendering the subtitles if you're using it. If you're not using it then you need to add something as a text output to the player (`player.addTextOutput`), which will receive the subtitles. You'll then need to render them. You can use `SubtitleView` for this, if you don't want to use the full `PlayerView. You can add a `SubtitleView` as a text output directly on the player.

**Comment by luna-vulpo** [comment]
nop. I use leanback for android tv. Very similar as in this example:
https://github.com/googlearchive/leanback-showcase

I will falow your advide. thx.
