### ISSUE TITLE
Crash occurred when exoplayer built locally is used along with another exo based player

### ISSUE THREAD

**Issue by krackjack234** [google/ExoPlayer#6543]
[REQUIRED] Question

We are trying to build a player based on exoplayer but with some custom modifications required by the client.

To do so, we have added exoplayer v2.9.6 code locally (without changing any code) as explained in exoplayer github link (https://github.com/google/ExoPlayer)

In our app, there are 2 players, both based on exo. One is a commercially available player which plays live video and another is our custom player which plays vod.

We then linked our custom player as a module dependency using local maven in the app

However when we invoke the player to play any vod content, we see a runtime crash

```
E AndroidRuntime: FATAL EXCEPTION: ExoPlayerImplInternal:Handler
E AndroidRuntime: Process: com.sonyliv.androidext, PID: 11064
E AndroidRuntime: java.lang.AbstractMethodError: abstract method "void com.google.android.exoplayer2.source.BaseMediaSource.prepareSourceInternal(com.google.android.exoplayer2.upstream.TransferListener)"
E AndroidRuntime: 	at com.google.android.exoplayer2.source.BaseMediaSource.prepareSource(BaseMediaSource.java:140)
E AndroidRuntime: 	at com.google.android.exoplayer2.ExoPlayerImplInternal.prepareInternal(ExoPlayerImplInternal.java:398)
E AndroidRuntime: 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:285)
E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:108)
10-14 15:34:16.861 11064 11546 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:216)
E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:65)
```

Is there a problem in this approach where 2 exo based players cannot be used at the same time, if one is build locally and the other is pointing to google's online repo?

Or do we need to ensure that the locally build exoplayer version is same as the online version used by the other player?

Any pointers are welcome.

**Comment by ojw28** [comment]
This is a bit of a tricky one, which arises from the fact we don't guarantee API stability.

* For now, if a library uses ExoPlayer, it should bundle the version that it wants directly inside its aar, and do so _with an modified/obfuscated package name_. This way multiple libraries using different versions of ExoPlayer can co-exist alongside one another, and with a version used by the app code directly, even if the APIs are incompatible. So you should ask whoever is providing the commercially available player that you're using to do this.
* The only other option you have currently is to ensure that both the library and your code use the same version of ExoPlayer, and (probably) that they pull it from the same place.

Longer term, we're looking at stabilizing parts of our API. We expose so much of the internals of the player (for extensibility reasons) that it's not viable to stabilize all of it, but we're looking into the possibility of stabilizing the higher level parts only. If and when we do this, a library will not be required to bundle and obfuscate the package name provided they only use the stabilized parts of the API surface.

**Comment by krackjack234** [comment]
Hi @ojw28, by "modified/obfuscated package name", do you mean all exoplayer classes have to be renamed to avoid namespace collision? 

Also in case both the versions are same, what you mean by "(probably) that they pull it from the same place" ?

**Comment by ojw28** [comment]
> Hi @ojw28, by "modified/obfuscated package name", do you mean all exoplayer classes have to be renamed to avoid namespace collision?

Yes. When the provider of the library produces their aar, they should include the ExoPlayer classes inside the aar with a different package name. This avoids collisions. I think it's probably fairly easy for a library developer to do this using proguard (or equivalent tool).

> Also in case both the versions are same, what you mean by "(probably) that they pull it from the same place"?

I'm less sure about this, but I was wondering what would happen in the case where you (i.e. app code) depend on ExoPlayer via gradle dependency, and the library bundles the same version of ExoPlayer directly (without obfuscation). This would be an example of the same source code coming from two different places. I'm not sure whether the compiler is clever enough to see they're identical and just throw one away. Perhaps it is, in which case it's not a problem.

**Comment by krackjack234** [comment]
Thanks @ojw28
