### ISSUE TITLE
MediaSessionConnector doesn't work at API 19

### ISSUE THREAD

**Issue by matheusbrandao** [google/ExoPlayer#6545]
I am trying to make the headset controls work in API 19 however unsuccessfully. I already added MediaButtonReceiver in the manifest, which made it possible to use MediaSession without crash.

However the controls by the handset still do not work. Any suggestion?

**Comment by marcbaechinger** [comment]
Prior to API 21 MediaButton events are not delivered to the MediaSession. 

Instead it is delivered as a key event (https://developer.android.com/guide/topics/media-apps/mediabuttons). In the demo app the key event arrives at the [dispatchKeyEvent](https://github.com/google/ExoPlayer/blob/release-v2/demos/main/src/main/java/com/google/android/exoplayer2/demo/PlayerActivity.java#L289) method which then delegates to the `PlayerView` which again delegates to `PlayerControlView` which finally calls `seekTo` accordingly.

If you are running a service (prior to API 21) you can create an intent filter and handle the MEDIA_BUTTON yourself ([details on how to do this](https://developer.android.com/reference/androidx/media/session/MediaButtonReceiver#service-handling-action_media_button)):

```
<service android:name="com.example.android.MyMediaPlaybackService" >
   <intent-filter>
     <action android:name="android.intent.action.MEDIA_BUTTON" />
   </intent-filter>
 </service>
```

More details can also be consulted in these documents: 

https://developer.android.com/guide/topics/media-apps/mediabuttons#mediabuttons-and-active-mediasessions
https://developer.android.com/reference/androidx/media/session/MediaButtonReceiver#service-handling-action_media_button
