### ISSUE TITLE
Custom Decoder Implement in Exoplayer

### ISSUE THREAD

**Issue by swastik52** [google/ExoPlayer#6547]
How to implement a custom decoder in Exoplayer v2
----------------------------------------------------------------------

I have an encrypted video URL and also have a native decoder code to decode the video.
How to use my native decoder code in Exoplayer.

**Comment by Samrobbo** [comment]
I would recommend looking into the existing extensions that wrap native decoders. 

For example [Flac decoders](https://github.com/google/ExoPlayer/tree/release-v2/extensions/flac/src)
