### ISSUE TITLE
Problem with playerNotificationManager.getCurrentLargeIcon in API 19

### ISSUE THREAD

**Issue by matheusbrandao** [google/ExoPlayer#6549]
As the image shows, trying to add a large icon to the playerNotificationManager, the app is showing a blue background.

Any suggestion?

![Screenshot_2019-10-15-14-50-27](https://user-images.githubusercontent.com/19668094/66857554-e8e79980-ef5d-11e9-83a4-9bec5b0351fb.png)

**Comment by marcbaechinger** [comment]
It appears to me the blue background is the default and the icon you are using has a transparent background.

Have you tried using an icon with an opaque background?

**Comment by matheusbrandao** [comment]
Yeah, I tried to use an icon with opaque background. However, it refers to the background color that I will have to set.

Is #1E2022 standard on API 19 devices?

**Comment by marcbaechinger** [comment]
I figure you need to use an opaque icon if you want to have another background than the blue default on KitKat. It's unfortunate but I think there is no way around it. 

To the best of my knowledge it works like this:

`NotificationCompat.Builder` has one setter only which takes a color: `setColor`. This color (let's assume I use red) is used as follows:

   a) without largeIcon and without a media session
         -> the icons of the action buttons are tinted in that color. The button icons are red.
   b) without largeIcon and (with a media session or with `setColorized(true)`)
         -> the notification gets that color as the background. The notification is red.
   c) with largeIcon and with a mediaSession
         -> the background color of the notification is taken from the largeIcon

The above is only true for recent API levels. For the KitKat case you are referring to the color of the notification does not have an effect. You need to use a large icon with a opaque background. Using an opaque large icon makes sense for other API levels as well (see above). The notification will nicely be colored to blend with the large icon. 

Please let me know if I miss something. If there is a way to set that background behind the transparent `largeIcon`on KitKat I'm happy to add this to our `PlayerNotificationManager`. I don't think it's possible in other ways than the largeIcon itself I'm afraid.

**Comment by marcbaechinger** [comment]
Closing for now as I think this can be done with opaque icons for that API level. Please reopen if you think I'm wrong.
