### ISSUE TITLE
createMessage(PlayerMessage.Target target)  gives multiple callback.

### ISSUE THREAD

**Issue by chitrang200889** [google/ExoPlayer#6550]
Our requirement is to have a callback at different time positions of the video duration. 

Below is our method to set createMessage() with the callback.

        fun addCuePosition(cuePositionInMillisecond: Int) {
            simpleExoPlayer
                    .createMessage(PlayerMessage.Target { messageType, payload ->
                        HDialogue.log("payload = $payload")
                    })
                    .setPosition(cuePositionInMillisecond.toLong())
                    .setPayload(cuePositionInMillisecond)
                    .setDeleteAfterDelivery(false)
                    .send()
        }

However, 
1) Once Player is prepared 
2) all the positions are set 
3) then we call simpleExoPlayer.seekTo(position.toLong()), here position is one of the same exact values which we set in create messages. 
Then it gives continuous multiple callbacks for PlayerMessage.Target, even before the video starts playing and also while it is playing.

Note:
I am new to ExoPlayer2, and we are planning to replace our existing media player https://github.com/protyposis/MediaPlayer-Extended with ExoPlayer. So we are looking for similar feature addCue, removeCue, setOnCueListener as in that library. 

Let us know if createMessage is not suitable for this and there is another method we can use instead. We referred https://github.com/google/ExoPlayer/issues/2189 and https://github.com/google/ExoPlayer/issues/5851

**Comment by marcbaechinger** [comment]
I would say that using createMessage is the right thing for this use case. That works for me when trying this out:

```
int positionMs = 30_000;
player.createMessage((messageType, payload)
         -> Log.d("player-message", payload.toString()))
     .setPosition(positionMs)
     .setPayload("payload 1")
     .send();
player.seekTo(positionMs);
player.prepare(mediaSource, false, false);
```

This gives me the output below when using EventLogger:

```
2019-10-16 11:10:34.183 13528-13528/com.google.android.exoplayer2.demo I/ExoPlayerImpl: Init bfe450d [ExoPlayerLib/2.10.6] [sailfish, Pixel, Google, 28]
2019-10-16 11:10:34.213 13528-13528/com.google.android.exoplayer2.demo D/EventLogger: seekStarted [0.01, 0.00, window=0]
2019-10-16 11:10:34.214 13528-13528/com.google.android.exoplayer2.demo D/EventLogger: positionDiscontinuity [0.01, 30.00, window=0, SEEK]
2019-10-16 11:10:34.218 13528-13528/com.google.android.exoplayer2.demo D/EventLogger: state [0.01, 30.00, window=0, true, BUFFERING]
2019-10-16 11:10:34.253 13528-13739/com.google.android.exoplayer2.demo D/player-message: payload 1
2019-10-16 11:10:34.278 13528-13528/com.google.android.exoplayer2.demo D/EventLogger: surfaceSize [0.07, 30.00, window=0, 1080, 1695]
```

I seek to the given position and the message is sent once at the correct time. This works as expected for me. 

> even before the video starts playing

I think it is expected that the message is sent at the moment when the position defined is reached. There is no guarantee that this is only fired when in STATE_READY. So receiving the message while in STATE_BUFFERING sounds ok to me in case you are seeking to this position.

**Comment by marcbaechinger** [comment]
Marking as a bug as setting 

```
.setDeleteAfterDelivery(false)
```

produces the continuous delivery of the message while the player is on the same position in BUFFERING_STATE.

**Comment by tonihei** [comment]
I think this is triggered by our special handling for the start position. In all other cases, we only trigger an  event when the requested time actually passed (and not when it stays constant).
