### ISSUE TITLE
Possible memory leak on SampleQueue AllocationNode

### ISSUE THREAD

**Issue by pnobbe** [google/ExoPlayer#6553]
### Searched documentation and issues
https://github.com/google/ExoPlayer/issues/5151 
https://github.com/google/ExoPlayer/issues/4539

Reopening this already discussed issue as I previous issues were closed due to insufficient evidence.

### Question

I am currently using ExoPlayer within a Fragment. A collection of these Fragments is displayed using ViewPager2 so the user can swipe between videos. Every time I swipe between two pre-existing Fragments the memory is increased even though there are seemingly no new instances being created on my end. Am I using the player incorrectly or is there a possible memory leak? Maybe something internal isn't reusing instances correctly?

Screenshot from Android profiler showing the ever increasing memory:
![image](https://user-images.githubusercontent.com/8037254/66908949-3d495280-f00c-11e9-9292-59ebbaef262e.png)

![image](https://user-images.githubusercontent.com/8037254/66909010-55b96d00-f00c-11e9-9484-fa3a6d3a1483.png)
It seems that `SampleQueue` from `exoplayer2.source` is occupying a majority of the memory here.

The code from my Fragment and the ViewPager:

**Fragment**:
```
class VideoFragment : Fragment() {
        private lateinit var videoView: VideoView
        private lateinit var exoPlayer: ExoPlayer
        private lateinit var dataSourceFactory: DefaultDataSourceFactory
        private lateinit var videoSourceFactory: ProgressiveMediaSource.Factory
        private lateinit var uri: Uri
        private lateinit var videoSource: ProgressiveMediaSource

        override fun onCreate(savedInstanceState: Bundle?) {
            super.onCreate(savedInstanceState)
            exoPlayer = ExoPlayerFactory.newSimpleInstance(this.context)
            dataSourceFactory = DefaultDataSourceFactory(this.context, Util.getUserAgent(this.context, "Swabbr"))
            videoSourceFactory = ProgressiveMediaSource.Factory(dataSourceFactory)
            uri = Uri.parse(Video.fromBundle(arguments!!).uri)
            videoSource = videoSourceFactory.createMediaSource(uri)
        }

        override fun onCreateView(
            inflater: LayoutInflater,
            container: ViewGroup?,
            savedInstanceState: Bundle?
        ): View? {
            videoView = VideoView(inflater, container)
            videoView.bind(exoPlayer)

            return videoView.view
        }

        override fun onResume() {
            super.onResume()
            exoPlayer.prepare(videoSource, true, false)
            exoPlayer.playWhenReady = true
        }

        override fun onPause() {
            super.onPause()
            exoPlayer.playWhenReady = false
        }

        companion object {
            fun create(video: Video): VideoFragment {
                val fragment = VideoFragment()
                fragment.arguments = video.toBundle()
                return fragment
            }
        }
    }
```

**Activity:**
```
class VlogActivity : AppCompatActivity() {

    private val vm: VideoViewModel by viewModel()
    private val vlogIds by lazy { intent.getStringArrayListExtra(SampleNavigation.VLOG_ID_KEYS) }
    private lateinit var vp: ViewPager2
    private var videos = listOf<VideoItem>()

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_view_video)

        if (savedInstanceState == null) {
            vm.get(videoIds, refresh = false)
        }

        vp = viewPager

        vp.adapter = object : FragmentStateAdapter(this) {
            override fun createFragment(position: Int): Fragment = VideoFragment.create(Video(videos[position].videoId))

            override fun getItemCount(): Int = videos.size
        }
        
        vm.videos.observe(this, Observer { update(it) })
    }

    private fun update(resource: Resource<List<VideoItem>>?) = resource?.data?.let {
        videos = it
        vp.adapter?.notifyDataSetChanged()
    }
}
```

Short GIF of what I'm doing in the app to trigger this behaviour:

![CbhR4CV](https://user-images.githubusercontent.com/8037254/66910091-37547100-f00e-11e9-95c4-f34906e2a5f7.gif)

**Comment by ojw28** [comment]
I think `SampleQueue` (and the Java heap in general) is accounted for in the "Java" part of the graph, where-as the problem is the "others" part. If this is when using the emulator, then it's probably this emulator specific issue: https://issuetracker.google.com/142528714

**Comment by pnobbe** [comment]
> I think `SampleQueue` (and the Java heap in general) is accounted for in the "Java" part of the graph, where-as the problem is the "others" part. If this is when using the emulator, then it's probably this emulator specific issue: https://issuetracker.google.com/142528714

I think you may be correct. I just tried replicating the issue on my phone and this was the result

![image](https://user-images.githubusercontent.com/8037254/66911374-acc14100-f010-11e9-8e48-c4e108c3ed95.png)

Looks much better. Guess I'm going to have to develop using my phone instead of the emulator then.

**Comment by ojw28** [comment]
Yeah, it's quite unfortunate. I'd suggest following the issue mentioned above to track when it's fixed!
