### ISSUE TITLE
On which class NAL Unit is read from mp4 file and render it? 

### ISSUE THREAD

**Issue by imbichitra** [google/ExoPlayer#6554]
On which class NAL Unit is read from mp4 file and render it?
-------------------------------------------------------------------------
I have an encrypted stream that i want to play with exoplayer but the problem is that exoplayer can't play the encrypted video file directly so if i got the position where the binary data is read from the stream then in that place i introduce my own decryption algorithm after decryption then the data is handover to the renders. Thanks in advance

**Comment by jzhoubupt** [comment]
I'm afraid your question is not clear enough for people to help you.
Depends on your stream format, how it is being encrypted, if it is in HLS,or DASH, or a local file, or online mp4 the area to introduce your own decryption algorithm  is quite different.

Just share what i knows: there is class Aes128DataSource in the HLS module which use javax.crypto.Cipher to decrypt AES-128 encrypted stream per HLS segment. You can see how  Aes128DataSource is integrated in HLS module. From there depends on your stream format you can find the right place to insert your own decryption algorithm.

**Comment by imbichitra** [comment]
Actually i have video file with 2 streams first one is encrypted video file(MP4) and second one is normal audio data, and i want to decrypt the video file and handover the decrypted video to the renderer.

**Comment by Samrobbo** [comment]
Hi,

If you have not yet looked into existing resources, our website with information can be found [here](https://exoplayer.dev), with our [Javadoc here](https://exoplayer.dev/doc/reference/).

If you've looked into these things, please can you fill out the question issue template, as shown [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/question.md). This will give us the necessary information and understanding to be able to help.

**Comment by imbichitra** [comment]
As discussed above https://github.com/google/ExoPlayer/issues/6554#issuecomment-543118468 i implement my own AES algorithm that's work fine but the problem is when i drag the seek bar to  forward the video for 10 second or press a button for backward the video 10 second it show below Error (The whole file is AEC encrypted along with header)
```
com.google.android.exoplayer2.ParserException: Invalid NAL length
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readSample(Mp4Extractor.java:554)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:201)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:962)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by Samrobbo** [comment]
Hi,

If possible, can we have a lot more information on what is happening.

We need information about what media you are using, what code is causing the problem etc. 

Please provide complete information as requested [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md). If you're unable to share bug reports or test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Please also update this issue to indicate you’ve done this.

Until you give us the necessary information as suggested in the [bug template](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md), we will not be able to help.

**Comment by Samrobbo** [comment]
Hi

To allow for seeking when using your own decryption algorithm, you need to support random access. After digging into this deeper, I believe your decryption algorithm may not account for this. Looking into [AesFlushingCipher](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/upstream/crypto/AesFlushingCipher.html) may assist your understanding. 

The main reason I'm assuming this is the case, is because most AES decryption algorithms rely on the previous block to decrypt the next one. Our exisiting solution uses CTR to avoid this.

If your algorithm does support random access, you may want to look into the specifics of handling access to a point that may be part way through a block of encrypted data.
