### ISSUE TITLE
AdsLoader.setPlayer crash

### ISSUE THREAD

**Issue by ArcherEmiya05** [google/ExoPlayer#6555]
### [REQUIRED] Searched documentation and issues
#5476 This is the only issue that I saw and no other SO question.

### [REQUIRED] Question
Is this issue already fix because I am still currently receiving some crash report on certain device. 

### A full bug report captured from the device
Fatal Exception: java.lang.NullPointerException: Set player using adsLoader.setPlayer before preparing the player.

### Link to test content
https://github.com/google/ExoPlayer/issues/5476

**Comment by Samrobbo** [comment]
Hi,

Can I get some more information please? In particular: 

- the device & version of Android.
- the exact version of ExoPlayer you are using.
- A full bug report, as mentioned [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md).
- The steps to reproduce, and how reproducible you found it to be.

**Comment by ArcherEmiya05** [comment]
- OPPO CPH1853 Android 8.1.0
- v2.9.6

`Fatal Exception: java.lang.NullPointerException: Set player using adsLoader.setPlayer before preparing the player.
       at c.h.b.b.y0.e.a(Assertions.java:5)
       at c.h.b.b.p0.a.a.a(ImaAdsLoader.java:25)
       at c.h.b.b.u0.j0.h.a(AdsMediaSource.java:10)
       at c.h.b.b.u0.j0.c.run(:4)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:200)
       at android.app.ActivityThread.main(ActivityThread.java:6956)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:836)`

- No idea since it was came from a crash report @Samrobbo

**Comment by andrewlewis** [comment]
I'm not aware of any current issues with this API. You do need to call `ImaAdsloader.setPlayer` before preparing the player instance that's using the loader via its `AdsMediaSource`, as indicated by the error message. #5476 is about fixing the IMA demo app to do this as expected, rather than an issue with the library.

**Comment by ArcherEmiya05** [comment]
> 
> 
> I'm not aware of any current issues with this API. You do need to call `ImaAdsloader.setPlayer` before preparing the player instance that's using the loader via its `AdsMediaSource`, as indicated by the error message. #5476 is about fixing the IMA demo app to do this as expected, rather than an issue with the library.

So what exactly the issue with this I am calling it like this.

`if (adsLoader == null)
                adsLoader = new ImaAdsLoader(this.context, adsUri);`

            adsMediaSource = new AdsMediaSource(mediaSourceBuilder.getMediaSource(), mediaSourceBuilder.getDataSourceFactory(), adsLoader, playerView);

            playerView.setPlayer(player);
            adsLoader.setPlayer(player);

            player.setPlayWhenReady(true);
            player.setVolume(this.volume);
            player.addListener(eventListener);
            player.seekTo(0, position);
            player.setAudioAttributes(audioAttributes, true);
            player.prepare(adsMediaSource, false, false);`

My concern is that, this only happens on particular device at particular time. Is there something wrong with the flow of execution?

**Comment by ArcherEmiya05** [comment]
`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.app, PID: 1009
    java.lang.NullPointerException: Set player using adsLoader.setPlayer before preparing the player.
        at c.h.b.b.y0.e.a(Assertions.java:130)
        at c.h.b.b.p0.a.a.a(ImaAdsLoader.java:587)
        at c.h.b.b.u0.j0.h.a(AdsMediaSource.java:220)
        at c.h.b.b.u0.j0.c.run(lambda)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5530)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:733)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:623)
        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)`

Tested it on my own and still getting this error when I tried to stop the player before it could start buffering please help. The worst part is that I can't tell what line on my code starts this error all I can do is to reproduce the scenario on my app in which not happening before.

**Comment by ArcherEmiya05** [comment]
Okay gonna need to fix this one! I review the `ImaAdsLoader` class and at the line **587** there is the **Assertion checkNotNull on a player** so what I did is removed the `adsLoader.setPlayer(null)` in my `release()` function. While this remove the crashing completely I wonder why this `adsLoader.setPlayer(null)` is still included in the demo app `PlayerManager` class if calling this will cause the Assertion to be triggered. I think you should test the IMA demo app on your own and try to open and close repeatedly and immediately to check whether there is a similar vulnerability crashing result like what is in this issue report. This is how I always test my app by opening and closing a view immediately to always check its stability despite of having a lot of network connection.

**Comment by Samrobbo** [comment]
Hi ArcherEmiya05, 

Have you verified whether using the newest version of ExoPlayer fixes this problem?
