### ISSUE TITLE
how do best partice make Music Player in Service with updatable UI ?

### ISSUE THREAD

**Issue by Hendriyawan** [google/ExoPlayer#6558]
how do best partice make Music Player in Service with updatable UI ?

**Comment by Samrobbo** [comment]
Hi,

It's quite unclear what you are asking, as you have not followed the question issue template [found here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/question.md).

However, I advise you go to [the exoplayer site](https://exoplayer.dev), where there is plenty of information about making a music player. In particular, [this page](https://exoplayer.dev/troubleshooting.html#how-do-i-keep-audio-playing-when-my-app-is-backgrounded) talks about using a Service.
