### ISSUE TITLE
Exoplayer cast implementation working on July 2019 but not working this month (October 2019) without changing any code, someone knows what happened?

### ISSUE THREAD

**Issue by ChannVincent** [google/ExoPlayer#6560]
I have implemented exoplayer with exoplayer cast extension in july 2019 and everything worked fine in august 2019 for my clients :
https://github.com/google/ExoPlayer/tree/release-v2
https://github.com/google/ExoPlayer/tree/release-v2/extensions/

    dependencies {
      implementation 'com.google.android.exoplayer:exoplayer-dash:2.9.6'
      implementation 'com.google.android.exoplayer:extension-cast:2.9.6'
    }
But suddenly, I have tested it this month (october 2019) on my chromecast and it doesn't work anymore.
Exoplayer still play video but it doesn't detect any chromecast.
My chromecast still works with Youtube cast or Netflix cast.

My code hasn't changed since august.
Someone has experience the same thing or has a clue of what is going on ?

**Comment by AquilesCanta** [comment]
Strange... Would you kindly try the dev version, just to check?

Can you check which receiver app id you are using?

**Comment by AquilesCanta** [comment]
@anjaneesh perhaps you can provide some insight here? What information could we use to diagnose what happened?
