### ISSUE TITLE
isPlaying API

### ISSUE THREAD

**Issue by giladna** [google/ExoPlayer#6561]
I have a question regarding isPlaying value while player is buffering.

Should it be expected to get isPlaying = false in this condition?

does it make sense to have value for suppress due to buffering?

  @IntDef({PLAYBACK_SUPPRESSION_REASON_NONE, PLAYBACK_SUPPRESSION_REASON_AUDIO_FOCUS_LOSS})

10x
Gilad

**Comment by tonihei** [comment]
Thanks for the suggestion. We considered this (and other variants thereof), but the playback suppression reason is essentially independent of the player state. You can lose audio focus and buffer at the same time and you can just lose focus but be ready for playback. Both may also change independently - one as a result of external changes (i.e. audio focus lost/regained) and one as a result of player-internal changes (change in duration of buffered data).
