### ISSUE TITLE
What are the correct MimeTypes for each subtitle format?

### ISSUE THREAD

**Issue by T-10001** [google/ExoPlayer#6567]
### [REQUIRED] Searched documentation and issues
Searched issues, https://exoplayer.dev/supported-formats.html#standalone-subtitle-formats and https://exoplayer.dev/media-sources.html#side-loading-a-subtitle-file

### [REQUIRED] Question
The table in https://exoplayer.dev/supported-formats.html#standalone-subtitle-formats lists the supported subtitle formats, but only the MimeTypes for 2 of the formats.
Going to https://exoplayer.dev/media-sources.html#side-loading-a-subtitle-file reveals a 3rd MimeType and there is the comment `// The mime type. Must be set correctly.`

So then what are the correct MimeTypes for the other formats?

**Comment by ojw28** [comment]
The two that are documented because they're non-obvious. Aren't the others all obvious, from the [ones available](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/util/MimeTypes.html) (or if you just type `MimeTypes.` into Android Studio and then start typing for auto-completion)?

**Comment by T-10001** [comment]
So 
```
WebVTT --> MimeTypes.TEXT_VTT
TTML --> MimeTypes.APPLICATION_TTML
SubStationAlpha (SSA) --> MimeTypes.TEXT_SSA
```
would be right?

**Comment by ojw28** [comment]
Yes. I guess we should just explicitly list them all in our documentation regardless, to avoid doubt. We will do that. Thanks!

**Comment by ojw28** [comment]
Fixed at https://exoplayer.dev/supported-formats.html.
