### ISSUE TITLE
Why ExoPlayer send so many requests for a single segment?

### ISSUE THREAD

**Issue by weiyuefei** [google/ExoPlayer#6569]
I have a Web server which handles requests to media files, e.g. m4s videos. When I use ExoPlayerLib/2.8.2 to access such a file, I can see lots of HTTP Requests (Range and No Range) in my server. The server can handle the requests, but I do not understand why ExoPlayer tries so many request to get a single file.  Here is part of my log file:
![15716242717910](https://user-images.githubusercontent.com/15873219/67180637-04eca000-f38f-11e9-9034-49a062b246b8.png)

Could anyone tell me why this happens? And what will cause it? Thanks in advance.

**Comment by asmolich** [comment]
different byte ranges

**Comment by krocard** [comment]
Request 1 is not directed to the same server (xx.mn instead of kk.mn)
Request 2 is for audio, not video.
Request 3, 4, 5 seems to be the same file.

**Comment by krocard** [comment]
This case seems to be using ProgressiveMediaSource. We normally make a single unbounded request (i.e. no range header) and hold the connection open. However if the user seeks or if the client needs to retry then we'd make an unbounded request starting from the offset we need, which is what the requests in this case look like.

There are some edge cases using ProgressiveMediaSource where we need additional requests (e.g. if the index we need for seeking is located at the end of the file, we'll request that at the start of playback). Probably doesn't apply here though.

**Comment by krocard** [comment]
Can you tell us more about you testing? Did you seek before capturing those logs?
Also the logs seem to have been corrupted (eg ip address incomplete in some case and not other) can you confirm all those request are from the same client?

**Comment by weiyuefei** [comment]
Sorry for the late response.  We change the live sources for testing and it didn't appear any longer.  Thus I think it is the source which cause this issue, so I will close this issue.
