### ISSUE TITLE
Extend to support raw H264 video stream in ExoPlayer

### ISSUE THREAD

**Issue by imbichitra** [google/ExoPlayer#6570]
Hello,
As discussed in previous issue https://github.com/google/ExoPlayer/issues/3503 
To work with raw H264 video stream one has to use Ac3Extractor and  make sniff return true and use  H264Reader instead of an Ac3Reader. I did the same but the problem is that when i create H264Reader it require 3 argument and the first argument is SeiReader ,actually i am not able to create an instance of SeiReader please help me to create SeiReader instance and pass it to H264Reader .

Thanks.

**Comment by andrewlewis** [comment]
If you don't need CEA 608/708 support I think you can just pass an empty list to `SeiReader`'s constructor.

**Comment by imbichitra** [comment]
I send an empty SeiReader now it work.
Thank you so much!

**Comment by JiannaiJ** [comment]
@imbichitra  I am also doing the same function, but playing H264 can only play one frame, can you give me a little help?
