### ISSUE TITLE
Source Error in Some mp4 Video

### ISSUE THREAD

**Issue by Aastha-dev** [google/ExoPlayer#6573]
Some of the mp4 videos throws this error but other works fine.I have used latest version   implementation 'com.google.android.exoplayer:exoplayer:2.10.6'

2019-10-22 17:44:20.451 27768-28012/com.adwii.android E/ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor, AmrExtractor, Ac4Extractor) could read the stream.
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractorHolder.selectExtractor(ProgressiveMediaPeriod.java:1074)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:952)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:394)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)

**Comment by krocard** [comment]
Could you please provide one of the video that fails to play?

Additionally are you sure your videos use the mp4  container ? A very common source of UnrecognizedInputFormatException is trying to play HLS content with a ProgressiveMediaSource.
Please take a look at our Troubleshooting guide on `unrecognized input format exception`: https://exoplayer.dev/troubleshooting.html#why-do-some-streams-fail-with-unrecognizedinputformatexception.

**Comment by deepakkumardk** [comment]
I am facing the same issue with this video url [https://streamable.com/ju6gs](https://streamable.com/ju6gs)

**Comment by ojw28** [comment]
@deepakkumardk - That's not a video URL. It's a web page URL. In this particular case, if you load the web page in Chrome, then right click and do "View page source", you'll be able to find the actual video URL in the source code, which plays fine in ExoPlayer. It appears the video URLs are deliberately designed to expire though, probably because this website doesn't want you to play its videos elsewhere.

**Comment by deepakkumardk** [comment]
Is this url is okay? [https://filebin.net/6mireu9gkmhdmlpc/video_file.mp4?t=hy31w9yp](https://filebin.net/6mireu9gkmhdmlpc/video_file.mp4?t=hy31w9yp)

**Comment by deepakkumardk** [comment]
Is this url okay? [https://filebin.net/6mireu9gkmhdmlpc/video_file.mp4?t=hyz3ldd1](https://filebin.net/6mireu9gkmhdmlpc/video_file.mp4?t=hyz3ldd1)

**Comment by ojw28** [comment]
That file doesn't play for me, but it's also missing the last 11794 bytes, which explains why. The size of the file is 1364435 bytes. If I download the video from the original link it's 1376229 bytes and plays correctly.
