### ISSUE TITLE
Exoplayer play without time control.

### ISSUE THREAD

**Issue by xiaos** [google/ExoPlayer#6574]
I am develop video editing by exoplayer.  I need process all the video frames output by exoplayer. 

The proess is like this:

exoplayer -> surfaceTexture -> onFrameAvaiable -> process frame ->  swap buffer on encoder's surface.

So i don't need exoplayer to play in real time, just need it output all the frame once decoded. 

Is it possible in exoplayer? Thank you.

**Comment by andrewlewis** [comment]
#3978 has some information on subclassing the video renderer to prevent frames from getting dropped, to do this kind of batch processing.
