### ISSUE TITLE
onTimelineChanged() called after the 2nd renderered

### ISSUE THREAD

**Issue by xiaos** [google/ExoPlayer#6579]
I am using exoplayer with ConcatenatingMediaSource to play 2 videos, output to SurfaceTexture.
I found that when the onTimelineChanged() is called, the 2nd video is rendered already with 1 frame.  
I am expecting onTimelineChanged() is called before any 2nd video frame rendered, any idae? thanks.

**Comment by tonihei** [comment]
The `onTimelineChanged` callback is issued when the media structure in the `Timeline` is updated. This is unrelated to the actual rendering process and more connected to the loading process. What are you trying to achieve with this callback? Maybe we can point out other callbacks that are better suited for what you are trying to do.

**Comment by xiaos** [comment]
thanks for yr reply.

i output the video to surfaceTexture.

in onFrameAvailable() 

I will process each frame, but i need to know when the video changed, to get the new video size for my processing.  

thanks!

**Comment by tonihei** [comment]
That sounds a bit like the problem described in #6576. Can you read through the discussion there to see if it helps?

**Comment by xiaos** [comment]
I have sovled it by using the onVideoFormatChange in Renderer.
