### ISSUE TITLE
Webvtt subtitles and embedded colouring.

### ISSUE THREAD

**Issue by luiscurini** [google/ExoPlayer#6581]
Hi , I'm using exoplayer 2.10.6

Is there a way to enable embedded subtitle colouring in Webvtt subtitles? For example:

```
00:10:21.920 --> 00:10:23.960 line:83%
<c.white.bg_black>Test subtitle white foreground, black background</c>

00:10:56.840 --> 00:11:00.080 line:75%
<c.lime.bg_black>Test subtitle green, black background</c>
```

Bold, italics and underline Tags works but dynamic colouring doesn't.

**Comment by icbaker** [comment]
Thanks for the report, I agree color (and font) styling doesn't seem to work in WebVTT currently.

Seems these are the relevant bits of the spec:
https://www.w3.org/TR/webvtt1/#default-text-color
https://www.w3.org/TR/webvtt1/#default-text-background

Marking this as an enhancement.

This is also tracked internally under issue 143200233.

**Comment by luiscurini** [comment]
Thanks! 

I got the colouring working by embedding the styles into the webvtt file. So it'd be something like this: 

```
WEBVTT

STYLE
::cue(.cyan) {
  color: cyan;
}

STYLE
::cue(.white) {
  color: white;
}

STYLE
::cue(.bg_black) {
  background-color: black;	
}

00:00:10.240 --> 00:00:13.720 line:83%
<c.white.bg_black>Test subtitle white foreground, black background</c>

00:00:28.400 --> 00:00:33.080 line:83%
<c.cyan.bg_black>Test subtitle blue foreground, black background</c>
```

But it would be a nice enhancement to support the default styles or give the possibility to provide a CSS file with the styles.

**Comment by icbaker** [comment]
Related: https://github.com/google/ExoPlayer/pull/4178

**Comment by danybony** [comment]
@icbaker I updated https://github.com/google/ExoPlayer/pull/4178 with the current changes of dev-v2.
Unfortunately I cannot comment on the PR anymore, to unblock the CLA check

**Comment by icbaker** [comment]
Ah, sorry! I assumed re-opening a locked & closed issue would make it unlocked & open but it seemed to make it locked & open. I just unlocked it as well - can you comment on it now?

**Comment by icbaker** [comment]
Should be working in `dev-v2`.
