### ISSUE TITLE
Subtitles are not shown with leanback extension enabled

### ISSUE THREAD

**Issue by GentianB** [google/ExoPlayer#6587]
Hi,

i am using leanback-extension on exoplayer 2.10.5,

if i use exoplayer without leanback extensions dvbsub subtitles are shown,

when i use leancback extension, subtitles are not shown.

i search and found issue: #3985 and i followed that guide but with no success, seems i can not pass a valid **subtitleView** to the **LeanbackPlayAdaptor**.

is there any other way, 
I see from the logs that cues are coming but they are not displayed, or somehow hidden.

##PlaybackFragment.java

subtitleView = getActivity().findViewById(R.id.my_subtitles);
mPlayerAdapter = new LeanbackPlayerAdapter(getActivity(), mPlayer, UPDATE_DELAY, _subtitleView_);

##LeanbackPlayerAdaptor.java
public LeanbackPlayerAdapter(Context context, Player player, final int updatePeriodMs, SubtitleView subtitleView) {
_this.subtitleView = subtitleView;_

***
public void onAttachedToHost(PlaybackGlueHost host) {
    if (host instanceof SurfaceHolderGlueHost) {
      surfaceHolderGlueHost = ((SurfaceHolderGlueHost) host);
      surfaceHolderGlueHost.setSurfaceHolderCallback(componentListener);
    }
    notifyStateChanged();
    player.addListener(componentListener);
    Player.VideoComponent videoComponent = player.getVideoComponent();
    _Player.TextComponent textComponent = player.getTextComponent();_ 

if (videoComponent != null) {
 videoComponent.addVideoListener(componentListener);
    }
 _if (textComponent != null){
      textComponent.addTextOutput(componentListener);
}_

  }

  @Override
  public void onDetachedFromHost() {
    player.removeListener(componentListener);
    Player.VideoComponent videoComponent = player.getVideoComponent();
    Player.TextComponent textComponent = player.getTextComponent();
    if (videoComponent != null) {
      videoComponent.removeVideoListener(componentListener);
    }
    if (textComponent != null){
      textComponent.removeTextOutput(componentListener);
    }
    if (surfaceHolderGlueHost != null) {
      removeSurfaceHolderCallback(surfaceHolderGlueHost);
      surfaceHolderGlueHost = null;
    }
    hasSurface = false;
    Callback callback = getCallback();
    callback.onBufferingStateChanged(this, false);
    callback.onPlayStateChanged(this);
    maybeNotifyPreparedStateChanged(callback);
  }

  _public void onCues(List<Cue> cues) {
      if (subtitleView != null){
        subtitleView.setCues(cues);
      }
    }_

**Comment by GentianB** [comment]
There was a problem with my subtitleView, after fixing it, the subtitle appeared.
anyway i think the above must be included by default on the leanback playadaptor.

**Comment by MustafaBasim** [comment]
hi @GentianB 
can you please upload a full example of how you managed to show the subtitles, I simply couldn't pass the SubtitleView to the LeanbackPlayerAdapter class nor extend it, I did merge the subtitle source with the video source already.

If you want to see my code I did open an issue here [Subtitles are not displaying](https://github.com/android/tv-samples/issues/6) 

thanks in advance

**Comment by GentianB** [comment]
you declare this inside activity_playback.xml

<com.google.android.exoplayer2.ui.SubtitleView
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/exo_subtitles"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:layout_gravity="bottom|center_horizontal"
    android:layout_marginBottom="32dp"
    android:layout_marginLeft="16dp"
    android:layout_marginRight="16dp"

    android:visibility="visible" />


then inside Plabackactivity you assign to subtitleView which is public
subtitleView = findViewById(R.id.exo_subtitles);

and you access it and pass to playbackadaptor like this:

mPlayerAdapter = new LeanbackPlayerAdapter(getActivity(), mPlayer, UPDATE_DELAY, PlaybackActivity.subtitleView);

the rest, i have already written above.

**Comment by MustafaBasim** [comment]
I did try that, but the LeanbackPlayerAdapter does not accept the fourth parameter ( subtitleView ) in its constructor, I'm using the 2.8.4 exoPlayer library, I did check the 2.10.5 and it also has the same issue.

I'm importing it from:
import com.google.android.exoplayer2.ext.leanback.LeanbackPlayerAdapter

**Comment by GentianB** [comment]
You should extend it like this inside LeanbackPlayeradaptor

public LeanbackPlayerAdapter(Context context, Player player, final int updatePeriodMs, SubtitleView subtitleView) {

    this.context = context;
    this.player = player;
    this.updatePeriodMs = updatePeriodMs;
    this.subtitleView = subtitleView;
    handler = new Handler();
    componentListener = new ComponentListener();

    controlDispatcher = new DefaultControlDispatcher();
  }

**Comment by MustafaBasim** [comment]
thanks for your help @GentianB 
I was extending the LeanbackPlayeradaptor itself, which was wrong
I extended the PlayerAdapter and added the needed code from your sample, it worked.

**Comment by khat33b** [comment]
I have done all the steps mentioned in Java and have gotten the subtitles to appear in the `onCues` method. The problem is declaring the `SubtitleView` in the layout. My `activity_player.xml` simply calls the fragment `PlaybackVideoFragment` which extends `VideoSupportFragment`  which has the layout files for the fragment.

```
<fragment xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/main_browse_fragment"
    android:name="com.example.android.leanbackexoplayer.PlaybackVideoFragment"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".PlaybackActivity"
    tools:deviceIds="tv"
    tools:ignore="MergeRootFrame">

    <com.google.android.exoplayer2.ui.SubtitleView
        android:id="@+id/leanback_subtitles"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="bottom|center_horizontal"
        android:layout_marginLeft="16dp"
        android:layout_marginRight="16dp"
        android:layout_marginBottom="32dp"
        android:visibility="visible" />
</fragment>
```

Declaring a subtitle view even as a child does not work as the `getActivity().findViewById(R.id.leanback_subtitles)` always returns null. I would like to do this in such a way that these changes can be added ot the leanback extension in a PR. How do I do this?

**Comment by MustafaBasim** [comment]
hi, @khat33b 
I managed to add the subtitleView in activity_playback.xml like so :

    <merge xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <TextureView
        android:id="@+id/texture_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_gravity="center" />

    <fragment
        android:id="@+id/playback_controls_fragment"
        android:name="co.albox.cinematv.player.PlaybackFragment"
        android:tag="@string/playback_tag"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />
    <com.google.android.exoplayer2.ui.SubtitleView
        android:id="@+id/leanback_subtitles"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="bottom|center_horizontal"
        android:layout_marginLeft="16dp"
        android:layout_marginRight="16dp"
        android:layout_marginBottom="32dp"
        android:visibility="visible" />
    </merge>

but realized that the subtitleView showed above the control dock so I add it as a child between the dock and the playerView like so (in kotlin)

    val subtitleView = SubtitleView(activity).apply {
            val params = FrameLayout.LayoutParams(
                FrameLayout.LayoutParams.WRAP_CONTENT,
                FrameLayout.LayoutParams.WRAP_CONTENT
            )
            params.gravity = Gravity.CENTER and Gravity.BOTTOM
            params.setMargins(16.toDp(resources), 0 , 16.toDp(resources) , 0 )
            layoutParams = params
        }
        mPlayerAdapter = LeanbackPlayerAdapter(activity as Context, mPlayer!!, UPDATE_DELAY,subtitleView)

    // adding subtitleView
        val controlsView = activity?.findViewById<View>(R.id.playback_controls_dock)
        val parent = controlsView?.parent
        val mainFrameLayout : FrameLayout
        if (parent == null) {
            Log.d("ERROR", "this.getParent() is null")
        }
        else {
            if (parent is ViewGroup) {
                val grandparent = parent.getParent()
                if (grandparent == null) {
                    Log.d("ERROR", "((ViewGroup) this.getParent()).getParent() is null")
                }
                else {
                    if (parent is FrameLayout) {
                        mainFrameLayout =  grandparent as (FrameLayout)
                        val playerFrameLayout = mainFrameLayout.getChildAt(1) as FrameLayout
                        // index 1 is between the playerSurface and the controlView, so we can add the subtitleView
                        playerFrameLayout.addView(subtitleView,1)
                    }
                    else {
                        Log.d("ERROR", "((ViewGroup) this.getParent()).getParent() is not a FrameLayout")
                    }
                }
            }
            else {
                Log.d("ERROR", "this.getParent() is not a ViewGroup")
            }
        }

and it worked as intended

**Comment by khat33b** [comment]
@MustafaBasim Thanks for your help. I figured it out. I had to override the `lb_playback_fragment.xml` file in my `res` folder. This is my modifed file:

```
<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/playback_fragment_root"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:transitionGroup="false">

    <androidx.leanback.widget.NonOverlappingFrameLayout
        android:id="@+id/playback_fragment_background"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:transitionGroup="false" />

    <androidx.leanback.widget.NonOverlappingFrameLayout
        android:id="@+id/playback_controls_dock"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:transitionGroup="true" />

    <com.google.android.exoplayer2.ui.AspectRatioFrameLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_gravity="center">

        <com.google.android.exoplayer2.ui.SubtitleView
            android:id="@+id/leanback_subtitles"
            android:layout_width="match_parent"
            android:layout_height="match_parent" />

    </com.google.android.exoplayer2.ui.AspectRatioFrameLayout>
</FrameLayout>
```

**Comment by YasirNabeel** [comment]
> hi, @khat33b
> I managed to add the subtitleView in activity_playback.xml like so :
> 
> ```
> <merge xmlns:android="http://schemas.android.com/apk/res/android"
> android:layout_width="match_parent"
> android:layout_height="match_parent"
> android:orientation="vertical">
> 
> <TextureView
>     android:id="@+id/texture_view"
>     android:layout_width="match_parent"
>     android:layout_height="match_parent"
>     android:layout_gravity="center" />
> 
> <fragment
>     android:id="@+id/playback_controls_fragment"
>     android:name="co.albox.cinematv.player.PlaybackFragment"
>     android:tag="@string/playback_tag"
>     android:layout_width="match_parent"
>     android:layout_height="match_parent" />
> <com.google.android.exoplayer2.ui.SubtitleView
>     android:id="@+id/leanback_subtitles"
>     android:layout_width="wrap_content"
>     android:layout_height="wrap_content"
>     android:layout_gravity="bottom|center_horizontal"
>     android:layout_marginLeft="16dp"
>     android:layout_marginRight="16dp"
>     android:layout_marginBottom="32dp"
>     android:visibility="visible" />
> </merge>
> ```
> 
> but realized that the subtitleView showed above the control dock so I add it as a child between the dock and the playerView like so (in kotlin)
> 
> ```
> val subtitleView = SubtitleView(activity).apply {
>         val params = FrameLayout.LayoutParams(
>             FrameLayout.LayoutParams.WRAP_CONTENT,
>             FrameLayout.LayoutParams.WRAP_CONTENT
>         )
>         params.gravity = Gravity.CENTER and Gravity.BOTTOM
>         params.setMargins(16.toDp(resources), 0 , 16.toDp(resources) , 0 )
>         layoutParams = params
>     }
>     mPlayerAdapter = LeanbackPlayerAdapter(activity as Context, mPlayer!!, UPDATE_DELAY,subtitleView)
> 
> // adding subtitleView
>     val controlsView = activity?.findViewById<View>(R.id.playback_controls_dock)
>     val parent = controlsView?.parent
>     val mainFrameLayout : FrameLayout
>     if (parent == null) {
>         Log.d("ERROR", "this.getParent() is null")
>     }
>     else {
>         if (parent is ViewGroup) {
>             val grandparent = parent.getParent()
>             if (grandparent == null) {
>                 Log.d("ERROR", "((ViewGroup) this.getParent()).getParent() is null")
>             }
>             else {
>                 if (parent is FrameLayout) {
>                     mainFrameLayout =  grandparent as (FrameLayout)
>                     val playerFrameLayout = mainFrameLayout.getChildAt(1) as FrameLayout
>                     // index 1 is between the playerSurface and the controlView, so we can add the subtitleView
>                     playerFrameLayout.addView(subtitleView,1)
>                 }
>                 else {
>                     Log.d("ERROR", "((ViewGroup) this.getParent()).getParent() is not a FrameLayout")
>                 }
>             }
>         }
>         else {
>             Log.d("ERROR", "this.getParent() is not a ViewGroup")
>         }
>     }
> ```
> 
> and it worked as intended



> @MustafaBasim Thanks for your help. I figured it out. I had to override the `lb_playback_fragment.xml` file in my `res` folder. This is my modifed file:
> 
> ```
> <?xml version="1.0" encoding="utf-8"?>
> <FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
>     android:id="@+id/playback_fragment_root"
>     android:layout_width="match_parent"
>     android:layout_height="match_parent"
>     android:transitionGroup="false">
> 
>     <androidx.leanback.widget.NonOverlappingFrameLayout
>         android:id="@+id/playback_fragment_background"
>         android:layout_width="match_parent"
>         android:layout_height="match_parent"
>         android:transitionGroup="false" />
> 
>     <androidx.leanback.widget.NonOverlappingFrameLayout
>         android:id="@+id/playback_controls_dock"
>         android:layout_width="match_parent"
>         android:layout_height="match_parent"
>         android:transitionGroup="true" />
> 
>     <com.google.android.exoplayer2.ui.AspectRatioFrameLayout
>         android:layout_width="match_parent"
>         android:layout_height="match_parent"
>         android:layout_gravity="center">
> 
>         <com.google.android.exoplayer2.ui.SubtitleView
>             android:id="@+id/leanback_subtitles"
>             android:layout_width="match_parent"
>             android:layout_height="match_parent" />
> 
>     </com.google.android.exoplayer2.ui.AspectRatioFrameLayout>
> </FrameLayout>
> ```
 hey, can you please tell me the way to override the lb_playback_fragment.xml
