### ISSUE TITLE
HLS Issue - Sound Streams, Video Freezes | Drops Repeatedly

### ISSUE THREAD

**Issue by Mackqrenc** [google/ExoPlayer#659]
Hello,

I have an issue that with Live HLS streaming, the sound works perfectly without any drop for hours but the image of video freezes from the first second. Would you kindly look into the issue and suggest a quick fix for the problem?

Best regards,

**Comment by bsysop** [comment]
@Mackqrenc, please say what exactly device/model/android version, and if possible put here some logcat log and if possible also a m3u8 online file.

(I got some problems like this, but depends the device)

**Comment by Mackqrenc** [comment]
@bsysop, I'm currently trying the player with LG Nexus 5 (5.1.1API) and Samsung Galaxy Alpha (5.0.1 API). I'm currently experiencing the issue on all the devices I'm working with.

There is not the same story all the time. Either I have the sound and no image or I drop out all the time, it is unwatchable. It may be due to m3u8 as well, so It might be a problem from provider side. The logcat which happens repeatedly is below:

![screen shot 2015-07-27 at 09 53 48](https://cloud.githubusercontent.com/assets/9883323/8900129/69d875ec-3445-11e5-9c85-b1d238b219df.png)

Also, the you can find the m3u8 file from the link: http://mn-i.mncdn.com/nokta2_live/live1/playlist.m3u8

Best,
Mackqrenc

**Comment by ojw28** [comment]
That looking means the connection is timing out. It's most likely a provider issue, I see the same behaviour if I try and play the stream in Safari on a Mac.

**Comment by Mackqrenc** [comment]
Hello @ojw28 

You were right, it was a problem with the provider. It is fixed now. I can play the stream very well but sometimes it stops again with the messages (These happen repeatedly when this issue shows itself, but the main one is the first screenshot's log) stated below:

![screen shot 2015-07-27 at 16 02 31](https://cloud.githubusercontent.com/assets/9883323/8906648/ec266a12-3478-11e5-8462-0498c1f998c5.png)

![screen shot 2015-07-27 at 15 12 39](https://cloud.githubusercontent.com/assets/9883323/8906663/fb44956e-3478-11e5-909c-e3f7ff73be40.png)

![screen shot 2015-07-27 at 15 28 39](https://cloud.githubusercontent.com/assets/9883323/8906670/0641c3e2-3479-11e5-9974-2849c77a3a52.png)

**Comment by bsysop** [comment]
If you see in that second picture, you will see "java.net.SocketTimeoutException", this is no difference than before,

For sure your internet connection or server connection have several problems, losing data or something like this.

Try to fix, later will be good.
