### ISSUE TITLE
Player unable to play 720p & above MP4 files on API 19 devices

### ISSUE THREAD

**Issue by hkim2013** [google/ExoPlayer#6594]
### [REQUIRED] Issue description
I am unable to play 720px and 1080px MP4 files, but I can play everything else on the Android API 19 device. We are currently using Exoplayer v2.9.0, however we cannot update because the issue still persists in Exoplayer v2.10.6.

```
[
  {
    "name": "MP4 Testing",
    "samples": [
      {
        "name": "Testing Random MP4 1080p Video",
        "uri": "https://file-examples.com/wp-content/uploads/2017/04/file_example_MP4_1280_10MG.mp4"
      },
      {
        "name": "H.264 320px",
        "uri": "https://cdn.jwplayer.com/videos/RDn7eg0o-Zq6530MP.mp4"
      },
      {
        "name": "H.264 480px",
        "uri": "https://cdn.jwplayer.com/videos/RDn7eg0o-TNpruJId.mp4"
      },
      {
        "name": "H.264 720px",
        "uri": "https://content.jwplatform.com/videos/RDn7eg0o-cIp6U8lV.mp4"
      },
      {
        "name": "H.264 1280px",
        "uri": "https://cdn.jwplayer.com/videos/RDn7eg0o-FctPAkow.mp4"
      },
      {
        "name": "H.264 HLS",
        "uri": "https://cdn.jwplayer.com/manifests/RDn7eg0o.m3u8"
      }
    ]
  }
]
```

### [REQUIRED] Reproduction steps
1. Open this project
2. Run "demo" module on Android API 19 device / emulator
3. Play **Testing Random MP4 1080p Video**, notice the video does not play
4. Play **H.264 320px**, notice the video plays
5. Play **H.264 480px**, notice the video plays
6. Play **H.264 720px**, notice the video does not play
7. Play **H.264 1080px**, notice the video does not play

### [REQUIRED] Link to test content
* **media.exolist.json:** [media.exolist.json](https://s3.amazonaws.com/hyunjoo.success.jwplayer.com/android/jira/v380/api19/exoplayer-issue-ticket/media.exolist.json)
* **Exoplayer Demo Project:** [ExoPlayer-2106-release-v2-API19-MP4broken.zip](https://s3.amazonaws.com/hyunjoo.success.jwplayer.com/android/jira/v380/api19/exoplayer-issue-ticket/ExoPlayer-2106-release-v2-API19-MP4broken.zip)

### [REQUIRED] A full bug report captured from the device
* **Error log (txt):** [exo2106-api19-mp4-errorlog.txt](https://s3.amazonaws.com/hyunjoo.success.jwplayer.com/android/jira/v380/api19/exoplayer-issue-ticket/exo2106-api19-mp4-errorlog.txt)
* **Video - API19 - broken:** [exo2106-api19-mp4-error.mov](https://s3.amazonaws.com/hyunjoo.success.jwplayer.com/android/jira/v380/api19/exoplayer-issue-ticket/exo2106-api19-mp4-error.mov)
* **Video - API 28 - works:** [exo2106-API28-works.mov](https://s3.amazonaws.com/hyunjoo.success.jwplayer.com/android/jira/v380/api19/exoplayer-issue-ticket/exo2106-API28-works.mov)
* **Exoplayer Version (2.9.0) - Video - API 19 - broken ** [exoplayer-290-hires-mp4-broken.mov](https://s3.amazonaws.com/hyunjoo.success.jwplayer.com/android/jira/v380/api19/exoplayer-290-hires-mp4-broken.mov)

### [REQUIRED] Version of ExoPlayer being used
Exoplayer v2.10.6

### [REQUIRED] Device(s) and version(s) of Android being used
* Tested on: 
- Emulator Android 4.4.2, API 19

**Comment by andrewlewis** [comment]
It's likely that the emulator doesn't support the video format you're trying to play. In particular, I think the official emulator only supports H.264/AVC Baseline profile before API 23. See also [Supported devices](https://exoplayer.dev/supported-devices.html).

If you can reproduce this on a real device and the video format is supported according to the [CDD](https://source.android.com/compatibility/cdd), please provide a full bug report captured via `adb bugreport`.

**Comment by hkim2013** [comment]
@andrewlewis thank you for still responding and providing the explanation. I read your other ticket responses and I double-checked as you suggested with a physical device, it worked as expected.
