### ISSUE TITLE
How to implement a base player ,while leaving from the video screen like picture in picture with video title ,seek ,pause ,play and close options in it

### ISSUE THREAD

**Issue by Sathish-Kumar-Kanagaraj** [google/ExoPlayer#6597]
1)How to implement a mini-player like youtube while leaving from the main screen of the video, Need to be displayed with the video content, title, and other needed options in the base of home page.
2)I have used Picture in Picture Mode but it supports only in the latest version of the android device from oreo.
3)How to implement same like a youtube mini-player in the base view of home page

**Comment by tonihei** [comment]
Supporting Picture-in-Picture is more of a general Android development question unrelated to ExoPlayer. Have a look at [this documentation](https://developer.android.com/guide/topics/ui/picture-in-picture) for a start. It also has links on how to handle UI during PiP mode (including video UI). Also consider asking questions on further implementation details on StackOverflow or similar sites.
