### ISSUE TITLE
Synchronize delayed subtitles stream with audio/video stream in MPEG-TS

### ISSUE THREAD

**Issue by okycelt** [google/ExoPlayer#6599]
### [REQUIRED] Searched documentation and issues
https://exoplayer.dev/
#6365

### [REQUIRED] Question
We were given a transport stream in which a subtitles elementary stream has PES timestamps several hours delayed from timestamps of a video elementary stream and an audio elementary stream. Because of that, ExoPlayer just throws the subtitle packets away. In theory, is there a way for us to adjust the subtitles stream PES timestamps to match the timestamps of video or audio? Or force ExoPlayer to parse the subtitle packets and display subtitles somehow else?

The transport stream is a live content delivered via UDP. 

We've reported the issue to the content provider, but I would like to check if there's something we can do on the player's side.

### Link to test content
We can provide a link, but I'm not sure if that's necessary.

**Comment by ojw28** [comment]
If you know the offset then it's almost certainly possible to do something on the player side. In the very simplest case you could take ExoPlayer as source and hard-code the offset. I don't think this is something we can justify spending time helping to work out for you though, sorry. You should really just get the content provider to fix the content, which is presumably a requirement to play the content with other players in any case.
