### ISSUE TITLE
Video is not displayed in LG google TV

### ISSUE THREAD

**Issue by aravinds03** [google/ExoPlayer#660]
[Cloning https://github.com/google/ExoPlayer/issues/604]
Hi,
I have integrated latest version of exoPlayer in my app and it performs really well in all mobile and tablet devices. It also worked well in amazon fire devices. But, it did not work in LG google tv (running jelly bean). The issue is that video is not displayed, but audio is playing. It happens for all .m3u8 files.

Since new android version does not have permission to read entire logs including framework, I manage to get logs that my app is recording from the customer device and it is available here https://www.dropbox.com/s/5yz356fs442whtc/logs.txt?dl=0 .

Please investigate the logs and provide your comments.

**Comment by aravinds03** [comment]
From the logs,
looks like some methods in MediaCodec are not available in framework.
I took one example http://developer.android.com/reference/android/media/MediaCodecInfo.CodecCapabilities.html#isFeatureSupported(java.lang.String) and observed that this method is available only after API level 19.

But, my customer device is running android 4.2.2 (Api 17) in LG google TV.
Shouldn't exoplayer internally handles such cases depending upon api level?

**Comment by ojw28** [comment]
The lines you refer to in the logs aren't errors, they are informational messages only. The library includes calls to these methods, but they're not actually called unless the API level is high enough.  There are some other ones that may or may not be more worrying, such as this one, but it's in your own code:

E/dalvikvm( 8233): Could not find class 'android.view.accessibility.CaptioningManager', referenced from method com.tentkotta.exoplayer.PlayerActivity.getUserCaptionFontScaleV19

As per my response in the other issue you filed, I don't think we'll be spending any effort investigating GoogleTV specific issues. There haven't been any new GoogleTV devices for at least 2 years. Most GoogleTV devices are over 3 years old, and all have been discontinued according to the (Wikipedia)[https://en.wikipedia.org/wiki/Google_TV#Second_Generation] page. The platform itself is deprecated in favour of AndroidTV, which we are supporting.

**Comment by aravinds03** [comment]
Hi,
Looks like the issue related to video is due to Exception,

I/TentkottaPlayerActivity( 3150): audio focus result=1
E/ExoPlayerImplInternal( 3150): Internal runtime error.
E/ExoPlayerImplInternal( 3150): java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
E/ExoPlayerImplInternal( 3150):         at com.google.android.exoplayer.hls.HlsChunkSource.getChunkOperation(HlsChunkSource.java:256)
E/ExoPlayerImplInternal( 3150):         at com.google.android.exoplayer.hls.HlsSampleSource.maybeStartLoading(HlsSampleSource.java:488)
E/ExoPlayerImplInternal( 3150):         at com.google.android.exoplayer.hls.HlsSampleSource.prepare(HlsSampleSource.java:160)
E/ExoPlayerImplInternal( 3150):         at com.google.android.exoplayer.MediaCodecTrackRenderer.doPrepare(MediaCodecTrackRenderer.java:248)
E/ExoPlayerImplInternal( 3150):         at com.google.android.exoplayer.TrackRenderer.prepare(TrackRenderer.java:116)
E/ExoPlayerImplInternal( 3150):         at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(ExoPlayerImplInternal.java:267)
E/ExoPlayerImplInternal( 3150):         at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:195)
E/ExoPlayerImplInternal( 3150):         at android.os.Handler.dispatchMessage(Handler.java:95)
E/ExoPlayerImplInternal( 3150):         at android.os.Looper.loop(Looper.java:137)
E/ExoPlayerImplInternal( 3150):         at android.os.HandlerThread.run(HandlerThread.java:60)
E/ExoPlayerImplInternal( 3150):         at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
D/TentkottaMediaController( 3150): onProgressChanged progress=0 fromUser=false
E/EventLogger( 3150): playerFailed [0.22]
E/EventLogger( 3150): com.google.android.exoplayer.ExoPlaybackException: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
E/EventLogger( 3150):   at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:236)
E/EventLogger( 3150):   at android.os.Handler.dispatchMessage(Handler.java:95)
E/EventLogger( 3150):   at android.os.Looper.loop(Looper.java:137)
E/EventLogger( 3150):   at android.os.HandlerThread.run(HandlerThread.java:60)
E/EventLogger( 3150):   at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
E/EventLogger( 3150): Caused by: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
E/EventLogger( 3150):   at com.google.android.exoplayer.hls.HlsChunkSource.getChunkOperation(HlsChunkSource.java:256)
E/EventLogger( 3150):   at com.google.android.exoplayer.hls.HlsSampleSource.maybeStartLoading(HlsSampleSource.java:488)
E/EventLogger( 3150):   at com.google.android.exoplayer.hls.HlsSampleSource.prepare(HlsSampleSource.java:160)
E/EventLogger( 3150):   at com.google.android.exoplayer.MediaCodecTrackRenderer.doPrepare(MediaCodecTrackRenderer.java:248)
E/EventLogger( 3150):   at com.google.android.exoplayer.TrackRenderer.prepare(TrackRenderer.java:116)
E/EventLogger( 3150):   at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(ExoPlayerImplInternal.java:267)
E/EventLogger( 3150):   at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:195)
E/EventLogger( 3150):   ... 4 more
