### ISSUE TITLE
How can we check if the controller is visible?

### ISSUE THREAD

**Issue by udaisubramaniam** [google/ExoPlayer#6600]
### Issue description
There's currently no way to check if the playback controls are visible or not. This seems to have been fixed in a past issue (https://github.com/google/ExoPlayer/issues/4385), however it's not there anymore. How can it be done now?

### Reproduction steps
No method present for checking control visibility.

### [REQUIRED] Version of ExoPlayer being used
2.7.3

### [REQUIRED] Device(s) and version(s) of Android being used
Mi A2 Android 9

**Comment by tonihei** [comment]
The method is still there: https://github.com/google/ExoPlayer/blob/41b3fc110178e9a5c969a0102c5b074189065273/library/ui/src/main/java/com/google/android/exoplayer2/ui/PlayerView.java#L809

**Comment by udaisubramaniam** [comment]
My bad, it was a versioning issue. I was on 2.7.3 on which this change wasn't there. Thanks for the help.
