### ISSUE TITLE
Video stutter/lag with DD+ 7.1 audio track on Shield

### ISSUE THREAD

**Issue by ebr11** [google/ExoPlayer#6602]
### [REQUIRED] Issue description
When playing an item with a 7.1 DD+ (EAC3) audio track, the video lags and stutters badly.

### [REQUIRED] Reproduction steps
Play an item with a DD+ 7.1 audio track on the Nvidia Shield.  I will send a sample.

### [REQUIRED] Link to test content
Will send.

### [REQUIRED] A full bug report captured from the device
Will send.

### [REQUIRED] Version of ExoPlayer being used
2.10.2 (also reproduced with 2.10.6)

### [REQUIRED] Device(s) and version(s) of Android being used
Only appears to be a problem on the NVidia Shield.  Has persisted across all firmware versions above 7.0.

**Comment by ebr11** [comment]
Hi.  Were you able to reproduce with the material I provided?

**Comment by andrewlewis** [comment]
Sorry for the long delay. The provided stream has some AC-3 syncframes within the E-AC-3 stream. We had another report of the same underlying bug recently with a suggested fix, so please look out for a fix here soon.

**Comment by ebr11** [comment]
Excellent.  Thanks for the update.  FYI - I can reproduce this problem with every DD+ 7.1 track I have...

Happy New Year!

**Comment by andrewlewis** [comment]
This should now be fixed on the development branch. Please let us know if you can still reproduce the issue.
