### ISSUE TITLE
Latency Measurement for ExoPlayer

### ISSUE THREAD

**Issue by harini113** [google/ExoPlayer#6606]
When filing a question:
-----------------------
Fill out the sections below, leaving the headers but replacing the content. If
you're unable to provide certain information, please explain why in the relevant
section. We may close issues if they do not include sufficient information.

### [REQUIRED] Searched documentation and issues
Searched https://github.com/google/ExoPlayer/issues to see if the latency measurement for exoplayer is addressed. Also searched https://github.com/google/ExoPlayer/blob/release-v2/RELEASENOTES.md and Android Mediacodec pages

### [REQUIRED] Question
I would like to measure latency when playing a clip via custom exoplayer apk. Example Startup Latency - from the time the play cmd is issued to the actual time the clip starts playing on the apk. Similarly pause latency. This is a value I would like to measure at the mediaCodecRenderer level and print values from my apk.

**Comment by ojw28** [comment]
You can time startup latency (among other things) by adding an `AnalyticsListener` to your player. You can do this by calling `player.addAnalyticsListener`, and then override methods corresponding to events that you're interested in. For example `onPlayerStateChanged` looking for when `playbackState` transitions to `STATE_READY`.

`EventLogger` is an `AnalyticsListener` that we provide, which logs events along with timings to logcat. This output should be visible if you play a piece of content using our demo app. To get started, one approach would be to fork that class and use it as a starting point.

I'm less clear what pause latency means. I'd expect pause to happen very quickly in all cases.

**Comment by tonihei** [comment]
In the next release, there will also be a `PlaybackStatsListener` that returns `PlaybackStats` for each playback. And you will be able to query all kinds of metrics from there (e.g. `PlaybackStats.getTotalJoinTimeMs()`)

**Comment by harini113** [comment]
Is there an ETA for the next release?

**Comment by ojw28** [comment]
We don't commit to release schedules. It should be relatively soon though (well before the end of the year). Closing this question as answered.
