### ISSUE TITLE
No playback on older devices (Specific chipsets)

### ISSUE THREAD

**Issue by antarikshc** [google/ExoPlayer#6609]
### Issue description
**Playback failed on MT6753 devices**

Tested on: 
Phone: Lenovo Vibe K4 Note (MT6753) API 23
Decoder: OMX.MTK.VIDEO.DECODER.AVC
Build.DEVICE: A7020a48
Build.MODEL: Lenovo A7020a48

Video's used:
https://storage.googleapis.com/wedupp-exo-bucket/demo.mp4
https://storage.googleapis.com/wedupp-exo-bucket/demo-baseline-3.mp4
https://storage.googleapis.com/wedupp-exo-bucket/demo-cloudinary.mp4

All the videos are playing on Snapdragon devices 

### Reproduction steps
Replace Links for Dizzy (MP4) in media.exolist.json

### A full bug report captured from the device
Logcat: https://pastebin.com/cVpK5vK3

### Version of ExoPlayer being used
2.10.6
can be reproduced on previous versions as well

### Device(s) and version(s) of Android being used
Lenovo Vibe K4 Note | (MT6753) | API 23

__________________________________________

Please let me know if the video needs any specific format.

**Comment by andrewlewis** [comment]
The logging like:

```
D/MediaCodecInfo: NoSupport [sizeAndRate.support, 1456x1456x59.992637634277344] [OMX.MTK.VIDEO.DECODER.AVC, video/avc] [A7020a48, Lenovo A7020a48, LENOVO, 23]
```

suggests that the stream exceeds the device capabilities.

Please see the Android CDD to find out what minimum format support you can expect. [Here is the relevant section for H.264/AVC on Android M](https://source.android.com/compatibility/6.0/android-6.0-cdd.html#5_3_video_decoding).
