### ISSUE TITLE
What is the dummysurface? 

### ISSUE THREAD

**Issue by Slim1991** [google/ExoPlayer#6611]
I want to use one player for 2 surfaceview/textureview for render one video in 2 views at the same time. I wandering the dummysurface may help somethings. I don't know. Anyone help me, pls.

**Comment by andrewlewis** [comment]
This sounds the same as #4640. Generally ExoPlayer uses `MediaCodec` to render video to a single `Surface`. To get the decoder output visible in two views, I'd try passing a surface created from a `SurfaceTexture` to the player, and then copying from the texture to the output views using OpenGL. I don't think `DummySurface` helps with this, though some of the code in its helper class `EGLSurfaceTexture` may be useful.

**Comment by Slim1991** [comment]
Can you give me some example codes, pls?

**Comment by andrewlewis** [comment]
I'm afraid we don't have any code ready to share for this, and we don't have resources to write sample code for such a specialized use case. The information in my previous comment should be enough to get started but you will need to do some research yourself. Sorry not to be more helpful.
