### ISSUE TITLE
Unable to play hevc video on LG Q7 (lower end device)

### ISSUE THREAD

**Issue by dummy-amit** [google/ExoPlayer#6612]
### [REQUIRED] Issue description
For hevc videos, exo player fails silently with error in log cat

### [REQUIRED] Reproduction steps
Create media source for above url and play it on this device.

### [REQUIRED] Link to test content
Video url --> https://d1104ewo8apaup.cloudfront.net/video/hevc-0/f82ea871847f635f8c25ddcd34786575rq6lpf9g.mp4

### [REQUIRED] A full bug report captured from the device
Attached log file in comments below.

Here is list of codecs available on devices.
![image](https://user-images.githubusercontent.com/49638809/68103060-581c3200-fefb-11e9-99b9-e288e7e7fbc5.png)

### [REQUIRED] Version of ExoPlayer being used
latest (2.9.6)

### [REQUIRED] Device(s) and version(s) of Android being used
LG Q7
Android 8.1.0

**Comment by dummy-amit** [comment]
[log.txt](https://github.com/google/ExoPlayer/files/3800201/log.txt)

Uploading log to see in proper formating

**Comment by ojw28** [comment]
Please can you try playing the video in our demo app on the affected device, and attach a bug report taken after experiencing the issue in that case? Alternatively, please attach an `EventListener` to the player inside your app, which will add additional logging to a bug report taken after experiencing the issue within your app. You can do this with:

```
player.addAnalyticsListener(new EventLogger(trackSelector));
```

> latest (2.9.6)

As an aside, 2.9.6 is not the latest. It would be a good test to try using the latest ExoPlayer demo app, which will use 2.10.6: https://github.com/google/ExoPlayer/tree/r2.10.6

**Comment by dummy-amit** [comment]
Sorry about wrong release info @ojw28 
I tried latest version 10.9.6 as well, same problem occured. Will follow steps given by you and will attach the required things today. 
Thanks for quick response for the issue.

**Comment by dummy-amit** [comment]
[log.txt](https://github.com/google/ExoPlayer/files/3810124/log.txt)

I attached Event Logger in my app and generated this logcat report. Let me know if you need any more help in getting more data. @ojw28

**Comment by ojw28** [comment]
> For hevc videos, exo player fails silently with error in log cat

It's worth noting that ExoPlayer is not failing silently. It's calling `EventListener.onPlayerError` to indicate that playback has failed.

> I attached Event Logger in my app and generated this logcat report. Let me know if you need any more help in getting more data. @ojw28

Thanks for the log. The device doesn't support this video resolution for HEVC.

Because querying a codec's support for vertical video resolutions has historically not been that reliable, we have code that queries codec's support with the width and height swapped round as well. If the swapped resolution is supported, we assume (correctly in most cases, but incorrectly here) that the vertical video resolution is supported too. This is why you see "rotated" and "AssumedSupport" in this log line:
```
AssumedSupport [sizeAndRate.rotated, 720x1280x-1.0]
```
We then attempt playback, and fail because in this case our assumption was incorrect.

Explanation aside, the device does not support this resolution, and so there is no fix that would result in the video playing correctly on the device. The only change we could make would be to propagate a clearer error.

**Comment by dummy-amit** [comment]
> It's worth noting that ExoPlayer is not failing silently. It's calling EventListener.onPlayerError to indicate that playback has failed.

Yes, sorry about that, I forgot to put in error listener. It does notify me of this error. But still need better error message to fallback to avc url or something.

> Explanation aside, the device does not support this resolution, and so there is no fix that would result in the video playing correctly on the device

Does this mean I will not be able to play this hevc video in any way with exo player? Or any other player for that fact?
@ojw28

**Comment by ojw28** [comment]
> Does this mean I will not be able to play this hevc video in any way with exo player? Or any other player for that fact?

I think this is correct for any player using the platform's HEVC decoder. It's possible that a player bundling its own video decoder might be able to play it, although since decoding would be purely in software in this case, performance and battery drain may be issues.

**Comment by ojw28** [comment]
There are two things we should do here:
1. Disable the rotation check for this decoder on this device.
1. Make sure a clearer error is thrown in the case playback fails due to a renderer error, having selected a format that exceeds device capabilities.

**Comment by ojw28** [comment]
Actually, (1) is not particularly important because the track selector will attempt to play the stream anyway. We should prioritize fixing (2).

**Comment by ojw28** [comment]
The first part of this is done. @tonihei is probably going to look at the second part.

**Comment by ojw28** [comment]
For the second part, `ExoPlaybackException` now includes a `rendererFormatSupport` field that you can query to determine whether the format being exceeded device capabilities (we should add this to our documentation somewhere!).
