### ISSUE TITLE
audio bug in library 2.9.6

### ISSUE THREAD

**Issue by safdarkowda** [google/ExoPlayer#6613]
Hi ,
 
I am working on exoplayer since 1 year,initially it was working fine ,but now ,
'com.google.android.exoplayer:exoplayer:2.9.6' is not supporting multiple audio detection,can you help.

the link has two audio ,only one is showing.

link=http://ooyalaqa.streaming.mediaservices.windows.net/a385162c-246d-418b-93b0-be08f2c28fe2/M1YnhyZTE6X6-QO5AmLg1f623BYEDioW.ism/Manifest(format=m3u8-aapl).m3u8

Thanks,

Safdar
[2019-11-02 12-15-39.zip](https://github.com/google/ExoPlayer/files/3800317/2019-11-02.12-15-39.zip)

**Comment by menscikov** [comment]
Just upgrade your ExoPlayer version to 2.10.0+ version.
This bug has been fixed there.

**Comment by safdarkowda** [comment]
Thanks for the update,but can you please fixed the issue in 2.9.6 because if I updated to 2.10.0 the whole download and ui is changed and it won’t be possible to change customise from scratch again because I need to deliver the application in 3 days,it would be a great help. Appreciate your help and support,thanks safdar

**Comment by tonihei** [comment]
Yes, this has likely been fixed in 2.10.

Unfortunately, we won't back port bug fixes into older version, so please try to upgrade if possible. 
Please have a look at the [Downloading page on our website](https://exoplayer.dev/downloading-media.html) to get started with the current version.
