### ISSUE TITLE
Is there a way to fetch current real timestamp of video frame when playing rtmp stream? 

### ISSUE THREAD

**Issue by caprice** [google/ExoPlayer#6616]
As title mentioned, I intent to do some sync work when playing  rtmp stream, but there is no public api like getRtmpVideoTimestamp() or video frame listener to watch the real timestamp of current video frame.

**Comment by andrewlewis** [comment]
You could try setting a `VideoFrameMetadataListener` (see #5860 and possibly also the discussion in #6576) to get the presentation timestamp of the frame about to be rendered.

I'm not sure if RTMP has a special notion of video timestamp that is different though (if so, please provide some more details), and whether this can be used to achieve the 'sync work' you refer to.
