### ISSUE TITLE
Play local aes128 encrypted mp3 file

### ISSUE THREAD

**Issue by GuybrushThreepwood** [google/ExoPlayer#662]
Hi,

I try to play a local mp3 file which is encrypted with aes128-cbc encryption with pkcs7 padding. The mp3 won't play and exoPlayer.getDuration returns -1, which means that the file is somehow corrupt I guess, because it could not be decrypted successfully. I don't get an Exception or any information in the logs though. What is the correct way to play a local aes128 encrypted mp3? (I use ExoPlayer version 1.3.3)
Here is what I do:
Iv and key:
```java
private byte[] iv = hexToBytes("..."); //32 hex symbols here as String
private byte[] key = hexToBytes("..."); //32 hex symbols here as String
```
HexToBytes function:
```java
private byte[] hexToBytes(String str) {
    if (str == null) {
        return null;
    }
    else if (str.length() < 2) {
        return null;
    }
    else {
        int len = str.length() / 2;
        byte[] buffer = new byte[len];
        for (int i = 0; i < len; i++) {
            buffer[i] = (byte) Integer.parseInt(str.substring(i * 2, i * 2 + 2), 16);
        }
        return buffer;
    }
}
```
Here is how I try to play the file:
```java
Uri uri = Uri.parse("android.resource://" + context.getPackageName() + File.separator + R.raw.track01_cbc);
DefaultBandwidthMeter bandwidthMeter = new DefaultBandwidthMeter();
String userAgent = getUserAgent(context, ...); 
DataSource dataSource = new DefaultUriDataSource(context, bandwidthMeter, userAgent);
Aes128DataSource aes128DataSource = new Aes128DataSource(dataSource, key, iv);
SampleSource sampleSource = new ExtractorSampleSource(uri, aes128DataSource, new Mp3Extractor(), RENDERER_COUNT, 5000);
MediaCodecAudioTrackRenderer audioRenderer = new MediaCodecAudioTrackRenderer(sampleSource);
exoPlayer.prepare(audioRenderer);
exoPlayer.setPlayWhenReady(true);
```

You can also find this issue on [stackoverflow] (http://stackoverflow.com/questions/31592158/play-local-aes128-cbc-encrypted-mp3-with-exoplayer)

**Comment by ojw28** [comment]
The problem is most likely because Aes128DataSource doesn't support reading from arbitrary positions in the stream. I think it should be moved to be private inside of TsChunk, given it's limited use case. I'll do that.

That aside, this use case isn't directly supported. If you can make a DataSource that will return correctly decrypted data at the offsets requested, then ExoPlayer will "just work". That's something you'll need to figure out how to do by yourself, however.

**Comment by AlirezaGhanbarinia** [comment]
I'm trying to play an encrypted local mp4 file,Exoplayer can not play the video. Would you please help me on this matter? Appreciate any help.

**Comment by ojw28** [comment]
There's no need to post the same question on three different issues. Thanks.

**Comment by mohsak** [comment]
Dears, I posted a question on Stackoverflow [http://stackoverflow.com/questions/36886879/exoplayer-play-aes-encrypted-file](url) . I am trying to play AES encrypted mp3 file hosted on a web server, I updated `DefaultHttpDataSource` open method to decrypt the stream but nothing gets played unless i change the return value to -1 but then I can't seek the song and the duration is not visible in the player screen. Can you please help ?

**Comment by AlienAsRoger** [comment]
@mohsak Hey! How does it work for you know? Could you please share your solution? I'm wondering where exactly you changed to return value to -1? I'm getting exception from ExoPlayer: UnrecognizedInputFormatException: None of the available extractors (WebmExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, TsExtractor, FlvExtractor, OggVorbisExtractor, PsExtractor, WavExtractor) could read the stream.
