### ISSUE TITLE
ffmpeg using readme in documentation C compiler test failed.

### ISSUE THREAD

**Issue by Rvldo** [google/ExoPlayer#6620]
Hello i'm using ExoPlayer for streaming, i found problem when play audio mpeg not support and i've browse and found that it because of ffmpeg and i found this readme

https://github.com/google/ExoPlayer/blob/release-v2/extensions/ffmpeg/README.md
the readme says that it currently support NDK 15c

and I use NDK 20 but it says like this

arm-linux-androideabi-gcc is unable to create an executable file.
C compiler test failed.

NDK 15c is working but many deprecated method,

and if i use android 7.1.2 its working with audio mpeg but when i use above version like android 8 or 9 the audio not working, it says in ExoPlayer Demo "media includes audio track, but none are playable by this device"

i wonder if the NDK version take effect for android version ?

Sory for bad english.

#4963

**Comment by andrewlewis** [comment]
> and if i use android 7.1.2 its working with audio mpeg but when i use above version like android 8 or 9 the audio not working, it says in ExoPlayer Demo "media includes audio track, but none are playable by this device"

The ffmpeg extension lets you include software decoders in your app, so if you're using it then audio decoding capabilities generally doesn't have to depend on the capabilities of the Android version and device. If configured correctly and playing a format which the extension supports you should get the same capabilities back to Android Jelly Bean. For more information on what level of format support to expect please see the [supported formats page](https://exoplayer.dev/supported-formats.html).

> and I use NDK 20 but it says like this
>
> arm-linux-androideabi-gcc is unable to create an executable file.
> C compiler test failed.

The build instructions on the current release branch (2.10.6) don't work if you switch to a newer NDK. The instructions on the development branch should work with NDK 20 (see [this version](https://github.com/google/ExoPlayer/tree/a4e7274/extensions/ffmpeg)). You can wait until those make it into a release, switch to using the development branch directly or try to apply the changes to the ffmpeg script and instructions from a4e7274cca0ab57f0b23bfa0251a06fae243bf94 manually.

**Comment by Rvldo** [comment]
Thank you for your reply, i really appreciate it.

**Comment by Rvldo** [comment]
Hello, @andrewlewis 
I've try your solution above but still not working.. i see the codec in VLC for audio is MPEG Audio Layer 1/2 (mpga)

but another stream audio codec MPEG AAC (mp4a) is working well..

and i try to use android version 5 to stream MPEG Audio Layer 1/2 (mpga) using ExoPlayer, working well without FFmpeg extension..

i've tried your solution above but not working..

**Comment by Rvldo** [comment]
i think my problem like this one..
https://github.com/google/ExoPlayer/issues/5204

you said that it working using the readme.
but i've tried many times not working.. i use the ExoPlayer Demo. and checkout to dev-v2
for NDK 20

**Comment by andrewlewis** [comment]
@Rvldo Using NDK r20 and following the steps in the README on Linux/Mac should work. If you get errors while following the steps in the README, please provide the error message here. If building the extension works but the stream doesn't play, make sure you have enabled the right decoder and look at logcat to see whether the extension is actually loading.

**Comment by Rvldo** [comment]
Hi @andrewlewis its working now.. 
im using NDK 15rc and i think the readme need to add some information about installation with ffmpeg.
in common_options

COMMON_OPTIONS="\
    --target-os=android \
    --disable-static \
    --enable-shared \
    --disable-doc \
    --disable-programs \
    --disable-everything \
    --disable-avdevice \
    --disable-avformat \
    --disable-swscale \
    --disable-postproc \
    --disable-avfilter \
    --disable-symver \
    --disable-swresample \
    --enable-avresample \
    --enable-decoder=vorbis \
    --enable-decoder=opus \
    --enable-decoder=flac \
    --enable-deocder=mp3 \ (i add this line)

and then im using ExoPlayer demo and change the Build Variants from withNoExtensionDebug to withExtensionDebug..

now the ffmpeg should work..

and its working..

**Comment by andrewlewis** [comment]
On the development branch we've moved these instructions into a script which should make this slightly easier (see [build_ffmpeg.sh](https://github.com/google/ExoPlayer/blob/a4e7274/extensions/ffmpeg/src/main/jni/build_ffmpeg.sh)). If the configuration commands there don't work for you (setting aside which decoders are enabled, which may vary between different users) please reply here with some more info. Thanks!

**Comment by Rvldo** [comment]
Hello @andrewlewis sorry for late reply, so u are enabling all the decoder right ? in build_ffmpeg.sh, https://github.com/google/ExoPlayer/blob/a4e7274/extensions/ffmpeg/src/main/jni/build_ffmpeg.sh here

i think it should work in my case, actually it's working but i have to go to android Build Variants and change the "withNoExtensionDebug" to "withExtensionDebug"

im using your ExoPlayer demo..

**Comment by andrewlewis** [comment]
@Rvldo The [README](https://github.com/google/ExoPlayer/blob/a4e7274/extensions/ffmpeg/README.md) explains how to enable the decoders you want to include (the part about `ENABLED_DECODERS`). We don't enable them all by default. For the demo app, yes, you need to select a build variant that includes extensions.

**Comment by Rvldo** [comment]
Yup.. but i "think maybe" you need to add the information about **build variant** 

because i successfully install the ffmpeg but it's not working until i found another solution in Google, and i need 2 weeks for searching googling everywhere :) 

maybe in README, in the bottom **note : build variant change to withExtensionDebug**
like that or something.. :+1: 

that's my opinion.. :) hehe.
