### ISSUE TITLE
When playing an HLS uri, I got null when calling player.currentTimeline.getWindow(,,).tag

### ISSUE THREAD

**Issue by hungntv** [google/ExoPlayer#6625]
I use ExoPlayer version 2.10.0

And `player.currentTimeline.getWindow(windowIndex, window, true).tag` **always returns null**

```
private inner class UampQueueNavigator(
            mediaSession: MediaSessionCompat
    ) : TimelineQueueNavigator(mediaSession) {
        private val window = Timeline.Window()
        override fun getMediaDescription(player: Player, windowIndex: Int): MediaDescriptionCompat {
            val tag = player.currentTimeline.getWindow(windowIndex, window, true).tag
            //**tag is always null**
            return tag as MediaDescriptionCompat
}
```

How can I fix it?

Someone got the same problem like me:
[https://github.com/android/uamp/issues/253](https://github.com/android/uamp/issues/253)

HLS sample:
[https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8](https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8)

**Comment by ojw28** [comment]
What are you expecting to be returned? I think it's supposed to simply return whatever tag you set when building the `HlsMediaSource`:
```
        return new HlsMediaSource.Factory(dataSourceFactory)
            .setDrmSessionManager(drmSessionManager)
            .setTag(tag)
            .createMediaSource(uri);
```
If you don't call `setTag` then `null` always being returned is expected behaviour.
