### ISSUE TITLE
Download data consumption is much higer for byte range request content's

### ISSUE THREAD

**Issue by sravan1213** [google/ExoPlayer#6626]
When we download content using byte range requests download consumption is showing 300mb for a 30 mb file. I found that in exoplayer request length is set -1 download requests, because of the server is sending entire content for each download request.

please check `readAndDiscard` function in `CacheUtil`.

Verified on [Test Asset](https://storage.googleapis.com/wvmedia/cenc/h264/tears/tears.mpd) as well. Check `content-length` in response for each segment request.

**Comment by ojw28** [comment]
I believe we already fixed this. What version are you using?

**Comment by ojw28** [comment]
It was fixed in 2.10.2, as per the release notes. See https://github.com/google/ExoPlayer/issues/5927.

**Comment by sravan1213** [comment]
Sorry for the duplicate issue. I was checking on 2.9.6. Thanks for the update. Closing this.
