### ISSUE TITLE
ExtractorSampleSource uses ReflectiveOperationException which isn't available till API 19 

### ISSUE THREAD

**Issue by IanDBird** [google/ExoPlayer#663]
The ExoPlayer documentation (and build.gradle) all state that ExoPlayer sets the minimum API version to 16. However, `ExtractorSampleSource` references the `ReflectiveOperationException` which didn't become available till API 19.

**Comment by ojw28** [comment]
This was fixed in https://github.com/google/ExoPlayer/commit/4c1fb0c9772fa76dc6e7695ee904a337cc56167c.

**Comment by IanDBird** [comment]
Sorry, I thought I was fully up to date, but look like I was running a different branch locally to what I thought.
