### ISSUE TITLE
How to enable / disable Closed Captioning?

### ISSUE THREAD

**Issue by khat33b** [google/ExoPlayer#6631]
### [REQUIRED] Searched documentation and issues
I have searched on the GitHub home page, the developer website, past issues and StackOverflow.

### [REQUIRED] Question
Please write the code on how to enable and disable closed captioning on the ExoPlayer developer website in a separate section. It is extremely difficult to figure out how to do it. Please do not direct me to the sample app as it is very difficult to figure out from the process from it. The process seems to have changed and all the answers on StackOverflow are not working. Please make the process clear on the developer website once and for all so people would not have to ask this same question again and again.

This is how I am creating the ExoPlayer instance:

```
private void initializePlayer() {
    BandwidthMeter bandwidthMeter = new
            DefaultBandwidthMeter.Builder(getContext()).build();
    TrackSelection.Factory videoTrackSelectionFactory =
            new AdaptiveTrackSelection.Factory(bandwidthMeter);
    mTrackSelector = new DefaultTrackSelector(videoTrackSelectionFactory);
    mTrackSelector.setParameters(new DefaultTrackSelector.ParametersBuilder()
            .setRendererDisabled(C.TRACK_TYPE_TEXT, false)
            .setRendererDisabled(C.TRACK_TYPE_VIDEO, false)
            .build()
    );
    mPlayer = ExoPlayerFactory.newSimpleInstance(getActivity(), mTrackSelector);
    mPlayerAdapter = new LeanbackPlayerAdapter(getActivity(), mPlayer, UPDATE_DELAY);
    mPlayerGlue = new VideoPlayerGlue(getActivity(), mPlayerAdapter);
    mPlayerGlue.setHost(new VideoSupportFragmentGlueHost(this));
    mPlayerGlue.playWhenPrepared();

    play();
}

private void play() {
    mPlayerGlue.setTitle("Title of movie");
    mPlayerGlue.setSubtitle("Subtitle of movie");
    prepareMediaForPlaying(Uri.parse(videoUrl), Uri.parse(subUrl));
    mPlayerGlue.play();
}

private void prepareMediaForPlaying(Uri mediaSourceUri, Uri subtitleUri) {
    String userAgent = Util.getUserAgent(getActivity(), "VideoPlayerGlue");
    DataSource.Factory dataSourceFactory =
            new DefaultHttpDataSourceFactory(userAgent);
    HlsMediaSource videoSource =
            new HlsMediaSource.Factory(dataSourceFactory).createMediaSource(mediaSourceUri);
    Format subtitleFormat = Format.createTextSampleFormat(
            "English Subtitles",
            MimeTypes.APPLICATION_SUBRIP,
            C.SELECTION_FLAG_DEFAULT,
            "en");
    MediaSource subtitleSource =
            new SingleSampleMediaSource.Factory(dataSourceFactory)
                    .createMediaSource(subtitleUri, subtitleFormat, C.TIME_UNSET);
    MergingMediaSource mergedSource =
            new MergingMediaSource(videoSource, subtitleSource);

    mPlayer.prepare(mergedSource);
}
```

**Comment by ojw28** [comment]
I don't think this is an issue with enabling closed captioning. I think closed captioning is probably already enabled in this case. You can verify this by adding a text listener and logging something whenever it's invoked:

```
player.addTextOutput(new TextOutput() {
    @Override
    public void onCues(List<Cue> cues) {
      // Log something here to verify that text is being output.
    }
});
```

Assuming closed captioning is already enabled, the problem is that you don't have anything in your view hierarchy to actually display the enabled captions. When using ExoPlayer's `PlayerView` component, this is taken care of for you, however I think in your case you're trying to use the leanback extension, which does not do this. I think this is a limitation of the leanback library; in that it does not provide built in support for caption rendering.

Please take a look at https://github.com/google/ExoPlayer/issues/6587, which describes how to use `SubtitleView` together with the leanback extension. Does this solve your problem?

**Comment by khat33b** [comment]
@ojw28 Using the solution at that link got me the subtitles in `onCues`. But then I encountered a new problem which I have mentioned as a [comment there](https://github.com/google/ExoPlayer/issues/6587#issuecomment-552335877). Although that solves the problem of showing the subtitles, I also wanted was a way to enable and disable subtitles on a button press. Leanback already has a button `PlaybackControlsRow.ClosedCaptioningAction` which gives a callback function in which I can toggle captions. My question was what code is required in that method to implement this feature. This is what I tried. Why do I have to use `C.TRACK_TYPE_VIDEO` for subtitles instead of `C.TRACK_TYPE_TEXT`?

```
public void toggleCaptions() {
mTrackSelector.setParameters(new DefaultTrackSelector.ParametersBuilder()
                .setRendererDisabled(C.TRACK_TYPE_VIDEO, mClosedCaptioningAction.getIndex() == PlaybackControlsRow.ClosedCaptioningAction.INDEX_OFF)
                .build()
        );
}
```

**Comment by giladna** [comment]
@khat33b 
you can debug the demo app in TrackSelectionDialog.java
you will have to investigate the behaviour of builder in the method createForTrackSelector.



```
 public static TrackSelectionDialog createForTrackSelector(
      DefaultTrackSelector trackSelector, DialogInterface.OnDismissListener onDismissListener) {
    MappedTrackInfo mappedTrackInfo =
        Assertions.checkNotNull(trackSelector.getCurrentMappedTrackInfo());
    TrackSelectionDialog trackSelectionDialog = new TrackSelectionDialog();
    DefaultTrackSelector.Parameters parameters = trackSelector.getParameters();
    trackSelectionDialog.init(
        /* titleId= */ R.string.track_selection_title,
        mappedTrackInfo,
        /* initialParameters = */ parameters,
        /* allowAdaptiveSelections =*/ true,
        /* allowMultipleOverrides= */ false,
        /* onClickListener= */ (dialog, which) -> {
          DefaultTrackSelector.ParametersBuilder builder = parameters.buildUpon();
          for (int i = 0; i < mappedTrackInfo.getRendererCount(); i++) {
            builder
                .clearSelectionOverrides(/* rendererIndex= */ i)
                .setRendererDisabled(
                    /* rendererIndex= */ i,
                    trackSelectionDialog.getIsDisabled(/* rendererIndex= */ i));
            List<SelectionOverride> overrides =
                trackSelectionDialog.getOverrides(/* rendererIndex= */ i);
            if (!overrides.isEmpty()) {
              builder.setSelectionOverride(
                  /* rendererIndex= */ i,
                  mappedTrackInfo.getTrackGroups(/* rendererIndex= */ i),
                  overrides.get(0));
            }
          }
          trackSelector.setParameters(builder);
        },
        onDismissListener);
    return trackSelectionDialog;
  }
```
