### ISSUE TITLE
Exoplayer support VTT and Subtitle srt at same aplication??

### ISSUE THREAD

**Issue by goustmk1** [google/ExoPlayer#6632]
Hello There
I'm new at Android Studio and also new to ExoPlayer and i have implement ExoPlayer to my app and for now it support only VTT or SRT with selecting proper mime.types

Question 
Does ExoPlayer support both VTT and SRT at the same application (have multiple movies with srt and vtt combined).
And if support anyone point me to the right direction.

Thank you

**Comment by ojw28** [comment]
> Does ExoPlayer support both VTT and SRT at the same application (have multiple movies with srt and vtt combined).

Yes, this is supported. When using `MergingMediaSource` as described [here](https://exoplayer.dev/media-sources.html#side-loading-a-subtitle-file), you can create and merge in as many subtitle `MediaSource`s as you like. As long as each one is created with the correct `Format`, then merging in multiple `MediaSource`s for both VTT and SRT subtitles should "just work".
