### ISSUE TITLE
DefaultLoadControl - Mismatch in Constructor and Builder behaviour 

### ISSUE THREAD

**Issue by giladna** [google/ExoPlayer#6634]
### [REQUIRED] Issue description

I have a LoadControl Settings Object which enable the app to configure the LoadControl via Builder API.

The Issue is with the
      int minBufferAudioMs,
      int minBufferVideoMs

 public static final int DEFAULT_MIN_BUFFER_MS = 15000;
 public static final int DEFAULT_MAX_BUFFER_MS = 50000;

the Definition in the constructor is : 
        /* minBufferAudioMs= */ DEFAULT_MIN_BUFFER_MS,
        /* minBufferVideoMs= */ DEFAULT_MAX_BUFFER_MS,

But in the builder when using the setBufferDurationsMs
these values are not exposed for set

      this.minBufferAudioMs = minBufferMs;
      this.minBufferVideoMs = minBufferMs;

this behaviour is not constant VS. the Constructor here the api sets them both to min!

as a result:

when creating DefaultLoadControl with Builder API (the Default works fine)

            return new DefaultLoadControl.Builder().
                    setBufferDurationsMs(
                            DEFAULT_MIN_BUFFER_MS,
                            DEFAULT_MAX_BUFFER_MS,
                            DEFAULT_BUFFER_FOR_PLAYBACK_MS,
                            DEFAULT_BUFFER_FOR_PLAYBACK_AFTER_REBUFFER_MS).
                   setBackBuffer(DEFAULT_BACK_BUFFER_DURATION_MS, DEFAULT_RETAIN_BACK_BUFFER_FROM_KEYFRAME).createDefaultLoadControl();

the result will be that the minBufferAudioMs will take same value as minBufferVideoMs

 I have a dash stream with several bitrates one of them is  0.09 mbps video bitrate and 0.06 mbps for audio

if I select the lowest  0.09 video track using track selector after 38 sec video stuck since the Exo is not downloading any chunks anymore

### [REQUIRED] Reproduction steps
create the DefaultLoadControl Via the code I shared here
play the stream (I will send url + lic to Exo mail)
switch to track with 0.09 mbps you can see that progress is not passing 38 sec due to cuenks are not downloaded

In Demo:

    DefaultBandwidthMeter dbm = new DefaultBandwidthMeter.Builder(this).build();
      DefaultLoadControl dlc = new DefaultLoadControl.Builder().
          setBufferDurationsMs(
              DEFAULT_MIN_BUFFER_MS,
              DEFAULT_MAX_BUFFER_MS,
              DEFAULT_BUFFER_FOR_PLAYBACK_MS,
              DEFAULT_BUFFER_FOR_PLAYBACK_AFTER_REBUFFER_MS).
          setBackBuffer(DEFAULT_BACK_BUFFER_DURATION_MS, DEFAULT_RETAIN_BACK_BUFFER_FROM_KEYFRAME).createDefaultLoadControl();
      player =
          ExoPlayerFactory.newSimpleInstance(
              /* context= */ this, renderersFactory, trackSelector, dlc, drmSessionManager, dbm);

### [REQUIRED] Link to test content
sending in mail demo entry

### [REQUIRED] Version of ExoPlayer being used
2.6.10
### [REQUIRED] Device(s) and version(s) of Android being used
Pixel 3 Android 10

**Comment by ojw28** [comment]
This is intentional. Note that `DEFAULT_MIN_BUFFER_MS` is documented to say:

> This value is only applied to playbacks without video.

And `DEFAULT_MAX_BUFFER_MS` is documented to say:

> this is also the default minimum duration of media that the player will attempt to ensure is buffered.

If you call `setBufferDurationsMs` it's assumed that you know what you're doing, and so both are set to the same value.

I'm not sure what the issue is you're seeing where playback gets stuck, but I don't think it's related to the way you're setting up the `DefaultLoadControl`. The stream provided returns a HTTP 403 error for me, so we're unable to reproduce the problem. Please provide a working test stream if you want us to take a look.

Marking as "need more information" because we need a working test stream to investigate further.

@tonihei - As an aside, do you think it's worth adding a second `setBufferDurationsMs` method that takes separate minimums for audio and video?

**Comment by giladna** [comment]
@ojw28  thanks
It is customer stream I am not sure I can change the geo block definition
It is working from my end I will send logs and charles capture on the demo app

**Comment by ojw28** [comment]
What GEO does the stream work in? We may be able to proxy.

**Comment by giladna** [comment]
> What GEO does the stream work in? We may be able to proxy.

Hi
I have sent more information via mail
It should work for India
Thanks

**Comment by giladna** [comment]
@tonihei @ojw28 

could you give it a look please?

**Comment by giladna** [comment]
@ojw28  media is expired 
I will resend it

**Comment by ojw28** [comment]
Sorry for the delayed response. I tried to VPN via both of the suggested countries, but neither of them worked. I see HTTP 404 in both cases.
