### ISSUE TITLE
Exo Player cannot play media urls with spaces in segments

### ISSUE THREAD

**Issue by shashank915** [google/ExoPlayer#6638]
Below is my MPD file I am using to play in Exo player: 
[d4a35346-bfa4-4ad8-9f09-a60333ce4f39-Excreatory System (Plants and Animals)_1.txt](https://github.com/google/ExoPlayer/files/3829910/d4a35346-bfa4-4ad8-9f09-a60333ce4f39-Excreatory.System.Plants.and.Animals._1.txt)

This works fine in Android Version 6+(Marshmellow) but the player is not able to fetch video segments in lower android versions(below Marshmellow).

**Comment by ojw28** [comment]
Preferably, you should avoid putting spaces in URLs. Spaces should be encoded as `%20`, as per https://github.com/google/ExoPlayer/issues/5983#issuecomment-527832552.

**Comment by ojw28** [comment]
Hm. We should possibly look at whether we should be doing this encoding automatically.

**Comment by ojw28** [comment]
I took a look at the DASH specification, and it appears to mandate that you encode spaces as `%20` in URLs specified within the manifest. In particular, it refers to RFC 3986 and its definition of `<absolute-URI>` and `<relative-ref>`. If you dig far enough down into that RFC, the URL segments are sequences of `pchar`, where `pchar` is defined as:

```
pchar         = unreserved / pct-encoded / sub-delims / ":" / "@"
query         = *( pchar / "/" / "?" )
fragment      = *( pchar / "/" / "?" )
pct-encoded   = "%" HEXDIG HEXDIG
unreserved    = ALPHA / DIGIT / "-" / "." / "_" / "~"
reserved      = gen-delims / sub-delims
gen-delims    = ":" / "/" / "?" / "#" / "[" / "]" / "@"
sub-delims    = "!" / "$" / "&" / "'" / "(" / ")"
                 / "*" / "+" / "," / ";" / "="
```

So I think it's reasonable to say this is bad media, and that the spaces should be encoded as per my original response.
