### ISSUE TITLE
IMA ads playback in a recyclerview

### ISSUE THREAD

**Issue by idandamri** [google/ExoPlayer#6639]
Hi, 
I am using a SimpleExoPlayer with PlayerView under 'com.google.android.exoplayer:exoplayer:2.8.2'.
I am using it in other places in the app as well but never inside an item inside a recyclerview and maybe that should be used differently?
because for some reason I hear the volume, I see the ad buttons and the controllers but I don't see the video nor the ad video - it looks like an empty container.

**Comment by marcbaechinger** [comment]
It's hard to say what the problem is without any further information. 

I think the easiest way is to set the player on the PlayerView when it is attached/detached from the recyclerview. You probably want to start playback only when it enters the visible area and pause playback when it leaves the visible area. 

For this to work you need to track when your UI elements are created, added to the recyclerview and appear on the screen. 

Usage of SimpleExoPlayer/PlayerView is the same but the app needs to take care of when to initalize/release play/pause.

**Comment by idandamri** [comment]
First of all thank you for your fast reply.
I agree about what you are saying. I don't care for now about the place of
the item (if it's visible or not). The thing is that it is the first item,
I am waiting for it to show the ad and video. It loaded the ad and start
playing but I am seeing the button for "learn more" and "skip" but not the
video. When the ad video is done (skipped or ended) the video starts with
sound but without video. Did you ever hear of that?

**Comment by marcbaechinger** [comment]
Are you using the IMA extension to show ads?

In any case, can you please take a bug report and upload it? I need to know what is going on in the player. Best would be to add an event logger, so I can see in the logs what is going on

```
player.addAnalyticsListener(new EventLogger(/* trackSelector= */ null));
```

**Comment by idandamri** [comment]
I am actually.
I will do.

**Comment by idandamri** [comment]
how do I pull the bug report?

**Comment by idandamri** [comment]
2019-11-11 15:05:51.849 20906-20942/? E/chromium: [ERROR:tile_manager.cc(779)] WARNING: tile memory limits exceeded, some content may not draw


 I see it writes this error in the log, is it related?

**Comment by marcbaechinger** [comment]
To do a bug report just let the player do what it does wrong, then after it do a

adb bugreport

this creates a zip file which you can upload here.

That's probably quickest. Else there are other ways to capture a bugreport: https://developer.android.com/studio/debug/bug-report

**Comment by marcbaechinger** [comment]
2019-11-11 15:05:51.849 20906-20942/? E/chromium: [ERROR:tile_manager.cc(779)] WARNING: tile memory limits exceeded, some content may not draw

is probably related. That could be the webview used by IMA. Bugreport will tell. :)

**Comment by idandamri** [comment]
I am not able to extract the bug report. is there any other way?

**Comment by idandamri** [comment]
here is the bug report
[bugreport-2019-11-11-16-21-38.zip](https://github.com/google/ExoPlayer/files/3831742/bugreport-2019-11-11-16-21-38.zip)

**Comment by marcbaechinger** [comment]
Thanks for the bug report.

I think I'd recommend to move to the most recent ExoPlayer version (you are using 2.8.2). The new ExoPlayer IMA extension will use the most recent IMA Ad SDK. It seems to me that an outdated Ad SDK is causing troubles. Upgrading probably helps.

Are you sure ads play in your app without RecyclerView? It appears to me that the problem is not related to recyclerview.

The logs shows, that shortly after IMA is complaining, ExoPlayer transitions into the IDLE state. This is cause by a playback error or, more likely for our case, by something calling player.stop(). According to the line which says "Destroying NativeVideoDisplay" I think this is triggered by the SDK telling ExoPlayer to stop. 

```
11-11 16:21:58.014 u0_a6  2015  2015 D EventLogger: positionDiscontinuity [12.56, 0.00, window=0, period=0, AD_INSERTION]
11-11 16:21:58.016 u0_a6  2015  2015 D EventLogger: tracksChanged [12.56, 0.00, window=0, period=0, []]
11-11 16:21:58.031 u0_a6  2015  2015 I SDK_LOG:ima.vast.VideoAdEventTracker: dispatching event engagedView
11-11 16:21:58.035 u0_a6  2015  2015 I chromium: [INFO:CONSOLE(993)] " [ 12.235s] [ima.vast.VideoAdEventTracker] dispatching event engagedView ", source: https://imasdk.googleapis.com/native/core/3.176.2/native_bridge_debug__en.js (993)
11-11 16:21:58.037 u0_a6  2015  2015 I chromium: [INFO:CONSOLE(993)] " [ 12.248s] [ima.vast.VideoAdEventTracker] dispatching event complete ", source: https://imasdk.googleapis.com/native/core/3.176.2/native_bridge_debug__en.js (993)
11-11 16:21:58.038 u0_a6  2015  2015 D EventLogger: videoSizeChanged [12.58, 0.00, window=0, period=0, 1024, 576]
11-11 16:21:58.048 u0_a6  2015  2015 I chromium: [INFO:CONSOLE(993)] " [ 12.262s] [UrlReporter] Reporting urls for event : complete ", source: https://imasdk.googleapis.com/native/core/3.176.2/native_bridge_debug__en.js (993)
11-11 16:21:58.082 u0_a6  2015  2015 I SDK_LOG:ima.vast.VideoAdEventTracker: dispatching event complete
11-11 16:21:58.099 u0_a6  2015  2015 I SDK_LOG:UrlReporter: Reporting urls for event : complete
====> 11-11 16:21:58.100 u0_a6  2015  2015 I chromium: [INFO:CONSOLE(161)] "Uncaught TypeError: Cannot read property 'h' of undefined", source: https://imasdk.googleapis.com/native/core/3.176.2/native_bridge_debug__en.js (161)
====> 11-11 16:21:58.136 u0_a6  2015  2015 W IMASDK  : Invalid internal message, ignoring. Please make sure the Google IMA SDK library is up to date. Message: gmsg://afma.google.com/videoDisplay?**type=unload&sid=f3ecdeec-d231-4730-bdba-4c4fbe3b0ba5&dt=1573482118119
====>  11-11 16:21:58.141 u0_a6  2015  2015 D SDK_DEBUG: Destroying NativeVideoDisplay
11-11 16:21:58.148 u0_a6  2015  2015 D SurfaceView: hide() Surface(name=SurfaceView - com.scores365/com.scores365.gameCenter.GameCenterBaseActivity@70c32a2@3[2015])/@0xdcd4870 true false android.view.SurfaceView{70c32a2 G.E...... ......I. 0,0-1080,516}
11-11 16:21:58.149 u0_a6  2015  2015 D SurfaceView: surfaceDestroyed callback.size 1 #3 android.view.SurfaceView{70c32a2 G.E...... ......I. 0,0-1080,516}
11-11 16:21:58.179 u0_a6  2015  2015 D SurfaceView: destroy() Surface(name=SurfaceView - com.scores365/com.scores365.gameCenter.GameCenterBaseActivity@70c32a2@3[2015])/@0xdcd4870 android.view.SurfaceView{70c32a2 G.E...... ......I. 0,0-1080,516}
11-11 16:21:58.181 u0_a6  2015  2015 D EventLogger: state [12.73, 0.00, window=0, period=0, true, IDLE]
```

**Comment by idandamri** [comment]
![image](https://user-images.githubusercontent.com/15670691/68654520-ca61c780-0536-11ea-96a0-94c3a8e4b829.png)

It does work well in other places in the app where it is not in a recyclerview.
I am using 2.8.2

**Comment by idandamri** [comment]
whenever I try using the 2.10.7 version the build gets stuck and I can't even get to the point of install!

**Comment by marcbaechinger** [comment]
I'm pretty sure the build works once your code has been adjusted to possible API changes since 2.8.2.

**Comment by idandamri** [comment]
Ok got it to build finally.

now we get the following error which is not from the code we write.

```
2019-11-13 16:15:23.803 26432-26432/com.scores365 E/RecyclerView: No adapter attached; skipping layout
2019-11-13 16:15:23.889 26432-26432/com.scores365 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.scores365, PID: 26432
    java.lang.IllegalStateException: Set player using adsLoader.setPlayer before preparing the player.
        at com.google.android.exoplayer2.util.Assertions.checkState(Assertions.java:95)
        at com.google.android.exoplayer2.ext.ima.ImaAdsLoader.start(ImaAdsLoader.java:592)
        at com.google.android.exoplayer2.source.ads.AdsMediaSource.lambda$prepareSourceInternal$0$AdsMediaSource(AdsMediaSource.java:220)
        at com.google.android.exoplayer2.source.ads.-$$Lambda$AdsMediaSource$zcXBZahV9F-k_KJACPO-bl_WWX0.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6806)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```

The problem is here:
    **java.lang.IllegalStateException: Set player using adsLoader.setPlayer before preparing the player.**

we caught it inside checkState function inside Assertions class which is not our code but exoplayers code.

any thoughts?

**Comment by ojw28** [comment]
The error message pretty clearly tells you what's wrong, doesn't it? I.e. Your code is creating an `AdsLoader` and is not calling `adsLoader.setPlayer` before preparing the player. So you should do that, to fix it. The demo app [does this here](https://github.com/google/ExoPlayer/blob/r2.10.7/demos/main/src/main/java/com/google/android/exoplayer2/demo/PlayerActivity.java#L572).
