### ISSUE TITLE
HLS - Unexpected End of Stream & Spurious Audio Timestamp

### ISSUE THREAD

**Issue by Mackqrenc** [google/ExoPlayer#664]
Hello @ojw28 

You were right, it was a problem with the provider on my previous issue. It is fixed now. However, I can play the stream very well but sometimes it stops again (no image, no sound. Completely freezes) with the messages (These happen repeatedly when this issue shows itself, but the main one is the first screenshot's log) stated below:

![screen shot 2015-07-27 at 16 02 31](https://cloud.githubusercontent.com/assets/9883323/8906648/ec266a12-3478-11e5-8462-0498c1f998c5.png)

![screen shot 2015-07-27 at 15 12 39](https://cloud.githubusercontent.com/assets/9883323/8906663/fb44956e-3478-11e5-909c-e3f7ff73be40.png)

![screen shot 2015-07-27 at 15 28 39](https://cloud.githubusercontent.com/assets/9883323/8906670/0641c3e2-3479-11e5-9974-2849c77a3a52.png)

**Comment by haitech** [comment]
You have already got answer in #659. If you look into your logs its your connection dropping out, "java.net.SocketTimeoutException".
The source the problem may be your WiFi signal is bad or something similar to that.
