### ISSUE TITLE
SeekPosition resolving issue

### ISSUE THREAD

**Issue by yamagata1037** [google/ExoPlayer#6641]
`timeline.getPeriod(periodIndex, period)` at [ExoPlayerImplInternal.java#L1474](https://github.com/google/ExoPlayer/blob/bef130ad17f11ab3997548653f2466e50bd6eb27/library/core/src/main/java/com/google/android/exoplayer2/ExoPlayerImplInternal.java#L1474) always gives an ArrayIndexOutOfBoundsException as `periodIndex == -1` at this point.
I think `timeline.getPeriodByUid(periodUid, period)` should be called instead to get the position of the subsequent period.
Thank you.

**Comment by marcbaechinger** [comment]
Thanks! We will provide a fix soon. 

Out of my personal curiosity: did you hit this with a live stream or a ConcatentatingMediaSource?

**Comment by yamagata1037** [comment]
With a ConcatenatingMediaSource.
