### ISSUE TITLE
Teletext

### ISSUE THREAD

**Issue by tipoc123** [google/ExoPlayer#6642]
### [REQUIRED] Issue description
Exoplayer doesn't show Teletext (application/cea-608).

### [REQUIRED] Reproduction steps
Play multicast.

Command:
```
multicat -uU envivio.ts 224.1.1.1:1234
```

### [REQUIRED] Link to test content
https://yadi.sk/d/sYH5XC-xZC1C7Q

### [REQUIRED] A full bug report captured from the device
[bugreport.txt.zip](https://github.com/google/ExoPlayer/files/3836852/bugreport.txt.zip)

### [REQUIRED] Version of ExoPlayer being used
2.10.2

### [REQUIRED] Device(s) and version(s) of Android being used
STB Rockchip RK3229
Android 7.1.2

**Comment by AquilesCanta** [comment]
ExoPlayer does not support teletext. The 608 track you see is a closed caption track that the TsExtractor creates by default for historic reasons, but it is not related to teletext. For DVB teletext support, please track #7220.
