### ISSUE TITLE
Buffering behaviour on pausing & resuming a live stream

### ISSUE THREAD

**Issue by tvanlaerhoven** [google/ExoPlayer#6644]
### [REQUIRED] Searched documentation and issues
I checked the documentation and existing related questions.

### [REQUIRED] Question
My intention is to add the ability to pause a live stream to our player. The stream could be paused for a predefined maximum time, after which play-out would resume from the buffer.

I configured ExoPlayer's LoadControl with a minBufferMs and maxBufferMs of, in this case, 30s. 

```
DefaultLoadControl.Builder defaultLoadControlBuilder = new DefaultLoadControl.Builder();
                    defaultLoadControlBuilder.setAllocator(allocator);
                    defaultLoadControlBuilder.setBufferDurationsMs(30000, 30000, 2500, 5000);
                    defaultLoadControlBuilder.setTargetBufferBytes(-1);
                    defaultLoadControlBuilder.setPrioritizeTimeOverSizeThresholds(true);
                    DefaultLoadControl defaultLoadControl = defaultLoadControlBuilder.createDefaultLoadControl();
```

I would expect the player to have a 30s buffer at all time, so when pausing the live stream for at most 30s, the player would stream from one end of the buffer, while buffering live chunks at the other end. 

However, when streaming from the buffer after resuming the player, at one point the totalBufferedDuration length seems to drop and a BehindLiveWindowException is thrown.
A log of buffer duration and player position would look like this (a log line is written every two seconds, triggered by the onTimeLineChanged event):

1. When starting the live stream, the buffered duration increases as expected:

```
bufferedPosition: 2143, totalBufferedDuration: 159, currentPosition: 1984
bufferedPosition: 1519, totalBufferedDuration: 1519, currentPosition: 0
bufferedPosition: 5989, totalBufferedDuration: 8247, currentPosition: -2258
bufferedPosition: 9628, totalBufferedDuration: 10715, currentPosition: -1087
bufferedPosition: 11984, totalBufferedDuration: 12942, currentPosition: -959
bufferedPosition: 13119, totalBufferedDuration: 14043, currentPosition: -924
bufferedPosition: 13994, totalBufferedDuration: 14987, currentPosition: -994
bufferedPosition: 14668, totalBufferedDuration: 15669, currentPosition: -1001
bufferedPosition: 14623, totalBufferedDuration: 15619, currentPosition: -996
bufferedPosition: 14799, totalBufferedDuration: 15531, currentPosition: -732
bufferedPosition: 16793, totalBufferedDuration: 17686, currentPosition: -893
bufferedPosition: 17748, totalBufferedDuration: 18729, currentPosition: -981
bufferedPosition: 17583, totalBufferedDuration: 18553, currentPosition: -970
bufferedPosition: 17759, totalBufferedDuration: 18722, currentPosition: -963
```

2. Then, if I pause the player, the totalBufferedDuration increases to the 30s I set, while the bufferPosition moves to the front of the buffer, as expected:

```
bufferedPosition: 18473, totalBufferedDuration: 20730, currentPosition: -2257
bufferedPosition: 17989, totalBufferedDuration: 22251, currentPosition: -4262
bufferedPosition: 20783, totalBufferedDuration: 27050, currentPosition: -6267
bufferedPosition: 20799, totalBufferedDuration: 29050, currentPosition: -8251
bufferedPosition: 19994, totalBufferedDuration: 30251, currentPosition: -10257
bufferedPosition: 17989, totalBufferedDuration: 30251, currentPosition: -12262
bufferedPosition: 15984, totalBufferedDuration: 30251, currentPosition: -14267
bufferedPosition: 14000, totalBufferedDuration: 30251, currentPosition: -16251
bufferedPosition: 11994, totalBufferedDuration: 30251, currentPosition: -18257
bufferedPosition: 9989, totalBufferedDuration: 30251, currentPosition: -20262
bufferedPosition: 7984, totalBufferedDuration: 30251, currentPosition: -22267
bufferedPosition: 6000, totalBufferedDuration: 30251, currentPosition: -24251
bufferedPosition: 3994, totalBufferedDuration: 30251, currentPosition: -26257
```

3. Next, while the player resumes the bufferedPosition remains in the front of the buffer, and the 
totalBufferedDuration remains somewhat constant around 30s:

```
bufferedPosition: 2679, totalBufferedDuration: 30004, currentPosition: -27326
bufferedPosition: 2153, totalBufferedDuration: 29422, currentPosition: -27269
bufferedPosition: 2468, totalBufferedDuration: 29835, currentPosition: -27367
bufferedPosition: 2143, totalBufferedDuration: 29595, currentPosition: -27453
bufferedPosition: 2000, totalBufferedDuration: 29420, currentPosition: -27420
bufferedPosition: 773, totalBufferedDuration: 28166, currentPosition: -27393
bufferedPosition: 1428, totalBufferedDuration: 28793, currentPosition: -27366
bufferedPosition: 1863, totalBufferedDuration: 29247, currentPosition: -27384
bufferedPosition: 1979, totalBufferedDuration: 29277, currentPosition: -27299
bufferedPosition: 1994, totalBufferedDuration: 29346, currentPosition: -27352
bufferedPosition: 1428, totalBufferedDuration: 28739, currentPosition: -27311
bufferedPosition: 1143, totalBufferedDuration: 28328, currentPosition: -27185
bufferedPosition: -247, totalBufferedDuration: 28774, currentPosition: -29021
bufferedPosition: 1433, totalBufferedDuration: 28676, currentPosition: -27243
bufferedPosition: 1989, totalBufferedDuration: 29276, currentPosition: -27288
bufferedPosition: 2243, totalBufferedDuration: 29578, currentPosition: -27335
```

4. This is the expected behaviour. It typically holds for a few minutes, after which the buffer totalBufferedDuration steeply drops below zero:

```
bufferedPosition: -11, totalBufferedDuration: 28902, currentPosition: -28914
bufferedPosition: -277, totalBufferedDuration: 28635, currentPosition: -28912
bufferedPosition: -561, totalBufferedDuration: 28317, currentPosition: -28878
bufferedPosition: -1367, totalBufferedDuration: 27491, currentPosition: -28859
bufferedPosition: -2011, totalBufferedDuration: 26881, currentPosition: -28892
bufferedPosition: -2737, totalBufferedDuration: 24568, currentPosition: -27305
bufferedPosition: -4241, totalBufferedDuration: 24322, currentPosition: -28563
bufferedPosition: -6006, totalBufferedDuration: 22856, currentPosition: -28862
bufferedPosition: -8011, totalBufferedDuration: 20842, currentPosition: -28853
bufferedPosition: -10016, totalBufferedDuration: 18619, currentPosition: -28635
bufferedPosition: -12000, totalBufferedDuration: 16558, currentPosition: -28558
bufferedPosition: -14006, totalBufferedDuration: 14845, currentPosition: -28851
bufferedPosition: -16011, totalBufferedDuration: 12835, currentPosition: -28847
bufferedPosition: -18016, totalBufferedDuration: 10840, currentPosition: -28856
bufferedPosition: -20000, totalBufferedDuration: 8586, currentPosition: -28586
bufferedPosition: -22006, totalBufferedDuration: 5911, currentPosition: -27917
bufferedPosition: -24011, totalBufferedDuration: 4604, currentPosition: -28615
bufferedPosition: -26016, totalBufferedDuration: 2635, currentPosition: -28651
bufferedPosition: -28000, totalBufferedDuration: 829, currentPosition: -28829
``` 

5. Finally, a BehindLiveWindowException is thrown and the player is re-initialized, continuing live play-out.

So my question is what triggers this buffer behavior, and how can I fix it to get the desired result?

I was not sure how the bufferPosition could drop this far below zero, but I guess this value is just (totalBufferedDuration - currentPosition). So a gap between the buffer and live position is created, logically triggering the BehindLiveWindowException.

A visualization of the buffer timeline (my interpretation at least) would look like this:

```
(b = bufferPosition; l= live position; [] is the buffer)
__[b--------]l_________
___[b--------]l________
____[b--------]l_______
_____[b--------]l______
______[b--------]l_____
...
__[b--------]l_________
___[b--------]l________
_____[b-------]l_______
______[b------]_l______
_______[b_----]__l_____
...
__________[b]________l_ => BehindLiveWindowException
```

**Comment by marcbaechinger** [comment]
It seems like the player has fallen behind the live window before step 4. So when the player resumes, there is no way to load data to further maintain the buffer.

At 4 it then  just plays out the rest of the buffer (totalBufferedDuration is decreasing) and then when the buffer is empty it throws because it is behind the live window and can't continue loading data from where it wants to. The chunks on the server are not available anymore so there is no way to fill the gap between the end of the buffer and the chunks available on the server.

This seems to work as it should. 

> My intention is to add the ability to pause a live stream to our player. The stream could be 
> paused for a predefined maximum time, after which play-out would resume from the buffer.

As soon as the currentPosition is farther behind than the duration of the live window, the player falls behind the live window if it wants start to load again.

**Comment by tvanlaerhoven** [comment]
> It seems like the player has fallen behind the live window before step 4. So when the player resumes, there is no way to load data to further maintain the buffer.

When resuming, the player can keep on streaming for several minutes. I also see it continuing to buffer. So it's not just playing the buffer it has creating while paused, the buffer is still being filled after resuming.

Is the "live window" determined by the stream server's manifest, or can this be set client-side? The manifest indicates a timeShiftBufferDepth of PT30S.

In addition, I've set the LoadControl's targetBufferSize to a large number (200Mb) to make sure it can fit the 3mins buffer and `DefaultLoadControl.shouldContinueLoading ` always returns `true`. During the paused state, the `totalBytesAllocated` keeps correctly increasing. It is only after resuming that the buffer size decreases. I am using the DefaultAllocator, but I do not see the mechanism that triggers this.

**Comment by marcbaechinger** [comment]
I guess after resuming, the player is very close to be behind the live window. It's kind of living on the edge :)

Like here:
```
bufferedPosition: 1143, totalBufferedDuration: 28328, currentPosition: -27185
bufferedPosition: -247, totalBufferedDuration: 28774, currentPosition: -29021
bufferedPosition: 1433, totalBufferedDuration: 28676, currentPosition: -27243
```
My understanding is the following: Let's say the currentPosition is at -29000 (it's 29 seconds behind the live edge) and we have a full buffer of 29500, the buffered position results in being 500. If now downloading data is slower than real time for any reason (totalBufferedDuration decreases), while the position is constantly -29000, the buffered position falls below zero. Buffer and live window do not overlap anymore, because the live window advances at real time the nexts bytes which need to be downloaded may fall behind the live window and the buffer is played out. Does this make sense?

The live window is defined by the server and it is declared in the manifest. It is the duration of media from the live edge, which is kept on the server for downloading before being removed. Chunks which are not in the declared live window, can't be downloaded anymore.
