### ISSUE TITLE
problem with noname Chinese tablet rk30sdk

### ISSUE THREAD

**Issue by rogotulka** [google/ExoPlayer#665]
I tested demo samples for HLS on this device (API 4.2.2, kernel version 3.0.36+ gonglvlv@ubuntu1 #848) and got freeze display after several seconds playing for example Apple master playlist, but in my log I have event  V/EventLogger﹕ loadStart.
It is same behaviour with Senkatel_T9702 - (API 4.1.1 kernel version 3.0.8+ )
May be it would be useful info.

Log: 
07-27 17:32:26.523  14659-14659/? D/dalvikvm﹕ Not late-enabling CheckJNI (already on)
07-27 17:32:26.713  14659-14659/com.google.android.exoplayer.demo I/dalvikvm﹕ Could not find method android.media.MediaCodecInfo$CodecCapabilities.isFeatureSupported, referenced from method com.google.android.exoplayer.MediaCodecUtil.isAdaptiveV19
07-27 17:32:26.713  14659-14659/com.google.android.exoplayer.demo W/dalvikvm﹕ VFY: unable to resolve virtual method 86: Landroid/media/MediaCodecInfo$CodecCapabilities;.isFeatureSupported (Ljava/lang/String;)Z
07-27 17:32:26.713  14659-14659/com.google.android.exoplayer.demo D/dalvikvm﹕ VFY: replacing opcode 0x6e at 0x0002
07-27 17:32:26.713  14659-14659/com.google.android.exoplayer.demo I/dalvikvm﹕ Could not find method android.media.MediaCodecInfo$CodecCapabilities.getVideoCapabilities, referenced from method com.google.android.exoplayer.MediaCodecUtil.isSizeAndRateSupportedV21
07-27 17:32:26.713  14659-14659/com.google.android.exoplayer.demo W/dalvikvm﹕ VFY: unable to resolve virtual method 85: Landroid/media/MediaCodecInfo$CodecCapabilities;.getVideoCapabilities ()Landroid/media/MediaCodecInfo$VideoCapabilities;
07-27 17:32:26.713  14659-14659/com.google.android.exoplayer.demo D/dalvikvm﹕ VFY: replacing opcode 0x6e at 0x0019
07-27 17:32:26.853  14659-14659/com.google.android.exoplayer.demo D/libEGL﹕ loaded /vendor/lib/egl/libEGL_POWERVR_SGX540_130.so
07-27 17:32:26.863  14659-14659/com.google.android.exoplayer.demo D/libEGL﹕ loaded /vendor/lib/egl/libGLESv1_CM_POWERVR_SGX540_130.so
07-27 17:32:26.863  14659-14659/com.google.android.exoplayer.demo D/libEGL﹕ loaded /vendor/lib/egl/libGLESv2_POWERVR_SGX540_130.so
07-27 17:32:26.933  14659-14659/com.google.android.exoplayer.demo D/OpenGLRenderer﹕ Enabling debug mode 0
07-27 17:32:26.933  14659-14659/com.google.android.exoplayer.demo W/HardwareRenderer﹕ Backbuffer cannot be preserved
07-27 17:32:31.063  14659-14659/com.google.android.exoplayer.demo E/dalvikvm﹕ Could not find class 'android.view.accessibility.CaptioningManager', referenced from method com.google.android.exoplayer.demo.PlayerActivity.getUserCaptionFontScaleV19
07-27 17:32:31.063  14659-14659/com.google.android.exoplayer.demo W/dalvikvm﹕ VFY: unable to resolve check-cast 98 (Landroid/view/accessibility/CaptioningManager;) in Lcom/google/android/exoplayer/demo/PlayerActivity;
07-27 17:32:31.063  14659-14659/com.google.android.exoplayer.demo D/dalvikvm﹕ VFY: replacing opcode 0x1f at 0x0006
07-27 17:32:31.063  14659-14659/com.google.android.exoplayer.demo E/dalvikvm﹕ Could not find class 'android.view.accessibility.CaptioningManager', referenced from method com.google.android.exoplayer.demo.PlayerActivity.getUserCaptionStyleV19
07-27 17:32:31.063  14659-14659/com.google.android.exoplayer.demo W/dalvikvm﹕ VFY: unable to resolve check-cast 98 (Landroid/view/accessibility/CaptioningManager;) in Lcom/google/android/exoplayer/demo/PlayerActivity;
07-27 17:32:31.063  14659-14659/com.google.android.exoplayer.demo D/dalvikvm﹕ VFY: replacing opcode 0x1f at 0x0006
07-27 17:32:31.093  14659-14659/com.google.android.exoplayer.demo W/dalvikvm﹕ VFY: unable to resolve instance field 42
07-27 17:32:31.093  14659-14659/com.google.android.exoplayer.demo D/dalvikvm﹕ VFY: replacing opcode 0x52 at 0x0002
07-27 17:32:31.093  14659-14659/com.google.android.exoplayer.demo I/dalvikvm﹕ Could not find method android.view.accessibility.CaptioningManager$CaptionStyle.hasForegroundColor, referenced from method com.google.android.exoplayer.text.CaptionStyleCompat.createFromCaptionStyleV21
07-27 17:32:31.093  14659-14659/com.google.android.exoplayer.demo W/dalvikvm﹕ VFY: unable to resolve virtual method 263: Landroid/view/accessibility/CaptioningManager$CaptionStyle;.hasForegroundColor ()Z
07-27 17:32:31.093  14659-14659/com.google.android.exoplayer.demo D/dalvikvm﹕ VFY: replacing opcode 0x6e at 0x0002
07-27 17:32:31.093  14659-14659/com.google.android.exoplayer.demo I/dalvikvm﹕ DexOpt: unable to optimize instance field ref 0x0027 at 0x04 in Lcom/google/android/exoplayer/text/CaptionStyleCompat;.createFromCaptionStyleV19
07-27 17:32:31.093  14659-14659/com.google.android.exoplayer.demo I/dalvikvm﹕ DexOpt: unable to optimize instance field ref 0x0029 at 0x07 in Lcom/google/android/exoplayer/text/CaptionStyleCompat;.createFromCaptionStyleV19
07-27 17:32:31.103  14659-14659/com.google.android.exoplayer.demo I/dalvikvm﹕ DexOpt: unable to optimize instance field ref 0x0028 at 0x09 in Lcom/google/android/exoplayer/text/CaptionStyleCompat;.createFromCaptionStyleV19
07-27 17:32:31.103  14659-14659/com.google.android.exoplayer.demo I/dalvikvm﹕ DexOpt: unable to optimize instance field ref 0x002a at 0x08 in Lcom/google/android/exoplayer/text/CaptionStyleCompat;.createFromCaptionStyleV21
07-27 17:32:31.103  14659-14659/com.google.android.exoplayer.demo I/dalvikvm﹕ DexOpt: unable to optimize instance field ref 0x0027 at 0x10 in Lcom/google/android/exoplayer/text/CaptionStyleCompat;.createFromCaptionStyleV21
07-27 17:32:31.103  14659-14659/com.google.android.exoplayer.demo I/dalvikvm﹕ DexOpt: unable to optimize instance field ref 0x002b at 0x18 in Lcom/google/android/exoplayer/text/CaptionStyleCompat;.createFromCaptionStyleV21
07-27 17:32:31.103  14659-14659/com.google.android.exoplayer.demo I/dalvikvm﹕ DexOpt: unable to optimize instance field ref 0x0029 at 0x20 in Lcom/google/android/exoplayer/text/CaptionStyleCompat;.createFromCaptionStyleV21
07-27 17:32:31.103  14659-14659/com.google.android.exoplayer.demo I/dalvikvm﹕ DexOpt: unable to optimize instance field ref 0x0028 at 0x28 in Lcom/google/android/exoplayer/text/CaptionStyleCompat;.createFromCaptionStyleV21
07-27 17:32:31.153  14659-14663/com.google.android.exoplayer.demo D/dalvikvm﹕ GC_CONCURRENT freed 166K, 5% free 4329K/4528K, paused 5ms+9ms, total 33ms
07-27 17:32:31.203  14659-14659/com.google.android.exoplayer.demo I/ExoPlayerImpl﹕ Init 1.4.1
07-27 17:32:31.213  14659-14659/com.google.android.exoplayer.demo D/EventLogger﹕ start [0]
07-27 17:32:31.213  14659-14659/com.google.android.exoplayer.demo D/EventLogger﹕ state [0.00, false, P]
07-27 17:32:31.223  14659-14659/com.google.android.exoplayer.demo D/EventLogger﹕ state [0.01, true, P]
07-27 17:32:31.223  14659-14747/com.google.android.exoplayer.demo I/dalvikvm﹕ Could not find method android.os.Trace.beginSection, referenced from method com.google.android.exoplayer.util.TraceUtil.beginSectionV18
07-27 17:32:31.223  14659-14747/com.google.android.exoplayer.demo W/dalvikvm﹕ VFY: unable to resolve static method 178: Landroid/os/Trace;.beginSection (Ljava/lang/String;)V
07-27 17:32:31.223  14659-14747/com.google.android.exoplayer.demo D/dalvikvm﹕ VFY: replacing opcode 0x71 at 0x0000
07-27 17:32:31.223  14659-14747/com.google.android.exoplayer.demo I/dalvikvm﹕ Could not find method android.os.Trace.endSection, referenced from method com.google.android.exoplayer.util.TraceUtil.endSectionV18
07-27 17:32:31.223  14659-14747/com.google.android.exoplayer.demo W/dalvikvm﹕ VFY: unable to resolve static method 179: Landroid/os/Trace;.endSection ()V
07-27 17:32:31.223  14659-14747/com.google.android.exoplayer.demo D/dalvikvm﹕ VFY: replacing opcode 0x71 at 0x0000
07-27 17:32:31.293  14659-14659/com.google.android.exoplayer.demo W/HardwareRenderer﹕ Backbuffer cannot be preserved
07-27 17:32:31.743  14659-14663/com.google.android.exoplayer.demo D/dalvikvm﹕ GC_CONCURRENT freed 217K, 6% free 4509K/4756K, paused 2ms+4ms, total 22ms
07-27 17:32:31.833  14659-14659/com.google.android.exoplayer.demo I/OMXClient﹕ Using client-side OMX mux.
07-27 17:32:31.853  14659-14659/com.google.android.exoplayer.demo I/dalvikvm﹕ Could not find method android.media.MediaCodec.releaseOutputBuffer, referenced from method com.google.android.exoplayer.MediaCodecVideoTrackRenderer.renderOutputBufferTimedV21
07-27 17:32:31.853  14659-14659/com.google.android.exoplayer.demo W/dalvikvm﹕ VFY: unable to resolve virtual method 80: Landroid/media/MediaCodec;.releaseOutputBuffer (IJ)V
07-27 17:32:31.853  14659-14659/com.google.android.exoplayer.demo D/dalvikvm﹕ VFY: replacing opcode 0x6e at 0x0008
07-27 17:32:31.863  14659-14659/com.google.android.exoplayer.demo I/dalvikvm﹕ Could not find method android.media.AudioTrack.setVolume, referenced from method com.google.android.exoplayer.audio.AudioTrack.setVolumeV21
07-27 17:32:31.863  14659-14659/com.google.android.exoplayer.demo W/dalvikvm﹕ VFY: unable to resolve virtual method 62: Landroid/media/AudioTrack;.setVolume (F)I
07-27 17:32:31.863  14659-14659/com.google.android.exoplayer.demo D/dalvikvm﹕ VFY: replacing opcode 0x6e at 0x0000
07-27 17:32:31.863  14659-14659/com.google.android.exoplayer.demo I/dalvikvm﹕ Could not find method android.media.AudioTrack.write, referenced from method com.google.android.exoplayer.audio.AudioTrack.writeNonBlockingV21
07-27 17:32:31.863  14659-14659/com.google.android.exoplayer.demo W/dalvikvm﹕ VFY: unable to resolve virtual method 63: Landroid/media/AudioTrack;.write (Ljava/nio/ByteBuffer;II)I
07-27 17:32:31.863  14659-14659/com.google.android.exoplayer.demo D/dalvikvm﹕ VFY: replacing opcode 0x6e at 0x0001
07-27 17:32:32.173  14659-14663/com.google.android.exoplayer.demo D/dalvikvm﹕ GC_CONCURRENT freed 263K, 6% free 4651K/4944K, paused 4ms+3ms, total 32ms
07-27 17:32:32.213  14659-14762/com.google.android.exoplayer.demo D/dalvikvm﹕ GC_FOR_ALLOC freed 56K, 6% free 4723K/4988K, paused 16ms, total 16ms
07-27 17:32:32.233  14659-14762/com.google.android.exoplayer.demo D/dalvikvm﹕ GC_FOR_ALLOC freed <1K, 6% free 4980K/5248K, paused 18ms, total 18ms
07-27 17:32:32.263  14659-14762/com.google.android.exoplayer.demo D/dalvikvm﹕ GC_FOR_ALLOC freed 2K, 5% free 5236K/5508K, paused 16ms, total 16ms
07-27 17:32:32.283  14659-14765/com.google.android.exoplayer.demo I/OMXClient﹕ Using client-side OMX mux.
07-27 17:32:32.293  14659-14765/com.google.android.exoplayer.demo D/ACodec﹕ mDealtTimeToTal 0 flags 909588782
07-27 17:32:32.323  14659-14659/com.google.android.exoplayer.demo D/EventLogger﹕ state [1.11, true, B]
07-27 17:32:32.323  14659-14659/com.google.android.exoplayer.demo D/EventLogger﹕ videoFormat [1.11, 0, 0]
07-27 17:32:32.363  14659-14659/com.google.android.exoplayer.demo D/EventLogger﹕ decoderInitialized [1.15, OMX.rk.video_decoder.avc]
07-27 17:32:32.363  14659-14746/com.google.android.exoplayer.demo I/OMXClient﹕ Using client-side OMX mux.
07-27 17:32:32.363  14659-14746/com.google.android.exoplayer.demo I/﹕ new RKOMXPlugin
07-27 17:32:32.393  14659-14778/com.google.android.exoplayer.demo I/OMXClient﹕ Using client-side OMX mux.
07-27 17:32:32.403  14659-14778/com.google.android.exoplayer.demo I/﹕ new RKOMXPlugin
07-27 17:32:32.413  14659-14778/com.google.android.exoplayer.demo D/ACodec﹕ MEDIA_MIMETYPE_AUDIO_AAC sampleRate 22050 wifidisplay_flag 0 info 6a661e78
07-27 17:32:32.413  14659-14778/com.google.android.exoplayer.demo E/OMXNodeInstance﹕ OMX_GetExtensionIndex failed
07-27 17:32:32.433  14659-14779/com.google.android.exoplayer.demo W/SoftAAC﹕ Sample rate was 44100 Hz, but now is 22050 Hz
07-27 17:32:32.453  14659-14659/com.google.android.exoplayer.demo D/EventLogger﹕ videoSizeChanged [400, 300, 1.0]
07-27 17:32:32.513  14659-14659/com.google.android.exoplayer.demo D/EventLogger﹕ state [1.30, true, R]
07-27 17:32:33.323  14659-14762/com.google.android.exoplayer.demo D/dalvikvm﹕ GC_FOR_ALLOC freed 89K, 5% free 5506K/5768K, paused 19ms, total 19ms
07-27 17:32:35.053  14659-14762/com.google.android.exoplayer.demo D/dalvikvm﹕ GC_FOR_ALLOC freed 107K, 5% free 5763K/6028K, paused 30ms, total 30ms
07-27 17:32:35.423  14659-14663/com.google.android.exoplayer.demo D/dalvikvm﹕ GC_CONCURRENT freed 115K, 4% free 6095K/6308K, paused 3ms+2ms, total 35ms
07-27 17:32:35.593  14659-14762/com.google.android.exoplayer.demo D/dalvikvm﹕ GC_FOR_ALLOC freed 76K, 4% free 6417K/6644K, paused 19ms, total 19ms
07-27 17:32:36.943  14659-14762/com.google.android.exoplayer.demo D/dalvikvm﹕ GC_FOR_ALLOC freed 71K, 4% free 6929K/7164K, paused 18ms, total 18ms
07-27 17:32:39.093  14659-14762/com.google.android.exoplayer.demo D/dalvikvm﹕ GC_FOR_ALLOC freed 144K, 4% free 7441K/7684K, paused 19ms, total 19ms
07-27 17:32:41.413  14659-14659/com.google.android.exoplayer.demo W/HardwareRenderer﹕ Backbuffer cannot be preserved
07-27 17:32:41.993  14659-14663/com.google.android.exoplayer.demo D/dalvikvm﹕ GC_CONCURRENT freed 214K, 3% free 8226K/8472K, paused 3ms+3ms, total 42ms
07-27 17:32:42.323  14659-14659/com.google.android.exoplayer.demo W/HardwareRenderer﹕ Backbuffer cannot be preserved
07-27 17:32:42.673  14659-14659/com.google.android.exoplayer.demo D/EventLogger﹕ videoFormat [11.46, 2, 0]
07-27 17:32:46.563  14659-14659/com.google.android.exoplayer.demo V/EventLogger﹕ loadEnd [15.35, 0, 5867]
07-27 17:32:46.563  14659-14659/com.google.android.exoplayer.demo V/EventLogger﹕ loadStart [15.35, 0, 1, 29930, 39906]
07-27 17:32:50.963  14659-14762/com.google.android.exoplayer.demo D/dalvikvm﹕ GC_FOR_ALLOC freed 720K, 8% free 8677K/9428K, paused 24ms, total 24ms
07-27 17:32:51.363  14659-14659/com.google.android.exoplayer.demo V/EventLogger﹕ loadEnd [20.16, 0, 4800]
07-27 17:32:51.373  14659-14659/com.google.android.exoplayer.demo V/EventLogger﹕ loadStart [20.16, 0, 1, 39906, 49883]
07-27 17:32:53.063  14659-14762/com.google.android.exoplayer.demo D/dalvikvm﹕ GC_FOR_ALLOC freed 325K, 8% free 9425K/10208K, paused 20ms, total 20ms
07-27 17:32:54.583  14659-14659/com.google.android.exoplayer.demo V/EventLogger﹕ loadEnd [23.37, 0, 3218]
07-27 17:32:54.583  14659-14659/com.google.android.exoplayer.demo V/EventLogger﹕ loadStart [23.38, 0, 4, 0, 0]
07-27 17:32:54.733  14659-14659/com.google.android.exoplayer.demo V/EventLogger﹕ loadEnd [23.52, 0, 143]
07-27 17:32:54.733  14659-14659/com.google.android.exoplayer.demo V/EventLogger﹕ loadStart [23.52, 0, 1, 39906, 49883]
07-27 17:32:54.983  14659-14762/com.google.android.exoplayer.demo D/dalvikvm﹕ GC_FOR_ALLOC freed 299K, 6% free 10376K/10988K, paused 20ms, total 20ms
07-27 17:32:57.443  14659-14762/com.google.android.exoplayer.demo D/dalvikvm﹕ GC_FOR_ALLOC freed 326K, 6% free 11616K/12288K, paused 27ms, total 28ms
07-27 17:32:59.183  14659-14659/com.google.android.exoplayer.demo V/EventLogger﹕ loadEnd [27.97, 0, 4455]
07-27 17:32:59.183  14659-14659/com.google.android.exoplayer.demo V/EventLogger﹕ loadStart [27.97, 0, 1, 49883, 59860]
07-27 17:33:04.563  14659-14762/com.google.android.exoplayer.demo D/dalvikvm﹕ GC_FOR_ALLOC freed 542K, 5% free 13408K/14108K, paused 23ms, total 23ms
07-27 17:33:05.653  14659-14659/com.google.android.exoplayer.demo V/EventLogger﹕ loadEnd [34.44, 0, 6471]
07-27 17:33:05.663  14659-14659/com.google.android.exoplayer.demo V/EventLogger﹕ loadStart [34.45, 0, 1, 49883, 59860]
07-27 17:33:08.803  14659-14762/com.google.android.exoplayer.demo D/dalvikvm﹕ GC_FOR_ALLOC freed 507K, 4% free 15828K/16448K, paused 39ms, total 39ms
07-27 17:33:09.133  14659-14659/com.google.android.exoplayer.demo V/EventLogger﹕ loadEnd [37.92, 0, 3476]
07-27 17:33:09.133  14659-14659/com.google.android.exoplayer.demo V/EventLogger﹕ loadStart [37.92, 0, 1, 49883, 59860]
07-27 17:33:14.863  14659-14659/com.google.android.exoplayer.demo V/EventLogger﹕ loadEnd [43.66, 0, 5733]
07-27 17:33:14.873  14659-14659/com.google.android.exoplayer.demo V/EventLogger﹕ loadStart [43.66, 0, 1, 59860, 69836]
07-27 17:33:15.523  14659-14663/com.google.android.exoplayer.demo D/dalvikvm﹕ GC_CONCURRENT freed 676K, 4% free 19016K/19724K, paused 7ms+5ms, total 46ms
07-27 17:33:22.403  14659-14659/com.google.android.exoplayer.demo V/EventLogger﹕ loadEnd [51.19, 0, 7537]
07-27 17:33:22.403  14659-14659/com.google.android.exoplayer.demo V/EventLogger﹕ loadStart [51.20, 0, 1, 59860, 69836]
07-27 17:33:24.373  14659-14659/com.google.android.exoplayer.demo V/EventLogger﹕ loadEnd [53.16, 0, 1967]
07-27 17:33:31.833  14659-14746/com.google.android.exoplayer.demo E/AudioTrack﹕ Discontinuity detected [expected 59904581, got 49836911]
07-27 17:33:41.823  14659-14746/com.google.android.exoplayer.demo E/AudioTrack﹕ Discontinuity detected [expected 59821491, got 49836911]
07-27 17:34:01.793  14659-14746/com.google.android.exoplayer.demo E/AudioTrack﹕ Discontinuity detected [expected 69806072, got 59752181]
07-27 17:34:12.353  14659-14659/com.google.android.exoplayer.demo D/EventLogger﹕ state [101.14, true, B]

Thank you

**Comment by ojw28** [comment]
This is almost certainly the same as #464, which is for rk31sdk. What [SDK_INT](http://developer.android.com/reference/android/os/Build.VERSION.html#SDK_INT) value does the device report?

**Comment by ojw28** [comment]
The change above is merged on the dev branch, and probably fixes this issue. We don't have a device of this type to test with, so please give it a try. If it's still broken, please let us know, along with the SDK_INT value as requested above. Thanks!
