### ISSUE TITLE
RTMP stream not playing

### ISSUE THREAD

**Issue by kaiv2000** [google/ExoPlayer#6653]
These RTMP streams cannot start to play, no error messages are showing in debugger:

rtmp://stream.triolan.net.ua:1935/cam32/stream
rtmp://stream.triolan.net.ua:1935/cam35/stream

Used extension 'com.google.android.exoplayer:extension-rtmp:2.10.7'

**Comment by ojw28** [comment]
[Removed incorrect diagnosis. Please see the correct one below!]

**Comment by ojw28** [comment]
I tried this from a different network and was able to diagnose what's wrong. It's essentially the same problem as described [here](https://github.com/ant-media/LibRtmp-Client-for-Android/issues/70#issuecomment-555025362). The stream signals that both audio and video tracks are available, when in fact only video is available. The player is then waiting to receive some audio data to start playback.

This is a problem with the stream. Depending on how it's generated, the comment [here](https://github.com/ant-media/LibRtmp-Client-for-Android/issues/70#issuecomment-555109976) may be relevant.
