### ISSUE TITLE
Getting notified about new playlist in ConcatenatingMediaSource

### ISSUE THREAD

**Issue by Kamil-H** [google/ExoPlayer#6658]
### [REQUIRED] Searched documentation and issues
Official `ExoPlayer` documentation and source code of `ConcatenatingMediaSource`, `BaseMediaSource`, `MediaSourceEventListener` classes.

### [REQUIRED] Question
Is it possible to gets notified every time playlist (list of `MediaSource`) gets changed? I would like to get notified about every add, remove, move, clear operation. Generally, I would like to observe changes that are applied to `ConcatenatingMediaSource` but couldn't find a proper way. 
Ideally, in this callback, I would like to be notified with current `List<MediaSource>`.
The problem I'm trying to solve is that I would like my UI be observing what is currently playing and update view adequately (based on some kind of id of currently playing media item). 
Maybe there is better way to do that?
I also tried to observe changes to queue in `MediaControllerCompat.Callback.onQueueChanged`, but I'm getting notified only about 10 items, what is not enough for me.

**Comment by marcbaechinger** [comment]
> I also tried to observe changes to queue in MediaControllerCompat.Callback.onQueueChanged,
> but I'm getting notified only about 10 items, what is not enough for me.

Only a sliding window of the current timeline is synced to the media session queue. You can choose the size if you pass `maxQueueSize` to the constructor of the `TimelineQueueNavigator`. Having such a sliding window is recommended by the media framework though. So use that value wisely :)

Without the media session you can listen to the `EventListener.onTimelineChanged(timeline, reason) `callback. It gives you the new timeline after a modification (or when initially prepared). The you can do something like this:

```
// Assumed you use a tag when creating your media sources.
   new ProgressiveMediaSource.Factory(dataSourceFactory)
       .setTag("source 1")
       .createMediaSource(uri);

// Then you can iterate over the timeline. Be aware that the shuffle mode might change the
// order of the windows according to shuffling.
Timeline currentTimeline = player.getCurrentTimeline();
List<Object> tags = new ArrayList<>();
Timeline.Window window = new Timeline.Window();
boolean shuffleModeEnabled = player.getShuffleModeEnabled();
int windowIndex = currentTimeline.getFirstWindowIndex(shuffleModeEnabled);
while (windowIndex != C.INDEX_UNSET) {
    tags.add(currentTimeline.getWindow(windowIndex, window).tag);
    windowIndex = currentTimeline.getNextWindowIndex(
        windowIndex, Player.REPEAT_MODE_OFF, shuffleModeEnabled);
}
updateUi(tags);
```

**Comment by Kamil-H** [comment]
Thank you @marcbaechinger this works like a charm! Just one small fix to your code snippet for future readers:
`tags.add(currentTimeline.getWindow(windowIndex, window, true).tag);`
without `true` there is null instead of tag :)

**Comment by marcbaechinger** [comment]
Glad it works!

And oh, you've seen the future... :) The variant with the boolean is deprecated soon and should work as it does the same as with the flag. 

See the dev-v2 branch: https://github.com/google/ExoPlayer/blob/dev-v2/library/core/src/main/java/com/google/android/exoplayer2/Timeline.java#L744

I close the issue then. Please reopen if needed.
