### ISSUE TITLE
Black Screen  Player.STATE_ENDED

### ISSUE THREAD

**Issue by longxuewei** [google/ExoPlayer#6660]
Black screen problem:
When my play completion status is: STATE_ENDED,
At this point, I press the Home button to return to the home page. When I return to this page again, the player changes from the last frame to a black screen. How can I solve this problem? I want to display the last frame when I return to the page! thanks

**Comment by marcbaechinger** [comment]
Can you please shed some more light on what you mean with "pressing the home screen and returning to the home page"? Does this mean you are putting the app into background and return to the Android launcher?

If this is the case you need to store the current position and then recreate the ExoPlayer instance when the app comes to foreground again. Then you start the player at the stored position.
