### ISSUE TITLE
Dolby AC-4 Playback

### ISSUE THREAD

**Issue by sammaes** [google/ExoPlayer#6667]
### Searched documentation and issues
I looked on the website and searched for AC-4/AC4 in the issues list.

### [REQUIRED] Question
Using the demo app I'm trying to play one of the DASH reference streams with Dolby AC-4 audio (see link below).

On all of the following Android Virtual Devices I get "media includes audio tracks but none are playable by this device":
Android TV (Android 9.0)
Pixel 3a (Android 10.0)
Pixel XL (Android 9.0 and Android 10.0)

I understand that not all hardware can playback AC-4 audio but at least one of them should be able to play them? What did the development team use to test this feature?

Both release-v2 and dev-v2 give me this error.

### Link to test content
  {
    "name": "DASH AC-4",
    "samples": [
      {
        "name": "Live Profile 1 96k (25fps)",
        "uri": "https://dash.akamaized.net/dash264/TestCasesMCA/dolby/5/7/Living_Room_720p_20_96k_25fps.mpd",
        "extension": "mpd"
      },
    ]
  },

**Comment by AquilesCanta** [comment]
I'm sorry, but I'd say it's correct that none of the devices listed provides an AC-4 decoder. By doing a quick search you can find new devices that provide support for AC-4 through MediaCodec. Also, you may be able to use a bundled decoder.

Note: AC-4 support was added in https://github.com/google/ExoPlayer/pull/5303. Perhaps it's worth asking the contributor directly?

**Comment by sammaes** [comment]
@ybai001 could you help me with this issue please?

**Comment by ybai001** [comment]
@sammaes Following mobile phones support Dolby AC-4: Samsung Galaxy S9, S10, Note9, Note10, Huawei P20 series/P30 series/Mate 20 series, OnePlus 7 & 7 Pro, OPPO Reno.
Google Pixel series have not integrated AC-4 decoder.

**Comment by sammaes** [comment]
> @sammaes Following mobile phones support Dolby AC-4: Samsung Galaxy S9, S10, Note9, Note10, Huawei P20 series/P30 series/Mate 20 series, OnePlus 7 & 7 Pro, OPPO Reno.
> Google Pixel series have not integrated AC-4 decoder.

Thanks for your feedback! Do you happen to know if there is a player for desktop PCs, I don't own any of these devices I'm afraid.

**Comment by ybai001** [comment]
> > @sammaes Following mobile phones support Dolby AC-4: Samsung Galaxy S9, S10, Note9, Note10, Huawei P20 series/P30 series/Mate 20 series, OnePlus 7 & 7 Pro, OPPO Reno.
> > Google Pixel series have not integrated AC-4 decoder.
> 
> Thanks for your feedback! Do you happen to know if there is a player for desktop PCs, I don't own any of these devices I'm afraid.

Unfortunately, there is no this kind of player for desktop PCs.

**Comment by sammaes** [comment]
> > > @sammaes Following mobile phones support Dolby AC-4: Samsung Galaxy S9, S10, Note9, Note10, Huawei P20 series/P30 series/Mate 20 series, OnePlus 7 & 7 Pro, OPPO Reno.
> > > Google Pixel series have not integrated AC-4 decoder.
> > 
> > 
> > Thanks for your feedback! Do you happen to know if there is a player for desktop PCs, I don't own any of these devices I'm afraid.
> 
> Unfortunately, there is no this kind of player for desktop PCs.

Is there a Dolby AC-4 player in the pipeline for desktop PCs? 
I'm trying to verify a packaged AC-4 stream but it looks like this is not possible at the moment?

**Comment by ybai001** [comment]
> > > > @sammaes Following mobile phones support Dolby AC-4: Samsung Galaxy S9, S10, Note9, Note10, Huawei P20 series/P30 series/Mate 20 series, OnePlus 7 & 7 Pro, OPPO Reno.
> > > > Google Pixel series have not integrated AC-4 decoder.
> > > 
> > > 
> > > Thanks for your feedback! Do you happen to know if there is a player for desktop PCs, I don't own any of these devices I'm afraid.
> > 
> > 
> > Unfortunately, there is no this kind of player for desktop PCs.
> 
> Is there a Dolby AC-4 player in the pipeline for desktop PCs?
> I'm trying to verify a packaged AC-4 stream but it looks like this is not possible at the moment?

Sorry, I can't provide this info since it is company confidential. Currently, you had better verify your packaged AC-4 stream on above mobile devices with ExoPlayer based application. Some TV modules support AC-4 decoding. Do you plan to verify it on TV?

**Comment by sammaes** [comment]
> > > > > @sammaes Following mobile phones support Dolby AC-4: Samsung Galaxy S9, S10, Note9, Note10, Huawei P20 series/P30 series/Mate 20 series, OnePlus 7 & 7 Pro, OPPO Reno.
> > > > > Google Pixel series have not integrated AC-4 decoder.
> > > > 
> > > > 
> > > > Thanks for your feedback! Do you happen to know if there is a player for desktop PCs, I don't own any of these devices I'm afraid.
> > > 
> > > 
> > > Unfortunately, there is no this kind of player for desktop PCs.
> > 
> > 
> > Is there a Dolby AC-4 player in the pipeline for desktop PCs?
> > I'm trying to verify a packaged AC-4 stream but it looks like this is not possible at the moment?
> 
> Sorry, I can't provide this info since it is company confidential. Currently, you had better verify your packaged AC-4 stream on above mobile devices with ExoPlayer based application. Some TV modules support AC-4 decoding. Do you plan to verify it on TV?

I just want to make sure that what we have is actually playable, doesn't really matter if we play it on a phone, tv or pc at this moment.

**Comment by ybai001** [comment]
> > > > > > @sammaes Following mobile phones support Dolby AC-4: Samsung Galaxy S9, S10, Note9, Note10, Huawei P20 series/P30 series/Mate 20 series, OnePlus 7 & 7 Pro, OPPO Reno.
> > > > > > Google Pixel series have not integrated AC-4 decoder.
> > > > > 
> > > > > 
> > > > > Thanks for your feedback! Do you happen to know if there is a player for desktop PCs, I don't own any of these devices I'm afraid.
> > > > 
> > > > 
> > > > Unfortunately, there is no this kind of player for desktop PCs.
> > > 
> > > 
> > > Is there a Dolby AC-4 player in the pipeline for desktop PCs?
> > > I'm trying to verify a packaged AC-4 stream but it looks like this is not possible at the moment?
> > 
> > 
> > Sorry, I can't provide this info since it is company confidential. Currently, you had better verify your packaged AC-4 stream on above mobile devices with ExoPlayer based application. Some TV modules support AC-4 decoding. Do you plan to verify it on TV?
> 
> I just want to make sure that what we have is actually playable, doesn't really matter if we play it on a phone, tv or pc at this moment.

OK, I see. Currently, AC-4 is playable on some mobile devices and TVs. Here are more info: https://dolbyac4.com/uk/ and https://www.dolby.com/us/en/technologies/ac-4.html
