### ISSUE TITLE
Can make exoplayer play mts, m2ts format videos?

### ISSUE THREAD

**Issue by NanyangTaiji** [google/ExoPlayer#6670]
Before filing a feature request:
-----------------------
- Search existing open issues, specifically with the label ‘enhancement’:
  https://github.com/google/ExoPlayer/labels/enhancement
- Search existing pull requests: https://github.com/google/ExoPlayer/pulls

When filing a feature request:
-----------------------
Fill out the sections below, leaving the headers but replacing the content. If
you're unable to provide certain information, please explain why in the relevant
section. We may close issues if they do not include sufficient information.

### [REQUIRED] Use case description
Describe the use case or problem you are trying to solve in detail. If there are
any standards or specifications involved, please provide the relevant details.

### Proposed solution
A clear and concise description of your proposed solution, if you have one.

### Alternatives considered
A clear and concise description of any alternative solutions you considered,
if applicable.

**Comment by AquilesCanta** [comment]
Yes. Please provide a sample if you have any issues playing one. May be worth looking at #1488.

**Comment by NanyangTaiji** [comment]
https://archive.org/download/scm-10794-mtstestfile/00007.mts

Santiago Seifert <notifications@github.com> 于2019年11月20日周三 上午12:05写道：

**Comment by NanyangTaiji** [comment]
It can be played by VLC android

Taiji Doctor <ooyellow58@gmail.com> 于2019年11月20日周三 下午9:16写道：

**Comment by AquilesCanta** [comment]
As per #1488, this type of files is not yet supported. Forking TS extractor to support them should be relatively easy. Please track #1488 for support.
