### ISSUE TITLE
Exoplayer for 360 videos

### ISSUE THREAD

**Issue by XanderSan** [google/ExoPlayer#6675]
[REQUIRED] Searched documentation and issues
https://medium.com/google-exoplayer/playing-360-degree-videos-with-exoplayer-f3b48f8ea390

[REQUIRED] Question
I'm using an exoplayer in an android app and I want to play 360 videos.
I used a player with surface_type = spherical_view 
To explore video in any direction I tryed draggind the finger across the screen and it works but if I move the device around in different directions the video don't change.
Could you help me to resolve this problem.

This is my layout:

```
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:background="@color/White">

    <ScrollView
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <RelativeLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent">

            <androidx.constraintlayout.widget.ConstraintLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:id="@+id/image_container">
<com.google.android.exoplayer2.ui.PlayerView
                    android:layout_width="match_parent"
                    android:layout_height="0dp"
                    android:layout_centerInParent="true"
                    android:visibility="gone"
                    android:id="@+id/video_player_view_360"
                    app:surface_type="spherical_view"
                    app:layout_constraintEnd_toEndOf="parent"
                    app:layout_constraintStart_toStartOf="parent"
                    android:background="@color/Black"
                    app:layout_constraintDimensionRatio="W,9:16"
                    app:controller_layout_id="@layout/custom_mediacontroller_full"
                    app:layout_constraintBottom_toBottomOf="parent"/>
</androidx.constraintlayout.widget.ConstraintLayout>
</ScrollView>
</RelativeLayout>
</RelativeLayout>
```

**Comment by AquilesCanta** [comment]
You should start by using the demo app to play your video, and go from there (for starters, does your video work in the demo app?). When you hit a more specific issue, please post the items required in the [issue template](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md) and we can try assisting you.

**Comment by XanderSan** [comment]
Hi.
I downloaded the demo app and I tried to use it with my video.
The behavior is the same: dragging finger across the screen the 360 video change direction, moving the device no.
I tried to play a 360 video in HLS format.
Is it correct or 360 video needs to be in a specific format?
I'm using a XiaoMi device Mi8 with android 9 and I run demo-ima from demo source (I changed the surface_type in spherical_view and the link for the video obviously)

**Comment by AquilesCanta** [comment]
By demo app, I mean the main demo app. 

Please provide the media you are trying to play, as requested in the [issue template](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md). I can try it and see what the issue may be.
