### ISSUE TITLE
How to disable subtitles?

### ISSUE THREAD

**Issue by luna-vulpo** [google/ExoPlayer#6677]
I change using text language:
```
fun f(language: String?) {
       val newParams = trackSelector.buildUponParameters()
       newParams.setPreferredTextLanguage(language)
        trackSelector.parameters = newParams.build()
}
```
it works fine for most streams. But I have stream which contains default text language, so above code force default text.
if language is null it means that no subtitle at all.

How to disable subtitles?

I try to add:
```
        newParams.setDisabledTextTrackSelectionFlags(C.SELECTION_FLAG_FORCED)
        newParams.setRendererDisabled(C.TRACK_TYPE_VIDEO, language == null)
```
but it not help.

**Comment by AquilesCanta** [comment]
Not really sure about what you want to achieve, but if you want to disable the DEFAULT selection flag, then you should be doing

`newParams.setDisabledTextTrackSelectionFlags(C.SELECTION_FLAG_DEFAULT)`.

Can you explain in more detail what you need? Ideally, please include a sample stream.

**Comment by AquilesCanta** [comment]
After reading again the issue I realized I probably misunderstood what you want. If you just want to have no subtitles at all, you can disable the Text renderer. Look for _Disabling Renderers_ in the [DefaultTrackSelector](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/trackselection/DefaultTrackSelector.html) docs:

`Renderers can be disabled using DefaultTrackSelector.ParametersBuilder.setRendererDisabled(int, boolean).`

I'll cose the issue now, but please comment below if your question is still unanswered, and please clarify if so.
