### ISSUE TITLE
How to cleanup exoplayer instance

### ISSUE THREAD

**Issue by krackjack234** [google/ExoPlayer#6679]
[REQUIRED] Searched documentation and issues
Searched documentation but could not find any explicit anser

### [REQUIRED] Question
How can we remove all the media sources added to SimpleExoPlayer

We are adding different media sources like Ads, subtitles etc. Is there a requirement to remove them explicitly when we release the player? Do we need to cleanup anything in PlayerUI & MediaSourceEventListeners also?

We are getting an error "Unable to instantiate decoder OMX.hisi.video.decoder.avc", hence wondering what is the best way to cleanup exoplayer.

Also is there a way to check how many exoplayer instances are there in memory?

Thanks

**Comment by AquilesCanta** [comment]
> We are adding different media sources like Ads, subtitles etc. Is there a requirement to remove them explicitly when we release the player?

Just call `Player.release()`. You shouldn't need to do anything else. If you think there's a bug, file a fresh issue including all the information requested by the issue template in the form.

> Also is there a way to check how many exoplayer instances are there in memory?

There's no way to do that: The application is the owner of the player instances, so the app should take care of their life-cycle. This includes releasing any created players.

**Comment by krackjack234** [comment]
Hi @AquilesCanta , we already see similar issues are reported for different devices (https://github.com/google/ExoPlayer/issues/6168)

Is this a known problem in exoplayer?

Since many have reported same issue, just wondering if its really a memory leak issue.
