### ISSUE TITLE
Exoplayer http source error

### ISSUE THREAD

**Issue by randeeppr** [google/ExoPlayer#668]
Hi,

We are playing a mpeg dash video using exoplayer. Its Widevine Modular DRM encrypted video.

Video is playing. But exoplayer is printing these errors in backend. And sometimes it goes to idle from buffering mode and not playing the video anymore. 

E/EventLogger( 4231): internalError [27.47, upstreamError]
E/EventLogger( 4231): com.google.android.exoplayer.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to htt4
E/EventLogger( 4231):   at com.google.android.exoplayer.upstream.HttpDataSource.open(HttpDataSource.java:258)
E/EventLogger( 4231):   at com.google.android.exoplayer.upstream.UriDataSource.open(UriDataSource.java:66)
E/EventLogger( 4231):   at com.google.android.exoplayer.upstream.DataSourceStream.load(DataSourceStream.java:223)
E/EventLogger( 4231):   at com.google.android.exoplayer.chunk.Chunk.load(Chunk.java:179)
E/EventLogger( 4231):   at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:206)
E/EventLogger( 4231):   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
E/EventLogger( 4231):   at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/EventLogger( 4231):   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/EventLogger( 4231):   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/EventLogger( 4231):   at java.lang.Thread.run(Thread.java:841)
E/EventLogger( 4231): Caused by: java.net.SocketTimeoutException
E/EventLogger( 4231):   at java.net.PlainSocketImpl.read(PlainSocketImpl.java:491)
E/EventLogger( 4231):   at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:46)
E/EventLogger( 4231):   at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:240)
E/EventLogger( 4231):   at java.io.InputStream.read(InputStream.java:162)
E/EventLogger( 4231):   at java.io.BufferedInputStream.fillbuf(BufferedInputStream.java:142)
E/EventLogger( 4231):   at java.io.BufferedInputStream.read(BufferedInputStream.java:227)
E/EventLogger( 4231):   at com.android.okhttp.internal.Util.readAsciiLine(Util.java:316)
E/EventLogger( 4231):   at com.android.okhttp.internal.http.RawHeaders.fromBytes(RawHeaders.java:308)
E/EventLogger( 4231):   at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:135)
E/EventLogger( 4231):   at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:644)
E/EventLogger( 4231):   at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:347)
E/EventLogger( 4231):   at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:296)
E/EventLogger( 4231):   at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java)
E/EventLogger( 4231):   at com.google.android.exoplayer.upstream.HttpDataSource.open(HttpDataSource.java:256)
E/EventLogger( 4231):   ... 9 more
D/DnsProxyListener( 1352): argv[0]=getaddrinfo
D/DnsProxyListener( 1352): argv[1]=test.domain.com
D/DnsProxyListener( 1352): argv[2]=^
D/DnsProxyListener( 1352): argv[3]=1024
D/DnsProxyListener( 1352): argv[4]=0
D/DnsProxyListener( 1352): argv[5]=1
D/DnsProxyListener( 1352): argv[6]=0
D/DnsProxyListener( 1352): argv[7]=^
D/DnsProxyListener( 1352): GetAddrInfoHandler for test.domain.com / [nullservice] / [nulliface] / 2
D/DnsProxyListener( 1352): GetAddrInfoHandler, now for test.domain.com / (null) / (null)

Regards,
Randeep

**Comment by ojw28** [comment]
"Unable to connect to htt4" suggests you're connecting to a bad URL, presumably? You'll need to figure out where those URLs are coming from (it's likely that they originate either from the manifest or from the license server response).

**Comment by randeeppr** [comment]
I think it was the issue with the streaming server. The network was slow so that sometimes exoplayer was not getting the requested data. Its working now. Thanks.
