### ISSUE TITLE
DefaultTimeBar Android 10 - back gesture handling

### ISSUE THREAD

**Issue by curlyfrie** [google/ExoPlayer#6685]
### Use case description
Android 10 with navigation gestures

Timebar is edge to edge, user wants to move the thumb from the begin to the middle => back gesture triggered. wanted => seek

### Proposed solution
implement `setSystemGestureExclusionRects()`
https://developer.android.com/guide/navigation/gesturenav#back-gestures

Since the "_SeekBar components support automatic opt-out behavior out of the box._" I think it would be a good idea to also support this.

**Comment by icbaker** [comment]
Thanks for the suggestion! I'll take a look.

**Comment by curlyfrie** [comment]
Nice, thx :)
