### ISSUE TITLE
Can not play UDP multicast.

### ISSUE THREAD

**Issue by a4x4kiwi** [google/ExoPlayer#6686]
**Issue description,**
We are struggling to use the demo 'sample chooser activity' to play a UDP TS multicast stream. We get a black screen and timeout.

**Reproduction steps**
We also tried the demo-ima by modifying the url in the strings.xml file. udp://@239.1.1.1:1234

This occurs on a Sony Android TV, Moto Z2 and in the emulator.
The emulator plays http samples OK. The PC please the multicast samples OK using ffplay and mplayer.

The multicast is being produced by a TV headend,  VLC, or ffmpeg to play a recorded DVB-T.ts file.
Ultimately we will play back live TV from a headend over a multicast vlan.

Thanks for any and all assistance. We have been struggling for a a few days on this now.
Sorry if this is not a bug and we are doing something wrong.

Below are the details and attached log.

[error log.txt](https://github.com/google/ExoPlayer/files/3883337/error.log.txt)

Target: **Android TV (1080P) API 26**
Version: **2.10.8 (2019-11-19)**
Demo app running: **Sample Chooser Activity**
Modified play list selector file: **media.exolist.json** 
Added:
{
    "name": "UDP",
    "samples": [
      {
        "name": "239.1.1.1:1234",
        "uri": "udp://@239.1.1.1:1234"
      },
      {
        "name": "239.1.1.2:1234",
        "uri": "udp://@239.1.1.2:1234"
      }
    ]
  },

**Comment by a4x4kiwi** [comment]
OK, looks like Multicast can not work in the emulator.

" Currently, the emulator does not support IGMP or multicast. "
from [https://developer.android.com/studio/run/emulator-networking](https://developer.android.com/studio/run/emulator-networking)

Not to get back to testing on the TV.

**Comment by SharanKumarReddyKambham** [comment]
@a4x4kiwi hey bro am facing the same issue ,can you guide us where we are going wrong,that would be helpful.

**Comment by a4x4kiwi** [comment]
Initially we were using the wrong release. Make sure you use release-v2

Per my solution, the emulator can't play multicast. You need to use a real
device. We have successfully tested the demo on an NVIDIA shield and a Sony
TV. Both on wired ethernet.

Mal
