### ISSUE TITLE
ImaAdsLoader leaks AdEventListener within its AdsManager

### ISSUE THREAD

**Issue by nihk** [google/ExoPlayer#6687]
Not sure if this is intentional or not, or whether I'm just using the API incorrectly, but I noticed that the value given to `ImaAdsLoader.Builder.setAdEventListener(AdEventListener)` never gets removed from the `AdsManager` instance it owns. The consequence of this in my app is where if I'm playing an ad, then call `ImaAdsLoader.release()` the `ImaAdsLoader`'s `AdsManager` still holds onto my `AdEventListener` and sends it an `AdEvent` with type `AdEventType.CONTENT_RESUME_REQUESTED`, which I don't want (I would've expected `ImaAdsLoader.release()` to remove the `AdEventListener` I gave it during instantiation, for me).

There's no method that I'm aware of on `ImaAdsLoader` to remove my `AdEventListener`, so as a workaround I have to tap into `ImaAdsLoader.getAdsLoader().addAdsLoadedListener(...)` then hold onto the `AdsManager` myself and manage its ownership of my `AdEventListener`.

I can provide a more comprehensive bug report if the above details are insufficient.

Version used: 2.9.0

**Comment by ojw28** [comment]
We call `adsManager.destroy()` from `ImaAdsLoader.release()`. It's possible we assumed that this would be sufficient to stop the `AdsManager` from subsequently calling its listeners.

If that's not the case then we should probably remove the listeners in addition to calling `destroy()` (i.e. `adEventListener`, and probably `this` x2 as well)?
