### ISSUE TITLE
Video frames moves forward when player is paused (API > 26)

### ISSUE THREAD

**Issue by androideveloper** [google/ExoPlayer#6688]
We are using exoplayer 2.10.6 and have an issue with playback. When going onPause(lock) and come back onResume(unlock), player seek a bit forward (~1 frame) on each lock/unlock. I have similar issue https://github.com/google/ExoPlayer/issues/3090 but seems to be resolved now. Any suggestions?

Exoplayer: 2.10.6
Devices: Pixel 2, Xiaomi MI A1 (most of them have android > 8.0)

Logs on lock/unlock:

> 2019-11-25 13:28:52.514 5219-5219 D/EventLogger: surfaceSizeChanged [12.45, 3.52, window=0, period=0, 0, 0]
2019-11-25 13:28:54.578 5219-5219 D/EventLogger: surfaceSizeChanged [14.51, 3.52, window=0, period=0, 810, 1080]
2019-11-25 13:28:54.594 5219-5219 D/EventLogger: videoSizeChanged [14.53, 3.52, window=0, period=0, 960, 1280]
2019-11-25 13:28:54.594 5219-5219 D/EventLogger: renderedFirstFrame [14.53, 3.52, window=0, period=0, Surface(name=null)/@0xe5cb11a]

**Comment by andrewlewis** [comment]
I think this is similar to part of #6408. `MediaCodec` doesn't let you re-render the last output frame, so when we resume from the background we need to advance one frame to render something to the new surface. (Aside: on Android 10 I think it's possible to avoid this by rendering to a [`SurfaceControl`](https://developer.android.com/reference/android/view/SurfaceControl) but we don't have any functionality around this built into ExoPlayer at the moment.)

**Comment by androideveloper** [comment]
Thanks!
