### ISSUE TITLE
Deinterlacing issue in exoplayer

### ISSUE THREAD

**Issue by vengateshvengi** [google/ExoPlayer#6689]
As now,I am using exo-player for hls live streaming purpose.Input hls feed is interlaced format so i want to convert the feed into progressive format without any loss and same quality.
So,kindly guide me to implement the de-interlacing feature in exo-player to get progressive output video format.

**Comment by icbaker** [comment]
ExoPlayer doesn't support de-interlacing in the general case, but it's possible on some devices to set device-specific MediaFormat keys which trigger de-interlacing after the decoding. There's some more info in https://github.com/google/ExoPlayer/issues/2013#issuecomment-257634155.

**Comment by vengateshvengi** [comment]
Thanks for your support @icbaker

**Comment by vengateshvengi** [comment]
Extremely Sorry.I dont have any idea about it.so,give me some example or guide-ens   to set  device-specific MediaFormat keys for deinterlacing in exoplayer.@icbaker

**Comment by icbaker** [comment]
You'll need specific knowledge of the devices you're targeting, and access to their documentation, to know what keys their codecs will accept. And this will only work on those specific devices.

Once you have the key (usually a string name & value, either a string or numeric), you'll need to create a custom sub-class of [`MediaCodecVideoRenderer`](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/video/MediaCodecVideoRenderer.java) and override `getMediaFormat()` to mutate the MediaFormat provided by the super-class. 

Something like:

```
@Override
getMediaFormat() {
  MediaFormat format = super.getMediaFormat();
  format.setInteger(KEY, VALUE);
  return format;
}
```

You'll then need to make sure this custom `MediaCodecVideoRenderer` sub-class is used, by registering it when you construct your ExoPlayer instance. This is easiest to do by passing a custom `RenderersFactory` into `ExoPlayerFactory#newSimpleInstance(Context, RenderersFactory, TrackSelector)`. Your custom `RenderersFactory` can sub-class `DefaultRenderersFactory` and override `buildVideoRenderers()` to construct your `MediaCodecVideoRenderer` sub-class from above and add it to `out`.
