### ISSUE TITLE
HLS Play newest mpegts file instead EXT-X-MEDIA-SEQUENCE

### ISSUE THREAD

**Issue by bsysop** [google/ExoPlayer#669]
I working many days with a problem with HLS LiveStreaming,

I take a playlist m3u8 and put in VLC and this play the file `segment280715412_00013.ts` but looks ExoPlayer no care about that, just play last one or some of lasts files .TS!

**Why this like this??**

Many times, Live streaming SHOULD have some small delay, if not always stuck the playback....

**Sample manifest:**
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:13
#EXT-X-ALLOW-CACHE:NO
#EXT-X-TARGETDURATION:18
#EXTINF:17.200000,
segment280715412_00013.ts
#EXTINF:2.920000,
segment280715412_00014.ts
#EXTINF:11.000000,
segment280715412_00015.ts
#EXTINF:10.600000,
segment280715412_00016.ts
#EXTINF:9.600000,
segment280715412_00017.ts
#EXTINF:9.960000,
segment280715412_00018.ts
#EXTINF:11.000000,
segment280715412_00019.ts
#EXTINF:10.520000,
segment280715412_00020.ts
#EXTINF:10.000000,
segment280715412_00021.ts
#EXTINF:10.000000,
segment280715412_00022.ts
```

**Comment by bsysop** [comment]
Hi again, i put a Log.e in HlsParserPlaylist and this show me that ExoPlayer is getting right this Manifest and reading and playing MEDIA-SEQUENCE perfect...

So.. I don't know what is happening with VLC, maybe a Cached file or something like this.

Close this for moment, if some new information i will updated here!.

Thank you!.

**Comment by bsysop** [comment]
Ok, now i think i know what happening with me before.

I have two types of manifests (Both generated with ffmpeg)

On give me segmented files like:
> #EXTINF:4.804667,
> play280723610.ts
> #EXTINF:3.603411,
> play280723611.ts

Another type give me files like this:
> #EXTINF:5.760000,
> segment280715412_02056.ts
> #EXTINF:6.200000,
> segment280715412_02057.ts

As you know, HLS have a sequence, so this have to be a INT sequence, in first case this sequence is 1,2,3, in the second case the sequence are 00001, 00002, 00003, but the difference is second type, ffmpeg put a **UNDERLINE** to separate FILENAME to MEDIA-SEQUENCE...

Well, for me now is perfect with a Segmented/FFmpeg format, no more problems with that, perhaps before i got many many problems and too much bufferings with HLS/FFmpeg format i should ask: Maybe ExoPlayer need Filename**UNDERLINE**SequenceInt?

**HLS Manifest based on hls/ffmpeg format.**
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-ALLOW-CACHE:NO
#EXT-X-TARGETDURATION:5
#EXT-X-MEDIA-SEQUENCE:280723607
#EXTINF:4.804467,
play280723607.ts
#EXTINF:3.603400,
play280723608.ts
#EXTINF:3.603467,
play280723609.ts
#EXTINF:4.804667,
play280723610.ts
#EXTINF:3.603411,
play280723611.ts
```

**HLS Manifest based in Segmented/FFmpeg format.**
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:2055
#EXT-X-ALLOW-CACHE:NO
#EXT-X-TARGETDURATION:20
#EXTINF:19.120000,
segment280715412_02055.ts
#EXTINF:5.760000,
segment280715412_02056.ts
#EXTINF:6.200000,
segment280715412_02057.ts
#EXTINF:14.680000,
segment280715412_02058.ts
#EXTINF:10.000000,
segment280715412_02059.ts
#EXTINF:10.000000,
segment280715412_02060.ts
#EXTINF:7.920000,
segment280715412_02061.ts
#EXTINF:9.680000,
segment280715412_02062.ts
#EXTINF:12.760000,
segment280715412_02063.ts
#EXTINF:12.560000,
segment280715412_02064.ts
```

**Comment by bsysop** [comment]
I forget to says...

I put a Log in HlsPlaylistParser and this show right in segmented/ffmpeg, but not in hls/ffmpeg (Show nothing).

```
E/ExoPlayerLib.HlsPlaylistParser(28913): TsFile: #EXT-X-MEDIA-SEQUENCE:2016
E/ExoPlayerLib.HlsPlaylistParser(28913): TsFile: #EXT-X-MEDIA-SEQUENCE:2017
E/ExoPlayerLib.HlsPlaylistParser(28913): TsFile: #EXT-X-MEDIA-SEQUENCE:2019
E/ExoPlayerLib.HlsPlaylistParser(28913): TsFile: #EXT-X-MEDIA-SEQUENCE:2019
E/ExoPlayerLib.HlsPlaylistParser(28913): TsFile: #EXT-X-MEDIA-SEQUENCE:2021
```

**Comment by bsysop** [comment]
Finally, checking with VLC, that not playing same content, looking VLC are back in the time compared with Exoplayer.

How to force ExoPlayer to playback the first files on the manifest and not lasts files?
```
https://tools.ietf.org/html/draft-pantos-http-live-streaming-01#section-3.1.2
3.1.2.  EXT-X-MEDIA-SEQUENCE
   Each media file URI in a Playlist has a unique sequence number.  The
   sequence number of a URI is equal to the sequence number of the URI
   that preceded it plus one.  The EXT-X-MEDIA-SEQUENCE tag indicates
   the sequence number of the first URI that appears in a Playlist file.
   Its format is:

   #EXT-X-MEDIA-SEQUENCE:<number>

   If the Playlist file does not contain an EXT-X-MEDIA-SEQUENCE tag
   then the sequence number of the first URI in the playlist SHALL be
   considered to be 1.
```
```
6.2.2.  Playing the Playlist file

   The client SHALL choose which media file to play first from the
   Playlist when playback starts.  If the Playlist file contains the
   EXT-X-ENDLIST tag, any file in the Playlist MAY be played first.  If
   the EXT-X-ENDLIST tag is not present, any file except for the last
   and second-to-last files in the Playlist MAY be played first.

   Once the first media file to play has been chosen, subsequent media
   files in the Playlist MUST be loaded in the order that they appear
   and played in the order that they are loaded.

   The client SHOULD attempt to load media files in advance of when they
   will be required for uninterrupted playback to compensate for
   temporary variations in latency and throughput.

   If the Playlist file contains the EXT-X-ALLOW-CACHE tag and its value
   is NO, the client MUST NOT cache downloaded media files after they
```

**Comment by ojw28** [comment]
It's unclear what the question is here, but:

1. Regarding the third post, ExoPlayer doesn't do anything with the file name other than use it to build the URL. The format of the file names makes no difference. They don't even need to include the sequence numbers, since the sequence numbers are derived from the #EXT-X-MEDIA-SEQUENCE at the top and then by counting the number of files when parsing the list.
1. If ENDLIST_TAG is present ExoPlayer will treat the video as on-demand and start from the first segment in the list. If it's not it will treat it as live and start from the third chunk from the end, as controlled by HlsChunkSource.getLiveStartChunkMediaSequence.

**Comment by ojw28** [comment]
Closing this issue because it's unclear. Please open a new (and concise) issue if you have a further question. Thanks.

**Comment by bsysop** [comment]
Hi @ojw28, well there have two questions, i know this should be two posts, sorry for that.

**1. Question:** I generate two m3u8 manifest files with ffmpeg, both have "#EXT-X-MEDIA-SEQUENCE" TAG, perhaps i check in HlsPlaylistParser, and when file name of the MPEGTS file are like "NAME200.ts" HlsParser don't understand that, perhaps when this are "NAME**_**200.ts" that are ok. Do you know about that? (This looks like a issue from ExoPlayer or FFmpeg)

For check that, only need to put a Log() in HlsPlaylistParser and try manifest.
![captura de tela 2015-07-29 as 18 30 46](https://cloud.githubusercontent.com/assets/9998303/8970440/14bfd79e-3620-11e5-8f55-542f81780cc9.png)

**2. Question:** I will check more about that before post here. Thanks.

**Comment by ojw28** [comment]
As per above, the file names aren't used for anything other than building the URLs to fetch the data from. Which answers question 1.

**Comment by bsysop** [comment]
Oh, i understand, so EXT-X-MEDIA-SEQUENCE have no much sense on this case.

Thank you!!!
