### ISSUE TITLE
Specific use-case of HLS streaming

### ISSUE THREAD

**Issue by Arthas19** [google/ExoPlayer#6690]
### [REQUIRED] Searched documentation and issues
I have searched almost every medium blog I could find on the topic of HLS streaming and downloading.
I also went through the issues.

### [REQUIRED] Question
I want to stream HLS content, by loading content into the cache and from the cache into the buffer.
By manually setting the load controller's max buffer to 10min I'll allocate too much (RAM) memory.
I don't want to use the downloader because I want to be able to adaptively stream into the cache.

At all times I want to have: 
-    10min of cached content
-    30s of buffered content

I need advice from where to start such implementation or if it is possible to make something like this.

**Comment by marcbaechinger** [comment]
Sorry, I missed that totally. Please accept my apologies.

For the 30 seconds of buffered content you can use the `DefaultLoadControl` as you suggest.

For caching you could use a `CacheDataSource`. But with HLS there is the difficulty that there may be various adaptive stream defined in the HLS manifest. So you need to restrict playback to a single quality to make sure the player only uses that quality. This makes sure that the `CacheDataSource' caches what the player requests for download if you play again. That's what the `Downloader` does so I recommend using it.

>  I want to be able to adaptively stream into the cache

You need a way to make sure that the player adapts in the very same way each time. Naturally, the cache can only cache what has been downloaded at a first playback. If a second playback adapts differently it does not work.

The only way I know to make sure that the player 'adapts' in the very same way each time, is restricting adaption to a single stream quality. That#s what the Downloader does.

**Comment by marcbaechinger** [comment]
Sorry again for letting this issue slip through.

I close now. Feel free to reopen in case you haven't solved your problem yet and you think we can help some further.
