### ISSUE TITLE
Matroska file and Extension Renderer ffmpeg 

### ISSUE THREAD

**Issue by Magntcrs** [google/ExoPlayer#6694]
Hello Exoplayer team.

i used Exoplayer in my app.
i have a problem.
when i play video format .mkv or Matroska on mobile device and android box 
video can't support Audio ac3 some device

i used Ffmpeg extension in my project, for decode audio renderer
video can play and audio support, but i have a problem

some device android box, CPU usage allwinner h6. example Android box Tx6, Android box X96H
when play video picture not smooth and freezes

could I ask for your advice about fix it.

**Comment by icbaker** [comment]
Please follow the issue template: 
https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md

Specifically, can you tell us:

1. What version of ExoPlayer are you using?
1. Did you build the FFmpeg extension with ac3 support enabled? https://exoplayer.dev/supported-formats.html#ffmpeg-extension
1. Does the issue reproduce in the ExoPlayer demo app? If so please attach a bug report showing the repro - or send it to dev.exoplayer@gmail.com if you don't want to attach it publicly.
1. Can you provide sample media that demonstrates the problem? Send it to dev.exoplayer@gmail.com if you don't want to attach it publicly.
    * If you can't provide the sample media, and it's a video-related problem, we at least need to know the video codec used inside the MKV container.
1. Can you more precisely describe the problem? You mention that AC3 audio isn't supported, but also say that the video isn't smooth - these don't sound like the same problem.
