### ISSUE TITLE
Prefer adaptive decoder 

### ISSUE THREAD

**Issue by david2658** [google/ExoPlayer#670]
The function getDecoderInfo in MediaCodecTrackRenderer.java cannot pass an argument that indicates the preference of adaptive decoder. It returns a decoder which has the best decoding ability on device but it maybe can not support adaptive playback. Is it possible that we pass an argument through the constructor of MediaCodecVideoTrackRenderer to indicate the adaptive playback when setup a video renderer of adaptive playback?

**Comment by ojw28** [comment]
Normally the adaptive decoder will be the first one in the list anyway. The exception to the rule would be if a H/W decoder wasn't adaptive but the S/W decoder was, however in this case note that the S/W decoder is probably significantly less powerful and/or will drain significantly more battery.

What's the actual use case here, and on which devices and platform levels is it relevant?

**Comment by david2658** [comment]
Because of the nature of my platform, I have two H/W decoders (logically defined in media_codecs.xml) and one S/W decoder. One of the H/W decoders has the better decoding ability (up to 4K/60fps), but no adaptive feature, and the other H/W decoder with adaptive feature can decode only 4K/30fps. Thus, when we want to play a adaptive playback, ExoPlayer will pick the first one rather than the decoder with adaptive feature and release decoder while resolution changes.

**Comment by ojw28** [comment]
The latest version of Android's compatibility test suite requires that all decoders for AVC/HEVC/VP8/VP9 must be adaptive. So it sounds like your device would fail the suite and not be classed as a certified Android device. The test in question can be found [here](https://android.googlesource.com/platform/cts/+/99b52fbea97cd8a8c95339dc1ff1681b934b1610/tests/tests/media/src/android/media/cts/MediaCodecCapabilitiesTest.java).
