### ISSUE TITLE
Exoplayer not playing Video only playing audio.

### ISSUE THREAD

**Issue by ArunJO** [google/ExoPlayer#6701]
I am using Exoplayer. where input is HLS Stream it playing in many mobile but still its getting video i s not paying in some Devices but  audio is playing.(Example Devices: Samsung s series)

kindly help me to resolve this issue

**Comment by icbaker** [comment]
Please fill in the issue template:
https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/question.md

It's going to be impossible to diagnose the issue without more information, such as:

* The stream you're seeing this behaviour with
  * What codecs are used for the audio & video?
* Does it reproduce in the demo app? If so, please provide a bug report after the reproduction.
* What devices does it work on, and which ones does it not?

**Comment by itstamil** [comment]
Hi @icbaker 

I'm also facing the same issue while testing on samsung j7

Video Codec : H262
Audio Codec : mp2

In samsung mobiles, video is not playing but i able to decode and play the audio 
please help me to sort this out 

Regrads,
Tamilvalavan Shanmugam

**Comment by ArunJO** [comment]
Hi @itstamil,
My setup also similar to this, but i'm testing with samsung s8

**Comment by icbaker** [comment]
Neither H262 video nor MP2 audio are required to be supported by all Android devices:
https://developer.android.com/guide/topics/media/media-formats#core

More information on supported formats:
https://exoplayer.dev/supported-formats.html#sample-formats

Do the devices you're using support these formats? If not, you might be able to decode in software using the FFmpeg extension:
https://exoplayer.dev/supported-formats.html#ffmpeg-extension
