### ISSUE TITLE
ExoPlayer .mp4 extension’s not working

### ISSUE THREAD

**Issue by maven-y** [google/ExoPlayer#6702]
### Issue description
I am using mp4 video URLs to play in my app,  I have checked Video is not playing it is just loading and taking much time. And GREEN screen over top of the videos.

###  Reproduction steps

Sample app of exoplayer added media source in  json file

Version Exoplayer:2.7.3

Url Streaming: https://sapphireblessings.s3.amazonaws.com/video/strategiesfordeliverance/02-The-Big-Book.mp4

### Video details are below : 

<img width="496" alt="Screenshot 2019-11-27 at 6 15 22 PM" src="https://user-images.githubusercontent.com/6801363/69725109-63056380-1143-11ea-9201-470429acf0f5.png">
<img width="488" alt="Screenshot 2019-11-27 at 6 15 42 PM" src="https://user-images.githubusercontent.com/6801363/69725112-6567bd80-1143-11ea-944f-03d34b2fb4da.png">

### A full bug report captured from the device
Android Versions 7.0 
Those models are:

- Moto E5
- Moto E5 play
- LG Aristo M210 
- Google Pixel 3
- Samsung Galaxy A5

### ScreenShot : 

![Screenshot_20191122-114341](https://user-images.githubusercontent.com/6801363/69728802-28072e00-114b-11ea-89e4-bd7b5a0ecbdf.png)

### Help
Please tell what is wrong with the media, how can I modify it so that it can be playable.
Do I need to add any extension or upgrade the version of exo ?

Any help would be appriciated

thanks

**Comment by icbaker** [comment]
I can reproduce this, thanks for the report. I'll take a closer look next week and see if I can work out what's going on.

**Comment by icbaker** [comment]
Looks like your video is interlaced, which isn't supported officially on Android: https://github.com/google/ExoPlayer/issues/3468#issuecomment-441324948

```
$ mediainfo https://sapphireblessings.s3.amazonaws.com/video/strategiesfordeliverance/02-The-Big-Book.mp4 | grep 'Scan type'
Scan type                                : Interlaced
Scan type, store method                  : Separated fields
```

It may work on some devices, but as you've seen doesn't work on many.

I suspect if you re-encode without interlacing you'll see a better result.
