### ISSUE TITLE
AudioStuttering

### ISSUE THREAD

**Issue by dnuriel** [google/ExoPlayer#671]
I have my own implementation of TrackRenderer for a mp3 decoder, that I integrated. When a lollipop device goes to standby and comes back, its not always repeatable but the audio starts to stutter until I force stop the application.

In the beginning, I thought it was the decoder I implemented, so I tried comparing the file output between a stuttering track to a normal one. The files are identical, I then thought maybe its taking too long to decode, so I increased the buffer size and called setPlayReady false, in order for the data to buffer. It stutters the same as if I didn't pause. I am currently thinking the issue is with either my implementation of audio track or an OS bug. The bug only happens on Lollipop devices. Not sure if this is the right place to post this, but hoping I can get help.

Thanks.

**Comment by ojw28** [comment]
Given you're using custom components, you'll have to figure this out yourself (or get some help on stackoverflow or something). This tracker is for bugs in the library.

**Comment by ptran-gpfw** [comment]
@dnuriel : I'll be working on MP3 decoding in my own project and I'm interested in the issue you are seeing. Perhaps post to stackoverflow and link to it here. Also, it would be great If you could describe how your custom TrackRenderer differs from the default ones in the library .

**Comment by dnuriel** [comment]
http://stackoverflow.com/questions/31707636/exoplayer-audiotrack-stuttering
@ptran-gpfw feel free to ask for further detail.
