### ISSUE TITLE
Error : Vaapi Not found on FFMPEG Cross-compile

### ISSUE THREAD

**Issue by itstamil** [google/ExoPlayer#6713]
Hi,
I was trying to build FFMPEG by following these steps,
Step 1: cloned Exo-player
Step 2: cd Exo-player && FFMPEG_EXT_PATH="$(pwd)/extensions/ffmpeg/src/main/jni"
Step 3: Downloaded NDK 
Step 4: cd NDK && NDK_PATH=$(pwd)
Step 5: HOST_PLATFORM="linux-x86_64"
Step 6: An complete Command run for build process

COMMON_OPTIONS="\
    --target-os=android \
     --disable-everything \
     --disable-static \
     --disable-doc \
     --disable-programs \
     --disable-postproc \
     --disable-symver \
     --disable-swresample \
     --enable-shared \
     --enable-avdevice \
     --enable-avformat \
     --enable-avfilter \
     --enable-swscale \
     --enable-filter=yadif \
     --enable-filter=scale \
     --enable-avresample \
     --enable-gpl \
     --enable-version3 \
     --enable-vaapi \
     --enable-filter=yadif \
     --enable-decoder=vorbis \
     --enable-decoder=opus \
     --enable-decoder=flac \
     --enable-decoder=mp3 \
     --enable-decoder=mp3 \
     --enable-decoder=mp2 \
     --enable-decoder=mpeg2video \
     --enable-encoder=mpeg2video \
     --enable-decoder=mpeg4 \
     --enable-encoder=libx264 \
     --enable-muxer=h264 \
     --enable-demuxer=h264 \
    " && \
cd "${FFMPEG_EXT_PATH}" && \
(git -C ffmpeg pull || git clone git://source.ffmpeg.org/ffmpeg ffmpeg) && \
cd ffmpeg && git checkout release/4.0 && \
./configure \
    --libdir=android-libs/armeabi-v7a \
    --arch=arm \
    --cpu=armv7-a \
    --cross-prefix="${NDK_PATH}/toolchains/arm-linux-androideabi-4.9/prebuilt/${HOST_PLATFORM}/bin/arm-linux-androideabi-" \
    --sysroot="${NDK_PATH}/platforms/android-9/arch-arm/" \
    --extra-cflags="-march=armv7-a -mfloat-abi=softfp" \
    --extra-ldflags="-Wl,--fix-cortex-a8" \
    --extra-ldexeflags=-pie \
    ${COMMON_OPTIONS} \
    && \
make -j4 && make install-libs && \
make clean && ./configure \
    --libdir=android-libs/arm64-v8a \
    --arch=aarch64 \
    --cpu=armv8-a \
    --cross-prefix="${NDK_PATH}/toolchains/aarch64-linux-android-4.9/prebuilt/${HOST_PLATFORM}/bin/aarch64-linux-android-" \
    --sysroot="${NDK_PATH}/platforms/android-21/arch-arm64/" \
    --extra-ldexeflags=-pie \
    ${COMMON_OPTIONS} \
    && \
make -j4 && make install-libs && \
make clean && ./configure \
    --libdir=android-libs/x86 \
    --arch=x86 \
    --cpu=i686 \
    --cross-prefix="${NDK_PATH}/toolchains/x86-4.9/prebuilt/${HOST_PLATFORM}/bin/i686-linux-android-" \
    --sysroot="${NDK_PATH}/platforms/android-9/arch-x86/" \
    --extra-ldexeflags=-pie \
    --disable-asm \
    ${COMMON_OPTIONS} \
    && \
make -j4 && make install-libs && \
make clean && ./configure \
	--libdir=android-libs/x86_64 \
	--arch=x86_64 \
	--cpu=x86_64 \
	--cross-prefix="${NDK_PATH}/toolchains/x86_64-4.9/prebuilt/${HOST_PLATFORM}/bin/x86_64-linux-android-" \
	--sysroot="${NDK_PATH}/platforms/android-21/arch-x86_64/" \
	--extra-ldexeflags=-pie \
	--disable-x86asm \
	${COMMON_OPTIONS} \
	&& \
make -j4 && make install-libs && \
make clean

Step 6: ERROR: Vaapi is not found
Step 7: But I installed [VAAPI](https://gist.github.com/Brainiarc7/eb45d2e22afec7534f4a117d15fe6d89) 
please help to sort this out

Regards,
Tamilvalavan Shanmugam

**Comment by andrewlewis** [comment]
Please take a look at the [README](https://github.com/google/ExoPlayer/blob/90b5212/extensions/ffmpeg/README.md) for the extension to see how we expect ffmpeg to be configured. For using the extension there is no point configuring with anything video-related as the extension only supports audio decoding.
