### ISSUE TITLE
AdEventListener.onAdEvent() is never called after the video has looped

### ISSUE THREAD

**Issue by markproxy** [google/ExoPlayer#6716]
### [REQUIRED] Issue description
When using LoopingMediaSource, I expect AdEventListener.onAdEvent() to be called throughout playback -- even when video playback has looped one or more times. This way, onAdEvent() can be used to record ad-related analytics, including the number of times an ad was watched due to looping. However, after the first time through an HLS video, onAdEvent() in not longer called. This is true regardless of whether I use LoopingMediaSource or Player.REPEAT_MODE_ONE to trigger looping of video playback.

Please note that I contacted the IMA SDK team. They investigated the issue and determined it was a problem in ExoPlayer, where onAdEvent() is no longer called once playback has looped -- even though the ads themselves continue to be shown.

### [REQUIRED] Reproduction steps
You can see this by modifying the BasicExample in the sample app available here: https://github.com/googleads/googleads-ima-android-dai

I have attached a patch.txt file with the changes I made to the BasicExample app, but I will also describe them here so you can do the same.

Within the BasicExample app, you first must set content type to VOD_HLS. You can change this in SampleAdsWrapper:

```
private static final ContentType CONTENT_TYPE = ContentType.VOD_HLS;
```

The other change you'll need to make is in the SampleVideoPlayer class. Within SampleVideoPlayer.play(), modify the code to use LoopingMediaSource:
 
```
  LoopingMediaSource actualMediaSource = new LoopingMediaSource(mediaSource);
  mPlayer.prepare(actualMediaSource);
```

Then run the app and watch the ad events that appear in the lower half of the screen, or monitor logcat for "Event:" logs. You'll see that events are fired only during the first time playing the video and associated ads. (Note: you don't have to sit through the entire video. You can scrub to the end and still see the problem once it loops.)

You can also use the BasicExample to demonstrate that the same problem occurs when you use the setRepeatMode() method to enable looping. At the same place in SampleVideoPlayer.play(), use this code to enable looping:
 
```
  mPlayer.setRepeatMode(Player.REPEAT_MODE_ONE);
  mPlayer.prepare(mediaSource);
```

Again, you'll see that ad events are not fired after the first time playing through the video and its ads.

### [REQUIRED] Link to test content
The BasicExample sample app (which you'll have to modify slightly, as described above) can be found here: https://github.com/googleads/googleads-ima-android-dai

### [REQUIRED] A full bug report captured from the device
I don't think this is relevant, but let me know if you need this. The IMA SDK team was able to reproduce the problem without any difficulty.

### [REQUIRED] Version of ExoPlayer being used
I've reproduced this problem on versions 2.8.0 and 2.10.8.

### [REQUIRED] Device(s) and version(s) of Android being used
I've seen the problem on a Pixel 3 running Android 10 Build QP1A.191005.007, and on a Nexus 7 emulator with API 28.

[patch.txt](https://github.com/google/ExoPlayer/files/3907807/patch.txt)

**Comment by andrewlewis** [comment]
If I understand correctly, this is not related to the ExoPlayer IMA extension, but instead is about behavior of IMA's sample app after applying a patch to loop playback. The sample app uses ExoPlayer for playback, but it has its own integration with the IMA SDK.

Please could you provide a link to the discussion with the IMA SDK team? Thanks.

**Comment by markproxy** [comment]
Within the IMA SDK BasicExample app, see `SampleAdsWrapper.onAdsManagerLoaded()`. Within this method, a call is made to `mStreamManager.addAdEventListener(this)`, which hooks the `SampleAdsWrapper` up to receive calls to `onAdEvent()`. The first time through video playback, this works as expected. On subsequent loops, `onAdEvent()` is no longer called. Are you saying that this is due to a bug in the BasicExample app code? Is there some place that `addAdEventListener()` needs to be called every time playback is looped?

Regarding the discussion with the IMA SDK team, the public thread is here: https://groups.google.com/forum/m/?fromgroups&hl=en-AU#!topic/ima-sdk/nbmoypvjtb4

However, the interesting portions of the conversation occurred in a private thread. I've pasted the thread contents below:

> Hi Mark,

> Thanks for getting back to me. I was now able to reproduce the issue by updating the content type to "VOD_HLS". However, adding loopingMediaSource or setting the player to REPEAT_MODE_ONE is definitely a non-standard implementation of the SDK and so I can't guarantee if everything is going to work as expected.
> 
> Alternatively, the IMA DAI SDK for Android do have the setContinuousPlayback method that notifies the SDK, whether the player intends to continuously play the content videos one after another. Let me know if this will work for you.
> 
> I would also suggest checking out the Ad serving guidelines for more information with regard to product-specific policies.
> 
> 
> Regards,
> Sherwin Diesta
> IMA SDK Team

- - - - 
> The setContinuousPlayback() method on AdsRequest does not pertain to looping. My use case is specific to looping. (We typically play a single content video, not a series of videos.)
> 
> LoopingMediaSource and REPEAT_MODE_ONE are standard to ExoPlayer, and have been present in ExoPlayer for as long as I've been using the IMA SDK. If these are considered non-standard approaches to looping playback of a video, then what's the recommended approach to looping playback? Or are you saying that looped playback itself isn't supported by the IMA SDK? If that's the case, it seems like the ads shouldn't play on every loop.
> 
> To provide context, this issue was discovered while adding ad-related analytics to the Bleacher Report app for Android. The app shows relatively short sports-related clips, as well as some longer video content, and all videos are looped so that app users can watch them multiple times without having to restart the video each time. The IMA SDK re-plays ads on each loop, and we want to be able to track analytics for each ad. Until we started adding analytics specific to ads, it appeared that everything was working fine. From the user's perspective, ad playback in a looped video works as expected.
> 
> Thanks,
> Mark

- - - - 

> Hi Mark,
> 
> Thank you for getting back to me with this information.
> 
> Just to clarify, the issue that you are seeing with your implementation is not with the IMA DAI SDK for Android, but instead with the Exoplayer's LoopingMediaSource and REPEAT_MODE_ONE not calling the onAdEvent() before looping the main content and the ads. I'm afraid is a non-IMA SDK issues and beyond the scope of this forum.
> 
> There's a separate forum for all Exoplayer related concern, and my recommendation would be for you to reach out to the Exoplayer Support Team for further assistance with your inquiry.
> 
> 
> Regards,
> Sherwin Diesta
> IMA SDK Team

- - - - 
> Thank you! I'll pursue this with the Exoplayer team. It didn't occur to me that they would be responsible for calling onAdEvent().

**Comment by andrewlewis** [comment]
There is potential for confusion here because ExoPlayer does have its own integration with IMA (the [IMA extension](https://github.com/google/ExoPlayer/tree/release-v2/extensions/ima), where we wrap the IMA SDK and take care of handling events for you), but this issue instead relates to the IMA sample app, in which ExoPlayer is being used to play individual pieces of content and ads and has no knowledge of the ad timeline as a whole.

`onAdEvent` is called by the IMA SDK and there's no way for it to be called directly by ExoPlayer. Sorry to redirect you back to the IMA team! It would be up to them to enhance the sample app to support looping if they want to handle this case. I'm not familiar with their BasicExample but you'd probably need to re-request the ad tag every time the content loops to be able to get this to work properly.

You could alternatively try using the ExoPlayer IMA extension, but at the moment I don't think we implement the behavior you want (instead I expect no ads would play after the first play through, as they are already marked as played and we don't re-request the ad tag).

**Comment by markproxy** [comment]
Thanks for the quick response on this. I was surprised by the assertion from the IMA team that ExoPlayer  would be responsible for calling onAdEvent(). I'll dig deeper on what it would take for onAdEvent() to continue to be called each time the video loops. It it indeed challenging to understand where responsibility lies here.
