### ISSUE TITLE
Where is the code that hide a subtitle since being elapsed a given time?

### ISSUE THREAD

**Issue by tuxxon** [google/ExoPlayer#6718]
### Problem.
  I have searched Cue.java, Subtitle.java, SimpleExoPlayer.java and so on  for the codes that hide a subtitle since being elapsed a given time. But I couldn't at this moment.

Please Let me know where the codes are.

**Comment by kim-vde** [comment]
The display of cues is based on events, as you can see in class `Subtitle`. A cue disappears when a new event (containing an empty cue or another cue to display) starts.

The display of subtitles is handled in `SubtitleView`. If you want to implement your own display, you will need to write a new class that implements interface `TextOutput`.

Does that answer your question? If not, could you be more specific about what you are looking for exactly and about what you want to achieve?

**Comment by tuxxon** [comment]
Thank you for your commenting. 

With your comment when I have checked out ***onCues()*** including ***cues.size(), player.getCurrentPostion()***, I got an empty cue and current position.

I am really appreciated for this.
