### ISSUE TITLE
How to play rtmp stream without audio in Exoplayer?

### ISSUE THREAD

**Issue by khyatiChitroda** [google/ExoPlayer#6719]
I am integrating Exoplayer into my application and into this I am getting problem when I am trying to play video without audio it can not play, but if I am enabling the audio it will play the video properly, my code :
````
player = ExoPlayerFactory.newSimpleInstance(this, trackSelector)

val playerView = findViewById<PlayerView>(R.id.simple_player)
playerView.player = player
val rtmpDataSourceFactory = RtmpDataSourceFactory()
val url = mVideoPath
val videoSource = ExtractorMediaSource.Factory(rtmpDataSourceFactory)
  .createMediaSource(Uri.parse(url))

player.prepare(videoSource)

player.playWhenReady = true
````

**Comment by kim-vde** [comment]
Please provide the video path (with and without audio) as described [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/question.md#link-to-test-content).

**Comment by khyatiChitroda** [comment]
rtmp://media1.ambicam.com:1938/dvr30/5ebeca06-910d-4eb8-8032-75cec2824f37

rightnow it is without audio once you check let me know I will add audio into this

**Comment by khyatiChitroda** [comment]
Please check my comment, and please help me as I want to update this issue
today as I have to upload my app

**Comment by khyatiChitroda** [comment]
PLease check mail, I had sent you url, once you check let me know I will add audio into that

**Comment by kim-vde** [comment]
ExoPlayer fails with the following stack trace when trying to open the rtmp url:
````
net.butterflytv.rtmp_client.RtmpClient$RtmpIOException: RTMP error: -3
        at net.butterflytv.rtmp_client.RtmpClient.open(RtmpClient.java:222)
        at com.google.android.exoplayer2.ext.rtmp.RtmpDataSource.open(RtmpDataSource.java:49)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:177)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:462)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:286)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:961)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:394)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
````

There is probably something wrong with the url or with the file because it also fails to play with ffplay.

**Comment by khyatiChitroda** [comment]
if you will try with VLC it will work properly, and even if I will add audio into this url then also it will working properly, you just try now I had enabled audio.

**Comment by kim-vde** [comment]
I still get the same error with ExoPlayer and with ffplay.

Note that, when trying to play the file with ExoPlayer, the error is not thrown by ExoPlayer but by net.butterflytv.rtmp_client.RtmpClient, which indicates that there is probably something wrong with the url.

I also tried with VLC (version 3.0.8) and got the following error: "Your input can't be opened:
VLC is unable to open the MRL '<url>'. Check the log for details."
And in the logs "avio error: Failed to open <url>: Operation not permitted".

What version of VLC are you using? Do you use Media > Open Network Stream to play the file?

**Comment by khyatiChitroda** [comment]
try this,

actually everyday we expired our links for security purpose,

please try this one

rtmp://media1.ambicam.com:1938/dvr30/f9cf7e97-3fcf-4a9d-a7be-dd9ddbaa73f4

Sorry for inconvenience

**Comment by kim-vde** [comment]
I can play this URL with ExoPlayer without problem.

Can you do it as well? Did you build you app with the ExoPlayer RTMP extension?

**Comment by umangsaini** [comment]
Multiple RTMP issues were resolved with the release of v2.10.5. Older versions may have the issue described. Latest ExoPlayer uses the fixed version of RTMP library - net.butterflytv.utils:rtmp-client:3.1.0. 

Regarding audio, in the Demo application, I am able to disable audio track from the "Select Tracks" menu, and video-only playback continues as expected.

Which version of Exoplayer are you working with, and have you tried disabling audio in the Demo Application?

![ExoPlayer_Rtmp_Video_Only](https://user-images.githubusercontent.com/51775549/70164896-01676b00-16e8-11ea-9ee7-605bca053df1.jpg)

**Comment by khyatiChitroda** [comment]
I am using extension rtmp and  library -
net.butterflytv.utils:rtmp-client:3.1.0. same as you said,

PFA, for my demo

https://drive.google.com/file/d/1WSbIJgTY9b3As-W1NM3F_WP11seP5PXR/view?usp=sharing

**Comment by umangsaini** [comment]
The RTMP content URL your demo app is trying to play is not video-only. It's FLV header is advertising both audio and video tracks, which is why ExoPlayer will not play the same.

Refer to this [link](https://github.com/ant-media/LibRtmp-Client-for-Android/issues/70#issuecomment-555025362) and its solution. 

Your FLV header should say only video track present for Exoplayer to play the same. Below is a screenshot of FLVExtractor showing hasAudio flag is true, even when audio track is not present.

![RTMP_Video_Only](https://user-images.githubusercontent.com/51775549/70221526-872df980-176e-11ea-8a54-8e664e404761.png)

**Comment by khyatiChitroda** [comment]
okay Thank you for your response, I need to talk with my team member for this, as we have to done changes into our URL side.
