### ISSUE TITLE
Video playback, which is inside the file

### ISSUE THREAD

**Issue by user968532** [google/ExoPlayer#6720]
Hello. I have a .mp5 file whose structure is: general data, video (.mp4) and preview image. I know the offset (348) and length(341258941) of the video (.mp4), can I play it using the exoplayer?

**Comment by kim-vde** [comment]
You can try using a `ResolvingDataSource` with a `Resolver` resolving the datasource by copying every field except the `position` and the `absoluteStreamPosition`. Something like this for example:

````
long offset = 348;
return new DataSpec(
    dataSpec.uri,
    dataSpec.httpMethod,
    dataSpec.httpBody,
    dataSpec.absoluteStreamPosition + offset,
    dataSpec.position + offset,
    dataSpec.length,
    dataSpec.key,
    dataSpec.flags,
    dataSpec.httpRequestHeaders);
````

**Comment by AlbertKobyakov** [comment]
> You can try using a `ResolvingDataSource` with a `Resolver` resolving the datasource by copying every field except the `position` and the `absoluteStreamPosition`. Something like this for example:
> 
> ```
> long offset = 348;
> return new DataSpec(
>     dataSpec.uri,
>     dataSpec.httpMethod,
>     dataSpec.httpBody,
>     dataSpec.absoluteStreamPosition + offset,
>     dataSpec.position + offset,
>     dataSpec.length,
>     dataSpec.key,
>     dataSpec.flags,
>     dataSpec.httpRequestHeaders);
> ```

forgot to mention, .mp5 is local file

**Comment by user968532** [comment]
> You can try using a `ResolvingDataSource` with a `Resolver` resolving the datasource by copying every field except the `position` and the `absoluteStreamPosition`. Something like this for example:
> 
> ```
> long offset = 348;
> return new DataSpec(
>     dataSpec.uri,
>     dataSpec.httpMethod,
>     dataSpec.httpBody,
>     dataSpec.absoluteStreamPosition + offset,
>     dataSpec.position + offset,
>     dataSpec.length,
>     dataSpec.key,
>     dataSpec.flags,
>     dataSpec.httpRequestHeaders);
> ```

forgot to mention, .mp5 is local file

**Comment by user968532** [comment]
I did so:
Uri uri = Uri.fromFile(new File(Environment.getExternalStorageDirectory() + "/test.mp5"));

long offset = 348;
DataSpec dataSpec1 = new DataSpec(
dataSpec.uri,
dataSpec.httpMethod,
dataSpec.httpBody,
dataSpec.absoluteStreamPosition + offset,
dataSpec.position + offset,
dataSpec.length,
dataSpec.key,
dataSpec.flags);

ResolvingDataSource.Resolver resolver = dataSpec2 -> dataSpec1;
dataSourceFactory = ((DemoApplication) getApplication()).buildDataSourceFactory();
mediaSource = new ProgressiveMediaSource.Factory(new ResolvingDataSource.Factory(dataSourceFactory, resolver)).createMediaSource(uri);

Error:
UnrecognizedInputFormatException: None of the available extractors

**Comment by kim-vde** [comment]
Can you try replacing the length of dataSpec1 by the actual length of the file?

If this does not work, can you provide the file as described [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/question.md#link-to-test-content)?

**Comment by user968532** [comment]
> Can you try replacing the length of dataSpec1 by the actual length of the file?
> 
> If this does not work, can you provide the file as described [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/question.md#link-to-test-content)?

File test.mp5: [here](http://s000.tinyupload.com/index.php?file_id=61561695956973229307)
videoStart: 16
videoLength: 1692377

**Comment by kim-vde** [comment]
I tried to use a resolver as described in [this](https://github.com/google/ExoPlayer/issues/6720#issuecomment-561128479) comment (i.e. without updating the length) and it worked for me.

I did the following:
- In PlayerActivity.java, update method `createLeafMediaSource(Uri, String, DrmSessionManager<ExoMediaCrypto>)` to
````
  private MediaSource createLeafMediaSource(
      Uri uri, String extension, DrmSessionManager<ExoMediaCrypto> drmSessionManager) {
    @ContentType int type = Util.inferContentType(uri, extension);
    switch (type) {
      case C.TYPE_DASH:
        return new DashMediaSource.Factory(dataSourceFactory)
            .setDrmSessionManager(drmSessionManager)
            .createMediaSource(uri);
      case C.TYPE_SS:
        return new SsMediaSource.Factory(dataSourceFactory)
            .setDrmSessionManager(drmSessionManager)
            .createMediaSource(uri);
      case C.TYPE_HLS:
        return new HlsMediaSource.Factory(dataSourceFactory)
            .setDrmSessionManager(drmSessionManager)
            .createMediaSource(uri);
      case C.TYPE_OTHER:
        // return new ProgressiveMediaSource.Factory(dataSourceFactory)
        return createResolverMediaSourceFactory()
            .setDrmSessionManager(drmSessionManager)
            .createMediaSource(uri);
      default:
        throw new IllegalStateException("Unsupported type: " + type);
    }
  }

  private ProgressiveMediaSource.Factory createResolverMediaSourceFactory() {
    return new ProgressiveMediaSource.Factory(new ResolvingDataSource.Factory(dataSourceFactory, new myResolver()));
  }

  private class myResolver implements ResolvingDataSource.Resolver{

    @Override
    public DataSpec resolveDataSpec(DataSpec dataSpec) throws IOException {
      long offset = 16;
      return new DataSpec(
          dataSpec.uri,
          dataSpec.httpMethod,
          dataSpec.httpBody,
          dataSpec.absoluteStreamPosition + offset,
          dataSpec.position + offset,
          dataSpec.length,
          dataSpec.key,
          dataSpec.flags,
          dataSpec.httpRequestHeaders);
    }

    @Override
    public Uri resolveReportedUri(Uri uri) {
      return uri;
    }
  }
````
- Add your file in `media.exolist.json` (the uri can be a path in your device).
- Start the demo app and play the file.

The extractor selected by the `ProgressiveMediaPeriod` is an `Mp4Extractor`.

What version of ExoPlayer are you using?

**Comment by user968532** [comment]
> * Add your file in `media.exolist.json` (the uri can be a path in your device).
> * Start the demo app and play the file.
> 
> The extractor selected by the `ProgressiveMediaPeriod` is an `Mp4Extractor`.

I found a problem, in the original file the video is encrypted (XOR). Please tell me at what stage do I need to decrypt the data?

> What version of ExoPlayer are you using?

2.10.3

**Comment by kim-vde** [comment]
I could play the file you sent with version 2.10.3 of ExoPlayer. I didn't need to decrypt anything. I just applied the steps described in [this](https://github.com/google/ExoPlayer/issues/6720#issuecomment-561301719) comment.

Did you manage to do the same? Is the file you are trying to play the same as the one you sent?

**Comment by user968532** [comment]
> I could play the file you sent with version 2.10.3 of ExoPlayer. I didn't need to decrypt anything. I just applied the steps described in [this](https://github.com/google/ExoPlayer/issues/6720#issuecomment-561301719) comment.
> 
> Did you manage to do the same? Is the file you are trying to play the same as the one you sent?

Yes, unencrypted video opens well. But, the original file contains the encrypted video using xor, at what stage should I decrypt it?

**Comment by user968532** [comment]
[New file ](http://s000.tinyupload.com/index.php?file_id=04783523281189680469)
encryptedVideoStart: 16
encryptedVideoLength: 1692377
key: byte[] key = {1, 2, 3, 4};

    public byte[] XOR(byte[] incomeByteArray, byte[] key) {
        byte[] result = new byte[incomeByteArray.length];
        int j = 0;

        for (int i = 0; i < incomeByteArray.length; i++) {
            result[i] = (byte) (incomeByteArray[i] ^ key[j]);
            j++;
            if (j == key.length) {
                j = 0;
            }
        }
        return result;
    }

**Comment by kim-vde** [comment]
You should implement your own `DataSource` and do the decryption there.

**Comment by user968532** [comment]
> You should implement your own `DataSource` and do the decryption there.

I created my DataSource ([link](https://pastebin.com/g0yBkHNp)), but the error remained
UnrecognizedInputFormatException: None of the available extractors

**Comment by user968532** [comment]
What am I doing wrong?

**Comment by kim-vde** [comment]
Why are you passing the `lastSize` and the `lastOffset` to the `XOR()` method instead of the current ones?

Wouldn't it be simpler if your data source contained another data source (e.g. `DefaultHttpDataSource`, `FileDataSource`, `DefaultDataSource`, ...) and would delegate all the logic to this upstream data source except for the decoding? A bit like in `ResolvingDataSource`.

**Comment by user968532** [comment]
> Why are you passing the `lastSize` and the `lastOffset` to the `XOR()` method instead of the current ones?
Did as you said. Now the error: ParserException: Invalid NAL length

**Comment by user968532** [comment]
Video plays with friezes
Data:
MyDataSource : https://pastebin.com/JGZgU3kV
CreateMediaSource: https://pastebin.com/U9V1J3gK
[localFile:](http://s000.tinyupload.com/index.php?file_id=04783523281189680469)

**Comment by user968532** [comment]
I solved the problem. Thanks for the help.
