### ISSUE TITLE
Get Title of the currently playing song.

### ISSUE THREAD

**Issue by RowlandOti** [google/ExoPlayer#6722]
### [REQUIRED] Searched documentation and issues
Tell us where you’ve already looked for an answer to your question. It’s
important for us to know this so that we can improve our documentation.

### [REQUIRED] Question
Currently attempting to read some metadata i.e the title of the currently playing song alongside the artist. I used the following code:

```java

fun getContentTitleFromMetadata(metadata: Metadata): String? {
        var title: String? = null
        for (i in 0 until metadata.length()) {
            val metadataEntry = metadata[i]
            if (metadataEntry is TextInformationFrame) {
                title = metadataEntry.value
                Timber.d(title)
            } else {
                continue
            }
        }

        return title
    }
```

which I call in 

```java
player?.addListener(object : EventListener {
            override fun onTracksChanged(trackGroups: TrackGroupArray?, trackSelections: TrackSelectionArray?) {
                for (i in 0 until trackGroups!!.length) {
                    val trackGroup = trackGroups.get(i);
                    for (j in 0 until trackGroup.length) {
                        val trackMetadata = trackGroup.getFormat(j).metadata;
                        if (trackMetadata != null) {
                            // We found metadata. Do something with it here!
                            Timber.d(trackMetadata.toString())

                            ExoPlayerUtils.getContentTitleFromMetadata(trackMetadata)
                                .let { playingTitleView.text = it }
                        }
                    }
                }
            }
        })
```

### A full bug report captured from the device
The logcat shows something like below for the log statement:

```java
entries=[TALB: description=null: value=Billboard Hot 100 Singles Chart (07.09.2019), TPE1: description=null: value=Taylor Swift,Jack Antonoff, TPE2: description=null: value=Various Artists, TBPM: description=null: value=149, COMM: language=eng, description=, TDAT: description=null: value=2019-08-23, TPOS: description=null: value=1, TCON: description=null: value=Pop, TSRC: description=null: value=USUG11901486, TPUB: description=null: value=Taylor Swift, TIT2: description=null: value=Daylight, TRCK: description=null: value=89, TYER: description=null: value=2019, WXXX: url=www.MusicalWorld.co, APIC: mimeType=image/jpeg, description=]

```

However, I don't get the actual title of the songs, what I get are random strings from other sections like:

![device-2019-12-03-174004](https://user-images.githubusercontent.com/8356008/70060652-00eda800-15f4-11ea-8935-9922b1735d31.png)

### Link to test content
N/A

**Comment by kim-vde** [comment]
Your file seems to be using ID3 v2 tags to contain the metadata. According to the ID3 v2 specifications, the title is provided in the TIT2 frame. I would therefore seach for this frame instead of searching for instances of `TextInformationFrame`. You can do that by checking the `id` of the `Id3Frame`s.

**Comment by RowlandOti** [comment]
Which methods or objects are these that have the method properties that is that `id`? Actually that is my problem. It is not documented anywhere at all.

**Comment by RowlandOti** [comment]
Which methods or objects are these that have the method properties that is that id? Actually that is my problem. It is not documented anywhere at all. Therefore I don't even know what you mean  by ` checking the id of the Id3Frame`. Is `id == TIT2` the check that would work?

**Comment by kim-vde** [comment]
The object `Id3Frame` has a public property `id`. The ID3 tags are documented [here](http://id3.org/id3v2.3.0#ID3v2_frame_overview). The check would be something like `metadataEntry is id3Frame && metadataEntry.id == "TIT2"`.

**Comment by RowlandOti** [comment]
This worked, well, but I had to do:

```java
fun getContentTitleFromMetadata(metadata: Metadata): String? {
        var title: String? = null
        for (i in 0 until metadata.length()) {
            val metadataEntry = metadata[i]
            Timber.d(metadataEntry.javaClass.simpleName)
            if (metadataEntry is Id3Frame && metadataEntry.id == "TIT2") {
                if (metadataEntry is TextInformationFrame) {
                    title = metadataEntry.value
                    Timber.d(title)
                }
            } else {
                continue
            }
        }

        return title
    }
```

since `Id3Frame` is an abstract class with only one property i.e id.

**Comment by ojw28** [comment]
We have a plan to expose metadata in a normalized way, to avoid the need to step through the individual metadata entries (and understand the specifics of ID3 etc). I've filed a tracking issue here: https://github.com/google/ExoPlayer/issues/6729.
