### ISSUE TITLE
Getting frequent HttpDataSource$HttpDataSourceException errors

### ISSUE THREAD

**Issue by harshmittal29** [google/ExoPlayer#6726]
I am getting very frequent errors when I try to play a video (m3u8) or audi (mp3
) file.

My code to get media source : 

```
private MediaSource buildMediaSource(
            Uri uri,
            String overrideExtension) {
        @C.ContentType int type = TextUtils.isEmpty(overrideExtension) ? Util.inferContentType(uri)
                : Util.inferContentType("." + overrideExtension);
        switch (type) {
            case C.TYPE_DASH:
                return new DashMediaSource.Factory(
                        new DefaultDashChunkSource.Factory(mediaDataSourceFactory),
                        buildDataSourceFactory(false))
                        .createMediaSource(uri);

            case C.TYPE_SS:
                return new SsMediaSource.Factory(
                        new DefaultSsChunkSource.Factory(mediaDataSourceFactory), null)
                        .createMediaSource(uri);
            case C.TYPE_HLS:
                return new HlsMediaSource.Factory(mediaDataSourceFactory)
                        .createMediaSource(uri);
            case C.TYPE_OTHER:
                return new ProgressiveMediaSource.Factory(mediaDataSourceFactory)
                        .createMediaSource(uri);
            default: {
                throw new IllegalStateException("Unsupported type: " + type);
            }
        }
    }
```

Also I could see logs displayed in logcat for a signed build too.

1. How can I avoid HttpDataSourceException ?
2. How can I disable logs from release build?

**Comment by kim-vde** [comment]
Can you send the test content producing errors as described [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/question.md#link-to-test-content)?

Regarding the logs, would setting the log level in class [`Log`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/util/Log.html) to LOG_LEVEL_OFF fix your issue?

**Comment by harshmittal29** [comment]
Log.setLogLevel(LOG_LEVEL_OFF) works.
The content I sometimes get, so I am guessing it might be related to network?

**Comment by kim-vde** [comment]
I need more information to investigate the issue you are having as I cannot reproduce. 

What is the version of ExoPlayer you are using? How do you build the data source? Can you provide a bug report following [these instructions](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/question.md#a-full-bug-report-captured-from-the-device)?

**Comment by harshmittal29** [comment]
Exoplayer : 2.10.8
Lately I have stopped encountering the issue so will close this for now. I will follow the steps in the instructions link if the issue reoccurs.
