### ISSUE TITLE
Provide metadata in a normalized way

### ISSUE THREAD

**Issue by ojw28** [google/ExoPlayer#6729]
### [REQUIRED] Use case description
Make it easier for applications to find and use metadata contained in media files.

Audio file metadata (like artist-name, album-name, song-title, etc.) is generally stored at the start of the file. This is then made available to the application via Format.metadata. Currently each Metadata.Entry contains a single, format-specific, frame (e.g. ID3 TextInformationFrame or Vorbis/FLAC VorbisComment) which generally contains a single piece of metadata (e.g. artist-name). This means applications that want to display this info have to step through each frame, and extract the info in a format-specific way (i.e. they need different code for FLAC files than MP3s). This is quite burdensome to the developer.

### Proposed solution
Present the metadata in a normalized way. This would remove the need for format-specific code from most apps, while also increasing type safety since we can expose numeric fields like trackTotal as integers rather than strings.

**Comment by Samrobbo** [comment]
As of the 2.14 release, `MediaMetadata` is the normalized object for accessing metadata in an easier manner, and it can be accessed through `Player.getMediaMetadata()` or by listening to `EventListener.onMediaMetadataChanged()`.

Currently, `VorbisComment`s are not polled for metadata to fill the MediaMetadata object.

**Comment by Samrobbo** [comment]
In the next release, `VorbisComment` metadata will correctly populate the `MediaMetadata` object in the `Player`. Additional fields will also be available. 

Marking this as closed.
