### ISSUE TITLE
DVR with smoothstreaming

### ISSUE THREAD

**Issue by SamirG** [google/ExoPlayer#673]
We are trying out DVR use case with live smoothstreaming.Not sure if it is implemented in current release branch (1.4.1). what i see is dvrWindowLength and duration is always zero for my stream in SmoothStreamingManifest.
 
Mediacontrol seekbar starts from zero position.my stream DVR windows is 15 minutes, i was expecting that stream should start from 15 minutes and it should allow me seek-back.it works with desktop browser smooth streaming player.
 
pfa my stream manifest file. 
![manifest](https://cloud.githubusercontent.com/assets/5227180/8976237/bbd35cc2-36a7-11e5-976f-29d9dee129b5.png)

---------------------------------------------------------------------------

I tried MPEG DASH dvr link and I get below exception.

stream link :

http://bitlivedemo-a.akamaihd.net/mpds/stream.php?streamkey=bitcodin

exception stack trace :

com.google.android.exoplayer.demo E/ExoPlayerImplInternal﹕ Internal track renderer error.
    com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.BehindLiveWindowException
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:513)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:415)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:205)

**Comment by ojw28** [comment]
We don't support seeking in the DVR window currently. This is tracked by https://github.com/google/ExoPlayer/issues/291.
