### ISSUE TITLE
LoadUsage table in oemcrypto : Signature did not match on Android 9.0

### ISSUE THREAD

**Issue by HarshithaVKadam** [google/ExoPlayer#6732]
The signature generated by OEMcrypto to load Usage table is Invalid.
Please find the adb  logcat below

EDIT: Removed the logcat paste to ease navigation. The logcat is included in the bugreport requested in the issue template.

**Comment by HarshithaVKadam** [comment]
Please find one more adb logcat:

2-06 08:25:13.006  2144  3903 D WVCdm   : Instantiating CDM.
12-06 08:25:13.008  2146  3904 D WVCdm   : Instantiating CDM.
12-06 08:25:13.020  2146  3904 I WVCdm   : [cdm_engine.cpp(481):QueryStatus] CdmEngine::QueryStatus
12-06 08:25:13.021  2146  3909 I WVCdm   : [(0):] Level3 Library 4445 Apr 20 2019 10:13:27
12-06 08:25:13.046  2146  3904 I WVCdm   : [oemcrypto_adapter_dynamic.cpp(573):Initialize] L3 Initialized. Trying L1.
12-06 08:25:13.071  2146  3904 D WVCdm   : [oemcrypto_adapter_dynamic.cpp(590):Initialize] OEMCrypto_Initialize Level 1 success. I will use level 1.
12-06 08:25:13.078  2146  3904 I WVCdm   : [(0):] L3 Terminate.
12-06 08:25:13.088  2146  3904 I WVCdm   : [cdm_engine.cpp(481):QueryStatus] CdmEngine::QueryStatus
12-06 08:25:13.093  2146  3910 I WVCdm   : [(0):] Level3 Library 4445 Apr 20 2019 10:13:27
12-06 08:25:13.113  2146  3904 I WVCdm   : [oemcrypto_adapter_dynamic.cpp(573):Initialize] L3 Initialized. Trying L1.
12-06 08:25:13.134  2146  3904 D WVCdm   : [oemcrypto_adapter_dynamic.cpp(590):Initialize] OEMCrypto_Initialize Level 1 success. I will use level 1.
12-06 08:25:13.135  2146  3904 D WVCdm   : [crypto_session.cpp(668):Open] CryptoSession::Open: Lock: requested_security_level: Default
12-06 08:25:13.143  2146  3904 E WVCdm   : [oemcrypto_usage_table_mock.cpp(552):LoadUsageTableHeader] LoadUsageTableHeader: Signature did not match.
12-06 08:25:13.143  2146  3904 E WVCdm   : [oemcrypto_usage_table_mock.cpp(554):LoadUsageTableHeader] LoadUsageTableHeader: Invalid signature    given: 0FB4F449B1BB2CC5A821D3AA4A54595C05838E29072A73A381FCD68038322412
12-06 08:25:13.144  2146  3904 E WVCdm   : [oemcrypto_usage_table_mock.cpp(556):LoadUsageTableHeader] LoadUsageTableHeader: Invalid signature computed: 54897933490AB33D07CE74DFA59E813D8DB736B58DB7C185879A85FB0C7F3B83
12-06 08:25:13.144  2146  3904 E WVCdm   : [crypto_session.cpp(2077):LoadUsageTableHeader] LoadUsageTableHeader: OEMCrypto_LoadUsageTableHeader error: 30
12-06 08:25:13.144  2146  3904 E WVCdm   : [usage_table_header.cpp(114):Init] UsageTableHeader::Init: load usage table failed, security level: 3
12-06 08:25:13.163  2146  3904 I WVCdm   : [(0):] L3 Terminate.
12-06 08:25:13.216  2144  3906 D WVCdm   : Instantiating CDM.
12-06 08:25:13.220  2146  3904 D WVCdm   : Instantiating CDM.
12-06 08:25:13.223  2146  3904 I WVCdm   : [cdm_engine.cpp(481):QueryStatus] CdmEngine::QueryStatus
12-06 08:25:13.229  2146  3912 I WVCdm   : [(0):] Level3 Library 4445 Apr 20 2019 10:13:27
12-06 08:25:13.254  2146  3904 I WVCdm   : [oemcrypto_adapter_dynamic.cpp(573):Initialize] L3 Initialized. Trying L1.
12-06 08:25:13.276  2146  3904 D WVCdm   : [oemcrypto_adapter_dynamic.cpp(590):Initialize] OEMCrypto_Initialize Level 1 success. I will use level 1.
12-06 08:25:13.276  2146  3904 D WVCdm   : [crypto_session.cpp(668):Open] CryptoSession::Open: Lock: requested_security_level: L3
12-06 08:25:13.281  2146  3904 E WVCdm   : [crypto_session.cpp(2077):LoadUsageTableHeader] LoadUsageTableHeader: OEMCrypto_LoadUsageTableHeader error: 7
12-06 08:25:13.282  2146  3904 E WVCdm   : [usage_table_header.cpp(114):Init] UsageTableHeader::Init: load usage table failed, security level: 3
12-06 08:25:13.310  2146  3904 I WVCdm   : [(0):] L3 Terminate.
12-06 08:25:13.323  2146  3904 I WVCdm   : [cdm_engine.cpp(481):QueryStatus] CdmEngine::QueryStatus
12-06 08:25:13.326  2146  3913 I WVCdm   : [(0):] Level3 Library 4445 Apr 20 2019 10:13:27
12-06 08:25:13.345  2146  3904 I WVCdm   : [oemcrypto_adapter_dynamic.cpp(573):Initialize] L3 Initialized. Trying L1.
12-06 08:25:13.360  2146  3904 D WVCdm   : [oemcrypto_adapter_dynamic.cpp(590):Initialize] OEMCrypto_Initialize Level 1 success. I will use level 1.
12-06 08:25:13.360  2146  3904 D WVCdm   : [crypto_session.cpp(668):Open] CryptoSession::Open: Lock: requested_security_level: L3
12-06 08:25:13.377  2146  3904 I WVCdm   : [(0):] L3 Terminate.
12-06 08:25:13.388  2146  3904 E WVCdm   : [wv_content_decryption_module.cpp(355):GetMetrics] WVContentDecryptionModule::GetMetrics. cdm_identifier not found
12-06 08:25:13.392  2146  3904 E WVCdm   : [wv_content_decryption_module.cpp(415):CloseCdm] WVContentDecryptionModule::Close. cdm_identifier not found.
12-06 08:25:13.392  2146  3904 E WVCdm   : Failed to close cdm. status 12
12-06 08:25:13.438  2144  3906 D WVCdm   : Instantiating CDM.
12-06 08:25:13.439  2146  3904 D WVCdm   : Instantiating CDM.
12-06 08:25:13.446  2146  3904 I WVCdm   : [cdm_engine.cpp(481):QueryStatus] CdmEngine::QueryStatus
12-06 08:25:13.447  2146  3914 I WVCdm   : [(0):] Level3 Library 4445 Apr 20 2019 10:13:27
12-06 08:25:13.466  2146  3904 I WVCdm   : [oemcrypto_adapter_dynamic.cpp(573):Initialize] L3 Initialized. Trying L1.
12-06 08:25:13.488  2146  3904 D WVCdm   : [oemcrypto_adapter_dynamic.cpp(590):Initialize] OEMCrypto_Initialize Level 1 success. I will use level 1.
12-06 08:25:13.488  2146  3904 D WVCdm   : [crypto_session.cpp(668):Open] CryptoSession::Open: Lock: requested_security_level: L3
12-06 08:25:13.505  2146  3904 I WVCdm   : [(0):] L3 Terminate.
12-06 08:25:13.514  2146  3904 I WVCdm   : [cdm_engine.cpp(111):OpenSession] CdmEngine::OpenSession
12-06 08:25:13.515  2146  3915 I WVCdm   : [(0):] Level3 Library 4445 Apr 20 2019 10:13:27
12-06 08:25:13.535  2146  3904 I WVCdm   : [oemcrypto_adapter_dynamic.cpp(573):Initialize] L3 Initialized. Trying L1.
12-06 08:25:13.559  2146  3904 D WVCdm   : [oemcrypto_adapter_dynamic.cpp(590):Initialize] OEMCrypto_Initialize Level 1 success. I will use level 1.
12-06 08:25:13.559  2146  3904 D WVCdm   : [crypto_session.cpp(668):Open] CryptoSession::Open: Lock: requested_security_level: L3
12-06 08:25:13.571  2146  3904 W WVCdm   : [device_files.cpp(1196):RetrieveHashedFile] DeviceFiles::RetrieveHashedFile: /data/vendor/mediadrm/IDM1013/L3/cert.bin does not exist
12-06 08:25:13.579  2146  3904 I WVCdm   : [(0):] L3 Terminate.
12-06 08:25:13.591  2146  3904 I WVCdm   : [cdm_engine.cpp(772):GetProvisioningRequest] CdmEngine::GetProvisioningRequest
12-06 08:25:13.592  2146  3916 I WVCdm   : [(0):] Level3 Library 4445 Apr 20 2019 10:13:27
12-06 08:25:13.612  2146  3904 I WVCdm   : [oemcrypto_adapter_dynamic.cpp(573):Initialize] L3 Initialized. Trying L1.
12-06 08:25:13.634  2146  3904 D WVCdm   : [oemcrypto_adapter_dynamic.cpp(590):Initialize] OEMCrypto_Initialize Level 1 success. I will use level 1.
12-06 08:25:13.644  2146  3904 D WVCdm   : [crypto_session.cpp(668):Open] CryptoSession::Open: Lock: requested_security_level: L3

**Comment by AquilesCanta** [comment]
We can't assist you without the bugreport and sample media requested in the issue template:

The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md). If you're unable to share bug reports or test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Please also update this issue to indicate you’ve done this.
