### ISSUE TITLE
Can I cast my RTMP link to android TV?

### ISSUE THREAD

**Issue by Mehdi-android** [google/ExoPlayer#6734]
# Searched documentation and issues
https://developers.google.com/cast/docs/android_sender/exoplayer

#Question
Hello, I have created an app where I am using exoplayer library to play a live video streaming from RTMP link. Now I want to cast that video to my android TV. I am able to see the casting icon on my TV but not able to see any video playing.
So, I am using following 2 libraries.

> implementation 'com.google.android.exoplayer:extension-cast:2.7.0'
> implementation 'com.google.android.exoplayer:extension-rtmp:2.9.6'

Following is my code where I try to cast my rtmp link to android TV.
```
CastContext castContext = CastContext.getSharedInstance(getActivity());
CastPlayer castPlayer = new CastPlayer(castContext);
castPlayer.setSessionAvailabilityListener(new CastPlayer.SessionAvailabilityListener() {
    @Override
    public void onCastSessionAvailable() {
        MediaMetadata movieMetadata = new MediaMetadata(MediaMetadata.MEDIA_TYPE_MOVIE);
        movieMetadata.putString(MediaMetadata.KEY_TITLE, "Test Stream");
        movieMetadata.putString(MediaMetadata.KEY_ALBUM_ARTIST, "Test Artist");
        movieMetadata.addImage(new 
 WebImage(Uri.parse("https://github.com/mkaflowski/HybridMediaPlayer/blob/master/images/cover.jpg?raw=true")));
        MediaInfo mediaInfo = new MediaInfo.Builder("rtmp://111.222.33.4/something")
                .setStreamType(MediaInfo.STREAM_TYPE_LIVE)
                .setContentType(MimeTypes.BASE_TYPE_APPLICATION)
                .setMetadata(movieMetadata).build();
        final MediaQueueItem[] mediaItems = {new MediaQueueItem.Builder(mediaInfo).build()};
        castPlayer.loadItem(mediaItems[0], Player.REPEAT_MODE_ALL);
    }

    @Override
    public void onCastSessionUnavailable() {
    
    }
});
```

**Comment by AquilesCanta** [comment]
Hi @Mehdi-android, after reading the cast [supported formats page](https://developers.google.com/cast/docs/media), I strongly suspect that RTMP is not supported. Adding @mjmancuso and @anjaneesh for confirmation.

**Comment by mjmancuso** [comment]
Hi @Mehdi-android, @AquilesCanta is correct. RTMP is not currently supported by the player on Chromecast, which focuses on HTTP streaming protocols(Dash, Smooth, HLS).
