### ISSUE TITLE
why exoplayer takes 30 to 40 seconds to stream video from url (firebase)....?

### ISSUE THREAD

**Issue by AshpakSk** [google/ExoPlayer#6736]
//Minimum Video you want to buffer while Playing
    public static final int MIN_BUFFER_DURATION = 1000;
    //Max Video you want to buffer during PlayBack
    public static final int MAX_BUFFER_DURATION = 2000;
    //Min Video you want to buffer before start Playing it
    public static final int MIN_PLAYBACK_START_BUFFER = 1000;
    //Min video You want to buffer when user resumes video
    public static final int MIN_PLAYBACK_RESUME_BUFFER = 1000;

 playerView = (PlayerView)findViewById(R.id.player_view);

        LoadControl loadControl = new DefaultLoadControl.Builder()
                .setAllocator(new DefaultAllocator(true, 16))
                .setBufferDurationsMs(MIN_BUFFER_DURATION,
                        MAX_BUFFER_DURATION,
                        MIN_PLAYBACK_START_BUFFER,
                        MIN_PLAYBACK_RESUME_BUFFER)
                .setTargetBufferBytes(-1)
                .setPrioritizeTimeOverSizeThresholds(true).createDefaultLoadControl();
        TrackSelector trackSelector = new DefaultTrackSelector();

        SimpleExoPlayer player = ExoPlayerFactory.newSimpleInstance(context,trackSelector,loadControl);
        playerView.setPlayer(player);
        // Produces DataSource instances through which media data is loaded.
        DataSource.Factory dataSourceFactory = new DefaultDataSourceFactory(context,
                Util.getUserAgent(context, "Appsta"));
        // This is the MediaSource representing the media to be played.
        MediaSource videoSource = new ProgressiveMediaSource.Factory(dataSourceFactory)
                .createMediaSource(Uri.parse(K.videoUrl));
      // Prepare the player with the source.
        player.prepare(videoSource);

        player.setPlayWhenReady(true);*/

**Comment by giladna** [comment]
@AshpakSk 

you should check in charles  what is the bottleneck
1) dns 
2) handshake
3) ssl
4) latency

once you have the input you can try fix the problematic component
A proven solution that can speed up the playback is using okhttp as http layer and not Connection URL
this will allow you to open a connection to the server where urls are hosted before the playback starts
so the network overhead will be minimal once you try to play some media and playback will start faster.

**Comment by christosts** [comment]
Hi @AshpakSk ,

As @giladna points, inspecting the network/transport delays will help understanding where the possible cause of delay is.

To help you further, can you please share a link to your content, the ExoPlayer version and the device you are working on (if it is a specific device)? If you cannot share any of this information in public, you can send it over email to dev.exoplayer@gmail.com using the subject "Issue #6736"

**Comment by AshpakSk** [comment]
thanks for your response @giladna i will try.
