### ISSUE TITLE
Exo player 2.8.4 request same audio segments (same SEQ)

### ISSUE THREAD

**Issue by eledri** [google/ExoPlayer#6737]
We see that the player is requesting a playlist (http)  from streaming server and  receives a playlist and eventually played duplicate audio segments.
The audio segment should keep always gap of 48128 in the segments (from manifest   d="48128").

please see attach images from wireshark , you can see that the same SEQ is shown twice and eventually cause to see audio repeat.
why this behavior occurs?
also always before the duplicate SEQ we noticed that there is two audio segment in a row, maybe  this what causing the player to ask again the same SEQ? 
![1](https://user-images.githubusercontent.com/4025470/70387996-e41af100-19b4-11ea-9366-d7a11135f4d6.png)
![2](https://user-images.githubusercontent.com/4025470/70387998-e5e4b480-19b4-11ea-9204-6d2618ecca8a.png)

**Comment by christosts** [comment]
Hi,

can you please share a link to the content so I can test locally and also your wireshark logs to compare? If you cannot share these publicly on the ticket, you can email them to dev.exoplayer@gmail.com with subject "Issue #6737".

Thanks

**Comment by ojw28** [comment]
Note: This is normally caused by incorrect manifest updates on the serving side, rather than an issue with the player.
