### ISSUE TITLE
how to get the duration of each video in a playlist ??

### ISSUE THREAD

**Issue by hlkcode** [google/ExoPlayer#6741]
Hello, am new to exoplayer. Through online resources, i was able to get started with it , and am trying to make a video playlist using ConcatenatingMediaSource which works fine. i am trying to get the duration of each video in the list, using player.getDuration() or player.getContentDuration() , but these  give me the duration of the full playlist, while i actually want the duration of each video in the list, not that of the full list. I need to display these durations in a listview (like in the udemy mobile app for example). please kindly assist me. thank you.

**Comment by christosts** [comment]
Hi @hlkcode 

`Player.getDuration()` and `Player.getContentDuration()` return the duration of the currently played item and not the entire list.

As answered in [this issue](https://github.com/google/ExoPlayer/issues/2122#issuecomment-270009553)
> You can use ExoPlayer.getCurrentTimeline to get the media Timeline. Once you have the Timeline you can query the number of windows and their properties (including duration). 

There is a code snippet on how to iterate over the timeline windows available [here](https://github.com/google/ExoPlayer/issues/2122#issuecomment-279531261).

The ability to list the duration of each item in the ConcatenatingMediaSource depends on the kind of media. There are kinds of media the player can tell the duration right after a call to prepare() (e.g., DASH media sources). But for a remote mp4 file (ProgressiveMediaSource), the duration will not be known until the player starts reading the actual mp4 data. Generally, whenever the player makes a change in the timeline, it will raise an [onTimelineChanged](https://github.com/google/ExoPlayer/blob/r2.10.8/library/core/src/main/java/com/google/android/exoplayer2/Player.java#L339) event. The app can register a listener to such events [here](https://github.com/google/ExoPlayer/blob/r2.10.8/library/core/src/main/java/com/google/android/exoplayer2/Player.java#L606).

Note that the ConcatenatingMediaSource will postpone getting the duration of each item for after prepare() if  `lazy preparation` is enabled when [creating the ConcatenatingMediaSource instance](https://github.com/google/ExoPlayer/blob/r2.10.8/library/core/src/main/java/com/google/android/exoplayer2/source/ConcatenatingMediaSource.java#L127).

**Comment by hlkcode** [comment]
Thank you very much for the info, your input was very useful. but unfortunately am working with mp4.  i wish there could be a way to do this (before the player starts reading the file) even for mp4

**Comment by hlkcode** [comment]
So, am thinking of something but i dont if this a good way to do things and if there would be any downside , so i need you point of view on this please. So what if i create another instance of SimpleExoPlayer and then try to mock the whole process of reading each one these mp4 file, maybe on another thread or something, do you think this would work... what could be the pros and cons of this . thank you.

**Comment by christosts** [comment]
We recommend avoiding multiple players because devices many times support only 1 instance of a decoder - see [this thread](https://github.com/google/ExoPlayer/issues/6430#issuecomment-531699053) for example.

There are couple of options listed in [this comment](https://github.com/google/ExoPlayer/issues/4727#issuecomment-416497405) of issue #4727.

Alternatively, may I suggest you try [MediaMetadataRetriever](https://developer.android.com/reference/android/media/MediaMetadataRetriever) to retrieve the data outside the player?

**Comment by hlkcode** [comment]
Sorry for the late response. I went through the listed options in [this comment of issue #4727](https://github.com/google/ExoPlayer/issues/4727#issuecomment-416497405). I will try the seeking option proposed at the number #2 as well as the " MediaMetadataRetriever" altenative you suggested and get back to you. Thank you for the help, really appreciate it

**Comment by hlkcode** [comment]
Hello, sorry you didn't hear from me earlier, i was actually sicked and could work. So, i followed the suggestion number 2 in the comment 4727 mentioned above, and i got the result needed, it worked for me (but i altered it a bit) .. thank you very very much... So copy what the solution down here for future reference sake, in case someone needs it later ... Once thank you very much, you've been very helpful 

> Before attaching the view to the player, start loading each item until the duration becomes known. You can do something like: seekTo(window=0, position=0), listen to onTimelineChanged until player.getDuration() is not C.TIME_UNSET, seekTo(window=1, position=0), listen until player.getDuration() is not C.TIME_UNSET, etc., until all duration of all items are known, and only then attach the view with showMultiWindowTimeBar enabled. (and seek back to window=0, position=0 to start from the beginning).

Here is my little input, as i mentioned earlier in my issue the player.getDuration() method gives in my playlist scenario the duration of the whole list, this is what i did in the onTimelineChanged:
int curIndex = player.getCurrentWindowIndex();
long curDur = timeline.getWindow(curIndex, new Timeline.Window()).getDurationMs();
 to get the duration of the current video each time the timeline changes

**Comment by ojw28** [comment]
> as i mentioned earlier in my issue the player.getDuration() method gives in my playlist scenario the duration of the whole list

As @christosts already mentioned, you are mistaken about this. It does exactly the same thing as the alternative you came up with (you can look at the source code to verify this!)

In any case, we can close this issue since you've found a suitable solution.
