### ISSUE TITLE
Error when compile Flac and other extensions

### ISSUE THREAD

**Issue by saleh-gholamian** [google/ExoPlayer#6743]
Hi. I get this error while trying to follow your instructions:

`/flactest/ExoPlayer/extensions/flac/src/main/jni$ ${NDK_PATH}/ndk-build APP_ABI=all -j4
Android NDK: WARNING: APP_PLATFORM android-14 is higher than android:minSdkVersion 1 in /home/philip/flactest/ExoPlayer/extensions/flac/src/main/AndroidManifest.xml. NDK binaries will *not* be compatible with devices older than android-14. See https://android.googlesource.com/platform/ndk/+/master/docs/user/common_problems.md for more information. 
Android NDK: WARNING: APP_STL gnustl_static is deprecated and will be removed in the next release. Please switch to either c++_static or c++_shared. See https://developer.android.com/ndk/guides/cpp-support.html for more information. 
[arm64-v8a] Compile++ : flacJNI <= flac_jni.cc
[arm64-v8a] Compile++ : flacJNI <= flac_parser.cc
[arm64-v8a] Compile : flacJNI <= bitmath.c
[arm64-v8a] Compile : flacJNI <= bitreader.c
[arm64-v8a] Compile : flacJNI <= bitwriter.c
[arm64-v8a] Compile : flacJNI <= cpu.c
[arm64-v8a] Compile : flacJNI <= crc.c
[arm64-v8a] Compile : flacJNI <= fixed.c
[arm64-v8a] Compile : flacJNI <= fixed_intrin_sse2.c
[arm64-v8a] Compile : flacJNI <= fixed_intrin_ssse3.c
[arm64-v8a] Compile : flacJNI <= float.c
[arm64-v8a] Compile : flacJNI <= format.c
[arm64-v8a] Compile : flacJNI <= lpc.c
[arm64-v8a] Compile : flacJNI <= lpc_intrin_avx2.c
/home/philip/flactest/ExoPlayer/extensions/flac/src/main/jni/flac/src/libFLAC/format.c:47:45: error: 
 use of undeclared identifier ‘VERSION’
FLAC_API const char *FLAC__VERSION_STRING = VERSION;
 ^
/home/philip/flactest/ExoPlayer/extensions/flac/src/main/jni/flac/src/libFLAC/format.c:49:64: error: 
 expected ‘;’ after top level declarator
FLAC_API const char *FLAC__VENDOR_STRING = “reference libFLAC “ VERSION …
 ^
 ;
2 errors generated.
make: *** [/home/philip/flactest/ExoPlayer/extensions/flac/src/main/obj/local/arm64-v8a/objs/flacJNI/flac/src/libFLAC/format.o] Error 1
make: *** Waiting for unfinished jobs….
philip@philip-MS-7B38:~/flactest/ExoPlayer/extensions/flac/src/main/jni$`

Lastly, I would like to ask if there was no way to solve the problem of unsupported formats without using extensions? Or couldn't you present it like a library?
It seems that only few people were able to add extensions!

Any tips are appreciated
Thanks.

**Comment by christosts** [comment]
Hi,

unfortunately, the build scripts and instructions for the flac extension in the release-v2 branch are currently broken. We have fixed those and pushed the commit to the dev-v2 branch, which will be merged and released soon. You can see detailed information in issue #6715, and specifically [this comment](https://github.com/google/ExoPlayer/issues/6715#issuecomment-561091074) offers two solutions to this (wait for the new release or cherry-pick the commit). As third solution, I was able to build flac from release-v2 with NDK r20 by adding the `APP_STL=c++_static` option on the command line, that is

`${NDK_PATH}/ndk-build APP_ABI=all APP_STL=c++_static -j4`

Regarding the overall question of the extensions, not all formats are supported by the Android platform directly. I will redirect you to issue #1434 which contains information on why extensions can't easily be distributed as libraries.
