### ISSUE TITLE
Playback cache file offline not working

### ISSUE THREAD

**Issue by charlie-captain** [google/ExoPlayer#6745]
### Question
when I use cache data source to read cache incompletely, and write data to another file, playing cache partial dataSource would not success in offline.

copy cache to another file, code like below:
```
 val dataSource =CacheDataSource(
            cache,
            DefaultHttpDataSourceFactory()).createDataSource()
        try {
            val totalSize = dataSource.open(DataSpec(uri))
            var data = ByteArray(1024)
            var position = 0
            var bytesRead = 0
            while (bytesRead != C.RESULT_END_OF_INPUT) {
                if (position == data.size) {
                    data = data.copyOf(data.size * 2)
                }
                bytesRead = dataSource.read(data, position, data.size - position)
                if (bytesRead != C.RESULT_END_OF_INPUT) {
                    position += bytesRead
                }
            }
            val bytes = data.copyOf(position)
            FileOutputStream(outPath).use {
                it.write(bytes)
            }
        } catch (e: Exception) {
        } finally {
            dataSource.close()
        }
```

after that, the cache directory will generate cache file, but I can't play cache from cache file, not the copy file.

**Comment by christosts** [comment]
It is not 100% clear what you are trying to achieve and what is failing exactly.

From the snippet of code, I understand you wish to store the data to the filsystem separately from the CacheDataSource and the cache. If that is the case, may I point you to the [TeeDataSource](https://github.com/google/ExoPlayer/blob/r2.11.0/library/core/src/main/java/com/google/android/exoplayer2/upstream/TeeDataSource.java) which provides this functionality directly?

Also, if the overall task is to play offline content, it may be a lot easier if you use ExoPlayer's downloading facilities, described [here](https://exoplayer.dev/downloading-media.html).

**Comment by charlie-captain** [comment]
> It is not 100% clear what you are trying to achieve and what is failing exactly.
> 
> From the snippet of code, I understand you wish to store the data to the filsystem separately from the CacheDataSource and the cache. If that is the case, may I point you to the [TeeDataSource](https://github.com/google/ExoPlayer/blob/r2.11.0/library/core/src/main/java/com/google/android/exoplayer2/upstream/TeeDataSource.java) which provides this functionality directly?
> 
> Also, if the overall task is to play offline content, it may be a lot easier if you use ExoPlayer's downloading facilities, described [here](https://exoplayer.dev/downloading-media.html).

That means I need to make custom DataSink if it could play cache. However, I want to play cache before the download is complete.

**Comment by christosts** [comment]
Hi, 

when you say `I want to play cache before the download is complete`, can I ask exactly what is your app trying to do? For example, is your app trying to download a file using the `DownloadService` and wish to play the file while it is being downloaded?
