### ISSUE TITLE
Exo Player Flac Extension issue

### ISSUE THREAD

**Issue by Shubham1209mathur** [google/ExoPlayer#6747]
Flac Extension is not working in my android app.When i am configuring flac extension it giving error in my Ubuntu PC please tell me how i can integrate this and use flac extension in my app

**Comment by saleh-gholamian** [comment]
I asked the same question yesterday.
See the answer here: https://github.com/google/ExoPlayer/issues/6743#issuecomment-563993365

**Comment by Shubham1209mathur** [comment]
ok @saleh-gholamian thanku

**Comment by christosts** [comment]
Closing as duplicate of #6743.
