### ISSUE TITLE
How to read Pcm Data when playing audio file?

### ISSUE THREAD

**Issue by saleh-gholamian** [google/ExoPlayer#6748]
I'm developing a visualizer for music player. I need to read (Listen) PCM Data When playing audio file.  
Please help me with sample code if possible.
This is my code for playing the audio file:

> Uri audioUri = ...
ExoPlayer mp = ExoPlayerFactory.newSimpleInstance(context, new AudioOnlyRenderersFactory(context), new DefaultTrackSelector());
DataSource.Factory dataSourceFactory = new DefaultDataSourceFactory(context, Util.getUserAgent(context, getString(R.string.app_name)));
MediaSource source = new ProgressiveMediaSource.Factory(dataSourceFactory).createMediaSource(audioUri);
mp.prepare(source);

This is my "AudioOnlyRenderersFactory" class:

`public class AudioOnlyRenderersFactory implements RenderersFactory {

    private final Context context;

    public AudioOnlyRenderersFactory(Context context) {
        this.context = context;
    }

    @Override
    public Renderer[] createRenderers(
            Handler eventHandler,
            VideoRendererEventListener videoRendererEventListener,
            AudioRendererEventListener audioRendererEventListener,
            TextOutput textRendererOutput,
            MetadataOutput metadataRendererOutput,
            DrmSessionManager<FrameworkMediaCrypto> drmSessionManager) {
        return new Renderer[] {new MediaCodecAudioRenderer(context, MediaCodecSelector.DEFAULT, eventHandler, audioRendererEventListener)};
    }
}`

Thanks.

**Comment by andrewlewis** [comment]
Please have a look at `TeeAudioProcessor` and #5268/#6063.
