### ISSUE TITLE
SmoothStreaming Playready streams.

### ISSUE THREAD

**Issue by VishwanathPatil** [google/ExoPlayer#675]
I have stream where chunk size are approximately of Duration 6sec . in Microsoft streams streaming is smooth which has chunk size of duration 2sec. but , in my stream  when it pauses it is still in 720p when it starts it is switching properly to 240p . I know it is our responisibilty to make chunks smaller for smooth playback. but can have some hack customized to switch when my buffered data is very low.without affecting other logic which is very well working.

**Comment by ojw28** [comment]
6 second chunks should work fine with ExoPlayer's adaptive bitrate algorithm, without the need for hacks. Any re-buffering that you are seeing is unlikely to be a direct result of this choice of chunk size.
