### ISSUE TITLE
Is it possible to retry a STATE_FAILED download?

### ISSUE THREAD

**Issue by Stonos** [google/ExoPlayer#6755]
### [REQUIRED] Searched documentation and issues
ExoPlayer's [Downloading Media](https://exoplayer.dev/downloading-media.html) documentation, and the available methods in the `DownloadService` class.

### [REQUIRED] Question
Is it possible to retry a download whose state is `STATE_FAILED`, ideally without losing progress?

I've tried to set the download's stop reason to `STOP_REASON_NONE`, but that didn't seem to do anything.

**Comment by christosts** [comment]
What kind of media are you downloading? For example, segmented (DASH, HLS etc) or a remote MP4.  Can you share the link to your content (if not in public, email to dev.exoplayer@gmail.com with subject "Issue #6755") to test? 

Also please specify the version of the player or you are using.

**Comment by Stonos** [comment]
I'm using ExoPlayer v2.11.0, and I'm downloading Widevine encrypted DASH content.

Just to be clear: downloading works perfectly.

My question is this: If the device's storage gets full while downloading something, then that download will enter a failed state. Is it possible to give the user the option to resume that failed download after they've freed some space?

**Comment by christosts** [comment]
The player will not do that automatically, you have to implement it on your app. You can retrieve which downloads have failed by querying the DownloadIndex and then re-try to download them. For example:

```
DownloadCursor cursor = myDownloadManager.getDownloadIndex().getDownloads(STATE_FAILED);
while(cursor.moveToNext()) {
    Download download = cursor.getDownload();
    DownloadRequest request = download.request;
    DownloadService.sendAddDownload(context, MyDownloadService.class, request, /* foreground= */ false);
}
```

Re-adding the download will use any content that was downloaded prior to failing as long as the download hasn't been removed.

**Comment by Stonos** [comment]
Thank you, this seems to be working!
