### ISSUE TITLE
How to ensure exoplayer starts with a specific bitrate

### ISSUE THREAD

**Issue by krackjack234** [google/ExoPlayer#6756]
### [REQUIRED] How to start exoplayer with a predefined bitrate?

We are trying to start exoplayer with a predefined bitrate say 900k . We are using v 2.9.6

We implemented the below code

```
if(initialBitrate > 0)
{
DefaultBandwidthMeter bandwidthMeter = new DefaultBandwidthMeter.Builder()
                        .setInitialBitrateEstimate(initialBitrate)
                        .build();
player =  ExoPlayerFactory.newSimpleInstance(context, renderersFactory, 
trackSelector, customLoadControl, drmSessionManager, bandwidthMeter);
}
else
{
player =  ExoPlayerFactory.newSimpleInstance(context, renderersFactory, 
trackSelector, customLoadControl, drmSessionManager);
}
```

However we still see that exoplayer is downloading segments of lower bitrate and then switch to the actual bitrate. We see _same segments of different bitrates_ are getting downloaded.

We also see that the player on start goes to READY_STATE (3) and then immediately goes to BUFFERING state (2) and comes back to READY state. 

Here are screenshots from charles

![image](https://user-images.githubusercontent.com/50735078/70711602-ec9e5f00-1d07-11ea-850f-b47fc0e3da8f.png)

![image](https://user-images.githubusercontent.com/50735078/70712028-e361c200-1d08-11ea-85be-a493d38073d0.png)

Any pointers will be very helpful.

**Comment by christosts** [comment]
The player will be try to pick up a bitrate that is close to a fraction of the estimated bandwidth (by default this is 75% (see [here](https://github.com/google/ExoPlayer/blob/r2.9.6/library/core/src/main/java/com/google/android/exoplayer2/trackselection/AdaptiveTrackSelection.java#L227)). You can try to set the initial bitrate by  `initialBitrate * 1.5`.

Note that this will affect the next segment selection, but as the bandwidth is re-adjusted on every download, it is not guaranteed that the next segments will be at the same bitrate.

**Comment by ojw28** [comment]
> We see same segments of different bitrates are getting downloaded

HLS doesn't require that segments start with key-frames, so in the general case it's necessary to download overlapping segments when switching quality. If you know that your segments do start with key-frames then you should make sure this is indicated using the HLS `EXT-X-INDEPENDENT-SEGMENTS` tag. See the [HLS RFC](https://datatracker.ietf.org/doc/rfc8216/) for details.

**Comment by krackjack234** [comment]
Hi @ojw28, @christosts,  in our app, we have different bitrate settings, ABR, High, Data Saver and Good. Each of these bitrate settings (except ABR) is mapped to a specific bitrate. When the user has selected, say High, which is mapped to 900k, we want the player to start with 900k bitrate chunk directly instead of starting with a different bitrate. 

How can we ensure that?

Also we see the player is starting and immediately going to buffer state. We are suspecting this is because of the bitrate switch.  This is our main concern and we want to avoid this

We are using below code for track selection and setting the initial bitrate

 ```
TrackSelection.Factory trackSelectionFactory;
 trackSelectionFactory = new AdaptiveTrackSelection.Factory();
 trackSelector = new DefaultTrackSelector(trackSelectionFactory);

 trackSelectorParameters = new DefaultTrackSelector.ParametersBuilder().build();
 trackSelector.setParameters(trackSelectorParameters);

CustomLoadControl customLoadControl = new CustomLoadControl(new CustomLoadControl.EventListener() {
    @Override
     public void onBufferedDurationSample(long bufferedDurationUs){}}, null);

if(initialBitrate > 0)
{
      DefaultBandwidthMeter bandwidthMeter = new DefaultBandwidthMeter.Builder()
                        .setInitialBitrateEstimate(initialBitrate)
                        .build();
    player =  ExoPlayerFactory.newSimpleInstance(context, renderersFactory, trackSelector, 
                  customLoadControl, drmSessionManager, bandwidthMeter);
}
else
{
    player =  ExoPlayerFactory.newSimpleInstance(context, renderersFactory, trackSelector, 
                        customLoadControl, drmSessionManager);
}

```

Please advice how we can avoid this.

**Comment by tonihei** [comment]
If you want to choose the highest video resolution up to a given maximum (e.g. 900), then you should configure that in the `DefaultTrackSelector` by setting two parameters:
1. `setMaxVideoSize(width, height)` to limit the resolution to your parameters.
2. `setForceHighestSupportedBitrate(true)` to force-select the highest bitrate that is still within your size constraints.

**Comment by tonihei** [comment]
> We see same segments of different bitrates are getting downloaded.

This is most likely because ExoPlayer downloads the first media playlist in the list to determine the available formats and unrelated to any bitrate or ABR algorithm. If your master playlist declares all information, you can enable "chunk-less" preperation, by calling `setAllowChunklessPreparation(true)` on the `HlsMediaSource.Factory`.

**Comment by krackjack234** [comment]
Hi @tonihei , for setting the max video bitrate we are using the below code

```
trackSelectorParameters = new DefaultTrackSelector.ParametersBuilder()
                        .setMaxVideoBitrate(maxVideoBitrate)
```

Is it not the right way to force explayer to remain within this limit?

Our problem is making exoplayer to start with a specific bitrate. 

What I understand from the explanation above is unless we select chunkless preparation, exoplayer will always dowloand 1-2 segments of the first bitrate mentioned in the master m3u8 (even if our master m3u8 has all the renditions mentioned), before switching to the initial bitrate that we passed in **setInitialBitrateEstimate** parameter.

Please correct if our understanding is wrong.

Also please confirm if the below code is correct to set the initial start bitrate.

 ```
DefaultBandwidthMeter bandwidthMeter = new DefaultBandwidthMeter.Builder()
                       .setInitialBitrateEstimate(initialBitrate)
                       .build();
```

**Comment by tonihei** [comment]
> Is it not the right way to force explayer to remain within this limit?

Yes, that's right. I thought you wanted to use a video size. But using a video bitrate is equally possible.

> What I understand from the explanation above is unless we select chunkless preparation, exoplayer will always dowloand 1-2 segments of the first bitrate mentioned in the master m3u8 (even if our master m3u8 has all the renditions mentioned),

That happens if you are *NOT* using chunkless preparation or your master playlist doesn't contain all the information needed to do chunkless preperation.

> Our problem is making exoplayer to start with a specific bitrate.
> before switching to the initial bitrate that we passed in setInitialBitrateEstimate parameter.

It's always preferable to set parameter in `DefaultTrackSelector` instead of overwriting the initial bitrate estimate. Setting the `maxVideoBitrate` should already be sufficient to limit the bitrate. If you never want to select another (lower) bitrate, then please also use `setForceHighestSupportedBitrate(true)` as suggested above.

**Comment by krackjack234** [comment]
Thanks @tonihei. Our requirement is to start with a predefined bitrate if user is not selecting ABR. But if user selects ABR, we should limit the max video bitrate used.

Hence we used setInitialBitrateEstimate for start of playback and maxVideoBitrate to limit ABR switch.

We are seeing one issue where the player is reporting READY state and then immediately going to BUFFERING state before coming back to READY.

Should we increasse MAX_BUFFER_MS to avoid the initial buffering after reaching first READY state?

**Comment by krackjack234** [comment]
> If you know that your segments do start with key-frames then you should make sure this is indicated using the HLS `EXT-X-INDEPENDENT-`

hi @ojw28  our master m3u8 do mention the key EXT-X-INDEPENDENT but still we see 3 different bitrate switch before playback start. First, player starts with 224k then to 664k and ultimately to 990k which is the desired one.

**Comment by ojw28** [comment]
It's somewhat unclear whether you're using `EXT-X-INDEPENDENT-SEGMENTS` (there was a response here that has subsequently disappeared).

It would probably be easier to discuss this if you could provide concrete reproduction steps, with a piece of media we can access. We can then tell you exactly why each segment is being requested.

**Comment by krackjack234** [comment]
hi @ojw28  since the hls url is from client, so I cant share it publicly. Is there a way to share it in private?

**Comment by ojw28** [comment]
You can mail `dev.exoplayer@gmail.com`. If there's any kind of geo-restriction on the stream, please indicate where it's restricted to in the email.

**Comment by ojw28** [comment]
Please also include `Issue #6756` in the subject, and let us know here once you've sent it our way. Thanks!

**Comment by krackjack234** [comment]
Hi @ojw28 , we have sent the mail

**Comment by krackjack234** [comment]
Hi @ojw28  we can close this issue as we have found the solution. Using maxVideoBitrate and setForceHighestSupportedBitrate(true) did the trick and not setInitialBitrateEstimate.

Thanks @tonihei  for pointing this out in earlier reply. We were using setInitialBitrateEstimate which was not the right one.
