### ISSUE TITLE
FLAC_EXT_PATH Failed

### ISSUE THREAD

**Issue by Shubham1209mathur** [google/ExoPlayer#6758]
Hello I am using exo player and my flac format is not running.When i am following flac extension tutorial at last i am getting error in 

 ****Build the JNI native libraries from the command line:****
cd "${FLAC_EXT_PATH}"/jni && \
${NDK_PATH}/ndk-build APP_ABI=all -j4

Getting this error 

No command '<path' found, did you mean:
 Command 'mpath' from package 'libmodule-path-perl' (universe)
 Command 'xpath' from package 'libxml-xpath-perl' (universe)
<path: command not found

**Comment by christosts** [comment]
Can you please copy/paste the output of the following variables when you get the error? (I'm assuming you are working on a Linux machine with a bash shell) 

- What is the content of the `EXOPLAYER_ROOT` variable? Run `echo $EXOPLAYER_ROOT`
- What is the content of the `FLAC_EXT_PATH` variable? Run `echo $FLAC_EXT_PATH`
- What is the content of the `NDK_PATH` variable? Run `echo $NDK_PATH`

All three variables should contain valid file-system paths pointing to (i) the ExoPlayer root folder, (ii) the Flac extension folder inside the ExoPlayer and (iii) the ndk folder.

**Comment by Shubham1209mathur** [comment]
Yes I am working on Linux 

Please check my attached image 

![cmd](https://user-images.githubusercontent.com/26159909/71058237-18e13200-2185-11ea-9555-d5c1c8e9e846.png)

**Comment by christosts** [comment]
The `NDK_PATH` variable is not set correctly. You need to replace `"<path to Android NDK>"` with the actual filesystem path where the NDK is. For example, if the NDK is installed in `/home/username/android/ndk` on your computer, then this command should look like

`NDK_PATH=/home/username/android/ndk`

**Comment by Shubham1209mathur** [comment]
ok i have done that but when i am playing flac extension file then i am getting below error.

----------------------------------------------------------------------------
E/LoadTask: Unexpected exception loading stream
    java.lang.RuntimeException: com.google.android.exoplayer2.ext.flac.FlacDecoderException: Failed to load decoder native libraries.
        at com.google.android.exoplayer2.ext.flac.FlacExtractor.init(FlacExtractor.java:117)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractorHolder.selectExtractor(ExtractorMediaPeriod.java:975)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:891)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: com.google.android.exoplayer2.ext.flac.FlacDecoderException: Failed to load decoder native libraries.

**Comment by christosts** [comment]
Did the native flac library build correctly? What was the output of the `${NDK_PATH}/ndk-build APP_ABI=all -j4` command?

For example, in a successful build, the output should finish with this

```
[x86_64] SharedLibrary  : libflacJNI.so
[arm64-v8a] SharedLibrary  : libflacJNI.so
[armeabi-v7a] SharedLibrary  : libflacJNI.so
[x86_64] Install        : libflacJNI.so => libs/x86_64/libflacJNI.so
[armeabi-v7a] Install        : libflacJNI.so => libs/armeabi-v7a/libflacJNI.so
[arm64-v8a] Install        : libflacJNI.so => libs/arm64-v8a/libflacJNI.so
[x86] Compile        : flacJNI <= stream_encoder.c
[x86] SharedLibrary  : libflacJNI.so
[x86] Install        : libflacJNI.so => libs/x86/libflacJNI.so
```

In path `${FLAC_EXT_PATH}/libs`, there should be 4 directories, each one containing the file `libflacJNI.so` (a different shared object per CPU architecture).

Do you see those files?

**Comment by Shubham1209mathur** [comment]
Cant get this response can you please help to setup this through teamview or some other tools.

**Comment by ojw28** [comment]
> Cant get this response can you please help to setup this through teamview or some other tools.

This is beyond the level of support that we can provide, sorry.
