### ISSUE TITLE
How to get BufferInfo in ExoPlayer 2?

### ISSUE THREAD

**Issue by saleh-gholamian** [google/ExoPlayer#6759]
Hi,
**BufferInfo** was available in ExoPlayer 1 in the **processOutputBuffer** method, But in curently veresion bufferInfo not exist in **processOutputBuffer**
In version 1 I had access to **BufferInfo** by extending **MediaCodecAudioRenderer** Class and implementing **processOutputBuffer**
As you can see below

Version 1:
```
@Override
protected boolean processOutputBuffer(long positionUs,
                                      long elapsedRealtimeUs,
                                      MediaCodec codec,
                                      ByteBuffer buffer,
                                      MediaCodec.BufferInfo bufferInfo, //TODO: BufferInfo
                                      int bufferIndex,
                                      boolean shouldSkip)
        throws com.google.android.exoplayer.ExoPlaybackException {

    //using bufferInfo

    return super.processOutputBuffer(positionUs,
            elapsedRealtimeUs,
            codec,
            buffer,
            bufferInfo,
            bufferIndex,
            shouldSkip);
}
```
Last Version:
```
    protected boolean processOutputBuffer(long positionUs,
                                          long elapsedRealtimeUs,
                                          MediaCodec codec,
                                          ByteBuffer buffer,
                                          int bufferIndex,
                                          int bufferFlags,
                                          long bufferPresentationTimeUs,
                                          boolean isDecodeOnlyBuffer,
                                          boolean isLastBuffer,
                                          Format format) throws ExoPlaybackException {

        return super.processOutputBuffer(positionUs,
                elapsedRealtimeUs,
                codec,
                buffer,
                bufferIndex,
                bufferFlags,
                bufferPresentationTimeUs,
                isDecodeOnlyBuffer,
                isLastBuffer,
                format);
    }
```
As you can see there is no **BufferInfo** inside **processOutputBuffer** method in the last version
I need to get BufferInfo for read '**size**' and '**offset**' and '**presentationTimeUs**', How to do this in the latest version?

**Comment by ojw28** [comment]
All the information is still there. It's just in slightly different places:
* `bufferFlags` in V2 is the same as `bufferInfo.flags` in V1
* `bufferPresentationTimeUs` in V2 is the same as `bufferInfo.presentationTimeUs` in V1
* `buffer.position()` in V2 is the same as `bufferInfo.offset` in V1
* `buffer.limit() - buffer.position()` in V2 is the same as `bufferInfo.size` in V1

**Comment by saleh-gholamian** [comment]
> All the information is still there. It's just in slightly different places:

    bufferFlags in V2 is the same as bufferInfo.flags in V1
    bufferPresentationTimeUs in V2 is the same as bufferInfo.presentationTimeUs in V1
    buffer.position() in V2 is the same as bufferInfo.offset in V1
    buffer.limit() - buffer.position() in V2 is the same as bufferInfo.size in V1

Very Thanks
