### ISSUE TITLE
Is it possible to buffer the individual parts of the video?

### ISSUE THREAD

**Issue by AlbertKobyakov** [google/ExoPlayer#6762]
Is it possible to buffer the individual parts of the video? For example, I have a video that lasts 50 seconds. Can I buffer 0-2, 10-12 and 20-22 seconds? If the current position position has changed by 3 seconds, then 3-5, 13-15 and 23-25 and so on.

**Comment by Samrobbo** [comment]
Hi, trying to get some context here. 

What is it you're trying to achieve? Why should the player not buffer all of the upcoming media?
