### ISSUE TITLE
Provide option to zoom in 360 playbacks

### ISSUE THREAD

**Issue by nikunjpalsana** [google/ExoPlayer#6763]
[No information provided]

**Comment by Samrobbo** [comment]
Hi,

Can you please fill out the template, rather than just copying it here. 

Thanks

**Comment by tejaskanani1** [comment]
I also required this type of functionality to manage zoom in/out.

**Comment by tejaskanani1** [comment]
hey @ojw28 , Is there any update regarding the issue?

**Comment by ojw28** [comment]
I don't think we have any plans to add support for this directly in the library. You would have to implement it in your own UI components.
