### ISSUE TITLE
Non-european closed captions support

### ISSUE THREAD

**Issue by moacir69** [google/ExoPlayer#6764]
### [REQUIRED] Searched documentation and issues
I have searched in https://github.com/google/ExoPlayer/issues.

### [REQUIRED] Question
Does ExoPlayer support Arabic, Chinese and Japanese closed captions (embedded subtitles) in HLS and MPEG-DASH streams?

Thank you,

Moacir

**Comment by icbaker** [comment]
We support WebVTT and CEA-608 in HLS & DASH, and also TTML in DASH:
https://exoplayer.dev/supported-formats.html#dash
https://exoplayer.dev/supported-formats.html#hls

WebVTT requires UTF-8:
https://www.w3.org/TR/webvtt1/#file-structure

TTML recommends UTF-8:
https://www.w3.org/TR/2018/REC-ttml1-20181108/#ttml-content-doctype
And we decode using XmlPullParser, which reads the encoding from the XML.

CEA-608 seems to have less complete support for non-western characters.

In WebVTT and TTML it should just work.

It's probably best to just try it out, and if you see problems please file new issues with specific repro steps and sample media.

**Comment by msilva-verimatrix** [comment]
OK, thanks for the quick reply.
Warm regards,

Moacir
