### ISSUE TITLE
ExoPlayer 2.11.0 update breaks DRM Callbacks sent in AnalyticsListener via DefaultDrmSessionEventListener

### ISSUE THREAD

**Issue by saurabharora90** [google/ExoPlayer#6765]
### [REQUIRED] Issue Description.

Drm Callback is broken after upgrading to ExoPlayer 2.11.0:

Since `DrmSessionManager` is now injected into `MediaSources` instead of `Renderers` (a very welcome change), the `DefaultDrmSessionManager` no longer has a listener to send callbacks to. Till ExoPlayer 2.10.8, `SimpleExoPlayer` would check if the `drmSessionManager` was a `DefaultDrmSessionManager` and if yes, it would set up the listener to route the callbacks through the Analytics Collector.

### [REQUIRED] Reproduction steps
Run the sample app with a DRM video such as Wideview Dash: MP4, Secure HD. See logs in logcat and no DRM events such as `drmSessionAcquired` are logged. 

### [REQUIRED] Version of ExoPlayer being used
2.11.0

Would suggest adding this change in the Changelog and also updating the sample app to reflect that we need to set up the listener in the `DefaultDrmSessionManager` since `SimpleExoPlayer` will not do it for us anymore. Currently, this is how I am handling it:

```
((DefaultDrmSessionManager<ExoMediaCrypto>) drmSessionManager)
          .addListener(new Handler(player.getApplicationLooper()), player.getAnalyticsCollector());
```

**Comment by Samrobbo** [comment]
Looking into this.

**Comment by tonihei** [comment]
Thanks for reporting this bug, this was an oversight when adding the per-MediaSource DRM configuration and we should fix this.

In the meantime, you can try to wire it up yourself like this:
```
DefaultDrmSessionManager drmManager = new DefaultDrmSessionManager.Builder().build();
MediaSource source = new MediaSource.Builder().setDrmSessionManager(drmManager).build();
SimpleExoPlayer player = new SimpleExoPlayer.Builder(context).build();

Handler playerHandler = new Handler(player.getApplicationLooper());
drmManager.addListener(playerHandler, player.getAnalyticsCollector());

player.prepare(source);
```

That probably works as least as good as the previous version for now.

It probably won't work in the long run though because as soon as we continue the DRM rework to load keys before they are actually used, the event association to media source will fail with this code.

**Comment by tonihei** [comment]
@AquilesCanta  Could you have a look at this issue?

**Comment by icbaker** [comment]
This should now be working on the dev-v2 branch.
