### ISSUE TITLE
The audio sounds terrible at 1.5 speed or 0.5 speed

### ISSUE THREAD

**Issue by imcloud** [google/ExoPlayer#6768]
### [REQUIRED] Issue description
When I play mp3 at 0.5x speed, the sound sounds weird, maybe it's tone shifting, and there is a little noise. I don't want to change tone or noise.
Compared to mac, the quality is much worse,you really should try it with the following file

### [REQUIRED] Reproduction steps
play a mp3 file at 0.5 speed

### [REQUIRED] Link to test content
[demo.mp3.zip](https://github.com/google/ExoPlayer/files/3967521/demo.mp3.zip)

### [REQUIRED] Version of ExoPlayer being used
2.10.8

### [REQUIRED] Device(s) and version(s) of Android being used
3.4.2

I use another player which seems to work better,sounds similar to mac playback
https://github.com/pili-engineering/PLDroidPlayer

**Comment by Samrobbo** [comment]
Hi,

Is it possible to get some clearer reproduction steps? What methods are you calling to adjust the playback speed, when are they being called etc? Code snippets would be very helpful. 

In case it is related, what device and version of android are you using? (I saw 3.4.2, but there is no version 3.4.2 for android)

**Comment by Samrobbo** [comment]
I have noticed the issues that you have described, and this problem is already being tracked by #6575. Please refer there for more information on our plans with this.
