### ISSUE TITLE
Identify playlist item in PlaybackStats

### ISSUE THREAD

**Issue by jakoss** [google/ExoPlayer#6772]
### [REQUIRED] Searched documentation and issues
I looked up the code and documentation on webpage

### [REQUIRED] Question
I'm looking to use `PlaybackStatsListener` and `PlaybackStats` for playback reporting.
On callback call i got 2 parameters - `EventTime` and `PlaybackStats`. Now - i can get total time spent listening to particular playlist item from `PlaybackStats`, but i'm not sure how to identify playlist item that these stats belong to. Can i assume that when this callback gets called i can get current playlist item window index using `Player.currentWindowIndex - 1` ? For me - the ideal case would be to get tag of this particular playlist item.

**Comment by tonihei** [comment]
The `EventTime` argument contains the event time at which the playback session started. So you can just use the information provided in there to retrieve the tag of the window for example: 
```
if (evenTime.timeline.isEmpty()) {
  // Tag not populated yet. This is first item in the playlist.  
  // Will be fixed by the new playlist API in ExoPlayer 2.12.
  // See https://github.com/google/ExoPlayer/issues/5155.
}
return eventTime.timeline.getWindow(eventTime.windowIndex, new Window()).tag;
```

**Comment by jakoss** [comment]
Great, that's what i needed. Thanks!

**Comment by ojw28** [comment]
Marking as a documentation candidate.
