### ISSUE TITLE
proguard rules for av1

### ISSUE THREAD

**Issue by master255** [google/ExoPlayer#6773]
You need to add proguard rules for new av1 extension:
`-keep class com.google.android.exoplayer2.ext.av1.** { *; }`

Otherwise, an error occurs:
Error instantiating AV1 extension
Caused by java.lang.NoSuchMethodException
<init> [long, class android.os.Handler, interface c.b.a.a.e1.s, int]...

**Comment by ojw28** [comment]
Could you confirm that it's sufficient to add the following:
```
-dontnote com.google.android.exoplayer2.ext.av1.Libgav1VideoRenderer
-keepclassmembers class com.google.android.exoplayer2.ext.av1.Libgav1VideoRenderer {
  <init>(long, android.os.Handler, com.google.android.exoplayer2.video.VideoRendererEventListener, int);
}
```

**Comment by master255** [comment]
@ojw28 , Yes Yes. I confirm. Is this the final version of the rules?
Maybe we need to test the playback of AV1? I have not seen such files yet.
