### ISSUE TITLE
Mp4Extractor sniffer does not recognize a file

### ISSUE THREAD

**Issue by bokach-stanislav** [google/ExoPlayer#6774]
### [REQUIRED] Issue description
com.google.android.exoplayer2.extractor.mp4.Sniffer cannot recognize the stream (see a link to torrent containing m4b files below).
ExoPlayer can play a file when media source is created with Mp4Extractor factory:
`MediaSource mediaSource = new ProgressiveMediaSource.Factory(dataSourceFactory, Mp4Extractor.FACTORY)`

However, exception is thrown when media source should recognize format:
`MediaSource mediaSource = new ProgressiveMediaSource.Factory(dataSourceFactory)`

### [REQUIRED] Reproduction steps
Download m4b files from torrent. Put any of them to test device/emulator. Define PATH_TO_FILE. Use the simplest code to play it by ExoPlayer:
```
mp = new SimpleExoPlayer.Builder(context)
	.setTrackSelector(new DefaultTrackSelector(context))
	.build();
mp.setAudioAttributes(new AudioAttributes.Builder()
	.setContentType(C.CONTENT_TYPE_MUSIC)
	.setUsage(C.USAGE_MEDIA).build());
DefaultDataSourceFactory dataSourceFactory = new DefaultDataSourceFactory(context, "none");
MediaSource mediaSource = new ProgressiveMediaSource.Factory(dataSourceFactory)
	.createMediaSource(Uri.fromFile(new File(PATH_TO_FILE)));
mp.prepare(mediaSource);
mp.setPlayWhenReady(true);
```

### [REQUIRED] Link to test content
[Torrent file](https://rutracker.org/forum/dl.php?t=5781821)

### [REQUIRED] A full bug report captured from the device
```
2019-12-17 17:21:03.783 25627-25627/mindmine.audiobook I/ExoPlayerImpl: Init 64ad1d2 [ExoPlayerLib/2.11.0] [blueline, Pixel 3, Google, 29]
2019-12-17 17:21:03.874 25627-25756/mindmine.audiobook E/ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor, AmrExtractor, Ac4Extractor) could read the stream.
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractorHolder.selectExtractor(ProgressiveMediaPeriod.java:1095)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:974)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:391)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
```

### [REQUIRED] Version of ExoPlayer being used
2.9.6 , 2.11.0

### [REQUIRED] Device(s) and version(s) of Android being used
Pixel 3, Android 10

**Comment by Samrobbo** [comment]
Hi,

It seems I can not access that file. If possible, please can you zip the test content and send it to dev.exoplayer@gmail.com using a subject in the format "Issue #6774"? Please also update this issue to indicate you’ve done this.

**Comment by bokach-stanislav** [comment]
Hi,
Please use this link to download a test file from Google Drive:
https://drive.google.com/open?id=1XyeOiy49CbH74h9Aui9b943tjD9Nxvz8

**Comment by Samrobbo** [comment]
Hi Stanislav,

Unfortunately corporate/technical restrictions means I can't actually download that.

Would it be possible for you to put the file on to a server and provide a URI accessible by http? 

Sorry for the inconvenience.

**Comment by bokach-stanislav** [comment]
Hi,
Could you please let me know on which server I can upload the file (~700Mb) so you can access it?

**Comment by ojw28** [comment]
The media is malformed, because it indexes data that's 8 bytes beyond the end of the file. That said, I think we might just relax the test we apply here to let this type of media play anyway.
