### ISSUE TITLE
Not smooth playing cbcs content on Samsung Galaxy Note 9

### ISSUE THREAD

**Issue by kyungtae-K** [google/ExoPlayer#6777]
### [REQUIRED] Question
used device : galaxy note 9
used app : https://github.com/google/ExoPlayer/tree/release-v2
The video is not smooth when playing cbcs content using exoplayer (release-v2) on samsung galaxy note 9(Android 9).
cbcs content playback performance is this normal?

### A full bug report captured from the device
[logcat.log](https://github.com/google/ExoPlayer/files/3976703/logcat.log)
[debug_console.log](https://github.com/google/ExoPlayer/files/3976704/debug_console.log)
![screenshot](https://user-images.githubusercontent.com/7933160/71057364-c82b0280-219f-11ea-964f-409ef6644112.png)

### Link to test content
{
        "name": "WV: Secure HD (cbcs,MP4,H264)",
        "uri": "https://storage.googleapis.com/wvmedia/cbcs/h264/tears/tears_aes_cbcs_hd.mpd",
        "drm_scheme": "widevine",
        "drm_license_url": "https://proxy.uat.widevine.com/proxy?provider=widevine_test"
}

**Comment by Samrobbo** [comment]
Can I get a little more information? I can't seem to reproduce this.

In what way is it not smooth? Is the audio stuttering?

**Comment by kyungtae-K** [comment]
problem is the video track.
If you look at the exoplayer screen shot log during playback, the db (droppedBufferCount) increases, so the video track playback is not smooth.
And my Galaxy Note 9 uses the Exynos 9810 AP.
However, the Galaxy Tab S6, which uses the Qualcomm Snapdragon 855 SM8150 AP, will play well.
Is it because of ap performance difference?

**Comment by Samrobbo** [comment]
Potentially?

We'll look into this in the new year, as the team are almost all taking time off for the holiday period.

**Comment by kyungtae-K** [comment]
Do you have any progress on this?

**Comment by Samrobbo** [comment]
It appears this is device specific, in that case I would recommend you report this issue to the device manufacturer, as they will have to fix it on their side. 

Thanks.
