### ISSUE TITLE
One HLS stream is not played

### ISSUE THREAD

**Issue by dreich** [google/ExoPlayer#6778]
Please, look at this stream: https://g7.wi.com.ua/hls/glassru.m3u8.
May you check why it is not played using ExoPlayer?

**Comment by Samrobbo** [comment]
Hi, 

It appears that the site can not be reached. (`g7.wi.com.ua’s server IP address could not be found.`). 

As a result, it won't play on ExoPlayer or any other player.

**Comment by dreich** [comment]
Excuse me, it CAN be reached. I can watch it with VLC player.

**Comment by dreich** [comment]
Strange: from one PC it opens in browser and in another it doesn't.

**Comment by Samrobbo** [comment]
For me, it will not open in ExoPlayer, Chrome or VLC. 

This may explain why ExoPlayer is struggling to play it?

**Comment by dreich** [comment]
Thank you for your time! 
Maybe there is some problem with DNS, because this stream can be accessed by IP: http://89.187.0.3/hls/glassru.m3u8. And it IS PLAYED by ExoPlayer.
The issue may be closed now!

**Comment by Samrobbo** [comment]
Weird! 

Feel free to file a new issue if you run into further issues :)
