### ISSUE TITLE
Supporting rendering a playlist overlay on top of the player.

### ISSUE THREAD

**Issue by krackjack234** [google/ExoPlayer#6780]
Before filing a question:
-----------------------
### [REQUIRED] 
Searched documentation and issues but didnt get the answer

### [REQUIRED] Question
Does exoplayer UI support rendering a playlist overlayed on top of player?

Can we draw a playlist (with asset cards) using **exoplayer.ui** class and let exoplayer control playback of any selected asset?

**Comment by Samrobbo** [comment]
Hi,

Currently, this functionality does not exist. It would be a RecyclerView with an item for each window from what I know.

This isn't actually possible with core ExoPlayer at the moment, as the player does not have all the meta data. 

We are planning to extend some of our functionality, which would make it easier to do, however there is no set timeline as to when this will be done.

**Comment by ojw28** [comment]
I don't really understand what this issue is tracking. It's possible to build this kind of UI today in application code, and it's not the job of the library to implement application UI to this extent. Please could you clarify?

**Comment by Samrobbo** [comment]
I must have misunderstood what the current capabilities are. In that case, happy to close.
