### ISSUE TITLE
Can you play fragmented mp4?

### ISSUE THREAD

**Issue by ilpelatodijavascript** [google/ExoPlayer#6782]
Hello, I'm trying to play a fragmented mp4 file on my player.
This is how I set the source:
```
File fragmentedFile = new File("/media", "testfile.mp4");
DataSource.Factory dataSourceFactory = new DefaultDataSourceFactory(context, Util.getUserAgent(context, "MyUserAgent"));
MediaSource videoSource = new ProgressiveMediaSource.Factory(dataSourceFactory).createMediaSource(Uri.fromFile(fragmentedFile));
simpleExoPlayer.setPlayWhenReady(true);
simpleExoPlayer.prepare(videoSource);
```
And this is the error I get:
```
E/ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor, AmrExtractor, Ac4Extractor) could read the stream.
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractorHolder.selectExtractor(ProgressiveMediaPeriod.java:1074)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:952)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:394)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:914)
```
Video format: mp4
Video codec: H264 MPEG-4 AVC
Audio codec: MPEG AAC

It seems strange to me that it can't play fragmented videos and I know that the video has no problems (For example, it works fine on VLC).

I tried
```
DefaultExtractorsFactory extractorsFactory = new DefaultExtractorsFactory().setFragmentedMp4ExtractorFlags(FragmentedMp4Extractor.FLAG_WORKAROUND_IGNORE_EDIT_LISTS);
```
but same error.
Am I missing something or you cannot play fragmented videos with exoplayer?
Thanks

**Comment by Samrobbo** [comment]
Hi, 

Is it possible for you to provide us with a link to the test content, so that I can reproduce the issue.
(feel free to send to dev.exoplayer@gmail.com with Issue #6782 as the title if you do not with to share publicly)

Thanks

**Comment by ojw28** [comment]
> Am I missing something or you cannot play fragmented videos with exoplayer?

We do support fragmented MP4. Please provide a link to the test content, or send it to us as requested above, so that we can have a look.

> I know that the video has no problems (For example, it works fine on VLC).

This does not necessarily mean the video has no problem. All it means is that VLC can play it. Those two things are not the same.

**Comment by ilpelatodijavascript** [comment]
I sent an email

**Comment by ojw28** [comment]
It's unclear from your email what you're trying to do, but it sounds more complicated than just playing a fragmented MP4 file. You mention that the file plays fine once it's fully copied, which suggests there's no issue with ExoPlayer's FMP4 support.

Note that it's generally not valid to give ExoPlayer a File URI to play if the file is still incomplete or being modified. That sounds very uncontrolled in general. I think you should rethink your approach of whatever it is that you're trying to accomplish.

**Comment by ilpelatodijavascript** [comment]
After some tests I've found out that the video plays fine untill the end of the fragment, so, at the beginning, it only shows 3/4 seconds, but if you set the video on loop it plays fine for 3/4 more seconds and so on.
So I tried to put the player position back to the last position before restarting the video, however it always goes back to the beginning of it.
It seems strange to me because the media is listed as a seeakable media (it's an mp4).
Here is my code:
````
DataSource.Factory dataSourceFactory = new DefaultDataSourceFactory(context, Util.getUserAgent(context, "UA"));
MediaSource videoSource = new ProgressiveMediaSource.Factory(dataSourceFactory).createMediaSource(Uri.fromFile(rFile));
simpleExoPlayer.setPlayWhenReady(true);
simpleExoPlayer.prepare(videoSource, false, true);
simpleExoPlayer.addListener(new Player.EventListener() {
    @Override
    public void onIsPlayingChanged(boolean isPlaying) {
        if(!isPlaying){
            //Player Stopped!
            long latestPos = simpleExoPlayer.getContentPosition();
            //Seeking to latestPos
            simpleExoPlayer.seekTo(latestPos);
            simpleExoPlayer.setPlayWhenReady(true);
        }
    }
});
````

Also, seekToDefaultPosition(); seeks at the beginning because it thinks it's a normal video

**Comment by ojw28** [comment]
As per my previous response:

> Note that it's generally not valid to give ExoPlayer a File URI to play if the file is still incomplete or being modified. That sounds very uncontrolled in general. I think you should rethink your approach of whatever it is that you're trying to accomplish.

If you want to play media that's still being modified, you should implement a custom `DataSource` that's able to do the right thing (e.g. indicate that the length of the media is still unknown, block until more media is available before returning, and know when the end of the media has been reached). The problem with trying to do this just by writing and reading a file is that the player doesn't have sufficient information to know what's going on (e.g. it has no way of knowing whether the file length might change, and it has no way of knowing when the writing side has stopped writing).
