### ISSUE TITLE
how can  remove and download  only one chunks [.ts] if already download any chunks from one hls file. 

### ISSUE THREAD

**Issue by faisalvv** [google/ExoPlayer#6783]
**how can  remove and download  only one chunks [.ts] if already download any chunks from one hls file.** 
i have already download all hls chunks. but i need only one latest chunks file [.ts]. its solve for memory issues.
how can use key for download and remove chuks

**Comment by Samrobbo** [comment]
Hi,

Can I get some clarification? What is it you actually want? I'm not sure what you mean by "i need only one latest chunks file" 

Is there another way you could explain your problem?

**Comment by faisalvv** [comment]
how can i load hls [.m3u8] file without delay. actualy it will be take one to two seconds. so i have use simple cache for resolving problem. 
here is my code:-
```
{.....
CacheDataSourceFactory dataSourceFactory =new  CacheDataSourceFactory(getSimpleCache(), new DefaultHttpDataSourceFactory("example_user_agent", null)/*,CacheDataSource.FLAG_BLOCK_ON_CACHE | CacheDataSource.FLAG_IGNORE_CACHE_ON_ERROR*/);
        SimpleVideoPreCacher precacher = new SimpleVideoPreCacher(getSimpleCache(), dataSourceFactory,1);
        ConcatenatingMediaSource concatenatingMediaSource = new ConcatenatingMediaSource();
        concatenatingMediaSource.addMediaSource(createMediaSource(mediaUrl, dataSourceFactory));
        videoPlayer.prepare(concatenatingMediaSource, true, true);
        precacher.preCache(Uri.parse(mediaUrl),0);
videoPlayer.setPlayWhenReady(true);
.......}
private SimpleCache getSimpleCache(){
    File downloadContentDirectory = new File(getDownloadDirectory(), "faisal");
    if (downloadCache==null) {
        return downloadCache = new SimpleCache(downloadContentDirectory, new NoOpCacheEvictor(), getDatabaseProvider());
    }else {
        return downloadCache;
    }
 }
```
<details>
  <summary>Related database images</summary>

![pic1](https://user-images.githubusercontent.com/13183069/71172941-84abc380-2287-11ea-92f3-a484b2d1e7ab.png)

![pic2](https://user-images.githubusercontent.com/13183069/71172969-92f9df80-2287-11ea-9ede-68553c3f7f3a.png)

![pics3](https://user-images.githubusercontent.com/13183069/71172982-9725fd00-2287-11ea-9e4a-38cf0a169876.jpg)

</details>

I have using inside recyclerview like instagram app.If i scroll recyclerview, it will take 1 to 2 seconds for the media to start playing.problem solved but it make more memory usage for downloading all chunks file. need only one latest cache ,for avoiding more memory usage. always play latest recent cache chunks file only[latest track].  i need video working smooth without delay like face book and, instagaram etc...  
Sorry for my bad english

**Comment by Samrobbo** [comment]
We'll look into this in the new year, as the team are almost all taking time off for the holiday period.

**Comment by faisalvv** [comment]
okey. . anyway Happy holiday

**Comment by faisalvv** [comment]
Hi, any updates

**Comment by Samrobbo** [comment]
Just to clarify, you have a recycler view, with multiple HLS [m3u8] files, which currently take one or two seconds to start playing after you are looking at them? 

You are asking if there is any way to reduce this play time through caching, but still keeping memory usage low?

**Comment by FOUADFAISAL** [comment]
also I faced same problem 
can you help us to resolve ?

**Comment by faisalvv** [comment]
i choose hls stream media playback. how can i use pre buffer for playing without delay.like facebook, instagram etc.. facebook and instagram not take such more seconds[2 to 4 seconds] for play.but this will take 2 to 4 second.i need play like face book and instagram. I am using  recyclerView with auto play video.using https://github.com/eneim/toro for that.

**Comment by faisalvv** [comment]
> Just to clarify, you have a recycler view, with multiple HLS [m3u8] files, which currently take one or two seconds to start playing after you are looking at them?
> 
> You are asking if there is any way to reduce this play time through caching, but still keeping memory usage low?

please any updates?

**Comment by Samrobbo** [comment]
Hi

So this is not an easy or trivial thing to actually do. Apps like Facebook and Instagram have invested a lot of time and resources into achieving this. There are some ways to achieve this with DownloadManager and the related classes. More information can be found by looking at [DownloadManager documentation](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/offline/DownloadManager.html).

That being said, it should work to a reasonable level by just creating the MediaSource and preparing the player with it. The need for advanced caching options seems excessive and over the top. 

Also consider whether there are several large and blocking tasks that occur before the recyclerview adapter calls prepare on the player.
