### ISSUE TITLE
Support variable speed / setPlaybackRate() in CastPlayer / Cast Extension

### ISSUE THREAD

**Issue by duncancarroll** [google/ExoPlayer#6784]
### Use case description
Exoplayer currently supports variable playback speed via `Player.setPlaybackParameters()`, however within `CastPlayer` this method is [marked as unsupported](https://github.com/google/ExoPlayer/blob/release-v2/extensions/cast/src/main/java/com/google/android/exoplayer2/ext/cast/CastPlayer.java#L404). This is out of date as the current `RemoteMediaClient` API does support playback speed changes via  `setPlaybackRate()` ([docs](https://developers.google.com/android/reference/com/google/android/gms/cast/framework/media/RemoteMediaClient.html#setPlaybackRate(double)))

### Proposed solution
Suggest CastPlayer expose `RemoteMediaClient.setPlaybackRate()` via it's own `setPlaybackRate()` method and update the code comment currently seen in `CastPlayer.setPlaybackParameters()` to reflect the current state of the RemoteMediaClient API and point developers to the new methods.

### Alternatives considered
The existing alternative is to call RemoteMediaClient directly, however there is no getter for this within CastPlayer, so it must be accessed via the clunky and verbose:
`CastContext.getSharedInstance(context).sessionManager.currentCastSession.remoteMediaClient.setPlaybackRate()`

**Comment by Samrobbo** [comment]
@AquilesCanta - This seems like your domain, can you have a look at this?

**Comment by makp9k** [comment]
Hello! Any plans to support it?

**Comment by marcbaechinger** [comment]
We are aware this could be done nicely with the Player API and it is on the list of features we want to add to CastPlayer. It's not something which is currently on a concrete roadmap I'm afraid.
