### ISSUE TITLE
Volume decreases when turning screen on again.

### ISSUE THREAD

**Issue by endlessmind** [google/ExoPlayer#679]
If the screen times out while playing HLS Live stream and I turn in back in, the volume will drop drastically. From 100% to maybe 25%. Pausing and resuming will reset the volume back to 100%.
The volume will also go back to 100% of I turn the screen off and then off again.

**Comment by ojw28** [comment]
This doesn't sound related to ExoPlayer. Sounds like a device or application issue.

**Comment by endlessmind** [comment]
Device issue. Only occures on my Asus TF103 (Android 4.4.2), and not on my Sony Xperia Z (Android 5.0.2).
Logcat gives me this when I turn on the screen and volume lowers:
http://gyazo.com/96bb883781f0d9def5ca2b427918fed1
and this when it rises (almost the same)
http://gyazo.com/76c3e468162cbb0a2087a5441b92a188

**Comment by andreimarinescu** [comment]
For what it's worth, I'm seeing that error message on several Nexus devices running Lollipop, with no apparent playback issues associated.

**Comment by ojw28** [comment]
Yeah, seems likely that it's unrelated. to the issue.

**Comment by endlessmind** [comment]
All right. Didn't know if it was relevant, but it's all the information I got, I figured I'd share it in case it matters.

I've seen Asus pushing A LOT of firmware updates. Maybe this is just an other bug in the current one, just waiting to be corrected. Let's hope so.

**Comment by ojw28** [comment]
Closing. Likely to be device or application specific.
