### ISSUE TITLE
Player gets stuck buffering with certain m3u8 playlists

### ISSUE THREAD

**Issue by jstubing** [google/ExoPlayer#6795]
I'm attempting to use ExoPlayer to play the following m3u8 playlist (note that this is geoblocked outside of Canada - I pasted the contents at the bottom of this post):
https://cbcvott-a.akamaihd.net/p//38e815a-011faed5219/CBC_KINGDOM_FORCE_S01E06-v2-24662916/CBC_KINGDOM_FORCE_S01E06-v2-24662916__smarttv.m3u8

Here is the event log:
```
D/EventLogger: state [eventTime=0.01, mediaPos=0.00, window=0, false, BUFFERING]
D/EventLogger: state [eventTime=0.01, mediaPos=0.00, window=0, true, BUFFERING]
D/EventLogger: surfaceSize [eventTime=0.08, mediaPos=0.00, window=0, 1440, 2532]
D/EventLogger: timeline [eventTime=0.96, mediaPos=0.00, window=0, periodCount=1, windowCount=1, reason=PREPARED
D/EventLogger:   period [1262.13]
D/EventLogger:   window [1262.13, true, false]
D/EventLogger: ]
D/EventLogger: mediaPeriodCreated [eventTime=0.97, mediaPos=0.00, window=0, period=0]
D/EventLogger: loading [eventTime=0.98, mediaPos=0.00, window=0, period=0, true]`
```
I'm using the latest ExoPlayer release at the time of this writing (2.11.0). I tried to play it using another media player (VisualOn) and it plays fine. Any ideas what might be causing this issue?

---

**m3u8 contents**:

#EXTM3U
#EXT-X-VERSION:4

#CL-PLAYLIST-VER:4.0
#CL-PLAYLIST-BANDWIDTH-MODIFIED:YES

#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="AC3-5_1",LANGUAGE="eng",NAME="English",AUTOSELECT=YES,DEFAULT=YES,URI="segments/CBC_KINGDOM_FORCE_S01E06_a3/prog_index.m3u8"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="AC3-2_0",LANGUAGE="eng",NAME="English (Descriptive)",AUTOSELECT=YES,CHARACTERISTICS="public.accessibility.describes-video",DEFAULT=NO,URI="segments/CBC_KINGDOM_FORCE_S01E06_a4/prog_index.m3u8"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="AACHEv1-2_0",LANGUAGE="eng",NAME="English",AUTOSELECT=YES,DEFAULT=YES,URI="segments/CBC_KINGDOM_FORCE_S01E06_a5/prog_index.m3u8"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="AACHEv1-2_0",LANGUAGE="eng",NAME="English (Descriptive)",AUTOSELECT=YES,CHARACTERISTICS="public.accessibility.describes-video",DEFAULT=NO,URI="segments/CBC_KINGDOM_FORCE_S01E06_a6/prog_index.m3u8"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="AACLC-2_0",LANGUAGE="eng",NAME="English",AUTOSELECT=YES,DEFAULT=YES,URI="segments/CBC_KINGDOM_FORCE_S01E06_a7/prog_index.m3u8"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="AACLC-2_0",LANGUAGE="eng",NAME="English (Descriptive)",AUTOSELECT=YES,CHARACTERISTICS="public.accessibility.describes-video",DEFAULT=NO,URI="segments/CBC_KINGDOM_FORCE_S01E06_a8/prog_index.m3u8"
#EXT-X-MEDIA:TYPE=CLOSED-CAPTIONS,GROUP-ID="CC",NAME="English",LANGUAGE="eng",AUTOSELECT=YES,DEFAULT=YES,INSTREAM-ID="CC1" 

#############################################################
\# AC3-5_1 enabled video streams:
#############################################################

#EXT-X-STREAM-INF:AVERAGE-BANDWIDTH=2948968,BANDWIDTH=3023223,CODECS="avc1.4d401f,ac-3",RESOLUTION=1280x720,FRAME-RATE=29.970,AUDIO="AC3-5_1",CLOSED-CAPTIONS="CC"
segments/CBC_KINGDOM_FORCE_S01E06_v7/prog_index.m3u8
#EXT-X-I-FRAME-STREAM-INF:AVERAGE-BANDWIDTH=201238,BANDWIDTH=506342,CODECS="avc1.4d401f",RESOLUTION=1280x720,URI="segments/CBC_KINGDOM_FORCE_S01E06_v7/iframe_index.m3u8"

#EXT-X-STREAM-INF:AVERAGE-BANDWIDTH=6514607,BANDWIDTH=6788986,CODECS="avc1.640028,ac-3",RESOLUTION=1920x1080,FRAME-RATE=29.970,AUDIO="AC3-5_1",CLOSED-CAPTIONS="CC"
segments/CBC_KINGDOM_FORCE_S01E06_v9/prog_index.m3u8
#EXT-X-I-FRAME-STREAM-INF:AVERAGE-BANDWIDTH=439188,BANDWIDTH=1134887,CODECS="avc1.640028",RESOLUTION=1920x1080,URI="segments/CBC_KINGDOM_FORCE_S01E06_v9/iframe_index.m3u8"

#EXT-X-STREAM-INF:AVERAGE-BANDWIDTH=3865076,BANDWIDTH=4058106,CODECS="avc1.4d401f,ac-3",RESOLUTION=1280x720,FRAME-RATE=29.970,AUDIO="AC3-5_1",CLOSED-CAPTIONS="CC"
segments/CBC_KINGDOM_FORCE_S01E06_v8/prog_index.m3u8
#EXT-X-I-FRAME-STREAM-INF:AVERAGE-BANDWIDTH=291209,BANDWIDTH=614021,CODECS="avc1.4d401f",RESOLUTION=1280x720,URI="segments/CBC_KINGDOM_FORCE_S01E06_v8/iframe_index.m3u8"

#EXT-X-STREAM-INF:AVERAGE-BANDWIDTH=2228693,BANDWIDTH=2314542,CODECS="avc1.4d401f,ac-3",RESOLUTION=960x540,FRAME-RATE=29.970,AUDIO="AC3-5_1",CLOSED-CAPTIONS="CC"
segments/CBC_KINGDOM_FORCE_S01E06_v6/prog_index.m3u8
#EXT-X-I-FRAME-STREAM-INF:AVERAGE-BANDWIDTH=160247,BANDWIDTH=321535,CODECS="avc1.4d401f",RESOLUTION=960x540,URI="segments/CBC_KINGDOM_FORCE_S01E06_v6/iframe_index.m3u8"

#EXT-X-STREAM-INF:AVERAGE-BANDWIDTH=1414584,BANDWIDTH=1465627,CODECS="avc1.42c01e,ac-3",RESOLUTION=640x360,FRAME-RATE=29.970,AUDIO="AC3-5_1",CLOSED-CAPTIONS="CC"
segments/CBC_KINGDOM_FORCE_S01E06_v5/prog_index.m3u8
#EXT-X-I-FRAME-STREAM-INF:AVERAGE-BANDWIDTH=79502,BANDWIDTH=179298,CODECS="avc1.42c01e",RESOLUTION=640x360,URI="segments/CBC_KINGDOM_FORCE_S01E06_v5/iframe_index.m3u8"

#############################################################
\# AACHEv1-2_0 enabled video streams:
#############################################################

#EXT-X-STREAM-INF:AVERAGE-BANDWIDTH=2628968,BANDWIDTH=2703223,CODECS="avc1.4d401f,mp4a.40.5",RESOLUTION=1280x720,FRAME-RATE=29.970,AUDIO="AACHEv1-2_0",CLOSED-CAPTIONS="CC"
segments/CBC_KINGDOM_FORCE_S01E06_v7/prog_index.m3u8
#EXT-X-I-FRAME-STREAM-INF:AVERAGE-BANDWIDTH=201238,BANDWIDTH=506342,CODECS="avc1.4d401f",RESOLUTION=1280x720,URI="segments/CBC_KINGDOM_FORCE_S01E06_v7/iframe_index.m3u8"

#EXT-X-STREAM-INF:AVERAGE-BANDWIDTH=6194607,BANDWIDTH=6468986,CODECS="avc1.640028,mp4a.40.5",RESOLUTION=1920x1080,FRAME-RATE=29.970,AUDIO="AACHEv1-2_0",CLOSED-CAPTIONS="CC"
segments/CBC_KINGDOM_FORCE_S01E06_v9/prog_index.m3u8
#EXT-X-I-FRAME-STREAM-INF:AVERAGE-BANDWIDTH=439188,BANDWIDTH=1134887,CODECS="avc1.640028",RESOLUTION=1920x1080,URI="segments/CBC_KINGDOM_FORCE_S01E06_v9/iframe_index.m3u8"

#EXT-X-STREAM-INF:AVERAGE-BANDWIDTH=3545076,BANDWIDTH=3738106,CODECS="avc1.4d401f,mp4a.40.5",RESOLUTION=1280x720,FRAME-RATE=29.970,AUDIO="AACHEv1-2_0",CLOSED-CAPTIONS="CC"
segments/CBC_KINGDOM_FORCE_S01E06_v8/prog_index.m3u8
#EXT-X-I-FRAME-STREAM-INF:AVERAGE-BANDWIDTH=291209,BANDWIDTH=614021,CODECS="avc1.4d401f",RESOLUTION=1280x720,URI="segments/CBC_KINGDOM_FORCE_S01E06_v8/iframe_index.m3u8"

#EXT-X-STREAM-INF:AVERAGE-BANDWIDTH=1908693,BANDWIDTH=1994542,CODECS="avc1.4d401f,mp4a.40.5",RESOLUTION=960x540,FRAME-RATE=29.970,AUDIO="AACHEv1-2_0",CLOSED-CAPTIONS="CC"
segments/CBC_KINGDOM_FORCE_S01E06_v6/prog_index.m3u8
#EXT-X-I-FRAME-STREAM-INF:AVERAGE-BANDWIDTH=160247,BANDWIDTH=321535,CODECS="avc1.4d401f",RESOLUTION=960x540,URI="segments/CBC_KINGDOM_FORCE_S01E06_v6/iframe_index.m3u8"

#EXT-X-STREAM-INF:AVERAGE-BANDWIDTH=1094584,BANDWIDTH=1145627,CODECS="avc1.42c01e,mp4a.40.5",RESOLUTION=640x360,FRAME-RATE=29.970,AUDIO="AACHEv1-2_0",CLOSED-CAPTIONS="CC"
segments/CBC_KINGDOM_FORCE_S01E06_v5/prog_index.m3u8
#EXT-X-I-FRAME-STREAM-INF:AVERAGE-BANDWIDTH=79502,BANDWIDTH=179298,CODECS="avc1.42c01e",RESOLUTION=640x360,URI="segments/CBC_KINGDOM_FORCE_S01E06_v5/iframe_index.m3u8"

#############################################################
\# AACLC-2_0 enabled video streams:
#############################################################

#EXT-X-STREAM-INF:AVERAGE-BANDWIDTH=2756968,BANDWIDTH=2831223,CODECS="avc1.4d401f,mp4a.40.2",RESOLUTION=1280x720,FRAME-RATE=29.970,AUDIO="AACLC-2_0",CLOSED-CAPTIONS="CC"
segments/CBC_KINGDOM_FORCE_S01E06_v7/prog_index.m3u8
#EXT-X-I-FRAME-STREAM-INF:AVERAGE-BANDWIDTH=201238,BANDWIDTH=506342,CODECS="avc1.4d401f",RESOLUTION=1280x720,URI="segments/CBC_KINGDOM_FORCE_S01E06_v7/iframe_index.m3u8"

#EXT-X-STREAM-INF:AVERAGE-BANDWIDTH=6322607,BANDWIDTH=6596986,CODECS="avc1.640028,mp4a.40.2",RESOLUTION=1920x1080,FRAME-RATE=29.970,AUDIO="AACLC-2_0",CLOSED-CAPTIONS="CC"
segments/CBC_KINGDOM_FORCE_S01E06_v9/prog_index.m3u8
#EXT-X-I-FRAME-STREAM-INF:AVERAGE-BANDWIDTH=439188,BANDWIDTH=1134887,CODECS="avc1.640028",RESOLUTION=1920x1080,URI="segments/CBC_KINGDOM_FORCE_S01E06_v9/iframe_index.m3u8"

#EXT-X-STREAM-INF:AVERAGE-BANDWIDTH=3673076,BANDWIDTH=3866106,CODECS="avc1.4d401f,mp4a.40.2",RESOLUTION=1280x720,FRAME-RATE=29.970,AUDIO="AACLC-2_0",CLOSED-CAPTIONS="CC"
segments/CBC_KINGDOM_FORCE_S01E06_v8/prog_index.m3u8
#EXT-X-I-FRAME-STREAM-INF:AVERAGE-BANDWIDTH=291209,BANDWIDTH=614021,CODECS="avc1.4d401f",RESOLUTION=1280x720,URI="segments/CBC_KINGDOM_FORCE_S01E06_v8/iframe_index.m3u8"

#EXT-X-STREAM-INF:AVERAGE-BANDWIDTH=2036693,BANDWIDTH=2122542,CODECS="avc1.4d401f,mp4a.40.2",RESOLUTION=960x540,FRAME-RATE=29.970,AUDIO="AACLC-2_0",CLOSED-CAPTIONS="CC"
segments/CBC_KINGDOM_FORCE_S01E06_v6/prog_index.m3u8
#EXT-X-I-FRAME-STREAM-INF:AVERAGE-BANDWIDTH=160247,BANDWIDTH=321535,CODECS="avc1.4d401f",RESOLUTION=960x540,URI="segments/CBC_KINGDOM_FORCE_S01E06_v6/iframe_index.m3u8"

#EXT-X-STREAM-INF:AVERAGE-BANDWIDTH=1222584,BANDWIDTH=1273627,CODECS="avc1.42c01e,mp4a.40.2",RESOLUTION=640x360,FRAME-RATE=29.970,AUDIO="AACLC-2_0",CLOSED-CAPTIONS="CC"
segments/CBC_KINGDOM_FORCE_S01E06_v5/prog_index.m3u8
#EXT-X-I-FRAME-STREAM-INF:AVERAGE-BANDWIDTH=79502,BANDWIDTH=179298,CODECS="avc1.42c01e",RESOLUTION=640x360,URI="segments/CBC_KINGDOM_FORCE_S01E06_v5/iframe_index.m3u8"

**Comment by ojw28** [comment]
It's working fine for me, on a Galaxy S8. I see a lot more logging as well:

```
EventLogger: state [eventTime=0.00, mediaPos=0.00, window=0, true, BUFFERING]
EventLogger: surfaceSize [eventTime=0.07, mediaPos=0.00, window=0, 1080, 2004]
EventLogger: timeline [eventTime=0.75, mediaPos=0.00, window=0, periodCount=1, windowCount=1, reason=PREPARED
EventLogger:   period [1262.13]
EventLogger:   window [1262.13, true, false]
EventLogger: ]
EventLogger: mediaPeriodCreated [eventTime=0.76, mediaPos=0.00, window=0, period=0]
EventLogger: loading [eventTime=0.78, mediaPos=0.00, window=0, period=0, true]
EventLogger: decoderEnabled [eventTime=1.55, mediaPos=0.00, window=0, period=0, video]
EventLogger: decoderEnabled [eventTime=1.56, mediaPos=0.00, window=0, period=0, audio]
EventLogger: tracks [eventTime=1.56, mediaPos=0.00, window=0, period=0, 
EventLogger:   Renderer:0 [
EventLogger:     Group:0, adaptive_supported=YES [
EventLogger:       [X] Track:0, id=0, mimeType=video/avc, bitrate=3023223, codecs=avc1.4d401f, res=1280x720, supported=YES
EventLogger:       [X] Track:1, id=1, mimeType=video/avc, bitrate=6788986, codecs=avc1.640028, res=1920x1080, supported=YES
EventLogger:       [X] Track:2, id=2, mimeType=video/avc, bitrate=4058106, codecs=avc1.4d401f, res=1280x720, supported=YES
EventLogger:       [X] Track:3, id=3, mimeType=video/avc, bitrate=2314542, codecs=avc1.4d401f, res=960x540, supported=YES
EventLogger:       [X] Track:4, id=4, mimeType=video/avc, bitrate=1465627, codecs=avc1.42c01e, res=640x360, supported=YES
EventLogger:     ]
EventLogger:     Metadata [
EventLogger:       HlsTrackMetadataEntry
EventLogger:     ]
EventLogger:   ]
EventLogger:   Renderer:1 [
EventLogger:     Group:0, adaptive_supported=YES_NOT_SEAMLESS [
EventLogger:       [X] Track:0, id=AC3-5_1:English, mimeType=audio/ac3, codecs=ac-3, channels=6, sample_rate=48000, language=en, label=English, supported=YES
EventLogger:       [ ] Track:1, id=AACHEv1-2_0:English, mimeType=audio/mp4a-latm, codecs=mp4a.40.5, channels=6, sample_rate=48000, language=en, label=English, supported=YES
EventLogger:       [ ] Track:2, id=AACLC-2_0:English, mimeType=audio/mp4a-latm, codecs=mp4a.40.2, channels=6, sample_rate=48000, language=en, label=English, supported=YES
EventLogger:     ]
EventLogger:     Group:1, adaptive_supported=YES_NOT_SEAMLESS [
EventLogger:       [ ] Track:0, id=AC3-2_0:English (Descriptive), mimeType=audio/ac3, channels=2, sample_rate=48000, language=en, label=English (Descriptive), supported=YES
EventLogger:       [ ] Track:1, id=AACHEv1-2_0:English (Descriptive), mimeType=audio/mp4a-latm, codecs=mp4a.40.5, channels=2, sample_rate=48000, language=en, label=English (Descriptive), supported=YES
EventLogger:       [ ] Track:2, id=AACLC-2_0:English (Descriptive), mimeType=audio/mp4a-latm, codecs=mp4a.40.2, channels=2, sample_rate=48000, language=en, label=English (Descriptive), supported=YES
EventLogger:     ]
EventLogger:     Metadata [
EventLogger:       HlsTrackMetadataEntry [AC3-5_1, English]
EventLogger:     ]
EventLogger:   ]
EventLogger:   Renderer:2 [
EventLogger:     Group:0, adaptive_supported=N/A [
EventLogger:       [X] Track:0, id=CC:English, mimeType=application/cea-608, language=en, supported=YES
EventLogger:     ]
EventLogger:   ]
EventLogger:   Renderer:3 [
EventLogger:     Group:0, adaptive_supported=N/A [
EventLogger:       [X] Track:0, id=null, mimeType=application/id3, supported=YES
EventLogger:     ]
EventLogger:   ]
EventLogger: ]
EventLogger: mediaPeriodReadingStarted [eventTime=1.58, mediaPos=0.00, window=0, period=0]
EventLogger: downstreamFormat [eventTime=1.64, mediaPos=0.00, window=0, period=0, id=AC3-5_1:English, mimeType=audio/ac3, codecs=ac-3, language=en, label=English]
EventLogger: decoderInitialized [eventTime=1.70, mediaPos=0.00, window=0, period=0, audio, OMX.dolby.ac3.decoder]
EventLogger: decoderInputFormat [eventTime=1.71, mediaPos=0.00, window=0, period=0, audio, id=AC3-5_1:English, mimeType=audio/ac3, codecs=ac-3, channels=6, sample_rate=48000, language=en, label=English]
EventLogger: downstreamFormat [eventTime=2.24, mediaPos=0.00, window=0, period=0, id=1, mimeType=null, bitrate=6788986, codecs=avc1.640028,ac-3, res=1920x1080, fps=29.97]
EventLogger: decoderInitialized [eventTime=2.53, mediaPos=0.00, window=0, period=0, video, OMX.Exynos.avc.dec]
EventLogger: decoderInputFormat [eventTime=2.53, mediaPos=0.00, window=0, period=0, video, id=1, mimeType=video/avc, bitrate=6788986, codecs=avc1.640028, res=1920x1080, fps=29.97]
EventLogger: videoSize [eventTime=2.63, mediaPos=0.00, window=0, period=0, 1920, 1080]
EventLogger: surfaceSize [eventTime=2.66, mediaPos=0.00, window=0, period=0, 1080, 607]
EventLogger: renderedFirstFrame [eventTime=2.67, mediaPos=0.00, window=0, period=0, Surface(name=null)/@0x60ba35f]
EventLogger: audioSessionId [eventTime=2.85, mediaPos=0.00, window=0, period=0, 9729]
EventLogger: state [eventTime=3.02, mediaPos=0.00, window=0, period=0, true, READY]
EventLogger: isPlaying [eventTime=3.02, mediaPos=0.00, window=0, period=0, true]
EventLogger: loading [eventTime=12.74, mediaPos=9.73, window=0, period=0, false]
EventLogger: loading [eventTime=16.19, mediaPos=13.08, window=0, period=0, true]
```

If you're not already, could you try in the 2.11.0 demo app, to rule out anything specific to your own application? Could you also try a few different devices, in case it's device specific?

**Comment by jstubing** [comment]
I see what it is now. I was building the media source as follows::

val factory = DefaultHlsDataSourceFactory(defaultMediaFactory)

val mediaSource = HlsMediaSource.Factory(factory)
    .setAllowChunklessPreparation(true)
    .createMediaSource(Uri.parse(url))

I deleted the "setAllowChunklessPreparation(true)" line and it works now.

Thank you for the fast response!
