### ISSUE TITLE
Unable to override exo_playback_control_view.xml

### ISSUE THREAD

**Issue by Mangoxd** [google/ExoPlayer#6799]
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:layout_gravity="bottom"
    android:layoutDirection="ltr"
    android:background="#CC000000"
    android:orientation="vertical">

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginTop="4dp"
        android:gravity="center_vertical"
        android:orientation="horizontal">

        <TextView android:id="@id/exo_position"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:textSize="14sp"
            android:textStyle="bold"
            android:paddingLeft="4dp"
            android:paddingRight="4dp"
            android:includeFontPadding="false"
            android:textColor="#FFBEBEBE"/>

        <com.google.android.exoplayer2.ui.DefaultTimeBar
            android:id="@id/exo_progress"
            android:layout_width="327dp"
            android:layout_height="wrap_content"
            android:layout_weight="1" />

        <TextView android:id="@id/exo_duration"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:textSize="14sp"
            android:textStyle="bold"
            android:paddingLeft="4dp"
            android:paddingRight="4dp"
            android:includeFontPadding="false"
            android:textColor="#FFBEBEBE"/>
    </LinearLayout>

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:paddingTop="4dp"
        android:orientation="horizontal">

        <ImageButton
            android:id="@id/exo_pause"
            android:layout_width="50dp"
            android:layout_height="30dp"
            android:scaleType="fitCenter"
            style="@style/ExoMediaButton.Pause" />

        <ImageButton
            android:id="@id/exo_play"
            style="@style/ExoMediaButton.Play"
            android:layout_width="50dp"
            android:layout_height="30dp"
            android:scaleType="fitCenter" />

        <ImageButton
            android:id="@id/exo_rew"
            style="@style/ExoMediaButton.Rewind"
            android:layout_width="48dp"
            android:layout_height="30dp"
            android:scaleType="fitCenter" />

        <ImageButton
            android:id="@id/exo_ffwd"
            style="@style/ExoMediaButton.FastForward"
            android:layout_width="42dp"
            android:layout_height="30dp"
            android:scaleType="fitCenter" />

        <androidx.mediarouter.app.MediaRouteButton
            android:id="@+id/media_route_button"
            android:layout_width="42dp"
            android:layout_height="30dp"
            android:scaleType="fitCenter"
            android:mediaRouteTypes="user"
            android:visibility="visible" />

        <FrameLayout
            android:id="@+id/exo_fullscreen_button"
            android:layout_width="50dp"
            android:layout_height="32dp"
            android:layout_marginLeft="120dp"
            android:gravity="right">

            <ImageView
                android:id="@+id/exo_fullscreen_icon"
                android:layout_width="18dp"
                android:layout_height="18dp"
                android:layout_gravity="center"
                android:adjustViewBounds="true"
                android:scaleType="fitCenter"
                android:src="@drawable/ic_fullscreen_expand"/>

        </FrameLayout>
    </LinearLayout>

</LinearLayout>

This is my exo_playback_control_view.xml ,

I can see all controls but MediaRouteButton  not works is invisible i can still click it to cast the video , but is invisible, if i put it on activity_main.xml i can see it, but on the exoplayer xml is invisible , why is that?

**Comment by marcbaechinger** [comment]
Can you check if you are able to change the PlayerControlView by using a layout file `exo_playback_control_view.xml` at all?

The reason why I am asking is that it appears to me you need to override `exo_player_control_view.xml` instead.

The `PlayerControlView` does inflate the layout file `R.layout.exo_player_control_view`(https://github.com/google/ExoPlayer/blob/release-v2/library/ui/src/main/java/com/google/android/exoplayer2/ui/PlayerControlView.java#L313)

Can you please check if it helps to rename your layout file to `exo_player_control_view.xml`?

**Comment by Mangoxd** [comment]
> Can you check if you are able to change the PlayerControlView by using a layout file `exo_playback_control_view.xml` at all?
> 
> The reason why I am asking is that it appears to me you need to override `exo_player_control_view.xml` instead.
> 
> The `PlayerControlView` does inflate the layout file `R.layout.exo_player_control_view`(https://github.com/google/ExoPlayer/blob/release-v2/library/ui/src/main/java/com/google/android/exoplayer2/ui/PlayerControlView.java#L313)
> 
> Can you please check if it helps to rename your layout file to `exo_player_control_view.xml`?

Thanks you , it works now! , my other problem is , 

Even though I have another problem, I would make another thread but I think it is unnecessary, my other problem is that when you turn the phone and go to landscape or vertical, the video stops for about 5 seconds, that is, and is buffered again in same position , how i cant prevent stop video when change to landscape or vertical?

    @Override
    public void onConfigurationChanged(Configuration newConfig) {
        super.onConfigurationChanged(newConfig);
        // Checks the orientation of the screen
        if (newConfig.orientation == Configuration.ORIENTATION_LANDSCAPE) {
            getWindow().addFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN);
        } else if (newConfig.orientation == Configuration.ORIENTATION_PORTRAIT){
            getWindow().clearFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN);
        }
    }

**Comment by marcbaechinger** [comment]
You are on the right track as you need to handle configuration changes for orientation changes yourself. This avoids that the activity is destroyed and recreated when the user changes orientation.

I think the `PlayerActivity` of the demo app is doing what you want. It tells the system that the app is handling configuration changes in the manifest: https://github.com/google/ExoPlayer/blob/release-v2/demos/main/src/main/AndroidManifest.xml#L65 . 

Have a look into the demo app and the `PlayerActivity` to see what happens there.

**Comment by Mangoxd** [comment]
> You are on the right track as you need to handle configuration changes for orientation changes yourself. This avoids that the activity is destroyed and recreated when the user changes orientation.
> 
> I think the `PlayerActivity` of the demo app is doing what you want. It tells the system that the app is handling configuration changes in the manifest: https://github.com/google/ExoPlayer/blob/release-v2/demos/main/src/main/AndroidManifest.xml#L65 .
> 
> Have a look into the demo app and the `PlayerActivity` to see what happens there.

Thanks you it works now!
