### ISSUE TITLE
Implement Closed Captioning support for HLS

### ISSUE THREAD

**Issue by andudo** [google/ExoPlayer#68]
Implement support for Closed Captioning via:
EIA-608 (CEA-608)
CEA-708
WEBVTT

**Comment by dhir-pratap** [comment]
This ticket is marked closed. But i am still unable to display CC in some video. E.g the link below.
http://cdnbakmi.kaltura.com/p/243342/sp/24334200/playManifest/entryId/0_uka1msg4/flavorIds/1_vqhfu6uy,1_80sohj7p/format/applehttp/protocol/http/a.m3u8

Can you tell what are the CC format supported by Exo player?

**Comment by sachinbhanot** [comment]
I having a downloaded. Srt File , How to use it with Exoplayer with HLS Support?
