### ISSUE TITLE
How to set unable auto play video in webview after add lib?

### ISSUE THREAD

**Issue by bk-ducle** [google/ExoPlayer#6803]
Hi guys,
When i add ExoPlayer library to my app, my WebView auto play video. But i don't want like that, do you know how to set unable auto play video in webview after add lib?

**Comment by marcbaechinger** [comment]
Can you elaborate a little bit on how you think adding the dependency to ExoPlayer does change the behaviour of your webview?

I currently understand the only thing you change in your app is adding a dependency in your gradle file like so:

```
implementation 'com.google.android.exoplayer:exoplayer-core:2.11.1'
```

I can not see why adding only this line would have an impact on the behaviour of a video playing in a webview which uses HTML/JS to play. 

Can you please confirm this is the only thing you are changing? If this is the case and you are still seeing the behaviour in the webview changes, can you please send a test fixture which does exhibit the behaviour so we can look into this.

**Comment by bk-ducle** [comment]
In my project, my webview show page facebook, i run javascript to find video, but not play it. I add lib implementation 'com.google.android.exoplayer:exoplayer-core:2.11.1', webview change(auto play video). I try remove the lib, the webview be normal.

But when i test again in my new  project, only have webview and implement lib. it ok. So i think problem not about lib, it from another some thing else.
Thank you.
