### ISSUE TITLE
How to  delete video file downloaded by exoplayer download manager

### ISSUE THREAD

**Issue by ajay-aravind** [google/ExoPlayer#6806]
### [REQUIRED] Searched documentation and issues
I've checked exo player blog and stackoverflow
### [REQUIRED] Question
How to  delete video file downloaded by exoplayer download manager. There is a way to delete download in progress but how can i delete a file if it is already downloaded. In out application we have allow user to delete download whenever he wants. So how to acheive this if user wants to delete the download

**Comment by marcbaechinger** [comment]
You can send a removal to the `DownloadService`. Does this work for you?

https://exoplayer.dev/downloading-media.html#removing-downloads

```
DownloadService.sendRemoveDownload(
    context,
    MyDownloadService.class,
    contentId,
    /* foreground= */ false)
```

The `DownloadManager` has a corresponding public method `removeDownload(String id)` in case you are using it directly:

https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/offline/DownloadManager.java#L445

**Comment by ajay-aravind** [comment]
Got it. I thought download service can only remove the downloads in progress, but it seems it can delete the completed downloads also. Thanks for the info. 
But removing download also calling getForegroundNotification method , which is annoying though.
