### ISSUE TITLE
Can't make release APK from demo app

### ISSUE THREAD

**Issue by raghavsatyadev** [google/ExoPlayer#6807]
### Issue description
Can't build release APK with minifyEnabled & shrinkResources = true

### Reproduction steps
* Upgrade demo app to use in **Android Studio 4.0 Canary 6**
* Try to make release APK of **demo** module with **withExtensionsRelease** Build Variant

### Version of ExoPlayer being used
2.11.1

R8 is enabled

### Error
`Multiple entries with same key: Method com.google.android.exoplayer2.analytics.AnalyticsCollector.onAudioSessionId Proto VI void int=Encoded method Method com.google.android.exoplayer2.analytics.AnalyticsCollector.onAudioSessionId Proto VI void int and Method com.google.android.exoplayer2.analytics.AnalyticsCollector.onAudioSessionId Proto VI void int=Encoded method Method com.google.android.exoplayer2.analytics.AnalyticsCollector.onAudioSessionId Proto VI void int`

**Comment by marcbaechinger** [comment]
Is this specific to Android Studio 4 or does it happen with AS 3.5.X as well?

**Comment by raghavsatyadev** [comment]
yes got the issue now, it was specific to Android Studio 4.0 Canary 6. It builds in Canary 7 and Studio 3.5.*, but in canary 7 we can't make app bundle because of some internal issue only APK

**Comment by marcbaechinger** [comment]
> we can't make app bundle because of some internal issue only APK

So, my current understanding is that there is an issue when you want to create an app bundle with Android Studio. This is not related to ExoPlayer as I understand. Is this correct?

**Comment by raghavsatyadev** [comment]
For Canary 6 it's related, for Canary 7 it's not

**Comment by tonihei** [comment]
If it's fixed by an update to a canary Android Studio version, then it probably was a bug in the Android Studio implementation unrelated to ExoPlayer itself. I'll close this issue under the assumption that it is now fixed.
