### ISSUE TITLE
How to start playback after downloading only the first segment

### ISSUE THREAD

**Issue by krackjack234** [google/ExoPlayer#6810]
### [REQUIRED] Searched documentation and issues
Could not find direct answer

### [REQUIRED] Start playback after downloading first segment of any bitrate.

We want to start playback after downloading the first segment
We have kept the DEFAULT_BUFFER_FOR_PLAYBACK_MS to 1s which is less than the hls chunk duration

When we start playback we see first the 1st chunk of the lowest bitrate is downloaded and then the player switches to another bitrate and downloads the first chunk again and then starts playback.

We want to start playback as soon as the first chunk of the lowest bitrate is downloaded

![Screen Shot 2019-12-27 at 8 37 58 AM](https://user-images.githubusercontent.com/50735078/71498950-83c8f200-2884-11ea-92ab-eb7567b6bff5.png)

In the diagram above, we see that the player first downloads 1st ts segment of 224K and then switches to 900k, download the same segment again and then starts playback.

We want the player to start playback after downloading the first segment of 224K.

Any pointers? Thanks in advance

**Comment by krackjack234** [comment]
We have used *setAllowChunklessPreparation* as true to avoid this problem. Is this the right way to fix this problem? 

Also if our chunks are not independent segments, there will be no impact for using this option (setAllowChunklessPreparation) and playback should still happen. Is our understanding correct?

**Comment by tonihei** [comment]
Yes, this is the intended solution as already pointed out in https://github.com/google/ExoPlayer/issues/6756#issuecomment-565356792. 
I've tested it with your example stream and it works as expected. Note that the 224K m3u8 media playlist is still loaded initially to obtain media information before the tracks are selected.

Chunkless preparation can only cause problems if the declared tracks in the master playlist and the actual tracks in the ts files do not match. For example, closed caption tracks are exposed if and only if they are declared by the master playlist. For details about the two modes, please also have a look at this [blog post ](https://medium.com/google-exoplayer/faster-hls-preparation-f6611aa15ea6)(caution, 2 years old by now, so no guarantee everything still applies).
