### ISSUE TITLE
EXO(2.9.1) Player video unplay error

### ISSUE THREAD

**Issue by beomboo** [google/ExoPlayer#6815]
**I use ExoPlayer 2.9.1 and after putting a number of YouTube video links in the database inside the program, I tried the following:**

1. Video link forwarding
a) video link forwarding [click](https://apps.jou.kr/jouTV/exoplayer2.PNG)
      a-1) extractYoutubeUrl (final String url)
      a-2) onExtractionComplete (SparseArray <YtFile> sparseArray, VideoMeta videoMeta)
b) If a video error occurs in the catch part, increase the count and play the next video.
c) I saw the following error [click](https://apps.jou.kr/jouTV/exoplayer.PNG)

**Here's the case I tried:**

 1. ExoPlayerManager.java
   1-1. public void extractYoutubeUrl (final String url) internal
      (1) change playStream (sparseArray.get (22) .getUrl ())
        -I changed (int) to various resolutions instead of 720p (22).
      (2) I checked the logs for videoMeta.

 2. Version Check
    1-1. Android Studio 3.4.1
    1-2. Gradle (follow Git guide)
       -'com.google.android.exoplayer: exoplayer: 2.9.3'
       -'com.google.android.exoplayer: exoplayer-core: 2.9.3'
       -'com.google.android.exoplayer: exoplayer-dash: 2.9.3'
       -'com.google.android.exoplayer: exoplayer-ui: 2.9.3'
       defaultConfig {
         minSdkVersion 15
         targetSdkVersion 27}
       -compileOptions {
         sourceCompatibility JavaVersion.VERSION_1_8
         targetCompatibility JavaVersion.VERSION_1_8}
   
   3. YouTube video review
     3-1. Review settings (allow embedding, copyright)
     3-2. Various YouTube video tests

   4. Identify the cause
     4-1. There have been no modifications to the source code since two months ago.

**Comment by andrewlewis** [comment]
ExoPlayer doesn't directly support playing YouTube streams. Please see #5466 for more information.

Edit: it looks like the error shown in the screenshot in item 1c) is not within ExoPlayer anyway.
