### ISSUE TITLE
Best way to send custom HTTP headers?

### ISSUE THREAD

**Issue by CalebGartner** [google/ExoPlayer#6818]
### [REQUIRED] Searched documentation and issues
#2166 | #2174

### [REQUIRED] Question
Both of the above issues seem to approach this problem by setting the desired headers on the DataSourceFactory and using the new DataSource(s) it produces. I'm wondering if this is the best way to send back custom headers to the server, or if it's possible to access a DataSource _after_ it's been used to create a MediaSource, and modify the headers via the DataSource instead ([from this method](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/upstream/DefaultHttpDataSource.html#setRequestProperty-java.lang.String-java.lang.String-))?

I also wanted to confirm exactly what the process would be if using the first method (as described in the other issues). My understanding is that you would have to create a brand new MediaSource with the modified DataSourceFactory and then 'prepare' the ExoPlayer instance with this new MediaSource, swapping out the old one. Is this correct?

**Comment by ojw28** [comment]
Default headers set on a `HttpDataSource.Factory` are applied to all subsequent requests made by `HttpDataSource` instances created by that factory, _including_ instances that have already been created. So you don't need to create the `MediaSource`.

Does that answer your question?

**Comment by CalebGartner** [comment]
Yes, I think it does - thank you. However, is there a way to set a header for only the next (single) subsequent request (i.e., make sure you only send the custom header _once_)? 

I've gone through the source code for the DefaultHttpDataSource, and the only way I can think of would be to override the HttpDataSource.close() function to call clearAllRequestProperties() at the end before opening a new connection/request . . . would you recommend a different approach?

**Comment by tonihei** [comment]
If you want to modify the request on the fly, please use `ResolvingDataSource`. You can find a simple example of how to use it [here](https://exoplayer.dev/progressive.html#customizing-server-interactions).

**Comment by CalebGartner** [comment]
Understood, thanks!
