### ISSUE TITLE
resume playing RTMP stream from Paused state, time of lag is getting longer

### ISSUE THREAD

**Issue by caprice** [google/ExoPlayer#6822]
In a live mode, I use  mInternalPlayer.setPlayWhenReady(false) to pause  the video stream for a long time, and I resume to play it by  mInternalPlayer.setPlayWhenReady(true). I find the playing video lagging the real live stream longer. 

**Because of live stream, users only want to chase the live stream while resuming to play, I guess there must be some cache logic behind exoplayer, if skipping the cache or deleting the cache, it may be work. Is there a way to do this? Any suggestions would be greatly appreciated**

**Comment by marcbaechinger** [comment]
ExoPlayer does not cache by default. You need to use a `CachingDataSource`. If you do not have this in place there is no caching.

Can you please be more specific on what kind of live stream you are using (Dash, Hls, Smooth, other)? Best would be to provide a URI to the stream so we can look into this ourself.

> I find the playing video lagging the real live stream longer.

If you are using a adaptive live stream (Dash, HLS, SmoothStreaming) you may want to seek to the live edge (default position) of the stream when the user resumes. As mentioned above, a URI to some test content would be best to make clear what we are talking about.

**Comment by marcbaechinger** [comment]
ExoPlayer does not cache by default. If you do not have a `CachingDataSource` in place there is no caching applied.

**Comment by caprice** [comment]
@marcbaechinger Thanks for your replies. There is no doubt that exoplayer has buffering cache in memory. At last, I found the latest live stream can be caught up by using player.seekTo(0) when resume to play in live mode
