### ISSUE TITLE
getCurrentPosition() returning values greater than getDuration()

### ISSUE THREAD

**Issue by vishal-i4gs** [google/ExoPlayer#6825]
Playing an audio via exoplayer returns getCurrentPostion() value greater than getDuration() when the audio is about to finish. The getDuration() value does not change but the getCurrentPosition() keeps increasing and goes past getDuration() value as well. This happens also in the playerNotificationManager where the see the time going past getDuration(). This should not happen and the getCurrentPosition() should never be greater than getDuration().

D/DurationTime: 1684323
D/ProgressTime: 1689893
D/DurationTime: 1684323
D/ProgressTime: 1690899
D/DurationTime: 1684323
D/ProgressTime: 1691903
D/DurationTime: 1684323

version 2.9.6

All simulators and devices.

**Comment by ojw28** [comment]
This can happen in some cases. For example if the media incorrectly specifies its own duration. To understand your specific case, we'd need you to provide a media sample for which you observe this happening.

**Comment by vishal-i4gs** [comment]
I am not sure whether its because of the media sample because I keep seeing different logs each time I test. One thing I observe is that the duration doesn't change at any point but definitely the amount getCurrentPosition() is greater than the getDuration() changes at every trial. Sometimes the getCurrentPosition() is 2 seconds more, sometimes  its 3 and sometimes its even 5.

Note : I did test that audio on chrome browser audio player and it feels fine, the progress doesn't go beyond the duration.

**Comment by ojw28** [comment]
As per my previous response, we need a media sample to understand your specific case.

**Comment by vishal-i4gs** [comment]
I am sorry @ojw28 I believe there might be some issue with the audio as well as you said. Unfortunately I cannot share the audio url because its proprietary but I believe there might some issues with the audio. I will get back in a while on this. Thanks

**Comment by ojw28** [comment]
Closing for now. Please reply here if you require more assistance, and we can re-open the issue.
