### ISSUE TITLE
I want to edit a Github issue

### ISSUE THREAD

**Issue by LaurentiuSimionescu** [google/ExoPlayer#6827]
Hi, 

A long time ago i created https://github.com/google/ExoPlayer/issues/5710
Since people started to ask me how I solved the issue.
I want to leave a comment on the issue, but it has been blocked only to collaborators.

Please allow me to comment on issue https://github.com/google/ExoPlayer/issues/5710

Have a nice day.

**Comment by ojw28** [comment]
You should be able to do this now!
