### ISSUE TITLE
Playing h264 main profile on android 4.1.1

### ISSUE THREAD

**Issue by dophlin** [google/ExoPlayer#683]
Is that possible to use a software codec and integrate it to Exoplayer in order to play h264 main profile on androi 4.1.1?
I know normally h/w codecs does not decode main profile on android 4.1.1. After googling I found that it might be possible to use a S/W codec instead of default H/W to play h264 main profile. Does anybody have any solution for my problem?

Thanks in advance.

**Comment by ojw28** [comment]
I wouldn't be surprised if many devices running 4.1.1 do support main profile, with the exception of low end devices. Are you sure this isn't the case? Note that it's not yet become a hard requirement for Android devices to support main profile in general, so there's no guarantee that you wont find a low end device running Lollypop that also lacks main profile support. I would expect all non-low-end devices to do so, however.

As for your specific question, yes it is possible to do this. The [VP9 extension](https://github.com/google/ExoPlayer/tree/master/extensions/vp9) shows how to bridge onto a VP9 software decoder. You could attempt something similar to bridge onto a S/W H264 decoder, if you wanted to do so. I can't say anything about what kind of performance this approach would give you; that's something you'd need to find out.

**Comment by dophlin** [comment]
Thank you ojw28 for your answer. It's really helpful for my situation. I guess reviewing The VP9 extention (as you said) will help me too. However, reconsidering of using main profile for devices running 4.1.1 is another solution which I am thinking about.
