### ISSUE TITLE
SRT subtitles not disappeared since 2.11.0 version

### ISSUE THREAD

**Issue by aarondib** [google/ExoPlayer#6833]
Starting from 2.11.0 library version, SRT subtitles in MKV videos has stopped to disappear at needed times and will show until the next CUES will come.

I can see that according to matroska tech specs in RELEASE NOTES:
> Require an end time or duration for SubRip (SRT) and SubStation Alpha (SSA/ASS) subtitles...

but in all available for me video samples subtitles are not disappeared.

Question:
Is it a bug or is it ok? Should we wait for new videos in new matroska specs and all current videos won't work correctly?

**Comment by ojw28** [comment]
It's a bug. Thanks for reporting!

**Comment by icbaker** [comment]
Thanks for catching this - it's now fixed on the dev-v2 branch and the fix will be included in the 2.11.2 release.
