### ISSUE TITLE
Alac support from MediaCodec change

### ISSUE THREAD

**Issue by Tolriq** [google/ExoPlayer#6837]
I'm sorry to open this question before having proper full report from the users, but despite a few impacted users, I have not yet had one of them providing bug reports and logs.

Anyway I have multiple report of Alac files in mp4 container no more working on device where it previously worked (Samsung / Xiaomi).

I know that I have made a change in how I initialize Exoplayer so ask about this, hoping there's an obvious answer, else I'll hope some user do provide the data.

To optimise application size with R8 I went from full default init to audio only initialization using:

```
ExtractorsFactory { arrayOf(Mp3Extractor(), FlacExtractor(), OggExtractor(), WavExtractor(), MatroskaExtractor(), Mp4Extractor()) }
```
as extractor factory.

```
class AudioOnlyRendererFactory(private val context: Context) : RenderersFactory {

    override fun createRenderers(
        eventHandler: Handler,
        videoRendererEventListener: VideoRendererEventListener,
        audioRendererEventListener: AudioRendererEventListener,
        textRendererOutput: TextOutput,
        metadataRendererOutput: MetadataOutput,
        drmSessionManager: DrmSessionManager<FrameworkMediaCrypto>?
    ): Array<Renderer> {
        return arrayOf(MediaCodecAudioRenderer(context, MediaCodecSelector.DEFAULT, eventHandler, audioRendererEventListener),
            LibflacAudioRenderer(eventHandler, audioRendererEventListener))
    }
}
```
as rendererFactory.

This works nicely for all the formats my test devices can handle, but maybe there's a magic thing to add for Alac to work? (I unfortunately do not have device with Alac codec support)

The other changed thing is R8 version, is there something in the resulting APK / Dex that I could check to see if something was removed that should not have and require a new Proguard rule?

**Comment by marcbaechinger** [comment]
The changes you made regarding the `ExtractorsFactory` should not matter. Providing the `MP4Extractor` should be sufficient.

Please  provide us with some more information about your case:

> Alac files in mp4 container no more working on device where it previously
> worked (Samsung / Xiaomi).

What changed here? Can you tell what ExoPlayer version you were using and whether this changed? Did the device receive an OS update? Please provide detailed information about what devices you are seeing to fail and which OS versions they are running.

Can you provide us with a url to a sample file which which you are experiencing the problem?

Best is if you can provide us with a bug report from one of these devices if possible.

**Comment by Tolriq** [comment]
As said for the moment users are not cooperative on this and I do not have devices that support Alac so can't reproduce on my side.

From the few reports all Alac files no more works and since I update ExoPlayer each time I release I currently can't tell when the issue occurred. (App is currently in prod with 2.11.0).

One strange thing is that I have a Nokia 8 that is not supposed to support Alac and on that device Google Play Music and Youtube Music can read the mp4 with alac (Even when both does not seems to embed ffmepg libs).
So maybe that device does support it, but my app and Files (From google) both can't (only show the progress bar but no sound).

**Comment by ojw28** [comment]
* Even just knowing what devices these users are using would likely be helpful (more specifically than "Samsung/Xiaomi").
* Could you confirm whether or not you're bundling the FFmpeg extension in your app (and if so, whether it's build with the alac decoder enabled)? I'm guessing not, but it's not completely clear.

**Comment by Tolriq** [comment]
I'm not using ffmpeg just Flac extension.

For the moment users who did contact me with device details are :

> Android: 10 - 29 [arm64-v8a,armeabi-v7a,armeabi]
> Device: Xiaomi - MI 8 [dipper - dipper]

and

> Android: 9 - 28 [arm64-v8a,armeabi-v7a,armeabi]
> Device: samsung - SM-A530F [jackpotltexx - jackpotlte]

But I do not want you to loose too much time because my users are lazy. If there's no obvious regression and my code change can't be the cause then I'll wait for a more dedicated user to provide everything necessary. (Unless you can confirm if the fact that GPM and YTM plays the files on my Nokia 8 means that Exoplayer should support it without ffmpeg and I'll do the research to find previous working version and change causing the issue)

**Comment by ojw28** [comment]
I got hold of a MI 8, but it doesn't have an ALAC decoder exposed via `MediaCodec`, so I'm not sure how it would have ever worked (unless you previously bundled the FFmpeg extension, and have now stopped doing so). That said, my MI 8 is on Android 9 still; it's not showing an updated to Android 10 as being available.

The 1st party video player on the MI 8 is able to play ALAC, but it appears to be doing so using a decoder that doesn't appear to be exposed through the platform APIs. Given the following logging, I'd guess it may be bundled in their app's apk (this is just speculation though!)

```
13747 14797 I libffmpeg2.7_log: : Audio: alac (alac / 0x63616C61), 44100 Hz, stereo, s32p (24 bit), 1258 kb/s
```

**Comment by Tolriq** [comment]
Thanks for testing, the A8 user finally provided logs but do not want to expose private data with a full bug report :(

As expected it says the same as my device so probably no MediaCodec exposed and all other apps use tricks / ffmepg for it.
```
2020-01-06 20:52:20.562 Verbose/MusicPlayer: tracks [eventTime=24.33, mediaPos=0.00, window=0, period=0, 
2020-01-06 20:52:20.564 Verbose/MusicPlayer:   Renderer:0 [
2020-01-06 20:52:20.566 Verbose/MusicPlayer:     Group:0, adaptive_supported=N/A [
2020-01-06 20:52:20.569 Verbose/MusicPlayer:       [ ] Track:0, id=1, mimeType=audio/alac, channels=2, sample_rate=44100, language=und, supported=NO_UNSUPPORTED_TYPE
2020-01-06 20:52:20.571 Verbose/MusicPlayer:     ]
2020-01-06 20:52:20.573 Verbose/MusicPlayer:   ]
2020-01-06 20:52:20.574 Verbose/MusicPlayer: ]
```


It's strange that I got multiple similar reports, but I start to suppose they mixed up with some other apps :(

I guess I'll move to ffmepg extension in the future then. Is there any difference between flac/opus extensions and ffmepg support for those? (I've seen some apps embedding both ffmepg and those so ask in case there's something not documented)

Edit: Ok seems there's no FLAC extractor yet for ffmepg :( Will the next release extractor for flac works with ffmepg or only for Android MediaCodec ?

**Comment by ojw28** [comment]
> Edit: Ok seems there's no FLAC extractor yet for ffmepg :( Will the next release extractor for flac works with ffmepg or only for Android MediaCodec ?

Version `2.11.2` will contain a Java FLAC extractor, which will work in conjunction with either a platform FLAC decoder (if the device has one) or the FFMpeg extension (if configured with `–enable-decoder=flac`). This release is scheduled for ~2 weeks from now.

> I guess I'll move to ffmepg extension in the future then. Is there any difference between flac/opus extensions and ffmepg support for those? (I've seen some apps embedding both ffmepg and those so ask in case there's something not documented)

I imagine the implementations are different, but I don't know the details I'm afraid.

**Comment by Tolriq** [comment]
Nice thanks. Does Exôplayer have public snapshot builds somewhere so I can already start to test migrating to ffmepg without doing the whole manual build?

**Comment by ojw28** [comment]
We don't provide any pre-builts for the FFMpeg extension because different apps will generally want to configure FFMpeg differently anyway. So you'd need to follow the instructions provided for the extension. It's pretty fast to get up and running.

**Comment by Tolriq** [comment]
Yes the ffmepg and extension I got it working, it's about the exoplayer part since I work with a custom aar and not a local exoplayer build currently.

**Comment by ojw28** [comment]
We don't provide any snapshots, sorry. There's a tracking issue here: https://github.com/google/ExoPlayer/issues/3859. There's also a discussion in that issue about using Jitpack as a way to get snapshots, so you could give that a try.

**Comment by Tolriq** [comment]
Ok thanks will follow the other issue, I have wayyy too many bad memories with Jitpack to ever rely on it ever again even for tests.
