### ISSUE TITLE
How to manually specify duration for stream?

### ISSUE THREAD

**Issue by cncb-gh** [google/ExoPlayer#6838]
When filing a question:
-----------------------
Fill out the sections below, leaving the headers but replacing the content. If
you're unable to provide certain information, please explain why in the relevant
section. We may close issues if they do not include sufficient information.

### [REQUIRED] Searched documentation and issues
"Timeline" class documentation

### [REQUIRED] Question
Is there a way to manually set the duration for a stream to enable seeking?  I am streaming a growing file, an http mpeg2 stream from a DVR with apparently an unspecified duration.  I know what the duration should be at any given time and could dynamically set a duration if there is a mechanism to do so.  There appears to be no way to modify the current Timeline.Window.  I am using the SimpleExoPlayer with an ExtractorMediaSource.

### A full bug report captured from the device
NA

### Link to test content
NA, server only streams locally

**Comment by marcbaechinger** [comment]
You are right that you can not change the timeline as it is an immutable object. The timeline is provided by the media source. When the information of the timeline changes the media source creates a new timeline and then notifies the player about the new timeline.

I think there is no other way to do that than providing your custom `CompositeMediaSource` which wraps a `ProgressiveMediaSource`. When the child media source calls the `onChildSourceInfoRefreshed`, you can wrap the timeline passed to `onChildSourceInfoRefreshed` with a `ForwardingTimeline` and override `getWindow(int windowIndex, Window window, long defaultPositionProjectionUs)` to set the duration of the window to the duration you know.

You can look into `ExtractorMediaSource` to see an example of such a wrapper. It actually already wraps a `ProgressiveMediaSource` and you can do it in a similar way.

**Comment by cncb-gh** [comment]
I will try that.  Thanks very much for your help.
