### ISSUE TITLE
How to save application specific information with download? 

### ISSUE THREAD

**Issue by ajay-aravind** [google/ExoPlayer#6840]
is the `byte[]  data` in downloadrequest  is the only way to save application specific data with download request? I wonder how to save if there is any application specific data like Objects.

**Comment by marcbaechinger** [comment]
Yes, the data field of type byte[] is the only application defined field which is persisted. 

You could actually store everything which you can transform from and to a byte array. I'd recommend though to only store small amount of data like that. Probably a key which you then can use for another storage mechanism to look up object data for the given key.

**Comment by ajay-aravind** [comment]
while my notification is updating every 250ms , I don't think it is a good idea to fetch data a from a table every 250ms is a good idea.

**Comment by marcbaechinger** [comment]
I actually can't see a reason for posting a notification every 250ms and if you do, how is this related to storing custom app data with a download request? I think you could just keep that data in memory.

Can you give a little bit more details about your use case?
