### ISSUE TITLE
Since 2.11.0 TrueHD videos stuck and playback time goes backwards

### ISSUE THREAD

**Issue by aarondib** [google/ExoPlayer#6845]
Since 2.11.0 library version videos with TrueHD audio track - stuck, when audio track is selected.
Also, playback time goes backwards.

The bug was reproduced on Nvidia Shield TV device and tested with different video samples.
There is no such issue on all previous library versions, up-to 2.10.8.
Also, no such issue on Sony Bravia TV, as it does not support TrueHD decoding.

[TrueHD Sample URL](https://samples.ffmpeg.org/A-codecs/TrueHD/TrueHD%20Sample%201%20(Final%20Fantasy%20VII%20Advent%20Children).mkv)
[Other TrueHD samples](https://samples.ffmpeg.org/A-codecs/TrueHD/)

**Comment by aarondib** [comment]
_Update:_
Nvidia Shield TV is connected to AVR Pioneer VSX-832. Video sample stuck at start playing, playback time goes to negative values, while sound (TrueHD audio track) is playing fine from AVR.

**Comment by andrewlewis** [comment]
It looks like this broke as part of recent changes to support Matroska block lacing. I'm investigating now.

**Comment by andrewlewis** [comment]
A fix for this is in review now.
