### ISSUE TITLE
Blank screen while switching video from portrait to landscape full screen for DRM enabled videos in DASH format

### ISSUE THREAD

**Issue by meenukrishnamurthy** [google/ExoPlayer#6847]
Issue description:
While switching a video from portrait to landscape mode a blank black screen is visible for a sec before showing the video frame.This happens while switching from landscape to portrait also.This is occuring only for the videos which are DRM protected.This is seen only in few devices.It appears in the exoplayer demo app as well.

Reproduction steps:
1.In the exoplayer demo app play the video with DASH+DRM
2.Enable auto rotate option in settings.
3.Rotate the phone to landscape.
4.A blank screen is shown for a sec before the video frame shows up.
5.Switch to portrait again and see the same blank screen

Link to test content
You can check any drm enabled video from the demo app for dash stream.

Version of ExoPlayer being used
2.9.0

Device(s) and version(s) of Android being used
1.Mi Note 7 Pro Android version:9.0--Issue arises
2.Asus Zenfone Max Pro M2. Android version:8.0--Issue arises
3.Real Me 2 Pro. Android version 9.0--No issue
4.Lenovo K5 note. Android Version 6.0--Issue Arises
5.Samsung Galaxy J2 Pro. Andorid version 6.0--No Issue
6.Mi A2. Android Version 9.0--No issue
7.Redmi Note 3. Android Version 6.0--No issue 

Could you please check into this issue.

**Comment by ojw28** [comment]
This is a limitation in the underlying platform. The fact that the output path is secure means that the video buffers aren't available to be composited into the rotation animation when the display orientation changes, so for the duration of the animation the surface appears as though it is black. You will observe the issue in all applications that play DRM protected content.

**Comment by meenukrishnamurthy** [comment]
Can you be more specific as to which underlying platform the issue arises.Because i dont see this issue in all the devices.

**Comment by ojw28** [comment]
As above:

> The fact that the output path is secure means that the video buffers aren't available to be composited into the rotation animation when the display orientation changes, so for the duration of the animation the surface appears as though it is black.

I'm not sure why you don't see the issue on all devices, but my best guess would be that your content doesn't require a secure output path in the license policy, and that the devices where you don't see the issue only support L3 Widevine. If that's the case then you could try forcing L3 Widevine on all devices, to see if that resolves the problem.

Alternatively, is it possible the devices where you don't see the issue simply don't animate orientation changes?

**Comment by meenukrishnamurthy** [comment]
Thanks a lot @ojw28 . Forcing to L3 on all devices worked for me.
