### ISSUE TITLE
Question: HLS Video change quality via PopupMenu

### ISSUE THREAD

**Issue by yoobi** [google/ExoPlayer#6849]
### [REQUIRED] Searched documentation and issues

I've looked into the issue, your exoplayer.dev and stackoverflow.
In the issue I've seen that you recommend to create a UI on our own [#5261](https://github.com/google/ExoPlayer/issues/5261)

I've seen many post on stackoverflow, and created my own but yet no answer.

On Exoplayer I think the TrackSelectionView would be useful therefore my question.

### [REQUIRED] Question

What I want to achieve is just like the TrackSelectionDialogBuilder but with a custom view. I've seen the class TrackSelectionView, How can I use the TrackSelectionView to link it to my view and will it manage the change of quality ?

So far I've been able to retrieve the videoRenderer which is the only that is interesting to me 
``` lang-kotlin
       var arrQuality : TrackGroupArray? = null
       for(i in 0 until mappedTrackInfo.rendererCount){
            if(isVideoRenderer(mappedTrackInfo, i)){
                videoRenderer = i
            }
        }
        trackGroupsQuality = mappedTrackInfo.getTrackGroups(videoRenderer)
        val trackSelectionView = TrackSelectionView(this)
        val listOverride = listOfNotNull(parameters.getSelectionOverride(videoRenderer, trackGroupsQuality))
        trackSelectionView.init(mappedTrackInfo, videoRenderer, true, listOverride, null)
```

How can I link my trackSelectionView to a View or something that the user can select the quality ?

### Link to test content

[m3u8 video](https://bitdash-a.akamaihd.net/content/MI201109210084_1/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8)

**Comment by marcbaechinger** [comment]
The `TrackSelectionView` is a `LinearLayout` which you can use within your own layouts of a fragment or activity. You can call the `init` method and pass the track information as a `MappedTrackInfo object.

You can pass a `TrackSelectionListener` to the `init` method to be informed of changes the user makes. You still need to apply these choices to the `TrackSelector` you are using with the player. Looking into `TrackSelectionDialog.createForTrackSelector(..)` gives yo an example.

> How can I use the TrackSelectionView to link it to my view and will it manage the change of quality?

Please narrow down you question a bit if you have further questions.

**Comment by yoobi** [comment]
> How can I use the TrackSelectionView to link it to my view and will it manage the change of quality?

For example if I create a LinearLayout called `selection_view.xml` how can I tell my TrackSelectionView to bind to it ?

My second question is about, how can I change the quality video on user selection. But I think you answered it and it'll be via the TrackSelectionListener

**Comment by marcbaechinger** [comment]
Yes, the `TrackSelectionListener` is a callback to which the selection of the user is passed. You can then apply it to the `DefaultTrackSelector` which you are probably using. You can use the `DefaultTrackSelector.ParameterBuilder`. [See also how the `TrackSelectionDialog` is doing it](https://github.com/google/ExoPlayer/blob/76962d50f1d80941d6768e4e765fa4ff010705e7/demos/main/src/main/java/com/google/android/exoplayer2/demo/TrackSelectionDialog.java#L99).

**Comment by yoobi** [comment]
I'm kind of lost with TrackSelectionView, once it is init what can I do with it ? or can I display the View that i just created ?

My goal is to use the TrackSelectionView to populate a PopupMenu I got and via the Listener change the quality

**Comment by marcbaechinger** [comment]
I think when you want to use a `PopupMenu` you probably just want to populate it with the tracks which are available for your stream. Something like `popup.getMenu().add("fooBar)`

**Comment by yoobi** [comment]
Yeah populate the `PopupMenu` and then be able to change the quality from that `PopupMenu`
So you're saying I should just get the TrackGroups populate my menu and then do the change of quality with the `setOnMenuItemClickListener` ?

**Comment by marcbaechinger** [comment]
It depends on your use case and streams. 

If you need the generic abilities of the `TrackSelectionView` you can do this as you've done it above. Then you can call `TrackSelectionView.getOverrides()`  to get the overrides resulting from the view state. Use these overrides to build parameters for the `DefaultTrackSelector` to apply the selection in the UI. You can [refer to the `TrackSelectionDialog`](https://github.com/google/ExoPlayer/blob/76962d50f1d80941d6768e4e765fa4ff010705e7/demos/main/src/main/java/com/google/android/exoplayer2/demo/TrackSelectionDialog.java#L99) which builds parameters from these overrides in such a way.

`TrackSelectionView` works with all streams of the demo app , including adaptive streams. It's quite technical though and allows enabling/disabling certain tracks. This can be overwhelming for a user. If you want to have a simple user model, you probably just want something like high/medium/low bandwidth or an upper/lower limit. In such a case you can make a `PopupMenu` which offers these variants like you suggested. Then translate these variants into a [parameter based track selection using a builder](https://exoplayer.dev/track-selection.html).

**Comment by yoobi** [comment]
Okay thank you for your help :)
It's a shame there is no tutorial for this, since it's demanded by a lot of people.
