### ISSUE TITLE
Adding Time Interval.(ConcatenatingMediaSource)

### ISSUE THREAD

**Issue by ShengjieGeng** [google/ExoPlayer#6850]
Is there any method to add a time interval between every item in ConcatenatingMediaSource's playlist?
I'd appreciate it if receiving some tips.

**Comment by andrewlewis** [comment]
`SilenceMediaSource` can be used to insert gaps (see #5735), but you need to add these into the concatenation yourself.

**Comment by marcbaechinger** [comment]
Let us know whether this solves your problem. As @andrewlewis mentioned you need to add SilenceMediaSources to the concatenating media source. It also appears as an additional window in between the actual media tracks.
