### ISSUE TITLE
UDP Multicast Stream not working

### ISSUE THREAD

**Issue by cardinaltm** [google/ExoPlayer#6851]
### Issue description
Hello, not working UDP Multicast stream on any devices,
i will use this version exoplayer: com.google.android.exoplayer:exoplayer:2.11.1
and i get black screen, nothing else

URL: udp://@239.192.50.2:1234
i try with "@" symbol, and without symbol. result is one, black sreen.

P.S. in VLC everythings works ok
```
DataSource.Factory factory = () -> new UdpDataSource(3000, 100000);
ExtractorsFactory tsExtractorFactory = () -> new TsExtractor[]{new TsExtractor(MODE_SINGLE_PMT, new TimestampAdjuster(0), new DefaultTsPayloadReaderFactory())};
MediaSource mediaSource = new ExtractorMediaSource(videoUri, factory, tsExtractorFactory,null,null);
```
Please help me, i need udp stream to turn on.

### Version of ExoPlayer being used:
com.google.android.exoplayer:exoplayer:2.10.0

### Device(s) and version(s) of Android being used:
Global Problem

**Comment by marcbaechinger** [comment]
I think I can not access that server. Plesae let me know if I'm wrong nad the server is available for me for testing.

Alternatively, can you please add the stream to the demo app, play the stream and after it failed, [take a bug report](https://developer.android.com/studio/debug/bug-report) which you upload here?

Add this to the `media.exolist.json` file of the demo app:

```
{
    "name": "Issue #6851",
    "uri": "udp://239.192.50.2:1234"
},
```

**Comment by cardinaltm** [comment]
UDP Multicast, working only on local net, and cant watch from outside
I think this is not a problem because of UDP Multicast, i reorganize my issue #6854
