### ISSUE TITLE
Some Streams not working

### ISSUE THREAD

**Issue by cardinaltm** [google/ExoPlayer#6854]
### Issue description
Some streams not working on exoplayer, but its working in vlc

Stream PALITRA:
working on exoplayer perfectly
http://188.169.194.17:8000/play/palitranews/index.m3u8

Stream ARKHI:
not working on exoplayer, but working in vlc, i get black screen, and no audio
http://188.169.194.17:8000/play/1arkhi/index.m3u8

I just can not understand what could be the problem.
help me please.

P.S. when i disable video from the settings, then i can hear audio

media.exolist.json file:
```
{
    "name": "HLS",
    "samples": [
      {
        "name": "ARKHI",
        "uri": "http://188.169.194.17:8000/play/1arkhi/index.m3u8"
      },
      {
        "name": "PALITRA",
        "uri": "http://188.169.194.17:8000/play/palitranews/index.m3u8"
      }
    ]
  },
```
### Version of ExoPlayer being used
com.google.android.exoplayer:exoplayer:2.11.1

### Device(s) and version(s) of Android being used
Global Problem

**Comment by marcbaechinger** [comment]
The audio track of ARKHU is of type audio/mpeg-L2 which is not supported by ExoPlayer. When I try to play it, EventLogger logs the following to logcat:

```
[ ] Track:0, id=1100/3, mimeType=audio/mpeg-L2, channels=2, sample_rate=48000, language=ka, supported=NO_UNSUPPORTED_TYPE
```

For the stream ARKHI I further get some http 404 for instance for http://188.169.194.17:8000/play/1arkhi/eepqr5ll.ts

I get the same when doing

```
curl "http://188.169.194.17:8000/play/1arkhi/eepqr5ll.ts"
```

**Comment by cardinaltm** [comment]
Hello,
audio/mpeg-L2 is working, please try this channel: http://188.169.194.17:8000/play/aljazeera/index.m3u8, here is audio/mpeg-L2
please try a latest exoplayer version
i will get this:

Aljazeraa
```
Track:0, id=708/3, mimeType=audio/mpeg-L2, channels=2, sample_rate=48000, language=ar, supported=YES
```
ARKHI
```
Track:0, id=1100/3, mimeType=audio/mpeg-L2, channels=2, sample_rate=48000, language=ka, supported=YES
```

about http://188.169.194.17:8000/play/1arkhi/eepqr5ll.ts
you can’t download this file if you don’t quickly do it, the point is that the HLS will delete the old .ts files that it no longer needs

**Comment by marcbaechinger** [comment]
You can not rely on this as it may be device specific. If you want to make sure it is supported you need to use the ffmpeg extension which does decode in software.

Regarding the 404: I see this when the demo app wants to play the stream. I can repro this each time I try.

**Comment by cardinaltm** [comment]
when I checked, it turned out that several more channels do not work in exoplayer from the same transponder - 490 MHz, but with the rest of the frequencies everything works in exoplayer
