### ISSUE TITLE
How to get observed fps, bitrate on RTSP

### ISSUE THREAD

**Issue by HGYEONG** [google/ExoPlayer#6855]
I have used exoplayer for playing RTSP on android.
But, I have a trouble.
I need a observed information of RTSP, such as bitrate, fps, delay time.
The information must be checked on real time.

Do u have any idea for this problem?

**Comment by marcbaechinger** [comment]
The `Player.EventListener` has a callback `onTracksChanged` which is called when a track selection has occured. It reports which track has been selected. You can for instance get the `Format` of the current video track. This format does include fields like bitrate and fps of the track currently being played.

I'm not sure whether I understand the question correctly I'm afraid. Please let me know in case I misunderstand your question.

**Comment by HGYEONG** [comment]
> The `Player.EventListener` has a callback `onTracksChanged` which is called when a track selection has occured. It reports which track has been selected. You can for instance get the `Format` of the current video track. This format does include fields like bitrate and fps of the track currently being played.
> 
> I'm not sure whether I understand the question correctly I'm afraid. Please let me know in case I misunderstand your question.

In my case, it doesn't happen that track selection has occured.
I want to get information of RTSP when I see my RTSP live streaming on exoplayer.

**Comment by HGYEONG** [comment]
Thank you for your reply!

In my case, the video is live streaming.
Is your solution good in my case?
If it's okay, please show me an example!!

**Comment by marcbaechinger** [comment]
This works for any stream including live.

The demo app is a good example. It shows you how you can setup the player and add an event listener. It's not too difficult and it's always worth to look into existing samples in a project. You find [the demo app as part of this repository](https://github.com/google/ExoPlayer/blob/release-v2/demos/main/src/main/java/com/google/android/exoplayer2/demo/PlayerActivity.java#L382).

**Comment by HGYEONG** [comment]
Sorry, I have one more question.

I don't want to make track list, but your solution need to make track list.
Is it okay to use for just one live streaming?

**Comment by HGYEONG** [comment]
Thank you!

But, I don't understand one point of your answer.
What is track means?

**Comment by HGYEONG** [comment]
This is my code.
It play very well, but I can't see any format for bitrate and fps...


import android.net.Uri;
import android.os.Bundle;
import android.util.Log;

import androidx.appcompat.app.AppCompatActivity;

import com.google.android.exoplayer2.ExoPlayerFactory;
import com.google.android.exoplayer2.PlaybackPreparer;
import com.google.android.exoplayer2.Player;
import com.google.android.exoplayer2.SimpleExoPlayer;
import com.google.android.exoplayer2.metadata.Metadata;
import com.google.android.exoplayer2.metadata.MetadataOutput;
import com.google.android.exoplayer2.source.TrackGroup;
import com.google.android.exoplayer2.source.TrackGroupArray;
import com.google.android.exoplayer2.source.rtsp.RtspDefaultClient;
import com.google.android.exoplayer2.source.rtsp.RtspMediaSource;
import com.google.android.exoplayer2.source.rtsp.core.Client;
import com.google.android.exoplayer2.trackselection.TrackSelectionArray;
import com.google.android.exoplayer2.ui.PlayerView;
import com.google.android.exoplayer2.upstream.DefaultBandwidthMeter;


public class MainActivity extends AppCompatActivity {

    PlayerView playerView;
    SimpleExoPlayer player = null;

    private Boolean playWhenReady = true;
    private int currentWindow = 0;
    private Long playbackPosition = 0L;

    DefaultBandwidthMeter defaultBandwidthMeter;


    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        playerView = findViewById(R.id.player_view);
        defaultBandwidthMeter = new DefaultBandwidthMeter();


        if (player == null) {
            player = ExoPlayerFactory.newSimpleInstance(MainActivity.this);
            playerView.setPlayer(player);
        }
        
        String url = "rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov";
        RtspMediaSource videoSource = new RtspMediaSource
                .Factory(RtspDefaultClient.factory()
                .setFlags(Client.FLAG_ENABLE_RTCP_SUPPORT)
                .setNatMethod(Client.RTSP_NAT_DUMMY))
                .createMediaSource(Uri.parse(url));

        //재생 준비를 위한 호출 콜백 함수
        playerView.setPlaybackPreparer(new PlaybackPreparer() {
            @Override
            public void preparePlayback() {

            }
        });
        player.addMetadataOutput(metadataOutput);
        player.addListener(eventListener);

        player.prepare(videoSource, true, false);
        player.setPlayWhenReady(true);



    }


    Player.EventListener eventListener = new Player.EventListener() {
        @Override
        public void onTracksChanged(TrackGroupArray trackGroups, TrackSelectionArray trackSelections) {
            for(int i = 0; i< trackGroups.length; i++){
                TrackGroup trackGroup = trackGroups.get(i);
                for(int j = 0; j< trackGroup.length; j++){
                    Metadata metadata = trackGroup.getFormat(j).metadata;
                    if(metadata != null){
                        Log.d("Metatdata Track", metadata.toString());
                    }
                }
            }
        }
    };

    MetadataOutput metadataOutput = new MetadataOutput() {
        @Override
        public void onMetadata(Metadata metadata) {
            Log.d("METADATA", metadata.toString());
        }
    };

    @Override
    protected void onStart(){
        super.onStart();

    }

    @Override
    protected void onStop(){
        super.onStop();

        if(player!=null){
            playbackPosition = player.getContentPosition();
            currentWindow = player.getCurrentWindowIndex();
            playWhenReady = player.getPlayWhenReady();

            playerView.setPlayer(null);
            player.release();
            player = null;
        }
    }


}

**Comment by marcbaechinger** [comment]
What is 

```
Log.d(TAG, trackGroup.getFormat(j).toString());
```

giving you?

https://github.com/google/ExoPlayer/blob/76962d50f1d80941d6768e4e765fa4ff010705e7/library/core/src/main/java/com/google/android/exoplayer2/Format.java

**Comment by HGYEONG** [comment]
![캡처](https://user-images.githubusercontent.com/35682252/72394595-2684da00-377a-11ea-8c80-9db891b14e1d.PNG)

I can't get anything...

**Comment by marcbaechinger** [comment]
You can always refer to the Java Doc of ExoPlayer to see what fields and methods a class like `Format` has. Try [this example of the JavaDoc of Format](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/Format.html) and see if it helps. 

Another, a bit more advanced technique for open source projects, is to look into the source code. It could [tell you how the toString() method constructs the string above](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/Format.java#L1518).

You can search for the terms you asked for in the first comment: bitrate and frameRate.

**Comment by HGYEONG** [comment]
Okay, Thank you

But, I think this is not suitable method for me because I want to get video information every second when RTSP is playing...

**Comment by HGYEONG** [comment]
Omg... I'm sorry... :( 
This is my mistake and happened lack of knowledge about video streaming.
Your solution is right!!
My streaming is based on video, so it has its information.
As a result, it is the correct output that bitrate is null!
