### ISSUE TITLE
Is it mandatory to integrate leanback extension for playback on TV

### ISSUE THREAD

**Issue by krackjack234** [google/ExoPlayer#6859]
### [REQUIRED] 
Searched documentation and issues but didnt find required answer

### [REQUIRED] 
We understand leanback extension is more to do with TV UI and not to do with actual playback.

Is it advisable to integrate leanback extension ( [https://bintray.com/google/exoplayer/extension-leanback/) ]) with exoplayer to support playback on tv platform ? 

If yes, do the exoplayer extension for leanback feature-complete or are they any know limitation?

Otherwise can the app developer take vanilla exoplayer and use the leanback classes independently in the TV App?

Thanks in advance !

**Comment by marcbaechinger** [comment]
> Is it advisable to integrate leanback extension ( [https://bintray.com/google/exoplayer/extension-leanback/) ]) with exoplayer to support playback on tv platform ?

If you want to integrate with Leanback you probably want to provide a `PlayerAdapter` which uses ExoPlayer. The leanback extension provides such a player adapter implementation, so you don't need to do your own. It saves you some time.

> If yes, do the exoplayer extension for leanback feature-complete or are they any know limitation?

The extension provides a `PlayerAdapter`. So in the sense that the extension provides all the feature of a PlayerAdapter, it is feature complete. 

>  Otherwise can the app developer take vanilla exoplayer and use the leanback classes independently in the TV App?

Of course. The leanback classes work with any player so you can do your own `PlayerAdapter` which is using ExoPlayer. I'd look into the version of the extension first though. You can probably save some duplication or at list get some hints on what's to do.

**Comment by krackjack234** [comment]
Thanks @marcbaechinger

**Comment by marcbaechinger** [comment]
Cool. I'm closing this issue. Please reopen if required.
