### ISSUE TITLE
How do I update cookie while the player is playing?

### ISSUE THREAD

**Issue by chanbbong** [google/ExoPlayer#6865]
I play video with a cookie that has a 60 second expiry.
So when the cookie expires, the video stop playing.
How do I update cookie in playing?
How to check expired cookie?
Should I use `player.prepare()` periodically?
If I use `player.prepare()` periodically, buffering occurs every time.

**Comment by ojw28** [comment]
@tonihei - Probably a use case for `ResolvingDataSource`? Do we have any documentation describing how to do this?

**Comment by tonihei** [comment]
Yes, it sounds as if you can solve this by using a `ResolvingDataSource` that sets the right cookie for each request at the time the request is made. See [here](https://exoplayer.dev/progressive.html#customizing-server-interactions) for an example how to use this data source for setting request headers.

**Comment by chanbbong** [comment]
thx
