### ISSUE TITLE
Does leanback extension provide any advantages over direct player implementation for Activity responsible for Playback?

### ISSUE THREAD

**Issue by Debayudh** [google/ExoPlayer#6868]
### [REQUIRED] Question
Hi, 
We have an exoplayer implementation that is already running our streaming mobile app.
Now that we are expanding our scope to androidTV, we are looking at the leanback extension.
Is there any developmental advantage/method that LeanbackPlayerAdapter provides over a plain implementation of exoplayer?
Currently, we are not using SurfaceHolderGlueHost/PlaybackGlueHost/VideoSurfaceView. Instead, we are directly using PlayerView. Can this cause any complications while porting to androidTV?

**Comment by ojw28** [comment]
The leanback extension is an optional component for connecting ExoPlayer to the leanback UI components. If you want to use the leanback UI components for your app's TV UI, then you should use it. If you don't want to use them, then you shouldn't. It doesn't do provide any additional or hidden benefits.
