### ISSUE TITLE
Does amazon fire stick support default exoplayer, or will we need to use amazon's exoplayer port?

### ISSUE THREAD

**Issue by Debayudh** [google/ExoPlayer#6869]
### [REQUIRED] Searched documentation and issues
Searched but did not find anything relevant.

### [REQUIRED] Question
For supporting playback on Amazon fire stick, will our default exoplayer implementation work, or do we need to use the exoplayer port published by amazon on:
https://github.com/amzn/exoplayer-amazon-port

**Comment by ojw28** [comment]
See https://github.com/google/ExoPlayer/issues/4947
