### ISSUE TITLE
Program type already present

### ISSUE THREAD

**Issue by adnan-dzindo-ct** [google/ExoPlayer#6871]
I added the latest Exoplayer library, now I have naming conflict probably several libraries use same support lib. Any Idea how to resolve this

D8 Error:
Program type already present: **android.support.v4.media.MediaBrowserCompat$CustomActionCallback**

**Comment by ojw28** [comment]
[Please see here?](https://www.google.com/search?q=Program+type+already+present%3A+android.support.v4.media.MediaBrowserCompat%24CustomActionCallback)
