### ISSUE TITLE
Supporting decoder reuse when calling release()?

### ISSUE THREAD

**Issue by greyski** [google/ExoPlayer#6872]
### [REQUIRED] Searched documentation and issues
I looked over the documentation and links in the blog post regarding decoder reuse: https://medium.com/google-exoplayer/improved-decoder-reuse-in-exoplayer-ef4c6d99591d

### [REQUIRED] Question
It can probably be assumed (even having looking at the source code it seems to be the case), but should we also avoid calling `release()` if we want to support decoder reuse?

I noticed `setForegroundMode()` only  handles decoder reuse for `stop()`, but wanted to get an official confirmation that `release()` would completely clear out the media decoder.

### A full bug report captured from the device
N/A

### Link to test content
N/A

**Comment by ojw28** [comment]
`release()` will always clear out the media decoder.
