### ISSUE TITLE
Render subtitles from an SRT file along with an audio source

### ISSUE THREAD

**Issue by shubhamvashisht** [google/ExoPlayer#6873]
### [REQUIRED] Searched documentation and issues
searched on stackoverflow

### [REQUIRED] Question
I want to render subtitles from an .srt file in subtitleview along with an audio source. Is there any good example which demonstrate something similar?

**Comment by ojw28** [comment]
Have you [read the documentation](https://exoplayer.dev/media-sources.html#side-loading-a-subtitle-file)? If not, does that answer your question? If so, which part are you stuck on?
