### ISSUE TITLE
ExoPlayerImplInternal: Internal runtime error.

### ISSUE THREAD

**Issue by perracodex** [google/ExoPlayer#6874]
### Issue description
Getting randomly an exception when rotating the device orientation between portrait and landscape, and the player gets recreated.
The player uses the surface from an external TextureView in order to use shaders, and is assigned via the setVideoSurface method.
I can only reproduce it if I rotate the device to change between portrait and landscape, but takes a while (several rotations none stop), as it happens rarely.
I made sure that the player is released when changing the device orientation.
Maybe it has something to do (just guessing) if ExoPlayer releases its resources in a separate thread, and when rotating and recreating the player is still in the process of releasing, making the MediaCodecs not to be ready yet, just a guess.

### Reproduction steps
Rotate the device between portrait to landscape several times, so the player gets recreated.

### A full bug report captured from the device
[stacktrace.txt](https://github.com/google/ExoPlayer/files/4060795/stacktrace.txt)

### Version of ExoPlayer being used
ExoPlayer 2.11.1

### Device(s) and version(s) of Android being used
Huawei SNE-LX1 API - Android 9 (harder to reproduce)
Motorola XT1058 - Android 5.1 (in this device is easier to reproduce)

**Comment by andrewlewis** [comment]
`android.media.MediaCodec.setOutputSurface` is throwing and there is logging like "MapperHal: buffer descriptor with invalid usage bits 0x2000".

> Maybe it has something to do (just guessing) if ExoPlayer releases its resources in a separate thread, and when rotating and recreating the player is still in the process of releasing, making the MediaCodecs not to be ready yet, just a guess.

When you call `release` ExoPlayer blocks until codecs have been returned to the system, so as long as you use player instances only from the main thread then all usage will be serialized.

If you switch to using a normal `SurfaceView` for output (no shaders involved) do you still see the same issue?

**Comment by perracodex** [comment]
When **not** using at all an external TextureView, and therfore not calling **SimpleExoPlayer.setVideoSurface**, it presents no problem in any of the devices, regardless if using an internal TextureView or SurfaceView via the **app:surface_type** xml tag.
 
The player is created and released in the UI thread, and each time is a new instance as the view is recreated when changing between portrait and landscane,
The **setVideoSurface** method is also called in the UI thread. 

I made sure that the surface is cleared from the player. This is the release flow:

```
simpleExoPlayer.setPlayWhenReady(false);
simpleExoPlayer.stop(true);
simpleExoPlayer.setVideoSurface(null);
simpleExoPlayer.release();
```
The Motorola XT1058 with API 5.1 is more propence to produce the exception, in addition it throws sometimes also a IllegalStateException. See the next stacktrace for more detail:
[stacktrace.txt](https://github.com/google/ExoPlayer/files/4064667/stacktrace.txt)

**Comment by perracodex** [comment]
I was able to create a test project that reproduces the problem, Find it attached to this message. 
Even if the code makes not much sense, is all set to force the issue. Try it if possible in old devices, in newer faster devices can take a while to reproduce.

The steps to reproduce it is quite simple and very boring to execute:

1) Run the app, and then rotate the device between portrait-landscape nonstop until your hand falls sleep, and you start to wonder what are you doing with your life. 

It can take a while to make it fail, **the screen will become black and throw the exception only in the logcat, the app will not crash.**

I include also a video recording reproducing the error, just to make it clearer. When the screen becomes black is when the exception is thrown. It took nearly two minutes of rotation, although sometimes can happen just after a few seconds of trying.

[Test.zip](https://github.com/google/ExoPlayer/files/4072237/Test.zip)
[Recording.zip](https://github.com/google/ExoPlayer/files/4072244/Recording.zip)

**Comment by andrewlewis** [comment]
Sorry for the year-long delay! I had a quick look at the sources and wanted to suggest the problem might be related to the lifecycle of the surface from the surface texture: it looks like there is no blocking player call to set the surface when it's destroyed, and I guess that might cause the codec to be retained for slightly longer.

One final thing to note is that the kernel log in a bug report on some devices includes information about when codecs are instantiated and destroyed. If you could take a bug report after reproducing the issue that may help us eliminate the possibility that decoder lifetimes are overlapping.

If that doesn't help it would be good if you could try replicating the issue with a small patch to the ExoPlayer demo app so it's less time-consuming for us to investigate what could be going wrong.
