### ISSUE TITLE
How to detect DefaultTrackSelector selecting no tracks?

### ISSUE THREAD

**Issue by l1bbcsg** [google/ExoPlayer#6875]
### [REQUIRED] Searched documentation and issues

Couldn't find particular documentation on how to deal with `TrackGroupArray` and `TrackSelectionArray`.
Several relevant issues seem to mostly address ExoPlayer v1.

### [REQUIRED] Question

Suppose a DRM protected content that's being played without a `DrmSessionManager` initialized (which is an error and I'm trying to handle it).

```java
Uri clean = Uri.parse("https://demo.unified-streaming.com/video/tears-of-steel/tears-of-steel.ism/.mpd");
Uri drmProtected = Uri.parse("https://demo.unified-streaming.com/video/tears-of-steel/tears-of-steel-dash-playready.ism/.mpd");

HttpDataSource.Factory dataSourceFactory = new DefaultHttpDataSourceFactory(Util.getUserAgent(context, BuildConfig.APPLICATION_ID));
DashMediaSource.Factory mediaSourceFactory = new DashMediaSource.Factory(dataSourceFactory);

HttpMediaDrmCallback playreadyCallback = new HttpMediaDrmCallback(
    "https://test.playready.microsoft.com/service/rightsmanager.asmx?PlayRight=1&UseSimpleNonPersistentLicense=1",
    dataSourceFactory
);
DefaultDrmSessionManager playreadyManager = new DefaultDrmSessionManager.Builder()
        .setUuidAndExoMediaDrmProvider(C.PLAYREADY_UUID, FrameworkMediaDrm.DEFAULT_PROVIDER)
        .build(playreadyCallback);

DefaultTrackSelector trackSelector = new DefaultTrackSelector(context);
SimpleExoPlayer player = new SimpleExoPlayer.Builder(context)
        .setTrackSelector(trackSelector)
        .build();
player.setPlayWhenReady(true);
((PlayerView) context.findViewById(R.id.player_view)).setPlayer(player);

player.addAnalyticsListener(new EventLogger(trackSelector));

// No visual or audible playback, no errors
MediaSource mediaSourceWithoutDrmManager = mediaSourceFactory.createMediaSource(drmProtected);
player.prepare(mediaSourceWithoutDrmManager);

// Plays correctly
//MediaSource mediaSourceWithDrmManager = mediaSourceFactory.setDrmSessionManager(playreadyManager).createMediaSource(drmProtected);
//player.prepare(mediaSourceWithDrmManager);

// Plays correctly
//MediaSource cleanMediaSource = mediaSourceFactory.createMediaSource(clean);
//player.prepare(cleanMediaSource);
```

The stream has several video, audio and subtitle tracks, audio and video are protected while subtitles are not.
`DefaultTrackSelector` fails to select any audio or video, but does not report any errors and seemingly plays content normally (probably only attempting to play subtitles) which is not a desirable outcome, I'd like to fail playback altogether and report DRM error.

Tracks as output by `EventLogger`:
```
tracks [eventTime=1.17, mediaPos=0.00, window=0, period=0, 
  Renderer:0 [
    Group:0, adaptive_supported=YES [
      [ ] Track:0, id=video_eng=401000, mimeType=video/avc, bitrate=401000, codecs=avc1.42C00D, res=224x100, fps=24.0, supported=NO_UNSUPPORTED_DRM
      [ ] Track:1, id=video_eng=751000, mimeType=video/avc, bitrate=751000, codecs=avc1.42C016, res=448x200, fps=24.0, supported=NO_UNSUPPORTED_DRM
      [ ] Track:2, id=video_eng=1001000, mimeType=video/avc, bitrate=1001000, codecs=avc1.4D401F, res=784x350, fps=24.0, supported=NO_UNSUPPORTED_DRM
      [ ] Track:3, id=video_eng=1501000, mimeType=video/avc, bitrate=1501000, codecs=avc1.640028, res=1680x750, fps=24.0, supported=NO_UNSUPPORTED_DRM
      [ ] Track:4, id=video_eng=2200000, mimeType=video/avc, bitrate=2200000, codecs=avc1.640028, res=1680x750, fps=24.0, supported=NO_UNSUPPORTED_DRM
    ]
    Group:1, adaptive_supported=YES [
      [ ] Track:0, id=video_eng_1=902000, mimeType=video/hevc, bitrate=902000, codecs=hvc1.1.6.L150.90, res=1680x750, fps=24.0, supported=NO_UNSUPPORTED_DRM
      [ ] Track:1, id=video_eng_1=1161000, mimeType=video/hevc, bitrate=1161000, codecs=hvc1.1.6.L150.90, res=2576x1150, fps=24.0, supported=NO_UNSUPPORTED_DRM
      [ ] Track:2, id=video_eng_1=1583000, mimeType=video/hevc, bitrate=1583000, codecs=hvc1.1.6.L150.90, res=3360x1500, fps=24.0, supported=NO_UNSUPPORTED_DRM
    ]
  ]
  Renderer:1 [
    Group:0, adaptive_supported=YES [
      [ ] Track:0, id=audio_eng=64008, mimeType=audio/mp4a-latm, bitrate=64008, codecs=mp4a.40.2, channels=2, sample_rate=48000, language=en, supported=NO_UNSUPPORTED_DRM
      [ ] Track:1, id=audio_eng=128002, mimeType=audio/mp4a-latm, bitrate=128002, codecs=mp4a.40.2, channels=2, sample_rate=48000, language=en, supported=NO_UNSUPPORTED_DRM
    ]
  ]
  Renderer:2 [
    Group:0, adaptive_supported=N/A [
      [ ] Track:0, id=textstream_eng=1000, mimeType=application/ttml+xml, bitrate=1000, codecs=stpp.ttml.im1t, language=en, supported=YES
    ]
    Group:1, adaptive_supported=N/A [
      [ ] Track:0, id=textstream_rus=1000, mimeType=application/ttml+xml, bitrate=1000, codecs=stpp.ttml.im1t, language=ru, supported=YES
    ]
  ]
]
```

I tried the following:

`onTracksChanged` callback in `Player.EventListener` that gets `TrackGroupArray` and `TrackSelectionArray`, but I'm lost trying to get this information out of them, is that even the right data?
I saw `Player.getVideoFormat` and `Player.getAudioFormat` suggested to get current track info, but both return `null` in `onTracksChanged` regardless of which of the three MediaSources was played.

`onDownstreamFormatChanged` callback in `MediaSourceEventListener` – `Player.getVideoFormat` and `Player.getAudioFormat` report relevant data there, but then it does not get called when playback fails in my DRM example.

I'm running this on Sony Bravia Android TV 7.0 with ExoPlayer 2.11.1, but I believe it's a general enough question since other factors besides DRM such as codecs or bandwidth can cause track selection to be empty. 

How can I detect that no video and/or no audio tracks were selected for playback?

Alternatively, how can I receive a notification the stream I'm playing requires DRM? That would also suffice in my case.

**Comment by icbaker** [comment]
The demo app uses `MappingTrackSelector#.getCurrentMappedTrackInfo()` inside `EventListener#onTracksChanged` to get info about the selected tracks:
https://github.com/google/ExoPlayer/blob/ea342a671c610916fdcdcb3c4f5c740ff1374719/demos/main/src/main/java/com/google/android/exoplayer2/demo/PlayerActivity.java#L694

When I remove the DRM info from an entry in `media.exolist.json` [1] and then play the file, I get a toast saying "Media includes audio tracks, but none are playable by this device".

I think you can adapt that logic to halt playback completely if you discover that the audio and/or video are completely unsupported.

[1]
```diff
{
  "name": "WV: Secure SD (cenc,MP4,H264)",
+  "uri": "https://storage.googleapis.com/wvmedia/cenc/h264/tears/tears_sd.mpd"
-  "uri": "https://storage.googleapis.com/wvmedia/cenc/h264/tears/tears_sd.mpd",
-  "drm_scheme": "widevine",
-  "drm_license_url": "https://example.com/invalid-license"
}
```

**Comment by l1bbcsg** [comment]
This is exactly what I was looking for, `MappedTrackInfo.getTypeSupport()` reports relevant and detailed enough info.
Thank you!
