### ISSUE TITLE
exoplayer 2.9.6 not work with androidx

### ISSUE THREAD

**Issue by FOUADFAISAL** [google/ExoPlayer#6876]
Hi ,
i have android application support androidx .
 I already tried to 
 implementation 'com.google.android.exoplayer:exoplayer:2.9.6'  
in my app , but every time get exoplayer 2.10.3 
this is problem for me because my code of exoplayer was in version 2.9.6  and i cannot upgrade code to 2.10.3 
please support me to get 2.9.6 as my request .
best regards

**Comment by andrewlewis** [comment]
> I already tried to
> implementation 'com.google.android.exoplayer:exoplayer:2.9.6'
> in my app , but every time get exoplayer 2.10.3

Are you saying that despite depending on 2.9.6 you end up getting version 2.10.3? If so: I wonder whether dependency resolution is causing the newer version to be picked up. Is there an indirect dependency on 2.10.3 from elsewhere in your project or one of its dependencies?

Regarding AndroidX support, it's a bit unclear what problem you're facing. #6804 may help, but if not please provide some more details.
