### ISSUE TITLE
change the dubbing sound of the video while playing a video

### ISSUE THREAD

**Issue by mustafaberk1996** [google/ExoPlayer#6879]
### **Description**

Hi
I have 1 video (.mp4), 2 audio files (.aac/.mp3) and 3 subtitle files (.vtt).

**What do i want ?**
**_for example, the default language of the video is English. When I change the sound the video should resume and the sound of the video dubbing should be in French. As in netflix application._**

I am trying to do this with the following code.

```
Format format_audio_en = Format.createAudioSampleFormat("en", MimeTypes.AUDIO_AAC, null, Format.NO_VALUE, Format.NO_VALUE, Format.NO_VALUE, 44100, null, null, C.SELECTION_FLAG_DEFAULT, "en");
Format format_audio_de = Format.createAudioSampleFormat("de", MimeTypes.AUDIO_AAC, null, Format.NO_VALUE, Format.NO_VALUE, Format.NO_VALUE, 44100, null, null, 0, "de");

SingleSampleMediaSource audio_source_de = new SingleSampleMediaSource.Factory(dataSourceFactory).createMediaSource(Uri.parse("http://*******/sound_de.aac"), format_audio_de, C.TIME_UNSET);
SingleSampleMediaSource audio_source_en = new SingleSampleMediaSource.Factory(dataSourceFactory).createMediaSource(Uri.parse("http://*******/sound_en.aac"), format_audio_en, C.TIME_UNSET);

MediaSource videoSource = buildMediaSource(uri, dataSourceFactory);

MediaSource[] mediaSourceList = new MediaSource[3];
mediaSourceList[0] = videoSource;
mediaSourceList[1] = audio_source_en ;
mediaSourceList[2] = audio_source_de ;
    

MergingMediaSource mergingMediaSource = new MergingMediaSource(mediaSourceList);

player.setPlayWhenReady(playWhenReady);
player.seekTo(playbackPosition);
player.prepare(mergingMediaSource, false, false);


```

But when I use it this way, I get an error.

```
E/ExoPlayerImplInternal: Internal runtime error.
    java.lang.IllegalStateException: Buffer too small (524288 < 2241155)
        at com.google.android.exoplayer2.decoder.DecoderInputBuffer.createReplacementByteBuffer(DecoderInputBuffer.java:167)
        at com.google.android.exoplayer2.decoder.DecoderInputBuffer.ensureSpaceForWrite(DecoderInputBuffer.java:117)
        at com.google.android.exoplayer2.source.SingleSampleMediaPeriod$SampleStreamImpl.readData(SingleSampleMediaPeriod.java:334)
        at com.google.android.exoplayer2.BaseRenderer.readSource(BaseRenderer.java:308)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1028)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:658)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:575)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:326)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:146)
        at android.os.HandlerThread.run(HandlerThread.java:61)
```

I do this with HLS. [Elephants Dream Hls Video](https://wowzaec2demo.streamlock.net/vod-multitrack/_definst_/smil:ElephantsDream/ElephantsDream.smil/playlist.m3u8) have two sound (english and spanish)
I can easily change the dubbing sound when I use the following code.
However, I have mp4 (video) and mp3 / aac (audio) files.
```
 trackSelector.setParameters(trackSelector.getParameters().buildUpon().setMaxVideoSizeSd()
.setPreferredTextLanguage(subTextLanguage)
.setPreferredAudioLanguage("<en or es>").build());
```
### **I looked at these**

#4600 #4698

### **How can I do what I want using mp4 (video) and mp3 (audio) files?**

I hope you can help, thanks

**Comment by ojw28** [comment]
`SingleSampleMediaSource` isn't appropriate for audio, which consists of many samples. Your code probably works if you use `ProgressiveMediaSource` instead.

I'm not sure what format your audio streams are in, but if they're raw AAC/ADTS, please note that this really isn't a suitable container format for on-demand content. Seeking probably wont work as a result, and switching track may be extremely slow. You should use a suitable container such as MP4 or MKV to resolve these issues.

**Comment by mustafaberk1996** [comment]
thanks for your answer @ojw28 

The video worked when I use ProgressiveMediaSource. I used it like this.

```
ProgressiveMediaSource progressiveMediaSource_audio_en = new ProgressiveMediaSource.Factory(dataSourceFactory, new DefaultExtractorsFactory()).createMediaSource(Uri.parse("http://******/sound_en.mp3"));
ProgressiveMediaSource progressiveMediaSource_audio_de = new ProgressiveMediaSource.Factory(dataSourceFactory, new DefaultExtractorsFactory()).createMediaSource(Uri.parse("http://******/sound_de.mp3"));

/*some codes*/

MediaSource[] mediaSourceList = new MediaSource[6];
mediaSourceList[0] = videoSource;
mediaSourceList[1] = subtitleSource_en;
mediaSourceList[2] = subtitleSource_de;
mediaSourceList[3] = subtitleSource_tr;
mediaSourceList[4] = progressiveMediaSource_audio_en;
mediaSourceList[5] = progressiveMediaSource_audio_de;
```

but **I couldn't change the dubbing sound** with the `setPreferredAudioLanguage ("<language-code>") `method.

I use the .mp3 audio format, not .aac.

sorry, but I can't use a .mkv file.

**_I want to give you an example from netflix. When we want to download a video from the Netflix application to the mobile device, the following files are saved to the mobile device;_**

filename.nfv (netflix for video)
**_filename1.nfa (netflix for audio)
filename2.nfa (netflix for audio)_**
filename.nfs (netflix for subtext)

(of course these are encrypted files)


netflix can use these files together and change the dubbing sound when playing video (of course it can also change the subtitle source).
that's exactly what I want to do. a video file, a few audio files and a few subtitle files together to change resources while playing video.

(these files may be on the server or in local memory)

[here is an image](https://support.automaticsync.com/hc/article_attachments/115009870403/iOS_Netflix_closed_captions.jpg)

which issue do you recommend to look at to solve this problem. Is there a similar example?

thank you

**Comment by ojw28** [comment]
> but I couldn't change the dubbing sound with the setPreferredAudioLanguage ("<language-code>") method.

The reason this doesn't work is that there's nothing in your audio files indicating what language they are. So, unsurprisingly, the player doesn't know which one to select.

Your audio files need to include language information. When using MP4, you can set this in the `mdhd` box. When using MKV you can set it using the `Language` element. MP3 is not really a suitable container for this use case (or for any other use case at all, except supporting playback of existing legacy files).

**Comment by mustafaberk1996** [comment]
Hello again @ojw28 

In the project I want to do, the audio files must be separate from the video file.

`(So, unsurprisingly, the player doesn't know which one to select.)`
How can I define external audio files to the player?

I tried to do this as I added subtitles. it didn't work.

Do you have a method suggestion for me?

**Comment by ojw28** [comment]
As per my previous response, modern container formats support including a language directly inside the media itself. So you should look at doing this. Note that content generation questions are not really within the scope of this issue tracker.

Once each audio file contains its language, the approach of using `ProgressiveMediaSource` already discussed above should work.

We could also think about adding a feature to let you side-load the language directly into `ProgressiveMediaSource`, which would avoid the need for you to include it directly into the files themselves. This seems a big like feature creep though.

**Comment by mustafaberk1996** [comment]
ohh! Now I looked and saw that my audio files do not have a language value.
I will try again with another audio file.

Thanks @ojw28 

I will write the result.

**Comment by mustafaberk1996** [comment]
I tried, unfortunately I couldn't succeed again

Do you have any other suggestions for this issue?

**Comment by ojw28** [comment]
What do you mean by couldn't succeed? Are you using a container format that supports specifying the language, and have you specified the language within it?

**Comment by mustafaberk1996** [comment]
`What do you mean by couldn't succeed?`
so i couldn't change the sound.

First of all, I couldn't find an audio file that contains language information.
and my existing audio files do not contain language information.

How can I do this for audio files without language information?

```
trackSelector.setParameters(trackSelector.getParameters().buildUpon().setMaxVideoSizeSd()
.setPreferredTextLanguage(subTextLanguage)
.setPreferredAudioLanguage("<en or es>").build());
```

**Comment by mustafaberk1996** [comment]
### I tried this and change sound of the video !


```
mergingMediaSource = new MergingMediaSource(soundSourceDE,videoSource);
player.setPlayWhenReady(true);
player.prepare(mergingMediaSource, false, false);
```

_when click for change the sound_

```
mergingMediaSource = new MergingMediaSource(soundSourceEN,videoSource);
player.setPlayWhenReady(true);
player.prepare(mergingMediaSource, false, false);
```

### Would you suggest me to use it?

### can a feature like this be added ?
this:

```
mergingMediaSource.removeSouce(sourceOne);
mergingMediaSource.addSouce(sourceTwo);
```
or
```
mergingMediaSource.changeSource(sourceOne,sourceTwo);
```

**Comment by ojw28** [comment]
As stated multiple times above, modern container formats support including a language directly inside the media itself. The correct solution is to do this and use `MergingMediaSource` in the normal way.

There is quite a lot of information available online about setting the language for different container formats. For example [this post](https://superuser.com/questions/1054260/how-can-i-change-the-language-metadata-with-ffmpeg-without-converting-video). I suspect this lets you add the language to an MP4 or M4A file using the following, for example:

```
ffmpeg -i in.mp4 -map 0 -c copy -metadata:s:a:1 language=spa out.mp4
```

**Comment by mustafaberk1996** [comment]
### thank you so much @ojw28 

### I got what I wanted.

First of all, I added language information to my audio files with [this program](https://mkvtoolnix.tr.uptodown.com/windows).
and then I edited the code like this;

        Uri uri_sound_en = Uri.parse("http://********/lm_sound_en.mka");
        Uri uri_sound_tr = Uri.parse("http://********/lm_sound_tr.mka");
        soundSourceTR = new ProgressiveMediaSource.Factory(new DefaultDataSourceFactory(getApplicationContext(), getPackageName())).createMediaSource(uri_sound_tr);
        soundSourceEN = new ProgressiveMediaSource.Factory(new DefaultDataSourceFactory(getApplicationContext(), getPackageName())).createMediaSource(uri_sound_en);

        Uri videoUri = Uri.parse("http://********/lm_video.mp4");
        videoSource = new ProgressiveMediaSource.Factory(new DefaultDataSourceFactory(getApplicationContext(), getPackageName())).createMediaSource(videoUri);
        mergingMediaSource = new MergingMediaSource(soundSourceEN, soundSourceTR, videoSource);
        player.prepare(mergingMediaSource, false, false);


**for english voice**

  ```
trackSelector.setParameters(trackSelector.getParameters().buildUpon()
.setPreferredAudioLanguage("eng").build());
```

**for turkish voice**

  ```
trackSelector.setParameters(trackSelector.getParameters().buildUpon()
.setPreferredAudioLanguage("tur").build());
```


_the issue can be closed, thanks_

**Comment by ojw28** [comment]
Glad you got it working!
