### ISSUE TITLE
Is it possible add replay button ?

### ISSUE THREAD

**Issue by drayan85** [google/ExoPlayer#688]
Once finish the playing the whole video instead of showing pause button, is it possible show replay button to play the same video again ?

Thank you in advance.

**Comment by ojw28** [comment]
ExoPlayer doesn't implement your application UI for you ;). UI questions are out of scope of this tracker, unless directly related to video surfaces. I suggest you post on StackOverflow.

**Comment by drayan85** [comment]
My concern was with out streaming the video again to replay by re-establishing the connection, i would like to use cache stream which i have already watched.
