### ISSUE TITLE
Why `DummySurface` is created on a separate thread?

### ISSUE THREAD

**Issue by Chuangwen-LIU** [google/ExoPlayer#6880]
Might be a dumb question: Why `DummySurface` is created on a separate thread?

I am asking this because we've been using `Codec#setOutputSurface` and the producation failure rate is really high (around 1%). And the only difference between our project and `Exoplayer` regarding how we use `Codec#setOutputSurface` is as follows.

- `Exoplayer` uses a `DummySurface` created on a separate thread.
- We use a general `Surface` created on the same thread.

Is there any theory behind this? Thank you!

**Comment by ojw28** [comment]
I think it's probably just so that the GL context it uses is created on its own thread. @andrewlewis - Can you remember?

**Comment by andrewlewis** [comment]
I think using the playback thread might work, but we'd be associating a GL context with it and I'm not sure what would happen if one were to use multiple `DummySurface`s (using a separate thread makes it more self-contained).

What are the errors you're seeing with `setOutputSurface`? Could they be related to having multiple producers outputting to the surface, or reusing a surface in an invalid way?

**Comment by Chuangwen-LIU** [comment]
@andrewlewis Thank you for your explannation. The errors are yet to report (orginally we only report exception message which is always null). And we've replaced our surface with `DummySurface`s.

**Comment by Chuangwen-LIU** [comment]
@andrewlewis Thank you for your reply again!
- From the latest reporting, the most errors we got from `setOutputSurface` is `IllegalArgumentException`. The latests error rate is around **0.8%**. [Android dev doc](https://developer.android.com/reference/android/media/MediaCodec.html#setOutputSurface(android.view.Surface)) says that the `IllegalArgumentException` is thrown if the new surface is not of a suitable type for the codec. However, the surface used to config the codec and the surface used in `setOutputSurface` are both created from `SurfaceTexture`. So they should be of the same type, right? I am confused here.

- We also found the surface could not be reused anymore when `setOutputSurface(surface)` fails, i.e. if we use the same surface to config a newly created codec (`MediaCodec.native_configure`), it always fails and throws `IllegalArgumentException`. It works if we create a new surface to config a newly created codec. Is it expected behavior?

CC @ojw28

**Comment by andrewlewis** [comment]
> From the latest reporting, the most errors we got from setOutputSurface is IllegalArgumentException.

Do you have any other information about the error? The output of logcat around the time the error was thrown, or a full bug report (`adb bugreport`) would be helpful if you can reproduce the issue. There's likely to be something more descriptive logged just before the exception.

> However, the surface used to config the codec and the surface used in setOutputSurface are both created from SurfaceTexture. So they should be of the same type, right? I am confused here.

Yeah, I think this should work. I kind of asked this before, but just to check are you certain you are synchronously detaching one surface texture before trying to use it again?

> We also found the surface could not be reused anymore when setOutputSurface(surface) fails [...]

Not sure -- it's hard to say without knowing what caused the original failure.

Stepping back, depending on your use case you may be able to have just one surface texture attached to the codec and them copy from there to a destination surface of your choice (the destination surface can change at any time). This layer of indirection is a bit wasteful in terms of memory and battery usage, but if you're using surface textures anyway that might not matter.

**Comment by Chuangwen-LIU** [comment]
@andrewlewis Thank you for replying!
> Do you have any other information about the error? The output of logcat around the time the error was thrown, or a full bug report (adb bugreport) would be helpful if you can reproduce the issue. There's likely to be something more descriptive logged just before the exception.
- From the production data, the error type is the only thing we could get. There is no error message.
- And we haven't been able to reproduce the issue yet after hundreds of trying on multiple devices.

It looks we can't root cause it for now.

 > Yeah, I think this should work. I kind of asked this before, but just to check are you certain you are synchronously detaching one surface texture before trying to use it again?

Actually we are not reusing the surface texture. Here is our detailed process:
1. Firstly we create a codec and config it with `DummySurface`. I checked the source codes of `DummySurface` and essentially it created a surface from a surface texture.
2. After hundreds of miliseconds, when the real decoder output surface is ready, we call `setOutputSurface` to reset the surface to the real decoder output surface, which is also created from a surface texture (another one, not the same as in step 1).

Thank you for your suggestion and we will consider it!

**Comment by andrewlewis** [comment]
Thanks for the information. I think there is a way forward where you keep the same `SurfaceTexture` surface attached to the decoder for its lifetime and copy from there to the output surface using OpenGL, to avoid calling `setOutputSurface`. I will close this for now as I don't think we can do much else to help, but if you can get any more information about the errors please feel free to file a new issue and reference this one.
