### ISSUE TITLE
IndexOutOfBoundsException in DashMediaSource$DashTimeline.getPeriod

### ISSUE THREAD

**Issue by sruditsky** [google/ExoPlayer#6883]
### [REQUIRED] Issue description
We experience occasional exceptions with the stack trace provided below: 
Caused by: java.lang.IndexOutOfBoundsException: index = -1; start = 0; limit = 5
at com.google.android.exoplayer2.util.Assertions.checkIndex(SourceFile:1)
at com.google.android.exoplayer2.source.dash.DashMediaSource$DashTimeline.getPeriod(SourceFile:1)
at com.google.android.exoplayer2.Timeline.getPeriodByUid(SourceFile:1)
at com.google.android.exoplayer2.MediaPeriodQueue.getMediaPeriodInfo(SourceFile:1)
at com.google.android.exoplayer2.MediaPeriodQueue.getFirstMediaPeriodInfo(SourceFile:1)
at com.google.android.exoplayer2.MediaPeriodQueue.getNextMediaPeriodInfo(SourceFile:2)
at com.google.android.exoplayer2.ExoPlayerImplInternal.maybeUpdateLoadingPeriod(SourceFile:3)
at com.google.android.exoplayer2.ExoPlayerImplInternal.updatePeriods(SourceFile:4)
at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(SourceFile:2)

### [REQUIRED] Reproduction steps
The issue is reproducible in production and we failed to reproduce in development so far.
What seems to be common to all the cases where it happened is that it happens during "player restart" sequence.
More specifically the player is playing DASH content and at some point ExoPlayer.stop() is called and then ExoPlayer.prepare() with the MediaSource created with the same MPD URI as was used before.

### [REQUIRED] Link to test content
The content which we are using is not playable in the demo app as it requires proprietary DRM mechanism.

### [REQUIRED] A full bug report captured from the device
As this happens only in production we have no way to provide this.

### [REQUIRED] Version of ExoPlayer being used
2.9.4

### [REQUIRED] Device(s) and version(s) of Android being used
Proprietary Android device. Android v8.0.0

**Comment by sruditsky** [comment]
I have more details about the scenario which is causing this exception.

The problem happens when we play a dynamic multi-period DASH content and at some point the number of periods in the MPD is getting smaller, while the period which is being played remains the same. Calling  ExoPlayer.stop(false), ExoPlayer.prepare(..., false, false) is such a state can cause the problem reported in this issue.

=======================================================

To describe this I am going to use the following abbreviations:
PC = ExoPlayerImplInternal.playbackInfo.timeline.getPeriodCount()
PID = ExoPlayerImplInternal.playbackInfo.playbackInfo.periodId.periodUid

Let's say we are playing back a dynamic multi-period DASH content and we are currently playing the second period of a two period MPD, then we have:
PC = 2, PID = 1

MPD id updated and the first period is removed, however, we still continue to play the same period as before, 
ExoPlayerImplInternal.handleSourceInfoRefreshed is called and we have:

PC = 1, PID = 1

Now if we do ExoPlayer.stop(false), ExoPlayer.prepare(..., false, false) we still have

PC = 1, PID = 1

And when doSomeWork is called (as was posted by ExoPlayer.prepare) we end up with IndexOutOfBoundsException.

**Comment by tonihei** [comment]
This looks like something that could have happened in the past when you call `ExoPlayer.prepare(..., false, false)` for the situation you describe. Basically, the player's position wasn't reset and then we tried to resolve the old position in the new manifest (and failed). [This commit ](https://github.com/google/ExoPlayer/commit/28c7cb3716c2c054d47a55a927f368058a0ed2a5)looks like it may have fixed it.

We recently changed a lot of related code to support a proper playlist API in the player and I suspect your issue will no longer occur. If the commit linked above already fixed it, you should be able to update to 2.10 or 2.11 to prevent this problem from happening.
