### ISSUE TITLE
Is Androidx required starting from Exoplayer v2.10+? 

### ISSUE THREAD

**Issue by hkim2013** [google/ExoPlayer#6884]
### Searched documentation and issues
I've seen a similiar issue raised here: https://github.com/google/ExoPlayer/issues/5870

### Question
I've recently updated from Exoplayer v2.9.0 to v2.19.0.
My application work by enabling Jetifier. 

I've checked the release notes, I was unable to find Androidx being required to use with Exoplayer v2.10.+

**Comment by ojw28** [comment]
Yes, ExoPlayer has depended on AndroidX since 2.10.0.
