### ISSUE TITLE
Avoid Video frame render before exoPlayer.setPlayWhenReady(true)

### ISSUE THREAD

**Issue by adrian-linca** [google/ExoPlayer#6886]
I'm using a SimpleExoPlayer instance to play videos with audio.
I'm playing video files from local storage.
Basic stuff, just like the Hello World setup (https://exoplayer.dev/hello-world.html)
The issue I have is that the first frame of the video is rendered before I call exoPlayer.setPlayWhenReady(true).
This, combined with audio latency, creates a small freeze on the first frame of each video when playing back to back videos.
I was able to modify MediaCodecVideoRenderer to avoid this, but my question is if there is a setting to avoid the first frame being rendered before exoPlayer.setPlayWhenReady(true) without modifying the code?
If there is no way I think this should be improved.

**Comment by andrewlewis** [comment]
You could show an opaque "shutter" view on top of the player layout until you want to show the first frame. `PlayerView` does something similar internally, but as you've noted it hides the shutter when a frame is first rendered rather than when starting playback. The frame layout returned by `PlayerView.getOverlayFrameLayout()` may be a convenient place to put your extra shutter view. Does that do what you need or are you looking for something different?

**Comment by adrian-linca** [comment]
@andrewlewis what I want to achieve is smooth transitions between videos, so an opaque view is not a solution.

**Comment by andrewlewis** [comment]
Can you use [playlists](https://exoplayer.dev/playlists.html) for that? If not please could you describe in a bit more detail what you're trying to achieve?

**Comment by adrian-linca** [comment]
I cannot use playlist or concatenated source because I only know what needs to play next after current video finishes.
I'm just trying to play back to back videos smoothly.
I don't need a workaround, for my project I modified the MediaCodecVideoRenderer and it works fine.
I just think this issue looks like something that should be improved, rendering should not start unless requested by the client.

**Comment by adrian-linca** [comment]
I initially opened this issue as a Question, I thought I was missing something.
Maybe it should be labeled as a feature request or a bug.

**Comment by andrewlewis** [comment]
Is the desired behavior to stay showing the last frame of the video that just ended while buffering the next video, then only advance to the first frame of the next video and resume when it can be played without buffering at the start?

@marcbaechinger, @tonihei I tried implementing this using a concatenation and pausing then adding a new media source after getting to the ended state. However, there isn't really an easy way to resume playback only when the next item is loaded far enough to play seamlessly, as it seems to be necessary to issue a seek to exit the ended state. Any ideas on a better way to do this?

Aside: I think a simple way to reduce the pause that might be sufficient for this use case (not using a concatenation) would be to customize load control to require a very small duration to be buffered before transitioning to the ready state (the content is local so this shouldn't be an issue).

**Comment by tonihei** [comment]
The suggestion above seems to work for me using code like that:
```
    player.addListener(new EventListener() {
      @Override
      public void onPlayerStateChanged(boolean playWhenReady, int playbackState) {
        if (playbackState == Player.STATE_ENDED) {
          player.pause();
          player.addMediaSource(/* your new MediaSource */);
          player.seekTo(player.getCurrentPosition());
        } else if (playbackState == Player.STATE_READY) {
          player.play();
        }
      }

      @Override
      public void onPositionDiscontinuity(@Player.DiscontinuityReason  int reason) {
        if (reason == Player.DISCONTINUITY_REASON_PERIOD_TRANSITION) {
          player.removeMediaItem(0);
        }
      }
    });
```

Note that seeking to `position-1` is needed because the player seems to ignore the seek to the current position even though it should change back to buffering state. Marking as bug to fix this issue.

**Comment by tonihei** [comment]
The comment above is using the new playlist APIs that will be added in 2.12. For the current release you can the equivalent with `ConcatenatingMediaSource` like that:
```
    player.addListener(new EventListener() {
      private boolean isPendingSeekToEnd;

      @Override
      public void onPlayerStateChanged(boolean playWhenReady, int playbackState) {
        if (playbackState == Player.STATE_ENDED 
            && concatenatingMediaSource.getSize() == 1) {
          player.pause();
          concatenatingMediaSource.addMediaSource(/* your new MediaSource */);
          isPendingSeekToEnd = true;
        } else if (playbackState == Player.STATE_READY) {
          player.play();
        }
      }

      @Override
      public void onTimelineChanged(
          Timeline timeline, Object manifest, @Player.TimelineChangeReason int reason) {
        if (timeline.getWindowCount() > 1 && isPendingSeekToEnd) {
          player.seekTo(player.getCurrentPosition() - 1);
          isPendingSeekToEnd = false;
        }
      }

      @Override
      public void onPositionDiscontinuity(@Player.DiscontinuityReason  int reason) {
        if (reason == Player.DISCONTINUITY_REASON_PERIOD_TRANSITION) {
          concatenatingMediaSource.removeMediaSource(0);
        }
      }
    });

**Comment by tonihei** [comment]
We pushed a fix so that you no longer have to seek to position-1 in the example above. I'll update the code snippet for future reference of how it should look like.
