### ISSUE TITLE
Looping Mp4 video seamlessly 

### ISSUE THREAD

**Issue by jopolot** [google/ExoPlayer#6889]
I am trying to loop small videos that are 15 seconds to 1:00 min long. The player is set to repeat the video that is selected. The video itself loop works fine, but the audio drops for a split second at the beginning of the loop. For example a video of waves crashing across the beach, the video loops perfectly but the audio stops and you witness a pause in the sound then it goes back fine alone with the video. Videos are in 1080p Mp4, I have been trying to find the issue here but all the posts seem to be a little different than what I am looking for, if a fix or issue has been addressed already, just point me in the right direction to read over the fix.

**Comment by jopolot** [comment]
I don't think this can be resolved due to the way MP4s are compressed. Upon reading as much research as possible on this, I don't think it can be accomplished with out using two players simultaneously or, editing player to start at a certain frame for every video, which would then cause an issue between the video part on the beginning frame and ending frame, for now I am going to use different formats that don't include using MP4 or MP3s and test my results.

**Comment by andrewlewis** [comment]
If you are authoring the streams to play, I think it should be possible to get this to work with MP4. As a starting point you could try disabling video and checking whether the audio-only playback loops gaplessly. If it doesn't then you you might need to add gapless metadata to the audio track (an edit list).

**Comment by jopolot** [comment]
No streams, these are local videos, that are being looped seamlessly like a fan for white noise, or waves on the beach. It has worked in other formats, MP4 format with audio seems to be the issue, MP4 without audio loops seamlessly fine. Thanks for the help and feedback, but since I do not think the issue is related to the player, I will close.
