### ISSUE TITLE
CryptoException: Unknown Error with DASH+PlayReady

### ISSUE THREAD

**Issue by icetronics** [google/ExoPlayer#6890]
### Issue description
In case of specific DRM-protected live DASH streams, after some seconds playback aborts with below Crypto exception.

```
com.google.android.exoplayer2.ExoPlaybackException: android.media.MediaCodec$CryptoException: Unknown Error
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1025)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:664)
```

### Reproduction steps
The exception only occurs on low-end FireTV models right after loading the stream.

### A full bug report captured from the device
<sent via email>

### Version of ExoPlayer being used:  2.9.6
(not Amazon's fork)

### Device(s) and version(s) of Android being used
FireTV Stick Generation 2 - FireOS 5.2.6.2 (Android 5.1)

Thanks for your help in advance!

**Comment by andrewlewis** [comment]
This will probably need to be investigated by Amazon. It might be worth checking whether it's reproducible using their fork before reporting it, in case they have some workaround for a known issue.

If you want us to have a look anyway, please provide a full bug report, as requested in the issue template.

**Comment by icetronics** [comment]
Hi @andrewlewis, thanks for getting back. Have you had a chance to peek at the log I sent to the dev.exoplayer email address?

**Comment by andrewlewis** [comment]
Hm, I don't think we received them. Could you try sending the bug report again? Here are the instructions for reference:

> Capture a full bug report using "adb bugreport". Output from "adb logcat" or a
> log snippet is NOT sufficient. Please attach the captured bug report as a file.
> If you don't wish to post it publicly, please submit the issue, then email the
> bug report to dev.exoplayer@gmail.com using a subject in the format
> "Issue #1234", where "#1234" should be replaced with your issue number.

**Comment by icetronics** [comment]
Sent again to given address. Please check.

**Comment by andrewlewis** [comment]
Thanks for resending. The messages went into spam for some reason.

In the provided bug report I can't see the `CryptoException` in the logging. Please could you take the bug report just after reproducing the problem?

**Comment by icetronics** [comment]
Sorry about that, now it has been corrected, I just resent it. Thank you

**Comment by icetronics** [comment]
Hi @andrewlewis - did you maybe have a chance to peek at it? Thanks

**Comment by icetronics** [comment]
@andrewlewis or @ojw28 - could you please give me any pointers what could be wrong? Thanks in advance

**Comment by ojw28** [comment]
I think @andrewlewis was right above - You'll need to ask Amazon to take a look at this. In particular, you should probably ask them what this means and why it could happen:
```
E Playready25: TZCMD_PLAYREADY_HANDLE_CONTENT_AESCTR_DECRYPT handle = 1745 Error: ffff0006
```
