### ISSUE TITLE
can we "insert" audio (eg. an ad/s) at runtime after X seconds of playback ? AdsMediaSource ?

### ISSUE THREAD

**Issue by ajonno** [google/ExoPlayer#6891]
I've checked Stackoverflow and blogs etc but havent been able to find an answer so wanted to ask for your assistance here in terms of whether the Exoplayer API can handle this use case:

Users of our app will be listening to podcasts. We need to play ads at designated intervals during playback. These intervals, will vary by user. But for example it could be the following scenario:

"ad markers" in milliseconds - [30000, 60000, 115000] 
(These ad marker "play the ad now" time points are stored in an array which we embed directly into the ID3 metadata in each MP3 file the user selects to play).

1. user starts playing "audio track 1" (MP3).
2. at 30000ms, we will pause "audio track 1", play an audio ad (MP3) for the user via a URL
3. when the ad finishes, we need to resume playback of audio from (1)
4. at 60000ms,  we will pause "audio track 1", play an audio ad, then resume playback of audio
etc...

How can we monitor the playback of "audio track 1" to know that 30000ms have elapsed, and so now its time to play the "ad" MP3. Do we need to maintain our own separate Timer in the Android app to manage this ? Or is there an API of some sort in the Exoplayer 2 API to help this use case ? 

Also, can we "insert" this ad MP3 (at runtime) into the currently playing "audio track 1" ? Or do we need to instantiate 2 x instances of Exoplayer ? (ie. one for the "audio track 1" playback and a second for the "ad" playback). Or can we / should we use AdsMediaSource  ? 

this might be what we are after, however the code snippets are minimal and without context to understand how to properly implement - https://stackoverflow.com/a/49951225/2409057

Really appreciate your assistance with this.

**Comment by ajonno** [comment]
Hi @andrewlewis, is there an eta on some docs for this?

**Comment by andrewlewis** [comment]
Sorry for the delay.

> How can we monitor the playback of "audio track 1" to know that 30000ms have elapsed, and so now its time to play the "ad" MP3.

There is indeed an API for this. Please have a look at https://github.com/google/ExoPlayer/issues/4176#issuecomment-384240744.

> (These ad marker "play the ad now" time points are stored in an array which we embed directly into the ID3 metadata in each MP3 file the user selects to play).
> Also, can we "insert" this ad MP3 (at runtime) into the currently playing "audio track 1" ? Or do we need to instantiate 2 x instances of Exoplayer ? (ie. one for the "audio track 1" playback and a second for the "ad" playback). Or can we / should we use AdsMediaSource ?

You can avoid needing to manage multiple players and track the playback position if you can make the `AdsMediaSource` option work. The main thing needed for that is a custom `AdsLoader` that receives the ID3 metadata and outputs `AdPlaybackState` updates based on the ad cue points and URLs.

One part I am not sure about is whether you will get the ID3 metadata (resulting from preparation of the content) before you have output any `AdPlaybackState` (which needs to include cue points based on the metadata) so I would check that first. I'm afraid we currently don't have good sample code or documentation around implementing `AdsLoader` but you can see `ImaAdsLoader` as a working example.

**Comment by ajonno** [comment]
we're implementing this now. 

re: 

> One part I am not sure about is whether you will get the ID3 metadata (resulting from preparation of the content) before you have output any AdPlaybackState (which needs to include cue points based on the metadata) so I would check that first.

what does this mean ? we will always (as far as im aware) get and parse out the ID3 metadata for each MP3 audio file, before it starts playing. is that what you mean ?

re: 

> You can avoid needing to manage multiple players and track the playback position if you can make the AdsMediaSource option work. The main thing needed for that is a custom AdsLoader that receives the ID3 metadata and outputs AdPlaybackState updates based on the ad cue points and URLs

so if i understand correctly, will we need to implement the AdsLoader interface on a new class that we must create -: in the same way that ```ImaAdsLoader``` does but taking into account that we are using the AdsWizz ad APIs ?

lastly - im certain that there are many devs that use AdsWizz worldwide that would benefit from some documentation on this. should i raise a separate ticket for that ?

**Comment by ajonno** [comment]
been a while, any feedback on my above questions? thanks.

**Comment by andrewlewis** [comment]
Sorry for the delay answering. Replies below.

>> One part I am not sure about is whether you will get the ID3 metadata (resulting from preparation of the content) before you have output any AdPlaybackState (which needs to include cue points based on the metadata) so I would check that first.

> what does this mean ? we will always (as far as im aware) get and parse out the ID3 metadata for each MP3 audio file, before it starts playing. is that what you mean ?

The problem is more that your custom `AdsLoader` implementation needs to know the cue points in order to produce an `AdPlaybackState`, but the cue points are only known once the content `ProgressiveMediaPeriod` has prepared to give you the format (which is where the ID3 info is available). The issue is that I don't think the content media period will be prepared until you've output the cue points (I could be wrong though). One way around this would be to extract the ID3 from the MP3 yourself but it's probably a fair amount of work.

> so if i understand correctly, will we need to implement the AdsLoader interface on a new class that we must create -: in the same way that ImaAdsLoader does but taking into account that we are using the AdsWizz ad APIs ?

Yes.

> lastly - im certain that there are many devs that use AdsWizz worldwide that would benefit from some documentation on this. should i raise a separate ticket for that ?

For any documentation that's specific to an ad network (as opposed to being generic/standardized), it probably makes more sense for the ad network to write and maintain this.
