### ISSUE TITLE
UnrecognizedInputFormatException: None of the available extractors (...) could read the stream.

### ISSUE THREAD

**Issue by ankur-93** [google/ExoPlayer#6892]
com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor, AmrExtractor, Ac4Extractor) could read the stream.

if i have 4 videos in loop then sometimes first video is skipped and jump to the second video and throws the above error. but in loop when it is again about to play then plays fine. it happens only first time but does not happen always.

i am using 2.11.1 version

**Comment by icbaker** [comment]
We need a lot more info.

Please fill in the [issue template](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md) (copy-paste it here, and fill in every section).

For this issue it sounds like we almost certainly need sample media that reproduces the problem in the demo app - either uploaded here or sent to dev.exoplayer@gmail.com with subject "Issue #6892".

**Comment by ankur-93** [comment]
```java
    private void audioVideoPlayback(final MediaFile mediaFile) {

        if (mediaFile.getFileType().equals(GlobalVar.VAR_AUDIO)) {
            viewFlipper.setDisplayedChild(viewFlipper.indexOfChild(imageViewWindow));

            MyApp.getInstance().getPicasso().load(R.drawable.org_full_logo).
                    resize(imageViewWindow.getWidth() / 3, 0).into(imageViewWindow);
        } else {
            viewFlipper.setDisplayedChild(viewFlipper.indexOfChild(mPlayerView));
        }

        mExoPlayer = ExoPlayerFactory.newSimpleInstance(getActivity());

        mPlayerView.setPlayer(mExoPlayer);

        DataSource.Factory dataSourceFactory = new DefaultDataSourceFactory(context,
                Util.getUserAgent(context, getString(R.string.app_name)));

        MediaSource mediaSource = new ProgressiveMediaSource.Factory(dataSourceFactory).
                createMediaSource(Uri.fromFile(new File(mediaFile.getFilePath())));

        mExoPlayer.addListener(new Player.EventListener() {
            @Override
            public void onTimelineChanged(Timeline timeline, Object manifest, int reason) {

            }

            @Override
            public void onTracksChanged(TrackGroupArray trackGroups, TrackSelectionArray trackSelections) {

            }

            @Override
            public void onLoadingChanged(boolean isLoading) {

            }

            @Override
            public void onPlayerStateChanged(boolean playWhenReady, int playbackState) {

                switch (playbackState) {
                
                }
            }

            @Override
            public void onRepeatModeChanged(int repeatMode) {

            }

            @Override
            public void onShuffleModeEnabledChanged(boolean shuffleModeEnabled) {

            }

            @Override
            public void onPlayerError(ExoPlaybackException error) {
               
            }

            @Override
            public void onPositionDiscontinuity(int reason) {

            }

            @Override
            public void onPlaybackParametersChanged(PlaybackParameters playbackParameters) {

            }

            @Override
            public void onSeekProcessed() {

            }
        });

        if (mediaFile.getProperties().getCurrentPosition() > 0) {
            mExoPlayer.seekTo(mediaFile.getProperties().getCurrentPosition());
        }
        mediaFile.getProperties().setCurrentPosition(0);

        mExoPlayer.prepare(mediaSource, false, true);
        mExoPlayer.setPlayWhenReady(true);
    }
```
i am using Samsung tab4 and i does not reproduce in one go. it takes many iteration to reproduce. if the file is corrupt then it should not play even a single time. So there is no problem with the file. Please find below url for the videos. In my app i first download all the files then I use exoplayer to play locally. 

https://we.tl/t-FVPdkLDnjm

Steps to reproduce:-
when i open my app, the videos start playing automatically. i just kill my app or just get out of the app by backpress, do the same many time like 20 to 25 then it may reproduce but not sure because it generate randomly.

**Comment by icbaker** [comment]
Please copy & fill in the issue template in full.

I'm unable to reproduce in the demo app on a Pixel 3A XL. I tried playing `1.mp4` & force-quitting 100 times as follows and I didn't see any errors:

```bash
$ for i in {1..100}; 
  do
    adb shell am start -a com.google.android.exoplayer.demo.action.VIEW \
        -d file:///sdcard/Download/1.mp4 && \
    sleep 2s && \
    adb shell am force-stop com.google.android.exoplayer2.demo && \
    sleep 1s; \
  done
```

If you're able to reproduce in the demo app then please attach a bug report (as requested in the issue template).

If you're unable to reproduce in the demo app, it suggests there might be something wrong with the way your app integrates with ExoPlayer. A bug report from your app may still be helpful in this case - but one from the demo app will be much better because it enables much more logging than most production apps.

**Comment by morfeo9950** [comment]
Hi, im having this same issue with the demo app, im using this link ( https://1fichier.com/?jpm7ht5bm7bn17a5yqzs ) to test the demo app in the hls section, i only add my hls test stream in the media.exolist.json, it is giving me this error and in the player shows the Playback failed message, the original vid is a .mkv and i use a free software to create the .ts files, vodobox is the freeware im using, i test my hls in an online web player from akamai website and it was working fine, slow but still working, i dont know if it is a problem with my hls or something else, thanks for any help you could provide.

**Comment by icbaker** [comment]
@morfeo9950 Can you file a new 'question' issue and we'll take a look? Please complete the template in full, including attaching a full bug report. Thanks!
