### ISSUE TITLE
Add dynamic MediaSource in Exoplayer

### ISSUE THREAD

**Issue by mrj976** [google/ExoPlayer#6898]
I want add MediaSource in MergingMediaSource
My code:
`
MediaSource mediaSource = new MergingMediaSource(mediaSource1, mediaSource2, mediaSource3, mediaSource4);
`
This worked for me But I want add mediaSource1, mediaSource2, mediaSource3, ... mediaSourceN dynamic in main mediaSource

in ConcatenatingMediaSource i want add mediasource with addMediaSource But in MergingMediaSource i can not  use addMediaSource  option

Please help me
Thanks

**Comment by icbaker** [comment]
If I've understood correctly you want to add child MediaSources to a MergingMediaSource during playback? MergingMediaSource plays all its child MediaSources back concurrently, so can you elaborate on the behaviour you expect when you add one during playback - should it immediately start being played at the same point as all the existing ones?

It might help if you could give some more concrete details of what you're trying to achieve - there may be a different way of reaching the same goal.

**Comment by mrj976** [comment]
> If I've understood correctly you want to add child MediaSources to a MergingMediaSource during playback? MergingMediaSource plays all its child MediaSources back concurrently, so can you elaborate on the behaviour you expect when you add one during playback - should it immediately start being played at the same point as all the existing ones?
> 
> It might help if you could give some more concrete details of what you're trying to achieve - there may be a different way of reaching the same goal.

Thank you 
I found my answer
Use this code:

       `
        ArrayList<Uri> mediaSource_array = new ArrayList<Uri>();
        MediaSource mediaSource = null;

        mediaSource_array.add(uri1);
        mediaSource_array.add(uri2);
        mediaSource_array.add(uri3);

        MediaSource[] mediaSources = new MediaSource[mediaSource_array.size()];
        for (int i=0; i<mediaSource_array.size(); i++){
            mediaSources[i] = buildMediaSource(mediaSource_array.get(i));
        }

        mediaSource = mediaSources.length == 1 ? mediaSources[0] : new MergingMediaSource(mediaSources);

        exoPlayer.prepare(mediaSource);
`

**Comment by icbaker** [comment]
Please can you provide the additional context I requested above in https://github.com/google/ExoPlayer/issues/6898#issuecomment-576680811.
