### ISSUE TITLE
Add or remove mediasources dynamically in Exoplayer

### ISSUE THREAD

**Issue by mrj976** [google/ExoPlayer#6900]
I want in every play Exoplayer, add or remove dynamically one or more mediaSource in this code:

`
MergingMediaSource mediaSource = new MergingMediaSource(mediaSource1, mediaSource2, mediaSource3, mediaSource4);
`
I want change it by user and play exoplayer again without exit activity and release exoplayer.

**Comment by icbaker** [comment]
This seems to be a duplicate of #6898, which you seemed to suggest was resolved so I closed it. I'll re-open that one, let's continue the discussion there.
