### ISSUE TITLE
exoplayer plays one or two songs before stopping while streaming with concatenatingMediaSource

### ISSUE THREAD

**Issue by 17martix** [google/ExoPlayer#6908]
### [REQUIRED] Question
I'd like to know how to keep my playlist going. While streaming audio content, I've managed to play a maximum of 2 audios before the player stopping as if the playlist was finished. However, when I pressed next while audio is playing I can go through the whole playlist. I can't get where's the issue in my code. Here's my code:

```java
{
  CacheDataSourceFactory cacheDataSourceFactory =
       new CacheDataSourceFactory(
           AudioDownloadUtil.getCache(context), 
           dataSourceFactory,
           new FileDataSource.Factory(),
           new CacheDataSinkFactory(
               AudioDownloadUtil.getCache(context), 
               CacheDataSink.DEFAULT_FRAGMENT_SIZE),
           0,
           null,
           new CacheKeyProvider());

  ProgressiveMediaSource[] mediaSources = new ProgressiveMediaSource[audioList.size()];

  for (int i = 0; i < mediaSources.length; i++){
    ProgressiveMediaSource mediaSource = 
        new ProgressiveMediaSource.Factory(cacheDataSourceFactory)
            .createMediaSource(Utilities.get_uri(context,audioList.get(i).getFile_name()));
    mediaSources[i]=mediaSource;
  }

  ConcatenatingMediaSource concatenatingMediaSource = 
      new ConcatenatingMediaSource(mediaSources);

  int index=audioList.indexOf(audio);
  player.prepare(concatenatingMediaSource);
  player.seekTo(index, C.TIME_UNSET);
  player.setPlayWhenReady(true);
}
```

where audio is the song I want to play first and audiolist a list of all the songs

**Comment by icbaker** [comment]
Can you please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)? I can't reproduce using the current code because I don't know what type `audioList` is, what `Utilities.get_uri` does, what `CacheKeyProvider` does etc.

You mentioned you're streaming the audio - does it work as you'd expect if the files are local to the device?

Does this still reproduce if you remove the caching logic?

**Comment by 17martix** [comment]
My bad it seems my mp3 files are carrying some extra information that is causing the player to crash since they can't be read. issue #4954 explains this in detail.
I'm looking now on how to force exoplayer to ignore the error, otherwise, I will change my audio files.
