### ISSUE TITLE
Cannot import in Gradle Release r1.4.2

### ISSUE THREAD

**Issue by spirosoik** [google/ExoPlayer#691]
In parent build.gradle, I am using build tools:
```classpath 'com.android.tools.build:gradle:1.2.3' ```

In app/build.gradle I am using this:

```compile 'com.google.android.exoplayer:exoplayer:r1.4.1' ``` and the exoplayer can't be imported into the project. Android Studio 1.3

**Comment by ojw28** [comment]
Sounds like a generic problem with your setup rather than an ExoPlayer specific bug. I'd suggest asking somewhere like StackOverflow.

**Comment by pelotasplus** [comment]
just a quick note, r1.4.2 works fine for me with AS 1.3

**Comment by spirosoik** [comment]
@pelotasplus which is your gradle config?

**Comment by adriamarti** [comment]
Hey @spirosoik , I got the same problem since I noticed that I've got 

    apply plugin: 'com.android.library'

instead of

    apply plugin: 'com.android.application'

Gl!

**Comment by spirosoik** [comment]
@adriamarti thanks for the answer I will try :)
