### ISSUE TITLE
How to download only the video with highest bitrate in adaptive format (DASH)

### ISSUE THREAD

**Issue by Cubxity** [google/ExoPlayer#6911]
### [REQUIRED] Searched documentation and issues
- I have looked at Exoplayer's developer documentation regarding downloading media

### [REQUIRED] Question
I would like to download a DASH stream however, it appears like it is downloading every format (qualities) of the stream. The video is 150 seconds long, the highest quality is 7941kbps. 

The code I've used is:
```kotlin
val defaultParams = DefaultTrackSelector.Parameters.DEFAULT_WITHOUT_CONTEXT.buildUpon()
        .setForceHighestSupportedBitrate(true)
        .build()
val helper = DownloadHelper(
                DownloadRequest.TYPE_DASH,
                uri,
                null,
                createMediaSource(ctx, media, false),
                defaultParams,
                Util.getRendererCapabilities(DefaultRenderersFactory(ctx), 
)
helper.prepare(object : DownloadHelper.Callback {
            override fun onPrepared(helper: DownloadHelper) {
                val request =
                    helper.getDownloadRequest(media.provider.id + "/" + media.id, null)
                
                DownloadService.sendAddDownload(
                    ctx,
                    MyDownloadService::class.java,
                    request,
                    false
                )
                helper.release()
            }

            override fun onPrepareError(helper: DownloadHelper, e: IOException) {
                e.printStackTrace()
            }
})
```

My app is using 296MB (user data) with only one video downloaded. It should have been around ~148MB.

Here is a screenshot of the quality selector from the downloaded video:
![image](https://user-images.githubusercontent.com/27609129/73132207-0e357a80-4018-11ea-8131-f8217e70ea64.png)

**Comment by ojw28** [comment]
I can't spot anything obviously wrong with your code. Can you reproduce it in the ExoPlayer demo app? Note that it should be pretty easy to make a minimal modification to `DownloadTracker` in the demo app to remove/skip the dialog.

If you can reproduce the problem there, could you point us to your modified clone of the demo app, so that we can take a look and reproduce it too?

**Comment by tonihei** [comment]
How did you determine that it downloaded all qualities? Your numbers suggest that it downloaded the same video twice somehow (because 296MB  = 2 x 148 MB), whereas all qualities should be around 288MB in total. Not a big difference, but just wanted to check we diagnosed the problem correctly :)

**Comment by Cubxity** [comment]
The 720p quality should be around ~75MB
The 480p quality should be around ~37MB
The 360p quality should be around ~19MB
The 240p quality should be around ~9MB
So the rest of the quality (aka. excluding 1080p) would be around 140MB

User data (296MB) - the rest (140MB) = 156MB

**Comment by ojw28** [comment]
Please try reproducing the issue with the demo app, as suggested above. Thanks!
