### ISSUE TITLE
lag in ui when call prepare

### ISSUE THREAD

**Issue by saleh-gholamian** [google/ExoPlayer#6912]
Hi, im using exoPlayer for play music in my application.
I have recently noticed that when I call prepare, it delays the performance of the thread. This looks like a very bad bug.
I've also tried to use the exoplayer in the background thread to fix this but I get the error below, apparently there is no way to use the exoplayer in the background thread.

```
SimpleExoPlayer: Player is accessed on the wrong thread. See https://exoplayer.dev/issues/player-accessed-on-wrong-thread
MessageQueue: Handler (android.os.Handler) {ed9399} sending message to a Handler on a dead thread
    java.lang.IllegalStateException: Handler (android.os.Handler) {ed9399} sending message to a Handler on a dead thread
```
If the prepare method involves heavy operations, it may be advisable to change it so as not to delay the main thread of the program. No one likes a slow program
Thanks

exoPlayer version 2.11.1

**Comment by ojw28** [comment]
> I have recently noticed that when I call prepare, it delays the performance of the thread. This looks like a very bad bug.

How have you determined that the call to `prepare` is what's causing the delay? I tried adding some timing around the `prepare` call in the demo app, and it seems to take between 2 and 3 milliseconds.

> If the prepare method involves heavy operations, it may be advisable to change it so as not to delay the main thread of the program. No one likes a slow program

The `prepare` call doesn't involve heavy operations, and it didn't seem to cause any significant delay when I added some timing as described above.

If you're convinced the `prepare` call is the problem, please could you provide more information about how you're measuring the issue, and more concrete reproduction steps?

**Comment by saleh-gholamian** [comment]
Sorry after checking out so much I realized that the problem wasn't ExoPlayer.
The problem was in the MediaCodecAudioRenderer class that I had manipulated
Thanks.


> 
> 
> > I have recently noticed that when I call prepare, it delays the performance of the thread. This looks like a very bad bug.
> 
> How have you determined that the call to `prepare` is what's causing the delay? I tried adding some timing around the `prepare` call in the demo app, and it seems to take between 2 and 3 milliseconds.
> 
> > If the prepare method involves heavy operations, it may be advisable to change it so as not to delay the main thread of the program. No one likes a slow program
> 
> The `prepare` call doesn't involve heavy operations, and it didn't seem to cause any significant delay when I added some timing as described above.
> 
> If you're convinced the `prepare` call is the problem, please could you provide more information about how you're measuring the issue, and more concrete reproduction steps?
