### ISSUE TITLE
Invoke-customs are only supported starting with Android O (--min-api 26)

### ISSUE THREAD

**Issue by zishanj** [google/ExoPlayer#6913]
Compiling with latest version 2.11.1 in Android Studio 3.5.3 gives me this error:
`Invoke-customs are only supported starting with Android O (--min-api 26)`
I have also enabled Java 1.8 but this error still occurred. I have changed the version to 2.8.4 and it works.

**Comment by ojw28** [comment]
> I have also enabled Java 1.8 but this error still occurred.

It seems pretty likely that you didn't do this correctly, given other answers to this question indicate that it's solved by enabling Java 8 (e.g. [this StackOverflow post](https://stackoverflow.com/questions/49891730/invoke-customs-are-only-supported-starting-with-android-0-min-api-26)). Our demo app targets `minSdkVersion = 16` and doesn't have this problem.

Are you certain that you enabled Java 8 in the correct place in your `build.gradle` file? Could you provide a small project somewhere that reproduces the problem?

**Comment by zishanj** [comment]
This is what I have in app build.gradle file:
```
compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
```
I am using Android Studio 3.5.3 with latest `buildToolsVersion = '29.0.2'`

**Comment by ojw28** [comment]
> This is what I have in app build.gradle file:

Where abouts? Are you sure you added it in the correct place? You'll need to share sufficient information for us to reproduce the problem (efficiently) for us to provide more guidance. A simple project that reproduces the problem is still the easiest way to do this.

**Comment by zishanj** [comment]
@ojw28 Are you sure you have thoroughly tested the lib? Here is the complete content of my build.gradle file:

```
plugins {
    id "me.tatarka.retrolambda" version "3.7.1"
}

apply plugin: 'com.android.application'

apply from: 'app-config.gradle'

def STRING = "String"

def keystorePropertiesFile = rootProject.file("keystore.properties");
def keystoreProperties = new Properties()
keystoreProperties.load(new FileInputStream(keystorePropertiesFile))

android {
    signingConfigs {
        release {
            try {
                storeFile file(keystoreProperties['storeFile'])
                storePassword keystoreProperties['storePassword']
                keyAlias keystoreProperties['keyAlias']
                keyPassword keystoreProperties['keyPassword']
            }
            catch (ex) {
                throw new InvalidUserDataException("You should define keystore properties in keystore.properties.")
            }
        }
    }

    compileSdkVersion 28
    buildToolsVersion = '29.0.2'
    defaultConfig {
        applicationId "com.test.zishanj"
        minSdkVersion 22
        targetSdkVersion 28
        versionCode 2
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        buildConfigField(STRING, "BASE_URL", base_url)
    }
    buildTypes {
        // Use different package name for non-release builds to install both debug & release apk
        // on same device
        debug {
            applicationIdSuffix '.debug'
            versionNameSuffix '-DEBUG'
        }
        release {
            signingConfig signingConfigs.release
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    // retrolambda requirement
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    testOptions {
        unitTests.returnDefaultValues = true
    }
    configurations.all {
        resolutionStrategy.force 'com.google.code.findbugs:jsr305:3.0.2'
        exclude group: 'xpp3', module: 'xpp3'
    }
    dexOptions {
        // for dagger
        additionalParameters=['--core-library']
    }
    dataBinding {
        enabled = true
    }
}

ext {
    support_version = '1.1.0'
    lifecycle_version = '2.2.0'
    room_version = '2.2.3'
    paging_version = '2.1.1'
    lombok_version = '1.18.10'
    // 2.11.1 gives error: Invoke-customs are only supported starting with Android O (--min-api 26)
    exoplayer_version = '2.11.1'
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation "androidx.appcompat:appcompat:$support_version"
    implementation "com.google.android.material:material:1.0.0"

    // ViewModel and LiveData
    implementation "androidx.lifecycle:lifecycle-viewmodel:$lifecycle_version"
    implementation "androidx.lifecycle:lifecycle-livedata:$lifecycle_version"
    implementation "androidx.lifecycle:lifecycle-viewmodel-savedstate:1.0.0"
    // Java8 compiler (does not work with min API < 24)
    //implementation "androidx.lifecycle:lifecycle-common-java8:$lifecycle_version"
    annotationProcessor "androidx.lifecycle:lifecycle-compiler:$lifecycle_version"
    // Room
    implementation "androidx.room:room-runtime:$room_version"
    annotationProcessor "androidx.room:room-compiler:$room_version"
    // optional - RxJava support for Room
    implementation "androidx.room:room-rxjava2:$room_version"
    // Paging
    implementation "androidx.paging:paging-runtime:$paging_version"
    // optional - RxJava support
    implementation "androidx.paging:paging-rxjava2:$paging_version"

    implementation "com.google.android.exoplayer:exoplayer-core:$exoplayer_version"
    implementation "com.google.android.exoplayer:exoplayer-hls:$exoplayer_version"
    implementation "com.google.android.exoplayer:exoplayer-ui:$exoplayer_version"
    implementation "com.google.android.exoplayer:extension-mediasession:$exoplayer_version"

    implementation 'com.google.firebase:firebase-analytics:17.2.2'

    implementation 'com.jakewharton.timber:timber:4.7.1'

    testImplementation 'junit:junit:4.13'
    androidTestImplementation 'androidx.test:runner:1.2.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
}
```

**Comment by ojw28** [comment]
> Are you sure you have thoroughly tested the lib?

There are thousands of applications successfully using versions of ExoPlayer more recent than the one that introduced the Java 8 requirement, that also set `minSdkVersion` lower than 26.

The part of your `build.gradle` that enables Java 8 looks fine to me, but it remains the case that this is unlikely to be an ExoPlayer issue. Is it possible you have some other module that depends on ExoPlayer as well, and that Java 8 isn't enabled in that module's `build.gradle` file? If you check out the ExoPlayer demo app, are you able to build that successfully?

**Comment by zishanj** [comment]
If I change the version to 2.8.4 then it compiles successfully. I have also commented out all the other dependencies in my gradle file but it throws error for 2.11.1.

**Comment by ojw28** [comment]
It's not the case that 2.11.1 is completely broken when targeting `minSdkVersion` lower than 26, because other developers have this working, and because it also works for our own demo app.

This means that it's not trivial for us to reproduce what you're seeing. Actual reproduction steps (i.e. providing a simple sample project that reproduces the problem) are what we need to help you with this. Re-stating the same thing and asking if we tested the library isn't going to help us to help you.

**Comment by zishanj** [comment]
I have attached the zip file [demo.zip](https://github.com/google/ExoPlayer/files/4116829/demo.zip). Here are details about the errors:

> Default interface methods are only supported starting with Android N (--min-api 24): java.lang.String com.google.android.exoplayer2.ui.PlayerNotificationManager$MediaDescriptionAdapter.getCurrentSubText(com.google.android.exoplayer2.Player)

> Invoke-customs are only supported starting with Android O (--min-api 26)

> Default interface methods are only supported starting with Android N (--min-api 24): void com.google.android.exoplayer2.Player$EventListener.onIsPlayingChanged(boolean)

> Default interface methods are only supported starting with Android N (--min-api 24): void com.google.android.exoplayer2.audio.AudioRendererEventListener.onAudioDecoderInitialized(java.lang.String, long, long)

**Comment by zishanj** [comment]
This same issue happens with v2.10.x also.

**Comment by ojw28** [comment]
The issue is something to do with your use of retrolambda. Apparently the retrolambda plugin disables desugaring in R8/D8, as per this issue:

https://github.com/evant/gradle-retrolambda/issues/272

Note that use of retrolambda also causes problems when using other libraries, for the same reason. For example:

https://github.com/JakeWharton/RxBinding/issues/490#event-2041804513
