### ISSUE TITLE
Playback freeze with tunneling enabled

### ISSUE THREAD

**Issue by danielgliga3ss** [google/ExoPlayer#6916]
### [REQUIRED] Issue description
I am getting a video freeze from time to time while playing Widevine DASH streams with tunneling enabled, the playback does not recover and it stays like this until next playback start.

Do you have any idea what can be the cause ? Usually this happens after the video track is changed (using adaptive track selection) and in the logs I get this line:
`2020-01-27 12:21:06.162 3198-9366/? W/AudioFlinger: pause because of UNDERRUN, framesReady = 0,minFrames = 1, mFormat = 0x9000000`
MediaSourceEventListener#onLoadStarted and .MediaSourceEventListener#onLoadCompleted are not called any more after this happens and the player state is STATE_READY.
 
We had no problems before, when tunneling was disabled.

###  Reproduction steps
I don't have the steps to reproduce, it just happens while you are playing a stream.
It is easier to reproduce if the internet connection is unstable.

### Link to test content
Cannot provide test content due to GeoBlocking.

### Version of ExoPlayer being used
ExoPlayer version 2.11.1

### Device(s) and version(s) of Android being used 
Technicolor STB ( customized for the project, based Sapphire)

[bugreport-uzx8020chm-PTT1.190904.001-2020-01-27-13-20-34.zip](https://github.com/google/ExoPlayer/files/4116930/bugreport-uzx8020chm-PTT1.190904.001-2020-01-27-13-20-34.zip)

Thank you,
Daniel

**Comment by ojw28** [comment]
This sounds a bit like a device specific issue with the Technicolor STB, in which case I think you're going to have to report it to Technicolor. Does it reproduce on any other devices?

**Comment by tch-Seb** [comment]
The problem seems to come from android framework audio flinger.
I suggest to close this bug.

**Comment by changxiangzhong** [comment]
Relevant to https://github.com/google/ExoPlayer/issues/5456. I think this has been fixed in the latest ExoPlayer. Checkout the comments as following, it's taken from the latest ExoPlayer. Bascially, don't call `MediaCodec` directly within the callback. Put it in another thread.
![image](https://user-images.githubusercontent.com/5352145/89398766-d53a3900-d711-11ea-98fd-d395cd401058.png)
