### ISSUE TITLE
HLS audio glitch

### ISSUE THREAD

**Issue by brianchu** [google/ExoPlayer#692]
When playing a HLS video, I observed when changing from low bitrate variant to high bitrate variant, there is an audio glitch. It repeats last half-second of previous chunk audio.

I play around with buffer sizes, ADAPTIVE_MODE (splice & abrupt) but I still can't get rid of the audio glitch, I even play around with different min max duration when switching between quality variants.

Looking at the network transmission, I see this happens always when changing from low to high bitrate variant.

My questions are:

- Are there any known issues with HLS glitch like this?

- What are the best value to tune these parameters? I do control the video at the server. I can't find it here but I remember seeing someone mentioned the size of the buffer cannot larger than the HLS chunk, is that correct?

I can email you the video link involved.

Thanks in advance.

**Comment by brianchu** [comment]
I folk the workspace and the demo links, you can find it @ https://github.com/brianchu/ExoPlayer/tree/issue692

**Comment by ojw28** [comment]
It looks like it's repeating a bit of the video as well. If this is the only video for which you're seeing a glitch, and if you don't have sample videos from another provider with similar problems, then I think it's highly likely to be an issue with the content where they've failed to properly align the timestamps in the two variants.

Closing on the assumption it's an issue with the content. Please re-open if you have solid reason to disagree or more examples. Thanks!

**Comment by brianchu** [comment]
It is not just a single video file, actually it seems to be most of them. I update the the example in github with many more example videos.

One thing I was puzzle was these files play okay in MX player and in Quicktime.

Could you reopen the issue? I can't reopen the issue.

**Comment by ojw28** [comment]
Most of which samples? Are they all from a single provider? It doesn't happen for the samples provided by default in the demo app, right?

**Comment by brian-chu-twc** [comment]
The samples are from the Weather channel. For the example with variant streams e.g. Apple master playlist advanced (the bipbop video), I can't really tell it has or hasn't the audio glitch. The Apple ID3 metadata simple doesn't have variant stream.

How can one tell if there is an overlap (audio or video glitch) other than playing the video? Can we tell from the codes inside HlsChunkSource?

**Comment by ojw28** [comment]
We have quite a lot of test streams from partners (we can't share them externally) and we don't see this issue in general, so it's likely the case that the Weather channel are producing slightly misaligned streams

**Comment by ojw28** [comment]
I stumbled across a fix for this whilst investigating another issue. The segments are slightly misaligned (i.e. different qualities are being segmented at slightly different offsets), but the underlying presentation timestamps within the media are aligned correctly. We should be using those to achieve proper sync across format switches.

**Comment by ojw28** [comment]
This should be fixed by the change above. Please verify.
