### ISSUE TITLE
Can we integrate an exoplayer based custom player with TVIF

### ISSUE THREAD

**Issue by krackjack234** [google/ExoPlayer#6921]
### [REQUIRED] Can we integrate an exoplayer based custom player with TVIF for Android TV?

We want to integrate an exoplayer based custom player with TV input framework.
Our understanding is TVIF uses the exoplayer interfaces directly and we cannot customize it. Kindly confirm if this understanding is correct.

1. Is there anyway we can use TVIF and integrate a custom player?
2. If yes, can we integrate a player fragment instead of calling the player sdk directly?

Any pointers will be helpful

Thanks in advance!

**Comment by phhusson** [comment]
This question isn't related to Exoplayer.

There is no connection between TVIF and ExoPlayer, except that the examples of androidtv-sample-inputs are using ExoPlayer, and the usb tuner support is loosely based on exoplayer.

I recommend you look at:
- https://developer.android.com/training/tv/tif/tvinput
- https://developer.android.com/reference/android/media/tv/TvInputService
- https://developer.android.com/reference/android/media/tv/TvInputService.Session.html

Plugging your own player (be it based on ExoPlayer, or whatever else) in those interfaces is pretty straightforward, you should try it from scratch at least once to understand how to interact with it.
