### ISSUE TITLE
HLS Buffering on Discontinuity

### ISSUE THREAD

**Issue by vincentthai22** [google/ExoPlayer#6924]
**Issue description**

I have HLS streams I am trying to play using ExoPlayer. The player initializes and plays audio. Once the first discontinuity tag is hit the player buffers indefinitely and eventually recovers. Upon recovering the following discontinuity tags that are hit no longer cause buffering.

**Reproduction steps**

Load up the linked test content into instance of SimpleExoplayer as HlsMediaSource.

**Link to test content**

https://api-stg.radio.com/streaming/stream/1532/manifest/digitalstations/playlist.m3u8?udid=c32b2112-aa36-4b96-aad4-5c5b196486d9

**Version of ExoPlayer being used**

ExoPlayer 2.11.1

**Device(s) and version(s) of Android being used**

Pixel 2, Android 9 (28)

**Errors and log output**

No exception or error is thrown. Following the logger's output the player simply stalls between the following logs:

2020-01-28 12:08:40.681 5441-5441/com.radiocom.staging E/EventLogger: audioTrackUnderrun [eventTime=278.36, mediaPos=231.43, window=0, period=0, 22050, 250, 13424]]
2020-01-28 12:08:40.682 5441-6494/com.radiocom.staging E/AudioTrack: Discontinuity detected [expected 61234103, got 29675100]

**Comment by ojw28** [comment]
I couldn't reproduce the exact issue, but the updates this HLS stream makes to its media playlists are invalid.

In subsequent requests for the media playlist during playback, old segments are removed and new segments are added. This is expected for a live stream. However other tags in the media playlist are not being correctly updated. For example the `EXT-X-PROGRAM-DATE-TIME` tag that applies to the first segment is not being correctly updated when segments are removed. This causes a problem even before a discontinuity is encountered, where the playback position in the demo app appears to be larger than the duration of the stream.

I would suggest fixing the HLS stream to perform valid media playlist updates, and see whether that resolves the problem.

**Comment by ddproxy** [comment]
This shouldn't be causing an issue per 6.3.3 of the HLS draft.

>   The client MUST NOT depend upon the correctness or the consistency of the value of the EXT-X-PROGRAM-DATE-TIME tag.


https://tools.ietf.org/html/draft-pantos-http-live-streaming-13#section-6.3.3

**Comment by ojw28** [comment]
If the date can be wrong then its existence isn't really useful. I've no idea how that statement ended up in the specification really. The statement was also removed in https://tools.ietf.org/html/draft-pantos-http-live-streaming-19.

**Comment by ddproxy** [comment]
Too many drafts - would really like to see an example of the X-PROGRAM-DATE-TIME being used in a stream so we implement it correctly.

**Comment by ojw28** [comment]
What's the confusion, our of interest? The spec seems fairly clear to me:

> The EXT-X-PROGRAM-DATE-TIME tag associates the first sample of a Media Segment with an absolute date and/or time.  It applies only to the next Media Segment.

Normally it's at the top of the media playlist, as it is in your stream. But it should be the time that corresponds to the first media segment in the media playlist, so as segments are removed it should be getting larger.

**Comment by ddproxy** [comment]
So it's supposed to be updated each time we remove a segment from the playlist?

**Comment by ojw28** [comment]
As per the quote above, it's the absolute date and/or time of the first sample of the next media segment. So if you have it at the top of the media playlist, it's the absolute date and/or time of the first sample of the first media segment in the playlist. Hence if you remove a media segment from the start of the playlist, you need to update the `EXT-X-PROGRAM-DATE-TIME` value to be correct for the segment that's now the first one in the playlist.

**Comment by ojw28** [comment]
By the way, I don't know if it covers this particular case, but Apple provide a validation tool that you can use to test the correctness of your streams ([see here](https://developer.apple.com/documentation/http_live_streaming/about_apple_s_http_live_streaming_tools)).

**Comment by ddproxy** [comment]
It can and does, but examples help first, linting second, and that tool helps with functional spec - it's just not always clear what's not working properly, unfortunately.

**Comment by ddproxy** [comment]
When we have a discontinuity tag, do we need to have an additional EXT-X-PROGRAM-DATE-TIME for that segment? I'm finding conflicting information.

**Comment by ojw28** [comment]
Assuming the stream corresponds to a contiguous period of time and the discontinuity tags are to handle a change in source (e.g. due to ad insertion) then I don't think you need an additional `EXT-X-PROGRAM-DATE-TIME` after the discontinuity tag.

**Comment by ddproxy** [comment]
That's my hopes and dreams - would be pretty difficult to keep track of that ALL the time.
