### ISSUE TITLE
Playback freeze when 'startNumber' property in 'SegmentTemplate' reset to zero. (Live Dash)

### ISSUE THREAD

**Issue by hyeonsu94** [google/ExoPlayer#6925]
I have a problem where playback freeze when I play a live-dash stream using exoplayer.

Playback freeze occurs when the 'startNumber' property of MPD's 'SegmentTemplate' is initialized.

The MPD during normal playback is as follows.
[before.mpd.txt](https://github.com/google/ExoPlayer/files/4121535/before.mpd.txt)

The MPD after the 'startNumber' property is initialized is as follows.
[after.mpd.txt](https://github.com/google/ExoPlayer/files/4121579/after.mpd.txt)

**Comment by ojw28** [comment]
Please properly fill in the issue template; there's not enough information here for us to help.

In addition, what does it mean to "initialize" the "startNumber"? It looks to me like you've either linked the two manifests the wrong way round, or a manifest update has "gone backward", which I don't think is a valid manifest transformation.
