### ISSUE TITLE
Clear exo player notification when app stops from recent apps in android studio

### ISSUE THREAD

**Issue by StefanosIliadis** [google/ExoPlayer#6929]
I am developing an app for radio streaming using exoplayer library. So, I want to clear(delete) exoplayer notification bar (with play/stop buttons) when I close the app. Now, I close the app but the notification bar still appears and doesn/t close with swipe left/right.

I try the following source code but it doesn't work.

```
protected void onDestroy() {
        super.onDestroy();
        NotificationManager notificationManager = (NotificationManager) getApplicationContext().getSystemService(Context.NOTIFICATION_SERVICE);
        notificationManager.cancel(NOTIFICATION_ID); }
```

I tried it with method cancelAll() , notificationManager.setPlayer(null); etc but it does'n work too.

It works on onpause() and onstop() methods but I want to do this onDestroy() only.

Thanks in advance.

**Comment by ojw28** [comment]
If you're supporting background playback then you should be using the notification for your foreground `Service`. I think that's probably sufficient to cause the notification to be removed in this case, so I suspect that you'er not currently doing this. Do you have a foreground `Service` to start with?

**Comment by marcbaechinger** [comment]
The app probably is using a foreground service already and that's the reason why the notification can't be removed before [stopForeground](https://developer.android.com/reference/android/app/Service.html#stopForeground(boolean)) is called.

If this is true, the following would do the trick:

```
service.stopForeground(/* removeNotification= */ true);
```

**Comment by StefanosIliadis** [comment]
Hello,

I have created a new Service like:

```
public class EsrService extends Service {
......
.......
......
public void onTaskRemoved(Intent rootIntent) {
        NotificationManager mNotificationManager = (NotificationManager) getSystemService(Context.NOTIFICATION_SERVICE);
        mNotificationManager.cancel(NOTIFICATION_ID);
        stopForeground(true);
        notificationManager.cancelAll();

    }

    public void onDestroy() {
        super.onDestroy();
        stopForeground(true);
        NotificationManager mNotificationManager = (NotificationManager) getSystemService(Context.NOTIFICATION_SERVICE);
        mNotificationManager.cancel(NOTIFICATION_ID);
      
    }
}
```
I declared it in AndroidManifest.xml too.

So, when I close app from taskmanager it continues to display notification bar (and I can't close it with swipe left/right).
Any syggestion please?

**Comment by ojw28** [comment]
I think we need more information to help with this. Perhaps you could share a minimal project that we could open in Android Studio to see exactly how you're implementing this.
