### ISSUE TITLE
HLS - Select correct audio stream when multiple embedded streams exist

### ISSUE THREAD

**Issue by SnowcatSVK** [google/ExoPlayer#693]
Hello,
I want to use exoplayer for streaming HLS, som streams play fine, but I can't play some of them at all,
I have found out it is problem with audio, .ts file looks like this:
Stream 0: Video, codec h264-mpeg-avc
Stream 1: Audio, codec MPEG AAC Audio(mp4a)
Stream 2: Audio, codec MPEG Audio layer 1/2(mpga)

On some devices app crashes completely(eg. genymotion emulator) with : 
    
    Unsupported mime audio/mpeg-L2 

, on some app works but stream doesn't play and I see this: 

    com.google.android.exoplayer.ExoPlaybackException:com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: [-49999], MediaFormat(audio/mpeg-L2, 4096, -1, -1, -1.0, 2, 48000, -1, -1, -1) 

in logcat, this  happened when i tested my app on on PAP5450 duo with mediatek chip and also on Nexus 7 with Snapdragon S4, on One+ One stream plays, but it lags and audio is slowed down, i guess it is some kind of problem with mpeg audio codek, is there any chance I can resolve it by myself, I am pretty noobish when it comes to video encoding. I can provide link to stream if needed for testing. Stream plays perfectly with usage of libVLC and basic MediaPlayer.

**Comment by SnowcatSVK** [comment]
Ok, after playing around in logcat I have found out that player ignores mp4a audio and tries to play mpga, is there a posibility to force player to play mp4a even if there is mpga?

**Comment by ojw28** [comment]
We should be filtering out the unsupported stream, yes. Please could you provide a link to some sample media?

**Comment by SnowcatSVK** [comment]
http://88.212.15.22/live/doma_1200/playlist.m3u8 here is a link, stream is ON 24/7, thank you very much for answering

**Comment by ojw28** [comment]
I think this is fixed. Please could you let us know if not.

**Comment by SnowcatSVK** [comment]
Can confirm that this issue is fixed
