### ISSUE TITLE
How to get to know when user clicks any of the play back controls which is managerd by playerControlView?

### ISSUE THREAD

**Issue by ajay-aravind** [google/ExoPlayer#6933]
I want to report events to when user clicked on any of the playback controls. I am using Player Control view managed by exo player for all playback functionalities. I am not sure how to get a callback when user clicked on any playback control?

**Comment by ojw28** [comment]
Depending on what you're trying to do, you could try setting a `ControlDispatcher` via `PlayerView.setControlDispatcher`. The methods of this component are called whenever an operation is performed on the player as a result of a UI interaction. Note that if you do set a `ControlDispatcher`, then it's also responsible for actually performing the operations. Hence your implementation should probably report what you want to report, and then call through to an instance of the `DefaultControlDispatcher` implementation.

If the suggestion above doesn't give you the granularity you need, and you really do want to report events for every click and know the specific control that was clicked, then this is not something supported by the library. You'd probably need to fork the UI components and use them as the starting point for your own custom implementation if you this functionality is important to you.

**Comment by ajay-aravind** [comment]
so, there is no way from the library to know if the play/forward/backward is clicked?

**Comment by ojw28** [comment]
No; this is not something we support out of the box.

**Comment by tonihei** [comment]
Not sure if you aware, but you get events for all these user interactions by adding an `EventListener` to the `Player`. This should already cover most of the required events:
```
player.addEventListener(new Player.EventListener() {
  boolean previousPlayWhenReady = false;
  int previousWindowIndex = 0;

  @Override
  public void onPlayerStateChanged(boolean playWhenReady, int state) {
    if (previousPlayWhenReady == false && playWhenReady == true) {  
      // Play clicked.
    }
    else if (previousPlayWhenReady == true && playWhenReady == false) {
      // Pause clicked.
    }
    previousPlayWhenReady = playWhenReady;
  }
 
  @Override
  public void onPositionDiscontinuity(@Player.DiscontinuityReason int reason) {
    if (reason == DISCONTINUITY_REASON_SEEK
        && previousWindowIndex + 1 == player.getCurrentWindowIndex()) {
      // Next clicked.
    }
    if (reason == DISCONTINUITY_REASON_SEEK
        && previousWindowIndex - 1 == player.getCurrentWindowIndex()) {
      // Previous clicked.
    }
    previousWindowIndex = player.getCurrrentWindowIndex();
  }

  @Override
  public void onTimelineChanged(Timeline timeline, int reason) {
    previousWindowIndex = player.getCurrrentWindowIndex();
  }
});
```

The only potential problem is that the same events are triggered if you call `player.setPlayWhenReady(...)`, `player.next()` or `player.previous()` in code without UI interaction.
