### ISSUE TITLE
Requesting Media Source

### ISSUE THREAD

**Issue by LowLevelSubmarine** [google/ExoPlayer#6935]
### [REQUIRED] Use case description
Months ago I tried to implement a MediaSource that takes two inputs: A primary queue, and a secondary list of tracks. The Media Source provides the tracks by the queue first and removes them after they have been played, and provides the tracks from the secondary list when the queue is empty.

### Proposed solution
I'd like to have a simpler option for creating custom concatinating MediaSources. Like, wouln't it be possible that you guys create a interface with methods like getNextMediaSource(MediaSource) and getFutureMediaSources(Collection<MediaSource>). The first one beeing used when the Player requests a new Track and the second one providing a collection of tracks the player can cache before playback.

### Alternatives considered
I tried to implement MediaSource to create my custom "Queue", but if i'm beeing honest, i didn't really understand neither the methods nor the documentation, it was just to much. So i used a ConcatinatingMediaSource and stored a marker seperately where my primary queue ends and the secondary track list starts. But, turns out, that way magically attracts bugs, and is incredibly hard to debug :/

**Comment by ojw28** [comment]
I'm a bit unclear what your use case is. Is it equivalent to having a single queue, where you want the first N items in the queue to be removed after they've been played? I'm guessing one use case would be pre-roll ads where you want them to be played only once?

**Comment by LowLevelSubmarine** [comment]
In my implementation, it should work like Spotifys system. (And prob other music apps). So that you have a base playlist that you play and a queue to which you can add the tracks that should be played before continuing with the base playlist. But the solution i proposed should work for more than my use case.

**Comment by ojw28** [comment]
I don't think I've ever seen this system (despite using Spotify)!? That aside, I'm somewhat unsure why you can't use a regular `ConcatenatingMediaSource` for this, given that it supports adding and removing children.

**Comment by LowLevelSubmarine** [comment]
I've probably explained it bad. When you select a playlist in spotify the following tracks in the playlist will be played automatically. But if you want to play a track after the current track, you can use "add To Queue" in the tracks submenue and it will be played right after the current one.

**Comment by ojw28** [comment]
Ah. Why can't you do this by adding and removing to a regular `ConcatenatingMediaSource`?

**Comment by LowLevelSubmarine** [comment]
The problem was, that you cant really tell where the tracks from the queue end and the tracks from the playlist start. I need to know this position to add a track right after the last one from the queue. I tried saving this position in an seperate int, but i had problems updating it.

Forget what I said. Just imagine having two concatMS in one concatMS. Lets name the first one the queue and the second one the playlist. Now, if the playhead moves on from the queue to the playlist, there is no way of adding tracks to the queue and playing them. I guess, that you could skip back to the queue, but after that track has played, the playback will not continue at the position where it was before the skip back to the queue but at the start of the playlist.

It is really hard to explain. But you can trust me, that I tried to implement such a systems for months now. A system like i've written in the proposed solution would help a lot.

**Comment by ojw28** [comment]
> The problem was, that you cant really tell where the tracks from the queue end and the tracks from the playlist start.

I don't understand why this is the case. Your application code is responsible for adding and removing all items from the `ConcatenatingMediaSource`. It should be fairly straightforward for you to keep track of this offset in application code as you do this.

**Comment by LowLevelSubmarine** [comment]
U gave me trust in redoing my my queue system in a seperated class. Although I do think, a solution as i proposed would make things a lot easier. Could you close this issue for now if u don't see a chance for such a feature?

It's just that u guys have a better understanding of that whole MediaSource system and could prob. add such a feature in minutes.

**Comment by ojw28** [comment]
> It's just that u guys have a better understanding of that whole MediaSource system and could prob. add such a feature in minutes.

I think it's actually easier for an application to implement this directly using the existing `ConcatenatingMediaSource` API, than it is to write a custom `MediaSource` component. It's also more flexible and generalizes better to other variations of queuing that applications might want to implement.
