### ISSUE TITLE
Exo player single download pause

### ISSUE THREAD

**Issue by harika1511** [google/ExoPlayer#6937]
Hi,
 Is it possible to pause or resume a single download with Exo player download service and track it's progress once it resumes.
If yes, can you please show an example of how to do this

**Comment by ojw28** [comment]
Please take a look at the [documentation](https://exoplayer.dev/downloading-media.html#starting-and-stopping-downloads).

**Comment by harika1511** [comment]
But in the documentation I see a way to only pause all the downloads and not a single one..or is my understanding wrong, if so please correct me

**Comment by ojw28** [comment]
The section describes how to set stop reasons on individual downloads...

**Comment by harika1511** [comment]
But does setting stop reason cancel or pause the download ??and can we resume the download from the point it was stopped by clearing the stop reason

**Comment by ojw28** [comment]
It has the same effect as pausing it. Clearing the stop reason will cause the download to resume (else there would be no point supporting the ability to clear a stop reason).

**Comment by ojw28** [comment]
Documentation has been improved internally, and these improvements will be pushed to the [public documentation](https://exoplayer.dev/downloading-media.html#starting-and-stopping-downloads) in due course.
