### ISSUE TITLE
How to stream single URL content into two surfaces?It should be sync in both.

### ISSUE THREAD

**Issue by iamradhakrishna** [google/ExoPlayer#6939]
Requirement:
Play same video content(one URL) into multiple or two surfaces using single Exo  player instance.
Both the surfaces should sync in video playing.
How can i achieve using exo player?Is there any limitations on this?

It is very similar to switching surfaces but here rendering into multiple surfaces the same content.
Please advice on feasibility or performance side effects.
Kindly suggest on this.

Regards,
RK

**Comment by ojw28** [comment]
This is quite difficult to achieve because a `MediaCodec` instance is tied to a single `Surface`. If I remember correctly, the solution is to render it to a texture, which you can then render to multiple places, but it's quite complicated to get this right.
