### ISSUE TITLE
Notification not removed on playerNotificationManager.setPlayer(null)

### ISSUE THREAD

**Issue by Miteshmakwana73** [google/ExoPlayer#6944]
I am trying to remove PlayerNotificationManager notification on activity destroy but it's not removing notification after app killed

```
private fun killPlayer() {
         playerNotificationManager.setPlayer(null)
        if (exoPlayer != null) {
            exoPlayer.release()
            mediaSource = null
        }
    }
```

can anyone suggest me why notification is not removed programmatically

**Comment by AquilesCanta** [comment]
@marcbaechinger, mind taking a look?

**Comment by marcbaechinger** [comment]
When looking at the code, calling `setPlayer(/* player= */ null)` results in calling `notificationManager.cancel(notificationId)` in case there was a) a non-null player set and b) a notification has already been started. So I'm pretty sure that works as expected.

In case you are running the player in a foreground service, and you've called `startForeground(notificationId, notification)`, the notification would not be removed by the system until you have called `stopForeground(/* removeNotification= */ true || false)`.

May I ask you to check whether this is the case for you? I change the type of this issue to 'question'. I'll put it back to 'bug' in case we can rule out the foreground service reason. LMK.

**Comment by Miteshmakwana73** [comment]
I am using this code to show notification in main activity

```
playerNotificationManager = PlayerNotificationManager.createWithNotificationChannel(
            this,"channel_id",R.string.channelName,R.string.channelDescription,11,
            object : PlayerNotificationManager.MediaDescriptionAdapter{
                override fun createCurrentContentIntent(player: Player): PendingIntent? {
                    val intent = Intent(this@MainActivity, MainActivity::class.java)
                    return PendingIntent.getActivity(this@MainActivity,0,intent, PendingIntent.FLAG_UPDATE_CURRENT)
                }

                override fun getCurrentContentText(player: Player): String? {
                    return mSongList[player.currentWindowIndex].descripation // descrption
                }

                override fun getCurrentContentTitle(player: Player): String {
                    return mSongList[player.currentWindowIndex].name // title
                }

                override fun getCurrentLargeIcon(
                    player: Player,
                    callback: PlayerNotificationManager.BitmapCallback
                ): Bitmap? {
                    return this@MainActivity.getBitmap(R.drawable.bg)
                }

            } ,null
        )

        playerNotificationManager.setUseStopAction(false)  //stop song
        playerNotificationManager.setRewindIncrementMs(0)   //hide rewind button
        playerNotificationManager.setFastForwardIncrementMs(0)  //hide fast forward button
        playerNotificationManager.setPlayer(exoPlayer)
```

I am not using any foreground service to show notification

**Comment by marcbaechinger** [comment]
When you are saying that you are trying to remove the notification from onDestroy with the snippet above then you are sure that onDestroy has been called? Like in you have set a break point there or a log statement telling you that `playerNotificationManager.setPlayer(null)` actually has been executed?

If this is the case I wonder what's the problem too. I just checked in a sample and calling 

notificationManager.setPlayer(null);

properly removes the notification for me as expected. If the notification is not attached to a service, it's unclear to me what could be the problem.

May I ask you to check whether that code in onDestroy() really is executed?

**Comment by Miteshmakwana73** [comment]
you are right I just checked onDestroy is not called in my app. but if I press back then onDestroy is calling and notification removing successfully

so is there any other way? to perform my task

**Comment by marcbaechinger** [comment]
Glad it's working!

I think you should do that right before you release the player, which is either in `onPause` or in `onStop` depending on the API level. The [PlayerActivity](https://github.com/google/ExoPlayer/blob/release-v2/demos/main/src/main/java/com/google/android/exoplayer2/demo/PlayerActivity.java#L253) of the demo app shows, how initialisation and releasing of the player is properly integrated into the life-cycle of an activity. 

I close this issue, please reopen if you think it's required.

**Comment by Miteshmakwana73** [comment]
@marcbaechinger thank you for your response but I am developing  audio streaming app so notification would stay until app close

onStop doesn't help me

should I have to create background service just to destroy notification? or is there any other better option available cause I don't know much about Service

**Comment by marcbaechinger** [comment]
For the current case of playing within an activity, you should remove the notification at the moment, when you release the player. 

In case that the app is put into background you need to release the player in `onPause/onStop` just like the demo app is doing it.

As a general advice I'd recommend doing a [foreground service](https://developer.android.com/guide/components/services#Foreground) for audio playback. This way your users can continue listening to the audio even when the app is put into background by the user.

**Comment by Miteshmakwana73** [comment]
okay, I created a foreground service successfully. I followed this session [Building feature-rich media apps with ExoPlayer (Google I/O '18)](https://www.youtube.com/watch?v=svdq1BWl4r8) but I don't get how do I update my MainActivity player UI on song change and update seek bar?
how do I pass Songlist to service?

**Comment by marcbaechinger** [comment]
You can pass the player to the activity from the service. You can use a `ResultReceiver` when you start the service by intent. Or you can simply have a static `player` field on the service.

Once you have the player you can add listeners like before. Make sure to unregister all listeners when the activity is destroyed or goes to background.

**Comment by Miteshmakwana73** [comment]
thanks, @marcbaechinger I'll try and let you know

**Comment by MAKFneish** [comment]
Just move the `super.onDestroy()` to the end of the `onDestroy()` function:

```
@Override
    protected void onDestroy() {
        try {
            playerNotificationManager.setPlayer(null);
            player.release();
            player = null;
        } catch (Exception e) {
            e.printStackTrace();
        }
        super.onDestroy();
    }
```
