### ISSUE TITLE
CEA608 Closed Caption repeating twice 

### ISSUE THREAD

**Issue by juechemparathy** [google/ExoPlayer#6948]
CEA608 Closed Caption characters are repeating twice.
@tonihei - Not sure if this is a side effect of changes made with  #6133. 
I will send the test video information to dev.exoplayer@gmail.com

**Comment by AquilesCanta** [comment]
@tonihei, is it possible that #6133 is related? Feel free to reassign to me if not.

**Comment by tonihei** [comment]
The provided test stream doesn't work for me and just returns a 404.

In addition it would be helpful to get some more information:
- Which ExoPlayer version are you using? Especially, does it already include the fixes for #6133?
- Which captions do you expect to see and which captions are shown by ExoPlayer?
- And at which time in the stream do I fine the problematic captions?
