### ISSUE TITLE
Seamless playing with ConcatenatingMediaSource

### ISSUE THREAD

**Issue by skogl** [google/ExoPlayer#6953]
### [REQUIRED] Searched documentation and issues
#4510 - Noticalbe gaps between h264 video file playback
#3526 - Gap between videos when playing fragmented mp4 files in ConcatenatingMediaSource

### [REQUIRED] Question
Using ConcatenatingMediasource, is it possible to get seamless/gapless playback using multiple mpegts files?
If I use the mp4 files from here: [sample_videos.zip](https://github.com/google/ExoPlayer/files/2191889/sample_videos.zip)  (same as in #4510) it plays seamless, but if I take two mpegts files I get a small delay/gap between the two files. Also, if I concatenate the two mpegts files into one it is also playing seamless.
I'm guessing it's related to mpegts keyframes but I just want to make sure before trying a different solution.

**Comment by AquilesCanta** [comment]
For seamless gapless transitions to work, the container needs to include special metadata which Transport Stream does not support (MP4 does). There are also other crucial factors, like format changes across streams.  

**How are you concatenating the TS files?**

If you are concatenating the files manually by appending the bytes, then you should provide the sample media for us to take a look (both separate and concatenated). If you are using ffmpeg or another tool, it's possible that you are accidentally re-encoding the contents to have the same format across all samples.

**Comment by skogl** [comment]
I'm manually appending the bytes.

[files.zip](https://github.com/google/ExoPlayer/files/4185779/files.zip)

**Comment by AquilesCanta** [comment]
@tonihei will be able to provide more insight on ConcatenatingMediaSource, surely.

**Comment by tonihei** [comment]
The two files play "gapless" for me. That is, the audio is perfectly continuous and no decoder changes happen between playing both parts.

There seems to be an issue with the timestamps in ts files themselves. The video samples in all 3 files starts with an offset of 1.902 seconds, meaning the first frame is always frozen for almost 2 seconds. For the concatenated file, this only happens at the beginning, and for the playlist of two parts this happens for each file separately and I can see a frozen frame for about 2 seconds at the transition.

**Comment by skogl** [comment]
When you say they play "gapless". You mean you create a ConcatenatingMediaSource, add "part1.ts" and "part2.ts" to it and when you play it it's as gapless as when you play "concatenated.ts"?

When I add the both files to a ConcatenatingMediaSource I get a small delay (~0.5s) between the two parts.

**Comment by tonihei** [comment]
Which ExoPlayer version are you using?

**Comment by skogl** [comment]
2.11.0

**Comment by tonihei** [comment]
I tried the same again with a ConcatenatingMediaSource on 2.11.0 without any modifications and the audio is still gapless and the video still has the same wrong time offset as described above.

**Comment by skogl** [comment]
Ok, I have the same results. I just wanted it confirmed that you cannot play any two splitted mpeg-ts files gapless using ConcatenatingMediaSource without using some kind of special keyframe handling.

Since exoplayer support gapless playing of adaptive streams, even with bitrate changes, I was hoping that ConcatenatingMediaSource was using the same mechanism. Obviously hls streaming uses some other handling that enables this.

**Comment by tonihei** [comment]
Closing, because I think all questions have been answered. Feel free to reopen if not.
