### ISSUE TITLE
AudioSessionId=0 always. The problem with getting an audio session.

### ISSUE THREAD

**Issue by master255** [google/ExoPlayer#6954]
I have problem on the 2.11.1 release right now.
Sometimes, when switching different files, with different codecs, with codec cache enabled, onAudioSessionId events do not work at all! At this time mMediaPlayer.getAudioSessionId() produces 0.
Most often it happens when you switch from 4k movie to mp3 track.
Music is playing, but no audio session and no onAudioSessionId events.
Fix it, please.
What details are you interested in?

**Comment by master255** [comment]
mMediaPlayer.setForegroundMode(false);
Temporarily helped. Can we make the audio session work properly with the codec cache enabled?

**Comment by master255** [comment]
I don't know if it's right anymore.
That's what the player start function looks like to me:
```
private void openVideo(boolean hls, String extension) {
        if (path == null) return;
        try {
            initPlayer();
            duration = 0;
            notifiedPrepared = false; //These are two variables for calculating where onPrepare will work.
            notifySessionId = false;
            mSeekWhenPrepared = 0;
            mOldCurrentState = 0;
            if (path.toLowerCase().startsWith("http") && Uri.decode(path).equals(path)) //To support all languages
                path = Uri.encode(path, Constants.ALLOW_STR);
            if (extension != null && extension.equals(lastExt))
                mMediaPlayer.setForegroundMode(true); //Is this how it's supposed to work? Surviving as much as I can.
            else
                mMediaPlayer.setForegroundMode(false);
            lastExt = extension;
            if (hls)  //We calculate HLS or not. The player can't do it on its own.
                mMediaPlayer.prepare(hlsSource.createMediaSource(Uri.parse(path)));
            else
                mMediaPlayer.prepare(progressiveSource.createMediaSource(Uri.parse(path)));
            mCurrentState = STATE_PREPARING;
        } catch (Exception e) {
            mCurrentState = STATE_ERROR;
            mErrorListener.onError(e);
        }
    }
```
Why is my code not formatted I don't know. It's Githab bug.
Google saves a lot of money on programmers.

**Comment by kim-vde** [comment]
What is the type of mMediaPlayer? Did it work with a previous version of ExoPlayer? Could you please provide steps to reproduce the issue, together with the test contents, as described [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md)?

**Comment by master255** [comment]
Thank you for the answer. This bug is available if you call stop after a track with mMediaPlayer.setForegroundMode(true);
It took me a long time to figure out what was going on, but then I found an instruction in the depths of the code explaining that I don't need to call a stop in this case.
Now it works correctly.
