### ISSUE TITLE
How to customize the progressbar when buffering

### ISSUE THREAD

**Issue by silvershort** [google/ExoPlayer#6957]
How do I customize the progress bar when buffering?

How to simply change the color and size,
And I want to know how to use custom progress bar.

```
    <com.google.android.exoplayer2.ui.PlayerView
        android:id="@+id/detail_exo"
        android:layout_width="match_parent"
        android:layout_height="0dp"
        app:show_timeout="0"
        app:show_buffering="always"
        app:layout_constraintDimensionRatio="1:1"
        app:layout_constraintTop_toTopOf="parent"
        app:layout_constraintBottom_toBottomOf="parent">

    </com.google.android.exoplayer2.ui.PlayerView>
````

The xml code of the current playerview.

**Comment by kim-vde** [comment]
Have you tried adding some attributes from `DefaultTimeBar` to the `PlayerView` (see [`DefaultTimeBar` Javadoc](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/ui/DefaultTimeBar.html) and [`PlayerView` Javadoc](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/ui/PlayerView.html))?

Example:
```
<com.google.android.exoplayer2.ui.PlayerView android:id="@+id/player_view"
      app:played_color="@android:color/holo_red_dark"/>
```

Concerning the use of a custom time bar, see the [`PlayerControlView` Javadoc](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/ui/PlayerControlView.html).

**Comment by silvershort** [comment]
I have looked at that document.
But it doesn't seem to be what I want.
In the center of the video when buffering
https://4.bp.blogspot.com/-tqB3UP6KYaM/VItDu0F9kdI/AAAAAAAAATs/QB0X4AqWWY0/s1600/spinningwheel.gif
I want to know how to change circleprogressbar like a link.

**Comment by kim-vde** [comment]
You can customize the progress bar by overriding the component with id `exo_buffering`, as explained in the [`PlayerView` Javadoc](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/ui/PlayerView.html).

**Comment by silvershort** [comment]
I'm very sorry, but can you explain how to override the layout?
I create exo_player_view.xml layout in res / layout * directory

https://github.com/m6s/video-android-2/blob/master/app/src/main/res/layout/exo_player_view.xml

After copying and pasting the above link source,
I created a View with the ID exo_buffering

android.view.InflateException: Binary XML file line # 8: Binary XML file line # 8: Error inflating class com.google.android.exoplayer2.ui.PlayerView
Caused by: android.view.InflateException: Binary XML file line # 8: Error inflating class com.google.android.exoplayer2.ui.PlayerView

I get the above error.

Do you need to do something other than simply creating an exo_player_view.xml layout?

**Comment by kim-vde** [comment]
The `ProgressBar` needs to be defined in the new layout file. For example, if you want a large red progress bar, your `exo_player_view.xml` would be something like:

```
<?xml version="1.0" encoding="utf-8"?>
<merge xmlns:android="http://schemas.android.com/apk/res/android">

  <com.google.android.exoplayer2.ui.AspectRatioFrameLayout android:id="@id/exo_content_frame"
      android:layout_width="match_parent"
      android:layout_height="match_parent"
      android:layout_gravity="center">

    <!-- Video surface will be inserted as the first child of the content frame. -->

    <View android:id="@id/exo_shutter"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="@android:color/black"/>

    <ImageView android:id="@id/exo_artwork"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:scaleType="fitXY"/>

    <com.google.android.exoplayer2.ui.SubtitleView android:id="@id/exo_subtitles"
        android:layout_width="match_parent"
        android:layout_height="match_parent"/>

    <ProgressBar android:id="@id/exo_buffering"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:indeterminate="true"
        android:layout_gravity="center"
        style="?android:attr/progressBarStyleLarge"
        android:indeterminateTint="@android:color/holo_red_dark"/>

    <TextView android:id="@id/exo_error_message"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_gravity="center"
        android:gravity="center"
        android:background="@color/exo_error_message_background_color"
        android:padding="16dp"/>

  </com.google.android.exoplayer2.ui.AspectRatioFrameLayout>

  <FrameLayout android:id="@id/exo_ad_overlay"
      android:layout_width="match_parent"
      android:layout_height="match_parent"/>

  <FrameLayout android:id="@id/exo_overlay"
      android:layout_width="match_parent"
      android:layout_height="match_parent"/>

  <View android:id="@id/exo_controller_placeholder"
      android:layout_width="match_parent"
      android:layout_height="match_parent"/>

</merge>

```

**Comment by silvershort** [comment]
It works perfectly well. Thank you for your kind explanation.
