### ISSUE TITLE
Integrate and customize IMA SDK for Android

### ISSUE THREAD

**Issue by yoobi** [google/ExoPlayer#6960]
### [REQUIRED] Searched documentation and issues
I've looked on stackoverflow, medium, and your the ads page which is in development [link](https://exoplayer.dev/ad-insertion.html)

### [REQUIRED] Question
I'm trying to integrate (which are in VAST protocol) and customize an ad to fit my needs which are modifying the "learn more" textbox with another text, add another link in the center of the screen and move the "skip in .." somewhere else.

I'm using Exoplayer:
```gradle
implementation "com.google.android.exoplayer:exoplayer:2.11.1"
implementation 'com.google.android.exoplayer:extension-ima:2.11.1'
```
----------

So far I was able to show this:
[![enter image description here][1]][1]

I'd like to change the "Learn More" textbox and add another button in the center?

Do you have any ressources or tutorial that I could use to do this ? If it's not doable, could you recommend me the way to achieve this ?

Thank you.

  [1]: https://i.stack.imgur.com/rUzgr.png

**Comment by kim-vde** [comment]
I am afraid I cannot help you because don't think this is possible (see https://github.com/google/ExoPlayer/issues/6313#issuecomment-522515193 and https://developers.google.com/interactive-media-ads/docs/sdks/android/faq#13).

**Comment by yoobi** [comment]
Okay thank you, that's what I though. I guess the only way to do what I want is to create a custom ad player
