### ISSUE TITLE
How to set initialize angle when start to play 360 video

### ISSUE THREAD

**Issue by ducnmisbk** [google/ExoPlayer#6964]
### Question
I want to set starting angle at exactly the center of source video frame when start playing 360 video. I already looked for methods in the doc reference (https://exoplayer.dev/doc/reference/) but got no luck. 
So my question is how can I set the starting angle at center?

### A full bug report captured from the device
For example:
I used Xiaomi 8 lite for testing (https://www.gsmarena.com/xiaomi_mi_8_lite-9329.php)
When start playing sample congo video the screen display as below image.
![85023196_555356201740162_8859166768728375296_n](https://user-images.githubusercontent.com/12099900/74211617-4c42c780-4cc3-11ea-86e9-1e1028ee3499.png)

But I want to set the start angle at the center as below image
![Screen Shot 2020-02-11](https://user-images.githubusercontent.com/12099900/74211912-89f42000-4cc4-11ea-9f88-5951915239e1.png)

### More information
I think my question is closely relevant to this issue https://github.com/google/ExoPlayer/issues/6480

Please help. Thanks!

**Comment by kim-vde** [comment]
I cannot reproduce on my test device (Pixel 2 XL).

What version of ExoPlayer are you using? Is this the demo app without any modification?

**Comment by ducnmisbk** [comment]
> I cannot reproduce on my test device (Pixel 2 XL).
> 
> What version of ExoPlayer are you using? Is this the demo app without any modification?

I used the latest one in this repository without any modification. 
I can't reproduce in samsung S9. But always happened when testing in Xiaomi devices (one of popular mobile brands in asia)
Do you think this issuse related to sensor of specific device?

**Comment by kim-vde** [comment]
You should report the problem to the device manufacturer. Please come back to us if you can reproduce the issue on other devices as well. Thanks.
