### ISSUE TITLE
IMA AdsLoader throwing an error with error code 1009 on pre-roll (with valid response on VAST inspector)

### ISSUE THREAD

**Issue by nishantkp** [google/ExoPlayer#6967]
### Issue description
Video doesn't load pre-roll. In VAST inspector I can still see the valid response, but when player tries to play the video, it does not play pre-roll and prints out log saying,

```
2020-02-11 13:52:21.026 4918-4918/com.google.android.exoplayer2.demo I/ImaAdsLoader: AdEvent: {errorMessage=The response does not contain any valid ads., errorCode=1009, type=adLoadError}
2020-02-11 13:52:21.531 4918-4918/com.google.android.exoplayer2.demo W/ImaAdsLoader: Unexpected loadAd in an ad group with no remaining unavailable ads
2020-02-11 13:52:30.366 4918-4918/com.google.android.exoplayer2.demo I/ImaAdsLoader: AdEvent: {errorMessage=VAST media file loading reached a timeout of 8 seconds., errorCode=402, type=adPlayError}
```

**P.S.** This one seems similar to issue #4779. But this one is for pre-roll instead of post-roll. 

### Reproduction steps
Just play any video with provided adTag on demo app

### Link to test content
Sample ad tag : https://pubads.g.doubleclick.net/gampad/ads?ciu_szs=300x250,728x90&sz=320x240&impl=s&gdfp_req=1&env=vp&output=xml_vmap1&unviewed_position_start=1&ad_rule=1&pp=global_go&correlator=1581445916&cmsid=2495352&iu=6872/shaw.mob.globaltv.com&vid=GLOB0056281260000000&cust_params=device%3Dandroidtablet%26bdu%3DShawGo%26version%3D3.0.0%26market%3D%26vmap%3Dyes%26mobileapp_idfa%3D33ca2f41-f9fb-4d63-bbd4-1dbe43cb00e0%26mobileapp_dnt%3Dfalse%26description_url%3Dhttps%3A%2F%2Fwww.globaltv.com%26mobileapp_ua%3DDalvik%2F2.1.0+%28Linux%3B+U%3B+Android+7.0%3B+SM-T813+Build%2FNRD90M%29%26mobileapp_url%3Dhttps%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.shawmedia.smglobal%26mobileapp_osversion%3D7.0%26mobileapp_carrier%3Dnone%26mobileapp_network%3Dwifi

### A full bug report captured from the device
- Reproducible on demo app

### Version of ExoPlayer being used
2.10.7 and onwards
### Device(s) and version(s) of Android being used
Any devices with api 21 and above. Did not checked on lower versions.

**Comment by andrewlewis** [comment]
There are two prerolls and one of them is empty, and I think what's going on is that we skip the entire preroll ad group as a result of seeing the empty ad, similar to #5006. Assuming it's the same issue, this should be fixed once we can upgrade to the new preloading API (#6429), and that upgrade is blocked waiting for a backend rollout the IMA team is working on at the moment (we still don't have a firm ETA on that but I understand they are making progress).

**Comment by nishantkp** [comment]
Hi @andrewlewis thanks for the clarification. So it is better to avoid fill issues for pre-roll till this is fixed.

**Comment by andrewlewis** [comment]
Yes, that's right. Thanks. I'll close this for now as there is a workaround and #6429 tracks the "proper" fix.
