### ISSUE TITLE
How to find exoplayer version from apk binary

### ISSUE THREAD

**Issue by wjj1928** [google/ExoPlayer#6968]
How to find which exoplayer version is used in apk binary?

I wish to find the exoplayer version used in apk binary (e.g. Google Files app) since some old version app behavior is different from newest one. Since app call exoplayer, so I wish to find the exact exoplayer version  to analysis if issue come from exoplayer version or not!

**Comment by kim-vde** [comment]
I am afraid this is not something we support. You can raise your issue to the Google Files team (for example by using the "Help and feedback" option in the Files app). If you have troubles playing a particular file, you can also try to play it with different versions of the [ExoPlayer demo app](https://exoplayer.dev/demo-application.html), to see if it is linked to the ExoPlayer version.

**Comment by wjj1928** [comment]
Google Files just a example, if exoplayer has some code to print version number, it would be very helpful for issue track! Where can I download demo.apk for old versions?

**Comment by kim-vde** [comment]
You can checkout the release tags and build the apk locally.
