### ISSUE TITLE
Which segment to start download for DASH Live stream

### ISSUE THREAD

**Issue by jzhoubupt** [google/ExoPlayer#6973]
### [REQUIRED] Question
For a DASH Live stream which segment does ExoPlayer decide to download and process? From source code i'd like to know which classes implement the logic as well.

For HLS Live stream the client behavior is defined in HLS draft however i can't find the similar guide for DASH. From different player implement ion (Exo,Shaka,Dash.js) the behavior are not quite the same.
Thanks a lot for your feedback.
jzhoubupt

**Comment by kim-vde** [comment]
I think the information you are looking for is in [`DashMediaSource.Factory.html#setLivePresentationDelayMs`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/source/dash/DashMediaSource.Factory.html#setLivePresentationDelayMs-long-boolean-).

If not, please provide more details about what kind of logic you are looking for.

**Comment by jzhoubupt** [comment]
Hi @kim-vde ,
Thanks for pointing that. This is the area i was looking for.
I was guessing there is logic in Exo to calculate the start position for live case but a API to set this value is reasonable as well.
Regards,
jzhoubupt

**Comment by jzhoubupt** [comment]
Get my answer and close the ticket.
Thanks again for your support.
