### ISSUE TITLE
Pixel 3 Android 9 Widevine DASH - no video (only audio)

### ISSUE THREAD

**Issue by oleksandr-yefremov** [google/ExoPlayer#6974]
[REQUIRED] Issue description
On Pixel 3 Android 9 Widevine DASH stream plays audio but no video (black frame).

[REQUIRED] Reproduction steps
Start ExoPlayer demo app. Add manifest stream url and drm license url from test website sent to dev.exoplayer@gmail.com. 

[REQUIRED] Link to test content
Will send a message to dev.exoplayer@gmail.com with a link to test website, where manifest and license url to our private livestream is generated.

[REQUIRED] A full bug report captured from the device
[bugreport-blueline-PQ1A.181105.017.A1-2020-02-13-15-00-36.zip](https://github.com/google/ExoPlayer/files/4199527/bugreport-blueline-PQ1A.181105.017.A1-2020-02-13-15-00-36.zip)

[REQUIRED] Version of ExoPlayer being used
2.11.1, 2.10.5

[REQUIRED] Device(s) and version(s) of Android being used
Reproducible on Google Pixel 3 with **Android 9.0**
We also got reports that this issue can be reproduced on Pixel 3a, Pixel 3 XL and OnePlus6T, OnePlus3/3T, but for those we don't have test devices.
The issue is not reproducible on Pixel devices on **Android 10**. 

Downgrading to L3 in code did not have any effect (it is an SD stream, so it should be possible). The issue has a high priority for us, because users can't watch our livestreams and there is still a lot of them who did not upgrade to Android 10. Looks very similar to what we have reported earlier with [Pixel 2 Android 8](https://github.com/google/ExoPlayer/issues/3596), but we are not sure whether it's the same problem or not.

**Comment by oleksandr-yefremov** [comment]
Any progress on this one?

**Comment by oleksandr-yefremov** [comment]
Can I get any kind of input on this issue? If you are busy with other things and won't have time to check it in the near future, then we will have to provide some feedback to our users. Something along the lines of "you are using outdated Android OS version, please upgrade to the latest".

**Comment by ojw28** [comment]
@jt64 - Could you take a look at this?

**Comment by jt64** [comment]
I believe this may be the same issue as what was reported in issue #3596. It is a color scheme encoding issue that was found on Android 9 devices and subsequently fixed. There is a workaround described in that issue. Please take a look.
