### ISSUE TITLE
Compiling the Exoplayer code to generate .aar file throws an error

### ISSUE THREAD

**Issue by harini113** [google/ExoPlayer#6976]
### [REQUIRED] Searched documentation and issues
https://exoplayer.dev/design-documents.html

### [REQUIRED] Question
When including  custom .aar file for Core, DASH, HLS and Smoothstreaming the apk throws the files
java.lang.NoClassDefFoundError: Failed resolution of: Lorg/jacoco/agent/rt/internal_8ff85ea/Offline;

I have compiled the .aar files using the version 2.11.2 and latest version of Android Studio.
The command used to generate the .aar file was Build -> Make Module "Library-xxx" which could be core, dash or hls. 

Are there any specific steps to be followed to generate the .aar files or modifications needed on my Android Studio Setup

**Comment by master255** [comment]
I just compiled the HLS library and I have no error. You can try this: implementation 'com.google.android.exoplayer:exoplayer-core:2.11.2'

**Comment by harini113** [comment]
I am compiling my apk via android.mk so I have included the custom .aar files via the following in the android.mk

LOCAL_STATIC_JAVA_LIBRARIES += library-core-debug
LOCAL_PREBUILT_STATIC_JAVA_LIBRARIES += library-core-debug:../../libs/library-core-debug.aar

**Comment by master255** [comment]
@harini113 Maybe this file?
[library-core-release.zip](https://github.com/google/ExoPlayer/files/4201554/library-core-release.zip)

**Comment by harini113** [comment]
I have the the aar files generated and shared in Exoplayer binary tray. I want to know how I could generate my custom .aar file which can be included with my exoplayer apk which will be generated via android.mk which would not throw the error.

**Comment by harini113** [comment]
I think I got it. By generating the release module rather than debug module for core library I think the issue is fixed. Testing it out currently

**Comment by master255** [comment]
@harini113 Okay. Close the bug.
Google should start paying my salary))).
