### ISSUE TITLE
MergingMediaSource with delay

### ISSUE THREAD

**Issue by karen-1996** [google/ExoPlayer#6977]
Hi
I have MergingMediaSource with audio and video sources and want to add delay to the audio file, like to play audio after 2 seconds from the video.
My audio and video sources are ProgressiveMediaSource and I can't find a solution for this.

I look forward to your reply.

**Comment by kim-vde** [comment]
If possible, the easiest way is to update the audio stream directly.

If not, you can concatenate the audio with a `SilenceMediaSource`, but then you will not be able to merge the resulting media source with the video, as they don't have the same number of periods anymore. You will therefore need to use 2 different players (one for audio, one for video) and to implement the synchronisation by yourself.

Another solution would be to do something like `concat(merge(clip(video, 0, 2), silence(2)), merge(clip(video, 2, end), audio))` but you might encounter a slight pause in the video.

**Comment by karen-1996** [comment]
I try to concatenate 2 media sources but played only first, here is what I try
val concatenatingMediaSource =
            ConcatenatingMediaSource(
                ClippingMediaSource(videoSource, 0, 40000000),
                ClippingMediaSource(videoSource, 4000000, 15000000)
            )

After this, my video played from 0 to 4 seconds and ended

**Comment by kim-vde** [comment]
`ConcatenatingMediaSource` creates playlist items. By default, the 2 `ClippingMediaSource`s should be played one after the other, as playlist items. You can play the videos as if it was a single media by setting [`setShowMultiWindowTimeBar`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/ui/PlayerView.html#setShowMultiWindowTimeBar-boolean-).

**Comment by karen-1996** [comment]
Great, this problem solved. Now I try something like this
```
val mediaSource = ConcatenatingMediaSource(
                MergingMediaSource(
                    ClippingMediaSource(videoSource, 0, 2000000),
                    SilenceMediaSource(2000000)
                ),
                MergingMediaSource(
                    ClippingMediaSource(videoSource, 2000000, 15000000),
                    audioSource
                )
            )
```
Here the video starts and there is no sound, everything looks good. After 2 seconds audio starts playing, and it was playing from 2 seconds, not from 0 seconds.
Why ???

**Comment by tonihei** [comment]
That's a known bug, see #6103.
