### ISSUE TITLE
ImaAdsLoader Error

### ISSUE THREAD

**Issue by inat-tv** [google/ExoPlayer#6980]
Ima Ads Loader keeps getting errors. Rebuild Project finally got this error.

<a href="https://hizliresim.com/0rVJZV"><img src="https://i.hizliresim.com/0rVJZV.png"></a>

**Comment by ojw28** [comment]
It looks like you're trying to use ExoPlayer's IMA extension together with a version of the IMA SDK that's newer than the one we support. We currently support 3.11.3, which is what we pull in via gradle if you don't do anything special yourself:

https://github.com/google/ExoPlayer/blob/r2.11.2/extensions/ima/build.gradle#L35

Upgrading ExoPlayer to use a newer version of the IMA SDK is tracked by https://github.com/google/ExoPlayer/issues/6429.
