### ISSUE TITLE
Unreleased Resource: Streams

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [google/ExoPlayer#6984]
https://github.com/google/ExoPlayer/blob/fd24df3b262dca1bc0b429421ba334fa127af3cf/library/core/src/main/java/com/google/android/exoplayer2/audio/TeeAudioProcessor.java#L163

The program can potentially fail to release a system resource.

**Comment by christosts** [comment]
Hi,

I'm not sure I follow the question. The file is closed in the [reset()](https://github.com/google/ExoPlayer/blob/fd24df3b262dca1bc0b429421ba334fa127af3cf/library/core/src/main/java/com/google/android/exoplayer2/audio/TeeAudioProcessor.java#L225) method.

Have you come upon a situation where the file is not closed?
