### ISSUE TITLE
When can we expect better battery consumption support in Exoplayer For Android Q and above

### ISSUE THREAD

**Issue by pawaom** [google/ExoPlayer#6986]
When can we expect better battery consumption support in Exoplayer For Android Q and above

It was mentioned in this post

https://exoplayer.dev/battery-consumption.html

hope its done soon

**Comment by krocard** [comment]
I'm currently working on it full time. This requires to rework the renderer data path and scheduling of Exoplayer so it is far from trivial. Very soon a detailed design doc will be published and some preliminary patches have already been merged (eg: ebce903aaf543b5056022dc71ed5e3cce866fdbc).
