### ISSUE TITLE
Chromecast Audio not detectable after upgrading from 2.10.8 to 2.11.2

### ISSUE THREAD

**Issue by finneapps** [google/ExoPlayer#6988]
### [REQUIRED] Issue description
Chromecast Audio and normal Chromecast has been working fine when using 2.10.8. But after I upgraded to use 2.11.2, it is only the Chromecast on my TV that is detectable. Chromecast Audio is gone. I also tried 2.11.0 and that version is also not able to detect Chromecast Audio.
I create ExoPlayer and CastPlayer like this:
```Kotlin
private val castPlayer = CastPlayer(CastContext.getSharedInstance(context.applicationContext))
private var exoPlayer = ExoPlayerFactory.newSimpleInstance(context, AudioOnlyRenderersFactory(context), DefaultTrackSelector())
```
in 2.11.2 newSimpleInstance is deprecated so I changed it to
```Kotlin
private var exoPlayer = SimpleExoPlayer.Builder(context, AudioOnlyRenderersFactory(context)).setTrackSelector(DefaultTrackSelector(context)).build()
```
But that did not help. I call this
```Kotlin
CastContext.getSharedInstance(this.applicationContext)
```
From my main activity.

I also use
```Kotlin
AudioAttributes.Builder().setContentType(C.CONTENT_TYPE_SPEECH).setUsage(C.USAGE_MEDIA).setAllowedCapturePolicy(C.ALLOW_CAPTURE_BY_SYSTEM).build()
```
Chromecast Audio is detectable in Google Play Music and also in the Google Home app.

### [REQUIRED] Reproduction steps
checkout r2.10.8 git SHA-1 33938c05b5050057f4bf865cf8e1f76207f56232
On this branch the demo cast app finds my Chromecast Audio device

Now checkout r.2.11.0 git SHA-1 76962d50f1d80941d6768e4e765fa4ff010705e7
On this branch the demo cast app *cannot* find Chromecast Audio

### [REQUIRED] Link to test content
not relevant

### [REQUIRED] A full bug report captured from the device
[bugreport-Onyx_00WW-QKQ1.190828.002-2020-02-18-09-38-55.zip](https://github.com/google/ExoPlayer/files/4218197/bugreport-Onyx_00WW-QKQ1.190828.002-2020-02-18-09-38-55.zip)

### [REQUIRED] Version of ExoPlayer being used
2.11.0

### [REQUIRED] Device(s) and version(s) of Android being used
Nokia 7 plus, Android 10

**Comment by AquilesCanta** [comment]
Would you kindly try it and reach back? It may be fixed now.

**Comment by finneapps** [comment]
Hi. All of sudden Chromecast Audio started to appear again. Not sure what the cause was.

**Comment by AquilesCanta** [comment]
It was a server side issue. The Cast team fixed it when we flagged it. Thanks for reporting!
