### ISSUE TITLE
Video Looping inside of Leanback UI

### ISSUE THREAD

**Issue by jopolot** [google/ExoPlayer#6992]
I have an issue I trying to see if someone knows what maybe going wrong.  I have an app similar to the Video Looper by Braids Brain. Except I am using the Android Leanback UI. The Video Looper app seems to run without issue video after video, but my app will start to have audio issues then start jumping frames, then eventually will close Android Box will just go back to home screen.

It will normally work fine after restarting the box, but after about 15 minutes or so it will start having the same issues again. I am unable get a error log, because it be problem won't happen sometimes an hour or so later.

**Comment by ojw28** [comment]
I don't think this has anything to do with your use of the Leanback UI. It sounds like the device just has an underlying problem at the platform level.

We've seen a lot of issues with what I'd describe as "low end" Android TV devices. You'll most likely need to report the issue to the device manufacturer.

**Comment by jopolot** [comment]
Yes, I understand your comment and what you mean, but The Video Looper App, by Brads Brain works well on the same Android Device, so I don't think the device is the problem. I will however see if I can track down the error code in hopes that it will reveal the issue whether device related or not.

**Comment by ojw28** [comment]
I don't think that comparing your app to another is a good way of working out whether the issue is device related. You have no way of knowing how that other app is implemented, and there are all kinds of potential differences in the detail of exactly how different apps might make use of the underlying platform.

**Comment by jopolot** [comment]
Thanks for the feedback, I will continue to look at platform differences and issues, I did play it on my Fire TV, saw visual improvements, but didn't pick up certain Thumbnails on the app. Exoplayer itself is running fine, I have three different devices Fire TV 6.0, X96s, X96mini, will continue testing, trying to figure out best way to have program run properly, but since the program runs on different platforms, its obvious the Exoplayer itself is not the problem, so will close.
