### ISSUE TITLE
Can we download Multiple(URI's) Videos  with One Service running with One Notification.

### ISSUE THREAD

**Issue by sakhasri** [google/ExoPlayer#6993]
[No information provided]

**Comment by marcbaechinger** [comment]
This is not supported I'm afraid. Each URL creates a separate `DownloadRequest` which can be downloaded, cancelled, deleted on its own and creates its own notification.

**Comment by marcbaechinger** [comment]
You only need a single `DownloadService` for multiple downloads. So downloading multiple streams with a single service is the normal case. You can look into the demo app which uses a single service only.

Further the download service only creates a single notification for the stream which is currently downloaded. 

The `DemoDownloadService` of the demo app creates one notification for each download which is completed, but you can customize this behaviour and just not create that notification on completion.

Can you give me some more details of what the behaviour is of what you see and what you want to achieve?
