### ISSUE TITLE
Black screen flashing when playing on recycler view

### ISSUE THREAD

**Issue by MauroVa** [google/ExoPlayer#6996]
### [REQUIRED] Issue description
Hello, I'm trying to implement a video player in a recycler view, I have a list of videos you can scroll, the video showed on screen is set on play while the others off screen are set on pause. I'm doing this setting player.playWhenReady on true or false.
The problem I'm facing is whenever a video starts playing there's a short black screen flashing before it actually starts playing.
Here's a video showing the issue: [https://imgur.com/a/2fZOv7Y](https://imgur.com/a/2fZOv7Y)

### [REQUIRED] Reproduction steps
Create a simple exo player in an adapter and set it to a view contained in a view holder, and change player.playWhenReady value on scrolling.

### [REQUIRED] Link to test content
[https://test-videos.co.uk/vids/bigbuckbunny/mp4/h264/1080/Big_Buck_Bunny_1080_10s_30MB.mp4](url)

### [REQUIRED] A full bug report captured from the device
Not relevant, it's just a visual glitch

### [REQUIRED] Version of ExoPlayer being used
I tried on ExoPlayer 2.10.7 and 2.11.3

### [REQUIRED] Device(s) and version(s) of Android being used
Tried on a Nokia 7.1 with android 10

**Comment by marcbaechinger** [comment]
It takes some time from the moment you prepare the player until it renders the first frame. I think that's the black flickering you are seeing. 

You can try to prepare the player as early as possible, like when the `ViewHolder` is attached to the `RecyclerView` and the player view is still off screen (`RecyclerView.OnChildAttachStateChangeListener`). If you already doing this and it does not help, there is probably not much you can do about it. You basically would need to have a bitmap of the first frame which you can place on top of the player view and which you remove when `AnalyticsCollector.onRenderedFirstFrame` is called.

This is not trivial to solve. You can in theory use multiple player instances if you are not already doing that. This brings in the difficulty that the number of player instances you can create is limited by the number of codec instances available on a device. This is different on different devices though and you need to take care to not run into problem.

As a simple approach you can just use a single bitmap which you can place on each player view (you can probably use the `artworkView`  for that which is part of the `PlayerView`) and remove it when the first frame is rendered. This would just replace the black frame with that bitmap though if you don't have a bitmap of the first frame of each video.

There is an open issue #867 about playing in a `RecyclerView`  where people discuss approaches for solving similar problems.
