### ISSUE TITLE
Stop player at specific position in recyclerview

### ISSUE THREAD

**Issue by saadbzu** [google/ExoPlayer#6998]
I want to stop the exo player at a specific position in recyclerview. Current the exo player have this function:

`videoPlayer.stop();`
But i want to stop player at specfic position something like :

`videoPlayer.stopAt(2);`

**Comment by christosts** [comment]
In `videoPlayer.stopAt(2)`, is parameter `2` the playback position? If yes, then this is similar to the request of #5660.
