### ISSUE TITLE
How can I change the audio track name

### ISSUE THREAD

**Issue by kirannecg** [google/ExoPlayer#7001]
I have a question, I need to change the audio track name, by default its showing English but I need to change from English to some other name & also remove none from the video track

**Comment by ojw28** [comment]
If you're using `TrackSelectionDialogBuilder`, then:

1. You can hide the "None" option using [setShowDisableOption(false)](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/ui/TrackSelectionDialogBuilder.html#setShowDisableOption-boolean-).
1. You can use [setTrackSelectionProvider](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/ui/TrackSelectionDialogBuilder.html#setTrackNameProvider-com.google.android.exoplayer2.ui.TrackNameProvider-) to provide a `TrackSelectionProvider` that'll set names for tracks other than the defaults.

Similar methods are available on `TrackSelectionView` as well.
