### ISSUE TITLE
Distinguishing between Video and Audio-only HLS streams

### ISSUE THREAD

**Issue by haohighview** [google/ExoPlayer#7014]
Can't find getRendererHasMedia method
https://github.com/google/ExoPlayer/issues/541

**Comment by Samrobbo** [comment]
Hi, that method is no longer a part of ExoPlayer. 

What is it you are trying to do?

Thanks

**Comment by haohighview** [comment]
> Hi, that method is no longer a part of ExoPlayer.
> 
> What is it you are trying to do?
> 
> Thanks

like https://github.com/google/ExoPlayer/issues/541
Distinguishing between Video and Audio-only HLS streams
Thanks

**Comment by Samrobbo** [comment]
You can listen to the `onTracksChanged` callback, and depending on what you want to do, can check the list of available tracks or selected tracks.

**Comment by haohighview** [comment]
> You can listen to the `onTracksChanged` callback, and depending on what you want to do, can check the list of available tracks or selected tracks.

why I
