### ISSUE TITLE
Getting NullPointerException in DefaultHlsPlaylistTracker 

### ISSUE THREAD

**Issue by sumitmattawynk** [google/ExoPlayer#7017]
### [REQUIRED] Issue description
I was trying to upgrade exoplayer from 2.8.2 to 2.11.3, and while making the change following crash is coming. and I am nowhere release the MediaSource in my app.

This is not an always issue,so it might be because of some threading in exoplayer internals.

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.exoplayer2.upstream.b0.f()' on a null object reference
       at com.google.android.exoplayer2.source.hls.playlist.DefaultHlsPlaylistTracker.stop(DefaultHlsPlaylistTracker.java:148)
       at com.google.android.exoplayer2.source.hls.HlsMediaSource.releaseSourceInternal(HlsMediaSource.java:453)
       at com.google.android.exoplayer2.source.BaseMediaSource.releaseSource(BaseMediaSource.java:186)
       at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:957)
       at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:850)
       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:402)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:214)
       at android.os.HandlerThread.run(HandlerThread.java:65)
```

### [REQUIRED] Reproduction steps
This is not an always issue. so we can't reproduce it.

### [REQUIRED] Link to test content
This is random so don't have the media for this

### [REQUIRED] A full bug report captured from the device
this is a production issue, captured through firebase console.

### [REQUIRED] Version of ExoPlayer being used
2.11.3

### [REQUIRED] Device(s) and version(s) of Android being used
This issue is found in Android 9 and 10 only
in 2.8.2 similar issue was found in other android versions rather than 9 and 10 but frequency was very less.

**Comment by andrewlewis** [comment]
Thank you for the report. It looks like `initialPlaylistLoader` is null in release. This is unexpected because start/stop calls should be paired, because prepare/resource source calls should be paired.

Do you have any customizations to the `HlsMediaSource` or related source components in your app?

In the Firebase console can you see any other information about the crashes that might be relevant, especially any other logging or related exceptions? Do you see this occurring uniformly across Android 9 and 10 devices, or is it affecting specific devices? Is it occurring frequently?

**Comment by sumitmattawynk** [comment]
> Do you have any customizations to the HlsMediaSource or related source components in your app?

No we don't have any customization on HlsMediaSource. we are using as it is. moreover the class in which exception is coming is internal. we are using encryption and decryption in streams. so the data sources are overridden

> In the Firebase console can you see any other information about the crashes that might be relevant, especially any other logging or related exceptions?

No we don't see other information apart from it.

> Do you see this occurring uniformly across Android 9 and 10 devices, or is it affecting specific devices? 

It is occurring only on 9 and 10.

> Is it occurring frequently?

Frequency is like 1% of users. and we are not able to reproduce this at our end

**Comment by AquilesCanta** [comment]
Hi @sumitmattawynk, apologies for the delay here. Have you tried any newer versions of ExoPlayer? There is not enough info in this report for us to speculate on what might be causing this, specially considering this is an old version at this point. Are you still running into this issue? I'd suggest you update to a newer version and reach back if you are still encountering this issue.

**Comment by sumitmattawynk** [comment]
This issue is sort out,
There is some issue where the calls to exoplayer is going in loop, in the previous version it has handled by exoplayer, but in the new version there seems to be a raise condition which caused this,
