### ISSUE TITLE
How to pause and resume player correctly

### ISSUE THREAD

**Issue by AlanCheen** [google/ExoPlayer#702]
I use demoplayer in my project but i am confused that how to pause and resume player correctly.In the Exoplayer Demo i found two way to pause/resume:

>  1. player.setPlayWhenReady(playwhenready);

>  2. player.selectTrack(DemoPlayer.TYPE_VIDEO, -1);
       player.selectTrack(DemoPlayer.TYPE_AUDIO, -1);
> 3. use mediacontroller

But unfortunately,i found some issue:

## The way setPlayWhenReady:
1. when onPause i setPlayWhenReady(false),and  setPlayWhenReady(true) when onResume.It takes a long time until video comes out(?sorr for my poor english,hope you can understand me) and the surfaceview is black but the audio is fine.

## The way selectTrack:

when i want the video stop ,i selectTrack(DemoPlayer.TYPE_VIDEO, -1),it appearances stopped  but not actually . 

Did i do somthing wrong or miss something important?

Waiting for your help,thank you in advance!

**Comment by ojw28** [comment]
Is this for when your activity is paused because it's gone into the background? You should be fully releasing the player in that case, recording the position the playback got to, and then instantiating a fresh player and restoring the position when the activity comes back later.

The alternative requires holding onto a bunch of stuff, including a lot of memory, which isn't being a good citizen when your application isn't in the foreground.

**Comment by AlanCheen** [comment]
Thanks for your reply.
I use exoplayer in my fragment.
I had tried what you say , but it takes about 10 seconds even worse when bad network. 
I think it is not a good citizen too because user can't see anything except a black frame.

Here are some codes in my application:

```java

@Override
    public void onResume() {
        super.onResume();
        if (!bInPauseManually) {
            resumeVideoAndAudio();
        }
        // The player will be prepared on receiving audio capabilities.
        audioCapabilitiesReceiver.register();
    }

private void resumeVideoAndAudio() {
        bClosableWhenPause = true;
        if (player != null) {
//            player.setPlayWhenReady(true);
            player.seekTo(playerPosition);
            player.selectTrack(DemoPlayer.TYPE_VIDEO, 0);
            player.selectTrack(DemoPlayer.TYPE_AUDIO, 0);
        }
    }
```

```java

@Override
    public void onPause() {
        super.onPause();
        pauseVideoAndAudio(false);
        audioCapabilitiesReceiver.unregister();
    }

private void pauseVideoAndAudio(boolean closableWhenPause) {
        bClosableWhenPause = closableWhenPause;
        if (player != null) {
//            player.setPlayWhenReady(false);
            player.selectTrack(DemoPlayer.TYPE_VIDEO, -1);
            player.selectTrack(DemoPlayer.TYPE_AUDIO, -1);
            playerPosition = player.getCurrentPosition();
        }
    }
```

I have no idea how to do it better , would give me some advices?
Thank you in advance!

**Comment by ojw28** [comment]
Being a good citizen means not consuming resources when your application isn't in the foreground. It doesn't mean optimizing your own app's experience at the cost of overall platform health. So it is the right thing to do to be releasing the player. As a point of reference, the YouTube application appears to do this correctly.

**Comment by AlanCheen** [comment]
Thank you for your reply!
Now i konw how to deal with it~
Every like YouTube ,lol~~~
Thanks!
