### ISSUE TITLE
Resource leak in test code

### ISSUE THREAD

**Issue by stephensj2** [google/ExoPlayer#7022]
### [REQUIRED] Issue description
When testing your project with an automated verification tool, a bug was detected in your test code. In [HostActivity.java](https://github.com/google/ExoPlayer/blob/release-v2/testutils/src/main/java/com/google/android/exoplayer2/testutil/HostActivity.java) a WifiLock and WakeLock are created and acquired in onStart, then released in onStop:

```java 
@Override
  public void onStart() {
    Context appContext = getApplicationContext();
    WifiManager wifiManager = (WifiManager) appContext.getSystemService(Context.WIFI_SERVICE);
    wifiLock = wifiManager.createWifiLock(WifiManager.WIFI_MODE_FULL_HIGH_PERF, LOCK_TAG);
    wifiLock.acquire();
    PowerManager powerManager = (PowerManager) appContext.getSystemService(Context.POWER_SERVICE);
    wakeLock = powerManager.newWakeLock(PowerManager.PARTIAL_WAKE_LOCK, LOCK_TAG);
    wakeLock.acquire();
    super.onStart();
  }

  @Override
  public void onPause() {
    super.onPause();
    if (Util.SDK_INT <= 23) {
      maybeStopHostedTest();
    }
  }

  @Override
  public void onStop() {
    super.onStop();
    if (Util.SDK_INT > 23) {
      maybeStopHostedTest();
    }
    wakeLock.release();
    wakeLock = null;
    wifiLock.release();
    wifiLock = null;
  }
```

Such behavior can result in a resource leak due to the Activity lifecycle. Rather, you should acquire and release on onResume/onPause

```java
  @Override
  public void onResume() {
    super.onResume();
    Context appContext = getApplicationContext();
    WifiManager wifiManager = (WifiManager) appContext.getSystemService(Context.WIFI_SERVICE);
    wifiLock = wifiManager.createWifiLock(WifiManager.WIFI_MODE_FULL_HIGH_PERF);
    wifiLock.acquire();
    PowerManager powerManager = (PowerManager) appContext.getSystemService(Context.POWER_SERVICE);
    wakeLock = powerManager.newWakeLock(PowerManager.PARTIAL_WAKE_LOCK);
    wakeLock.acquire();
  }

  @Override
  public void onPause() {
    super.onPause();
    if (Build.VERSION.SDK_INT <= 23) {
      maybeStopHostedTest();
    }
    wakeLock.release();
    wakeLock = null;
    wifiLock.release();
    wifiLock = null;
  }
```

Or you should use a non-reference counted lock:
```java
  @Override
  public void onStart() {
    Context appContext = getApplicationContext();
    if(wifiLock == null) {
      WifiManager wifiManager = (WifiManager) appContext.getSystemService(Context.WIFI_SERVICE);
      wifiLock = wifiManager.createWifiLock(WifiManager.WIFI_MODE_FULL_HIGH_PERF);
      wifiLock.setReferenceCounted(false);
    }
    wifiLock.acquire();
    if(wakeLock == null) {
      PowerManager powerManager = (PowerManager) appContext.getSystemService(Context.POWER_SERVICE);
      wakeLock = powerManager.newWakeLock(PowerManager.PARTIAL_WAKE_LOCK);
      wakeLock.setReferenceCounted(false);
    }
    wakeLock.acquire();
    super.onStart();
  }

  @Override
  public void onPause() {
    super.onPause();
    if (Build.VERSION.SDK_INT <= 23) {
      maybeStopHostedTest();
    }
  }

  @Override
  public void onStop() {
    super.onStop();
    if (Build.VERSION.SDK_INT > 23) {
      maybeStopHostedTest();
    }
    wakeLock.release();
    wakeLock = null;
    wifiLock.release();
    wifiLock = null;
  }
```

### [REQUIRED] Reproduction steps
Found with an automated tool, so there's nothing to reproduce.

### [REQUIRED] Link to test content
Found with an automated tool, so there's nothing to test.

### [REQUIRED] A full bug report captured from the device
Bug not dependent on a particular device.

### [REQUIRED] Version of ExoPlayer being used
v2

### [REQUIRED] Device(s) and version(s) of Android being used
Not dependent on device.

**Comment by Samrobbo** [comment]
Looking into this now.

**Comment by Samrobbo** [comment]
I'm curious as to why you think acquiring in onStart and releasing in onStop is actually problematic? [The android activity lifecycle](https://developer.android.com/guide/components/activities/activity-lifecycle) indicates they are balanced.

**Comment by stephensj2** [comment]
The path we are detecting is as follows: onCreate -> onStart -> onResume -> onPause -> kill. As shown in the android lifecycle, it is possible for the app to be killed after onPause causing onStop never to be called. Such a path would leave both of the locks acquired when the app is killed.

**Comment by ojw28** [comment]
It's not required that an application release any locks that it's holding before it's killed. This is also impossible to implement this, because the underlying platform can kill the application at any arbitrary point in time (e.g., it's perfectly possible that `onPause` will never be called either). So I don't think your concern is valid.
