### ISSUE TITLE
Out-Of-Order Buffer Presentation Times?

### ISSUE THREAD

**Issue by CalebGartner** [google/ExoPlayer#7024]
### [REQUIRED] Searched documentation and issues
I've searched in the available documentation and through the issues, thought the closest thing I could find was this issue, which is only semi-related: https://github.com/google/ExoPlayer/issues/3139

### [REQUIRED] Question
Currently, when we're playing a simple TS file, it plays as expected, except that when we log the `outputBufferInfo.presentationTime` in `MediaCodecRenderer.java`, line 1589 in the `drainOutputBuffer()` function, we're seeing them appear out-of-order. We're only logging this value in the `if(processedOutputBuffer)` block, but we're wondering why it appears out of order so frequently.

### A full bug report captured from the device
Here are the logs we have: [hd_times_ExoPlayer.txt](https://github.com/google/ExoPlayer/files/4264532/hd_times_ExoPlayer.txt)

You can see that the buffer presentation times are not ordered. e.g.:
```
02-26 15:17:04.125 11164 11232 D PTS     : Rendered PTS in us: 384000
02-26 15:17:04.135 11164 11232 D PTS     : Rendered PTS in us: 133455
02-26 15:17:04.165 11164 11232 D PTS     : Rendered PTS in us: 166833
02-26 15:17:04.167 11164 11232 D PTS     : Rendered PTS in us: 426666
02-26 15:17:04.206 11164 11232 D PTS     : Rendered PTS in us: 200200
02-26 15:17:04.208 11164 11232 D PTS     : Rendered PTS in us: 469333
02-26 15:17:04.236 11164 11232 D PTS     : Rendered PTS in us: 233555
02-26 15:17:04.257 11164 11232 D PTS     : Rendered PTS in us: 512000
02-26 15:17:04.266 11164 11232 D PTS     : Rendered PTS in us: 266933
02-26 15:17:04.297 11164 11232 D PTS     : Rendered PTS in us: 554666
02-26 15:17:04.306 11164 11232 D PTS     : Rendered PTS in us: 300288
02-26 15:17:04.337 11164 11232 D PTS     : Rendered PTS in us: 333666
```

**Comment by andrewlewis** [comment]
Is it possible that the logging is mixing audio and video output buffer timestamps? If so, it is expected that they may not be "synchronized" as an output buffer may be processed from the perspective of the renderer without actually being presented to the user yet (e.g., it may have been written to the `AudioTrack` buffer but not played out yet.)

**Comment by CalebGartner** [comment]
Hmm, perhaps. I'll try investigating to see if we're mixing in the audio timestamps. Thanks for the suggestion!

**Comment by ojw28** [comment]
I think we can say with a pretty high degree of certainty that this is the case, since once you separate them you get two sets of timestamps with constant gaps (~42ms for audio, and ~33ms for video):
```
02-26 15:17:04.125 11164 11232 D PTS     : Rendered PTS in us: 384000
02-26 15:17:04.167 11164 11232 D PTS     : Rendered PTS in us: 426666
02-26 15:17:04.208 11164 11232 D PTS     : Rendered PTS in us: 469333
02-26 15:17:04.257 11164 11232 D PTS     : Rendered PTS in us: 512000
02-26 15:17:04.297 11164 11232 D PTS     : Rendered PTS in us: 554666
```
```
02-26 15:17:04.135 11164 11232 D PTS     : Rendered PTS in us: 133455
02-26 15:17:04.165 11164 11232 D PTS     : Rendered PTS in us: 166833
02-26 15:17:04.206 11164 11232 D PTS     : Rendered PTS in us: 200200
02-26 15:17:04.236 11164 11232 D PTS     : Rendered PTS in us: 233555
02-26 15:17:04.266 11164 11232 D PTS     : Rendered PTS in us: 266933
02-26 15:17:04.306 11164 11232 D PTS     : Rendered PTS in us: 300288
02-26 15:17:04.337 11164 11232 D PTS     : Rendered PTS in us: 333666
```
If you want only the video ones you should add logging in the `MediaCodecVideoRenderer` subclass, or add an instanceof check to the condition that decides whether to log something.
