### ISSUE TITLE
I am not able play this url.

### ISSUE THREAD

**Issue by arun-ns** [google/ExoPlayer#7027]
I am not able play this url.

https://tvesyfy-vh.akamaihd.net/i/prod/video/645/191/180615_3746314_The_Tip_of_the_Zoidberg_anvver_5_,40,25,18,12,7,4,2,00.mp4.csmil/master.m3u8?__b__=1000&hdnea=st=1582897780~exp=1582905010~acl=/i/prod/video/645/191/180615_3746314_The_Tip_of_the_Zoidberg_anvver_5_*~id=3af44eeb-211b-40c4-9ab6-327ae1f28d6c~hmac=b5bc47ab4c7a999349d2442921ec4a5d858a06b80af2864e8a6699358441db5c

Error:
UnrecognizedInputFormatException: None of the available extractors
(MatroskaExtractor, FragmentedMp4Extractor, ...) could read the stream.https://github.com/google/ExoPlayer/issues/5346

**Comment by andrewlewis** [comment]
Looking at the URL, this appears to be an HLS stream so please make sure you're using `HlsMediaSource`.

**Comment by andrewlewis** [comment]
The stream plays fine in the ExoPlayer demo app (after allowing non-HTTPS connections) using `HlsMediaSource`.

**Comment by arun-ns** [comment]
How to  allow non-HTTPS connections ?? Please Provide Some Code Snippets

**Comment by arun-ns** [comment]
> The stream plays fine in the ExoPlayer demo app (after allowing non-HTTPS connections) using `HlsMediaSource`.

Have you checked in Demo app. Because I am not able to play demo app also

**Comment by Shmuel83** [comment]
> How to allow non-HTTPS connections ?? Please Provide Some Code Snippets

In your manifest, add that
```
 <application
android:networkSecurityConfig="@xml/network_security_config">
```

And in your /res/xml , created your file "network_security_config.xml"

Past that : 

```
<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
    <base-config cleartextTrafficPermitted="true">
        <trust-anchors>
            <certificates src="system"></certificates>
        </trust-anchors>
    </base-config>
</network-security-config>
```

https://developer.android.com/training/articles/security-config

**Comment by arun-ns** [comment]
> > How to allow non-HTTPS connections ?? Please Provide Some Code Snippets
> 
> In your manifest, add that
> 
> ```
>  <application
> android:networkSecurityConfig="@xml/network_security_config">
> ```
> 
> And in your /res/xml , created your file "network_security_config.xml"
> 
> Past that :
> 
> ```
> <?xml version="1.0" encoding="utf-8"?>
> <network-security-config>
>     <base-config cleartextTrafficPermitted="true">
>         <trust-anchors>
>             <certificates src="system"></certificates>
>         </trust-anchors>
>     </base-config>
> </network-security-config>
> ```
> 
> https://developer.android.com/training/articles/security-config

Its Working. Thanks a lot  @Shmuel83  @andrewlewis

**Comment by ojw28** [comment]
To blanket allow non-HTTPS in your app it's also sufficient just to do this:
```
<application
    android:usesCleartextTraffic="true"
```
which avoids you having to make the separate `network_security_config.xml` file.
