### ISSUE TITLE
add a property to enable/disable the seek bar / scrubbing

### ISSUE THREAD

**Issue by SogoGolf** [google/ExoPlayer#7031]
is there a property or programmatic way of disabling the seek bar so the user can't scrub through an audio track ?

if we set ```app:touch_target_height="0dp"``` it works, but that (i dont think) can't be changed at run time back to (say) 20dp when we DO need the user to scrub/use the seek bar.

please let us know asap many thanks

**Comment by SogoGolf** [comment]
i see this got labelled as an ```enhancement```. im amazed this sdk feature isn't available given there is already an XML property setter for it 

in the mean time is there another way / workaround to achieve this at run time ? for example what about using ```@BindingAdapter``` somehow from the Android SDK ? we're open to any kind of hack/approach for now to get this working. really appreciate your comments on this as its currently a blocker for us

**Comment by SogoGolf** [comment]
for the time being ive subclassed DefaultTimeBar and added a setter method for ```app:touch_target_height``` ie. ```setTouchTargetHeight```, which is working ok

**Comment by krocard** [comment]
Have you tried setting [Timeline.Window.isSeekable](https://github.com/google/ExoPlayer/blob/r2.11.3/library/core/src/main/java/com/google/android/exoplayer2/Timeline.java#L151) to false for the tracks you do not want to be seekable?

It should allow you to disable and enable seeking without having to modify UI touch surface. You current workaround also may be by-passable by using a keyboard/remote control.
