### ISSUE TITLE
Download the track by URI

### ISSUE THREAD

**Issue by vldF** [google/ExoPlayer#7035]
I used this code for create DownloadService: 

    package ru.vldf.plawer.player
    import android.app.Notification
    import android.content.Context
    import com.google.android.exoplayer2.database.ExoDatabaseProvider
    import com.google.android.exoplayer2.offline.Download
    import com.google.android.exoplayer2.offline.DownloadManager
    import com.google.android.exoplayer2.offline.DownloadService
    import com.google.android.exoplayer2.scheduler.PlatformScheduler
    import com.google.android.exoplayer2.scheduler.Scheduler
    import com.google.android.exoplayer2.ui.DownloadNotificationHelper
    import com.google.android.exoplayer2.util.NotificationUtil
    import com.google.android.exoplayer2.util.Util
    import ru.vldf.plawer.R
    
    
    class PlayerDownloadService : DownloadService(2, 100) {
        private lateinit var notificationHelper: DownloadNotificationHelper
        override fun getDownloadManager(): DownloadManager {
            notificationHelper = DownloadNotificationHelper(this, "ru.vldf.plawer")
            val databaseProvider = ExoDatabaseProvider(this);

            val cacheSourceFactory = PlayerCacheSourceFactory.getInstance(this)
            val manager = DownloadManager(
                this,
                databaseProvider,
                cacheSourceFactory.simpleCache!!,
                cacheSourceFactory
            )
            manager.maxParallelDownloads = 4
            manager.addListener(TerminalStateNotificationHelper(this, notificationHelper))
            return manager
        }
    
        override fun getForegroundNotification(downloads: MutableList<Download>): Notification {
            return notificationHelper
                .buildProgressNotification(
                    R.drawable.skip_previous_24px,
                    null,
                    "downloading...",
                    downloads
                )
    
        }
    
        override fun getScheduler(): Scheduler? {
            return PlatformScheduler(this, 1)
        }
    
    }
    
    private class TerminalStateNotificationHelper(
        val context: Context, val notificationHelper: DownloadNotificationHelper) :
        DownloadManager.Listener {
        override fun onDownloadChanged(
            manager: DownloadManager,
            download: Download
        ) {
            val notification: Notification = when (download.state) {
                Download.STATE_COMPLETED -> {
                    notificationHelper.buildDownloadCompletedNotification(
                        R.drawable.exo_icon_play,  /* contentIntent= */
                        null,
                        Util.fromUtf8Bytes(download.request.data)
                    )
                }
                Download.STATE_FAILED -> {
                    notificationHelper.buildDownloadFailedNotification(
                        R.drawable.unknown_document,  /* contentIntent= */
                        null,
                        Util.fromUtf8Bytes(download.request.data)
                    )
                }
                else -> {
                    return
                }
            }
            NotificationUtil.setNotification(context, 2, notification)
        }
    
    }

and this for start download:

        val request = DownloadRequest(
            track.key,  // unique id
            DownloadRequest.TYPE_PROGRESSIVE,
            Uri.parse(track.fileUrl),
            listOf(),
            track.key,
            track.key.toByteArray()
        )
        DownloadService.sendAddDownload(
            this,
            PlayerDownloadService::class.java,
            request,
            false
    )

But after this code starts, music doesn't downloading, notification doesn't updates and etc. If I try to debug this code, I see that `onDownloadChanged()` calls few times with diferent `download`. And statuses of all of them are `STATE_DOWNLOADING` or `STATE_QUEUED`. And after this code stops, I can see, that URIs adds to `my_app_path\databases\exoplayer_internal.db`, but cache files  of music don't apears in directories.

I wanna save music to local storage by URIs. What I'am doing wrong?

**Comment by krocard** [comment]
@marcbaechinger can I assign it to you as the owner of the download component? I do no see anything obviously wrong here.

**Comment by krocard** [comment]
The notification not showing up seems

**Comment by marcbaechinger** [comment]
Sorry for my late response. 

Can you please create a bug report right after you have tried to download a song? Then upload it here so I can investigate a bit more closely.
