### ISSUE TITLE
About MPEG-DASH behavior

### ISSUE THREAD

**Issue by hokar** [google/ExoPlayer#7036]
I would like to ask you a question about segmentation protocol.
How dows the player decide next getting segmentation?
For example, when I have this manifest which is shown below.

```
<S t="57042992" d="2002" r="445"/>
<S t="57945727" d="2169"/>
<S t="57945760" d="2136"/>
<S t="57945793" d="2103"/>
<S t="57945827" d="2069"/>　★１
<S d="2002" r="3801"/>　★２
```

I think that the next segmentation should be "★１t + ★１d(57945827 + 2069)", but actually it is "★１t + ★２d(57945827 + 2002)".
Is it expected result?

Thanks.

**Comment by ojw28** [comment]
Sorry, but I don't understand the question. I don't understand what "★１t + ★１d(57945827 + 2069)" and "★１t + ★２d(57945827 + 2002)" mean (e.g., what is the function `d`, and what are the stars). It's also unclear which segment you consider the "current" one when you ask what the next one is.

Please could you try and reformulate the question in a simpler to understand way? Thanks!

**Comment by hokar** [comment]
Sorry, this issue was misunderstood.
I'll let you know if there is anything. 
Thanks.
