### ISSUE TITLE
Is it possible to create an instance in a background thread

### ISSUE THREAD

**Issue by imcloud** [google/ExoPlayer#7039]
I create texture view by myself

Can I create and use the exoplayer in a background thread to render video

**Comment by krocard** [comment]
Yes it is possible. The only requirement is that the same thread accesses an ExoPlayer instance.

> ExoPlayer instances must be accessed from a single application thread. For the vast majority of cases this should be the application’s main thread. Using the application’s main thread is also a requirement when using ExoPlayer’s UI components or the IMA extension.
https://exoplayer.dev/getting-started.html#creating-the-player

**Comment by tonihei** [comment]
Even though it's possible, we strongly recommend to use the main UI thread for all ExoPlayer interactions because none of them are blocking. I don't think creating a texture view makes any difference as all the main work is already redirected to background threads.

**Comment by krocard** [comment]
Closing the issue as the question is answered.
