### ISSUE TITLE
Metadata Documentation?

### ISSUE THREAD

**Issue by SteveEdson** [google/ExoPlayer#704]
Forgive me, but I am having a hard time finding any documentation on how to get metadata events from Exoplayer.

I can see the API documentation for `MetadataTrackRenderer` and `Id3Parser` etc, but I'm not sure how it all fits together.

My application is playing audio only streams, using the automatic detection in `ExtractorSampleSource`.

Thanks.

**Comment by ojw28** [comment]
There are many types of metadata in many types of media. What's your specific use case (i.e. what format are you playing, what metadata are you expecting)?

**Comment by SteveEdson** [comment]
Thanks for the reply. Mostly MP3 + AAC streams, from Icecast + Shoutcast servers, with the addition of other misc streams.

I'm aware these particular Metadata parsers might not be available, but I couldn't really find how to get ID3 info from a simple MP3 file.

Thanks.

**Comment by ojw28** [comment]
Currently we only parse metadata from HLS streams.

**Comment by SteveEdson** [comment]
Are there any examples on how to achieve that?

**Comment by Ood-Tsen** [comment]
If you just need the title of each song from shoutcast.
You may try my previous patch.

Patch :

* [try to add IcyDataSource](
https://github.com/Ood-Tsen/ExoPlayer/commit/8ccc99bc5c6428760efd9f1780dd90be9386339e)

* [fix Exception ](
https://github.com/Ood-Tsen/ExoPlayer/commit/8f4a619d1244cfb5977e2e5ba0d5fac08b01903b)

**Comment by ojw28** [comment]
For HLS we parse ID3 data from the stream. The demo app prints parsed ID3 data to logcat, so it should be fairly easy to trace backwards through the code to work out how it works, given a sample HLS stream containing such data. For MP3/AAC see Ood-Tsen's response above.
