### ISSUE TITLE
AdEvent.ALL_ADS_COMPLETED called prematurely

### ISSUE THREAD

**Issue by CBCSeanNguyen** [google/ExoPlayer#7041]
I've been noticing some strange behaviour associated with the IMA ExoPlayer extension, not too sure if it's intended or not.  When loading a pre-roll ad where there are multiple ads served, if I background the app while the last ad is playing (ie. 2 of 2) I get returned an AdEvent.ALL_ADS_COMPELETED.  As a result, when returning to the app, rather than continuing the ad, it finishes and proceeds to play the content.

If I do the same steps but on the first ad (ie. 1 of 2), it pauses then resumes as intended.  Behaviour is also fine when one ad is served.

I can provide more information if needed.  I can also send an ad URL via email if needed as well.

Reproducible on the demo app
Version(s) used:  2.9.1 & 2.11.3

**Comment by andrewlewis** [comment]
Please do send the ad tag URL to dev.exoplayer@gmail.com. Thanks.

**Comment by CBCSeanNguyen** [comment]
Hello Andrew,

I sent the ad tag URL to the email.  Subject: Issue #7041

**Comment by andrewlewis** [comment]
The ad tag is unfortunately now empty. Please could you try to reproduce this on the `dev-v2` branch, as I think it is probably fixed by fa7d26dd9f94f52c412ff7d6490630dd73f187a6?

**Comment by CBCSeanNguyen** [comment]
Hey Andrew, it looks the issue is resolved using dev-v2

What would be the timeline for this release?

Thanks a bunch!

**Comment by andrewlewis** [comment]
Glad to hear that it's fixed. We generally don't give a concrete timeline as unexpected things can come up but I expect it will be within the next week or two.
