### ISSUE TITLE
In repeat mode, how do I know to play once

### ISSUE THREAD

**Issue by ventsea** [google/ExoPlayer#7049]
How do I do it? thx

**Comment by krocard** [comment]
I'm sorry but I do not understand what you are trying to achieve. Are you trying to programmatically know how many time a track in repeat mode was played?

**Comment by xinboljy** [comment]
So,How to know how many time a track in repeat mode was played? @krocard

**Comment by tonihei** [comment]
You can listen to `onPositionDiscontinuity` with reason `PERIOD_TRANSITION` to find out when it's repeating. And then count yourself.

**Comment by xinboljy** [comment]
@tonihei thanks
