### ISSUE TITLE
AVC decoding not working (Portuguese TV channels)

### ISSUE THREAD

**Issue by realwizzard** [google/ExoPlayer#7052]
When trying to decode live TV of portuguese channels (RTP1, RTP2, SIC, TVI...) VLC is not able to do it. Tested on Android with latest ExoPlayer 2.11.3. It is working with MXPlayer and BSplayer, but not with ExoPlayer and not with VLC. See mediadetails attached. Please contact me if I should upload an example file.
[mediadetails.txt](https://github.com/google/ExoPlayer/files/4293973/mediadetails.txt)

**Comment by krocard** [comment]
Please attached the media to this bug if possible, otherwise send it to  dev.exoplayer@gmail.com referencing this issue (if too big to send by email, please share it through Google Drive or shorten it).
Thanks.

**Comment by realwizzard** [comment]
https://drive.google.com/file/d/12bHJ0nF42Td25sI8B8mztiSY38Ow5J2c/view?usp=sharing

**Comment by krocard** [comment]
It's a badly formated file. Gstreamer and VLC (desktop) can not read it. FFMPEG can decode it with many errors and then give up complaining on corrupt input.
The media is malformed, exoplayer can not support it.
Given that it seems to work a bit better with ffmpeg (it's more error tolerant), you may have some luck using the ExoPlayer ffmpeg extension instead of the platform codec (cf EXTENSION_RENDERER_MODE_PREFER).

**Comment by realwizzard** [comment]
Thanks. But this is the way Portuguese NOS channels are aired. Kodi and MPC-HC can decode it without problems. I uploaded another sample which is a bit longer. 
https://drive.google.com/file/d/15G4RUqziOWLrk-GC8vwABRL4jzCeqMa_/view?usp=sharing
The FFMPEG extension is only for audio right? Or is there a way to use FFMEPG as video decoder?

**Comment by krocard** [comment]
FFMPEG is for both audio and video. You can try playing your media with ffplay, the built-in player of ffmpeg to confirm if it ffmpeg will support your malformed media.
~If it does, consider using the ExoPlayer FFMPEG extension at the platform codecs are not as error tolerant as ffmpeg.~ Not possible currently, see my next message.

**Comment by krocard** [comment]
Actually the ExoPlayer FFMPEG extension currently only implements an audio renderer, so it will not work as your video stream is malformed.
I can think of 3 ways you could playing your malformed media:

1.  try using the platform software decoder (OMX.google.h264.decoder), it could be more error tolerant than the hardware one.
2.  work with #6864 to finish a ffmpeg video renderer extention, if you confirm ffmpeg can handle your media
3.  transcode your media to a valid stream before distributed to the phone.

**Comment by krocard** [comment]
After testing your new media on ExoPlayer, the following is thrown:
```
ExoPlayerImplInternal: com.google.android.exoplayer2.ParserException: Loading finished before preparation is complete.
```
The Exoplayer container parsing failed, so my previous options 1 and 2 will not work. You could improve the ExoPlayer parser to better support invalid media.
But it's probably less work to transcode the media, you might even be able to regenerate the container only, without touching the streams, if they are valid.
