### ISSUE TITLE
Remove progressbar/seekbar from CastPlayer notification 

### ISSUE THREAD

**Issue by MDXDave** [google/ExoPlayer#7053]
### Searched documentation and issues
- https://exoplayer.dev
- Stackoverflow
- Google... 

### Question
I need to remove the progress-/seekbar from the default cast notification that appears after a cast session started, because the progress is not in-sync with the actual progress showing in the receiver app. 

![image](https://user-images.githubusercontent.com/6099976/76009131-ff908c00-5f10-11ea-85c8-5fcbdae7ead3.png)

**Comment by krocard** [comment]
I'm not sure ExoPlayer is controlling this notification. Taking a look through the Cast SDK, this is the only mention of notification I could find:
https://developers.google.com/android/reference/com/google/android/gms/cast/CastRemoteDisplayLocalService.NotificationSettings
@AquilesCanta will know more as the author of the cast extension.

**Comment by ojw28** [comment]
I agree this notification is most likely provided by the Cast SDK rather than ExoPlayer. Closing on that basis.
