### ISSUE TITLE
Black frame for video and only Audio is playing - FireTv AspectRatioFrameLayout API

### ISSUE THREAD

**Issue by giladna** [google/ExoPlayer#7054]
### [REQUIRED] Searched documentation and issues
I have been searching in the AspectRatioFrameLayout class java doc and in the issues here :)

### [REQUIRED] Question
Hi,
In the Exo Player demo app when there is update in the onVideoSizeChanged the app will onContentAspectRatioChanged that calls contentFrame.setAspectRatio(aspectRatio)

I am trying to fix an issue that for some reason only audio is playing on FireTv in our app (the media is playing fine on the Exo Player demo app on that FireTv)

when I comment the contentFrame.setAspectRatio(aspectRatio) on my app video will also be playing

the question is:  if this code is a must or can be removed or changed by the hosting app since it plays fine without that on this case.

if this is a must is there any other API that we should consider using  from AspectRatioFrameLayout class where we can apply if condition and use them instead of the setAspectRatio that works from most cases except this one.

In example using:
     contentFrame.forceLayout();
or
    contentFrame.setMeasureAllChildren(true);

PS.

For this device this issue happening  on medias that its values as below
in this format 

width="640"
height="512"

width="720"
height="576"

On same device this issue is NOT happening to us on media that its values as below 

width="640"
height="360"

width="1280"
height="720"

width="1920"
 height="1080"

Thanks!

Gilad

**Comment by ashwithraja** [comment]
We are also observed the same issue and most of the time we have seen this issue when there are multiple activities in a stack. 
 Setting the aspect ratio to AspectRatioFrameLayout.RESIZE_MODE_FILL makes playback to appear with stretch. 

Thanks
Ashwith

**Comment by custadian** [comment]
Hi, I am also facing this issue which is very weird. @ojw28 , if you can help on this. 
-Thanks

**Comment by prakhyathhegde** [comment]
Add further info to corner the issue. If we have multiple activities with one launching player activity having style setting "android:windowIsTranslucent=true", we end up seeing black screen in it.

item name="android:windowIsTranslucent">true</item>

**Comment by ashwithraja** [comment]
This issues is observed on fireOs vesrsion 5.2.2 and its series. Not seen on firesOs 6 and above

**Comment by ojw28** [comment]
Are all four of you working on the same project, or not? It sounds like a FireOS specific issue unrelated to ExoPlayer (except that you are using the two together). So you should probably report the issue to Amazon, and ask them for guidance.

> When I comment the contentFrame.setAspectRatio(aspectRatio) on my app video will also be playing. The question is: if this code is a must or can be removed or changed by the hosting app since it plays fine without that on this case.

The implication of not making this call is that the video may not be rendered in the correct aspect ratio (i.e., it may be stretched or squashed).

**Comment by ojw28** [comment]
Closing because this sounds like a FireOS specific issue, which should be reported to Amazon.
