### ISSUE TITLE
Rendered buffer count is always 0 when tunneling is enabled

### ISSUE THREAD

**Issue by Cizor** [google/ExoPlayer#7055]
### When tunneling is enabled, renderedOutputBufferCount is 0 
renderedOutputBufferCount of decoderCounters works fine to report number of buffers rendered for video and audio tracks but when tunneling is enabled, number of buffers are not being updated and is always 0. Audio buffer counts are working in both modes.

### Reproduction steps
1. Launch Demo app
2. Check "Request multimedia tunneling" option from top right  hidden menu.
3. Select "Widevine DASH: MP4,H264" -> "WV: Clear SD & HD (MP4,H264)" track
4. After video starts playing properly, check values in top. Second row gives values of 
decoderCounters of video tracks. Check value rb:0, in which 0 represents value of 
renderedOutputBufferCount of decoderCounters. When tunneling mode is enabled it is always 0.
Cross check it by unchecking "Request mutimedia tunneling" option and it can be seen that this value gives proper value when tunneling mode is not enabled

### Link to test content
Test media is already available in Demo app and issue can be seen with tracks present in it.
For testing, track used is Widevine DASH: MP4,H264" -> "WV: Clear SD & HD (MP4,H264)"

### A full bug report captured from the device
Bugreport sent at mail address

### Version of ExoPlayer being used
r2.11.3

### Device(s) and version(s) of Android being used
Device: ARRIS android tv box with Broadcom SOC
Model: VIP6102W
Version: 9
Firmware Version: 04.01.15.59

**Comment by andrewlewis** [comment]
Will be fixed by #7051.

**Comment by andrewlewis** [comment]
Fixed by 26d3914e43bac7491f0caa1f9ffbce1ebd6b5924.
