### ISSUE TITLE
ffmpeg Extension for x86_64

### ISSUE THREAD

**Issue by krok55** [google/ExoPlayer#7058]
Hello,

I read all the manuals and issues regarding building the ffmpeg extension for various ABI.
I'm able to build it a get it working for armeabi-v7a, arm64-v8a, x86.
However, I can't get it working for x86_64 platforms...

Can you guide me please on how should I modify `build_ffmpeg.sh` to get this working?

Thanks

**Comment by krocard** [comment]
I tried replacing `x86` and `i686` by `x86_64` in `build_ffmpeg.sh`:
```
./configure \
    --libdir=android-libs/x86_64 \
    --arch=x86_64 \
    --cpu=x86_64 \
    --cross-prefix="${TOOLCHAIN_PREFIX}/x86_64-linux-android16-" \
    --nm="${TOOLCHAIN_PREFIX}/x86_64-linux-android-nm" \
    --strip="${TOOLCHAIN_PREFIX}/x86_64-linux-android-strip" \
    --extra-ldexeflags=-pie \
    --disable-asm \
    ${COMMON_OPTIONS}
```
and it seems to build fine. Please confirm that it solve your issue. I'll then update `build_ffmpeg.sh` to support `x86_64` officially.

**Comment by krocard** [comment]
I went on and merged the x86_64. Please reopen the bug if there is an issue with my change.
