### ISSUE TITLE
No Vision while there is Sound (Customer Reviews)

### ISSUE THREAD

**Issue by rencsaridogan** [google/ExoPlayer#706]
Hello,

I was not able to detect the issue from any logs over Google Analytics or Google Play Developer Console, while trying to make the case happen within a range of 15 devices or so. I'm receiving many reviews which indicates that people are having problems when they are playing a video there is sound but no vision what so ever. Does anyone know what might be the issue?

I've also made a research and found that YouTube had the same problem a while ago with many reviews from their users as well.

PS: Some people also gives feedback that the problem is being solved when they make the video full screen, but some people also reply them with indicating that they've tried it and it does not work.

Hope someone had this issue and found a solution. Because I can not fix it due that I can not make it happen to see the logs.

Best regards,
Mackqrenc.

**Comment by ojw28** [comment]
Closing due to lack of information. Please see (this)[https://google.github.io/ExoPlayer/2015/10/01/reporting-issues.html].
