### ISSUE TITLE
When play the H264 encoded video in TS package, and the sample data sent to the MediaCodec is abnormal.

### ISSUE THREAD

**Issue by linxin2020** [google/ExoPlayer#7067]
### [REQUIRED] Issue description
With a private DRM project, I try to get the sample data to the MediaCodec, do some things; when I read the data sent to the MediaCodec, I found that the data did not meet the expectations.
I found that for each video sample data, there will be a byte 0x00 less in the front and a byte 0x00 more in the back.
For example, when I get sample data from  exoplayer is
**_00 00 01 09 f0_** 00 00 00 01 67 64 00 1f ac 72 04
...
fc 71 bb 62 b4 f8 **_f0 e1 25 00_** 

In fact, the sample should be
**_00 00 00  01 09 f0_** 00 00 00 01 67 64 00 1f ac 72 04
...
fc 71 bb 62 b4 f8 **_f0 e1 25_**

Most decoding are fault-tolerant and have no obvious problems; however, this is an obvious bug.
The TS encapsulation H264 encoded video I currently use will have such problems. Other formats have not been verified yet.

### [REQUIRED] Reproduction steps
Play the video in the link, print the sample data.

if (bufferEncrypted) {
        MediaCodec.CryptoInfo cryptoInfo = getFrameworkCryptoInfo(buffer,
            adaptiveReconfigurationBytes);
        codec.queueSecureInputBuffer(inputIndex, 0, cryptoInfo, presentationTimeUs, 0);
      } else {
        **_printByteBuffer(buffer.data);_**
        codec.queueInputBuffer(inputIndex, 0, buffer.data.limit(), presentationTimeUs, 0);
      }

### [REQUIRED] Link to test content
http://106.13.4.186/h264-sample-test.ts

### [REQUIRED] A full bug report captured from the device
NOT REQUIRED.

### [REQUIRED] Version of ExoPlayer being used
v2.11.3

### [REQUIRED] Device(s) and version(s) of Android being used
Phone android 9;
TV android 5.1.1

**Comment by tonihei** [comment]
Thanks for reporting. 

I far as I can tell, the current ExoPlayer behaviour is according to the [H.264 spec](https://www.itu.int/rec/T-REC-H.264-201906-I). Annex B of the linked doc lists the exact semantics and the NAL unit decoding process. Essentially, all NAL units are delineated by the four bytes 0x00'00'00'01, where the first byte 0x00 is the _trailing_zero_8bits_ element belonging to the previous NAL unit, and the remaining 3 bytes 0x00'00'01 are the _start_code_prefix_one_3bytes_ element that is the beginning of the next NAL unit. Thus, the sample data looks correct to me.

If you think this should be handled in another way, please explain why and how you read this from the spec.

**Comment by tonihei** [comment]
Assuming the request was answered and closing the issue. If not, please reopen.
