### ISSUE TITLE
Clarify Javadoc for DataSpec.httpRequestHeaders

### ISSUE THREAD

**Issue by tifroz** [google/ExoPlayer#7069]
For troubleshooting purposes I am trying to print the request (url, headers) generated by the player. At first glance it seemed like the `TransferListener` hook was build for this very purpose, but I can't get it to show the request headers.

How can I print the header information to the logs? Can you provide some guidance?  My code and output below:

```
TransferListener transferListener = new TransferListener() {
	@Override
	public void onTransferInitializing(DataSource dataSource, DataSpec dataSpec, boolean isNetwork) {
		Log.v(TAG, "OK initializing transfer for " + dataSpec.getHttpMethodString() + " " + dataSpec.uri + ", " + dataSpec.httpRequestHeaders);
	}

	@Override
	public void onTransferStart(DataSource dataSource, DataSpec dataSpec, boolean b) { }

	@Override
	public void onBytesTransferred(DataSource dataSource, DataSpec dataSpec, boolean b, int i) { }

	@Override
	public void onTransferEnd(DataSource dataSource, DataSpec dataSpec, boolean b) { }
};

DefaultHttpDataSourceFactory dataSourceFactory = new DefaultHttpDataSourceFactory("myUserAgent", transferListener);
dataSourceFactory.getDefaultRequestProperties().set("X-Test", "AVALUE");
MediaSource source = new HlsMediaSource.Factory(dataSourceFactory).createMediaSource(mediaUri) ;
```

I would expect to see at least the "User-Agent" & "X-Test" headers in the logs, instead the headers are always empty as shown in the sample output below:

```
OK initializing transfer for GET http://webtv.dev.swishly.com/thru/chuggington-rel-path.m3u8, {}
OK initializing transfer for GET http://webtv.dev.swishly.com/thru/chuggington-data-files/chuggington000.ts, {}
OK initializing transfer for GET http://webtv.dev.swishly.com/thru/chuggington-data-files/chuggington001.ts, {}
OK initializing transfer for GET http://webtv.dev.swishly.com/thru/chuggington-data-files/chuggington002.ts, {}
OK initializing transfer for GET http://webtv.dev.swishly.com/thru/chuggington-data-files/chuggington003.ts, {}
```

**Comment by ojw28** [comment]
`User-Agent` isn't included in the headers you're seeing because, rather than being added into the request `DataSpec`, it's instead added late in the `HttpDataSource` instances. I'm not sure what `X-Test` is or why you'd expect that to be present.

**Comment by ojw28** [comment]
Note that for `User-Agent`, I think your application code will be injecting it via a `DefaultHttpDataSourceFactory` constructor. So you already know what the value is, even if you can't see it in the `TransferListener` callbacks.

**Comment by tifroz** [comment]
Thanks for being so responsive, this is sooooo helpful !!!

As you said, don't really need to know about the `X-Test` and `User-Agent` headers, I already know what they are (I just set them to the code to see if they would show up in the logs). The reason for printing out the headers is to get some information on the headers that are set by the default logic which is abstracted away.

For example, with a plain `DefaultHttpDataSourceFactory` the request for the m3u8 is sent with an `"accept-encoding":"gzip"` header, the request for the content files should have `"accept-encoding":"identity"`. Is there way to figure out what these headers are?

**Comment by tonihei** [comment]
Just to add to the general listener questions - `TransferListener` is probably not the best listener to use for this case. You should be better off using `AnalyticsListener` and listening to `onLoadStarted/Canceled/Completed/Failed` to get all the details. These callbacks also contains both the request and response headers of all loads.

**Comment by tifroz** [comment]
I just tested using `AnalyticsListener`'s `onLoadStarted()` and `onLoadCompleted()` callbacks but no cigar :( In every case, the `loadEventInfo.dataSpec.httpRequestHeaders` is an empty object. 

Note that `loadEventInfo.responseHeaders` is indeed populated in the `onLoadCompleted()` callback, but the request headers still won't show

Code extract below for reference:

```
@Override
    public void onLoadStarted(EventTime eventTime, MediaSourceEventListener.LoadEventInfo loadEventInfo, MediaSourceEventListener.MediaLoadData mediaLoadData) {
        Log.v(TAG, "transfer: "+loadEventInfo.uri+" "+loadEventInfo.dataSpec.httpRequestHeaders);
    }

    @Override
    public void onLoadCompleted(EventTime eventTime, MediaSourceEventListener.LoadEventInfo loadEventInfo, MediaSourceEventListener.MediaLoadData mediaLoadData) {
        Log.v(TAG, "transfer completed: "+loadEventInfo.dataSpec.uri+" "+loadEventInfo.dataSpec.httpRequestHeaders + " " + loadEventInfo.responseHeaders);
    }
```

**Comment by ojw28** [comment]
>  Is there way to figure out what these headers are?

Look at the [source code](https://github.com/google/ExoPlayer/blob/r2.11.3/library/core/src/main/java/com/google/android/exoplayer2/upstream/DefaultHttpDataSource.java#L535). There are only three: `Range`, `User-Agent` and `Accept-Encoding`.

**Comment by tifroz** [comment]
Thanks, I appreciate the guidance! This is helpful yet still provides no reliable way of figuring out what headers & what header values (values for the `Range` header?) are being sent at run time, which would be very useful when troubleshooting with a streaming server that we don't have control over.

I posted this as a question and I don't think I can re-categorized as a bug, but it's probably more accurate to describe it as a such - in particular I think it's pretty clear that `loadEventInfo.dataSpec.httpRequestHeaders` *should not* be empty in the `AnalyticsListener`'s `onLoadStarted ` callback.

**Comment by ojw28** [comment]
You know what the `User-Agent` is because you're passing it into the library yourself. The `Range` and `Accept-Encoding` values are both trivially derived from the `DataSpec`, which the listener does have access to. You can see how to derive these by looking at the source code linked above (i.e., `Range` is derived from `DataSpec.position` and `DataSpec.length`, and `Accept-Encoding` is derived from whether `DataSpec.isFlagSet(DataSpec.FLAG_ALLOW_GZIP)`.

`DataSpec.httpRequestHeaders` is really a mechanism for a `MediaSource` to set additional non-standard headers (e.g., to enable ICY metadata for SHOUTcast streams). It's not intended to specify headers that are already directly defined by structured parts of the `DataSpec`. We should update the documentation to indicate this.
