### ISSUE TITLE
java.io.EOFException: unable to play partially downloaded mp4 file

### ISSUE THREAD

**Issue by brijeshbhatt09** [google/ExoPlayer#7070]
Hi, I am using Exoplayer to play mp4 file from local but when i am trying to play it throws following exception below.
I am playing same file with MediaPlayer then its working fine. I searched alot and found same issue #3351 reported before which i thought may be the case because my file size is also small so after reading the post i checkout the Exoplayer dev-v2-cea and tried to play same file but it throws same exception. 
it only happens in case when i download file from url and before download finish if my download interrupt and file store in local is partially downloaded and then i tried to play partially downloaded content from file otherwise file is playing fine.
please find the file i sent on dev.exoplayer@gmail.com

ExoPlayer Version dev-v2-cea, 2.9.0

Tested on device: Redmi Note4 Android 7.0

```
2020-03-11 15:46:07.324 15149-15149/com.google.android.exoplayer2.demo E/EventLogger: internalError [0.06, 0.00, window=0, period=0, loadError]
    com.google.android.exoplayer2.upstream.FileDataSource$FileDataSourceException: java.io.EOFException
        at com.google.android.exoplayer2.upstream.FileDataSource.open(FileDataSource.java:70)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:147)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:442)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:283)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:844)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:320)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:760)
     Caused by: java.io.EOFException
```

**Comment by tonihei** [comment]
It's not possible to play a partially manually downloaded file in a reliable way. The player will fill its buffer and it reads the file faster than it's being written, it will eventually encounter an EOFException when it tries to read bytes that aren't there yet. 

If you want to download a file and already start playback during the download, you can use ExoPlayer's [download functionality](https://exoplayer.dev/downloading-media.html) that keeps tracks of already downloaded parts of the file. In the case above, ExoPlayer may request the same data online again instead of running into EOFExceptions. If you want to avoid downloading the data twice, I'd recommend to configure the `DefaultLoadControl` to use a small maximum buffer to avoid duplicate downloads.

**Comment by brijeshbhatt09** [comment]
Hi @tonihei ,
Thanks for your input on above issue. I came up with a finding when i am trying to play partially downloaded file its moov atom is missing which might be in the end of file but when i decompress same file to add moov atom at beigning then same file is working fine. But i stucked here because i have large number of files whose moov atom is already at the end of file. So is there any way that Exoplayer can hanlde to play downloaded bytes with missing moov atom. It whould be much helpful if there is any workaround for this problem.

**Comment by tonihei** [comment]
> So is there any way that Exoplayer can hanlde to play downloaded bytes with missing moov atom. 

There is no way to do that given that we need to read the metadata first to know where the sample boundaries are.

> Thanks for your input on above issue. I came up with a finding when i am trying to play partially downloaded file its moov atom is missing which might be in the end of file but when i decompress same file to add moov atom at beigning then same file is working fine. 

As already noted above, you can use ExoPlayer's download functionality. If the end of the file with moov atom isn't downloaded yet, ExoPlayer will just load this part online and then read the rest from the already downloaded data again.

**Comment by Brij09** [comment]
Hi tonihei,

Thanks for the input. I am also curious to know that is there any way that we can get exact number of bytes played by the exoplayer while playing any video.

**Comment by tonihei** [comment]
You can listen to `AnalyticsListener.onLoadFinished/onLoadCanceled/onLoadError` to know how many bytes were loaded for playback. But there is no way I'm aware of that would tell you how many bytes were "played". It's also slightly undefined how you would measure these bytes - is this the encoded video and audio data only? or does it include metadata of the container? etc.

**Comment by tonihei** [comment]
Assuming the question was answered and closing the issue. If not, please reopen.
