### ISSUE TITLE
Switching from Atmos audio to non-atmos midstream in HLS playback causes playback errors

### ISSUE THREAD

**Issue by ScienceIsNeato** [google/ExoPlayer#7072]
When the audio content of a stream transitions from Dolby Atmos (eac3-joc) to regular Dolby Digital Plus in a .m3u8 HLS stream, Exoplayer has errors in playback. The errors include:

- video playback will freeze frame while audio continues playing back normally
- sometimes video unfreezes, which is then out of sync with audio
- sometimes video does not unfreeze and will continue displaying the stuck frame until intervention
- If audio format switches back to Dolby Atmos, sometimes there are extreme audio playback errors (machine-gun stutter sounds)

Using the remote to seek will resolve the problems listed above. 

Here is an example stream that demonstrates the issue: https://content.downlynk.com/a573ae40ee664667adc91beb32394ef2.m3u8?ddp=1&ddpdefault=1&ad=mock_freewheel (note this stream is not expected to exist permanently, but will probably be available at least for a couple months)

The stream above plays back as expected on a variety of other devices (ios, appletv, roku player) and as DASH playback in Exoplayer (.mpd). The only problematic playback is during HLS playback on Exoplayer. Note that I tried to replicate in a virtual player in Android studio, but it appears that you need hardware that supports Dolby Atmos in order to render the eac3-joc audio stream.

**Comment by tonihei** [comment]
Assigning @krocard for investigation.

Note that we can't access a Dolby Atmos enabled device in the near future, so this may need to wait for a while.

**Comment by krocard** [comment]
@ScienceIsNeato Unfortunately, with the current COVID-19 confinement in London, none of the team has access to devices with Dolby Atmos support.
Given the news that the confinement is expected to last for at least a month, (and I suspect probably more), we will probably not be able to look into the issue before this summer I suspect.

**Comment by ScienceIsNeato** [comment]
@krocard that sounds prudent - certainly not an important bug to address in times like these! Stay safe and healthy and I'll check back in when the things get back to some semblance of normalcy

**Comment by krocard** [comment]
@tonihei now that we have a tunneling setup again, there are a few tunneling bugs that should be confirmed, including this one.

**Comment by tonihei** [comment]
@ScienceIsNeato The stream linked above is no longer available. If you still want us to look into this issue, please provide a new link.
