### ISSUE TITLE
GvrAudioProcessor is deprecated but needed.

### ISSUE THREAD

**Issue by lewwns** [google/ExoPlayer#7073]
I'd like to implement spatial sound with ExoPlayer in my project and I found that there's an `ExoPlayer GVR extension` which provides `GvrAudioProcessor` that I can use to make it. But I've realized that it is already deprecated.
Is there any other AudioProcessor that is available to implement as `GvrAudioProcessor` which can provide the rendering of 360 spatial sound in ExoPlayer? Any substitutions? or there might be a need of some minor modifications when overriding `buildAudioProcessors()` ?

Please help me figure this out if you have some ideas. Thanks a lot!

**Comment by andrewlewis** [comment]
I'm afraid we don't have a replacement for this at the moment, though I think it should still work in the current release.
