### ISSUE TITLE
OfflineLicenseHelper does not have customizable DRM session.

### ISSUE THREAD

**Issue by gregmcox** [google/ExoPlayer#7078]
Hello,
Currently, I have the need to customize the load error handling policy for an offline license request. Since the DefaultDrmSession is created within the helper, this is not really possible. I was wondering the rationale behind not exposing the DrmSession during the creation of OfflineLicenseHelper.

I'm in a use-case where I'm unable to modify the base ExoPlayer libraries and extending OfflineLicenseHelper is not possible as it's a final class.

Please let me know if it's a good idea and I'll submit a pull request.

Thanks!

Documentation:
https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/drm/OfflineLicenseHelper.html

**Comment by tonihei** [comment]
There is no particular reason for that. The LoadErrorHandlingPolicy in DrmSessionManager is relatively new, so that's why this wasn't asked before. 

I'll update the class to accept a customized DefaultDrmSessionManager.

**Comment by gregmcox** [comment]
@tonihei, I've created the pull request. Please let me know if it's sufficient.

**Comment by tonihei** [comment]
Thanks for the pull request - as mentioned above I already had a pending change that fixes the problem on our dev branch, so I'll go ahead and merge this one instead. Please give it a try once ready to see if it fixes your issue.

**Comment by gregmcox** [comment]
Thanks for the fast turn around! Could you reference your commit here? I'm not seeing it on the dev-v2 branch.
