### ISSUE TITLE
How to select audio track when there are multiple for the same language?

### ISSUE THREAD

**Issue by casolorz** [google/ExoPlayer#7084]
I think I'm missing something. Right now I'm using this to set the audio language:

```
DefaultTrackSelector.Parameters newParams = trackSelector.getParameters();
newParams = newParams.buildUpon().setPreferredAudioLanguage(language).build();
```

But what if I have stereo and surround for a given language? Passing the ID didn't work. I'm thinking maybe I need to set the maximum number of audio channels? but that seems overly complex, am I misunderstanding something?

Thanks.

**Comment by ojw28** [comment]
Different ways of selecting tracks are documented fairly well in the [DefaultTrackSelector Javadoc](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/trackselection/DefaultTrackSelector.html). It's unclear which track you want to select, and why. It really depends on your use case.

**Comment by casolorz** [comment]
Thank you, that is the info I needed.
