### ISSUE TITLE
Exoplayer not working on android device

### ISSUE THREAD

**Issue by ash-1202** [google/ExoPlayer#7085]
On one of the android devices exoplayer video does not work and gives below exception

`com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.realtek.video.decoder, Format(1, null, video/avc, -1, null, [1280, 720, -1.0], [-1, -1])`

`Caused by: android.media.MediaCodec$CodecException: Failed to initialize OMX.realtek.video.decoder, error 0xfffffff`

Do let know if you have any idea how this can be solved

**Comment by ojw28** [comment]
We need more information to investigate this type of issue. I'll close this one for now. Please file a new one that properly fills in the [bug issue template](https://github.com/google/ExoPlayer/issues/new?assignees=&labels=bug%2C+needs+triage&template=bug.md&title=), including all the requested information, if you want us to take a look.

Please also confirm that the video you're trying to play doesn't exceed the capabilities of the device.
