### ISSUE TITLE
audioFocusChange(-1)

### ISSUE THREAD

**Issue by orcunkobal** [google/ExoPlayer#7089]
Hi,

Sometimes I get an error like this then the player stays pause until I start it. Should I write a custom audio focus manager to handle that? Which way should I follow to resolve this issue?

**dispatching onAudioFocusChange(-1) to android.media.AudioManager@75cbcaacom.google.android.exoplayer2.AudioFocusManager$AudioFocusListener@974509b**

Thank you

**Comment by ojw28** [comment]
I think that probably just means that your app has lost audio focus (presumably because some other app has requested it?). It's correct that the player should be paused when this happens, until you cause it to play again.

**Comment by orcunkobal** [comment]
Yes, I understand. For example, if I open Instagram or youtube my player is pausing. If I close Instagram or youtube then my player is playing. Or If I receive a phone call the same thing happening. But this error occurs even I hadn't opened to any application. I found the onPlaybackSuppressionReasonChanged method but it does not catch my issue. It only returns two things **PLAYBACK_SUPPRESSION_REASON_TRANSIENT_AUDIO_FOCUS_LOSS, PLAYBACK_SUPPRESSION_REASON_NONE**. Actually I want to know when my focus is lost because I want to start again my player

**Comment by ojw28** [comment]
> But this error occurs even I hadn't opened to any application.

To clarify, this is not an error. It's expected that your application may lose audio focus if another app requests it, and your app should not be automatically restarting playback in this case. Something else must be requesting audio focus (either within your own app, or some other app) in order for audio focus to be lost. I wouldn't be surprised if the logcat output tells you what's requesting audio focus, but since you've only provided a single line, it's not possible to tell.

**Comment by orcunkobal** [comment]
I understood. This situation is very bad because I have no idea what should I do when this happened. What is your opinion?

**Comment by ojw28** [comment]
The logcat output from the device should tell you exactly why this is happening. In particular, just before you see the log line where you lose focus, you should see a log line telling you who's requesting focus to take it from you. For example, this logging shows YouTube acquiring audio focus and Spotify losing it as a result:

```
I MediaFocusControl: requestAudioFocus() from uid/pid 10183/5004 clientId=android.media.AudioManager@1753dbaahre@f96246b callingPack=com.google.android.youtube req=1 flags=0x0 sdk=29
D MediaFocusControl: selectFocusStack, uid = 10183, appDevice = 0, device = 2
D AudioManager: requestAudioFocus status : 1
D AudioManager: dispatching onAudioFocusChange(-1) to android.media.AudioManager@f5158b1ghn$2@88ee196
```

If you want help then please provide a more complete version of the logcat output from the device.

**Comment by orcunkobal** [comment]
I checked out my logcat and I didn't see any messages like that. Should I write anything else to see like it? My logchat only gives me an error like this:  **D/AudioManager: dispatching onAudioFocusChange(-1) to android.media.AudioManager@43e7988com.google.android.exoplayer2.AudioFocusManager$AudioFocusListener@b7ef642**

I opened Spotify for trying the same time.  Firstly I'm playing music on my app then I'm playing music on Spotify the exoplayer focusing works well. But, I didn't see any messages about who want to request focus on my app. If I do like that everything works well. But my issue is sometimes it's happened itself and focus not gain again.

ExoVersion: 2.11.1
Extensions: extension-mediasession, extension-okhttp

**Comment by ojw28** [comment]
Please provide a more complete version of the logcat output from the device, if you want us to help.

Knowing what device you're using would also be helpful (and, just in general, providing the information requested in our [issue template](https://github.com/google/ExoPlayer/issues/new?assignees=&labels=bug%2C+needs+triage&template=bug.md&title=)).

**Comment by orcunkobal** [comment]
I/ExoPlayerImpl: Init 4b1433b [ExoPlayerLib/2.11.1] [dreamlte, SM-G950F, samsung, 28]

My device is Samsung Galaxy S8

**Comment by ojw28** [comment]
Marking as needs more info again because more complete logging is still not provided. If you're unable to provide it, we're unable to help.

**Comment by orcunkobal** [comment]
I'm wondering how do you get a message like this?
```
I MediaFocusControl: requestAudioFocus() from uid/pid 10183/5004 clientId=android.media.AudioManager@1753dbaahre@f96246b callingPack=com.google.android.youtube req=1 flags=0x0 sdk=29
D MediaFocusControl: selectFocusStack, uid = 10183, appDevice = 0, device = 2
```
I can't see any message like that can you help me with that? Did you write anything to see it?

**Comment by ojw28** [comment]
It's standard logging in the platform (I'm tried using a Galaxy S8 as well, and do see this logging in logcat). As per above, please provide complete logging as captured from `adb logcat` or `adb bugreport`. If you're unable to help us to help you, then there's not much we can do to help.

**Comment by orcunkobal** [comment]
I exported my logcat reports with ADB. I can see which application wants to request focus my app. I realized something, I have an another music application and it has a widget. When I add the widget to my home screen sometimes the application wants the request focus from the widget. If I don't add the widget I don't get any issue. It is possible to request the focus from the widget? Because I didn't press the click button on the widget. Because the request is running by itself

> 
> 03-23 13:18:45.847 10044 32281 32719 D vol.MediaSessions: updateRemoteControllerH null
> 03-23 13:18:45.847 10044 32281 32719 D vol.MediaSessions: onActiveSessionsUpdatedH n=1
> 03-23 13:18:45.851 10306 16380 16380 W AudioManager: Use of stream types is deprecated for operations other than volume control
> 03-23 13:18:45.851 10306 16380 16380 W AudioManager: See the documentation of requestAudioFocus() for what to use instead with android.media.AudioAttributes to qualify your playback use case
> 03-23 13:18:45.852 10044 32281 32719 D vol.MediaSessions: onActiveSessionsUpdatedH n=1
> 03-23 13:18:45.856  1000  3834  5247 I MediaFocusControl: requestAudioFocus() from uid/pid 10306/16380 clientId=android.media.AudioManager@e029a3ecom.ttnet.muzik.player.Player$1@c0ec09f callingPack=com.ttnet.muzik req=1 flags=0x0 sdk=29
> 03-23 13:18:45.856 10166  5618  5618 I SKBD    : and isTosAccept false
> 03-23 13:18:45.860 10044 32281 32719 D vol.MediaSessions: updateRemoteControllerH null
> 03-23 13:18:45.860 10044 32281 32719 D vol.MediaSessions: onActiveSessionsUpdatedH n=2
> 03-23 13:18:45.865  1000  3834  5247 D MediaFocusControl: selectFocusStack, uid = 10306, appDevice = 0, device = 2
> 03-23 13:18:45.870 10306 16380 16380 D AudioManager: requestAudioFocus status : 1
> 03-23 13:18:45.871 10485  6317  6317 D AudioManager: dispatching onAudioFocusChange(-1) to android.media.AudioManager@1f6cf97com.google.android.exoplayer2.AudioFocusManager$AudioFocusListener@f209584

**Comment by ojw28** [comment]
Right, so this is what's requesting focus:
```
03-23 13:18:45.856 1000 3834 5247 I MediaFocusControl: requestAudioFocus() from uid/pid 10306/16380 clientId=android.media.AudioManager@e029a3ecom.ttnet.muzik.player.Player$1@c0ec09f callingPack=com.ttnet.muzik req=1 flags=0x0 sdk=29
```
and this is what's losing focus as a result:
```
03-23 13:18:45.870 10306 16380 16380 D AudioManager: requestAudioFocus status : 1
03-23 13:18:45.871 10485 6317 6317 D AudioManager: dispatching onAudioFocusChange(-1) to android.media.AudioManager@1f6cf97com.google.android.exoplayer2.AudioFocusManager$AudioFocusListener@f209584
```
If `com.ttnet.muzik.player.Player` is your class, then you need to work out why that class is requesting audio focus when it is. If that's not intentional, you need to fix that. If this class is wrapping a `SimpleExoPlayer` that you've configured to handle audio focus automatically, then it appears you've implemented audio focus handling twice in your application. In that case you should remove your own implementation (or disable focus handling in `SimpleExoPlayer`). Double implementing audio focus will cause your app to compete for focus with itself, which will cause problems.

**Comment by orcunkobal** [comment]
Thank you for the quick answer. But com.ttnet.muzik.player is not my class it is another application like Spotify, not my project.

**Comment by ojw28** [comment]
Does uninstalling that application fix the issue?

**Comment by orcunkobal** [comment]
Yes if I remove the widget who has com.ttnet.muzik.player.Player. But I get messages from our users on google play. They are saying sometimes the app is stopping. That's why I'm wondering if they are having the same problem. Maybe another app not com.ttnet.muzik.player.Player. But I understand, there is nothing I can do. Maybe I ask which media apps use and try to resolve their problems.

**Comment by ojw28** [comment]
I don't think this would be at all specific to your app. Presumably the same widget also causes the vast majority of other music apps (e.g., Spotify) to pause when they shouldn't be pausing as well?

I also don't think this is a widespread issue, since generally applications are well behaved and don't do this kind of thing. I would suggest reporting the issue to the developer of the problematic app, and else doing nothing.

Note that proactively re-requesting audio focus when you lose it is definitely not the right thing to do, since that'll effectively break other audio apps by preventing them from starting playback when the user wants them to.

**Comment by orcunkobal** [comment]
Yes, the same situation is happening on Spotify. I don't any requests if I lost my request focus. Thank you for your help.
