### ISSUE TITLE
TrackSelectionView.getDialog is deprecated . what should i use instead ?

### ISSUE THREAD

**Issue by newtestpage** [google/ExoPlayer#7091]
Hi guys 
I am completely newbie with exoplayer . I want to show the list of quality of hls to user and let the user to choose one of them . I found below code but one part is deprecated in version 2.10. Could someone help me on this case please ? I also tried to find solution on demo app . but there is a lot of code and it make me confused .
```
MappingTrackSelector.MappedTrackInfo mappedTrackInfo = trackSelector.getCurrentMappedTrackInfo();
        if (mappedTrackInfo != null) {
            CharSequence title = "Video";
            int rendererIndex = 2;
            int rendererType = mappedTrackInfo.getRendererType(rendererIndex);
            boolean allowAdaptiveSelections =
                    rendererType == C.TRACK_TYPE_VIDEO
                            || (rendererType == C.TRACK_TYPE_AUDIO
                            && mappedTrackInfo.getTypeSupport(C.TRACK_TYPE_VIDEO)
                            == MappingTrackSelector.MappedTrackInfo.RENDERER_SUPPORT_NO_TRACKS);
            Pair<AlertDialog, TrackSelectionView> dialogPair =
                    TrackSelectionView.getDialog(this, title, trackSelector, rendererIndex);
            dialogPair.second.setShowDisableOption(true);
            dialogPair.second.setAllowAdaptiveSelections(allowAdaptiveSelections);
            dialogPair.first.show();
        }
    }
```

TrackSelectionView.getDialog  is deprecated .Thanks in advance.

**Comment by ojw28** [comment]
Use `TrackSelectionDialogBuilder`.

**Comment by newtestpage** [comment]
> Use `TrackSelectionDialogBuilder`.

Thanks for your response . I changed the code as follow and it shows the dialog but it just contain auto and unknown. however hls has 5 different quality (second code) . 

code 1 :
`private void showMenuQuality() {
        MappingTrackSelector.MappedTrackInfo mappedTrackInfo = trackSelector.getCurrentMappedTrackInfo();
        if (mappedTrackInfo != null) {
            CharSequence title = "Video";
            int rendererIndex = 2;
            int rendererType = mappedTrackInfo.getRendererType(rendererIndex);
            boolean allowAdaptiveSelections =
                    rendererType == C.TRACK_TYPE_VIDEO
                            || (rendererType == C.TRACK_TYPE_AUDIO
                            && mappedTrackInfo.getTypeSupport(C.TRACK_TYPE_VIDEO)
                            == MappingTrackSelector.MappedTrackInfo.RENDERER_SUPPORT_NO_TRACKS);


            TrackSelectionDialogBuilder build = new TrackSelectionDialogBuilder(PlayerActivity.this, title, trackSelector, rendererIndex);

            build.setAllowAdaptiveSelections(allowAdaptiveSelections);
            build.build().show();


        }

    }`


code 2 (stream file ) 
`#EXTM3U
#EXT-X-VERSION:3
#EXT-X-INDEPENDENT-SEGMENTS
#EXT-X-STREAM-INF:BANDWIDTH=3951200,AVERAGE-BANDWIDTH=2961200,CODECS="avc1.4d4028,mp4a.40.2",RESOLUTION=1920x1080,FRAME-RATE=25.000
live_2500.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=2631200,AVERAGE-BANDWIDTH=1861200,CODECS="avc1.4d4028,mp4a.40.2",RESOLUTION=1920x1080,FRAME-RATE=25.000
live_1500.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1971200,AVERAGE-BANDWIDTH=1311200,CODECS="avc1.4d4028,mp4a.40.2",RESOLUTION=1920x1080,FRAME-RATE=25.000
live_1000.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1201200,AVERAGE-BANDWIDTH=1036200,CODECS="avc1.4d401f,mp4a.40.2",RESOLUTION=1280x720,FRAME-RATE=25.000
live_750.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=871200,AVERAGE-BANDWIDTH=761200,CODECS="avc1.4d401f,mp4a.40.2",RESOLUTION=1280x720,FRAME-RATE=25.000
live_500.m3u8`

**Comment by newtestpage** [comment]
I changed the renderindex to 0 and get answer . Thanks
