### ISSUE TITLE
Hls is the subtitle in a video displayed on the screen automatically?

### ISSUE THREAD

**Issue by halilozel1903** [google/ExoPlayer#7092]
I get a video url type hls from the service. There is a subtitle in the url. Can Exoplayer detect this directly? As in AVPlayer, is the subtitle icon placed automatically on the screen?

```
  val bandwidthMeter = DefaultBandwidthMeter()
        
        val dataSourceFactory = DefaultDataSourceFactory(this, Util.getUserAgent(this, "ExoPlayerDemo"), bandwidthMeter)
        
        val videoSource = HlsMediaSource.Factory(dataSourceFactory).createMediaSource(uri)
        
        val textFormat = Format.createTextSampleFormat(null, MimeTypes.TEXT_VTT, Format.NO_VALUE, "en", null)
        
        val subtitleSource = SingleSampleMediaSource.Factory(dataSourceFactory).createMediaSource(subUri, textFormat, C.TIME_UNSET)
        
        return MergingMediaSource(videoSource, subtitleSource)
```
I do as in the example, but the subtitle logo does not appear on the player. 

Can you help me?

**Comment by marcbaechinger** [comment]
To select a subtitle you need to select the text track accordingly. There is [a page around track selection in the developer guide](https://exoplayer.dev/track-selection.html) which gives you initial guidance on track selection. The [javadoc of the DefaultTrackSelector](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/trackselection/DefaultTrackSelector.html) gives some more documentation around this topic.

It should be enough to set the preferred text language to 'en' for your sample code above.

I don't think the UI does automatically show a subtitle icon. I actually think you need to provide such an icon yourself as there is no such icon in the UI module. You can then make the player select a given preferred text language when someone is hitting your icon or set it to null to toggle off subtitles.

If you run your stream with a 'MergingMediaSource' as above in the demo app you can see the tracks in the track selection dialog. This can also help you to figure out how to select text tracks. But selecting the preferred text language should be enough and easy in any case.

**Comment by halilozel1903** [comment]
> To select a subtitle you need to select the text track accordingly. There is [a page around track selection in the developer guide](https://exoplayer.dev/track-selection.html) which gives you initial guidance on track selection. The [javadoc of the DefaultTrackSelector](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/trackselection/DefaultTrackSelector.html) gives some more documentation around this topic.
> 
> It should be enough to set the preferred text language to 'en' for your sample code above.
> 
> I don't think the UI does automatically show a subtitle icon. I actually think you need to provide such an icon yourself as there is no such icon in the UI module. You can then make the player select a given preferred text language when someone is hitting your icon or set it to null to toggle off subtitles.
> 
> If you run your stream with a 'MergingMediaSource' as above in the demo app you can see the tracks in the track selection dialog. This can also help you to figure out how to select text tracks. But selecting the preferred text language should be enough and easy in any case.

The text format field will come from the service. For example English and French. What kind of path can I follow when I have more than one language option? I couldn't find a similar example on GitHub.

**Comment by marcbaechinger** [comment]
Sorry, I'm not sure whether I understand the question. Please correct me if I go in the wrong direction.

For creating a `MergingMediaSource` with a media stream and two text tracks you need the mediaUri and two subtitle uris with the corresponding subtitle format info and the languages. With that you can create a `MergingMediaSource`.

If you setup the mergin media source with that you have at least one video track, one audio track and two text tracks. Each text track has a language according to what you passed to `Format.createTextSampleFormat`.

You can only select one text track at the same time, so it should be possible to create a UI for the user to choose either en or fr and then call the track selector accordingly:

```
DefaultTrackSelector.Parameters parameters =
        trackSelector.buildUponParameters().setPreferredTextLanguage("en").build();
trackSelector.setParameters(parameters);
```

**Comment by ojw28** [comment]
I think this issue is about when subtitles are included directly in the HLS stream (i.e., `MergingMediaSource` is not required).

Yes, ExoPlayer should be able to detect these subtitles directly. Please try loading your stream into the ExoPlayer demo app and verifying that it's possible to select text tracks under the "Select tracks" button. If that works, ExoPlayer supports it (building the type of UI that you want is up to you, however). If it doesn't work, please provide the stream URL so we can take a look at why.

**Comment by halilozel1903** [comment]
@ojw28 Apple uses AVPlayer. This video player finds the subtitle itself. He puts the subtitle icon himself.I don't really understand why ExoPlayer doesn't do the same thing itself. When I play a hls video it doesn't show subtitles. There are two subtitles in the link. One is English and the other is French. I really did not understand how to use this without using MergingMediaSource.

**Comment by ojw28** [comment]
As above:

> Please try loading your stream into the ExoPlayer demo app and verifying that it's possible to select text tracks under the "Select tracks" button. If that works, ExoPlayer supports it (building the type of UI that you want is up to you, however). If it doesn't work, please provide the stream URL so we can take a look at why.

**Comment by marcbaechinger** [comment]
Closed due to lack of activity. Please reopen if required.
