### ISSUE TITLE
Streaming mp2 contained aac over WebSockets

### ISSUE THREAD

**Issue by ghost** [google/ExoPlayer#7093]
Hello all,
I have question that I am streaming data through http which contains audio format mp2 container and aac encode while running this type of audio data then exoplayer gives clean sound.But when I try to take this data through websocket then exoplayer doesnt play.Need help

**Comment by marcbaechinger** [comment]
I'm happy to help as much as I can.

What `DataSource` are you using for accessing the data over websockets? I'm not sure whether I am aware of what I would use for such a case.

And even more important: Can you please provide a bug report that you have taken just after you tried to play the mp2 file over websockets?

**Comment by ghost** [comment]
Hello Marc thanks for your response currently bytearray is coming from websocket so I am thinking to give data source as bytearray 

Actually I am playing raw pcm data using AudioTrack through websocket so it is giving me clean audio quality ok so when I am receiving some encoder contained data through websocket then my AudioTrack play audio but it has 30 sec latency so the data receiving at websocket is of aac encoded and mp3 container using ffmpeg this type of data AudioTrack can decode but it takes 30sec approx and then play so we can say that latency of 30 sec we need to reduce latency as pcm data run as it is on Android device which has no latency .... And about bug exoplayer gives unknown source error

**Comment by marcbaechinger** [comment]
Thanks for the further explanation. 

It would really be helpful if you can [take a bug report](https://developer.android.com/studio/debug/bug-report) right after you tried to play with ExoPlayer. Ideally you have an EventLogger added to ExoPlayer so I can see what is going on internally. 

Without some decent log output it may be very hard for me to understand what you are trying to achieve.

**Comment by ghost** [comment]
hello marc here is my code and logs 

code :

when I receive byte array in websocket then following is my code

```
   @Override
            public void onBinaryReceived(byte[] data) {
                Log.e("onBinaryReceived",""+data);
                try{
                  dataa =  createMediaSourceFromByteArray(data);
                  Log.e("data",""+dataa);
                  runOnUiThread(new Runnable() {
                      @Override
                      public void run() {
                          initplayerExo(dataa);
                      }
                  });
}
```
function to create bytearray data source is 
```
 private MediaSource createMediaSourceFromByteArray(byte[] data) {
        ByteArrayDataSource byteArrayDataSource = new ByteArrayDataSource(data);
        Uri bytesUri = Uri.parse("byte:///audio");
        DataSpec dataSpec = new DataSpec(bytesUri);
        try {
            byteArrayDataSource.open(dataSpec);
        } catch (IOException e) {
            e.printStackTrace();
        }

        DataSource.Factory factory = new DataSource.Factory() {
            @Override
            public DataSource createDataSource() {
                return byteArrayDataSource;
            }
        };

        MediaSource mediaSource = new ExtractorMediaSource.Factory(factory)
                .setExtractorsFactory(new DefaultExtractorsFactory())
                .createMediaSource(byteArrayDataSource.getUri());

        return mediaSource;
    }
```

and function for playing exoplayer
```
 public void initplayerExo(MediaSource mediaSource){
       player.setPlayWhenReady(true);
       player.prepare(mediaSource, true, false);
    }
```



And logs getting to me 

```
2020-03-17 12:50:40.020 10373-10510/com.example.radiogo E/onBinaryReceived: [B@bc9e21b
2020-03-17 12:50:40.020 10373-10510/com.example.radiogo E/data: com.google.android.exoplayer2.source.ExtractorMediaSource@3bbafb8
2020-03-17 12:50:40.033 10373-10513/com.example.radiogo E/ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor, AmrExtractor, Ac4Extractor) could read the stream.
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractorHolder.selectExtractor(ProgressiveMediaPeriod.java:1095)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:974)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:391)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
2020-03-17 12:50:40.033 10373-10510/com.example.radiogo E/onBinaryReceived: [B@580f64
2020-03-17 12:50:40.034 10373-10510/com.example.radiogo E/data: com.google.android.exoplayer2.source.ExtractorMediaSource@58735cd

```

**Comment by marcbaechinger** [comment]
The `UnrecognizedInputFormatException` suggests that the data the player is receiving from the byte array data source is not recognized by any of the extractors to be a supported format.

I think you need to validate what data is read from the data source and make sure this is a valid media format.

**Comment by ghost** [comment]
Hello marc could you please give some details about this
  How can we debug Exoplayer  in-depth. We want to know how internally depacketization, decryption … works.
please give some feedback for above mentioned issue

Marc for validation of data read from source is we are reading aac encoder data with mp2 compression is this audio is playable in android ? 

My next observation is when I run aac encoder data with mp3 compression then exoplayer doesnt give any exception it tries to play audio but sound is not generating.But when I use AudioTrack class instead of exoplayer then it is going to play audio but having 30 sec latency.

**Comment by marcbaechinger** [comment]
When you are using the `ProgressiveMediaSource` it uses the `DefaultExtractorsFactory`. The `DefaultExtractorsFactory` creates a number of `Extractor`s [which sniff the start of a stream](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/source/ProgressiveMediaPeriod.java#L1067)  and try to infer the type of the stream. If none of the extractors recognise the stream an `UnrecognizedInputFormatException` is thrown. 

So if you are using an `ByteArrayDataSource` it expects an array of bytes which represents such a media stream. The array you construct must be valid media. I think you could test this by first downloading it with websockets, write the bytes into to a file. Now you should be able to play that file with ExoPlayer (or another media player).  Once this works you can directly download and construct the byte array (you can probably also verify again that the bytes of the array is identical with the file you've created before).

So I would recommend these steps:

1. Download with websockets and create a file. Play that file with ExoPayer
2. Download with websockets and create a byte array. Compare that byte array with the file above (in case that plays fine with ExoPlayer)
3. Download with websockets and create a ByteArrayDataSource with it.

> when I run aac encoder data with mp3 compression then exoplayer doesnt give any exception

Can you send me a url to that file? I'm not sure I understand what aac with mp3 compression means.  My understanding is that [aac is a sample format while mp3 is a mixture of container/sample format](https://exoplayer.dev/supported-formats.html). So it is either aac in eg. a mp4 container or mp3. Best would be to send me a uri so I can try to play it myself.  

(Aside: The ExtractorMediaSource you are using is deprecated, so I recommend updating to the newest ExoPlayer version and using `ProgressiveMediaSource` instead)

**Comment by marcbaechinger** [comment]
Closed due to lack of activity. Please reopen if required.
