### ISSUE TITLE
Can I Run ExoPlayer In Docker?

### ISSUE THREAD

**Issue by matanmarciano** [google/ExoPlayer#7094]
Hello everyone,
Can I use ExoPlayer i docker? 
To run it on any PC and manage it by Kubernetes?

Thank you!

**Comment by marcbaechinger** [comment]
ExoPlayer is running on Android using the Android media framework. The Android media framework is using media codecs which are provided by the hardware vendor. I think that could be the challenge for you.

ExoPlayer runs in the Android emulator on a PC or OSX. So it can run on a platform like PC or a mac. I think this is still not a virtualized environment you probably want.

I'm afraid that I can not give you more support on that topic as we actually support ExoPlayer as an Android media player here in this issue tracker.
