### ISSUE TITLE
Exoplayer seekto not work when playing ad video

### ISSUE THREAD

**Issue by EddieMeng** [google/ExoPlayer#7096]
### [REQUIRED] 
I already checked all the issues related to my question here, but looks like others didn't encounter this question. In addiction, i also check the source code of exoplayer, but fail to solve my question. 

### [REQUIRED] Question
It is possible to call seekTo() when play advertisement video? when develop my android tv app, i found a problem hard to resolve,  if user click home button in tv remote control when the player is playing ad, then my app go to background. Then, if user resume my app, i want user watch ad video from where he leave instead of from beginning. But since when my app go to background, i need release the player, and when resume, i need initialize player again. **I found seek to is not work when playing ad video, while it is fine when playing video content. So, is it possible to seekTo() when play advertisement video?**

<img width="780" alt="Screen Shot 2020-03-17 at 17 48 42" src="https://user-images.githubusercontent.com/14977785/76844353-1e2f4500-6878-11ea-984f-c7657cdcff51.png">

I check the source code and found the if condition, **is it not allow seek to when playing video ad by design**? if that so, what is the reason for that, and **if the new version of exoplayer allow to do that?
thanks for help.**

**Comment by marcbaechinger** [comment]
Yes, seeking within ads is not possible. The code snippet you are pointing at shows, that any attempt to seek starts from the begin of the ad period.

I don't think that this will change in a future release of ExoPlayer.

**Comment by EddieMeng** [comment]
I got it, thanks for your help

**Comment by EddieMeng** [comment]
> Yes, seeking within ads is not possible. The code snippet you are pointing at shows, that any attempt to seek starts from the begin of the ad period.
> 
> I don't think that this will change in a future release of ExoPlayer.

I got it, thanks for your help

**Comment by marcbaechinger** [comment]
Ok. thank you. I'm closing this issue. Feel free to re-open if needed.
