### ISSUE TITLE
onRenderedFirstFrame is called after seeking in live progressive

### ISSUE THREAD

**Issue by stari4ek** [google/ExoPlayer#7097]
### [REQUIRED] Searched documentation and issues
Documentation reference:
```java
  /**
   * Called when a frame is rendered for the first time since setting the surface, and when a frame
   * is rendered for the first time since a video track was selected.
   */
  default void onRenderedFirstFrame() {}
```

### [REQUIRED] Question
I'm getting `onRenderedFirstFrame` after seeking in buffered live progressive. Same result with `seekTo` (to the head - `minPlayabackBufferMs`) and `seekToDefaultPosition`.

```
12:40:05.216D/TimeShiftInMemory: Seeking to: 12:40:03.721 (pos: 275.94). Buffered: 280.94
12:40:05.218D/EventLogger: seekStarted [eventTime=282.20, mediaPos=212.73, window=0, period=0]
12:40:05.226D/EventLogger: positionDiscontinuity [eventTime=282.21, mediaPos=275.94, window=0, period=0, SEEK]
12:40:05.318D/EventLogger: positionDiscontinuity [eventTime=282.30, mediaPos=0.00, window=0, period=0, SEEK_ADJUSTMENT]
12:40:05.325D/EventLogger: state [eventTime=282.30, mediaPos=0.00, window=0, period=0, BUFFERING]
12:40:05.345D/EventLogger: seekProcessed [eventTime=282.33, mediaPos=0.00, window=0, period=0]
12:40:06.568D/EventLogger: renderedFirstFrame [eventTime=283.54, mediaPos=281.77, window=0, period=0, Surface(name=null)/@0xad1e4c]
12:40:06.588D/EventLogger: state [eventTime=283.57, mediaPos=281.77, window=0, period=0, READY]
```

Is it expected behavior? Cause it does not match description from `onRenderedFirstFrame`. Or it's due missing implementation for https://github.com/google/ExoPlayer/issues/6562 ?

### A full bug report captured from the device
* https://drive.google.com/open?id=1EEYH0BmvWU0qiBmPSU3W5g7WocREBfAW

### Link to test content
it's live http progressive. I don't think that it's related to specific stream

**Comment by marcbaechinger** [comment]
I think this is working as intended. Can you elaborate why you think the documentation of `onRenderedFirstFrame()` is not matching the behaviour you see?

I'm a bit confused around the mediaPos=0.00 which shows up in your logs above from BUFFERING and then goes back to 281.77 (if you think this is relevant, can you send me the uri to the media?).

However, my understanding of `seekProcessed` is, that the player has selected the next period to be played and updated the public playback position accordingly. No data is necessarily downloaded at this point and when needed this starts after updating the playback position. Rendering the next frame is then done by the render component. It obviously needs data first for rendering and this can only happen after updating the playback position which needs to be known before.

When I looked into this on my device the log was as follows:

```
D/EventLogger: loading [eventTime=27.31, mediaPos=86.83, window=0, period=0, true]
D/EventLogger: state [eventTime=27.31, mediaPos=86.83, window=0, period=0, BUFFERING]
D/EventLogger: isPlaying [eventTime=27.31, mediaPos=86.83, window=0, period=0, false]
D/EventLogger: seekProcessed [eventTime=27.31, mediaPos=86.83, window=0, period=0]
D/EventLogger: renderedFirstFrame [eventTime=28.30, mediaPos=86.83, window=0, period=0, Surface(name=null)/@0xc223ee3]
```

It shows that the first four events are issued at the very same event time. They have been notified in the same listener iteration as we call this. The the renderFirstFrame event happens at eventTime 28.30 which is not in the same iteration as the other events because, it is issued by the renderer after the data has been made available.

Does this make sense? Please let me know if you think the documentation is misleading.

**Comment by ojw28** [comment]
I think the point is that seeking doesn't fall into either of the cases that the documentation says the event is fired for:

1. Called when a frame is rendered for the first time since setting the surface - Not true
1. and when a frame is rendered for the first time since a video track was selected - Also not true

It's worth noting that the same method in both `AnalyticsListener` and `VideoRendererEventListener` is documented differently, and more accurately, so we probably just need to update the `VideoListener` documentation to say the same thing?

**Comment by stari4ek** [comment]
> I think this is working as intended. Can you elaborate why you think the documentation of onRenderedFirstFrame() is not matching the behaviour you see?

Since it's the same stream, and first frame was rendered already (and notified with `onRenderedFirstFrame` ) and it's the same surface (_"since setting the surface"_) with same tracks selected (_"since a video track was selected"_). At least as exoplayer (`SimpleExoPlayer`) client I performed seek only.

> I'm a bit confused around the mediaPos=0.00 which shows up in your logs above from BUFFERING and then goes back to 281.77 (if you think this is relevant, can you send me the uri to the media?).

It happens cause of seeking. I thought that this one is normal cause of https://github.com/google/ExoPlayer/issues/6562

> However, my understanding of seekProcessed is, that the player has selected the next period to be played and updated the public playback position accordingly. No data is necessarily downloaded at this point and when needed this starts after updating the playback position.

In my case it worked totally different - cause current position was 0 when I checked it from `seekProcessed()` - i was going to adjust "expected position after seek" to real one.

Please note, that my stream is http progressive. Live (`isCurrentWindowLive()`) and not-seekable (`isCurrentWindowSeekable()`). 
This is multicast mpeg-ts stream which goes through `udpxy` (udp to http proxy). It's in private network from my internet provider - so I cannot expose share it with you.

Here is log when playback is started:
```
22:40:54.343 volume [eventTime=57.38, mediaPos=53.48, window=0, period=0, 0.0]
22:40:54.384 timeline [eventTime=57.42, mediaPos=0.00, window=0, periodCount=0, windowCount=0, reason=PLAYLIST_CHANGED
22:40:54.387 ]
22:40:54.420 tracks [eventTime=57.46, mediaPos=0.00, window=0, []]
22:40:54.454 loading [eventTime=57.48, mediaPos=0.00, window=0, false]
22:40:54.465 state [eventTime=57.50, mediaPos=0.00, window=0, IDLE]
22:40:54.476 isPlaying [eventTime=57.51, mediaPos=0.00, window=0, false]
22:40:54.739 surfaceSize [eventTime=57.77, mediaPos=0.00, window=0, period=0, 0, 0]
22:40:54.927 surfaceSize [eventTime=0.00, mediaPos=0.00, window=0, -1, -1]
22:40:54.929 volume [eventTime=0.00, mediaPos=0.00, window=0, 0.0]
22:40:54.930 playWhenReady [eventTime=0.01, mediaPos=0.00, window=0, true, USER_REQUEST]
22:40:54.941 timeline [eventTime=0.02, mediaPos=0.00, window=0, periodCount=1, windowCount=1, reason=PLAYLIST_CHANGED
22:40:54.941   period [?]
22:40:54.942   window [?, false, true]
22:40:54.942 ]
22:40:54.944 state [eventTime=0.02, mediaPos=0.00, window=0, BUFFERING]
22:40:55.007 mediaPeriodCreated [eventTime=0.08, mediaPos=0.00, window=0, period=0]
22:40:55.018 loading [eventTime=0.09, mediaPos=0.00, window=0, period=0, true]
22:40:55.023 timeline [eventTime=0.10, mediaPos=0.00, window=0, period=0, periodCount=1, windowCount=1, reason=SOURCE_UPDATE
22:40:55.024   period [?]
22:40:55.030   window [?, false, false]
22:40:55.032 ]
22:40:55.575 timeline [eventTime=0.65, mediaPos=0.00, window=0, period=0, periodCount=1, windowCount=1, reason=SOURCE_UPDATE
22:40:55.582   period [?]
22:40:55.588   window [?, false, false]
22:40:55.601 ]
22:40:55.761 decoderEnabled [eventTime=0.83, mediaPos=0.00, window=0, period=0, video]
22:40:55.790 decoderEnabled [eventTime=0.86, mediaPos=0.00, window=0, period=0, audio]
22:40:55.801 tracks [eventTime=0.87, mediaPos=0.00, window=0, period=0, 
22:40:55.802   Renderer:0 [
22:40:55.806     Group:0, adaptive_supported=N/A [
22:40:55.830       [X] Track:0, id=203/301, mimeType=video/avc, codecs=avc1.640028, res=1920x1080, supported=YES
22:40:55.836     ]
22:40:55.842   ]
22:40:55.846   Renderer:1 [
22:40:55.849     Group:0, adaptive_supported=N/A [
22:40:55.870       [X] Track:0, id=203/302, mimeType=audio/mp4a-latm, codecs=mp4a.40.2, channels=2, sample_rate=48000, language=ru, supported=YES
22:40:55.872     ]
22:40:55.874   ]
22:40:55.893   Renderer:3 [
22:40:55.899     Group:0, adaptive_supported=N/A [
22:40:55.910       [ ] Track:0, id=203/8493, mimeType=application/cea-608, supported=YES
22:40:55.912     ]
22:40:55.915   ]
22:40:55.916 ]
22:40:56.064 mediaPeriodReadingStarted [eventTime=1.14, mediaPos=0.00, window=0, period=0]
22:40:56.093 downstreamFormat [eventTime=1.16, mediaPos=0.00, window=0, period=0, id=203/301, mimeType=video/avc, codecs=avc1.640028, res=1920x1080]
22:40:56.258 decoderInitialized [eventTime=1.33, mediaPos=0.00, window=0, period=0, video, OMX.amlogic.avc.decoder.awesome]
22:40:56.281 decoderInputFormat [eventTime=1.35, mediaPos=0.00, window=0, period=0, video, id=203/301, mimeType=video/avc, codecs=avc1.640028, res=1920x1080]
22:40:56.287 downstreamFormat [eventTime=1.36, mediaPos=0.00, window=0, period=0, id=203/302, mimeType=audio/mp4a-latm, codecs=mp4a.40.2, channels=2, sample_rate=48000, language=ru]
22:40:56.475 decoderInitialized [eventTime=1.55, mediaPos=0.00, window=0, period=0, audio, OMX.google.aac.decoder]
22:40:56.475 decoderInitialized [eventTime=1.55, mediaPos=0.00, window=0, period=0, audio, OMX.google.aac.decoder]
22:40:56.501 decoderInputFormat [eventTime=1.58, mediaPos=0.00, window=0, period=0, audio, id=203/302, mimeType=audio/mp4a-latm, codecs=mp4a.40.2, channels=2, sample_rate=48000, language=ru]
22:40:56.661 audioSessionId [eventTime=1.71, mediaPos=0.00, window=0, period=0, 1881]
22:40:56.800 videoSize [eventTime=1.88, mediaPos=0.00, window=0, period=0, 1920, 1080]
22:40:56.884 renderedFirstFrame [eventTime=1.95, mediaPos=0.00, window=0, period=0, Surface(name=null)/@0x6d104ad]
22:40:57.087 state [eventTime=2.16, mediaPos=0.18, window=0, period=0, READY]
22:40:57.181 isPlaying [eventTime=2.26, mediaPos=0.28, window=0, period=0, true]
```

Paused:
```
22:43:54.304 playWhenReady [eventTime=179.38, mediaPos=177.40, window=0, period=0, false, USER_REQUEST]
22:43:54.307 isPlaying [eventTime=179.38, mediaPos=177.41, window=0, period=0, false]
```

Wait till there will be +90 sec of buffered data (compared to current pos). Unpause:

```
2020-03-17 22:45:43.524 2883-2883/by.stari4ek.tvirl.debug D/EventLogger: playWhenReady [eventTime=288.60, mediaPos=177.41, window=0, period=0, true, USER_REQUEST]
2020-03-17 22:45:43.526 2883-2883/by.stari4ek.tvirl.debug D/EventLogger: isPlaying [eventTime=288.60, mediaPos=177.43, window=0, period=0, true]
```

Seek:
```
22:46:18.974 seekStarted [eventTime=324.05, mediaPos=212.83, window=0, period=0]
22:46:18.982 positionDiscontinuity [eventTime=324.06, mediaPos=322.05, window=0, period=0, SEEK]
22:46:19.079 positionDiscontinuity [eventTime=324.15, mediaPos=0.00, window=0, period=0, SEEK_ADJUSTMENT]
22:46:19.082 state [eventTime=324.16, mediaPos=0.00, window=0, period=0, BUFFERING]
22:46:19.111 isPlaying [eventTime=324.19, mediaPos=0.00, window=0, period=0, false]
22:46:19.117 seekProcessed [eventTime=324.19, mediaPos=0.00, window=0, period=0]
22:46:20.150 renderedFirstFrame [eventTime=325.23, mediaPos=323.58, window=0, period=0, Surface(name=null)/@0x6d104ad]
22:46:20.276 state [eventTime=325.35, mediaPos=323.58, window=0, period=0, READY]
22:46:20.309 isPlaying [eventTime=325.38, mediaPos=323.61, window=0, period=0, true]
```

I've debuged a bit MSG_SEEK_TO, and there is:

stopRenderers()
...
resetRendererPosition(0)
at
```
seekToPeriodPosition:972, ExoPlayerImplInternal (com.google.android.exoplayer2)
seekToPeriodPosition:959, ExoPlayerImplInternal (com.google.android.exoplayer2)
seekToInternal:940, ExoPlayerImplInternal (com.google.android.exoplayer2)
handleMessage:387, ExoPlayerImplInternal (com.google.android.exoplayer2)
dispatchMessage:101, Handler (android.os)
loop:164, Looper (android.os)
run:65, HandlerThread (android.os)
```
So it produces both artifacts during seek (jumping pos and additional "first frame")

**Comment by stari4ek** [comment]
@ojw28 , you're correct. Documentation in `AnalyticsListener` describes it in the way it works

**Comment by marcbaechinger** [comment]
Ok, thanks for clarification. I was confused and thought it's about the sequence in which the callbacks are called.

I'll correct the the documentation in `VideoListener` to make the docs consistent.
