### ISSUE TITLE
Decode with MediaRecorder API

### ISSUE THREAD

**Issue by ppamorim** [google/ExoPlayer#710]
Libstreaming can encode with MediaRecorder with an API lower than 16 because this uses a little hack to use the encoder with videos. Can we implement that solution here?

https://github.com/fyhertz/libstreaming/blob/master/src/net/majorkernelpanic/streaming/MediaStream.java
https://github.com/fyhertz/libstreaming/blob/2343e3ad16fc394ed54f05d705b2eaa7d19f0696/src/net/majorkernelpanic/streaming/video/VideoStream.java

**Comment by Ood-Tsen** [comment]
@ppamorim ,  a [MediaMuxer](https://developer.android.com/reference/android/media/MediaMuxer.html) version of ExoPlayer ?

**Comment by ojw28** [comment]
I don't understand what this is requesting either.

**Comment by ppamorim** [comment]
@ojw28 This is a little trick to encode the data with MediaRecorder API. Look here: https://github.com/fyhertz/libstreaming#encoding-with-the-mediarecorder-api

**Comment by ojw28** [comment]
That library looks like it has very different goals (encoding + preview from camera). ExoPlayer is a decoding + playback library. MediaRecorder does not provide decoding functionality, so how do you propose we decode on API levels prior to those that make the decoders available from MediaCodec?

**Comment by ppamorim** [comment]
@ojw28, sorry for this confusion, I'll review an another alternative.

**Comment by ppamorim** [comment]
@ojw28 It's possible to decode with FFmpeg?

**Comment by ojw28** [comment]
Yes, it's possible to hook a software decoder such as ffmpeg into ExoPlayer to decode on earlier API levels. The [extensions](https://github.com/google/ExoPlayer/tree/master/extensions) directory has two examples for vp9 and opus. We have no plans to support further extensions onto software decoders ourselves, so you'd need to implement your own extension if you wanted to bridge onto something like ffmpeg. It's also unclear what kind of performance you'd be able to achieve with this approach. You should also be aware of ffmpeg's [legal considerations](https://www.ffmpeg.org/legal.html)., on which we cannot advise.
