### ISSUE TITLE
Seeking 'infinite' streams

### ISSUE THREAD

**Issue by nicolausYes** [google/ExoPlayer#7103]
### [REQUIRED] Searched documentation and issues
https://exoplayer.dev/progressive.html
https://github.com/google/ExoPlayer/issues/4917

### [REQUIRED] Question
I use ExoPlayer for playing media, some of them include 'infinite' radio streams. I need to provide seek support for them, even it's not exact and not efficient.
I use ProgressiveMediaSource and provide the input data via DataSource implementation (obtaining data and caching is completely on the application side).
In most of the cases, it works with enabled constant bitrate seeking, but in some cases, it doesn't.

For example, TsExtractor uses an implementation of BinarySearchSeeker, so it reads the beginning and the end of the stream for seeking. The duration/size is constantly growing and ExoPlayer caches the duration on opening.

I tried to reopen cache on seeking event, so ExoPlayer can reindex existing cache and seek in the position, but it doesn't seem to work as expected (ExoPlayer still gives the wrong duration).

I understand ExoPlayer doesn't support that, but any recommendation how can it be achieved in a reasonable way?

**Comment by marcbaechinger** [comment]
I assume with infinite streams you are referring to progressive live streams.
I think it is still valid what is said in #4917, which means that this is not supported I'm afraid. 

I don't think I can give you some sensible recommendations, as making this work in a reasonable way doesn't seem trivial or an easy thing to do.

There is another issue which is marked as enhancement which goes in a similar direction: #6562
