### ISSUE TITLE
Actions button in pip mode is not showing 

### ISSUE THREAD

**Issue by newtestpage** [google/ExoPlayer#7107]
Hi 
I implemented pip mode for my exoplayer . Everything works fine but I have a problem with action buttons . they didn't show in pip mode . I don't know is related or not but I overwrite  the exo_playback_control_view.xml . also I   set this code on when pipButton Clicked         `            playerView.hideController();
`

I made a MediaSession like follow code in My initializePlayer() :
`MediaSessionCompat mediaSessionCompat = new MediaSessionCompat(PlayerActivity.this,TAG);
            MediaSessionConnector connector = new MediaSessionConnector(mediaSessionCompat);
            connector.setPlayer(player);
`
but nothing changed yet . Could someone help me on this case What should I do to show the play pause button and also I have mute button and I want to show it also . 
Thanks in advance .

**Comment by marcbaechinger** [comment]
When in PIP mode you should hide all UI of the player. The system will place a UI on top of the PIP window. When PIP mode has been started your callback `onPictureInPictureModeChanged` will be called and you can call `setUseController(/* useController= */ false)`. When pip mode is exited you can call `setUseController(/* useController= */ true)` again.

As mentioned, the system will place the UI on top of the PIP window.  I don't think you can place custom buttons in a PIP window. So I think a mute button is not possible. The user can mute the media volume on a system level though (like hardware volume buttons).

If an app has an active media session, then play, pause, next, and previous controls will appear. I think you code is ok but you need to activate the media session:

```
MediaSessionCompat mediaSessionCompat = new MediaSessionCompat(PlayerActivity.this,TAG); 

mediaSessionCompat.setActive(true);

MediaSessionConnector connector = new MediaSessionConnector(mediaSessionCompat);
connector.setPlayer(player);
```

Please find more details here: https://developer.android.com/guide/topics/ui/picture-in-picture#java

**Comment by newtestpage** [comment]
Hi Thanks for your response . I tried to add mute and play button with actionRequest and I did it .play and pause button work properly | onPlayerStateChanged | . my problem is with mute button when I click on it it make the player mute but it didn't change the icon of remoteaction . i should to change playerstate  then mute icon will change . Is it possible to add volume listener on exoplayer and this listener to player?
