### ISSUE TITLE
Functionality to acquire DRM licenses before playback

### ISSUE THREAD

**Issue by dextergk** [google/ExoPlayer#712]
This is more of a question. Now ExoPlayer tries to acquire licenses 'on-the-fly' or POST the playback has been initiated for both playready and widevine. Is there any plan to add functionality to acquire and may be store licenses before initiation of playback (PRE delivery)?
This feature is essential especially while subscribing to a music service, with pre-delivery the user need not wait for license acquisition for each song.

Thanks!
Dex

**Comment by ojw28** [comment]
You could implement your own DrmSessionManager to do this kind of thing. It's not something we're planning to support directly.

I'd be surprised if music services are using (or are required to use) full Widevine/PlayReady DRM, as opposed to simply relying on authentication + HTTPS to secure the data over the wire. Given there's no secure audio path, I'm not really sure what additional benefit full DRM gives you for the streaming case. For the offline case, you'd need to implement your own DrmSessionManager anyway.

**Comment by dextergk** [comment]
Thanks for your reply!
