### ISSUE TITLE
Request for android X

### ISSUE THREAD

**Issue by renesotolira** [google/ExoPlayer#7121]
Compatibility with android x dependencies

**Comment by marcbaechinger** [comment]
Please apologize me being not well educated regarding androidx. What compatibilities with androidx would you like to see and what incompatibilities did you notice?

Can you give me some more details so I can report accordingly?

**Comment by reneciokaigen** [comment]
![Captura de Pantalla 2020-03-22 a la(s) 22 13 52](https://user-images.githubusercontent.com/11642446/77280626-7906d900-6c8a-11ea-9c77-9018fec78450.png)

**Comment by renesotolira** [comment]
![Captura de Pantalla 2020-03-22 a la(s) 22 14 50](https://user-images.githubusercontent.com/11642446/77280675-9045c680-6c8a-11ea-8021-e45c1cd37cf7.png)

**Comment by marcbaechinger** [comment]
Thanks! I can't find a `newSimpleInstance` method which does not have the `Context` as the first parameter. In general I'd recommend using `SimpleExoPlayer.Builder` which is less confusing and easier to use than the factory with that many newXyz factory methods.

It is still not clear to me how this relates to androidx compatibility. If you want to tell me something about it, I'd politely ask you to become a bit more verbose.

**Comment by marcbaechinger** [comment]
Closed due to lack of activity.
