### ISSUE TITLE
error: method does not override or implement a method from a supertype

### ISSUE THREAD

**Issue by seyinator** [google/ExoPlayer#7123]
I looked everywhere and I couldn't find a solution for this error. I'm using ExoPlayer.

> error: method does not override or implement a method from a supertype

Android Studio highlights the 8 `@Override`s.
`AdaptiveMediaSourceEventListener`s methods are underlined red.
**onTimelineChanged** is underlined red
**onPositionDiscontinuity** is underlined red
MainActivity:
    `
   

    //http://mos.rusiptv.net:8080/live/@celalsonat/784512/94815.m3u8

    public class MainActivity extends AppCompatActivity implements ExoPlayer.EventListener {

    private SimpleExoPlayerView simpleExoPlayerView;
    private String hlsVideoUri = 
    "http://mos.rusiptv.net:8080/live/@celalsonat/784512/94815.m3u8";
    private SimpleExoPlayer player;
    private ProgressBar progressBar;

    @Override
     protected void onCreate(Bundle savedInstanceState) {
     super.onCreate(savedInstanceState);
     setContentView(R.layout.activity_main);

    // 1. Create a default TrackSelector
    Handler mainHandler = new Handler();
    BandwidthMeter bandwidthMeter = new DefaultBandwidthMeter();
    TrackSelection.Factory videoTrackSelectionFactory = new 
    AdaptiveTrackSelection.Factory(bandwidthMeter);
    TrackSelector trackSelector = new DefaultTrackSelector(videoTrackSelectionFactory);

    // 2. Create a default LoadControl
    LoadControl loadControl = new DefaultLoadControl();

    // 3. Create the player
    player = ExoPlayerFactory.newSimpleInstance(this, trackSelector, loadControl);

    simpleExoPlayerView = (SimpleExoPlayerView)findViewById(R.id.player_view);
    simpleExoPlayerView.setPlayer(player);

    // Measures bandwidth during playback. Can be null if not required.
    DefaultBandwidthMeter defaultBandwidthMeter = new DefaultBandwidthMeter();

    // Produces DataSource instances through which media data is loaded.
    DataSource.Factory dataSourceFactory = new DefaultDataSourceFactory(this, 
    Util.getUserAgent(this, "Exo2"), defaultBandwidthMeter);
    // Produces Extractor instances for parsing the media data.
    ExtractorsFactory extractorsFactory = new DefaultExtractorsFactory();
    // This is the MediaSource representing the media to be played.
    HlsMediaSource hlsMediaSource = new HlsMediaSource(Uri.parse(hlsVideoUri), 
    dataSourceFactory, mainHandler, new AdaptiveMediaSourceEventListener(){

        @Override
        public void onLoadStarted(DataSpec dataSpec, int dataType, int trackType, Format 
        trackFormat, int trackSelectionReason, Object trackSelectionData, long mediaStartTimeMs, 
        long mediaEndTimeMs, long elapsedRealtimeMs){

        }

        @Override
        public void onLoadCompleted(DataSpec dataSpec, int dataType, int trackType, Format 
        trackFormat, int trackSelectionReason, Object trackSelectionData, long mediaStartTimeMs, 
        long mediaEndTimeMs, long elapsedRealtimeMs, long loadDurationMs, long bytesLoaded) {

        }

        @Override
        public void onLoadCanceled(DataSpec dataSpec, int dataType, int trackType, Format 
        trackFormat, int trackSelectionReason, Object trackSelectionData, long mediaStartTimeMs, 
        long mediaEndTimeMs, long elapsedRealtimeMs, long loadDurationMs, long bytesLoaded) {

        }

        @Override
        public void onLoadError(DataSpec dataSpec, int dataType, int trackType, Format 
        trackFormat, int trackSelectionReason, Object trackSelectionData, long mediaStartTimeMs, 
        long mediaEndTimeMs, long elapsedRealtimeMs, long loadDurationMs, long bytesLoaded, 
        IOException error, boolean wasCanceled) {

        }

        @Override
        public void onUpstreamDiscarded(int trackType, long mediaStartTimeMs, long 
        mediaEndTimeMs) {

        }

        @Override
        public void onDownstreamFormatChanged(int trackType, Format trackFormat, int 
        trackSelectionReason, Object trackSelectionData, long mediaTimeMs) {

        }
        });

        player.addListener(this);
        player.prepare(hlsMediaSource);
       simpleExoPlayerView.requestFocus();
       player.setPlayWhenReady(true);
 
       progressBar = (ProgressBar) findViewById(R.id.progressBar);
       }
       @Override
       public void onTimelineChanged(Timeline timeline, Object manifest) {

       }

       @Override
        public void onTracksChanged(TrackGroupArray trackGroups, TrackSelectionArray 
        trackSelections) {

        }

        @Override
         public void onLoadingChanged(boolean isLoading) {

         }

         @Override
          public void onPlayerStateChanged(boolean playWhenReady, int playbackState) {

         switch (playbackState) {
        case Player.STATE_BUFFERING:
            //You can use progress dialog to show user that video is preparing or buffering so 
         please wait
            progressBar.setVisibility(View.VISIBLE);
            break;
        case Player.STATE_IDLE:
            //idle state
            break;
        case Player.STATE_READY:
            // dismiss your dialog here because our video is ready to play now
            progressBar.setVisibility(View.GONE);
            break;
        case Player.STATE_ENDED:
            // do your processing after ending of video
            break;
         }
        } 

        @Override
        public void onPlayerError(ExoPlaybackException error) {

        AlertDialog.Builder adb = new AlertDialog.Builder(MainActivity.this);
        adb.setTitle("Could not able to stream video");
       adb.setMessage("It seems that something is going wrong.\nPlease try again.");
       adb.setPositiveButton("OK", new DialogInterface.OnClickListener() {
        @Override
        public void onClick(DialogInterface dialog, int which) {
            dialog.dismiss();
            finish(); // take out user from this activity. you can skip this
        }
        });
       AlertDialog ad = adb.create();
       ad.show();
       }

       @Override
       public void onPositionDiscontinuity() {

       }

       @Override
       protected void onPause() {
       super.onPause();
       if (player != null) {
        player.setPlayWhenReady(false); //to pause a video because now our video player is not in 
       focus
       }
       }

        @Override
        protected void onDestroy() {
        super.onDestroy();
        player.release();
         }

        } `

**Comment by ojw28** [comment]
That means the methods you're overriding don't exist in the interface that you're implementing, or have different method signatures.

Note that these APIs have changed over time, so you need to be overriding the correct methods for whatever version of ExoPlayer you're depending on. For example, if you're depending on 2.11.3, you should be overriding methods with signatures as defined [here](https://exoplayer.dev/doc/reference/index.html?com/google/android/exoplayer2/source/AdaptiveMediaSourceEventListener.html).

**Comment by seyinator** [comment]
> That means the methods you're overriding don't exist in the interface that you're implementing, or have different method signatures.
> 
> Note that these APIs have changed over time, so you need to be overriding the correct methods for whatever version of ExoPlayer you're depending on. For example, if you're depending on 2.11.3, you should be overriding methods with signatures as defined [here](https://exoplayer.dev/doc/reference/index.html?com/google/android/exoplayer2/source/AdaptiveMediaSourceEventListener.html).

Can you tell me example for onLoadStarted please because I can't understand?

**Comment by ojw28** [comment]
If you're using ExoPlayer 2.11.3, you should probably just do:
```
player.addAnalyticsListener(new AnalyticsListener() {
  @Override
  public void onLoadStarted(EventTime eventTime,
      MediaSourceEventListener.LoadEventInfo loadEventInfo,
      MediaSourceEventListener.MediaLoadData mediaLoadData) {
    // Do what you like here
  }
});
```
