### ISSUE TITLE
Does mediaDrm.restoreKeys() support offline multiple session?

### ISSUE THREAD

**Issue by mehdibf** [google/ExoPlayer#7124]
I am trying to play Widevine DASH content using offline Licence. The offline Playback works well when multiple-session is turned off, but not if the backend server is able to respond with only one License at the time.

### Searched documentation and issues
According to https://github.com/google/ExoPlayer/issues/3872 and the documentation, the actual implementation of the ExoPlayer support that "Only one offline key set can be specified per playback". 

### Question
Is it theoretically possible to modify the player so that multiple License can be restored or is it a limitation in the Android SDK? 
As suggested in https://github.com/google/ExoPlayer/issues/3872 I tried to modify the player's code to restore two different keySetId before the playback start. For that I first modified DashUtil.loadDrmInitData() to get the audio and the video init data separately and called offlineLicenseHelper.downloadLicense(drmInitData) twice to download the licenses. But trying to restore the two licenses using mediaDrm.restoreKeys() twice, each one with the specific KeySetId for audio and video does not seem to work. Could it be that the second call of mediaDrm.restoreKeys() overrides the first one?

**Comment by ojw28** [comment]
> Could it be that the second call of mediaDrm.restoreKeys() overrides the first one?

Yes, that's what happens.

> Is it theoretically possible to modify the player so that multiple License can be restored or is it a limitation in the Android SDK?

It's possible, but you need to restore each key into its own session, rather than calling `restoreKeys` twice on the same session. You then need to ensure the correct session is used by each renderer during playback (e.g., the audio renderer needs to use the DRM session into which you've restored the keys needed for the audio tracks).

**Comment by mehdibf** [comment]
Thank you for your answer. Do you have any plans to support this multi-key issue in the next releases as responding with all licenses together for one requested key is not recommended by DASH-IF?

**Comment by ojw28** [comment]
> Do you have any plans to support this multi-key issue in the next release

That's essentially what https://github.com/google/ExoPlayer/issues/3872 is tracking, so I'll go ahead and close this as a duplicate. It's unlikely we will get round to it soon, unfortunately.

> as responding with all licenses together for one requested key is not recommended by DASH-IF?

In practice, the majority of streaming services that need the functionality you describe are doing this for Android / Widevine.
