### ISSUE TITLE
Bug: unable to play various videos on sample, on emulator API 21

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [google/ExoPlayer#7127]
### [REQUIRED] Issue description
Emulator API 21 fails to play a lot of the videos, even though it's supposed to support them:
https://developer.android.com/guide/topics/media/media-formats

### [REQUIRED] Reproduction steps
Run the sample demo on emulator API 21, and try playing the various videos. I'm talking about the "demo" sample on this repository.
See here:
[2020-03-23_10-55-48.zip](https://github.com/google/ExoPlayer/files/4368164/2020-03-23_10-55-48.zip)

### [REQUIRED] Link to test content
It's on the sample itself.
Here's the project:
[ExoPlayer.zip](https://github.com/google/ExoPlayer/files/4368166/ExoPlayer.zip)

### [REQUIRED] A full bug report captured from the device
Attached:
[bugReport.zip](https://github.com/google/ExoPlayer/files/4368170/bugReport.zip)

### [REQUIRED] Version of ExoPlayer being used
    releaseVersion = '2.11.3'
    releaseVersionCode = 2011003
    minSdkVersion = 16
    appTargetSdkVersion = 29
    targetSdkVersion = 28 // TODO: Bump once b/143232359 is resolved
    compileSdkVersion = 29
    dexmakerVersion = '2.21.0'
    guavaVersion = '23.5-android'
    mockitoVersion = '2.25.0'
    robolectricVersion = '4.3'
    autoValueVersion = '1.6'
    autoServiceVersion = '1.0-rc4'
    checkerframeworkVersion = '2.5.0'
    jsr305Version = '3.0.2'
    kotlinAnnotationsVersion = '1.3.31'
    androidxAnnotationVersion = '1.1.0'
    androidxAppCompatVersion = '1.1.0'
    androidxCollectionVersion = '1.1.0'
    androidxMediaVersion = '1.0.1'
    androidxTestCoreVersion = '1.2.0'
    androidxTestJUnitVersion = '1.1.1'
    androidxTestRunnerVersion = '1.2.0'
    androidxTestRulesVersion = '1.2.0'
    truthVersion = '0.44'

### [REQUIRED] Device(s) and version(s) of Android being used
Emulator API 21.

**Comment by ojw28** [comment]
> Emulator fails to play a lot of the videos, even though it's supposed to support them.

How did you determine that the emulator is supposed to support them? In the bug report, it looks like all of the failed playbacks indicate that the formats exceed the capabilities of the device (in this case the emulator). Look for lines such as the ones below, and in particular the "supported=NO_EXCEEDS_CAPABILITIES" next to each track:
```
D EventLogger:     Group:0, adaptive_supported=YES [
D EventLogger:       [X] Track:0, id=0, mimeType=video/avc, bitrate=232370, codecs=avc1.4d4015, supported=NO_EXCEEDS_CAPABILITIES
D EventLogger:       [ ] Track:1, id=1, mimeType=video/avc, bitrate=649879, codecs=avc1.4d401e, supported=NO_EXCEEDS_CAPABILITIES
D EventLogger:       [ ] Track:2, id=2, mimeType=video/avc, bitrate=991714, codecs=avc1.4d401e, supported=NO_EXCEEDS_CAPABILITIES
D EventLogger:       [ ] Track:3, id=3, mimeType=video/avc, bitrate=1927833, codecs=avc1.4d401f, supported=NO_EXCEEDS_CAPABILITIES
D EventLogger:     ]
```
We do have a few changes coming that aim to make it more obvious when a playback subsequently fails for this reason, but it doesn't seem unexpected to me that the playbacks would fail in this case.

**Comment by AndroidDeveloperLB** [comment]
Shouldn't it support them?
https://developer.android.com/guide/topics/media/media-formats#video-codecs
The entire table is covered from Android 5.0.
Would those work on real devices? I want to be able to test even on old versions, and emulator is the only choice I have...
It's just that I noticed this issue on a real app we develop, but again only on emulator because I don't have a device nearby with Android API 21 (I'm at home because of the Coronoa virus).
Should I be worried ?

**Comment by ojw28** [comment]
As per our [supported devices page](https://exoplayer.dev/supported-devices.html), we recommend against using the emulator unless it's running at least API level 23, due to the emulator not fully implementing the Android media stack. So no, I don't think you should be worried. This is an issue with the emulator, not with ExoPlayer, and you should not expect to see the same behavior on real devices.

**Comment by AndroidDeveloperLB** [comment]
OK I hope you are right and that it works fine on devices.
You say then that only from API 23 it's expected to work fine, right?
I'm closing this now.
I suggest in the demo to show a warning in case it detects too old version on emulator.

However, I'd like to ask:
Could audio be a cause on the emulator for this issue:
https://issuetracker.google.com/issues/152108780
?
On some cases, such as phone ringing or even taking a bug report after trying ExoPlayer, there is a repeating annoying sound that will stop only if I close the emulator.

**Comment by ojw28** [comment]
> You say then that only from API 23 it's expected to work fine, right?

Correct. The emulator has known issues on earlier API versions. I'm not sure about the issue you reference, but it seems quite likely to be an issue with the emulator.

**Comment by AndroidDeveloperLB** [comment]
OK , can you please add a check about the version on emulator, on the demo?
It can warn people who try this, that notice it has issues.

As for the issue I reported on the issue tracker, I know it's an emulator issue. Just a terrible one...

**Comment by ojw28** [comment]
I don't think it's worth adding extra code to the demo app for this. The popularity of using emulators with older API levels is naturally decreasing over time as developers increase their apps' minimum API levels, and we're already well past the point of peak confusion. In any case, doing so wont help anyone trying to run their own app on the emulator, which is probably the more common use case that results in developers hitting this problem.

**Comment by AndroidDeveloperLB** [comment]
I see. Sadly we work on this minimal API version, and we even moved to it only this year...

I wish I could show the team the statistics now, but sadly Google still didn't update the statistics, for a long time:
https://developer.android.com/about/dashboards
