### ISSUE TITLE
Picture will not be available during playback.

### ISSUE THREAD

**Issue by video-fly** [google/ExoPlayer#7128]
### [REQUIRED] Issue description
Picture will not be available during playback.
The video mimeType is null. Because we can not find correct atom type  when parseStsd.

### [REQUIRED] Reproduction steps
Play the video。

### [REQUIRED] Version of ExoPlayer being used
2.8.2 

### [REQUIRED] Device(s) and version(s) of Android being used
vivo x20, Android 9.0

**Comment by video-fly** [comment]
The video is h263.
I have send an email whicn contains the wrong video.
I get the result when  ffprobe the video.
Video: h263 (H263 / 0x33363248), yuv420p
Audio: mp3 (.mp3 / 0x33706D2E), 22050 Hz, stereo, s16p, 63 kb/s (default)

**Comment by ojw28** [comment]
We did not receive an email. Where did you send it, and what subject line did you use?

**Comment by video-fly** [comment]
I am sorry that I failed to send mail. I have resend.

**Comment by ojw28** [comment]
We have still not received this email.
