### ISSUE TITLE
Wrong duration for mp3 file

### ISSUE THREAD

**Issue by lucastsantos** [google/ExoPlayer#713]
ExoPlayer is returning an incorrect duration for certain mp3 files. 

I've compared ExoPlayer and MediaPlayer and got the following:

| Player | Duration (ms) | Duration (mm:ss) |
| --- | --- | --- |
| MediaPlayer | 202606 ms | 3:22 |
| ExoPlayer | 837156 ms | 13:57 |

Source file description:

|  |  |
| --- | --- |
| Format | MPEG 1 Layer 3 |
| Bitrate | CBR 231 kbps |
| Frequency | 44100 Hz |
| Channel | Stereo |
| Duration | 3:22 |

If a sample is needed, let me know.

**Comment by ojw28** [comment]
Thanks for the information. It's probably relatively easy to fix, but you'll need to provide a sample. I assume you're using ExtractorSampleSource for playback? Thanks!

**Comment by lucastsantos** [comment]
Yes, I'm using the ExtractorSampleSource.
How can I send it to you?
Thanks!

**Comment by ojw28** [comment]
If it's suitable for public distribution, then a public link to a file on Google Drive / DropBox is best. If not, email privately to olly.exoplayer@gmail.com. Thanks!

**Comment by lucastsantos** [comment]
Don't think that would be suitable for public distribution, I've sent trough email. 
Thank you. :smile:

**Comment by ojw28** [comment]
Where did you get the "source file description" from, out of interest?

**Comment by lucastsantos** [comment]
I used [kid3](http://kid3.sourceforge.net/). But since you asked, I checked on iTunes and found that the bitrate it's VBR 231 kbps there. 
Sorry about information that might be wrong.

**Comment by ojw28** [comment]
Andrew has a fix for this. Will merge soon.

**Comment by ojw28** [comment]
This should be fixed by https://github.com/google/ExoPlayer/commit/37ebec6e826bac0f09c17e977f7341f76127e2b4. Please let us know if this isn't the case.

**Comment by lucastsantos** [comment]
I've tested with the sample I've sent and it was fixed. However, I've found another sample that remains with the problem. I'm sending it to you.

**Comment by ojw28** [comment]
We have a change that fixes the duration.

Note however that this mp3 will not be seekable once the change has gone in, because it has a Xing header that does not include a table of contents, which would usually be used to determine how to seek within the file. To this extent, I think the file provided should be considered abnormal/flawed.
