### ISSUE TITLE
Corrupted playback of 15x I-frame H264 TS content

### ISSUE THREAD

**Issue by CalebGartner** [google/ExoPlayer#7131]
- Related/Similar issues https://github.com/google/ExoPlayer/issues/1393   https://github.com/google/ExoPlayer/issues/1263   https://github.com/google/ExoPlayer/pull/6270   https://github.com/google/ExoPlayer/issues/6598   https://github.com/google/ExoPlayer/issues/678 https://github.com/google/ExoPlayer/issues/488  https://github.com/google/ExoPlayer/issues/5003 https://github.com/google/ExoPlayer/issues/926

### [REQUIRED] Issue description
To give context, I'm trying to playback a particular MPEG-TS stream that's been sped up 15x - i.e., a stream of only I-frames that skips content in-between to speed up playback to 15x. The issue is that I'm able to playback one of these streams just fine, while another stream of the same type, that's prepared the same way, glitches terribly and renders artifacts/green blocks/etc. to the screen before usually becoming stuck in a buffering state. 
Example playback link of the issue:
[![Example playback link](https://i9.ytimg.com/vi/Xu8YN1Lv66E/hqdefault.jpg?time=1584829379048&sqp=CJCm2vMF&rs=AOn4CLAhy3V5QlHDdzsTtOSOybdweDWXpQ)](https://www.youtube.com/watch?v=Xu8YN1Lv66E)

There are a number of things that have stuck out while trying to debug this issue.

- It's unlikely to be the decoder:
    - The decoder used by default is `OMX.amlogic.avc.decoder.awesome`. Even when blacklisting it in `MediaCodecUtil.isCodecUsableDecoder()` to use google's software decoder for h264, playback failed.
- Debugging and analyzing the rendering pipeline on Exoplayer’s side:
    - In `MediaCodecRenderer.java`, the core cause seems to be that the `outputIndex` variable in the `drainOutputBuffer` function is consistently being set to -1 (indicating timeout), causing ExoPlayer to eventually switch to a BUFFERING state (the clip I emailed may not be long enough for you to see this). The `outputIndex` variable is set to the return value of a function call in Android’s native libraries, `native_dequeueOutputBuffer`  in `MediaCodec.java`, which has no implementation I can find, and the debugger cannot follow any further. It's likely forwarded to the AOSP/HAL.
- Analysis with ffmpeg/ffprobe tools
    - Interestingly, using `ffplay -loglevel debug -report -an -sn  15x_not_working.ts` will playback the fast-forward stream just fine, though it spits out some errors. 
    - Here is the ffprobe output for each of the working and non-working TS streams (`ffprobe -show_streams -select_streams v <filename>.ts`). 
[ffprobe_15x_not_working.txt](https://github.com/google/ExoPlayer/files/4369996/ffprobe_15x_not_working.txt)
[ffprobe_15x_working.txt](https://github.com/google/ExoPlayer/files/4369998/ffprobe_15x_working.txt)
Something interesting worth noting is that on the 15x stream of the not-working content, ffprobe reports the field order as `tt`, but on the 1x stream of the same content, ffprobe reports the field order as `bb`. Orirginally, I thought that deinterlacing might be the cause of the issue, but since the 1x interlaced stream plays back fine I doubt it. Unless the decoder can't handle deinterlacing a different field order?
- Analysis of incoming NAL units (logged in `H264Reader.startNalUnit()`):
    - The only difference I could see was that compared to the working 15x stream (left), the not-working stream (right) always had one less SEI (Supplemental Enhancement Information) NAL unit, which should be largely irrelevant since it's mainly used for CC information and such.
    - Edit: I've since found that NAL SEI units can contain recovery point data, a point at which video can start playing without issues. Perhaps it's assuming that Exoplayer should use SEI recovery points in the elementary stream as random access points?
![nal_unit_types_missing_6](https://user-images.githubusercontent.com/16978771/77328331-00336b80-6ce2-11ea-8050-fc85966a6d2d.PNG)
- Finally, it's important to note that there _is_ a proprietary adaptation field included in the ts streams, and since ExoPlayer's TsExtractor skips the adaptation field by default, this could possibly be part of the issue.

### [REQUIRED] Reproduction steps
In order to reproduce, please use the files I emailed and add them to the `demo` module's asset folder. I am using the demo app as a base for this. [Here is a link to the github repo I'm using](https://github.com/CalebGartner/ExoPlayer). [This is the link to commit I added to modify the demo to test this content](https://github.com/CalebGartner/ExoPlayer/commit/c491f876a95d1a0b0e8e647276e9fb17edd51eda).

### [REQUIRED] Link to test content
Emailed link to `dev.exoplayer@gmail.com`

### [REQUIRED] A full bug report captured from the device
[bugreport-SEI400DN-PI-2020-03-23-08-53-08.zip](https://github.com/google/ExoPlayer/files/4370135/bugreport-SEI400DN-PI-2020-03-23-08-53-08.zip)

### [REQUIRED] Version of ExoPlayer being used
2.11.1

### [REQUIRED] Device(s) and version(s) of Android being used
SEI Robotics AirTV Mini, Android API 28

**Comment by ojw28** [comment]
The Google Drive folder you've shared appears to be empty. Please could you drop the test content into it?

**Comment by CalebGartner** [comment]
That's quite odd. I just tested the link on a separate account and computer, and it seemed to work. I've uploaded it to DropBox instead and sent another link via email; please let me know if it doesn't work. Otherwise I can just email the test content bit by bit. Sorry for the trouble.

**Comment by ojw28** [comment]
> In MediaCodecRenderer.java, the core cause seems to be that the outputIndex variable in the drainOutputBuffer function is consistently being set to -1

This is expected if the decoder hasn't got an output buffer to dequeue when the method is called, and will occur during normal playback. If you're saying that the decoder ends up in a state where it _never_ has an output buffer to dequeue, then that's either because nothing is being fed on the input side, or because the input is malformed in a way that's preventing the decoder from generating corresponding output buffers.

Regarding the content: It seems highly likely the content itself is malformed. Neither of the three 15x samples play at all in VLC for me. When playing with ExoPlayer I see quite a lot of warnings from `PesReader`, which indicates that the container is likely malformed. I think the media being malformed is probably the root cause of the problem. Unfortunately, since this doesn't look likely to be an ExoPlayer issue, and also because it looks like it would be very time consuming to debug, it's probably out of scope for this issue tracker.

> Orirginally, I thought that deinterlacing might be the cause of the issue, but since the 1x interlaced stream plays back fine I doubt it. Unless the decoder can't handle deinterlacing a different field order?

As an aside, it's worth noting that Android devices do not guarantee to support interlacing at all. They may do so if the device manufacturer has implemented it, but support is quite varied.

**Comment by CalebGartner** [comment]
> I think the media being malformed is probably the root cause of the problem. Unfortunately, since this doesn't look likely to be an ExoPlayer issue, and also because it looks like it would be very time consuming to debug, it's probably out of scope for this issue tracker.

Makes total sense. Thank you for taking a look at it anyways. If you don't mind though, I have a few more questions I wanted to ask. It was undoubtedly an issue with the media format, regardless of whether it was malformed or ExoPlayer was somehow mishandling it. I just wanted to rule out potential issues on the ExoPlayer side of things. 

The main reason for this was that it stuck out to me that one of the H.264 15x samples played back fine in ExoPlayer, but the other didn't, though both had the same warnings from `PesReader`. If you look at the commit I linked above, you'll see that line 318 in `TsExtractor`, `payloadReader.seek()`, is commented out in order to avoid becoming stuck in buffering. Could doing so possibly cause this corruption issue?

> As an aside, it's worth noting that Android devices do not guarantee to support interlacing at all. They may do so if the device manufacturer has implemented it, but support is quite varied.

This makes sense. Do you mean Android device support for interlacing when decoding, or when rendering? I had hoped that using the OMX.google.h264.decoder instead of the AMLogic hardware decoder would have helped with that.

Finally, I have one more question: I couldn’t find any code to handle the removal of emulation prevention bytes in NAL units, which is part of the MPEG-4 spec. Did I miss it (likely), or is there a reason for ExoPlayer not handling it?

**Comment by ojw28** [comment]
> Could doing so possibly cause this corruption issue?

It's possible, but it's not that easy to prove that this is the case. In general, I don't understand why you would use MPEG-TS at all for this use case. Particularly if you're creating this media yourself, an MP4 container is going to be _much_ simpler to reason about.

> Do you mean Android device support for interlacing when decoding, or when rendering?

Video decoders always produce full output buffers, so the answer to your question is effectively "when decoding". There's no requirement that decoders support decoding of interlaced content.

> Finally, I have one more question: I couldn’t find any code to handle the removal of emulation prevention bytes in NAL units, which is part of the MPEG-4 spec. Did I miss it (likely), or is there a reason for ExoPlayer not handling it?

`NalUnitUtil.unescapeStream` does this. It appears to do so for SEI units only. It's unclear how this would be related to this issue, however, since if we need this elsewhere then it would be a problem for regular streams as well.

**Comment by CalebGartner** [comment]
> It's possible, but it's not that easy to prove that this is the case.

Fair enough. The last question was more to satisfy my own curiosity, thank you for the answer. I'll see about switching container formats. Thanks again!
