### ISSUE TITLE
This video is played incorrectly in ExoPlayer

### ISSUE THREAD

**Issue by dryganets** [google/ExoPlayer#7133]
Video is playing correctly by all desktop players while in ExoPlayer there is a glitch in video playback.
Audio is played correctly, while video playback starts from the middle.

[sample.mp4.zip](https://github.com/google/ExoPlayer/files/4371327/sample.mp4.zip)

Tried:
- VLC
- Mplayer
- Quicktime
- Google chrome

I tried multiple devices running different Android OS and results are consistent.

I'm using latest version of ExoPlayer available at the moment 2.11.3.

Wonder if something could be done on the ExoPlayer side.

**Comment by ojw28** [comment]
Fixed in `dev-v2`

**Comment by dryganets** [comment]
@ojw28, could you reference the change in dev-2 which fixes this issue please?

Could you share more technical details on why it is happening?
ie what is special about this particular video?

It will help the community to figure out if the issue they are facing is duplicate of this one.

Also it will give them a clue in which version they could expect the fix or which commit they need to cherry-pick in their internal fork.

Thank you!

**Comment by ojw28** [comment]
The change is already referenced right above.

**Comment by ojw28** [comment]
In terms of why this is happening: The video has an MP4 edit list that partially clips the first video frame. Our logic for edit list handling would skip this frame, and then skip forward to the next keyframe, which for this video is quite far into the video. After the change, we no longer skip a sample that's partially clipped by the edit list.

**Comment by dryganets** [comment]
Thanks, for the fix and the explanation of the root cause, sorry didn't notice the the reference to https://github.com/google/ExoPlayer/commit/eebe990d2059a04c645cf1c0fd254764ddb4c0bc  on the top.
