### ISSUE TITLE
Exoplayer 2.9.6: Why does the exoplayer start playing audio with a tinkle like a notice?

### ISSUE THREAD

**Issue by l20160606sy** [google/ExoPlayer#7135]
[No information provided]

**Comment by ojw28** [comment]
Sorry, but it's impossible to know what this means. Please could you more fully describe your question?

**Comment by l20160606sy** [comment]
On Android phones, just like wechat will ring for new information, it will also ring at the beginning of playback

**Comment by ojw28** [comment]
Given ExoPlayer is used by a huge number of apps, and this has never been reported before, I'm fairly certain this is not general ExoPlayer behaviour.

It's most likely an issue specific to your app, or (less likely) a device specific issue affecting the particular device you're using. If you're seeing the issue across all apps that use ExoPlayer, and in particular if you see it in the ExoPlayer demo app, then please file an issue that properly fills in the issue template.

**Comment by l20160606sy** [comment]
Thank you, I think I've found a solution. There's something wrong with some androids.
