### ISSUE TITLE
[DashManifestParser] [Invalid UUID string When parse manifest]

### ISSUE THREAD

**Issue by ChangLingSg** [google/ExoPlayer#7136]
Hi, 

  Inside `DashMainifestParser`, there is a function   
   ```
protected Pair<@NullableType String, @NullableType SchemeData> parseContentProtection(
      XmlPullParser xpp) throws XmlPullParserException, IOException

```
Which is used for parse the dash mainifest, but I get a problem, my default_KID is on below format instead of the format like "39392-32322-dsdsds-33222323-323232", the parseContentProtection cannot parse it. Can I know is it a issue for exoplayer? or our mainifest have to follow this format "39392-32322-dsdsds-33222323-323232" with segment of "-"?

`<ContentProtection schemeIdUri="urn:mpeg:dash:mp4protection:2011" value="cenc" cenc:default_KID="21d541c403214c1e0f431d130496i5be"/>`

**Comment by ojw28** [comment]
`default_KID` is supposed to be a UUID format string. I.e., your `default_KID` should be `21d541c4-0321-4c1e-0f43-1d130496i5be`.
