### ISSUE TITLE
Exoplayer Screen shows black screen for sometime while changing Orientation manually

### ISSUE THREAD

**Issue by ghost** [google/ExoPlayer#7141]
I am facing issue while rotating device orientation manually 
Some black screen (some milliseconds ) on some devices appears before playback is visible .
Kindly provide  some solution for this.

**Comment by ojw28** [comment]
Is it viable for you to configure your activity to handle the orientation change manually? This avoids the UI from being recreated, and hence the problem you're seeing. This is what the [ExoPlayer main demo app does](https://github.com/google/ExoPlayer/tree/release-v2/demos/main). Note the following is present in the `AndroidManifest.xml`

```
android:configChanges="keyboard|keyboardHidden|orientation|screenSize|screenLayout|smallestScreenSize|uiMode"
```

**Comment by shashanksaxena1234** [comment]
Hi Ojw28 ,
I already implemented   android:configChanges="screenSize|smallestScreenSize|screenLayout|orientation" in my AndroidManifest.xml
also tried with your configChanges .Still black screen  appears
Is there any change in fragment required.Kindly help on this.

**Comment by ghost** [comment]
> Is it viable for you to configure your activity to handle the orientation change manually? This avoids the UI from being recreated, and hence the problem you're seeing. This is what the [ExoPlayer main demo app does](https://github.com/google/ExoPlayer/tree/release-v2/demos/main). Note the following is present in the `AndroidManifest.xml`
> 
> ```
> android:configChanges="keyboard|keyboardHidden|orientation|screenSize|screenLayout|smallestScreenSize|uiMode"
> ```

Hi Ojw28 ,
I already implemented android:configChanges="screenSize|smallestScreenSize|screenLayout|orientation" in my AndroidManifest.xml and also tried with your configChanges ,Still black screen appears
One more thing this problem occurs when i am calling setRequestedOrientation(int requestedOrientation) manually .
Is there any change in fragment required.Kindly help on this.

**Comment by ojw28** [comment]
Does the issue reproduce in the ExoPlayer demo app, or only in your own application? If the latter then it sounds like an issue with your application code, rather than ExoPlayer, in which case it's not possible for us to help unless you can provide a project as source code that reproduces the problem.

**Comment by ghost** [comment]
This issue is reproducible in exoplayer (demo-gl) app (Device - Sony Experia G8342).

**Comment by ojw28** [comment]
This is not relevant because the demo-gl app doesn't handle orientation changes manually (as an aside, we will fix it so that it does).

**Comment by ghost** [comment]
I am also facing this issue. It shows black screen for few milliseconds.


package com.example.videoplayer

import android.annotation.SuppressLint
import android.content.pm.ActivityInfo
import android.content.res.Configuration
import android.graphics.Color
import android.os.Bundle
import android.os.Handler
import android.os.Looper
import android.view.View
import android.view.WindowManager
import android.widget.ImageView
import android.widget.TextView
import androidx.appcompat.app.AppCompatActivity
import com.google.android.exoplayer2.Player
import com.google.android.exoplayer2.SimpleExoPlayer
import com.google.android.exoplayer2.extractor.DefaultExtractorsFactory
import com.google.android.exoplayer2.source.ExtractorMediaSource
import com.google.android.exoplayer2.source.MediaSource
import com.google.android.exoplayer2.source.ProgressiveMediaSource
import com.google.android.exoplayer2.ui.DefaultTimeBar
import com.google.android.exoplayer2.ui.PlayerControlView
import com.google.android.exoplayer2.ui.PlayerView
import com.google.android.exoplayer2.upstream.DataSource
import com.google.android.exoplayer2.upstream.DefaultDataSourceFactory
import com.google.android.exoplayer2.upstream.RawResourceDataSource
import com.google.android.exoplayer2.util.Util
import kotlinx.android.synthetic.main.activity_main.*
import kotlinx.android.synthetic.main.custom_exo_controller_view.*
import kotlinx.android.synthetic.main.video_player_help.*


class MainActivity : AppCompatActivity(), Player.EventListener {

    private lateinit var  mPlayerEventListener: Player.EventListener
    private lateinit var player : SimpleExoPlayer
    private lateinit var playerView : PlayerView
    private lateinit var handler : Handler
    private lateinit var totalTime : TextView
    private lateinit var audioImage: ImageView
    private lateinit var runnable : Runnable
    private lateinit var exoPlayerProgress : DefaultTimeBar
    private lateinit var pauseButtonImage : ImageView
    private lateinit var  controls : PlayerControlView
    private lateinit var playImage : ImageView
    private var isPlaying: Boolean = false

    // autoplay = false
    private var autoPlay = false

    // used to remember the playback position
    private var currentWindow = 0
    private var playbackPosition: Long = 0
    private var  audioValue : Float = 0f

    @SuppressLint("ResourceType")
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        viewInitialization()
        if (savedInstanceState != null) {
            playbackPosition = savedInstanceState.getLong("playback_pos", 0)
            currentWindow = savedInstanceState.getInt("curr_win", 0)
            autoPlay = savedInstanceState.getBoolean("autoplay", false)

            if (autoPlay) {
                playerView.videoSurfaceView?.setBackgroundResource(Color.TRANSPARENT)
                pauseButtonImage.visibility = View.GONE
            }
        }

        mPlayerEventListener = this
        toolbar?.setNavigationOnClickListener {
            finish()
        }
        handler = Handler(Looper.getMainLooper())

        videoPlayer()
        onClickListeners()
        playBackListener()
        updateElapsedTimeAndSeekBar()
    }


    override fun onSaveInstanceState(outState: Bundle) {
        super.onSaveInstanceState(outState)
        outState.putLong("playback_pos", playbackPosition)
        outState.putInt("curr_win", currentWindow)
        outState.putBoolean("autoplay", autoPlay)
        outState.putFloat("audio", audioValue)
    }

    private fun viewInitialization() {
        player = SimpleExoPlayer.Builder(this).build()
        playerView = findViewById(R.id.videoView)
        playerView.player = player
        controls = findViewById(R.id.controls)
        controls.player = player
        totalTime = findViewById(R.id.total_time)
        audioImage = findViewById(R.id.speaker_image)
        exoPlayerProgress = findViewById(R.id.exo_progress)
        pauseButtonImage = findViewById(R.id.pauseButtonImage)
        playImage = findViewById(R.id.playImage)
        playerView.videoSurfaceView?.setBackgroundResource(R.color.colorPrimary)
    }

    private fun videoPlayer() {

        // Produces DataSource instances through which media data is loaded.
        val dataSourceFactory: DataSource.Factory = DefaultDataSourceFactory(this, Util.getUserAgent(this, "PPE"))
        // This is the MediaSource representing the media to be played.
        val uri = RawResourceDataSource.buildRawResourceUri(R.raw.st1_vsb_conv_u01ls01_02)
        val videoSource: MediaSource = ProgressiveMediaSource.Factory(dataSourceFactory).createMediaSource(uri)

        /*val audioSource: MediaSource = ExtractorMediaSource(
            uri,
            CacheDataSourceFactory(
                this,
                100 * 1024 * 1024,
                5 * 1024 * 1024
            ), DefaultExtractorsFactory(), null, null
        )*/

        player.prepare(videoSource)
        player.playWhenReady = autoPlay
        if (resources.configuration.orientation == Configuration.ORIENTATION_LANDSCAPE) {
            controls.visibility = View.INVISIBLE
            window.addFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN);
        }
        if (!autoPlay) {
            pausePlayer()
        }
        // resume playback position
        player.seekTo(currentWindow, playbackPosition)
        player.addListener(mPlayerEventListener)
    }

    private fun updateElapsedTimeAndSeekBar() {
        handler = Handler()
        runnable = Runnable {
            val seconds = (player.currentPosition / 1000).toInt() % 60;
            val minutes = ((player.currentPosition / 1000).toInt() / 60) % 60
            totalTime.text = String.format("%01d:%02d", minutes, seconds)
            handler.postDelayed(runnable, 1000)
        }
        handler.postDelayed(runnable, 0)
    }

    private fun playBackListener() {

        player.addListener(object : Player.EventListener {
            override fun onPlayerStateChanged(playWhenReady: Boolean, playbackState: Int) {

                if (playbackState == Player.STATE_ENDED) {
                    player.seekTo(0)
                    totalTime.text = "0:00"
                    player.playWhenReady = false
                    pauseButtonImage.visibility = View.VISIBLE
                    playerView.videoSurfaceView?.setBackgroundResource(R.color.colorPrimary)
                    playImage.setImageResource(R.drawable.play_video_blue)
                    isPlaying = false
                    controls.visibility = View.VISIBLE
                }
            }
        })
    }

    private fun pausePlayer() {
        player.playWhenReady = false
        playerView.videoSurfaceView?.setBackgroundResource(R.color.blue_transparent)
        pauseButtonImage.visibility = View.VISIBLE
        playImage.setImageResource(R.drawable.play_video_blue)
        controls.visibility = View.VISIBLE
        player.seekTo(player.currentPosition)
    }

    @SuppressLint("ResourceType")
    private fun startPlayer() {
        player.playWhenReady = true
        playerView.videoSurfaceView?.setBackgroundResource(Color.TRANSPARENT)
        pauseButtonImage.visibility = View.GONE
        playImage.setImageResource(R.drawable.pause_video)
        if (resources.configuration.orientation == Configuration.ORIENTATION_LANDSCAPE) {
            controls.visibility = View.INVISIBLE
        }
    }

    override fun onSupportNavigateUp(): Boolean {
        onBackPressed()
        return true
    }

    private fun onClickListeners() {
        Video_helpImage.setOnClickListener {
            videoHelpLayout.visibility = View.VISIBLE
            if (player.isPlaying) {
                isPlaying = true
                pausePlayer()
            }
        }

        closeImage.setOnClickListener {
            videoHelpLayout.visibility = View.GONE
            if (isPlaying)
                startPlayer()
        }

        playImage.setOnClickListener {
            if (player.isPlaying) {
                pausePlayer()
            } else {
                startPlayer()
            }
        }

        val currentvolume = player.volume
        audioImage.setOnClickListener {
            if (player.volume == 0f) {
                player.volume = currentvolume
                audioImage.setImageResource(R.drawable.ic_speaker)
            } else {
                player.volume = 0f
                audioImage.setImageResource(R.drawable.audio_muted)
            }
        }

        pauseButtonImage.setOnClickListener {
            startPlayer()
        }

        playerView.videoSurfaceView?.setOnClickListener {
            if (player.isPlaying) {
                pausePlayer()
            } else {
                startPlayer()
            }
        }

        fullScreenImage.setOnClickListener {
            requestedOrientation = if (resources.configuration.orientation == Configuration.ORIENTATION_LANDSCAPE) {
                ActivityInfo.SCREEN_ORIENTATION_SENSOR_PORTRAIT
            } else {
                ActivityInfo.SCREEN_ORIENTATION_SENSOR_LANDSCAPE
            }
        }
    }

   /* private fun updateProgressBar() {
        val duration = if (player == null) 0 else player.duration
        val position = if (player == null) 0 else player.currentPosition

        totalTime.text = "" +  position/1000
        handler.removeCallbacks(updateProgressAction);
        // Schedule an update if necessary.
        val playbackState = if (player == null) Player.STATE_IDLE else player.playbackState
        if (playbackState != Player.STATE_IDLE && playbackState != Player.STATE_ENDED) {
            var delayMs: Long
            if (player.playWhenReady && playbackState == Player.STATE_READY) {
                delayMs = 1000 - position % 1000
                if (delayMs < 200) {
                    delayMs += 1000
                }
            } else {
                delayMs = 1000
            }
            handler.postDelayed(updateProgressAction, delayMs)
        }
    }

    private val updateProgressAction = Runnable { updateProgressBar() }*/

    override fun onPause() {
        super.onPause()

        playbackPosition = player.getCurrentPosition();
        currentWindow = player.getCurrentWindowIndex();
        autoPlay = player.getPlayWhenReady();
        audioValue = player.volume
    }
    override fun onStop() {
        super.onStop()
        pausePlayer()
    }

}
