### ISSUE TITLE
Unable to sync buffering with controls 

### ISSUE THREAD

**Issue by PPetka** [google/ExoPlayer#7143]
### [REQUIRED] Issue description
The `PlayerView` attrubute `app:show_buffering` does not take into account control views. What I mean by that is, whenever you have your control view buttons (especially pause and play button) in the same place as buffering `ProgressBar`, those 2 views overlap each other. And I can't see a way to make it in-sync. 

What I've tried to do, is to listen upon buffering state, and if one is present, hide pause button. It works, but when you hide and then show whole control view, the play (or pause button, depending on video state) is back visible again. And there seems not to be a way to fix it.

I did some digging and found that the cause is in the `show()` method inside `PlayerControlView`
```
  public void show() {
    if (!isVisible()) {
      setVisibility(VISIBLE);
      if (visibilityListener != null) {
        visibilityListener.onVisibilityChange(getVisibility());
      }
      updateAll();
      requestPlayPauseFocus();
    }
    // Call hideAfterTimeout even if already visible to reset the timeout.
    hideAfterTimeout();
  }
```
The listeners are applied, and then `updateAll()` method is called. Thats the place, where all buttons visbility is changed, regarding video state. 
So in other words, no matter what changes upon control views visibility I do inside listeners, it will be reset by `updateAll()` **which is buffering unaware.**

What there should be, is some kind of flag (that `updateAll()` method could be aware of), that lets you hide the play/pause buttons (or any) when the buffering is happening.

### [REQUIRED] Reproduction steps
1) download repo:
https://github.com/PPetka/exo-buffering-not-in-sync-with-controll-buttons
2) make video start buffering
3) hide and then show control view while buffering is on

### [REQUIRED] Link to test content
https://drive.google.com/file/d/1E_xHJ5yhf9vHuHQDgfxFMNH9V0JSDZ4n/view?usp=sharing

### [REQUIRED] A full bug report captured from the device
its UI related. No bug captured

### [REQUIRED] Version of ExoPlayer being used
2.9.5

### [REQUIRED] Device(s) and version(s) of Android being used
It will not be device/os related. Anyway
Oneplus 7 pro
Android 10

**Comment by ojw28** [comment]
There's only so much customization that it's possible for our out-of-the-box UI components to support in a reasonable way. If we try and support every possible customization then those components will become an unusable mess.

If you need a specific type of customization that's not supported, you'll need to implement your own UI components instead, which is what the vast majority of media apps do. You can pretty easily fork ExoPlayer's UI components to use as a starting point, and modify them to suit your needs.
