### ISSUE TITLE
Frames are Skipping randomly in When DRM Videos are getting Downloaded and trying to Play

### ISSUE THREAD

**Issue by piyush2dev** [google/ExoPlayer#7144]
@marcbaechinger @erdemguven 

Please help.

I am using Exoplayer 2.11.3. I implemented Offline Drm in it. When I am trying to play offline downloaded videos than Video Frames are getting skipped randomly and video is getting skipped randomly. Please find the attached Video for the same.

//This is the Video of the Issue coming in 2.11.3 as mentioned above.
[Video Link of the Issue](https://www.youtube.com/watch?v=a6XXsYwIl6I&feature=youtu.be)
https://www.youtube.com/watch?v=a6XXsYwIl6I&feature=youtu.be

**In Logs Something like this is coming continously**:
```
droppedFrames [eventTime=0.69, mediaPos=11.26, window=0, period=0, 179]
droppedFrames [eventTime=4.26, mediaPos=29.63, window=0, period=0, 282]
droppedFrames [eventTime=27.42, mediaPos=131.30, window=0, period=0, 88]
```

*In 2.10.4 this issue was not coming.

**Code Which is Used in 2.11.3 is given below**

```
DefaultDrmSessionManager<ExoMediaCrypto> drmSessionManager =new DefaultDrmSessionManager.Builder()
              .setUuidAndExoMediaDrmProvider(drmInfo.drmScheme, FrameworkMediaDrm.DEFAULT_PROVIDER)
              .setMultiSession(drmInfo.drmMultiSession)
              .build(mediaDrmCallback);
drmSessionManager.setMode(DefaultDrmSessionManager.MODE_PLAYBACK, offlineLicenseKeySetId);
```

```
 DownloadRequest downloadRequest =((DemoApplication) getApplication())
            .getDownloadTracker()
            .getDownloadRequest(parameters.uri);

   if (downloadRequest != null) {
      return DownloadHelper.createMediaSource(downloadRequest, dataSourceFactory, drmSessionManager);
```

**Comment by ojw28** [comment]
Please provide complete information as is requested in the [issue template](https://github.com/google/ExoPlayer/issues/new?assignees=&labels=bug%2C+needs+triage&template=bug.md&title=). Please copy/paste the issue template into this issue and fill it out, rather than filing a new issue.
