### ISSUE TITLE
when pause media , slow down the volume

### ISSUE THREAD

**Issue by ruichaoqun** [google/ExoPlayer#7145]
many player can slow down the volume when pause the media,how can exoplayer to achieve this effect?

**Comment by ojw28** [comment]
Please could you clarify what it means to slow down the volume? Do you mean that when pause is pressed, the audio volume will ramp down over a period of time before playback is finally paused?

**Comment by ruichaoqun** [comment]
> Please could you clarify what it means to slow down the volume? Do you mean that when pause is pressed, the audio volume will ramp down over a period of time before playback is finally paused?

yeah,how to that? i didn't find some useful parameter int method setPlayWhenReady

**Comment by ojw28** [comment]
What duration are you expecting this to occur over? Please could you provide an example of one of the players that supports this feature. VLC doesn't appear to, for example.

If you're thinking of a very short duration of volume shaping to make the pause/resume "feel" nicer, then the underlying platform should already do this underneath ExoPlayer. It's possible we need to tweak some things to enable it though.

**Comment by ruichaoqun** [comment]
> What duration are you expecting this to occur over? Please could you provide an example of one of the players that supports this feature. VLC doesn't appear to, for example.
> 
> If you're thinking of a very short duration of volume shaping to make the pause/resume "feel" nicer, then the underlying platform should already do this underneath ExoPlayer. It's possible we need to tweak some things to enable it though.

**Comment by ruichaoqun** [comment]
> What duration are you expecting this to occur over? Please could you provide an example of one of the players that supports this feature. VLC doesn't appear to, for example.
> 
> If you're thinking of a very short duration of volume shaping to make the pause/resume "feel" nicer, then the underlying platform should already do this underneath ExoPlayer. It's possible we need to tweak some things to enable it though.

such as Netease cloud music  and QQ music ,They all have a fade-in and fade out function when play or pause the music
