### ISSUE TITLE
Local build fails cause of missing exoplayerModulePrefix

### ISSUE THREAD

**Issue by stari4ek** [google/ExoPlayer#7147]
### [REQUIRED] Issue description
Changes made with 4e5b2c692f44d354dfc5e6c0e078d6f9a1ebaa47 broke local build:

```
Build file '/home/astar/dev/tvirl/develop/extern/ExoPlayer/library/core/build.gradle' line: 65
A problem occurred evaluating project ':library-core'.
> Cannot get property 'exoplayerModulePrefix' on extra properties extension as it does not exist
```

adding check as in all other places where `exoplayerModulePrefix` is referenced fixes the issue
```
if (gradle.ext.has('exoplayerModulePrefix')) {
```

### [REQUIRED] Reproduction steps
Build exoplayer as library inside another app project

### [REQUIRED] Link to test content
not applicable

### [REQUIRED] A full bug report captured from the device
not applicable

### [REQUIRED] Version of ExoPlayer being used
5c4d4762d1fc7c58349089deb67d44188f873d57

### [REQUIRED] Device(s) and version(s) of Android being used
not applicable

**Comment by ojw28** [comment]
@sim0629 - This is related to your recent change. Could you take a look? Thanks!

**Comment by ojw28** [comment]
Note: I think this relates to the instructions [here](https://github.com/google/ExoPlayer/blob/release-v2/README.md#locally) for using a local dependency.

**Comment by stari4ek** [comment]
Good point.
Should it be aligned to same kind of usage in all places?

**Comment by ojw28** [comment]
Fixed in `dev-v2`.

**Comment by stari4ek** [comment]
just in case, I've checked integration on my side. it was as described in documentation:
```
gradle.ext.exoplayerRoot = 'extern/ExoPlayer'
gradle.ext.exoplayerModulePrefix = 'exoplayer-'
apply from: new File(gradle.ext.exoplayerRoot, 'core_settings.gradle')
```
