### ISSUE TITLE
Out of memory issue while displaying a image overlay on the video 

### ISSUE THREAD

**Issue by Root2Technologies** [google/ExoPlayer#715]
In My application i play a video playlist using 'exoplayer' , It works fine , but when i overlay a small image  
using imageview on the video . the video hangs after 10 minutes . The same thing happens even if i have a text overlay on the video . My  hprof dumps shows that  
 
22,133 instances of "java.lang.Thread", loaded by "system class loader"  . Could you please guide me. thankyou

**Comment by ojw28** [comment]
That sounds like an issue with application code, not directly related to ExoPlayer. I'd suggest you ask for help on StackOverflow.
