### ISSUE TITLE
MediaSource in dynamic ConcatenatingMediaSource freezing UI after calling addMediaSource() 

### ISSUE THREAD

**Issue by vipafattal** [google/ExoPlayer#7150]
### [REQUIRED] Searched documentation and issues
I've searched in documentation and other similar issues about how to create a dynamic playlist in Exoplayer but all I found just create a `ConcatenatingMediaSource` then add or remove media source from it.

### [REQUIRED] Question
I'm creating a dynamic mp3 list with `ConcatenatingMediaSource()` and when the user adds more mp3 to the playlist I'm updating the media source through `ConcatenatingMediaSource.addMediaSource(mediaSource)` while the exoplayer is playing the list but whenever I called `addMediaSource` the app freezes and stop responding. I tried to call it from the background thread but I ended up with same results

**Comment by ojw28** [comment]
This sounds like it's probably an application issue. I think you'll need to provide a small app as source code that demonstrates the issue, if you want help figuring out what's wrong.

**Comment by vipafattal** [comment]
@ojw28 Thanks for pointing me that I had an issue with App.

Unfortunately, I had an issue in the way that I was adding media sources.
I was trying to add multiple media sources through using `ConcatenatingMediaSource` to combine `them in one source than adding them to the current playlist through `ConcatenatingMediaSource.addMediaSource()` which is wrong because  `addMediaSources` (please be advised it's the one that ends with 's') it's used to a  list of media source without concatenating them.
