### ISSUE TITLE
AMR file: Seeking resets position to 0

### ISSUE THREAD

**Issue by l20160606sy** [google/ExoPlayer#7151]
[No information provided]

**Comment by l20160606sy** [comment]
The suffix of the file link is AMR

**Comment by ojw28** [comment]
As documented on our [supported formats page](https://exoplayer.dev/supported-formats.html#progressive-container-formats), we don't support seeking into AMR files unless you enable constant bitrate seeking, [as documented here](https://exoplayer.dev/progressive.html#enabling-constant-bitrate-seeking).
