### ISSUE TITLE
Disable default subtitle

### ISSUE THREAD

**Issue by markdev12** [google/ExoPlayer#7158]
Hello,

 [Assume : https://domain.com/video/Duck_Fast.mkv] 

This Video Link Have Default/Embeded Subtitle in It. And when this  Video is Played ..Video plays with Subtitle .

How Can I Disable Default Subtitle?

**Comment by giladna** [comment]
@markdev12 

you have to use the DefaultTrackSelector to override the TextTracks to select the off option
see the Demo app code for detailed example.

```
private void overrideTrack(int rendererIndex, SelectionOverride override, DefaultTrackSelector.ParametersBuilder parametersBuilder) {
        if (override != null) {
            //actually change track.
            TrackGroupArray trackGroups = mappedTrackInfo.getTrackGroups(rendererIndex);
            parametersBuilder.setSelectionOverride(rendererIndex, trackGroups, override);
        } else {
            //clear all the selections if the override is null.
            parametersBuilder.clearSelectionOverrides(rendererIndex);
        }
        trackSelector.setParameters(parametersBuilder);
    }
```

**Comment by ojw28** [comment]
As @giladna notes, `DefaultTrackSelector` gives you everything that you need to do this.
