### ISSUE TITLE
Can't play the video without audio.

### ISSUE THREAD

**Issue by AlanCheen** [google/ExoPlayer#716]
I found Exoplayer can't play the video without audio but MediaPlayer can.

For examle uri :
>  http://taoletest.taolesoft.com/hls/90/30010660_399_13.m3u8

Is that a way to play it ?

Thank you in advance.

**Comment by Arqu** [comment]
By itself it is not currently supported (at least as far as I know), but I had the same requirement, to make it work you will have to modify the TS extractor a bit to skip the lookup of audio during playback, it can be made to work seamlessly ie. files with audio play the audio, files without just play the video.

**Comment by ojw28** [comment]
Audio only is supported. The problem with the media in this case is that the TS chunks *do* define a video track, it's just that they don't then include any samples. The TS chunks shouldn't define a video track if they don't contain any video.

**Comment by AlanCheen** [comment]
Thanks for your reply.
@ojw28  I think you might misunderstand me, I mean video only not audio.

**Comment by AlanCheen** [comment]
Hi @Arqu ,thanks for your reply.
Would you tell me more details because i don't understand what you said enough .

And here is an another problem:
I don't know whether the video contains audio or not,how to deal with this situation?

**Comment by AlanCheen** [comment]
@Arqu How to skip the lookup of audio during playback?

**Comment by ojw28** [comment]
Apologies for the lack of clarity, I got audio and video the wrong way around in my earlier response.

To clarify, the TS chunks in the affected media define *both* audio and video streams. If the media is video only, as in this case, then it should not define an audio stream and playback will work. Similarly, if the media is audio only, it should not define a video stream and playback will work.

So in conclusion, I think the media is at fault. To get the media to play, you can comment out the ```TS_STREAM_TYPE_AAC``` case [here](https://github.com/google/ExoPlayer/blob/master/library/src/main/java/com/google/android/exoplayer/extractor/ts/TsExtractor.java#L363), which will result in the audio stream being ignored. To re-iterate, the media should not define an audio stream in the first place, which would make commenting out this block unnecessary.

However to re-iterate, the

**Comment by Arqu** [comment]
In the TsExtractor I've edited this:
```
case TS_STREAM_TYPE_AAC:
            pesPayloadReader = new AdtsReader(output.track(TS_STREAM_TYPE_AAC));
            break;
```

to

```
case TS_STREAM_TYPE_AAC:
            if(!someboolean)pesPayloadReader = new AdtsReader(output.track(TS_STREAM_TYPE_AAC));
            break;
```

I've also changed the packetFinished function in the h264reader to:

```
if (ifrParserBuffer != null && foundFirstSample) {
      if (isKeyframe && !hasOutputFormat && sps.isCompleted() && pps.isCompleted()) {
        parseMediaFormat(sps, pps);
      }
      int flags = isKeyframe ? C.SAMPLE_FLAG_SYNC : 0;
      int size = (int) (totalBytesWritten - samplePosition);
      output.sampleMetadata(sampleTimeUs, flags, size, 0, null);
      foundFirstSample = false;
    }
```

**Comment by AlanCheen** [comment]
@ojw28 @Arqu 
Thank you for your reply!!

I have trid the way ojw28 told me : commenting out the `TS_STREAM_TYPE_AAC ` case .
  
That works well when video only , but in this case it also ingore the audio when the audio exists.

So how to control the value of `someboolean ` which mentioned by @Arqu ?

```
case TS_STREAM_TYPE_AAC:
            if(!someboolean)pesPayloadReader = new AdtsReader(output.track(TS_STREAM_TYPE_AAC));
            break;
```

**Comment by ojw28** [comment]
Please just fix the source content to not include an audio stream if it doesn't contain any audio. If it's not your content, please ask whoever is producing the content to do this.

If you're adding a boolean there, you're basically saying that you know what's in the media better than the media itself. Which implies that you have to know what its value should be yourself (e.g. through some additional metadata that you have). If you don't, then I can't see how you could correctly set it.

**Comment by Arqu** [comment]
@ojw28 is right, I pass that boolean around the entire exoplayer but that is because I'm using a lot of metadata not included in the media itself and I know beforehand what type of media I'll be playing. Also note that once you start messing with the audio in that way, you will also mess up timing and stuff around the video (maybe thats no longer the case with the media clock implementation) and all sorts of issues. TBH it is not worth doing like that, its easier to just properly encode the data in the first place.

**Comment by AlanCheen** [comment]
@Arqu @ojw28  
**Thanks very very much ,for your help and patience!!**
