### ISSUE TITLE
Is it possible to skip using presentation time stamp in processOutputBuffer?

### ISSUE THREAD

**Issue by januswa** [google/ExoPlayer#7163]
Can we skip using bufferPresentationTimeUs in processOutputBuffer() in MediaCodecVideoRenderer.java ? Is that even a possibility to skip relying on PTS and use some fixed repeat rate instead ? 
Looks like in the processOutputBuffer() , renderOutputBuffer() is being called and presentationTimeUs is being passed in as an argument. But, i don't see where this parameter is being used in the renderOutputBuffer() function.

**Comment by andrewlewis** [comment]
`MediaCodecVideoRenderer.processOutputBuffer` will (among other things) decide whether to drop the frame, and (if not) when to render it. It should be possible to implement custom frame dropping/rendering behavior by subclassing `MediaCodecVideoRenderer` and overriding this method. I'd probably start by using the existing implementation as a starting point then make customizations based on that. Please let us know if you run into any issues.

The reason `presentationTimeUs` is passed to the render methods is to allow subclasses to use the presentation time of the frame as part of the rendering process if they need to. An example use case would be to retrieve stabilization metadata keyed by timestamp from some other source and apply that when rendering the frame.

**Comment by januswa** [comment]
I changed the processOutputBuffer function to not use the following (by commenting out those sections of code) :
1. skipOutputBuffer(),
2. notifyFrameMetadataListener(), 
3. frameReleaseTimeHelper.adjustReleaseTime(),
4. treatDroppedBuffersAsSkipped and it's related logic.

Instead of using long adjustedReleaseTimeNs = frameReleaseTimeHelper.adjustReleaseTime(),
I am changing it to use systemTimeNs + xxxxxxx      (my frame time inNs)

Also changed unadjustedFrameReleaseTimeNs to be same as systemTimeNs

And in order to get to renderOutputBufferV21(codec, bufferIndex, presentationTimeUs, adjustedReleaseTimeNs);, I changed the earlyUs logic to use 70000 instead of 50000 (since my earlyUS now is 66666).

With these changes, I see that when I play forward stream (local ts file), it plays for a little bit and gets stuck at a certain point. Any insight would be helpful. Thank you !

**Comment by andrewlewis** [comment]
The release time ends up being passed to [`MediaCodec.releaseOutputBuffer`](https://developer.android.com/reference/android/media/MediaCodec#releaseOutputBuffer(int,%20long)) so please read the documentation there.

Based on your description, I wonder whether you are passing release times that are too far in the future. You probably still want to treat buffers as early if your frame time in nanoseconds is more than ~ 50 ms in the future, so I don't think the 'wait if early' logic should be changed.

To debug why rendering is getting stuck, I'd start by checking whether the video renderer is reporting itself as being ready (`MediaCodecVideoRenderer.isReady`), and step through `processOutputBuffer` in a debugger to check the player position and buffer time to see why nothing is being rendered.

**Comment by Swathi-Thirunarayanan** [comment]
@andrewlewis What does the rendering depend on? I am trying to render only one consecutive frame during each key press. I found that frames where rendered onto the surface after codec.releaseOutputBuffer(index, releaseTimeNs) in processOutputBuffer. But seems like even though I forced the releaseTimeNs to increment by 1ms (also found through observation that index was also incrementing by 1) the frames that are rendered onto the surface are very random. Seems like rendering depends on more parameters than releaseTimeNs and index! Is there any other parameter that needs to be considered when we try to manipulate rendering frame by frame?

**Comment by januswa** [comment]
When it was getting stuck, it was in buffering state. So, in ExoPlayerImplInternal.java, in doSomeWork(), I forced the renderer.isReady() to be true so that renderersAllowPlayback becomes true. In that case, it falls into the following section of code and sets the state to 'Ready':
else if (playbackInfo.playbackState == Player.STATE_BUFFERING  && shouldTransitionToReadyState(renderersAllowPlayback)) 
With this, I am able to play the .ts file completely, without getting stuck in buffering state. Although, it does struggle at a couple of points when transitioning from buffering to ready.

Now, the question I have is, when I change the repeat rate i.e.,
adjustedReleaseTimeNs = systemTimeNs + xxxxxxx, where xxxxx = 33.3ms*2 or 33.3ms*4 or 33.3ms*8   (Considering 30fps frame rate and 4 as repeat rate (33.3ms*4 = 133300000ns))
I do not see any change in the play duration of the file from start to end. Any insight on why it isn't change play duration ? I expect it to take longer to finish when I increase repeat rate from 2 to 4 to 8.

**Comment by andrewlewis** [comment]
Sorry for being slow to reply. I'm not sure adjusting the release time in the way you describe makes much sense, as that parameter is intended to synchronize video frame release to another time source, which is typically an `AudioTrack` position.

For your use case, assuming you only care about video, I think it would make more sense to make your subclass of `MediaCodecVideoRenderer` implement the `MediaClock` interface. In `processOutputBuffer` you can decide when to render by keeping track of time yourself (while the renderer is started) and returning false when the pending frame is not ready to render. Each time you render a frame you can increase the `MediaClock` position to the presentation time of the rendered frame. With this setup, I think you have control over the playback duration.
