### ISSUE TITLE
How to update ExoPlayer's progress bar while playing video on CastPlayer Android?

### ISSUE THREAD

**Issue by chinmaygghag** [google/ExoPlayer#7166]
I have a doubt regarding the ExoPlayer and CastPlayer. When I cast a video on the castplayer the progressbar on exoplayer is not being updated, also the remaining and the timme elapsed on exoplayer is not updating. I want to enable the functionality that will control the video (like play, pause, forward, rewind) from the exoplayer while the video is being played on the castPlayer. Also the exoplayer video view should show the text "Casting on " These are the dependecies

implementation 'androidx.mediarouter:mediarouter:1.1.0'
implementation 'com.google.android.exoplayer:extension-cast:2.11.3'
implementation 'com.google.android.exoplayer:exoplayer:2.11.3'

Can someone point me to an example implementation about the same?

I have gone through these example https://github.com/google/ExoPlayer/tree/release-v2/demos, https://github.com/googlecast/CastVideos-android.

I have this question on Stackoverflow as well 
https://stackoverflow.com/questions/60875569/how-to-update-exoplayers-progress-bar-while-playing-video-on-castplayer-android

**Comment by AquilesCanta** [comment]
We need, at least, sample media which which you can reproduce this issue.

@marcbaechinger, once @chinmaygghag provides media would you kindly try this in the demo app? I don't currently have any cast devices.

I'll take it on once we confirm this is an issue with ExoPlayer.

**Comment by chinmaygghag** [comment]
@AquilesCanta Thank you for you response.
It can be any video with m3u8 video format. I saw that the new screen opens up when the video is played on the CastPlayer by which we can control the video on the device which it is casted on. 

I want to know if there is any such possibility where once we cast the video on the chromecast, the current video view to be replaced by a video thumbnail and forward by 10 seconds and rewind by 10 seconds ( which I already have for exoPlayer) also work on the CastPlayer.

**Comment by AquilesCanta** [comment]
> I want to know if there is any such possibility where once we cast the video on the chromecast, the current video view to be replaced by a video thumbnail and forward by 10 seconds and rewind by 10 seconds ( which I already have for exoPlayer) also work on the CastPlayer.

If I'm understanding correctly, this is unrelated to the original post. The answer is that, unfortunately, you'll have to create your own custom receiver in order to alter the UI. There's documentation about this in the [Cast SDK documentation](https://developers.google.com/cast/docs/caf_receiver).

Regarding the original issue, are you saying that when casting any HLS video, the ExoPlayer progress bar is not updated? I don't think we've observed that in the past. Please provide precise repro steps and we'll have a look.
