### ISSUE TITLE
Getting NullPointerException when calling DrmSessionManager.release()

### ISSUE THREAD

**Issue by Gowsky** [google/ExoPlayer#7168]
### [REQUIRED] Issue description
Judging by stacktraces we see in Crashlytics, the crash occurs while ExoPlayer releases itself, most likely when finishig an Activity. We weren't able to reproduce it, as it occurrs on devices we don't have.

### [REQUIRED] Reproduction steps
We don't have any details about it yet, as Crashlytics log is all we have right now. 
It most likely occurrs after calling `SimpleExoPlayer#release()` on one of devices mentioned at the bottom of the page.

### [REQUIRED] A full bug report captured from the device
```
Fatal Exception: java.lang.NullPointerException
Attempt to invoke interface method 'void com.google.android.exoplayer2.drm.DrmSessionManager.release()' on a null object reference
com.google.android.exoplayer2.source.dash.DashMediaSource.releaseSourceInternal (DashMediaSource.java:730)
com.google.android.exoplayer2.source.BaseMediaSource.releaseSource (BaseMediaSource.java:186)
com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal (ExoPlayerImplInternal.java:957)
com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal (ExoPlayerImplInternal.java:850)
com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage (ExoPlayerImplInternal.java:402)
android.os.Handler.dispatchMessage (Handler.java:98)
android.os.Looper.loop (Looper.java:148)
android.os.HandlerThread.run (HandlerThread.java:61)
```
### [REQUIRED] Version of ExoPlayer being used
`2.11.1`

### [REQUIRED] Device(s) and version(s) of Android being used
Devices: OnePlus One, OnePlus5, Intel T2101L2B1C, Blackview BV7000, rockchip X99.02.3.01.d32, Xiaomi MIX, Nubia NX531J, JSR Innos_D6000
Android Versions: 5.1, 5.1.1, 6.0.1, 7.0, 7.1.2, 10

**Comment by andrewlewis** [comment]
Looking at the code, it's unclear how this can happen on 2.11.1. The field is final and should always get a non-null value. If a null value were passed in when building the media source it would have thrown NPE in prepareSourceInternal. Could you double-check your code to make sure you aren't passing a null `DrmSessionManager` when creating the media source factory anyway? I also can't see a reason this would be device-specific. @AquilesCanta please could you take a quick look to make sure I haven't missed something?

**Comment by AquilesCanta** [comment]
I agree with everything @andrewlewis points out. 

> Could you double-check your code to make sure you aren't passing a null DrmSessionManager when creating the media source factory anyway? 

Please check this. Even if passing null, this would mean ExoPlayer is calling release without calling prepare first, which sounds unlikely. Your app is not modifying ExoPlayer code either, is it?

In the most recent release version, a null value is even more likely since it's replaced during construction for a dummy DRM session manager, so perhaps it's also worth updating the ExoPlayer version to be safe.

**Comment by Gowsky** [comment]
As far as I can see we pass `null` for `DrmSessionManager` while creating MediaSource only when we get `UnsupportedDrmException` while building `DefaultDrmSessionManager<ExoMediaCrypto>`. Could it be the case since the crash occurrs on some unpopular devices mentioned in the issue?

**Comment by AquilesCanta** [comment]
I suggest you pass a dummy drm session manager in that case. Note that the null value shouldn't cause the NPE in release either, but null values are not accepted in the version you are using.

Do you think you can reach back after trying this in the wild? If so, can we close the comment until you are sure you can reproduce even after removing the null value?

**Comment by Gowsky** [comment]
Yes, I think so. Though the company I work for releases updates to their apps once a couple of months, so it will take a while until we know if it resolves our problem.

**Comment by amiantoch** [comment]
Hi, 
the same issue can be seen in our Crashlytics logs as well, since we updated from ExoPlayer version 2.10.6 to 2.11.3.

Stacktrace:
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'void com.google.android.exoplayer2.drm.DrmSessionManager.release()' on a null object reference
       at com.google.android.exoplayer2.source.dash.DashMediaSource.releaseSourceInternal(DashMediaSource.java:731)
       at com.google.android.exoplayer2.source.BaseMediaSource.releaseSource(BaseMediaSource.java:186)
       at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:957)
       at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:850)
       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:402)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:154)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```

Judging by the logs, it seems to happen when the Activity has been destroyed and recreated. 

We can be sure that the `DrmSessionManager` passed to the media source factory is not `null`, since this would appear in our logs.

Crashlytics reported Android versions:
Android 5, Android 6, Android 7, Android 8, Android 9, Android 10
Crashlytics reported devices:
HUAWEI, CHUWI, samsung, realtek, YUFLY, Netxeon, OnePlus, Intel, Xiaomi, etc.

**Comment by ojw28** [comment]
I agree with what others are saying here. The only possible way this can happen is if null is passed to the `DashMediaSource.Factory.setDrmSessionManager` (short of something super weird, like a Proguard issue or something wrong with the VM). It's easy to validate this by reading the code of that class (unless you can see another way). The latest code in `dev-v2` is robust against null being passed (we replace it with a dummy instance internally).

> Even if passing null, this would mean ExoPlayer is calling release without calling prepare first, which sounds unlikely.

I don't think this is true. The stack trace includes [`com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage (ExoPlayerImplInternal.java:402)`](https://github.com/google/ExoPlayer/blob/r2.11.3/library/core/src/main/java/com/google/android/exoplayer2/ExoPlayerImplInternal.java#L402), which indicates that we've already encountered a `RuntimeException` and are failing again whilst trying to clean things up. It's likely that the initial `RuntimeException` was a `NullPointerException` during preparation.

I would suggest we:

1. Cherry-pick the change that makes the code robust against null into any future 2.11.x release, if there is one before it gets picked up in 2.12.0.
1. We should probably surround [this line of code](https://github.com/google/ExoPlayer/blob/r2.11.3/library/core/src/main/java/com/google/android/exoplayer2/ExoPlayerImplInternal.java#L957) with a try/catch "There's nothing we can do." block, similar to the ones further up in that method. I will do this (we should also cherry-pick that if there's another 2.11.x release). This will not prevent the playback failure, but will prevent the process from crashing. Instead, the original failure will be propagated properly as a playback error.

**Comment by amiantoch** [comment]
> It's likely that the initial RuntimeException was a NullPointerException during preparation.

In our Logs this seems to be the case, most of the crashes happen after `simpleExoPlayer.prepare` has been called.

**Comment by ojw28** [comment]
Changes (1) and (2) will be picked up in 2.11.5, which should go out sometime next week.
