### ISSUE TITLE
No Audio in Offline playback

### ISSUE THREAD

**Issue by Taranlayal10** [google/ExoPlayer#7169]
Hi

I am trying to play a dash (.mpd) content in offline mode. Only video is coming on player without any audio. Please help

**Comment by andrewlewis** [comment]
Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md). If you're unable to share bug reports or test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Please also update this issue to indicate you’ve done this.

Does the stream play correctly in non-offline mode? If you do any stream selection for downloading please check that and share the code.
