### ISSUE TITLE
setting builder.mediaLoadTimeOutInMs = 1000 ms not working. exo version 2.9.1

### ISSUE THREAD

**Issue by nitinjain12** [google/ExoPlayer#7170]
we are using exo ima extension v2.9.1. we want mediaLoadTimeOutInMs = 1000 ms of preroll. 
but Ad wait for 8 sec to throw the media timeout error. It increase the latency of the content startup. 

              ImaAdsLoader.Builder builder = new ImaAdsLoader.Builder(context);

                if (vastTimeOutInMs != AdData.NOT_SET) {
                    builder.setVastLoadTimeoutMs(vastTimeOutInMs);
                }
                if (mediaLoadTimeOutInMs != AdData.NOT_SET) {
                    builder.setMediaLoadTimeoutMs(mediaLoadTimeOutInMs);
                }
                 builder.setAdEventListener(this);
                adsLoader = builder.buildForAdTag(adTagUri);

**Comment by andrewlewis** [comment]
I think I've seen this value be ignored by the IMA SDK in the past. I will check again and ask them if they could take a look if needed. Thanks for the report.

**Comment by nitinjain12** [comment]
Thank you @andrewlewis for your reply. It will be really helpful if we get some workaround as well.
Adding more info we are using the below IMA SDK version.
com.google.ads.interactivemedia.v3:interactivemedia:3.10.9

**Comment by nitinjain12** [comment]
@andrewlewis Any update on this?

**Comment by andrewlewis** [comment]
No updates yet. I will update here when we have made progress.

**Comment by nitinjain12** [comment]
ok @andrewlewis Thank you :)

**Comment by andrewlewis** [comment]
Tracked by [Internal: b/144008313].

**Comment by andrewlewis** [comment]
Update: A fix has been submitted and we should be able to pick this up in the next IMA SDK release (not sure when that will be yet).

**Comment by nitinjain12** [comment]
Thank you @andrewlewis for your support.
