### ISSUE TITLE
OnTrackChnaged method called twice while click next button . why?

### ISSUE THREAD

**Issue by WaqasYousafy786** [google/ExoPlayer#7173]
OnTrachChanged called twice . when i click on next or previous button of player . 
I am beginner of exoplayer user

**Comment by andrewlewis** [comment]
I think what's going on is that at the moment you click next/previous, the tracks for the new playlist item are sometimes not known. In this case you get a tracks changed notification with empty tracks, then once the media is prepared for playback you get another notification with the actual tracks.

You can see this if you look at `EventLogger` output in logcat when seeking in a playlist in the demo app. If the next media item actually is buffered when seeking to the next item I think you'll (currently) see only one tracks changed notification, as in this case the tracks are known.
