### ISSUE TITLE
Hls not live streaming doesn't set EXT-X-SEQUENCE to 0

### ISSUE THREAD

**Issue by github-eugene** [google/ExoPlayer#7178]
I am using ExoPlayer to play stream url .m3u8. I am not using some special, only base realisation :

   private val trackSelector = DefaultTrackSelector(AdaptiveTrackSelection.Factory())
    private val rendererFactory = DefaultRenderersFactory(context)
    private val loadControl = DefaultLoadControl()

    private val simplePlayer: SimpleExoPlayer = ExoPlayerFactory.newSimpleInstance(
        context,
        rendererFactory,
        trackSelector,
        loadControl
    )

  simplePlayer.prepare(
                HlsMediaSource.Factory(
                    DefaultHttpDataSourceFactory(
                        "tv-streaming"
                    )
                )
                    .createMediaSource("myUrl-with-timeshift353535353.m3u8")
            )

This link binded with some begin time. When track played, i got info tag in segments, like
EXT-X-SEQUENCE: n, where n = number of segment.
and when i start play, n = 0.
but if i use another url, his EXT-X-SEQUENCE begins not from 0, but from last url current sequence position. Is there some way to clear current sequence position when i try to use another url?

**Comment by andrewlewis** [comment]
I'm not sure what you are trying to do here. Please could you try restating the question in terms of ExoPlayer APIs?
