### ISSUE TITLE
DRM + subtitles

### ISSUE THREAD

**Issue by Belozerow** [google/ExoPlayer#718]
Hi
Is it possible to play widevine dash with subtitles?
I found that TextTrackRenderer has no drm parameters, so drm session doesn't decode subtitles and subtitle parser get encoded text.

Can you give me any advices how to implement this feature?
How can I decode subtitles input stream with DrmSessionManager?

**Comment by ojw28** [comment]
This is not supported. Why would you need to DRM protect subtitles?

**Comment by Belozerow** [comment]
Because my client say so :(
Is it possible somehow to decode inputstream before pass it into parserhelper?

**Comment by ojw28** [comment]
I would encourage you to discuss with your client why they think that's a sensible requirement. What are they actually trying to achieve? Why is just sending the subtitle over https not sufficient?

**Comment by Belozerow** [comment]
Probably it is because of offline playback.

Btw, offline doesn't work for me too, because of fragmented mp4.

**Comment by ojw28** [comment]
We haven't seen any other demand for this feature, including from major service providers who are distributing premium content and supporting offline playback. Hence it's not something we'll be looking to support in the near future.
