### ISSUE TITLE
Audiofocus Broken after AUDIOFOCUS_LOSS_TRANSIENT

### ISSUE THREAD

**Issue by PaulWoitaschek** [google/ExoPlayer#7182]
On ExoPlayer 2.11.3, audiofocus is broken when receiving a `AUDIOFOCUS_LOSS_TRANSIENT`.
In that case the AudioFocusManager receives no furhter events and exoplayer is unable to play any longer.
This can be reproduced using the following steps:
* Clone uamp: https://github.com/android/uamp
* Update exoplayer from 2.10.0 to 2.11.3
* Run the app and play a song
* Call the phone using Google Duo

Now after the call the UI still shows playing but isn't. This can only be fixed by using another media player and let it request audio focus.

**Comment by PaulWoitaschek** [comment]
It would be great if a fix went already into the next release as this bug renders exoplayer completely unusable.

**Comment by ojw28** [comment]
I can't reproduce this using normal phone calls (which should be the same in terms of how audio focus works). Are you sure this isn't a Due issue?

**Comment by ojw28** [comment]
I think it's a Duo bug where they should be releasing audio focus but aren't. If you kill the Duo process after the call then playback does resume.

That said, the state ExoPlayer ends up in is definitely non-ideal (it's waiting indefinitely for Duo to release audio focus, which it's not doing). If the user toggles to pause and back to play, we should be more aggressive at trying to take audio focus back.

> this bug renders exoplayer completely unusable

Has it also been "completely unusable" for the past 18 months, because the current behaviour appears to have existed ever since we added audio focus management in 2.9.0 :)...

**Comment by PaulWoitaschek** [comment]
Ah very interesting. 

In my testing it was working with UAMP and exoplayer 2.10.0
But it only **appeared** to be working in 2.10.0 because the time displayed in the player was advancing, but there is no actual audio being played.

So there definitely is a behavior change anywhere. Maybe introduced to the change with the event handler introduced between these releases.

> If the user toggles to pause and back to play, we should be more aggressive at trying to take audio focus back.

Yes that's a very good idea.
I still think there is something different in how exoplayer handles this. Because when you use Google Music and then receive a duo call, after the call the player is in the paused state. And when you press play the playback continues.
When you use my appication (voice), after the call the player is still shown as playing yet it's not advancing. I wonder where that comes from.

**Comment by ojw28** [comment]
I reported the Duo issue to the relevant team [Internal ref: 153249585]

**Comment by ojw28** [comment]
User recovery should be possible with the first of the two patches referenced above. The second patch fixes an additional edge case we discovered, but is unlikely to occur in practice.

**Comment by ojw28** [comment]
Please verify with dev-v2-r2.11.4 if possible, prior to us cutting the release. The cherry-pick wasn't totally straightforward, so verification would be appreciated.

**Comment by PaulWoitaschek** [comment]
I couldn't verify it before the release. 
However it works fine, thanks a lot!
