### ISSUE TITLE
seek problem

### ISSUE THREAD

**Issue by ccflyy** [google/ExoPlayer#7183]
player.setLoadControl(new DefaultLoadControl.Builder()
            .setBufferDurationsMs(1000x60x6, 1000x60x8,1500,2000)
            .createDefaultLoadControl());

When I seek progress, the original buffer progress will be cleared and the buffer will start again

**Comment by ojw28** [comment]
The format is probably not seekable. Please see [this FAQ](https://exoplayer.dev/troubleshooting.html#why-are-some-media-files-not-seekable). Depending on the stream type, you may be able to enable seeking by enabling [constant bitrate seeking](https://exoplayer.dev/progressive.html#enabling-constant-bitrate-seeking).
