### ISSUE TITLE
DRM-protected content playback stuck after ad playback (VMAP)

### ISSUE THREAD

**Issue by 07steven01** [google/ExoPlayer#7188]
### [REQUIRED] Issue description
When playing a Widevine DRM protected video content (secure) along with VMAP ads the player does not resume content playback when a pre-roll ad has completed. This doesn't happen with Widevine Clear streams. 

### [REQUIRED] Reproduction steps
1) In ExoPlayer demo app code, in demos/main/media.exolist.json edit the entry VW Secure HD (MP4,H265) to include the ad info of the "VMAP pre-, mid- and post-rolls, single ads" entry (to be found further down in the media.exolist.json file)
   [combined entry]
     "name": "WV: Secure HD (MP4,H265)",
        "uri": "https://storage.googleapis.com/wvmedia/cenc/hevc/tears/tears_hd.mpd",
        "drm_scheme": "widevine",
        "drm_license_url": "https://proxy.uat.widevine.com/proxy?provider=widevine_test",
        "ad_tag_uri": "https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpost&cmsid=496&vid=short_onecue&correlator="
2) Compile and run the exoplayer demo with extenstions flavour
3) Now choose the VW Secure HD (MP4, H265) entry for playback
4) Wait until pre-roll ad playback completes

Expected result: Video playback is resumed
Actual result: Video playback is stuck

### [REQUIRED] Link to test content
https://drive.google.com/open?id=115Vdcs80frzeoYtgapZDmqn1l0z07TdH
{
"name": "WV: Secure HD (MP4,H265)",
        "uri": "https://storage.googleapis.com/wvmedia/cenc/hevc/tears/tears_hd.mpd",
        "drm_scheme": "widevine",
        "drm_license_url": "https://proxy.uat.widevine.com/proxy?provider=widevine_test",
        "ad_tag_uri": "https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpost&cmsid=496&vid=short_onecue&correlator="
}
### [REQUIRED] A full bug report captured from the device
https://drive.google.com/open?id=1ARnREKjruCI5r0tyUfD-M8QosA-w0K2G

### [REQUIRED] Version of ExoPlayer being used
2.11.1

### [REQUIRED] Device(s) and version(s) of Android being used
Android Emulator/Android 10; Xiaomi Mi A3/Android 9

**Comment by AquilesCanta** [comment]
I think this is an issue we are already aware of and working on.

The underlying cause is that since we moved DRM to the SampleQueue, an assumption made by the ClippingMediaPeriod is no longer true. We'll be adding a workaround to fix clipping in the short term sometime soon, and then work towards a longer term solution. Once we push the fix to the dev branch, a commit will be referenced here.

**Comment by ojw28** [comment]
This will be fixed in 2.11.4. Please verify using dev-v2-r2.11.4 or dev-v2 if possible.

**Comment by 07steven01** [comment]
Verified (ca 10 times). Works as expected.  
            
          
     
      
       
        Dnia 7 kwietnia 2020 15:16 Oliver Woodman &lt;notifications@github.com&gt; napisał(a):
       
    
       
         
 This will be fixed in 2.11.4. Please verify using dev-v2-r2.11.4 or dev-v2 if possible.
