### ISSUE TITLE
AtomParsers. Subtitles 'subt' handler with 'stpp' codec

### ISSUE THREAD

**Issue by Belozerow** [google/ExoPlayer#719]
AtomParsers in parseTrak check the track type for 'vide', 'soun', 'sbtl' and 'text', but not for 'subt' (http://www.mp4ra.org/handler.html#subt).

The same thing with 'sttp' codec in parseStsd (http://www.mp4ra.org/codecs.html)

Is it correct?

**Comment by ojw28** [comment]
This is tracked by #689. We have a fix that will add support for subt(type) + stpp(codec) support in the next day or so. We won't be supporting wvtt(codec) in the near future though, since it's a non-trivial amount of work.

**Comment by ojw28** [comment]
Please track using #689.
