### ISSUE TITLE
how use custom_layou in playerView ?

### ISSUE THREAD

**Issue by abolfazlkalamati** [google/ExoPlayer#7190]
when use custom_layout for exo player with child view with the same id in exo_playeback_controller_view file, for example exo_play, exo_position,exo_ffwd and etc, and set custom_layout in PlayerView with controller_layout_id="@layout/custom_layout", it's enough or we must doing other work to working widgets in custom_layou and connected to exo player?
i'm doing this work and show custom_layout when running player in service but but  custom_layout not working and can't play or pause audio from custom_layout .

**Comment by AquilesCanta** [comment]
@marcbaechinger Marc could you take a look at this?

**Comment by marcbaechinger** [comment]
Yes, setting `controller_layout_id="@layout/custom_layout"` is sufficient for telling the `PlayerView` to use a custom layout file for the controller:

1) I copied `exo_playback_control_view.xml` and removed everything except the play/pause buttons. Then I stored it in the file `custom_control_view.xml` in the layout directory of the app:

```
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
  xmlns:tools="http://schemas.android.com/tools"
  android:layout_width="match_parent"
  android:layout_height="wrap_content"
  android:layout_gravity="bottom"
  android:layoutDirection="ltr"
  android:background="#CC000000"
  android:orientation="vertical"
  tools:targetApi="28">

  <LinearLayout
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:gravity="center"
    android:paddingTop="4dp"
    android:orientation="horizontal">

    <ImageButton android:id="@id/exo_play"
      style="@style/ExoMediaButton.Play"/>
    <ImageButton android:id="@id/exo_pause"
      style="@style/ExoMediaButton.Pause"/>

  </LinearLayout>

</LinearLayout>
```
2) I referenced the id in PlayerView which is in the layout file of the activity:

```
<com.google.android.exoplayer2.ui.PlayerView android:id="@+id/player_view"
      app:controller_layout_id="@layout/custom_control_view"
      android:layout_width="match_parent"
      android:layout_height="match_parent"/>
```

When starting the demo app, I get the player with only a play/pause button.

Can you give me some more details on what is not working? Do you see some error messages? 
Can you post a copy of your custom layout file and the PlayerView element of you activity layout?

**Comment by abolfazlkalamati** [comment]
thank you for answer, this is my custom_layout : 
`<?xml version="1.0" encoding="utf-8"?>
<layout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools">

    <androidx.constraintlayout.widget.ConstraintLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <com.google.android.material.card.MaterialCardView
            android:id="@+id/cv_podcast_cover"
            android:layout_width="match_parent"
            android:layout_height="0dp"
            android:layout_marginStart="@dimen/spacing_15x"
            android:layout_marginTop="@dimen/spacing_7x"
            android:layout_marginEnd="@dimen/spacing_15x"
            app:cardCornerRadius="@dimen/spacing_5x"
            app:layout_constraintDimensionRatio="w,1:1"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent">

            <androidx.constraintlayout.widget.ConstraintLayout
                android:layout_width="match_parent"
                android:layout_height="match_parent">

                <androidx.appcompat.widget.AppCompatImageView
                    android:id="@+id/iv_podcast_cover"
                    android:layout_width="match_parent"
                    android:layout_height="0dp"
                    android:layout_margin="@dimen/spacing_10x"
                    app:layout_constraintBottom_toBottomOf="parent"
                    app:layout_constraintDimensionRatio="w,1:1"
                    app:layout_constraintEnd_toEndOf="parent"
                    app:layout_constraintStart_toStartOf="parent"
                    app:layout_constraintTop_toTopOf="parent"
                    tools:src="@drawable/ic_about" />

            </androidx.constraintlayout.widget.ConstraintLayout>

        </com.google.android.material.card.MaterialCardView>
        
        <com.google.android.exoplayer2.ui.DefaultTimeBar
            android:id="@+id/exo_progress"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginStart="@dimen/spacing_5x"
            android:layout_marginTop="@dimen/spacing_5x"
            android:layout_marginEnd="@dimen/spacing_5x"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toBottomOf="@+id/cv_podcast_cover"
            app:played_color="@color/colorGreen"
            app:unplayed_color="@color/colorGray" />

        <androidx.appcompat.widget.AppCompatTextView
            android:id="@+id/exo_position"
            style="@style/Headline6"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginStart="@dimen/spacing_6x"
            android:layout_marginTop="@dimen/spacing_base"
            android:layout_marginEnd="@dimen/spacing_6x"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintTop_toBottomOf="@+id/exo_progress"
            tools:text="8:12" />

        <androidx.appcompat.widget.AppCompatTextView
            android:id="@+id/exo_duration"
            style="@style/Headline6"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginStart="@dimen/spacing_6x"
            android:layout_marginTop="@dimen/spacing_base"
            android:layout_marginEnd="@dimen/spacing_6x"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toBottomOf="@+id/exo_progress"
            tools:text="22:32" />

        <androidx.appcompat.widget.LinearLayoutCompat
            android:id="@+id/ll_podcast_tools_bottom"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginTop="@dimen/spacing_base"
            android:layout_marginBottom="@dimen/spacing_5x"
            android:gravity="center"
            android:orientation="horizontal"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toBottomOf="@+id/exo_duration">

            <androidx.appcompat.widget.AppCompatImageView
                android:id="@+id/exo_ffwd"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginStart="@dimen/spacing_3x"
                android:layout_marginEnd="@dimen/spacing_3x"
                app:srcCompat="@drawable/ic_ffwd" />

            <androidx.appcompat.widget.AppCompatImageView
                android:id="@+id/exo_next"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginStart="@dimen/spacing_3x"
                android:layout_marginEnd="@dimen/spacing_3x"
                app:srcCompat="@drawable/ic_next" />

            <FrameLayout
                android:layout_width="wrap_content"
                android:layout_height="wrap_content">

                <androidx.appcompat.widget.AppCompatImageView
                    android:id="@id/exo_pause"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_marginStart="@dimen/spacing_3x"
                    android:layout_marginEnd="@dimen/spacing_3x"
                    app:srcCompat="@drawable/ic_play" />

                <androidx.appcompat.widget.AppCompatImageView
                    android:id="@id/exo_play"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_marginStart="@dimen/spacing_3x"
                    android:layout_marginEnd="@dimen/spacing_3x"
                    app:srcCompat="@drawable/ic_play" />

            </FrameLayout>


            <androidx.appcompat.widget.AppCompatImageView
                android:id="@+id/exo_prev"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginStart="@dimen/spacing_3x"
                android:layout_marginEnd="@dimen/spacing_3x"
                app:srcCompat="@drawable/ic_prev" />

            <androidx.appcompat.widget.AppCompatImageView
                android:id="@+id/exo_rew"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginStart="@dimen/spacing_3x"
                android:layout_marginEnd="@dimen/spacing_3x"
                app:srcCompat="@drawable/ic_rew" />

        </androidx.appcompat.widget.LinearLayoutCompat>

    </androidx.constraintlayout.widget.ConstraintLayout>

</layout>`

and set with app:controller_layout_id="@layout/custom_layout" : 

`<?xml version="1.0" encoding="utf-8"?>
<layout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto">

    <androidx.constraintlayout.widget.ConstraintLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent">


        <com.google.android.exoplayer2.ui.PlayerView
            android:id="@+id/playerView"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:auto_show="true"
            app:controller_layout_id="@layout/layout_podcast_controller_view"
            app:fastforward_increment="3000"
            app:hide_on_touch="false"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent"
            app:player_layout_id="@layout/podcast_player_view"
            app:resize_mode="fixed_height"
            app:rewind_increment="3000"
            app:show_buffering="always"
            app:show_timeout="0"
            app:surface_type="texture_view"
            />

    </androidx.constraintlayout.widget.ConstraintLayout>

 
</layout>`

after review my code today, i think don't set true exoPlayer for playerView.
i have inner class in MyService with below code : 

` inner class PlayerServiceBinder() : Binder() 
{

        val service
            get() = this@AudioService
        val exoPlayer
            get() = this@AudioService.exoPlayer

}`

and confige attr exo in service and get exo from service in my fragment with this code : 

`private val connection = object : ServiceConnection {

        override fun onServiceConnected(name: ComponentName?, service: IBinder?) {

            val binder = service as AudioService.PlayerServiceBinder
            audioService = binder.service
            // Attach the ExoPlayer to the PlayerView.
            playerView.player = binder.exoPlayer

        }
        override fun onServiceDisconnected(p0: ComponentName?) {
            audioService = null
        }

      }`

and set connection when bind service , i have not any error, when run app show custom view and play audio in push notificaation but not progress exo_progress and time duration or position or not working any buttom for example exo_play or pause, i  jaut can see mu custom_view.

**Comment by marcbaechinger** [comment]
Overriding the layout with the attribute as you describe should work. I've seen/done this various times.

I'd recommend to copy the original layout file again, rename it and then set the layout file id:

```
<com.google.android.exoplayer2.ui.PlayerView android:id="@+id/player_view"
      app:controller_layout_id="@layout/custom_control_view"
      android:layout_width="match_parent"
      android:layout_height="match_parent"/>
``` 

Only remove elements and probably at the beginning just a single element. A very small change. Then check if it works. Once it works you can do the larger changes you had in mind. Probably also step by step. So you can narrow down the problem.
