### ISSUE TITLE
Workaround for empty timeline in PlaybackStatsListener

### ISSUE THREAD

**Issue by jakoss** [google/ExoPlayer#7193]
### [REQUIRED] Question
First callback for a new playlist have empty timeline. I'm aware that it will be fixed in 2.12, but i'm looking for workaround for now.

I'm not sure how to get my id reliably in this case:
```kotlin
exoPlayer.addAnalyticsListener(PlaybackStatsListener(true) { eventTime, playbackStats ->
            if (eventTime.timeline.isEmpty) {
                Timber.d("Empty timeline")
                // FIXME : need to get proper tag here somehow
                return@PlaybackStatsListener
            }

            val tag = eventTime.timeline.getWindow(
                eventTime.windowIndex,
                Timeline.Window()
            ).tag as? MediaDescriptionCompat
            val id = tag?.mediaId?.toInt() ?: return@PlaybackStatsListener
            Timber.d("[AnalyticsListener] Playback [${id}] - ${playbackStats.totalPlayTimeMs}")
        })
```

There is possibility that `MediaSource` will be removed from `ConcatenatingMediaSource` after track change (this is implementation of temporary item in queue).

**Comment by AquilesCanta** [comment]
@tonihei Can you take a look at this?

**Comment by tonihei** [comment]
That's an interesting problem. And yes, you are right that it will be solved in 2.12.   (For reference, this issue is #5155).

Generally speaking, only the first item that will be played has the initial unassigned empty timeline. So you could work around that by saving the `MediaDescriptionCompat` of the item that will be played after the call to `player.prepare`. You should know this in code depending on whether you reset the position in `prepare`:
 - If you do reset, the first first item in the playlist will be played first. 
 - If you don't reset the position, then you can query `player.getCurrentWindowIndex` to know which item will play first. 

Once you know the item, you can immediately query `concatenatingMediaSource.getMediaSource(index).getTag()` to retrieve the `MediaDescriptionCompat` before playback even starts and then use it in your listener for the case of the empty timeline. 

That's obviously way more complicated than it should be, but I can't think of another workaround for now.

> There is possibility that MediaSource will be removed from ConcatenatingMediaSource after track change (this is implementation of temporary item in queue).

This shouldn't be an issue in itself because the `eventTime.timeline` object still contains the item even if it was removed later.

**Comment by jakoss** [comment]
> This shouldn't be an issue in itself because the eventTime.timeline object still contains the item even it was removed later.

Yes, i was asking within context of empty timeline. Thank you very much for details guidance. I'll try to adapt this way.

**Comment by jakoss** [comment]
Ok, so it seems to be working for the first playlist, but i have an issue when changing playlist.

I play one album and then i want to change to another one. I expect that the last item on first album i have listen to will be reported. But the callback is called with empty timeline for it. So i get empty timeline for the first AND the last item while changing.

Full steps:
- I create `ConcatenatingMediaSource`, i set `MediaDescriptionCompat` for the first item.
- Then i listen to few tracks (raporting here is just fine)
- Then i change album (again - i create new `ConcatenatingMediaSource` and set new `MediaDescriptionCompat` for the first item). And here - i expect that the last track of first album gets reported. And it does - but timeline is empty for it. 

Whole event callback:
```kotlin
exoPlayer.addAnalyticsListener(PlaybackStatsListener(true) { eventTime, playbackStats ->
            if (eventTime.timeline.isEmpty) {
                if (firstMediaDescription!= null) {
                    Timber.d("[AnalyticsListener] Playback [${firstMediaDescription.mediaId}] - ${playbackStats.totalPlayTimeMs.getAsSeconds()}")
                } else {
                    Timber.e("[AnalyticsListener] Empty timeline without first queue item set")
                }
                return@PlaybackStatsListener
            }

            val tag = eventTime.timeline.getWindow(
                eventTime.windowIndex,
                Timeline.Window()
            ).tag as? MediaDescriptionCompat
            val id = tag?.mediaId?.toInt() ?: return@PlaybackStatsListener
            Timber.d("[AnalyticsListener] Playback [${queueItem.trackId}] - ${playbackStats.totalPlayTimeMs.getAsSeconds()}")
        })
```

Whole log after changing album:
```
// changed album here
D/PlayerService$onCreate: [AnalyticsListener] Empty timeline without first queue item set
D/PlayerService$onCreate: [AnalyticsListener] Playback [115033] - 18 (the id here is from `firstMediaDescription` of the new playlist but should be taken from old timeline (from previous album).
```

I'm not sure if described it propely - please let me know if you have any more questions about that

**Comment by jakoss** [comment]
@tonihei could you take another look at this?

**Comment by tonihei** [comment]
Did you try to call playbackStatsListener.finishAllSessions() just before the second prepare() call? This may work I think.

**Comment by jakoss** [comment]
Unfortunetely, when i do that i have pretty frequent (but seems to be random) NullPointerExceptions

```
Caused by: java.lang.NullPointerException
        at com.google.android.exoplayer2.util.Assertions.checkNotNull(Assertions.java:147)
        at com.google.android.exoplayer2.analytics.PlaybackStatsListener.onSessionFinished(PlaybackStatsListener.java:220)
        at com.google.android.exoplayer2.analytics.DefaultPlaybackSessionManager.handleTimelineUpdate(DefaultPlaybackSessionManager.java:118)
        at com.google.android.exoplayer2.analytics.PlaybackStatsListener.onTimelineChanged(PlaybackStatsListener.java:266)
        at com.google.android.exoplayer2.analytics.AnalyticsCollector.onTimelineChanged(AnalyticsCollector.java:422)
```

**Comment by tonihei** [comment]
Ah, indeed. There is a bug in finishAllSessions() that gets triggered if you use and keep the listener registered on a player. I'll fix that on the dev branch. As a workaround, you can call finishAllSession() and then remove the listener from the player, and add a brand new one for the new playlist.

**Comment by jakoss** [comment]
I came up with this:
```kotlin
class PlaybackStatsHandler(
    private val player: SimpleExoPlayer,
    private val queueRepository: QueueRepository
) {

    /**
     * This field is used as workaround for issue:
     * https://github.com/google/ExoPlayer/issues/7193
     * We can remove this after ExoPlayer 2.12 release
     */
    private var firstQueueItemInPlaylist: QueueItem? = null

    private var currentStatsListener: PlaybackStatsListener? = null

    fun startPlayback() {
        currentStatsListener?.let {
            it.finishAllSessions()
            player.removeAnalyticsListener(it)
        }
        val statsListener = createStatsListener()
        currentStatsListener = statsListener
        player.addAnalyticsListener(statsListener)
    }

    fun setFirstQueueItem(queueItem: QueueItem) {
        firstQueueItemInPlaylist = queueItem
    }

    private fun createStatsListener() = PlaybackStatsListener(true) { eventTime, playbackStats ->
        if (eventTime.timeline.isEmpty) {
            // this occurs for the first track in playlist. This is a known bug in ExoPlayer
            // https://github.com/google/ExoPlayer/issues/7193
            // We can remove this after ExoPlayer 2.12 release
            val firstQueueItem = firstQueueItemInPlaylist
            if (firstQueueItem != null) {
                Timber.d("[AnalyticsListener] Playback [${firstQueueItem.trackId}] - ${playbackStats.totalPlayTimeMs.getAsSeconds()}")
                firstQueueItemInPlaylist = null
            } else {
                Timber.e("Empty timeline without first queue item set")
            }
            return@PlaybackStatsListener
        }

        val tag = eventTime.timeline.getWindow(
            eventTime.windowIndex,
            Timeline.Window()
        ).tag as? MediaDescriptionCompat
        val id = tag?.mediaId?.toInt() ?: return@PlaybackStatsListener
        val queueItem = queueRepository.getQueueItemById(id) ?: return@PlaybackStatsListener
        Timber.d("[AnalyticsListener] Playback [${queueItem.trackId}] - ${playbackStats.totalPlayTimeMs.getAsSeconds()}")
    }
}
```
Method `startPlayback` is called before preparing new mediaSource. Method `setFirstQueueItem` is called in the moment i know which track is played first.

It doesn't crash and it sometimes gives a proper results. But, sometimes (seems like one in 3 trials) it reports zero time on playlist change.

Sometimes it works properly:
```
D/PlaybackStatsHandler$createStatsListener: [AnalyticsListener] Playback [65876] - 12
D/PlaybackRepository$reportPlayback: Playback [65876] - 12 <- **This is from our custom playback reporter which gives expected and proper result**
```

But sometimes it still returns "zero" time and empty timeline.

```
D/PlaybackStatsHandler$createStatsListener: [AnalyticsListener] Playback [8350] - 0
E/PlaybackStatsHandler$createStatsListener: Empty timeline without first queue item set
D/PlaybackRepository$reportPlayback: Playback [8350] - 13 <- **This is from our custom playback reporter which gives expected and proper result**
```

It seems like some race condition here, i'm still trying to locate probably cause on our side.
If it help - we are creating our media source like that (heavily redacted):

```kotlin
playbackStatsHandler.startPlayback()

val mediaSource = ConcatenatingMediaSource(false, true, DefaultShuffleOrder(0))

tracks.forEachIndexed { index, queueItem ->
    mediaSource.addMediaSource(
        mediaSourcePreparer.prepare(queueItem, useCache) // we have different strategies for multiple audio sources
    )
    if (index == startPosition) { // start position holds index we want to start playback on
        // start playback right away when position is ready
        exoPlayer.prepare(mediaSource)
        playbackStatsHandler.setFirstQueueItem(queueItem)
        try {
            exoPlayer.seekTo(index, 0)
        } catch (ex: IllegalSeekPositionException) {
            Timber.e(ex)
        }
    }
}
exoPlayer.playWhenReady = true
```

EDIT: i think this works properly if index startPosition is 0. If startPosition is different - magic is happening. Sometimes it gives proper time and sometimes it gives 0 or empty timeline. I cannot figure out pattern here

**Comment by tonihei** [comment]
There are already events triggered by `exoplayer.prepare` that may set the `eventTime` value you receive in the callback. I think you need to call the `setFirstQueueItem` earlier. Ideally at the same time you add the the new `PlaybackStatsListener` as a listener (i.e. in `startPlayback()`). 

Thanks for trying this out by the way and reporting these subtle issues! It will hopefully get a lot easier when we release 2.12 and playlist handling and related updates are part of the `Player` interface and better integrated.

**Comment by jakoss** [comment]
I changed my code to this:
```kotlin
fun startPlayback(queueItem: QueueItem) {
        firstQueueItemInPlaylist = queueItem
        currentStatsListener?.let {
            it.finishAllSessions()
            player.removeAnalyticsListener(it)
        }
        val statsListener = createStatsListener()
        currentStatsListener = statsListener
        player.addAnalyticsListener(statsListener)
    }
```

Unfortunetely i see no difference in behavior here.

This is not critical for us since we have our own playback listener (much more primitive, but battle tested). I would love to migrate it to supported solution from exoplayer nonetheless. If 2.11 won't work - i will happily test 2.12 :)

**Comment by ojw28** [comment]
@tonihei - Can this be marked as fixed now?

**Comment by tonihei** [comment]
Yes, bf5b52e fixed the bug mentioned above.
