### ISSUE TITLE
Offline playback shows black screen

### ISSUE THREAD

**Issue by alexandru-calinoiu** [google/ExoPlayer#7201]
### [REQUIRED] Issue description
With the latest version of player, when setting the DrmSessionManager on MediaSource downloaded videos show black video and no sound, the duration and subtitles continue to work.

### [REQUIRED] Reproduction steps

Use this code to init the DrmSession Manager

```
        val drmSessionManager = DefaultDrmSessionManager.Builder()
                .setUuidAndExoMediaDrmProvider(C.WIDEVINE_UUID, AppManagedProvider(FrameworkMediaDrm.newInstance(C.WIDEVINE_UUID)))
                .setMultiSession(true)
                .build(movieWidevineMediaDrmCallback.initialize(args.movieId))
        val readKeySetId = OvxFileUtils.readKeySetId(this, args.movieId, DownloadPreferences())
        drmSessionManager.setMode(DefaultDrmSessionManager.MODE_PLAYBACK, readKeySetId)
        drmSessionManager
```

Make sure you sent your session manager on the MediaSource
```
        return ProgressiveMediaSource.Factory(dataSourceFactory)
                .setDrmSessionManager(drmSessionManager)
                .createMediaSource(url.toUri()).takeUnless { url.isBlank() }
```

This player init will results in black screen

```
        player = SimpleExoPlayer.Builder(this, renderersFactory)
                .setTrackSelector(trackSelector)
                .setLoadControl(loadControl)
                .setBandwidthMeter(bandwidthMeter)
                .build()
```

This legacy code will work

```
        player = ExoPlayerFactory.newSimpleInstance(this, renderersFactory, trackSelector, loadControl, drmSessionManager as DrmSessionManager<FrameworkMediaCrypto>, bandwidthMeter)
```

### [REQUIRED] Link to test content
-

### [REQUIRED] A full bug report captured from the device
There is not logged error and PlayerEventListener#onPlayerError does not get called.

### [REQUIRED] Version of ExoPlayer being used
2.11.3

### [REQUIRED] Device(s) and version(s) of Android being used
Android Pixel 4

### Bug Report
[bugreport-coral-QQ2A.200405.005-2020-05-04-19-57-45.zip](https://github.com/google/ExoPlayer/files/4576081/bugreport-coral-QQ2A.200405.005-2020-05-04-19-57-45.zip)

### Screenshoot
![20200504_195738](https://user-images.githubusercontent.com/679198/80993135-3caac900-8e43-11ea-80ac-338e8ef534cf.jpg)

**Comment by AquilesCanta** [comment]
Please provide the bugreport as requested in the issue template.

**Comment by alexandru-calinoiu** [comment]
@AquilesCanta I've update the description with more info.

**Comment by AquilesCanta** [comment]
Hi, it seems the bugreport was not captured from the demo app. Please also provide sample media on which I can reproduce the issue. If you're unable to share test content publicly, please send it to dev.exoplayer@gmail.com using the subject "Issue #7201". Please also update this issue to indicate you’ve done this.

If you play your stream in the demo app, it will provide you with more information through logcat.

**Comment by AquilesCanta** [comment]
Sorry, my comment above was off-topic (deleted it, not sure whether it shows a marker for you). It seems your app is not attaching an EventLogger, which means that the bugreport is not very useful. Also, the content is offline and DRM protected, which means that the sample stream will not be useful either.

Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that demonstrates the problem in a way that we build locally. This could be an Android Studio project on GitHub, or zipped up and sent to dev.exoplayer@gmail.com (with subject "Issue #7201").
