### ISSUE TITLE
Exoplayer stops playing while background when screen off

### ISSUE THREAD

**Issue by literaturesharingforvi** [google/ExoPlayer#7208]
I use exoplayer as a audio player in my application and while playing in background when screen is off the playback stops after few minutes.

Can anyone suggest solution

**Comment by AquilesCanta** [comment]
There's some material available freely. I suspect your service is being killed.
- [IO exoplayer talk](https://youtu.be/svdq1BWl4r8?t=756).
- [Sample audio app](https://github.com/google/ExoPlayer/tree/io18).
- #6710.

**Comment by literaturesharingforvi** [comment]
ok thanks will try to solve by going through materials you suggested.
