### ISSUE TITLE
i have try when RTSP to a H264 camera,  this player not work,but VLC work good.,

### ISSUE THREAD

**Issue by hears** [google/ExoPlayer#7211]
i have try when RTSP to a H264 camera,  this player not work,but VLC work good.,

and i have looked , when exoplayer try to connect a RTSP server ,  
(other player will send to server  client port in this mode  :  40000-40001  )
but exoplayer only send 1 port :40000  , this will make many RTSP cannot get client port correct

**Comment by AquilesCanta** [comment]
#55 tracks support for RTSP.
