### ISSUE TITLE
IMA Extension - Player doesn't resume content if one ad of a playlist returns a VAST error

### ISSUE THREAD

**Issue by tim-strehlow-zattoo** [google/ExoPlayer#7212]
### Issue description
When an ad in a preroll or midroll playlist returns a VAST error response, the player does not resume content correctly after playing the other retrieved video ads.

### Reproduction steps
Since we can’t provide an environment to reproduce the issue, I will describe the scenario as detailed as possible:
- We start a stream and receive a preroll playlist with two ads.
- The first ad is an inline creative.
- The second ad is a wrapper ad that points to an ad tag uri of a different ad provider. From there we receive another wrapper that delegates even further. In total the ad retrieval is delegated via three different providers. 
- Finally the ad tag uri of the third provider returns a VAST error response.
- In our app the first ad plays correctly and also the UI is updated as expected (countdown for one ad is displayed, instead of “ad 1 of 2”).
- After the ad is finished, the player is stuck in displaying the ad and doesn’t resume the content as expected.
- When debugging the ExoPlayer code, it at first seemed more like an IMA issue, since onAdEvent() kept being called with AD_PROGRESS even after the ad finished. However, we are not seeing this issue on other platforms that run the same campaigns and also use IMA.

### Link to test content
Unfortunately we can’t provide that setup for a demo case, it is happening in our production environment only and due to the complexity it’s hard to simulate. Therefore I tried to describe the case as detailed as possible. If you have further questions or ideas how we can assist, please let me know.

### A full bug report captured from the device
Provided via email

### Version of ExoPlayer being used
2.10.6, 2.11.3

### Device(s) and version(s) of Android being used
OnePlus 5t (Android 9)
Galaxy S6 & S7 (Android 7)
Galaxy A6 (Android 9)
Galaxy Tab A (Android 6)

**Comment by softartdev** [comment]
It seems we are faced with the same problem.
If prepare [ImaAdsLoader](https://github.com/google/ExoPlayer/blob/release-v2/extensions/ima/src/main/java/com/google/android/exoplayer2/ext/ima/ImaAdsLoader.java) in the standard way
```
imaAdsLoader = ImaAdsLoader.Builder(context)
                .buildForAdTag(videoVastUri)
```
then when an error occurs in the preroll

> W/IMASDK: Invalid internal message, ignoring. Please make sure the Google IMA SDK library is up to date. Message: gmsg://afma.google.com/activityMonitor?type=getPageSignals&sid=7d4700e2-62fa-43be-8bf8-eaabc410167e&dt=1587039202087
> I/ImaAdsLoader: AdEvent: {errorMessage=Linear assets were found in the VAST ad response, but none of them matched the video player's capabilities., errorCode=403, type=adPlayError}

the main content does not play.
We found a workaround so that after advertising errors the main content continued to play:
```
imaAdsLoader = ImaAdsLoader.Builder(context)
                .setAdEventListener { if (it.type == AdEvent.AdEventType.ALL_ADS_COMPLETED) imaAdsLoader?.release() }
                .buildForAdTag(videoVastUri)
```
Hope this will be fixed in the next version of the library.

**Comment by andrewlewis** [comment]
It's difficult to say without the ad tag but please could you try to reproduce this on `dev-v2` to pick up the preloading improvements in fa7d26dd9f94f52c412ff7d6490630dd73f187a6? I suspect that will fix this.
