### ISSUE TITLE
Player view doesn't change size when applying scale to parent container on Android 6

### ISSUE THREAD

**Issue by jruesga** [google/ExoPlayer#7214]
### [REQUIRED] Issue description
On Android 6 when applying scale to a parent container of the player view, the view doesn't update its state to reflect the new dimensions.

### [REQUIRED] Reproduction steps
Surround com.google.android.exoplayer2.ui.PlayerView with a container, and call setScaleX or setScaleY in the container. In Android 6, the ExoPlayer doesn't adapt to the new dimensions of the container.

### [REQUIRED] A full bug report captured from the device
Attached is a video using the Demo App (modified to surround the PlayerView with a FrameLayout) running in 2 Android emulator instances (the upper one running Api 29 and the lower one running Api 23) playback the same video: WV: Clear HD (MP4,H264)(https://storage.googleapis.com/wvmedia/clear/h264/tears/tears_hd.mpd)

[Video](https://youtu.be/AwhBmc5dqdQ)

### [REQUIRED] Version of ExoPlayer being used
r2.10.8

### [REQUIRED] Device(s) and version(s) of Android being used
Android 6.x, Android Studio Emulator

**Comment by AquilesCanta** [comment]
@marcbaechinger can you take a look at this in the context of PlayerView?

**Comment by marcbaechinger** [comment]
Thanks for the uploaded video, This was very helpful. 

It seems that it is only the surface which does not adjust. All other UI elements are scaled correctly. This makes me think it's a problem on the platform on Marshmallow. I look into this and see whether there is some kind of workaround.

You may want to try different surfaces yourself. Are you currently using SurfaceView or TextureView? Do you experience the problem with both surfaces?  You can switch easily by  using the `surface_type` attribute in your xml layout.

**Comment by jruesga** [comment]
Thanks for quick response.

> Are you currently using SurfaceView or TextureView?

SurfaceView

> Do you experience the problem with both surfaces? 

Seems only affects to SurfaceView. TextureView behaves correctly.

**Comment by marcbaechinger** [comment]
Thanks for checking. 

If `TextureView` works and you are not having protected content, you could [create a layout or resource files which is specific for API level 23](https://developer.android.com/guide/topics/resources/providing-resources#AlternativeResources) and then change the `surface_type` to texture view for only this API level. Besides `TextureView` not supporting DRM'd content, it has a bit higher energy consumption. That's why I would only do a API specific layout, so all other API level still have the more efficient SurfaceView.

**Comment by jruesga** [comment]
Ok. Thank you so much. I will try your suggestion.
