### ISSUE TITLE
Hot to detect play/pause button click in the playerNotificationManager

### ISSUE THREAD

**Issue by pawaom** [google/ExoPlayer#7215]
Hot to detect play/pause button click in the `playerNotificationManager`

Exoplayer has its own notification controls, using the `playerNotificationManager`

I wan to play the next song when there is no `player.hasNext()` and we have set `Player.REPEAT_MODE_OFF`  when the player has stopped after laying the last song

i can use  ` player.next();` but for that **I want to detect when the user clicks the play button**. to fire that event 

how can this be done 

thanks

**Comment by AquilesCanta** [comment]
@marcbaechinger mind taking a look?

**Comment by marcbaechinger** [comment]
Closing this as a duplicate of #7221
