### ISSUE TITLE
DefaultLoadControl.Builder() not working on recorded video streams

### ISSUE THREAD

**Issue by menscikov** [google/ExoPlayer#7218]
**Issue description**

`DefaultLoadControl.Builder()` not working properly on recorded streams on ExoPlayer 2.11.4 and lower versions.
ExoPlayer gets "**403 ERROR**" after ~2 minutes of playing.
If video stream is opened without LoadControl, everything is working fine.

**Reproduction steps**

Add LoadControl `.setLoadControl(loadControl)` to your `SimpleExoPlayer.Builder(this).build()` with default parameters. It doesn't work with them also:

```
LoadControl loadControl = new DefaultLoadControl.Builder()
                    .setBufferDurationsMs(
                            DefaultLoadControl.DEFAULT_MIN_BUFFER_MS,
                            DefaultLoadControl.DEFAULT_MAX_BUFFER_MS,
                            DefaultLoadControl.DEFAULT_BUFFER_FOR_PLAYBACK_MS,
                            DefaultLoadControl.DEFAULT_BUFFER_FOR_PLAYBACK_AFTER_REBUFFER_MS)
                    .createDefaultLoadControl();
```

Open the video stream and wait ~2 minutes.
Link to the media e-mailed to ExoPlayer development team.

**Version of ExoPlayer being used**

2.11.4

**Device(s) and version(s) of Android being used**

Tested on Android Emulators, versions: 8.0, 9.0, 10.0.
Samsung Galaxy Note 4, Android 6.0.1

**Comment by AquilesCanta** [comment]
It doesn't sound likely to me that injecting a custom load control (specially with default values) could trigger a 403. However, I will look into this once I have access to the provided stream. Please check that you sent the e-mail to dev.exoplayer@gmail.com with subject "Issue #7218".

**Comment by menscikov** [comment]
> It doesn't sound likely to me that injecting a custom load control (specially with default values) could trigger a 403. However, I will look into this once I have access to the provided stream. Please check that you sent the e-mail to [dev.exoplayer@gmail.com](mailto:dev.exoplayer@gmail.com) with subject "Issue #7218".

Hello, I just sent the new url to the media stream.
I checked this issue again, I think there is a bug somewhere in the Builder, because without load controls it works.

**Comment by AquilesCanta** [comment]
Hi @menscikov, I'm playing the stream right now. The player is created with the following parameters:

```
new SimpleExoPlayer.Builder(/* context= */ this, renderersFactory)
              .setLoadControl(new DefaultLoadControl.Builder()
                  .setBufferDurationsMs(
                      DefaultLoadControl.DEFAULT_MIN_BUFFER_MS,
                      DefaultLoadControl.DEFAULT_MAX_BUFFER_MS,
                      DefaultLoadControl.DEFAULT_BUFFER_FOR_PLAYBACK_MS,
                      DefaultLoadControl.DEFAULT_BUFFER_FOR_PLAYBACK_AFTER_REBUFFER_MS)
                  .createDefaultLoadControl())
              .setTrackSelector(trackSelector)
              .build();
```

But the stream plays correctly. And also plays correctly with the default load control. Note that the lines above are equivalent to not passing anything at all.

I think it's extremely likely that this is just a server side issue with authentication, somehow. Please provide precise steps to reproduce the issue in the demo app.

**Comment by menscikov** [comment]
Hi @AquilesCanta, it's very strange.

I copied your code and replaced with mine. Also removed "renderersFactory" and "trackSelector" from Builder, only left LoadControl.

After 2 minutes of playing I get this error:
```
2020-04-14 13:38:07.482 14195-14457/com.ottplay.ottplay E/ExoPlayerImplInternal: Source error
      com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:300)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:177)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.prepareExtraction(HlsMediaChunk.java:390)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.feedDataToExtractor(HlsMediaChunk.java:369)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.loadMedia(HlsMediaChunk.java:343)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.load(HlsMediaChunk.java:314)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:391)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
```

**Comment by menscikov** [comment]
@AquilesCanta I will try to insert load control in ExoPlayer demo project with this url. Will see if the problem persists.

**Comment by menscikov** [comment]
@AquilesCanta I reinstalled Android Studio and ExoPlayer, loaded test url into ExoPlayer Demo project with Load Control. After 2 minutes of playing 403 error.
Tested on Android 10 Emulator (Android Studio 3.6.2 + ExoPlayer 2.11.4) from MacBook Pro.

I would agree that problem is on the server side, but error persists even if I injecting Load Controls with default values.
Without Load Control everything is fine, no errors.

I also tried to connect to mobile internet, but it doesn't help.

P.S. I tried other media streams, and they are working without any errors with Load Control. But anyway, I can't understand why media stream that I sent to the e-mail is working without Load Control and isn't working with Load Control default values.

**Comment by AquilesCanta** [comment]
Hi @menscikov, is this still an issue? I found it hard to understand how this could be possible, and went under my radar.

If this is still an issue, could you please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that demonstrates the problem in a way that I can reproduce locally? Even perhaps a small patch I can apply to our demo app should be enough. I'm sorry for the delay on this.
