### ISSUE TITLE
Another video ExoPlayer unable to play

### ISSUE THREAD

**Issue by dryganets** [google/ExoPlayer#7219]
### Issue description
Video doesn't play in ExoPlayer but playable by any available desktop player.
The file doesn't look to be corrupted or truncated. There is no ExoPlayer error triggered.

### Reproduction steps
Play attached file in the exoplayer

### Link to test content
[sample.mp4.zip](https://github.com/google/ExoPlayer/files/4463766/sample.mp4.zip)

###  Version of ExoPlayer being used 
- 2.10.2 - doesn't render anything
- 2.11.4 - renders first frame only

### Device(s) and version(s) of Android being used
- Essential Phone Android 10.
- Huawei P20 Lite Android 9

Don't think it is device specific.

**Comment by ojw28** [comment]
It plays the same (i.e. only a single frame) in both Quicktime and Chrome for me. In VLC it plays a single frame, but has some very strange resizing artefacts during the 3s of playback.

Given other players are either playing it the same way that ExoPlayer does, or doing something that looks obviously broken, it seems unlikely there's an ExoPlayer issue here. Please could you clarify why you think there is one? Thanks!

**Comment by dryganets** [comment]
yep, agree, this one is an issue somewhere in our pipeline..
Need to figure out how we got into that state.
It is fragmented mp4.
Sorry for bothering you.
