### ISSUE TITLE
Does exoplayer support dolby digital sound?

### ISSUE THREAD

**Issue by aravinds03** [google/ExoPlayer#722]
Hi,
Does exoplayer support video files which has dolby digital surround audio?
If yes, can you provide sample code snippet (or) which type of AudioRendering to use?

**Comment by andrewlewis** [comment]
Extraction of AC-3 samples is supported for HLS and DASH streaming, and when reading samples from MP4 and Matroska containers.

Playback of the extracted samples requires either an AC-3 decoder on the device, or encoded audio passthrough support over HDMI to a separate audio receiver on platform API versions >= L. An app can check whether an AC-3 decoder is present using MediaCodecUtil, and it can check whether passthrough is possible using AudioCapabilities (see the demo app for an example of how to use the latter).

**Comment by quanghuy1288** [comment]
Do you have demo app for using AC-3 passthrought? 
I have a Android box connect to a 5.1 dolby receiver, but box always error when play dolby 5.1 audio (link is http://123.30.233.143/vod/a.mp4/playlist.m3u8 )
Error log is attached.

[ac3.txt](https://github.com/google/ExoPlayer/files/995049/ac3.txt)

**Comment by andrewlewis** [comment]
@quanghuy1288 Please file a new issue including all the information requested in the issue template. The log provided doesn't have enough information to figure out what build the device is running, but the mention of `jb-mr1` in logcat seems supicious; passthrough output requires at least Android Lollipop.

**Comment by quanghuy1288** [comment]
Hi, i have create new issue: https://github.com/google/ExoPlayer/issues/2816 
My device 's Android version is 5.1.
