### ISSUE TITLE
Add support for DVB EBU Teletext 

### ISSUE THREAD

**Issue by a4x4kiwi** [google/ExoPlayer#7220]
### [REQUIRED] Searched documentation and issues
Have checked documentation and see classes relating to subtitles, but would like example stringing the necessary pieces together.

### [REQUIRED] Question
Does anyone have an example of how to display subtitles from a UDP TS DVB stream? 
Any assistance would be most helpful.

Thanks in advance.

**Comment by AquilesCanta** [comment]
Please try your stream in the demo app. You need to ensure the subtitles are being recognised by the player, and that the text track you want is selected. It's easy to confirm both by looking at the logcat.

For an example of how subtitles work end to end (the format shouldn't make a difference from the app's perspective), you should follow the demo app. If you are running into any specific issue, please share the elements required in the issue template (please include a media sample, and a bugreport) and we can address the more specific issues.

**Comment by LRTNZ** [comment]
I also have been working on a media player project utilising UDP TS streams, and was wondering if I could get some help about how to get the subtitles embedded in these files to be played back?

I have tried finding documentation on how to do it, but I have been able to find no clear information on what exactly needs to be done. Yes, I have looked into the demo app, but could not find anything clearly showing how to do it.
If something could be put together by someone knowledgable on the workings of Exoplayer, based on the media samples below, I am sure many people will be very happy, based on the number of accounts I have come across online of people trying to achieve this. I for one, certainly would be, as it would solve a decent problem I am facing in the app that I am developing.

https://drive.google.com/open?id=1Q9n5KY-WSodNbVIyUntgz_jKzgR9GGQs
https://drive.google.com/open?id=1eTFX0KpQUog9bI5LQOe23K6B_FkgpErr

**Comment by a4x4kiwi** [comment]
Thanks  AquilesCanta.
The subtitles are recognised but labelled as 'unknown' by the player. When 'unknown' is selected subtitles are not displayed as I presume they should be. This is an Australian DVB-T  channel.

I am not sure if this is a bug or not at this point.

The 2 example streams posted by LRTNZ (Also Australian TV) contain subtitles playable in VLC.
I have streamed them to the demo Exoplayer app (using http) with the same result. (They play audio and video, but no subtitles)

Do I need to formulate a subtitle URI somehow perhaps?

Below is the Logcat when playing a multicast stream.
[Exoplayer Logcat.txt](https://github.com/google/ExoPlayer/files/4478292/Exoplayer.Logcat.txt)

Thanks for any assistance.

**Comment by a4x4kiwi** [comment]
Hi AquilesCanta.

Did you happen to have any further thoughts on this?

Thanks again for your assistance.
Stay well.

**Comment by AquilesCanta** [comment]
I had a look at it. Seems the files carry EBU teletext which ExoPlayer doesn't currently support. I'll have a look into this when I have some time. I'll post here once I have news. Naturally, you are welcome to send a pull request our way.

**Comment by AquilesCanta** [comment]
Not 100% sure, but this may also be a duplicate of #5491.

**Comment by a4x4kiwi** [comment]
Thanks. Let me know if you need me to provide any further info, details, stream captures or testing. 
Anything that would help the process. It makes me wonder what other countries apart from Australia use this format.

**Comment by a4x4kiwi** [comment]
If this post is not acceptable, please feel free to delete. I have created a freelancer listing to get help with this enhancement. If anyone is interested in assisting, please see [https://www.freelancer.com.au/projects/android/Develop-Australian-Subtitles-Closed/details](https://www.freelancer.com.au/projects/android/Develop-Australian-Subtitles-Closed/details)

**Comment by HuzefaGadi** [comment]
> If this post is not acceptable, please feel free to delete. I have created a freelancer listing to get help with this enhancement. If anyone is interested in assisting, please see https://www.freelancer.com.au/projects/android/Develop-Australian-Subtitles-Closed/details

Hello there @a4x4kiwi , I am freelancer myself and seems the project which you have posted on freelancer has been subcontracted to a lot of people, as the same project has been reposted by the developer you hired to do the job. I can help you with this issue, message me if you are interested. and beware of the scammers on freelancer certainly the developer you hired has no idea on how to do this. and he might eventually cheat you

**Comment by a4x4kiwi** [comment]
Well that freelancer did not work out. If anyone is interested in paid development for this, please contact me by email at malcolm@avcomm.com.au

**Comment by a4x4kiwi** [comment]
**Further details provided for any dev.**

Other related issues / enhancement requests
https://github.com/google/ExoPlayer/issues/6642
https://github.com/google/ExoPlayer/issues/5491

Australian Standards. (These reference the ETSI documents below)
https://www.freetv.com.au/resources/operational-practices/
https://www.freetv.com.au/wp-content/uploads/2019/08/OP-47-Storage-and-Distribution-of-Teletext-Subtitle-and-VBI-Data-Issue-6-May-2018.pdf
https://www.freetv.com.au/wp-content/uploads/2019/08/OP-42-Closed-Captioning-Issue-5-May-2018.pdf

Specification for conveying ITU-R System B Teletext in DVB bitstreams
https://www.etsi.org/deliver/etsi_en/300400_300499/300472/01.03.01_60/en_300472v010301p.pdf

Media Content Distribution (MCD);Subtitles distribution, situation and perspectives
https://www.etsi.org/deliver/etsi_tr/102900_102999/102989/01.01.01_60/tr_102989v010101p.pdf

Enhanced teletext specification
https://www.etsi.org/deliver/etsi_en/300700_300799/300706/01.02.01_60/en_300706v010201p.pdf

Digital Video Broadcasting (DVB);Specification for the carriage of Vertical Blanking Information (VBI) data in DVB bitstreams
https://www.etsi.org/deliver/etsi_en/301700_301799/301775/01.02.01_60/en_301775v010201p.pdf

**Comment by wazerstar** [comment]
I'm glad that this is finally beeing looked into.

I have a sample file from channel using these subs.

50ish mb on mega

https://mega.nz/file/cNAQ2ApS#bt0OhhBuxiAJ0s2_qioOxes6xO1cOIl-xE7AUX20lOY

Please let me know if there's anything else you need, I can provide realtime tv data stream for testing if needed.

@AquilesCanta you still on it?
@HuzefaGadi what about you.

**Comment by trmvenus** [comment]
Hello, **a4x4kiwi**.

I also want to stream TS files (included Australian TV Subtitle) to the demo Exoplayer app.
Could you help me to stream TS file?

Thanks.

**Comment by a4x4kiwi** [comment]
Hi trmdeveloper.

I use the Windows VLC player to stream the files in a loop. Note the android VM can not receive multicast. You should also have an Android TV box / Nvidia shield on your wired network for testing. (Wireless and Multicast do not usually play well together.

All the best,

**Comment by trmdeveloper** [comment]
Thanks for your response, a4x4kiwi.

https://drive.google.com/open?id=1Q9n5KY-WSodNbVIyUntgz_jKzgR9GGQs
https://drive.google.com/open?id=1eTFX0KpQUog9bI5LQOe23K6B_FkgpErr

I downloaded TS files from above urls and I tried to test this TS file on local using Exoplayer.
But I could see only black screen but the Exoplayer was playing without errors.

Could you play the TS files on local (storage or sdcard) using Exoplayer?

If you can, please let me know how to implement.

Best wishes.

**Comment by icbaker** [comment]
Marking this as a dupe of https://github.com/google/ExoPlayer/issues/5491 since that one's older.
