### ISSUE TITLE
OkHttpDataSourceFactory for Web sockets

### ISSUE THREAD

**Issue by mobileappspuzzles** [google/ExoPlayer#7224]
How can use okHttp web sockets. I have studied [Extension](https://github.com/google/ExoPlayer/tree/release-v2/extensions/okhttp) not found any thing related to web sockets.

Our sever will continue send Raw H264 frames through web sockets. Which datasource we have to use for web sockets with exo player.

**Comment by icbaker** [comment]
The ExoPlayer OkHttpDataSource doesn't support web sockets - it only uses OkHttp's `Call.Factory`.

ExoPlayer doesn't have any support for web sockets.
