### ISSUE TITLE
How to play a local Server Socket

### ISSUE THREAD

**Issue by guy244** [google/ExoPlayer#7225]
Hey,

I am trying to play a file sitting in a SMB share, I am able to play the file just fine if I user other player such VLC or MX Player by using a server socket with the input stream of the file and then sending the localhost as intent to these apps.
I am trying to play it via Exoplayer as well, which data source should I use? I have failed to play it so far

**Comment by icbaker** [comment]
ExoPlayer doesn't support accessing SMB files directly.

If you can get the SMB share mounted on the phone's file system then you can pass a 'file' URI to `DefaultDataSource` and it should just work.

It's not clear to me what this part means:
>  I am able to play the file just fine if I user other player such VLC or MX Player by using a server socket with the input stream of the file and then sending the localhost as intent to these apps.

If the file is on an SMB share that's mounted locally, I'm not sure why you'd need to pass socket info or `localhost` around - it should look exactly like a local file.

**Comment by danergo** [comment]
You can also create your own DataSource which can use some SMB library to read (and seek) files on SMB if you want to go on the hard way :)
