### ISSUE TITLE
MediaSessionConnector.PlaybackPreparer parameter is not properly annotated with @Nullable

### ISSUE THREAD

**Issue by eprendre** [google/ExoPlayer#7234]
MediaSessionConnector.PlaybackPreparer.onPrepareFromUri's parameter `extras` is not annotated with @Nullable. 
This forces kotlin to override nonnull parameter. 
As tested, this will crash on api level 19 and 21: `Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter extras`

**Comment by marcbaechinger** [comment]
The missing annotations have been added (see commit above). Many thanks for reporting.
I'm going to close this issue. Please re-open if I missed something.
