### ISSUE TITLE
Check if media has or not audio track(s)

### ISSUE THREAD

**Issue by danergo** [google/ExoPlayer#7235]
### [REQUIRED] Searched documentation and issues

- Searched in Google "ExoPlayer [get|detect|query] [default] [audio] [track|tracks]"
- Searched also in github
- Searched in StackOverflow

### [REQUIRED] Question
I want to know if a stream currently playing has or not audio track.
It is good even in `onTracksChanged` listener, or querying directly.
However I want to avoid to guess it based on some `formatString.contains("audio")`.

### Link to test content

Test content is unnecessary. I'd like to distinguish if a media is playing with or without audio.

**Comment by danergo** [comment]
Right now I'm doing this like below, but it feels too complicated for this single information:

Initialization:
```
trackSelector = new DefaultTrackSelector(context);
mediaPlayer = new SimpleExoPlayer.Builder(context).setTrackSelector(trackSelector).build();
mediaPlayer.addListener(this);
```
Listening on events:
```
@Override
public void onTracksChanged(TrackGroupArray trackGroups, TrackSelectionArray trackSelections) {
    MappingTrackSelector.MappedTrackInfo ti = 
        ((MappingTrackSelector)trackSelector).getCurrentMappedTrackInfo();

    if (ti!=null) {
        if (ti.getTypeSupport(TRACK_TYPE_AUDIO) == RENDERER_SUPPORT_NO_TRACKS) {
            //Does not have audio
        }
        else {
            //Has audio
        }
    }
}
```

Was also strange that `trackSelector`  without first casting it to `MappingTrackSelector` does not provide the `getCurrentMappedTrackInfo`.

I still believe it shall be some other (much easier) way to detect audio tracks.

**Comment by icbaker** [comment]
Do you want to know if your media contains any audio tracks, or any audio tracks that are selected and playable by the current device?

The code you've written for `onTracksChanged` does the latter - it checks if the media contains audio tracks that have renderer support. You can see this used in the demo app to pop up a toast in this case: https://github.com/google/ExoPlayer/blob/7214ad2d6f9d1e1c13649f2fb4b085ef746f0c3e/demos/main/src/main/java/com/google/android/exoplayer2/demo/PlayerActivity.java#L627

For the former, something like this should work:

```java
@Override
public void onTracksChanged(TrackGroupArray trackGroups, TrackSelectionArray trackSelections) {
  boolean containsAudioTrack = containsAudioTrack(trackGroups);
}

private static void containsAudioTrack(TrackGroupArray trackGroups) {
  for (int i = 0; i < trackGroups.length; trackGroups++) {
    TrackGroup trackGroup = trackGroups.get(i);
    for (int j = 0; j < trackGroup.length; j++) {
      if (MimeTypes.isAudio(trackGroup.format(i).sampleMimeType)) {
        return true;
      }
    }
  return false;
}
```

> Was also strange that trackSelector without first casting it to MappingTrackSelector does not provide the getCurrentMappedTrackInfo.

Since you're constructing a `DefaultTrackSelector`, you can store this directly into a field of type `DefaultTrackSelector` or `MappingTrackSelector` without needing any casting.

**Comment by danergo** [comment]
Great, thanks very much. Indeed, this would be a nice to have in the documentation.

(My use case was the second, i.e. is it reasonable to show the mute control - in case the device is unable to decode audio I did not want to show it).

**Comment by danergo** [comment]
This might not be closed because of "documentation candidate" label.

**Comment by ojw28** [comment]
We don't keep issues open for the documentation candidate label. We use it as a separate tracking mechanism instead (and remove the label from the closed issue once we've added corresponding documentation).
