### ISSUE TITLE
HLS With discontinuity stuck in buffer

### ISSUE THREAD

**Issue by rossanakarina** [google/ExoPlayer#7237]
We are using JWPlayer 8.9.0 and we are trying to insert advertisements in our videos. We are using EXT-X-DISCONTINUITY but apparently, when we get to the point of starting our advertising, the player stops showing a buffer status.

This is an example of our playlist:

[CODE]
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-TARGETDURATION:16
#EXT-X-PLAYLIST-TYPE:VOD
#EXTINF:14.557178,
https://slave2.example.com/hls/output1/output_000.ts
#EXTINF:1.376467,
https://slave3.example.com/hls/output1/output_001.ts
#EXT-X-DISCONTINUITY
#EXTINF:8.050244,
https://slave2.example.com/hls/HLSad/output_000.ts
#EXTINF:4.880200,
https://slave2.example.com/hls/HLSad/output_001.ts
#EXTINF:7.090889,
https://slave2.example.com/hls/HLSad/output_002.ts
#EXTINF:5.881267,
https://slave2.example.com/hls/output1/output_002.ts
#EXTINF:5.672711,
https://slave3.example.com/hls/output1/output_003.ts
#EXT-X-DISCONTINUITY
#EXTINF:8.050244,
https://slave2.example.com/hls/HLSad/output_000.ts
#EXTINF:4.880200,
https://slave2.example.com/hls/HLSad/output_001.ts
#EXTINF:7.090889,
https://slave2.example.com/hls/HLSad/output_002.ts
#EXTINF:5.714422,
https://slave2.example.com/hls/output1/output_004.ts
#EXTINF:4.755067,
https://slave3.example.com/hls/output1/output_005.ts
[...]
#EXT-X-ENDLIST[/CODE]

This is what the JS console tells us:
[CODE][log] > audio sampling rate : 48000
9512e6e5-eff6-4f75-806f-a367785315b7:1 [log] > manifest codec:undefined,ADTS data:type:2,sampleingIndex:3[48000Hz],channelConfig:2
9512e6e5-eff6-4f75-806f-a367785315b7:1 [log] > parsed codec:mp4a.40.5,rate:48000,nb channel:2
9512e6e5-eff6-4f75-806f-a367785315b7:1 [log] > audio sampling rate : 48000
9512e6e5-eff6-4f75-806f-a367785315b7:1 [log] > AVC:59 ms overlapping between fragments detected
9512e6e5-eff6-4f75-806f-a367785315b7:1 [log] > Video/PTS/DTS adjusted: 15958/15933,delta:-59 ms[/CODE]

While the Chrome Media console says:
[CODE]1.414   kPlay   
{}

17.280  kBufferingStateChanged  
{audio_buffering_state: {reason: "DEMUXER_UNDERFLOW", state: "BUFFERING_HAVE_NOTHING"}}

17.280  kBufferingStateChanged  
{,…}
pipeline_buffering_state: {for_suspended_start: false, reason: "DEMUXER_UNDERFLOW", state: "BUFFERING_HAVE_NOTHING"}
for_suspended_start: false
reason: "DEMUXER_UNDERFLOW"
state: "BUFFERING_HAVE_NOTHING"[/CODE]

Considering that the two videos that we are going to "merge" in the playlist have the same audio / video characteristics (codecs, bitrate, resolution etc.), why is this not working? Thank you

**Comment by icbaker** [comment]
There isn't enough information for us to reproduce & debug this issue.

We ideally need a real playlist that demonstrates the behaviour (assuming the behaviour reproduces in the demo app) and/or a bug report taken directly after reproducing the problem using `adb bugreport`.

If you're unable to share bug reports or test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Please also update this issue to indicate you’ve done this.
