### ISSUE TITLE
Exoplayer Demo: Cleartext traffic not permitted

### ISSUE THREAD

**Issue by LRTNZ** [google/ExoPlayer#7242]
### [REQUIRED] Issue description

When adding a new source to the media.exolist.json file in the demo application, any
sources that required a cleartext (HTTP) connection cannot play, as cleartext connections
are not allowed in the demo application.
This appears to be an issue starting with Android 9 (The highest version I have running on
a device I can test with), and the introduction of the default setting that does not allow
cleartext traffic through by default.

### [REQUIRED] Reproduction steps

Add in a new source to the media list, that uses an http connection, and install it
onto an Android 9 device.
Setup something on your local network, that can deliver some media over http,
to the device you installed the app onto.
Open the app, and try to playback the http stream. A toast should be thrown saying
that cleartext traffic is not allowed.

### [REQUIRED] Link to test content
{
    "name": "Streams",
    "samples": [
      {
        "name": "Test HLS",
        "uri": "http://your_test_ip_address/hls/test.m3u8"
      }
    ]
  }

### [REQUIRED] A full bug report captured from the device
Emailed in.

### [REQUIRED] Version of ExoPlayer being used
2.11.4 - demo app

### [REQUIRED] Device(s) and version(s) of Android being used

Mibox4 running Android 9 - Could not play out of the box
Sony Bravia TVs running Android 8 - Could play out out the box

**Comment by icbaker** [comment]
You need to use a Network Security Configuration that permits cleartext traffic. There's more info (and links to even more info) here:
https://exoplayer.dev/troubleshooting.html#fixing-cleartext-http-traffic-not-permitted-errors

**Comment by LRTNZ** [comment]
Thank you - I am aware of the fix, and did easily implement it.
However, I am wondering if this is something to maybe have in the manifest for
the demo app, so people can play http sources without needing to change that permission?

**Comment by icbaker** [comment]
We want the demo app to be a good starting point for people to understand how to use our library to build their own apps. As such, there's a degree of "being a good role model", so we generally try to follow Android best practices as much as possible.

The platform has decided that blocking cleartext traffic is a good default, so we keep the default behaviour.

Of course, the demo app is also a very useful sandbox for testing out how the library handles various media - and for that use-case it would be more reasonable to explicitly allow cleartext traffic by default. 

These two use-cases sometimes compete directly - like here - and in these cases we generally come down on the side of keeping things simple for new developers, at a small cost to those wanting to experiment with different pieces of media.
