### ISSUE TITLE
Sony Bravia AndroidTV Decoding artifacts

### ISSUE THREAD

**Issue by BoschAlejandro** [google/ExoPlayer#7248]
### [REQUIRED] Issue description
Decoding artifacts when changing from a higher track (1280x720 or higher) to a lower track (960x540 or 704x396) in Sony TV with Android TV.

Video showing the issue:
https://drive.google.com/open?id=1jLTSyw7e8oc1q7J9RL3L3v7Fq7asWjjc

### [REQUIRED] Reproduction steps
In a Sony Bravia 4K with Android TV (BRAVIA_ATV3_4K), install exoplayer demo app with related content.
Play the content and reduce bandwidth to make exoplayer descend to lower tracks (960x540 or 704x396). 
Problems with image are shown when changing quality.

### [REQUIRED] Link to test content
Sended by email.
The content has drm protection and HDMI HDCP 2.1 protection

### [REQUIRED] A full bug report captured from the device
Bugreport: https://drive.google.com/open?id=1NtR1VTcfoBbyz241cnN53Nd2kU7RWTIu
Logcat output: https://drive.google.com/open?id=16IhzpLdNEU2lQEO85Qj_8OMPZIgfhuIY

### [REQUIRED] Version of ExoPlayer being used
Tested with versión 2.11.1
Same results with 2.10.5 and 2.9.2

### [REQUIRED] Device(s) and version(s) of Android being used
Issue is happening in 
Sony BRAVIA_ATV3_4K with AndroidTV 8.0
We don't have more Sony 4K AndroidTV to test.

Issue doesn't happen in:
ARRIS VIP5242A AndroidTV 9.0 connected to TV Samsung ue40ku6000
ARRIS VIP5242A AndroidTV 9.0 connected to Monitor BenQ EL2870U
Xiaomi Mi Box 3 (AndroidTV 8.0) connected to Sony BRAVIA_ATV3_4K (same as issue)

### Issues maybe related
https://github.com/google/ExoPlayer/issues/7009

**Comment by icbaker** [comment]
Thanks for the report, unfortunately as noted in https://github.com/google/ExoPlayer/issues/7009#issuecomment-602460636 the COVID-19 situation means we don't currently have access to a Sony TV for testing, so if this issue only reproduces on that hardware then we're not going to be able to look deeply in to it.

This sounds similar enough to 7009 that I'm going to assign it to @Samrobbo, they can take a look at both when we're able to access a device that repros the problem.

**Comment by BoschAlejandro** [comment]
Hi @icbaker and @Samrobbo 
There is nothing in the files logcat or bugreport that I have attached that gives you a clue about what is happening?

Thanks

**Comment by BoschAlejandro** [comment]
Hi @icbaker and @Samrobbo 

Can you take a look at logcat files? Maybe you see something that I don't see because I don't know where to look.

Thanks a lot.

**Comment by Manasovo** [comment]
Hi guys,

same situation and offer from our side. If your office is open now, we can deliver SONY Tv for free. Just let me know !

**Comment by ojw28** [comment]
Duplicating to https://github.com/google/ExoPlayer/issues/7009; there's no need for us to have two issues tracking this. Our office is still closed, and we do not have a date for it reopening.
