### ISSUE TITLE
Google Cast

### ISSUE THREAD

**Issue by ghost** [google/ExoPlayer#7249]
Hello friends.
I need your help, I used the demo-cast example Exoplayer r.2.11.4 to use my chrome cast, and it works perfectly with the streams found in the example.
1-> I edited the stream url to http://jatenstvdeborla.ddns.net:81/encurt/0cXzY,
2-> I edited the MediaSource buildMediaSource (MediaItem item) function in PlayerManager.java 
3-> I compiled the apk and played the stream only when I send Cast to my Google Cast it does not play the stream. I liked your help.

Note: the only changes to the project have been mentioned above

package com.google.android.exoplayer2.castdemo;

import android.net.Uri;
import com.google.android.exoplayer2.C;
import com.google.android.exoplayer2.ext.cast.MediaItem;
import com.google.android.exoplayer2.ext.cast.MediaItem.DrmConfiguration;
import com.google.android.exoplayer2.util.MimeTypes;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/** Utility methods and constants for the Cast demo application. */
/* package */ final class DemoUtil {

  public static final String MIME_TYPE_DASH = MimeTypes.APPLICATION_MPD;
  public static final String MIME_TYPE_HLS = MimeTypes.APPLICATION_M3U8;
  public static final String MIME_TYPE_SS = MimeTypes.APPLICATION_SS;
  public static final String MIME_TYPE_VIDEO_MP4 = MimeTypes.VIDEO_MP4;

  /** The list of samples available in the cast demo app. */
  public static final List<MediaItem> SAMPLES;

  static {
    ArrayList<MediaItem> samples = new ArrayList<>();

    // Clear content.
    samples.add(
        new MediaItem.Builder()
            .setUri("http://jatenstvdeborla.ddns.net:81/encurt/dFOJo")
            .setTitle("Clear DASH: Tears")
            .setMimeType(MIME_TYPE_DASH)
            .build());
    samples.add(
        new MediaItem.Builder()
            .setUri("http://jatenstvdeborla.ddns.net:81/encurt/dFOJo")
            .setTitle("Clear HLS: Angel one")
            .setMimeType(MIME_TYPE_HLS)
            .build());
    samples.add(
        new MediaItem.Builder()
            .setUri("http://jatenstvdeborla.ddns.net:81/encurt/dFOJo")
            .setTitle("Clear MP4: Dizzy")
            .setMimeType(MIME_TYPE_VIDEO_MP4)
            .build());

    // DRM content.
    samples.add(
        new MediaItem.Builder()
            .setUri(Uri.parse("http://jatenstvdeborla.ddns.net:81/encurt/dFOJo"))
            .setTitle("Widevine HLS cenc: Tears")
            .setMimeType(MIME_TYPE_HLS)
            .setDrmConfiguration(
                new DrmConfiguration(
                    C.CLEARKEY_UUID,
                    Uri.parse("https://proxy.uat.widevine.com/proxy?provider=widevine_test"),
                    Collections.emptyMap()))
            .build());
    samples.add(
        new MediaItem.Builder()
            .setUri(
                Uri.parse(
                    "http://jatenstvdeborla.ddns.net:81/encurt/dFOJo"))
            .setTitle("Widevine DASH cbc1: Tears")
            .setMimeType(MIME_TYPE_DASH)
            .setDrmConfiguration(
                new DrmConfiguration(
                    C.CLEARKEY_UUID,
                    Uri.parse("https://proxy.uat.widevine.com/proxy?provider=widevine_test"),
                    Collections.emptyMap()))
            .build());
    samples.add(
        new MediaItem.Builder()
            .setUri(
                Uri.parse(
                    "http://jatenstvdeborla.ddns.net:81/encurt/dFOJo"))
            .setTitle("Widevine SS cbcs: Tears")
            .setMimeType(MIME_TYPE_SS)
            .setDrmConfiguration(
                new DrmConfiguration(
                    C.CLEARKEY_UUID,
                    Uri.parse("https://proxy.uat.widevine.com/proxy?provider=widevine_test"),
                    Collections.emptyMap()))
            .build());

    samples.add(
        new MediaItem.Builder()
            .setUri(
                Uri.parse(
                    "http://jatenstvdeborla.ddns.net:81/encurt/dFOJo"))
            .setTitle("Widevine MP4 cbcs: Tears")
            .setMimeType(MIME_TYPE_VIDEO_MP4)
            .setDrmConfiguration(
                new DrmConfiguration(
                    C.CLEARKEY_UUID,
                    Uri.parse("https://proxy.uat.widevine.com/proxy?provider=widevine_test"),
                    Collections.emptyMap()))
            .build());

    SAMPLES = Collections.unmodifiableList(samples);
  }

  private DemoUtil() {}
}

package com.google.android.exoplayer2.castdemo;

import android.content.Context;
import android.net.Uri;
import android.view.KeyEvent;
import android.view.View;
import com.google.android.exoplayer2.C;
import com.google.android.exoplayer2.Player;
import com.google.android.exoplayer2.Player.DiscontinuityReason;
import com.google.android.exoplayer2.Player.EventListener;
import com.google.android.exoplayer2.Player.TimelineChangeReason;
import com.google.android.exoplayer2.SimpleExoPlayer;
import com.google.android.exoplayer2.Timeline;
import com.google.android.exoplayer2.Timeline.Period;
import com.google.android.exoplayer2.drm.DefaultDrmSessionManager;
import com.google.android.exoplayer2.drm.DrmSessionManager;
import com.google.android.exoplayer2.drm.ExoMediaCrypto;
import com.google.android.exoplayer2.drm.FrameworkMediaDrm;
import com.google.android.exoplayer2.drm.HttpMediaDrmCallback;
import com.google.android.exoplayer2.ext.cast.CastPlayer;
import com.google.android.exoplayer2.ext.cast.DefaultMediaItemConverter;
import com.google.android.exoplayer2.ext.cast.MediaItem;
import com.google.android.exoplayer2.ext.cast.MediaItemConverter;
import com.google.android.exoplayer2.ext.cast.SessionAvailabilityListener;
import com.google.android.exoplayer2.source.ConcatenatingMediaSource;
import com.google.android.exoplayer2.source.MediaSource;
import com.google.android.exoplayer2.source.ProgressiveMediaSource;
import com.google.android.exoplayer2.source.TrackGroupArray;
import com.google.android.exoplayer2.source.dash.DashMediaSource;
import com.google.android.exoplayer2.source.hls.HlsMediaSource;
import com.google.android.exoplayer2.source.smoothstreaming.SsMediaSource;
import com.google.android.exoplayer2.trackselection.DefaultTrackSelector;
import com.google.android.exoplayer2.trackselection.MappingTrackSelector;
import com.google.android.exoplayer2.trackselection.TrackSelectionArray;
import com.google.android.exoplayer2.ui.PlayerControlView;
import com.google.android.exoplayer2.ui.PlayerView;
import com.google.android.exoplayer2.upstream.DefaultDataSourceFactory;
import com.google.android.exoplayer2.upstream.DefaultHttpDataSource;
import com.google.android.exoplayer2.upstream.DefaultHttpDataSourceFactory;
import com.google.android.exoplayer2.util.Util;
import com.google.android.gms.cast.MediaQueueItem;
import com.google.android.gms.cast.framework.CastContext;
import java.util.ArrayList;
import java.util.Map;

  private static final String USER_AGENT = "ExoCastDemoPlayer";
  private static final DefaultHttpDataSourceFactory DATA_SOURCE_FACTORY =
      new DefaultHttpDataSourceFactory(USER_AGENT);

  private final PlayerView localPlayerView;
  private final PlayerControlView castControlView;
  private final DefaultTrackSelector trackSelector;
  private final SimpleExoPlayer exoPlayer;
  private final CastPlayer castPlayer;
  private final ArrayList<MediaItem> mediaQueue;
  private final Listener listener;
  private final ConcatenatingMediaSource concatenatingMediaSource;
  private final MediaItemConverter mediaItemConverter;

  private TrackGroupArray lastSeenTrackGroupArray;
  private int currentItemIndex;
  private Player currentPlayer;
  private Context ctx;

  /**
   * Creates a new manager for {@link SimpleExoPlayer} and {@link CastPlayer}.
   *
   * @param listener A {@link Listener} for queue position changes.
   * @param localPlayerView The {@link PlayerView} for local playback.
   * @param castControlView The {@link PlayerControlView} to control remote playback.
   * @param context A {@link Context}.
   * @param castContext The {@link CastContext}.
   */
  public PlayerManager(
      Listener listener,
      PlayerView localPlayerView,
      PlayerControlView castControlView,
      Context context,
      CastContext castContext) {
    this.ctx = context;
    this.listener = listener;
    this.localPlayerView = localPlayerView;
    this.castControlView = castControlView;
    mediaQueue = new ArrayList<>();
    currentItemIndex = C.INDEX_UNSET;
    concatenatingMediaSource = new ConcatenatingMediaSource();
    mediaItemConverter = new DefaultMediaItemConverter();

    trackSelector = new DefaultTrackSelector(context);
    exoPlayer = new SimpleExoPlayer.Builder(context).setTrackSelector(trackSelector).build();
    exoPlayer.addListener(this);
    localPlayerView.setPlayer(exoPlayer);

    castPlayer = new CastPlayer(castContext);
    castPlayer.addListener(this);
    castPlayer.setSessionAvailabilityListener(this);
    castControlView.setPlayer(castPlayer);

    setCurrentPlayer(castPlayer.isCastSessionAvailable() ? castPlayer : exoPlayer);
  }

  // Queue manipulation methods.

  /**
   * Plays a specified queue item in the current player.
   *
   * @param itemIndex The index of the item to play.
   */
  public void selectQueueItem(int itemIndex) {
    setCurrentItem(itemIndex, C.TIME_UNSET, true);
  }

  /** Returns the index of the currently played item. */
  public int getCurrentItemIndex() {
    return currentItemIndex;
  }

  /**
   * Appends {@code item} to the media queue.
   *
   * @param item The {@link MediaItem} to append.
   */
  public void addItem(MediaItem item) {
    mediaQueue.add(item);
    concatenatingMediaSource.addMediaSource(buildMediaSource(item));
    if (currentPlayer == castPlayer) {
      castPlayer.addItems(mediaItemConverter.toMediaQueueItem(item));
    }
  }

  /** Returns the size of the media queue. */
  public int getMediaQueueSize() {
    return mediaQueue.size();
  }

  /**
   * Returns the item at the given index in the media queue.
   *
   * @param position The index of the item.
   * @return The item at the given index in the media queue.
   */
  public MediaItem getItem(int position) {
    return mediaQueue.get(position);
  }

  /**
   * Removes the item at the given index from the media queue.
   *
   * @param item The item to remove.
   * @return Whether the removal was successful.
   */
  public boolean removeItem(MediaItem item) {
    int itemIndex = mediaQueue.indexOf(item);
    if (itemIndex == -1) {
      return false;
    }
    concatenatingMediaSource.removeMediaSource(itemIndex);
    if (currentPlayer == castPlayer) {
      if (castPlayer.getPlaybackState() != Player.STATE_IDLE) {
        Timeline castTimeline = castPlayer.getCurrentTimeline();
        if (castTimeline.getPeriodCount() <= itemIndex) {
          return false;
        }
        castPlayer.removeItem((int) castTimeline.getPeriod(itemIndex, new Period()).id);
      }
    }
    mediaQueue.remove(itemIndex);
    if (itemIndex == currentItemIndex && itemIndex == mediaQueue.size()) {
      maybeSetCurrentItemAndNotify(C.INDEX_UNSET);
    } else if (itemIndex < currentItemIndex) {
      maybeSetCurrentItemAndNotify(currentItemIndex - 1);
    }
    return true;
  }

  /**
   * Moves an item within the queue.
   *
   * @param item The item to move.
   * @param toIndex The target index of the item in the queue.
   * @return Whether the item move was successful.
   */
  public boolean moveItem(MediaItem item, int toIndex) {
    int fromIndex = mediaQueue.indexOf(item);
    if (fromIndex == -1) {
      return false;
    }
    // Player update.
    concatenatingMediaSource.moveMediaSource(fromIndex, toIndex);
    if (currentPlayer == castPlayer && castPlayer.getPlaybackState() != Player.STATE_IDLE) {
      Timeline castTimeline = castPlayer.getCurrentTimeline();
      int periodCount = castTimeline.getPeriodCount();
      if (periodCount <= fromIndex || periodCount <= toIndex) {
        return false;
      }
      int elementId = (int) castTimeline.getPeriod(fromIndex, new Period()).id;
      castPlayer.moveItem(elementId, toIndex);
    }

    mediaQueue.add(toIndex, mediaQueue.remove(fromIndex));

    // Index update.
    if (fromIndex == currentItemIndex) {
      maybeSetCurrentItemAndNotify(toIndex);
    } else if (fromIndex < currentItemIndex && toIndex >= currentItemIndex) {
      maybeSetCurrentItemAndNotify(currentItemIndex - 1);
    } else if (fromIndex > currentItemIndex && toIndex <= currentItemIndex) {
      maybeSetCurrentItemAndNotify(currentItemIndex + 1);
    }

    return true;
  }

  /**
   * Dispatches a given {@link KeyEvent} to the corresponding view of the current player.
   *
   * @param event The {@link KeyEvent}.
   * @return Whether the event was handled by the target view.
   */
  public boolean dispatchKeyEvent(KeyEvent event) {
    if (currentPlayer == exoPlayer) {
      return localPlayerView.dispatchKeyEvent(event);
    } else /* currentPlayer == castPlayer */ {
      return castControlView.dispatchKeyEvent(event);
    }
  }

  /** Releases the manager and the players that it holds. */
  public void release() {
    currentItemIndex = C.INDEX_UNSET;
    mediaQueue.clear();
    concatenatingMediaSource.clear();
    castPlayer.setSessionAvailabilityListener(null);
    castPlayer.release();
    localPlayerView.setPlayer(null);
    exoPlayer.release();
  }

  // Player.EventListener implementation.

  @Override
  public void onPlayerStateChanged(boolean playWhenReady, @Player.State int playbackState) {
    updateCurrentItemIndex();
  }

  @Override
  public void onPositionDiscontinuity(@DiscontinuityReason int reason) {
    updateCurrentItemIndex();
  }

  @Override
  public void onTimelineChanged(Timeline timeline, @TimelineChangeReason int reason) {
    updateCurrentItemIndex();
  }

  @Override
  public void onTracksChanged(TrackGroupArray trackGroups, TrackSelectionArray trackSelections) {
    if (currentPlayer == exoPlayer && trackGroups != lastSeenTrackGroupArray) {
      MappingTrackSelector.MappedTrackInfo mappedTrackInfo =
          trackSelector.getCurrentMappedTrackInfo();
      if (mappedTrackInfo != null) {
        if (mappedTrackInfo.getTypeSupport(C.TRACK_TYPE_VIDEO)
            == MappingTrackSelector.MappedTrackInfo.RENDERER_SUPPORT_UNSUPPORTED_TRACKS) {
          listener.onUnsupportedTrack(C.TRACK_TYPE_VIDEO);
        }
        if (mappedTrackInfo.getTypeSupport(C.TRACK_TYPE_AUDIO)
            == MappingTrackSelector.MappedTrackInfo.RENDERER_SUPPORT_UNSUPPORTED_TRACKS) {
          listener.onUnsupportedTrack(C.TRACK_TYPE_AUDIO);
        }
      }
      lastSeenTrackGroupArray = trackGroups;
    }
  }

  // CastPlayer.SessionAvailabilityListener implementation.

  @Override
  public void onCastSessionAvailable() {
    setCurrentPlayer(castPlayer);
  }

  @Override
  public void onCastSessionUnavailable() {
    setCurrentPlayer(exoPlayer);
  }

  // Internal methods.

  private void updateCurrentItemIndex() {
    int playbackState = currentPlayer.getPlaybackState();
    maybeSetCurrentItemAndNotify(
        playbackState != Player.STATE_IDLE && playbackState != Player.STATE_ENDED
            ? currentPlayer.getCurrentWindowIndex()
            : C.INDEX_UNSET);
  }

  private void setCurrentPlayer(Player currentPlayer) {
    if (this.currentPlayer == currentPlayer) {
      return;
    }

    // View management.
    if (currentPlayer == exoPlayer) {
      localPlayerView.setVisibility(View.VISIBLE);
      castControlView.hide();
    } else /* currentPlayer == castPlayer */ {
      localPlayerView.setVisibility(View.GONE);
      castControlView.show();
    }

    // Player state management.
    long playbackPositionMs = C.TIME_UNSET;
    int windowIndex = C.INDEX_UNSET;
    boolean playWhenReady = false;

    Player previousPlayer = this.currentPlayer;
    if (previousPlayer != null) {
      // Save state from the previous player.
      int playbackState = previousPlayer.getPlaybackState();
      if (playbackState != Player.STATE_ENDED) {
        playbackPositionMs = previousPlayer.getCurrentPosition();
        playWhenReady = previousPlayer.getPlayWhenReady();
        windowIndex = previousPlayer.getCurrentWindowIndex();
        if (windowIndex != currentItemIndex) {
          playbackPositionMs = C.TIME_UNSET;
          windowIndex = currentItemIndex;
        }
      }
      previousPlayer.stop(true);
    }

    this.currentPlayer = currentPlayer;

    // Media queue management.
    if (currentPlayer == exoPlayer) {
      exoPlayer.prepare(concatenatingMediaSource);
    }

    // Playback transition.
    if (windowIndex != C.INDEX_UNSET) {
      setCurrentItem(windowIndex, playbackPositionMs, playWhenReady);
    }
  }

  /**
   * Starts playback of the item at the given position.
   *
   * @param itemIndex The index of the item to play.
   * @param positionMs The position at which playback should start.
   * @param playWhenReady Whether the player should proceed when ready to do so.
   */
  private void setCurrentItem(int itemIndex, long positionMs, boolean playWhenReady) {
    maybeSetCurrentItemAndNotify(itemIndex);
    if (currentPlayer == castPlayer && castPlayer.getCurrentTimeline().isEmpty()) {
      MediaQueueItem[] items = new MediaQueueItem[mediaQueue.size()];
      for (int i = 0; i < items.length; i++) {
        items[i] = mediaItemConverter.toMediaQueueItem(mediaQueue.get(i));
      }
      castPlayer.loadItems(items, itemIndex, positionMs, Player.REPEAT_MODE_OFF);
    } else {
      currentPlayer.seekTo(itemIndex, positionMs);
      currentPlayer.setPlayWhenReady(playWhenReady);
    }
  }

  private void maybeSetCurrentItemAndNotify(int currentItemIndex) {
    if (this.currentItemIndex != currentItemIndex) {
      int oldIndex = this.currentItemIndex;
      this.currentItemIndex = currentItemIndex;
      listener.onQueuePositionChanged(oldIndex, currentItemIndex);
    }
  }

  private MediaSource buildMediaSource(MediaItem item) {
    Uri uri = item.uri;

    DrmSessionManager<ExoMediaCrypto> drmSessionManager =
        DrmSessionManager.getDummyDrmSessionManager();
    MediaItem.DrmConfiguration drmConfiguration = item.drmConfiguration;
    if (drmConfiguration != null && Util.SDK_INT >= 18) {
      String licenseServerUrl =
          drmConfiguration.licenseUri != null ? drmConfiguration.licenseUri.toString() : "";
      HttpMediaDrmCallback drmCallback =
          new HttpMediaDrmCallback(licenseServerUrl, DATA_SOURCE_FACTORY);
      for (Map.Entry<String, String> requestHeader : drmConfiguration.requestHeaders.entrySet()) {
        drmCallback.setKeyRequestProperty(requestHeader.getKey(), requestHeader.getValue());
      }
      drmSessionManager =
          new DefaultDrmSessionManager.Builder()
              .setMultiSession(/* multiSession= */ true)
              .setUuidAndExoMediaDrmProvider(
                  drmConfiguration.uuid, FrameworkMediaDrm.DEFAULT_PROVIDER)
              .build(drmCallback);
    }

    MediaSource createdMediaSource;
    String userAgent = Util.getUserAgent(ctx,"oxoo");

    // Default parameters, except allowCrossProtocolRedirects is true
    DefaultHttpDataSourceFactory httpDataSourceFactory = new DefaultHttpDataSourceFactory(
        userAgent,
        null /* listener */,
        DefaultHttpDataSource.DEFAULT_CONNECT_TIMEOUT_MILLIS,
        DefaultHttpDataSource.DEFAULT_READ_TIMEOUT_MILLIS,
        true /* allowCrossProtocolRedirects */
    );

    DefaultDataSourceFactory dataSourceFactory = new DefaultDataSourceFactory(
        ctx,
        null /* listener */,
        httpDataSourceFactory
    );

        createdMediaSource =new ProgressiveMediaSource.Factory(dataSourceFactory)
            .setDrmSessionManager(drmSessionManager)
            .createMediaSource(uri);

    return createdMediaSource;
  }
}

**Comment by marcbaechinger** [comment]
You can not put arbitrary video streams in the sample with a random mime type and expect them to play. The streams must be supported by the cast device and you need to use a matching mime-type. In the samples you just replaced every url with the same url and tried playing them with any mime type.

When I curl the url you used it gives me two redirects and in the end a file of type `Content-Type: video/mp2t`. This is likely not supported by the cast device I suspect.

You can use the following type of streams like the DemoUtil exemplifies:

* MimeTypes.APPLICATION_MPD: adaptive DASH streams
* MimeTypes.APPLICATION_M3U8: adaptive HLS streams
* MimeTypes.APPLICATION_SS: adaptive smoothstreaming streams
* MimeTypes.VIDEO_MP4: progressive MP4 streams

Easiest is to test your app with a sample MP4 once this works you can go from there.

There is also a page  telling which formats are supported by cast in the cast documentation:
https://developers.google.com/cast/docs/media

**Comment by ghost** [comment]
Hello @marcbaechinger 

Thanks for the quick response,
I find it strange that on the phone the stream is reproduced, and not on the cast, that is, the cast only supports:

MimeTypes.APPLICATION_MPD: adaptive DASH streams
MimeTypes.APPLICATION_M3U8: adaptive HLS streams
MimeTypes.APPLICATION_SS: adaptive smoothstreaming streams
MimeTypes.VIDEO_MP4: progressive MP4 streams

**Comment by marcbaechinger** [comment]
I think it's not unusual or surprising that different devices with different operating systems are supporting different media formats. 

Cast does probably support other formats as well as documented in the link I pasted above:
https://developers.google.com/cast/docs/media

I'm closing this issue now. Feel free to re-open if you think I can help you some further.
