### ISSUE TITLE
Change playback speed, occurs underrun

### ISSUE THREAD

**Issue by Romantic-LiXuefeng** [google/ExoPlayer#7252]
### [REQUIRED] Issue description
I used the release apk to test. When change the playback to 1.5x, 1.75x. 2.0x. it occurs the audio underrun. It's only occur in specific device. I'm not clear what's the reason.  whether because of device cpu performance poor, or low memory?  I have captured the full bug report, hope give some explain.

### [REQUIRED] A full bug report captured from the device

[bugrerport.zip](https://github.com/google/ExoPlayer/files/4490892/bugrerport.zip)

### [REQUIRED] Version of ExoPlayer being used
version: 2.9.0

**Comment by Samrobbo** [comment]
Hi, 

Does this happen with all media you try, or is it specific? Is it possible to get the test media you used, so I can attempt to reproduce this on my end.

Also, how are you changing the playback speed, if possible can I get a code snippet of this? 

Thanks.

**Comment by Romantic-LiXuefeng** [comment]
I think it's not the test media ,because of in other device it works well in different playback speed.
And the test media can't request in the public internet.   

The code snippet: 
```
    /*
     * @param speed must between 0.5x ~ 2.0x
     * Must called on Main Thread
     */
    public void setPlaybackSpeed(float speed){
        if (speed < 0.5 || speed > 2.0){
            Log.w(TAG,"playback speed is invalid, speed = [" + speed + "]");
            return;
        }
        if (mExoPlayer != null){
            PlaybackParameters playbackParameters = mExoPlayer.getPlaybackParameters();
            if (playbackParameters.speed != speed){
                mExoPlayer.setPlaybackParameters(new PlaybackParameters(speed));
            }else {
                Log.d(TAG,"playback speed is not changed!");
            }
   }
```
I can't understand the bugreport's meaning. Could you give some explain?

**Comment by Samrobbo** [comment]
What device/OS are you using? 

Test media wise, if you're unable to share test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Let me know when you've done this. 

Thanks

**Comment by Romantic-LiXuefeng** [comment]
#https://github.com/google/ExoPlayer/issues/7252

**Comment by Samrobbo** [comment]
Closing as bot was about to close, and no new information has been given.
