### ISSUE TITLE
How to use exo-cronet and okhttp together

### ISSUE THREAD

**Issue by leotyndale** [google/ExoPlayer#7254]
Hello, we have used exo-okhttp and exo-cronet, and they are running normally.
But the problem is that when using the quic protocol to play video through exo-cronet, there is no way to go through the okhttp interceptor. How can I make the request pass the okhttp interceptor based on exo-cronet?
Because we have added a lot of unified processing functions to the okhttp interceptor, such as log printing, UA changes, etc., so we can’t do without okhttp.

**Comment by icbaker** [comment]
Just to check I've understood correctly: You want your requests to go through both `CronetDataSource` and `OkHttpDataSource`?

Both of these make their requests directly on to the network, so plumbing through both isn't very trivial.

I think you'll need to create your own `HttpDataSource` implementation that wires up the behaviour you expect.

**Comment by leotyndale** [comment]
@icbaker 
Thank you for your help, but I still have some questions that are not very clear.

Is there anything special about exo-cronet?
Can I just use exo-http without exo-cronet, and then process quic network requests in okhttp interceptor. Most of my simple network requests are handled in this way. 
If I deal with this way, Is there anything on EXO that needs process carefully?

**Comment by icbaker** [comment]
> Can I just use exo-http without exo-cronet, and then process quic network requests in okhttp interceptor. Most of my simple network requests are handled in this way.

Do you mean **exo-okhttp** here?

I found this blog post that includes a mention of using an OkHttp interceptor to get cronet behaviour with OkHttp:
https://medium.com/the-react-native-log/using-cronet-in-your-mobile-app-7dda3a89c132

I haven't tried it, but you could give it a go. I suppose you'd use `OkHttpDataSource` and register the interceptor mentioned there.
