### ISSUE TITLE
How to sync notification Play/Pause into the Activity UI

### ISSUE THREAD

**Issue by marctan** [google/ExoPlayer#7255]
Hi,

I'm trying to create my own music player and I'm following the client/server approach stated in https://developer.android.com/guide/topics/media-apps/media-apps-overview. 

I've my own UI for play, pause, prev, next and implemented a Service.
I'm using the PlayerNotificationManager to display the song detail in notification section. 
I would like to sync the buttons of notification into the UI of my Activity. For example, if I click the Pause button in the notification, the button should also update automatically in my Activity. They should have the same state. 

I've read somewhere that I should use MediaController's callback (onPlaybackStateChanged) to update my UI. But to use it, I need the MediaSessionCompat token. My mediasession is instantiated under the Service and the mediaController is instantiated in the Activity.  

How can I pass the mediaSession token from the Service to my Activity? I don't want to use the MediaBrowser since I don't need it.

Is it ok to use localbroadcastmanager and pass the token to the activity using intent? 

Thanks!

**Comment by marcbaechinger** [comment]
There are various ways you can do that. 

Basically, you need to start the service somehow, so you can use a `ResultReceiver` which you add as an extra to your intent with which you start the service from the activity. The service receives your intent, creates the player and the media session and then sends the token via  `ResultReceiver` to your activity. 

> pass the token to the activity using intent?

Sure. The media session token is a simple object which you can pass around as you like. Once you received it you can create the MediaControllerCompat to connect to the session to which the given token belongs to.

Once you have such a media controller you can even listen to when the [media session is destroyed](https://developer.android.com/reference/android/support/v4/media/session/MediaControllerCompat.Callback#onSessionDestroyed()), so you know your service who owns the media session has been terminated.

**Comment by marctan** [comment]
I've ended up using local broadcast to get the token tnx
