### ISSUE TITLE
ExoPlayer Buffering

### ISSUE THREAD

**Issue by Brij09** [google/ExoPlayer#7256]
I am using exoplayer to play multiple videos on recyclerview with caching. Before playing i prepare player for 5 videos at a time as a result of which exoplayer starts buffering and caching for all 5 videos at a time. So i am worried if there any impact on buffering of currently playing video. if so then how i can handle this situation.

**Comment by Brij09** [comment]
Hi,  I am using exoplayer to play multiple videos on recyclerview with caching. Before playing i prepare player for 5 videos at a time as a result of which exoplayer starts buffering and caching for all 5 videos at a time. So i am worried if there any impact on buffering of currently playing video. if so then how i can handle this situation.

**Comment by tonihei** [comment]
When you say "i prepare player for 5 videos at a time as a result of which exoplayer starts buffering and caching for all 5 videos at a time", it's not clear if 
 (1) you call `player.prepare` on 5 different player instances,
 (2) or if you use ExoPlayer's caching functionality that downloads to a cache.

I wouldn't recommend to do (1). One reason is that it may use download bandwidth that impacts the currently playing video as you say. And also, many devices have a limited number of decoders that can be used at the same time (in some cases only one decoder).

The right way to do this is (2). You can read more about ExoPlayer's download functionality here: https://exoplayer.dev/downloading-media.html. If you just want to download while the app in in foreground, you can also ignore the part about the service and just use `DownloadManager`. 

The advantage of doing this is that it just downloads the media data and uses no decoders, so you can't run into the problem of not having enough decoders. In addition, you can pass in a `PriorityTaskManager` to both the `DownloadManager` and the `SimpleExoPlayer`. This priority task manager automatically ensures that no download is progressing while the currently playing media is downloaded. Only once the playback buffer for the current media is filled can the other downloads continue. 

To pass in the `ProrityTaskManager` to `DownloadManager`, you need to do the following when creating the `DownloadManager`:
```
new DownloadManager(
        context,
        new DefaultDownloadIndex(databaseProvider),
        new DefaultDownloaderFactory(
            new DownloaderConstructorHelper(
                cache, upstreamFactory, null, null, priorityTaskManager))); 
```
And then use the same `ProrityTaskManager` in `SimpleExoPlayer.setPriorityTaskManager`.

**Comment by Brij09** [comment]
i am not using any Download functionality. I am just using Simple caching to avoid re buffering when i play same video again and  I am using different instance of exoplayer to prepare player. How can I give all bandwidth to currently playing video while its buffering.

**Comment by tonihei** [comment]
Please see my answer above, you need to use `PriorityTaskManager` to make sure playback has priority over background caching/downloading.

> I am just using Simple caching

Not sure what you mean that exactly, but if it is `CacheUtil.cache`, then you can also pass in the `PriorityTaskManager` in there.
