### ISSUE TITLE
Is there any way to save audio after changing the Playback Parameters

### ISSUE THREAD

**Issue by Mouadabdelghafouraitali** [google/ExoPlayer#7259]
After changing the **playback parameters** (Speed and Pitch), I'm looking now for a way to saving the audio as a file in **SD**, is there any way to achieve that?

**Comment by AquilesCanta** [comment]
Please have a look at the [TeeAudioProcessor](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/audio/TeeAudioProcessor.html) and [WavFileAudioBufferSink](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/audio/TeeAudioProcessor.WavFileAudioBufferSink.html). That should probably be enough.
