### ISSUE TITLE
Support injection of custom stream readers into TsExtractor (e.g. to handle DVB subtitles)

### ISSUE THREAD

**Issue by tresvecesseis** [google/ExoPlayer#726]
are you interested in DVB subtitle (or any other kind graphic subtitle) support in Exoplayer, I made a pull request #705 and I don´t know if you don´t have time to check the patch or there are other problems with it

**Comment by ojw28** [comment]
We're thinking about it; it's not high up the list of things we want to land though. My gut feeling is that we wont want to support this directly. It's not something we want to be encouraging v.s. having services send text format subtitles, and it seems to exist largely for legacy reasons. It also looks like quite a lot of code that we'd have to maintain.

If we don't take it, we should at least provide a way for clients to inject their own support without having to modify the library. This probably means the ability to inject custom stream readers into a TsExtractor instance.

**Comment by tresvecesseis** [comment]
i don´t agree to call "legacy" to one the most used subtitle format in the world, dvb-t is the main TV service in most of the world (all Europe and Australia, almost all Africa and Asia, part of South America and Greenland), so you are excluding the posibility to use the exoplayer library to create TV/DVD/BR players, in any case we will maintain our fork of the exoplayer library until you provide the means to extract the TS data to be able to integrate the funtionality in our player

**Comment by ojw28** [comment]
I mean legacy for streaming. Doesn't your suggested use case require custom hardware? I don't think Android has any APIs for receiving raw terrestrial broadcast streams, although please correct me if I'm wrong.

**Comment by tresvecesseis** [comment]
In the OTT case that´s true but we manage a private multicast VDN (with several million of customers)  that is based in DVB-IPI (so no special hardware needed), I could understand that is not a typical scenario and that is why we propose to generalize the graphics subtitle renderer to give support to DVB/BR subtitles given that the DVD/BR streaming from a home video server is way more popular.

For the hardware and API support, all the Android TVs have the required hardware but the APIs for accesing the hardware doesn´t seem to be available currently for the creation of new tuners (they are system/vendor private), and the other Android 4.x chinese boxes available use standard linux v4l2 drivers/APIs, but, as you said, there is not an Android APi to control the DVB tuners  and it depends in proper implementation by the player.

Having said that, it could be enough if we had a way to enumerate the tracks/PIDs and extract them to be processed by the player, something like passing a callback to the exoplayer library to be called when new data/PES is available for a given track/PID. Could that be a workable solution?

**Comment by ojw28** [comment]
In the OTT case I'd expect most providers to be converting subtitles into a more suitable format for OTT delivery. The one case where this doesn't really hold is if you're not the original broadcaster and only have access to the DVT subtitles, in which case I guess you'd need to OCR them, which would be messy. This seems like a relatively niche case though.

I don't know if the Android TV people have plans to expose any new APIs, but I would guess that they wouldn't expose the raw feed in a way that would make ExoPlayer supporting DVB subtitles useful. It feels like a much higher level API would make sense, with the DVB support remaining in the platform.

Agreed that there should be a way to inject custom handlers into TsExtractor. Let's use this bug to track that request.

**Comment by tresvecesseis** [comment]
@ojw28 I've sent another pull request #1781 for the v2 branch, to support DVB subtitles, it´s much less invasive that the old one (only minimal adjustments in two files of the core library)  and I think it's a valuable addition for the European/Asian IPTV developers.

**Comment by AquilesCanta** [comment]
In the next push a fix for this will be provided. The API is a bit awkward, yet, due to HLS compatibility requisites, but we are working on it.

**Comment by AquilesCanta** [comment]
Guys, let me know if you find any inconveniences with the API for reader injection. It should be possible to inject any kind of readers now. Thanks for being patient about it.

**Comment by tresvecesseis** [comment]
thanks, I supposse that this is the API we should use to implement additional subtitle formats, isnt't it?

**Comment by AquilesCanta** [comment]
Well, this is the API you should use to implement additional subtitle format extraction from TS. That is, through this API you can provide the readers to the TsExtractor. They will obtain a trackOutput from the extractor output, and that will eventually be passed to the decoders. TsExtractorTest may serve as example.

Depending on the format, you will also have to create a SubtitleDecoder, if no decoder exists (if it exists, you need to pass whatever it needs).

You can have a look at the CeaxxxDecoder's, or the Mp4WebvttDecoder for an example.

**Comment by kiall** [comment]
@tresvecesseis did you ever manage to implement support out-of-tree for DVBSUB and other bitmap subtitles? If so, I'm very interested for use in in https://github.com/kiall/android-tvheadend.

@ojw28 is the exoplayer projects stance still that bitmap based subtitles won't be supported? This rules out a whole category of Android TV apps, where Satellite and Terrestrial content is grabbed and pushed over IP to a Android TV device. For better or worse, bitmap subtitles are pretty much standard for OTA broadcasts (At least in the EU), and aren't going anywhere anytime soon. And worse, transcoding bitmap subtitles to text isn't something many people do, given the need to OCR them :(

**Comment by ojw28** [comment]
@kiall - https://github.com/google/ExoPlayer/issues/179 is the right place to discuss bitmap based subtitles.

**Comment by tresvecesseis** [comment]
@kiall we are pretty busy doing new stuff on our heavily modified ExoPlayer so no time for this porting, but it should be very simple with the support provided by @AquilesCanta to add custom stream readers, you only have to move some classes around (move the DVB subs classes to your player) and provide a Custom TsPayloadReader, you will also need to port  https://github.com/google/ExoPlayer/pull/1781/commits/530977da02f5a52c28fbdbb7924ee32e376673f0 to be able to see the subs.
