### ISSUE TITLE
Video is not payed and player went into idle state with following errors.

### ISSUE THREAD

**Issue by vishal-prepladder** [google/ExoPlayer#7263]
1. com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to http://rajeshkaushal-inct.streaming.media.azure.net/6d208469-6803-48c7-97d1-c35debcdfbd7/Neural-Columns-PyrIPz3e7k.ism/QualityLevels(1470000)/Fragments(video=2220000000,format=mpd-time-csf)

2.Unable to connect error is on both http and https urls
 com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc.secure, Format(1_V_video_4, null, null, video/avc, avc1.64001E, 295000, null, [640, 360, -1.0], [-1, -1])

3. java.lang.IllegalStateException

I have checked several times the player is released and start wherever required. Please let me know if there is way to fix this.

**Comment by kim-vde** [comment]
If I try to open the link in Chrome or in VLC (http or https), nothing is played. Can you provide reproduction steps and necessary files (e.g. manifest) to play the stream?
