### ISSUE TITLE
Add convenience API for querying static metadata

### ISSUE THREAD

**Issue by Jei** [google/ExoPlayer#7266]
### Searched documentation and issues
I've been looking at the issues in this repository regarding Icy metadata and Shoutcast streams, especially:
- https://github.com/google/ExoPlayer/issues/6753
- https://github.com/google/ExoPlayer/issues/5876
- https://github.com/google/ExoPlayer/issues/3735

### Question
I want to add metadata events to the [just_audio](https://pub.dev/packages/just_audio) Flutter plugin, which uses ExoPlayer in the Android version.
I'm trying to read the IcyInfo and IcyHeaders of a Shoutcast stream. Reading the aforementioned resources, plus [this Medium article](https://medium.com/google-exoplayer/exoplayer-2-10-whats-new-15d344eaa8b9), I was under the impression that I could retrieve them by adding a MetadataOutput to the current player, like this:
```java
	MetadataOutput metadataOutput = new MetadataOutput() {
		@Override
		public void onMetadata(Metadata metadata) {
			Log.d("just_audio", "New metadata. Length: " + metadata.length());
			for (int i = 0; i < metadata.length(); i++) {
				final Metadata.Entry entry = metadata.get(i);
				if (entry instanceof IcyHeaders) {
					Log.d("just_audio", "Headers");
				} else if (entry instanceof IcyInfo) {
					icyTitle = ((IcyInfo) entry).title;
					icyUrl = ((IcyInfo) entry).url;
					Log.d("just_audio", "Info");
				}
				broadcastPlaybackEvent();
			}
		}
	};

[...]

	player = new SimpleExoPlayer.Builder(context).build();
	player.addMetadataOutput(metadataOutput);

[...]

	DataSource.Factory dataSourceFactory = new DefaultDataSourceFactory(context, Util.getUserAgent(context, "just_audio"));
	Uri uri = Uri.parse(url);
	mediaSource = new ProgressiveMediaSource.Factory(dataSourceFactory).createMediaSource(uri);
	player.prepare(mediaSource);
```
However, I'm receiving events that contain only IcyInfo metadata entries, and I can't figure out why. I've had the same result with several different streams. Am I doing something wrong during initialization?
I'm using ExoPlayer 2.11.4.

### Link to test content
I've had the same result with all the Shoutcast streams I've tried. Some examples are:
- http://stream2.mpegradio.com:8070/tormented.mp3
- http://static.207.181.251.148.clients.your-server.de:8000/listen
- http://stream.radyoalaturka.com.tr:9100/test.aac (mentioned in #5876)
- https://radio.mahoro-net.org/streams/tsumugi (mentioned in #6753)

The full code I'm using for the Flutter plugin is here: https://github.com/Jei/just_audio/blob/icy-metadata/android/src/main/java/com/ryanheise/just_audio/AudioPlayer.java
I'm currently developing a Flutter app on top of it: https://github.com/Jei/tormentedplayer/tree/develop

**Comment by icbaker** [comment]
The `IcyInfo` represents the "Metadata" section here: https://cast.readme.io/docs/icy#section-metadata It's parsed regularly throughout the stream, and the results are passed to `MetadataOutput.onMetadata()` as you've seen.

The `IcyHeaders` are only parsed once then the connection to the stream is established, and it's made available through the `Format.metadata` field.

So you should be able to retrieve the `IcyHeaders` object by moving your `instanceof IcyHeaders` check to anywhere that you have access to the track's `Format` object.

**Comment by Jei** [comment]
Thank you for the clarification. I'm working on a solution that uses `Player.EventListener.onTracksChanged()` to collect the IcyHeaders for the current track.

**Comment by ojw28** [comment]
@icbaker - We should probably make it easier for developers to know when static metadata has changed, and to retrieve the current static metadata from the player without having to trawl through all the `Format` objects themselves. Could we consider this an enhancement (i.e., provide a better API), rather than (or in addition to) a documentation candidate?
