### ISSUE TITLE
Issue playing larger DASH audio files

### ISSUE THREAD

**Issue by pestopastarasta** [google/ExoPlayer#727]
Hi, 

I'm currently having an issue where exoplayer is giving me a 404 error when I'm trying to stream DASH content from my server. I'm apprehensive about posting this here as I am unsure as to whether or not the issue is from my exoplayer instance or from my server however I felt I should post here just incase it could help clarify my issue. I have made a post on StackOverflow but haven't had any input so I will copy and paste some of what I wrote there.

I'm serving a number of MPD's created through MP4Box to my Exoplayer instance.

These are all audio only.

Each MPD is created with three representations

Playback is fine for the shorter audio clips however when I try to stream one of the larger clips the exoplayer gives a 404 error

com.google.android.exoplayer.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 404

Is there anything in particular that may be causing this? Or any more info I can give out that will help solve this issue?

Thanks all!

For an example of the MPDs I am using on my server please follow this link to my SO question 
http://stackoverflow.com/questions/32035674/exoplayer-not-playing-larger-files-mpd-dash?noredirect=1#comment52006444_32035674

**Comment by ojw28** [comment]
That's a server response indicating that nothing was found at the URL you're requesting. See [here](https://en.wikipedia.org/wiki/HTTP_404). So it's either a serving issue (likely) or an issue with how ExoPlayer is handling your URL (less likely, but possible).

If you think the URL you're seeing this for is valid, please provide the URL (or better - the snippet that you'd copy into Samples.java to add the problematic stream to the demo app) and we can take a look and advise.

**Comment by pestopastarasta** [comment]
Thank you very much for getting back in touch

Here is my web page with all my MPD's 
http://maxmarshall.ddns.net/MPD/

for example this mpd works fine
http://maxmarshall.ddns.net/MPD/IntroE/IntroE.mpd

yet this one will cause a 404 error 
http://maxmarshall.ddns.net/MPD/FleetE/FleetE.mpd

Thanks for any and all help solving this issue,
I appreciate that I am an amateur trying these things out so chances are the issues I'm coming up against are trivial so thank you for your patience!

**Comment by ojw28** [comment]
You should avoid putting spaces in your URLs / file names. If you get rid of them, or replace them with underscores as in your working example, you may find that it starts working correctly?

**Comment by pestopastarasta** [comment]
I guess you are talking about all of my segments as well as mp4 files, I cant believe I overlooked that, will report back thanks!

**Comment by ojw28** [comment]
Yeah, specifically things like:
http://maxmarshall.ddns.net/MPD/FleetE/seg_The River Fleet_English_FirstRender_641.m4s

You may find it works if you modify the mpd to contain the spaces in encoded form, like:
http://maxmarshall.ddns.net/MPD/FleetE/seg_The%20River%20Fleet_English_FirstRender_641.m4s

But really, you should just not use spaces. It's easier that way :).

**Comment by pestopastarasta** [comment]
Ok great I will definitely have a go at that I really appreciate the help!
