### ISSUE TITLE
Black screen while switching orientation for DRM enabled videos in DASH format

### ISSUE THREAD

**Issue by Taranlayal10** [google/ExoPlayer#7270]
Hi,  @ojw28 

I am writing this as a question in regards to a previously closed bug 6847. Where I have tried the given solution but it did not fix the problem.Since that issue is in locked state so I am unable to add comment on same thread.

**Original Issue**
While switching a video from portrait to landscape mode a blank black screen is visible for a sec before showing the video frame.This happens while switching from landscape to portrait also.This is occurring only for the videos which are DRM protected.This is seen only in few devices.It appears in the exoplayer demo app as well.

**Already Reported Bug**
[issue](https://github.com/google/ExoPlayer/issues/6847).

**ExoPlayer Version**
2.11.1

**Solution tried:**
We have tried forcing L3 Widevine on all devices for the contents but this does not resolve the issue

Can you suggest some alternatives other than this.

**Comment by ojw28** [comment]
I tried forcing L3 in the demo app, and it makes the orientation change look identical to the animation that occurs for non-DRM protected content. I did this by modifying [this piece of code in the demo app](https://github.com/google/ExoPlayer/blob/r2.11.4/demos/main/src/main/java/com/google/android/exoplayer2/demo/PlayerActivity.java#L493) to look like this instead:
```
drmSessionManager =
          new DefaultDrmSessionManager.Builder()
              .setUuidAndExoMediaDrmProvider(drmInfo.drmScheme,
                  uuid -> {
                    try {
                      FrameworkMediaDrm mediaDrm = FrameworkMediaDrm.newInstance(uuid);
                      // Force L3.
                      mediaDrm.setPropertyString("securityLevel", "L3");
                      return mediaDrm;
                    } catch (UnsupportedDrmException e) {
                      return new DummyExoMediaDrm<>();
                    }
                  })
              .setMultiSession(drmInfo.drmMultiSession)
              .build(mediaDrmCallback);
```
I'm not quite certain whether the screen goes black during the animation, but the animation itself looks natural, and is identical to the one that occurs for clear content. This is not the case for L1, for which the screen goes suddenly black for a longer period of time.

I don't think there's anything actionable here. Saying that it doesn't work doesn't give us enough to go on. I think you will need to provide a minimal example as source code if the snippet above doesn't resolve your problem, and if you want us to investigate further.

**Comment by Taranlayal10** [comment]
This resolves the issue. Thanks for your Support :)

**Comment by Taranlayal10** [comment]
Hello @ojw28,

The solution provided by you did worked but this is causing error if I keep the HDCP settings to HDCP – V1 for my Contents.

It is giving error "Required output protections are not active". Please suggest how to play content with HDCP – V1 for L3 settings.

Any Help would be appreciated on this.

**Comment by ojw28** [comment]
Widevine L3 offers a lower level of security than L1. If your license policy requires a higher level of security than it's able to support (e.g., HDCP requirements) then it wont work.

1. It's a fundamental platform limitation that you get a black screen during rotation when using L1. This is because the graphics system that renders the rotation does not have access to the content of the surface.
1. It's a fundamental limitation that Widevine L3 offers a lower level of security protection than L1. If you want to use it, your license policy must not require security features that it does not support.

Those are your options; you need to decide which one you prefer.

**Comment by Taranlayal10** [comment]
Thanks for the prompt response. I will explore the possible options.
