### ISSUE TITLE
Support seeking in fMp4 files

### ISSUE THREAD

**Issue by sridhard** [google/ExoPlayer#7272]
**Tell us where you’ve already looked for an answer to your question. It’s
important for us to know this so that we can improve our documentation.**
I have searched all the exoplayer issues and also the exoplayer docs and stackoverflow questions

**Describe your question in detail.**
We have used Bento4 tools in past and we have encrypted thousands of files using mp4Encrypt with MPEG-CENC. https://www.bento4.com/documentation/mp4encrypt/.  Before encrypting these files were fragmented using mp4fragment of Bento4 tools.

As per my knowledge sidx box is optional in fMp4 files. So mp4Encrypt and mp4Fragment is not adding and sidx boxes in the file. We can play these files successfully with exoplayer but we are not able to seek inside these files.

I have checked #6704 . 

Since the files are downloaded already by users we cannot ask them to download again. Can you please help with below queries:
1. Is there any method to play these files with exoplayer? We dont want to redownload the content. 
2. How difficult is it to generate sidx boxes for the already available fmp4 files? Is there any tool to generate such sidx  files? can you please help me with the method to generate sidx box so that I can generate them in client side and add in fmp4 files.
3. Our previous 3rd party player support playing these fmp4 files. They have a http proxy in mobile which generate HLS content on the fly for these fmp4 files and can do the seeking. Now we are migrating from 3rd party player to exoplayer. I am not sure how they were able to generate HLS from fMp4. Can we do anything similar with exoplayer? 

Please help us with some guidance for playing fMp4 files with exoplayer. Since fMp4 is a standard format and also Bento4 tools is quite popular the  solution/guidance given by exoplayer team will help all these people.

### A full bug report captured from the device
NA

### Link to test content
NA

**Comment by kim-vde** [comment]
1. There is no existing way to seek into an fmp4 file without sidx box in ExoPlayer. The cleaner solution would be to generate files with this box.
2. Is there an option in Bento4 to do that (the [index option](https://www.bento4.com/documentation/mp4fragment/) seems promising)? Have you tried using ffmpeg?
3. As the enhancement already exists (#6704), I will mark this issue as duplicate.
