### ISSUE TITLE
Allow manual quality selection for HLS playbacks

### ISSUE THREAD

**Issue by rok5ek** [google/ExoPlayer#728]
One would be able to set a custom bitrate (dynamically - when playing) depending on what the user sets in its own settings.

**Comment by ojw28** [comment]
In what context is this? HLS / DASH / SmoothStreaming / SomethingElse? It's obviously only possible to stream a bitrate that's provided by the server.

**Comment by rok5ek** [comment]
It should be possible to set a bitrate on a player itself for HLS shouldn't it?

**Comment by ojw28** [comment]
For HLS, it would be possible to allow the user to select from the different qualities that the server makes available, yes. We're working on this currently for SmoothStreaming (done on dev branch) and DASH (will be done on dev branch soon). HLS support will follow later (no immediate ETA).

**Comment by rok5ek** [comment]
Ok superb!

**Comment by ojw28** [comment]
Let's use #676 to track this. Closing this one.
