### ISSUE TITLE
how to pause and resume player when incomeing call or outgoing call activity happens

### ISSUE THREAD

**Issue by literaturesharingforvi** [google/ExoPlayer#7283]
please help me to pause player when incomeing or outgoing call happens and resume playback after finishing them.

what should i do to resolve it.

**Comment by kim-vde** [comment]
Does setting the audio attributes content type to [`CONTENT_TYPE_SPEECH`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/C.html#CONTENT_TYPE_SPEECH) solve your problem (see [`setAudioAttributes()`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/SimpleExoPlayer.html#setAudioAttributes-com.google.android.exoplayer2.audio.AudioAttributes-boolean-) and [`setContentType()`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/audio/AudioAttributes.Builder.html#setContentType-int-))?

**Comment by literaturesharingforvi** [comment]
Can you explain more about that?
How to implement it because I am new to Android

**Comment by kim-vde** [comment]
For unknown content type:
```java
player.setAudioAttributes(AudioAttributes.DEFAULT, /* handleAudioFocus= */ true);
```

For speech content type:
```java
AudioAttributes audioAttributes =
          new AudioAttributes.Builder().setContentType(C.CONTENT_TYPE_SPEECH).build();
player.setAudioAttributes(audioAttributes, /* handleAudioFocus= */ true);
```

You can also set another content type to correspond to the content played by your app.

**Comment by literaturesharingforvi** [comment]
this is my code, what should i impliment


import android.app.PendingIntent;
import android.content.Context;
import android.content.Intent;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.net.Uri;
import android.speech.tts.TextToSpeech;
import android.support.annotation.Nullable;
import android.support.v4.app.NotificationCompat;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.telephony.PhoneStateListener;
import android.telephony.TelephonyManager;
import android.util.Log;
import android.view.KeyEvent;
import android.view.MenuItem;
import android.view.View;
import android.widget.ImageView;
import android.widget.Toast;

import com.google.android.exoplayer2.C;
import com.google.android.exoplayer2.ExoPlaybackException;
import com.google.android.exoplayer2.ExoPlayer;
import com.google.android.exoplayer2.ExoPlayerFactory;
import com.google.android.exoplayer2.PlaybackParameters;
import com.google.android.exoplayer2.Player;
import com.google.android.exoplayer2.SimpleExoPlayer;
import com.google.android.exoplayer2.Timeline;
import com.google.android.exoplayer2.source.ConcatenatingMediaSource;
import com.google.android.exoplayer2.source.ExtractorMediaSource;
import com.google.android.exoplayer2.source.MediaSource;
import com.google.android.exoplayer2.source.TrackGroupArray;
import com.google.android.exoplayer2.trackselection.AdaptiveTrackSelection;
import com.google.android.exoplayer2.trackselection.DefaultTrackSelector;
import com.google.android.exoplayer2.trackselection.TrackSelection;
import com.google.android.exoplayer2.trackselection.TrackSelectionArray;
import com.google.android.exoplayer2.ui.DebugTextViewHelper;
import com.google.android.exoplayer2.ui.PlayerNotificationManager;
import com.google.android.exoplayer2.ui.PlayerView;
import com.google.android.exoplayer2.upstream.BandwidthMeter;
import com.google.android.exoplayer2.upstream.DataSource;
import com.google.android.exoplayer2.upstream.DefaultBandwidthMeter;
import com.google.android.exoplayer2.upstream.DefaultDataSourceFactory;
import com.google.android.exoplayer2.upstream.TransferListener;
import com.google.android.exoplayer2.util.Util;
import com.lsfv.myliteraturesharing.Database.SQliteDatabase;
import com.lsfv.myliteraturesharing.model.ResumeStateModel;

import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Map;

public class VideoPlayerActivity extends AppCompatActivity implements
        TextToSpeech.OnInitListener {

    private static final String KEY_PLAY_WHEN_READY = "play_when_ready";
    private static final String KEY_WINDOW = "window";
    private static final String KEY_POSITION = "position";

    private PlayerView mPlayerView;
    private SimpleExoPlayer player;

    private Timeline.Window window;
    private DataSource.Factory mediaDataSourceFactory;
    private DefaultTrackSelector trackSelector;
    private boolean shouldAutoPlay;
    private BandwidthMeter bandwidthMeter;


    boolean lock_phone=false;
    private ImageView ivHideControllerButton;
    private boolean playWhenReady;
    private int currentWindow;
    private long playbackPosition;

    String playLink, musicName;
    private PlayerNotificationManager playerNotificationManager;
    private ArrayList<String> urlList = new ArrayList<>();
    ArrayList<String> titleList = new ArrayList<>();
    List<MediaSource> playlist = new ArrayList<>();
    SQliteDatabase db;
    private static int audio_counter = 0;
    ComponentListerner componentListerner;
    private static final int PRESS_INTERVAL = 1000;
    private long upKeyTime = 0;

    private int current_track_no;
    private TextToSpeech tts;
    private TelephonyManager mgr;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_video_player);


        Intent intent = getIntent();
        urlList = intent.getStringArrayListExtra("PlayLink");
        titleList = intent.getStringArrayListExtra("MusicName");
        current_track_no = intent.getIntExtra("TrackNumber", 0);
        if (musicName != null && !musicName.isEmpty())
            getSupportActionBar().setTitle(musicName);
        else
            getSupportActionBar().setTitle("Music Player");

        getSupportActionBar().setHomeButtonEnabled(true);
        getSupportActionBar().setDisplayHomeAsUpEnabled(true);

        db=new SQliteDatabase(this);
        tts = new TextToSpeech(this, this);

        Log.d("PlayLink22", "k" + playLink);
        if (savedInstanceState == null) {
            playWhenReady = true;
            currentWindow = 0;
            playbackPosition = 0;
        } else {
            playWhenReady = savedInstanceState.getBoolean(KEY_PLAY_WHEN_READY);
            currentWindow = savedInstanceState.getInt(KEY_WINDOW);
            playbackPosition = savedInstanceState.getLong(KEY_POSITION);
        }

        shouldAutoPlay = true;
        bandwidthMeter = new DefaultBandwidthMeter();
        mediaDataSourceFactory = new DefaultDataSourceFactory(this,
                Util.getUserAgent(this, "mediaPlayerSample"), (TransferListener<? super DataSource>) bandwidthMeter);
        window = new Timeline.Window();
        ivHideControllerButton = (ImageView) findViewById(R.id.exo_controller);


    }


    private void initializePlayer() {

        mPlayerView = (PlayerView) findViewById(R.id.player_view);
        //mPlayerView.showController();


        mPlayerView.requestFocus();

        TrackSelection.Factory videoTrackSelectionFactory =
                new AdaptiveTrackSelection.Factory(bandwidthMeter);

        trackSelector = new DefaultTrackSelector(videoTrackSelectionFactory);

        player = ExoPlayerFactory.newSimpleInstance(this, trackSelector);
        playerNotificationManager = new PlayerNotificationManager(this, "1001", 1, new DescriptionAdapter());
        mPlayerView.setPlayer(player);

        mPlayerView.setControllerAutoShow(false);
        playerNotificationManager.setPlayer(player);
        playerNotificationManager.setFastForwardIncrementMs(15000);
        playerNotificationManager.setRewindIncrementMs(15000);

        if (urlList != null) {
            for (int i = 0; i < urlList.size(); i++) {
                playlist.add(new ExtractorMediaSource.Factory(mediaDataSourceFactory).createMediaSource(Uri.parse(urlList.get(i))));
            }
        }


        ConcatenatingMediaSource concatenatedSource = new ConcatenatingMediaSource(
                playlist.toArray(new MediaSource[playlist.size()]));


        player.setPlayWhenReady(shouldAutoPlay);
/*        MediaSource mediaSource = new HlsMediaSource(Uri.parse("https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8"),
                mediaDataSourceFactory, mainHandler, null);*/

        boolean haveStartPosition = currentWindow != C.INDEX_UNSET;
        /*if (haveStartPosition) {
            player.seekTo(currentWindow, playbackPosition);
        }
        else*/ if(db.getResumeState(urlList.get(current_track_no))!=-1)
            player.seekTo(current_track_no, db.getResumeState(urlList.get(current_track_no)));
        else
            player.seekTo(current_track_no, C.TIME_UNSET);
        //player.prepare(mediaSource, !haveStartPosition, false);
        player.prepare(concatenatedSource, !haveStartPosition, false);

        mPlayerView.setControllerAutoShow(false);
        mPlayerView.setUseController(true);
        mPlayerView.setControllerHideOnTouch(false);
        mPlayerView.showController();
        mPlayerView.setControllerShowTimeoutMs(3600000);
        componentListerner = new ComponentListerner();
        player.addListener(componentListerner);
        ivHideControllerButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                mPlayerView.hideController();
            }
        });
    }

    private void releasePlayer() {
        if (player != null) {
            updateStartPosition();
            shouldAutoPlay = player.getPlayWhenReady();
            player.removeListener(componentListerner);
            playerNotificationManager.setPlayer(null);
            player.release();
            player = null;
            trackSelector = null;
        }
    }

    @Override
    public void onStart() {
        super.onStart();
        /*if (Util.SDK_INT > 23) {
            initializePlayer();
        }*/
    }

    @Override
    public void onResume() {
        super.onResume();

        mgr = (TelephonyManager) getSystemService(TELEPHONY_SERVICE);
        if(mgr != null) {
            mgr.listen(phoneStateListener, PhoneStateListener.LISTEN_CALL_STATE);
        }
        /*if ((Util.SDK_INT <= 23 || player == null)) {
            initializePlayer();
        }*/
    }

    @Override
    public void onPause() {
        super.onPause();

        if(mgr != null) {
            mgr.listen(phoneStateListener, PhoneStateListener.LISTEN_NONE);
        }
        lock_phone=true;
        /*if (Util.SDK_INT <= 23) {
            releasePlayer();
        }*/
    }

    @Override
    public void onStop() {
        super.onStop();
        if (Util.SDK_INT > 23) {
            //releasePlayer();
        }
        lock_phone=true;
    }

    @Override
    protected void onSaveInstanceState(Bundle outState) {
        updateStartPosition();

        outState.putBoolean(KEY_PLAY_WHEN_READY, playWhenReady);
        outState.putInt(KEY_WINDOW, currentWindow);
        outState.putLong(KEY_POSITION, playbackPosition);
        super.onSaveInstanceState(outState);
    }

    private void updateStartPosition() {
        if (player != null) {

            playbackPosition = player.getCurrentPosition();
            currentWindow = player.getCurrentWindowIndex();
            playWhenReady = player.getPlayWhenReady();
            db.addResumeState(new ResumeStateModel(playbackPosition,urlList.get(currentWindow)));
            current_track_no=currentWindow;
        }
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        switch (item.getItemId()) {
            case android.R.id.home:
                onBackPressed();
                return true;
            default:
                return super.onOptionsItemSelected(item);
        }

    }


    public String getMusicTitle(int pos) {
        return titleList.get(pos);
    }

    public void forwardMusic() {
        //Toast.makeText(this, ""+player.getDuration(), Toast.LENGTH_SHORT).show();
        long forward_duration=player.getContentPosition()+15000;

        if(forward_duration<player.getDuration())
            player.seekTo(player.getCurrentPosition()+15000);
        else if(player.getDuration()<forward_duration)
            player.seekTo(player.getDuration());

    }

    public void rewindMusic() {
        if(player.getCurrentPosition()>15000)
        player.seekTo(player.getCurrentPosition()-15000);
        else if(player.getCurrentPosition()>0 && player.getCurrentPosition()<15000)
            player.seekTo(0);

    }

    public Bitmap getAppIcon() {
        return BitmapFactory.decodeResource(getResources(), R.drawable.ic_launcher_round_logo);
    }

    @Override
    public void onInit(int status) {
        if (status == TextToSpeech.SUCCESS) {

            int result = tts.setLanguage(Locale.US);

            // tts.setPitch(5); // set pitch level

            // tts.setSpeechRate(2); // set speech speed rate

            if (result == TextToSpeech.LANG_MISSING_DATA
                    || result == TextToSpeech.LANG_NOT_SUPPORTED) {
                Log.e("TTS", "Language is not supported");
            } else {
                //Toast.makeText(this, "enabled", Toast.LENGTH_SHORT).show();
                //speakOut("Enabled");
            }

        } else {
            Log.e("TTS", "Initilization Failed");
        }
    }

    private void speakOut(String text) {


        tts.speak(text, TextToSpeech.QUEUE_FLUSH, null);
    }

    private class DescriptionAdapter implements PlayerNotificationManager.MediaDescriptionAdapter {
        @Override
        public String getCurrentContentTitle(Player player) {
            return getMusicTitle(player.getCurrentWindowIndex());
        }

        @Nullable
        @Override
        public PendingIntent createCurrentContentIntent(Player player) {
            return null;
        }

        @Nullable
        @Override
        public String getCurrentContentText(Player player) {
            return null;
        }

        @Nullable
        @Override
        public Bitmap getCurrentLargeIcon(Player player, PlayerNotificationManager.BitmapCallback callback) {

            return getAppIcon();
        }
    }

    private class ActionReceiver implements PlayerNotificationManager.CustomActionReceiver {

        @Override
        public Map<String, NotificationCompat.Action> createCustomActions(Context context) {
            return null;
        }

        @Override
        public List<String> getCustomActions(Player player) {
            return null;
        }

        @Override
        public void onCustomAction(Player player, String action, Intent intent) {

        }
    }

    public class ComponentListerner implements Player.EventListener {

        @Override
        public void onTimelineChanged(Timeline timeline, Object manifest, int reason) {

        }

        @Override
        public void onTracksChanged(TrackGroupArray trackGroups, TrackSelectionArray trackSelections) {
            /*getSupportActionBar().setTitle(titleList.get(audio_counter));
            audio_counter++;*/
            Log.d("Track444", "" + player.getCurrentWindowIndex());

            getSupportActionBar().setTitle(getMusicTitle(player.getCurrentWindowIndex()));


        }

        @Override
        public void onLoadingChanged(boolean isLoading) {

        }

        @Override
        public void onPlayerStateChanged(boolean playWhenReady, int playbackState) {

        }

        @Override
        public void onRepeatModeChanged(int repeatMode) {

        }

        @Override
        public void onShuffleModeEnabledChanged(boolean shuffleModeEnabled) {

        }

        @Override
        public void onPlayerError(ExoPlaybackException error) {

        }



        @Override
        public void onPositionDiscontinuity(int reason) {

        }

        @Override
        public void onPlaybackParametersChanged(PlaybackParameters playbackParameters) {


        }

        @Override
        public void onSeekProcessed() {

        }
    }

    @Override
    public void onBackPressed() {
        super.onBackPressed();
        releasePlayer();
    }

    /*    @Override
        public boolean onKeyDown(int keyCode, KeyEvent event) {
            if (KeyEvent.KEYCODE_VOLUME_DOWN == event.getKeyCode()) {
                //Toast.makeText(this, "Volume down" + priviousMusic(), Toast.LENGTH_SHORT).show();
                Log.d("PlayerTrack", "" + player.getPreviousWindowIndex());
                //player.seekTo(player.getCurrentPosition()-15000);
                //Toast.makeText(this, "Volume up" + player.getCurrentPosition(), Toast.LENGTH_SHORT).show();
               rewindMusic();
                return true;
            } else if (keyCode == KeyEvent.KEYCODE_VOLUME_UP) {
                //Toast.makeText(this, "Volume up" + nextMusic(), Toast.LENGTH_SHORT).show();
                forwardMusic();
                return true;
            }
            return super.onKeyDown(keyCode, event);
        }*/
    /*@Override
    public boolean onKeyUp(int keyCode, KeyEvent event) {
        if (KeyEvent.KEYCODE_VOLUME_UP == keyCode) {
            upKeyTime = event.getEventTime();
        }
        return super.onKeyUp(keyCode, event);
    }*/
PhoneStateListener phoneStateListener=new PhoneStateListener(){
    @Override
    public void onCallStateChanged(int state, String incomingNumber) {
        if (state == TelephonyManager.CALL_STATE_RINGING) {
            //Incoming call: Pause music
            Log.d("Call222","ringing");
            if (Util.SDK_INT <= 23) {
                lock_phone=false;
                releasePlayer();
            }
            else {
                releasePlayer();
                lock_phone=false;
            }

        } else if(state == TelephonyManager.CALL_STATE_IDLE) {
            //initializePlayer();
            //Not in call: Play music
            if ((Util.SDK_INT <= 23 || player == null)) {
                //music_state=true;
                if(!lock_phone)
                initializePlayer();
            }
            Log.d("Call222","play music");
        } else if(state == TelephonyManager.CALL_STATE_OFFHOOK) {
            //releasePlayer();
            //A call is dialing, active or on hold
            Log.d("Call222","offhook");
        }
        super.onCallStateChanged(state, incomingNumber);

    }
};
}

**Comment by kim-vde** [comment]
You should do that in `initializePlayer()`.

**Comment by literaturesharingforvi** [comment]
Ok thanks
