### ISSUE TITLE
How to make a thumbnail of a local video?

### ISSUE THREAD

**Issue by silvershort** [google/ExoPlayer#7285]
https://i.stack.imgur.com/pC4rn.jpg

I am trying to implement a seekbar using a thumbnail like the link above.

To implement the function, need to import thumbnail of the video.

How to extract thumbnail images from local video?

**Comment by kim-vde** [comment]
This is currently not possible with ExoPlayer. We already have an enhancement for providing a metadata extraction API (#3609).

**Comment by kim-vde** [comment]
Duplicate of #3609.

**Comment by silvershort** [comment]
> Duplicate of #3609.

thank you
