### ISSUE TITLE
Cannot play mp3 file from local storage

### ISSUE THREAD

**Issue by linhttbk** [google/ExoPlayer#7290]
I have local mp3 file with uri path: content://mypackagename.provider/external_files/Android/data/co.unstatic.summerian/files/Download/MyApp/mp3folder/WuV4ncJXVD2Ck1u77lP8.mp3 
When i used virtutal devices such as Pixel 2 ( Android 10.0) it's worked properly. But when I run on my devices ( Xiaomi Redmi 5 Plus Android 8.1  or Xiaomi redmi go Android 8.1) I got this error. 
com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor, AmrExtractor, Ac4Extractor) could read the stream.
How can I fix this
I am using version 2.10.2 and following [uamp ](https://github.com/android/uamp) example 
you can download my mp3 file [here](https://www.mboxdrive.com/WuV4ncJXVD2Ck1u77lP8.mp3):
Thank for your help!

**Comment by christosts** [comment]
I tested the attached mp3 file and it works fine with the ExoPlayer demo app on a few devices I have handy (Pixel 2, One Plus 3T, Samsung S9), but they all have a newer Android version than 8.

Can you please test your file with the ExoPlayer demo app to see if that works? That would at least verify that vanilla ExoPlayer can play the file on the specific Xiaomi devices.

Note, I loaded the file directly from the device's storage using a filesystem uri (`file:///...`).

**Comment by linhttbk** [comment]
I just checked my local file, it seem lack some information. I also tested other local file and it works fine. So i would closed this issue. Thank for your help!
