### ISSUE TITLE
Test HDCP with ExoPlayer issue "WVCdm   : Decrypt error result in session sid28 during encrypted block: 179"

### ISSUE THREAD

**Issue by ThunderSoft123** [google/ExoPlayer#7293]
System version: Android 10
Chipset: SDM-450
Sink: WFD-dongle (HDCP 1.x).
The "HDCP: 1.0 required" can display DRM video in WFD-dongle, but the "HDCP: 2.0 required", "HDCP: 2.1 required" and "HDCP: 2.2 required" don't display DRM video in WFD-dongle.

**Comment by ThunderSoft123** [comment]
However, the Sony phone Xperia can display DRM video in WFD-dongle with "HDCP: 1.0 required", "HDCP: 2.0 required", "HDCP: 2.1 required".

**Comment by christosts** [comment]
Looks like the issue is coming from the device you are playing content and not from ExoPlayer, especially since you mention on the comment above that a Sony  Xperia can display the video (I assume you are using the same HDCP dongle).

I don't think we provide more information on this.
