### ISSUE TITLE
ExoPlayerView swiping  in Vertical ViewPager

### ISSUE THREAD

**Issue by naintrakusam** [google/ExoPlayer#7299]
Hi, I am implementing custom vertical viewpager with PlayerView on each page. 
It works very well until I start swiping. During swiping the PlayerView's content disappears until I finish swiping. Then video is again displayed. I can still hear the sounds from video, so issue is just displaying it during swiping.

Please note I dont have this issue with default native horizontal viewpager.

Please see attached VerticalViewPager code and GIF which help you to understand it better.

[VerticalViewPager.txt](https://github.com/google/ExoPlayer/files/4540957/VerticalViewPager.txt)

I would like to ask if you are aware of any issue like this and how can it be solved.

Thank you in advance

**UPDATE:** I found this on native VideoView : **setZOrderOnTop(true)** 
Actually it **partly** solved my issue but I would like to use ExoPlayer if possible

**UPDATE 2 :** Found again smth. better and it is **TextureVideoView**. It is extended VideoView, using a **TextureView** instead of a **SurfaceView** and works just fine. But still I like more ExoPlayer if this issue can be solved. Hopefully it will be hmmm ?

**UPDATE 3:** Guys, I have found 100% solution. You just need to get rid of custom ViewPager.
All you need to do is implement **ViewPager2** which is part of **androidx** and just set 👍 **android:orientation="vertical"**

![gif-video](https://user-images.githubusercontent.com/3417582/80398323-b7aa3780-88b7-11ea-8484-f598a8187ec9.gif)

**Comment by naintrakusam** [comment]
Guys, I have found 100% solution. You just need to get rid of custom ViewPager.
All you need to do is implement ViewPager2 which is part of androidx and just set 👍 android:orientation="vertical"

**Comment by christosts** [comment]
closing as it seems issue is solved!
