### ISSUE TITLE
HLS seek stops the playback

### ISSUE THREAD

**Issue by acq** [google/ExoPlayer#730]
Hi,

I'm currently trying to replace VideoPlayer by ExoPlayer in our app, which displays VoD and live content, via HLS streams.
The code for the integration of ExoPlayer is mostly the one provided in the sample.

Most of it works great, except for one problem : most of the time, when I try to seek forward or backwards via the MediaController, the seek bar is updated properly but the stream stops playing. Pressing pause/play does not restart it.

I added all the listeners I could and here is a sample of the kind of logs I get after asking for a seek forward :

```
E/OMXMaster﹕ A component of name 'OMX.qcom.audio.decoder.aac' already exists, ignoring this one.
E/VideoPlayer﹕ video format enabled : com.google.android.exoplayer.chunk.Format@33 (0,10000)
E/VideoPlayer﹕ dropped frames : 4 frames for 11852ms
E/VideoPlayer﹕ load started : sourceId:0, length:-1, type:1, trigger:0, format:com.google.android.exoplayer.chunk.Format@33, mediaStartTime:20000ms, mediaEndTime:30000ms
E/VideoPlayer﹕ state changed : STATE_BUFFERING
E/VideoPlayer﹕ load completed : sourceId:0, bytesLoaded:0, type:1, trigger:0, format:com.google.android.exoplayer.chunk.Format@33, mediaStartTime:20000ms, mediaEndTime:30000ms, elapsedRealtimeMs:168147287ms, loadDurationMs:25ms
E/VideoPlayer﹕ load started : sourceId:0, length:-1, type:1, trigger:0, format:com.google.android.exoplayer.chunk.Format@33, mediaStartTime:30000ms, mediaEndTime:40000ms
E/VideoPlayer﹕ load completed : sourceId:0, bytesLoaded:0, type:1, trigger:0, format:com.google.android.exoplayer.chunk.Format@33, mediaStartTime:30000ms, mediaEndTime:40000ms, elapsedRealtimeMs:168147299ms, loadDurationMs:12ms
E/VideoPlayer﹕ load started : sourceId:0, length:-1, type:1, trigger:0, format:com.google.android.exoplayer.chunk.Format@33, mediaStartTime:40000ms, mediaEndTime:50000ms
E/VideoPlayer﹕ load completed : sourceId:0, bytesLoaded:0, type:1, trigger:0, format:com.google.android.exoplayer.chunk.Format@33, mediaStartTime:40000ms, mediaEndTime:50000ms, elapsedRealtimeMs:168147311ms, loadDurationMs:12ms
E/VideoPlayer﹕ load started : sourceId:0, length:-1, type:1, trigger:0, format:com.google.android.exoplayer.chunk.Format@33, mediaStartTime:50000ms, mediaEndTime:60000ms
E/VideoPlayer﹕ load completed : sourceId:0, bytesLoaded:0, type:1, trigger:0, format:com.google.android.exoplayer.chunk.Format@33, mediaStartTime:50000ms, mediaEndTime:60000ms, elapsedRealtimeMs:168147323ms, loadDurationMs:12ms
E/VideoPlayer﹕ load started : sourceId:0, length:-1, type:1, trigger:0, format:com.google.android.exoplayer.chunk.Format@33, mediaStartTime:60000ms, mediaEndTime:64200ms
E/VideoPlayer﹕ load completed : sourceId:0, bytesLoaded:0, type:1, trigger:0, format:com.google.android.exoplayer.chunk.Format@33, mediaStartTime:60000ms, mediaEndTime:64200ms, elapsedRealtimeMs:168147338ms, loadDurationMs:15ms
E/VideoPlayer﹕ state changed : STATE_READY
```

I'm not sure whether this problem is coming from ExoPlayer or a bad setup : do you know what could be the cause for such a problem ?

Thanks

**Comment by ojw28** [comment]
- What version of ExoPlayer are you using.
- Does the issue reproduce with the test streams in the ExoPlayer demo app?

**Comment by acq** [comment]
Thanks for your quick response

I'm using the 1.4.2 version of ExoPlayer

I just tested with the HLS test streams : the playback freezes for a few seconds but then resumes normally.

**Comment by ojw28** [comment]
If the issue doesn't reproduce with the test streams, you'll need to provide a stream that we can reproduce the issue with for us to look into it. Thanks.

**Comment by acq** [comment]
Unfortunately, I am not the owner of the stream and cannot provide it to you.

I tested it in the demo application, and it seems to be working flawlessly.
So I will try to see where I diverged from the demo to create this bug.
If I find the answer, I will post it here.

Thank you for your time
