### ISSUE TITLE
ExoPlayer sometimes returns negative duration for an mp3 file from url

### ISSUE THREAD

**Issue by josequintana94** [google/ExoPlayer#7314]
### [REQUIRED] Issue description
I'm making an app where I play .mp3 files from the URL. I'm using the latest version of ExoPlayer 2.11.4.

What I need to do is get the total duration of the audio from the url so I can use it in my custom audio player.

The urls I'm using are of this type: https://prepublish.f.qaotic.net/media/vod/legacy-audio/c5c3478127f5e50e49b50a3846afe884-1588170579-56e4bd3f359025fba2d2e080cb2c25a9.mp3?lsdpass=6oc-32-1as-2ul-4a-5aoj

The problem is that sometimes my code works correctly most of the time and returns the correct duration. But sometimes what I get is a negative number: -9223372036854775807

And that doesn't allow my code to work properly. My code where I get the duration is this:
```
fun getDuration(url: String, context: Context) {
        exoPlayer?.release()

        exoPlayer = SimpleExoPlayer.Builder(context).build()
        val dataSourceFactory = DefaultDataSourceFactory(context, Util.getUserAgent(context, "ExoPlayer"))
        val mediaSource = ProgressiveMediaSource.Factory(dataSourceFactory).createMediaSource(Uri.parse(url))

        exoPlayer?.prepare(mediaSource)

        exoPlayer?.addListener(object : Player.EventListener {
            override fun onPlayerStateChanged(playWhenReady: Boolean, playbackState: Int) {
                if (playbackState == ExoPlayer.STATE_READY) {
                    val realDurationMillis: Long? = exoPlayer?.getDuration()
                    currentDuration = realDurationMillis
                    if (currentDuration != null) {
                        if (currentDuration!! > 0) {
                            exoPlayer?.release()
                        }
                    }

                }
            }
        })
    }
```

### [REQUIRED] Version of ExoPlayer being used
2.11.4

### [REQUIRED] Device(s) and version(s) of Android being used
This happens in every physical and virtual device I've tried

**Comment by christosts** [comment]
Can you try to attach the listener before calling player.prepare() and let me know if it worked?

-- **update** --
I think you may be hitting a bug that we have fixed in the dev-v2 branch.
1. Can you try with your code on dev-v2 to verify it works?
2. How to fix this in v2.11.4:
- can you try to add the listener before calling player.prepare()
- can you switch to listening to the `onTimeLineChanged(TimeLine, reason)` event, with reason TIMELINE_CHANGE_REASON_DYNAMIC

**Comment by DevinDuricka** [comment]
I also have run into this issue. I haven't tried the dev-v2 branch yet, but for me it occurs when I add a `ClippingMediaSource` which has some start position within the file, and the end position is `C.TIME_END_OF_SOURCE`. 

Windows/Periods with these criteria almost always had a large negative duration.

**Comment by andrewlewis** [comment]
@DevinDuricka If you can reproduce the issue when using `dev-v2` it would be helpful if you could file a new issue and include steps to reproduce the problem. Thank you!
