### ISSUE TITLE
Multiple Video rendered when select lower resolution video track 

### ISSUE THREAD

**Issue by zgzong** [google/ExoPlayer#7318]
### [REQUIRED] Issue description
When play a DASH stream, select lower resolution video track caused new resolution rendered on top of previous rendered frames. Attached a screen shot to show the issue on some devices.
![Screenshot_20200501_133615_com google android exoplayer2 demo](https://user-images.githubusercontent.com/2271258/80808523-a1ea8a00-8bb7-11ea-922b-0102c593d3a2.jpg)

### [REQUIRED] Reproduction steps
1. Use latest main build exo demo application to play a stream https://d3bqrzf9w11pn3.cloudfront.net/basic_dash_bbb_clear/bbb_public.mpd
2. Select video track that is lower resolution, when playback start. 

### [REQUIRED] A full bug report captured from the device
Captured log attached below.
[p20.txt](https://github.com/google/ExoPlayer/files/4564429/p20.txt)

### [REQUIRED] Version of ExoPlayer being used
Latest.

### [REQUIRED] Device(s) and version(s) of Android being used
I only have limited devices in hand, but this can be reproduced on HuaWei P20, P20 Lite, Dell Venue 8 7000 tablet.

**Comment by christosts** [comment]
I cannot reproduce the exact issue but I see garbled video when performing seeking on a couple tested devices (Pixel 2 and OnePlus 3T). Have you noticed anything with seeking on your devices?

I repro'd issue with seeking with other players too, and also saw some sudden aspect ratio changes in the beginning of playback when playing with vlc on a MacBook, so I think there is something related with the asset's encoding/packaging.

**Comment by zgzong** [comment]
@christosts 
This issue I reproducible on my huawei p20 lite, I can't reproduce it on my pixel 3a.
The issue is happened when it switch bitrate from high to low.
