### ISSUE TITLE
Recycling exoplayer instances

### ISSUE THREAD

**Issue by AshtonEngberg** [google/ExoPlayer#732]
I was wondering if as part of the new sample, code for showing how to reuse an exoplayer instance could be included. Currently I have a view pager, wherein each page has an 70% of having a video of type HLS or mp4: currently I just create a new instance of the exoplayer with the proper format loaders, but for optimization (and I've optimized almost everything else) I'd like to reuse one instance of both the HLS and Mp4 types. So to reiterate, could the new sample app (or if anyone has some code they could share), show how a) to properly initialize (ie, what if no audio track, I've seen its good to just use IGNORE track for audio in this case as opposed to just not adding it); b) properly release; c) properly recycle an instance of an exoplayer (if possible). 

In any case, thanks for all the work!

**Comment by ojw28** [comment]
This is outside the scope of this tracker, which is focused directly on library issues / enhancements. We're not planning on adding any more complexity to our demo app in the near future; we're actually trying to make it simpler. If you need help with application development, I'd suggest asking on StackOverflow. Thanks!
