### ISSUE TITLE
Stream with Invalid PMTs?

### ISSUE THREAD

**Issue by skogl** [google/ExoPlayer#7325]
### [REQUIRED] Issue description
Mpeg-ts stream coming from DVB-S broadcast contain PMTs that contain invalid "program_info_length" that cannot be handled by Exoplayer.

This issue also had issues with "program_info_length": https://github.com/google/ExoPlayer/issues/1068

It also mentined a workaround that also works in my case:
```
if (programInfoLength > sectionData.bytesLeft()) {
  Log.w(TAG, "Invalid programInfoLength: " + programInfoLength);
  return;
}
```

Comments for the above issue states that errors in streams should not be handled with workarounds in Exoplayer which I totally buy, but in this case the stream comes from a network broadcast company in europe that obviously uses this technique for some reason which makes me unsure of how to handle the situation.

If this is a "won't fix" please give me some guidelines of how to proceed. To I need to maintain this workaround in a fork or is there a better solution?

### [REQUIRED] Reproduction steps
Play linked stream with Exoplayer 2.11.4 so see the error.

### [REQUIRED] Link to test content
[stream.ts](https://drive.google.com/file/d/1cWDZwfzu7VqSBqejIpwyKMBVW589P67b/view?usp=sharing)

### [REQUIRED] A full bug report captured from the device
```2020-05-04 12:16:38.068 20906-20906/com.google.android.exoplayer2.demo E/EventLogger: internalError [eventTime=5.28, mediaPos=0.00, window=0, period=0, loadError
      com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected IllegalArgumentException: null
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:413)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.IllegalArgumentException
        at com.google.android.exoplayer2.util.Assertions.checkArgument(Assertions.java:39)
        at com.google.android.exoplayer2.util.ParsableByteArray.setPosition(ParsableByteArray.java:155)
        at com.google.android.exoplayer2.util.ParsableByteArray.skipBytes(ParsableByteArray.java:167)
        at com.google.android.exoplayer2.extractor.ts.TsExtractor$PmtReader.consume(TsExtractor.java:562)
        at com.google.android.exoplayer2.extractor.ts.SectionReader.consume(SectionReader.java:127)
        at com.google.android.exoplayer2.extractor.ts.TsExtractor.read(TsExtractor.java:338)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:982)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:391)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
    ]
```

### [REQUIRED] Version of ExoPlayer being used
2.11.4

### [REQUIRED] Device(s) and version(s) of Android being used
Only tested on emulator.

**Comment by skogl** [comment]
Have you been able to reproduce this issue or do you need more info?

**Comment by skogl** [comment]
Just want to know if you have acknowledged this issue or if I should add more info? It's been two weeks.

**Comment by AquilesCanta** [comment]
Hi, surprisingly the CRC seems correct. So I don't understand how the muxer is generating this. I'm trying to gain some insight on the root of the problem. I wouldn't like to blindly add a workaround for this without having a sensible justification.

If you happen to come across a reasonable explanation we can look into working around this. However, you can always try to working around this in a fork. In my case adding

```
      if (programInfoLength > sectionData.bytesLeft()) {
        return;
      }
```

right after [reading `programInfoLength`](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/extractor/ts/TsExtractor.java#L555) allows media to prepare, although it fails immediately afterwards with a MediaCodecVideoRenderer exception which may be unrelated.

Had you tried this workaround before reporting the issue? If so, I assume you didn't run into the MediaCodec exception.

**Comment by skogl** [comment]
Hi,
I agree completely and that's why I wanted your opinion before I just added the workaround.

Yes I have tried the workaround (it's included in my first post) and for me it's working really well. I don't get the MediaCodecVideoRenderer exception that you say, though I have only tested it in an emulator.

Not sure what info you want from me. I don't have a reasonable explanation, that's why I ask you. The workaround works, but I don't want to use it if the media is bad and I don't have enough knowledge to determine if it's bad or not.

**Comment by skogl** [comment]
Any news on this one?

**Comment by AquilesCanta** [comment]
I haven't had time to do more research on this. I did some digging around and it would seem that dvbsnoop never reads the invalid program info length, which suggests there's something wrong with the exoplayer parsing code. Which provides evidence against adding the program info length workaround to exoplayer. I think the next step is to define this is whether this is bad media or a bug in the exoplayer parsing code. But I haven't had the time to do the research yet. Any input is welcome.

**Comment by skogl** [comment]
Ok, so I believe I have found an issue with the parser. I have not reviewed the entire parser but stopped when I found the first (and only?) issue.

In _ISO/IEC 13818-1_ in section _2.4.4.9_ it's clearly stated that a program map table section's _section_syntax_indicator_ bit should be set to '1', this was not checked in Exoplayer.

So, I've inserted the below code on row 527:

```
      int secondHeaderByte = sectionData.readUnsignedByte();
      if((secondHeaderByte & 0x80) == 0) {
        // See ISO/IEC 13818-1, section 2.4.4.9 for more information on transport stream program map section.
        return;
      }
```

And also updated row 539 to skip only one byte like this:
```
      sectionData.skipBytes(1)
```
Using the attached stream I enter the condition once (and return) before entering a second time where correct program_info_length is now used.

What do you think? Does this look like a viable solution? I have tested it with a number of previously working and non-working streams that now all work.

**Comment by AquilesCanta** [comment]
Yes, looks good to me. 

Are you ok with me introducing an equivalent change internally or would you prefer sending a pull request?

**Comment by skogl** [comment]
You can go ahead and change it, most important is that it's getting fixed.

**Comment by AquilesCanta** [comment]
Cool, thanks for the research!

**Comment by skogl** [comment]
No problem!
