### ISSUE TITLE
Request: Multiple Loaders Support

### ISSUE THREAD

**Issue by krok55** [google/ExoPlayer#733]
Hi,

Is it possible to allow several loaders to work simultaneously in order to improve the user experience?
Some servers don't consume the bandwidth entirely and by forking the loader thread it could potentially maximize the quality for the given user connection.
The HLS is a perfect candidate for that, since the m3u8 format usually contains several *.ts files that each can be downloaded in parallel by a different loader.

Do you think it's possible?

Thanks.

**Comment by ojw28** [comment]
See https://github.com/google/ExoPlayer/issues/565 for reasons why we opted not to do this.
