### ISSUE TITLE
Videos Live stream is playing only Audio but not video(Black Screen).

### ISSUE THREAD

**Issue by gautamlook** [google/ExoPlayer#7331]
I am using current Exoplayer. all VOD and live stream is working fine. but I have live streaming feed which is not working in exoplayer(Only play audio and not showing videos).

Feed Url : https://live.field59.com/wdrb/ngrp:wdrb2_all/playlist.m3u8

I saw some link regarding this issue but not reached any valuable point. so, please help me if you have any idea regarding this feed.

Note: This feed is working and playing on VLC player ,online player and other platform like iOS and ROKU.

**Comment by Samrobbo** [comment]
I've tried this on the demo application, and both audio and video are working as expected. Try looking over the demo application code and comparing to your own application code, and check that you are not missing something.
