### ISSUE TITLE
couldn't find a codec If only tunneled codecs are available

### ISSUE THREAD

**Issue by sunrise0406-bc** [google/ExoPlayer#7335]
According to the guidance from https://source.android.com/devices/tv/multimedia-tunneling, 
I add 'required=true' to all MediaCode columns in media_codecs.xml,
  <Feature name="tunneled-playback" required="true"/>
BUT my platform pops up a msg- 'XXXX non are playable by this device' while playing a video file, so I traced out the source code of Exoplayer 2.11.2 and found out that Exoplayer seeks for non-tunneled codec only.
In ExoPlayer-r2.11.2/library/core/src/main/java/com/google/android/exoplayer2/video/MediaCodecVideoRenderer.java
  protected int supportsFormat(
      MediaCodecSelector mediaCodecSelector,
      @Nullable DrmSessionManager<FrameworkMediaCrypto> drmSessionManager,
      Format format)
      throws DecoderQueryException {
    String mimeType = format.sampleMimeType;
    if (!MimeTypes.isVideo(mimeType)) {
      return RendererCapabilities.create(FORMAT_UNSUPPORTED_TYPE);
    }    
    @Nullable DrmInitData drmInitData = format.drmInitData;
    // Assume encrypted content requires secure decoders.
    boolean requiresSecureDecryption = drmInitData != null;
    List<MediaCodecInfo> decoderInfos =
        getDecoderInfos(
            mediaCodecSelector,
            format,
            requiresSecureDecryption,
            /* requiresTunnelingDecoder= */ false);
    if (requiresSecureDecryption && decoderInfos.isEmpty()) {
      // No secure decoders are available. Fall back to non-secure decoders.
      decoderInfos =
          getDecoderInfos(
              mediaCodecSelector,
              format,
              /* requiresSecureDecoder= */ false,
              /* requiresTunnelingDecoder= */ false);
    }    
    if (decoderInfos.isEmpty()) {
      return RendererCapabilities.create(FORMAT_UNSUPPORTED_SUBTYPE);   //return here
    }

**Comment by andrewlewis** [comment]
`MediaCodecVideoRenderer.supportsFormat` currently expects there to be a non-tunneled codec for the same format present. Later on in the method (after that code snippet) it checks whether there is a tunneled decoder for the format. Can you list the codec twice, once without the tunneling feature and once with it?

**Comment by sunrise0406-bc** [comment]
@andrewlewis 
Okey, I'll give it a try and reply my result to you.
Thank you very much.

**Comment by sunrise0406-bc** [comment]
We list the codec twice, add another codec name without a suffix-'tunneled'
