### ISSUE TITLE
flac extension audio file play discontinuous, play a while and switch to next audio

### ISSUE THREAD

**Issue by ZhangHui0608** [google/ExoPlayer#7336]
### [REQUIRED] Question
build flac extension and Integrate flac libray in my app,
flac extension audio file play discontinuous, play a while and switch to next audio

**Comment by ZhangHui0608** [comment]
log link: https://pan.baidu.com/s/14OvWHZo24fBbusRpXFXPKA 
download code: sm36

**Comment by Samrobbo** [comment]
Hi, 

Can I just get some clarification? Do you have a problem with using the flac extension, or are you asking how to use it?

Thanks

**Comment by ZhangHui0608** [comment]
I add flac module as my library module,  build libflacJNI.so and add it jniLibs in flac module.  when playing flac format audio file, there has problem.

**Comment by kim-vde** [comment]
Please provide a link to the FLAC file that produces the issue. If you're unable to share bug reports or test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Please also update this issue to indicate you’ve done this.
