### ISSUE TITLE
MP3 XingSeeker with big audio size (~2 GB)

### ISSUE THREAD

**Issue by simonvar** [google/ExoPlayer#7337]
### Issue description
If try play mp3 with size ~2 GB, player throws exception -
`java.lang.IllegalStateException: Top bit not zero: -2121515177`.
It's happens in ` XingSeeker.create(...)`.
In this line `long dataSize = frame.readUnsignedIntToInt();`.
It's becuse readUnsignedIntToInt can return int in interval 0 .. 2,147,483,647, but size can be actual long. In my case 2,173,452,181 bytes.

### Reproduction steps
1. Play audio with size more than 2,147,483,647 bytes size.

### Link to test content
You can use any mp3 file with size more than 2,147,483,647 bytes.
I sent on email my test case.

### A full bug report captured from the device
I sent on email.

### Version of ExoPlayer being used
2.11.4

### Device(s) and version(s) of Android being used
Samsung SM-A505FN with Android 10.

**Comment by ojw28** [comment]
@Samrobbo - It would be good to get a fix in for this. It's probably just a case of using `readUnsignedInt` instead of `readUnsignedIntToInt` when reading `dataSize`.

**Comment by Samrobbo** [comment]
@ojw28 @simonvar I'll look into this now. Thanks for the hint.
