### ISSUE TITLE
the video getting skewed.

### ISSUE THREAD

**Issue by shaheercs** [google/ExoPlayer#7345]
Hi,

I am working on a project like TikTok. user can swipe up/down to see the next full-screen video.
Users can see the ingredients Tab and user profiles Tab against the video by swipe left and right.  
**(please find the attached video)**

[issue.mov.zip](https://github.com/google/ExoPlayer/files/4592448/issue.mov.zip)

here I am using viewPager2 with FragmentStateAdapter and I am using the Exo Player instance for each Fragment item in viewPager.

**configuration** 
onResume- initializing the player, prepare and once ready will play.
onPause- pause the video
onDestroyView-releasing the player
so the viewPager2 will only keep 3 fragment item, as I am keeping maximum two-player instances
 
**issue**
I am facing issue like if I swipe left or right will get ingredients tab and user tab. till now everything is correct. if we go back to the playback tab the video getting skewed and rotated even the app only supports portrait mode.

please advise me if you find any mistake.

Thanks & Regards

**Comment by krocard** [comment]
I don't think we can help you without more information like a your player configuration and layout and a logcat to check if anything interesting is happening when the issue occurs.
