### ISSUE TITLE
mediacodec flower screen and blue screen on some phones with poor performance

### ISSUE THREAD

**Issue by kuailedeadai** [google/ExoPlayer#7346]
Hello, please ask at high bit rate and high quality, using mediacodec decoding, there are flower screen and blue screen problems on mobile phones with poor performance, what is the solution?

**Comment by krocard** [comment]
Could you please explain what is a _flower sreen_? Does the video contain flowers that are glitched out? [Like so maybe](https://www.techopedia.com/images/uploads/collage-poster-art-modern-art-home-decor-quilt-mosaic-tile-graphic-des.jpg).
 Same question for _blue screen_ is it a decoder error?
Maybe provide a screenshot?

Additionally, please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md). If you're unable to share bug reports or test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Please also update this issue to indicate you’ve done this.

**Comment by kuailedeadai** [comment]
Hello, I have captured the effect picture of Huaping as follows:
![Screenshot_20200513-072507](https://user-images.githubusercontent.com/10614848/81763217-4dbd9f00-9501-11ea-986b-1c18d59206e5.png)，
The video file is in h265 format, the phone model is TECNO I5，thank you

**Comment by kuailedeadai** [comment]
Hello, my test video is in h265 format, the decoded data bit depth is 16 bits, at this time Huaping, I use another h265 video, the decoded bit depth is 8 bits, the rendering is normal, please ask if this Is there any parameter of mediacodec that can be obtained or optimized?

**Comment by kuailedeadai** [comment]
[Spider-Man-x265-59fps-60s.mkv.zip](https://github.com/google/ExoPlayer/files/4641633/Spider-Man-x265-59fps-60s.mkv.zip)

This is a video file of the test Huaping, which occurs on most models below Android5.1

**Comment by kuailedeadai** [comment]
HDR video files generally have errors

**Comment by krocard** [comment]
Thank you for posting the problematic media.
I played it on both VLC with maximum verbosity and on my test Pixel 2 (checking the logcat), but could not observe any decoding log (1).

(1) Except for `05-18 10:36:11.067   920 10494 W QC2V4l2Codec: [hevcD_13] unknown/unsupported param index = 0xD200180A` but it did not prevent the video from playing.

As you commented, this seems to be device specific.

> if this Is there any parameter of mediacodec that can be obtained or optimized?


I'm not sure we can help you regarding device specific tuning, but maybe @ojw28 has some tips regarding video glitches?

**Comment by krocard** [comment]
@andrewlewis Do we have a way to validate an/[this](https://github.com/google/ExoPlayer/issues/7346#issuecomment-629906222) h265 stream?

**Comment by krocard** [comment]
@andrewlewis, sorry to assign you this issue but this seems to be a bad media case (1) and I don't know of a way to validate the h265 stream. None of the validators online seem to be free/easy to use.

(1) handled differently on certain devices. if the stream is correct, then this is a device specific decoder issue

**Comment by andrewlewis** [comment]
I'm afraid we don't have a stream validator/verifier, but the video does appear to play correctly on a Pixel 2 XL I have here. `mediainfo` identifies the stream profile/tier/level as Main 10, main, L4.1.

We have seen some cases of video rendering being broken in one of `SurfaceView` or `TextureView` so it may be worth trying both in case that fixes it.

> This is a video file of the test Huaping, which occurs on most models below Android5.1

I'm not sure what 'Huaping' is, but the [Android 5.0 CDD](https://source.android.com/compatibility/5.0/android-5.0-cdd#5_3_video_decoding) doesn't require support for 1080p H.265/HEVC, so I don't think there's an expectation that all Android devices can handle this.

You could try checking codec capabilities on the device to make sure this profile is supported (there are utilities in `MediaCodecUtil`) and contact the manufacturer if the device should be capable but it doesn't play.
