### ISSUE TITLE
Demo app: Support DRM protected downloads

### ISSUE THREAD

**Issue by hermasyp** [google/ExoPlayer#7347]
I have a question. in the documentation we can download clean media and store it as a cache in the device. but I need to download media with drm ( widevine ). is that possible ? can I get example for it ?

**Comment by krocard** [comment]
This question is similar to https://github.com/google/ExoPlayer/issues/7202.

@marcbaechinger or @AquilesCanta do we have an example of such DRM offload playback?

**Comment by ojw28** [comment]
We don't have an example, although we're getting closer to a point where it can be added to the demo app without too much additional complexity. Let's use this issue to track doing this.

**Comment by christosts** [comment]
We have included an example how to download DRM protected content on the demo app in v2.12, you can start by inspecting this snippet of code in [DownloadTracker.java](https://github.com/google/ExoPlayer/blob/r2.12.0/demos/main/src/main/java/com/google/android/exoplayer2/demo/DownloadTracker.java#L199-L231)
