### ISSUE TITLE
SubripParser asked to parse multiple times

### ISSUE THREAD

**Issue by IanDBird** [google/ExoPlayer#736]
This might be working as designed, but I thought best to raise after observing the behaviour. I've basically been having a look at SRT support and have a very basic implementation working using the sample code provided in https://github.com/google/ExoPlayer/issues/587:

```
DataSource textDataSource = new DefaultUriDataSource(context, bandwidthMeter, userAgent);
SingleSampleSource textSampleSource = new SingleSampleSource(textUri, textDataSource,
    MediaFormat.createTextFormat(MimeTypes.APPLICATION_SUBRIP, C.MATCH_LONGEST_US));
TrackRenderer textRenderer = new TextTrackRenderer(textSampleSource, player,
    player.getMainHandler().getLooper());
```

I added in my own logging into `SubripParser.parse` to see how often it's being called. I found the following:
 - On player start, it's being called twice
 - After any seek, it's also being called

Of course, the output of the `parse` method is the same since nothing has changed to potentially invalidate it. It doesn't really cause an issue though, unless the subtitle parsing is super expensive, so feel free to close if not worth trying to optimise.

**Comment by ojw28** [comment]
I only see it being called once when the player starts. It's likely you're calling seek at a sub-optimal time or something if you're seeing a second parse on player start.
