### ISSUE TITLE
Video And Audio Play at Same time

### ISSUE THREAD

**Issue by dolarbhanderi-meka** [google/ExoPlayer#7363]
Can i Play video and audio file at same time ?
Can i Increase and Decrease video duration using ExoPlayer.

**Comment by krocard** [comment]
> Can i Play video and audio file at same time ?

Yes, using a [`MergingMediaSource`](https://github.com/google/ExoPlayer/blob/dev-v2/library/core/src/main/java/com/google/android/exoplayer2/source/MergingMediaSource.java#L36).

The following example in the developer guide merges a subtitle and a video file, but you can do the same with a video and audio source: https://exoplayer.dev/media-sources.html#side-loading-a-subtitle-file

> Can i Increase and Decrease video duration using ExoPlayer.

I'm not sure to understand your question. The video duration is a property of the media beeing played. How could ExoPlayer increase it?

If you want to not play the beginning or end of a video stream, use a [`ClippingMediaSource`](https://github.com/google/ExoPlayer/blob/dev-v2/library/core/src/main/java/com/google/android/exoplayer2/source/ClippingMediaSource.java#L35)
Example in the developer guide: https://exoplayer.dev/media-sources.html#clipping-a-video

**Comment by krocard** [comment]
Please reopen if my previous comment does not answer your questions.

**Comment by dolarbhanderi-meka** [comment]
Thank you. @krocard
