### ISSUE TITLE
how to make custom actions with "PlayerNotificationManager.createWithNotificationChannel" ?

### ISSUE THREAD

**Issue by Bhuvanesh-Verma** [google/ExoPlayer#7364]
I want to create notification with custom actions
If I use PlayerNotificationManager() to create notification then I am not able to get notification.
However if I use PlayerNotificationManager.createWithNotificationChannel() then I am not able to use custom actions

**Comment by Bhuvanesh-Verma** [comment]
Otherwise is there any way to override default playPause notification button ?

**Comment by marcbaechinger** [comment]
Yes, you can use the constructor in case you want to use custom actions.

You can [create your notification channel yourself](https://developer.android.com/training/notify-user/channels) and then pass the channel id, name and constructor to the constructor.

> Otherwise is there any way to override default playPause notification button ?

If you want to override the drawables used by the actions you can override these as [described in the class level java doc of the PlayerNotificationManager](https://github.com/google/ExoPlayer/blob/release-v2/library/ui/src/main/java/com/google/android/exoplayer2/ui/PlayerNotificationManager.java#L108).

If you want to intercept the calls you can [set a custom `ControlDispatcher`](https://github.com/google/ExoPlayer/blob/release-v2/library/ui/src/main/java/com/google/android/exoplayer2/ui/PlayerNotificationManager.java#L707).

**Comment by Bhuvanesh-Verma** [comment]
Thanks, it worked. I thought there is any exoplayer specific constructor where I can make custom action along with Notification channel. But this worked as well.
Closing the issue.
