### ISSUE TITLE
Is it possible to change video duration after changing video speed?

### ISSUE THREAD

**Issue by ghost** [google/ExoPlayer#7366]
I have used `setPlaybackParameters` method to change speed of video. Player keep same duration when I increased or decreased speed. But if we apply process on video then if speed increased, video duration decreased and speed decreased, video duration increased. I want to show that in preview using exoplayer. 

Please guide me.

Thanks

**Comment by krocard** [comment]
I'm not sure to understand the question. What type of video processing are you talking about?

Do you want the video duration in the UI to decrease with the speed as if
`UI_video_duration = real_video_duration / speed`)

Or is the UI video duration you want to display related to your app _processing on video_, so not proportional to the speed?

**Comment by ghost** [comment]
Hi @krocard Thank you for quick response.
I have applied above formula. But video will complete on it's actual time.
Let's say I have choose video of `144639` Millisecond. set speed 5. As per your formula `144639/5 = 28927.8`. So now video duration is `28927.8`. But when I play video in exoplayer with speed `5` it will complete in `144639` Millisecond not `28927.8`. 
So how can I play complete video in updated duration?
I hope for your response.
Thank you.

**Comment by krocard** [comment]
> But when I play video in exoplayer with speed 5 it will complete in 144639 Millisecond not 28927.8.

If you play a video with speed 5, the real elapse time to play the video will be 5 time less.
Aka if you start a stopwatch at the beginning of the video, and stop the timewatch when it is finished playing, the stopwatch will show around 28927.8. You will also see and hear the video playing 5 time faster.

On the other hand, the timestamps reported by ExoPlayer (for example `Player.getCurrentPosition()`), are independent of the speed and refer to the position in the video as if it was played at speed 1.

If what you want is the real time ExoPlayer has played the current video (like the stopwatch would give you in my previous thought experiment), I'm afraid ExoPlayer does not keep track of it.
Nevertheless, assuming you always play the video at the same speed, you can divide the position that ExoPlayer returns by the playback speed to get the "stopwatch" position.

Does this answers your question?

**Comment by ghost** [comment]
Thanks for your help.

I have implemented as per you told. I calculated updated video duration and video will complete within updated duration with speed changes.

Let say `29568` Millisecond video, `0.6` speed set then updated video duration is `49280(29568 / 0.6).` So I sat that update duration and display in my screen.

But now I will seek manually and `seekTo` `24640` millisecond means `50%` of updated video duration. But player seek video almost till end because video actual duration is `29568`.
In That case what should I do to seek video to `50%`

Please guide me.

Thank you.

**Comment by krocard** [comment]
Does doing the inverse transformation when controlling the player fixes your issue. Aka
`player.seekTo(TimestampFromTheUI*videoSpeed)`.

In your example that would be: `player.seekTo(24640*0.6)`. As `24640*0.6 = 14784` which is 50% of the actual video duration (`29568/2`).

**Comment by ghost** [comment]
Yes, It is working.
Thank you so much for help and support.

**Comment by krocard** [comment]
You're welcome!
I'm closing this issue as your questions are answered.
