### ISSUE TITLE
Is the source code of the ExoPlayer's custom Cast receiver available somewhere?

### ISSUE THREAD

**Issue by Stonos** [google/ExoPlayer#7372]
### [REQUIRED] Searched documentation and issues
* Google
* ExoPlayer's repo: Found a commit (57ed00873ff948370d38901b5b0fd73992abfc7e) that mentions a `cast_receiver_app` directory on `,gitignore`, but that directory is not in the repo
* [ExoPlayer Integration](https://developers.google.com/cast/docs/android_sender/exoplayer) guide on the Cast documentation. It has some code snippets to help you integrate ExoPlayer, but it would be nice if the full source code was available as well.

### [REQUIRED] Question
Commit 3314391932394feef441d6f619651c6ea5f3d5f7 added a new Cast receiver (application id `A12D4273`) which supports DRM. Is the source code of this custom CAF receiver available somewhere?

### A full bug report captured from the device
N/A

### Link to test content
N/A

**Comment by AquilesCanta** [comment]
Hi @Stonos, there are two different apps in discussion here:
- The custom cast receiver project (the one [this commit](https://github.com/google/ExoPlayer/commit/57ed00873ff948370d38901b5b0fd73992abfc7e) references) was canceled before release. And ExoPlayer's cast extension users are encouraged to use the default cast receiver and follow cast's documentation if they want to implement their own custom receiver. We haven't released the source.
- The receiver app that supports DRM is just the default receiver app with a small modification to support DRM. I don't think the default receiver app's source is open source either, unfortunately.

I hope this answers your question. If you had any specific question in mind, please post it here and I'll try to help. I don't think I can do much to make any source code available, though.

**Comment by Stonos** [comment]
Thanks for the quick response!

Oh, my bad, I didn't realize that those were 2 different apps. I was talking about the receiver app that supports DRM.

So I assume that the only change that was made to it was to add a [License request handler](https://developers.google.com/cast/docs/android_sender/exoplayer#license_request_handler) in order to support DRM?

**Comment by AquilesCanta** [comment]
Yes, I'm not perfectly aware of what the change involves, but it basically plumbs the JSON message to make a license request. Please close if this answers your question.

**Comment by Stonos** [comment]
Thanks, that's what I needed to know!
