### ISSUE TITLE
Exoplayer FFMPEG issue. Video froze on the first frame after adding Exoplayer FFMPEG extension

### ISSUE THREAD

**Issue by Aravindraj93** [google/ExoPlayer#7373]
### [REQUIRED] Searched documentation and issues
https://github.com/google/ExoPlayer/issues/4940
https://github.com/google/ExoPlayer/issues/3852

### [REQUIRED] Question
I am working on adding Exoplayer and it works fine. But some of the videos were playing without audio, it plays fine in VLC medial player. So I was suggested to add Exoplayer FFMPEG. I added Exoplayer FFMPEG extension. But now Video froze on the first frame after adding Exoplayer FFMPEG extension

### A full bug report captured from the device
W/s.royal.royalt: Accessing hidden method Landroid/media/AudioTrack;->getLatency()I (light greylist, reflection)
I/ExoPlayerImpl: Init 386273d [ExoPlayerLib/2.10.2] [generic_x86, sdk_google_atv_x86, unknown, 28]
W/AudioManager: Use of stream types is deprecated for operations other than volume control
    See the documentation of requestAudioFocus() for what to use instead with android.media.AudioAttributes to qualify your playback use case
D/checkinglist: 45
I/ExoPlayerImpl: Init c08187e [ExoPlayerLib/2.10.2] [generic_x86, sdk_google_atv_x86, unknown, 28]
I/ViewTarget: Glide treats LayoutParams.WRAP_CONTENT as a request for an image the size of this device's screen dimensions. If you want to load the original image and are ok with the corresponding memory cost and OOMs (depending on the input size), use override(Target.SIZE_ORIGINAL). Otherwise, use LayoutParams.MATCH_PARENT, set layout_width and layout_height to fixed dimension, or use .override() with fixed dimensions.
I/chatty: uid=10073(royaltv.playvideo.channels.royal.royaltv) identical 4 lines
I/ViewTarget: Glide treats LayoutParams.WRAP_CONTENT as a request for an image the size of this device's screen dimensions. If you want to load the original image and are ok with the corresponding memory cost and OOMs (depending on the input size), use override(Target.SIZE_ORIGINAL). Otherwise, use LayoutParams.MATCH_PARENT, set layout_width and layout_height to fixed dimension, or use .override() with fixed dimensions.
E/Handlers: Calls
D/EGL_emulation: eglMakeCurrent: 0xe9ca5c60: ver 2 0 (tinfo 0xf14e09c0)
W/VideoCapabilities: Unrecognized profile 4 for video/hevc
I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
I/OMXClient: IOmx service obtained
D/SurfaceUtils: connecting to surface 0xd6aff808, reason connectToSurface
I/MediaCodec: [OMX.google.h264.decoder] setting surface generation to 32570369
D/SurfaceUtils: disconnecting from surface 0xd6aff808, reason connectToSurface(reconnect)
    connecting to surface 0xd6aff808, reason connectToSurface(reconnect)
E/ACodec: [OMX.google.h264.decoder] setPortMode on output to DynamicANWBuffer failed w/ err -1010
I/ACodec: codec does not support config priority (err -1010)
I/OMXClient: IOmx service obtained
I/ACodec: codec does not support config priority (err -2147483648)
I/ACodec: codec does not support config operating rate (err -2147483648)
D/MediaCodec: [OMX.google.h264.decoder] setting dataspace on output surface to #104
D/: HostConnection::get() New Host Connection established 0xd6341880, tid 31879
D/SoftwareRenderer: setting dataspace on output surface to #104
I/s.royal.royalt: Background concurrent copying GC freed 117(38KB) AllocSpace objects, 0(0B) LOS objects, 27% free, 15MB/21MB, paused 800us total 111.238ms

### Link to test content
Before it was playing the video fine, but I am facing this issue only after adding the Exoplayer FFMEG. Please help me with this issue. 

the code I modified after adding Exoplayer Ffmepg extension as follows,

`val videoTrackSelectionFactory: TrackSelection.Factory = AdaptiveTrackSelection.Factory(BANDWIDTH_METER)
val trackSelector: TrackSelector = DefaultTrackSelector(videoTrackSelectionFactory)

val renderersFactory: RenderersFactory = DefaultRenderersFactory(mContext, null, EXTENSION_RENDERER_MODE_PREFER)
mPlayer = ExoPlayerFactory.newSimpleInstance(mContext, renderersFactory, trackSelector)
mediaSource = mMediaSourceUri?.let { createLeafMediaSource(it) }!!
mPlayer.prepare(mediaSource)`

**Comment by andrewlewis** [comment]
Does it play on a real device (not the emulator)?

Please provide the media you are trying to play so we can reproduce the issue. If you're unable to share test content publicly, please send it to `dev.exoplayer@gmail.com` using subject "Issue #7373". Please also update this issue to indicate you’ve done this.

**Comment by Aravindraj93** [comment]
Thanks for helping me. No it doesn't work in real device as well. I tried to play the below testing link 
[http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4](url)

**Comment by Aravindraj93** [comment]
@andrewlewis  Hi, Could you help me with this issue?, And also there is no proper demo for the ffmpeg implementation. Could you help me with implementation code?

**Comment by Aravindraj93** [comment]
@andrewlewis I am still not able get the Ffmpeg extension to work.

**Comment by Aravindraj93** [comment]
@andrewlewis Atleast could you guide me what changes I need to make in the code after adding the ffmpeg extension?

**Comment by andrewlewis** [comment]
Sorry for the delay. The Elephants Dream stream provided above has AAC audio so I'd expect it to play fine without the ffmpeg extension. Are you sure you need to use it?

If you really do need to use the ffmpeg extension you'll need to compile ffmpeg with AAC support (see the [readme](https://github.com/google/ExoPlayer/blob/release-v2/extensions/ffmpeg/README.md) for the ffmpeg extension). The main demo app can use extension decoders (see [this documentation](https://exoplayer.dev/demo-application.html#enabling-extension-decoders)).

**Comment by Aravindraj93** [comment]
As I have mentioned before we have several videos that plays in VLC media player with audio and in Exoplayer it plays without audio. That's why I wanted to add ffmpeg extension. I have compiled ffmpeg with all the audio formats in my project. I just need to know what kind of changes I need to make in my code. I am developing an application for android TV.

` mPlayer = ExoPlayerFactory.newSimpleInstance(
            mContext,
            DefaultTrackSelector(),
            DefaultLoadControl()
        )
        mPlayer.addListener(this)`

` mediaSource = mMediaSourceUri?.let { createLeafMediaSource(it) }!!
        mPlayer.prepare(mediaSource)`
` fun createLeafMediaSource(uri : String) : MediaSource {
        val userAgent =
            Util.getUserAgent(mContext, "ExoPlayerAdapter")
        val dataSourceFactory =
            DefaultDataSourceFactory(mContext, userAgent)

        if(uri.contains(".")) {
            extension = uri.substring(uri.lastIndexOf("."))
        }
        @C.ContentType val type = Util.inferContentType(uri)
        if (type == C.TYPE_HLS){
            Log.d("TYPE_HLS", uri)
            return HlsMediaSource.Factory(dataSourceFactory).createMediaSource(Uri.parse(uri))
        } else if(type == C.TYPE_DASH){
            Log.d("TYPE_DASH", uri)
            return DashMediaSource.Factory(dataSourceFactory).createMediaSource(Uri.parse(uri))
        } else if(type == C.TYPE_SS){
            Log.d("TYPE_SS", uri)
            return SsMediaSource.Factory(dataSourceFactory).createMediaSource(Uri.parse(uri))
        } else if(type == C.TYPE_OTHER){
            Log.d("TYPE_OTHER", uri)
            return ProgressiveMediaSource.Factory(dataSourceFactory).createMediaSource(Uri.parse(uri))
        } else {
            Log.d("Others", uri)
            return ProgressiveMediaSource.Factory(dataSourceFactory).createMediaSource(Uri.parse(uri))
        }
    }`

These are the bit of code I am using to play the video in Android TV application. Everything was working fine. But some videos were playing without audio. So that's why I added the ffmpeg extension.   After compiling the ffmpeg extension, I added these below two line after going through the Readme file. 

`val renderersFactory: RenderersFactory = DefaultRenderersFactory(mContext, null, EXTENSION_RENDERER_MODE_ON)
        mPlayer = ExoPlayerFactory.newSimpleInstance(mContext, renderersFactory, trackSelector)`

After adding those two lines all the videos freezes in the first frame and it won't play.

**Comment by Aravindraj93** [comment]
As I have mentioned before we have several videos that plays in VLC media player with audio and in Exoplayer it plays without audio. That's why I wanted to add ffmpeg extension. I have compiled ffmpeg with all the audio formats in my project. I just need to know what kind of changes I need to make in my code. I am developing an application for android TV.

`mPlayer = ExoPlayerFactory.newSimpleInstance( mContext, DefaultTrackSelector(), DefaultLoadControl() ) mPlayer.addListener(this)
mediaSource = mMediaSourceUri?.let { createLeafMediaSource(it) }!! mPlayer.prepare(mediaSource)
` fun createLeafMediaSource(uri : String) : MediaSource {val userAgent=Util.getUserAgent(mContext, "ExoPlayerAdapter")
val dataSourceFactory =
DefaultDataSourceFactory(mContext, userAgent)`

    if(uri.contains(".")) {
        extension = uri.substring(uri.lastIndexOf("."))
    }
    @C.ContentType val type = Util.inferContentType(uri)
    if (type == C.TYPE_HLS){
        Log.d("TYPE_HLS", uri)
        return HlsMediaSource.Factory(dataSourceFactory).createMediaSource(Uri.parse(uri))
    } else if(type == C.TYPE_DASH){
        Log.d("TYPE_DASH", uri)
        return DashMediaSource.Factory(dataSourceFactory).createMediaSource(Uri.parse(uri))
    } else if(type == C.TYPE_SS){
        Log.d("TYPE_SS", uri)
        return SsMediaSource.Factory(dataSourceFactory).createMediaSource(Uri.parse(uri))
    } else if(type == C.TYPE_OTHER){
        Log.d("TYPE_OTHER", uri)
        return ProgressiveMediaSource.Factory(dataSourceFactory).createMediaSource(Uri.parse(uri))
    } else {
        Log.d("Others", uri)
        return ProgressiveMediaSource.Factory(dataSourceFactory).createMediaSource(Uri.parse(uri))
    }
}`
These are the bit of code I am using to play the video in Android TV application. Everything was working fine. But some videos were playing without audio. So that's why I added the ffmpeg extension. After compiling the ffmpeg extension, I added these below two line after going through the Readme file.

val renderersFactory: RenderersFactory = DefaultRenderersFactory(mContext, null, EXTENSION_RENDERER_MODE_ON) mPlayer = ExoPlayerFactory.newSimpleInstance(mContext, renderersFactory, trackSelector)

Still the videos plays without audio. And for your information I fixed the freezing issue on the first frame. But now the issue is the video still playing without audio. I have emailed the source link. Please check.

**Comment by andrewlewis** [comment]
The provided stream plays in the demo app (on a device without an AC3 `MediaCodec`) via `FfmpegAudioRenderer` if you build ffmpeg with AC3 decoding support and use a variant with extensions. There should be enough information on [enabling extension decoders](https://exoplayer.dev/demo-application.html#enabling-extension-decoders) and the [ffmpeg extension readme](https://github.com/google/ExoPlayer/blob/release-v2/extensions/ffmpeg/README.md) to get this to work. I'm afraid we don't have time to provide more detailed guidance so please read those pages carefully.

**Comment by Aravindraj93** [comment]
I fixed it my self. Thank you.
