### ISSUE TITLE
Drm Dash Video are not playing in redmi note 8 pro

### ISSUE THREAD

**Issue by gokulkalagara** [google/ExoPlayer#7384]
Getting this error only for this mobile only

**com.google.android.exoplayer2.drm.DrmSession$DrmSessionException: android.media.MediaDrm$MediaDrmStateException: Failed to handle key response: General DRM error**

Please help me

![WhatsApp Image 2020-05-15 at 12 59 17](https://user-images.githubusercontent.com/13214923/82027076-5228ba00-96b1-11ea-8bf8-b109c9918e8e.jpeg)

![WhatsApp Image 2020-05-15 at 12 59 09](https://user-images.githubusercontent.com/13214923/82027070-50f78d00-96b1-11ea-9743-0869d09e8e94.jpeg)

**Comment by gokulkalagara** [comment]
[log.txt](https://github.com/google/ExoPlayer/files/4640390/log.txt)

its log file

**ERROR**
playerFailed [eventTime=1.25, mediaPos=0.00, window=0, period=0\n 
 com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.drm.DrmSession$DrmSessionException: android.media.MediaDrm$MediaDrmStateException: Failed to handle key response: General DRM error\n      at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(SourceFile:30)\n      at android.os.Handler.dispatchMessage(Handler.java:102)\n      at android.os.Looper.loop(Looper.java:201)\n      at android.os.HandlerThread.run(HandlerThread.java:65)\n  Caused by: com.google.android.exoplayer2.drm.DrmSession$DrmSessionException: android.media.MediaDrm$MediaDrmStateException: Failed to handle key response: General DRM error\n      at com.google.android.exoplayer2.drm.DefaultDrmSession.onError(SourceFile:1)\n      at com.google.android.exoplayer2.drm.DefaultDrmSession.onKeysError(SourceFile:3)\n      at com.google.android.exoplayer2.drm.DefaultDrmSession.onKeyResponse(SourceFile:14)\n      at com.google.android.exoplayer2.drm.DefaultDrmSession.access$100(SourceFile:1)\n      at com.google.android.exoplayer2.drm.DefaultDrmSession$ResponseHandler.handleMessage(SourceFile:5)\n      at android.os.Handler.dispatchMessage(Handler.java:106)\n      ... 2 more\n  Caused by: android.media.MediaDrm$MediaDrmStateException: Failed to handle key response: General DRM error\n      at android.media.MediaDrm.provideKeyResponse(Native Method)\n      at com.google.android.exoplayer2.drm.FrameworkMediaDrm.provideKeyResponse(SourceFile:3)\n      at com.google.android.exoplayer2.drm.DefaultDrmSession.onKeyResponse(SourceFile:9)\n      ... 5 more\n]

**Comment by christosts** [comment]
This is probably a device issue unrelated to ExoPlayer but we might be able to provide some assistance you if you can share a bug report from the device, obtained after the device raises the error. You can send the bug report at dev.exoplayer@gmail.com with subject "Issue #7384".

**Comment by gokulkalagara** [comment]
@christosts
Its showing error as the 
**android.media.MediaDrm$MediaDrmStateException: Failed to handle key response: General DRM Error**

**Comment by ojw28** [comment]
@jt64 - Please take a look.

**Comment by jt64** [comment]
Yes we will need an adb bugreport to diagnose this further.

**Comment by gokulkalagara** [comment]
Its customer phone, I can't get that.

**Comment by rrfrias** [comment]
Instructions to capture a bugreport: https://developer.android.com/studio/debug/bug-report

**Comment by gokulkalagara** [comment]
I sent bug report please cross-check

**Comment by gokulkalagara** [comment]
@rrfrias @jt64 @ojw28 Please cross-check

**Comment by rrfrias** [comment]
Thanks for the logs @gokulkalagara . Unfortunately the bugreport does not capture the the license request and playback. Did you try to playback, have it fail and then capture the bugreport? If not can you try again. An alternative might be to capture a logcat without filtering out an log tags during the playback attempt.

**Comment by gokulkalagara** [comment]
I sent to 2 bug reports. @rrfrias @jt64 @ojw28 Please cross-check

**Comment by gokulkalagara** [comment]
any luck

**Comment by gokulkalagara** [comment]
@rrfrias please cross check

**Comment by ojw28** [comment]
@gokulkalagara - Please stop using `@mentions` and repeatedly spamming the same issues. All it does is create additional email for a large number of people to sift through. We will look at your issue when possible, and repeatedly spamming it wont make that happen any faster. Thanks!

**Comment by rrfrias** [comment]
Thanks for the logs. It appears that this is a device specific problem. I would like to get Xiaomi involved. Do i have permission to share a bugreport with them? Or can you send another bugreport/logcat that you would be comfortable sharing?

**Comment by ojw28** [comment]
@gokulkalagara - We cannot make progress here until you respond to the question above.

**Comment by gokulkalagara** [comment]
What I have do? you already said that issue belongs phone, not for Exoplayer

**Comment by gokulkalagara** [comment]
### Xiaomi Response
Identify whether the app crashes while using a particular app or under normal use circumstances.
If the issue is caused while using a particular app, please follow the below steps:

 1. Reboot the Device -Rebooting the device will close all the running apps & processes,

 2. Check for System Updates -Settings > About Phone > System Update > Check for Updates

 3. Check for App Updates -Play Store > Tap on “More”Option (on the top left corner)> My Apps & Games > Check for Updates>Update the apps,if any update available

 4. Check Storage and free up space -<10% of free storage space may cause instability issues.

( To clean up the storage files, navigate to Security > cleaner> clean up)

 5. Force Stop the application which is crashing -Force stopping an app will completely shut the app down and stop any background services that may address the symptoms

Settings > Apps > Manage apps >Tap and Open the app which is crashing > Force Stop

Or

Open security app> Manage Apps> Tap and Open the app which is crashing > Force Stop

 6. Clear app cache -Deletes the stored cache files 

 Settings > Apps > Tap and Open the app which is crashing > Storage > Tap on Clear Data >Select Clear cache

 Or

 Open security app> Manage Apps> Tap and Open the app which is crashing > Storage > Tap on Clear Data >Select Clear cache

 7. Clear app data -Deletes stored data that may have become corrupted or causing a conflict

Settings > Apps > Tap and Open the app which is crashing > Storage > Clear Data > Clear All data

Or

Open security app> Manage Apps> Tap and Open the app which is crashing >Storage > Clear data > Clear All data

 8. Uninstall and Re-install the apps -This is not a fix, but removing the app that is misbehaving should address the symptoms.

 Note: For Built-in apps - Uninstall the updates & retest. If the symptoms continue, disable the app.

However, you can also perform a factory reset if your issue is not solved.

Sign Out from your Mi Account:-

1. Go to Settings

2. Select Mi-Account

3. Then confirm to Sign Out

Create a Backup: -

1. Go to Settings

2. Select About phone

3. Select Backup and Reset

4. Select Local Backups

5. Select Backup

6. Select Accounts and Contacts & Deselect System

7. Then select Backup so that a backup would be created

For Finding Backup File:-

1. Go to Internal Storage

2. Select MIUI

3. Select Backup

4. Select All Backup

(Note: - Please save the backup file in your PC/ Laptop, so that your important data would be prevented)

Factory Data Reset:-

1. Go to Settings

2. Select About phone

3. Select Backup and Reset

4. Tap on Factory Data Reset

Restoring Data:-

1. Go to Settings

2. Select About phone

3. Select Backup and Reset

4. Select Local Backups

5. Select Backup File

6. Select Restore in order to complete this process

If the app still continues to crash, the report in the Feedback app. I also share your feedback with our concerned team.

Also, I would like to inform you that we are sending updates to the customers to remove any bug or issues if they are facing in the device and also to run the device smoothly with new applications or options.

However, it will not affect your application or it will not consume extra space. If in case you are facing such issues I request you to kindly go to feedback option in your device and send your feedback to the developer team, so that our team can come up with a next update to fix the issue at the earliest.

With respect to your concern, there are two methods by which you can update your mobile:

1)  Automatic: To check for an update, go to Settings > About Phone > System Update > Check for Updates. Some devices might receive the update early in comparison to other devices as OTA updates are released in batches to compensate the load on the server.

2)  Manual -> Go to http://en.miui.com/download.html & choose your device. Once chosen, the next page will give you the links to download the ROM file. Ensure you are on the 'Global' page & click on Download Full ROM. Version number & size of the update will be mentioned right below the download link. You can also try to download this file into your mobile phone or connect your device to the Windows PC/laptop via a micro USB cable, and copy the ROM file downloaded into the folder ‘downloaded_rom’ in the internal storage of your device. If the folder is unavailable, create a folder with exactly the similar name. To update your device follow the mentioned steps: Setting >> about phone >> system update >> Click the ‘…’ the icon at the top-right corner, select ‘Choose update package’, and choose the ROM file you’ve put in ‘downloaded_rom’.

After choosing the right ROM file, your device will begin upgrading. Your device should automatically boot to the new version when the update is completed.

I have also taken your feedback and forwarded it to the concerned team so that the issues which you are facing will be rectified in the future update.

**Comment by ojw28** [comment]
> What I have do?

As already stated, we cannot make progress here until you respond to the question we asked you, which was:

> I would like to get Xiaomi involved. Do i have permission to share a bugreport with them? Or can you send another bugreport/logcat that you would be comfortable sharing?

**Comment by gokulkalagara** [comment]
I cant unable to understand. what question you have asked?
One of the developer, says to share the bug report to Xiaomi.
I share, they give some response. comment paste it above, its comment type as off-topic. 
I missed it, could you please repeat your question?

**Comment by rrfrias** [comment]
gokulkalagara, can i share the bugreport with Xiaomi, as well? I need you to say ok.

This is a device problem rather than an exoplayer issue. We can follow up with the Xiaomi engineers and find out whether there is a way to address this.

**Comment by gokulkalagara** [comment]
ok you can share, this to Xiaomi

**Comment by rrfrias** [comment]
Thanks @gokulkalagara . We are following up with Xiaomi. Will let you know when we have more information.

**Comment by rrfrias** [comment]
We have been looking at the bugreports with Xiaomi. The original log.txt (second comment) had a MediaDrmStateException, but i do not see this in any of the bugreports you shared with us. Can you capture a bugreport after a playback attempt and share with us? You can capture a logcat and see if playback was attempted/MediaDrmStateException occurred.

**Comment by pratimagauns** [comment]
Hi,
I also receive this issue for my app on Redmi Note 8 pro running video with Widevine DRM. I was waiting for resolution on this thread. I can share the required bug reports with you.

**Comment by ojw28** [comment]
@pratimagauns - If you're able to capture a bug report shortly after encountering the issue, please share it with `dev.exoplayer@gmail.com` using the subject title "Issue #7384" and then update this issue to indicate that the bug report has been sent. If you could also indicate whether you're happy for us to share your bug report with Xiaomi when you respond here, that would also be useful, and this might unblock further progress. Thanks!

**Comment by gokulkalagara** [comment]
the client did not share the bug report, so I'm closing the issue
