### ISSUE TITLE
removeFirst error, threading and activities usage

### ISSUE THREAD

**Issue by Verdurakh** [google/ExoPlayer#7385]
I have a question about usage of exoplayer.
I recently switched from MediaPlayer to Exoplayer to play background music in a game and from my local tests everything is working as it should but I'm getting crash reports in crashalytics.
crashalytics:
NoSuchElementException at java.util.ArrayDeque.removeFirst (ArrayDeque.java:264)

From my research this might have to do with threading and can occur when calling the player from different threads.
I am using exoplayer-core:2.11.4 only

### [REQUIRED] Searched documentation and issues
Might be refereed from my question of usage

### [REQUIRED] Question
My question is about the usage that I've implemented.
I have a game app with 4 activities all activities will be playing different background music, 3 of them is from menus and one is handling the game loop.
Since I basically replaced my MediaPlayer implementation all of the menu activities have their own SimpleExoPlayer instance that they are creating and releasing as needed.
My game is running in it's own thread and have its own instance of SimpleExoPlayer and will also sometimes stop, release and recreate as needed.
The below code is called each time I need to play a new song
```
    private SimpleExoPlayer createSimpleExoPlayer(Context context, int resId, boolean repeat) {
        SimpleExoPlayer exoPlayer = new SimpleExoPlayer.Builder(context).build();
        DataSource.Factory dataSourceFactory = new DefaultDataSourceFactory(context,
            Util.getUserAgent(context, "appname"));
        Uri uri = RawResourceDataSource.buildRawResourceUri(resId);
        MediaSource source = new ProgressiveMediaSource.Factory(dataSourceFactory).createMediaSource(uri);
        exoPlayer.prepare(source);
        if (repeat)
            exoPlayer.setRepeatMode(Player.REPEAT_MODE_ALL);
        //exoPlayer.setPlayWhenReady(true);
        return exoPlayer;
    }
```

So I wonder if I have misunderstood how to use the player?
My thinking was that since each activity have their own instance and they don't talk with any players outside their own context it should be fine.

Or am I supposed to have a singleton SimpleExoPlayer that I move between each activity and send commands to?

Could the problem be my gameActivity that runs the game thread that is causing the problem? Even though they never talk with each other directly.(gameActivity have no reference to the loops player)
Would the solution then be to let the GameActivity hold the player and send commands to the activity from the loop and let it stop and start things?

### A full bug report captured from the device
```
NoSuchElementException at java.util.ArrayDeque.removeFirst (ArrayDeque.java:264)
com.google.android.exoplayer2.ExoPlayerImpl.notifyListeners (ExoPlayerImpl.java:737)
com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo (ExoPlayerImpl.java:710)
com.google.android.exoplayer2.ExoPlayerImpl.handlePlaybackInfo (ExoPlayerImpl.java:652)
com.google.android.exoplayer2.ExoPlayerImpl.handleEvent (ExoPlayerImpl.java:595)
com.google.android.exoplayer2.ExoPlayerImpl$1.handleMessage (ExoPlayerImpl.java:127)
```

**Comment by Verdurakh** [comment]
ok, I found logs saying that I was making calls on the wrong thread, so assume that my instance inside the game loop is the problem, have moved it to the game activity and will see if it solves the problem

**Comment by Verdurakh** [comment]
So I moved the exoplayer from game loop into the game activity which should be running on the main thread and communicate with broadcast messages from the game loop to the activity, and it removed all the logs but I still get the crash error in crashalytics:

```
Fatal Exception: java.util.NoSuchElementException
java.util.ArrayDeque.removeFirst (ArrayDeque.java:248)
com.google.android.exoplayer2.ExoPlayerImpl.notifyListeners (ExoPlayerImpl.java:737)
com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo (ExoPlayerImpl.java:710)
com.google.android.exoplayer2.ExoPlayerImpl.handlePlaybackInfo (ExoPlayerImpl.java:652)
com.google.android.exoplayer2.ExoPlayerImpl.handleEvent (ExoPlayerImpl.java:595)
com.google.android.exoplayer2.ExoPlayerImpl$1.handleMessage (ExoPlayerImpl.java:127)
android.os.Handler.dispatchMessage (Handler.java:111)
android.os.Looper.loop (Looper.java:210)
android.app.ActivityThread.main (ActivityThread.java:5973)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:852)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:742)
```

**Comment by Verdurakh** [comment]
getting a few more crashes 3  of the NoSuchElementException but they point at different rows of ArrayDeque (264,263,248)

Can the errors be because I'm recreating the player whenever I want to change music and each activity have their own player?
The use case is
Main activity -> game activity -> end activity1 or end activity2 and then back to main activity

Also got the below error

```
Fatal Exception: java.lang.NullPointerException
Attempt to invoke interface method 'void java.lang.Runnable.run()' on a null object reference
com.google.android.exoplayer2.ExoPlayerImpl.notifyListeners (ExoPlayerImpl.java:736)
com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo (ExoPlayerImpl.java:710)
com.google.android.exoplayer2.ExoPlayerImpl.handlePlaybackInfo (ExoPlayerImpl.java:652)
com.google.android.exoplayer2.ExoPlayerImpl.handleEvent (ExoPlayerImpl.java:595)
com.google.android.exoplayer2.ExoPlayerImpl$1.handleMessage (ExoPlayerImpl.java:127)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:148)
android.app.ActivityThread.main (ActivityThread.java:5551)
java.lang.reflect.Method.invoke (Method.java)

```

**Comment by tonihei** [comment]
The player needs to be accessed from one single thread. That is, *all* methods need to be called on this thread without exception. See also [this section in the documentation](https://exoplayer.dev/hello-world.html#a-note-on-threading).

By default, the player expects to use the thread it is created on, but you can manually set the thread by using `SimpleExoPlayer.Builder.setLooper` if you like.

The error messages you posted above show that it is very likely that the player was accessed from multiple threads. Please have a look at logcat for "Player is accessed on the wrong thread.". These warnings will tell you when this happens and the first time it will also print a stack trace so that you can easily identify the code that causes this to happen.

**Comment by Verdurakh** [comment]
> The player needs to be accessed from one single thread. That is, _all_ methods need to be called on this thread without exception. See also [this section in the documentation](https://exoplayer.dev/hello-world.html#a-note-on-threading).
> 
> By default, the player expects to use the thread it is created on, but you can manually set the thread by using `SimpleExoPlayer.Builder.setLooper` if you like.
> 
> The error messages you posted above show that it is very likely that the player was accessed from multiple threads. Please have a look at logcat for "Player is accessed on the wrong thread.". These warnings will tell you when this happens and the first time it will also print a stack trace so that you can easily identify the code that causes this to happen.

Thanks for the reply.
As I said in my follow up comments I had the message of threading when I used exoplayer inside the game loop but I moved it into the activity and use local broadcast messages to change what is playing instead and that removed the logs that I could find.

Also I notice in the logs that the crash often happen after several usages and game attempts.

As far as I know all activities is using the ui thread so there shouldn't be any difference in how they are handled

**Comment by tonihei** [comment]
The second failure looks more like you added a `null` listener to the player. Please check you only add non-null listeners when calling `player.addEventListener` or similar.

**Comment by Verdurakh** [comment]
> The second failure looks more like you added a `null` listener to the player. Please check you only add non-null listeners when calling `player.addEventListener` or similar.

I'm not setting any listeners.
See the creation code I posted above, the only thing I do with the player after it is created is setting runWhenReady(true/false)

**Comment by tonihei** [comment]
Yes, sorry, ignore the last comment. The second error also clearly indicates parallel access. Please check again to see if there are any warnings.

**Comment by Verdurakh** [comment]
I'll take a look again and see if I can find something.

So you don't think there is any problem with recreating the player in each activity?

**Comment by tonihei** [comment]
> So you don't think there is any problem with recreating the player in each activity?

No, that shouldn't be an issue.

**Comment by Verdurakh** [comment]
I was actually able to identify  one more threading issue as you said that was only used in rare cases where I called the player from a TimerTask that I in my mistake thought would play out on the main thread on its completion.
I've uploaded the new version and will wait and see if it solves the issue.

Another question, even though the crash was caught in Crashalytics would it really have created a app crash for the user? I've tested it 100 times on my device and it always seemed to work flawlessly .

**Comment by tonihei** [comment]
> Another question, even though the crash was caught in Crashalytics would it really have created a app crash for the user? I've tested it 100 times on my device and it always seemed to work flawlessly .

That's the problem with multi-threading issues - they aren't easy to reproduce. It's likely that this caused a crash for the users where it occurred because there is no try/catch block that could have caught the exception. 

To make it easier to detect such problems in the future, we will throw immediately when the player is used from the wrong thread in one of the next ExoPlayer releases. This way, you will see the problem immediately during development time and not only as spurious crashes in a released version.

**Comment by Verdurakh** [comment]
It seems like the last change resolved my issue, thank you for your help.

And yes I think that would be a good change, logs can be hard to find if they are not thrown in a common function
