### ISSUE TITLE
PlayerNotificationManager is not removing Notification after swiping from recent items

### ISSUE THREAD

**Issue by Bhuvanesh-Verma** [google/ExoPlayer#7386]
I am streaming audio through Exoplayer and creating respective notification for it. 
When I remove app from recent apps, onTaskRemoved is called from service and notification is removed. However it only happens if I try to remove app within 1-2 minutes of starting the app. Post that if I try to swipe remove app from recent apps, playback is stopped but notification is not removed. Even onTaskRemoved is not called. 
Further if I click on Notification then it redirects me to MainActivity where service instance is recreated.
I am not using foreground service explicitly

**Comment by Bhuvanesh-Verma** [comment]
I explicitly used startForeground()  in onNotificationStarted() and closed it with stopForeground in onNotificationClosed(). I am able to remove notification properly now but playback is not being stopped. 
onDestroy() and onTaskRemoved() is being called but still music keeps on playing. 
I then used player.setPlayWhenReady(false) in onDestroy() to stop music onDestroy() which worked but then if I try to restart the app again it crashes.

**Comment by marcbaechinger** [comment]
DId you manage to remove these issues? I think you are digging at the right spot in making the service nicely integrated into the life cycle of the app/playback. Please let me know about your state.

If not yet solved and when you are at it. Can you probably add an `EventLogger` with `player.addAnalyticListener()`, take a bug report and upload here. This allows us to look into it more easily.

**Comment by Bhuvanesh-Verma** [comment]
No I am still stuck. I will try what you suggested and will report back. Thanks

**Comment by Bhuvanesh-Verma** [comment]
![evntloger](https://user-images.githubusercontent.com/25547376/83015159-9ca91f80-a03d-11ea-94c5-bef3b703bbde.jpg)

I kept streaming for 2-3 minutes after that I removed app using swipe action from recent apps.


This is the code used as you suggested

` DefaultTrackSelector trackSelector = new DefaultTrackSelector();
            DefaultDataSourceFactory dataSourceFactory = new DefaultDataSourceFactory(getApplicationContext(), "RadioPlayer");

            HlsMediaSource mediaSource = new HlsMediaSource.Factory(dataSourceFactory)
                    .createMediaSource(Uri.parse(streamUrl));

            exoPlayer.prepare(mediaSource);
            exoPlayer.setPlayWhenReady(true);
            exoPlayer.addAnalyticsListener(new EventLogger(trackSelector));`

**Comment by marcbaechinger** [comment]
Can you please [create a bug report](https://developer.android.com/studio/debug/bug-report) after the notification has been removed and then upload it here?

**Comment by Bhuvanesh-Verma** [comment]
The only way to remove notification after this situation is to tap on Notification which opens app and then stream media and then tap on stop button in notification. Otherwise notification stays there only.

**Comment by marcbaechinger** [comment]
The notification would not be removed by the system until you have called `stopForeground(/* removeNotification= */ true || false)`. Do you call this?

Please also look into #6944 which was about a similar case.

**Comment by Bhuvanesh-Verma** [comment]
If I do not use foreground service then the main problem which I stated regarding "Notification not getting removed after 2-3 minutes of playback " is coming.
If I use foreground service then this problem is solved but another problem is occurred. After removing app from recent apps App and notification is removed but music keeps on playing. In this case I have used stopForeground().

**Comment by marcbaechinger** [comment]
If you properly stop the service i.e. with `stopForeground` and `stopSelf` and at the same time release the player this should work properly. Please refer to the[ life-cycle of a service documentation](https://developer.android.com/guide/components/services#Foreground) to see how to achieve that.

If you want me to look into this some further please send me a bug report as described above. I can't really help you with the information available.

**Comment by Bhuvanesh-Verma** [comment]
Sure I will try to stop service properly one more time, if it didn't work then I will share the bug report.

**Comment by Bhuvanesh-Verma** [comment]
I started service as foreground service and changed nothing. It is working uninterruptedly now. Thanks
Closing the issue
