### ISSUE TITLE
Correct way of implementing an interactive livestream from a gRPC streaming endpoint

### ISSUE THREAD

**Issue by bhanuism** [google/ExoPlayer#7387]
### [REQUIRED] Searched documentation and issues
Exoplayer Javadoc: Looked at ProgressiveMediaSource, ConcatenatingMediaSource, ByteArrayDataSource, UdpDataSource
Exoplayer github issues: Found this #7238  which closely resembles my use case 

### [REQUIRED] Question
I'm implementing an interactive livestream(e.g a video call/conference). Exoplayer will render the video packets obtained from a gRPC streaming endpoint. Using gRPC client i'm able to get continuous video packets flowing in on a coroutine. Now i need to render them on a SurfaceView using Exoplayer. 

The **first** thing i did was to use a ProgressiveMediaSource with ByteArrayDataSource. It worked but the source is bounded, so it plays a packet and the player stops. Then i used a ConcatenatingMediaSource and started adding ProgressiveMediaSources with ByteArrayDataSource in a different coroutine. This worked and player started continuously playing new video packets. But this feels like system would be doing heavy work. Is it? There must be a simpler way. Also i need to track the size of ConcatenatingMediaSource and remove old media sources in it. And if player drifts away from live edge, i also need to skip the player to the latest media source. Is it the right approach?

The **second** thing i did was to look at #7238. This is a similar problem statement except the packets are arriving on udp. And seeing the implementation, it felt like i can create a datasource implementation which never returns C.RESULT_END_OF_INPUT, rather gets a new packet and starts reading from it. But this didn't work, player kept on reading and never played anything. I can provide further info on this, if needed. 

The **third** thing which i'm still working on, is to create a custom implementation of MediaSource, which provides a timeline with a single window and a single period(with unknown duration). I'm going through Exoplayer provided implementations of various media sources, to understand the flow. Seems overwhelming on first look. There are MediaSourceCallers, source info has to be refreshed, media periods need to be prepared, extractors need to be used, MediaPeriod.Callback needs to called etc. etc. Should i go down this path? Or is there a way to use existing implementations?

One **important** thing to notice here is that, video packets are expected to be smaller, covering a duration of at most 1 second, and latency needs to be smaller than 1 second. The player is supposed to be as close to the live edge as possible, and rather drop packets if it's drifting away. 

I really need your guidance to pick the right implementation, and also if there are any performance issues i should watch out for.

**Comment by marcbaechinger** [comment]
Sorry for my late reply. 

I think I'd try to do a custom data source rather than a custom media source. Like create a `GrpcDataSource` in which you can do your logic. Then create a `ProgressiveMediaSource` with that. 

Issue #7228 is probably helpful for creating a custom data source. You can create an unbounded data source which returns `C.LENGTH_UNSET` on `open()` to signal that the data source is unbounded. See the documentation of [DataSource.open](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/upstream/DataSource.html#open-com.google.android.exoplayer2.upstream.DataSpec-) also.

**Comment by marcbaechinger** [comment]
After discussing this internally a bit it has been brought up that ExoPlayer may not be the best choice for your low-latency use case. I won't stop you from trying :) Just saying.
