### ISSUE TITLE
How to determine the type of MediaSource to use

### ISSUE THREAD

**Issue by AnkurJagani** [google/ExoPlayer#7389]
Que. 1: Is it possible to detect the `MediaSource` type before We initialise it? I am playing different types of urls from backend and I need to specify the types of url whether it is `dash`, `hls`, `progressive` or `ss`. I am curios to know if there is any method from exoplayer which can infrom us the type of 'MediaSource' so that I can easily automate my client code. 

Que. 2 : What should be the `MediaSource` for url like `http://149.242.212.8:8081/us/channel/1`? (Provided url is not actual one. Because this question will be public, right?)

**Comment by marcbaechinger** [comment]
You need to figure out the type of media source you need to instantiate for a given stream yourself. 

As you say, there are three adaptive types with a manifest which are DASH, HLS and SmoothStreaming. So for one of these three types, you need to know which one you need and then instantiate the correct one. 

All the progressive formats need a `ProgressiveMediaSource`. The type of extractor required internally is evaluated by sniffing the content of the progressive format and then selecting the correct extractor.

So in general you need to know whether your stream is DASH, HLS or SmoothStreaming. All the rest is handled by the `ProgressiveMediaSource`.

**Comment by AnkurJagani** [comment]
Thank you for your prompt reply. Is there any comment for my second question? (I can provide you actual url if it is must)

**Comment by yoobi** [comment]
> Que. 2 : What should be the MediaSource for url like http://149.242.212.8:8081/us/channel/1? (Provided url is not actual one. Because this question will be public, right?)

The `MediaSource` doesn't depend on the url but on the type of your video, for example if your video is a `mp4` you will use [`ProgressiveMediaSource`](https://exoplayer.dev/progressive.html)

**Comment by marcbaechinger** [comment]
> Is there any comment for my second question?

The library will not help you to figure out the type with a generic URI. You need to know the type of the stream and then create the appropriate media source as described above.
