### ISSUE TITLE
Running project demo in Exoplayer new least is not successull.

### ISSUE THREAD

**Issue by kinhdang** [google/ExoPlayer#739]
Dear all !

I have downloaded the new least ExoPlayer, and running ExoPlayerDemo in eclipse, but not successfull, Please tell me, how to fix this case ? 

Thanks a lots.

this is log file :
 08-26 03:51:19.932: I/dalvikvm(2564): Failed resolving Lcom/google/android/exoplayer/demo/PlayerActivity; interface 1696 'Lcom/google/android/exoplayer/audio/AudioCapabilitiesReceiver$Listener;'
08-26 03:51:19.932: W/dalvikvm(2564): Link of class 'Lcom/google/android/exoplayer/demo/PlayerActivity;' failed
08-26 03:51:19.932: E/dalvikvm(2564): Could not find class 'com.google.android.exoplayer.demo.PlayerActivity', referenced from method com.google.android.exoplayer.demo.SampleChooserActivity.onSampleSelected
08-26 03:51:19.932: W/dalvikvm(2564): VFY: unable to resolve const-class 1727 (Lcom/google/android/exoplayer/demo/PlayerActivity;) in Lcom/google/android/exoplayer/demo/SampleChooserActivity;
08-26 03:51:19.932: D/dalvikvm(2564): VFY: replacing opcode 0x1c at 0x0002
08-26 03:51:20.372: I/Choreographer(2564): Skipped 35 frames!  The application may be doing too much work on its main thread.
08-26 03:51:20.372: D/gralloc_goldfish(2564): Emulator without GPU emulation detected.
08-26 03:51:21.682: D/dalvikvm(2564): GC_FOR_ALLOC freed 80K, 5% free 3030K/3176K, paused 2ms, total 7ms
08-26 03:51:24.512: D/AndroidRuntime(2564): Shutting down VM
08-26 03:51:24.512: W/dalvikvm(2564): threadid=1: thread exiting with uncaught exception (group=0xb1c6db20)
08-26 03:51:24.512: E/AndroidRuntime(2564): FATAL EXCEPTION: main
08-26 03:51:24.512: E/AndroidRuntime(2564): Process: com.google.android.exoplayer.demo, PID: 2564
08-26 03:51:24.512: E/AndroidRuntime(2564): java.lang.NoClassDefFoundError: com.google.android.exoplayer.demo.PlayerActivity
08-26 03:51:24.512: E/AndroidRuntime(2564): 	at com.google.android.exoplayer.demo.SampleChooserActivity.onSampleSelected(SampleChooserActivity.java:87)
08-26 03:51:24.512: E/AndroidRuntime(2564): 	at com.google.android.exoplayer.demo.SampleChooserActivity.access$0(SampleChooserActivity.java:86)
08-26 03:51:24.512: E/AndroidRuntime(2564): 	at com.google.android.exoplayer.demo.SampleChooserActivity$1.onItemClick(SampleChooserActivity.java:80)
08-26 03:51:24.512: E/AndroidRuntime(2564): 	at android.widget.AdapterView.performItemClick(AdapterView.java:299)
08-26 03:51:24.512: E/AndroidRuntime(2564): 	at android.widget.AbsListView.performItemClick(AbsListView.java:1113)
08-26 03:51:24.512: E/AndroidRuntime(2564): 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:2911)
08-26 03:51:24.512: E/AndroidRuntime(2564): 	at android.widget.AbsListView$3.run(AbsListView.java:3645)
08-26 03:51:24.512: E/AndroidRuntime(2564): 	at android.os.Handler.handleCallback(Handler.java:733)
08-26 03:51:24.512: E/AndroidRuntime(2564): 	at android.os.Handler.dispatchMessage(Handler.java:95)
08-26 03:51:24.512: E/AndroidRuntime(2564): 	at android.os.Looper.loop(Looper.java:136)
08-26 03:51:24.512: E/AndroidRuntime(2564): 	at android.app.ActivityThread.main(ActivityThread.java:5001)
08-26 03:51:24.512: E/AndroidRuntime(2564): 	at java.lang.reflect.Method.invokeNative(Native Method)
08-26 03:51:24.512: E/AndroidRuntime(2564): 	at java.lang.reflect.Method.invoke(Method.java:515)
08-26 03:51:24.512: E/AndroidRuntime(2564): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
08-26 03:51:24.512: E/AndroidRuntime(2564): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
08-26 03:51:24.512: E/AndroidRuntime(2564): 	at dalvik.system.NativeStart.main(Native Method)
08-26 03:51:26.282: I/Process(2564): Sending signal. PID: 2564 SIG: 9

**Comment by ojw28** [comment]
This looks like something wrong with your local setup to me. Specifically:

```08-26 03:51:19.932: E/dalvikvm(2564): Could not find class 'com.google.android.exoplayer.demo.PlayerActivity```

That class definitely still exists in the code base. It might be an eclipse quirk. Try cleaning the project, closing and opening it again, then doing a clean build.

**Comment by ened** [comment]
If it builds with `./gradlew clean assembleDebug`, it should be fine. @ojw28 just to be sure, it might be beneficial to setup a travis-ci instance and add the build label to the README file.

**Comment by ojw28** [comment]
The logs show that the demo app is running (and then crashes), so it must have built and installed successfully. Closing the issue, since it's likely to be a local issue with the reporters environment.
