### ISSUE TITLE
Google Assistant Voice Commands not working on AndroidTV

### ISSUE THREAD

**Issue by aureobeck** [google/ExoPlayer#7396]
### Searched documentation and issues
Official `ExoPlayer` documentation and source code of `MediaControllerCompat`, `MediaSessionConnector`, `MediaSession` classes.

### Question
The new version release of Google app of May 14th (4.1.0.310049754) is not calling any callbacks on `MediaSessionConector`'s `DefaultMediaMetadataProvider` such as `onPause`, `onPlay`, `onSeekTo`.

On version 3.14.1.294935492 (March 30) of Google app it's still working as expected.

**Comment by marcbaechinger** [comment]
Thanks for reporting. Seems like something changed in 4.1.0.310049754.
What is the package name of this app? Is this [katniss](https://play.google.com/store/apps/details?id=com.google.android.katniss&hl=en_GB)?

On what device can I repro this?

What is the voice command you are issuing and how does Assistant behave when you issue the command? Does it pretend it works but the command does not arrive in your app? Please give me some more context so I have a chance to look into this myself in case I have a device available with that version.

Best would be if you take a bug report right after you have seen the faulty behaviour.

**Comment by aureobeck** [comment]
Yeah this was katniss. They just published a new version yesterday (3.14.2.312211540 ) and now it's working as expected. Probably they fixed the issue, thanks!

**Comment by marcbaechinger** [comment]
Ok, thanks for letting me know. I'm closing this issue. Please re-open if you notice further problems.

**Comment by aureobeck** [comment]
Greetings @marcbaechinger , we've noticed that on new version from Google app for Androidtv release on June 13 (4.2.0.314209501) this same issue was reintroduced: it's not calling any callbacks on MediaSessionConector's `DefaultMediaMetadataProvider` such as `onPause`, `onPlay`, `onSeekTo`.

On version 3.14.2.312211540 (May 20) of Google app it's still working as expected with Exoplayer 2.11.7
