### ISSUE TITLE
Does the order of code when initing the player matter?

### ISSUE THREAD

**Issue by hyeonsu94** [google/ExoPlayer#7398]
Most of the sample code calls 'setPlayWhenReady()' after calling the 'prepare()' method.

There's no particular reason, but I'm calling 'setPlayWhenReady()' first.

Is there any possibility of side effects or issues (I'm asking because there is already a distributed version)?

**Comment by christosts** [comment]
I am not aware of an issue when calling `setPlayWhenReady()` before `prepare()`. Let us know if you see something strange.
