### ISSUE TITLE
Current position when playing a sequence of audio files

### ISSUE THREAD

**Issue by th3hamm0r** [google/ExoPlayer#740]
I'm playing around with a sequence of gapless ogg files and how to implement a clean solution with the ExoPlayer.
I've implemented a custom `SampleSource` which instantiates a `FrameworkSampleSource` for each file and forwards the necessary calls. Between each file the `FORMAT_READ` resets the codec in `MediaCodecAudioTrackRenderer`. This works and it plays without gaps.

My problem is that the current position which gets updated by the track renderer is wrong, since the `presentationTimeUs` restarts from 0 on every file change. This of course works as intended and I can fix it by updating the `timeUs` of each `SampleHolder` to hold the absolute position across all files, as it is done by all the `ChunkSource` implementations.
But I have problems calculating this absolute position on the device. I'm using the duration returned by the `MediaExtractor`, but I've samples where this duration is wrong or inaccurate so after some playback the current position information is totally wrong.

Is there another way to get the correct absolute playback position from the `MediaCodecAudioTrackRenderer` without having to pass the correct absolute timestamp (across all files) to the decoder? Maybe it it easier to get access to `AudioTrack.getPlaybackHeadPosition()`, but I don't see a way without duplicating the renderer's implementation?

**Comment by ojw28** [comment]
This question is not about functionality supported directly by ExoPlayer, and therefore falls outside the scope of this issue tracker. Closing. We'll be supporting playlists more directly in the ExoPlayer 2.x release.
