### ISSUE TITLE
exoplayer uses a lot of traffic

### ISSUE THREAD

**Issue by javalue** [google/ExoPlayer#7400]
hello exoplayer‘s developer
it's my question:
i have many videos, there are in list, when i slide screen, i will change the uri and rebuild mediasource. it's exist only one player and one textrueview.
In the test, my friend find it uses a lot of traffic, data speed plugin show 1-2m/s. it continued for about 4-5 seconds,but my video size just 2MB.

it's my old code:
```
player = ExoPlayerFactory.newSimpleInstance(
                new DefaultRenderersFactory(context),
                new DefaultTrackSelector(), new DefaultLoadControl());

private MediaSource buildMediaSource(int position, Uri uri) {
        if (sourceArray.get(position) != null) {
            return sourceArray.get(position);
        }

        MediaSource source = new ExtractorMediaSource.Factory(
                new DefaultHttpDataSourceFactory("exoplayer-codelab")).
                createMediaSource(uri);
        sourceArray.put(position, source);
        return source;
    }
```

today, i add the cache like this:

```
private MediaSource buildMediaSource(int position, Uri uri) {
        if (sourceArray.get(position) != null) {
            return sourceArray.get(position);
        }

        if (cachedDataSourceFactory == null) {
            DefaultHttpDataSourceFactory dataSourceFactory = new DefaultHttpDataSourceFactory("exoplayer-codelab");
            File cacheFile = new File(FrameworkUtil.getContext().getExternalCacheDir().getAbsolutePath(), "video");
            simpleCache = new SimpleCache(cacheFile, new LeastRecentlyUsedCacheEvictor(256 * 1024 * 1024)); 
            cachedDataSourceFactory = new CacheDataSourceFactory(simpleCache, dataSourceFactory);
        }

        MediaSource source = new ExtractorMediaSource.Factory(cachedDataSourceFactory).createMediaSource(uri);
        sourceArray.put(position, source);
        return source;
    }
```

Looks like it worked. Data speed plugin show 300kb/s, and it can play offline.
i want to know why it different.Especially on the data flow.

**Comment by christosts** [comment]
I don't fully understand the situation.

If you have a list of videos and keep sliding between videos, the player will download a video every time you slide to a new screen. Are you saying the player keeps downloading data after you have played a 2M video but stay at that screen?

In the second code snippet, you are caching (temporarily storing) on the device each video, so a video is downloaded from the network only the first time you play it. If you play the specific video again, it will not be dowloaded from the network but the player will use the copy from the cache.

**Comment by javalue** [comment]
> I don't fully understand the situation.
> 
> If you have a list of videos and keep sliding between videos, the player will download a video every time you slide to a new screen. Are you saying the player keeps downloading data after you have played a 2M video but stay at that screen?
> 
> In the second code snippet, you are caching (temporarily storing) on the device each video, so a video is downloaded from the network only the first time you play it. If you play the specific video again, it will not be dowloaded from the network but the player will use the copy from the cache.

yes,it waste downloading data more than video file size.And i don't know why DefaultHttpDataSourceFactory like that.

**Comment by christosts** [comment]
The fact that you see data usage going down when using a local cache means the videos are played more than once. So maybe the app is asking the player to do more things that just a play a video once.  For example, is the repeat mode on? Or, are you using the ConcateningMediaSource for a playlist anywhere in your app, which would make the player preload new items?

You may also want to verify what the data speed plugin shows. The player offers APIs that report the amount downloaded data. Can you attach an `AnalyticsListener` to the player and listen to `onLoadCompleted/onLoadCanceled/onLoadError` events as described in this [issue](https://github.com/google/ExoPlayer/issues/7401#issuecomment-631379803)?

**Comment by javalue** [comment]
> The fact that you see data usage going down when using a local cache means the videos are played more than once. So maybe the app is asking the player to do more things that just a play a video once. For example, is the repeat mode on? Or, are you using the ConcateningMediaSource for a playlist anywhere in your app, which would make the player preload new items?
> 
> You may also want to verify what the data speed plugin shows. The player offers APIs that report the amount downloaded data. Can you attach an `AnalyticsListener` to the player and listen to `onLoadCompleted/onLoadCanceled/onLoadError` events as described in this [issue](https://github.com/google/ExoPlayer/issues/7401#issuecomment-631379803)?

aha？Oh no, you means if I set repeat mode on,the data will be costed all the time?

**Comment by javalue** [comment]
i try to set addAnalyticsListener for player, i play my first video ,but log show onLoadCompleted 3times and onLoadStarted 4 times.

**Comment by christosts** [comment]
You can inspect what exactly the player is downloading by looking at the `LoadEventInfo` and `MediaLoadData` params passed from the callbacks. The LoadEventInfo contains the exact uri downloaded and the number of bytes. `LoadEventInfo.dataSpec` can give you the uri and position in the stream. From `MediaLoadData` you can see the downloaded piece's start and end time. This information should help you verify what exactly is being downloaded.

Videos are downloaded in pieces, so it's likely you are getting the events for individual pieces of the single file. However, I haven't understood how exactly your app is using the player, so I recommend you inspect the params of the events to verify for example the player is not downloading another file, or the same file more than once.

**Comment by ojw28** [comment]
> Oh no, you means if I set repeat mode on ,the data will be costed all the time?

Yes. The way to avoid this is to add a cache, as you did successfully in your initial post. So it seems like everything is working as intended here, and the question is answered?
