### ISSUE TITLE
Question: Does ProgressiveMediaSource save any file while playing from http url?

### ISSUE THREAD

**Issue by tigerss** [google/ExoPlayer#7402]
1. I have been searching on Stackoverflow, website, API docs but it's still not clear how does ProgressiveMediaSource behaves when playing video from external http url. Does it saves chunks into a file and then render that? Or it keeps chunks only in memory?

2. Also when playing a video in loop it downloads over and over again the video or it has a cache somewhere?

**Comment by christosts** [comment]
It depends how you construct the ProgressiveMediaSource. 

For example, if you use a DefaultHttpDataSourceFactory, it will create DataSources that fetch the video and keep it only in memory. Therefore, the ProgressiveMediaSource will download the video contents every time you play the file, and, in fact, it will likely download pieces of the same file within the same playback session more than once if you seek backwards.

However, if you create a ProgressiveMediaSource using a CacheDataSourceFactory, it will use CachingDataSources that download the video and store it locally on the device, so the video pieces will be downloaded only if they are not present in the cache (they have been downloaded before or perhaps they were evicted to make room for other chunks).

Let me know if you need more clarifications.
