### ISSUE TITLE
Exoplayer DRM Support

### ISSUE THREAD

**Issue by Serkan-Karacelikler** [google/ExoPlayer#7403]
Hello, how can I add DRM support based on the code below?
```
switch (type) {
            case C.TYPE_DASH:
                long livePresentationDelayMs = DashMediaSource.DEFAULT_LIVE_PRESENTATION_DELAY_PREFER_MANIFEST_MS;
                DefaultDashChunkSource.Factory dashChunkSourceFactory = new DefaultDashChunkSource.Factory(dataSourceFactory);
                // Last param is AdaptiveMediaSourceEventListener
                mediaSource = new DashMediaSource(uri, dataSourceFactory, dashChunkSourceFactory, retryCount, livePresentationDelayMs, mainHandler, null);
                break;
            case C.TYPE_HLS:
                // Last param is AdaptiveMediaSourceEventListener
                mediaSource = new HlsMediaSource(uri, dataSourceFactory, retryCount, mainHandler, null);
                break;
            case C.TYPE_SS:
                DefaultSsChunkSource.Factory ssChunkSourceFactory = new DefaultSsChunkSource.Factory(dataSourceFactory);
                // Last param is AdaptiveMediaSourceEventListener
                mediaSource = new SsMediaSource(uri, dataSourceFactory, ssChunkSourceFactory, mainHandler, null);
                break;
            default:
                ExtractorsFactory extractorsFactory = new DefaultExtractorsFactory();
                mediaSource = new ExtractorMediaSource(uri, dataSourceFactory, extractorsFactory, mainHandler, null);
                break;
        }
```

**Comment by christosts** [comment]
@AquilesCanta can you take a look?

**Comment by AquilesCanta** [comment]
To summarise, you need to inject a [DefaultDrmSessionManager](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/drm/DefaultDrmSessionManager.html) into the MediaSource you are using. The [best example I can give you](https://github.com/google/ExoPlayer/blob/7d3f54a375fac04a746ca76a8f2e1ad32c8b45b2/demos/main/src/main/java/com/google/android/exoplayer2/demo/PlayerActivity.java#L517) of this is the demo app. Try following what's done there. If you run into issues following this example, feel free to post a comment below and I'll reopen the issue. or just file a fresh bug including as much information as you can (something like "DRM doesn't work" will be closed immediately).

Final note: I'm assuming that you are aware of all the parts involved in DRM. For example:
- License server.
- Encrypted content.
- Most likely: Authentication.
