### ISSUE TITLE
Using SilenceMediaSource with shuffle mode enabled

### ISSUE THREAD

**Issue by yamagata1037** [google/ExoPlayer#7406]
I'm using a `SilenceMediaSource` to add a gap between tracks in a `ConcatenatingMediaSource`.
The problem I faced is that when shuffle mode is enabled, these gaps don't work as expected.
And there are also some problems related to it.
For example, `TimelineQueueNavigator` tries to create a `QueueItem` for just a gap.
These problems seem to be caused by `SilenceMediaSource` having its own `Window`.
Is it possible to create something like PaddingMediaSource that wraps another `MediaSource` and adds padding to the beginning and/or the end of it and has a single `Window`?
Or is there another way to solve these problems? Thank you.

**Comment by tonihei** [comment]
This will be possible once we implement #4868. This enhancement will allow you to merge multiple sources together as if they were only one item (=only one window). Doing that will allow nice interaction with UI, MediaSession, skipping items, etc. 

Marking as duplicate.
