### ISSUE TITLE
What library version is used on the demo that we download?

### ISSUE THREAD

**Issue by morfeo9950** [google/ExoPlayer#7408]
[No further info]

**Comment by ojw28** [comment]
If by "download" you mean cloning the git repository, as documented [here](https://exoplayer.dev/demo-application.html#getting-the-code), then you're getting and building both the demo app and the library as source code. So it depends on what branch or release tag you've checked out. If you just do
```
git clone https://github.com/google/ExoPlayer.git
```
then you'll get the release branch, which will contain the latest stable release. However after you've cloned the repository you can check out whatever version you want using release tags. For example:
```
git checkout r2.11.3
```
will give you the 2.11.3 library and the corresponding demo app that uses it.
