### ISSUE TITLE
Mi Box S: 90% frame drops on 9XXp60 but OK for 1080p60

### ISSUE THREAD

**Issue by fgl27** [google/ExoPlayer#7411]
### [REQUIRED] Issue description

When playing 9XXp60 content the player will constantly drop frames, when playing the same content but on higher quality 1080p60 and higher bitrate no problem.

After some time paying the problematic video the audio start to get out of sync as more one whatch more out of sync it gets.

The app can check codecs capability and allow user to enable and disable them, bellow is a image showing the capability of the avc decoder available:

![device_avc_decoders](https://user-images.githubusercontent.com/13755892/82634787-1328c600-9bd5-11ea-95fb-04ad3370b3b9.png)

On the test made only the HW codec was enable, SW codecs have even worst performance.

I know this is probably a device issue, but maybe is something that can be improve after all the device is capable of play same type of content on higher quality.

This issue have started after the device received android 9 update, is not possible to revert the OS so I can't confirm the old OS is OK.

This is a similar issue to https://github.com/google/ExoPlayer/issues/7294 but on a different device.

### [REQUIRED] Reproduction steps

Play the shared links on defected devices, constant frame drop.

### [REQUIRED] Link to test content

**Defected videos:**
HLS VOD 998p60 bitrate 6.41 Mbps:
https://d2nvs31859zcd8.cloudfront.net/96e878ed8a302fd1f15b_koil_38183634672_1455351108/chunked/index-dvr.m3u8

![vod_codec_info](https://user-images.githubusercontent.com/13755892/82634635-985fab00-9bd4-11ea-90a5-af1b15527028.png)

MP4 clip 998p60 
https://clips-media-assets2.twitch.tv/AT-cm%7C719320743.mp4
![mp4_codec_info](https://user-images.githubusercontent.com/13755892/82634670-bfb67800-9bd4-11ea-92b7-4536a9bc8adf.png)

**OK video (for comparison):**
HLS VOD 1080p60 bitrate 8.41 Mbps
https://d2nvs31859zcd8.cloudfront.net/a0ea2ae0dd343bcc6cce_summit1g_38183932656_1455369742/chunked/index-dvr.m3u8

![ok_vod_codec_info](https://user-images.githubusercontent.com/13755892/82634712-dfe63700-9bd4-11ea-9e80-ffdac2f315aa.png)

### [REQUIRED] A full bug report captured from the device

[bugreport-oneday-PI-2020-05-22-00-37-21.zip](https://github.com/google/ExoPlayer/files/4666236/bugreport-oneday-PI-2020-05-22-00-37-21.zip)

On the above I played it of the above videos for about 30/40 seconds.

### [REQUIRED] Version of ExoPlayer being used
dev-v2 branch

### [REQUIRED] Device(s) and version(s) of Android being used

Xiaomi Mi box S running android 9

**Comment by christosts** [comment]
Can you please check the status of the 9XXp60 stream? Chunk downloads return HTTP  403.

**Comment by fgl27** [comment]
I don't control the content it may have expired or was removed. The clip is from the stream use that for a test as it produce the same problem.

I share a new working vod later.

**Comment by fgl27** [comment]
New VOD links

**Defected videos:**
HLS VOD 998p60 bitrate 6.41 Mbps:
https://d2nvs31859zcd8.cloudfront.net/4862214b132a73a6ac53_koil_38285374704_1461717311/chunked/index-dvr.m3u8

**OK video (for comparison):**
HLS VOD 1080p60 bitrate 8.41 Mbps
https://d2nvs31859zcd8.cloudfront.net/bdb4126bea8947bf773d_summit1g_38245992016_1459252067/chunked/index-dvr.m3u8

This also may expire after a few days, so let me know if new links are needed, the clips link will probably last for longer.

**Comment by ojw28** [comment]
The first link doesn't work for me (the manifest itself is accessible, but the segments are not). The second link is currently working correctly. Please could you provide a set of working links? Thanks.

**Comment by fgl27** [comment]
Some links expire after a amount of days, odd that only the TS aren't accessible.

I can keep updating once every two days the links.

This are working for me...

**Defected video:**
HLS VOD 998p60 bitrate 6.4 Mbps:
https://d2nvs31859zcd8.cloudfront.net/31f52ae479c351d185c8_koil_38405013248_1469205309/chunked/index-dvr.m3u8

**OK video (for comparison):**
HLS VOD 1080p60 bitrate 8.4 Mbps
https://d2nvs31859zcd8.cloudfront.net/6a0abb5fd2c2586c5848_summit1g_38366249920_1466779205/chunked/index-dvr.m3u8

I update again in two days or so.

**Comment by ojw28** [comment]
I tried this on an MiBox 3 and the 998p stream works fine. It's running Android 8 and there's no upgrade available for it. I guess that's not particularly useful information :).

I should have a MiBox S available to test with on Wednesday. I'll ping this issue for new streams when I get it setup.

**Comment by fgl27** [comment]
I don't have the older version of the box, but the new on android 8 didn't had issues, I assume that is a android 9 only issue on those devices.

Is good that you manage to get a device, that is a very popular device at least from the analytics of the TV only apk I share, I see it as 2 most used device with is 10+% of active devices, second only to Sony Bravia.

My come with android 8.1, that was almost a year ago and all works OK, after android 9 update I notice issue, but only after a few month on it.

If yours also comes like that and you have the time to test 8.1 versus after update that will be great.

As I use the device on the daily basis, I don't try a downgrade as the process is not [ a friendly process](https://piunikaweb.com/2020/01/30/mi-box-s-pie-bug-report-oreo-downgrade/#:~:text=The%20bootloader%20of%20Mi%20Box,but%20there%20is%20a%20catch!&text=It%20is%20possible%20to%20flash,via%20low%20level%20Amlogic%20flasher.).

**Comment by fgl27** [comment]
As clips links don't expirer as the VOD do, here is a list of a few, plus some other VOD that may take more time to expire:

**Defected MP4:**

- 998p60 https://clips-media-assets2.twitch.tv/38306572304-offset-2318.mp4
- 936p60 https://clips-media-assets2.twitch.tv/AT-cm%7C741846235.mp4
- 900p60 https://clips-media-assets2.twitch.tv/AT-cm%7C732178007.mp4

**Defected VOD:**

- 998p60 https://d2nvs31859zcd8.cloudfront.net/a43b7e837d00a2057ccd_koil_38509172992_1475728676/chunked/index-dvr.m3u8
- 936p60 https://d2nvs31859zcd8.cloudfront.net/9d4d17a9778b95be2e17_sacriel_1876121361_117319924/chunked/index-dvr.m3u8
- 900p60 https://d2nvs31859zcd8.cloudfront.net/de7a00f1730d2e8dafb2_smoke_38517754416_1476268403/chunked/index-dvr.m3u8

**OK video (for comparison):**

- 1080p60 MP4 https://clips-media-assets2.twitch.tv/AT-cm%7C731155634.mp4
- 1080p60 VOD https://d2nvs31859zcd8.cloudfront.net/652a2959a819c58bfafd_summit1g_38521698608_1476515189/chunked/index-dvr.m3u8

**Comment by fgl27** [comment]
One thing I notice is that the 900p60 takes more time to show the issue 10 to 30s, the others is practically instantaneous.

Also when I use `app:surface_type="texture_view"` the problem is there I can visually notice it, but the dropped frame counter doesn't work, maybe is intentional this type of surface doesn't support the listener or something related.

**Comment by ojw28** [comment]
I was able to reproduce the problem. My device came with Android 9 pre-installed, so I wasn't able to test whether it worked with Android 8. I agree it's a device specific problem, and I've reported the issue to Xiaomi [Internal ref: b/158212014]. I will let you know if/when we hear back.

**Comment by fgl27** [comment]
OK thanks for the help.

**Comment by ojw28** [comment]
Xiaomi have a fix for this issue. My understanding is that it should roll out some time this month.

**Comment by fgl27** [comment]
OK, Thank you.
I complement here when I manage to test they update.
