### ISSUE TITLE
How to hide skip ads button from IMA ads player

### ISSUE THREAD

**Issue by gautamlook** [google/ExoPlayer#7415]
Hi support,

I want to hide skip button from ads even if passed by the vast tag. is it possible? please reply as soon as possible.

**Comment by andrewlewis** [comment]
I think this isn't possible, as in general customizing the ad overlay UI is against the IMA SDK policy (see [this thread](https://groups.google.com/forum/#!searchin/ima-sdk/customize$20skip%7Csort:date/ima-sdk/c9Ed45PedFk/dErEDgndIQAJ)). If the ad tag specifies that the ad is skippable, the user should be able to skip it.

**Comment by ojw28** [comment]
This is already documented [here](https://exoplayer.dev/ad-insertion.html). Removing documentation candidate label. I will also add some specific examples to the documentation of things that cannot be customized.
