### ISSUE TITLE
Overlapping GLSurfaceView on SurfaceView and vice versa

### ISSUE THREAD

**Issue by chitrang200889** [google/ExoPlayer#7418]
ExoPlayer - SurfaceView

Camera2 + MediaCodec - GLSurfaceView

I am using the above view groups for playing video and camera recording.

**UI-1:** **Exo-Surf** at the center and **Cam-GLS** in the top right corner.

**UI-2:** **Cam-GLS** at the center and **Exo-Surf** in the top right corner.

![20200522_210750](https://user-images.githubusercontent.com/4860999/82719679-b5e75000-9c7a-11ea-9dc0-a024460ef8b9.jpg)

To achieve this I am using setZOrderOnTop to set z-index, as both are inside RelativeLayout.

`(exoPlayerView.videoSurfaceView as? SurfaceView)?.setZOrderOnTop(true/false)`

It seems working fine on Samsung S9+ with API 29 - Android 10, and also for API 28.

But for API 21-27, it behaves with some random issues.

- Dash-A top part of SurfaceView/GLSurfaceView is not visible
- Dash-B bottom part of SurfaceView/GLSurfaceView is not visible
- Entire SurfaceView / GLSurfaceView becomes completely transparent in the top right corner

I also tried using setZOrderMediaOverlay but no luck.

I am sure two surface view works together as Whatsapp and google duo apps are using them in video calls. But I am wondering if GLSurfaceView is causing an issue "something about locking the GL thread" as commented below in [this answer](https://stackoverflow.com/a/22746240/3598052).

**Comment by andrewlewis** [comment]
Have you tried using `TextureView` on those older API versions? I don't have an explanation for what's going on but `TextureView` is rendered/composited like a normal view so using that in conjunction with a single `GLSurfaceView` may work.

There is some information about `TextureView` and media playback [here](https://exoplayer.dev/ui-components.html#choosing-a-surface-type). Generally we advise using `SurfaceView` where possible, but using `TextureView` on older API versions where it's necessary due to platform limitations seems fine.

**Comment by chitrang200889** [comment]
Yes, I tried TextureView and seems working fine on all API levels. 

But I am wondering what possible issues will occur if TextureView is used. Because I see more issues related to TextureView in this section.

"More accurate frame timing, resulting in smoother video playback." which is not applicable to TextureView I guess. So the major concern was about exact seeking as it is necessary for our app. Will it work properly with TextureView?

**Comment by andrewlewis** [comment]
Exact seeking should work fine with `TextureView`, and I wouldn't anticipate other issues apart from the ones implied by the `SurfaceView` benefits listed on that page.

Given it appears to work correctly from API 28, you could restrict use of `TextureView` to older API versions, at the cost of needing to maintain the two implementations.
