### ISSUE TITLE
unable to play HLS streaming with .m3u8 in some devices (only audio no video is shown) 

### ISSUE THREAD

**Issue by ashwithraja** [google/ExoPlayer#742]
It seems that exoplayer is not able to play HLS streaming with .m3u8 in some devices like micromax canvas hd and Lava iris. I could not find the root cause for this issue as it is not throwing exception and also  only audio comes no pictures visible. Initially i thought that the issue is with the device codec but i verified that the issue is with exoplayer. I could play HLS video with .m3u8 in the default player of the device but the same URL does not play in exoplayer. Same behaviour is observed in the sample provided by the exoplayer. Kindly provide me the solution to resolve this.

**Comment by ojw28** [comment]
If this is still an problem, please file a fresh issue with all of the information requested in the issue template. There is not enough information provided here for us to investigate further.
