### ISSUE TITLE
Question: Copy cached video to file

### ISSUE THREAD

**Issue by tigerss** [google/ExoPlayer#7424]
I would like a review for the code below to copy from cache to file and also leave this for future reference in case someone else is looking if the code is correct. Thanks!

I found a suggestion to use the TeeDataSource to [copy from cache to file](https://github.com/google/ExoPlayer/issues/6745#issuecomment-566179054)

```
DataSpec dataSpec = new DataSpec(videoUri);

// Build cache
SimpleCache simpleCache = new SimpleCache(
                new File(getCacheDir(), "video"),
                new LeastRecentlyUsedCacheEvictor(30 * 1000 * 1000),
                new ExoDatabaseProvider(context));

// Build data source factory with cache enabled, if data is available in cache it will return immediately, otherwise it will open a new connection to get the data.
CacheDataSource cacheDataSource = new CacheDataSourceFactory(
                simpleCache,
                new DefaultDataSourceFactory(
                        context,
                        Util.getUserAgent(context, "app")))
                .createDataSource();

TeeDataSource teeDataSource = new TeeDataSource(cacheDataSource, new FileDataSink(outputFile));

int read, progress;
long total, currentBytesCount = 0;
byte[] bytes = new byte[1024];

total = teeDataSource.open(dataSpec);
while ((read = teeDataSource.read(bytes, 0, bytes.length)) != C.RESULT_END_OF_INPUT) {
   currentBytesCount += read;
   progress = (int) (((double) currentBytesCount / total) * 100);
}
```

FileDataSink - writes data to file
```
public class FileDataSink implements DataSink {

    private File file;
    private FileOutputStream fileOutputStream;

    public FileDataSink(File file) {
        this.file = file;
    }

    @Override
    public void open(DataSpec dataSpec) throws IOException {
        fileOutputStream = new FileOutputStream(file, false);
    }

    @Override
    public void write(byte[] buffer, int offset, int length) throws IOException {
        fileOutputStream.write(buffer, offset, length);
    }

    @Override
    public void close() throws IOException {
        fileOutputStream.close();
    }
}
```

**Comment by marcbaechinger** [comment]
If the `TeeDataSource` works for you like this this looks ok to me. 

If the use case is to cache this without playback, I think you can have that a bit easier if you are using the [`CacheUtil`](https://github.com/google/ExoPlayer/blob/76962d50f1d80941d6768e4e765fa4ff010705e7/library/core/src/main/java/com/google/android/exoplayer2/upstream/cache/CacheUtil.java#L120). You are currently reading from the `TeeDataSource` manually. The `CacheUtil` would probably help you with this:

```
TeeDataSource teeDataSource = new TeeDataSource(
   defaultDataSource, // no need for CacheDataSource which is created by the CachUtil
   new FileDataSink(outputFile));

 CacheUtil.cache(
    dataSpec, // construct this with your url and a DataSpec.Builder
    simpleCache,
    /* cacheKeyFactory= */ null,
    teeDataSource,
    /* progressListener= */ null,
    /* isCancelled= */ null);
```

**Comment by tigerss** [comment]
Thanks for the suggestion. My use case is video editing: step 1 the user selects/plays a video, then in step 2 I will do some processing on the video (crop,resize,etc). So the video is in most cases partially played. In step 2 I would like to copy the video from cache to a file for processing.

The code you suggested seems to cache but not copy to the outputFile, or I did something wrong. Can you confirm that it should also copy to the output file?
