### ISSUE TITLE
Any information/roadmap of when issue #7207 will be released in production?

### ISSUE THREAD

**Issue by ghost** [google/ExoPlayer#7425]
### [REQUIRED] Searched documentation and issues
This issue solves the problem that is stopping us form updating Wowza to 4.8
https://github.com/google/ExoPlayer/issues/7207

I have tried to search for a public roadmap of when the different bug fixes are going to be merged from development to production, but I cannot find any such information.

I see that the question of a roadmap has been answered before, does that mean that you are not answering these kind of questions?
https://github.com/google/ExoPlayer/issues/3711

### [REQUIRED] Question
We need to update our Wowza to version 4.8 but then ExoPlayer will stop working.
This issue seems to fix the problem:
https://github.com/google/ExoPlayer/issues/7207

Any information of when it will be released?

**Comment by ojw28** [comment]
It should be in 2.11.5, which will hopefully go out next week.

As an aside, if you have a question about an existing issue, please ask it on the issue, rather than failing a new one (unless it's been locked, but that's not the case here).
