### ISSUE TITLE
Understanding Exoplayer BUFFERING and READY state

### ISSUE THREAD

**Issue by krackjack234** [google/ExoPlayer#7427]
### [REQUIRED] 
Searched documentation and issues but have few doubts

### [REQUIRED]  
Have below questions on the behavior of exoplayer and its different state transitions

1. Can the player starts playing when it is in STATE_BUFFERING state and not in STATE_READY state but playWhenReady is true? I think this can happen if player has downloaded minimum duration of data but has not reached the max buffer limit. Please confirm.

2. If the player was paused after initialisation then can it still can it reach READY state with playWhenReady as false i.e. will exoplayer still continue to load data in background but not play anything?

Any pointers on these 2 questions will be helpful.

**Comment by marcbaechinger** [comment]
Regarding question 1) The player doesn't start rendering when in `STATE_BUFFERING`. The player starts playing when in `STATE_READY`. 

You are correct for question 2) in saying that the player downloads data even when `playWhenReady==false`. When the player is prepared, it transitions from `STATE_IDLE` to `STATE_BUFFERING` until enough data is available to transition to `STATE_READY`. This happens regardless of `playWhenReady` being true or false.

In general the player state (IDLE|BUFFERING|READY|ENDED) and `playWhenReady` are independent.

As an aside: There is a method [`player.isPlaying`](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/Player.java#L433) and a callback `Player.EventListener.onIsPlayingChanged()`. This gives you a boolean which reports whether the player is actually playing media.

**Comment by krackjack234** [comment]
Thanks. 

Can it happen that the client gets **onRenderedFirstFrame** callback first before READY state is reported in **onPlayerStateChanged** callback?

**Comment by marcbaechinger** [comment]
When I try with the most recent code (dev2 branch) it looks like you can not rely on the one arriving before the other. I've seen these event arrive in the logs in a different order at least when I play offline vs. streamed content.

It seems like for streamed content (normal case) it's like you say that the `onFirstFrameRendered` is called before `onPlayerStateChanged` (former is called by the renderer while latter is called from the internal player).

I wonder though if this works as intended. I need to investigate this some further whether this can/should be deterministic. I will look into this.

If I can help you in the meanwhile, what do you try to achieve?

**Comment by ojw28** [comment]
> I wonder though if this works as intended.

It is working as intended. `STATE_READY` is [defined as](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/Player.html#STATE_READY):

> The player is able to immediately play from its current position. 

This would include both the audio and video parts of the stream being ready for playback. Independently to that, the first video frame will always be rendered as soon as it's possible. So there's no guaranteed ordering between the two. I don't think you should ever need to rely on there being a particular order, so if you're trying to, it's likely you're doing something wrong or unnecessary.

Regarding the original question, the Javadoc (linked above) defines `STATE_READY` and `STATE_BUFFERING` very unambiguously. Please always check the documentation before filing issues.

**Comment by krackjack234** [comment]
Actually we need to log 2 events for analytics: 1> when player is ready to play (but may be paused because of Ads playing, ima sdk is used here ) 2> when player has actually rendered 

So we were relying on READY_STATE and onFirstFrameRendered callback to track these 2 events

**Comment by marcbaechinger** [comment]
Depending on what semantics your analytics want to log, you probably want to look into the `onIsPlayingChanged()` callback as well. It reports a change in `player.isPlaying()`. Please consult the java doc of [isPlaying](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/Player.java#L712) about what this means.

**Comment by TakuSemba** [comment]
Can I ask a question regarding to onRenderedFirstFrame/onPlayerStateChanged

> It seems like for streamed content (normal case) it's like you say that the onFirstFrameRendered is called before onPlayerStateChanged (former is called by the renderer while latter is called from the internal player).

While I understand these two do not depend on each other, in a weak network condition, I can confirm there is a huge gap between onRenderedFirstFrame and onPlayerStateChanged. I thought network condition is not supposed to affect the gap between these calls and I could not figure out why this happens.

```
emulator -avd Pixel_2_API_29 -netspeed 128 -read-only
```

```
EventLogger  D  decoderInitialized [2.59, 5.00, window=0, period=0, video, OMX.google.h264.decoder]
EventLogger  D  decoderInputFormatChanged [2.59, 5.00, window=0, period=0, video, id=1, mimeType=video/avc, bitrate=300000, codecs=avc1.4D401F, res=426x240]
EventLogger  D  videoSizeChanged [2.91, 5.00, window=0, period=0, 426, 240]
EventLogger  D  surfaceSizeChanged [2.91, 5.00, window=0, period=0, 1080, 608]
EventLogger  D  renderedFirstFrame [2.93, 5.00, window=0, period=0, Surface(name=null)/@0x4d6565c]
EventLogger  D  state [4.30, 5.00, window=0, period=0, true, READY]
```

**Comment by marcbaechinger** [comment]
Like @ojw28 stated above about when the player transitions to `STATE_READY`:

> This would include both the audio and video parts of the stream being ready for playback.

Accordingly this means that if the player is configured to wait until X milliseconds of media is available, the first frame can be rendered before this condition is met. In a slow network this gap can increase as you observed.

**Comment by krackjack234** [comment]
hi @marcbaechinger , a follow up question on this. 

In exoplayer we have a minimum buffer size (DEFAULT_BUFFER_FOR_PLAYBACK_AFTER_REBUFFER_MS) after which first frame will get rendered and also a max buffer size (DEFAULT_MAX_BUFFER_MS) till which it will buffer before stopping.

Will the player reach STATE_READY after reaching DEFAULT_MAX_BUFFER_MS ?

**Comment by ojw28** [comment]
The Javadoc for the states is defined clearly:

> STATE_READY - The player is able to immediately play from its current position.

It should be clear that the ability to play is not tied to the buffer reaching its maximum possible size. So you'd expect `STATE_READY` to come before the maximum buffer duration is reached in most cases. The ability to play _is_ tied to `DEFAULT_BUFFER_FOR_PLAYBACK_MS`:

> DEFAULT_BUFFER_FOR_PLAYBACK_MS - The default duration of media that must be buffered for playback to start or resume following a user action such as a seek, in milliseconds.

So you'd expect `STATE_READY` to happen around the point at `DEFAULT_BUFFER_FOR_PLAYBACK_MS` of media has been buffered (or `DEFAULT_BUFFER_FOR_PLAYBACK_AFTER_REBUFFER_MS` after a re-buffer).

There is no guarantee on the ordering of these events though, and I can't really envisage a valid case where you'd ever need to rely on one.
