### ISSUE TITLE
Add background audio-only ads to ExoPlayer IMA extension

### ISSUE THREAD

**Issue by inProjects** [google/ExoPlayer#7428]
In addition to the great extension of SimpleExoPlayerView , Can you add similar extension to exoplayer that will allow playing **audio-only ads in background** with integration of audio tracks. Something like createAudioAdDisplayContainer that is used in this [sample](https://github.com/googleads/googleads-ima-android/tree/master/audioplayerexample).
Thanks.

**Comment by andrewlewis** [comment]
The IMA extension now supports audio-only ads. See acc8453628b250318f39b03e15a9f2dee3bcb0cc and #7689.
