### ISSUE TITLE
exo player mp2, aac audio format and avi video format

### ISSUE THREAD

**Issue by hakancess** [google/ExoPlayer#7429]
![error](https://user-images.githubusercontent.com/63077154/82947743-29ee6480-9fa9-11ea-82fd-598640458bbe.jpeg)
I use exoplayer but no sound from mp2 and aac audio formats in android application.

I get this error when I open mp2 and aac audio format videos "media includes audio tracks but none 

are playable by this device"and some are not working in .avi format, some are working please can you help me

![image](https://user-images.githubusercontent.com/63077154/82934400-171d6500-9f94-11ea-8edf-9a703dee66e5.png)

**Comment by marcbaechinger** [comment]
Can you please send us a link to the stream so we can investigate this more closely? If you don't want to send this in public you can send it to dev.exoplayer@gmail.com using a subject in the format "Issue #7429".

Creating a bug report and upload/mail to us would be helpful as well to speed up investigation. Ideally you have the `EventLogger` in use which gives us a good picture of what the player is doing.

**Comment by hakancess** [comment]
There is no problem with flow file, just exoplayer problem

**Comment by marcbaechinger** [comment]
I would like to investigate if it's an ExoPlayer problem, so we can fix that if that's the case. For this purpose we would need the stream so we can see why it does not work.

Can you please send us a link to the stream so we can investigate this more closely? If you don't want to send this in public you can send it to dev.exoplayer@gmail.com using a subject in the format "Issue #7429"
