### ISSUE TITLE
HLS - Support EXT-X-START tag

### ISSUE THREAD

**Issue by androidCoder** [google/ExoPlayer#744]
We would like to use a specific tag within the hls master playlist, which was introduced with protocol version 6: EXT-X-START (https://tools.ietf.org/html/draft-pantos-http-live-streaming-16#section-4.3.5.2)

My general question is now, whether there is a specific protocol version implemented within the ExoPlayer HLS implementation or is there is protocol independent support for certain tags?

And as a specific question, whether there is support for the EXT-X-START tag already in place or planed for integration?

Thanks for your help.

**Comment by endlessmind** [comment]
Looking at the HlsPlaylistParser.java (https://github.com/google/ExoPlayer/blob/master/library/src/main/java/com/google/android/exoplayer/hls/HlsPlaylistParser.java)
it appears that EXT-X-START is not supported at this time

**Comment by endlessmind** [comment]
Because I'm bored, I can give it a shot, if you can supply me with a hls master playlist that contains the EXT-X-START tag.

**Comment by androidCoder** [comment]
Hello @endlessmind! Thanks for your response! I would really appreciate, if this feature could be integrated. You can find two sample streams here, one having the EXT-X-START tag within the masterplaylist (https://dl.dropboxusercontent.com/u/69373833/stream/offsetInMaster.m3u8) with a start offset of 20 seconds, and another one having the tag within the subplaylist ( https://dl.dropboxusercontent.com/u/69373833/stream/master.m3u8).

Thanks in advance!

**Comment by cskinfill** [comment]
Any traction on this?

**Comment by ojw28** [comment]
Support has been merged to `dev-v2` in https://github.com/google/ExoPlayer/commit/28e117d25fb211b18a815b961135b78e7a18abdb.
