### ISSUE TITLE
ExoPlayerImplInternal: Renderer error

### ISSUE THREAD

**Issue by Cencodes** [google/ExoPlayer#7440]
Hi Exoplayer Team,

We are deploying OTT in the production environment. So for the application we are using exoplayer version 2.11.4. Currently we have been testing the application and observed that for some Android devices DRM enabled VOD contents cannot play. For some mobile devices it is able to play. I have listed the mobile devices below which we cannot play the DRM contents.

- Xiaomi Note 10

- Samsung A71

I was able to get the client logs for the above devices and observed the below error.
```
2020-05-28 19:10:43.837 4647-5334/? E/ExoPlayerImplInternal: Renderer error: index=0, type=video, format=Format(video=900034, null, null, video/avc, avc1.64001E, 900034, null, [854, 480, 25.0], [-1, -1]), rendererSupport=NO_UNSUPPORTED_DRM
      com.google.android.exoplayer2.ExoPlaybackException: android.media.MediaCodec$CodecException: Error 0x80000000
        at t60.a(SourceFile:32)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.a(SourceFile:40)
        at d70.a(SourceFile:139)
        at d70.handleMessage(SourceFile:18)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:201)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: android.media.MediaCodec$CodecException: Error 0x80000000
        at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
        at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:2608)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.y(SourceFile:83)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.a(SourceFile:27)
        at d70.a(SourceFile:139) 
        at d70.handleMessage(SourceFile:18) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:201) 
        at android.os.HandlerThread.run(HandlerThread.java:65)
```
Would appreciate if you could share your thoughts on this.

Thanks.

**Comment by marcbaechinger** [comment]
As you say this seems to be a device specific problem caused by the secure codec. I understand you only see client logs. But for proper investigation we would need a full bug report.

Can you get your hands on such a device and provide us with such a bug report by uploading it here?

**Comment by Cencodes** [comment]
Hi,
I was able to collect a full log of a working device and a non working device. I have attached them here. Hope this might be helpful.
Thanks.
[Not Working Device.txt](https://github.com/google/ExoPlayer/files/4702031/Not.Working.Device.txt)
[Working Device.txt](https://github.com/google/ExoPlayer/files/4702032/Working.Device.txt)

**Comment by jt64** [comment]
Hi Cencodes, thank you for the files. The files you attached are logs from the application and do not contain the system level information we need to investigate the problem in the framework. What we need are system level bugreports, please see the [Android Studio developer page](https://developer.android.com/studio/debug/bug-report) that describes how to collect one.

Thanks!

**Comment by hpsoar** [comment]
same issue Huawei P20, android 10

**Comment by hpsoar** [comment]
> same issue Huawei P20, android 10

After debuging, found that it's because a wrong codec is used.

```   
/*
 * got two codecs:
 * OMX.hisi.video.decoder.avc
 * c2.android.avc.decoder
 */
List<MediaCodecInfo> decoderInfos =
        mediaCodecSelector.getDecoderInfos(
            mimeType, requiresSecureDecoder, requiresTunnelingDecoder);

/*
 * choosed c2.android.avc.decoder, because my video size is 128x96.
 */
decoderInfos = MediaCodecUtil.getDecoderInfosSortedByFormatSupport(decoderInfos, format);
```
however, it seems that `c2.android.avc.decoder` does not work on my device properly.

**Comment by hpsoar** [comment]
> same issue Huawei P20, android 10

In my case, some m3u8 stream works on my device, some doesn't. 
So I debugged and compared them.

**Comment by jt64** [comment]
ojw28, this looks like  a codec or exoplayer issue since it is selecting the wrong codec. Can you take a look?

**Comment by ojw28** [comment]
I think there are two issues here:

* The original one, for which we still need a bug report. The correct decoder seems to be selected in the snippet of logging provided.
* Whatever issue @hpsoar is seeing, which is not described in enough detail. It could be that `OMX.hisi.video.decoder.avc` claims that it's unable to support video sizes under a particular resolution, but there's not enough information here to really tell. @hpsoar - If you'd like us to take a look then please file a new issue containing a more detailed description of why `OMX.hisi.video.decoder.avc` is not being selected, and properly filling out the issue template. Thanks!

Let's use this issue to track the original issue, for which we still need a bug report. Keeping the "needs more info" accordingly.

**Comment by ojw28** [comment]
For the issue @hpsoar is seeing, I think the very low resolution (128x96) is probably below the minimum resolution supported by the hardware decoder. I think this means that very low resolution videos need to use L3 DRM (or no DRM) in practice.
