### ISSUE TITLE
Start renderer after video preroll is completed - For AV content. 

### ISSUE THREAD

**Issue by harini113** [google/ExoPlayer#7447]
Feature description: 
Decoder needs to fill up decoded picture buffer (DPB) list and handle display re-ordering of buffers before decoder can output any buffer for render purpose. Time to produce first decoder output for render purpose = frame decoding time x number of frames decoder needs to decode as pre-roll. This pre-roll time can vary based on underlying decode HW capability. Example: Decoder HW max capability is UHD@60fps. Hence, HW will take average 16 ms to decode one frame. If we consider 5 DPB buffers as pre-roll, then it will take 5x16=80 ms before any output arrives at player level for render purpose. If player starts audio decoding and video sample decoding at same time, in most of cases decoded audio sample for render purpose will arrive first. However, video output for render purpose will come later due to pre-rolling. Hence, it will lead to AV sync gap.

Recommendation to start render (AV sync timer) once first sample of video & audio both arrives. This logic should be present for start of player as well as at every seek operation. (After every seek, decoder again needs to build pre-roll buffers as well).

**Comment by andrewlewis** [comment]
Could you give some more details on the specific change to ExoPlayer this is requesting? Generally, we queue as many input buffers to `MediaCodec` as possible, and we release video output frames timed based on the `AudioTrack` timestamp to synchronize audio and video. We start the audio track playing only once audio/video renderers are reporting that they are ready (this condition includes having rendered the first video frame and having pending data for the `AudioTrack`).

Side note: on Android I think there is currently no guarantee that a `MediaCodec` fills its first output buffer as soon as it has enough information to do so (so for example you may have to queue several input buffers before the first frame corresponding to an IDR input frame is output in an H.264/AVC stream).
