### ISSUE TITLE
AudioTrackPositionTracker returns negative timestamps after reset

### ISSUE THREAD

**Issue by tonihei** [google/ExoPlayer#7456]
### [REQUIRED] Issue description
`AudioTrackPositionTracker` sometimes returns a negative timestamps immediately after a reset (e.g. at the start of playback, or after a seek). This causes the `rendererPositionUs` in `ExoPlayerImplInternal` to be negative, which in turn violates other assumptions the player and the renderers make about the position. This issue was originally reported in #7449. The PR proposed a workaround for this problem for the total buffered duration specifically, but it should ideally be fixed closer to the root cause.

### [REQUIRED] Reproduction steps
Play "Apple TS media playlist" in the demo app and add logging similar to [this one](https://github.com/fgl27/ExoPlayer/commit/6601c6435540ef7bf3ae25259d20ddffbd03eebc). The issue doesn't happen after all resets, but only occasionally. 

### [REQUIRED] Link to test content
"Apple TS media playlist" in the demo app

### [REQUIRED] A full bug report captured from the device
Not relevant. 

### [REQUIRED] Version of ExoPlayer being used
dev-v2 

### [REQUIRED] Device(s) and version(s) of Android being used
Pixel 4, Android 11.  Probably unrelated.

**Comment by ojw28** [comment]
Should be fixed by the commit ref'd above.
