### ISSUE TITLE
RESIZE_MODE_ZOOM or RESIZE_MODE_FIXED_HEIGHT don't keep aspect ratio

### ISSUE THREAD

**Issue by tprochazka** [google/ExoPlayer#7459]
Basically I need to display 16:9 movie to fullscreen on 19:10 screen. So set height to maximum and crop on both sides. 

I tried to use
```
  /**
   * The height is fixed and the width is increased or decreased to obtain the desired aspect ratio.
   */
  public static final int RESIZE_MODE_FIXED_HEIGHT = 2;
```
or
```
  /**
   * Either the width or height is increased to obtain the desired aspect ratio.
   */
  public static final int RESIZE_MODE_ZOOM = 4;
```
Both modes should keep aspect ration according to documentation, but it doesn't happen.
Both just stretch video to fill the whole screen, so it is deformed.

I tried also
`player.setVideoScalingMode(C.VIDEO_SCALING_MODE_SCALE_TO_FIT_WITH_CROPPING);`
but it does nothing.

I just added `playerView.setResizeMode(AspectRatioFrameLayout.RESIZE_MODE_FIXED_HEIGHT);` at the end of `initializePlayer()` method.

I tested it on your demo app directly with this stream
https://storage.googleapis.com/wvmedia/clear/vp9/tears/tears_hd.mpd

Tested with commit 7d3f54a3 in release-v2 branch.

**Comment by tprochazka** [comment]
Update.

So it is not a common issue, it works for other devices. The issue is only on this [android box](https://www.gearbest.com/tv-box/pp_009170053505.html). :-(

There is Android 9. I tested it on Samsung S8+ where is also  A9 and on Sony Android TV, where is A8 and it works there. Do you have an idea what can be different in this Android box, that it ignore aspect ration of the movie?

**Comment by andrewlewis** [comment]
As this appears to be device-specific, please raise a bug with the device manufacturer. I'm not sure what they might be doing differently. If there isn't already a compatibility test for this in Android CTS, I'll ask the media framework team if they can add one.

**Comment by andrewlewis** [comment]
For the record I've referenced this issue in [Internal: b/34159087], for tracking adding a CTS test.
