### ISSUE TITLE
Player View overlap when rotating

### ISSUE THREAD

**Issue by dukaenea** [google/ExoPlayer#7463]
### Searched documentation and issues
I have already looked at [#5714](https://github.com/google/ExoPlayer/issues/5714) but the solution provided there looks more like a workaround rather than a proper solution. I followed the proposed workaround but it does not work in my case. 

###  Question
I have created an `Activity` containing a `ViewPager`.
Inside the `ViewPager` I put `View`s which can be `ImageView`s or `PlayerView`s.
Every setting of the `ExoPlayer` is left to default.
When I try swiping from one page to the other everything is fine. The issue described in [#5714](https://github.com/google/ExoPlayer/issues/5714) does not happen in my case even if I use ` app:surface_type="surface_view"` instead of the suggested  ` app:surface_type="surface_view"`. However, the overflow happens at the moment when I rotate the device, either when I have just rotated it or when I have rotated it and swiped several times.

![ezgif com-resize](https://user-images.githubusercontent.com/34164912/83693842-25542c80-a5f7-11ea-8cf4-afa58615f2b3.gif)

### Link to test content
The videos used are simple screen recordings

### Version of ExoPlayer being used
Using ExoPlayer Core and ExoPlayer UI version 2.8.2

### Device(s) and version(s) of Android being used
Tested on various phones, all reproduce errors. Min SDK is set to 23.

**Comment by andrewlewis** [comment]
Please could you share a minimal test project so we can reproduce this here?

Is the problem the black rectangle that's visible after rotation? And that doesn't go away even if you use `TextureView`?

**Comment by dukaenea** [comment]
Yes, exactly. The problem is the black block that still remains on screen after rotating. 
I tried setting `surface_type=texture_view`  and different `zoom_mode`s but the issue still persists. 


As for the test project I have to ask my higher-ups if I can provide part of the application. If not I will have to create a sample project and make sure that the issue occured in it as well.

**Comment by andrewlewis** [comment]
It's strange this is happening with `TextureView` as that should be rendered/composited just like a normal UI view (rather than having special handling of `SurfaceView`). Could there be any other `SurfaceViews` in your layout? If you inspect the layout via the Android Studio layout inspector while the black rectangle is visible, is there any sign of the black rectangle in the layout inspector?
