### ISSUE TITLE
Transfer characteristics: BT.470 Only Audio No Video

### ISSUE THREAD

**Issue by Taranlayal10** [google/ExoPlayer#7465]
Hi, @ojw28

I am writing this as a question in regards to a previously closed bug 3596. Where provided solution is not feasible. Since that issue is in locked state so I am unable to add comment on same thread.

**Original Issue**
When playing live encrypted dash content on Pixel 2 XL, audio plays but the video is not visible. The content plays fine on other devices including Pixel 1 with Android O.
Same issue is coming in One Plus 6 Device.

**Already Reported Bug**
[issue](https://github.com/google/ExoPlayer/issues/3596).

**ExoPlayer Version**
2.11.1

**Solution Provided**
Changing the Color Scheme or updating the Os of Device.

**Problem**
Due to some dependencies we can not make any changes in the color scheme of the stream also updating the OS too is not a good option since we are giving support for all versions.
Is there any way of setting the desired color scheme in to the player.

**Below is my Scheme**

Standard                                 : PAL
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Encryption                               : Encrypted
colour_description_present               : Yes
colour_description_present_Source        : Stream
Color range                              : Full
colour_range_Source                      : Stream
Color primaries                          : BT.601 PAL
colour_primaries_Source                  : Stream
Transfer characteristics                 : BT.470 System B/G
transfer_characteristics_Source          : Stream
Matrix coefficients                      : BT.470 System B/G
matrix_coefficients_Source               : Stream
Codec configuration box                  : avcC

**Comment by andrewlewis** [comment]
It looks like handling of BT.601 was missing in the graphics stack and this had to be fixed by Qualcomm, so a system update was required to roll out the fix. I think it's unlikely we can workaround the bug at the app level (even if it was worth the effort to try to handle rendering ourselves, which is unlikely, it would probably be impossible because the content is DRM protected).

@ojw28 I'll close this as infeasible, but please reopen if you can see a feasible workaround.
