### ISSUE TITLE
Does Exoplayer support Incremental Kapt, I want to make incremental build which will help in reducing build time

### ISSUE THREAD

**Issue by uktshukg** [google/ExoPlayer#7466]

**Comment by andrewlewis** [comment]
The best way to check is probably to try it, but as far as I know we don't depend on any non-incremental annotation processors so I'd expect it to work. [Here are some instructions](https://github.com/gradle/gradle/blob/master/subprojects/docs/src/docs/userguide/jvm/java_plugin.adoc#incremental-annotation-processing) about checking for annotation processors triggering full recompilation. I'll leave this open for a while in case you find any issues that we need to investigate.
