### ISSUE TITLE
HLS - Support EXT-X-PROGRAM-DATE-TIME tag

### ISSUE THREAD

**Issue by cskinfill** [google/ExoPlayer#747]
Does the exoplayer support for HLS include the `EXT-X-PROGRAM-DATE-TIME` and reporting the program date time somehow?  Like metadate in some playback event?  Or at least report the `EXT-X-PROGRAM-DATE-TIME` when the manifest loads?

**Comment by endlessmind** [comment]
No it does not, but it wouldn't be hard to add support for it.

**Comment by cskinfill** [comment]
i'm new to exoplayer, if someone can give me a pointer where to start i can try and add the integration.

**Comment by endlessmind** [comment]
The class that parses the hls master playlist can be found here https://github.com/google/ExoPlayer/blob/master/library/src/main/java/com/google/android/exoplayer/hls/HlsPlaylistParser.java

Look how they extract attributes and just add the ability to extract the one you're after.

If you won't want to do it your self, then might take a look at it if you can supply me with a hls master playlist that contains the requested attribute.

**Comment by mr-bob** [comment]
Here's the top of a playlist containing the meta data:

#EXTM3U
#EXT-X-VERSION:1
## Created with ProSTREAM X/2 v1.08
#EXT-X-MEDIA-SEQUENCE:506698
#EXT-X-TARGETDURATION:9
#EXT-X-PROGRAM-DATE-TIME:2015-07-31T06:27:43Z
#EXTINF:10, no desc
seg192000-00506698.aac
#EXTINF:10, no desc
seg192000-00506699.aac
#EXTINF:10, no desc
seg192000-00506700.aac
#EXTINF:10, no desc
seg192000-00506701.aac
#EXTINF:10, no desc
seg192000-00506702.aac
#EXTINF:10, no desc
seg192000-00506703.aac
#EXTINF:10, no desc
seg192000-00506704.aac
#EXTINF:10, no desc
seg192000-00506705.aac
....


Hope this helps!

**Comment by abhiguru** [comment]
any updates here ?

**Comment by ojw28** [comment]
This is supported in `2.1.0`.
