### ISSUE TITLE
How to change song from list in exoplayer programmatically

### ISSUE THREAD

**Issue by mitesh-foremost** [google/ExoPlayer#7470]
I am developing an audio player app and I am using exoplayer first time I am searching solution for change song programmatically.
 
I have one ArrayList of the song. if the user clicks on the Next button then play the next song and if the user clicks on previous, I want to start the song from start or click twice then play the previous song.

I am using this for now but is there any other easy way available?
```

 public void previous() {
        Timeline timeline = mPlayer.getCurrentTimeline();
        final Timeline.Window window;
        window = new Timeline.Window();

        if (timeline.isEmpty()) {
            return;
        }
        int windowIndex = mPlayer.getCurrentWindowIndex();
        timeline.getWindow(windowIndex, window);
        if (windowIndex > 0 && (mPlayer.getCurrentPosition() <= 3000
                || (window.isDynamic && !window.isSeekable))) {
            mPlayer.seekTo(windowIndex - 1, C.TIME_UNSET);
        } else {
            mPlayer.seekTo(0);
        }
    }

    public void next() {
        final Timeline.Window window;
        window = new Timeline.Window();
        Timeline timeline = mPlayer.getCurrentTimeline();
        if (timeline.isEmpty()) {
            return;
        }
        int windowIndex = mPlayer.getCurrentWindowIndex();
        if (windowIndex < timeline.getWindowCount() - 1) {
            mPlayer.seekTo(windowIndex + 1, C.TIME_UNSET);
        } else if (timeline.getWindow(windowIndex, window, false).isDynamic) {
            mPlayer.seekTo(windowIndex, C.TIME_UNSET);
        }
    }
```
how do I achieve this?  play next song, prev song, play repeat song, shuffle song etc...

**Comment by andrewlewis** [comment]
Regarding simplifying the code snippets, on recent versions of the player there are convenience methods `boolean player.hasNext()`, `player.next()` and similarly for previous. You can also refer to [`PlayerControlView`](https://github.com/google/ExoPlayer/blob/1f505fa/library/ui/src/main/java/com/google/android/exoplayer2/ui/PlayerControlView.java) for sample code.

See also [Controlling the player](https://exoplayer.dev/hello-world.html#controlling-the-player), which mentions shuffling.

**Comment by ojw28** [comment]
The player methods for navigating the playlist will be added to [this section](https://exoplayer.dev/hello-world.html#controlling-the-player) in a future documentation push. Removing `documentation candidate` label as this change has already been made internally.
