### ISSUE TITLE
ITS POSSIBLE WEBVIEW HTML5 VIDEO TO EXOPLAYER ?

### ISSUE THREAD

**Issue by davebatistareal** [google/ExoPlayer#7471]
Hello, 
i need a little help, i need to run a HLS video in HTML5 in my webview to Exoplayer, its possible ?
in html5 video am using hls.js library.

thank you so much!

**Comment by andrewlewis** [comment]
`WebView` has its own playback implementation for HTML 5 video and I'm pretty sure they don't use ExoPlayer: [see this old thread](https://groups.google.com/a/chromium.org/forum/#!topic/android-webview-dev/FbP9FhHCM38) about using the platform `MediaPlayer` for HLS, and a custom player implementation for other formats (I think that includes playback when using media source extensions, e.g., with hls.js).

You could try using the `WebView` to communicate with your app code and use ExoPlayer directly from there, so I think it's possible but probably quite a lot of work.
