### ISSUE TITLE
Add new Feature Request for supporting bit.tube urls

### ISSUE THREAD

**Issue by pooyair** [google/ExoPlayer#7472]
Thanks for wonderful work. I love exoplayer the only missing feature is opening Bit.tube stream url. as you know there are so many bit.tube stream url that currently is not possible to view them by your library but it can be open by VLC and Safari web browser but not with Exoplayer. here is an example  for url https://bittube.tv
Thanks

**Comment by andrewlewis** [comment]
That URL looks like it's intended for embedding playback within a web page. You'd need to get them to provide a media URL following a standard streaming format like DASH or HLS to be able to play the stream directly with ExoPlayer.

**Comment by pooyair** [comment]
please open the ticket. please note bit.tube it's video and stream provider like youtube, it has some live video streaming. so if Exoplayer support youtube why it wouldn't be support bit.tube? 
https://bittube.tv/
https://bittube.tv/post/77de82f5-7975-4c6b-bc27-1817767bade7
 https://bit.tube/playerembed/12067/BRJfxvDlyaXTF3GrxB1i
Thanks!

**Comment by andrewlewis** [comment]
We don't really support YouTube in that sense. Apps can use the YouTube Player API to embed playback, and a similar model would work for this situation, but you'd need to ask the stream provider to implement that. I will leave this closed for now as I don't think we intend to implement the enhancement.
