### ISSUE TITLE
The exiting during video playing.

### ISSUE THREAD

**Issue by inat-tv** [google/ExoPlayer#7474]
I started receiving some complaints. 5 minutes after watching the video it exiting the video. I couldn't find out what this problem is. Such a problem started to occur on some devices. Is there a known issue in this regard?

**Comment by ojw28** [comment]
No, there are no known issues related to this. It sounds more likely to be an app issue than an issue with ExoPlayer, although from the limited information provided it's hard to be sure.

Closing for now, since there's no evidence this is an ExoPlayer problem.
