### ISSUE TITLE
Can the volume be set dynamically

### ISSUE THREAD

**Issue by HanGao1** [google/ExoPlayer#7476]
I encountered a difficulty: I used exoplayer to play user-recorded audio, but the volume of the audio was different, resulting in varying sound levels during playback. Is there any way to dynamically adjust the overall playback volume based on the average volume of the current audio

**Comment by ojw28** [comment]
We support setting the volume, by calling `setVolume` on the player instance. We don't support automatic volume normalisation though. You'd probably need to write your own code to scan each of the files, work out what volume to use for each one, and then call `setVolume` with these values for normalized playback.

**Comment by HanGao1** [comment]
Can the maximum volume be greater than 1

**Comment by ojw28** [comment]
No. If you want to volume-boost audio that doesn't use the full range then you'd probably have to look at writing a custom `AudioProcessor` to do that. That's a lot more complicated though!
