### ISSUE TITLE
Useragent not identified by podcast hosts

### ISSUE THREAD

**Issue by shirtmogul12** [google/ExoPlayer#7478]
Hi, i have a podcast app using exo. I have set the useragent as follows but podcast hosting providers and statistics can't find my useragent on their logs. What should I change?

```
  private MediaSource buildMediaSource(Context context, Uri uri){
        String userAgent = Util.getUserAgent(context, "MyPodcastApp");

        // Default parameters, except allowCrossProtocolRedirects is true
        DefaultHttpDataSourceFactory httpDataSourceFactory = new DefaultHttpDataSourceFactory(
                userAgent,
                null /* listener */,
                DefaultHttpDataSource.DEFAULT_CONNECT_TIMEOUT_MILLIS,
                DefaultHttpDataSource.DEFAULT_READ_TIMEOUT_MILLIS,
                true /* allowCrossProtocolRedirects */
        );

        ExtractorMediaSource audioSource =
                new ExtractorMediaSource.Factory(
                        new DefaultDataSourceFactory(context, null, httpDataSourceFactory)).
                        createMediaSource(uri);

        return new ConcatenatingMediaSource(audioSource);
    }
```

**Comment by ojw28** [comment]
That looks like it should be sufficient. Note that the user agent isn't just going to be `MyPodcastApp`. It's going to be some larger string that starts with `MyPodcastApp/`, as per the source code for `Util.getUserAgent`.

You can probably use a tool like WireShark to work out whether the user agent header is being set correctly in the outbound requests. Currently I don't think you know whether the issue is on the ExoPlayer side, or on the podcast hosting provider side.

**Comment by shirtmogul12** [comment]
I tested by hosting an mp3 file on my server. It shows as:

`MyPodcastApp/1.5.1 (Linux;Android 8.1.0) ExoPlayerLib/2.10.8`

1.5.1 is the app version. Is doing the following acceptable?
`
String userAgent = "MyPodcastApp/ Android";`

**Comment by ojw28** [comment]
The string you're proposing seems strictly less useful than the one you're currently using, so ideally I think you'd continue to pass the one that contains the additional information, and you'd fix whatever server-side logic you're using to detect them to be able to handle such strings.

That aside, you can basically set the user agent to whatever you like, so there's no reason you can't do what you're proposing if that's what you want to do!
