### ISSUE TITLE
ExoPlayer server and client(s)

### ISSUE THREAD

**Issue by ChernyshovYuriy** [google/ExoPlayer#7484]
Hey,

Is there any plans to introduce functionality of serve-client(s) within ExoPlayer?
For example, one ExoPlayer's instance might act as media server, with controls of playlist, currently playing track, etc ..., might not have use view at all. Another instance may act as client or clients, which simply connects to server and consumes whatever server broadcasts.

Thanks in advance,

Yurii

**Comment by ojw28** [comment]
No, we do not currently have any plans to introduce serving functionality.

**Comment by ChernyshovYuriy** [comment]
Ok, thanks.
