### ISSUE TITLE
Is there a way to know the "type" of an HTTP request? (e.g. manifest, segment, etc)

### ISSUE THREAD

**Issue by chrisfillmore** [google/ExoPlayer#7485]
When we get an HttpDataSourceException, often we want to know whether this was for a manifest request, segment request, etc. This information is used for analytics/reporting purposes. Inspecting the URL can be error-prone. Is there a better way to find this out?

Follow-up question: if there is not currently a better way, would you be willing to review a design/PR that added this information to HttpDataSource (or other relevant location)?

**Comment by ojw28** [comment]
`AnalyticsListener.onLoadError` gives you a lot of data for analytics/reporting, including `mediaLoadData.dataType` that should tell you what type of data was being loaded. Is that sufficient?

**Comment by chrisfillmore** [comment]
@ojw28 thanks for replying. Sorry for the delay in responding, I had to check with my teammates because I see, in fact, we are using `AnalyticsListener` for reporting already. But we have separate reporting for errors coming out of `onPlayerError(ExoPlaybackException exception)`. I'm trying to map the HttpDataSourceException to a particular error code in our own domain, so that "fatal errors" are presented in an easily digestible way for our analytics people.

Thanks for the help. I'm going to close this for now because I don't think I have a definite need for "request type". Guessing from the url will probably work 99% of the time. I'll circle back if I run into a problem.
