### ISSUE TITLE
in rare condition exoplayer stop at the end of buffer

### ISSUE THREAD

**Issue by pooyair** [google/ExoPlayer#7487]
please run following code with Exoplayer after 12 seconds of playing or less it will be stop

`http://linux-app.tv:6204/60400655844704/32991126026152/7576
`

`javax.net.ssl.sslhandshakeexception: ssl handshake aborted: connection reset by peer`

**Comment by ojw28** [comment]
I don't see the SSL issue, but I do see playback ending after a short period of time.

I see the same behaviour in VLC as well. It seems that the server is indicating that it has no more data, and so playback ends. This is working as intended from the player's perspective.
