### ISSUE TITLE
Help me for HLS Seeking in livestream  and download TS offline 

### ISSUE THREAD

**Issue by ducanh3005** [google/ExoPlayer#7496]
Before filing a question:
Can you help me for HLS Seeking in livestream  and download ts offline when watch a livestream ~ 5mins. 
I test in  your demo and duration get 10s and position seeking ~ 2 -4s
if you have a example , give me . 
Thank you,

**Comment by AquilesCanta** [comment]
Downloading live streams is not supported by ExoPlayer. Please track #3877.
