### ISSUE TITLE
how to work for tag EXT-X-DISCONTINUITY-SEQUENCE？

### ISSUE THREAD

**Issue by High-calcium-tiger** [google/ExoPlayer#7500]
as i konw， for EXT-X-DISCONTINUITY，The client MUST be prepared to reset its parser(s) and decoder(s) before playing a Media Segment that has an EXT-X-DISCONTINUITY tag applied to it, otherwise playback errors can occur.
for  EXT-X-DISCONTINUITY-SEQUENCE tag allows synchronization between different Renditions of the same Variant Stream or different Variant Streams that have EXT-X-DISCONTINUITY tags in their Media Playlists.
i want understand how to synchronization for Variant Streams?
I guess when Internet speed is not good, server have removed the EXT-X-DISCONTINUITY tag ,but cliant haven`t play the tag. so in this time cliant play media playlist ,without EXT-X-DISCONTINUITY tag ,but the media segment  should bring DISCONTINUITY attribute.so cliant maybe play hang up(becuase have no  reset its parser(s) and decoder(s) ).
is true? who can tell me. thanks

**Comment by ojw28** [comment]
It's very unclear what the question is here. Please could you try and phrase it more clearly? It's also unclear whether this is an ExoPlayer question, or a general question about HLS. If this is a general question about HLS, StackOverflow would be a better place to ask.
