### ISSUE TITLE
Which version of the HLS protocol does the player support？

### ISSUE THREAD

**Issue by arlimm318** [google/ExoPlayer#7503]
The HLS protocol has been updated to version 8.
Which version of the HLS protocol does the ExoPlayer support？

**Comment by AquilesCanta** [comment]
We aim to always support the newest version. We try to add support for any new features while remaining backwards compatible. 

If there's a specific feature for which you don't find support, please file a fresh issue for tracking its addition. It would also be important that you include sample media for us to take a look into adding a specific feature. Also relevant: #4073.

**Comment by arlimm318** [comment]
I'm Sorry.
But, I still have a question.
The  Tag  EXT-X-I-FRAME-STREAM-INF and EXT-X-I-FRAMES-ONLY Can  be supported?
They were defined in the HLS V4.
On 6/16/2020 04:01，Santiago Seifert<notifications@github.com> wrote：

Closed #7503.

**Comment by ojw28** [comment]
There is an open enhancement tracking supporting those tags (https://github.com/google/ExoPlayer/issues/474). It's generally a good idea to search the issue tracker, in case your question is already answered or your request is already tracked :).
