### ISSUE TITLE
Is SimpleExoPlayer Multiple Instances Allowed ?

### ISSUE THREAD

**Issue by manish-jet** [google/ExoPlayer#7505]
I want to play Video in list and need NextPlayer,ActivePlayer and Previous Player.

Is there any way to achieve lets suppose I am playing 1th position video and want 0th and 2nd Video Prepared .

I have wasted 2 days to achieve this using 3 player but not get success .Please let me know if it is possible .Thanks in advance

**Comment by fgl27** [comment]
Yes it is I have 5 working at the same time https://youtu.be/EASKYW3TiOQ?t=291 no problem on prepare one when others are playing as you can see.

Depend on the device HW slow devices may not be able to play more then two (even one maybe if is really old device), but that is a issue of the HW and not the player, so what I do is to use a hls playlist that has multiple resolution/bitrates and I block the max bitrate in relation to the device, this way it player plays lets say at 720p30 3 Mbps and work on most devices, some needs to lower to 480p30 2 Mbps, I let the user override the max allowed bitrate as some device may be more capable then what I expect as I can't test all devices so I must assume capability on my end.

you can set max bitrate on the fly (after the playback has started), so when not all players are used you can allow all resolutions again, when a multiple player process start again you block, a small stop to buffer may happen when you change the max bitrate as the player needs to buffer the new resolution.

you must get the ideia, is technically simple, but of course you need to adapt for yours use case.

**Comment by AquilesCanta** [comment]
There's no specific limitation around keeping multiple Player instances alive. If you can provide specific information about what you are having issues with, we may be able to provide more assistance. You can provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) if you think you might be encountering an ExoPlayer issue.

Thanks @fgl27 for your contribution!

**Comment by manish-jet** [comment]
@fgl27 @AquilesCanta Thanks for your answer I am looking more closely in my code and let you know if any specific problem arise. For now I am closing this thread

**Comment by manish-jet** [comment]
@AquilesCanta  I am Using 3 Exoplayer in RecyclerView 
1-ActivePlayer
2-FirstPlayer
3-SecondPlayer 

Now when list scroll selected position will be ActivePlayer and I prepare pos+1(FirstPlayer) and Pos-1 (SecondPlayer) When scroll list up releasing ActivePlayer and Assign FirstPlayer To ActivePlayer also release second player and prepare both first and second player 

for some video it is working fine and after some scroll I am getting Following error 
[exoMultiplayerError.txt](https://github.com/google/ExoPlayer/files/4784746/exoMultiplayerError.txt)

Can you help me with an example ?

**Comment by manish-jet** [comment]
Hello Team,

Thanks for response and support I found the problem .That problem was in my code not in exoplayer
