### ISSUE TITLE
about custom decryption

### ISSUE THREAD

**Issue by NerdAnonymous** [google/ExoPlayer#7506]
How to customize the data source to achieve custom decryption？

**Comment by AquilesCanta** [comment]
There is [some material available](https://github.com/google/ExoPlayer/issues?q=is%3Aissue+custom+encryption) in this issue tracker about custom encryption (example: #2467). You could start by looking at the [AesCipherDataSource](https://github.com/google/ExoPlayer/blob/dev-v2/library/core/src/main/java/com/google/android/exoplayer2/upstream/crypto/AesCipherDataSource.java), and the [Aes128DataSource](https://github.com/google/ExoPlayer/blob/dev-v2/library/hls/src/main/java/com/google/android/exoplayer2/source/hls/Aes128DataSource.java).

We don't have the resources to provide an exhaustive tutorial on how to implement in-app encryption. I suggest you do some research, and reach to us if you encounter any specific issues. We can help if you have more constrained questions.
