### ISSUE TITLE
rk3288 Can't play video

### ISSUE THREAD

**Issue by star-andy** [google/ExoPlayer#7510]
````
implementation 'com.google.android.exoplayer:exoplayer-core:2.11.5'
````
````
  private TextureView mDsipTure;
    private SimpleExoPlayer mPlayer;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        mDsipTure = findViewById(R.id.dsip_play);
        readDeauftVideo();
        initPlayer();
        showDefaultVideo();
    }


    private void initPlayer() {
        TrackSelection.Factory videoTrackSelection = new AdaptiveTrackSelection.Factory();
        TrackSelector trackSelector = new DefaultTrackSelector(videoTrackSelection);
        mPlayer = ExoPlayerFactory.newSimpleInstance(this, trackSelector);
        mPlayer.setVideoTextureView(mDsipTure);
    }

    /**
     * 读取默认视频source
     */
    private MediaSource readDeauftVideo() {
        MediaSource mediaSource = null;
        try {
            DataSpec dataSpec = new DataSpec(RawResourceDataSource.buildRawResourceUri(R.raw.default_video));
            RawResourceDataSource rawResourceDataSource = new RawResourceDataSource(this);
            rawResourceDataSource.open(dataSpec);
            DataSource.Factory factory = () -> rawResourceDataSource;
            mediaSource = new ExtractorMediaSource.Factory(factory).createMediaSource(rawResourceDataSource.getUri());
        } catch (RawResourceDataSource.RawResourceDataSourceException e) {
            e.printStackTrace();
        }
        return mediaSource;
    }


    /**
     * 显示默认视频
     */
    public void showDefaultVideo() {
        mPlayer.setRepeatMode(Player.REPEAT_MODE_ALL);
        mPlayer.prepare(readDeauftVideo());
        mPlayer.setPlayWhenReady(true);
    }

````

Unable to play video on RK3288, other devices are working normally

![image](https://user-images.githubusercontent.com/15726024/84744571-09cd2680-afe6-11ea-8f5c-2eb60dbdc445.png)

**Comment by AquilesCanta** [comment]
There is not enough information for us to help with this. Please provide all information requested in the issue template [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md). If you're unable to share bug reports or test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Please also update this issue to indicate you’ve done this.

I would also suggest that before updating this issue, you should:
- Have a look at #403. 
- Try playing your file in the demo app, to make sure the issue doesn't lie in the media file itself.

**Comment by star-andy** [comment]
@AquilesCanta 
Thank you very much for your answer
I tested mp4 on SDCard with the same problem，Demo doesn't work properly either
Below is the log file  

[logcat.txt](https://github.com/google/ExoPlayer/files/4789847/logcat.txt)

**Comment by AquilesCanta** [comment]
Hi again. We still don't have the information to help with this. We usually need at least a media sample to reproduce the issue and a bugreport.

However, if the issue is limited to a specific device, this suggests the issue is not ExoPlayer-related and it's instead a device issue. If so, please try contacting the device manufacturer directly.

**Comment by AquilesCanta** [comment]
A quick look at the logcat shows that the device does not seem to support the given video format:

```
NoSupport [sizeAndRate.support, 1920x816x23.97579574584961] [OMX.google.h264.decoder, video/avc] [rk3288, rk3288, rockchip, 25]
```
