### ISSUE TITLE
Play 2 mono mp3 audio streams at the same time, Only 1 Audio was played at a time

### ISSUE THREAD

**Issue by naruto2302** [google/ExoPlayer#7511]
### [REQUIRED] Issue description
2 Instances were created for play 2 Mono-Channel Audio , but only 1 Audio was played.
I also try to play 2 Stereo-Channel Audio at the same time, and both were played correctly.

### [REQUIRED] Reproduction steps
Step 1: Init 2 SimpleExoplayer instances
Step 2: Generate ProgressiveMediaSource from 2 url below (2 Mono Audios stream)
Step 3: setPlayWhenReady(true) for both 2 instances
Step 4: Saw that Track 1 played, will pause  until play Track 2 from start to finish. Track 1 Continue Play when pause Track 2. Expect 2 players paralell playing.
Step 5: Repeat step 2 but this time 2 Stereo Audios Stream
Step 6: 2 players paralell playing 

### [REQUIRED] Link to test content
2 Mono Audio tracks
https://archive.org/download/trudio53e60f3ffcf1b67c77375f3f2a44022c-sv-2/10595115_3_vi+chuong-3116.mp3
https://archive.org/download/trudio2e85c44ed2d65c0bf390204627d492bb-sv-3/10595114_3_vi+chuong-3115.mp3
2 Stereo Audio Tracks
https://archive.org/download/NhacNenTruyenaudiocv/EDM-Chinese.mp3
https://archive.org/download/NhacNenTruyenaudiocv/Happy-Cafe.mp3

### [REQUIRED] A full bug report captured from the device
Not much things to capture
https://www.mediafire.com/file/tdukeg8ou57duov/demo2exoplayer.zip/file 
I created a demo project too 

### [REQUIRED] Version of ExoPlayer being used
exoplayer 2.11.5

### [REQUIRED] Device(s) and version(s) of Android being used
Pixel 3a XL - API 30 - Simulator

**Comment by AquilesCanta** [comment]
I cannot reproduce the issue. Put the following code in onCreate of a basic activity, and both files play simultaneously on version 2.11.4:

```
    Uri uri1 = Uri.parse("https://archive.org/download/trudio53e60f3ffcf1b67c77375f3f2a44022c-sv-2/10595115_3_vi+chuong-3116.mp3");
    SimpleExoPlayer player1 = new SimpleExoPlayer.Builder(/* context= */ this).build();

    player1.prepare(new ProgressiveMediaSource.Factory(new DefaultDataSourceFactory(this,
        Util.getUserAgent(this, "test"))).createMediaSource(uri1));
    player1.setPlayWhenReady(true);

    Uri uri2 = Uri.parse("https://archive.org/download/trudio2e85c44ed2d65c0bf390204627d492bb-sv-3/10595114_3_vi+chuong-3115.mp3");
    SimpleExoPlayer player2 = new SimpleExoPlayer.Builder(/* context= */ this).build();

    player2.prepare(new ProgressiveMediaSource.Factory(new DefaultDataSourceFactory(this,
        Util.getUserAgent(this, "test"))).createMediaSource(uri2));
    player2.setPlayWhenReady(true);
```

Can you clarify what the issue is?
