### ISSUE TITLE
PlayerNotificationManager not showing notification for video

### ISSUE THREAD

**Issue by wishy-viewlift** [google/ExoPlayer#7514]
I have application which plays video and I want to show notification with player controls - play, pause, next, previous etc.
I tried using PlayerNotificationManager mentioned in the Medium Post
PlayerNotificationManager
But the notification isn't visible. I assigned the player to notification manager after the player is initialised.

Checking on android API 29 and I am using SimpleExoPlayer for player and setting it to notification manager

          `  DefaultRenderersFactory defaultRenderersFactory = new DefaultRenderersFactory(getContext())
                .setExtensionRendererMode(DefaultRenderersFactory.EXTENSION_RENDERER_MODE_ON);
        SimpleExoPlayer   player = new SimpleExoPlayer.Builder(getContext(), defaultRenderersFactory)
                .setTrackSelector(trackSelector)
                .build();
        player.addListener(this);
        playerView.setPlayer(player);
        playerView.setPlaybackPreparer(this);
        PlayerNotificationManager playerNotificationManager = new PlayerNotificationManager(
                appCMSPresenter.getCurrentContext(),
                "player not",
                459, new DescriptionAdapter());

        playerNotificationManager.setPlayer(player);`

**Comment by marcbaechinger** [comment]
With the code above you are saying that you have created a notification channel with the title `player not`. If such a notification channel does not exist, the system will not show the notification and I believe you would find something in the logs telling this (not sure though).

Can you double check  whether the notification channel 'player not' has been properly created? 

If you find you need to create a channel first, you may consider looking into the static factory method which will create the channel with the declared id's and names for you.

```
createWithNotificationChannel(
      Context context,
      String channelId,
      @StringRes int channelName,
      @StringRes int channelDescription,
      int notificationId,
      MediaDescriptionAdapter mediaDescriptionAdapter)
```

If this does not work, please accept my apologies and do a bug report and upload it here so I can look into your issue some more. You can alternatively send the bug report by email to dev.exoplayer@gmail.com using a subject in the format "Issue #7514".

**Comment by wishy-viewlift** [comment]
Notification Channel did not existed, that seemed to be the issue.
