### ISSUE TITLE
Regarding 'setEnablePreloading' API 

### ISSUE THREAD

**Issue by custadian** [google/ExoPlayer#7519]
### [REQUIRED] Searched documentation and issues
I had raised a question to IMA android SDK forum regarding this API.
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/ima-sdk/vTiYV0NMzbY/DG3__PKvBwAJ

I got the answer from them that preloading works with single ads, VMAPs and Ad Rules.

### [REQUIRED] Question
Can you please tell me how ExoPlayer is handling this pre-roll with multiple pods in the code or my understanding is totally wrong with respect to this feature.

**Comment by andrewlewis** [comment]
The ExoPlayer IMA extension requires preloading to be enabled (it won't work without it). This allows us to avoid buffering at ad/content, content/ad and ad/ad transitions in almost all cases.

To try to address remaining questions from your IMA SDK forum post
- For an ad tag with a single preroll, once we have the ad URI we are able to start buffering the ad and the start of the content. The point at which we actually start buffering content depends on the load control configuration of the player (see [load control](https://exoplayer.dev/glossary.html#loadcontrol)). Note: we don't do anything 'special' for skippable ads currently, so as for non-skippable ads the content will only start loading once the ad has finished loading.
- You can see preloading working in the ExoPlayer demo app if you build it to include the IMA extension and play one of the sample ad tags. If you set `ImaAdsLoader.DEBUG` to true you will see logging about `loadAd` before the player position actually reaches the ad, for example.
- I suspect the IMA advanced sample doesn't use preloading yet, though I'm not sure.

This all relates to client-side ad insertion. If you are using sever-side ad insertion (DAI), the stream itself contains ads so preloading is not relevant.
