### ISSUE TITLE
Changing stream takes a lot of time

### ISSUE THREAD

**Issue by Zo2m4bie** [google/ExoPlayer#752]
I use ExoPlayer to create some kind of the TV. My problem is if user looks channel for some time(for example 5 min) and try to change it to another one, it will take a lot of time to change stream(once it took 15 min to change stream). But if user looks first channel 1 min, when he will change channel, it will take seconds to change stream. For my app I use DemoPlayer from sample project. When user changes channel, app calls releasePlayer(); and after that preparePlayer(); with new stream's url. 

Also I tried another way to change stream. I have fragment which contains ExoPlayer and I tried recreate fragment when I need to change channel and set up it instead of old one. And it's work perfect. In this case It takes seconds to change stream. But problem is when I tried ti change stream only via player methods, it takes a lot of time. 

Method releasePlayer() and preparePlayer(); the same as at this class https://github.com/google/ExoPlayer/blob/master/demo/src/main/java/com/google/android/exoplayer/demo/PlayerActivity.java

**Comment by ojw28** [comment]
The demo app is only a guide of how an application could be implemented. In this case I suspect you haven't adapted it sufficiently to meet your needs. In particular, I suspect the problem might be related to playerPosition and how it's set in releasePlayer and applied as the seek position in preparePlayer. You probably don't want that behavior for what you're trying to do. You'll probably find that commenting out the call to player.seekTo in preparePlayer "fixes" the issue for you.
