### ISSUE TITLE
PlayerNotificationManager not updating player on notification

### ISSUE THREAD

**Issue by wishy-viewlift** [google/ExoPlayer#7522]
I have 2 players in my app. One is a mini player which is available through out app. 
Other is a half page player. When the half page player is playing the mini player is dismissed.
I added PlayerNotificationManager it seems to working fine and good for the mini player.
But when I switch to half page player the last player instance in the notification is of the mini player.
Notification never updates to my current player.

This is code for the notification

`        
        void createNotification() {

        playerNotificationMetaDataAdapter = new PlayerNotificationMetaDataAdapter();

        playerNotificationManager = PlayerNotificationManager.createWithNotificationChannel(
                getContext(),
                getContext().getString(R.string.player_channel_id),
                R.string.player_channel_name,
                R.string.player_channel_description,
                984, playerNotificationMetaDataAdapter);

    }

    public void showNotification() {
        playerNotificationManager.setPlayer(getPlayer());
    }

    void clearNotification() {
        if (playerNotificationManager != null)
            playerNotificationManager.setPlayer(null);
    }`

**Comment by AquilesCanta** [comment]
I'm assuming you have checked you are correctly calling `playerNotificationManager.setPlayer ` when needed. We will need a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) to help with this, since it's not really clear this is not an application issue.
