### ISSUE TITLE
Ability to switch between external subtitle files

### ISSUE THREAD

**Issue by mick1418** [google/ExoPlayer#753]
Hi,

I'm trying to develop a video player that have external subtitle support.
I managed to display external SRT file thanks to the following code:

`DataSource textDataSource = new DefaultUriDataSource(context, bandwidthMeter, userAgent);
SingleSampleSource textSampleSource = new SingleSampleSource(textUri, textDataSource,
    MediaFormat.createTextFormat(MimeTypes.APPLICATION_SUBRIP, C.MATCH_LONGEST_US));
TrackRenderer textRenderer = new TextTrackRenderer(textSampleSource, player,
    player.getMainHandler().getLooper());` 

My question is: how could I switch between different subtitle sources once the video is playing?

**Comment by ojw28** [comment]
More or less everything that's needed for this is in place. There's one small piece missing. We'll add it this week.

**Comment by mick1418** [comment]
Awesome. I'm looking forward to it!

**Comment by ojw28** [comment]
The change referenced above allows you to pass multiple sources to a TextTrackRenderer. So to switch between multiple subtitles at runtime you should:

1. Duplicate the first three lines of your code snippet above to create a sample source for each subtitle.
1. Pass all of the sources to the text renderer.

Note that if you're using ExtractorSampleSource for audio/video and you're unsure as to whether there are embedded subtitles in the stream itself, you can also pass that as an additional source.

**Comment by mick1418** [comment]
Ok so I managed to display multi source subtitles thanks to your commit, but once I added the TextTrackRenderer, I lost the total duration and progress of the video.
If I go back to video+audio only, total duration and progress are working again.

Maybe I'm missing something in the MediaFormat (the new bitrate parameter is maybe not rightly set). You'll find my code below.

`Allocator allocator = new DefaultAllocator(BUFFER_SEGMENT_SIZE);

        // Build the video and audio renderers.
        DefaultBandwidthMeter bandwidthMeter = new DefaultBandwidthMeter(player.getMainHandler(), null);
        DataSource dataSource = new DefaultUriDataSource(context, bandwidthMeter, userAgent);
        ExtractorSampleSource sampleSource = new ExtractorSampleSource(uri, dataSource, allocator, BUFFER_SEGMENT_COUNT * BUFFER_SEGMENT_SIZE);

        // Video track
        MediaCodecVideoTrackRenderer videoRenderer = new MediaCodecVideoTrackRenderer(sampleSource, null, true, MediaCodec.VIDEO_SCALING_MODE_SCALE_TO_FIT, 5000, null, player.getMainHandler(), player, 50);

        // Audio track
        MediaCodecAudioTrackRenderer audioRenderer = new MediaCodecAudioTrackRenderer(sampleSource, null, true, player.getMainHandler(), player, AudioCapabilities.getCapabilities(context));

        // Subtitle track
        DataSource textDataSource = new DefaultUriDataSource(context, bandwidthMeter, userAgent);
        //Fake to test
        SingleSampleSource frSource = new SingleSampleSource(Uri.fromFile(new File(context.getExternalCacheDir(), "fr-FR.srt")), textDataSource, MediaFormat.createTextFormat(MimeTypes.APPLICATION_SUBRIP, 25, "fr"));
        SingleSampleSource enSource = new SingleSampleSource(Uri.fromFile(new File(context.getExternalCacheDir(), "en-GB.srt")), textDataSource, MediaFormat.createTextFormat(MimeTypes.APPLICATION_SUBRIP, 25, "en"));
        SingleSampleSource nlSource = new SingleSampleSource(Uri.fromFile(new File(context.getExternalCacheDir(), "nl-NL.srt")), textDataSource, MediaFormat.createTextFormat(MimeTypes.APPLICATION_SUBRIP, 25, "nl"));

        TrackRenderer textRenderer = new TextTrackRenderer(new SingleSampleSource[]{frSource, enSource, nlSource}, player, player.getMainHandler().getLooper());

        // Invoke the callback.
        TrackRenderer[] renderers = new TrackRenderer[VideoPlayer.RENDERER_COUNT];
        renderers[VideoPlayer.TYPE_VIDEO] = videoRenderer;
        renderers[VideoPlayer.TYPE_AUDIO] = audioRenderer;
        renderers[VideoPlayer.TYPE_TEXT] = textRenderer;
        player.onRenderers(renderers, bandwidthMeter);`

Thanks in advance for your support.

**Comment by ojw28** [comment]
You can set the bitrate to whatever you like. The important thing is that when creating your MediaFormat you need to set the duration of the subtitle. The constructor that you're using currently sets it to a default, which is C.UNKNOWN_TIME_US. This means that the duration of the media as a whole is unknown, which is why you lose the duration and progress.

To fix this, use the createTextFormat method that takes a fourth argument. Set the fourth argument to either C.MATCH_LONGEST_US (which basically means "this is the same length as the video") or the duration of the video in microseconds, if you happen to know what it is when you're executing this code.

We should probably set the default to MATCH_LONGEST_US rather than UNKNOWN_TIME_US for text tracks, because it's normally what the developer will want.

**Comment by ElioTohm** [comment]
DataSource textDataSource = new DefaultUriDataSource(context, bandwidthMeter, userAgent); SingleSampleSource textSampleSource = new SingleSampleSource(textUri, textDataSource, MediaFormat.createTextFormat(MimeTypes.APPLICATION_SUBRIP, C.MATCH_LONGEST_US)); TrackRenderer textRenderer = new TextTrackRenderer(textSampleSource, player, player.getMainHandler().getLooper()); 

hello sorry i am having trouble implementing this,
player.getMainHandler() can't be resolved 
and i dn't know what to put for bandwidthMeter 
(i am an entry level developer)
thank you in advance
