### ISSUE TITLE
Optimisation of ABR on exoplayer via Server & network assisted DASH

### ISSUE THREAD

**Issue by amitsamal** [google/ExoPlayer#7533]
### Searched documentation and issues

https://eprints.lancs.ac.uk/id/eprint/88536/1/print_version.pdf.
https://www.ibc.org/download?ac=1464

### Question

We are looking at enhancing our video playback experience on our app which is dominated by our android version. We use exoplayer 2.11.4 on our video streaming app and use DASH as the preferred format. We have almost covered all client side optimisation except pre-caching of initial segments for faster startup to have a better streaming experience. However we are looking at exploring the SAND architecture to optimise our customer QOS. 
We are exploring different use cases on it and one is to optimise ABR in exoplayer according to our needs. If you can guide by sharing inputs on cases to keep in mind while exploring this route. 

### A full bug report captured from the device

*[not provided]*

### Link to test content

*[not provided]*

**Comment by ojw28** [comment]
This sounds like a research topic, and as such is too vague / broad for us to really provide much guidance on this issue tracker. It's not something that we've looked into in a lot of detail, and so we don't really have concrete experiences or findings to share either. Sorry!
