### ISSUE TITLE
Add DATA_TYPE_* member to ParserException

### ISSUE THREAD

**Issue by chrisfillmore** [google/ExoPlayer#7536]
### [REQUIRED] Use case description
I would like to know what type of media was being parsed when a `ParserException` occurred. I am trying to map these exceptions to particular error codes in our application.

### Proposed solution
Add a new member `int dataType` to `ParserException`. The value will be one of the DATA_TYPE_* values defined in C.java.

### Alternatives considered
I'm not aware of an alternative. In many cases `ParserException` is constructed with a message string, thus it's not possible to determine anything about the nature of the error, so far as I can tell.

If you are amenable to this idea, I am willing to do a PR.

**Comment by chrisfillmore** [comment]
Hm I have a problem actually. Some methods, e.g. `Util.parseXsDateTime` throw `ParserException` but are called from both manifest parsers and media parsers. I could likely work around this by copying the exception at the point the parse is invoked, but it's not the prettiest solution.

Edit: Seems that `Util.parseXsDateTime` is the only place where the `dataType` is not clear. I have resolved on a local branch by catching `ParserException` and rethrowing a new `ParserException` with the correct `dataType` in two places: `DashManifestParser#parseDateTime` and `HlsPlaylistParser#parseMediaPlaylist`.

**Comment by ojw28** [comment]
This seems similar to https://github.com/google/ExoPlayer/issues/7485. I.e., can't you get this using `AnalyticsListener.onLoadError`? It may be that the same error is passed to `onPlayerError(ExoPlaybackException exception)` later on, which is the point at which the error is deemed fatal, causing playback to fail. But using `AnalyticsListener.onLoadError` should be sufficient for analytics purposes.

**Comment by chrisfillmore** [comment]
@ojw28 thanks for replying. Sorry for the delay getting back to you, I've been on holiday.

My team does use `AnalyticsListener.onLoadError`. However it seems we have different analytics/monitoring pipelines for error info from `onLoadError` and `onPlayerError`, and thus have difficulty correlating the two.

It seems like we would be better off dropping our reporting of error events from `onPlayerError`, and instead just reporting what we get from `onLoadError`. We could continue to use `onPlayerError` for behaviour handling, e.g. attempting to recover from fatal errors.
