### ISSUE TITLE
Can I switch to VR mode view for 360 Videos?

### ISSUE THREAD

**Issue by 3ameration** [google/ExoPlayer#7539]
I am using exoplayer (version 2.10.4) to play 360 videos from web.

and I am using PlayerControlView to show the VR mode button, but how to make it work?

I mean I want the user to be able to switch between the normal 360 video view and VR mode

Please check the following photo to understand what I mean by VR mode

![1_BGErBq2M120VzieCyQtRHA](https://user-images.githubusercontent.com/12966689/85515027-b70af480-b60d-11ea-8c22-5d67ca12c0dc.png)

Thank you

**Comment by andrewlewis** [comment]
Are you looking for an implementation of VR mode? If so I think the closest we ever had was [`GvrPlayerActivity`](https://github.com/google/ExoPlayer/blob/r2.10.8/extensions/gvr/src/main/java/com/google/android/exoplayer2/ext/gvr/GvrPlayerActivity.java), which used the GVR SDK, but that was removed in release 2.11.0 (it may still work in 2.10.8 though). As we aren't maintaining support for this use case any more I will close this issue.
