### ISSUE TITLE
Speed up offline download

### ISSUE THREAD

**Issue by JoshuaChewStar** [google/ExoPlayer#7541]
I have followed the latest demo and implemented the download functions. Everything works fine but the only problem is that the download is kind of slow, the file size of the content to be downloaded is normally around 8GB or more. I was wondering if there's any way I could speed up the downloads for now? 

Thanks in advance.

**Comment by icbaker** [comment]
How slow is slow?

Is the media you're downloading a progressive file, or HLS/DASH/something else?

Are you seeing download speeds that are significantly lower than the bandwidth available between the device & the server (i.e. you're not just hitting bandwidth limits)?

**Comment by JoshuaChewStar** [comment]
The media is a DASH type.

I'm not sure about the bandwidth tho, how can I check if the bandwidth has hit the limit? 

The reason I mention it's slow is because previously my app was using the v2.9.0 version of exoplayer, the download speed of v2.9 was relatively faster

**Comment by icbaker** [comment]
What version are you on now? It's interesting that it seems to have got slower.

Given this is DASH I'm going to duplicate this against #5978 - the work happening there should improve download speed by downloading multiple chunks at once.

**Comment by JoshuaChewStar** [comment]
I'm using the v2.11.6 now.

Alright then, I'll check on #5978 

Thank you so much

**Comment by JoshuaChewStar** [comment]
Hi just to update you guys about this issue.

It was my mistake and the download was actually quick, I overlooked and the file size during downloading for v2.9.0 was much more smaller.

My apologies, and thanks for helping me.
