### ISSUE TITLE
com.google.android.exoplayer.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 404

### ISSUE THREAD

**Issue by niteshfel** [google/ExoPlayer#7542]
com.google.android.exoplayer.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 404

When i have play some video got this error occur this video is youtube video when is play on youtube is playing good on all video quality formats but when i play on exoplayer 2 then only two video quality format are playing 360p and 720p and other video format return error : com.google.android.exoplayer.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 404
so what was the problem in video or exoplayer because this video play well in youtube but not in exoplayer 2

**Comment by icbaker** [comment]
We don't support playing YouTube videos on ExoPlayer: https://exoplayer.dev/troubleshooting.html#can-i-play-youtube-videos-directly-with-exoplayer

**Comment by niteshfel** [comment]
@icbaker  Yes i know exoplayer not playing youtube video via video id but  am plating with urls like hls,dash and other webm and mp4 urls then in some urls i found this error again and again .. so can guide me for this whats wrong with this

**Comment by icbaker** [comment]
Are these DASH/HLS/etc URLs derived from a YouTube ID and hosted on YouTube servers? If so, my answer above applies.

If not, it seems likely to be a server-side problem (since 404 indicates the requested resource could not be found) and you should probably talk whoever is hosting the content.

**Comment by niteshfel** [comment]
Yes @icbaker  these DASH and HLS URls derived from youtube and i am broadcasting on youtube using RTMP and then playing these urls on exoplayer not with youtube id , we are got youtube all supported urls of these video like 144p,244p,340p,480p,720p...etc then play by urls (urls are dash or hls)
