### ISSUE TITLE
inter-movie banner advertising

### ISSUE THREAD

**Issue by SerkanKUL** [google/ExoPlayer#7543]
I have android application, user is watching movie, exoplayer, I want full screen admob advertisement to appear every 5 minutes while watching movies...is it possible

**Comment by icbaker** [comment]
Have you read this page about ad Insertion?
https://exoplayer.dev/ad-insertion.html

ExoPlayer has an extension to support client-side ad insertion using the [Interactive Media Ads (IMA) SDK](https://developers.google.com/interactive-media-ads) (with more details on the page linked above).

**Comment by icbaker** [comment]
You can probably also build your own integration with AdMob by using [`PlayerMessage#setPosition(long)`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/PlayerMessage.html) to get a callback when playback reaches a certain position (i.e. you could send a message to yourself every 5 minutes of playback). You create PlayerMessages by calling `ExoPlayer#createMessage(PlayerMessage.Target)`.

You'd need to implement a `PlayerMessage.Target` that triggers the AdMob behaviour you want.
