### ISSUE TITLE
[Widevine] Duplicate Audio Tracks

### ISSUE THREAD

**Issue by Taranlayal10** [google/ExoPlayer#7548]
I am getting duplicate audio tracks in the stream, Where as in the ingestion audio track English is ingested once but on the player it is getting repeated thrice. I tried searching existing issues but could not find any one similar. If you already have issue reported kindly direct me to the same or help me in this one.

**Exo Player Version**
2.11.5

**Problem**

I am getting the duplicate Audio tracks from the player, This issue also exists in the sample app

**This is the list of audio tracks I am getting from the stream in the player.**
 
0 = {Format@16469} "Format(5, null, audio/mp4, audio/mp4a-latm, mp4a.40.2, 64070, en, [-1, -1, -1.0], [-1, 48000])"

 accessibilityChannel = -1
 bitrate = 64070
 channelCount = -1
 codecs = "mp4a.40.2"
 colorInfo = null
 containerMimeType = "audio/mp4"
 drmInitData = {DrmInitData@16480} 
 encoderDelay = 0
 encoderPadding = 0
 exoMediaCryptoType = {Class@15376} "class com.google.android.exoplayer2.drm.FrameworkMediaCrypto"
 frameRate = -1.0
 hashCode = 0
 height = -1
 id = "5"
 initializationData = {Collections$EmptyList@16482}  size = 0
 label = null
 language = "en"
 maxInputSize = -1
 metadata = null
 pcmEncoding = -1
 pixelWidthHeightRatio = 1.0
 projectionData = null
 roleFlags = 0
 rotationDegrees = 0
 sampleMimeType = "audio/mp4a-latm"
 sampleRate = 48000
 selectionFlags = 0
 stereoMode = -1
 subsampleOffsetUs = 9223372036854775807
 width = -1
 shadow$_klass_ = {Class@15316} "class com.google.android.exoplayer2.Format"
 shadow$_monitor_ = 0

1 = {Format@16611} "Format(6, null, audio/mp4, audio/mp4a-latm, mp4a.40.2, 64099, en, [-1, -1, -1.0], [-1, 48000])"

 accessibilityChannel = -1
 bitrate = 64099
 channelCount = -1
 codecs = "mp4a.40.2"
 colorInfo = null
 containerMimeType = "audio/mp4"
 drmInitData = {DrmInitData@16616} 
 encoderDelay = 0
 encoderPadding = 0
 exoMediaCryptoType = {Class@15376} "class com.google.android.exoplayer2.drm.FrameworkMediaCrypto"
 frameRate = -1.0
 hashCode = 0
 height = -1
 id = "6"
 initializationData = {Collections$EmptyList@16482}  size = 0
 label = null
 language = "en"
 maxInputSize = -1
 metadata = null
 pcmEncoding = -1
 pixelWidthHeightRatio = 1.0
 projectionData = null
 roleFlags = 0
 rotationDegrees = 0
 sampleMimeType = "audio/mp4a-latm"
 sampleRate = 48000

2= Format(7, null, audio/mp4, audio/mp4a-latm, mp4a.40.2, 64019, en, [-1, -1, -1.0], [-1, 48000])
accessibilityChannel = -1
bitrate = 64019
channelCount = -1
codecs = "mp4a.40.2"
colorInfo = null
containerMimeType = "audio/mp4"
drmInitData = {DrmInitData@16623} 
encoderDelay = 0
encoderPadding = 0
exoMediaCryptoType = {Class@15376} "class com.google.android.exoplayer2.drm.FrameworkMediaCrypto"
frameRate = -1.0
hashCode = 0
height = -1
id = "7"
initializationData = {Collections$EmptyList@16482}  size = 0
label = null
language = "en"
maxInputSize = -1
metadata = null
pcmEncoding = -1
pixelWidthHeightRatio = 1.0
projectionData = null
roleFlags = 0
rotationDegrees = 0
sampleMimeType = "audio/mp4a-latm"
sampleRate = 48000

![duplicate_audios](https://user-images.githubusercontent.com/5041526/85849546-cb472100-b7c8-11ea-83c1-d3892e60eb60.png)

**Comment by icbaker** [comment]
It's hard for us to help without access to the media that demonstrates the problem.

If you're unable to share test content publicly, please send it to dev.exoplayer@gmail.com using subject "Issue #7548". Please also update this issue to indicate you’ve done this.

**Comment by ojw28** [comment]
To add to @icbaker's response above, it seems most likely that the content you're playing has duplicate audio tracks, in which case this would be an issue with how you're creating the content rather than an issue with ExoPlayer.

**Comment by Taranlayal10** [comment]
I have raised the request with our customer / content owner and will share it with you once we have the agreement.

@ojw28 I understand your point but for the same widevine content on web application the bit movin player does not have this problem. Can you check at your end once I share the content so that we can be sure whether its content ingestion problem or not.

**Comment by Taranlayal10** [comment]
I have shared the content details. Please check.

**Comment by icbaker** [comment]
Thanks for the link - unfortunately I'm unable to access the DASH manifest, the server returns me a 403 error. This happens from the ExoPlayer demo app and also when I try and download it directly in my browser.

**Comment by Taranlayal10** [comment]
Thanks for checking. Yes I can see the sample app is throwing error in my case its not 403 rather it is  com.google.android.exoplayer2.ExoPlaybackException: android.media.MediaCodec$CryptoException: Required output protections are not active.

Please ensure to remove any force L3 settings. After removing below settings content gets played in sample app too
mediaDrm.setPropertyString("securityLevel", "L3");

Even if the playback is getting failed you still would be able to access the audio tracks pop up. I would request if possible please look in to that as We have issue in duplicate audio track only. Playback is working in my exoplayer integrated app

**Comment by icbaker** [comment]
OK I've managed to access the DASH manifest (seems it's geo-blocked?).

It declares 2 audio `AdaptationSet` elements, one with `lang="eng"` and the other `lang="hin"`. The english one contains 3 `Representation` nodes (with 3 slightly different bandwidths) while the hindi one only has one:

```
<AdaptationSet mimeType="audio/mp4" segmentAlignment="0" lang="eng">
  <Representation id="5" bandwidth="64070" audioSamplingRate="48000" codecs="mp4a.40.2">
  ...
  </Representation>
  <Representation id="6" bandwidth="64099" audioSamplingRate="48000" codecs="mp4a.40.2">
  ...
  </Representation>
  <Representation id="7" bandwidth="64019" audioSamplingRate="48000" codecs="mp4a.40.2">
  ... 
 </Representation>
</AdaptationSet>
<AdaptationSet mimeType="audio/mp4" segmentAlignment="0" lang="hin">
  <Representation id="8" bandwidth="64092" audioSamplingRate="48000" codecs="mp4a.40.2">
  ...
  </Representation>
</AdaptationSet>
```

It seems ExoPlayer is working as I'd expect here. You can see in the logcat it knows the 3 english audio tracks are part of the same adaption group (this grouping is represented by [`TrackGroup`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/source/TrackGroup.html) programatically):
```
Group:0, adaptive_supported=YES_NOT_SEAMLESS [                                                                               
  [ ] Track:0, id=5, mimeType=audio/mp4a-latm, bitrate=64070, codecs=mp4a.40.2, sample_rate=48000, language=en, supported=YES
  [X] Track:1, id=6, mimeType=audio/mp4a-latm, bitrate=64099, codecs=mp4a.40.2, sample_rate=48000, language=en, supported=YES
  [ ] Track:2, id=7, mimeType=audio/mp4a-latm, bitrate=64019, codecs=mp4a.40.2, sample_rate=48000, language=en, supported=YES
]                                                                                                                            
Group:1, adaptive_supported=N/A [                                                                                            
  [ ] Track:0, id=8, mimeType=audio/mp4a-latm, bitrate=64092, codecs=mp4a.40.2, sample_rate=48000, language=hi, supported=YES
]                                                                                                                            
```

The Demo app's track selection UI exposes all the tracks within a group to allow the user to manually override any automatic track selection (e.g. if they want to pick a higher quality video feed).

If you only expect the user to see 2 audio options in your app (english and hindi) then you shouldn't flatten each `TrackGroup` when building your list of tracks (I guess take the `Format` info from the first one?). But you should also consider whether it makes sense to provide 3 different audio tracks with the same encoding and very similar bitrates - maybe the manifest could be updated to have only a single english audio track? Then you wouldn't have to make any changes to your track selection dialog. It's not clear to me how a user or ExoPlayer is expected to choose/adapt between these 3 audio tracks.

**Comment by Taranlayal10** [comment]
Best possible way looks to add only one language based on its locale. Thanks for your time.
