### ISSUE TITLE
Codec 0x80000000 error happens using SW decoder 

### ISSUE THREAD

**Issue by bluekyu** [google/ExoPlayer#7551]
### Issue description
When SW decoder is used, codec reported 0x80000000 error in 3 seconds after ready state.
(I overridded MediaCodecSelector to select SW decoder.)

However, on playing state, the error does not happen.

In exoplayer-log.txt attachment, player is on ready state,
```
2020-06-26 20:33:33.481 16470-16737 D/EventLogger: state [eventTime=1.25, mediaPos=5.27, window=0, period=0, false, READY]
```
after about 3 seconds, "Queue" timeout happens in CCodec.
```
2020-06-26 20:33:42.314 16470-16794 W/CCodec: previous call to queue exceeded timeout
2020-06-26 20:33:42.315 16470-16791 E/MediaCodec: Codec reported err 0x80000000, actionCode 0, while in state 6
```

Note that everything is okay when I used HW decoder.

### Reproduction steps
I setup player with Surface and SurfaceTexture for GL rendering. (codes flow is similar to GL demo)
MediaCodecSelector is overrided to select SW decoder.
And I used H.264 and AAC MP4 video:
```
Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709), 1920x1080, 10846 kb/s, 30 fps, 30 tbr, 30k tbn, 60 tbc (default)
Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 317 kb/s (default)
```

### A full bug report captured from the device
[exoplayer-log.txt](https://github.com/google/ExoPlayer/files/4836743/exoplayer-log.txt)

### Version of ExoPlayer being used
2.11.5

### Device(s) and version(s) of Android being used
Pixel 2 / Android 11 beta 1
Galaxy Fold / Android 10

**Comment by bluekyu** [comment]
I guess that the error is caused by stuck of dequeueing output buffer.

The error message is on https://android.googlesource.com/platform/hardware/google/av/+/refs/heads/master/media/sfplugin/CCodec.cpp#1688
And 3 seconds deadline of queue is on https://android.googlesource.com/platform/hardware/google/av/+/refs/heads/master/media/sfplugin/CCodec.cpp#1705

**Comment by christosts** [comment]
Hi @bluekyu, thank you for reporting this. Can you please send us a bugreport obtained from the device right after the error is raised at dev.exoplayer@gmail.com, with subject "Issue #7551"? You can obtain the bugreport running `adb bugreport` from the command line (more info [here](https://developer.android.com/studio/debug/bug-report)).

**Comment by bluekyu** [comment]
Thank you for the reply! I sent a full bug report captured in Pixel 2.

**Comment by christosts** [comment]
[internal ref b/163127030]

**Comment by christosts** [comment]
Closing, issue has been addressed in Android framework, this is not an ExoPlayer issue (see internal b/163127030)
