### ISSUE TITLE
Exoplayer showing wrong orientation of some videos.

### ISSUE THREAD

**Issue by NitinSharma639** [google/ExoPlayer#7553]
Hello team

I found one bug while playing some mp4 videos hosted on amazon. While the video is in portrait exoplayer always play it in landscape. I am not able to find any specific source to solve this issue. I can provide you the link as the link is private video. I am not able to share it here. 

I am using following libraries.

 implementation "com.google.android.exoplayer:extension-mediasession:$exoplayer_version"
    implementation "com.google.android.exoplayer:exoplayer-ui:$exoplayer_version"
    implementation "com.google.android.exoplayer:exoplayer:$exoplayer_version"

exoplayer_version = "2.11.1"

Please let me know how I can resolve this.I am using  following 

  val dataSourceFactory: DataSource.Factory = DefaultDataSourceFactory(
                context,
                Util.getUserAgent(
                    context!!,
                    context!!.getString(com.becon.app.R.string.app_name)
                )
            )
            val cacheDataSourceFactory = CacheDataSourceFactory(
                DownloadUtil.getCache(context),
                dataSourceFactory,
                CacheDataSource.FLAG_IGNORE_CACHE_ON_ERROR
            );

            val mediaSource =
                ProgressiveMediaSource.Factory(cacheDataSourceFactory)
                    .createMediaSource()
Please let me know if there is some method to handle this scenario

Thanks

**Comment by kim-vde** [comment]
As you cannot share it publicly, could you send the link to the test content to dev.exoplayer@gmail.com, using subject "Issue #7553"? This would help me understand what's going on. Please also update this issue to indicate you’ve done this.

The information in #3275 could also be useful.

**Comment by NitinSharma639** [comment]
> As you cannot share it publicly, could you send the link to the test content to [dev.exoplayer@gmail.com](mailto:dev.exoplayer@gmail.com), using subject "Issue #7553"? This would help me understand what's going on. Please also update this issue to indicate you’ve done this.
> 
> The information in #3275 could also be useful.

Hi I found the issue is in file the width of the file is greater than the height but when I download it the default player (Mac) is playing it as portrait. Exoplayer is correctly playing it. Thank you very much.
