### ISSUE TITLE
Does Exoplayer support with Hybrid Android App?

### ISSUE THREAD

**Issue by kvmoondra** [google/ExoPlayer#7557]
Hello there,
Hope you are doing well.

With regards, we are developing a hybrid video news android app(from our app: we are going to distribute the hyperlocal video news feed to end-users, only video content).

For the above, we are looking to integrate Exoplayer and the technologies we are using to develop the Hybrid Android App are:
Ionic, Angular JS, Node JS & MySQL

**Does Exoplayer support with hybrid android app(Ionic, Angular Js, Node JS & MySQL)?**

Will wait to hear from you

Thanks & Regards
Kumar Vansh Moondra

**Comment by ojw28** [comment]
ExoPlayer is an Android library designed for native Android app development. We don't do anything special for other development platforms, such as Ionic. Whether Ionic supports ExoPlayer is a question you'll need to direct to the Ionic team.

**Comment by kvmoondra** [comment]
> ExoPlayer is an Android library designed for native Android app development. We don't do anything special for other development platforms, such as Ionic. Whether Ionic supports ExoPlayer is a question you'll need to direct to the Ionic team.

Thanks for your response, Oliver. I have managed to speak to Ionic support and they referred me **Cordova ExoPlayer Plugin** , more info is provided in this link: https://ionicframework.com/docs/native/android-exoplayer

**However, they suggested us to recheck with Exoplayer team**, so, can you please check the link provided above & confirm whether that plugin will work with Exoplayer or not?

It would be really appreciated if you can help us the last time.

Will wait to hear from you

Thanks & Regards
Kumar Vansh Moondra

**Comment by ojw28** [comment]
As in my previous response, we don't do anything special for other development platforms, such as Ionic.  If another development platform wishes to provide support for ExoPlayer, it's entirely the responsibility of that platform to implement and maintain an integration, or to provide sufficiently direct access such that you can build such an integration yourself.

Your link appears to link [to this project](https://github.com/frontyard/cordova-plugin-exoplayer), which looks like it hasn't received any updates for over two years. My best guess would be that this is an integration that someone created at some point, but which is now quite out of date. If that's the case, you will probably need to fork it, update it to be compatible with a recent version of ExoPlayer, and then maintain it yourselves going forward.
