### ISSUE TITLE
The memory always increases until the app is out of memory error.

### ISSUE THREAD

**Issue by allen218** [google/ExoPlayer#7558]
Before filing a bug:
-----------------------
I had searched a lot of the solution from stackOverflow or issues of this project and tried it, but I can't find any solutions to solve this memory problems.

When reporting a bug:
-----------------------
This problem always exists when I use this player and I have tried many methods, but It failed.

### [REQUIRED] Issue description
The code details following:

```kotlin
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_exo)
        player = SimpleExoPlayer.Builder(this).build()
        playerView = findViewById(R.id.play_view)
        playerView?.player = player

        val dataSourceFactory: DataSource.Factory = DefaultDataSourceFactory(
            this,
            Util.getUserAgent(this, "testExoPlayer")
        )
        uri =
            Uri.parse("${Environment.getExternalStorageDirectory()}/ad-resource/7_23143512515413.mp4")
        videoSource = ProgressiveMediaSource.Factory(dataSourceFactory)
            .createMediaSource(uri)
        player?.prepare(videoSource!!)
        player?.addListener(object : Player.EventListener {
            override fun onPlayerStateChanged(playWhenReady: Boolean, playbackState: Int) {
                if (playbackState == STATE_READY) {
                    player?.playWhenReady = true
                }
            }
        })
    }

    override fun onStop() {
        super.onStop()
        player?.release()
        player = null
        playerView?.onPause()
        playerView?.player = null
        playerView?.overlayFrameLayout?.removeAllViews()
        playerView = null
        uri = null
        videoSource = null
    }
```
The memory can't be released when the ``onStop()`` method had executed. The others of memory in profiler never decreased and the value always increased if I jumped into the current activity repeatedly.

### [REQUIRED] Reproduction steps
The example is here: https://github.com/allen218/TestExoplayer.git

### [REQUIRED] Link to test content
The video url is here: https://www.pexels.com/video/view-of-the-city-at-dusk-1826904/

### [REQUIRED] Version of ExoPlayer being used
2.11.6

### [REQUIRED] Device(s) and version(s) of Android being used
API 27 8.1

**Comment by ojw28** [comment]
If this is happening with the emulator, then it's probably an emulator bug rather than a problem with ExoPlayer. Most likely https://issuetracker.google.com/142528714. If this is happening with a real device, please provide complete information as requested in the issue template (i.e. a full bug report, and the device being used).

As a final point, `onCreate` and `onStop` are not symmetric. You should probably move what you're doing in `onCreate` to be in `onStart` instead.

**Comment by allen218** [comment]
@ojw28 OK, I‘ll try that at the real devices.

**Comment by allen218** [comment]
> If this is happening with the emulator, then it's probably an emulator bug rather than a problem with ExoPlayer. Most likely https://issuetracker.google.com/142528714. If this is happening with a real device, please provide complete information as requested in the issue template (i.e. a full bug report, and the device being used).
> 
> As a final point, `onCreate` and `onStop` are not symmetric. You should probably move what you're doing in `onCreate` to be in `onStart` instead.

You're right. The problem don't occur on the real devices.  I appreciate your help very much.

**Comment by ojw28** [comment]
@allen218 - The issue I referenced above suggests that the problem might be fixed if using an API level 29 emulator. Would it be possible for you to give this a try? They may be able to backport the fix to earlier API level emulators if verified. Thanks!
