### ISSUE TITLE
please Include  dispatchPrevious(Player player) in DefaultControlDispatcher in next release update

### ISSUE THREAD

**Issue by pawaom** [google/ExoPlayer#7559]
The dev version V2 has this code

```
@Override
  public boolean dispatchPrevious(Player player) {
    Timeline timeline = player.getCurrentTimeline();
    if (timeline.isEmpty() || player.isPlayingAd()) {
      return true;
    }
    int windowIndex = player.getCurrentWindowIndex();
    timeline.getWindow(windowIndex, window);
    int previousWindowIndex = player.getPreviousWindowIndex();
    if (previousWindowIndex != C.INDEX_UNSET
        && (player.getCurrentPosition() <= MAX_POSITION_FOR_SEEK_TO_PREVIOUS
            || (window.isDynamic && !window.isSeekable))) {
      player.seekTo(previousWindowIndex, C.TIME_UNSET);
    } else {
      player.seekTo(windowIndex, /* positionMs= */ 0);
    }
    return true;
  }
```

from this

https://github.com/google/ExoPlayer/blob/dev-v2/library/core/src/main/java/com/google/android/exoplayer2/DefaultControlDispatcher.java

the release code for version r2.11.6 still doesn't have it 

I have been waiting for the feature for the a few months now, I don't want to use the dev v2 version for my app (production) level 

all I wan to do is to override the existing feature in MediaSessionConnector

https://github.com/google/ExoPlayer/blob/release-v2/extensions/mediasession/src/main/java/com/google/android/exoplayer2/ext/mediasession/MediaSessionConnector.java

The feature I want is to override the functionality where we are forced to repeat the same song if the current duration is less than 3 seconds and instead play the previous song as its normally done in other apps, if this is included in the next release we can use it in our app without having to make changes to the original code

the basic request is we need a feature which has already been implemented in dev version, for a long time but not included in the release version

**Comment by ojw28** [comment]
Noted, but closing because it's not useful to have lots of issues just to track everything that's currently in the dev branch and hasn't made it to a release yet. This feature will not be included in future 2.11.X minor releases. It will be included in 2.12.X, which we're planning to release at some point in the next three months.
