### ISSUE TITLE
No AC3 Sound on supported device

### ISSUE THREAD

**Issue by LSDsl** [google/ExoPlayer#7563]
One of my device support AC3 from box. But during play HLS there is no sound. Logs from player

```
D/APP: mediaPeriodReleased [eventTime=113.02, mediaPos=6.42, window=0, period=0]
D/APP: timeline [eventTime=113.02, mediaPos=0.00, window=0, periodCount=0, windowCount=0, reason=RESET
    ]
D/APP: tracks [eventTime=113.02, mediaPos=0.00, window=0, []]
D/APP: loading [eventTime=113.02, mediaPos=0.00, window=0, false]
D/APP: state [eventTime=113.02, mediaPos=0.00, window=0, true, BUFFERING]
D/APP: isPlaying [eventTime=113.03, mediaPos=0.00, window=0, false]
    onIsPlayingChanged, false
D/APP: KeyEvent { action=ACTION_UP, keyCode=KEYCODE_DPAD_CENTER, scanCode=97, metaState=0, flags=0x8, repeatCount=0, eventTime=975510, downTime=975428, deviceId=3, source=0x301 }
D/APP: decoderDisabled [eventTime=113.17, mediaPos=0.00, window=0, period=0, video]
D/APP: decoderDisabled [eventTime=113.17, mediaPos=0.00, window=0, period=0, audio]
D/APP: timeline [eventTime=113.42, mediaPos=5.12, window=0, periodCount=1, windowCount=1, reason=PREPARED
      period [?]
D/APP:   window [21.08, true, true]
    ]
    mediaPeriodCreated [eventTime=113.42, mediaPos=5.12, window=0, period=0]
D/APP: loading [eventTime=113.43, mediaPos=5.12, window=0, period=0, true]
W/AudioCapabilities: Unsupported mime audio/ac3
W/MediaCodecInfo: AssumedMaxChannelAdjustment: OMX.google.ac3.decoder, [1 to 6]
W/MediaCodecInfo: AssumedMaxChannelAdjustment: OMX.google.ac3.decoder, [1 to 6]
W/MediaCodecInfo: AssumedMaxChannelAdjustment: OMX.google.ac3.decoder, [1 to 6]
W/MediaCodecInfo: AssumedMaxChannelAdjustment: OMX.google.ac3.decoder, [1 to 6]
D/APP: decoderEnabled [eventTime=113.66, mediaPos=5.12, window=0, period=0, video]
D/APP: decoderEnabled [eventTime=113.80, mediaPos=5.12, window=0, period=0, audio]
D/APP: tracks [eventTime=113.81, mediaPos=5.12, window=0, period=0
D/APP:   Renderer:0 [
D/APP:     Group:0, adaptive_supported=N/A [
          [X] Track:0, id=0, mimeType=video/avc, bitrate=6240000, codecs=avc1.4D4028, res=1920x1080, fps=25.0, supported=YES
D/APP:     ]
D/APP:     Metadata [
          HlsTrackMetadataEntry
        ]
      ]
      Renderer:1 [
D/APP:     Group:0, adaptive_supported=N/A [
          [X] Track:0, id=aac:eng a1, mimeType=audio/ac3, channels=6, sample_rate=48000, language=en, label=eng a1, supported=YES
        ]
D/APP:     Group:1, adaptive_supported=N/A [
          [ ] Track:0, id=aac:rus a2, mimeType=audio/ac3, channels=6, sample_rate=48000, language=ru, label=rus a2, supported=YES
        ]
      ]
D/APP:   Renderer:3 [
D/APP:     Group:0, adaptive_supported=N/A [
D/APP:       [X] Track:0, id=null, mimeType=application/id3, supported=YES
        ]
D/APP:     Group:1, adaptive_supported=N/A [
          [ ] Track:0, id=null, mimeType=application/id3, supported=YES
        ]
D/APP:   ]
    ]
D/APP: mediaPeriodReadingStarted [eventTime=113.83, mediaPos=5.12, window=0, period=0]
D/APP: downstreamFormat [eventTime=113.83, mediaPos=5.12, window=0, period=0, id=0, mimeType=null, bitrate=6240000, res=1920x1080, fps=25.0]
D/APP: decoderInputFormat [eventTime=113.84, mediaPos=5.12, window=0, period=0, video, id=0, mimeType=video/avc, bitrate=6240000, codecs=avc1.4D4028, res=1920x1080, fps=25.0]
I/OMXClient: MuxOMX ctor
I/ACodec: audio_extendformat:0
I/ACodec: codec does not support config priority (err -2147483648)
I/ACodec: codec does not support config operating rate (err -2147483648)
D/APP: decoderInitialized [eventTime=114.11, mediaPos=5.12, window=0, period=0, audio, OMX.google.ac3.decoder]
D/APP: decoderInputFormat [eventTime=114.12, mediaPos=5.12, window=0, period=0, audio, id=1/129, mimeType=audio/ac3, channels=6, sample_rate=48000, language=en]
D/AudioTrack: Client defaulted notificationFrames to 8208 for frameCount 16416
D/APP: videoSize [eventTime=114.51, mediaPos=5.12, window=0, period=0, 1920, 1080]
D/APP: surfaceSize [eventTime=114.62, mediaPos=5.12, window=0, period=0, 1280, 720]
D/APP: renderedFirstFrame [eventTime=114.65, mediaPos=5.12, window=0, period=0, Surface(name=null)/@0x7faadd4]
D/APP: state [eventTime=114.71, mediaPos=5.16, window=0, period=0, true, READY]
```

**Comment by LSDsl** [comment]
[bugreport-NHG47L-2020-06-29-16-40-40.zip](https://github.com/google/ExoPlayer/files/4847920/bugreport-NHG47L-2020-06-29-16-40-40.zip)

**Comment by kim-vde** [comment]
Can you send the test content? If you're unable to share it publicly, please send it to dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Please also update this issue to indicate you’ve done this.

Note that you can use the [ExoPlayer FFMEG extension](https://github.com/google/ExoPlayer/tree/release-v2/extensions/ffmpeg) to play AC-3 on all devices.

**Comment by andrewlewis** [comment]
Just to add to Kim's suggestion: this device appears to have an ac3 decoder (`OMX.google.ac3.decoder`) and we try to use it, so it may be worth setting breakpoints to check whether `DefaultAudioSink.configure` is being called (to make sure we are setting up an `AudioTrack` based on a decoder output format) and then whether `DefaultAudioSink.handleBuffer` is being called (to see if the decoder is actually producing output). If the decoder is not working as expected then the FFmpeg extension may be an option.

**Comment by LSDsl** [comment]
test link http://212.237.34.148/hls3.m3u8

@andrewlewis what I need to do?

**Comment by LSDsl** [comment]
configure and handleBuffer called.
![image](https://user-images.githubusercontent.com/1483011/86170393-bbf70900-bb23-11ea-89ab-885dda5056aa.png)

**Comment by andrewlewis** [comment]
[This forum page](https://forum.odroid.com/viewtopic.php?f=178&t=36999) suggests an Amlogic AC-3 decoder is broken: "I can see in media_codecs.xml that there is MediaCodec support for AC3 via OMX.amlogic.audio.decoder.ac3. However, when I try to use this codec to decode via the MediaCodec API I get buffers that contain all zeroes". Although the decoder has a different name, I wouldn't be surprised if it's the same problem. If you could verify that the decoder output is all-zero that would be helpful, and we can make a code change to block use of this decoder. I also filed a bug for Amlogic to take a  look [Internal ref: b/160306737].

If that's what's going wrong you may want to investigate using the FFmpeg extension as Kim suggested above.

**Comment by LSDsl** [comment]
` If you could verify that the decoder output is all-zero that would be helpful`
how I can do this?

**Comment by andrewlewis** [comment]
I'd just edit the code to loop over the bytes in the input buffer passed to `DefaultAudioSink.handleBuffer` and check if they are all zero.

**Comment by LSDsl** [comment]
Yes. they are all zero 😒

**Comment by andrewlewis** [comment]
Given the device is not a certified Android device, I'm not sure we should block use of the decoder in `MediaCodec.isCodecUsableDecoder` (it may have other compatibility issues). The other report I linked to above is similarly not from a certified Android build. I'll plan to provide an update here if we hear back from Amlogic on the internal issue.

As mentioned above, investigating using the FFmpeg extension to avoid the reliance on `MediaCodec` is probably your best bet.
