### ISSUE TITLE
Setting initial startup buffer size/time for Dash playback

### ISSUE THREAD

**Issue by biswarupdasgupta** [google/ExoPlayer#7564]
### [REQUIRED]We have a question of how to set the initial buffer size/time for DASH playback.

We are using the below parameter, wanted a confirmation if this is enough. Our chunk size is 4s.

 /**
     * The default duration of media that must be buffered for playback to start or resume following a
     * user action such as a seek, in milliseconds.
     */
    public static final int DEFAULT_BUFFER_FOR_PLAYBACK_MS = 1000; //start after downloading 1 chunk

If we use this above value for loadControl, does this mean dash file will start playing after 1s of audio + video data (i.e. 1st chunk) is downloaded?

**Comment by AquilesCanta** [comment]
As you point out, buffer for playback is `The duration of media that must be buffered for playback to start or resume following a user action such as a seek`. If you want to start playback after loading the first chunk then you should match this value and the duration of the first chunk, which is 4 seconds.

> 1s of audio + video data (i.e. 1st chunk)

I don't understand the _id est_ part of the sentence. 1 seconds of audio and video are not the first chunk. Can you clarify this?

Aside, I'd generally advise against changing the default values unless you are trying to achieve something specific. Perhaps you could roughly explain your usecase?

**Comment by biswarupdasgupta** [comment]
hi @AquilesCanta , the goal is for faster startup time. We wanted to use this configuration to start playback as soon as 1 independent decodable segment is downloaded by player. Since our chunk size is 4s and the DEFAULT_BUFFER_FOR_PLAYBACK_MS is 1s , what we understand is using this config we can make the player start playback after downloading the first audio and video segment.

Please correct me.

**Comment by AquilesCanta** [comment]
In that case I suggest you experiment with the different parameters in `DefaultLoadControl`. Specifically important are `bufferForPlaybackMs` and `bufferForPlaybackAfterRebufferMs`. In general, the smaller the values, the faster playback will transition to the READY state. But it's also more likely that it will transition to BUFFERING immediately afterwards. The unit for both parameters is milliseconds, so it has no relation with the chunk/segment size. There's plenty of material on this in this issue tracker, please have a look around. For example, #7238, #2083.

**Comment by ojw28** [comment]
> We wanted to use this configuration to start playback as soon as 1 independent decodable segment is downloaded by player. Since our chunk size is 4s and the DEFAULT_BUFFER_FOR_PLAYBACK_MS is 1s , what we understand is using this config we can make the player start playback after downloading the first audio and video segment.

To clarify, "chunk" and "segment" mean the same thing, and the duration is solely determined by the media. If your chunks/segments are 4s long, then the player will download 4s chunks/segments regardless of what value you're using.

The player does not need to download an entire chunk/segment before it can start playback. If `bufferForPlaybackMs` / `bufferForPlaybackAfterRebufferMs` are set to 1s and your chunk/segment duration is 4s, this means playback will start once a quarter of the first chunk/segment has been downloaded.

**Comment by biswarupdasgupta** [comment]
Thanks for the clarifications
