### ISSUE TITLE
SimpleCache RAM consumption

### ISSUE THREAD

**Issue by kvillnv** [google/ExoPlayer#7567]
### Searched documentation and issues
Related: https://github.com/google/ExoPlayer/issues/4253

### Subject
* **Context:** Android P - Exoplayer 2.11.7 - Android TV devices with USB-C external hard drive
Right now I have just 90GB of files in my download folder. These are DASH streams downloaded with Exoplayer 2.11.7

* The more the download folder size increases the more the RAM consumption increases when `SimpleCache` is used.
There is only one instance of `SimpleCache` in the app. It is initialized once. This `SimpleCache` is for download and playback so it has a `NoOpEvictor`
When SimpleCache initialization occurs the RAM issues starts: the heap is quickly maxed, GC is called constantly and and I very easily reach OOM.
Note: I have the same issue if I set the app in largeHeap. My app normally works fine without largeHeap.

* If I never initialize the SimpleCache I have no issue.

Here is my init, pretty basic and as described in Exoplayer demo: 
`SimpleCache(getDownloadDir(context), NoOpCacheEvictor(), getDatabaseProvider(context))`

Knowing that I could download Terabytes on an external hard drive, having the app already unusable with 90GB of downloaded content is problematic.

### Questions
* Why is the SimpleCache maxing the app's heap ?
* Most importantly is it possible reduce/control the RAM memory dedicated to the SimpleCache ?
* When starting a playback, is there a way to target precisely the cache files in order to improve loading time? (which can take up to 40 seconds and more if I keep adding content to my download folder)

I am also open to any other ideas or suggestion that would help. Thanks

--------------

FYI: My master branch is still using the method described in the related ticket (Exoplayer 2.9.6 with custom multi-folder download). 
And now I have implemented exoplayer 2.11.7 stock on my dev branch, hoping to finally be able to release it. But it seems I cannot get good performances.

**Comment by ojw28** [comment]
Note: This is related to https://github.com/google/ExoPlayer/issues/5989.

**Comment by ojw28** [comment]
Actually, it's unclear why this issue is different at all. It seems to be reporting the same thing. Marking as a duplicate.

**Comment by kvillnv** [comment]
@ojw28 you are right #5989 is related, but also old and exposes multiple issues that might be confusing. I suggest we close #5989 and keep this new ticket. 

Otherwise, please consider looking into my new questions in this new ticket. Any information I don't have could help me take decisions regarding this situation.

Thanks.

**Comment by ojw28** [comment]
Have you tried doing any debugging to work out where the RAM is being used? For example by using the [memory profiler](https://developer.android.com/studio/profile/memory-profiler)? Also, is this issue device specific, or specific to not-really-properly-certified Android TV box devices?

It would be useful if you could capture a [heap dump](https://developer.android.com/studio/profile/memory-profiler#capture-heap-dump) when the issue is occurring (before the process is killed or the device reboots), for us to take a look at. And also a bug report captured with `adb bugreport`.

**Comment by kvillnv** [comment]
> Also, is this issue device specific, or specific to not-really-properly-certified Android TV box devices?

Not device specific. All tested devices are google certified.

> Have you tried doing any debugging to work out where the RAM is being used? For example by using the memory profiler?

Yes. RAM is used in the SimpleCache.

> It would be useful if you could capture a heap dump when the issue is occurring (before the process is killed or the device reboots), for us to take a look at. And also a bug report captured with adb bugreport.

I just emailed you Heap dumps and adb bugreport

**Comment by petoknm** [comment]
@kvillnv @ojw28 Any progress on this?

**Comment by kvillnv** [comment]
No. My project does not need it anymore, we switched to cloud recording.
I see you updated your ticket in the meantime. Indeed it wasn't the same issue.
