### ISSUE TITLE
get the hls media playlist info

### ISSUE THREAD

**Issue by Gumio** [google/ExoPlayer#7570]
I want to get information on the media playlist when the player is trying to play the HLS.
Is there a better way to do this?

**Comment by AquilesCanta** [comment]
Please check out [Player.getCurrentManifest](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/Player.html#getCurrentManifest--). It should return an [HlsManifest](https://exoplayer.dev/doc/reference/index.html?com/google/android/exoplayer2/source/hls/HlsManifest.html) object. Hope this answers your question. Leaving open in case you have a follow up question. If not, please close the issue.

**Comment by Gumio** [comment]
@AquilesCanta 
Thx for the reply.

I can certainly get Segments with that. But isn't it difficult to determine the request to the segment that you're about to play back?

The player would get the HlsMediaPlaylist and request an individual segment to play. I would like to get the segment information that is attempting to skip that request.

**Comment by AquilesCanta** [comment]
> I would like to get the segment information that is attempting to skip that request.

Perhaps I'm misunderstanding. Do you want to skip the segment load? What do you intend to do with the information of the currently loading segment?

Aside, please have a look around the issue tracker. Similar questions have been asked in the past. For example, #2805, #4905.

**Comment by Gumio** [comment]
Sorry for the delay.

> Do you want to skip the segment load?
What do you intend to do with the information of the currently loading segment?

Not this one.

I want to use it for data analysis and error analysis. I want to use it to identify when and which segments were accessed, when errors occurred, etc.

You're right, https://github.com/google/ExoPlayer/issues/4905 is very similar.

Thank you for adding a new comment here.
I think I can do it this way, so I'll put it into practice.https://github.com/google/ExoPlayer/issues/4905#issuecomment-653488832.

Thank you!

**Comment by AquilesCanta** [comment]
I'll close this then. Any more questions are welcome.
