### ISSUE TITLE
Draw interactive shapes on top of SphericalGLSurfaceView? 

### ISSUE THREAD

**Issue by ar-g** [google/ExoPlayer#7574]
### Searched documentation and issues
I've looked into `gldemo` and library srcs.

### Question
I have rather design question unrelated to ExoPlayer, I'm trying to draw several shapes on top of playing 360 video, these forms will change coordinates depending on sensor position, touch data and point in time. 

What would be the best option?
- Pull `spherical` package from `library-ui` into my own project, modify it, and provide `VideoComponent` for it. Use it the similar way PlayerView is using it. I expect that it shouldn't influence the playback of 360 videos. One issue I see is that pulled sources might get outdated, although it's doesn't look as something that might change.
- Trying to use another surface view on top of it 🤔  I see the problem with gestures as those shapes I need to draw are interactive, as well as SphericalGLSurfaceView.

**Comment by andrewlewis** [comment]
I guess the things rendered on top of the video need to be synchronized with it in a frame-accurate way. That may be difficult with the second option, and I'm also not certain compositing another `SurfaceView` on top will work nicely across all devices.

So I'd go for the first option: fork the `SphericalGLSurfaceView` or at least its renderer, and modify the GL shader to show the shapes on top. I'm not sure what kind of shapes you need to draw, but it is possible to render to a `Canvas` and upload the result into a GL texture as a bitmap. A 'pure' GL implementation is probably more efficient though. I don't think we have any work planned at the moment that would make substantial changes to classes in the spherical package.
