### ISSUE TITLE
Hello, the current PS format file, 0xBD audio data currently only supports AC3, but there are actually many other encodings, such as pcm_dvd, are there any distinguishing fields in the PS byte stream?

### ISSUE THREAD

**Issue by kuailedeadai** [google/ExoPlayer#7575]
Hello, the current PS format file, 0xBD audio data currently only supports AC3, but there are actually many other encodings, such as pcm_dvd, are there any distinguishing fields in the PS byte stream?

**Comment by ojw28** [comment]
Duplicate of https://github.com/google/ExoPlayer/issues/6956.
