### ISSUE TITLE
The "buffer" variable of the processOutputBuffer in MediaCodecRenderer and MediaCodecVideoRenderer and MediaCodecAudioRenderer should be annotated @Nullable 

### ISSUE THREAD

**Issue by emilieroberts** [google/ExoPlayer#7579]
Sometimes the ByteBuffer buffer variable in ```processOutputBuffer``` of ```MediaCodecRenderer```/```MediaCodecVideoRenderer```/```MediaCodecAudioRenderer``` can be null. In Kotlin, this triggers a runtime error of:
```java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter buffer```

I believe adding ```@Nullable``` to the java will ensure these parameters are considered as a ```ByteBuffer?``` instead of a ```ByteBuffer```(ie. nullable) in Kotlin.

Current work around is to completely disable the intrinsic checkParameterIsNotNull check for the whole project in proguard by adding:
-assumenosideeffects class kotlin.jvm.internal.Intrinsics {
    public static void checkParameterIsNotNull(java.lang.Object, java.lang.String);
}

**Comment by kim-vde** [comment]
Thanks for reporting this. 

Note that the buffer should not be null in most cases. Could you explain the use case for which it is null for you?

**Comment by emilieroberts** [comment]
I see this when running my [demo program](https://github.com/chromeos/video-decode-encode-demo) on Chrome OS. It does not seem to be null on the Android phones I have tested on.

I did not do a detailed analysis but I believe there are probably some extra configuration buffers or null buffers before the stream actually starts while the Chrome OS decoder spins up? (Just a guess).

In the app, I am working around this by disabling the non-null runtime kotlin check via proguard. [See here](https://github.com/chromeos/video-decode-encode-demo/blob/master/app/proguard-rules.pro#L25).

**Comment by kim-vde** [comment]
Thanks for the extra information!

**Comment by kim-vde** [comment]
Can you confirm that the `buffer` is also null in `MediaCodecAudioRenderer`? I am asking because I would expect an NPE to be thrown in that case. Thanks!

**Comment by emilieroberts** [comment]
In my demo I am actually throwing away the audio stream ([see here](https://github.com/chromeos/video-decode-encode-demo/blob/master/app/src/main/java/dev/hadrosaur/videodecodeencodedemo/VideoHelpers/ExoUtils.kt#L51)). I assume it is null as well but have not tested.

**Comment by kim-vde** [comment]
And for videos, the buffers are null at the beginning but become non-null at some point if my understanding is correct?

**Comment by emilieroberts** [comment]
I believe so. I am extending ExoPlayer's MediaCodecVideoRenderer implementation so I assume that at some point the buffers must be non-null, since the video data comes out fine and is displayed.

On Kotlin, there is a runtime null check on values not declared nullable so it crashes when the null value comes in. If I disable the check, everything runs fine, and the video is shown, I don't see any dropped frames. To me this indicates that a null buffer must be used (or ignored) intentionally by Exo / MediaCodecVideoRenderer in some cases. In this case, when a Chromebook is used.

We could add a specific check in the code [here](https://github.com/chromeos/video-decode-encode-demo/blob/master/app/src/main/java/dev/hadrosaur/videodecodeencodedemo/VideoHelpers/VideoMediaCodecVideoRenderer.kt#L81) and log when/why a null buffer is passed in.

I would assume the same to be true for MediaCodecAudioRenderer but have not tested.

**Comment by kim-vde** [comment]
Actually, the buffer could be null in some cases (see [`MediaCodec#getOutputBuffer(int)`](https://developer.android.com/reference/android/media/MediaCodec#getOutputBuffer(int))). It is also not surprising to be able to play the video even if the buffers are null because `MediaCodecVideoRenderer#processOutputBuffer()` doesn't use the `buffer` parameter.

> We could add a specific check in the code [here](https://github.com/chromeos/video-decode-encode-demo/blob/master/app/src/main/java/dev/hadrosaur/videodecodeencodedemo/VideoHelpers/VideoMediaCodecVideoRenderer.kt#L81) and log when/why a null buffer is passed in.

This would be interesting input for us to know whether the buffer being null is expected or whether this is a bug in the Chrome OS.

> I would assume the same to be true for MediaCodecAudioRenderer but have not tested.

This would also be interesting to know if you have time to check.
