### ISSUE TITLE
Video only (i.e. no audio) live streams don't start playing when not starting at t=0.

### ISSUE THREAD

**Issue by Bastian35022** [google/ExoPlayer#758]
For pure live video content (i.e. without audio track), playback starts with a long buffering interval. This is caused by the difference in media time of the StandaloneMediaClock (always 0 initially) and the (much higher) media time of the incoming video content.

Somehow, the media start time of the video content is not propagated into the StandaloneMediaClock: its member "setPositionUs" is only called once in the demo app, caused by the call "player.seekTo(playerPosition);" in the "preparePlayer" function in the PlayerActivity, with the initial playerPosition 0.

This effect can also be observed with static content, if the media start time is much higher than 0.

I have a hard time thinking of a way to easily fix this. Will this issue be resolved? If not, i would be happy about some guidance where to start.

I only tested this behavior for DASH+MP4+AVC, if that is relevant.

**Comment by ojw28** [comment]
Yes, this is a known issue. We should fix it.

**Comment by vaszol** [comment]
this link https://bitlivedemo-a.akamaihd.net/mpds/stream-exo-liveedge.php?streamkey=bitcodin&#038;inputType=dash normal playing in commit 26 Jan 2015 @ojw28 ojw28 Fix DASH Live edge calculation.,
but non playing in current 22 jan 2016.  
how i fix it in current commit for playing my link?

**Comment by addicted2defrac** [comment]
any updates on this issue?

**Comment by ojw28** [comment]
This is fixed in 2.x.
