### ISSUE TITLE
Offline Playback Support

### ISSUE THREAD

**Issue by Taranlayal10** [google/ExoPlayer#7586]
Before filing a question:

### [REQUIRED] Searched documentation and issues
I did find an issue similar to mine. But it was closed without any comments [https://github.com/google/ExoPlayer/issues/7300](url)

### [REQUIRED] Question
I am downloading the widevine content with a license URL from some third party library which appends an token with License URL for some duration(8 hours) and after that it gets expired but the downloaded license has expiry more than this token.

When I am playing the downloaded content I am setting play URL as my file path giving the license URL but not with token this time as token that was used for downloading is not saved.

I am getting exception as below
com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect
**Update:**
If I play my downloaded Content online once then I am able to play the content offline also. Do you think this is something related to license URL itself. I am not sure about this

**My question is as this is getting played offline so how player will suppose to connect to server.**  Is it required to provide the License URL as well for offline playing of content.

Here is my code for offline playback

private fun buildMediaSource(uri: Uri): MediaSource {
        val type = Util.inferContentType(uri)
        var drmCallback: HttpMediaDrmCallback;
        if (!mDrmLicenseUrl.isNullOrBlank()) {
                drmCallback = HttpMediaDrmCallback(
                        mDrmLicenseUrl!!,
                        DefaultHttpDataSourceFactory("tplayer")
                )
            }
            mDrmSessionManager = DefaultDrmSessionManager.Builder().setMultiSession(true).build(drmCallback)
            if (isOfflineContent && offlineLicenseKeySetIdBase64 != null) {
                mDrmSessionManager!!.setMode(DefaultDrmSessionManager.MODE_PLAYBACK, Base64.decode(offlineLicenseKeySetIdBase64, Base64.DEFAULT))
            }
            mDrmSessionManager!!.addListener(mDrmHandler, this)
        }
        if (mDrmSessionManager != null) {
            return getMediaSource(type, uri, mDrmSessionManager!!)
        } else {
            return getMediaSource(type, uri)
        }
    }

### A full bug report captured from the device
com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect

### Link to test content
I can't share the content.

**Comment by Taranlayal10** [comment]
Hi Guys, Appreciate any update on this.

**Comment by AquilesCanta** [comment]
Apologies, I didn't notice I was assigned to this.

> A full bug report captured from the device

A full bug report means that you need to capture a bugreport and send it to us. You can capture a bug report using `adb bugreport`, and if you don't want to share the bugreport publicly, you can send it directly to us via dev.exoplayer@gmail.com.

- Are you downloading the license using the [OfflineLicenseHelper](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/drm/OfflineLicenseHelper.html)?
- Are you sure the offlineLicenseKeySetId you are passing the the DrmSessionManager is correctly populated? Is it not null when you are trying to play the content offline?
- Why is it stored in Base64?

**Comment by Taranlayal10** [comment]
Hello

Are you downloading the license using the OfflineLicenseHelper?
  **I am using client SDK for downloading the content & license file.**
Are you sure the offlineLicenseKeySetId you are passing the the DrmSessionManager is correctly populated? Is it not null when you are trying to play the content offline?
  **Yes the offlineLicenseKeySetId is not null & it is correct**
Why is it stored in Base64?
**Two way encryption required while download and play**

I have checked the license from the player and I am getting "LicenseDurationRemaining" as 0 second even though the license is set to a different value other than 0. This is the reason I am not able to play my downloaded content.

"PersistAllowed" -> "True"
"PlayAllowed" -> "True"
"PlaybackDurationRemaining" -> "604800"
"LicenseDurationRemaining" -> "0"
"RenewalServerUrl" -> ""
"RenewAllowed" -> "True"
"LicenseType" -> "Offline"

**Comment by AquilesCanta** [comment]
> I have checked the license from the player and I am getting "LicenseDurationRemaining" as 0 second even though the license is set to a different value other than 0. This is the reason I am not able to play my downloaded content.

Then I think this is a server-side configuration issue. License server configuration should have an option to define the license duration. Are you sure that value is correctly set?

Please provide the bug report as requested in the issue template and in my previous comment.

**Comment by Taranlayal10** [comment]
Yes the server-side configuration is correct. I have sent bug report on mail. Kindly check.

**Comment by Taranlayal10** [comment]
Hope you have received the bug report.

**Comment by Taranlayal10** [comment]
HI AquilesCanta

Did u manage to find out the cause?

**Comment by AquilesCanta** [comment]
Sorry, I hadn't seen this. I can't find anything specially useful. I can see logging that corresponds to what you describe, but I cannot theorise about the cause. @rrfrias Would you kindly take a quick look at the bugreport in case you can find anything that could point us in the direction of the issue?

Aside, @Taranlayal10. I think the best way to approach this is debugging locally. If you need me to help with that, I'll need a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that demonstrates the problem in a way that I can build locally. Specifically, I'd look into what's happening in [FrameworkMediaDrm](https://exoplayer.dev/doc/reference/index.html?com/google/android/exoplayer2/drm/FrameworkMediaDrm.html) when the offline keys are restored. There are a bunch of listeners which should get called with useful info, so I think we need to check out those.

**Comment by rrfrias** [comment]
Duration information is not logged at the plugin level so i cannot tell much from the logs.

> I have checked the license from the player and I am getting "LicenseDurationRemaining" as 0 second even though the license is set to a different value other than 0. This is the reason I am not able to play my downloaded content.

Yes, it looks like your license is expired. Do you see this right after the license is downloaded? If not, what values do you see?

**Comment by Taranlayal10** [comment]
Hi Guys, Thanks for your time. Really Appreciated.
Looks like there is some problem in the token that I am using to download the license itself.
