### ISSUE TITLE
How to cache buffer from flv stream?

### ISSUE THREAD

**Issue by ducanh3005** [google/ExoPlayer#7587]
Can you help to cache data source (buffer) of flv stream( record video of flv stream)
Thank you

**Comment by ducanh3005** [comment]
Can you help me ? @marcbaechinger

**Comment by marcbaechinger** [comment]
Sorry for my late response. Is this resolved in the meanwhile?

I understand that you are able to play that flv stream without caching. Given this works, caching for flv is very much the same as for every other media type. You need to create a `CacheDataSource` in the very same way as the [demo app does this](https://github.com/google/ExoPlayer/blob/release-v2/demos/main/src/main/java/com/google/android/exoplayer2/demo/DemoApplication.java#L175).
