### ISSUE TITLE
CPU usage too high on some tablets

### ISSUE THREAD

**Issue by rodrigoolr** [google/ExoPlayer#759]
We've received some complaints from our tablet users, mainly from Samsung Galaxy Note 10.1, about the player not working properly (missing music parts, stopping a lot during execution). It increased after we upgraded the player version from 1.3.3 to 1.4.2. I've tried to reproduce the issue in a Galaxy Tab, although it worked properly, the CPU usage gets too high (around 50%, even with the application in background while playing) and I suspect this could be the reason it could get buggy in some devices. Running the same code and same track on the Android's default media player lowers the CPU usage to below 1%. 

This issue may be related to the Android version (4.1.2) that seems to be the same on all devices, so as a workaround I'm falling back to the MediaPlayer in this version.

Do you guys have any idea what could be the issue? I can send a method profiling result of the execution if it can help.

Thanks.

**Comment by bsysop** [comment]
Are you sure this tablet are using hardware decoder? I think this is your
issue!

Em sexta-feira, 4 de setembro de 2015, Rodrigo Lessinger <
notifications@github.com> escreveu:

> We've received some complaints from our tablet users, mainly from Samsung
> Galaxy Note 10.1, about the player not working properly (missing music
> parts, stopping a lot during execution). It increased after we upgraded the
> player version from 1.3.3 to 1.4.2. I've tried to reproduce the issue in a
> Galaxy Tab, although it worked properly, the CPU usage gets too high
> (around 50%, even with the application in background while playing) and I
> suspect this could be the reason it could get buggy in some devices.
> Running the same code and same track on the Android's default media player
> lowers the CPU usage to below 1%.
>
> This issue may be related to the Android version (4.1.2) that seems to be
> the same on all devices, so as a workaround I'm falling back to the
> MediaPlayer in these versions.
>
> Do you guys have any idea what could be the issue? I can send a method
> profiling result of the execution if it can help.
>
> Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/ExoPlayer/issues/759>.
>


-- 
*Guillermo Gregorio*
Diretor: *www.alicetesla.com.br <http://www.alicetesla.com.br>*
T.: (+55) 34 91241302
Skype: b.sword

**Comment by rodrigoolr** [comment]
How exactly do I know it?

**Comment by bsysop** [comment]
There have many ways to check.

**1. With ExoPlayer**:
You can use ```MediaCodecTrackRenderer.getDecoderInfo()``` To check what Decoder your device want to use with exactly MimeType

**2. Without ExoPlayer**: Check all decoders you have in your device.
```
int numCodecs = MediaCodecList.getCodecCount();
for (int i = 0; i < numCodecs; i++) {
    MediaCodecInfo codecInfo = MediaCodecList.getCodecInfoAt(i);
    String name = codecInfo.getName();
    Log.i(TAG, "Examinig " + (codecInfo.isEncoder() ? "encoder" : "decoder") + ": " + name);
    for(String type: codecInfo.getSupportedTypes()) {
        boolean ap = codecInfo.getCapabilitiesForType(type).isFeatureSupported(MediaCodecInfo.CodecCapabilities.FEATURE_AdaptivePlayback);
        Log.i(TAG, "supports adaptive playback: " + ap);
    }
}
```

**3. Check directly in your device with ADB with less information, you just can know what decoders you got in your device** ```/system/etc/media_codecs.xml```

Maybe another people can help with another way/ideia.

Check that and post here what return to you the 1 and 2 ways, and that is easily to know if you are using software or hardware decoder, if software of course your CPU increase and maybe lose some fps in video.

**Comment by rodrigoolr** [comment]
But it's quite weird that it would consume 50% of the CPU only to play an audio, isn't it? Also, using the default MediaPlayer it goes smoothly.

Anyway, the decoder that is used (OMX.SEC.mp3.dec) is not adaptive.

**Comment by bsysop** [comment]
Try this: #251

**Comment by rodrigoolr** [comment]
He just switched to the dev branch when the issue came, those changes that solved his problem are probably already incorpored in the current release, since this issue is from january...

**Comment by bsysop** [comment]
What branch/version are you using?
Do you know full list of Decoder do you have in this device? (You can force to use one or another decoder for test that)
