### ISSUE TITLE
Amazon Firestick: Native Out of Memory error while playing 4k 

### ISSUE THREAD

**Issue by PratimMallick** [google/ExoPlayer#7591]
### [REQUIRED] Issue description
Player stops playing with out of memory in native while playing 4k content (DASH) on AFTMM firestick. This stream is encoded using h265, so it is using the hevc decoder. From the logs it looks like a native out of memory happened when GraphicBufferAllocator tried to allocate memory
```
**2020-07-03 17:49:06.417 251-1527/? E/ion: ioctl c0144900 failed with code -1: Out of memory
2020-07-03 17:49:06.417 251-1527/? E/IMGSRV: :0: MTKGenericAlloc: Allocating memory via ion heap_id_mask=0x2000 size(15716480) failed (Out of memory)
2020-07-03 17:49:06.417 251-1527/? E/Gralloc1On0Adapter: gralloc0 allocation failed: -12 (Out of memory)
2020-07-03 17:49:06.417 251-1527/? E/GraphicBufferAllocator: Failed to allocate (3840 x 2176) format 2130706439 usage 16804147: 5
2020-07-03 17:49:06.418 251-1527/? D/GraphicBufferAllocator: Allocated buffers:
    0xa74a9aa0: 8100.00 KiB | 1920 (1920) x 1080 |        1 | 0x00001a00 | FramebufferSurface
    0xa74a9be0: 8100.00 KiB | 1920 (1920) x 1080 |        1 | 0x00001a00 | FramebufferSurface
    0xa74a9d20: 8100.00 KiB | 1920 (1920) x 1080 |        1 | 0x00001a00 | FramebufferSurface
    0xa74abf80: 8100.00 KiB | 1920 (1920) x 1080 |        1 | 0x00000b00 | com.google.android.exoplayer2.demo/com.google.android.exoplayer2.demo.PlayerActivity
    0xa74ac020: unknown     | 3840 (3840) x 1472 | 7F000007 | 0x01006933 | SurfaceView - com.google.android.exoplayer2.demo/com.google.android.exoplayer2.demo.PlayerActivity
    0xa74ac700: 8100.00 KiB | 1920 (1920) x 1080 |        1 | 0x00000b00 | com.google.android.exoplayer2.demo/com.google.android.exoplayer2.demo.PlayerActivity
    0xa7c8c000: unknown     | 3840 (3840) x 2176 | 7F000007 | 0x01006933 | SurfaceView - com.google.android.exoplayer2.demo/com.google.android.exoplayer2.demo.PlayerActivity
    0xa7c8c280: unknown     | 3840 (3840) x 2176 | 7F000007 | 0x01006933 | SurfaceView
2020-07-03 17:49:06.418 251-1527/? E/BufferQueueProducer: [SurfaceView - com.google.android.exoplayer2.demo/com.google.android.exoplayer2.demo.PlayerActivity] dequeueBuffer: createGraphicBuffer failed
2020-07-03 17:49:06.418 30738-30889/com.google.android.exoplayer2.demo E/ACodec: dequeueBuffer failed: Out of memory (12)
2020-07-03 17:49:06.419 30738-30889/com.google.android.exoplayer2.demo E/ACodec: Failed to allocate output port buffers after port reconfiguration: (-12)
2020-07-03 17:49:06.419 30738-30889/com.google.android.exoplayer2.demo E/ACodec: signalError(omxError 0x80001001, internalError -12)
2020-07-03 17:49:06.419 30738-30888/com.google.android.exoplayer2.demo E/MediaCodec: Codec reported err 0xfffffff4, actionCode 0, while in state 6
2020-07-03 17:49:06.419 278-904/? D/MtkOmxVdecEx: [0xb37bb800] MtkOmxVdec::GetState (mState=OMX_StateExecuting)
2020-07-03 17:49:06.419 278-904/? D/MtkOmxVdecEx: [0xb37bb800] MtkOmxVdec::SendCommand cmd=OMX_CommandStateSet
2020-07-03 17:49:06.419 278-904/? E/MtkOmxVdecEx: [0xb37bb800] current status is MTK_OMX_OUT_PORT_ENABLE_PENDING, alloced output 4 total 10
2020-07-03 17:49:06.419 278-904/? E/MtkOmxVdecEx: [0xb37bb800] signal mOutPortAllocDoneSem (1) to cancel port enable reconfig.
2020-07-03 17:49:06.419 278-904/? D/MtkOmxVdecEx: [0xb37bb800] set MTK_OMX_VDEC_IDLE_PENDING
2020-07-03 17:49:06.420 278-904/? D/MtkOmxVdecEx: [0xb37bb800] MtkOmxVdec::GetState (mState=OMX_StateExecuting)
2020-07-03 17:49:06.420 278-30891/? D/MtkOmxVdecEx: [0xb37bb800] mPortReconfigInProgress as FALSE
2020-07-03 17:49:06.420 278-30891/? D/MtkOmxVdecEx: [0xb37bb800] # Got general command (OMX_CommandStateSet)
2020-07-03 17:49:06.420 278-30891/? D/MtkOmxVdecEx: [0xb37bb800] Request [OMX_StateExecuting]-> [OMX_StateIdle]
2020-07-03 17:49:06.420 278-30891/? D/MtkOmxVdecEx: [0xb37bb800] +FlushInputPort
2020-07-03 17:49:06.420 278-30891/? D/MtkOmxVdecEx: [0xb37bb800] --- ETBQ: mNumPendingInput 5; mEmptyThisBufQ.size() 5
2020-07-03 17:49:06.420 278-30897/? D/VDO_LOG: [h265_coreDecode] do core flush.
2020-07-03 17:49:06.420 278-30891/? I/PPFramework:  flushAllBufQ
2020-07-03 17:49:06.420 30738-30888/com.google.android.exoplayer2.demo I/MediaCodecLogger: xxx.4K.secure.HW.video.hevc.DecoderErrorFatal = 1**
```
### [REQUIRED] Reproduction steps
Play the 4k content using exo sample app. This issue only happens when switching between 2160p and 1440p. Happens sometimes while going from 1080p to 1440p layer too.
Chances of getting this error increases when seek is done multiple times or incase of network fluctions. Either ways it looks like this issue comes when there is layer change. We get the following logs from the java layer

```
07-03 20:40:03.274  5920 24142 E ExoPlayerImplInternal: Renderer error: index=0, type=video, format=Format(video/hvc1/8, null, null, video/hevc, hvc1.2.4.L150.90, 12030919, null, [2560, 1440, 23.976025], [-1, -1]), rendererSupport=NO_UNSUPPORTED_DRM
07-03 20:40:03.274  5920 24142 E ExoPlayerImplInternal: com.google.android.exoplayer2.ExoPlaybackException: java.lang.IllegalStateException
07-03 20:40:03.274  5920 24142 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.BaseRenderer.createRendererException(BaseRenderer.java:359)
07-03 20:40:03.274  5920 24142 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:725)
07-03 20:40:03.274  5920 24142 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:599)
07-03 20:40:03.274  5920 24142 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:329)
07-03 20:40:03.274  5920 24142 E ExoPlayerImplInternal: 	at android.os.Handler.dispatchMessage(Handler.java:98)
07-03 20:40:03.274  5920 24142 E ExoPlayerImplInternal: 	at android.os.Looper.loop(Looper.java:154)
07-03 20:40:03.274  5920 24142 E ExoPlayerImplInternal: 	at android.os.HandlerThread.run(HandlerThread.java:61)
07-03 20:40:03.274  5920 24142 E ExoPlayerImplInternal: Caused by: java.lang.IllegalStateException
07-03 20:40:03.274  5920 24142 E ExoPlayerImplInternal: 	at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
07-03 20:40:03.274  5920 24142 E ExoPlayerImplInternal: 	at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2584)
07-03 20:40:03.274  5920 24142 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1506)
07-03 20:40:03.274  5920 24142 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:711)
07-03 20:40:03.274  5920 24142 E ExoPlayerImplInternal: 	... 5 more
```

### [REQUIRED] Link to test content
Test content. Please use the below:
`"uri": "https://vod-1300670515.cos.ap-mumbai.myqcloud.com/hotstar_4k_test/testreel_0711/master.mpd",
        "drm_scheme": "widevine",
        "drm_license_url": "https://ipl.service.expressplay.com/hms/wv/rights/?ExpressPlayToken=BQAAABNlKb8AAAAAALDrHvw6eTXoSmBWBb5scoH90fHDb4jbIVUumrRVc7FSXRBZWjPT8eYWf5tozgL65ItF-e5O1nrMqeuoBa9OzKy3NEOxcohve7aWrkqD5ULWloUMIF6xA-ziJw7I6KKI0aJ62NMN1quYLsGll1S7eFfOvLXTg-jnhKIrr-lVbazziCDuJnkwwJaRfJRCpmbHRD06-RqJnYDp8fGdOrt7z7co8CxLzx9jX6Gm5fpcsC6RWmssVx9JZjq7-VvVaKKN6jDMxdDp"`

### [REQUIRED] A full bug report captured from the device
https://drive.google.com/file/d/16XhL0FFtBXHm8ctgGFnou--tYtTXpJmg/view?usp=sharing

### [REQUIRED] Version of ExoPlayer being used
2.11.0, 2.11.7

### [REQUIRED] Device(s) and version(s) of Android being used
Reproducible easily on AFTMM firestick model . Android SDK version 25

**Comment by PratimMallick** [comment]
@ojw28 I also tried using tunneled decoder as per your article shared here https://medium.com/google-exoplayer/tunneled-video-playback-in-exoplayer-84f084a8094d. But I was still getting this same error in addition to getting lots of jitters on the app while playback. Could you also help me understand why the method mentioned in the abv post doesnot work on Firestick 4k?

**Comment by PratimMallick** [comment]
This issue comes almost always when there is a layer switch from 1440p to 2160p. Anything in particular happening when we are trying to use the same decoder profile?

**Comment by kim-vde** [comment]
Could you share the test content? If you're unable to share test content publicly, please send it to dev.exoplayer@gmail.com using a subject in the format "Issue #7591". Please also update this issue to indicate you’ve done this.

Did you simply play the content using the demo app, or did you modify the app?

**Comment by PratimMallick** [comment]
@kim-vde We are trying to provide a stream that can be played in all geo-location. No modification done to the app except for changing the cookie setting and User Agent value to match with ours. 

The reproduction of the issue depends on the layer switches, so the best way is to seek the content multiple times and let the ABR kick in. Also having a reduced bandwidth would help

**Comment by kim-vde** [comment]
Test content has been sent to ExoPlayer email address.

**Comment by PratimMallick** [comment]
On further analysis of the issue, we pin pointed the Out of memory occuring whenever a switch is happening from 2160p to 1440p or from 1440p to 2160p. In our case both are using same decoder level and profile(**hvc1.1.6.H150.90**). Could this be causing anything unsual which is leading to the fatalerror at decoder level?

**Comment by PratimMallick** [comment]
Looks like this is another case of using the `codecNeedsReconfigureWorkaround` for this model(AFTMM) and decoder OMX.MTK.VIDEO.DECODER.HEVC as we  need to `drain and reintialize` the codec to avoid OOM when switching between 1440 and 2160. 
Another issue reported here which is similar - https://github.com/google/ExoPlayer/issues/5483

PLease suggest what is the correct way to properly handle this error. This looks like bug from exoplayer's implementaion rather than OEMs side

**Comment by PratimMallick** [comment]
Added the test content to the issue @kim-vde @ojw28

**Comment by ojw28** [comment]
If this is happening only on an Amazon device, have you reported the issue to Amazon?

**Comment by PratimMallick** [comment]
We have been able to replicate this on amazon firestick consistently by ourselves and have reported to amazon already. But we have been seeing similar logs from field devices running on android too. They all are OS 7.1 and lesser and not playing any 4k content.

In our case this issue(on AFTMM) went away after removing 1440p layer from manifest. But want to know what is the real cause for this issue?

**Comment by ojw28** [comment]
> We have been able to replicate this on amazon firestick consistently by ourselves and have reported to amazon already.

Is there a publicly visible issue filed somewhere that we can follow along on, and/or reference from this issue?

> But want to know what is the real cause for this issue?

It seems most likely that this is an issue with the underlying SoC vendor's implementation (MediaTek in this case).

**Comment by PratimMallick** [comment]
Filed the bug with amazon here --> https://github.com/amzn/exoplayer-amazon-port/issues/105

**Comment by ojw28** [comment]
Marking as a device specific issue until Amazon respond on amzn/exoplayer-amazon-port#105.

**Comment by ojw28** [comment]
Closing this because it's likely to be a device specific issue. Amazon have yet to respond on the issue ref'd above.
