### ISSUE TITLE
Duration invalid

### ISSUE THREAD

**Issue by IonAalbers** [google/ExoPlayer#760]
After updating the ExoPlayer from **1.2.4** to **1.4.2** the `getDuration()` call seems to return -1 (UNKNOWN_TIME) on some streams.
The streams are DASH with Widevine. (Therefor I cannot share an url)

Any advice on how to debug this? Or did something major change in these versions?

**Comment by ojw28** [comment]
Can you share the manifest URL? If the streams are protected by Widevine, I would have thought this would make the URL easier to share, not less. We wont be able to play the content, but the manifest and header of each stream (that's relevant for this) are normally unencrypted.

**Comment by IonAalbers** [comment]
Thanks for your response, but I got more info. It seems to be my text SampleSource that causes this.

After looking at the [duration code of the ExoPlayer](https://github.com/google/ExoPlayer/blob/450105b61f34afd34bfd6695d0388d909a9ce6c1/library/src/main/java/com/google/android/exoplayer/ExoPlayerImplInternal.java#L286) I noticed it checks all the renderers and if any of them is TrackRenderer.UNKNOWN_TIME_US it stays that way.

Now the old [HttpSampleCode](https://gist.github.com/triwav/ba72e99e5181427f4645) version had 'UNKNOWN_TIME_US' in the TrackInfo. But this was updated just a few weeks ago.

Changing the TrackInfo to `TrackRenderer.MATCH_LONGEST_US` fixes this issue.
