### ISSUE TITLE
FFmpeg Video not play in Exoplayer

### ISSUE THREAD

**Issue by Webix123** [google/ExoPlayer#7600]
Hi,

I have one question, when I create video through FFMPEG and upload on our server then play online url in Exoplayer, at a time video not playing and show "Player.STATE_IDLE" status.

This is issue facing some device which have different Codec. what should I do?

Waiting for your reply.

Thanks,
Webix

**Comment by tonihei** [comment]
Please provide all the information requested in the issue template (e.g. example media, reproduction steps, etc). Please also see the [list of supported formats](https://exoplayer.dev/supported-formats.html), if it is of any help.
