### ISSUE TITLE
Which is the "play" command?

### ISSUE THREAD

**Issue by Informatheus** [google/ExoPlayer#7601]
Sorry for the silly question but I looked in the documentation, in the references and in the demos and I couldn't find the command to be called to start the reproduction if the player.setPlayWhenReady () == false. How should I proceed?

**Comment by tonihei** [comment]
In the upcoming release there will be a method `player.play()` to make this more obvious. For now you should use `player.setPlayWhenReady(true)`. Is that what you are looking for? Please also see our [Getting started guide](https://exoplayer.dev/hello-world.html).

**Comment by tonihei** [comment]
Closing because the question was answered above. Feel free to reopen if not.
