### ISSUE TITLE
How to get Video Duration, Video Resolution and Audio Channels

### ISSUE THREAD

**Issue by ghost** [google/ExoPlayer#7603]
Hello,

I am using ExoPlayer2 in my Leanback application along with leanback extension. What I am trying to achieve here is, once the video is ready, I would like to get the total duration of the video, video resolution (2160p, 1080p, 720p etc) and also the Audio Channel (7.1, 5.1, 2.0 etc).

I am using VideoPlayerGlue along with LeanbackPlayerAdapter. How can I achieve the above mentioned funcionality?

Thanks.

**Comment by tonihei** [comment]
Have you tried `player.getDuration` and `player.getCurrentTrackSelections`? The `TrackSelections` contain a list of `Format` objects with resolution, audio channels etc.

**Comment by tonihei** [comment]
Closing because the questions was answered above. Feel free to reopen if not.
