### ISSUE TITLE
Error playing m3u: Input does not start with the #EXTM3U header

### ISSUE THREAD

**Issue by stefanhh0** [google/ExoPlayer#7605]
### Issue description
Playing an m3u radio audio stream using the Transistor app v4.0.1 (https://github.com/y20k/transistor)  
fails due to an exo player failure.

Streaming address: http://www.ndr.de/resources/metadaten/audio/m3u/ndrkultur.m3u

Log:
```
07-07 23:34:55.997 13530 13530 W ConstraintHelper: Could not find id of "@+id/sheet_metadata_history"
07-07 23:34:56.006 13530 13530 D MediaBrowserCompat: Connecting to a MediaBrowserService.
07-07 23:34:56.082 13530 13530 I ExoPlayerImpl: Init 67f6314 [ExoPlayerLib/2.11.7] [lilac, Xperia XZ1 Compact (AOSP), Sony, 29]
07-07 23:34:58.978 13530 13530 W transistor_PlayerService: Unhandled player state change.
07-07 23:34:58.981  1062  9117 I MediaFocusControl: requestAudioFocus() from uid/pid 10118/13530 clientId=android.media.AudioManager@3bc8aa1m.b.a.a.p$a@60d2a57 callingPack=org.y20k.transistor req=1 flags=0x0 sdk=29
07-07 23:34:59.349 13530 19327 E ExoPlayerImplInternal: Source error
07-07 23:34:59.349 13530 19327 E ExoPlayerImplInternal:   m.b.a.a.z0.d0: Input does not start with the #EXTM3U header.
07-07 23:34:59.349 13530 19327 E ExoPlayerImplInternal:       at m.b.a.a.z0.g0.t.g.a(SourceFile:33)
07-07 23:34:59.349 13530 19327 E ExoPlayerImplInternal:       at m.b.a.a.d1.b0.a(SourceFile:8)
07-07 23:34:59.349 13530 19327 E ExoPlayerImplInternal:       at m.b.a.a.d1.a0$d.run(SourceFile:6)
07-07 23:34:59.349 13530 19327 E ExoPlayerImplInternal:       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
07-07 23:34:59.349 13530 19327 E ExoPlayerImplInternal:       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
07-07 23:34:59.349 13530 19327 E ExoPlayerImplInternal:       at java.lang.Thread.run(Thread.java:919)
```

### Reproduction steps
Try play http://www.ndr.de/resources/metadaten/audio/m3u/ndrkultur.m3u with org.y20k.transistor using ExoPlayerLib/2.11.7

### Link to test content
http://www.ndr.de/resources/metadaten/audio/m3u/ndrkultur.m3u

### A full bug report captured from the device
[bugreport-aosp_g8441-QQ3A.200705.002-2020-07-08-00-03-30.zip](https://github.com/google/ExoPlayer/files/4887392/bugreport-aosp_g8441-QQ3A.200705.002-2020-07-08-00-03-30.zip)

### Version of ExoPlayer being used
ExoPlayerLib/2.11.7

### Device and version of Android being used
Sony Xperia XZ1 Compact 
Android version 10, security update: 5 July 2020

**Comment by tonihei** [comment]
`m3u` playlists are not supported yet, see #4066.
