### ISSUE TITLE
Video gets crop from edges when set resize option to zoom

### ISSUE THREAD

**Issue by prashantj17** [google/ExoPlayer#7606]
Issue description
Video gets crop from edges when set resize option to zoom,full video must  be shown but only centre part of video is shown.

 Reproduction steps.
set the resize option to zoom for exoplayer in xml and play the video.

Version of ExoPlayer being used
2.7.3

Device(s) and version(s) of Android being used
OS Android 9 and Android 10 with Vivo y17, Samsung M30

**Comment by tonihei** [comment]
I'm not completely sure whether I understand the documentation correctly, but I think this is working as intended. The resize mode zoom increases the width or height of your video to fill your surface and thus some parts of the video will be cropped. @ojw28 may be able to confirm.

**Comment by ojw28** [comment]
Yes, cropping is expected if using `zoom`. It's unclear what you're trying to achieve, but perhaps you want to use `fill` instead.
