### ISSUE TITLE
Playing redirect URL

### ISSUE THREAD

**Issue by wishy-viewlift** [google/ExoPlayer#7609]
There is a service provider which hosts videos for my client and have given us a redirect URL something like this
[Redirect URL](https://justice-avod.amagi.tv/vod?c=justiceAA-justiceonoavod&a=BM1145&redirect_path=https://justice-avod.amagi.tv/justiceAA-justiceonoavod/BM1145/playlist.m3u8)
How can I get this to be played?

In the logs I see the error
      `None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor, AmrExtractor, Ac4Extractor, FlacExtractor) could read the stream`

I am using the allowcrossprtocol

           ` new DefaultHttpDataSourceFactory(userAgent, bandwidthMeter, DefaultHttpDataSource.DEFAULT_CONNECT_TIMEOUT_MILLIS,
                DefaultHttpDataSource.DEFAULT_READ_TIMEOUT_MILLIS, true);`

**Comment by ojw28** [comment]
Please see https://github.com/google/ExoPlayer/issues/7614.
