### ISSUE TITLE
Does the Exoplayer support HLS streaming with separate audio video sources?

### ISSUE THREAD

**Issue by lucascauthen** [google/ExoPlayer#761]
I am working with an HLS manifest that separates out the audio and video for a stream. (Both having variants for different quality/bandwidth) Plugging in the HLS stream I am working into the demo player results in only audio playing through the demo player and the screen remaining black. It also doesn't show the video button at the top of the video like the sample HLS videos in the demo.

Is this because separate audio/video sources in HLS streaming is not currently supported?

**Comment by ojw28** [comment]
See #73
