### ISSUE TITLE
offline videos getting java.lang.IllegalArgumentException: Failed to restore keys 

### ISSUE THREAD

**Issue by gokulkalagara** [google/ExoPlayer#7610]
### [REQUIRED] Issue description
I got playback exception for offline video
com.google.android.exoplayer2.drm.DrmSession$DrmSessionException: java.lang.IllegalArgumentException: Failed to restore keys

### [REQUIRED] Reproduction steps
I downloaded the protected dash video while playing an offline video
I got this exception

### [REQUIRED] Version of ExoPlayer being used
Exoplayer 2.11.6

### [REQUIRED] Device(s) and version(s) of Android being used
Brand: OnePlus, Model: IN2011, OS: 10
Brand: Realme, Model: RMX1992, OS: 10

**Comment by tonihei** [comment]
Offline license download isn't managed automatically by ExoPlayer yet. How do you download and restore the keys? It would be helpful to understand your setup in order to see potential problems.

@ojw28 Could you take a look?

**Comment by ojw28** [comment]
@gokulkalagara - Please properly fill out the issue template, including providing a full bug report captured from the device shortly after the failure occurs.

**Comment by SandraViJu** [comment]
I have a same error when try to playing offline video, the error reported by firebase is these:

<img width="1127" alt="Captura de pantalla 2020-10-07 a las 15 00 02" src="https://user-images.githubusercontent.com/70659518/95334047-e2101000-08ad-11eb-8c9e-bd223b920214.png">

Some devices with this error: 
Samsung Galaxy Tab A Android 10
Samsung Galaxy A7(2018) Android 10
Samsung Galaxy S9 Android 10
