### ISSUE TITLE
The special url include ".m3u8" in the parameter, not in the path cannot play.

### ISSUE THREAD

**Issue by wywy4pm** [google/ExoPlayer#7614]
The url include ".m3u8" in the parameter, not in the path,then Util.inferContentType cannot return the C.TYPE_HLS,so the m3u8 url cannot use HlsMediaSource to play,the video cannot play.

**Comment by wywy4pm** [comment]
This type of address can play use vlc or mxplayer，so i hope exo can play so.

**Comment by AquilesCanta** [comment]
If the extension is not part of the path, you'll have to manually indicate the type of media.

In the demo app this is done by adding an entry to the sample:
`"extension": "m3u8"`
in the media samples json file. 

If you are trying to play the file in your own app then you just have to create an HlsMediaSource for your URL. `Util.inferContentType ` is just a best effort heuristic based on the file extension so it's ok to override any returned value. 

Please clarify the issue to me if you have further questions. #3165 tracks MediaSource-level sniffing.

**Comment by AquilesCanta** [comment]
Closing. Please feel free to comment below if you have further questions.
