### ISSUE TITLE
Google Assistant Voice Commands not working on AndroidTV

### ISSUE THREAD

**Issue by aureobeck** [google/ExoPlayer#7615]
### Searched documentation and issues
Official `ExoPlayer` documentation and source code of `MediaControllerCompat`, `MediaSessionConnector`, `MediaSession` classes.

### Question
We've noticed that on new version from Google app for Androidtv release on June 13 (4.2.0.314209501) is not calling any callbacks on `MediaSessionConector`'s `DefaultMediaMetadataProvider` such as `onPause`, `onPlay`, `onSeekTo`.

On version 3.14.2.312211540 (May 20) of Google app it's still working as expected with Exoplayer 2.11.7

**Comment by tonihei** [comment]
That sounds more like an issue with the Google app instead of an ExoPlayer issue. Have you tried reporting this to them?

**Comment by aureobeck** [comment]
@tonihei , we could open an issue at their side as well, but we've made some tests on other apps which are working as expected, so perhaps we could just be sure that it's nothing at our side. This is how we implement our player, could you please confirm if you see anything unexpected, thanks!

**ControlDispatcher:**
```
private class MyControlDispatcher extends DefaultControlDispatcher {
	@Override
	public boolean dispatchSetPlayWhenReady(Player player, boolean playWhenReady) {
		...
		return true;
	}

	@Override
	public boolean dispatchSetRepeatMode(Player player, int repeatMode) {
		return false;
	}

	@Override
	public boolean dispatchSetShuffleModeEnabled(Player player, boolean shuffleModeEnabled) {
		return false;
	}

	@Override
	public boolean dispatchStop(Player player, boolean reset) {
		...
		return true;
	}

	@Override
	public boolean dispatchSeekTo(Player player, int windowIndex, long positionMs) {
		...
		return true;
	}
}
```
**MediaSessionConnector:**
```
MyControlDispatcher myControlDispatcher = new MyControlDispatcher();
MediaSessionCompat mediaSession = new MediaSessionCompat(context, TAG);
MediaSessionConnector mediaSessionConnector = new MediaSessionConnector(mediaSession);
mediaSessionConnector.setControlDispatcher(myControlDispatcher);
```
**Initialization of player:**
```
SimpleExoPlayerView simpleExoPlayerView = new SimpleExoPlayerView(context);
SimpleExoPlayer player = new SimpleExoPlayer.Builder(getContext(), renderersFactory)
							.setTrackSelector(trackSelector)
							.setLoadControl(new DefaultLoadControl())
							.build();

simpleExoPlayerView.setPlayer(player);
mediaSessionConnector.setPlayer(player);
mediaSession.setActive(true);
```

**Comment by tonihei** [comment]
The provided code looks fine to me. When you say "commands are not working", I assume you mean that none of these `ControlDispatcher` methods is called? 

@marcbaechinger Could you take a look too to verify that I don't miss something here?

**Comment by aureobeck** [comment]
I'm getting `dispatchSetPlayWhenReady` with `playWhenReady=false` when Google Assistant is opened, but then after the command is identified it doesn't call apropriate callback. For example "fast forward" or "rewind" doesn't call `dispatchSeekTo`.

**Comment by marcbaechinger** [comment]
Does look similar as with #7396 when an update tof the Google app eventually solved the issue. That's very unfortunate to happen again. If the commands do not arrive at the media session callback we can't really do something. Do you have the chance to verify whether the commands are being sent. Like setting a breakpoint in the [callback of the `MediaSessionConnector`](https://github.com/google/ExoPlayer/blob/release-v2/extensions/mediasession/src/main/java/com/google/android/exoplayer2/ext/mediasession/MediaSessionConnector.java#L1209)?

**Comment by aureobeck** [comment]
@marcbaechinger I've added breakpoints on `MediaSessionConector` and I'm only getting `OnPause` when Google Assistant is opened, no other callback is being called on voice command :((

**Comment by aureobeck** [comment]
Tested on 4.2.1.320059654 (July 20) and same problem occurs, should I open an issue on katniss side? @marcbaechinger

**Comment by aureobeck** [comment]
Any updates on this @marcbaechinger ? Tested on Google app 4.2.1.323041977 (July 25) issue still occurs

**Comment by marcbaechinger** [comment]
Difficult to diagnose why you only receive a `onPause`. You need to find out why no acton arrives from Assistant.

Can you do a 

`adb shell dumpsys media_session`

while your app is running and ready to receive media session commands and a paste the output here?

You can also create your own `MediaControllerCompat` and connect to the media session that you are exposing with the `MediaSessionConnector`. Then you can send the command yourself and check whether the connector is correctly setup. If this works, you are sure that you need to dig into the question why assistant is not sending commands to you.

**Comment by aureobeck** [comment]
Greetings, thank you for the answer, after a few more investigation we've noticed the application was restarting playback before Exoplayer had the chance to perform the command. This was related to multi-window support introduced on API 23, therefore Google Assistant started calling `onPause` and pausing the playback. As [doc ](https://developer.android.com/guide/topics/ui/multi-window#lifecycle) the solution was: 

> we recommend that activities that play video not pause video playback in response to the ON_PAUSE lifecycle event. Instead, the activity should begin playback in response to ON_START, and pause playback in response to ON_STOP
