### ISSUE TITLE
mts, m2ts format can not be played in exoplayer

### ISSUE THREAD

**Issue by kuailedeadai** [google/ExoPlayer#7616]
Hello, mts, m2ts format can not be played in exoplayer? May I ask when to integrate?

**Comment by AquilesCanta** [comment]
It's impossible to assist you with this amount of information. MPEG-2 Transport Streams are supported by ExoPlayer. Please provide all the information requested in the issue template and we'll take a look. Issue template [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md).
