### ISSUE TITLE
Buffer stalls without doing so for initial load and seeking

### ISSUE THREAD

**Issue by zhanhuang** [google/ExoPlayer#7618]
### [REQUIRED] Searched documentation and issues
related question: https://github.com/google/ExoPlayer/issues/1344

### [REQUIRED] Question
I tried to implement the check described, which is just entering Buffering state with playWhenReady on.
However, this event is triggered on initial load and seek as well, which are not actual stalls.

Is there a way Exoplayer could emit events for this like AVPlayer's [AVPlayerItemPlaybackStalled](https://developer.apple.com/documentation/foundation/nsnotification/name/1387661-avplayeritemplaybackstalled), or do I just have to add logic to check for these cases?

**Comment by tonihei** [comment]
You could either try to detect that yourself or add a [`PlaybackStatsListener`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/analytics/PlaybackStatsListener.html) that returns a `PlaybackStats` object with [`getMeanRebufferCount`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/analytics/PlaybackStats.html#getMeanRebufferCount--) to retrieve the average number of rebuffers per playback. If there is only one playback, this is your stall count.

**Comment by tonihei** [comment]
Closing because the question was answered above. Feel free to reopen if not.
