### ISSUE TITLE
Audio playback is not smooth when set the playback speed with 2.0x on a specific device

### ISSUE THREAD

**Issue by rishun-fsi** [google/ExoPlayer#7623]
Hello,

When I play a widevine content on 2.0x speed, the audio is breaking up and generated some noises.

It occurred only a specific model phone and widevine content.

And, this issue occurs all the time at a certain time.
But at another certain time, it only happens about once every 10 times.

Could you confirm this issue and please tell me how to avoid the problem.

# Issue description
 ・AQUOS R (Android 9)(SH-03J)
 ・Exo ver 2.11.6(1a5b304)
 ・content：[https://storage.googleapis.com/wvmedia/cenc/h264/tears/tears.mpd]
 ・License Server：[https://proxy.uat.widevine.com/proxy?video_id=d286538032258a1c&provider=widevine_test]

# Reproduction steps
 1.  Inside  `PlayerActivity.java` `initializePlayer()` method,  I implemented the below.
```bash
player = new SimpleExoPlayer.Builder...

PlaybackParameters parameters = new PlaybackParameters(2.0f);
player.setPlaybackParameters(parameters);
```
2. Launch the Exo demo app.
3. Play the content(listed in the issue description section) at double speed.

About details, please check the attached file below.
[bugreport-SH-03J-RB09A-2020-07-08-14-36-03.zip](https://github.com/google/ExoPlayer/files/4918134/bugreport-SH-03J-RB09A-2020-07-08-14-36-03.zip)

[reproduce.zip](https://github.com/google/ExoPlayer/files/4918180/reproduce.zip)

**Comment by Samrobbo** [comment]
Hi,

Based on the bug report and the information given, it looks as though the audio buffer is underrunning frequently. This can be related to several things, but it seems likely that the playback speed adjustment is blocking the playback thread for too long, which causes the audio buffer to not be written to as frequently as needed. A potential fix for this would be to use the frameworks speed adjustment (as opposed to our current approach of having it as part of ExoPlayer), which is being tracked here in #7502. 

Curiously, does this same issue occur with non widevine content? 

Thanks.

**Comment by rishun-fsi** [comment]
Hello @Samrobbo ,
The same issue does not occur with non widevine content.
Why widevine and non widevine contents have two different behavior, could you explain it?

Thanks.

**Comment by Samrobbo** [comment]
My understanding is that widevine content needs to be decrypted, which takes some processing time. As a result, each sample takes longer to process and not as many are written to the buffer. 

Because of this, you can see these issues whereby the audio buffer underruns (being read faster than written to), and audio issues begin. 

As mentioned above, #7502 is tracking a change to make use of the frameworks built in speed adjustment, which we believe will reduce the frequency of audio underruns when playing at a faster speed.
