### ISSUE TITLE
Unable to play AES encrypted m3u8 url using Exoplayer(version 2.11.7). 

### ISSUE THREAD

**Issue by arshuk007** [google/ExoPlayer#7624]
I am trying to play AES encrypted m3u8 video in exoplayer. I don't want to download the file and decrypt it. I just want to stream online. Kindly help on this. Any help/suggestions would be appreciated.

**Comment by Samrobbo** [comment]
Hi,

Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md). If you're unable to share bug reports or test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Please also update this issue to indicate you’ve done this.

Thanks.

**Comment by arshuk007** [comment]
> Hi,
> 
> Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md). If you're unable to share bug reports or test content publicly, please send them to [dev.exoplayer@gmail.com](mailto:dev.exoplayer@gmail.com) using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Please also update this issue to indicate you’ve done this.
> 
> Thanks.

Hi,

I have sent you the mail with details. Kindly check. Please let me know any other details required from my end.

Thanks.

**Comment by ojw28** [comment]
Your HLS playlist is referencing a file called `enc.key`, but it doesn't appear that it exists on the server. Or at least, attempting to request it returns a HTTP 403 response. Playback of this stream does not work in VLC or Safari either, presumably for the same reason. I think you need to make sure that this file is present and that the player is able to request it.
