### ISSUE TITLE
volume automatically increase on video play back and  on seek bar position change

### ISSUE THREAD

**Issue by Gaurav328** [google/ExoPlayer#7627]
we are facing this issue only on Jio stb android version 7.0. exoplayer volume do not work with audio manager. exoplayer volume automatcally increase on video playback and on seek bar position change while audio manger volume remain in same state. after up/down device volume exoplayer volume  behavior normally.

**Comment by Samrobbo** [comment]
Hi, can I get some more information about this?

- What version of ExoPlayer are you using? 
- Does this occur with any media, or only specific videos/audio clips? If specific, please provide a link to this media. 
- What code executes on your side as a result of seeking? 
- You mentioned only facing the issue on the Jio set-top box, have you tested whether the same thing happens on different set-top boxes? 

Thanks. 

In general, now and in future, please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md). If you're unable to share bug reports or test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Please also update this issue to indicate you’ve done this.

**Comment by Gaurav328** [comment]
1. ExoPlayer  version: 2.11.3
2. only  specific  device (jio setup box android version 7.0)
4. Working fine on other version of jio setup and other devices (android tv, mi tv, fire tv)

**Comment by Samrobbo** [comment]
- Does this occur with any media, or only specific videos/audio clips? If specific, please provide a link to this media. 
- I also would ideally need a snippet of any custom code that executes as result of a seek.

**Comment by piyush2dev** [comment]
Facing Same Issue. Can someone help here.

ExoPlayer version: 2.11.3
(jio setup box android version 7.0)
