### ISSUE TITLE
Offline downloaded unable to play, showing error unable to connect host

### ISSUE THREAD

**Issue by gokulkalagara** [google/ExoPlayer#7629]
### [REQUIRED] Issue description
Offline downloaded unable to play, They need internet to play the videos

### [REQUIRED] Reproduction steps
I download the dash protected video with license, sometimes they are unable to play the videos
Still, the license is not expired
**Getting PlaybackException**
com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect

### [REQUIRED] Version of ExoPlayer being used
**EXO-PLAYER 2.11.6**

### [REQUIRED] Device(s) and version(s) of Android being used
Brand: Realme X2, Model: RMX1992, OS: 10

**Comment by ojw28** [comment]
There is nothing we can do with this kind of report. _Please_ properly fill out the issue template. Providing only the very top line of a stack trace is not sufficient information for us to help. Note that we've requested you properly fill out the issue template _repeatedly_ on issues that you've filed. For all future issues you file, _please_ either fill out the issue template properly, or clearly explain why you're unable to do so in the issue itself.

**Comment by gokulkalagara** [comment]
I sent an email @ojw28, please cross-check with device bug report also

**Comment by ojw28** [comment]
The bug report provided does not capture the point at which the failure occurred, and therefore I would conclude that it was not captured shortly after encountering the issue. If it were, the full stack trace starting with:

```
com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect
```

would be present in the bug report. Closing because there's nothing we can do without a higher quality report.

**Comment by gokulkalagara** [comment]
You close the issue but the issue still exists

@ojw28 I will create a new issue, we take the report  from the users, not from my phone, Redmi and Realme not storing the proper bug reports, 
there is only one bug report, we are getting not like stock android os
