### ISSUE TITLE
Disabling  subtitles

### ISSUE THREAD

**Issue by rajyvan** [google/ExoPlayer#763]
Hi, 

When I disable subtitles, I get the last one displayed frozen on the screen. 
Is there a way to totally disable subtitles?
Thanks.

**Comment by ojw28** [comment]
This is a bug affecting only the current dev branch (not the latest release on the master branch). We'll push a fix today.

**Comment by rajyvan** [comment]
Alright. Thanks!

**Comment by rajyvan** [comment]
Thanks !
