### ISSUE TITLE
is it possible to set formant in audio track?

### ISSUE THREAD

**Issue by ckdrb7017** [google/ExoPlayer#7631]
Hi.
I try setting formant in audio track. I found the AuxEffectInfo class, but it has only one option, default no-setting value. And there is no any examples about this setting. I want to add audio effect like echo in audio track.

**Comment by krocard** [comment]
If you are trying to implement a custom effect for an ExoPlayer, derive the [AudioProcessor](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/audio/AudioProcessor.html) class to implement it, then inject your effect using any of the [DefaultAudioSink constructors](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/audio/DefaultAudioSink.html#DefaultAudioSink-com.google.android.exoplayer2.audio.AudioCapabilities-com.google.android.exoplayer2.audio.AudioProcessor:A-).

If you are trying to enable a platform effect on an ExoPlayer track, you need to retrieve the audiosession using `Player.getAudioSessionId()` and then use the [Android effect framework](https://developer.android.com/reference/android/media/effect/Effect) to attach effects.

**Comment by krocard** [comment]
Please reopen if your question is not answered.

**Comment by krocard** [comment]
https://github.com/google/ExoPlayer/issues/6705#issuecomment-633942165 has a nice snippet on how to inject an AudioProcessor.
