### ISSUE TITLE
How to use LeanbackPlayerAdapter?

### ISSUE THREAD

**Issue by CloneTV** [google/ExoPlayer#7636]
I don't quite understand how the LeanbackPlayerAdapter class can be used.

example1: where is not support `Sample` interface?

```
            DefaultRenderersFactory renderersFactory = new DefaultRenderersFactory(getContext());
            Renderer[] r = new Renderer[] {(Renderer) renderersFactory};
                                              ^^^^^^^ BAD CASTING!
            Player player = ExoPlayerFactory.newInstance(
                    getContext(),
                    r,
                    new DefaultTrackSelector(),
                    new DefaultLoadControl()
            );

```

example2: where add `LeanbackPlayerAdapter` to `ControlGlue` ??
```
            LeanbackPlayerAdapter adapter = new LeanbackPlayerAdapter(getContext(), player, 1000);
            mTransportControlGlue = new PlaybackTransportControlGlue<LeanbackPlayerAdapter>(getContext(), adapter);
                                                                                          NO CAST! ERROR! ^^^^^
```

> Required type: `PlaybackTransportControlGlue<MediaPlayerAdapter>`
> Provided: `PlaybackTransportControlGlue<LeanbackPlayerAdapter>`
> 

```
           OR
            mTransportControlGlue = new PlaybackTransportControlGlue<MediaPlayerAdapter>(getContext(), (MediaPlayerAdapter) adapter);
                                                                                          NO CAST! ERROR! ^^^^^^^^^^^^^^
```

> Inconvertible types; cannot cast 'com.google.android.exoplayer2.ext.leanback.LeanbackPlayerAdapter' to 'androidx.leanback.media.MediaPlayerAdapter'

**Comment by marcbaechinger** [comment]
What is the type of the member variable `mTransportControlGlue` in your code? I think it should be 

```
PlaybackTransportControlGlue<LeanbackPlayerAdapter> mTransportControlGlue;
```

whereas the output you get 

```
Required type: PlaybackTransportControlGlue<MediaPlayerAdapter>
```

suggests, it is `PlaybackTransportControlGlue<MediaPlayerAdapter>`. Can you double check that you are using `PlaybackTransportControlGlue<LeanbackPlayerAdapte>`?
