### ISSUE TITLE
Use of downloaded content in different player

### ISSUE THREAD

**Issue by rahulsDia** [google/ExoPlayer#7643]
I downloaded a content in Exoplayer download manager, Can i play that content in any other player which is not based on Exoplayer

**Comment by krocard** [comment]
Marc, searching in your doc https://exoplayer.dev/downloading-media.html, I could not find if maybe the media can be retrieved from eg the MediaStore.

Do you mind answering this question?

**Comment by marcbaechinger** [comment]
ExoPlayer is storing downloaded media data in an internal format which is not designed to be played by other players than ExoPlayer I'm afraid.
