### ISSUE TITLE
Handle playernotificationmanager while other app is playing video / audio?

### ISSUE THREAD

**Issue by wishy-viewlift** [google/ExoPlayer#7645]
I have incorporated  playernotificationmanager for vidoeplayer in my app. The video's sound plays in the background which is a requirement. I am not able to get the audio focus for other app.
For eg : My app is playing the audio of the video in the background now I open youtube and play the audio I don't get the callback in audio focus. I am running on Android 10.
This is my code 

```java
protected boolean requestAudioFocus() {
        AudioManager am = (AudioManager) getApplicationContext()
                .getSystemService(Context.AUDIO_SERVICE);
        int result = am.requestAudioFocus(this,
                AudioManager.STREAM_MUSIC,
                AudioManager.AUDIOFOCUS_GAIN);
        if (result == AudioManager.AUDIOFOCUS_REQUEST_GRANTED) {
            mAudioFocusGranted = true;
        }
        return mAudioFocusGranted;
    }
```

Will this work or is there anything which exoplayer provides?

**Comment by krocard** [comment]
With exoPlayer, you can either
 1) manage audiofocus in your app, independently of ExoPlayer, which your snippet suggest you are doing,
 2) have ExoPlayer handle it: https://medium.com/google-exoplayer/easy-audio-focus-with-exoplayer-a2dcbbe4640e

You seem to use the first option. So your code is not ExoPlayer specific in any way. Thus I don't think we can help you debug your app, especially without its code.

Tip: you can see which app(s) has the audiofocus by running `adb shell dumpsys audio`.
