### ISSUE TITLE
How can I Show Image or Text into PlayerView with duration which is configured like video in the same Playlist

### ISSUE THREAD

**Issue by AndersonCrew** [google/ExoPlayer#7646]

**Comment by krocard** [comment]
Are you trying to build something like a slideshow? With images and text alternating/superposing?

For text, you could play subtitles but you will be limited in customisation.
For images, ExoPayer has no builtin ways to display an image.

You will have to build you own custom renderer, see also https://github.com/google/ExoPlayer/issues/2874

**Comment by krocard** [comment]
We do no plan to support playing images currently, closing this enhancement request.

Please reopen if I misunderstood your request.
