### ISSUE TITLE
Does ExoPlayer supports CMAF for DASH streams?

### ISSUE THREAD

**Issue by PavelGP** [google/ExoPlayer#7649]
### Searched documentation and issues
Look through ExoPLayer documentation and questions on GitHub but didn't find straight answer on my question. Can find only info about HLS streams, but not about DASH.

### Question
Does ExoPlayer oficially supports CMAF for DASH streams? Which DRMs are applicable in this case? Should I setup any special settings for ExoPlayer to support CMAF playback?

**Comment by ojw28** [comment]
Supported DRM configurations are documented [here](https://exoplayer.dev/drm.html). Aside from making sure you use a supported DRM configuration, I would expect use of CMAF segments in DASH to just work without you having to do anything special.

**Comment by PavelGP** [comment]
Thank you.
