### ISSUE TITLE
Make behaviour when dropping off back of live streams consistent across DASH/SS/HLS

### ISSUE THREAD

**Issue by ojw28** [google/ExoPlayer#765]
DASH/SS live playbacks currently fail with BehindLiveWindowException, where-as for HLS we currently skip ahead to the live edge and allow playback to continue with a discontinuity. We should make the behaviour consistent everywhere.

**Comment by ChernyshovYuriy** [comment]
Hi,
Is there any updates so far on this issue?
We facing BehindLiveWindowException for the Widevine mpegdash protected content when throttling network, for instance up to 250 kbit/sec. However, player works fine with the high speed network.

**Comment by ChernyshovYuriy** [comment]
Hi,
Would like to ask, is there any hints that you can provide how to implement this functionality? I can try to manage it by myself. BehindLiveWindowException is blocking to play livestream in the low speed network, like LTE or 3G.
I know that this could be server side issue with amount of data available to play for a lice stream, but while our server team investigates it, is there any clue to try to do it from ExoPlayer side?
Thanks in advance.

**Comment by ojw28** [comment]
We now consistently throw `BehindLiveWindowException` for DASH/SS/HLS, so the inconsistency tracked by this issue is resolved.
