### ISSUE TITLE
exoplayer doesn't accept * character in url 

### ISSUE THREAD

**Issue by newtestpage** [google/ExoPlayer#7655]
Hi 
I faced a problem when I want to pass a url to exoplayer that  include "*" in url . My url has 2 part like follow :

part1*part2
and when I want to pass whole url to exoplayer it just identify part1 and leave part 2. I should mention I fetched this url and I can not  change it's structure . 
Any suggestion or help ?

**Comment by krocard** [comment]
> and leave part 2

What do you mean by that, are you sniffing the ExoPlayer network request or in some other way?
Could you share the problematic URL?

Wild guess, but how are you passing the URL to ExoPlayer? If it is through the shell, you might need to % encode it (`%2A`) or escape it (`\*`)

**Comment by newtestpage** [comment]
> > and leave part 2
> 
> What do you mean by that, are you sniffing the ExoPlayer network request or in some other way?
> Could you share the problematic URL?
> 
> Wild guess, but how are you passing the URL to ExoPlayer? If it is through the shell, you might need to % encode it (`%2A`) or escape it (`\*`)

Hi , Thanks for your response . I just catch it url from another website. Bellow is e complete url I got .

`https://dcunilive208-lh.akamaihd.net/i/dclive_1@112780/master.m3u8?hdnea=st=1595542867~exp=1595543267~acl=/i/dclive_1@112780*~hmac=5a254dc68c0e08e37a577de62969f24918c0583a1dc2651aa159456f9cc31a69`

as you can see it contain '*'  and when I want to pass to exoplayer it didn't accept whole url and it just got this part 
`https://dcunilive208-lh.akamaihd.net/i/dclive_1@112780/master.m3u8?hdnea=st=1595542867~exp=1595543267~acl=/i/dclive_1@112780`

and left the rest . 
`*~hmac=5a254dc68c0e08e37a577de62969f24918c0583a1dc2651aa159456f9cc31a69`

however for playing this media I need complete url without loss any letter or character etc.and also I tried to encode it but after encode url '*' was without any change and another part of url was changed .

**Comment by krocard** [comment]
> when I want to pass to exoplayer it didn't accept whole url and it just got this part
`https://dcunilive208-lh.akamaihd.net/i/dclive_1@112780/master.m3u8?hdnea=st=1595542867~exp=1595543267~acl=/i/dclive_1@112780`

How do did you observe that the url is truncated? I just put a breakpoint in Cronet and the `dataSpec.uri` is correct:
```
https://dcunilive208-lh.akamaihd.net/i/dclive_1@112780/master.m3u8?hdnea=st=1595542867~exp=1595543267~acl=/i/dclive_1@112780*~hmac=5a254dc68c0e08e37a577de62969f24918c0583a1dc2651aa159456f9cc31a69
```

So I don't think the url is truncated in any way. You can also see it in ExoPlayer's log:
```
2020-07-24 13:54:25.298 14198-14198/com.google.android.exoplayer2.demo D/EventLogger: mediaItem [eventTime=0.05, mediaPos=0.00, window=0, mediaId=https://dcunilive208-lh.akamaihd.net/i/dclive_1@112780/master.m3u8?hdnea=st=1595542867~exp=1595543267~acl=/i/dclive_1@112780*~hmac=5a254dc68c0e08e37a577de62969f24918c0583a1dc2651aa159456f9cc31a69, reason=PLAYLIST_CHANGED]
```

**Comment by krocard** [comment]
Your URL always return a 404 for me, in ExoPlayer, curl and my browser. Is the URL geoblocked by any chance or invalid?

If this is not the issue, could you post the logcat of the error?

**Comment by newtestpage** [comment]
it is return 404 because I think link is expired . I try to get direct link from follow url . 
`http://iframe.dacast.com/b/127281/c/545749`

I tried to get complete link from above url and pass it to exoplayer . but I got source error . I thought maybe * is the cause of it .

**Comment by krocard** [comment]
We will not help extracting video URLs from websites.

This issue aims to answer ExoPlayer questions. Please post a valid URL or/and a log of the issue using for example `adb logcat` or better a full bug report for example `adb bugreport` taken just after the failed playback.
