### ISSUE TITLE
How mediaStartTimeMs could be aligned with current timeline?

### ISSUE THREAD

**Issue by swamp-agr** [google/ExoPlayer#7658]
### Searched documentation and issues

The most related question here was #5851.

### Question

- I am working with HLS Live stream. 
- I need current position that could be obtained from `#EXT-X-PROGRAM-DATE-TIME` tags from HLS Media Playlist to know what time is it now according to live stream, with some accuracy (e.g. `300ms`).
- For this particular reason I looked up for currently downloading chunk (i.e. `MediaSourceEventListener.onLoadStarted`).
- Currently downloading chunk compared with HLS manifest.
- Segment located in HLS manifest and date time extracted from corresponding tag.
- Then, interval between `mediaLoadData?.mediaStartTimeMs` and `mediaLoadData?.mediaEndTimeMs` split with specified step (e.g. `300ms`). 
- And after that I am planning my events via for loop. The code inside the loop is similar to snippet provided in #5851:

   ```kotlin
                    player
                            ?.createMessage { _, _ ->
                                streamTime.time = streamTime.time + timeShift /* 300ms */
                                Log.d(TAG, "Time according to live stream: ${streamTime}")
                                doSomething()
                            }
                            ?.setPosition(mediaLoadData?.mediaStartTimeMs +  timeShift /* 300ms */)
                            ?.setHandler(handler)
                            ?.send()
   ```

This approach is working about `30s`. After that I am starting to notice an increasing delay between current device time and currently achieved live stream time. 

The questions:

- Is it correct way to retrieve live stream date time or I could use some better approaches?
- What could cause these increasing delays? 
- Could `mediaStartTimeMs` be invalidated by ExoPlayer? And if so, how I could work around it?

**Comment by swamp-agr** [comment]
**Update No. 1**

I am dealing with HLS Live stream with limited availability:
```
current window: dynamic=true, live=true, index=0
timeline | windows: 1 | | 0 (15000|30000) |
timeline | periods: 1 | | 0 (-25000|-9223372036854775807) |
```

Here:
- Window: `15000` - is `defaultPositionMs`, `30000` - is `durationMs`.
- Period: `-25000` - is `positionInWindowMs`, `C.TIME_UNSET` - durationMs.

<img width="1292" alt="Screenshot 2020-07-22 at 19 20 07" src="https://user-images.githubusercontent.com/6595049/88210115-55659680-cc5c-11ea-8a50-e16a532d786b.png"> 

I also see that `Period.positionInWindowMs` absolute value is increasing within playback (i.e. `-30000`, `-35000`) every 5-10 seconds.

In this particular case I am still have no understanding about how `Timeline`'s changes affect constantly changing playback position or how to identify currently playing chunk (and associated live stream date time) from `PlayerEventListener.onTimelineChanged`.

**Comment by AquilesCanta** [comment]
If I understand correctly, what you want to do is get the playback position in the timebase of the `#EXT-X-PROGRAM-DATE-TIME` tags. If that's correct, what you want is:

`player.getCurrentPosition() + currentWindow.windowStartTimeMs // The currentWindow can be obtained from the current timeline.`

If not what you want, can you clarify?

**Comment by swamp-agr** [comment]
Hi @AquilesCanta,

This is exactly what I wanted to find.
In this case I do not know what chunk is currently playing in the moment. In order to catch some information from tags. However, I could perform `HlsManifest` tags analysis and match them with `currentTimeline`/`currentWindow`.

I appreciate your support!
Closing issue for now.

Thank you and have a good day!
