### ISSUE TITLE
Demo HLS streams not working on Sony TVs

### ISSUE THREAD

**Issue by cachapa** [google/ExoPlayer#766]
I've tested the ExoPlayer Demo app in a modern Sony TV with integrated Android TV.
None of the video streams under the "HLS" category play - instead, the state remains at "buffering" and nothing else seems to happen.
All of the other streams work fine. I have also been able to play HLS streams from other sources.

In my testing I have been able to confirm that:
- The demo app runs as expected on Android mobile devices (tested on Nexus S and Nexus 6)
- Playing the problematic streams in a standard VideoView works on the Sony TV.
- The Demo app also works as intended on the Android TV emulator from the SDK.

I've attached an excerpt of the log here: http://www.wepaste.com/exoplayer/
Please let me know if you need more information from my side.

**Comment by ojw28** [comment]
[Following up through other channels. Thanks.]
