### ISSUE TITLE
Buffering State triggers at the end of playback for short period of time ~10ms

### ISSUE THREAD

**Issue by Pavel87** [google/ExoPlayer#7664]
When playing ABR VOD using DASH **ExoPlayer.STATE_BUFFERING** triggers at the end of the video playback for very short period of time (peak at ~10ms). We record duration by doing diff from ExoPlayer.STATE_READY -  ExoPlayer.STATE_BUFFERING. The strange part is that if video segments total duration is i.e. 32440ms this buffering triggers at the same time or even past this time based on the playback position we have recorded as well. I am attaching a distribution of durations and playback positions to illustrate the problem.

Are there any reasons why would player transition to ExoPlayer.STATE_BUFFERING at the end of the video when all segments should be already downloaded?

<img width="1388" alt="Screen Shot 2020-07-23 at 11 59 08 AM" src="https://user-images.githubusercontent.com/5558923/88327840-5d651b00-ccdc-11ea-91de-1b514317158a.png">

**Comment by Pavel87** [comment]
When digging into this more the duration of video returned by player.getDuration() is 33003ms (DASH Manifest value) is not equal to actual length of the segments downloaded. The real length appears to be **32440**ms based on summation of all video segments downloaded length. Could this discrepancy trigger the short buffering I was observing. I am unable to reproduce it on any device I have the data I have shown above are from production.

**Comment by ojw28** [comment]
> Are there any reasons why would player transition to ExoPlayer.STATE_BUFFERING at the end of the video when all segments should be already downloaded?

It wouldn't be expected, no. Are you able to slice your production data by device model, to see if only certain devices are affected? If it only happens on certain devices, that would also explain why you're unable to reproduce (assuming you don't have one of the affected devices for local testing) and might also help us to reproduce and figure out what's happening.

**Comment by Pavel87** [comment]
From device distribution the most affected are older versions of android and also appears like no top tier devices are in the list, but still good variety of manufacturers/models experiencing this issue.

<img width="1434" alt="Screen Shot 2020-07-24 at 8 47 24 AM" src="https://user-images.githubusercontent.com/5558923/88410006-98258c80-cd8a-11ea-961f-520f9e16ee9a.png">

**Comment by ojw28** [comment]
I don't think we were ever able to root cause this. We've also not seen any reports from other app developers, which somewhat suggests it might be a content or app specific problem.

@Pavel87 - Could you confirm whether this is still an active problem for you?
