### ISSUE TITLE
Gap between video in ConcatenatingMediaSource

### ISSUE THREAD

**Issue by dmkenza** [google/ExoPlayer#7665]
### Issue description
I play video sequence by using ConcatenatingMediaSource. 

https://drive.google.com/file/d/1kYXtP0wG7_gYqu_ALnVqF-wkEqlgL4qN/view?usp=sharing

First video has size  640*640 and load quick.

I see gap in second video. It seem what load video begin when previous got end. This video has sizes 4000*3000 and this source does not have time to load.  How to fix this problem?

I want to preload next video then play the current.

### Version of ExoPlayer being used
2.11.7

Xiaomi Mi 9 Android 10

**Comment by krocard** [comment]
In order for us to reproduce and understand the issue, could you please provide a 
 - a link to the 2 videos that reproduces the issue
 - a full bug report using "adb bugreport". Output from "adb logcat" or a log snippet is NOT sufficient. Please attach the captured bug report as a file.

If you don't wish to post those publicly, please email the link to dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Provide all the metadata we'd need to play the content like drm license urls or similar. If the content is accessible only in certain countries or regions, please say so.

**Comment by dmkenza** [comment]
@krocard 
https://drive.google.com/file/d/11xwvFU26d8CT2g1Ao31kfeYQAmx9lfpF/view?usp=sharing

**Comment by krocard** [comment]
Sorry for not addressing your issues earlier. I could not reproduce your issue. Do you still observe it on your device with the last Exoplayer version? We made significant improvements on playlist loading.
