### ISSUE TITLE
hls stream has no sound with exoplayer how ever it has on another player 

### ISSUE THREAD

**Issue by newtestpage** [google/ExoPlayer#7670]
Hi 
I am trying to play hls stream with exoplayer . video playing good but I have problem with audio . it doesn't have any audio . 
hls link :
```
https://glwizhhls22.glwiz.com/ManotoPlus1.m3u8?
```

is there any solution ?
my media source method :

``` 
DataSource.Factory dataSourceFactory =
               new DefaultDataSourceFactory(this, Util.getUserAgent(this,this.getString(R.string.app_name)));

        //DefaultHlsExtractorFactory defaultHlsExtractorFactory =
             // new DefaultHlsExtractorFactory(FLAG_ALLOW_NON_IDR_KEYFRAMES,false);

        HlsMediaSource.Factory mediaSourceFactory = new HlsMediaSource.Factory(dataSourceFactory);
        return mediaSourceFactory.createMediaSource(uri);
```

**Comment by ojw28** [comment]
The stream plays fine with audio for me. Please properly fill in the issue template, [available here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md), if you require further help.

**Comment by newtestpage** [comment]
> The stream plays fine with audio for me. Please properly fill in the issue template, [available here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md), if you require further help.

Hi
thanks for your response . it was wrong url . I edited url and entered correct url . It doesn't have audio with exoplayer.

**Comment by ojw28** [comment]
I suspect this is a case of bad media, but over to @AquilesCanta to take a look.

**Comment by AquilesCanta** [comment]
I agree with @ojw28. The master playlist explicitly puts no audio codecs in the first variant, even though it does contain audio. From the [HLS specification (section 4.3.4.1.1)](https://tools.ietf.org/html/rfc8216#section-4.3.4.1.1):

```
   any EXT-X-STREAM-INF tag (Section 4.3.4.2) or EXT-X-I-FRAME-STREAM-
   INF tag (Section 4.3.4.3) that references such a Group MUST have a
   CODECS attribute that lists every sample format present in any
   Rendition in the Group, or client playback failures can occur.
```

In order to easily fix this, just include the codec string for the audio track in all variants that contain audio.

**Comment by newtestpage** [comment]
> I agree with @ojw28. The master playlist explicitly puts no audio codecs in the first variant, even though it does contain audio. From the [HLS specification (section 4.3.4.1.1)](https://tools.ietf.org/html/rfc8216#section-4.3.4.1.1):
> 
> ```
>    any EXT-X-STREAM-INF tag (Section 4.3.4.2) or EXT-X-I-FRAME-STREAM-
>    INF tag (Section 4.3.4.3) that references such a Group MUST have a
>    CODECS attribute that lists every sample format present in any
>    Rendition in the Group, or client playback failures can occur.
> ```
> 
> In order to easily fix this, just include the codec string for the audio track in all variants that contain audio.

thanks for your response . Could give me more detail how I could do this ?

**Comment by AquilesCanta** [comment]
Add the audio codecs string in your

`#EXT-X-STREAM-INF:BANDWIDTH=512000,RESOLUTION=480x360,CODECS="avc1.640015"`

The other variant in the manifest is:

`#EXT-X-STREAM-INF:BANDWIDTH=128000,RESOLUTION=240x180,CODECS="avc1.64000c,mp4a.40.2"`

As you can observe, it does contain the audio codec. You need to include the audio codec in both tags. Just make sure you are providing the right codec string in both. It's possible that it's the same codec, but I haven't checked.
