### ISSUE TITLE
dev-v2 latest: Playback can get stuck buffering after seeking

### ISSUE THREAD

**Issue by fgl27** [google/ExoPlayer#7672]
### [REQUIRED] Issue description
Last changes on dev-v2 branch from Jul 24, 2020 is causing problem on three situations.

**1. starting a hls VOD passing a starting `position > 0`**

The playback will not start as expect, it will stall, and after a few seconds will start from the `position > 0`. This is not a expected buffer stall, is something unusual way longer then the normal starting buffer.

I notice that when the stall happen the buffer size `player.getTotalBufferedDuration()` incrises more and more, after 5 to 10 seconds it goes back to 0 and the playback starts from the passed position.

It seems that the playback is starting from the position 0, but as the starting position is `> 0` it will not play, but it will buffer starting from 0 then drops the buffer and only after that start from `position > 0`.

**2. seekTo() backwards on a hls VOD**

It just stall, the buffer incrises until the limit reaches and the player stay stalled on `STATE_BUFFERING`.

**3. This is personal, just a change I do that may help understand were the issue is**

On Live hls playback I change this line 

https://github.com/google/ExoPlayer/blob/6fb28a8dc91ee0d0542e7b9e6647656c64c35e37/library/hls/src/main/java/com/google/android/exoplayer2/source/hls/HlsMediaSource.java#L523

To be time base like this:

`          windowDefaultStartPositionUs = playlist.durationUs - 2000000;
`

Starting the playback close to the live window as possible when the user choose to.

But that is causing the same stall as seeking backwards

Now I have change this to 

`          windowDefaultStartPositionUs = segments.get(segments.size() - 1).relativeStartTimeUs;
`

There is others checks to prevent issues, that is just a sample how it can end up working...

This third issue is not something that I expect to be fixed, is just a information that show a problem, I already added my "fix".

So before was possible to start a playback passing any time inside the duration to start the playback, now is necessary a precise time position of a segment, at least for lives.

So this may help find the cause of issue 1 and 2.

### [REQUIRED] Reproduction steps
Already explain on description.

### [REQUIRED] Link to test content
I assume any hls vod will cause this

### [REQUIRED] A full bug report captured from the device
Not a crash so I assume one can reproduce it very easy and get the logs if necessary

### [REQUIRED] Version of ExoPlayer being used
dev-v2

### [REQUIRED] Device(s) and version(s) of Android being used
Not a specific device or OS issue.

**Comment by ojw28** [comment]
I tried both (1) and (2) in the ExoPlayer demo app at 6fb28a8dc91ee0d0542e7b9e6647656c64c35e37, and I couldn't reproduce either.

Would it be possible for you to provide more specific, concrete reproduction steps in the demo app, since I think some of your assumptions ("I assume any hls vod will cause this" and "I assume one can reproduce it very easy") are probably not valid.

**Comment by fgl27** [comment]
This is a odd one to reproduce, I can't cause (1) on the demo app, the demo app code is not what I use (regarding starting the playback when `ResumePosition > 0`), but I can cause (2)

**How to reproduce (2) on demo app:**

Play this:

https://github.com/google/ExoPlayer/blob/6fb28a8dc91ee0d0542e7b9e6647656c64c35e37/demos/main/src/main/assets/media.exolist.json#L272-L275

Go to 5 minutes or so (seek forward), exit the app (press home key don't close it) then go back to the app after it start playing from 5 min, seek to backwards, app doesn't plays.

on the logs I see this 

```
07-27 14:24:25.860 29125 29125 D EventLogger: seekStarted [eventTime=5.09, mediaPos=276.44, window=0, period=0]
07-27 14:24:25.861 29125 29125 D EventLogger: positionDiscontinuity [eventTime=5.09, mediaPos=185.64, window=0, period=0, SEEK]
07-27 14:24:25.866 29125 29125 D EventLogger: state [eventTime=5.09, mediaPos=185.64, window=0, period=0, BUFFERING]
07-27 14:24:25.872 29125 29125 D EventLogger: isPlaying [eventTime=5.10, mediaPos=185.64, window=0, period=0, false]
07-27 14:24:31.353 29125 29125 D EventLogger: loading [eventTime=10.58, mediaPos=185.64, window=0, period=0, false]
```

no crash just normal logs, [full_log.txt](https://github.com/google/ExoPlayer/files/4983519/full_log.txt)

On the seek bar I can see the buffer filling up then it stops buffering but noting plays unless I seek forward again, then If I seek backwards the problem happens again all the time, so this playback after resume cause the issue.

**Regarding (1)**

I start the playback very different then what demo app does.

I use

```java
        player.setPlayWhenReady(true);
        player.setMediaSource(
                mediaSource,
                (ResumePosition > 0) ? ResumePosition : C.TIME_UNSET
        );

        player.prepare();
```

And the `mediaSource` is a hls master playlist.

On my app that causes the problem, maybe is not noticeable on the demo because the way it starts when `ResumePosition > 0`.

https://github.com/google/ExoPlayer/blob/6fb28a8dc91ee0d0542e7b9e6647656c64c35e37/demos/main/src/main/java/com/google/android/exoplayer2/demo/PlayerActivity.java#L305-L310

Also on my app the buffer size is different, it's base on the device RAM size, on a 3GB device the buffer goes up to 200+ seconds on most content, and that maybe be the issue, the buffer is allow to be bigger and I start it different so I see the issue.

As (1) eventually plays, the only problem is that it only plays after doing some very long buffering and releasing the buffer before start playing, as I allow a very bigger buffer I notice it.

**Comment by ojw28** [comment]
Thanks for the additional details. It looks like bf5e6c7862ae418895b2b6b26fae9c28aa662ee8 is the culprit

**Comment by fgl27** [comment]
Yes reverting that fixes all issues.

**Comment by ojw28** [comment]
The change has been reverted in 1ed5d8b5633f935d3c7f2cc52c1493616b7e0d32. Thanks for reporting this issue!
