### ISSUE TITLE
Set lowest quality(Track selection) as default for both video and the TrackSelectionBuilder 

### ISSUE THREAD

**Issue by krys007** [google/ExoPlayer#7673]
Hello Team .. i am using exoplayer:2.11.6 version in my app 
i have setForceLowestBitrate(true) in onCreate so that video will play in lowest quality available.

```
 trackSelectorParameters = new DefaultTrackSelector.ParametersBuilder()
                    .setForceLowestBitrate(true)
                    .build();
```

and i am opening TrackSelector using this code

```
@Override
    public void onClick(View view) {
            MappingTrackSelector.MappedTrackInfo mappedTrackInfo = trackSelector.getCurrentMappedTrackInfo();
            if (mappedTrackInfo != null) {
                CharSequence title = "Available quality";
                int rendererIndex = 2;
                int rendererType = mappedTrackInfo.getRendererType(rendererIndex);
                boolean allowAdaptiveSelections = rendererType == C.TRACK_TYPE_VIDEO || (rendererType == C.TRACK_TYPE_AUDIO && mappedTrackInfo.getTypeSupport(C.TRACK_TYPE_VIDEO) == MappingTrackSelector.MappedTrackInfo.RENDERER_SUPPORT_NO_TRACKS);
                TrackSelectionDialogBuilder build = new TrackSelectionDialogBuilder(VideoViewActivity.this, title, trackSelector, 0);
                build.setAllowAdaptiveSelections(allowAdaptiveSelections);
                build.setTrackNameProvider(format -> (format.height) + "p");
                build.setShowDisableOption(false);
                build.build().show();
            }
        }
```

but in the dialog its now showing lowest quality selected by default
instead of that it shows 
Auto as selected by deafult 
see image here: https://freeimage.host/i/dTEmKP
i want it to show the lowest quality selected or current running quality (144p as its lowest quality available)

but its been a week i still get no idea how it could be done..

please tell me if there is a way to do so ..

**Comment by tonihei** [comment]
The `TrackSelectionDialog` shows `Auto` because the selection is "automatic" based on the specified preferences. Our default `TrackSelectionDialog` doesn't support showing the currently auto-selected track, but you could fork the class to add this option yourself. To get the currently selected track, you can use `SimpleExoPlayer.getVideoFormat()`.

**Comment by tonihei** [comment]
Closing, because we won't add this to our `TrackSelectionDialog`.
