### ISSUE TITLE
How to get current audio frame?

### ISSUE THREAD

**Issue by matanmarciano** [google/ExoPlayer#7674]
Hi Exoplayer's :)
How can I get (in real-time) the current audio frame (byte[]?) that about to be rendered ???

**Comment by tonihei** [comment]
Depending on what you'd like to achieve, you could try to add a custom `AudioProcessor` (for example by overriding `DefaultRenderersFactory. buildAudioProcessors`). In there you get access to the raw PCM data just before it is sent to the platform `AudioTrack`.

**Comment by andrewlewis** [comment]
If synchronization with what's actually being played out is important, #4107 may also help with this.

**Comment by tonihei** [comment]
Closing under the assumption that the question was answered.
