### ISSUE TITLE
HLS: Are there "legitimate" cases where chunkless preparation fails but the stream works fine without?

### ISSUE THREAD

**Issue by DavidMihola** [google/ExoPlayer#7678]
### Searched documentation and issues
* Code documentation of `HlsMediaSource`
* Blog post about chunkless preparation: https://medium.com/google-exoplayer/faster-hls-preparation-f6611aa15ea6
* Searched the issues here on Github for `chunkless`

### Question
Are there cases where an HLS manifest is complete and correct (with regards to the actual segment files) but chunkless preparation in ExoPlayer still fails? Conversely, if I _switch_ to `setAllowChunklessPreparation(true)` and there are _new_ playback problems is there always something wrong with either the manifest of the segment files (or at least a mismatch between the two)? Or are there "legitimate" cases where chunkless preparation fails but "normal" preparation works fine?

The current context is a stream where audio is played fine with "normal" preparation but the stream is played silently with chunkless preparation. (Also, from the logs I can see that no Decoder of type `C.TRACK_TYPE_AUDIO` is even enabled in this case). (Interestingly, this only happens when the app requests a manifest which contains only the highest of several available qualities. If the app requests the "full" manifest it can then later switch up to the highest quality and still continue playing the audio.)

### A full bug report captured from the device
If you think it makes sense in this case I will provide a bug report log.

### Link to test content
Currently, the relevant stream configuration is only available on the internal test network and under a dynamic URL. We are working on getting a test stream under a public and fixed URL.

**Comment by AquilesCanta** [comment]
I think the best step forward is that we wait until we get a sample stream to reproduce ourselves. I don't think chunkless preparation would cause audio tracks not to be detected, in general. And there is not really much gain in speculating about possible causes. Please post below once you have a stream you can share with us. Thanks for reporting!

**Comment by DavidMihola** [comment]
Thanks for the quick reply!

OK, I will get back to you as soon as we have a test stream!

**Comment by DavidMihola** [comment]
Sorry, that took a while... But we do have public test streams now!

For convenience, I forked the ExoPlayer project and added a branch with a few changes to the `demo` app:
* it includes only our HLS test streams
* it enables chunkless preparation for HLS streams

https://github.com/google/ExoPlayer/compare/release-v2...DavidMihola:demonstrate-HLS-chunkless-preparation-problems

As I wrote in the stream names in `media.exolist.json` the audio in the first stream works with and without chunkless preparation. For the second stream, though, the audio is fine with "normal" preparation but with chunkless preparation no audio track is recognized and the stream is played silently.

**Comment by AquilesCanta** [comment]
A fix for this will be available in the next release.

Edit: The issue here is that the variants were removed but the media tags corresponding to those variants were left. The playlist parser fails to map the media tags to a variant, therefor missing the codecs attribute from the variant, which in turn means the media period fails to assign a sample mime type to the audio track. In conclusion, the audio track is exposed without a mime type, making it unmappable by the track selector.
