### ISSUE TITLE
How to show thumbnail in ExoPlayer?

### ISSUE THREAD

**Issue by halilozel1903** [google/ExoPlayer#7684]
Hi,

I want to show thumbnail in ExoPlayer.

I didn't found thumbnail document & example.

How can I show thumbnail in ExoPlayer? 

I'm waiting  for your support

**Comment by tonihei** [comment]
ExoPlayer automatically displays the artwork embedded in the media if the `use_artwork` attribute on `PlayerView` is set to true. You can also specify your own default artwork that is used if the media doesn't provide one by setting the `default_artwork` attribute. Is that what you are looking for?

**Comment by halilozel1903** [comment]
No, It doesn't work. I get a json type url from the service. I couldn't find a similar example how to add it.

**Comment by tonihei** [comment]
You can also set the default artwork with a call to `PlayerView.setDefaultArtwork(Drawable)` if you receive it programmatically.

**Comment by tonihei** [comment]
Closing under the assumption that the question was answered.
