### ISSUE TITLE
How to make DefaultHttpDataSource trust a CA that isn't supported by the system ?

### ISSUE THREAD

**Issue by ghost** [google/ExoPlayer#7688]
We're having a problem where we're loading a video through an HTTPS connection. We're getting `CertPathValidatorException: Trust anchor for certification path not found` error because the CA used by the server isn't recognized by the Android version (21, 22) since it's old. The same video url works fine on newer devices. For an extra check, I disabled the CA used by the server on the newer device and the video stopped working.

So I'm trying to figure out a way to make the CA trusted. I thought of extending `DefaultHttpDataSource` and overriding either `makeConnection` or `openConnection`, but those two methods are private. So I thought of just copy pasting the source code but that's not a maintainable approach for when new updates roll in.

Is there an easier way I'm not thinking of ? Or if not, could you guys consider developing an API for this use case ?
What do you recommend ?

Thanks.

**Comment by ghost** [comment]
I ended up going with this solution that adds the CA as a trusted source globally not just for Exoplayer. This seems to work. I'm calling it in `onCreate` of the application class.

            // Load CAs from file
            val cf: CertificateFactory = CertificateFactory.getInstance("X.509")
            val caInput: InputStream = BufferedInputStream(assets.open("certificate.crt"))
            val ca: X509Certificate = caInput.use {
                cf.generateCertificate(it) as X509Certificate
            }

            // Create a KeyStore containing our trusted CAs
            val keyStoreType = KeyStore.getDefaultType()
            val keyStore = KeyStore.getInstance(keyStoreType).apply {
                load(null, null)
                setCertificateEntry("ca", ca)
            }

            // Create a TrustManager that trusts the CAs inputStream our KeyStore
            val tmfAlgorithm: String = TrustManagerFactory.getDefaultAlgorithm()
            val tmf: TrustManagerFactory = TrustManagerFactory.getInstance(tmfAlgorithm).apply {
                init(keyStore)
            }

            // Create an SSLContext that uses our TrustManager
            SSLContext.getInstance("TLS").apply {
                init(null, tmf.trustManagers, null)
                HttpsURLConnection.setDefaultSSLSocketFactory(socketFactory)
            }

**Comment by tonihei** [comment]
This is not really an ExoPlayer issue I think because these things are handled by the platform. It looks like you found a way to add the missing servers? I'll close the issue under the assumption that it is solved.
