### ISSUE TITLE
.NoClassDefFoundError

### ISSUE THREAD

**Issue by Shingibanggi** [google/ExoPlayer#7692]
Hello, I am developing Exoplayer plugin for Unity to play HLS video,
but I have a problem with playing video..

In the logs, I got this problem..
AndroidJavaException: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/exoplayer2/source/MediaSource;
07-29 17:46:49.174 20874 20910 E Unity   : java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/exoplayer2/source/MediaSource;
07-29 17:46:49.174 20874 20910 E Unity   : 	at java.lang.reflect.Executable.getMethodReturnTypeInternal(Native Method)
07-29 17:46:49.174 20874 20910 E Unity   : 	at java.lang.reflect.Method.getReturnType(Method.java:148)
07-29 17:46:49.174 20874 20910 E Unity   : 	at java.lang.Class.getDeclaredMethods(Class.java:1883)
07-29 17:46:49.174 20874 20910 E Unity   : 	at com.unity3d.player.ReflectionHelper.getMethodID(Unknown Source:89)
07-29 17:46:49.174 20874 20910 E Unity   : 	at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
07-29 17:46:49.174 20874 20910 E Unity   : 	at com.unity3d.player.UnityPlayer.access$300(Unknown Source:0)
07-29 17:46:49.174 20874 20910 E Unity   : 	at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:95)
07-29 17:46:49.174 20874 20910 E Unity   : 	at android.os.Handler.dispatchMessage(Handler.java:103)
07-29 17:46:49.174 20874 20910 E Unity   : 	at android.os.Looper.loop(Looper.java:214)
07-29 17:46:49.174 20874 20910 E Unity   : 	at com.unity3d.player.UnityPlayer$e.run(Unknown Source:20)
07-29 17:46:49.174 20874 20910 E Unity   : Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.exoplayer2.source.MediaSource" on path: DexPathList[[zip file "/data/app/com.Jihyun.P

What should do I do to fix this?!?!
Please help me.
Additionally, If there is an Exoplayer plugin for unity, I really want to get it.
I've searched for a few days, but i couldn't found.

**Comment by Shingibanggi** [comment]
I am a newbie in Android Studio and Unity.

**Comment by tonihei** [comment]
If you load classes via reflection, they need to be added to the proguard config list so that they are not optimized away. This is not ExoPlayer specific and needs to be solved in your app or whatever library you are using. See https://developer.android.com/studio/build/shrink-code#keep-code for some high-level guidance.
