### ISSUE TITLE
Future support for DASH with AES-128

### ISSUE THREAD

**Issue by aKnaupp** [google/ExoPlayer#7694]
Hi, I know that, at this time, ExoPlayer does not support DASH with AES-128. Is there any plan for adding support to this?
Thanks.

**Comment by tonihei** [comment]
Could you clarify what you mean by "DASH with AES-128" exactly? If the data transferred over network is encrypted by AES-128, you should be able to use a `Aes128DataSource` to decrypt it before playback. If you are talking about something else, please clarify.
