### ISSUE TITLE
Why does Exoplayer try to play the wrong bitrate when downloaded?

### ISSUE THREAD

**Issue by BarryFruitman** [google/ExoPlayer#7697]
### [REQUIRED] Searched documentation and issues
Google + Exoplayer docs + Exoplayer source code.

### [REQUIRED] Question
I'm having trouble playing downloaded content. My HLS stream has three bitrates (64k, 128k, 192k). When I call `DownloadService.addToDownload()`, I can see it downloading the 192k track by setting breakpoints in `DefaultHttpDataSource.open()`. However, when I put my device into airplane mode and pass `Exoplayer.prepare()` the _exact same master playlist URI_ that I passed to `DownloadServer`, it reports that it can't find the 64k track. Specifically, it can't find the 64k playlist URI, which it must have pulled from the master playlist.

Why would Exoplayer try to play the 64k track when only the 192k track is downloaded? My device is in airplane mode.

Note: I'm able to stream the exact same master playlist. Only downloaded content isn't working.

### A full bug report captured from the device
Emailed to dev.exoplayer@gmail.com

### Link to test content
Unfortunately my test content is restricted.

**Comment by tonihei** [comment]
I'm not sure what class `DownloadServer` is because it's not part of ExoPlayer, but in case you are using `DownloadHelper`, ExoPlayer will select the highest supported quality for download by default (192k in your example).

If you want to play the downloaded data afterwards, you need to make sure to tell the `MediaSource` which tracks are already downloaded. You can do that by using `DownloadHelper.createMediaSource`. See also our documentation at https://exoplayer.dev/downloading-media.html#downloading-and-playing-adaptive-streams.

**Comment by BarryFruitman** [comment]
My bad, I meant `DownloadService` not `DownloadServer` (ticket updated).

Thank you for pointing that out in the docs. I'll check it out.

**Comment by kschults** [comment]
@tonihei Thanks for the pointer. Is this something that should be an improvement within ExoPlayer? It seems that if I request to play the same URI again, after already having downloaded it, the playback system should be able to check the downloads and determine that there's already one there.

**Comment by tonihei** [comment]
We have an open enhancement to automatically take downloaded tracks into account during track selection (#6471). I think this is essentially what you are asking for. Once we've done that, the current approach of setting up the `MediaSource` in a special way is likely no longer needed.

**Comment by kschults** [comment]
@tonihei Thanks, that's exactly what I'm looking for. I think between the comment about using the `DownloadRequest` and #6471, it's probably safe to close this ticket. Thanks for your help

**Comment by tonihei** [comment]
You're welcome :)
