### ISSUE TITLE
How can I use the ExpandedControllerActivity correctly with exoplayer? 

### ISSUE THREAD

**Issue by chinmaygghag** [google/ExoPlayer#7699]
[No info provided]

**Comment by tonihei** [comment]
It looks as if `ExpandedControllerActivity` is part of the Cast API and has nothing to do with ExoPlayer. If you want to use ExoPlayer and enable casting, please have a look at our [cast extension](https://medium.com/google-exoplayer/new-cast-extension-and-demo-app-55816a50012).

**Comment by chinmaygghag** [comment]
@tonihei Thanks for pointing me in this direction, I am trying the cast extension demo from the release-v2 branch. 
I am not sure if it is designed to work this way or am I missing something. But this is my observation. 
When I hit cast button the cast on chromecast starts but as soon as I press back button or minimize the android app the casting stops (Also no access from the notification panel)
Can you provide some insights on this?

**Comment by tonihei** [comment]
Assigning to @AquilesCanta to have a look and comment on this.

**Comment by AquilesCanta** [comment]
You should track #7296, if that's what you are trying to do. If not, please clarify and I'll reopen.
