### ISSUE TITLE
How to delay/increment the timing of the subtitles?

### ISSUE THREAD

**Issue by manojkumarm2406** [google/ExoPlayer#7702]

**Comment by manojkumarm2406** [comment]
I am trying to delay the timing of the subtitles that I sideloaded with MergeMediaSource

`val fullMediaSource = List<MediaSource>()

val mergedMediaSource = MergingMediaSource(videoSource,subtitleSource)

fullMediaSource.add(mergedMediaSource)`

But How do I synchronize the subtitles that I merged?

**Comment by ojw28** [comment]
This is not currently supported. Note that this is a duplicate of https://github.com/google/ExoPlayer/issues/854, so I'll go ahead and close this one.
