### ISSUE TITLE
Does Exoplayer support with Flutter Android App?

### ISSUE THREAD

**Issue by kvmoondra** [google/ExoPlayer#7705]
Hello there,
Hope you are doing well.

With regards, we are developing a flutter video android app(from our app: we are going to distribute the videos to end-users, only video content).

**For the above, we are looking to integrate Exoplayer(to use ABR technology like HLS) and the technologies we are using to develop our App is:**
-App: Flutter
-Backend: NodeJS, MongoDB
-Storage: AWS S3
-Html5, CSS, Angular for Web

Does Exoplayer support with flutter & the technologies we have mentioned above so that we can stream HLS? If yes, what's the way- Do we need to integrate directly OR any plugin in between?

Help is super appreciated in advance & will wait to hear from you.

**Comment by ojw28** [comment]
Have you tried doing a [simple web search](https://www.google.com/search?q=video+playback+on+flutter)? For which [this is the top result](https://flutter.dev/docs/cookbook/plugins/play-video).

**Comment by kvmoondra** [comment]
Thanks, @ojw28 for your reply.

I have gone through and it's mentioned that: this plugin is using Exoplayer to stream videos. 

Just want to clear in my head about the process: As soon as we integrate this plugin -> then Exoplayer works -> then Exoplayer can use ABR technology(like HLS).

Kindly correct me if I am wrong

Thanks & Regards

**Comment by ojw28** [comment]
I think so, yes, but that seems like more of a question for the flutter team / whoever maintains the flutter video plugin.
