### ISSUE TITLE
Missing Cursor close in DefaultDownloadIndex.java

### ISSUE THREAD

**Issue by amankr** [google/ExoPlayer#7706]
### Issue description
missing cursor.close in a finally block causing a failure in cursor allocation on low Ram devices

```
Fatal Exception: android.database.CursorWindowAllocationException: Cursor window allocation of 2048 kb failed. # Open Cursors=43 (# cursors opened by this proc=43)
       at android.database.CursorWindow.<init>(CursorWindow.java:108)
       at android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java:198)
       at android.database.sqlite.SQLiteCursor.clearOrCreateWindow(SQLiteCursor.java:301)
       at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:139)
       at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:133)
       at com.google.android.exoplayer2.offline.DefaultDownloadIndex.getDownload(DefaultDownloadIndex.java:172)
```

above stacktrace is captured on Crashlytics, hence I am not able to provide full bug report. 

### Version of ExoPlayer being used
exoplayerVersion = '2.11.7'

### Device(s) and version(s) of Android being used
Brand: samsung
Model: Galaxy J2
RAM free: 183.88 MB
Disk free: 454.74 MB
OS Version: 5.1.1

**Comment by ojw28** [comment]
The cursor is part of a try-with-resources statement, which should ensure that it's closed automatically. See:

https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html

and the corresponding lines of code in ExoPlayer:

https://github.com/google/ExoPlayer/blob/r2.11.7/library/core/src/main/java/com/google/android/exoplayer2/offline/DefaultDownloadIndex.java#L171

The logging is saying that there are 43 open cursors, but it's unclear what they are or whether they originate from ExoPlayer. Note that I'm pretty sure this count is the number of open cursors that you have across your entire process, so they could equally well be originating from outside of ExoPlayer.

I think you'll need to figure out where those 43 open cursors are coming from. You can do this using strict mode, as per the top answers to [this StackOverflow question](https://stackoverflow.com/questions/11340257/sqlite-android-database-cursor-window-allocation-of-2048-kb-failed). If they're originating from ExoPlayer, please provide the strict mode failures that you see, which should indicate the exact point at which the problematic cursors are opened.

**Comment by amankr** [comment]
Thanks for the clarification. Closing the issue
