### ISSUE TITLE
Support custom track ordering in TrackSelectionView / TrackSelectionDialogBuilder

### ISSUE THREAD

**Issue by yoobi** [google/ExoPlayer#7709]
### [REQUIRED] Searched documentation and issues

I've looked around stackoverfow and multiple forums but they just use `TrackSelectionDialog` without sorting the format

### [REQUIRED] Question

How can I sort the format inside `TrackSelectionDialog` ? I can't modify the videos as I'm just picking up the link from a WebService. Here is a [screen](https://imgur.com/a/ETbg84d) of what I'm describing.

my `TrackSelectionDialog` displays the format in the following order: 480p, 720p, 1080p, 360p, 256p and I'd like to sort the format in the following order: 256p, 360p, 480p, 720p, 1080p.

This is my code:

```
trackSelectionDialogBuilder = TrackSelectionDialogBuilder(context, context.getString(R.string.qualitySelector), trackSelector, videoRenderer)
trackSelectionDialogBuilder.setTrackNameProvider {
    // Override function getTrackName
    context.getString(R.string.exo_track_resolution_pixel, it.height)
}
return trackSelectionDialogBuilder.build()
```

**Comment by ojw28** [comment]
There's no way to do this currently. I'll mark it as an enhancement.

In the meantime, it should be relatively easy for you to fork `TrackSelectionDialogBuilder` and `TrackSelectionView` into your own codebase, at which point you'll be able to customize them to exactly suit your use case.

**Comment by yoobi** [comment]
So you mean I should copy your `TrackSelectionDialogBuilder` and `TrackSelectionView` and change them to add this `sortBy` method ?

**Comment by ojw28** [comment]
We will use this issue to track adding support directly to the library, but in the meantime, yes, that's the easiest thing for you to do. You could also send a pull request directly to the project, if you're sufficiently motivated to do so!

**Comment by ojw28** [comment]
Pull request was merged. Thanks!
