### ISSUE TITLE
Total duration is not working exactly

### ISSUE THREAD

**Issue by AndersonCrew** [google/ExoPlayer#7710]
I had .setShowMultiWindowTimeBar(true) with my list Uri File , but the total duration is not working exactly 
https://drive.google.com/file/d/1PdEfmT9quPJVOA9mrRV7rgJ81motuynV/view?usp=sharing
Total my video list is 54s but you can see the video it is incorrect

**Comment by ojw28** [comment]
Is your issue that it's showing 55s rather than 54s? Or is your issue that it's initially showing 4s before it updates?

**Comment by AndersonCrew** [comment]
I .setShowMultiWindowTimeBar(true) , but it not load total duration in seekbar first . It show timebard of first window, then show total duration of playlist until the first windows ended

**Comment by ojw28** [comment]
This is a duplicate of https://github.com/google/ExoPlayer/issues/4727.
