### ISSUE TITLE
Play torrent files

### ISSUE THREAD

**Issue by master255** [google/ExoPlayer#7712]
I want to play 4k Blu-Ray mkv torrent files. How long would it take you to do that?

**Comment by ojw28** [comment]
I don't think it falls within the scope of ExoPlayer to implement a BitTorrent client, or to provide a direct integration with a BitTorrent client library. That said, ExoPlayer is flexible enough that it should be fairly easy for a sufficiently motivated app developer to do this themselves, without having to make any direct modifications to the ExoPlayer library. A good starting point would probably be to write a `DataSource` component that uses the BitTorrent client library underneath.

**Comment by master255** [comment]
@ojw28 Yep! I found a solution! ExoPlayer plays video from torrents! :-D https://play.google.com/store/apps/details?id=com.media.library

**Comment by master255** [comment]
@ojw28 Yep! I found a solution! ExoPlayer plays video from torrents! h|ttp|s:/|/play.|google.|com|/store|/apps|/details|?id|=com|.media|.library|
