### ISSUE TITLE
Clearkey key-rotation content's audio playback fails after 6 sec on exoplayer

### ISSUE THREAD

**Issue by mkcdot** [google/ExoPlayer#7716]
### Question
I have generated clearkey encrypted DASH content with key-rotation using shaka-packager and hosted it on a media server.
I have configured license server with all keys used for encryption.
Then I added entry for this content in exoplayer's media.exolist.json file as below:
```
{
        "name": "ClearKey_KeyRotation_sample",
        "uri": "http://<media-server-ip-address>/shaka_clearkey/h264.mpd",
        "drm_scheme": "clearkey",
        "drm_license_url": "http://<license-server-ip-address>/clearkey-server/AcquireLicense",
        "drm_multi_session": true
 }
```
If only video stream is selected for playback with no audio stream, video plays fully by acquiring all required keys from license server.
But when audio stream is selected along with/without video stream, playback fails after 6 seconds.
When audio stream is selected and played in exoplayer and playback is seeked to any particular timestamp of the content, corresponding key is acquired by exoplayer from license server correctly. But playback immediately fails.

Key rotation dash content:
[key_rotation_sample.zip](https://github.com/google/ExoPlayer/files/5027747/key_rotation_sample.zip)

Keys used for content encryption:
KID: 59766957-2e55-547e-656b-56586e2f6f68,	Key: 7959493a764556786527517849756635
KID: 7669572E-5554-7E65-6B56-586E2F6F6859,	Key: 59493a76455678652751784975663579

Additional information:
This content plays on shaka player with both audio and video without any issues.

**Comment by ojw28** [comment]
This issue occurs when there are multiple `sbgp` or `sgbp` boxes in an FMP4 container, and the one we want (`grouping_type == seig`) doesn't come first. We'll fix this. Thanks for reporting!

**Comment by mkcdot** [comment]
This issue is now resolved with latest commit [https://github.com/google/ExoPlayer/commit/6a54ddd2173d3fd6def0c7e1320a3197e5ac2f44](url) .
Audio and video both are playing without any issues with key rotation.

Thanks for your valuable and quick support. This issue can be closed now.
