### ISSUE TITLE
How to read SEI  from FLV

### ISSUE THREAD

**Issue by ren93** [google/ExoPlayer#7717]

**Comment by AquilesCanta** [comment]
Can you clarify exactly what your usecase is? If you want to read the actual SEI bytes, you can inject a custom H264 reader using a custom `HlsExtractorFactory` when creating the `HlsMediaSource`. 

In your custom HlsExtractorFactory you'll probably have something like:

```java
    return new TsExtractor(
        TsExtractor.MODE_HLS,
        timestampAdjuster,
        new CustomH264TsPayloadReaderFactory(...));
```

If you can better describe your usecase, perhaps the solution is simpler.

**Comment by ren93** [comment]
I want to read SEI information in real time while playing flv video，Can you explain how to achieve it？
Or give me a demo，thanks！

**Comment by AquilesCanta** [comment]
FLV is not supported by HLS. Can you clarify?

**Comment by ren93** [comment]
Sorry,I want to read SEI while playing a flv video,not hls video。

**Comment by AquilesCanta** [comment]
This is not supported out of the box by ExoPlayer and I don't think we can reasonably allocate time to address this use case.

I think the best advise I can give you is too fork [FlvExtractor](https://github.com/google/ExoPlayer/blob/dev-v2/library/extractor/src/main/java/com/google/android/exoplayer2/extractor/flv/FlvExtractor.java) to do the parsing manually, and then inject your FlvExtractor implementation using your own [ExtractorsFactory](https://github.com/google/ExoPlayer/blob/dev-v2/library/extractor/src/main/java/com/google/android/exoplayer2/extractor/ExtractorsFactory.java). You may want to wrap the default one.
