### ISSUE TITLE
widevine DRM session exception

### ISSUE THREAD

**Issue by ericharlow** [google/ExoPlayer#7718]
### [REQUIRED] Issue description
When I try to play widevine dash content on some devices I am observing the following failure.
com.google.android.exoplayer2.drm.DrmSession$DrmSessionException: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 500

### [REQUIRED] Reproduction steps
using the ExoPlayer demo app on the devices named below try to play a widevine DASH secure cenc content.
I observe a failure before the video starts.

### [REQUIRED] Link to test content
{
        "name": "Secure (cenc)",
        "uri": "https://storage.googleapis.com/wvmedia/cenc/h264/tears/tears.mpd",
        "drm_scheme": "widevine",
        "drm_license_url": "https://proxy.uat.widevine.com/proxy?provider=widevine_test"
      }

### [REQUIRED] A full bug report captured from the device
[Archive.zip](https://github.com/google/ExoPlayer/files/5030353/Archive.zip)

### [REQUIRED] Version of ExoPlayer being used
exoplayer 2.11.7

### [REQUIRED] Device(s) and version(s) of Android being used
Nexus 5 running android 6.0.1
LG-D851 running android 6.0

**Comment by rrfrias** [comment]
@ericharlow , can you use https://www.widevine.com/contact to contact Widevine support. Describe the problem or provide this URI and they should be able to help you. If you still have issue, please reopen.
