### ISSUE TITLE
How ABR bitrate selection is done in exoplayer

### ISSUE THREAD

**Issue by krackjack234** [google/ExoPlayer#7719]
### [REQUIRED] Searched documentation and issues
Searched documentation but could not find the issue

### [REQUIRED] Question
We wanted to check how ABR bitrate selection is done by Exoplayer.

In our use case we set player in default ABR mode and set a max bitrate
We have a manifest where we set the player in ABR mode but map the max bitrate to 6mbps
However we see that exoplayer is picking up the track which is ~3mpbs (3330800.m3u8)
But if we set the max bitrate to 9mbps we see the track of 6bmps is getting picked (7158800.m3u8)
Note we are on 30bmps wifi speed

Here are the 2 tracks we have in our manifest

```
#EXT-X-STREAM-INF:BANDWIDTH=3330800,AVERAGE-BANDWIDTH=**2890800**,CODECS="avc1.640028,mp4a.40.2",RESOLUTION=1920x1080,FRAME-RATE=25.000
/linear/hls/pb/event/xxxx/stream/b7050743-bc9d-4c7f-9208-72effe3ea586:SIN/variant/5f5eca0bfae268a6f8f5840d46404e3a/bandwidth/hdntl=exp=1596731026~acl=%2f*~id=c415e396-a636-44d1-a530-c5a99571e210~data=hdntl~hmac=4b35d28e5f389a73545c3fb67ea598c0f426f1aad38aa2cb298a4379c89e7927/**3330800.m3u8**

#EXT-X-STREAM-INF:BANDWIDTH=7158800,AVERAGE-BANDWIDTH=**6190800**,CODECS="avc1.640028,mp4a.40.2",RESOLUTION=1920x1080,FRAME-RATE=25.000
/linear/hls/pb/event/xxxx/stream/b7050743-bc9d-4c7f-9208-72effe3ea586:SIN/variant/5ef524b8df09e6774a750b59a4edf8bb/bandwidth/hdntl=exp=1596731026~acl=%2f*~id=c415e396-a636-44d1-a530-c5a99571e210~data=hdntl~hmac=4b35d28e5f389a73545c3fb67ea598c0f426f1aad38aa2cb298a4379c89e7927/**7158800.m3u8**
```

Here are the tracks reported by Exoplayer

```
08-06 11:14:58.324  3785  3785 D EventLogger:     Group:0, adaptive_supported=YES [
08-06 11:14:58.324  3785  3785 D EventLogger:       [X] Track:0, id=0, mimeType=video/avc, bitrate=180400, codecs=avc1.42c00c, res=256x144, fps=25.0, supported=YES
08-06 11:14:58.326  3785  3785 D EventLogger:       [X] Track:1, id=1, mimeType=video/avc, bitrate=333520, codecs=avc1.42c00d, res=426x220, fps=25.0, supported=YES
08-06 11:14:58.333  3785  3785 D EventLogger:       [X] Track:2, id=2, mimeType=video/avc, bitrate=537680, codecs=avc1.42c00d, res=426x220, fps=25.0, supported=YES
08-06 11:14:58.333  3785  3785 D EventLogger:       [X] Track:3, id=3, mimeType=video/avc, bitrate=810480, codecs=avc1.77.30, res=640x360, fps=25.0, supported=YES
08-06 11:14:58.333  3785  3785 D EventLogger:       [X] Track:4, id=4, mimeType=video/avc, bitrate=1729200, codecs=avc1.77.30, res=854x480, fps=25.0, supported=YES
08-06 11:14:58.333  3785  3785 D EventLogger:       [X] Track:5, id=5, mimeType=video/avc, bitrate=2112000, codecs=avc1.4d401f, res=1280x720, fps=25.0, supported=YES
08-06 11:14:58.333  3785  3785 D EventLogger:       [X] Track:6, id=6, mimeType=video/avc, bitrate=3330800, codecs=avc1.640028, res=1920x1080, fps=25.0, supported=YES
08-06 11:14:58.333  3785  3785 D EventLogger:       [X] Track:7, id=7, mimeType=video/avc, bitrate=7158800, codecs=avc1.640028, res=1920x1080, fps=25.0, supported=YES
```

In this case the bitrate of the track reported by exoplayer is 7158800 but if we see the actual TS segment we see that its bitrate is actually 6mbps.

Here is the code we are using to set max bitrate of player

```
  trackSelectorParameters = new DefaultTrackSelector.ParametersBuilder().
                        setMaxVideoSize(maxVideoWidth, maxVideoHeight)
                        .setMaxVideoBitrate(maxVideoBitrate)
                        .setForceHighestSupportedBitrate(false)
                        .build();
```

While looking at the AdaptiveTrackSelection class in exoplayer we see that there is a bandwidth factor (DEFAULT_BANDWIDTH_FRACTION) applied whose value is 0.7F.  

So our questions are:

1. Does exoplayer picks up a track based on AVERAGE-BANDWIDTH mentioned in manifest and not on bitrate?
2. If yes, does it apply the DEFAULT_BANDWIDTH_FRACTION factor on AVERAGE-BANDWIDTH of tracks available and choose the track accordingly?
3. If the above understanding is not correct, then please let us know how the bitrate selection is happening in ABR mode.
4. Is exoplayer reporting average bandwidth as bitrate as part of track information? If yes then how can we calculate the average bitrate from that value?

Thanks.

**Comment by ojw28** [comment]
> Here is the code we are using to set max bitrate of player

Note that the code snippet you've provided doesn't actually do anything. You need to pass the built parameters back to the `TrackSelector` via `trackSelector.setParameters()` for them to be applied. I will assume that you're doing that.

* When you set a maximum video bitrate with `setMaxVideoBitrate`, tracks whose bitrates are greater than the specified `maxVideoBitrate` will be deselected and not considered for playback.
* This process does not take into account `DEFAULT_BANDWIDTH_FRACTION`.
* Whether the selection uses `BANDWIDTH` or `AVERAGE-BANDWIDTH` as the track bitrate depends on which version of ExoPlayer you're using, since this logic has changed. Since 2.11.0 `BANDWIDTH` has been used.

Note that none of this is related to ABR. This is a static selection that determines which tracks are considered for playback. During playback, ABR then adapts between the tracks that can be considered.

**Comment by krackjack234** [comment]
> Note that none of this is related to ABR. This is a static selection that determines which tracks are considered for playback. During playback, ABR then adapts between the tracks that can be considered.

Hi @ojw28 our requirement is to play in ABR mode but with a max bitrate cap. So if the bitrate cap is 6mbps, we want ABR to 
happen below 6mbps, i.e. player will select tracks which are below 6mbps bitrate

We are using _setMaxVideoBitrate_ to cap the max bitrate in ABR mode.  Is this the right way to achieve this?

> Whether the selection uses BANDWIDTH or AVERAGE-BANDWIDTH as the track bitrate depends on which version of ExoPlayer you're using, since this logic has changed. Since 2.11.0 BANDWIDTH has been used.

Can we assume that for exoplayer, the BANDWIDTH value defined in manifest is used to select the bitrate, if we are using exoplayer v2.11.4?

**Comment by ojw28** [comment]
> We are using setMaxVideoBitrate to cap the max bitrate in ABR mode. Is this the right way to achieve this?

Yes, as long as you're actually passing the parameters back to the `TrackSelector` via `trackSelector.setParameters()`.

> Can we assume that for exoplayer, the BANDWIDTH value defined in manifest is used to select the bitrate, if we are using exoplayer v2.11.4?

I think this is already answered by my previous comment:

> Since 2.11.0 BANDWIDTH has been used.

**Comment by krackjack234** [comment]
@ojw28  

If exoplayer is interpreting bandwidth as bitrate, then we are seeing one problem. We found that the bandwidth mentioned in manifest is actually not matching with the bitrate of the media segments. 

So it is a problem in generating the manifest and we should continue to use bandwidth as bitrate or should we calculate actual bitrate from bandwidth?

**Comment by ojw28** [comment]
> We found that the bandwidth mentioned in manifest is actually not matching with the bitrate of the media segments.

As per the [HLS specification](https://datatracker.ietf.org/doc/rfc8216/), the `BANDWIDTH` tag specifies: "the peak segment bit rate of the Variant Stream". It's unclear how you've determined that "the bandwidth mentioned in manifest is actually not matching with the bitrate of the media segments", because you'd typically expect the bitrate of the segments to be variable, and as per the specification the `BANDWIDTH` tag is specifying the peak bitrate.

This thread seems to be veering outside the scope of what this issue tracker is for. For general questions about HLS manifests, content generation etc, please try StackOverflow.

**Comment by krackjack234** [comment]
Thanks for the clarifications.
