### ISSUE TITLE
ExoPlayer no sound - stream

### ISSUE THREAD

**Issue by rok5ek** [google/ExoPlayer#772]
If I set the player surface to null while streaming a video the surface freezes, which is fine, but after a while the audio is not being heard (cca after 1-2min).

Use Demo app -> player.setSurface(null)

Exo version: master branch 1.4.2  (Merge branch 'dev-1.4.2-rc')

**Comment by ojw28** [comment]
What media are you playing?

**Comment by rok5ek** [comment]
I am playing a normal HLS stream, m3u8 file with HlsRenderedBuilder. I used the demo app which has beep bop sample in it, that is this url -> https://devimages.apple.com.edgekey.net/streaming/examples/bipbop_4x3/bipbop_4x3_variant.m3u8

**Comment by rok5ek** [comment]
Any updates on this?

**Comment by ojw28** [comment]
I cannot reproduce the issue. What device are you playing the content on? Can you provide more information?

**Comment by rok5ek** [comment]
I am playing it on Nexus5 4.4, but the same happens on 5.0. What i do is the following...I cloned the ExoPlayer project and in the demo package there is a PlayerActivity class, there I added the following:

`// OPTIONS MENU
    public boolean onCreateOptionsMenu(Menu menu)
    {
        Log.d(TAG, "[EXO] onCreateOptionsMenu");

        menu.add(Menu.NONE, 1234, Menu.NONE, "Surface NULL");

        return super.onCreateOptionsMenu(menu);
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item)
    {
        Log.d(TAG, "[EXO] onOptionsItemSelected");
        if (item.getItemId() == 1234)
        {
            player.setSurface(null);
            return true;
        }
        else
        {
            return super.onOptionsItemSelected(item);
        }
    }`

When I press this button in the options menu, the audio stops after 1-2mins, because I set the surface to null. Is this what it is supposed to happen?
I am playing a normal HLS stream from the Apple bipbop sample provided in the ExoPlayer (https://devimages.apple.com.edgekey.net/streaming/examples/bipbop_4x3/bipbop_4x3_variant.m3u8) and I am using the HlsRenderedBuilder.

**Comment by ojw28** [comment]
I haven't had a chance to try, but I think you should be disabling the video renderer if you want to leave it without a surface for an extended period of time. If instead of calling setSurface(null), you instead call setBackgrounded(true), you'll probably find that audio plays indefinitely. setBackgrounded(true) will both clear the surface and disable the renderer.

If you just clear the surface, I think video data probably keeps accumulating (and not being rendered) and eventually occupies all of the available buffer space, at which point audio stalls.

**Comment by rok5ek** [comment]
Ok thanks for the effort, I will try it as proposed.

**Comment by luckcoolla** [comment]
rok5ek, setBackgrounded(..) works for me. Please check out test button onClick code:
```
@Override
public void onClick(View v) {
  if (player != null) {
    player.setBackgrounded(!player.getBackgrounded());
    //in case of foreground
    if (!player.getBackgrounded()) {
      player.setSurface(surfaceView.getHolder().getSurface());
    }
  }
}
```

**Comment by rok5ek** [comment]
ojw28's answer was correct.
