### ISSUE TITLE
Getting wrong total duration for Encrypted CMAF contents (DRM protected)

### ISSUE THREAD

**Issue by vip644** [google/ExoPlayer#7724]
Issue description:

I've observed that ExoPlayer calculating the wrong total duration in case Encrypted CMAF content which is DRM protected but when it comes to Un-encrypted CMAF content it shows the accurate duration.

Encrypted CMAF content player image:
Total Duration: 10m01s

<img width="597" alt="Screenshot 2020-08-07 at 2 30 05 PM" src="https://user-images.githubusercontent.com/10258819/89637238-833b1400-d8c7-11ea-9c9c-433f2ff527a1.png">

Un-Encrypted CMAF content player image:
Total Duration: 9m56s

<img width="594" alt="Screenshot 2020-08-07 at 3 23 26 PM" src="https://user-images.githubusercontent.com/10258819/89637288-91893000-d8c7-11ea-8dfb-811add9e6880.png">

**Actual Duration of content: 9m56s**

Version of ExoPlayer being used
Version of ExoPlayer: 2.11.7

Device(s) and version(s) of Android being used
Device: Google Pixel 3
Version: Android 9

**Comment by ojw28** [comment]
ExoPlayer reads the duration directly from the content, so it seems most likely that ExoPlayer is doing the right thing, and that your encrypted content is specifying a different duration to your non-encrypted content. To be able to confirm this we'd need access to the content.

**Comment by vip644** [comment]
Sure, I'll provide you the encrypted content. Is it fine If I send you content over the mail?

**Comment by ojw28** [comment]
Yes, please send it to `dev.exoplayer@gmail.com`. If you could send the non-encrypted version as well for comparison, it will likely make things easier.

**Comment by vip644** [comment]
I've shared you all the details over mail. Please check your mailbox.

**Comment by ojw28** [comment]
The player shows 9:56 in both cases for me when I load the manifests up into our demo app (obviously the actual media isn't playable, because you didn't share it, but the duration is defined from the manifest anyway).

**Comment by vip644** [comment]
It seems the issue is coming from the DRM side, I need to look into that part. After you said, I've tested with Widevine as well and It's giving the correct duration. So ExoPlayer is working fine from its end.
