### ISSUE TITLE
How to play from constantly updated file ? 

### ISSUE THREAD

**Issue by Quantron7t** [google/ExoPlayer#7726]
I don't know if this question seems legit or if i missed any thing from the exoplayer docs but i had to ask this to someone. 
Can exoplayer play from a single file that is constantly updated and also play till the updated part. 
Why i am doing this ? - its because i want to seek the mp3 live radio stream since exoplayer dont seek live stream.
Was successful in doing so but the exoplayer abruptly stops and then i have to play the file again in order to listen to updated part of file and then it stops again.
I have tried posting a question in [stackoverflow](https://stackoverflow.com/questions/63214151/exoplayer-playback-with-updating-file-and-continued-source-preparing) but did not get much attention. 
In the linked question i have added a snippet that downloads the stream into a file and then play it after preparing it.
Is there a way to prepare it indefinitely ? 
how can i make exoplayer continuously play updated file without stopping or need for restarting playback from start? 
I am fairly new to android development. 
Please help me out here!

**Comment by andrewlewis** [comment]
Does #6411 address this, especially the part about implementing a custom `DataSource`? I think this is the same so I will mark this as a duplicate but please reply if you are trying to do something different.
