### ISSUE TITLE
Playing on-growing ffmpeg output with custom DataSource showing Strange Behavior 

### ISSUE THREAD

**Issue by PrinceVergil** [google/ExoPlayer#7727]
### [REQUIRED] Searched documentation and issues
i am trying similar to [6411](https://github.com/google/ExoPlayer/issues/6411)
### [REQUIRED] Question
1. My problem is that when I start Playback Exoplayer gives some duration to file. Example. 00:58
And play 00:58 then Restart the playback and then continues playing beyond 00:58.
2.Before starting the playback if screen is locked Then exoplayer shows 00:00 Duration and play's Fine .
3.Can i have 00:00 Unknown Duration so the exoplayer can play my complete media file?
    
My implementation
```
        DefaultTrackSelector trackSelector = new DefaultTrackSelector(File_upload_test.this);
        MediaSource mediaSource =  buildMediaSource(Uri.fromFile(myFile),Size);
        player = new SimpleExoPlayer.Builder(File_upload_test.this)
                .setTrackSelector(trackSelector).setLoadControl(new CustomLoadControl()).build();
        player.setPlayWhenReady(playWhenReady);
//        player.seekTo(currentWindow, playbackPosition);
        player.prepare(mediaSource, false, false);
```
```
    private MediaSource buildMediaSource(Uri uri,long Size) {
        DataSource.Factory dataSourceFactory =new  FileDataSource.Factory(Size);
        return new ProgressiveMediaSource.Factory(dataSourceFactory)
                .createMediaSource(uri);
    }
```
i have added Some logs in my FileDataSource And notice that Exoplayer first start Read() after reading some data then its call close();
when playback is completes and restarts then its continues reading complete on-growing file without any problem 

### Link to test content
i am attaching the behavior [video ](https://drive.google.com/file/d/1wi6fD9p2SWQJ4_aUsmCBGEHOy7TC2NZ3/view?usp=sharing)

**Comment by andrewlewis** [comment]
> My problem is that when I start Playback Exoplayer gives some duration to file.

Please could you check the implementation of your custom `DataSource` is not returning a fixed length, but instead returns `C.LENGTH_UNSET` when it's opened, as described in #6411? (I assume you are not using ExoPlayer's `FileDataSource` even though that class name appears in your code.) What media container format are you using?

**Comment by PrinceVergil** [comment]
1.DataSource 
Explanation=>The only change i have made is file.length to Size (Size is file length Already known).

 ` public class FileDataSource extends BaseDataSource {
    private long size;

    /** Thrown when a {@link FileDataSource} encounters an error reading a file. */
    public static class FileDataSourceException extends IOException {

        public FileDataSourceException(IOException cause) {
            super(cause);
        }

        public FileDataSourceException(String message, IOException cause) {
            super(message, cause);
        }
    }

    /** {@link DataSource.Factory} for {@link FileDataSource} instances. */
    public static final class Factory implements DataSource.Factory {
        long size;
        @Nullable private TransferListener listener;

        public Factory(long s) {
            size = s;
        }

        /**
         * Sets a {@link TransferListener} for {@link FileDataSource} instances created by this factory.
         *
         * @param listener The {@link TransferListener}.
         * @return This factory.
         */
        public Factory setListener(@Nullable TransferListener listener) {
            this.listener = listener;
            return this;
        }

        @Override
        public FileDataSource createDataSource() {
            FileDataSource dataSource = new FileDataSource(size);
            if (listener != null) {
                dataSource.addTransferListener(listener);
            }
            Log.e("data source size", String.valueOf(dataSource.size));
            return dataSource;
        }
    }

    @Nullable private RandomAccessFile file;
    @Nullable private Uri uri;
    private long bytesRemaining;
    private boolean opened;
    public FileDataSource(long size) {
        super(/* isNetwork= */ false);
        this.size = size;
    }
    @Override
    public long open(DataSpec dataSpec) throws FileDataSourceException {
        try {
            Uri uri = dataSpec.uri;
            this.uri = uri;
            transferInitializing(dataSpec);
            this.file = openLocalFile(uri);
            
            file.seek(dataSpec.position);
            //Log.e("file len", String.valueOf(file.length())+ ":size:"+size);
            bytesRemaining = dataSpec.length == C.LENGTH_UNSET ? size - dataSpec.position
                    : dataSpec.length;
            //            bytesRemaining = dataSpec.length == C.LENGTH_UNSET ? C.LENGTH_UNSET - dataSpec.position
           //              : dataSpec.length;

            if (bytesRemaining < 0) {
          //      Log.e("end Of File", String.valueOf(bytesRemaining));
                throw new EOFException();
            }
        } catch (IOException e) {
            e.printStackTrace();
        //    Log.e("end Of File2", String.valueOf(bytesRemaining));
            throw new FileDataSourceException(e);
        }
        opened = true;
        transferStarted(dataSpec);
        return bytesRemaining;
    }

    private static RandomAccessFile openLocalFile(Uri uri) throws FileDataSourceException {
        try {
            return new RandomAccessFile(Assertions.checkNotNull(uri.getPath()), "r");
        } catch (FileNotFoundException e) {
            if (!TextUtils.isEmpty(uri.getQuery()) || !TextUtils.isEmpty(uri.getFragment())) {
                throw new FileDataSourceException(
                        String.format(
                                "uri has query and/or fragment, which are not supported. Did you call Uri.parse()"
                                        + " on a string containing '?' or '#'? Use Uri.fromFile(new File(path)) to"
                                        + " avoid this. path=%s,query=%s,fragment=%s",
                                uri.getPath(), uri.getQuery(), uri.getFragment()),
                        e);
            }
            throw new FileDataSourceException(e);
        }
    }

    @Override
    public int read(byte[] buffer, int offset, int readLength) throws FileDataSourceException {
        //Log.e("buff size",buffer.length +":"+offset+":"+readLength);
        if (readLength == 0) {
         //   Log.e("readLen==0", String.valueOf(readLength));
            return 0;
        } else if (bytesRemaining == 0) {
           // Log.e("else if",bytesRemaining+":-return"+C.RESULT_END_OF_INPUT);
            return C.RESULT_END_OF_INPUT;
        } else {
            int bytesRead;
            try {
                bytesRead =
                        castNonNull(file).read(buffer, offset, (int) Math.min(bytesRemaining, readLength));
             //   Log.e("try",readLength+":-return"+bytesRemaining);
            } catch (IOException e) {
                throw new FileDataSourceException(e);
            }
            if (bytesRead > 0) {
                bytesRemaining -= bytesRead;
                bytesTransferred(bytesRead);
            }
      //      Log.e("read return", String.valueOf(bytesRead));
            return bytesRead;
        }
    }
    @Override
    @Nullable
    public Uri getUri() {
        return uri;
    }
    @Override
    public void close() throws FileDataSourceException {
        uri = null;
        Log.e("Close","Close");
        if (bytesRemaining != 0 ){
            Log.e("closing file","without end of byte remaining");
        }else {
            try {
                if (file != null) {
                    file.close();
                }
            } catch (IOException e) {
                throw new FileDataSourceException(e);
            } finally {
                file = null;
                if (opened) {
                    opened = false;
                    transferEnded();
                }
            }
        }
    }
  } ` 

2)Media container format is.mkv generated from ffmpeg 
     `-i http://117.200.221.89:3000/video -c copy -bsf:a aac_adtstoasc -movflags +faststart -y sdcard/b1.mkv`

**Comment by andrewlewis** [comment]
If the input file grows over time, I think you need to check a few things:
1. It looks like your current implementation of `open` returns the bytes remaining in the file, but wouldn't you want to return `C.LENGTH_UNSET` like detailed in #6411?
1. When you run out of data in `read` I think you need to reopen the stream so you can read data that was added since you last opened it.
1. Finally, I'm not 100% sure this approach works with the Matroska container in general. If the file grows over time you presumably want the duration to be `C.TIME_UNSET`, but it sounds like you are getting a 58 second duration. I'd set a breakpoint in `MatroskaExtractor.buildSeekMap` to see what's going on, and then set breakpoints in other places as needed to figure out the cause. You may need to change the options you pass to FFmpeg or even switch to another container format to get this to work.

**Comment by PrinceVergil** [comment]
1. `C.LENGTH_UNSET`  Works which set 00:00 duration.
But i have done some experimentation:-
    1.if i started playback after  receiving ` frame: 198, time: 8218 ` from ffmepg its shows me duration even if C.LENGTH_UNSET is return 
    2.if i wait little longer like Time:61501 then the duration of playback is 00:00

**Comment by andrewlewis** [comment]
> if i started playback after receiving frame: 198, time: 8218 from ffmepg its shows me duration even if C.LENGTH_UNSET is return

Could you try the suggestions from item 3 in my previous comment, to try to work out why the duration is becoming set when it's initially unset? Or if you are looking for a quick fix, perhaps you could try switch to using an MPEG-TS container?
