### ISSUE TITLE
Sleep exoplayer

### ISSUE THREAD

**Issue by deathvivek** [google/ExoPlayer#7728]
Anyone can tell me how to sleep exoplayer for few millisecond while it is running. I have a UI where I have to match the song lyrics with text (not form srt file )

**Comment by andrewlewis** [comment]
If you are trying to show timed text but don't have an SRT file to play, the easiest way to do this may be to generate an SRT (I think [the syntax](https://en.wikipedia.org/wiki/SubRip) is quite simple). Then you can use ExoPlayer's [support for side-loading subtitles](https://exoplayer.dev/media-sources.html#side-loading-a-subtitle-file).

If the goal is to do something when the player position reaches a certain position, please see #4317.

If you are trying to do something different, please could you give more details? I'm not sure what "sleep exoplayer" means.

**Comment by ojw28** [comment]
> please see #7624.

Did you mean to reference a different issue?

**Comment by andrewlewis** [comment]
> Did you mean to reference a different issue?

I've updated it (not sure where that came from). Thanks.

**Comment by abhikommen** [comment]
Hi , was anyone able to solve this?
Its a hard core requirement of what I'm working on right now so please suggest some way. 🥇

**Comment by andrewlewis** [comment]
@abhishekengineer Could you describe in more detail exactly what you are trying to do?
