### ISSUE TITLE
Exoplayer sometimes get source error in 2.5.4 version.

### ISSUE THREAD

**Issue by Daktm** [google/ExoPlayer#7730]
08-07 22:09:41.305  3234 28844 E ExoPlayerImplInternal: Source error.
08-07 22:09:41.305  3234 28844 E ExoPlayerImplInternal: com.google.android.exoplayer2.upstream.FileDataSource$FileDataSourceException: java.io.IOException: read failed: EIO (I/O error)
08-07 22:09:41.305  3234 28844 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.upstream.FileDataSource.read(FileDataSource.java:92)
08-07 22:09:41.305  3234 28844 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.upstream.DefaultDataSource.read(DefaultDataSource.java:142)
08-07 22:09:41.305  3234 28844 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.upstream.crypto.VeerEncryptedDataSource.read(VeerEncryptedDataSource.java:257)
08-07 22:09:41.305  3234 28844 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFromDataSource(DefaultExtractorInput.java:273)
08-07 22:09:41.305  3234 28844 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.extractor.DefaultExtractorInput.read(DefaultExtractorInput.java:66)
08-07 22:09:41.305  3234 28844 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.source.SampleQueue.sampleData(SampleQueue.java:517)
08-07 22:09:41.305  3234 28844 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.readSample(FragmentedMp4Extractor.java:1153)
08-07 22:09:41.305  3234 28844 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:275)
08-07 22:09:41.305  3234 28844 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:704)
08-07 22:09:41.305  3234 28844 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:315)
08-07 22:09:41.305  3234 28844 E ExoPlayerImplInternal: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
08-07 22:09:41.305  3234 28844 E ExoPlayerImplInternal: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
08-07 22:09:41.305  3234 28844 E ExoPlayerImplInternal: 	at java.lang.Thread.run(Thread.java:761)
08-07 22:09:41.305  3234 28844 E ExoPlayerImplInternal: Caused by: java.io.IOException: read failed: EIO (I/O error)
08-07 22:09:41.305  3234 28844 E ExoPlayerImplInternal: 	at libcore.io.IoBridge.read(IoBridge.java:481)
08-07 22:09:41.305  3234 28844 E ExoPlayerImplInternal: 	at java.io.RandomAccessFile.readBytes(RandomAccessFile.java:325)
08-07 22:09:41.305  3234 28844 E ExoPlayerImplInternal: 	at java.io.RandomAccessFile.read(RandomAccessFile.java:354)
08-07 22:09:41.305  3234 28844 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.upstream.FileDataSource.read(FileDataSource.java:90)
08-07 22:09:41.305  3234 28844 E ExoPlayerImplInternal: 	... 12 more
08-07 22:09:41.305  3234 28844 E ExoPlayerImplInternal: Caused by: android.system.ErrnoException: read failed: EIO (I/O error)
08-07 22:09:41.305  3234 28844 E ExoPlayerImplInternal: 	at libcore.io.Posix.readBytes(Native Method)
08-07 22:09:41.305  3234 28844 E ExoPlayerImplInternal: 	at libcore.io.Posix.read(Posix.java:169)
08-07 22:09:41.305  3234 28844 E ExoPlayerImplInternal: 	at libcore.io.BlockGuardOs.read(BlockGuardOs.java:231)
08-07 22:09:41.305  3234 28844 E ExoPlayerImplInternal: 	at libcore.io.IoBridge.read(IoBridge.java:471)
08-07 22:09:41.305  3234 28844 E ExoPlayerImplInternal: 	... 15 more

**Comment by andrewlewis** [comment]
Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/question.md).

A couple of specific notes:
- `VeerEncryptedDataSource` is not an ExoPlayer component and may be the cause of the error.
- Please check the media you are trying to play is valid.
- ExoPlayer 2.5.3 is three years old. I'd recommend upgrading as there are been loads of fixes since that release.
