### ISSUE TITLE
Not able play camera stream(fragmented-MP4) HLS URL into chromecast

### ISSUE THREAD

**Issue by amiya-elear** [google/ExoPlayer#7732]
### [REQUIRED] Searched documentation and issues
https://github.com/google/ExoPlayer/issues/4110
https://github.com/google/ExoPlayer/issues/6482

### [REQUIRED] Question
I have generated an HLS URL(fragemented_mp4) from my camera stream, Chromecast is not playing that HLS URL. I have tried to play some URL found on the internet I observed Chromecast not supporting all HLS URL this 
https://mnmedias.api.telequebec.tv/m3u8/29880.m3u8 URL in Chromecast paying perfectly but I have tried with another URL https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8 it's not playing. So is it an issue from the  Chromecast player side?
but both URL is playing in all other players. like shaka player,hls.js,vlc.

My Camera generated HLS URL info:
codec: avc1.42c028 (H.264 Baseline@4.0)
Bitrate
1.7 mbps
Video resolution
640x480px

Camera generated HLS URL I am able to play in shaka player and few other players also like vlc, hls.js but not able to play in Chromecast.

### Link to test content
https://www.radiantmediaplayer.com/test-your-streaming-url.html?streamProtocol=hls&streamType=live&streamUrl=https%3A%2F%2Fbitdash-a.akamaihd.net%2Fcontent%2FMI201109210084_1%2Fm3u8s%2Ff08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8

**Comment by andrewlewis** [comment]
This doesn't seem to be reporting an ExoPlayer issue. Have you read the latest comment on #6482? If that doesn't help I'd suggest reporting it on the [Cast SDK issue tracker](https://issuetracker.google.com/code/p/google-cast-sdk/issues/list).
