### ISSUE TITLE
Exoplayer fails to play certain AAC-ADTS .m3u8 files

### ISSUE THREAD

**Issue by spark85** [google/ExoPlayer#774]
The sample looks exactly like other samples created from the same app, all are being classified with an mp4a-latm MIME type, with an AAC-ATDS stream.  

Here is the the full MediaFormat:  MediaFormat(audio/mp4a-latm, -1, -1, -1, -1.0, 1, 22050, -1, -1, -1) 

The DecoderInfo object shows it is using the OMX.google.aac.decoder codec.

This audio file was created within our app; using the default framework MediaRecorder.  We set the sample rate to 22050 instead of 44100 to match the iOS build. 

Is there more information that you might find useful?  I thought it could be possible that there is a discontinuity in the sample; or the an error in the manifest header.  How should I go about looking for these issues? 

I've posted everything from the error message that I believe might be relevant. 

<09-08 15:07:14.189  27057-27057/com.google.android.exoplayer.demo I/ExoPlayerImpl﹕ Init 1.4.2
09-08 15:07:14.201  27057-27057/com.google.android.exoplayer.demo D/EventLogger﹕ start [0]
09-08 15:07:14.201  27057-27057/com.google.android.exoplayer.demo D/EventLogger﹕ state [0.00, false, P]
09-08 15:07:14.203  27057-27057/com.google.android.exoplayer.demo D/EventLogger﹕ state [0.00, true, P]
09-08 15:07:14.443  27057-27082/com.google.android.exoplayer.demo D/OpenGLRenderer﹕ endAllStagingAnimators on 0xb49a0300 (ListView) with handle 0xaec2cf40
09-08 15:07:14.544  27057-27057/com.google.android.exoplayer.demo D/EventLogger﹕ state [0.34, true, B]
09-08 15:07:14.544  27057-27057/com.google.android.exoplayer.demo D/EventLogger﹕ videoFormat [0.34, 0, 0]
09-08 15:07:14.552  27057-28353/com.google.android.exoplayer.demo I/OMXClient﹕ Using client-side OMX mux.
09-08 15:07:14.559  27057-28353/com.google.android.exoplayer.demo E/OMXMaster﹕ A component of name 'OMX.qcom.audio.decoder.aac' already exists, ignoring this one.
09-08 15:07:14.579  27057-28354/com.google.android.exoplayer.demo W/SoftAAC2﹕ aacDecoder_ConfigRaw decoderErr = 0x2003
09-08 15:07:14.579  27057-28353/com.google.android.exoplayer.demo E/ACodec﹕ [OMX.google.aac.decoder] ERROR(0x80001001)
09-08 15:07:14.579  27057-28353/com.google.android.exoplayer.demo E/ACodec﹕ signalError(omxError 0x80001001, internalError -2147483648)
09-08 15:07:14.579  27057-28353/com.google.android.exoplayer.demo E/MediaCodec﹕ Codec reported err 0x80001001, actionCode 0, while in state 6
09-08 15:07:14.585  27057-28343/com.google.android.exoplayer.demo E/ExoPlayerImplInternal﹕ Internal runtime error.
    java.lang.IllegalStateException
            at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
            at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:1033)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.drainOutputBuffer(MediaCodecTrackRenderer.java:832)' ....

....

Further down in the log 

 Caused by: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.google.aac.decoder, MediaFormat(audio/mp4a-latm, -1, -1, -1, -1.0, 1, 22050, -1, -1, -1)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:374)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:739)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:511)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:492)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:417)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:205)

Thank you,

**Comment by ojw28** [comment]
The most useful thing would probably be if you could provide the media, so that we can reproduce. Thanks!

**Comment by spark85** [comment]
Right...pretty obvious.   

Here they are. 

http://s3.amazonaws.com/instarad_audio/27/270819/index.m3u8
http://s3.amazonaws.com/instarad_audio/27/270819/stream.aac

**Comment by ojw28** [comment]
Thanks. Hm, it seems these also fail to play using Android's native media player. VLC does play them properly though.

**Comment by spark85** [comment]
Thanks, 

I'll take a look into it.

**Comment by jeoliva** [comment]
This is related with #178. The two streams provided are encoded using AAC-LTP, that is an audio codec not officially supported by Android

**Comment by spark85** [comment]
It looks like the audio files aren't actually encoded with AAC-LTP; it's just tagged with AAC-LTP instead of AAC-LC. -->  http://stackoverflow.com/questions/22198794/force-mediarecorder-to-produce-aac-lc

Could I use MediaExtractor & MediaCodec libraries to force the player to either change the MIME-TYPE on the audio file/stream; OR simply use the AAC-LC encoded audio regardless of the tag?

**Comment by jeoliva** [comment]
My quick response to this would be that's not possible. It is the Android decoder the one raising the error after parsing audio initialization data by itself. This initialization data is built by Exoplayer reading what comes in the stream, don't taking any assumption nor forcing any specific type/codec. Take a look at parseHeader method of AdtsReader class. 

The most you can do is, in parseHeader method, forcing audioObjectType variable to be 2 (AAC LC) in case it is 19 (AAC LTP) but I don't think this is a good practice...

**Comment by spark85** [comment]
Is it possible to peak and see if the format can be decoded with an AAC-LC decoder; or use a MediaExtractor & a MediaCodec to convert the AAC-ADTS stream to raw audio frames, and into an AudioTrack?  I've seen this used with another player called OpenMax.

**Comment by spark85** [comment]
After checking the parseHeader method, I'm seeing the audioObjectType is being set to 4.

**Comment by jeoliva** [comment]
Oh, you are right, I was wrong, AAC LTP object type is 4. 19 is for ER AAC LTP. More info: http://wiki.multimedia.cx/index.php?title=MPEG-4_Audio#Audio_Object_Types

You can try overriding the objectype value with number 2. You can give it a try. Probably you will need to do that for every ADTS frame because you can not trust decoder is going to analyze objectType just during initialization (while parsing initialization data).

**Comment by spark85** [comment]
The fix seems to work.  I'll test it out with a few other 'broken' audio files and let you know.  Thanks for your help.

**Comment by igor9silva** [comment]
You've never let him know @spark85! Can I? :smile:

**Comment by spark85** [comment]
Please do :)

**Comment by igor9silva** [comment]
I meant, *can I know?*.

**Comment by ojw28** [comment]
We should probably override 4 to be 2 instead by default in ExoPlayer. We already do this if the value is 1. My understanding is that Main and LTP are basically dead as formats, and that most Android devices don't have suitable decoders for them in any case. In which case we're best off just assuming it's AAC-LC and hoping for the best.
