### ISSUE TITLE
Need help about pushing my code to repository

### ISSUE THREAD

**Issue by msilucifer** [google/ExoPlayer#7747]
I made a customized engine for Australian Subtitles in streaming mode.
I want to share this code but I am not sure how to push it.
When i try to push my code it says the following.

```
remote: Permission to google/ExoPlayer.git denied to msilucifer.
fatal: unable to access 'https://github.com/google/ExoPlayer.git/': The requested URL returned error: 403
```

Waiting for your helps.
Best

**Comment by zsmatyas** [comment]
I think you need to fork your own copy of the exoplayer repository. You will have full access to that copy. Then you push the changes to that copy. After this in the stock exoplayer repository, you can create a pull request between the two.

**Comment by msilucifer** [comment]
Thanks, @zsmatyas .

But I need to push my code to one of new branches in Google's Exoplayer.
Not my repository.

And how did others create their branch in Exoplayer repository? I can't make mine there

Waiting for your helps.
Regards.

**Comment by andrewlewis** [comment]
Forking and pushing changes to the fork sounds right as a way to share the code.

For contributing this to ExoPlayer please see #7746.

**Comment by msilucifer** [comment]
Thanks for your help.
