### ISSUE TITLE
Play local mp4 video get ArrayIndexOutOfBoundsException.

### ISSUE THREAD

**Issue by Daktm** [google/ExoPlayer#7748]
### [REQUIRED] Issue description
Play a local mp4 video sometime get a ArrayIndexOutOfBoundsException.

### [REQUIRED] Reproduction steps
Hard to reproduce.

### [REQUIRED] A full bug report captured from the device
```
08-11 19:09:24.944  3242 23145 E LoadTask: Unexpected exception loading stream
08-11 19:09:24.944  3242 23145 E LoadTask: java.lang.ArrayIndexOutOfBoundsException: length=65536; regionStart=44622; regionLength=-1
08-11 19:09:24.944  3242 23145 E LoadTask: 	at java.util.Arrays.checkOffsetAndCount(Arrays.java:4857)
08-11 19:09:24.944  3242 23145 E LoadTask: 	at libcore.io.IoBridge.read(IoBridge.java:466)
08-11 19:09:24.944  3242 23145 E LoadTask: 	at java.io.RandomAccessFile.readBytes(RandomAccessFile.java:325)
08-11 19:09:24.944  3242 23145 E LoadTask: 	at java.io.RandomAccessFile.read(RandomAccessFile.java:354)
08-11 19:09:24.944  3242 23145 E LoadTask: 	at com.google.android.exoplayer2.upstream.FileDataSource.read(FileDataSource.java:90)
08-11 19:09:24.944  3242 23145 E LoadTask: 	at com.google.android.exoplayer2.upstream.DefaultDataSource.read(DefaultDataSource.java:142)
08-11 19:09:24.944  3242 23145 E LoadTask: 	at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFromDataSource(DefaultExtractorInput.java:273)
08-11 19:09:24.944  3242 23145 E LoadTask: 	at com.google.android.exoplayer2.extractor.DefaultExtractorInput.read(DefaultExtractorInput.java:66)
08-11 19:09:24.944  3242 23145 E LoadTask: 	at com.google.android.exoplayer2.source.SampleQueue.sampleData(SampleQueue.java:517)
08-11 19:09:24.944  3242 23145 E LoadTask: 	at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.readSample(FragmentedMp4Extractor.java:1153)
08-11 19:09:24.944  3242 23145 E LoadTask: 	at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:275)
08-11 19:09:24.944  3242 23145 E LoadTask: 	at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:704)
08-11 19:09:24.944  3242 23145 E LoadTask: 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:315)
08-11 19:09:24.944  3242 23145 E LoadTask: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
08-11 19:09:24.944  3242 23145 E LoadTask: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
08-11 19:09:24.944  3242 23145 E LoadTask: 	at java.lang.Thread.run(Thread.java:761)
```
### [REQUIRED] Version of ExoPlayer being used
Version 2.5.4

### [REQUIRED] Device(s) and version(s) of Android being used
Skyworth VR Headset. Android 7.1.2

**Comment by andrewlewis** [comment]
- Could you share a link to the stream you are trying to play ([see the new issue template](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md#required-link-to-test-content))?
- I'd recommend testing with a more recent ExoPlayer version if possible.
- One possible explanation is that the stream is not valid. Does it play in other players without any errors being output?

**Comment by Daktm** [comment]
this is my video
https://qvcdn.veervr.tv/vm0h3T4pXX0Zlag6WpqU6Q/hevc/d65ba3b1a643/2160p/index.mp4?sign=96330126b384b7c2ac0f219c234a8f2c&t=5f503200

**Comment by andrewlewis** [comment]
I get HTTP status code 403 when requesting that stream. It might be georestricted. Can you remove any restrictions that might cause requesting it to return status 403? Or share it in a different way?

**Comment by andrewlewis** [comment]
Never mind. I tried again and this time it loaded.

> Hard to reproduce.

Could you give some more details about what I'd need to do to see the error?

**Comment by Daktm** [comment]
https://d1cwu1o9pcv4g6.cloudfront.net/vm0h3T4pXX0Zlag6WpqU6Q/hevc/d65ba3b1a643/2160p/index.mp4
You can use up link.

**Comment by Daktm** [comment]
Sometimes the video get stuck in the part of the video. Then throw ArrayIndexOutOfBoundsException error.

**Comment by andrewlewis** [comment]
> Sometimes the video get stuck in the part of the video.

Which part of the video? I've played it through a couple of times and tried seeking around and didn't see any errors in the extractor.

Can you reproduce this if you push the file locally and play it from the device rather than over the network?
