### ISSUE TITLE
Dash HTTP 403 error when using uneven segment count for audio and video

### ISSUE THREAD

**Issue by MaTriXy** [google/ExoPlayer#775]
Hi,
I've been trying to figure how to play dash when the number of segments is different between Audio and Video. 
For example Audio has 4 segments and Video has only 3. 
The current behaviour is for each segment to try and fetch both audio and video. 
i'm not sure where is best to change that behaviour. 

Example MPD file 

    <MPD xmlns="urn:mpeg:dash:schema:mpd:2011" xmlns:mas="urn:marlin:mas:1-0:services:schemas:mpd" xmlns:mspr="urn:microsoft:playready" xmlns:cenc="urn:mpeg:cenc:2013" profiles="urn:mpeg:dash:profile:isoff-live:2011" type="static" mediaPresentationDuration="PT8S" minBufferTime="PT1.97S">
    <Period>
        <AdaptationSet mimeType="audio/mp4" segmentAlignment="true" startWithSAP="1" lang="und">
            <SegmentTemplate duration="1968" initialization="$RepresentationID$/init.mp4" media="$RepresentationID$/seg-$Number$.m4f" startNumber="0" timescale="1000"/>
            <Representation audioSamplingRate="22050" bandwidth="3613" codecs="mp4a.40.2" id="270k/audio/und">
                <AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2"/>
            </Representation>
        </AdaptationSet>
        <AdaptationSet mimeType="video/mp4" scanType="progressive" segmentAlignment="true" startWithSAP="1">
            <SegmentTemplate duration="1968" initialization="$RepresentationID$/init.mp4" media="$RepresentationID$/seg-$Number$.m4f" startNumber="0" timescale="1000"/>
            <Representation bandwidth="90869" codecs="avc1.42c00d" frameRate="30000/1001" height="270" id="270k/video/1" width="360"/>
        </AdaptationSet>
    </Period>
</MPD>

**Comment by ojw28** [comment]
The manifest indicates there are the same number of segments of audio and video, as far as I can see. Where is it indicating anything differently?

**Comment by MaTriXy** [comment]
i don't see it as well - but the actual segments are uneven. 
how is this possible?
