### ISSUE TITLE
IllegalStateException on Android P (9.X) when Other App Video Plays

### ISSUE THREAD

**Issue by jamescahall** [google/ExoPlayer#7751]
### [REQUIRED] Issue description

On Android P, specifically seen commonly on Android TVs (such as Sony and Jio) we are getting an IllegalStateException when the app enters the background during playback and playback is started in a different application (such as live TV app or YouTube).

### [REQUIRED] Reproduction steps

1) Launch app.
2) Play a video using ExoPlayer
3) Press TV button on remote to launch live TV (or Home and select and app like YouTube and start a video).  App goes in to background in this process
4) ExoPlayer reports "stop failed" and IllegalStateException error.  We aren't calling stop ourselves and only pause when the main activity onPause event occurs and on audio focus loss
5) Upon returning to the app, the player is in an unrecoverable state.

### [REQUIRED] Link to test content
Same error occurs with any video.

### [REQUIRED] A full bug report captured from the device

Error is TYPE_UNEXPECTED

2020-08-13 14:45:57.932 27620-27754/com.toongoggles.tv E/ExoPlayerImplInternal: Stop failed.
   java.lang.IllegalStateException
       at android.media.MediaCodec.native_stop(Native Method)
       at android.media.MediaCodec.stop(MediaCodec.java:2090)
       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.releaseCodec(MediaCodecRenderer.java:608)
       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.releaseCodec(MediaCodecVideoRenderer.java:508)
       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onDisabled(MediaCodecRenderer.java:562)
       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onDisabled(MediaCodecVideoRenderer.java:377)
       at com.google.android.exoplayer2.BaseRenderer.disable(BaseRenderer.java:153)
       at com.google.android.exoplayer2.ExoPlayerImplInternal.disableRenderer(ExoPlayerImplInternal.java:983)
       at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:771)
       at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:742)
       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:358)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:193)
       at android.os.HandlerThread.run(HandlerThread.java:65)

### [REQUIRED] Version of ExoPlayer being used
2.8.0

### [REQUIRED] Device(s) and version(s) of Android being used
Sony Bravia 4K UR3 (but issue appears to occur on other Android 9 TV devices as well)
Android 9

**Comment by andrewlewis** [comment]
It is hard to say exactly what the cause of the error is without a full bug report (captured via `adb bugreport`) but it's possible that the media framework's resource manager has revoked the codec from your application, and that this is causing an error to be thrown when we try to release it.

It is important to `release()` the player if you are going into the background before the lifecycle methods `onPause()`/`onStop()` (depending on API version -- see the demo app [`PlayerActivity`](https://github.com/google/ExoPlayer/blob/7414a86/demos/main/src/main/java/com/google/android/exoplayer2/demo/PlayerActivity.java)) returns, so that media framework resources are returned to the system for use by other apps. The comment that "Upon returning to the app, the player is in an unrecoverable state." makes we wonder whether you are keeping the player across background/resume.

**Comment by jamescahall** [comment]
Hi Andrew,

Thank you for your feedback.  We are utilizing the player in a service instead of in an activity due to the need to allow for a floating player that can change based upon device orientation (windows vs. fullscreen) as well as support background audio playback so the lifecycle is somewhat different.  We are NOT calling releasePlayer and the intent is not to have to rebuffed the player upon return to the app so there is a seemless experience for phone calls, notifications, changing apps, etc.  Currently we only call releasePlayer in the destroy method.  I've tested calling releasePlayer upon entering background which seems to prevent the error but then the player needs to be completely rebuilt upon return to the app which is not ideal and wastes bandwidth.

This has NOT been a problem at all until Android P on Android TV devices.  I'm guessing, and you can clarify, that this may be due to how Android P attempts to re-use codecs vs. separate initialization for each app / video session to speed up video load times.

I'm not sure the best way to tackle this as we don't want to lose background audio support nor lead to having to completely reload the player upon return to the app.  Ideally there would be some suspend and unsuspend method like we see on some other platforms like Samsung TVs.

I'll work on getting a bug report but open to any input you may have in the meantime.

**Comment by andrewlewis** [comment]
Could you try deselecting the video track when switching to the background audio use case? Retaining an audio decoder should be fine.

**Comment by jamescahall** [comment]
Hi Andrew,

Thank you for the input.  Disabling the video renderer upon entering the background appears to resolve the issue.

Thanks
James
