### ISSUE TITLE
Failed to resolve error with andriodx. Unable to even start exoplayer

### ISSUE THREAD

**Issue by ghost** [google/ExoPlayer#7752]
[Edited to remove issue template, which wasn't filled in.]

**Comment by andrewlewis** [comment]
I'm not aware of any issues with the build setup at the moment. There isn't enough information here for us to help. Can you share build/error logs, version information or anything else that might help us diagnose the issue?

**Comment by urboihotshot** [comment]
![imagedesc](https://user-images.githubusercontent.com/58696605/90319872-bfa3eb00-df2b-11ea-90b9-29667eacc398.PNG)

Been trying for close to a month now, download different andriod studios and gradle. It keeps writing failed to resolve error after dowloading. It doesn't work for me at all. I use the latest andriod studio and andriodx. Please help

**Comment by andrewlewis** [comment]
Filed again in #7769 and answered there so closing this one.
