### ISSUE TITLE
Playback of Clearkey key rotation content with live profile getting failed after playing for few seconds

### ISSUE THREAD

**Issue by mkcdot** [google/ExoPlayer#7753]
### Question
I am generating clearkey dash content with key rotation in live profile using shaka packager.
Shaka packager Command:
```
shaka_packager.exe 'in=udp://127.0.0.1:1234,stream=audio,init_segment=audio_init.mp4,segment_template=audio_$Number$.m4s,drm_label=AUDIO' 'in=udp://127.0.0.1:1234,stream=video,init_segment=video_init.mp4,segment_template=h264_360p_$Number$.m4s,drm_label=SD' --enable_raw_key_encryption --crypto_period_duration 120 --keys label=AUDIO:key_id=279926496a7f5d25da69f2b3b2799a81:key=eee0f2b3b279926496a7f5d25da692f6,label=SD:key_id=279926496a7f5d25da69f2b3b2799a81:key=eee0f2b3b279926496a7f5d25da692f6 --mpd_output h264.mpd
```

When I am playing the dash content on exoplayer, The playback fails after playing for few seconds.

### Additional information
I have configured license server with all required keys and exoplayer can get required key based on currently running segment.
I am also able to completely play onDemand profile content with key rotation using same keys.

### A full bug report captured from the device
Full log report of the exoplayer: 
[Exoplayer log.txt](https://github.com/google/ExoPlayer/files/5073354/Exoplayer.log.txt)

**Comment by andrewlewis** [comment]
The exception is not very informative here:

```
     Caused by: android.media.MediaCodec$CryptoException: Unknown Error
        at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
```

The only media framework logging that stood out was `I/MediaDrm: Drm event (4,0)`, but I'm not sure if that helps.

@ojw28 @AquilesCanta Please could you take a look? Thanks.

**Comment by ojw28** [comment]
For us to investigate this further, I think you will need to provide a sample playable DASH stream that reproduces the issue.

**Comment by mkcdot** [comment]
I am running dash server on local network which is not accessible publicly.
I can share the content files generated during live-session. But when I play that pre-generated content, I get different error and playback stops.
`E/EventLogger: playerFailed [eventTime=168.73, mediaPos=1697.58, window=0, period=0
      com.google.android.exoplayer2.ExoPlaybackException: MediaCodecAudioRenderer error, index=1, format=Format(0, null, null, audio/mp4a-latm, mp4a.40.2, 137077, und, [-1, -1, -1.0], [2, 44100]), format_supported=YES
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:535)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:230)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: android.media.MediaCodec$CryptoException: Crypto key not available
        at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
        at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:2702)
        at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.queueSecureInputBuffer(SynchronousMediaCodecAdapter.java:75)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1394)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:842)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:870)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:464)
        at android.os.Handler.dispatchMessage(Handler.java:103) 
        at android.os.Looper.loop(Looper.java:230) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
    ]`

I can share these files but it will not reproduce same error as I am getting during live session.
Please suggest how can I share you dash stream?

**Comment by mkcdot** [comment]
I forgot to add "drm_multi_session": true in sample entry of exoplayer when moving from single key to key rotation testing.
Now after adding that, playback with key rotation & live profile is also working without any glitch/failure (even when playback is seeked to any past timestamp).

Only problem now I have is initial delay when starting playback. It takes 10 seconds to start playback. Is this normal behaviour in live profile? There is no delay when I play onDemand profile dash content.
Is it possible to reduce this delay?

**Comment by ojw28** [comment]
There's nothing that would be expected to cause a 10 second delay on the client side, no.

If you're unable to share a working test stream, then there's not much we can do to debug where the delay might be coming from.

**Comment by mkcdot** [comment]
I have attached the dash content zip generated using shaka packager (with the command given in question).
[sintel_live_clearkey_keyrotation.zip](https://github.com/google/ExoPlayer/files/5090000/sintel_live_clearkey_keyrotation.zip)

**Comment by ojw28** [comment]
As above, we need a working test stream. So in particular, we need an accessible license server that will respond with the necessary keys. It's not possible for us to tell you where the delay is coming from if we can't actually play the content in the same way as you're playing it. Ideally, please just provide a JSON snippet that we can put into the demo app's `exolist.json` file.

I did look at the same content provided above, and there was nothing obviously wrong with it. There's no obvious delay being introduced anywhere up until the point at which the license request is made, and from that point we cannot reproduce what's happening due to the lack of a working test stream.
