### ISSUE TITLE
Reading the TsExtractor code and see its methods `sniff(ExtractorInput input)`， some problems 

### ISSUE THREAD

**Issue by JaredLees** [google/ExoPlayer#7754]
Reading the TsExtractor code and see its methods `sniff(ExtractorInput input)`， some problems behind it：

```
public static final int TS_PACKET_SIZE = 188; // why it is 188？
private static final int SNIFF_TS_PACKET_COUNT = 5; // why it is 5？
private static final int SNIFF_TS_PACKET_COUNT = 5; // why it is 5？

public boolean sniff(ExtractorInput input) throws IOException, InterruptedException {
    byte[] buffer = tsPacketBuffer.data;
    input.peekFully(buffer, 0, TS_PACKET_SIZE * SNIFF_TS_PACKET_COUNT);
    for (int startPosCandidate = 0; startPosCandidate < TS_PACKET_SIZE; startPosCandidate++) {
      // Try to identify at least SNIFF_TS_PACKET_COUNT packets starting with TS_SYNC_BYTE.
      boolean isSyncBytePatternCorrect = true;
      for (int i = 0; i < SNIFF_TS_PACKET_COUNT; i++) {
        if (buffer[startPosCandidate + i * TS_PACKET_SIZE] != TS_SYNC_BYTE) {
          isSyncBytePatternCorrect = false;
          break;
        }
      }
      if (isSyncBytePatternCorrect) {
        input.skipFully(startPosCandidate);
        return true;
      }
    }
    return false;
  }
```
I wonder why loops inside don't start with i =0 and end at buffer.length, but it's a complicated calculation. What is the principle? Thank you!

**Comment by AquilesCanta** [comment]
I suggest you have a look at ISO/IEC 13818-1 for some context on what a Transport stream looks like (packets are 188 bytes) and what the spec expects from the Transport Stream receiving end (e.g. synchronisation guidelines: try to find 5 consecutive packets). Also keep in mind that Transport stream is a stream to which clients need to synchronise, which means packet boundaries are not necessarily aligned with file boundaries therefor the complicated loop. Hope this helps!

**Comment by JaredLees** [comment]
thanks!
