### ISSUE TITLE
 How to use the ffmpeg extension within exoplayer ?

### ISSUE THREAD

**Issue by ChristianGiuseppe** [google/ExoPlayer#7755]
Hi, I'm trying to use the FFmpeg extension inside exoplayer. I followed the [](https://github.com/google/ExoPlayer/tree/release-v2/extensions/ffmpeg) guide below but it is not very clear to me how to go about using the extension. Could anyone help me?

**Comment by andrewlewis** [comment]
The [README](https://github.com/google/ExoPlayer/blob/3fd7d21/extensions/ffmpeg/README.md#using-the-extension) has a section on using the extension. Does that help? If not please could you give some more information about where you get stuck and what you've tried?
