### ISSUE TITLE
Exoplayer not playing offline download after toggling wifi

### ISSUE THREAD

**Issue by letaochenyuja** [google/ExoPlayer#7757]
### [REQUIRED] Searched documentation and issues
To download the video, I followed the sample code here: https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/source/hls/offline/HlsDownloader.html

### [REQUIRED] Question
If I start my app with wifi off, offline downloaded videos play fine.

I exit the video, then toggle wifi (on, then off), 
I get a black screen when watching the same video now. After a few seconds, this error message (nothing else):
```
E/ExoPlayerImplInternal: Source error.
```

Is there a way to force cache usage? 

Code for how I get the MediaSource:
```
SimpleCache sc = ...
DefaultDataSourceFactory dataSourceFactory = new DefaultDataSourceFactory(app, "exoplayer-test");
DefaultExtractorsFactory extractorsFactory = new DefaultExtractorsFactory().setConstantBitrateSeekingEnabled(true);
CacheDataSourceFactory cacheDataSourceFactory = new CacheDataSourceFactory(sc, dataSourceFactory, CacheDataSource.FLAG_BLOCK_ON_CACHE);
MediaSource mediaSource = new HlsMediaSource.Factory(cacheDataSourceFactory).createMediaSource(uri);
```

**Comment by letaochenyuja** [comment]
Seems to be fixed when I set the PlaylistParserFactory
```
                mediaSource = new HlsMediaSource.Factory(cacheDataSourceFactory)
                        .setPlaylistParserFactory(
                                new FilteringHlsPlaylistParserFactory(
                                        new DefaultHlsPlaylistParserFactory(),
                                        Collections.singletonList(new StreamKey(HlsMasterPlaylist.GROUP_INDEX_VARIANT, 0))))
                        .createMediaSource(uri);
```

Not sure what this does but swag

**Comment by ojw28** [comment]
Our [download documentation](https://exoplayer.dev/downloading-media.html#downloading-and-playing-adaptive-streams) explains how to do this properly. You should use `DownloadHelper.createMediaSource` to create a source for playback. As per the bottom of that page:

> The created MediaSource is aware of which tracks have been downloaded, and so will only attempt to use these tracks during playback. See PlayerActivity in the demo app for a concrete example.
