### ISSUE TITLE
Buffering Issues

### ISSUE THREAD

**Issue by isaranghi** [google/ExoPlayer#7758]
Hello,

I am using Exoplayer Version 2.11.4 in a Leanback (AndroidTV) application. My media source is ProgressiveMediaSource. The media is hosted on remote server. I have noticed that when I play the exact same source with Exoplayer, I see a lot of buffering issues (often player is stuck buffering the stream).... The same stream works perfectly fine on another player (I have tried VLC and Kodi's media player). Currently I am using Exoplayer with DefaultLoadControl and default buffer duration settings. Since my application is targeted for high powered devices (Android TV), is there any recommended setting that I need to do to fix this buffering issues?

Thanks in advance.

**Comment by marcbaechinger** [comment]
Can you provide us with a URL to one of these streams so we can look into this?
