### ISSUE TITLE
Adapting bar height for DefaultTimeBar when dragging/in focus

### ISSUE THREAD

**Issue by AlexDundar** [google/ExoPlayer#7759]
I use `ExoPlayer `in my `Android `App and I try to customize player controls. All works fine, but I didn't find, how to change field `bar_height `for `DefaultTimeBar` for several states. For now I use it like the following:

  ```
<com.google.android.exoplayer2.ui.DefaultTimeBar
                    android:id="@id/exo_progress"
                    android:layout_width="match_parent"
                    android:layout_height="26dp"
                    android:layout_centerVertical="true"
                    android:focusable="true"
                    app:bar_height="4dp"
                    app:buffered_color="@color/gray"
                    app:played_color="@color/red"
                    app:scrubber_color="@color/white"
                    app:scrubber_dragged_size="24dp"
                    app:scrubber_enabled_size="12dp"
                    app:unplayed_color="@color/white_transparent_30p" />

```

And I see that scrubber size changes depending on focus state (it is what I want), but `bar_height` is always `4dp` and I can not find how to change it for state "in focus". How can I do it?

**Comment by marcbaechinger** [comment]
Setting `app:bar_height="4dp"` with a `com.google.android.exoplayer2.ui.DefaultTimeBar` works fine as you say and I double checked. There is currently no way to change the `bar_height` depending on a give state like for the scrubber I'm afraid.

**Comment by ojw28** [comment]
Closing because we have no plan to support this. Developers are free to fork our UI components if they require very specific customizations.
