### ISSUE TITLE
Can't set audio session ID

### ISSUE THREAD

**Issue by vhow** [google/ExoPlayer#7760]
Can you add a `setAudioSessionId` API like Android MediaPlayer?
https://developer.android.com/reference/android/media/MediaPlayer#setAudioSessionId(int)

**Comment by andrewlewis** [comment]
This already exists on the development branch ([here](https://github.com/google/ExoPlayer/blob/eee9b31/library/core/src/main/java/com/google/android/exoplayer2/SimpleExoPlayer.java#L868)) and should be included in the next release soon.

If you need this now, #6975 has instructions for setting the audio session ID on the audio sink directly.
