### ISSUE TITLE
cannot play the dash video

### ISSUE THREAD

**Issue by michael-eddy** [google/ExoPlayer#7761]
- i used the DashManifestParser create a dashManifest from mpd string.
- It is normal from the creation of the player to the loading of the mediaSource. The video cannot be played even if the auto-play attribute is set, and the pause icon displayed on the play button indicates that the video is "playing". 
- But in fact the video did not play and there was no sound. Below is the detailed data of the mpd file and video information that I have spliced out based on the video information. 
- What exactly caused this situation? Thanks!
[mpd.zip](https://github.com/google/ExoPlayer/files/5079167/mpd.zip)

the IDE output  the log:
```
08-17 21:05:23.909 I/MediaCodec(19969): [OMX.qcom.video.decoder.avc] setting surface generation to 20448262
08-17 21:05:23.909 D/SurfaceUtils(19969): disconnecting from surface 0x74568b4010, reason connectToSurface(reconnect)
08-17 21:05:23.909 D/SurfaceUtils(19969): connecting to surface 0x74568b4010, reason connectToSurface(reconnect)
08-17 21:05:23.923 D/SurfaceUtils(19969): set up nativeWindow 0x74568b4010 for 852x480, color 0x7fa30c06, rotation 0, usage 0x20002900
08-17 21:05:23.946 D/SurfaceUtils(19969): set up nativeWindow 0x74568b4010 for 864x480, color 0x7fa30c06, rotation 0, usage 0x20002900
08-17 21:05:26.982 E/ExoPlayerImplInternal(19969): Source error.
08-17 21:05:26.982 E/ExoPlayerImplInternal(19969): java.io.EOFException
08-17 21:05:26.982 E/ExoPlayerImplInternal(19969): 	at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFromDataSource(DefaultExtractorInput.java:265)
08-17 21:05:26.982 E/ExoPlayerImplInternal(19969): 	at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:72)
08-17 21:05:26.982 E/ExoPlayerImplInternal(19969): 	at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:81)
08-17 21:05:26.982 E/ExoPlayerImplInternal(19969): 	at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.readAtomPayload(FragmentedMp4Extractor.java:424)
08-17 21:05:26.982 E/ExoPlayerImplInternal(19969): 	at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:315)
08-17 21:05:26.982 E/ExoPlayerImplInternal(19969): 	at com.google.android.exoplayer2.source.chunk.InitializationChunk.load(InitializationChunk.java:89)
08-17 21:05:26.982 E/ExoPlayerImplInternal(19969): 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
08-17 21:05:26.982 E/ExoPlayerImplInternal(19969): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-17 21:05:26.982 E/ExoPlayerImplInternal(19969): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-17 21:05:26.982 E/ExoPlayerImplInternal(19969): 	at java.lang.Thread.run(Thread.java:919)
08-17 21:05:26.995 D/SurfaceUtils(19969): disconnecting from surface 0x74568b4010, reason disconnectFromSurface
```

**Comment by marcbaechinger** [comment]
The `EOFException` tells that the streamed file ends before it is expected to end.  

Can you just upload the mpd directly? I see there is a `build.xml` and `data.json` file inside the zip file but I can not extract it because it needs a pkzip which I do not have. Can you pack with another tool like standard unix zip?

**Comment by ojw28** [comment]
Please also refer to the comment I left on your other issue (https://github.com/google/ExoPlayer/issues/7687):

> Generating valid content is outside the scope of this issue tracker, so I think we can close this. If you have questions about generating valid content, perhaps try StackOverflow.

If your content doesn't work in _any_ player, then it's likely that your content is malformed. This issue tracker is for ExoPlayer issues, not with issues you have with whatever software you're using to generate your content. Hence, in addition to providing what Marc requests above, please also validate that your content plays successfully in at least one other media player, and let us know which media player that is.

**Comment by michael-eddy** [comment]
> The `EOFException` tells that the streamed file ends before it is expected to end.
> 
> Can you just upload the mpd directly? I see there is a `build.xml` and `data.json` file inside the zip file but I can not extract it because it needs a pkzip which I do not have. Can you pack with another tool like standard unix zip?

thanks,the files is all here.
[mpd.zip](https://github.com/google/ExoPlayer/files/5087589/mpd.zip)
create by 7z

**Comment by michael-eddy** [comment]
> Please also refer to the comment I left on your other issue (#7687):
> 
> > Generating valid content is outside the scope of this issue tracker, so I think we can close this. If you have questions about generating valid content, perhaps try StackOverflow.
> 
> If your content doesn't work in _any_ player, then it's likely that your content is malformed. This issue tracker is for ExoPlayer issues, not with issues you have with whatever software you're using to generate your content. Hence, in addition to providing what Marc requests above, please also validate that your content plays successfully in at least one other media player, and let us know which media player that is.

the same code (mpd string) in win10,vlc player with uwp

**Comment by marcbaechinger** [comment]
I can not extract that with standard unzip. I see what in the archive but it does not seem to include an mpd xml file:

```
Archive:  mpd.zip
   skipping: mpd/build.xml           need PK compat. v6.3 (can do v4.5)
   skipping: mpd/data.json           need PK compat. v6.3 (can do v4.5)
    testing: mpd/                     OK
No errors detected in mpd.zip for the 1 file tested.
2 files skipped because of unsupported compression or encoding.
```

To make it easy, you can probably upload the mpd file without compressing it? I think it should be very small so no need for zipping it. :)

**Comment by michael-eddy** [comment]
> I can not extract that with standard unzip. I see what in the archive but it does not seem to include an mpd xml file:
> 
> ```
> Archive:  mpd.zip
>    skipping: mpd/build.xml           need PK compat. v6.3 (can do v4.5)
>    skipping: mpd/data.json           need PK compat. v6.3 (can do v4.5)
>     testing: mpd/                     OK
> No errors detected in mpd.zip for the 1 file tested.
> 2 files skipped because of unsupported compression or encoding.
> ```
> 
> To make it easy, you can probably upload the mpd file without compressing it? I think it should be very small so no need for zipping it. :)

it's wired....or u can try remand the extension？
[rename this in json extension.log](https://github.com/google/ExoPlayer/files/5090286/rename.this.in.json.extension.log)
[rename this in mpd extension.log](https://github.com/google/ExoPlayer/files/5090288/rename.this.in.mpd.extension.log)

**Comment by marcbaechinger** [comment]
I wouldn't really know where the uri's come from to download something from this manifest:

```
<MPD xmlns="urn:mpeg:DASH:schema:MPD:2011"  profiles="urn:mpeg:dash:profile:isoff-on-demand:2011" type="static"
 mediaPresentationDuration="PT3M9S">
  <Period>
    <AdaptationSet>
      <ContentComponent contentType="video" id="1" />
      <Representation bandwidth="3922280" codecs="avc1.640028" height="1080" id="112" mimeType="video/mp4" width="1920">
        <BaseURL></BaseURL>
        <SegmentBase indexRange="976-1463">
          <Initialization range="0-975" />
        </SegmentBase>
      </Representation>
    </AdaptationSet>
    <AdaptationSet>
      <ContentComponent contentType="audio" id="2" />
      <Representation bandwidth="319183" codecs="mp4a.40.2" id="30280" mimeType="audio/mp4" >
        <BaseURL></BaseURL>
        <SegmentBase indexRange="908-1539">
          <Initialization range="0-907" />
        </SegmentBase>
      </Representation>
    </AdaptationSet>
  </Period>
</MPD>
```

I think it's a problem with the DASH manifest. I'm afraid but we can't really support you with generating valid DASH manifests. As a rule of thumb I'd try it with various player first, if it fails with either of this players, it's probably a problem with the manifest.

**Comment by michael-eddy** [comment]
> I wouldn't really know where the uri's come from to download something from this manifest:
> 
> ```
> <MPD xmlns="urn:mpeg:DASH:schema:MPD:2011"  profiles="urn:mpeg:dash:profile:isoff-on-demand:2011" type="static"
>  mediaPresentationDuration="PT3M9S">
>   <Period>
>     <AdaptationSet>
>       <ContentComponent contentType="video" id="1" />
>       <Representation bandwidth="3922280" codecs="avc1.640028" height="1080" id="112" mimeType="video/mp4" width="1920">
>         <BaseURL></BaseURL>
>         <SegmentBase indexRange="976-1463">
>           <Initialization range="0-975" />
>         </SegmentBase>
>       </Representation>
>     </AdaptationSet>
>     <AdaptationSet>
>       <ContentComponent contentType="audio" id="2" />
>       <Representation bandwidth="319183" codecs="mp4a.40.2" id="30280" mimeType="audio/mp4" >
>         <BaseURL></BaseURL>
>         <SegmentBase indexRange="908-1539">
>           <Initialization range="0-907" />
>         </SegmentBase>
>       </Representation>
>     </AdaptationSet>
>   </Period>
> </MPD>
> ```
> 
> I think it's a problem with the DASH manifest. I'm afraid but we can't really support you with generating valid DASH manifests. As a rule of thumb I'd try it with various player first, if it fails with either of this players, it's probably a problem with the manifest.

here has the windows platform project.i got the mpd from here `https://github.com/xiaoyaocz/biliuwp/blob/master/BiliBili.UWP/Helper/PlayurlHelper.cs#L1101`, this progrem this playing the video with mpd model.
I came into contact with mpd files for the first time. Does each player have different requirements for the mpd format?

**Comment by ojw28** [comment]
> Does each player have different requirements for the mpd format?

Not really, although some players may support a different subset of features. For example, some players might not support multiple `Period` elements.

I think the manifest you're providing is just broken. As @marcbaechinger says, there aren't any URLs defined in the manifest above that tell the player where it should be loading segments from. Why are the `BaseURL` elements empty? How can the player know what the URLs of the media segments are from this manifest?

Closing this, since it seems clear that you're not providing the player with valid media. If you still believe that you're providing valid media, please reply to this issue providing all of the files that make up the media, in the same folder/directory structure as it would be hosted. Note that a DASH manifest is not a self contained, playable piece of media. It will refer to other files that contain the actual media data as well (or at least, it should do, this is one thing that appears to be missing in the manifest defined above).
