### ISSUE TITLE
Video Preview Gone When Given A shape to parent View

### ISSUE THREAD

**Issue by Mr-Ramzan** [google/ExoPlayer#7764]
No Relevant Question Asked here as I saw.

I Tried to give shape to the parent view to EXO Player view Video was playing before But After only Audio is I have left with. Controller show and work well.

Its Not Bug Or maybe it is but I haven't seen anything Relevant in Logs.

**I am Using Shape Of View Lib From Github**

**Sample project link to recreate Issue**
**https://drive.google.com/file/d/1DpZFHCd8N68UvqFOSqQ_zjaTESlopkcV/view?usp=sharing**

Please have a look it's Urgent for me

**Comment by Mr-Ramzan** [comment]
@ojw28 Please Guide

**Comment by andrewlewis** [comment]
Have you tried using `TextureView`? See also #5714 and https://exoplayer.dev/ui-components.html#choosing-a-surface-type.

**Comment by Mr-Ramzan** [comment]
@andrewlewis  Thanks For Quick Response  Yes I have tried all three types by default are provided in Exoplayer

I have also given a link to sample project in which you can see preview is not visible

**Comment by andrewlewis** [comment]
I think this might be a limitation of the way the 'shape of view' library works. I had a quick look at its code and I'd guess the way it forces using a software layer may be problematic. I suggest asking for help at https://github.com/florent37/ShapeOfView/issues/73.

**Comment by andrewlewis** [comment]
Closing as this doesn't appear to be a problem with the way ExoPlayer works.

**Comment by Mr-Ramzan** [comment]
@andrewlewis Thanks for pointing right direction I have resolved the issue
