### ISSUE TITLE
Unable to import exoplayer with andriodx, always writing Failed to resolve error after downloading

### ISSUE THREAD

**Issue by urboihotshot** [google/ExoPlayer#7769]
![imagedesc](https://user-images.githubusercontent.com/58696605/90386060-88405600-e073-11ea-877b-087e55d745f2.PNG)
Pls what's the solution?

**Comment by marcbaechinger** [comment]
Seems to me there is a typo in the package name? 

`com.google.android.exoplayer`
vs.
`com.google.andriod.exoplayer`

**Comment by urboihotshot** [comment]
Thanks a lot @marcbaechinger. You are a life saver. Have been trying for close to a month now, not knowing my error is the spelling of android. I really appreciate. God bless

**Comment by marcbaechinger** [comment]
Glad I was able to help! I close this issue then.
