### ISSUE TITLE
When playback fails, include the index of the failing renderer in ExoPlaybackException

### ISSUE THREAD

**Issue by IanDBird** [google/ExoPlayer#777]
When investigating https://github.com/google/ExoPlayer/pull/776, I found that if the SRT (or whatever subtitle track) isn't parsed correctly, leading to an exception, this is translated to a `ExoPlaybackException` as a "Internal track renderer error". This then basically prevents any playback from continuing.

Is it (could it be) possible for an application to detect the "source" of the failure (e.g. the track renderer) and decide to simply disable and continue playback? For something like a subtitle track, I think starting playback and toasting the user that the subtitle appears to be invalid so is being ignored is preferable from the UX perspective.

**Comment by ojw28** [comment]
- For subtitles, we should just make the parsers progressively less strict as we find issues. The WebVTT and TTML parsers already have a ```strictParsing``` parameter, that defaults to false.
- I don't think we want to go as far as allowing playback to proceed seamlessly in this case; the hooks that would be required are a bit invasive given what's being achieved. We could add the renderer index into the ExoPlaybackException that gets reported back to the application though. This would allow you to determine whether the source was the text renderer and take appropriate action. Sound sufficient?

**Comment by IanDBird** [comment]
Both sound great!

After an `ExoPlaybackException` occurs, and the application decides to disable a specific track, how can it "retry"? Would/should it call `prepare` again but set the the selected track of the text renderer to `-1`?

**Comment by ojw28** [comment]
When you call prepare again you'll need to pass a fresh set of renderers. You'd probably just pass a set that omitted the text one. Or you can set the selected track index to -1; either should work.

**Comment by ojw28** [comment]
This is fixed in 2.x. See [here](https://github.com/google/ExoPlayer/blob/0e60335064c87b0d62665eab0ac2a5f8a048e236/library/src/main/java/com/google/android/exoplayer/ExoPlaybackException.java#L55).
