### ISSUE TITLE
parse Program Configuration Element (PCE) when parsing audio specific config (AAC)

### ISSUE THREAD

**Issue by xufuji456** [google/ExoPlayer#7770]
Hello, guys of developer. I found there is something wrong that Mp4Extractor parses the channel of AAC.
First, it parses channel is 2. Then parses aacAudioSpecificConfig, and the result of channel is 0. I Found FFmpeg when encountering channel is 0, it will parse the left of bits, which calls PCE(Program Configuration Element), to calculate the correct result of channel. The source code of FFmpeg is: the method of decode_ga_specific_config() in aacdec_template.c,
when the channel_config is 0, it will call the method of decode_pce().
Here is the video(the second audio track): [https://drive.google.com/file/d/1f-Zf6jINarcKnZnrP0ye8SRj0aPCwOXc/view](url)
Looking forward to your reply sincerely.

**Comment by marcbaechinger** [comment]
You are right, we currently do not parse the Program Configuration Element.

If the [channel configuration is 0 (zero), an` UnsupportedOperationException` is thrown](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/util/CodecSpecificDataUtil.java#L365). 

I think that is what would happen if I played the sample from the Drive-Url you pasted above. If you want me to confirm that with your media, please make the url readable. Access is currently restricted.

 I marked this issue as an enhancement. We will update this issue when there is an update around this.

**Comment by xufuji456** [comment]
OK, Thank  you.
