### ISSUE TITLE
Exo IMA extension is not respecting user's preferences ads opt out (&rdid=)

### ISSUE THREAD

**Issue by priscila225** [google/ExoPlayer#7772]
### Question
I had checked the User's preference before append the &rdid= for pubads url to pass to IMA extension. Somehow IMA is appending even we passing blank value or zeros 0000-0000-0000 for opt out case (is_lat=1)

This is easy to reproduce on sample too. I used the google sample checking isLimitAdTrackingEnabled before append or not this value. Check the results using charles to see the calls here: 

```
https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=%2F124319096%2Fexternal%2Fsingle_ad_samples&ciu_szs=300x250&gdfp_req=1&env=vp&output=xml_vast4&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dlinear&correlator=3613992415143084&ms=KCQY4rJgUViUMCQLAteRapi_sTowU4QB9Zza1QRMLoNUUWTRU_JiWVx_QdZAUEfX19sOYn4ct41UhG5p78RCPvJGRKACrSa5p7G-MZiXCQqSMMU7c6PWjs7X-8Yq-46eCSEVT22rZONtsAawU9rRlBjtDDvE3B8X7sxXTSSJ2WhR5bXS0LGnU0NoP5zaG2lFz2oGl8sbVisSiPM9o9Htro9-TBCJt4xkuJf_FDq9ZlrJeH1DVaXAgDiS0vtqNR38T5nkq0gXZ19EHi3CvN7Fc6RIPsR3ynAcY-PqGqZESUQOQOsvuCj8Hi7dxs1JqhcWI1qGqphOt-qEdU7Z916Rsw&sdkv=h.3.233.0%2Fn.android.3.19.4%2Fcom.google.ads.interactivemedia.v3.samples.videoplayerapp&osd=2&frm=0&vis=1&sdr=1&hl=pt&idtype=adid&is_lat=1&rdid=46ae4eb0-d719-4149-bb4a-10ca1ad1abe1&is_amp=0&js=ima-android.3.19.4&an=com.google.ads.interactivemedia.v3.samples.videoplayerapp&msid=com.google.ads.interactivemedia.v3.samples.videoplayerapp&mv=82141510.com.android.vending&u_so=l&sdki=445&sdk_apis=7%2C8&omid_p=Google1%2Fandroid.3.19.4&url=com.google.ads.interactivemedia.v3.samples.videoplayerapp&eid=44717393&dlt=1597705525946&idt=448&dt=1597705533130&scor=3679774915919482
```

Can you please verifiy if it's the normal behavior on IMA extension side? How we can hide this rdid when users opt out this value?
Thank you

**Comment by cadalt** [comment]
we are trying to respect California Consumer Privacy Act and not include the users rdid in the ad tag when the User has chosen to limit ad tracking, but no matter what we do it gets inserted

**Comment by mhr78** [comment]
^ Same here! Our company is trying to determine how this works since we can see rdid for is_lat=1 case and we tried everything on our side except run on google sample like you did. I can't find a solution for this IMA situation. Please let us know if you find it.

**Comment by andrewlewis** [comment]
I understand from the IMA SDK team that the `is_lat` setting is enforced server-side.

**Comment by priscila225** [comment]
Got it. Thank you Andrew! I'll close this question
