### ISSUE TITLE
Please help me implement audio into playlist using ClippingMediaSource

### ISSUE THREAD

**Issue by AndersonCrew** [google/ExoPlayer#7773]
I have list of video, then I buildMediaSource by ConcatenatingMediaSource together 
// These factories are used to construct two media sources below
        val dataSourceFactory : DataSource.Factory = DefaultDataSourceFactory(this, "ABC")
        val mediaSourceFactory = ProgressiveMediaSource.Factory(dataSourceFactory)

        val concatenatingMediaSource = ConcatenatingMediaSource()
        for (videoUri in list) {
            concatenatingMediaSource.addMediaSource( mediaSourceFactory.createMediaSource(videoUri)
         }

      return concatenatingMediaSource

Now, I have audio, I want to play audio at 00:05 seconds, it's mean when the playlist play at 5s,  I want to start audio together, how can I do that?

In my code, but it's not working

             val audiSource = ProgressiveMediaSource.Factory(dataSourceFactory).createMediaSource(Uri.parse(it))

             return  MergingMediaSource(
                concatenatingMediaSource,
                ClippingMediaSource(audiSource, 5000000, C.TIME_END_OF_SOURCE)
            )

**Comment by andrewlewis** [comment]
Please try `adjustPeriodTimeOffsets` added in 0a89d0e8c3b0fa1a5e211e72ef95d35a1c69b5b3, and see also #6103. This is currently on the `dev-v2` branch but will be in a release soon.
