### ISSUE TITLE
How can I get current position realtime when ExoPlay are running?

### ISSUE THREAD

**Issue by kunpark168** [google/ExoPlayer#7775]
I do not find anything to the listener when my video is running? Please help me!

**Comment by marcbaechinger** [comment]
There is the method 'Player.getCurrentPosition()' which gives the current position. You are correct that there is no listener on the player which calls your app repeatedly to report changes in the position. 

There is `PlayerControlView.setProgressUpdateListener` to register a `ProgressUpdateListener`. It is called each time the UI has updated so you can sync with UI updates. The interval of calling this listener varies according to whether the player is playing or not.

Depending on your use case, it's probably easiest to implement your own polling from the app thread that calls `getCurrentPosition()` frequently. The `View` class gives you an easy option to call a `Runnable` delayed. A simple implementation could look like this:

```
private void getCurrentPlayerPosition() {
  Log.d("TAG", "current pos: " + player.getCurrentPosition());
  if (player.isPlaying()) {
      playerView.postDelayed(this::getCurrentPlayerPosition, POLL_INTERVAL_MS);
  }
}

player.addListener(new Player.EventListener() {
  @Override
  public void onIsPlayingChanged(boolean isPlaying) {
    if (isPlaying) {
      playerView.postDelayed(this::getCurrentPlayerPosition, POLL_INTERVAL_MS);
    }
  }
});
```
