### ISSUE TITLE
Is it Possible to Skip Midroll Ad playing when Seeked / Resume the content beyond the Ad position

### ISSUE THREAD

**Issue by ursurya** [google/ExoPlayer#7776]
Hi,
I want VMAP Midroll ad not to play when Resume or seek beyond the Ad position . Say, when i had Midroll Ad at 20th min and i seeked directly to 30th minute, the midroll Ad should not play. Currently the last midroll Ad plays .Can we control it ?

Also, is it possible to play the Midroll ad everytime i seek to the Ad position. Say, in the above scenario after Midroll ad played once at 20th min and seek back to 19th minute .Now i want the midroll ad to play again at 20th minute. Is this possible ?

**Comment by andrewlewis** [comment]
Regarding the behavior when seeking, I'm afraid this isn't possible as the IMA SDK dictates the policy on what ad plays after seeking (#4005 is an open enhancement about allowing control over what ad plays on seeking with `AdsMediaSource` but won't help here unless the IMA SDK add the feature -- and I don't think they have any plans to add this functionality per https://groups.google.com/d/msg/ima-sdk/GT0Tsioklhc/3KW6-5TjAwAJ).

Regarding starting (or resuming) playback from a non-zero position, there is an option not to play the ad before the start position: e261b8d0ef8e0d35b3f4ec2d936ba08ce8a6d151
