### ISSUE TITLE
All frames dropped when playing some HLS streams

### ISSUE THREAD

**Issue by tai2** [google/ExoPlayer#778]
* Stream: http://tai2.net/misc/hls_test/stream_.m3u8
* ExoPlayer: r1.4.2

When I play this HLS stream on some devices, all frames are dropped and it displays only black surface. Below is the result of my investigation.

When playing on Nexus5(Android 5.1.1) there is no problem. It plays stream smoothly.
But when playing on TC97RA1(Android 4.4.4), it drop frames. Some other streams are played normally on this device tough.

In my speculation, the difference is some playable streams are ordered by PTS and other streams are reordered randomly by the encoder. When packets are not ordered by PTS, calculated timeUs by ptsToTimeUs() has negative value. I saw the resulted buffer info's positionUs retrieved by dequeueOutputBuffer() are same values and this cause frame dropping. I think negative timestamp might cause this result on some devices or OS versions.

Could you fix this problem or have any workarounds?

Thanks,

**Comment by ojw28** [comment]
Sounds more like a device specific issue with the TC97RA1 than an ExoPlayer problem, although it's quite hard to say.

**Comment by ojw28** [comment]
It's an interesting theory though. Why don't you test it by modifying MediaCodecTrackRenderer. Specifically, where presentationTimeUs is set, add a small value to it to ensure that it never goes negative for the test stream.

In other words, simply replace the line:

```
long presentationTimeUs = sampleHolder.timeUs;
```

With

```
long presentationTimeUs = sampleHolder.timeUs + 66733;
```

And then see if playback works. If it does, then we can investigate potential workarounds.

**Comment by tai2** [comment]
Yes, It works fine on the device when I add a offset value to timestamps before enqueueing.

**Comment by ojw28** [comment]
Thanks for the quick response! What happens if you use:

```
long presentationTimeUs = Math.max(0, sampleHolder.timeUs);
```

Does that also fix it, or does that cause issues?

**Comment by tai2** [comment]
It solved the problem!

**Comment by mkazuma29** [comment]
Excuse me for jumping into this issue, but is there side effect for the solution both of you mentioned?
long presentationTimeUs = Math.max(0, sampleHolder.timeUs);

If there is no side effect, that is enough.

**Comment by ojw28** [comment]
There are probably some negative implications of fixing it that way, yes. Some decoders may rely on the timestamps to some extent, for example to re-order the frames correctly before they're output. We'll have a think about how we can fix this "properly", or at least what the best workaround is.

**Comment by mkazuma29** [comment]
Thanks for your reply.  If you come up with good solution, please share us!!!!

**Comment by ppamorim** [comment]
:+1: The same here :(

**Comment by ppamorim** [comment]
@ojw28 It's better to use this:
```java
long presentationTimeUs = sampleHolder.timeUs + 66733;
```
Or this: 
```java
long presentationTimeUs = Math.max(0, sampleHolder.timeUs);
```

I think that the second one is more correct, but It don't do a different thing?

**Comment by ojw28** [comment]
Neither are a correct fix for the issue. We have a partial fix that should cover most cases, including the case in the stream linked at the top of this issue. We'll push the change soon. For any remaining cases, we'll need to think about it some more.

**Comment by ppamorim** [comment]
@ojw28 It's the most common problem reported on my app... Glad you!

**Comment by ojw28** [comment]
This is partially fixed on dev, by the change referenced above. Please confirm that it fixes the issue for you, at least for the test stream at the top of this issue.

**Comment by mkazuma29** [comment]
Thanks all. The fix above seems to be fine. We will try and report the result!!

**Comment by tai2** [comment]
I tried the dev head. The result is a bit unexpected.

Using the fixed version, the stream referenced at the top of this issue is played properly on TC97RA1. The problem we discussed seems fixed.

Then, I picked up some other streams from our real product which we cannot share publicly.
These streams cause 404 http error in TsChunk#load. This is not occurred on r1.4.2 because this is common result both TC97RA1 and Nexus5.Below is the summary.

r1.4.2

|       |Sample data|Real data |
|-------|-----------|----------|
|TC97RA1|Frame drop |Frame drop|
|Nexus5 |OK         |        OK|

dev

|       |Sample data|Real data|
|-------|-----------|---------|
|TC97RA1|         OK|      404|
|Nexus5 |         OK|      404|

Some other commits might result a regression.
But it seems different problem so we'll investigate it and report another issue.

**Comment by tai2** [comment]
posted a new issue. https://github.com/google/ExoPlayer/issues/788

**Comment by tai2** [comment]
Finally, all streams we tested are properly played by ExoPlayer as a result of server modification.
Thank you.

dev

|       |Sample data|Real data|
|-------|-----------|---------|
|TC97RA1|         OK|      OK|
|Nexus5 |         OK|      OK|
