### ISSUE TITLE
Dash Stream struck on infinite buffering state after PTS reset

### ISSUE THREAD

**Issue by SharanKumarReddyKambham** [google/ExoPlayer#7780]
###  Issue description
We configured a Dash stream from an encoder and feeding it to sample Exoplayer as a live stream while streaming if we restart the encoder, the stream freezes and is struck in buffer state, we observed the difference in Bufferpresentation time compared to the previous buffer presentation time. We've checked with the **replaceStream** by giving the difference of the buffer presentation time and positionUs as the stream offset,Here is the code snippet

```
if ((diff == 0l) && (pdiff > 1000000) && !isEnteredFirstCase) {
            diff = positionUs - bufferPresentationTimeUs;
            Log.d(TAG, "FIRST ENTRY_________diff:" + (diff) + " PDiff " + pdiff);
            outputStreamOffsetUs = C.TIME_UNSET;
            isEnteredFirstCase = true;
            replaceStream(getStreamFormats(), getStream(), diff);
        }
```

> 08-17 12:23:00.719  2222  2264 D MediaCodecVideoRenderer: diff                    :3379360000
> 08-17 12:23:00.719  2222  2264 D MediaCodecVideoRenderer: After earlyUs           :59000
> 08-17 12:23:00.720  2222  2264 D MediaCodecVideoRenderer: RETURN NOTHING--------
> 08-17 12:23:00.720  2222  2264 D MediaCodecRenderer: drainOutputBuffer: after 6496456000
> 08-17 12:23:00.721  3348  3348 E HWComposer: getLayerReleaseFence failed for display -1: Invalid display
> 08-17 12:23:00.721  3348  3348 E HWComposer: getLayerReleaseFence failed for display -1: Invalid display
> 08-17 12:23:00.729  2222  2264 D MediaCodecRenderer: drainOutputBuffer: before6496456000
> 08-17 12:23:00.729  2222  2264 D MediaCodecVideoRenderer: Before pos:6496407000 buf:6496456000 OffUs:3379360000 ptUs:3117096000 pdiff:49000 diff:3379360000
> 08-17 12:23:00.729  2222  2264 D MediaCodecVideoRenderer: getState():2
> 08-17 12:23:00.729  2222  2264 D MediaCodecVideoRenderer: Before earlyUs          :49000
> 08-17 12:23:00.729  2222  2264 D MediaCodecVideoRenderer: diff                    :3379360000
> 08-17 12:23:00.729  2222  2264 D MediaCodecVideoRenderer: After earlyUs           :49000
> 08-17 12:23:00.729  2222  2264 D MediaCodecRenderer: drainOutputBuffer: after 6496456000
> 08-17 12:23:00.730  2222  2264 D MediaCodecRenderer: drainOutputBuffer: before6496473000
> 08-17 12:23:00.730  2222  2264 D MediaCodecVideoRenderer: Before pos:6496407000 buf:6496473000 OffUs:3379360000 ptUs:3117113000 pdiff:66000 diff:3379360000
> 08-17 12:23:00.730  2222  2264 D MediaCodecVideoRenderer: getState():2
> 08-17 12:23:00.730  2222  2264 D MediaCodecVideoRenderer: Before earlyUs          :65000
> 08-17 12:23:00.730  2222  2264 D MediaCodecVideoRenderer: diff                    :3379360000
> 08-17 12:23:00.730  2222  2264 D MediaCodecVideoRenderer: After earlyUs           :65000
> 08-17 12:23:00.730  2222  2264 D MediaCodecVideoRenderer: RETURN NOTHING--------
> 08-17 12:23:00.730  2222  2264 D MediaCodecRenderer: drainOutputBuffer: after 6496473000
> 08-17 12:23:00.730  2222  2264 D ReadSource: readSource: 282000
> 08-17 12:23:00.739  3348  3348 E HWComposer: getLayerReleaseFence failed for display -1: Invalid display
> 08-17 12:23:00.739  3348  3348 E HWComposer: getLayerReleaseFence failed for display -1: Invalid display
> 08-17 12:23:00.740  2222  2264 D MediaCodecRenderer: drainOutputBuffer: before6496473000
> **_08-17 12:23:00.740  2222  2264 D MediaCodecVideoRenderer: Before pos:6496418000 buf:**6496473000** OffUs:3379360000 ptUs:3117113000 pdiff:55000 diff:3379360000_**
> 08-17 12:23:00.740  2222  2264 D MediaCodecVideoRenderer: getState():2
> 08-17 12:23:00.740  2222  2264 D MediaCodecVideoRenderer: Before earlyUs          :55000
> 08-17 12:23:00.740  2222  2264 D MediaCodecVideoRenderer: diff                    :3379360000
> 08-17 12:23:00.740  2222  2264 D MediaCodecVideoRenderer: After earlyUs           :55000
> 08-17 12:23:00.740  2222  2264 D MediaCodecRenderer: drainOutputBuffer: after 6496473000
> 08-17 12:23:00.741  2222  2264 D MediaCodecRenderer: drainOutputBuffer: before3379376000
> **_08-17 12:23:00.741  2222  2264 D MediaCodecVideoRenderer: Before pos:6496418000 buf:**3379376000** OffUs:3379360000 ptUs:16000 pdiff:3117042000 diff:3379360000_**

### Reproduction steps
Configure a route stream through the encoder and restart the encoder when streaming in exoplayer

###  A full bug report captured from the device
[routeissue6.txt](https://github.com/google/ExoPlayer/files/5090356/routeissue6.txt)

### Version of ExoPlayer being used
Used Exoplayer V.2.11.0

###  Device(s) and version(s) of Android being used
 NVIDIA SHIELD Android TV (Android 9) 
``

**Comment by marcbaechinger** [comment]
> stream from an encoder and feeding it to sample Exoplayer as a live stream
> [...] while streaming if we restart the encoder, the stream freezes and is struck in buffer state

What do you mean with 'restart the encoder'? Do you encode something on the fly and then when you restart the encoder ExoPlayer starts to buffer when trying to read from that stream?

When looking into the log file I can observe a few things:

```
08-17 13:04:49.096  2666  2666 I ExoPlayerImpl: Init 43b8ed2 [ExoPlayerLib/2.11.0] [darcy, SHIELD Android TV, NVIDIA, 28]
```
 The player is initialized and starts playback as expected. 

```
08-17 13:04:49.288  2666  2666 D EventLogger: timeline [eventTime=0.16, mediaPos=9005.00, window=0, periodCount=1, windowCount=1, reason=PREPARED
```
The first mediaPos that is reported is **mediaPos=9005.00**

```
08-17 13:06:40.683  2666  2666 D EventLogger: loading [eventTime=111.56, mediaPos=9116.13, window=0, period=0, true]
08-17 13:06:40.740  2666  2666 D EventLogger: loading [eventTime=111.61, mediaPos=9116.19, window=0, period=0, false]
08-17 13:06:41.175  2666  2666 D EventLogger: timeline [eventTime=112.05, mediaPos=9116.61, window=0, period=0, periodCount=1, windowCount=1, reason=DYNAMIC
08-17 13:06:41.175  2666  2666 D EventLogger:   period [?]
08-17 13:06:41.175  2666  2666 D EventLogger:   window [9148.17, true, true]
08-17 13:06:41.175  2666  2666 D EventLogger: ]
08-17 13:06:42.175  2666  2666 D EventLogger: timeline [eventTime=113.05, mediaPos=9117.62, window=0, period=0, periodCount=1, windowCount=1, reason=DYNAMIC
08-17 13:06:42.176  2666  2666 D EventLogger:   period [?]
08-17 13:06:42.176  2666  2666 D EventLogger:   window [9149.17, true, true]
08-17 13:06:42.176  2666  2666 D EventLogger: ]
08-17 13:06:42.680  2666  2666 D EventLogger: loading [eventTime=113.55, mediaPos=9118.13, window=0, period=0, true]
08-17 13:06:42.740  2666  2666 D EventLogger: loading [eventTime=113.61, mediaPos=9118.19, window=0, period=0, false]
08-17 13:06:43.176  2666  2666 D EventLogger: timeline [eventTime=114.05, mediaPos=9118.62, window=0, period=0, periodCount=1, windowCount=1, reason=DYNAMIC
08-17 13:06:43.176  2666  2666 D EventLogger:   period [?]
08-17 13:06:43.176  2666  2666 D EventLogger:   window [9150.17, true, true]
08-17 13:06:43.176  2666  2666 D EventLogger: ]
```

After initializing the player it plays fine. Manifests are refreshed every second and the **media position advances until 9118.62.**

Now comes the buffering which never goes away again (while the manifest still refreshes every second afterwards):

```
state [eventTime=114.70, mediaPos=9119.27, window=0, period=0, true, BUFFERING]
08-17 13:06:43.828  2666  2666 D EventLogger: isPlaying [eventTime=114.70, mediaPos=9119.27, window=0, period=0, false]
08-17 13:06:43.828  2666  2666 D EventLogger: state [eventTime=114.70, mediaPos=9119.27, window=0, period=0, true, READY]
08-17 13:06:43.829  2666  2666 D EventLogger: isPlaying [eventTime=114.70, mediaPos=9119.27, window=0, period=0, true]
08-17 13:06:43.845  2666  2666 D EventLogger: droppedFrames [eventTime=114.72, mediaPos=9119.28, window=0, period=0, 8]
08-17 13:06:43.846  2666  2666 D EventLogger: state [eventTime=114.72, mediaPos=9119.29, window=0, period=0, true, BUFFERING]
08-17 13:06:43.847  2666  2666 D EventLogger: isPlaying [eventTime=114.72, mediaPos=9119.29, window=0, period=0, false]
08-17 13:06:43.848  2666  2666 D EventLogger: state [eventTime=114.72, mediaPos=9119.29, window=0, period=0, true, READY]
08-17 13:06:43.849  2666  2666 D EventLogger: isPlaying [eventTime=114.72, mediaPos=9119.29, window=0, period=0, true]
08-17 13:06:43.862  2666  2666 D EventLogger: droppedFrames [eventTime=114.74, mediaPos=9119.29, window=0, period=0, 3]
08-17 13:06:43.862  2666  2666 D EventLogger: state [eventTime=114.74, mediaPos=9119.29, window=0, period=0, true, BUFFERING]
08-17 13:06:43.864  2666  2666 D EventLogger: isPlaying [eventTime=114.74, mediaPos=9119.29, window=0, period=0, false]
```

If this is caused as you say by `restarting the encoder` which delivers the file behind that ip address the I would expect it's a problem caused by restarting the encoder. 

```
08-17 13:05:08.598  2666  2718 D DefaultHttpDataSource: open: http://192.168.3.100/service/v1-4510.mp4v
```

Did you encounter such a problem without restarting the encoder or does this happen only when restarting?

**Comment by SharanKumarReddyKambham** [comment]
The encoder which is serving the stream is restarted on the fly which makes the stream struck in buffering state, this problem occurred only after restarting the encoder.

**Comment by marcbaechinger** [comment]
Ok. The calculation you are doing with your code inside the renderer does unveil some inconsistencies with the timestamps, if I understand you correctly. You also say it only happens when you restart the encoder. If that restart would be transparent in a sense that the file which is delivered looks just the same as without a restart everything would work fine I suspect. To what extend do you expect that this is a problem with ExoPlayer rather than with the encoder? 

(I can not access the stream so I can not really investigate what is going on besides looking into your log files)

**Comment by SharanKumarReddyKambham** [comment]
But is there any way to handle bufferpresentationtimeUs when it is not monotonically increased ?? Here in the case of encoder restart the bufferpts is resetting to 0.While in other players like vlc this case been handled and the stream continues to play.In Exoplayer the stream strucks in a buffering state.

**Comment by ojw28** [comment]
Within a period, sample timestamps must be monotonically increasing. If your encoder needs to restart in a way that violates this requirement, the only specification compliant thing you can do is to end the current `Period` in the DASH manifest, and start a new one. You can read more about the DASH timing model [here](https://dashif-documents.azurewebsites.net/Guidelines-TimingModel/master/Guidelines-TimingModel.html).

Note in particular the following clause. Resetting the media presentation timestamps to 0 due to an encoder reset is basically the same case as timestamp wrap-around, except that the point where the reset occurs might be a bit different. It needs to be handled in the same way:

> A sample timeline is linear - encoders are expected to use an appropriate timescale and sufficiently large timestamp fields to avoid any wrap-around. If wrap-around does occur, a new period must be started in order to establish a new sample timeline.
