### ISSUE TITLE
Where to call Util.startForegroundService in PlayerActivity?

### ISSUE THREAD

**Issue by tosam144** [google/ExoPlayer#7781]
Like in the exoplayer demo app (https://github.com/google/ExoPlayer), I have a PlayerActivity that plays mp3s. Now I want to start a foreground service so that the mp3 continues to play even though PlayerActivity is in the background (or even killed). I am aware of `Util.startForegroundService` but my 2 questions are:

1) Where in the code should I call this? In `onCreate` or in `onStart` of PlayerActivity?
2) Which Intent do I pass into `Util.startForegroundService`? The one retrieved by `getIntent()` in PlayerActivity?

**Comment by marcbaechinger** [comment]
The intent you pass to `Util.startForegroundService(context, intent)` is the `Intent` which declares what service to start. It is passed to [`Context.startForegroundService()`](https://developer.android.com/reference/android/content/Context#startForegroundService(android.content.Intent)) or `Context.startService` according to the API level. Both methods define the intent as follows: _Intent: Identifies the service to be started. The Intent must be fully explicit (supplying a component name). Additional values may be included in the Intent extras to supply arguments along with this specific start call._

So actually the [intent to start a service](https://developer.android.com/guide/components/services) looks like this in it's simplest form:

```
Util.startForegroundService(context, new Intent(this, HelloService.class));
```

You would call this whenever the user wants to start listening to audio and the service is not yet started. I would not call this in a life-cycle method necessarily. I would expect the activity has a UI with either a play button or a list of media items or the like. The when the user chooses to play something and the service  has not yet been started, you can fire the intent and include some extras with which you tell the service what to play.

**Comment by tosam144** [comment]
Thanks for the reply. So in my case, once the user clicks on the mp3, the PlayActivity is launched:

```
Intent intent = new Intent(mContext, PlayerActivity.class);
Bundle bundle = new Bundle();
bundle.putParcelable(Constants.EXTRA_MEDIA_DATA, mMetaData);
bundle.putInt(Constants.EXTRA_AUDIO_TYPE, mAudioType);
intent.putExtras(bundle);
mContext.startActivity(intent);
```

Now in my PlayerActivity, I set up the player in an `initializePlayer` method:

```
player = new SimpleExoPlayer.Builder(this).build();
...
player.setPlayWhenReady(true);
player.prepare(mMediaSource, !haveStartPosition, false);
```
The onStart looks like this:

```
@Override
public void onStart() {
        super.onStart();
        //bindService(mServiceIntent, mConnection, Context.BIND_AUTO_CREATE);
        if (Util.SDK_INT > 23) {
            initializePlayer();
            if (playerView != null) {
                playerView.onResume();
            }
        }
}
```

All of this works fine and the PlayerActivity opens with the standard buttons play, stop, pause etc. It works great. But once the user puts PlayerActivity in the background, the mp3 stops playing. Therefore, I want to make it a foreground service. Would it be the correct approach to call these lines in the activity's `initializePlayer` which is called in `onStart`?

```
mServiceIntent = new Intent(this, AudioPlayerService.class);
Bundle bundle = new Bundle();
bundle.putParcelable(Constants.EXTRA_MEDIA_DATA, mMediaMetaData);
bundle.putInt(Constants.EXTRA_AUDIO_TYPE, audioType);
mServiceIntent.putExtras(bundle);
Util.startForegroundService(this, mServiceIntent);
```
Is the correct?

**Comment by marcbaechinger** [comment]
So you first create the activity where you create the intent with the metadata pointing to `AudioPlayerService`. You pass that intent to `Util.startForegroundService` which starts your service and you can receive the intent there. In the service you will need then to create the player instance and prepare it with the media source according to the metadata. Everything that needs to survive the destruction of the activity needs to be in the service. That's probably at least the player instance, the `PlayerNotificationManager` and the `MediaSessionConnector`. 

Once the service is started you can pass the player instance back to the activity, so you can set it to `playerView.setPlayer(player)`. There are various ways how you can send the player back from the service to the activity. Like by using a `ResultReceiver` or by broadcasting an intent from the service to the activity.

When the activity is going to be destroyed you need to detach the `PlayerView` from the player, so that the player is referenced from the service only.

**Comment by tosam144** [comment]
Thank you @marcbaechinger, that really helped. I have one more question here: Now I am calling `Util.startForegroundService` in the `onCreate` method of my PlayerActivity (as suggested by you). That works well. However, sometimes the user presses the back button. As a result, PlayerActivity gets destroyed and the player is detached from the PlayerView (which is correct). However, the foreground service is still running (which is also correct). Now when the user touches the notification, the PlayerActivity is re-created and thus `Util.startForegroundService` is called again. The result is that the player is reset and the currently running mp3 jumps back to the start (`player.getCurrentPosition()` returns 0). However, I want the mp3 to continue once PlayerActivity has been brought back (via notification). How do I do this? Do I have to check in `onCreate` whether the service is running and only then call `Util.startForegroundService`? If yes, how do I do this?

**Comment by marcbaechinger** [comment]
You are right, when the service is already running you want just get the player from the service and not start the service again. 

Simplest would probably be that the service has a static field `AudioPlayerService.player` to which the player is assigned once created and set to `null` when the service is destroyed again. You can then simply check in your activity's `onCreate` whether the field is not `null`. If not `null` you have the player, if it is `null` you need to start the service first and wait for a callback to check the static field again.

**Comment by tosam144** [comment]
Thank you @marcbaechinger, that worked perfectly. You may close the issue.
