### ISSUE TITLE
Determine required disk space size before downloading

### ISSUE THREAD

**Issue by Subuday** [google/ExoPlayer#7787]
### [REQUIRED] Searched documentation and issues
https://stackoverflow.com/questions/58324072/detect-required-disk-space-for-exoplayer-offline-download
https://exoplayer.dev/downloading-media.html
https://github.com/google/ExoPlayer/blob/release-v2/demos/main/src/main/java/com/google/android/exoplayer2/demo/DownloadTracker.java

### [REQUIRED] Question
I use HLS protocol and I need to determine the size of the video with the selected resolution, subtitles and audio tracks. Unfortunely, I haven't found any examples in demo-app.  I could define only the size of the video track by multiplying the bitrate of the selected track. But the size of multiple audio tracks and subtitles is not included in this number. 

### Link to test content
I use Download Tracker and  other classes provided by this example.
https://github.com/google/ExoPlayer/blob/release-v2/demos/main/src/main/java/com/google/android/exoplayer2/demo/DownloadTracker.java

**Comment by marcbaechinger** [comment]
This is discussed in detail in #6347 . I'm closing this as a duplicate.
