### ISSUE TITLE
MKV: Video Track not displayed

### ISSUE THREAD

**Issue by ened** [google/ExoPlayer#779]
Given I have the following MKV file:
```
$ ffmpeg -i sample-mkv.mkv 
ffmpeg version 2.7.2 Copyright (c) 2000-2015 the FFmpeg developers
  built with Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/2.7.2_1 --enable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-opencl --enable-libx264 --enable-libmp3lame --enable-libvo-aacenc --enable-libxvid --enable-libfreetype --enable-libtheora --enable-libvorbis --enable-libvpx --enable-librtmp --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libass --enable-ffplay --enable-libspeex --enable-libschroedinger --enable-libfdk-aac --enable-libopus --enable-frei0r --enable-libopenjpeg --disable-decoder=jpeg2000 --extra-cflags='-I/usr/local/Cellar/openjpeg/1.5.2_1/include/openjpeg-1.5 ' --enable-nonfree --enable-vda
  libavutil      54. 27.100 / 54. 27.100
  libavcodec     56. 41.100 / 56. 41.100
  libavformat    56. 36.100 / 56. 36.100
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 16.101 /  5. 16.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.100 /  1.  2.100
  libpostproc    53.  3.100 / 53.  3.100
Input #0, matroska,webm, from 'sample-mkv.mkv':
  Metadata:
    encoder         : libebml v0.7.7 + libmatroska v0.8.1
    creation_time   : 2009-09-30 10:39:36
  Duration: 00:57:49.94, start: 0.000000, bitrate: 999 kb/s
    Stream #0:0: Video: mpeg4 (Simple Profile) (DX50 / 0x30355844), yuv420p, 704x396 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 1k tbn, 25 tbc (default)
    Stream #0:1: Audio: aac (HE-AAC), 44100 Hz, stereo, fltp (default)
```

And ExoPlayer instantiated like this:
```
final ExtractorSampleSource sampleSource = new ExtractorSampleSource(uri,
        new DefaultUriDataSource(this, "AUDI/RSEIII"), new DefaultAllocator(65534), 10485760);

final TrackRenderer videoRenderer = new MediaCodecVideoTrackRenderer(sampleSource, MediaCodec.VIDEO_SCALING_MODE_SCALE_TO_FIT);
final TrackRenderer audioRenderer = new MediaCodecAudioTrackRenderer(sampleSource);

exoPlayer = ExoPlayer.Factory.newInstance(numRenderers);

exoPlayer.addListener(new ExoPlayer.Listener() {
    @Override
    public void onPlayerStateChanged(final boolean playWhenReady, final int playbackState) {
        Log.d(TAG, "state: "+ playbackState);
        if (playbackState == ExoPlayer.STATE_READY) {
            for (int i = 0; i < sampleSource.getTrackCount(); i++) {
                addTrackInfo(sampleSource.getFormat(i));
            }
        }
    }

    @Override
    public void onPlayWhenReadyCommitted() {
    }

    @Override
    public void onPlayerError(final ExoPlaybackException e) {
        addErrors("Error in ExoPlayer", e);
    }
});
exoPlayer.sendMessage(videoRenderer, MediaCodecVideoTrackRenderer.MSG_SET_SURFACE, new Surface(surface));
exoPlayer.prepare(videoRenderer, audioRenderer);
exoPlayer.setPlayWhenReady(true);
```

Produces a black screen and only the audio track will be played.

Based on e13e23e3e030b49d3e1dac17ba93ef4bcf837a71.

Sample file will be send by eMail (>400MB).

(PS: No problems playing some other MP4 files and also no issues playing this MKV using MediaPlayer).

**Comment by ojw28** [comment]
Are you certain this plays with video using Android's MediaPlayer? On Nexus devices. It's possible that some OEM devices support additional formats, but I don't think the video track in this file is officially supported by Android.

If you can play on a Nexus device, which one (and what OS version)? Thanks!

**Comment by vigneshvg** [comment]
Just to double check if the video codec is supported, could you please also
post the output of "mkvinfo sample-mkv.mkv" here? You can get mkvinfo as
part of mkvtoolnix [1].

[1] https://www.bunkus.org/videotools/mkvtoolnix/downloads.html

On Thu, Sep 10, 2015 at 7:50 AM, ojw28 <notifications@github.com> wrote:

> Are you certain this plays with video using Android's MediaPlayer? On
> Nexus devices. It's possible that some OEM devices support additional
> formats, but I don't think the video track in this file is officially
> supported by Android.
>
> If you can play on a Nexus device, which one (and what OS version)? Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/ExoPlayer/issues/779#issuecomment-139269989>.
>



-- 
Vignesh

**Comment by ened** [comment]
mkvinfo output:

```
+ EBML head
|+ Doc type: matroska
|+ Doc type version: 2
|+ Doc type read version: 2
+ Segment, size 433354831
|+ Seek head (subentries will be skipped)
|+ EbmlVoid (size: 4027)
|+ Segment information
| + Timecode scale: 1000000
| + Muxing application: libebml v0.7.7 + libmatroska v0.8.1
| + Writing application: mkvmerge v2.9.8 ('C'est le bon') built on Aug 13 2009 12:49:06
| + Duration: 3469.943s (00:57:49.943)
| + Date: Wed Sep 30 10:39:36 2009 UTC
| + Segment UID: 0x8d 0x41 0x7d 0xc5 0x1e 0xd7 0xfa 0xc8 0x80 0xf9 0x9e 0x33 0x20 0x8b 0x66 0x6f
|+ Segment tracks
| + A track
|  + Track number: 1 (track ID for mkvmerge & mkvextract: 0)
|  + Track UID: 974589112
|  + Track type: video
|  + Enabled: 1
|  + Default flag: 1
|  + Forced flag: 0
|  + Lacing flag: 0
|  + MinCache: 1
|  + Timecode scale: 1
|  + Max BlockAddition ID: 0
|  + Codec ID: V_MS/VFW/FOURCC
|  + Codec decode all: 1
|  + CodecPrivate, length 40 (FourCC: 0x44583530 »DX50«: MPEG-4p2)
|  + Default duration: 40.000ms (25.000 frames/fields per second for a video track)
|  + Language: und
|  + Video track
|   + Pixel width: 704
|   + Pixel height: 396
|   + Interlaced: 0
|   + Display width: 704
|   + Display height: 396
| + A track
|  + Track number: 2 (track ID for mkvmerge & mkvextract: 1)
|  + Track UID: 1892816006
|  + Track type: audio
|  + Enabled: 1
|  + Default flag: 1
|  + Forced flag: 0
|  + Lacing flag: 1
|  + MinCache: 0
|  + Timecode scale: 1
|  + Max BlockAddition ID: 0
|  + Codec ID: A_AAC
|  + Codec decode all: 1
|  + CodecPrivate, length 5
|  + Default duration: 46.440ms (21.533 frames/fields per second for a video track)
|  + Language: und
|  + Audio track
|   + Sampling frequency: 22050
|   + Channels: 2
|   + Output sampling frequency: 44100
|+ EbmlVoid (size: 1024)
|+ Cluster
```

**Comment by ened** [comment]
For my understanding - ExoPlayer should parse meta data and track infos and then pass the raw media data to the underlying system (OMX), right? Or is part of the meta data retrieved via the system methods? 

I'm not sure if standard Android can handle this particular codec (or another file format like MOV even, for that matter), yet a chip vendor can choose to implement it and provide playback support for it. Question is what is needed to make ExoPlayer play it successfully.

**Comment by ojw28** [comment]
They could do yes, but without standard Android support it would be unclear, for example, in what form the decoder initialization data should be provided. It's also unclear whether or not there's a significant use case if the majority of Android devices wont support the format?

The standard Android MediaPlayer implementation does not appear to support this type of video track, regardless of whether there's an underlying decoder. So an OEM would have to provide both the decoder and a modified MediaPlayer implementation for playback to succeed using the MediaPlayer API.

On what device(s) are you able to play this file successfully using MediaPlayer? We can consider doing as you suggest and make it work where an underlying decoder is provided, (a) we can test it, and (b) the custom decoder takes decoder initialization data in a sensible way.

Thanks!

**Comment by ojw28** [comment]
Closing due to lack of requested info.
