### ISSUE TITLE
Have Both LeastRecentlyUsedCacheEvictor for Playback cache and NoOpCacheEvictor for downloads

### ISSUE THREAD

**Issue by suchoX** [google/ExoPlayer#7796]
So I am working on an Audio Streaming app which allows the audio to be downloaded as well. Everything is going perfectly fine with NoOpCacheEvictor. But Cache size is increasing astronomically. I decided to use LeastRecentlyUsedCacheEvictor which will work with Cache size but will also probably remove downloaded audios as well.

Is there any way I can use both which will clear Cache automatically but make sure that downloaded audios are not deleted?
The document mentions to have a separate solution when using NoOpCacheEvictor. Is giving an option to Clear Cache the only way? If it is how do I make sure when I clear cache manually, Downloaded data is not cleared as well.
I have looked for this solution everywhere on documentation, github and Stackoverflow

**Comment by AquilesCanta** [comment]
I'm not clear about the whole problem but is it an option for you to use two different caches: One for playback caching and one for downloading? The former uses LRU CacheEvictor, and the latter uses NoOpCacheEvictor.

If you want to use a single cache, you can implement your own evictor which does whatever you specifically want, like LRU for video streams, and no eviction for audio streams.

Can you provide a bit more context so I can understand why neither of the options above work?

**Comment by suchoX** [comment]
@AquilesCanta I think I solved It. I Never thought you can have different DataSource for different Media on the same Concatenating Media Source. I created two caches and two datasource using the two caches and based on download status I am adding the respective Datasource. Closing This issue.
