### ISSUE TITLE
license_start_time = 0 in Widevine modular DRM

### ISSUE THREAD

**Issue by randeeppr** [google/ExoPlayer#780]
Hi,

When we play any video Live/VOD encrypted in Widevine modular DRM, On the proxy the license_start_time is coming as "0". So the drm is not working and the client is getting unlimited license time to watch the programs. 

We had contacted Google and they replied the following.
exoplayer can set the request_time in the license_request.

How can we do this? Is this a bug?

Regards,
Randeep

**Comment by ojw28** [comment]
I don't understand this. I'll follow up with Widevine.

**Comment by randeeppr** [comment]
Hi,

Widevine has a proxy server. Whenever a video is played, the license request will come to this proxy server. Proxy will get the license from google's cloud server and forward to client.

So the proxy, take the playback request and gives the license to client. There is a parameter license_start_time. Its always coming zero if I play videos from exoplayer. If I play video with their hosted shaka player, timestamp is printing for license_start_time. 

I had created a support ticket for widevine. ticket number is #[8-5827000007942] Exoplayer. You can mention it. 

Regards,
Randeep

**Comment by ojw28** [comment]
Apparently this is a server side issue. Widevine have a fix that has been pushed to some of their proxy instances, but not to the one that you're hitting.

Please follow up with Widevine on the support ticket you created. They should be able to give you an ETA for the fix being pushed, and advise as to whether there's a different proxy that you can use in the meantime that already has the fix (I've no idea whether there is or not!). For reference, you can mention that there's an internal bug tracking the issue. The id is 23525547.

Hope that helps!
