### ISSUE TITLE
Add  latest version to README 

### ISSUE THREAD

**Issue by MahmoudMabrok** [google/ExoPlayer#7801]

**Comment by AquilesCanta** [comment]
Handing over to @ojw28 for context on this.

**Comment by ojw28** [comment]
@marcbaechinger - Looks like this is possible by putting https://img.shields.io/github/v/release/google/ExoPlayer.svg?label=latest somewhere in the page.

**Comment by marcbaechinger** [comment]
Done. This will show up in the release branch with the next release and in the dev-v2 branch with the next sync.
