### ISSUE TITLE
Change theme or UI element of TrackSelectionDialogBuilder

### ISSUE THREAD

**Issue by yoobi** [google/ExoPlayer#7803]
### [REQUIRED] Searched documentation and issues
Stackoverflow and issues in this repo

### [REQUIRED] Question
I'd like to know if it's possible to change the theme of TrackSelectionDialogBuilder, because I can't find any method to do so.

How can I set a theme for my trackSelectionDialogBuilder?

Thanks

**Comment by AquilesCanta** [comment]
@tonihei, mind answering this?

**Comment by yoobi** [comment]
I've already made a PR, https://github.com/google/ExoPlayer/pull/7804

**Comment by tonihei** [comment]
Thanks, just reviewed it :)

**Comment by tonihei** [comment]
PR got merged, so I'll close this issue.
