### ISSUE TITLE
Exoplayer playback fails after acquiring keys from license server

### ISSUE THREAD

**Issue by mkcdot** [google/ExoPlayer#7805]
### Question
I am using a third party drm (other than widevine, playready, FPS or clearkey).
When I play the dash content (encrypted with CENC for this drm) on exoplayer, content plays for 5-6 seconds. It acquires the license and keys are loaded. But playback fails after that with some decryption error: 
`Caused by: android.media.MediaCodec$CryptoException: Decryption Error`.

### A full bug report captured from the device
Full log of this content playback:
[log.txt](https://github.com/google/ExoPlayer/files/5129527/log.txt)

### Link to test content
[encdash.zip](https://github.com/google/ExoPlayer/files/5129568/encdash.zip)
Video file is greater than 10 MB.

**Comment by AquilesCanta** [comment]
I think you should contact the Content Decryption Module owner to assist on this, considering this is a decryption error raised by the CDM. There's no way for us to diagnose this. Is there any evidence pointing at this being an ExoPlayer issue?

The reason it plays for a few seconds might be related to the fact that most media streams have a leading group of clear samples, after which content is encrypted. In general, one way for us to deal with decryption errors is contacting the widevine team but in this case this is not an option. 

Please let me konw if you think there is anything actionable on our side, or you have evidence showing this is an ExoPlayer issue (and not a CDM issue).

**Comment by mkcdot** [comment]
I also suspected the same, but was not sure. I will focus on CDM-side.
It will be helpful for me if I get more information on this error, like what can be the reasons for exoplayer to give this error. Is it due to improper decryption or improper content itself or exoplayer/media DRM server is unable to interact with CDM for decryption? Can I get more information from exoplayer regarding this error to narrow-down the possibilities?

**Comment by AquilesCanta** [comment]
The CDM is a black box to the player. Debugging any type of DRM issues is, more often than not, complex. ExoPlayer itself does not provide any tools, but you might be able to get some information from [Android MediaDrm](https://developer.android.com/reference/android/media/MediaDrm)'s callbacks. The best tool you have is pretty much in-app debugging and discarding options as you go. For example,
- Does your stream play on any other platform? This will rule out that the stream is malformed.
- Are you able to play any type of stream that uses this third-party protection scheme? This will rule out that the CDM integration is not working properly.

I don't think there are many routes other than in-app debugging and contacting the CDM provider to help you with the issue. Hope this helps, and please don't hesitate to reach out to us if you have evidence pointing at this being an ExoPlayer issue.

**Comment by mkcdot** [comment]
Thanks for the suggestions. I will look into that.
