### ISSUE TITLE
playbackLooper is null in @NonNullApi package

### ISSUE THREAD

**Issue by Turalllb** [google/ExoPlayer#7807]
![Снимок экрана 2020-08-26 в 21 11 55](https://user-images.githubusercontent.com/28982210/91342200-594c8180-e7e3-11ea-9892-e5c00905d12f.png)                                                                   https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/package-info.java
  Release 2.10.+ has no bug, release 2.11.7 has a bug.     Play steps: at the moment of closing the player, pass to the main thread loop:  exoplayer.playbackLooper 
![Снимок экрана 2020-08-26 в 21 36 00](https://user-images.githubusercontent.com/28982210/91343389-286d4c00-e7e5-11ea-8be2-ca23fc8758e0.png)                                                                                                                                         
 private val uiContext = Handler(Looper.getMainLooper())

**Comment by AquilesCanta** [comment]
It seems like `getPlaybackLooper()` should be marked as Nullable. Is that the issue? If not, please clarify.

EDIT: We are not marking it as nullable but instead saving the playback looper reference which we always return. This should also address your usecase.
