### ISSUE TITLE
AudioTrack Underrun optimization

### ISSUE THREAD

**Issue by changxiangzhong** [google/ExoPlayer#7808]
### [REQUIRED] Searched documentation and issues
ExoPlayer source code
MediaCodec API

### [REQUIRED] Question
We are trying to deploy our product on some low end devices (yes, really low). And we've been hit by *audio jank* issue. When it happens we could find one warning log like the following.
```
08-26 15:54:12.048 19143 19326 W AudioTrack: releaseBuffer() track 0x818b5500 disabled due to previous underrun, restarting
```
And We've checked the thread nice value of that process. Threads related to AV processing are listed as following
```
canal_sat_bcm:/ # ps -T `pidof com.canaldigital.ngp` -O NI                                          
USER           PID   TID  PPID     VSZ    RSS WCHAN            ADDR S  NI CMD  
system       29171 29171  2967 1465212 213680 SyS_epoll+          0 S -10 analdigital.ngp # our main app
system       29171 29268  2967 1465212 213680 SyS_epoll+          0 S -10 RenderThread
system       29171 29866  2967 1465212 213680 binder_th+          0 S -16 ExoPlayerImplIn
system       29171 29870  2967 1465212 213680 SyS_epoll+          0 S -16 DrmRequestHandl
system       29171 29879  2967 1465212 213680 futex_wai+          0 S -10 MediaCodec_loop
system       29171 29880  2967 1465212 213680 futex_wai+          0 S -16 CodecLooper
system       29171 29900  2967 1465212 213680 futex_wai+          0 S -10 MediaCodec_loop
system       29171 29904  2967 1465212 213680 futex_wai+          0 S -16 AudioTrack
```

So we are trying to tweak the following options. 
- Increase the priority to -20 for ExoPlayerImplInternal::Handler thread
- Decrease the interval of `ExoPlayerImplInternal::doSomeWork()` to 0ms, like the following 
```java  
private void doSomeWork() {
    //...
    if (!queue.hasPlayingPeriod()) {
      //...
      scheduleNextWork(operationStartTimeMs, 0);
      //...
    }
}
```

So do you have any suggestion? Do you see any side effects?

Thanks a lot

**Comment by fmatosqg** [comment]
Hi @changxiangzhong I don't think I can help you but maybe you can help me. Can you describe how your audio jank sounds like?  

I get some feedback from users with live audio streams that may indirectly be related to this, do you know how I can reproduce this issue, is there a specific audio file (preferrably live, and audio only) / phone model combination you can share?

**Comment by changxiangzhong** [comment]
@fmatosqg 

The root cause (my understanding) of this issue is the execution block/method execution of `ExoPlayerImplInternal::doSomeWork()` scheduled on thread **ExoPlayerImplInternal:Handler** is not fast enough. It calls `MediaCodec.releaseOutputBuffer()` too late. Essentially, we are feeding the **sound card** too late/slow.

The *audio jank* issue sounds like a very short halt/gap within the sound stream. It's extreme short period, but not difficult to recognize.

Are you playing with audio only stream? That should be very light task comparing to Video processing.

**Comment by AquilesCanta** [comment]
Assigning @christosts who is working on renderer pipeline optimizations.

**Comment by andrewlewis** [comment]
It may be worth trying increasing the `AudioTrack` buffer size (calculated in `DefaultAudioSink` around [here](https://github.com/google/ExoPlayer/blob/ad1dffc/library/core/src/main/java/com/google/android/exoplayer2/audio/DefaultAudioSink.java#L1365), based on some [constants](https://github.com/google/ExoPlayer/blob/ad1dffc/library/core/src/main/java/com/google/android/exoplayer2/audio/DefaultAudioSink.java#L178)).

**Comment by changxiangzhong** [comment]
@andrewlewis Thank you so much for your instruction, that's really helpful. On a smoke test, we found that the smoothness of the playback gets improved **substantially** by 10X the default `AudioTrack::bufferSize`. Our use case is bit special - we are rendering the semi-transparent activity_layout on top of a Surface for playback purpose. So yeah, we have crappy devices and resource intensive requirement. We are conducting more tests trying to find any potential side effects.

**Comment by christosts** [comment]
If you are using the dev-v2 branch, can you try to enable the experimental mediaCodecOperationMode? 

If you are not passing your own renderers factory, then you need to instantiate a `DefaultRenderersFactory`, set [experimentalSetAudioMediaCodecOperationMode](https://github.com/google/ExoPlayer/blob/61abe5951a421d563de034c3d14f1392b4303164/library/core/src/main/java/com/google/android/exoplayer2/DefaultRenderersFactory.java#L162) and [experimentalSetVideoMediaCodecOperationMode](https://github.com/google/ExoPlayer/blob/61abe5951a421d563de034c3d14f1392b4303164/library/core/src/main/java/com/google/android/exoplayer2/DefaultRenderersFactory.java#L177) to [MediaCodecRenderer.OPERATION_MODE_ASYNCHRONOUS_DEDICATED_THREAD_ASYNCHRONOUS_QUEUEING](https://github.com/google/ExoPlayer/blob/61abe5951a421d563de034c3d14f1392b4303164/library/core/src/main/java/com/google/android/exoplayer2/mediacodec/MediaCodecRenderer.java) and pass the `DefaultRenderersFactory` to ExoPlayer's builder.

If you are using your own custom renderers factory, then you need to set these modes on the `MediaCodecVideoRenderer` and `MediaCodecAudioRenderer` instances directly.

These modes will be available soon as part of v2.12 (but still experimental).

**Comment by changxiangzhong** [comment]
@christosts Thanks for your reply. What you are asking is non-trivial for me. Currently we are using a quite old version. Then we need to migrate to the latest one first. I'll see what I can do.

**Comment by changxiangzhong** [comment]
@christosts It takes some effort to migrate to dev-v2, but I've achieved it. Regarding the option `OPERATION_MODE_ASYNCHRONOUS_DEDICATED_THREAD_ASYNCHRONOUS_QUEUEING`, here is my test case. The following screen shots indicates, we have a seek bar on top of the SurfaceView, on which video was rendered. The seek bar is **NOT** hooked with anything. 
![20200908_212054_HDR](https://user-images.githubusercontent.com/5352145/92519173-d03d3d80-f219-11ea-8bee-473571b0bc21.jpg)

My test case is very simple move the seekbar from leftmost to rightmost while playing 50FPS 720p smooth streaming content. And count how many *underrun* events have happened


The following results are with the **options off**
```
2020-09-08 21:52:44.150 26460-26513/com.cxz.walkman W/AudioTrack: releaseBuffer() track 0xa2e15c00 disabled due to previous underrun, restarting
2020-09-08 21:52:46.224 26460-26513/com.cxz.walkman W/AudioTrack: releaseBuffer() track 0xa2e15c00 disabled due to previous underrun, restarting
2020-09-08 21:52:47.319 26460-26513/com.cxz.walkman W/AudioTrack: releaseBuffer() track 0xa2e15c00 disabled due to previous underrun, restarting
2020-09-08 21:52:48.139 26460-26513/com.cxz.walkman W/AudioTrack: releaseBuffer() track 0xa2e15c00 disabled due to previous underrun, restarting
2020-09-08 21:52:53.511 26460-26513/com.cxz.walkman W/AudioTrack: releaseBuffer() track 0xa2e15c00 disabled due to previous underrun, restarting
2020-09-08 21:52:54.936 26460-26513/com.cxz.walkman W/AudioTrack: releaseBuffer() track 0xa2e15c00 disabled due to previous underrun, restarting
2020-09-08 21:52:57.650 26460-26513/com.cxz.walkman W/AudioTrack: releaseBuffer() track 0xa2e15c00 disabled due to previous underrun, restarting
2020-09-08 21:53:00.646 26460-26513/com.cxz.walkman W/AudioTrack: releaseBuffer() track 0xa2e15c00 disabled due to previous underrun, restarting
```
The following results are with the **options on**
```
2020-09-08 21:40:17.291 25968-25998/com.cxz.walkman W/AudioTrack: releaseBuffer() track 0xa2e21c00 disabled due to previous underrun, restarting
2020-09-08 21:40:17.479 25968-25998/com.cxz.walkman W/AudioTrack: releaseBuffer() track 0xa2e21c00 disabled due to previous underrun, restarting
2020-09-08 21:40:20.095 25968-25998/com.cxz.walkman W/AudioTrack: releaseBuffer() track 0xa2e21c00 disabled due to previous underrun, restarting
```
Conclusions: I've run the same test a few times, the result seems consistent. It relieve the *underrun* symptom to some degree. Just let me know if you want to test more stuff.

One caveat is the experiment option seems very unstable, it causes exception/frozen a few times

**Comment by christosts** [comment]
Good to see some improvement is made, but unfortunately not good enough. 

Another idea to experiment: Depending on which ExoPlayer version your app is using, you may have access to [experimental_setRenderTimeLimitMs](https://github.com/google/ExoPlayer/blob/r2.10.0/library/core/src/main/java/com/google/android/exoplayer2/mediacodec/MediaCodecRenderer.java#L403) which was available from v2.10 until v2.11.8. This feature limits how much real time `doSomeWork` spends interacting with the audio and video MediaCodec instances. We experimented with values between 15ms to 40ms, but we did not get conclusive data to enable this by default for all devices. You may get promising results on the specific low end devices you are using. Consider setting a rendering limit only on video (MediaCodecVideoRenderer). Possible side effects might be increased dropped frames. Please note that we have removed this experimental feature and it will not available in the upcoming 2.12 release.

> Decrease the interval of ExoPlayerImplInternal::doSomeWork() to 0ms

You may of course try this, but here are some side-effects I can think of
- increased power usage: the ExoPlayerImplInternal thread will run continuously. If this is a battery powered device, please keep an eye on battery usage. 
- decreased player responsiveness: if the ExoPlayerImplInternal thread is busier running `doSomeWork()` all the time, the thread might not pick up other commands fast enough, including control commands coming from UI such as pausing, stopping or seeking. Please perform some QA testing to verify that there is no noticeable delays there.

Also, if you are trying to tune the player for the specific device, you may try a combination of the options discussed here to see what works best on the device.

**Comment by changxiangzhong** [comment]
@christosts, short version is - this is a great option. It works perfectly with our project. Please consider to keep this option in the future release.

I've followed your instruction - `experimental_setRenderTimeLimitMs(40)`, while building the `MediaCodecVideoRenderer` instance. 

The result seems very very ~interesting~ compelling. We see way lesser **audio buffer underrun** in logcat. The trade off is a few **visual frame drops**. This is PERFECTLY acceptable! This is actually the perfect solution - we are sitting with a low end device, if we have to choose between A) Visual frame drop, B) Audio jank, we can live with **visual frame drop**. **Audio jank** is way more annoying than. 

Before we applied this change, we have been puzzled by why **smooth stream** is of so many **audio janks**, while with **hls** and **dash**, there's only **visual frame drops** (which is perfectly acceptable). This option has put the **smooth streaming** to the same level as **dash** and **hls**. 

Please think about to keep this option in the future, this bring the **smooth streaming** quality as good as **hls** and **dash** Thanks a lot

Here are the sample manifest files, and we are using tunneling.
- [Smooth streaming](https://cd-stream-live.telenorcdn.net/cdgo/cdgo_nrk1hd_no_live/cdgo_nrk1hd_no_live.isml/Manifest)
- [HLS](https://cd-stream-live.telenorcdn.net/cdgo/cdgo_nrk1hd_no_live/cdgo_nrk1hd_no_live.isml/Manifest.m3u8)
- [Dash](https://cd-stream-live.telenorcdn.net/cdgo/cdgo_nrk1hd_no_live/cdgo_nrk1hd_no_live.isml/playlist.mpd)

**Comment by christosts** [comment]
Hi,

This is just to let you know that the feature is back at the dev-v2 branch, see commit [397fe8f](https://github.com/google/ExoPlayer/commit/397fe8f305a01c5921267fd31f9a900205eba3d5). So, although this method is not present at v2.12, it will be available on a next ExoPlayer release and you will be able to keep using it if you upgrade to the next release (when that time comes). 

Please note that, as part of the internal experimentation, the actual implementation might slightly differ from the one you are using at the moment.

**Comment by changxiangzhong** [comment]
@christosts Thanks for the input, I'll keep an eye on the implementation. I think this feature can be very useful because on our platform (derived from Banff) `MediaCodecVideoRender::feedInputBuffer()` takes 12ms with SS+Playready **in average**. **In burst cases** it could take up to 300 ms, which starves the audio handling completely (`AudioTrack::buffer` is 250ms by default). That's why I was thinking this feature can be a sliver bullet. There are side effects, OFC. With `experimental_setRenderTimeLimitMs(80)`, we are seeing more video frame drops than not having it.

So we are still discussing/experimenting with this option.
