### ISSUE TITLE
How do I remove the debug text at the top of the Demo app?

### ISSUE THREAD

**Issue by eservicetv** [google/ExoPlayer#7810]
hello how can i remove that text
![err](https://user-images.githubusercontent.com/70307516/91383412-79d80400-e802-11ea-9e8f-873e80ed04ea.png)

**Comment by AquilesCanta** [comment]
That text is produced by the `DebugTextViewHelper`. I'm assuming you are forking the demo app, in which case you should just not use a `DebugTextViewHelper` in your activity. Please comment below if this does not solve your question and I'll reopen.

**Comment by eservicetv** [comment]
I do not understand much but I would like to remove or hide it because it is annoying
