### ISSUE TITLE
Pause download

### ISSUE THREAD

**Issue by Subuday** [google/ExoPlayer#7812]
Before filing a feature request:
-----------------------
https://github.com/google/ExoPlayer/issues/4860

### [REQUIRED] Use case description
User should be able to pause downloading of one video. Currently supported only pause and resume all downloads. I have found a hack in whick I can set `DownloadService.sendSetStopReason()` and unset then. But when stop reason is set the notification is deleted.

**Comment by ojw28** [comment]
This is already supported by setting per-download stop reasons, as documented [here](https://exoplayer.dev/downloading-media.html#setting-and-clearing-download-stop-reasons).
