### ISSUE TITLE
How i can setVolume Left and Right

### ISSUE THREAD

**Issue by AskMeCode** [google/ExoPlayer#7815]
Hello all.

I need make app karaoke and i need to setVolume of each speaker left or right separated 
like setVolume(float left,float right);
if possible how i can do that,

Thanks in advance

**Comment by andrewlewis** [comment]
We don't support this directly, but please read #2659 for more information and guidance on implementing it via a custom `AudioProcessor`.

**Comment by AskMeCode** [comment]
@andrewlewis hi dear can you please guide me to make this custom AudioProcessor i don't got it from the URL you give me . if you have some time for me please .

**Comment by andrewlewis** [comment]
I'm afraid we don't have time to give step by step guidance on niche use cases like this. I suggest starting by copying `ChannelMappingAudioProcessor` and making edits along the lines of what's suggested in https://github.com/google/ExoPlayer/issues/2659#issuecomment-378284797. Then you will need to customize the renderers factory to include your custom audio processor.
