### ISSUE TITLE
Clicking on player notification pause my media playback

### ISSUE THREAD

**Issue by ravisaini1990** [google/ExoPlayer#7818]
On Exo player, I am playing any audio media and if I click on the notification of the player. Current ongoing media get paused and vice versa if its in pause state.
Note: I am not clicking on play/pause icon, clicking outside anywhere on notification causing this random behavior.

**Comment by marcbaechinger** [comment]
When creating the `PlayerNotificationManager` you need to create a `MediaDescriptionAdapter`. The adapter has a method `getCurrentContentIntent`. When clicking on the notification (not on any buttons) this pending intent is fired. If you return `null` for the pending intent tapping the notification should have no effect.

Can you review your code to see what you pass as the pending intent for your `MediaDescriptionAdapter`?

This simple implementation should make tapping the notification a no-op:

```
@Nullable
@Override
public PendingIntent createCurrentContentIntent(Player player) {
    return null;
}
```

If you are in doubt you can paste your implementation of the method here. I'm happy to review it for you.

**Comment by ravisaini1990** [comment]
@marcbaechinger If I set createCurrentContentIntent return as null, on clicking of notification won't open my app. I have the following code written

```
override fun createCurrentContentIntent(player: Player): PendingIntent? {
                    return launchIntent()
                }
```
------
```
fun launchIntent(action: String? = null): PendingIntent? {
        try {
            val launchIntent = Intent(getAppContent(), HomeActivity::class.java)
            return PendingIntent.getActivity(
                getAppContent(),
                0,
                launchIntent,
                PendingIntent.FLAG_CANCEL_CURRENT
            )
        } catch (exc: Exception) {
            return null
        }
    }
```
Please suggest what should i do

**Comment by marcbaechinger** [comment]
So what happens is that when the user taps the notification, it launches your activity again. You need to make sure that this does not recreate the player or similar. 

Please check [this documentation page](https://developer.android.com/training/notify-user/navigation) for more details.
