### ISSUE TITLE
Green screen when play video

### ISSUE THREAD

**Issue by rockman9x** [google/ExoPlayer#7823]
Hi ExoPlayer team,
We have a problem with newest version of ExoPlayer: 2.11.7. Player show green screen like picture below. Some device like OPPO-OPPO-A37fw, Xiaomi redmi note 4x, OPPO-OPPO-A33fw... are affected.  We try version 2.9.5 or lower version and it work without green screen.

**Version of ExoPlayer being used**
v2.11.7

**Device(s) and version(s) of Android being used**
OPPO-OPPO-A37fw - Android 5.1.1
Xiaomi Redmi note 4x - Android 7.0
OPPO-OPPO-A33fw - Android 5.1.1

![green](https://user-images.githubusercontent.com/13161505/91550278-879c9f00-e952-11ea-8e79-5ef29cf6883a.png)

**Comment by christosts** [comment]
Hi @rockman9x 

Does the issue occur when playing the content on the ExoPlayer demo app? If so, can you please share a link to your content for us to test, and also attach a bug report captured from your device(s) when the issue occurs? 

If you cannot share the above in public, you can send those over email at dev.exoplayer@gmail.com with subject "Issue #7823".
