### ISSUE TITLE
Player small icon goes missing from status bar while player is playing

### ISSUE THREAD

**Issue by ravisaini1990** [google/ExoPlayer#7824]
I am facing this little strange issue that the small player icon from the status bar goes missing randomly, while my Exo player is on and playing. 
Any suggestions about what I could do to solve it.

**Comment by marcbaechinger** [comment]
Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/question.md).

**Comment by hobsRKM** [comment]
@ravisaini1990 I had faced something related to this. See here #7820  it might be because of "Priority" settings.

**Comment by ravisaini1990** [comment]
Fixed
