### ISSUE TITLE
How can I make the login screen appear first?

### ISSUE THREAD

**Issue by eservicetv** [google/ExoPlayer#7827]
I would like to know how do I make the login screen (MainActivity.java) appear first

**Comment by eservicetv** [comment]
![fgejhde](https://user-images.githubusercontent.com/70307516/91627309-f7c81680-e98c-11ea-9dc1-1daa2b23cce7.PNG)

**Comment by marcbaechinger** [comment]
You need to configure your manifest accordingly. This is a general Android development question which we can not support in this issue tracker which is about questions and issues around the ExoPlayer library.  Look at the configuration of the `SampleChooserActivity` which has the category `android.intent.category.LAUNCHER`. For more details, please [refer to the Android documentation](https://developer.android.com/guide/topics/manifest/manifest-intro#example) or ask on StackOverflow.

**Comment by eservicetv** [comment]
ok thanks dear this I already solved it in the android manifest thanks anyway
