### ISSUE TITLE
Exoplayer continues to run when app goes in background

### ISSUE THREAD

**Issue by punitagoel2403** [google/ExoPlayer#7829]
The player keeps playing the video, and audio is audible when the app goes in background by any means. 
Is it expected behavior? If yes, what I need to do to stop playing it.

**Comment by marcbaechinger** [comment]
If the player goes in background you need to[ release the player](https://exoplayer.dev/hello-world.html#releasing-the-player) and create a new one when the app comes to the foreground again.

Best is to look into the [lifecycle methods ot the `PlayerActivity`](https://github.com/google/ExoPlayer/blob/release-v2/demos/main/src/main/java/com/google/android/exoplayer2/demo/PlayerActivity.java#L233) of the demo app. This is the approach which does it right on all API levels.

**Comment by punitagoel2403** [comment]
@marcbaechinger  Thank you :)
