### ISSUE TITLE
 Exception thrown when playing ts file

### ISSUE THREAD

**Issue by meizhiping2019** [google/ExoPlayer#7834]
### [REQUIRED] Issue description
I refer to the answers #7310, #6862, but did not find the corresponding reason.
I Can't play the ts file, but it can be played normally in vlc.

### [REQUIRED] Reproduction steps
1. I downloaded the ts file uploaded by my platform
2. Copy the file to the assets file and use exoplayer for local playback
3. I get an error Loading finished before preparation is complete.

### [REQUIRED] Link to test content

[063411.zip](https://github.com/google/ExoPlayer/files/5154833/063411.zip)

### [REQUIRED] A full bug report captured from the device
![image](https://user-images.githubusercontent.com/53566874/91826634-6e586300-ec70-11ea-9957-7851dd2d271f.png)

### [REQUIRED] Version of ExoPlayer being used
exoplayer 2.11.8
### [REQUIRED] Device(s) and version(s) of Android being used
samsung SM-G973U, Android 10

**Comment by christosts** [comment]
Is the file expected to have audio? I hear no audio when playing the file with VLC (tested on Mac and Android) and when I inspect the file with `ffprobe` I get 

```
[mpegts @ 0x55f73b438900] start time for stream 1 is not set in estimate_timings_from_pts
[mpegts @ 0x55f73b438900] stream 1 : no TS found at start of file, duration not set
[mpegts @ 0x55f73b438900] Could not find codec parameters for stream 1 (Audio: aac ([15][0][0][0] / 0x000F), 0 channels): unspecified sample format
```
