### ISSUE TITLE
"LicenseDurationRemaining" has always 0 as value

### ISSUE THREAD

**Issue by mseroczynski** [google/ExoPlayer#7836]
Device: LG V30 or more specifically LG-H930
ExoPlayer version: 2.11.8

Mentioned device downloads freshly generated Widevine license and instantly sees it as expired. Our other test devices behave 100% correctly with current implementation and I'm in a kind of a dead end (tried many license server configs) so I thought I'd ask here if there are any possible solutions. Other DRM protected apps (Spotify, Netflix etc.) seem to be working just fine on this device.

![image](https://user-images.githubusercontent.com/7540518/91842815-fe88af00-ec54-11ea-9016-cfea74986bcc.png)
![image](https://user-images.githubusercontent.com/7540518/91842826-01839f80-ec55-11ea-8106-b328a35fb550.png)

![image](https://user-images.githubusercontent.com/7540518/91843830-b36f9b80-ec56-11ea-9ea8-da7cf284faa0.png)
![image](https://user-images.githubusercontent.com/7540518/91843837-b66a8c00-ec56-11ea-9c58-dddfcb5d053d.png)

Is there anything I can try to make it work?

**Comment by christosts** [comment]
@ojw28 can you take a look?

**Comment by ojw28** [comment]
Re-routing to @rrfrias

**Comment by rrfrias** [comment]
I will try and see if i can find a similar device to reproduce. Is it possible to send some instructions to reproduce this problem to  dev.exoplayer@gmail.com. A test app and some content will be helpful.

**Comment by mseroczynski** [comment]
Could you please confirm you've received additional info that I've sent few days ago..?

**Comment by rrfrias** [comment]
We did get your information. Thanks. Would it be possible to share an app and repro steps so that we are testing it exactly as you are?

**Comment by mseroczynski** [comment]
I've sent you a mail with complete project and a small instruction. It instantly throws PlaybackException (or starts playing content on non problematic device). Hope you'll be able to reproduce this issue easier now. I’m eager to receive your feedback.

**Comment by mseroczynski** [comment]
Could you kindly update us on the status of this issue? I'd like to know if this clarifies as a serious release blocker. Also, meanwhile I've verified that external library (PRESTOplay, which uses ExoPlayer) can correctly handle DRM license offline caching flow - is there anything that can be done to fix it in ExoPlayer itself?

**Comment by rrfrias** [comment]
Sorry for the delay. I seem to get a 403 error when i try this on a Pixel 3 XL

> 10-20 16:14:45.438 E/ExoPlayerImplInternal( 8961):   com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403

 Can you help?

[android.log](https://github.com/google/ExoPlayer/files/5412201/android.log)

> Also, meanwhile I've verified that external library (PRESTOplay, which uses ExoPlayer) can correctly handle DRM license offline caching flow - is there anything that can be done to fix it in ExoPlayer itself?

From the information you provided this does not indicate an Exoplayer issue but rather one with the device(LG V30/LG-H930)/android framework. It is possible that other apps work because of differences in their license (duration) policy. If i am able to make a license request i can take a look at the policy. You can also share information of a sample policy, including license, rental, playback duration values and flags to dev.exoplayer@gmail.com.
