### ISSUE TITLE
This video urls not playing in exoplayer video urls is mp4 and webm

### ISSUE THREAD

**Issue by niteshfel** [google/ExoPlayer#7838]
**video is webm** 

https://r7---sn-gwpa-qxa6.googlevideo.com/videoplayback?expire=1598984263&ei=5ztOX_PGLpfj3LUP1-Sd0Aw&ip=157.37.179.34&id=o-AOffYPb4kBbZ2cU6tYnpE1GpRtHTtfhAYbzfG2GmIPzy&itag=243&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278%2C298%2C299%2C302%2C303&source=yt_otf&requiressl=yes&mh=nz&mm=31%2C26&mn=sn-gwpa-qxa6%2Csn-cvh76nek&ms=au%2Conr&mv=m&mvi=7&pl=19&initcwndbps=145000&vprv=1&mime=video%2Fwebm&otf=1&otfp=1&dur=0.000&lmt=1598416298237689&mt=1598962595&fvip=1&keepalive=yes&c=WEB&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cotf%2Cotfp%2Cdur%2Clmt&sig=AOq0QJ8wRgIhANb-GUKiqXtG0u-Hh957WJho1R8-YtAopJwVo-1J4-OsAiEA1c5_eZCJP5wdjZiX33UTw3or1FIYVwrLCpLppnsQz_0%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgN3vbD7_CXrRzQIQHO1w4wK3RO8YmLHa4V-TSFF9Wv20CIQDSZazlSoPzwwvE85LxiqjDopbUv08GGtascxawHCfO4g%3D%3D

https://r7---sn-gwpa-qxay.googlevideo.com/videoplayback?expire=1598984503&ei=1zxOX_STArLg4-EPxu61yAk&ip=157.37.179.34&id=o-AJLFcO7MfuB56B8zFNYetG_6VRakMGFAh6oQO_vYSvfg&itag=299&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278%2C298%2C299%2C302%2C303&source=youtube&requiressl=yes&mh=ru&mm=31%2C26&mn=sn-gwpa-qxay%2Csn-cvh76n7k&ms=au%2Conr&mv=m&mvi=7&pl=19&initcwndbps=136250&vprv=1&mime=video%2Fmp4&gir=yes&clen=1350366201&otfp=1&dur=3086.000&lmt=1598315193823375&mt=1598962832&fvip=5&keepalive=yes&c=WEB&txp=7216222&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cotfp%2Cdur%2Clmt&sig=AOq0QJ8wRQIgdKNc34KstEfZE50eBV2F1_toQ-wKU5B0tN2yClmPwC0CIQCDoreN64sAAl7GmDCxUiEvvFmJ3_BmzbYM_jSFjJcFEA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgPc_flMQCw-Q_HEtSrLPCyLLMGeyI8skRvkq4T9OFeyYCIQCcN3dVBnYG55e7Tof6_stDPtZsM8mZVqTOJPOn5sZYJA%3D%3D

**mp4 video url :** 

https://r7---sn-gwpa-qxay.googlevideo.com/videoplayback?expire=1598984503&ei=1zxOX_STArLg4-EPxu61yAk&ip=157.37.179.34&id=o-AJLFcO7MfuB56B8zFNYetG_6VRakMGFAh6oQO_vYSvfg&itag=298&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278%2C298%2C299%2C302%2C303&source=yt_otf&requiressl=yes&mh=ru&mm=31%2C26&mn=sn-gwpa-qxay%2Csn-cvh76n7k&ms=au%2Conr&mv=m&mvi=7&pl=19&initcwndbps=136250&vprv=1&mime=video%2Fmp4&otf=1&otfp=1&dur=0.000&lmt=1598315193823375&mt=1598962832&fvip=5&keepalive=yes&c=WEB&txp=7210222&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cotf%2Cotfp%2Cdur%2Clmt&sig=AOq0QJ8wRAIgW4y5jqbe9Jj8SdUmxSFUkQwcOTXESOsGV04Kbngjy4oCIAah-bR6ol8Y5Y8UOC7rXsn3jiSRV9cmXK9Rz6ViIv54&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgPc_flMQCw-Q_HEtSrLPCyLLMGeyI8skRvkq4T9OFeyYCIQCcN3dVBnYG55e7Tof6_stDPtZsM8mZVqTOJPOn5sZYJA%3D%3D

**Comment by christosts** [comment]
Hi @niteshfel,

- The 1st and 3rd links return an HTTP 404. Are the links accessible?
- The 2nd link plays on a Pixel 4 device with the ExoPlayer demo app (and also plays on Chrome), but the stream does not have an audio track. 

What kind of errors did you see, on which devices and ExoPlayer version?
