### ISSUE TITLE
Handle incoming calls when connected to car's bluetooth

### ISSUE THREAD

**Issue by tosam144** [google/ExoPlayer#7841]
I am using this code to handle incoming calls:

        AudioAttributes audioAttributes = new AudioAttributes.Builder()
                .setUsage(C.USAGE_MEDIA)
                .setContentType(C.CONTENT_TYPE_SPEECH)
                .build();

This works as exepected. However, a user reported that **when connected to a car media system via bluetooth** to listen to mp3s and then he receives an incoming call, the player stops completely (not paused but ended). So my user had to start the mp3 all over (from the beginning). I am using `AudioPlayerService` to stream mp3s. 

So my question is: Is there any difference between using ExoPlayer "normally" and using it via bluetooth in a car media system?

**Comment by christosts** [comment]
@andrewlewis will you be able to take look?

**Comment by andrewlewis** [comment]
I'm not sure why the car bluetooth case is behaving differently. Could you give some more precise details on the state of the player when you see the unexpected behavior that playback doesn't resume? Is the player actually in `STATE_ENDED` or is it just not resuming automatically?

If you reproduce the issue then capture a bug report from the device via `adb bugreport`, ideally from the demo app or with `EventLogger` set as the listener on the player, that is likely to have useful diagnostic information for us to figure out what is going on.

@nic0lette @jaewan-github Any ideas about this? Thanks.

**Comment by jaewan-github** [comment]
It seems to be working as expected due to the audio focus.

Phone call cause permanent loss of audio focus, and ExoPlayer's default audio focus behavior follows the developer's guideline [responding to an audio focus change](https://developer.android.com/guide/topics/media-apps/audio-focus#audio-focus-change).

You can check the audio focus change history via dump of audio service with command
`adb shell dumpsys audio`.

**Comment by jaewan-github** [comment]
Feel free to reopen if it's not your case.

**Comment by tosam144** [comment]
I think the request audio focus will simply cause speech to be paused. Once the incoming call is over, audio will resume where it was (not stop completely). This works as expected most of the time. Just one user complained about the issue I described above.

I will run some tests using `EventLogger` and then upload the logs here.

**Comment by jaewan-github** [comment]
Could you also also upload bug report as well, which contains audio focus history and device version?

If full bug report isn't available, then please attach logcat, audio service dump (`adb shell dumpsys audio`), and device version/model (`adb shell getprop ro.build.fingerprint`). Detailed audio focus behavior changes over releases, so it's helpful to verify behavior across the platform version.

**Comment by tosam144** [comment]
How can I get this info from a running device in the field? I am getting Logcat via `Runtime.getRuntime().exec(cmd)`.
