### ISSUE TITLE
No sound from HLS stream

### ISSUE THREAD

**Issue by malamoonh** [google/ExoPlayer#7842]
Hey. I use SimpleExoPlayer in my streaming video application. I noticed that sometimes the stream has sound, and sometimes it doesn't. I inserted the Uri of the stream directly - there is sound, and if, for example, change the timing of the link literally for 1 second, there is no sound anymore. At the same time, for comparison, I downloaded the VLS player, there is always sound for the same links. What could be the problem?
As TextureView i use ZoomableTextureView.

```
button?.setOnClickListener {
    val dataSourceFactory: DataSource.Factory = DefaultHttpDataSourceFactory(Util.getUserAgent(this, "testplayer"))
    val hlsMediaSource: HlsMediaSource = HlsMediaSource.Factory(dataSourceFactory).setAllowChunklessPreparation(true).createMediaSource(Uri.parse("here my stream link"))
    exoPlayer = SimpleExoPlayer.Builder(this).build()
    exoPlayer?.setVideoTextureView(texture)
    exoPlayer?.prepare(hlsMediaSource)
    exoPlayer?.playWhenReady = true
    texture?.postInvalidate()
}
```

Here are the stream parameters:
```
#EXTM3U
#EXT-X-VERSION:4
#EXT-X-TARGETDURATION:3.997
#EXT-X-MEDIA-SEQUENCE:5579
#EXT-X-PROGRAM-DATE-TIME:2020-09-02T07:58:55Z
#EXTINF:3.996,
hlsva_5579.ts?token=
#EXTINF:3.996,
hlsva_5580.ts?token=
#EXTINF:3.996,
hlsva_5581.ts?token=
#EXTINF:3.996,
hlsva_5582.ts?token=
#EXTINF:3.996,
hlsva_5583.ts?token=
#EXTINF:3.997,
hlsva_5584.ts?token=
#EXTINF:3.996,
hlsva_5585.ts?token=
#EXTINF:3.996,
hlsva_5586.ts?token=
#EXTINF:3.996,
hlsva_5587.ts?token=
#EXTINF:3.996,
hlsva_5588.ts?token=
```
and subsequent segments.

**Comment by christosts** [comment]
@AquilesCanta can you please take a look?

**Comment by AquilesCanta** [comment]
Hi @malamoonh, can you please provide both a link which plays with audio and one that plays without audio? I will need to reproduce the issue to help you.

**Comment by malamoonh** [comment]
I can't provide the link, as it contains a token, but I can provide the mpeg ts segment if it suits you

**Comment by AquilesCanta** [comment]
I cannot guarantee it will be enough for me to help, but whatever helps us reproduce the issue and understand what the expected and observed behaviors are. Make sure you can reproduce the issue with the standalone TS file before sending it to us.

**Comment by malamoonh** [comment]
We pass the playlist link to the player. If the difference in link timing is 1 second, the server returns the same segment, so I  can provide only 1 file. And if you start the downloaded segment, the sound is there. But in the player inside the application - there is sound in one case, in the other not. Perhaps the matter is in the sequential initialization of the video, and only then the sound on our server. I understand that my add-on gives very little information, but maybe you will notice something and some idea will appear.
[1.zip](https://github.com/google/ExoPlayer/files/5168093/1.zip)
![logs](https://user-images.githubusercontent.com/61450244/92108155-93271480-edef-11ea-8b90-6749c39bf45c.jpg)

**Comment by AquilesCanta** [comment]
This issue is very similar to #5537. The first PMT in the provided segment only declares a video track, but following PMTs correctly declare the audio track:

```
dvbsnoop -if 1.ts -tssubdecode -s ts -N 3 256

 Stream_type loop: 

            Stream_type: 27 (0x1b)  [= AVC video stream as defined in ITU-T Rec. H.264 | ISO/IEC 14496-10 Video]
            reserved_1: 7 (0x07)
            Elementary_PID: 257 (0x0101)
            reserved_2: 15 (0x0f)
            ES_info_length: 0 (0x0000)

...

        Stream_type loop: 

            Stream_type: 27 (0x1b)  [= AVC video stream as defined in ITU-T Rec. H.264 | ISO/IEC 14496-10 Video]
            reserved_1: 7 (0x07)
            Elementary_PID: 257 (0x0101)
            reserved_2: 15 (0x0f)
            ES_info_length: 0 (0x0000)


            Stream_type: 15 (0x0f)  [= ISO/IEC 13818-7 Audio with ADTS transport sytax]
            reserved_1: 7 (0x07)
            Elementary_PID: 258 (0x0102)
            reserved_2: 15 (0x0f)
            ES_info_length: 0 (0x0000)
```

I think the way to go here is to fix the media by removing the spurious PMT.

**Comment by AquilesCanta** [comment]
I will be adding a workaround for ExoPlayer to support streams with this kind of issues. Please track #7873.
