### ISSUE TITLE
The rewind, fast forward button and total time is not shown when I playing a music in .acc extension

### ISSUE THREAD

**Issue by donglp1810** [google/ExoPlayer#7843]
ExoPlayer is work well almost files in my app. I only get issue with .acc file. It still can play well but the remind, fast forward button is disable, total time is not show.
I'm using ExoPlayer version: 2.11.8.
I'm looking forward your help

**Comment by christosts** [comment]
Can you please provide us with a file to test? If you cannot attach the file publicly on this issue, please email it to dev.exoplayer@gmail.com with subject "Issue #7843", and then update the issue here.

You mention `acc` extension, did you mean `aac` instead?

**Comment by donglp1810** [comment]
> Can you please provide us with a file to test? If you cannot attach the file publicly on this issue, please email it to [dev.exoplayer@gmail.com](mailto:dev.exoplayer@gmail.com) with subject "Issue #7843", and then update the issue here.
> 
> You mention `acc` extension, did you mean `aac` instead?

Yes, It's .aac file

Please get more detail in attached files: 1 file is good for .flac file, 1 file is issue for .acc file

![Screenshot_20200903-085856_Home IQ](https://user-images.githubusercontent.com/7262510/92064217-40396700-edc7-11ea-859b-9f637441f934.jpg)

![Screenshot_20200903-085913_Home IQ](https://user-images.githubusercontent.com/7262510/92064235-4a5b6580-edc7-11ea-8852-751dbca27d96.jpg)

**Comment by christosts** [comment]
Hi @donglp1810.

In the comment above you have attached two screenshots (jpeg images) of your app when playing the media files, but we need the actual `.aac` file so that we can play it locally with the ExoPlayer demo app.

Can you please attach (or email) the `aac` file?

**Comment by donglp1810** [comment]
hi @christosts ,

I sent to dev.exoplayer@gmail.com a .aac file what get issue in my app. Please check it.

**Comment by christosts** [comment]
Here is the output of `mediainfo` insepcting the provided `.aac` file

```
General
Complete name                            : Daily Meeting 20200903.aac
Format                                   : ADTS
Format/Info                              : Audio Data Transport Stream
File size                                : 10.8 MiB
Overall bit rate mode                    : Variable

Audio
Format                                   : AAC LC
Format/Info                              : Advanced Audio Codec Low Complexity
Format version                           : Version 4
Codec ID                                 : 2
Bit rate mode                            : Variable
Channel(s)                               : 1 channel
Channel layout                           : C
Sampling rate                            : 48.0 kHz
Frame rate                               : 46.875 FPS (1024 SPF)
Compression mode                         : Lossy
Stream size                              : 10.8 MiB (100%)
```

Note that the file is encoded at variable bit rate. It is best explained in [Why are some media files not seekable?](https://exoplayer.dev/troubleshooting.html#why-are-some-media-files-not-seekable) in the ExoPlayer's trouble shooting section. Please consider using a different media container (mp4 works best) or at least encode at constant bit rate.
