### ISSUE TITLE
4k video 

### ISSUE THREAD

**Issue by kuailedeadai** [google/ExoPlayer#7845]
Hello, please tell me, when vpx decodes 4k video, it takes more than 100ms to decode a frame of video data. This will cause the audio and video synchronization module to discard the decoded video frames all the time. What are the optimization suggestions for this one? Looking forward to your answer, thank you

**Comment by christosts** [comment]
Can you please give us more info on your setup:
- apart from resolution, what is the bitrate of the video?
- what device is this happening on?
- when you say vpx, do you mean you are using ExoPlayer's [vp9 extension](https://github.com/google/ExoPlayer/tree/release-v2/extensions/vp9) or are you using ExoPlayer with the Android platform decoders only?

In principle, you might need to switch to a lower resolution and/or bitrate, but let's start by clarifying the above.

**Comment by kuailedeadai** [comment]
Hello:
This is the video file details：
![image](https://user-images.githubusercontent.com/10614848/92062502-7678e580-edcb-11ea-8a61-f1d63a13435a.png)
Occurs on the Android 10 model configuration, this phone performs well
vpx refers to exoplayer's vpx extension program, which uses soft decoding

How do I switch to a lower resolution and/or bit rate?

thanks

**Comment by Mavrick102** [comment]
> Hello:
> This is the video file details：
> ![image](https://user-images.githubusercontent.com/10614848/92062502-7678e580-edcb-11ea-8a61-f1d63a13435a.png)
> Occurs on the Android 10 model configuration, this phone performs well
> vpx refers to exoplayer's vpx extension program, which uses soft decoding
> 
> How do I switch to a lower resolution and/or bit rate?
> 
> thanks

did did u get that file decrypted please tell me how

**Comment by christosts** [comment]
So, the file is 4K encoded at 16.6Mb/s and you are using the software decoder. I can see how that can stretch the device's CPU.

I can think of different ideas:
1. Did you try without ExoPlayer's vp9 extension? Your device should be able to play VP9 directly. That may offer improved decoding performance. Note however, that different devices may have different decoders, so you might run to device-specific issues in case you plan to install the app on multiple device types.
2. You can try to lower the video bitrate and/or the resolution. That is, you may try to produce a video at 4K resolution at 8Mb/s (this is just random number, you can experiment more), or reduce the resolution assuming that it will also reduce the bitrate. To do that, you need to re-encode the video. Whether that's easy or not depends on how your application/service is setup. For example, do you have access to the encoding process? Of course, lowering the resolution and/or the bitrate might have impact on the visible video on screen, so it's up to you to decide what's best for your users. If you are not targeting TVs but targeting handheld devices, I'd say that a 1080p video will not look much worse compared to a 4K one (that's a personal opinion).
