### ISSUE TITLE
get key request type for renewal

### ISSUE THREAD

**Issue by coshri** [google/ExoPlayer#7847]
I'm using with Widevine DRM and I implement the MediaDrmCallback interface.
now I need to get information about the request type ( specific,  if it is 'renewal' I need to add more information for server) 

I see that android.media.MediaDrm.KeyRequest include [getRequestType](https://developer.android.com/reference/android/media/MediaDrm.KeyRequest#getRequestType()) methods for this.

why ExoMediaDrm.KeyRequest doesn't contain this information?
there is another way (by ExoPlayer) to know if the request is for renewal?

Thanks a lot
Oshri

**Comment by ojw28** [comment]
I think the addition of `getRequestType` probably happened after we implemented `ExoMediaDrm.KeyRequest`, so this is just an omission. We can add it.

Note that `getRequestType` didn't exist in the platform until API level 23, and similarly, we'll only be able to make it work via `ExoMediaDrm.KeyRequest` from API level 23 onward. How do you plan to decide whether to attach your additional information on earlier API levels? Note that if you need to make this work, you may as well just do whatever you come up with for all API levels so as not to have to wait for us to add this functionality to the library. I also wonder whether you can't just attach the additional information in all cases, and have the server ignore it if it's not a renewal.

Marking as an enhancement to track adding something equivalent to `getRequestType` for API level 23 and above.
