### ISSUE TITLE
Buffering behaviour with `ConcatenatingMediaSource` and `REPEAT_ONE`

### ISSUE THREAD

**Issue by kamalloup** [google/ExoPlayer#7848]
Hey everyone! 👋 

I have a very specific use case I'm trying to support with `ExoPlayer`: a playlist of multiple videos where each video of the playlist is on loop and will keep playing until the playlist index is manually moved to the next item. I have quite easily achieved this with a `ConcatenatingMediaSource` combined with the player's `REPEAT_ONE` repeat mode, as outlined in this great article: [Repeat modes in ExoPlayer](https://medium.com/google-exoplayer/repeat-modes-in-exoplayer-19dd85f036d3).

I'm now stuck on the buffering behaviour in this situation. Assuming I have a playlist containing videos `A`, `B` and `C`. While video `A` is playing on loop, I'd like for video `B` to start buffering as soon as `A` is 100% buffered. Empirically this doesn't seem to be happening. When toggling the repeat mode to `REPEAT_ONE` the next playlist item doesn't start buffering until the playlist window index is pointed to that item.

As I understand it, the player will determine what to buffer next based on the `Timeline.getNextWindowIndex()` method, in this case to be more specific `AbstractConcatenatedTimeline.getNextWindowIndex()` (source [here](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/source/AbstractConcatenatedTimeline.java#L79)). From what I see this method will return the current window when in `REPEAT_ONE` (please correct me if I'm wrong). This means that it will never start buffering the next window while in `REPEAT_ONE`.

This is how I'm setting up the player:
```
val player = ExoPlayerFactory.newSimpleInstance(this)
player.repeatMode = Player.REPEAT_MODE_ONE
val playlistMediaSource = ConcatenatingMediaSource(*playlistItems.toTypedArray())
player.prepare(playlistMediaSource)
```
Where `playlistItems` is a `List<HlsMediaSource>`.

### Searched documentation and issues

I've spent the last couple of days searching through existing issues and I think https://github.com/google/ExoPlayer/issues/3327 is the one that comes closer to meeting my requirements. It could provide a workaround by explicitly asking to start buffering the next item in the list. This would just be a workaround and is still just a feature request unfortunately. 

### Question(s)

- Is what I am experiencing the intended buffering behaviour for `ConcatenatingMediaSource` while in `REPEAT_ONE`? 
- Would it be reasonable for the player to start buffering the next playlist item once the current item has been completely buffered when playing a playlist in `REPEAT_ONE` mode?
- Is there a way to configure the player to achieve this behaviour at the moment?

Raising this as a question, but based on the answers could be either a bug or a feature request. 🙂

**Comment by marcbaechinger** [comment]
Thanks for your question! Your understanding is correct. 

Firstly, regarding #3327 and looping aside, if the user skips to the next window from an arbitrary position in the window, you would need #3327 in any case to have the player never re-buffer (given the media duration of a single window is not much smaller than max buffered duration). 

Besides this and if I understand correctly, the key problem you are having is that you want a change of an indefinite sequence of window indices to occur. Let me give you some context:

Internally ExoPlayer builds a queue of media periods [p,p,p,p,...] to be sequentially played and hence to be buffered. The sequence is determined by the current window index, the timeline, the repeat mode and the shuffle mode. The queue is rebuilt each time when either of these determinants changes.

In your case with `REPEAT_MODE_ONE` the queue with `currentWindowIndex=0` is `[P0, P0]`. Meaning the period of window 0 is repeated (lets assume one single period for each window). This tells the player to buffer the start of P0 again when at the end of P0. The manual seek to window 1 then builds a queue of `[P1, P1]` to seamlessly repeat window 1. So the queue to be played and buffered is never in the state of the timeline [W0, W1].

Because of this and #3327, you probably need to anticipate that a period needs suddenly to be played that is not already buffered. 

For non-adapative media and to make this sudden change quicker, you can pre-cache the next item or a portion of it. When the users skips, the data can be loaded from the local cache instead of the network. [A Medium post about this](https://medium.com/google-exoplayer/pre-caching-downloading-progressive-streams-in-exoplayer-3a816c75e8f6) is a bit old but should give some context. 

(Not as a recommendation but just a though or last resort is that you could consider of using two players if the caching solution is not good enough or adaptive media makes pre-loading difficult. This obviously introduces UI logic complexities though.)

> Would it be reasonable for the player to start buffering the next playlist item once the current item has been completely buffered when playing a playlist in REPEAT_ONE mode?
> Is there a way to configure the player to achieve this behaviour at the moment?

I don't think that the behavior of the period queue will change to match the use case with indefinite looping I'm afraid.

**Comment by kamalloup** [comment]
Hey @marcbaechinger! First of all, thanks for your thorough and very clear response. 🙇  

> if the user skips to the next window from an arbitrary position in the window, you would need #3327 in any case to have the player never re-buffer

True, I see how that would be necessary in most situations. In my question I have failed to say that I am working with videos that are between 30 and 60 seconds in length. This means that each video would be easily buffered in its entirety in a short amount of time. So, in my (very) specific case avoiding re-buffering should be possible most of the time.

> This tells the player to buffer the start of P0 again when at the end of P0. The manual seek to window 1 then builds a queue of [P1, P1] to seamlessly repeat window 1. So the queue to be played and buffered is never in the state of the timeline [W0, W1].

Great explanation! This means that there's currently **no way to separate the playback behaviour from the buffering behaviour**, because they both rely on the same queue. The behaviour I am after would require the playback queue to be `[P0, P0]` and the buffering queue to be `[P0, P1]`. And this is not possible. Correct?

> Not as a are recommendation but just a though or last resort is that you could consider of using two players if the caching solution is not good enough or adaptive media makes pre-loading difficult.

Unfortunately I am serving adaptive media. So pre-loading would be challenging (if possible at all). The two player swap "trick" was my last resort, but I really wanted to avoid it. It adds a lot of complexity and can be fiddly. At this stage I think I'll watch https://github.com/google/ExoPlayer/issues/3327 and hope it'll be added as a new feature at some point in the near future.

Thanks for your help!

**Comment by marcbaechinger** [comment]
> thanks for your thorough and very clear response

well, I just tried to give an answer as clear and well formulated as the question. :)

Yes, you are right that there is only one queue which is built according to the periods to be played. And sorry I couldn't really help in the end as your conclusion is correct that this is not really possible right now.

Something came to my mind for your case of 30 second videos. It's a bit hacky and I haven't tried so I can not say how properly that works (and whether I recommend doing that :D). Just as a thought. It is about building a timeline `[W0, W1, W2, W3]` and play it without repeat mode -> `[P0,P1,P2,P3]`. Then you [create a message that is fired at a position](https://exoplayer.dev/customization.html#sending-messages-to-components) close to the end of each window. If playback is at that position, your code in the message target is executed and adds window `W0'` and sets a message to be executed close to the end of `W0'`: `[W0, W0', W1, W2, W3]` If the user does not skip again, that message is fired again and does `[W0, W0', W0'', W1, W2, W3]` and so on (you can add the same media source instance multiple times, btw). If the user skips before that position, the player skips to `W1` which is already buffered in your case of short videos. 

If the position at which the message executes is sufficiently close to the end, the majority of cases could benefit from that. So when the position is 5 secs before the end, all user skips which are in the range of 0sec to (duration - 5secs) would skip to the next window without buffering. What I'm not quite sure and haven't tested is how close to the end of the window the message can be to still have a proper looping experience. If it's too close, the player probably buffers when looping (plus you need to sanitize the case when the user skips in the last 5secs). Depending on how much you want it, it's probably worth experimenting with this. Agreed it adds some complexities. :) (aside: if the bandwidth for the user is already scarce, eg slow network or metered/capped data plan,  it may make it even worse with that approach. Not sure.).

**Comment by kamalloup** [comment]
Thanks again @marcbaechinger! It's a good (albeit a bit hacky 😛 ) idea. I'll play around with it and see whether the result is any better than the two player swap option in regards to complexity / performance.

Really appreciate your time. I don't think there's a feature request coming out of this conversation, I honestly wouldn't know what change to recommend. I'll close the issue. 🙂

**Comment by tonihei** [comment]
> you can pre-cache the next item or a portion of it.

This is practically speaking still a good option I think. Note that ExoPlayer supports downloading of adaptive media. See https://exoplayer.dev/downloading-media.html#downloading-and-playing-adaptive-streams.

> I don't think there's a feature request coming out of this conversation, I honestly wouldn't know what change to recommend. 

I think you initial feature request is already covered by #3327. When we get around to implement #3327, we should make sure to prebuffer whatever period is "next" according to the "player.next()" operation. And in your case, "player.next()" skips to the next item regardless of repeat mode.

**Comment by kamalloup** [comment]
Thanks for following up @tonihei! I must have misunderstood the previous comment then. Good to know that pre-downloading is an option with adaptive media streams. Though, if it does require the `DownloadManager` and the corresponding download notification I am seeing in the example, then it might have some unwanted UX implications. I'll look into it further...

> we should make sure to prebuffer whatever period is "next" according to the "player.next()" operation

Yes, that should do it. If that's how it'll be implemented then https://github.com/google/ExoPlayer/issues/3327 is probably the ideal solution for me. 🙂 

Just to recap for whoever might stumble on this issue in the future (eg. me in 6 months). Three workarounds have been suggested to meet this use case before https://github.com/google/ExoPlayer/issues/3327 is delivered:

- Manage two players, having one buffering while the other is playing and then swapping them when required.
- Manually request to pre-download the next stream while the current one is playing.
- Don't set the player in `REPEAT_ONE` mode but rather dynamically modify the timeline by inserting new windows when appropriate.

No solution has been tested so far.

**Comment by tonihei** [comment]
> and the corresponding download notification I am seeing in the example, then it might have some unwanted UX implications

The notifications are optional. If your app stays in foreground during the download process, you may as well use `DownloadManager` directly in a background thread of your app (i.e. without the service).

**Comment by kamalloup** [comment]
> The notifications are optional. If your app stays in foreground during the download process, you may as well use DownloadManager directly in a background thread of your app (i.e. without the service).

True, thanks @tonihei! 
In the meantime I've been suggested an alternative approach: 

- Do not use `REPEAT_ONE`.
- Listen for the playback end event for the currently playing video.
- Once the event is received: seek back to current window start.

This basically implements repeat one "manually" while allowing the player to pre-cache the next item in the playlist. Will consider this option together with the others listed.
