### ISSUE TITLE
Buffer stuck after seeking

### ISSUE THREAD

**Issue by itboy87** [google/ExoPlayer#7853]
### [REQUIRED] Issue description
Video plays fine without seeking but if seek then it keeps buffering and never plays. But if we seek again it from start then it will start playing again fine.

### [REQUIRED] Reproduction steps
use this URL `https://cdn-na-b2.nextstream.org/stream/0001/74caecc945501095109bc44c764697a6305c87949b2bc42f225e2e86efe82dcc/uwu.m3u8`
with header `Referer:https://kwik.cx/e/0yaDWcEQScOe`
It will play but will stuck when seek

### [REQUIRED] Link to test content
```
val videoUri = "https://cdn-na-b2.nextstream.org/stream/0001/74caecc945501095109bc44c764697a6305c87949b2bc42f225e2e86efe82dcc/uwu.m3u8"
val dataSourceFactory = DefaultHttpDataSourceFactory(C.USER_AGENT)
dataSourceFactory.defaultRequestProperties.set("Referer", "https://kwik.cx/e/0yaDWcEQScOe")
val videoSource = HlsMediaSource.Factory(dataSourceFactory)
                .setExtractorFactory(
                    DefaultHlsExtractorFactory(
                        DefaultTsPayloadReaderFactory.FLAG_ALLOW_NON_IDR_KEYFRAMES,
                        false
                    )
                )
                .createMediaSource(videoUri)
exoPlayer?.prepare(videoSource, true, true)
```

Video link: `https://cdn-na-b2.nextstream.org/stream/0001/74caecc945501095109bc44c764697a6305c87949b2bc42f225e2e86efe82dcc/uwu.m3u8`
with header `Referer:https://kwik.cx/e/0yaDWcEQScOe`

### [REQUIRED] A full bug report captured from the device
No error in logs

### [REQUIRED] Version of ExoPlayer being used
2.11.8 and also older versoins

### [REQUIRED] Device(s) and version(s) of Android being used
That issue occurs on all devices and emulators.

**Comment by christosts** [comment]
I can repro on the demo app from the dev-v2 branch, modified to match the code snippet's configuration. @AquilesCanta can you take a look?

**Comment by itboy87** [comment]
@christosts @AquilesCanta any workaround?

**Comment by itboy87** [comment]
@christosts @AquilesCanta any update?

**Comment by AquilesCanta** [comment]
Hi, we are looking into this. I'll post below once I have any updates. Thanks for your patience.

**Comment by itboy87** [comment]
Hi @AquilesCanta ok. Thanks.

**Comment by itboy87** [comment]
Hi @AquilesCanta, any update?

**Comment by AquilesCanta** [comment]
The media is malformed. The first segment contains correct PSI information: PAT declares a PMT on PID 4095. With that initialisation information, playback continues throughout the media correctly. When seeking, the extractor needs to parse initialisation information again, but all segments after the first spuriously declare the PMT at PID 3583, which doesn't exist in the stream. I've also noticed the CRC check is failing too, so it's possible the PATs on all segments (except the first) are corrupted, somehow. You should check that the PSI is correct for all segments in the stream. See [spec](https://tools.ietf.org/html/draft-pantos-http-live-streaming-23#section-3.2).
