### ISSUE TITLE
Screen rotation issue

### ISSUE THREAD

**Issue by hinditutorpoint** [google/ExoPlayer#7857]
Dear sir
Facing screen rotation related issue if we flip horizontal or vertical the flip screen both playerview and controller view I want flip only player view
I trying with code
playerView.setRotationX(playerView.getRotationX+180f);

Sorry for any typo
Thanks for advance

**Comment by kim-vde** [comment]
I don't think there is any easy way to do that.

You could try to add an OrientationEventListener on your activity and dynamically move the controls around when the screen is rotated.

Maybe @ojw28 has a better idea?

**Comment by hinditutorpoint** [comment]
Thanks for replay sir 
I found easy method
1 surface type texture view
View mVideoView=playerView.getVideoSurfaceView()
mVideoView.setRotationX(mVideoView.getRotationX+180f);
