### ISSUE TITLE
Can i prevent screen recording on exoplayer 2

### ISSUE THREAD

**Issue by niteshfel** [google/ExoPlayer#7860]
I have a query regarding security feature so can i prevent screen recording . like if any video is playing in my app using exoplayer then no can record screen using any screen recorders.  because these videos are paid type. so please suggest how can i do this.

**Comment by hinditutorpoint** [comment]
https://developer.android.com/reference/android/view/SurfaceView#setSecure(boolean)

**Comment by kim-vde** [comment]
See also [SimpleExoPlayer#setVideoSurfaceView](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/SimpleExoPlayer.html#setVideoSurfaceView-android.view.SurfaceView-) and [PlayerView#getVideoSurfaceView](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/ui/PlayerView.html#getVideoSurfaceView--).

**Comment by luiscurini** [comment]
I'm using this but with the built in screen recorder in Android 11, the audio can still be recorded. Is there a way to also prevent this?

**Comment by kim-vde** [comment]
Have you tried to add `android:allowAudioPlaybackCapture="false` to your manifest application tag?

**Comment by ojw28** [comment]
See https://android-developers.googleblog.com/2019/07/capturing-audio-in-android-q.html for more details.
