### ISSUE TITLE
ExoPlayer unable to play videos recorded from device's camera

### ISSUE THREAD

**Issue by EllingtonKirby** [google/ExoPlayer#7861]
### [REQUIRED] Issue description
I have built an ExoPlayer video player inside a RecyclerView adapter. I share a single instance of ExoPlayer for the adapter via the parent fragment, and create and prepare different media sources per item in the adapter. I use the default data sources and extractors, as follows
```
    private val dataSourceFactory: DefaultDataSourceFactory = DefaultDataSourceFactory(context, Util.getUserAgent(context, context.applicationInfo.name))
    private val mediaSourceFactory: ProgressiveMediaSource.Factory = ProgressiveMediaSource.Factory(dataSourceFactory, DefaultExtractorsFactory())
```

When I record a video using the camera, there are situations where the playback will fail, with the following error:
```
com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor, AmrExtractor, Ac4Extractor, FlacExtractor) could read the stream.
```

However, in 99% of other cases, playback succeeds correctly and we are able to preview the video. I am using Google's CameraX library to perform the video recording, and the video is saved to a file in the `cacheDir` with a `.mp4` extension.

### [REQUIRED] Reproduction steps
It is most reproducible by loading a video from the phone's gallery, dismissing it, then recording a video from the camera. However, attempted video recordings following this failed recording will succeed and preview correctly, so the issue is temporary. 

### [REQUIRED] Link to test content
Any recording will reproduce the bug

### [REQUIRED] Version of ExoPlayer being used
2.11.4

### [REQUIRED] Device(s) and version(s) of Android being used
Pixel 3 Android 10 (and many other phones)

**Comment by kim-vde** [comment]
This error means that there is either a problem in the media file, or a problem in the extractor sniffing method.

Can you provide a test content that produces the error? I couldn't reproduce it myself. If you're unable to share the test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #7861". Please also update this issue to indicate you’ve done this. Thanks.

**Comment by EllingtonKirby** [comment]
Hi there, thank you for the update. 

I can reproduce this with any media, there is no specific media that causes this.

It occurs by playing a video with ExoPlayer (any video), stopping playback, recording a video using CameraX, and then attempting to play the recorded video using ExoPlayer. 

When using the device file explorer and exporting the recorded video, I have no issues playing it in another media player. However, it does not play using ExoPlayer

**Comment by kim-vde** [comment]
Sorry, but I am not sure I am following.

Does it work if you try to play a recorded video with the [demo app](https://github.com/google/ExoPlayer/tree/dev-v2/demos/main)?

**Comment by EllingtonKirby** [comment]
I am looking at the Demo application, how would I change the content that is being played?

**Comment by kim-vde** [comment]
If you cannot reproduce the issue with the demo app, can you provide me an application where it can easily be reproduced? I need some easy reproduction steps to investigate.

Something else you can do is to debug `Sniffer.java` from package `com.google.android.exoplayer2.extractor.mp4` and check why `sniffFragmented` and `sniffUnfragmented` both return false (one of them should return true when trying to play an mp4 file).

**Comment by EllingtonKirby** [comment]
Hi Kim! There are security issues around me sending you our sample app, so I am working on creating a sample app to reproduce the issue.

In the meantime, I have worked on debuging `Sniffer.java`

I set up some breakpoints in `ProgressiveMediaPeriod.java` and `Sniffer.java` during the `selectExtractor` process, and logged the three booleans returned by `sniffInternal` 

```
Sniffing com.google.android.exoplayer2.extractor.mp4.Mp4Extractor@83c370d
Breakpoint reached at com.google.android.exoplayer2.extractor.mp4.Sniffer.sniffInternal(Sniffer.java:178)
isFragmented: false | foundGoodFiileType: true |  fragmented: false 
Sniff success
```

It looks like the extractor is successfully found.

However, in the case above, I was still left with the issue described: I can hear the audio track looping, but the video player is stuck on the first frame of playback, and never progresses. 

I see 
`2020-09-15 12:27:22.953 887-2667/? E/LocSvc_SystemStatus: PQWP7parser - invalid size=404`
Filling up the logs when the video is stuck in this state, not sure if it is relevant

Let me know if this is helpful information. 

Aside, can I correspond with the email you posted above to avoid publicly posting our sample?

**Comment by kim-vde** [comment]
> Hi Kim! There are security issues around me sending you our sample app, so I am working on creating a sample app to reproduce the issue.

Thanks. I think this is gonna be much easier.

> However, in the case above, I was still left with the issue described: I can hear the audio track looping, but the video player is stuck on the first frame of playback, and never progresses.

This is different from the original issue, right? If yes, please open another bug so that the discussion is easier to follow. 

Does this occur only in repeat mode? Is the duration indicated in the UI correct? 

Again, sharing the file which produces the issue and/or reproduction steps would really be helpful.

You could also debug `MediaCodecRenderer#feedInputBuffer` to see if the decoder receives the video frames.

> Aside, can I correspond with the email you posted above to avoid publicly posting our sample?

Yes, sure. Please also update this issue to indicate that you have done so.

**Comment by EllingtonKirby** [comment]
No this is the same issue. The video playback fails (stays frozen on one frame), but the audio is there. We don't track duration in this screen, but the audio lasts the correct duration. 

There is not a specific file that causes the issue, it occurs immediately after a video has been recorded using CameraX. 

I debugged into `MediaCodecRenderer#feedInputBuffer` and the method was hit many times. How would I know if the decoder is receiving video frames or not?

**Comment by ojw28** [comment]
Is it possible that the new video file hasn't been fully written to disk by the time you're preparing the player? I.e., that it's a CameraX problem, or a problem with the assumptions you're making about use of that API? It seems like the most plausible explanation, particularly if the issue "resolves itself" shortly thereafter (I'm not sure if this is true).

**Comment by EllingtonKirby** [comment]
Yes, it is likely that this is a CameraX problem. I just wanted to raise it here to see if this was a known issue within ExoPlayer.

We are receiving the file from the "success" callback of the recording process, and then we pass it off to the player. So ideally that prevents any such race condition but perhaps there is an issue somewhere in the file writing (although when I manually download the .mp4 via the device file explorer it plays correctly).

CameraX video recording is still experimental so there is not much support on these kinds of issues yet, hence me turning here first.

**Comment by kim-vde** [comment]
I will mark this issue as "need more info" until you can confirm that it is a CameraX issue or until we have a way to reproduce.

**Comment by kim-vde** [comment]
I will close this issue. Feel free to open a new issue if you discover that the problem comes from ExoPlayer.
