### ISSUE TITLE
Fix the problem when video file in res/raw file can be played.

### ISSUE THREAD

**Issue by JeffMony** [google/ExoPlayer#7866]
Before filing a feature request:
-----------------------
- Search existing open issues, specifically with the label ‘enhancement’:
  https://github.com/google/ExoPlayer/labels/enhancement
- Search existing pull requests: https://github.com/google/ExoPlayer/pulls

When filing a feature request:
-----------------------
Fill out the sections below, leaving the headers but replacing the content. If
you're unable to provide certain information, please explain why in the relevant
section. We may close issues if they do not include sufficient information.

### [REQUIRED] Use case description
When I create a raw folder in res folder, I save test.mp4 in res/raw/test.mp4,
I want to play the raw video file with : android.resource schema
But exoplayer cannot play the android.resource schema file

### Proposed solution
```
Author: JeffMony <jeffmony@163.com>
Date:   Tue Sep 8 14:56:25 2020 +0800

    Fix the problem when video file in res/raw file can be played.
    
    Signed-off-by: JeffMony <jeffmony@163.com>

diff --git a/library/core/src/main/java/com/google/android/exoplayer2/upstream/DefaultDataSource.java b/library/core/src/main/java/com/google/android/exoplayer2/upstream/DefaultDataSource.java
index afef3e676..582a53b02 100644
--- a/library/core/src/main/java/com/google/android/exoplayer2/upstream/DefaultDataSource.java
+++ b/library/core/src/main/java/com/google/android/exoplayer2/upstream/DefaultDataSource.java
@@ -58,6 +58,7 @@ public final class DefaultDataSource implements DataSource {
   private static final String SCHEME_RTMP = "rtmp";
   private static final String SCHEME_UDP = "udp";
   private static final String SCHEME_RAW = RawResourceDataSource.RAW_RESOURCE_SCHEME;
+  private static final String SCHEME_ANDROID_RESOURCE = RawResourceDataSource.ANDROID_RESOURCE_SCHEME;
 
   private final Context context;
   private final List<TransferListener> transferListeners;
@@ -169,7 +170,7 @@ public final class DefaultDataSource implements DataSource {
       dataSource = getUdpDataSource();
     } else if (DataSchemeDataSource.SCHEME_DATA.equals(scheme)) {
       dataSource = getDataSchemeDataSource();
-    } else if (SCHEME_RAW.equals(scheme)) {
+    } else if (SCHEME_RAW.equals(scheme) || SCHEME_ANDROID_RESOURCE.equals(scheme)) {
       dataSource = getRawResourceDataSource();
     } else {
       dataSource = baseDataSource;
diff --git a/library/core/src/main/java/com/google/android/exoplayer2/upstream/RawResourceDataSource.java b/library/core/src/main/java/com/google/android/exoplayer2/upstream/RawResourceDataSource.java
index 0595cb84b..4c7c55d85 100644
--- a/library/core/src/main/java/com/google/android/exoplayer2/upstream/RawResourceDataSource.java
+++ b/library/core/src/main/java/com/google/android/exoplayer2/upstream/RawResourceDataSource.java
@@ -65,6 +65,7 @@ public final class RawResourceDataSource extends BaseDataSource {
 
   /** The scheme part of a raw resource URI. */
   public static final String RAW_RESOURCE_SCHEME = "rawresource";
+  public static final String ANDROID_RESOURCE_SCHEME = "android.resource";
 
   private final Resources resources;
 
@@ -87,7 +88,8 @@ public final class RawResourceDataSource extends BaseDataSource {
     try {
       Uri uri = dataSpec.uri;
       this.uri = uri;
-      if (!TextUtils.equals(RAW_RESOURCE_SCHEME, uri.getScheme())) {
+      if (!TextUtils.equals(RAW_RESOURCE_SCHEME, uri.getScheme()) &&
+          !TextUtils.equals(ANDROID_RESOURCE_SCHEME, uri.getScheme())) {
         throw new RawResourceDataSourceException("URI must use scheme " + RAW_RESOURCE_SCHEME);
       }
 
```

### Alternatives considered
A clear and concise description of any alternative solutions you considered,
if applicable.

**Comment by JeffMony** [comment]
@ojw28 Could you check the feature?

**Comment by JeffMony** [comment]
> @ojw28 Could you check the feature?

Yes, I have checked it with many phones, such as Huawei/Vivo/Oppo/Mi Phone.

**Comment by JeffMony** [comment]
@ojw28 
https://github.com/JeffMony/PlayerSDK/blob/master/files/exoplayer-rawtest.jpg
This is the patch

**Comment by kim-vde** [comment]
Can you explain why you want the scheme to be "android.resource"? Can you use `RawResourceDataSource.buildRawResourceUri(R.raw.filename)` to build the URI?

**Comment by JeffMony** [comment]
@ojw28 
I use the android.resource schema for the following reason:
Android platform support android.resource schema, for example, http://androidxref.com/9.0.0_r3/xref/frameworks/base/core/java/android/content/ContentResolver.java#190
`
public static final String SCHEME_ANDROID_RESOURCE = "android.resource";

96    public final @Nullable InputStream openInputStream(@NonNull Uri uri)
997            throws FileNotFoundException {
998        Preconditions.checkNotNull(uri, "uri");
999        String scheme = uri.getScheme();
1000        if (SCHEME_ANDROID_RESOURCE.equals(scheme)) {
1001            // Note: left here to avoid breaking compatibility.  May be removed
1002            // with sufficient testing.
1003            OpenResourceIdResult r = getResourceId(uri);
1004            try {
1005                InputStream stream = r.r.openRawResource(r.id);
1006                return stream;
1007            } catch (Resources.NotFoundException ex) {
1008                throw new FileNotFoundException("Resource does not exist: " + uri);
1009            }
1010        } else if (SCHEME_FILE.equals(scheme)) {
1011            // Note: left here to avoid breaking compatibility.  May be removed
1012            // with sufficient testing.
1013            return new FileInputStream(uri.getPath());
1014        } else {
1015            AssetFileDescriptor fd = openAssetFileDescriptor(uri, "r", null);
1016            try {
1017                return fd != null ? fd.createInputStream() : null;
1018            } catch (IOException e) {
1019                throw new FileNotFoundException("Unable to create stream");
1020            }
1021        }
1022    }
`

ExoPlayer is a universal player, it should support the android platform standard schema such as android.resource

**Comment by JeffMony** [comment]
@kim-vde The reason

**Comment by ojw28** [comment]
This is equivalent to [Internal ref: b/162842184]. We should probably just make the changes documented in `#6` of the internal issue.

**Comment by JeffMony** [comment]
> This is equivalent to [Internal ref: b/162842184]. We should probably just make the changes documented in `#6` of the internal issue.

So , will you submit this change to ExoPlayer project ?

**Comment by kim-vde** [comment]
Yes, it is work in progress.
