### ISSUE TITLE
rtmp stream crash

### ISSUE THREAD

**Issue by androidWht** [google/ExoPlayer#7871]
version:
    api 'com.google.android.exoplayer:exoplayer:2.11.7'
    api 'com.google.android.exoplayer:extension-rtmp:2.11.7'
    api 'com.google.android.exoplayer:extension-ima:2.11.7'
![1599614033(1)](https://user-images.githubusercontent.com/10459917/92544101-a0c11c00-f27f-11ea-8e82-ab212324f033.jpg)
Play RTMP on a weak network may crash and anr

**Comment by kim-vde** [comment]
Could you provide reproduction steps together with a bug report, as suggested by our [template](https://github.com/google/ExoPlayer/blob/dev-v2/.github/ISSUE_TEMPLATE/bug.md)?
