### ISSUE TITLE
Why exoplayer cannot stream PLS type streaming link?

### ISSUE THREAD

**Issue by bhaskarraj** [google/ExoPlayer#7875]
I have PLS streaming link which plays fine in other players. But exoplayer is not able to play such link. Test link:
[http://shoutcast.radyogrup.com:1020/listen.pls](url)

Does exoplayer not support of PLS type streaming? I am able to stream .m3u8 and other links except for that.

**Comment by kim-vde** [comment]
Duplicate of #1947.
