### ISSUE TITLE
How to get raw output data from a rtmp url

### ISSUE THREAD

**Issue by luohaohaha** [google/ExoPlayer#7883]
I use rtmpdatasource to play，I want to process raw data,so setvideoencoderoutputbufferrenderer，but not called. How can we handle the live data stream?

Sorry for bad english

**Comment by kim-vde** [comment]
I am afraid I don't understand what the question is. 

What do you mean by "so setvideoencoderoutputbufferrenderer，but not called"?

How is the raw data like? Is it PCM audio data inside a container format? Maybe you could send an example file so that I can check. If you're unable to the test content publicly, please send it to dev.exoplayer@gmail.com using subject "Issue #7883". Please also update this issue to indicate you’ve done this.

**Comment by luohaohaha** [comment]
Code like this.
Are there other ways to get raw data?
```
        Uri url = Uri.parse("rtmp://...");
        TrackSelection.Factory trackSelectionFactory = new AdaptiveTrackSelection.Factory();
        DefaultTrackSelector trackSelector = new DefaultTrackSelector(/* context= */ this, trackSelectionFactory);
        SimpleExoPlayer player = new SimpleExoPlayer.Builder(/* context= */ this).setTrackSelector(trackSelector).build();
        RtmpDataSource.Factory dataSourceFactory = new RtmpDataSourceFactory();
        MediaSource videoSource = new ProgressiveMediaSource.Factory(dataSourceFactory).createMediaSource(url);
        player.prepare(videoSource);
        player.setVideoDecoderOutputBufferRenderer(new VideoDecoderOutputBufferRenderer() {
            @Override
            public void setOutputBuffer(VideoDecoderOutputBuffer outputBuffer) {
                //I want to get the raw data and do something, but there is no callback
            }
        });
        player.setVideoSurface(mSurfaceView);
        player.setPlayWhenReady(true);
```

**Comment by kim-vde** [comment]
As specified in the Javadoc, `setVideoDecoderOutputBufferRenderer` is intended for use only with extension renderers that accept `Renderer#MSG_SET_VIDEO_DECODER_OUTPUT_BUFFER_RENDERER`.

What you could do is to:
- Create a custom `Renderer` (probably by extending `BaseRenderer`). You might need to make this renderer implement `MediaClock` to speed things up if you don't need to get the frames at the time when they should be displayed.
- In the `render()` method, call `readSource()` to retrieve the encoded video frames.
- Decode the video frames using [`MediaCodec`](https://developer.android.com/reference/android/media/MediaCodec) to have acccess to the raw video frames.
- Create a custom `RenderersFactory` that would return your custom `Renderer`.
- Pass the new factory to a `SimpleExoPlayer`.
