### ISSUE TITLE
Exoplayer's PlayerNotificationManager not handling focus. Audio getting mixed up.

### ISSUE THREAD

**Issue by angitha-das** [google/ExoPlayer#7884]
Hi,

The SimpleExoPlayer is what I use in my application. I have placed the play/pause button in my XML layout file, i.e I am not using PlayerControlView. I need to show a notification when audio is played. I am using the below method.

```
 fun setDescriptionAdapter(adapter: DescriptionAdapter) {
        playerNotificationManager = PlayerNotificationManager.createWithNotificationChannel(
            context,
            PLAYBACK_CHANNEL_ID,
            R.string.playback_channel_name,
            R.string.playback_channel_description,
            PLAYBACK_NOTIFICATION_ID,
            adapter
        )

        playerNotificationManager?.setSmallIcon(R.drawable.app_logo)
        // omit skip previous and next actions
        playerNotificationManager?.setUseNavigationActions(false)
        // omit fast forward action by setting the increment to zero
        playerNotificationManager?.setFastForwardIncrementMs(0)
        // omit rewind action by setting the increment to zero
        playerNotificationManager?.setRewindIncrementMs(0)

        val trackSelector = DefaultTrackSelector(context)
        player = ExoPlayerFactory.newSimpleInstance(context, trackSelector)
        playerNotificationManager?.setPlayer(player)
    }
```
I have initialized my player initializePlayer() method as given below. I had referred the issues section and from the answer got a link to modify code with audio attributes so that Exoplayer will handle the focus.

```
private fun initializePlayer() {
        val audioAttributes =
            AudioAttributes.Builder()
                .setUsage(C.USAGE_MEDIA)
                .setContentType(C.CONTENT_TYPE_SPEECH)
                .build()

        player = SimpleExoPlayer.Builder(context).build().apply {
            setHandleAudioBecomingNoisy(true)
            setAudioAttributes(audioAttributes, true)
            addListener(playerEventListener)
        }
    }

private val playerEventListener = object : Player.EventListener {
        override fun onPlayerStateChanged(
            playWhenReady: Boolean,
            playbackState: Int
        ) {

        }
    }
 
```

Steps to reproduce the issue:
I play the audio from within my app.
The notification is shown.
Open a music player, play any song

Expected Result: The Audio playing should be paused before playing the second audio.
Actual Result: Both audio files play together, and is noisy.

Note: 
The setAudioAttributes(audioAttributes, true) flag when set to true and setHandleAudioBecomingNoisy(true) takes care of this when a notification is not shown.
When the phone rings the audio gets paused and resumes when the call ends with the above implementation.

References: [https://medium.com/google-exoplayer/easy-audio-focus-with-exoplayer-a2dcbbe4640e](https://medium.com/google-exoplayer/easy-audio-focus-with-exoplayer-a2dcbbe4640e)

**Comment by angitha-das** [comment]
Updated relevant information and code blocks used.

**Comment by marcbaechinger** [comment]
I don't think using a notification should make any difference.

I can play a song with for example Spotify and then the demo app player is paused. When I start playback in the notification of the demo app,  ExoPlayer requests the audio focus again, Spotify pauses and ExoPlayer resumes playback. I can switch from one app to the other by using the controls in their notification. 

You can verify whether the audio focus is requested correctly by your and the other app with the following command:

```
adb shell dumpsys audio | more
```

At the beginning is a line `Audio Focus stack entries (last is top of stack):` which tells the package of the app that currently has the audio focus. Start with playing your app then you should see your package name in the output. Then use another app and check whether that app has the audio focus. This should tell whether the other app requests the audio focus correctly. Further down in the dumpsys output you find a line `Audio event log: focus commands as seen by MediaFocusControl` where you see a log of the apps that requested the audio focus. The passing of the audio focus should be recorded.

You can then set a breakpoint in the `AudioFocusManager` of ExoPlayer like [when the focus change arrives](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/AudioFocusManager.java#L394) and when the player requests the audio focus like [here](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/AudioFocusManager.java#L213) or [here](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/AudioFocusManager.java#L213) according to the API level. This way you can verify whether the player setup works as intended.

You can also deploy the app and reproduce the steps you've listed above. After doing that you can [capture a bug report](https://developer.android.com/studio/debug/bug-report) and upload it here or email to dev.exoplayer@gmail.com with subject "Issue #7884". This contains all the information needed to diagnose.
