### ISSUE TITLE
Question on HLS:  Rationale behind choosing the max and min buffered duration for switching up/down

### ISSUE THREAD

**Issue by Srinidhikandi** [google/ExoPlayer#790]
Hi,

I'd like to understand what is the rationale behind choosing  DEFAULT_MIN_BUFFER_TO_SWITCH_UP_MS = 5000; to switch up and  DEFAULT_MAX_BUFFER_TO_SWITCH_DOWN_MS = 20000 to switch down

Thanks in Advance!

**Comment by ojw28** [comment]
They're just set to "sensible" values.
