### ISSUE TITLE
Upgrading from 2.11.x to 2.12 questions

### ISSUE THREAD

**Issue by farnooa** [google/ExoPlayer#7901]
Hello. I am upgrading from v2.11.x into v2.12 and there are so many deprecated methods. I could not find examples and I have searched the issues but since 2.12 is a fresh update, I did not expect much. I just want to know if my changes are the proper changes. That is all.

I have changed:
```java
player.prepare(mediaSource);
```
into:
```java
player.setMediaSource(mediaSource);
player.prepare();
```

I have changed:
```java
new ProgressiveMediaSource.Factory(dataSourceFactory).createMediaSource(uri)
```
into
```java
new ProgressiveMediaSource.Factory(dataSourceFactory).createMediaSource(new MediaItem.Builder().setUri(uri).build());
```

For external subtitles, I have changed:
```java
MediaSource mediaSource = new ProgressiveMediaSource.Factory(dataSourceFactory).createMediaSource(uri);
Format textFormat = Format.createTextSampleFormat(null, MimeTypes.APPLICATION_SUBRIP, null, Format.NO_VALUE, Format.NO_VALUE, "en", null, Format.OFFSET_SAMPLE_RELATIVE);
MediaSource textMediaSource = new SingleSampleMediaSource.Factory(dataSourceFactory).createMediaSource(Uri.parse(mSubtitlesPath), textFormat, C.TIME_UNSET);
```
into:
```java
MediaSource mediaSource = new ProgressiveMediaSource.Factory(dataSourceFactory).createMediaSource(new MediaItem.Builder().setUri(uri).build());
MediaSource textMediaSource = new SingleSampleMediaSource.Factory(dataSourceFactory).createMediaSource(new MediaItem.Subtitle(uri, MimeTypes.APPLICATION_SUBRIP, "en", Format.NO_VALUE), C.TIME_UNSET);
```

If I am doing something wrong, please let me know. Thanks for your time.

**Comment by marcbaechinger** [comment]
That seems fine I think. It does not seem to compile they way you have it?

Actually, the use cases you are having seem to be supported by the new MediaItem now. We [documented how you can leverage the media item in the Developer Guide](https://exoplayer.dev/media-items.html).

```
// This works
new MediaItem.Builder().setUri(uri).build()
// but can be shorter
MediaItem.fromUri(uri);
```

For the [subtitle case you can to build a  media item](https://exoplayer.dev/media-items.html#sideloading-subtitle-tracks) and then just pass it to `player.setMediaItem(mediaItem)`. You don't have to build the media source yourself anymore. You still can, but just using the media item and passing it to the player may be more convenient. See the doc around the [playlist API](https://exoplayer.dev/playlists.html) as well.

**Comment by farnooa** [comment]
Thank you very much for the information, @marcbaechinger
