### ISSUE TITLE
how do one mp4 file and two wav files,I hope the video is playing but the sound comes from the wav file

### ISSUE THREAD

**Issue by wangxuan217** [google/ExoPlayer#7908]
How to add two audio tracks to all the way video, while ensuring audio switching and audio and video synchronization.

**Comment by icbaker** [comment]
It sounds like you might want [`MergingMediaSource`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/source/MergingMediaSource.html).

If that doesn't seem right, can you provide a bit more detail about exactly what you're trying to do: Do you have 3 separate files (2x audio + video) that you want to play simultaneously (with one or other of the audio selected), or is it something else?

**Comment by wangxuan217** [comment]
yes I have one mp4 file and two wav files,I hope the video is playing but the sound comes from the wav file,These two wav  files are similar to different tracks, The final rendering is that the video has no sound, and the sound comes from one of the two wavs.  like: test.mp4  test_m.wav  test_f.wav  @icbaker

**Comment by icbaker** [comment]
Did you try `MergingMediaSource`? 

If you did, and you're still seeing problems we can't really provide more help without more info. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that demonstrates the problem in a way that we can build locally. This could be an Android Studio project on GitHub, or zipped up and sent to dev.exoplayer@gmail.com (with subject "Issue #7908").

**Comment by wangxuan217** [comment]
thanks,I try to use MergingMediaSource ,but my video(test.mp4) has two tracks,I can't make it mute, so I can't tell if the sound came from my wav file.I use this to 
`MediaSource audiosource = new ProgressiveMediaSource.Factory(new FileDataSourceFactory()).createMediaSource(Uri.parse(videoModel.getAudio()));
MediaSource videoSource = new ProgressiveMediaSource.Factory(new FileDataSourceFactory()).createMediaSource(Uri.parse(videoModel.getVideo()));
player.prepare(new MergingMediaSource(videoSource , audiosource ), true, false);`
If there's no other way, I'll try the two-instance method, but there may be synchronized problems with video and audio. @ @icbaker

**Comment by icbaker** [comment]
Have you tried [selecting](https://exoplayer.dev/track-selection.html) the audio track you want?

You can attach an `EventLogger` and it will print the tracks it can find to logcat, so you can check the audio file is being added as a track.

We can't really provide more help without more info. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that demonstrates the problem in a way that we can build locally. This could be an Android Studio project on GitHub, or zipped up and sent to dev.exoplayer@gmail.com (with subject "Issue #7908").

**Comment by wangxuan217** [comment]
yes I do it, but viedo file has sound,I hope the sound come from my other wav file.or  How to mute  video file，my question like [https://github.com/google/ExoPlayer/issues/2990](url),I can't provide a minimal reproducible example now, because I need some time to do it. @icbaker  thanks icbaker

**Comment by icbaker** [comment]
#2990 and #2200 seem to both be about playing multiple audio tracks simultaneously - while you're asking the opposite afaict (you want just the audio from the audio file, and not from the video).

This should be possible with `MergingMediaSource` and then using the track selection infrastructure to choose the the audio track from the audio file (and thus de-selecting the audio track from the video).

**Comment by wangxuan217** [comment]
ok  I won't use track selection until now, can you give me a example or code? thanks @icbaker

**Comment by icbaker** [comment]
You can find info under "Selecting specific tracks" here: https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/trackselection/DefaultTrackSelector.html

**Comment by wangxuan217** [comment]
thanks icbaker I'm glad to tell you that with your help I've achieved what I want.Thank you again for your help. @ @icbaker
