### ISSUE TITLE
License file is missing copyright owner

### ISSUE THREAD

**Issue by fluidsonic** [google/ExoPlayer#7914]
Is the license actually valid without it?

https://github.com/google/ExoPlayer/blob/d2fa7b0217d069cda4d2588ad39e17f042093a28/LICENSE#L190

**Comment by ojw28** [comment]
The line being referenced is in a section called:

> APPENDIX: How to apply the Apache License to your work.

which is explaining how to apply the license to individual files through the repository. Note that changing this line would result in the previous paragraph explaining what to do no longer making sense.

So I think it's correct how it is. It's probably also an option to remove the appendix entirely, but I'm not sure about this, and in any case it's doing no harm. I found over 28,000 other projects that have the same as what we're doing currently. Here's an [arbitrary example](https://github.com/apache/beam/blob/master/LICENSE#L189).
