### ISSUE TITLE
Blank screen on HiKey960 50 Hz frame rate play/pause connected to 50/60Hz TV

### ISSUE THREAD

**Issue by dwhea** [google/ExoPlayer#7921]
### [REQUIRED] Issue description
Observation: ExoPlayer demo app blank screen on play / pause when playing 50 Hz video frame rate content on HiKey960 connected to 50/60 Hz capable TV.
Expected: No black screen on play / pause

Details: The DisplayManagerService logs the behavior:

**On startup display mode is 60 Hz (modeId 6)**
09-15 05:03:47.802  2828  2848 I DisplayManagerService: Display device changed: DisplayDeviceInfo{"Built-in Screen": uniqueId="local:0", 1920 x 1080, modeId 6, defaultModeId 6, supportedModes [{id=1, width=800, height=600, fps=60.31654}, {id=2, width=1280, height=720, fps=60.0}, {id=3, width=1920, height=1080, fps=24.0}, {id=4, width=1920, height=1080, fps=50.0}, {id=5, width=1280, height=720, fps=50.0}, {id=6, width=1920, height=1080, fps=60.0}], colorMode 0, supportedColorModes [0], HdrCapabilities HdrCapabilities{mSupportedHdrTypes=[], mMaxLuminance=500.0, mMaxAverageLuminance=500.0, mMinLuminance=0.0}, allmSupported false, gameContentTypeSupported false, density 160, 320.0 x 320.0 dpi, appVsyncOff 1000000, presDeadline 16666667, touch INTERNAL, rotation 0, type INTERNAL, address {port=0}, deviceProductInfo null, state ON, FLAG_DEFAULT_DISPLAY, FLAG_ROTATES_WITH_CONTENT, FLAG_SECURE, FLAG_SUPPORTS_PROTECTED_BUFFERS}

**When playing 50 Hz content, the display switches to 50Hz (modeId 4)**
09-15 05:03:17.904  2828  2848 I DisplayManagerService: Display device changed: DisplayDeviceInfo{"Built-in Screen": uniqueId="local:0", 1920 x 1080, modeId 4, defaultModeId 6, supportedModes [{id=1, width=800, height=600, fps=60.31654}, {id=2, width=1280, height=720, fps=60.0}, {id=3, width=1920, height=1080, fps=24.0}, {id=4, width=1920, height=1080, fps=50.0}, {id=5, width=1280, height=720, fps=50.0}, {id=6, width=1920, height=1080, fps=60.0}], colorMode 0, supportedColorModes [0], HdrCapabilities HdrCapabilities{mSupportedHdrTypes=[], mMaxLuminance=500.0, mMaxAverageLuminance=500.0, mMinLuminance=0.0}, allmSupported false, gameContentTypeSupported false, density 160, 320.0 x 320.0 dpi, appVsyncOff 1000000, presDeadline 20000000, touch INTERNAL, rotation 0, type INTERNAL, address {port=0}, deviceProductInfo null, state ON, FLAG_DEFAULT_DISPLAY, FLAG_ROTATES_WITH_CONTENT, FLAG_SECURE, FLAG_SUPPORTS_PROTECTED_BUFFERS}

https://developer.android.com/guide/topics/media/frame-rate?hl=id mentions 

"The platform will only switch display modes in response to a call to setFrameRate() if the mode switch is lightweight and unlikely to be noticeable to the user. If the app prefers to switch the display refresh rate even if it requires a heavy mode switch (for example, on an Android TV device), use preferredDisplayModeId."

Is the "heavy mode switch" that I'm seeing on HiKey960 happening because the platform thinks HiKey960 switching is lightweight and unlikely to be noticeable to a user because platform isn't aware that HiKey960 is a HDMI output ("Android TV") device? NOTE: I am building the HiKey960 "phone" target hikey960-userdebug not hikey960_tv-userdebug because the HiKey960 TV target on Android 11 is unstable.

Also screen capture software (https://github.com/Genymobile/scrcpy) does not show any blank screen issues; the blank screen is on TV due to HDMI renegotiation.

### [REQUIRED] Reproduction steps
See issue description above.

### [REQUIRED] Link to test content
Any 50 Hz content on affected device will reproduce the issue. 

### [REQUIRED] A full bug report captured from the device
Will email the bug report to dev.exoplayer@gmail.com using a subject in the format "Issue #1234"

### [REQUIRED] Version of ExoPlayer being used
origin/dev-v2 (12a29e3026b2efa289a44bfe08fd61b2d11b7a68, 13 Sep 2020)

### [REQUIRED] Device(s) and version(s) of Android being used
HiKey960 Android 11.

**Comment by icbaker** [comment]
This seems like a question more for the manufacturers of the HiKey960 device - have you reached out them?

**Comment by dwhea** [comment]
Do you have any pointers for how the platform determines if the mode switch is "lightweight and unlikely to be noticeable to the user"?

**Comment by icbaker** [comment]
We don't have the platform expertise to answer that I'm afraid.

**Comment by icbaker** [comment]
Closing this as it's not really an ExoPlayer issue.
