### ISSUE TITLE
noticeable gap when play videos using ConcatenatingMediaSource 

### ISSUE THREAD

**Issue by yangcheng** [google/ExoPlayer#7924]
### [REQUIRED] Issue description
When using ConcatenatingMediaSource to play 2 videos, there is a notable gap/jitter when load second video, the video seems skipping ~100-200ms, and sometimes there is flash over the screen. 

When play the second video separately without a ConcatenatingMediaSource, the startup jitter is  still noticeable but shorter. There is no flash

### [REQUIRED] Reproduction steps
put the urls in demo app's playlist section

### [REQUIRED] Link to test content
will send over email

### [REQUIRED] A full bug report captured from the device
send over email

### [REQUIRED] Version of ExoPlayer being used
2.11.7

### [REQUIRED] Device(s) and version(s) of Android being used
pixel 3 , android 10

**Comment by yangcheng** [comment]
I did some more testing, the issue is isolated with hevc, after I convert hevc to webm (similar quality and similar file size), there is no gap.

**Comment by kim-vde** [comment]
I think there are some issues in the video sample timestamps of both files:
1. The ctts box has version 0 and has negative offsets, which is not allowed.
2. The composition timestamps seem incorrect. For example, some samples have a timestamp smaller than the timestamp of the key sample preceding it. This might be a consequence of 1.
3. The edit list media time does not correspond to a key sample. As a result, the samples from that time are ignored until the next key sample.

**Comment by yangcheng** [comment]
thanks!
