### ISSUE TITLE
How to delete single cached file 

### ISSUE THREAD

**Issue by noman-noor** [google/ExoPlayer#7925]
I m using exo player v2.12.0, with offline support, i m using **SimpleCache** and Download manager for offline support. Now i need to delete single track from cache so that whenever user play with same url it should be download again from server

**Comment by icbaker** [comment]
Did you try [`DownloadService#sendRemoveDownload()`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/offline/DownloadService.html#sendRemoveDownload-android.content.Context-java.lang.Class-java.lang.String-boolean-)?

**Comment by noman-noor** [comment]
yes i have tried both DownloadService#sendRemoveDownload() and DownloadService.removeDownlaod() but its still playing offline, it should not play offline after removing the downloads

**Comment by icbaker** [comment]
We can't really provide more help without more info. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that demonstrates the problem in a way that we can build locally. This could be an Android Studio project on GitHub, or zipped up and sent to dev.exoplayer@gmail.com (with subject "Issue #7925").
