### ISSUE TITLE
Live video rewind issue

### ISSUE THREAD

**Issue by kartikdrag** [google/ExoPlayer#7926]
When I play live video url (dash/hls) then seek bar is misbehaving. It mean I can't go back or seek to particular time period.

**Comment by icbaker** [comment]
We need far more information to be able to help you.

Please copy/paste the [issue template](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md) and fill in **all** the required sections.
