### ISSUE TITLE
Extending ProgressiveMediaSource library classes

### ISSUE THREAD

**Issue by mastermj94** [google/ExoPlayer#7933]
I'd like to get the ProgressiveMediaSource as parent and add some custom functionality to it and i like to do it without editing the core so i tried to do this with implementing MediaSource interface and use instance of ProgressiveMediaSource to add it s functions here is my code:

```
import android.os.Handler
import com.google.android.exoplayer2.MediaItem
import com.google.android.exoplayer2.drm.DrmSessionEventListener
import com.google.android.exoplayer2.source.MediaPeriod
import com.google.android.exoplayer2.source.MediaSource
import com.google.android.exoplayer2.source.MediaSourceEventListener
import com.google.android.exoplayer2.source.ProgressiveMediaSource
import com.google.android.exoplayer2.upstream.Allocator
import com.google.android.exoplayer2.upstream.TransferListener
import java.util.*

class MediaSourceDecorator(var progressiveMediaSource: ProgressiveMediaSource) : MediaSource {

    var callers: ArrayList<MediaSource.MediaSourceCaller> = ArrayList()

    override fun prepareSource(
        caller: MediaSource.MediaSourceCaller,
        mediaTransferListener: TransferListener?
    ) {

        this.callers.add(caller)
       return progressiveMediaSource.prepareSource(caller, mediaTransferListener)
    }

    override fun releaseSource(caller: MediaSource.MediaSourceCaller) {
        progressiveMediaSource.releaseSource(caller)
    }

    override fun addDrmEventListener(handler: Handler, eventListener: DrmSessionEventListener) {
        progressiveMediaSource.addDrmEventListener(handler, eventListener)
    }

    override fun removeEventListener(eventListener: MediaSourceEventListener) {
        progressiveMediaSource.removeEventListener(eventListener)
     }

    override fun createPeriod(
        id: MediaSource.MediaPeriodId,
        allocator: Allocator,
        startPositionUs: Long
    ): MediaPeriod {
        return progressiveMediaSource.createPeriod(id, allocator, startPositionUs)
    }

    override fun enable(caller: MediaSource.MediaSourceCaller) {
        progressiveMediaSource.enable(caller)


    }

    override fun removeDrmEventListener(eventListener: DrmSessionEventListener) {
        progressiveMediaSource.removeDrmEventListener(eventListener)

    }

    override fun getMediaItem(): MediaItem {
       return progressiveMediaSource.mediaItem
    }

    override fun releasePeriod(mediaPeriod: MediaPeriod) {
        progressiveMediaSource.releasePeriod(mediaPeriod)
    }

    override fun maybeThrowSourceInfoRefreshError() {
        progressiveMediaSource.maybeThrowSourceInfoRefreshError()
    }

    override fun addEventListener(handler: Handler, eventListener: MediaSourceEventListener) {
        progressiveMediaSource.addEventListener(handler, eventListener)
    }

    override fun disable(caller: MediaSource.MediaSourceCaller) {
        progressiveMediaSource.disable(caller)
    }
} 
```

So it work well when i use it in my code as single mediaSource with SimpleExoPlayer but when i want use it with more than one media and merge them together with MergingMediaSource() the player stuck in loading and no error appears (Nothing) with debug i realised original ProgressiveMediaSource calls different methods than my class I think it s bug can someone please help me

**Comment by icbaker** [comment]
`ProgressiveMediaSource` is `final`, you can't extend it. As you've said you've implemented `MediaSource` using a `ProgressiveMediaSource` instance as a delegate.

Can you provide more info about how you're constructing the `MergingMediaSource`, and what you mean exactly by this:
> with debug i realised original ProgressiveMediaSource calls different methods than my class

We can't really provide more help than that without more info. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that demonstrates the problem in a way that we can build locally. This could be an Android Studio project on GitHub, or zipped up and sent to dev.exoplayer@gmail.com (with subject "Issue #1234").

**Comment by tonihei** [comment]
When forwarding to another `MediaSource` class, you are probably best off to extend `CompositeMediaSource<Void>` similar to how the deprecated [`ExtractorMediaSource`](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/source/ExtractorMediaSource.java) is already delegating to `ProgressiveMediaSource`.

**Comment by mastermj94** [comment]
Here is my MergingMediaSource:
```
var uri = Uri.fromFile(File("/storage/emulated/0/Download/audio_eng.mp4"))
        var uriTwo = Uri.fromFile(File("/storage/emulated/0/Download/audio_per.mp4"))
        var uriThree = Uri.fromFile(File("/storage/emulated/0/Download/video_360.mp4"))
val factory: DataSource.Factory = DefaultDataSourceFactory(
            this,
            Util.getUserAgent(this, "myApp"),
            null
        )

val mediaSource = MediaSourceDecorator(ProgressiveMediaSource.Factory(factory)
            .createMediaSource(MediaItem.fromUri(uri)))
val mediaSourceTwo = MediaSourceDecorator(ProgressiveMediaSource.Factory(factory)
            .createMediaSource(MediaItem.fromUri(uriTwo)))
val mediaSourceThree = MediaSourceDecorator(ProgressiveMediaSource.Factory(factory)
            .createMediaSource(MediaItem.fromUri(uriThree)))

val mergeMedia = MergingMediaSource(mediaSource, mediaSourceTwo, mediaSourceThree)
        player.setMediaSource(mergeMedia)
        player.prepare()
        player.playWhenReady = true
```
And it works when I pass one by one to player.setMediaSource but when I pass mergeMedia like this code player dont work.
And in debug I set some break points in library classes and my MediaSourceDecorator had different behavior than ProgressiveMediaSource so I conclusion that my class doesn't call some methods in MergingMediaSource
@icbaker

**Comment by icbaker** [comment]
Nothing you've posted jumps out as glaringly wrong. Without being able to reproduce the problem we can't help further.

> Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that demonstrates the problem in a way that we can build locally. This could be an Android Studio project on GitHub, or zipped up and sent to [dev.exoplayer@gmail.com](mailto:dev.exoplayer@gmail.com) (with subject "Issue #1234").
