### ISSUE TITLE
2.12.0 PlaybackParameters skipSilence disappeared?

### ISSUE THREAD

**Issue by TacoTheDank** [google/ExoPlayer#7939]
### [REQUIRED] Searched documentation and issues
I've looked in the 2.12.0 release notes, and looked through https://exoplayer.dev/.

### [REQUIRED] Question
Where did the skipSilence parameter in PlaybackParameters go? There's no documentation anywhere for this that I've found. It's just vanished.

I looked at https://github.com/google/ExoPlayer/issues/7864, and saw a related thing. Are we supposed to now use `SimpleExoPlayer.setSkipSilenceEnabled`?

If this is the case, could you add documentation for its disappearance and the replacement?

**Comment by icbaker** [comment]
Thanks for flagging that this isn't clearly documented. Yes the intention is to use `SimpleExoPlayer.setSkipSilenceEnabled` as you've said.

Info about this was added to the 'unreleased' section of the release notes back in March https://github.com/google/ExoPlayer/commit/f794a798520ef8cb0029666ee310af12e335b757

But it looks like it was removed again accidentally when prepping for the 2.12.0 release: https://github.com/google/ExoPlayer/commit/94cff6ba506dc60689227ebe00cd3ea55c66c5ad

(the accidental removal is related to the fact we re-added PlaybackParameters, but kept skipSilence separate: https://github.com/google/ExoPlayer/commit/74c493f51e1b0a86ce31aa8290d304696ae1a57d)

@marcbaechinger's going to re-add it to the 2.12.0 release notes - sorry for the trouble!

**Comment by TacoTheDank** [comment]
It's ok. Thanks for fixing this! :)
