### ISSUE TITLE
How to keep the buffer after  seekTo() called.

### ISSUE THREAD

**Issue by AlanCheen** [google/ExoPlayer#794]
After calling seekTo  the buffer will be cleared and rebuffer again.
Suppose that user has buffered 100% of the video then he just wanna look backword few seconds ,but the buffer is cleared.I think it's not a good UX and wasting of resource(power,cpu,data stream).
Is there a way to keep the buffer or a good way for better UX?
Thanks  in advance!

**Comment by ojw28** [comment]
In most cases we do retain the buffer when seeking forward into it. We do not retain any buffer behind the current playback position. Except in the special case where the media is buffered to the end, it's better to discard media behind the current playback position in order to buffer further ahead into the future.

**Comment by AlanCheen** [comment]
I know,but i really need this function ,what should do?
I saw the code in `HlsSampleSource`:
```Java
public void seekToUs(long positionUs) {
    Log.d(TAG, "seekToUs() called with: " + "positionUs = [" + positionUs + "]");
    Assertions.checkState(prepared);
    Assertions.checkState(enabledTrackCount > 0);

    long currentPositionUs = isPendingReset() ? pendingResetPositionUs : downstreamPositionUs;

    downstreamPositionUs = positionUs;
    lastSeekPositionUs = positionUs;
    Log.d(TAG, "seekToUs: currpos:" + currentPositionUs+";downstreamPositionUs:"+downstreamPositionUs+";lastSeekPositionUs:"+lastSeekPositionUs);

    if (currentPositionUs == positionUs) {
      return;
    }

    // TODO: Optimize the seek for the case where the position is already buffered.
    downstreamPositionUs = positionUs;
    for (int i = 0; i < pendingDiscontinuities.length; i++) {
      pendingDiscontinuities[i] = true;
    }
    restartFrom(positionUs);
  }
```
You left a comment:`    // TODO: Optimize the seek for the case where the position is already buffered.
`

**Comment by ojw28** [comment]
The todo is for optimizing forward seeking specifically for HLS. We've already done this for DASH, SmoothStreaming and regular media playback, where such optimization is significantly easier. We'll get round to it eventually, but it's considered low priority. In the meantime, you'll either have to live with the existing behavior or work out how to implement what you need yourself.

Note that we have no plans to retain buffer behind the current playback position (and that the todo is only referring to the forward direction).

**Comment by AlanCheen** [comment]
Yeah,i only use HLS for now ,so i just care about HLS.
I will work out it by myself.
I will be very appreciate if you give me some advice about how to implement it because i have no idea about this such as which class i should modified.. (I am fresh about Media)
Thanks very much!

**Comment by cre8ivejp** [comment]
@AlanCheen hey did you figure out how to retain it?

**Comment by AlanCheen** [comment]
Hi @cre8ivejp,
Im sorry , we cut this requirement already.

**Comment by sonikasoni** [comment]
Is it avaialbe to keep the buffer after seekTo() in exoplayer? I am looking for this.
Please help me, Thanks

**Comment by moroz0v** [comment]
@ojw28 Has this been implemented for `HLS`? Could this be prioritized? We need this! Thank you
