### ISSUE TITLE
durationUs error caused by different track timescale

### ISSUE THREAD

**Issue by XiaoLongTX** [google/ExoPlayer#7941]
### [REQUIRED] Issue description
I have a video that contains two tracks. The timescale of one track is 1000, the timescale of the other track is 48000, and the movieTimescale is 1000. As a result, the video time I get is 48 times the real video time.

### [REQUIRED] Reproduction steps
This problem will inevitably occur when using ExoPlayer to play the video file I sent to dev.exoplayer@gmail.com.

### [REQUIRED] Version of ExoPlayer being used
latest

### [REQUIRED] Device(s) and version(s) of Android being used
Device independent

**Comment by XiaoLongTX** [comment]
PR[#7923](https://github.com/google/ExoPlayer/pull/7923)
@kim-vde kim

**Comment by kim-vde** [comment]
What subject did you use in your email? You should use "Issue #7941". Thanks.

**Comment by XiaoLongTX** [comment]
@kim-vde I hava resend mail with subject Issue #7941

**Comment by kim-vde** [comment]
In the case of your file, the tracks duration are derived from the tkhd boxes. One track has duration 41906 while the other has duration 2010112. According to the specification, these durations are given in the timescale indicated in the mvhd box, which is 1000 in this case. The duration of the second file should therefore be updated in order for the file to be valid.
