### ISSUE TITLE
The video blocked when audio stop(The duration of audio track is less than video)?

### ISSUE THREAD

**Issue by friskyliu** [google/ExoPlayer#7943]
I played a video(mp4 format),  the audio track duration is 6 seconds and the video duration is 40 seconds.  When it is played to 6 seconds, the video will be blocked。

**Comment by icbaker** [comment]
Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md). If you're unable to share bug reports or test content publicly, please send them to dev.exoplayer@gmail.com using a subject "Issue #7943". Please also update this issue to indicate you’ve done this.

To debug this we certainly need:
* Sample media that demonstrates the problem
* The version of ExoPlayer and Android used

**Comment by friskyliu** [comment]
[ https://github.com/friskyliu/exoplayerbug7943.git ] is the demo for Issue #7943

Exoplayer version：2.12.0
Android version: Android 9.0

**Comment by icbaker** [comment]
Thanks for the app link - I can repro the behaviour you describe when running your app.

However when playing the [same media](https://github.com/friskyliu/exoplayerbug7943/raw/master/app/src/main/assets/error.mp4) in the demo app at 2.12.0 it plays to the end of the video (i.e. I don't see the behaviour you describe).

So it looks like it's something about the way your app is integrating ExoPlayer. I had a scan through the code and spotted these possible culprits:
* `player.setRepeatMode(Player.REPEAT_MODE_ONE)`: Changed the demo app to do this - didn't cause problems.
* `player.setSeekParameters(SeekParameters.EXACT)`: Changed the demo app to do this - didn't cause problems.

Passing this over to @andrewlewis to take a look.

**Comment by friskyliu** [comment]
It seems the code __setLoadControl__ caused the problem. After delete LoadControl, it plays to the end.

Is the params wrong when using LoadControl?


```
        this.exoPlayer = new SimpleExoPlayer.Builder(context)
            .setTrackSelector(trackSelector)
    //        .setLoadControl(loadControl)   
            .setClock(Clock.DEFAULT)
            .build();
```

**Comment by icbaker** [comment]
Ah good find. I tried swapping in some different values for `MAX_BUFFER_MS` in your app. I found:
* 50_000 allowed the video to play to completion reliably
* 15_000 allowed it to play a few times, but it would eventually get stuck

I was able to repro in the demo app by including your LoadControl and the repeat mode (it didn't repro without the repeat mode):
```
player =
    new SimpleExoPlayer.Builder(/* context= */ this, renderersFactory)
        .setMediaSourceFactory(mediaSourceFactory)
        .setTrackSelector(trackSelector)
        .setLoadControl(
            new DefaultLoadControl.Builder()
                .setBufferDurationsMs(
                    /* minBufferMs= */ 5_000,
                    /* maxBufferMs= */ 10_000,
                    /* bufferForPlaybackMs= */ 1500,
                    /* bufferForPlaybackAfterRebufferMs= */ 3500)
                .build())
        .build();
player.setRepeatMode(Player.REPEAT_MODE_ONE);
```

cc @tonihei who might also have some thoughts

**Comment by tonihei** [comment]
Thanks for all the reproduction details - it looks as if this is a bug that got introduced as part of https://github.com/google/ExoPlayer/commit/652c2f9c188bf9d9d6e323ff5333e5026454a082. We'll provide a fix for that.
