### ISSUE TITLE
Missing duration while using FLAG_ENABLE_INDEX_SEEKING flag on some files

### ISSUE THREAD

**Issue by ghost** [google/ExoPlayer#7949]
### [REQUIRED] Issue description
For some of my MP3 files when using the new FLAG_ENABLE_INDEX_SEEKING flag I see no duration and seeking is not possible at all (greyed out seekbar). A few of my files are affected while the rest work with the flag without issues.

### [REQUIRED] Reproduction steps
Perform the following

```java
DefaultExtractorsFactory extractorsFactory = new DefaultExtractorsFactory();
extractorsFactory.setMp3ExtractorFlags(Mp3Extractor.FLAG_ENABLE_INDEX_SEEKING);
```

If I skip the second line all files display the duration and allow seek.
### [REQUIRED] Link to test content
Here is a link to one of the files with issues:
https://ufile.io/1usbf4c1

### [REQUIRED] A full bug report captured from the device
No issues reported on logs.

### [REQUIRED] Version of ExoPlayer being used
2.12.0

### [REQUIRED] Device(s) and version(s) of Android being used
Device: Moto G 1st Gen OS: 5.1 (Lollipop). I do not have other devices.

Edit: Added mirrors to the post below.

**Comment by kim-vde** [comment]
I get an error "ufile.io refused to connect" when trying to open the link you provided. Can you check the link or send the content directly by email to dev.exoplayer@gmail.com using subject "Issue #7949"? Please also update this issue to indicate you’ve done this.

**Comment by ghost** [comment]
@kim-vde Thanks for checking my issue out. The link works fine at my end. Though, here are three mirrors:

https://www36.zippyshare.com/v/SjSJHnha/file.html
http://ge.tt/2oRtMM73
http://www.filedropper.com/test_20504

Use either of the links. They are all the same file.

Regards.

**Comment by kim-vde** [comment]
The index seeker (enabled by `FLAG_ENABLE_INDEX_SEEKING`) updates the duration if it is incorrect or unset once the whole file has been parsed. You can see that, if you play the file and wait until you are close to the end, the duration will have appeared.

Before that, the duration is generally retrieved from the metadata provided in a Xing header, VBRI header or ID3 MLLT frame. As the file you provided does not contain any of these, the MP3 extractor can only compute the duration by parsing the whole file.

Your file contains a TLEN ID3 tag (indicating the duration) though. I'll update the `Mp3Extractor` so that it retrieves this duration.

**Comment by ghost** [comment]
Thanks in advance for the update. Though, I do not get it. Would `FLAG_ENABLE_INDEX_SEEKING` allow me to provide an exact seek on the user moving the thumb on seekbar or do I have to wait for the file to be fully played before the user is enabled to do so?

**Comment by kim-vde** [comment]
The user will be able to seek before the file is completely parsed.

**Comment by ghost** [comment]
> 
> 
> The user will be able to seek before the file is completely parsed.

Sorry for iterating but will it be an exact seek or normal seek, in this case (my test file).

**Comment by kim-vde** [comment]
What do you mean by "normal seek"? Seeking will use the index seeker, which means that seeking will be precise. Indeed, the index will store all the samples that are at least 0.1 second apart.
