### ISSUE TITLE
Doesn't cache TS files

### ISSUE THREAD

**Issue by Serkan-Karacelikler** [google/ExoPlayer#7952]
Why doesn't it cache live streams with TS extension? 
Nothing appears in the Progress bar.
Is it necessary to write a different code for publications with Ts extension?
The class I use for TS files: ExtractorsFactory

```
ExtractorsFactory extractorsFactory = new DefaultExtractorsFactory();
mediaSource = new ExtractorMediaSource(uri, dataSourceFactory, extractorsFactory, mainHandler, null);
```

**Comment by marcbaechinger** [comment]
Assuming that `dataSourceFactory` is  `CacheDataSource` I would assume that should work. let me know if it is a `CacheDataSource`. If it's not [you can refer to the dev guide](https://exoplayer.dev/customization.html#caching-data-loaded-from-the-network).

Aside: `ExtractorMediaSource` is pretty old and deprecated. I recommend updating to the latest version of ExoPlayer and use `ProgressiveMediaSource` which is a drop-in replacement for the `ExtractorMediaSource`.

**Comment by Serkan-Karacelikler** [comment]
> Varsayılırsa `dataSourceFactory`olduğunu `CacheDataSource`bunu çalışmalıdır varsayılabilir. bir `CacheDataSource`. Değilse [, geliştirici kılavuzuna başvurabilirsiniz](https://exoplayer.dev/customization.html#caching-data-loaded-from-the-network) .
> 
> Kenara: `ExtractorMediaSource`oldukça eski ve kullanımdan kaldırıldı. ExoPlayer'ın en son sürümüne güncellemenizi `ProgressiveMediaSource`ve `ExtractorMediaSource`.

Thanks.
