### ISSUE TITLE
How to play drm file Using Raw Key

### ISSUE THREAD

**Issue by GongKuiJun** [google/ExoPlayer#7953]
I use "shaka-packager" to generate DRM video, Using Raw Key Like This:
packager input=h264_main_720p_3000.mp4,stream=video,output=h264_720p.mp4,drm_label=HD --enable_raw_key_encryption --keys label=HD:key_id=6d76f25cb17f5e16b8eaef6bbf582d8e:key=cb541084c99731aef4fff74500c12ead --mpd_output h264.mpd

I want to know how to play it through Exoplayer

**Comment by Samrobbo** [comment]
For information on playing DRM content with ExoPlayer, see https://exoplayer.dev/drm.html 

There is also a vast amount of information on getting started with ExoPlayer at https://exoplayer.dev 

Please look into this documentation, and reply on this issue if you are still having problems afterwards.
