### ISSUE TITLE
Logs for HTTP Connections?

### ISSUE THREAD

**Issue by wishy-viewlift** [google/ExoPlayer#7957]
Is there a way I can get logs for network calls like downloading HLS segment or segment URLs ?

**Comment by AquilesCanta** [comment]
You can inject an [AnalyticsListener](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/analytics/AnalyticsListener.html) (like ExoPlayer's [EventLogger](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/util/EventLogger.java)) which has callbacks pertaining network requests, like [onLoadStarted](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/analytics/AnalyticsListener.html#onLoadStarted-com.google.android.exoplayer2.analytics.AnalyticsListener.EventTime-com.google.android.exoplayer2.source.LoadEventInfo-com.google.android.exoplayer2.source.MediaLoadData-). Does this work for you?
