### ISSUE TITLE
Notification bar is no longer responsive during playback upon loss of Internet

### ISSUE THREAD

**Issue by tosam144** [google/ExoPlayer#7958]
I am streaming mp3 using Exoplayer. When the Internet connection is lost during playback, my Player UI works well because I have implmemented `preparePlayback`:

```
    @Override
    public void preparePlayback() {
        if (AudioPlayerService.getPlayer() != null) {
            AudioPlayerService.getPlayer().prepare();
        }
    }
```

This works as expected. **My question now is: Is there a similar method for the notification?** At the moment, when Internet is lost during playback and comes back on, all my notification controls (play, pause, skip) are not longer responsive, that is, clicking on them has no effect whatsoever. How can I make the notifcation bar the same as the Player UI? Thanks!

**Comment by marcbaechinger** [comment]
Do you have a `PlaybackPreparer` registered with `PlayerNotificationManager.setPlaybackPreparer(PlaybackPreparer)`? If this is the case, then the [playback preparer will be called when the user hits the play button in the notification](https://github.com/google/ExoPlayer/blob/a15d01d36f8334293b6a1a19d6e66a77994bb696/library/ui/src/main/java/com/google/android/exoplayer2/ui/PlayerNotificationManager.java#L1379).

Without the playback preparer in place, the notification should be removed when an error occurs. This means that the player transitions to `STATE_IDLE` and the [notification is removed](https://github.com/google/ExoPlayer/blob/release-v2/library/ui/src/main/java/com/google/android/exoplayer2/ui/PlayerNotificationManager.java#L1040) until the player transitions out of `STATE_IDLE` again.

**Comment by tosam144** [comment]
Thank you @marcbaechinger, that was the method I was looking for. It is working now.
