### ISSUE TITLE
How to set mimetype using Exoplayer IMA extension

### ISSUE THREAD

**Issue by krackjack234** [google/ExoPlayer#7961]
### [REQUIRED] How can we set the mimetype using exoplayer IMA extension
If we use the IMA Sdk directly, we can set the mime type using the below api:

```
 List<String> mimes = new ArrayList<>();
 mimes.add("video/mp4"); //client wants only mp4 creatives to be rendered
   adsRenderingSettings.setMimeTypes(mimes);
```

However if we use IMA extension we are not able to use this feature.
We see the below code in exoplayer IMA extension to set mime types

```
public void setSupportedContentTypes(@C.ContentType int... contentTypes) {
    List<String> supportedMimeTypes = new ArrayList<>();
    for (@C.ContentType int contentType : contentTypes) {
      // IMA does not support Smooth Streaming ad media.
      if (contentType == C.TYPE_DASH) {
        supportedMimeTypes.add(MimeTypes.APPLICATION_MPD);
      } else if (contentType == C.TYPE_HLS) {
        supportedMimeTypes.add(MimeTypes.APPLICATION_M3U8);
      } else if (contentType == C.TYPE_OTHER) {
        supportedMimeTypes.addAll(
            Arrays.asList(
                MimeTypes.VIDEO_MP4,
                MimeTypes.VIDEO_WEBM,
                MimeTypes.VIDEO_H263,
                MimeTypes.AUDIO_MP4,
                MimeTypes.AUDIO_MPEG));
      }
    }
    this.supportedMimeTypes = Collections.unmodifiableList(supportedMimeTypes);
  }

```

Using the above method we cannot set a specific mime type like only video/mp4. 
Also is the content type mentioned here refers to type of ad creative?

Ideally it will be better to expose all the getters and setters of IMA library so that user of ima extension can get the full benefit of ima library.

Is this a feature missing in ima extension now?

**Comment by andrewlewis** [comment]
> Using the above method we cannot set a specific mime type like only video/mp4.

Would it meet your needs if there were a setter for that MIME types to include for `C.TYPE_OTHER` content types on `ImaAdsLoader.Builder`? The DASH/HLS types would continue to work in the same way.

> Also is the content type mentioned here refers to type of ad creative?

Yes.

> Ideally it will be better to expose all the getters and setters of IMA library so that user of ima extension can get the full benefit of ima library.

Not all getters/setters make sense though as the IMA extension places extra restrictions (`setEnablePreloading` comes to mind -- the extension relies on this being enabled). I think the important ones are there already but please let me know if there are other cases you want to override.

> Is this a feature missing in ima extension now?

I think so. I'll mark this as an enhancement. If you reply with an answer to my question above we should be able to address it soon.
