### ISSUE TITLE
onNotificationCancelled isn't called on api 30

### ISSUE THREAD

**Issue by grosalex** [google/ExoPlayer#7964]
Hey, 
I'm developping an audio app and "onNotificationCancelled" isn't called when targeting and android 11 devices or emulator when pausing soundtrack  and dismissing the player notification ? It's well called from android 4.4 to 10.
I've been looking for changes about that but found nothing sorry, so I'm asking here.

Regards,

**Comment by marcbaechinger** [comment]
Thanks for flagging this. I see the same behavior. We are setting a pending intent to [NotificationCompat.Builder.setDeleteIntent](https://developer.android.com/reference/androidx/core/app/NotificationCompat.Builder#setDeleteIntent(android.app.PendingIntent)) of the builder, which results in a broadcast of that intent with action `com.google.android.exoplayer.dismiss`. With API 30 we don't receive this broadcast and can't call `onNotificationCancelled` accordingly.

I marked this as a bug for now. We call an androidx API of which we expect to then broadcast this intent. It may be that an update is needed to make it work on the  API 30. However, we need to investigate this and we will update this issue accordingly.

**Comment by marcbaechinger** [comment]
With API 30 Android creates a larger media player in a carousel for apps with media notifications and a media session token attached to it. As a consequence of this change, swiping away a media notification no longer fires a pending intent. Hence the `onNotificationCancelled` callback is no longer called on API 30, when the user swipes away a notification with a media session token. 

For API levels 29 and lower and if used within a foreground service, we still recommend to listen to this event and terminate the service at this moment to free resources. Starting with API 30 you can leave it to the system to terminate your service after a while.

May I ask what your app is doing within this callback? Do you just terminate the service?

**Comment by grosalex** [comment]
Hey Marc, thanks for your answer.
Like you said I was using it to terminate my service.

**Comment by marcbaechinger** [comment]
Thanks for letting know. That's fine. Keep it as it is.  :)
