### ISSUE TITLE
Playing MOV file but no sound 

### ISSUE THREAD

**Issue by greatktv** [google/ExoPlayer#7967]
### [REQUIRED] Issue description
Play a Mov url, there is video but no sound

### [REQUIRED] Reproduction steps
just use our own app to play the mov url

### [REQUIRED] Link to test content
http://shinemov.joyk.com.cn/free/647753.mov
http://shinemov.joyk.com.cn/free/900318.mov

### [REQUIRED] A full bug report captured from the device
just no sound

### [REQUIRED] Version of ExoPlayer being used
https://github.com/Jenjen1324/ExoPlayer/tree/hls-multi-track
using this branch, to enable changing multi-tracks in m3u8.
And we also integreted the ffmpeg mp2 decoder.

### [REQUIRED] Device(s) and version(s) of Android being used
Android 6 TV/Box

**Comment by Samrobbo** [comment]
A patch will be available shortly that corrects this issue.

**Comment by greatktv** [comment]
> A patch will be available shortly that corrects this issue.

https://github.com/google/ExoPlayer/commit/b293cf2a76b6181fd8c4261c74d5a705f24eb739
Is this the patch for same issue?

**Comment by Samrobbo** [comment]
851ca20 is the patch i meant. Reply on this issue if there is still a problem.
