### ISSUE TITLE
 ExoPlayer PlayerView flickers in dragDown transition using Motion Layout

### ISSUE THREAD

**Issue by Prateek-Kapoor** [google/ExoPlayer#7971]
### Documentation Referred
https://exoplayer.dev/ui-components.html

### Description
My requirement is to dock/move the Exo Player view from the top and the bottom right (not ribbon, but what youtube used to do a few years back).

For achieving the scenario I am using MotionLayout providing required **dragDown** animation in **layoutDescription** property(PFA the files). However, while dragging down the player from its top position to the bottom position, the player view shakes/flickers and a black screen is visible in the background, the flickers amount vary from device to device, video flickers more in low-end devices(LG-H860) and less in a good configuration devices. (OnePlus 7, Poco F1). 

As per the documention

> SurfaceView should therefore be preferred over TextureView where possible. TextureView should be used only if SurfaceView does not meet your needs. One example is where smooth animations or scrolling of the video surface is required prior to Android N, as described below. For this case, it’s preferable to use TextureView only when SDK_INT is less than 24 (Android N) and SurfaceView otherwise.
> 
> And
> 
> SurfaceView has a number of benefits over TextureView for video playback:
> - Significantly lower power consumption on many devices.
> - More accurate frame timing, resulting in smoother video playback.
> - **Support for secure output when playing DRM protected content**

I have 2 questions

- As per documentation, we need to use **texture_view** as **app:surface_type** to solve this below API 24, Is it the only feasible solution? Because as mentioned in the above documentation that _SurfaceView Support for secure output when playing DRM protected content._

- During animation the player view still flickers in devices with API 24 and above, Do we need to add some other attribute for preventing this, or using texture_view is the only solution?  

The videos for the below-mentioned devices can be found at - https://drive.google.com/drive/folders/1--q02o5N-wfEPBrqMe8sThjo7CqvIds5?usp=sharing

- LG-H860 OS 6.0.1  (using surface_view) 
- POCO F1 OS MIUI 11.0.9.0 based on Android version 10  API (using surface_view) 
- Samsung Tab SM-T3  (OS 7.1.1)  (using surface_view) 

### Dependencies used:- 
- Exo player - implementation 'com.google.android.exoplayer:exoplayer:2.11.8' 
- Constraint layout - implementation "androidx.constraintlayout:constraintlayout:2.0.1"

### XML classes:- 
- PFA Main class XML : actvity_main 
- PFA Transition XML :  scene_drag_down_transition

[activity_main.txt](https://github.com/google/ExoPlayer/files/5266653/activity_main.txt)

[scene_drag_down_transition.txt](https://github.com/google/ExoPlayer/files/5266664/scene_drag_down_transition.txt)

**Comment by Prateek-Kapoor** [comment]
Hello, I request you to please have a look at this issue, we kind of a stuck on this from quite a time.
Thanks

**Comment by Prateek-Kapoor** [comment]
Hi Samrobbo,
Any update on this?

**Comment by Prateek-Kapoor** [comment]
Hi Samrobbo,
Any update on this?

**Comment by marcbaechinger** [comment]
If this works on some devices while not on other low-level devices this indicates that it is a device specific problem. Seems like you did everything right. I'm not aware of further configs which would help in such cases.

Below API 24 you need to use a `TextureView` when animating like the documentation says. Animating a `SurfaceView` with protected content (L1) is always difficult because the protected content can not accessed by the OS outside the secure path.

**Comment by Prateek-Kapoor** [comment]
Thanks, marchaechger for the information. 

But as you mentioned that - **If this works on some devices while not on other low-level devices this indicates that it is a device- specific problem.**

But I never mention that it doesn't happen in higher-end devices. I said that **the flickers amount varies from device to device, video flickers more in low-end devices(LG-H860), and less in good configuration devices. (OnePlus 7, Poco F1).**
Hence it's not a device-specific issue but yes the rendering might vary depending upon the device performance. 

Adding to this I will like to say as per the [exo player documentation](https://exoplayer.dev/ui-components.html):-  **SurfaceView rendering wasn’t properly synchronized with view animations until Android N** which means it shall work properly above N but that's not the case, my observation and findings validated that.

**Comment by marcbaechinger** [comment]
I don't know what I can do to help you some further from ExoPlayer side I'm afraid. If you see it is working better with a `TextureView` then using it seems to make sense. I leave this issue open in case someone else has some ideas how to improve this behaviour.
