### ISSUE TITLE
How can I move out My Custom Control PlayBack from PlayerView

### ISSUE THREAD

**Issue by AndersonCrew** [google/ExoPlayer#7972]
I have customized control playback, now I want to move out from PlayerView, how can I do that? Please help me!

**Comment by marcbaechinger** [comment]
Please check the [section about the `PlayerControlView`](https://exoplayer.dev/ui-components.html#player-control-views) in the developer guide. It tells how you can find the view in your activity. 

We can not support general Android UI development in this issue tracker I'm afraid. If you think it is related to the player view specifically, please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/question.md).
