### ISSUE TITLE
How can I change ratio of PlayerView when show the video?

### ISSUE THREAD

**Issue by AndersonCrew** [google/ExoPlayer#7973]
I have a video with the ratio is 4:3 but I want to show a video with the ratio is 16:9, It's mean the video will be center of PlayerView, and the cover is the background of black color, how can I do that, please help me?

**Comment by Samrobbo** [comment]
If I'm understanding your question correctly, you want to display a video with the aspect ratio of 4:3 on a screen that is 16:9 aspect ratio.

If that's correct, the [demo app](https://github.com/google/ExoPlayer/tree/release-v2/demos/main) currently does this, so you may want to replicate that behaviour.
