### ISSUE TITLE
What do I need to pass into ExoPlayer.Builder to create a player?

### ISSUE THREAD

**Issue by nirazv** [google/ExoPlayer#7976]
ExoPlayerFactory method is deprecated in 2.12.0 instead of this they introduced [ExoPlayer.Builder](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/ExoPlayer.Builder.html)

ExoPlayer.Builder class takes few parameters

Context context, Renderer... renderers

I am confused what Renderers is what is the use of it? and How to create an instance of it?

**Comment by tosam144** [comment]
You can use:

`SimpleExoPlayer player = new SimpleExoPlayer.Builder(this).build();`

In a singelton, this would be something like:

```
private static SimpleExoPlayer player;

public static SimpleExoPlayer getPlayer(Context context) {
   if (player == null) {
       player = new SimpleExoPlayer.Builder(context).build();
   }
   return player;
}
```

**Comment by nirazv** [comment]
I tried this approach but what if i had to remove PlayerView and reattach the same instance to new PlayerView with everything fresh/reset except instance?

**Comment by nirazv** [comment]
and What is the different between SimpleExoPlayer.Builder vs ExoPlayer.Builder method?

**Comment by Samrobbo** [comment]
### ExoPlayer vs SimpleExoPlayer 
SimpleExoPlayer has a large number of enhancements and automations to make getting started easier. It also has a number of improvements that are very valuable for media app development. Unless you are an advanced developer with very specific and large customisations, we recommend using SimpleExoPlayer.

### Builder 
`SimpleExoPlayer.Builder`is the way to create a `SimpleExoPlayer` instance. 

There are multiple constructors to initialise the builder, and it depends on the level of customisation you want.

`Builder(Context context)` is the most straightforward option, and should be used unless you specifically want to make use of a custom `RenderersFactory` or `ExtractorsFactory`. Once you have the builder instance, you can set specific properties, such as bandwidth meter, track selector etc using the setters. 

Once the builder is ready, you call `builder.build()` and it will return a `SimpleExoPlayer` instance for your use. 

#### Renderers
As mentioned above, you can pass a custom `RenderersFactory` to SimpleExoPlayer. This is the way to customise `SimpleExoPlayer` to use specific `Renderer` instances, as well as other modifications. For most straightforward use cases, I doubt there is need to specify a custom `RenderersFactory`.

**Comment by Samrobbo** [comment]
I will keep open in case i've not fully answered your question.

**Comment by nirazv** [comment]
What if I want to use ExoPlayer multiple times such as Youtube does in their app, its much faster right?. but if I create multiple instance of SimpleExoplayer (ex- more than 2 times it became slower and laggy)? it there any way I can use it exoplayer with faster way by changing just data source url?

**Comment by nirazv** [comment]
I am still not understood what renderer is? or how it helps exoplayer?

And how to initialize it as following:
ExoPlayer player = new ExoPlayer.Builder(context, Renderers???? how to pass here??)

**Comment by AquilesCanta** [comment]
Hi @nirazv, I suggest you share with us the code you were using to instantiate ExoPlayer before 2.12, and we will provide you with the equivalent 2.12 code. Does that work for you?

**Comment by nirazv** [comment]
> Hi @nirazv, I suggest you share with us the code you were using to instantiate ExoPlayer before 2.12, and we will provide you with the equivalent 2.12 code. Does that work for you?

`renderers = ???? // how to intitialize`
`player = new ExoPlayer.Builder(context, renderers)`
                `.setMediaSourceFactory(new DefaultMediaSourceFactory(cacheDataSourceFactory))`
                `.build();`

**Comment by Samrobbo** [comment]
Given your code snippet, you could instead use this:

```
player = new SimpleExoPlayer.Builder(context)
.setMediaSourceFactory(new DefaultMediaSourceFactory(cacheDataSourceFactory))
.build();
``` 

`SimpleExoPlayer` is a subclass of `ExoPlayer`, so has all the functionality of `ExoPlayer` plus more!

Alternatively, if you wish to avoid the SimpleExoPlayer, you can create a [`DefaultRenderersFactory`](exoplayer.dev/doc/reference/com/google/android/exoplayer2/DefaultRenderersFactory.html) and call [`createRenderers`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/DefaultRenderersFactory.html#createRenderers-android.os.Handler-com.google.android.exoplayer2.video.VideoRendererEventListener-com.google.android.exoplayer2.audio.AudioRendererEventListener-com.google.android.exoplayer2.text.TextOutput-com.google.android.exoplayer2.metadata.MetadataOutput-) to acquire a Renderer[]. The [javadoc of createRenderers](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/DefaultRenderersFactory.html#createRenderers-android.os.Handler-com.google.android.exoplayer2.video.VideoRendererEventListener-com.google.android.exoplayer2.audio.AudioRendererEventListener-com.google.android.exoplayer2.text.TextOutput-com.google.android.exoplayer2.metadata.MetadataOutput-) covers what to pass in to this method.

It's worth pointing out that SimpleExoPlayer does this for you, as well as automatically handling callbacks from the renderers. Therefore we strongly recommend using SimpleExoPlayer over ExoPlayer.

**Comment by nirazv** [comment]
What if i wants to Reuse renderer? 
[Reusing renderer] How to Reuse PlayerView instance for multiple Videos?

**Comment by Samrobbo** [comment]
If you want to reuse the `Renderer[]`, just keep a reference to it when you pass it into the `ExoPlayer.Builder`.

**Comment by ojw28** [comment]
> what if i had to remove PlayerView and reattach the same instance to new PlayerView with everything fresh/reset except instance?

To clarify, if you want to do this, just:

1. Call `playerView.setPlayer(null)` to remove the player from the old view.
1. Call `player.stop()` to reset the player.
1. Call `playerView.setPlayer(player)` to attach the player to the new view.

You really don't need to be messing around with renderers at all.
