### ISSUE TITLE
How To Synchronizing Playing Multiple Audio 2.12.0

### ISSUE THREAD

**Issue by xiaochedexinyang1** [google/ExoPlayer#7979]
I wanted to use exoplayer to play three music at the same time, but I found that it was not played at the same time. There was some time lag between them. What can I do so that there is no time difference 。I use the [#4261](https://github.com/google/ExoPlayer/issues/4261)but it not solve。

This is the code I use
```
MultiTrackRenderersFactory factory = new MultiTrackRenderersFactory(3, context);
mediaPlayer = new SimpleExoPlayer.Builder(context, factory).setTrackSelector(new MultiTrackSelector()).build();
DefaultDataSourceFactory defaultDataSourceFactory = new DefaultDataSourceFactory(context, "audio/mpeg");
ProgressiveMediaSource[] progressiveMediaSources = new ProgressiveMediaSource[4];
progressiveMediaSources[0] = new ProgressiveMediaSource.Factory(defaultDataSourceFactory).createMediaSource(new MediaItem.Builder().setUri(music.getUrl()).build());
progressiveMediaSources[1] = new ProgressiveMediaSource.Factory(defaultDataSourceFactory).createMediaSource(new MediaItem.Builder().setUri(info.getUrl1()).build());
progressiveMediaSources[2] = new ProgressiveMediaSource.Factory(defaultDataSourceFactory).createMediaSource(new MediaItem.Builder().setUri(info.getUrl1()).build());
MergingMediaSource concatenatingMediaSource = new MergingMediaSource(true, progressiveMediaSources);
mediaPlayer.setMediaSource(concatenatingMediaSource, true);
```
Thanks in advance!

**Comment by xiaochedexinyang1** [comment]
Can anyone answer my question? thanks

**Comment by Samrobbo** [comment]
The answer provided here https://github.com/google/ExoPlayer/issues/4261#issuecomment-389818937 gives a few possible approaches, with the comments afterwards giving more information and context. From what I can tell you are not trying either of these.

**Comment by xiaochedexinyang1** [comment]
> The answer provided here [#4261 (comment)](https://github.com/google/ExoPlayer/issues/4261#issuecomment-389818937) gives a few possible approaches, with the comments afterwards giving more information and context. From what I can tell you are not trying either of these.

I tried, they can play at the same time, but there is a difference of tens of milliseconds between them. Is there any way to reduce it

**Comment by Samrobbo** [comment]
Which approach are you trying?

**Comment by Samrobbo** [comment]
@andrewlewis Can you advise on this?
