### ISSUE TITLE
Why is ExoPlayer not switching to different bitrate in auto mode for HLS videos?

### ISSUE THREAD

**Issue by vickyexpert** [google/ExoPlayer#7980]
Hello All,
             I have HLS videos with pre-signed URL of s3 bucket. I have created different different bitrates videos with one master .M3U8 file which can select the appropriate bitrate m3u8 file.

But I have checked that it is not switching from 720p to 1080p or 576p. I have 3 bitrates like 

```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:BANDWIDTH=1174112,RESOLUTION=1280x720,CODECS="avc1.640020,mp4a.40.2"
Video_2D_720p_750k.m3u8

#EXT-X-STREAM-INF:BANDWIDTH=1449112,RESOLUTION=1280x720,CODECS="avc1.640020,mp4a.40.2"
Video_2D_720p_1000k.m3u8

#EXT-X-STREAM-INF:BANDWIDTH=899112,RESOLUTION=720x576,CODECS="avc1.64001f,mp4a.40.2"
Video_2D_576p_500k.m3u8
```

But it is taking only Video_2D_720p_1000k.m3u8, not switching to another even internet speed it less then 1 mbps or greater then 8 mbps.

**Comment by Samrobbo** [comment]
Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md). If you're unable to share bug reports or test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Please also update this issue to indicate you’ve done this.
