### ISSUE TITLE
Is there a demo for streaming foreground service?

### ISSUE THREAD

**Issue by tosam144** [google/ExoPlayer#7987]
In the official demo app of Exoplayer I cannot find any code on how to implement a streaming foreground service. I do see the `DemoDownloadService` but I am missing an audio streaming demo, that is, something like

`class DemoStreamingService extends Service {...}`

which is bound to some PlayerActivtiy and started via `Util.startForegroundService`. Where can I find a demo for that? Thanks!

**Comment by marcbaechinger** [comment]
We don't have such a sample that would give you good insights in doing a production ready audio service with ExoPlayer. There is not much specific to ExoPlayer actually. For creating a foreground service with Android there is general documentation here:

https://developer.android.com/guide/components/foreground-services
https://developer.android.com/guide/components/services

If you have questions with ExoPlayer specific details around this, you can check this issue tracker [with an appropriate search term](https://github.com/google/ExoPlayer/issues?q=is%3Aissue+foreground+service+). If that doesn't help you can probably narrow down your question and file a question issue here.

We ask people to try StackOverflow for general Android questions also.

**Comment by tosam144** [comment]
OK, thanks for the Info!
