### ISSUE TITLE
Documentation need to be updated on how to compile Exoplayer 2.12.0 apps with androidx.work library dependency

### ISSUE THREAD

**Issue by Rexee** [google/ExoPlayer#7997]
### [REQUIRED] Issue description
If you use androidx.work and ExoPlayer with version 2.12.0 you need to add additional undocumented settings to gradle file described in issue: https://github.com/google/ExoPlayer/issues/7905#issuecomment-692637059
If Exoplayer 2.12.0 cannot work with androidx.work library without these changes, then it should be officially documented because androidx.work is really popular. Currently we need to check closed issues to find solution.
Google have similar problem and recommend to include "councurrent-futures" dependency in gradle file: https://developer.android.com/topic/libraries/architecture/workmanager/advanced/listenableworker, can this problem be solved with similar approach?

### [REQUIRED] Reproduction steps
Described in https://github.com/google/ExoPlayer/issues/7905

### [REQUIRED] Link to test content
Described in https://github.com/google/ExoPlayer/issues/7905

### [REQUIRED] A full bug report captured from the device
Described in https://github.com/google/ExoPlayer/issues/7905

### [REQUIRED] Version of ExoPlayer being used
2.12.0

### [REQUIRED] Device(s) and version(s) of Android being used
any

**Comment by rial1106** [comment]
I had to add a the guava dependancy since listenablefuture wasn't found. It took a lot of work to find the soloution

`implementation 'com.google.guava:guava:29.0-android'`

**Comment by icbaker** [comment]
Thanks for flagging - I agree these errors are pretty confusing.

I've sent a change switching ExoPlayer to depend on Guava as 'api', which I believe resolves both #7905 and #7993.

I'm not going to make any additional documentation changes - in the short term people can find these issues until the 'api' dependency change is included in a release.
