### ISSUE TITLE
Play a "key-frame only" video in reverse 

### ISSUE THREAD

**Issue by idish** [google/ExoPlayer#8000]
I've already took a look in the issues section regarding playing a video in reversed order, and understand that it is not quite supported by exoplayer natively, as shown here: https://github.com/google/ExoPlayer/issues/5084

My use case is a bit more specific, and can be more "played" with ;)

Say I have a fully key-framed video, so that decoding it in reversed order shouldn't be an issue, as there are only key-frames, how would it be possible to play that video in reverse? If the library itself doesn't support playing backwards, is there any "hacky" way for me to achieve that, or a way to implement properly?

**Comment by krocard** [comment]
I think you will need to hack in the container parser to force it to return the frame in reverse. You might need to have to hack in the downloader too to download chunks in reverse (except if you are OK with having the file fully downloaded before playing).

@kim-vde can you think of a hack to achieve this?

**Comment by idish** [comment]
@krocard Exoplayer should load a local h264 file, so the downloading part isn't needed.

**Comment by kim-vde** [comment]
I don't think there is a simple way to do that. 

You could implement a custom [Extractor](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/extractor/Extractor.html) and add it to a custom [ExtractorsFactory](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/extractor/ExtractorsFactory.html) that you would pass to the player [builder](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/SimpleExoPlayer.Builder.html#Builder-android.content.Context-com.google.android.exoplayer2.extractor.ExtractorsFactory-).

Another solution could be to remux the file to inverse the frame order before passing it to ExoPlayer.

What is the container format? Does the file have audio?

**Comment by idish** [comment]
Container format is mp4, and there's no audio, only video.

**Comment by kim-vde** [comment]
You will need to locate the frames in reverse order by parsing the stbl box (I am assuming your input file is not fragmented) and changing the frame timestamps.
