### ISSUE TITLE
Non Play Services device

### ISSUE THREAD

**Issue by ArcherEmiya05** [google/ExoPlayer#8002]
Will ExoPlayer libraries including ExoPlayer IMA SDK will work without needing a Play Services in a device such as Amazon tablets?

Thank you

**Comment by krocard** [comment]
@andrewlewis, do you know if the IMA SDK depends on play services?

**Comment by andrewlewis** [comment]
The ExoPlayer IMA extension will support any device where the Android IMA SDK works. That includes at least Fire TV (see https://developers.google.com/interactive-media-ads/docs/sdks/other).

I'm not sure about other cases so I suggest asking on the IMA SDK forum: https://groups.google.com/g/ima-sdk/. It would be nice if you could reply here once you get an answer, for the benefit of other people who have the same question.

**Comment by ArcherEmiya05** [comment]
> 
> 
> The ExoPlayer IMA extension will support any device where the Android IMA SDK works. That includes at least Fire TV (see https://developers.google.com/interactive-media-ads/docs/sdks/other).
> 
> I'm not sure about other cases so I suggest asking on the IMA SDK forum: https://groups.google.com/g/ima-sdk/. It would be nice if you could reply here once you get an answer, for the benefit of other people who have the same question.

Thanks, I already ask a new case but similar topic.

Our team is wondering if it will work fully and fine on devices like Huawei that has no Play Services for us to measure our app's compatibility and its scalability as these libraries are included and part of the main functionality in our product.

**Comment by andrewlewis** [comment]
For reference here is [the thread](https://groups.google.com/g/ima-sdk/c/u2cSTqia8kA/m/JGJJs4lRBQAJ).

**Comment by ArcherEmiya05** [comment]
> 
> 
> The ExoPlayer IMA extension will support any device where the Android IMA SDK works. That includes at least Fire TV (see https://developers.google.com/interactive-media-ads/docs/sdks/other).
> 
> I'm not sure about other cases so I suggest asking on the IMA SDK forum: https://groups.google.com/g/ima-sdk/. It would be nice if you could reply here once you get an answer, for the benefit of other people who have the same question.

According to the thread the IMA SDK has dependency on Play Services but should work even without it. So can we conclude that all ExoPlayer dependency will work with or without Play Services installed except for its IMA SDK which seems to be situational since it is possible that some 3rd party builds of Android made by manufacturers could lead to some bugs that affects the IMA SDK?

**Comment by andrewlewis** [comment]
ExoPlayer's core playback functionality doesn't rely on Play Services.

By "all ExoPlayer dependency" are you including extension modules? If yes, the other ones that depend on Play Services are the Cast extension and (possibly) the Cronet extension, depending on how it's used (it can bundle the network stack or rely on the one in Play Services).

**Comment by ArcherEmiya05** [comment]
> 
> 
> ExoPlayer's core playback functionality doesn't rely on Play Services.
> 
> By "all ExoPlayer dependency" are you including extension modules? If yes, the other ones that depend on Play Services are the Cast extension and (possibly) the Cronet extension, depending on how it's used (it can bundle the network stack or rely on the one in Play Services).

Thanks for pointing out those extensions that has dependency, currently the extension that we just used is IMA SDK together with full library of ExoPlayer. So there should be at least no problem if an Android device happens to have no Play Services.

`com.google.android.exoplayer:exoplayer:2.11.1`
`com.google.android.exoplayer:extension-ima:2.11.1`
