### ISSUE TITLE
Timeframe for Exoplayer Migration to Kotlin 

### ISSUE THREAD

**Issue by harini113** [google/ExoPlayer#8004]
### [REQUIRED] Searched documentation and issues
https://developer.android.com/kotlin/faq

### [REQUIRED] Question
Are Exoplayer libraries migrating to kotlin. Will you continue to support Java. If java is being deprecated, is there a timeline?

**Comment by andrewlewis** [comment]
Please see the discussion on #6826. We aren't planning to switch to Kotlin in the short term, but we do want to make sure the ExoPlayer API surface is designed in a way that works well for Kotlin users.
