### ISSUE TITLE
I can't play video in second time

### ISSUE THREAD

**Issue by cockroach904** [google/ExoPlayer#8006]
Hi sir~
I have a question,
I play the video for the first time,it play success,
when video in end and replay it , the video can't play.

but I try my code in 2.6.1, it can work.
Thi is my vido url = "https://apptest.greattree.com.tw/upload_file/mdm_20200204142044.mp4"

**Comment by krocard** [comment]
I can reproduce the bug on tip of tree:
~~~
curl -LO "https://apptest.greattree.com.tw/upload_file/mdm_20200204142044.mp4"
adb push mdm_20200204142044.mp4 /sdcard/Music/
./gradlew demo:installNoDecoderExtensionsDebug # if ExoPlayer's demo app is not installed
adb shell am start -a com.google.android.exoplayer.demo.action.VIEW -d file:///sdcard/Music/mdm_20200204142044.mp4
~~~
Seek in the video => no issue
Seek towards the end, let the video finish and then click on the `|<` button to seek back to the beginning

The issue is that the screen is green with a few color region that change color while seeking. The audio is not affected.

[Screenshot of the glitch.](https://user-images.githubusercontent.com/6862950/94712148-f8175100-0340-11eb-9580-3b271f0550e8.png)

**Comment by krocard** [comment]
I'll try on 2.11.8 to see if this is a regression.

**Comment by krocard** [comment]
The logcat does not shows any error or suspicious log. This looks to me like the codec is not properly re-initialized when seeking back to 0.
4min 33s is the typing point, if seeking back to 0 before it, no issues occur. If seeking back to 0 after 4:33, the screen is read until 4:33 is reached where the glitch disappears and the video is back to normal.

It's like 2 video were stitched and only going from 1 to 2 is possible, but not from 2 to 1.

I have reproduced the issue on VLC on my MacBook, and Photos on Android 10, but Chrome on MacBook does not have the issue.

**Comment by krocard** [comment]
The Media is encoded in AVC in an MPEG-4 container:
<details>
<summary>
$ mediainfo ~/Music/mdm_20200204142044.mp4
</summary>
General
Complete name                            : /Users/krocard/Music/mdm_20200204142044.mp4
Format                                   : MPEG-4
Format profile                           : Base Media
Codec ID                                 : isom (isom)
File size                                : 54.2 MiB
Duration                                 : 5 min 38 s
Overall bit rate mode                    : Variable
Overall bit rate                         : 1 341 kb/s
Encoded date                             : UTC 2019-02-14 06:56:26
Tagged date                              : UTC 2019-02-14 06:56:26

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L3.1
Format settings                          : CABAC / 1 Ref Frames
Format settings, CABAC                   : Yes
Format settings, Reference frames        : 1 frame
Format settings, GOP                     : M=1, N=60
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 5 min 38 s
Source duration                          : 5 min 38 s
Bit rate                                 : 1 165 kb/s
Maximum bit rate                         : 2 885 kb/s
Width                                    : 1 280 pixels
Height                                   : 720 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Variable
Frame rate                               : 25.000 FPS
Minimum frame rate                       : 21.789 FPS
Maximum frame rate                       : 25.000 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.051
Stream size                              : 47.1 MiB (87%)
Source stream size                       : 47.1 MiB (87%)
Tagged date                              : UTC 2019-02-14 06:56:27
Color range                              : Limited
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709
Codec configuration box                  : avcC

Audio
ID                                       : 2
Format                                   : AAC LC
Format/Info                              : Advanced Audio Codec Low Complexity
Codec ID                                 : mp4a-40-2
Duration                                 : 5 min 38 s
Source duration                          : 5 min 38 s
Bit rate mode                            : Variable
Bit rate                                 : 173 kb/s
Nominal bit rate                         : 192 kb/s
Maximum bit rate                         : 203 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 44.1 kHz
Frame rate                               : 43.066 FPS (1024 SPF)
Compression mode                         : Lossy
Stream size                              : 7.01 MiB (13%)
Source stream size                       : 7.01 MiB (13%)
Title                                    : IsoMedia File Produced by Google, 5-11-2011
Language                                 : English
Encoded date                             : UTC 2018-03-13 16:34:24
Tagged date                              : UTC 2019-02-14 06:56:27
</details>

**Comment by krocard** [comment]
Given that VLC has the same issue than ExoPlayer, the issue most certainly comes from your media being non conformant.
Please fix your MPEG video. I suspect two or more MPEG video were stitched together into one incorrectly.
Please reopen the issue if you believe this is incorrect.
