### ISSUE TITLE
Need an event listener for child media source in playlist.

### ISSUE THREAD

**Issue by sunhb** [google/ExoPlayer#8007]
### [REQUIRED] Searched documentation and issues
I searched related issues, Documents and stackOverFlow, but did not find any information related to my problem. 
I even made the wrong off-topic in other issues(#7995 ), so sorry

### [REQUIRED] Question
I need an event listener which can Triggered when the current media playback is complete and ready to play the next media in a playlist. To do some operations witch depends user do for next datasource

I tried find a STATE in `Player.EventListener#onPlayerStateChanged(playWhenReady: Boolean, playbackState: Int)`, `Player.STATE_ENDED` is fine for me, but this state is only triggered when all playlists are over, not for childMediaSource.

Then I tried `Player.EventListener#onPositionDiscontinuity(reason: Int)`, But because the mediasource at this time lacks the preprocessing I mentioned above, mediaUri is incomplete, so when I receive this EVENT, there is no way to stop the playback in time, and the Player has thrown a SourceException.

So is there such an event that can notify me so that I can: 
1. Pause the playback, 
2. Inform the user to perform the necessary operations,
3. Re-obtain the complete mediaSource. 
4. Update the current playlist

Very thankful

**Comment by marcbaechinger** [comment]
If I understand correctly you are saying that mediaSource 1 is playing and media source 2, that is the next media source in the playlist, is currently not complete in a sense that trying to prepare it would fail because the user needs to add something to make this possible.

If this is the case for all media sources in the playlist it sounds easiest to me to just don't add the source yet? Then you can wait for the STATE_ENDED, ask the user and when the user entered the required data you just add the media source to the playlist after this. Would that work?

**Comment by sunhb** [comment]
As you said, if all data sources are this situation, it will be easier to deal with. But this is the case with only a few data sources in real business.

**Comment by sunhb** [comment]
I need to ensure that the playlist is complete. The loop mode of the playlist, the function of random playback, and the advance preparation of the data source. These rely on adding all media sources to the playlist.

**Comment by marcbaechinger** [comment]
Have you looked at [`ResolvingDataSource`](https://github.com/google/ExoPlayer/blob/83477497c19959f4b33c3af57cc1e646fcc3848a/library/core/src/main/java/com/google/android/exoplayer2/upstream/ResolvingDataSource.java)?

**Comment by sunhb** [comment]
> Have you looked at [`ResolvingDataSource`](https://github.com/google/ExoPlayer/blob/83477497c19959f4b33c3af57cc1e646fcc3848a/library/core/src/main/java/com/google/android/exoplayer2/upstream/ResolvingDataSource.java)?

Thanks for your reply :)
As far as I know, `resolveReportedUri` in `ResolvingDataSource` is a method that does not allow blocking. 
But what I need is the player to pause and wait for the user to do something.

**Comment by marcbaechinger** [comment]
When there is a playlist, ExoPlayer is going to automatically prepare the next media source. This happens a certain duration before the next  media source would need to start playback. The duration depends on the configuration of the [`DefaultLoadControl`](https://github.com/google/ExoPlayer/blob/83477497c19959f4b33c3af57cc1e646fcc3848a/library/core/src/main/java/com/google/android/exoplayer2/DefaultLoadControl.java#L44) which defines the buffered duration. It depends on how you configured the player.

So what you probably can do is executing a message a certain duration before the given media source would be prepared. The [page about events in the Developer Guide](https://exoplayer.dev/listening-to-player-events.html#playback-position) explains how you can execute such a message at an arbitrary playback position.

**Comment by sunhb** [comment]
LoadControl cannot prevent data Source prepare, so it cannot prevent throwing exception.

I need to pause the play immediately when onMediaMetadataChanged, and stop loading the DataSource don't throwing an exception.

**Comment by marcbaechinger** [comment]
Yes, you need to pause yourself in the message which is executed at the playback position you define. This will prevent prepare if you properly define the position which is something like `(currentWindow.durationMs - maxBufferMs - sanityMs)`? You need to know how you configured  the `DefaultLoadControl` to know `maxBufferedMs`.

**Comment by sunhb** [comment]
If I understand correctly, You mean when I execute this  message , currentWindow is not play completed right?

**Comment by sunhb** [comment]
The position is very close to **currentWindow.duration**? So it's looks like paused at end of previous media ?

**Comment by marcbaechinger** [comment]
Lets say, that you configure the `DefaultLoadControl` to have a buffer duration of 50sec. If now playback arrives at the position `(duration - 50 seconds)` , ExoPlayer needs to prepare the next media source to be able to start buffering ahead. So the moment in time when ExoPlayer wants to prepare your media source is about 50 seconds before the next window starts. That's the moment your data source is asked for data and the exception is thrown. 

So you need to ask your user 50 seconds before the start of the next window to prevent the exception.  If you wait until shortly before the next window starts, it's already too late. So you need to ask the user at position `(currentWindow.durationMs - maxBufferMs - sanityMs)`. If your media items are very short in duration it gets more complicated.

**Comment by sunhb** [comment]
This is not in line with my usage scenario. This will happen when the current media has not been played. (and true，some media item maybe very shot) At that time, I cannot pause the player, nor can I show the user any information about the next media.

**Comment by marcbaechinger** [comment]
You can try to put a placeholder media source in the timeline at the position where the media source is which needs additional information. Probably a `SilenceMediaSource` is a good fit. Then listen for a media item transition for that window. If the player transitions to that window, you pause the player, present the UI to the user. Then you replace the `SilenceMediaSource` with the one that just got the user information needed and then continue.

**Comment by sunhb** [comment]
I think new version(2.12.0) resolved my problems. So very thankful and we can close this issue. :)
