### ISSUE TITLE
audio late reached after 14 seconds than video when tunneling video playback enabled

### ISSUE THREAD

**Issue by jdshaoheyi** [google/ExoPlayer#8008]
### Issue description
sound of video is occur after video frame displayed 14 seconds when i opened tunneling video playback, and video also discontinuity, stuck. after first 14 seconds every thing is ok.
this problem is not happened after tunneling video playback disabled.

### Reproduction steps
play rtp source with bit rate 8Mbit/s, resolution 1920*1080i.

### Link to test content
little sorry i can not provide any source because it's a rtp over udp inner local network provided by a special device. but the udp data i have uploaded can download with below link. i extract frame info use ffmpeg also uploaded.

1、udp data
[https://www.filehosting.org/file/details/896584/udp_huawei.ts](url)

2、extracted frame info 
[https://www.filehosting.org/file/details/896582/udp_huawei.frame.unit.xml.txt](url)

### A full bug report captured from the device
log can not provided because the testing device can not connected with adb.

### Version of ExoPlayer being used
2.11.8

### Device(s) and version(s) of Android being used
100% can be reproduced on TV with model num Skyworth 50E388G. Android Version 5.1.1

**Comment by krocard** [comment]
Tunneling playback is known to have many device specific issues. I'm afraid we can not help you resolve this issue as we do not have access to that TV, and even if we did, there is very little that an app can do to workaround tunneling issues.

Given how old the TV is, the manufacturer won't fix the issue.
I would suggest not enabling tunneling for that TV.
