### ISSUE TITLE
In Protected Dash Content, audio and video sync is missing in playback speed at 2

### ISSUE THREAD

**Issue by gokulkalagara** [google/ExoPlayer#8009]
### [REQUIRED] Issue description
In Protected Dash Content, audio and video sync is missing in playback speed at 2.0f
in event logger i find this error
audioTrackUnderrun   [eventTime=29.05, mediaPos=27.39, window=0, period=0, 61568, 320, 112]
audioTrackUnderrun   [eventTime=29.05, mediaPos=27.39, window=0, period=0, 61568, 320, 1]]

### [REQUIRED] Link to test content
I will share a sample APK to you in mail and event logger also details in excel sheet

### [REQUIRED] Version of ExoPlayer being used
2.12.0

### [REQUIRED] Device(s) and version(s) of Android being used
Brand: Samsung
Model: SM-J810G 
android Version: 9

If you need means we will share the device bug report

**Comment by krocard** [comment]
Your content might not be decrypted fast enough to play it at 2x. @AquilesCanta do you have experience with fast playback of DRM content?

**Comment by AquilesCanta** [comment]
Hi @gokulkalagara, everything seems to suggest this is the device not being able to keep up, and not an ExoPlayer issue.
- Please try playing the content using a lower playback speed, like 1.1, and let us know if you still run into issues. Ideally, try and find the playback speed threshold at which you run into playback issues.
- Please also try an older ExoPlayer version (like 2.10 and 2.11) to see if this is has regressed in the latest version.
- If you have any evidence of this being an ExoPlayer issue, please do provide evidence.
