### ISSUE TITLE
Playback speed is faster for some audios

### ISSUE THREAD

**Issue by matheusss-ufop** [google/ExoPlayer#801]
Hi folks,

I'm trying to solve an issue that is happening with just some audios when I try to play an mp3 streaming..
I've already looked through the whole issues posts, but unfortunately no success.

So, the problem is that in some samples, it starts to play with a high playback speed and in other samples it just start as expected, but I have never changed playback speed.

My app is playing podcasts from different sources, and I'm facing this problem with just some of them. For example, these audios are problematics:
- http://download.sgr.globo.com/sgr-mp3/cbn/2015/colunas/max_150622.mp3
- http://download.sgr.globo.com/sgr-mp3/cbn/2015/colunas/max_150825.mp3

And this is the way I'm redering the audio:
```java
Allocator allocator = new DefaultAllocator(BUFFER_SEGMENT_SIZE);
DefaultBandwidthMeter bandwidthMeter = new DefaultBandwidthMeter(player.getMainHandler(), null);
DataSource dataSource = new DefaultUriDataSource(context, bandwidthMeter, userAgent);
ExtractorSampleSource sampleSource = new ExtractorSampleSource(uri, dataSource, allocator, BUFFER_SEGMENT_COUNT * BUFFER_SEGMENT_SIZE);
MediaCodecAudioTrackRenderer audioRenderer = new MediaCodecAudioTrackRenderer(sampleSource, null, true, player.getMainHandler(), player);
```

Does anyone else is facing the same problem or know a way to workaround ?

Ps: I dont think this problem is related with the audio source, because it was playing correctly on android MediaPlayer before I change to ExoPlayer..

Thanks in advance,
Regards,
Matheus

**Comment by ojw28** [comment]
Both of those are playing at normal speed for me, using both dev and master branches. Is this only happening on some devices or some Android platform versions? Please provide as much detail as possible on what devices / Android platform versions you've experienced this issue on.

Thanks!

**Comment by matheusss-ufop** [comment]
Ohh, I forgot to give details about the device..

That's exactly the point, it works just fine on Samsung GT-I9082 and Android 4.4.4, but when I try to play on an Alcatel One Touch 4033E and Android 4.2.2 its happening this issue.

I would like to try on another device running Android 4.2.2, but I dont have it, so I tried on emulate on genymotion on android version 4.2.2 and it worked just fine..

Best regards,
Matheus

**Comment by spark85** [comment]
I've had similar issues as well.

**Comment by matheusss-ufop** [comment]
spark85, which device and android are you using ?

**Comment by matheusss-ufop** [comment]
I'm still trying to figure out what is going on, I guess that this issue is related with bit rate and/or sample rate..
So I downloaded the mp3 listed above which has this details:

Complete name                            : max_150825.mp3
Format                                   : MPEG Audio
File size                                : 930 KiB
Duration                                 : 1mn 58s
Writing library                          : LAME3.98r
Bit rate mode                            : Constant
<strong> Bit rate                                 :  64.0 Kbps</strong>
<strong>Channel(s)                               : 1 channel</strong>
<strong>Sampling rate                            : 48.0 KHz</strong>
Compression mode                         : Lossy
Stream size                              : 929 KiB (100%)
Encoding settings                        : -m m -V 4 -q 3 -lowpass 16.5 -b 64

And converted it to a mp3 with a higher bit rate and lower sample rate, like this:

Complete name                            : max_150825(2).mp3
Format                                   : MPEG Audio
File size                                : 1.82 MiB
Duration                                 : 1mn 59s
Writing library                          : LAME3.98.4
Bit rate mode                            : Constant
<strong>Bit rate                                 : 128 Kbps</strong>
<strong>Channel(s)                               : 2 channels</strong>
<strong>Sampling rate                            : 44.1 KHz</strong>
Compression mode                         : Lossy
Stream size                              : 1.82 MiB (100%)
Writing library                          : LAME3.98.4

It worked just fine after conversion, and I'm trying to figure out what does it means..
Does Exoplayer defines a minimum bit rate or a maximum sample rate ?
Any ideas or suggestions would be great..

Best regards,
Matheus

**Comment by kylejbrock** [comment]
I'm seeing several reports of this as well.  We recently switched to ExoPlayer.

Users are saying the audio sounds as if it is playing twice as fast.

Device model: Lenovo B6000-F
Firmware version: 4.2.2
Kernel version: 3.4.5
Build number: B6000_A422_000_040_131023_WW_WIFI

Device model: ME173X
Firmware version: 4.2.2
Kernel version: 3.4.5
Build number: ME173X_US_user_4.2.4.04152_20140714

Device model: Lenovo B8000-F
Firmware version: 4.2.2
Kernel version: 3.4.5
Build number: B8000_A422_000_029_130926_WW_WIFI

Device model: SONY Xperia S39h
Firmware version: 4.2.2
Kernel version: 3.4.5
Build number: 16.0.A.0.47

**Comment by dk54** [comment]
I have same problem on Android 4.2.2 (Prestigio Multipad Rider 7.0 3G).

**Comment by GoranStorytel** [comment]
We're having this same issue, it's on some devices when playing back mono mp3 files

**Comment by matheusss-ufop** [comment]
Since there is no feedback about this issue, I assume its not a good ideia to use this ExoPlayer..

**Comment by ojw28** [comment]
It more just means that the issue hasn't been diagnosed yet. From the above, I'd guess that the issue is limited to certain devices and only when playing mono audio, perhaps? Whether that's an issue for you obviously depends on whether you're playing mono audio and whether you care about the affected devices.

We'll try and get around to investigating this in detail soon.

**Comment by ojw28** [comment]
I tried this on a Lenovo B6000-F and it worked fine for me. Although my test devices runs 4.4.2 rather than 4.2.2 as was reported by @kylejbrock. I do wonder to what extent users can fix this themselves by upgrading their OS to the most recent version available for the device. You could/should recommend they try this.

If it is a device specific issue affecting only certain devices only on Android 4.2.2, then it's possible that we could find a workaround. I don't have a device to reproduce the issue with, however, which makes looking for such a workaround difficult.

**Comment by ojw28** [comment]
The change ref'd above most likely fixes this issue on the dev branch (and in 1.5.6, when we generate that release). Please verify.

**Comment by dk54** [comment]
Yes. Verified.

**Comment by bkhall** [comment]
Still seeing this issue on 1.5.6.

Device: QUANTUM-4
OS: 4.2

Device: wiko
OS: 4.2

Several other devices...OS seems to be 4.2.x or lower on all of them.

Mono stream: http://d.liveatc.net/kjfk_twr (plays too fast)

Stereo stream: http://d.liveatc.net/kjfk_gnd_twr (plays correctly)
