### ISSUE TITLE
MiTV requires a output surface workaround

### ISSUE THREAD

**Issue by vinodkputta** [google/ExoPlayer#8014]
## [REQUIRED] Issue description
This is similar to issue https://github.com/google/ExoPlayer/issues/6899. We are getting same issue on other MiTV models,
dangal
dangalUHD
dangalFHD
magnolia
machuca
pacificrim

Please include these device models for output surface workaround.

### [REQUIRED] Reproduction steps
Open watch page and press back. You will get the error.

### [REQUIRED] A full bug report captured from the device
[bugreport-dangalUHD-PI-2020-09-07-16-55-35.zip](https://github.com/google/ExoPlayer/files/5300128/bugreport-dangalUHD-PI-2020-09-07-16-55-35.zip)

### [REQUIRED] Version of ExoPlayer being used
2.11.0

### [REQUIRED] Device(s) and version(s) of Android being used
MiTV dangal, dangal UHD, magnolia

**Comment by krocard** [comment]
Thank for the list, we will add them in the list shortly.

**Comment by krocard** [comment]
To confirm, all those devices were on Android 9? The patch is realy to merge as soon as you will confirm this [internal: cl/334806730].

**Comment by vinodkputta** [comment]
@krocard except **pacificrim** model all are on Android 9.

**Comment by krocard** [comment]
Which Android version is `pacificrim` on ?

**Comment by manojitballav** [comment]
@krocard  Pacificrim is on AOSP 6.0

**Comment by vinodkputta** [comment]
@krocard In which version these changes will be released?

**Comment by krocard** [comment]
They are scheduled to be part of the next major release 2.13.0 that will probably be release in the first few months of 2021.

**Comment by krocard** [comment]
The workarounds have been merged.
