### ISSUE TITLE
Video not showing

### ISSUE THREAD

**Issue by hinditutorpoint** [google/ExoPlayer#8016]
Hi sir 
Recently I played some video working fine but on video not display only audio play
Video ![20200930_012143.jpg](https://user-images.githubusercontent.com/42866845/94608684-5d286380-02bb-11eb-8089-2f2b2f43af47.jpg)

**Comment by marcbaechinger** [comment]
Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md). If you're unable to share bug reports or test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Please also update this issue to indicate you’ve done this.
