### ISSUE TITLE
Ads on SurfaceView

### ISSUE THREAD

**Issue by gowthamkrishnabj** [google/ExoPlayer#8018]
Hi, 

Is there any possibility to display ads on SurfaceView, with SKIP options and duration?

Thanks,
Gowtham.

**Comment by andrewlewis** [comment]
If you are using the IMA extension, the ad UI (including skip button and count down text) will be rendered in a WebView on top of the SurfaceView with video output. There isn't an option to render this UI to the SurfaceView I'm afraid. The ad media is rendered to the SurfaceView in the same way as the content media.
