### ISSUE TITLE
How to detect when playback transitions to another media item

### ISSUE THREAD

**Issue by Abrar-ul-haq-Abro** [google/ExoPlayer#8019]
**This is how i add media items**
```
  for (int i=0;i<=paths.size();i++)
                    {
                        MediaItem mediaItem = MediaItem.fromUri( Uri.encode( paths.get(i)));
                        player.addMediaItem(mediaItem);
                    }
                   videoView.setPlayer(player);
                   player.seekTo(position, currentPosition);
                   player.setPlayWhenReady(true);
                   player.prepare();
                  player.play();
```

**My On playback state change Method** 

     @Override
        public void onPlaybackStateChanged(@Player.State int state){
            if (state == PlaybackStateCompat.STATE_SKIPPING_TO_NEXT) {
                   //do something
            }
            if (state == PlaybackStateCompat.STATE_SKIPPING_TO_PREVIOUS) {
               //do something
        }
}

**and it returns me state=2  and state = 3 every time......**

**Comment by marcbaechinger** [comment]
Can you please have a look in the Developer Guide which has [a section about listening to the playback state](https://exoplayer.dev/listening-to-player-events.html#player-state-changes)?

It looks like you mix up the states of ExoPlayer and `MediaSessionCompat`.

When you are using a callback or another method like `onPlaybackStateChanged` you can always consult the JavaDoc of that method. It provides information about the given method. In this case you can look up [`onPlaybackStateChanged`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/Player.EventListener.html#onPlaybackStateChanged-int-). If you are there you can click on `@Player.State` which gives you further information about what constants you can expect to be passed as argument `state`. This method of reading JavaDoc works with all methods of the ExoPlayer project and is of general value. I consider this as a successful practice for myself and can recommend it.

If you want to listen to the event which notifies you about a media item transitioning to the next in the playlist, please check the [Developer Guide page about playlists](https://exoplayer.dev/playlists.html#detecting-when-playback-transitions-to-another-media-item).

**Comment by Abrar-ul-haq-Abro** [comment]
**Thanks marcbaechinger for correcting me**
**I believe you suggested me to do it like this**

 private class PlayerEventListener implements Player.EventListener {
        @Override
        public void onMediaItemTransition(@Nullable MediaItem mediaItem, @Player.MediaItemTransitionReason int reason) {
                   //do something
        }
}

**right....?**
   **but still I can't get the right action weather it is Skip to next or Previous**

  above method gives me following reasons 
**MEDIA_ITEM_TRANSITION_REASON_AUTO,
    MEDIA_ITEM_TRANSITION_REASON_SEEK,**

**Comment by marcbaechinger** [comment]
I don't really know what you are trying to achieve I'm afraid. Can you please explain in a little bit more detail what you want to do?
