### ISSUE TITLE
Right way to implement video playlist

### ISSUE THREAD

**Issue by Nimrodda** [google/ExoPlayer#802]
I'm reusing `DemoPlayer` from the demo app and I'd like to have playlist functionality for videos.
So in essence, enable the user to create a queue, etc.

As far as I understand the only way to get such functionality is by replacing the `RendererBuilder` instance which holds the URL to the video.
Without making any modifications to `DemoPlayer`, it seems that I have to release it and reconstruct it with a new `RendererBuilder`.

Another way might be to add a setter for `rendererBuilder`, but I noticed that `rendererBuilder` field in `DemoPlayer` is declared as `final`. I didn't dive in too deep to figure out why is it `final`, but instead decided to ask here first.

So what would be the best way to do this?
Thanks in advance!

**Comment by andrewlewis** [comment]
#1270 tracks adding playlist support.
