### ISSUE TITLE
Portrait video in full screen

### ISSUE THREAD

**Issue by ghost** [google/ExoPlayer#8021]
Hello there

I want to show portrait video in full screen. `Exoplayer` will show it in full screen one time if video was not end. When `onPlayerStateChanged` called with `Player.STATE_ENDED` after that if I display it in full screen then `Exoplayer` did not resize video even player size is resized by me every time.

Lets say video is playing and I make it full screen and video is showing in full screen. When video ended and play it again size will change automatically.

Please guide me to get problem and help me to solve this

Thank you.

**Comment by Yugalbuddy** [comment]
In this reference, Since the video playing mode can be set by providing the proper command and to merge with your in built screen rotate mode

**Comment by ghost** [comment]
Thank you for your response.

I have observe issue and I have notice one thing is that. If initially I start player in full screen then video plays always in ratio of full screen mode. if I resize it and exit from full screen then player size is resize but video plays in ratio of full screen.

Please guide me to solve the problem.

**Comment by ghost** [comment]
I got solution for my problem
Thank you for your response.
