### ISSUE TITLE
BasePlayer::setMediaItems resetPosition is not used

### ISSUE THREAD

**Issue by loki666** [google/ExoPlayer#8024]
https://github.com/google/ExoPlayer/blob/8a0d52be4b5402af0987fc7d009bc49977c72b67/library/core/src/main/java/com/google/android/exoplayer2/BasePlayer.java#L48

**Comment by krocard** [comment]
@marcbaechinger is this on purpose? simpleExoPlayer overrides the method but only calls ExoPlayerImpl which use the `BasePlayer` implementation ignoring the parameter. So `resetPosition` seems to always be ignored for both `setMediaItem` methods with a `resetPosition` parameter when calling on `SimpleExoPlayer` or `ExoPlayerImpl`.

**Comment by marcbaechinger** [comment]
Yes, that doesn't look right. Thanks for reporting. I look into this.

Edit: As a workaround you can do

```
setMediaItems(items, 0, C.TIME_UNSET);
```

instead of 

```
setMediaItems(items, /* resetPosition= */ true);
```

**Comment by loki666** [comment]
> ```
> setMediaItems(items, /* resetPosition= */ true);
> ```

tried that, not working either.
my work around was to call seekTo after setMediaItems

**Comment by loki666** [comment]
> Yes, that doesn't look right. Thanks for reporting. I look into this.
> 
> Edit: As a workaround you can do
> 
> ```
> setMediaItems(items, 0, C.TIME_UNSET);
> ```
> 
> instead of
> 
> ```
> setMediaItems(items, /* resetPosition= */ true);
> ```

thanks, I'm calling seekTo after setMediaItems as a workaround now

**Comment by marcbaechinger** [comment]
Cool! Fix is on it's way, btw.

Just to be a bit more precise to my comment above. A general solution would need something like this:

```
Timeline timeline = player.getCurrentTimeline();
int windowIndex = timeline.isEmpty()
    ? 0 
    : timeline.getFirstWindowIndex(player.getShuffleModeEnabled());
player.setMediaItems(items, windowIndex, C.TIME_UNSET);
```
