### ISSUE TITLE
PlaybackParameters not working in few android devices

### ISSUE THREAD

**Issue by vishal-prepladder** [google/ExoPlayer#8026]
PlaybackParameters are not working properly in *REALME 6, POCO, LENOVO* devices.While speed is set to higher than normal than video got stuck and not playing properly by the player. We are using **WIDEVINE DRM** for playing videos.However when widevine is removed video plays smoothly.

 **Please help us if something we can change with encoding paramaters**

                     //PlayerView myVideoView;

                    myVideoView.getPlayer().setPlaybackParameters(new PlaybackParameters(1.2f, 1.0f));

Please let us know if any other input is required from our side.

**Comment by andrewlewis** [comment]
Is it possible that all frames are being dropped because video decoding can't keep up with the player speed? See also #4851.
