### ISSUE TITLE
ConcatenatingMediaSource stops sending timeline updates

### ISSUE THREAD

**Issue by IanDBird** [google/ExoPlayer#8033]
## 📱 Environment
- **Device**: NVIDIA SHIELD
- **ExoPlayer Version**: r2.12.0

## Details

We have our own implementation of a MediaSource that is responsible for playing Live content. We therefore frequently provide updates to the timeline as its duration changes over time. This custom MediaSource is used within a `ConcatenatingMediaSource`.

We found that after a number of timeline updates, our player instance was no longer receiving updates via `onTimelineChanged`. After digging into this, I found that the `ConcatenatingMediaSource.scheduleTimelineUpdate` was being called but was deciding to no-op because `timelineUpdateScheduled == true`. After adding in logging around when `timelineUpdateScheduled` was set to true and then reset, I found it was possible (i'm surprised myself) that the main thread was handling the message before the posting background thread was able to update `timelineUpdateScheduled`. This lead to a state where the media source thought it had an outstanding timeline update scheduled but it had already executed. I was able to reproduce this pretty easily

The following change appeared to resolve my issue:

```
diff --git a/library/core/src/main/java/com/google/android/exoplayer2/source/ConcatenatingMediaSource.java b/library/cor
e/src/main/java/com/google/android/exoplayer2/source/ConcatenatingMediaSource.java
index 48305bc916..281f7fe418 100644
--- a/library/core/src/main/java/com/google/android/exoplayer2/source/ConcatenatingMediaSource.java
+++ b/library/core/src/main/java/com/google/android/exoplayer2/source/ConcatenatingMediaSource.java
@@ -722,9 +722,10 @@ public final class ConcatenatingMediaSource extends CompositeMediaSource<MediaSo
   private void scheduleTimelineUpdate(@Nullable HandlerAndRunnable onCompletionAction) {
     if (!timelineUpdateScheduled) {
-      getPlaybackThreadHandlerOnPlaybackThread().obtainMessage(MSG_UPDATE_TIMELINE).sendToTarget();
       timelineUpdateScheduled = true;
+      getPlaybackThreadHandlerOnPlaybackThread().obtainMessage(MSG_UPDATE_TIMELINE).sendToTarget();
     }
     if (onCompletionAction != null) {
       nextTimelineUpdateOnCompletionActions.add(onCompletionAction);
     }
```

**Comment by marcbaechinger** [comment]
Thanks for reporting! Have you used your media source below 2.12 without seeing that issue?

**Comment by IanDBird** [comment]
We have, but in previous implementations we didn't rely on this timeline update in order to determine duration/etc. As part of updating to r2.12.0 we are trying to remove some of our own bespoke code to leverage what's there as much as possible. So it's unclear as to whether this is a recent regression or something that has been around for a while.

At the moment, I have applied my patch locally to our own repo and we are testing the suggested change.

**Comment by marcbaechinger** [comment]
>  I found it was possible (i'm surprised myself) that the main thread was handling the message before the posting background thread was able to update timelineUpdateScheduled

Hmm, I'm wondering why it appears that any of these messages are handled by the main thread. In general and when looking into the `ConcatenatingMediaSource` I would expect this should be the playback thread. It seems like `MSG_UPDATE_TIMELINE` or `MSG_ON_COMPLETION` is expected to be handled by the playback thread when looking into `getPlaybackThreadHandlerOnPlaybackThread()` and `ConcatenatingmediaSource.prepareSourceInternal`. 

Not sure what I'm looking for now, but would it be possible to do a bug report and upload it here or send it to dev.exoplayer@gmail.com using a subject in the format "Issue #8033"? Ideally with the 'EventLogger' attached if possible?
