### ISSUE TITLE
[Exoplayer -  audio auto focus]

### ISSUE THREAD

**Issue by chihung93** [google/ExoPlayer#8036]
Hello everyone, I have problem with Audio focus on Exoplayer 2.9.2
=> My expectation :
When my app is playing video -> pause Spotify
When my app is pause/stop/destroy video -> resume Spotify
But I have no idea about this, only stop spotify not pause when my app is playing video
Thanks

https://medium.com/google-exoplayer/easy-audio-focus-with-exoplayer-a2dcbbe4640e

````
binding.playerView.setControlDispatcher(object : DefaultControlDispatcher() {
                override fun dispatchSetPlayWhenReady(
                        player: Player?,
                        playWhenReady: Boolean
                ): Boolean {
                    player?.audioComponent?.setAudioAttributes(AudioAttributes.Builder()
                            .setUsage(C.USAGE_MEDIA)
                            .setContentType(C.CONTENT_TYPE_SPEECH)
                            .build(),true)
                    binding.playerView.keepScreenOn = playWhenReady
                    Hawk.put(FEED_VIDEO_AUTO_PLAY, playWhenReady)
                    setVideoPlayLargest()
                    return super.dispatchSetPlayWhenReady(player, playWhenReady)
                }
            })
<com.google.android.exoplayer2.ui.SimpleExoPlayerView
                        android:id="@+id/player_view"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:layout_gravity="center_horizontal"
                        app:controller_layout_id="@layout/video_tab_playback_control"
                        app:resize_mode="fixed_width"
                        app:surface_type="texture_view"
                        app:use_controller="true" />

```

**Comment by krocard** [comment]
First, if if what your app is playing is long duration (eg music), you should keep the current behaviour. Spotify and playbacks in general are only expected to resume after the playback of a notification or a short priority sound in general.

Now if your app is indeed playing a short sound, for Spotify or any other playback (eg Youtube) to resume after your app has stopped playback, [Audio focus transient](https://developer.android.com/reference/android/media/AudioFocusRequest) needs to be requested.

As you are using SimpleExoPlayer's AudioFocus management, a TRANSIENT audio focus request will be automatically used for usages such as `USAGE_ALARM` (pause), `USAGE_NOTIFICATION` (duck).
Thus switch `USAGE_MEDIA` for what usage best describe your usage.

**Comment by chihung93** [comment]
> First, if if what your app is playing is long duration (eg music), you should keep the current behaviour. Spotify and playbacks in general are only expected to resume after the playback of a notification or a short priority sound in general.

I have used Facebook app, they can play a long video and Pause Spotify, Video pause or stop => Spotify is automatically playing it again.

so How to implement like that with Exoplayer?

**Comment by krocard** [comment]
> I have used Facebook app, they can play a long video and Pause Spotify, Video pause or stop => Spotify is automatically playing it again.

Please refer to the linked documentation:
 [Audio focus transient](https://developer.android.com/reference/android/media/AudioFocusRequest)
> AudioManager#AUDIOFOCUS_GAIN_TRANSIENT is for a situation when you know your application is temporarily grabbing focus from the current owner, but the user expects playback to go back to where it was once your application no longer requires audio focus. An example is for playing an alarm, or during a VoIP call. The playback is known to be finite: the alarm will time-out or be dismissed, the VoIP call has a beginning and an end. When any of those events ends, and if the user was listening to music when it started, the user expects music to resume, but didn?t wish to listen to both at the same time.

Youtube for example does not request transient. I expect Facebook to only request transient for short videos while scrolling through your feed.

> so How to implement like that with Exoplayer?

Please refer to the last paragraph of my last message https://github.com/google/ExoPlayer/issues/8036#issuecomment-705489000. If you want to use USAGE_MEDIA with a transient audiofocus request, your app will need to [manage the audio focus itself](https://developer.android.com/reference/android/media/AudioFocusRequest), as it is not currently a supported use case.

**Comment by krocard** [comment]
Actually after checking the code more thoroughly, audio focus transient is not supported at all by SimpleExoPlayer(1), and there is no way to subclass AudioFocusManager.

So you will have to implement audio focus management in your app.
(1) https://github.com/google/ExoPlayer/blob/r2.12.0/library/core/src/main/java/com/google/android/exoplayer2/AudioFocusManager.java#L146

@Samrobbo maybe Audio focus improvement should be made, but the player API will need to be changed.

**Comment by Samrobbo** [comment]
You can see #7399 for an explanation into this more, and we currently have #7317 to track the addition of more audio focus modes.
