### ISSUE TITLE
Media item downloaded repeatedly when repeat mode is Player.REPEAT_MODE_ONE

### ISSUE THREAD

**Issue by littledot** [google/ExoPlayer#8038]
### [REQUIRED] Issue description
In 2.12.0, ExoPlayer will repeatedly download MediaItem until released, wasting user bandwidth.

https://i.imgur.com/nZDROLY.png
All these requests happened within 10 seconds of playing.

### [REQUIRED] Reproduction steps
Simply prepare a SimpleExoPlayer like so and check the network logs using your favorite MITM inspector.

    exoPlayer.setMediaItem(MediaItem.fromUri("https://i.imgur.com/dgNL2jK.mp4"))
    exoPlayer.prepare()
    exoPlayer.repeatMode = Player.REPEAT_MODE_ONE
    exoPlayer.seekTo(playbackTime)

This only happens with the new `.setMediaItem()` & `.prepare()` API.
The deprecated `.prepare(MediaSource)` still works correctly.

**Comment by marcbaechinger** [comment]
I think that works as intended. This behaviour was the same before version 2.12. 

But you can customize your player by using a `CacheDataSource` as [documented in the developer guide](https://exoplayer.dev/customization.html#caching-data-loaded-from-the-network). For the use case of small videos like your sample stream `https://i.imgur.com/dgNL2jK.mp4` a small sized [`SimpleCache`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/upstream/cache/SimpleCache.html) with a [LRU cache evictor](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/upstream/cache/LeastRecentlyUsedCacheEvictor.html ) is easy and sufficient.

Regarding the deprecated methods behaving differently, you can look into the implementation of the [`prepare(MediaSource)`](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/ExoPlayerImpl.java#L335) method to see there is no difference.

**Comment by littledot** [comment]
Are you sure you didn't misunderstand the issue? 

The new API has already downloaded the media, and is rendering it in a PlayerView. But for some reason, it decides to download the exact same file again & again & again non-stop.

I only took a screencap of 10 seconds and it downloaded the file 25 times. I could leave the player looping for 5 minutes, and it will download the file 750 times. 

None of this happens with the old API. Are you sure this is considered normal?

**Comment by marcbaechinger** [comment]
Not sure, but pretty sure? :) 

The Developer Guide says I should [use a CacheDataSource for temporarily cache data](https://exoplayer.dev/customization.html#caching-data-loaded-from-the-network).

In the code snippet you are preparing the player with a media item with a duration of 1 second while repeat mode ONE is selected. I assume we are having a [default buffer configuration](https://exoplayer.dev/doc/reference/constant-values.html#com.google.android.exoplayer2.DefaultLoadControl.DEFAULT_MIN_BUFFER_MS) telling the player to buffer 50 seconds ahead. To buffer 50 seconds the player then downloads  that file 50 times to make sure we can play ahead as we told. It's non-stop if not paused and once per second on average. This happens repeatedly unless the download is cached somehow ([see page in developer guide about caching](https://exoplayer.dev/customization.html#caching-data-loaded-from-the-network)).

I would consider this normal, or a reasonable behaviour, given looping a 1-sec video endlessly is not the primary use case of this library.

>  I could leave the player looping for 5 minutes, and it will download the file 750 times.

5 x 60 + 50 = 350 times.

When you say old API, do you mean an old version of an app you are having, or calling [a deprecated method](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/ExoPlayerImpl.java#L332) of the same version of which the [new API](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/ExoPlayerImpl.java#L351) produces described results?

**Comment by master255** [comment]
@littledot The best practice now is to cache content. The whole file. This significantly reduces the network load in most scenarios.

**Comment by littledot** [comment]
Thanks for working on caching, I appreciate the 2.12.0 changes that makes setting up a cache for SimpleExoPlayer much easier. But I'm talking about no-cache players, and I think you might be confusing Progressive vs Adaptive streams. :)

Behavior <2.12.0, with no cache configured:
Progressive streaming, using `.prepare(MedisSource)` -> only downloads once
DASH, HLS using `.prepare(MediaSource)` -> downloads non-stop (I understand the difference and expect that this is normal)

Behavior >= 2.12.0, with no cache configured:
Progressive streaming, using `.setMediaItem(MediaItem)` & `.prepare()` -> downloads non-stop
Progressive streaming, using `.prepare(MediaSource)` -> only downloads once
DASH, HLS using `.prepare(MediaSource)` -> downloads non-stop

But let me spell out why I think this is a big deal. :)

`.setMediaItem(MediaItem) + .prepare()` - a new API in 2.12.0 - is meant to deprecate `.prepare(MediaSource)`, yet they yield radically different behaviors when dealing with Progressive media types. This is a huge foot gun for anyone thinking this might just be another minor update. Especially since the javadocs for `.prepare(MediaSource)` make it sound like a simple find-and-replace refactor, but there's actually an undocumented breaking change when a Progressive media source is being passed in to `.setMediaItem(MediaItem)`.

If this inconsistency between prepare(MS) and prepare() is the way forward, I think it should at least be called out in the Javadocs.

**Comment by marcbaechinger** [comment]
Ok, thanks for clarification and helping me understand. I appreciate your patience.

I understand now that the issue says that 

```
player.setMediaItem(mediaItem);
player.prepare();
```

yields a totally different networking behaviour of the player than if you do the deprecated way which is

```
player.prepare(mediaSource);
```

I added back the bug label, so we investigate.

When you test and you do instead use the other, non deprecated, API based on media sources like so

```
exoPlayer.setMediaSource(mediaSource);
exoPlayer.prepare();
```

Do you see the same networking behaviour that repeatedly downloads the media instead of only once?

If it only downloads once with that, it would be a step forward for me solving that problem with your help. Could you then post the code how you create the `ProgressiveMediaSource` which you pass to `setMediaSource(ms)` and `prepare(ms)` ? Really appreciate your time!

**Comment by marcbaechinger** [comment]
>  Especially since the javadocs for .prepare(MediaSource) make it sound like a simple find-and-replace refactor, but there's actually an undocumented breaking change when a Progressive media source is being passed in to .setMediaItem(MediaItem)

I reviewed the JavaDoc of the deprecated `prepare(MediaSource)` method, it says that `setMediaSource(MediaSource)` should be used, which appears to me to be correct. Because if someone does some specific setup of a media source, like using a custom data source or something else which can be configured when using the factory directly, that media source still needs to be passed directly, because the internal media item to media source conversion may be different to what has been done by the developer before.

```
/** @deprecated Use {@link #setMediaSource(MediaSource)} and {@link #prepare()} instead. */
@Deprecated
void prepare(MediaSource mediaSource);
```

**Comment by littledot** [comment]
> I reviewed the JavaDoc of the deprecated prepare(MediaSource) method, it says that setMediaSource(MediaSource) should be used, which appears to me to be correct.

Thank you for pointing out the mistake I made about the docs; I mixed up `.setMediaSource()` & `.setMediaItem()` together due to how similar they look.

I tested `.setMediaSource() & .addMediaSource()` with Progressive media and it only downloads the media once. Here's my setup:
    
    val exoPlayer = SimpleExoPlayer.Builder(context).build().also { playerView.player = it }
    val dsf = OkHttpDataSourceFactory(okHttpClient, null)
    val mediaSource = ProgressiveMediaSource.Factory(dsf)
        .createMediaSource(Uri.parse("https://i.imgur.com/dgNL2jK.mp4"))
    // exoPlayer.setMediaSource(mediaSource)
    exoPlayer.addMediaSource(mediaSource)
    exoPlayer.prepare()

If you think this is a simple case of user error I am now at peace with that, after all I did RTFM incorrectly.

**Comment by marcbaechinger** [comment]
Cool! I'm glad it's working! :)

It seems that `okHttpClient` does the caching (TIL). It probably caches files in a behaviour similar to a web browser (honouring cache-control, max-age headers and the like). The `DefaultMediaSourceFactory` that is in charge for doing the media item to media source conversion uses the `DefaultDataSourceFactory` that makes HTTP requests with a plain http connection which is stateless and does not cache anything.

If you want to have the media item API use okhttp, you can inject the `OkHttpDataSourceFactory` into the default media source factory when building your player (not compiled and tested that code below, beware, but it should work that way). 

```
DefaultMediaSourceFactory defaultMediaSourceFactory = new DefaultMediaSourceFactory()
    .setDataSourceFactory(new OkHttpDataSourceFactory(okHttpClient, null));

SimpleExoPlayer player = new SimpleExoPlayer.Builder(context)
    .setMediaSourceFactory(defaultMediaSourceFactory)
    .build();
```
