### ISSUE TITLE
Cookie management fails on few devices and works after factory reset.

### ISSUE THREAD

**Issue by cbadhrinath** [google/ExoPlayer#8043]
We are using Exoplayer for our app with Akamai as a VOD resource provider.
Our player implementation works really well with the cookies provided by Akamai.
However, there were few devices which got reported for some playback failures.
On testing with an affected device, we noticed that it wasn't propagating the cookies as expected. 
We followed all the advices provided by the following threads: 
https://github.com/google/ExoPlayer/issues/3472
https://github.com/google/ExoPlayer/issues/625
However, none resolved the issue.
But, when we did a factory reset on the affected device, the cookie management started to work as expected.
We are trying to figure out how a playback stopped working, and doing a factory reset resolves it all.
Could there be a possible corruption with Android's Cookie manager ? 
Is there any other way to overcome these issues ?

**Comment by tonihei** [comment]
Cookie management is mostly independent from ExoPlayer and I think we can't debug that (even if it were a problem in the Android Cookie Manager). Please also see #7431 for some further explanations.

A potential alternative is to use `OkHttpDataSource` that allows to handle cookie management more directly (see linked StackOverflow post from #7431).

**Comment by tonihei** [comment]
Closing under the assumption that the question was answered.
