### ISSUE TITLE
MediaItem.Subtitle is missing some text-related fields.

### ISSUE THREAD

**Issue by tonihei** [google/ExoPlayer#8044]
### [REQUIRED] Issue description
2.12 changed the setup of `SingleSampleMediaSource` to always use a `MediaItem.Subtitle` instead of a `Format` object to define the properties of the single sample track. This removed the possibility to set any `Format` values that are not part of the `MediaItem.Subtitle` config. 

The following values are potentially text-related but can't be set anymore:
 - `Format.label`
 - `Format.roleFlags`
 - `Format.accessibilityChannel`

### [REQUIRED] Reproduction steps
Build a `SingleSampleMediaSource` with 2.11.0 and 2.12.0. Try to set `Format.label` or other values mentioned above. 

### [REQUIRED] Link to test content
n/a

### [REQUIRED] A full bug report captured from the device
n/a

### [REQUIRED] Version of ExoPlayer being used
2.12.0

### [REQUIRED] Device(s) and version(s) of Android being used
n/a

**Comment by marcbaechinger** [comment]
Yup, thanks for reporting. We will provide a fix asap and update this issue. :)

**Comment by giladna** [comment]
@marcbaechinger 

this is my temp fix for this 

https://github.com/google/ExoPlayer/compare/release-v2...giladna:2.12.0.1
