### ISSUE TITLE
does ExoPlayer internally perform below-mentioned adjustment as per users internet speed or is there access or settings provided in the library for the same so that  we can do so?

### ISSUE THREAD

**Issue by kvmoondra** [google/ExoPlayer#8052]
We are using [Chewie Player for flutter](https://pub.dev/packages/chewie) android app, it uses a [video player plugin](https://pub.dev/packages/video_player) for flutter internally and this video player plugin uses ExoPlayer internally to play videos on android devices.

We are using AWS media convert service which gives video output in HLS format. This helps us to show videos in lower resolution when there is a poor network connection(but what issue we are facing is that:
it is showing by default high-resolution video even at low internet speeds). 

**Do we need that to set up a player for this setting like:** 

1: How much video segments to buffer before playing(currently: the segment length is 3, seconds)?

2: How to set up the lowest and highest profile in video player i.e - RESOLUTION=480x270 is lowest and Highest as 1920x1080. For the Lowest profile required bandwidth is around 400 kbps

Hence when the speed is slow if it's even 400 Kbps or lower than that(we want the lowest resolution to play and that setting has to set in exoplayer) & whenever the speed is high then the resolution should get increased

**Following is example of how we are using video plugin and chewie player together:**

//Declaring values 

VideoPlayerController _controller;
ChewieController _chewieController;

// Init before using 
_controller = VideoPlayerController.network(video_url)
 ..initialize().then((_) {
   // Ensure the first frame is shown after the video is initialized, even before the play button has been pressed.
   setState(() {
     if(autoPlay)
     _controller.play();
   });

   _chewieController = ChewieController(
     videoPlayerController: _controller,
     aspectRatio: 3 / 2,
     autoPlay: true,
     looping: false,
   );
 });

// using them to show video content to user 
_controller.value.initialized
   ? AspectRatio(
       aspectRatio: _controller.value.aspectRatio,
       child: Chewie(
         controller: _chewieController,
       )
)

So my question is, **does ExoPlayer internally perform above-mentioned adjustment as per users internet speed or is there access provided in the library for the same so that  we can do so?**

Kindly let me know how to proceed.

Will wait to hear from you @ojw28 

Thanks & Regards
Kumar Vansh Moondra

**Comment by tonihei** [comment]
ExoPlayer is automatically adjusting the video quality by default and is also pre-buffering media without any special settings needed. 

If this isn't happening when using the Chewie player, you should probably report the problem to them.

**Comment by tonihei** [comment]
Closing under the assumption that the question was answered.
