### ISSUE TITLE
Implementing a DashManifestParser

### ISSUE THREAD

**Issue by AnassHmida** [google/ExoPlayer#8054]
Hello, I'm asking if you guys can show me a way to implement a way to retrieve a licenseURL using dash manifest from azure,
I saw issue  #3393 but unfortunately, it doesn't tell how to retrieve the license URL.
can anyone help me pls ??

**Comment by tonihei** [comment]
#3393 is already fully implemented and should just work out of the box. If you are have a specific problem related to that, please fill out the issue template completely.

**Comment by AnassHmida** [comment]
It's strange , i need to learn more about the behavior , i mean , when implementing it in my player , i added my manifest url , set the DRM type ,  added a random string in the licenseServer and add a token and my data plays normally with no problems , does that mean when there is an error in the licenseServer , the player tries to resolve a licenseServer from the manifest ??

**Comment by tonihei** [comment]
I can't really help you with that without knowing specific details and having access to example media etc.
If you media plays fine without license then it's probably not encrypted and doesn't need a license to play?

**Comment by AnassHmida** [comment]
My example is encrypted and token restricted : 
you can try it out here : 

https://ampdemo.azureedge.net/?url=https%3A%2F%2Fswannmediaservice-euwe.streaming.media.azure.net%2F95aae6ef-55a4-411d-9706-73890f5d2ba5%2FL%27Homme%20qui%20courait%20apre%CC%80s%20le%20Te.ism%2Fmanifest(format%3Dmpd-time-csf%2Cencryption%3Dcenc)&widevine=true&widevinetoken=Bearer%3DeyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL3d3dy5zYXRvcmlwb3AuY29tLyIsImF1ZCI6InVybjpzYXRvcmlwb3AiLCJleHAiOjE3MTA4MDczODksIm5iZiI6MTYwMTMwMDA3OH0.O_41HbAcE8kFDivOM9Q4AL2z-4TMUTLchuUoyxCdDKY

the licenseServer is already inside of the manifest, azure media services implement it like that.

**Comment by tonihei** [comment]
The stream on this page (https://swannmediaservice-euwe.streaming.media.azure.net/95aae6ef-55a4-411d-9706-73890f5d2ba5/L'Homme%20qui%20courait%20apre%CC%80s%20le%20Te.ism/manifest(format=mpd-time-csf,encryption=cenc)) is not playable in the ExoPlayer demo app. Is that what you were expecting given you added a random string as license? Please clarify your problem in more detail if you'd like us to look further.
