### ISSUE TITLE
Custom style for each cue

### ISSUE THREAD

**Issue by AdisAlagic** [google/ExoPlayer#8056]
I need a custom typeface and color for upper cue. That's a problem for me and I can't find any fix for that.

Thanks for your time in advance.

**Comment by tonihei** [comment]
There may be multiple options to achieve this:
- Use a subtitle format that lets you define the style in the source. This is the ideal option as the subtitle data will then show up in the same way in other players or platforms as well and no player customizations are needed.
- Intercept the `Cue`s before forwarding them to `SubtitleView`. You can add your own `TextOutput` listener to the player and forward all `Cue`s styled to your requirements to the `SubtitleView`.
- Use `SubtitleView.setStyle` to define the style you want to use for your captions. This applies to all captions that don't have embedded styles and may not fit your request.
- Use a customized `SubtitleView` class by forking the original and make whatever adjustment you'd like to make.

**Comment by tonihei** [comment]
Closing under the assumption that the question was answered.
