### ISSUE TITLE
Exoplayer 2.12, dose not load local subtitle file.

### ISSUE THREAD

**Issue by ominfowave** [google/ExoPlayer#8057]
Exoplayer version: 2.12.0
Android version: 9

Even after going through many questions on Stackoverflow and other threads we could not find any solution for the subtitle issue in Exoplayer.

Following is the code snippet we are using to load video and subtitle from local storage.

    public void setVideo(String absolutePath, String vtt){
        player = new SimpleExoPlayer.Builder(this).build();
        videoView.setPlayer(player);
      //  MediaItem mediaItem = MediaItem.fromUri(absolutePath);
        MediaItem.Subtitle subtitle = new MediaItem.Subtitle(Uri.parse(vtt),MimeTypes.TEXT_VTT,"en-US");
        List<MediaItem.Subtitle> subtitleList = new ArrayList<>();
        subtitleList.add(subtitle);

        videoView.setShowSubtitleButton(true);
        MediaItem mediaItem = new MediaItem.Builder()
                .setUri(absolutePath)
                .setDrmUuid(C.WIDEVINE_UUID)
                .setDrmMultiSession(true)
                .setSubtitles(subtitleList)
                .build();
        player.setMediaItem(mediaItem);
        player.setPlayWhenReady(true);
        player.prepare();

    }

Here absolutePath is path to the video and vtt is the path to .srt subtitle file. We would really appreciate any suggestions or alternative way to achieve this.

**Comment by marcbaechinger** [comment]
Thanks for your report! Can you provide me with a bug report, please? I think there should be something in the logs in cases when this fails. Your code looks good as far as I can tell.

Also important would be what the value of `vtt` is. Can you send me this as well please? So I can test and evaluate what's going wrong.

If you're unable to share bug reports or test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #8057". Please also update this issue to indicate you’ve done this.

**Comment by icbaker** [comment]
> Here absolutePath is path to the video and vtt is the path to .srt subtitle file.

Assuming your .srt file is in [SubRip](https://en.wikipedia.org/wiki/SubRip#File_format) format and not [WebVTT](https://www.w3.org/TR/webvtt1/), you need to pass [`MimeTypes.APPLICATION_SUBRIP`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/util/MimeTypes.html#APPLICATION_SUBRIP) to the `MediaItem.Subtitle` constructor, not `MimeTypes.TEXT_VTT`. WebVTT files usually use the .vtt extension.

The formats are similar (WebVTT is based on SubRip), but different enough that our WebVTT parser will almost certainly fail when pointed at a SubRip file.
