### ISSUE TITLE
Can the encrypted video of HLS and the key downloaded from the player be modified and then written back to the player

### ISSUE THREAD

**Issue by litaogithub** [google/ExoPlayer#8059]
As the title

**Comment by tonihei** [comment]
I don't really understand the question. Could you explain in a bit more detail?

**Comment by litaogithub** [comment]
We have a requirement that HLS encrypted videos be re-encrypted to improve security, which means that the ExoPlayer download encryptionKey needs to be modified. Will it affect the workflow behind the ExoPlayer? Does ExoPlayer support such changes? thank you

**Comment by litaogithub** [comment]
We have a requirement that HLS encrypted videos be re-encrypted to improve security, which means that the ExoPlayer download encryptionKey needs to be modified. Will it affect the workflow behind the ExoPlayer? Does ExoPlayer support such changes? thank you


在 2020年10月10日 00:13，tonihei<notifications@github.com> 写道：


I don't really understand the question. Could you explain in a bit more detail?

**Comment by tonihei** [comment]
If you want to modify the data before it's read (including the kind of re-encryption you mention), you probably need to provide your own `DataSource` that reads and modifies the data. Have a look at other `DataSource` implementations to see how forwarding works.

**Comment by tonihei** [comment]
Closing under the assumption that the question was answered.
