### ISSUE TITLE
Fatal signal 11

### ISSUE THREAD

**Issue by juanpef** [google/ExoPlayer#806]
I am using ExoPlayer in our Android app form playing IPTV videos, and we have problems because sometimes app crashes with this log:

09-18 06:52:39.450: I/OMXClient(2732): Using client-side OMX mux.
09-18 06:52:39.450: E/ACodec(2732): [OMX.rk.video_decoder.avc] storeMetaDataInBuffers failed w/ err -2147483648
09-18 06:52:39.490: I/OMXClient(2732): Using client-side OMX mux.
09-18 06:52:39.490: I/(2732): new RKOMXPlugin
09-18 06:52:39.490: A/libc(2732): Fatal signal 11 (SIGSEGV) at 0x7a70a050 (code=1), thread 3050 (MediaCodec_loop)

Somebody knows what could be the problem? I am using dev brunch.

Thanks

**Comment by ojw28** [comment]
Please provide additional information as described [here](https://google.github.io/ExoPlayer/2015/10/01/reporting-issues.html). Thanks.
