### ISSUE TITLE
Opus doesn't work with m3u8

### ISSUE THREAD

**Issue by Zevsus** [google/ExoPlayer#8072]
Good afternoon, add the opus extension according to the instructions. But when I turn on the stream (m3u8) with opus, I get an error.  
```
E/ExoPlayerImplInternal: Source error
      com.google.android.exoplayer2.ParserException: Cannot find sync byte. Most likely not a Transport Stream.
        at com.google.android.exoplayer2.extractor.ts.TsExtractor.findEndOfFirstTsPacketInBuffer(TsExtractor.java:411)
        at com.google.android.exoplayer2.extractor.ts.TsExtractor.read(TsExtractor.java:279)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.feedDataToExtractor(HlsMediaChunk.java:376)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.loadMedia(HlsMediaChunk.java:343)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.load(HlsMediaChunk.java:314)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)Cannot find sync byte. Most likely not a Transport Stream.
```

```
Version 2.11.8.
            DefaultRenderersFactory defaultRenderersFactory = new DefaultRenderersFactory(this).setExtensionRendererMode(DefaultRenderersFactory.EXTENSION_RENDERER_MODE_PREFER);
            try {
                audioPlayer = new SimpleExoPlayer.Builder(this, defaultRenderersFactory).build();
            }catch (Exception ignored){}
```
[playlist.zip](https://github.com/google/ExoPlayer/files/5371306/playlist.zip)

**Comment by marcbaechinger** [comment]
Seems like the `TsExtractors` starts extracting and finds that what is referenced in the m3u8 file is not a ts file that is referenced.

The Opus samples need to be in a container that needs to be supported by HLS. The [supported formats section about HLS](https://exoplayer.dev/supported-formats.html#hls) lists what that can be. 

Looking at the supported format page, I don't think you need the opus extension for that btw. Probably best to try without first.

**Comment by marcbaechinger** [comment]
The media urls in the m3u8 file you added as ZIP file give me a http forbiddden. So I can not really check what container it is using.

**Comment by Zevsus** [comment]
is work https://api-v2.soundcloud.com/media/soundcloud:tracks:619905291/c713fe8d-fb5d-4ce0-9b36-f32c2d016554/stream/hls?client_id=tjYModkBgXhr3bXS6OoNjnLR7wLLzy2i
not work https://api-v2.soundcloud.com/media/soundcloud:tracks:619905291/9bfb8ad5-35a0-4ae4-9097-2c7aabec81e0/stream/hls?client_id=tjYModkBgXhr3bXS6OoNjnLR7wLLzy2i

**Comment by marcbaechinger** [comment]
Sorry, you need to be a bit more clear. These urls return a JSON file. If you want to help me efficiently please become a bit more verbose. :)

**Comment by Zevsus** [comment]
There is a link to url.Generated

**Comment by marcbaechinger** [comment]
Exactly. And every media url gives me a HTTP forbidden.

I suspect these are not TS files. Can you check wehther the container of these files is one of the [containers supported by HLS](https://exoplayer.dev/supported-formats.html#hls)?

**Comment by Zevsus** [comment]
https://api-v2.soundcloud.com/media/soundcloud:tracks:619905291/9bfb8ad5-35a0-4ae4-9097-2c7aabec81e0/stream/hls?client_id=73a3db34973aee46de488c0b902b5cc3
Try this should get the link.

**Comment by Zevsus** [comment]
Write when check delete.

**Comment by marcbaechinger** [comment]
This is an OGG container with Opus samples. You need to provide a container that is [supported by HLS as documented in the supported formats page](https://exoplayer.dev/supported-formats.html#hls).

**Comment by Zevsus** [comment]
Thank you correctly, I understood in this format, I can not lose anything.
