### ISSUE TITLE
Mov file with pcm_u8 audio track couldn't play correctly

### ISSUE THREAD

**Issue by xufuji456** [google/ExoPlayer#8073]
Hello, guys of developer, nice to contact you again. I Found that Mov file with pcm_u8 audio track couldn't play correctly. It uses Mp4Extractor, when running on the method of readSample, the sampleSize of audioTrack is always 1. As a result, audio frame couldn't be decoded correctly. Looking forward to your reply.

Here is the testing video: [https://drive.google.com/file/d/1QMX--yv2jloMbANXWQbAepF1n71Pm7RJ/view](url)

**Comment by marcbaechinger** [comment]
Mov is the Apple Quicktime format. This is similar to MP4 but not exactly. Some files may work with ExoPlayer while some do not. So in your case it seems that the MP4 extractor does not like it, I'm afraid:

```
Caused by: com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (FlvExtractor, FlacExtractor, WavExtractor, FragmentedMp4Extractor, Mp4Extractor, AmrExtractor, PsExtractor, OggExtractor, TsExtractor, MatroskaExtractor, AdtsExtractor, Ac3Extractor, Ac4Extractor, Mp3Extractor) could read the stream.
```

Why are you thinking it has something to do with the pcm_u8 audio track? Have you been able to play a mov file with another audio track?

> , the sampleSize of audioTrack is always 1

Can you give me a bit more details on how you see the error message you are reporting above? For me the file can not be extracted at all, so I don't see tracks at all like you say.

**Comment by marcbaechinger** [comment]
I assign to @kim-vde so you have someone looking into it who actually knows all the extractor details.

**Comment by xufuji456** [comment]
> Mov is the Apple Quicktime format. This is similar to MP4 but not exactly. Some files may work with ExoPlayer while some do not. So in your case it seems that the MP4 extractor does not like it, I'm afraid:
> 
> ```
> Caused by: com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (FlvExtractor, FlacExtractor, WavExtractor, FragmentedMp4Extractor, Mp4Extractor, AmrExtractor, PsExtractor, OggExtractor, TsExtractor, MatroskaExtractor, AdtsExtractor, Ac3Extractor, Ac4Extractor, Mp3Extractor) could read the stream.
> ```
> 
> Why are you thinking it has something to do with the pcm_u8 audio track? Have you been able to play a mov file with another audio track?
> 
> > , the sampleSize of audioTrack is always 1
> 
> Can you give me a bit more details on how you see the error message you are reporting above? For me the file can not be extracted at all, so I don't see tracks at all like you say.

The mov with pcm_u8 frame always output sampleSize of 1.  In other words, it samples one byte to decode every time.

I try to play mov with pcm_s16le(swot), and it works well. I found that it needs to rechunk these rawAudio frame which has fixSampleSize. Mov with pcm_s16le has been rechunked, so it could play correctly. As a result, I rechunk pcm_u8 frame, then it could play too. I could pull a request to fix this problem.

**Comment by kim-vde** [comment]
Here is what I observed:

- `Mp4Extractor.sniff()` returns false for the input file you provided. In other words, the `Mp4Extractor` does not recognise the file as one it supports. This is because the input file does not have any ftyp box. This box is mandatory in the MP4 format but not in the QuickTime format (but it is strongly recommended). This is what @marcbaechinger was referring to. ExoPlayer doesn't currently support mov files without ftyp box.
- If you force the use of the `Mp4Extractor` (in other words if you don’t sniff the file to check whether it is supported), the extractor finds the 2 tracks (one of type jpeg, the other of type raw) but none of them is supported. As a result, the extractor ends playback.

> the sampleSize of audioTrack is always 1

My observation is that it the extractor doesn't send any sample. Can you explain how you arrived to this conclusion?

**Comment by xufuji456** [comment]
@kim-vde, Yes, you are right. There is no ftyp box in this mov file. I make it compatible without ftyp box in the `Mp4Extractor.sniff()`. Something like `MPEG4Extractor` of the Android framework source code:[https://www.androidos.net.cn/android/9.0.0_r8/xref/frameworks/av/media/extractors/mp4/MPEG4Extractor.cpp](url).
I refer to the method of `BetterSniffMPEG4` which in the bottom of `MPEG4Extractor`, it will scan the box of moov when sniffing. Here is the simplified source code:
```
// Attempt to actually parse the 'ftyp' atom and determine if a suitable
// compatible brand is present.
// Also try to identify where this file's metadata ends
// (end of the 'moov' atom) and report it to the caller as part of
// the metadata.
static bool BetterSniffMPEG4(DataSourceBase *source, float *confidence) {
    static const off64_t kMaxScanOffset = 128ll;
    off64_t offset = 0ll;
    bool foundGoodFileType = false;
    off64_t moovAtomEndOffset = -1ll;
    bool done = false;

    while (!done && offset < kMaxScanOffset) {
       ......
        switch (chunkType) {
            case FOURCC('f', 't', 'y', 'p'):
            .......
            break;
            case FOURCC('m', 'o', 'o', 'v'):
            {
                moovAtomEndOffset = offset + chunkSize;
                done = true;
                break;
            }
        }
    }

    if (!foundGoodFileType) {
        return false;
    }
    return true;
}
```
