### ISSUE TITLE
Source error. com.google.android.exoplayer2.source.UnrecognizedInputFormatException in Flutter

### ISSUE THREAD

**Issue by theAkshay60** [google/ExoPlayer#8074]
```
E/ExoPlayerImplInternal(10866): Source error.
E/ExoPlayerImplInternal(10866): com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor, AmrExtractor) could read the stream.
```

The video urls can't be opened inside a browser. It can only be opened inside the video player.
I get a list of 8 url which I fed to the video player, however only one url was able to play which is mentioned below:

https://media.lwwindia.in/books/9789389859737/videos/9.1+Jaw+deviation+-+Left.mp4?Expires=1602685241&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9tZWRpYS5sd3dpbmRpYS5pbi9ib29rcy85Nzg5Mzg5ODU5NzM3L3ZpZGVvcy85LjErSmF3K2RldmlhdGlvbistK0xlZnQubXA0IiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjAyNjg1MjQxfX19XX0_&Signature=Jtzuf9aSlHOmogDW976XufASfJMyIi2Q2-lMgCXieVmiKAwglmWvwrbdaM5jKTgEOm9TP5S2fq58JhBUQjw4MxyiO~kYFuwv9Z4pwLk9MFR~uwyDCyVBJ9hylS-9F34KDCcRQ2mGMwt2yh5tQm~bA~zIyBRFA-6rPei7m6ahiPeKjgqCwNUF4SfKtPVtsbfJNTJlZgC2ZP~GuNedz8JfyOSdR51IOvcnMvwH-D6FDyPtpyliHO-wj8fBgHnQgnsuEbVvdyLO2zr7J1x5iIGFBebZGovfvwTxdAXVeWv8unvsTXwLnyAaYYjYiMV3-6ePj1GqDXAGsBmYCKsK2Hqc6A__&Key-Pair-Id=APKAISGYBLHSD54HPXYQ

**Comment by marcbaechinger** [comment]
I'm getting a 403 when trying the above uri from within the player.

```
com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
```

The log line you pasted above says that the format is not not recognized by the player. This can be because the format is not supported. 

Please let me know how I can access the stream so I can investigate. I can not really help more with the current information available.

**Comment by theAkshay60** [comment]
You won't be able to access the url inside a browser. You'll have to feed the url inside some sort of video player. We've a website and all the url are working there. Inside the exoplayer, some url are working and some are not. There is also one issue. When I try to replay the video, It doesn't load.

**Comment by marcbaechinger** [comment]
I tried from within ExoPlayer which is to the best of my knowledge some sort of a video player. I got a 404 as the log line I pasted above indicates. You need to make the url is accessible by the player on the server side. I can not really help you with that. If you can provide me with a url that is accessible I can look whether this plays.
