### ISSUE TITLE
Can setVideoScalingMode work with SimpleExoPlayer?

### ISSUE THREAD

**Issue by skreenr** [google/ExoPlayer#8081]
Per https://github.com/google/ExoPlayer/issues/2016 discussing VIDEO_SCALING_MODE_SCALE_TO_FIT_WITH_CROPPING
 @ojw28 commented on Nov 21, 2016:

_-We're going to add a setVideoScalingMode method to SimpleExoPlayer_  

Yet I am not observing cropping of video in my code:

         Simple_player = new SimpleExoPlayer.Builder(getBaseContext()).build();
            Uri uri = RawResourceDataSource.buildRawResourceUri(R.raw.videofile );
            DataSource.Factory dataSourceFactory = new DefaultDataSourceFactory(getBaseContext(), "com.domain.theapp");
            videoSource = new ExtractorMediaSource.Factory( dataSourceFactory ).createMediaSource(uri);
            Simple_player.prepare(videoSource );
            Simple_player.setRepeatMode(Player.REPEAT_MODE_ONE);
            Simple_player.setVideoScalingMode(Renderer.VIDEO_SCALING_MODE_SCALE_TO_FIT_WITH_CROPPING);

Am I missing something?

**Comment by andrewlewis** [comment]
Are you saying that calling the method has no effect? There are a few limitations for this scaling mode to be aware of. See [the javadoc for the MediaCodec constant](https://developer.android.com/reference/android/media/MediaCodec#VIDEO_SCALING_MODE_SCALE_TO_FIT_WITH_CROPPING), which mentions requirements for 1:1 pixel aspect ratio and not using rotation (see also #1482). It also looks like this scaling mode only works with `SurfaceView` not `TextureView`. Also you need to be using `MediaCodec`-based renderer (this will be the case by default). Please check whether your implementation is running into one of these limitations.

Aside: you can set the scaling mode when building `SimpleExoPlayer` as an alternative to calling it once you already have a player instance, if you prefer.

**Comment by skreenr** [comment]
On the _Aside_:  exactly How I do that? 
this works with FIT_WITH_CROPPING mode?

**Comment by andrewlewis** [comment]
> On the Aside: exactly How I do that?

Via [this SimpleExoPlayer.Builder method](https://cs.opensource.google/exoplayer/ExoPlayer/+/release-v2:library/core/src/main/java/com/google/android/exoplayer2/SimpleExoPlayer.java;l=412-427;drc=862cf26534d5050a6706f341f97fce3da2b4a06a). This doesn't do anything really different to what you were doing before, so the first paragraph of my previous comment still applies.

**Comment by skreenr** [comment]
I see the Builder, I don't see how it gets into the player though

**Comment by andrewlewis** [comment]
When you call `build` on the builder it returns the player instance you need to use.

**Comment by skreenr** [comment]
Can you pass a code example please with  FIT_WITH_CROPPING mode?
 
You are correct: in my code there is no observable difference, e.g. no video cropping observed

**Comment by andrewlewis** [comment]
In the demo app's player_activity.xml set the resize mode of the `StyledPlayerView` element to fill the container by adding `app:resize_mode="fill"`, then in PlayerActivity.java add `.setVideoScalingMode(Renderer.VIDEO_SCALING_MODE_SCALE_TO_FIT_WITH_CROPPING)` before the call to build the `SimpleExoPlayer`.

When you play a sample video you should see the video is scaled/cropped as expected. Then if you remove the call to `setVideoScalingMode` and try again you should see that the video is stretched.

The reason the resize mode of the `AspectRatioFrameLayout` needs to be set is that it will relayout itself so the video fits at its normal aspect ratio. If the containing surface view has the same aspect ratio as the video then setting the scaling mode won't do anything.

**Comment by skreenr** [comment]
We don't do Demo, @andrewlewis 
We don't use activity XML either
It is a background service we do
I am sorry your answer does not really help
Can you please ask somebody who can produce a relevant Code snippet?

Thank you

**Comment by skreenr** [comment]
to sum up, we need a Java code showing how to get Fit with Cropping mode work
Thank you

**Comment by andrewlewis** [comment]
The ExoPlayer demo app is a Java sample project where you can try out fit with cropping, as described in my previous comment.

**Comment by skreenr** [comment]
It is not our scenario kind of app
Can you please drop a Java snippet we can use in a service?

**Comment by andrewlewis** [comment]
I'm afraid we don't have sample code for that specific use case. If you go through the steps I outlined above to try this in the demo app, you can just translate that over to your own app yourself (the way it works doesn't need to be significantly different).
