### ISSUE TITLE
[Feature] - Lazy Queue

### ISSUE THREAD

**Issue by xeinebiu** [google/ExoPlayer#8082]
With the latest version of **Exo Player**, we can pass a **List**<_MediaItem_> and the player handles the queue itself very great.

The issue on my side it is, that the Playlist is stored on Server and I need to retrieve all URI's of each song before creating the **MediaItem's**. URI's are expired if they are not used within a limited time.

I tried to extend the **MediaItem** and do the reuqest only when **Exo Playe**r calls _getUri_() but I found the class is marked as _**final**_.

Is there any solution for my issue?

Thanks for your time & Best Regards.

**Comment by marcbaechinger** [comment]
I think the `ResolvingDataSource` could be helpful for your use case. It allows you to modify the URI just before the network request is made.

The JavaDoc of the [`ResolvingDataSource.Resolver.resolveDataSpec()`](https://github.com/google/ExoPlayer/blob/83477497c19959f4b33c3af57cc1e646fcc3848a/library/core/src/main/java/com/google/android/exoplayer2/upstream/ResolvingDataSource.java#L43) says the following:

```
/**
 * Resolves a {@link DataSpec} before forwarding it to the wrapped {@link DataSource}. This
 * method is allowed to block until the {@link DataSpec} has been resolved.
 *
 * <p>Note that this method is called for every new connection, so caching of results is
 * recommended, especially if network operations are involved.
 *
 * @param dataSpec The original {@link DataSpec}.
 * @return The resolved {@link DataSpec}.
 * @throws IOException If an {@link IOException} occurred while resolving the {@link DataSpec}.
 */
DataSpec resolveDataSpec(DataSpec dataSpec) throws IOException;
```

So if you have a way to know whether the uri is still valid (not expired), best would be to avoid loading the new URI from the server and only do that if really required.


You can inject the `ResolvingDataSource.Factory` into the `DefaultMediaSourceFactory` when building your player:
```
DataSource.Factory dataSourceFactory = new ResolvingDataSource.Factory(
    httpDataSourceFactory,
    // Provide just-in-time URI resolution logic.
    (DataSpec dataSpec) -> dataSpec.withUri(resolveUri(dataSpec.uri)));

SimpleExoPlayer player = new SimpleExoPlayer.Builder(context)
    .setMediaSourceFactory(new DefaultMediaSourceFactory(dataSourceFactory))
    .build();
```

Please, let me know whether this suits your use case.

**Comment by xeinebiu** [comment]
> I think the `ResolvingDataSource` could be helpful for your use case. It allows you to modify the URI just before the network request is made.
> 
> The JavaDoc of the [`ResolvingDataSource.Resolver.resolveDataSpec()`](https://github.com/google/ExoPlayer/blob/83477497c19959f4b33c3af57cc1e646fcc3848a/library/core/src/main/java/com/google/android/exoplayer2/upstream/ResolvingDataSource.java#L43) says the following:
> 
> ```
> /**
>  * Resolves a {@link DataSpec} before forwarding it to the wrapped {@link DataSource}. This
>  * method is allowed to block until the {@link DataSpec} has been resolved.
>  *
>  * <p>Note that this method is called for every new connection, so caching of results is
>  * recommended, especially if network operations are involved.
>  *
>  * @param dataSpec The original {@link DataSpec}.
>  * @return The resolved {@link DataSpec}.
>  * @throws IOException If an {@link IOException} occurred while resolving the {@link DataSpec}.
>  */
> DataSpec resolveDataSpec(DataSpec dataSpec) throws IOException;
> ```
> 
> So if you have a way to know whether the uri is still valid (not expired), best would be to avoid loading the new URI from the server and only do that if really required.
> 
> You can inject the `ResolvingDataSource.Factory` into the `DefaultMediaSourceFactory` when building your player:
> 
> ```
> DataSource.Factory dataSourceFactory = new ResolvingDataSource.Factory(
>     httpDataSourceFactory,
>     // Provide just-in-time URI resolution logic.
>     (DataSpec dataSpec) -> dataSpec.withUri(resolveUri(dataSpec.uri)));
> 
> SimpleExoPlayer player = new SimpleExoPlayer.Builder(context)
>     .setMediaSourceFactory(new DefaultMediaSourceFactory(dataSourceFactory))
>     .build();
> ```
> 
> Please, let me know whether this suits your use case.

This does the job. Thank you very much @marcbaechinger
