### ISSUE TITLE
UnrecognizedInputFormatException: Input does not start with the #EXTM3U header

### ISSUE THREAD

**Issue by newtestpage** [google/ExoPlayer#8085]
Hi
I am working on online video player and I wanted to play a hls  with my exoplayer . exoplayer works fine with all of hls I had but with this one I got error . 

```
E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:554)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: com.google.android.exoplayer2.source.UnrecognizedInputFormatException: Input does not start with the #EXTM3U header.
        at com.google.android.exoplayer2.source.hls.playlist.HlsPlaylistParser.parse(HlsPlaylistParser.java:201)
        at com.google.android.exoplayer2.source.hls.playlist.HlsPlaylistParser.parse(HlsPlaylistParser.java:62)
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:179)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
```

the Url I wanted to play has session and I can not sent it as static link . But You can get it from follow link . at the second line after "HlsStreamURL"

could you help me to solve this problem ?
thanks in advance .

**Comment by andrewlewis** [comment]
I took a stream URL from the provided plist file and it played fine for me in the demo app, though I needed to enable cleartext requests (for example, via `android:usesCleartextTraffic="true"`).

You are probably already aware but just to be clear the plist file itself is not playable by ExoPlayer -- we need an HLS manifest to play.

I will leave this open for a while in case you can provide further steps to help us reproduce the issue, but as things stand it looks like everything is working as expected.

**Comment by newtestpage** [comment]
Hi 
thanks for your response .I tested with demo app and it works fine . Problem is with my app .  I tried to make my exoplayer like demo app . But it didn't help me . I don't know which part is wrong or different . this is my playeractivity  code and my demoUtil is copied from demo app. 

`

    @SuppressLint("SourceLockedOrientationActivity")
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_player);


        dataSourceFactory = DemoUtil.getDataSourceFactory(this);



        ///get video address 
        channelAddress = getIntent().getStringExtra("channelNameAddress");
  

    @Override
    public void onStart() {
        super.onStart();

  	initilizePlayer();
    }

    @Override
    public void onResume() {
        super.onResume();
       
     }


       

    @Override
    public void onPause() {

        if (Util.SDK_INT <= 23) {
            releasePlayer();
        }
        super.onPause();

    }

    @Override
    public void onStop() {
        super.onStop();
        if (Util.SDK_INT > 23) {
            releasePlayer();

        }
    }



    private void initializePlayer() {
        if (player == null ) {

            RenderersFactory renderersFactory =
                    DemoUtil.buildRenderersFactory(/* context= */ this, false);
            MediaSourceFactory mediaSourceFactory =
                    new DefaultMediaSourceFactory(dataSourceFactory);
                         //   .setAdsLoaderProvider(this::getAdsLoader)
                           // .setAdViewProvider(playerView);

           
            trackSelector = new DefaultTrackSelector(PlayerActivity.this);
            DefaultTrackSelector.Parameters defaultTrackParam = trackSelector.buildUponParameters().build();
            trackSelector.setParameters(defaultTrackParam);

            player = new SimpleExoPlayer.Builder(PlayerActivity.this,renderersFactory)
                    .setMediaSourceFactory(mediaSourceFactory)
                    .setTrackSelector(trackSelector)
                    .build();

            player.addAnalyticsListener(new EventLogger(trackSelector));

            debugViewHelper = new DebugTextViewHelper(player, txtChannelName);
            debugViewHelper.start();

            playerView.setPlayer(player);
		
            Uri uri = null;
            if (channelAddress != null) {
                uri = Uri.parse(channelAddress);

            }

         
            MediaSource mediaSource = buildMediaSource(uri);

            player.setPlayWhenReady(playWhenReady);
            player.seekTo(currentWindow, playbackPosition);
            player.addListener(playbackStateListener);


            player.setMediaSource(mediaSource,false);
            player.prepare();

          

          
        hideSystemUi();


        });**/
    }

    private void releasePlayer() {
        if (player != null) {

            playbackPosition = player.getCurrentPosition();
            currentWindow = player.getCurrentWindowIndex();
            playWhenReady = player.getPlayWhenReady();
            player.removeListener(playbackStateListener);
            player.release();
            player = null;
        }
    }




    private MediaSource buildMediaSource(Uri uri) {

        HlsMediaSource.Factory hlsMediaSource =
                new HlsMediaSource.Factory(dataSourceFactory);
         
            return hlsMediaSource.createMediaSource(MediaItem.fromUri(uri));
    }


    
    @SuppressLint("InlinedApi")
    private void hideSystemUi() {
        playerView.setSystemUiVisibility(View.SYSTEM_UI_FLAG_LOW_PROFILE
                | View.SYSTEM_UI_FLAG_FULLSCREEN
                | View.SYSTEM_UI_FLAG_LAYOUT_STABLE
                | View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY
                | View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION
                | View.SYSTEM_UI_FLAG_HIDE_NAVIGATION);
    }


 
        @Override
        public void onPlayerError(ExoPlaybackException error) {
            if (isBehindLiveWindow(error)) {
                releasePlayer();
                initializePlayer();

            } else {
                playerView.showController();
            }
            switch (error.type) {
                case ExoPlaybackException.TYPE_SOURCE:

                    // Log.e(TAG, "TYPE_RENDERER: " + error.getRendererException().getMessage());

                    break;

                case ExoPlaybackException.TYPE_RENDERER:
                    //  Log.e(TAG, "TYPE_RENDERER: " + error.getRendererException().getMessage());
                    break;

                case ExoPlaybackException.TYPE_UNEXPECTED:
                    //  Log.e(TAG, "TYPE_UNEXPECTED: " + error.getUnexpectedException().getMessage());
                    break;
            }
        }
    }

    private static boolean isBehindLiveWindow(ExoPlaybackException e) {
        if (e.type != ExoPlaybackException.TYPE_SOURCE) {
            return false;
        }
        Throwable cause = e.getSourceException();
        while (cause != null) {
            if (cause instanceof BehindLiveWindowException) {
                return true;
            }
            cause = cause.getCause();
        }
        return false;
    }

}
`

I think maybe it can because of mediasource method but I coudn't find how it done on demo app . 
Could you help me on this case ?
Best Regards

**Comment by andrewlewis** [comment]
To track down what's going wrong, I'd set a breakpoint just before passing the `channelAddress` URI to `buildMediaSource` and check exactly what's in it. There may be an issue with escaping for example. You could also try hard-coding the string to play in the sources and seeing if the issue is still reproducible.

I can't see anything else obvious that could cause the issue in the provided code snippet though (most of it isn't relevant to the problem). By the way, you can use `player.setMediaItem` to avoid needing code to build the media source yourself.

**Comment by andrewlewis** [comment]
> I think maybe it can because of mediasource method but I coudn't find how it done on demo app .

See the code to initialize the player in [PlayerActivity.java](https://github.com/google/ExoPlayer/blob/8a0d52be4b5402af0987fc7d009bc49977c72b67/demos/main/src/main/java/com/google/android/exoplayer2/demo/PlayerActivity.java#L276).

**Comment by droidwithme** [comment]
@andrewlewis 
`/ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.source.UnrecognizedInputFormatException: Input does not start with the #EXTM3U header.
        at com.google.android.exoplayer2.source.hls.playlist.HlsPlaylistParser.parse(HlsPlaylistParser.java:149)
        at com.google.android.exoplayer2.source.hls.playlist.HlsPlaylistParser.parse(HlsPlaylistParser.java:48)
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:138)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:320)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)`


`public class ExoPlayerJavaActivity extends AppCompatActivity {
    private boolean playWhenReady = true;
    private int currentWindow = 0;
    private long playbackPosition = 0;
    private SimpleExoPlayer player;
    private PlayerView playerView;
    private View loading;`
    `@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_exo_player_java);
        playerView = findViewById(R.id.video_view);
        loading = findViewById(R.id.loading);
        prepareAndPlay()
    }`
    
    `private void prepareAndPlay() {
        //--------------------------------------
        //Creating default track selector
        TrackSelection.Factory adaptiveTrackSelection = new AdaptiveTrackSelection.Factory(new DefaultBandwidthMeter());
        player = ExoPlayerFactory.newSimpleInstance(
                new DefaultRenderersFactory(ExoPlayerJavaActivity.this),
                new DefaultTrackSelector(adaptiveTrackSelection),
                new DefaultLoadControl());
        playerView.setPlayer(player);
        DefaultBandwidthMeter defaultBandwidthMeter = new DefaultBandwidthMeter();
        DataSource.Factory dataSourceFactory = new DefaultDataSourceFactory(ExoPlayerJavaActivity.this,
                Util.getUserAgent(ExoPlayerJavaActivity.this, "Employee Management"), defaultBandwidthMeter);
        String hls_url = "https://www.youtube.com/watch?v=Lha9n8VJf0";
        Uri uri = Uri.parse(hls_url);
        Handler mainHandler = new Handler();
        MediaSource mediaSource = new HlsMediaSource(uri,
                dataSourceFactory, mainHandler, null);
        player.prepare(mediaSource);
        player.setPlayWhenReady(playWhenReady);
        player.addListener(new Player.EventListener() {
            @Override
            public void onTimelineChanged(Timeline timeline, Object manifest, int reason) {
            }

            @Override
            public void onTracksChanged(TrackGroupArray trackGroups, TrackSelectionArray trackSelections) {
            }

            @Override
            public void onLoadingChanged(boolean isLoading) {
            }

            @Override
            public void onPlayerStateChanged(boolean playWhenReady, int playbackState) {
                switch (playbackState) {
                    case ExoPlayer.STATE_READY:
                        loading.setVisibility(View.GONE);
                        break;
                    case ExoPlayer.STATE_BUFFERING:
                        loading.setVisibility(View.VISIBLE);
                        break;
                }
            }

            @Override
            public void onRepeatModeChanged(int repeatMode) {
            }

            @Override
            public void onShuffleModeEnabledChanged(boolean shuffleModeEnabled) {
            }

            @Override
            public void onPlayerError(ExoPlaybackException error) {
            }

            @Override
            public void onPositionDiscontinuity(int reason) {
            }

            @Override
            public void onPlaybackParametersChanged(PlaybackParameters playbackParameters) {
            }

            @Override
            public void onSeekProcessed() {
            }
        });
        player.seekTo(currentWindow, playbackPosition);
        player.prepare(mediaSource, true, false);
    }

    @Override
    public void onStart() {
        super.onStart();
       
    }

    private void releasePlayer() {
        if (player != null) {
            playbackPosition = player.getCurrentPosition();
            currentWindow = player.getCurrentWindowIndex();
            playWhenReady = player.getPlayWhenReady();
            player.release();
            player = null;
        }
    }

    @Override
    public void onPause() {
        super.onPause();
        if (Util.SDK_INT <= 23) {
            releasePlayer();
        }
    }

    @Override
    public void onStop() {
        super.onStop();
        if (Util.SDK_INT > 23) {
            releasePlayer();
        }
    }
}`

I'm getting same error, while playing the youtube's live videos.
` implementation 'com.google.android.exoplayer:exoplayer-core:2.8.3'
    implementation 'com.google.android.exoplayer:exoplayer-hls:2.8.3'
    implementation 'com.google.android.exoplayer:exoplayer-ui:2.8.3'`
