### ISSUE TITLE
How to use 2 ImaAdsLoader instances with exoplayer

### ISSUE THREAD

**Issue by krackjack234** [google/ExoPlayer#8089]
### [REQUIRED] 
Searched documentation and issues

### [REQUIRED] 
We wanted to use 2 IMAAdsLoader instances, one to load preroll and another for midroll & postrolls.
We want the preroll IMAAdsLoader to be preloaded with a static ad tag whereas the midroll IMAAdsLoader can be loaded with a dynamic ad tag (targeted for an asset)

Please let us know how can we add 2 Ad loaders and start playing a content following exoplayer extension approach

We tried below code but it didnot work for us

    
 ```
    preAdsLoader = new ImaAdsLoader(this, Uri.parse(getString(R.string.preroll_ad_tag_url)));
    
    midAdsLoader = new ImaAdsLoader(this, Uri.parse(getString(R.string.midroll_ad_tag_url)));

    preAdsLoader.setPlayer(player);
    midAdsLoader.setPlayer(player);

    DataSource.Factory dataSourceFactory =
        new DefaultDataSourceFactory(this, Util.getUserAgent(this, getString(R.string.app_name)));

    ProgressiveMediaSource.Factory mediaSourceFactory =
        new ProgressiveMediaSource.Factory(dataSourceFactory);

    // Create the MediaSource for the content you wish to play.
    MediaSource mediaSource =
        mediaSourceFactory.createMediaSource(Uri.parse("https://storage.googleapis.com/gvabox/media/samples/stock.mp4"));

    // Create the AdsMediaSource using the AdsLoader and the MediaSource.
    AdsMediaSource adsMediaSource =
        new AdsMediaSource(mediaSource, dataSourceFactory, preAdsLoader, playerView);

    AdsMediaSource adsMediaSource1 =
            new AdsMediaSource(adsMediaSource, dataSourceFactory, midAdsLoader, playerView);


    player.prepare(adsMediaSource1, false, false);


    // Set PlayWhenReady. If true, content and ads will autoplay.
    player.setPlayWhenReady(true);

```

The player instance didn't start Ad playback in this case.
Please let us know how we can achieve this using IMA extension approach.

Thanks

**Comment by andrewlewis** [comment]
Having another ads media source as the content for an ads media source (like "new AdsMediaSource(adsMediaSource, dataSourceFactory, midAdsLoader, playerView);") is not supported. Please merge the preroll/midroll ad tags.
