### ISSUE TITLE
ExoPlayer seem to cutting off audio from the MP3 file

### ISSUE THREAD

**Issue by pratikjk** [google/ExoPlayer#809]
Hi,
I am tying to play a mp3 file saved locally on an android device. The audio file contains speech audio. I am seeing an issue consistently that the player cuts off the last word either completely or part of it. I compiled Exoplayer from both  master branch as well as dev and I can see the issue in both cases. When I play the same mp3 file in Android Media Player or some different media player it works fine.

Also, I can see that the audio is cutoff before we receive the playBackState=ended.

All files that I am playing have following metadata if that helps -:
MPEG-2 Layer III audio, 
48 kbps (CBR),
24000 Hz, 
mono

Edit:
This issue is on Kindle devices, tested on Nexus 7 it works fine

**Comment by ojw28** [comment]
Kindle devices have known compatibility issues. See for example [this](https://forums.developer.amazon.com/forums/thread.jspa?threadID=5067).

**Comment by ojw28** [comment]
Closing this. Hopefully ExoPlayer compatibility issues are fixed in FireOS 5.
