### ISSUE TITLE
Exoplayer black screen sometimes

### ISSUE THREAD

**Issue by punitagoel2403** [google/ExoPlayer#8093]
Exoplayer is working fine, but the video in the recyclerview, at times shows black screen. The audio in the background keeps running, but the video is black. There is no specific time when it happens. It is happening randomly. Also, it happens in recylerview only. I am using singleton object for Exoplayer. Please help and suggest.

**Comment by andrewlewis** [comment]
When you see the problematic behavior please could you take a bug report via `adb bugreport` and attach it here or email it to `dev.exoplayer@gmail.com` with subject `Issue #8093`, as requested in the [new issue template](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/question.md)? Then we can see if there's any information in the logging about what is going wrong. Thanks.

**Comment by punitagoel2403** [comment]
Emailed 2 days ago, how long can I expect for the answer?

**Comment by andrewlewis** [comment]
Note: #7750 looks like the same issue. Can we close either this issue or the other one to avoid duplication of effort?

I didn't spot any sign of issues with the media framework, nor any ExoPlayer logs (which would include a version number) in the provided logging, but it is just a short snippet. So I don't think there's enough information here for me to help.

Here are some things to investigate/try:
- You noted in the email that the `SurfaceView`'s surface is being destroyed. Have you found that this is correlated with the video not showing up? If a SurfaceView is on the screen then it should have a corresponding surface. Are you passing the surface to the player yourself, and if so, do you definitely do this at the right time?
- This topic has been covered in a few issues in the past. See #867 (and some issues referencing that like #7947, #7482).
- It's worth being aware that Android devices may not support instantiating multiple hardware video decoders at once, and if you have multiple players in a scrolling list then there is a risk that video playback can't start because there is no hardware decoder available. This is covered on a few issues including #1286.

**Comment by punitagoel2403** [comment]
Tried everything with no solution or reason to the problem.

- You noted in the email that the SurfaceView's surface is being destroyed. Have you found that this is correlated with the video not showing up? If a SurfaceView is on the screen then it should have a corresponding surface. Are you passing the surface to the player yourself, and if so, do you definitely do this at the right time?
-- I said this on basis of logs that I shared on email. I am comparatively new to exoplayer. 
-- Also, this black out happens when the player is once removed from the previous view and then added to the new view, based on recycler view scrolling.

- This topic has been covered in a few issues in the past. See #867 (and some issues referencing that like #7947, #7482).
-- These links speak of how to show in recyclerview, which I am already following.

- It's worth being aware that Android devices may not support instantiating multiple hardware video decoders at once, and if you have multiple players in a scrolling list then there is a risk that video playback can't start because there is no hardware decoder available. This is covered on a few issues including #1286.
-- Also, I am having only one player, which I am adding to or removing from the view based on the current holder in the recycler view.

It actually works fine many a times, but doesn't work sometimes, and the video is blacked out. Kindly help. 

Also, if you can tell me what exactly you want from the adb logs, so that I can provide you that info, since I am not sure what all info does it contain from my phone.(Looks like almost everything).

**Comment by andrewlewis** [comment]
I don't think we'll be able to make much progress without reproducing the issue here. It would be helpful if you could make a minimal test project (or modification to the ExoPlayer demo app) that reproduces the bug and share that.

**Comment by punitagoel2403** [comment]
I have made it better by moving the addview method from onScrollStateChanged to onPlayerStateChanged( ready state)

Still it was failing sometimes, so I added a handler, which keeps checking if video has started and the pointer for some reason didn't go to onPlayerStateChanged method.

It is lot better, as in if black screen appears and we scroll once and back then it gets displayed. But still it is not working perfectly. 

Creating a demo app needs some time. Will try to make it ASAP and provide.

**Comment by ajaasazeez** [comment]
> I have made it better by moving the addview method from onScrollStateChanged to onPlayerStateChanged( ready state)
> 
> Still it was failing sometimes, so I added a handler, which keeps checking if video has started and the pointer for some reason didn't go to onPlayerStateChanged method.
> 
> It is lot better, as in if black screen appears and we scroll once and back then it gets displayed. But still it is not working perfectly.
> 
> Creating a demo app needs some time. Will try to make it ASAP and provide.

can you please explain a bit more how you solved the issue?

**Comment by punitagoel2403** [comment]
> > I have made it better by moving the addview method from onScrollStateChanged to onPlayerStateChanged( ready state)
> > Still it was failing sometimes, so I added a handler, which keeps checking if video has started and the pointer for some reason didn't go to onPlayerStateChanged method.
> > It is lot better, as in if black screen appears and we scroll once and back then it gets displayed. But still it is not working perfectly.
> > Creating a demo app needs some time. Will try to make it ASAP and provide.
> 
> can you please explain a bit more how you solved the issue?

I moved the addview method from onScrollStateChanged  to onPlayerStateChanged method of exoplayer. By adding view in onscrollstatechanged it was trying to add the view at every fraction of second. 

Second, I added handler, which keeps checking state of a variable if the view is not added then add the view, this way, the view gets added most of the times either via onPlayerStateChanged method, or by the handler. It resolves in most of the cases but still not 100%. Hope this helps.
