### ISSUE TITLE
Can we pre-fetch and hold ads to show at a particular time using exoplayer-ima-extension?

### ISSUE THREAD

**Issue by Manvendra-Jadon** [google/ExoPlayer#8094]
I want to add custom cue points, where i want to pre-fetch ads and hold them before showing at a particular time. Is there any way to do this using exoplayer-ima-extension?
Any help/hint around this would be appreciable.

**Comment by andrewlewis** [comment]
If this isn't covered in the comment on your previous issue #8070, please could you reply there with more details about what you need? I will close this one as it seems very similar to that issue.
