### ISSUE TITLE
role of MediaSource in 2.12.0

### ISSUE THREAD

**Issue by yoobi** [google/ExoPlayer#8096]
### [REQUIRED] Question
I've looked in the issues but didn't find anything concerning my question.
I'm currently upgrading a project with exoplayer 2.11.4 to 2.12.0 so I've been to https://codelabs.developers.google.com/codelabs/exoplayer-intro to take a look and saw that `ProgressiveMediaSource`, `HlsMediaSource`, etc... weren't needed anymore to play a video.

Code below is working without `MediaSource`
```kotlin
val mediaItem = MediaItem.Builder()
            .setUri(HLS_STATIC_URL)
            .setMimeType(MimeTypes.APPLICATION_M3U8)
            .build()
        exoPlayer = SimpleExoPlayer.Builder(this).build()
//        val videoSource = HlsMediaSource.Factory(dataSourceFactory).createMediaSource(mediaItem)

        with(exoPlayer) {
            playWhenReady = isPlayerPlaying
            seekTo(currentWindow, playbackPosition)
            setMediaItem(mediaItem, false)
//            setMediaSource(videoSource, false)
            prepare()
        }
```

My question is what is the difference between the use of `setMediaItem` and `setMediaSource` ?

Some side questions:

I've been looking at the [doc](https://exoplayer.dev/media-items.html)
Where do I find the `mediaId` and `metadata` of the code below, is it a random int ?
```kotlin
MediaItem mediaItem = new MediaItem.Builder()
    .setUri(videoUri)
    .setMediaId(mediaId)
    .setTag(metadata)
    .build();
```

**Comment by marcbaechinger** [comment]
If you are using the API based on `MediaItem` like `player.setMediaItem(item)` the player internally converts the media item to a `MediaSource` and then passes the source to the media source based API. 

This conversion from item to source is carried out by a `MediaSourceFactory`. By default the `DefaultMediaSourceFactory` is used for this. You can choose to inject either a custom implementation of `MediaSourceFactory` or configure the `DefaultMediaSourceFactory` to tailor it to your use case. The developer guide explains how you can [customize media source creation](https://exoplayer.dev/media-sources.html#customizing-media-source-creation) when building your player.

Alternatively you can use the media source API directly:

```
// Using the media item API
player.setMediaItem(mediaItem);

// internally results by default in creating a media source and using the media source API
MediaSource mediaSource = new DefaultMediaSourceFactory(context).createMediaSource(mediaItem);
exoplayer.setMediaSource(mediaSource);
```

[`mediaId`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/MediaItem.Builder.html#setMediaId-java.lang.String-) is an optional identifier of the media item and the `tag` of the media item is a aribtrary object apps want to store with the media item. Both are optional, so you don't need to provide them. 

Apps may want to use these to know what item is playing. For instance an app can listen to a media item transition with an `Player.EventListener` and update the ui or similar:

```
@Override
public void onMediaItemTransition(
    @Nullable MediaItem mediaItem, @MediaItemTransitionReason int reason) {
  updateUiForPlayingMediaItem(mediaItem.mediaId);
}
```

The player does not use/need `mediaId` or the tag for playback. This is data owned and used by an app.

**Comment by yoobi** [comment]
Thanks for your answer, if I understand correctly, form 2.12.0 I don't need to create `MediaSource` to play a video because it is done internally by exoplayer, but I can pass the `MediaSource` to the player if I want to add caching or a custom it with a certain behavior ?

If I use a custom `MediaSource` should I remove `setMediaItem(mediaItem)` from the exoplayer and use 
```
val mediaSource = HlsMediaSource.Factory(dataSourceFactory).createMediaSource(mediaItem)
exoplayer.setMediaSource(videoSource, false)
```
is there a point of having both `setMediaItem` and `setMediaSource` for this example ?

**Comment by marcbaechinger** [comment]
You can use `setMediaItem` or `setMediaSource` as you wish. It probably makes sense for an app to only use one of them or the other and not both but this is up to you. For the player it boils down to the same.

**Comment by yoobi** [comment]
Okay I see, thanks for the explanation :)
