### ISSUE TITLE
custom layout for Ads

### ISSUE THREAD

**Issue by sajjadshahbazi** [google/ExoPlayer#8098]
I show ads with ImaAdsLoader. I want to use a custom layout for show ads. how do I do this?

**Comment by andrewlewis** [comment]
Customizing the ad layout (skip button, countdown timer, ...) is not possible per the IMA SDK policy. See [this thread](https://groups.google.com/g/ima-sdk/c/c9Ed45PedFk/m/6Md7CELQIQAJ). Please feel free to post on the [IMA SDK forum](https://groups.google.com/g/ima-sdk/) if you still want to make a feature request in this area (it's not really an ExoPlayer or IMA extension issue).

If the customizations you want to make don't affect the ad overlay please give some more details and we can try to help. As an example, the ExoPlayer IMA extension does allow you to pass slots for companion ads via `ImaAdsLoader.Builder`.

**Comment by sajjadshahbazi** [comment]
I want to change the position, background, language, and font of skip button, countdown timer.

**Comment by andrewlewis** [comment]
The language can be set by calling `ImaAdsLoader.Builder.setImaSdkSettings` and passing an `ImaSdkSettings` instance where you've customized the language (see also [Localization](https://developers.google.com/interactive-media-ads/docs/sdks/android/client-side/localization)).

Modifying the position, background and font for the skip button and countdown timer are not supported per IMA SDK policy.

**Comment by sajjadshahbazi** [comment]
can I invisible or gone skip button, countdown timer?

**Comment by andrewlewis** [comment]
That wouldn't be allowed by policy, as I understand it.

**Comment by ojw28** [comment]
Not allowing customization is already documented [here](https://exoplayer.dev/ad-insertion.html). Removing documentation candidate label. I will also add some specific examples to the documentation of things that cannot be customized.

Regarding the language, we should update the IMA extension to default to the device locale. This should remove the need to change the language manually in almost all circumstances, at which point that probably doesn't need documenting separately to the existing IMA documentation.
