### ISSUE TITLE
How to flip video and some other feature.

### ISSUE THREAD

**Issue by design365** [google/ExoPlayer#8099]
### [REQUIRED] Use case description
When using exoplayer, the following features are required. I don’t know if exoplayer supports it:
1. It can be flipped horizontally, vertically, rotated 90 degrees to the left and 90 degrees to the right
2. When playing, you can freely set the width and height ratio of the video, and there is also a video with a blurred background. Just think that when YouTube plays some 9:16 videos, in order to adapt to the width of the player, it will set the background blur video.

**Comment by andrewlewis** [comment]
> It can be flipped horizontally, vertically, rotated 90 degrees to the left and 90 degrees to the right

One way to do this is render to a `TextureView` then [set its transformation](https://developer.android.com/reference/android/view/TextureView#setTransform(android.graphics.Matrix)) as desired.

There are caveats to using `TextureView` [listed here](https://exoplayer.dev/ui-components.html#choosing-a-surface-type). If you can't use `TextureView`, it's also possible to set a rotation when configuring the `MediaCodec`, which you could do by subclassing `MediaCodecVideoRenderer` and passing your subclass via a custom `RenderersFactory` when building the player.

> When playing, you can freely set the width and height ratio of the video, and there is also a video with a blurred background. Just think that when YouTube plays some 9:16 videos, in order to adapt to the width of the player, it will set the background blur video.

This is not something ExoPlayer supports at the moment, and I think it's unlikely we will implement support as it is quite a niche feature.

You can still implement it in your app by using ExoPlayer to render to an off-screen `SurfaceTexture` then using GL to copy the video decoder output to a `GLSurfaceView` (for example). If you do that you have complete control to transform the video output as you wish (including flipping/rotating as from your first question), so you can do one copy with a blur to draw the background and another copy without a blur to show the main video. Going into detail is beyond the scope of this issue tracker but you could using the [gl demo](https://github.com/google/ExoPlayer/tree/release-v2/demos/gl) as a starting point.
