### ISSUE TITLE
Lock Screen Media Button Control

### ISSUE THREAD

**Issue by orcunkobal** [google/ExoPlayer#8107]
Hi,

Is there any way to use two different media session instance? I ask it because I have a scenario like that;

For example, I have a MediaService.kt which is bounded to the MainActivity. Also, I want to play a video from VideoPlayerActivity it can be a live stream or not. I'm preparing everything for VideoPlayerActivity and the video is playing. But, the default control dispatcher event can't catch anything from VideoPlayerActivity. It's catching from MediaService.kt. For this reason, I can't handle the play/pause, etc from VideoPlayerActivity. Why this happening? How can I separate it?

The Exoplayer Version is 2.12.0.

**Comment by andrewlewis** [comment]
I'm finding it difficult to get a picture of the setup and understand the problem based on your description. It might help if you could give provide diagram or more detailed/structured description.

Are MediaService and VideoPlayerActivity using separate ExoPlayer instances? If so I think you can just have one media session active at a time, linked up to the relevant player instance?

**Comment by orcunkobal** [comment]
Yes, they both have different ExoPlayer instances. 

**MusicService.kt**
```
class MusicService : MediaBrowserServiceCompat(){
    private val mediaSessionConnectorControlDispatcher by lazy {
        return@lazy MediaSessionConnectorControlDispatcher()
    }

    private val player: SimpleExoPlayer by lazy {
        return@lazy SimpleExoPlayer.Builder(this@ MusicService).setMediaSourceFactory(defaultMediaSourceFactory).build().apply {
            setHandleAudioBecomingNoisy(true)
            addListener(playerListener)
        }
    }

  override fun onCreate(){
     super.onCreate()
    val sessionActivityPendingIntent =
                packageManager?.getLaunchIntentForPackage(packageName)?.let { sessionIntent ->
                    PendingIntent.getActivity(this, 0, sessionIntent, 0)
                }

        mMediaSession = MediaSessionCompat(this, userAgent).apply {
            setSessionActivity(sessionActivityPendingIntent)
            isActive = true
        }
        sessionToken = mMediaSession.sessionToken

        mMediaSessionConnector = MediaSessionConnector(mMediaSession).apply {
            setPlayer(player)
            setControlDispatcher(mediaSessionConnectorControlDispatcher)
            setPlaybackPreparer(mediaSessionConnectorPlaybackPreparer)
            setCustomActionProviders(aoCustomShuffleButton)
        }
 }

private inner class MediaSessionConnectorControlDispatcher : DefaultControlDispatcher() {
        override fun dispatchSetPlayWhenReady(player: Player, playWhenReady: Boolean): Boolean = handleNtfAndMediaSessionPlayPause(playWhenReady)
    }

}

```

I control media actions from MediaSessionConnectorControlDispatcher class. Notifcation, headset etc.


VideoPlayerActivity.kt

```
    private val player by lazy {
        return@lazy SimpleExoPlayer.Builder(this@VideoPlayerActivity).setMediaSourceFactory(defaultMediaSourceFactory).build().apply {
            setHandleAudioBecomingNoisy(true)
            addListener(mPlayerListener)
        }
    }
  override fun onCreate(){
     super.onCreate()
player.run {
      setAudioAttributes(viewModel.audioAttributes, true)
       setMediaItem(viewModel.mediaItem!!)
       prepare()
}
mMediaSessionConnector.setPlayer(player)
mMediaSessionConnector.setQueueNavigator(TimeLineQueuNavigator())
                mMediaSessionConnector.setControlDispatcher(object : DefaultControlDispatcher() {
                    override fun dispatchSetPlayWhenReady(player: Player, playWhenReady: Boolean): Boolean = handlePlayPause(playWhenReady)
                })
                mMediaSession.isActive = true
                player.play()
}
```

The **dispatchSetPlayWhenReady** is not calling in VideoPlayer for this session. But, the MusicService is catching **dispatchSetPlayWhenReady**. This reason, I can't control the player instance on VideoPlayer. I just want to handle the events on VideoPlayer, not in the Service.

I test the lock screen media buttons on Samsung S8.

**Comment by andrewlewis** [comment]
Can you have just a single player instance with a media session? I'm not sure why you need two.

**Comment by orcunkobal** [comment]
Yes, I can. I just wondered why this is not working even I release the service. Anyway, thank you for your quick response.
