### ISSUE TITLE
Dynamically change renderer mode

### ISSUE THREAD

**Issue by hinditutorpoint** [google/ExoPlayer#8109]
It is possible to dynamically change renderer mode in when video is playing

**Comment by ojw28** [comment]
It's unclear what the question is that you're asking. What is a "renderer mode"? Please provide a more detailed explanation of your question.

**Comment by hinditutorpoint** [comment]
hardware and software decoder mode

**Comment by ojw28** [comment]
It's not possible to do this mid-playback, since at that point the decoder has been instantiated and is in use.
