### ISSUE TITLE
Sending user data along with query strings to widevine proxy

### ISSUE THREAD

**Issue by randeeppr** [google/ExoPlayer#811]
Hi,
We are trying to send user-data along with the other query strings to the widevine proxy.
In com/google/android/exoplayer/demo/WidevineTestMediaDrmCallback.java
We have done the following:
- changed `defaultUri` to your own license proxy
- updated `executeKeyRequest` by adding X-Subscription-ID to the POST header before calling executePost().

The following is our code.
```
		Map<String, String> headers = new HashMap<String, String>();
		headers.put("X-Subscription-ID", CacheData.getSubscriberId());
		return DemoUtil.executePost(url, request.getData(), headers);
But on the proxy, I'm trying to get the X-Subscriber-ID by parsing the query strings.
		url_components = urlparse.urlparse(self.request.url)
		query_string_components = urlparse.parse_qs(url_components.query)
		self.provider = (query_string_components['provider'][0]
						if 'provider' in query_string_components else PROVIDER)
		self.subscriberid = (query_string_components['X-Subscription-ID'][0]
						 if 'X-Subscription-ID' in query_string_components else "")	 
```
But its not printing. May be its not going in query strings. How can we do that? Please help
Regards,
Randeep

**Comment by jeoliva** [comment]
Hi Randeep,

Looking at your code (please, note you can use markdown to format code in your github comments: https://guides.github.com/features/mastering-markdown/), seems you are passing your Subsription-ID parameter in the HTTP header, not as a query string parameter. 

Assuming you are using python in your proxy server (looks like that), it would be like:
```
 self.request.headers.get("X-Subscription-ID", "");
```

**Comment by ojw28** [comment]
@randeeppr, did the above resolve the issue for you? Thanks!

**Comment by randeeppr** [comment]
@ojw28 I'll check tomorrow from office (IST time). But it would be better if we can pass the user data in query strings. It will be more secure.

**Comment by ojw28** [comment]
I'm not sure as to the security of each approach, but I don't think there's anything stopping you from setting it in the query string. It's your code that's putting the data in the header, after all :). I think putting the data in the query string consists of writing the data directly into the url?

**Comment by randeeppr** [comment]
I'll check with our developers. I tried to implement the solution jeoliva suggested. But it didnt work. I'm not a developer and python is new to me. 
```
self.request.headers.get("X-Subscription-ID", "");
```
Wondering why I dont get anything when I search with self.request.headers.get in google :|

**Comment by jeoliva** [comment]
@randeeppr, there is not a single way of reading http headers in python, that depends on the python framework/lib you are using in your proxy. What I pasted above was just an example of reading headers using WebOb python library (a very used one, http://docs.webob.org/en/latest/reference.html#id1) but of course you could be using a different one (Django, for example). So, the best idea is talking with the colleague that is developing the proxy and asking him to read the variable from the http header.

Regarding security, why do you think using HTTP headers is less secure than using query string parameters? In fact, in general, thinking on the most secure option is more recomendable using cookies/http headers than query string parameters. In this specific case (HTTP request done by Exoplayer) both options are equally secure, but if you are building a web application (or a Flash/Silverlight media player) and are thinking on sending sensitive information in query string parameter, try to avoid that as information could be compromised (http referrer, browser history, etc).

**Comment by randeeppr** [comment]
Thanks @jeoliva and @ojw28 
We were able to do this with the help of WebOb library. We have used headers for this. Thanks a lot for explaining the security part.

Regards,
Randeep
