### ISSUE TITLE
How to work with MediaItem.MediaMetadata 

### ISSUE THREAD

**Issue by yoobi** [google/ExoPlayer#8110]
### [REQUIRED] Question

I was looking at `MediaMetadata` class and there is only one attribute `title`. Is this class supposed to be override in the project to add for example `duration`, `placeholderPicture` etc... ?

**Comment by marcbaechinger** [comment]
If you want to store additional attributes with a media item, I'd suggest to use the tag for that. That's an arbitrary object you can set as the tag in the builder:

```
MyMediaData myObject = new MyMediaData(duration, placeholderPicture);
MediaItem mediaItem = new MediaItem.Builder().setUri(uri).setTag(myObject).build();
```

Later you can retrieve this custom tag object in the `playbackProperties` object of the media item.

```
MyMediaData myObject = (MyMediaData)mediaItem.playbackProperties.tag;
```

Let me know if this helps for your use case.

**Comment by yoobi** [comment]
Oh yes it might work I didn't think about the `tag`, i'll try that out :)
Thanks

**Comment by yoobi** [comment]
I've tried using `tag` so far so good, except when I'm trying to retrieve the tag from the `downloads` I lost the `tag`.

I got the following flow:
- First screen with `Exoplayer` and a button to download the video (that's in this activity that I set my `tag` on `mediaItem`)
- Second screen with all the videos (a `recyclerview` which shows my current/downloaded video), following the [`Demo`](https://github.com/google/ExoPlayer/blob/59b34ede6165d029d86a677fea73a5dd0dd55c74/demos/main/src/main/java/com/google/android/exoplayer2/demo/DownloadTracker.java#L71) I get a `HashMap<Uri, Download>`

How can I get my `tag` back ? I see a function [`toMediaItem()`](https://github.com/google/ExoPlayer/blob/59b34ede6165d029d86a677fea73a5dd0dd55c74/library/core/src/main/java/com/google/android/exoplayer2/offline/DownloadRequest.java#L225) for `DownloadRequest` object but when I inspect the function there is no set of the `tag`

**Comment by marcbaechinger** [comment]
The download request that is persistent to the database does not store the entire media item but only what is needed for downloading. You need to use the `mediaId` to identify your media item and then lookup up your custom data with it from somewhere where you store your data.

**Comment by yoobi** [comment]
Just to be sure I've understood, I should persist in a database my custom tag with `mediaId` as primary key, so that when I need to have these datas I can just get it though my database instance ?

**Comment by ojw28** [comment]
You can leverage `DownloadRequest.data` for this, if you don't want to persist your data somewhere completely separate. You'll need to take care of serializing and de-serializing your data into and out of that field though, since it's just a `byte[]`.

**Comment by yoobi** [comment]
Indeed you're right I though I had to put the url in `DownloadRequest.data` this will be much easier to handle :)

Thank you
