### ISSUE TITLE
How to save the modified PlaybackParameters audio into storage

### ISSUE THREAD

**Issue by AliilA233** [google/ExoPlayer#8111]
I wonder how to save the audio into storage after changing the `PlaybackParameters `such as speed and pitch : 

```
  public void setSpeed(float speed) {
        PlaybackParameters param = new PlaybackParameters(speed, (float) getCurrentPitch());
        player.setPlaybackParameters(param);
    }


    public void setPitch(float pitch) {
        PlaybackParameters param = new PlaybackParameters((float) getCurrentTempo(), pitch);
        player.setPlaybackParameters(param);
    }
```

I tried to use **FFmpeg** but the output (pitch and speed) audio is different from the `ExoPlayer` 

```
  float pitch = (float) (getCurrentPitch());
  float tempo = (float) (getCurrentTempo());
  int sampleRate = 32000;
String cmd = "-y -i " + copiedPath + " -filter_complex asetrate=" + sampleRate + "*" + pitch + "^(-10/12),atempo=" + tempo + "^(-10/12)" + " " + outputPath;
```

Thank you for your help

**Comment by ojw28** [comment]
ExoPlayer does not currently support recording use cases, so this is something you'll have to figure out for yourself I'm afraid!

**Comment by AliilA233** [comment]
@ojw28 thank you, I'm not asking for recording, the audio file is already exist, I've searched and I found [TeeAudioProcessor ](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/audio/TeeAudioProcessor.html) and [WavFileAudioBufferSink](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/audio/TeeAudioProcessor.WavFileAudioBufferSink.html), but till now I didn't find any example of how to use these class.

**Comment by ojw28** [comment]
You're asking how to record audio played back from ExoPlayer (whether that audio is adjusted from original audio that already exists doesn't change that). So, I'm afraid please see my response above.
