### ISSUE TITLE
Video colors are messed up when using surface_type=surface_view

### ISSUE THREAD

**Issue by ltomov** [google/ExoPlayer#8112]
Up until now I was using the player with surface_type=texture_view, however on slower devices the videos lagged. I noticed that switching to surface_view improves the performance significantly, however I faced another problem.

On some devices the colors are somehow messed up - they appear a lot more red-ish and just not that vivid. I tested on two devices, both API version 26 - one of them displays them fine, the other one is messed up.

And also I now get some flickering of the video - black screen appears for ~100ms a few seconds after the beginning.

I tried 2 exoplayer versions - 2.12.1 and 2.7.3 - no difference. I tried 2 videos - mp4/x264 and webm/vp9 - again no difference.
As far as I can tell there's nothing else interesting about the setup, just a full-screen video, no scrolling, etc.

Is there anything I can do to fix that, besides using texture_view? 
Would it help if I use the VP9 extension?

Thanks!

**Comment by ojw28** [comment]
I suggest you start by properly filling in our [issue template](https://github.com/google/ExoPlayer/issues/new?assignees=&labels=bug%2C+needs+triage&template=bug.md&title=) (it's fine to copy/paste it below, rather than starting another new issue). Without complete details and a way for us to reproduce the problem, there's not much we can do to help.

**Comment by ltomov** [comment]
It's ok, you can close this.

Basically I was wondering if this is some known limitation of the surface_view with a known workaround. I don't think it's a bug, I'm pretty much using the hello-world setup. 

From my testing it seems the videos are such that they just fall into the rare exception where texture_view needs to be used (fast moving animations). So I guess I'll stick with it.
