### ISSUE TITLE
is there any way to play only ads with this ima

### ISSUE THREAD

**Issue by DaveBoy** [google/ExoPlayer#8113]
we hava only the ads to play,there is no other video content.
if i set a null or wrong video link,it  will not report the complete event,but an error event.

is there any solution?

**Comment by ojw28** [comment]
I don't think the IMA SDK is designed for this purpose. You should probably take a look at the [Admob SDK](https://developers.google.com/admob/android/quick-start) instead.

**Comment by DaveBoy** [comment]
i use the IMA SDK because our app maybe run on FireTv，admob have trouble on these devices。
so i want to use the IMA SDK to play VAST ads like Interstitial

**Comment by ojw28** [comment]
If you don't have any other video content into which these ads are being inserted, then what are your ads interstitials _for_, exactly?

**Comment by DaveBoy** [comment]
maybe  there are some other videos,but in order to Compatible with the method to deal with the old Interstitial ad（some devices we use admob），we want to show the VAST like interstitial，in a DialogFragment above the content，not contact with the video

**Comment by ojw28** [comment]
If your use case is to insert interstitial ads into video content, you should probably stop using the Admob SDK and migrate fully to the IMA SDK and/or IMA extension, so you're using the right SDK in the way it was designed to be used.

What you're describing is attempting to use the IMA SDK to do what the IMA SDK is designed to do, but not in a way that it's designed to do it. This is not something we support.

**Comment by DaveBoy** [comment]
#3774
