### ISSUE TITLE
Widevine license renewal using azure media services

### ISSUE THREAD

**Issue by AnassHmida** [google/ExoPlayer#8116]
hello, 

I'm trying to renew my widevine offline license for playback, I'm not able to do so with azure media services because it provides a dynamic license server URL that is included in the manifest.

a bug report was opened for a variant of this issue #3393  and was fixed. ( when the player doesn't parse incoming data in the manifest and now that it is fixed , the parser reads directly from the manifest and parses the azure license URL without a problem.)   

my issue comes at hand when I'm trying to renew my license using a dynamic license URL because I can't include it in my widevine license template in the field renewal_server_url since it's not static, and azure media services does not provide a commun url for their license server.

what can i do to retreive the license url in order to ask for a renewal?

Version of ExoPlayer being used
2.12.0

HUAWEI P30 LITE

**Comment by ojw28** [comment]
If the URL is included in the manifest then I think you'll need to request and parse the manifest, and then retrieve the URL from it. You can load and parse the manifest with `DashUtil.loadManifest`. Once you have it, you can dig around inside the `DashManifest` to retrieve the license URL. I didn't test this, but it's probably retrievable via:
```
dashManifest.getPeriod(0).adaptationSets.get(0).representations.get(0).format.drmInitData.get(0).licenseServerUrl
```
If not, try attaching a debugger and exploring in the `DashManifest` object.

**Comment by AnassHmida** [comment]
Good evening @ojw28,
Thank you for your detailed response, i will get back to you after i test this. 
I do have one last question tho,
after renewing my license for offline playback , do i need to replace the generated keysetid response from offlinelicencehelper.renewlicense with the one that is linked to the download so i can playback my downloaded content with the new license or is there an other step to it?

**Comment by ojw28** [comment]
If you're using `OfflineLicenseHelper.renewLicense`, was your initial question about getting a `defaultLicenseUrl` to build a `HttpMediaDrmCallback`? I'm not sure, but it might be possible for you to set it to any dummy value for your media, if it's always specifying a URL internally. That would avoid you needing to look inside the DASH manifest. In future releases we will allow this parameter to be `null`.

> after renewing my license for offline playback , do i need to replace the generated keysetid response from offlinelicencehelper.renewlicense with the one that is linked to the download so i can playback my downloaded content with the new license or is there an other step to it?

I'm not entirely sure what you're asking here. Is the `keySetId` returned by `renewLicense` _different_ to the one when the license was originally obtained, or is it the same? If the `keySetId` has changed, you'll need to use the one returned by `renewLicense` for successful playback after renewal. We should probably look at an easy way to update the download database in this case.

**Comment by AnassHmida** [comment]
@ojw28 yes that's exactly what I meant, and by setting that value to `null` will that mean it will use a license URL if it has one and `null` if it doesn't?

as for the download part, that is what I meant precisely, I use the `newkeySetId `generated from the `OfflineLicenseHelper.renewLicense` function using my old `keySetId` like this : 

```
        keySetId = mediaItem.playbackProperties.drmConfiguration.getKeySetId();
        android.util.Log.d(TAG, "doInBackground: Old key : "+ Arrays.toString(keySetId));
        newkeySetId = offlineLicenseHelper.renewLicense(keySetId);
        android.util.Log.d(TAG, "doInBackground: new key : "+Arrays.toString(newkeySetId));
```

Then afterwards , i'm creating a new downloadRequest  using the same data from the old DownloadRequest and only replacing my old `keySetId ` with the new `newkeySetId` and adding that request to a new download and replacing that download with the one in the `downloads` list, here's the function that i'm using to do so : 

`updateDownloadwithKeySetId(mediaItem, newkeySetId);`

Here's how it works.

```
 private void  updateDownloadwithKeySetId(MediaItem mediaItem,byte[] KeysetId) {

//Adding a new download request using previous data from my stored download Request.
//Here i'm using my uri for the ID.

  DownloadRequest downloadRequest = downloadHelper.getDownloadRequest(Util.getUtf8Bytes(checkNotNull(mediaItem.mediaMetadata.title))).copyWithKeySetId(keySetId);

    DownloadRequest newDownloadRequest =
            new DownloadRequest.Builder(downloadRequest.id, downloadRequest.uri)
                    .setStreamKeys(downloadRequest.streamKeys)
                    .setCustomCacheKey(downloadRequest.customCacheKey)
//Changing the keysetId here
                    .setKeySetId(keySetId)
                    .setData(downloadRequest.data)
                    .setMimeType(downloadRequest.mimeType)
                    .build();


//creating a new download based on the stored download (Updating Download Request).

    Download download = downloads.get(checkNotNull(mediaItem.playbackProperties).uri);

    Download download1 = new Download(
            newDownloadRequest,
            download.state,
            download.startTimeMs,
            download.updateTimeMs,
            download.contentLength,
            download.stopReason,
            download.failureReason);

//Replacing the old download with the new modified one.

    downloads.put(mediaItem.playbackProperties.uri,download1);
    Download justDownloaded = downloads.get(checkNotNull(mediaItem.playbackProperties).uri);

    /*Checking */

    String justDown = new String(justDownloaded.request.keySetId);
    String oldDown = new String(download.request.keySetId);

    if(justDown.equals(oldDown)){
      android.util.Log.d(TAG, "onPostExecute: License renew error.");
    }else{
      android.util.Log.d(TAG, "onPostExecute: License has been renewed.");
    }

  }
```
Not sure if this is the correct approach to achieve license renewal.
this function is not tested because I'm not able to receive a new `keySetID` from the azure license URL ( for some reason )  , but I wrote it based on the logic of what will happen when my license is renewed.

**Comment by ojw28** [comment]
> We should probably look at an easy way to update the download database in this case.

Aha, it looks like you've figured out how to do this, just by adding the same download request again with an updated `keySetId`. Nice one :)! It looks like that should work fine, although we can optimize it slightly to not moving the download out of the `STATE_COMPLETED` state.

I think everything else you've written looks sensible/correct. Can I close this issue as answered?

**Comment by AnassHmida** [comment]
> > We should probably look at an easy way to update the download database in this case.
> 
> Aha, it looks like you've figured out how to do this, just by adding the same download request again with an updated `keySetId`. Nice one :)! It looks like that should work fine, although we can optimize it slightly to not moving the download out of the `STATE_COMPLETED` state.
> 
> I think everything else you've written looks sensible/correct. Can I close this issue as answered?


Yes, I believe you can, my problem is now with azure, since everything works as intended in here. 
Thank you for your guidance!
