### ISSUE TITLE
Can't retrieve closed captions info from the track in Exo v2.12.1. 

### ISSUE THREAD

**Issue by dmitriy-onix** [google/ExoPlayer#8120]
Can't retrieve closed captions info from the track in Exo v2.12.1. 

please check repo:
https://bitbucket.org/dmitriy_godun/exoccissuedemo/src/master/
branches:
test/exoV_2_11_8
test/exoV_2_12_1

video link:
https://drive.google.com/file/d/1c0ZvYxEaFTEG_mhCouJ_kuDKRwtRtvtM/view?usp=sharing 

For the same video file:
V2.11.8
mappedTrackInfo -> rendererFormatSupports ->array for text renderer is not empty
![image](https://user-images.githubusercontent.com/38754554/97280123-8699c800-1844-11eb-8e6c-fc4c65604e0c.png)

V2.12.1 
mappedTrackInfo -> rendererFormatSupports ->array for text renderer is empty
![image](https://user-images.githubusercontent.com/38754554/97280140-8dc0d600-1844-11eb-82a0-514569868c60.png)

Version of ExoPlayer 
2.12.0, 2.12.1

.ts video file - possibly a problem with the extractor.
File media info:
[mediainfo.txt](https://github.com/google/ExoPlayer/files/5444254/mediainfo.txt)

Min API 26, tested on several devices (Galaxy Tab A(2016), Mi A2 light) but it looks like it can be reproduced on all.

There is no information in the logs. But here are the logs: 
2.12.1
[logs_2.12.1.txt](https://github.com/google/ExoPlayer/files/5444229/logs_2.12.1.txt)
2.11.8
[logs_2.11.8.txt](https://github.com/google/ExoPlayer/files/5444274/logs_2.11.8.txt)

**Comment by icbaker** [comment]
This is due to https://github.com/google/ExoPlayer/commit/6d0696a3c84f05889e7a9a54025f9ec8cf81c733.

The release notes of that change let you know how to resolve it in your app:
>Stop auto-generating a CEA-608 track when playing standalone Transport Stream files. Users that require Closed Captions tracks being auto-generated should manually inject a customized `DefaultTsPayloadReaderFactory` into their `TsExtractor`.
