### ISSUE TITLE
mediacodec error

### ISSUE THREAD

**Issue by kuailedeadai** [google/ExoPlayer#8121]
Hello, I am playing a video with a video encoding format of h265. The system supports hardware decoders of omx.google and omx.sec. After the decoder is initialized, the normal input data feedInputBuffer() is decoded, but the codec.dequeueOutputBuffer() always return -1, and the decoder has no Exception, the Android kernel reports an error: E/ACodec: [OMX.google.hevc.decoder] storeMetaDataInBuffers failed w/ err -1010, E/OMXNodeInstance: setConfig(1:google.hevc.decoder, ConfigPriority(0x6f800002)) ERROR: Undefined(0x80001001) I think it is a model adaptation problem, but how to find the decoder can not support decoding data, we can turn to soft solution or other, look forward to your answer, thank you

**Comment by ojw28** [comment]
Please properly fill in the issue template, including all of the requested information, if you wish us to investigate this further. Thanks!

**Comment by kuailedeadai** [comment]
![image](https://user-images.githubusercontent.com/10614848/97523425-3a35c000-19dd-11eb-9828-78947aa9386b.png)

The picture above is the video encoding information, the model of the mobile phone played is: galaxy j7 sm-j700f

**Comment by ojw28** [comment]
Please properly fill in the issue template, including all of the requested information, if you wish us to investigate this further. The issue template can be found [here](https://github.com/google/ExoPlayer/issues/new?assignees=&labels=bug%2C+needs+triage&template=bug.md&title=). Please copy/paste it into this issue and complete all of the requested sections. Thanks!
