### ISSUE TITLE
Download class missing equals function

### ISSUE THREAD

**Issue by yoobi** [google/ExoPlayer#8122]
### [REQUIRED] Issue description
I was using `Download` in my `Recyclerview` and `ListAdapter` and in my `DiffUtil.ItemCallback<Download>` I got a warning with the following message: `Suspicious equality check: equals() is not implemented in Download` 
```kotlin
override fun areContentsTheSame(oldItem: Download, newItem: Download): Boolean {
    return oldItem == newItem
}
```

In the mean time I've changed to: 
```kotlin
return (oldItem.request == newItem.request
                    && oldItem.state == newItem.state
                    && oldItem.startTimeMs == newItem.startTimeMs
                    && oldItem.updateTimeMs == newItem.updateTimeMs
                    && oldItem.contentLength == newItem.contentLength
                    && oldItem.stopReason == newItem.stopReason
                    && oldItem.failureReason == newItem.failureReason
                    && oldItem.bytesDownloaded == newItem.bytesDownloaded
                    && oldItem.percentDownloaded == newItem.percentDownloaded)
```

**Comment by ojw28** [comment]
The `Download` includes things like the current state (i.e., whether the download is paused, completed, failed etc). If you're trying to test whether two `Download` instances correspond to the same piece of content, I don't think you want to be including that kind of state in your equality check, and so I don't think checking for equality between the two `Download` instances is the correct approach. You should probably be comparing using `Download.request`, or possibly even `Download.request.id` or `Download.request.uri`.

**Comment by yoobi** [comment]
Maybe I'm not using the correct approach indeed, I'm trying to display the current progression of the download in my activity, how would you recommend me to do so ?

I currently have a recyclerview with all downloads, that's why I'm using DiffUtil, my code below:
```
val downloads: HashMap<Uri, Download> = HashMap()
try {
    downloadIndex.getDownloads().use { loadedDownloads ->
        while (loadedDownloads.moveToNext()) {
            val download = loadedDownloads.download
            downloads[download.request.uri] = download
        }
    }
} catch (e: IOException) {
    Log.w(TAG, "Failed to query downloads", e)
}
```
then I'm using a `Flow` to get the progress of each download every second
```
suspend fun getDownloadProgressFlow() = callbackFlow {
    while(downloads.values.any { !it.isTerminalState }) {
        offer(downloads)
        withContext(Dispatchers.IO) { delay(1000) }
    }
    if(downloads.values.none { !it.isTerminalState }){
        this.cancel()
    }
}
```
and submit the new list.

**Comment by ojw28** [comment]
This is getting into the realm of providing support specifically for your own application code, which is beyond the scope of this issue tracker. I think my response above explains how to compare whether two `Download` instances correspond to the same content, which was the original query asked here.
