### ISSUE TITLE
ExoPlayer cannot play normally, when the first ExoPlayer(uses the same URL) is buffering

### ISSUE THREAD

**Issue by friskyliu** [google/ExoPlayer#8123]
There ara two Activity, each with a ExoPlayer,

Both ExoPlayer use the same URL,

When the first ExoPlayer is buffering, start the second Activity, and the ExoPlayer player cannot play normally.

If it's not a bug, is there a good way to avoid it?

___Possible reasons for using cache:___

<pre>
       private static class CacheDataSourceFactory implements DataSource.Factory {
        private final Context context;
        private final DataSource.Factory factory;
        private final long maxFileSize, maxCacheSize;
        private static SimpleCache sSimpleCache = null;
        private static final byte[] lock = new byte[0];
        private final File cacheDir;
        CacheDataSourceFactory(Context context, DataSource.Factory factory, File cacheDir) {
            this(context, factory, cacheDir, 80 * 1024 * 1024, 5 * 1024 * 1024);
        }
        CacheDataSourceFactory(Context context, DataSource.Factory factory, File cacheDir, long maxCacheSize, long maxFileSize) {
            super();
            this.context = context;
            this.maxCacheSize = maxCacheSize;
            this.maxFileSize = maxFileSize;
            this.factory = factory;
            this.cacheDir = cacheDir;
        }
        @Override
        public DataSource createDataSource() {
            if (sSimpleCache == null) {
                synchronized (lock) {
                    if (sSimpleCache == null) {
                        LeastRecentlyUsedCacheEvictor evictor = new LeastRecentlyUsedCacheEvictor(maxCacheSize);
                        sSimpleCache = new SimpleCache(cacheDir, evictor, new ExoDatabaseProvider(context.getApplicationContext()));
                    }
                }
            }
            return new CacheDataSource(sSimpleCache, factory.createDataSource(),
                    new FileDataSource(), new CacheDataSink(sSimpleCache, maxFileSize),
                    CacheDataSource.FLAG_BLOCK_ON_CACHE | CacheDataSource.FLAG_IGNORE_CACHE_ON_ERROR, null);
        }
    }

</pre>

Android Version: 9.0

ExoPlayer: 2.12.0

Git: https://github.com/friskyliu/exoplayerdemo.git

steps:
1. Launch app
2. When the player is playing and buffering
3. Click the button "New Video Player"

**Comment by friskyliu** [comment]
I found it was blocked in the CacheDataSource#openNextSource.

CacheDataSource.java 
<pre>

private void openNextSource(boolean checkCache) throws IOException {
    CacheSpan nextSpan;
    if (currentRequestIgnoresCache) {
      nextSpan = null;
    } else if (blockOnCache) {
      try {
        nextSpan = cache.startReadWrite(key, readPosition);     //Blocked here!!!!!!!!
      } catch (InterruptedException e) {
        Thread.currentThread().interrupt();
        throw new InterruptedIOException();
      }
    } else {
      nextSpan = cache.startReadWriteNonBlocking(key, readPosition);
    }

   ....
}

<pre>

**Comment by ojw28** [comment]
`SimpleCache` does indeed have some limitations on concurrent access.  Note that your code above is explicitly requesting blocking in this case, by using `FLAG_BLOCK_ON_CACHE`. If you don't want that behavior, don't use this flag :).
