### ISSUE TITLE
scrubber_drawable not showing properly

### ISSUE THREAD

**Issue by mohsin16432** [google/ExoPlayer#8124]
I want to show custom Thumb for DefaultTimeBar and to do so i have used the attribute `scrubber_drawable` and it is showing but copped image to the height of DefaultTimeBar. Kindly assist.
<img width="379" alt="Screenshot 2020-10-27 at 8 27 36 PM" src="https://user-images.githubusercontent.com/72552138/97324858-25014a00-1894-11eb-8eb6-7ea248182601.png">

```
        <com.google.android.exoplayer2.ui.DefaultTimeBar
        android:id="@+id/exo_progress"
        android:layout_width="match_parent"
        android:layout_height="@dimen/_5sdp"
        android:layout_marginTop="@dimen/_30sdp"
        app:scrubber_drawable="@drawable/ic_add_image"
        app:scrubber_enabled_size="@dimen/_10sdp"
        app:played_color="@color/lightGrey2"
        app:unplayed_color="@color/grey_25"
        app:buffered_color="@color/grey_transparent"
        app:scrubber_color="@color/grey_10"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent" />
```

**Comment by ojw28** [comment]
This appears to be an issue with your customization, and is not something we can help with directly. If your image is being cropped by the height of the time bar, you'll possibly need to find a way to make it taller.

I'll leave this issue open for a few weeks in case anyone else is able to help. You may find StackOverflow is a better place to ask this question.

**Comment by mohsin16432** [comment]
Thanks @ojw28 
The issue is now resolved.
Actually the attribute `app:bar_height="@dimen/_1sdp"` is used to show the height of the progress/timebar and i thought `android:layout_height="@dimen/_5sdp"` is used to show the height which is cropping the `Scrubber` drawable. Making `android:layout_height="wrap_content"` fixed my problem.
