### ISSUE TITLE
Widevine license and Playback

### ISSUE THREAD

**Issue by randeeppr** [google/ExoPlayer#813]
Hi,
We are playing widevine modular drm encrypted dash videos using exoplayer. But what I have observed is every time we play the video, it sends the license request to the widevine proxy server. The license is giving for 72 hours or so. So it should request the license only after the current license is expired right? 
How we can force exoplayer to check the validity of the current license and play the video?
Regards,
Randeep

**Comment by ojw28** [comment]
As I understand it, streaming licenses are only valid/usable for as long as the MediaDrm session into which they've been loaded remains open. ExoPlayer's StreamingDrmSessionManager keeps a MediaDrm session for the duration of the playback only. Starting a new playback will open a new session, and so it will be necessary to load the licenses again.

We have no plans to change this behavior. If you were particularly motivated to do something different, you'd need to implement your own DrmSessionManager that holds a MediaDrm session open for a longer period of time. Note however that holding multiple sessions open is generally a bad idea, and will likely cause session instantiation to fail if you try to have too many sessions open at once.
