### ISSUE TITLE
Hide Quality display from Video

### ISSUE THREAD

**Issue by shwetachauhan-simform** [google/ExoPlayer#8135]
![video_player](https://user-images.githubusercontent.com/63042002/97574001-96660780-1a10-11eb-86f8-7a6439b577ea.png)

I want to hide video quality from PlayerView. I have attached image and I want to hide that "FULL HD" button. 

Is it possible???

**Comment by ojw28** [comment]
That view has nothing to do with ExoPlayer. I suggest you contact the author of whatever app or library you're using.

**Comment by shwetachauhan-simform** [comment]
yea, I thought same but when I use different trackselector I mean quality then it's showing me like 480p, 240p. 

So, I am confirming here it's related to ExoPlayer??

**Comment by ojw28** [comment]
Whether something is displayed in a UI component or not, is a property of the UI component. That UI component doesn't look like anything that we provide in the ExoPlayer library, so this is not an ExoPlayer issue.

**Comment by shwetachauhan-simform** [comment]
okay, thanks a lot. Got it.
