### ISSUE TITLE
Detecting live and VoD content (2020)

### ISSUE THREAD

**Issue by CanerGures** [google/ExoPlayer#8138]
I am trying to detect whether the stream is live or not. I reviewed many questions in here and in stackoverflow, but they are not working, at least anymore.
I checked [this](https://github.com/google/ExoPlayer/issues/2668) , [this](https://github.com/google/ExoPlayer/issues/2623) and [this](https://stackoverflow.com/questions/38037794/exoplayer-how-to-know-if-hls-video-is-live-or-not)

What is I am trying to do, I want to set player time to minus value for live streams. As you know nowadays everyone does this. For example live stream has 1 hour cache backwards, I want to set player timer left end side with minus value like "-1.00.00"

I tried to get _player.duration_ but it gives minus some value like 12 13 digits. Also _C.TIME_UNSET_ gives the same value for both live and VoD. Is there and updated solution to this ?

application repo [here](https://github.com/CanerGures/ExoPlayer-Application)

**Comment by ojw28** [comment]
Have you tried using `Player.isCurrentWindowLive` and/or `Player.isCurrentWindowDynamic`? If neither of those are correctly detecting what you want, please could you provide direct links to some live content that is not being detected as such? Thanks.

**Comment by CanerGures** [comment]
Yes, I tried every combination of these. My links are not live anymore now but I found a live link and the player didn't detect that either. I will edit this answer when I got new live links from my company. Thanks.

**http://livesim.dashif.org/livesim/segtimeline_1/testpic_2s/Manifest.mpd**

**Comment by ojw28** [comment]
I tried adding the sample linked above into the demo app, and I also added this to `PlayerActivity.PlayerEventListener`:
```
@Override
public void onTimelineChanged(Timeline timeline, @Player.TimelineChangeReason int reason) {
  Log.e("PlayerActivity",
      "dynamic=" + player.isCurrentWindowDynamic()
      + "\tlive=" + player.isCurrentWindowLive());
}
```
The corresponding logging when playing the sample linked above is:
```
11-01 19:45:25.408 27376 27376 E PlayerActivity: dynamic=true	live=true
```
So it seems the player is detecting this correctly.

**Comment by CanerGures** [comment]
When I wrote isCurrentWindowLive on the initializer it gives false. But I wrote in the listener like yours. It gives the correct response. What is the difference between writing in the listener and just in the initializer?

`        if (player!!.isCurrentWindowDynamic && player!!.isCurrentWindowLive) {
            Toast.makeText(this, "video is Live", Toast.LENGTH_LONG).show()
        }`

**Comment by ojw28** [comment]
If the player hasn't loaded any of the content yet, which is probably the case where you're trying to make the call, then it's not going to have any way of determining whether the content is live.  `onTimelineChanged` is called when the player detected a change in the content structure (including whether the content is live or not), and so is the right place to check.

**Comment by CanerGures** [comment]
Outside of this topic, Can I use your help on another question?

When live videos are playing I want to set the slider on the right end side and on the right end side I want to set the time of the video backward like minus value. Can you check the picture? You will understand what I meant. 

[picture](https://linkpicture.com/q/Ads%C4%B1z_81.png)
