### ISSUE TITLE
ExoPlayer show first frame during loading of video

### ISSUE THREAD

**Issue by JimClermonts** [google/ExoPlayer#8139]
### Loading frame shown during loading
I'm having an API serving the video URI and a (preloaded!) first frame URI. I don't think it is possible right now to show the loading frame until the video is ready to play. I've tried a simple overlay view in android, but I'm running into issues with RecyclerView. It seems like a common use case so maybe I'm missing something?

### Proposed solution
This is my code and I would suggest to add the imageUri to the initializeExoplayer:
```
@Singleton
class MediaPlayer @Inject constructor(private val context: Context) {

    companion object {
        var exoPlayer: SimpleExoPlayer? = null
        var pauseItem = false
    }

    fun initializeExoplayer(uri: Uri): SimpleExoPlayer {
        if (exoPlayer != null) {
            resetPlayer()
        }

        val trackSelector = DefaultTrackSelector()

        trackSelector.setParameters(
            DefaultTrackSelector.ParametersBuilder()
                .setForceLowestBitrate(true)
                .setMaxAudioBitrate(128_000)
        )

        exoPlayer = ExoPlayerFactory.newSimpleInstance(context, trackSelector)

        val mediaSource = createMediaSource(uri)
        val loopingSource = LoopingMediaSource(mediaSource)

        exoPlayer?.prepare(loopingSource)
        exoPlayer?.volume = 1f

        return exoPlayer!!
    }

    fun resetPlayer() {
        exoPlayer?.playWhenReady = false
        exoPlayer?.stop()
        exoPlayer?.release()
        exoPlayer = null
    }

    private fun createMediaSource(uri: Uri): MediaSource {
        val userAgent = Util.getUserAgent(context, "ExoPlayerIntro")
        val dataSourceFactory = DefaultDataSourceFactory(context, userAgent)

        val mediaSource =
            ProgressiveMediaSource.Factory(dataSourceFactory, DefaultExtractorsFactory())
                .createMediaSource(uri)

        return Objects.requireNonNull(mediaSource, "MediaSource cannot be null")
    }
}
```

### Alternatives considered
I tried overlaying a View in RecyclerView, but it's not working. it sometimes stays black until the video starts playing, not always. But I wait long enough for the next 5 video's to load the frame. When printing out the imageUri, it shows that the imageUri is prefetched correctly, ready and on the correct thread. Yet, it still stays black (but not always..?) until the video starts playing.

 ```
       val listener = object : EventListener {
            override fun onPlayerStateChanged(playWhenReady: Boolean, playbackState: Int) {
                super.onPlayerStateChanged(playWhenReady, playbackState)

                if (playbackState == Player.STATE_READY) {
                    if (playWhenReady) {
                        binding.layout.foreground = null
                        binding.loadingFrame.visibility = View.INVISIBLE

                    } else if (MediaPlayer.pauseItem.not()) {
                        /*
                         * This is so that the loading frame shows
                         * when swiping up to the next video
                         */
                        binding.loadingFrame.visibility = View.VISIBLE
                    }
                    else {
                        onVideoPlayed.cancel()
                    }
                }
            }

```

**Comment by ojw28** [comment]
Assuming the first frame URIs you refer to fetch regular image files, loading that image into a view and placing it on top of the `Surface` to which the video will be rendered should work fine, and is a fairly widely used technique. I would therefore suspect that there's just something a little wrong with your implementation.

**Comment by rahulsainani** [comment]
@JimClermonts Maybe this helps you, this is what i was using in onBind of the recyclerview:

```
player.addListener(
                    object : Player.EventListener {

                        override fun onPlaybackStateChanged(state: Int) {
                            super.onPlaybackStateChanged(state)
                            when (state) {
                                Player.STATE_IDLE -> {
                                }
                                Player.STATE_BUFFERING -> imageView.toVisible()
                                Player.STATE_READY -> imageView.toGone()
                                Player.STATE_ENDED -> {
                                }
                            }
                        }
                    }
                )
```

@ojw28 The problem with this we faced is that sometimes the player doesn't fire the event "Ready" and plays the video for a while while the state is still "Buffering" So by this logic, the image is visible while the player plays in some cases. It specifically happens if we scroll 25+ items. Maybe that's why an API/enhacement for this would be valid. Let me know what you think?

**Comment by ojw28** [comment]
> The problem with this we faced is that sometimes the player doesn't fire the event "Ready" and plays the video for a while while the state is still "Buffering"

I think this is extremely unlikely. It would be a fairly fundamental issue with ExoPlayer state reporting, which no-one else has reported. It seems much more likely that your listener is not correctly registered, or that you have some other issue in your application code.

**Comment by rahulsainani** [comment]
@ojw28 Thanks for the quick reply. I see, in order to not change the topic of this issue, I will ask about the best practices for using exoplayer in recyclerview as a separate question.
