### ISSUE TITLE
Support Role listed after Representation in DashManifestParser

### ISSUE THREAD

**Issue by bafolts** [google/ExoPlayer#8141]
Before filing a feature request:
-----------------------
- Search existing open issues, specifically with the label ‘enhancement’:
  https://github.com/google/ExoPlayer/labels/enhancement
- Search existing pull requests: https://github.com/google/ExoPlayer/pulls

When filing a feature request:
-----------------------
Fill out the sections below, leaving the headers but replacing the content. If
you're unable to provide certain information, please explain why in the relevant
section. We may close issues if they do not include sufficient information.

### [REQUIRED] Use case description
I have been provided dash manifests which have the `<Role` element listed after the `<Representation` element within an `<AdaptationSet`. The `roleFlags` value is always `0`. This seems to happen because of how the parser is written.

https://github.com/google/ExoPlayer/blob/release-v2/library/dash/src/main/java/com/google/android/exoplayer2/source/dash/manifest/DashManifestParser.java#L327

When the call to `parseRepresentation` happens the role hasn't been parsed yet. When the role is parsed the representation is not updated.

### Proposed solution
Parse role elements first before parsing representation elements.

### Alternatives considered
Extending `DashManifestMaker` in some way where these manifests parse `roleFlags` or asking my manifest provider to update the manifest to list `<Role` before `<Representation`.

**Comment by ojw28** [comment]
Putting the `Role` element after the `Representation` element is a violation of the DASH spec.

**Comment by bafolts** [comment]
Closing this makes sense if it violates the DASH spec. The shaka player supports the `Role` element anywhere whether by design or by accident. 

https://github.com/google/shaka-player/blob/master/lib/dash/dash_parser.js#L727

I believe my manifest provider uses shaka to verify their changes as it is more accessible.
