### ISSUE TITLE
No sound in MKV file.

### ISSUE THREAD

**Issue by master255** [google/ExoPlayer#8142]
No sound in MKV file.
It consists of x265 video and PCM 32bit 48KHz stereo audio track.
Both codecs are separately supported by ExoPlayer, but when they are in the same mkv container there is no sound.

Version ExoPlayer: 2.12.1
[My file.](https://mega.nz/file/ZgVmBRpD#7TmaSEyxqCRrJnaUWKMY7U0HCqYyNtM1NbIwj4B7HJg)

Other players play this file with sound.

**Comment by ojw28** [comment]
We need to add a block to `MatroskaExtractor` to handle floating point PCM. This is pretty straightforward; we'll get it added. Thanks!
