### ISSUE TITLE
Support for Android 11

### ISSUE THREAD

**Issue by Ethan1983** [google/ExoPlayer#8145]
### [REQUIRED] Searched documentation and issues
Couldn't find anything regarding this in https://exoplayer.dev/

### [REQUIRED] Question

API getActiveNetworkInfo of ConnectivityManager and getSubType of NetworkInfo is deprecated from API 29 (Android 10). This is being used to find the cellular network sub type( getMobileNetworkType of com.google.android.exoplayer2.util.Util) used in DefaultBandwidthMeter (com.google.android.exoplayer2.upstream)

https://developer.android.com/reference/android/net/ConnectivityManager#getActiveNetworkInfo()
https://developer.android.com/reference/android/net/NetworkInfo#getSubtype()

The alternate API is getDataNetworkType of TelephonyManager. However, this requires a runtime permission (Manifest.permission.READ_PHONE_STATE). Is there going to be a workaround or is this permission going to be requested by ExoPlayer?

https://developer.android.com/reference/android/telephony/TelephonyManager#getDataNetworkType()

**Comment by lcf87** [comment]
@tonihei Could you take a closer look at it?

**Comment by tonihei** [comment]
We are not planning to request permissions as READ_PHONE_STATE at any point. 

The "workaround" for the case you mention is just to keep using the deprecated API as long as it is supported. This is easier for us as long as there is no functional difference because we need to have a code path for the deprecated API anyway to support older devices.

**Comment by Ethan1983** [comment]
Thanks. Only catch is if and when deprecated API is removed in a future SDK and ExoPlayer would run into it as compileSdkVersion is updated. Anyways, for now, it looks like 28 is targetSdkVersion and 29 is compileSdkVersion.

**Comment by tonihei** [comment]
Yes, this sounds like a long way off from now though :) 

I'll close the issue because the question was answered I think.
