### ISSUE TITLE
DASH + Widevine + FMP4 TTML UnexpectedLoaderException

### ISSUE THREAD

**Issue by DStanojevic** [google/ExoPlayer#8148]
### Issue description
When trying to play Widevine protected DASH manifest with the fragmented MP4 TTML closed captions, player crashes (see attachment) with "Unexpected NullPointerException". When try to play the same content which is transcoded without protection, than works fine.
Also when CC are not turned on with the Widevine protected content there is no issues.

### Reproduction steps
Turn on the CC when playinh manifest below:
https://d1h439zc5v8bgw.cloudfront.net/assets/510130/dash/befb5f75-7ffc-43d9-9622-8fd0d97ed8e3/510130.mpd
(if it is necessary we can make effort provide environment for obtaining the licence)

### Link to test content
Manifest than causes player to crash (Widevine):
https://d1h439zc5v8bgw.cloudfront.net/assets/510130/dash/befb5f75-7ffc-43d9-9622-8fd0d97ed8e3/510130.mpd
Manifest that works fine (unprotected)
https://d1h439zc5v8bgw.cloudfront.net/assets/510130/dash/379160d8-15a1-11eb-845f-acde48001122/510130.mpd

### Version of ExoPlayer being used
Player version: 2.12.0

### Device(s) and version(s) of Android being used
Android version: 10

[ssai_subtitle_error.txt](https://github.com/google/ExoPlayer/files/5475546/ssai_subtitle_error.txt)

**Comment by lcf87** [comment]
@kim-vde Could you take a look? The NPE happened in FMp4 extractor, when extracting CC files.
You can reproduce by using the unprotected link and choose the CC track.
The links to the CC files:

https://d1h439zc5v8bgw.cloudfront.net/assets/510130/dash/befb5f75-7ffc-43d9-9622-8fd0d97ed8e3/510130_ccinit.mp4
https://d1h439zc5v8bgw.cloudfront.net/assets/510130/dash/befb5f75-7ffc-43d9-9622-8fd0d97ed8e3/510130_cc_000000006.mp4

**Comment by kim-vde** [comment]
ExoPlayer doesn't support encrypted subtitles. The sinf box in the text track is not parsed and, as a result, the sample description encryption box is null, and an NPE is thrown when parsing the saiz box.

Regarding the sample you provided, the fact that the text track is encrypted or not seems inconsistent: the DASH manifest indicates that it isn't, while the MP4 file indicates that it is. Are the subtitles protected?

I have also noticed that the text encryption information in the Widevine content doesn’t seem right: there is no enct atom and the scheme type is unknown.
