### ISSUE TITLE
How to get the buffering percent updates withExoPlayer?

### ISSUE THREAD

**Issue by cacciato** [google/ExoPlayer#815]
With Mediaplayer class, there is a callback method:

```java 
public void onBufferingUpdate(MediaPlayer mp, int percent);
```
http://developer.android.com/reference/android/media/MediaPlayer.OnBufferingUpdateListener.html#onBufferingUpdate(android.media.MediaPlayer,int)

Is there an equivalent interface with ExoPlayer ?
Or at least a method like : 
```java 
public void onBufferingEnd(ExoPlayer mp);
```

**Comment by ojw28** [comment]
```ExoPlayer.getBufferedPosition``` and ```ExoPlayer.getBufferedPercentage``` gives you the buffer position and percentage respectively. If you want periodic updates, call them periodically.

**Comment by cacciato** [comment]
Thank you.
