### ISSUE TITLE
How to clear the last frame when video switching

### ISSUE THREAD

**Issue by VeiZhang** [google/ExoPlayer#8150]
### [REQUIRED] Question
When playing a video, then I switch to another video link, the surface view showed a picture which is a frame of last video. The question is I want to clear the last frame and make it black screen when switching video.

### A full bug report captured from the device
I try to clear surface view, but strange something happend, the video will become stuck. It seems surface view locked.

**Comment by lcf87** [comment]
A quick solution would be to create a custom view on top to block the last frame.

Please see if #8139 would help!

**Comment by VeiZhang** [comment]
@lcf87 Yes, I also try it, but when switching small to big surface view, the picture can be saw in a short time, so I think it is not a perfect idea. If there is no other method, I will keep to add a view above surface view.

Thank you for the reply.
