### ISSUE TITLE
Current position greater than duration

### ISSUE THREAD

**Issue by D00mch** [google/ExoPlayer#8156]
### Issue description
Current position value greater than duration value at the end of the stream. 

### Reproduction steps
1. open ExoPlayer demo app, 
2. choose video YouTube DASH Google Glass H264 (MP4)
3. wait until the end, you will see current position == 02:17, and duration == 02:16

### Link to test content
```json
{
    "name": "YouTube DASH",
    "samples": [
      {
        "name": "Google Glass H264 (MP4)",
        "uri": "https://www.youtube.com/api/manifest/dash/id/bf5bb2419360daf1/source/youtube?as=fmp4_audio_clear,fmp4_sd_hd_clear&sparams=ip,ipbits,expire,source,id,as&ip=0.0.0.0&ipbits=0&expire=19000000000&signature=51AF5F39AB0CEC3E5497CD9C900EBFEAECCCB5C7.8506521BFC350652163895D4C26DEE124209AA9E&key=ik0",
        "extension": "mpd"
      }
    ]
}
```

### A full bug report captured from the device
[bugreport](https://drive.google.com/file/d/1CgUQOOovbrfPgbRs0FuW4_O3POv9h5Cr/view?usp=sharing)

### Version of ExoPlayer being used
2.12.1

### Device(s) and version(s) of Android being used
Custom device, android 9.
(can't reproduce it on anything else)

**Comment by lcf87** [comment]
Cannot reproduce on my end (emulator/Samsung A51). If you cannot reproduce on your other devices, maybe it's not worth spending time on it.

**Comment by D00mch** [comment]
![customAndroid9](https://user-images.githubusercontent.com/14236531/98036385-00c0e280-1e2b-11eb-81da-3787a874fb71.gif)

It seems that the duration is correct. The problem is that videos keep going after the end.

**Comment by D00mch** [comment]
I have just reproduced this bug with Android Emulator 10.1_WXGA_Tablet_API_28
![image](https://user-images.githubusercontent.com/14236531/98039660-1684d680-1e30-11eb-9213-ed34dd68846a.png)

[bugreport](https://drive.google.com/file/d/1nQ-j9YYeJdovA3PT8-Zv9pWrJIXjZGdj/view?usp=sharing)

I tried to debug ExoPlayerImplInternal with android studio debugger and I found out that sometimes my custom devices stops with the correct position at the end. So I assume there may be a race condition.

**Comment by lcf87** [comment]
Sorry I still cannot reproduce, using exactly the same emulator (wxga tablet, API28).

Maybe there are some `ExoplayerImplInternal` specific changes on your side?

![Screen Shot 2020-11-03 at 4 58 58 PM](https://user-images.githubusercontent.com/6046605/98045231-28e21e80-1df6-11eb-9b11-fcbafd3a5538.png)

**Comment by D00mch** [comment]
It seems I can't reproduce it without the debugger. 

May be something like this occurred when I reproduced it:
I put a debugger-poin on ExoPlayerImplInternal#doSomeWork line 900:
`boolean isReadingAhead = playingPeriodHolder.sampleStreams[i] != renderer.getStream();`
and set condition: `renderersEnded == true`, 
and when debugger was triggered at the end of the stream, it ended up with the current position >= than the duration.
I guess the reason of this was that I've delayed below-900-line-code invocation.
———

I tried to find out what is different on my device (checking MediaCodecRenderer#processEndOfStream and ExoPlayerImplInternal#stopRenderers) when the stream position goes after the duration, but cant find any differences (compared to other devices and the emulator). 
May be you will be able to give me some hint on where to look for?

**Comment by lcf87** [comment]
My gut feeling is the break point paused the player, but not the system clock. So the playback position changed location.

I don't understand why this is a concern, I would probably take it as "expected behaviour".

**Comment by lcf87** [comment]
Again I don't think it should concern you, but here's the position that you may want to look into.

https://github.com/google/ExoPlayer/blob/59b34ede6165d029d86a677fea73a5dd0dd55c74/library/core/src/main/java/com/google/android/exoplayer2/audio/AudioTrackPositionTracker.java#L267
