### ISSUE TITLE
unsuported drm_license_uri option

### ISSUE THREAD

**Issue by ramzeska** [google/ExoPlayer#8157]
Not working with "drm_license_uri" option as supposed (according to documentations): 

`adb shell am start -a com.google.android.exoplayer.demo.action.VIEW -d https://storage.googleapis.com/wvmedia/cenc/hevc/tears/tears_uhd.mpd --es drm_scheme widevine --es drm_license_uri 'https://proxy.uat.widevine.com/proxy?provider=widevine_test'
`

But working with "drm_license_url option":

`ubuntu@ubuntu-VirtualBox:~$ adb shell am start -a com.google.android.exoplayer.demo.action.VIEW -d https://storage.googleapis.com/wvmedia/cenc/hevc/tears/tears_uhd.mpd --es drm_scheme widevine --es drm_license_url 'https://proxy.uat.widevine.com/proxy?provider=widevine_test'
`

Also not parsing JSON file correctly via email/browser etc. 

Seems it is very simple mistake here: 
https://github.com/google/ExoPlayer/blob/59b34ede6165d029d86a677fea73a5dd0dd55c74/demos/main/src/main/java/com/google/android/exoplayer2/demo/SampleChooserActivity.java#L375

**Comment by lcf87** [comment]
I don't understand what you mean. Please fill out the issue template form so that we could help, thanks!

**Comment by ramzeska** [comment]
According to manuals from here: https://exoplayer.dev/demo-application.html

Option should be called "**drm_license_uri**", but that option doesn't get recognised via command line or via json. 
If opening json it throw error in logcat about "unsupported option". 

But if I use "**drm_license_url**" with L letter on end, everything working fine.

**Comment by lcf87** [comment]
I tried it and it worked fine on my end.

The command I tried (one of the default DRM content in the demo app):
```
am start -a com.google.android.exoplayer.demo.action.VIEW \
    -d https://storage.googleapis.com/wvmedia/cenc/h264/tears/tears.mpd \
    --es drm_scheme widevine \
    --es drm_license_uri https://proxy.uat.widevine.com/proxy?video_id=GTS_SW_SECURE_CRYPTO&provider=widevine_test
```

Looking at the code you pasted, the case `drm_license_uri` should just fall through to `drm_license_url`.

**Comment by ojw28** [comment]
@ramzeska - I suspect you're using an older release of ExoPlayer. The documentation is always in sync with the latest release.

**Comment by ramzeska** [comment]
Yep, but strange I used 2.11 version. 

Just recompiled with latest version from repo, like 2.12 and `drm_license_uri` now started to work, and `drm_license_url` stopped. 

Anyway can close task. As seems for laters source everything works according to docs.
