### ISSUE TITLE
Which callback is getting triggered when Ads are requested ?

### ISSUE THREAD

**Issue by nishantkp** [google/ExoPlayer#8158]
### Searched documentation and issues
N/A

### Question

Is there a way from where I can get `com.google.ads.interactivemedia.v3.api.AdsLoader` instance? 

I am using ImaAdsLoader.getAdsLoader() but this could be null if the ads are not requested.

I am looking for a callback which tells me ads are requested so that I can query `com.google.ads.interactivemedia.v3.api.AdsLoader` instance to attach `AdsLoader.AdsLoadedListener`.

Currently, I am using something like _(just introducing bit of a delay hoping ads will get requested)_,

```java
 new Handler().postDelayed(() -> {
            if (adsLoader.getAdsLoader() != null) {
                adsLoader.getAdsLoader().addAdsLoadedListener(this);
                adsLoader.getAdsLoader().addAdErrorListener(adErrorEvent -> {
                    // do something
                });
                log.d(TAG, "Ads analytics listeners are attached.");
            } else {
                log.e(TAG, "Ads Loader is Null; Ads are not requested yet.");
            }
        }, 200 /* To fix the issue where AdsLoader is null until ads are requested */);
```

ExoPlayer version: 2.12.1

### A full bug report captured from the device
N/A

### Link to test content
N/A

**Comment by andrewlewis** [comment]
If you attach a player event listener and listen for `onTimelineChanged`, you can check the ad group count for the period becoming non-zero. Something like this:

```
Handler handler = new Handler(Looper.getMainLooper());
player.addListener(
    new Player.EventListener() {
      private boolean seenAdsLoader;

      @Override
      public void onTimelineChanged(Timeline timeline, int reason) {
        if (!seenAdsLoader
            && reason == Player.TIMELINE_CHANGE_REASON_SOURCE_UPDATE
            && timeline.getPeriod(/* periodIndex= */ 0, new Timeline.Period()).getAdGroupCount()
                > 0) {
          seenAdsLoader = true;
          handler.post(
              () -> Log.w("DEBUG", "Ads loader: " + imaAdsLoader.getAdsLoader()));
        }
      }
    });
```

Some notes/caveats:
- I think the posting to the main thread is not actually necessary in the current release but will be needed in future to ensure that the `AdsMediaSource` handles the timeline change event before the call to `getAdsLoader`, as the way this works in `ImaAdsLoader` is going to change soon.
- This snippet only works if the ad tag loaded is non-empty.
- As you can see, this is not very convenient at the moment. I would be grateful to hear more about what you need the ads loader for so we can see if there is an easier way to do it without needing to access the IMA SDK `AdsLoader` instance.

**Comment by nishantkp** [comment]
Hi @andrewlewis ,

I need IMA SDK ’s `AdsLoader.AdsLoadedListener` is for querying `com.google.ads.interactivemedia.v3.api.AdsManager` on `onAdsManagerLoaded(AdsManagerLoadedEvent event)` callback  from `AdsManagerLoadedEvent`. 

After I get AdsManager, I use `AdsManager.addAdEventListener` to get notified for different types of ad events. Then these events are used for controlling ads volume programmatically, skipping pre-rolls/mid-rolls for resuming a video from history position (depending upon playhead position), analytics (ad-pod/ad info, ad start/completete events), adjust aspect ratio between `AspectRatioFrameLayout.RESIZE_MODE_FIT` and `AspectRatioFrameLayout.RESIZE_MODE_ZOOM` depending upon user preference and ad playback (adjust to default aspect ratio regardless of user preference), controlling control rack visibility (show/hide depending on the user tap)

Something like this, 
```java
 @Override
 public void onAdsManagerLoaded(@NonNull AdsManagerLoadedEvent adsManagerLoadedEvent) {
         AdsManager adsManager = adsManagerLoadedEvent.getAdsManager();
         adsManager.addAdEventListener(adEvent -> {
            if (adsManager != null) {
                switch (adEvent.getType()) {
                    case TAPPED:
                        break;
                    case AD_BREAK_STARTED:
                        break;
                    case AD_BREAK_ENDED:
                        break;
                    case STARTED:
                        break;
                    case PAUSED:
                        break;
                    case COMPLETED:
                        break;
                    case CONTENT_RESUME_REQUESTED:
                        break;
                    case CONTENT_PAUSE_REQUESTED:
                        break;
                    case LOG:
                        break;
                    case SKIPPED:
                        break;
                    case CLICKED:
                        break;
                    default:
                        break;
                }
            }
        });
    }
```

**Comment by andrewlewis** [comment]
@nishantkp I think you should be able to attach a listener via `ImaAdsLoader.Builder.setAdEventListener`.

For what it's worth, I think there are equivalents for almost all of the things you are trying to do, though:

> controlling ads volume programmatically

You can query `player.isPlayingAd` after a position discontinuity event from the player and set volume accordingly.

> skipping pre-rolls/mid-rolls for resuming a video from history position (depending upon playhead position)

If you seek before preparing the player, ads before the start position are skipped. `ImaAdsLoader.setPlayAdBeforeStartPosition(false)` can be used to skip the first ad that would play (if any). If you need to skip ads with finer granularity that isn't supported for video ads at the moment (`skipAd` is intended for audio ads, and we don't expose `discardAdBreak`).

> analytics (ad-pod/ad info, ad start/completete events)

Although ad info from IMA is missing, if you just want to log playback of ads starting/finishing there should be enough information in ExoPlayer's `AnalyticsListener`.

> adjust aspect ratio between AspectRatioFrameLayout.RESIZE_MODE_FIT and AspectRatioFrameLayout.RESIZE_MODE_ZOOM depending upon user preference and ad playback (adjust to default aspect ratio regardless of user preference), controlling control rack visibility (show/hide depending on the user tap)

Similar to the first item above, the main requirement for the event is to tell when ads start/stop playing, which can be done via position discontinuity events from the player.

I'll close this issue now given that it's possible to attach an ad event listener. Thanks!
