### ISSUE TITLE
Performance on Sony 5.1.1

### ISSUE THREAD

**Issue by IonAalbers** [google/ExoPlayer#816]
The ExoPlayer was working fine until we updated the Sony Z2 tablet (SGP512)  to Android 5.1.1 (from 5.0.1) now this tablet has lots of frame drops, every second it drops at least 10 frames.
The same exact thing happend when updating the Sony Z2 phone (D6503) when also updating from 5.0.1 to 5.1.1.

To test if this was caused by the UI/app I replaced streamed the Youtube sample from the demo. But this was streaming smoothly.

The stream is DASH with Widevine on ExoPlayer 1.4.2.

So it seems like my stream (which I cannot share publicly) causes something odd, what is the best way to debug this issue?

**Comment by ojw28** [comment]
This is an issue with Sony's platform software update :(. My understanding is that they're aware and will be resolving the performance problem in a future update.

**Comment by IonAalbers** [comment]
Oh thats just great.. 
But why isn't this a problem on the ExoPlayer demo streams, these are also DRM protected, right?

**Comment by ojw28** [comment]
Which demo streams, specifically?

**Comment by IonAalbers** [comment]
http://www.youtube.com/api/manifest/dash/id/d286538032258a1c/source/youtube?as=fmp4_audio_cenc,fmp4_sd_hd_cenc&sparams=ip,ipbits,expire,source,id,as&ip=0.0.0.0&ipbits=0&expire=19000000000&signature=477CF7D478BE26C205045D507E9358F85F84C065.8971631EB657BC33EC2F48A2FF4211956760C3E9&key=ik0

With videoId 'd286538032258a1c'

**Comment by ojw28** [comment]
Right. Yes, that is DRM protected. I'm not sure. It might be that the performance issue only applies when HDCP is required, and/or when the secure video path is required. I'd suggest trying some of the other samples that have different requirements to figure this out.

**Comment by IonAalbers** [comment]
I tried all the streams within WIDEVINE_GTS in the demo, they don't show any performance drops.
So their might be something about our streams that causes this..

**Comment by ojw28** [comment]
We've definitely seen similar performance issues. I'm fairly sure I reproduced with the sample videos at some point on one of the Sony Xperia device range. I doubt it's anything specific that you're doing. All the platform does is decrypt and decode the frames; ExoPlayer handles things like stripping away the container at the application layer. A few random ideas about things that might make some streams worse than others:

- Higher bitrates and/or resolutions.
- License policy (already covered above) around HDCP / Secure path. I'm unsure whether there's anything for the audio streams that would be analogous. There are also policy settings for things like PST usage table features, which you could try turning on and off if you want to experiment.

**Comment by ojw28** [comment]
I think (hope?) Sony fixed this in more recent device updates.
