### ISSUE TITLE
After upgrading from 2.11.8 to 2.12.1 and replacing deprecated components I can't play any video.

### ISSUE THREAD

**Issue by dscoppelletti** [google/ExoPlayer#8160]
### [REQUIRED] Searched documentation and issues
[Release Notes](http://github.com/google/ExoPlayer/blob/release-v2/RELEASENOTES.md) for version 2.12.1 and 2.12.0.

### [REQUIRED] Question
I've recently upgraded `com.google.android.exoplayer:exoplayer-core` from version 2.11.8 to version 2.12.1.  
Some components are deprecated by version 2.12.1 in the following code snippet.

```
        cacheEvictor = LeastRecentlyUsedCacheEvictor(CACHE_SIZE_MAX)
        databaseProvider = ExoDatabaseProvider(context)
        cache = SimpleCache(File(context.cacheDir, CACHE_DIR),
                cacheEvictor, databaseProvider)
        upstreamFactory = DefaultDataSourceFactory(context, USER_AGENT)
        // CacheDataSourceFactory class is deprecated
        cacheFactory = CacheDataSourceFactory(cache, upstreamFactory,
                CacheDataSource.FLAG_BLOCK_ON_CACHE or
                        CacheDataSource.FLAG_IGNORE_CACHE_ON_ERROR)
        mediaSourceFactory = ProgressiveMediaSource.Factory(cacheFactory)
        [...]
        val url: Uri
        val player: SimpleExoPlayer
        [...]
        // createMediaSource method is deprecated
        val mediaSource = mediaSourceFactory.createMediaSource(uri)
        // prepare method is deprecated
        player.prepare(mediaSource, true, true)

```

Thus I replaced the deprecated components by the newest ones.

```
        cacheEvictor = LeastRecentlyUsedCacheEvictor(CACHE_SIZE_MAX)
        databaseProvider = ExoDatabaseProvider(context)
        cache = SimpleCache(File(context.cacheDir, CACHE_DIR),
                cacheEvictor, databaseProvider)
        upstreamFactory = DefaultDataSourceFactory(context, USER_AGENT)
        cacheFactory = CacheDataSource.Factory().apply {
              setCache(this@VideoPlayer.cache)
              setUpstreamDataSourceFactory(upstreamFactory)
              setFlags(CacheDataSource.FLAG_BLOCK_ON_CACHE or                  
                    CacheDataSource.FLAG_IGNORE_CACHE_ON_ERROR)
        }
        mediaSourceFactory = ProgressiveMediaSource.Factory(cacheFactory)
        [...]
        val url: Uri
        val player: SimpleExoPlayer
        [...]
        val mediaItem =  MediaItem.fromUri(uri)
        val mediaSource = mediaSourceFactory.createMediaSource(mediaItem)
        player.setMediaSource(mediaSource, true)
        player.prepare(mediaSource, true)
```

After the updates, the player was black and I could not play any video (nothing usefull in Logcat).
I've returned to the deprecated components (still with version 2.12.1) and now I can play every video.

I think I messed up something when in replacing the deprecated components.   
Can you help me, please?

### A full bug report captured from the device
(EMPTY)

### Link to test content
(EMPTY)

**Comment by marcbaechinger** [comment]
Did you call `player.prepare()` in the new version? 

The call `player.prepare(mediaSource, true, true)` needs to be replaced by 

```
player.setMediaSource(source, /* resetPosition= */  false); // you do this already, you want false?
player.prepare(); // this is not part of your snippet above
```

**Comment by dscoppelletti** [comment]
Yes, @marcbaechinger , I call `player.prepare()` in the new version?. I've only mess the pasted code. Now I fixed it.

**Comment by marcbaechinger** [comment]
Hmm, I think the code looks roughly ok.
 
Can you isolate what change causes the problem? Like first still use the old deprecated `CacheMediaSourceFactory` as in the old version, then see whether that works? Then the other way around using the new `CacheMediaSource.Factory` but preparing the old way?

If you don't find something, can you please add

```
player.addAnalyticsListener(new EventLogger(/* trackSelector= */ null));
```

and send me the output of the logs? This way I can see what the player is doing because it is logged accordingly.

**Comment by dscoppelletti** [comment]
I am very sorry.  
You were right pointing out that the call `player.prepare(mediaSource, true, true)` needs to be replaced by:
```
player.setMediaSource(source, true);
player.prepare();
```
Then I messed again my pasted code because `player.prepare(false)`  does not exist and it must be simply `player.prepare()`.

Now the new code works fine.

Thanks.

**Comment by marcbaechinger** [comment]
Glad it works! Thanks for letting me know!
