### ISSUE TITLE
VideoScalingMode:  Java-only possible?

### ISSUE THREAD

**Issue by skreenr** [google/ExoPlayer#8163]
Hello ExoPlayer team:

How feasible is to set VideoScalingMode  with Java code only, no XML?
The code like this is not working for us as far as cropping function:

     Simple_player = new SimpleExoPlayer.Builder(getBaseContext()).build();
        Uri uri = RawResourceDataSource.buildRawResourceUri(R.raw.videofile );
        DataSource.Factory dataSourceFactory = new DefaultDataSourceFactory(getBaseContext(), "com.domain.theapp");
        videoSource = new ExtractorMediaSource.Factory( dataSourceFactory ).createMediaSource(uri);
        Simple_player.prepare(videoSource );
        Simple_player.setRepeatMode(Player.REPEAT_MODE_ONE);
        Simple_player.setVideoScalingMode(Renderer.VIDEO_SCALING_MODE_SCALE_TO_FIT_WITH_CROPPING);

**Comment by andrewlewis** [comment]
> How feasible is to set VideoScalingMode with Java code only, no XML?

It should work fine. If it doesn't work for you I suspect your output view is scaling the surface in a way that makes the new scaling mode a no-op. This seems closely related to your previous issue #8081, where it was necessary to set the resize mode on the player view (note there are methods `StyledPlayerView.setResizeMode` and `PlayerView.setResizeMode`).

**Comment by skreenr** [comment]
There is no output view and no XML, as I mentioned previously.

I don't see how your answer addresses the situation posted about.

**Comment by andrewlewis** [comment]
How do you obtain a Surface to render to?

**Comment by skreenr** [comment]
OnSurfaceCreated callback gives me a holder

**Comment by skreenr** [comment]
Any followup here? Thanks,

**Comment by ojw28** [comment]
As per the comment from @andrewlewis above, calling `setVideoScalingMode` should work fine. If it does not appear to do anything, it's possible that either:

1. You are encountering a device specific issue. There are some known device specific issues affecting this method, for example https://github.com/google/ExoPlayer/issues/2484.
1. Your `Surface` is being sized in such a way that makes the scaling mode a no-op, as mentioned by @andrewlewis above.

If you would like further assistance, please provide a complete and minimal example project that reproduces the issue, perhaps using our demo app as a starting point and editing it just enough to reproduce the issue. Just saying that it doesn't work does not give us sufficient information for us to help you. It's also not reasonable to expect us to provide complete sample code for your particular use case.

**Comment by skreenr** [comment]
On #1: this is on a recent Samsung phone, so if it's device-specific perhaps this should be treated like bug

Question on the code snippet above: Is there a requirement to use Renderer for a ScalingMode to work, and if so that could what's breaking it?

**Comment by ojw28** [comment]
The player uses renderers internally. As above, if you would like further assistance, please provide a complete and minimal example project that reproduces the issue, perhaps using our demo app as a starting point and editing it just enough to reproduce the issue.

**Comment by skreenr** [comment]
I emailed the Zip of the project
Let me know if not received
Let me know if you need video with different dimensions for test

**Comment by ojw28** [comment]
Clipping is working fine for me when I test this on a Pixel 4 XL. What device do you see the issue on?

**Comment by skreenr** [comment]
Galaxy A10e
model # SM-S102DL

**Comment by skreenr** [comment]
you don't see the green stripes?

your screen resolution 1440x3040 pixels ?
I may need to adjust video for the specs

**Comment by ojw28** [comment]
> you don't see the green stripes?

No

> your screen resolution 1440x3040 pixels ?

Yes

> I may need to adjust video for the specs

I don't understand what this means. The fact I don't see green stripes means that clipping is working, because if there were no clipping then all of the video would always be displayed, green stripes included.

**Comment by skreenr** [comment]
Here are screenshots as seen on Galaxy A10e with screen resolution exactly half of yours;
Both show green stripes on top and bottom, meaning the app scales video to fit in both X and Y dimensions.
The first one is of Preview in wallpaper picker, the second one is actual wallpaper






To test a theory I resized the video down to half resolution so as to imitate your situation, where it's stretched 2X horizontally, resulting in a 360pix X 790pix video. This still shows green stripes just like in screenshots above

**Comment by ojw28** [comment]
> Galaxy A10e with screen resolution exactly half of yours

This device doesn't have a screen resolution exactly half of mine. At 720x1560 pixels, its aspect ratio is a little taller/narrower when in portrait:

720 / 1440 = 0.5 (i.e., exactly half the width of the Pixel 4 XL)
1560 / 3040 = 0.513 (i.e., slightly over half the height of the Pixel 4 XL)

So it's expected that it will display a bit more of the video at the top and bottom compared to the Pixel 4 XL. It's also the case that a small amount of the green bars have been clipped, since they're bigger in the underlying source content. So, I think things are working as intended here, and that you've just prepared the video with the wrong aspect ratio for what you're trying to show.

**Comment by skreenr** [comment]
My math was a bit off. 
I re-did the video clip and now it's cropping perfectly. No green bars shows
The only thing of concern is, testing with odie Moto G/KitKat device the video plays not very smooth, with certain jerkiness
Is it due to Cropping operation expense? or just a high pixel count for the device

**Comment by ojw28** [comment]
I doubt it's due to the cropping. I suspect you're just hitting performance limitations on older devices. This may be pixel count, bitrate, frame-rate, etc. Most likely a combination of multiple factors.
