### ISSUE TITLE
how to change provision server url when 

### ISSUE THREAD

**Issue by vincenttsai-cloud** [google/ExoPlayer#8165]
I wrote my own player based on the exoplayer library, but I can't find the API to modify the url of the provision server. If I directly download the exoplayer code on GitHub, I can modify<<< public ProvisionRequest getProvisionRequest() >>>in FrameworkMediaDrm.java. But when writing a player based on the library of exoplayer, how to modify the provision url?

**Comment by icbaker** [comment]
Can you expand a bit on what you're trying to achieve? Why do you want to modify the provision URL?

`FrameworkMediaDrm` delegates most operations to Android's [`MediaDrm`](https://developer.android.com/reference/android/media/MediaDrm), including [`getProvisionRequest()`](https://developer.android.com/reference/android/media/MediaDrm#getProvisionRequest()).

Provisioning servers are provided by DRM implementations - so the provisioning URL generally doesn't need to be customised per-app.

If you want complete control you can implement your own [`ExoMediaDrm`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/drm/ExoMediaDrm.html) (and delegate to `FrameworkMediaDrm` if you want). You can use this in your app by calling `setUuidAndExoMediaDrmProvider` when building your `DefaultDrmSessionManager`. This is very advanced customisation though, I'd expect this to only be necessary if you're using a DRM scheme not supported by the `MediaDrm` implementation on the Android devices you're working on.

**Comment by icbaker** [comment]
Simpler alternative:
Inject a custom [`MediaDrmCallback`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/drm/MediaDrmCallback.html), and use your custom provisioning URL inside `executeProvisionRequest()`.

You'll either need to delegate to `HttpMediaDrmCallback` or pull in your own HTTP library/DataSource of choice.

**Comment by vincenttsai-cloud** [comment]
> 更简单的选择：
> 注入自定义[`MediaDrmCallback`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/drm/MediaDrmCallback.html)，然后在中使用您的自定义设置URL `executeProvisionRequest()`。
> 
> 您将需要委托`HttpMediaDrmCallback`或拉入自己选择的HTTP库/数据源。

I've done it this way, thank you very much
