### ISSUE TITLE
The video freezes in the first 10 seconds.

### ISSUE THREAD

**Issue by Hachimori** [google/ExoPlayer#8167]
### [REQUIRED] Issue description
The video freezes in the first 10 seconds.
- The video is expected to be played without freezes, as the video is played smoothly when I watched the video on web browser.

The issue happens on some of videos only ; I couldn’t reproduce the issue with most of videos over the internet.
- So, the issue could lie in the video itself / its encoding method.

That behavior could be, or couldn't be a buffering.
- After the first 10 seconds, the video is played properly. Then, I move its seek bar to the beginning, however, again the video freezes in the first 10 seconds.
- The issue happens when I let the app load the video from local storage. So, I believe it’s not server side / network issue.
- The issue happens when I let the app load the video from the internet too.

The issue happens on ExoPlayer **2.12.0**, but didn't happen on **2.8.4**.

### [REQUIRED] Reproduction steps
I've created a repo which I could reproduce the issue.
https://github.com/Hachimori/ExoPlayerSampleApplication

**Please note that the repo doesn't contain the freezing video due to the copyright problem** (the issue doesn't happen with ABC2.mp4 and Bee2.mp4 inside the repo).
I'll send a email which has the link to the video to dev.exoplayer@gmail.com.

To reproduce the issue in my repo, please specify the link in the email in MainActivity.kt, or download the video in assets/ and specify its filename in MainActivity.kt.

### [REQUIRED] Link to test content
Again, due to the copyright, I cannot post a link here. I'll sent a link to dev.exoplayer@gmail.com.

Here's the metadata of the video.

```
$ ffprobe 0002.mp4 
ffprobe version 4.3.1 Copyright (c) 2007-2020 the FFmpeg developers
  built with Apple clang version 12.0.0 (clang-1200.0.32.21)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.3.1_2 --enable-shared --enable-pthreads --enable-version3 --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librtmp --enable-libspeex --enable-libsoxr --enable-videotoolbox --disable-libjack --disable-indev=jack
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '0002.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 1
    compatible_brands: mp41mp42isom
    creation_time   : 2017-11-23T15:42:14.000000Z
  Duration: 00:01:55.89, start: 0.000000, bitrate: 1894 kb/s
    Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709), 1920x1080 [SAR 1:1 DAR 16:9], 1887 kb/s, 24.98 fps, 25 tbr, 90k tbn, 180k tbc (default)
    Metadata:
      creation_time   : 2017-11-23T15:42:14.000000Z
      handler_name    : Core Media Video
```

### [REQUIRED] A full bug report captured from the device

I've attached the full bug report using "adb bugreport".
[bugreport-sdk_gphone_x86_arm-PSR1.180720.117-2020-11-05-12-38-25.zip](https://github.com/google/ExoPlayer/files/5494284/bugreport-sdk_gphone_x86_arm-PSR1.180720.117-2020-11-05-12-38-25.zip)

### [REQUIRED] Version of ExoPlayer being used
2.12.0

### [REQUIRED] Device(s) and version(s) of Android being used
I've reproduced in following devices:

- Pixel 2 API 28 (Emulator)
- Nexus 5X API 24 (Emulator)

**Comment by Hachimori** [comment]
Additional remarks: while we investigate the issue, we found that the issue is resolved when we re-encode the video using ffmpeg without additional options.
What we did is `$ ffmpeg -i 0002.mp4 0002_ffmpeg.mp4` and the video was played without freezes.

**Comment by lcf87** [comment]
I think that can be categorized as bad media?

**Comment by lcf87** [comment]
The problem is with MP4's edit list. The first MP4 file has an edit list telling the player to play after 0.265 second, apparently there was not a keyframe for some while, so the video freezes.

One workaround is to let ExoPlayer ignore the edit list altogether, and the video plays from the start. [Please reference here](https://exoplayer.dev/troubleshooting.html#why-do-some-mp4fmp4-files-play-incorrectly)

**Comment by Hachimori** [comment]
@lcf87 

Thank you!  As you mentioned, I could resolve the issue by ignoring edit lists.

For those who interested, this is the changes I made:
- https://github.com/Hachimori/ExoPlayerSampleApplication/commit/2eb4a8044ebb0119504dfad6d4c64109ef05d9a1
