### ISSUE TITLE
Impossible to play clear lead of DASH manifest

### ISSUE THREAD

**Issue by mseroczynski** [google/ExoPlayer#8168]
ExoPlayer version: 2.12.1

I am getting an `ExoPlaybackException` due to `UnexpectedLoaderException` when below method is called (`Track.java`):

```
  /**
   * Returns the {@link TrackEncryptionBox} for the given sample description index.
   *
   * @param sampleDescriptionIndex The given sample description index
   * @return The {@link TrackEncryptionBox} for the given sample description index. Maybe null if no
   *     such entry exists.
   */
  @Nullable
  public TrackEncryptionBox getSampleDescriptionEncryptionBox(int sampleDescriptionIndex) {
    return sampleDescriptionEncryptionBoxes == null ? null
        : sampleDescriptionEncryptionBoxes[sampleDescriptionIndex];
  }
```

It happens because of:
![Zrzut ekranu 2020-11-05 o 17 23 38](https://user-images.githubusercontent.com/7540518/98267417-a8edbd00-1f8b-11eb-95fe-6698cf599ca1.png)

Do you have any ideas what may be wrong? The manifest seems fine when tested with other players.

**Comment by lcf87** [comment]
Could you fill out the issue template and provide us with the media that triggered this problem to help us help you better, thanks!

**Comment by mseroczynski** [comment]
Manifest: https://audio-test.atkcdn.com/53a04460-20ae-474b-8fc0-181e657764f5/4acbfae6-a5d2-4ded-b112-4295cfa37103/dash-cenc/sample-manifest.mpd

**Comment by mseroczynski** [comment]
Please close this issue, the problem was

**Comment by mseroczynski** [comment]
Problem was related to corrupted manifest, sorry for the trouble.
