### ISSUE TITLE
DownloadManager/DownloadService, available space left

### ISSUE THREAD

**Issue by yoobi** [google/ExoPlayer#8169]
### [REQUIRED] Searched documentation and issues
I've looked into the issues in github and on stackoverflow

### [REQUIRED] Question

1. Does `DownloadManager`/`DownloadService` check the space left on storage before starting a download ? Does it allocates an estimated size in the storage to avoid 2 downloads starting and none finishing ?
2. What does the requirement `DEVICE_STORAGE_NOT_LOW` exactly do ? I've seen the doc which says `Requirement that the device's <em>internal</em> storage is not low` but what happens if my storage has 2Go left and I try to download 2 videos of 1.5Go each ? Will it prevent one from starting ?

**Comment by marcbaechinger** [comment]
Sorry for my late response. 

The downloader starts downloading without checking the available space. If the disk space is not sufficient this would end in an `IOException` and the `Download` is marked with `STATE_FAILED`.

The requirement `DEVICE_STORAGE_NOT_LOW` is used to schedule jobs either with the `PlatformSchedulerService` or the WorkManager` depending on what you are using. It decides whether to start a given job. As you say this is only relevant for starting a download. If a download is very large as in the example you are giving it may still fail when the device runs out of disk space. 

I the java doc of [JobInfo.Builder.setRequiresStorageNotLow(boolean)](https://developer.android.com/reference/android/app/job/JobInfo.Builder#setRequiresStorageNotLow(boolean)) that is used for the job scheduler it says:

```
Specify that to run this job, the device's available storage must not be low. 
This defaults to false. If true, the job will only run when the device is not 
in a low storage state, which is generally the point where the user is given 
a "low storage" warning.
```

so this only makes sure to not start a job at `the point where the user is given a "low storage" warning.`

You could try to estimate the size of a download yourself before adding a download request, but this isn't trivial. Please also see the discussion in this pull request #6347 (edit: you've already seen that, I leave it here for completenes).

**Comment by yoobi** [comment]
Okay thank you for the details, I'll make my own estimation and get the storage available though `StatFs`
