### ISSUE TITLE
I get a MediaDrmStateException on Pixel devices with Android 11.

### ISSUE THREAD

**Issue by TaruiTakashi** [google/ExoPlayer#8175]
### Searched documentation and issues
・ExoPlayer Javadoc.
・ExoPlayer Issues

### Question
MediaDrmStateException may occur when streaming a dash video.
The device that occurs is Pixel of Android 11.
However, not all Pixel devices will raise an exception, and some Pixel devices will raise an exception.

Please let us know the following
* is this a device specific issue?
* Should I change the way streaming playback is implemented?

Error log

```
ExoPlayerImplInternal: Playback error
ExoPlayerImplInternal:   com.google.android.exoplayer2.ExoPlaybackException: Source error
ExoPlayerImplInternal:       at m.c.b.b.o0.handleMessage(ExoPlayerImplInternal.java:41)
ExoPlayerImplInternal:       at android.os.Handler.dispatchMessage(Handler.java:102)
ExoPlayerImplInternal:       at android.os.Looper.loop(Looper.java:223)
ExoPlayerImplInternal:       at android.os.HandlerThread.run(HandlerThread.java:67)
ExoPlayerImplInternal:   Caused by: com.google.android.exoplayer2.drm.DrmSession$DrmSessionException: android.media.MediaDrm$MediaDrmStateException: Failed to get key request: General DRM error
ExoPlayerImplInternal:       at com.google.android.exoplayer2.drm.DefaultDrmSession.a(DefaultDrmSession.java:47)
ExoPlayerImplInternal:       at com.google.android.exoplayer2.drm.DefaultDrmSession.b(DefaultDrmSession.java:35)
ExoPlayerImplInternal:       at com.google.android.exoplayer2.drm.DefaultDrmSession.a(DefaultDrmSession.java:46)
ExoPlayerImplInternal:       at com.google.android.exoplayer2.drm.DefaultDrmSession.a(DefaultDrmSession.java:31)
ExoPlayerImplInternal:       at com.google.android.exoplayer2.drm.DefaultDrmSession.a(DefaultDrmSession.java:10)
ExoPlayerImplInternal:       at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.a(DefaultDrmSessionManager.java:65)
ExoPlayerImplInternal:       at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.b(DefaultDrmSessionManager.java:1)
ExoPlayerImplInternal:       at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.a(DefaultDrmSessionManager.java:56)
ExoPlayerImplInternal:       at m.c.b.b.c2.k0.a(SampleQueue.java:157)
ExoPlayerImplInternal:       at m.c.b.b.c2.k0.a(SampleQueue.java:55)
ExoPlayerImplInternal:       at m.c.b.b.c2.k0.a(SampleQueue.java:8)
ExoPlayerImplInternal:       at m.c.b.b.c2.s0.h.a(ChunkSampleStream.java:83)
ExoPlayerImplInternal:       at m.c.b.b.e0.a(BaseRenderer.java:17)
ExoPlayerImplInternal:       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.b(MediaCodecRenderer.java:3)
ExoPlayerImplInternal:       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.a(MediaCodecRenderer.java:37)
ExoPlayerImplInternal:       at m.c.b.b.o0.b(ExoPlayerImplInternal.java:154)
ExoPlayerImplInternal:       at m.c.b.b.o0.handleMessage(ExoPlayerImplInternal.java:25)

```

Source code

```
private var simpleExoPlayer: SimpleExoPlayer? = null
var playerView: PlayerView? = null

~~~~

playerView = view.findViewById(R.id.player_view)

~~~~

val drmSessionManagerBuilder = DefaultDrmSessionManager.Builder()
player = SimpleExoPlayer.Builder(context).build()

val bandwidthMeter = DefaultBandwidthMeter.Builder(context).build()

val dataSourceFactory = DefaultHttpDataSourceFactory(
    Util.getUserAgent(context, context.getString(R.string.app_name)),
    bandwidthMeter
)

val drmCallback = HttpMediaDrmCallback(licenseUrl, true, dataSourceFactory)

val mediaSource = DashMediaSource.Factory(dataSourceFactory)
    .setDrmSessionManager(drmSessionManagerBuilder.build(drmCallback))
    .createMediaSource(MediaItem.fromUri(Uri.parse(manifestUrl)))

player?.setMediaSource(mediaSource)

player?.prepare()
player?.playWhenReady = true


simpleExoPlayer = player
playerView?.player = player
```

Version of ExoPlayer being used: 2.12.1

### A full bug report captured from the device
sorry.
This error is caused by a user who is using the app we are releasing, so we cannot get the bug report.
If I need a bug report, I ask the user to submit a bug report.
Please let us know if you need a bug report.
Ask the user to submit a bug report.

**Comment by lcf87** [comment]
Could you provide us a bug report? We'll need one to debug DRM issues.

**Comment by rrfrias** [comment]
The exception thrown is unfortunately too generic. We are working on improving this in future releases.

For this release we will need a bugreport to investigate furthur. If you are unable to share bug reports publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #8175".

**Comment by TaruiTakashi** [comment]
Please be patient as we ask users to send us a bug report.

**Comment by TaruiTakashi** [comment]
@rrfrias 
I have sent the bugreport to dev.exoplayer@gmail.com.
Please check it out.

**Comment by jt64** [comment]
Thank you for providing the bugreport. We can see in the bugreport that this is an error we have been working on with Qualcomm that happens on Pixel devices.

A suggested workaround would be if you see multiple errors from MediaDrm.getKeyRequest, to force a reprovision using getProvisionRequest and provideProvisionResponse, like you would if the device has not been provisioned.

**Comment by TaruiTakashi** [comment]
@jt64 
Thank you for the workaround answer.

What is provision?
Also, I didn't see any errors in the ExoPlayer sample app, but does the sample app do any reprovision or other processing?

**Comment by jt64** [comment]
Provisioning is installing a drm certificate from the provisioning certificate server. An app needs to provision before it is able to get licenses to play drm content. I see you are using ExoPlayer, so your app isn't directly using the mediadrm APIs. Olly is there a way for an app to force provisioning through ExoPlayer?

**Comment by ojw28** [comment]
Providing an API for force provisioning is tracked by https://github.com/google/ExoPlayer/issues/8039.
