### ISSUE TITLE
[Widevine-DASH] Check Chunks info getting Played

### ISSUE THREAD

**Issue by Taranlayal10** [google/ExoPlayer#8177]
I checked the onChunkLoadCompleted in the DefaultDashChunkSource class. Is there any way I can get callback to check chunk that is being played

### [REQUIRED] Question
I am playing DASH Content with Widevine and the buffering time is pretty much more than usual. I need to check which chunk is getting more time in getting load. Is there any way I can get the chunk URL information that is being played

**Comment by Taranlayal10** [comment]
Hi @ojw28 

Request your attention. Its little bit urgent to debug this.

**Comment by ojw28** [comment]
> Is there any way I can get the chunk URL information that is being played

There isn't an easy way to get this directly from the player. That said, the player gives you both the playback position, and the manifest (by calling `Player.getCurrentManifest`). It should be possible for you to work out which chunk in the manifest the playback position corresponds to.

Aside from the direct answer above, it's quite unclear whether what you're asking for is really what you need. If you want to identify where chunks are loading slower than expected, the currently playing chunk isn't what you should be looking at. Instead, try implementing an `AnalyticsListener`, registering it to the player (`SimpleExoPlayer.addAnalyticsListener`) and implementing the `AnalyticsListener.onLoadCompleted` method. You get _lots_ of information about each load via that method, including how long it took (`loadEventInfo.loadDurationMs`), the chunk start and end time (`mediaLoadData.mediaStartTimeMs`, `mediaLoadData.mediaEndTimeMs`), the chunk URL (`loadEventInfo.dataSpec.uri`) and so on. This information should be sufficient for you to identify loads that are taking longer than expected. I'd suggest carefully reading the Javadoc for `LoadEventInfo` and `MediaLoadData` to see exactly what data is available.
