### ISSUE TITLE
addtional questions & answers

### ISSUE THREAD

**Issue by ilker-aktuna** [google/ExoPlayer#8179]
I am sorry but I had to open a new issue to continue on this issue:
https://github.com/google/ExoPlayer/issues/8097

I really would not prefer to open a new issue but since it is closed, I guess there's no other option.

>>> Why do I observe zero length chunks when everything is normal ?

>> I'm guessing the empty ones may be requests that are not media chunks (initialization data for example). Can you tell from the load event info or media load data passed to AnalyticsListener.onLoadCompleted what kind of loads they were?

how can I determine the type of loadcomplete events ?

>>> Is there a way of disabling rebuffer totally ?

>> You could try increasing the player's buffer buffer for playback to be equal to the duration of the media, via DefaultLoadControl. Then the player won't transition out of the buffering state until it's loaded the entire stream. I think that any setup where you have a smaller buffer leaves open the possibility that loading will become slow and playback will exhaust all loaded data. Of course this isn't appropriate for a real playback application as it may use lots of RAM and the user will need to wait until the entire stream is in memory before playback starts.

how can I set the player's buffer to a static duration and stop the media after that duration ?
I really want to play just a 30 seconds of live media and then stop.
I only want to analyze if 30 seconds of media is well received from the server. 
so : start media - get 30 seconds of media - stop
how can I achieve that ?

at time of problem, I observe that loadcomplete events increase but rebuffer does not increase. What does that mean ?

**Comment by andrewlewis** [comment]
Continuing on #8097.

**Comment by ilker-aktuna** [comment]
added this to previous issue.
closing.
