### ISSUE TITLE
PlayerNotificationManager not show notification on android 10

### ISSUE THREAD

**Issue by mahdisadeghi74** [google/ExoPlayer#8181]
I use https://medium.com/google-exoplayer/playback-notifications-with-exoplayer-a2f1a18cf93b and create exoplayer but it is not work on android 10 devices!! how can i fix this?

player play music but not show notification on android 10!!

```
{
   var playerNotificationManager = PlayerNotificationManager(
            this, CHANNEL_ID, NOTIFICATION_ID, DescriptionAdapter(), object : PlayerNotificationManager.NotificationListener{

            }
        )

        var player = ExoPlayerFactory.newSimpleInstance(this, DefaultTrackSelector());
        player.playWhenReady = true
        player.addMediaItem(MediaItem.fromUri(Uri.parse("asset:///test.mp3")))
        playerNotificationManager.setPlayer(player)

        player.prepare()
        player.play()
    }
}
```

**Comment by marcbaechinger** [comment]
I've seen `PlayerNotificationManager` working on Android 10. I don't think that it is a general problem with Android 10. If I add it to the demo app for example I see this works.

May I ask to review your code and look whether things are set up as explained it the Medium blog post? The code you pasted above looks a bit like being in a temporary state (like the test.mp3 and the no-op NotificationListener). Just refactoring can probably help making it work.

**Comment by mahdisadeghi74** [comment]
> I've seen `PlayerNotificationManager` working on Android 10. I don't think that it is a general problem with Android 10. If I add it to the demo app for example I see this works.
> 
> May I ask to review your code and look whether things are set up as explained it the Medium blog post? The code you pasted above looks a bit like being in a temporary state (like the test.mp3 and the no-op NotificationListener). Just refactoring can probably help making it work.

Thank you for response.
But  you can see my project https://github.com/mahdisadeghi74/MusicPlayer

1- When I test on "Pixel2 API 25 emulator"  it is work
2- When I test on "Pixel2 XL API 29 emulator" it is not work and show "Failed to post notification on channel "CHANNEL_ID" see log for more details" inside toast message 
3- When I test on "Huawei Honor 8x real device" it is not work without any message

**Comment by marcbaechinger** [comment]
In this case you need to create a notification channel for the given CHANNEL_ID. Since API 26 a notification needs to have a channel or the notification is not posted with the error message you pasted above.

You can either create [your own channel](https://developer.android.com/training/notify-user/channels) for the given CHANNEL_ID or you can use one of the [static factory methods](https://github.com/google/ExoPlayer/blob/release-v2/library/ui/src/main/java/com/google/android/exoplayer2/ui/PlayerNotificationManager.java#L439) that creates the channel for your.

**Comment by mahdisadeghi74** [comment]
Thank you. I use  `createWithNotificationChannel `and my problem solve.
