### ISSUE TITLE
is exoplayer support the ima Non-Linear ad?

### ISSUE THREAD

**Issue by DaveBoy** [google/ExoPlayer#8183]
i use the [demo](https://github.com/googleads/googleads-ima-android) and Non-Linear ad tag:`https://pubads.g.doubleclick.net/gampad/ads?sz=480x70&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dnonlinear&correlator=`(sometimes it response empty,use ie maybe all right)

it use the exoplayer ima extension,but i found it not show ad  when the content video play.

the url is right when i use [vastinspector](https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/vastinspector) to test 

is the ima not support non-linear ad？

**Comment by ojw28** [comment]
According to [this page](https://developers.google.com/interactive-media-ads/docs/sdks/android/client-side/compatibility), non-linear ads are only supported with the HTML5 version of the IMA SDK. The Android version (and also the iOS version) supports the following types:

> Linear and companion ads, Ad Manager video, Ad Exchange video, and AFV ads
