### ISSUE TITLE
short video and long IMA mid-roll ad

### ISSUE THREAD

**Issue by DaveBoy** [google/ExoPlayer#8186]
use the tag url `https://pubads.g.doubleclick.net/gampad/ads?env=vp&gdfp_req=1&unviewed_position_start=1&output=vast&iu=/5374/TV2video/avod/programmer/underholdning/love-island-uk/sesong-5&sz=640x480&description_url=https://www.tv2.no/v/1463716&hl=no&cmsid=2510181&vid=1463716` in [7477](https://github.com/google/ExoPlayer/issues/7477),
my video is `https://storage.googleapis.com/gvabox/media/samples/stock.mp4`,the  video only has 1 minute,but the ad mid-roll has more than the video length.

then the player stop play anything after 1m,and the duration still incress ,the progress is wrong,such as 3:55/1:00.
when time arrive the 9:44,the third ad time,player become  normal.

**Comment by andrewlewis** [comment]
Supporting playback of ad tags where cue points are beyond the content duration is tracked by #5534.
