### ISSUE TITLE
Fix and improve handling of audio session IDs

### ISSUE THREAD

**Issue by master255** [google/ExoPlayer#8190]
@ojw28 Perhaps you need to pay special attention to AudiosessionId, and to test its work properly?
I regularly come across the fact that it does not work:
https://github.com/google/ExoPlayer/issues/6954.
https://github.com/google/ExoPlayer/issues/6975

ExoPlayer 2.12.0
Android 4.4 audio session stops transmitting data after rewinding and when you switch to the next track. There are no errors or notifications in the logs.

mMediaPlayer.getAudioSessionId() - method does not work. It regularly returns 0 at the time when the session number is different.

**Comment by ojw28** [comment]
If you want us to investigate this, please provide proper reproduction steps, ideally in the form of a minimal test app. Note that #6954 also lacked clear reproduction steps, to the extent that it's still unclear whether there was a bug. #6975 also lacked clear reproduction steps until 12 messages in, and when they were finally provided we were able to provide a clear answer.

**Comment by master255** [comment]
@google-oss-bot This is your module. You should test it, not me. If you are not interested, I can do nothing to help.
I switched to VLC. It has a better sound and a better picture.

**Comment by ojw28** [comment]
Handling of audio session IDs is much improved in https://github.com/google/ExoPlayer/commit/a95b2ebb1d3125a4899c0dfe4a830077271ebca0, which will be in `2.13.0`.
