### ISSUE TITLE
StreamVolumeManager crash during Initialization on certain devices when getting getStreamVolume from AudioManager

### ISSUE THREAD

**Issue by saurabhkpatel** [google/ExoPlayer#8191]
### [REQUIRED] Issue description

Getting the following crash after bumping the new release version which has this commit: https://github.com/google/ExoPlayer/commit/160ee9d890df463fe907c09736f932b255e1c53d

**Crash is:**
- During SimpleExoPlayer inits, StreamVolumeManager sets the volume which gets the streaming volume from AudioManager and it gives NPE.

### [REQUIRED] Reproduction steps
This crash is very device-specific, I see this crash only happens on some manufactured (so far only two: **RealMe**
**OPPO**) Android 10 devices.

### [REQUIRED] Link to test content
NA

### [REQUIRED] A full bug report captured from the device
```
--- Caused by.java.lang.NullPointerException:Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
android.os.createException ( Parcel .java :2093)
android.os.readException ( Parcel .java :2055)
android.os.readException ( Parcel .java :2003)
android.media.getStreamVolume ( IAudioService .java :2409)
android.media.getStreamVolume ( AudioManager .java :1115)
com.google.android.exoplayer2.getVolumeFromManager ( StreamVolumeManager .java :180)
com.google.android.exoplayer2.<init> ( StreamVolumeManager .java :68)
com.google.android.exoplayer2.<init> ( SimpleExoPlayer .java :648)
com.google.android.exoplayer2.build ( SimpleExoPlayer .java :513)
```

### [REQUIRED] Version of ExoPlayer being used
2.12.1

### [REQUIRED] Device(s) and version(s) of Android being used

Brand: realme
Model: realme X2Pro, realMe 5 pro,realme 2 Pro
Brand: OPPO
Model: R15 Pro, A52, A72, K3,

**Comment by kim-vde** [comment]
This seems to be a device-specific issue in Android framework. I will implement a workaround.

**Comment by kim-vde** [comment]
I just pushed the fix. Please let us know if you still encounter issues with the `AudioManager` in the future.

**Comment by saurabhkpatel** [comment]
@kim-vde : what's the timeline to release this?

**Comment by kim-vde** [comment]
Probably end of November or beginning of December.
