### ISSUE TITLE
How to use spatial audio in Exoplayer 2.12.1 ?

### ISSUE THREAD

**Issue by Daktm** [google/ExoPlayer#8193]
How to use spatial audio in Exoplayer 2.12.1 ?

**Comment by kim-vde** [comment]
You should use the [GVR extension](https://github.com/google/ExoPlayer/tree/release-v2/extensions/gvr). [This article](https://medium.com/google-exoplayer/spatial-audio-with-exoplayer-and-gvr-cecb00e9da5f#.xdjebjd7g) explains how to do it.

Note that the GVR extension is deprecated, but I am afraid there is no other way to implement spatial audio in ExoPlayer.

**Comment by master255** [comment]
@Daktm Looks like [ExoPlayer is not for music](https://github.com/google/ExoPlayer/issues/8198).
Just use VLC. Use the settings in it:
options.add("--audio-resampler");
options.add("any");
options.add("--spatialaudio-headphones");
