### ISSUE TITLE
Download notification crash on API 19

### ISSUE THREAD

**Issue by yoobi** [google/ExoPlayer#8197]
### [REQUIRED] Issue description
When I start a download on my phone I got a crash because of the notification

I found this while searching: https://stackoverflow.com/a/38999661/6074224 it might help to resolve the issue

### [REQUIRED] Reproduction steps
I've got a repo which you can use to reproduce the bug https://github.com/yoobi/exoplayer-kotlin/tree/master/downloadvideo (note that it is still in development)

### [REQUIRED] A full bug report captured from the device
```
11-10 09:59:49.394 16574-16574/com.app.exoplayer_kotlin E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.app.exoplayer_kotlin, PID: 16574
    android.app.RemoteServiceException: Bad notification posted from package com.app.exoplayer_kotlin: Couldn't create icon: StatusBarIcon(pkg=com.app.exoplayer_kotlinuser=0 id=0x7f0800d6 level=0 visible=true num=0 )
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1453)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5476)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
        at dalvik.system.NativeStart.main(Native Method)
```
### [REQUIRED] Version of ExoPlayer being used
2.12.0

### [REQUIRED] Device(s) and version(s) of Android being used
API 19 Galaxy S3 Neo Android 4.4.2

**Comment by marcbaechinger** [comment]
The StackOverflow post says that with KitKat the icons must not be SVG. In the project you linked above I see that you are using custom drawables that are xml file. I suspect these are not working (the demo app uses png for all API levels).

I'd suggest you first replace your icons with a png to see whether that solves the problem. You can [pick those from the demo app](https://github.com/google/ExoPlayer/tree/release-v2/demos/main/src/main/res/drawable-xxxhdpi) for a first test. 

If this is working and you want to use SVG for the API levels that support them you can [provide alternative png drawables for those API levels](https://developer.android.com/guide/topics/resources/providing-resources#AlternativeResources) that do not support SVG.

**Comment by yoobi** [comment]
Ooh you're totally right I didn't pick the image from the demo, my bad.
