### ISSUE TITLE
Please open a security advisory

### ISSUE THREAD

**Issue by JLLeitschuh** [google/ExoPlayer#8200]
I have a relatively minor security vulnerability to disclose in ExoPlayer. I'd appreciate not going through the Google disclosure process because it's slow and heavyweight for what I'd like to disclose.

Would the maintainers of this project be willing to open a security advisory to allow me to disclose the vulnerability privately and quietly?

https://github.com/google/ExoPlayer/security/advisories

**Comment by kim-vde** [comment]
I just created one. Please tell me if I should do anything else (I have never used security advisories before). Thanks!

**Comment by JLLeitschuh** [comment]
Thanks @kim-vde!
