### ISSUE TITLE
exoplayer can not play widevine + ts m3u8

### ISSUE THREAD

**Issue by vincenttsai-cloud** [google/ExoPlayer#8202]
System info
exoplayer 2.12.1 +android 10

Issue and steps to reproduce the problem
Packager Command:

packager
'in=/media/media/2.ts,stream=video,segment_template=test1/$Number$.ts,playlist_name=test1/video.m3u8'
--hls_master_playlist_output master1.m3u8
--enable_widevine_encryption
--key_server_url https://license.uat.widevine.com/cenc/getcontentkey/widevine_test
--protection_scheme cenc
--content_id ***********************
--signer widevine_test
--aes_signing_key *****************************************
--aes_signing_iv ******************************************

Extra steps to reproduce the problem?

Our m3u8 file contains 2 clear streams, and the other streams are encrypted. The clear stream is played normally, and it gets stuck when starting to play the encrypted stream, and there is no error in the log

m3u8 file:
#EXTM3U
#EXT-X-VERSION:6

Generated with https://github.com/google/shaka-packager version v2.4.3-dd9870075f-release
#EXT-X-TARGETDURATION:6
#EXT-X-PLAYLIST-TYPE:VOD
#EXTINF:4.960,
1.ts
#EXTINF:5.960,
2.ts
#EXT-X-DISCONTINUITY
#EXT-X-KEY:METHOD=SAMPLE-AES,URI="data:text/plain;base64,
AA************************g==",
KEYID=0x8,IV=0x6,KEYFORMATVERSIONS="1",
KEYFORMAT="urn:uuid:----"
#EXTINF:5.960,
3.ts
#EXTINF:5.960,
4.ts
#EXTINF:5.960,
5.ts
#EXTINF:5.960,
6.ts
#EXTINF:5.960,
7.ts
#EXTINF:5.960,
8.ts
#EXTINF:5.960,
9.ts
#EXTINF:5.960,
10.ts
#EXTINF:5.960,
11.ts
#EXTINF:5.960,
12.ts
#EXTINF:5.960,
13.ts
#EXTINF:5.960,
14.ts
#EXTINF:5.960,
15.ts
#EXTINF:5.960,
16.ts
#EXTINF:5.960,
17.ts
#EXTINF:5.960,
18.ts
#EXTINF:5.960,
19.ts
#EXT-X-ENDLIST

**Comment by kim-vde** [comment]
Could you try to play your media in the [demo app](https://github.com/google/ExoPlayer/tree/release-v2/demos/main)? You will need to add it to [this](https://github.com/google/ExoPlayer/blob/release-v2/demos/main/src/main/assets/media.exolist.json) file? The corresponding object should have the following form:

```
{
    "name": "<name>",
    "uri": "<uri to HLS file>",
    "drm_scheme": "widevine",
    "drm_license_uri": "<DRM license URI>"
},
```

If it doesn't work, could you send us a bug report taken while playing the file in the demo app and a test content that reproduces the issue? If you're unable to share bug reports or test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #8202".

**Comment by AquilesCanta** [comment]
This is not currently supported. Please track #4021. Note there are no currently plans to implement support for this.
