### ISSUE TITLE
How to update UI with download progress 

### ISSUE THREAD

**Issue by yoobi** [google/ExoPlayer#8207]
### [REQUIRED] Searched documentation and issues
I've looked at your [doc](https://exoplayer.dev/downloading-media.html#querying-downloads) and stackoverflow

### [REQUIRED] Question
I'd like to make a recyclerview with all the download (and all state, ie downloading, done, error ...) 
I've been able to get all the download via the `DownloadCursor` and using that list in the `recyclerview` and then I refresh the value every second by calling [`loadDownload()`](https://github.com/google/ExoPlayer/blob/59b34ede6165d029d86a677fea73a5dd0dd55c74/demos/main/src/main/java/com/google/android/exoplayer2/demo/DownloadTracker.java#L130) but the changes appear in my `recyclerview` only every 4 or 5 seconds (even though `loadDownload()` is called every seconds). I'm guessing it has to do with the time it needs to browse the `Cursor`.

I'd like to know how am I supposed to get all the download and have the updated value ?

**Comment by marcbaechinger** [comment]
There is a section in the docs about ["Listening to Downloads"](https://exoplayer.dev/downloading-media.html#listening-to-downloads) has an info box about this. It refers to the `DownloadService` that has a [`ForegroundNotificationUpdater`](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/offline/DownloadService.java#L872) that updates the notification every second. I think that's a good example.

It uses

```
List<Download> downloads = Assertions.checkNotNull(downloadManager).getCurrentDownloads();
```

to get all downloads and the updates the notification. Then each download can be queried for  `getBytesDownloaded()` and `getPercentDownloaded()`.

**Comment by yoobi** [comment]
Yeah I saw the info box and used it for another screen, but I'm asking to get all downloads even the one completed, 
`List<Download> downloads = Assertions.checkNotNull(downloadManager).getCurrentDownloads();` only return the one in progress,paused or queued.

If I use `downloads` for my `recyclerview` I will only have the one in progress and not the completed or failed one.

**Comment by marcbaechinger** [comment]
Sounds like you can build up the recyclerview like you already do, then use the downloadManager to get most recent updates and update the adapter of the recycler view with the most recent data?

**Comment by yoobi** [comment]
Yeah I can build it the issue is that when I browse the Cursor it only updates every 4 or 5 iteration of the `while` loop instead of updating every iteration, that's why Cursor is not a good option for my issue, I wanted to know if you have any advice about it.

```kotlin
val downloadsCursor = MutableLiveData<DownloadCursor>()
val cursorAdapter = OfflineVideoCursorAdapter(downloadsCursor.value)
recyclerView.adapter = cursorAdapter

coroutineScope.launch {
    while(isActive) {
        downloadsCursor.postValue(DownloadUtil.getDownloadTracker(this@OfflineVideoActivity).downloadIndex.getDownloads())
        delay(1000)
    }
}
downloadsCursor.observe(this) { cursorAdapter.setDownload(it) }
```

**Comment by marcbaechinger** [comment]
I don't think you need a cursor. There is probably just no change in the download index.

I suggest you [get a simple list of `Download`s from the `DownloadIndex`](https://exoplayer.dev/downloading-media.html#querying-downloads), when you create the recycler view. Create an adapter that wraps that list. 

Then [register a listener to the `DownloadManager` like explained i the devguide](https://exoplayer.dev/downloading-media.html#listening-to-downloads). This way you get informed when downloads are added or removed. When the listener calls you, update your adapter of the recycler view and trigger the recycler view to be updated.

If, as a second step, you want to update your UI with the download progress of the download currently being downloaded, then you need to poll [like explained in the info box in the same section of the devguide](https://exoplayer.dev/downloading-media.html#listening-to-downloads). Then again you need to update the adapter with the updated download progress and trigger the recycler view to draw again.

I think that should be doable with what is documented in the dev guide. Please have a look. I can't give you close 1:1 support here I'm afraid. I leave the issue open though so someone else can add some hints if they want.

**Comment by makkhay** [comment]
@marcbaechinger  How can I create a list of downloads from the downloadIndex ? [ DownloadIndex.getDownloads()](https://exoplayer.dev/downloading-media.html#querying-downloads) return DownloadCursor. I am trying to do something similar as well. Want to get the real-time progress percentage for the list of videos and show it inside Recyclerview.
