### ISSUE TITLE
Unable to play some HLS URLs in the player

### ISSUE THREAD

**Issue by Sathish-Kumar-Kanagaraj** [google/ExoPlayer#8210]
### [REQUIRED] Question
I am unable to play the given HLS URL in most of the devices, but on some devices its playing, The URL link I have given in the test content section.
I just want to know what is the source error, since it is playing on web and android emulator devices but not playing on the latest real-world mobile devices So I am unable to capture the error.

### A full bug report captured from the device
Realme X and most of the device the following URL not playing
https://kripalunidhi.akamaized.net/jkp/audios/knaudio/33008_03_hare_ram_sankeertan___bageeshwari_devi/playlist.m3u8

### Link to test content
Playing audio: https://kripalunidhi.akamaized.net/jkp/audios/knaudio/31005_01_radhe_govind_govind_radhe___sushri_suswari_devi/playlist.m3u8 

Not Playing audio: https://kripalunidhi.akamaized.net/jkp/audios/knaudio/33008_03_hare_ram_sankeertan___bageeshwari_devi/playlist.m3u8

**Comment by kim-vde** [comment]
I couldn't reproduce neither on a Pixel 3, nor on a Samsung Galaxy Note 10+ (I tried [the first link](https://kripalunidhi.akamaized.net/jkp/audios/knaudio/33008_03_hare_ram_sankeertan___bageeshwari_devi/playlist.m3u8)). Can you reproduce with the [demo app](https://github.com/google/ExoPlayer/tree/release-v2/demos/main)?

Could you please provide a bug report captured when the problem occurs (using `adb bugreport`)? If you're unable to share bug reports or test content publicly, please send them to dev.exoplayer@gmail.com using subject "Issue #8210".

Something (probably unrelated) that I noticed about the media: the TS files in the media playlists declare a video track in their PMT while these files do not contain any video samples.
