### ISSUE TITLE
Custom data on MediaItem

### ISSUE THREAD

**Issue by roubertedgar** [google/ExoPlayer#8211]
Hey, we use a custom URI protection and the MediaItem just supports DRM credentials. In this case, on the exoplayer side, we are sending this custom data by creating a MediaSource with a DataSource that put our custom headers in the defaultRequestProperties. On the GoogleCast side, we're creating a MediaQueueItem with a custom data that has our credentials headers. 

Is there any possibility of adding a **Map<String, String> customData** field to the MediaItem? Thus, when converting the MediaItem, we could add this custom data to the MediaQueueItem (Google Cast) and the defaultRequestProperties present in the BaseFactory (Exoplayer). Thanks

**Comment by marcbaechinger** [comment]
You can use `new MediaItem.Builder().setUri(uri).setTag(yourCustomObject).build()`. Then you find your custom object in `mediaItem.playbackProperties.tag`. The tab is of type 'Object' so you can use whatever you want. There is a [code snippet](https://exoplayer.dev/media-items.html#simple-media-items) in the dev guide about this.

**Comment by roubertedgar** [comment]
I believe that the tag can help, many thanks
