### ISSUE TITLE
IMA Extension support for client-side DAI

### ISSUE THREAD

**Issue by adrianrdzv** [google/ExoPlayer#8213]
### Use case description
The IMA SDK now provides support for using dynamic ad insertion on the client
https://developers.google.com/interactive-media-ads/docs/sdks/android/dai
However, this requires to manipulate the AdsLoader. Currently the IMA Extension wraps the AdsLoader inside a ImaAdsLoader and would not be possible to request a Stream from it.

### Alternatives considered
Currently the only alternative to use client side DAI is bypass IMA Extension and directly construct the AdsLoader ourselves.

**Comment by andrewlewis** [comment]
The IMA extension only handles client-side ad insertion currently.

You can still use ExoPlayer as a player for DAI streams loaded by the IMA SDK, where your app interacts with the IMA SDK APIs directly (in this case the IMA extension isn't used at all). You'd need to write code to get the stream URL to play and propagate metadata events from the player.

I'll leave this open to track supporting DAI via the IMA SDK in the IMA extension (or a new extension), but marked as low priority as we aren't planning to work on it soon.

**Comment by victorraft** [comment]
Our company would very much appreciate if the Exo team implemented support for DAI! 
We have lots of apps using DAI and just today we found errors in our DAI implementation that are causing a great deal of issues, and I guess this would not have happened if we had a reliable DAI implementation in the Exo SDK itself, so that's something I'd very much like to see in the future :)

**Comment by cadalt** [comment]
yes! support for dai!

**Comment by nishantkp** [comment]
This will be very much appreciated. 
Support for DAI, way to go...

**Comment by marcbaechinger** [comment]
The `ImaServerSideAdInsertionMediaSoruce.Factory` has been published with 2.17.0. The first release supports IMA streams for HLS/DASH VOD and HLS live.

https://exoplayer.dev/ad-insertion.html#ima-extension-1
