### ISSUE TITLE
Replacement for buildAudioProcessor()

### ISSUE THREAD

**Issue by giangpham2811** [google/ExoPlayer#8216]
Details
-----------------------
In DefaultRenderersFactory in version 2.11.8 there was a function that is buildAudioProcessor(), I call it by : 
 @Override
        protected AudioProcessor buildAudioProcessor() {
        return new AudioProcessor[]{recording, speedChange};
    }
and return an AudioProcessor but when I upgrade exoplayer 2.12.1 , This function was no longer exists. Is there any methods or function that I can replace this?

**Comment by kim-vde** [comment]
You can probably use [`DefaultRenderersFactory#buildAudioSink`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/DefaultRenderersFactory.html#buildAudioSink-android.content.Context-boolean-boolean-boolean-) together with a [`DefaultAudioSink`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/audio/DefaultAudioSink.html#DefaultAudioSink-com.google.android.exoplayer2.audio.AudioCapabilities-com.google.android.exoplayer2.audio.DefaultAudioSink.AudioProcessorChain-boolean-boolean-boolean-).

**Comment by timusus** [comment]
For example:

```
val renderersFactory = object : DefaultRenderersFactory(context) {
            override fun buildAudioSink(context: Context, enableFloatOutput: Boolean, enableAudioTrackPlaybackParams: Boolean, enableOffload: Boolean): AudioSink? {
                return DefaultAudioSink(AudioCapabilities.DEFAULT_AUDIO_CAPABILITIES, DefaultAudioSink.DefaultAudioProcessorChain(<YOUR_AUDIO_PROCESSOR>).audioProcessors)
            }
        }
```
