### ISSUE TITLE
exoplayer模式 播放hls 进度条不对

### ISSUE THREAD

**Issue by ab503044120** [google/ExoPlayer#8217]
播放hls 直播流 exo内核 getDuration() 不为0 
ijk内核getDuration()为0
导致直播播放的时候进度条有进度
这个可以修复吗
附上链接地址
http://cctvalih5ca.v.myalicdn.com/live/cctv1_2/index.m3u8

**Comment by kim-vde** [comment]
Google Translate translation: 

Play hls live stream exo kernel getDuration() is not 0
ijk kernel getDuration() is 0
Cause the progress bar to have progress when the live broadcast is playing
Can this be fixed
Attach the link address

**Comment by kim-vde** [comment]
No sure I understand the question. You don't want any progress displayed in the progress bar, is that right?

In this case, I would remove or hide the progress bar. You can also implement a custom TimeBar.

You should check these pages:
- [UI components guide](https://exoplayer.dev/ui-components.html)
- [StyledPlayerControlView JavaDoc](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/ui/StyledPlayerControlView.html)
- [PlayerControlView JavaDoc](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/ui/PlayerControlView.html)

**Comment by ab503044120** [comment]
@kim-vde
thank you for you answer
I means that   I play this [link](http://cctvalih5ca.v.myalicdn.com/live/cctv1_2/index.m3u8) with ijkplayer  then the value  get by `getDuration()`  is 0, but exoplayer is not 0
 the m3u8 stream can be live or on-demand，how can i know that

**Comment by kim-vde** [comment]
> I means that I play this link with ijkplayer then the value get by getDuration() is 0, but exoplayer is not 0

The duration indicated in ExoPlayer is the sum of the segments duration given in the EXTINF tags.

> the m3u8 stream can be live or on-demand，how can i know that

You can use [`Player#isCurrentWindowLive`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/Player.html#isCurrentWindowLive--) (see #2668 for more info).

**Comment by ab503044120** [comment]
thx , it resolve it  by `Player#isCurrentWindowLive`
