### ISSUE TITLE
Internal track renderer error :  Unable to connect

### ISSUE THREAD

**Issue by randeeppr** [google/ExoPlayer#822]
Hi,

We are getting this error when we play the video. But from the chrome browser I am able to play the video all the time. What could be the issue?
I am able to wget the video also. (changed the urls because of security issues)

E/ExoPlayerImplInternal( 2078): Internal track renderer error.
E/ExoPlayerImplInternal( 2078): com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to http://**domain**/movie/HORRIBLE_BOSSES/HORRIBLE_BOSSES_enc_audio.mp4
E/ExoPlayerImplInternal( 2078):         at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:455)
E/ExoPlayerImplInternal( 2078):         at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:401)
E/ExoPlayerImplInternal( 2078):         at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:203)
E/ExoPlayerImplInternal( 2078):         at android.os.Handler.dispatchMessage(Handler.java:98)
E/ExoPlayerImplInternal( 2078):         at android.os.Looper.loop(Looper.java:136)
E/ExoPlayerImplInternal( 2078):         at android.os.HandlerThread.run(HandlerThread.java:61)
E/ExoPlayerImplInternal( 2078):         at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
E/ExoPlayerImplInternal( 2078): Caused by: com.google.android.exoplayer.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to http://**domain**/movie/HORRIBLE_BOSSES/HORRIBLE_BOSSES_enc_audio.mp4
E/ExoPlayerImplInternal( 2078):         at com.google.android.exoplayer.upstream.HttpDataSource.open(HttpDataSource.java:258)
E/ExoPlayerImplInternal( 2078):         at com.google.android.exoplayer.upstream.UriDataSource.open(UriDataSource.java:66)
E/ExoPlayerImplInternal( 2078):         at com.google.android.exoplayer.upstream.DataSourceStream.load(DataSourceStream.java:223)
E/ExoPlayerImplInternal( 2078):         at com.google.android.exoplayer.chunk.Chunk.load(Chunk.java:179)
E/ExoPlayerImplInternal( 2078):         at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:206)
E/ExoPlayerImplInternal( 2078):         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
E/ExoPlayerImplInternal( 2078):         at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/ExoPlayerImplInternal( 2078):         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/ExoPlayerImplInternal( 2078):         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/ExoPlayerImplInternal( 2078):         at java.lang.Thread.run(Thread.java:841)
E/ExoPlayerImplInternal( 2078): Caused by: java.net.SocketTimeoutException
E/ExoPlayerImplInternal( 2078):         at java.net.PlainSocketImpl.read(PlainSocketImpl.java:491)
E/ExoPlayerImplInternal( 2078):         at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:46)
E/ExoPlayerImplInternal( 2078):         at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:240)
E/ExoPlayerImplInternal( 2078):         at java.io.InputStream.read(InputStream.java:162)
E/ExoPlayerImplInternal( 2078):         at java.io.BufferedInputStream.fillbuf(BufferedInputStream.java:142)
E/ExoPlayerImplInternal( 2078):         at java.io.BufferedInputStream.read(BufferedInputStream.java:227)
E/ExoPlayerImplInternal( 2078):         at com.android.okhttp.internal.Util.readAsciiLine(Util.java:316)
E/ExoPlayerImplInternal( 2078):         at com.android.okhttp.internal.http.RawHeaders.fromBytes(RawHeaders.java:308)
E/ExoPlayerImplInternal( 2078):         at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:135)
E/ExoPlayerImplInternal( 2078):         at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:644)
E/ExoPlayerImplInternal( 2078):         at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:347)
E/ExoPlayerImplInternal( 2078):         at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:296)
E/ExoPlayerImplInternal( 2078):         at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:503)
E/ExoPlayerImplInternal( 2078):         at com.google.android.exoplayer.upstream.HttpDataSource.open(HttpDataSource.java:256)
E/ExoPlayerImplInternal( 2078):         ... 9 more

Regards,
Randeep

**Comment by ojw28** [comment]
Well, it is a connection error. Does your domain contain any underscores by any chance? If not, there's not much we can do to debug the issue without the proper link (feel free to email it to olly.exoplayer@gmail.com)

**Comment by randeeppr** [comment]
@ojw28 
We were able to fix this issue. It was a firewall issue. 
Thank you :)

**Comment by neo17** [comment]
Why is underscore a problem when it is located in the host part of the url? I encounter some problems with underscores in the url but only on some devices with android 4.1 and lower.
