### ISSUE TITLE
How can I get  the pts int TS or MP4 

### ISSUE THREAD

**Issue by arlimm318** [google/ExoPlayer#8226]
I want to get the PTS of the currently rendered video frame.
Hoe  can I get  it?

**Comment by icbaker** [comment]
You can register a `VideoFrameMetadataListener` with `SimpleExoPlayer#setVideoFrameMetadataListener()` - this will give you a `onVideoFrameAboutToBeRendered` callback for each frame.

**Comment by arlimm318** [comment]
yes，But the presentationTimeUs in VideoFrameMetadataListener  isn't the PTS in PES packet.
I want raw PTS in video from the video.

**Comment by arlimm318** [comment]
I want to know whether the playback progress of the two different streams is consistent by comparing PTS, and the video source of the two streams is consistent.

**Comment by AquilesCanta** [comment]
Is this in the context of HLS or is it just a TS/MP4 file you are playing?

**Comment by arlimm318** [comment]
udp stream  or  http stream

**Comment by ojw28** [comment]
ExoPlayer does not expose the underlying MPEG-2 PTS timestamps. Without a clear motivating use case, this isn't a feature we'll be adding support for. Closing this for now because no use case has been stated.
