### ISSUE TITLE
find a error about com.google.android.exoplayer2.util.Util.getDataUriForString 

### ISSUE THREAD

**Issue by dy1023348109** [google/ExoPlayer#8228]
Use in ImaAdLoader : 
      adTagDataSpec = new DataSpec(Util.getDataUriForString(adsResponse, "text/xml"));
but the method params are define like this:
      public static Uri getDataUriForString(String mimeType, String data);

so if you use vast response, You will never succeed 。。。。。

**Comment by icbaker** [comment]
This is fixed by https://github.com/google/ExoPlayer/commit/4289112947dfac41c1ea45f14c01153bf3fe2eab which will be released in 2.12.2.
