### ISSUE TITLE
unable to play gifv from imgur

### ISSUE THREAD

**Issue by vvincirey** [google/ExoPlayer#823]
I am trying to play gifv and gfy files from imgur and gfycat which are basically webm/mp4 videos. According to exoplayer documentation they should be supported, But i am unable to play them. I am testing on a lollipop device so vp9 should be supported too. Could you please guide me. I used demo app to test.
Device details : Yu Yuphoria

**Comment by ojw28** [comment]
I took a look at the source of the [this gifv](i.imgur.com/zvATqgs.gifv). It looks like gifv is syntactic sugar around actual mp4 and webm videos, whose urls in this are ```http://i.imgur.com/zvATqgs.mp4``` and ```http://i.imgur.com/zvATqgs.webm```. ExoPlayer plays both of these urls correctly, so it seems we're already doing the right thing here.

**Comment by vvincirey** [comment]
Thanks its working. But i cant seem to get it work with this(http://fat.gfycat.com/MadeupShamelessIndianjackal.webm).
And is there any way i can play them like gif's, like repeat mode.

**Comment by ojw28** [comment]
The link you provide works fine for me. We don't support loop mode as a direct feature at this time. The best you could do would be to reset the position back to 0 when the player tells you that it's ended.
