### ISSUE TITLE
Custom audio processor getting incorrect channel count with (baked audio?) adaptive HLS that has mono and stereo audio

### ISSUE THREAD

**Issue by Ste-RH** [google/ExoPlayer#8230]
### [REQUIRED] Issue description
I have created a few audio processors (a pan, and one that allows me to pipe samples out to an external entity).  On playing an HLS stream that has a mixture of mono and stereo audio think the 'onConfigure' method is not being called when the adaptive track selection changes the audio stream.  I am seeing 'inputAudioFormat.channelCount' reporting that there are 2 channels of audio, but never comes through as 1 channel when, I think, the track selector is dropping it down.

I have tested this with a local MP4 video with a single mono audio stream and I get a single channel reported in the 'channelCount' variable.

Some additional information on the stream.  It looks like there is no audio stream defined in the manifest, but rather the audio is baked into the track segments.  With the lower bitrates have the mono audio baked in (tracks 0, 1 and 2), whilst the higher ones appear to have stereo audio baked in.

Off the back of the above information, I have tested selecting the lower resolution/bitrate video tracks on their own and indeed see a 'chanelCount' of 1 coming through.

I tested the stream in the ExoPlayer demo and get a assert stop/crash when I try to select an individual track.  The demo does report the selectable audio as both stereo and mono.

If indeed there is an issue, I am not convinced it is manifesting itself with negative effect in the demo and 'regular' use-cases.  I am piping out the audio samples to be played externally (via Unity) and the result of the incorrect channel count is (I think) double samples being pumped to my output buffer...which is leading to half speed pitched down playback.

### [REQUIRED] Reproduction steps
- Create an audio processor and insert it into the processing chain
- Use adaptive track selection
- Play back the following stream: [http://sample.vodobox.net/skate_phantom_flex_4k/skate_phantom_flex_4k.m3u8](http://sample.vodobox.net/skate_phantom_flex_4k/skate_phantom_flex_4k.m3u8)
- Logging out of the custom AudioProcessors 'onConfigure' function will show that the 'inputAudioFormat.channelCount' is 2

### [REQUIRED] Link to test content
[http://sample.vodobox.net/skate_phantom_flex_4k/skate_phantom_flex_4k.m3u8](http://sample.vodobox.net/skate_phantom_flex_4k/skate_phantom_flex_4k.m3u8)

### [REQUIRED] A full bug report captured from the device
[bugreport-NRD90M-2020-11-16-13-16-53.zip](https://github.com/google/ExoPlayer/files/5546449/bugreport-NRD90M-2020-11-16-13-16-53.zip)

### [REQUIRED] Version of ExoPlayer being used
2.12.1

### [REQUIRED] Device(s) and version(s) of Android being used
- Nexus 7 (2nd generation)
- NVidia Shield Tablet

**Comment by icbaker** [comment]
@christosts PTAL from an HLS perspective - I suspect (but might be wrong) this is related to the way the ExoPlayer HLS module creates tracks.

Please reassign if it turns out to be more tied to the audio-specific parts of ExoPlayer.

**Comment by christosts** [comment]
If I read the description correctly, there may be 3 issues involved: 
1. Player not calling `AudioProcessor.configure()` (or `BaseAudioProcessor.onConfigure()`) whenever there is an audio format change, to at least detect audio channel count.
2. When playing the provided HLS stream in the demo app, the demo app does not detect both audio streams (audio and mono).
3. When a selecting a specific track on the demo app, there's an assertion failing that causes a crash.

I need to ask for some clarifications:

> Off the back of the above information, I have tested selecting the lower resolution/bitrate video tracks on their own and indeed see a 'chanelCount' of 1 coming through.

Was this with the ExoPlayer demo app or with your app? I tried the playing the provided HLS stream with the ExoPlayer demo app (v2.12.1, no custom components) on a Pixel device. I manually chose the video tracks (one at a time). When playing the first two bitstreams, they have 1 channel and I do see the format being propagated all the way to calling [AudioProcessor.configure()](https://github.com/google/ExoPlayer/blob/r2.12.1/library/core/src/main/java/com/google/android/exoplayer2/audio/DefaultAudioSink.java#L531). When I chose any of the other bitstreams, the format was propagated all the way to AudioProcessor.configure() too, with channel count set to 2. 

> I tested the stream in the ExoPlayer demo and get an assert stop/crash when I try to select an individual track. 

Was this with your custom audio processors or was it without any custom components. As I wrote above, I did not see any crashes when I played the stream. So, I'd need to verify if you are seeing the crash with the exact same setup.

I do not see a stacktrace on the provided bugreport. Was this bugreport captured playing the demo app or your app?

**Comment by Ste-RH** [comment]
Thanks for your time on this one.

I have spent a few more hours adding debug logging and tracing through where the channel count mismatch was coming from and, apologetically, it is down to where my code pics up the channel count. So (1) in your summation is as you see, complete correct and doing what it should do.

Point (2) is probably correct I think?  Technically it is correct that there is only a mono stream reported as there is only one audio stream reported.  Though is is indeed the case that the video having embedded mono/stereo audio in the video tracks is what was causing the problem (I was taking the mono reported stream as the number of channels when I need to poke the audio format directly to get that piece of information)

Point (3) is a strange one.  Yes, it was in the ExoPlayer demo app.  I saw the crash on the Shield Tablet (which I do not have to hand today).  The code is stock v2.12.1, with the exception that I have renamed the package across the board to avoid clashes with other Unity plugin assets using different versions of ExoPlayer).  I have tested the exact same scenario on the Nexus 7 (2nd gen) and Xiaomi Mi10 T and I do not see the same crash.  When I am next in our office (in the next few days for sure) I will test again and send a crash dump if I can reproduce it (no reason to suspect I won't be able to).  That said...if you are not concerned about this side issue, I am obviously happy for this issue to be closed down.

Apologies again for wasting your time.

**Comment by Ste-RH** [comment]
Wait, wait...strike that bit about it not happening on the Nexus7.  I had commented out the assert that fires (and added an 'if' check):

TrackSelectorView.java

```
private void updateViewStates() {
    disableView.setChecked(isDisabled);
    defaultView.setChecked(!isDisabled && overrides.size() == 0);
    for (int i = 0; i < trackViews.length; i++) {
      SelectionOverride override = overrides.get(i);
      for (int j = 0; j < trackViews[i].length; j++) {
        if (override != null) {
          TrackInfo trackInfo = (TrackInfo) /*Assertions.checkNotNull(*/trackViews[i][j].getTag();//);
          if( trackViews[i][j].getTag() != null )
            trackViews[i][j].setChecked(override.containsTrack(trackInfo.trackIndex));
        } else {
          trackViews[i][j].setChecked(false);
        }
      }
    }
  }
```

With that null check back in I get the crash on the Nexus7, but it is fine on he Xiaomi Mi 10T.

Here is the crash dump...(it's not a full bugreport as the device is running Android 6.0.1)

[2020.11.23_Nexus7_Bugreport.zip](https://github.com/google/ExoPlayer/files/5585250/2020.11.23_Nexus7_Bugreport.zip)

**Comment by christosts** [comment]
I see how this can happen if at [TrackSelectionView.java L292](https://github.com/google/ExoPlayer/blob/r2.12.1/library/ui/src/main/java/com/google/android/exoplayer2/ui/TrackSelectionView.java#L292) ExoPlayer decides a track is not handled by the respective renderer and later, in updateViewStates(), there's a selection override for this track (`if (override != null) {`).

We will add a quick fix for this case, but out of curiosity, does this occur with stock v2.12.1 as you said? That is, there are no other custom components, e.g. a custom track selector, right?

**Comment by Ste-RH** [comment]
Aside from renaming the package, it is stock 2.12.1

Give me an hour or two and I will test this on a fresh pull (so completely stock) and report back.

**Comment by Ste-RH** [comment]
I can confirm that a completely stock 2.12.1 also bombs as described on the Nexus7 (2013)

**Comment by christosts** [comment]
We pushed commit [a8365c2](https://github.com/google/ExoPlayer/commit/a8365c2cca37917cb8aa4a2e9c0936b1cdada18e) on the dev-v2 branch. I'd appreciate if you can spend 5' testing this on your Nexus device.

**Comment by Ste-RH** [comment]
I can report that the issue appears fixed running on my Nexus device 👍

(happy for you to close this one if you see fit)

**Comment by christosts** [comment]
Thank you for the assistance!
