### ISSUE TITLE
java.io.EOFException at about 1-2 seconds from of end of m4a audio track

### ISSUE THREAD

**Issue by chunanli** [google/ExoPlayer#8233]
### [REQUIRED] Issue description
Player gets stuck at about 1-2 seconds from end of track for 1-2 minutes and throws `java.io.EOFException` eventually when streaming from web on our own application. Able to reproduce with demo player playing from local file, though in this scenario I'm seeing this error `java.io.EOFException` being thrown every 2 seconds or so from the middle of song, player will also stopped short about 1 second from end of song and `Playback failed` error message shown on UI.

### [REQUIRED] Reproduction steps
Using demo app, I've added the audio file to the `assets` folder, and modified `media.exolist.json`:
```
    "name": "Misc",
    "samples": [
      {
        "name": "Dizzy (MP4)",
        "uri": "asset:///track.m4a"
      },
```

### [REQUIRED] Link to test content
Sent email with link to media. Please download it to play from local file, as playing directly from link will cause player to not recognized the format likely due to incorrect http response `Content-Type` header.

### [REQUIRED] A full bug report captured from the device
Sent email with link to bug report.

### [REQUIRED] Version of ExoPlayer being used
2.11.7, 2.11.8, 2.12.1

### [REQUIRED] Device(s) and version(s) of Android being used
Multiple devices, e.g. Pixel 2/Android 10, Pixel 3/Android 11.

**Comment by icbaker** [comment]
I can reproduce the `EOFException` with the provided instructions. It produces the below stack trace several times before eventually failing playback. It's first thrown at ` mediaPos=141.38`, i.e. 2m21.38s in to the 3m19s sample.

@kim-vde can you take a look?

```
2020-11-17 09:47:34.345 15846-15846/com.google.android.exoplayer2.demo E/EventLogger: internalError [eventTime=34.60, mediaPos=195.46, window=0, period=0, loadError
      java.io.EOFException
        at com.google.android.exoplayer2.source.SampleDataQueue.sampleData(SampleDataQueue.java:193)
        at com.google.android.exoplayer2.source.SampleQueue.sampleData(SampleQueue.java:530)
        at com.google.android.exoplayer2.extractor.TrackOutput.sampleData(TrackOutput.java:161)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readSample(Mp4Extractor.java:626)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:249)
        at com.google.android.exoplayer2.source.BundledExtractorsAdapter.read(BundledExtractorsAdapter.java:127)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1044)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)
    ]
```

**Comment by kim-vde** [comment]
The problem is that the samples declared in the `stbl` box are not all present in the `mdat` box, as if the file had been cut without adapting the `moov` box consequently.

**Comment by chunanli** [comment]
Thank you @kim-vde. We did notice that the issue goes away by re-encoding the track, though it means we have to identify all such tracks in our catalog, not a trivial task. What makes it bad for user experience, is that for some reason, if we're streaming the track from web, it takes the player about 1-2 minutes before `EOFException` is thrown.  Other than us finding and re-encoding all such tracks, is there anything  we can do to make `ExoPlayer` identify or notify sooner at runtime to improve user experience?

**Comment by kim-vde** [comment]
For performance reasons, ExoPlayer generally does not scan a content to check its validity before playing it so it won't notify you of the error before it actually tries to read the missing samples.

To solve this, you could make your own `Mp4Extractor` from the existing one that would check the sample table before starting to extract the samples. This could for example work by checking if the last sample of each track in the `List<TrackSampleTable>` (`trackSampleTables.get(i).offsets[sampleCount - 1]`) retrieved in `processMoovAtom()` is located before the end of the file (`input.getLength()`). You could also try to play the file without error by removing all the missing samples from the `trackSampleTables` or by returning RESULT_END_OF_INPUT when the extractor fails at reading a sample.

Custom extractors can be added by passing a custom `ExtractorsFactory` to the `SimpleExoPlayer` builder.

**Comment by ojw28** [comment]
> though it means we have to identify all such tracks in our catalog, not a trivial task

I'm not sure it's really that hard. There are tools you can use to efficiently check whether your media files are valid. So you just need to find one that detects this type of error, and run it over your catalog. If a relatively low number of files are affected then re-encoding wont be expensive either. It looks like this command will quickly tell you about the problem, for example:
```
$ ffmpeg -v error -i <your-file.m4a> -f null -
[aac @ 0x55d388ad7dc0] TYPE_FIL: Input buffer exhausted before END element found
Error while decoding stream #0:0: Invalid data found when processing input
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55d388ac1f40] stream 0, offset 0x24e10e: partial file
<your-file.m4a>: Invalid data found when processing input
```

**Comment by chunanli** [comment]
@kim-vde , @ojw28 , thank you both for your suggestions, we will look into them.
