### ISSUE TITLE
[OMX.google.mp3.decoder] ERROR(0x80001001) throws when trying to dequeueOutputBuffer

### ISSUE THREAD

**Issue by siduytruong-us** [google/ExoPlayer#8234]
### [REQUIRED] Issue description
Hi Exo-dev, I'm creating an app that gets all the buffer from readAllocationNode (while node is empty or reach the limit 4 nodes can be read)  in SampleQueue.java. After that, I stored all buffer I got in my cache and pass into the OMX.google.mp3.decoder (configure sample-rate: 44100, 2 channels, max-input-size: size of buffer that I stored ~ 196608 bytes). The issue is sometimes decoder works fine, I can get decoded-buffer and do my job. But sometimes, it throws the issue below

### [REQUIRED] Reproduction steps
First, I get all buffer in SampleQueue.java I described above, then stored it in my cache.
Second, I pass all buffers into my decode method I put below the _while (feedInputBuffer())_  in _render_ method in MediaCodecRenderer.java.
Third, I'm using decoder within my DecoderAsyncTask, the decoding process I imitate like ExoPlayer feed->drain. The issue happens when I trying to dequeueOutputBuffer and it dropped all buffer remain. 

### [REQUIRED] Link to test content
[https://drive.google.com/file/d/1Nsg5ei1nCnK-wdBFBwKJuOnCZ6J-VCvo/view?usp=sharing](url)

### [REQUIRED] A full bug report captured from the device
```
4148-6324/com.vng.zalo.zmediaplayerdemo E/ACodec: [OMX.google.mp3.decoder] ERROR(0x80001001)
4148-6324/com.vng.zalo.zmediaplayerdemo E/ACodec: signalError(omxError 0x80001001, internalError -2147483648)
4148-6324/com.vng.zalo.zmediaplayerdemo E/MediaCodec: Codec reported err 0x80001001, actionCode 0, while in state 6
4148-5336/com.vng.zalo.zmediaplayerdemo W/System.err: java.lang.IllegalStateException
4148-5336/com.vng.zalo.zmediaplayerdemo W/System.err:     at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
4148-5336/com.vng.zalo.zmediaplayerdemo W/System.err:     at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2789)
4148-5336/com.vng.zalo.zmediaplayerdemo W/System.err:     at com.vng.android.exoplayer2.audio.silencesound.OutputRatingSilence$RatingBufferAsyncTask.drainOutputFromCodec(OutputRatingSilence.java:252)
4148-5336/com.vng.zalo.zmediaplayerdemo W/System.err:     at com.vng.android.exoplayer2.audio.silencesound.OutputRatingSilence$RatingBufferAsyncTask.convertOutputToRawData(OutputRatingSilence.java:239)
4148-5336/com.vng.zalo.zmediaplayerdemo W/System.err:     at com.vng.android.exoplayer2.audio.silencesound.OutputRatingSilence$RatingBufferAsyncTask.doInBackground(OutputRatingSilence.java:162)
4148-5336/com.vng.zalo.zmediaplayerdemo W/System.err:     at com.vng.android.exoplayer2.audio.silencesound.OutputRatingSilence$RatingBufferAsyncTask.doInBackground(OutputRatingSilence.java:130)
4148-5336/com.vng.zalo.zmediaplayerdemo W/System.err:     at android.os.AsyncTask$3.call(AsyncTask.java:378)
4148-5336/com.vng.zalo.zmediaplayerdemo W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
4148-5336/com.vng.zalo.zmediaplayerdemo W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
4148-5336/com.vng.zalo.zmediaplayerdemo W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
4148-5336/com.vng.zalo.zmediaplayerdemo W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
4148-5336/com.vng.zalo.zmediaplayerdemo W/System.err:     at java.lang.Thread.run(Thread.java:919)
4148-5336/com.vng.zalo.zmediaplayerdemo W/System.err: java.lang.IllegalStateException
4148-5336/com.vng.zalo.zmediaplayerdemo W/System.err:     at android.media.MediaCodec.native_stop(Native Method)
4148-5336/com.vng.zalo.zmediaplayerdemo W/System.err:     at android.media.MediaCodec.stop(MediaCodec.java:2147)
4148-5336/com.vng.zalo.zmediaplayerdemo W/System.err:     at com.vng.android.exoplayer2.audio.silencesound.OutputRatingSilence$RatingBufferAsyncTask.releaseCodec(OutputRatingSilence.java:213)
4148-5336/com.vng.zalo.zmediaplayerdemo W/System.err:     at com.vng.android.exoplayer2.audio.silencesound.OutputRatingSilence$RatingBufferAsyncTask.drainOutputFromCodec(OutputRatingSilence.java:255)
4148-5336/com.vng.zalo.zmediaplayerdemo W/System.err:     at com.vng.android.exoplayer2.audio.silencesound.OutputRatingSilence$RatingBufferAsyncTask.convertOutputToRawData(OutputRatingSilence.java:239)
4148-5336/com.vng.zalo.zmediaplayerdemo W/System.err:     at com.vng.android.exoplayer2.audio.silencesound.OutputRatingSilence$RatingBufferAsyncTask.doInBackground(OutputRatingSilence.java:162)
4148-5336/com.vng.zalo.zmediaplayerdemo W/System.err:     at com.vng.android.exoplayer2.audio.silencesound.OutputRatingSilence$RatingBufferAsyncTask.doInBackground(OutputRatingSilence.java:130)
4148-5336/com.vng.zalo.zmediaplayerdemo W/System.err:     at android.os.AsyncTask$3.call(AsyncTask.java:378)
4148-5336/com.vng.zalo.zmediaplayerdemo W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
4148-5336/com.vng.zalo.zmediaplayerdemo W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
4148-5336/com.vng.zalo.zmediaplayerdemo W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
4148-5336/com.vng.zalo.zmediaplayerdemo W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
4148-5336/com.vng.zalo.zmediaplayerdemo W/System.err:     at java.lang.Thread.run(Thread.java:919)
4148-5336/com.vng.zalo.zmediaplayerdemo W/DUY_TAG: ===> END CODEC ]] -- with end times: -9.223372036854775E12
```

### [REQUIRED] Version of ExoPlayer being used
2.9.5.11

### [REQUIRED] Device(s) and version(s) of Android being used
Virtual Devices: 7.3 Foldable API 29
Real Devices: vsmart joy 3, google pixel 2 (100% failed), Samsung SM-G975F

**Comment by icbaker** [comment]
From the description it sounds like you've made some quite low-level changes in ExoPlayer, in particular changing how it interacts with MediaCodec, and now you're seeing exceptions from MediaCodec.

I suspect these exceptions are the result of the changes you've made.

Customising ExoPlayer in this way (by directly editing the source of low-level components) is outside the scope of this issue tracker, so I'm afraid we can't offer much support. I'll leave the question open for a couple of weeks in case anyone else wants to chime in with suggestions.

You may find there's some additional logging slightly higher up in your logcat that provides some more information about what MediaCodec is complaining about. You may also need to go digging around in the MediaCodec source to understand some of the error codes that are being logged.

**Comment by siduytruong-us** [comment]
But can I ask you @icbaker this? If I pass a big input buffer size (~196608 bytes) into the codec and execute the job every 5 seconds, maybe the codec will throw error like description above because I'm passing a big data size into mediacodec or loop job in a short time?

**Comment by icbaker** [comment]
>If I pass a big input buffer size (~196608 bytes) into the codec and execute the job every 5 seconds, maybe the codec will throw error like description above because I'm passing a big data size into mediacodec or loop job in a short time?

I'm afraid questions about the behaviour of MediaCodec are outside the scope of this issue tracker (that component lies beneath the ExoPlayer library).

I'm going to close this question due to inactivity.
