### ISSUE TITLE
Dash streaming, Manifest url is called multiple times. Is this indended?

### ISSUE THREAD

**Issue by athulantonynp** [google/ExoPlayer#8235]
I am not sure whether this is the intended behaviour of exoplayer or not. So basically, we have a manifest file which is hosted on our server. The manifest file contains the location of video file to stream and other streaming configuration such as audio tracks meta and video resolution metas etc., As far as my understanding, while the streaming initialization, exoplayer requests for the manifest file first and after parsing the manifest file, it starts to request HTTP range operations to actual video URL for streaming. I believe manifest fetching and parsing is a one time operation while HTTP range operation isn't.

I have used OkHttp's exoplayer extension for viewing the API calls and got a strange behaviour that the manifest URL is fetched repeatedly. I cannot find out specific intervals for the call to happen. But it happens repeatedly. I would like to know whether this is intended behaviour or am I doing something wrong here?

The DASH URL used for streaming is listed below
[URL](http://rdmedia.bbc.co.uk/dash/ondemand/bbb/2/client_manifest-common_init.mpd)

Used versions
**extension-okhttp:2.11.7
exoplayer:exoplayer-core:2.11.4
exoplayer:exoplayer-dash:2.11.4**

**Comment by icbaker** [comment]
I added log lines to `DefaultHttpDataSource.open()` and `DefaultHttpDataSource.close()` and played the entire sample you linked. I saw a single open() call to fetch the manifest followed almost immediately by a matching close() call:

```
2020-11-17 11:41:32.982 19742-19914/com.google.android.exoplayer2.demo W/: open(); url=http://rdmedia.bbc.co.uk/dash/ondemand/bbb/2/client_manifest-common_init.mpd
2020-11-17 11:41:33.315 19742-19914/com.google.android.exoplayer2.demo W/: close(); url=http://rdmedia.bbc.co.uk/dash/ondemand/bbb/2/client_manifest-common_init.mpd
```

>I have used OkHttp's exoplayer extension for viewing the API calls and got a strange behaviour that the manifest URL is fetched repeatedly. I cannot find out specific intervals for the call to happen. But it happens repeatedly.

Can you provide some more concrete info here? Do you see it being fetched every 10ms, every 1 minute, something else?

**Comment by icbaker** [comment]
Aside:

**Comment by icbaker** [comment]
Aside:

It's not supported to use different versions of the core library and the extensions, you may well find they're incompatible, I'd strongly suggest you use either everything at 2.11.4 or 2.11.7.

>Used versions
>extension-okhttp:2.11.7
>exoplayer:exoplayer-core:2.11.4
>exoplayer:exoplayer-dash:2.11.4

**Comment by athulantonynp** [comment]
Thanks for the suggestions @icbaker I will get back to you with more info with updated dependencies.

**Comment by athulantonynp** [comment]
Thank you @icbaker The issue got cleared. Some improper logic with code made the bug. Thanks for the insights.
