### ISSUE TITLE
ExoPlayer as part of item in RecyclerView is hiding controls like play, pause etc.

### ISSUE THREAD

**Issue by liridonsadiku** [google/ExoPlayer#8236]
Hi there,

I have a strange issue with ExoPlayer which I have implemented as part of recyclerView to play audio file. When I click on item it should expand and show exo player, but if the list is large so the user can scroll, the controls are not showing properly, if the list is short for example it has only two items exo player is showing controls well.

Any suggestions?

**Comment by icbaker** [comment]
Without being able to reproduce this issue it's going to be very hard for us to offer help.

Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that demonstrates the problem in a way that we can build locally. 

This could be an Android Studio project on GitHub, or zipped up and sent to dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Please also update this issue to indicate you’ve done this.
