### ISSUE TITLE
how to play control play next previous shewing in google map     

### ISSUE THREAD

**Issue by nateshjammy** [google/ExoPlayer#8238]
Before filing a feature request:
-----------------------
- Search existing open issues, specifically with the label ‘enhancement’:
  https://github.com/google/ExoPlayer/labels/enhancement
- Search existing pull requests: https://github.com/google/ExoPlayer/pulls

When filing a feature request:
-----------------------

during media player is playing and this time google map  navigation view  default application and playback control in google map view how to enable like Spotify 
 
### [REQUIRED] Use case description

during media player is playing and this time google map  navigation view  default application and playback control in google map view how to enable like Spotify

**Comment by icbaker** [comment]
I believe this Google Maps feature only supports YouTube Music, Spotify and Apple Music - I don't think it's possible to integrate an arbitrary media app.

https://www.xda-developers.com/google-maps-now-supports-youtube-music-playback-controls/

Closing this as it's not related to ExoPlayer.

**Comment by nateshjammy** [comment]
how to set the same as my own   ExoPlayer. via intent
setting ->navigation setting  -> default music app shows my media player app
