### ISSUE TITLE
The countdown of the ima extension is frozen after loading

### ISSUE THREAD

**Issue by sajjadshahbazi** [google/ExoPlayer#8239]
I'm using ImaAdsLoader for show advertisement.
when watching an ad if the show loading view(Buffering Event), the countdown is stopped.

**Comment by sshahbazi** [comment]
[ad_test.zip](https://github.com/google/ExoPlayer/files/5554818/ad_test.zip)

**Comment by sshahbazi** [comment]
video attached for show the bug

**Comment by sshahbazi** [comment]
https://admin.deema.agency/?c=v&m=tag&placementId=1678&videotype=prerole&wPlayer=0&hPlayer=0&ip=151.241.1.99&ua=okhttp&domain=namava.ir&page=/&secure=1&language=fa&res=xml

**Comment by icbaker** [comment]
Thanks for the video - I can reproduce what you're seeing in the demo app by forcing a rebuffer during the ad playback and playing the "VMAP pre-roll" IMA sample.

@andrewlewis The code I used to reproduce is in internal change 343081629.

**Comment by sajjadshahbazi** [comment]
I do not know what to do about this problem.
Please advise you

**Comment by sajjadshahbazi** [comment]
In addition to the buffer mode, sometimes these three events happen quickly in a row (even it may be early in the ad show).

FIRST_QUARTILE
MIDPOINT
THIRD_QUARTILE

The loading is displayed and then the timer stops.

**Comment by andrewlewis** [comment]
Thank you for reporting this. There is a fix in review.

**Comment by atrope** [comment]
Do you know when  we can expect a minor update?

We are waiting for this to release an update.


Thanks!

**Comment by andrewlewis** [comment]
The above commit on `dev-v2` should fix the issue. I think the minor release that will pick this up is planned for early December (but we can't commit to a schedule I'm afraid).

If you need this urgently you could try making the equivalent one-line bug fix in `ImaAdsLoader` as from that commit. You need to depend on sources to do that though.
