### ISSUE TITLE
sending message to a Handler on a dead thread

### ISSUE THREAD

**Issue by randeeppr** [google/ExoPlayer#824]
Hi,

We are getting this exception when we stop a video(call release() method). What can be the cause?
How can we solve this?

W/MessageQueue( 2089): Handler (com.google.android.exoplayer.upstream.Loader$LoadTask) {430ae040} sending message to a Handler on a dead thread
W/MessageQueue( 2089): java.lang.RuntimeException: Handler (com.google.android.exoplayer.upstream.Loader$LoadTask) {430ae040} sending message to a Handler on a dead thread
W/MessageQueue( 2089):     at android.os.MessageQueue.enqueueMessage(MessageQueue.java:320)
W/MessageQueue( 2089):     at android.os.Handler.enqueueMessage(Handler.java:626)
W/MessageQueue( 2089):     at android.os.Handler.sendMessageAtTime(Handler.java:595)
W/MessageQueue( 2089):     at android.os.Handler.sendMessageDelayed(Handler.java:566)
W/MessageQueue( 2089):     at android.os.Handler.sendEmptyMessageDelayed(Handler.java:530)
W/MessageQueue( 2089):     at android.os.Handler.sendEmptyMessage(Handler.java:515)
W/MessageQueue( 2089):     at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:208)
W/MessageQueue( 2089):     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
W/MessageQueue( 2089):     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/MessageQueue( 2089):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/MessageQueue( 2089):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/MessageQueue( 2089):     at java.lang.Thread.run(Thread.java:841)
W/MessageQueue( 2089): Handler (com.google.android.exoplayer.upstream.Loader$LoadTask) {42050090} sending message to a Handler on a dead thread
W/MessageQueue( 2089): java.lang.RuntimeException: Handler (com.google.android.exoplayer.upstream.Loader$LoadTask) {42050090} sending message to a Handler on a dead thread
W/MessageQueue( 2089):     at android.os.MessageQueue.enqueueMessage(MessageQueue.java:320)
W/MessageQueue( 2089):     at android.os.Handler.enqueueMessage(Handler.java:626)
W/MessageQueue( 2089):     at android.os.Handler.sendMessageAtTime(Handler.java:595)
W/MessageQueue( 2089):     at android.os.Handler.sendMessageDelayed(Handler.java:566)
W/MessageQueue( 2089):     at android.os.Handler.sendEmptyMessageDelayed(Handler.java:530)
W/MessageQueue( 2089):     at android.os.Handler.sendEmptyMessage(Handler.java:515)
W/MessageQueue( 2089):     at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:208)
W/MessageQueue( 2089):     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
W/MessageQueue( 2089):     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/MessageQueue( 2089):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/MessageQueue( 2089):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/MessageQueue( 2089):     at java.lang.Thread.run(Thread.java:841)

Regards,
Randeep

**Comment by ojw28** [comment]
Please see #426 (it's a good idea to search existing issues before filing a new one, also!). Thanks!
