### ISSUE TITLE
Update ffmpeg extension for AGP 4.1

### ISSUE THREAD

**Issue by chhatrasal09** [google/ExoPlayer#8242]
### [REQUIRED] Upgrading the ndk for AGP 4.1 for ffmpeg extension
I have updated my Android Studio to lates version v4.1. To run this version of studio the recommended version for AGP is v4.1 which recommends ndk version of 21.1.6352462 and this repo has ndk version of 20.0.5594570
[https://developer.android.com/studio/projects/install-ndk#default-ndk-per-agp](https://developer.android.com/studio/projects/install-ndk#default-ndk-per-agp)

**Comment by icbaker** [comment]
AFAICT ExoPlayer doesn't specify an NDK version.

The closest we get is this part of the [ffmpeg extension README](https://github.com/google/ExoPlayer/blob/release-v2/extensions/ffmpeg/README.md#build-instructions-linux-macos):
>This build configuration has been tested on NDK r20.

I believe as a developer you should be free to use your choice of NDK version.
