### ISSUE TITLE
Slower transitioning in newer library versions

### ISSUE THREAD

**Issue by amirhasanovic** [google/ExoPlayer#8249]
### [REQUIRED] Searched documentation and issues
https://github.com/google/ExoPlayer/issues/2049
https://github.com/google/ExoPlayer/issues/7542
https://github.com/google/ExoPlayer/issues/4718

### [REQUIRED] Question
This question is in correlation with https://github.com/google/ExoPlayer/issues/7771. After successful adaptation of our app to have smooth transition between streams, we upgraded library to 2.12.0, here is where the issues started.
We have a P2P implemented, and our hls stream is loaded using that P2P lib url, we have api access to this lib where we monitor buffer health, play time and other channel data. Everything was fine till 2.11.7 version. All versions after this are not  working like it is in this version. P2P shows that the stream is being reset to the old stream before the switch even though we don't reset the stream anywhere in the app. And especially on the latest release we have audio stuck when we are switching channels. 
`E/EventLogger: audioTrackUnderrun [eventTime=258.52, mediaPos=17.17, window=0, period=0, 71552, 372, `1223]`
- this output is present in version 2.12.0, when switching channels, the player drags and every now and then this error shows up,
the stream starts lagging and there are audio issues
 Could it be that some changes made in versions after 2.11.7 could have affected this, and that's why we are getting this behavior?
### Link to test content
Can't provide content.

**Comment by icbaker** [comment]
>Everything was fine till 2.11.7 version. All versions after this are not working like it is in this version.

To confirm: It doesn't work as you expect with 2.11.8? The diff between 2.11.7 and 2.11.8 is [reasonably small](https://github.com/google/ExoPlayer/blob/release-v2/RELEASENOTES.md#2118-2020-08-25) (while the diff from 2.11.8 to 2.12.0 is huge), so this might help locate the cause of the behaviour.

Unfortunately without being able to reproduce what you're seeing it's impossible for us to debug this in detail - so there's not much we can do if you're unable to share a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) in a way that we can build locally.

**Comment by amirhasanovic** [comment]
The biggest problem is in 2.12.0, according to server information, the stream information is not the same as in the previous versions.
The way in which we set the stream in 2.11.7:
```
videoSource = new HlsMediaSource
                    .Factory(dataSourceFactory)
                    .setAllowChunklessPreparation(true)
                    .setLoadErrorHandlingPolicy(new CustomErrorPolicy())
                    .createMediaSource(Uri.parse(url));
player.prepare(videoSource);
player.setPlayWhenReady(true);
```
in 2.12.0:
```
videoSource = new HlsMediaSource
                    .Factory(dataSourceFactory)
                    .setAllowChunklessPreparation(true)
                    .setLoadErrorHandlingPolicy(new CustomErrorPolicy())
                    .createMediaSource(MediaItem.fromUri(Uri.parse(url)));
player.setMediaSource(videoSource);
player.prepare();
player.setPlayWhenReady(true);
```
I was just wandering if the library has changed the way it behaves with the hls streams that much, because the information we are getting is much different when switching streams.

**Comment by icbaker** [comment]
Without clear steps to reproduce the behaviour you're seeing, it's not possible for us to offer more help.

Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that demonstrates the problem in a way that we can build locally. 

This could be an Android Studio project on GitHub, or zipped up and sent to dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Please also update this issue to indicate you’ve done this.

There have been >2000 lines changed in the HLS module between 2.11.7 and 2.12.0 [1] - I'm afraid we don't have the capacity to try and guess which of these changes might be causing the issues you're seeing without being able to understand exactly the symptoms you're seeing, and how your app is interacting with ExoPlayer in detail.

[1]
```
$ git diff --stat r2.11.7 r2.12.0 -- */hls/*
 library/hls/README.md                                                                               |  17 +-
 library/hls/build.gradle                                                                            |  28 ++-
 library/hls/src/main/java/com/google/android/exoplayer2/source/hls/Aes128DataSource.java            |   1 +
 .../hls/src/main/java/com/google/android/exoplayer2/source/hls/BundledHlsMediaChunkExtractor.java   | 104 ++++++++++
 library/hls/src/main/java/com/google/android/exoplayer2/source/hls/DefaultHlsExtractorFactory.java  | 240 ++++++++---------------
 library/hls/src/main/java/com/google/android/exoplayer2/source/hls/HlsChunkSource.java              |  94 ++++++---
 library/hls/src/main/java/com/google/android/exoplayer2/source/hls/HlsExtractorFactory.java         |  38 +---
 library/hls/src/main/java/com/google/android/exoplayer2/source/hls/HlsMediaChunk.java               | 165 +++++++++-------
 library/hls/src/main/java/com/google/android/exoplayer2/source/hls/HlsMediaChunkExtractor.java      |  62 ++++++
 library/hls/src/main/java/com/google/android/exoplayer2/source/hls/HlsMediaPeriod.java              | 113 ++++++-----
 library/hls/src/main/java/com/google/android/exoplayer2/source/hls/HlsMediaSource.java              | 241 +++++++++++++----------
 library/hls/src/main/java/com/google/android/exoplayer2/source/hls/HlsSampleStreamWrapper.java      | 516 +++++++++++++++++++++++++++++++++++---------------
 library/hls/src/main/java/com/google/android/exoplayer2/source/hls/HlsTrackMetadataEntry.java       |  32 +++-
 .../src/main/java/com/google/android/exoplayer2/source/hls/UnexpectedSampleTimestampException.java  |  65 +++++++
 library/hls/src/main/java/com/google/android/exoplayer2/source/hls/WebvttExtractor.java             |  29 ++-
 library/hls/src/main/java/com/google/android/exoplayer2/source/hls/offline/HlsDownloader.java       | 120 ++++++++----
 .../src/main/java/com/google/android/exoplayer2/source/hls/playlist/DefaultHlsPlaylistTracker.java  | 228 ++++++++++++----------
 library/hls/src/main/java/com/google/android/exoplayer2/source/hls/playlist/HlsMasterPlaylist.java  |  11 +-
 library/hls/src/main/java/com/google/android/exoplayer2/source/hls/playlist/HlsMediaPlaylist.java   |  32 ++--
 library/hls/src/main/java/com/google/android/exoplayer2/source/hls/playlist/HlsPlaylistParser.java  | 239 +++++++++++------------
 library/hls/src/main/java/com/google/android/exoplayer2/source/hls/playlist/HlsPlaylistTracker.java |  16 +-
 .../hls/src/test/java/com/google/android/exoplayer2/source/hls/DefaultHlsExtractorFactoryTest.java  | 167 ++++++++++++++++
 .../hls/src/test/java/com/google/android/exoplayer2/source/hls/DefaultMediaSourceFactoryTest.java   | 101 ++++++++++
 library/hls/src/test/java/com/google/android/exoplayer2/source/hls/HlsMediaPeriodTest.java          | 102 ++++------
 library/hls/src/test/java/com/google/android/exoplayer2/source/hls/HlsMediaSourceTest.java          | 135 +++++++++++++
 library/hls/src/test/java/com/google/android/exoplayer2/source/hls/HlsTrackMetadataEntryTest.java   |  50 +++++
 library/hls/src/test/java/com/google/android/exoplayer2/source/hls/WebvttExtractorTest.java         |  39 +++-
 library/hls/src/test/java/com/google/android/exoplayer2/source/hls/offline/DownloadHelperTest.java  |  27 ++-
 library/hls/src/test/java/com/google/android/exoplayer2/source/hls/offline/HlsDownloadTestData.java |   9 +-
 library/hls/src/test/java/com/google/android/exoplayer2/source/hls/offline/HlsDownloaderTest.java   |  56 +++---
 .../test/java/com/google/android/exoplayer2/source/hls/playlist/HlsMasterPlaylistParserTest.java    | 105 ++++++----
 .../src/test/java/com/google/android/exoplayer2/source/hls/playlist/HlsMediaPlaylistParserTest.java |  81 +++++---
 32 files changed, 2159 insertions(+), 1104 deletions(-)
```
