### ISSUE TITLE
Wrong index used in VideoFormatSelectorUtil?

### ISSUE THREAD

**Issue by pakerfeldt** [google/ExoPlayer#825]
See my comment here: https://github.com/google/ExoPlayer/commit/b405d3d9b73d2854c5ae7f173755917807e13045

Seems like we're using the wrong index in the second pass filter.

**Comment by ojw28** [comment]
Yep, thanks!

**Comment by ojw28** [comment]
Out of interest, have you seen any bad behavior that you have been able to trace back to this, or did you just spot it browsing the code?

**Comment by pakerfeldt** [comment]
It was reported internally by one of my colleagues. I don't believe it was tied to any specific issue. She just happened to spot it in our code (we had a copy of VideoFormatSelectorUtil at the time).

**Comment by ojw28** [comment]
Ok, thanks!
