### ISSUE TITLE
MediaPeriodHolder causing memory leaks and OutOfMemory errors

### ISSUE THREAD

**Issue by jam-le** [google/ExoPlayer#8250]
### [REQUIRED] Issue description
Describe the issue in detail, including observed and expected behavior.

**Observed Behavior**
Some devices are experiencing fatal crashes due to OutOfMemory errors. Firebase crashlytics (crash reporting tool) implicates ExoPlayer and ProgressiveMediaPeriod to be the source of the issue.
![image](https://user-images.githubusercontent.com/6895708/99578162-67590b00-29aa-11eb-8e30-62193b4b5b37.png)

Though I cannot personally reproduce the crashes, Firebase is reporting ~5000 crashes relating to this.

**Expected Behavior**
No OOM crashes.

### [REQUIRED] Reproduction steps
Describe how the issue can be reproduced, ideally using the ExoPlayer demo app

I cannot personally reproduce the error, but doing a memory analysis via Android Profiler, there appears to be a ton of memory leaks involving MediaPeriodHolder.
![image](https://user-images.githubusercontent.com/6895708/99578273-9c655d80-29aa-11eb-92e6-1f42287c51ef.png)

The problem is, [the MediaSource documentation states that releasing the MediaPeriod should not be handled by the application code](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/source/MediaSource.html#releasePeriod-com.google.android.exoplayer2.source.MediaPeriod-). But it looks like a large source of memory leaks are caused by residual MediaPeriodHolder and ProgressiveMediaPeriod objects. A large number of these objects are not destroyed when a garbage collection is forced. I assume these objects are accumulating in memory as long as the ExoPlayer is alive and able to play videos, but I am not sure of the source. I suspect looping could related to or directly causing this issue.

### [REQUIRED] Link to test content
Provide a JSON snippet for the demo app’s media.exolist.json file, or a link to
media that reproduces the issue. If you don't wish to post it publicly, please
submit the issue, then email the link to dev.exoplayer@gmail.com using a subject
in the format "Issue #1234", where "#1234" should be replaced with your issue
number. Provide all the metadata we'd need to play the content like drm license
urls or similar. If the content is accessible only in certain countries or
regions, please say so.

Several different videos are playing in the ExoPlayer over time. Is there an issue with keeping the ExoPlayer open for long periods of time, playing it on loop until the next video is submitted? I can send a sample video if it is absolutely required.

### [REQUIRED] A full bug report captured from the device
Capture a full bug report using "adb bugreport". Output from "adb logcat" or a
log snippet is NOT sufficient. Please attach the captured bug report as a file.
If you don't wish to post it publicly, please submit the issue, then email the
bug report to dev.exoplayer@gmail.com using a subject in the format
"Issue #1234", where "#1234" should be replaced with your issue number.

I am struggling to post the bug report since I cannot personally reproduce the error and Firebase Crashlytics doesn't allow for an easy way to copy the entire stack trace. I hope that I can still get help. The Firebase Crash report looks like this:
```
Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 80 byte allocation with 1167000 free bytes and 1139KB until OOM, target footprint 268435456, growth limit 268435456; failed due to fragmentation (largest possible contiguous allocation 9961472 bytes)
       at android.content.Intent$1.createFromParcel(Intent.java:11181)
       at android.content.Intent$1.createFromParcel(Intent.java:11179)
       at android.app.IApplicationThread$Stub.onTransact(IApplicationThread.java:782)
       at android.os.Binder.execTransactInternal(Binder.java:1056)
       at android.os.Binder.execTransact(Binder.java:1029)
Loader:ProgressiveMediaPeriod
       at sun.misc.Unsafe.park(Unsafe.java)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2067)
       at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1092)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)
dummySurface
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:336)
       at android.os.Looper.loop(Looper.java:197)
       at android.os.HandlerThread.run(HandlerThread.java:67)
Loader:ProgressiveMediaPeriod
       at sun.misc.Unsafe.park(Unsafe.java)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2067)
       at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1092)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)

      ...
```
and the `Loader:ProgressiveMediaPeriod` error repeats many, many times throughout the stacktrace.

### [REQUIRED] Version of ExoPlayer being used
com.google.android.exoplayer:exoplayer:2.11.3 (I will upgrade soon, but looking at the release notes, I do not think any of the listed fixes will solve my current problem)

### [REQUIRED] Device(s) and version(s) of Android being used
Devices (include but not limited to): Galaxy Note10
Versions (include but not limited to): Android 10.0

**Comment by icbaker** [comment]
>doing a memory analysis via Android Profiler, there appears to be a ton of memory leaks involving MediaPeriodHolder.

Was this done on the ExoPlayer demo app, or your app?

>I assume these objects are accumulating in memory as long as the ExoPlayer is alive and able to play videos

It should be easy to confirm this hypothesis by seeing if the number of these objects increases over time - is that what you observe?

---------

The screenshot seems to show 6 allocated `ExoPlayerImplInternal` objects, which suggests there are 6 players being used - is that expected based on your setup?

There are also lots of objects with 88 allocations (`MediaPeriodHolder`, `ProgressiveMediaPeriod`, `SampleQueue`, `SampleDataQueue`, `TsExtractor`, `Ac4Extractor`, `ProgressiveMediaPeriod#ExtractorHolder`). How many `ProgressiveMediaSource` allocations are there? I can't see any in the screenshot but I assume there must be some. It might be helpful if you could attach a complete heap dump.

------

It's very difficult to debug issues like this via screenshots. If you believe there's a memory leak in the ExoPlayer library then it should be possible to reproduce the behaviour in the demo app - if you're able to do this, please provide us the repro instructions.

**Comment by jam-le** [comment]
Hi, thank you for your response.

I'll try building the feature into the ExoPlayer demo app and checking to see if I find the same issues. I'll need a bit of time to recreate my issue, but I'll follow up once I am able to.

**Comment by DeeptiMota** [comment]
Hi There,
I am finding similar issue in my app. It might be possible there is no issue in Exoplayer library but we might not using it correctly. So, could you please help us to solve our problem?

I have a grid of videos in my app and have to play random video in the grid, either on scroll or on item-click. 
Have created a single Exoplayer and PlayerView instance, which is being used for playing the video in the grid. Am I doing anything wrong?

**Comment by DeeptiMota** [comment]
Do you have any demo app which shows usage of exoplayer in recycler view or view-pager or any similar structure?

Otherwise, how can I show you my code, without making it public?

**Comment by DeeptiMota** [comment]
@icbaker Could you please help?

**Comment by icbaker** [comment]
@DeeptiMota you're probably best off filing a new issue. You'll need to provide enough info for us to be able to help you.

We ideally need to be able to reproduce the problematic behaviour you're seeing so that we can help. If that's not possible then a heap dump showing the problematic memory usage might be enough.

Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that demonstrates the problem in a way that we can build locally. This could be an Android Studio project on GitHub, or zipped up and sent to dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Please also update your issue to indicate you’ve done this.

> Do you have any demo app which shows usage of exoplayer in recycler view or view-pager or any similar structure?

We don't have a demo app for this, there's quite a lot of discussion of using ExoPlayer in RecyclerView in this issue tracker if you have a read through old issues.

> Have created a single Exoplayer and PlayerView instance, which is being used for playing the video in the grid. **Am I doing anything wrong?**

It's impossible to tell if you're doing something wrong with so little information. See comments above about needing to be able to reproduce the problems you're seeing.
