### ISSUE TITLE
AbstractMethodError

### ISSUE THREAD

**Issue by ShengjieGeng** [google/ExoPlayer#8254]
Hi，I don't know what's going on.
Please do me a favor,
thanks a lot. 
below is the log
```

1 com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.lambda$run$0$ExoPlayerImpl$PlaybackInfoUpdate(ExoPlayerImpl.java:804)
--
2 com.google.android.exoplayer2.-$$Lambda$ExoPlayerImpl$PlaybackInfoUpdate$N_S5kRfhaRTAkH28P5luFgKnFjQ.invokeListener(lambda)
3 com.google.android.exoplayer2.BasePlayer$ListenerHolder.invoke(BasePlayer.java:182)
4 com.google.android.exoplayer2.ExoPlayerImpl.invokeAll(ExoPlayerImpl.java:845)
5 com.google.android.exoplayer2.ExoPlayerImpl.access$000(ExoPlayerImpl.java:43)
6 com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.run(ExoPlayerImpl.java:802)
7 com.google.android.exoplayer2.ExoPlayerImpl.notifyListeners(ExoPlayerImpl.java:736)
8 com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo(ExoPlayerImpl.java:710)
9 com.google.android.exoplayer2.ExoPlayerImpl.handlePlaybackInfo(ExoPlayerImpl.java:652)
10 com.google.android.exoplayer2.ExoPlayerImpl.handleEvent(ExoPlayerImpl.java:595)
11 com.google.android.exoplayer2.ExoPlayerImpl$1.handleMessage(ExoPlayerImpl.java:127)
12 android.os.Handler.dispatchMessage(Handler.java:102)
13 android.os.Looper.loop(Looper.java:135)
14 android.app.ActivityThread.main(ActivityThread.java:5254)
15 java.lang.reflect.Method.invoke(Native Method)
16 java.lang.reflect.Method.invoke(Method.java:372)
17 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
18 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)


```

```
--------- beginning of main
--
111-17 18:45:03.946 1196 1196 E MtaSDK.CaughtExp: MTA has caught the following uncaught exception:
211-17 18:45:03.948 1196 1196 E MtaSDK.CaughtExp:
311-17 18:45:03.948 1196 1196 E MtaSDK.CaughtExp: java.lang.AbstractMethodError: abstract method "void com.google.android.exoplayer2.Player$EventListener.onTimelineChanged(com.google.android.exoplayer2.Timeline, int)"
411-17 18:45:03.948 1196 1196 E MtaSDK.CaughtExp: at com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.lambda$run$0$ExoPlayerImpl$PlaybackInfoUpdate(ExoPlayerImpl.java:804)
511-17 18:45:03.948 1196 1196 E MtaSDK.CaughtExp: at com.google.android.exoplayer2.-$$Lambda$ExoPlayerImpl$PlaybackInfoUpdate$N_S5kRfhaRTAkH28P5luFgKnFjQ.invokeListener(lambda)
611-17 18:45:03.948 1196 1196 E MtaSDK.CaughtExp: at com.google.android.exoplayer2.BasePlayer$ListenerHolder.invoke(BasePlayer.java:182)
711-17 18:45:03.948 1196 1196 E MtaSDK.CaughtExp: at com.google.android.exoplayer2.ExoPlayerImpl.invokeAll(ExoPlayerImpl.java:845)
811-17 18:45:03.948 1196 1196 E MtaSDK.CaughtExp: at com.google.android.exoplayer2.ExoPlayerImpl.access$000(ExoPlayerImpl.java:43)
911-17 18:45:03.948 1196 1196 E MtaSDK.CaughtExp: at com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.run(ExoPlayerImpl.java:802)
1011-17 18:45:03.948 1196 1196 E MtaSDK.CaughtExp: at com.google.android.exoplayer2.ExoPlayerImpl.notifyListeners(ExoPlayerImpl.java:736)
1111-17 18:45:03.948 1196 1196 E MtaSDK.CaughtExp: at com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo(ExoPlayerImpl.java:710)
1211-17 18:45:03.948 1196 1196 E MtaSDK.CaughtExp: at com.google.android.exoplayer2.ExoPlayerImpl.handlePlaybackInfo(ExoPlayerImpl.java:652)
1311-17 18:45:03.948 1196 1196 E MtaSDK.CaughtExp: at com.google.android.exoplayer2.ExoPlayerImpl.handleEvent(ExoPlayerImpl.java:595)
1411-17 18:45:03.948 1196 1196 E MtaSDK.CaughtExp: at com.google.android.exoplayer2.ExoPlayerImpl$1.handleMessage(ExoPlayerImpl.java:127)
1511-17 18:45:03.948 1196 1196 E MtaSDK.CaughtExp: at android.os.Handler.dispatchMessage(Handler.java:102)
1611-17 18:45:03.948 1196 1196 E MtaSDK.CaughtExp: at android.os.Looper.loop(Looper.java:135)
1711-17 18:45:03.948 1196 1196 E MtaSDK.CaughtExp: at android.app.ActivityThread.main(ActivityThread.java:5254)
1811-17 18:45:03.948 1196 1196 E MtaSDK.CaughtExp: at java.lang.reflect.Method.invoke(Native Method)
1911-17 18:45:03.948 1196 1196 E MtaSDK.CaughtExp: at java.lang.reflect.Method.invoke(Method.java:372)
2011-17 18:45:03.948 1196 1196 E MtaSDK.CaughtExp: at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
2111-17 18:45:03.948 1196 1196 E MtaSDK.CaughtExp: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
2211-17 18:45:03.948 1196 1196 E MtaSDK.CaughtExp: App uncaught exception end.


```

_Originally posted by @ShengjieGeng in https://github.com/google/ExoPlayer/issues/8227#issuecomment-730099202_

**Comment by icbaker** [comment]
See my [response](https://github.com/google/ExoPlayer/issues/8227#issuecomment-727854676) on #8227:

> Errors like this are generally related to Java 8 support (the method it's complaining about is marked `default` on the ~`DrmSessionManager`~`Player.EventListener` interface, which is a language feature added in Java 8).
> 
> There's a [comment](https://github.com/google/ExoPlayer/issues/6801#issuecomment-574089568) here suggesting to try `android.enableDexingArtifactTransform=false` - did you try that?
> 
> If you'd like us to investigate further please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that demonstrates the problem in a way that we can build locally.
> 
> This could be an Android Studio project on GitHub, or zipped up and sent to [dev.exoplayer@gmail.com](mailto:dev.exoplayer@gmail.com) using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Please also update this issue to indicate you’ve done this.

**Comment by ShengjieGeng** [comment]
> See my [response](https://github.com/google/ExoPlayer/issues/8227#issuecomment-727854676) on #8227:
> 
> > Errors like this are generally related to Java 8 support (the method it's complaining about is marked `default` on the ~`DrmSessionManager`~`Player.EventListener` interface, which is a language feature added in Java 8).
> > There's a [comment](https://github.com/google/ExoPlayer/issues/6801#issuecomment-574089568) here suggesting to try `android.enableDexingArtifactTransform=false` - did you try that?
> > If you'd like us to investigate further please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that demonstrates the problem in a way that we can build locally.
> > This could be an Android Studio project on GitHub, or zipped up and sent to [dev.exoplayer@gmail.com](mailto:dev.exoplayer@gmail.com) using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Please also update this issue to indicate you’ve done this.

Actually，it's occasionally. Even just appeared once during the last one year.

**Comment by icbaker** [comment]
For a given APK and android version, I would expect this error to either permanently occur or never - I'd be surprised if with no other changes, sometimes the `ExoPlayerImpl.handlePlaybackInfo()` method can be invoked successfully and other times it fails as above.

If you want us to investigate further we need more information.

Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that demonstrates the problem in a way that we can build locally. 

This could be an Android Studio project on GitHub, or zipped up and sent to dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Please also update this issue to indicate you’ve done this.

**Comment by ShengjieGeng** [comment]
> Hey @ShengjieGeng. We need more information to resolve this issue but there hasn't been an update in 14 weekdays. I'm marking the issue as stale and if there are no new updates in the next 7 days I will close it automatically.
> 
> If you have more information that will help us get to the bottom of this, just add a comment!

Sorry，I cannot give you the sample，because the App runs on special device and the special scene：
![image](https://user-images.githubusercontent.com/18364968/101855016-b35c3180-3b9d-11eb-97d2-a20f58d4d55f.png)

**Comment by icbaker** [comment]
There still isn't enough info here for us to investigate.

**Comment by shiv-u** [comment]
Hi @icbaker , I'm also facing the similar issue if I use the aar file from my private maven repo but it won't occur if I use local AAR file (implementation file("/path/to/aar").
Gradle files :
[app_gradlefile.txt](https://github.com/google/ExoPlayer/files/5868638/app_gradlefile.txt)
[library_gradlefile.txt](https://github.com/google/ExoPlayer/files/5868640/library_gradlefile.txt)
[project_gradlefile.txt](https://github.com/google/ExoPlayer/files/5868641/project_gradlefile.txt)

Crashlog:
[crashlog.txt](https://github.com/google/ExoPlayer/files/5868639/crashlog.txt)

My Android Gradle Plugin Version is `3.6.3` and Gradle version is `5.6.4` .
If I use ` android.enableDexingArtifactTransform=false` in `gradle.properties` there are no issues.

**Comment by icbaker** [comment]
@shiv-u that sounds to me like the same situation addressed in this comment: https://github.com/google/ExoPlayer/issues/6801#issuecomment-579164194

If you believe it's different to that issue, please file a new issue including a **complete** [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that demonstrates the problem in a way that we can build locally (the files you've attached are interesting, but they don't allow us to immediately reproduce the problem).

This could be an Android Studio project on GitHub, or zipped up and sent to dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Please also update this issue to indicate you’ve done this.

**Comment by shiv-u** [comment]
Thanks for such a quick response @icbaker , so including dependencies in the pom file will resolve this issue ?

**Comment by shiv-u** [comment]
Thanks, it worked !!! This is the groovy block I used 

```

 publishing {
        publications {
            aar(MavenPublication) {
                groupId libraryGroupId
                //You can either define these here or get them from project conf elsewhere
                artifactId libraryArtifactId
                version libraryVersion
                artifact "$buildDir/outputs/aar/release.aar"
                //aar artifact you want to publish

                //generate pom nodes for dependencies
                pom.withXml {
                    def dependenciesNode = asNode().appendNode('dependencies')
                    configurations.implementation.allDependencies.each { dependency ->
                        def dependencyNode = dependenciesNode.appendNode('dependency')
                        dependencyNode.appendNode('groupId', dependency.group)
                        dependencyNode.appendNode('artifactId', dependency.name)
                        dependencyNode.appendNode('version', dependency.version)
                    }
                }
            }
        }

        artifactory {
            contextUrl = ''
            publish {
                repository {
                    repoKey = 'repo'

                    username = username
                    password = password
                }
                defaults {
                    publications('aar')
                    publishArtifacts = true

                    properties = ['qa.level': 'basic', 'q.os': 'android', 'dev.team': 'core']
                    publishPom = true
                }
            }
        }
    }
```
