### ISSUE TITLE
Invalid seekTo() method

### ISSUE THREAD

**Issue by ShengjieGeng** [google/ExoPlayer#8256]
Hi, I'm using the multi-item MediaSource, 
but the method  `simpleExoPlayer.seekTo(position);` is invalid.
 ` simpleExoPlayer.setMediaSource(concatenatingMediaSource,position);`   is invalid too.
it always starts playing from the position 0 ms.
below is the codes
```
if (concatenatingMediaSource == null) {
    concatenatingMediaSource = new ConcatenatingMediaSource();
} else {
    concatenatingMediaSource.clear();
}
if (progressiveMediaSource == null)
    progressiveMediaSource = new ProgressiveMediaSource.Factory(getFactory());
for (String path : paths) {
    LogUtil.d(TAG, "play path:" + path);
    ProgressiveMediaSource tempMedia = progressiveMediaSource.createMediaSource(MediaItem.fromUri(getUri(path)));
    concatenatingMediaSource.addMediaSource(tempMedia);
}
simpleExoPlayer.setRepeatMode(loop ? Player.REPEAT_MODE_ALL : Player.REPEAT_MODE_OFF);
simpleExoPlayer.setMediaSource(concatenatingMediaSource,position);
simpleExoPlayer.setPlayWhenReady(true);
simpleExoPlayer.prepare();
```
PS: the first audio's length is less than the postion seeked.

Did I use the simpleExoPlayer correctly? 
please help，thanks a lot.

**Comment by icbaker** [comment]
This is likely happening because ExoPlayer doesn't support seeking in the media you're using: 
https://exoplayer.dev/troubleshooting.html#why-are-some-media-files-not-seekable

When calling `SimpleExoPlayer.seekTo()` on non-seekable media, the expected behaviour is to restart playback from the beginning (as you observe).
 
To avoid accidentally calling `seekTo()` when playing non-seekable media, you can use `Player#isCurrentWindowSeekable()`, and only call `seekTo()` if this returns true.

**Comment by ShengjieGeng** [comment]
> This is likely happening because ExoPlayer doesn't support seeking in the media you're using:
> https://exoplayer.dev/troubleshooting.html#why-are-some-media-files-not-seekable
> 
> When calling `SimpleExoPlayer.seekTo()` on non-seekable media, the expected behaviour is to restart playback from the beginning (as you observe).
> 
> To avoid accidentally calling `seekTo()` when playing non-seekable media, you can use `Player#isCurrentWindowSeekable()`, and only call `seekTo()` if this returns true.

Got it.
But，the version `'com.google.android.exoplayer:exoplayer-core:2.11.3'` works fine. And when calling `SimpleExoPlayer.seekTo(position)` , the callback: 
```
@Override
    public void onPlayerStateChanged(boolean playWhenReady, int playbackState) {
}
```
the state Player.STATE_READY and Player.STATE_BUFFERING will receive several times, which is not what the App wants.

Anyway,I will try the latest version of exoplayer-core again.
thanks.
