### ISSUE TITLE
How to add user agent to Android exoplayer

### ISSUE THREAD

**Issue by binbinyYang** [google/ExoPlayer#8267]
How to add user agent to Android exoplayer？please tell me

**Comment by AquilesCanta** [comment]
You need to pass it to the DataSource when you are creating it. For example, if you are using a [DefaultDataSourceFactory](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/upstream/DefaultDataSourceFactory.html#DefaultDataSourceFactory-android.content.Context-java.lang.String-), you would use a constructor that takes a `userAgent` string. The ExoPlayer demo app creates the DataSource factory [here](https://github.com/google/ExoPlayer/blob/59b34ede6165d029d86a677fea73a5dd0dd55c74/demos/main/src/main/java/com/google/android/exoplayer2/demo/DemoUtil.java#L93).
