### ISSUE TITLE
TX3G Subtitles not showing in Exoplayer

### ISSUE THREAD

**Issue by AliZgheib** [google/ExoPlayer#8271]
Hello everyone,

**Introduction:**
I've been trying to implement exoplayer in a project of mine. The media that im trying to load in the players has different tracks embedded to it, such as audio tracks (English and Portuguese), text tracks (English and Portuguese).

**Issue:**
I was able to listen/read the audio/subtitles in the VLC player however, when I tried to do the same in exoplayer, I was able to change between the audio tracks ( it worked) however, the subtitles options didnt show up in the player ( and using the none/default options didn't do anything either).
After submitting an issue to this repo describing this problem [Link to the issue](https://github.com/google/ExoPlayer/issues/8260). I received a response saying the 2 text tracks embedded to the media are of 2 different formats ( Vobsub , tx3g), and that vobsub format is not supported by exoplayer.

So my issue is, why exoplayer is not showing the tx3g format subtitles even though its one of the supported formats?
Can someone look at the media link please and provide me with any feedback?

Thank you a lot in advance!

**Link to the media:**
[H265 media](http://lebgid.com/file_mp4.mp4?v=2)

 **Additional:**
![Capture](https://user-images.githubusercontent.com/46545733/100000235-fb234080-2dc9-11eb-9f0d-90eaf2b76a60.PNG)

**Comment by icbaker** [comment]
I looked at the file you provided in [MP4Box.js](https://gpac.github.io/mp4box.js/test/filereader.html).

The `trak` box with `id=5` (the tx3g one) has a `hdlr` box with `handler=text`. We treat this as a text track:
https://github.com/google/ExoPlayer/blob/59b34ede6165d029d86a677fea73a5dd0dd55c74/library/extractor/src/main/java/com/google/android/exoplayer2/extractor/mp4/AtomParsers.java#L794-L795

However the `stsd` box contains a box with `type=text`. This isn't one of the subtitle types that we detect when parsing `stsd` boxes:
https://github.com/google/ExoPlayer/blob/59b34ede6165d029d86a677fea73a5dd0dd55c74/library/extractor/src/main/java/com/google/android/exoplayer2/extractor/mp4/AtomParsers.java#L892-L896

I changed `AtomParsers` in two places: The `if` above to treat it as a text track and also inside `parseTextSampleEntry()` to assume `text` is `tx3g`:
https://github.com/google/ExoPlayer/blob/59b34ede6165d029d86a677fea73a5dd0dd55c74/library/extractor/src/main/java/com/google/android/exoplayer2/extractor/mp4/AtomParsers.java#L928

Then the track appears in the track selector of the demo app, and renders "Chapter 1" semi-permanently (it eventually changes to "Chapter 2") - same behaviour as VLC.

@kim-vde Do you know if a) `type=text` is valid for a `stsd` box? b) It's reasonable to assume this contains `tx3g`? Or is this media not quite structured correctly? (note I noted a different weirdness about this same media in https://github.com/google/ExoPlayer/issues/8260#issuecomment-733051270)

**Comment by kim-vde** [comment]
I wouldn't add support for type `text` in ExoPlayer because this is the only issue reporting this (as far as I am aware of), I couldn't find anything about this type (in [here](https://cconcolato.github.io/mp4ra/codecs.html) for example) and because there is no apparent link between type `text` and `tx3g`.

Do not hesitate to open another issue if you find information about this type (e.g. other issues, specifications).
