### ISSUE TITLE
Buggy extra controls of Styled player on Android 5.0

### ISSUE THREAD

**Issue by moneytoo** [google/ExoPlayer#8272]
### [REQUIRED] Issue description
The extra controls of the StyledPlayerView do not work the same on Android 5.0 as they work for example on devices running Android 10 (or even Android 6). Opened overflow menu cannot be closed when tapping outside. Selecting the Audio action without loaded media makes the interface unresponsive (this works on higher Android versions just fine).

### [REQUIRED] Reproduction steps
Demo app: https://github.com/moneytoo/ExoPlayerDemo
Steps / problems in action: https://youtu.be/Hsb8lWyceTE

### [REQUIRED] Link to test content
N/A (can be repro without media)

### [REQUIRED] A full bug report captured from the device
[bugreport.zip](https://github.com/google/ExoPlayer/files/5585814/bugreport.zip)

### [REQUIRED] Version of ExoPlayer being used
``2.12.1``

### [REQUIRED] Device(s) and version(s) of Android being used
Both Android 5.0 emulator and real Android 5.0 device: Samsung Galaxy S5 (Model: SM-G900F, Build: LRX21T.G900FXXS1BPE3)

**Comment by ojw28** [comment]
Thanks for reporting this [Internal ref: b/173997207].

**Comment by ojw28** [comment]
Pretty obscure, but it seems this can be fixed by setting a transparent background on the popup, as per:

https://stackoverflow.com/questions/12232724/popupwindow-dismiss-when-clicked-outside
