### ISSUE TITLE
Crash of Android low version SIGSEGV(SEGV_MAPERR)

### ISSUE THREAD

**Issue by junchenChow** [google/ExoPlayer#8275]
### [REQUIRED] Issue description

```
1 #00 pc 00017352 /system/lib/libmedia_jni.so (_ZNK7android11JMediaCodec27createByteBufferFromABufferEP7_JNIEnvbbRKNS_2spINS_7ABufferEEEPP8_jobject+25) [armeabi-v8::f20b230ba9a385365f9e591750559b48]
--
2 #01 pc 0001774b /system/lib/libmedia_jni.so (_ZNK7android11JMediaCodec9getBufferEP7_JNIEnvbjPP8_jobject+54) [armeabi-v8::f20b230ba9a385365f9e591750559b48]
3 #02 pc 00018a79 /system/lib/libmedia_jni.so [armeabi-v8::f20b230ba9a385365f9e591750559b48]
4 #03 pc 0079f007 /data/dalvik-cache/arm/system@framework@boot.oat [armeabi::14af9236f5c95ef4a8efa18992756d13]
5 java:
6 android.media.MediaCodec.getOutputBuffer(MediaCodec.java:1497)
7 com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.getOutputBuffer(MediaCodecRenderer.java:1008)
8 com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1547)
9 com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:718)
10 com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:599)
11 com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:329)
12 android.os.Handler.dispatchMessage(Handler.java:107)
13 android.os.Looper.loop(Looper.java:224)
14 android.os.HandlerThread.run(HandlerThread.java:61)
```

### [REQUIRED] Reproduction steps
Just play the video in the list normally, there is no special operation, it is easier to appear under 23 24 api.

### [REQUIRED] Link to test content
N/A (can be repro without media)

### [REQUIRED] A full bug report captured from the device
[crash_reporting_text.zip](https://github.com/google/ExoPlayer/files/5589580/crash_reporting_text.zip)

### [REQUIRED] Version of ExoPlayer being used
> 2.11.3

### [REQUIRED] Device(s) and version(s) of Android being used
![screenshot_20201124194136](https://user-images.githubusercontent.com/13553319/100089780-320e5a80-2e8d-11eb-98bd-cb38aa984865.png)

**Comment by AquilesCanta** [comment]
> Just play the video in the list normally, there is no special operation, it is easier to appear under 23 24 api.

Which list are you referring to?

> Device(s) and version(s) of Android being used

Have you seen it occur in newer APIs?

My current impression is that this could be an issue which affected certain devices, but that has been fixed on newer versions by the device manufacturers. If this assessment is right, there's not much on the ExoPlayer side to do. If we contact the device manufacturers they'll probably say to us "this is something we've fixed on version xyz". Can you clarify how the ExoPlayer team can help with this?

**Comment by junchenChow** [comment]
**Thank you for your reply.**

> Which list are you referring to?

The list in my app data, most of them are MP4 files.

> Have you seen it occur in newer APIs?

 I think you are right with a high probability, I did not find this problem in the newer APIs. The bug statistics only has this problem on the 23-24 version. I also have this problem with the latest exoplayer version, but this problem is not found on the Android version above 24.

 I thought exoplayer was compatible with older versions.
For example, Android media player doesn't seem to have this problem.

**Comment by AquilesCanta** [comment]
> For example, Android media player doesn't seem to have this problem.

In general, MediaPlayer being able to play something that ExoPlayer is not is able to play is a good starting point to fix the issue. In this specific case, not so much. Device manufacturers are able to modify the MediaPlayer implementation. It's possible that they know some quirk/bug in their codecs -that we don't- which they work around in their media player implementation. These quirks/bugs were eventually fixed (as per API level issue occurrence) so we find ourselves trying to reverse engineer the codecs of devices made by another company on old API versions. It's not a good position to be in.

If you are able to narrow down what ExoPlayer is doing wrong, then we can take it from there. Otherwise, I don't see actionable items to pick up here, unfortunately. My advise would be trying to contact the devices' manufacturer in case they might help with the diagnosis.

**Comment by TmRobust** [comment]
I have same crash

**Comment by junchenChow** [comment]
Sorry, there have been a lot of things recently, and I did not follow this reply. 
Because it is a matter of online statistics, it is impossible to directly contact the user in question to provide equipment.
I can only judge by the version for the time being, the version <=24 will use mediaplayer to solve the problem.

Sorry for not providing you with more information, this problem can be closed.
