### ISSUE TITLE
Cant play http streams 

### ISSUE THREAD

**Issue by Andreeiva** [google/ExoPlayer#8278]
I noticed I cant play streams with http formats such as this 
http://1111296894.rsc.cdn77.org/ls-54548-1/tracks-v1a1/mono.m3u8
but i can play streams with secured format like this
https://content.uplynk.com/channel/ff809e6d9ec34109abfb333f0d4444b5.m3u8

**Comment by AquilesCanta** [comment]
Both of the provided media streams play correctly in the demo app. With the given information it's impossible to know what you are experiencing. Please try playing your media in the ExoPlayer demo app and, if you run into issues, file a new github issue (type "bug") including all the information requested in the issue template available in the form. If you don't run into issues, this is probably an application issue which is not something we can assist with.

**Comment by ojw28** [comment]
You probably need to add `android:usesCleartextTraffic="true"` to your manifest. Please see the [first troubleshooting item on this page](https://exoplayer.dev/troubleshooting.html#fixing-cleartext-http-traffic-not-permitted-errors).
