### ISSUE TITLE
default track selection according to internet

### ISSUE THREAD

**Issue by deepaksmindiii** [google/ExoPlayer#8285]
How we can implement default track selection according to internet speed?
If we have trackselectiondialog and if i want to select 1080p and my internet speed is slow then it will switch on default pixel track according to internet speed.
please explain it step by step.

**Comment by AquilesCanta** [comment]
ExoPlayer does automatic track selection for you if you play a piece of adaptive media, like DASH or HLS. There's nothing you need to do. I don't understand the trackselectiondialog part, though. Perhaps you can clarify?

**Comment by deepaksmindiii** [comment]
Which method is called when exoplayer does automatic track selection, i mean how we notify on which pixel exoplayer change the track?

**Comment by AquilesCanta** [comment]
Have a look at [`Player.getVideoComponent().addVideoListener(yourVideoListener)`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/Player.VideoComponent.html). [VideoListener](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/video/VideoListener.html) should get an [`onVideoSizeChanged`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/video/VideoListener.html#onVideoSizeChanged-int-int-int-float-) every time the video size changes.

**Comment by deepaksmindiii** [comment]
Thankyou for commenting
