### ISSUE TITLE
play offline encryption hls video loading 3-5 seconds

### ISSUE THREAD

**Issue by ChrisChing24** [google/ExoPlayer#8288]
hello,I use exoplayer to play downloaded offline video,when i seek the position,the video buffering about 3-5 seconds.
how to reduce the buffering time?
exoplayer version:2.12.0
look forward to your reply.thanks

**Comment by AquilesCanta** [comment]
Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md). If you're unable to share bug reports or test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Please also update this issue to indicate you’ve done this.
