### ISSUE TITLE
Timestamp Map read is missing from WebVttParser

### ISSUE THREAD

**Issue by ferrytanu** [google/ExoPlayer#829]
Any reason why X-TIMESTAMP-MAP read get removed from WebVttParser?
https://github.com/google/ExoPlayer/commit/02c7525ff7d98b861d45aa32741611df6a339a89#diff-877f2292bc541a8abc6e4748532dbcf4L143

**Comment by ojw28** [comment]
We don't support WebVTT for HLS playbacks yet (see #151), which is the use case for which X-TIMESTAMP-MAP is actually intended to be used. It was previously being misused for propagating timestamp offsets for WebVTT in DASH. We will of course bring it back once we implement #151.
