### ISSUE TITLE
RequestProperty "Referer" not working with CronetDataSourceFactory

### ISSUE THREAD

**Issue by menscikov** [google/ExoPlayer#8292]
**Issue description**
If i set "Referer" header using `new DefaultHttpDataSourceFactory()`, then everything works fine.
But if i set "Referer" using `new CronetDataSourceFactory()`, it's not working.

I'm setting "Referer" header with `getDefaultRequestProperties().set()`.

**Reproduction steps**
1. Open **demo** app in Android Studio;
2. Find **DemoUtil.java** class and go to the **getHttpDataSourceFactory** method;
3. Add this code:
 `httpDataSourceFactory.getDefaultRequestProperties().set("Referer", "https://www.dailymotion.com");`

after
```
httpDataSourceFactory =
          new CronetDataSourceFactory(cronetEngineWrapper, Executors.newSingleThreadExecutor());
```
4. Open the url provided below;
5. ExoPlayer will throw an exception with 403 code;
6.  Replace:
```
httpDataSourceFactory =
          new CronetDataSourceFactory(cronetEngineWrapper, Executors.newSingleThreadExecutor());
```

with

`httpDataSourceFactory = new DefaultHttpDataSourceFactory();`
7. Open the url again. Now stream is playing.

**Link to test content**
https://fvtv.mywire.org/playlist/c6pxxm7rgq-maywremf1e.m3u8

P.S. I found this url in the Internet, so i don't know how long it will be alive.

**Version of ExoPlayer being used**
2.12.1

**Device(s) and version(s) of Android being used**
Android Emulator, Android 9.0 x86

**Comment by christosts** [comment]
Update: I can verify this happens with ExoPlayer 2.12.1. Although the ExoPlayer sets the header, it seems that specifically the "Referer" header is not transmitted, while other custom headers are transmitted. I will need to investigate further, it seems that there is something happening later in the software stack.

**Comment by christosts** [comment]
this seems to be related to cronet and not ExoPlayer directly [internal ref 174837576]

**Comment by christosts** [comment]
The cronet team submitted a fix for this, so I'll close this issue.
https://chromium-review.googlesource.com/c/chromium/src/+/2879998

Regarding when the fix will be available to ExoPlayer: it depends on how the player picks cronet at runtime. In cases where cronet is bunded with the player, the fix should be available when the player is built with a cronet version that has the fix. However, when the player picks cronet from the platform, this is dependent on platform updates and not on ExoPlayer.

**Comment by menscikov** [comment]
@christosts 

Thank you for writing about the fix. But they made a mistake. They wrote header name as "Refere", without "r", that's why it's not working anyway.

`
public void testCustomReferer() throws Exception {
TestUrlRequestCallback callback = new TestUrlRequestCallback();
String refererName = "Refere";
String refererValue = "Referer-Value";
UrlRequest.Builder builder = mTestFramework.mCronetEngine.newUrlRequestBuilder(
NativeTestServer.getEchoHeaderURL(refererName), callback, callback.getExecutor());
builder.addHeader(refererName, refererValue);
builder.build().start();
callback.blockForDone();
assertEquals(200, callback.mResponseInfo.getHttpStatusCode());
assertEquals(refererValue, callback.mResponseAsString);
}
`

**Comment by icbaker** [comment]
Good spot - I've commented on the commit pointing that out.

**Comment by Danstahrg** [comment]
The typo was fixed in https://crrev.com/c/2887329.

**Comment by menscikov** [comment]
Hello again,

If i understood correctly, latest cronet-embedded library version is very old (2019 year), and according to this message, they no longer provide updates (https://groups.google.com/a/chromium.org/g/net-dev/c/RdMsMNLwSDw).
I have to use embedded version because Google Play Services are not available on all Android devices.
Could you tell me please where to get the latest version and how to use it with ExoPlayer?

**Comment by ojw28** [comment]
@menscikov - Thanks for bringing this to our attention. I've filed https://github.com/google/ExoPlayer/issues/9085 to track this. As noted on that issue, it seems newer versions are available as binaries hosted on Google Cloud Storage. If `cronet-embedded` isn't going to receive future updates, then we'll need to figure out how to use those directly and update our instructions (in the meantime, you may be able to figure out how to do this yourself). Please follow https://github.com/google/ExoPlayer/issues/9085 for future updates.

**Comment by menscikov** [comment]
@ojw28 - Thank you very much.

Actually i'm using Cronet at this moment only because some of my users can't watch videos on Wi-Fi connection with default ExoPlayer HttpDataSource and also with ExoPlayer OkHttp extension. On mobile connection it is working fine.

When i changed it to CronetDataSource, videos started to play without any problems on Wi-Fi and mobile connection for these users.
The strangest thing is that these videos play without problems for me.
