### ISSUE TITLE
The position of getcurrentposition after seekto of HLS resource is not accurate

### ISSUE THREAD

**Issue by czeall** [google/ExoPlayer#8296]
### [REQUIRED] Issue description
Recently, I have been working on time point related requirements,After the HLS resource seekto, the getcurrentposition location is not accurate，If the seek operation is not performed, the getcurrentposition position position is obtained normally。

I want to know how to accurately get the current playback position after the seek operation when playing HLS type resources.

### [REQUIRED] Reproduction steps
Get getcurrentposition after the HLS type resource seek operation
Has been setSeekParameters(SeekParameters.EXACT);

### [REQUIRED] Link to test content
Internal resources, external network cannot access

### [REQUIRED] A full bug report captured from the device
none

### [REQUIRED] Version of ExoPlayer being used
2.11.1

### [REQUIRED] Device(s) and version(s) of Android being used
android 10, api version 28

**Comment by czeall** [comment]
Premium Processing

**Comment by czeall** [comment]
In addition, after the seek operation of playing HLS resources, subtitles will not be consistent with video playback

**Comment by czeall** [comment]
There may be an interval error of three to four seconds between the current playback position given by getcurrentposition and the actual playback position of the video after seek operation

**Comment by czeall** [comment]
#EXTM3U
#EXT-X-ALLOW-CACHE:YES
#EXT-X-VERSION:3
#EXT-X-KEY:METHOD=AES-128,URI="key.txt",IV=0xe8513fff57d996636154d5dd14855127
#EXT-X-TARGETDURATION:10
#EXTINF:9.92,"417376"
2d5baeae9cb36adce422f50aaa75be33-000.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"397072"
2d5baeae9cb36adce422f50aaa75be33-001.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"395376"
2d5baeae9cb36adce422f50aaa75be33-002.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"388048"
2d5baeae9cb36adce422f50aaa75be33-003.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"393488"
2d5baeae9cb36adce422f50aaa75be33-004.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"428272"
2d5baeae9cb36adce422f50aaa75be33-005.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"375072"
2d5baeae9cb36adce422f50aaa75be33-006.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"374880"
2d5baeae9cb36adce422f50aaa75be33-007.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"392560"
2d5baeae9cb36adce422f50aaa75be33-008.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"397632"
2d5baeae9cb36adce422f50aaa75be33-009.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"371872"
2d5baeae9cb36adce422f50aaa75be33-010.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"374320"
2d5baeae9cb36adce422f50aaa75be33-011.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"380896"
2d5baeae9cb36adce422f50aaa75be33-012.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"375264"
2d5baeae9cb36adce422f50aaa75be33-013.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"396688"
2d5baeae9cb36adce422f50aaa75be33-014.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"429584"
2d5baeae9cb36adce422f50aaa75be33-015.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"387472"
2d5baeae9cb36adce422f50aaa75be33-016.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"368864"
2d5baeae9cb36adce422f50aaa75be33-017.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"384656"
2d5baeae9cb36adce422f50aaa75be33-018.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"406656"
2d5baeae9cb36adce422f50aaa75be33-019.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"399328"
2d5baeae9cb36adce422f50aaa75be33-020.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"376192"
2d5baeae9cb36adce422f50aaa75be33-021.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"335776"
2d5baeae9cb36adce422f50aaa75be33-022.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"400448"
2d5baeae9cb36adce422f50aaa75be33-023.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"431840"
2d5baeae9cb36adce422f50aaa75be33-024.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"360224"
2d5baeae9cb36adce422f50aaa75be33-025.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"392560"
2d5baeae9cb36adce422f50aaa75be33-026.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"386160"
2d5baeae9cb36adce422f50aaa75be33-027.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"400080"
2d5baeae9cb36adce422f50aaa75be33-028.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"396496"
2d5baeae9cb36adce422f50aaa75be33-029.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"424512"
2d5baeae9cb36adce422f50aaa75be33-030.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"394992"
2d5baeae9cb36adce422f50aaa75be33-031.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"415296"
2d5baeae9cb36adce422f50aaa75be33-032.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"385040"
2d5baeae9cb36adce422f50aaa75be33-033.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"437488"
2d5baeae9cb36adce422f50aaa75be33-034.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"438432"
2d5baeae9cb36adce422f50aaa75be33-035.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"454592"
2d5baeae9cb36adce422f50aaa75be33-036.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"482800"
2d5baeae9cb36adce422f50aaa75be33-037.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"433344"
2d5baeae9cb36adce422f50aaa75be33-038.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"476400"
2d5baeae9cb36adce422f50aaa75be33-039.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"451776"
2d5baeae9cb36adce422f50aaa75be33-040.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"445952"
2d5baeae9cb36adce422f50aaa75be33-041.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"424512"
2d5baeae9cb36adce422f50aaa75be33-042.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"434848"
2d5baeae9cb36adce422f50aaa75be33-043.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"475088"
2d5baeae9cb36adce422f50aaa75be33-044.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"437296"
2d5baeae9cb36adce422f50aaa75be33-045.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"382784"
2d5baeae9cb36adce422f50aaa75be33-046.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"370928"
2d5baeae9cb36adce422f50aaa75be33-047.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"375824"
2d5baeae9cb36adce422f50aaa75be33-048.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"437856"
2d5baeae9cb36adce422f50aaa75be33-049.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"422256"
2d5baeae9cb36adce422f50aaa75be33-050.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"462496"
2d5baeae9cb36adce422f50aaa75be33-051.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"397632"
2d5baeae9cb36adce422f50aaa75be33-052.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"439744"
2d5baeae9cb36adce422f50aaa75be33-053.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"437680"
2d5baeae9cb36adce422f50aaa75be33-054.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"417936"
2d5baeae9cb36adce422f50aaa75be33-055.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"455728"
2d5baeae9cb36adce422f50aaa75be33-056.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"383712"
2d5baeae9cb36adce422f50aaa75be33-057.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"409856"
2d5baeae9cb36adce422f50aaa75be33-058.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"434848"
2d5baeae9cb36adce422f50aaa75be33-059.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"394240"
2d5baeae9cb36adce422f50aaa75be33-060.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"381280"
2d5baeae9cb36adce422f50aaa75be33-061.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"438608"
2d5baeae9cb36adce422f50aaa75be33-062.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"433728"
2d5baeae9cb36adce422f50aaa75be33-063.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"402512"
2d5baeae9cb36adce422f50aaa75be33-064.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"386720"
2d5baeae9cb36adce422f50aaa75be33-065.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"388048"
2d5baeae9cb36adce422f50aaa75be33-066.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"402512"
2d5baeae9cb36adce422f50aaa75be33-067.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"430720"
2d5baeae9cb36adce422f50aaa75be33-068.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"420944"
2d5baeae9cb36adce422f50aaa75be33-069.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"425456"
2d5baeae9cb36adce422f50aaa75be33-070.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"414368"
2d5baeae9cb36adce422f50aaa75be33-071.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"401008"
2d5baeae9cb36adce422f50aaa75be33-072.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"423760"
2d5baeae9cb36adce422f50aaa75be33-073.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"409472"
2d5baeae9cb36adce422f50aaa75be33-074.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"350448"
2d5baeae9cb36adce422f50aaa75be33-075.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"365664"
2d5baeae9cb36adce422f50aaa75be33-076.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"400256"
2d5baeae9cb36adce422f50aaa75be33-077.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"388224"
2d5baeae9cb36adce422f50aaa75be33-078.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"399696"
2d5baeae9cb36adce422f50aaa75be33-079.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"421696"
2d5baeae9cb36adce422f50aaa75be33-080.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"406096"
2d5baeae9cb36adce422f50aaa75be33-081.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"377520"
2d5baeae9cb36adce422f50aaa75be33-082.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"382032"
2d5baeae9cb36adce422f50aaa75be33-083.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"369424"
2d5baeae9cb36adce422f50aaa75be33-084.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"398384"
2d5baeae9cb36adce422f50aaa75be33-085.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"373376"
2d5baeae9cb36adce422f50aaa75be33-086.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"363984"
2d5baeae9cb36adce422f50aaa75be33-087.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"382400"
2d5baeae9cb36adce422f50aaa75be33-088.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"360032"
2d5baeae9cb36adce422f50aaa75be33-089.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"378640"
2d5baeae9cb36adce422f50aaa75be33-090.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:9.92,"461552"
2d5baeae9cb36adce422f50aaa75be33-091.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXTINF:0.88,"53584"
2d5baeae9cb36adce422f50aaa75be33-092.ts?VideoId=20220966&Schema=cif&Speed=10&Type=video
#EXT-X-ENDLIST

**Comment by czeall** [comment]
Can anyone help with the problem?

**Comment by christosts** [comment]
This is a case where need a piece of media to test with; we need a link to media that reproduces the issue. You mention that the media is not publicly available but we cannot investigate without them. Can you please prepare a sample that reproduces the issue and is accessible to us, and the email the link to dev.exoplayer@gmail.com with the subject "Issue #8296". If yes, please update this issue after you send the email so that we take a look The playlist snippet that you have shared above is not enough, we'd need to look at the bitstream.

**Comment by czeall** [comment]
The information has been supplemented and the HLS test media has been sent to the mailbox

**Comment by czeall** [comment]
This test uses ijkplayer (the bottom layer uses ffmpeg and ffplay) to play the video. The obtained time stamp of the current playback position corresponds to the actual playing position of the video. I hope this information can help solve the problem.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "google/ExoPlayer"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月2日(星期三) 晚上10:49
收件人:&nbsp;"google/ExoPlayer"<ExoPlayer@noreply.github.com&gt;;
抄送:&nbsp;"赤 子"<654202200@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [google/ExoPlayer] The position of getcurrentposition after seekto of HLS resource is not accurate (#8296)





 
This is a case where need a piece of media to test with; we need a link to media that reproduces the issue. You mention that the media is not publicly available but we cannot investigate without them. Can you please prepare a sample that reproduces the issue and is accessible to us, and the email the link to dev.exoplayer@gmail.com with the subject "Issue #8296". If yes, please update this issue after you send the email so that we take a look The playlist snippet that you have shared above is not enough, we'd need to look at the bitstream.

**Comment by christosts** [comment]
Hi @czeall,

Thank you for sending the content. I played the content with the ExoPlayer demo app, using versions 2.11.1 (which you mention in the issue description) and 2.12.2 (the latest version). In both cases, after a seek is performed, Player.getCurrentPosition() returned the exact position of the seek.

May I ask:
- Do you observe the issue when playing the content with the ExoPlayer demo app?
- If yes, are there any specific steps I should attempt in order to reproduce the same issue?

**Comment by czeall** [comment]
I found the same problem when using exoplayer demo.
I found this problem recently when I was making subtitle plug-in requirements. The main representation is that the audio and video content of the player does not match the current subtitle display. The main logic of the external subtitle module is to display the subtitles corresponding to the subtitle file queue index according to the getcurrentposition() play position of the current player. Similarly, if I use the subtitle module in exoplayer, I also have the same problem that audio and video playback does not correspond to subtitle display.
I am considering that the problem may be caused by the uneven TS slices in the m3u8 file (all "s" in the m3u8 file read by exoplayer) `# EXTINF:`time ”The total length of does not match the actual length of all TS). For example, if I mark the file length of each TS file in the m3u8 file, the# EXTINF:9.92 ”Round up operation, change to "round up"# EXTINF:10 ”If getcurrentposition() is not accurate, the problem will disappear.However, if getcurrent() does not play all the files, I will not be able to play all the files# EXTINF:time ”If it is rounded up, getcurrentposition() will get the files with problems, but the m3u8 files with no problems will be retrieved after modification.
I will send the ass subtitle test resource file attached to the“ dev.exoplayer @ gmail.com "This mailbox. The specific step to find the problem is that after the HLS resource starts to play, after the seek operation, the subtitle display and video playback will not match. Because I use the video plug-in module developed by myself, I need to use getcurrentposition() to get the video position, but I think the implementation principle here is basically the same.
Thank you for your help.

**Comment by czeall** [comment]
Will my question continue to be discussed and resolved?

**Comment by christosts** [comment]
This is to confirm we have received the subtitle file and do see that subtitles become out-of-sync with audio/video. I will update the issue when I have more data to share.

**Comment by christosts** [comment]
I tested the video with the subtitles and see that the subtitles get out of sync with the video only after a seek is performed. If a seek is not performed, the subtitles remain in sync with the content. 

`seekTo()` and `getCurrentPosition()` are consistent. That is, after performing a `seekTo()` to time X, `getCurrentPosition()` returns X and the position advances as expected without any adjustment or jump. I am mentioning this because in the description of the ticket, I understood that they player may be seeking to X but getCurrentPosition() may return a different value.

What is probably happening is that they player is asked to seek to time X but it may not actually seek to this exact position. I debugged the durations of the segments, after you provided us with the hint that the segment durations in the m3u8 file may not be accurate:

> I am considering that the problem may be caused by the uneven TS slices in the m3u8 file (all "s" in the m3u8 file read by exoplayer) # EXTINF:time ”The total length of does not match the actual length of all TS). For example, if I mark the file length of each TS file in the m3u8 file, the# EXTINF:9.92 ”Round up operation, change to "round up"# EXTINF:10 ”If getcurrentposition() is not accurate, the problem will disappear.

The playlist says that each segment's duration is 9.92 seconds, however each segment seems to be 10 seconds. As a result, the player cannot seek to the exact location because the playlist and the media stream do not match. It appears that you are aware that the playlist's `# EXTINF` tags are not accurate and that you can fix the problem by setting them correctly. 

May I ask why you are not setting `# EXTINF` correctly?

**Comment by czeall** [comment]
Hello, if you have repeated out of sync, you will understand the problem I described. The TS slicing files of HLS resources are automatically sliced and converted by the server. At present, because the same HLS resource files and subtitles are synchronized normally on the H5 side, it is also normal to test the playback synchronization with ijkplayer on the Android side. However, if the seek operation is performed under the exoplayer on the Android side and avplayer on the IOS side, the synchronization will occur.So I want to find out the cause of the problem. The HLS resource problem may be a situation. In addition, I also want to ask whether exoplayer has the corresponding fault tolerance treatment to repair this situation.
For example, the time length (frame rate * size) is set according to the length of the actual TS file size obtained.

**Comment by christosts** [comment]
> In addition, I also want to ask whether exoplayer has the corresponding fault tolerance treatment to repair this situation.

At the moment, ExoPlayer does not handle the situation where the playlist does not reflect how the segments are actually sliced. Introducing such a mechanism would require a lot of changes that would make the player either fragile or slow down its performance. Please check if you can change this in the HLS side and properly create the HLS playlists.
