### ISSUE TITLE
How to display multiple download notifications ?

### ISSUE THREAD

**Issue by yoobi** [google/ExoPlayer#8297]
### [REQUIRED] Searched documentation and issues
I've found this issue https://github.com/google/ExoPlayer/issues/4494 and this page https://exoplayer.dev/downloading-media.html#creating-a-downloadservice

### [REQUIRED] Question
I've got exactly the same question as the issue https://github.com/google/ExoPlayer/issues/4494 but I didn't get the answer, would you be so kind to details it a bit more ?

How can I return a `List<Notification>` ? or should I just create notification and return the last one from my `downloads: MutableList<Download>` ?

**Comment by christosts** [comment]
@marcbaechinger can you take a look?

**Comment by jandresakis** [comment]
You should take a look at the DownloadNotificationHelper class 
https://github.com/google/ExoPlayer/blob/release-v2/library/ui/src/main/java/com/google/android/exoplayer2/ui/DownloadNotificationHelper.java

I just copied it to start and heavily modified it to fit the patterns I use but its a great starting point

**Comment by yoobi** [comment]
Well I know how to create and customize a notification, my question is how can I make to show multiple notification ? The issue is with `Notification getForegroundNotification(@NonNull List<Download> downloads)`

**Comment by jandresakis** [comment]
I dont think you would want multiple notifications. You would be better off showing one notification with multiple progress bars using a custom view in the notification. Then you would just take into account the progress of each on going download and update the UI accordingly. That's just my opinion of course. 

You could start here - https://developer.android.com/training/notify-user/custom-notification

**Comment by marcbaechinger** [comment]
I agree as a user I would probably prefer a single notification telling me about whats going on in one place. That may be an opinionated and personal view though.

Technically, when running your download service as a foreground service you need to return one notification from `Notification getForegroundNotification(List<Download> downloads)`. This notification is used for the foreground service to make sure the system does not kill your service. 

I think there is nothing that keeps you away from creating additional notifications yourself besides this one required for the foreground. So, when the method is called you pick one `Download` from the list of downloads, create your notification and return it. Then create [additional notifications yourself ](https://developer.android.com/training/notify-user/build-notification) for the other downloads. You can choose any strategy how to do that besides the one single notification that you need to return for the foreground. 

When the `getForegroundNotification` method is called again, this logic then needs to make sure to update all your notifications accordingly, by mapping the downloads in the list to the corresponding notification. The library just does not know about all these notifications as you create and keep them up to date yourself behind `Notification getForegroundNotification(List<Download> downloads)`.

Please also consider the reply from jandresakis above that points you to create a custom layout that displays extended information about all downloads in a single notification.

**Comment by yoobi** [comment]
> I think there is nothing that keeps you away from creating additional notifications yourself besides this one required for the foreground. So, when the method is called you pick one Download from the list of downloads, create your notification and return it. Then create additional notifications yourself for the other downloads. You can choose any strategy how to do that besides the one single notification that you need to return for the foreground.
> 
> When the getForegroundNotification method is called again, this logic then needs to make sure to update all your notifications accordingly, by mapping the downloads in the list to the corresponding notification. The library just does not know about all these notifications as you create and keep them up to date yourself behind Notification getForegroundNotification(List<Download> downloads).

Okay that's what I was going for but I wasn't sure it was the right solution. I was also thinking of using [group notification](https://developer.android.com/training/notify-user/group) with it

@jandresakis do you have an example of what you've done ?

**Comment by jandresakis** [comment]
Ive never used the group notification but that might be a nice approach. 

The way I used their example kinda looks like this. Sorry but the app is not mine so I can't share specific implementation stuff:

here would be my custom notification helper
```
public final class CustomNotificationHelper { 
    
    public Notification buildProgressNotification(
      Context context,
      @DrawableRes int smallIcon,
      @Nullable PendingIntent contentIntent,
      @Nullable String message,
      List<Download> downloads) {
        // Do all the magic to reference your existing notification, get references to the custom views, 
        // iterate through the downloads, and update the UI
    }
}
```

and then my service that extends from DownloadService uses it like this 

```
class MyDownloadService : DownloadService(FOREGROUND_NOTIFICATION_ID,
                                            DEFAULT_FOREGROUND_NOTIFICATION_UPDATE_INTERVAL,
                                            CHANNEL_ID,
                                            CHANNEL_NAME, CHANNEL_DESCRIPTION_ID) {

    override fun getForegroundNotification(downloads: MutableList<Download>): Notification {
        customNotificationHelper.buildProgressNotification(context, notificationId, null, null, downloads)
    }

}
```

In your case use which is probably close to mine I would do it like that with all the updating logic living in the notification helper. Using custom views its possible to get pretty close to that group look while offering actionable buttons or swipe actions. Using that same helper pattern approach you might be able use the group notifications but after taking a quick look at the documentation and what the service is doing with the notification your building by passing it to an activity manager Im not sure.
