### ISSUE TITLE
Scrambled video when playing Smooth Streaming with DRM Playready on Nexus Player

### ISSUE THREAD

**Issue by coding4Lif3** [google/ExoPlayer#830]
Hi guys, we are using Exoplayer on a Nexus Player device for play video Smooth Streaming with DRM Playready.

I noticed that with normal content, Smooth Streaming without DRM Playready, the player works fine!
While at the start of the player for protected content there's a Scrambled video effect for more/less 5 seconds. After some seconds the video is rendered fine (like the free SmoothStreaming content).

I also noticed that rewinding the video to second 00:00 the video problem doesn't appear, so the video continues to be rendered fine.

Here we can find some Exoplayer's errors, but I don't know if are related to this problem because I have always these errors, also when I play normal content....!

Maybe could be related to: [#725](https://github.com/google/ExoPlayer/issues/725) or to [#612](https://github.com/google/ExoPlayer/issues/612) ?

Thanks in advance,
Federico

**Error:**
7030-8259/it.myapp.secure_player E/ACodec﹕ [OMX.Intel.VideoDecoder.AVC.secure] storeMetaDataInBuffers failed w/ err -1010

**Warning:**
7030-9747/it.myapp.secure_player W/linker﹕ libmfx_omx_components_sw.so: unused DT entry: type 0x6ffffffe arg 0x1908
7030-9747/it.myapp.secure_player W/linker﹕ libmfx_omx_components_sw.so: unused DT entry: type 0x6fffffff arg 0x1

**Extract of full log:**
09-30 13:19:16.655    7030-7030/it.myapp.secure_player I/ExoPlayerImpl? Init 1.4.2
09-30 13:19:16.660    7030-7030/it.myapp.secure_player D/EventLogger? start [0]
09-30 13:19:16.660    7030-7030/it.myapp.secure_player D/EventLogger? state [0.00, false, P]
09-30 13:19:16.663    7030-7030/it.myapp.secure_player D/EventLogger? state [0.00, true, P]
09-30 13:19:17.416    7030-7030/it.myapp.secure_player I/VideoCapabilities? Unsupported profile 4 for video/mp4v-es
09-30 13:19:17.426    7030-7030/it.myapp.secure_player D/EventLogger? state [0.77, false, P]
09-30 13:19:17.426    7030-7030/it.myapp.secure_player D/EventLogger? state [0.77, true, P]
09-30 13:19:17.429    7030-7030/it.myapp.secure_player D/EventLogger? state [0.77, true, B]
09-30 13:19:17.429    7030-7030/it.myapp.secure_player D/EventLogger? videoFormat [0.77, 0, 1]
09-30 13:19:17.552    7030-7030/it.myapp.secure_player D/EventLogger? bandwidth [0.89, 50102, 0.09, 4264000]
09-30 13:19:17.584    7030-7030/it.myapp.secure_player D/EventLogger? bandwidth [0.92, 10782, 0.03, 4264000]
09-30 13:19:18.145    7030-8259/it.myapp.secure_player I/OMXClient? Using client-side OMX mux.
09-30 13:19:18.155    7030-8259/it.myapp.secure_player E/ACodec? [OMX.Intel.VideoDecoder.AVC.secure] storeMetaDataInBuffers failed w/ err -1010
09-30 13:19:18.353    7030-7030/it.myapp.secure_player D/EventLogger? decoderInitialized [1.69, OMX.Intel.VideoDecoder.AVC.secure]
09-30 13:19:18.353    7030-7030/it.myapp.secure_player D/EventLogger? audioFormat [1.69, 0, 1]
09-30 13:19:18.357    7030-8263/it.myapp.secure_player I/OMXClient? Using client-side OMX mux.
09-30 13:19:18.361    7030-8263/it.myapp.secure_player I/wrs-omxil-core? found component library libOMXVideoDecoderAVC.so
09-30 13:19:18.362    7030-8263/it.myapp.secure_player I/cmodule? module libOMXVideoDecoderAVC.so successfully loaded
09-30 13:19:18.363    7030-8263/it.myapp.secure_player I/cmodule? module libOMXVideoDecoderAVC.so successfully unloaded
09-30 13:19:18.363    7030-8263/it.myapp.secure_player I/wrs-omxil-core? module libOMXVideoDecoderAVC.so:OMX.Intel.VideoDecoder.AVC added to component list
09-30 13:19:18.363    7030-8263/it.myapp.secure_player I/wrs-omxil-core? found component library libOMXVideoDecoderH263.so
09-30 13:19:18.364    7030-8263/it.myapp.secure_player I/cmodule? module libOMXVideoDecoderH263.so successfully loaded
09-30 13:19:18.364    7030-8263/it.myapp.secure_player I/cmodule? module libOMXVideoDecoderH263.so successfully unloaded
09-30 13:19:18.364    7030-8263/it.myapp.secure_player I/wrs-omxil-core? module libOMXVideoDecoderH263.so:OMX.Intel.VideoDecoder.H263 added to component list
09-30 13:19:18.364    7030-8263/it.myapp.secure_player I/wrs-omxil-core? found component library libOMXVideoDecoderWMV.so
09-30 13:19:18.365    7030-8263/it.myapp.secure_player I/cmodule? module libOMXVideoDecoderWMV.so successfully loaded
09-30 13:19:18.365    7030-8263/it.myapp.secure_player I/cmodule? module libOMXVideoDecoderWMV.so successfully unloaded
09-30 13:19:18.365    7030-8263/it.myapp.secure_player I/wrs-omxil-core? module libOMXVideoDecoderWMV.so:OMX.Intel.VideoDecoder.WMV added to component list
09-30 13:19:18.365    7030-8263/it.myapp.secure_player I/wrs-omxil-core? found component library libOMXVideoDecoderMPEG4.so
09-30 13:19:18.366    7030-8263/it.myapp.secure_player I/cmodule? module libOMXVideoDecoderMPEG4.so successfully loaded
09-30 13:19:18.367    7030-8263/it.myapp.secure_player I/cmodule? module libOMXVideoDecoderMPEG4.so successfully unloaded
09-30 13:19:18.367    7030-8263/it.myapp.secure_player I/wrs-omxil-core? module libOMXVideoDecoderMPEG4.so:OMX.Intel.VideoDecoder.MPEG4 added to component list
09-30 13:19:18.367    7030-8263/it.myapp.secure_player I/wrs-omxil-core? found component library libOMXVideoDecoderVP8.so
09-30 13:19:18.368    7030-8263/it.myapp.secure_player I/cmodule? module libOMXVideoDecoderVP8.so successfully loaded
09-30 13:19:18.368    7030-8263/it.myapp.secure_player I/cmodule? module libOMXVideoDecoderVP8.so successfully unloaded
09-30 13:19:18.368    7030-8263/it.myapp.secure_player I/wrs-omxil-core? module libOMXVideoDecoderVP8.so:OMX.Intel.VideoDecoder.VP8 added to component list
09-30 13:19:18.368    7030-8263/it.myapp.secure_player I/wrs-omxil-core? found component library libOMXVideoDecoderVP9HWR.so
09-30 13:19:18.369    7030-8263/it.myapp.secure_player I/cmodule? module libOMXVideoDecoderVP9HWR.so successfully loaded
09-30 13:19:18.369    7030-8263/it.myapp.secure_player I/cmodule? module libOMXVideoDecoderVP9HWR.so successfully unloaded
09-30 13:19:18.369    7030-8263/it.myapp.secure_player I/wrs-omxil-core? module libOMXVideoDecoderVP9HWR.so:OMX.Intel.VideoDecoder.VP9.hwr added to component list
09-30 13:19:18.369    7030-8263/it.myapp.secure_player I/wrs-omxil-core? found component library libOMXVideoDecoderVP9Hybrid.so
09-30 13:19:18.370    7030-8263/it.myapp.secure_player I/cmodule? module libOMXVideoDecoderVP9Hybrid.so successfully loaded
09-30 13:19:18.370    7030-8263/it.myapp.secure_player I/cmodule? module libOMXVideoDecoderVP9Hybrid.so successfully unloaded
09-30 13:19:18.370    7030-8263/it.myapp.secure_player I/wrs-omxil-core? module libOMXVideoDecoderVP9Hybrid.so:OMX.Intel.VideoDecoder.VP9.hybrid added to component list
09-30 13:19:18.370    7030-8263/it.myapp.secure_player I/wrs-omxil-core? found component library libOMXVideoDecoderAVCSecure.so
09-30 13:19:18.371    7030-8263/it.myapp.secure_player I/cmodule? module libOMXVideoDecoderAVCSecure.so successfully loaded
09-30 13:19:18.372    7030-8263/it.myapp.secure_player I/cmodule? module libOMXVideoDecoderAVCSecure.so successfully unloaded
09-30 13:19:18.372    7030-8263/it.myapp.secure_player I/wrs-omxil-core? module libOMXVideoDecoderAVCSecure.so:OMX.Intel.VideoDecoder.AVC.secure added to component list
09-30 13:19:18.372    7030-8263/it.myapp.secure_player I/wrs-omxil-core? found component library libOMXVideoEncoderAVC.so
09-30 13:19:18.373    7030-8263/it.myapp.secure_player I/cmodule? module libOMXVideoEncoderAVC.so successfully loaded
09-30 13:19:18.373    7030-8263/it.myapp.secure_player I/cmodule? module libOMXVideoEncoderAVC.so successfully unloaded
09-30 13:19:18.373    7030-8263/it.myapp.secure_player I/wrs-omxil-core? module libOMXVideoEncoderAVC.so:OMX.Intel.VideoEncoder.AVC added to component list
09-30 13:19:18.373    7030-8263/it.myapp.secure_player I/wrs-omxil-core? found component library libOMXVideoEncoderH263.so
09-30 13:19:18.375    7030-8263/it.myapp.secure_player I/cmodule? module libOMXVideoEncoderH263.so successfully loaded
09-30 13:19:18.375    7030-8263/it.myapp.secure_player I/cmodule? module libOMXVideoEncoderH263.so successfully unloaded
09-30 13:19:18.375    7030-8263/it.myapp.secure_player I/wrs-omxil-core? module libOMXVideoEncoderH263.so:OMX.Intel.VideoEncoder.H263 added to component list
09-30 13:19:18.375    7030-8263/it.myapp.secure_player I/wrs-omxil-core? found component library libOMXVideoEncoderMPEG4.so
09-30 13:19:18.376    7030-8263/it.myapp.secure_player I/cmodule? module libOMXVideoEncoderMPEG4.so successfully loaded
09-30 13:19:18.376    7030-8263/it.myapp.secure_player I/cmodule? module libOMXVideoEncoderMPEG4.so successfully unloaded
09-30 13:19:18.376    7030-8263/it.myapp.secure_player I/wrs-omxil-core? module libOMXVideoEncoderMPEG4.so:OMX.Intel.VideoEncoder.MPEG4 added to component list
09-30 13:19:18.376    7030-8263/it.myapp.secure_player I/wrs-omxil-core? found component library libOMXVideoEncoderVP8.so
09-30 13:19:18.378    7030-8263/it.myapp.secure_player I/cmodule? module libOMXVideoEncoderVP8.so successfully loaded
09-30 13:19:18.378    7030-8263/it.myapp.secure_player I/cmodule? module libOMXVideoEncoderVP8.so successfully unloaded
09-30 13:19:18.378    7030-8263/it.myapp.secure_player I/wrs-omxil-core? module libOMXVideoEncoderVP8.so:OMX.Intel.VideoEncoder.VP8 added to component list
09-30 13:19:18.381    7030-8263/it.myapp.secure_player W/linker? libmfx_omx_components_sw.so: unused DT entry: type 0x6ffffffe arg 0x1908
09-30 13:19:18.381    7030-8263/it.myapp.secure_player W/linker? libmfx_omx_components_sw.so: unused DT entry: type 0x6fffffff arg 0x1
09-30 13:19:18.382    7030-8263/it.myapp.secure_player I/libva? VA-API version 0.34.0
09-30 13:19:18.383    7030-8263/it.myapp.secure_player I/libva? va_getDriverName() returns 0
09-30 13:19:18.383    7030-8263/it.myapp.secure_player I/libva? Trying to open /system/lib/pvr_drv_video.so
09-30 13:19:18.384    7030-8263/it.myapp.secure_player I/libva? Found init function __vaDriverInit_0_32
09-30 13:19:18.384    7030-8263/it.myapp.secure_player I/libva? va_openDriver() returns 0
09-30 13:19:18.390    7030-8263/it.myapp.secure_player I/? OMX IL core libisv_omx_core.so: declares component OMX.Intel.VideoDecoder.AVC
09-30 13:19:18.390    7030-8263/it.myapp.secure_player I/? OMX IL core libisv_omx_core.so: declares component OMX.Intel.VideoDecoder.H263
09-30 13:19:18.390    7030-8263/it.myapp.secure_player I/? OMX IL core libisv_omx_core.so: declares component OMX.Intel.VideoDecoder.WMV
09-30 13:19:18.390    7030-8263/it.myapp.secure_player I/? OMX IL core libisv_omx_core.so: declares component OMX.Intel.VideoDecoder.MPEG4
09-30 13:19:18.390    7030-8263/it.myapp.secure_player I/? OMX IL core libisv_omx_core.so: declares component OMX.Intel.VideoDecoder.VP8
09-30 13:19:18.390    7030-8263/it.myapp.secure_player I/? OMX IL core libisv_omx_core.so: declares component OMX.Intel.VideoDecoder.VP9.hwr
09-30 13:19:18.390    7030-8263/it.myapp.secure_player I/? OMX IL core libisv_omx_core.so: declares component OMX.Intel.VideoDecoder.VP9.hybrid
09-30 13:19:18.390    7030-8263/it.myapp.secure_player I/? OMX IL core libisv_omx_core.so: declares component OMX.Intel.VideoDecoder.AVC.secure
09-30 13:19:18.390    7030-8263/it.myapp.secure_player I/? OMX IL core libisv_omx_core.so: declares component OMX.Intel.VideoEncoder.AVC
09-30 13:19:18.391    7030-8263/it.myapp.secure_player I/? OMX IL core libisv_omx_core.so: declares component OMX.Intel.VideoEncoder.H263
09-30 13:19:18.391    7030-8263/it.myapp.secure_player I/? OMX IL core libisv_omx_core.so: declares component OMX.Intel.VideoEncoder.MPEG4
09-30 13:19:18.391    7030-8263/it.myapp.secure_player I/? OMX IL core libisv_omx_core.so: declares component OMX.Intel.VideoEncoder.VP8
09-30 13:19:18.391    7030-8263/it.myapp.secure_player I/? OMX IL core libisv_omx_core.so: declares component OMX.Intel.sw_vd.h265
09-30 13:19:18.391    7030-8263/it.myapp.secure_player I/? OMX IL core libisv_omx_core.so: contains 13 components

**Comment by ojw28** [comment]
Does this occur when playing the SmoothStreaming (PlayReady) sample in the demo app, or only when playing some other content that you have access to? Thanks!

**Comment by coding4Lif3** [comment]
Thanks for your feedback and sorry for the delay!
I'm having problems with other smoothstreaming content.

Tomorrow I'll check it with the PlayReady sample demo app for give you a feedback!

Thanks,
Federico

**Comment by coding4Lif3** [comment]
Hi ojw28,
I did a test with the demo app and I was able to see that the video don't have my issue....!

So, do you have any suggestion about this problem? What could be the cause of it?

Regards,
Federico

**Comment by ojw28** [comment]
Closing because bug is stale. If still relevant: I don't have any suggestions, sorry. I'm guessing something about the way you're encrypting the streams is invalid and/or not handled by the PlayReady DRM implementation.
