### ISSUE TITLE
playing flac format audio，when play end，it can't callback onPositionDiscontinuity （r2.12.1）

### ISSUE THREAD

**Issue by ZhangHui0608** [google/ExoPlayer#8306]

**Comment by christosts** [comment]
For general questions, we have a template issue that mentions the information we need. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/question.md).

Overall, I'm not sure why the onPositionDiscontinuity is expected. Can you provide more information? The issue template can help.
