### ISSUE TITLE
Failed to play manifest that has presentationTimeOffset And startNumber > 1

### ISSUE THREAD

**Issue by kennykarnama** [google/ExoPlayer#8307]
When reporting a bug:
-----------------------

### [REQUIRED] Issue description
Hi, i tried to add presentationTimeOffset to my manifest and play it using demo application exoplayer. But it can't be played or sometimes it is playable but audio is out of sync. 
As i suspect, may be there is something wrong with my manifest, i tried to play using dash.js. It was successfully played and the audio is sync too

### [REQUIRED] Reproduction steps
Play the manifest file using demo application

```
on Clear DASH attribute inside file media.exolist.json, add the following key: 
{
        "name": "Live Quiz trimmed segment timeline with only presentation offset",
        "uri": "https://rg-live-streaming.s3-ap-southeast-1.amazonaws.com/live-quiz/ac1bb5d3-3dfb-4214-b6f3-9c82b10e53b3/stitched_test_trimmed_by_offset.mpd"
      }
```
Then play it.

### [REQUIRED] Link to test content
https://rg-live-streaming.s3-ap-southeast-1.amazonaws.com/live-quiz/ac1bb5d3-3dfb-4214-b6f3-9c82b10e53b3/stitched.mpd

### [REQUIRED] A full bug report captured from the device
not sure about the log, but after press the video, i got this log

```
2020-12-02 16:44:38.068 22952-23256/com.google.android.exoplayer2.demo E/FMQ: grantorIdx must be less than 3
2020-12-02 16:44:38.068 22952-23256/com.google.android.exoplayer2.demo E/FMQ: grantorIdx must be less than 3
2020-12-02 16:44:38.073 22952-23256/com.google.android.exoplayer2.demo I/CCodecBufferChannel: [c2.android.aac.decoder#896] Created output block pool with allocatorID 16 => poolID 96 - OK
2020-12-02 16:44:38.077 22952-23256/com.google.android.exoplayer2.demo E/FMQ: grantorIdx must be less than 3
2020-12-02 16:44:38.085 22952-23119/com.google.android.exoplayer2.demo E/FMQ: grantorIdx must be less than 3
2020-12-02 16:44:38.101 22952-23246/com.google.android.exoplayer2.demo E/AudioTrack: Discontinuity detected [expected 0, got -1998934]
````

### [REQUIRED] Version of ExoPlayer being used
r2.12.2 (clone from github repository)

### [REQUIRED] Device(s) and version(s) of Android being used
- Emulator Pixel_3a_API_30_x86
- samsung J4+ galaxy, androd 6.0

**Comment by christosts** [comment]
~~Quick update: I'm able to play the manifest with 2.12.1 but not 2.12.2. Investigating where there's a regression on DASH live streaming in 2.12.2.~~

~~@kennykarnama, in the meantime, can you verify the stream works for you in 2.12.1?~~

**[update]**
I probably hit false positives, the first few attempts on 2.12.1 worked fine and I assumed that's the case in general, but I'm also seeing playback failing with 2.12.1 so the above is not accurate.

**Comment by christosts** [comment]
The presentation time offset in the manifest is set to 780 seconds and each segment has a duration of 2 seconds. I modified ExoPlayer to ignore the presentation time offset and the player starts playback at 778 seconds, so I'm assuming (but have not verified yet) that the first segment's PTSes start at 778 seconds - startNumber is 390 in the manfiest. 
Considering that segment duration is 2 seconds, it looks there's an off-by-one error somewhere. Eg, if I set the startNumber at 391 (instead of 390), playback works.

I'm not sure it's an ExoPlayer problem at the moment. Can you please check that the bistream is packaged correctly, i.e segment 390 PTS starts at 780 seconds and not 778 seconds?

Note: I tried playing with VLC, which does play the content but after some delay and a few warning logs on around discontinuities, which I think are indications of a similar problem, though VLC seems to be more robust.

**Comment by christosts** [comment]
> I'm not sure it's an ExoPlayer problem at the moment. Can you please check that the bistream is packaged correctly, i.e segment 390 PTS starts at 780 seconds and not 778 seconds?

I may have made an off-by-one mistake here myself. If segment numbers start from 1, then segment 391 (and not 390) should start at 780 seconds ( `(780 / 2) + 1` because segment no 1 starts at 0 seconds)

**Comment by kennykarnama** [comment]
Hi @christosts, thanks for replying.

i tried to change the segment number start to become 391, but still the playback failed.
Also the issue was reproduced if i use bitmovin stream tester. 

So, I tried to cross check if it is true that segment 391 occur at 780 seconds by looking on first segment timestamp creation until it reach 780 seconds, and found that it should be segment no 381 

i tried to change as follow:

https://rg-live-streaming.s3-ap-southeast-1.amazonaws.com/live-quiz/ac1bb5d3-3dfb-4214-b6f3-9c82b10e53b3/stitched_trimmed2.mpd

I tested in exoplayer, now it can be played but the audio is out of sync. But in bitmovin, it works (audio - video is sync).

**Comment by christosts** [comment]
> So, I tried to cross check if it is true that segment 391 occur at 780 seconds by looking on first segment timestamp creation until it reach 780 seconds, and found that it should be segment no 381

If the segments have a duration of 2 seconds, then segment 381 should start at 760 seconds. I do see 760 that when testing with the latest manifest. However, when I override the startNumber to 391, playback works fine (tested with 2.12.2 on a Pixel 4). Can you please try again with startNumber set to 391 for both video and audio (assuming both tracks have a fixed 2 seconds duration). If that fails, please attach the logs.

If you want to debug in more detail, you can also see the sample timestamps in two locations
- [SampleQueue.sampleMetadata()](https://github.com/google/ExoPlayer/blob/r2.12.2/library/core/src/main/java/com/google/android/exoplayer2/source/SampleQueue.java#L558): this is where sample timestamps are adjusted based on the presentation time offset
- [MediaCodecRenderer.feedInputBuffer()](https://github.com/google/ExoPlayer/blob/r2.12.2/library/core/src/main/java/com/google/android/exoplayer2/mediacodec/MediaCodecRenderer.java#L1386) this is where the samples are passed to the platform for decoding. The first sample per audio/video should have a PTS of 0 after adjustment (but they are negative in this case).
