### ISSUE TITLE
HLS bitrate change shows upside down image

### ISSUE THREAD

**Issue by thomasfriedl** [google/ExoPlayer#831]
After updating to 1.5.0 whenever there is a HLS quality change (better quality) I see the current frame upside down for a fraction (from 50ms to 500ms). Afterwards it plays the better quality just fine. I didn't see that behaviour with 1.4.2.

**Comment by ojw28** [comment]
What device and OS version is this happening on?

**Comment by ojw28** [comment]
Closing due to insufficient information.
