### ISSUE TITLE
Try to playback HLS + TS widevine  protected ， playback almost successful with local anomaly sometimes

### ISSUE THREAD

**Issue by lys1737** [google/ExoPlayer#8314]
### [REQUIRED] Question
Describe your question in detail.
Use Exoplayer version 2.10 , try to playback HLS + TS widevine  protected ，audio AAC/AC3 decode success and playback success ， video H264  decode success but playback disturbed 。

 I set drmInitData  right and get license success。 Parse keyid 、iv and set into H264Reader，AdtsReader。I find SampleQueue get encrypt params like iv，clearSize=9，encryptionKey=1,  encryptedBlocks =9 。So I set clearSize=16，encryptionKey=0,  encryptedBlocks =0 to decode audio and playback success， I set clearSize=9 + 32，encryptionKey=1,  encryptedBlocks =9 to decode，Finally， I can see the animals in my video with error color and  superimposed with the impact of the previous second。

From https://developer.apple.com/library/archive/documentation/AudioVideo/Conceptual/HLS_Sample_Encryption/Encryption/Encryption.html#//apple_ref/doc/uid/TP40012862-CH2-SW6 ， It said that  emulation prevention must again be applied over the entire NAL unit，Am I missing this step？

**Comment by lys1737** [comment]
Latest progress after audio playback success。

To decode video ， I found clearSize is 9 for HLS + fMP4 and set nal type equal 1。
Use 'clearSize = 9 + 32' to decode NAL type 1 and 'clearSize = 32' to decode NAL type 5, It playback video almost successful in Android 11,  playback video almost successful in  Android 9 with few green screen （The picture is normal but color is green）。

It playback video almost successful with local anomaly sometimes。 

first，I am not sure why can I add 9 in 'clearSize=9+32' when Nal type is 1， but I let me playback anomaly successful。
second， I am not sure that it is right for me to set 'clearSize = 32' when Nal type is 5, because when I set clearSize equal is 0、4、8、16 etc, only a little impact on playback。

**Comment by AquilesCanta** [comment]
Hi, widevine in transport stream is not supported by ExoPlayer. The only protection scheme we support for transport stream is full segment encryption. For widevine support using transport stream segments in HLS, you should track #4021.

NOTE: Contributions on this area would be welcome.
