### ISSUE TITLE
Playback error when trying to play video

### ISSUE THREAD

**Issue by dmitrytavpeko** [google/ExoPlayer#8315]
I try to play a video in the ExoPlayer demo application, but it does not start playing.
**Reprodution steps**: 
1) open the video
 adb shell am start -a com.google.android.exoplayer.demo.action.VIEW -d https://filesamples.com/samples/video/mkv/sample_2560x1440.mkv

**Expected**: video is playing well
**Actual**: video is not started. An error message appears.

**Bugreport**: sent to email.
**Content**: https://filesamples.com/samples/video/mkv/sample_2560x1440.mkv
**ExoPlayer version**: 2.12.2
**Android version**: 9
**Device**: Nokia 6 TA-1021

**Comment by christosts** [comment]
From the log (and the name of the test content) it looks like the video resolution is 2560x1440 (1440p). However, it appears that the device cannot handle this resolution. From the bug-report (this should appear on the logcat too):
```
280 16453 16453 D EventLogger:   MediaCodecVideoRenderer [
12-04 02:10:37.166 10280 16453 16453 D EventLogger:     Group:0, adaptive_supported=N/A [
12-04 02:10:37.166 10280 16453 16453 D EventLogger:       [X] Track:0, id=1, mimeType=video/avc, res=2560x1440, language=und, supported=NO_EXCEEDS_CAPABILITIES
12-04 02:10:37.166 10280 16453 16453 D EventLogger:     ]
12-04 02:10:37.166 10280 16453 16453 D EventLogger:   ]  
```

Notice the video renderer reports that **supported=NO_EXCEEDS_CAPABILITIES**

I suggest to use a resolution that is supported by the device, or try on a device that can decode 1440p video.

Closing this for now, feel free to reopen if the issue persists.

**Comment by dmitrytavpeko** [comment]
Thank you for the answer!
I've tried to play it in VLC player and it plays well. Do you have any future plans to handle such situations or is the ExoPlayer is not designed for this?

**Comment by christosts** [comment]
> I've tried to play it in VLC player and it plays well.

I assume you mean you used VLC on the specific device. Can you please inspect the device logs to get a hint on what decoder VLC used? My guess is that VLC is playing the video with its bundled ffmpeg software decoders. If that's the case, ExoPlayer has an ffmpeg extension which currently supports audio, but in the dev branch there's incomplete support for [video](https://github.com/google/ExoPlayer/blob/dev-v2/extensions/ffmpeg/src/main/java/com/google/android/exoplayer2/ext/ffmpeg/FfmpegVideoRenderer.java). We have no concrete plans to release this feature yet.
