### ISSUE TITLE
appending bytes to data source while playing audio

### ISSUE THREAD

**Issue by mhdabbaghy** [google/ExoPlayer#8321]
Hi,
I'm trying to play a realtime voice with Exo player
data bytes comes from a Bluetooth device and the data length is unset
my problem is I didn't find any good doc or example to do that.
this is how I tried to solve the problem:
1- I create a ByteArray and filled it with headers (List<Byte> bytes = new ArrayList()
2- I create Uri from that array
3- create a data source and pass that array to it's the constructor
4- when new data arrived, add it to the array and increase remains

but it doesn't work, I did everything like ByteArrayDataSource but my problem didn't solve

**Comment by krocard** [comment]
> I'm trying to play a realtime voice with Exo player

Note that ExoPlayer is not designed for realtime audio playback. It will introduce significant latency to your playback. Directly using `AudioTrack` will give you better latency.

> 4- when new data arrived, add it to the array and increase remains

How do you add it to the array? Java arrays can not be increased in size.
How do you increase remains? `bytesRemaining` is a private field of `ByteArrayDataSource`.

I don't believe `ByteArrayDataSource` is the right approach, as it is intended to play an array of constant size.
Consider implementing your own `DataSource` similar to `ByteArrayDataSource`.

It's hard to provide guidance without a better understanding of your use case. Could you describe your use case?

**Comment by tonihei** [comment]
This issue also sounds very similar to #8051 and it 's worth checking the implementation hints provided in there if you think ExoPlayer is a good choice compared to using AudioTrack directly.

**Comment by mhdabbaghy** [comment]
tnx @tonihei 
I saw that but my problem didn't solve, I think his problem didn't solve too

**Comment by ojw28** [comment]
As @krocard notes above, using `AudioTrack` directly is probably a better way of implementing this. From the little information provided, it seems unlikely that ExoPlayer is the right API to be using.
