### ISSUE TITLE
ExoPlayer support in CMAF, CTE with http 1.1

### ISSUE THREAD

**Issue by He12345678901** [google/ExoPlayer#8327]

**Comment by He12345678901** [comment]
Hi, the Exoplayer supports on DASH/ Low latency in live channels with CMAF/Chunk Transfer Encoding over HTTP 1.1 ? please specify which ExoPlayer versions already support that feature and which parameters involved in its customization for small chunks
thanks

**Comment by ojw28** [comment]
Low latency DASH should be fully supported from `2.13.0`, which is scheduled to be released at some point in the first quarter of next year. The functionality should already be available in the `dev-v2` branch.

>  and which parameters involved in its customization for small chunks

I don't really understand the question. However, `exoplayer.dev` page will be updated with documentation around low latency functionality when `2.13.0` is released.

**Comment by He12345678901** [comment]
thanks
it means that 2.13.0 release will support DASH Low latency with 'Chunk Transfer Encoding' (CTE) over HTTP 1.1 ?

**Comment by ojw28** [comment]
Yes.
