### ISSUE TITLE
 Format.frameRate for HLS

### ISSUE THREAD

**Issue by lazycatsoft** [google/ExoPlayer#8337]
Found a problem: For HLS streams, the Format.frameRate field is not detected (always -1, but correct work for MP4).
This data is required to implement autoframerate for correct inclusion of Display.Mode via preferredDisplayModeId.

Is it possible to expect correct filling of the Format.frameRate field for hls in the future?

**Comment by ojw28** [comment]
The `Format.frameRate` field will be populated if the `FRAME-RATE` attribute is specified on the `EXT-X-STREAM-INF` tags in the HLS master playlist. This attribute is optional but recommended, as per the [HLS RFC](https://tools.ietf.org/html/draft-pantos-hls-rfc8216bis-08):

```
FRAME-RATE

The value is a decimal-floating-point describing the maximum frame
rate for all the video in the Variant Stream, rounded to three
decimal places.

The FRAME-RATE attribute is OPTIONAL but is recommended if the
Variant Stream includes video.  The FRAME-RATE attribute SHOULD be
included if any video in a Variant Stream exceeds 30 frames per
second.
```

There is no way for the player to efficiently determine the frame-rate of each variant if this information is not included, so we wont be changing how this works in the future. The correct solution is to ensure that the `FRAME-RATE` attribute is specified in the content.
