### ISSUE TITLE
Ima extension high memory issue

### ISSUE THREAD

**Issue by Rulemylife** [google/ExoPlayer#8339]
ExoPlayer Version : 2.12.2 , IMA extension : 2.12.2
I use IMA to play  vast advertises,  when I quite the app  and it becomes a background process, but the momery is still to high, above 100M. Even I called AdsLoader.release , player.release and playerView.setPlayer(null), it doesn't work. 
Also I tested BasicSample of IMA SDK, it has the same problem. How could I decrease the app's memory when I quite the app.

**Comment by andrewlewis** [comment]
Thanks for the report. I think this is probably a memory leak tracked by [internal: b/170917904] and I will plan to update this issue when we have more information.
