### ISSUE TITLE
Encountered more data after announced end of track

### ISSUE THREAD

**Issue by ChernyshovYuriy** [google/ExoPlayer#8341]
Dear engineers,
There is one stream that confuses me when I try to use ExoPlayer to consume it:
```
http://stream.psychoradio.org:8000
```
It has intro, something like advertisement of their stream, of about 7 seconds long.
When I use ExoPlayer, set it in the media.exolist.json as another item in the:
```
"name": "Misc",
    "samples":[....]
 ```
It plays this intro only.
However, when I use VLC player, it continues after into to the real stream itself.
I am asking of help to understand what type of stream is it and why VLC moves forward but ExoPlayer stops after 7 or so seconds.
Message that I see in the console from VLC player is:
```
Encountered more data after announced end of track (frame 372/372)
```
Thank you very much in advance.

**Comment by krocard** [comment]
`mediainfo` output for `http://stream.psychoradio.org:8000`:
```
General
Complete name                            : /tmp/stream.mp3
Format                                   : MPEG Audio
File size                                : 1.02 MiB
Duration                                 : 1 min 6 s // The duration I left curl run, not the actual content length
Overall bit rate mode                    : Constant
Overall bit rate                         : 128 kb/s
Writing library                          : LAME3.98
Comment                                  : Made with Sonic Foundry ACID 4

Audio
Format                                   : MPEG Audio
Format version                           : Version 1
Format profile                           : Layer 3
Duration                                 : 1 min 6 s // The duration I left curl run, not the actual content length
Bit rate mode                            : Constant
Bit rate                                 : 128 kb/s
Channel(s)                               : 2 channels
Sampling rate                            : 44.1 kHz
Frame rate                               : 38.281 FPS (1152 SPF)
Compression mode                         : Lossy
Stream size                              : 1.02 MiB (100%)
Writing library                          : LAME3.98
```

As it is a radio, the mp3 file never ends, nor has a significant duration.

But when I run it with the demo app (`adb shell am start -a com.google.android.exoplayer.demo.action.VIEW_LIST     --es uri_0 http://stream.psychoradio.org:8000`), it also only plays the 10 first second. The length seems to be set as the beginning of the file:
```
D/EventLogger: timeline [eventTime=0.50, mediaPos=0.00, window=0, period=0, periodCount=1, windowCount=1, reason=SOURCE_UPDATE
      period [9.72]
      window [durationMs=9.72, seekable=true, dynamic=false, live=false]
    ]
```

I'm not sure how to play such mp3 livestream. @marcbaechinger should dynamic/live to set on the window, or should it be detected from the media?

**Comment by ChernyshovYuriy** [comment]
Thank you guys for the investigation. I wouldn't bring it to you if I couldn't able to play it by VLC, for example. And since VLC can handle this, I thought why ExoPlayer can't.

**Comment by ojw28** [comment]
This normally happens when a streaming provider has simply concatenated a fixed duration MP3 file and an MP3 live stream together. This is not really a valid thing to do. The fixed duration MP3 file specifies where the media data ends in its header. ExoPlayer does not attempt to play beyond this point because correctly formatted MP3 files can (and sometimes do) have non-media data concatenated onto their ends after this specified end point. This is why playback stops.
