### ISSUE TITLE
How to get PCM audio stream ?

### ISSUE THREAD

**Issue by Lua12138** [google/ExoPlayer#8342]
Now I want to reprocess the played audio instead of outputting it directly. 

Therefore, is there any way for me to obtain the decoded PCM audio stream (the input audio format is uncontrollable, but it is all supported by ExoPlayer, such as AAC/MP3, etc.)? 

And ExoPlayer no longer continues to output audio.

**Comment by krocard** [comment]
If I understand correctly you want to process the audio after the it has been decoded and before it is played:

For example: AAC --decoder--> PCM ----[your custom preprocessor]---> PCM ---[AudioTrack]--> Sound waves

ExoPlayer supports this. You need to implement a custom [AudioProcessor](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/audio/AudioProcessor.java) and then inject it when constructing the `DefaultAudioSink`.

**Comment by krocard** [comment]
Please reopen if this does not answer your question.

**Comment by andrewlewis** [comment]
To add to Kevin's suggestion, you may want to consider using `TeeAudioProcessor` (see also #5416).

**Comment by Lua12138** [comment]
I tried it, and `TeeAudioProcessor` really met the demand. 

Now I have some other questions. Can I specify the specific format of PCM data obtained by this method, such as 8-bit or 16-bit or float, sample rate,  little-endian or big-endian?
