### ISSUE TITLE
Keep last frame of previous source when switching sources: Live DASH Widevine protected streams and L1 security level

### ISSUE THREAD

**Issue by vkoehler** [google/ExoPlayer#8345]
I use PlayerView.setKeepContentOnPlayerReset(true) option to keep last frame when switching between Live DASH Widevine protected streams.

Works as expected with Android Emulator API 29.

Doesn't work on below listed test devices. Black frame is shown when switching. Seems to be related to L1 security level used on test devices. When forcing test devices to L3 security level this option works as expected.

ExoPlayer version: 2.12.2
Device 1: Samsung SM-G973F, Android 10, 
Device 2: Amlogic DV6067Y HDMI Dongle, Android 9

**Comment by ojw28** [comment]
Although it's a slightly different case, the answer is the same as in https://github.com/google/ExoPlayer/issues/8196#issuecomment-738204570.
