### ISSUE TITLE
Playback stalls when playing broken H.264 stream

### ISSUE THREAD

**Issue by CatchupTVnet** [google/ExoPlayer#8346]
Playback stalls at 22 seconds, when playing this particular stream that I sent to dev.exoplayer@gmail.com in both an Amlogic android device, and in Bluestacks android emulator under Windows.

When the same stream is opened in other players like VLC the first 22 s of the segment is played twice, but then the rest of the segment is played so playback does not stall.

FFMPEG log is found below:

ffmpeg-20201209-7777e5119a-win64-static\bin\ffmpeg.exe -v error -i LINK -f null - 2>&1
[h264 @ 000001dec18f4140] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 000001dec18f4140] decode_slice_header error
[h264 @ 000001dec18f4140] no frame!
[h264 @ 000001dec18f4140] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 000001dec18f4140] decode_slice_header error
[h264 @ 000001dec18f4140] no frame!
[h264 @ 000001dec18f4140] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 000001dec18f4140] decode_slice_header error
[h264 @ 000001dec18f4140] no frame!
[h264 @ 000001dec18f4140] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 000001dec18f4140] decode_slice_header error
[h264 @ 000001dec18f4140] no frame!
[h264 @ 000001dec18f4140] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 000001dec18f4140] decode_slice_header error
[h264 @ 000001dec18f4140] no frame!
[h264 @ 000001dec18f4140] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 000001dec18f4140] decode_slice_header error
[h264 @ 000001dec18f4140] no frame!
[h264 @ 000001dec18f4140] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 000001dec18f4140] decode_slice_header error
[h264 @ 000001dec18f4140] no frame!
[h264 @ 000001dec18f4140] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 000001dec18f4140] decode_slice_header error
[h264 @ 000001dec18f4140] no frame!
[h264 @ 000001dec18f4140] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 000001dec18f4140] decode_slice_header error
[h264 @ 000001dec18f4140] no frame!
[h264 @ 000001dec18f4140] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 000001dec18f4140] decode_slice_header error
[h264 @ 000001dec18f4140] no frame!
[h264 @ 000001dec18f4140] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 000001dec18f4140] decode_slice_header error
[h264 @ 000001dec18f4140] no frame!
[h264 @ 000001dec18f4140] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 000001dec18f4140] decode_slice_header error
[h264 @ 000001dec18f4140] no frame!
[h264 @ 000001dec18f4140] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 000001dec18f4140] decode_slice_header error
[h264 @ 000001dec18f4140] no frame!
[h264 @ 000001dec18f4140] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 000001dec18f4140] decode_slice_header error
[h264 @ 000001dec18f4140] no frame!
[h264 @ 000001dec18f4140] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 000001dec18f4140] decode_slice_header error
[h264 @ 000001dec18f4140] no frame!
[h264 @ 000001dec18f4140] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 000001dec18f4140] decode_slice_header error
[h264 @ 000001dec18f4140] no frame!
[h264 @ 000001dec18f4140] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 000001dec18f4140] decode_slice_header error
[h264 @ 000001dec18f4140] no frame!
[h264 @ 000001dec18f4140] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 000001dec18f4140] decode_slice_header error
[h264 @ 000001dec18f4140] no frame!
[h264 @ 000001dec18f4140] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 000001dec18f4140] decode_slice_header error
[h264 @ 000001dec18f4140] no frame!
[h264 @ 000001dec18f4140] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 000001dec18f4140] decode_slice_header error
[h264 @ 000001dec18f4140] no frame!
[h264 @ 000001dec18f4140] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 000001dec18f4140] decode_slice_header error
[h264 @ 000001dec18f4140] no frame!
[h264 @ 000001dec18f4140] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 000001dec18f4140] decode_slice_header error
[h264 @ 000001dec18f4140] no frame!
[h264 @ 000001dec18f4140] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 000001dec18f4140] decode_slice_header error
[h264 @ 000001dec18f4140] no frame!
[h264 @ 000001dec18f4140] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 000001dec18f4140] decode_slice_header error
[h264 @ 000001dec18f4140] no frame!
[h264 @ 000001dec1e0b7c0] cabac decode of qscale diff failed at 59 17
[h264 @ 000001dec1e0b7c0] error while decoding MB 59 17, bytestream -5

**Comment by krocard** [comment]
`mediaInfo` output:
```
General
ID                                       : 1 (0x1)
Complete name                            : /tmp/8346.ts
Format                                   : MPEG-TS
File size                                : 12.4 MiB
Overall bit rate mode                    : Variable

Video
ID                                       : 256 (0x100)
Menu ID                                  : 1 (0x1)
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : Main@L3.1
Format settings                          : CABAC / 1 Ref Frames
Format settings, CABAC                   : Yes
Format settings, Reference frames        : 1 frame
Codec ID                                 : 27
Bit rate mode                            : Variable
Maximum bit rate                         : 1 200 kb/s
Width                                    : 960 pixels
Height                                   : 540 pixels
Display aspect ratio                     : 16:9
Frame rate                               : 25.000 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive

Audio
ID                                       : 257 (0x101)
Menu ID                                  : 1 (0x1)
Format                                   : AAC LC
Format/Info                              : Advanced Audio Codec Low Complexity
Format version                           : Version 4
Muxing mode                              : ADTS
Codec ID                                 : 15-2
Bit rate mode                            : Variable
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 46.875 FPS (1024 SPF)
Compression mode                         : Lossy
Delay relative to video                  : -128 ms

Menu
ID                                       : 4096 (0x1000)
Menu ID                                  : 1 (0x1)
List                                     : 256 (0x100) (AVC) / 257 (0x101) (AAC)
Service name                             : Service01
Service provider                         : FFmpeg
Service type                             : digital television
```

I can reproduce the issue. No error is logged but playback stops after 22 seconds. Log at 22s:
```
D/AudioTrack: stop(37): called with 1044480 frames delivered
D/EventLogger: droppedFrames [eventTime=22.71, mediaPos=21.82, window=0, period=0, 1296]
D/PipelineWatcher: onInputBufferReleased: frameIndex not found (553); ignored
D/CCodecBufferChannel: [c2.qti.avc.decoder#865] Discard frames from previous generation.
I/chatty: uid=10245(com.google.android.exoplayer2.demo) CodecLooper identical 3 lines
D/CCodecBufferChannel: [c2.qti.avc.decoder#865] Discard frames from previous generation.
W/Codec2Client: query -- param skipped: index = 1342179345.
    query -- param skipped: index = 2415921170.
    query -- param skipped: index = 1610614798.
D/CCodecBufferChannel: [c2.qti.avc.decoder#865] Discard frames from previous generation.
D/PipelineWatcher: onInputBufferReleased: frameIndex not found (586); ignored
W/Codec2Client: query -- param skipped: index = 1342179345.
W/Codec2Client: query -- param skipped: index = 2415921170.
    query -- param skipped: index = 1610614798.
D/CCodecBufferChannel: [c2.qti.avc.decoder#865] Discard frames from previous generation.
I/chatty: uid=10245(com.google.android.exoplayer2.demo) CodecLooper identical 3 lines
D/CCodecBufferChannel: [c2.qti.avc.decoder#865] Discard frames from previous generation.
D/EventLogger: droppedFrames [eventTime=22.83, mediaPos=21.94, window=0, period=0, 34]
D/EventLogger: state [eventTime=22.83, mediaPos=21.94, window=0, period=0, ENDED]
D/EventLogger: isPlaying [eventTime=22.83, mediaPos=21.94, window=0, period=0, false]
```

There is something weird at the beginning though, the length of the window is negative:
```
D/EventLogger: timeline [eventTime=0.66, mediaPos=0.00, window=0, period=0, periodCount=1, windowCount=1, reason=SOURCE_UPDATE
      period [-6020.72]
      window [durationMs=-6020.72, seekable=true, dynamic=false, live=false]
```

@AquilesCanta, could you take a look at this MPEG-TS media. Even if we do not want to be support it, we might want to throw an exception or at least log when the length do not match.

**Comment by ojw28** [comment]
Given the media is malformed, I don't think it's worth investigating this in any detail. We should fix the negative window length though (by setting it to `TIME_UNSET` instead). I'll make that change and then close this.
