### ISSUE TITLE
Video stops for a few seconds before playing the next video in concatenatingmediasource

### ISSUE THREAD

**Issue by pawaom** [google/ExoPlayer#8348]
I have a list of 3 videos say a,b,c,

when playing the videos one after other, there is some delay of atleast 1 second or so, before playing the next video for example,
when video a, has played, and next video "b" has to start, it takes a few seconds then it plays.

can we avoid this delay.

Or is there a way to know when the next video has started to play,I wan to update the UI based on this,

I know of onTracksChanged  and onPositionDiscontinuity but this just checks the change in index, how do we know the next video has started to play.

I think the delay is expected behavior, my problem is the last frame gets stuck of the previous video till the next video starts, which also should be the expected behavior, so the question would be **how do we know the next video has started playing**

the problem is I show the title of the video being played below it, so now when the next video should start the title gets updated, but the frame that we see is the last frame (or in case we moved to the next video using the next button manually that particular frame for 1-2 seconds). I want to synchronize this process.  

I have noticed the defaulttimebar  pauses for a few moments before it starts to update, can that be helpful

I tried a few things, to delay the update of text for a few seconds, but then the problem was the video used to be updated earlier some times but the text didn't match the video(there is no confirm duration for which the delay in video occurs)

**Comment by krocard** [comment]
`EventListener.onMediaItemTransition` is what you should override to change the title. Nevertheless, if this delay is due to ExoPlayer buffering the video, I believe it will be called before the first frame is rendered.

Without an example playlist, we can not confirm if this delay is due to video buffering.

During this delay, is ExoPlayer state `BUFFERING`? If so, your UI should show a spinner showing that the next video is loading but not yet ready.

@ojw28 what is the best way for a UI to know that the first frame of a video has been rendered to update its metadata?

**Comment by pawaom** [comment]
The videos are from the SD card, not being downloaded, so I don't think it will be buffering 

I have tried onMediaItemTransition ,  onTracksChanged, and onPositionDiscontinuity, Player.STATE_BUFFERING,Player.STATE_READY , but every time there is some delay.how do we manage this and syncronize 

Is there a way to know when the  frame is rendered (example if user goes to next video from video a yo video b, can we know when frome from video b is rendered, and vice versa)

**Comment by krocard** [comment]
Without better understanding where this delay comes from, it's difficult to help you further.

Could you please share the media you are trying to play and a bug report taken just after this media transition delay.

If you're unable to share [bug reports](https://developer.android.com/studio/debug/bug-report) or
test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format
"Issue #1234" ("#1234" is replaced with your issue number). Please also update this issue to
indicate you've done this.

**Comment by krocard** [comment]
> playing the next video in concatenatingmediasource

It is probably unrelated to your issue, but we encourage developers to use `Player.addMediaItem` rather than the lower level `ConcatenatingMediaSource`.

**Comment by pawaom** [comment]
I will try Player.addMediaItem and get back to you

**Comment by pawaom** [comment]
the real problem is when we move from one video to another, there is a slight delay till the frame of the new video is rendered, If we can capture this change wen can manage the things that we want to do, can we capture this change.

**Comment by krocard** [comment]
`VideoListener.onRenderedFirstFrame` could be a solution to you issue, but I'm really wondering what causes this delay. Video transitions should not be so long as to be visible to the user.
@ojw28 do you have an advice?

**Comment by pawaom** [comment]
thanks for the help VideoListener.onRenderedFirstFrame is helpful but still there is a delay of about 500ms similar to this issue

https://github.com/google/ExoPlayer/issues/2533

**Comment by pawaom** [comment]
can we render FirstFrame after a certain duration, so that we can manage these changes

**Comment by krocard** [comment]
> thanks for the help VideoListener.onRenderedFirstFrame is helpful but still there is a delay of about 500ms similar to this issue
Is the listener called 500ms too late? Your device is maybe slowed significantly by the decoding start. Is it an old android device?

@pawaom without more information about what is causing the delay we can not help you further. Please provide us with the media files/streams you are trying to play and well as a bug report taken after the delay.

If you're unable to share [bug reports](https://developer.android.com/studio/debug/bug-report) or
test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format
"Issue #1234" ("#1234" is replaced with your issue number). Please also update this issue to
indicate you've done this.

**Comment by pawaom** [comment]
> > thanks for the help VideoListener.onRenderedFirstFrame is helpful but still there is a delay of about 500ms similar to this issue
> > Is the listener called 500ms too late? Your device is maybe slowed significantly by the decoding start. Is it an old android device?
> 
> @pawaom without more information about what is causing the delay we can not help you further. Please provide us with the media files/streams you are trying to play and well as a bug report taken after the delay.
> 
> If you're unable to share [bug reports](https://developer.android.com/studio/debug/bug-report) or
> test content publicly, please send them to [dev.exoplayer@gmail.com](mailto:dev.exoplayer@gmail.com) using a subject in the format
> "Issue #1234" ("#1234" is replaced with your issue number). Please also update this issue to
> indicate you've done this.

the device has 2gb ram , is just a year old, I am not able to produce a bug report but this approach mentioned in 

https://github.com/google/ExoPlayer/issues/2533#issuecomment-292556170

` Maybe if we were to report the presentation timestamp of the rendered frame via onRenderedFirstFrame, you'd be able to compare that against the current playback position.`

may be helpful, please consider this as an enhancement.

**Comment by ojw28** [comment]
I don't think this issue warrants further attention until sufficient information is provided to allow us to investigate it efficiently. Given the information has been requested repeatedly and not provided, I'll go ahead and close this on the assumption that it's not going to be provided. If you are able to provide it, please feel free to reply here with the requested information, and we'll reopen the issue. Thanks!
