### ISSUE TITLE
Maven unable to resolve 2.12.x exoplayer-core dependencies

### ISSUE THREAD

**Issue by space-pope** [google/ExoPlayer#8353]
Gradle seems to have no problem downloading ExoPlayer, but I maintain a Java library that uses Maven for dependency management, and the following dependency:

```xml
      <dependency>
         <groupId>com.google.android.exoplayer</groupId>
         <artifactId>exoplayer-core</artifactId>
         <version>2.12.2</version>
         <type>aar</type>
         <scope>provided</scope>
      </dependency>
```

produced the following error during `mvn compile` (or any other task that pulls dependencies):

```
The following artifacts could not be resolved: com.google.android.exoplayer:exoplayer-common:jar:2.12.2, com.google.android.exoplayer:exoplayer-extractor:jar:2.12.2
```

I could see via bintray's web interface that the files are there, so I dug further. This appears to be related to the pom files generated by Gradle. I can fix the problem by:

1. Editing the exoplayer-core pom file downloaded by Maven, adding the `<type>aar</type>` line to its exoplayer-common and exoplayer-extractor dependencies
2. Removing exoplayer-common and exoplayer-extractor directories from my local repository (so Maven doesn't think they're cached)
3. Rerunning the Maven task
4. Editing the newly downloaded exoplayer-extractor pom file, again adding `<type>aar</type>` to its exoplayer-common dependency
5. Running the Maven task one last time

I would expect having `<packaging>aar</packaging>` under the `project` element (as ExoPlayer poms do) to address this problem, but apparently not, at least for runtime-scoped dependencies.

Note that I didn't have this problem with 2.11.x—`exoplayer-core` doesn't have runtime dependencies on the other libraries in that version.

**Comment by tonihei** [comment]
We added an internal dependency in 2.12.0 from `core` to `common` and `extractor`. In Gradle this should be resolved automatically as you noted. I'm not sure who's creating the pom files you are using here and whether it's expected that they contain dependency information. @ojw28 might know more about this.

**Comment by ojw28** [comment]
I guess this is the same issue as @andrewlewis on the bintray-release project in https://github.com/novoda/bintray-release/issues/212. We might just solve it by migrating away from bintray-release, which we need to do anyway for other reasons.

**Comment by andrewlewis** [comment]
I had thought that our migration to maven-publish would fix this but actually it appears `<type>aar</type>` is still missing from the dependency declarations. There is a workaround mentioned in https://github.com/gradle/gradle/issues/3170#issuecomment-544248344.

**Comment by space-pope** [comment]
Is there any update to share on this? I'm still unable to locate exoplayer-common via maven as of version 2.14.1.

**Comment by andrewlewis** [comment]
There aren't any updates I'm afraid.

**Comment by tonihei** [comment]
The commit above will work around the issue in future releases.
