### ISSUE TITLE
Question: The different meaning of the concept 'bypass', 'passthrough' and 'tunneling' in ExoPlayer

### ISSUE THREAD

**Issue by Romantic-LiXuefeng** [google/ExoPlayer#8354]
When reading the source code of video render and audio render, I'm confused with the meaning of the concept 'bypass', 'passthrough' and 'tunneling'. Hope give some explain 

-  What's the different between these?
- And what are their specific usage scenarios？

**Comment by krocard** [comment]
audio passthrough and video tunneling are described in https://exoplayer.dev/glossary.html.

bypass is an internal concept of the MediaCodecRenderer and means that the MediaCodec decoding is not used aka bypassed. The sampleQueue buffers are directly played without being decoded by MediaCodec.

bypass mode is used for audio passthrough and audio offload.
