### ISSUE TITLE
2160p60 playback performance on slow CPU

### ISSUE THREAD

**Issue by CiNcH83** [google/ExoPlayer#8358]
I just finished profiling 2160p60 playback on a slow Sony BRAVIA X900F using different SmartTubeNext/ExoPlayer versions with different MediaCodec operational modes (sync/async).

Device: Sony BRAVIA KD-65XF9005 (X900F)
SoC: MediaTek MT5891 ([MT5596](https://www.mediatek.com/products/digitaltv/mt5596))
CPU: 4X ARM Cortex A53 @ 1GHz
OS: Android TV 9 (Kernel 4.9.125)
Player: SmartTubeNext
Video: [The World in HDR in 4K](https://www.youtube.com/watch?v=tO01J-M3g0U) (17mbps @ 1440p60; 30mbps @ 2160p60)

### Amazon ExoPlayer 2.10.6

**2160p60** (4K/UHD)
There is slight micro-stuttering every few seconds which is mostly visible in panning shots. CPU usage is close to 100% when this happens. No frames are being dropped. So the problem might be VSync timing related and happen at the last stage inside the SurfaceFlinger.
There is lots of frame dropping when browsing recommendations on top of the playing video. As soon as ExoPlayer finishes downloading towards the end of the clip, rendering becomes smooth, even when browsing recommendations on top of the playing video. CPU usage drops considerably. So I assume that the streaming and rendering threads are fighting for resources. 

2X speed exhibits extreme frame dropping and bad stuttering.

**1440p60** (2K/QHD)
Video playback is perfectly fine. CPU usage never goes high enough to cause stuttering. There is hardly any frame dropping when browsing recommendations on top of the playing video.

2X speed exhibits extreme frame dropping and bad stuttering.

### Google ExoPlayer 2.12.1
_Mode: `OPERATION_MODE_SYNCHRONOUS`_

**2160p60** (4K/UHD)
Heavy stuttering happens in the beginning due to very high CPU usage. Initial buffering seems to be more resource intensive than with ExoPlayer 2.10.6. Playback also suffers a bit more from the recurring micro-stuttering.
There is lots of frame dropping when browsing recommendations on top of the playing video.

2X speed exhibits extreme frame dropping and bad stuttering.

**1440p60** (2K/QHD)
Video playback is perfectly fine. CPU usage never goes high enough to cause stuttering. There is hardly any frame dropping when browsing recommendations on top of the playing video.

2X speed exhibits extreme frame dropping and bad stuttering.

### Google ExoPlayer 2.12.1
_Mode: `OPERATION_MODE_ASYNCHRONOUS_DEDICATED_THREAD_ASYNCHRONOUS_QUEUEING`_

Pretty similar to `OPERATION_MODE_SYNCHRONOUS`. Async MediaCodec does not seem to have an impact.

### Google ExoPlayer 2.12.1
_Mode: `OPERATION_MODE_ASYNCHRONOUS_DEDICATED_THREAD`_

Same as `OPERATION_MODE_ASYNCHRONOUS_DEDICATED_THREAD_ASYNCHRONOUS_QUEUEING`.

### Conclusion

ExoPlayer 2.10.6 seems better than 2.12.1, especially the first few seconds of playback. The MediaCodec modes do not seem to be having a real impact. Hopefully they are properly being applied, [see code](https://github.com/yuliskov/SmartTubeNext/blob/d15826b15f50e5ec595890fa20e6812375880529/common/src/main/java/com/liskovsoft/smartyoutubetv2/common/exoplayer/other/V3/CustomOverridesRenderersFactory.java#L33).

2160p60 suffers from recurring micro-stuttering on BRAVIA due to playback exhausting the slow CPU at times. Streaming high bitrate content (30mbps isn't exactly high though...) seems to have quite an impact on CPU usage. Also quite some frames get dropped when browsing recommendations on top of the playing video. 1440p60 is fine already (which is half the bitrate). 2160p60 is also fine after the clip has finished downloading. So it clearly looks like streaming and rendering threads are fighting for resources. The original YouTube app suffers in pretty much the same way.

**Comment by tonihei** [comment]
The new media codec operating modes are mostly targeted towards DRM protected playbacks. If the video you are playing is unprotected, it wouldn't be unsurprising you can't see a noticeable difference when testing on a single device. 

Generally it sounds as if 2160@60fps is just too much for this device, especially if other things need to be done in the background (like loading media.).

@christosts may have more details to add.

**Comment by CiNcH83** [comment]
Thanks for your response!

> If the video you are playing is unprotected

Yes. I am talking about the non-protected YouTube videos shared via their social media platform, see [The World in HDR in 4K](https://www.youtube.com/watch?v=tO01J-M3g0U).

> Generally it sounds as if 2160@60fps is just too much for this device

Even though a quad ARM Cortex A53 is still a standard CPU for Android TV, running it at only 1GHz might indeed be a problem here. Plus the fact that the SoC is a MediaTek. I am not sure how good their MediaCodec implementation and networking drivers are. Transferring data over network indeed stresses the CPU quite a bit.

Really sad that Sony has been deploying this chip to all 4K HDR BRAVIAs between 2016 and 2019, so for 4 model years (parts of XD, XE, XF and parts of XG). I however tested YouTube 2160p60 playback on a 2020 BRAVIA XG95 with 4X ARM Cortex A73 1.5GHz in a store about a year ago and found those 2160p60 videos also to be suffering from the seemingly VSync timing related slight micro-stuttering every few seconds. It suffered less from frame dropping though.

**Comment by christosts** [comment]
Thank you for your analysis.

> The MediaCodec modes do not seem to be having a real impact. Hopefully they are properly being applied, [see code](https://github.com/yuliskov/SmartTubeNext/blob/d15826b15f50e5ec595890fa20e6812375880529/common/src/main/java/com/liskovsoft/smartyoutubetv2/common/exoplayer/other/V3/CustomOverridesRenderersFactory.java#L33).

I think the code sample is enabling the asynchronous mode only for the video rendering part, can you please try enabling for both audio and video? Eg

```
experimentalSetVideoMediaCodecOperationMode(MediaCodecRenderer. OPERATION_MODE_ASYNCHRONOUS_DEDICATED_THREAD_ASYNCHRONOUS_QUEUEING);
experimentalSetAudioMediaCodecOperationMode(MediaCodecRenderer. OPERATION_MODE_ASYNCHRONOUS_DEDICATED_THREAD_ASYNCHRONOUS_QUEUEING);
```
or for convenience
```
experimentalSetMediaCodecOperationMode(MediaCodecRenderer. OPERATION_MODE_ASYNCHRONOUS_DEDICATED_THREAD_ASYNCHRONOUS_QUEUEING);
```

Also, it'd be useful to see the codecs used for the specific file (not sure which encoding of the video file is reaching your device). Will you be able to attach an `EventLogger` to the player and copy the tracks information from the logcat?

**Comment by CiNcH83** [comment]
Thanks @christosts for your response!

> I think the code sample is enabling the asynchronous mode only for the video rendering part, can you please try enabling for both audio and video?

[Tried](https://github.com/yuliskov/SmartTubeNext/commit/a47738ffe77dc04f44c38649b3acf5bb6d9540f0), but didn't help. Heavy stuttering in the beginning due to continuously high CPU load. Lots of frames get dropped. CPU load stabilizes after several seconds. There are still spikes every few seconds which cause micro-stuttering (no frames get dropped anymore though).

> Also, it'd be useful to see the codecs used for the specific file (not sure which encoding of the video file is reaching your device).

YouTube 4K streams are always VP9/VP9.2 (AV1 is not supported by the BRAVIA).

```
Video: VP9.2 (HDR10), 3840x2160, 59.940fps, 29.6mbps
Audio: AAC LC, 2CH, 44.1kHz, 128kbps
```


---
Just FYI, VLC has the most efficient video pipeline on Android (native app using NDK MediaCodec). CPU usage never comes even close to 100% on BRAVIA when playing back 2160p60 streams. It is in fact half idle. Even 80mbps HEVC plays fine via DLNA. I also downloaded [The World in HDR](https://www.youtube.com/watch?v=tO01J-M3g0U) (VP9.2 30mbps 2160p60) using youtube-dl(+ffmpeg) and played it back via DLNA in VLC. Playback is perfectly fine. So the CPU should be potent enough for playing back big streams over network. It is just a matter of how well playback engines are optimized. Most aren’t enough.

**Comment by christosts** [comment]
Thank you for the information. 

I took a closer look at your code sample and I see your renderer factory is also overriding `buildAudioRenderers()` and `buildVideoRenderers()`. The code is replacing the MediaCodec audio and video renderers with custom ones. However, the MediaCodec operation modes need to be passed down to the MediaCodecVideoRenderer and MediaCodecAudiorRenderer instances, and I think the code does not do it at the moment (at least on the link you posted before). You should be able to set the operation mode on `AudioDelayMediaCodecAudioRenderer` and `FrameDropFixMediaCodecVideoRenderer`. 

When playback starts, you should see [this line](https://github.com/google/ExoPlayer/blob/r2.12.1/library/core/src/main/java/com/google/android/exoplayer2/mediacodec/MediaCodecRenderer.java#L1135) being executed in the MediaCodec audio/video renderers when they initialize the MediaCodec internally.

Can you please verify the operation mode is passed down the MediaCodecRenderers correctly?
