### ISSUE TITLE
Missing segments at the end of the period are perhaps incorrectly considered a playback failure

### ISSUE THREAD

**Issue by sandersaares** [google/ExoPlayer#836]
I have a video here that "fails" near the end with a 404. It plays fine most of the video but when playing the last half minute of the video, we run into this:

    10-02 10:52:28.514: E/BasePlayerController(25561): onLoadError: Response code: 404

Video URL: http://media.axprod.net/ExoPlayer/Multisdk/Clear/manifest.mpd

The 404 comes from the 223rd video segment, which does not exist. ExoPlayer gets a 404 and then immediately signals the error to the app and closes up shop.

Running the timing numbers tells me that there should be 223 segments for all adaptation sets. The audio duration is a bit less than the duration of the others (3.989s VS 4s) but it still comes out to 223 total. In practice, however, there are only 222 segments in the video stream.

Now, the spec purist in me immediately says "Hey, DASH does not allow missing segments unless you are using `SegmentTimeline`, so fix your video". Unfortunately, this situation - uneven adaptation sets, with some being shorter than the period - is very common with VOD content produced by the various available encoders. Therefore, I would expect players to be more lenient here and ignore missing segments. This is what dash.js does, for example - it plays the segments that exist and simply ignores the ones that are missing in the end, without signaling a failure.

A different but related scenario is live video, where missing segments are a common thing that occurs when network disruptions happen between the encoder and the origin server. I have not tested ExoPlayer with regard to this scenario but maybe it is worth tackling two birds with one stone and ensuring that ExoPlayer does its best to skip past missing segments in all scenarios.

**Comment by Bastian35022** [comment]
I faced the issue of missing segments with live content before. The ExoPlayer then performes the configured number of requests for the missing segment, and exits afterwards. It would be great to support skipping segments in that case.

**Comment by ojw28** [comment]
Could you specify exactly which of the "various available encoders" exhibit this issue for VOD content? Thanks.

**Comment by sandersaares** [comment]
This is confirmed to occur with the [mp4box](https://github.com/gpac/gpac) packager. We have also seen it with various customer content of unknown origin and in our testing with various different products. I do not have a list nor do I remember the specific ones affected, though.

See also discussion here: https://github.com/gpac/gpac/issues/360#issuecomment-170904967

**Comment by sandersaares** [comment]
Quick update: there are attempts to raise the topic in MPEG for clarification of what is "the right way" but from what I see right now, CMAF will explicitly state that samples must be provided for the entire timeline, so possibly this issue is becoming less relevant as 404s get even more officially relegated to the "broken content" category.

**Comment by ojw28** [comment]
Thanks for the update. Does this issue still occur with mp4box, or has that been resolved?

**Comment by sandersaares** [comment]
The issue still occurs with mp4box.

**Comment by ojw28** [comment]
@erdemguven - It's probably rather easy to handle this in 2.x (`DashChunkSource.onChunkLoadError` could probably handle the error, and then when a subsequent call comes into `DashChunkSource.getNextChunk` requesting the final chunk - we could instead return endOfStream).

**Comment by ojw28** [comment]
Fixed in `dev-v2`, which is the V2 development branch.
