### ISSUE TITLE
How to viewBinding of PlayerView's controller layout

### ISSUE THREAD

**Issue by javaing** [google/ExoPlayer#8369]
Using ViewBinding, 
but I dont konw how to binding PlayerView's  custom controller layout

<com.google.android.exoplayer2.ui.PlayerView
                android:id="@+id/player_view"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                **app:controller_layout_id**="@layout/layout_player_mask"/>

onCreate()
binding = ActivityVideoRoomBinding.inflate(layoutInflater)
// This method is not work
//bindingLayoutPlayerMask = LayoutPlayerMaskNewBinding.inflate(layoutInflater)
//This method still not work
bindingLayoutPlayerMask = binding.playerView. ?

//gradle
ext.exo_version = '2.12.2'
compileSdkVersion 28
    buildFeatures {
        dataBinding true
        viewBinding true
    }
Android Studio 4.1.1

Thanks in advance

**Comment by javaing** [comment]
I try this way , work for me now

```
val videoControlView = binding.root.findViewById<View>(R.id.custom_layout)
bindingLayoutPlayerMask = DataBindingUtil.bind(videoControlView)!!
```

**Comment by tonihei** [comment]
I'm not sure I understand your original problem, but glad you found a solution yourself. Closing this issue as I think there is nothing else for us to do here.
