### ISSUE TITLE
Unable to play widevine encrypted CMAF HLS stream

### ISSUE THREAD

**Issue by SharanKumarReddyKambham** [google/ExoPlayer#8372]
Hi Team,

Playback is not happening when I play DRM+HLS+CMAF encrypted content.

The content is generated by shaka-packager with widevine encryption. I tried different types of protection schemes such as cenc,cbcs but none of them played and the player got stuck in the 'BUFFERING' state.

**Observation**

When I generate content with **cenc** the manifest shows

> "#EXT-X-KEY:METHOD=SAMPLE-AES-CTR"

with **cbcs** it shows 

> "#EXT-X-KEY:METHOD=SAMPLE-AES"

 [Supported formats](https://exoplayer.dev/supported-formats.html) - As per the link, Exoplayer doesn't support SAMPLE-AES-128. 

How can we play the DRM+HLS+CMAF encrypted content? Is there anything we have to consider while generating the content or missing something?

Bug Report attached: [drm_report.log](https://github.com/google/ExoPlayer/files/5715616/drm_report.log)

We checked in Android Pie Device (API 28)

**Comment by tonihei** [comment]
Your attached logs show two DRM-protected playbacks with the demo app that seemed to have worked fine based on the EventLogger output. 

If you want us to investigate further, it would be helpful if you could provide a test stream and/or logs that show the problem. In case you don't want to post the stream publicly, you can send an email to exoplayer.dev@gmail.com with "Issue #8372" in the subject and then report back here that you've send the stream url.

**Comment by SharanKumarReddyKambham** [comment]
Hi @tonihei I ve shared the test content via exoplayer.dev@gmail.com, please use that content to reproduce the issue,the content is generated using widevine test credentials.

We are testing the content in Realme and Nvidia shield devices.

**Comment by tonihei** [comment]
Thanks for reporting! I can reproduce the issue.

My initial investigation shows that playback is stuck in a buffering state because the loading thread is indefinitely blocked on `timestampAdjuster.waitUntilInitialized()` in `HlsMediaChunk`.  Note that this only happens when you try to play past the discontinuity. For example seeking to a later position in the stream works just fine. Not sure if this is because the media is somehow broken or whether this is a bug in ExoPlayer. But even for broken media, we shouldn't end up blocking forever without an error. 

@christosts  Do you want to take a look because it's an HLS issue?

**Comment by tonihei** [comment]
The root cause for getting stuck looks the same as in #6896. In this case it's audio track though and it's not the final segment, so may as well be unrelated.

**Comment by SharanKumarReddyKambham** [comment]
Hi Team, We observed that playback is happening with 720p CMAF content, but unable to play with 1080p.

**Comment by AquilesCanta** [comment]
I suspect the issue is caused by the lack of discontinuity alignment. The discontinuity in the video variant happens at t=16s and in audio at t=6s. The audio loading cannot continue because it waits for timestamp adjustment initialization by the video variant, but the video variant does not load because the CompositeSequenceableLoader sees the video's next load position is further ahead in time.

I will continue investigation next week and see what the best next steps are.

**Comment by SharanKumarReddyKambham** [comment]
Hi,

@AquilesCanta any update on this,we are struck at this issue.

**Comment by AquilesCanta** [comment]
Hi, we won't be able to look into this until mid-February unfortunately. A few actionable items you can take on to push this forward:
- We would like to know a bit more how the content was generated. That is, could you provide us with instructions on how to generate similar content using shaka packager?
- I would also suggest generating equivalent content with a MacOS-supported DRM scheme, so as to evaluate playback with quick time, to ensure it's doing what you expect it to do, and not something like audio and video out of sync.

The problem we currently have is that the content discontinuities are not aligned. I haven't found anything in the spec forbidding it, but at the same time I struggle to imagine a real world scenario where it makes sense to have non-aligned discontinuities.

**Comment by SharanKumarReddyKambham** [comment]
Hi @AquilesCanta ,

We are using the following command to generate the content  using shaka packager

> packager 'in=llama_3_original.mp4,stream=video,init_segment=init_v.mp4,segment_template=v_$Number$.m4s' 'in=/home/gaian/llama_3_original.mp4,stream=audio,init_segment=init_a.mp4,segment_template=a_$Number$.m4s' --enable_widevine_encryption --key_server_url https://license.uat.widevine.com/cenc/getcontentkey/widevine_test  --content_id 7465737420636f6e74656e74206964 --signer widevine_test --aes_signing_key 1ae8ccd0e7985cc0b6203a55855a1034afc252980e970ca90e5202689f947ab9  --aes_signing_iv d58ce954203b7c9a9a9d467f59839249 --hls_master_playlist_output h264_master.m3u8

**Comment by AquilesCanta** [comment]
Hi @SharanKumarReddyKambham, would you kindly provide us with a copy of llama_3_original.mp4? That way we can look into why the content is being generated with a strange structure. We are not yet convinced this is worth fixing in the ExoPlayer codebase. You can either post it here, or send it to dev.exoplayer@gmail.com. Discussed with @christosts and we agreed we would try to decide whether this content is valid, or perhaps a bug in shaka-packager, in which case we might want to contact the shaka team.

**Comment by SharanKumarReddyKambham** [comment]
Hi @AquilesCanta ,i ve shared the content over mail,please check and update.
