### ISSUE TITLE
Zooming problem with hls live stream

### ISSUE THREAD

**Issue by anupdey99** [google/ExoPlayer#8376]
When working with HLS streaming playerview is not zooming.
I use 
```
videoScalingMode = Renderer.VIDEO_SCALING_MODE_SCALE_TO_FIT_WITH_CROPPING
app:resize_mode="zoom"
app:surface_type="texture_view"
```

Stream Event Logs

```
D/EventLogger: timeline [eventTime=0.25, mediaPos=0.00, window=0, periodCount=1, windowCount=1, reason=PLAYLIST_CHANGED
D/EventLogger:   period [?]
D/EventLogger:   window [?, false, true]
D/EventLogger: ]
D/EventLogger: mediaItem [eventTime=0.25, mediaPos=0.00, window=0, reason=PLAYLIST_CHANGED]
D/EventLogger: state [eventTime=0.25, mediaPos=0.00, window=0, BUFFERING]
D/EventLogger: surfaceSize [eventTime=0.25, mediaPos=0.00, window=0, 1046, 688]
D/EventLogger: playWhenReady [eventTime=0.25, mediaPos=0.00, window=0, true, USER_REQUEST]
D/EventLogger: loading [eventTime=0.29, mediaPos=0.00, window=0, period=0, true]
D/EventLogger: timeline [eventTime=1.28, mediaPos=0.00, window=0, period=0, periodCount=1, windowCount=1, reason=SOURCE_UPDATE
D/EventLogger:   period [58.27]
D/EventLogger:   window [58.27, true, false]
D/EventLogger: ]
D/EventLogger: videoEnabled [eventTime=1.32, mediaPos=0.00, window=0, period=0]
D/EventLogger: audioEnabled [eventTime=1.33, mediaPos=0.00, window=0, period=0]
D/EventLogger: tracks [eventTime=1.33, mediaPos=0.00, window=0, period=0
D/EventLogger:   MediaCodecVideoRenderer [
D/EventLogger:     Group:0, adaptive_supported=N/A [
D/EventLogger:       [X] Track:0, id=0, mimeType=video/avc, bitrate=818576, codecs=avc1.4D401E, res=540x360, fps=30.0, supported=YES
D/EventLogger:     ]
D/EventLogger:     Metadata [
D/EventLogger:       HlsTrackMetadataEntry
D/EventLogger:     ]
D/EventLogger:   ]
D/EventLogger:   MediaCodecAudioRenderer [
D/EventLogger:     Group:0, adaptive_supported=N/A [
D/EventLogger:       [X] Track:0, id=0, mimeType=audio/mp4a-latm, codecs=mp4a.40.2, supported=YES
D/EventLogger:     ]
D/EventLogger:     Metadata [
D/EventLogger:       HlsTrackMetadataEntry
D/EventLogger:     ]
D/EventLogger:   ]
D/EventLogger:   TextRenderer []
D/EventLogger:   MetadataRenderer [
D/EventLogger:     Group:0, adaptive_supported=N/A [
D/EventLogger:       [X] Track:0, id=ID3, mimeType=application/id3, supported=YES
D/EventLogger:     ]
D/EventLogger:   ]
D/EventLogger:   CameraMotionRenderer []
D/EventLogger: ]
```

![Screenshot_1608360248](https://user-images.githubusercontent.com/17586034/102683052-4d545780-41f8-11eb-8996-ca83733445e4.png)

I tested with mp4 file, its zoom to fill the rectangle shape.
Need some help with this issue

**Comment by marcbaechinger** [comment]
I tested with the demo app. I changed layout element of the `PlayerView` 200x200dp like this:

```
<com.google.android.exoplayer2.ui.PlayerView android:id="@+id/player_view"
      android:layout_width="200dp"
      android:layout_height="200dp"
      android:background="@android:color/holo_blue_dark"
      android:layout_gravity="center"
      app:surface_type="texture_view"
      app:resize_mode="zoom"
      app:use_controller="false"/>
```

Without setting a specific `resize_mode` it gives me the video scaled to the size of the player view which gives the typical letter box view with some areas left out at the top and bottom. As expected it fits the whole video into the available space by maintaining aspect ratio. When I switch the resize mode to `zoom` like in the snippet above, the video is rendered in correct aspect ratio with a squared view port of 200x200dp like the view itself and the margins of the video at the right and left are cropped away (see screenshot below). This is also what I would expect. The behavior is the same with mp4 or HLS (or any other formats I tried). So I think this works as I would expect it with HLS or other formats.

If you think that does not work for you, please provide full information of your `PlayerView` xml element with all the attributes and explain what your expectations are and what the observed behavior is. Best is if you also provide us with a test stream to your HLS.

![image](https://user-images.githubusercontent.com/584321/103311861-58d32a00-4a13-11eb-8e54-ec8a9d3812b2.png)
