### ISSUE TITLE
Incorrect timecode handling for Smooth Streaming when 'tfdt' is present

### ISSUE THREAD

**Issue by barbibulle** [google/ExoPlayer#838]
When playing a Smooth Streaming presentation where the fragmented MP4 segments contain a timecode ('tfdt' box), the internal timecode computation gets confused and A/V synchronization does not work properly (the 'tfdt' timecode gets added to the segment start time).
While most Smooth Streaming media comes without 'tfdt' boxes, some media does have it (for example, media that's packaged to target both Smooth Streaming clients as well as MPEG DASH clients, since MPEG DASH requires 'tfdt' to be present). The Smooth Streaming spec from Microsoft remains silent on 'tftd' boxes (neither requires it nor forbids it), so it seems that such a stream (supporting both DASH and Smooth) should be valid (and desirable).
[all other Smooth Streaming clients tested support streams with 'tfdt' without any problem]

The simplest way to support this may be to have a policy that when a 'tfdt' timestamp is found, it should *override*, rather than be added to, the segment start time obtained from the Manifest. Alternatively, 'tfdt' timestamps could just be ignored in Smooth Streaming mode.

**Comment by ojw28** [comment]
This is a valid point. Can you point to a stream that includes tfdt boxes at all?

**Comment by barbibulle** [comment]
I've posted two versions of a test stream, one where the media segments have a 'tfdt' box, and one where they don't.

With 'tfdt':
http://www.bok.net/tmp/dash/smooth_tfdt/stream.ism/Manifest

Without 'tfdt':
http://www.bok.net/tmp/dash/smooth_no_tfdt/stream.ism/Manifest

The effects are pretty obvious with the demo ExoPlayer example: the video will freeze every few seconds for the 'tfdt' version.

**Comment by ojw28** [comment]
Given the SmoothStreaming specification doesn't mention tfdt boxes at all, I would suggest the best thing to do is simply to ignore them for SmoothStreaming playbacks, rather than having them override the segment start time.

**Comment by barbibulle** [comment]
That makes perfect sense. Thanks.
