### ISSUE TITLE
TimeoutException: MediaMetadataRetriever.finalize() timed out

### ISSUE THREAD

**Issue by ItzNotABug** [google/ExoPlayer#8381]
I've been getting a lot of `TimeoutException`s lately,\
the stack trace does not give much info. but the Log tab in `Crashlytics` hints at a specific flow as to when this crash occurs.

**Stack Trace:**
```
Fatal Exception: java.util.concurrent.TimeoutException: android.media.MediaMetadataRetriever.finalize() timed out after 10 seconds
       at android.media.MediaMetadataRetriever.native_finalize(MediaMetadataRetriever.java)
       at android.media.MediaMetadataRetriever.finalize(MediaMetadataRetriever.java:340)
       at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:202)
       at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:185)
       at java.lang.Thread.run(Thread.java:818)
```
<br>

**Android Devices Affected:** LG, Motorola, Xiaomi, Asus
**Android Version Affected:** Android 7 (86%), Android 6 (10%), Android 5 (4%)
**ExoPlayer Library Version:** `2.12.1`

Attaching a screenshot from Crashlytics' log tab to prove that the crash is somehow originating from the `VideoPlayer`

<img width="516" alt="Screenshot 2020-12-20 at 12 06 00 PM" src="https://user-images.githubusercontent.com/20625965/102706902-f748e800-42bb-11eb-81d6-070e8523049d.png">

It seems that,\
as soon the `VideoPlayer` Activity is destroyed (by `onBackPressed` or `finish()`), this crash hits up.

The use case is simple:
1. Get `File` paths (String) list from MainActivity
2. Play in `VideoPlayer` like:
```kotlin
// in onCreate()
val mediaSource = ArrayList<MediaSource>()
withContext(Dispatchers.IO) { fileList.forEach { mediaSource.add(buildMediaSource(it)) } }
player = SimpleExoPlayer.Builder(this@VideoPlayer,
                    DefaultRenderersFactory(this@VideoPlayer),
                    DefaultExtractorsFactory())
                    .setUseLazyPreparation(true)
                    .build()
                    .apply {
                        setMediaSources(mediaSource, position, 1)
                        prepare()
                        repeatMode = Player.REPEAT_MODE_OFF
                        playWhenReady = true
                    }

            playerView.player = player
            playerView.keepScreenOn = true
            playerView.requestFocus()

// in onPause()
player?.pause()

// in onResume()
if (player?.isPlaying == false) player?.play()

// in onDestroy()
player?.release()
player = null // just to be extra sure

**Comment by ojw28** [comment]
It's clear from the stack trace that this issue is occurring in `android.media.MediaMetadataRetriever`, which isn't part of the ExoPlayer library. Please [file your issue on the Android platform instead](https://source.android.com/setup/contribute/report-bugs).
