### ISSUE TITLE
Is it possible to get PCM float audio stream in AudioProcessor from the MP4 video?

### ISSUE THREAD

**Issue by nicktz118** [google/ExoPlayer#8384]
I have a similar scenario with #8342, but I would like to process the PCM Float audio stream in AudioPrcoessor. I follow Issue #6749 and set `enableFloatOutput` to true when I initialized the DefaultAudioSink. However, the callback `queueInput` in BaseAudioProcessor always return PCM 16 bit. It seems there is a statement that will make `useFloatOutput` to false in DefaultAudioSink. (Please see the code below)
```
boolean useFloatOutput = enableFloatOutput && Util.isEncodingHighResolutionPcm(inputFormat.pcmEncoding);
```
Is there anyone who knows how to get PCM float in AudioProcessor? Thank you!

**Comment by ojw28** [comment]
`DefaultAudioSink` will not use float output unless the source content is itself high resolution. Furthermore, we do not support audio processing when float output is switched on. As per the `enableFloatOutput` [Javadoc](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/audio/DefaultAudioSink.html#DefaultAudioSink-com.google.android.exoplayer2.audio.AudioCapabilities-com.google.android.exoplayer2.audio.DefaultAudioSink.AudioProcessorChain-boolean-boolean-boolean-):

> Where possible, 32-bit float output will be used if the input is 32-bit float, and also if the input is high resolution (24-bit or 32-bit) integer PCM. Float output is supported from API level 21. Audio processing (for example, speed adjustment) will not be available when float output is in use.

So what you're looking for is unsupported, and you'll need to use the 16-bit PCM path.

**Comment by nicktz118** [comment]
Thank you very much for your quick response @ojw28

**Comment by nicktz118** [comment]
Hi @ojw28, dose callback `queueInput` in BaseAudioProcessor allow operating the sample? I found it will be laggy when I was trying to transfer range 32767~-32768 to 1~-1. Is there a solution that could help me solve the problem? Thank you!

**Comment by ojw28** [comment]
`ResamplingAudioProcessor` is an example of an `AudioProcessor` that operates on sample data, including potential resampling between different PCM formats. It's unclear what "laggy" means in this context, but that processor seems to perform fine.

It's really difficult to provide further guidance without any information about what your actual use case is. I think you'd need to provide a much more detailed description of what you're actually trying to do in order for us to help. You must _need_ to get the PCM float audio stream to implement a feature of some kind, which is currently not described in this issue.

**Comment by nicktz118** [comment]
Hi @ojw28, Thanks for the help and the suggestion. Finally, I found the issue occurs when I print the message in the AudioProcessor.
