### ISSUE TITLE
Exoplayer with AWS CloudFront Signed Cookies

### ISSUE THREAD

**Issue by skfaisal93** [google/ExoPlayer#8386]
I am using Cloudfront Signed Cookies to protect videos and I implemented it for browsers but I don't know how can I implement this with Exoplayer. 

Can anyone share some example or piece of code. It will be really helpful.

**Comment by marcbaechinger** [comment]
I do not really know the details of AWS CloudFront Signed Cookies. Assuming these are cookies like all others and these are name/value pairs that carry AWS specific signed values in HTTP headers of requests and responses (Set-Cookie and Cookie), this should probably just work with the standard cookie manager.

Please check the documentation of [java.net.CookieManager](https://developer.android.com/reference/java/net/CookieManager). This looks quite straightforward and is well explained on that page. You probably already found how [we are using the `CookieManager` in the `PlayerActivity` of the demo app](https://github.com/google/ExoPlayer/blob/release-v2/demos/main/src/main/java/com/google/android/exoplayer2/demo/PlayerActivity.java#L116).

For now I assume that AWS CloudFront Signed Cookies work as any other cookies, so the above would be sufficient. I'd suggest you try it out and if it does not work you tell us what you tried, which networks stack you are using and why you think it does not work, so we can continue from there. If it does just work, please let us know quickly too, so other user can learn from your experience. :)

**Comment by skfaisal93** [comment]
Here is the solution. Please note that I am using a custom CNAME. you can use your CloudFront URL instead of "https://protected.example.com". Also, let me know if anybody needs help in creating a signature. Hope this solution will help others.

```
Uri daUri = Uri.parse("https://protected.example.com/output-plain/art.m3u8");
        String cookieValue = "";
        if(policy != null && signature !=null && key != null){
            cookieValue +="CloudFront-Policy="+policy+";";
            cookieValue +="CloudFront-Signature="+signature+";";
            cookieValue +="CloudFront-Key-Pair-Id="+key+";";
        }

        DefaultHttpDataSourceFactory defaultHttpDataSourceFactory =
                new DefaultHttpDataSourceFactory(
                        "ExoPlayer",
                        null,
                        DefaultHttpDataSource.DEFAULT_CONNECT_TIMEOUT_MILLIS,
                        DefaultHttpDataSource.DEFAULT_READ_TIMEOUT_MILLIS,
                        true);
        defaultHttpDataSourceFactory.setDefaultRequestProperty("Cookie",cookieValue);
        DefaultDataSourceFactory dataSourceFactory = new DefaultDataSourceFactory(this, null, defaultHttpDataSourceFactory);
        defaultHttpDataSourceFactory.createDataSource();

        TrackSelection.Factory adaptiveTrackSelection = new AdaptiveTrackSelection.Factory(new DefaultBandwidthMeter());
        player = ExoPlayerFactory.newSimpleInstance(
                new DefaultRenderersFactory(this),
                new DefaultTrackSelector(adaptiveTrackSelection),
                new DefaultLoadControl());
        playerView.setPlayer(player);

        Handler mainHandler = new Handler();
        MediaSource mediaSource = new HlsMediaSource(daUri, dataSourceFactory, mainHandler, null);
```
