### ISSUE TITLE
What is the libvpx that is used in ExoPlayer?

### ISSUE THREAD

**Issue by bluemix** [google/ExoPlayer#839]
Hello,
I am wandering of the libvpx version that is used here.
Thanks in advance :)

**Comment by vigneshvg** [comment]
by default, libvpx is not bundled with exoplayer. the android platform's libvpx is used to decode vp8/vp9. so the version of libvpx there will depend on the version of android (e.g.: [1]).

if you are using the VP9 extension [2], then you can use whatever version of libvpx you prefer (if you follow the instructions to build the extension precisely, then you will end up with the tip-of-tree libvpx).

[1] http://androidxref.com/5.1.1_r6/xref/external/libvpx/generic/vpx_version.h
[2] https://github.com/google/ExoPlayer/tree/master/extensions/vp9

**Comment by andrewlewis** [comment]
The [build instructions for the software VP9 extension](https://github.com/google/ExoPlayer/blob/dev/extensions/vp9/README.md) suggest fetching the latest version of libvpx from https://chromium.googlesource.com/webm/libvpx.
