### ISSUE TITLE
Captions not working from M3U8 file, MIME TYPE eia608/1

### ISSUE THREAD

**Issue by kevinbtesar** [google/ExoPlayer#8391]
I'm on Android API Level 28 and I'm unable to get captions to work. It's MIME type is eia608. Here's the log output:

TextRenderer [
    Group:0, adaptive_supported=N/A [
        [X] Track:0, id=captions:CC1, mimeType=application/cea-608, language=en, supported=YES
    ]
 ]

And here's a URL pointing at an M3U8 file. Of course, the captions are embedded into the file itself.

https://dai2-playlistserver.aws.syncbak.com/playlist/18533680/master.m3u8?access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkdyYXkyMDE2MDgyOSJ9.eyJtaWQiOiIxODUzMzY4MCIsIm1kNSI6Ijg2MTZhMDgxMGU0MjViNmZjMjE0YjcxZmM3N2ViMjU1IiwiaWF0IjoxNTk0NTgzNTc4LCJpc3MiOiJTeW5jYmFrIChURykifQ.iMmFxpzDdyXuuhMVZm1jIN2JZ4B1Cl6ms5RwyuI2P-E

All online test players show captions without issue. Example:
https://castr.io/hlsplayer <-- shows captions.

It's easy to replicate. Download the latest version of ExoPlayer (2.12.2), use the 'demo' application; create a new media item using the provided URL, and it's apparent that captions are not working. Please note that is a link to a news station's live stream, so there may not be captions as soon as it's invoked, but it shouldn't take long before captions appear. I've tried setting the MIME type to APPLICATION_CEA708, APPLICATION_CEA608 and APPLICATION_M3U8. None of which made captions appear.

Here is a working M3U8 that should have been transcoded in the same way, though I can't be sure of that.
https://dai2-playlistserver.aws.syncbak.com/playlist/17375903/master.m3u8?access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkdyYXkyMDE2MDgyOSJ9.eyJtaWQiOiIxNzM3NTkwMyIsIm1kNSI6IjZiMDA2OGM2ODIzYjk3ZGJkNDRkNjA4NjM4ZWIzYWVjIiwiaWF0IjoxNTU5MDc2MjQ5LCJpc3MiOiJTeW5jYmFrIChURykifQ.1vK32jbcvuZTHCJA5BCDO8pe1o1lLNQyZe2dZ9JURGI

I should also note that the onCues(List<Cue> cues){} listener is repeatedly coming back with cues that are 0 sizes. It may be that the codec is can't translate it so the cues don't contain strings.

**Comment by icbaker** [comment]
I can reproduce what you're seeing. The subtitles don't work with the first link, but they do with the second.

When debugging inside `Cea608Decoder` during playback of the non-working stream, it seems every time a cue 'completes' we determine it's empty, which results in nothing being shown:
https://github.com/google/ExoPlayer/blob/107fed9b2afc1e1edce95eee4a1fbc952377efd2/library/core/src/main/java/com/google/android/exoplayer2/text/cea/Cea608Decoder.java#L905-L908

I haven't dug in deeper yet to understand why that's happening - it's likely that won't happen until the new year.

**Comment by kevinbtesar** [comment]
@icbaker Hey, thanks for the quick reply! And at least you're seeing the same thing :D 

Along with some other efforts, notably, I've also tried to introduce an HLS media source to see if that helped. It did not. 
 HlsMediaSource hlsMediaSource =
          new HlsMediaSource.Factory(dataSourceFactory)
              .createMediaSource(MediaItem.fromUri("https://dai2-playlistserver.aws.syncbak.com/playlist/18533680/master.m3u8?access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkdyYXkyMDE2MDgyOSJ9.eyJtaWQiOiIxODUzMzY4MCIsIm1kNSI6Ijg2MTZhMDgxMGU0MjViNmZjMjE0YjcxZmM3N2ViMjU1IiwiaWF0IjoxNTk0NTgzNTc4LCJpc3MiOiJTeW5jYmFrIChURykifQ.iMmFxpzDdyXuuhMVZm1jIN2JZ4B1Cl6ms5RwyuI2P-E")
                  .buildUpon()
                  .setMimeType(MimeTypes.APPLICATION_M3U8)
                  .build());
      player.setMediaSource(hlsMediaSource);

I like what you said about a cue completing and the player determining it was empty. I'm going to explore that avenue further. I'll be sure to get back with this thread if I have any luck. 

@icbaker Thank you!!!

**Comment by icbaker** [comment]
Apologies for the big delay here. I just tried to reproduce this on both dev-v2 and 2.12.2 and subtitles are visible to me with this link provided in the original comment:

https://dai2-playlistserver.aws.syncbak.com/playlist/18533680/master.m3u8?access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkdyYXkyMDE2MDgyOSJ9.eyJtaWQiOiIxODUzMzY4MCIsIm1kNSI6Ijg2MTZhMDgxMGU0MjViNmZjMjE0YjcxZmM3N2ViMjU1IiwiaWF0IjoxNTk0NTgzNTc4LCJpc3MiOiJTeW5jYmFrIChURykifQ.iMmFxpzDdyXuuhMVZm1jIN2JZ4B1Cl6ms5RwyuI2P-E

Did you change something about the encoding of the video/subtitles to resolve this?
