### ISSUE TITLE
Unable to play multimedia resources on USB flash drive

### ISSUE THREAD

**Issue by Killometer** [google/ExoPlayer#8392]
First of all, thank you.
   So here are my questions:
-- I tried to play the video from the USB flash drive, but it failed and nothing was displayed.

-- However, it can successfully play videos on Android internal storage.

--logcat shows some errors
![exoplayer_udisk_unable_play](https://user-images.githubusercontent.com/16235907/102986649-1fe71100-454c-11eb-968e-13d86b1fe703.png)

**Comment by ojw28** [comment]
If you think there's an issue here, you'll need to provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md). If you're unable to share [bug reports](https://developer.android.com/studio/debug/bug-report) or test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #1234" ("#1234" is replaced with your issue number). Please also update this issue to indicate you've done this.

**Comment by Killometer** [comment]
> If you think there's an issue here, you'll need to provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md). If you're unable to share [bug reports](https://developer.android.com/studio/debug/bug-report) or test content publicly, please send them to [dev.exoplayer@gmail.com](mailto:dev.exoplayer@gmail.com) using a subject in the format "Issue #1234" ("#1234" is replaced with your issue number). Please also update this issue to indicate you've done this.

**Comment by Killometer** [comment]
> If you think there's an issue here, you'll need to provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md). If you're unable to share [bug reports](https://developer.android.com/studio/debug/bug-report) or test content publicly, please send them to [dev.exoplayer@gmail.com](mailto:dev.exoplayer@gmail.com) using a subject in the format "Issue #1234" ("#1234" is replaced with your issue number). Please also update this issue to indicate you've done this.

OK. Thanks for your reply.
