### ISSUE TITLE
Consider exposing frame rate ranges for codecs

### ISSUE THREAD

**Issue by IanDBird** [google/ExoPlayer#840]
`MediaCodecUtil` exposes a number of helpful utility methods describing the capabilities of different MediaCodecs. One of them i've been planning on using was `isSizeAndRateSupportedV21`. The problem that I have is that already this will tell me simply whether a codec can't handle a particular size/rate, it doesn't tell me what it *can* handle. 

The scenario I have is that i'm trying to detect a video that can't be supported, and force it to be converted/transcoded on-the-fly to something more manageable. However, since it doesn't the video capabilities, i'm unable to tell the converter/transcoder what frame rate (or size) would be better. 

Would either of the options be considered:
 - Added new methods to `MediaCodecUtil` expose more `MediaCodecInfo.VideoCapabilities` methods
 - Actually expose `MediaCodecInfo.VideoCapabilities` directly.

I'm happy to try and take a punt at doing one of these, or even an alternative approach, but wanted to sanity check things would be acceptable before submitting a PR.

**Comment by ojw28** [comment]
Why don't you just use `MediaCodecInfo.CodecCapabilities` directly for this?

**Comment by IanDBird** [comment]
Very good point :)

The easiest way for me to actually obtain the `MediaCodecInfo.CodecCapabilities` is still with a modification to `MediaCodecUtil` to expose `getMediaCodecInfo`. Any concerns with making this public?

**Comment by IanDBird** [comment]
We eventually just made `MediaCodecUtil.getMediaCodecInfo` public. Out of interest, do you have any objections to this change being made in this branch, if so, what are they?

**Comment by ojw28** [comment]
No objection. I'm going to close this issue because it looks like you have a solution. Feel free to send a pull request to the dev branch (nb - please add @param and @return javadoc to the method if you make it public) if you'd like to see the change incorporated into the library. Thanks!
