### ISSUE TITLE
player always stay buffer when  network signal instability，how to solve it 

### ISSUE THREAD

**Issue by xiaoxiaoliu6** [google/ExoPlayer#8406]
When the network is unstable, for example, when the weak network is restored to the normal network, the player will always be in the buffer state. How to solve this problem? Look at the log and find no exception

exo version 2.9.6  &verison 2.12.2

**Comment by marcbaechinger** [comment]
I would expect that the state of the player transitions to `STATE_BUFFERING` when there is not enough data to continue playback. When further data is available the player goes back to `STATE_READY`. This should be unrelated to the type of network the device is currently connected to. 

Can you elaborate a bit on what the behavior is that you are seeing and that you think is not behaving as expected? Please provide us with clear reproduction steps so we know what you are doing and we can take action. If you are saying that the player is stuck in `STATE_BUFFERING` even when the device is back on 'normal network', please describe what you do to bring the player in this condition.

**Comment by xiaoxiaoliu6** [comment]
sorry  ,qa tell me  stay buffer for a white,then exo throw timeout exception
