### ISSUE TITLE
Is there any way to speed up more than 8x?

### ISSUE THREAD

**Issue by tamanna-seg** [google/ExoPlayer#8413]

**Comment by marcbaechinger** [comment]
To change the playback speed you pass a `PlaybackParameters` object to `player.setPlaybackParameters(PlaybackParameters)`.

This snippet sets the playback speed to 32f and it seems to work.

```
player.setPlaybackParameters(new PlaybackParameters(32f));
```

Why do you think that 8x is the limit?

Aside: If you are using the playback speed for fast forward, I don't think that's the intended use case of setting a playback speed. It's probably inefficient and you can run into buffering problems quite easily if the bandwidth is not super good. Setting the playback speed is to allow users to listen to and watch content in a higher or lower speed. When speeding up above around 2x or similar a user probably can't consume the media appropriately anymore.

**Comment by tamanna-seg** [comment]
But when i am setting it to 10f or 12f and after that when i get player.getPlaybackParameters().speed it always returns 8.0

**Comment by marcbaechinger** [comment]
Upps, yes, you are right. The values are limited by the [`DefaultAudioSink`](https://github.com/google/ExoPlayer/blob/ffea2a64b30f40bb298a6f97b9a0ec828312c138/library/core/src/main/java/com/google/android/exoplayer2/audio/DefaultAudioSink.java#L1044).

```
2020-12-30 13:35:24.867 1627-1627/com.google.android.exoplayer2.demo D/EventLogger: playbackParameters [eventTime=0.00, mediaPos=0.00, window=0, PlaybackParameters(speed=32.00, pitch=1.00)]

[...]

2020-12-30 13:35:25.070 1627-1627/com.google.android.exoplayer2.demo D/EventLogger: playbackParameters [eventTime=0.20, mediaPos=0.00, window=0, period=0, PlaybackParameters(speed=8.00, pitch=1.00)]
```

Seem like the code kind of confirms my comments about having the playback speed above a certain speed does not make sense for the use case it is intended for.

**Comment by tamanna-seg** [comment]
So there is any way to customize this class or any other way for more speeds?

**Comment by tonihei** [comment]
Do you need the audio to play at more than 8x speed? If not, you could disable the audio in the `DefaultTrackSelector` as video-only playback should be fine with speeds of more than 8x.

**Comment by ojw28** [comment]
I think the conclusion here is that:

* Speeds faster than 8x are not supported.
* Playing audio at faster than 8x probably doesn't make a whole lot of sense anyway, from a feature perspective. At a certain point it's better to disable the audio and/or pause the player and use seeking operations, depending on the exact use case.
