### ISSUE TITLE
Video Not Playing 

### ISSUE THREAD

**Issue by Ashwin-Sqt** [google/ExoPlayer#8418]
Hi, 

Im a beginner in this library .. im Getting a playback error when trying to play this URL "**http://40.112.184.97:8080/saada-staging/admin/documents/broadcast-media/5555551609332108932/SampleVideo_720x480_1mb.mp4**" 
I have used one of your tutorial code 

public class MainActivity extends AppCompatActivity {
//    private PlayerView playerView;
    ProgressBar loading;

//    SimpleExoPlayer player;
    PlayerView playerView;
    Player player;
    private boolean playWhenReady = true;
    private int currentWindow = 0;
    private long playbackPosition = 0;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        playerView = findViewById(R.id.video_view);
        loading = findViewById(R.id.loading);
//        player = new SimpleExoPlayer.Builder(this).build();

    }
    @Override
    public void onStart() {
        super.onStart();
        if (Util.SDK_INT >= 24) {
            initializePlayer();
        }
    }

    @Override
    public void onResume() {
        super.onResume();
        hideSystemUi();
        if ((Util.SDK_INT < 24 || player == null)) {
            initializePlayer();
        }
    }

    @SuppressLint("InlinedApi")
    private void hideSystemUi() {
        playerView.setSystemUiVisibility(View.SYSTEM_UI_FLAG_LOW_PROFILE
                | View.SYSTEM_UI_FLAG_FULLSCREEN
                | View.SYSTEM_UI_FLAG_LAYOUT_STABLE
                | View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY
                | View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION
                | View.SYSTEM_UI_FLAG_HIDE_NAVIGATION);
    }
    @Override
    public void onPause() {
        super.onPause();
        if (Util.SDK_INT < 24) {
            releasePlayer();
        }
    }

    @Override
    public void onStop() {
        super.onStop();
        if (Util.SDK_INT >= 24) {
            releasePlayer();
        }
    }
    private void releasePlayer() {
        if (player != null) {
            playWhenReady = player.getPlayWhenReady();
            playbackPosition = player.getCurrentPosition();
            currentWindow = player.getCurrentWindowIndex();
            player.release();
            player = null;

        }
    }
    private void initializePlayer() {
        DefaultTrackSelector trackSelector = new DefaultTrackSelector(this);
        trackSelector.setParameters(
                trackSelector.buildUponParameters().setMaxVideoSizeSd());
        player = new SimpleExoPlayer.Builder(this)
                .setTrackSelector(trackSelector)
                .build();
        playerView.setPlayer(player);
        Uri uri = Uri.parse(getString(R.string.media_url_mp3));
        MediaItem mediaItem = new MediaItem.Builder()
                .setUri(uri)
                .setMimeType(MimeTypes.APPLICATION_MPD)
                .build();
        player.setMediaItem(mediaItem);

        player.setPlayWhenReady(playWhenReady);
        player.seekTo(currentWindow, playbackPosition);
        player.prepare();
    }

}

**Comment by andrewlewis** [comment]
Please fill in the issue template [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md) next time. In particular, you've said there's a playback error but not what it is!

When I request the provided URL I get data that doesn't look like a valid stream, and I see an `UnrecognizedInputFormatException`. It looks like the server is not providing a valid MP4. Also, in your code snippet the MIME type is overridden to `APPLICATION_MPD` but I think that'd only be appropriate for a DASH stream (I think you can probably just remove the line that sets that).

**Comment by Ashwin-Sqt** [comment]
But this same url works for ios . I guess its adaptive stream url

**Comment by andrewlewis** [comment]
I think your server requires that the player makes a range request. Currently ExoPlayer only adds the Range header if the request is from a non-zero position (or has a bounded length), so when starting to load the MP4 we don't make a range request by default and the server isn't returning any data.

If I edit `CronetDataSource` so it always sets a Range header (`"Range: bytes=0-"`) the provided URL plays in the demo app. Given this hasn't been reported before I suspect the right fix is on the server side, not ExoPlayer.

**Comment by Ashwin-Sqt** [comment]
Thanks alot sir.
Can I know  how did u edit in demo app in detail ..

**Comment by andrewlewis** [comment]
If you take a look at `CronetDataSource.buildRequestBuilder` it should be clear where you can hack the code to add the range header. I think the right fix is to make the server respond with data when requests don't have a range header, though.
