### ISSUE TITLE
Unable to play DASH & Widevine on Nexus Player

### ISSUE THREAD

**Issue by mitsnosrap** [google/ExoPlayer#842]
This issue may be similar to #612 .

I am unable to play a DASH & Widevine protected stream on the Nexus Player.  The same stream plays fine on other devices (I have tested on an ADT-1 and a Sony XBR43X830C TV).  I have forked this repo and created a new [branch](https://github.com/BrightcoveConsultingReusableComponents/ExoPlayer/tree/brightcove).  In that branch I have modified the sample app to play some of our test streams.  All the samples that are in the "Brightcove Samples" category and named DASH+CENC & Widevine do not play on the Nexus Player.  Those videos play fine when running the same app on the ADT-1 or the Sony TV. These videos also play well on other non-TV devices (phones, tablets).

It's worth noting that the existing Widevine samples do play fine on the Nexus Player.  This seems to indicate a potential issue with the stream itself or our Widevine licensing server.

I tried attaching my logcat output as a file, but Github was having issues.  Therefore, I have posted my logcat output [here](http://psdev.brightcove.com/tparsons/logcat.txt).  There are numerous exceptions in there and what looks like issues reported from Widevine.

**Comment by mitsnosrap** [comment]
I have just updated my fork to include a new sample stream.  It's the same Dash video, only protected with PlayReady instead of Widevine.  That video is able to play correctly on the Nexus Player.

**Comment by jatago** [comment]
Hi @mitsnosrap, 

Seems you are not alone on this and there are several of us having the same issue. Our streams work just fine in most devices (we had some issues in some Samsung Galaxy S4 for some weird reason); phones, tablets and even other AndroidTV boxes.

**Comment by ojw28** [comment]
Are you sure the issue is specific to Widevine? Do you have an otherwise identical non-encrypted stream that you can test on a Nexus Player internally? The reason I ask is because this bit of the logcat looks generally suspicious, but may not be Widevine related:

```
E VideoDecoder: Reference frame 0 is missing. Stop decoding.
E VideoDecoder: setReference failed. status = -6
E VideoDecoder: beginDecodingFrame failed. status = -6
```

- What version of Android are you running on the Nexus Player, and if not the latest, does updating help?
- Does updating to the latest release of ExoPlayer help (it looks like your branch contains 1.4.2, which isn't that recent).
- If you could attach a full bugreport (adb bugreport > bugreport.txt) and share that, that would be more helpful than just logcat.

Thanks!

**Comment by mitsnosrap** [comment]
Hello,
I'm pretty sure the issue is specific to Widevine, but I'm not 100% sure.  I haven't tested it on an otherwise identical non-encrypted stream, so I'll be sure to check that.

To answer your other questions:
* My Nexus Player is running 6.0. I can flash it to 6.0.1 and try again.
* I will update to the latest release of ExoPlayer and try again.
* If I can still reproduce after updating, I will attach a full bug report.

**Comment by mitsnosrap** [comment]
I have updated my Nexus Player to 6.0.1, and merged the latest commits in dev into my branch.  Playback is working now!  However, I'm seeing lots of artifacts.  I will test on an MPEG-DASH version of the stream (without Widevine), before attaching a full bug report and comparison screenshot of the artifacts.

**Comment by mitsnosrap** [comment]
[Here is a bug report](https://github.com/google/ExoPlayer/files/63020/bugreport.txt) taken when playing back the video. Below is a screenshot showing the artifacts when the video plays.

![2015-12-14 12 38 47](https://cloud.githubusercontent.com/assets/5825829/11819253/dcbbc7fc-a32c-11e5-908c-f1eb294337ef.jpg)

**Comment by mitsnosrap** [comment]
We (Brightcove) think we have a solution for this issue, so I will be closing it. 

When we use baseline renditions with Widevine, we get the artifacts as seen above.
When we use baseline renditions **without** Widevine, we get **NO** artifacts.
When we use main or high renditions with Widevine, we get **NO** artifacts.

**Comment by Sean-X** [comment]
Thanks a lot for this report. it's very helpful!!!
