### ISSUE TITLE
Add option to align durations of MergingMediaSource elements

### ISSUE THREAD

**Issue by joel1st** [google/ExoPlayer#8422]
I want to set up a default audio clip to play for video playback when there is no audio track present. I want this default audio source to play for the same duration as the video (downloaded mp4 file) MediaSource. My first thought was to use a ClippingMediaSource + MergingMediaSource, but the nature of this application means I do not know what the precise video duration is (unless there is a performant way to easily calculate this without playing the file). If there was a way to dynamically update the ClippingMediaSource duration this could work, but I have not found a way.

So I guess there are two questions:
Is there a way to dynamically update the duration of a ClippingMediaSource?
or is there a way to set the ClippingMediaSource duration to the be same duration as another MediaSource?

**Comment by andrewlewis** [comment]
If the media is downloaded, loading it to find its duration is not going to be excessively inefficient so that might be fine for now. Whether it's performant enough will depend on your specific requirements I guess.

#3163 tracks having a way to update the clipping start/end points dynamically.

@tonihei Please could you take a look and add or correct anything? Thanks.

**Comment by tonihei** [comment]
That's pretty much it:

 - Loading a downloaded or local file to find its duration is not super inefficient and a good workaround if required:
```
Player player = new SimpleExoPlayer.Builder(context).build();
player.setMediaItem(MediaItem.fromUri(localFileUri));
player.addListener(new EventListener() {
  @Override
  public void onTimelineChanged(Timeline timeline, int reason) {
    if (!timeline.isEmpty()) {
      long durationMs = timeline.getWindow(0, new Window().getDurationMs;
      if (durationMs != C.TIME_UNSET) {
        player.release();
        reportDuration(durationMs);
      }
    } 
  }

  @Override 
  public void onPlayerError(ExoPlaybackException error) {
    player.release();
    reportDurationExtractionFailed();
  }
};
player.prepare()
```

- Updating the clipped duration is tracked by #3163, but there are no immediate plans to finish this feature.

-  Clipping elements in a `MergingMediaSource` to match the duration of the shortest merged source is a sensible feature request. We already have a feature to ensure the timestamps of merged sources match, so it also makes sense to match the durations if required. Marking as an enhancement accordingly.
