### ISSUE TITLE
How to know about MediaCodecVideoRenderer in EventLogger

### ISSUE THREAD

**Issue by JJJoonngg** [google/ExoPlayer#8424]
I wanna know about Media codec, fps, resoultion etc..
So I use `addAnalyticsListener` and can read MediaCodecVideoRenderer but
I don't get these informations.
Plz Help me

**Comment by andrewlewis** [comment]
To find out which `MediaCodec`s are being used, you can handle `onVideoDecoderInitialized` and `onAudioDecoderInitialized`, which receive the decoder name. `Format` instances passed to listener methods and in the `TrackGroupArray` `TrackGroup`s contain information about resolution, frame rate and so on (if parsed from the container). More generally it may be worth having a look at the [`EventLogger`](https://github.com/google/ExoPlayer/blob/440fd1c/library/core/src/main/java/com/google/android/exoplayer2/util/EventLogger.java) class to see where information logged there comes from.

If you are looking for something else please give some more details about what specific information is needed. Thanks.

**Comment by JJJoonngg** [comment]
@andrewlewis Thanks a lot!!! I appreciate your comments, a big help for me! Thanks
