### ISSUE TITLE
transport part

### ISSUE THREAD

**Issue by manang** [google/ExoPlayer#8425]
Hi,
I'm trying to implement a new version of this application that does not use tcp to download the manifest and the chunks of the videos, but I want to use another technology.

could you point me where is the donwload part of the contents?
thank you very much.

Angelo

**Comment by icbaker** [comment]
You should implement a [`DataSource`](https://github.com/google/ExoPlayer/blob/release-v2/library/common/src/main/java/com/google/android/exoplayer2/upstream/DataSource.java). For example there's a [`UdpDataSource`](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/upstream/UdpDataSource.java).

For playback you can register your `DataSource` implementation by passing it to a `MediaSource.Factory` constructor, which you then pass to `(Simple)ExoPlayer.Builder#setMediaSourceFactory()`.

**Comment by manang** [comment]
thank you very much
