### ISSUE TITLE
The first few seconds of falling frames video will be black and cannot be skipped, but there's noise

### ISSUE THREAD

**Issue by xuzh2017** [google/ExoPlayer#8426]
The first few seconds of falling frames video will be black and cannot be skipped, but
there's noise

**Comment by andrewlewis** [comment]
Hi! Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md). If you're unable to share [bug reports](https://developer.android.com/studio/debug/bug-report) or test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #1234" ("#1234" is replaced with your issue number). Please also update this issue to indicate you've done this.

**Comment by xuzh2017** [comment]
OK.thank you
