### ISSUE TITLE
Set quality in SmoothStreaming

### ISSUE THREAD

**Issue by juanpef** [google/ExoPlayer#843]
I am working on a VOD app and the video assets are Smooth Streaming. There is some way to change manually the start bitrate in order to put the highest available by default?

Thanks!

**Comment by ojw28** [comment]
Yes. When you instantiate the components needed for playback, you'll build a `SmoothStreamingChunkSource` to generate video chunks. One of the objects passed to the constructor is a `FormatEvaluator`. You're probably passing an `AdaptiveEvaluator` for this argument at the moment. The solution is to create your own `FormatEvaluator` implementation, probably based on the `AdaptiveEvaluator` implementation, that selects the initial format in a different way.

**Comment by juanpef** [comment]
Thanks!
