### ISSUE TITLE
how to set a selected subtitle from the list which is sideloaded to mediaItem

### ISSUE THREAD

**Issue by SepidehAkbarinezhad** [google/ExoPlayer#8433]
hello
I'm using the last version of exoPlayer (2.12.2) . According to documents ,a list of subtitles can be added when building a media item . In my case user can see the sideloaded subtitles in a dialog and choose from them . how can I switch to the selected one as the video is playing. In past we can use MergingMediaSource . But now ,how can we perform this ,when  MergingMediaSource is used by DefaultMediaSourceFactory internally .

**Comment by icbaker** [comment]
Sideloading subtitle files using `MediaItem` should work, and they should show up in the track selector (which I think is what you're asking?).

We need more information to understand your exact problem - please describe clearly what you're trying to do, what you expect to see, and what you actually see. Ideally this would done by making changes to our [demo app](https://exoplayer.dev/demo-application.html) and showing screenshots of the unexpected behaviour.
