### ISSUE TITLE
HDR Live content not detected automatically

### ISSUE THREAD

**Issue by needz** [google/ExoPlayer#8434]
When streaming Live HLG HDR content in the TS or HLS containers, the HDR format is not detected by device automatically and thus not triggered on TV. When you open the same Live stream in VLC or MX Player, it is detected automatically.

Interestingly, when you play a saved TS recording with specific length, it is detected automatically.

The issue can be easily reproduced in ExoPlayer demo player by running each of the examples, which will be sent to your e-mail address with respective issue number.

1) Partial TS stream of specific length in HLG HDR format
2) Produced TS clip of specific length in HLG HDR format
3) Live HLS stream in HLG HDR format

- ExoPlayer 2.12.2
- Android 9
- Sony Android TV (XG series, 2019)

**Comment by andrewlewis** [comment]
> Interestingly, when you play a saved TS recording with specific length, it is detected automatically.

Just to clarify, does this case (where it works correctly with ExoPlayer) correspond to one of the three provided streams? If so, which one? If not, could you share that stream too?

I think it's unlikely we will be able to make much progress on this issue currently, partly because I don't think we have access to test equipment that supports this format. If you can share any information (e.g., references to specifications) describing how this format is signaled that might help us pass the right information down to the H.265/HEVC decoder. I have a suspicion that in the case where it doesn't work we are stripping out some SEI messages that signal the color info, but I'm not sure.

**Comment by needz** [comment]
@andrewlewis On Sony Android TV (XG series, 2019) it works correctly in case 1 and 2 only.

I did some additional test on the following devices:

1) nVIdia Shield TV - works in all 3 cases
2) Amazon Fire Stick 4K - works in case 1 only
3) Google Chromecast - works in case 1 and 3

It can be tested on any 4k HDR capable device and if your TV supports HDR, it will switch to HDR mode automatically. In case of LG TVs it shows a small popup HLG HDR, whereas on Samsung you need to go to picture settings shortcut and HDR label will be visible.

You can also notice some UI color distortions in ExoPlayer if you run these streams on an 4k HDR capable device with a non-HDR capable TV, then you can see UI color changes when you go back to the playlist.

**Comment by andrewlewis** [comment]
The fact that Nvidia Shield works in all cases suggests that the application layer (and ExoPlayer) is passing required information to the system, so I think we should treat this as a device-specific issue for now.

Could you report this to Amazon so they can investigate the FireTV issue?

I can follow up for Chromecast, but it would be helpful if you could share a bug report taken just after playing case 2 so we have information about any errors and the build information. Thanks.

**Comment by andrewlewis** [comment]
Please could you also share some more details on what the difference is between streams 1 and 2? Thanks!

**Comment by needz** [comment]
**Case 1:**

```
ID                                       : 11100 (0x2B5C)
Format                                   : MPEG-TS
File size                                : 722 MiB
Duration                                 : 5 min 0 s
Overall bit rate mode                    : Variable
Overall bit rate                         : 20.1 Mb/s

Video
ID                                       : 457 (0x1C9)
Menu ID                                  : 4603 (0x11FB)
Format                                   : HEVC
Format/Info                              : High Efficiency Video Coding
Format profile                           : Main 10@L5.1@Main
Codec ID                                 : 36
Duration                                 : 1 min 13 s
Width                                    : 3 840 pixels
Height                                   : 2 160 pixels
Display aspect ratio                     : 16:9
Frame rate                               : 50.000 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 10 bits
Writing library                          : ATEME Titan File 3.7.6 (4.7.6.0)
Color range                              : Limited
Color primaries                          : BT.2020
Transfer characteristics                 : HLG
Matrix coefficients                      : BT.2020 non-constant

Audio
ID                                       : 458 (0x1CA)
Menu ID                                  : 4603 (0x11FB)
Format                                   : AAC LC
Format/Info                              : Advanced Audio Codec Low Complexity
Format version                           : Version 4
Muxing mode                              : ADTS
Codec ID                                 : 15-2
Duration                                 : 1 min 12 s
Bit rate mode                            : Variable
Channel(s)                               : 1 channel
Channel layout                           : C
Sampling rate                            : 48.0 kHz
Frame rate                               : 46.875 FPS (1024 SPF)
Compression mode                         : Lossy
Delay relative to video                  : -156 ms

Menu
ID                                       : 456 (0x1C8)
Menu ID                                  : 4603 (0x11FB)
Duration                                 : 5 min 0 s
List                                     : 457 (0x1C9) (HEVC) / 458 (0x1CA) (AAC)
```

**Case 2:**

```
ID                                       : 1049 (0x419)
Format                                   : MPEG-TS
File size                                : 738 MiB
Duration                                 : 4 min 57 s
Overall bit rate mode                    : Variable
Overall bit rate                         : 20.8 Mb/s

Video
ID                                       : 33 (0x21)
Menu ID                                  : 301 (0x12D)
Format                                   : HEVC
Format/Info                              : High Efficiency Video Coding
Format profile                           : Main 10@L5.1@Main
Codec ID                                 : 36
Duration                                 : 17 h 6 min
Width                                    : 3 840 pixels
Height                                   : 2 160 pixels
Display aspect ratio                     : 16:9
Frame rate                               : 59.940 (60000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0 (Type 2)
Bit depth                                : 10 bits
Writing library                          : ATEME Titan File 3.7.7 (4.7.7.1)
Color range                              : Limited
Color primaries                          : BT.2020
Transfer characteristics                 : HLG / BT.2020 (10-bit)
Matrix coefficients                      : BT.2020 non-constant
SEI_rbsp_stop_one_bit                    : Missing

Audio
ID                                       : 36 (0x24)
Menu ID                                  : 301 (0x12D)
Format                                   : AAC LC
Format/Info                              : Advanced Audio Codec Low Complexity
Format version                           : Version 4
Muxing mode                              : ADTS
Codec ID                                 : 15-2
Duration                                 : 4 min 57 s
Bit rate mode                            : Variable
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 46.875 FPS (1024 SPF)
Compression mode                         : Lossy
Delay relative to video                  : -35 ms
```

**Case 3 (TS Chunk):**

```
General
ID                                       : 1 (0x1)
Format                                   : MPEG-TS
File size                                : 13.4 MiB
Duration                                 : 4 s 780 ms
Overall bit rate mode                    : Variable
Overall bit rate                         : 23.5 Mb/s

Video
ID                                       : 256 (0x100)
Menu ID                                  : 1 (0x1)
Format                                   : HEVC
Format/Info                              : High Efficiency Video Coding
Format profile                           : Main 10@L5.1@Main
Codec ID                                 : 36
Duration                                 : 22 h 55 min
Width                                    : 3 840 pixels
Height                                   : 2 160 pixels
Display aspect ratio                     : 16:9
Frame rate                               : 50.000 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 10 bits
Color range                              : Limited
Color primaries                          : BT.2020
Transfer characteristics                 : HLG / BT.2020 (10-bit)
Matrix coefficients                      : BT.2020 non-constant

Audio
ID                                       : 257 (0x101)
Menu ID                                  : 1 (0x1)
Format                                   : AAC LC
Format/Info                              : Advanced Audio Codec Low Complexity
Format version                           : Version 4
Muxing mode                              : ADTS
Codec ID                                 : 15-2
Duration                                 : 4 s 778 ms
Bit rate mode                            : Variable
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 46.875 FPS (1024 SPF)
Compression mode                         : Lossy
Delay relative to video                  : -189 ms
Language                                 : Russian
```

**Comment by needz** [comment]
@andrewlewis Could you maybe hint me on what changes I can make to ExoPlayer (like skip some checks), so it does not strip any color information from the stream, so I can test it on specific device? It seems there is definitively something in the ExoPlayer library, since other apps can detect HDR information on the same device.

**Comment by andrewlewis** [comment]
> @andrewlewis Could you maybe hint me on what changes I can make to ExoPlayer (like skip some checks), so it does not strip any color information from the stream, so I can test it on specific device? It seems there is definitively something in the ExoPlayer library, since other apps can detect HDR information on the same device.

We don't intentionally strip color information from the stream as far as I know, and the fact that it works on Shield means that the extraction code is providing the required information (unless Shield is doing something clever to reconstruct missing information!).

I expect the exact same information is being passed down to the `MediaCodec` on every device because the extractors are part of ExoPlayer not the platform.
