### ISSUE TITLE
Playback failing on Xiaomi AOSP box

### ISSUE THREAD

**Issue by logituitrel** [google/ExoPlayer#8438]
Playback is reported as constantly failing on xiaomi aosp boxes.
Observed in logs:
```
internalError [eventTime=0.01, mediaPos=0.00, window=0, loadError
com.google.android.exoplayer2.upstream.cache.Cache$CacheException: Failed to create cache directory: /storage/emulated/0/Android/data/com.xiaomitv.sonyliv/files/logixplayer
at com.google.android.exoplayer2.upstream.cache.SimpleCache.initialize(SimpleCache.java:522)
at com.google.android.exoplayer2.upstream.cache.SimpleCache.access$000(SimpleCache.java:50)
at com.google.android.exoplayer2.upstream.cache.SimpleCache$1.run(SimpleCache.java:268)
]
```

**Comment by andrewlewis** [comment]
Hi! Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md). If you're unable to share [bug reports](https://developer.android.com/studio/debug/bug-report) or test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #1234" ("#1234" is replaced with your issue number). Please also update this issue to indicate you've done this.

I think @marcbaechinger's response in #8253 may apply for this case too as the error looks similar.

**Comment by ojw28** [comment]
It's possible that the workaround submitted at the bottom of https://github.com/google/ExoPlayer/issues/8253 will fix this issue. Closing as a duplicate in any case, since additional information has not been provided.
