### ISSUE TITLE
h265 file format support

### ISSUE THREAD

**Issue by purvagevaria** [google/ExoPlayer#8439]
Hi team I want to achieve two things using exo player.

1. h265 file format support. : File is there in my internal storage I just want to play it using exo player. I tried different examples to load the same but I am getting a supported format error . 
2.  I want to achieve live streaming into the app: I am connecting my device as a hotspot and loading the URL and trying to achieve live streaming. Is there any way to achieve live streaming? Tried in the given sample app but live streaming not working.

I checked the supported format but in exo library class I found h265 reader that why i am posting the issue 

https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/extractor/ts/H265Reader.html

Appreciate your help on the same.

**Comment by andrewlewis** [comment]
Please provide complete information as requested in the question template. The template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/question.md).

Unfortunately we can't answer unclear questions or those with insufficient information. In particular, for the first point, it would be useful to know what the error is, whether the stream plays in the ExoPlayer demo app and (if not) what logging output you get when trying to play the stream in the demo app. For the second point, ExoPlayer does support some types of live stream, and we'd need to know what the error is to be able to help.

**Comment by purvagevaria** [comment]
@andrewlewis 
Issue description :  I am having file let's assume file name is **abc.h265** file with h265 extention. Now my question am I able to load this file using exo ? I tried but I am getting file format error .
Reproduction steps
Load any h265 file

**Comment by purvagevaria** [comment]
@andrewlewis My simple question to the dev team is am I able to load file with extension h265. Suppose I am having file **abc.h265** and I want  load this file in exoplayer view. Is it achievable ? If yes then how ?

I checked Exo player supported format but as mentioned in the above link I found h265 reader in exo class so I am curious to know if I could achieve this?

https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/extractor/ts/H265Reader.html

**Comment by andrewlewis** [comment]
I'm not sure exactly what the file format is, but you could try remuxing it into a container like MP4 or put it in an MPEG-TS stream. `H265Reader` is used by `TsExtractor`. If the file is a 'raw' H.265/HEVC Annex B stream, I don't think we support it directly.

**Comment by purvagevaria** [comment]
Hi @andrewlewis I am using this below sample file. File is added in raw folder.
https://drive.google.com/file/d/1NJHbSVgMS4veLqtVLLNLOfXg6MOgvL9O/view?usp=sharing
Below is the exception when I try to load the file.
ExoPlayerImplInternal: Source error
      com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor, AmrExtractor, Ac4Extractor, FlacExtractor) could read the stream.

**Comment by andrewlewis** [comment]
That sample does look like an Annex B stream (there are start codes (0, 0, 0, 1) followed by H.265/HEVC NAL unit headers).

As I mentioned above, we don't support this format directly at the moment and I don't think we have plans to add support. To play media with ExoPlayer you are better off using a more common format like MP4, Matroska or similar. You could also take a look at #3503 which is an old issue that has a suggestion about how you could implement an extractor for this format if you really want to use it.

**Comment by purvagevaria** [comment]
> I'm not sure exactly what the file format is, but you could try remuxing it into a container like MP4 or put it in an MPEG-TS stream.
@andrewlewis  Is there any way to convert the container format from Exo or any suggestion or utility class which is available for us to convert our container format?

**Comment by andrewlewis** [comment]
ExoPlayer doesn't remux (and even if it did, it doesn't currently read this input container format!).

I'd probably use ffmpeg (see for example https://stackoverflow.com/questions/15049829/remux-to-mkv-but-add-all-streams-using-ffmpeg). Giving further help with this is beyond the scope of this issue tracker I'm afraid.

**Comment by purvagevaria** [comment]
> ExoPlayer doesn't remux (and even if it did, it doesn't currently read this input container format!).
> 
> I'd probably use ffmpeg (see for example https://stackoverflow.com/questions/15049829/remux-to-mkv-but-add-all-streams-using-ffmpeg). Giving further help with this is beyond the scope of this issue tracker I'm afraid.

No worries @andrewlewis thanks for the prompt update I will look into other library.
