### ISSUE TITLE
Question: Are these error messages a real problem?

### ISSUE THREAD

**Issue by dnutcracker** [google/ExoPlayer#844]
I keep getting the following error messages multiple times when starting ExoPlayer instances - (I don't see any visible problems anywhere) 

E/OMXMaster: A component of name 'OMX.qcom.audio.decoder.aac' already exists, ignoring this one.
E/OMXNodeInstance: OMX_GetExtensionIndex OMX.google.android.index.storeMetaDataInBuffers failed

Should I care about them?

**Comment by ojw28** [comment]
Those messages come from the underlying platform, so we have no control over them. I don't think they're problematic, and I don't know why they're logged with E rather than I or D.

**Comment by TommyVisic** [comment]
I get these messages too - on all our test devices. It does indeed seem that they were mistakenly logged as E.

**Comment by dnutcracker** [comment]
OK, good to know.

Thanks.
