### ISSUE TITLE
Ima ads not working with mediaItem

### ISSUE THREAD

**Issue by SetareMaghari** [google/ExoPlayer#8440]
hi there
I'm using mediaItem for exo following the document.
I wanna set an IMA ad, but its just not showing and i get the following error in 

[errorType: LOAD, errorCode: AdErrorCode [name: FAILED_TO_REQUEST_ADS, number: 1005], message: There was a problem requesting ads from the server.]

this is my code:

`MediaItem.Builder().setUri(url).setAdTagUri("https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpostlongpod&cmsid=496&vid=short_tencue&correlator=").build()`

`val imaLoader =  ImaAdsLoader.Builder(context)
            .setAdErrorListener {
                <some logs>
            }
            .setAdEventListener {
                <some logs>
            }
            .build()`

`player = exoPlayerBuilder.setMediaSourceFactory(
            DefaultMediaSourceFactory(context)
            .setAdsLoaderProvider {
                imaLoader
            }.setAdViewProvider(appPlayerView.playerContainer)).build()
            .apply {
                imaLoader.setPlayer(this)
                setMediaItem(mediaItem)
                prepare()
                playWhenReady = true
            }`

I passed several days working on that, and now i really need a help :/

**Comment by andrewlewis** [comment]
That ad tag loads fine for me, and I didn't spot any issues with the code snippets provided. Please could you try enabling debug logging via `ImaAdsLoader.Builder.setDebugModeEnabled` (on the latest version) then capturing the logcat output when trying to play the stream so we can see if there are any informative error messages?

**Comment by SetareMaghari** [comment]
so is my code correct?

this are some logs that i get while playing, hope it helps you find the problem



V/StudioTransport: Handling agent command 1200 for pid: 4277.
V/StudioTransport: Handling agent command 1200 for pid: 4277.
V/StudioTransport: Handling agent command 1200 for pid: 4277.
I/OMXClient: IOmx service obtained
D/SurfaceUtils: connecting to surface 0x76c57fd010, reason connectToSurface
I/MediaCodec: [OMX.qcom.video.decoder.avc] setting surface generation to 4379653
D/SurfaceUtils: disconnecting from surface 0x76c57fd010, reason connectToSurface(reconnect)
D/SurfaceUtils: connecting to surface 0x76c57fd010, reason connectToSurface(reconnect)
I/ExtendedACodec: setupVideoDecoder()
I/ExtendedACodec: Decoder will be in frame by frame mode
D/SurfaceUtils: set up nativeWindow 0x76c57fd010 for 854x480, color 0x7fa30c06, rotation 0, usage 0x20002900
I/OMXClient: IOmx service obtained
I/ACodec: codec does not support config priority (err -2147483648)
I/ACodec: codec does not support config priority (err -2147483648)
W/ExtendedACodec: Failed to get extension for extradata parameter
D/SurfaceUtils: set up nativeWindow 0x76c57fd010 for 864x480, color 0x7fa30c06, rotation 0, usage 0x20002900
I/ELEVOC_NS_FRONT: cycle task init 0x76a5f42d40
D/AudioTrack: set(sessionID=0)
D/AudioTrack: set(): streamType -1, sampleRate 44100, format 0x1, channelMask 0x3, frameCount 14144, flags #0, notificationFrames 0, sessionId 0, transferType 3, uid -1, pid -1

**Comment by andrewlewis** [comment]
The provided log snippet doesn't have anything ad-related in it (some relevant tags: `IMASDK`, `ImaAdsLoader`, `AdTagLoader` and `EventLogger`). Please try what I suggested in my previous message and share all the relevant logging.

If you are worried about whether your app code might be causing the issue, I think the easiest way to check would be to load the ad tag in the ExoPlayer demo app. If that works but your own app doesn't work, then the issue is probably in your app.

**Comment by SetareMaghari** [comment]
using these two links(from https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/tags)  as an example, I get following logs below:

https://pubads.g.doubleclick.net/gampad/ads?iu=/21775744923/external/simid&description_url=https%3A%2F%2Fdevelopers.google.com%2Finteractive-media-ads&tfcd=0&npa=0&sz=640x480&gdfp_req=1&output=vast&unviewed_position_start=1&env=vp&impl=s&correlator=


https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpostlongpod&cmsid=496&vid=short_tencue&correlator=




[INFO:CONSOLE(937)] " [  0.014s] [ima.NativeBridge] OMID measurement with OMSDK SessionClient version 1.3.14-google_20201211 is ready. ", source: https://imasdk.googleapis.com/native/core/3.265.0/native_bridge_debug__en.js (937)
[INFO:CONSOLE(937)] " [  0.081s] [ima.loader.AdsLoaderImpl] Requesting ads using new ads loader. ", source: https://imasdk.googleapis.com/native/core/3.265.0/native_bridge_debug__en.js (937)
[INFO:CONSOLE(937)] " [  0.082s] [ima.loader.AdsLoaderImpl] requestAds, processing external request. ", source: https://imasdk.googleapis.com/native/core/3.265.0/native_bridge_debug__en.js (937)
[INFO:CONSOLE(937)] " [  0.082s] [ima.loader.SequentialAdsLoader] Enqueued new request. ", source: https://imasdk.googleapis.com/native/core/3.265.0/native_bridge_debug__en.js (937)
[INFO:CONSOLE(937)] " [  0.082s] [ima.loader.SequentialAdsLoader] Starting request from queue. ", source: https://imasdk.googleapis.com/native/core/3.265.0/native_bridge_debug__en.js (937)
[INFO:CONSOLE(0)] "A cookie associated with a cross-site resource at http://plus.sabavision.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.", source: https://imasdk.googleapis.com/native/sdkloader/native_sdk_v3_debug.html?sdk_version=a.3.21.0&hl=en&omv=1.3.3-google_20200416&app=com.sabaidea.aparat.dev (0)
[INFO:CONSOLE(937)] " [  0.203s] [ima.loader.AdXmlFetcher] Failed to load ad request URL. Error: Assertion failed: Expected instanceof Document but got Object. ", source: https://imasdk.googleapis.com/native/core/3.265.0/native_bridge_debug__en.js (937)
[INFO:CONSOLE(937)] " [  0.205s] [ima.loader.SequentialAdsLoader] Starting request from queue. ", source: https://imasdk.googleapis.com/native/core/3.265.0/native_bridge_debug__en.js (937)

ImaAdsLoader: onAdError
      AdError [errorType: LOAD, errorCode: AdErrorCode [name: FAILED_TO_REQUEST_ADS, number: 1005], message: There was a problem requesting ads from the server. Caused by: Assertion failed: Expected instanceof Document but got Object.]
        at com.google.ads.interactivemedia.v3.internal.alp.c(IMASDK:4)
        at com.google.ads.interactivemedia.v3.internal.ane.d(IMASDK:66)
        at com.google.ads.interactivemedia.v3.internal.anj.d(IMASDK:5)
        at com.google.ads.interactivemedia.v3.internal.ang.shouldOverrideUrlLoading(IMASDK:2)
        at android.webkit.WebViewClient.shouldOverrideUrlLoading(WebViewClient.java:83)
        at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(chromium-TrichromeWebViewGoogle.apk-stable-410410183:16)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:336)
        at android.os.Looper.loop(Looper.java:181)
        at android.app.ActivityThread.main(ActivityThread.java:7584)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by andrewlewis** [comment]
I did some searching around and couldn't find any reports with the error `[ima.loader.AdXmlFetcher] Failed to load ad request URL. Error: Assertion failed: Expected instanceof Document but got Object.`. Those ad tags load fine for me in the ExoPlayer demo app, so I suggest you check they play for you in the demo app, and, if so, try to figure out what's different about how you are configuring playback and setting the ad tag in your app. You could also try reporting this on the [IMA SDK forum](https://groups.google.com/g/ima-sdk/) in case they can identify the problem based on the error message.

**Comment by SetareMaghari** [comment]
Thanks, ok i will check it with demo app and let you know the root of the issue.
