### ISSUE TITLE
How to use multiple exoplayer 2.x versions in single app

### ISSUE THREAD

**Issue by krackjack234** [google/ExoPlayer#8442]
[REQUIRED] Searched documentation and issues
[REQUIRED] How to bundle multiple exoplayer 2.x versions based players in single app

One of our client is having a requirement to have multiple exoplayer based players in the same app. The app will be playing syndicated contents and hence will have different players from different partners.

Our question is what is the best way to support different exoplayer versions in the same app.

Should we load each player from maven repo independently or bundle the player as part of aar (after changing all exoplayer namespace) to avoid any runtime exception?

Any pointers are welcome

Thanks in advance !

**Comment by andrewlewis** [comment]
> Should we load each player from maven repo independently or bundle the player as part of aar (after changing all exoplayer namespace) to avoid any runtime exception?

I'm not sure about the details of the first suggestion (if you depend on multiple versions without any repackaging I'd expect there will be collisions, or possibly the dependency will just get resolved to the newest version). Repackaging either the sources or classes to avoid collisions should work though.
