### ISSUE TITLE
setBottomPaddingFraction for WebVtt subtitles is not working.

### ISSUE THREAD

**Issue by sravan1213** [google/ExoPlayer#8443]
For following subtitle bottom padding fraction is not getting applied. This used to work fine before 2.12 exoplayer versions.

[webvtt-subtitles.zip](https://github.com/google/ExoPlayer/files/5795277/webvtt-subtitles.zip)

**Comment by icbaker** [comment]
Duplicate of https://github.com/google/ExoPlayer/issues/7934
