### ISSUE TITLE
HDR movie color is wrong when "surface_type" attribute set "texture_view"

### ISSUE THREAD

**Issue by klob** [google/ExoPlayer#8448]
## Issue description
HDR movie color is wrong when surface_type set texture_view. Will ExoPlayer support TextureView mode HDR?
Related issue #7334, I provide  screenshots and test content.

## Reproduction steps
Using the ExoPlayer demo app, add an hdr moive to the Clear DASH list.
Then  set different surface_type to the StyledPlayerView. 
```
  <com.google.android.exoplayer2.ui.StyledPlayerView android:id="@+id/player_view"
      android:layout_width="match_parent"
      android:layout_height="match_parent"
      app:show_shuffle_button="true"
      app:show_subtitle_button="true"
      app:surface_type="surface_view"
    />
```

Here is two screenshots.

1、surface_type set texture_view, the color is wrong
```
app:surface_type="texture_view"
```
![texture_view](https://user-images.githubusercontent.com/8454656/104284263-b2942380-54ec-11eb-866c-5a313635e509.jpg)

2、surface_type set surface_view, the color is right
```
app:surface_type="surface_view"
```

![surface_view](https://user-images.githubusercontent.com/8454656/104284258-b0ca6000-54ec-11eb-9b7a-441334d069d8.jpg)

## Test content

https://user-images.githubusercontent.com/8454656/104285064-06533c80-54ee-11eb-8aef-ce6ea09f6f17.MP4

## Version info

- ExoPlayer version : 2.12.2 
- Phone : Galaxy S10+
- Android os version  : 10

## Something may be usefull

SurfaceView‘s  SurfaceTexture(IGraphicBufferProducer)  is different from TextureView‘s  SurfaceTexture.Where is SurfaceView‘s  SurfaceTexture implements?

**Comment by lcf87** [comment]
@andrewlewis could you take a closer look?

**Comment by andrewlewis** [comment]
I think this is probably due to platform limitations with how texture views work, rather than anything that ExoPlayer is doing. Please use `SurfaceView` instead. If there is a reason you can't use `SurfaceView` please give some more details.

**Comment by sam-m3** [comment]
@andrewlewis I am facing the same problem, and I cannot use `surface_view` because the video lags and thee playback gets way slower, using `texture_view` solved the lagging issue, but it messed up other videos color's.
