### ISSUE TITLE
Playback Issue in context of de-multiplexed HLS Streams 

### ISSUE THREAD

**Issue by ReinhardG** [google/ExoPlayer#845]
We build a simple player application on top of ExoPlayer in context of MPEG-DASH and HLS streaming. In principle the application only demonstrates the playback of encoded streams by our own cloud based encoding system - https://www.bitcodin.com/. For HLS streams, we store audio and video in separate files/playlists. For video tracks everything works fine and as expected, but the audio tracks are not played at all. We follow the same approach (separated audio/video) in context of MPEG-DASH, where both streams play as expected.

If you should need some assets to reproduce the issue, please let me know.

**Comment by ojw28** [comment]
We don't support demuxed audio for HLS yet. This is tracked by #73.

As an aside, if your systems are capable of outputting DASH streams, you (and any clients) should really use them even when we do get around to adding support for demuxed audio for HLS.

**Comment by ojw28** [comment]
Closing as this is tracked by #73.
