### ISSUE TITLE
Android TV/ Exo player issue

### ISSUE THREAD

**Issue by AngelikaSahakyan** [google/ExoPlayer#8450]
[No info provided]

**Comment by AngelikaSahakyan** [comment]
Hi, 
I would like to know what can cause this problem.(Please watch the attached video)
Is this rgb bgr problem ?
It occurs when I run the app on TV box(Android version 9),but I'm not getting this on emulator TV.
Thanks in advance.

**Comment by AngelikaSahakyan** [comment]
https://user-images.githubusercontent.com/49554711/104305707-71007a00-54e6-11eb-9f23-6b7f9fbf5174.mp4

**Comment by lcf87** [comment]
I don't see what the problem is. Please fill out the issue template properly.

**Comment by AngelikaSahakyan** [comment]
![download](https://user-images.githubusercontent.com/49554711/104315211-0a825880-54f4-11eb-8b26-b84f17e82227.png)

**Comment by lcf87** [comment]
Please fill out the issue template properly.

**Comment by lcf87** [comment]
Hi! Please provide complete information as requested in the question template. The template can be
found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/question.md).

Unfortunately we can't answer unclear questions or those with insufficient information.

**Comment by AngelikaSahakyan** [comment]
thanks for quick response 
Solved
