### ISSUE TITLE
Changing Download Location in application

### ISSUE THREAD

**Issue by yoobi** [google/ExoPlayer#8452]
### [REQUIRED] Use case description
I think it's more and more common nowadays to have an SD card inserted in the phone, and thus a neat feature would be to be able to change the download location of Exoplayer between the local Storage and the External Storage while keeping the application running (not being forced to restart it). Just like in the image below

<img width="256" alt="Screenshot 2021-01-12 at 15 11 21" src="https://user-images.githubusercontent.com/17434735/104339961-79fa4700-54f8-11eb-8a55-0d9381047e45.png">

I don't know if Exoplayer should move the downloads from one location to the other upon changing the location (that's to discuss). 
If we don't move the downloads then there should be a function to look in both location for the file.

### Proposed solution

Adding a new API to be able to make the switch and read the file even though it's not in the currently selected location

**Comment by lcf87** [comment]
I see what you mean, but the picture is missing. 
Assigning to master of download @marcbaechinger

**Comment by yoobi** [comment]
I've updated to add the picture :)

**Comment by kgrevehagen** [comment]
Maybe not exactly what you want, but I solved it by just creating two instances of SimpleCache(with different paths which could be internal/external or whatever works best for you), create appropriate DataSources (with the different caches) and provide them on demand based on download location(which you can store locally for each file) for both the act of downloading and for playback.

This will be two individual caches working on each own, but it gets the job done. I guess you can play around with this solution to make it work more like you want, but this is what I have done and works for my use case.

**Comment by yoobi** [comment]
Yeah that could be a solution thanks, i'll try to implement something like that

**Comment by yoobi** [comment]
Thanks @kgrevehagen I've managed to create the change without reloading the application

**Comment by yoobi** [comment]
@kgrevehagen May I ask a quick question, I'm getting a little issue with my DownloadService, did you create 2 DownloadService as well? One for each storage

**Comment by kgrevehagen** [comment]
@yoobi Sorry for the late answer, but great to hear it worked for you!
Regarding the `DownloadService`: I'm using my own `Service` for this, but after having a quick look now, I can't see the need for that for this scenario. It all depends on how you implemented it, but the `DataSource` I create for each download decides the storage.
