### ISSUE TITLE
The ad will not play

### ISSUE THREAD

**Issue by chladto1** [google/ExoPlayer#8453]
Scenario. There are 5 midrolls on the timeline. I played the third one and jumped in front of the second unplayed. If I jump anywhere behind the second midroll, the ad should start playing. The ad will not play if I jump between the third and fourth midroll.

Android version and device independent.
ExoPlayer version 2.11.8

![not playing ad](https://user-images.githubusercontent.com/62881052/104329346-1a4a6e80-54ed-11eb-8d3e-55d524ba1cd1.jpg)

**Comment by lcf87** [comment]
Hi! Please provide complete information as requested in the issue template. The issue template can
be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md).
If you're unable to share [bug reports](https://developer.android.com/studio/debug/bug-report) or
test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format
"Issue #1234" ("#1234" is replaced with your issue number). Please also update this issue to
indicate you've done this.

**Comment by andrewlewis** [comment]
> I played the third one and jumped in front of the second unplayed. If I jump anywhere behind the second midroll, the ad should start playing. The ad will not play if I jump between the third and fourth midroll.

Currently, our implementation assumes that each ad gates access to the following piece of content. This means that for your screenshot if the user seeks between 2 and 3 or between 4 and the end they will see an ad, but if they seek before the 2 or between 3 and 4 they will not see an ad. The expectation that "If I jump anywhere behind the second midroll, the ad should start playing." is not consistent with that. So I think this is working as expected, but if I've misunderstood please provide some more details.
