### ISSUE TITLE
DASH: Support for SegmentBase with external RepresentationIndex

### ISSUE THREAD

**Issue by ronak2121** [google/ExoPlayer#8455]
### [REQUIRED] Use case description
We use dynamic manifest/sidx creation on the server side to support dynamic clear lead injection, custom clipping scenarios (where users can select sections of streams to play), and other dynamic stream creation. Due to this, and our desire to use SegmentBase, we end up having to dynamically generate sidx atoms instead of having them pre-baked into the assets.

We are using the MPEG DASH main profile as defined here: https://dashif.org/identifiers/profiles/ and trying to use an external RepresentationIndex by way of the RepresentationIndex element as defined in the Dash XSD: https://github.com/Dash-Industry-Forum/MPEG-Conformance-and-reference-source/blob/master/conformance/MPDValidator/schemas/DASH-MPD.xsd#L291 but it looks like Exoplayer does not support this.

### Proposed solution
We'd like for Exoplayer to support an external RepresenatationIndex based on the MPEG DASH standard, where all segment offsets would be relative to the end of the primary content's init-segment.

### Alternatives considered
We can switch to SegmentLists instead of SegmentBase, but this bloats our manifests from 2KB to almost 10 MB.

**Comment by ronak2121** [comment]
We are currently on Exoplayer 2.12.1 and would like this enhancement made to Exoplayer so we can go out the gate with SegmentBase support, instead of having to worry about backwards compatibility later.

We would have to have this change ready for consumption by the end of January so we can launch with this.

**Comment by ojw28** [comment]
There's quite a bit here that I'm unclear on. In general, I don't think you need to generate `sidx` boxes for the features you're trying to implement, and your approach sounds very unusual.

1. How does being able to specify a different `sidx` help with clear lead injection? Please could you outline in more detail how this works? Assuming the feature here is to prefix an additional piece of content (e.g., an ad) before a main piece of content, the normal way to do this within the DASH specification is to add an additional `Period` element.
2. Why does clipping require being able to specify a different `sidx`? Can't you just serve the regular asset and start/end playback at non-zero positions (or, specific to ExoPlayer, use `ClippingMediaSource`)?

> where all segment offsets would be relative to the end of the primary content's init-segment.

3. Is this defined in the spec anywhere? If so, could you point me to it?

The only reference I can find around using `RepresentationIndex` with ISO BMFF DASH suggests that the index will still be _within_ the media segment, which your proposed approach presumably does not adhere to. This is from `23009-1:2014`:

> Index Segments shall not be present. However, a RepresentationIndex element or a @indexRange attribute may be present to signal the byte range for Segment Index _within_ a Media Segment.

The DASH Industry Forum also [concluded that use of RepresentationIndex is undefined for ISO BMFF DASH](https://github.com/Dash-Industry-Forum/DASH-IF-IOP/issues/171#issuecomment-374613984). I couldn't find any examples of `RepresentationIndex` being used other than with MPEG-TS.

**Comment by ronak2121** [comment]
Hey Ollie,

Answering your questions:

1. Clear Lead is dynamically injected when we generate the manifest, by injecting the lead and offsetting the sidx to start at the end of the lead. I learned yesterday about the presentationTimeOffset attribute on SegmentBase. I imagine we can use this to offset the start of when lead ends and sidx segments begin.

2. We do not trust clients to use a start/end value returned by services and not play clips outside of this range, therefore we clip manifests dynamically at the edge. This requires us to segment content at 1s intervals. But, since we do not want clients to make network calls for every single segment of audio (our streams are audio only), we aggregate the 1s segments into 20s ones at the edge.

I also only saw the XSD and saw that you can specify an external RepresentationIndex, and saw usage out there, but never saw any documentation that says you can't with ISO-BMFF. 

To bake the sidx into our files, it would mean having to pre-bake our segment sizes in up front, or dynamically inject them into the asset while returning the media through the CDN...which are options we can pursue if we have to, but we wanted to explore this option first since it would be much simpler.

**Comment by ojw28** [comment]
You might be able to prove me wrong, but my guess is that you'll find client support for external `RepresentationIndex` in ISO BMFF DASH to be non-existent. As per my previous response, the DASH Industry Forum appears to have concluded that it doesn't have a well defined behaviour, which was also the conclusion I came to through reading the specification.

I still don't understand why you don't use two `Period` elements for (1), which is the standard way to concatenate two pieces of content in DASH. This is likely to be far more widely supported than what you're proposing.

For (2), do you control the clients? If you do, why can't you trust them to apply start/end values? If you don't, then I doubt you'll be able to trust them to correctly support external `RepresentationIndex` for the reasons mentioned above. If you don't control the clients then I think you should try and implement something that's more clearly within the DASH spec.

**Comment by ronak2121** [comment]
For (1) We do use two Periods for clear, but it was our bad in not fully researching presentationTimeOffset, and how we can use it to offset where in the sidx the player reads from. So I think this part of the argument is superfluous now.

As for (2), we use clips for various purposes and generate samples prior to purchase (which is a clip), and while we do control the clients, we do not trust since it opens us up for fraud scenarios with hacking.

**Comment by ronak2121** [comment]
Closing this as we figured out an alternative without requiring changes to Exoplayer. Thanks for the help Ollie!
