### ISSUE TITLE
NuEyes device does not return true for Widevine on isCryptoSchemeSupported

### ISSUE THREAD

**Issue by Kusand** [google/ExoPlayer#8457]
I am attempting to work with ExoPlayer on a device known as the NuEyes e2 (https://www.nueyes.com/nueyes-e2), which is based on the Pico VR devices. The About section of the device indicates it is running Android 8.1, which meets the requirements for all types of playback according to the supported devices list. However, when I use the demo app from this project to test playback, `FrameworkMediaDrm.isCryptoSchemeSupported` returns false for Widevine's UUID. Can you help me understand what I need to do next in order to support Widevine on this device?

**Comment by icbaker** [comment]
@rrfrias could you take a look?

**Comment by ojw28** [comment]
I think that error simply indicates that the device does not support Widevine. You would need to ask the device manufacturer why this is the case. From ExoPlayer's point of view I think everything is working as intended, in that we're querying the underlying device for Widevine support, and finding that there isn't any.

**Comment by Kusand** [comment]
Thanks. I'll follow up with them.
