### ISSUE TITLE
What is proper way to create audio playlist?

### ISSUE THREAD

**Issue by PawelDedio** [google/ExoPlayer#846]
How can I create playlist with multiple mp3 stream url? I am thinking about extending MediaCodecAudioTrackRenderer and override handleMessage(), but how can I load multiple uri to Sample Source and prebuffer next song? I don't found any information about this.

**Comment by kunalbhatia** [comment]
@PawelDedio, anything found yet? I'm trying to switch from Classic MediaPlayer to ExoPlayer? Want to implement a Music/Video player with playlist, subtitles etc, similar to Saavn, is it good time to switch to ExoPlayer right now? Asking you as you're 4 month ahead of me.

**Comment by Ash256** [comment]
Can I have few codes example to apply reg this issue? TQ

**Comment by andrewlewis** [comment]
#1270 tracks adding support for playlists. This is non-trivial to implement because it is necessary to buffer future sources before the current one finishes, so that transitions between sources can be seamless.
