### ISSUE TITLE
How can I get the duration of HLS Stream of .m3u8 playlist ?

### ISSUE THREAD

**Issue by giangpham2811** [google/ExoPlayer#8463]
I have used SimpleExoPlayer to play this Stream but I have seen some application can get position and duration to manage player.
I have used getDuration() but it is return null or sometimes is minus interger

**Comment by lcf87** [comment]
I'm not exactly sure what are you trying to achieve here, please elaborate on that.

I invite you to take a look at class `StyledPlayerControlView`, in which the duration of the media is gathered, specifically here:

https://github.com/google/ExoPlayer/blob/16b51d689c6a1a5ec327d1977a5fe8de9fefe41e/library/ui/src/main/java/com/google/android/exoplayer2/ui/StyledPlayerControlView.java#L1356-L1383

**Comment by giangpham2811** [comment]
@ojw28 so instead of UI lib from Exo player, I implemented with my own custom exoPlayer and extend from simpleExoPlay, and now I want to get the duration and position of HLS stream while playing but it usually returns null or sometimes is minus.
![Screenshot from 2021-01-21 11-37-22](https://user-images.githubusercontent.com/47731369/105280740-11d4f080-5bdd-11eb-9f8e-d325a0d9d84c.png)
I got some screenshot for the extended exoplayer , I cant not share the source code via the privacy.

**Comment by ojw28** [comment]
`Player.getDuration()` returns a primitive type, so it's not possible for it to be returning null. It can return `C.TIME_UNSET == Long.MIN_VALUE + 1` if the duration is unknown, as per the documentation. You can listen to `EventListener.onTimelineChanged` to be notified of changes in the player's view of the media, which may include the duration becoming known.
