### ISSUE TITLE
Support PCM WAV RF64 format

### ISSUE THREAD

**Issue by parthkalavadia** [google/ExoPlayer#8467]
Does EXOPlayer supports PCM containerized in WAV with type - RF64?

**Comment by ojw28** [comment]
I don't think so, although it's probably not too difficult to add support. We would likely accept a high quality pull request that does so. Marking as an enhancement. A couple of useful resources:

1. [Wikipedia page](https://en.wikipedia.org/wiki/RF64)
2. [Specification](https://tech.ebu.ch/docs/tech/tech3306v1_0.pdf)
3. https://github.com/iluvcapra/wavinfo/issues/3#issuecomment-505129130 might be useful for testing, although I didn't verify

**Comment by KasemJaffer** [comment]
I just created PR containing the support for RF64 wave files. Hopefully it gets reviewed and merged soon

https://github.com/google/ExoPlayer/pull/9543

**Comment by kim-vde** [comment]
I am closing this issue as the corresponding pull request has now been merged.
