### ISSUE TITLE
How to get NV21 data of video

### ISSUE THREAD

**Issue by Lua12138** [google/ExoPlayer#8468]
## expectant
```
Input Source(yuv420p) -> ExoPlayer -> UI(Usually presented in `Surface`)
                                                |
                                                | (duplicated NV21 data)
                                                |
                                                --> `Byte[]` or `ByteBuffer` -> The application handles it itself -> UI (Displayed on another surface)
```

## the usage scenarios

I want to make a simple video editing tool. There are two `Surface` on the interface, the one on the left shows the original video content and the one on the right shows the content that I have processed. I hope users can see the effects before and after editing synchronously.

For the pre-editing effect, it is only necessary to simply let ExoPlayer play the video, and for the edited effect, I need to modify it in real time through the program, but I can't get the video data when ExoPlayer plays normally.

---

I tried override `MediaCodecVideoRenderer.processOutputBuffer(...)` with `codec.getOutputImage(bufferIndex)`, but it always return `null`

```kotlin
class CustomMediaCodecVideoRenderer(
    context: Context,
    mediaCodecSelector: MediaCodecSelector,
    allowedJoiningTimeMs: Long,
    eventHandler: Handler?,
    eventListener: VideoRendererEventListener?,
    maxDroppedFramesToNotify: Int
) : MediaCodecVideoRenderer(
    context,
    mediaCodecSelector,
    allowedJoiningTimeMs,
    eventHandler,
    eventListener,
    maxDroppedFramesToNotify
) {

    override fun processOutputBuffer(
        positionUs: Long,
        elapsedRealtimeUs: Long,
        codec: MediaCodec?,
        buffer: ByteBuffer?,
        bufferIndex: Int,
        bufferFlags: Int,
        sampleCount: Int,
        bufferPresentationTimeUs: Long,
        isDecodeOnlyBuffer: Boolean,
        isLastBuffer: Boolean,
        format: Format
    ): Boolean {
        val image = codec?.getOutputImage(bufferIndex) // <-- alwasy be null
        if (image != null) {
            val y = image.planes[0].buffer.duplicate()
            val u = image.planes[1].buffer.duplicate()
            val v = image.planes[2].buffer.duplicate()
            val sizeY = y.remaining()
            val sizeU = u.remaining()
            val sizeV = v.remaining()
            val nv21 = ByteArray(sizeY + sizeU + sizeV)
            y.get(nv21, 0, sizeY)
            v.get(nv21, sizeY, sizeV)
            u.get(nv21, sizeY + sizeV, sizeU)
            Log.d("CustomMediaCodecVideoRenderer", "processOutputBuffer: ${nv21.size}")
        }

        return super.processOutputBuffer(
            positionUs,
            elapsedRealtimeUs,
            codec,
            buffer,
            bufferIndex,
            bufferFlags,
            sampleCount,
            bufferPresentationTimeUs,
            isDecodeOnlyBuffer,
            isLastBuffer,
            format
        )
    }
}
```

**Comment by andrewlewis** [comment]
`getOutputImage` is documented to return `null` if you are rendering to a `Surface`. You'd need to use [`ByteBuffer` mode](https://developer.android.com/reference/android/media/MediaCodec#raw-video-buffers) to be able to use that (see the [javadoc](https://developer.android.com/reference/android/media/MediaCodec#getOutputImage(int)) on the return value), but we don't have any plans to support this in ExoPlayer as it's going to be much slower than rendering to a `Surface`.

I think the better approach for what you are doing is to have the codec render to a `SurfaceTexture` and process that as a GL texture. You can copy each frame to one view, and also process it and copy the processed output to the second view. This assumes you can do the processing you are trying to do in a GL shader. The [gldemo](https://github.com/google/ExoPlayer/tree/release-v2/demos/gl) may be a useful starting point for this.

If you really need to access the data on the CPU you could also try reading back from the `Surface` using `PixelCopy` or `ImageReader` (I don't know if this is going to be more efficient or worse than using `ByteBuffer` mode).

**Comment by Lua12138** [comment]
Thank you for your reply.
If I want to get NV21 data before rendering to Surface, and make some modifications before rendering, is there any suggestion?

```
Input Source(yuv420p) -> ExoPlayer -> (modify NV21 data,eg modify Y of YUV) -> UI(Usually presented in `Surface`)
```

**Comment by andrewlewis** [comment]
You'd need to use `MediaCodec` in `ByteBuffer` mode then render to the surface yourself, or try rendering to a `Surface` created from a `SurfaceTexture` then read back so you can process the bitmap from the CPU (as described at the end of my previous comment).
