### ISSUE TITLE
Which callbacks should be used to show/remove progress loader while preparing/buffering and playing states?

### ISSUE THREAD

**Issue by gupta-sachin** [google/ExoPlayer#847]
I was successfully using onPlayerStateChanged() till previous release but now with release 1.5.0, even when this call is received with STATE_READY and playWhenReady=true, the video is not being played. It starts playing after few milliseconds and it seems that video is hanged as we have removed the loader and all other app specific initial state views.

**Comment by ojw28** [comment]
Waiting for STATE_READY is the right thing to do. Sounds like something else is wrong, but you haven't provided sufficient information for us to determine what that is. Please see [this](https://google.github.io/ExoPlayer/2015/10/01/reporting-issues.html). Thanks!

**Comment by gupta-sachin** [comment]
As demo app does not have any progress loader or any view that are to be shown only when video is not being played so issue is not easily reproducible. I will get more details and update here.

**Comment by ojw28** [comment]
It does [print state changes](https://github.com/google/ExoPlayer/blob/master/demo/src/main/java/com/google/android/exoplayer/demo/EventLogger.java#L69) to the logs though, so you should be able to tell whether the expected state changes are occurring by looking at logcat. Alternatively, it should be pretty trivial for you to fork ExoPlayer and add a loading spinner locally for debugging purposes.

Note also that apps like YouTube do show a spinner based on this logic, and haven't reported any issues.
