### ISSUE TITLE
Cannot find sync byte. Most likely not a Transport Stream

### ISSUE THREAD

**Issue by lsgfly** [google/ExoPlayer#8471]
Issue description
I have an M3U8 file.
There will be a problem when it's played to 2:30

Link to test content
Can reproduce with this link
I will provide the m3u8 file.

Version of ExoPlayer being used
2.8.2
I also tested in the latest version

Device(s) and version(s) of Android being used
Vivo x50

A full bug report captured from the device
```
:19:47.322  3808  6153 E ExoPlayerImplInternal:   com.google.android.exoplayer2.ExoPlaybackException: Source error
01-18 16:19:47.322  3808  6153 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:554)
01-18 16:19:47.322  3808  6153 E ExoPlayerImplInternal:       at android.os.Handler.dispatchMessage(Handler.java:103)
01-18 16:19:47.322  3808  6153 E ExoPlayerImplInternal:       at android.os.Looper.loop(Looper.java:230)
01-18 16:19:47.322  3808  6153 E ExoPlayerImplInternal:       at android.os.HandlerThread.run(HandlerThread.java:67)
01-18 16:19:47.322  3808  6153 E ExoPlayerImplInternal:   Caused by: com.google.android.exoplayer2.ParserException: Cannot find sync byte. Most likely not a Transport Stream.
01-18 16:19:47.322  3808  6153 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.extractor.ts.TsExtractor.findEndOfFirstTsPacketInBuffer(TsExtractor.java:453)
01-18 16:19:47.322  3808  6153 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.extractor.ts.TsExtractor.read(TsExtractor.java:320)
01-18 16:19:47.322  3808  6153 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.source.hls.BundledHlsMediaChunkExtractor.read(BundledHlsMediaChunkExtractor.java:67)
01-18 16:19:47.322  3808  6153 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.source.hls.HlsMediaChunk.feedDataToExtractor(HlsMediaChunk.java:405)
01-18 16:19:47.322  3808  6153 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.source.hls.HlsMediaChunk.loadMedia(HlsMediaChunk.java:375)
01-18 16:19:47.322  3808  6153 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.source.hls.HlsMediaChunk.load(HlsMediaChunk.java:342)
01-18 16:19:47.322  3808  6153 E ExoPlayerImplInternal:       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
01-18 16:19:47.322  3808  6153 E ExoPlayerImplInternal:       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
01-18 16:19:47.322  3808  6153 E ExoPlayerImplInternal:       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
01-18 16:19:47.322  3808  6153 E ExoPlayerImplInternal:       at java.lang.Thread.run(Thread.java:919)
```

**Comment by lsgfly** [comment]
[m3u8.txt](https://github.com/google/ExoPlayer/files/5828908/m3u8.txt)

**Comment by lsgfly** [comment]
This is the m3u8 file.
In order to play it, you need  set the  userAgent "Mozilla/5.0 (Linux; Android 10; V1936A; wv) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.84 Mobile Safari/537.36"

**Comment by ojw28** [comment]
@AquilesCanta - I can reproduce this easily with the demo app (tip of tree), but I can't work out what's going wrong. It looks like the failure occurs on different segments each time, which might suggest that the server is sporadically returning incorrect data. However, I tried repeatedly requesting one of the segments that I saw the failure occur on using my desktop machine, and the downloaded data was always identical.

**Comment by zhengzhuoxing** [comment]
Have you solved it now

**Comment by zhengzhuoxing** [comment]
I had the same problem

**Comment by AquilesCanta** [comment]
I have a list of urgent things I need to look into. @christosts, if you have time please take a look. Let me know if I can assist you.

**Comment by christosts** [comment]
Does the playlist attached [above](https://github.com/google/ExoPlayer/issues/8471#issuecomment-762090700) still point to valid content? I tried with ExoPlayer 2.13.3 (and set the user-agent as instructed), the player fails to parse the incoming data:

```
com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (FlvExtractor, FlacExtractor, WavExtractor, FragmentedMp4Extractor, Mp4Extractor, AmrExtractor, PsExtractor, OggExtractor, TsExtractor, MatroskaExtractor, AdtsExtractor, Ac3Extractor, Ac4Extractor, Mp3Extractor, JpegExtractor) could read the stream.
```

I downloaded the first two TS files manually (with the agent specified) and parsed them with [tsduck](https://tsduck.io/), the files appear to not have any valid streams.

**Comment by lsgfly** [comment]
[m3u8.txt](https://github.com/google/ExoPlayer/files/6498272/m3u8.txt)
It will occur in 01:26 .

**Comment by christosts** [comment]
Apologies for the delay, is the stream still working?

**Comment by zourb** [comment]
I had the same problem. any updates about this?
