### ISSUE TITLE
AC-3 and E-AC-3, DTS, TrueHD, ALAC, etc. exact seek not working or not playable even with FFmpeg extension

### ISSUE THREAD

**Issue by T-10001** [google/ExoPlayer#8472]
I am playing an mkv file with 2 audio tracks: AC-3 and E-AC-3.

When the file is playing, I use the seek buttons with increment of 1000ms. The seek is not exact. It seems to jump. For example, if I seek forwards 1000ms from current playback position of 10 seconds, it jumps to new position of 11 seconds and then jumps back 1000ms again to position of 10 seconds.

It occurs for both audio tracks with and without the FFmpeg extension.

- ExoPlayer version number: 2.11.4
- Android version: 9
- Android device: Samsung Galaxy S8

**Comment by ojw28** [comment]
Hi! Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md). If you're unable to share [bug reports](https://developer.android.com/studio/debug/bug-report) or test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #1234" ("#1234" is replaced with your issue number). Please also update this issue to indicate you've done this.

**Comment by T-10001** [comment]
I have sent email to the dev.exoplayer@gmail.com with more details and test file.

**Comment by T-10001** [comment]
The FFmpeg extension appears to work (audio formats are playable and seek is exact although possibly slow) if I use Exoplayer version 2.12.2

**Comment by ojw28** [comment]
Are you saying that this no longer reproduces with new versions of ExoPlayer?

**Comment by T-10001** [comment]
Don't know about all new versions of ExoPlayer. Have only tested with 2.11.4 where it doesn't work and 2.12.2 where it does work.

**Comment by ojw28** [comment]
Given it works in the newer version, I think we can close this as being fixed already. Please let us know if the issue still reproduces on the latest version. Thanks!
