### ISSUE TITLE
Make a call just before the playback

### ISSUE THREAD

**Issue by Kamil-H** [google/ExoPlayer#8476]
What is the best way to make a call just before the playback starts?
I've got a use case where I need to make a call to the API for a content `mediaUrl` that contains stitched advertisement just before the playback (ad provider requirement).
Recently I'm migrating from the `ConcatenatingMediaSource` to new Playlist API. Before I was passing url that I wanted to call as a `MediaSource`'s url and then by using custom `HttpDataSource.Factory` (`OkHttpDataSourceFactory`) that has Interceptor implemented I was able to use passed url and perform a call to the API and proceed with it.
In Playlist API "world" it is not possible, because `mediaItem.uri` is getting processed before being passed to playback for extract the type of media purpose. That's why I thought that the best way to implement such case will be to implement custom `ExtractorsFactory`. There I should be able to get `uri`, make a call and proceed with correct `mediaUrl`. Unfortunately it is not working as I expected.

I've implemented it as following:
```
class AdExtractorFactory @Inject constructor(
    private val getAdvertisement: GetAdvertisement,
) : ExtractorsFactory {

    private val defaultExtractor = DefaultExtractorsFactory()

    override fun createExtractors(): Array<Extractor> = defaultExtractor.createExtractors()

    override fun createExtractors(uri: Uri, responseHeaders: MutableMap<String, MutableList<String>>): Array<Extractor> {
        return when (val mediaUrl = MediaUrl.create(url = uri.toString())) {
            is HlsWithAd -> runBlocking {
                val url = getAdvertisement(mediaUrl)
                defaultExtractor.createExtractors(Uri.parse(url), responseHeaders)
            }
            is Progressive, is Hls -> defaultExtractor.createExtractors(uri, responseHeaders)
        }
    }
}
```
I'm passing `AdExtractorFactory` to `DefaultMediaSourceFactory` which is passed to `ExoPlayer` via `SimpleExoPlayer.Builder(context).setMediaSourceFactory(mediaSourceFactory)` method.
The behavior I'm observing is that in case `url` cannot be "parsed" (extracted) above `createExtractors` method is getting called, I'm able to make a call, get correct `mediaUrl` and I'm passing it to `defaultExtractor.createExtractors(Uri.parse(url), responseHeaders)` method. 
The problem is my playback is not starting and I'm getting:
```
E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:554)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (FlvExtractor, FlacExtractor, WavExtractor, FragmentedMp4Extractor, Mp4Extractor, AmrExtractor, PsExtractor, OggExtractor, TsExtractor, MatroskaExtractor, AdtsExtractor, Ac3Extractor, Ac4Extractor, Mp3Extractor) could read the stream.
        at com.google.android.exoplayer2.source.BundledExtractorsAdapter.init(BundledExtractorsAdapter.java:92)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1024)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
``` 
Am I missing something? Maybe I'm passing my custom `ExtractorsFactory` in a wrong place?
Is there a better way to achieve what I described above?

**Comment by ojw28** [comment]
An `Extractor` is a component that parses loaded data. It's not responsible for actually loading the data, and the `uri` argument that's passed to `DefaultExtractorsFactory.createExtractors` has no effect on where the data is loaded from.

The right place to be intercepting and modifying the URL is in `DataSource` components. We have documentation that I think covers your exact use case, [here](https://exoplayer.dev/customization.html#customizing-server-interactions). Specifically, look at the last example in that section, which uses `ResolvingDataSource.Factory` to re-write the URL. In your case you would want to implement `resolveUri` to call your `getAdvertisement` method.

Does that help?

**Comment by Kamil-H** [comment]
Thank you @ojw28 for your response. It definitely helps me understand the way it should be implemented.

I implemented a custom `Resolver` that is running my logic to get correct `mediaUrl` and I'm passing it like that:
```
class AdUriResolver @Inject constructor(private val getAdvertisement: GetAdvertisement) : ResolvingDataSource.Resolver {

    override fun resolveDataSpec(dataSpec: DataSpec): DataSpec {
        return if (shouldFetch(dataSpec.uri)) {
            runBlocking {
                val advertisementUrl = getAdvertisement(dataSpec.uri) 
                if (advertisementUrl != null) {
                    DataSpec(Uri.parse(advertisementUrl))
                } else {
                    throw IOException()
                }
            }
        } else {
            dataSpec
        }
    }
    
    private fun shouldFetch(uri: Uri): Boolean { ... }
}
```
I'm creating my `MediaSourceFactory` in a following way:
```
@Provides
    fun provideMediaSourceFactory(context: Context, cache: Cache, resolver: AdUriResolver, okHttpClient: OkHttpClient): MediaSourceFactory {
        val httpDataSourceFactory = OkHttpDataSourceFactory(okHttpClient, provideUserAgent(context))

        val dataSourceFactory = ResolvingDataSource.Factory(httpDataSourceFactory, resolver)

        val cacheDataSourceFactory = CacheDataSource.Factory()
            .setCache(cache)
            .setUpstreamDataSourceFactory(dataSourceFactory)
            .setCacheReadDataSourceFactory(FileDataSource.Factory())
            .setFlags(CacheDataSource.FLAG_IGNORE_CACHE_ON_ERROR)

        return DefaultMediaSourceFactory(cacheDataSourceFactory)
    }
```
and I'm passing it to `SimpleExoPlayer`. When I'm adding some logs, I can clearly see that my logic is getting executed and proper url is getting returned from `resolveDataSpec`, however I'm still getting following error when trying to play the playlist item that contains this special url:
```
E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:554)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (FlvExtractor, FlacExtractor, WavExtractor, FragmentedMp4Extractor, Mp4Extractor, AmrExtractor, PsExtractor, OggExtractor, TsExtractor, MatroskaExtractor, AdtsExtractor, Ac3Extractor, Ac4Extractor, Mp3Extractor) could read the stream.
        at com.google.android.exoplayer2.source.BundledExtractorsAdapter.init(BundledExtractorsAdapter.java:92)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1024)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
```

Am I missing something? Maybe I should pass `MediaSourceFactory` somewhere else?

**Comment by Kamil-H** [comment]
Closing as I opened a new issue here: https://github.com/google/ExoPlayer/issues/8487

**Comment by ojw28** [comment]
`DataSpec` contains more information than just the URL. Your implementation is throwing away any other information in the `DataSpec`. In particular, I think this line is problematic:

```
val advertisementUrl = getAdvertisement(dataSpec.uri) 
if (advertisementUrl != null) {
    DataSpec(Uri.parse(advertisementUrl))                         <-------------
} else {
    throw IOException()
}
```

Use `dataSpec.withUri(Uri.parse(advertisementUrl))` instead, to retain any other information in the original `DataSpec`.

Regarding replacing a progressive link with an HLS link, I don't think that's ever going to work, because the type of the media (progressive vs HLS) has already been determined prior to the point at which the URL is being resolved. The failure you're seeing in https://github.com/google/ExoPlayer/issues/8487 is because the determined type is progressive, but the actual content you're trying to play is HLS. `ProgressiveMediaSource` cannot detect the content type because it doesn't handle HLS media, and so playback fails.

**Comment by Kamil-H** [comment]
First of all, thank you for your time and response, I really appreciate that.
Is there any way to "instruct" `MediaType` that the passed `mediaUri` will resolve to `Hls` instead of `Progressive`? I would guess that maybe `setMimeType` should help, but I'm not sure what should I pass there.

**Comment by ojw28** [comment]
If you know that your URL is going to resolve to an HLS stream, you should use `setMimeType(MimeTypes.APPLICATION_M3U8)`.

**Comment by Kamil-H** [comment]
It's working. Thank you for your advices and time.
