### ISSUE TITLE
ExoPlayer Ima SDK Extension Offline Usage Stuck!!

### ISSUE THREAD

**Issue by nebyan** [google/ExoPlayer#8483]
Hi ExoPlayer Team. 
I have lived a problem when try to play ima url within exoplayer ima sdk extension

The case happens like that.
-I turn off the internet of the device
-I open the application that I want to play ima url.
-The app waits for response from Ima extensions for exoplayer. But it just stucks and never sends any logs.
-I turn on the internet and it plays ima urls in success
-Then I close the internet and try to play ima url. It sends error. I catch error and my app continue to life
-This case happens when I open the application offline for the first time
-This case happens in any exoplayer version and any devices.

I wish you solve this problem.
Thanks

**Comment by ojw28** [comment]
Hi! Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md). If you're unable to share [bug reports](https://developer.android.com/studio/debug/bug-report) or test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #1234" ("#1234" is replaced with your issue number). Please also update this issue to indicate you've done this.
