### ISSUE TITLE
No static method getLooper()Landroid/os/Looper; in class Lcom/google/android/exoplayer2/z1/k0

### ISSUE THREAD

**Issue by aedgar777** [google/ExoPlayer#8485]
Using the latest version of exoplayer:

```
 implementation "com.google.android.exoplayer:exoplayer:2.12.3"
 implementation "com.google.android.exoplayer:extension-ima:2.12.3"
```

The DefaultExoCreator class calls Util.getLooper() in createPlayer():

```
 @NonNull @Override public SimpleExoPlayer createPlayer() {
    return new ToroExoPlayer(toro.context, renderersFactory, trackSelector, loadControl,
        new DefaultBandwidthMeter(), config.drmSessionManager, Util.getLooper());
  }

```

However, the UTIL class doesn't have that method, only

```
public static Looper getCurrentOrMainLooper() {
    @Nullable Looper myLooper = Looper.myLooper();
    return myLooper != null ? myLooper : Looper.getMainLooper();
  }
```

When I call play() on an ExoPlayable it crashes gives me the above error:

`java.lang.NoSuchMethodError: No static method getLooper()Landroid/os/Looper; in class Lcom/google/android/exoplayer2/z1/k0; or its super classes (declaration of 'com.google.android.exoplayer2.z1.k0' appears in /data/app/~~wEGp5TVoXpOMXwPqfVqJ0A==/com.eight.app.qa-yBkNhO_wgq9FeKEPO1O3YA==/base.apk)`

For what it's worth, I also get a "library source does not match the bytecode for class DefaultExoCreator" flag on when I have  DefaultExoCreator.java open but I already cleaned/rebuilt my project and invalidated the cache. Am I missing something?

**Comment by ojw28** [comment]
`DefaultExoCreator` is not part of ExoPlayer. It sounds like it is not compatible with ExoPlayer version 2.12.3.

We do not guarantee API stability between versions, so `DefaultExoCreator` will need updating to work properly with the version of ExoPlayer that you're trying to use.
