### ISSUE TITLE
Seeking causes playback stuck buffering and not loading

### ISSUE THREAD

**Issue by adaleydev** [google/ExoPlayer#8488]
[Issue description]
When streaming using DASH, audio plays fine without seeking, but if seek occurs, then buffering fails and indicates "Target buffer size reached with less than 500ms of buffered media data." The audio will play again if you seek back to beginning.

[Reproduction steps]
Using Exoplayer Sample app, load the following url: 
https://d274s1rljlgioj.cloudfront.net/test.mpd
It will play, but will get stuck when seek

[Log]
[exoplayer_dash_log.txt](https://github.com/google/ExoPlayer/files/5852030/exoplayer_dash_log.txt)

[Version of ExoPlayer being used] 
Tested on 2.12.1 and using sample Exoplayer app on 2.12.3

[Device(s) and version(s) of Android being used]
Tested on Pixel 3a API 30 and Pixel 2 API 25

**Comment by ronak2121** [comment]
This was an issue with our media. Closing.
