### ISSUE TITLE
How to make complete Player clickable for VAST Ads

### ISSUE THREAD

**Issue by tcudev** [google/ExoPlayer#8489]
Is there any option to get the click through link of the "learn more" button and somehow make the complete Player clickable?

I just want that the behaviour is the same as in a normal browser. If i click anywhere on the video it should open a browser with the url link and not only when i click on that tiny learn more label 

I tried to use MadManPlayer which allows to customize the ad ui but it does not work for the newest version of ExoPlayer so this is not a solution.

I tried to get the Clickthrough Link of the VAST ad with an AdEventListener but it seems that is not given anywhere. Anyone has an idea?

**Comment by andrewlewis** [comment]
The IMA SDK controls the behavior of the UI overlay on top of the player and would need to implement the behavior you're asking for, or provide a way for the app to trigger showing more info programmatically (I don't think this exists already), so please ask on their support forum: https://groups.google.com/g/ima-sdk/. If there's an API to enable this behavior then let us know here and we can add support for it in the ExoPlayer IMA extension. Thanks.
