### ISSUE TITLE
External_CONTENT_URI not playing video (ver:2.10.6)

### ISSUE THREAD

**Issue by mihirmodiofficial** [google/ExoPlayer#8497]
```
            try{
                filecount++
/*
                val cr = applicationContext.contentResolver
                val flg: Int = Intent.FLAG_GRANT_WRITE_URI_PERMISSION or
                        Intent.FLAG_GRANT_READ_URI_PERMISSION
                cr.takePersistableUriPermission(Uri.fromFile(File(path)), flg)
*/
                val dataSpec = DataSpec(Uri.fromFile(File(path)))
                val fileDataSource = FileDataSource()
                try {
                    fileDataSource.open(dataSpec)
                } catch (e: FileDataSourceException) {
                    e.printStackTrace()
                }

                val factory = DataSource.Factory { fileDataSource }

/*
                    mediaSource = new ExtractorMediaSource(fileDataSource.getUri(),
                            factory, new DefaultExtractorsFactory(), null, null);
*/
                mediaSource = ProgressiveMediaSource.Factory(factory).createMediaSource(fileDataSource.uri)


            }
            catch (e: Exception){
                e.printStackTrace()
            }
```

**Comment by ojw28** [comment]
Hi! Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md). If you're unable to share [bug reports](https://developer.android.com/studio/debug/bug-report) or test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #1234" ("#1234" is replaced with your issue number). Please also update this issue to indicate you've done this.

**Comment by mihirmodiofficial** [comment]
As i updated my code make targetSdkVersion 30 i am getting External_CONTENT_URI from scoped storage that i am passing in mediasource  Pre targetsdkversion 30 its working and playing the video from local device storage. I am using exoplayer version(Please see below)  and also Previously i was using ExtractorMediaSource which is deprecated now whats the reason?

com.google.android.exoplayer:exoplayer:2.10.6

**Comment by ojw28** [comment]
Unless you provide complete information as requested by the issue template, including clear reproduction steps (ideally in the form of a minimal sample project, that you can provide as source code via GitHub, and that reproduces the issue), then we are not in a position to help with this.
