### ISSUE TITLE
Can't repeat when using MergingMediaSource for 2+ MediaSource

### ISSUE THREAD

**Issue by simline** [google/ExoPlayer#8498]
code in Application class:

```kotlin

exoPlayer = SimpleExoPlayer.Builder(baseContext)
    .build().apply {
        repeatMode	= Player.REPEAT_MODE_ONE
    }

...

return MergingMediaSource(
    true,
    // http://hogwarts.pub/S01E07.srt
    getSampleSource(srtUri)	.createMediaSource(subtitle, C.TIME_UNSET),
    // http://hogwarts.pub/file_example_MP3_1MG.mp3
    // is a copy from https://file-examples-com.github.io/uploads/2017/11/file_example_MP3_1MG.mp3
    getMediaSource(audioUri).createMediaSource(MediaItem.fromUri(Uri.parse(audioUri))),
    // https://v-cdn.zjol.com.cn/289991.mp4
    getMediaSource(videoUri).createMediaSource(MediaItem.fromUri(Uri.parse(videoUri))),
)
```

SRT time ~ 39 sec
MP3 time ~ 27 sec
MP4 time ~ 42 sec

when there is only a `videoUri` item, exoplayer repeat func works well, but when I add subtitle item or audio item and played after 1 time:

- with audio and subtitle: will got black screen, no sound, subtitle, video
- with audio: will got black screen, only sound
- both siutation: `onIsPlayingChanged` and `onPlaybackStateChanged` can't listen its change

**Comment by marcbaechinger** [comment]
This works for me with the code below. Please make sure that you pass the video source is passed as the first source argument of the `MergingMediaSource`. Internally the `MerginMediaSource` uses the timeline of the first source passed to the constructor as the main timeline that is used. I recommend to use the video source as the main source (first source argument) to avoin unintended behaviour.

I'm not sure what your methods are doing like the following:

```
getMediaSource(audioUri).createMediaSource(MediaItem.fromUri(Uri.parse(audioUri)))
```

I suggest to review your code and make it similar to what I pasted below. Currently I don't think this is a library issue I'm afraid. If you think it is an ExoPlayer problem please report the actual version you are using and basically provide the information requested by the [issue template](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md).

```
DefaultHttpDataSourceFactory defaultHttpDataSourceFactory = new DefaultHttpDataSourceFactory();
    ProgressiveMediaSource.Factory progressiveFactory =
        new ProgressiveMediaSource.Factory(defaultHttpDataSourceFactory);
    ProgressiveMediaSource videoSource = progressiveFactory.createMediaSource(
        MediaItem.fromUri("https://v-cdn.zjol.com.cn/289991.mp4"));
    ProgressiveMediaSource audioSource = progressiveFactory.createMediaSource(
        MediaItem.fromUri(
            "https://file-examples-com.github.io/uploads/2017/11/file_example_MP3_1MG.mp3"));

    MediaItem.Subtitle subtitle = new MediaItem.Subtitle(
        Uri.parse("http://hogwarts.pub/S01E07.srt"),
        MimeTypes.APPLICATION_SUBRIP,
        /* language= */ null);
    SingleSampleMediaSource subtitleSource =
        new SingleSampleMediaSource.Factory(defaultHttpDataSourceFactory)
        .createMediaSource(subtitle, C.TIME_UNSET);

    MergingMediaSource mergingMediaSource = new MergingMediaSource(
        /* adjustPeriodTimeOffsets= */ true, videoSource, audioSource, subtitleSource);

    player.setMediaSource(mergingMediaSource);
    player.setRepeatMode(Player.REPEAT_MODE_ONE);
```

**Comment by simline** [comment]
thanks, it is timeline problem...
