### ISSUE TITLE
Load different video while playing

### ISSUE THREAD

**Issue by samek** [google/ExoPlayer#85]
My question is how would I approach this. 
I would need to load different video while current video is playing. 

Since player is created from renderer and url is added to that renderer how would I do something like: 

In PlayerControl method seekTo() I would need to call 
player.stop();
player.loadUrl(); //new url depending on seek time//
player.play();

**Comment by hansvdg** [comment]
Since the previous comment a lot has changed in the library, on the current master branch I do not experience the issue mentioned above.
In the dev branch of December I was not able to create a reproducable scenario.

**Comment by PrasadShirsath** [comment]
Anybody able to play different video while one is playing?

**Comment by NoGirlFriendException** [comment]
why have no answer? ???

**Comment by chile-zhong** [comment]
same question too, but dont know how to do ,any progress?

**Comment by cmdkhh** [comment]
We have been able to play multiple videos at a time as well as play a video while we buffer another one to create a playlist. 
Your questions were a bit broad but if you have something specific I would be happy to help.

**Comment by andrewlewis** [comment]
We are working on built-in support for playlists, tracked by #1270. The first comment in this issue will probably be addressed by that enhancement.
