### ISSUE TITLE
Fatal signal 6 (SIGABRT)

### ISSUE THREAD

**Issue by MurtadhaS** [google/ExoPlayer#850]
Hello every one .
I got this error when using the library.
I read about it and it says that it is a Native level error .
But really didn't get any way to fix it, so any info would be helpful.

*****Note:*****
(this is my Mobile Chip:Qualcomm Snapdragon 400 MSM8230)

<CODE>
10-08 09:03:37.596 9586-10028/com.example.marti.tv E/ACodec: [OMX.qcom.video.decoder.avc] storeMetaDataInBuffers failed w/ err -2147483648
10-08 09:03:37.599 9586-10028/com.example.marti.tv I/ACodec: [OMX.qcom.video.decoder.avc] prepareForAdaptivePlayback(1280x720)
10-08 09:03:37.600 9586-10028/com.example.marti.tv I/ACodec: [OMX.qcom.video.decoder.avc] DRC Mode: Adaptive Mode
10-08 09:03:37.600 9586-10028/com.example.marti.tv A/: frameworks/av/media/libstagefright/foundation/ABitReader.cpp:50 CHECK_LE( n,32u) failed: 40 vs. 32
10-08 09:03:37.601 9586-10028/com.example.marti.tv A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 10028 (CodecLooper)
</CODE>

**Comment by ojw28** [comment]
Please provide additional information as described [here](https://google.github.io/ExoPlayer/2015/10/01/reporting-issues.html). Thanks.

**Comment by MurtadhaS** [comment]
The issue happens when watching multiple HLS videos consecutively , where the player activity in this case crashes showing the given log above.
at first I thought it can be fixed by changing some parameters of the library, but then I am convinced it is a CyanogenMod problem (The OS I use, 12.1 version specifically).
I think there is a huge problem with the garbage collection in the kernel level of CM 12.1 or simply the default heap size for CM is smaller than the one of vendor based androids.

**Comment by ojw28** [comment]
It probably is a CyanogenMod issue. It's not hugely helpful that the first post in this issue didn't mention that you were using a custom ROM. Closing for now, since this issue still doesn't contain all of the information requested [here](https://google.github.io/ExoPlayer/2015/10/01/reporting-issues.html). Note specifically the 4th, 5th and 6th bullet points in that post, none of which seem to be provided here.

**Comment by MurtadhaS** [comment]
ok , not a problem , but really I can't get a bug report as you know .
since I am back to the stock system now .

**Comment by MurtadhaS** [comment]
about the version of exo player I used 1.4.1 and 1.5.
and was able to produce the error in both of them.
