### ISSUE TITLE
Notification not visible after notify on Notification Tray (Android 11)

### ISSUE THREAD

**Issue by deepanshu-hh** [google/ExoPlayer#8500]
I am using ExoPlayer in My application and using PlayerNotificationManager for notification building

Notification Player is not Showing on Notification Tray (Android 11):
-------------------------

When I am playing a media resource, the notification builder creates a Notification using notify() internally using a specific Notification Id and Notification Channel.

- But after notify the Notification is Not visible on Notification Tray. Why(??)

- ExoPlayer version number : 2.9.6
- Android version : 11
- Android device : Samsung

**Comment by marcbaechinger** [comment]
Seems like that Samsung has implemented a mini player for Android 11 similar to what Pixel phones do. 

We tested with a Samsung phone with Android 11 with the `PlayerNotificationManager` and a media session attached to the notification by calling `playerNotificationManager.setMediaSessionToken(mediaSession.getSessionToken())`. With that a mini player is added at the very top of the notification tray (see [this screenshot](https://www.log.com.tr/wp-content/uploads/2020/12/samsung-android-11-one-ui-3-guncellemesi-icin-bilinmesi-gereken-her-sey-5.jpg) I found on the net). In case that there is another audio app running on the device, there may be more than one mini player. In this case you may have to swipe to the left to make the mini player of your app visible. You would see two or more little dots below the mini player indicating the existence of multiple players.

One important detail to mention is that there is no mini icon of your app in the status bar of the phone. So when the notification tray is not expanded, there is no way to see that there is a mini player of your app.

May I ask you to do the following, so we can further investigate what the problem with the notification in your app on Samsung is about:

1) Please send me a short code sample of how you set up the `PlayerNotificationManager`. I'm specifically interested in whether you are using a media session with the player.

2) If you are not using a media session with the 'PlayerNotificationManager', please add a media session to see whether the Samsung device changes it's behaviour?

3) Please do a screenshot of the phone with the notification tray open a) for a phone on which the notification shows (non-Samsung) and b) with the Samsung phone on which you don't see the notification according to your report.

**Comment by deepanshu-hh** [comment]
Here is the Extended class for PlayerNotificationManger:

```
 private class CustomPlayerNotificationManager extends PlayerNotificationManager {



        @SuppressLint("WrongConstant")
        CustomPlayerNotificationManager(Context context, MediaDescriptionAdapter mediaDescriptionAdapter, @Nullable CustomActionReceiver customActionReceiver) {

            super(context, CHANNEL_ID, NOTIFICATION_ID, mediaDescriptionAdapter, customActionReceiver);
            MediaSessionCompat mediaSession = new MediaSessionCompat(context, context.getString(R.string.app_name));
            mediaSession.setActive(true);
            setMediaSessionToken(mediaSession.getSessionToken());

            setSmallIcon(R.drawable.ic_hh_notification);
            setVisibility(NotificationCompat.VISIBILITY_PUBLIC);
            setUseNavigationActions(false);
            setRewindIncrementMs(0);
            setFastForwardIncrementMs(0);
            setUsePlayPauseActions(false);
            setBadgeIconType(NotificationCompat.BADGE_ICON_SMALL);

            setUseChronometer(false);
            setStopAction(null);
            setNotificationListener(new CustomNotificationListener());

        }
```
Here where we are calling and notifying the Notification: 

 ```
private void createNotification() {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            NotificationChannel notificationChannel = new NotificationChannel(CHANNEL_ID, CHANNEL_NAME, NotificationManager.IMPORTANCE_LOW);
//            notificationChannel.setShowBadge(true);
            notificationChannel.setLockscreenVisibility(Notification.VISIBILITY_PUBLIC);
            notificationManager = (NotificationManager) AppController.getInstance().getSystemService(NOTIFICATION_SERVICE);
            Objects.requireNonNull(notificationManager).createNotificationChannel(notificationChannel);
        }
        customPlayerNotificationManager = new CustomPlayerNotificationManager(
                AppController.getInstance(),
                new CustomMediaDescriptionAdapter(), new actionReceiver()) {
            @Override
            protected Notification createNotification(Player player, @Nullable Bitmap largeIcon) {
                notification = super.createNotification(player, largeIcon);
                startForeground(NOTIFICATION_ID, notification);
                return notification;
            }
        };
    }
```

The given screenshot is working below Android 11 but Not in Android 11 as per issued mentioned:

![Screenshot_20210129-114217_Hubhopper~2](https://user-images.githubusercontent.com/76508575/106238944-cac3ac80-6227-11eb-8a1b-2eaf3492f70f.jpg)

And the given below Screenshot is of Samsung Android 11 device G973F

![WhatsApp Image 2021-01-29 at 5 07 32 PM](https://user-images.githubusercontent.com/76508575/106270959-c497f500-6254-11eb-828c-36a967a5c3ef.jpeg)

**Comment by deepanshu-hh** [comment]
Is this issue track-able?? Can it can be solved in any other way?? 

Here I debugged on Google Pixel Now:

Working on Google Pixel android 11 but Not on Samsung G973F. Why this is not working on Samsung??

**Comment by geeta4** [comment]
Exoplayer '2.11.3' also not showing Notification player on same device

**Comment by geeta4** [comment]
google podcasts app also not showing its player notification

**Comment by marcbaechinger** [comment]
@deepanshu-hh We have this issue that is tracking that for some apps `PlayerNotificationManager` does not display the notification on Samsung devices with Android 11. If you can achieve a tracking bug with Samsung that would be great, I can't help with that. 

To investigate your problem I would start with **providing all information to your media session**. This is probably mostly about `sessionCompat.setMetadata(metatdata)`. It is likely that Samsung does only show media style notification that provide a media session that is fully populated. One way to do this is that you use the `MediaSessionConnector` of the [media session extension](https://github.com/google/ExoPlayer/tree/release-v2/extensions/mediasession) of this library.

I'm currently trying to get my hands on a Samsung device with Android 11 but due to WFH this is not that easy as usual in the office. 

We have tested on one Samsung device with Android 11 as I reported in the comment above. It is working there with the code below.

We tested with a service that has this code in the `onCreate` method that sets up the `PlayerNotifcationManager` and the `MediaSessionConnector`.


```
playerNotificationManager =
        PlayerNotificationManager.createWithNotificationChannel(
            context,
            PLAYBACK_CHANNEL_ID,
            R.string.playback_channel_name,
            R.string.playback_channel_name,
            PLAYBACK_NOTIFICATION_ID,
            new MediaDescriptionAdapter() {
              @Override
              public String getCurrentContentTitle(Player player) {
                return SAMPLES[player.getCurrentWindowIndex()].title;
              }

              @Nullable
              @Override
              public PendingIntent createCurrentContentIntent(Player player) {
                return null;
              }

              @Nullable
              @Override
              public String getCurrentContentText(Player player) {
                return SAMPLES[player.getCurrentWindowIndex()].description;
              }

              @Nullable
              @Override
              public Bitmap getCurrentLargeIcon(Player player, BitmapCallback callback) {
                return Samples.getBitmap(
                    context, SAMPLES[player.getCurrentWindowIndex()].bitmapResource);
              }
            },
            new PlayerNotificationManager.NotificationListener() {
              @Override
              public void onNotificationPosted(
                  int notificationId, Notification notification, boolean ongoing) {
                if (ongoing) {
                  startForeground(notificationId, notification);
                } else {
                  stopForeground(/* removeNotification= */ false);
                }
              }

              @Override
              public void onNotificationCancelled(int notificationId, boolean dismissedByUser) {
                stopSelf();
              }
            });

    mediaSession = new MediaSessionCompat(context, MEDIA_SESSION_TAG);
    mediaSession.setActive(true);

    mediaSessionConnector = new MediaSessionConnector(mediaSession);
    mediaSessionConnector.setQueueNavigator(
        new TimelineQueueNavigator(mediaSession, 10) {
          @Override
          public MediaDescriptionCompat getMediaDescription(Player player, int windowIndex) {
            return Samples.getMediaDescription(context, SAMPLES[windowIndex]);
          }
        });
    mediaSessionConnector.setPlayer(player);

    playerNotificationManager.setMediaSessionToken(mediaSession.getSessionToken());
    playerNotificationManager.setPlayer(player);
```

This is the Samples class that creates the media session metadata:

```
public final class Samples {

  public static final class Sample {
    public final Uri uri;
    public final String mediaId;
    public final String title;
    public final String description;
    public final int bitmapResource;

    public Sample(
        String uri, String mediaId, String title, String description, int bitmapResource) {
      this.uri = Uri.parse(uri);
      this.mediaId = mediaId;
      this.title = title;
      this.description = description;
      this.bitmapResource = bitmapResource;
    }

    @Override
    public String toString() {
      return title;
    }
  }

  public static final Sample[] SAMPLES =
      new Sample[] {
        new Sample(
            "https://storage.googleapis.com/automotive-media/Jazz_In_Paris.mp3",
            "audio_1",
            "Jazz in Paris",
            "Jazz for the masses",
            R.drawable.album_art_1),
        new Sample(
            "https://storage.googleapis.com/automotive-media/The_Messenger.mp3",
            "audio_2",
            "The messenger",
            "Hipster guide to London",
            R.drawable.album_art_2),
        new Sample(
            "https://storage.googleapis.com/automotive-media/Talkies.mp3",
            "audio_3",
            "Talkies",
            "If it talks like a duck and walks like a duck.",
            R.drawable.album_art_3),
      };

  public static MediaDescriptionCompat getMediaDescription(Context context, Sample sample) {
    Bundle extras = new Bundle();
    Bitmap bitmap = getBitmap(context, sample.bitmapResource);
    extras.putParcelable(MediaMetadataCompat.METADATA_KEY_ALBUM_ART, bitmap);
    extras.putParcelable(MediaMetadataCompat.METADATA_KEY_DISPLAY_ICON, bitmap);
    return new MediaDescriptionCompat.Builder()
        .setMediaId(sample.mediaId)
        .setIconBitmap(bitmap)
        .setTitle(sample.title)
        .setDescription(sample.description)
        .setExtras(extras)
        .build();
  }

  public static Bitmap getBitmap(Context context, @DrawableRes int bitmapResource) {
    return ((BitmapDrawable) context.getResources().getDrawable(bitmapResource)).getBitmap();
  }
}
```

**Comment by marcbaechinger** [comment]
@geeta4 Thanks for reporting. The problem is not related to a given version, so this should not make a difference.

**Comment by deepanshu-hh** [comment]
Thanks @marcbaechinger for the fix, Now the Notification player is showing on Notification Tray, but there is an issue, Next button is disabled on Locked screen when I am using the given below Code: 

```
mediaSessionConnector.setQueueNavigator(
        new TimelineQueueNavigator(mediaSession, 1) {
          @Override
          public MediaDescriptionCompat getMediaDescription(Player player, int windowIndex) {
            return Samples.getMediaDescription(context, SAMPLES[windowIndex]);
          }
        });
```
But Previous button and Play/Pause button is Enabled.

**Comment by geeta4** [comment]
@marcbaechinger  thanks for solution.

**Comment by marcbaechinger** [comment]
@deepanshu-hh Hard to say with the information you are giving me.

What is in the queue and on what position are you in the timeline when this is the case? 

What is the output of 

adb shell dumpsys media_session

at the moment when this happens?

**Comment by marcbaechinger** [comment]
@deepanshu-hh Please change the value to something higher to 1. I checked the java doc for you:

```
/**
   * Creates an instance for a given {@link MediaSessionCompat} and maximum queue size.
   * <p>
   * If the number of windows in the {@link Player}'s {@link Timeline} exceeds {@code maxQueueSize},
   * the media session queue will correspond to {@code maxQueueSize} windows centered on the one
   * currently being played.
   *
   * @param mediaSession The {@link MediaSessionCompat}.
   * @param maxQueueSize The maximum queue size.
   */
public TimelineQueueNavigator(MediaSessionCompat mediaSession, int maxQueueSize) {
```

The second argument is the queue size that you want to have larger than one. That was a typo but proved that the code is working quite well. :) Sorry for that.

**Comment by deepanshu-hh** [comment]
We are not using queue with ExoPlayer, we have the queue session separately only single episode is playing in the exoplayer at a time, is there is any way to use next or previous button, to change my queue item.

**Comment by marcbaechinger** [comment]
Seem like Samsung is using the information of the media session for this.

**Comment by deepanshu-hh** [comment]
So, How to use PlaybackStateCompat and CustomActions for MediaSessionConnector

**Comment by marcbaechinger** [comment]
When testing we found that either of these approaches work:

1) Not using a media session at all result in a media style notification in the 'Alerting notification' part of the notification drawer.

2) Using it with a properly populated media session. This includes the populating playback state, metadata and the queue of the media session. This is what the MediaSessionConnector does if you provide a TimelineQueueNavigator as in the code snippet I posted above.

The approach of your code snippet that is using a media session that is not populated apparently result in not displaying a notification at all. So you could just remove these lines from you initial code above to have 1):

```
MediaSessionCompat mediaSession = new MediaSessionCompat(context, context.getString(R.string.app_name));
mediaSession.setActive(true);
setMediaSessionToken(mediaSession.getSessionToken());
```

**Comment by deepanshu-hh** [comment]
If I remove both Media Session and Media Session Connector, is it work on my Samsung device on Android 11???
And how to populate media session??

**Comment by deepanshu-hh** [comment]
@marcbaechinger Thanks For helping.
Any ways we are using custom implementation of `TimelineQueueNavigator` overriden methods to enable/disable next/previous events and it helps for now. 

````
mediaSessionConnector.setQueueNavigator(
                    new TimelineQueueNavigator(mediaSession) {
                        @Override
                        public MediaDescriptionCompat getMediaDescription(Player player, int windowIndex) {
                           
                            return new MediaDescriptionCompat.Builder()
                                    .....
                                    .build();
                        }

                        @Override
                        public long getSupportedQueueNavigatorActions(Player player) {
                            long actions =  super.getSupportedQueueNavigatorActions(player);
                            ....
                            return actions;
                        }

                        @Override
                        public void onSkipToNext(Player player) {
                            Log.d(TAG, "skiptoNext->mediaConnector");
                        }

                        @Override
                        public void onSkipToPrevious(Player player) {
                            Log.d(TAG, "skiptoPrevious->mediaConnector");
                        }
                    });
````
