### ISSUE TITLE
how to add multi language audios in latest version of exoplayer

### ISSUE THREAD

**Issue by SepidehAkbarinezhad** [google/ExoPlayer#8501]
hi 
as I found in previous versions , to add language audio , we must create a format by calling "createAudioSampleFormat" and then making a mediasource by passing the foramt to createMediaSource() . finally call MergingMediaSource() to merge the mediasources . now ,I would like to know how to do this as I am using the last version of exoplayer , the createMediaSource() and createAudioSampleFormat() are deprecated and by calling setMediaItems() the  MergingMediaSource()  is called internally

**Comment by marcbaechinger** [comment]
You can not sideload an audio track to a video media source with a media item. But the old way of creating a `MergingMediaSource` programmatically is still possible and not deprecated. Something like the following snippet should do the trick:

```
    ProgressiveMediaSource.Factory mediaSourceFactory = new ProgressiveMediaSource.Factory(
        new DefaultHttpDataSource.Factory());
    ProgressiveMediaSource videoSource = 
        mediaSourceFactory.createMediaSource(MediaItem.fromUri("http://example.com/video"));
    ProgressiveMediaSource audioSource = 
        mediaSourceFactory.createMediaSource(MediaItem.fromUri("http://example.com/audio"));
    player.setMediaSource(new MergingMediaSource(videoSource, audioSource));
```

**Comment by niiitish** [comment]
> You can not sideload an audio track to a video media source with a media item. But the old way of creating a `MergingMediaSource` programmatically is still possible and not deprecated. Something like the following snippet should do the trick:
> 
> ```
>     ProgressiveMediaSource.Factory mediaSourceFactory = new ProgressiveMediaSource.Factory(
>         new DefaultHttpDataSource.Factory());
>     ProgressiveMediaSource videoSource = 
>         mediaSourceFactory.createMediaSource(MediaItem.fromUri("http://example.com/video"));
>     ProgressiveMediaSource audioSource = 
>         mediaSourceFactory.createMediaSource(MediaItem.fromUri("http://example.com/audio"));
>     player.setMediaSource(new MergingMediaSource(videoSource, audioSource));
> ```

hello sir i m  new in programming can you please tell me how to change audio track in my video player app i m playing video from internal or external storage i want change audio track just like vlc App i searched everywhere but i didn't get any solution please help me sir
