### ISSUE TITLE
Exoplayer 2.12, does not load local subtitle file.

### ISSUE THREAD

**Issue by devnullpointer** [google/ExoPlayer#8503]
Similar to issue #8057 When using a local file, it appears that the SRT or WebVTT is loaded because I get the options as indicated in this [screenshot](https://ibb.co/0q97RD9), unfortunately there are no subtitles displayed. If I provide a http:// protocol for a provided SRT or WebVTT file instead of a file:// protocol the subtitles options only display the language I've set, the "Unknown" is not visible, and the subtitles then proceed to work. 

For the local files they are being saved to the Environment.getExternalStorageDirectory() and all the required READ/WRITE permissions have been set as I am able to retrieve other files from the same location.

- ExoPlayer 2.12.3
- Android 7.1.1

**Comment by icbaker** [comment]
Are you able to reproduce the problem in the demo app? You can add subtitle URIs to the JSON sample format:
https://exoplayer.dev/demo-application.html#1-editing-assetsmediaexolistjson

I've often used sideloaded subtitle files stored in `/sdcard/` for testing and haven't seen any problems with accessing it from the demo app.

How is the video you're playing hosted (simple progressive container, DASH, HLS, something else)?

Is there anything logged when the subtitles fail to display?

**Comment by devnullpointer** [comment]
The video is loaded using a progressive container `mediaSource = new ProgressiveMediaSource.Factory(mediaDataSourceFactory).createMediaSource(MediaItem.fromUri(streamUri));`

Subs are loaded as 
```
final MediaItem.Subtitle srt = new MediaItem.Subtitle(loadedSubtitleUri, loadedSubtitleUri.toString().contains("vtt") ? MimeTypes.TEXT_VTT : MimeTypes.APPLICATION_SUBRIP, "en-US", C.SELECTION_FLAG_AUTOSELECT, C.ROLE_FLAG_CAPTION, "English");
            final SingleSampleMediaSource subtitleSource = new SingleSampleMediaSource.Factory(mediaDataSourceFactory).createMediaSource(srt, C.TIME_UNSET);

            final MediaSource mediaSourceWithText = new MergingMediaSource(mediaSource, subtitleSource);
            player.setMediaSource(mediaSourceWithText);
```

In the logs I don't see any mention about subs as I would if i was using a http one.

When I'm downloading the subs from OpenSubtitle I'm saving them as such:
```
final InputStream stream = new GZIPInputStream(connection.getInputStream());
                final InputStream input = new BufferedInputStream(new InputSource(stream).getByteStream());

                final String PATH = Environment.getExternalStorageDirectory() + "/subtitles/";
                final File subtitlePath = new File(PATH);
                subtitlePath.mkdirs();

                FileUtils.cleanDirectory(subtitlePath);

                final File subtitleFile = new File(subtitlePath, subtitle.getFileName());
                final OutputStream output = new FileOutputStream(subtitleFile);
                byte[] buffer = new byte[1024];
                int length;
                while ((length = input.read(buffer)) != -1)
                {
                    output.write(buffer, 0, length);
                }
                output.flush();
                output.close();
                stream.close();
```

and then passing `subtitleFile.toURI().toString()` to my exoplayer activity. 

I can try the demo app as you suggested and get back to you.

**Comment by icbaker** [comment]
> and then passing `subtitleFile.toURI().toString()` to my exoplayer activity.

What happens if before you pass it to ExoPlayer you just log the entire contents (or the first few lines) of the file to logcat? Just to check the file really is present and contains the textual content you expect.

> I can try the demo app as you suggested and get back to you.

Thanks! If you're able to reproduce and can share a plaintext subtitle file that I can put on my device to try and repro that would be helpful. It would probably also be helpful to grab a bug report (`adb bugreport`) after reproducing with the demo app.

**Comment by devnullpointer** [comment]
I can dump the contents of the srt file into logcat and send you the output. Unfortunately I wont be able to get to it until later this evening.

**Comment by devnullpointer** [comment]
@icbaker  I put a breakpoint in my code to show you the location of the srt file after it was decompressed. [Here it is](https://ibb.co/hKmmPzg), and below is the logcat showing the first 10 lines of the srt file from the exoplayer activity. You can also see in the logcat that the subrip track was also loaded.

uri sent to the media source is "file:/storage/emulated/0/subtitles/\<filename\>.srt

added this to my activity onCreate method:
```
 try {
            final InputStream in = getContentResolver().openInputStream(loadedSubtitleUri);
            final BufferedReader r = new BufferedReader(new InputStreamReader(in));
            final StringBuilder total = new StringBuilder();
            int num = 0;
            for (String line; (line = r.readLine()) != null; ) {
                total.append(line).append('\n');
                num++;

                if (num > 10) break;
            }
            Log.d(TAG, total.toString());
        }
        catch (final Exception e)
        {
        }
```

```
D/com.myproject.activities.ExoPlayerActivity: ﻿1
    00:00:06,000 --> 00:00:12,074
    Advertise your product or brand here
    contact www.OpenSubtitles.org today
    
    2
    00:00:42,835 --> 00:00:49,420
    Oh. A newlywed couple
    just moved to town.
    
    3
I/ExoPlayerImpl: Init 143a71f [ExoPlayerLib/2.12.3] [generic_x86, Android SDK built for x86, Google, 25]
D/EventLogger: sourceInfo [periodCount=1, windowCount=1
      period [2021.21]
      window [2021.21, true, false]
    ]
D/EventLogger: Tracks [
      Renderer:0 [
        Group:0, adaptive_supported=N/A [
          [X] Track:0, id=0, mimeType=video/avc, bitrate=1031829, res=640x360, supported=YES
        ]
        Metadata [
        ]
      ]
      Renderer:1 [
        Group:0, adaptive_supported=N/A [
          [X] Track:0, id=audio:English stereo, mimeType=audio/mp4a-latm, codecs=mp4a.40.2, channels=2, sample_rate=48000, language=und, label=English stereo, supported=YES
        ]
        Metadata [
        ]
      ]
D/EventLogger:   Renderer:2 [
        Group:0, adaptive_supported=N/A [
          [ ] Track:0, id=null, mimeType=application/x-subrip, language=en-us, label=English, supported=YES
        ]
      ]
      Renderer:3 [
        Group:0, adaptive_supported=N/A [
          [X] Track:0, id=null, mimeType=application/id3, supported=YES
        ]
      ]
    ]
```

**Comment by devnullpointer** [comment]
@icbaker I've also noticed a few times that I get an additional subtitle entry marked "Unknown" even though I only load 1 subrip track with one video stream. In Renderer 2 theres an cea-608 entry that shows up mysteriously, i presume its the progressive stream adding it?

example logcat:
```
D/EventLogger: Tracks [
      Renderer:0 [
        Group:0, adaptive_supported=YES [
          [X] Track:0, id=0, mimeType=video/avc, bitrate=955494, codecs=avc1.64001e, res=854x480, supported=NO_EXCEEDS_CAPABILITIES
          [ ] Track:1, id=1, mimeType=video/avc, bitrate=83386, codecs=avc1.64001e, res=854x480, supported=NO_EXCEEDS_CAPABILITIES
        ]
        Metadata [
        ]
      ]
      Renderer:1 [
        Group:0, adaptive_supported=N/A [
          [X] Track:0, id=1/15, mimeType=audio/mp4a-latm, codecs=mp4a.40.2, channels=2, sample_rate=44100, supported=YES
        ]
      ]
      Renderer:2 [
        Group:0, adaptive_supported=N/A [
          [ ] Track:0, id=1/8219, mimeType=application/cea-608, supported=YES
        ]
        Group:1, adaptive_supported=N/A [
          [ ] Track:0, id=null, mimeType=application/x-subrip, language=en-us, label=English, supported=YES
D/EventLogger:     ]
      ]
      Renderer:3 [
        Group:0, adaptive_supported=N/A [
          [X] Track:0, id=null, mimeType=application/id3, supported=YES
        ]
      ]
    ]
```

**Comment by devnullpointer** [comment]
@icbaker Also please not that when I select the language form the CC selector in the logs the Renderer:2 group shows an X on the subrip, but no subs are shown. Also as mentioned in #8504 the same subtitle shows fine when its provided via http.

**Comment by icbaker** [comment]
I don't know what could be causing the problem - but it seems likely to me that it's related either to the way you're writing the file out or to storage permissions.

If you're able to reproduce the problem by hard-coding a local file URI in the demo app JSON (i.e. generate the output once and leave it, rather than generating it just-in-time), then please provide the **exact** file you used (fetch it with `adb pull`) and a bug report (taken with `adb bugreport`).

I tried just now and successfully played a sideloaded subtitle file from local disk in the demo app and it worked fine.

NOTE: I tried at both dev-v2 and r2.12.3 (which you said you're using). When I tried at dev-v2 I accidentally messed up my file URI (so it pointed at nothing), and I saw the symptoms you describe (video played, no subtitles, no errors in logcat). At 2.12.3 this same setup causes a playback failure with a clear FileNotFoundException in logcat. The change in behaviour is due to https://github.com/google/ExoPlayer/commit/f076080434c24a00309098ef3afc350d175ec4bb - I'm going to revisit that and see if we can also log some sort of error even if we allow playback to continue in this case. This is only relevant if you're actually using dev-v2 and not 2.12.3 :)

---

> uri sent to the media source is "file:/storage/emulated/0/subtitles/<filename>.srt

Is there a typo here? It needs 3 slashes after `file:`: `file:///storage/emulated/0/subtitles/...`

---

> I've also noticed a few times that I get an additional subtitle entry marked "Unknown" even though I only load 1 subrip track with one video stream. In Renderer 2 theres an cea-608 entry that shows up mysteriously, i presume its the progressive stream adding it?

Yes it's probably a subtitle track included in the main media container you're playing. You should be able to see the same track when playing the same file in e.g. VLC, or running it through mediainfo.

**Comment by devnullpointer** [comment]
> Is there a typo here? It needs 3 slashes after file:: file:///storage/emulated/0/subtitles/...

That is what is being returned when I do a .toURI().toString() from a File object. That actually might be the cause as the protocol is incorrect as you stated. I'll attempt run 2 tests on the app with the same srt file, one using the uri mentioned in the ticket (file:/) and the same file with a corrected uri protocol (file:///)

**Comment by icbaker** [comment]
> NOTE: I tried at both dev-v2 and r2.12.3 (which you said you're using). When I tried at dev-v2 I accidentally messed up my file URI (so it pointed at nothing), and I saw the symptoms you describe (video played, no subtitles, no errors in logcat). At 2.12.3 this same setup causes a playback failure with a clear FileNotFoundException in logcat. The change in behaviour is due to [f076080](https://github.com/google/ExoPlayer/commit/f076080434c24a00309098ef3afc350d175ec4bb) - I'm going to revisit that and see if we can also log some sort of error even if we allow playback to continue in this case. This is only relevant if you're actually using dev-v2 and not 2.12.3 :)

We now log the error even when transforming it to end-of-stream: https://github.com/google/ExoPlayer/commit/ffc1b5bbef61494086bd95b14b58a3986a28e5d8
