### ISSUE TITLE
Does anyone have an IPTV project focused on multicast udp?

### ISSUE THREAD

**Issue by matheusccarvalho** [google/ExoPlayer#8505]
I am developing an IPTV application for android TV for my college project, in which the channels are reproduced by udp links, example: "udp: //224.2.2.2: 1234". Live channels must be .ts. I'm using android studio.

**Comment by marcbaechinger** [comment]
There is a `UdpDataSource` available that is created by the `DefaultDataSource` automatically if you use a url with the `udp://` scheme like your example.

 > Live channels must be .ts.
 
If you are asking for multicast udp streams in the ts format for testing, we can not provide these I'm afraid, but I leave the issue open in case someone else can help you some further.

Please let me know and add some details if I didn't understand your question correctly.
