### ISSUE TITLE
A NullPointerException occurred in com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.timelineOrManifestChanged.

### ISSUE THREAD

**Issue by xifengyekai** [google/ExoPlayer#8508]
A NullPointerException occurred in com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.timelineOrManifestChanged.

logcat:
```
01-22 20:48:51.824889  3727  3727 E AndroidRuntime: FATAL EXCEPTION: main
01-22 20:48:51.824889  3727  3727 E AndroidRuntime: Process: com.baidu.car.radio, PID: 3727
01-22 20:48:51.824889  3727  3727 E AndroidRuntime: java.lang.NullPointerException: Attempt to read from field 'boolean b.f.a.a.h$a.j' on a null object reference
01-22 20:48:51.824889  3727  3727 E AndroidRuntime: 	at b.f.a.a.h.a(:16)
01-22 20:48:51.824889  3727  3727 E AndroidRuntime: 	at b.f.a.a.g.handleMessage(:2)
01-22 20:48:51.824889  3727  3727 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
01-22 20:48:51.824889  3727  3727 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:228)
01-22 20:48:51.824889  3727  3727 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6721)
01-22 20:48:51.824889  3727  3727 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-22 20:48:51.824889  3727  3727 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
01-22 20:48:51.824889  3727  3727 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:917)
```

Confusion part：
```
com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate -> b.f.a.a.h$a:
    boolean playbackStateOrPlayWhenReadyChanged -> i
    boolean timelineOrManifestChanged -> j
    boolean isLoadingChanged -> k
    com.google.android.exoplayer2.trackselection.TrackSelector trackSelector -> c
    boolean trackSelectorResultChanged -> l
    int timelineChangeReason -> f
    boolean seekProcessed -> g
    java.util.Set listeners -> b
    int positionDiscontinuityReason -> e
    boolean playWhenReady -> h
    com.google.android.exoplayer2.PlaybackInfo playbackInfo -> a
    boolean positionDiscontinuity -> d

com.google.android.exoplayer2.ExoPlayerImpl$1 -> b.f.a.a.g:
    com.google.android.exoplayer2.ExoPlayerImpl this$0 -> a
    1:1:void com.google.android.exoplayer2.ExoPlayerImpl.handleEvent(android.os.Message):0:0 -> handleMessage
    1:1:void handleMessage(android.os.Message):0 -> handleMessage
    2:2:void com.google.android.exoplayer2.ExoPlayerImpl.handlePlaybackInfo(com.google.android.exoplayer2.PlaybackInfo,int,boolean,int):0:0 -> handleMessage
    2:2:void com.google.android.exoplayer2.ExoPlayerImpl.handleEvent(android.os.Message):0 -> handleMessage
    2:2:void handleMessage(android.os.Message):0 -> handleMessage
    3:3:void com.google.android.exoplayer2.ExoPlayerImpl.handleEvent(android.os.Message):0:0 -> handleMessage
    3:3:void handleMessage(android.os.Message):0 -> handleMessage
```

**Comment by marcbaechinger** [comment]
Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md). If you're unable to share bug reports or test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Please also update this issue to indicate you’ve done this.

In addition I would like to ask you to check whether you are accessing methods of the players from different threads. It's a long shot from my side, but a `NullPointerException` in `PlaybackInfoUpdate` makes me think of a threading issue. Can you, in addition to provide the information of the issue template, check whether you are seeing log statement that are mentioned in https://exoplayer.dev/troubleshooting.html#what-do-player-is-accessed-on-the-wrong-thread-warnings-mean ?

**Comment by xifengyekai** [comment]
This exception was caused by monkey test. Logically, it was caused by stopping and releasing the player in the thread.We expect the player to stop and release correctly.
The exception has not been reproduced at present, and'"adb bugreport" cannot be executed, but there is a log when the exception occurs.
Test content and steps：1.adb push whitelist.txt /data/local/tmp/
2.adb shell monkey -s 500 -v-v-v --pct-syskeys 0 --throttle 300 --pct-touch 30 --pct-motion 30 --pkg-whitelist-file /data/local/tmp/whitelist.txt --ignore-crashes --ignore-timeouts --ignore-security-exceptions --ignore-native-crashes 500000
The content of whitelist.txt is application package name.
ExoPlayer version number:2.8.4
Android version:Android 9 API 28
Android device:Car machine


[monkey_log.zip](https://github.com/google/ExoPlayer/files/5886995/monkey_log.zip)

**Comment by marcbaechinger** [comment]
Thanks for the logs. 

I think it will be difficult to diagnose. The stack trace is obfuscated so I think both the class name and the line number is hard to interpret. 

We have a lot of changes in PlaybackInfoUpdate and how updates of the state are handled since 2.8.4. I'd actually recommend to upgrade to the most recent version. It's unlikely that we are going to do big analysis for 2.8.4.

**Comment by ojw28** [comment]
Closing as not actionable, given this is about a relatively old version and there's only an obfuscated stack trace to go on.
