### ISSUE TITLE
Get URL played by the player

### ISSUE THREAD

**Issue by cacciato** [google/ExoPlayer#851]
Hi,

I'm using ExoPlayer to read some HLS streams. I was wondering : Can we retrieve the URL read by the player ?

I'm asking this in case of a redirection : Let's assume, I tell the player to read an **URL A**. But this URL redirects the player to **URL B**. So the player is going to read **URL B**.

I read the docs but I did not find a such property / method.

Thanks.

**Comment by ojw28** [comment]
Taking the demo app as an example, in `HlsRendererBuilder.onSingleManifest`, `manifest.baseUri` is the URL after redirection (i.e. URL B).
