### ISSUE TITLE
AudioChannelConfiguration metadata is not parsed from the manifest correctly.

### ISSUE THREAD

**Issue by avhetman** [google/ExoPlayer#8510]
According to the DASH specification 4.3 the `AudioChannelConfiguration` could either be a sibling of Representation or a child of it. In the DashManifestParser.java it is properly parsed from the manifest when it is a child of Representation or when the `AudioChannelConfiguration` element appears in the adaptation set before the Representation element, otherwise, when the Representation is before the AudioChannelConfiguration, the `parseRepresentation()` function is called without this audio channel metadata. Ultimately, not having this AudioChannelConfiguration results in some audio codecs being incorrectly labeled as unsupported (as seen on my Chromecast w/ GTV for example, where ec-3 ends up as 'unsupported'). 

Looking through the DASH specification, I cannot find anything about the order of the AudioChannelConfiguration in regard to Representation inside of the AdaptationSet, hence I believe ExoPlayer should handle the AudioChannelConfiguration parsing regardless of it appearing before or after the Representation instead of just before.  

To reproduce, a manifest with the following structure can be used:
```
<AdaptationSet mimeType="audio/mp4" codecs="ec-3" lang="und" subsegmentAlignment="true" subsegmentStartsWithSAP="1">
    <Representation id="2" bandwidth="192000">
        <BaseURL>audio.mp4</BaseURL>
        <SegmentBase indexRange="652-875">
            <Initialization range="0-651"/>
        </SegmentBase>
    </Representation>
    <AudioChannelConfiguration schemeIdUri="tag:dolby.com,2014:dash:audio_channel_configuration:20
11" value="F801"/>
</AdaptationSet>
```

As can be seen, the Representation element appears before the AudioChannelConfiguration inside of the AdaptationSet.

**Comment by marcbaechinger** [comment]
Yeah, that's probably correct by spec, practically a bit cumbersome to parse. I haven't found 4.3 and the expression `sibling` but I found something like:

```
For any Representation within an Audio Adaptation Sets as defined in 3.2.13 the 
following elements and attributes shall be present:  [...] AudioChannelConfiguration, if not 
present in AdaptationSet element
```

Arguably, for an event-based parser that does not load the entire DOM into memory, the term `if not present in AdaptationSet element` could mean `present in AdaptationSet at the moment when the Representation element appears`. If that is not the case parsing gets a bit inefficient.

We probably should look into this. Assigning to @ojw28 for a second opinion.

**Comment by avhetman** [comment]
In case it helps, here is the link to the AudioChannelConfiguration guidelines/constraints: https://dashif-documents.azurewebsites.net/DASH-IF-IOP/master/DASH-IF-IOP.html#audio-constraints 

`The AudioChannelConfiguration element SHALL be present either on the adaptation set or representation level (but not both).`

Looks like they use "levels" instead of "child/sibling" as I had mentioned, however it doesn't specify the order of the adaptation set elements anywhere, just that they are to be present. I interpret that as the AudioChannelConfiguration could appear before or after the Representation element.

I understand that with the current single-pass logic in the parser this is a bit of a pain, but I am sure there is a clever way to handle this edge case :) 

One way this could probably be done is to call that ` parseRepresentation()` function *after* the do-while loop that gets all the elements from the AdaptationSet.

**Comment by ojw28** [comment]
> Looking through the DASH specification, I cannot find anything about the order of the AudioChannelConfiguration in regard to Representation inside of the AdaptationSet

The DASH specification does define this order. In general it defines quite specifically the order of elements in many places. The ordering is defined by the _XML syntax_ sections, which use `xs:sequence`, which is a way of specifying that child elements must appear in the defined order. Please refer to the DASH specification, https://www.w3schools.com/xml/el_sequence.asp and https://www.w3schools.com/xml/el_complexcontent.asp.

**Comment by avhetman** [comment]
That makes sense, I knew there had to be some semblance of order with all these elements. Appreciate your help @marcbaechinger and @ojw28
