### ISSUE TITLE
Trouble integrating exoplayer with Nibiru VR Headset

### ISSUE THREAD

**Issue by Sidharth666** [google/ExoPlayer#8512]
I'm playing a mp4 video in VR headset having Nibiru OS. The video is stored locally on the device and is able to play using exoplayer but is dropping frames big time and streaming is not smooth at all. While the default media player is able to play the video smoothly.

Here is the exoplayer implementation:
-------------------------
```
Surface surface = new Surface(m_VideoArea.getSurfaceTexture());
MediaSource mediaSource = new ExtractorMediaSource.Factory(dataSourceFactory)
                    .setExtractorsFactory(new DefaultExtractorsFactory())
                    .createMediaSource(Uri.parse(videoPath));
player = ExoPlayerFactory.newSimpleInstance(VRMediaPlayer.this, new DefaultRenderersFactory
                        (this), new DefaultTrackSelector(), loadControl);
                player.setVideoSurface(surface);
                player.setPlayWhenReady(false);
                player.prepare(mediaSource);
```
Android MediaPlayer implementation which is working well
-------------------------
```
mPlayer = new MediaPlayer();
mPlayer.setSurface(surface);
mPlayer.start();
```

-The video we're trying to play is a 360 mp4. 
-The interesting thing is exoplayer implementation is working fine in a mobile phone device.

**Comment by ojw28** [comment]
If the video plays fine on mobile phone devices, then this seems like an issue either with the device itself or with Nibiru OS. You'll need to report the issue to them.
