### ISSUE TITLE
Exo keep on playing black screen and never stops when with postRoll

### ISSUE THREAD

**Issue by cohenItay** [google/ExoPlayer#8515]
Hi there, 
I've downloaded the ExoPlayer sample project and tried to run this adTag: 
https://pubads.g.doubleclick.net/gampad/ads?iu=/6870/ynet_mobile/ynet_iphone_preroll_health&description_url=https%3A%2F%2Fwww.ynet.co.il%2Fhome%2F0%2C7340%2CL-8%2C00.html&tfcd=0&npa=0&sz=480x360%7C480x361%7C640x480&cust_params=dcStage%3D4444&gdfp_req=1&output=xml_vmap1&vpi=1&unviewed_position_start=1&env=vp&impl=s&correlator=

as you can see it includes 2 pre-rolls and one post-roll.
the two pre-roll are displayed with success, but when we reach to the end of the original video, instead of showing the post-roll, the video keep on being played without ever stopping on black screen. (the video time progress just keep on going endlessly)

this adTag has been tried on other players (such as FlowPlayer) in native app and web browsers, and it correctly showed all of the ads.

**Comment by marcbaechinger** [comment]
I can repro that the postroll ad is not shown. I also see only one preroll.

Can you give us some information about what version of ExoPlayer you are using? We are constantly improving and extending IMA support so it may be relevant to know the exact version you are using.

@andrewlewis may I ask you to take a look?

**Comment by cohenItay** [comment]
It happens in 2.12.2 

Just tried it on 2.12.3 and it suddenly works :)

**Comment by andrewlewis** [comment]
Sorry for the delay. I just tried playing this ad tag and saw two prerolls but no postroll. Based on your last message it sounds like it's working anyway so I will close this for now but please let us know if anything still needs fixing. Thanks!
