### ISSUE TITLE
How to find cache exist?

### ISSUE THREAD

**Issue by GobuTranxit** [google/ExoPlayer#8519]
I am using V2.12. **How can I find my file is cached or not?** 
Kindly give me an instructions

**Comment by marcbaechinger** [comment]
Given you know the size of the file, you can find whether a given byte range of the file is cache by using the `isCached` of the cache object you are using:

```
/**
   * Returns whether the specified range of data in a resource is fully cached.
   *
   * @param key The cache key of the resource.
   * @param position The starting position of the data in the resource.
   * @param length The length of the data.
   * @return true if the data is available in the Cache otherwise false;
   */
  boolean isCached(String key, long position, long length);
```
The cache key is the uri or the key you specified for the file.
