### ISSUE TITLE
cdn name

### ISSUE THREAD

**Issue by karamgharam** [google/ExoPlayer#8520]
i have multiple cdn 
how can i get the name of cdn that player use it

**Comment by karamgharam** [comment]
@marcbaechinger

**Comment by karamgharam** [comment]
@andrewlewis

**Comment by marcbaechinger** [comment]
@karamgharam Please stop tagging people. Your issue is not being processed quicker if you do this. Contrary, chances are nice people are being prefered. Thanks!

**Comment by marcbaechinger** [comment]
Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/question.md).

I do not understand what you mean. Can you please clarify what you do in your code and what information you are missing? I suspect you are requesting a media file with HTTP with a given uri. What do you mean when you say which cdn? Is there an http redirect involved somehow? Please clarify so we can help you. Happy to help!

**Comment by karamgharam** [comment]
i have media url that have cdn i want to know which server that use from player @marcbaechinger  
for example if i have url https://tt.cdn.com and this url mabe use frankfor server or tokyo there is way to know which one the player use

**Comment by marcbaechinger** [comment]
I'm not sure whether this is possible. Specifically because it is not clear how your CDN provider achieves this behavior. There can be several ways to do that like with over an internal DNS server or by a proxy configuration of the edge server of the CDN backend. If it's done on HTTP level then it could be a redirect that the player could be aware of. I doubt an efficient CDN implementation would do that though. 

Can you provide me with a sample uri so I can have check this? Or alternatively, can you research this and tell me how that is implemented by your CDN?

**Comment by karamgharam** [comment]
> I'm not sure whether this is possible. Specifically because it is not clear how your CDN provider achieves this behavior. There can be several ways to do that like with over an internal DNS server or by a proxy configuration of the edge server of the CDN backend. If it's done on HTTP level then it could be a redirect that the player could be aware of. I doubt an efficient CDN implementation would do that though.
> 
> Can you provide me with a sample uri so I can have check this? Or alternatively, can you research this and tell me how that is implemented by your CDN?

this is url https://geo.tent-cdn.com/out/u/Ahl_Alraya_S01_E04.mpd

**Comment by marcbaechinger** [comment]
This url does an HTTP redirect when the manifest is loaded. So if you are using `CronetDataSource.Factory` or `DefaultHttpDataSource.Factory` you could for instance set a transfer listener to the factory your app is using for loading the manifest. The DataSpec that is passed to the callbacks `onTransferStart` and `onTransferEnd` has the uri that is already resolved in case of a redirect. In `onTransferInitializing` `dataSpec.uri` points to the original uri before the redirect. I think that's the easiest way to get access to the uri the player is using for downloading the manifest after a redirect:

```
      ((CronetDataSource.Factory)httpDataSourceFactory).setTransferListener(new TransferListener() {

        @Override
        public void onTransferInitializing(DataSource source, DataSpec dataSpec,
            boolean isNetwork) { /* Do nothing. */ }

        @Override
        public void onTransferStart(DataSource source, DataSpec dataSpec, boolean isNetwork) {
          Log.d("transferStart", "dataSpec.uri: " + dataSpec.uri);
        }

        @Override
        public void onBytesTransferred(DataSource source, DataSpec dataSpec, boolean isNetwork,
            int bytesTransferred) {/* Do nothing. */ }

        @Override
        public void onTransferEnd(DataSource source, DataSpec dataSpec, boolean isNetwork) {
          Log.d("transferEnd", "dataSpec.uri: " + dataSpec.uri);
        }
      });
```

**Comment by karamgharam** [comment]
thanks for help 
this work to me 


```
public String getCDNName(String url) {
        String cdnName = "";
        try {
            DataSource dataSource = buildHttpDataSourceFactory().createDataSource();
            DashManifest dashManifest = DashUtil.loadManifest(dataSource, Uri.parse(url));
            if (dashManifest.getPeriodCount() > 0) {
                if (dashManifest.getPeriod(0).adaptationSets.size() > 0) {
                    if (dashManifest.getPeriod(0).adaptationSets.get(0).representations.size() > 0) {
                        cdnName = dashManifest.getPeriod(0).adaptationSets.get(0).representations.get(0).baseUrl;
                    }
                }
            }

            URL uri = new URL(cdnName);
            cdnName = uri.getHost();

        } catch (IOException e) {
            e.printStackTrace();
        }


        return cdnName;
    }
```

**Comment by marcbaechinger** [comment]
Cool. Thanks. Please reopen if you need.
