### ISSUE TITLE
How to change audio track 

### ISSUE THREAD

**Issue by niiitish** [google/ExoPlayer#8522]
Can anyone please help me 
I am playing a video (contain 2 Audio) from my internal storage but i can't change audio i searched everywhere but I can't find any solution for this i want to change track like VLC App

**Comment by marcbaechinger** [comment]
Does the Developer Guide help? There is a page about selecting tracks and it has a code snippet telling how to select a given language. That could be a good start. You can find this page here: https://exoplayer.dev/track-selection.html

**Comment by niiitish** [comment]
Tysm for your reply sir.
Sir can you please show some examples so i can understand easily

**Comment by marcbaechinger** [comment]
I suggest you use the `EventLogger`, so you can [see the audio tracks in the log](https://exoplayer.dev/debug-logging.html#media-tracks):

```
MediaCodecAudioRenderer [
   Group:0, adaptive_supported=N/A [
       [X] Track:0, id=5, mimeType=audio/mp4a-latm, bitrate=128000, codecs=mp4a.40.2, channels=2, language=fr, supported=YES
     ]
   ]
```

Once you know what language your tracks have, you can check the code snippet in the developer guide page I referenced above. 

Please also do a bit of investigation yourself.
