### ISSUE TITLE
How to disable the seek bar if video is live Stream.

### ISSUE THREAD

**Issue by SharyRajpoot** [google/ExoPlayer#8527]
I have an app where I am using ExoPlayer lib.
In this app, I have some content that is provided by a user and then played using the internet.
Now, this content can be varied like it may be a simple video or a live stream.

Now in the **Simple Video**, we need to move the video to a certain position with the help of seek bar and here we can say we need it and that's what a seek bar is for.
**Simple Video Example: ** [Bugs Bunny](http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4)

Simple Video Seek Bar Example:
05:20 -----------**o**-------------- 10:25

 And,

Now in the **Live Stream Video**, we don't need the seek bar as we can move this video to a certain position as we do with the simple video. So this is my main question...

How can I disable the seek bar so the user can't interact with it or can seek the video? 
**ONLY IN LIVE STREAMS.**
I want something like this...
e.g:
00:00 -------------------------- 00:00

Here i want when the video is a live stream i want ExoPlayer, not the update the starting and ending video time and also no seek bar option is shown...

Sample Video Live Steam ( **just for reference** )
[Live Youtube Channel](https://www.youtube.com/watch?v=evpxACpzPtg)

**Comment by icbaker** [comment]
You can determine if the current `Window` is live:
https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/Timeline.Window.html#isLive

And use that to decide to hide the scrubber:
https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/ui/DefaultTimeBar.html#hideScrubber--

**Comment by SharyRajpoot** [comment]
> And use that to decide to hide the scrubber:
https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/ui/DefaultTimeBar.html#hideScrubber--

The methods you are pointing here are all PRIVATE and can not be accessible by class instance...

**Comment by icbaker** [comment]
Not sure I understand what you mean - the `hideScrubber` method is public, as-is the `DefaultTimeBar` class it's defined on.

For determining if the currently playing content is live, there's also more info here:
https://exoplayer.dev/troubleshooting.html#how-can-i-query-whether-the-stream-being-played-is-a-live-stream

**Comment by SharyRajpoot** [comment]
`hideScrubber ` is what I actually want...you got it right and.
Also, they are showing it public in `DefaultTimeBar ` documentation BUT if you looked at actual code in android studio for this then it private there, so we can access it by class instance.

**Comment by SharyRajpoot** [comment]
`hideScrubber` is what I actually want...you got it right and.
Also, they are showing it public in `DefaultTimeBar` documentation BUT if you looked at actual code in android studio for this then it private there, so we can access it by class instance.

**Comment by SharyRajpoot** [comment]
`hideScrubber ` is what I actually want...you got it right and.
Also, they are showing it public in `DefaultTimeBar ` documentation BUT if you looked at actual code in android studio for this, then it's private there, so we can access it by class instance.

**Comment by SharyRajpoot** [comment]
`hideScrubber` is what I actually want...you got it right and.
Also, they are showing it public in `DefaultTimeBar` documentation BUT if you looked at actual code in android studio for this, then it's private there, so we can't access it by class instance.

**Comment by icbaker** [comment]
Glad you got it working - still not quite sure what you mean about it being private in the code, the `hideScrubber` method was added in https://github.com/google/ExoPlayer/commit/d162c07ecf8472dfab532a48bfa9d6a56bd73fc7, released in 2.11.5 and it's always been public afaict.

**Comment by SharyRajpoot** [comment]
Oh, it's in version 2.11.5...
actually, I was using version 2.11.3 in which `hideScrubber` is a private method.
so I upgrade to the newer version and I got access to the `hideScrubber`. It did the work which I want but left with one more thing, as I can still able to seek or change the position of the video.
Even I have set the `isEnabled` to false still user can seek the video/live stream.
