### ISSUE TITLE
Force a maximum number of retrys in the get manifest case

### ISSUE THREAD

**Issue by Xlcghs** [google/ExoPlayer#8528]
Hi,

Is it possible to customize the maximum number of retrys to load the manifest in an error case?
I saw the possibility to customize the minimum number  and the delay between two retrys with loadErrorHandlingPolicy:

```
LoadErrorHandlingPolicy loadErrorHandlingPolicy =
    new DefaultLoadErrorHandlingPolicy() {
      @Override
      public long getRetryDelayMsFor(LoadErrorInfo loadErrorInfo) {
        // Implement custom back-off logic here.
      }
    };
```

however, I don't see the possibility of customizing the maximum number of retrys with this method.

Best Regards,

**Comment by icbaker** [comment]
Can you add more detail about what you're trying to do?

It's possible that the `minimum` wording in that method name is slightly confusing. The [javadoc](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/upstream/LoadErrorHandlingPolicy.html#getMinimumLoadableRetryCount-int-) says:
> Returns the minimum number of times to retry a load in the case of a load error, before propagating the error.

i.e. if the load attempts fail more than this value then the error is propagated up the call-stack (and not retried).

It's not clear to me what behaviour a 'maximum retry count' would imply? Assuming the max > min, how would you ever reach that if you've already propagated the error after exceeding the `minimum retry count` (and therefore aren't retrying any more, so the retry count isn't incrementing)?

**Comment by Xlcghs** [comment]
In fact, I will want to force an exact number of retrys otherwise the max number of retrys = the min number of retries.
I found a solution to force this behavior, below is an example to force an exact number of retrys to 2 : 

          setLoadErrorHandlingPolicy(new DefaultLoadErrorHandlingPolicy() {
            @Override
            public int getMinimumLoadableRetryCount(int dataType) {
                return 2;
            }

            @Override
            public long getRetryDelayMsFor(LoadErrorInfo loadErrorInfo) {
              IOException exception = loadErrorInfo.exception;
              return exception instanceof ParserException
              || exception instanceof FileNotFoundException
              || exception instanceof Loader.UnexpectedLoaderException
              || loadErrorInfo.errorCount > 2
              ? C.TIME_UNSET
              : min((loadErrorInfo.errorCount ) * 1000, 5000);
            }
        });

**Comment by icbaker** [comment]
Glad you solved the problem!

~FWIW I would expect just this to generally result in exactly 2 retries, so you may not need the extra logic in `getRetryDelayMsFor()`:~

Edit: My understanding was wrong about this, it depends on whether the errors are thrown during initial load or during playback.

**Comment by icbaker** [comment]
My expectation in the previous comment was wrong, it depends on whether the errors are thrown during initial load or during playback. I've edited it to reflect that - sorry for any confusion!
