### ISSUE TITLE
Program type already present: com.google.android.exoplayer2.core.R

### ISSUE THREAD

**Issue by rhonyabdullah** [google/ExoPlayer#8529]
- ExoPlayer version: "2.11.4"
- Android Plugin: com.android.tools.build:gradle:3.5.4
- Kotlin 1.3.61

I'm building a project that using exoplayer as a **library module**, whenever i try to build release (minify, shrinkresource & proguard enabled) i got this error:

```
> Task :app:transformClassesAndResourcesWithR8ForRelease
AGPBI: {"kind":"error","text":"Program type already present: com.google.android.exoplayer2.core.R","sources":[{}],"tool":"R8"}
Program type already present: com.google.android.exoplayer2.core.R


> Task :app:transformClassesAndResourcesWithR8ForRelease FAILED

Execution failed for task ':app:transformClassesAndResourcesWithR8ForRelease'.
> com.android.tools.r8.CompilationFailedException: Compilation failed to complete
```

But if i remove exoplayer dependencies build release is just fine, any help to resolve this issue ?

This thread [issue](https://github.com/google/ExoPlayer/issues/8517) still didn't help \.

I try turning off R8 obfuscation and got this warning using gradle build scan:
```
Warning: com.google.android.exoplayer2.R$layout: can't find referenced class com.tencent.rtmp.liteavsdk.R$layout |  
-- | --
  | Warning: com.google.android.exoplayer2.R$layout: can't find referenced class com.tencent.rtmp.liteavsdk.R$layout |  
  | Warning: com.google.android.exoplayer2.R$layout: can't find referenced class com.tencent.rtmp.liteavsdk.R$layout |  
  | Warning: com.google.android.exoplayer2.R$styleable: can't find referenced field 'int[] PlaybackControlView' in program class com.tencent.rtmp.liteavsdk.R$styleable |  
  | Warning: com.google.android.exoplayer2.R$styleable: can't find referenced field 'int PlaybackControlView_controller_layout_id' in program class com.tencent.rtmp.liteavsdk.R$styleable |  
  | Warning: com.google.android.exoplayer2.R$styleable: can't find referenced field 'int PlaybackControlView_fastforward_increment' in program class com.tencent.rtmp.liteavsdk.R$styleable |  
  | Warning: com.google.android.exoplayer2.R$styleable: can't find referenced field 'int PlaybackControlView_rewind_increment' in program class com.tencent.rtmp.liteavsdk.R$styleable |  
  | Warning: com.google.android.exoplayer2.R$styleable: can't find referenced field 'int PlaybackControlView_show_timeout' in program class com.tencent.rtmp.liteavsdk.R$styleable |  
  | Warning: com.google.android.exoplayer2.R$styleable: can't find referenced field 'int[] SimpleExoPlayerView' in program class com.tencent.rtmp.liteavsdk.R$styleable |  
  | Warning: com.google.android.exoplayer2.R$styleable: can't find referenced field 'int SimpleExoPlayerView_controller_layout_id' in program class com.tencent.rtmp.liteavsdk.R$styleable |  
  | Warning: com.google.android.exoplayer2.R$styleable: can't find referenced field 'int SimpleExoPlayerView_default_artwork' in program class com.tencent.rtmp.liteavsdk.R$styleable |  
  | Warning: com.google.android.exoplayer2.R$styleable: can't find referenced field 'int SimpleExoPlayerView_fastforward_increment' in program class com.tencent.rtmp.liteavsdk.R$styleable |  
  | Warning: com.google.android.exoplayer2.R$styleable: can't find referenced field 'int SimpleExoPlayerView_hide_on_touch' in program class com.tencent.rtmp.liteavsdk.R$styleable |  
  | Warning: com.google.android.exoplayer2.R$styleable: can't find referenced field 'int SimpleExoPlayerView_player_layout_id' in program class com.tencent.rtmp.liteavsdk.R$styleable |  
  | Warning: com.google.android.exoplayer2.R$styleable: can't find referenced field 'int SimpleExoPlayerView_resize_mode' in program class com.tencent.rtmp.liteavsdk.R$styleable |  
  | Warning: com.google.android.exoplayer2.R$styleable: can't find referenced field 'int SimpleExoPlayerView_rewind_increment' in program class com.tencent.rtmp.liteavsdk.R$styleable |  
  | Warning: com.google.android.exoplayer2.R$styleable: can't find referenced field 'int SimpleExoPlayerView_show_timeout' in program class com.tencent.rtmp.liteavsdk.R$styleable |  
  | Warning: com.google.android.exoplayer2.R$styleable: can't find referenced field 'int SimpleExoPlayerView_surface_type' in program class com.tencent.rtmp.liteavsdk.R$styleable |  
  | Warning: com.google.android.exoplayer2.R$styleable: can't find referenced field 'int SimpleExoPlayerView_use_artwork' in program class com.tencent.rtmp.liteavsdk.R$styleable |  
  | Warning: com.google.android.exoplayer2.R$styleable: can't find referenced field 'int SimpleExoPlayerView_use_controller' in program class com.tencent.rtmp.liteavsdk.R$styleable
```

Confusing here why exoplayer trying to refer another dependency (tencent liteavdsdk which i'm using it)

**Comment by icbaker** [comment]
There isn't enough info here for us to help you resolve the problem.

Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that demonstrates the problem in a way that we can build locally. 

This could be an Android Studio project on GitHub, or zipped up and sent to dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Please also update this issue to indicate you’ve done this.

**Comment by rhonyabdullah** [comment]
I have gradle build scan for more log info. Here: [gradle scan result](https://scans.gradle.com/s/ffes6cj53hrz2).

**Comment by icbaker** [comment]
Thanks for the build scan, unfortunately I don't see what could be causing the problem you're seeing.

The only suspicious part of the gradle scan is your dependency on `tv.danmaku.ijk.media:ijkplayer-exo:0.8.8` which depends on `com.google.android.exoplayer:exoplayer:r1.5.11`. This is getting auto-upgraded to 2.12.3 by Gradle:
```
com.google.android.exoplayer:exoplayer:r1.5.11 --> 2.12.3
```

This is **not** a compatible upgrade. ExoPlayer is generally not stable across versions, and certainly not from v1 to v2 (the whole package changed). I can't see how this could be causing the problem you're seeing, but I also can't see how `tv.danmaku.ijk.media:ijkplayer-exo:0.8.8` could possibly function if it was compiled against ExoPlayer 1.5.11 and is now trying to run against 2.12.3 AARs - you could perhaps try removing that dependency and see if it has any effect on the `R.java` error you're seeing.

Otherwise if you want us to take a further look:
> Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that demonstrates the problem in a way that we can build locally.

**Comment by rhonyabdullah** [comment]
Hi,
Sorry late response, you right, existing dependency `tv.danmaku.ijk.media:ijkplayer-exo:0.8.8` still using exoplayer `r1.5.11`but actually not being used. Luckily that library is open source and i can resolved it by removing that dependency. Thanks.
