### ISSUE TITLE
ArrayIndexOutOfBound when play HLS in DemoPlayer ( r1.4.2)

### ISSUE THREAD

**Issue by tungds** [google/ExoPlayer#853]
Hi,
When I playing HLS link on DemoPlayer, app  crash after display video about 1s.
I try this link on VLC, it's working fine!
Stack Trace below
```
10-09 10:40:22.178 5385-6678/com.play.digicom E/AndroidRuntime: FATAL EXCEPTION: ExoPlayerImplInternal:Handler
10-09 10:40:22.178 5385-6678/com.play.digicom E/AndroidRuntime: Process: com.play.digicom, PID: 5385
10-09 10:40:22.178 5385-6678/com.play.digicom E/AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: length=681; index=-12
10-09 10:40:22.178 5385-6678/com.play.digicom E/AndroidRuntime:     at java.util.ArrayList.get(ArrayList.java:310)
10-09 10:40:22.178 5385-6678/com.play.digicom E/AndroidRuntime:     at java.util.Collections$UnmodifiableList.get(Collections.java:1050)
10-09 10:40:22.178 5385-6678/com.play.digicom E/AndroidRuntime:     at com.google.android.exoplayer.hls.HlsChunkSource.getChunkOperation(HlsChunkSource.java:314)
10-09 10:40:22.178 5385-6678/com.play.digicom E/AndroidRuntime:     at com.google.android.exoplayer.hls.HlsSampleSource.maybeStartLoading(HlsSampleSource.java:510)
10-09 10:40:22.178 5385-6678/com.play.digicom E/AndroidRuntime:     at com.google.android.exoplayer.hls.HlsSampleSource.onLoadCompleted(HlsSampleSource.java:383)
10-09 10:40:22.178 5385-6678/com.play.digicom E/AndroidRuntime:     at com.google.android.exoplayer.upstream.Loader$LoadTask.handleMessage(Loader.java:245)
10-09 10:40:22.178 5385-6678/com.play.digicom E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102)
10-09 10:40:22.178 5385-6678/com.play.digicom E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:145)
10-09 10:40:22.178 5385-6678/com.play.digicom E/AndroidRuntime:     at android.os.HandlerThread.run(HandlerThread.java:61)
10-09 10:40:22.178 5385-6678/com.play.digicom E/AndroidRuntime:     at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
```

Any suggestion to solve this problem? Thanks.

**Comment by ojw28** [comment]
Please provide additional information as described [here](https://google.github.io/ExoPlayer/2015/10/01/reporting-issues.html). Thanks.

**Comment by tungds** [comment]
Following Reporting an issue structure:
- ExoPlayer demo app crash when playing a HLS link.
- I copy all code from demo app to my project. I replace a link of Sample[] HLS to my link, detail : 
```
  new Sample("Apple master playlist", "my_link", PlayerActivity.TYPE_HLS)
```
- Crash only happens with this link . But when I tested this link with VLC, it was working fine. My link : 
```
Sorry, I can't public this link or send link to dev.exoplayer email because security.
```
- ExoPlayer Version r1.4.2.
- I tested on Samsung Galaxy s2 (android 4.1.2), Samsung Galaxy s5(android 5.0) and Sony Xperia Z3(android 5.1.1). All of them crash with the link above.
This link below include my bugreport . I can't upload bug file here because file too large:
```
http://www.mediafire.com/download/t1y7u5x4kdo41li/bugreport.rar
```
Hope this help.

**Comment by ojw28** [comment]
Thanks!

Is the URL that you're providing to the player a master playlist (i.e. lists the variant playlists) or a variant playlist directly (i.e. lists the media segments)? If it's a master playlist, can you try passing each of the variant playlists directly instead? It would be useful to know whether they work correctly. If they do, then is it the case that the different variants have non-aligned media sequence indices and/or different duration media segments? If so, the issue you're seeing is the same as described in #699. Until we fix that issue, we only support aligned media sequence indices and (required for the media sequence indices to be aligned) equal duration media segments.

**Comment by tungds** [comment]
Thanks for your help,
My server stream has some errors in configuration so it is a reason why error happends in Exo Player.
Thanks!
