### ISSUE TITLE
No picture when playing Dolby Vision video (Unknown Dolby Vision level string)

### ISSUE THREAD

**Issue by moneytoo** [google/ExoPlayer#8530]
I'm unsuccessfully trying to play Dolby Vision videos that come from iPhone 11/12 devices (not necessarily the stock recorder app). When playing these two samples:

- iPhone 12: https://cdn.vox-cdn.com/uploads/chorus_asset/file/22023469/12_Pro_Max_IMG_0344.0.qt
- iPhone 11: https://drive.google.com/file/d/1cTRNwacsV-8J8PtcYNVDXBmGZF1SOynj

following is logged and video does not play (no picture at all):

```
W/MediaCodecUtil: Unknown Dolby Vision level string: 010
    Unknown Dolby Vision level string: 010
```

```
W/MediaCodecUtil: Unknown Dolby Vision level string: 012
    Unknown Dolby Vision level string: 012
```

Platform `VideoView` plays both videos just fine.

- ExoPlayer version number: 2.12.3
- Android version: 10
- Android device: OnePlus 7

**Comment by krocard** [comment]
For reference, the level is parsed by [this switch](https://github.com/google/ExoPlayer/blob/8a0d52be4b5402af0987fc7d009bc49977c72b67/library/core/src/main/java/com/google/android/exoplayer2/mediacodec/MediaCodecUtil.java#L1274-L1299).

**Comment by kim-vde** [comment]
Could you provide a bug report for the 2 following scenarios:
1.  Playing one of the videos with MediaPlayer/PlayerView.
2. Attempting to play it with ExoPlayer.

Note that:
- The Android platform doesn't have constants for levels > 9 (https://developer.android.com/reference/android/media/MediaCodecInfo.CodecProfileLevel) so we cannot just add the constants in the switch case mentioned above.
- Having a 3 digits level is a bit surprising. I'll ask Dolby if this is supported and how to interpret it.

**Comment by moneytoo** [comment]
Here are requested bug reports:

1. MediaPlayer: [bugreport-OnePlus7-QKQ1.190716.003-2021-02-02-22-02-18.MediaPlayer.zip](https://github.com/google/ExoPlayer/files/5914492/bugreport-OnePlus7-QKQ1.190716.003-2021-02-02-22-02-18.MediaPlayer.zip)
2. ExoPlayer: [bugreport-OnePlus7-QKQ1.190716.003-2021-02-02-22-08-39.ExoPlayer.zip](https://github.com/google/ExoPlayer/files/5914495/bugreport-OnePlus7-QKQ1.190716.003-2021-02-02-22-08-39.ExoPlayer.zip)

**Comment by kim-vde** [comment]
I just pushed a fix on branch dev-v2. It will be part of the next release (2.13.0).

Please open another bug if you encounter other issues. Thanks for reporting this one.

**Comment by moneytoo** [comment]
Amazing, thank you!

**Comment by moneytoo** [comment]
Just confirming that I'm able to play the videos with `dev-v2-r2.13.0` branch.
