### ISSUE TITLE
Clearkey DRM content with secure video path.

### ISSUE THREAD

**Issue by socnix-lab** [google/ExoPlayer#8531]
Hi,

I managed to create a demo app that plays clearkey DRM content. Everything plays fine. However, I am wondering if it is possible to play the clearkey DRM content via the secure video path so it can not be recorded? E.g. When exoplayer is playing a Widevine DRM content, the recorder video shows black screen. 

I am currently using the latest stable 2.12.3.

**Comment by Duna** [comment]
I have tried to encrypt the mp4 using ffmpeg or mp4box - and i am able to play with simple encryption key the encrypted file using ffplay

The main problem is I am not able to playback it via exoPlayer.

I used [drm.xml](https://drive.google.com/file/d/1JW9Y1fJQgszK5TWtH2V_L_6GXas-ARxQ/view?usp=sharing) when mp4box with command: MP4Box -crypt drm.xml legend.mp4 -out movie_encrypted.mp4
I used [these](https://drive.google.com/file/d/1EWVac1VF2dije7pL3-USUHEUnoE6r9mQ/view?usp=sharing) files with ffmpeg the command: ffmpeg -i legend.mp4 -vf scale=w=1280:h=720:force_original_aspect_ratio=decrease -c:a aac -ar 48000 -b:a 128k -c:v h264 -profile:v main -crf 20 -g 48 -keyint_min 48 -sc_threshold 0 -b:v 2500k -maxrate 2675k -bufsize 3750k -hls_time 4 -hls_playlist_type vod -hls_segment_filename beach/720p_%03d.ts beach/720p.m3u8 -hls_key_info_file enc.keyinfo

It is so strange that I have spent 2 days figuring out that ExoPlayer is not able to play via ClearKey and FFPLAY is able.

I think I am missing something in between....

**Comment by ojw28** [comment]
If you want to prevent recording then you can call [SurfaceView.setSecure(true)](https://developer.android.com/reference/android/view/SurfaceView#setSecure(boolean)) on the surface. If you're using one of ExoPlayer's player view UI components, then you can retrieve the surface to make this call like this:
```
((SurfaceView) playerView.getVideoSurfaceView()).setSecure(true);
```

Note that this is not quite the same as using the actual secure video path, which I don't think is possible when using ClearKey DRM. I'm not sure that the combination of ClearKey DRM and a secure video path makes sense even from a theoretical perspective, since I think the scheme itself is not secure enough for a secure video path to add additional protection.

**Comment by socnix-lab** [comment]
> If you want to prevent recording then you can call [SurfaceView.setSecure(true)](https://developer.android.com/reference/android/view/SurfaceView#setSecure(boolean)) on the surface. If you're using one of ExoPlayer's player view UI components, then you can retrieve the surface to make this call like this:
> 
> ```
> ((SurfaceView) playerView.getVideoSurfaceView()).setSecure(true);
> ```
> 
> Note that this is not quite the same as using the actual secure video path, which I don't think is possible when using ClearKey DRM. 

I am aware of FLAG_SECURE but it isn't the same as the same with secure video path. 

> I'm not sure that the combination of ClearKey DRM and a secure video path makes sense even from a theoretical perspective, since I think the scheme itself is not secure enough for a secure video path to add additional protection.

Thank you for your reply. I just see a use case and wondering if it is configurable. 

Another question, is there any online DRM license server that is recommended to work with exoplayer directly.

**Comment by ojw28** [comment]
> I just see a use case and wondering if it is configurable.

What use case do you see? If using the secure video path doesn't actually add any additional security, then it's unclear what you actually gain from it. If ClearKey provides sufficient protection for your use case, then you should just mark the surface as secure. If you need DRM suitable for high value content, then you should use Widevine instead.

**Comment by Duna** [comment]
Here it is the sourcecode of my class

```
class MainActivity : AppCompatActivity() {

    private var exoPlayer: SimpleExoPlayer? = null
    private var trackSelector: DefaultTrackSelector? = null
    var drmSessionManager: DefaultDrmSessionManager? = null

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        trackSelector = DefaultTrackSelector(this)
        exoPlayer = SimpleExoPlayer.Builder(this)
            .setTrackSelector(trackSelector!!)
            .build()

        player_view.player = exoPlayer

       var uri =  Uri.fromFile( File("//android_asset/movie_encrypted.mp4"))
       playVideo(uri, "J5kmSWp/p+YcNz4hkDPCEJH6YHvzuA", "dqbGXF6nYgRr10mi5jLMuw")

    }

    private fun playVideo(url: Uri, id: String, value: String){
        try {
            drmSessionManager =
                Util.getDrmUuid(C.CLEARKEY_UUID.toString())?.let { buildDrmSessionManager(
                    it,
                    true,
                    id,
                    value
                ) }
        } catch (e: UnsupportedDrmException) {
            e.printStackTrace()
        }
        exoPlayer?.setMediaSource(buildDashMediaSource(url))
        exoPlayer?.prepare()
        exoPlayer?.playWhenReady = true
    }

    private fun buildDashMediaSource(uri: Uri): MediaSource {
        val dashChunkSourceFactory = DefaultDataSourceFactory(this, "agent")
        return ProgressiveMediaSource.Factory(dashChunkSourceFactory)
            .setDrmSessionManager(drmSessionManager ?: DrmSessionManager.DUMMY)
            .createMediaSource(uri)
    }

    @Throws(UnsupportedDrmException::class)
    private fun buildDrmSessionManager(uuid: UUID, multiSession: Boolean, id: String, value: String): DefaultDrmSessionManager {
        val drmCallback = LocalMediaDrmCallback("{\"keys\":[{\"kty\":\"oct\",\"k\":\"${value}\",\"kid\":\"${id}\"}],\"type\":\"temporary\"}".toByteArray())
        val mediaDrm = FrameworkMediaDrm.newInstance(uuid)
        return DefaultDrmSessionManager(uuid, mediaDrm, drmCallback, null, multiSession)
    }
}
```

**Comment by socnix-lab** [comment]
> What use case do you see? If using the secure video path doesn't actually add any additional security, then it's unclear what you actually gain from it. If ClearKey provides sufficient protection for your use case, then you should just mark the surface as secure. If you need DRM suitable for high value content, then you should use Widevine instead.

it increase the protection against rooted devices or scrcpy to mirror/record the screen. It is not a ideal solution as the API can still be hook to extract the key but avoiding the Widevine server(). Yes, i am lean toward to Widevide DRM based solution instead of clearkey. Thank your for your help

Please feel free to close this issue. Thank you very much.
