### ISSUE TITLE
Unable to play FFMPEG/MP4BOX AES_CTR encrypted mp4 files ClearKey

### ISSUE THREAD

**Issue by Duna** [google/ExoPlayer#8532]
I have successfully tried to encrypt an MP4 file using ffmpeg and mp4box - and I am able to play with simple encryption key AES_CTR the encrypted file using ffplay

The main problem is I am not able to playback it via exoPlayer.

I used [drm.xml](https://drive.google.com/file/d/1JW9Y1fJQgszK5TWtH2V_L_6GXas-ARxQ/view?usp=sharing) when mp4box with command:
`MP4Box -crypt drm.xml legend.mp4 -out movie_encrypted.mp4`
I used [these](https://drive.google.com/file/d/1EWVac1VF2dije7pL3-USUHEUnoE6r9mQ/view?usp=sharing) files with ffmpeg the command:
`ffmpeg -i legend.mp4 -vf scale=w=1280:h=720:force_original_aspect_ratio=decrease -c:a aac -ar 48000 -b:a 128k -c:v h264 -profile:v main -crf 20 -g 48 -keyint_min 48 -sc_threshold 0 -b:v 2500k -maxrate 2675k -bufsize 3750k -hls_time 4 -hls_playlist_type vod -hls_segment_filename beach/720p_%03d.ts beach/720p.m3u8 -hls_key_info_file enc.keyinfo`

It is so strange that I have spent 2 days figuring out that ExoPlayer is not able to play via ClearKey and FFPLAY is able.

I think I am missing something in between....using implementation 'com.google.android.exoplayer:exoplayer:2.12.3'

**Comment by icbaker** [comment]
Please provide media we can use to reproduce this issue.

Please either link it here or send to dev.exoplayer@gmail.com using a subject in the format "Issue #1234" (where "#1234" should be replaced with this issue number.) Please also update this issue to indicate you’ve done this.

**Comment by Duna** [comment]
I executed the ffmpeg command to encrypt an mp4 file AES_CTR: 
`ffmpeg -i legend.mp4 -vcodec copy -acodec copy -encryption_scheme cenc-aes-ctr -encryption_key 76a6c65c5ea762046bd749a2e632ccbb -encryption_kid a7e61c373e219033c21091fa607bf3b8 legend_encrypted.mp4`
The output file is [here](https://drive.google.com/file/d/1hL-Xuw1NZ2YbUwN0AQXy8qWxRgOPIAqB/view?usp=sharing)
The movie sound is playing with ExoPlayer, but the video not. The same result when I encrypt the video using MP4Box. Here it is the [drm.xml](https://drive.google.com/file/d/1JW9Y1fJQgszK5TWtH2V_L_6GXas-ARxQ/view?usp=sharing) file. Here it is the command line used:
`MP4Box -crypt drm.xml legend.mp4 -out movie_encrypted.mp4`
If i play the movie with the ffplay with clearkey, then the video is playing. 
`ffplay legend_encrypted.mp4 -decryption_key 76a6c65c5ea762046bd749a2e632ccbb`
I use the latest ffmpeg release and latest ExoPlayer release

**Comment by Duna** [comment]
Here it is the sourcecode of my class

```
class MainActivity : AppCompatActivity() {

    private var exoPlayer: SimpleExoPlayer? = null
    private var trackSelector: DefaultTrackSelector? = null
    var drmSessionManager: DefaultDrmSessionManager? = null

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        trackSelector = DefaultTrackSelector(this)
        exoPlayer = SimpleExoPlayer.Builder(this)
            .setTrackSelector(trackSelector!!)
            .build()

        player_view.player = exoPlayer

       var uri =  Uri.fromFile( File("//android_asset/movie_encrypted.mp4"))
       playVideo(uri, "p+YcNz4hkDPCEJH6YHvzuA", "dqbGXF6nYgRr10mi5jLMuw")

    }

    private fun playVideo(url: Uri, id: String, value: String){
        try {
            drmSessionManager =
                Util.getDrmUuid(C.CLEARKEY_UUID.toString())?.let { buildDrmSessionManager(
                    it,
                    true,
                    id,
                    value
                ) }
        } catch (e: UnsupportedDrmException) {
            e.printStackTrace()
        }
        exoPlayer?.setMediaSource(buildDashMediaSource(url))
        exoPlayer?.prepare()
        exoPlayer?.playWhenReady = true
    }

    private fun buildDashMediaSource(uri: Uri): MediaSource {
        val dashChunkSourceFactory = DefaultDataSourceFactory(this, "agent")
        return ProgressiveMediaSource.Factory(dashChunkSourceFactory)
            .setDrmSessionManager(drmSessionManager ?: DrmSessionManager.DUMMY)
            .createMediaSource(uri)
    }

    @Throws(UnsupportedDrmException::class)
    private fun buildDrmSessionManager(uuid: UUID, multiSession: Boolean, id: String, value: String): DefaultDrmSessionManager {
        val drmCallback = LocalMediaDrmCallback("{\"keys\":[{\"kty\":\"oct\",\"k\":\"${value}\",\"kid\":\"${id}\"}],\"type\":\"temporary\"}".toByteArray())
        val mediaDrm = FrameworkMediaDrm.newInstance(uuid)
        return DefaultDrmSessionManager(uuid, mediaDrm, drmCallback, null, multiSession)
    }
}
```

**Comment by icbaker** [comment]
Thanks for the file. It doesn't seem to contain a `pssh` box, meaning ExoPlayer doesn't know it's encrypted and so doesn't attempt to decrypt it.

I found this by analyzing it with MP4Box: https://gpac.github.io/mp4box.js/test/filereader.html

The result of this is that `newFormat.drmInitData == null` in `SampleQueue#onFormatResult`, meaning we never acquire a `DrmSession`.

Preparing valid media is outside the scope of this issue tracker, but the MP4Box XML config in this comment might help:
https://github.com/google/ExoPlayer/issues/8237#issuecomment-732100349

I noticed some other things about your setup that don't seem quite right:

* The key IDs and values that are in the JSON string you're passing to `LocalMediaDrmCallback` are [expected to be base64 **URL** encoded](https://www.w3.org/TR/encrypted-media/#clear-key-license-format). That means I believe the ID should be `p-YcNz4hkDPCEJH6YHvzuA` and not `p+YcNz4hkDPCEJH6YHvzuA`.

* Having said that, your XML file seems to use the same hex string for both key ID and value:
  ```
  <key KID="0x76a6c65c5ea762046bd749a2e632ccbb" value="0x76a6c65c5ea762046bd749a2e632ccbb"/>
  ```
  If you compare that to the comment I linked above, you'll see they use the `KID` XML attribute to carry the key ID, which is different to the value.

* The pssh part in your XML also doesn't seem to start with a SystemID I recognise. As defined by section 8.1.2 of ISO 23001-7:2016, and [here](https://w3c.github.io/encrypted-media/format-registry/initdata/cenc.html#common-system-definition) the pssh box should start with a SystemID, probably the [Common SystemID](https://w3c.github.io/encrypted-media/format-registry/initdata/cenc.html#common-system).
  * Compare your line: `<BS ID128="6770616363656E6364726D746F6F6C31"/>`
  * With the one from #8237: `<BS ID128="1077efecc0b24d02ace33c1e52e2fb4b"/>`

**Comment by Duna** [comment]
Again I rebuilt the input and output files. I generated the encrypted file using mp4box using the following command line:
`MP4Box -crypt drm_file.xml legend.mp4 -out legend_enc.mp4`
The drm file looks like this:
```
<GPACDRM type="CENC AES-CTR">
  <DRMInfo type="pssh" version="1">
    <BS ID128="1077efecc0b24d02ace33c1e52e2fb4b"/>
    <BS bits="32" value="1"/>
    <BS ID128="cd7eb9ff88f34caeb06185b00024e4c2"/>
  </DRMInfo>
  <CrypTrack IV_size="8" first_IV="0xbb5738fe08f11341" isEncrypted="1" saiSavedBox="senc" trackID="1">
    <key KID="0xcd7eb9ff88f34caeb06185b00024e4c2" value="0x63cb5f7184dd4b689a5c5ff11ee6a328"/>
  </CrypTrack>
</GPACDRM>
```
I am able to play the file using the command:
`ffplay legend_enc.mp4 -decryption_key 63cb5f7184dd4b689a5c5ff11ee6a328`

When I am trying to play the file with ExoPlayer it seems the PSSH box is ignored and the file is not playable.
I play the offline video with [Base64](https://base64.guru/converter/encode/hex) generated key_id and value like this: 
`playVideo(uri, "zX65/4jzTK6wYYWwACTkwg", "Y8tfcYTdS2iaXF/xHuajKA")...`

Generated encrypted video is [here](https://drive.google.com/file/d/1_g619Bk8a_X8Bg3Kv66fQyNZUI4Fa1J3/view?usp=sharing)

I analysed the video using [GPAC](https://gpac.github.io/mp4box.js/test/filereader.html) and the PSSH box is there. 

Why the ExoPlayer is not able to play the video and the FFPLAY is able? Is there a way to initialise the player in such a way that do not ignore the PSSH box, or build PSSH box by code?

**Comment by Duna** [comment]
Following this example https://github.com/ruthwikkk/DRMOffline

**Comment by icbaker** [comment]
I can see the pssh box too in your latest linked file. And I agree it plays with your provided `ffplay` command (however the fact it also played the file without a pssh box suggests they're not using the same approach as ExoPlayer, so it's not a great comparison).

After looking deeper into this, I found that ExoPlayer's `Mp4Extractor` actually doesn't read pssh boxes. Currently we only read this info in fragmented MP4 files (using `FragmentedMp4Extractor`). This means even when playing the file with the pssh box, the `drmInitData` still ends up null - meaning playback fails. I didn't realise this limitation when you initially filed the issue, otherwise I would have flagged it earlier.

I [fragmented](https://github.com/gpac/gpac/wiki/Fragmentation,-segmentation,-splitting-and-interleaving) your file (into a single fragment) by selecting a fragment length (240s) longer than the content (123s):
```
$ MP4Box -frag 240000 legend_enc.mp4 -out legend_enc_frag.mp4
```

I'm then able to play this file with the demo app by configuring a `DrmSessionManager` & `LocalDrmCallback` as you've done [above](https://github.com/google/ExoPlayer/issues/8532#issuecomment-771868978).

One thing I did notice is that the base64 key ID & value in your JSON key response are normal base64 encoded, **not** URL-safe encoded. The [URL-safe alphabet](https://tools.ietf.org/html/rfc4648#section-5) uses `-` for 62 (vs `+` in normal base64) and `_` for 63 (vs `/` in normal base64). So I think technically this line in your code should be:
```
playVideo(uri, "zX65_4jzTK6wYYWwACTkwg", "Y8tfcYTdS2iaXF_xHuajKA")...
``` 

However I tried both and both seemed to work on my Pixel 3a XL - so perhaps the MediaDrm implementation is robust against either variant being passed. If you see problems, that might be something worth trying though.

**Comment by Duna** [comment]
I am confirming that the file `legend_enc_frag.mp4` is playing now. 
So a small bug remains in ExoPlayer drmInitData - is null even if pssh box is present in encoded mp4 videos.
Should I log a new issue, or someone will work on this already logged  issue?

**Comment by icbaker** [comment]
Glad you got your content playing!

> So a small bug remains in ExoPlayer drmInitData - is null even if pssh box is present in encoded mp4 videos.

I wouldn't say it's a bug. We just don't currently support reading pssh boxes from non-fragmented MP4 files.

You're welcome to file an issue requesting us to add support for this, but given that DRM is most commonly used for content streamed over DASH or HLS (which both use fragmented MP4), and how easy it seems to be to transform a non-fragmented progressive MP4 to a fragmented one, it's not clear how high a priority it should be to add this support - and thus how quickly we'd implement it.

I suspect we would welcome PR adding it, but there's likely more to do than just reading the pssh box - I think there will be other boxes that will need to be supported in `Mp4Extractor` to make it work.

**Comment by Duna** [comment]
I'll have a look into code, can you tell me the class involved? I didn't
developed for this project and do not want to spent too much time on
debugging it.

Thank you for your time

**Comment by icbaker** [comment]
[`Mp4Extractor`](https://github.com/google/ExoPlayer/blob/dev-v2/library/extractor/src/main/java/com/google/android/exoplayer2/extractor/mp4/Mp4Extractor.java) is used for non-fragmented MP4s, [`FragmentedMp4Extractor`](https://github.com/google/ExoPlayer/blob/dev-v2/library/extractor/src/main/java/com/google/android/exoplayer2/extractor/mp4/FragmentedMp4Extractor.java) is used for fragmented ones.

You probably also want to take at look at our contributing guide if you haven't seen it already:
https://github.com/google/ExoPlayer/blob/dev-v2/CONTRIBUTING.md

**Comment by Duna** [comment]
Just one more question: I am willing to use ffmpeg instead of mp4box
Is there an equivalent command line to add the pssh box to ffmpeg command line file encryption?
`MP4Box -crypt drm_file.xml legend.mp4 -frag 240000 -out legend_enc.mp4` - I am looking for the equivalent using ffmpeg

**Comment by rbouqueau** [comment]
@Duna No equivalent but you could also use GPAC to encode your content (they rely on FFmpeg's libraries). There are command-lines in the fox for MP4Box (https://github.com/gpac/gpac/wiki/mp4box-dash-opts) or the newer ```gpac``` executable (https://github.com/gpac/gpac/wiki/encryption-filters).
