### ISSUE TITLE
DASH playback start position is wrong under SegmentTemplate number mode 

### ISSUE THREAD

**Issue by happyong-ib** [google/ExoPlayer#8537]
Under Dash number mode, the playback starts from the begin of window, seems the suggestedPresentationDelay of manifest does not apply.
I use the dev-v2 branch 724ded167c973991eb58d49e3d0f2aa9be62ed2e (2021-01-26).

I also debug the code, please check the following code in DashMediaSource.java line 917,
      long liveStreamEndPositionInLastPeriodUs = currentEndTimeUs - C.msToUs(lastPeriod.startMs);
Here the currentEndTimeUs refers to the period-relative endTimeUs, it shouldn't subtract the period.startMs.

**Comment by ojw28** [comment]
In nearly all cases where we've received reports similar to this one, the problem was that the media being played did not conform to the DASH specification.

In any case, we need concrete reproduction steps to investigate this further. Please provide an accessible sample stream and reproduction steps for us to take a look.

**Comment by happyong-ib** [comment]
Our test live stream is difficult to push to the public network, I can only provide one MPD for reference. Here it is single period with non-zero value for start@Period.
[t594_hd_long.zip](https://github.com/google/ExoPlayer/files/5922935/t594_hd_long.zip)

I also find one public dashif test streaming for testing, 
http://reference.dashif.org/dash.js/nightly/samples/dash-if-reference-player/index.html
Stream > LIVE (Dynamic MPD) > Multiperiod SegmentTemplate. New period every minute (livesim), click 'Load' to play. It works well in dash javascript player. It display the current time with format "00:mm:ss:SS".
I aslo test it on exoplayer but playback failed, I got http 404 and also found the requested media url use startNumber of first period in mpd. I have some doubts about liveStreamEndPositionInLastPeriodUs value, also included these params naming and values of function updateMediaItemLiveConfiguration() (cause the liveConfiguration.targetOffsetMs with abnormal vaule), please double check them. Test steps:
1) check out the dev-v2 branch 724ded1 (2021-01-26)
2) add the following lines into demo/assets/media.exolist.json
{
        "name": "DASH number with multi-period",
        "uri": "https://livesim.dashif.org/livesim/periods_60/continuous_1/testpic_2s/Manifest.mpd"
      }
3) lanuch demo app and click this test streaming, report "playback failed", from the logcat report http 404.  
[logcat.txt](https://github.com/google/ExoPlayer/files/5922943/logcat.txt)

**Comment by ojw28** [comment]
@tonihei - The stream provided above works in 2.12, but not in 2.13. I think this must be related to changes made for low latency live streaming. I did a bit of digging and shared a possible fix for discussion.

**Comment by ojw28** [comment]
@tonihei - I did a bit of digging and shared a possible fix for discussion.

**Comment by tonihei** [comment]
Thanks both!  @happyong-ib Your initial investigation exactly pinpointed the problem, sorry for the delay in addressing this.  We'll push a fix soon and release it as part of 2.13.1.
