### ISSUE TITLE
Jcenter will be shutdown on May 1st, can you migrate to mavenCentral?

### ISSUE THREAD

**Issue by apkelly** [google/ExoPlayer#8544]
As per this article - https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

Jcenter will be shutdown on May 1st 2021, can you please publish the exoplayer artefacts to mavenCentral()

Thanks.

**Comment by andrewlewis** [comment]
We're looking into migrating to GMaven (#5246).

**Comment by andrewlewis** [comment]
Duplicate of #5246
