### ISSUE TITLE
class AudioFocusManager function shouldAbandonAudioFocus logic error

### ISSUE THREAD

**Issue by keqizwl** [google/ExoPlayer#8545]
```
private boolean shouldAbandonAudioFocus(@Player.State int playbackState) {
  return playbackState == Player.STATE_IDLE || focusGain != C.AUDIOFOCUS_GAIN;
}
```
when player not gain the audio focus, why should it abandon?

**Comment by icbaker** [comment]
Looks like this logic changed in https://github.com/google/ExoPlayer/commit/cc29798d9b7dec65785c1a93a2a186352c92ff6f in response to https://github.com/google/ExoPlayer/issues/7182.

@krocard can you comment on this?

**Comment by krocard** [comment]
`focusGain` is not whether the focus is currently held. It is a member that caches the type of audio focus request that should be done for the current audioAttributes. If it is not AUDIOFOCUS_GAIN, that means that ExoPlayer should not be holding the audio focus.

**Comment by ojw28** [comment]
@keqizwl - If you have a specific issue, please describe the problem in terms of the problematic behavior. For example by describing, with reproduction steps, a specific case in which audio focus is not held when you think that it should be.

**Comment by keqizwl** [comment]
sorry，i misunderstand the code。

**Comment by krocard** [comment]
No worries, I got confused myself too by this code. I have renamed that member and a few others to clarify their meaning.
