### ISSUE TITLE
FFMPEG extension codec error

### ISSUE THREAD

**Issue by jjuandiaz** [google/ExoPlayer#8549]
ExoPlaybackException: MediaCodecVideoRenderer

first of all I use extension FFMPEG to reproduce Audio AC3 and it's works on emulator
but when I running on physical devices the application doesn't work .

 
When reporting a bug:
-------------------------

I attach files where found logcat here you search errors when I play stream video 
and the class  where I programming this .
that all .

proyect demo https://we.tl/t-rJ2Sh4tfcN
 
[logcat.txt](https://github.com/google/ExoPlayer/files/5928013/logcat.txt)

- ExoPlayer version number 2.12.1
- Android version 9
- Android device HUAWEI ATU-LX3.
 

[ffmpeg.aar.zip](https://github.com/google/ExoPlayer/files/5928021/ffmpeg.aar.zip)

[VideoPlayerActivity.kt.zip](https://github.com/google/ExoPlayer/files/5928023/VideoPlayerActivity.kt.zip)

**Comment by icbaker** [comment]
In the logcat snippet provided it looks like the video decoder crashes:

```
E/ACodec: [OMX.qcom.video.decoder.avc] ERROR(0x80001009)
    signalError(omxError 0x80001009, internalError -2147483648)
E/MediaCodec: Codec reported err 0x80001009, actionCode 0, while in state 6
```

Unfortunately the `STREAM_URL` in the provided project doesn't resolve for me:

```
$ curl http://10.40.0.20:1935/wimuxTest/lo_discoveryTheaterUDP.stream/playlist.m3u8
curl: (28) Failed to connect to 10.40.0.20 port 1935: Connection timed out
```

Without access to the stream it's very hard for us to investigate further. Please host it somewhere accessible and share it here or send to dev.exoplayer@gmail.com using a subject in the format "Issue #1234" (where "#1234" should be replaced with this issue number.) Please also update this issue to indicate you’ve done this.

You can also try playing the stream in the [demo app with the ffmpeg decoder](https://exoplayer.dev/demo-application.html#enabling-extension-decoders). If it works there then it's likely something wrong with your application. If it doesn't work in the demo app then please provide the zip file produced by running `adb bugreport` after the failure.

**Comment by jjuandiaz** [comment]
Sorry I forget that only work url in LAN

here new URL http://170.247.204.7:1935/test/discoveryTheater/playlist.m3u8

**Comment by jjuandiaz** [comment]
Sorry I forget that only work url in LAN

here new URL http://0.0.0.0:1935/test//playlist.m3u8

**Comment by icbaker** [comment]
The video in the TS files of your HLS stream is interlaced (MBAFF is a form of interlacing: https://en.wikipedia.org/wiki/Advanced_Video_Coding#Features):

```
$ mediainfo media_w339580790_675.ts
...
Scan type                                : MBAFF
Scan type, store method                  : Interleaved fields
Scan order                               : Top Field First
...
```

When I play the stream on a Pixel 3a XL the video is garbled with lots of pink & green decoding artefacts - a symptom of not correctly de-interlacing interlaced content.

Android devices aren't required to support interlaced video in general: https://github.com/google/ExoPlayer/issues/3468#issuecomment-441601053

I suspect that explains the problems you're seeing.

I agree the stream plays back fine in the emulator, I guess that does support interlaced content.
