### ISSUE TITLE
Trick-play track selection

### ISSUE THREAD

**Issue by davydovvladimir** [google/ExoPlayer#8555]
Hi all,

Could you please suggest a proper way to implement switching to trick-play tracks?

I have searched and found one solution is to override canSelectFormat() method in AdaptiveTrackSelection.

But after this commit: https://github.com/zxzx74147/ExoPlayer/commit/2b1ec5cd850cf30f5331333dd004124866c8ebc3
it seems impossible because trick-play tracks are removing from track group for AdaptiveTrackSelection.

Another way I see is to override selectVideoTrack() method in  DefaultTrackSelector. But in that case I need to re-implement a lot of code which is called by original selectVideoTrack();

So, what is correct way to implement did you assume for trick-play modes?

Thanks.

**Comment by icbaker** [comment]
> But after this commit: [zxzx74147@2b1ec5c](https://github.com/zxzx74147/ExoPlayer/commit/2b1ec5cd850cf30f5331333dd004124866c8ebc3)

That commit isn't in this repository. You perhaps mean this one: https://github.com/google/ExoPlayer/commit/bdc0db30fdddc3cbc01827acdf46b56dfc802bb5.

----

@tonihei PTAL

**Comment by davydovvladimir** [comment]
> > But after this commit: [zxzx74147@2b1ec5c](https://github.com/zxzx74147/ExoPlayer/commit/2b1ec5cd850cf30f5331333dd004124866c8ebc3)
> 
> That commit isn't in this repository. You perhaps mean this one: [bdc0db3](https://github.com/google/ExoPlayer/commit/bdc0db30fdddc3cbc01827acdf46b56dfc802bb5).
> 
> @tonihei PTAL

Yes, maybe. I just copied commit url from here: https://github.com/google/ExoPlayer/issues/474
But anyway current release and master branches have this code.

**Comment by tonihei** [comment]
You should be able to set an `SelectionOverride` with `DefaultTrackSelector.ParametersBuilder.setSelectionOverride`. 
The trick play track is still there, so you can manually select it in this way. bdc0db3 just changed it so that the track isn't automatically included in an adaptive selection.

**Comment by davydovvladimir** [comment]
@tonihei 
I have implemented switching by using SelectionOverride and it is working correct.
Thank you!
