### ISSUE TITLE
Configure a proxy for the traffic

### ISSUE THREAD

**Issue by lpuglia** [google/ExoPlayer#8556]
Hello, thanks for the amazing library. I was wondering if it is possible to configure a proxy for the player.

I can easily setup a proxy for some `HttpURLConnection` I'm performing but now I would like to route the traffic of the player itself through the same proxy.

Any advice on the subject will be much appreciated.

**Comment by kim-vde** [comment]
My understanding is that it should just work if you provide the proxy URI to the player (see #6024 and #2954)? If not, could you clarify what you are trying to do?

**Comment by lpuglia** [comment]
Hello, what do you mean by "provide the proxy URI to the player", how do you do that?

**Comment by kim-vde** [comment]
My understanding is that you have a [proxy server](https://en.wikipedia.org/wiki/Proxy_server) that redirects the calls to retrieve the media contents and that you send your requests to this proxy server using the corresponding URI/URL.

Please provide more detail if this is not what you are trying to do.

**Comment by lpuglia** [comment]
i know what a proxy server is and how to use it, i don't know how to tell exoplayer how to use it

**Comment by kim-vde** [comment]
Here is some information that could help:
- ExoPlayer uses a [`DefaultHttpDataSource`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/upstream/DefaultHttpDataSource.html) by default, which in turn uses an `HttpURLConnection`. If you set up the proxy for `HttpURLConnection ` by configuring some global properties somewhere, then this approach should also work with ExoPlayer, as long as you are not using an other `DataSource`.
- If you need to access the `HttpURLConnection` instance directly, then you could try to use a [custom `DataSource`](`HttpUrlConnection`) extending the `DefaultHttpDataSource`.

If this doesn't help, please provide more information, such as:
- How do you set up the proxy with `HttpURLConnection`?
- How do you build the player? More precisely, do you pass a `DataSource` such as `DefaultHttpDataSource`, `OkHttpDataSource` or `CronetDataSource`?

**Comment by lpuglia** [comment]
Thanks, this is very helpful advice. Unfortunately I already tried to set up a global proxy for all the `HttpURLConnection` without any success, at this point I doubt it is possible to do. I can instantiate single proxied `HttpURLConnection` without problems though. 

I think that the only way to allow ExoPlayer to use a proxy is to write my own extension of `HttpDataSource`. would that be enough to proxy all the requests the player makes?

**Comment by lpuglia** [comment]
@kim-vde Thank you very much for your suggestions, they put me on the right direction. I was finally able to make a `MediaSource` with a proxy connection. I struggled a lot with `HttpURLConnection` because on android it has limitations that are not present in a normal JVM. In particular the following global variables:
```java
systemProperties.setProperty("http.proxyHost",proxy);
systemProperties.setProperty("http.proxyPort",port);
```

are ignored in android. I was also trying to use the `Proxy` class:
```java
Proxy proxy = new Proxy(Proxy.Type.HTTP, new InetSocketAddress(proxy, port));
```
for each single connection but I hit a hard wall when i tryed to swith to an authentication proxy:
```java
Authenticator authenticator = new Authenticator() {

    public PasswordAuthentication getPasswordAuthentication() {
        return (new PasswordAuthentication(user,
                password.toCharArray()));
    }
};
Authenticator.setDefault(authenticator);
```
the Exception I was getting was:
```
java.net.ProtocolException: unexpected end of stream
```

In the end, your answer put me on the right track because while i was searching for a way to implement my own  `DefaultHttpDataSource` I came accross `OkHttpClient` and its ExoPlayer [extension](https://github.com/google/ExoPlayer/tree/release-v2/extensions/okhttp). For me it was much easier to setup `OkHttpClient` with proxy, after adding my client to the mentioned extension everything started to work flawlessy. For future reference here is my code for a proxied HLS stream:

```java
okhttp3.Authenticator proxyAuthenticator = new Authenticator() {
    @Override
    public Request authenticate(Route route, Response response) throws IOException {
        String credential = Credentials.basic(user, password);
        return response.request().newBuilder()
                .header("Proxy-Authorization", credential)
                .build();
    }
};
OkHttpClient client = new OkHttpClient.Builder()
        .proxy(new Proxy(Proxy.Type.HTTP, new InetSocketAddress(proxy, port)))
        .proxyAuthenticator(proxyAuthenticator)
        .build();

DataSource.Factory dataSourceFactory =
        new OkHttpDataSourceFactory(client);

MediaSource mediaSource =
        new HlsMediaSource.Factory(dataSourceFactory).createMediaSource(Uri.parse(uri));
```

I hope this will help someone else in the future. Regards
