### ISSUE TITLE
Possibility of customizing the entire layout file?

### ISSUE THREAD

**Issue by ghost** [google/ExoPlayer#8559]
Hi,
Is it not possible to customize the entire layout file? I don't want the player to be black when I have light theme. There seems to be no other questions asked about this other than customizing the control buttons. In my case, I want a complete redesign with the same controls but just with a light background.
Thanks.

**Comment by Blatzar** [comment]
https://levelup.gitconnected.com/customize-exoplayer-overlay-look-like-youtube-player-14fdd6d4583d
gives a good explanation how to override entire player UI :)

**Comment by ojw28** [comment]
Please also see https://exoplayer.dev/ui-components.html and the Javadoc for the UI components you're using, both of which provide additional documentation about this.
