### ISSUE TITLE
Integration of exoplayer in android auto (car play).

### ISSUE THREAD

**Issue by ghost** [google/ExoPlayer#8561]
Hello ,
I have one request to developer. I need to integrate exoplayer in android car play i.e. android auto. I need help whether exoplayer can be integrated in android auto ? any example will be helpful for developing android app for car using exoplayer.And also if we can do that then can we make custom design for car play using exoplayer's support. Thanks in advance.

**Comment by marcbaechinger** [comment]
To create  media app for Android Auto you need basically provide two things: a way to let the user browse the media library and on the other hand, player controls that display the state of the player and allow sending commands to the player.

For browsing the media you create a [`MediaBrowserServiceCompat`](https://developer.android.com/guide/topics/media-apps/audio-app/building-a-mediabrowserservice) that allows the Android Auto companion app to browse the categories of media. Your implementation of the `MediaBrowserServiceCompat` will house the ExoPlayer instance and a `MediaSession`.

The `MediaSession` provides the second part which is representing the state of the player and sending/receiving playback commands from Android Auto. You can use the `MediaSessionConnector` of the [media session extension](https://github.com/google/ExoPlayer/tree/release-v2/extensions/mediasession) of the ExoPlayer library for this (seethis  [Medium blog post](https://medium.com/google-exoplayer/the-mediasession-extension-for-exoplayer-82b9619deb2d) also) . The `MediaSessionConnector` maps the state of the player to the media session and receives commands sent by controller and applies these to appropriate ExoPlayer method calls. 

That's what you need to provide in a nutshell. There is more detailed documentation available on Android Developers in the article ['Building media apps for cars'](https://developer.android.com/training/cars/media). There is also an [IO19 talk which gives an  overview](https://youtu.be/AHHERLwjUGo) on `MediaBrowserService` and `MediaSession`. The most helpful resource will probably be the [UAMP sample app](https://github.com/android/uamp) that implements a `MusicService.kt` in the common module that is using the `MediaSessionConnector`. The `automotive` module of the app includes a lot of details of the auto integration. UAMP is a great resource for you to investigate the details of the Auto integration.

**Comment by ghost** [comment]
Hello,
Thanks for your detailed explanation. I go through your points one last question can we use exoplayer for live hls streaming in andorid car play (Android auto) ? and if so then how ? what is the exact way to do that ?

**Comment by marcbaechinger** [comment]
You can play any content just like in a normal local app including HLS live content. That works exactly the same by [using an `MediaItem`](https://exoplayer.dev/media-items.html) with an HLS uri or by directly [creating an HLS media source](https://exoplayer.dev/media-sources.html).  

The player will run in the `MediaBrowserServiceCompat` and receive commands via media session that has been sent by the Android Auto companion app. But that is completely transparent for the app. You can simulate the behavior of Android Auto by using a `MediaControllerCompat.TransportControl` and send [`playByXyz`](https://developer.android.com/reference/kotlin/android/support/v4/media/session/MediaControllerCompat.TransportControls#playfrommediaid) commands by using the transport control. You can implement your own `PlaybackPreparer` for the `MediaSessionConnector` to receive this play commands, create a media item and [modify the playlist of the player](https://exoplayer.dev/playlists.html#modifying-the-playlist) accordingly.
