### ISSUE TITLE
How to remove LRU files from download cache?

### ISSUE THREAD

**Issue by vhow** [google/ExoPlayer#8563]
As the [doc](https://exoplayer.dev/downloading-media.html) says: 

> A download cache should not evict media, so should use a NoopCacheEvictor.

What is the recommend way to **remove least recently used cache** files from **download cache**?

**Comment by marcbaechinger** [comment]
I don't think there is an easy way to use the same `Cache` instance that you are using with a `DownloadManager` for normal caching with `CacheDataSource`. That's what the documentation means when it is saying 'download cache' (used for persistent offline media) as opposed to a 'temporary cache' utilized to facilitate seeking backwards and repetitive playback of the same media.

You probably can use two different cache instances for one and the other use case. That would mean that you check first whether a given media is available offline, if this is the case you use the 'Cache' that you use with the download manager as well. If the media is not available offline you can use another cache instance to setup the `CacheDataSource`. That second instance could then apply a LRU strategy for eviction.
