### ISSUE TITLE
One empty extra closed captions track with mime type eia608 always presented in HLS stream with ts chunks

### ISSUE THREAD

**Issue by sergju** [google/ExoPlayer#8567]
One empty extra closed captions track with mime type eia608 always presented in HLS stream with ts chunks.

It can be seen with ExoPlayer demo app as well.
For example link "Apple TS media playlist" I see only one "Unknown track"
but I can't see any closed caption track in m3u8 playlist and inside ts chunk

With link "Apple 16x9 basic stream" several tracks on languages and again - "Unknown track"

Checked on latest ExoPlayer verions 2.13

TextRenderer [
  Group:0, adaptive_supported=N/A [
    [ ] Track:0, id=1/8219, mimeType=application/cea-608, supported=YES
  ]
]

**Comment by icbaker** [comment]
The "unknown" 608 subtitle track you're seeing is always added if the HLS playlist contains TS content and doesn't specify `CLOSED-CAPTIONS=NONE` in the `EXT-X-STREAM-INF` tag.

`CLOSED-CAPTIONS` is an optional HLS attribute: https://tools.ietf.org/html/draft-pantos-http-live-streaming-23#section-4.3.4.2

There's more info about why ExoPlayer conservatively assumes TS streams have a subtitle track in https://github.com/google/ExoPlayer/issues/8130#issuecomment-719027183.

For your own HLS streams you can resolve this by either changing the manifest, or forcing `exposeCea608WhenMissingDeclarations` to false as described in https://github.com/google/ExoPlayer/issues/8130#issuecomment-718687961.
