### ISSUE TITLE
Specific MPEG-TS video, getDuration returns TIME_UNSET

### ISSUE THREAD

**Issue by moneytoo** [google/ExoPlayer#8571]
When I play [LG Demo DolbyVision Trailer](https://drive.google.com/open?id=0BwxFVkl63-lEWmNWcGl4eVRWS2M) (from [kodi.wiki samples](https://kodi.wiki/view/Samples)), `SimpleExoPlayer.getDuration()` returns `C.TIME_UNSET`. This causes PlayerView to show video duration as 00:00 and prevents scrubbing.

Even though the filename ends with `.mkv`, it's a MPEG-TS container. (The same video is also shared [elsewhere](https://4kmedia.org/lg-dolby-vision-uhd-4k-demo/), with the correct extension.)

Player using platform `MediaPlayer` reports the correct duration (of ~ 1 min 20 s).

- ExoPlayer version number: 2.13.0
- Android version: 10
- Android device: OnePlus 7

BTW: The _Files by Google_ app also reports incorrect duration (of -2562047:47:17).

**Comment by kim-vde** [comment]
To be more efficient, ExoPlayer does not parse the whole media file before starting media. Instead, to compute the duration, it scans the last bytes of the media to get the last PCR value, then it scans the first bytes to have the first PCR value and finally it computes the duration based on the difference between the last and first PCR values (see [TsDurationReader.java](https://github.com/google/ExoPlayer/blob/dev-v2/library/extractor/src/main/java/com/google/android/exoplayer2/extractor/ts/TsDurationReader.java)).  Also for performance reasons, the number of bytes to scan at the start and end of the file is limited and, if one of the PCR values was not found, the duration is set to `C.TIME_UNSET`.

That's what's happening in your case. To prevent that, you can set the maximum number of bytes to search by [customizing the extractors factory](https://exoplayer.dev/customization.html#customizing-extractor-flags) and setting the desired value for [`DefaultExtractorsFactory.setTsExtractorTimestampSearchBytes()`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/extractor/DefaultExtractorsFactory.html#setTsExtractorTimestampSearchBytes(int)) (the value 1500 * `TsExtractor.TS_PACKET_SIZE` = 282000 works for the content you provided for example).

**Comment by moneytoo** [comment]
Thank you for your detailed and exhausting answer. Suggested solution works.
