### ISSUE TITLE
How to set 2 or more download manager Requirements

### ISSUE THREAD

**Issue by AnandSaran** [google/ExoPlayer#8573]
I want to set Requirements.NETWORK and Requirements.DEVICE_STORAGE_NOT_LOW to the DownloadManager

But   downloadManager.setRequirements () accepting only one  Requirements.
Can any one tell me how add  2 or more download manager Requirements?

**Comment by marcbaechinger** [comment]
`Requirements.NETWORK` and `Requirements.DEVICE_STORAGE_NOT_LOW` are flags of type [`RequirementFlags`](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/scheduler/Requirements.java#L40). 

```
@Documented 
@Retention(RetentionPolicy.SOURCE)
@IntDef(
    flag = true,
    value = {NETWORK, NETWORK_UNMETERED, DEVICE_IDLE, DEVICE_CHARGING, DEVICE_STORAGE_NOT_LOW})
public @interface RequirementFlags {}
```

The `@IntDef` has the attribute `flag = true`, this means that you can combine them with a bitwise AND operation or an addition.

```
Requirements requirements = 
    new Requirements(Requirements.NETWORK & Requirements.DEVICE_STORAGE_NOT_LOW)
downloadManager.setRequirements(requirements);
```

All the `isXyz` methods of the `Requirements` class like [`isNetworkRequired()`](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/scheduler/Requirements.java#L95) will check the given value with a bitwise and operation to figure out whether you have requested the given requirements.

**Comment by ojw28** [comment]
Don't flags need combining with a bitwise OR operation, rather than AND? I.e.,
```
Requirements.NETWORK | Requirements.DEVICE_STORAGE_NOT_LOW
```
