### ISSUE TITLE
Use _only_ the media extractor.

### ISSUE THREAD

**Issue by vshivam** [google/ExoPlayer#8575]
Is it possible to re-use only the Mp4Extractor in place of Android's inbuilt media extractor ? My goal is to extract samples from a video file, pass them onto a decoder, the decoded output is then rendered onto a Surface. It's _like_ playing a video onto the Surface. 

I have so far used the ExoPlayer to do the above by simply providing it a MediaItem and a Surface. It seems to work great and handles an issue where Android's Media extractor crashes. 

However, since I don't really need to play the video, I would like to simply use ExoPlayer's extractor to extract the samples from the file and feed it to my own MediaCodec instance. Is that a possibility ?

**Comment by kim-vde** [comment]
What you could do is to use a `SimpleExoPlayer` with a custom `Renderer`. You could then directly use the samples passed to the renderer. That's what we did to implement the [Transformer](https://github.com/google/ExoPlayer/tree/release-v2/library/transformer) library. You should have a look at the following classes: [Transformer.java](https://github.com/google/ExoPlayer/blob/release-v2/library/transformer/src/main/java/com/google/android/exoplayer2/transformer/Transformer.java), [TransformerVideoRender.java](https://github.com/google/ExoPlayer/blob/release-v2/library/transformer/src/main/java/com/google/android/exoplayer2/transformer/TransformerVideoRenderer.java), [TransformerAudioRenderer.java](https://github.com/google/ExoPlayer/blob/release-v2/library/transformer/src/main/java/com/google/android/exoplayer2/transformer/TransformerVideoRenderer.java) and [TransformerBaseRenderer.java](https://github.com/google/ExoPlayer/blob/release-v2/library/transformer/src/main/java/com/google/android/exoplayer2/transformer/TransformerBaseRenderer.java).
