### ISSUE TITLE
com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException

### ISSUE THREAD

**Issue by asvoxl** [google/ExoPlayer#8578]
Hello Guys,

I'm getting this error in exoplayer while playing videos in recycler view or pager like TikTok. This issue is random it comes in a very rare case, not all the time I'm getting this error.

`com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.Exynos.avc.dec, Format(1, null, null, video/avc, null, -1, null, [960, 720, 15.516247], [-1, -1])`

Please help me out if anybody has faced this issue or has an idea about this.

Thank you.

**Comment by kim-vde** [comment]
Can you try the potential solutions given in https://github.com/google/ExoPlayer/issues/6556#issuecomment-545003963 and see if it helps?

**Comment by kim-vde** [comment]
Can you provide:
- The whole stack trace (and more particularly the error code).
- The device on which you had this issue.
Thanks
