### ISSUE TITLE
Replace support library classes with androidx, to allow jetifier to be removed.

### ISSUE THREAD

**Issue by apkelly** [google/ExoPlayer#8580]
### [REQUIRED] Use case description
Exoplayer still ships with Android support library references. I'd like a version that doesn't have these classes so that I can remove jetifier from my project and therefore reduce build times.

WARNING: [Processor] Library '/Users/andy/.gradle/caches/modules-2/files-2.1/com.google.android.exoplayer/exoplayer-ui/2.12.2/f12f560645024231ee5dc11f86a18098c268b1a2/exoplayer-ui-2.12.2.aar' contains references to both AndroidX and old support library. This seems like the library is partially migrated. Jetifier will try to rewrite the library anyway.
 Example of androidX reference: 'androidx/core/app/NotificationCompat$Builder'
 Example of support library reference: 'android/support/v4/media/session/MediaSessionCompat$Token'

### Proposed solution
Replace support library versions of classes with androidx versions.

### Alternatives considered
No alternative, other than just keep using jetifier.

**Comment by andrewlewis** [comment]
According to https://developer.android.com/jetpack/androidx/migrate/class-mappings, `android.support.v4.media.session.MediaSessionCompat` did not get a new class name in AndroidX (probably because of compatibility requirements for cross-process communication for media sessions). I am checking with the Jetifier team and will post back here if/when we get more information.

**Comment by andrewlewis** [comment]
The jetifier owner said this warning is expected for apps that are completely migrated but run jetifier on code that references `android.support` still (like is the case for `MediaSessionCompat` as I mentioned in the previous comment). So unless there are other non-migrated support libraries in there you can ignore the warning.
