### ISSUE TITLE
ExoPlayer FFmpeg extension Build doc update

### ISSUE THREAD

**Issue by Nodrex** [google/ExoPlayer#8581]
In build doc (https://github.com/google/ExoPlayer/tree/release-v2/extensions/ffmpeg)
there is written that supported NDK is r20, as I know this version of NDk is deprecated, because there is r22 already.
So is this doc outdated and needs a refresh or we need to downgrade to deprecated r20  NDK to build FFmpeg extension ?

**Comment by kim-vde** [comment]
Thanks for reporting this.

Android NDK r20 is indeed [deprecated](https://developer.android.com/ndk/downloads/older_releases). I tested the extensions with r22 and it seems to be working. I will update the documentation.

**Comment by Tolriq** [comment]
@kim-vde NDK 21 is the LTS version and should be used. NDK 22 have possible big size regressions and should be full tested against that.

**Comment by kim-vde** [comment]
Yes, you are right. It is better to use the latest LTS version because it is supported for longer (I don't know about the regressions in r22). I updated the guidelines.
