### ISSUE TITLE
In HLS, some URLs don't work on Exo but work just fine with VLC and MX player

### ISSUE THREAD

**Issue by sam-m3** [google/ExoPlayer#8587]
I am a newbie in Exo and HLS at all, but I have been given a task to create a streaming app; I used Exoplayer and faced some issues with some audio types and managed to solve it using ffmpeg extension.
My second biggest problem is that some channels output data in EvenLogger and nothing seems to be wrong, but it has no audio or video output. 
Here is an EventLog of a channel that works fine, and one that has the problem:
That Channel works fine:-

> EventLogger: videoEnabled [eventTime=0.85, mediaPos=10.08, window=0, period=0]
EventLogger: audioEnabled [eventTime=0.85, mediaPos=10.08, window=0, period=0]
EventLogger: tracks [eventTime=0.85, mediaPos=10.08, window=0, period=0
EventLogger:   FfmpegVideoRenderer []
EventLogger:   MediaCodecVideoRenderer [
EventLogger:     Group:0, adaptive_supported=N/A [
EventLogger:       [X] Track:0, id=0, mimeType=video/hevc, bitrate=1740000, codecs=hvc1.1.6.L153, res=1920x1080, fps=50.0, supported=YES
EventLogger:     ]
EventLogger:     Metadata [
EventLogger:       HlsTrackMetadataEntry
EventLogger:     ]
EventLogger:   ]
EventLogger:   FfmpegAudioRenderer [
EventLogger:     Group:0, adaptive_supported=N/A [
EventLogger:       [X] Track:0, id=34/4, mimeType=audio/mpeg-L2, channels=2, sample_rate=48000, supported=YES
EventLogger:     ]
EventLogger:   ]
EventLogger:   MediaCodecAudioRenderer []
EventLogger:   TextRenderer []
EventLogger:   MetadataRenderer [
EventLogger:     Group:0, adaptive_supported=N/A [
EventLogger:       [X] Track:0, id=null, mimeType=application/id3, supported=YES
EventLogger:     ]
EventLogger:   ]

And That one has the problem: 

> EventLogger: videoEnabled [eventTime=0.99, mediaPos=10.24, window=0, period=0]
EventLogger: audioEnabled [eventTime=0.99, mediaPos=10.24, window=0, period=0]
EventLogger: tracks [eventTime=0.99, mediaPos=10.24, window=0, period=0
EventLogger:   FfmpegVideoRenderer []
EventLogger:   MediaCodecVideoRenderer [
EventLogger:     Group:0, adaptive_supported=N/A [
EventLogger:       [X] Track:0, id=0, mimeType=video/avc, bitrate=7750000, codecs=avc1.640028, res=1920x1080, fps=25.0, supported=YES
EventLogger:     ]
EventLogger:     Metadata [
EventLogger:       HlsTrackMetadataEntry
EventLogger:     ]
EventLogger:   ]
EventLogger:   FfmpegAudioRenderer [
EventLogger:     Group:0, adaptive_supported=N/A [
EventLogger:       [X] Track:0, id=1/4, mimeType=audio/mpeg-L2, channels=2, sample_rate=48000, language=pl, supported=YES
EventLogger:     ]
EventLogger:   ]
EventLogger:   MediaCodecAudioRenderer []
EventLogger:   TextRenderer [
EventLogger:     Group:0, adaptive_supported=N/A [
EventLogger:       [ ] Track:0, id=1/8219, mimeType=application/cea-608, supported=YES
EventLogger:     ]
EventLogger:     Group:1, adaptive_supported=N/A [
EventLogger:       [ ] Track:0, id=subs:pol t1, mimeType=text/vtt, language=pl, label=pol t1, supported=YES
EventLogger:     ]
EventLogger:     Group:2, adaptive_supported=N/A [
EventLogger:       [ ] Track:0, id=subs:pol t2, mimeType=text/vtt, language=pl, label=pol t2, supported=YES
EventLogger:     ]
EventLogger:   ]
EventLogger:   MetadataRenderer [
EventLogger:     Group:0, adaptive_supported=N/A [
EventLogger:       [X] Track:0, id=null, mimeType=application/id3, supported=YES
EventLogger:     ]
EventLogger:   ]

In addition, When I used vlc to play the non working channels, I observed the codec informations, I compared it to a working channel and the result was like that:

2 examples of Working channels:
> Codec: H264-MPEG-AVC(part 10) (avc1)
Type: Video
Video resolution: 1280*720
Buffer dimensions: 1280*738
Frame rate: 29.97000
Decoded format: Planar 4:2:0 YUV
Orientation: Top left
Chroma location: Left

> Codec: H264-MPEG-AVC(part 10) (hevc)
Type: Video
Video resolution: 1920*1080
Buffer dimensions: 1920*1088
Frame rate: 50
Decoded format: Planar 4:2:0 YUV full scale
Orientation: Top left
Color primaries: ITU-R BT.601 (525 lines, 60 Hz)
Color transfer function: ITU-R BT.709
Color space: ITU-R BT.601 Range

Non-Working channel:
> Codec: H264-MPEG-AVC(part 10) (h264)
Type: Video
Video resolution: 1920*1080
Buffer dimensions: 1920*1080
Frame rate: 25
Decoded format: Planar 4:2:0 YUV
Orientation: Top left
Color primaries: ITU-R BT.709
Color transfer function: ITU-R BT.709
Color space: ITU-R BT.709 Range
Chroma location: Left

I tried using av1 and vp9 extensions, but when I was setting my PlayerView's `surface_type` to `video_decoder_gl_surface_view`, the screen would just turn black and the non working channels still had no audio or video output.

Is there any way to solve this issue?!

*EDIT*
I have also tried exo demo app with enabling extensions, and it gives the same result.

**Comment by sam-m3** [comment]
It is strange but I managed to solve that issue right after submitting the issue.
But as usual, other issues occured, now these channels are working fine on some devices, but on my emulator and some other devices, they only load one frame and after that it freezes.

I also checked #2939 but it didn't help.

Any recommendations?

*EDIT*
For those who faced the same issue and didn't manage to find the solution.
I created An extractor factory like that, and passed it to the media source.

`val extractorFactory = DefaultHlsExtractorFactory(DefaultTsPayloadReaderFactory.FLAG_ALLOW_NON_IDR_KEYFRAMES, true)`

`HlsMediaSource.Factory(dataSourceFactory).setExtractorFactory(extractorFactory)`

**Comment by christosts** [comment]
Hi,

I am assuming you are still testing with the ExoPlayer demo app in your second comment, right? In this case, we would need a link to the channel stream to inspect the stream. If you cannot share the link publicly, please send it via email at dev.exoplayer@gmail.com using the subject "Issue #8587". Please also update this issue to indicate you've done this.

**Comment by someq** [comment]
Hello! Same issue here.

Emailed you examples of working and freezing streams.

Reproduced in [tutorial app](https://developer.android.com/codelabs/exoplayer-intro#2) with replaced uri in PlayerActivity:

```java
  private void initializePlayer() {
    player = new SimpleExoPlayer.Builder(this).build();
    playerView.setPlayer(player);
    // provided examples of working and non-working streams in email
    MediaItem mediaItem = MediaItem.fromUri("http://my_stream_uri.m3u8");
    player.setMediaItem(mediaItem);
    player.setPlayWhenReady(playWhenReady);
    player.seekTo(currentWindow, playbackPosition);
    player.prepare();
  }
```
  
and following dependencies in player-lib build.gradle:

```gradle
dependencies {
    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'com.google.android.exoplayer:exoplayer-core:2.13.1'
    implementation 'com.google.android.exoplayer:exoplayer-hls:2.13.1'
    implementation 'com.google.android.exoplayer:exoplayer-ui:2.13.1'
}
```

Also tried with exoplayer 2.12.0.

Starting both streams produces log:

```
I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
D/MediaCodecInfo: NoSupport [codec.profileLevel, avc1.64001E, video/avc] [OMX.google.h264.decoder, video/avc] [generic_x86, Android SDK built for x86, Google, 25]
    NoSupport [codec.profileLevel, avc1.64001E, video/avc] [OMX.google.h264.decoder, video/avc] [generic_x86, Android SDK built for x86, Google, 25]
I/OMXClient: MuxOMX ctor
I/MediaCodec: [OMX.google.h264.decoder] setting surface generation to 8593409
E/ACodec: [OMX.google.h264.decoder] storeMetaDataInBuffers failed w/ err -1010
I/ACodec: codec does not support config priority (err -1010)
I/OMXClient: MuxOMX ctor
I/ACodec: codec does not support config priority (err -2147483648)
I/ACodec: codec does not support config operating rate (err -2147483648)
D/MediaCodec: [OMX.google.h264.decoder] setting dataspace on output surface to #102
D/: HostConnection::get() New Host Connection established 0x91d8fac0, tid 8416
D/SoftwareRenderer: setting dataspace on output surface to #102
```

It has some errors but I assume they do not cause the problem, as one stream works normally after them, and other - does not.

Sometimes following lines appear, then freezing stream shows black screen, otherwise - first frame of the video:

```
D/AudioTrack: Client defaulted notificationFrames to 6000 for frameCount 12000
E/DefaultAudioSink: Discontinuity detected [expected 0, got -389542667]
```

Stream can't be started, on play/pause taps controls change but video does not play. Video progress indicator can be scrubbed to another frame, and it appears on screen, but still not playing.

Also, if it helps: at first Issue appeared in my Flutter app, but I reproduced it in a native app to exclude Flutter layer. Both streams were working fine at Tuesday 2021-Feb-09 (and probably until Friday Feb 12) and then one stopped working. No code in app or API changed since then, just time passed.

**Comment by someq** [comment]
UPD:
Setting flags `FLAG_ALLOW_NON_IDR_KEYFRAMES` and `FLAG_DETECT_ACCESS_UNITS` did not help.

Set them like this:

```java
public class PlayerActivity extends AppCompatActivity {
  ...

  private HlsDataSourceFactory dataSourceFactory;

  @Override
  protected void onCreate(Bundle savedInstanceState) {
    ...

    dataSourceFactory = new DefaultHlsDataSourceFactory(new DefaultDataSourceFactory(this));
  }

  private void initializePlayer() {
    int flags = DefaultTsPayloadReaderFactory.FLAG_ALLOW_NON_IDR_KEYFRAMES
            | DefaultTsPayloadReaderFactory.FLAG_DETECT_ACCESS_UNITS;
    HlsExtractorFactory extractorFactory = new DefaultHlsExtractorFactory(flags, true);
    HlsMediaSource.Factory sourceFactory = new HlsMediaSource
            .Factory(dataSourceFactory)
            .setExtractorFactory(extractorFactory);

    player = new SimpleExoPlayer.Builder(this)
            .setMediaSourceFactory(sourceFactory)
            .build();
    playerView.setPlayer(player);

    String uri = "<my_hls_uri>";  // provided in email
    player.setMediaItem(MediaItem.fromUri(uri));
    player.setPlayWhenReady(playWhenReady);
    player.seekTo(currentWindow, playbackPosition);
    player.prepare();
  }

  ...
}
```

**Comment by someq** [comment]
UPD:
Restarted ffmpeg encoder after ~60-70 hrs uptime and it worked. Still not clear, what happened to the stream after that uptime, but it's not an ExoPlayer issue anymore.

**Comment by sam-m3** [comment]
Hello @someq 
Same happened with me; I observed that this only happens on my emulator, when I use the app on an android box or mobile, or any other real device, It works just fine.

Thanks @christosts for your reply, But as I mentioned This only happens on the emulator, So as long as my videos work on real devices, That is not a problem.

*Closing the issue*
