### ISSUE TITLE
No audio output, but vlc work well.

### ISSUE THREAD

**Issue by SmallYuuu** [google/ExoPlayer#8591]
Xiaomi Pad 4 Android O
com.google.android.exoplayer:exoplayer:2.13.1

This is my test url:
http://101.71.255.229:6610/zjhs/2/10067/index.m3u8?virtualDomain=zjhs.live_hls.zte.com&IASHttpSessionId=OTT3347520210215122103231147

Exoplayer can not output the audio when play this M3U8(video works well). And I also test VLC, it is no problem.

I find out the stream format. What should I do to play with audio?

<img width="552" alt="屏幕快照 2021-02-16 下午3 19 54" src="https://user-images.githubusercontent.com/10010149/108030584-74999a80-706a-11eb-9717-466302d4251c.png">

**Comment by SmallYuuu** [comment]
It seem like MPEG Audio layer1/2 not support？

**Comment by christosts** [comment]
To play this audio format, please try out the ffmpeg extension. [Here are the instructions](https://github.com/google/ExoPlayer/blob/r2.13.0/extensions/ffmpeg/README.md) how to use it. Also, make sure to specify the `mp3` decoder when building the native ffmpeg library.

Closing this issue for now, feel free to re-open if using ffmpeg did not work.
