### ISSUE TITLE
MPEG DASH SGAI Ad Support

### ISSUE THREAD

**Issue by ronak2121** [google/ExoPlayer#8595]
When filing a feature request:
-----------------------
Replace the content in the sections below.

### [REQUIRED] Use case description
MPEG DASH is closing in on support for a new Ad Delivery Architecture called Server Guided Ad Insertion: https://dashif.org/docs/CR-Ad-Insertion-r8.pdf.

We are thinking of taking advantage of SGAI to drive ads from the server side, while providing a more dynamic ad experience to our users.

### Proposed solution
Implement Server Guided Ad Insertion support in Exoplayer so more of the Ad Injection is handled server side, instead of clients knowing when to reload VAST files.

### Alternatives considered
Using CSAI support in Exoplayer, and having AdsMediaSource reload the VAST file on seek operations.

**Comment by christosts** [comment]
@ojw28 will you be able to look at the proposed enhancement?

**Comment by ronak2121** [comment]
FYI I've learned much more about the upcoming SGAI specification from DASH-IF:

There's really two parts:

1. XLinks used to resolve ads for VOD usecases. And using xlink:actuate="onRequest" to delay ad resolution up to the latest point you can.
2. Patch Manifests for the live use case.

We are really looking for support for the first usecase here, and I saw this: https://github.com/google/ExoPlayer/issues/1574 that Exoplayer does not support xlinks. I have a series of questions out to DASH-IF: https://github.com/Dash-Industry-Forum/AdInsertion/issues/83 to learn more about what this does to the VOD player timeline and more.

**Comment by ronak2121** [comment]
@ojw28 just want to make sure this is on your radar for a future version of Exoplayer. Would it be reasonable to expect Dash SGAI support to be available by end of this year?

**Comment by ronak2121** [comment]
Not sure if you can help answer my question above @christosts ?

**Comment by ronak2121** [comment]
Hi @ojw28 or @christosts is there any update on this?

**Comment by ronak2121** [comment]
Hi @ojw28 or @christosts is there any update?

**Comment by tonihei** [comment]
From the player's perspective, this is mainly the same as #1574, which tracks support for xlinks and publishing the correct ad metadata in the player. So I'd just duplicate to the other issue. If you think this isn't correct and this is tracking something else, please let us know.

**Comment by ronak2121** [comment]
My use case is VOD so supporting DASH Patch Manifests is outside of my scope, but you will have to support that if you truly wish to support the entirety of the DASG SGAI speecification.

**Comment by tonihei** [comment]
The SGAI proposal you linked above is mainly talking about xlink patch manifests as the way to implement this. Could you clarify what feature you are asking for exactly if it's not that?

**Comment by ronak2121** [comment]
This ticket is asking for the entirety of SGAI. Which includes delayed xlink resolution for VOD and patch manifests to cover the live use case.

**Comment by tonihei** [comment]
I think this should be covered by #1574 once we implement it, because it's about when and how to load xlinks. So I'll leave this issue closed.
