### ISSUE TITLE
How to set subtitles bottom padding? Now subtitles show on screen very bottom.

### ISSUE THREAD

**Issue by sergju** [google/ExoPlayer#8598]
How to set subtitles bottom padding? Now subtitles show on screen very bottom.
But I need to show it on some offset from bottom

**Comment by icbaker** [comment]
If your subtitle content doesn't specify the vertical position of the subtitles and you're using ExoPlayer's UI components then you can use [`SubtitleView#setBottomPaddingFraction`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/ui/SubtitleView.html#setBottomPaddingFraction(float)). This doesn't work if the subtitles already specify a vertical position.

Note that in WebVTT (and probably others) the **standard** specifies a vertical position for every cue even if your .vtt file doesn't. So for WebVTT content the `setBottomPaddingFraction` method never has an effect. More details: https://github.com/google/ExoPlayer/issues/7934#issuecomment-694063859
