### ISSUE TITLE
Player Crashes on HTC one V Android version:4.0.3  because of java.lang.VerifyError

### ISSUE THREAD

**Issue by aren13** [google/ExoPlayer#86]
ExoPlayer crashes when try to initialize EventLogger. 

java.lang.VerifyError: exoPlayer/full/EventLogger
&nbsp;&nbsp;&nbsp;&nbsp;at exoPlayer.full.FullPlayerActivity.preparePlayer(FullPlayerActivity.java:213)
&nbsp;&nbsp;&nbsp;&nbsp;at exoPlayer.full.FullPlayerActivity.onResume(FullPlayerActivity.java:151)

Implementation is as same as in demo project.

**Comment by zayass** [comment]
so minSdk 9 in library https://github.com/google/ExoPlayer/blob/master/library/build.gradle project is mistake?

> There's no way to support API level 14

sad api 8-15 take more then 14% market share as I see here https://developer.android.com/about/dashboards/index.html and around 9.5% in our project

**Comment by ojw28** [comment]
It's not a mistake. See: https://github.com/google/ExoPlayer/blob/master/library/src/main/AndroidManifest.xml#L26
I guess we should add that comment to the gradle file too.
