### ISSUE TITLE
ExoPlayer does not support FLV

### ISSUE THREAD

**Issue by ehoodkatz** [google/ExoPlayer#860]
Hello,

I am learning ExoPlayer in order to replace it with the current player in my app. I am using the demo app as the client to play the videos currently being served to my app. However when I try to play these videos the following exception is thrown:

10-11 12:26:39.634 25447-9657/com.google.android.exoplayer.demo E/ExoPlayerImplInternal: Internal track renderer error.
10-11 12:26:39.634 25447-9657/com.google.android.exoplayer.demo E/ExoPlayerImplInternal: com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.extractor.ExtractorSampleSource$UnrecognizedInputFormatException: None of the available extractors (WebmExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, TsExtractor) could read the stream.
10-11 12:26:39.634 25447-9657/com.google.android.exoplayer.demo E/ExoPlayerImplInternal:     at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:154)
10-11 12:26:39.634 25447-9657/com.google.android.exoplayer.demo E/ExoPlayerImplInternal:     at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:145)
10-11 12:26:39.634 25447-9657/com.google.android.exoplayer.demo E/ExoPlayerImplInternal:     at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(ExoPlayerImplInternal.java:283)
10-11 12:26:39.634 25447-9657/com.google.android.exoplayer.demo E/ExoPlayerImplInternal:     at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:205)
10-11 12:26:39.634 25447-9657/com.google.android.exoplayer.demo E/ExoPlayerImplInternal:     at android.os.Handler.dispatchMessage(Handler.java:95)
10-11 12:26:39.634 25447-9657/com.google.android.exoplayer.demo E/ExoPlayerImplInternal:     at android.os.Looper.loop(Looper.java:176)
10-11 12:26:39.634 25447-9657/com.google.android.exoplayer.demo E/ExoPlayerImplInternal:     at android.os.HandlerThread.run(HandlerThread.java:61)
10-11 12:26:39.634 25447-9657/com.google.android.exoplayer.demo E/ExoPlayerImplInternal:     at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
10-11 12:26:39.634 25447-9657/com.google.android.exoplayer.demo E/ExoPlayerImplInternal:  Caused by: com.google.android.exoplayer.extractor.ExtractorSampleSource$UnrecognizedInputFormatException: None of the available extractors (WebmExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, TsExtractor) could read the stream.
10-11 12:26:39.634 25447-9657/com.google.android.exoplayer.demo E/ExoPlayerImplInternal:     at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractorHolder.selectExtractor(ExtractorSampleSource.java:807)
10-11 12:26:39.634 25447-9657/com.google.android.exoplayer.demo E/ExoPlayerImplInternal:     at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:738)
10-11 12:26:39.634 25447-9657/com.google.android.exoplayer.demo E/ExoPlayerImplInternal:     at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
10-11 12:26:39.634 25447-9657/com.google.android.exoplayer.demo E/ExoPlayerImplInternal:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
10-11 12:26:39.634 25447-9657/com.google.android.exoplayer.demo E/ExoPlayerImplInternal:     at java.util.concurrent.FutureTask.run(FutureTask.java:234)
10-11 12:26:39.634 25447-9657/com.google.android.exoplayer.demo E/ExoPlayerImplInternal:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
10-11 12:26:39.634 25447-9657/com.google.android.exoplayer.demo E/ExoPlayerImplInternal:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
10-11 12:26:39.634 25447-9657/com.google.android.exoplayer.demo E/ExoPlayerImplInternal:     at java.lang.Thread.run(Thread.java:841)

10-11 12:26:39.639 25447-25447/com.google.android.exoplayer.demo E/EventLogger: playerFailed [1.63]
10-11 12:26:39.639 25447-25447/com.google.android.exoplayer.demo E/EventLogger: com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.extractor.ExtractorSampleSource$UnrecognizedInputFormatException: None of the available extractors (WebmExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, TsExtractor) could read the stream.
10-11 12:26:39.639 25447-25447/com.google.android.exoplayer.demo E/EventLogger:     at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:154)
10-11 12:26:39.639 25447-25447/com.google.android.exoplayer.demo E/EventLogger:     at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:145)
10-11 12:26:39.639 25447-25447/com.google.android.exoplayer.demo E/EventLogger:     at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(ExoPlayerImplInternal.java:283)
10-11 12:26:39.639 25447-25447/com.google.android.exoplayer.demo E/EventLogger:     at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:205)
10-11 12:26:39.639 25447-25447/com.google.android.exoplayer.demo E/EventLogger:     at android.os.Handler.dispatchMessage(Handler.java:95)
10-11 12:26:39.639 25447-25447/com.google.android.exoplayer.demo E/EventLogger:     at android.os.Looper.loop(Looper.java:176)
10-11 12:26:39.639 25447-25447/com.google.android.exoplayer.demo E/EventLogger:     at android.os.HandlerThread.run(HandlerThread.java:61)
10-11 12:26:39.639 25447-25447/com.google.android.exoplayer.demo E/EventLogger:     at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
10-11 12:26:39.639 25447-25447/com.google.android.exoplayer.demo E/EventLogger:  Caused by: com.google.android.exoplayer.extractor.ExtractorSampleSource$UnrecognizedInputFormatException: None of the available extractors (WebmExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, TsExtractor) could read the stream.
10-11 12:26:39.639 25447-25447/com.google.android.exoplayer.demo E/EventLogger:     at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractorHolder.selectExtractor(ExtractorSampleSource.java:807)
10-11 12:26:39.639 25447-25447/com.google.android.exoplayer.demo E/EventLogger:     at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:738)
10-11 12:26:39.639 25447-25447/com.google.android.exoplayer.demo E/EventLogger:     at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
10-11 12:26:39.639 25447-25447/com.google.android.exoplayer.demo E/EventLogger:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
10-11 12:26:39.639 25447-25447/com.google.android.exoplayer.demo E/EventLogger:     at java.util.concurrent.FutureTask.run(FutureTask.java:234)
10-11 12:26:39.639 25447-25447/com.google.android.exoplayer.demo E/EventLogger:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
10-11 12:26:39.639 25447-25447/com.google.android.exoplayer.demo E/EventLogger:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
10-11 12:26:39.639 25447-25447/com.google.android.exoplayer.demo E/EventLogger:     at java.lang.Thread.run(Thread.java:841)

The peculliar thing is that the videos I am trying to play work with other players but not ExoPlayer. I looked at other issues that reported a similar issue but I was not able to use the insights in them to solve the problem. 

The version of the demo app that I am using is from the master branch with last commit 0c060f429f459f1bac2ffa0963cadc45ce35b73a.

The file I am trying to play can be found in the following link:
http://5c856ba6cc9ed2fe2e9a-6e12211e6bcd3a3454f29c48581571ff.r59.stream.cf5.rackcdn.com/69c0f207-6c65-e511-80cd-fcaa14926e72_c624d65a-1566-e511-80cd-fcaa14926e72_87356fac-4302-e511-afdd-d0509926ddf2_android_28092015103324_986806128.mp4

I would appreciate any help.

Thank you in advance,
Ehood Katz

**Comment by ojw28** [comment]
Despite the mp4 file extension, this is actually an FLV video file. We don't currently support FLV. It does sort of work if you patch in this change, which adds FLV support: https://github.com/google/ExoPlayer/pull/828. We're yet to decide whether we want to support FLV officially. Note that even with this change, you cannot seek and the player gets stuck in the buffering state at the end of the content (see below).

A couple of questions:
- If you control the media, why are you using FLV? Can you use MP4 instead? I don't think Android officially supports FLV for the built in MediaPlayer. I don't think iOS supports FLV either, although I could be wrong.
- There seems to be something weird/broken with the server. It claims the media is ~2GB long and then prematurely closes the connection at 84MB. For example if I try and fetch the media with curl, I get:

```
curl http://5c856ba6cc9ed2fe2e9a-6e12211e6bcd3a3454f29c48581571ff.r59.stream.cf5.rackcdn.com/69c0f207-6c65-e511-80cd-fcaa14926e72_c624d65a-1566-e511-80cd-fcaa14926e72_87356fac-4302-e511-afdd-d0509926ddf2_android_28092015103324_986806128.mp4 > test.mp4
olly-macbookpro2:exoplayer-aosp olly$ curl http://5c856ba6cc9ed2fe2e9a-6e12211e6bcd3a3454f29c48581571ff.r59.stream.cf5.rackcdn.com/69c0f207-6c65-e511-80cd-fcaa14926e72_c624d65a-1566-e511-80cd-fcaa14926e72_87356fac-4302-e511-afdd-d0509926ddf2_android_28092015103324_986806128.mp4 > testwhat.mp4
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  4 2047M    4 84.0M    0     0   379k      0  1:32:12  0:03:47  1:28:25  410
kcurl: (18) transfer closed with 2059165544 bytes remaining to read
```

This is broken and will cause issues. It's most likely why playback gets stuck in the buffering state when you patch in FLV support (not certain about this).

**Comment by ehoodkatz** [comment]
Thank you for the quick reply and the useful information. I would also like
to know what you used out that the file is in FLV format and not MP4, if
possible, so in the future I will know first to check the file file format.

Respectfully,
Ehood Katz

**Comment by ojw28** [comment]
I used [this tool](https://mediaarea.net/en/MediaInfo/Download). This is by no means an endorsement, but it did the job in this case!

**Comment by ojw28** [comment]
FLV is now supported, although without seeking support currently. FLV doesn't actually contain a media index to make seeking easy, so it's unclear whether we'll ever support it. Closing the issue for now. @jeoliva can comment on whether it makes sense to add seeking support at some point, or not.

**Comment by trungptdhcn** [comment]
I pull  #828, I still play video with flv sample, However when I try to play flv videos the following exception is thrown:
![untitled](https://cloud.githubusercontent.com/assets/2919735/11490571/6b28a748-980c-11e5-957f-463acd47b344.png)
I need any help! Thank you in advance
Jodie Pham!

**Comment by Sabinmon** [comment]
hi,
Same happens for me. Any help??

**Comment by ojw28** [comment]
Please file a separate issue, with all of the information listed [here](https://google.github.io/ExoPlayer/2015/10/01/reporting-issues.html) including a link to sample media. Most likely the media you're attempting to play is not supported by Android/ExoPlayer.

**Comment by arjuntu** [comment]
ok, i will do that. thank u.

**Comment by v4ekmarev** [comment]
@trungptdhcn you solved an issue?
