### ISSUE TITLE
Is there a way to discard an ongoing chunk download and download lower bitrate chunk when it takes long time to download?

### ISSUE THREAD

**Issue by tanhan** [google/ExoPlayer#8604]
Hi,

As you can see from Charles trace below, it takes 30 seconds to download 6 Mbit chunk when network speeds decrease dramatically. Is there a way to discard an ongoing chunk download when it takes long time to download and make the player to download lower bitrate chunks?

<img width="1813" alt="Screen Shot 2021-02-18 at 15 07 00" src="https://user-images.githubusercontent.com/2428616/108355010-47c8bd00-71fb-11eb-82be-7e8ab775d506.png">

**Comment by kpandroid** [comment]
+1 very interested in such feature. Like ABR hls.js does
https://github.com/video-dev/hls.js/blob/master/src/controller/abr-controller.ts#L200

**Comment by tonihei** [comment]
Yes, you can overwrite `TrackSelection.shouldCancelChunkLoad` (e.g. by extending `AdaptiveTrackSelection`) to trigger a cancellation of the current chunk load.

**Comment by tonihei** [comment]
Closing because the question was answered.

**Comment by tanhan** [comment]
Thanks 👍
