### ISSUE TITLE
Offline DRM : Is it possible to set a new DRM rather than renew the current ?

### ISSUE THREAD

**Issue by ghost** [google/ExoPlayer#8606]
Hi, I'm using ExoPlayer in my application and I want to add offline mode.

I encounter an issue with the DRM provider I use because he doesn't allow DRM renewal. 

Currently I use the Exoplayer sample app model to do my tests.

I create a DownloadHelper with my media information and use the OfflineLicenseHelper.downloadLicense() in onPrepared callback method to get DRM and I set it to the Download request before sending it to the Service.

It works fine and we are able to play protected video offline, but when the license is close to expiration we want to renew it.
As my DRM provider provides me non-renewable DRM I got an error when if I try to renew DRM with OfflineLicenseHelper.

Is it possible to get a new DRM License and set it to a completed download to get around the impossibility to renew it ?

**Comment by christosts** [comment]
There is a similar discussion on #8116, which however needed to store the keySetId after renewal, whereas, correct me if I'm wrong, the difference is that you need to download a new licence again. Other than that, you effectively need the new keySetId to replace the previous one in the database.

[This comment on #8116](https://github.com/google/ExoPlayer/issues/8116#issuecomment-720492638) should give you an idea who to update the Download instance on the database with the new keySetId. The question in this case is how to obtain the keySetId for a new license. You need information that is not stored in the database, at least the `drmInitData` and license URI, which are available in the DASH manifest. Therefore you need to download the dash manifest again. This [comment on #8116](https://github.com/google/ExoPlayer/issues/8116#issuecomment-717471893) can be helpful finding the this information in the manifest.

An alternative, **which I have not tested**, it to use `DownloadHelper` just as in the demo app and `prepare` it for the same video. The `DownloadHelper` should download the manifest and trigger the onPrepared callback, something that you probably have already done in your app. From there you can find the drmInitData and the license URL. In fact, I think that if you kick-off a new download at this point, the DownloadService will overwrite the existing entry in the database with the new keySetId but figure out the content is already downloaded. I repeat, I have not tried this.

Please let me know if any of the above worked for you.

**Comment by ghost** [comment]
Thanks for your answer, all these points are interesting and I will investigate them. 

For the third point I confirm that it works as you said. I test it and it works fine, but I encountered a new issue due to a limitation in our side. The Manifest url is protected with a limited duration url. So I can renew the DRM using this method during few hours, but past a day I no longer be able to download the manifest.

**Comment by christosts** [comment]
> For the third point I confirm that it works as you said. I test it and it works fine, but I encountered a new issue due to a limitation in our side. The Manifest url is protected with a limited duration url. So I can renew the DRM using this method during few hours, but past a day I no longer be able to download the manifest.

It looks like you have solved the initial problem, getting a new licence and updating the download in the database. Therefore I will close this ticket. If there's something is not working as expected with respect to the initial question, feel free to re-open this issue.
