### ISSUE TITLE
[Question] Previous button is going to the beginning of the stream instead of the previous item in the playlist

### ISSUE THREAD

**Issue by amahouachi** [google/ExoPlayer#8607]
I am using the exoplayer to play live streams in a playlist.

The previous button instead of going to the previous item in the playlist, it returns to the beginning of the stream of the current item.

This happens when I let it play the stream for few seconds then click on the previous button.
In that case, I need to click twice on the previous button to have it switch to the previous item in the playlist.

What do I need to do in order to force the previous button to ignore the current item's live window and go to the previous item in the playlist?

Thanks

**Comment by marcbaechinger** [comment]
This behaviour is defined by the `DefaultControlDispatcher`.  You can create a subclass of `DefaultControlDispatcher`, override `dispatchPrevious` and set the control dispatcher with `PlayerView.setControlDispatcher` or `StyledPlayerView.setControlDispatcher` respectively.

**Comment by amahouachi** [comment]
Works great thanks !

```kotlin
playerView.setControlDispatcher(object : DefaultControlDispatcher() {
          override fun dispatchPrevious(player: Player): Boolean {
            player.seekTo(0)
            return super.dispatchPrevious(player)
          }
        })
```
