### ISSUE TITLE
start (slow or after) a while big mkv file  and also buffering very slow as compare to other like xplayer and mxplayer why?

### ISSUE THREAD

**Issue by waqasyousafy** [google/ExoPlayer#8608]
I am playing the 3gb mkv file but it taking too much time to load the file also when i scroll horizontally to seek video it is buffering very slow . As see in mx and xplayer is my reference app they are not buffering too much . 

How can i acheive that slow  buffering and mkv file start time reduction help me ???

**Comment by christosts** [comment]
You can customize the buffering threasholds by creating your own [DefaultLoadControl](https://github.com/google/ExoPlayer/blob/r2.13.1/library/core/src/main/java/com/google/android/exoplayer2/DefaultLoadControl.java) and passing it to the player. You can set the buffering thresholds for initial minimum buffer, minimum buffer after a rebuffer, and so on.

In at least 2.13, by default, the player will attempt to buffer [2.5 seconds](https://github.com/google/ExoPlayer/blob/r2.13.1/library/core/src/main/java/com/google/android/exoplayer2/DefaultLoadControl.java#L49) before playback begins. You can try a lower value. Note that the amount of time taken to start playback depends on the bitrate of your file and not the size of the file.

If the bitrate of the file is over (or close) to the device's bandwidth throughput with the server, then reducing the buffering thresholds might increase the probability for a rebuffer.

**Comment by waqasyousafy** [comment]
what value of defaultloadcontrol should i set?

**Comment by waqasyousafy** [comment]
am trying to play another video it is playing fine in xplayer and mx player but in exo buffering and buffering , loading and loading but video not play.
i am getting this error : Decoder failed: OMX.Exynos.hevc.dec
on newly played video here is the link:
https://drive.google.com/file/d/1_WXMY2YWixBdEaDuLPdYk-IniPuBXeyw/view?usp=sharing

**Comment by christosts** [comment]
this question was also asked in #8618, we cannot respond because the authenticity of the content seems questionable.
