### ISSUE TITLE
Firebase performance plugin FileNotFoundException when updating ExoPlayer to 2.13.1

### ISSUE THREAD

**Issue by SepidehAkbarinezhad** [google/ExoPlayer#8613]
hi, I have exoplayer in my project and I decided to update it to the latest version.

 I am using these dependency  : 

    implementation 'com.google.android.exoplayer:exoplayer-core:2.13.1'
    implementation 'com.google.android.exoplayer:exoplayer-dash:2.13.1'
    implementation 'com.google.android.exoplayer:exoplayer-ui:2.13.1'
    implementation 'com.google.android.exoplayer:extension-ima:2.13.1'
    implementation 'com.google.android.exoplayer:exoplayer-hls:2.13.1'

I've been working on updating exo in a separate branch and everything was ok . but as I merged the branch with my develop branch I get these errors in build time : 

:app:transformClassesWithFirebasePerformancePluginForMyFlavourName
java.io.FileNotFoundException: C:\...\app\build\intermediates\transforms\FirebasePerformancePlugin\flavourName\debug\79\com\google\ads\interactivemedia\v3\internal\aux.class (The system cannot find the file specified)
C:\...\app\build\intermediates\transforms\FirebasePerformancePlugin\flavourName\debug\79\com\google\ads\interactivemedia\v3\internal\aux.class (The system cannot find the file specified)

*It's worth mentioning that if I change the ima dependency to the lower version , my project builds successfully ,
but it causes problems in showing ads in playlist , that's the reason I insist on updating ima to the latest version.

     implementation 'com.google.android.exoplayer:extension-ima:2.12.3'

Any assistance you can provide would be greatly appreciated

**Comment by ThisIsSadeghi** [comment]
I had a similar issue, fixed by updating the [Firebase performance plugin](https://firebase.google.com/docs/perf-mon/get-started-android#add-perfmon-plugin).

**Comment by Samrobbo** [comment]
Let us know if updating the firebase plugin, as recommended by ThisIsSadeghi, helps with your issue. Thanks!

**Comment by SepidehAkbarinezhad** [comment]
tnx to him , the solution worked for me too.
