### ISSUE TITLE
Audio track "Auto" doesn't play after switching tracks back and forth (video w/ TrueHD 7.1)

### ISSUE THREAD

**Issue by moneytoo** [google/ExoPlayer#8616]
When I play video files that include TrueHD 7.1 audio tracks, the "Auto" audio track selection (in `StyledPlayerView`) often results in no audio playback (even though all individual audio tracks play just fine).

Sample files: [matrix-sample.mkv](http://brouken.com/tmp/matrix-sample.mkv) or [Dolby Cinema demo](https://we.tl/t-k73Ong0SYN)

[Project for demonstration](https://github.com/moneytoo/ExoPlayerDemo/blob/master/app/src/main/java/com/example/exoplayer/MainActivity.java) (basically just a `StyledPlayerView` with `EXTENSION_RENDERER_MODE_ON` - ffmpeg extension compiled with all available decoders). (Without `EXTENSION_RENDERER_MODE_ON`, "Auto" works fine, as TrueHD tracks aren't made available.)

Steps to reproduce (always):

1. Open a video file in the demo app (select it from file manager)
2. Change audio track selection from "Auto" to any other track
3. Set audio track back to "Auto" 
4. Hit play - audio doesn't play

"Auto" works, if I skip steps 2 and 3. Every single audio track plays on the device (when selected manually). It's just something with the initial vs manual "Auto".

- ExoPlayer version number: 2.13.1
- Android version: 10
- Android device: OnePlus 7

Bugreport: [bugreport-OnePlus7-QKQ1.190716.003-2021-02-21-19-18-31.zip](https://github.com/google/ExoPlayer/files/6018348/bugreport-OnePlus7-QKQ1.190716.003-2021-02-21-19-18-31.zip)

I'm not noticing anything suspicious in logcat.

**Comment by ojw28** [comment]
This issue occurs because we try and read the channel count for the TrueHD stream from FFmpeg before it's known. We will provide a fix.
