### ISSUE TITLE
How to use Jetpack Compose with ExoPlayer?

### ISSUE THREAD

**Issue by okycelt** [google/ExoPlayer#8629]
Hello,

Has somebody tried to use ExoPlayer with Jetpack Compose? If so, do you have any recommendations? I've tried to post a question for today's #TheAndroidShow but didn't get a reply. The only thing I found online is people recommending to wrap `PlayerView`, `SurfaceView` or `TextureView` in an `AndroidView` composable.

Thanks in advance

**Comment by andrewlewis** [comment]
I don't think we've got any direct experience with this, but I checked with the Compose team and their guidance is to wrap in an `AndroidView` as you suggest. They just published a guide to interoperability here: https://developer.android.com/jetpack/compose/interop

**Comment by okycelt** [comment]
@andrewlewis, thanks for the confirmation. I think it might help a lot of folks in the future to have some ExoPlayer Compose sample that would showcase best practices of interaction between ExoPlayer and composables :)
