### ISSUE TITLE
m3u8视频地址慢，可以开起多线程缓存吗？直到影片全部缓存完成

### ISSUE THREAD

**Issue by jianxiaobai999** [google/ExoPlayer#8631]

**Comment by Samrobbo** [comment]
Hi,

Is it possible to give some more information? Ideally in English (don't worry if it's not perfect). 

I saw you had pasted the issue template here. What we actually need is for you to fill it in, so answer the questions it asks and provide the information it says about.

The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md).
