### ISSUE TITLE
Create TrackSelectionDialogBuilder and TrackSelectionView based on track type instead of renderer index

### ISSUE THREAD

**Issue by pvishnyakov** [google/ExoPlayer#8637]
Hi. 
Current implementation of TrackSelectionDialogBuilder and TrackSelectionView requires the exact Renderer index to be specified. 
It would be great to have an option to create the selection dialog/view based on track type like C.TRACK_TYPE_AUDIO and be able to select from all audio tracks provided by all renderers on the fly.

Why it’s needed:
If there are 2 audio renderers available at the same time, like MediaCodecAudioRenderer and FfmpegAudioRenderer (extension mode on), default dialog/view can show track selection only for one renderer at the time. Even opening 2nd renderer track selection separately I cannot switch to it using standard TrackSelection dialog/view if the media is playing, otherwise I’m getting an error (2 media renderers witch clock enabled).
2 renderers make sense because I need MediaCodec Passthrough capabilities for all audio when possible and Ffmpeg to decode the rest of audio tracks that are not supported by MediaCodec, and I’d like to choose between all possible audio tracks conveniently.

I have implemented desired behavior but I had to fork your source code of TrackSelectionDialogBuilder and TrackSelectionView because these classes are not customizable in the necessary parts.
Can you please add described functionality somewhen?
Or at least allow subclassing and modification of TrackSelectionDialogBuilder and View more freely, without source code forks.

**Comment by andrewlewis** [comment]
@krocard please could you take a look?

**Comment by krocard** [comment]
The new track selection API is renderer agnostic, tracks are selected individually based on track index and track type:
https://github.com/google/ExoPlayer/blob/a308c691d120e0b8496b2e843635edd9cc7dcef0/library/common/src/main/java/com/google/android/exoplayer2/trackselection/TrackSelectionOverrides.java#L91-L92

When `TrackSelectionDialogBuilder` and `TrackSelectionView` are migrated to the new track selection API (aka depend on Player, not ExoPlayer), their behavior should conform to your requirements.

We don't have a timeline as to when those UI components will be migrated.

**Comment by tonihei** [comment]
I believe this was solved by https://github.com/google/ExoPlayer/commit/08b861b61a732a4dbae9b80b98119a8205c48604. I'll close the issue accordingly.
