### ISSUE TITLE
Negative Pitch value for Exoplayer Xamarin forms

### ISSUE THREAD

**Issue by ajoypoweract** [google/ExoPlayer#8638]
I used exoplayer into my xamarin forms cross platform app. Regarding the pitch, I want range between -4 to + 4 semitones.
How to apply pitch value (-4). I know negative pitch is not supported on Exoplayer. But my requirement is , I can change pitch frequently -4 to +4. How it posssible.

**Comment by andrewlewis** [comment]
The pitch parameter in ExoPlayer's `PlaybackParameters` is a multiplicative factor (not a number of semitones). I think the factor multiplies the frequency, but I could be wrong so you may want to experiment or read the source for the implementation in [`Sonic.java`](https://github.com/google/ExoPlayer/blob/0e4d316/library/core/src/main/java/com/google/android/exoplayer2/audio/Sonic.java). I'd guess that you can multiply the pitch by `2^(n/12)` to scale up by `n` semitones but you probably know the music theory side of this better than I do!

Something to be aware of is that Sonic is really designed to handle speech input, not music, so you may find that the output quality is not good enough for use cases involving music.

**Comment by krocard** [comment]
Note that the 2^(N/12) formula is exact only for equal temperance. Though I doubt the difference is audible.
+1 <=> set pitch to 2^1/12 ~ 1.059
-1 <=> set pitch to 2^-1/2 ~ 0.944

Doubling on @andrewlewis's warning: Sonic was design for relatively high speed adjustment of voice. For such small pitch change of music, the result might not be good enough.
