### ISSUE TITLE
NPE in IcyHeaders class

### ISSUE THREAD

**Issue by aroraprateek202112** [google/ExoPlayer#8641]
I am trying to play multiple audio files in loop. Previously with ExtractorMediaSource it is working fine, but after upgrade the exoplayer version and change the ExtractorMediaSource with ProgressiveMediaSource, this NPE is observed.

I have created ProgressiveMediaSource for each audio file, and then created the ConcatenationMediaSource by passing array of ProgressiveMediaSource. And for playing the source in loop, I have created a LoopingMediaSource from this ConcatenatingMediaSource.

**NPE:**

> PlayerEventListener onPlayerError e : com.google.android.exoplayer2.ExoPlaybackException: Source error
>         at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:579)
>         at android.os.Handler.dispatchMessage(Handler.java:98)
>         at android.os.Looper.loop(Looper.java:148)
>         at android.os.HandlerThread.run(HandlerThread.java:61)
>      Caused by: com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.Map.get(java.lang.Object)' on a null object reference
>         at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:436)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
>         at java.lang.Thread.run(Thread.java:818)
>      Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.Map.get(java.lang.Object)' on a null object reference
>         at com.google.android.exoplayer2.metadata.icy.IcyHeaders.parse(IcyHeaders.java:61)
>         at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1019)
>         at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
>         at java.lang.Thread.run(Thread.java:818) 
>      AudioFragment{280214a (41456c34-99a5-4fdd-b9c8-9af9763bc952) com.panasonic.android_app.fragments.AudioFragment}
> 02-26 14:24:54.117 24235-24235/panasonic.digital.signage.pionpremises2 D/com.panasonic.android_app.fragments.AudioFragment: [2021-02-26 14:24:54.215] PlayerEventListener onPlayerStateChanged playbackState : 1 AudioFragment{280214a (41456c34-99a5-4fdd-b9c8-9af9763bc952) com.panasonic.android_app.fragments.AudioFragment}

- ExoPlayer version number- 2.13.2
- Android version - 6.0.1
- Android device - Amlogic Device

**Comment by icbaker** [comment]
What DataSource implementation is being used here?

Looks like that NPE is occurring because `DataSource#getResponseHeaders()` is returning null (which is not permitted).

**Comment by aroraprateek202112** [comment]
We have to play encrypted audio files. For that we have use EncryptedDataSource. Please find the file attached.

[EncryptedFileDataSource.txt](https://github.com/google/ExoPlayer/files/6048979/EncryptedFileDataSource.txt)

.

**Comment by icbaker** [comment]
I suspect this is your problem:

```
  @Override
  public Map<String, List<String>> getResponseHeaders() {
    return null;
  }
```

If you remove that completely the default implementation from DataSource returns an empty map and should resolve your NPE.

**Comment by aroraprateek202112** [comment]
Thanks @IanDBird, Now it's working.
