### ISSUE TITLE
TimeBar is missing scrubber after return from PiP (StyledPlayerView)

### ISSUE THREAD

**Issue by moneytoo** [google/ExoPlayer#8646]
When I enter and leave Picture-in-Picture mode, the `TimeBar` in `StyledPlayerView` is missing its scrubber (thumb). When I hide and show the controller by tapping the screen, only partial scrubber is displayed.

Steps to reproduce:

1. Open a video file from a file manager in [Demo app](https://github.com/moneytoo/ExoPlayerDemo/tree/pip)
2. Pres system "Home" button to enter PiP
3. Tap the PiP window and switch back to the full screen activity
4. See the scrubber

I only hide and restore controls depending on PiP state. Full [demo Activity](https://github.com/moneytoo/ExoPlayerDemo/blob/pip/app/src/main/java/com/example/exoplayer/MainActivity.java).

```
    @Override
    public void onPictureInPictureModeChanged(boolean isInPictureInPictureMode) {
        super.onPictureInPictureModeChanged(isInPictureInPictureMode);

        if (isInPictureInPictureMode) {
            playerView.hideController();
        } else {
            playerView.showController();
        }
    }

    @Override
    protected void onUserLeaveHint() {
        enterPictureInPictureMode();
    }
```

- ExoPlayer version number: 2.13.2
- Android version: Android 10
- Android device: OnePlus 7

Bugreport: [bugreport-OnePlus7-QKQ1.190716.003-2021-02-28-15-33-59.zip](https://github.com/google/ExoPlayer/files/6056957/bugreport-OnePlus7-QKQ1.190716.003-2021-02-28-15-33-59.zip)

![Screenshot_20210228-151552](https://user-images.githubusercontent.com/1071643/109422374-86b8f880-79db-11eb-966d-166841d3535a.jpg)

![Screenshot_20210228-151657](https://user-images.githubusercontent.com/1071643/109422380-8f113380-79db-11eb-9363-1df1480647a3.jpg)

**Comment by ojw28** [comment]
This should be fixed by the commit referenced above. The fix will be included in 2.13.3 (if there is one) or 2.14.0 (if not). Thanks for the report!
