### ISSUE TITLE
Overlaying graphics

### ISSUE THREAD

**Issue by kaweesi** [google/ExoPlayer#8648]
### Use case description
As a programmer i would wish to overlay/float on-top of the playing video graphics such as a logo, lower thirds, tickers etc.

**Comment by ojw28** [comment]
You can already do this, simply by placing views over the player in the same way that you'd do for any other type of view in Android. If you wish to customize ExoPlayer's built in UI components, refer to [this documentation](https://exoplayer.dev/ui-components.html#customization).

**Comment by kaweesi** [comment]
BTW, is it possible to use a videoView or anything else to load a video under controls?
