### ISSUE TITLE
Color error when playing Dash Videos 

### ISSUE THREAD

**Issue by luisuarez09** [google/ExoPlayer#8649]
In some smart phone devices, during low resolution video playback below 480p, the video is displayed with color errors. I am using Dash

- Samsung S5. Versión Android: 6.0
- Samsung J2 Pro. Android 7.1.1
- Version ExoPlayer: 2.13.2

![WhatsApp Image 2021-02-28 at 6 19 04 PM](https://user-images.githubusercontent.com/6549169/109435587-8a577a00-79f1-11eb-8c9f-0a0d554cdfb0.jpeg)
![WhatsApp Image 2021-02-28 at 6 19 03 PM](https://user-images.githubusercontent.com/6549169/109435593-95aaa580-79f1-11eb-96d5-9e2207d215d0.jpeg)

Greetings

**Comment by krocard** [comment]
Unfortunately, we cannot help you with the provided information and screenshots.

We need a bug report to understand the setup (for example which decoder is used) and the media played.

If you're unable to share [bug reports](https://developer.android.com/studio/debug/bug-report) or
test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format
"Issue #1234" ("#1234" is replaced with your issue number). Please also update this issue to
indicate you've done this.
