### ISSUE TITLE
Loop playing

### ISSUE THREAD

**Issue by pufic** [google/ExoPlayer#865]
I've read the issue https://github.com/google/ExoPlayer/issues/794 and I really need to keep buffer.

In my app I have small videos (just mp4) and in most cases user needs to repeat them several times, to remember better. Every time I seekTo(0) the video downloads again. My app usecases are almost with mobile network, so I care about the gigabytes of traffic and if the connection is not too fast - every repeat the user needs to wait for download. 

Can you please advise me what to do?

**Comment by MaTriXy** [comment]
You can install a simple HttpResponseCache for first step - 
This can help reduce the file downloads.
http://developer.android.com/reference/android/net/http/HttpResponseCache.html
---------------
Better option is to setup a cache mechanism where you download the files into a folder and serve them - as much as Picasso does for images (for example)

**Comment by ojw28** [comment]
Tracked by #490
