### ISSUE TITLE
Major crash occur mainly on android 11 devices

### ISSUE THREAD

**Issue by andrewsafwatsamuel** [google/ExoPlayer#8652]
I have crash RemoteServiceException with error message Context.startForegroundService() did not then call Service.startForeground() this crash occurs at a player service that uses MediaBrowserServiceCompat this player streams soundtracks and shows player notification with controls. I confirmed that I am calling Service.startForeground() once after Context.startForegroundService() before the required five seconds pass calling it from onStartCommand() of the service also the service intent is sent in two conditions at Player.EventListener callbacks of ExoPlayer at Player.EventListener.onPositionDiscontinuity() with reason DISCONTINUITY_REASON_PERIOD_TRANSITION and Player.EventListener.onPlayerStateChanged() with Player.STATE_READY. this crash mainly occurs on android 11 devices especially Samsung devices It can be also triggered with multiple fast presses on play/pause button from the notification

- **Clear reproduction steps including observed and expected behavior:**
    
    i.
   - start player 
   - from the notifications press play/ pause button many times while the app is in foreground 
   - play/ pause button does not respond
   - ANR occurs
    2.
   - start the player
   - put the app to background
   - from the notifications press play/ pause button many times 
   - the notification hide and exception triggered in the background
   - open the app again and start player
   - ANR occurs
    3.  
   - start the player
   - put the app to background
   - open a push notification inside the app
   - press play/ pause many time while the app in foreground
   - ANR occurs
    4.
   - start the player
   - put the app to background
   - open many other apps 
   - press play/ pause many times
   - the player notification is not responding then hides and exception triggered in the background

- **ExoPlayer version number** : 2.8.4
- **android**: mainly 11 API 30, 10 API 29, 9 API 28
- **Android device**: Samsung Devices, xiaomi redmi note 5, xiaomi mi a2, huawei honor

**Comment by krocard** [comment]
@andrewsafwatsamuel Could you please join a bug report to allow us to see the errors around the ANR ?

If you're unable to share [bug reports](https://developer.android.com/studio/debug/bug-report) or test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #1234" ("#1234" is replaced with your issue number). Please also update this issue to indicate you've done this.

**Comment by marcbaechinger** [comment]
Agreed we need more information to look into what is going wrong here. 

Can you shed some light on this statement:

> the service intent is sent in two conditions at Player.EventListener callbacks of ExoPlayer at
> Player.EventListener.onPositionDiscontinuity() with reason DISCONTINUITY_REASON_PERIOD_TRANSITION
> and Player.EventListener.onPlayerStateChanged() with Player.STATE_READY

This sounds like you are sending service intents to the service from within callback of the player, as I would expect that the player is running inside the service. Can you confirm that the ExoPlayer instance I running inside the service?

**Comment by andrewsafwatsamuel** [comment]
Reason: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{b1f9fe0 u0 }
    Load: 0.02 / 0.03 / 0.06
    CPU usage from 0ms to 7830ms later (2021-03-15 10:50:58.515 to 2021-03-15 10:51:06.346) with 99% awake:
      56% 747/surfaceflinger: 41% user + 14% kernel / faults: 239 minor 3 major
      49% 11166/com.innovolve.iqraaly: 42% user + 7.4% kernel / faults: 1578 minor 37 major
      28% 2274/com.android.systemui: 21% user + 7.1% kernel / faults: 2780 minor 31 major
      19% 2071/system_server: 8.6% user + 11% kernel / faults: 2379 minor 322 major
      12% 698/android.hardware.graphics.composer@2.1-service: 5.3% user + 7.5% kernel / faults: 127 minor 15 major
      9.3% 1059/media.codec: 5.6% user + 3.7% kernel / faults: 4341 minor 43 major
      6.3% 150/kswapd0: 0% user + 6.3% kernel
      5.6% 23885/com.google.android.gms.persistent: 3.1% user + 2.4% kernel / faults: 2441 minor 69 major
      3.9% 22367/com.google.android.inputmethod.latin: 2.4% user + 1.5% kernel / faults: 1902 minor 81 major
      3.7% 2670/com.android.phone: 2.4% user + 1.2% kernel / faults: 1833 minor 182 major
      3.3% 289/kgsl_worker_thr: 0% user + 3.3% kernel
      3.3% 11527/com.android.camera: 2.6% user + 0.6% kernel / faults: 2086 minor 10 major
      3.1% 17029/adbd: 0.5% user + 2.6% kernel / faults: 45 minor
      2.4% 448/mmc-cmdqd/0: 0% user + 2.4% kernel
      2.2% 88/kcompactd0: 0% user + 2.2% kernel
      0% 690/android.hardware.camera.provider@2.4-service: 0% user + 0% kernel / faults: 275 minor 27 major
      2.1% 4506/kworker/u16:14: 0% user + 2.1% kernel
      2% 704/android.hardware.sensors@1.0-service: 0.5% user + 1.5% kernel / faults: 86 minor 32 major
      2% 1506/kworker/u16:13: 0% user + 2% kernel
      2% 6569/mdss_fb0: 0% user + 2% kernel
      1.6% 3082/irq/50-1008000.: 0% user + 1.6% kernel
      1.6% 11508/com.qualcomm.qti.smcinvokepkgmgr: 1% user + 0.6% kernel / faults: 1185 minor 1 major
      1.5% 8544/kworker/u16:2: 0% user + 1.5% kernel
      1.5% 24408/kworker/u16:12: 0% user + 1.5% kernel
      1.5% 29223/com.android.bluetooth: 0% user + 1.5% kernel / faults: 76 minor 18 major
      0% 1023/media.extractor: 0% user + 0% kernel / faults: 1339 minor 26 major
      1.4% 2966/cnss_diag: 1% user + 0.3% kernel / faults: 31 minor
      1.1% 586/logd: 0.8% user + 0.2% kernel / faults: 34 minor
      1.1% 6573/kworker/u16:4: 0% user + 1.1% kernel
      0.6% 1//init: 0.1% user + 0.5% kernel / faults: 70 minor
      0.6% 349/irq/242-synapti: 0% user + 0.6% kernel
      0.6% 440/cfinteractive: 0% user + 0.6% kernel
      0.6% 30766/kworker/u16:5: 0% user + 0.6% kernel
      0.5% 79/smem_native_rpm: 0% user + 0.5% kernel
      0.5% 10232/com.facebook.orca: 0.5% user + 0% kernel / faults: 277 minor
      0.3% 1027/mediaserver: 0% user + 0.3% kernel / faults: 70 minor 10 major
      0% 1143/tombstoned: 0% user + 0% kernel / faults: 55 minor 43 major
      0.3% 8543/kworker/u16:0: 0% user + 0.3% kernel
      0.3% 11329/com.truecaller: 0.3% user + 0% kernel / faults: 243 minor
      0.3% 28314/kworker/u16:17: 0% user + 0.3% kernel
      0.2% 3/ksoftirqd/0: 0% user + 0.2% kernel
      0.2% 7/rcu_preempt: 0% user + 0.2% kernel
      0.2% 553/ueventd: 0.2% user + 0% kernel
      0.2% 688/android.hardware.audio@2.0-service: 0% user + 0.2% kernel / faults: 104 minor 12 major
      0% 689/android.hardware.bluetooth@1.0-service-qti: 0% user + 0% kernel / faults: 25 minor 5 major
      0.2% 708/android.hardware.wifi@1.0-service: 0.2% user + 0% kernel / faults: 48 minor
      0.2% 741/audioserver: 0% user + 0.2% kernel / faults: 101 minor 13 major
      0.2% 1040/netd: 0% user + 0.2% kernel / faults: 61 minor 10 major
      0.2% 4149/com.lbe.security.miui: 0% user + 0.2% kernel / faults: 137 minor
      0.2% 8514/kworker/0:1: 0% user + 0.2% kernel
      0.2% 8522/kworker/1:1: 0% user + 0.2% kernel
      0.2% 11499/logcat: 0% user + 0.2% kernel / faults: 3 minor
      0.2% 27120/kworker/u17:0: 0% user + 0.2% kernel
      0.1% 10/rcuop/0: 0% user + 0.1% kernel
      0% 11/rcuos/0: 0% user + 0% kernel
      0.1% 18/rcuop/1: 0% user + 0.1% kernel
      0.1% 21/migration/2: 0% user + 0.1%

**Comment by andrewsafwatsamuel** [comment]
> 
> 
> Agreed we need more information to look into what is going wrong here.
> 
> Can you shed some light on this statement:
> 
> > the service intent is sent in two conditions at Player.EventListener callbacks of ExoPlayer at
> > Player.EventListener.onPositionDiscontinuity() with reason DISCONTINUITY_REASON_PERIOD_TRANSITION
> > and Player.EventListener.onPlayerStateChanged() with Player.STATE_READY
> 
> This sounds like you are sending service intents to the service from within callback of the player, as I would expect that the player is running inside the service. Can you confirm that the ExoPlayer instance I running inside the service?

yes I am running the player from inside the service

**Comment by andrewsafwatsamuel** [comment]
> 
> 
> @andrewsafwatsamuel Could you please join a bug report to allow us to see the errors around the ANR ?
> 
> If you're unable to share [bug reports](https://developer.android.com/studio/debug/bug-report) or test content publicly, please send them to [dev.exoplayer@gmail.com](mailto:dev.exoplayer@gmail.com) using a subject in the format "Issue #1234" ("#1234" is replaced with your issue number). Please also update this issue to indicate you've done this.

```
ANR in com.MyApp
PID: 11166

Reason: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{b1f9fe0 u0 com.MyApp/.player.service.MyAppPlayerService}
Load: 0.02 / 0.03 / 0.06
CPU usage from 0ms to 7830ms later (2021-03-15 10:50:58.515 to 2021-03-15 10:51:06.346) with 99% awake:
56% 747/surfaceflinger: 41% user + 14% kernel / faults: 239 minor 3 major
49% 11166/com.MyApp: 42% user + 7.4% kernel / faults: 1578 minor 37 major
28% 2274/com.android.systemui: 21% user + 7.1% kernel / faults: 2780 minor 31 major
19% 2071/system_server: 8.6% user + 11% kernel / faults: 2379 minor 322 major
12% 698/android.hardware.graphics.composer@2.1-service: 5.3% user + 7.5% kernel / faults: 127 minor 15 major
9.3% 1059/media.codec: 5.6% user + 3.7% kernel / faults: 4341 minor 43 major
6.3% 150/kswapd0: 0% user + 6.3% kernel
5.6% 23885/com.google.android.gms.persistent: 3.1% user + 2.4% kernel / faults: 2441 minor 69 major
3.9% 22367/com.google.android.inputmethod.latin: 2.4% user + 1.5% kernel / faults: 1902 minor 81 major
3.7% 2670/com.android.phone: 2.4% user + 1.2% kernel / faults: 1833 minor 182 major
3.3% 289/kgsl_worker_thr: 0% user + 3.3% kernel
3.3% 11527/com.android.camera: 2.6% user + 0.6% kernel / faults: 2086 minor 10 major
3.1% 17029/adbd: 0.5% user + 2.6% kernel / faults: 45 minor
2.4% 448/mmc-cmdqd/0: 0% user + 2.4% kernel
2.2% 88/kcompactd0: 0% user + 2.2% kernel
0% 690/android.hardware.camera.provider@2.4-service: 0% user + 0% kernel / faults: 275 minor 27 major
2.1% 4506/kworker/u16:14: 0% user + 2.1% kernel
2% 704/android.hardware.sensors@1.0-service: 0.5% user + 1.5% kernel / faults: 86 minor 32 major
2% 1506/kworker/u16:13: 0% user + 2% kernel
2% 6569/mdss_fb0: 0% user + 2% kernel
1.6% 3082/irq/50-1008000.: 0% user + 1.6% kernel
1.6% 11508/com.qualcomm.qti.smcinvokepkgmgr: 1% user + 0.6% kernel / faults: 1185 minor 1 major
1.5% 8544/kworker/u16:2: 0% user + 1.5% kernel
1.5% 24408/kworker/u16:12: 0% user + 1.5% kernel
1.5% 29223/com.android.bluetooth: 0% user + 1.5% kernel / faults: 76 minor 18 major
0% 1023/media.extractor: 0% user + 0% kernel / faults: 1339 minor 26 major
1.4% 2966/cnss_diag: 1% user + 0.3% kernel / faults: 31 minor
1.1% 586/logd: 0.8% user + 0.2% kernel / faults: 34 minor
1.1% 6573/kworker/u16:4: 0% user + 1.1% kernel
0.6% 1//init: 0.1% user + 0.5% kernel / faults: 70 minor
0.6% 349/irq/242-synapti: 0% user + 0.6% kernel
0.6% 440/cfinteractive: 0% user + 0.6% kernel
0.6% 30766/kworker/u16:5: 0% user + 0.6% kernel
0.5% 79/smem_native_rpm: 0% user + 0.5% kernel
0.5% 10232/com.facebook.orca: 0.5% user + 0% kernel / faults: 277 minor
0.3% 1027/mediaserver: 0% user + 0.3% kernel / faults: 70 minor 10 major
0% 1143/tombstoned: 0% user + 0% kernel / faults: 55 minor 43 major
0.3% 8543/kworker/u16:0: 0% user + 0.3% kernel
0.3% 11329/com.truecaller: 0.3% user + 0% kernel / faults: 243 minor
0.3% 28314/kworker/u16:17: 0% user + 0.3% kernel
0.2% 3/ksoftirqd/0: 0% user + 0.2% kernel
0.2% 7/rcu_preempt: 0% user + 0.2% kernel
0.2% 553/ueventd: 0.2% user + 0% kernel
0.2% 688/android.hardware.audio@2.0-service: 0% user + 0.2% kernel / faults: 104 minor 12 major
0% 689/android.hardware.bluetooth@1.0-service-qti: 0% user + 0% kernel / faults: 25 minor 5 major
0.2% 708/android.hardware.wifi@1.0-service: 0.2% user + 0% kernel / faults: 48 minor
0.2% 741/audioserver: 0% user + 0.2% kernel / faults: 101 minor 13 major
0.2% 1040/netd: 0% user + 0.2% kernel / faults: 61 minor 10 major
0.2% 4149/com.lbe.security.miui: 0% user + 0.2% kernel / faults: 137 minor
0.2% 8514/kworker/0:1: 0% user + 0.2% kernel
0.2% 8522/kworker/1:1: 0% user + 0.2% kernel
0.2% 11499/logcat: 0% user + 0.2% kernel / faults: 3 minor
0.2% 27120/kworker/u17:0: 0% user + 0.2% kernel
0.1% 10/rcuop/0: 0% user + 0.1% kernel
0% 11/rcuos/0: 0% user + 0% kernel
0.1% 18/rcuop/1: 0% user + 0.1% kernel
0.1% 21/migration/2: 0% user + 0.1%
```

**Comment by andrewsafwatsamuel** [comment]
I tried to reproduce that issue and removed the call to service.stopForeground() the crash didn't occur and the player notification did not respond just frozen on pause icon and did not pause the player

**Comment by marcbaechinger** [comment]
The information provided gives not much evidence on something going wrong on the player side. Can you narrow down your question a bit on why you think it's a problem on ExoPlayer side?

It looks like that your app is not calling start/stopForeground correctly. Can you review the code that is calling these methods? If you want us to give you some feedback you should provide some more info about when your code calls start/stopForeground and how you think this is related to the ExoPlayer library or the PlayerNotificationManager. not working correctly
