### ISSUE TITLE
I get a MediaDrmStateException.

### ISSUE THREAD

**Issue by KazukiSugiyama107** [google/ExoPlayer#8655]
### Searched documentation and issues
・ExoPlayer Javadoc.
・ExoPlayer Issues

### Question
The same error as the following issue is occurring during streaming playback.
https://github.com/google/ExoPlayer/issues/8175

The application in error is requesting a license from the license server.
No license has been confirmed at the time of this streaming playback.
From that, I think the license application failed.

・Is the problem that is occurring this time caused by the same Qualcomm error as #8175 ?

Version of ExoPlayer being used: 2.12.1

### A full bug report captured from the device

I sent it to dev.exoplayer@gmail.com.

**Comment by krocard** [comment]
@jt64 could you please look if this is the same error you were mentioning in https://github.com/google/ExoPlayer/issues/8175#issuecomment-729276800?

Additionally consider copying the relevant error log line here or in original issue https://github.com/google/ExoPlayer/issues/8175 for search discoverability and triage.

Thanks.

**Comment by KazukiSugiyama107** [comment]
Thank you for your reply.

The application with the error is the same as #8175 and the source code is the same.
error is `Failed to get key request: General DRM error` with the same content.

Below is the log that occurred at the time of the error.

```
ExoPlayerImplInternal: Source error.
ExoPlayerImplInternal: com.google.android.exoplayer2.drm.DrmSession$DrmSessionException: android.media.MediaDrm$MediaDrmStateException: Failed to get key request: General DRM error
ExoPlayerImplInternal: 	at com.google.android.exoplayer2.drm.DefaultDrmSession.a(DefaultDrmSession.java:44)
ExoPlayerImplInternal: 	at com.google.android.exoplayer2.drm.DefaultDrmSession.b(DefaultDrmSession.java:21)
ExoPlayerImplInternal: 	at com.google.android.exoplayer2.drm.DefaultDrmSession.a(DefaultDrmSession.java:43)
ExoPlayerImplInternal: 	at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.a(DefaultDrmSessionManager.java:58)
ExoPlayerImplInternal: 	at com.google.android.exoplayer2.drm.DefaultDrmSession.a(DefaultDrmSession.java:29)
ExoPlayerImplInternal: 	at com.google.android.exoplayer2.drm.DefaultDrmSession.b(DefaultDrmSession.java:9)
ExoPlayerImplInternal: 	at m.c.b.b.s1.k0.a(SampleQueue.java:152)
ExoPlayerImplInternal: 	at m.c.b.b.s1.q0.g.a(ChunkSampleStream.java:68)
ExoPlayerImplInternal: 	at m.c.b.b.s1.k0.a(SampleQueue.java:64)
ExoPlayerImplInternal: 	at m.c.b.b.s1.k0.a(SampleQueue.java:8)
ExoPlayerImplInternal: 	at m.c.b.b.z.a(BaseRenderer.java:15)
ExoPlayerImplInternal: 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.a(MediaCodecRenderer.java:30)
ExoPlayerImplInternal: 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.b(MediaCodecRenderer.java:3)
ExoPlayerImplInternal: 	at m.c.b.b.j0.handleMessage(ExoPlayerImplInternal.java:24)
ExoPlayerImplInternal: 	at m.c.b.b.j0.b(ExoPlayerImplInternal.java:161)
ExoPlayerImplInternal: 	at android.os.Handler.dispatchMessage(Handler.java:102)
ExoPlayerImplInternal: 	at android.os.HandlerThread.run(HandlerThread.java:67)
ExoPlayerImplInternal: 	at android.os.Looper.loop(Looper.java:223)
ExoPlayerImplInternal: Caused by: android.media.MediaDrm$MediaDrmStateException: Failed to get key request: General DRM error
ExoPlayerImplInternal: 	at com.google.android.exoplayer2.drm.DefaultDrmSession.a(DefaultDrmSession.java:40)
ExoPlayerImplInternal: 	at android.media.MediaDrm.getKeyRequest(Native Method)
ExoPlayerImplInternal: 	at m.c.b.b.m1.t.a(FrameworkMediaDrm.java:69)
```

**Comment by jt64** [comment]
From the bugreport we see these errors: [included for reference and tracking]

  cdm_engine_generate_key_request_time_us: mean=7942 count=1 {error_code:323 323}
  oemcrypto_prep_and_sign_license_request_time_us[1]: mean=2521 count=1 {oemcrypto_result:10085 10085}

We have seen this error very intermittently on some Pixel devices. We have an open bug with Qualcomm to resolve it.

The workaround described in #8175 would probably resolve this, but that depends on the ExoPlayer feature requested in #8039 which is still open.

**Comment by jt64** [comment]
When the workaround is available, if you find it doesn't help please reopen this bug and assign it back to us.
