### ISSUE TITLE
Why does the 2.13.2 version always report this exception：Player is accessed on the wrong thread  ?

### ISSUE THREAD

**Issue by PeOS-China** [google/ExoPlayer#8656]
Exception: [3865] Player is accessed on the wrong thread. See https://exoplayer.dev/issues/player-accessed-on-wrong-thread
I run this code on the main thread， the program reports an exception (Player is accessed on the wrong thread) ：

        player = SimpleExoPlayer.Builder(requireContext()).setLooper(Looper.getMainLooper()).build()

        val dataSourceFactory = DefaultDataSourceFactory(requireContext(), Util.getUserAgent(requireContext(), "DongMi"))
        val mediaSource = ProgressiveMediaSource.Factory(dataSourceFactory).createMediaSource(Uri.parse(viewModel.path))

        player.repeatMode = Player.REPEAT_MODE_ONE
        player.volume = SysDataManager.getMusicVolume()
        player.setMediaSource(mediaSource)

        player.playWhenReady = true
        binding.videoPlayer.setSimpleExoPlayer(player)

Regardless of whether it is setLooper or not, this exception will be reported.

**Comment by tonihei** [comment]
The exception has a stack trace that tells you exactly where the access on a background thread happened. Please check this to find the relevant code.
