### ISSUE TITLE
Something wrong with orientation in lower version of android.

### ISSUE THREAD

**Issue by cabuhatprince** [google/ExoPlayer#866]

**Comment by ojw28** [comment]
See #91

**Comment by cabuhatprince** [comment]
hi, i try this but it's still the same ? is it a bug?

**Comment by cabuhatprince** [comment]
Hi, i dont know what is the best solution , the orientation is not working in the lowerversion? only in lollipop? is it a bug? please help thankyou!

**Comment by cabuhatprince** [comment]
Hi, i did it now! Thankyou very much for your hardwork :*
