### ISSUE TITLE
Missing for ImaAdsLoader.Builder.buildForAdsResponse

### ISSUE THREAD

**Issue by gsavvid** [google/ExoPlayer#8663]
I've just updated from version `2.10.2` to `2.13.2` and I noticed that `ImaAdsLoader.Builder.buildForAdsResponse` doesn't exist anymore.

What's the equivalent to achieve the same result in version `2.13.2` (ie side-load a VMAP file instead of passing an ad tag uri)?

**Comment by andrewlewis** [comment]
It's still possible to pass a literal ads response by building a data URI. Please see the [documentation here](https://github.com/google/ExoPlayer/blob/d0dd33e/extensions/ima/src/main/java/com/google/android/exoplayer2/ext/ima/ImaAdsLoader.java#L72-L79).
