### ISSUE TITLE
How to know which MediaSource caused ExoPlaybackException (on preloading the next track)?

### ISSUE THREAD

**Issue by halaei** [google/ExoPlayer#8666]
To handle `ExoPlaybackException` we must implement `EventListener.onPlayerError()`. If for example, we encounter a 403 HTTP error because the track's URL is expired,  we can catch it inside this function and take appropriate actions:
- See which track caused 403 exception.
- Check our application API to see if we have access to a new URL for the track.
- Replace the corresponding MediaSource with a new one having a valid & fresh URL.
- Play the new MediaSource.

It isn't clear how we can find which track caused the exception. Currently we are using `player.getCurrentWindowIndex()`. There is a new `mediaPeriodId` in the exception too, but I am not sure how to trace it back to `MediaSource`. Also I am not sure if either of `player.getCurrentWindowIndex()` or ` mediaPeriodId` leads me to the correct `MediaSource`, in case the media source was just preloaded and it is not actually the current playing media source.

**Comment by marcbaechinger** [comment]
I think with the approach you are currently using, `player.getCurrentWindowIndex()` will return the window index that belongs to the media source that causes the exception (for my explanation I assume that you are not using `ConcatenatingMediaSource` but the top-level playlist API with a 1:1 relationship between media sources and windows). So in case of the playback error it is clear that the source from which the current window originated caused the exception, and you could do something like the following to recover:

```
MediaItem mediaItem = player.getCurrentMediaItem();
int windowIndex = player.getCurrentWindowIndex();
MediaItem fixedMediaItem = mediaItem.buildUpon().setUri(fixMyUri(mediaItem.playbackProperties.uri)).build();
player.removeMediaItem(windowIndex);
player.addMediaItem(windowIndex, fixedMediaItem);
player.seekTo(windowIndex, C.TIME_UNSET);
player.play();
player.prepare();
```

The reason why this works is that you get the `ExoPlayerPlaybackException` in `onPlayerError` late, namely when the player (that had a load error for the given medias source earlier) wants to start playback for the given window, but can't as no data is available. 

While this works, you probably want to get notified about this earlier, which is when you notice that a load error occurs when the player tries to buffer data ahead. In a playlist for which the player transitions to the next item without user interaction, this is when the player tries to load data ahead for the next window. Being aware of this, you could fix your media source ahead of time and possibly don't even run into the playback exception. I don't think I can give you a answer regarding an API that exactly matches this use case. You may want to look into a custom `LoadErrorHandlingPolicy` which gets notified early about such loading errors and can evaluate which url caused the exception. However, there is no API to correlated that properly to the media source that caused this load error though. The API of the `LoadErrorhandlingPolicy` is not designed for this purpose.

Also, if the player does not transition automatically to the next window, but instead the user skips to this window you will be late anyway, and encounter the `ExoPlayerPlaybackException` in `onPlayerError` as above. You probably may want to tweak the `LoadErrorHandlingPolicy` for this case to fail with a playback exception  quickly, but again, the API is not designed for this I think.

**Comment by tonihei** [comment]
Just to add to that:
One further alternative if you want to handle the case early is to listen to `AnalyticsListener.onLoadError` which has an `EventTime` parameter that tells you exactly which item the error is for.

**Comment by halaei** [comment]
Thanks for your help.
So I can assume `onPlayerError()` is only called for the current track and they are delayed in case of preloading. Meanwhile I take a look at `LoadErrorhandlingPolicy` and `AnalyticsListener.onLoadError()` to see if I can handle the errors during the preload sooner, so that I can prevent lags.
I hope I get it right.
