### ISSUE TITLE
How to change playback frame rate?

### ISSUE THREAD

**Issue by ZeroOneZeroR** [google/ExoPlayer#8667]
Suppose my video frame rate is 30 fps. But i want to play it at 5 fps. How can i achieve this?

**Comment by krocard** [comment]
@ZeroOneZeroR you have not filled the issue template. It seems you have only written the title of the issue.
Please provide more information regarding your question.

If your question is about playback speed, please take a look at `ExoPlayer.setPlaybackParameters`.

**Comment by ZeroOneZeroR** [comment]
Suppose my video frame rate is 30 fps. But i want to play it at 5 fps. It is not speed. It is frame rate. How can i achieve this?

**Comment by krocard** [comment]
I'm not sure to understand. Do you want to play the video 6 time slower (30fps/6 = 5fps), then use `ExoPlayer.setPlaybackParameters` and pass a speed of 1/6=1.6667.

If you want to artificially drop 5/6 of the video frames, then I'm afraid ExoPlayer does not support such use case and we would like to understand better why you would want to do that.

**Comment by ZeroOneZeroR** [comment]
Yeah I want to drop frames. I want to let the users of my app to encode a video with lower frame rate. But before encoding, I want to show that on preview.

**Comment by krocard** [comment]
The easiest way would be for you to subclass `MediaCodecVideoRenderer`, overriding `processOutputBuffer`. Call the super method with isDecodeOnlyBuffer set to true 5/6 (or whatever other ratio) of the time. Make sure to forward buffers that are already decodeOnlyBuffer.
Pseudo Code:
```
@Override
fun processOutputBuffer(..., decodeOnlyBuffer, ...)
   if (decodeOnlyBuffer) return super.processOutputBuffer(decodeOnlyBuffer)

   bool shouldDrop = this.outputBufferBeforeDownsamplingDropCount++ % 6 != 0; // drop 5/6 of frames
   return super.processOutputBuffer(shouldDrop);
```
You can inject you custom `DropMediaCodecVideoRenderer` by overriding `DefaultRenderersFactory.buildVideoRenderers`. Pass your custom RenderersFactory to the SimpleExoPlayer's Builder.

**Comment by ZeroOneZeroR** [comment]
Thanks. I will try this way.

**Comment by krocard** [comment]
Let us know how it went. Closing as the question has been answered.
