### ISSUE TITLE
How to seek video exact and fast?

### ISSUE THREAD

**Issue by ZeroOneZeroR** [google/ExoPlayer#8671]
Is it possible to seek video exact and very fast with seekbar progress? If directly it is not possible, do you have any idea or workaround to achieve this?

**Comment by krocard** [comment]
There are 2 reasons for delays when seeking:
 1) the media does not support exact seeking in O(1). This can be mitigated by searching in the stream the seek position, but is slow in O(n). This can mitigated by using a media that support exact seeking.
 2) the seek destination is in between key frame, thus the frames in between must be decoded then discarded. There is no way to avoid the delay but it can be minimized by having the media contain more frequent key frames.

Without more information about your use case, it's hard to know what the bottleneck here.
Could you please post the media you wish to seek into as well as an estimate of the time it takes to seek into it and your target. Attaching a bug report would be great too.
If you're unable to share [bug reports](https://developer.android.com/studio/debug/bug-report) or test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #1234" ("#1234" is replaced with your issue number). Please also update this issue to indicate you've done this.

**Comment by ZeroOneZeroR** [comment]
I have understood the reasons. But I have seen many video editing apps can seek exact with seek bar progress very fast. How do they do that? Could you please give any idea?

**Comment by krocard** [comment]
Without looking at those apps, there is no way to be sure. I can think of many ways to accelerate seeking:
 - download the content before playing it
 - do not exact frame accurate seeking but seeking to the closest key frame, for most media users will not see the difference
 - build a seek table for fast exact seeking on media not supporting it
 - (re) encode the media to have frequent keyframes
 - switch to a low resolution stream temporarily after seeking
 - pre-decode the stream

Without knowing the bottleneck in your seeking and use case, it's hard to know which one would be more applicable to your app.
Please provide more information about your seek issue.

**Comment by ZeroOneZeroR** [comment]
I want to seek like the app InShot. Videos are local, not from server. I don't need to seek if the media is not seekable. Reencoding is not allowed for me.

**Comment by krocard** [comment]
Looking at some Youtube video about InSot, it seems to me that InShot when importing the video extract a low resolution image of every ~200ms. They can then "seek" by replacing the preview by whatever image is at this timestamp.
It doesn't seem like they seek in the actual video.

**Comment by krocard** [comment]
You might be able to do something similar by transcoding the video to a very low framerate (to save disk space and have a faster import) of only keyframes. ExoPlayer should then be able to seek virtually instantaneously in the content. make sure to not actually play the video but keeping it paused.
If the user presses play, switch to the original content at that position.

**Comment by ZeroOneZeroR** [comment]
Thank you for the suggestions. I will try this.

**Comment by missu263** [comment]
> Thank you for the suggestions. I will try this.

hi , I also find this problem that seek is not immediately , but the video-edit app can do this , whatever seek position ,the frame-image display without any delay and play smoothly 

so , do you have any ideas about the video-edit app solutions? 

wish you reply t_t

**Comment by krocard** [comment]
@missu263 as I explain in https://github.com/google/ExoPlayer/issues/8671#issuecomment-790474583 there are multiple ways to accelerate seeking. I can't now which ones the video-edit app you have in mind use.

Closing as the original question has been answered.

**Comment by missu263** [comment]
@krocard as you mentioned in comment https://github.com/google/ExoPlayer/issues/8671#issuecomment-790474583 , I think that it's fit for player .  but in video-edit scene  it will be a delay-operation . what I  used video-app is  剪映  . 

Mediacodec decode must feed a complete GOP, in this case , i want to decode a fame (any position) ,I have to seek to previous I-Frame  first, then decode every frame until to the frame that I want. 

so when i seek to any position , what i can do is waiting decoding from previous sync-frame .  I play a video that 20 seconds an I-Frame     

i mean is when I seeking , how avoiding waiting .....

wish you replay :)

**Comment by krocard** [comment]
I'm not sure to understand your question. To decode a frame, all dependent frames must be decoded first. Eg. to decode a P frame all previous P frames up to the last I frame need to be decoded first. This is unavoidable. That is why ExoPlayer feeds all frames from the last iframe to the decoder [1].

As listed in https://github.com/google/ExoPlayer/issues/8671#issuecomment-790474583, your app could rencode the media to have more frequent I frames to mitigate the wait.

[1] I don't think ExoPlayer avoids feeding non dependent frames between the last I frame and the target frame (eg skip b frames). @andrewlewis would know.

**Comment by andrewlewis** [comment]
> [1] I don't think ExoPlayer avoids feeding non dependent frames between the last I frame and the target frame (eg skip b frames). @andrewlewis would know.

Sounds right.

I think the only thing ExoPlayer currently 'knows' about the reference structure (dependencies between frames) is which samples are synchronization samples, and for exact seeking we already use this information to avoid decoding previous GOPs. (Side note: it is also used to drop frames up to a keyframe when the video renderer is far behind the playback position as a way to catch up more quickly.) We don't parse/use finer-grained information to skip processing frames that won't be displayed or used as reference.

**Comment by missu263** [comment]
@krocard @andrewlewis 
thanks a lot ! It's my honor to receive your comments . 谢谢！
