### ISSUE TITLE
Cache that uses only one file

### ISSUE THREAD

**Issue by krottv** [google/ExoPlayer#8681]
I am developing a video editor app. We have functionality to present remote audio library.

When user plays tracks they get cached. Ok, exoPlayer does a good job here.

Then we have an option to take the track and use it later as audio for video rendering. For adding audio to a video first the audio should be local (I use MediaExtractor). 

Unfortunately, exoPlayer cache works by creating many files. Is it possible to cache audio only to one file so it can be read later for encoding/decoding as a part of video?

Right now the only solution is to redownload the audio as a whole file, but it is weird to do so.

**Comment by krocard** [comment]
@marcbaechinger Is there an easy way to recover the cache media without playing it to be consumed by a third-party audio library?

**Comment by marcbaechinger** [comment]
If the file is completely in the cache, I think it should be possible to create a `CacheDataSource` with the cache and then use the API of `DataSource` to read from it. The `CacheDataSource` finds everything in the cache and returns the byte until the end of the input is reached. I haven't tried but this is what the player does as well I think.

**Comment by marcbaechinger** [comment]
A user just added some code that reads from a CachedDataSource. In that case the stream is not yet completely downloaded but for the use case here, when we are sure that everything is downloaded already, this should work the same without accessing the upstream data source. 

Please see #8645
