### ISSUE TITLE
ImaSdk extension shows orange border when ad is played on TV

### ISSUE THREAD

**Issue by GrilloLuca** [google/ExoPlayer#8685]
Hi, i've found an issue in androidTV. 
i can simulate the issue in a google chromecast.
When an ad is played, with ImaSdk extension, Exoplayer shows an orange border all over the TV screen.

Steps to reproduce the issue

1. launch the demo app on google chromecast
2. open "IMA Sample ad tags" menu
3. open "Single inline linear"
4. you can show the border around the sample ad. Also, clicking the down arrow of the remote, the border is moving in the exo ad overlay.

- ExoPlayer version number: 2.13.x
- Android device Google Chromecast on a phisical TV

![photo_2021-03-08_12-19-43](https://user-images.githubusercontent.com/6304568/110314840-b1710580-8008-11eb-90e8-7c3f44758de6.jpg)
![photo_2021-03-08_12-19-43 (2)](https://user-images.githubusercontent.com/6304568/110314845-b2099c00-8008-11eb-8f94-4d5705462fba.jpg)

**Comment by antoniovillanova** [comment]
Can confirm it's happening also on NVIDIA SHIELD.

**Comment by andrewlewis** [comment]
I think this is the visual indicator of where the UI focus is, so it's probably working as intended.

If you don't want to focus the ad overlay UI you could try passing false to `ImaAdsLoader.Builder.setFocusSkipButtonWhenAvailable`.

**Comment by andrewlewis** [comment]
See also #8565 if you want to be able to focus the skip button after turning off the automatic focus behavior.
