### ISSUE TITLE
Wrong path to .ts file in HLS Live Stream (Solved!)

### ISSUE THREAD

**Issue by plitaev** [google/ExoPlayer#8689]
Hi there!

Today, I ran into a technical problem-Exoplayer could not open HLS stream from webcam because player create a wrong URI in GET query to .ts file after m3u8 loading.

I give to a player m3u8 link with token and filename like http://MY_IP_ADDRESS:20200/streaming?token=SoXAreIBouxi0EkifWe9crkncUWzQgFz&filename=playlist.m3u8

And next player needs a .ts file from URI like http://MY_IP_ADDRESS:20200/streaming?token=SoXAreIBouxi0EkifWe9crkncUWzQgFz&filename=segment_013.ts

But player create wrong URI: /segment_013.ts and got 404 error.

Screenshots in attachments

How can I shape the right path for .ts file?

**Comment by plitaev** [comment]
![1](https://user-images.githubusercontent.com/31280583/110416418-47b73100-80c6-11eb-9053-d0db51dd9b95.jpg)
![2](https://user-images.githubusercontent.com/31280583/110416432-4e45a880-80c6-11eb-8c01-79b8b64432c7.jpg)

**Comment by tonihei** [comment]
It would be helpful if you cold provide an example playlist with the path where you hosted it and the expected path of the segments. It's likely the playlist is not configured correctly. 

Aside: Please provide the file contents and any other information as text in the reply instead of posting a screenshot photo.

**Comment by plitaev** [comment]
I solved the problem using the dataSpec.withUri method in ResolvingDataSource.Factory

Build is here: https://github.com/plitaev/ExoPlayerHlsWithCustomTsPath

In PlayerActivity: https://github.com/plitaev/ExoPlayerHlsWithCustomTsPath/blob/master/app/src/main/java/plita/me/exoplayerhlswithcustomtspath/PlayerActivity.java
