### ISSUE TITLE
what ratio between the skipoffset and Duration?

### ISSUE THREAD

**Issue by sajjadshahbazi** [google/ExoPlayer#8694]
I'm using ImaAdsLoader with version 2.12.0.
when skipoffset is equal to 1 Second and Duration is 7 Second can't skip the ad and I must watch all ad. but when that skipoffset is equal to 4 Second and Duration is 10 Second, can skip the ad.
what ratio between the skipoffset and Duration?

**Comment by andrewlewis** [comment]
I think this behavior is controlled purely by the IMA SDK so please ask on their [support forum](https://groups.google.com/g/ima-sdk). Feel free to reply here and reopen if this is actually about some IMA extension-specific behavior.
