### ISSUE TITLE
How to use audio AC3 pass-through mode？

### ISSUE THREAD

**Issue by arlimm318** [google/ExoPlayer#8697]
How to get MediaCodec to not decode AC3, but to play through to support TV.
My device is Android 4.4.

**Comment by andrewlewis** [comment]
HDMI audio passthrough support was added in Android 5.0 (API 21) so I'm afraid this isn't supported. See the minimum API version listed for [`ENCODING_AC3`](https://developer.android.com/reference/android/media/AudioFormat#ENCODING_AC3).
