### ISSUE TITLE
引入“LibRtmp-Client-for-Android”库，播放rtmp直播流，页面闪退也没有日志，当前exoplayer版本为：2.11.7

### ISSUE THREAD

**Issue by QinLei1** [google/ExoPlayer#8698]
![image](https://user-images.githubusercontent.com/24694778/110598311-934c0680-81bc-11eb-9a91-b45a5dbdd32b.png)

**Comment by tonihei** [comment]
Please provide complete reproduction steps as explained in the issue template. Thanks.
