### ISSUE TITLE
Support Common Media Client Data (CMCD) 

### ISSUE THREAD

**Issue by tonihei** [google/ExoPlayer#8699]
CMCD is a new standard that allows player clients to report some state to the CDN to allow the CDN to improve delivery performance (see https://cdn.cta.tech/cta/media/media/resources/standards/pdfs/cta-5004-final.pdf).

Implementing this with ExoPlayer is currently difficult as the necessary information needs to be available on the playback thread at the point where the request is generated. This issue is tracking two things:
 1. Making sure the necessary hooks are available to forward all required information to the chunk sources that generate the requests. 
 2. Providing an opt-in implementation of CMCD.

**Comment by wilaw** [comment]
Request around opt-in API structure and API methods:

1. Have CMCD be default off, to protect privacy and information leakage. 
2. Be able to activate it easily through single API call. This activation would turn on all available keys.
3. Be able to apply a separate filter list to explicitly enable certain keys. Only keys whitelisted by the filter would be sent. 
4. Have an API method to enable setting the 
     1. ContentID value.
     2. RTP value, both as a fixed threshold and also as a multiple of encoded bitrate.
     3. Custom keys - accepting both a key and value arguments.

**Comment by beka-discovery** [comment]
Any updates on CMCD support?

**Comment by pankaj-giter** [comment]
From Disney Streaming, we are interested to see this support in Exo Player given the performance and other benefits we will see. 

Any updates on the timeline for supporting CMCD will be great.

**Comment by sdaub** [comment]
Starz has also been looking into CMCD for our apps.  Having support in ExoPlayer would give us a much stronger business case for taking it up internally. 

It would be great to see this added to an upcoming release.

**Comment by nicoweil** [comment]
At AWS we see more and more customers asking us to support CMCD at the CDN level, as this is a key enabler for content steering (aka multi-CDN switching) and QoE improvements in general. We cannot do that without the cooperation of the player ecosystem, and that's where ExoPlayer footprint becomes decisive. Thanks in advance for adding CMCD support to a future release!

**Comment by fisherinnovation** [comment]
Vimeo has been activly working with CMCD data in our web playback systems and would love to see support in our mobile application video players as well. +1 to this request!

**Comment by tonihei** [comment]
This is still on our agenda and thanks for reiterating your interest. We'll post updates here once we have the implementation ready.

**Comment by acbegen** [comment]
I would like to make comments with my two different hats:
1) First with my academic hat, we published two papers already showing the benefits of CMCD (and CMSD) in two different ACM conferences. There is also a paper published in the IEEE Communications Magazine. These are getting pretty good traction as many researchers in the field believe that CMCD/CMSD will bring us much anticipated capabilities. Expect more studies/papers on this topic. See some examples at: https://ali.begen.net/current.php
2) With my Comcast hat, we expect to roll out CMCD support on the RDK client (which runs millions of settops not just for Comcast but for all syndication partners including all major cable operators in North America).

**Comment by mayursfox** [comment]
From FOX, we are interesting in seeing CMCD support in ExoPlayer as we believe this will be a key feature for monitoring QoE and for steering QoE improvements. We're actively engaged on enabling CMCD across other platforms in our ecosystem, would love to get an update on when ExoPlayer would offer support.

**Comment by beka-discovery** [comment]
Warner Bros Discovery. 

We are looking for integrating CMCD into our playback platforms. We are very pleased that Shaka Player, Dash.js, and Roku players already have rolled out CMCD support.

Currently, I’m not aware of any good way of narrowing down Rebuffering cases without correlating Playback session to CDN logs/state.
CMCD support on ExoPlayer is highly appreciated. Since ExoPlayert is the most Player Engine in the Android ecosystem.

**Comment by dsparacio** [comment]
From Paramount Streaming's perspective, we are also very interested in seeing CMCD implemented for Exo.  

We have full support for this across all web. Our team at Paramount has implemented  the CMCD spec in HLS.js and Google Shaka Player.  There is also an implementation in Dash.js.  So, the most popular open source projects for web have it this feature in prod today. It would be nice to have cross platform support for CMCD. Let us know if you are looking for contributors for this feature.

**Comment by haudiobe** [comment]
Broad support for CMCD is important. If Exoplayer adds CMCD; it will stay important - we are supportive of this feature.

**Comment by seanmccarthy1992** [comment]
+1 from Paramount's perspective, our goal is to offer a standardized data set for operations teams to troubleshoot playback issues. A subset of our players now have the rich CMCD data set which makes debugging last-mile and CDN issues more timely and enables us to get to root cause faster. It would be great if this data was provided across our native player platform stack as well.

**Comment by zen-tek** [comment]
Datazoom has been leveraging CMCD and related mechanisms for quite some time to link player QoE + CDN cache log  data for coordinate analysis. We're also leveraging it for experimentation with distributed request tracing across the streaming content delivery pipeline. This overlaps with our efforts within the Streaming Video Alliance. In general, we see CMCD as valuable observability tool that every player should seek to support. Support for CMCD in Exoplayer would be a huge step forward.

**Comment by tonihei** [comment]
Just repeating what I already mentioned above: We are aware that there is a wide interest in this feature and we also understand why it is important to many of you. It's definitely on our agenda and we'll update this issue with commits and comments once we have them. 

If you have a concrete implementation idea, we are also open to accept PRs. The request parameters can be extended in either `DefaultDashChunkSource`/`HlsChunkSource` at the point where we generate the original `DataSpec`, or by a variant of a `ResolvingDataSource` that amends existing requests before sending them (the former sounds more promising). In any case, the complicated part is to make sure all the relevant information is available. If you are thinking about sending a PR that isn't maintained in a small section of the code, it's worth providing a design document first to allow a better discussion of the approach. Once we know the right way to implement this, merging code changes becomes a lot simpler.

**Comment by totallyunknown** [comment]
Has anyone looked into https://github.com/realeyes-media/cta-wave-cmcd-lib? They said that's a reference implementation for CMCD on Exoplayer.

**Comment by tonihei** [comment]
This implementation looks as if it might not achieve its purpose very well at the moment as the necessary player state information is obtained with a delay to when it's used to fill the request parameters. For example, a buffer starvation or startup after seek would not show up in the relevant next request, but only one request later. This isn't really something they could have easily solved though and it nicely shows that implementing this correctly needs some integration in the player itself and can't be done from the outside.

**Comment by rohitjoins** [comment]
Hi Everyone, 

Thank you for your patience. We have added CMCD support in ExoPlayer. Please see the [doc](https://developer.android.com/guide/topics/media/exoplayer/cmcd) on how to enable CMCD. 

Timeline of changes made:

- [Release 1.1.0](https://github.com/androidx/media/releases/tag/1.1.0): Added support to enable CMCD with fields bitrate (`br`), buffer length (`bl`), content ID (`cid`), requested maximum throughput (`rtp`), and session ID (`sid`).
- [Release 1.1.1](https://github.com/androidx/media/releases/tag/1.1.1): Added additional fields: streaming format (`sf`), stream type (`st`), version (`v`), top birate (`tb`), object duration (`d`), measured throughput (`mtp`) and object type (`ot`)
- Upcoming Release 1.2.0(available in [main](https://github.com/androidx/media/tree/main) branch): Remaining fields added: buffer starvation (`bs`), deadline (`dl`), playback rate (`pr`), startup (`su`),  next object request (`nor`) and next range request (`nrr`). Also added functionality to transmit CMCD data using query parameters.

We look forward to your feedback. Have a nice weekend!

**Comment by icbaker** [comment]
For those wanting to experiment without building from the `main` branch, [1.2.0-alpha01](https://github.com/androidx/media/releases/tag/1.2.0-alpha01) is also already available, and contains support for buffer starvation (`bs`), deadline (`dl`), playback rate (`pr`) and startup (`su`). The remaining keys mentioned above will be available in the next 1.2.0 pre-release.

**Comment by rohitjoins** [comment]
[1.2.0](https://github.com/androidx/media/releases/tag/1.2.0) has been released, incorporating support for CMCD including all fields. Kindly share your feedback regarding this integration.
