### ISSUE TITLE
Support formatted WebVTT subtitle

### ISSUE THREAD

**Issue by kientux** [google/ExoPlayer#870]
Is there anyway to enable format for WebVTT subtitle? I mean subtitle like `<i>This is a sample</i>`. They're displayed as plain text.

**Comment by kientux** [comment]
I just change a piece of code in `CuePainter.draw(...)`

```
if (!applyEmbeddedStyles) {
    // Strip out any embedded styling.
    cueText = cueText.toString();
} else {
    cueText = Html.fromHtml(cueText.toString());
}
```

and now subtitle is displayed with proper format (at least with supported html tags).

**Comment by ojw28** [comment]
You're right - this isn't currently supported. We (annoyingly) support styling but not positioning for TTML, and positioning but not styling for WebVTT. We plan to add styling support to WebVTT and positioning support to TTML this quarter.

**Comment by kientux** [comment]
Glad to hear that, this really is a good library, I following your progress from the beginning and it's getting better every day. I will use the temporary fix above for the time being.

**Comment by ojw28** [comment]
I believe support was added in https://github.com/google/ExoPlayer/commit/1a9b2be5510bd9698c90aeaaa28a9e1ba965c0a6.

**Comment by kientux** [comment]
Thank you, it works fine.
