### ISSUE TITLE
URGENT: ExoPlayer freezing after ad break 

### ISSUE THREAD

**Issue by axalam9** [google/ExoPlayer#8700]
We are currently facing an issue on all Android platforms utilizing ExoPlayer. As soon as the video goes into a midroll, the ad break plays fine but coming out of the ad break back into content, the player freezes with no error whatsoever. This has been replicated with both production and test ads. 

The steps to reproduction are the following:
1. Download sample app from here: https://drive.google.com/file/d/1wrmRAYlpTIfUQvZ_DlmmQ8n7VSlLBhgs/view?usp=sharing
2. Play the last content in the list "Semi Final Vuelta...."
3. Watch the pre-roll play
4. As soon as content starts playing, scroll to about the 10:30 minute mark
5. Let the content play naturally and wait for midroll
6. Let midroll play 
7. See the content freeze and playback stalls

Here is a Charles log of the issue:
https://drive.google.com/file/d/1xjDGxzXK51jvN9jX-U6ccp73hpW2d_D2/view?usp=sharing

As well as a video showing the issue:
https://drive.google.com/file/d/1mxzOCTr5AP0zvX3Lz8sjXDIHSAagofXe/view?usp=sharing

This issue was replicated on Android Studio Emulator running Android R. It is also easily reproducible on hardware devices. 

The manifest being used is the following:
https://storage.googleapis.com/trumantest-public/hls-content/univision-Semifinal-Vuelta-Apertura/master-6e5253cb-91c0-4e92-a2bd-c68c6fb35ada.m3u8

The production content has encryption on it but we removed encryption in order to eliminate it playing a role in the freeze

**Comment by ojw28** [comment]
Let's use [Internal ref: b/181999437] for this. Closing the public issue.
