### ISSUE TITLE
BuildConfig.USE_DECODER_EXTENSIONS not found

### ISSUE THREAD

**Issue by newtestpage** [google/ExoPlayer#8701]
Hi 
when I tried to use DemoUtil class on my app I faced problem with BuildConfig.USE_DECODER_EXTENSION  and I got this error 👍 Cannot resolve symbol 'USE_DECODER_EXTENSIONS'

could you help me to solve this problem ?

**Comment by tonihei** [comment]
This value is auto-generated by our gradle config. See https://github.com/google/ExoPlayer/blob/4364b9150f236813a2070fc79d3bcb76e11969ac/demos/main/build.gradle#L58

So if you copied `DemoUtil` to your project, you need a similar setup or just set the value to whatever you prefer.
