### ISSUE TITLE
CC708 subtitle display issue with multiple windows in different priority

### ISSUE THREAD

**Issue by fred0426** [google/ExoPlayer#8704]
I play a stream with CC708 subtitle on Exoplayer 2.13.1.  The CC708 subtitle can NOT be displayed correctly with multiple windows that have different window priorities.  Please see the below picture.
![CC708 issue](https://user-images.githubusercontent.com/80472661/110820760-4f720380-8287-11eb-96f3-fc3b9dfd5289.png)

I found one line code is incorrect in Cea708Decoder class:
```java
    Collections.sort(
        displayCueInfos,
        (thisInfo, thatInfo) -> Integer.compare(thisInfo.priority,thatInfo.priority));
```
should be changed to :
```java
    Collections.sort(
        displayCueInfos,
        (thisInfo, thatInfo) -> Integer.compare(thatInfo.priority,thisInfo.priority));
```
So the sort is descending order, not ascending order. Thanks.

**Comment by icbaker** [comment]
Thanks for reporting this, I agree this is wrong, section 8.4.2 of the CEA-708B spec says (emphasis mine):
> A higher priority **(with 0 being the highest and 7 being the lowest)** displayed window will overlap lower priority displayed windows on the screen.

I'll send a fix.

**Comment by icbaker** [comment]
Interestingly this also reveals an implicit assumption that the order of `Cue` objects passed to `TextOutput.onCues` indicates the order they should be drawn on the screen.

That should probably be more clearly documented on the `TextOutput` interface.
