### ISSUE TITLE
Views from exo_playback_control_view not working as before with new version of Exoplayer

### ISSUE THREAD

**Issue by darrinps** [google/ExoPlayer#8706]
Please refer to https://github.com/google/ExoPlayer/issues/8588

This is identical to that one which was closed. 

Before, the issue was several parts of the exoplayer library were being depended on. 

This time, only the core library is brought and the problem is showing up again.

In short, you cannot grab a a view using findViewById  in the Activity holding Exoplayer as you used to be able to do.

For example (which is also the same as issue 8588):

`    implementation 'com.google.android.exoplayer:exoplayer:2.13.1'
`

The layout for Exoplayer holds that view:

`?xml version="1.0" encoding="utf-8"?>

<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
              xmlns:tools="http://schemas.android.com/tools"
              android:layout_width="match_parent"
              android:layout_height="wrap_content"
              android:layout_gravity="bottom"
              android:layoutDirection="ltr"
              android:background="#CC000000"
              android:orientation="vertical"
              tools:targetApi="28">

    <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:gravity="center"
            android:paddingTop="4dp"
            android:orientation="horizontal">

        <ImageButton android:id="@id/exo_prev"
                     style="@style/ExoMediaButton.Previous"
                     android:visibility="gone"
                />

        <ImageButton android:id="@id/exo_rew"
                     style="@style/ExoMediaButton.Rewind"/>

        <ImageButton android:id="@id/exo_play"
                     style="@style/ExoMediaButton.Play"/>

        <ImageButton android:id="@id/exo_pause"
                     style="@style/ExoMediaButton.Pause"/>

        <ImageButton android:id="@id/exo_ffwd"
                     style="@style/ExoMediaButton.FastForward"/>

        <ImageButton android:id="@id/exo_next"
                     style="@style/ExoMediaButton.Next"
                     android:visibility="gone"
                />

        <ImageButton android:id="@+id/slowMo"
                     android:layout_width="wrap_content"
                     android:layout_height="wrap_content"
                     android:layout_marginStart="10dp"
                     android:background="@drawable/ic_slow_motion_white_48dp"
                     android:visibility="gone"
        />

        <Button android:id="@+id/editButton"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginStart="20dp"
                android:text="@string/edit"
                android:visibility="gone"
                />

        <ImageButton android:id="@+id/backButton"
                     android:layout_width="wrap_content"
                     android:layout_height="wrap_content"
                     android:layout_marginStart="20dp"
                     android:background="@drawable/ic_arrow_back_white_48dp"
                     android:visibility="gone"
        />

    </LinearLayout>

    <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginTop="4dp"
            android:gravity="center_vertical"
            android:orientation="horizontal">

        <TextView android:id="@id/exo_position"
                  android:layout_width="wrap_content"
                  android:layout_height="wrap_content"
                  android:textSize="14sp"
                  android:textStyle="bold"
                  android:paddingStart="4dp"
                  android:paddingEnd="4dp"
                  android:includeFontPadding="false"
                  android:textColor="#FFBEBEBE"/>

        <com.google.android.exoplayer2.ui.DefaultTimeBar
                android:id="@id/exo_progress"
                android:layout_width="0dp"
                android:layout_weight="1"
                android:layout_height="26dp"/>

        <TextView android:id="@id/exo_duration"
                  android:layout_width="wrap_content"
                  android:layout_height="wrap_content"
                  android:textSize="14sp"
                  android:textStyle="bold"
                  android:paddingStart="4dp"
                  android:paddingEnd="4dp"
                  android:includeFontPadding="false"
                  android:textColor="#FFBEBEBE"/>

    </LinearLayout>

</LinearLayout>`

Then in the Activity that uses the Exoplayer:

`            val editButton = this.findViewById<Button>(R.id.editButton)
`

Here editButton will be null.

This is the same thing that was happening in issue 8588 which was closed.

**Comment by darrinps** [comment]
Also note that, as before, I tried:

`val editButton = binding.playerView.findViewById<Button>(R.id.editButton)`

That didn't work either.

How can I grab the buttons defined in exo_playback_control_view? Has the way this is to be done changed?

**Comment by darrinps** [comment]
Also note that I updated to 2.13.1 but the problem remains.

`    implementation 'com.google.android.exoplayer:exoplayer:2.13.1'
`

**Comment by darrinps** [comment]
Could this somehow be conflicting with YoutubePlayer?

I introduced YoutubePlayer into the app about the same time I noticed this problem. Could it be that it is using old versions of ExoPlayer which might cause this same issue to manifest itself?

**Comment by darrinps** [comment]
I may have a way to get this to work. 

I added the controller layout explicitly like this:

`    <com.google.android.exoplayer2.ui.PlayerView
            android:id="@+id/playerView"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:keepScreenOn="true"
            app:controller_layout_id="@layout/exo_playback_control_view"
            />
`

Doing that, I'm now able to get the button back. 

I didn't used to need to do that. Not sure what changed.

**Comment by tonihei** [comment]
@ojw28 Could you take a look? You worked on #8588 originally, so I assume you have the most context.

**Comment by ojw28** [comment]
> Could this somehow be conflicting with YoutubePlayer? I introduced YoutubePlayer into the app about the same time I noticed this problem. Could it be that it is using old versions of ExoPlayer which might cause this same issue to manifest itself?

I think you're in a much better position than we are to test this theory, since you can simply try before and after the change in your app where you did this.

As per the previous issue, if you're still able to reproduce this, please provide a minimal reproducible example, as source code, that demonstrates the problem.

**Comment by darrinps** [comment]
I can try to create a demo of sorts, but before I go to that extent, is it recommended to normally do what I ended up doing as a work around from the start?

In other words, should we, not just can we, explicitly mark the layout like this?

app:controller_layout_id="@layout/exo_playback_control_view"

That doesn't seem overly intrusive to ask of a developer and as long as it doesn't hurt anything, this is probably the easiest thing to do rather than updating YoutubePlayer (assuming it is at issue).

**Comment by ojw28** [comment]
Ah. I think your problem is actually that your layout file isn't being used at all, but perhaps this is not obvious because your application is crashing before you get to the point where you can see what the UI looks like :).

If your layout file is currently called `exo_playback_control_view.xml`, I think you need to rename it to `exo_player_control_view.xml`, and then things should work without you having to specify `app:controller_layout_id`.

ExoPlayer has loaded from `exo_player_control_view.xml` for quite a long time now, but I think it probably used to alias `exo_playback_control_view.xml` for backward compatibility, and no longer does so. The reason specifying `app:controller_layout_id` fixes it is just that it points ExoPlayer to the right layout file.

Does that help? Sorry for the confusion!

**Comment by darrinps** [comment]
That did it!!!!! 

Thanks so much! 

The tutorials I looked at were calling it by the old name. Hopefully this will help other people out!
