### ISSUE TITLE
exoplayer version 2.13.2 got only audio without picture when play stream Silent_Movie_200_AC4_H264_DVB_25fps.ts

### ISSUE THREAD

**Issue by AndyYoung1004** [google/ExoPlayer#8708]
when I use ExoPlayer demo app to playback Silent_Movie_200_AC4_H264_DVB_25fps.ts
only audio is played,screen is black,and it is 100% reproduceable on all Android version.
I tried P,Q,R and got the same result,please help to check this issue

- ExoPlayer version number : 2.13.2
- Android version : P Q R
- Android device : oppo Findx2/reno3 pro/reno4 pro/reno5 pro,all oppo phones

[Silent_Movie_200_AC4_H264_DVB_25fps.zip](https://github.com/google/ExoPlayer/files/6128206/Silent_Movie_200_AC4_H264_DVB_25fps.zip)

**Comment by tonihei** [comment]
Kim, could you take a look why the video samples are not shown? In works in other players like VLC, so there is definitely video data in the file, and ExoPlayer's event logger also detects it as AVC and claims it is supported.

**Comment by kim-vde** [comment]
The problem is that the stream does not contain any access unit delimiters. You should set FLAG_DETECT_ACCESS_UNITS, as indicated [here](https://exoplayer.dev/troubleshooting.html#why-do-some-mpeg-ts-files-fail-to-play).

**Comment by AndyYoung1004** [comment]
thank kim & tonihei,it works now
