### ISSUE TITLE
Spaces in media URLs are not handled by Exoplayer

### ISSUE THREAD

**Issue by SiimSaksing** [google/ExoPlayer#871]
We have a media that contains spaces in its path, for example:
> .../Axinom/Axinom_Media/Encrypted/Media Final-360-800k_dashinit.mp4

When starting playback, we get this:
> 10-16 10:13:26.517 2589-2589/com.axinom.player.exoplayer E/BasePlayerController: onLoadError: Response code: 400
> 10-16 10:13:26.527 2589-2589/com.axinom.player.exoplayer I/writeToLog: Adding text to log: BasePlayerController - player error: onLoadError: Response code: 400
> 10-16 10:13:26.527 2589-2589/com.axinom.player.exoplayer D/FileUtils: BasePlayerController - player error: onLoadError: Response code: 400
> 10-16 10:13:26.537 2589-2589/com.axinom.player.exoplayer E/BasePlayerController: onLoadError: Response code: 400
> 10-16 10:13:26.537 2589-2589/com.axinom.player.exoplayer I/writeToLog: Adding text to log: BasePlayerController - player error: onLoadError: Response code: 400
> 10-16 10:13:26.537 2589-2589/com.axinom.player.exoplayer D/FileUtils: BasePlayerController - player error: onLoadError: Response code: 400

Could you please fix in a way that playback is not affected by the characters used in URLs?

**Comment by jeoliva** [comment]
That's not really a problem with Exoplayer, but with url itself. You have to url encode your url, replacing spaces with its ascii equivalent codification (%20). So, taking as an example your url, it would be:


You can read more about this in RFC 1738 (http://www.ietf.org/rfc/rfc1738.txt, page 2). 

.../Axinom/Axinom_Media/Encrypted/Media%20Final-360-800k_dashinit.mp4

**Comment by ojw28** [comment]
As above. See a previous discussion [here](https://github.com/google/ExoPlayer/issues/727), and @jeolivia's link above (note that spaces in URLs are deemed unsafe by the RFC).
