### ISSUE TITLE
2.13.2 no call to AnalyticsListener.onAudioSessionIdChanged

### ISSUE THREAD

**Issue by AndreasVogelfrei** [google/ExoPlayer#8712]
- ExoPlayer version number: 2.13.2 (using demo project)
- Android version: 11
- Android device: Xiaomi Mi A2

Using your demo project.
Playing: Misc -> Google Play (MP3)

Expected behavior:
 - AnalyticsListener.onAudioSessionIdChanged should be called when playing audio stream

Current behavior:
 - No call to AnalyticsListener.onAudioSessionIdChanged 

Occurance rate:
 - 100%

Current workaround:
 - Call ExoPlayer.getAudioSessionId() when receiving AnalyticsListener.onAudioInputFormatChanged

**Comment by ojw28** [comment]
This is a deliberate change in behavior, as outlined in the 2.13.0 release notes:

> Audio:
> * Fix handling of audio session IDs (#8190). SimpleExoPlayer now generates an audio session ID on construction, which can be immediately queried by calling SimpleExoPlayer.getAudioSessionId. The audio session ID will only change if application code calls SimpleExoPlayer.setAudioSessionId.
> * Replace onAudioSessionId with onAudioSessionIdChanged in AudioListener and AnalyticsListener. Note that onAudioSessionIdChanged is called in fewer cases than onAudioSessionId was called, due to the improved handling of audio session IDs as described above.

In short, unless you change the session ID yourself, it will not change. You can query it immediately after building the player using `getAudioSessionId`.
