### ISSUE TITLE
Is it possible to use the ExtractorRendererBuilder from the Demo with Widevine protection ?

### ISSUE THREAD

**Issue by matt-hub** [google/ExoPlayer#872]
Hello,
I would like to make my own renderer able to read video (progressif download like wmv) content with Widevine protection. Is it possible with the ExoPlayer ?

If yes, can I have some help please ?

Regards, Thanks in advance

**Comment by ojw28** [comment]
I'm unsure what the question is here, since ExtractorRendererBuilder isn't used for HLS, which uses HlsRendererBuilder. Is this about HLS or something else?

Either way, we currently support Widevine only for DASH and SmoothStreaming with fragmented mp4 (and webm in the case of DASH).
