### ISSUE TITLE
Following the instructions for "Hello world!" results in multidex error

### ISSUE THREAD

**Issue by dturner** [google/ExoPlayer#8721]
If you follow the [Hello world! instructions](https://exoplayer.dev/hello-world.html) to add ExoPlayer to a new empty project in Android Studio you will receive the following error: 

```Cannot fit requested classes in a single dex file (# methods: 72119 > 65536)```

It appears that adding ExoPlayer pushes the APK over the dex method limit. 

Steps to reproduce
- Create a new "empty activity" project in Android Studio (4.1.2)
- Add ExoPlayer to the project according to the instructions here (essentially add a `PlayerView` in `activity_main.xml` and a `SimpleExoPlayer` in `MainActivity`)
- Build the project

Expected outcome
- Project builds and runs successfully

Actual outcome
- Project build fails with the error "Cannot fit requested classes in a single dex file (# methods: 72119 > 65536)"

Workaround
- Add `implementation 'androidx.multidex:multidex:2.0.1` to `build.gradle`
- Add `multiDexEnabled = true` under the `defaultConfig` block

Proposed solution
- Update the Hello World! documentation. I propose adding a section under "Turn on Java 8 support" titled "Turn on MultiDex support" which includes the above instructions, and maybe a short explanation of why this is necessary.

**Comment by AquilesCanta** [comment]
Oops sorry, missed this.

**Comment by AquilesCanta** [comment]
I'm unable to reproduce the issue myself, but I think it might be worth adding to the documentation anyway. I'll send a CL your way and we can go from there.
