### ISSUE TITLE
Low latency AudioProcessor

### ISSUE THREAD

**Issue by ryanheise** [google/ExoPlayer#8722]
I'm trying to build an audio processor to adjust the left/right stereo volumes independently in real time. Currently I've observed a 500ms lag from the time I move the volume slider to the time it takes effect. This is the same lag observed when adjusting speed/pitch via sonic.

When trying to lower ExoPlayer's `targetBufferBytes` size, the audio processors will not work unless there is at least 500ms of buffer. Where does this buffer limitation get imposed?

Is there a way of inserting low-latency audio processors later in the pipeline that don't require such large buffers?

**Comment by AquilesCanta** [comment]
@krocard mind taking a look at  this?

**Comment by krocard** [comment]
The easiest way to achieve low latency audio manipulation is to have the platform audio server apply them, not doing it in ExoPlayer.

If you are just trying to adjust the gain of stereo audio,[`AudioTrack.setStereoVolume`](https://developer.android.com/reference/android/media/AudioTrack#setStereoVolume(float,%20float)) might work. Note however that this method is deprecated and only work for two channels. You will need to customize `DefaultAudioSink` or use reflection to access the `AudioTrack`. If you confirm that this work for you, we can think of cleaner way to expose the AudioTrack.

If you want more control over the channels than a simple gain (eg: dynamic range compression) or want to support different channel config than stereo, the best solution is to use the android effect [`DynamicsProcessing`]( https://developer.android.com/reference/android/media/audiofx/DynamicsProcessing). This has the drawback of only being available for API 28+ but does not require any change to ExoPlayer and need only a few dozen line of code.

If you really need to apply the effect in ExoPlayer, then you will need to configure ExoPlayer to use a low latency AudioTrack. This is a highly experimental configuration that ExoPlayer doesn't support out of the box.
Please see point 2 of my comment https://github.com/google/ExoPlayer/issues/8665#issuecomment-789595598 that goes in great detail regarding low latency ExoPlayer audio effects.

**Comment by krocard** [comment]
> This is the same lag observed when adjusting speed/pitch via sonic.

If the default speed pitch latency is an issue, you can enable [`DefaultRenderersFactory.setEnableAudioTrackPlaybackParams`](https://github.com/google/ExoPlayer/blob/b1000940eaec9e1202d9abf341a48a58b728053f/library/core/src/main/java/com/google/android/exoplayer2/DefaultRenderersFactory.java#L266-L284) to thave the platform audio server make the speed/pitch adjustments. It should get rid of virtually all of the latency when adjusting the speed&pitch for API 23+.

**Comment by krocard** [comment]
> When trying to lower ExoPlayer's targetBufferBytes size, the audio processors will not work unless there is at least 500ms of buffer. Where does this buffer limitation get imposed?

What do you mean by "not work"? Does the audio track fails to be created or are you hearing underruns?

**Comment by ryanheise** [comment]
This is the error I got:

```
W/DefaultLoadControl( 2006): Target buffer size reached with less than 500ms of buffered media data.
E/ExoPlayerImplInternal( 2006): Playback error
E/ExoPlayerImplInternal( 2006):   com.google.android.exoplayer2.ExoPlaybackException: Unexpected runtime error
E/ExoPlayerImplInternal( 2006):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:586)
E/ExoPlayerImplInternal( 2006):       at android.os.Handler.dispatchMessage(Handler.java:102)
E/ExoPlayerImplInternal( 2006):       at android.os.Looper.loop(Looper.java:223)
E/ExoPlayerImplInternal( 2006):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal( 2006):   Caused by: java.lang.IllegalStateException: Playback stuck buffering and not loading
E/ExoPlayerImplInternal( 2006):       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1015)
E/ExoPlayerImplInternal( 2006):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:477)
E/ExoPlayerImplInternal( 2006):       ... 3 more
```

Looking through the source, I see this in `DefaultLoadControl`:

```java
    // Prevent playback from getting stuck if minBufferUs is too small.
    minBufferUs = max(minBufferUs, 500_000);
    if (bufferedDurationUs < minBufferUs) {
      isLoading = prioritizeTimeOverSizeThresholds || !targetBufferSizeReached;
      if (!isLoading && bufferedDurationUs < 500_000) {
        Log.w(
            "DefaultLoadControl",
            "Target buffer size reached with less than 500ms of buffered media data.");
      }
    } else if (bufferedDurationUs >= maxBufferUs || targetBufferSizeReached) {
      isLoading = false;
    } // Else don't change the loading state.
```

which I guess partially answers the question of where that limit is coming from.

Then in `ExoPlayerImplInternal` there is this:

```java
      if (!playbackInfo.isLoading
          && playbackInfo.totalBufferedDurationUs < 500_000
          && isLoadingPossible()) {
        // Throw if the LoadControl prevents loading even if the buffer is empty or almost empty. We
        // can't compare against 0 to account for small differences between the renderer position
        // and buffered position in the media at the point where playback gets stuck.
        throw new IllegalStateException("Playback stuck buffering and not loading");
      }
```

> [`AudioTrack.setStereoVolume`](https://developer.android.com/reference/android/media/AudioTrack#setStereoVolume(float,%20float)) might work

From what I've read, it may not be supported anymore on some devices, so I can't use it.

> If the default speed pitch latency is an issue, you can enable [`DefaultRenderersFactory.setEnableAudioTrackPlaybackParams`](https://github.com/google/ExoPlayer/blob/b1000940eaec9e1202d9abf341a48a58b728053f/library/core/src/main/java/com/google/android/exoplayer2/DefaultRenderersFactory.java#L266-L284) to thave the platform audio server make the speed/pitch adjustments. It should get rid of virtually all of the latency when adjusting the speed&pitch for API 23+.

This isn't necessarily my issue, I mentioned it only since it seemed to provide a hint as to the source of the 500ms limitation, but the above is interesting to know nonetheless, thanks.

I do much prefer ExoPlayer's sonic-based time stretching algorithm as it is higher quality for voice. And when using the sonic library directly, I do know that it is also capable of operating at much lower latencies.

> If you really need to apply the effect in ExoPlayer, then you will need to configure ExoPlayer to use a low latency AudioTrack. This is a highly experimental configuration that ExoPlayer doesn't support out of the box.
> Please see point 2 of my comment [#8665 (comment)](https://github.com/google/ExoPlayer/issues/8665#issuecomment-789595598) that goes in great detail regarding low latency ExoPlayer audio effects.

Interesting, thank you! But the 500ms limitation isn't coming from AudioTrack, so even enabling performance mode on the track doesn't seem like it would be enough on its own.

**Comment by krocard** [comment]
> I do much prefer ExoPlayer's sonic-based time stretching algorithm as it is higher quality for voice.

The platform audio framework also uses the Sonic library (the C++ version). You should get the same audio as using ExoPlayer.

> Interesting, thank you! But the 500ms limitation isn't coming from AudioTrack, so even enabling performance mode on the track doesn't seem like it would be enough on its own.

I think you are confusing 2 different buffers in the playback pipeline. Here is a greatly simplified model of the audio playback data pipeline:

`
network stack -[Network buffer]-> Extractor -[SampleQueue]-> decoder -[PreProcessorBuffer]-> AudioProcessors -[PostProcessorBuffer]-> AudioTrack -[AudioTrackBuffer]-> Mixer -[Hw buffer]-> ... Speaker
`
Between every active element, there is a buffer marked with `[]`. Algorithm latency is ignored as it is currently negligible in front of buffer latency for your use-case.

Only buffers after `AudioProcessors` affect the latency of the `AudioProcessors` audio changes.
The `PostProcessorBuffer` is already minimal and cannot be reduced more. The 2 buffers that are responsible for virtually all of the AudioProcessor latency are the `AudioTrackBuffer` and `Hw buffer`. With the `AudioTrackBuffer` being massively bigger, it is your best bet to minimize the `AudioProcessors` latency. Additionally apps have very limited and indirect control over what I called `Hw buffer`.

`targetBufferBytes` controls the size of the `Network buffer`. As this buffer is before `AudioProcessors`, changing its size will not do anything to change the `AudioProcessors` latency.
