### ISSUE TITLE
Player.getCurrentPosition() returns much larger than expected

### ISSUE THREAD

**Issue by GhostFlying** [google/ExoPlayer#8723]
The version:

```
implementation 'com.google.android.exoplayer:exoplayer-core:2.13.2'
implementation 'com.google.android.exoplayer:exoplayer-hls:2.13.2'
```

The way to reproduce:

1. use the repo https://github.com/jbochi/hls-loop to serve or use http://hls-loop.appspot.com/variant.m3u8 as source
2. playback like this 
```
val firstItem = MediaItem.fromUri("http://localhost:5000/variant.m3u8")
mPlayer.addMediaItem(firstItem)
mPlayer.prepare()
mPlayer.videoComponent!!.setVideoTextureView(textureView)
mPlayer.play()
```

3. then print mPlayer.getCurrentPosition every seconds, then u can see the cur position  do not start from 0
![image](https://user-images.githubusercontent.com/4019569/111254674-844bd500-8650-11eb-91be-da02d1842cac.png)

Expected

Player.getCurrentPosition() returned value starts from 0 like MediaPlayer.

**Comment by GhostFlying** [comment]
After dig into the source code, I found that the currentPosition minus the window.defaultPositionMs seems the value with the same meaning of MediaPlayer.

But it seems misleading? Or it should be well-documented.

**Comment by GhostFlying** [comment]
After more experiments, both MediaPlayer and Exo tried to catch up the newest part of the hls playlist, but the MediaPlayer make sure the currentPosition is start from 0 but Exo's currentPosition seems the actually position in current window.

**Comment by hantrungkien** [comment]
@GhostFlying I'm also confused at same case. After Exo throw BLWE then I call seekToDefaultPosition() and prepare() again but like the below image. I'm not really understood.

![photo_2021-03-13_17-25-03](https://user-images.githubusercontent.com/20286370/111338705-b8071900-86a9-11eb-8aa1-cd9e78b16609.jpg)

**Comment by AquilesCanta** [comment]
When the playlist does not specify the start position, the player will start from as close as possible to the live edge, while still following the [spec](https://tools.ietf.org/html/draft-pantos-http-live-streaming-23#section-6.3.3).

getCurrentPosition returns the position in the sliding window. You can make ExoPlayer start from 0 if you want by using an [EXT-X-START](https://tools.ietf.org/html/draft-pantos-http-live-streaming-23#section-4.3.5.2) tag. What is the proposed change here?

**Comment by GhostFlying** [comment]
I have understood the behavior and so the same interface getCurrentPosition means different behavior with MediaPlayer in this situation, right?

**Comment by AquilesCanta** [comment]
> I have understood the behavior and so the same interface getCurrentPosition means different behavior with MediaPlayer in this situation, right?

Yes. MediaPlayer doesn't support seeking in a live window as far as I am aware, so the playback position is only telling you how long playback has been going on (as far as I'm aware). ExoPlayer's getCurrentPosition is documented as:

> Returns the playback position in the current content window

Which is in line with what the seeking functionality does (seeking in the window).
