### ISSUE TITLE
How can I seek to the end of VOD content?

### ISSUE THREAD

**Issue by josraigreen** [google/ExoPlayer#8724]
I'm implementing an app which plays VOD content, and one of requirement is to seek to the end of content for skipping advertisement based on user configuration.

This can be done very easily using **seek** API on exoplayer on the exoplayer version 2.9.4 which I'm currently using on my app.
However, I'm working on upgrading exoplayer version to 2.12.3, and I encountered issue on this version.

I could see seeking to end of content does not move playhead position to end of content directly. Instead, seek position was `end position of content - 1`
This can be checked by below source code.
```
In the code ExoPlayerImplInternal.seekToPeriodPosition

        if (newPlayingPeriodHolder.info.durationUs != C.TIME_UNSET
            && periodPositionUs >= newPlayingPeriodHolder.info.durationUs) {
          // Make sure seek position doesn't exceed period duration.
          periodPositionUs = max(0, newPlayingPeriodHolder.info.durationUs - 1);
        }
```
Above code says seeking position is adjusted by minus 1 when seeks to the end of content.
I checked this logic has been added from the version 2.10

Is there any way to seek to end of content directly without adjustment?
It looks this code was added to avoid seeking to the position exceeds end of content, but why there is minus 1?

**Comment by AquilesCanta** [comment]
Hi @tonihei, mind taking a look at this as part of [Internal ref: cl/300133655]?

**Comment by tonihei** [comment]
If media is played in a playlist, the position at `mediaStartTimeUs + mediaDurationUs` already corresponds to position `0` in the next item in a playlist. So the last possible timestamp in the current media item is `mediaStartTimeUs + mediaDurationUs - 1`. 

Practically speaking, this `-1` shouldn't make a difference at all because there shouldn't be any samples in the media with a timestamps `>= durationUs`. And thus seeking to `durationUs` or `durationUs-1` should always show the last frame of the video. 

Could you describe in more detail what you are seeing and what you expect to see?

**Comment by josraigreen** [comment]
Sorry for very late response.

I have custom scheduler to check the current playhead position every 250 mili-seconds.
Main task for this schedular is to skip advert session. Problem happens with processing post roll.
In general, post roll starts from 15 ~ 30 seconds from the real end of the content.

When I seek to the end, seeking request looks taking time (a few seconds). 
During this time, 

> Playback position from the exoplayer points real end minus 1.
> Custom schedular reports current position to advert provider
> Advert provider triggers advert session events (start and other relevant callbacks)

Last week, I spent time to update custom schedular, and schedular does not report playhead position to advert provider when there is a seek request to the end.

I think we can close this ticket.
Thanks.
