### ISSUE TITLE
request support wav format using offload method to render audio

### ISSUE THREAD

**Issue by AndyYoung1004** [google/ExoPlayer#8727]
as far as I know, the latest exo version supports audio offload output, however,
only mp3 and aac are supported currently, can we support wav ? Android MediaPlayer
now currently supports wav format using offload

**Comment by AquilesCanta** [comment]
Hey @krocard, mind taking a look?

**Comment by krocard** [comment]
The central part of Audio offload is that the audio played is compressed. The hardware is responsible for decompressing it. This allows much bigger buffer between the processor and the DSP, which mean less wakups and less work, which mean less power usage. Read my offload design document for more detail: https://docs.google.com/document/d/1r6wi6OtJUaI1QU8QLrLJTZieQBFTN1fyBK4U_PoPp3g

WAV is a container usually used to store uncompressed (PCM) audio. As such, it is not possible to "offload" it's decoding as there is no decoding to do in the first place.
