### ISSUE TITLE
Drop frame during rendering

### ISSUE THREAD

**Issue by miniesahni1** [google/ExoPlayer#8729]
I am using ExoPlayer for playback in our application. I am facing an issue when rendering pipeline takes more time while applying effects which leads to frame drop. 
If the frame is rendering the "onFrameAvailable" method is not called for the second frame.
I need a suggestion here, what is an ideal way to handle dropped frame in case rendering is taking more time than expected during playback.

**Comment by andrewlewis** [comment]
Does the information in #7439 help?

**Comment by andrewlewis** [comment]
Closing on the assumption that the information in #7439 addressed the problem.
