### ISSUE TITLE
Bottom controls is invisible on video but clickable

### ISSUE THREAD

**Issue by Lewiy** [google/ExoPlayer#8730]
In our project we use videos from camera mp4 format and also convert audio with picture in the same format mp4.  
Example of converted audio - https://cdn1.cander-dev.com/media/videos/2021/03/16/12afed58-65e5-477d-9c74-7b7a3152271e.mp4
All players work correct with this video but ExoPlayer hide controls. It is invisible but clicable. 
Normal videos from camera work fine. See screenshots 
This is bug or i need configure player in right way?
Any ideas? 
Converted video in mp4 (controls are invisible but user can click)
![Screenshot_20210317-103034](https://user-images.githubusercontent.com/15640162/111444105-b1f95280-8712-11eb-9c02-57aee2636199.jpg)
Normal video in mp4 (work correct - controls are shown)
![Screenshot_20210317-103043](https://user-images.githubusercontent.com/15640162/111444109-b291e900-8712-11eb-8076-ab1b91459652.jpg)

**Comment by AquilesCanta** [comment]
> This is bug or i need configure player in right way?

Impossible to know with the given info. Please clarify:
- What ExoPlayer version are you using?
  - Note: If it's not the latest version, please try the latest version.
- Can you reproduce the issue in the ExoPlayer demo app?
  - If you cannot reproduce in the ExoPlayer demo app, can you build a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) for us to reproduce?
