### ISSUE TITLE
Jagged playback on real devices

### ISSUE THREAD

**Issue by anishpsla** [google/ExoPlayer#8732]
I am developing a streaming application using Exoplayer (Xamarin Android). The playback quality is excellent in emulator. But in real devices like Android STB and Mobiles, the quality is not good. The picture is not sharp. Edges look like saw tooth. I am stuck with the problem. Please help.

**Comment by AquilesCanta** [comment]
There's nothing actionable for us with the given information. This doesn't seem related to ExoPlayer. I would advise that you contact the manufacturers of the devices presenting the issues. It would also be a good idea to try your media on the ExoPlayer demo app to check whether you observe the same issues. If you are able to gather evidence pointing at this being an ExoPlayer issue, please fill the [issue template](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md), and I will reopen the issue.

**Comment by anishpsla** [comment]
Thankyou for the quick reply. I solve the issue by adding relatively low quality output ffmpeg encoding command to the existing command for creation of HLS from UDP multicast stream.

`-c:v libx264 -preset ultrafast -profile:v high -crf 20  -c:a aac`

Now picture in sharp and have good viewing experience. The source and result streams are still x264.
