### ISSUE TITLE
jpg image in some chunk of HLS and ExoPlayer's HLS extractor can't play that jpg which triggers error? 

### ISSUE THREAD

**Issue by lavara123** [google/ExoPlayer#8733]
When reporting a bug:
-------------------------
server returning jpg image in some chunk of HLS and ExoPlayer's HLS extractor can't play that jpg which triggers error.

- Test URL:
  - https://v3.xmurowchickrro.tk/m8/DzylYycuoJShoTSlYxWuqTyxLF5CozAyYyIjo24hDF5HnJ1yYxyhYyEbMF5KMKA0YwR5AwthZGN4ZUNhEUIuoNd0zxrT11pz93L2ucL2glpz8hqTfs0xi3vr1

**Error:**
<img width="1659" alt="111504684-33b7a300-8748-11eb-8c81-6a0807538c2d" src="https://user-images.githubusercontent.com/12005386/111509998-5f458800-875e-11eb-8a15-324773755086.png">

- ExoPlayer version 2.13

https://github.com/jhomlala/betterplayer/issues/373#event-4471396862

**Comment by AquilesCanta** [comment]
Thanks for reporting. A fix will be available soon. Next time please make sure you fill the entire issue template that appears when you are going to post the issue.

**Comment by ojw28** [comment]
@AquilesCanta - Is this issue fixed by the commit ref'd above? Thanks!
