### ISSUE TITLE
Can't play audio for HLS

### ISSUE THREAD

**Issue by nguyenthanhduy91** [google/ExoPlayer#8734]
I have link audio https://storage.googleapis.com/as-piepme/1465/livestream/1465.fef238cdc9d9eb0b958d4eb23080e28b/index.m3u8 but I can't play above link, I have tested in Exoplayer demo and it return "source error". Could all you help me?

**Comment by wangear** [comment]
As I analyzed, AdtsExtractor must play. But it didn't play. Because the method of "AdtsExtractor.sniff" return false.

**Comment by AquilesCanta** [comment]
The issue here is identical to #4918. The issue includes instructions on how to work around this issue.
