### ISSUE TITLE
OMX-VDEC-1080P is reported while playing 4K video

### ISSUE THREAD

**Issue by whatisor** [google/ExoPlayer#8735]
Logcat log info which contains TAG OMX-VDEC-1080P while playing 4K video.

Sample:
"2021-03-19 11:06:26.303 838-6455/? E/OMX-VDEC-1080P: [Vidc_PNP]video playback fps:22"

Why is it always 1080P decoder TAG?
Is there something wrong with the configuration?

**Comment by andrewlewis** [comment]
I'm pretty sure this logging is there for legacy reasons and is expected regardless of the input resolution. It doesn't imply there is anything wrong with the configuration and you can ignore it.
