### ISSUE TITLE
Interlaced hls with bt470bg in video

### ISSUE THREAD

**Issue by PoghosyanRoman** [google/ExoPlayer#8738]
Hello, i try to play some interlaced hls lives  with exoplayer, them have different codecs. Both h264/acc but some have  yuv420p(tv, bt470bg, top first) some is  yuv420p(tv, , top first). 
The streams who have  yuv420p(tv, top first) playing normal , streams  yuv420p(tv,bt470bg, top first) stuck on buffering. 
is it normal ?

**Comment by AquilesCanta** [comment]
No, and interlacing (and all video compression details) is almost surely completely unrelated to buffering. If you want us to assist with this, please provide the information required in the [issue template](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md).

**Comment by PoghosyanRoman** [comment]
player init by :

Player is last 2.13.2
Android 9
stb based on amlogic  s905w 

```
 private void Prepare_Player()
    {
        @SuppressLint("WrongConstant") DefaultExtractorsFactory extractorsFactory =
                new DefaultExtractorsFactory()
                        .setTsExtractorFlags(DefaultTsPayloadReaderFactory.FLAG_DETECT_ACCESS_UNITS | DefaultTsPayloadReaderFactory.FLAG_ALLOW_NON_IDR_KEYFRAMES | DefaultTsPayloadReaderFactory.FLAG_OVERRIDE_CAPTION_DESCRIPTORS).setTsExtractorMode( TsExtractor.TS_STREAM_TYPE_AAC_ADTS );
        player =new SimpleExoPlayer.Builder(this, new DefaultRenderersFactory(this)).setTrackSelector(new DefaultTrackSelector(this)).setMediaSourceFactory(
                new DefaultMediaSourceFactory(this, extractorsFactory)).setLoadControl(new DefaultLoadControl.Builder()
                .setPrioritizeTimeOverSizeThresholds(false).build()).setSeekParameters(SeekParameters.CLOSEST_SYNC ).build();
                //new SimpleExoPlayer.Builder(_ctx).build();
        StyledPlayerView pw = findViewById(R.id.player_view);
        pw.setUseController(false);
        pw.setResizeMode(AspectRatioFrameLayout.RESIZE_MODE_FILL);
        pw.setPlayer(player);

and next i giv him urls by 

 Uri mp4VideoUri = Uri.parse(item.getItemUrl());
            MediaItem mediaItem = new MediaItem.Builder()
                    .setUri(mp4VideoUri)
                    .setDrmUuid(C.WIDEVINE_UUID)
                    .build();

            // Prepare the player with the source.
            player.setMediaItem(mediaItem);
```

at this time the stream  have parametrs 
Input #0, mpegts, from 'http://10.100.100.9:8888/ngw.ts':
  Duration: N/A, start: 90621.328378, bitrate: N/A
  Program 19116
    Metadata:
      service_name    :
      service_provider:
    Stream #0:0[0xdd](rus): Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 127 kb/s
    Stream #0:1[0xde](eng): Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 164 kb/s
    Stream #0:2[0xd3]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(tv, bt470bg, top first), 720x576 [SAR 16:11 DAR 20:11], 25 fps, 50 tbr, 90k tbn, 50 tbc
    Stream #0:3[0x401](rus): Subtitle: dvb_subtitle ([6][0][0][0] / 0x0006)

playing normal without any problem but stream 
Input #0, hls, from 'http://10.100.100.9:8888/ngw/index.m3u8':
  Duration: N/A, start: 91505.803044, bitrate: N/A
  Program 0
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
    Stream #0:2: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(tv, bt470bg), 720x576 [SAR 16:11 DAR 20:11], 50 fps, 50 tbr, 90k tbn, 50 tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:3: Subtitle: dvb_subtitle ([6][0][0][0] / 0x0006)
    Metadata:
      variant_bitrate : 0

stuck on buffering

**Comment by AquilesCanta** [comment]
The provided uri http://10.100.100.9:8888/ngw/index.m3u8 is not accessible to me. It's a [reserved IP](https://en.wikipedia.org/wiki/Reserved_IP_addresses). Please provide a link to the content which is publicly available.

EDIT: Also,  `TsExtractor.TS_STREAM_TYPE_AAC_ADTS`  is not a valid value to pass to `setTsExtractorMode()`.

**Comment by PoghosyanRoman** [comment]
try this : http://91.205.196.11:8888/ngw/index.m3u8
i open it tempoary

**Comment by PoghosyanRoman** [comment]
EDIT: Also, TsExtractor.TS_STREAM_TYPE_AAC_ADTS is not a valid value to pass to setTsExtractorMode().
added as try. whithout it not playing too

**Comment by AquilesCanta** [comment]
I'm able to access `http://91.205.196.11:8888/ngw/index.m3u8`. However, neither a segment as a standalone file, or the HLS version of the media have "stuck in buffering" issues. Both versions succeed in starting playback. Can you:
- Provide a static file (i.e. something that's not changing like a live stream) that reproduces the issue directly? (Note: You provided a link to a live stream, which means i'm not able to consistently try what you are trying).
- Explain how I can use the file from the item above so as to reproduce the issue in the ExoPlayer demo app?

**Comment by PoghosyanRoman** [comment]
how init the player then it play normal ? i show a part of code on my side , and it not play this live

**Comment by AquilesCanta** [comment]
I don't understand the question. Are you passing DefaultTsPayloadReaderFactory.FLAG_ALLOW_NON_IDR_KEYFRAMES to your `DefaultHlsExtractorFactory`?

The flag you need to set should be passed to this [DefaultHlsExtractorFactory constructor](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/source/hls/DefaultHlsExtractorFactory.html#%3Cinit%3E(int,boolean)). You need to pass the created DefaultHlsExtractorFactory instance to HlsMediaSource.Factory's [setExtractorFactory](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/source/hls/HlsMediaSource.Factory.html#setExtractorFactory(com.google.android.exoplayer2.source.hls.HlsExtractorFactory)). And then you use that HlsMediaSource factory to create the media source with which you prepare the player.

I'm assigning to @marcbaechinger in case you have any questions about going from the MediaItem API to customizing the HLS MediaSource.

**Comment by PoghosyanRoman** [comment]
ok thank you.
the problem solved  then i use DefaultHlsExtractorFactory and not mediasource
