### ISSUE TITLE
Video and audio are out of sync

### ISSUE THREAD

**Issue by Leatar** [google/ExoPlayer#874]
Hi. I try to use your library for playback video from website http://geth.by/ through the Internet connection. However when I try to play a large mp4 video (for example, http://geth.by/video/20151011_2.mp4) the audio and video are a bit out of sync. This file is played fine by the default android video player. So please help me to configure ExoPlayer for correct playback.

**Comment by ojw28** [comment]
For what it's worth, playback is out of sync using the platform player too on the devices I just tested with. VLC does appear to sync audio and video correctly though. We'll take a look. It's unclear whether it's a media issue or a player issue at this point.

**Comment by Android4MediaPlayer** [comment]
can't get streaming,please check the url.

**Comment by andrewlewis** [comment]
This file has a ctts box that provides offsets between decoding and composition time. We only support ctts boxes with one entry currently. We should parse the complete table and apply the timestamp offsets, which I suspect will make this file play correctly.

**Comment by andrewlewis** [comment]
Correction: we are actually parsing all entries of the table.

**Comment by andrewlewis** [comment]
The stream has edit lists (elst) which are not parsed at the moment.

**Comment by ojw28** [comment]
This is now fixed in the dev branch.
