### ISSUE TITLE
Very slow seeking compared to android's native media player.

### ISSUE THREAD

**Issue by dummy-amit** [google/ExoPlayer#8740]
I am trying to seek locally available video using Exo Player, to my surprise seeking is extremely slow. 
I understand how MP4 works and how seeking is slow because of dependency of frames decoding on key frames, but exact same file when played using media player can be seeked very smoothly (almost at frame level)

Attaching comparison video for reference.

1st video shows seeking of exo player 
https://user-images.githubusercontent.com/49638809/111849850-a2f1ea80-8934-11eb-9174-60993cb86d50.mp4

2nd video shows seeking of media player
https://user-images.githubusercontent.com/49638809/111849863-a84f3500-8934-11eb-92fb-756fd1c11ebf.mp4

I am not able to understand how can media player seek so much better and what I am missing in exo player that I cannot get this performance. Is there a way we can achieve this in exo player? 

Exo Player version: 2.12.1
Device: Any device

**Comment by dummy-amit** [comment]
https://user-images.githubusercontent.com/49638809/111850011-11cf4380-8935-11eb-8f1b-797faa02f740.mp4

Attaching video used for showing demo of seeking if it helps.

**Comment by andrewlewis** [comment]
There are some suggestions in #6794, in particular avoiding having the UI issue a seek when there is one already 'pending' and pausing the player when scrubbing.

**Comment by andrewlewis** [comment]
Please could you try those suggestions and let us know if it makes a difference?

**Comment by dummy-amit** [comment]
Sure let me try and get back to you at earliest.

**Comment by dummy-amit** [comment]
Can you guide me how can I know when seek is processed. 

`onSeekProcessed` method callback gets called in sync with seekTo method while seek to command is provided to internal player via handler. 

![image](https://user-images.githubusercontent.com/49638809/112428838-cae0b400-8d61-11eb-90ee-93522b050a71.png)

**Comment by andrewlewis** [comment]
The behavior of `onSeekProcessed` changed after https://github.com/google/ExoPlayer/issues/6794#issuecomment-573068211 was written. Please ignore that part of the instructions for now and see if the rest helps.
