### ISSUE TITLE
MostRecentlyUsedCacheEvictor?

### ISSUE THREAD

**Issue by NathanSass** [google/ExoPlayer#8746]
Hello,

I am currently using the `LeastRecentlyUsedCacheEvictor` for our playback cache. Exoplayer currently does not provide an MRU cache as an alternative. I am wondering if an MRU cache would be most appropriate for audio playback applications. I would think we would want to prioritize caching content the user has not heard yet. Skipping back 10 - 30 seconds is a common use case, I think this would be un affected in most situations because that skipping would occur on the chunk that the user is currently listening to. 

Is a MRU cache a better choice for audio than a LRU cache?

**Comment by ojw28** [comment]
Writing something into the cache counts as using it, so I don't think a `MostRecentlyUsedCacheEvictor` would make sense. It would end up trying to evict content immediately after it's been written.

I would generally expect a cache to be significantly bigger than a single piece of audio content, so I'm not sure the way you're thinking about it, which seems to be considering playback through a single piece of content, is necessarily the right one.
