### ISSUE TITLE
Help troubleshoting with freezing HLS 

### ISSUE THREAD

**Issue by maketvgithub** [google/ExoPlayer#8747]
Hello,

We are having difficulties with playing HLS streams. We did debug and noticed that some requests which ExoPlayer is sending about chunk download.

The expected scenario is to download the last chunk after each chunk list, but this sometimes doesn't happen and can be seen in lines 8 and 9 of the log below. @alenemini

[hls_log_report_1616488413.log](https://github.com/google/ExoPlayer/files/6189089/hls_log_report_1616488413.log)

Also, we are attaching here sample of chunk list:

```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:7
#EXT-X-MEDIA-SEQUENCE:86109
#EXTINF:4.0,
media-ufhofmxul_86109.ts
#EXTINF:4.0,
media-ufhofmxul_86110.ts
#EXTINF:4.0,
media-ufhofmxul_86111.ts
```

Here is also sample of master playlist:

```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:BANDWIDTH=3708488,CODECS="avc1.77.32,mp4a.40.2",RESOLUTION=1280x720
chunklist.m3u8?token=hash-2vOandpv-sXEZXt8BxgA7A-cid-n1-expires-1617101287-ak-4229161
```

Is there anything that we can do to improve this strange behavior.

**Comment by andrewlewis** [comment]
> The expected scenario is to download the last chunk after each chunk list, but this sometimes doesn't happen and can be seen in lines 8 and 9 of the log below. @alenemini

I'm not sure I follow. Please could you elaborate a bit about what's causing playback to freeze based on your debugging, and also provide instructions for us to reproduce the problem here including a link to the stream to play? If you don't want to post them here you can email them to `dev.exoplayer@gmail.com`.

**Comment by maketvgithub** [comment]
Hello, 

Thank you for the quick response!

We found that the download depends on the `# EXT-X-TARGETDURATION` parameter and therefore the chunks were downloading unevenly. We're still researching, so we'll get back to you when we got more information.

**Comment by ZloyDyadka** [comment]
Hello! We have the same problem. Also i found the same problem in closed issue https://github.com/google/ExoPlayer/issues/6360

**Comment by maketvgithub** [comment]
Hello @andrewlewis,

We continued to research why the stream could freeze and we found that the player sometimes does not download the chunks, but gets stuck in downloading the chunk list and the only recovery here is to restart the player, ie change the channel in our case which can be seen when a playlist download has appeared.

We deliver to you below the log from the server:
[server_logs.txt](https://github.com/google/ExoPlayer/files/6236327/server_logs.txt)

**Comment by christosts** [comment]
To further assist you, can you please provide instructions for us to reproduce the problem and a link to the stream to play it in the ExoPlayer demo app? If you don't want to post them here you can email them to dev.exoplayer@gmail.com with subject "Isse #8747" and update this issue once you have done so. Thanks.

**Comment by SeJIya** [comment]
Same problem

**Comment by ZloyDyadka** [comment]
Hello! Playlist with the same data for reproducing problem:  https://support-dm.erlyvideo.ru/wasd_live/test/index.m3u8

**Comment by christosts** [comment]
> Hello! Playlist with the same data for reproducing problem: https://support-dm.erlyvideo.ru/wasd_live/test/index.m3u8

The link above returns an HTTP 404 (not found).

**Comment by ZloyDyadka** [comment]
Sorry, recheck please https://support-dm.erlyvideo.ru/wasd_live/test/index.m3u8

**Comment by christosts** [comment]
> Sorry, recheck please https://support-dm.erlyvideo.ru/wasd_live/test/index.m3u8

I tested the stream with version 2.13.3 and it worked fine. The stream is identified as

```
      MediaCodecVideoRenderer [
        Group:0, adaptive_supported=N/A [
          [X] Track:0, id=0, mimeType=video/avc, bitrate=320000, codecs=avc1.42C015, res=320x240, fps=25.0, supported=YES
        ]
        Metadata [
          HlsTrackMetadataEntry
        ]
      ]
      MediaCodecAudioRenderer [
        Group:0, adaptive_supported=N/A [
          [X] Track:0, id=1/15, mimeType=audio/mp4a-latm, codecs=mp4a.40.2, channels=2, sample_rate=48000, supported=YES
        ]
      ]
     TextRenderer []
      MetadataRenderer [
        Group:0, adaptive_supported=N/A [
          [X] Track:0, id=null, mimeType=application/id3, supported=YES
        ]
      ]
      CameraMotionRenderer []
    ]
```

I see a grey-scale image with an increasing timer and a bip sound every second. Is this the expected content? I did not reproduce any freezing.  Are there specific steps/setup that reproduce the issue?

**Comment by ZloyDyadka** [comment]
Hello! Yep, grey-scale image is expected content.
Now, we have updated the playlist for only 3 segments and see problems. Playback stalls every 6 seconds, but for 4 segments we haven't problems.
Version 2.13.3

**Comment by christosts** [comment]
The playlist's target duration is 7 seconds but the 3 segments total duration is 6 seconds. The player refreshes the playlist every 7 seconds, instructed by target duration as per the HLS spec.
https://tools.ietf.org/html/draft-pantos-hls-rfc8216bis-09#section-6.3.4

Ensure that playlist duration is longer than the target duration.

**Comment by christosts** [comment]
As this issue is more with more with forming a valid HLS playlist and less with ExoPlayer, I'm inclined to close this issue. If you need further assistance, feel free to re-open.
