### ISSUE TITLE
HLS video lag and massive dropped frames 

### ISSUE THREAD

**Issue by sam-m3** [google/ExoPlayer#8751]
Problem
--
I have been using exo-player to play hls and live-stream videos in some android devices and the videos were playing just fine when they were in `h264` format, but when `h265` is used, A MASSIVE number of frames were dropped and the videos become very laggy.

The h265 video resolution is `1920*1080` and the frame rates are 50 fps.

I spent the last 2 weeks seeking for an answer and looked at all the raised issues in exoplayer that hls was mention in, but I found nothing helpful for my case.
I also thought that this could be a hardware issue, but then I used android's MediaPlayer to play the same video, and they were playing fine, but I still want to use exo-player because MediaPlayer does not work as I intended on my newer devices.

Due to privacy manners, I sent you the link to your email, an example of H265 video that keeps lagging with exoplayer but works with MediaPlayer, you can test it on an android TV emulator api 29, and see the dropped frames on the EventLogger.

**Comment by andrewlewis** [comment]
The emulator uses software decoding that is likely to be slower than what you see on a real device, which can lead to dropped frames, so we recommend testing your app on real devices. If you see an excessive number of dropped frames on a real device please take a bug report via `adb bugreport` and we can see if that contains any indications about what is going on. By the way, the link provided via email is showing an error page for me.

**Comment by sam-m3** [comment]
Hello, sorry for the late response.

I tried to take a bug report from my box, because the device couldn't be connected to my PC, so that I cannot even USB debug my app or take a bug report from my box.

Recently, I faced the same problem with my emulator, the H.264 videos work fine, but the H.265 videos have many dropped frames; So I took a bug report from my emulator.

And the link I sent to you has been expired, So I have sent you another one with the Title of #8751

Bug report
--   
[bugreport-sdk_google_atv_x86-QTU1.200805.001-2021-04-12-14-46-58.txt](https://github.com/google/ExoPlayer/files/6297690/bugreport-sdk_google_atv_x86-QTU1.200805.001-2021-04-12-14-46-58.txt)

And as I explained before, It cannot be a device specific or a hardware problem, because the same video works smoothly using MediaPlayer on the same device.

EventLogger
-----

> D/EventLogger: loading [eventTime=0.05, mediaPos=0.00, window=0, period=0, true]
D/EventLogger: timeline [eventTime=0.54, mediaPos=10.08, window=0, period=0, periodCount=1, windowCount=1, reason=SOURCE_UPDATE
D/EventLogger:   period [?]
D/EventLogger:   window [50.40, seekable=true, dynamic=true]
D/EventLogger: ]
D/EventLogger: videoEnabled [eventTime=0.64, mediaPos=10.08, window=0, period=0]
D/EventLogger: audioEnabled [eventTime=0.64, mediaPos=10.08, window=0, period=0]
D/EventLogger: tracks [eventTime=0.64, mediaPos=10.08, window=0, period=0
D/EventLogger:   LibvpxVideoRenderer []
D/EventLogger:   MediaCodecVideoRenderer [
D/EventLogger:     Group:0, adaptive_supported=N/A [
D/EventLogger:       [X] Track:0, id=0, mimeType=video/hevc, bitrate=1950000, codecs=hvc1.1.6.L153, res=1920x1080, fps=50.0, supported=YES
D/EventLogger:     ]
D/EventLogger:     Metadata [
D/EventLogger:       HlsTrackMetadataEntry
D/EventLogger:     ]
D/EventLogger:   ]
D/EventLogger:   FfmpegAudioRenderer [
D/EventLogger:     Group:0, adaptive_supported=N/A [
D/EventLogger:       [X] Track:0, id=1001/4, mimeType=audio/mpeg-L2, channels=2, sample_rate=48000, supported=YES
D/EventLogger:     ]
D/EventLogger:   ]
D/EventLogger:   MediaCodecAudioRenderer []
D/EventLogger:   TextRenderer []
D/EventLogger:   MetadataRenderer [
D/EventLogger:     Group:0, adaptive_supported=N/A [
D/EventLogger:       [X] Track:0, id=null, mimeType=application/id3, supported=YES
D/EventLogger:     ]
D/EventLogger:   ]
D/EventLogger:   CameraMotionRenderer []
D/EventLogger: ]
D/EventLogger: staticMetadata [eventTime=0.64, mediaPos=10.08, window=0, period=0
D/EventLogger:   Metadata:0 [
D/EventLogger:     HlsTrackMetadataEntry
D/EventLogger:   ]
D/EventLogger: ]
D/EventLogger: downstreamFormat [eventTime=0.64, mediaPos=10.08, window=0, period=0, id=0, mimeType=null, bitrate=1950000, res=1920x1080, fps=50.0]
D/EventLogger: videoDecoderInitialized [eventTime=0.66, mediaPos=10.08, window=0, period=0, OMX.google.hevc.decoder]
D/EventLogger: videoInputFormat [eventTime=0.66, mediaPos=10.08, window=0, period=0, id=0, mimeType=video/hevc, bitrate=1950000, codecs=hvc1.1.6.L153, res=1920x1080, fps=50.0]
D/EventLogger: audioDecoderInitialized [eventTime=0.66, mediaPos=10.08, window=0, period=0, ffmpegLavc58.54.100-mp3]
D/EventLogger: audioInputFormat [eventTime=0.66, mediaPos=10.08, window=0, period=0, id=1001/4, mimeType=audio/mpeg-L2, channels=2, sample_rate=48000]
D/EventLogger: videoSize [eventTime=0.71, mediaPos=10.08, window=0, period=0, 1920, 1080]
D/EventLogger: renderedFirstFrame [eventTime=0.82, mediaPos=10.08, window=0, period=0, Surface(name=null)/@0x1904f2e]
D/EventLogger: state [eventTime=0.87, mediaPos=10.08, window=0, period=0, READY]
D/EventLogger: isPlaying [eventTime=0.87, mediaPos=10.08, window=0, period=0, true]
E/EventLogger: audioTrackUnderrun [eventTime=1.15, mediaPos=10.27, window=0, period=0, 48000, 250, 287]
D/EventLogger: droppedFrames [eventTime=2.36, mediaPos=11.50, window=0, period=0, 50]
D/EventLogger: droppedFrames [eventTime=4.16, mediaPos=13.30, window=0, period=0, 50]
D/EventLogger: droppedFrames [eventTime=6.29, mediaPos=15.43, window=0, period=0, 50]
D/EventLogger: droppedFrames [eventTime=9.11, mediaPos=18.25, window=0, period=0, 50]
D/EventLogger: timeline [eventTime=11.73, mediaPos=10.81, window=0, period=0, periodCount=1, windowCount=1, reason=SOURCE_UPDATE
D/EventLogger:   period [?]
D/EventLogger:   window [50.40, seekable=true, dynamic=true]
D/EventLogger: ]
D/EventLogger: droppedFrames [eventTime=12.17, mediaPos=11.16, window=0, period=0, 50]

**Comment by andrewlewis** [comment]
Sorry for the late reply. Without the ability to get bug report (or presumably even see logcat) from the device I don't think this is actionable for us.

You could try contacting the device manufacturer and getting them to help set up a way to access device logs, and see if they have any suggestions on resolving the difference in performance between playback using ExoPlayer vs MediaPlayer. One possible explanation is that ExoPlayer is picking a software decoder on the device because the stream exceeds a hardware decoder's advertised capabilities, while `MediaPlayer`'s simpler codec selection algorithm just picks the hardware decoder and it happens to work. You could try forcing selection of the first listed decoder for H.265/HEVC in ExoPlayer to test that hypothesis. If you are serving an unnecessarily high bitrate or high resolution stream you could also try reducing it and see if that fixes the problem (I can't check because the link provided via email is returning an HTTP error code).

Closing as we don't have enough information to investigate properly.
