### ISSUE TITLE
Exoplayer crossfade support

### ISSUE THREAD

**Issue by adoudech** [google/ExoPlayer#8753]
Is it possible to support crossfade transition between two medias using Merging/Clipping/Concatenating media source without overriding the behavior of some internal Exoplayer classes such as `MediaCodecAudioRenderer`?
If not, what is the easiest way to implement this feature and what you recommend?
Thank you

**Comment by andrewlewis** [comment]
I'm afraid this isn't supported. See also #3438.

**Comment by andrewlewis** [comment]
Duplicate of #3438
