### ISSUE TITLE
Unable to play url with direct download link

### ISSUE THREAD

**Issue by MeiYi2** [google/ExoPlayer#8754]
Unable to play video which will be downloaded automatically.

 http://down.okdownload8.com/20210116/8916_c122d0c0/ok夺命巨鲨HD2021.mp4

Is there any way to play this video in ExoPlayer?

**Comment by andrewlewis** [comment]
That video plays for me in the [ExoPlayer demo app](https://exoplayer.dev/demo-application.html). If you are seeing an error, please provide some more details about what behavior/message you see, ideally by filling out the [issue template](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md).

**Comment by NanyangTaiji** [comment]
Same issue for me, in fact, links starting with "http" are not playable.

**Comment by andrewlewis** [comment]
The issue may be that cleartext traffic is not permitted. See [these instructions](https://exoplayer.dev/troubleshooting.html#fixing-cleartext-http-traffic-not-permitted-errors).

**Comment by NanyangTaiji** [comment]
It is no the issue, the App works fine before upgrding. It was declared in Application: android:usesCleartextTraffic="true" already.

**Comment by andrewlewis** [comment]
There isn't enough information for us to help here. The originally-reported issue was not reproducible so I'll close this. If you are still having problems please file a new issue and include all the information requested in the template.
