### ISSUE TITLE
Is it expected behavior for exoplayer to call getForegroundNotification multiple times when deleting a video?

### ISSUE THREAD

**Issue by andrematheus** [google/ExoPlayer#8757]
We're developing an app using exoplayer to download videos and noticed that, when deleting videos, `getForegroundNotification` may be called multiple times, depending on the size of the video. Depending on the importance of the notification the mobile may vibrate and emit sound many times, one for each call of `getForegroundNotification`, and this gets annoying for our end users.

So, our question is: is this expected behavior on part of exoplayer ou could this be a bug? We've searched for related issues and found only [this](https://github.com/google/ExoPlayer/issues/6806#issuecomment-569503783) comment, that says it is annoying too but doesn't go any further.

Thanks for the help.

**Comment by andrewlewis** [comment]
@marcbaechinger Please could you take a look?

**Comment by marcbaechinger** [comment]
I don't think this is a bug. As long as the `DownloadService` is running in the foreground there is a task that updates the foreground notification every second. This is the case either when the media is downloaded or when it is removed. Both tasks are executed by the `DownloadService` and have the same behaviour. 

In the case of a download updating the notification every second allows to display the download progress to the user. I would expect that this sound is played in the same way when downloading and playing that sound each time the progress bar is increasing isn't nice either. The same mechanism is used when a download is removed. Removing a download involves updating the database and deleting numerous file parts from the cache. So this can trigger this update more than once, just like you report. 

I'm not questioning your design decisions, but for a foreground service notification I would not use an importance that triggers a sound. Just for the reason that you are describing.  The importance is defined by the notification channel. So if you have other notifications that should play a sound, I'd suggest to create a separate channel for downloads and then assign the notification returned by `getForegroundNotification` to this specific channel.

**Comment by andrematheus** [comment]
Makes sense @marcbaechinger , thanks for the help!
