### ISSUE TITLE
How can i update the Exoplayer from v1.9.6 to v2.12.0

### ISSUE THREAD

**Issue by zhhach123** [google/ExoPlayer#8759]
Hi,
I am trying to update the exoplayer from version 1.9.6 to 2.12.0.When i finish the update,i found some function have been modified.

```java
        DefaultBandwidthMeter defaultBandwidthMeter = new DefaultBandwidthMeter();
        TrackSelection.Factory videoTrackSelectionFactory = new AdaptiveTrackSelection.Factory();
        TrackSelector trackSelector =
                new DefaultTrackSelector(videoTrackSelectionFactory);
        RenderersFactory renderersFactory;
//        RenderersFactory renderersFactory = new DefaultRenderersFactory(AppConfig.instance);
        DefaultDrmSessionManager<FrameworkMediaCrypto> drmSessionManager = null;
        renderersFactory =
                new DefaultRenderersFactory(AppConfig.instance, 1) {
                    @Override
                    public AudioProcessor[] buildAudioProcessors() {
                        return new AudioProcessor[]{};
                    }
                };
        player = ExoPlayerFactory.newSimpleInstance(this, renderersFactory, trackSelector, drmSessionManager);
```

The code above is to create the Exoplayer.After the update,i found some fuctions have been modified.Now i don't know how to create the exoplayer with the version 2.12.0.I hope to give some suggestions.
Thank you very much.

**Comment by icbaker** [comment]
Version 1.9.6 doesn't exist - ExoPlayer v1 (now unsupported) only got as high as 1.5.16. Most of the symbols you reference don't exist in 1.5.16. Presumably you mean 2.9.6?

In some cases it looks like the symbols you're using are deprecated and the deprecation message tells you the alternative to use, e.g.:
https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/upstream/DefaultBandwidthMeter.html#DefaultBandwidthMeter--

In other cases there's info in the [release notes](https://github.com/google/ExoPlayer/blob/release-v2/RELEASENOTES.md). For example this bullet looks relevant:
> * Remove deprecated symbols:
>    * Remove ExoPlayerFactory. Use SimpleExoPlayer.Builder instead.

`DefaultRenderersFactory#buildAudioProcessors()` has been replaced by `buildAudioSink()` (more info: https://github.com/google/ExoPlayer/issues/8841#issuecomment-823942199).

Closing as I think this should be enough info to update the code snippet provided. Please reply here if there are specific parts you can't get to work.
