### ISSUE TITLE
Provide offline DRM support (without need to implement your own DrmSessionManager)

### ISSUE THREAD

**Issue by siavashabdoli** [google/ExoPlayer#876]
Hi

Can I Download a video with DRM protection on sdcard and play it only with my my app that using exoplayer. I don't want user can copy my video to another device and I want save it on SD card because of size and number of videos that user may download

**Comment by seventhmoon** [comment]
Exoplayer currently support the following
1. Offline playback
2. store the DRM key securely by MediaDrm

However, it require your own implementation of DrmSessionManager on how to store the keySetId of each video content.

**Comment by ojw28** [comment]
@seventhmoon is correct - it's fairly straightforward to implement your own DrmSessionManager. That said, we should probably add support directly to the library. We should also provide a component to assist in requesting the offline keys.

**Comment by ram992** [comment]
Can I get an Example Class on how to implement our Own DrmSessionManager

**Comment by erdemguven** [comment]
This has been implemented in the change 9d5c750

**Comment by chandrasekhararao** [comment]
Dear All,

I am trying to do offline DRM videos playing in android.
I have configured in gradle like: compile 'com.google.android.exoplayer:exoplayer:r2.0.3'
I have tried with new version but some unknown exception are coming.
Can you please give full sample code for the above version?
How to gather keys and how to store and retrieve those keys using StreamingDrmSessionManager...? Please explain.

**Comment by seventhmoon** [comment]
I think how to store the key for offline is already mentioned in Android DRM Framework.
You do 95% the same as streaming playback. Just one more step on telling the OS to store the key.

**Comment by chandrasekhararao** [comment]
Thank you @seventhmoon .
Can please share sample code for that...i am new to this android.
