### ISSUE TITLE
VideoCapabilities: Unsupported profile 5 for video/mpeg2

### ISSUE THREAD

**Issue by jjuandiaz** [google/ExoPlayer#8760]
what happened here?

when I started video 
the image is frozen in video and stop playing 

**********START LOGCAT************

I/Choreographer: Skipped 287 frames!  The application may be doing too much work on its main thread.
W/VideoCapabilities: Unrecognized profile/level 0/0 for video/mpeg2
W/VideoCapabilities: Unrecognized profile/level 0/2 for video/mpeg2
    Unrecognized profile/level 0/3 for video/mpeg2
I/VideoCapabilities: Unsupported profile 2 for video/mpeg2
    Unsupported profile 2 for video/mpeg2
    Unsupported profile 2 for video/mpeg2
    Unsupported profile 2 for video/mpeg2
I/VideoCapabilities: Unsupported profile 3 for video/mpeg2
    Unsupported profile 3 for video/mpeg2
    Unsupported profile 3 for video/mpeg2
    Unsupported profile 3 for video/mpeg2
    Unsupported profile 4 for video/mpeg2
    Unsupported profile 4 for video/mpeg2
    Unsupported profile 4 for video/mpeg2
    Unsupported profile 4 for video/mpeg2
I/VideoCapabilities: Unsupported profile 5 for video/mpeg2
    Unsupported profile 5 for video/mpeg2
    Unsupported profile 5 for video/mpeg2
    Unsupported profile 5 for video/mpeg2
W/VideoCapabilities: Unrecognized profile/level 0/0 for video/mpeg2
    Unrecognized profile/level 0/2 for video/mpeg2
W/VideoCapabilities: Unrecognized profile/level 0/3 for video/mpeg2
I/VideoCapabilities: Unsupported profile 2 for video/mpeg2
I/VideoCapabilities: Unsupported profile 2 for video/mpeg2
I/VideoCapabilities: Unsupported profile 2 for video/mpeg2
I/VideoCapabilities: Unsupported profile 2 for video/mpeg2
I/VideoCapabilities: Unsupported profile 3 for video/mpeg2
I/VideoCapabilities: Unsupported profile 3 for video/mpeg2
    Unsupported profile 3 for video/mpeg2
I/VideoCapabilities: Unsupported profile 3 for video/mpeg2
    Unsupported profile 4 for video/mpeg2
I/VideoCapabilities: Unsupported profile 4 for video/mpeg2
I/VideoCapabilities: Unsupported profile 4 for video/mpeg2
I/VideoCapabilities: Unsupported profile 4 for video/mpeg2
    Unsupported profile 5 for video/mpeg2
    Unsupported profile 5 for video/mpeg2
I/VideoCapabilities: Unsupported profile 5 for video/mpeg2
    Unsupported profile 5 for video/mpeg2
W/AudioCapabilities: Unsupported mime audio/ac3
W/MediaCodecInfo: AssumedMaxChannelAdjustment: OMX.google.ac3.decoder, [1 to 6]
I/OMXClient: MuxOMX ctor
I/MediaCodec: [OMX.amlogic.mpeg2.decoder.awesome] setting surface generation to 6688770
D/ACodec_amlogic: query systemComposer 1
E/ACodec: [OMX.amlogic.mpeg2.decoder.awesome] storeMetaDataInBuffers failed w/ err -2147483648
I/ACodec: codec does not support config priority (err -1010)
D/SurfaceUtils: set up nativeWindow 0xd02bc808 for 1920x1088, color 0x11, rotation 0, usage 0x2002900
W/ACodec: [OMX.amlogic.mpeg2.decoder.awesome] setting nBufferCountActual to 8 failed: -1010
W/ACodec: [OMX.amlogic.mpeg2.decoder.awesome] setting nBufferCountActual to 7 failed: -1010
D/AudioTrack: Client defaulted notificationFrames to 8208 for frameCount 16416
D/getSubtitulo: activado
W/MediaCodecInfo: AssumedMaxChannelAdjustment: OMX.google.ac3.decoder, [1 to 6]
D/AudioTrack: Client defaulted notificationFrames to 8208 for frameCount 16416
D/requestdebug_chunk: https://url.example.com/video.m3u8

**********END LOGCAT************
<img width="879" alt="image" src="https://user-images.githubusercontent.com/59715844/112631516-bf4ec500-8e15-11eb-84e7-edf47a6224dc.png">

**Comment by lcf87** [comment]
Hi! Please provide complete information as requested in the issue template. The issue template can
be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md).
If you're unable to share [bug reports](https://developer.android.com/studio/debug/bug-report) or
test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format
"Issue #1234" ("#1234" is replaced with your issue number). Please also update this issue to
indicate you've done this.

**Comment by jjuandiaz** [comment]
ExoPlayer version number: 2.12.0

Android version: 7.1.2

Android device: Amlogic JB BOX p281

Gradle: 

//libreria de FFMPEG solo incluye codec AC3
implementation files('../libs/ffmpeg.aar')

implementation 'com.google.android.exoplayer:exoplayer-core:2.12.0'
implementation 'com.google.android.exoplayer:exoplayer-dash:2.12.0'
implementation 'com.google.android.exoplayer:exoplayer-hls:2.12.0'
implementation 'com.google.android.exoplayer:exoplayer-smoothstreaming:2.12.0'
implementation 'com.google.android.exoplayer:exoplayer-ui:2.9.6'

implementation 'com.google.android.exoplayer:extension-rtmp:2.12.0'
[logcat.txt](https://github.com/google/ExoPlayer/files/6223285/logcat.txt)
[bugreport-NHG47L-2021-03-29-11-51-19.zip](https://github.com/google/ExoPlayer/files/6223286/bugreport-NHG47L-2021-03-29-11-51-19.zip)

**Comment by andrewlewis** [comment]
I think the log lines about unsupported profiles from VideoCapabilities may be expected and not actually indicative of a problem. Not sure what your ffmpeg.aar library does but you may want to try using the [FFmpeg extension](https://github.com/google/ExoPlayer/tree/release-v2/extensions/ffmpeg).

**Comment by jjuandiaz** [comment]
ffmpeg.aar are FFmpeg compiled  extension

**Comment by lcf87** [comment]
I can't open the bugreport.zip you uploaded.

In the meantime, could you try play the video without ffmpeg? Or if you can provide us with a video clip to test with?
