### ISSUE TITLE
StyledPlayerControlView: Constraints for minimal mode too conservative

### ISSUE THREAD

**Issue by fountaingeyser** [google/ExoPlayer#8763]
With the introduction of the minimal mode the player controls become mostly unusable in many cases. When used in portrait mode on the OnePlus 7 with a 16:9 video the minimal mode is already activated. Consequently, none of the basic controls (e.g. VR or shuffle button) are reachable for users anymore. 

A thorough investigation has revealed that the height of the player is considered too small to fit the default control views: https://github.com/google/ExoPlayer/blob/4364b9150f236813a2070fc79d3bcb76e11969ac/library/ui/src/main/java/com/google/android/exoplayer2/ui/StyledPlayerControlViewLayoutManager.java#L565-L589

Two possible solutions are:
1. Relax the constraints required to display the default user interface. As shown in our screenshots there is ample space to layout both the play/pause button and the bottom controls. This could be achieved by reducing padding or margins. 
2. Provide fallback for all controls in minimal mode. This could be achieved with a simple overflow button and a bottom sheet or dialog with the basic controls (as illustrated e.g. by YouTube). 

|  Minimal mode on OnePlus 7 | Default mode on OnePlus 7 |
| -------------------------------- | ------------------------------ |
| ![image](https://user-images.githubusercontent.com/12252259/112749065-2dcf8680-8fc0-11eb-9d85-361ceb11d57d.png) | ![image](https://user-images.githubusercontent.com/12252259/112749017-e517cd80-8fbf-11eb-94e8-3af04694068a.png) |

- ExoPlayer version number: 2.13.2
- Android version: Android 10
- Android device: OnePlus 7

**Comment by ojw28** [comment]
Agree there is an issue here. It looks like the padding of `exo_center_controls` is not being removed from the calculation, which I think it should be.  There's also a problem horizontally where the edges of the far left/right icons can end up being clipped even when there is sufficient space for them to be fully rendered.

![device-2021-03-30-161823](https://user-images.githubusercontent.com/7881572/113013378-914de580-9173-11eb-8389-16ef27e863b7.png)
