### ISSUE TITLE
hls stream got error with demo app

### ISSUE THREAD

**Issue by newtestpage** [google/ExoPlayer#8768]
Hi 
I am trying to play this stream link with on my app . but it didn't works . also it has problem with demo app . 
 could you please check the link ?

`

 
--
https://d2e40kvaojifd6.cloudfront.net/stream/mifa/playlist.m3u8 | Detail
 

`

**Comment by lcf87** [comment]
I doubt it's a problem within the playlist, assigning to @christosts. Here's the pasted playlist:

```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-INDEPENDENT-SEGMENTS
#EXT-X-STREAM-INF:BANDWIDTH=2621819,AVERAGE-BANDWIDTH=2525600,CODECS="avc1.640029,mp4a.40.2",RESOLUTION=960x540,FRAME-RATE=29.970
playlist_960x540_2000k.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=5287612,AVERAGE-BANDWIDTH=5090800,CODECS="avc1.640029,mp4a.40.2",RESOLUTION=1920x1080,FRAME-RATE=29.970
playlist_1920x1080_4500k.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=985388,AVERAGE-BANDWIDTH=950400,CODECS="avc1.77.30,mp4a.40.2",RESOLUTION=640x360,FRAME-RATE=29.970
playlist_640x360_800k.m3u8
```

**Comment by christosts** [comment]
The player cannot download the playlist and consistently gets an HTTP 403 when attempting to download the playlist. The same happens why I try to access the content using vlc on mac. However, the playlist -at least- can be downloaded with a browser. 

Do you know if there's any restriction to this content applied on server side?

**Comment by ojw28** [comment]
This kind of thing often ends up being to do with the user agent. Changing the `USER_AGENT` constant in `DemoUtil` to be the same as your browser's is a quick test you can do to see whether this is the case.

**Comment by christosts** [comment]
Fyi, setting the user agent to the same as Chrome works and the content plays (tested with version 2.13.2).
