### ISSUE TITLE
How to enableDecoderFallback for ExoPlayerFactory.newSimpleInstance() ?

### ISSUE THREAD

**Issue by sruditsky** [google/ExoPlayer#8769]
Let's say there is an app which uses two third-party media players each one internally implemented using ExoPlayer.
Let's refer to the first player as the "main" and the second one as "aux".

The main player plays content and when the user pauses playback it the application starts the "aux" player.
The aux player plays some special "pause" content.

When we were using this scenario with ExoPlayer 2.9.4 this worked with a caveat that the aux player was using the software video decoder while the main player was holding on to the hardware video decoder (it is just paused and not stopped or released). 

When we switched to ExoPlayer 2.12.3 this stopped working -- the "aux" player now fails with an exception that it cannot allocate the _hardware_ video decoder.

In ExoPlayer 2.12.3 there is a way to enable decoder fallback, when it is enabled the behavior is similar to what we used to have with 2.9.4.
The problem however is that "aux" player is using ExoPlayerFactory.newSimpleInstance() and there is no way to enable decoder fallback from this level of API (and decoder fallback is disabled by default).

Do you have any recommendation on how to work around this issue (without asking the "main" player vendor to change the player behavior significantly during pause or asking the "aux" player vendor to use different API level for ExoPlayer)?

Any plans to allow enableDecoderFallback with ExoPlayerFactory.newSimpleInstance() ?

**Comment by lcf87** [comment]
I don't think supporting `enableDecoderFallback` in `newSimpleInstance` is on our agenda. If you don't have direct influence on the implementations on the two players you are using, I doubt there's a "workaround" to enabling that. 

Olly, could you confirm?

**Comment by ojw28** [comment]
I'm not sure exactly what was in `2.12.3`, but certainly from `2.13.0` you can do:

```
DefaultRenderersFactory renderersFactory =
    new DefaultRenderersFactory(this).setEnableDecoderFallback(true);
SimpleExoPlayer player =
    new SimpleExoPlayer.Builder(/* context= */ this, renderersFactory)
        ...
        .build();
```

**Comment by sruditsky** [comment]
Oh, yeah, this should work.
Thanks!
