### ISSUE TITLE
EXOPLAYER 4K STREAMING

### ISSUE THREAD

**Issue by mouemen-haress** [google/ExoPlayer#8770]
hello , please help me .
Exoplayer play videos with Good Resolution
perfectly without any buffering but when i try to play 4k or high resolution videos Exo Player start buffering alot (start buffering within more or less 10 seconds then start playing again).

**Comment by lcf87** [comment]
The buffering is controlled by `LoadControl`. I invite you to take a look there.
If you did not do any customization, the default buffer time before start playback is 2.5 seconds 

https://github.com/google/ExoPlayer/blob/4364b9150f236813a2070fc79d3bcb76e11969ac/library/core/src/main/java/com/google/android/exoplayer2/DefaultLoadControl.java#L49

That is, the playback will start after 2.5 seconds of media is buffered.

**Comment by mouemen-haress** [comment]
I do this customization but the same probleme Appeared .

**Comment by lcf87** [comment]
It sounds more like a network issue to me. Could you provide a link to your 4k stream?

**Comment by mouemen-haress** [comment]
I use vlc to similate a broadcast udp streaming in  local network .

**Comment by mouemen-haress** [comment]
only 4k video play very slowly but other video play smoothly

**Comment by lcf87** [comment]
Could you provide more information on your setup? It's impossible to pinpoint the issue with such limited info.

You mentioned UDP streaming, is it RTP? If so, there could be packet reordering/loss that contributed to the issues you saw.

**Comment by ojw28** [comment]
Closing due to lack of information.
