### ISSUE TITLE
add MediaSourceListener using DataSource.Factory 

### ISSUE THREAD

**Issue by GrilloLuca** [google/ExoPlayer#8775]
Hi, since i've migrated to MediaSourceFactory pattern, how can i add a MediaSourceListener if i can't access MediaSource?

i was able to add listener using the mediaSource.addEventListener(handler, listener) methon and then, prepare the player passing the mediasource: player.prepare(MediaSource mediaSource, boolean resetPosition, boolean resetState)

But now, building the player like this, i can't figure out how to listen the mediasource events
```
SimpleExoPlayer player = new SimpleExoPlayer.Builder(context)
    .setMediaSourceFactory(mediaSourceFactory)
    .build();
```

Thank you

**Comment by marcbaechinger** [comment]
Can you instead use the `AnalyticsListener` that you can add globally to `SimpleExoPlayer`? The events from the `MediaSourceEventListener` are delegated to the `AnalyticsListener`.

```
SimpleExoPlayer player = new SimpleExoPlayer.Builder(context)
    .setMediaSourceFactory(mediaSourceFactory)
    .build();

player.addAnalyticsListener(new MyAnalyticsListener() {
    public void onLoadStarted(
      EventTime eventTime, LoadEventInfo loadEventInfo, MediaLoadData mediaLoadData) {
          // your implementation
     }
})'
```

**Comment by GrilloLuca** [comment]
> Can you instead use the `AnalyticsListener` that you can add globally to `SimpleExoPlayer`? The events from the `MediaSourceEventListener` are delegated to the `AnalyticsListener`.
> 
> ```
> SimpleExoPlayer player = new SimpleExoPlayer.Builder(context)
>     .setMediaSourceFactory(mediaSourceFactory)
>     .build();
> 
> player.addAnalyticsListener(new MyAnalyticsListener() {
>     public void onLoadStarted(
>       EventTime eventTime, LoadEventInfo loadEventInfo, MediaLoadData mediaLoadData) {
>           // your implementation
>      }
> })'
> ```

thank you, it worked !
