### ISSUE TITLE
For DRM enabled content, Renew License keys after a particular duration, sent from server

### ISSUE THREAD

**Issue by nithinkumarnk88** [google/ExoPlayer#8777]
Hi Team,

We have a requirement in the project where we need to renew the license for a content after a particular duration.
This license renewal duration is configurable and sent from remote config.

So my question is: is there a way to set this renewal duration programmatically? so that the license is renewed after the set duration, for example after every 30 sec.

As per my exploration on google and Exoplayer code.. But no concrete solution available.
WidevineUtil.java has a method getLicenseDurationRemainingSec() 
Also the event to trigger key request is EVENT_KEY_REQUIRED which triggers the license acquisition.

But since the player handles all the events, I am not sure how to achieve the above requirement.

Any help would be much appreciated and will be really grateful. Thanks in Advance.

**Comment by icbaker** [comment]
What DRM scheme are you using?

The existing ExoPlayer license refresh mechanism reads license refresh periods from the license provided by the DRM license server. The precise details of configuring license servers & policies is outside the scope of this issue tracker, you're likely better off reaching out to your DRM vendor for assistance on this, or Widevine directly if you're a Widevine partner (https://support.google.com/widevine/contact/wv_cwipcf?hl=en).

**Comment by nithinkumarnk88** [comment]
Hi, Thank a lot for the reply.
We use Widevine scheme for DRM.
So what I understand from your comment is that we cannot explicitly set the renewal time in the Exoplayer from the client/application side and this renewal duration will be part of the license issued and renewal time must be handled by the DRM vendor only.
Please correct me if I am wrong?

**Comment by icbaker** [comment]
Correct - ExoPlayer doesn't provide a mechanism to sideload the license refresh duration.

DRM licenses often have a a license duration and a refresh duration. ExoPlayer currently doesn't retry license refreshes (https://github.com/google/ExoPlayer/issues/8241), so if you're configuring these periods consider making your refresh interval less than half your total license duration, as that will ensure any refresh failures are 'retried' by virtue of there being a second refresh event before the license expires.

**Comment by nithinkumarnk88** [comment]
Thanks a lot for the information and confirming on the refresh duration mechanism.
