### ISSUE TITLE
"Internal track renderer error" for play MP4 in some HTC machine

### ISSUE THREAD

**Issue by yuquan23459** [google/ExoPlayer#878]
Hi,I use Exoplayer 1.5.0 passing Library.jar for play MP4,But there has some error,the logcat is:

10-22 17:34:31.032 25358-25358/com.howdo.commonschool E/VideoPlayActivity: Uri is : http://vc.howdo.cc/E0F1ABCD5955CFC209D33D1E6072C808.mp4
10-22 17:34:31.152 25358-25358/com.howdo.commonschool E/TextHttpResponseHandler: {"code":1000,"msg":"\u4f5c\u4e1a\u53d1\u5e03\u6210\u529f!","data":{"ok":1,"nModified":0,"n":1,"err":null,"errmsg":null,"updatedExisting":true}}
10-22 17:34:31.162 25358-25358/com.howdo.commonschool E/VideoDetailActivity: onSuccess{"code":1000,"msg":"\u4f5c\u4e1a\u53d1\u5e03\u6210\u529f!","data":{"ok":1,"nModified":0,"n":1,"err":null,"errmsg":null,"updatedExisting":true}}
10-22 17:34:31.202 25358-26043/com.howdo.commonschool E/ExoPlayerImplInternal: Internal track renderer error.
10-22 17:34:31.202 25358-26043/com.howdo.commonschool E/ExoPlayerImplInternal: com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.extractor.ExtractorSampleSource$UnrecognizedInputFormatException: None of the available extractors (WebmExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, TsExtractor) could read the stream.
10-22 17:34:31.202 25358-26043/com.howdo.commonschool E/ExoPlayerImplInternal:     at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:154)
10-22 17:34:31.202 25358-26043/com.howdo.commonschool E/ExoPlayerImplInternal:     at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:145)
10-22 17:34:31.202 25358-26043/com.howdo.commonschool E/ExoPlayerImplInternal:     at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(ExoPlayerImplInternal.java:283)
10-22 17:34:31.202 25358-26043/com.howdo.commonschool E/ExoPlayerImplInternal:     at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:205)
10-22 17:34:31.202 25358-26043/com.howdo.commonschool E/ExoPlayerImplInternal:     at android.os.Handler.dispatchMessage(Handler.java:98)
10-22 17:34:31.202 25358-26043/com.howdo.commonschool E/ExoPlayerImplInternal:     at android.os.Looper.loop(Looper.java:157)
10-22 17:34:31.202 25358-26043/com.howdo.commonschool E/ExoPlayerImplInternal:     at android.os.HandlerThread.run(HandlerThread.java:61)
10-22 17:34:31.202 25358-26043/com.howdo.commonschool E/ExoPlayerImplInternal:     at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
10-22 17:34:31.202 25358-26043/com.howdo.commonschool E/ExoPlayerImplInternal:  Caused by: com.google.android.exoplayer.extractor.ExtractorSampleSource$UnrecognizedInputFormatException: None of the available extractors (WebmExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, TsExtractor) could read the stream.
10-22 17:34:31.202 25358-26043/com.howdo.commonschool E/ExoPlayerImplInternal:     at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractorHolder.selectExtractor(ExtractorSampleSource.java:807)
10-22 17:34:31.202 25358-26043/com.howdo.commonschool E/ExoPlayerImplInternal:     at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:738)
10-22 17:34:31.202 25358-26043/com.howdo.commonschool E/ExoPlayerImplInternal:     at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
10-22 17:34:31.202 25358-26043/com.howdo.commonschool E/ExoPlayerImplInternal:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
10-22 17:34:31.202 25358-26043/com.howdo.commonschool E/ExoPlayerImplInternal:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
10-22 17:34:31.202 25358-26043/com.howdo.commonschool E/ExoPlayerImplInternal:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
10-22 17:34:31.202 25358-26043/com.howdo.commonschool E/ExoPlayerImplInternal:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
10-22 17:34:31.202 25358-26043/com.howdo.commonschool E/ExoPlayerImplInternal:     at java.lang.Thread.run(Thread.java:864)
10-22 17:34:32.832 25358-25358/com.howdo.commonschool E/TextHttpResponseHandler: {"code":1000,"msg":"\u64cd\u4f5c\u6210\u529f","data":true}

I do not know how to solve it？

**Comment by ojw28** [comment]
That url is working fine for me. Are you sure you can reproduce this? Please try with the ExoPlayer demo app rather than in your own application, so we can be sure it's not an error in your own code. To do this, install the demo app in the 1.5.1 release (not 1.5.0), and start playback from the command line with:

`adb shell am start -a com.google.android.exoplayer.demo.action.VIEW -d http://vc.howdo.cc/E0F1ABCD5955CFC209D33D1E6072C808.mp4`

If you're still seeing the issue, do you see it only on certain devices? That would be strange, since very little platform specific code relates to the failure mode you're seeing. If so you need to state exactly which devices you can reproduce the issue, attach a full bug report, and provide any other information that might be of use as described [here](https://google.github.io/ExoPlayer/2015/10/01/reporting-issues.html).

**Comment by yuquan23459** [comment]
eh...I try it with the ExoPlayer demo app is ok,so i think it is possible cause by my own code,thanks!
