### ISSUE TITLE
Support forced subtitles from Dash manifest

### ISSUE THREAD

**Issue by laruedavid** [google/ExoPlayer#8781]
### Use case description
Video can have a "forced" subtitle track used, for example, when characters speak a different language from the main language.
Dash manifests support this feature using a role as mentioned in Amd. 5 for 23009-1: Dash-Industry-Forum/DASH-IF-IOP#165
ExoPlayer already manage forced subtitle with HLS.

### Proposed solution
ExoPlayer should parse the "forced_subtitle" role from DASH manifest. If no other subtitle tracks are selected it should show the forced subtitle corresponding to the audio language.

**Comment by icbaker** [comment]
Thanks for the request - would you be able to provide a sample stream containing the `forced_subtitle` role that we can use for testing?

**Comment by laruedavid** [comment]
Hi, thanks for your response. Unfortunately I'm not able to provide a sample stream for now.
Have you possibility to do differently or is it blocking for the feature ?

**Comment by icbaker** [comment]
We can add the support without a test stream.

**Comment by laruedavid** [comment]
Do you have any idea of when this feature could be added ?

**Comment by icbaker** [comment]
This is included in the 2.13.3 release that was just published.
