### ISSUE TITLE
How can I download multiple videos HLS like youtube?

### ISSUE THREAD

**Issue by Pisey-Nguon** [google/ExoPlayer#8788]
I have use this method to download video
  downloadManager?.addDownload(downloadRequest)
then I use it with other downloadRequest but It always downloads without waiting for the first download completed.

**Comment by ojw28** [comment]
It's unclear exactly what your question is, but if you want to restrict `DownloadManager` to downloading one item at a time then you can call `DownloadManager.setMaxParallelDownloads(1)`.
