### ISSUE TITLE
Does ExoPlayer support custom data retrieval methods?

### ISSUE THREAD

**Issue by sandersaares** [google/ExoPlayer#879]
I am interested in building a cache type of feature that would provide data to ExoPlayer even when the device is not connected to the network. Does any such data feeding capability exist in the ExoPlayer interfaces?

I would envision it as something like a method that takes in a URL (+headers, cookies and other metadata) and returns the data for that URL (+headers etc). Example of the Microsoft implementation: https://msdn.microsoft.com/en-us/library/jj822781(v=vs.90).aspx

**Comment by ojw28** [comment]
Yes, you'd want to implement a custom [DataSource](https://github.com/google/ExoPlayer/blob/master/library/src/main/java/com/google/android/exoplayer/upstream/DataSource.java)
