### ISSUE TITLE
Sound Played on Android App, not Chromecast Device

### ISSUE THREAD

**Issue by ghost** [google/ExoPlayer#8790]
I want to use Chromecast with live streaming audio.
I implemented Chromecast using Chromecast Manager

      ///MainActivity.java
              CastButtonFactory.setUpMediaRouteButton(this, buttonCast);
              castPlayerManager = new CastPlayerManager(this, castControlView, castContext);

      /// CastPlayerManager.java
              castPlayer = new CastPlayer(castContext);
              castPlayer.addListener(this);
              castPlayer.setSessionAvailabilityListener(this);
              castControlView.setPlayer(castPlayer);

        mediaItem = new MediaItem.Builder()
                .setUri("http://91.232.4.33:9590")
                .setMediaMetadata(new MediaMetadata.Builder().setTitle("Radio Host Cast Play MimeType: SS").build())
                .setMimeType(MIME_TYPE_SS)
                .build();

when cast session available, I started like follow

        castPlayer.clearMediaItems();
        castPlayer.setMediaItem(mediaItem, C.TIME_UNSET);

        castPlayer.setPlayWhenReady(false);
        castPlayer.prepare();

      ///Gradle
          implementation 'com.google.android.exoplayer:exoplayer:2.13.2'
          implementation 'com.google.android.exoplayer:extension-cast:2.13.2'
          implementation 'com.google.android.exoplayer:extension-mediasession:2.13.2'

But when I select Chromecast device on app, sound played on app. It's mistake
Sound should play on Chromecast device. and then also on Cast player view, play button not working...
I want to solve this issue. 
Thank you for your help

**Comment by ojw28** [comment]
This is almost certainly an issue with your application code, since `CastPlayer` doesn't contain any functionality that would allow it to play audio on the local device. Most likely your application is accidentally configuring another player, in addition to the `CastPlayer`, which is what's playing the sound locally.

There is insufficient information here for us to provide further guidance. If you believe it to be an ExoPlayer issue, please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that demonstrates the problem in a way that we can build locally. This could be an Android Studio project on GitHub, or zipped up and sent to dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Please also update this issue to indicate you’ve done this.

**Comment by ghost** [comment]
https://play.google.com/store/apps/details?id=player.radiohost.pl
My app is published on google play store, you can check Chromecast on app
I don't know what is issues on there.
There are two play, local player and cast player, but it's different player each other

**Comment by ghost** [comment]
It's CastPlayerManager.java code ..

`package player.radiohost.pl.player.cast;

import android.content.Context;

import com.google.android.exoplayer2.C;
import com.google.android.exoplayer2.MediaItem;
import com.google.android.exoplayer2.MediaMetadata;
import com.google.android.exoplayer2.Player;
import com.google.android.exoplayer2.Player.EventListener;
import com.google.android.exoplayer2.ext.cast.CastPlayer;
import com.google.android.exoplayer2.ext.cast.SessionAvailabilityListener;
import com.google.android.exoplayer2.ui.PlayerControlView;
import com.google.android.exoplayer2.util.MimeTypes;
import com.google.android.gms.cast.framework.CastContext;

import org.greenrobot.eventbus.EventBus;

import player.radiohost.pl.global.Global;
import player.radiohost.pl.player.stream.RadioPlaybackStatus;
import player.radiohost.pl.utils.Utils;

public class CastPlayerManager implements EventListener, SessionAvailabilityListener {

    //Mime Types
    public static final String MIME_TYPE_DASH = MimeTypes.APPLICATION_MPD;
    public static final String MIME_TYPE_HLS = MimeTypes.APPLICATION_M3U8;
    public static final String MIME_TYPE_SS = MimeTypes.APPLICATION_SS;
    public static final String MIME_TYPE_VIDEO_MP4 = MimeTypes.VIDEO_MP4;

    private final Context context;
    private final PlayerControlView castControlView;
    private final CastPlayer castPlayer;

    private final MediaItem mediaItem;

    private String status = "";
    private boolean isPlayWhenReady = false;
    private boolean isRadioStopped = false;

    public CastPlayerManager(Context context, PlayerControlView castControlView, CastContext castContext) {
        this.context = context;
        this.castControlView = castControlView;

        Utils.appendLog("============CastPlayerManager started============", Global.LOG_LOG);

        castPlayer = new CastPlayer(castContext);
        castPlayer.addListener(this);
        castPlayer.setSessionAvailabilityListener(this);
        castControlView.setPlayer(castPlayer);

        mediaItem = new MediaItem.Builder()
                .setUri("http://91.232.4.33:9590")
                .setMediaMetadata(new MediaMetadata.Builder().setTitle("Radio Host Cast Play MimeType: SS").build())
                .setMimeType(MIME_TYPE_SS)
                .build();
    }

    public void release() {
        if (isPlaying()) {
            castPlayer.stop(true);
        }
        castPlayer.clearMediaItems();
        castPlayer.setSessionAvailabilityListener(null);
        castPlayer.removeListener(this);
        castPlayer.release();

        Utils.appendLog("============CastPlayerManager release============", Global.LOG_LOG);
    }

    @Override
    public void onPlayWhenReadyChanged(boolean playWhenReady, int reason) {
        this.isPlayWhenReady = playWhenReady;

        if (status.equals(RadioPlaybackStatus.PLAYING) || status.equals(RadioPlaybackStatus.PAUSED)) {
            status = playWhenReady ? RadioPlaybackStatus.PLAYING : RadioPlaybackStatus.PAUSED;
            EventBus.getDefault().post(status);
        }
    }

    @Override
    public void onPlaybackStateChanged(int state) {
        switch (state) {
            case Player.STATE_IDLE:
                status = isRadioStopped ? CastPlaybackStatus.STOPPED : CastPlaybackStatus.IDLE;
                break;
            case Player.STATE_BUFFERING:
                status = CastPlaybackStatus.BUFFERING;
                break;
            case Player.STATE_READY:
                status = isPlayWhenReady ? CastPlaybackStatus.PLAYING : CastPlaybackStatus.PAUSED;
                isRadioStopped = true;
                break;
            case Player.STATE_ENDED:
                status = CastPlaybackStatus.STOPPED;
                break;
            default:
                status = CastPlaybackStatus.IDLE;
        }
        Utils.appendLog("=============CastPlayerManager player status===============", Global.LOG_LOG);
        Utils.appendLog(status, Global.LOG_LOG);

        EventBus.getDefault().post(status);
    }

    @Override
    public void onCastSessionAvailable() {
        Utils.appendLog("=============CastPlayerManager onCastSessionAvailable===============", Global.LOG_LOG);
        castControlView.show();
        startCastPlayer();
    }

    @Override
    public void onCastSessionUnavailable() {
        Utils.appendLog("=============CastPlayerManager onCastSessionUnavailable===============", Global.LOG_LOG);
        castControlView.hide();
        stopCastPlayer();
    }

    public boolean isPlaying() {
        return status.equals(CastPlaybackStatus.PLAYING);
    }

    public void startCastPlayer() {
        if (isPlaying())
            stopCastPlayer();

        castPlayer.clearMediaItems();
        castPlayer.setMediaItem(mediaItem, C.TIME_UNSET);

        castPlayer.setPlayWhenReady(false);
        castPlayer.prepare();

        Utils.appendLog("=============CastPlayerManager prepare player.===============", Global.LOG_LOG);
    }

    public void stopCastPlayer() {
        castPlayer.stop();
        castPlayer.clearMediaItems();
        Utils.appendLog("=============CastPlayerManager stop player.===============", Global.LOG_LOG);
    }
}`

**Comment by ojw28** [comment]
There's not much we can do with the information provided above. If you believe this to be an ExoPlayer issue, please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that demonstrates the problem in a way that we can build locally. This could be an Android Studio project on GitHub, or zipped up and sent to dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Please also update this issue to indicate you’ve done this.

**Comment by ghost** [comment]
I sent source code to dev.exoplayer@gmail.com

**Comment by ojw28** [comment]
As above, we need a **minimal** reproducible example. It's not the job of this issue tracker for us to debug your entire application.

**Comment by ghost** [comment]
My app is very short
You can run without any action, and then will see bottom cast button
I think it's minimal product.

**Comment by ojw28** [comment]
Sorry, but the app provided is not what we'd class as a minimal reproducible example.
