### ISSUE TITLE
How to download DRM using drm server url

### ISSUE THREAD

**Issue by olgunkaya** [google/ExoPlayer#8791]
Hi,

I have been trying to implement offline playback of DRM protected media. I did go through the [this official page ](https://exoplayer.dev/downloading-media.html) and the demo app several times but ended up here to ask the question.

In the demo app there is a background task WidevineOfflineLicenseFetchTask which is used to download the keys using the stream/manifest itself. But in my case I have the key server url. Debugged my app, checked the DownloadHelper.Callback onPrepared method and there is no track contains a Format with drmInitData.

The demo app has a note, an internal one, like below : 
_// TODO(internal b/163107948): Support cases where DrmInitData are not in the manifest._

So, my question is how to download these keys? Is there utility etc in exo player library ? If I somehow be able to download the keys (I am quite new to media APIs) how can I provide these keys to the SimplePlayer ? 

Note : ExoPlayer is able to play the content if I provide the license url. But obviously it gets these keys somewhere deep in the library :(

Exo Player version : 2.11.4

**Comment by icbaker** [comment]
It sounds like you want the [`OfflineLicenseHelper`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/drm/OfflineLicenseHelper.html).

This is used by the demo app `WidevineOfflineLicenseFetchTask` you mentioned - but you can integrate it differently and pass the license (key server) URL however you like.

> there is no track contains a Format with drmInitData.

Possibly your media isn't prepared correctly? Hard to say without access to the media. Please either upload it here or send to dev.exoplayer@gmail.com using a subject in the format "Issue #1234" (where "#1234" should be replaced with this issue number.) Please also update this issue to indicate you’ve done this.

Or if you know the details that should be in the `drmInitData` then you can augment the `Format` from the media before passing it to the `OfflineLicenseHelper` - using `Format#buildUpon()`

**Comment by olgunkaya** [comment]
@icbaker, thanks for the info and reply. Following this post, I kept looking at the media and finally realized that even the API response, I am working with, claims there is encryption, there was not. so I think this post would be considered to be completed. I checked correct manifests and see the <ContentProtection> tags with different DRM entries.

```
<ContentProtection schemeIdUri="urn:mpeg:dash:mp4protection:2011" value="cenc" />
<ContentProtection schemeIdUri="urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed" cenc:default_KID="...." xmlns:cenc="urn:mpeg:cenc:2013">
        <cenc:pssh>.....</cenc:pssh>
</ContentProtection>
<ContentProtection xmlns:mspr="urn:microsoft:playready" schemeIdUri="urn:uuid:9a04f079-9840-4286-ab92-e65be0885f95">
        <mspr:pro>...</mspr:pro>
</ContentProtection>

```
