### ISSUE TITLE
Downloading/Caching live streams

### ISSUE THREAD

**Issue by im244** [google/ExoPlayer#8792]
Hey everyone, 

First let me thank you for the fantastic job you have done so far with ExoPlayer, it really is amazing.

So my app is a live tv channels app that connect directly to open channels in different countries.
The idea is to offer live caching for these live streams, so the player will cache X minutes or up to X available space and the user will be able to go backward forward within the defined limit.
As I searched and tried to find an already available solution I found none and saw the exoplayer does not support live streams downloads/caching.

The streams are mostly TS type streams, at the moment I offer an option to download or better say "record" to streams without any issues as I just download the content of the stream and save it locally, I was thinking about downloading the file and playing it at the same time, but then I am limited by the buffer the player loaded at the time of loading the file and the buffer/length of the stream within Exoplayer does not update accordingly the download progress.
I would love to see if there is any available solutions or ideas of what I can do.

Best regards.

**Comment by ojw28** [comment]
Downloading live streams is tracked by https://github.com/google/ExoPlayer/issues/3877. Until we have time to support that directly in the library, I don't think we have any further solutions or ideas to offer here. Hence I'll go ahead and close this as a duplicate.
