### ISSUE TITLE
IMA Extension: How to implement onAdEvent

### ISSUE THREAD

**Issue by nbasbous** [google/ExoPlayer#8795]
Hello ExoPlayer Team,

I need to check if there is a plan to expose the onAdEvent, so I can register to listen to Adds events.
BR

**Comment by ojw28** [comment]
I think this is already exposed via:

https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/ext/ima/ImaAdsLoader.Builder.html#setAdEventListener(com.google.ads.interactivemedia.v3.api.AdEvent.AdEventListener)

For example:

```
adsLoader = new ImaAdsLoader.Builder(/* context= */ this).setAdEventListener(
    new AdEventListener() {
      @Override
      public void onAdEvent(AdEvent adEvent) {
        ... 
      }
    }).build();
```
