### ISSUE TITLE
How to download video hls with different quality without use DownloadHelper?

### ISSUE THREAD

**Issue by Pisey-Nguon** [google/ExoPlayer#8799]

**Comment by ojw28** [comment]
As with your other issues, it's unclear what your question is here. `DownloadHelper` is specifically for this purpose, so if you want to do this, why would you not use the class that's intended for this purpose? If you want to use something else, you'll need to replicate the same logic that `DownloadHelper` implements yourself. You can look at the source code to see exactly what it's doing internally.

As a general point, please don't file one sentence issues. It's very unlikely they contain sufficient information for us to provide a helpful response.
