### ISSUE TITLE
SegmentBase calculate segment count in accurate.

### ISSUE THREAD

**Issue by zgzong** [google/ExoPlayer#8804]
When play or download a number-based VoD stream, player report the last segment is missing. 

The stream information: 
mediaPresentationDuration="PT2931.820S"
<SegmentTemplate timescale="90000" initialization="$RepresentationID$-init.m4s" media="$RepresentationID$-181400-i-$Number$.m4s" startNumber="1" duration="179989" presentationTimeOffset="3600"/>

- ExoPlayer version number 
2.13.1

- Android version
all os version

- Android device
Samsung tablet SMP610

SegmentBase.java
`
public int getSegmentCount(long periodDurationUs) 
...
        long durationUs = (duration * C.MICROS_PER_SECOND) / timescale;
        return (int) Util.ceilDivide(periodDurationUs, durationUs);
`

long durationUs = (179989 * 1000000) / 90000 = (long) 1,999,877.7777777777777777777777778 = 1999877
 Util.ceilDivide(periodDurationUs, durationUs) = Util.ceilDivide( 2931820000 / 1999877) = 1467

Actually: 
Based on https://dashif-documents.azurewebsites.net//DASH-IF-IOP/pull/210/DASH-IF-IOP.html#timing-addressing-simple-to-explicit
SegmentCount = Ceil(AsSeconds(Period@duration) / ( SegmentTemplate@duration / SegmentTemplate@timescale)) 
 = Ceil ( 2931.820 / (179989 / 90000) ) = 1466.

**Comment by ojw28** [comment]
Thanks for reporting this. The problem with:
```
long durationUs = (duration * C.MICROS_PER_SECOND) / timescale;
return (int) Util.ceilDivide(periodDurationUs, durationUs);
```
is that `durationUs` is rounded down to the nearest microsecond. We can avoid any loss of precision by doing the calculation like this instead:
```
return (int) Util.ceilDivide(periodDurationUs * timescale, duration * C.MICROS_PER_SECOND);
```

**Comment by zgzong** [comment]
@ojw28 Thanks for your confirmation. The proposal works as ceilDivide will truncate the result only keep the integer part.

**Comment by ojw28** [comment]
We are a little concerned about the possibility of overflow of `periodDurationUs * timescale`, so will give this a bit more thought before submitting a fix.
