### ISSUE TITLE
Play after static frame about 1 second 

### ISSUE THREAD

**Issue by arlimm318** [google/ExoPlayer#8805]
Some video play after static frame about 1 second .
the smaple video file is
https://1drv.ms/u/s!AmEXoF8AZryCdkmU-ujO1J2ZMF8?e=XkYDWe

 I analyzed the ts, Each I frame has two PPS. I'm not sure if that's what caused it.
exo version: 2.11.7
device  : Android 4.4

**Comment by ojw28** [comment]
Behaviour seems to be device dependent. It plays successfully on a Galaxy S20. The video decoder fails on a Pixel 4. It sounds like you are seeing something different on the device you're testing with.

It seems likely that the video bitstream is malformed. Playing this stream in VLC gives quite a lot of "waiting for SPS/PPS" warnings, although I'm not sure if that's necessarily relevant. The first second of content cannot be played initially, and if you try seeking backwards to it there's some frame corruption.

Given this seems like an issue that's specific to this particular piece of content, we cannot justify spending further time investigating. If you have time to do so, I'd suggest you dig deeper to see if the video bitstream is malformed.
