### ISSUE TITLE
"Vicious" cycle of downloading the same segment lots of times after sudden improvement of network conditions

### ISSUE THREAD

**Issue by sruditsky** [google/ExoPlayer#8807]
We use ExoPlayer 2.12.3

In one of the tests we play a (DASH) media stream on a high throughput network, then we throttle the network to the level which causes the player buffer to be gradually depleted.
Shortly after the buffer gets empty we restore network to the normal (i.e. high throughput) conditions and let the player play.

The _expected_ result (of the last step in the sequence above) would be that the player recognizes better network conditions and selects a high quality video representation.

The _actual_ result is that in some cases the player gets into a loop of downloading the same segment multiple times and switches to a higher quality video only long time (~20 min) after this.

The reason for this is as follows:
Let's start from a state where the player just downloaded a low quality video chunk and is deciding what to download next.

One of the steps in this process is DefaultDashChunkSource.getPreferredQueueSize() which calls AdaptiveTrackSelection.evaluateQueueSize() which decides that it is OK to discard the chunk which was just downloaded, because the network conditions are great, but the queue contains some low quality media chunk.

At some point after this DefaultDashChunkSource.getNextChunk() calls AdaptiveTrackSelection.updateSelectedTrack(), which looks at the buffer size and decides _"The selected track is a higher quality, but we have insufficient buffer to safely switch up. Defer switching up for now."_ and selects the same quality as before.

_Note that evaluateQueueSize() does not take into account that after removing some part of the queue this queue may fall under the threshold of minDurationForQualityIncreaseUs and thus become not eligible for the increase of quality which evaluateQueueSize() is assuming to happen._

The result is getting stuck on downloading the same segment (with the same quality) dozens of times till the playback eventually reaches the position represented by this segment and it stops being eligible for the quality increase.

As an attempt of a workaround I added to AdaptiveTrackSelection the following method:

```Java
   private boolean isEligibleForQualityIncrease(long playbackPositionUs, 
                                                int queueSize, 
                                                List<? extends MediaChunk> queue) {
    long loadPositionUs = (queueSize > 0) ? queue.get(queueSize - 1).endTimeUs : playbackPositionUs;
    long bufferedDurationUs = loadPositionUs - playbackPositionUs;
    return bufferedDurationUs >= minDurationForQualityIncreaseUs;
  }
```
 which then is called from the if in evaluateQueueSize():
```Java
     if (playoutDurationBeforeThisChunkUs >= minDurationToRetainAfterDiscardUs
          && format.bitrate < idealFormat.bitrate
          && format.height != Format.NO_VALUE && format.height < 720
          && format.width != Format.NO_VALUE && format.width < 1280
          && format.height < idealFormat.height
          // However, never allow the new queue to be below the size eligible for the quality increase
          && isEligibleForQualityIncrease(playbackPositionUs, i, queue)) {
        return i;
      }
```  

and I still cannot reproduce this issue after this change.

**Comment by sruditsky** [comment]
I realized this issue can be avoided by constructing AdaptiveTrackSelection with sufficiently high value for minDurationToRetainAfterDiscardMs. 
However, I would still say that what is described above is a bug.

**Comment by AquilesCanta** [comment]
@tonihei, the reporter describes this as an ABR issue. Can you take a look?

**Comment by AquilesCanta** [comment]
@sruditsky Might be useful to provide the content with which you are reproducing the issue. It could help efficient diagnosing on our side.

**Comment by sruditsky** [comment]
@AquilesCanta We reproduce this issue with a proprietary content which I am not allowed to provide, however, to my best understanding this issue can be reproduces with any content containing video of both SD and HD resolution.

As I mentioned above the problem in our case happened because we passed to AdaptiveTrackSelection.Factory() value for minDurationToRetainAfterDiscardMs which was lower than minDurationForQualityIncreaseMs.

Should this be considered a valid configuration?
From reading documentation it is difficult to conclude if any specific relationship between these two parameters should be maintained.

If such requirement does exist it would be nice to prevent creation of AdaptiveTrackSelection with erroneous set of parameters.

If however, the configuration above _is_ valid then AdaptiveTrackSelection() has the following bug.
Let's start with a situation where the _currentFormat_ is the lowest quality format while the getAllocatedBandwidth() returns value much higher than the bitrate of the highest quality variant. 
And the duration of the media in the buffer is higher than minDurationToRetainAfterDiscardMs but lower than minDurationForQualityIncreaseMs.

The result is that updateSelectedTrack() does not switch to higher variant and causes download of a low quality chunk. Then evaluateQueueSize() decides to discard this chunk because it is low quality. However, updateSelectedTrack() selects the same low quality chunk again and so on and so forth.

**Comment by tonihei** [comment]
> As I mentioned above the problem in our case happened because we passed to AdaptiveTrackSelection.Factory() value for minDurationToRetainAfterDiscardMs which was lower than minDurationForQualityIncreaseMs.
Should this be considered a valid configuration?
From reading documentation it is difficult to conclude if any specific relationship between these two parameters should be maintained.
If such requirement does exist it would be nice to prevent creation of AdaptiveTrackSelection with erroneous set of parameters.

I agree with that. The class clearly assumes that `minDurationToRetainAfterDiscardMs` is greater or equal than `minDurationForQualityIncreaseMs`. Otherwise you may run into a cycle of reloading the same format as you described. 

Actually, this issue already came up in #7582 and enforcing this relationship was mentioned in https://github.com/google/ExoPlayer/issues/7582#issuecomment-653450969 Issue 1, second improvement idea.  Seems we never implemented this though :)

**Comment by ojw28** [comment]
It looks like we enforced the relationship as described above, so I think this can now be closed.
