### ISSUE TITLE
Does exoplayer can play (support ) the 8k 360 degree video?

### ISSUE THREAD

**Issue by onetwobin** [google/ExoPlayer#8809]
Does exoplayer can play the 8k 360 degree video?

What kind of android device is required?

thank you !

**Comment by AquilesCanta** [comment]
Assuming the device is capable of decoding (and I guess also gl-rendering) 8K streams. ExoPlayer shouldn't be a limiting factor. 

> What kind of android device is required?

I would start with a device that advertises 8K support. 

Assigning to @andrewlewis in the context of vr.

**Comment by andrewlewis** [comment]
I don't really have anything vr-specific to add to @AquilesCanta's points above. The limitation comes from the capabilities of the decoders or graphics system and you'll need to do your own research to find out about device capabilities.

For what it's worth I'd start by searching for references to devices that appear to support 8K capture on the web (devices that can capture 8K will almost certainly be able to decode it!). The [Android CDD](https://source.android.com/compatibility/cdd) documents requirements for all Android devices but they are below 8K resolution currently I'm afraid.

**Comment by onetwobin** [comment]
Thank you very much. I confirmed that exoplayer can play 8k 360 degree video by Android device (Samsung galaxy S20).
