### ISSUE TITLE
SIGABRT libstagefright MuxOMX freeNode (OS 7, Samsung devices)

### ISSUE THREAD

**Issue by greyski** [google/ExoPlayer#8811]
Android OS 7.0
Device: Samsung S6 Edge+, Galaxy Note5, Galaxy S6, Galaxy S6 Active
ExoPlayer: 2.13.2 & 2.12.3

```
SIGABRT Abort program 
    /system/lib64/libc.so:439732 tgkill
    /system/lib64/libc.so:428628 pthread_kill
    /system/lib64/libc.so:147308 raise
    /system/lib64/libc.so:117232 abort
    /system/lib64/libcutils.so:65928 __android_log_bwrite
    /system/lib64/libstagefright.so:1167944 android::MuxOMX::freeNode(unsigned int)
    /system/lib64/libstagefright.so:718156 android::ACodec::LoadedState::onShutdown(bool)
    /system/lib64/libstagefright.so:718060 android::ACodec::LoadedState::stateEntered()
    /system/lib64/libstagefright_foundation.so:71372 android::AHierarchicalStateMachine::changeState(android::sp<android::AState> const&)
    /system/lib64/libstagefright.so:732600 android::ACodec::IdleToLoadedState::onOMXEvent(OMX_EVENTTYPE, unsigned int, unsigned int)
    /system/lib64/libstagefright.so:703840 android::ACodec::BaseState::onOMXMessage(android::sp<android::AMessage> const&)
    /system/lib64/libstagefright_foundation.so:70576 android::AHierarchicalStateMachine::handleMessage(android::sp<android::AMessage> const&)
    /system/lib64/libstagefright.so:702840 android::ACodec::BaseState::onOMXMessageList(android::sp<android::AMessage> const&)
    /system/lib64/libstagefright.so:702168 android::ACodec::BaseState::onMessageReceived(android::sp<android::AMessage> const&)
    /system/lib64/libstagefright_foundation.so:70576 android::AHierarchicalStateMachine::handleMessage(android::sp<android::AMessage> const&)
    /system/lib64/libstagefright_foundation.so:69916 android::AHandler::deliverMessage(android::sp<android::AMessage> const&)
    /system/lib64/libstagefright_foundation.so:85696 android::AMessage::deliver()
    /system/lib64/libstagefright_foundation.so:74316 android::ALooper::loop()
    /system/lib64/libutils.so:74780 android::Thread::_threadLoop(void*)
    /system/lib64/libc.so:426588 0x75dd9b425c
    /system/lib64/libc.so:121860 0x75dd969c04
    unknown 0x0
```

Unfortunately, we have not been able to reproduce this locally, and I had trouble finding this exact issue mentioned in the repo.

We're seeing this happen when videos are autoplaying on-screen (via breadcrumbs, again cannot reproduce locally). I could provide our entire ExoPlayer setup (Factories etc.) as well if needed. We believe this is related to a `libstagefright` issue that was resolved some time way back when?

Any feedback is helpful. Thanks!

**Comment by greyski** [comment]
Potentially related? https://github.com/google/ExoPlayer/issues/6168

However, this issue does not cause a crash, but instead ExoPlayer fails during playback and cannot recover the stream.

**Comment by AquilesCanta** [comment]
Is this issue Samsung specific? Have you seen occurrences in other devices? Pixel, for instance?

If this is an issue which is specific to Samsung, there's nothing we can do on our side. We don't even have enough info for reasonably report this, so I would advise you try gathering some more info: A bug report and a minimal sample APK would be good starting points. You could attempt to contact the device manufacturer directly.

Can you think of any way in which we could be able to assist? Is there any evidence of this being an ExoPlayer issue?

**Comment by greyski** [comment]
This is 100% Samsung specific to OS 7.0.

I was hoping something in the trace would look familiar to someone here. I can work on getting an official bug report, not too sure about a sample APK.

Our evidence of it being related to ExoPlayer is our breadcrumbs showing that 100% of these native crashes occur during a video playback session (we don't fork/or implement anything outside of the ExoPlayer library). I'll try to get a better report with more information, but I believe it'll be easier for us to simply disable video autoplaying for these specific devices & OS version.

Thanks for looking!

**Comment by AquilesCanta** [comment]
> Our evidence of it being related to ExoPlayer is our breadcrumbs showing that 100% of these native crashes occur during a video playback session

I will rephrase as "Is there any evidence of this being a bug in the ExoPlayer codebase (as opposed to a device issue, for example)?"

Being samsung specific, there's not much we can do except maybe report. But for that I don't think the stacktrace will be enough. I suggest you report directly to Samsung, since they might be able to better follow up on the report. If you find anything pointing at exoplayer, or you are able to reproduce reasonably consistently, please post below and I'll reopen the issue. I don't think there's anything actionable for us as things stand.
