### ISSUE TITLE
Generating Relation Between Offline License and Downloaded Content

### ISSUE THREAD

**Issue by olgunkaya** [google/ExoPlayer#8813]
Hi,

I am trying to understand how to create the downloaded license's keySetId and downloaded track. Normally If I am on the latest release that's not an issue. Because we can create a relation between keySetId and download request during the request generation. But since I am on 2.11.4 (due to some other dependencies in the project) I can not find a way to create the relation. 

Should I save the keyset id with the related content id in local storage or some place like that ? Or is there a supportive utility that can manage the keysetId and content relation ?

**Comment by ojw28** [comment]
`DownloadRequest.data` is available in 2.11.4, and can be used to hold arbitrary application defined data. So you can use that. Note that if you're serializing multiple pieces of data into that field, it's your responsibility to handle versioning and compatibility of the data across different versions of your application.

As you've noted, you can also persist the mapping with your own application code.

**Comment by olgunkaya** [comment]
Thanks @ojw28, I was using that field to hold metadata like title etc.. But, now I will add my piece of keySetId array there too.
