### ISSUE TITLE
Any way to pass/modify the headers of the chunk request

### ISSUE THREAD

**Issue by custadian** [google/ExoPlayer#8815]
Is there any way to pass the headers on every ts/m4s segment ?

I know that I can pass the headers using `setDefaultRequestProperties` on `OkHttpDataSource.Factory` or `DefaultHttpDataSource.Factory()` but it is one time. Is there any way to pass the headers on the fly ?

One more question, in case, if I write my own `DefaultHttpDataSource` by extending it to `BaseDataSource` then also is there any way to pass the httpDataSource during the playback because I can see that on `SimpleExoPlayer` there is no `buildUpon` method.

Can you please help on it ?

**Comment by AquilesCanta** [comment]
> I know that I can pass the headers using setDefaultRequestProperties on OkHttpDataSource.Factory or DefaultHttpDataSource.Factory() but it is one time

This shouldn't be the case. The default request properties should apply to all HTTP requests performed by that DataSource. Are you injecting your customized DataSourceFactory to the MediaSource? Please share a **small** snippet of what you've tried.

> then also is there any way to pass the httpDataSource during the playback

No, you cannot change the data source during playback. Setting the data source factory happens at construction. Please clarify what you are trying to do.

**Comment by custadian** [comment]
> This shouldn't be the case. The default request properties should apply to all HTTP requests performed by that DataSource. Are you injecting your customised DataSourceFactory to the MediaSource? Please share a **small** snippet of what you've tried.

Right @AquilesCanta. I am setting request properties using `setDefaultRequestProperties`. Passing the headers. Yes it is getting applied on all HTTP requests performed by DataSource.

> then also is there any way to pass the httpDataSource during the playback

I have passed the headers using `setDefaultRequestProperties` on `DefaultHttpDataSource`. I am looking for a solution where I can modify the headers on the fly (during the playback). You can assume a case that a token is required for every chunk request and token is expired during the playback

**Comment by AquilesCanta** [comment]
In that case you should implement a custom factory which will return a DataSource implementation that wraps one of the base implementations but when `DataSource.open` is called, it adds the required request headers to the received `dataSpec`.

So your DataSource.open implementation will look something like:
```
@Override
 public long open(DataSpec dataSpec) throws IOException {
   return wrappedDataSource.open(dataSpec.buildUpon().setHttpRequestHeaders(myRequestHeaders).build());
}
```
Does this work for you?

**Comment by custadian** [comment]
I will try it @AquilesCanta Thank you

**Comment by tonihei** [comment]
Specifically for this case, I think you shouldn't write a custom `DataSource`, but instead use `ResolvingDataSource` as explained in our documentation: https://exoplayer.dev/customization.html#customizing-server-interactions

**Comment by GouravSna** [comment]
I will give it a try @tonihei thanks

**Comment by custadian** [comment]
I will give a try @tonihei thanks

**Comment by custadian** [comment]
Hi @AquilesCanta @tonihei , thanks for the help. After your suggestions, I have a way to achieve it. Following links are helping me more on this.

https://github.com/google/ExoPlayer/issues/5779
https://juliensalvi.medium.com/building-custom-datasource-for-exoplayer-87fd16c71950
