### ISSUE TITLE
Audio/ Speed controls shown when Overflow button is clicked are not accessible on all FireTV devices

### ISSUE THREAD

**Issue by Manvendra-Jadon** [google/ExoPlayer#8818]
We are getting rejection on amazon store, saying Audio/ Speed controls in Overflow settings are not accessible on all devices.
Here is the list: 
![rejected_devices](https://user-images.githubusercontent.com/70095620/114769324-b2bfeb80-9d87-11eb-8a0b-f630e43a4c55.png)

For now, as a workaround i m trying to remove overflow button from player controls.

**Comment by AquilesCanta** [comment]
@ojw28 Assigning to you in the context of UI.

**Comment by ojw28** [comment]
There's very little information here to help us to help you effectively:

* Please could you clarify what you mean when you say that the controls are "not accessible"? Do you mean that it's impossible to access the settings using the remote on these devices, or is this specifically about [Accessibility](https://developer.android.com/guide/topics/ui/accessibility)? A video demonstrating the problem would be very helpful.
* Is the issue specific to FireOS devices, or does it occur on AndroidTV devices as well?
