### ISSUE TITLE
m4a stream issue

### ISSUE THREAD

**Issue by kenroyandfamily** [google/ExoPlayer#882]
In the Samples.java file of the ExoPlayerDemo I replace the " public static final Sample[] MISC = new Sample[]" lines with:

public static final Sample[] MISC = new Sample[] {
    new Sample("Test",
    		"http://od.pianostream.com:8080/pianosolo/HE-AAC%2064/Main/Christian%20Lindquist-Solo%20Piano%20Diary-Five.m4a?username=iphone1&password=0dce6f76ac1a29d276c0c6dabe60519c", PlayerActivity.TYPE_OTHER),   };

This does not work in the ExoPlayerDemo.  The stream works fine in iTunes and my iPhone so I know it is not an issue with the link or the file.  iTunes shows file as "MPEG-4 audio stream, 64kbps 44.100 kHz".

The following code does work fine in the ExoPlayerDemo:

public static final Sample[] MISC = new Sample[] {
    new Sample("Test",
    		"http://od.pianostream.com:8080/pianosolo/MP3%20128/Main/Christine%20Brown-Promise-Moonlight%20Embrace.mp3?username=iphone1&password=0dce6f76ac1a29d276c0c6dabe60519c", PlayerActivity.TYPE_OTHER),   };

This is an mp3 file and iTunes shows it as "MPEG audio stream, 128 kbps, 44.100kHz".

The first stream is m4a and the second is mp3.  Did I code the m4a stream correctly by using PlayerActivity.TYPE_OTHER?  There was no example for playing m4a so I believe I may have simply coded it incorrectly.

Thanks,

Ken

**Comment by ojw28** [comment]
Both of the links above are dead at the moment. I got one of them to work once in the past 10 minutes or so, but all other attempts have resulted in ERR_CONNECTION_REFUSED. This is just in Chrome Browser on a laptop. Please update this bug if/when they're reliably available. Thanks!

**Comment by kenroyandfamily** [comment]
Is my syntax correct for playing a m4a file?

**Comment by ojw28** [comment]
Yes. This appears to be a server issue. I did manage to download the content eventually. I temporarily uploaded it elsewhere, and it worked perfectly from that server.

It appears that the server you're using repeatedly refuses connections. It's either doing some very harsh request throttling, or it doesn't properly support range requests. The latter would explain why the m4a doesn't work whilst the mp3 does.

**Comment by kenroyandfamily** [comment]
Here's a link that requires no authentication:

 new Sample("Google Play (MP3 Audio)",
    		"http://od.pianostream.com:9000/pianosolo/HE-AAC%2064/Featured/Amy%20Janelle-Whisperings-%20Solo%20Piano.%20Vol.%202-A%20New%20Direction.m4a", PlayerActivity.TYPE_OTHER), 
    
and I get the following java error in the ExoPlayerDemo:

10-21 17:31:32.001: E/ExoPlayerImplInternal(29074): Internal track renderer error.
10-21 17:31:32.001: E/ExoPlayerImplInternal(29074): com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to http://od.pianostream.com:9000/pianosolo/HE-AAC%2064/Featured/Amy%20Janelle-Whisperings-%20Solo%20Piano.%20Vol.%202-A%20New%20Direction.m4a
10-21 17:31:32.001: E/ExoPlayerImplInternal(29074): 	at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:154)
10-21 17:31:32.001: E/ExoPlayerImplInternal(29074): 	at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:141)
10-21 17:31:32.001: E/ExoPlayerImplInternal(29074): 	at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:438)
10-21 17:31:32.001: E/ExoPlayerImplInternal(29074): 	at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
10-21 17:31:32.001: E/ExoPlayerImplInternal(29074): 	at android.os.Handler.dispatchMessage(Handler.java:98)
10-21 17:31:32.001: E/ExoPlayerImplInternal(29074): 	at android.os.Looper.loop(Looper.java:145)
10-21 17:31:32.001: E/ExoPlayerImplInternal(29074): 	at android.os.HandlerThread.run(HandlerThread.java:61)
10-21 17:31:32.001: E/ExoPlayerImplInternal(29074): 	at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
10-21 17:31:32.001: E/ExoPlayerImplInternal(29074): Caused by: com.google.android.exoplayer.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to http://od.pianostream.com:9000/pianosolo/HE-AAC%2064/Featured/Amy%20Janelle-Whisperings-%20Solo%20Piano.%20Vol.%202-A%20New%20Direction.m4a
10-21 17:31:32.001: E/ExoPlayerImplInternal(29074): 	at com.google.android.exoplayer.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:202)
10-21 17:31:32.001: E/ExoPlayerImplInternal(29074): 	at com.google.android.exoplayer.upstream.DefaultUriDataSource.open(DefaultUriDataSource.java:136)
10-21 17:31:32.001: E/ExoPlayerImplInternal(29074): 	at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:733)
10-21 17:31:32.001: E/ExoPlayerImplInternal(29074): 	at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
10-21 17:31:32.001: E/ExoPlayerImplInternal(29074): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
10-21 17:31:32.001: E/ExoPlayerImplInternal(29074): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
10-21 17:31:32.001: E/ExoPlayerImplInternal(29074): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
10-21 17:31:32.001: E/ExoPlayerImplInternal(29074): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
10-21 17:31:32.001: E/ExoPlayerImplInternal(29074): 	at java.lang.Thread.run(Thread.java:818)
10-21 17:31:32.001: E/ExoPlayerImplInternal(29074): Caused by: java.net.ProtocolException: Unexpected status line: GET /pianosolo/HE-AAC%2064/Featured/Amy%20Janelle-Whisperings-%20Solo%20Piano.%20Vol.%202-A%20New%20Direction.m4a HTTP/1.1
10-21 17:31:32.001: E/ExoPlayerImplInternal(29074): 	at com.android.okhttp.internal.http.StatusLine.<init>(StatusLine.java:38)
10-21 17:31:32.001: E/ExoPlayerImplInternal(29074): 	at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:203)
10-21 17:31:32.001: E/ExoPlayerImplInternal(29074): 	at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:119)
10-21 17:31:32.001: E/ExoPlayerImplInternal(29074): 	at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:798)
10-21 17:31:32.001: E/ExoPlayerImplInternal(29074): 	at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:405)
10-21 17:31:32.001: E/ExoPlayerImplInternal(29074): 	at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:349)
10-21 17:31:32.001: E/ExoPlayerImplInternal(29074): 	at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:517)
10-21 17:31:32.001: E/ExoPlayerImplInternal(29074): 	at com.google.android.exoplayer.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:199)
10-21 17:31:32.001: E/ExoPlayerImplInternal(29074): 	... 8 more
10-21 17:31:32.041: I/ACodec(29074):  [OMX.SEC.aac.dec] Now uninitialized
10-21 17:31:32.051: E/EventLogger(29074): playerFailed [3.97]
10-21 17:31:32.051: E/EventLogger(29074): com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to http://od.pianostream.com:9000/pianosolo/HE-AAC%2064/Featured/Amy%20Janelle-Whisperings-%20Solo%20Piano.%20Vol.%202-A%20New%20Direction.m4a
10-21 17:31:32.051: E/EventLogger(29074): 	at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:154)
10-21 17:31:32.051: E/EventLogger(29074): 	at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:141)
10-21 17:31:32.051: E/EventLogger(29074): 	at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:438)
10-21 17:31:32.051: E/EventLogger(29074): 	at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
10-21 17:31:32.051: E/EventLogger(29074): 	at android.os.Handler.dispatchMessage(Handler.java:98)
10-21 17:31:32.051: E/EventLogger(29074): 	at android.os.Looper.loop(Looper.java:145)
10-21 17:31:32.051: E/EventLogger(29074): 	at android.os.HandlerThread.run(HandlerThread.java:61)
10-21 17:31:32.051: E/EventLogger(29074): 	at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
10-21 17:31:32.051: E/EventLogger(29074): Caused by: com.google.android.exoplayer.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to http://od.pianostream.com:9000/pianosolo/HE-AAC%2064/Featured/Amy%20Janelle-Whisperings-%20Solo%20Piano.%20Vol.%202-A%20New%20Direction.m4a
10-21 17:31:32.051: E/EventLogger(29074): 	at com.google.android.exoplayer.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:202)
10-21 17:31:32.051: E/EventLogger(29074): 	at com.google.android.exoplayer.upstream.DefaultUriDataSource.open(DefaultUriDataSource.java:136)
10-21 17:31:32.051: E/EventLogger(29074): 	at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:733)
10-21 17:31:32.051: E/EventLogger(29074): 	at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
10-21 17:31:32.051: E/EventLogger(29074): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
10-21 17:31:32.051: E/EventLogger(29074): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
10-21 17:31:32.051: E/EventLogger(29074): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
10-21 17:31:32.051: E/EventLogger(29074): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
10-21 17:31:32.051: E/EventLogger(29074): 	at java.lang.Thread.run(Thread.java:818)
10-21 17:31:32.051: E/EventLogger(29074): Caused by: java.net.ProtocolException: Unexpected status line: GET /pianosolo/HE-AAC%2064/Featured/Amy%20Janelle-Whisperings-%20Solo%20Piano.%20Vol.%202-A%20New%20Direction.m4a HTTP/1.1
10-21 17:31:32.051: E/EventLogger(29074): 	at com.android.okhttp.internal.http.StatusLine.<init>(StatusLine.java:38)
10-21 17:31:32.051: E/EventLogger(29074): 	at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:203)
10-21 17:31:32.051: E/EventLogger(29074): 	at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:119)
10-21 17:31:32.051: E/EventLogger(29074): 	at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:798)
10-21 17:31:32.051: E/EventLogger(29074): 	at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:405)
10-21 17:31:32.051: E/EventLogger(29074): 	at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:349)
10-21 17:31:32.051: E/EventLogger(29074): 	at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:517)
10-21 17:31:32.051: E/EventLogger(29074): 	at com.google.android.exoplayer.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:199)
10-21 17:31:32.051: E/EventLogger(29074): 	... 8 more

**Comment by ojw28** [comment]
My comment above already answers what's wrong with these streams (i.e. the server is refusing connections and/or doesn't properly support range requests). You can upload the exact same files to Google Drive and they play fine.

URLs with spaces in are also unsafe. Although not a problem for ExoPlayer in this specific case, you should remove the spaces if you're hosting this content yourself in order to ensure proper playback across different players and devices (e.g. by converting spaces to underscores). See [this](https://github.com/google/ExoPlayer/issues/871) for details.

**Comment by kenroyandfamily** [comment]
I'm sorry but I just don't understand.  The URL I posted:

"http://od.pianostream.com:9000/pianosolo/HE-AAC%2064/Featured/Amy%20Janelle-Whisperings-%20Solo%20Piano.%20Vol.%202-A%20New%20Direction.m4a"

 does not require authentication (like the previous URL's I posted) so it is not a "Connection refused" issue (as you can see from the jave error I posted) and as you said it plays in Google Drive (and iTunes for me).  So that leaves the "range requests" issue.  Is that what is going on here?  If so how do you know that since I don't see anything about "range requests" in the ExoPlayer log files?

I am able to play that URL using the native Android MediaPlayer so I'm confused as to why the ExoPlayer cannot play it.  For the Android MediaPlayer I simply setDataSource() and then do prepare() and it plays fine.  What does the "Unexpected status line: GET /pianosolo/HE-AAC%2064/Featured/Amy%20Janelle-Whisperings-%20Solo%20Piano.%20Vol.%202-A%20New%20Direction.m4a HTTP/1.1" java error in ExoPlayer mean?  

Thank you for your patience.

**Comment by ojw28** [comment]
- Ah, I didn't see that part of the error, sorry! "Unexpected status line" is pretty easy to search for on Google. It appears in indicate that the server isn't providing a valid HTTP response, which explains why the connection then fails.
- I didn't mean that it plays in Google Drive. I meant that it plays fine in ExoPlayer if you just host the exact same content on Google Drive and use the Google Drive download link. Hence indicating that it's a server problem as opposed to a problem with either the media or ExoPlayer. For example, I've temporarily uploaded your content to the following link, from which it plays just fine:

https://docs.google.com/uc?authuser=1&id=0BydSekB7szpxNlo1UXIwUlRncTQ&export=download

NB - I'll delete this in ~1 hour.

**Comment by kenroyandfamily** [comment]
I see.  But if there is an issue with the header why then does it play fine in iTunes and the native Android MediaPlayer but not ExoPlayer?

What exactly is wrong with the header?  When I use the following to view the header:

 curl "http://od.pianostream.com:9000/pianosolo/HE-AAC%2064/Featured/Amy%20Janelle-Whisperings-%20Solo%20Piano.%20Vol.%202-A%20New%20Direction.m4a" -i | more

I see the following header:

TP/1.0 200 OK
Content-Type: application/octet-stream

There doesn't appear to be anything wrong with this header.

**Comment by ojw28** [comment]
Which loops back nicely to the comment about not supporting range requests properly. If you make a range request, like:

`curl -r 10-20 "http://od.pianostream.com:9000/pianosolo/HE-AAC%2064/Featured/Amy%20Janelle-Whisperings-%20Solo%20Piano.%20Vol.%202-A%20New%20Direction.m4a" -i | more`

then it appears the response headers are broken. iTunes and MediaPlayer probably do not issue range requests for the playback, but it's a legitimate thing for a player to do.

**Comment by kenroyandfamily** [comment]
Great, then we are getting somewhere :-).  How then do I play this URL in ExoPlayer and have the ExoPlayer NOT send a range request?  I have no need for range requests.  And there is no "range request" information in the lines:

new Sample("Google Play (MP3 Audio)",
"http://od.pianostream.com:9000/pianosolo/HE-AAC%2064/Featured/Amy%20Janelle-Whisperings-%20Solo%20Piano.%20Vol.%202-A%20New%20Direction.m4a", PlayerActivity.TYPE_OTHER),

Thanks

**Comment by kenroyandfamily** [comment]
BTW, what is wrong with this header?

GET /pianosolo/HE-AAC%2064/Featured/Amy%20Janelle-Whisperings-%20Solo%20Piano.%20Vol.%202-A%20New%20Direction.m4a HTTP/1.1
Host: od.pianostream.com:9000
Range: bytes=10-20
User-Agent: curl/7.43.0
Accept: */*

Thanks again

**Comment by ojw28** [comment]
- It's perfectly legitimate for a player to issue range requests in this way. This kind of functionality is essential for seeking in large video files, for example, where it's obviously unreasonable for the player to download the entire video just because the user seeks to a point near to the end. The server is supposed to return a 206 status code and the requested range in this case.
- We do actually support the case where a server doesn't support range requests. In this case the server is supposed to return a 200 status code and the whole content, and we'll manually skip and discard data until we get to the byte offset that we're interested in. In practice servers should always support range requests unless they're dealing exclusively with segmented media (i.e. DASH or HLS), which is not true in your case.
- In this example the server just isn't returning a valid HTTP response. The first line of the response is not a valid status line. The correct format for a status line can be found [here](http://www.w3.org/Protocols/rfc2616/rfc2616-sec6.html). We do not support this, and the correct solution is very much to fix the server to return valid responses. Sorry.

**Comment by kenroyandfamily** [comment]
No need to be sorry.  Believe it or not this was very very helpful :-)

Thanks

**Comment by laminsk** [comment]
@kenroyandfamily I'm having the same issue here and wondering how you managed to solve this. Thanks in advance.
