### ISSUE TITLE
What is best approach to block out current program and play some clear content.

### ISSUE THREAD

**Issue by spakanati123** [google/ExoPlayer#8820]
My application plays only Live content(DASH+Widevine) but because of business rules some of regions we should not allow to play some of programs. So the recommended approach is to play some other content in that particular time slot for that region.

**Given context:** I am playing particular channel and the specified block out interval is 6PM to 7PM so with in this 1hour window i should play some other content(clear content mpd) 

**Question 1:** 
What is best approach to swap the main content Vs block out content(clear content) in the given block out interval.

**Question 2:**
We support dvrWindow of 6 hours(timeShiftBuffer) so user can rewind until 6 hours so when user playing black out content(6pm to 7pm) if he rewinds it say 4pm then i should fall back to main content and if the user forward to 6pm to 7pm time window again i need switch to black out content.

Note: main content mpd and black out content mpd are different.

Requesting your thoughts on this.

Thanks in advance.

**Comment by AquilesCanta** [comment]
For security reasons this doesn't seem something that should be solved client side (and therefor ExoPlayer). Are your 6 hours of content served as a single DASH manifest? Couldn't the server just offer the alternative content for the blocked-out interval in the manifest?

Aside, I don't think the ExoPlayer issue tracker is the right place to ask this, probably a forum or a general Q&A site would be a better place to ask this. Can you clarify how this question relates to ExoPlayer?

**Comment by spakanati123** [comment]
@AquilesCanta you are right. This should be served from server side but because of challenges currently from server side we decided to address on client side as a temporary solution. 
Like you said it is single dash manifest for six hours of content.

**Comment by AquilesCanta** [comment]
Sorry I can't be of more assistance. As a pointer for experimenting with client-side, you could solve this at manifest parsing level, where you create a parser that merges both manifest by picking the parts (are you using periods?) it wants from each manifest (from the main content up to 6 pm, from the alternative manifest 6-7 pm and back to the main manifest). Then you could potentially impose security restrictions on the segment serving only. That might work, but I'm just brainstorming based on the little info I have. Hope you manage to fix this soon.

**Comment by linhai326** [comment]
From my experience, this blackout feature should be implemented outside of exoplayer. 
There should be a business layer over exoplayer to apply the business logics like this one.
