### ISSUE TITLE
no audio on live streams , which have audio MP2

### ISSUE THREAD

**Issue by littlelitleStar** [google/ExoPlayer#8822]
I have an IPTV app , for android devices. 
I stream iptv streams there, but im having issues with my users.

they are complaining that streams dont have AUDIO. 
But on some devices they have and on some they dont.

I found that the issue was that , streams with mp2 audio , were causing the problem.

How can this be fixed ?

**Comment by icbaker** [comment]
MP2 audio is not required to be supported by all Android devices:
https://developer.android.com/guide/topics/media/media-formats#core

More information on supported formats:
https://exoplayer.dev/supported-formats.html#sample-formats

Do the devices you're seeing problems with support MP2? If not, you might be able to decode in software using the FFmpeg extension:
https://exoplayer.dev/supported-formats.html#ffmpeg-extension
