### ISSUE TITLE
Properties setMaxAudioChannelCount() & setPreferredAudioMimeType() not working in some situations.

### ISSUE THREAD

**Issue by menscikov** [google/ExoPlayer#8824]
**Issue description**
First and second video stream has 4 audio tracks, two of them are in 6 channel AC-3 format and other two in 2 channel MPEG-L2 format.
ExoPlayer always selects first available audio track 2 channel MPEG-L2 even when i set this in track selector:
```
DefaultTrackSelector trackSelector = new DefaultTrackSelector(context)
    .setParameters(trackSelector
    .buildUponParameters()
    .setMaxAudioChannelCount(6)
    .setPreferredAudioMimeType("audio/ac3")
```

**Link to test content**
Link to the media e-mailed to ExoPlayer development team.

**Version of ExoPlayer being used**
2.13.3

**Device(s) and version(s) of Android being used**
Xiaomi Mi 9T, Android 10

**Comment by icbaker** [comment]
> **Link to test content**
> Link to the media e-mailed to ExoPlayer development team.

We didn't receive this - did you send it to dev.exoplayer@gmail.com with the subject "Issue #8824"? Please re-send it, and update this issue when you've done so.

**Comment by menscikov** [comment]
> > **Link to test content**
> > Link to the media e-mailed to ExoPlayer development team.
> 
> We didn't receive this - did you send it to [dev.exoplayer@gmail.com](mailto:dev.exoplayer@gmail.com) with the subject "Issue #8824"? Please re-send it, and update this issue when you've done so.

Hello, yes. I sent it again 1 minute ago.

**Comment by icbaker** [comment]
Thanks for the link.

I played it in the ExoPlayer demo app and saw this in logcat:

```
tracks [eventTime=1.23, mediaPos=0.00, window=0, period=0
  MediaCodecVideoRenderer [
    Group:0, adaptive_supported=N/A [
      [X] Track:0, id=0, mimeType=video/avc, bitrate=10280000, codecs=avc1.640028, res=1920x1080, fps=25.0, supported=YES
    ]
    Group:1, adaptive_supported=N/A [
      [ ] Track:0, id=aac:undefined a2, mimeType=video/avc, codecs=avc1.640028, res=1920x1080, label=undefined a2, supported=YES
    ]
    Metadata [
      HlsTrackMetadataEntry
    ]
  ]
  MediaCodecAudioRenderer [
    Group:0, adaptive_supported=N/A [
      [ ] Track:0, id=aac:rus a1, mimeType=audio/mpeg-L2, channels=2, sample_rate=48000, language=ru, label=rus a1, supported=NO_UNSUPPORTED_TYPE
    ]
    Group:1, adaptive_supported=N/A [
      [ ] Track:0, id=17103/4, mimeType=audio/mpeg-L2, channels=2, sample_rate=48000, language=ru, supported=NO_UNSUPPORTED_TYPE
    ]
  ]
  TextRenderer []
  MetadataRenderer [
    Group:0, adaptive_supported=N/A [
      [X] Track:0, id=null, mimeType=application/id3, supported=YES
    ]
    Group:1, adaptive_supported=N/A [
      [ ] Track:0, id=null, mimeType=application/id3, supported=YES
    ]
  ]
  CameraMotionRenderer []
]
```

ExoPlayer has determined the stream has two video tracks (both avc1.640028 and 1920x1080) and two audio tracks (both stereo and mpeg-L2).

This doesn't match the description of the media you've provided in the issue. `mediainfo` agrees with your description when I analyse one of the TS segments (for the v1a1 stream):

```
General
ID                                       : 17 (0x11)
Format                                   : MPEG-TS
File size                                : 5.17 MiB
Duration                                 : 5 s 580 ms
Overall bit rate mode                    : Variable
Overall bit rate                         : 7 745 kb/s

Video
ID                                       : 211 (0xD3)
Menu ID                                  : 17103 (0x42CF)
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4
Format settings                          : CABAC / 4 Ref Frames
Format settings, CABAC                   : Yes
Format settings, Reference frames        : 4 frames
Codec ID                                 : 27
Duration                                 : 5 s 600 ms
Bit rate                                 : 6 780 kb/s
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate                               : 25.000 FPS
Standard                                 : Component
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Interlaced
Scan type, store method                  : Separated fields
Scan order                               : Top Field First
Bits/(Pixel*Frame)                       : 0.131
Stream size                              : 4.53 MiB (88%)
Color range                              : Limited
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709

Audio #1
ID                                       : 221 (0xDD)
Menu ID                                  : 17103 (0x42CF)
Format                                   : MPEG Audio
Format version                           : Version 1
Format profile                           : Layer 2
Codec ID                                 : 4
Duration                                 : 5 s 616 ms
Bit rate mode                            : Constant
Bit rate                                 : 192 kb/s
Channel(s)                               : 2 channels
Sampling rate                            : 48.0 kHz
Frame rate                               : 41.667 FPS (1152 SPF)
Compression mode                         : Lossy
Delay relative to video                  : -73 ms
Stream size                              : 132 KiB (2%)
Language                                 : Russian

Audio #2
ID                                       : 222 (0xDE)
Menu ID                                  : 17103 (0x42CF)
Format                                   : AC-3
Format/Info                              : Audio Coding 3
Commercial name                          : Dolby Digital
Codec ID                                 : 129
Duration                                 : 5 s 600 ms
Bit rate mode                            : Constant
Bit rate                                 : 384 kb/s
Channel(s)                               : 6 channels
Channel layout                           : L R C LFE Ls Rs
Sampling rate                            : 48.0 kHz
Frame rate                               : 31.250 FPS (1536 SPF)
Compression mode                         : Lossy
Delay relative to video                  : -56 ms
Stream size                              : 262 KiB (5%)
Service kind                             : Complete Main
```

Your master playlist only includes 2 `EXT-X-MEDIA` tags - if there are 4 audio tracks in the stream I think you need 4?

Your `EXT-X-STREAM-INF` tag is missing a `CODECS` attribute, but I think [in this case (of mixing codecs) it's required](https://tools.ietf.org/html/draft-pantos-http-live-streaming-23#section-4.3.4.1.1):
```
   Each member in a Group of Renditions MAY have a different sample
   format.  For example, an English rendition can be encoded with AC-3
   5.1 while a Spanish rendition is encoded with AAC stereo.  However,
   any EXT-X-STREAM-INF (Section 4.3.4.2) tag or EXT-X-I-FRAME-STREAM-
   INF (Section 4.3.4.3) tag which references such a Group MUST have a
   CODECS attribute that lists every sample format present in any
   Rendition in the Group, or client playback failures can occur.  In
   the example above, the CODECS attribute would include
   "ac-3,mp4a.40.2".
```

Passing this over to @christosts who is more familiar with HLS. Marking as a question for now, as I don't think we've uncovered a bug in the ExoPlayer library yet.

**Comment by menscikov** [comment]
@icbaker thank you for investigating the video stream.

When i parsing this video stream (HLS) in my application i get 4 audio tracks:
```
1 Track: Format(aac:rus a1, rus a1, null, audio/mpeg-L2, null, -1, ru, [-1, -1, -1.0], [2, 48000])
2 Track: Format(aac:rus a1, rus a1, null, audio/ac3, null, -1, ru, [-1, -1, -1.0], [6, 48000])
3 Track: Format(17103/221, null, null, audio/mpeg-L2, null, -1, ru, [-1, -1, -1.0], [2, 48000])
4 Track: Format(17103/222, null, null, audio/ac3, null, -1, null, [-1, -1, -1.0], [6, 48000])
```

This video stream is not mine, one of the users sent it to me. I understand that it may be not correctly decoded by provider.
When i select the audio track manually 2 channels or 6 channels, they are working fine.
I use `setMaxAudioChannelCount()` and `setPreferredAudioMimeType()` to remember last played audio track, but it doesn't work in this situation. Even if this video stream has problems, why manual selection is working, but not automatic.

I have other video streams with more than 1 audio track, and there everything is working as expected, ExoPlayer preselects correct track.

P.S. Could you tell me please what library do you use to get `mediainfo` metadata for TS segment?

**Comment by icbaker** [comment]
> P.S. Could you tell me please what library do you use to get `mediainfo` metadata for TS segment?

On linux I used `sudo apt install mediainfo` - think it's this: https://mediaarea.net/en/MediaInfo

**Comment by menscikov** [comment]
Hello, any update on this? I'm just afraid that media link will become unavailable soon.

**Comment by christosts** [comment]
Hi,

I just checked the stream that was sent to us, but the stream  maybe has changed since last time. What I get now is single video track with two audio tracks, a 2 channel MPEG-L2 and a 6 channel AC-3. By default, the demo app's track selector would go to the 2 channel audio (I am using the ffmpeg extension to support this format, my devices do not support it directly).  But if I do as indicated above

```
trackSelector.setParameters(trackSelectorParameters.buildUpon().setMaxAudioChannelCount(6).setPreferredAudioMimeType("audio/ac3"));
```

then the player picks up the 6-channel stream by default.

Please note that the video stream is interlaced and none of my devices actually displays it (I have to disable it). 

Does the issue occur only on the stream that was originally reported on this issue, i.e. 4 audio tracks with 2 stereo and 2 ac3?

**Comment by menscikov** [comment]
Hello, thank you for checking the stream.
Yes, it looks like that this stream has been modified, and only 2 audio tracks are available now.
If in the future the audio tracks will change, I will post about it here.
Thank you.

**Comment by christosts** [comment]
I'm closing this issue, feel free to re-open if there's an update.
