### ISSUE TITLE
Using the keySetId for MediaSource creation. 

### ISSUE THREAD

**Issue by olgunkaya** [google/ExoPlayer#8825]
Lately I have been keep posting tons of questions about the DRM, sorry in advance, but due to constraints I have (unable to upgrade the dependencies) and lack of documents on the internet, I have no other chance. 

Lately, so my question is quite straight forward. 

**What I have so far ?** 
1. exo player version : 2.11.4
2. DRM protected video downloaded.
3. Keys downloaded and have keySetId persisted per content. (keys has special custom data for extra authorization, I am not trying a fraud :) )
4. Clear content is ok to both download and play. 

**What is the issue ?** 
but when it comes to DRM protected, downloaded media. I don't know how to use my keySetId to create a DRMSessionManager.

**Comment by icbaker** [comment]
You need to pass [`MODE_PLAYBACK`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/drm/DefaultDrmSessionManager.html#MODE_PLAYBACK) and the `keySetId` to [`DefaultDrmSessionManager#setMode()`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/drm/DefaultDrmSessionManager.html#setMode-int-byte:A-).

You can see this in the way we create a `MediaSource` from a `MediaItem` in the post-2.13.0 code:
https://github.com/google/ExoPlayer/blob/r2.13.3/library/core/src/main/java/com/google/android/exoplayer2/drm/DefaultDrmSessionManagerProvider.java#L116

(That line doesn't exist in 2.11.4 that you're using of course, but the `setMode` API does)

**Comment by olgunkaya** [comment]
Thanks again @icbaker I obviously have more way to go but at least this is a start. If I try to explain what I understand,

I need an http data source factory (I already have one for downloading the media etc.. can use that one)
I need a media drm callback that player will use to get the keys over network using the http data source from above statement.
I need to add extra parameter(s)/custom headers for my drm provider's extra filtering case.
And put all those to generate a drm session manager. Assuming that when I give the keySetId to the session manager with mode_playback. It will not try to go over network (not possible to go when it is on plane mode :) ) but use the existing key.

**Comment by olgunkaya** [comment]
@icbaker thanks again. finally I had this implemented not tested yet but want to confirm with you since I set the mode to playback, it will use the keysetId that I provide and not gonna try to fetch keys again over network ?

```
@RequiresApi(18)
    private DrmSessionManager<ExoMediaCrypto> getDrmSessionManager(byte[] keySetId, WritableMap drmConfig) {
        HttpMediaDrmCallback drmCallback = new HttpMediaDrmCallback(
                drmConfig.hasKey("licenseServer") ? drmConfig.getString("licenseServer") : null,
                //do not force to go to the server
                false,
                httpDataSourceFactory
        );

        for (Map.Entry<String, String> entry : SaatDownloadUtil.getDrmExtraData(drmConfig).entrySet()) {
            drmCallback.setKeyRequestProperty(entry.getKey(), entry.getValue());
        }

        DefaultDrmSessionManager<ExoMediaCrypto> drmSessionManager = new DefaultDrmSessionManager.Builder()
                .setUuidAndExoMediaDrmProvider(C.WIDEVINE_UUID, FrameworkMediaDrm.DEFAULT_PROVIDER)
                .setMultiSession(false)
//                .setPlayClearSamplesWithoutKeys(true)
//                .setUseDrmSessionsForClearContent()
                .build(drmCallback);

        drmSessionManager.setMode(DefaultDrmSessionManager.MODE_PLAYBACK, keySetId);
        
        return drmSessionManager;
    }
```

**Comment by icbaker** [comment]
It should only try and fetch keys if the existing offline license referenced by `keySetId` has expired.
