### ISSUE TITLE
IllegalStateException on Nexus Player

### ISSUE THREAD

**Issue by PetrSklenicka** [google/ExoPlayer#883]
I am using Exoplayer for playing Widevine protected video. The format of video is MPEG-DASH. It works fine, but in case that I run my application on Nexus Player device with Android 6.0, I get an exception and video cannot be played. MPD file of video contains a lot of links to segments of MP4 video. The full log is attached below.

10-20 00:40:52.151 11891-11891/com.my.app I/ExoPlayerImpl: Init 1.4.2
10-20 00:40:52.222 11891-11891/com.my.app E/SensorManager: sensor or listener is null
10-20 00:40:53.285 11891-11897/com.my.app W/art: Suspending all threads took: 17.282ms
10-20 00:40:53.331 11891-11891/com.my.app W/VideoCapabilities: Unrecognized profile/level 0/0 for video/mpeg2
10-20 00:40:53.331 11891-11891/com.my.app W/VideoCapabilities: Unrecognized profile/level 0/2 for video/mpeg2
10-20 00:40:53.331 11891-11891/com.my.app W/VideoCapabilities: Unrecognized profile/level 0/3 for video/mpeg2
10-20 00:40:53.347 11891-11891/com.my.app I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
10-20 00:40:54.784 11891-11897/com.my.app W/art: Suspending all threads took: 6.590ms
10-20 00:40:54.954 11891-12357/com.my.app I/OMXClient: Using client-side OMX mux.
10-20 00:40:54.972 11891-12356/com.my.app I/MediaCodec: [OMX.Intel.VideoDecoder.AVC.secure] setting surface generation to 12176385
10-20 00:40:54.996 11891-12357/com.my.app D/SurfaceUtils: set up nativeWindow 0xf921c9d8 for 768x448, color 0x7fa00e00, rotation 0, usage 0x6922
10-20 00:40:55.025 11891-12360/com.my.app I/OMXClient: Using client-side OMX mux.
10-20 00:40:55.055 11891-12360/com.my.app I/wrs-omxil-core: found component library libOMXVideoDecoderAVC.so
10-20 00:40:55.060 11891-12360/com.my.app I/cmodule: module libOMXVideoDecoderAVC.so successfully loaded
10-20 00:40:55.061 11891-12360/com.my.app I/cmodule: module libOMXVideoDecoderAVC.so successfully unloaded
10-20 00:40:55.061 11891-12360/com.my.app I/wrs-omxil-core: module libOMXVideoDecoderAVC.so:OMX.Intel.VideoDecoder.AVC added to component list
10-20 00:40:55.061 11891-12360/com.my.app I/wrs-omxil-core: found component library libOMXVideoDecoderH263.so
10-20 00:40:55.067 11891-12360/com.my.app I/cmodule: module libOMXVideoDecoderH263.so successfully loaded
10-20 00:40:55.068 11891-12360/com.my.app I/cmodule: module libOMXVideoDecoderH263.so successfully unloaded
10-20 00:40:55.068 11891-12360/com.my.app I/wrs-omxil-core: module libOMXVideoDecoderH263.so:OMX.Intel.VideoDecoder.H263 added to component list
10-20 00:40:55.068 11891-12360/com.my.app I/wrs-omxil-core: found component library libOMXVideoDecoderWMV.so
10-20 00:40:55.073 11891-12360/com.my.app I/cmodule: module libOMXVideoDecoderWMV.so successfully loaded
10-20 00:40:55.073 11891-12360/com.my.app I/cmodule: module libOMXVideoDecoderWMV.so successfully unloaded
10-20 00:40:55.073 11891-12360/com.my.app I/wrs-omxil-core: module libOMXVideoDecoderWMV.so:OMX.Intel.VideoDecoder.WMV added to component list
10-20 00:40:55.074 11891-12360/com.my.app I/wrs-omxil-core: found component library libOMXVideoDecoderMPEG4.so
10-20 00:40:55.079 11891-12360/com.my.app I/cmodule: module libOMXVideoDecoderMPEG4.so successfully loaded
10-20 00:40:55.079 11891-12360/com.my.app I/cmodule: module libOMXVideoDecoderMPEG4.so successfully unloaded
10-20 00:40:55.079 11891-12360/com.my.app I/wrs-omxil-core: module libOMXVideoDecoderMPEG4.so:OMX.Intel.VideoDecoder.MPEG4 added to component list
10-20 00:40:55.079 11891-12360/com.my.app I/wrs-omxil-core: found component library libOMXVideoDecoderVP8.so
10-20 00:40:55.085 11891-12360/com.my.app I/cmodule: module libOMXVideoDecoderVP8.so successfully loaded
10-20 00:40:55.086 11891-12360/com.my.app I/cmodule: module libOMXVideoDecoderVP8.so successfully unloaded
10-20 00:40:55.086 11891-12360/com.my.app I/wrs-omxil-core: module libOMXVideoDecoderVP8.so:OMX.Intel.VideoDecoder.VP8 added to component list
10-20 00:40:55.086 11891-12360/com.my.app I/wrs-omxil-core: found component library libOMXVideoDecoderMPEG2.so
10-20 00:40:55.090 11891-12360/com.my.app I/cmodule: module libOMXVideoDecoderMPEG2.so successfully loaded
10-20 00:40:55.091 11891-12360/com.my.app I/cmodule: module libOMXVideoDecoderMPEG2.so successfully unloaded
10-20 00:40:55.091 11891-12360/com.my.app I/wrs-omxil-core: module libOMXVideoDecoderMPEG2.so:OMX.Intel.VideoDecoder.MPEG2 added to component list
10-20 00:40:55.091 11891-12360/com.my.app I/wrs-omxil-core: found component library libOMXVideoDecoderVP9Hybrid.so
10-20 00:40:55.096 11891-12360/com.my.app I/cmodule: module libOMXVideoDecoderVP9Hybrid.so successfully loaded
10-20 00:40:55.096 11891-12360/com.my.app I/cmodule: module libOMXVideoDecoderVP9Hybrid.so successfully unloaded
10-20 00:40:55.096 11891-12360/com.my.app I/wrs-omxil-core: module libOMXVideoDecoderVP9Hybrid.so:OMX.Intel.VideoDecoder.VP9.hybrid added to component list
10-20 00:40:55.096 11891-12360/com.my.app I/wrs-omxil-core: found component library libOMXVideoDecoderAVCSecure.so
10-20 00:40:55.100 11891-12360/com.my.app I/cmodule: module libOMXVideoDecoderAVCSecure.so successfully loaded
10-20 00:40:55.101 11891-12360/com.my.app I/cmodule: module libOMXVideoDecoderAVCSecure.so successfully unloaded
10-20 00:40:55.101 11891-12360/com.my.app I/wrs-omxil-core: module libOMXVideoDecoderAVCSecure.so:OMX.Intel.VideoDecoder.AVC.secure added to component list
10-20 00:40:55.101 11891-12360/com.my.app I/wrs-omxil-core: found component library libOMXVideoEncoderAVC.so
10-20 00:40:55.107 11891-12360/com.my.app I/cmodule: module libOMXVideoEncoderAVC.so successfully loaded
10-20 00:40:55.108 11891-12360/com.my.app I/cmodule: module libOMXVideoEncoderAVC.so successfully unloaded
10-20 00:40:55.108 11891-12360/com.my.app I/wrs-omxil-core: module libOMXVideoEncoderAVC.so:OMX.Intel.VideoEncoder.AVC added to component list
10-20 00:40:55.108 11891-12360/com.my.app I/wrs-omxil-core: found component library libOMXVideoEncoderH263.so
10-20 00:40:55.111 11891-12360/com.my.app I/cmodule: module libOMXVideoEncoderH263.so successfully loaded
10-20 00:40:55.111 11891-12360/com.my.app I/cmodule: module libOMXVideoEncoderH263.so successfully unloaded
10-20 00:40:55.111 11891-12360/com.my.app I/wrs-omxil-core: module libOMXVideoEncoderH263.so:OMX.Intel.VideoEncoder.H263 added to component list
10-20 00:40:55.111 11891-12360/com.my.app I/wrs-omxil-core: found component library libOMXVideoEncoderMPEG4.so
10-20 00:40:55.114 11891-12360/com.my.app I/cmodule: module libOMXVideoEncoderMPEG4.so successfully loaded
10-20 00:40:55.115 11891-12360/com.my.app I/cmodule: module libOMXVideoEncoderMPEG4.so successfully unloaded
10-20 00:40:55.115 11891-12360/com.my.app I/wrs-omxil-core: module libOMXVideoEncoderMPEG4.so:OMX.Intel.VideoEncoder.MPEG4 added to component list
10-20 00:40:55.115 11891-12360/com.my.app I/wrs-omxil-core: found component library libOMXVideoEncoderVP8.so
10-20 00:40:55.120 11891-12360/com.my.app I/cmodule: module libOMXVideoEncoderVP8.so successfully loaded
10-20 00:40:55.121 11891-12360/com.my.app I/cmodule: module libOMXVideoEncoderVP8.so successfully unloaded
10-20 00:40:55.121 11891-12360/com.my.app I/wrs-omxil-core: module libOMXVideoEncoderVP8.so:OMX.Intel.VideoEncoder.VP8 added to component list
10-20 00:40:55.140 11891-12360/com.my.app I/libva: VA-API version 0.34.0
10-20 00:40:55.141 11891-12360/com.my.app I/libva: va_getDriverName() returns 0
10-20 00:40:55.141 11891-12360/com.my.app I/libva: Trying to open /system/lib/pvr_drv_video.so
10-20 00:40:55.143 11891-12360/com.my.app I/libva: Found init function __vaDriverInit_0_32
10-20 00:40:55.144 11891-12360/com.my.app I/libva: va_openDriver() returns 0
10-20 00:40:55.144 11891-12360/com.my.app I/mediasdk_omx: mfx_omx_dev_android: Driver version is Intel GMA500-MRFL-5.6.0.1202 (0X00000071)
10-20 00:40:55.557 11891-12357/com.my.app E/ACodec: [OMX.Intel.VideoDecoder.AVC.secure] ERROR(0x80001005)
10-20 00:40:55.557 11891-12357/com.my.app E/ACodec: signalError(omxError 0x80001005, internalError -2147483648)
10-20 00:40:55.557 11891-12357/com.my.app W/ACodec: not dequeuing from native window due to fatal error
10-20 00:40:55.558 11891-12357/com.my.app W/ACodec: not dequeuing from native window due to fatal error
10-20 00:40:55.558 11891-12356/com.my.app E/MediaCodec: Codec reported err 0x80001005, actionCode 0, while in state 6
10-20 00:40:55.570 11891-12357/com.my.app E/ACodec: [OMX.Intel.VideoDecoder.AVC.secure] ERROR(0x80001005)
10-20 00:40:55.570 11891-12357/com.my.app E/ACodec: signalError(omxError 0x80001005, internalError -2147483648)
10-20 00:40:55.570 11891-12356/com.my.app E/MediaCodec: Codec reported err 0x80001005, actionCode 0, while in state 0
10-20 00:40:55.577 11891-12286/com.my.app E/ExoPlayerImplInternal: Internal runtime error.
10-20 00:40:55.577 11891-12286/com.my.app E/ExoPlayerImplInternal: java.lang.IllegalStateException
10-20 00:40:55.577 11891-12286/com.my.app E/ExoPlayerImplInternal:     at android.media.MediaCodec.native_dequeueInputBuffer(Native Method)
10-20 00:40:55.577 11891-12286/com.my.app E/ExoPlayerImplInternal:     at android.media.MediaCodec.dequeueInputBuffer(MediaCodec.java:2319)
10-20 00:40:55.577 11891-12286/com.my.app E/ExoPlayerImplInternal:     at com.google.android.exoplayer.MediaCodecTrackRenderer.feedInputBuffer(MediaCodecTrackRenderer.java:565)
10-20 00:40:55.577 11891-12286/com.my.app E/ExoPlayerImplInternal:     at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:501)
10-20 00:40:55.577 11891-12286/com.my.app E/ExoPlayerImplInternal:     at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:417)
10-20 00:40:55.577 11891-12286/com.my.app E/ExoPlayerImplInternal:     at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:205)
10-20 00:40:55.577 11891-12286/com.my.app E/ExoPlayerImplInternal:     at android.os.Handler.dispatchMessage(Handler.java:98)
10-20 00:40:55.577 11891-12286/com.my.app E/ExoPlayerImplInternal:     at android.os.Looper.loop(Looper.java:148)
10-20 00:40:55.577 11891-12286/com.my.app E/ExoPlayerImplInternal:     at android.os.HandlerThread.run(HandlerThread.java:61)
10-20 00:40:55.577 11891-12286/com.my.app E/ExoPlayerImplInternal:     at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
10-20 00:40:55.584 11891-12357/com.my.app E/Surface: getSlotFromBufferLocked: unknown buffer: 0xf91892f0
10-20 00:40:55.584 11891-12357/com.my.app W/ACodec: [OMX.Intel.VideoDecoder.AVC.secure] can not return buffer 26 to native window
10-20 00:40:55.616 11891-12357/com.my.app E/IMGSRV: :0: DeferFreeCallback: WARNING: Buffer ID=48797 had no ops on it (ever) at the point it was freed
10-20 00:40:55.616 11891-12357/com.my.app E/Surface: getSlotFromBufferLocked: unknown buffer: 0xf90f84a8
10-20 00:40:55.616 11891-12357/com.my.app W/ACodec: [OMX.Intel.VideoDecoder.AVC.secure] can not return buffer 25 to native window
10-20 00:40:55.617 11891-12357/com.my.app E/IMGSRV: :0: DeferFreeCallback: WARNING: Buffer ID=48799 had no ops on it (ever) at the point it was freed
10-20 00:40:55.617 11891-12357/com.my.app E/Surface: getSlotFromBufferLocked: unknown buffer: 0xf8c85320
10-20 00:40:55.617 11891-12357/com.my.app W/ACodec: [OMX.Intel.VideoDecoder.AVC.secure] can not return buffer 24 to native window
10-20 00:40:55.619 11891-12357/com.my.app E/IMGSRV: :0: DeferFreeCallback: WARNING: Buffer ID=48801 had no ops on it (ever) at the point it was freed
10-20 00:40:55.619 11891-12357/com.my.app E/Surface: getSlotFromBufferLocked: unknown buffer: 0xf8f45fb8
10-20 00:40:55.619 11891-12357/com.my.app W/ACodec: [OMX.Intel.VideoDecoder.AVC.secure] can not return buffer 23 to native window
10-20 00:40:55.621 11891-12357/com.my.app E/IMGSRV: :0: DeferFreeCallback: WARNING: Buffer ID=48803 had no ops on it (ever) at the point it was freed
10-20 00:40:55.621 11891-12357/com.my.app E/Surface: getSlotFromBufferLocked: unknown buffer: 0xf9025730
10-20 00:40:55.621 11891-12357/com.my.app W/ACodec: [OMX.Intel.VideoDecoder.AVC.secure] can not return buffer 22 to native window
10-20 00:40:55.622 11891-12357/com.my.app E/IMGSRV: :0: DeferFreeCallback: WARNING: Buffer ID=48805 had no ops on it (ever) at the point it was freed
10-20 00:40:55.628 11891-12357/com.my.app D/SurfaceUtils: set up nativeWindow 0xf921c9d8 for 1x1, color 0x2, rotation 0, usage 0x930
10-20 00:40:55.654 11891-11901/com.my.app I/art: Background partial concurrent mark sweep GC freed 19923(1453KB) AllocSpace objects, 21(6MB) LOS objects, 32% free, 33MB/49MB, paused 4.514ms total 150.343ms
10-20 00:40:55.657 11891-12286/com.my.app E/ExoPlayerImplInternal: Stop failed.
10-20 00:40:55.657 11891-12286/com.my.app E/ExoPlayerImplInternal: java.lang.IllegalStateException
10-20 00:40:55.657 11891-12286/com.my.app E/ExoPlayerImplInternal:     at android.media.MediaCodec.native_stop(Native Method)
10-20 00:40:55.657 11891-12286/com.my.app E/ExoPlayerImplInternal:     at android.media.MediaCodec.stop(MediaCodec.java:1901)
10-20 00:40:55.657 11891-12286/com.my.app E/ExoPlayerImplInternal:     at com.google.android.exoplayer.MediaCodecTrackRenderer.releaseCodec(MediaCodecTrackRenderer.java:437)
10-20 00:40:55.657 11891-12286/com.my.app E/ExoPlayerImplInternal:     at com.google.android.exoplayer.MediaCodecTrackRenderer.onDisabled(MediaCodecTrackRenderer.java:407)
10-20 00:40:55.657 11891-12286/com.my.app E/ExoPlayerImplInternal:     at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onDisabled(MediaCodecVideoTrackRenderer.java:328)
10-20 00:40:55.657 11891-12286/com.my.app E/ExoPlayerImplInternal:     at com.google.android.exoplayer.TrackRenderer.disable(TrackRenderer.java:219)
10-20 00:40:55.657 11891-12286/com.my.app E/ExoPlayerImplInternal:     at com.google.android.exoplayer.ExoPlayerImplInternal.stopAndDisable(ExoPlayerImplInternal.java:538)
10-20 00:40:55.657 11891-12286/com.my.app E/ExoPlayerImplInternal:     at com.google.android.exoplayer.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:525)
10-20 00:40:55.657 11891-12286/com.my.app E/ExoPlayerImplInternal:     at com.google.android.exoplayer.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:502)
10-20 00:40:55.657 11891-12286/com.my.app E/ExoPlayerImplInternal:     at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:239)
10-20 00:40:55.657 11891-12286/com.my.app E/ExoPlayerImplInternal:     at android.os.Handler.dispatchMessage(Handler.java:98)
10-20 00:40:55.657 11891-12286/com.my.app E/ExoPlayerImplInternal:     at android.os.Looper.loop(Looper.java:148)
10-20 00:40:55.657 11891-12286/com.my.app E/ExoPlayerImplInternal:     at android.os.HandlerThread.run(HandlerThread.java:61)
10-20 00:40:55.657 11891-12286/com.my.app E/ExoPlayerImplInternal:     at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)

**Comment by ojw28** [comment]
Let's use #612 to track this. They look the same.
