### ISSUE TITLE
Getting a progress loader on exoplayer upgrade to latest version 2.13.3

### ISSUE THREAD

**Issue by ArchanaGwda** [google/ExoPlayer#8831]
Hi, 
I tried to update the dependencies from 2.6.1 to 2.13.3.
Now I am getting a transparent overlay with progress dialog.  Video is paying in below the overlay. Please help me out to resolve this.

https://user-images.githubusercontent.com/20718146/115245544-a8fd0600-a142-11eb-95ad-2154da963363.mp4

Dependencies from build.gradle file
```
    implementation 'com.google.android.exoplayer:exoplayer:2.12.3'
    implementation 'com.google.android.exoplayer:exoplayer-core:2.12.3'
    implementation 'com.google.android.exoplayer:exoplayer-dash:2.12.3'
    implementation 'com.google.android.exoplayer:exoplayer-hls:2.12.3'
    implementation 'com.google.android.exoplayer:exoplayer-smoothstreaming:2.12.3'
    implementation 'com.google.android.exoplayer:exoplayer-ui:2.12.3'
```

Please help me to resolve this issue at the earliest. I am stuck with this from 2 days. Not able to resolve this issue. Any help would be appreciated.

**Comment by icbaker** [comment]
There isn't enough information here to help you.

Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that demonstrates the problem in a way that we can build locally.

This could be an Android Studio project on GitHub, or zipped up and sent to dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Please also update this issue to indicate you’ve done this.

**Comment by ArchanaGwda** [comment]
Hi, 

Thank you for the reply. I have resolved this issue. While upgrading to latest version I forgot to hide the default loader. Now its working fine. 

But now I am facing issue with ads. I am using mediaItem to play ads. But ads aren't playing. And also I am not getting any logs regarding the ads. [Issue raised here](https://github.com/google/ExoPlayer/issues/8866). Please help me out this at the earliest.
