### ISSUE TITLE
Previous button works wrong with mp3 streams

### ISSUE THREAD

**Issue by svyatoslavpavlov** [google/ExoPlayer#8835]
Hi!
When I'm using exoplayer for radio app with icecast streams, previous action in notification trying to play this stream again instead of playing previous stream. In DefaultControlDispatcher#dispatchPrevious library checks `window.isDynamic && !window.isSeekable`,  but maybe better is `(window.isDynamic || window.isLive) && !window.isSeekable`

- ExoPlayer version number: 2.13
- Android version: 11
- Android device: samsung s10e

**Comment by marcbaechinger** [comment]
Thanks for reporting!

I think that's already fixed in the most recent version where we do

```
boolean isUnseekableLiveStream = window.isLive() && !window.isSeekable;
```

I'm closing. Please re-open if you have further input. Thanks again!
