### ISSUE TITLE
exoplayer.dev is broken

### ISSUE THREAD

**Issue by ojw28** [google/ExoPlayer#8837]
This is known issue. We're working to resolve it. In the meantime, the developer guide can be accessed at https://google.github.io/ExoPlayer/ instead.

**Comment by electrodragon** [comment]
https://google.github.io/ExoPlayer/supported-formats.html

can't access this page still.

**Comment by ojw28** [comment]
It's fixed. Apologies for the inconvenience!

**Comment by huttarl** [comment]
@ojw28 Strangely enough, the page styling is broken in Brave browser. E.g. https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/trackselection/TrackSelectionArray.html
works fine in Chrome but not Brave. "Too many redirects" on CSS and JS fetches.
It worked fine in Brave before this issue arose.

Screenshot:
https://imgur.com/a/B0sW5Tp

**Comment by ojw28** [comment]
I wonder if that's a caching issue of some kind. Does it reproduce in a Brave Private Window? Or any other browser?

**Comment by huttarl** [comment]
Thanks for your response. Maybe it was a caching issue. I tried it today and it worked fine (displayed correctly) in both a Brave Private window and a non-private window. Sorry if this was a false alarm.
