### ISSUE TITLE
Is there a way to synchronize HLS playlists at playback start

### ISSUE THREAD

**Issue by sruditsky** [google/ExoPlayer#8840]
We are using ExoPlayer 2.12.3

Let's say there is a live HLS stream where all segments are 6 sec long and perfectly aligned between audio and video.

When an HLS playback starts ExoPlayer downloads a video and an audio playlists. In most cases these two first playlists arrive aligned, however. sometimes one of the playlist is shifted by one segment compared to the other one, i.e. we happened to be "lucky" to get one before update and one after it.

The result is that the first media segment which is requested for one media type is not requested for the other. In the situation which we are facing it is always video which starts later. And the behavior which we get is that the first video frame is displayed and frozen for 6 sec, while the audio is playing till the moment when it reaches the playback position of the displayed video frame. From this moment the playback continues as it should.

The question is: does ExoPlayer has any mechanism to avoid this situation?

**Comment by christosts** [comment]
Can you please share a link to your playlist? If you cannot post it here publicly, can you email it to dev.exoplayer@gmail.com with subject "Issue #8840" and update this issue so we get notified. 

How often does this happen to you? I don't recall ever seeing this in local tests with the player, so I would like to test with your content.

**Comment by sruditsky** [comment]
@christosts 
I just sent a playlist URL as you described above. It requires a proprietary DRM mechanism, so it would be difficult to actually make it play for you.
However, it probably helps to explain my question.
I just used this URL to start playing this content twice and I experienced the problem on the first attempt while the second attempt did not show this issue.

This is the list of  the (abbreviated to remove proprietary info) URLs which ExoPlayer fetches.

For the first (bad) attempt:
04-30 12:59:12.552  URL: https://.../index_tv.m3u8	
04-30 12:59:12.958  URL: https://.../06.m3u8	
04-30 12:59:13.683  URL: https://.../20210410T182013-287183-06.**m4v**?initSeg=20210410T182013-stream06-initSection.m4i&st=**1619801929**	
04-30 12:59:13.724  URL: https://.../09.m3u8	
04-30 12:59:14.143  URL: https://.../20210410T182013-287182-09.**m4a**?initSeg=20210410T182013-stream09-initSection.m4i&st=**1619801923**	
04-30 12:59:14.415  URL: https://.../20210410T182013-287183-09.**m4a**?initSeg=20210410T182013-stream09-initSection.m4i&st=**1619801929**	
04-30 12:59:14.620  URL: https://.../20210410T182013-287184-09.m4a?initSeg=20210410T182013-stream09-initSection.m4i&st=1619801935	
04-30 12:59:14.632  URL: https://.../20210410T182013-287184-06.m4v?initSeg=20210410T182013-stream06-initSection.m4i&st=1619801935

For the second (good) attempt:
04-30 13:00:00.231  URL: https://.../index_tv.m3u8
04-30 13:00:00.413  URL: https://.../06.m3u8
04-30 13:00:00.847  URL: https://.../20210410T182013-287190-06.**m4v**?initSeg=20210410T182013-stream06-initSection.m4i&st=**1619801971**
04-30 13:00:00.914  URL: https://.../09.m3u8
04-30 13:00:01.327  URL: https://.../20210410T182013-287190-09.**m4a**?initSeg=20210410T182013-stream09-initSection.m4i&st=**1619801971**
04-30 13:00:01.478  URL: https://.../20210410T182013-287191-09.m4a?initSeg=20210410T182013-stream09-initSection.m4i&st=1619801977
04-30 13:00:01.522  URL: https://.../20210410T182013-287191-06.m4v?initSeg=20210410T182013-stream06-initSection.m4i&st=1619801977

================================
The number which is bold in the several URLs above is the start time of the segment in UTC seconds.

As it can be seen, in the first attempt the download starts with video start time 6 second after the audio start time.
So the first video frame is displayed and paused while audio is playing. 
6 seconds later normal playback starts.

In the second attempt, however, audio and video started from the same moment and no problematic behavior was  observed.

As there is no perfect way to synchronize this on the server side -- they are two different HTTP requests --
the question is:
does ExoPlayer have some mechanism to prevent this?

**Comment by sruditsky** [comment]
@christosts 
I think I understand now what is really going on and the answer to my question in the previous message is "yes, but it does not always work well". 

I see the following sequence which leads to this problem:
a) initial loadPosition is set to the beginning of a segment in the primary (i.e. video) HLS media playlist
b) this loadPosition is then used to calculate which audio segment should be downloaded first (in HlsChunkSource.getNextChunk())
c) the audio and video segments are _not_ always aligned perfectly, so it happens that the boundary between two audio segments is several milliseconds before the boundary between two video segments.
d) the result is downloading an audio segment with the loadPosition several milliseconds before this segment's end.
e) now this audio segment is being played while the video frame is frozen for the duration of a segment. 

As a way to confirm this I added inside HlsChunkSource.getChunkMediaSequence() something like this:
```
if (the segment found by Util.binarySearchFloor() ends less than 100 msec after targetPositionInPlaylistUs) {
   return next segment
}
```
and I do not see this problem anymore. 

Should this be considered a bug?

**Comment by sruditsky** [comment]
@christosts 
Actually, just adding a small value to targetPositionInPlaylistUs in HlsChunkSource.getChunkMediaSequence() helps to avoid this:

```Java
targetPositionInPlaylistUs += 300_000L;
```

**Comment by christosts** [comment]
Hi,

The provided playlist URL returns an HTTP 403. Can you check it is accessible? Could access be geo-restricted?

As of version 2.13, we added support for Low-Latency HLS live streaming, and, as part of that, we added an API to tune some parameters related to live streaming - see LiveConfiguration [here](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/MediaItem.LiveConfiguration.html) and [here](https://exoplayer.dev/live-streaming.html#configuring-live-playback-parameters). It would be worth trying to see if specifying a `liveTargetOffset` solves this.

Also, we recently [merged a pull request](https://github.com/google/ExoPlayer/commit/e20ea797ef17b68222419312cb591cb73b7a67b9) to better support the EXT-X-START directive, and I'd like to see if there's a way to handle the issue with proper use of EXT-X-START (please ignore this if you're already including EXT-X-START - I haven't been able to examine your playlist yet).

For both ideas, I'd like to check if they're possible to work with the playlists (and if not, what changes would be needed if possible). So, can you please check that we have access to the playlist?

Thanks!

**Comment by sruditsky** [comment]
@christosts

Yes, this is a production content and it is restricted to US.

However, I updated our code to work with 2.13 and I can easily reproduce this issue with 2.13.2, but _not_ with 2.13.3.
I also verified that the playlist on which this happens does _not_ contain EXT-X-START.

I guess we can consider this closed.
If I figure out what exactly fixed this I'll post it here.

Thanks!

**Comment by christosts** [comment]
Good to hear that everything works!
