### ISSUE TITLE
Player is accessed on the wrong thread

### ISSUE THREAD

**Issue by cidevant** [google/ExoPlayer#8843]
I know there is a lot of issues with this topic, but didnt found answer for this one.
The problem occurs, when player is playing and I try to turn off simulator/androidtv. Error stack traces doesnt show that my app is involved in it, only androidtv+exoplayer

```
2021-04-21 14:23:48.417 15207-15207/MY_APP_ID E/SurfaceView: Exception configuring surface
    java.lang.IllegalStateException: Player is accessed on the wrong thread. See https://exoplayer.dev/issues/player-accessed-on-wrong-thread
        at com.google.android.exoplayer2.SimpleExoPlayer.verifyApplicationThread(SimpleExoPlayer.java:1953)
        at com.google.android.exoplayer2.SimpleExoPlayer.getCurrentTimeline(SimpleExoPlayer.java:1640)
        at com.google.android.exoplayer2.analytics.AnalyticsCollector.generateEventTime(AnalyticsCollector.java:816)
        at com.google.android.exoplayer2.analytics.AnalyticsCollector.generateEventTime(AnalyticsCollector.java:865)
        at com.google.android.exoplayer2.analytics.AnalyticsCollector.generateReadingMediaPeriodEventTime(AnalyticsCollector.java:873)
        at com.google.android.exoplayer2.analytics.AnalyticsCollector.onSurfaceSizeChanged(AnalyticsCollector.java:471)
        at com.google.android.exoplayer2.SimpleExoPlayer.maybeNotifySurfaceSizeChanged(SimpleExoPlayer.java:1897)
        at com.google.android.exoplayer2.SimpleExoPlayer.access$3600(SimpleExoPlayer.java:79)
        at com.google.android.exoplayer2.SimpleExoPlayer$ComponentListener.surfaceDestroyed(SimpleExoPlayer.java:2188)
        at android.view.SurfaceView.updateSurface(SurfaceView.java:715)
        at android.view.SurfaceView.windowStopped(SurfaceView.java:242)
        at android.view.ViewRootImpl.setWindowStopped(ViewRootImpl.java:1549)
        at android.view.WindowManagerGlobal.setStoppedState(WindowManagerGlobal.java:647)
        at android.app.Activity.performStop(Activity.java:8027)
        at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:4616)
        at android.app.ActivityThread.handleSleeping(ActivityThread.java:4753)
        at android.app.ActivityThread.access$2500(ActivityThread.java:219)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1957)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

When calling player methods I always do it in this way:

```
new Handler(player.getApplicationLooper()).post(() -> player.setVideoSurfaceView(surfaceView));
```

- Clear reproduction steps including observed and expected behavior

Play video and press powerbutton (simulator or real device - doesnt mattr)

- Output of running "adb bugreport" in the console shortly after encountering
  the issue

[bugreport-sdk_google_atv_x86-QTU1.200805.001-2021-04-21-12-43-48.zip](https://github.com/google/ExoPlayer/files/6350861/bugreport-sdk_google_atv_x86-QTU1.200805.001-2021-04-21-12-43-48.zip)

- ExoPlayer version number

2.13.3

- Android version 

10

- Android device

emualtor, androidtv - doesnt matter

**Comment by icbaker** [comment]
I followed your repro steps using the [demo app](https://google.github.io/ExoPlayer/demo-application.html) and an Android TV emulator running Q but I didn't see any such exception in logcat. Can you reproduce this with the demo app, or only with your application? If it's only with your app, please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that demonstrates the problem in a way that we can build locally. 

This could be an Android Studio project on GitHub, or zipped up and sent to dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Please also update this issue to indicate you’ve done this.

-------

> Error stack traces doesnt show that my app is involved in it, only androidtv+exoplayer

The stack trace looks to me like it's coming via a [`SurfaceHolder.Callback`](https://developer.android.com/reference/android/view/SurfaceHolder.Callback). Assuming the concrete implementation of `SurfaceHolder` is [`SurfaceView`](https://developer.android.com/reference/android/view/SurfaceView) then this part of the javadoc seems possibly relevant (emphasis mine):
> One of the purposes of this class is to provide a surface in which a secondary thread can render into the screen. If you are going to use it this way, you need to be aware of some threading semantics:
>
> * **All SurfaceView and SurfaceHolder.Callback methods will be called from the thread running the SurfaceView's window (typically the main thread of the application)**. They thus need to correctly synchronize with any state that is also touched by the drawing thread.

In your application does the same thread interact with ExoPlayer as run the SurfaceView's window?

**Comment by cidevant** [comment]
> In your application does the same thread interact with ExoPlayer as run the SurfaceView's window?

We are using react-native and player canvas (SurfaceView) is exported to our application as react-native component `PlayerCanvas`. When react-native renders `PlayerCanvas` our player manager links `PlayerCanvas` with with our `Player` instance (implementation of ExoPlayer).

`PlayerCanvas` implementation:

```java
public class PlayerCanvas extends SurfaceView implements SurfaceHolder.Callback {
    public static final String TAG = PlayerCanvas.class.getName();
    public String playerId;
    private Player mPlayer;

    public PlayerCanvas(Context context) {
        super(context);

        Log.d(TAG, "init playerCanvas");
        getHolder().addCallback(this);
    }

    public void setPlayerId(String playerId) {
        this.playerId = playerId;
    }

    public void setPlayer(Player player) {
        this.mPlayer = player;
    }

    @Override
    public void surfaceCreated(SurfaceHolder holder) {
        Log.d(TAG, "surfaceCreated() - this.playerId: " + this.playerId + " canvas hash: " + System.identityHashCode(this));

        if (this.mPlayer != null) {
            mPlayer.setSurfaceView(this);
        } else {
            Log.d(TAG, "Setting playerCanvas with player ID: " + playerId);
            PlayerManager.registerPlayerCanvas(this);
        }
    }

    @Override
    public void surfaceChanged(SurfaceHolder holder, int format, int width, int height) {
        Log.d(TAG, "surfaceChanged " + "width: " + width + ", height: " + height + " canvas hash: " + System.identityHashCode(this));
    }

    @Override
    public void surfaceDestroyed(SurfaceHolder holder) {
        Log.d(TAG, "surfaceDestroyed " + this.playerId + " canvas hash: " + System.identityHashCode(this));
        if (mPlayer != null) {
            PlayerManager.clearCanvas(this.playerId);

            mPlayer = null;
        }
    }
}
```

and `mPlayer.setSurfaceView(this);` implementation in our `Player` is:

```java
    @Override
    public void setSurfaceView(SurfaceView surface) {
        if (surface == null){
            clearSurfaceView();

            surfaceView = null;

            return;
        }

        if (surfaceView != null){
            clearSurfaceView();
        }

        surfaceView = surface;

        new Handler(player.getApplicationLooper()).post(() -> player.setVideoSurfaceView(surfaceView));
    }

    private void clearSurfaceView(){
        new Handler(player.getApplicationLooper()).post(() -> player.clearVideoSurfaceView(surfaceView));
        
        surfaceView = null;
    }

```

**Comment by icbaker** [comment]
It seems likely this is a problem in your application, not in ExoPlayer.

I suggest you look into what thread is being used to run the window of the `SurfaceView` (or `PlayerCanvas`) - possibly the thread used to construct it? I'm not sure.

I'm afraid we don't have time to do detailed debugging of app integrations on this issue tracker.

If you can provide a minimal reproducible example that shows there's a bug in ExoPlayer we can take a look.

**Comment by icbaker** [comment]
The stack trace indicates the problematic callback is happening on the main thread: `at android.app.ActivityThread.main(ActivityThread.java:7356)`

Do you construct your player on a thread other than the main thread? If so that's likely the cause of your problem, and you should be able to resolve it by passing the main thread's Looper during construction, as detailed at the link in the error message: https://google.github.io/ExoPlayer/hello-world.html#a-note-on-threading
