### ISSUE TITLE
OOM crash during offline playback of encoded with proprietary encoder flac tracks

### ISSUE THREAD

**Issue by ALiushenko** [google/ExoPlayer#8845]
Hi everyone,

We're using ExoPlayer (now v.2.12.3) for playback of specific tracks encoded with some custom proprietary encoder and are packed into FLAC container. Unfortunately, I can't give you more details about the encoder due to NDA...

To make the playback actually work, we use ExoPlayer's FLAC extension.
Everything seems to be working fine except for one problem.
We experience OOM crashes during offline playback (when a track is downloaded) of quite big files (duration > ~15 minutes/ or size > ~150MB).
Android Studio's Profiler during the playback shows constantly increasing memory consumption until OOM crash occurs.
I've spent some time for investigation and realized that these OOM crashes appeared with this [commit](https://github.com/google/ExoPlayer/commit/5e090d81b41f8c6dfcb20dc641fe720e97f01cfb)
I reverted this commit, and it seems that OOM went away.

So, guys, I'd really appreciate it if you could revert the commit on your end, of course, if there is no reason not to do it. If you decide to leave it as is, maybe you could give us some more details about why you need it?

Thanks.

**Comment by ojw28** [comment]
Reverted. Thanks!

**Comment by ALiushenko** [comment]
@ojw28  Thank you so much
