### ISSUE TITLE
Occasional `InvalidStateException` from `seekTo` use

### ISSUE THREAD

**Issue by davidvedvick** [google/ExoPlayer#8849]
Occasionally, I see an `InvalidStateException` with `null` reason. While my stacktraces are obfuscated, I assume this is coming out of `seekTo`.

Currently, I prepare a player roughly like this:

```
exoPlayer.setMediaSource(mediaSource, startPositionMs);
exoPlayer.seekTo(startPositionMs); // added in after the above didn't seem to ever fire a Player.STATE_READY after calling prepare below (when startPositionMs > 0)...
exoPlayer.prepare(); // Once a Player.STATE_READY event is received, start playback if desired...
```

Is the above flow a valid lifecycle? Or should my initialization logic follow some other path?

Thanks!

**Comment by icbaker** [comment]
There isn't really enough info here to help you. Please provide the info requested in the [issue template](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/question.md).

------
> While my stacktraces are obfuscated, I assume this is coming out of seekTo.

It should be possible de-obfuscate the stack traces if you have access to the mapping file: https://www.guardsquare.com/en/products/proguard/manual/retrace

------
> ```java
>exoPlayer.prepare(); // Once a Player.STATE_READY event is received, start playback if desired...
>```

Not sure I understand this comment - are you saying that in later code (not shown) you wait for  `STATE_READY` from `Player.EventListener#onPlaybackStateChanged()` and then call `Player#play()`? You shouldn't need to wait for the state change manually - just calling `Player#play()` directly after `Player#prepare()` will start playback when the player is ready.

-----
>```java
>exoPlayer.seekTo(startPositionMs); // added in after the above didn't seem to ever fire a Player.STATE_READY after calling prepare below (when startPositionMs > 0)...
>```

This comment sounds unexpected - if you can reliably reproduce this in a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), can you please file a separate bug?

----

>Is the above flow a valid lifecycle? Or should my initialization logic follow some other path?

The three lines you've provided look reasonable, if slightly redundant as discussed above - but there isn't enough info to say concretely.

**Comment by davidvedvick** [comment]
Thanks for the information, it was still helpful.

I'll close this if that's ok, as my question was answered, and I'll continue to monitor my application. The version of retrace included with Android studio hasn't properly deobfuscated my stack trace, but I'll continue playing around to see if I can get it working. If I do get something more concrete, I'll open a defect and link it back to this question.
