### ISSUE TITLE
An implementation section please in FFmpeg Extensions.

### ISSUE THREAD

**Issue by electrodragon** [google/ExoPlayer#8854]
https://github.com/google/ExoPlayer/blob/release-v2/extensions/ffmpeg/README.md
In this FFmpeg ReadMe, currently, there are two section

1. Build Instructions
2. Using the extension

There is no section that says how to include the built extensions in our own project.
I have been looking for that for 3 days, and still, No luck.
One tutorial said to build an AAR file and use it but how?
Can you guys please provide something?

**Comment by icbaker** [comment]
I think this section at the top of the Build instructions answers your question?

>To use this extension you need to clone the ExoPlayer repository and depend on its modules locally. Instructions for doing this can be found in ExoPlayer's [top level README](https://github.com/google/ExoPlayer/blob/release-v2/README.md).

Once you've got your app depending on a local copy of ExoPlayer, and then you build the FFmpeg extension inside that local copy, the extension should be available to your app.
