### ISSUE TITLE
Called "setParameter"  frequently, playing live contents since 2.13.x

### ISSUE THREAD

**Issue by HyowonHwang** [google/ExoPlayer#8861]
I've found that my override audio processor called flush so frequently than 2.12.x while playing live normal hls(not low latency) by below changes.

<img width="1593" alt="updateposion_setparameter_audio_processor_flush" src="https://user-images.githubusercontent.com/7637498/115821516-e1039200-a43d-11eb-8875-349980d56058.png">

Also, It seems there's a problem of floating point comparison or something else.
I just wondered if this was what you expected or not.

Below are my environment. Hope you helpful.

- ExoPlayer version number
   2.13.3
- Android version
  Android 11
- Android device
  SM-N970

**Comment by tonihei** [comment]
This is expected and triggered by the automatic playback speed adjustment for live streams we added in 2.13.

The changes shouldn't happen more often than once per second and they should stop after a while (once the live offset is at its desired value). 

So the questions are:
 - Do you see it happening more often than once per second? 
 - Is this causing any issues in your app?

If you want to disable speed adjustment for any reasons, you can set `minPlaybackSpeed` and `maxPlaybackSpeed` to `1.0` as explained here: https://exoplayer.dev/live-streaming.html#configuring-live-playback-parameters

**Comment by HyowonHwang** [comment]
Yes,  I see  it happening once per second and keeping during almost 50 seconds. 
That makes `AudioProcessor.flush` frequently, my implemented codes of it makes audio stuttering.

I think I fix this in my side and just understood the operation and will follow your guide in case that don't want to up playback speed. 

Thanks,
Hyowon
