### ISSUE TITLE
Playback is intermittent with response code 206 for HLS content

### ISSUE THREAD

**Issue by GouravSna** [google/ExoPlayer#8862]
**ExoPlayer version:** release-v2
**Video link:** https://drive.google.com/file/d/1c4ifF88UGKQJ5fh6lfwJjDUseGbE6xmL/view?usp=sharing
**Link for testing:** Have sent on email

**Steps to reproduce:**
1.Play the content 
2. Select the video track of 1280 * 544 0.28Mbps, 640 * 272 0.08 Mbps etc
3. See the video playback is intermittent

I checked in charles, i can see on this request, 206 response is coming. Can you please check why it is happening. I don't have Dash variant of this where I could check it.

**PS:** In our player code, when we are passing `initialBitrateEstimate` to `DefaultBandwidthMeter` (Any value from the manifest), there we see this video issue for initial 15-20 seconds; after that it work fine. Here also I do see 206 response code.

**Comment by icbaker** [comment]
The low bitrate tracks are I-frame-only tracks, identified in the manifest with `#EXT-X-I-FRAME-STREAM-INF`.

These won't be automatically selected by the ExoPlayer ABR algorithm, but if you explicitly select them then it will try to play them. These are usually included in the manifest to facilitate trickplay scrubbing - they're generally not intended for normal speed playback.

https://github.com/google/ExoPlayer/issues/8313 has info on identifying trickplay tracks programmatically.

**Comment by icbaker** [comment]
HTTP 206 is the normal response code for [range requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests), which ExoPlayer will use if the server indicates support via the `Accept-Ranges:` response header. I'm not sure it's relevant here - it generally indicates everything is working OK.

**Comment by GouravSna** [comment]
Thanks for your response @icbaker
