### ISSUE TITLE
no sound on MKV file

### ISSUE THREAD

**Issue by Mkurbanov** [google/ExoPlayer#8863]
On Samsung devices working fine but on Redmi devices no sound of the film. (Example on Redmi note 9 pro)
i am using version of exoplayer _2.13.3_

MKV file : [film](http://95.85.127.129:9000/movies/4103/ce6605be-6b9f-4e51-96e7-eaf6bd5d23c8.mkv?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20210423%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20210423T100907Z&X-Amz-Expires=216000&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%3D%22ce6605be-6b9f-4e51-96e7-eaf6bd5d23c8.mkv%22&X-Amz-Signature=3efa8d658e2ef1cda57acdfeea17103a3ae4a01e04ab9f8f8f38897d3fc91785)

**Comment by icbaker** [comment]
The provided link returns me the following XML:

```
<Error>
<Code>AccessDenied</Code>
<Message>Request has expired</Message>
<Key>4103/ce6605be-6b9f-4e51-96e7-eaf6bd5d23c8.mkv</Key>
<BucketName>movies</BucketName>
<Resource>/movies/4103/ce6605be-6b9f-4e51-96e7-eaf6bd5d23c8.mkv</Resource>
<RequestId>16795A93D0BFB3C3</RequestId>
<HostId>c031f430-0f68-43c3-a3d8-892a0317b451</HostId>
</Error>
```

**Comment by aadityadoshi17798** [comment]
Same issue 
Try link - https://beta.sastatv.com/Hindi/Saina%20(2021)%20HEVC.mkv
Also event logger says the below mentioned
MediaCodecAudioRenderer [
2021-04-25 02:27:58.569 D/EventLogger:     Group:0, adaptive_supported=N/A [
2021-04-25 02:27:58.569 D/EventLogger:       [ ] Track:0, id=3, mimeType=audio/eac3, channels=6, sample_rate=48000, language=hi, label="", supported=NO_UNSUPPORTED_TYPE
2021-04-25 02:27:58.569 D/EventLogger:     ]
2021-04-25 02:27:58.569 D/EventLogger:   ]

**Comment by icbaker** [comment]
@aadityadoshi17798 that logcat (specifically `supported=NO_UNSUPPORTED_TYPE`) indicates the device you're using doesn't support the `audio/eac3` audio sample format. More info on supported formats: https://exoplayer.dev/supported-formats.html

**Comment by doshi-github** [comment]
Any way to fix this and make it work on all devices ?
Also currently I am using emulator in Android Studio
Here .mkv file is obtained from the link mentioned above

**Comment by Mkurbanov** [comment]
> The provided link returns me the following XML:
> 
> ```
> <Error>
> <Code>AccessDenied</Code>
> <Message>Request has expired</Message>
> <Key>4103/ce6605be-6b9f-4e51-96e7-eaf6bd5d23c8.mkv</Key>
> <BucketName>movies</BucketName>
> <Resource>/movies/4103/ce6605be-6b9f-4e51-96e7-eaf6bd5d23c8.mkv</Resource>
> <RequestId>16795A93D0BFB3C3</RequestId>
> <HostId>c031f430-0f68-43c3-a3d8-892a0317b451</HostId>
> </Error>
> ```

new link: [Google Drive](https://drive.google.com/file/d/1sIA3CzqGoAyDOl36MGWcafMUV0l-1ihX/view?usp=sharing)

**Comment by icbaker** [comment]
@Mkurbanov When I play the provided file in the demo app I see this in logcat:

```
tracks [eventTime=0.73, mediaPos=0.00, window=0, period=0
  MediaCodecVideoRenderer [
    Group:0, adaptive_supported=N/A [
      [X] Track:0, id=1, mimeType=video/avc, codecs=avc1.640828, res=1920x804, language=und, supported=YES
    ]
  ]
  MediaCodecAudioRenderer [
    Group:0, adaptive_supported=N/A [
      [ ] Track:0, id=2, mimeType=audio/eac3, channels=6, sample_rate=48000, language=ru, supported=NO_UNSUPPORTED_TYPE
    ]
  ]
  TextRenderer []
  MetadataRenderer []
  CameraMotionRenderer []
]
```

As mentioned above, this indicates the device I'm using doesn't support the `audio/eac3` audio sample format. It's likely your device doesn't either (some might, but it's not a requirement).

More info on supported formats: https://exoplayer.dev/supported-formats.html
