### ISSUE TITLE
Ads aren't playing with MediaItem.

### ISSUE THREAD

**Issue by ArchanaGwda** [google/ExoPlayer#8866]
Hi, 

I am trying to integrate ads with exoplayer for TV application. Earlier I was using the adsLoader for ad play with exopleyer version 2.6.1. Facing some with focus  issues on ad play for skip ads. And decided to upgrade to new dependencies. Now I have upgraded to version 2.13.3.

With mediaItem not able to play the ads. Ads are not playing. I am not getting where I am wrong. I am not getting any errors. Please help me out at the earliest. 

dependencies: 
```
    implementation 'com.google.android.exoplayer:exoplayer:2.13.3'
    implementation 'com.google.android.exoplayer:exoplayer-core:2.13.3'
    implementation 'com.google.android.exoplayer:exoplayer-dash:2.13.3'
    implementation 'com.google.android.exoplayer:exoplayer-hls:2.13.3'
    implementation 'com.google.android.exoplayer:exoplayer-smoothstreaming:2.13.3'
    implementation 'com.google.android.exoplayer:exoplayer-ui:2.13.3'
    implementation 'com.google.android.exoplayer:extension-ima:2.13.3'
```

```
    MediaSourceFactory mediaSourceFactory =
            new DefaultMediaSourceFactory(context)
                    .setAdsLoaderProvider(this::getAdsLoader)
                    .setAdViewProvider(playerView);
    player = new SimpleExoPlayer.Builder(context)
            .setMediaSourceFactory(mediaSourceFactory)
            .build();
```

```
private AdsLoader getAdsLoader(MediaItem.AdsConfiguration adsConfiguration) {
    if (adsLoader == null) {
      adsLoader = new ImaAdsLoader.Builder(mContext).setDebugModeEnabled(true).build();
    }
    adsLoader.setPlayer(player);
    return adsLoader;
}
```

```
private MediaSource buildMediaSource(Uri uri) {
    @ContentType int type = Util.inferContentType(uri);
    Uri adTagUri = Uri.parse("https://pubads.g.doubleclick.net/gampad/ads?iu=/1007232/Testing_APP_Ads/Test_Vast_TAG&description_url=https%3A%2F%2Fwww.indiatoday.in%2F&tfcd=0&npa=0&sz=640x480%7C1280x720&gdfp_req=1&output=vast&unviewed_position_start=1&env=vp&impl=s&correlator=");
    MediaItem mediaItem =
            new MediaItem.Builder().setUri(uri).setAdTagUri(adTagUri).build();
    switch (type) {
      case C.TYPE_DASH:
        return new DashMediaSource.Factory(
                new DefaultDashChunkSource.Factory(mediaDataSourceFactory),
                manifestDataSourceFactory)
            .createMediaSource(mediaItem);
      case C.TYPE_SS:
        return new SsMediaSource.Factory(
                new DefaultSsChunkSource.Factory(mediaDataSourceFactory), manifestDataSourceFactory)
            .createMediaSource(mediaItem);
      case C.TYPE_HLS:
        return new HlsMediaSource.Factory(mediaDataSourceFactory).createMediaSource(mediaItem);
      case C.TYPE_OTHER:
        return new ExtractorMediaSource.Factory(mediaDataSourceFactory).createMediaSource(mediaItem);
      default:
        throw new IllegalStateException("Unsupported type: " + type);
    }
  }
```

```
      MediaSource contentMediaSource = buildMediaSource(Uri.parse(url));
      player.setMediaSource(contentMediaSource);
      player.prepare();
```

**Comment by icbaker** [comment]
The `MediaSourceFactory` implementations you're using in that code snippet (`Dash`, `Ss`, `Hls`, and `Extractor`) don't handle the ad information inside `MediaItem`. The only ExoPlayer-provided `MediaSourceFactory` implementation that does is `DefaultMediaSourceFactory`.

You should either use `DefaultMediaSourceFactory` or re-implement the way it handles the ad information from `MediaItem` in your custom `MediaSourceFactory` implementation.

**Comment by ArchanaGwda** [comment]
Hi @icbaker thanks for the response. Please let me know how can I make use of `DefaultMediaSourceFactory` for `DASH` and `HLS` media. Can we use `DefaultMediaSourceFactory` for Dash implementation?

**Comment by icbaker** [comment]
From the [`DefaultMediaSourceFactory` javadoc](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/source/DefaultMediaSourceFactory.html):

>This implementation delegates calls to `createMediaSource(MediaItem)` to the following factories:
>
>* `DashMediaSource.Factory` if the item's uri ends in '.mpd' or if its `mimeType` field is explicitly set to `MimeTypes.APPLICATION_MPD` (Requires the exoplayer-dash module to be added to the app).

**Comment by ArchanaGwda** [comment]
@icbaker Can I get some sample code for for supporting ads for Dash and HLS media with mediaItem?

**Comment by icbaker** [comment]
https://exoplayer.dev/hello-world.html

**Comment by ArchanaGwda** [comment]
This example doesn't have details for ad support for Dash or HLS. I need some sample to code to understand how to implement ad support for Dash and HLS.

**Comment by icbaker** [comment]
https://exoplayer.dev/ad-insertion.html#declarative-ad-support

**Comment by ArchanaGwda** [comment]
@icbaker I have followed the same document to implement. And I have added the code what I have added. Please let me know what changes I have to make so that ads will play.

**Comment by icbaker** [comment]
By calling `player.setMediaSource()`, you're causing the library to ignore the `MediaSourceFactory` you've provided (because you're providing a fully built source, so there's no need for the library to construct one).

Change these 2 lines:

```
MediaSource contentMediaSource = buildMediaSource(Uri.parse(url));
player.setMediaSource(contentMediaSource);
```

To:

```
Uri adTagUri = Uri.parse("https://pubads.g.doubleclick.net/gampad/ads?iu=/1007232/Testing_APP_Ads/Test_Vast_TAG&description_url=https%3A%2F%2Fwww.indiatoday.in%2F&tfcd=0&npa=0&sz=640x480%7C1280x720&gdfp_req=1&output=vast&unviewed_position_start=1&env=vp&impl=s&correlator=");
MediaItem mediaItem = new MediaItem.Builder().setUri(Uri.parse(url)).setAdTagUri(adTagUri).build();
player.setMediaItem(mediaItem)
```

And remove your `buildMediaSource()` method completely.

**Comment by ArchanaGwda** [comment]
@icbaker If I change to above code, on click of other data items, which is not changing to other content. Which is still playing the same content.

**Comment by ArchanaGwda** [comment]
@icbaker Any Updates on this? Do we need to re initiate the player each time if there is content change ?? This is weird behavior I am getting. If I don't understand the flow I can't fix this issue. Please let me know why this is happening. 

If I change to `setMediaSource` which works proper but no ads will play. 

If I use `setMediaItem` I have **LiveTV** playing on launch. Where ad is getting played and after that **Live content** starts playing. **Only the live content is being played every time even though I choose some other content**. This is only happening after I change to `setMediaItem`. Your help is indeed. And will be appreciated. I am stuck with this issue. :-(

**Comment by icbaker** [comment]
There are no updates. You haven't provided enough info for us to help. We generally don't have capacity to provide detailed app-specific debugging on this issue tracker. If you believe there's a bug in the ExoPlayer library please clearly isolate the problematic behaviour in a way that we can reproduce.

Your description of the problem is unclear. I don't know what this means:
>on click of other data items, which is not changing to other content.

nor this:
> If I use `setMediaItem` I have **LiveTV** playing on launch. Where ad is getting played and after that **Live content** starts playing. **Only the live content is being played every time even though I choose some other content**. This is only happening after I change to `setMediaItem`.

Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that demonstrates the problem in a way that we can build locally. 

This could be an Android Studio project on GitHub, or zipped up and sent to dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Please also update this issue to indicate you’ve done this.

**Comment by ArchanaGwda** [comment]
@icbaker Hi Have fixed this issue. I was missing out the mime type for each stream type. By adding the mime type I am able to play the content. Thank you for your help. Now I am stuck at playing post roll ads. Could you please help me to play post roll ads ?
Instead of `createMediaSource()` I replaced with `createMediaItem()`
Here is my code structure, 

```
private MediaItem createMediaItem(Uri uri) {
    Uri adTagUri = Uri.parse("https://pubads.g.doubleclick.net/gampad/ads?iu=/1007232/Testing_APP_Ads/Test_Vast_TAG&description_url=https%3A%2F%2Fwww.indiatoday.in%2F&tfcd=0&npa=0&sz=640x480%7C1280x720&gdfp_req=1&output=vast&unviewed_position_start=1&env=vp&impl=s&correlator=");
    @ContentType int type = Util.inferContentType(uri);
    switch (type) {
      case C.TYPE_DASH:
      case C.TYPE_HLS:
        return new MediaItem.Builder()
                .setUri(uri)
                .setAdTagUri(adTagUri)
                .setMimeType(MimeTypes.APPLICATION_M3U8)
                .build();
      case C.TYPE_SS:
        return new MediaItem.Builder()
                .setUri(uri)
                .setAdTagUri(adTagUri)
                .setMimeType(MimeTypes.APPLICATION_SS)
                .build();
      case C.TYPE_OTHER:
        return new MediaItem.Builder()
                .setUri(uri)
                .setAdTagUri(adTagUri)
                .setMimeType(MimeTypes.BASE_TYPE_APPLICATION)
                .build();
      default:
        throw new IllegalStateException("Unsupported type: " + type);
    }
  }
```

```
      MediaItem mediaItem = createMediaItem(Uri.parse(url));
      player.setMediaItem(mediaItem);
      player.prepare();
      play();
```

As per the documentation, shows only about mid roll ads. [Playlists with ads](https://exoplayer.dev/ad-insertion.html#using-a-third-party-ads-sdk).

**Comment by icbaker** [comment]
I used the ad tag URL you provided in the demo app by adding it to the [JSON file](https://exoplayer.dev/demo-application.html#1-editing-assetsmediaexolistjson):

```
{
  "name": "Issue #8866",
  "uri": "https://html5demos.com/assets/dizzy.mp4",
  "ad_tag_uri": "https://pubads.g.doubleclick.net/gampad/ads?iu=/1007232/Testing_APP_Ads/Test_Vast_TAG&description_url=https%3A%2F%2Fwww.indiatoday.in%2F&tfcd=0&npa=0&sz=640x480%7C1280x720&gdfp_req=1&output=vast&unviewed_position_start=1&env=vp&impl=s&correlator="
},
```

I saw only a pre-roll ad, no mid-roll or post-roll. Is that what you expect? I see the same behaviour at this test player: https://googleads.github.io/googleads-ima-html5/vsi/

**Comment by ArchanaGwda** [comment]
@icbaker No, I know this TAG is only for pre roll ad. I want to know the procedure/code help to implement post roll ads.

**Comment by icbaker** [comment]
There's not an obvious answer to that question - post-roll tags should 'just work'.

If your post-roll tag works in the demo app and not in your app then please provide a minimally reproducible example so we can reproduce what your app is doing.

If it doesn't work in the demo app then please provide the tag URI so we can investigate.

**Comment by ArchanaGwda** [comment]
@icbaker I am not telling that, its not playing in demo app. Which is playing well. If we pass vmap tags. 
 What I am trying to tell to tell you is that we are using vast tags. If we use vmap post rolls are paying well. I am seeking your help to integrate post roll ads to my code. I have already posted my code structure in the last reply.

We don't have document to integrate post roll ads. Can I get sample code that would be helpful to me.

**Comment by ArchanaGwda** [comment]
@icbaker Hi Any Update on this? Please let me help to integrate post roll ads with vast tags. Sample code of lines would help me better.

**Comment by icbaker** [comment]
You've neither described your problem(s) clearly nor provided a means for us to reproduce them.

Without that info we can't help you.

We provide sample code at http://exoplayer.dev and in the demo app (which supports ad tags):
https://github.com/google/ExoPlayer/tree/release-v2/demos/main

We don't have the capacity to provide code samples tailored to every app.

If you can ask your questions clearly we'll try and answer them. If the problem(s) relate to a behaviour of your app it's very unlikely we can answer without being able able to reproduce the problematic behaviour you're seeing. The code snippets you've provided so far do not give us enough information to reproduce anything.

**Comment by andrewlewis** [comment]
I agree with @icbaker's points. Lack of a clear explanation it makes it less efficient to help and we don't have time to provide samples for every use case.

It sounds like you may be trying to play a VAST ad tag as a postroll. That isn't directly supported (as mentioned in #3694 the IMA extension plays all VAST tags as prerolls). You may be able to do a slight hack to get the behavior you are looking for, by playing two media sources, the first of which is the content and the second of which is an `AdsMediaSource` using a short `SilenceMediaSource` as the content and the VAST ad tag as its inserted ad. The effect is that the content plays, then the VAST ad plays as the preroll of a very short piece of silent content, which looks like a postroll.
