### ISSUE TITLE
Unable to build ffmpeg extension

### ISSUE THREAD

**Issue by dzolnai** [google/ExoPlayer#8868]
I have upgraded our in app version of ExoPlayer to 2.13.3.
Now we also want to build the ffmpeg extension to go along with it, however, I get a build error when the `build_ffmpeg.sh` script launches:

```
Using 8 jobs for make
~/Library/Android/sdk/ndk/21.0.6113669/toolchains/llvm/prebuilt/darwin-x86_64/bin/armv7a-linux-androideabi16-clang is unable to create an executable file.
C compiler test failed.

...
```
After that it still continues with building, but the output files are missing. Previously, I was able to build the 2.11.3 extension with this same machine.

I have checked, and the referenced file does exist:
```
Daniels-MacBook-Pro-2:jni dzolnai$ ls -l ~/Library/Android/sdk/ndk/21.0.6113669/toolchains/llvm/prebuilt/darwin-x86_64/bin/armv7a-linux-androideabi16-clang
-rwxr-xr-x  1 dzolnai  staff  177 Jun  8  2020 /Users/dzolnai/Library/Android/sdk/ndk/21.0.6113669/toolchains/llvm/prebuilt/darwin-x86_64/bin/armv7a-linux-androideabi16-clang
```

Switching over to the r20 NDK does not help. I also tried versions `21.4.7075529` and `22.1.7171670` without any success.
I am building the `aac ac3 eac3` decoders.
I have checked, the checked out FFMPEG version is 4.2, as instructed.

Do you perhaps have any idea what might be wrong in my case?

**Comment by kim-vde** [comment]
It works for me with ExoPlayer `2.13.3` and NDK `21.4.7075529`.

```
Using 12 jobs for make
install prefix            /usr/local
source path               .
C compiler                /Users/kimvde/Library/Android/sdk/ndk/21.4.7075529//toolchains/llvm/prebuilt/darwin-x86_64/bin/armv7a-linux-androideabi16-clang
...
```
[Here](https://github.com/google/ExoPlayer/tree/r2.13.3/extensions/ffmpeg) is the link to the installation guide in case you don't know about it.

Have you deleted the ffmpeg folder in `"${FFMPEG_EXT_PATH}/jni"` before creating the symbolic link with `ln -s "$FFMPEG_PATH" ffmpeg`? Have you tried running the commands of `build_ffmpeg.sh` one by one to see which one is failing? You could also tried to reinstall the NDK. If I remember correctly, I installed mine using Android Studio.

**Comment by dzolnai** [comment]
> Here is the link to the installation guide in case you don't know about it.

I have tried cloning both the ExoPlayer and ffmpeg repo's again, and following the guide step by step, but I get the same result.

> Have you deleted the ffmpeg folder in "${FFMPEG_EXT_PATH}/jni" before creating the symbolic link with ln -s "$FFMPEG_PATH" ffmpeg?

No, the ffmpeg directory is there.

> You could also tried to reinstall the NDK. If I remember correctly, I installed mine using Android Studio

NDK versions were freshly installed from Android Studio.

> Have you tried running the commands of build_ffmpeg.sh one by one to see which one is failing? 

It fails on the configure call. To be specific, my configure command looks like this:

```
./configure \
     --libdir=android-libs/armeabi-v7a \
     --arch=arm \
     --cpu=armv7-a \
     --cross-prefix="~/Library/Android/sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/darwin-x86_64/bin/armv7a-linux-androideabi16-" \
     --nm="~/Library/Android/sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-nm" \
     --ar="~/Library/Android/sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-ar" \
     --ranlib="~/Library/Android/sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-ranlib" \
     --strip="~/Library/Android/sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-strip" \
     --extra-cflags="-march=armv7-a -mfloat-abi=softfp" \
     --extra-ldflags="-Wl,--fix-cortex-a8" \
     --target-os=android \
	 --enable-static \
	 --disable-shared \
	 --disable-doc \
	 --disable-programs \
	 --disable-everything \
	 --disable-avdevice \
	 --disable-avformat\
	  --disable-swscale \
	  --disable-postproc \
	  --disable-avfilter \
	  --disable-symver \
	  --disable-avresample \
	  --enable-swresample \
	  --extra-ldexeflags=-pie \
	  --enable-decoder=aac \
	  --enable-decoder=ac3 \
	  --enable-decoder=eac3
```

I remember the r2.11.3 build working on this exact same machine. Trying to build 2.11.3 again results in the same error.
Is there any other software I could check?
This is my clang:
```
clang -v
Apple clang version 12.0.0 (clang-1200.0.32.27)
Target: x86_64-apple-darwin20.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

This is what I see when I ask the binary file which throws the error:
```
~/Library/Android/sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/darwin-x86_64/bin/armv7a-linux-androideabi16-clang --version
Android (7019983 based on r365631c3) clang version 9.0.9 (https://android.googlesource.com/toolchain/llvm-project a2a1e703c0edb03ba29944e529ccbf457742737b) (based on LLVM 9.0.9svn)
Target: armv7a-unknown-linux-android16
Thread model: posix
InstalledDir: /Users/dzolnai/Library/Android/sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/darwin-x86_64/bin
```

**Comment by kim-vde** [comment]
> Have you deleted the ffmpeg folder in "${FFMPEG_EXT_PATH}/jni" before creating the symbolic link with ln -s "$FFMPEG_PATH" ffmpeg?

I meant that you should delete the folder before creating the symbolic link, and then make sure that the symbolic link has been correctly created. 

I don't see anything wrong in the `./configure` command.

My clang version is a bit older.

```
clang -v
Apple clang version 11.0.3 (clang-1103.0.32.29)
Target: x86_64-apple-darwin20.3.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

Running the last command, I get the same as you.
```
~/Library/Android/sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/darwin-x86_64/bin/armv7a-linux-androideabi16-clang --version
Android (7019983 based on r365631c3) clang version 9.0.9 (https://android.googlesource.com/toolchain/llvm-project a2a1e703c0edb03ba29944e529ccbf457742737b) (based on LLVM 9.0.9svn)
Target: armv7a-unknown-linux-android16
Thread model: posix
InstalledDir: /Users/kimvde/Library/Android/sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/darwin-x86_64/bin
```
Looking at older Github issues, it seems you are not the first one to run into this but none if the issues has a clear explanation of what was going wrong. Searching for "clang is unable to create an executable file" on Google seems to indicate that the problem is caused by ffmpeg. 

Any idea of what could be wrong @andrewlewis ?

**Comment by andrewlewis** [comment]
There should be a log file with more verbose output after you see the error `unable to create an executable file`, possibly called `config.log` (that may not be the exact name). Please could you try to find the verbose logging and attach it here? I think that may help us track down the root cause.

**Comment by dzolnai** [comment]
> I meant that you should delete the folder before creating the symbolic link, and then make sure that the symbolic link has been correctly created.

Yes, the symlink works fine.

Here you can find the config.log created after running the long command from my previous comment:
[config.log](https://github.com/google/ExoPlayer/files/6390365/config.log)

**Comment by andrewlewis** [comment]
```
~/Library/Android/sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/darwin-x86_64/bin/armv7a-linux-androideabi16-clang: No such file or directory
```

Does clang exist at this path?

**Comment by dzolnai** [comment]
Yes:
```
Daniels-MacBook-Pro-2:ffmpeg dzolnai$ ls -l ~/Library/Android/sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/darwin-x86_64/bin/armv7a-linux-androideabi16-clang
-rwxr-xr-x  1 dzolnai  staff  177 Apr 26 12:29 /Users/dzolnai/Library/Android/sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/darwin-x86_64/bin/armv7a-linux-androideabi16-clang
```

**Comment by dzolnai** [comment]
I have changed TMPDIR to a `tmp` directory I created inside the `ffmpeg` root repo.
Now the end of my logs look like this:
```
BEGIN /Users/dzolnai/Documents/Work/ffmpeg/tmp/ffconf.fv1NJEWM/test.c
    1	int main(void){ return 0; }
END /Users/dzolnai/Documents/Work/ffmpeg/tmp/ffconf.fv1NJEWM/test.c
~/Library/Android/sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/darwin-x86_64/bin/armv7a-linux-androideabi16-clang -march=armv7-a -mfloat-abi=softfp -march=armv7-a -c -o /Users/dzolnai/Documents/Work/ffmpeg/tmp/ffconf.fv1NJEWM/test.o /Users/dzolnai/Documents/Work/ffmpeg/tmp/ffconf.fv1NJEWM/test.c
./configure: line 974: ~/Library/Android/sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/darwin-x86_64/bin/armv7a-linux-androideabi16-clang: No such file or directory
C compiler test failed.
```

I have checked, and the file `/Users/dzolnai/Documents/Work/ffmpeg/tmp/ffconf.fv1NJEWM/test.c` Does not exist. The `tmp` directory is completely empty. Maybe the part where it should create the temporary file goes wrong?
I'll try to play a bit around with permissions and file locations, I know that macOS has added some special permissions to accessing special directories like Documents or Desktop.

**Comment by dzolnai** [comment]
I finally found the solution. Moving the `ffmpeg` directory outside Documents did not help.
But when I copied the NDK over to a temporary place, it all started working.

So for others, if you run into a similar issue, here's what I did:

```
cp -R ~/Library/Android/sdk/ndk/21.4.7075529/ /tmp/ndk-copy/
NDK_PATH="/tmp/ndk-copy/"
```

The first command might take a minute to complete.
I still don't understand the cause behind it, but I'm glad that I finally got it working.

**Comment by dzolnai** [comment]
I got an even better solution: it turns out there is no need to copy the NDK to another place. The issue was the tilde (`~`) in the NDK path.
This works:
```
NDK_PATH="/Users/dzolnai/Library/Android/sdk/ndk/21.4.7075529/"
```
This does not work:
```
NDK_PATH="~/Library/Android/sdk/ndk/21.4.7075529/"
```
Maybe some command is ran by a different user? Or there is some path processing done which can not handle the tilde?
Anyways, feel free to close this issue if you don't have any further comments or ideas.

**Comment by kim-vde** [comment]
Thanks for sharing the solution! I could indeed reproduce by changing the NDK_PATH to start with a tilde.
