### ISSUE TITLE
Internal track renderer error.

### ISSUE THREAD

**Issue by hex81** [google/ExoPlayer#887]
ExoPlayer Error. We have three Exoplayers on different devices. Only one of them happened below issue.

E/ExoPlayerImplInternal( 2207): Internal track renderer error.

E/ExoPlayerImplInternal( 2207): com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 404

E/ExoPlayerImplInternal( 2207): 	at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:481)

E/ExoPlayerImplInternal( 2207): 	at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:401)

E/ExoPlayerImplInternal( 2207): 	at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:203)

E/ExoPlayerImplInternal( 2207): 	at android.os.Handler.dispatchMessage(Handler.java:95)

E/ExoPlayerImplInternal( 2207): 	at android.os.Looper.loop(Looper.java:137)

E/ExoPlayerImplInternal( 2207): 	at android.os.HandlerThread.run(HandlerThread.java:61)

E/ExoPlayerImplInternal( 2207): 	at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)

E/ExoPlayerImplInternal( 2207): Caused by: com.google.android.exoplayer.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 404

E/ExoPlayerImplInternal( 2207): 	at com.google.android.exoplayer.upstream.HttpDataSource.open(HttpDataSource.java:265)

E/ExoPlayerImplInternal( 2207): 	at com.google.android.exoplayer.upstream.UriDataSource.open(UriDataSource.java:66)

E/ExoPlayerImplInternal( 2207): 	at com.google.android.exoplayer.upstream.DataSourceStream.load(DataSourceStream.java:223)

E/ExoPlayerImplInternal( 2207): 	at com.google.android.exoplayer.chunk.Chunk.load(Chunk.java:182)

E/ExoPlayerImplInternal( 2207): 	at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:206)

E/ExoPlayerImplInternal( 2207): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)

E/ExoPlayerImplInternal( 2207): 	at java.util.concurrent.FutureTask.run(FutureTask.java:234)

E/ExoPlayerImplInternal( 2207): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)

E/ExoPlayerImplInternal( 2207): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)

E/ExoPlayerImplInternal( 2207): 	at java.lang.Thread.run(Thread.java:841)

**Comment by ojw28** [comment]
This is a not found http exception returned from the server, as indicated by:

`HttpDataSource$InvalidResponseCodeException: Response code: 404`
