### ISSUE TITLE
MediaButtonEventHandler in extension-media2

### ISSUE THREAD

**Issue by lwld** [google/ExoPlayer#8876]
Hi,
we currently use `extension-mediasession` with the support `MediaSessionCompat`, and we are handling some hardware button events with a custom `MediaButtonEventHandler` (set in the media session connector with `MediaSessionConnector.setMediaButtonEventHandler(MediaButtonEventHandler)`). Essentially, we're handling `KEYCODE_MEDIA_NEXT`/`_PREVIOUS` and `_STOP` for custom handling before/after playback (fetch temporary stream urls, clean up resources..).

I'm trying to update the implementation to `androidx.media2.MediaSession` with `extension-media2` and achieve the same controls. Is there a similar way to do handle media button events in the new `SessionPlayerConnector`? I can't find anything there - am I missing something?

I tried setting a custom `ControlDispatcher` in the `SessionPlayerConnector` that overrides `dispatchPrevious/Next/Stop` but that doesn't seem to get called on media buttons. I also tried the `MediaSession.SessionCallback` with overriding `SkipCallback` but don't find anything to override for next/previous/stop. 

Or do we need to use an `intent-filter` for `android.intent.action.MEDIA_BUTTON` in our service or configure a `androidx.media.session.MediaButtonReceiver`? But the media session already receives the events (according to https://developer.android.com/guide/topics/media-apps/mediabuttons, "On Android 5.0 (API level 21) and higher, Android automatically dispatches media button events to your active media session"). Do you know if this is handled in the same way in media2 session?

### Question
Is it possible to intercept/handle media button events (hardware, bluetooth?) in `extension-media2` with `androidx.media2.MediaSession`, similarly to `MediaButtonEventHandler`? If so, can you hint me to a relevant code point, or where to find documentation or example?  

### Searched documentation and issues
https://medium.com/google-exoplayer/the-media2-extension-for-exoplayer-d6b7d89b9063
https://exoplayer.dev/
https://developer.android.com/reference/androidx/media2/session/package-summary
https://developer.android.com/guide/topics/media-apps/mediabuttons

Related issue (but not regarding `media2`): #5719

**Comment by ojw28** [comment]
@jaewan-github - Would you be able to provide some input on this question? Thanks!

**Comment by jaewan-github** [comment]
media2 intentionally disallows to modify media key behaviors, because too many users have complaint that their headsets behave unexpectedly rather than their manual says so. Could you tell me about the details about your customization? I'll have a look whether it can be the part of the common use case.
