### ISSUE TITLE
Should switchTargetView support PlayerView <--> StyledPlayerView?

### ISSUE THREAD

**Issue by eneim** [google/ExoPlayer#8881]
One of my practice to keep the Player instance across different playback surfaces is to use the `switchTargetView` method. It is so useful, but it is not possible to switch the target from a PlayerView to a StyledPlayerView and back. As far as I can see, the implementation of `setPlayer` is similar for these classes. 

I want to ask (1) Is there any concern about switching a `Player` instance from a `PlayerView` to a `StyledPlayerView` and back? (2) Why not have a `switchTargetView` method that supports both Views (I sure can create one for my use case, so question 1 is more critical I suppose)?

Thanks in advance.

**Comment by ojw28** [comment]
We could add a new interface to make this possible, but it seems pretty unusual to be using both within a single app, given they look so different. What's the use case for doing that?

**Comment by eneim** [comment]
@ojw28 Thanks for the answer, having an interface on top of these Views would be nice.

> What's the use case for doing that?

It is a library that supports switching Player between different playback _targets_ (in other words, different PlayerView instances in terms of the old ExoPlayer versions). Thinking like having an Activity that uses StyledPlayerView and when the user clicks it, it opens another Activity that uses PlayerView, my implementation keeps the Player instance at Application scope, and just switches between the targets to keep the playback experience smoothly. 

Since it is a library, it is not really friendly to tell the clients they should use PlayerView only, or StyledPlayerView only in their app. (I acknowledge that maybe it is just me doing this, so it is fine if I should do it myself. It is good to know that "switching Player between PlayerView and StyledPlayerView" is not something bad technically).

**Comment by ojw28** [comment]
I think we can close this as "sufficiently obscure" that we don't need to provide support directly in the library. As you've noted, it's pretty easy for you to implement your own version that works with both views for your specific case.
