### ISSUE TITLE
Is it possible to grab a frame from a video without displaying it?

### ISSUE THREAD

**Issue by danergo** [google/ExoPlayer#8883]
I know I can get a frame of a playing video by using TextureView and its getBitmap function.

However can I also get a frame from a video if I don't want to display the video at all, hence I don't have any surface on the UI?

Can it also work somehow when the phone's screen is off?

**Comment by andrewlewis** [comment]
The information in #7167 will probably help. The non-`TextureView` techniques should work without an output view (with the screen off).

**Comment by danergo** [comment]
I'm trying to use those approaches, but ImageReader throws me an exception with a strange message:

```
// Create the player
exoplayer = new SimpleExoPlayer.Builder(ctx).setTrackSelector(new DefaultTrackSelector(ctx)).build();

// Create the virtual output
ImageReader ir = ImageReader.newInstance(1920, 1080, PixelFormat.RGBA_8888, 5);

imageReader.setOnImageAvailableListener(new ImageReader.OnImageAvailableListener() {
    @Override
    public void onImageAvailable(ImageReader imageReader) {
        imageReader.acquireLatestImage();
    }
}, null);

exoplayer.setVideoSurface(ir.getSurface());
exoplayer.prepare(...);
exoplayer.setPlayWhenReady(true);
```

imageReader.acquireLatestImage() throws an exception:

**java.lang.UnsupportedOperationException: The producer output buffer format 0x7fa30c06 doesn't match the ImageReader's configured buffer format 0x1.**
