### ISSUE TITLE
Unable to build ffmpeg extension

### ISSUE THREAD

**Issue by JiannaiJ** [google/ExoPlayer#8885]
ExoPlayer: 2.13.3
ndk: 21.4.7075529 / 21.0.6113669
ffmpeg: release 4.2
HOST_PLATFORM: darwin-x86_64

[config.log](https://github.com/google/ExoPlayer/files/6395975/config.log)

**Comment by kim-vde** [comment]
Could this be the same problem as in #8868? If not, could you please specify the value you set for the environment variables in the [build instructions](https://github.com/google/ExoPlayer/tree/r2.13.3/extensions/ffmpeg) and the error you get in the console?

**Comment by JiannaiJ** [comment]
@kim-vde  My problem is different from his. I gave the config.log information above.

**Comment by kim-vde** [comment]
I found 2 lines that could be the cause of the issue:
```
WARNING: /Users/jian/Library/Android/sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/darwin-x86_64/bin/x86_64-linux-android21-pkg-config not found, library detection may fail.
```
and
```
./configure: line 974: /Users/jian/Library/Android/sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/darwin-x86_64/bin/x86_64-linux-android21-g++: No such file or directory
```

Any idea what could be the problem @andrewlewis ?

**Comment by andrewlewis** [comment]
I agree those lines may point to the cause. Checking that those files exist seems like a good next step.
