### ISSUE TITLE
Last frame of previous video will be shown when switch video

### ISSUE THREAD

**Issue by Rulemylife** [google/ExoPlayer#8887]
1.ExoPlayer 2.13.3
I add midiaItems to SimpleExoPlayer. When seek to next window or the previous window ,the issue will occur.
By the way , When the next or the previous video is downloaded, the issue will be occured easily.

**Comment by kim-vde** [comment]
Hi! Please provide complete information as requested in the issue template. The issue template can
be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md).
If you're unable to share [bug reports](https://developer.android.com/studio/debug/bug-report) or
test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format
"Issue #1234" ("#1234" is replaced with your issue number). Please also update this issue to
indicate you've done this.
