### ISSUE TITLE
controlling applied rotation parameter in PlayerView.onVideoSizeChanged

### ISSUE THREAD

**Issue by asafbennatan** [google/ExoPlayer#8888]
I have a requirement to play a video rotated by 90 degrees and fill the entire screen with it .
I tried rotating the `PlayerView `itself but when I programmatically set its resize mode afterwards using :
        `PlayerView.setResizeMode(AspectRatioFrameLayout.RESIZE_MODE_FILL);`
the rotation is not applied.
looking at `PlayerView ` code I saw the following method:

```
public void onVideoSizeChanged(
        int width, int height, int unappliedRotationDegrees, float pixelWidthHeightRatio)
```
implemented by `ComponentListener` in `PlayerView` , if I manually change the library code and force unappliedRotationDegrees to 90 everything works perfectly.

my question is how this parameter is suppose to be set , is there any way to control it via the library exposed interfaces ?
Thanks.

**Comment by kim-vde** [comment]
The rotation degree is usually encoded in the media content itself (in the tkhd box for MP4 for example), so you could try to do that.

You could also try to implement one of the solutions described in #8099.

I don't think there is an easier way to do what you want.
