### ISSUE TITLE
how to solved this json exolist, please help me

### ISSUE THREAD

**Issue by xxxportxxx** [google/ExoPlayer#8895]
}
    ]  
  },
  {
    "name": "TEST CHANEL",
    "samples": [
	 {
        "name": "CITRA",
        "logo_uri": "https://divign0fdw3sv.cloudfront.net/Images/ChannelLogo/contenthub/60_144.png",
        "uri": "https://linear-playback.astro.com.my/linear-livewvdaf/2700/default_ott.mpd",
        "drm_scheme": "widevine",
        "drm_license_url": "https://sg-sg-sg.astro.com.my:9443/vgemultidrm/v1/widevine/license",
        "drm_key_request_properties": {
        "authorization": "Bearer",
        "bearerToken": "eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MjAwNTIzNzMsInN1YiI6IjgxNDgzMjM4IiwiYXVkIjoiaXZwLnNlc3Npb25ndWFyZCIsImV4cCI6MTYyMDA2MzE3Mywic2Vzc2lvbl9kYXRhIjp7InNlc3Npb24iOnsiY29tbXVuaXR5IjoiTWFsYXlzaWEgTGl2ZSIsImJ1c1VuaXRJZCI6IkFTVFJPIiwic2NvcGUiOiJicm93c2UgcGxheWJhY2siLCJ1cElkIjoiODE0ODMyMzhfMCIsImRldklkIjoiODE0ODMyMzguYTc2OGZkYzMtM2M5NS00YzViLWFkZmYtODcxNzA2OWM1MWJiIiwicmVnaW9uIjoiUE9TVFBBSUQiLCJjbWRjUmVnaW9uIjoiODAwMDAiLCJkZXZpY2VGZWF0dXJlcyI6WyJBQlIiLCJQRVJTT05BTC1DT01QVVRFUiIsIlVOTUFOQUdFRCIsIkRBU0giLCJXVi1EUk0iLCJTZWNvbmRTY3JlZW4iXSwiY21kY0RldmljZVR5cGUiOiJQQyIsImRldmljZVR5cGUiOiJDT01QQU5JT04iLCJ0ZW5hbnQiOiJrIiwic29sdXRpb25JZCI6ImsiLCJ0ZW5hbnRJZCI6IkFTVFJPIiwiZ3Vlc3RNb2RlIjpmYWxzZSwiaGhJZCI6IjgxNDgzMjM4In0sImhoSGFzaCI6MTcsImNvbW11bml0eSI6Ik1hbGF5c2lhIExpdmUifSwic2NvcGUiOiJicm93c2UgcGxheWJhY2siLCJ0b2tlbl90eXBlIjoiYWNjZXNzX3Rva2VuIiwic3NhX2p0aSI6ImJyb3dzZXIiLCJjbGllbnRfaWQiOiJicm93c2VyIiwianRpIjoiZDI0ZDU2YzAtYzM4MC00MGY0LTk0NWUtZjU4MmUwZmMyZmY0In0.2ohz2qp6CcCOaqclRCCtLRwTvYb-IYYbqN6eUmuDwzc",
        "WsbSession": "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1cElkIjoiODE0ODMyMzhfMCIsImhoSWQiOiI4MTQ4MzIzOCIsImlhdCI6MTYyMDA1NDI0OCwic2Vzc2lvbklkIjoiNDRiMDllNTEtMjVmMS00MTEwLWFmNDctMTZlNjBiMmYzODI5Iiwic2Vzc2lvbkRhdGEiOnsidXBJZCI6IjgxNDgzMjM4XzAiLCJoaElkIjoiODE0ODMyMzgiLCJyZWdpb24iOiJQT1NUUEFJRCIsInRlbmFudCI6ImsiLCJzZXNzaW9uSWQiOiI0NGIwOWU1MS0yNWYxLTQxMTAtYWY0Ny0xNmU2MGIyZjM4MjkiLCJkZXZpY2VUeXBlIjoiQ09NUEFOSU9OIiwiZ3Vlc3RNb2RlIjpmYWxzZSwiZGV2aWNlRmVhdHVyZXMiOlsiQUJSIiwiUEVSU09OQUwtQ09NUFVURVIiLCJVTk1BTkFHRUQiLCJEQVNIIiwiV1YtRFJNIiwiU2Vjb25kU2NyZWVuIl0sImJ1c1VuaXRIb3VzZWhvbGRJZCI6IjgxNDgzMjM4IiwiZGV2SWQiOiI4MTQ4MzIzOC5hNzY4ZmRjMy0zYzk1LTRjNWItYWRmZi04NzE3MDY5YzUxYmIiLCJjbWRjRGV2aWNlVHlwZSI6IlBDIiwiY29tbXVuaXR5IjoiTWFsYXlzaWEgTGl2ZSIsImNtZGNSZWdpb24iOiI4MDAwMCIsImJ1c1VuaXRJZCI6IkFTVFJPIn0sImd1ZXN0TW9kZSI6ZmFsc2UsImxhc3RVcGRhdGVJZCI6IjJlMWJiNzU3LTMyZTQtNDEwNC1hMjJhLWE1MzU2MDVlODM3NyIsImV4cCI6MTYyMDA1Nzg0OCwiZGV2SWQiOiI4MTQ4MzIzOC5hNzY4ZmRjMy0zYzk1LTRjNWItYWRmZi04NzE3MDY5YzUxYmIiLCJhdWQiOiJpdnAuc2Vzc2lvbmd1YXJkIiwiY29tbXVuaXR5IjoiTWFsYXlzaWEgTGl2ZSIsImhoSGFzaCI6MTQsImJ1c1VuaXRJZCI6IkFTVFJPIn0.Zv8N_CpxspkHCws3lfQdk079NH7UMyd7OPNM1lQKUDCIgHx89A1JyKYksox0bnDMWKeMOatOkBf6rTP2y2pHiQ",
         "cmty": "%7B%22community%22%3A%22Malaysia%20Live%22%2C%22hhHash%22%3A14%7D"
}

      }
    ]
  },
  {

}
                ]
              }
            }
          }
        },
        "_priority": "High",
        "_resourceType": "fetch",
        "cache": {},
        "connection": "36910",
        "request": {
          "method": "POST",
          "url": "https://sg-sg-sg.astro.com.my:9443/vgemultidrm/v1/widevine/license",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "Host",
              "value": "sg-sg-sg.astro.com.my:9443"
            },
            {
              "name": "Connection",
              "value": "keep-alive"
            },
            {
              "name": "Content-Length",
              "value": "6124"
            },
            {
              "name": "sec-ch-ua",
              "value": "\" Not A;Brand\";v=\"99\", \"Chromium\";v=\"90\", \"Google Chrome\";v=\"90\""
            },
            {
              "name": "authorization",
              "value": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MjAwNTIzNzMsInN1YiI6IjgxNDgzMjM4IiwiYXVkIjoiaXZwLnNlc3Npb25ndWFyZCIsImV4cCI6MTYyMDA2MzE3Mywic2Vzc2lvbl9kYXRhIjp7InNlc3Npb24iOnsiY29tbXVuaXR5IjoiTWFsYXlzaWEgTGl2ZSIsImJ1c1VuaXRJZCI6IkFTVFJPIiwic2NvcGUiOiJicm93c2UgcGxheWJhY2siLCJ1cElkIjoiODE0ODMyMzhfMCIsImRldklkIjoiODE0ODMyMzguYTc2OGZkYzMtM2M5NS00YzViLWFkZmYtODcxNzA2OWM1MWJiIiwicmVnaW9uIjoiUE9TVFBBSUQiLCJjbWRjUmVnaW9uIjoiODAwMDAiLCJkZXZpY2VGZWF0dXJlcyI6WyJBQlIiLCJQRVJTT05BTC1DT01QVVRFUiIsIlVOTUFOQUdFRCIsIkRBU0giLCJXVi1EUk0iLCJTZWNvbmRTY3JlZW4iXSwiY21kY0RldmljZVR5cGUiOiJQQyIsImRldmljZVR5cGUiOiJDT01QQU5JT04iLCJ0ZW5hbnQiOiJrIiwic29sdXRpb25JZCI6ImsiLCJ0ZW5hbnRJZCI6IkFTVFJPIiwiZ3Vlc3RNb2RlIjpmYWxzZSwiaGhJZCI6IjgxNDgzMjM4In0sImhoSGFzaCI6MTcsImNvbW11bml0eSI6Ik1hbGF5c2lhIExpdmUifSwic2NvcGUiOiJicm93c2UgcGxheWJhY2siLCJ0b2tlbl90eXBlIjoiYWNjZXNzX3Rva2VuIiwic3NhX2p0aSI6ImJyb3dzZXIiLCJjbGllbnRfaWQiOiJicm93c2VyIiwianRpIjoiZDI0ZDU2YzAtYzM4MC00MGY0LTk0NWUtZjU4MmUwZmMyZmY0In0.2ohz2qp6CcCOaqclRCCtLRwTvYb-IYYbqN6eUmuDwzc"
            },
            {
              "name": "cache-control",
              "value": "no-cache , no-store"
            },
            {
              "name": "accept-language",
              "value": "en"
            },
            {
              "name": "sec-ch-ua-mobile",
              "value": "?0"
            },
            {
              "name": "User-Agent",
              "value": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36"
            },
            {
              "name": "content-type",
              "value": "application/json"
            },
            {
              "name": "Accept",
              "value": "*/*"
            },
            {
              "name": "Origin",
              "value": "https://astrogo.astro.com.my"
            },
            {
              "name": "Sec-Fetch-Site",
              "value": "same-site"
            },
            {
              "name": "Sec-Fetch-Mode",
              "value": "cors"
            },
            {
              "name": "Sec-Fetch-Dest",
              "value": "empty"
            },
            {
              "name": "Referer",
              "value": "https://astrogo.astro.com.my/"
            },
            {
              "name": "Accept-Encoding",
              "value": "gzip, deflate, br"
            }
          ],
          "queryString": [],
          "cookies": [],
          "headersSize": 1663,
          "bodySize": 6124,
          "postData": {
            "mimeType": "application/json",
            "text": "{\"contentID\":\"2700\",\"contentType\":2,\"authorizationToken\":\"AAAAQAAAAKIAAABgAAAAGgAAAGEAAAACAAIAAABjAAAACADDTogcT5IgAAAAcAAAAHgCAQAAAAbd3/RirAJR2PSUyc6TtMtIPPpyaz7m8mLGw95nFnrqjGif6g4qiBi89cvPDJzz+6ZctZB81z5HBdIJReD4mCiLwFcI/Dq03avJGPGvCKoZ67O0j0ZTOmcYRnGcDe6T2xVb/sqDu+9hWU3aRAmLrC+KTBY=\",\"authorizationTokenType\":\"1\",\"licenseChallenge\":\"CAESvR8SQAo+CigIARIQhL+a1oSL59sg+dFoI97vEBoIY2lzY29uZHMiBDI3MDAqAlNEEAEaEF8tt0ueZqiuaJtJdx239t8YASDoocCEBjAVOLykxsgMQugeCgx3aWRldmluZS5jb20SEFFDT+KkTHY7zCyCai1u+acasBwX+qQKBVwb3zy35UMdbpNBcZzzstruqCrSmUR/p4ycpa8Al/JkLsA/GzFNJ8fm6Tq2ztvryWwR9BQG9N5jpauoXRMnk64RQbcwn8lyPT3wtZze1lF1jwzqxKClea+BZP11CFAA6+eCTouDLGqlJYyUolGF4y/kmCIPP+gvPMEKLW04iofxJO8U32h0XrDcW4qUQSizKMn2z2AXrOFUugO+QkxiXj8b9F+x1MD4hlXArKSkYRq8qTtKRZMcn5TVK8vyRN6Mq41Rq3B6M6+A5vmai2YECJL9lBQl9H1bmEv1ythYXRq/pwqReOx6MZYKlxVsgw8vaQjgnGJFXIE0Kl0aZdeM7OUjHrKvNDbif3o+AvXB4SQQcGvDljeDuKZPKpLjUO+d0vUWnKaRdgvX0BKWdlkbREpCQJVeopD52MSpyYfySyXGj2S5qsL4rKNAyOSVRZugnid0Hbb0F+CoSt8nqEpjpx5uc1ID7GjvnlVNR5Xi+4UxL24sEyWlcxT73yXADIypF4ZSqf1jq4Q+xMVW01pAHphed52y2MZNDnm8ne7NXsU9blTSSydD1o3vG6b0AhP9gHtJAB8dK1nq6P+Gmml/60ycrF2TBGqFKx4NdAIasCXmRY/dcnlgv552oAO16gl7wNk9DGkF0mF6LKz1SXQnLcHJw3lrhvKpjpq8OMZw2//BJx1UhNa+K6sfl+tj+NeA0/P8RIyEO93O91w+cLU8UEySjxvggr041RI4BYwPEIuf1/6+LokV9w4NwHgiaH5jkQCNc72qvDfV4RDy0l6GzEBUQ3SbDUav4VbNE8WI+dbQCapxRCxEYGc8viMy6TLnLsfE74aM3HMBsz/eM6SxCbg1me7qG+eV2anmagmWBf87nfDbQ8KONn+fF382iBbqDnTYgRmK9o7BHT2lvcFKvP0xA3lmPDk9/UqqW9PRLYW1Oz9jsrjIebvzOkizyVVaZzr5HbY0+S/dgZZhLEllwweOgXmMzN6OtLkpQppHzV8vudJwzYONX9ow8JHjEw0Ngx8BxGcUBPTg5tek5M3Y0Sbu4AV7D62MKdZiJBGwl8njzgsK17ruJHAwhj+1ZeN+9MdEX//WBcWQIU1qDViYKrw3AMmyIGpyrsyASvgNcuP8Hx/oDx9c+8tC+CRUr3GFXUAmadLQBqmzE4EzFIXQBrxLcU2OQD+culu5DJl3dOM4ZiNpHL/vltVrJu7f6kSLWNxfpgD1Qk7q4LthCEEnUoE3FFHqq3dvKfkei0qGibsXB7ujiZMEgG+cECBl4oXgZ5EwHrrewxUWi3fKIxeEajPBz76ul2hKW3A1LPjRZSFEc24QR0tynLOFah3JRImoMdGBCjjGMIsoTm+A1hQV5xVxn8ARINd/T/MPmbITmwuxxTINNOd50dBuiGaEtPmyeqNMugg2GUiL2YKXG3HUiGrpTeJkqs6GNyJ5k6npXp3GJQXShCYVtspZHZF0NTaqalvR2l1FVYFzMr7vcnGo/JpZO/AJRRqUN1hx4S3KuCmYP2kq57wk9m+9TjkjoH+reJ9g+V9LuTAPYw9kFvX1bUaEx7gBBouw1HtYfAHfe3QbWAA04Q1lipg+5WcNQRKMtryQ73Su+1xPyTqgiR2hAxWChYCRRkNLlaFQKwXjw+OesrGExSHAMKyzBu3luRFUa8+FJBMelQHij4JsyVC7KEr+Cr+0Yp3HBawqw/IbrqJwx2D0egp3kXEPZ/wr+zd4jnNyXy/CgAITzRY9aWY+EKa3TKAb2T2iP0QhbWUCBCHXB/xmfn6kaXytb7KQxILYMZn43x5wo4ZZdfQPvRh30j/zh47aSR07yaY+hPK3yMJG4SFmKchrOoqzmImYe3DFJKThOJHU/Mge3mNn1WyiL21BBHvm0s1a+60SQrc3Y2k/eY/WKB2FYltzaRZgCAOocG+IoiWbQXYNd90MxI6pZVonaOOqNNzrHzHaAQkYIYJdr7nfb7Ounf9CkAdU1Mb6QSV6OzazYpxeyDtNPuPYcYZ4Vzl7ad983thX1ZyDuU3lLNEZHHZMiOJZ+HohU8tx93Sv8jgIu0/xJdf+R04KLZ+OEiLFmc/ZMJAfK23vPZGjI1B0e5wfx3Na5gMMXos4kLVIoPTqaorn08yz12WWixAhUKUwEFNPOQJX5bK6zjoz8wcdM+h05KwA8DBemH+hW5wWWc00oaDlSifKktivF+snbbnS2o8J0J6fGhS+ZI7ImpCazeN8LckvAnKxwQOTOAqhj3Fz1tf73McanJWEVEpY3TA3NJzHkhDAgQ+pS9SebgtqNp83nAUSBO6WEjgHZQAyTq3mK1w1r5HSoaeS7zN7lnVPWijVqTGhC3yXlkxI5kgdk4pbjjDYEkcO3ksaI8G4xpjdgwBE/MzwBfn0JGfWUtBGSSOs9EyjSczapNQyRnjtLQeOlM9wWgj3NYYTax82LxxlU9B4mZcrLExXCsIsKfNRFodJHQZIq8Zg/V+t/v+bru/Aa+eUjfE1pELLCsu37oGzQ+rvQ4GBEZbK0P3/jpDIwNOfYOr8VOXzhaK08HqU6O5iKw2UsHc4a2OJaGiFx1RsDy47RcVe6B5QXUxCyUcw3TutUi3CRyP0ugDNt5Bh0UkYzYExFupZuCjfHp69kRz6YWW3gDtVwvXx2/vkrlCsB99TTWm6UNzo/+/KfjrPvq2DxhBr8AybOp5C5+N1764i1ttTEJp9MHuUtOLiYnoK5T865fhE+ysnQcokytohedeK/dalzAMqEOAlCr2vDaUi4e+r/sc+0rGmj3i/w4FUN16YCnem7ZGdAROlZED8wzQR8s4O2sfnMCsJLXrKH7ejnReZD4ygeTImNJ4idjEPOLezsFyDw43slbaKupOchGKEBc31xTdtrUhlWzEs0+Ih6TW/mRFtiwYN+BuwDaw6vNhhfy68bpt3UMKhjSaV7Dfed2vcLrzAgNgon/OV3au2Qg+q1fHnfe4Lg/GDliqJPgZ+9au/DKsFNBRtRWbRr1mI1L4uFKeHZ5S1AgJtUVABvjgJkie3hESIb1VSNq/A9uaCsZ6B0NGU+5TKlQTczMz92yVXeJhdL/XJnD7idy+g6oqJqVNyPdPvqxAsxf8uMiFfIHwSgbBk6Vl1WYbJOV1KqZh35P7eOUdE22L36WKOc1PBM4uvdccp3JgPNiwWOgksRwhji8zgIYW+xcORfLIER0nMn49Usz/TcCAeJiL9DGxQEPzp9HyggQr87lzJkI/bcZuMJ2+r9pyYEC6z0k9tPErnPvKlO7u5+zSLHNq9A9bGHBUBqgA6xqJsZYwmcrgu7l06h+c/Jcxjt8mqD4UXgJ5jN6zbvRmJLqyc8HWClOiDT562dskhClO7mPALrTOMOjbZy5hNJTDx1YrmPW9B2A+L7n4INgjfC0Tm4m+9unAmelEyD4YxaiBm5kXjfsvyF5Fcr244T9ZNswhzXz0UhZWXGib4jCkVUggOWNnVUjj1HtaUJIdAWona+LmheNczBpfgxZ/ZcxxBVbJ3MX66V0CJFtbSzbrNizqHmnj2Z7mb/kehU2V5ISxrpwqC4oOIEOwmXLfIGoE2gS8c0scSQR1lz7DASghUXu3ea3XmmymfK2LxTUdOg4QkDUsV3Df++bcFWqa6DlAYRHsoKg4yrEr0SmM5E2fK+TwptpPgZBsWJxnLEg810F1uNqxDfw8SLcvWvQVeU5iG8FjTc6zzpayLYud4AQPYsR2692hRClKxDigolXd+cO2AaH0Dqi159b9rzmKKk3gpTG8gj5yoa3WvFsZMMahKvqz1a7DmY0g6oZGmugZ4M/0ODYIC+eU03x4ofzHiLKZViO6cgN3f1f3ggH+BBgZZ/hLHi4H0/mfh8rpG5cuuT0YJY8fAwx2uko+6a/rPOkaodp6QKGetRZYSJkliZ4/wlAHZgZl8iXG/+v14KJeRKpMUNEvPynqUnICUPM2bnVd2VwlEz0oEt2NrIHQVL4B/LdXaS9/zs1ddFblO7sz4KOQGRee8LkgqqH9Bf6MuqHOrgi1nPzsG9m2BF8eU3cGpdtQ7aH5X4bjr39O3/HROGwkupggtxaPZUz6SoVM55HIFoGw+2UlPau2VWMiDuLZfPE9+j1JrPwFmpKtGbAzEAIYkUlZa3PBgVm26Imldr4+rxkvfotYcZJxzoNARFFSCgn+JPHPeO4bXPL8PCvtE24QajHC7J3YUlC/5YvJgQpMmPcbcKI/AJDrvTOydsPI/Kk/lFNDZm5rKfzNX3d4GbIZ2epBg8G2hHqmx4m7Vg76n7u1aEnogYhZUgrymOatggA8Y8ebwu1Zb4Q0RP3t/2J0xE838e4sXl0WrVGFGeO/GRROonzvIf8bUJBJopRI7hkBvWpcv0xBuOvq34ClmeBoRY80/DRSV1SYSaymtTs/hK5wkpiV92+K0i/ulxqRMz0xvY7I7GeBeq2H/J4RhqgTW3F4QL4IzQKsmQPUffAZbM4hTTVR0tfDQ2pkR9Yzit3zzNTyaMSxwpXfAQhbYsCbrTDtz8fIQxHUCGDSne62oDTAjjTKOeJbfIYzjOavH+UcnVKPjWdbF6PWOk6UTkTyvcXtR7lGqb3IaBOFjH1CyOoruUCDP9QAKxRBmaW9aQD4lu5prMCfOajpu5CFfl8LZYgMBM8GPYAjFugoKnhKfszCxHXHCfLF2lLwLbgatRuHG1KHfLxD/An3EEi8TJxqQ/IAClhFjGSlO+I0LQ8Ged8JoMpnztN34R3TDXelRhADHVfXkM3glY1J78p6f8ei3haM3cJae+RuDPwHVBDgIuEZGpHqDKYMZirz1PJq7jWQommzpUcA+N4bvjC2XLn/redzKjO4AgmBq4CIQHg273IJQM+Py/30oZLiZsSqAAi4iqG7jDURlXED/GWchTi7StG3HBpfYS03ZurCAI7oZYFrCC5TGVHl/fxOlzj/H4CBcTRTcD32oXrueM0Xz0zKvdrhFv7nhU5s3/LBqpq9PvBqSySuQUhFOgZCAoFAvad5ivVpcCOAo8WaKc9gU5rh5ptxxudEBeLJ6TK5qXt+7NU96fGeOYLJiPQw+lc2peX5SOWVJzGJgsWyn02jNkcEX2XXIk5IDYINzP3dr4E1rUoEJATs1cjr1th8sfkUWipQv3P5oOn1xJXhELPC3Iy91qbBVoIt9cqALRFFuRsbtyJ/tZLWWZ8ZGBt/kfd/IxDUcNnd0C5CSOCluWOn2YSYagAKZPXd3orSbhZahVFd5Kb9weHppOg2nPcBucyTtK9puqIzOHDzn0vB1q7DveTSwr+Mr5SW+wu9PrjSBjYLvxSSah6gU+5ciDYYDPIUJdwZKQP3nuTx7z+hRE8SomtUBucucAPFaeaGNAI5EcKEvPmlqlgK8gyUydu1wMGcU1Q6msxTJ4SgGwIUmd3GEIuMLXB67WTSRAcHvKXI0LfwN0F9M/DVr2sAxZ2glghEfJSyaqbFW8TRY0wOcZjySRw1Gq+w45A3DAgItvcbzGHyaiuY7kErJBzX2aMPCsqRgatMOjeq1kJcf7m2PGG+ajKsPlzXLkME+bcHu/lhxYtFtdaW7ShQAAAABAAAAFAAFABDJEZI8/aJ//A==\",\"playbackSessionCookie\":null}"
          }
        },
        "response": {
          "status": 200,
          "statusText": "OK",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "Date",
              "value": "Mon, 03 May 2021 15:04:08 GMT"
            },
            {
              "name": "Content-Type",
              "value": "application/json; charset=utf-8"
            },
            {
              "name": "Content-Length",
              "value": "2510"
            },
            {
              "name": "Connection",
              "value": "keep-alive"
            },
            {
              "name": "FLOW_CONTEXT",
              "value": "609010E86E95A81F0E0036FC"
            },
            {
              "name": "Set-Cookie",
              "value": "WsbSession=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1cElkIjoiODE0ODMyMzhfMCIsImhoSWQiOiI4MTQ4MzIzOCIsImlhdCI6MTYyMDA1NDI0OCwic2Vzc2lvbklkIjoiNDRiMDllNTEtMjVmMS00MTEwLWFmNDctMTZlNjBiMmYzODI5Iiwic2Vzc2lvbkRhdGEiOnsidXBJZCI6IjgxNDgzMjM4XzAiLCJoaElkIjoiODE0ODMyMzgiLCJyZWdpb24iOiJQT1NUUEFJRCIsInRlbmFudCI6ImsiLCJzZXNzaW9uSWQiOiI0NGIwOWU1MS0yNWYxLTQxMTAtYWY0Ny0xNmU2MGIyZjM4MjkiLCJkZXZpY2VUeXBlIjoiQ09NUEFOSU9OIiwiZ3Vlc3RNb2RlIjpmYWxzZSwiZGV2aWNlRmVhdHVyZXMiOlsiQUJSIiwiUEVSU09OQUwtQ09NUFVURVIiLCJVTk1BTkFHRUQiLCJEQVNIIiwiV1YtRFJNIiwiU2Vjb25kU2NyZWVuIl0sImJ1c1VuaXRIb3VzZWhvbGRJZCI6IjgxNDgzMjM4IiwiZGV2SWQiOiI4MTQ4MzIzOC5hNzY4ZmRjMy0zYzk1LTRjNWItYWRmZi04NzE3MDY5YzUxYmIiLCJjbWRjRGV2aWNlVHlwZSI6IlBDIiwiY29tbXVuaXR5IjoiTWFsYXlzaWEgTGl2ZSIsImNtZGNSZWdpb24iOiI4MDAwMCIsImJ1c1VuaXRJZCI6IkFTVFJPIn0sImd1ZXN0TW9kZSI6ZmFsc2UsImxhc3RVcGRhdGVJZCI6IjJlMWJiNzU3LTMyZTQtNDEwNC1hMjJhLWE1MzU2MDVlODM3NyIsImV4cCI6MTYyMDA1Nzg0OCwiZGV2SWQiOiI4MTQ4MzIzOC5hNzY4ZmRjMy0zYzk1LTRjNWItYWRmZi04NzE3MDY5YzUxYmIiLCJhdWQiOiJpdnAuc2Vzc2lvbmd1YXJkIiwiY29tbXVuaXR5IjoiTWFsYXlzaWEgTGl2ZSIsImhoSGFzaCI6MTQsImJ1c1VuaXRJZCI6IkFTVFJPIn0.Zv8N_CpxspkHCws3lfQdk079NH7UMyd7OPNM1lQKUDCIgHx89A1JyKYksox0bnDMWKeMOatOkBf6rTP2y2pHiQ; Path=/; HttpOnly; SameSite=None; Secure; Expires=Mon, 03-May-21 17:04:08 GMT; Max-Age=7200"
            },
            {
              "name": "Set-Cookie",
              "value": "cmty=%7B%22community%22%3A%22Malaysia%20Live%22%2C%22hhHash%22%3A14%7D; Path=/; HttpOnly; SameSite=None; Secure; Expires=Wed, 02-Jun-21 15:04:08 GMT; Max-Age=2592000"
            },
            {
              "name": "x-powered-by",
              "value": "Express"
            },
            {
              "name": "access-control-allow-origin",
              "value": "https://astrogo.astro.com.my"
            },
            {
              "name": "x-mdrm-data-response",
              "value": "null"
            },
            {
              "name": "ETag",
              "value": "W/\"9ce-lLF6Fv2zZdKP5cFjj0+Ps9/vEq8\""
            },
            {
              "name": "Access-Control-Allow-Credentials",
              "value": "true"
            },
            {
              "name": "Access-Control-Allow-Methods",
              "value": "GET, POST, PUT, DELETE, OPTIONS, PATCH"
            },
            {
              "name": "Access-Control-Allow-Headers",
              "value": "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization,Source-Type,Source-ID,FLOW_CONTEXT,sky-email,sky-token,sky-ccode,sky-deviceid,sky-devinfo,sky-locale,sky-version,Date,SOAPAction,X-Response-Lang"
            },
            {
              "name": "Access-Control-Expose-Headers",
              "value": "FLOW_CONTEXT,WWW-Authenticate"
            },
            {
              "name": "Strict-Transport-Security",
              "value": "max-age=31536000; includeSubDomains"
            }
          ],
          "cookies": [
            {
              "name": "WsbSession",
              "value": "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1cElkIjoiODE0ODMyMzhfMCIsImhoSWQiOiI4MTQ4MzIzOCIsImlhdCI6MTYyMDA1NDI0OCwic2Vzc2lvbklkIjoiNDRiMDllNTEtMjVmMS00MTEwLWFmNDctMTZlNjBiMmYzODI5Iiwic2Vzc2lvbkRhdGEiOnsidXBJZCI6IjgxNDgzMjM4XzAiLCJoaElkIjoiODE0ODMyMzgiLCJyZWdpb24iOiJQT1NUUEFJRCIsInRlbmFudCI6ImsiLCJzZXNzaW9uSWQiOiI0NGIwOWU1MS0yNWYxLTQxMTAtYWY0Ny0xNmU2MGIyZjM4MjkiLCJkZXZpY2VUeXBlIjoiQ09NUEFOSU9OIiwiZ3Vlc3RNb2RlIjpmYWxzZSwiZGV2aWNlRmVhdHVyZXMiOlsiQUJSIiwiUEVSU09OQUwtQ09NUFVURVIiLCJVTk1BTkFHRUQiLCJEQVNIIiwiV1YtRFJNIiwiU2Vjb25kU2NyZWVuIl0sImJ1c1VuaXRIb3VzZWhvbGRJZCI6IjgxNDgzMjM4IiwiZGV2SWQiOiI4MTQ4MzIzOC5hNzY4ZmRjMy0zYzk1LTRjNWItYWRmZi04NzE3MDY5YzUxYmIiLCJjbWRjRGV2aWNlVHlwZSI6IlBDIiwiY29tbXVuaXR5IjoiTWFsYXlzaWEgTGl2ZSIsImNtZGNSZWdpb24iOiI4MDAwMCIsImJ1c1VuaXRJZCI6IkFTVFJPIn0sImd1ZXN0TW9kZSI6ZmFsc2UsImxhc3RVcGRhdGVJZCI6IjJlMWJiNzU3LTMyZTQtNDEwNC1hMjJhLWE1MzU2MDVlODM3NyIsImV4cCI6MTYyMDA1Nzg0OCwiZGV2SWQiOiI4MTQ4MzIzOC5hNzY4ZmRjMy0zYzk1LTRjNWItYWRmZi04NzE3MDY5YzUxYmIiLCJhdWQiOiJpdnAuc2Vzc2lvbmd1YXJkIiwiY29tbXVuaXR5IjoiTWFsYXlzaWEgTGl2ZSIsImhoSGFzaCI6MTQsImJ1c1VuaXRJZCI6IkFTVFJPIn0.Zv8N_CpxspkHCws3lfQdk079NH7UMyd7OPNM1lQKUDCIgHx89A1JyKYksox0bnDMWKeMOatOkBf6rTP2y2pHiQ",
              "path": "/",
              "domain": "sg-sg-sg.astro.com.my",
              "expires": "2021-05-03T17:04:07.977Z",
              "httpOnly": true,
              "secure": true,
              "sameSite": "None"
            },
            {
              "name": "cmty",
              "value": "%7B%22community%22%3A%22Malaysia%20Live%22%2C%22hhHash%22%3A14%7D",
              "path": "/",
              "domain": "sg-sg-sg.astro.com.my",
              "expires": "2021-06-02T15:04:07.977Z",
              "httpOnly": true,
              "secure": true,
              "sameSite": "None"
            }
          ],
          "content": {
            "size": 2510,
            "mimeType": "application/json",
            "compression": 0
          },
          "redirectURL": "",
          "headersSize": 2338,
          "bodySize": 2510,
          "_transferSize": 4848,
          "_error": null
        },
        "serverIPAddress": "18.140.144.126",
        "startedDateTime": "2021-05-03T15:04:07.976Z",
        "time": 160.43599999829894,
        "timings": {
          "blocked": 3.1199999969708734,
          "dns": -1,
          "ssl": -1,
          "connect": -1,
          "send": 0.17900000000000005,
          "wait": 120.86899999785376,
          "receive": 36.2680000034743,
          "_blocked_queueing": 1.5599999969708733,
          "_blocked_proxy": 0.17599999999999993
        }
      },
      {
        "_initiator": {

**Comment by icbaker** [comment]
This looks very similar to https://github.com/google/ExoPlayer/issues/8856 where not enough information was provided.

Please provide complete information as requested in the question template. The template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/question.md).

Unfortunately we can't answer unclear questions or those with insufficient information.
