### ISSUE TITLE
Applying time stretched media duration into player

### ISSUE THREAD

**Issue by devingryu** [google/ExoPlayer#8896]
SonicAudioProcessor has time stretching ability, but it doesn't take into account media duration of the player.
For example, when media of duration 2:00 is shrunk by 0.7 with AudioProcessor, then shown audio duration should be 1:24 or should be played faster. But it doesn't work like that even though music playes well.
I know that player.setPlaybackParameters() does the thing, but I want to know how to do same thing with AudioProcessor.

Thanks in advance.

**Comment by christosts** [comment]
Can you please explain in more detail your use-case? 

> when media of duration 2:00 is shrunk by 0.7 with AudioProcessor, then shown audio duration should be 1:24

The position and duration returned by the player are based on the media regardless of playback speed or other processing. For example, playing a 2:00 content faster will not change the duration, but the player will advance faster that the real time. 
If the question is how to display duration/position to the UI in terms of real time, then the app has to adjust duration/position based on the playback speed that the app itself has set through `player.setPlaybackParameters()`. Please see #7366 for a similar discussion.

> I know that player.setPlaybackParameters() does the thing, but I want to know how to do same thing with AudioProcessor.

Does this mean you want to effectively change the playback speed directly through AudioProcessor? As I said above, changing the speed will change what the player returns for duration/position.

**Comment by devingryu** [comment]
What I meant was even though I change the speed through SonicAudioProcessor, the player dosen't advance faster. Setting playbackparameter while using Sonic makes double-effect on speed(because both Sonic and player changes speed)
So, I was wondering if there is a way to make player advance faster when using SonicAudioProcessor.

**Comment by christosts** [comment]
I don't think you can make the player advance faster going directly through SonicAudioProcessor. You have to set the playback speed on the player which will then configure SonicAudioProcessor accordingly.

@krocard can you please verify the above? Maybe there is case of achieving what @devingryu describes that I'm not aware of.

Thanks

**Comment by krocard** [comment]
I'm unsure to understand the question. `Player.setPlaybackSpeed` (or equivalently `Player.setPlaybackParameters`), will play the media faster or slower than the media normal rate.

This is achieved internally by ExoPlayer for audio by using the platform's `AudioTrack.setPlaybackParams` or equivalently (depending on the `Player` configuration and the API level) by using the `SonicAudioProcessor`.

The media duration as reported by `Player.getDuration` is not affected as it is considered the duration of the media, independently of how it is played. 

> For example, when media of duration 2:00 is shrunk by 0.7 with AudioProcessor, then shown audio duration should be 1:24 or should be played faster. But it doesn't work like that even though music playes well.

I'm not sure to understand your question. Could you please explain what you expect and how it is different to what you observe?

**Comment by devingryu** [comment]
Ok, then now I want to know if changing the player's playback speed is available while using custom AudioProcessor to modify audio speed.
I'm pretty sure that setPlaybackParameters doesn't modify audio with attached AudioProcessor, because audio ticks a lot when using setPlaybackParameters(unlike when I use custom AudioProcessor).

**Comment by andrewlewis** [comment]
> Ok, then now I want to know if changing the player's playback speed is available while using custom AudioProcessor to modify audio speed.

You can pass a custom [`AudioProcessorChain`](https://github.com/google/ExoPlayer/blob/aeb306a164911aa1491b46c2db4da0d329c83c65/library/core/src/main/java/com/google/android/exoplayer2/audio/DefaultAudioSink.java#L86) when constructing `DefaultAudioSink` to provide a speed scaling audio processor and at the same time override how the media position is calculated. See the `DefaultAudioProcessorChain` implementation in that class as an example.

**Comment by devingryu** [comment]
Yes, I managed to modify audio by AudioProcessorChain with my AudioProcessor, and it plays well.
But what I meant was, even though I change speed with setSpeed() in processor(just as same as one in SonicAudioProcessor), the time in player's view doesn't advance faster.
There would be no problem if I use setPlayBackParameter (since it makes both audio and time faster) but when I use my AudioProcessor, time management is not available.

It would be great if there is a method that sets playbackspeed without modifying audio, or setPlayBackSpeed which accepts custom AudioProcessor.

**Comment by krocard** [comment]
Is your custom AudioProcessor correctly reporting the speed up/down media duration. Here is how The `SonicAudioProcessor` does it: https://github.com/google/ExoPlayer/blob/aeb306a164911aa1491b46c2db4da0d329c83c65/library/core/src/main/java/com/google/android/exoplayer2/audio/SonicAudioProcessor.java#L138

**Comment by andrewlewis** [comment]
> But what I meant was, even though I change speed with setSpeed() in processor(just as same as one in SonicAudioProcessor), the time in player's view doesn't advance faster.

Have you overridden `AudioProcessorChain.getMediaDuration` to reflect the speedup you are applying in your custom audio processor? If you do that, the player's position should reflect the scaling.

> There would be no problem if I use setPlayBackParameter (since it makes both audio and time faster) but when I use my AudioProcessor, time management is not available.

I'm not sure why you'd want to avoid using `setPlaybackParameters` -- that is the right way to update the player speed, and it doesn't have to be tied to the default implementation via `SonicAudioProcessor` as you can completely replace the implementation (both for speedup and the actual scaling calculation) via your custom `AudioProcessorChain`. It sounds a bit like you may be trying to have video go at a different speed from the player position?

**Comment by devingryu** [comment]
>Have you overridden AudioProcessorChain.getMediaDuration to reflect the speedup you are applying in your custom audio processor? If you do that, the player's position should reflect the scaling.

I think I didn't override AudioProcessorChain.getMediaDuration. I'll try right now. Thanks!
Besides, I wonder how to give DefaultAudioSink as argument in SimpleExoPlayer.Builder(). I couldn't find anything like setRenderFactory() or setAudioSink(). I'm still using deprecated method since I don't know how.

**Comment by devingryu** [comment]
> Have you overridden `AudioProcessorChain.getMediaDuration` to reflect the speedup you are applying in your custom audio processor? If you do that, the player's position should reflect the scaling.

Problem Solved by overriding `AudioProcessorChain.getMediaDuration` and using `setPlaybackParameters`!
I got to know that I can use `SimpleExoPlayer.Builder(context,renderersfactory)` to use custom RenderersFactory, so my problem is all solved.

Thank you all for answering this question!
