### ISSUE TITLE
Exoplayer cannot play this link ，This link jumps back to another address, but the player does not follow the jump

### ISSUE THREAD

**Issue by zhoushsong** [google/ExoPlayer#8899]
http://qtv.panel.tm/script/vod4.php?v=IND_Roohi_movie.mp4&item=Movie

**Comment by christosts** [comment]
When I try the url above, it redirects to `https://ww.google.com` which is not a media file.

Aside: if you are using the DefaultHttpDataSource, you need to allow [cross protocol redirects](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/upstream/DefaultHttpDataSource.Factory.html#setAllowCrossProtocolRedirects-boolean-). By default, the demo app will try to use the Cronet data source which supports redirects.
