### ISSUE TITLE
How to add devices to codecNeedsSetOutputSurfaceWorkaround?

### ISSUE THREAD

**Issue by AtteR** [google/ExoPlayer#8902]
Hello,

Been testing devices that get sometimes black screen and the issue could be fixed with adding the device to `codecNeedsSetOutputSurfaceWorkaround`. The list is missing my Huawei device, so it I would like to test if this helps. I could not find any examples how to implement this. 

I tried by using the Exoplayer.build() instead of SimpleExoplayer.build() but the screen is black, probably because I am only passing my own MediaCodecVideoRenderer to it? I assume it should also need to things than only this renderer.

`mPlayer = new SimpleExoPlayer.Builder(getContext()).build();`

This is the way I am currently initializing player, it is very simple and this is enough for other cases, except for the black screen issue.

Do I need to create each renderer separately or is there any examples how to do this?

Thanks!

**Comment by christosts** [comment]
The description has two questions: 
1. Is it possible to extend the devices considered in codecNeedsSetOutputSurfaceWorkaround
2. How to pass a custom video renderer to the player (black screen issue)

**Issue** 1.
You can extend the behavior of codecNeedsSetOutputSurfaceWorkaround by subclassing MediaCodecVideoRenderer and override `codecNeedsSetOutputSurfaceWorkaround`
https://github.com/google/ExoPlayer/blob/0ba317b1337eaa789f05dd6c5241246478a3d1e5/library/core/src/main/java/com/google/android/exoplayer2/video/MediaCodecVideoRenderer.java#L1565

You mentioned

> I am only passing my own MediaCodecVideoRenderer to it

so I understand you have figured how to extend codecNeedsSetOutputSurfaceWorkaround already, right?

**Issue 2.**

In your code snippet how to create the player, you do not pass your custom renderer. Maybe it was mistyped in the description, but just to be sure, you need to create the player with

```
RenderersFactory renderersFactory = ... // your custom renderers factory
mPlayer = new SimpleExoPlayer.Builder(getContext(), renderersFactory).build();
```

Also, make sure to use a constructor of MediaCodecVideoRenderer that sets the event handler and video event listener, for example this one:

https://github.com/google/ExoPlayer/blob/0ba317b1337eaa789f05dd6c5241246478a3d1e5/library/core/src/main/java/com/google/android/exoplayer2/video/MediaCodecVideoRenderer.java#L193-L199

The RenderersFactory.createRenderers() passes an EventHandler and VideoRendererEventListener in the argument list, so you can forward those to your renderer.

I tested it with the demo app. You can use only a MediaCodecVideoRenderer and it will only display video, but you need to pass the two parameters I mentioned above. I was able to tweak the demo app as follows:

```
RenderersFactory renderersFactory = (eventHandler, videoRendererEventListener, audioRendererEventListener, textRendererOutput, metadataRendererOutput) -> new Renderer[]{
          new MediaCodecVideoRenderer(
              context,
              MediaCodecSelector.DEFAULT,
              500,
              false,
              eventHandler,
              videoRendererEventListener,
              50)};
player  = new SimpleExoPlayer.Builder(getContext(), renderersFactory).build();
```

Please let me know if the above worked so I can close this issue.

Thanks.

**Comment by AtteR** [comment]
Hi,

Thank you so much for this! This has fixed our issue with this device. There were also other improvements which fixed this issue somewhat, but this completely fixed it.

Here is the code we use for override:

```
        @Override
        protected boolean codecNeedsSetOutputSurfaceWorkaround(String name) {
            if ( name.equals("OMX.IMG.MSVDX.Decoder.AVC")) {
                return true;
            } else {
                return super.codecNeedsSetOutputSurfaceWorkaround(name);
            }
        }
```

Answered and thank you!
