### ISSUE TITLE
how to download video one by one of a series

### ISSUE THREAD

**Issue by NG-Gaurav** [google/ExoPlayer#8909]
Actually, we have a series which have 10 episodes. so we want to download all episodes one by one. means firstly episode 1 download after that other start episode 2 and at last episode 10 download.

**Comment by christosts** [comment]
Have you considered setting a listener on the DownloadManager, and when a download is completed, your listener will queue the next download?

Relevant documentation: https://exoplayer.dev/downloading-media.html#listening-to-downloads

**Comment by NG-Gaurav** [comment]
yes, We are using listener but we are adding 10 videos in the queue one by one. so we want just DownloadManager to start picking the first video than the second and so on. but DownloadManager picks randomly and starts downloading.

**Comment by dzungvu** [comment]
Have you tried to set maxParallelDownloads for DownloadManager, then simply call download for each media source using DownloadService
```kotlin
DownloadService.sendAddDownload(
    context,
    MyDownloadService.class,
    downloadRequest,
    /* foreground= */ false)
```
I've tested it and it works well

**Comment by NG-Gaurav** [comment]
yes maxParallelDownloads = 10 my problem is the download manager picks a random video and starts downloading. so I just want to download manager should pick the first video and starts downloading then pick the second from the queue.

**Comment by dzungvu** [comment]
> yes maxParallelDownloads = 10 my problem is the download manager picks a random video and starts downloading. so I just want to download manager should pick the first video and starts downloading then pick the second from the queue.

So, you should set maxParallelDownloads = 1. Because what you want is to download only 1 video at a time. Exo will automatically download the next one if the current one is finish or pause. With maxParallelDownloads  = 10, then Exoplayer will download 10 videos in parallel.

**Comment by christosts** [comment]
@NG-Gaurav have you tried the recommendation above?
