### ISSUE TITLE
Rendering to ImageReader: always crashing

### ISSUE THREAD

**Issue by danergo** [google/ExoPlayer#8910]
Guys, I really want to extract JPG images from a (live)stream (which is anyway perfectly playable).

I need extractions also when phone is idle or its screen is turned off.

I know https://github.com/google/ExoPlayer/issues/7167, and I'm trying to use the "ImageReader" approach.

However if I use some RGBA_8888 pixelformat, it crashes, as Exo's output format differs from RGBA_8888. (It's YCbCr_420_SP I think).

If I change ImageReader's format to something like NV21, or this YCbCr_420_SP (which is anyway deprecated), I got another crash: NV21 is not supported.

So, my question is: isn't there any documentation on how can I get a single still image from the stream with ExoPlayer? All things are mentioned in the linked issue are helpful, but not complete or up-2-date.

Please help me!

**Comment by danergo** [comment]
Maybe I can somehow ask Exo to change it's decoder output to RGBA_8888?

**Comment by andrewlewis** [comment]
I'm afraid I can't give you a simple answer that will definitely work, but here are some more pointers in addition to #7167 which you've seen already:
- If you can use a min SDK version of 24 or above, please try using https://developer.android.com/reference/android/view/PixelCopy instead. There is an example of using this in the CTS `DecodeAccuracyTest` ([here](https://cs.android.com/android/platform/superproject/+/master:cts/tests/tests/media/src/android/media/cts/DecodeAccuracyTestBase.java;l=1389;drc=master) is part of the implementation as a starting point). My understanding is that if you pixel copy from an off-screen `SurfaceTexture` to an RGB bitmap you should get any required color conversion automatically.
- If not, I would try looking at what color formats are supported in the `CodecCapabilities` (see the [MediaCodec documentation](https://developer.android.com/reference/android/media/MediaCodec#raw-video-buffers) on color formats), which may differ for software vs hardware codecs. If you find a decoder where RGB is in the list I suspect it's possible to request this via `MediaFormat.KEY_COLOR_FORMAT` on the decoder configuration `MediaFormat`.

**Comment by danergo** [comment]
Perfect, thank you. My minSDK is lower unfortunately, and I still would like to stick with it (22). I saw an article which specifically requests 

`mediaFormat.setInteger(MediaFormat.KEY_COLOR_FORMAT, MediaCodecInfo.CodecCapabilities.COLOR_FormatYUV420Flexible);`

Which might be good for me. How can I request this with ExoPlayer? I'm going to create a very basic and minimalistic example and share here for later comers to learn. It will load a video and create JPGs peridically even with screen turned off.

**Comment by andrewlewis** [comment]
> How can I request this with ExoPlayer?

You can subclass `MediaCodecVideoRenderer` and override `getMediaFormat` to call the superclass implementation then include the line pasted above to set the color format.

To use your custom video renderer, you can override `DefaultRenderersFactory.buildVideoRenderers` and pass your custom renderers factory when building `SimpleExoPlayer`, for example.
