### ISSUE TITLE
exoplayer 2.13.3

### ISSUE THREAD

**Issue by ramkumar19** [google/ExoPlayer#8917]
exoplayer 2.13.3 factory code not working please  bandwidth meter code error .please full code for exoplayer 2.13.3 m3u8 hls link play please separate the code becase of i totally confused exoplayer code for android 11  exoplayer video play

**Comment by Samrobbo** [comment]
Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md). If you're unable to share bug reports or test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Please also update this issue to indicate you’ve done this.
