### ISSUE TITLE
How to play multiple mp4 files part way through a hls stream at different times?

### ISSUE THREAD

**Issue by sajjadshahbazi** [google/ExoPlayer#8919]
I have a hls stream that I want to play multiple mp4 files at different times.
for example, I want to play an mp4 file at The beginning of the movie Or Play an mp4 file After 10 minutes of watching the Film.
I don't want to use ImaAdsLoader, ...
Do in the new version of Exoplayer is posible ?

please guide me about this issue

**Comment by christosts** [comment]
I'm afraid I can't fully follow the question because you mention both HLS streams and MP4 files. 
- do you have access to multiple MP4 files directly?
- do you have access to multiple HLS streams?
- is it a single HLS stream that plays all these files?

> for example, I want to play an mp4 file at The beginning of the movie Or Play an mp4 file After 10 minutes of watching the Film.

When you add a MediaItem to the player, you can set `clipping properties` to say at want point to start and stop playback for each MediaItem. Please see the `setClipXXX` methods on [MediaItem.Builder](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/MediaItem.Builder.html). This way you can set the player to start at the beginning or at 10 minutes.

If the above did not answer your question, please provide some clarifications on what exactly you are trying to achieve and what exactly is the input to the player. Thanks

**Comment by sajjadshahbazi** [comment]
I have a number of http mp4 links that I want to play these mp4 files at the beginning of a single HLS stream.

**Comment by christosts** [comment]
Ok, so my understanding is you have an HLS stream and additional links to MP4 files that you want to play either in the beginning or in any point while playing the HLS stream. One way to achieve this is to load each playback "piece" as a separate media item and set the [clipping properties](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/MediaItem.Builder.html) for each media item accordingly. For example, if you want to play

- an mp4 file
- the HLS stream from 0 to 10 minutes
- another mp4 file
- the HLS stream from minute 10 onwards

then you would add 4 media items to the player and set the clipping properties of the 2nd and 4th item. In the demo app, there's an example already who to achieve this [here](https://github.com/google/ExoPlayer/blob/r2.14.0/demos/main/src/main/assets/media.exolist.json#L432-L447). In terms of code:

```
player.setMediaItems(Arrays.asList(
        MediaItem.fromUri("..mp4"), // 1st mp4 file
        new MediaItem.Builder().setUri("...").setClipEndPositionMs(ten_minutes).build(), // HLS stream 0-10 minutes
        MediaItem.fromUri("...mp4"), // 2nd mp4 file
        new MediaItem.Builder().setUri("...").setClipStartPositionMs(ten_minutes).build() // HLS stream 10-end of stream
    ));
```

Note that with this solution your HLS stream will appear as two separate media items, first with a duration of 10 minutes, and then with a duration of `stream duration - 10 minutes`. 

Please let me know if that answered your question.

**Comment by sajjadshahbazi** [comment]
i have single Hls stream that has a MediaSource for subtitle.
Is the subtitle displayed over mp4?

**Comment by icbaker** [comment]
The subtitles shouldn't show over the MP4, no. The video, audio, text, etc of the HLS will all 'pause' at the `clipEndPositionMs` of the first item and resume again at the `clipStartPosition` of the following item.

(there was a bug where subtitles would keep being displayed in this case, it's fixed from 2.13.3 upwards: https://github.com/google/ExoPlayer/issues/8456)

**Comment by sajjadshahbazi** [comment]
thank you

**Comment by sajjadshahbazi** [comment]
now i firing events at specified playback positions over single Hls stream, do may with add mp4 file have problem ?
do may firing event at specified playback positions over play mp4 ?

**Comment by sajjadshahbazi** [comment]
can i skip media item of mp4 file when watch ?

**Comment by ojw28** [comment]
Regarding the two questions above, I suggest you try for yourself. E.g., the `Player` interface defines various seeking methods, including ones that you should be able to use to seek ahead to the next portion of HLS when you're currently playing one of the MP4 files (`seekToNextWindow` is probably the method that you want, or `next` if on an older ExoPlayer release).
