### ISSUE TITLE
How can I detect HDCP (High-bandwidth Digital Content Protection) compliance?

### ISSUE THREAD

**Issue by jitendratiwari** [google/ExoPlayer#8923]
In Exoplayer is there any method which can give callback to  detect the HDCP compliance

**Comment by Samrobbo** [comment]
@icbaker can you look into this? I couldn't find anything obvious from a cursory look.

**Comment by icbaker** [comment]
I don't think you need ExoPlayer to do this - I believe you can do it directly with the Android `MediaDrm` API (on API 28+):

```
try (MediaDrm mediaDrm = new MediaDrm()) {
  mediaDrm.getConnectedHdcpLevel()
}
```

https://developer.android.com/reference/android/media/MediaDrm#getConnectedHdcpLevel()

I don't think ExoPlayer needs to expose this in another way, so I'm going to close this - but please reply here if I've misunderstood the question or requirements.

**Comment by icbaker** [comment]
Oh I missed `MediaDrm` is `Autocloseable` - updated my example above to use try-with-resources.
