### ISSUE TITLE
Overriding Controller UI no longer work?

### ISSUE THREAD

**Issue by ArcherEmiya05** [google/ExoPlayer#8930]
We can only process bug reports that are actionable. Unclear bug reports or
reports with insufficient information may not get attention.

Before filing a bug:
-------------------------

- Search existing issues, including issues that are closed:
  https://github.com/google/ExoPlayer/issues?q=is%3Aissue
- Consult our developer website: https://exoplayer.dev/
- Check the supported formats: https://exoplayer.dev/supported-formats.html
- Try playing problematic media in the demo app:
  http://exoplayer.dev/demo-application.html

When reporting a bug:
-------------------------

Describe how the issue can be reproduced, ideally using the ExoPlayer demo app
or a small sample app that you’re able to share as source code on GitHub. To
increase the chance of your issue getting attention, please also include:

- Clear reproduction steps including observed and expected behavior
- Output of running "adb bugreport" in the console shortly after encountering
  the issue
- URI to test content for reproduction
- For protected content:
  - DRM scheme and license server URL
  - Authentication HTTP headers

- ExoPlayer version number : 2.13.3
- Android version : 10
- Android device : Mi9T Pro

If there's something you don't want to post publicly, please submit the issue,
then email the link/bug report to dev.exoplayer@gmail.com using a subject in the
format "Issue #1234", where #1234 is your issue number (we don't reply to
emails).

```
<com.google.android.exoplayer2.ui.PlayerView
        android:id="@+id/player_view"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_centerInParent="true"
        android:theme="@style/MyAppTheme.Progress"
        app:hide_during_ads="true"
        android:animateLayoutChanges="true"
        app:controller_layout_id="@layout/exo_player_control_view"
        app:keep_content_on_player_reset="true"
        app:show_buffering="always"
        app:surface_type="surface_view" />
```

This no longer works, I can skip the ads or have a ripple touch feedback from the controller UI but pause/play , fast forward, etc is not working. This happens after updating with `2.13.3`

**Comment by ojw28** [comment]
From the information provided, it's unclear exactly what no longer works, or why. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that demonstrates the problem in a way that we can build locally. This could be an Android Studio project on GitHub, or zipped up and sent to dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Please also update this issue to indicate you’ve done this.

**Comment by ArcherEmiya05** [comment]
Unfortunately the project was too big, but after updating to latest version `2.13.3` the overriding of controller no longer works while downgrading it back to original version `2.11.1` it works just fine.

**Comment by ArcherEmiya05** [comment]
I  guess this has something to do with `ControlDispatcher` vs `PlaybackPreparer` ?

**Comment by ArcherEmiya05** [comment]
I can confirm that implementing ControlDispatcher with `playerView.setControlDispatcher(this)` means you will be responsible for handling the control UI and player behavior since it overrides a lot of method. Actually all I need is `dispatchPrepare` where I start creating the player and its MediaSource but implementing `ControlDispatcher ` forces me to implement all override methods. I guess I will just remove it completely.
