### ISSUE TITLE
Cronet long to int overflow

### ISSUE THREAD

**Issue by DarkAnakin** [google/ExoPlayer#8931]
https://github.com/google/ExoPlayer/blob/aeb306a164911aa1491b46c2db4da0d329c83c65/extensions/cronet/src/main/java/com/google/android/exoplayer2/ext/cronet/CronetDataSource.java#L669

Casting can return overflow if file larger than ~2GB. You can ignore this message if it's intentional.

**Comment by Samrobbo** [comment]
Fortunately, the fix for this (bc69509aba5afacaeb0e2ac5114f5a7c155f352a) has already been committed! It'll be released as part of the next release. If you want to see how it works, use the dev-v2 branch rather than release.
