### ISSUE TITLE
how to download video thumbnail image with video 

### ISSUE THREAD

**Issue by NG-Gaurav** [google/ExoPlayer#8932]
We have two video thumbnails one portrait and the other for landscape. so how to download both thumbnails with video.

**Comment by Samrobbo** [comment]
How are the thumbnails stored? Are they part of the video metadata? 

There is not much information here for us to be able to help. The best way to get good assistance on the issue tracker is to fill in the issue template, which can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md). If you're unable to share test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Please also update this issue to indicate you’ve done this.

**Comment by NG-Gaurav** [comment]
https://snagfilms-a.akamaihd.net/7fa0ea9a-9799-4417-99f5-cbb5343c551d/images/2021/01/22/1611276403267_hello3_600x338_ep1_16x9Images.jpg

**Comment by NG-Gaurav** [comment]
this is the thumbnail URL that we want to download with video file.

**Comment by Samrobbo** [comment]
I'm not quite sure how this relates to ExoPlayer. Can you not download the thumbnail through normal methods to download an image on android?

**Comment by ojw28** [comment]
I agree it's very unclear what this request is about. Downloading a thumbnail image can be done independently of ExoPlayer.
