### ISSUE TITLE
AdError VAST_EMPTY_RESPONSE when VAST Tag is good

### ISSUE THREAD

**Issue by devnullpointer** [google/ExoPlayer#8934]
When setting the AdTagUri in the MediaItem, ExoPlayer logs an error: `AdError [errorType: LOAD, errorCode: AdErrorCode [name: VAST_EMPTY_RESPONSE, number: 1009], message: The VAST response document is empty` even though the VAST Tag is valid.

```
mediaItem = new MediaItem.Builder()
                        .setUri(streamUri)
                        .setAdTagUri(Uri.parse(IMA_ADTAG))
                        .setMimeType(MimeTypes.APPLICATION_M3U8);

```
- ExoPlayer 2.13.3
- Android 8.0
- Pixel 4

**Comment by Samrobbo** [comment]
Do you have an example streamUri that we can use to verify this is reproducable? If you're unable to share test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Please also update this issue to indicate you’ve done this.

**Comment by devnullpointer** [comment]
@Samrobbo The player doesn't crash, the ad never gets played and the player plays the intended stream. You can use buck bunny as a test stream. I even tested the adtag in the ExoPlayer Demo app, same thing.

**Comment by Samrobbo** [comment]
Note for assignee, stream url has been provided in an email.

**Comment by andrewlewis** [comment]
I can't reproduce this in the ExoPlayer demo app using the ad tag URI provided via email (the ad loads and plays as expected).

**Comment by devnullpointer** [comment]
They might have fixed the issue. I'll retest on my end.
