### ISSUE TITLE
playback mp3 with some noise on AVD API 23

### ISSUE THREAD

**Issue by permenko** [google/ExoPlayer#894]
Hello,
I try a demo application on a virtual device Nexus_5_API_23_x86 and mp3 playback with some noise.
My friend the same problem with the virtual device, I also tried different mp3s and some problem occurs about half the time (one and the same song is played normally, but the new buffering the same noise).
The only problem in version 23, the older work fine.

sample mp3: https://drive.google.com/uc?export=download&id=0B0WER-eCrqYPV2VMLWJ5Z3FOcE0

**Comment by ojw28** [comment]
If this is only when using the emulator, I'm afraid you'll have to figure out where to file a bug on the emulator itself, and report the issue there. Please re-open if you can reproduce the issue on a real device. It works fine for me on a Nexus 5X.
