### ISSUE TITLE
How should I use the pass-through function？

### ISSUE THREAD

**Issue by kdsrsl** [google/ExoPlayer#8940]
I have an android box which supports Dolby decoding function.
The box is connected to a playback device, which also supports Dolby decoding.

I want to configure the box to output audio to the playback device through the passthrough function. How should I operate in exoplayer?
I have read Google's search results and github issues, but the debugging was not successful.
I hope to be able to send passthrough data through HDMI and S/PDIF lines respectively.
I used exoplayer 2.13.3，android box system version is 9.
Thanks.

**Comment by krocard** [comment]
This is handled automatically by `SimpleExoPlayer` and enabled by default. More specifically the supported formats are automatically discovered by `AudioCapabilities.getCapabilities()` and passed to the `DefaultAudioSink` by the `RenderersFactory.buildAudioSink`.

Just play the Dolby media with ExoPlayer normally and, if the device supports it, it will be played in passthrough.
