### ISSUE TITLE
Notification for download after pausing download.

### ISSUE THREAD

**Issue by pratikK017** [google/ExoPlayer#8945]
We are developing app where we are working on download part.

Requirement is to show a notification when download is paused. so that from the notification we can resume or remove the download.
but with current version notification is removed when download is paused. 

Is there any way to show download notification even when download is paused, which should be same as progress notification.

**Comment by pratikK017** [comment]
Is there any update in this. Please let me know. Also we are using latest exo player version i.e. 2.14.1.

**Comment by marcbaechinger** [comment]
There is no way to do that out of the box I'm afraid.

I'm assuming you are using the `DownloadService` for downloading. So you have subclassed the `DownloadService` and implemented the `getDownloadManager()` method. The `DownloadManager` has a `addListener` method that allows you to register a listener that gets its `onDownloadsPausedChanged(DownloadManager downloadManager, boolean downloadsPaused)` called when a change in pausing occurs. `DownloadManager.getDownloadsPaused()` tells you whether downloads are paused or not.

This way you can listen to this event and if downloads are pause, then post your own notification that allows the user to resume. On another call to that method you can then remove your custom notification again if `getDownloadsPaused` returns false again.
