### ISSUE TITLE
Exoplayer buffer time too long

### ISSUE THREAD

**Issue by ghost** [google/ExoPlayer#8948]
I am building audio podcast app. 
But I faced big problem.
I used exoplayer for audio podcast. When I move time track, I have to wait too long time to play audio
When exoplayer buffer audio, played. But on ios AVPlayer is fast to buffer. I think there are best solution to reduce buffer time.
```java
DefaultBandwidthMeter.Builder bandwidthMeter = new DefaultBandwidthMeter.Builder(getApplicationContext());
AdaptiveTrackSelection.Factory trackSelectionFactory = new AdaptiveTrackSelection.Factory();
DefaultTrackSelector trackSelector = new DefaultTrackSelector(getApplicationContext(), trackSelectionFactory);
DefaultAllocator allocator = new DefaultAllocator(true, C.DEFAULT_BUFFER_SEGMENT_SIZE);
DefaultLoadControl loadControl = new DefaultLoadControl.Builder()
    .setAllocator(allocator)
    .setBufferDurationsMs(1000 * 60 * 60, 1000 * 60 * 60 * 2, 1000, 2000)
    .build();
exoPlayer = new SimpleExoPlayer.Builder(getApplicationContext())
    .setTrackSelector(trackSelector)
    .setBandwidthMeter(bandwidthMeter.build())
    .setLoadControl(loadControl)
    .build();
 exoPlayer.addListener(this);
```
My exoplayer is above.
Thank you for your help

**Comment by krocard** [comment]
The media that has already been played is kept in a "back buffer". By default to save memory, the size of the back buffer is 0,  so when seeking back, the media has to be downloaded again.
You can adjust the size of the back buffer by `DefaultLoadControl.Builder.setBackBuffer`.
https://github.com/google/ExoPlayer/blob/d5d78238773d6dc53b54849ca10d845a4421284c/library/core/src/main/java/com/google/android/exoplayer2/DefaultLoadControl.java#L203-L213
