### ISSUE TITLE
Subtitle / Captions Styling

### ISSUE THREAD

**Issue by sjarschel-vida** [google/ExoPlayer#8958]
I am having some challenges styling my subtitles with the Exoplayer. I am passing subtitles via webvtt files with an HLS media source. This works fine for the most part, subtitles are rendered in the player view.

    private fun buildHlsMediaSource(uri: Uri): MediaSource {
        val dataSourceFactory = DefaultHttpDataSource.Factory()
        val hlsDataSourceFactory = DefaultHlsDataSourceFactory(dataSourceFactory)
        val hlsMediaSourceFactory = HlsMediaSource.Factory(hlsDataSourceFactory)
        return hlsMediaSourceFactory.createMediaSource(MediaItem.fromUri(uri))
    }

Now I want to style the subtitles via the CSS format inside the vtt files. Something like this:

WEBVTT

STYLE
::cue {
  font-size: 80%;
  font-style: italic;
  color: yellow;
  font-weight: bold;
  background-color: red;
}

00:00:00.000 --> 00:01:40.000 position:50% align:center size:85%
This blade has a dark past.
You're lucky your blood's still flowing.
This font is way too big!

The player obeys all these styling options, except for the font size (which is the most important one to me). No matter what I try the player ignores the size (works fine on iOS). Furthermore, the rendered default font size seems to change with the ratio of the video, e.g. if the video is in landscape mode the subtitles are too small. If the video is in portrait mode, the subtitles are too big.

<img width="407" alt="image" src="https://user-images.githubusercontent.com/66448150/118687316-b6e18d80-b7b9-11eb-835f-e47e4d5ba89a.png">

How do I change the font size via embedded webvtt styling?

OK, now I tried using the subtitle view. Hooking it up was amazingly easy:

                videoPlayer.addTextOutput(TextOutput {
                    subtitleView?.onCues(it)
                })

However, captions are now rendered double, once in the player view and once in the subtitle view:

<img width="407" alt="image" src="https://user-images.githubusercontent.com/66448150/118688337-d1683680-b7ba-11eb-96fa-bcea4933e7c4.png">

**I do understand why is is happening, but is obviously not what I want. I desperately want to know how I do make the subtitles in the player view go away and only show them in the subtitle view. I found nothing on the Internet and no one seems to have this problem.**

Disabling the text track does not help:

        trackSelector.parameters = trackSelector.buildUponParameters().setRendererDisabled(2, true).build()

because this makes the player stop sending text to the TextOutput (subtitleView) also. I know this is intended behavior because the player sends an empty cue when I disable the text track. So, I get all or nothing. What am I missing?

The only workaround I found is to make the fonts in the player view disappear by setting both font and window color with alpha=0 in the webvtt style:

  color: rgba(0,0,0,0);
  background-color: rgba(0,0,0,0);

This of course make the fonts disappear in the subtitle view as well, so I need to turn embedded styles off:

        subtitleView.setApplyEmbeddedFontSizes(false)
        subtitleView.setApplyEmbeddedStyles(false)

I am now able to change the font size, but font color seems to be fixed to white and the window color to black. What is the best way to set font color and text window color?

Overall, frustrating experience. Am I doing this all wrong?

**Comment by sjarschel-vida** [comment]
Got the styling working now:

    private fun configureSubtitleView() {
        subtitleView.setApplyEmbeddedFontSizes(false)
        subtitleView.setApplyEmbeddedStyles(false)
        subtitleView.setFixedTextSize(TEXT_SIZE_TYPE_ABSOLUTE, 30F)
        subtitleView.setBottomPaddingFraction(.1F)

        val style = CaptionStyleCompat(Color.WHITE, Color.GRAY, Color.TRANSPARENT,
            CaptionStyleCompat.EDGE_TYPE_NONE, Color.TRANSPARENT, null)
        subtitleView.setStyle(style)
    }

My main question still stands: How can I turn off subtitles in the player view while showing them in the subtitle view? I would prefer not to have separate webvtt files just for Android to make the subtitles invisible via vtt styling.

**Comment by icbaker** [comment]
There's a few different things going on here.

1. As you've noted, ExoPlayer doesn't  parse the `font-size` CSS property from WebVTT style info. I've filed https://github.com/google/ExoPlayer/issues/8964 to track adding support for that (no ETA I'm afraid, but we would welcome a high quality pull request if you're interested in contributing the feature).

2. It sounds like you're manually instantiating a `SubtitleView` while there's one already instantiated by `StyledPlayerView` (which results in the subtitles being shown twice): https://github.com/google/ExoPlayer/blob/d5d78238773d6dc53b54849ca10d845a4421284c/library/ui/src/main/res/layout/exo_styled_player_view.xml#L35-L37
    You can get a handle to it by calling [`StyledPlayerView#getSubtitleView()`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/ui/StyledPlayerView.html#getSubtitleView()). You can then use that `SubtitleView` instance in your `configureSubtitleView()` method, and I guess avoid instantiating your own.

Hopefully that helps! I'll close this for now, but let me know if you still have questions and I can re-open it.

**Comment by sjarschel-vida** [comment]
Thank you @icbaker! StyledPlayerView was the missing link.
