### ISSUE TITLE
Texture View flip

### ISSUE THREAD

**Issue by lacheolsoo** [google/ExoPlayer#8971]
I am testing RTSP.
When the screen is flipped, it goes out of the center.
VLC works fine with the same code.

Test Version : 2.14.0 (2021-05-13)
Device : Samsung Galaxy S21 Ultra (Android 11)

    private void flipTextureView() {
        Matrix transform = new Matrix();
        float x = (float)(mPlayerView.getWidth()/2);
        float y = (float)(mPlayerView.getHeight()/2);

        if (mbFlip) {
            mbtnFlip.setBackgroundResource(R.drawable.btn_reverse_on);
            transform.setScale(-1, 1, x, y);
        } else {
            mbtnFlip.setBackgroundResource(R.drawable.btn_reverse_off);
            transform.setScale(1, 1, x, y);
        }

        TextureView textureView = (TextureView) mPlayerView.getVideoSurfaceView();
        if (textureView != null) {
            textureView.setTransform(transform);
        }
    }

<com.google.android.exoplayer2.ui.PlayerView
                android:id="@+id/videoView"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                app:surface_type="texture_view"
                app:use_controller="false"/>

![normal](https://user-images.githubusercontent.com/23448289/119075120-3b871280-ba2b-11eb-886c-f238dcd255da.jpg)
![flip](https://user-images.githubusercontent.com/23448289/119075129-40e45d00-ba2b-11eb-8d47-290192163b58.jpg)

**Comment by krocard** [comment]
> I am testing RTSP.

@claincly will be glad to hear that. Nevertheless I don't think RTSP is related to the TextureView issue.

> `textureView.setTransform(transform);`

The UI already applies a transformation (see [`applyTextureViewRotation`](https://github.com/google/ExoPlayer/blob/bd54394391b0527893f382c9d641b8a55ffca765/library/ui/src/main/java/com/google/android/exoplayer2/ui/StyledPlayerView.java#L1463)) to match the video aspect ratio and size to the view port. By calling `setTransform` this adaptation is removed. As visible in the screen captures, the aspect ratio is incorrect.
The solution is to apply a rotation to the existing matrix (I haven't tested the snippet, but you get the idea):

```
Matrix matrix = new Matrix();
textureView.getTransform(matrix);
matrix.setTranslate(-1, 1);
textureView.setTransform(matrix);
```

Note that you will have to reapply this transformation on [every video size change](
https://github.com/google/ExoPlayer/blob/bd54394391b0527893f382c9d641b8a55ffca765/library/ui/src/main/java/com/google/android/exoplayer2/ui/StyledPlayerView.java#L1544) and [layout update](https://github.com/google/ExoPlayer/blob/bd54394391b0527893f382c9d641b8a55ffca765/library/ui/src/main/java/com/google/android/exoplayer2/ui/StyledPlayerView.java#L1625) as the player view overrides the existing matrix:

**Comment by lacheolsoo** [comment]
Thank you for answer. The code below temporarily solved the problem.
It will be necessary to study more whether it works differently from VLC.
(It was not an aspect ratio problem, it was a problem that the left side of the screen was cut off.)

    /**
     * Video Source Resolution : 1920x1080 (fixed)
     * 1920/1080 = 1.78
     */
    private void flipTextureView() {
        Matrix matrix = new Matrix();
        TextureView textureView = (TextureView) mPlayerView.getVideoSurfaceView();

        if (textureView != null) {
            float y = (float)(mPlayerView.getHeight()/2);
            float x = (mPlayerView.getHeight() * 1.78f)/2;

            if (mbFlip) {
                mbtnFlip.setBackgroundResource(R.drawable.btn_reverse_on);
                matrix.setScale(-1, 1, x, y);
            } else {
                mbtnFlip.setBackgroundResource(R.drawable.btn_reverse_off);
                matrix.setScale(1, 1, x, y);
            }

            textureView.setTransform(matrix);
        }
    }

**Comment by krocard** [comment]
Your code seems very similar, but suspiciously different (especially the 1.78 magic) than the player view calculation: https://github.com/google/ExoPlayer/blob/bd54394391b0527893f382c9d641b8a55ffca765/library/ui/src/main/java/com/google/android/exoplayer2/ui/StyledPlayerView.java#L1463-L1483.
Your code might break if the video size/aspect ration/layout size changes.

Have you tried adding the flip transformation as suggested in my previous comment instead? It is simpler and should be more robust.

**Comment by lacheolsoo** [comment]
I tried but the result was the same...
Now I'm using below code. 

    /**
     * Consider using getLocationInWindow instead of getLocationOnScreen depending 
     * on the visibility of the status bar
     */
    private void flipTextureView() {
        Matrix matrix = new Matrix();
        TextureView textureView = (TextureView) mPlayerView.getVideoSurfaceView();

        if (textureView != null) {
            float x = (float)(mPlayerView.getWidth()/2);
            float y = (float)(mPlayerView.getHeight()/2);

            // Starting location of the TextureView
            int[] outLocation = new int[2];
            textureView.getLocationOnScreen(outLocation);
            
            if (mbFlip) {
                mbtnFlip.setBackgroundResource(R.drawable.btn_reverse_on);
                matrix.setScale(-1, 1, x-outLocation[0], y);
            } else {
                mbtnFlip.setBackgroundResource(R.drawable.btn_reverse_off);
                matrix.setScale(1, 1, x-outLocation[0], y);
            }

            textureView.setTransform(matrix);
        }
    }
