### ISSUE TITLE
How to set player don't load whole video in the beginning.

### ISSUE THREAD

**Issue by javalue** [google/ExoPlayer#8972]
When I try to play video by exoplayer, video maybe 2-3Mb (10-20s) or other big size(10Mb - 60s)
I wan‘t to play video and  load whole video in the beginning. it's too waste stream.
i try to use loadcontrol.setBufferDurationsMs to reduce buffer size,but it's not work.
Could you help me to solve it?

**Comment by javalue** [comment]
`LoadControl loadControl = new DefaultLoadControl.Builder()
                .setBufferDurationsMs(1000,3000,
                        500, 1000)
                .createDefaultLoadControl();`

**Comment by krocard** [comment]
The bitrates mentioned are around 0.2Mb/s, which are fairly low for video. Your issue is that the whole video is downloaded before playback starts, right?

I'm guessing your app use-case is presenting lots of video that the user quickly switch through (like a gallery or Tick-Tock).

I'm not sure what causes the issue, DefaultLoadControl might not take into account all buffering occurring bellow the main network buffer, or it might be a variable bitrate issue.

@javalue could you attach one of the video triggering the issue? 
If you're unable to share test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #1234" ("#1234" is replaced with your issue number). Please also update this issue to indicate you've done this.

@ojw28 do you know the level of precision LoadController can achieve for low bitrate low duration?

**Comment by ojw28** [comment]
> @ojw28 do you know the level of precision LoadController can achieve for low bitrate low duration?

I think it should work at a granularity of around ~1MB increments of buffer.

@javalue - In addition to the information requested above, please could you also attach a slightly more complete code block showing how you build your player (i.e., after you create your `LoadControl`, how do you inject it into the player).

**Comment by javalue** [comment]
> > @ojw28你知道 LoadController 在低比特率低持续时间下可以达到的精度水平吗？
> 
> 我认为它应该以大约 1MB 缓冲区增量的粒度工作。
> 
> @javalue - 除了上面要求的信息之外，您能否附上一个稍微完整的代码块，显示您如何构建播放器（即，在创建您的 之后`LoadControl`，如何将其注入播放器）。

`LoadControl loadControl = new DefaultLoadControl.Builder()
                .setBufferDurationsMs(1000,3000,
                        500, 1000)
                .createDefaultLoadControl();

        TrackSelection.Factory trackSelectionFactory = new AdaptiveTrackSelection.Factory(new DefaultBandwidthMeter());

        DefaultTrackSelector trackSelector = new DefaultTrackSelector(trackSelectionFactory);

        trackSelector.setParameters(new DefaultTrackSelector.ParametersBuilder().build());

        DefaultRenderersFactory renderersFactory = new DefaultRenderersFactory(FrameworkUtil.getContext(),
                DefaultRenderersFactory.EXTENSION_RENDERER_MODE_ON);

        SimpleExoPlayer player = ExoPlayerFactory.newSimpleInstance(renderersFactory, trackSelector, loadControl);`

**Comment by javalue** [comment]
> > @ojw28你知道 LoadController 在低比特率低持续时间下可以达到的精确水平吗？
> 
> 我认为它应该大约有 1MB 增长的规模工作。
> 
> @javalue - 除了上面要求的信息之外，您还可以附上一个完整的代码块，显示您如何构建播放器（即，在创建您的之后`LoadControl`，如何将注入其播放器）。


`LoadControl loadControl = new DefaultLoadControl.Builder()
                .setBufferDurationsMs(1000,3000,
                        500, 1000)
                .createDefaultLoadControl();

        TrackSelection.Factory trackSelectionFactory = new AdaptiveTrackSelection.Factory(new DefaultBandwidthMeter());

        DefaultTrackSelector trackSelector = new DefaultTrackSelector(trackSelectionFactory);

        trackSelector.setParameters(new DefaultTrackSelector.ParametersBuilder().build());

        DefaultRenderersFactory renderersFactory = new DefaultRenderersFactory(FrameworkUtil.getContext(),
                DefaultRenderersFactory.EXTENSION_RENDERER_MODE_ON);

        SimpleExoPlayer player = ExoPlayerFactory.newSimpleInstance(renderersFactory, trackSelector, loadControl);`

**Comment by javalue** [comment]
> > @ojw28你知道 LoadController 在低比特率低持续时间下可以达到的精度水平吗？
> 
> 我认为它应该以大约 1MB 缓冲区增量的粒度工作。
> 
> @javalue - 除了上面要求的信息之外，您能否附上一个稍微完整的代码块，显示您如何构建播放器（即，在创建您的 之后`LoadControl`，如何将其注入播放器）。

the video maybe have 1.5mb,when it play 1s,i pause it,but the cache have already downloaded the whole video.

**Comment by javalue** [comment]
> 由于这里没有任何最近的更新，我将关闭此问题。
> 
> @javalue如果您仍然遇到此问题并想继续讨论，请在此处发表评论，我们很乐意重新打开此问题。

please open it. thanks
