### ISSUE TITLE
how to play a custom chunk files with different download manager 

### ISSUE THREAD

**Issue by hosseinkhojany** [google/ExoPlayer#8977]
How can I give Exo a different source of Chunks downloaded with a own download manager?

**Comment by ojw28** [comment]
If the result of your download logic is that you have a valid media file (or a complete and valid DASH and HLS stream) downloaded locally, then you can simply pass a `file:///` URI that points to it to ExoPlayer, and playback should work fine.

If your use case is different, then it sounds like your question falls outside the scope of this issue tracker. We provide built in components to implement the functionality you request, so we'd suggest using those if you can't get your own solution to work.
