### ISSUE TITLE
How can I seek in video with encrypted content?

### ISSUE THREAD

**Issue by Clement-Jean** [google/ExoPlayer#8978]
Recently I've been trying to read my encrypted videos and the playing/fast forward work well however the seek action leads to a weird behavior. The behavior is that it will stop playing and the play button will stay as if the content is reading (sometime the cursor is even moving).

Here is my `CipherHelper`, which helps me encrypt/decrypt the content:

```
object CipherHelper {
    private const val ALGORITHM = "AES/CBC/NoPadding"

    private const val KEY_LENGTH = 32
    private const val IV_LENGTH = 16

    private const val salt = "..."

    fun getEncryptCipher(pass: String): Cipher = Cipher.getInstance(ALGORITHM).apply {
        init(Cipher.ENCRYPT_MODE, getAESKey(pass), IvParameterSpec(getIv(pass)))
    }

    fun getDecryptCipher(pass: String): Cipher = Cipher.getInstance(ALGORITHM).apply {
        init(Cipher.DECRYPT_MODE, getAES(pass), IvParameterSpec(getIv(pass)))
    }

    private fun getAESKey(pass: String): SecretKey {
        val factory: SecretKeyFactory = SecretKeyFactory.getInstance("PBKDF2WithHmacSHA256")
        val spec: KeySpec = PBEKeySpec(pass.take(KEY_LENGTH).toCharArray(), salt.toByteArray(), 65536, 256)

        return SecretKeySpec(factory.generateSecret(spec).encoded, "AES")
    }

    private fun getIv(pass: String) = pass.substring(0, IV_LENGTH).toByteArray()
}
```
Then here is the custom `DataSource` I made for decrypting the content (largely inspired by [this](https://stackoverflow.com/questions/62565879/android-exoplayer-play-aes-encrypted-videos-locally)):

```
class EncryptedDataSourceFactory(
    private val cipher: Cipher
) : DataSource.Factory {
    override fun createDataSource() = EncryptedDataSource(cipher)
}

class EncryptedDataSource(
    private val cipher: Cipher
): DataSource {
    private lateinit var uri: Uri
    private lateinit var inputStream: CipherInputStream

    override fun addTransferListener(transferListener: TransferListener) {}

    override fun open(dataSpec: DataSpec): Long {
        uri = dataSpec.uri
        inputStream = CipherInputStream(uri.toFile().inputStream(), cipher)
        return dataSpec.length
    }

    override fun read(buffer: ByteArray, offset: Int, readLength: Int): Int =
        if (readLength == 0) {
            0
        } else {
            inputStream.read(buffer, offset, readLength)
        }

    override fun getUri() = uri

    override fun close() {
        inputStream.close()
    }
}
```
And finally here is how I create the playlist of my videos:

```
val mediaSource = ConcatenatingMediaSource()
val dataSourceFactory = EncryptedDataSourceFactory(CipherHelper.getDecryptCipher(uuid))

list.forEach {
    val mediaItem = MediaItem.Builder().setTag(it.id).setUri(Uri.fromFile(
        File(
            videosDirectory,
            it.id.toString()
        )
    )).build()

    val source = ProgressiveMediaSource.Factory(dataSourceFactory).createMediaSource(mediaItem)

    mediaSource.addMediaSource(source)
}
```

Furthermore, during the debugging I found out that when I seek to a certain time in the video, the `EncryptedDataSource` will indefinitely call close/start, close/start, ...

Did I miss something here ? How can I improve this ?

**Comment by icbaker** [comment]
Your implementation of `DataSource#open` doesn't look correct - it ignores several important fields of the `dataSpec` parameter including `DataSpec#position`, which probably explains your seeking problems.

We recently wrote a standard test suite for our own `DataSource` implementations - to check compliance with the interface. You may find it helpful to use the same suite for your implementation - you can do this by subclassing [`DataSourceContractTest`](https://github.com/google/ExoPlayer/blob/release-v2/testutils/src/main/java/com/google/android/exoplayer2/testutil/DataSourceContractTest.java). You'll need to provide some test data (encrypted in your case), and the expected result data (unencrypted). You can take a look at examples in our code base by looking for other subclasses of this test class.

**Comment by Clement-Jean** [comment]
I need to say thank you to you 🙏 I didn't try the test yet, but my seek problem is gone.

for the others who have this problem, please take a look at `DefaultHttpDataSource`, you can easily remove the connection part and adapt it to your encrypted datasource.
