### ISSUE TITLE
How to temporarily cache content to allow seeking backwards 

### ISSUE THREAD

**Issue by logituitrel** [google/ExoPlayer#8982]
We are currently using exo version 2.11.8, and are able to replicate this behavior in exoplayer sample app for the same.

Scenario:
1. When playback starts, pause and wait for content to buffer for some time.
2. Switch off internet and play.
3. Play and seeking forward works fine, but seeking backwards within the buffered content immediately results in Playback Failure.

This is easily replicable in contents with short content duration, as the buffer bar gets more area.

**Comment by marcbaechinger** [comment]
I think without further configuration this is kind of working as intended. After playback the data in the buffer is discarded and when you want to seek back the player would need to load data from the network again. 

> seeking backwards within the buffered content immediately results in Playback Failure/ buffer bar

I think with 'buffered content' you are referring what the UI displays behind the current position which is a bit misleading as this data is not actually retained but immediately discarded after playback.

You can configure the duration of the back buffer when building the `DefaultLoadControl` (defaults to 0) but I don't think this is a solution for offline which is what your repro steps suggest.

If you want to cache data temporarily, to make seeking backwards possible when offline, you may want to use a `CacheDataSource.Factory`. There is a [code snippet in the DevGuide](https://exoplayer.dev/customization.html#caching-data-loaded-from-the-network) about this. The snippet uses an instance of a `SimpleCache` that you can setup to match your use case.
