### ISSUE TITLE
StyledPlayerView issue in 2.14.0

### ISSUE THREAD

**Issue by eprendre** [google/ExoPlayer#8985]
After upgrading from 2.12 to 2.14, NullPointerException occured in `ComponentListener` after StyledPlayerView.setPlayer(null) then player.clearMediaItems(). While it's safe to call PlayerView.setPlayer(null).

There is `oldPlayer.removeListener(componentListener);` in `PlayerView`, I believe it was accidently deleted in `StyledPlayerView`.
![screenshot](https://user-images.githubusercontent.com/7194531/119533072-12aea680-bdb8-11eb-819e-8a37adac2651.jpg)

**Comment by ojw28** [comment]
Thanks for the report. We'll get this fixed in 2.14.1.

**Comment by ojw28** [comment]
This should be fixed by the commit referenced above. We'll get it into 2.14.1.
