### ISSUE TITLE
TsExtractor DTS decode timestamp adjustment causing timestamp shift

### ISSUE THREAD

**Issue by brabeler** [google/ExoPlayer#899]
I have noticed the following starting in version 1.5.1, as compared to 1.4.2.

In extractor/ts/TsExtractor.java, in PesReader.parseHeaderExtension(), the first sample's DTS decode timestamp is sent to ptsTimestampAdjuster.adjustTimestamp() to set the timestamp offset to apply to all future samples.  This value is stored as PtsTimestampAdjuster.timestampOffsetUs.

For my particular H265 HLS streaming media sample, the value of PtsTimestampAdjuster.timestampOffsetUs in 1.4.2 is -1466733 but in 1.5.1 it is now -1400000.  This has the effect of shifting all the timestamps forward in time by 2 samples, eliminating the first two values.

I logged the sample timestamp and size from SampleReader.outputSample() in H265Reader.java.

Log from 1.4.2:
timestampOffsetUs: -1466733
H265Reader.outputSample() timeUs: 0 size: 554
H265Reader.outputSample() timeUs: 166833 size: 351
H265Reader.outputSample() timeUs: 100100 size: 188
H265Reader.outputSample() timeUs: 33367 size: 139
H265Reader.outputSample() timeUs: 66733 size: 141
H265Reader.outputSample() timeUs: 133467 size: 168
H265Reader.outputSample() timeUs: 333667 size: 1101
H265Reader.outputSample() timeUs: 266933 size: 497
H265Reader.outputSample() timeUs: 200200 size: 268
H265Reader.outputSample() timeUs: 233567 size: 323
H265Reader.outputSample() timeUs: 300300 size: 441
H265Reader.outputSample() timeUs: 500500 size: 3097

Log from 1.5.1:
timestampOffsetUs: -1400000
H265Reader.outputSample() timeUs: 66733 size: 554
H265Reader.outputSample() timeUs: 233566 size: 351
H265Reader.outputSample() timeUs: 166833 size: 188
H265Reader.outputSample() timeUs: 100100 size: 139
H265Reader.outputSample() timeUs: 133466 size: 141
H265Reader.outputSample() timeUs: 200200 size: 168
H265Reader.outputSample() timeUs: 400400 size: 1101
H265Reader.outputSample() timeUs: 333666 size: 497
H265Reader.outputSample() timeUs: 266933 size: 268
H265Reader.outputSample() timeUs: 300300 size: 323
H265Reader.outputSample() timeUs: 367033 size: 441
H265Reader.outputSample() timeUs: 567233 size: 3097

It seems wrong that the video samples are shifted forward in time by 2 samples.  It also seems wrong that the first timestamp is not 0 ms.

I have not noticed any glitch in the video.  But the audio could be out of sync slightly, if the video is ahead by 66 ms from where it should be.

**Comment by ojw28** [comment]
We shift audio and video timestamps by the same amount, using the same PtsTimestampAdjuster. Hence any change in the offset between the two versions will be applied equally to both audio and video, and A/V sync will be unchanged.

Unless there's a user visible effect of this issue, I think it should be marked working as intended. Note that the fact DTS is making a difference implies that segments aren't starting with keyframes, which means some of the frames at the start of the first segment will end up being discarded rather than being played anyway.
