### ISSUE TITLE
Notification not showing on real devices but showing in emulator

### ISSUE THREAD

**Issue by khsuzan** [google/ExoPlayer#8995]
I am using the builder class to show the notification when playing audio but its showing in the emulator but not showing `on` real devices

```
 PlayerNotificationManager notiBuilder = new PlayerNotificationManager.Builder(getApplicationContext()
                , NOTI_ID, CHANNEL_ID, new MediaDescripTo()).build();
        notiBuilder.setControlDispatcher(new DispatcherDef());

        notiBuilder.setUseNextAction(true);
        notiBuilder.setUsePreviousAction(true);
        notiBuilder.setVisibility(NotificationCompat.VISIBILITY_PUBLIC);
        notiBuilder.setPlayer(exoPlayer);
```

What I am missing or am I not going correct!

**Comment by marcbaechinger** [comment]
Do you think it may be a difference in API versions when you compare this on real device and emulator?

Please check that you are comparing device and emulator with the same OS version. If you still see a difference, please let us know detailed information about what device/OS and emulator/OS you are using. You need to provide more information and context than the snippet above.

If you still think it is a problem of the library, please provide a snippet of the code you are running when seeing the issue.

**Comment by khsuzan** [comment]
Finally notification show up and that was a mistake to add a channel to the notification builder
My final code with fix are 
 ```
PlayerNotificationManager.Builder myNoti = new PlayerNotificationManager.Builder(getApplicationContext()
                , NOTI_ID, CHANNEL_ID, new MediaDescripTo());
        myNoti.setNotificationListener(new NotiListener());
        myNoti.setChannelImportance(NotificationUtil.IMPORTANCE_LOW);
        myNoti.setChannelNameResourceId(R.string.channelname);

        PlayerNotificationManager nManager = myNoti.build();
        nManager.setControlDispatcher(new DispatcherDef());
        nManager.setUseNextAction(true);
        nManager.setUsePreviousAction(true);
        nManager.setVisibility(NotificationCompat.VISIBILITY_PUBLIC);
        nManager.setPlayer(exoPlayer);
```
