### ISSUE TITLE
Dolby Vision videos can not be extracted correctly

### ISSUE THREAD

**Issue by avilliwesley** [google/ExoPlayer#8996]
We can only process bug reports that are actionable. Unclear bug reports or
reports with insufficient information may not get attention.

Before filing a bug:
-------------------------

- Search existing issues, including issues that are closed:
  https://github.com/google/ExoPlayer/issues?q=is%3Aissue
- Consult our developer website: https://exoplayer.dev/
- Check the supported formats: https://exoplayer.dev/supported-formats.html
- Try playing problematic media in the demo app:
  http://exoplayer.dev/demo-application.html

When reporting a bug:
-------------------------

Describe how the issue can be reproduced, ideally using the ExoPlayer demo app
or a small sample app that you’re able to share as source code on GitHub. To
increase the chance of your issue getting attention, please also include:

- Clear reproduction steps including observed and expected behavior
- Output of running "adb bugreport" in the console shortly after encountering
  the issue
- URI to test content for reproduction
- For protected content:
  - DRM scheme and license server URL
  - Authentication HTTP headers

- ExoPlayer version number
- Android version
- Android device

If there's something you don't want to post publicly, please submit the issue,
then email the link/bug report to dev.exoplayer@gmail.com using a subject in the
format "Issue #1234", where #1234 is your issue number (we don't reply to
emails).

**Comment by avilliwesley** [comment]
- Clear reproduction steps including observed and expected behavior

1.Push Dolby Vision videos to device;
2.Open Photos to play Dolby Vision videos;
3.Dolby Vision Profile 8 and Profile 9 will not be played sometimes.
OBSERVED RESULTS: Profile 8 or Profile 9 video can not be played.
EXPECTED RESULTS:Profile 8 and Profile 9 can be played.

- Output of running "adb bugreport" in the console shortly after encountering

the issue
The bugreport is attatched.

- URI to test content for reproduction
The test video exceed 10M, I can not upload it.

For protected content:

DRM scheme and license server URL
Authentication HTTP headers

- ExoPlayer version number
I use the Exoplayer latest version r2.13.3 SDK to test, the issue is reproduce.
Android version
Android R/Android P can reproduce the issue

Android device
Lenovo P11 Pro/Lenovo BLADEX

**Comment by avilliwesley** [comment]
We created a case to google:  179633366, and google reply:
As Photos relies on the Explayer to support the video playback, it is not able to support the video format until they are supported by Exoplayer. Please feel free to open the issue to Exoplayer(github). The new format will be supported in Photos once it is available in Exoplayer.

**Comment by avilliwesley** [comment]
[bugreport-LenovoYT-K606F-RKQ1.201022.002-2021-02-08-01-59-18.zip](https://github.com/google/ExoPlayer/files/6568488/bugreport-LenovoYT-K606F-RKQ1.201022.002-2021-02-08-01-59-18.zip)

**Comment by avilliwesley** [comment]
https://user-images.githubusercontent.com/26531833/120158014-39d8fe00-c226-11eb-9cb7-6773dd088358.mp4

**Comment by avilliwesley** [comment]
Hi，

I modified the logic of ` private static List<MediaCodecInfo> getDecoderInfos()`, and tested the dolby vision being played normally. The modified file will be uploaded:
```
private static List<MediaCodecInfo> getDecoderInfos(
      MediaCodecSelector mediaCodecSelector,
      Format format,
      boolean requiresSecureDecoder,
      boolean requiresTunnelingDecoder)
      throws DecoderQueryException {
    @Nullable String mimeType = format.sampleMimeType;
    if (mimeType == null) {
      return Collections.emptyList();
    }

    List<MediaCodecInfo> decoderInfos = null;
    if (MimeTypes.VIDEO_DOLBY_VISION.equals(mimeType)) {
      // Fall back to H.264/AVC or H.265/HEVC for the relevant DV profiles.
      @Nullable
      Pair<Integer, Integer> codecProfileAndLevel = MediaCodecUtil.getCodecProfileAndLevel(format);
      if (codecProfileAndLevel != null) {
        int profile = codecProfileAndLevel.first;
        if (profile == CodecProfileLevel.DolbyVisionProfileDvheDtr
            || profile == CodecProfileLevel.DolbyVisionProfileDvheSt) {
          decoderInfos = mediaCodecSelector.getDecoderInfos(MimeTypes.VIDEO_H265, requiresSecureDecoder, requiresTunnelingDecoder);
        } else if (profile == CodecProfileLevel.DolbyVisionProfileDvavSe) {
          decoderInfos = mediaCodecSelector.getDecoderInfos(MimeTypes.VIDEO_H264, requiresSecureDecoder, requiresTunnelingDecoder);
        }
      }
    } else {
      decoderInfos =
          mediaCodecSelector.getDecoderInfos(
              mimeType, requiresSecureDecoder, requiresTunnelingDecoder);
      decoderInfos = MediaCodecUtil.getDecoderInfosSortedByFormatSupport(decoderInfos, format);
    }
    return Collections.unmodifiableList(decoderInfos);
  }
```

**Comment by avilliwesley** [comment]
[MediaCodecVideoRenderer.txt](https://github.com/google/ExoPlayer/files/6583905/MediaCodecVideoRenderer.txt)

**Comment by andrewlewis** [comment]
It looks like the effect of the change is that we never use a decoder advertising support for `video/dolby-vision` and instead we use an H.265 or H.264 decoder for the profiles that have compatible base layers. That doesn't sound like the correct fix -- if there is a Dolby Vision decoder on the device there must be cases where we'd prefer to use it. Is the root cause of the problem that there is a Dolby Vision decoder present but it doesn't support the required profiles?
