### ISSUE TITLE
Smooth Streaming: Peak bit rate field is empty but average bit rate field has the bitrate value

### ISSUE THREAD

**Issue by krishnarama** [google/ExoPlayer#8997]
Hi, we are trying to retrieve peak and average bit rates separately when they exist in the stream. When playing smooth streaming content we are receiving peak bit rate as empty and average bit rate field with valid value. However, as per the manifest and SS protocol there is no avg bandwidth/bitrate field but only Bitrate is present. 

**Steps to reproduce:**
Use the exoplayer sample app and play the content related to smooth streaming.
Retrieve peak and average bit rates separately. 
Actual Result: Peak bit rate is empty and average bit rate filed has the valid value.
Expected: Peak bit rate field should give the bit rate as per the manifest.
Devices: Reproducible on any device.
Bug report: Not attached.
Content URI: "https://playready.directtaps.net/smoothstreaming/SSWSS720H264/SuperSpeedway_720.ism/Manifest"
Exoplayer version: 2.13.0/2.14.0

Please advice if this is normal behavior or it is being fixed in future releases. Thank You

**Comment by andrewlewis** [comment]
> Actual Result: Peak bit rate is empty and average bit rate filed has the valid value.
> Expected: Peak bit rate field should give the bit rate as per the manifest.

Are you certain the value in the manifest is a peak bitrate and if so could you give a reference for this? Looking at the SS specification linked [here](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-sstr/8383f27f-7efe-4c60-832a-387274457251), I see "Bitrate (variable): The average bandwidth that is consumed by the track, in bits per second (bps)." so the current behavior seems correct.

**Comment by krishnarama** [comment]
That's right. I have referred to an outdated protocol document. Apologize for the confusion. Closing the ticket.
