### ISSUE TITLE
Can't player WideVine DRM streaming on OS 11

### ISSUE THREAD

**Issue by isaacchiang-kkstream** [google/ExoPlayer#8998]
## Question
I'm trying to player CGMS_NEVER(disable analog) protected MPEG-DASH streaming, but get `android.media.MediaCodec$CryptoException: Required output protections are not active` error message. I'm testing with the android TV (ADT-3, android 11), and the output only support HDMI. If DRM server only request the CGMS_NONE which means don't care analog, the streaming can play well without any exception.
Above issue only occurs on android OS 11, android OS 10 is fine.

Besides, I have tested return null directly in DefaultTrackSelector's selectAudioTrack() function. It play well just without audio output.

My question is how ExoPlayer detect the analog output from the environment? Can I get the detected result from app?

## A full bug report captured from the device
https://drive.google.com/drive/folders/1vZv6AhiSYVguIxwlaOVr8toTmy7RhRqd?usp=sharing

**Comment by icbaker** [comment]
Can you please provide links to manifests with both CGMS_NEVER and CGMS_NONE so that we can reproduce the problem and also see the working content?

This is just a guess, but I wonder if CGMS_NEVER prevents PCM (i.e. decoded) audio from passing over HDMI, but passing through DRM'd encoded audio won't work either because the receiving device won't be able to decrypt it. That would explain why disabling the audio track resolves the problem.

I don't know why it would work on Android 10 but fails on Android 11 - being able to reproduce the problem might help narrow that down.

What happens if you play this content on a device with a built-in screen (e.g. a phone)?

**Comment by isaacchiang-kkstream** [comment]
Hi @icbaker 

Thanks for your reply. The links to manifest as below:
`https://s3-ap-northeast-1.amazonaws.com/smt-theater/theater/exoplayer/drm/1540806115_dash.mpd`
In my test, I always use this manifest. Only switch the setting of DRM license server (CGMS_NEVER <=> CGMS_NONE).
I'm not sure, is that limitation depends on streaming itself? My understanding is the streaming will request DRM limitation to DRM license server. If server response CGMS_NEVER, then player will check the output criteria is satisfied or not? 

I have tested the same contents on android 10/12 mobile phone, it can be played well both of them. It's a pity that we don't have others android 11 devices.

**Comment by icbaker** [comment]
Sorry I should have been more clear that I need to be able to play the content, so I also need the DRM license URL.
If you don't want to post that here you can send it to dev.exoplayer@gmail.com using a subject in the format "Issue #1234" (where "#1234" should be replaced with this issue number.) Please also update this issue to indicate you’ve done this.

> In my test, I always use this manifest. Only switch the setting of DRM license server (CGMS_NEVER <=> CGMS_NONE).

Is it possible to configure two different license policies at different URLs (e.g. with query parameters?) so that we can try both configs without needing to toggle anything on your DRM server?

**Comment by isaacchiang-kkstream** [comment]
@icbaker 
Sorry I didn't understand what you mean before. I have sent a letter to the designated mailbox with the location of the DRM license server, and how to use the parameters. Thank you for your assistance.

**Comment by isaacchiang-kkstream** [comment]
@icbaker 

Are there any new discoveries? Can you reproduce this issue using the DRM server sent to you?

**Comment by icbaker** [comment]
@rrfrias Could you take a look at this?

It seems that if an audio track is protected with a DRM policy that enforces protected output then it fails to play over HDMI on Android 11 but not 10. Did something change in the DRM/Widevine stack that might explain this?

**Comment by rrfrias** [comment]
It appears that the device cannot meet the analog output protection required by the license (CGMS_NEVER/disable analog). There were no changes related to the CGMS requirements specs between android 10 and 11 so it is possible that the differences in behavior that you are seeing are specific to that device. If a device cannot enforce analog output protection, the failure you are seeing is the right behavior (as in android 11). The license request should include the device capabilities and allow you to decide what content (resolution etc) to serve to the device. 

```
2021-05-31 17:10:45.389 3249-3289/? I/WVCdm: [cdm_engine.cpp(313):AddKey] Adding key: session_id = sid9
2021-05-31 17:10:45.458 3249-3289/? I/oemcrypto_tz: [OEMCrypto_TEEInvokeData:469] cmd 1105 return 43
2021-05-31 17:10:45.459 3249-3289/? E/oemcrypto_tz: [OEMCrypto_TEEInvokeData:471] error return 43
2021-05-31 17:10:45.459 3249-3289/? E/oemcrypto_tz: [_oecc105:1208] error return 2b
2021-05-31 17:10:45.459 3249-3289/? E/WVCdm: [crypto_session.cpp(1521):Decrypt] OEMCrypto_DecryptCENC failed: status = 43
2021-05-31 17:10:45.459 3249-3289/? E/WVCdm: Decrypt error in session sid9 during a sample with protected data: 211
2021-05-31 17:10:45.459 6900-6981/com.google.android.exoplayer2.demo I/CCodecBufferChannel: [c2.android.aac.decoder#90] decrypt failed: result=-2011
2021-05-31 17:10:45.459 6900-6981/com.google.android.exoplayer2.demo W/MediaCodec: Log queueSecureInputBuffer error: -2011
2021-05-31 17:10:45.459 4812-5422/? E/chromium: [4812:5422:ERROR:wifi_util.cc(72)] Cannot do SIOCGIWFREQ for wifi: Operation not permitted (1)
2021-05-31 17:10:45.465 6900-6966/com.google.android.exoplayer2.demo E/ExoPlayerImplInternal: Renderer error: index=1, type=audio, format=Format(96k, null, null, audio/mp4a-latm, mp4a.40.2, 104632, und, [-1, -1, -1.0], [2, 44100]), rendererSupport=NO_UNSUPPORTED_DRM
    com.google.android.exoplayer2.ExoPlaybackException: android.media.MediaCodec$CryptoException: Required output protections are not active
        at com.google.android.exoplayer2.BaseRenderer.createRendererException(BaseRenderer.java:359)

```

**Comment by rrfrias** [comment]
> My question is how ExoPlayer detect the analog output from the environment? Can I get the detected result from app?

ExoPlayer does not have a way of being able to check the analog output protections capabilities before the errors occurs. Instead these are reported in the client capabilities in the license request for android 9/P onwards. Does this meet your needs?
