### ISSUE TITLE
Exoplayer playback error(com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors  could read the stream) while trying to play mp4 video

### ISSUE THREAD

**Issue by DharamMaz** [google/ExoPlayer#9003]
Hi ,we are trying to play mp4 video with exoplayer (version 2.14.0 and 2.12.2) and getting below exoplayer error only on single device SamSung S9 (Android 10). While its playing fine on other devices with same or other android versions.

**Error: E/ExoPlayerImplInternal: Playback error
com.google.android.exoplayer2.ExoPlaybackException: Source error**
at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:580)
at android.os.Handler.dispatchMessage(Handler.java:103)
at android.os.Looper.loop(Looper.java:237)
at android.os.HandlerThread.run(HandlerThread.java:67)
**Caused by: com.google.android.exoplayer2.source.UnrecognizedInputFormatException:** None of the available extractors (FlvExtractor, FlacExtractor, WavExtractor, FragmentedMp4Extractor, Mp4Extractor, AmrExtractor, PsExtractor, OggExtractor, TsExtractor, MatroskaExtractor, AdtsExtractor, Ac3Extractor, Ac4Extractor, Mp3Extractor, JpegExtractor) could read the stream.
at com.google.android.exoplayer2.source.BundledExtractorsAdapter.init(BundledExtractorsAdapter.java:92)
at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1027)
at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:417)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:919)

Please help us to fix this.
 **ExoPlayer version number : 2.14.0 and 2.12.2
 Android version :  10
 Android device : SamSung S9**

**Comment by andrewlewis** [comment]
Normally `UnrecognizedInputFormatException`s are not device-specific, as the extractors are part of ExoPlayer. Maybe a different stream is being served to this device, or there's a problem with what data is being loaded.

Do you see the same error when [playing the same stream in the demo app](https://exoplayer.dev/demo-application.html)? Is so, please also provide a link to the media that you are trying to play on this specific device so we can try to reproduce the problem here.

**Comment by DharamMaz** [comment]
@andrewlewis we have tried the same video in demo app and its working fine. so we are checking now in our app.but could not understand why its throwing exception only on one single device while working fine on other devices?

**Comment by andrewlewis** [comment]
Does your app have any customized components (a custom data source or caching/downloading functionality for example)?

**Comment by DharamMaz** [comment]
yes, our app have caching/downloading functionality.

**Comment by andrewlewis** [comment]
It seems quite likely that that device's cache is in a bad state. You could try clearing the cache/storage and playing the video again (but it may be difficult to figure out what went wrong having done that!).

**Comment by DharamMaz** [comment]
but it happens while we are playing the video online or after the fresh install app.

**Comment by DharamMaz** [comment]
@andrewlewis thank you very much. our issue is resolve

**Comment by andrewlewis** [comment]
Thanks. I will close this. If you learned anything that might help other ExoPlayer users please do post a quick summary here!
