### ISSUE TITLE
How replace a frame by a bitmap file on TextureView before playout

### ISSUE THREAD

**Issue by minhkstn** [google/ExoPlayer#9007]
I created a TextureView to display ExoPlayer instance. The function `onSurfaceTextureUpdated` will be called whenever a new frame is available. In this function, I can access the frame in `bitmap` type from `textureView.getBitmap()` as follows

```
public void onSurfaceTextureUpdated(SurfaceTexture surfaceTexture) {
     frame_idx ++;
     if (frame_idx == 100) {
          Bitmap bmp = textureView.getBitmap();
          Bitmap modifiedFame = getModifiedFrame(bmp);
          // From here, replace the original frame by newFrame and play newFrame on screen.
     }
}
```

I want to modify the 100th frame in `getModifiedFrame(Bitmap bmp)` that returns another bitmap file, namely `modifiedFame` and ExoPlayer plays `modifiedFame` instead of the original frame.

Is it possible to do it in function `onSurfaceTextureUpdated` and how? If not, which file in ExoPlayer should I modify?
Thanks!

**Comment by andrewlewis** [comment]
This use case is quite custom so I'm afraid we can't spend time giving detailed support. For what it's worth: I suspect that by the time `onSurfaceTextureUpdated` has been called it's too late to "intercept" the frame you want to replace (it may be shown to the user), and I'm also not sure that it's possible to render to the same texture as the codec. If you don't need perfect timing you could do just show/hide a separate image view positioned on top of the texture view (and possibly also customize the video renderer so it doesn't render the frame(s) you want to replace). If you do need perfect timing, I would follow an approach like gldemo where you can do arbitrary GL processing on the texture before it's shown to the user (see also #5860 and #8468).
