### ISSUE TITLE
RTSP: Parsing profile and level from SPS

### ISSUE THREAD

**Issue by EduardAblekimov** [google/ExoPlayer#9010]
### [REQUIRED] Use case description
My RTSP server's SDP doesn't provide `profile-level-id`. According to RFC, it is not mandatory parameter and it can be parsed from `sprop-parameter-sets` (SPS) instead

### Proposed solution
If `sprop-parameter-sets` takes the following value - `67 4d 00 2a 96 35 40 f0 04 4f cb 37 01 01 01 02`, then `profile-level-id` hexa string would be `4d002a`.

**Comment by andrewlewis** [comment]
@claincly Please take a look. I'd guess we can use `AvcConfig.parse(...)` to get the required information.
