### ISSUE TITLE
RTSP H.264 playback artifacts

### ISSUE THREAD

**Issue by EduardAblekimov** [google/ExoPlayer#9011]
I have a camera that lies on my local network. It streams using RTSP, H.264 Main Profile. When I play from the camera, the video is not loaded properly, only the upper part of it.

In `SampleQueue.format(Format)`, format's codecs is `avc1.4d002a`, which is H.264 Main Profile.

Unfortunately I cannot share URI of the media source, since its located on my local network.

[Screencast of the issue](https://drive.google.com/uc?id=1exwBS21puMqWV84glGqj7ullvuJTgsHA). I physically moved the camera so you can see it in action.

## Player Initialization
```kotlin
        val mediaSource: MediaSource = RtspMediaSource.Factory()
            .createMediaSource(MediaItem.fromUri(fullUrl))
        val player = SimpleExoPlayer.Builder(requireContext()).build()
        player.addAnalyticsListener(EventLogger(null))
        viewPlayer.player = player
        player.setMediaSource(mediaSource)
        player.prepare()
```

## SDP from RTSP DESCRIBE response:
```
v=0
o=- 3831122695 3831122695 IN IP4 192.168.1.114
c=IN IP4 192.168.1.114
t=0 0
a=tool:my-tool
a=recvonly
a=type:broadcast
a=charset:UTF-8
a=control:*
m=video 0 RTP/AVP 96
a=rtpmap:96 H264/90000
a=fmtp:96 packetization-mode=1;sprop-parameter-sets=Z00AKpY1QPAET8s3AQEBAg==,aO48gA==
a=control:video
```

## Xml
```XML
    <FrameLayout
        android:id="@+id/layout_preview"
        android:layout_width="match_parent"
        android:layout_height="180dp"
        android:layout_marginTop="20dp"
        android:background="@color/stream_detail_preview_bg"
        android:foreground="?android:attr/selectableItemBackground">

        <com.google.android.exoplayer2.ui.StyledPlayerView
            android:id="@+id/view_player"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_gravity="center" />
    </FrameLayout>
```

**Comment by claincly** [comment]
The SPS -> profile level fix should be in GH very shortly.

You did hard code the profile-level-id right? Without the source it'd be immensely difficult for us to know what's causing the issue. If the profile-level-id is set correctly, there are two possibilities that struct me

1. (unlikely) You are using RTP/UDP and many packets are dropped. You can take a look at the log, do you see anything like "Received RTP packet with unexpected sequence number"? And also, what resolution/bitrate are you expecting?
2. (also somewhat unlikely) The local decoder does not actually support playback the specific H264 stream.

**Comment by EduardAblekimov** [comment]
> Without the source it'd be immensely difficult for us to know what's causing the issue

These are my local changes:

I set session name in session description to some arbitrary value

I split SDP lines by LF, not by CRLF

Server doesn't send rtp-info in the PLAY response. Since its livestream, I just hardcode it:
`@Nullable String rtpInfoString = "url=rtsp://192.168.1.114/videoMain/video;seq=0;rtptime=0";`

Hardcoded `profile-level-id`:
```java
/* checkArgument(fmtpAttributes.containsKey(PARAMETER_PROFILE_LEVEL_ID));
    String profileLevel = checkNotNull(fmtpAttributes.get(PARAMETER_PROFILE_LEVEL_ID)); */
    formatBuilder.setCodecs(H264_CODECS_PREFIX + "4d002a");
```

>You are using RTP/UDP and many packets are dropped. You can take a look at the log, do you see anything like "Received RTP packet with unexpected sequence number"? And also, what resolution/bitrate are you expecting?

No logs, packetSequenceNumber = expectedSequenceNumber.
Video settings:
```json
"video": {
        "codec": "h264",
        "width": 1920,
        "height": 1080,
        "fps": 25,
        "gop_size": 50,
        "profile": "MAIN",
        "bitrate": {
            "mode": "vbr",
            "min_quality": 0,
            "max_quality": 80,
            "max_bitrate": 4000
        }
    }
```

**Comment by claincly** [comment]
Thanks! 

For hardcoding RTP-Info though, ExoPlayer doesn't require a RTP-Info header, what's the reason of hardcoding it, maybe to force the extractor start from sequence number 0 and timestamp 0? That is unnecessary IMO.

The RTSP stream plays in the end, so there's no problem in RTSP setup. If there's no lost/out-of-order packet, RTP reception seems to be doing a good job also.

Could you try using a emulator (on your computer), or try with other devices?

**Comment by EduardAblekimov** [comment]
> For hardcoding RTP-Info though, ExoPlayer doesn't require a RTP-Info header, what's the reason of hardcoding it, maybe to force the extractor start from sequence number 0 and timestamp 0? That is unnecessary IMO.

Hmm, it's crashing without my hardcoded value.

This is the piece of code where it crashes. `trackUrisWithTiming` is empty:
```java
        RtpLoadInfo loadInfo = selectedLoadInfos.get(i);
        if (!trackUrisWithTiming.contains(loadInfo.getTrackUri())) {
          playbackException =
              new RtspPlaybackException(
                  "Server did not provide timing for track " + loadInfo.getTrackUri());
          return;
        }
```

> Could you try using a emulator (on your computer), or try with other devices?

On emulator its the same problem, except the 'black' area is [now green](https://i.imgur.com/yZ2bxgJ.png). There is also this log:
```
E/ACodec: [OMX.google.h264.decoder] setPortMode on output to DynamicANWBuffer failed w/ err -1010
I/ACodec: codec does not support config priority (err -1010)
```

On my samsung there is no such log, but it also doesn't use `OMX.google.h264.decoder`, but `OMX.qcom.video.decoder.avc`

**Comment by claincly** [comment]
The `ACodec` log is expected, no big deal.

I would try,

- To make sure no packet is lost, print out the sequence numbers of the H264 packets on L113 of `RtpH264Reader`
- Dump the received media using tools like [openRTSP](http://www.live555.com/openRTSP/) and check if it plays on ExoPlayer
- Just for sure, check if the video plays nicely with VLC.
- Dump a few (~100) RTP packet contents as hex strings. You can insert this after `RtpExtractor` L137

```java
    byte[] data = new byte[bytesRead];
    rtpPacketDataBuffer.readBytes(data, 0, bytesRead);
    System.out.println(Util.toHexString(data));

    rtpPacketScratchBuffer.setPosition(0);
    rtpPacketScratchBuffer.setLimit(bytesRead);
```

**Comment by EduardAblekimov** [comment]
Aight, will try!

> Just for sure, check if the video plays nicely with VLC.

Already tried, its playing nicely in VLC.

**Comment by EduardAblekimov** [comment]
> To make sure no packet is lost, print out the sequence numbers of the H264 packets on L113 of RtpH264Reader

Every sequence number == last sequence number + 1, so i guess no lost packets.

> Dump the received media using tools like openRTSP and check if it plays on ExoPlayer

Dumped received media via ffmpeg to .mp4 file by invoking that 
`ffmpeg -i rtsp://admin:12345@192.168.1.114/videoMain -vcodec copy -acodec copy -f mp4 -y video.mp4`. 
Put it into assets and did a playback from it - all good, picture perfect.

> Just for sure, check if the video plays nicely with VLC.

As mentioned earlier, yes, all good.

> Dump a few (~100) RTP packet contents as hex strings. You can insert this after RtpExtractor L137

First ~50 packets were throwing `IndexOutOfBoundException`, but then it started to produce hex strings.

I put a count as a global int variable and then increment it every time after i convert bytes to hex strings. Seems like multithreading issue, but it increments by 10-14 everytime. Anyway, I dumped ~175 packets:


[RTSPHexaPackets.txt](https://github.com/google/ExoPlayer/files/6600085/RTSPHexaPackets.txt)

**Comment by EduardAblekimov** [comment]
@claincly Do you have any news on the topic? Is it in progress/on hold/low prio?

**Comment by claincly** [comment]
No updates at the moment, sorry.

**Comment by EduardAblekimov** [comment]
Hey @claincly 
I am curious if there is any work planned to do on the topic? Or maybe some ETA? Its important to me to make a decision internally.

Meanwhile I found something else, it might be connected, might not:
When I am starting playback, my app crashes in ~4 minutes with out of memory.
[Screenshot of Android Studio Monitor](https://i.imgur.com/2JcrfgE.png). Playback is started whenever CPU spiked to ~20%. Then I do nothing, but memory slowly raises and then crashes at 512MB.

**Comment by claincly** [comment]
Hey, thanks for asking.

We don't have a plan on this topic at the moment. I will take a look at the memory issue. Would you mind specifying what video format you are playing? H264 of what kind of bitrate/resolution?

**Comment by EduardAblekimov** [comment]
Same as I wrote above:

```
"video": {
        "codec": "h264",
        "width": 1920,
        "height": 1080,
        "fps": 25,
        "gop_size": 50,
        "profile": "MAIN",
        "bitrate": {
            "mode": "vbr",
            "min_quality": 0,
            "max_quality": 80,
            "max_bitrate": 4000
        }
    }
```

**Comment by claincly** [comment]
That does not look too bad, I tried to play some H264+AC3 video (~32Mbps) for a while and here's how the memory usage looked like, there are drops (GC) here and there. Not sure the memory issue is due to the video does not play properly?

<img width="1456" alt="Screen Shot 2021-06-21 at 2 00 54 PM" src="https://user-images.githubusercontent.com/84200018/122766422-6a4a1000-d299-11eb-8fd7-e93a99ba4383.png">

I would ask again if there is a way to tap into your stream, it is very hard to pinpoint the issue otherwise.

**Comment by ojw28** [comment]
Closing because there's not a lot we can do to investigate further without access to the stream.
