### ISSUE TITLE
ExoPlayer throws ExoPlaybackException when a live video ends.

### ISSUE THREAD

**Issue by wangzhe890703** [google/ExoPlayer#9013]
ExoPlayer throws **ExoPlaybackException** when a live video ends.
Attached an error log
`E/ExoPlayerImplInternal: Playback error com.google.android.exoplayer2.ExoPlaybackException: Source error at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:554) at android.os.Handler.dispatchMessage(Handler.java:102) at android.os.Looper.loop(Looper.java:223) at android.os.HandlerThread.run(HandlerThread.java:67) Caused by: com.google.android.exoplayer2.source.hls.playlist.HlsPlaylistTracker$PlaylistStuckException at com.google.android.exoplayer2.source.hls.playlist.DefaultHlsPlaylistTracker$MediaPlaylistBundle.processLoadedPlaylist(DefaultHlsPlaylistTracker.java:667) at com.google.android.exoplayer2.source.hls.playlist.DefaultHlsPlaylistTracker$MediaPlaylistBundle.onLoadCompleted(DefaultHlsPlaylistTracker.java:547) at com.google.android.exoplayer2.source.hls.playlist.DefaultHlsPlaylistTracker$MediaPlaylistBundle.onLoadCompleted(DefaultHlsPlaylistTracker.java:462) at com.google.android.exoplayer2.upstream.Loader$LoadTask.handleMessage(Loader.java:481) at android.os.Handler.dispatchMessage(Handler.java:106) at android.os.Looper.loop(Looper.java:223)  at android.os.HandlerThread.run(HandlerThread.java:67) `

The bug is reproducible consistently.

Steps to reproduce:
1. Start a live video using RTMP protocol
2. Play the live video using ExoPlayer
3. End video stream from the broadcaster side

- ExoPlayer version number: 2.13.3
- Android version: 11
- Android device: Google - Pixel 3a

We also attached a manifest file to help debug. Please let us know if the manifest file has any issue.
`#EXTM3U
#EXT-X-VERSION:4
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-ALLOW-CACHE:NO
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-TARGETDURATION:3
#EXT-X-PROGRAM-DATE-TIME:2021-05-27T14:07:24Z
#EXTINF:2.002000,no-desc
Fragments(video=6030,format=m3u8-aapl)
#EXTINF:2.002000,no-desc
Fragments(video=186210,format=m3u8-aapl)
#EXTINF:2.002000,no-desc
Fragments(video=366390,format=m3u8-aapl)
#EXTINF:2.002000,no-desc
Fragments(video=546570,format=m3u8-aapl)
#EXTINF:1.969000,no-desc
Fragments(video=726750,format=m3u8-aapl)
#EXTINF:2.002000,no-desc
Fragments(video=903960,format=m3u8-aapl)
#EXTINF:2.002000,no-desc
Fragments(video=1084140,format=m3u8-aapl)
#EXTINF:2.002000,no-desc
Fragments(video=1264320,format=m3u8-aapl)
#EXTINF:2.002000,no-desc
Fragments(video=1444500,format=m3u8-aapl)
#EXTINF:2.002000,no-desc
Fragments(video=1624680,format=m3u8-aapl)
#EXTINF:2.002000,no-desc
Fragments(video=1804860,format=m3u8-aapl)
#EXTINF:2.002000,no-desc
Fragments(video=1985040,format=m3u8-aapl)
#EXTINF:2.002000,no-desc
Fragments(video=2165220,format=m3u8-aapl)
#EXTINF:2.002000,no-desc
Fragments(video=2345400,format=m3u8-aapl)
#EXTINF:2.002000,no-desc
Fragments(video=2525580,format=m3u8-aapl)
#EXTINF:2.002000,no-desc
Fragments(video=2705760,format=m3u8-aapl)
#EXTINF:2.002000,no-desc
Fragments(video=2885940,format=m3u8-aapl)
#EXTINF:2.002000,no-desc
Fragments(video=3066120,format=m3u8-aapl)
#EXTINF:2.002000,no-desc
Fragments(video=3246300,format=m3u8-aapl)
#EXTINF:2.002000,no-desc
Fragments(video=3426480,format=m3u8-aapl)
#EXTINF:2.002000,no-desc
Fragments(video=3606660,format=m3u8-aapl)
#EXTINF:1.968000,no-desc
Fragments(video=3786840,format=m3u8-aapl)
#EXTINF:2.002000,no-desc
Fragments(video=3963960,format=m3u8-aapl)
#EXTINF:2.002000,no-desc
Fragments(video=4144140,format=m3u8-aapl)
#EXTINF:2.002000,no-desc
Fragments(video=4324320,format=m3u8-aapl)
#EXTINF:2.002000,no-desc
Fragments(video=4504500,format=m3u8-aapl)
#EXTINF:2.002000,no-desc
Fragments(video=4684680,format=m3u8-aapl)
#EXT-X-ENDLIST`

**Comment by andrewlewis** [comment]
It looks like the 'playlist stuck' case only happens if `#EXT-X-ENDLIST` isn't present, but it is there in the snapshot you provided. Are you sure it's being added to the playlist soon enough to avoid the player detecting a stuck playlist? See also: https://github.com/google/ExoPlayer/blob/6e8af81/library/hls/src/main/java/com/google/android/exoplayer2/source/hls/playlist/DefaultHlsPlaylistTracker.java#L706

**Comment by wangzhe890703** [comment]
@andrewlewis Thanks for your response! Is there an explicit requirement from the ExoPlayer side to define "how fast" the end tag should be added to the playlist?

**Comment by andrewlewis** [comment]
Just reading the code I linked to above, it looks like the error condition requires that the playlist hasn't changed for 3.5 * the target duration (by default).

@christosts can maybe confirm/correct me on this or provide further information.

**Comment by jiangyurong609** [comment]
@andrewlewis thanks for the quick response, what's the timeout threshold for player to report playlist stuck? server may not know the content ended until user tells so, or there can be networking issue during live stream, therefore it's very common  #EXT-X-ENDLIST could miss in the playlist for a long time, which could lead suboptimal playback experience. But I think player could handle this better instead of reporting error quickly? In addition, is the playlistStuckTargetDurationCoefficient parameter controllable by player settings? Thanks

**Comment by andrewlewis** [comment]
> what's the timeout threshold for player to report playlist stuck?

3.5 * target duration by default (please see my previous message).

> server may not know the content ended until user tells so, or there can be networking issue during live stream, therefore it's very common #EXT-X-ENDLIST could miss in the playlist for a long time, which could lead suboptimal playback experience

I think the component that's generating the HLS stream needs to handle this case, for example by filling in media segments if there's nothing from upstream. For what it's worth I don't think we've seen this issue reported commonly on this tracker.

> But I think player could handle this better instead of reporting error quickly?
> In addition, is the playlistStuckTargetDurationCoefficient parameter controllable by player settings?

If you need to handle this case differently in the player, you could try customizing the behavior by passing your own `HlsPlaylistTracker.Factory` when creating the `HlsMediaSource`.
