### ISSUE TITLE
Disable Ima Sdk PlaybackSpeed

### ISSUE THREAD

**Issue by nebyan** [google/ExoPlayer#9018]
Hello Exo Team
I am using the Exoplayer Ima Sdk. I am changing the playback speed of exoplayer within the application. When Ima ads start playing, it plays with the playbackspeed I set last. Can we make the ad content play with default playback speed(1.0).

Exoplayer Version Number : Any Version
Android Devices: Any Android devices

**Comment by ojw28** [comment]
We agree that ads should play at 1x speed, regardless of speed at which content is being played.

**Comment by alarochelle** [comment]
Will this get fixed soon?
That's pretty major in our case. We can manually set the playback speed back to 1 whenever an ad starts playing, but it's honestly not perfect. Would probably be a lot better if it was handled on your side.

**Comment by ojw28** [comment]
This is fixed in 2.17.0, which will be released shortly.
