### ISSUE TITLE
com.google.android.exoplayer2.ExoPlaybackException: Source error

### ISSUE THREAD

**Issue by nassdk** [google/ExoPlayer#9022]
Hello, dears! I'm new at exo player and in general in working with media, but i was searching for answer for my problem for 2 days already, so i decided to ask here.

I'm trying to play video from VKontakte (vk.com) and getting source error every time.

When i'm trying to play test video like https://storage.googleapis.com/exoplayer-test-media-0/BigBuckBunny_320x180.mp4 , video is playing. 

Example of video url which i'm trying to play - https://vk.com/video_ext.php?oid=92093600&id=456239925&hash=a388b8ddc008e840&__ref=vk.api&api_hash=1614108141eb9de7d2afdf5e0e1a_GI3DGOJXHE3Q

I guess something wrong with video format, please, give me some kind of direction what i should to do. Thanks!

`   
 override fun prepareUi() {

        _viewBinding = ScreenVideoDetailsBinding.bind(requireView())
        mPlayer = SimpleExoPlayer.Builder(requireContext()).build()

        viewBinding.playerView.player = mPlayer

        mPlayer = SimpleExoPlayer.Builder(requireContext()).build()

        viewBinding.playerView.player = mPlayer

        val mediaItem = createMediaItem()

        mPlayer?.addMediaItem(mediaItem)
        mPlayer?.prepare()
        mPlayer?.playWhenReady = true
    }

    private fun createMediaItem(): MediaItem {
        val mediaUri = Uri.parse(url)
        return MediaItem.fromUri(mediaUri)
    }
}
`

`E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:580)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:246)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (FlvExtractor, FlacExtractor, WavExtractor, FragmentedMp4Extractor, Mp4Extractor, AmrExtractor, PsExtractor, OggExtractor, TsExtractor, MatroskaExtractor, AdtsExtractor, Ac3Extractor, Ac4Extractor, Mp3Extractor, JpegExtractor) could read the stream.`

**Comment by claincly** [comment]
The link you posted does not resolve to a video file, but rather a webpage.

**Comment by nassdk** [comment]
> The link you posted does not resolve to a video file, but rather a webpage.

So, can i get some workaround with that link, or it is impossible to resolve video?

**Comment by claincly** [comment]
You have to make sure the link "points" to a media file. Like, if I click on the link, I can download the video directly. 

Currently it points to a webpage that already contains a player. If you want to play this with ease, webview may be a better option.

**Comment by nassdk** [comment]
> Currently it points to a webpage that already contains a player. If you want to play this with ease, webview may be a better option.

Ohh(( Thanks for clarifying!
