### ISSUE TITLE
Is Exoplayer capable of handling VAST 4.1? 

### ISSUE THREAD

**Issue by chris-sloan** [google/ExoPlayer#9027]
We're looking to update our existing ads implementation and currently handle VAST Version 4.1 and VAST 2.0. 

I can see that VAST 2.0 works when I pass url as the `ad_tag_uri` in the demo app, and I can see tha the samples given in the demo app are all VAST 3.  I don't have access to a url which will return me a VAST 4.1 file and so can't test this so easily. 

Before I go through the manual process of making a VAST 4.1 file, does Exoplayer support it?
Many Thanks.

**Comment by andrewlewis** [comment]
The IMA extension exposes VAST loading support from the IMA SDK (and I don't think we additional limitations), so please check their compatibility documentation: https://developers.google.com/interactive-media-ads/docs/sdks/android/client-side/compatibility
