### ISSUE TITLE
Unable to show close-captions after clearing selection override

### ISSUE THREAD

**Issue by nishantkp** [google/ExoPlayer#9029]
I have closed captions in the Live DASH manifest.

I am trying following to enable and disable closed captions,

```java
// Call this to select any track
static void selectTrack(@NonNull DefaultTrackSelector trackSelector, @NonNull Track track) {
        MappingTrackSelector.MappedTrackInfo mappedTrackInfo = trackSelector.getCurrentMappedTrackInfo();
        DefaultTrackSelector.ParametersBuilder builder = trackSelector.buildUponParameters();
        DefaultTrackSelector.SelectionOverride override = new DefaultTrackSelector.SelectionOverride(track.getGroupIndex(), track.getTracks(), C.SELECTION_REASON_MANUAL, 0);
        builder.setSelectionOverride(track.getRenderIndex(), mappedTrackInfo.getTrackGroups(track.getRenderIndex()), override);
        trackSelector.setParameters(builder.build());
    }

// Call this to clear track selection
static void clearTrackSelection(@NonNull DefaultTrackSelector trackSelector, @NonNull Track track) {
        MappingTrackSelector.MappedTrackInfo mappedTrackInfo = trackSelector.getCurrentMappedTrackInfo();
        DefaultTrackSelector.ParametersBuilder builder = trackSelector.buildUponParameters();
        builder.clearSelectionOverrides(track.getRenderIndex());
        builder.setRendererDisabled(track.getRenderIndex(), true);
        trackSelector.setParameters(builder.build());
    }
```

Here `Track` object contains render index, group index, track name, and a bunch of other metadata.

I am calling `selectTrack()` to set closed-captions and `clearTrackSelection()` method to clear that selection. 
After clearing text track selection with `clearTrackSelection()`, I am not able to show close-cations again with `selectTrack()` method.

Do you know why that is?

**Comment by ojw28** [comment]
Your two methods are not symmetric to one another:

1. `selectTrack` only sets the override. It does not enable the renderer
2. `clearTrackSelection` clears the override and disables the renderer

As a result, after you clear and then select, the renderer is still disabled.

You should delete the `builder.setRendererDisabled(track.getRenderIndex(), true);` line from your `clearTrackSelection` method, or add a `builder.setRendererDisabled(track.getRenderIndex(), false);` line to your `selectTrack` method.
