### ISSUE TITLE
Exoplayer live stream in android auto.

### ISSUE THREAD

**Issue by ghost** [google/ExoPlayer#9033]
Hello,
I want to know that how we can play customize exoplayer in android auto app. Also can we run HLS stream in exoplayer using android auto ? I have already developed mobile app using exoplayer and it is possible to customize it in mobile version but I didn't get any example or code in which we can use exoplayer in android auto or how to code it so that we can play live stream in android auto using exoplayer. need a help regarding this problem. Can anyone have solution on this please update here.

**Comment by ojw28** [comment]
There's some fairly good guidance on how to make an app compatible with Android Auto in [this issue](https://github.com/google/ExoPlayer/issues/8561). I'd suggest you use that as a starting point.
