### ISSUE TITLE
Questions about FirstFrame render time

### ISSUE THREAD

**Issue by iblh** [google/ExoPlayer#9034]
Hello, the following content shows my exploration of the rendering time of the first frame. There are some questions about it, I would very much appreciate it if someone could reply to me or give me some suggestions.

> I wanna understand how the firstframe render time been calculated and which function in code implements it. Seems it's related to `player.setMediaItem`, but I have no clues. The following describes my current thoughts but still need more help.

The version of ExoPlayer I used is 2.14.0. I would like to figure out how the ExoPlayer calculates the first frame render time.
Therefore, I have added an analytics event listener to the player, the code is like below:
```java
player.addAnalyticsListener(new AnalyticsListener() {
@Override
public void onRenderedFirstFrame(EventTime eventTime, Object output, long renderTimeMs) {
    Log.d("FirstFrame", "render time: " + renderTimeMs );
}
```

The media uri I used is `https://media.vued.vanthink.cn/CJ7%20-%20Trailer.mp4`, and the integration code is:
```java
SimpleExoPlayer player = new SimpleExoPlayer.Builder(this).build();
playerView = findViewById(R.id.exoplayer_view);
playerView.setPlayer(player);

button.setOnClickListener(new View.OnClickListener() {
    @Override
    public void onClick(View v) {
        Uri playUri = Uri.parse("https://media.vued.vanthink.cn/CJ7%20-%20Trailer.mp4");
        MediaItem mediaItem = MediaItem.fromUri(playUri);
        player.setMediaItem(mediaItem);
        player.prepare();
    }
});
```

After that, every time I click the button, I will get the FirstFrame render time. I have tested it several times and got a set of render time, such as: `[33524120, 34405862, 34405891, ...]`

And then, I have browsed the ExoPlayer code and found the render function process is:
```
render() 
-> DecoderVideoRenderer.java
	-> drainOutputBuffer()
	-> processOutputBuffer()
	-> renderOutputBuffer()
	-> maybeNotifyRenderedFirstFrame()
-> VideoRendererEventListener.java
	-> renderedFirstFrame()
	-> onRenderedFirstFrame()
```

In the `renderedFirstFrame()`, it define the `renderTimeMS`
```
public void renderedFirstFrame(Object output) {
  if (handler != null) {
    // TODO: Replace this timestamp with the actual frame release time.
    long renderTimeMs = SystemClock.elapsedRealtime();
    handler.post(() -> castNonNull(listener).onRenderedFirstFrame(output, renderTimeMs));
  }
}
```

So far, I understand the `renderTimeMS` is come from `SystemClock.elapsedRealtime()`. But after I check the [SystemClock - docs](https://developer.android.com/reference/android/os/SystemClock#elapsedRealtime()), it said that the `elapsedRealtime` returns milliseconds since **boot**. That's what bothers me, the render time I have got obviously indicates the time is related to the media loading part and the code shows it's the time since boot.

Very thanks for your time to read this!

**Comment by claincly** [comment]
Please don't mind my question, but `33524120` milliseconds is about nine and half hours, that does look like the time since boot?

**Comment by iblh** [comment]
> Please don't mind my question, but `33524120` milliseconds is about nine and half hours, that does look like the time since boot?

@claincly Thanks for your reply.  Actually, the `33524120` milliseconds is also a weird part of the results.  The time will be displayed in the console after I click the button (setMediaItem). 
For instance, after I boot the app and click the button 5 times, the time I got is `[33500000, 34400000, 34300000, 33300000, 35200000]`. These numbers are not an increasing law, but more like the time it takes to load the media each time (they are in a specific range). In addition,  I am not sure whether the unit is milliseconds, it is more reasonable if it is nanoseconds. I still very confused about its logic, thanks again for your time :)
 
I have attached the `OnClickListener` code:
```
SimpleExoPlayer player = new SimpleExoPlayer.Builder(this).build();
playerView = findViewById(R.id.exoplayer_view);
playerView.setPlayer(player);

button.setOnClickListener(new View.OnClickListener() {
    @Override
    public void onClick(View v) {
        Uri playUri = Uri.parse("https://media.vued.vanthink.cn/CJ7%20-%20Trailer.mp4");
        MediaItem mediaItem = MediaItem.fromUri(playUri);
        player.setMediaItem(mediaItem);
        player.prepare();
    }
});
```

**Comment by andrewlewis** [comment]
> That's what bothers me, the render time I have got obviously indicates the time is related to the media loading part and the code shows it's the time since boot.

I think you are seeing the number of milliseconds since the device (not app) booted, sampled at the time when ExoPlayer rendered the frame, which can depend on media loading time (longer loading => longer delay before the frame is rendered => more time elapsed since boot).

The TODO in the code snippet relates to the following detail: ExoPlayer (normally) schedules frames to be rendered a few milliseconds in advance via [`releaseOutputBuffer`](https://developer.android.com/reference/android/media/MediaCodec#releaseOutputBuffer(int,%20long)), and `renderTimeMs` is not taking into account the scheduled delay. By the way, you mentioned `DecoderVideoRenderer.java` but this is only used with decoder extensions. (Unless you are using a decoder extension deliberately I suspect you might mean `MediaCodecVideoRenderer`).

> For instance, after I boot the app and click the button 5 times, the time I got is [33500000, 34400000, 34300000, 33300000, 35200000]. These numbers are not an increasing law, but more like the time it takes to load the media each time (they are in a specific range). In addition, I am not sure whether the unit is milliseconds, it is more reasonable if it is nanoseconds. I still very confused about its logic, thanks again for your time :)

Could you describe exactly where you are logging the numbers? If you are logging `renderTimeMs` in an analytics listener then this looks very strange. I tried logging `renderTimeMs` in the demo app's `EventLogger.onRenderedFirstFrame` and played a video a few times and saw increasing values a few seconds apart as expected.

**Comment by iblh** [comment]
@andrewlewis Thanks for your answer. I have attached my Android App([BoMediaPlayer.zip](https://github.com/google/ExoPlayer/files/6653557/BoMediaPlayer.zip)) so that you could run it for the test.

BTW, The `DecoderVideoRenderer` I mentioned is wrong, I did mean to `MediaCodecVideoRenderer`.

Apart from the above, could you introduce in detail which part of the code is used to calculate the rendered time of the first frame? Thank you so much!

**Comment by iblh** [comment]
At present I found the logic is:
```shell
	render() 
-> MediaCodecRenderer.java
	-> drainOutputBuffer()
-> MediaCodecVideoRenderer.java
	-> processOutputBuffer()
	-> renderOutputBuffer(codec, bufferIndex, presentationTimeUs);
	-> maybeNotifyRenderedFirstFrame()
-> VideoRendererEventListener.java
	-> renderedFirstFrame()
	# long renderTimeMs = SystemClock.elapsedRealtime();
	-> onRenderedFirstFrame(renderTimeMs)
```
I didn't find when is the start time of SystemClock, if it is the time when the virtual machine starts as mentioned above, then this first frame rendered time will be very strange. 
Because as far as I know, the first frame rendered time should be the time when the video is ready to play the first frame after the video is loaded, and irrelevant with the system startup time or APP startup Time.
