### ISSUE TITLE
Ffmpeg exstension not build with ndk r22

### ISSUE THREAD

**Issue by umerov1999** [google/ExoPlayer#9039]
NDK r22 -The assembly occurs with the error Recompile with -FPIC on the ARMV8-A64, but Armv7 is going. NDK r21 collects everything without errors

Сборка происходит с ошибкой recompile with -FPIC на armv8-a64, но armv7 собирается. ndk21 собирает всё без ошибок

**Comment by andrewlewis** [comment]
The [build instructions](https://github.com/google/ExoPlayer/tree/release-v2/extensions/ffmpeg) work fine for me on Android NDK r22b (22.1.7171670) on Mac, testing decoding using FLAC via the FFmpeg extension in the ExoPlayer demo app, release 2.14.0.

Please try again using r22b on the latest release. If it still fails please provide the configuration/build logs from ffmpeg compilation.
