### ISSUE TITLE
Inquiries about streaming playback buffer time

### ISSUE THREAD

**Issue by yyms3275** [google/ExoPlayer#9040]
I want to optimize the start buffer time it takes to play a streaming video. Some videos can start quickly, but some videos take 5 to 7 seconds or more than 10 seconds to buffer. I want to know how to solve it. I use the code below

```
DefaultLoadControl loadControl = new DefaultLoadControl.Builder()
                    .setAllocator(new DefaultAllocator(true, 16))
                    .setBufferDurationsMs(500, 500, 500, 500)
                    .setTargetBufferBytes(200 * 64 * 1024)
                    .setPrioritizeTimeOverSizeThresholds(false)
                    .setBackBuffer(2000, false)
                    .createDefaultLoadControl();

final long defaultMaxInitialBitrate = Integer.MAX_VALUE;

final DefaultBandwidthMeter defaultBandwidthMeter = new DefaultBandwidthMeter
                    .Builder(this)
                    .setInitialBitrateEstimate(defaultMaxInitialBitrate)
                    .build();

AdaptiveTrackSelection.Factory trackSelectionFactory = new AdaptiveTrackSelection.Factory();
DefaultTrackSelector trackSelector = new DefaultTrackSelector(this, trackSelectionFactory);

exoPlayer = new SimpleExoPlayer.Builder(this)
                    .setTrackSelector(trackSelector)
                    .setBandwidthMeter(defaultBandwidthMeter)
                    .setLoadControl(loadControl)
                    .build();
```

* I play combined video and sound media sources for streaming.

```
MediaSource videoSource = new ProgressiveMediaSource.Factory(new DefaultHttpDataSourceFactory()).createMediaSource(Uri.parse(video));

MediaSource audioSource = new ProgressiveMediaSource.Factory(new DefaultHttpDataSourceFactory()).createMediaSource(Uri.parse(audio));

return new MergingMediaSource(videoSource, audioSource);
```

**Comment by fgl27** [comment]
why `16` in `DefaultAllocator`?

I don't think a small value here help, you are using a value that is far from the default value that is `65536` see https://exoplayer.dev/doc/reference/constant-values.html#com.google.android.exoplayer2.C.DEFAULT_BUFFER_SEGMENT_SIZE try to use the default here.

you don't need to call `setTrackSelector` if you aren't making changes to the `trackSelector`, as `AdaptiveTrackSelection` is the default.

Setting a low value for `bufferForPlaybackMs` (low be 250 to 500) will help to start faster, but the other values are too low see here 
https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/DefaultLoadControl.Builder.html#setBufferDurationsMs(int,int,int,int) 

I set it base on device ram to avoid using a time value and cause low device memory error, I use 1/20 of the device ram, the `int buffer` value is 250, I use this fun to start it:

```java
    static DefaultLoadControl getLoadControl(int buffer, int DeviceRam) {
        return new DefaultLoadControl.Builder()
                .setAllocator(new DefaultAllocator(true, C.DEFAULT_BUFFER_SEGMENT_SIZE))
                .setBufferDurationsMs(
                        60000, //minBufferMs
                        36000000, //maxBufferMs... technically infinity setTargetBufferBytes controls it
                        buffer, //bufferForPlaybackMs
                        buffer + 1000 //bufferForPlaybackAfterRebufferMs
                )
                .setTargetBufferBytes(DeviceRam)
                .build();
    }
```

for example `minBufferMs` and `maxBufferMs` if they are too low will cause rebuffers do to `Player.STATE_BUFFERING` with will use `bufferForPlaybackAfterRebufferMs` and that is also too low with can trigger again `Player.STATE_BUFFERING` and again and again... with is an "rebuffer loop" (5 to 7 seconds that you have may be this rebuffer loop) as the values are not set properly, setting the proper values here is key to have a proper playback start.

Check those see what improves and remember things that needed to be downloaded from the internet may suffer from internet random lags.

**Comment by yyms3275** [comment]
Thank you for answer. I have modified the code as below. Still, the normal video loads quickly, while the video below loads too slowly. Is it because of the long play time? When opened in a browser, it starts quickly, but when loaded in exoPlayer, it takes a few seconds to load.

```
DefaultLoadControl loadControl = new DefaultLoadControl.Builder()
.setAllocator(new DefaultAllocator(true, C.DEFAULT_BUFFER_SEGMENT_SIZE))
.setBufferDurationsMs(50000, 50000, 2500, 5000)
.createDefaultLoadControl();

exoPlayer = new SimpleExoPlayer.Builder(this).setLoadControl(loadControl).build();
```

https://youtu.be/p2fxv3PAtLU

**The important thing is that I take the video and audio separately and put them together to play.**

**Comment by fgl27** [comment]
BTW `maxBufferMs` should be bigger then `minBufferMs` just look for the documentation and try to understand the description of it value, min is minimum possible max the maximum, the player will try to keep the buffer on that constrain between min and max.

You can't compare the way youtube site work with the way you are trying to play those links.

first youtube use an adaptive playback system, if you are using the video/audio url to play, you aren't using adaptive playback then there is no need to initiate yours own `TrackSelector` or `BandwidthMeter`, as those are needed to play an master playlist with was initiated to an `MediaSource`, so if there is a internet lag youtube site player will start as fast as possible but using an lower resolution and that doesn't happen on yours case.

Another things is that they use an geolocation latency system, in with the site will play the content from a server that will have the best connection, I don't think they provide that for any one requesting they links, so the link you are receive will have random latency issues.

If you are going to use a master playlist to load a `MediaSource`, don't create a new `BandwidthMeter` every time you start an player, just create it only if it is `null` if not reuse as if you start a new every time the way you are doing it will loose the previously calculation for the bandwidth as you are forcing the "Maximum bandwidth" possible using `setInitialBitrateEstimate` to  `Integer.MAX_VALUE`, doing that if was detected a slow internet on a previously playback that will be lost and some additional lag/buffer will occurred until the player properly measure the connection again do to the new `BandwidthMeter` and choose the proper content.

**Comment by ojw28** [comment]
I would echo what @fgl27 has said above. If you care about minimizing latency then you really need to optimize everything related to content preparation and delivery. This includes using modern formats (e.g., DASH with FMP4), optimizing your encodes to give the best quality for the least bitrate, distributing your content over a CDN to ensure there's a copy located close to your users, and so on.

It's unlikely that the large amount of latency you're seeing is caused by ExoPlayer, or that it's resolvable by changing ExoPlayer's configuration (beyond reducing `bufferForPlaybackMs` to a small value, as @fgl27 suggests).
