### ISSUE TITLE
OkHttpDataSource - missing content subtitles after ADs error

### ISSUE THREAD

**Issue by jaworskim** [google/ExoPlayer#9042]
We are having an issue with loading subtitles during ad playback (subtitles for content, not for ads). ExoPlayer sometimes returns empty list of subtitle tracks for streams. Issue only happens after ad playback, if we disable the playback of ads, everything works correctly in the same video stream. We are using DASH protocol. Stream is DRM encrypted, but ads are not. Everything is using HTTPS. Issue only occurs if we are using OkHttpDataSource, on DefaultHttpDataSource subtitles are always showing up correctly. For better reproduction rate we have changed DefaultLoadErrorHandlingPolicy retry count to 1.

onLoadError returns for us two errors in this case during ad playback:

```
trackFormat = Format(9, null, application/x-mpegURL, null, mp4a.40.2,avc1.4d401f, 4859787, null, [1280, 720, 25.0], [-1, -1])
error = {HttpDataSource$HttpDataSourceException@29557} "com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: javax.net.ssl.SSLProtocolException: Read error: ssl=0xb9447b38: Failure in SSL library, usually a protocol error\nerror:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT (third_party/openssl/boringssl/src/crypto/fipsmodule/cipher/e_aes.c:1040 0xbff98d4c:0x00000000)\nerror:1000008b:SSL routines:OPENSSL_internal:DECRYPTION_FAILED_OR_BAD_RECORD_MAC (third_party/openssl/boringssl/src/ssl/tls_record.cc:298 0xbff98d4c:0x00000000)"

trackFormat = Format(9, null, application/x-mpegURL, null, mp4a.40.2,avc1.4d401f, 4859787, null, [1280, 720, 25.0], [-1, -1])
com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect
```

After those errors show up, subtitles are usually not downloaded and do not show up in track selector.

Test device on which issue is reproducable: Android TV API 28 emulator (I can also confirm that this happens on some real Android TV devices).
ExoPlayer version: r2.14.0

I'm unable to share the DRMed content, however I can provide a full ADB log if it will be needed.

**Comment by claincly** [comment]
The error does say Failure in SSL library, and Unable to connect right? I suspect it's something to do with the network. Can you reproduce it reliably?

**Comment by jaworskim** [comment]
Reproduction is reliable, around 50% rate. I've checked a few phone devices on the same network and error never happens on them, however we do know that error does happen on some real TV devices (customer reports about missing subtitles).

After SSL error happens on ADs, we would expect subtitles for content to work correctly in OkHttpDataSource. Like I've mentioned DefaultHttpDataSource does not have that issue at all.

**Comment by claincly** [comment]
Can you share some media for us to test with?
