### ISSUE TITLE
Transaction: live to vod

### ISSUE THREAD

**Issue by javaboboApp** [google/ExoPlayer#9044]
Given a LIVE content that became VOD I would like to ask what is the best way to detect transaction live to vod. 

Actually  what I am doing is override function: 

1. onTimelineChanged(timeline: Timeline, reason: Int)

2. and checking if (reason == Player.TIMELINE_CHANGE_REASON_SOURCE_UPDATE) {.. //do stuff}

but I could have a handle calling itself and checking : if(player?.isCurrentWindowsDynamic()) {} 

so when manifest file change from dynamic to static I can detect this change. 

My question is: is this the best way to do it? or Do I missing something?. 

Thanks.

**Comment by claincly** [comment]
Hi! Please provide complete information as requested in the question template. The template can be
found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/question.md).

Not sure what live content you are using, HLS, DASH?

**Comment by javaboboApp** [comment]
Content use DASH.
Type of content LIVE.

Target: Content Live become VOD, detect this change and update ui according state. 

Current solution: 

1. Detect current state every 500 ms (is content still live or is vod), using handle:

    handler.post(runnable, 500){
      if(player?.isCurrentWindowsDynamic()) { updateUiAccordinglive() }
      else {updateUiAccordingVod()}
      .... 
      handler.post(runnable, 500)
      ...
    }
 2. Use onTimelineChanged (timeline: Timeline, reason: Int) 
 {
  if (reason == Player.TIMELINE_CHANGE_REASON_SOURCE_UPDATE) {.. //do stuff}
 }

**Comment by ojw28** [comment]
You shouldn't need to detect the current state periodically. Using `onTimelineChanged` sounds right to me. Inside that method, you should query the player to see if the specific state that you're interested in has changed. Something like:

```
onTimelineChanged (Timeline timeline, int reason) {
  if (reason == Player.TIMELINE_CHANGE_REASON_SOURCE_UPDATE) {
    boolean isDynamic = player.isCurrentWindowDynamic();
    // ... do stuff
  }
}
```

**Comment by javaboboApp** [comment]
ok clear thanks for the answer :)

**Comment by javaboboApp** [comment]
@ojw28  I would like to ask you if there is any way to find out faster if the current manifest is live or not. 
Listen the event using the function onEvents(..) would help ?

**Comment by ojw28** [comment]
The approach outlined above allows you to query whether the manifest is live immediately on each manifest update. So as soon as a manifest update occurs that indicates the manifest is no longer live, you should find out about that straight away.
