### ISSUE TITLE
Inaccurate EXTINF in m3u8 playlist leads to wrong clip position

### ISSUE THREAD

**Issue by charles-yinyu** [google/ExoPlayer#9046]
Media URL:
http://freevod.nf.migu.cn:8080/HvlmXE4s1sZ2lFLNrjmRI3Xac7sAHB3Bo0R1D6179Fv6iy1P0%2F3hONhDvJHW3%2BNGoooXTbtNkRh0q2u3NpmnhMp7sRQ9UN%2BFZVrHlLmbKSDnudrhzah0vusSi6omMOi49xkZntZgBLXrUV1dkjZQUEYJD0MV7ClZJ%2BKTDxskgRg2yUoX6Xiw1VdDnXchvv9x/600575Y9P8H044207.mp4.m3u8?msisdn=1ae26295-9758-49bc-9c27-c6db2f76cb48&spid=600906&sid=56887397529200&timestamp=20210531165722&encrypt=2dba5c8acd9430fa683b3a0dc477dbf6&k=58ea4616d3cce25a&t=1622458642787&ec=2&flag=+&FN=filename

which is used in a ClipMediaSource started as 9791ms. Unfortunately, the video is started from about 7000ms.

The reason is because the second ts segment in the m3u8 playlist is marked as #EXTINF 1s but actually lasts for 3s. HlsMediaChunk adjusts the timestamp by startTimeUs which is written from #EXTINF. Eventually TimestampAdjuster adjust sample timestamp by a wrong timestampOffsetUs.

HlsMediaChunk.java
```
private void loadMedia() throws IOException, InterruptedException {
    if (!isMasterTimestampSource) {
      timestampAdjuster.waitUntilInitialized();
    } else if (timestampAdjuster.getFirstSampleTimestampUs() == TimestampAdjuster.DO_NOT_OFFSET) {
      // We're the master and we haven't set the desired first sample timestamp yet.
      **timestampAdjuster.setFirstSampleTimestampUs(startTimeUs);**
    }
    feedDataToExtractor(dataSource, dataSpec, mediaSegmentEncrypted);
  }

TimestampAdjuster.java
public long adjustSampleTimestamp(long timeUs) {
    if (timeUs == C.TIME_UNSET) {
      return C.TIME_UNSET;
    }
    // Record the adjusted PTS to adjust for wraparound next time.
    if (lastSampleTimestampUs != C.TIME_UNSET) {
      lastSampleTimestampUs = timeUs;
    } else {
      if (firstSampleTimestampUs != DO_NOT_OFFSET) {
        // Calculate the timestamp offset.
        **timestampOffsetUs = firstSampleTimestampUs - timeUs;**
      }
      synchronized (this) {
        lastSampleTimestampUs = timeUs;
        // Notify threads waiting for this adjuster to be initialized.
        notifyAll();
      }
    }
    **return timeUs + timestampOffsetUs;**
  }
```

Hope you guys can help, thanks.

**Comment by claincly** [comment]
I'm not sure I understand. It seems you have a wrong HLS playlist?

**Comment by charles-yinyu** [comment]
HLS playlists aren't what we can control(.etc third party). Is there any way the player can rewrite the wrong startTimeUs like reading duration from ts segment instead of #EXTINFO.

**Comment by ojw28** [comment]
This doesn't seem like something that should fall on the client. Closing as `bad media`.
