### ISSUE TITLE
Ignore audio track

### ISSUE THREAD

**Issue by ppamorim** [google/ExoPlayer#905]
Hi.
We use the ExoPlayer on the application that's uses stream HLS. This flux is generated with Nginx-rtmp-module.

https://github.com/arut/nginx-rtmp-module

But the stream isn't work with ExoPlayer, we've tested this same flux with another player (VLC) and works fine.

This is the m3u8 from Eiffel Tower: https://d33e9z4l6nr9ho.cloudfront.net/hls/1dia/13fb7fa0-370d-11e5-9a60-35a00edea567.stream/index.m3u8
Another m3u8 from Russia: https://d33e9z4l6nr9ho.cloudfront.net/hls/1dia/ccc15d50-37b9-11e5-97b7-9dad1a791e1d.stream/index.m3u8

I'm doing the same config of the HLS player of the sample application. I believe it's a problem with ExoPlayer.
No errors, no warnings. A bug.

**Comment by ojw28** [comment]
- If this is HLS, it has nothing to do with RTMP right? It's just that the module you're using has RTMP in the name. Is that correct, or did I misunderstand?
- The link you've posted 404s for me. If it broken and/or geo-restricted?

**Comment by ppamorim** [comment]
@ojw28 It`s only the name of the module.
I`ll review this 404 problem.

**Comment by ppamorim** [comment]
@ojw28 We use this: https://github.com/arut/nginx-rtmp-module/wiki/Directives#hls

**Comment by ojw28** [comment]
- The Eiffel Tower one seems to work fine for me.
- The Russia one doesn't work because the stream's program map declares an audio track even though the stream doesn't contain any audio data. The stream shouldn't do this (although granted, we should also be doing a better job of being robust against this). You can make it work by manually ignoring the audio track declaration, which can be done by commenting out the TS_STREAM_TYPE_AAC case [here](https://github.com/google/ExoPlayer/blob/master/library/src/main/java/com/google/android/exoplayer/extractor/ts/TsExtractor.java#L303).

**Comment by ppamorim** [comment]
@ojw28 Tower Eiffel working fine too! Let's me analyse this problem with the Russia one.

**Comment by ppamorim** [comment]
@ojw28 Good news! I commented this line of the audio reader and stream works perfectly! 
What I can do to fix it? Would we implements a detector of audio track before the init of the reader?

**Comment by ojw28** [comment]
If the stream claims to contain audio then it should contain audio. Ultimately this is a problem with the content, and whoever's providing the stream should fix it to not declare an audio track in the program map.

We may make the player more robust against this kind of content error in the future, but it's nowhere near being high up on our list of things to do, and is probably quite complicated to handle in a nice way.

**Comment by sillywab8** [comment]
Hi @ojw28,
I know this is an old and closed issue but I am need to find an interim solution to address this.  I understand that the stream is claiming audio when there shouldn't be one but I wish this failure was consistent with other video players for example any web HLS player. Our customers can play their videos on our web product and then can't on their Android devices and that makes the "If the stream claims to contain audio then it should contain audio" argument difficult to sell to them.  For us, we are experiencing this mostly with time-lapse videos which are by default are without audio.

Before I embark on figuring out a fix in a forked version of ExoPlayer, I was wondering if you can provide any high-level insight on where a solution might exist so I don't have to start at ground zero. So far the only thing I have to go by is commenting TS_STREAM_TYPE_AAC to get the videos to play.

Any help is very much appreciated.
