### ISSUE TITLE
Google Exoplayer : HLS Redundant stream is not working (Issue #9047)

### ISSUE THREAD

**Issue by SUNYTYAGI** [google/ExoPlayer#9054]
Hi I am creating new issue , since i do not have access to re-open close issue (#9047)

Please check my last comment on the issue (#9047 )

https://github.com/google/ExoPlayer/issues/9047#issuecomment-860863669

**Comment by SUNYTYAGI** [comment]
+@christosts

**Comment by ojw28** [comment]
Closing as a duplicate of #9047 (which I will re-open).
