### ISSUE TITLE
Choppy audio playback for some m4a's

### ISSUE THREAD

**Issue by timusus** [google/ExoPlayer#9058]
Hi ExoPlayer team,

I've had user reports of choppy audio for a couple of songs. They've sent me the tracks, which I'll attach here. Unfortunately they're extremely awful to listen to even without playback issues.

Easy to replicate. Listen to either song and you should notice the 'choppy' sound. 

I can replicate the issue on my Pixel 5 running Android 11. I see the following in the logs:

```
W/C2SoftAacDec: AAC decoder returned error 0x4004, substituting silence
W/C2SoftAacDec: aacDecoder_DecodeFrame decoderErr = 0x4004
```

These lines are consistently output while playing the files. 

I've reproduced the issue in ExoPlayer 2.14.1.

I reckon there's probably a good chance that the file is corrupt, or incorrectly encoded - but I don't possess the skills to verify this. According to user reports, these play OK using other apps (so probably using the Android MediaPlayer).

I tested in VLC and playback seems OK.

Sincere apologies to anyone who has to listen to the audio.
[songs.zip](https://github.com/google/ExoPlayer/files/6653356/songs.zip)

**Comment by ojw28** [comment]
I'm not sure what's going wrong here, but I've filed an internal issue on those responsible for the AAC decoder to take an initial look [Internal ref: 191123693]. I'll provide an update when we hear back.

> Sincere apologies to anyone who has to listen to the audio.

Heh :)

**Comment by UtsavG93** [comment]
i facing same issue POCO M2 Android 10
in ExoPlayer  #2.14.1.

the m4a files i have those from iTunes and then transferred them to an Android phone
[song_test.zip](https://github.com/google/ExoPlayer/files/6676097/song_test.zip)

**Comment by ojw28** [comment]
The issue seems to be fixed on Pixel running Android 12. I'm following up to try and understand what the fix was, and whether it will be deployed to Android 11 devices (for those devices that are not updated quickly, or will have Android 11 as their final major release).

**Comment by ojw28** [comment]
Android 11 devices with modular system components (https://source.android.com/devices/architecture/modular-system) should be receiving an update that fixes the issue this month (the fix is in the `com.android.media.swcodec` module). It's also possible that OEMs may update Android 11 devices via their OTA mechanism. So, the fix is available and Android 11 devices are being updated. Exactly when may vary by device and OEM.

**Comment by timusus** [comment]
Thanks for following up, much appreciated.
