### ISSUE TITLE
getBufferedPercentage for streaming before being able to play

### ISSUE THREAD

**Issue by ripleyXLR8** [google/ExoPlayer#906]
Hi everybody,

I'm using ExoPlayer as an HLS stream player (streams are genereted by Wowza) and I need to be able to display the current percentage buffered before the stream will be able to play.

In fact "getBufferedPercentage" return me the total amount of the total track which is currently buffered and not the percentage buffered before the player will be able to play the stream.

Is there a function that can returns this information? Or a way to compute it?

Best regards
Richard

**Comment by ojw28** [comment]
You could do something like this to get an estimate of the duration currently buffered:

```
int estimatedBufferDuration = ExoPlayer.UNKNOWN_TIME;
int estimatedBufferPosition = player.getBufferedPosition();
if (estimatedBufferPosition != Exoplayer.UNKNOWN_TIME) {
  estimatedBufferDuration = estimatedBufferPosition - getCurrentPosition();
}
```

You could then compare this to the duration that needs to be buffered for playback to start, which is the second argument passed to `ExoPlayer.Factory.newInstance` when creating the player, or `ExoPlayer.Factory.DEFAULT_MIN_BUFFER_MS` if you're using the one-arg version of that method. If you're handling a re-buffer, compare to the third argument or `ExoPlayer.Factory.DEFAULT_MIN_REBUFFER_MS`.

You'd probably end up with something like:

```
int percentage = 0;
if (estimatedBufferDuration != ExoPlayer.UNKNOWN_TIME) {
  percentage = (estimatedBufferDuration * 100) / ExoPlayer.Factory.DEFAULT_MIN_BUFFER_MS;
  percentage = Math.max(0, Math.min(100, percentage));
}
```

When you create an ExoPlayer using ExoPlayer.newInstance, the second argument is the minimum duration that needs to be buffered before playback starts and the third argument is the minimum duration that needs to be buffered before playback resumes following a re-buffer.

- You can use `player.getCurrentPosition()

**Comment by Android4MediaPlayer** [comment]
@ojw28 why not merged code to gitbub?

**Comment by Android4MediaPlayer** [comment]
@ojw28 why not merged code to github?

**Comment by ojw28** [comment]
This is the first time anyone's asked for this, which suggests it's not a feature that a many people want. Most applications don't show the percentage to the user; they just show a buffering spinner. The percentage isn't going to be particularly accurate anyway.

**Comment by ripleyXLR8** [comment]
I tried it in my application, and it is accurate enough.
The only problem is to detect if it is a buffer or a rebuffer? For me the MIN_BUFFER is 1000 and the MIN_REBUFFER is 5000 so the difference is too big to present it to the user.

Is there a way to know if we are in a buffer or a rebuffer?

**Comment by wajidp** [comment]
@ripleyXLR8 How did you configure the minimum buffer ? .. Thanks

**Comment by ojw28** [comment]
@ripleyXLR8 - For playback to be happening playWhenReady must be true and the state must be ExoPlayer.STATE_READY. If this is the case and the player state then transitions to STATE_BUFFERING by itself (i.e. without you having called seekTo or setPlayWhenReady), then that counts as a re-buffer. If you call seekTo or toggle setPlayWhenReady then it's always a buffer rather than a re-buffer.

**Comment by ripleyXLR8** [comment]
@wajidp When you initialize your player you can do it through the following constructor instead of using the standard 1 parameter constructor.

ExoPlayer.Factory.newInstance(RENDERER_COUNT, DEFAULT_MIN_BUFFER_MS, DEFAULT_MIN_REBUFFER_MS);

Of course i had previously declared :

    public static final int RENDERER_COUNT = 4;
    public static final int DEFAULT_MIN_BUFFER_MS = 1000;
    public static final int DEFAULT_MIN_REBUFFER_MS = 5000;

**Comment by ripleyXLR8** [comment]
@ojw28 Thank you!!! By the way thank for your work on this player, it is amazing. I have remove Vitamio from my dependencies....  which is a no longer active project and a very heavy library.

**Comment by wajidp** [comment]
@ripleyXLR8 Thanks man..

**Comment by needz** [comment]
In ExoPlayer 2, is there a correlation between the following items: **DEFAULT_MIN_BUFFER_MS, DEFAULT_MAX_BUFFER_MS, DEFAULT_BUFFER_FOR_PLAYBACK_MS, DEFAULT_BUFFER_FOR_PLAYBACK_AFTER_REBUFFER_MS** ?

That is, if I change the **DEFAULT_BUFFER_FOR_PLAYBACK_MS** and **DEFAULT_BUFFER_FOR_PLAYBACK_AFTER_REBUFFER_MS** values in app settings, should I change the **DEFAULT_MIN_BUFFER_MS** and **DEFAULT_MAX_BUFFER_MS** too? What would be the relation?

Also, is **DEFAULT_BUFFER_FOR_PLAYBACK_AFTER_REBUFFER_MS** set at **DEFAULT_BUFFER_FOR_PLAYBACK_MS** multiplied by 2 is a good way to correlate?
