### ISSUE TITLE
Unable to access items in popup menus of StyledPlayerView on older Android TV

### ISSUE THREAD

**Issue by moneytoo** [google/ExoPlayer#9061]
I use `StyledPlayerView` on Android TV devices. It's ok on Android TV 9.0 (like Xiaomi Mi Box S) but on older devices like Geniatech ATV598Max with Android TV 7.0, the items in popup menus (like subtitle languages or playback speed & audio) are inaccessible. No item can be selected using navigation keys.

Reproducible on Android TV emulators (API 24) as well.

Demo project: https://github.com/moneytoo/ExoPlayerDemo/blob/tv-control/app/src/main/java/com/example/exoplayer/MainActivity.java

- ExoPlayer version number: 2.14.1
- Android version: 7.0
- Android device: Geniatech ATV598Max (enjoytv_hybrid) / Android TV emulator

![OnZatHFrdj](https://user-images.githubusercontent.com/1071643/122131076-ecb97680-ce38-11eb-8c3f-a77482d3db06.jpg)

On picture: emulators API 24 (left) vs API 29 (right).

**Comment by ojw28** [comment]
I can reproduce this on API level 25 and earlier (but not API level 26 and later).

**Comment by moneytoo** [comment]
Just confirming that after cherry picking, it works on both real device and emulator. Thank you!
