### ISSUE TITLE
Video rotation and scaling/cropping to fit fullscreen

### ISSUE THREAD

**Issue by pavhofman** [google/ExoPlayer#9063]
My goal is simple but I have been struggling with it for many days:

Live H264 RTSP feed from an IP camera of 1280 width x 720 height -> rotated by 90 degrees -> centred, scaled, cropped to fit portrait-mode 768 width x 1024 height display at fullscreen, no geometric distortion (same scale factor in both dimensions). That requires: resizing by factor 768/720 to fit the rotated width, rotating by 90 degrees, cropping height to 1024 centered. Using maximum HW accelleration/minimum CPU load.

I can change anything in exoplayer sources, not limited to using exoplayer API only.

Due to rotation I am using the recommended `TextureView`. I do not understand the co-ordination/combination of resizing/scaling/matrix transforms:

- setting `AspectRatioFrameLayout` dimensions in `AspectRatioFrameLayout.onMeasure()` (controlled by the `ResizeMode` values)
- `codec.setVideoScalingMode(scalingMode)` in `MediaCodecVideoRenderer`
- `TextureView` rotation/scale/cropping transformation matrix calculated in `PlayerView.applyRotation()`

Please can I ask for explanation of how these three operations fit together? I have tried many combinations but do not understand how their results were reached, so that I am able to find the correct procedure to reach the above goal. Thank you very much for any hints.

**Comment by pavhofman** [comment]
IIUC AspectRatioFrameLayout just limits size of output video surface based on aspect ratio. In my case of fullscreen the parameter ResizeMode.RESIZE_MODE_FILL should be used as it keeps the layout at screen size.

But I would like the codec to scale + crop using VIDEO_SCALING_MODE_SCALE_TO_FIT_WITH_CROPPING (without rotation that should work correctly according to https://developer.android.com/reference/android/media/MediaCodec#VIDEO_SCALING_MODE_SCALE_TO_FIT_WITH_CROPPING ) . However, I do not understand how to give unrotated output dimensions to the codec - IIUC the codec should read dimensions from the output surface (SurfaceTexture of TextureView) but the surface's aspect is already rotated to portrait mode. I would do the final rotation with the TextureView transformation matrix.

**Comment by pavhofman** [comment]
Hm, setting VIDEO_SCALING_MODE_SCALE_TO_FIT_WITH_CROPPING and  VIDEO_SCALING_MODE_SCALE_TO_FIT makes no visual difference. It just does not make any sense to me. Rotating a video and scaling while maintaining aspect seems to be an insurmountable problem...

**Comment by pavhofman** [comment]
I guess a working way is like this:

- Setting `playerView.setResizeMode(AspectRatioFrameLayout.RESIZE_MODE_FILL)` to keep the `AspectRatioFrameLayout` (parent of the video player view) fullscreen
- Rotating the video by `MediaCodec`: `Format.rotationDegrees = 90` in Format.java - hard-coded for now, to be investigated how to set it properly outside of ExoPlayer source code.
- Non-uniform scaling the rotated video by `MediaCodec` to fit the `TextureView` in portrait aspect: `player.setVideoScalingMode(C.VIDEO_SCALING_MODE_SCALE_TO_FIT)`. Using `VIDEO_SCALING_MODE_SCALE_TO_FIT_WITH_CROPPING` makes no difference.
- Non-uniform scaling by `TextureView` transformation matrix to obtain the original video (rotated) aspect which does the necessary cropping too - in `PlayerView.applyTextureViewRotation` - again to be investigated how to modify outside of ExoPlayer sources:
```java
Matrix transformMatrix = new Matrix();
        float textureWidth = textureView.getWidth();
        float textureHeight = textureView.getHeight();
        float pivotX = textureWidth / 2;
        float pivotY = textureHeight / 2;
        // video is already rotated by the MediaCodec (incl. videoSize params)
        transformMatrix.preScale(
                // width will not change
                1f,
                // making higher
                (this.videoSize.height/textureHeight) * (textureWidth/this.videoSize.width),
                pivotX,
                pivotY);
        textureView.setTransform(transformMatrix);
```
I am not entirely satisfied with the result because of the two scaling operations - `MediaCodec` non-uniformly scaling  to fit the `TextureView` size and subsequently `TextureView` non-uniformly scaling back to the original aspect of the video. If I could tell `MediaCodec` some "virtual" dimensions of the output surface, it could scale uniformly and the output surface could be the more efficient `SurfaceView`, doing no scaling at all. However I am afraid there is no such method ( https://stackoverflow.com/questions/68033162/mediacodec-with-surfacetexture-transformation-matrix-passing-custom-output-s )

Or please is there a better way?  Thanks a lot in advance.

**Comment by ojw28** [comment]
* `MediaCodec.setVideoScalingMode` doesn't do anything when using `TextureView` (it applies to `SurfaceView` only). Unfortunately this is not clearly documented (as far as I can tell), but that aside, it's not useful for what you're trying to do, so you can discard this option.
* I would also advise against using `Format.rotationDegrees` as a way to get the codec to perform rotation. There's no need to do this given you can apply the rotation using `TextureView.setTransform`, and doing so splits the transformation across multiple pieces of code, which doesn't seem like a good idea.
* Using `AspectRatioFrameLayout.RESIZE_MODE_FILL` sounds like a good idea.
* The transformation you're trying to do is a linear transformation, so you should be able to do the whole thing using `TextureView.setTransform`. It's really just a matter of working out how to construct the correct transformation matrix, as far as I can tell.
