### ISSUE TITLE
MediaSessionConnector: Can onPause() be intercepted?

### ISSUE THREAD

**Issue by y20k** [google/ExoPlayer#9066]
I am developing a web radio player app. I am using [MediaSessionConnector.java ](https://github.com/google/ExoPlayer/blob/b2333c86c1eac9a1f95992960a8495f1e5b79200/extensions/mediasession/src/main/java/com/google/android/exoplayer2/ext/mediasession/MediaSessionConnector.java) to deal with MediaSession stuff. The UI of the app offers the following playback options: Play, Stop, Next station, Previous station. The app can also be controlled via Android Auto and Bluetooth (headphones). This works basically great thanks to MediaSessionConnector. :+1: 

But Headphones buttons and Android Auto are sending the Pause command to the app. This triggers [Player.pause()](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/Player.html#pause()). 

**For a radio app that means:** 

- Playback is paused
- ExoPlayer is buffering the stream

**When the user selects to start the stream again, the following happens:**

- Playback starts right, where it was paused. Playback is not "live" anymore,
- When the buffer is exhausted, playback jumps to the live stream

**Desired behavior for a radio app, when a user selects to start a stream again:**

- Playback jumps right back into the live stream

That brings me to my question. I am able to intercept the Headphone Pause button using [MediaButtonEventHandler](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/ext/mediasession/MediaSessionConnector.MediaButtonEventHandler.html). But I am not sure how to intercept the Pause command from Android Auto. The only way I was able to come up with to reach this goal would be: Intercept the [onPause()](https://github.com/google/ExoPlayer/blob/b2333c86c1eac9a1f95992960a8495f1e5b79200/extensions/mediasession/src/main/java/com/google/android/exoplayer2/ext/mediasession/MediaSessionConnector.java#L1170) command somehow and trigger a [Player.stop()](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/Player.html#stop()). Is that possible?

Note: I have the strong feeling that I am missing an obvious solution here :-/

**Comment by marcbaechinger** [comment]
There is a method `mediaSessionConnector.setControlDispatcher` to which you can pass a custom `ControlDispatcher` instance. You can just pass a `DefaultControlDeispatcher` of which you override the method `dispatchSetPlayWhenReady(Player player, boolean playWhenReady)`.

**Comment by y20k** [comment]
>> Note: I have the strong feeling that I am missing an obvious solution here :-/

> There is a method `mediaSessionConnector.setControlDispatcher` ...

I knew I was missing something obvious. Thank you!
