### ISSUE TITLE
Is there a way to manualy switch between rendition quality in adaptive HLS streaming?

### ISSUE THREAD

**Issue by ripleyXLR8** [google/ExoPlayer#907]
Hi everybody,

I'm looking for a way to switch manualy between rendition quality in HLS adaptive streaming. I have seen that in the demo app, this option is available for DASH streaming, is there a way to do the same thing with HLS?

Best regards

Richard

**Comment by crossle** [comment]
+1

**Comment by ojw28** [comment]
Same as #676
