### ISSUE TITLE
How to remove Y translation from DefaultTimeBar

### ISSUE THREAD

**Issue by MathiasOhrstrom** [google/ExoPlayer#9072]
We use `StyledPlayerControlView` but have a problem with `DefaultTimeBar` having a different animation that the rest of the controls that fade in.

How can i remove the Y-translation animation on the `DefaultTimeBar`?

We are using ExoPlayer `2.12.3`
Example video:

https://user-images.githubusercontent.com/26031482/122393842-9aca3b00-cf75-11eb-8b03-b917b6b1275a.mov

**Comment by ojw28** [comment]
It doesn't look like it's easy to do this, I'm afraid.

It's an entirely reasonable request in isolation, but what we see is that developers who want to customize our UI components generally all want to do so in different ways. Hence whilst each request may be reasonable in isolation, it doesn't make sense for us to support them all (each request is only going to benefit a small number of developers, and the API surface and implementation becomes even more messy to support not only each feature, but also combinations of such features that no-one ever uses). As a result, our advice for such requests is to either (a) accept that the UI will not be exactly as your designers envisaged it, or (b) fork the relevant classes, which gives you complete control to adjust them to suit your needs.
