### ISSUE TITLE
Override  selectVideoTrack , but it keeps calling the initial track  

### ISSUE THREAD

**Issue by isaacdz** [google/ExoPlayer#9076]
I'm trying to deploy a Random Forest Classier Model in Exoplayer using Weka API . 
After each onLoadCompleted, I predict the best track to be downloaded next ,  as I was looking for the best implementation here , I went through 2 possible ways  . 

-  SelectionOverride   inside  onLoadCompleted
```
MappingTrackSelector.MappedTrackInfo mappedTrackInfo = trackSelector.getCurrentMappedTrackInfo();
                     TrackGroupArray rendererTrackGroups = mappedTrackInfo == null ? null : mappedTrackInfo.getTrackGroups(rendererIndex);
                     DefaultTrackSelector.SelectionOverride selectionOverride = new DefaultTrackSelector.SelectionOverride(0, chunkindex);
                      trackSelector.setParameters(
                                 trackSelector
                                     .buildUponParameters()
                                     .setSelectionOverride(rendererIndex, rendererTrackGroups, selectionOverride));
```

- Extend DefaultTrackSelector and Override  selectVideoTrack 
```
public class RFTrackSelector extends DefaultTrackSelector   {
    protected ExoTrackSelection.Definition selectVideoTrack(TrackGroupArray groups, int[][] formatSupport, int mixedMimeTypeAdaptationSupports, Parameters params, boolean enableAdaptiveTrackSelection) throws ExoPlaybackException {
        return new ExoTrackSelection.Definition(groups.get(0),getNextTrackID());
    }
}
```

because of the stall Duration and Rebuffering time in the first method and it's Asynchronous, I opted for the second implementation , now the problem I'm having is that,  selectVideoTrack keeps selecting always the first Track I gave, is there anything I'm missing about selectVideoTrack? , because I want to keep the model selecting each track, is this possible to do with  selectVideoTrack? or are there other methods that I'm not aware of, thank you so much in advance .

**Comment by ojw28** [comment]
If your goal is to implement an ABR algorithm for DASH and/or HLS then you'll need to implement a custom `TrackSelection`. As a starting point, I'd suggest you look at `AdaptiveTrackSelection` in the library, which is the built in ABR algorithm. The quality evaluation happens in `AdaptiveTrackSelection.updateSelectedTrack`. It may be easiest for you to start by forking `AdaptiveTrackSelection` and editing it to suit your needs.

To actually use your custom `TrackSelection` implementation, create a `DefaultTrackSelector` using the constructor that takes an `ExoTrackSelection.Factory`.
