### ISSUE TITLE
HLS stream does not start playback

### ISSUE THREAD

**Issue by poptong** [google/ExoPlayer#9081]
http://123.140.197.22/stream/2/play.m3u8

Does not jump from STATE_BUFFERING to STATE_READY

**Comment by BaranovVO** [comment]
I have the same issue.

There are several HLS sources. When I set them and call prepare(), the player state doesn't go to READY.

My code:

    private fun initExoPlayer() {
        val player = SimpleExoPlayer.Builder(this).build()
        player.addListener(object : Player.Listener {
            override fun onPlayerError(error: ExoPlaybackException) {
                super.onPlayerError(error)
                if (error.cause is BehindLiveWindowException) {
                    player.playWhenReady = false
                    startPlayVideo()
                }
            }
        })
        player.addAnalyticsListener(EventLogger(player.trackSelector as MappingTrackSelector?))
        exoPlayerView.player = player

        val haveResumePosition = mResumeWindow != C.INDEX_UNSET

        if (haveResumePosition) {
            exoPlayerView.player?.seekTo(mResumeWindow, mResumePosition)
        }

        startPlayVideo()
    }

    private fun startPlayVideo() {
        exoPlayerView.player?.let { player ->
            if (sources.isNotEmpty()) {
                (player as SimpleExoPlayer).apply {
                    val mediaSources = sources.map {
                        HlsMediaSource.Factory(dataSourceFactory)
                            .createMediaSource(
                                MediaItem.Builder()
                                    .setUri(it.url)
                                    .setMimeType(MimeTypes.APPLICATION_M3U8)
                                    .build()
                            )
                    }
                    setMediaSources(mediaSources, true)
                    seekTo(index, C.POSITION_UNSET.toLong())
                    playWhenReady = true
                    prepare()
                }
            }
        }
    }

And my log where the video starts playing after being called player.next().
[log.txt](https://github.com/google/ExoPlayer/files/6905578/log.txt)

**Comment by BaranovVO** [comment]
> I have the same issue.
> 
> There are several HLS sources. When I set them and call prepare(), the player state doesn't go to READY.
> 
> My code:
> 
> ```
> private fun initExoPlayer() {
>     val player = SimpleExoPlayer.Builder(this).build()
>     player.addListener(object : Player.Listener {
>         override fun onPlayerError(error: ExoPlaybackException) {
>             super.onPlayerError(error)
>             if (error.cause is BehindLiveWindowException) {
>                 player.playWhenReady = false
>                 startPlayVideo()
>             }
>         }
>     })
>     player.addAnalyticsListener(EventLogger(player.trackSelector as MappingTrackSelector?))
>     exoPlayerView.player = player
> 
>     val haveResumePosition = mResumeWindow != C.INDEX_UNSET
> 
>     if (haveResumePosition) {
>         exoPlayerView.player?.seekTo(mResumeWindow, mResumePosition)
>     }
> 
>     startPlayVideo()
> }
> 
> private fun startPlayVideo() {
>     exoPlayerView.player?.let { player ->
>         if (sources.isNotEmpty()) {
>             (player as SimpleExoPlayer).apply {
>                 val mediaSources = sources.map {
>                     HlsMediaSource.Factory(dataSourceFactory)
>                         .createMediaSource(
>                             MediaItem.Builder()
>                                 .setUri(it.url)
>                                 .setMimeType(MimeTypes.APPLICATION_M3U8)
>                                 .build()
>                         )
>                 }
>                 setMediaSources(mediaSources, true)
>                 seekTo(index, C.POSITION_UNSET.toLong())
>                 playWhenReady = true
>                 prepare()
>             }
>         }
>     }
> }
> ```
> 
> And my log where the video starts playing after being called player.next().
> [log.txt](https://github.com/google/ExoPlayer/files/6905578/log.txt)

I've found my error. I used  C.POSITION_UNSET instead of  C.TIME_UNSET in seekTo(). But it worked with very older versions.

**Comment by ojw28** [comment]
The stream declares an H.264 video track, but the track doesn't contain any content. It's similar to https://github.com/google/ExoPlayer/issues/6112#issuecomment-507051301, except that the track without content is video rather than audio. The content should be fixed to not declare this track.

If you know a stream that you're going to try and play has this specific problem, you can work around it as described in that issue, except that in this case you need to use `FLAG_IGNORE_H264_STREAM`.

Closing as bad media, since the media should not be declaring the empty video track.
