### ISSUE TITLE
Does Exoplayer download a chunk completely before processing (decoding) it ? 

### ISSUE THREAD

**Issue by harishiyer0204** [google/ExoPlayer#9082]
Does Exoplayer download a chunk completely before processing (decrypting, decoding) it. Is there a way to override this and start decoding / playback before the chunk is completely downloaded. The content is an MPEG-DASH content with a 6 second chunk size.

I am on the latest version of Exoplayer. I am trying to improve the Video Start Time and hence this query. Also, will smaller chunk sizes impact the Video start time ?

**Comment by ojw28** [comment]
> Does Exoplayer download a chunk completely before processing (decrypting, decoding) it.

No, it doesn't. Chunks are processed incrementally as they become available.

> Also, will smaller chunk sizes impact the Video start time ?

No, I wouldn't expect this to improve startup latency.
