### ISSUE TITLE
How to queue songs with exoplayer

### ISSUE THREAD

**Issue by ibrajix** [google/ExoPlayer#9083]
How to Make Exoplayer Form a Queue From A list of songs
-------------------------

I am building a music player app.

In there, there are various segments:

All Songs - All songs from a user device
Playlist - All songs a user has added to playlist
Favourites - Songs a user has added as favorites/liked
Artistes Songs - All songs from an artiste

Right now, I have set up everything and I can play "ALL" songs etc...

What I want

When the user is in:

Playlist - Play only list of songs in that playlist

Favorites - Play only list of songs in favorites

Artiste Songs - Play only list of songs from an artiste

I have the list of songs from various segments

Right now, I can only play ALL songs from user media...So, the queue is from ALL SONGS IN THE DEVICE irrespective of the section you are in the app.. Which I dont want.

I have no problem with ALL SONGS Segment...

I asked on stackoverflow, no answer yet..

https://stackoverflow.com/questions/67959589/how-to-make-exoplayer-play-media-from-a-list-of-songs

**Comment by ojw28** [comment]
You can read about ExoPlayer's support for playlists [here](https://exoplayer.dev/playlists.html).

Beyond that, this doesn't sound like an ExoPlayer library question. It's the job of your application code to provide the correct set of media items, and doing this correctly does not fall within the scope of this issue tracker.
