### ISSUE TITLE
Use `ControlDispatcher` for dispatching next/previous in media2 extension

### ISSUE THREAD

**Issue by chvp** [google/ExoPlayer#9084]
[The current implementation](https://github.com/google/ExoPlayer/blob/release-v2/extensions/media2/src/main/java/com/google/android/exoplayer2/ext/media2/PlayerWrapper.java#L238) calculates the previous position itself and uses `ControlDispatcher.seekTo` to seek to it. This is different from [the default behaviour in the mediasession extension](https://github.com/google/ExoPlayer/blob/bd54394391b0527893f382c9d641b8a55ffca765/extensions/mediasession/src/main/java/com/google/android/exoplayer2/ext/mediasession/TimelineQueueNavigator.java#L148). 

I was wondering why this decision was taken, since this makes it impossible (or at least a **lot** harder than it should be) to override the behaviour of skip actions when using the media2 extension. The same question can be asked for more than just skip to previous, the behaviour of skip to next and other related methods should also be overridable, IMO (or at least, it should be clear why this was not made possible).

To avoid an [XY problem](https://en.wikipedia.org/wiki/XY_problem), what I really want to do is make it so that when the skip to previous action happens if a track has been playing for a few seconds, that it skips back to the start of the track instead of skipping to the previous track. I've found [SkipCallback](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/ext/media2/SessionCallbackBuilder.SkipCallback.html), but the problem there is that I didn't find any way to call the [skipBackward](https://developer.android.com/reference/androidx/media2/session/MediaController#skipBackward()) method from a notfication (or wearables, or OS-level controls, ...). Those all use the `skipToPreviousItem` action. Note that this worked out of the box when using the mediasession extension, so I assume that if `ControlDispatcher.dispatchPrevious(Player)` would be used there, it would remove the need for me to start messing around with it.

**Comment by chvp** [comment]
Any progress on this? Due to the `SessionPlayerConnector` class being `final` and the `SessionPlayer` not being an interface but an abstract class, there is no easy way to create a delegate or proxy to work around this behaviour.

**Comment by ojw28** [comment]
Thanks for the pull request! I posted one comment there for you to take a look at. Once we resolve that one way or another, I think we're good to get that merged in.

**Comment by jiaoya** [comment]
@chvp Excuse me: how did you solve it so that it won't jump back to the beginning of the track

**Comment by chvp** [comment]
This issue was to make the opposite behaviour possible (and default). If you don't want this, you need to set a custom ControlDispatcher and override the `previous` call.

**Comment by jiaoya** [comment]
thank you very much

Charlotte Van Petegem ***@***.***> 于2021年8月6日周五 下午6:10写道：
