### ISSUE TITLE
Cronet extension: `cronet-embedded` dependency is out of date

### ISSUE THREAD

**Issue by ojw28** [google/ExoPlayer#9085]
The [Cronet extension README](https://github.com/google/ExoPlayer/tree/release-v2/extensions/cronet) contains instructions for using `cronet-embedded`, but the Cronet Embedded library hasn't been updated since 2019. Newer versions are available directly on Google Cloud Storage, [here](https://pantheon.corp.google.com/storage/browser/chromium-cronet?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&prefix=&forceOnObjectsSortingFiltering=false).

We need to either (a) persuade the relevant team to start updating `cronet-embedded` again [Internal ref: b/169562606#comment20], or (b) update ExoPlayer's Cronet extension README to explain how to use the binaries available on Google Cloud Storage.

**Comment by andrewlewis** [comment]
Side note: the dependency on `org.chromium.net:cronet-embedded:76.3809.111` seems to be our last dependency that still requires jetification to be enabled.

```
 * org/chromium/base/ApiCompatibilityUtils.class -> android/support/v4/widget/ImageViewCompat
 * org/chromium/base/ApplicationStatus$2.class -> android.support.v7.app.ToolbarActionBar$ToolbarCallbackWrapper
 * org/chromium/base/ApplicationStatus$2.class -> android.support.v7.internal.app.ToolbarActionBar$ToolbarCallbackWrapper
 * org/chromium/base/ApplicationStatus.class -> android.support.v7.internal.app.ToolbarActionBar$ToolbarCallbackWrapper
 * org/chromium/base/ApplicationStatus.class -> android.support.v7.app.ToolbarActionBar$ToolbarCallbackWrapper
```

**Comment by ag2s20150909** [comment]
I found some new version Cronet compiled by the third party
https://github.com/biaomingzhong/Cronet-Android
https://github.com/zy3274311/CronetForAndroid


`        MicroG:
        
         implementation 'org.microg:cronet-native:92.0.4509.1'

         implementation 'org.microg:cronet-api:92.0.4509.1'

         implementation 'org.microg:cronet-common:92.0.4509.1'`

**Comment by ojw28** [comment]
I would advise against using versions provided by third parties, unless you know that the source is trustworthy.

**Comment by ojw28** [comment]
It's not certain yet, but I think option (a) is the most likely outcome here. Hence we have no plan to do (b) for the time being.

**Comment by ag2s20150909** [comment]
https://console.cloud.google.com/storage/browser/chromium-cronet/android

**Comment by ojw28** [comment]
`cronet-embedded` is being updated again. 92.4515.131 was published recently:

https://maven.google.com/web/index.html?q=cronet#org.chromium.net:cronet-embedded:92.4515.131

Closing since the issue is now resolved. Thanks!
