### ISSUE TITLE
"Unclickable" zones in track selectors of StyledPlayerView

### ISSUE THREAD

**Issue by moneytoo** [google/ExoPlayer#9086]
Please see the screenshot of StyledPlayerView with opened audio track selector popup window (& layout bounds enabled). When there's at least one longer string (like "English, 5.1 surround sound" in this case), other shorter items do not span the full width and contain "unlickable" (meaning that click doesn't result in item selection) zone on the right.

![Screenshot_20210619-215902](https://user-images.githubusercontent.com/1071643/122654229-50e67e00-d14a-11eb-96cd-fc28afebd7a9.jpg)

I'm not sure this is a bug per se, but it's definitely something IMHO doesn't feel right (based on my expectations after using Android UI). At least couple of times I tapped an item in a hope it would select but found that it didn't (until now I wasn't sure why it didn't work).

- ExoPlayer version number: 2.14.1
- Android version: Android 10
- Android device: OnePlus 7

**Comment by ojw28** [comment]
I've also noticed this, and spent half a day or so trying to figure out how to fix it without success. We'd definitely welcome a pull request to fix the issue, if you manage to figure it out. Marking as a bug for now.

**Comment by ojw28** [comment]
Actually, I have a fix for this. I'll merge it shortly.

**Comment by moneytoo** [comment]
Great! I tried the related changes and it works. Thank you!
