### ISSUE TITLE
can not decode APICFrame picutreData (mimetype=image/png, encoding=UTF-16, description=Cover)

### ISSUE THREAD

**Issue by Empressia** [google/ExoPlayer#9087]
### Problem

I extracted the APICFrame from an MP3 file and tried to decode it with BitmapFactory#decodeByteArray.
but it returns null.

### MP3 file information

MP3 files are updated by mutagen (version 1.45.1 python library),
For AICFrames, the encoding is UTF-16, MIMEType is image/png, and description is "Cover".

### APICFrame#toString()

> APIC: mimeType=image/png, description=Cove�

It is dingy.

### Environment

* ExoPlayer version number -> 2.14.0
* Android version -> 11
* Android device -> Xperia 10 II

### extras

* When I updated description from "Cover" to ""(0 length string) by mutagen, i can get a bitmap expected (non null).
* When I updated encoding from UTF-16 to ISO-8859-1, i can get a bitmap expected (non null).
* When I updated image with JPEG, i can get a bitmap expected (non null).
* When I updated MP3 file with WMP, i get null by decoding.

**Comment by Empressia** [comment]
I made a mistake, so I'll fix it.

**Comment by Empressia** [comment]
fix UTF-8 to UTF-16 (I didn't know how to fix the title...).

**Comment by Empressia** [comment]
I added test case to my fork repository.
https://github.com/Empressia/ExoPlayer/tree/dev-v2-issue-9087
https://github.com/Empressia/ExoPlayer/commit/b0f0415d2221126fcba996fdda3ebfe33b9d1e6d

* Test Result.

    > expected: Hello World
    > but was : Hello World Ă̄Ԇ܈ऀ

**Comment by ojw28** [comment]
Thanks for reporting this. There's a small bug detecting string termination if (a) UTF-16 is used, and (b) the string starts at an non-even offset in the ID3 data. We'll push a fix.
