### ISSUE TITLE
Consider allowing alternative MimeTypes to handle device differences

### ISSUE THREAD

**Issue by IanDBird** [google/ExoPlayer#909]
One thing i've seen is that some devices use slightly different MimeTypes for a number of audio codecs (mainly DTS/DTS-HD/TrueHD). I think this might be because as far as i'm aware, this isn't strictly specified anywhere and is more of an adopted standard.

Of course, one stance would be to just not support these devices which are "wrong". I did however have a go to see what it would take to allow alternative MimeType lookups to allow their MediaCodec's to be used. I found the following changes were required:
 - Modify `MediaCodecUtil.getMediaCodecInfo` method to consider the specified `mimeType` but also any other alternatives known for that type.
 - Modify the `MediaFormat.getFrameworkMediaFormatV16` method to translate the `mimeType` into one specific for the device.
   - The way I did this was to simply add another method into the `MediaCodecUtil` to perform the lookup.

I actually have a patch that I could submit as a Pull Request for this, but thought it was unclear as to whether you consider this an ExoPlayer issue to be resolved, or whether these devices should simply not be supported. The device I was testing around with was the "Minix Neo", but I believe that the Sony Android TVs also use a different MimeType for DTS than that defined in ExoPlayer (which maybe they've fixed already in a recent FW update).

Thoughts?

**Comment by ojw28** [comment]
I'm unsure as to why the second bullet point would be necessary, if you were to do the first one. I can't think of a reason why we couldn't do the first one; that seems like a fairly sensible thing to do.

**Comment by IanDBird** [comment]
The reason I thought (think) the second point was required is that when initially testing, I found that when initialising the codec (in `MediaCodecTrackRenderer.configureCodec`) it resulted in a failure because an unknown or unexpected mime type was being specified in the provided `MediaFormat`. I thought it made sense to provide a mime type that the codec was expecting, and registered against, rather than what ExoPlayer was using internally.

**Comment by IanDBird** [comment]
If you're happy with the explanation for the second point, i'm happy to submit a PR with the suggested changes for further discussion?

**Comment by ojw28** [comment]
A PR would be the best way to proceed, yes.

**Comment by ojw28** [comment]
Decided not to do this for the time-being, but will reconsider in the future if it becomes a more widespread issue.
