### ISSUE TITLE
MediaItem.mediaId ?

### ISSUE THREAD

**Issue by dani3l3** [google/ExoPlayer#9098]
Hi, I had logic which was working fine up to version 2.13 that was using player.getCurrentMediaItem().mediaId --> this was giving me the URL of the mediaitem. But in 2.14 it's always null/empty and my code started failing....

I had to rewrite my logic using player.getCurrentWindowIndex() instead.... something along the lines of what's suggested on https://github.com/google/ExoPlayer/issues/2328 (which is a thread from 2017!) to make it work again.

Has this been an intentionl change or is it a regression? I couldn't understand it from release notes and such.

Thanks for any insight.

**Comment by icbaker** [comment]
This is the relevant release note (from the 2.14.0 release):

> * Use an empty string instead of the URI if the media ID is not explicitly set with `MediaItem.Builder.setMediaId(String)`.

If you want the URI, can you just use [`MediaItem#playbackProperties#uri`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/MediaItem.PlaybackProperties.html#uri)?

**Comment by dani3l3** [comment]
Ok thanks, I fixed it with the other method but I'll look into what you suggested.
Just to clarify, I was not using MediItem.Builder, but simply MediaItem.fromUri(url). I understand this needs to be set explicitly now.
