### ISSUE TITLE
Regarding deprecated classes

### ISSUE THREAD

**Issue by chandangit89** [google/ExoPlayer#9101]
hlo sir...
As per documentation .......PlayerNotificationManager has been deprecated and replaced by PlayerNotificationManager.Builder and so many methods are not there in the class ...for example....playerNotificationManager.setplayer() is not there in builder classs.
so now it is very difficult to code with PlayerNotificationManager.Builder

will u please provide a demo where notification is managed using Builder class

regards

**Comment by icbaker** [comment]
Only the constructors and static factory methods on `PlayerNotificationManager` are deprecated (in favour of the `PlayerNotificationManager.Builder`), [`PlayerNotificationManager#setPlayer`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/ui/PlayerNotificationManager.html#setPlayer(com.google.android.exoplayer2.Player)) is not deprecated.

**Comment by icbaker** [comment]
Closing as I've answered the specific example from the original post - if there's other functionality you can't find a non-deprecated alternative for, please reply and I'll try and help.
