### ISSUE TITLE
Adding same ad url for multiple MediaItems does not work

### ISSUE THREAD

**Issue by Debayudh** [google/ExoPlayer#9106]
While passing same List of MediaItems into player, if the same ad url is used for multiple Media Items, the ad plays only once and does not play for subsequent MediaItems.

**Comment by andrewlewis** [comment]
Please could you try passing a different `adsId` for each `MediaItem`? See the explanation here: https://exoplayer.dev/ad-insertion.html#playlists-with-ads

**Comment by giladna** [comment]
From what I know changing the correlator attribute  value with different timestamp each ad request solves it


samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dlinear&correlator=123456
