### ISSUE TITLE
Implicit PendingIntent Vulnerability in PlayerNotificationManager

### ISSUE THREAD

**Issue by daugeldauge** [google/ExoPlayer#9110]
It seems like pending intent created in [PlayerNotificationManager](https://github.com/google/ExoPlayer/blob/b2333c86c1eac9a1f95992960a8495f1e5b79200/library/ui/src/main/java/com/google/android/exoplayer2/ui/PlayerNotificationManager.java#L1599) violates Google Play policy (see https://support.google.com/faqs/answer/10437428). Component in base intent is not set and there is no FLAG_IMMUTABLE in pending intent.

**Comment by marcbaechinger** [comment]
Thanks for reporting!

I think this already landed in the dev-v2 branch but not in the release branch. Will be included with the next release:

https://github.com/google/ExoPlayer/commit/5ff2d24faba529a92d57be2f389fedf234560d96#diff-81e3997acc8088ad028a86594387431b3779700a7190124a9298a680896f76a3

From the doc you linked:

```
Intents can either specify the target component (Explicit Intent) or list a general 
action and let the operating system deliver the Intent to any component on the
device that registers an Intent Filter matching that action (Implicit Intent).
```

So beside the FLAG_IMMUTABLE we have to make sure the intent is explicit, which is it by setting the package:
From the Java Doc of setPackage():

```
Set an explicit application package name that limits the components this Intent will resolve to.
```
