### ISSUE TITLE
How the player parse url to IP address

### ISSUE THREAD

**Issue by iblh** [google/ExoPlayer#9117]
I would like to dive into the logic of url parser. But I only found how the UDP do ([UdpDataSource](https://github.com/google/ExoPlayer/blob/bd54394391b0527893f382c9d641b8a55ffca765/library/core/src/main/java/com/google/android/exoplayer2/upstream/UdpDataSource.java#L91-L119)) but couldn't find the TCP method.

Would very appreciate if someone could help me understand where is the function to implement the url parse to IP address?

**Comment by kim-vde** [comment]
This is handled by the libraries used by ExoPlayer (e.g. Cronet, OkHttp) or by the layers below, not by ExoPlayer directly.

**Comment by iblh** [comment]
> This is handled by the libraries used by ExoPlayer (e.g. Cronet, OkHttp) or by the layers below, not by ExoPlayer directly.

Thanks a lot, I have found that is implementd by [DefaultHttpDataSource](https://github.com/google/ExoPlayer/blob/bd54394391b0527893f382c9d641b8a55ffca765/library/common/src/main/java/com/google/android/exoplayer2/upstream/DefaultHttpDataSource.java) -> `java/net/URL.java`
