### ISSUE TITLE
Will ExoPlayer support 3D videos in the future?

### ISSUE THREAD

**Issue by don11995** [google/ExoPlayer#912]
Will ExoPlayer support 3D videos in the future? For example, I need this to support AndroidTV in my project. Thanks.

**Comment by ojw28** [comment]
I'm not aware of what it would mean for ExoPlayer to support 3D videos. Depending on how the TV supports 3D, it may "just work" already. For example, if the TV expects 3D content where each video frame is actually two frames side-by-side, this would work already. If you have a more specific question let us know.

**Comment by Avetri** [comment]
Side-by-side isn't a just 3D video format.
For true 3D video, such on the 3D BluRay disks, the player should support two additional video-output modes with frame packing (vertical and horizontal) and decoding of MVC (two separated TS or one SSIF). Also decoding of MVC requires two simultaneous hardware decoders.

**Comment by ojw28** [comment]
What does *just* mean in this context? The question remains pretty vague. What container format are you envisaging using here, how are the 3D frames packed within the container, and how do you envisage them being pushed to the display through Android's APIs?

**Comment by Avetri** [comment]
It means that side-by-side and over-and-under are only adaptation of existing infrastructure for needs of 3D. And they don't require special advantages of player. All 3D work makes TV Set when transforming one splitted frame onto two (left and right).

I don't know details about other containers (3D MKV or other) but 3D MVC, in usual case, is a common TS. But it has two (primary and secondary) FullHD video elementary streams in H264. This can be two dedicated TS files or one SSIF.

After decoding composer makes frame packing (FP) (one 1980*2240 or 4040*1080 frame, if I remember right) from two FullHD frames. And a playback device turns HDMI output in the according FP mode.

**Comment by ojw28** [comment]
Got it. It's unclear whether AndroidTV supports this at the platform level. I'll try and find out.

**Comment by don11995** [comment]
Ok, I'll try play some videos in 3D from my server and if there is some problem I'll write here. For now I have not any videos in 3D yet.

**Comment by ptran-gpfw** [comment]
If the 3D video stream has two video streams, each with its own TS packet ID, then I doubt ExoPlayer will work out of the box. Each stream needs its own MediaCodec instance and rendering Surface. Then, as @Avetri mentioned, every output frame will be need to composed from the contents of the two Surfaces.

You could try writing your own MediaCodecTrackRenderer.  Then instantiate two instances and direct the left-eye video track to one instance and direct the right-eye video track to the other.

**Comment by Avetri** [comment]
I have explained main points. But there are a few another specific tech. details and requirements.
Please look at Wiki about AVC, MVC, 2D Plus Delta, 3D Blu-Ray, etc.

**Comment by ojw28** [comment]
As per above, I would guess that side-by-side and over-and-under should "just work" if the TV supports it. Frame packing appears to be almost identical as a concept, with the caveat that there's some explicitly defined padding to separate the packed frames, and that it's explicitly defined that the resolution isn't halved as a result of the packing (because the total size in the packing direction is 2x individual frame + padding). Again, I would expect this format to "just work" if the TV supports it.

Approaches that require two video decoders and/or specific decoder support would require platform support, which I don't believe exists currently.
