### ISSUE TITLE
stop() cause crash

### ISSUE THREAD

**Issue by ab503044120** [google/ExoPlayer#9124]
the crash log is follow:
 java.lang.IllegalStateException
        at com.google.android.exoplayer2.util.Assertions.checkState(Assertions.java:84)
        at com.google.android.exoplayer2.util.ExoFlags$Builder.add(ExoFlags.java:54)
        at com.google.android.exoplayer2.util.ListenerSet$ListenerHolder.invoke(ListenerSet.java:280)
        at com.google.android.exoplayer2.util.ListenerSet.lambda$queueEvent$0(ListenerSet.java:170)
        at com.google.android.exoplayer2.util.-$$Lambda$ListenerSet$NbKDn9xtItiyMgYZmjIx_Sv1FFQ.run(Unknown Source:6)
        at com.google.android.exoplayer2.util.ListenerSet.flushEvents(ListenerSet.java:191)
        at com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo(ExoPlayerImpl.java:1340)
        at com.google.android.exoplayer2.ExoPlayerImpl.stop(ExoPlayerImpl.java:802)
        at com.google.android.exoplayer2.ExoPlayerImpl.stop(ExoPlayerImpl.java:772)
        at com.google.android.exoplayer2.SimpleExoPlayer.stop(SimpleExoPlayer.java:1589)

version is 2.24.1

**Comment by kim-vde** [comment]
It seems that `flagsBuilder.add()` is called after `flagsBuilder.build()` on the same object in [`ListenerHolder`](https://github.com/google/ExoPlayer/blob/r2.14.1/library/common/src/main/java/com/google/android/exoplayer2/util/ListenerSet.java) (`ExoFlags` was renamed  to`FlagSet` recently). This error does not occur on our demo app, and I don't see how it can be thrown by looking at the code.

Are you always accessing the player from the correct thread (see [note on threading](https://exoplayer.dev/hello-world.html#a-note-on-threading))? 

Could you please provide complete information as requested in the issue template (particularly clear reproduction steps). The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md). If you're unable to share [bug reports](https://developer.android.com/studio/debug/bug-report) or test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #1234" ("#1234" is replaced with your issue number). Please also update this issue to indicate you've done this.

> version is 2.24.1

This version doesn't exist. Please provide the correct one.

**Comment by ab503044120** [comment]
> It seems that `flagsBuilder.add()` is called after `flagsBuilder.build()` on the same object in [`ListenerHolder`](https://github.com/google/ExoPlayer/blob/r2.14.1/library/common/src/main/java/com/google/android/exoplayer2/util/ListenerSet.java) (`ExoFlags` was renamed to`FlagSet` recently). This error does not occur on our demo app, and I don't see how it can be thrown by looking at the code.
> 
> Are you always accessing the player from the correct thread (see [note on threading](https://exoplayer.dev/hello-world.html#a-note-on-threading))?
> 
> Could you please provide complete information as requested in the issue template (particularly clear reproduction steps). The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md). If you're unable to share [bug reports](https://developer.android.com/studio/debug/bug-report) or test content publicly, please send them to [dev.exoplayer@gmail.com](mailto:dev.exoplayer@gmail.com) using a subject in the format "Issue #1234" ("#1234" is replaced with your issue number). Please also update this issue to indicate you've done this.
> 
> > version is 2.24.1
> 
> This version doesn't exist. Please provide the correct one.

yes,I always accessing the player from the correct thread 
the correct version is 2.14.1

**Comment by kim-vde** [comment]
Hi! Please provide complete information as requested in the issue template (particularly **clear reproduction steps**). The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md). If you're unable to share [bug reports](https://developer.android.com/studio/debug/bug-report) or test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #1234" ("#1234" is replaced with your issue number). Please also update this issue to indicate you've done this.
