### ISSUE TITLE
Allow Exoplayer to toggle the buffering of segments without affecting playback. 

### ISSUE THREAD

**Issue by nick-tkachov** [google/ExoPlayer#9126]
### [REQUIRED] Use case description
In certain situations, we want to stop buffering segments without having the player stop playing. For example, if the user is on Wifi when they start playback, we would like to be able to stop loading segments if they switch to cellular and continue loading if we re-connect to wifi. 

Right now, exoplayer has no official way of doing this which means the implementation can change between releases. 

### Proposed solution
A Method on ExoPlayer (eg. `Exoplayer.allowDownloadingSegments` that will indicate to the player that the user wants to stop loading from network. This should act as if the network is slow without actually causing any network exceptions.

### Alternatives considered
Currently, we need to use LoadControl to accomplish this. We used to return false in "LoadControl.shouldContinueLoading".  in a recent Exoplayer version, we started to throw an exception when we stop loading with the buffer empty. We have to capture and ignore the exception now when we intend to be empty and not buffering.

**Comment by marcbaechinger** [comment]
I would have recommended using a custom `LoadControl`. As you mention this would certainly make the player transition to the `STATE_BUFFERING` when no more buffered data is available. 

What user experience would you expect when the user is on cellular and the player is running out of buffered data? Wouldn't you just pause the player?

> We have to capture and ignore the exception now when we intend to be empty and not buffering.

Can you clarify what exception you catch?
