### ISSUE TITLE
Live audio plays only first segment from 2.12.x version

### ISSUE THREAD

**Issue by cruiz666** [google/ExoPlayer#9128]
I'll send example and url to reproduce the issue via mail. Thanks

**Comment by kim-vde** [comment]
I have just requested access on the file you provided.

**Comment by cruiz666** [comment]
Done!

**Comment by kim-vde** [comment]
I can reproduce by trying the stream URI in the demo app. It is working in 2.12.3 but not in dev-v2. The content is live HLS. Can you have a look @christosts ?

**Comment by christosts** [comment]
@cruiz666, please grant me access to the file too

**Comment by cruiz666** [comment]
@christosts, done!

**Comment by christosts** [comment]
This is a duplicate of #9153 - please track that issue for updates.
