### ISSUE TITLE
Continue to output errors while playing FLAC files.

### ISSUE THREAD

**Issue by Empressia** [google/ExoPlayer#9131]
I play some mediaitems like below.

```java
public void play(List<MediaItem> items, int index) {
	SimpleExoPlayer player = this.Player;
	this.NotificationManager.setPlayer(player);
	player.setMediaItems(Items);
	player.seekToDefaultPosition(index);
	player.prepare();
	player.play();
}
```

When I called this in a FLAC file. I received error messages (not in mp3 and m4a files) (The sound is playing from the speakers).

>       com.google.android.exoplayer2.audio.AudioSink$UnexpectedDiscontinuityException: Unexpected audio track timestamp discontinuity: expected 1857596, got 1578956
>         at com.google.android.exoplayer2.audio.DefaultAudioSink.handleBuffer(DefaultAudioSink.java:792)
>         at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(MediaCodecAudioRenderer.java:637)
>         at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1917)
>         at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:843)
>         at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:945)
>         at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:478)
>         at android.os.Handler.dispatchMessage(Handler.java:102)
>         at android.os.Looper.loop(Looper.java:368)
>         at android.os.HandlerThread.run(HandlerThread.java:67)

The "expected" and "got" values are different every time
* extract from contiguous logs

    > Unexpected audio track timestamp discontinuity: expected 1857596, got 1578956
    > Unexpected audio track timestamp discontinuity: expected 3065033, got 3343673
    > Unexpected audio track timestamp discontinuity: expected 5572788, got 5201269
    > Unexpected audio track timestamp discontinuity: expected 5665669, got 5387029
    > Unexpected audio track timestamp discontinuity: expected 5479908, got 5758548
    > Unexpected audio track timestamp discontinuity: expected 7430385, got 7709024
    > Unexpected audio track timestamp discontinuity: expected 8823582, got 8359183
    > Unexpected audio track timestamp discontinuity: expected 9380861, got 9845260
    > Unexpected audio track timestamp discontinuity: expected 11145577, got 10681179
    > Unexpected audio track timestamp discontinuity: expected 12167256, got 12631655

* Environment
    * ExoPlayer version number -> 2.14.1
    * Android version -> 11
    * Android device -> Xperia 10 II

What does this log mean?
What should I do?

**Comment by kim-vde** [comment]
This means that the audio timestamps provided in the FLAC content provided do not correspond to what the `AudioSink` is expecting ([code](https://github.com/google/ExoPlayer/blob/r2.14.1/library/core/src/main/java/com/google/android/exoplayer2/audio/DefaultAudioSink.java#L791)).

Imagine you have a FLAC file with audio samples of duration 1 second each. The `AudioSink` would expect to receive timestamps 0, then 1 second, then 2 seconds, .... If the timestamps advertised in the samples metadata does not correspond, then this error is logged.

Please provide a test content if you need more details. If you're unable to share test content publicly, please send it to dev.exoplayer@gmail.com using a subject "Issue #9131" . Please also update this issue to indicate you've done this.

**Comment by Empressia** [comment]
Thanks for the explanation.
I've tried commercial music, so I can't share content.

As an other method, I tried to create my own Flac file, but I couldn't make a file that would cause this problem.

Therefore, I will try to ignore this log when playing the music in question.
