### ISSUE TITLE
Xiaomi Mi Box S + Tunneling + HEVC results in no video output until I seek

### ISSUE THREAD

**Issue by Stonos** [google/ExoPlayer#9133]
I have an HEVC DASH live stream which has the following issue on a Xiaomi Mi Box S (oneday) running Android TV 9:

If tunneling is disabled, the stream works as expected. However, if tunneling is enabled, then I can hear the audio, but there is no video output (black screen). The video will only start rendering once I seek the stream.

Tested with ExoPlayer v2.14.1

I have sent a bugreport & a sample stream to dev.exoplayer@gmail.com.

**Comment by moneytoo** [comment]
I'm experiencing similar video issues when attempting to play local HEVC content on the very same device (oneday) with tunneling enabled. Running ExoPlayer 2.15.0, device is also at its latest stable update.

**Comment by krocard** [comment]
Tunneling is known to have many device specific issues and it is rarely possible to work around them. As you pointed out, there seems to be a low level error message.

Unfortunately, it is risky to use tunneling if the device has not been tested to work with the media. You could keep it as an advance option of your app.

**Comment by tonihei** [comment]
As @krocard pointed out above, it's infeasible for us to workaround device-specific tunneling issues, so I'll close this issue. You may want to report this to Xiaomi in case they are interested in fixing this.
