### ISSUE TITLE
DASH with closed captions cea-608 displays repetead letters

### ISSUE THREAD

**Issue by CrashBashMD** [google/ExoPlayer#9135]
Issue happens with ExoPlayer demo app with version r2.14.1 as well as build from dev-v2 branch.
URL to content: https://bp-cdnlab.clarotvpr.com/bpk-vod/vod/default/90dcd9a7-6df7-48c4-a855-b9f08d66de4e/90dcd9a7-6df7-48c4-a855-b9f08d66de4e/index.mpd

Displayed captions from above stream in exo player demo app are messed. Looks like it displays duplicated subtitle packages.
![bug_cc](https://user-images.githubusercontent.com/19472471/123966333-9fe7ab00-d9b5-11eb-86d9-e7adcc744152.png)

On reference dash player and e.g. VLC player it works fine. (http://reference.dashif.org/dash.js/v3.0.0/samples/dash-if-reference-player/index.html)
![fine_CC](https://user-images.githubusercontent.com/19472471/123965283-93168780-d9b4-11eb-8967-06092ef37000.png)

To reproduce please play above dash manifest and enable CC. Captions are visible when people talk in the movie. (many talks is around 62 minute). 

When debugging I found that _Cea608Decoder_ decode buffers with same data twice (same signs and timestamp) 

- ExoPlayer version number :2.14.1
- Android version (at least android 8 and 9)
- Android device (at least samsung s7)

**Comment by icbaker** [comment]
I can reproduce the problem with the media provided. I don't know what the root cause is yet.

**Comment by icbaker** [comment]
Sorry for the lack of follow-up - I took another look at this on Monday but it seems the stream is no longer active (it returns 404 errors).

Would it be possible to provide a permanently available stream? I'll try to take another look when I get some available time.
