### ISSUE TITLE
IllegalArgumentException in PlaybackStatsListener

### ISSUE THREAD

**Issue by zubcoco** [google/ExoPlayer#9138]
Hello,

We see this error sometimes on our application since we updated exoplayer to 2.13.x (2.13.3).
Why does this exception occur?

com.google.android.exoplayer2.util.Assertions.checkArgument (Assertions.java:41)
com.google.android.exoplayer2.analytics.PlaybackStatsListener$PlaybackStatsTracker.updatePlaybackState (PlaybackStatsListener.java:677)
com.google.android.exoplayer2.analytics.PlaybackStatsListener$PlaybackStatsTracker.onFinished (PlaybackStatsListener.java:475)
com.google.android.exoplayer2.analytics.PlaybackStatsListener.onSessionFinished (PlaybackStatsListener.java:183)
com.google.android.exoplayer2.analytics.DefaultPlaybackSessionManager.finishAllSessions (DefaultPlaybackSessionManager.java:247)
com.google.android.exoplayer2.analytics.PlaybackStatsListener.onEvents (PlaybackStatsListener.java:291)
com.google.android.exoplayer2.analytics.AnalyticsCollector.lambda$setPlayer$1 (AnalyticsCollector.java:141)
com.google.android.exoplayer2.analytics.AnalyticsCollector.lambda$setPlayer$1$AnalyticsCollector (AnalyticsCollector.java)
com.google.android.exoplayer2.analytics.-$$Lambda$AnalyticsCollector$yS3z67Oa1f_t9PmuRvwn2pyVDcQ.invoke (-.java:8)
com.google.android.exoplayer2.util.ListenerSet$ListenerHolder.release (ListenerSet.java:287)
com.google.android.exoplayer2.util.ListenerSet.release (ListenerSet.java:230)
com.google.android.exoplayer2.util.ListenerSet.handleMessage (ListenerSet.java:266)
com.google.android.exoplayer2.util.ListenerSet.lambda$eEvjP-IE0x3J2lRvKfFbbjRFRvc (ListenerSet.java)
com.google.android.exoplayer2.util.-$$Lambda$ListenerSet$eEvjP-IE0x3J2lRvKfFbbjRFRvc.handleMessage (-.java:2)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:193)
android.app.ActivityThread.main (ActivityThread.java:6718)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:858)

**Comment by kim-vde** [comment]
The assertion is failing on [this line](https://github.com/google/ExoPlayer/blob/r2.13.3/library/core/src/main/java/com/google/android/exoplayer2/analytics/PlaybackStatsListener.java#L677). It checks that the event that triggered the playback state update did not occur before the previous update, or in other words that the playback state updates are executed in the order of events.

Could this be the same issue as in #8675, which should have been fixed in 2.14?

If not, please provide clear reproduction steps (by sharing a sample test app for example).

**Comment by zubcoco** [comment]
We don't have reproduction steps. We only see the crash on Firebase Crashlytics.

It could be the same issue as in #8675... We'll update the exoplayer version to 2.14 soon.

If the error come back again, I'll reopen a new issue.

Thanks to you for the quick answer.
