### ISSUE TITLE
Dash with Widevine Fails to parse Adaption Set.

### ISSUE THREAD

**Issue by Amritpal33** [google/ExoPlayer#914]
Hi,
    I am using Widevine DRM with DASH Streaming. We are facing issue in parsing few Representation due to which Player throws the following Error.

Another issue is The Audio keeps on playing on the lowest bitrate while the Video Stream goes Adaptive.

Demo url for Testing:
http://wvcontent.jio.ril.com/test/0_07ugllju.mpd

Proxy URL:
http://wvproxy1.jio.ril.com/proxy?video_id=1000000184

10-30 18:51:22.003 22914-22914/com.jio.media.widevinesample I/ExoPlayerImpl: Init 1.4.2
10-30 18:51:22.006 22914-22914/com.jio.media.widevinesample D/EventLogger: start [0]
10-30 18:51:22.006 22914-22914/com.jio.media.widevinesample D/EventLogger: state [0.00, false, P]
10-30 18:51:22.023 22914-22914/com.jio.media.widevinesample D/EventLogger: state [0.02, true, P]
10-30 18:51:22.037 22914-22945/com.jio.media.widevinesample E/Surface: getSlotFromBufferLocked: unknown buffer: 0xb3664170
10-30 18:51:22.048 22914-23083/com.jio.media.widevinesample E/LoadTask: Unexpected exception loading stream
10-30 18:51:22.048 22914-23083/com.jio.media.widevinesample E/LoadTask: java.lang.IllegalStateException
10-30 18:51:22.048 22914-23083/com.jio.media.widevinesample E/LoadTask:     at com.google.android.exoplayer.util.Assertions.checkState(Assertions.java:66)
10-30 18:51:22.048 22914-23083/com.jio.media.widevinesample E/LoadTask:     at com.google.android.exoplayer.dash.mpd.MediaPresentationDescriptionParser$ContentProtectionsBuilder.endRepresentation(MediaPresentationDescriptionParser.java:706)
10-30 18:51:22.048 22914-23083/com.jio.media.widevinesample E/LoadTask:     at com.google.android.exoplayer.dash.mpd.MediaPresentationDescriptionParser.parseAdaptationSet(MediaPresentationDescriptionParser.java:211)
10-30 18:51:22.048 22914-23083/com.jio.media.widevinesample E/LoadTask:     at com.google.android.exoplayer.dash.mpd.MediaPresentationDescriptionParser.parsePeriod(MediaPresentationDescriptionParser.java:164)
10-30 18:51:22.048 22914-23083/com.jio.media.widevinesample E/LoadTask:     at com.google.android.exoplayer.dash.mpd.MediaPresentationDescriptionParser.parseMediaPresentationDescription(MediaPresentationDescriptionParser.java:124)
10-30 18:51:22.048 22914-23083/com.jio.media.widevinesample E/LoadTask:     at com.google.android.exoplayer.dash.mpd.MediaPresentationDescriptionParser.parse(MediaPresentationDescriptionParser.java:95)
10-30 18:51:22.048 22914-23083/com.jio.media.widevinesample E/LoadTask:     at com.google.android.exoplayer.dash.mpd.MediaPresentationDescriptionParser.parse(MediaPresentationDescriptionParser.java:53)
10-30 18:51:22.048 22914-23083/com.jio.media.widevinesample E/LoadTask:     at com.google.android.exoplayer.upstream.UriLoadable.load(UriLoadable.java:93)
10-30 18:51:22.048 22914-23083/com.jio.media.widevinesample E/LoadTask:     at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
10-30 18:51:22.048 22914-23083/com.jio.media.widevinesample E/LoadTask:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
10-30 18:51:22.048 22914-23083/com.jio.media.widevinesample E/LoadTask:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
10-30 18:51:22.048 22914-23083/com.jio.media.widevinesample E/LoadTask:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
10-30 18:51:22.048 22914-23083/com.jio.media.widevinesample E/LoadTask:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
10-30 18:51:22.048 22914-23083/com.jio.media.widevinesample E/LoadTask:     at java.lang.Thread.run(Thread.java:818)
10-30 18:51:22.098 22914-22914/com.jio.media.widevinesample E/EventLogger: internalError [0.09, rendererInitError]
10-30 18:51:22.098 22914-22914/com.jio.media.widevinesample E/EventLogger: com.google.android.exoplayer.upstream.Loader$UnexpectedLoaderException: Unexpected IllegalStateException: null
10-30 18:51:22.098 22914-22914/com.jio.media.widevinesample E/EventLogger:     at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:222)
10-30 18:51:22.098 22914-22914/com.jio.media.widevinesample E/EventLogger:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
10-30 18:51:22.098 22914-22914/com.jio.media.widevinesample E/EventLogger:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
10-30 18:51:22.098 22914-22914/com.jio.media.widevinesample E/EventLogger:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
10-30 18:51:22.098 22914-22914/com.jio.media.widevinesample E/EventLogger:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
10-30 18:51:22.098 22914-22914/com.jio.media.widevinesample E/EventLogger:     at java.lang.Thread.run(Thread.java:818)
10-30 18:51:22.098 22914-22914/com.jio.media.widevinesample E/EventLogger:  Caused by: java.lang.IllegalStateException
10-30 18:51:22.098 22914-22914/com.jio.media.widevinesample E/EventLogger:     at com.google.android.exoplayer.util.Assertions.checkState(Assertions.java:66)
10-30 18:51:22.098 22914-22914/com.jio.media.widevinesample E/EventLogger:     at com.google.android.exoplayer.dash.mpd.MediaPresentationDescriptionParser$ContentProtectionsBuilder.endRepresentation(MediaPresentationDescriptionParser.java:706)
10-30 18:51:22.098 22914-22914/com.jio.media.widevinesample E/EventLogger:     at com.google.android.exoplayer.dash.mpd.MediaPresentationDescriptionParser.parseAdaptationSet(MediaPresentationDescriptionParser.java:211)
10-30 18:51:22.098 22914-22914/com.jio.media.widevinesample E/EventLogger:     at com.google.android.exoplayer.dash.mpd.MediaPresentationDescriptionParser.parsePeriod(MediaPresentationDescriptionParser.java:164)
10-30 18:51:22.098 22914-22914/com.jio.media.widevinesample E/EventLogger:     at com.google.android.exoplayer.dash.mpd.MediaPresentationDescriptionParser.parseMediaPresentationDescription(MediaPresentationDescriptionParser.java:124)
10-30 18:51:22.098 22914-22914/com.jio.media.widevinesample E/EventLogger:     at com.google.android.exoplayer.dash.mpd.MediaPresentationDescriptionParser.parse(MediaPresentationDescriptionParser.java:95)
10-30 18:51:22.098 22914-22914/com.jio.media.widevinesample E/EventLogger:     at com.google.android.exoplayer.dash.mpd.MediaPresentationDescriptionParser.parse(MediaPresentationDescriptionParser.java:53)
10-30 18:51:22.098 22914-22914/com.jio.media.widevinesample E/EventLogger:     at com.google.android.exoplayer.upstream.UriLoadable.load(UriLoadable.java:93)
10-30 18:51:22.098 22914-22914/com.jio.media.widevinesample E/EventLogger:     at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
10-30 18:51:22.098 22914-22914/com.jio.media.widevinesample E/EventLogger:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423) 
10-30 18:51:22.098 22914-22914/com.jio.media.widevinesample E/EventLogger:     at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
10-30 18:51:22.098 22914-22914/com.jio.media.widevinesample E/EventLogger:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
10-30 18:51:22.098 22914-22914/com.jio.media.widevinesample E/EventLogger:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
10-30 18:51:22.098 22914-22914/com.jio.media.widevinesample E/EventLogger:     at java.lang.Thread.run(Thread.java:818) 
10-30 18:51:22.107 22914-22914/com.jio.media.widevinesample E/EventLogger: playerFailed [0.10]
10-30 18:51:22.107 22914-22914/com.jio.media.widevinesample E/EventLogger: com.google.android.exoplayer.upstream.Loader$UnexpectedLoaderException: Unexpected IllegalStateException: null
10-30 18:51:22.107 22914-22914/com.jio.media.widevinesample E/EventLogger:     at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:222)
10-30 18:51:22.107 22914-22914/com.jio.media.widevinesample E/EventLogger:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
10-30 18:51:22.107 22914-22914/com.jio.media.widevinesample E/EventLogger:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
10-30 18:51:22.107 22914-22914/com.jio.media.widevinesample E/EventLogger:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
10-30 18:51:22.107 22914-22914/com.jio.media.widevinesample E/EventLogger:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
10-30 18:51:22.107 22914-22914/com.jio.media.widevinesample E/EventLogger:     at java.lang.Thread.run(Thread.java:818)
10-30 18:51:22.107 22914-22914/com.jio.media.widevinesample E/EventLogger:  Caused by: java.lang.IllegalStateException
10-30 18:51:22.107 22914-22914/com.jio.media.widevinesample E/EventLogger:     at com.google.android.exoplayer.util.Assertions.checkState(Assertions.java:66)
10-30 18:51:22.107 22914-22914/com.jio.media.widevinesample E/EventLogger:     at com.google.android.exoplayer.dash.mpd.MediaPresentationDescriptionParser$ContentProtectionsBuilder.endRepresentation(MediaPresentationDescriptionParser.java:706)
10-30 18:51:22.107 22914-22914/com.jio.media.widevinesample E/EventLogger:     at com.google.android.exoplayer.dash.mpd.MediaPresentationDescriptionParser.parseAdaptationSet(MediaPresentationDescriptionParser.java:211)
10-30 18:51:22.107 22914-22914/com.jio.media.widevinesample E/EventLogger:     at com.google.android.exoplayer.dash.mpd.MediaPresentationDescriptionParser.parsePeriod(MediaPresentationDescriptionParser.java:164)
10-30 18:51:22.107 22914-22914/com.jio.media.widevinesample E/EventLogger:     at com.google.android.exoplayer.dash.mpd.MediaPresentationDescriptionParser.parseMediaPresentationDescription(MediaPresentationDescriptionParser.java:124)
10-30 18:51:22.107 22914-22914/com.jio.media.widevinesample E/EventLogger:     at com.google.android.exoplayer.dash.mpd.MediaPresentationDescriptionParser.parse(MediaPresentationDescriptionParser.java:95)
10-30 18:51:22.107 22914-22914/com.jio.media.widevinesample E/EventLogger:     at com.google.android.exoplayer.dash.mpd.MediaPresentationDescriptionParser.parse(MediaPresentationDescriptionParser.java:53)
10-30 18:51:22.107 22914-22914/com.jio.media.widevinesample E/EventLogger:     at com.google.android.exoplayer.upstream.UriLoadable.load(UriLoadable.java:93)
10-30 18:51:22.107 22914-22914/com.jio.media.widevinesample E/EventLogger:     at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
10-30 18:51:22.107 22914-22914/com.jio.media.widevinesample E/EventLogger:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423) 
10-30 18:51:22.107 22914-22914/com.jio.media.widevinesample E/EventLogger:     at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
10-30 18:51:22.107 22914-22914/com.jio.media.widevinesample E/EventLogger:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
10-30 18:51:22.107 22914-22914/com.jio.media.widevinesample E/EventLogger:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
10-30 18:51:22.107 22914-22914/com.jio.media.widevinesample E/EventLogger:     at java.lang.Thread.run(Thread.java:818) 
10-30 18:51:22.108 22914-22914/com.jio.media.widevinesample D/EventLogger: state [0.10, true, I]

Kindly help me know where can issue possibly be.

**Comment by ojw28** [comment]
The issue is that there are representations with different ContentProtection elements inside of a single adaptation set. Specifically, the HD streams have a different ContentProtection compared to the SD streams. This goes against the DASH IF Interoperability recommendations, and isn't something that we support.

For Widevine, the expected behavior is that a single license response should contain all of the keys that are associated with the media. This means you can promote an arbitrary ContentProtection element to the AdaptationSet level of the manifest. So it can look like:

```
<MPD ...>
  <Period>
    <AdaptationSet id="0" contentType="video" ...>
      <ContentProtection value="cenc" schemeIdUri="urn:mpeg:dash:mp4protection:2011" cenc:default_KID="a3397cf3-ecb8-5585-93fe-8cee74ccf638"/>
      <ContentProtection schemeIdUri="urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed">
        <cenc:pssh>AAAAR3Bzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAACcIARIQozl88+y4VYWT/ozudMz2OBoIcmVsaWFuY2UiBRAAAAGEMgA=</cenc:pssh>
      </ContentProtection>
      <Representation id="0" ....>
      <Representation id="1" ....>
      ....
````

Where the ContentProtection you promote can be chosen arbitrarily.

**Comment by Amritpal33** [comment]
Thanks a lot for your help.The Content protection issue has been resolved.
The other Concern is The Audio Streaming is not Adaptive. shall i raise this as a Separate Question Meanwhile We close this one.

Cheers!!

**Comment by Amritpal33** [comment]
Please Provide your comments  then only it get Closed.
"Another issue is The Audio keeps on playing on the lowest bitrate while the Video Stream goes Adaptive."

**Comment by ojw28** [comment]
It's working as intended that audio isn't adaptive (it's quite hard to simultaneously adapt both audio and video, and since video is the dominant stream, it makes sense to adapt it and keep the audio fixed). Note that all of the available audio tracks will be exposed in ExoPlayer's track query/selection methods, which allow you to query the available tracks and change the selection. It's probably the case that the first track in the AdaptationSet is selected by default, so you could change the order to put the default one first.
