### ISSUE TITLE
Please share a sample for HLS+Widevine

### ISSUE THREAD

**Issue by GouravSna** [google/ExoPlayer#9147]
Hi Team,

If possible, can you please share a sample for hls with widevine ?

**Comment by icbaker** [comment]
There's an example for configuring a media item for widevine here: https://exoplayer.dev/media-items.html#protected-content

You can also find concrete examples of Widevine-protected DASH in the demo app JSON file: 
https://github.com/google/ExoPlayer/blob/b2333c86c1eac9a1f95992960a8495f1e5b79200/demos/main/src/main/assets/media.exolist.json#L32-L39

The ExoPlayer code for playing widevine-protected HLS vs widevine-protected DASH should be basically the same.

I'm going to close this as I think this answers the question, but please reply here if I've misunderstood.

**Comment by GouravSna** [comment]
Thanks @icbaker  for the answer but I require an example for HLS-Widevine. I agree that both would be same.
But wanted to understand that will EXT-X-KEY be the same for all the playlists and how it is being structured. 

I tried searching on Google but could not find any sample stream.

**Comment by icbaker** [comment]
I'm afraid that constructing valid media is outside the scope of this issue tracker - we can't help you with how to structure your HLS playlist.
