### ISSUE TITLE
Widevine DRM Content Not Playing On Android Box After Ads

### ISSUE THREAD

**Issue by ChesterAL-GH** [google/ExoPlayer#9149]
Hi Team, we have an issue with our app when using most AndroidTV and Android Boxex. After the preroll ad, either the main content displays a black screen and audio can only be heard before it crashes, or the player crashes after ads. THis is only experienced when playing DRM contents (no issues with playing live and non DRM contents). And when there is no ads, we could stream the content with no issues at all.

I got the logcat file for both working (No ads), and not working (with ads) when playing a DRM content. Since it contains sensitive information, I will email both logcat files on dev.exoplayer@gmail.com.

Hope you could highlight us with the issue.

**Comment by icbaker** [comment]
The two logcats provided seem to differ in more than just ads vs non-ads. One (the failure with ads) seems to be using [MediaPlayer](https://developer.android.com/reference/android/media/MediaPlayer) in addition to ExoPlayer. 

In the failure case there's lots of logging like this (which I suspect is coming from MediaPlayer):
```
I/NU-AmNuPlayer: [getCurrentPosition]
```

I also can't see any details of an ExoPlayer playback error in the failure logs.

Whereas in the successful case (no ads) there's no mention of `AmNuPlayer`.

Are the ads being played with MediaPlayer while the content is being played with ExoPlayer?

Transitioning smoothly from MediaPlayer to ExoPlayer isn't something we really support - it's not clear from the report or logs provided whether the crash is occurring in MediaPlayer or ExoPlayer.

Is it possible to use ExoPlayer for the ad playbacks as well as the content? Then it's likely we'd be able to provide more detailed help with any crashes you experience.

**Comment by ChesterAL-GH** [comment]
Hi icbaker! yes we are using MediaPlayer.. We're going to try that route first on playing the video on ExoPlayer for both ads and content. If anything comes up, I'll just refer this issue.. thank you getting back to us on this appreciate it a lot.
