### ISSUE TITLE
Seekbar not working with some mp3 files

### ISSUE THREAD

**Issue by tosam144** [google/ExoPlayer#9150]
I use exoplayer to stream mp3 files that are located on a private server. I exerpience a strange problem: With some mp3 files, exoplayer's seekbar shows 100% and does not move (and cannot be moved by the user). With other mp3 files, the seekbar works as expected. So far, I was not able to identify the difference between a working and a non-working mp3. However, I discovered that if I convert the non-working mp3 into a new mp3 (with the same properties), the seekbar for the new mp3 suddenly works as expected. I use Audacity for conversion. I am wondering what causes exoplayer's seekbar to sometimes work and sometimes not. Does anyone have a hint? Thanks!

**Comment by icbaker** [comment]
It's impossible to say for sure without access to the media, but ExoPlayer probably considers the file unseekable (efficiently): https://exoplayer.dev/troubleshooting.html#why-are-some-media-files-not-seekable

It's likely that when you re-encode it with Audacity, even if it looks like you keep all the properties the same, it adds the extra metadata needed to allow efficient seeking into the file - hence the result is seekable.

I'm going to close this as I think this answers the question.
