### ISSUE TITLE
Ad pod timer can remain on screen after finishing ads

### ISSUE THREAD

**Issue by usopphammer** [google/ExoPlayer#9152]
Hello

In our application we observe 2 bugs from time to time
1. ad timer overlaps with other ads
2. ad times remains on screen after finishing ads

ExoPlayer version 2.14
minSdkVersion 21
There are no errors in the adb logs

Could someone tell me if this is a known issue and how it can be fixed?

![image](https://user-images.githubusercontent.com/86966407/124481911-7661c180-ddb1-11eb-89a0-899f495b40e0.png)
![ad on screen](https://user-images.githubusercontent.com/86966407/124482024-8c6f8200-ddb1-11eb-98cf-21a3c522b4f0.jpeg)

**Comment by icbaker** [comment]
Please can you provide more info:
* How often does this reproduce? (You say "from time to time" - can you estimate e.g. 5/10 times?)
* Are those subtitles in the screenshot sideloaded via `MediaItem.Builder#setSubtitles` or are they embedded in the stream?
* Please either provide a stream/file we can use to reproduce the issue in the demo app, or reproduce it yourself in the demo app and capture a bug report (`adb bugreport`) and send it to us. Please either post the media/bug report here or send it to dev.exoplayer@gmail.com using a subject in the format "Issue #1234" (where "#1234" should be replaced with this issue number.) Please also update this issue to indicate you’ve done this.
