### ISSUE TITLE
Slow motion video rotation ignored

### ISSUE THREAD

**Issue by gmbett** [google/ExoPlayer#9154]
Hi,

I'm trying to evaluate Exoplayer so we can use it in our Android TV application but I noticed one issue with slow motion videos: The 90° rotation that is present in the Exif info is completely ignored.

I found this issue that was reported before: https://github.com/google/ExoPlayer/issues/8928, which seems to be what I'm also seeing.

The problematic file is .mp4 file that was recorded using a Google Pixel 3XL with Android 11, the file is uploaded (without modifications) to our servers and from there is "downloaded" by the player.

I also tried the demo app (on the TV) and the same rotation issue can be reproduced, but when the demo app is executed on a mobile device (same Pixel device) then the issue is not triggered... so I'm not sure what's going on

The file can be downloaded from [here](https://library.prod.mdl.swisscom.ch/download/~L0070042A3C5988AA001970FA38F66235CD3D017AFF3B83646E364F11786C4BB9/Storage::Photos::Asset::VWRweEM4ckRkMGtDeUpuQzh2Mmttdz09).

BTW, I'm using the latest version **2.14.1**

**Comment by kim-vde** [comment]
The rotation seems indeed correctly applied on phones (the red line on the video must be horizontal, at the bottom of the screen, is that right?). I tried to reproduce with a TV emulator but the video was also correctly playing.

I am not able to test on a real TV device at the moment. In the mean time, can you give me more information:
1. On what TV model(s) does the issue occur?
2. Does it work correctly on some other TV models?
3. Does it work correctly with [MediaPlayer](https://developer.android.com/reference/android/media/MediaPlayer)?
4. Does it work correctly with other rotated videos?

Note that this is not the same issue as in #8923 as the transformation matrix is correct here. This looks like a TV specific issue.

**Comment by andrewlewis** [comment]
Just to add something to be aware of: there is variation in how decoders handle rotation across API versions (see the [MediaCodec documentation](https://developer.android.com/reference/android/media/MediaCodec#transformations-when-rendering-onto-surface))

**Comment by gmbett** [comment]
Hi Kim,

Thank for checking... just to understand a bit... is this a codec issue? So that's why it works fine on some devices?

>The rotation seems indeed correctly applied on phones (the red line on the video must be horizontal, at the bottom of the screen, is that right?).

Yes, that is correct. The red line should be at the bottom

> I tried to reproduce with a TV emulator but the video was also correctly playing

Yes, I also checked this and in the emulator it works fine.

> On what TV model(s) does the issue occur?

I'm not sure if is a problem of the TV... or the TV box where the Android application is running. That's why I asked if is a codec issue. One of the TV were we checked is a 65'' LG OLED TV - B9 3.840 x 2.160 

>Does it work correctly on some other TV models?

So far no... but again I'm not sure if is a problem of the TV or the TV box.

>Does it work correctly with MediaPlayer?

I don't know. I need to check.

>Does it work correctly with other rotated videos?

All slow motion videos that are recorded in portrait mode are displayed wrong. But slow motion videos that are recorded in landscape are displayed properly. 

Other video formats (time lapse or normal) that are recorded in portrait mode are also displayed properly.

**Comment by gmbett** [comment]
The TV box I'm using has Android 8.0 (API level 26). Also I forgot to mention that when onVideoSizeChanged(videoSize: VideoSize) is invoked, I can see that the **unappliedRotationDegrees** is always 0.

**Comment by kim-vde** [comment]
> Thank for checking... just to understand a bit... is this a codec issue? So that's why it works fine on some devices?

Yes, the problem is probably that the decoder ignores the rotation degree.

> I'm not sure if is a problem of the TV... or the TV box where the Android application is running. That's why I asked if is a codec issue. One of the TV were we checked is a 65'' LG OLED TV - B9 3.840 x 2.160

The problem is probably in the TV box as it is decoder-related. You should report it to the TV box manufacturer.

**Comment by gmbett** [comment]
Hi,

Today I tried to play the same video with MediaPlayer and the same issue is triggered (the video is rotated).

Now, the funny thing is that with our current video player (VLC 3.0.10) the video is played properly, maybe they are doing something different?

**Comment by kim-vde** [comment]
> Now, the funny thing is that with our current video player (VLC 3.0.10) the video is played properly, maybe they are doing something different?

Yes, that's possible. It might not be using the same video decoder for instance (e.g. software decoder instead of hardware one).

**Comment by LukasHohlSCM** [comment]
The issue is specific to Android 8.0. It was introduced with this commit: 
https://android.googlesource.com/platform/frameworks/av/+/afb43f76821e6a63e17e6484289a40430ada6978

It was later solved with this commit (not clear if by accident or on purpose):
https://android.googlesource.com/platform/frameworks/av/+/002e413a5a7460a32790ed08408085a6062f4054

We will solve it by adding "'rotation-degrees" back to the code. 



For your reference, this is the information we got from our STB SoC vendor:

The issue comes from ‘/frameworks/av/media/libstagefright/MediaCodec.cpp’, line705:
```
status_t MediaCodec::configure(
        const sp<AMessage> &format,
        const sp<Surface> &surface,
        const sp<ICrypto> &crypto,
        const sp<IDescrambler> &descrambler,
        uint32_t flags) {
    sp<AMessage> msg = new AMessage(kWhatConfigure, this);

    if (mIsVideo) {
        format->findInt32("width", &mVideoWidth);
        format->findInt32("height", &mVideoHeight);
        if (!format->findInt32(kCodecRotation/*it is "rotation-degrees" on Android_N*/, &mRotationDegrees)) {
            mRotationDegrees = 0;
        }
```

If changing 'kCodecRotation' to 'rotation-degrees' then issue disappeared.

When getting the rotation-degrees info, it read "rotation-degrees" on Android_N. But not sure why it changes to 'kCodecRotation' (“android.media.mediacodec.rotation-degrees“) on Android_O. Besides, I notice that from Android_8.1, it has changed back "rotation-degrees".

**Comment by kim-vde** [comment]
Ah, the issue was in the framework then, not in the codec. Interesting. I don't think we can work around this in ExoPlayer unfortunately.
