### ISSUE TITLE
Can not parse video type when play H263.

### ISSUE THREAD

**Issue by lsgfly** [google/ExoPlayer#9158]
Can not parse video type when play H263.
when atomType is s263, It can be parsed correctly.
but when atomType is H263, it can not be parsed correctly.

This is the video.
https://user-images.githubusercontent.com/47651022/124697890-34a05a80-df1a-11eb-9f41-a7c4d4328314.mp4

Exo version:
2.14.0

Android version:
android 10

**Comment by kim-vde** [comment]
I have added support. This should be working now.
