### ISSUE TITLE
Exoplayer MPEG - 2 Stream Problem

### ISSUE THREAD

**Issue by yachana1** [google/ExoPlayer#9165]
Hi ,

My problem regarding Exoplayer not playing video of MPEG-2 Stream, only Audio is there as I am trying to play it out. Whenever I tried, it shows media includes video tracks but none are playable.

Please help me to build the exoplayer release to play the MPEG-2 Stream.

I have added the download link for exoplayer, from where I have downloaded. Also adding one MPEG-2 Stream for your support to test the audio and video in the build.

Exoplayer - https://github.com/google/ExoPlayer
MPEG-2 Stream - https://drive.google.com/file/d/1D89V6i6y2g3zs9yetSbcFtIt4v_Gr40G/view?usp=sharing

**Comment by yachana1** [comment]
can anyone help me ?

**Comment by yachana1** [comment]
Marc, please could you take a look?

**Comment by icbaker** [comment]
> Whenever I tried, it shows media includes video tracks but none are playable.

That toast in the demo app suggests your device doesn't support decoding MPEG-2 video: https://exoplayer.dev/troubleshooting.html#why-does-content-fail-to-play-but-no-error-is-surfaced

Android devices are not required to support MPEG-2 video: https://developer.android.com/guide/topics/media/media-formats#video-formats

Without a suitable video decoder, ExoPlayer won't be able to play the content. I would suggest either using a device that has an MPEG-2 decoder, or transcoding your content to a format that's more widely supported.
