### ISSUE TITLE
Cant play encrypted video with clearkey drm scheme in Exoplayer2

### ISSUE THREAD

**Issue by grovertb** [google/ExoPlayer#9169]
Hi, I'm having trouble playing an .mpd file with DRM (ClearKey).

This code snippet works for me in my web environment.

```js
var player = new Clappr.Player({
  parentId: '#player',
  autoPlay: true,
  plugins: [DashShakaPlayback],
  source: 'http://localhost:8080/live/manifest.mpd',
  shakaConfiguration: {
    drm: {
      clearKeys: {
        '2f49373e9a10d42964a79530e148ac19': 'fd38b9616945021315f376c5a1b9e7c0'
      }
    }
  },
  height: 360,
  width: 640
})
```
kid => 2f49373e9a10d42964a79530e148ac19
kid Base64Url => L0k3PpoQ1Clkp5Uw4UisGQ
k => fd38b9616945021315f376c5a1b9e7c0
k Base64Url => /Ti5YWlFAhMV83bFobnnwA

I replaced / by _ as indicated in the documentation https://www.w3.org/TR/encrypted-media/#using-base64url

```java
String keyString = "{\"keys\":[{\"kty\":\"oct\",\"k\":\"_Ti5YWlFAhMV83bFobnnwA\",\"kid\":\"L0k3PpoQ1Clkp5Uw4UisGQ\"}],\"type\":\"temporary\"}";
MediaDrmCallback drmCallback = new LocalMediaDrmCallback(keyString.getBytes());
                        DrmSessionManager drmSessionManager = new DefaultDrmSessionManager.Builder()
                                .setMultiSession(true)
                                .setUuidAndExoMediaDrmProvider(Assertions.checkNotNull(Util.getDrmUuid("clearkey")), FrameworkMediaDrm.DEFAULT_PROVIDER)
                                .build(drmCallback);
                                
mediaSource = new DashMediaSource.Factory(dataSourceFactory).setDrmSessionManager(drmSessionManager).createMediaSource(MediaItem.fromUri(urlStream));
```

I have tried different ways but cannot reproduce the live one.
I hope you can help me with some solution. Thank you!

Issues:
https://github.com/google/ExoPlayer/issues/3856
https://github.com/google/ExoPlayer/issues/3201
https://github.com/google/ExoPlayer/issues/3138

Note: In the player it shows me this way

![Screenshot_20210709-004447_PlayerGO](https://user-images.githubusercontent.com/9616253/125032241-49ccd480-e053-11eb-8ea7-abac0c6ee6f1.jpg)

**Comment by icbaker** [comment]
There isn't enough info here to identify what might be the problem.

Please provide a link to media we can use to reproduce the problem. Please either upload it here or send to dev.exoplayer@gmail.com using a subject in the format "Issue #1234" (where "#1234" should be replaced with this issue number.) Please also update this issue to indicate you’ve done this.

**Comment by grovertb** [comment]
> There isn't enough info here to identify what might be the problem.
> 
> Please provide a link to media we can use to reproduce the problem. Please either upload it here or send to [dev.exoplayer@gmail.com](mailto:dev.exoplayer@gmail.com) using a subject in the format "Issue #1234" (where "#1234" should be replaced with this issue number.) Please also update this issue to indicate you’ve done this.

Hi @icbaker, I just sent the mail. Thanks for your answer.

**Comment by icbaker** [comment]
I can reproduce that playback doesn't succeed.

I see this in logcat in the demo app:
```
tracks [eventTime=2.23, mediaPos=42.03, window=0, period=0
  MediaCodecVideoRenderer [
    Group:0, adaptive_supported=YES [
      [ ] Track:0, id=1621577614203item-01item, mimeType=video/avc, bitrate=300000, codecs=avc1.640029, drm=[playready,widevine], res=366x206, fps=29.97003, supported=NO_UNSUPPORTED_DRM
      [ ] Track:1, id=1621577614203item-02item, mimeType=video/avc, bitrate=900000, codecs=avc1.640029, drm=[playready,widevine], res=544x306, fps=29.97003, supported=NO_UNSUPPORTED_DRM
      [ ] Track:2, id=1621577614203item-03item, mimeType=video/avc, bitrate=1200000, codecs=avc1.640029, drm=[playready,widevine], res=686x386, fps=29.97003, supported=NO_UNSUPPORTED_DRM
      [ ] Track:3, id=1621577614203item-04item, mimeType=video/avc, bitrate=1800000, codecs=avc1.640029, drm=[playready,widevine], res=832x468, fps=29.97003, supported=NO_UNSUPPORTED_DRM
      [ ] Track:4, id=1621577614203item-05item, mimeType=video/avc, bitrate=2500000, codecs=avc1.640029, drm=[playready,widevine], res=1280x720, fps=29.97003, supported=NO_UNSUPPORTED_DRM
      [ ] Track:5, id=1621577614203item-06item, mimeType=video/avc, bitrate=3500000, codecs=avc1.640029, drm=[playready,widevine], res=1920x1080, fps=29.97003, supported=NO_UNSUPPORTED_DRM
    ]
  ]
  MediaCodecAudioRenderer [
    Group:0, adaptive_supported=N/A [
      [ ] Track:0, id=1621577614203item-07item, mimeType=audio/mp4a-latm, bitrate=96000, codecs=mp4a.40.2, drm=[playready,widevine], sample_rate=48000, language=es, supported=NO_UNSUPPORTED_DRM
    ]
  ]
  TextRenderer []
  MetadataRenderer []
  CameraMotionRenderer []
]
```

Note the `drm=[playready,widevine]` lines, which should also include `cenc` if ExoPlayer was able to parse the `<ContentProtection schemeIdUri="urn:mpeg:dash:mp4protection:2011" value="cenc"></ContentProtection>` node from your MPD file. This is the info needed for clearkey encryption.

The reason ExoPlayer is unable to parse this is because it's missing a `default_KID` attribute as required by the [DASH-IF guidelines](https://dashif-documents.azurewebsites.net/Guidelines-Security/master/Guidelines-Security.html#CPS-mpd-scheme):
> The cenc:default_KID attribute SHALL be present and have a value matching the default_KID in the tenc box.
