### ISSUE TITLE
Does it support Lollipop+ devices?

### ISSUE THREAD

**Issue by aareeph** [google/ExoPlayer#917]
Hi

We are experiencing problem with the MediaPlayer in Lollipop+ devices. Does this player works well with Lollipop+ devices? We need to play 3 sounds at a time (Playback + Background + Humming sound). This is the actual issue that our customers have started experiencing after upgrading to Lollipop and Marshmallow versions.

https://code.google.com/p/android/issues/detail?id=94069&thanks=94069&ts=1420659450

Thanks!

**Comment by ojw28** [comment]
ExoPlayer is designed for API levels 16+, so yes, it should work on Lollipop devices. See the (developer guide)[https://google.github.io/ExoPlayer/guide.html] for more information.
