### ISSUE TITLE
Error inflating class com.google.android.exoplayer2.ui.PlayerView

### ISSUE THREAD

**Issue by mwshubham** [google/ExoPlayer#9170]
Closing because this does not appear to be an ExoPlayer problem.

_Originally posted by @ojw28 in https://github.com/google/ExoPlayer/issues/6132#issuecomment-509342265_

This seems to be a major issue in our application. Can we do something for the same? Any tips on the android issue tracker for the same?

**Comment by marcbaechinger** [comment]
If you are having a similar issue, that some drawables are not found, then I suspect that we would give you a similar answer here again I'm afraid. Like that this is rather an application issue than an ExoPlayer issue. I'm quite sure that the drawables used by our UI components can be found. If this wasn't the case we'd probably had people complain here quickly after releasing (or when the given change landed in dev-v2).

If you are convinced that you are seeing an ExoPlayer library issue, please go ahead and describe the problem in more detail. I don't think that the issue from July 2019 does describe your problem accurately. Our [issue template](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md) gives you an idea what makes an issue actionable for us.

> Any tips [...] ?

Repeating from the other issue:

> I'd suggest to rebuild your app and maybe also to invalidate Android Studio caches. That often helps for such problems.

If the above does not help, try narrow down the problem. UI components of ExoPlayer are customizable. If you have applied some customization and then see some problems with resources not being found, I would recommend to start with an unmodified component. Then add your customization  step by step until it fails. This helps you to narrow down the problem to a given change.
