### ISSUE TITLE
How much data is used when streaming music ?

### ISSUE THREAD

**Issue by marinica94** [google/ExoPlayer#918]
Hi, I am streaming music from a cloud using `MediaPlayer`, untill now, playing a song of 3.4 MB will consume 3.4 MB on phone using Data.

Switching to exoplayer will help my app to use less data ? Thank you

**Comment by andreimarinescu** [comment]
Well, downloading a 3.4MB file will always consume at least 3.4MB of data. You might want to look at transcoding the files to an adaptive stream format such as DASH or HLS, this could give you more control over how much bandwith each client is consuming.
