### ISSUE TITLE
RTSP headers

### ISSUE THREAD

**Issue by a-blekot** [google/ExoPlayer#9182]
Hi everyone)

I'm not sure if it should be fixed but with some of our IP cameras, we had a problem with Authorization, because of lowerCase headers.

```
final class RtspHeaders {
   public static final String ACCEPT = "accept";
   public static final String ALLOW = "allow";
   ...
```

I have reverted changes to normal case (Accept, ...) and now it works correctly.
Also, I have changed this code in RtspHeaders:

```
public Builder add(String headerName, String headerValue) {
      // namesAndValuesBuilder.put(Ascii.toLowerCase(headerName.trim()), headerValue.trim());
      namesAndValuesBuilder.put(headerName.trim(), headerValue.trim());
      return this;
    }

public ImmutableList<String> values(String headerName) {
    //return namesAndValues.get(Ascii.toLowerCase(headerName));
    return namesAndValues.get(headerName);
  }
```
If it makes sense you can add these changes to repo))

**Comment by claincly** [comment]
It could be the specifics of your IP camera, could you elaborate?

As an aside, the header names are handled case insensitively, as mandated by RFC2068 (section 4.2):

> Field names are case-insensitive.

**Comment by a-blekot** [comment]
Hm... ok. I will ask our support team what is the difference between our cameras.
Thank you for the reference!
