### ISSUE TITLE
ExoPlayer toLowerInvariant("") not found 

### ISSUE THREAD

**Issue by sandipnawle** [google/ExoPlayer#9187]
Cannot find Util.toLowerInvariant(schemeId) method in Exoplayer after library updated to 2.14.1

**Comment by icbaker** [comment]
It was removed in https://github.com/google/ExoPlayer/commit/c50084e7baefc92f6222e1624fb716d20d37b160 and generally replaced with calls to Guava's [`Ascii.toLowerCase`](https://guava.dev/releases/snapshot-jre/api/docs/com/google/common/base/Ascii.html#toLowerCase(java.lang.String)) - see the linked commit message for more details.

**Comment by sandipnawle** [comment]
Thank you so much @icbaker
