### ISSUE TITLE
Aspect ratio not properly set at playback start after latest changes to dev-v2

### ISSUE THREAD

**Issue by fgl27** [google/ExoPlayer#9189]
I was using dev-v2 branch and found this

During the buffer stage the player doesn't have the proper aspect ratio, is just a square but the content and view are 16 by 9.

After `Player.STATE_READY` the size is OK.

I initiate the view layout like this.

```
            <com.google.android.exoplayer2.ui.PlayerView
                android:id="@+id/player_view"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:focusableInTouchMode="false"
                app:show_buffering="always"
                app:use_artwork="false"
                app:use_controller="false" />
```
Then dinamicly change the view layout to be smaller always keeping the 16 by 9 aspect ratio, that is why I can see it changing from a square to a rectangle, as the view is smaller then the device screen and is above a lighter background.

I notice this issue after this change https://github.com/google/ExoPlayer/commit/3c97815d55529cbd1f98581fa1a5677af16ceb9e reverting it will solve.

I made this for testing
https://github.com/fgl27/ExoPlayer/commit/39b2ea662a2e5b5685cec032f0be2c6a2cc624dc

the result is this

```
updateAspectRatio: setPlayer
updateAspectRatio: width 0 height 0
updateAspectRatio: onVideoSizeChanged
updateAspectRatio: width 1920 height 1080
```

As we can see `setPlayer` is called before `onVideoSizeChanged` and the sizes are 0 causing the issue, once `onVideoSizeChanged` is called the sizes are OK.

**Comment by Samrobbo** [comment]
Hey @klhyun, given you authored this change,. are you okay to have a look into this?

**Comment by klhyun** [comment]
Thanks for reporting this. I uploaded the fix. It'll be merged into dev-v2 branch soon.
