### ISSUE TITLE
What is causing `duplicate class com.google.android.exoplayer2` when using a library that uses ExoPlayer?

### ISSUE THREAD

**Issue by JMApps** [google/ExoPlayer#9192]
To work with audio in my flutter application, I use the [assets_audio_player](https://pub.dev/packages/assets_audio_player) library. Everything works great on the iOS platform, but as soon as I tried to release the release version on android, I ran into the problem:

**Duplicate class com.google.android.exoplayer2.ui.package-info found in modules jetified-exoplayer-common-2.14.1-runtime (com.google.android.exoplayer: exoplayer-common: 2.14.1) and jetified-exoplayer -ui-2.13.2-runtime (com.google.android.exoplayer: exoplayer-ui: 2.13.2)**

I tried to specify dependencies directly, then the error disappears, but the player in the android app doesn't work.

**Comment by Samrobbo** [comment]
It looks like the assets_audio_player is specifying 2.13.2 in their build.gradle. Given you are using their library (which makes use of ExoPlayer with other things on top), I would report the issue to them.

The link you shared has a GitHub project associated with it, where you can dig into their code if needed.

**Comment by JMApps** [comment]
@Samrobbo Yes, I probably should have done so, and not take your time. Thank you!

**Comment by icbaker** [comment]
One thing to note about the error message: It looks like you're (transitively?) depending on two different versions of ExoPlayer - the `exoplayer-ui` module at 2.14.2 and the `exoplayer-common` module at 2.13.2. This isn't supported. You have to use the same version of all parts of ExoPlayer.

It looks like assets_audio_player is depending on 2.13.2:
https://github.com/florent37/Flutter-AssetsAudioPlayer/blob/6467b5f969b07acf369a5ccfa7523d5e3853fa3c/android/build.gradle#L61

Are you depending on `exoplayer-ui:2.14.1` from somewhere else in your application's build process? If you change that to 2.13.2 it might resolve the problem.

----

Boring details:

The `package-info.java` file the error is complaining moved from the [`exoplayer-ui` module in 2.13.2](https://github.com/google/ExoPlayer/blob/r2.13.2/library/ui/src/main/java/com/google/android/exoplayer2/ui/package-info.java) to the [`exoplayer-common` module in 2.14.1](https://github.com/google/ExoPlayer/blob/r2.14.1/library/common/src/main/java/com/google/android/exoplayer2/ui/package-info.java). By depending on the two different versions you're ending up with two versions of the file.
