### ISSUE TITLE
Predicate not found in ExoPlayer

### ISSUE THREAD

**Issue by sandipnawle** [google/ExoPlayer#9194]
com.google.android.exoplayer2.util.Predicate not found when exoplayer updated to latest version

**Comment by marcbaechinger** [comment]
I think this has been removed when we added the Guava library (2.12.0). 

If you've used this in your own code, then you can use `com.google.common.base.Predicate` from Guava instead.

**Comment by sandipnawle** [comment]
@marcbaechinger evaluate(String) function is not found in that

**Comment by icbaker** [comment]
> @marcbaechinger evaluate(String) function is not found in that

In the Guava `Predicate<T>` the method is called `apply(T)` rather than `evaluate(T)`

https://guava.dev/releases/snapshot-jre/api/docs/com/google/common/base/Predicate.html#apply(T)
