### ISSUE TITLE
Encrypt Existing Downloaded Video m3u8 Chunks on Local Storage 

### ISSUE THREAD

**Issue by atulclassplus** [google/ExoPlayer#9195]
I am using Exo player CypherDataSource to encrypt HLS videos and storing the encrypted videos on local storage of android device.

Problem Statement: 
I want to encrypt existing videos which are already been downloaded using DownloadManager. How can I do that?

**Comment by ojw28** [comment]
`AesFlushingCipher` provides methods for encrypting data in the same way as when using `AesCipherDataSink` and `AesCipherDataSource. You can look at the source code for `AesCipherDataSink` to see how the content is encrypted using this class prior to being written to disk.

If you want to encrypt some clear files, you'll need to read them (using `FileDataSource` or just the standard Android APIs for reading files), encrypt the read data using `AesFlushingCipher` (in the same way that `AesCipherDataSink` does), and then overwrite the file with the encrypted data. You'll need to do this for each of the files.

If the idea is to clean up legacy downloads that weren't encrypted as a one off upgrade, then you may want to consider just deleting them and having the app (or the user) re-download them now that you have encryption enabled.
