### ISSUE TITLE
How to cancel the ongoing prepare()

### ISSUE THREAD

**Issue by halizton** [google/ExoPlayer#9197]
Context:

We are an app which can play multiple videos in a feed flow. We try to reuse exoplayer instances in our application since the exoplayer itself and underlying decoder is expensive to warm up. We usually call stop on an exoplayer once we are done with using it and put it back to a player pool for further usage.

Usually as the user scroll through our feed, if there is view in the feed needs to play a video, we will obtain a player from the cached player pool. Set media item to it, prepare() and then play(). Once the video view is scrolled out of the view port, we will call stop() on that player and put the player back to the player pool. (very typical caching strategy)

There is a problem that we have encountered. Once the user scrolls through the feed quickly, we will have a case where we just call prepare() on a player to play **video A** but we have to call stop() on it and put it back to the pool. Because the view just appears in the view port and then move off of the view port due to the fast scroll speed. In this case, if the user quickly moves and stops at a position, that stopped player is obtained to prepare/play another **video B**. But instead **video A** is played.

player 1: setMediaItem(video A)
player 1: prepare()
player 1: stop()
player 1: isLoading() returns true ==> means the prepare() is still in process
player 1: being put into the cached pool

player 1: picked up from the cached pool
player 1: setMediaItem(video B)
player 1: prepare()
player 1: play()
====== video A is played by player 1 instead of video B.

I have tried to use **clearMediaItems()** before sending the video to the cached pool, there is no success. The video miss play still happens.

Question:
My question is if the prepare() can be cancelled. I read through the exoplayer code and it seems the clearMediaItems() would call all the way to release the media source. But it certainly does not solve the problem. I wonder if there is public API can achieve what I want or this is a new feature request. Or should I wait for the prepare() to be finished and then call clearMediaItems() instead, but then that won't stop the internal media downloading then.

-> MediaPeriodQueue.clear()
-> MediaPeriodHolder.releaseMediaPeriod()
-> MediaSourceList.releasePeriod()

My goal is try to keep the exoplayer instances and its decoders around instead of releasing them.

**Comment by marcbaechinger** [comment]
stop() is clearing the media period queue. prepare as a such is delegated to the media sources and can't be cancelled in that sense. 

The ongoing prepare is ongoing only regarding loading of the media source I would say. And even if you would be able to stop the loading I wouldn't understand how it would change something regarding the problem you see, because at least after `setMediaItem(video B)' the old media source should not be in charge of delivering data for rendering anymore.

I wonder whether there is some data sent to the renderer/media codec already which then is rendered to the surface. Are you reusing the same `PlayerView`/`Surface` or are these different instances? It would be interesting to know when in the log files you see that the player goes to STATE_IDLE after stop() related to the calls to setMediaItem and when setting the player to the view for instance.

One thing I would try if you are sure you will replace the media items after stop is calling clearMediaItems() right after stop. 

In general such quick prepare() calls  is a tricky problem and even more because calls to the player first need be passed to the playback thread (and back).

The burden to solve this problem is very much on the player side right now. Another approach you could try to ease this a bit and stop preparing the player when the scrolling is really fast. When the recyclerview is scrolling very fast you can probably stop preparing until it gets some slower. The user won't see any video frame after a certain scroll speed.

**Comment by halizton** [comment]
> I wonder whether there is some data sent to the renderer/media codec already which then is rendered to the surface.

I think this is the case. Also since our videos are short (less than a minute), it appears the entire video A (old)is already in the renderer/media.

> Are you reusing the same **PlayerView/Surface** or are these different instances? 

I also reuse the **PlayerView/Surface** but they are managed (reused) by the recycler view directly. The cached exoplayer pool is independent from the **PlayerView/Surface**. I set a player to the PlayerView/Surface when it comes into the view port.

> It would be interesting to know when in the log files you see that the player goes to STATE_IDLE after stop() related to the calls to setMediaItem and when setting the player to the view for instance.

Here are the two examples that I collected, from the log, I do call **stop** on the player first while the player can be in READY or BUFFERING state. The **stop** does turn the player's state back to IDLE. But I found in some cases the player is still not reusable as long as the **player.isLoading** still return true. This does not change even if I call **clearMediaItems** right after calling the **stop**, **player.isLoading** still returns true.

I found as long as the **player.isLoading** still returns true after calling **stop** and **clearMediaItems** on it, the problem remains there and I cannot reuse that player instance. So I am guessing the **player.isLoading** might imply the underlying loading is still going on although the player can be in state IDLE, any insights?

```
PlayerCache: stop player [198970871], player state [READY] isLoading [true]
PlayerCache: called clearMediaItems() on player [198970871]
PlayerCache: release player [198970871], player state [IDLE] isLoading [true], cannot reuse

PlayerCache: stop player [169738086], player state [BUFFERING] isLoading [true]
PlayerCache: called clearMediaItems() on player [169738086]
PlayerCache: release player [169738086], player state [IDLE] isLoading [true], cannot reuse
```

> When the recyclerview is scrolling very fast you can probably stop preparing until it gets some slower. The user won't see any video frame after a certain scroll speed.

This is a good suggestion and I am considering to give it a shot.

**Comment by ojw28** [comment]
> player 1: setMediaItem(video A)
> player 1: prepare()
> player 1: stop()
> player 1: isLoading() returns true ==> means the prepare() is still in process
> player 1: being put into the cached pool

> player 1: picked up from the cached pool
> player 1: setMediaItem(video B)
> player 1: prepare()
> player 1: play()
> ====== video A is played by player 1 instead of video B.

If you're seeing the entirety of video A play in this case, then that just sounds broken. Without additional information, I think it's more likely to be a bug in your application code (e.g., the call sequence being made on the player is not what you think it is). I'd suggest you try and reproduce the problem with a simple example that makes the call sequence above directly, without complicated logic around pooling/caching. If you can reproduce the issue in a simple example, please provide clear reproduction steps and we can take a look. If you can't, I'd suggest you take a closer look for issues in your application code to double check that what you think is happening really is happening.

> I think this is the case. Also since our videos are short (less than a minute), it appears the entire video A (old)is already in the renderer/media.

It's not possible for the entire video to be held this far down the media pipeline, and even if it were, the pipeline should be cleared when the new item is set.
