### ISSUE TITLE
Merging audio and video together

### ISSUE THREAD

**Issue by krishna-apk** [google/ExoPlayer#9199]
In a previous version of exoplayer a developer can merge audio and video with the help of MergingMediaSource but in the new version, there is no manual way to do it because it only considers merging substiles (.setsubstitles) but no audio.

If there is any way to merge audio and video and play together.

**Comment by Samrobbo** [comment]
Hi, From what I understand, `MergingMediaSource` hasn't had any large functionality changes in a while.

If possible, can you give:

- The ExoPlayer version where this feature worked.
- A code snippet showing what you did
- The ExoPlayer version you are using now
- A code snippet showing what you are currently trying, although as you've said it isn't working in the current state.

Thanks!

**Comment by Samrobbo** [comment]
Just to add some additional info that might be useful: 

You can still create `MediaSource` instances directly, and this is recommended for use-cases that aren't supported the `MediaItem`, such as using `MergingMediaSource` to merge audio and video from different streams.

Given that loading subtitles is more common, we have support for it directly in `MediaItem`, but from what we've seen, playing audio from one file and video from another isn't as common of a use-case, so it can't be done with `MediaItem` directly.

It's worth noting that even though `MediaItem` is recommended, `MediaSource` is not deprecated and is still supported.

See https://exoplayer.dev/media-sources.html#media-source-based-playlist-api for some snippets and other examples.
