### ISSUE TITLE
Can't compile AV1

### ISSUE THREAD

**Issue by master255** [google/ExoPlayer#9200]
Try https://github.com/google/ExoPlayer/tree/release-v2/extensions/av1#build-instructions-windows
It's not working.

**Comment by master255** [comment]
add OPTION(BUILD_TESTING "Build tests" OFF) to CMakeLists.txt

**Comment by ojw28** [comment]
@AquilesCanta - Could you take a look (reassign to @andrewlewis if needed). Thanks!

**Comment by AquilesCanta** [comment]
I've just followed the build instructions on linux, exoplayer version 2.14.2, and it works well. If you provide more info about your error, we may be able to assist you. Can you explain which step is failing and what error message you are running into?

**Comment by master255** [comment]
@AquilesCanta try to think for yourself? You have a problem and a solution to that problem. Think about it and tell me what the problem was and what needs to be done?

**Comment by AquilesCanta** [comment]
I don't currently have a reason to think there is a problem. Please provide more info about the problem below and I will reopen the issue. I will not modify the source code unless it is clear what we are getting out of it.

**Comment by master255** [comment]
@AquilesCanta try creating a clean Ubuntu virtual machine and follow your instructions.
Do this on a regular basis.
