### ISSUE TITLE
RTSP - header method

### ISSUE THREAD

**Issue by bianchina3** [google/ExoPlayer#9201]
Please, use the standard keyword in header method:
CSeq, Transport, Session, .......

Greetings

**Comment by marcbaechinger** [comment]
Thanks for reporting! Can you give us a bit more details what you observed and what the expectations are?

**Comment by bianchina3** [comment]
Hi.
My camera is not responding due to non-compliant keyword headers.
I changing the code for replace keyword headers in accordance of  RFC 7826 (section 18) and now the IP camera work well.
I believe the issue #9182 is similar to mine.

**Comment by claincly** [comment]
RTSP header syntax is case insensitive. Your camera is not fully compliant in this case. Glad that you fixed it by changing some string constants.

**Comment by bianchina3** [comment]
Hi.
The RFC7826 don't talk about case insensitive in headers. the keywords should be equal as in section 18

**Comment by claincly** [comment]
Yes it does, in section 20:

The RTSP syntax is described in an Augmented Backus-Naur Form (ABNF)as defined in RFC 5234.  It uses the basic definitions present in RFC 5234 <https://datatracker.ietf.org/doc/html/rfc5234>. Please note that ABNF strings, e.g., "Accept", are case insensitive as specified in Section 2.3 of RFC 5234. The RTSP syntax makes use of the ISO 10646 character set in UTF-8 encoding.

**Comment by bianchina3** [comment]
you're right. But there are many cameras that are not responding, but if you change the strings you cover all the cameras and you are not out of the RFC standard.

**Comment by claincly** [comment]
Fixing for one camera may break for another. In our testing we found there
are discrepancies in what cameras support. For example, for
Content-Encoding header, a camera could support either

- Content-encoding
- Content-Encocing
- content-encoding

We've seen RTSP servers do all three, so it's hard for us to make a
decision which one to use. But we will keep an eye on this.

**Comment by claincly** [comment]
It's fixed in the new release. 

https://github.com/google/ExoPlayer/commit/13ff72d86934070867dce1b1be2b7ab5f91f0bb7
