### ISSUE TITLE
com.google.android.exoplayer2.ExoPlaybackException: Source error | 403

### ISSUE THREAD

**Issue by irfanirawansukirman** [google/ExoPlayer#9209]
I'm trying to run a video with the following URL: http://cdn-vt.corporateedu.xyz/videos/files/20210510/transcode/1620620085_test-video-mp4-ilyas_480p.mp4?md5=P3OvD06gnIzFa6FbdBNJIw&expires=1626847945 Tried getting 403 error sometimes. upgraded the exoplayer version but it still happens.

exoplayer version: 2.13.3
android: 11
device: samsung A50

**Comment by claincly** [comment]
I get a 403 accessing that link directly with Chrome. Maybe the server's permission is doing something?

**Comment by irfanirawansukirman** [comment]
> I get a 403 accessing that link directly with Chrome. Maybe the server's permission is doing something?

If i access the video using wifi rarely get errors. But when using mobile data, there are often problems with source errors or forbidden 403

**Comment by marcbaechinger** [comment]
The player can connect to the server and is receiving an HTTP/403 which is reported accordingly. 

There is not much more the player can do. I think you need to get access granted for that resource from any network if this should reliably work. You need to figure out with the owner of the server how you can authenticate.
