### ISSUE TITLE
Exoplayer declared permissions

### ISSUE THREAD

**Issue by diabloo** [google/ExoPlayer#921]
Hi,
first ,thank you for this library  , i was  wondering if i can remove the wirte permission in exoplyer ,because i use it only for online audio streaming

**Comment by ojw28** [comment]
You can remove both READ_EXTERNAL_STORAGE and WRITE_EXTERNAL_STORAGE if you're only doing streaming over the network.

When we first added these permissions to the manifest I don't think manifest merging existed, so the permissions were there for informational purposes only. Now manifest merging does exist I guess these permissions do get merged into your application when you pull in the ExoPlayer library.

Is that correct? Do you think it would make more sense to comment these permissions out by default in the library manifest?

**Comment by diabloo** [comment]
thank you for the response . yes I think it would be better to let the devlepper add permission in the manifaist . for my case it easier and faster  to use the Jcenter dependency witout downloading and linking the library . thank you for your time and for this library

**Comment by ojw28** [comment]
This is fixed in the dev branch.
