### ISSUE TITLE
 Packet Capture trac user agent

### ISSUE THREAD

**Issue by samirtvdev** [google/ExoPlayer#9213]
Hi,

App " Packet Capture" trac my app  (url and user agent )
I use IPTV panel 
I try with different ExoPlayer version.
Is there a solution to protect this data (url and user agent )?

[https://drive.google.com/file/d/16GE_SFkZn4I6kFXax0eehSxT9U_tVcv8/view](url)

**Comment by ojw28** [comment]
The solution is to request data over HTTPS rather than HTTP. See https://www.cloudflare.com/en-gb/learning/ssl/why-is-http-not-secure/. If the server only supports HTTP, then there is fundamentally no way to protect this data.

**Comment by samirtvdev** [comment]
Thanks for your assistance
