### ISSUE TITLE
Ndk r21e Linux-x86_64 cannot build ffmpeg with provided build script

### ISSUE THREAD

**Issue by SharifRafid** [google/ExoPlayer#9215]
Hi, 

I am using Ubuntu Linux 64bit Version to build the Exo Player FFMPEG extension. 

I followed the whole readme quite a lot of times and tried online fixes but none is actually helping to get the build successful.

After giving this command 
`cd "${FFMPEG_EXT_PATH}/jni" && \
./build_ffmpeg.sh \
  "${FFMPEG_EXT_PATH}" "${NDK_PATH}" "${HOST_PLATFORM}" "${ENABLED_DECODERS[@]}"
`
I'm getting an output like below,

```
Using 4 jobs for make
/media/sharifrafid/Android Files Basically/Exo Player/android-ndk-r21e-linux-x86_64/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi16-clang is unable to create an executable file.
C compiler test failed.

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.
Makefile:163: /tests/Makefile: No such file or directory
make: *** No rule to make target '/tests/Makefile'.  Stop.
Makefile:163: /tests/Makefile: No such file or directory
make: *** No rule to make target '/tests/Makefile'.  Stop.
Makefile:163: /tests/Makefile: No such file or directory
make: *** No rule to make target '/tests/Makefile'.  Stop.
/media/sharifrafid/Android Files Basically/Exo Player/android-ndk-r21e-linux-x86_64/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang is unable to create an executable file.
C compiler test failed.

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.
Makefile:163: /tests/Makefile: No such file or directory
make: *** No rule to make target '/tests/Makefile'.  Stop.
Makefile:163: /tests/Makefile: No such file or directory
make: *** No rule to make target '/tests/Makefile'.  Stop.
Makefile:163: /tests/Makefile: No such file or directory
make: *** No rule to make target '/tests/Makefile'.  Stop.
/media/sharifrafid/Android Files Basically/Exo Player/android-ndk-r21e-linux-x86_64/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/i686-linux-android16-clang is unable to create an executable file.
C compiler test failed.

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.
Makefile:163: /tests/Makefile: No such file or directory
make: *** No rule to make target '/tests/Makefile'.  Stop.
Makefile:163: /tests/Makefile: No such file or directory
make: *** No rule to make target '/tests/Makefile'.  Stop.
Makefile:163: /tests/Makefile: No such file or directory
make: *** No rule to make target '/tests/Makefile'.  Stop.
/media/sharifrafid/Android Files Basically/Exo Player/android-ndk-r21e-linux-x86_64/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android21-clang is unable to create an executable file.
C compiler test failed.

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.
Makefile:163: /tests/Makefile: No such file or directory
make: *** No rule to make target '/tests/Makefile'.  Stop.
Makefile:163: /tests/Makefile: No such file or directory
make: *** No rule to make target '/tests/Makefile'.  Stop.
Makefile:163: /tests/Makefile: No such file or directory

```
This is my `ffbuild/config.log` file
[config.log](https://github.com/google/ExoPlayer/files/6860466/config.log)

Please help me out, I really am not finding anything on the web about solving this issue and I'm actually a beginner at ffmpeg and audio decoders. 

TIA

**Comment by master255** [comment]
@SharifRafid Wrong encoding of the file?

**Comment by AquilesCanta** [comment]
I've just built ffmpeg with no issues using ndk 20. I'm pretty sure that this is an issue with your local setup. For starters, ndk is looking for a file in `/tests/Makefile`, which doesn't look right and should instead be `{ffmpeg's location}/tests/Makefile`.

If I have to guess, I'd say NDK_PATH has an issue. In your case it's probably set to "/media/sharifrafid/Android Files Basically/Exo Player/android-ndk-r21e-linux-x86_64/android-ndk-r21e", but I think the script is failing to find armv7a-linux-androideabi16-clang. The reason I think your NDK_PATH is incorrectly set is that if I unset NDK_PATH locally, I guess the same error code you are getting. I strongly doubt it, but I wonder if the spaces in the path are problematic. Honestly I doubt that's the case, but it's worth taking a look. First step is making sure "/media/sharifrafid/Android Files Basically/Exo Player/android-ndk-r21e-linux-x86_64/android-ndk-r21e" actually points to the expected file.

Please provide the value of all the involved environment variables: "${FFMPEG_EXT_PATH}/jni" && ./build_ffmpeg.sh "${FFMPEG_EXT_PATH}" "${NDK_PATH}" "${HOST_PLATFORM}" and please make sure all of those values are pointing to the expected paths.

**Comment by SharifRafid** [comment]
@AquilesCanta I literally don't know how to thank you bro, the issue was with the spaces in my path, I just made the whole path space proof and it worked like a charm. There are such huge communities and after searching for 2 days I didn't find this simple issue. No one told me that your path should not contain spaces lol. 
Thanks A Lot Man. Saved my life.
