### ISSUE TITLE
Skip Silence at end of tracks?

### ISSUE THREAD

**Issue by cncb-gh** [google/ExoPlayer#9218]
Is SkipSilence supposed to work at the end of audio tracks or just in the middle?  It doesn't seem to be working at the ends.  Is there something that has to be set other than SkipSilenceEnabled?  Thanks.

**Comment by marcbaechinger** [comment]
I think setting the flag should be sufficient in case you are using the `DefaultAudioSink` that is used by default.

That should work on analzying the audio data that are produced by the audio media, so I'd expect in the middle as well as at the end. 

When using the `EventLogger`, do you see a line printed to he log similar like the one below? (or do you see a call to `AnalyticsListener.onSkipSilenceEnabledChanged` in case you are using a custom listener?)

```
com.google.android.exoplayer2.demo D/EventLogger: skipSilenceEnabled [eventTime=0.00, mediaPos=0.00, window=0, true]
```

If you see that log entry, all you need to do seems fine. In this case, can you post the media here or send us by email to dev.exoplayer@gmail.com?

**Comment by cncb-gh** [comment]
Thanks, turns out it was a stupid mistake on my part.  Sorry to waste your time.
