### ISSUE TITLE
Short jamming in hls (h264 and h265)

### ISSUE THREAD

**Issue by darius1706** [google/ExoPlayer#922]
Hello,
I am using MediaPlayer for playing live HLS streams. It works well but I want to switch to ExoPlayer, because it looks very good.
But If I use your demo I have problems, that stream has very short jamming. The same streams on the same device are ok.
I dont know what I should change or check, where could be a problem. I have tried to make chunks longer, but jamming is in the chunk also, not between two chunks.
Thank you
D

**Comment by pajatopmr** [comment]
Which stream would that be?  And can you elaborate on what you mean by "jamming"?

**Comment by darius1706** [comment]
Hello, Its HLS stream and jamming is situation that pictures are frozen for a short time - milliseconds.

**Comment by darius1706** [comment]
http://qthttp.apple.com.edgesuite.net/1010qwoeiuryfg/sl.m3u8 - this video is very freezing, but only in ExoPlayer, with MediaPlayer on the same device is playing well.

**Comment by ojw28** [comment]
I don't observe any issues playing that stream. Please try with a more recent version of ExoPlayer (1.5.8+) and file a new issue containing more detailed information if you're still observing the problem.
