### ISSUE TITLE
A problem with drm protected contents.

### ISSUE THREAD

**Issue by HyowonHwang** [google/ExoPlayer#9220]
### Enviroment
- ExoPlayer version number'
2.14.1
- Android version
Android 11
- Android device
SM-N970

### Problem
I have a  problem with some content of widevine and  checked that  it was played well  on chrome browser.
Only Android  devices have problem and tried to figure out what problem is. But I couldn't make it.

I have attached  full logs. 
[wv_failed_error.txt](https://github.com/google/ExoPlayer/files/6866788/wv_failed_error.txt)

And I am sending you media files by e-mail.  could you help me out, please?

**Comment by marcbaechinger** [comment]
That`s probably an issue with the implementation on that device.

@rrfrias may I kindly ask you to have a look?
@HyowonHwang I checked the inbox but I haven't found an email with subject "Issue 9220" or similar.

**Comment by HyowonHwang** [comment]
@marcbaechinger  Sorry for sending late. I've just sent  it.

I understand that this could be a problem of device. But almost android devices(SM-9xx, LM-V500) have problem this.
Some device(Nexus5_5.0) play while too many frame drops.

If there is a point of modifying my content, I really want to know about it and will try to fix it.

**Comment by rrfrias** [comment]
From wv_failed_error.txt it appears that the content is encoded with more subsamples than the device can handle. In android 10 onwards, the maximum number of subsamples that a device can handle can be queried by the app. There is no way to tell for the devices you have listed. I assume it is 10 subsamples but it might be lower. 

Try to modify content encoding parameters and see if that helps.

```
2021-07-23 14:32:01.443 557-23699/? E/wv_dash: Subsample count is exceeded the maximum.
2021-07-23 14:32:01.443 557-23699/? E/wv_dash: process drm decrypt CENC failed [ffffffff]
2021-07-23 14:32:01.443 557-23699/? E/WVCdm: [crypto_session.cpp(1541):Decrypt] OEMCrypto_DecryptCENC failed: status = -1
2021-07-23 14:32:01.443 557-23699/? E/WVCdm: Decrypt error in session sid270 during a sample with protected data: 1
```

**Comment by HyowonHwang** [comment]
@rrfrias Alright, I am trying to fix this like what you said. Thanks.
