### ISSUE TITLE
Feature: MP4 Chapter support

### ISSUE THREAD

**Issue by elvinas-engagecraft** [google/ExoPlayer#9225]
Add support for MP4 Chapters (type `chap`).

This is not part of ISO/IEC 14496-12 standard but it is widely supported by various tools (e.g. Subler: https://bitbucket.org/galad87/subler/wiki/Subtitles%20Guide).
Also it is supported on `AVFoundation` on iOS.

### Proposed solution
Import MP4 chapters as Cues with images from `chap` tracks.

### Alternatives considered

---

Also #8271 is related to this. VLC is incorrectly showing Chapters' track as Tx3g track (fallbacking to `tx3g` on `text` boxes?).

ExoPlayer behavior is correct - this track should not be a subtitles track. It's only intended for Chapter list (Cues).

---

Attaching **MP4Box.js** screenshots:

1. Chapters configuration:
![image](https://user-images.githubusercontent.com/16777267/126962221-dea433e9-c98f-477e-b72c-3ececaacad4f.png)

2. Images track:
![image](https://user-images.githubusercontent.com/16777267/126962370-b6622a91-3432-4658-9234-be6a8f98aa73.png)

3. Titles track:
![image](https://user-images.githubusercontent.com/16777267/126962454-5780ad4b-20c0-4ac3-8eec-d089ed7a7920.png)

**Comment by kim-vde** [comment]
Hi,

Can you provide more information on this `chap` atom (e.g. link to specifications), and an example of content? If you're unable to share the test content publicly, please send it to dev.exoplayer@gmail.com using subject #9225. Please also update this issue to indicate you've done this.

We don't have the capacity to work on this at the moment but I have marked the issue as a low-priority enhancement to keep track of it.

**Comment by rohitjoins** [comment]
FYI: We have [added](https://github.com/androidx/media/commit/0fde8633a190f31b237f00d087ca922ca42b1912) MP4 Chapter support.
