### ISSUE TITLE
Exoplayer - java.lang.IllegalStateException: Player is accessed on the wrong thread

### ISSUE THREAD

**Issue by ibrajix** [google/ExoPlayer#9226]
After playing a media from my device, I get:

Exoplayer - java.lang.IllegalStateException: Player is accessed on the wrong thread
-------------------------

This happened after updating exoplayer from: **2.12.2** to  **2.14.2**

Current thread: 
'ExoPlayer:Playback'
'Expected thread: 'main'
-------------------------

AudioPlayer.kt:
-------------------------

```
class AudioPlayerImplementation(
internal val context: Application
) : AudioPlayer,
Player.Listener,
LoadEventController {

private var playerBase: ExoPlayer? = null
private val player: ExoPlayer
    get() {
        if (playerBase == null) {
            playerBase = createPlayer(this)
        }
        return playerBase ?: throw IllegalStateException("Could not create an 
audio player")
    }
  
   override fun play(startAtPosition: Long?) {
    startAtPosition ?: return player.play()
    player.seekTo(startAtPosition)
    //error thrown here
    player.play()
    }

   override fun seekTo(position: Long) {
    //error thrown here
    player.seekTo(position)
   }
 }

private fun createPlayer(owner: AudioPlayerImplementation): ExoPlayer {
    return SimpleExoPlayer.Builder(context)
        .setLoadControl(LoadController().apply {
            eventController = owner
        })
        .build().apply {
            val attr = AudioAttributes.Builder().apply {
                setContentType(C.CONTENT_TYPE_MUSIC)
                setUsage(C.USAGE_MEDIA)
            }.build()

            setAudioAttributes(attr, false)
            setPriorityTaskManager(PriorityTaskManager())
            addListener(owner)
        }
  } 
```

I read that you need to use a Handler so I changed  my **createPlayer** function:

 ```
override fun seekTo(position: Long) {
    val mainThreadHandler = Handler(Looper.getMainLooper())
    mainThreadHandler.post { player.seekTo(position) }
}
```

I cant write this code in every instance player...there are so many instances.

NB: I use Hilt. Best way to structure and build exoplayer instance?

**Comment by christosts** [comment]
As you may read on the player's [documentation](https://exoplayer.dev/hello-world.html#a-note-on-threading), you should access the player instance only from a single thread. As of version 2.13, the player throws an exception if it is accessed from a wrong thread. This check was present in 2.12.2 too, but produced a warning log. As the documentation says, there is an API to make the player not throw an exception, which is planned to be removed however, therefore the better fix is to make your app access player instances from the same thread always.

How to fix this is up to your application. From your description above, it looks like seekTo is called from another thread, and it's up to you how to invoke player methods from the same thread.

I am closing this issue - feel free to re-open if the answer above did not answer your question.
