### ISSUE TITLE
Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR)

### ISSUE THREAD

**Issue by IamArmaan** [google/ExoPlayer#9227]
When ExoPlayer video is playing , app is getting crash on few devices like one plus 6 (Android 10) and moto g 10 (Android 11) . Error is getting like this Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR) . Sent bug report on mail dev.exoplayer@gmail.com

**Comment by christosts** [comment]
Hi! Please provide complete information as requested in the issue template. The issue template can
be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md). If you're unable to share [bug reports](https://developer.android.com/studio/debug/bug-report) or test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #9227" ("#9227" is this issue's number). Please also update this issue to indicate you've done this.

**Comment by IamArmaan** [comment]
Please check mail , I have sent bug reports on mail.

**Comment by christosts** [comment]
@IamArmaan thank you for sending information, however it is incomplete. If you read the [issue template](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md) you'll see that we need a bug report captured with `adb bugreport` and a URL to test content for reproduction.

The logs that you have shared with us are not the output of running `adb bugreport` - please see [documentation](https://developer.android.com/studio/debug/bug-report) how to capture a bug report.

One note: in your email you mentioned you are using ExoPlayer 2.8.4. Have you tested your content on the ExoPlayer demo app with the latest ExoPlayer version, which is 2.14.2 at the moment?

PS Not all information needs to be sent over email, but only the things you don't want to share in public such as links to test content and bug reports. The rest (android version and/or devices where the issue occurs) can be put here.

**Comment by IamArmaan** [comment]
I have checked on latest version also 2.14.2 and getting similar issue on device like moto e(7) plus (Android version 10) ,Moto G 10 (Android 11) ,One Plus 6 (Android10) I have sent bug report on mail dev.exoplayer@gmail.com , Please check.

**Comment by christosts** [comment]
We have received one email about this issue but it does not contain a full bugreport (but only a copy of logcat logs) or a URL to the content. 

Please obtain a full bug report (running `adb bugreport` - see [here](https://developer.android.com/studio/debug/bug-report)) from the device after the crash occurs and send the bug report and  the content URL so that we can test the same content on the ExoPlayer demo app.

Thanks

**Comment by IamArmaan** [comment]
I have shared full bug report , if anything else you want please let me know. Thanks.

**Comment by IamArmaan** [comment]
Hi @christosts , have you checked this issue ? Please look into it.

**Comment by IamArmaan** [comment]
Hi @christosts , thanks for cooperate . I have resolved this issue to add `app:surface_type="texture_view"` in exoplayer layout file .
