### ISSUE TITLE
Do multiple players need to use multiple handlers?

### ISSUE THREAD

**Issue by dnutcracker** [google/ExoPlayer#923]
I'm using multiple instances of ExoPlayer simultaneously.

Does it make sense that each player will create a new Handler or create a single Handler to be shared between all the players?

**Comment by dnutcracker** [comment]
Well - eventually a handler is just what it is - a handler to the looper to which events will be posted - so I guess it doesn't really matter if multiple handlers are used or a single shared one as long as they all use the same looper.(usually the main looper)

**Comment by ojw28** [comment]
I assume you mean the Handler that you create to pass as the `eventHandler` to quite a few of the components? You would normally be creating those on the main application thread. It makes pretty zero difference whether you instantiate multiple instances, or only one.
