### ISSUE TITLE
Snapshot in StyledPlayerView

### ISSUE THREAD

**Issue by Wiktorl4z** [google/ExoPlayer#9234]
Question regarding making snapshot for ExoPlayer.
I am having same problem like in this topic: 
https://github.com/google/ExoPlayer/issues/2993

I have used both solutions from @ojw28 https://github.com/google/ExoPlayer/issues/2993#issuecomment-310911567
Created sample project to show the code.

Solution first:

> There is no requirement that you use SimpleExoPlayerView. You can use a TextureView directly if you prefer. You can use SimpleExoPlayer.setVideoTextureView to set a SimpleExoPlayer instance to output to a TextureView.

```
    <TextureView
        android:id="@+id/textureView"
        android:layout_width="0dp"
        android:layout_height="0dp"
        app:layout_constraintBottom_toTopOf="@+id/button"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent" />
```
```
private fun initializePlayer() {
        val player = SimpleExoPlayer.Builder(this).build()
        player.setMediaItem(MediaItem.fromUri(rtsp))
        player.prepare()
        player.setVideoTextureView(binding.textureView)
}
```

```
binding.button.setOnClickListener {
            // get the bitmap of the view
            val bitmap = getScreenShotFromView(binding.textureView)
            // if bitmap is not null then save it to gallery
            if (bitmap != null) {
                saveMediaToStorage(bitmap)
            }
}
```

Full code: https://github.com/Wiktorl4z/ExoPlayerSnapshot/blob/textureView/app/src/main/java/com/example/exoplayersnapshot/MainActivity.kt

Solution second:
> If you do want to use SimpleExoPlayerView, you can specify surface_type as @b0g8 notes above. You can retrieve the TextureView from the SimpleExoPlayerView using SimpleExoPlayerView. getVideoSurfaceView and then casting to TextureView.`

```
 <com.google.android.exoplayer2.ui.StyledPlayerView
        android:id="@+id/player_view"
        android:layout_width="0dp"
        android:layout_height="0dp"
        app:layout_constraintBottom_toTopOf="@+id/button"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        app:show_shuffle_button="true"
        app:show_subtitle_button="true"
        app:surface_type="texture_view" />
```

```
private fun initializePlayer() {
        val player = SimpleExoPlayer.Builder(this).build()
        player.setMediaItem(MediaItem.fromUri(rtsp))
        player.prepare()
        binding.playerView.player = player
}
```

```
binding.button.setOnClickListener {
            val textureView = binding.playerView.videoSurfaceView as TextureView
            // get the bitmap of the view
            val bitmap = getScreenShotFromView(textureView)
            // if bitmap is not null then save it to gallery
            if (bitmap != null) {
                saveMediaToStorage(bitmap)
   }
}
```
Full code:
https://github.com/Wiktorl4z/ExoPlayerSnapshot/blob/surface_type/app/src/main/java/com/example/exoplayersnapshot/MainActivity.kt

In both cases my bitmap is dark, is there anything what I have missed? 
I would appreciate for any feedback.

**Comment by christosts** [comment]
@ojw28 can you take a look?

**Comment by Wiktorl4z** [comment]
TextureView has already implemented getBitmap function.
I didn't noticed that. This is correct answer for solution first:
```
binding.button.setOnClickListener {
            val textureView = binding.playerView.videoSurfaceView as TextureView
            // if bitmap is not null then save it to gallery
            textureView.bitmap?.let {
                saveMediaToStorage(it)
            }
}
```
