### ISSUE TITLE
Can't play an mp4 file.

### ISSUE THREAD

**Issue by master255** [google/ExoPlayer#9242]
https://mega.nz/file/khNEGbAT#O1uKAMECAivkxxKuq_PQTszzXaQFRFHdin9rn3hRBtw

**Comment by christosts** [comment]
The video of this file is encoded as mpeg2. ExoPlayer uses the platform decoders for video and this video codec is not supported on Android, please see the [Supported sample formats](https://exoplayer.dev/supported-formats.html#sample-formats) on ExoPlayer documentation, which further links to [Android supported formats](https://developer.android.com/guide/topics/media/media-formats#core) page. The suggestion is to use formats that are supported by the Android platform, such as H264, VP9 or HEVC (new devices also support AV1)

When playing the video on the demo app, these logs are printed which show that the video encoding is unsupported

```
MediaCodecVideoRenderer [
        Group:0, adaptive_supported=N/A [
D/EventLogger:       [ ] Track:0, id=1, mimeType=video/mpeg2, res=720x576, fps=24.95276, supported=NO_UNSUPPORTED_TYPE
        ]
      ]
```
You may look for such logs on the device you are testing.

Note: the audio is encoded with AC-3, the audio would work only on devices with AC-3 support, likely TVs but probably not mobile phones.

**Comment by master255** [comment]
@christosts That's too bad. You've been developing the player for so many years, and it still doesn't play mp4. This is ridiculous!
