### ISSUE TITLE
get callback which provide current playing state?

### ISSUE THREAD

**Issue by Office-Murtaza** [google/ExoPlayer#9246]
we have custom seekbar. I am trying to find callback which provide current playing postion to update custom seekbar.

**Comment by andrewlewis** [comment]
There is no callback that's called when the player's position changes, but you can poll the player position periodically to update the UI, like [`StyledPlayerControlView`](https://github.com/google/ExoPlayer/blob/79f03df/library/ui/src/main/java/com/google/android/exoplayer2/ui/StyledPlayerControlView.java#L1436). See also #8680 and #3980.

For a callback when the playback state (idle, buffering, ready, ended) changes use [`onPlaybackStateChanged`](https://github.com/google/ExoPlayer/blob/80332f7f1be7f0ea59440b4888560d228f405789/library/common/src/main/java/com/google/android/exoplayer2/Player.java#L211).
