### ISSUE TITLE
Ads don't play on a specific (actual production) package name on Android, Android TV & Fire TV.

### ISSUE THREAD

**Issue by anas-incedo** [google/ExoPlayer#9249]
Hi,

I am getting the below error whenever I try to play ads on my Android, Android TV, and Amazon Fire TV app with a particular package name which is `tv.horseandcountry`. If I change the package name to anything other than the actual production package name, the ads play as expected. I can't change the package name because there are apps already Live on the respective app stores.

The result is the same on my app and on the [latest exoplayer](https://github.com/google/ExoPlayer) demo, which I tested by changing the package name in the `AndroidManifest.xml` inside the `demo` module. None of the videos under **IMA sample ad tags** section play ads and the logcat shows the below error every time.

```
AdError [errorType: LOAD, errorCode: AdErrorCode [name: VAST_EMPTY_RESPONSE, number: 1009], message: The VAST response document is empty.]
```

## Steps to reproduce

1. Git clone the ExoPlayer repo from [here](https://github.com/google/ExoPlayer)
2. Go to [demos/main/src/main/AndroidManifest.xml](https://github.com/google/ExoPlayer/blob/release-v2/demos/main/src/main/AndroidManifest.xml) and change the line ~~`package="com.google.android.exoplayer2.demo"`~~ to `package="tv.horseandcountry"`
3. Gradle sync your project and run
4. Play any title under the **IMA sample ad tags** section.
5. Notice the ads won't play and the `VAST_EMPTY_RESPONSE` error would be seen in the logcat.

## Other Details
- ExoPlayer version number: **r2.14.2**
- Android version: **7.1.2** & **Android 11**
- Android device: **Amazon Fire TV Stick 4k** & **Google Pixel 2 XL**

**Comment by anas-incedo** [comment]
Attaching bug report.
[bugreport-NS6281-2021-08-03-15-28-36.zip](https://github.com/google/ExoPlayer/files/6923341/bugreport-NS6281-2021-08-03-15-28-36.zip)

**Comment by andrewlewis** [comment]
I think the problem must be with the ad server or the IMA SDK itself -- ExoPlayer doesn't do any handling dependent on the package name that could explain this. I'd recommend reporting it on the [IMA SDK forum](https://groups.google.com/g/ima-sdk).

Had a quick look at the bug report anyway and I couldn't see anything obviously going wrong depending on the package name. You could try enabling debug mode for the IMA extension (`ImaAdsLoader.Builder.setDebugModeEnabled`) just in case there is any useful diagnostic info.

**Comment by andrewlewis** [comment]
I've filed [internal: b/195517075] to ask the IMA SDK team directly but I'd still recommend posting on their official forum.

**Comment by andrewlewis** [comment]
This is being addressed on https://groups.google.com/g/ima-sdk/c/IpqFjlRHVnw.
