### ISSUE TITLE
ExoPlayer fails to play HLS with AAC audio

### ISSUE THREAD

**Issue by radian09** [google/ExoPlayer#925]
The following video is unable to play on all devices when added as an HLS sample within the latest 1.5.2 demo app:

http://videos.smugmug.com/Iceland/i-p78nnnx/0/SMIL/p78nnnx.smil/master.m3u8

The video will play correctly if I disable audio by commenting out the TS_STREAM_TYPE_AAC case switch within TsExtractor.consume().  Downloading each ts file and inspecting it in VLC shows stream 1 as MPEG AAC Audio (mp4a), but it doesn't appear AdtsReader is being invoked on any data and the DefaultTrackOutput is never assigned a format so the player never leaves STATE_PREPARING.  

I'm unsure how to proceed at this point and any guidance would be appreciated.  I did not generate this video, so its possible there is something wrong with its encoding but it does play using Android's VideoView.

**Comment by ojw28** [comment]
I think this is the same as #905 (i.e. stream declares audio but does not contain any). Are you sure the stream actually contains audio, as opposed to falsely claiming that it does?
