### ISSUE TITLE
SmoothStream track (format) label metadata is not made available

### ISSUE THREAD

**Issue by rossbeazley** [google/ExoPlayer#9252]
This is a bug very similar to https://github.com/google/ExoPlayer/issues/1095

When parsing smooth streams, the label that can appear on StreamIndex is not propogated to associated Format objects. Inclusion of the label will make presenting choices of captions, subtitles or audio tracks nicer to the user.

[This commit](https://github.com/google/ExoPlayer/commit/6ce1a2b1cdc23b135c8816dce04941c468980401) adds a failing test illustrating it and the fix is [here](https://github.com/google/ExoPlayer/commit/998c924989f30916eceeedc62f1068da969b0112).

Im currently trying to sort out access with our corporate CLA primary point of contact but its quite trivial and could just be transcribed if you wish. The PR is raised [here](https://github.com/google/ExoPlayer/pull/9253).

**Comment by andrewlewis** [comment]
I'll take a look at submitting a simple fix directly and let you know if I run into any issues. Thanks!

**Comment by rossbeazley** [comment]
👌
