### ISSUE TITLE
Help me，After the player has paused, the time in the notification bar continues to add up！

### ISSUE THREAD

**Issue by Mighty-tech** [google/ExoPlayer#9255]

**Comment by andrewlewis** [comment]
I just tried modifying the demo app to use a [`PlayerNotificationManager`](https://github.com/google/ExoPlayer/blob/c7d34d7/library/ui/src/main/java/com/google/android/exoplayer2/ui/PlayerNotificationManager.java) to show a notification and it worked fine (when pausing/resuming the position in the notification stopped/resumed advancing as expected).

There isn't enough information here for us to help. If you want us to look into this further, please provide enough information for us to reproduce the problem, for example, a minimal sample project or patch to the ExoPlayer demo app that shows the behavior.

**Comment by Mighty-tech** [comment]
Sorry, I'm using [uamp](https://github.com/android/uamp) For the open source project, there is a problem with his sample (after the player is suspended, the time of the notification bar continues to increase), The notification bar uses [playernotificationmanager]( https://github.com/google/ExoPlayer/blob/c7d34d7/library/ui/src/main/java/com/google/android/exoplayer2/ui/PlayerNotificationManager.java)。

**Comment by andrewlewis** [comment]
Have you reported this on the [UAMP issue tracker](https://github.com/android/uamp/issues)? Based on my testing, the player notification manager is working fine in the ExoPlayer demo app, so I think it should be reported to UAMP first.

**Comment by andrewlewis** [comment]
Marking as an app issue for now but feel free to reopen or file a new issue if you find evidence this is a problem with ExoPlayer components.
