### ISSUE TITLE
How to Hide seekbar in exoplayer leanback implementation

### ISSUE THREAD

**Issue by nithinkumarnk88** [google/ExoPlayer#9260]
Hi Team,
We have implemented a player in our application on Leanback using Exoplayer and for UI controls we have extended PlaybackSupportFragment.
We could not find a way, how to hide the seekbar for live tv content. We also extend PlaybackSeekDataProvider for seekbar data for non live content. But for live content we have a requirement to hide the seekbar.

Any suggestions will be of great help

Thanks.
Nithin

**Comment by andrewlewis** [comment]
From what I can tell this is about how app code integrates with `androidx.leanback`, not about the ExoPlayer `PlayerAdapter` for leanback, so I suggest [filing a bug in the androidx.leanback component](https://issuetracker.google.com/issues/new?component=460758&template=1422626). If that's not correct, could you give some more information on what change you'd expect to the `LeanbackPlayerAdapter` to resolve this? Thanks.
