### ISSUE TITLE
play RTMP URL 

### ISSUE THREAD

**Issue by patelakshay13890** [google/ExoPlayer#9269]
How Can I play RTMP Url in ExoPlayer ??
I don't get latest example for RTMP in version r2.14.2...
So please help me out...

**Comment by andrewlewis** [comment]
Please see the [RTMP extension readme](https://github.com/google/ExoPlayer/blob/1ee5151/extensions/rtmp/README.md#using-the-extension). If you have added a dependency from your app onto the RTMP extension then load a URL starting `rtmp://` it should just work.
