### ISSUE TITLE
[Question]how to  play multiple mp4 videos gapless

### ISSUE THREAD

**Issue by silo4** [google/ExoPlayer#9270]
Hi, I'm using exoplayer 2.12.1.
I want to play multiple local videos gapless.My app runs on Android TV.
When my videos are all the same definitions(eg, all are 1080p mp4[h264] videos), they play gapless.
But when they are not the same def[eg, 1080p + 720p mp4 videos], it's not gapless. There is a black screen when begin playing the next.
All videos are mp4 (h264+aac) files and they are local files.

Is there a way to solve this question?
My code is like below:

```
String filePath1 = "/mnt/sdcard/Download/1.mp4";
  String filePath2 = "/mnt/sdcard/Download/2.mp4";
  String filePath3 = "/mnt/sdcard/Download/3.mp4";

 DataSource.Factory factory = new DefaultDataSourceFactory(this.getApplicationContext());
    MediaSource mediaSource1 = new ProgressiveMediaSource.Factory(factory)
        .createMediaSource(MediaItem.fromUri(
            Uri.parse(filePath1)));
    MediaSource mediaSource2 = new ProgressiveMediaSource.Factory(factory)
        .createMediaSource(MediaItem.fromUri(
            Uri.parse(filePath2)));
    MediaSource mediaSource3 = new ProgressiveMediaSource.Factory(factory)
        .createMediaSource(MediaItem.fromUri(
            Uri.parse(filePath3)));

 List<MediaSource> mediaSourceList = new ArrayList<>();
   mediaSourceList.add(mediaSource1);
    mediaSourceList.add(mediaSource2);
    mediaSourceList.add(mediaSource3);   

 player.setMediaSources(mediaSourceList);
    player.setRepeatMode(Player.REPEAT_MODE_ALL);
    player.prepare();     
``` 

Sorry, my English is not good.
Thanks！

**Comment by claincly** [comment]
You can try using the playlist API, so instead of creating the DataSources yourself, you can simply add the `MediaItems`.

[This doc may come in handy.](https://exoplayer.dev/playlists.html)

**Comment by silo4** [comment]
@claincly Hi, thank you for you reply. But I think they are same in the bottom.
I have tried it like this:
`player.addMediaItem(MediaItem.fromUri(
        Uri.parse(filePath2)));
    player.addMediaItem(MediaItem.fromUri(
        Uri.parse(filePath3)));
    player.addMediaItem(MediaItem.fromUri(
        Uri.parse(filePath4)));`

and the question also exists.

**Comment by silo4** [comment]
As what it says here [https://medium.com/google-exoplayer/exoplayer-2-x-mediasource-composition-6c285fcbca1f](url)
at the part "Seamlessly playing a sequence of videos". I tried using ConcatenatingMediaSource, and replace the ExtractorMediaSource with ProgressiveMediaSource.  It doesn't solve the question either.
The code is like below:

`DataSource.Factory factory = new DefaultDataSourceFactory(this.getApplicationContext());
 MediaSource mediaSource2 = new ProgressiveMediaSource.Factory(factory)
        .createMediaSource(MediaItem.fromUri(
            Uri.parse(filePath2)));
    MediaSource mediaSource3 = new ProgressiveMediaSource.Factory(factory)
        .createMediaSource(MediaItem.fromUri(
            Uri.parse(filePath3)));
    MediaSource mediaSource4 = new ProgressiveMediaSource.Factory(factory)
        .createMediaSource(MediaItem.fromUri(
            Uri.parse(filePath4)));
            ConcatenatingMediaSource concatenatingMediaSource = new ConcatenatingMediaSource(mediaSource2, mediaSource3, mediaSource4);
    player.setMediaSource(concatenatingMediaSource);
    player.setRepeatMode(Player.REPEAT_MODE_ALL);
    player.prepare();`

Could you  give me some solution or suggestion?

**Comment by silo4** [comment]
After my testing, it occurs on Android 4.4. It plays gapless on other android version (7.1.2/6.0/9.0).
But I don't know what the difference is.

**Comment by icbaker** [comment]
What devices are you using for these cases? It's likely related to device-specific decoder behaviour.

Can you provide the exact media you're using to reproduce the problem? Please either upload it here or send to dev.exoplayer@gmail.com using a subject in the format "Issue #1234" (where "#1234" should be replaced with this issue number.) Please also update this issue to indicate you’ve done this.

**Comment by icbaker** [comment]
> After my testing, it occurs on Android 4.4. It plays gapless on other android version (7.1.2/6.0/9.0).

Android 4.4 (KitKat) is pretty old at this point, with only ~4% of devices running it. If this doesn't repro on any newer devices then I'm afraid it's unlikely we'll be able to dedicate much time to investigating - especially as this isn't a playback failure/crash.

**Comment by silo4** [comment]
@icbaker Thank you for your reply. It just exists on 4.4 by my testing.  I know it's old version.
I would close this. 
At the end, could you give me some suggestions or directions if I want to investigate it to avoid the black gap.
