### ISSUE TITLE
What is the best approach to stream .mp3 .flac files from cloud

### ISSUE THREAD

**Issue by marianpavel** [google/ExoPlayer#928]
Hi, I apologize for posting such a newby question but I really don't know if I should use SampleSource, Dash or Smooth for this tasks.

I have also study the sample source but I would like depending of your answer to give me a mimial example ( not fancy ) about how to do the implementation. Thank you.

Best Marian.

**Comment by andrewlewis** [comment]
[ExtractorRendererBuilder](https://github.com/google/ExoPlayer/blob/master/demo/src/main/java/com/google/android/exoplayer/demo/player/ExtractorRendererBuilder.java) shows how to set up a sample source for playing e.g. an MP3 file from a URI. FLAC support is work in progress, tracked by #366 (but for now you could try using the deprecated [FrameworkSampleSource](https://github.com/google/ExoPlayer/blob/master/library/src/main/java/com/google/android/exoplayer/FrameworkSampleSource.java)).
