### ISSUE TITLE
No Audio track selection after adding ffmpeg extension

### ISSUE THREAD

**Issue by dhaval-devstree** [google/ExoPlayer#9285]
Initially, I have implemented a track selection dialog, and it's working fine. Then I facing with the '.ac3' audio codec with no sound play so I have followed the FFMPEG extension steps and added an extension in my app. Using FFMPEG extension .ac3 codec audio working fine but track selection is not allowed.  

I have debugged everything, I am getting 2 tracks in video information but it's not showing in the track selection dialog. 

When reporting a bug:
-------------------------
- Reproduction steps
  - Generated Ffmpeg extension .aar file and adding in working player with track selection
  - Give FFmpeg support to the current player using the below code. After that no audio track selection allow
   
```
val trackSelectionFactory: ExoTrackSelection.Factory = AdaptiveTrackSelection.Factory()
val defaultRenderersFactory = DefaultRenderersFactory(context).setExtensionRendererMode(DefaultRenderersFactory.EXTENSION_RENDERER_MODE_ON)

trackSelector = DefaultTrackSelector(context, trackSelectionFactory)

player = SimpleExoPlayer.Builder(context, defaultRenderersFactory)
    .setMediaSourceFactory(mediaSourceFactory)
    .setTrackSelector(trackSelector!!).build()

```
- URI to test content for reproduction
  - Testing video Url : [http://172.105.33.71/ministra_dev/public/4119330.mkv](url)

- ExoPlayer version number v2.14.2
- Android version: 10
- Android device: Redmi Note 7 Pro

Log sample: 
-------------------------
```
MediaCodecAudioRenderer []
FfmpegAudioRenderer [
     Group:0, adaptive_supported=N/A [
       [X] Track:0, id=2, mimeType=audio/eac3, channels=2, sample_rate=48000, language=es, label=Latino [www.GDRIVELatinoHD.site], supported=YES
     ]
     Group:1, adaptive_supported=N/A [
       [ ] Track:0, id=3, mimeType=audio/eac3, channels=2, sample_rate=48000, language=en, label=Inglés [www.GDRIVELatinoHD.site], supported=YES
  
 downstreamFormat [eventTime=1.23, mediaPos=0.00, window=1, period=1, id=1, mimeType=video/avc, codecs=avc1.640028, res=1920x1080, language=und, label=www.GDRIVELatinoHD.site]

audioDecoderInitialized [eventTime=1.31, mediaPos=0.00, window=1, period=1, ffmpegLavc58.54.100-eac3]
audioInputFormat [eventTime=1.31, mediaPos=0.00, window=1, period=1, id=2, mimeType=audio/eac3, channels=2, sample_rate=48000, language=es, label=Latino [www.GDRIVELatinoHD.site]]

Format(2, Latino [www.GDRIVELatinoHD.site], null, audio/eac3, null, -1, es, [-1, -1, -1.0], [2, 48000])
Format(3, Inglés [www.GDRIVELatinoHD.site], null, audio/eac3, null, -1, en, [-1, -1, -1.0], [2, 48000])
```

Screenshots : 
-------------------------
 Before adding Ffmpeg track is disable and no sound due to audio/eac3 not being supported by default.
![device-2021-08-16-103007](https://user-images.githubusercontent.com/51994348/129521671-5c57e500-b0b3-40e7-aba8-56d827e87e28.png)

 After adding Ffmpeg no track selection
![device-2021-08-16-103208](https://user-images.githubusercontent.com/51994348/129521718-b0c70f1b-e575-4f81-8e46-0ddc8c37a95d.png)

**Comment by AquilesCanta** [comment]
Back to @claincly for assignment to someone from the ExoPlayer team with ownership over track selection.

**Comment by AquilesCanta** [comment]
Also, @dhaval-devstree, please fill the issue template. Specifically useful here:
- bugreport.
- sample media with which we can reproduce the issue.

Please look at the [issue template](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md) if you would like to learn how to obtain a bugreport or share media with us.

**Comment by dhaval-devstree** [comment]
> Also, @dhaval-devstree, please fill the issue template. Specifically useful here:
> 
> * bugreport.
> * sample media with which we can reproduce the issue.
> 
> Please look at the [issue template](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md) if you would like to learn how to obtain a bugreport or share media with us.

@AquilesCanta Sorry for the unformatted report. I have updated the bug report as per the issues template please check and help me with that issues.
