### ISSUE TITLE
Why ExoPlayer targetSdkVersion is 28?

### ISSUE THREAD

**Issue by sruditsky** [google/ExoPlayer#9292]
ExoPlayer's constant.gradle contains:

appTargetSdkVersion = 29
targetSdkVersion = 28 // TODO: Bump once b/143232359 is resolved. Also fix TODOs in UtilTest.

What is b/143232359?
Is there any know issue of using ExoPlayer in applications with targetSdkVersion > 28?

**Comment by icbaker** [comment]
`targetSdkVersion` has been changed to 30 in the 2.15.0 release: https://github.com/google/ExoPlayer/commit/bb2e0bc0ef0d4f9055980118e46b0203951657a6

> What is b/143232359?

This is a google-internal issue tracker link - in this case the issue it links is public and the TODO probably should have referenced the public URL instead: https://issuetracker.google.com/143232359
