### ISSUE TITLE
Does ExoPlayer support transparent video playback? Is is possible to set different playback speeds by specifying a time interval?

### ISSUE THREAD

**Issue by androidGhost** [google/ExoPlayer#9293]
Thanks Reply！

**Comment by claincly** [comment]
Please provide more context. 

- Transparent video playback: do you mean by the alpha in HEVC?

The way to set playback speed is by using `Player.setPlaybackParameters()`. `PlaybackParameters` sets contains the field of playback speed to set.

**Comment by androidGhost** [comment]
Thanks for your reply, the question I want to talk about is the same as the one below
https://github.com/google/ExoPlayer/issues/7789

**Comment by claincly** [comment]
Please refer to that issue for updates then, it's being open means we haven't added such support. 

Please see [this comment](https://github.com/google/ExoPlayer/issues/7789#issuecomment-875559263) for more info.

I am closing this for now.
