### ISSUE TITLE
play wowza server .m3u8 dvr live sometime no show video, sound only ,  play this live .mpd ver no problem,

### ISSUE THREAD

**Issue by qoo8888** [google/ExoPlayer#9299]
NVIDIA SHIELD 
Android version : 9
exoplayer  2.14.2

play wowza server .m3u8 dvr live sometime no show video, sound only ,  play this live .mpd ver no problem,

aaa m3u8 link:
exo >>  no video , aac sound ok
mxplayer >> video ok , sound ok
pc html5 player >> video ok , sound ok

aaa mpd link:
exo >> video ok, aac sound ok

check MediaCodecVideoRenderer is empty?
please help,thanks

com.google.android.exoplayer2 D/EventLogger:   MediaCodecVideoRenderer []
com.google.android.exoplayer2 D/EventLogger:   MediaCodecAudioRenderer [
com.google.android.exoplayer2 D/EventLogger:     Group:0, adaptive_supported=N/A [
com.google.android.exoplayer2 D/EventLogger:       [X] Track:0, id=0, mimeType=audio/mp4a-latm, bitrate=3702286, codecs=mp4a.40.2, channels=2, sample_rate=44100, supported=YES
com.google.android.exoplayer2 D/EventLogger:     ]
com.google.android.exoplayer2 D/EventLogger:     Metadata [
com.google.android.exoplayer2 D/EventLogger:       HlsTrackMetadataEntry
com.google.android.exoplayer2 D/EventLogger:     ]
com.google.android.exoplayer2 D/EventLogger:

**Comment by qoo8888** [comment]
I have send video link to email,thanks

**Comment by icbaker** [comment]
I can reproduce the problem you're seeing the link provided over email.

Your HLS master playlist only declares the audio codec in the `CODECS` attribute:
```
#EXT-X-STREAM-INF:BANDWIDTH=4795390,CODECS="mp4a.40.2"
```

The media is TS content with audio & video muxed together. The video codec must be provided too. From the [HLS spec](https://datatracker.ietf.org/doc/html/draft-pantos-http-live-streaming#section-4.3.4.2):
> If an EXT-X-STREAM-INF tag or EXT-X-I-FRAME-STREAM-INF tag contains the CODECS attribute, the attribute value MUST include every media format [RFC6381] present in any Media Segment in any of the Renditions specified by the Variant Stream.

I edited the master playlist to include the video codec and the video played successfully in the ExoPlayer demo app v2.15.0.
