### ISSUE TITLE
How to get Proper AdprogressInfo using Exoplayer extension of IMA

### ISSUE THREAD

**Issue by adityaroutandroid** [google/ExoPlayer#9302]
How I will get ad player current position when ad is playing. Am able to get ad duration but am not getting ad current position means that how much second being played. Am working on custom ad controller using exoplayer ima extension,  so I required this information. Please help.

**Comment by ojw28** [comment]
Just calling `getCurrentPosition` on the player should give you the playback position within the ad. If you're interested in the position within the content (i.e., the position from which playback of the content will resume after the ad has finished playing), then you can call `getContentPosition`.

**Comment by adityaroutandroid** [comment]
thanks @ojw28. Its working as expected.
