### ISSUE TITLE
How to set drm_scheme  and drm_license_uri in intent startActivity

### ISSUE THREAD

**Issue by qoo8888** [google/ExoPlayer#9304]
HI
exoplayer 2.14.2

eg
 am start -a com.google.android.exoplayer.demo.action.VIEW \
    -d https://storage.googleapis.com/wvmedia/cenc/h264/tears/tears.mpd \
    --es drm_scheme widevine \
    --es drm_license_uri https://proxy.uat.widevine.com/proxy?video_id=GTS_SW_SECURE_CRYPTO&provider=widevine_test

Intent intent = new Intent(getApplicationContext(), PlayerActivity.class);
intent.setAction(PlayerActivity.ACTION_VIEW);
intent.addCategory("android.intent.category.DEFAULT");
intent.setData(Uri.parse("https://storage.googleapis.com/wvmedia/cenc/h264/tears/tears.mpd"));
startActivity(intent);

How to set drm_scheme  and drm_license_uri in intent startActivity ?
thanks..

**Comment by ojw28** [comment]
I suggest taking a look at [this code in the demo app](https://github.com/google/ExoPlayer/blob/r2.15.0/demos/main/src/main/java/com/google/android/exoplayer2/demo/IntentUtil.java#L200). You can also take a look at https://exoplayer.dev/demo-application.html.
