### ISSUE TITLE
Unable to play xHE-AAC with "none of the extractors available"

### ISSUE THREAD

**Issue by mengli1986** [google/ExoPlayer#9305]
Hi, 
 It appears that the exoplayer couldn't play certain xHE-AAC encoded file, while the quicktime on MAC OS has no problem in playback. I always get "none of the extractor available" error as attached. The mp4 file I am trying to play is [here](https://drive.google.com/file/d/1iWK-Udk00HNjwP7Th2_dEKpVPe5PVEfs/view?usp=sharing) 
![238592425_4442202549181687_5382136929717041406_n](https://user-images.githubusercontent.com/20529230/129641242-07d9b5aa-f702-4b6e-879b-e698350f4d65.png)

Thanks!

**Comment by ojw28** [comment]
The information in the screenshot suggests that you've customized ExoPlayer by injecting only `Mp4Extractor`. The attached file is fragmented MP4, and so `FragmentedMp4Extractor` is required to play it.

The [demo app](https://exoplayer.dev/demo-application.html), which can make use of any of the extractor implementations, uses a `FragmentedMp4Extractor` for this content and is able to play the stream correctly.
