### ISSUE TITLE
WAV extractor never calls attached AnalyticsListener's onAudioDecoderInitialized

### ISSUE THREAD

**Issue by Adamantcheese** [google/ExoPlayer#9306]
An attached AnalyticsListener to an ExoPlayer instance with a WAV file as an audio source will never call onAudioDecoderInitialized, but will call onAudioEnabled followed by onAudioDisabled in the lifecycle of the instance. Any other audio source will call onAudioEnabled, onAudioDecoderInitialized, and onAudioDisabled in the lifecycle of the instance.

- ExoPlayer version number: 2:15.0, but also 2.14.2
- Android version: Emulator, SDK 29
- Android device: Emulator

**Comment by ojw28** [comment]
If the file contains PCM audio data then the player doesn't need to instantiate a decoder. The audio can be fed directly from the source file to the `AudioTrack` for output in this case.
