### ISSUE TITLE
Changing streams 

### ISSUE THREAD

**Issue by SnowcatSVK** [google/ExoPlayer#931]
Hi there,
i have one question regarding HLS, is there any way to change stream links withou creating completely new player and renderer?

**Comment by ojw28** [comment]
You always need to build new renderers. You can optionally re-use the ExoPlayer by passing the new renderers to the existing ExoPlayer instance. This doesn't save much though, and there are some complexities around having to reset the playback position manually, so you may as well just instantiate a new one.
