### ISSUE TITLE
What to do if PTS Wraparound Logic Yields a Negative Value

### ISSUE THREAD

**Issue by acass91** [google/ExoPlayer#9312]
[REQUIRED] Searched documentation and issues

This may be related to issue #8220, but I am unsure if the timestamps in that issue were referring to unadjusted frame presentation timestamps.

[REQUIRED] Question

For context, I'm using ExoPlayer 2.11.1, but I've ported the latest version of TimestampAdjuster into my project; I think I've seen the following with the 2.11.1 version of TimestampAdjuster as well, though.

I added some logs to TimestampAdjuster, specifically adjustTsTimestamp, and I'm seeing a series of negative PTS values. 
The first PTS value is positive and is equal to ptsWrapAbove, but due to the Math.abs(ptsWrapBelow - lastPts)  being less than Math.abs(ptsWrapAbove - lastPts), the PTS gets set to ptsWrapBelow which is a negative value.

Here are the logs:

08-18 18:06:21.793 25387 28296 D TimestampAdjuster: Negative PTS detected! lastPts: 447558321 closestWrapCount: 0 ptsWrapBelow: -2255131118 ptsWrapAbove: **6334803474**
08-18 18:06:21.793 25387 28296 D TimestampAdjuster: Before: **6334803474** Negative PTS: **-2255131118**
08-18 18:06:21.801 25387 28296 D TimestampAdjuster: Negative PTS detected! lastPts: -2255131117 closestWrapCount: 0 ptsWrapBelow: -5981079300 ptsWrapAbove: 2608855292
08-18 18:06:21.801 25387 28296 D TimestampAdjuster: Before: 2608855292 Negative PTS: -5981079300
08-18 18:06:21.805 25387 28296 D TimestampAdjuster: Negative PTS detected! lastPts: -5981079299 closestWrapCount: 0 ptsWrapBelow: -5981077798 ptsWrapAbove: 2608856794
08-18 18:06:21.805 25387 28296 D TimestampAdjuster: Before: 2608856794 Negative PTS: -5981077798
08-18 18:06:21.807 25387 28296 D TimestampAdjuster: Negative PTS detected! lastPts: -5981077797 closestWrapCount: 0 ptsWrapBelow: -5981082302 ptsWrapAbove: 2608852290
08-18 18:06:21.807 25387 28296 D TimestampAdjuster: Before: 2608852290 Negative PTS: -5981082302
08-18 18:06:21.812 25387 28296 D TimestampAdjuster: Negative PTS detected! lastPts: -5981082301 closestWrapCount: 0 ptsWrapBelow: -5981080800 ptsWrapAbove: 2608853792
08-18 18:06:21.812 25387 28296 D TimestampAdjuster: Before: 2608853792 Negative PTS: -5981080800
08-18 18:06:21.815 25387 28296 D TimestampAdjuster: Negative PTS detected! lastPts: -5981080799 closestWrapCount: 0 ptsWrapBelow: -5981076296 ptsWrapAbove: 2608858296
08-18 18:06:21.815 25387 28296 D TimestampAdjuster: Before: 2608858296 Negative PTS: -5981076296
08-18 18:06:21.817 25387 28296 D TimestampAdjuster: Negative PTS detected! lastPts: -5981076295 closestWrapCount: 0 ptsWrapBelow: -5981074794 ptsWrapAbove: 2608859798
08-18 18:06:21.817 25387 28296 D TimestampAdjuster: Before: 2608859798 Negative PTS: -5981074794
08-18 18:06:21.819 25387 28296 D TimestampAdjuster: Negative PTS detected! lastPts: -5981074794 closestWrapCount: 0 ptsWrapBelow: -5981061282 ptsWrapAbove: 2608873310
08-18 18:06:21.819 25387 28296 D TimestampAdjuster: Before: 2608873310 Negative PTS: -5981061282

If ExoPlayer does not support negative presentation timestamps, how might I mitigate this issue?

**Comment by ojw28** [comment]
I don't really follow how you'd end up in this situation unless the timestamps in the source content are incorrect. Please could you share some content that reproduces the issue, if you want us to take a closer look?

**Comment by acass91** [comment]
I sent an email to dev.exoplayer@gmail.com with the content. After further investigation, I agree that the timestamps in the source content are incorrect. I implemented a workaround to avoid feeding the bad PTS values to the adjuster. Do you think this is viable?

```
      if (previousPts != -1 && Math.abs(pts - previousPts) > PTS_TICKS_PER_SECOND * 2) {
          // Try not feeding the PTS to the timestamp adjuster if the difference is too great.
          Log.w(TAG, "Current PTS is " + pts + ", but previous PTS was " + previousPts + "!");
        } else {

          if (!firstGoodPts && previousPts != -1) {
            timestampAdjuster.reset(TimestampAdjuster.ptsToUs(pts));
            firstGoodPts = true;
          }

          timeUs = timestampAdjuster.adjustTsTimestamp(pts);
        }
        previousPts = pts;
```

**Comment by ojw28** [comment]
I think it would probably break other usages of the adjuster (e.g., when the timestamp adjuster is used to determine the duration of a TS stream, it's going to be fed timestamps that are separated by approximately the duration of the content).

I think we should probably just do nothing and mark down as a case of bad media.

**Comment by acass91** [comment]
If I am only working with bad live streams, in which case the duration is unknown, would this still break other usages of the adjuster?

**Comment by ojw28** [comment]
I'm not sure to be honest. If you choose to make this modification locally, then I think you'll just have to put it through a sufficient level of QA to be confident that it's safe.
