### ISSUE TITLE
Listening to Ad Events

### ISSUE THREAD

**Issue by olgunkaya** [google/ExoPlayer#9320]
Hi,

In my application's iOS version I am listening to the events defined here https://developers.google.com/interactive-media-ads/docs/sdks/ios/client-side/reference/Enums/IMAAdEventType

Can I listen to the same event using exoplayer-ima extension in Android too ? if so can you point me to a page for implementing it on my app's android version too ?

**Comment by andrewlewis** [comment]
This looks the same as #8795. If that doesn't answer the question please provide some more information about what is needed.
