### ISSUE TITLE
Error While Using RTMP Extension

### ISSUE THREAD

**Issue by patelakshay13890** [google/ExoPlayer#9322]
![image](https://user-images.githubusercontent.com/6092323/130328636-65216fcb-cf8e-4a59-a3ad-ad080c895d2d.png)
I am getting this error while Using extension rtmp...
How can I resolve this issue ?

**Comment by minzbox** [comment]
Add jcenter() to your project gradle file

**Comment by patelakshay13890** [comment]
And please can you provide me a sample link for the RTMP example ?

**Comment by icbaker** [comment]
I agree with @minzbox, it looks like you're missing `jcenter()` in the `allprojects.repositories` section of your project-level `build.gradle` file. RTMP is currently only distributed on jcenter - they're working on hosting it elsewhere before jcenter shuts down: https://github.com/ant-media/LibRtmp-Client-for-Android/issues/96
