### ISSUE TITLE
WebVTT cue positioning issue

### ISSUE THREAD

**Issue by JRFrampton** [google/ExoPlayer#9324]
Question about the intended behavior of WebVTT `line` values. Using `SubtitleView` there is a constant [DEFAULT_BOTTOM_PADDING_FRACTION](https://github.com/google/ExoPlayer/blob/release-v2/library/ui/src/main/java/com/google/android/exoplayer2/ui/SubtitleView.java#L89) which describes the default behavior of `Cue`s that have `Cue#line` set to `Cue#DIMEN_UNSET`. This would allow cues with no positional arguments to float off the bottom of the player.

[Prior to the 2.12.0 release](https://github.com/google/ExoPlayer/blob/r2.11.8/library/core/src/main/java/com/google/android/exoplayer2/text/webvtt/WebvttSubtitle.java#L74), it seems that cues that overlapped in timing would simply append to the spanned string of the first "normal" cue and the `Cue#line` would be left as `DIMEN_UNSET` if no line was set. This then allows the `DEFAULT_BOTTOM_PADDING_FRACTION` to be applied to cues.

[In 2.12.0 and onwards however](https://github.com/google/ExoPlayer/blob/r2.12.0/library/core/src/main/java/com/google/android/exoplayer2/text/webvtt/WebvttSubtitle.java#L70), that logic was changed to better adhere to the [w3 WebVTT spec](https://www.w3.org/TR/webvtt1/#cue-computed-line). It seems as a consequence of this change, now all cues regardless of overlap have the `line` set to -1 which causes the `DEFAULT_BOTTOM_PADDING_FRACTION` logic to no longer be accessible and all cues render at the bottom of the screen. This is problematic for OTT/10ft applications as overscan then cuts off the bottom of the captions.

Is there another way to apply this default bottom padding still via the `SubtitleView` (outside of adding view padding/margins)?

**Comment by icbaker** [comment]
https://github.com/google/ExoPlayer/issues/7934#issuecomment-694063859 has more info on this deliberate change, as well as some suggestions for how you can make the subtitles appear higher on the screen.

**Comment by JRFrampton** [comment]
Thanks Ian. I got it resolved.
