### ISSUE TITLE
How to Parse my m3u8 file in exoplayer

### ISSUE THREAD

**Issue by androaddict** [google/ExoPlayer#9326]
I have a m3u8 URL and its a Live Streaming. so it will update frequently. So that I want to parse my m3u8 content. Mainly I focus on Particular tag from m3u8 file. so how to parse my m3u8

**Comment by icbaker** [comment]
From https://github.com/google/ExoPlayer/issues/9331 it looks like you've found the manifest info you need? I'm going to close this - please reply here  if you still need help, providing some more information about exactly what you're trying to achieve. It would also be helpful to provide a link to a playlist that we can look at to understand what you're working with. Please either link it here or send to dev.exoplayer@gmail.com using a subject in the format "Issue #1234" (where "#1234" should be replaced with this issue number.) Please also update this issue to indicate you’ve done this.
