### ISSUE TITLE
Сlick on ads does not work on Android TV (IMA)

### ISSUE THREAD

**Issue by kirkaDev** [google/ExoPlayer#9328]
Working with smartphones and tablets when 

> onAdClicked()

 method of  EventListener invoked everything works well, the browser opens and the desired web page opens.

 _But when I run the same code on the Android TV devices_ (emulator or real device), then nothing happens.
 
1. In debug mode, I see that the condition for the  "case CLICKED"  is satisfied and I can't understand what's the matter. 

The only difference is that I run the application on an Android TV device.

At first, I thought that the point was that neither of the browsers was installed on the device, but after installing two applications, I realized that this was not the case.
 
```
private void handleAdEvent(AdEvent adEvent) {
    if (adsManager == null) {
      // Drop events after release.
      return;
    }
    switch (adEvent.getType()) {
      case AD_BREAK_FETCH_ERROR:
        String adGroupTimeSecondsString = checkNotNull(adEvent.getAdData().get("adBreakTime"));
        if (configuration.debugModeEnabled) {
          Log.d(TAG, "Fetch error for ad at " + adGroupTimeSecondsString + " seconds");
        }
        double adGroupTimeSeconds = Double.parseDouble(adGroupTimeSecondsString);
        int adGroupIndex =
            adGroupTimeSeconds == -1.0
                ? adPlaybackState.adGroupCount - 1
                : getAdGroupIndexForCuePointTimeSeconds(adGroupTimeSeconds);
        markAdGroupInErrorStateAndClearPendingContentPosition(adGroupIndex);
        break;
      case CONTENT_PAUSE_REQUESTED:
        // After CONTENT_PAUSE_REQUESTED, IMA will playAd/pauseAd/stopAd to show one or more ads
        // before sending CONTENT_RESUME_REQUESTED.
        imaPausedContent = true;
        pauseContentInternal();
        break;
      case TAPPED:
        for (int i = 0; i < eventListeners.size(); i++) {
          eventListeners.get(i).onAdTapped();
        }
        break;
      case CLICKED:
        for (int i = 0; i < eventListeners.size(); i++) {
          eventListeners.get(i).onAdClicked();
        }
        break;
      case CONTENT_RESUME_REQUESTED:
        imaPausedContent = false;
        resumeContentInternal();
        break;
      case LOG:
        Map<String, String> adData = adEvent.getAdData();
        String message = "AdEvent: " + adData;
        Log.i(TAG, message);
        break;
      default:
        break;
    }
  }
```
2. Also when I run the code on a TV device the "Learn More" button is not displayed.

3. When ads is playing and I using D-Pad, firstly the focus is getting the view to navigate through the ad, but after several clicks on the direction buttons of D-Pad, it fails to get focus again, I can set focus to the "Skip ad" button only.

And I cannot figure out why this is so, there is no way to look at the source code.

I ask for your advice, maybe the implementation of the player and advertising for Android TV should somehow be different.

I am using exoPlayer version 2.14.1 and tried with 2.15.0

Thank you.

**Comment by icbaker** [comment]
> * Also when I run the code on a TV device the "Learn More" button is not displayed.

Looks like [that's expected](https://developers.google.com/interactive-media-ads/docs/sdks/android/client-side/android-tv):
> The SDK optimizes skippable formats for TV-like devices, for instance by removing the ability to engage with a Learn More button. By default, the SDK sets focus on the skip button when skipping is available so the ad can be skipped on Android TV. 
-----
> And I cannot figure out why this is so, there is no way to look at the source code.

This is the ExoPlayer issue tracker, and ExoPlayer is open source, so you should be able to look at the source code for anything that's in scope for this issue tracker :) This looks like a question about the IMA SDK (which the ExoPlayer IMA extension depends on) - I suggest you ask on https://groups.google.com/g/ima-sdk.

**Comment by kirkaDev** [comment]
Thank you very much for the clarification, Ian. 
Now everything became clear to me.
