### ISSUE TITLE
After upgrade to exoplayer 2.13.3, live playback speed became to variant speed. 

### ISSUE THREAD

**Issue by zgzong** [google/ExoPlayer#9329]
After upgrade to exoplayer 2.13.x onwards, the live playback speed became variant speed between range [0.97, 1.03], even for normal non-low latency live stream.

- URI to test content for reproduction
https://livesim.dashif.org/livesim/mup_30/testpic_2s/Manifest.mpd"

- ExoPlayer version number
Tested with 2.13.3

- Android version
android 11

- Android device
Samsung SM-P610

Since the 2.13.0, exoplayer introduce DefaultLivePlaybackSpeedControl.java, getAdjustedPlaybackSpeed function looks check  

> DefaultLivePlaybackSpeedControl.java
if (mediaConfigurationTargetLiveOffsetUs == C.TIME_UNSET) {
      return 1f;
}
and mediaConfigurationTargetLiveOffsetUs = C.msToUs(liveConfiguration.targetOffsetMs);

Because of DASH's DashMediaSource.java updateMediaItemLiveConfiguration logic
private void updateMediaItemLiveConfiguration(long nowInWindowUs, long windowDurationUs) {

Based on current implementation DashMediaSource targetOffsetMs's  can not be TIME_UNSET any more, that means all live stream will play live stream with variant playback speed.

**Comment by icbaker** [comment]
You can customise this behaviour as explained here: https://exoplayer.dev/live-streaming.html#configuring-live-playback-parameters

**Comment by ojw28** [comment]
@christosts @marcbaechinger - Could we reconsider the decision to enable variable playback speed for non-LL streams? I still don't think it's really expected, in general.
