### ISSUE TITLE
Fatal Exception: java.lang.IllegalStateException: onPlayerError()

### ISSUE THREAD

**Issue by ghost** [google/ExoPlayer#9330]
Hello guys, sorry cuz my question placed in not valid region, but i really need help. 
I was implements this lib: https://github.com/HamidrezaAmz/MagicalExoPlayer to play video in my app. It extended from our lib. And i have a crash issue: https://github.com/HamidrezaAmz/MagicalExoPlayer/issues/63
Anyone can help me, pls!

**Comment by icbaker** [comment]
Hi! Please provide complete information as requested in the question template. The template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/question.md).

Unfortunately we can't answer unclear questions or those with insufficient information.

**Comment by ghost** [comment]
@icbaker hi
i use this library to play video in my application: https://github.com/HamidrezaAmz/MagicalExoPlayer, it extended from your lib, and i have an issue is sometime my app crash when i tap to play video
this is my firebase log:
```
com.google.android.exoplayer2.util.Assertions.checkState (Assertions.java:5) 
com.google.android.exoplayer2.ExoPlaybackException.getSourceException (ExoPlaybackException.java:1) 
com.potyvideo.library.AndExoPlayerView.onPlayerError (AndExoPlayerView.java:1) 
com.google.android.exoplayer2.ExoPlayerImpl.lambda$updatePlaybackInfo$9 (ExoPlayerImpl.java:1) 
com.google.android.exoplayer2.-$$Lambda$ExoPlayerImpl$Y5tnvNJdNEscTPhujmeSdRy1n7Y.invoke (-.java:1) 
com.google.android.exoplayer2.util.ListenerSet$ListenerHolder.invoke (ListenerSet.java:4) 
com.google.android.exoplayer2.util.ListenerSet.lambda$queueEvent$0 (ListenerSet.java:4) 
com.google.android.exoplayer2.util.-$$Lambda$ListenerSet$NbKDn9xtItiyMgYZmjIx_Sv1FFQ.run (-.java:4) 
com.google.android.exoplayer2.util.ListenerSet.flushEvents (ListenerSet.java:2)
com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo (ExoPlayerImpl.java:2) com.google.android.exoplayer2.ExoPlayerImpl.handlePlaybackInfo (ExoPlayerImpl.java:5) 
com.google.android.exoplayer2.-$$Lambda$ExoPlayerImpl$nOBJYkeEQ2uz3sBKLToLWmzrgZk.run (-.java:5) 
android.os.Handler.handleCallback (Handler.java:938) 
android.os.Handler.dispatchMessage (Handler.java:99) 
android.os.Looper.loop (Looper.java:263) 
android.app.ActivityThread.main (ActivityThread.java:8267) 
java.lang.reflect.Method.invoke (Method.java) 
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:612) 
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1006)
```

In my programmatically, i have calls `startPlayer()` in `onStart()` callback and `pausePlayer()` in `onStop()`
`andExoPlayerView.startPlayer()` `andExoPlayerView.pausePlayer()`
in addition, i calls `setSource()` inside BindingAdapter file
`view.setSource(url)`
crash occurs at line `com.potyvideo.library.AndExoPlayerView.onPlayerError` (AndExoPlayerView.java:1)

**Comment by icbaker** [comment]
This looks like a bug in `com.potyvideo.library.AndExoPlayerView`. It is [unconditionally calling `ExoPlaybackException#getSourceException`](https://github.com/HamidrezaAmz/MagicalExoPlayer/blob/17e1c70d118d4e5bff686ea19b7127c595fb4a89/library/src/main/java/com/potyvideo/library/AndExoPlayerView.kt#L113) without first checking if `ExoPlaybackException#type == TYPE_SOURCE`:

From the [ExoPlaybackException#getSourceException javadoc](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/ExoPlaybackException.html#getSourceException()):
> **Throws:** `IllegalStateException` - If `type` is not `TYPE_SOURCE`.

I suggest you report this to the maintainers of `AndExoPlayerView`.
