### ISSUE TITLE
Fatal Exception: java.lang.IllegalArgumentException Receiver not registered: q2.a$b$b@43f7836

### ISSUE THREAD

**Issue by andj207** [google/ExoPlayer#9333]
My app use exoplayer to play video downloaded from the internet. Firebase Crashlytics recently reports many crashes (on Xiaomi, Realme, motorola,...) as below. I am using exoplayer version 2.14.2.

    Fatal Exception: java.lang.IllegalArgumentException Receiver not registered: q2.a$b$b@43f7836

    android.app.LoadedApk.forgetReceiverDispatcher (LoadedApk.java:1433)
    android.app.ContextImpl.unregisterReceiver (ContextImpl.java:1553)
    android.content.ContextWrapper.unregisterReceiver (ContextWrapper.java:674)
    androidx.media2.player.AudioFocusHandler$AudioFocusHandlerImplBase.unregisterBecomingNoisyReceiverLocked (AudioFocusHandler.java:261)
    androidx.media2.player.AudioFocusHandler$AudioFocusHandlerImplBase.onPause (AudioFocusHandler.java:161)
    androidx.media2.player.AudioFocusHandler.onPause (AudioFocusHandler.java:76)
    androidx.media2.player.MediaPlayer$3.onExecute (MediaPlayer.java:802)
    androidx.media2.player.MediaPlayer$PendingFuture.execute (MediaPlayer.java:574)
    androidx.media2.player.MediaPlayer.executePendingFutures (MediaPlayer.java:3268)
    androidx.media2.player.MediaPlayer.addPendingFuture (MediaPlayer.java:730)
    androidx.media2.player.MediaPlayer.pause (MediaPlayer.java:811)
    androidx.media2.player.AudioFocusHandler$AudioFocusHandlerImplBase$AudioFocusListener.onAudioFocusChange (AudioFocusHandler.java:417)
    android.media.AudioManager$ServiceEventHandlerDelegate$1.handleMessage (AudioManager.java:2566)
    android.os.Handler.dispatchMessage (Handler.java:107)
    android.os.Looper.loop (Looper.java:225)
    android.app.ActivityThread.main (ActivityThread.java:7564)
    java.lang.reflect.Method.invoke (Method.java)
    com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:539)
    com.android.internal.os.ZygoteInit.main (ZygoteInit.java:950)

**Comment by andrewlewis** [comment]
Please report `androidx.media2.player` issues on the AndroidX issue tracker: https://source.android.com/setup/contribute/report-bugs

Slightly off-topic: I'd recommend switching to using ExoPlayer directly instead of using the media2's MediaPlayer.
