### ISSUE TITLE
Question about TimelineQueueNavigator and PlaybackPreparer method argument deprecations

### ISSUE THREAD

**Issue by sQu1rr** [google/ExoPlayer#9338]
I am using classes that inherit from `TimelineQueueNavigator` and `MediaSessionConnector.PlaybackPreparer` to control the media playback in my music service. I have based my implementation on the UAMP code. I recently noticed that the methods that use `ControlDispatcher` are showing deprecation warnings. I am not entirely sure how I need to change my code to avoid these methods/warnings. It looks like the `ForwardingPlayer` is mentioned but I cannot find any documentation on its use.

**Comment by kim-vde** [comment]
It depends on how you are using the `ControlDispatcher`. My understanding is that you are overriding callback methods (like `QueueNavigator.onSkipToPrevious`). Please provide more information if that is not correct.


* If you are not using the `controlDispatcher` parameter in your callback implementation, then you don't need to do anything. These parameters will be removed in a future release.
* If you are using the `controlDispatcher` parameter in your callback implementation, then you should change your implementation to use the `player` parameter only. Let's say that, for some reason, you are calling `controlDispatcher.setPlayerWhenReady()`. If the implementation of `controlDispatcher.setPlayerWhenReady()` is equivalent to `player.setPlayWhenReady()/play()/pause`, then you can just use the latter. If not, then you need to wrap the `player` in a [`ForwardingPlayer`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/ForwardingPlayer.html) that will override `player.setPlayWhenReady()/play()/pause` to match the implementation of `controlDispatcher.setPlayerWhenReady()`.

**Comment by sQu1rr** [comment]
I am not using the argument indeed. So no action is required then. It will be removed in the future release. Correct? Thanks for the prompt reply and the explanation for the `ForwardingPlayer`!

**Comment by kim-vde** [comment]
Yes, that's right (probably in the next major release or the one after).

**Comment by sQu1rr** [comment]
OK, thanks a lot, @kim-vde ! I'm closing the issue
