### ISSUE TITLE
Behaviour of `getMinimumLoadableRetryCount` in `DefaultLoadErrorHandlingPolicy`

### ISSUE THREAD

**Issue by GouravSna** [google/ExoPlayer#9341]
ExoPlayerVersion: v2.15.0

I am trying to give retry count for the http calls which Exo is doing internally (Be it manifest, Chunk/Segment, DRM).
For that, I have my class which extends to `DefaultLoadErrorHandlingPolicy` and I am overriding `getMinimumLoadableRetryCount` in order to achieve it.

**Question:** I can see that when i pass count 2 then LoadError is coming 3 times and then it gives SourceError. I mean when I give value greater than 1, it always results in +1 LoadError.

But when I give 0 or 1 in count, it always results with LoadError 2 times.
I think Exo is internally starting from 0 (with Index). But what is going on with 0 or 1 count value. 

Exo is calling it **minLoadableRetryCount**, is there something max as well ? 
Can you please suggest on it ? Is this the expected behaviour. 

I have tested in ExoDemo app as well by hard coding the return value in `getMinimumLoadableRetryCount` of `DefaultLoadErrorHandlingPolicy`. It is the same behaviour as explained above.

**Comment by GouravSna** [comment]
Hi @ojw28 , Can you please help me on this.

**Comment by ojw28** [comment]
As per the documentation, `getMinimumLoadableRetryCount` returns a _minimum_ number of retries. The player may make more retry attempts than this. This approach is generally useful to allow the player to continue making additional retries for errors that may be recoverable, for as long as it's able to play out media that it had already buffered.

If you want to impose a maximum limit then I think you can do so by overriding `getRetryDelayMsFor` to do something like:

```
if (loadErrorInfo.errorCount > maxRetryCount) {
  return C.TIME_UNSET;
}
return super.getRetryDelayMsFor(loadErrorInfo);
```

As per the Javadoc for that method:

> A return value of {@link C#TIME_UNSET} indicates that the error is fatal and should not be retried.

**Comment by GouravSna** [comment]
Sure. Thanks @ojw28 
I will try it.
