### ISSUE TITLE
Video Rendering and praying bugs

### ISSUE THREAD

**Issue by HappySinha** [google/ExoPlayer#9342]
When I playing video then facing this errors. Anyone can help me

Performing hot reload...
Syncing files to device CPH2213...
Reloaded 0 libraries in 644ms.
I/OplusFeedbackInfo(32666): [sendFPSInfo:L334] mInputBufCnt = 0 fps, mOutputBufCnt = 0 fps, mRenderFrameCnt = 0 fps
I/OplusFeedbackInfo(32666): [sendFPSInfo:L334] mInputBufCnt = 0 fps, mOutputBufCnt = 0 fps, mRenderFrameCnt = 0 fps
I/OplusFeedbackInfo(32666): [sendFPSInfo:L334] mInputBufCnt = 0 fps, mOutputBufCnt = 0 fps, mRenderFrameCnt = 0 fps
I/OplusFeedbackInfo(32666): [sendFPSInfo:L334] mInputBufCnt = 0 fps, mOutputBufCnt = 0 fps, mRenderFrameCnt = 0 fps
I/OplusFeedbackInfo(32666): [sendFPSInfo:L334] mInputBufCnt = 0 fps, mOutputBufCnt = 0 fps, mRenderFrameCnt = 0 fps
I/OplusFeedbackInfo(32666): [sendFPSInfo:L334] mInputBufCnt = 0 fps, mOutputBufCnt = 0 fps, mRenderFrameCnt = 0 fps
I/OplusFeedbackInfo(32666): [sendFPSInfo:L334] mInputBufCnt = 0 fps, mOutputBufCnt = 0 fps, mRenderFrameCnt = 0 fps
I/OplusFeedbackInfo(32666): [sendFPSInfo:L334] mInputBufCnt = 0 fps, mOutputBufCnt = 0 fps, mRenderFrameCnt = 0 fps
I/OplusFeedbackInfo(32666): [sendFPSInfo:L334] mInputBufCnt = 0 fps, mOutputBufCnt = 0 fps, mRenderFrameCnt = 0 fps
I/OplusFeedbackInfo(32666): [sendFPSInfo:L334] mInputBufCnt = 0 fps, mOutputBufCnt = 0 fps, mRenderFrameCnt = 0 fps
I/OplusFeedbackInfo(32666): [sendFPSInfo:L334] mInputBufCnt = 0 fps, mOutputBufCnt = 0 fps, mRenderFrameCnt = 0 fps
I/OplusFeedbackInfo(32666): [sendFPSInfo:L334] mInputBufCnt = 0 fps, mOutputBufCnt = 0 fps, mRenderFrameCnt = 0 fps
I/OplusFeedbackInfo(32666): [sendFPSInfo:L334] mInputBufCnt = 0 fps, mOutputBufCnt = 0 fps, mRenderFrameCnt = 0 fps
I/OplusFeedbackInfo(32666): [sendFPSInfo:L334] mInputBufCnt = 0 fps, mOutputBufCnt = 0 fps, mRenderFrameCnt = 0 fps
I/OplusFeedbackInfo(32666): [sendFPSInfo:L334] mInputBufCnt = 0 fps, mOutputBufCnt = 0 fps, mRenderFrameCnt = 0 fps
I/OplusFeedbackInfo(32666): [sendFPSInfo:L334] mInputBufCnt = 0 fps, mOutputBufCnt = 0 fps, mRenderFrameCnt = 0 fps
I/OplusFeedbackInfo(32666): [sendFPSInfo:L334] mInputBufCnt = 0 fps, mOutputBufCnt = 0 fps, mRenderFrameCnt = 0 fps
I/OplusFeedbackInfo(32666): [sendFPSInfo:L334] mInputBufCnt = 0 fps, mOutputBufCnt = 0 fps, mRenderFrameCnt = 0 fps
I/OplusFeedbackInfo(32666): [sendFPSInfo:L334] mInputBufCnt = 0 fps, mOutputBufCnt = 0 fps, mRenderFrameCnt = 0 fps
I/OplusFeedbackInfo(32666): [sendFPSInfo:L334] mInputBufCnt = 0 fps, mOutputBufCnt = 0 fps, mRenderFrameCnt = 0 fps
I/OplusFeedbackInfo(32666): [sendFPSInfo:L334] mInputBufCnt = 0 fps, mOutputBufCnt = 0 fps, mRenderFrameCnt = 0 fps
I/OplusFeedbackInfo(32666): [sendFPSInfo:L334] mInputBufCnt = 0 fps, mOutputBufCnt = 0 fps, mRenderFrameCnt = 0 fps
I/OplusFeedbackInfo(32666): [sendFPSInfo:L334] mInputBufCnt = 0 fps, mOutputBufCnt = 0 fps, mRenderFrameCnt = 0 fps
I/OplusFeedbackInfo(32666): [sendFPSInfo:L334] mInputBufCnt = 0 fps, mOutputBufCnt = 0 fps, mRenderFrameCnt = 0 fps
I/OplusFeedbackInfo(32666): [sendFPSInfo:L334] mInputBufCnt = 0 fps, mOutputBufCnt = 0 fps, mRenderFrameCnt = 0 fps
I/OplusFeedbackInfo(32666): [sendFPSInfo:L334] mInputBufCnt = 0 fps, mOutputBufCnt = 0 fps, mRenderFrameCnt = 0 fps
I/OplusFeedbackInfo(32666): [sendFPSInfo:L334] mInputBufCnt = 0 fps, mOutputBufCnt = 0 fps, mRenderFrameCnt = 0 fps

**Comment by icbaker** [comment]
Hi! Please provide complete information as requested in the issue template. 

None of the logcat snippet provided looks like it's coming from ExoPlayer.

The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md). If you're unable to share [bug reports](https://developer.android.com/studio/debug/bug-report) or test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #1234" ("#1234" is replaced with your issue number). Please also update this issue to indicate you've done this.
