### ISSUE TITLE
Play audio and video at the same time. (However, post-processing must be possible in the AudioProcessor)

### ISSUE THREAD

**Issue by hotstone1993** [google/ExoPlayer#9343]
Hi 

Currently, we are using two exoplayer instances to play audio and video at the same time.
(This audio was extracted from the video and then processed by our solution.
So, Audio is 5.1 channels and video is stereo)
However, of course, if i repeat seek, play, and pause, the synchronization will gradually become out of sync.
Therefore, I want to play audio and video files with one Exoplayer Instance. 

sum up
- play audio and video at the same time
  ( video is stereo, audio is 5.1 )
- post-processing must be possible (AudioProcessor)
- NO out of sync

Is it possible?

**Comment by icbaker** [comment]
Have you tried using MergingMediaSource?

**Comment by hotstone1993** [comment]
Thank you for quick response.
I use MergingMediaSource and it works perfectly.
(It didn't work when I used MergingMediaSource in the past, but I guess I was used it wrong then.)
