### ISSUE TITLE
Playlist with Ads - Wrap Playlist with 1 Ads Source.

### ISSUE THREAD

**Issue by saurabharora90** [google/ExoPlayer#9344]
I have 3 `MediaItem`(s) in a playlist and I would like to wrap them with 1 Ad Playlist, i.e. the pre-roll plays before the first media item, the mid-rolls plays through the first, second and third media item and the end-roll plays at the end of the third media item.

I had a look at the [documentation](https://exoplayer.dev/ad-insertion.html), and found that:

>It’s possible to customize this behavior by passing an opaque ads identifier with which ad playback state for a given media item is linked, based on object equality. Here is an example where ad playback state is linked to the ad tag URI only, rather than the combination of the media ID and ad tag URI, by passing the ad tag URI as the ads identifier. The effect is that ads will load only once and the user will not see ads on the second item when playing the playlist from start to finish.

This customisation didn't work for us, since no ads were played in the second item (the post-roll was triggered before the start of the second media item).

I also tried wrapping the 3 `MediaItem`(s) in a `ConcatenatingMediaSource` and then wrap the resulting `ConcatenatingMediaSource` with an `AdsMediaSource`. That didn't work and threw an exception. 

Is there any way to achieve this? Would I need to build my own `AdsLoader` for this?

**Comment by icbaker** [comment]
> > The effect is that ads will load only once and **the user will not see ads on the second item** when playing the playlist from start to finish.
> 
> This customisation didn't work for us, since **no ads were played in the second item** (the post-roll was triggered before the start of the second media item).

Sounds like your experience matched the documentation, right?

----


> I also tried wrapping the 3 `MediaItem`(s) in a `ConcatenatingMediaSource` and then wrap the resulting `ConcatenatingMediaSource` with an `AdsMediaSource`. That didn't work and threw an exception.

I believe this is also expected. From the [`AdsMediaSource` javadoc](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/source/ads/AdsMediaSource.html):
> The wrapped content media source must contain a single Timeline.Period.

----

> Is there any way to achieve this? Would I need to build my own AdsLoader for this?

The easiest way seems to be to just 3 different ad tags? One with pre-roll + mid-roll attached to the first item, another with only mid-rolls attached to the second & third items and one with mid-roll + post-roll attached to the fourth item.

**Comment by saurabharora90** [comment]
> Sounds like your experience matched the documentation, right?

Ah Yes. I should have phrased that better. The behaviour was as per the documentation. 

> I believe this is also expected. From the [`AdsMediaSource` javadoc](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/source/ads/AdsMediaSource.html):
> > The wrapped content media source must contain a single Timeline.Period.
 
Yes as well


> > Is there any way to achieve this? Would I need to build my own AdsLoader for this?
> 
> The easiest way seems to be to just 3 different ad tags? One with pre-roll + mid-roll attached to the first item, another with only mid-rolls attached to the second & third items and one with mid-roll + post-roll attached to the fourth item.
> 

Unfortunately that's not feasible for us due to internal limitations. We would need to work with only one ad tag (cross platform support, analytics, and other reasons). Any other thoughts on how that could be achieved?

**Comment by saurabharora90** [comment]
Currently we have our own integration of IMA using a video view on top of Exoplayer. That solves our use case. The hope was to migrate to Exoplayer's implementation to get all the benefits that `AdsMediaSource` provides.

**Comment by icbaker** [comment]
@andrewlewis can you take a look and see if there are any alternative approaches here that I've missed?

**Comment by andrewlewis** [comment]
I don't think there are any alternative approaches that work at the moment -- you'd need to work around the problem by splitting the ad tag as suggested above, or find a way to join the content pieces into one period. https://github.com/google/ExoPlayer/issues/3693 tracks removing the limitation that the content media source may only have one period.
