### ISSUE TITLE
Exoplayer unable to show preview with RTSP url with format “rtsp://ip:port” 

### ISSUE THREAD

**Issue by penmatsa** [google/ExoPlayer#9345]
Using exoplayer to connect to my ip  camera with RTSP url of format rtsp://ip:port.

Getting URL ParserException.

Please provide RTSP url format's supported by exo-player

**Comment by claincly** [comment]
Please provide a log of RTSP messages.

The easiest way is to use the `RtspMediaSource.Factory` method `setDebugLoggingEnabled()`

And any logs you have.

**Comment by penmatsa** [comment]
Sorry for duplicate question.Need to resolve same issue as #9346.

Thank You

**Comment by claincly** [comment]
Please track the issue using #9346. I am closing this for the time being.
