### ISSUE TITLE
Exoplayer expiration token

### ISSUE THREAD

**Issue by javaboboApp** [google/ExoPlayer#9348]
When using dash protocol during a live/vod event and using drm (widevine): 
 
During live event , could player request the license several times in one session?, problem is if token is expired it will not be able to use it.

**Comment by icbaker** [comment]
Is this token passed to the license server as an HTTP request header?

You can control what headers are sent with the license & provision requests with [`HttpMediaDrmCallback#setKeyRequestProperty`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/drm/HttpMediaDrmCallback.html#setKeyRequestProperty(java.lang.String,java.lang.String)). It should work to hold a reference to the `HttpMediaDrmCallback` used by your `DefaultDrmSession`  and modify the headers when you need to. There's info about customising the `DefaultDrmSessionManager` here: https://exoplayer.dev/drm.html#using-a-custom-drmsessionmanager

If you want to modify the headers directly before a request is sent you could implement your own [`MediaDrmCallback`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/drm/MediaDrmCallback.html) that mostly just wraps an `HttpMediaDrmCallback` but changes the headers inside `executeKeyRequest` before forwarding the call to the delegate.

**Comment by javaboboApp** [comment]
Thanks for the answer:
I am using   .**setDrmLicenseRequestHeaders**(requestHeader) and updating token before building each MediaItem, the token is passed in the header I just I am wondering if if possible that during playing the content (once playback has the license) it could request a new license, during playback, If this the case I guess i will have to customize as you propose  **HttpMediaDrmCallback**.

 //Check token expiration and calculate customHeader
 val customHeader = calculateHeader() //If token is expired it will change header with new token. 
  return MediaItem.Builder()
            .setUri(uri)
            .setDrmUuid(C.WIDEVINE_UUID)
            .setDrmLicenseUri("license url")
            .setDrmLicenseRequestHeaders(customHeader)
            .build()
            
  This implementation will not work if player request the license again during playback (it that possible?)

**Comment by icbaker** [comment]
> I just I am wondering if if possible that during playing the content (once playback has the license) it could request a new license, during playback, If this the case I guess i will have to customize as you propose **HttpMediaDrmCallback**.

The DRM stack may refresh the license during playback, yes - the precise behaviour here likely depends on your license policy.

**Comment by javaboboApp** [comment]
@icbaker Ok clear, thanks very much for information :)
