### ISSUE TITLE
Outdated javadoc line about tunneled playback

### ISSUE THREAD

**Issue by moneytoo** [google/ExoPlayer#9350]
https://github.com/google/ExoPlayer/blob/r2.15.0/library/core/src/main/java/com/google/android/exoplayer2/trackselection/DefaultTrackSelector.java#L159 contains outdated information ("_...enabled by passing an audio session ID..._") about tunneled playback, since a95b2ebb1d3125a4899c0dfe4a830077271ebca0.

**Comment by kim-vde** [comment]
Thanks for reporting this. I just pushed the fix!
