### ISSUE TITLE
skipPre or skipnext not working after i click to fast

### ISSUE THREAD

**Issue by Colaman0** [google/ExoPlayer#9351]
I use exoplayer and MediaCompat.

When i call skipToNext or skipToPrevious too fast ,  then it will not working.

First i call  skipToNext or skipToPrevious too fast, then i call skipToPrevious  but it doesn't change the music , it seek to 0 prgress. and sometimes skipToNext  also not working , it seem like exoplayer accept wrong action.

When i change the music position too fast ,it will buffering too long and skipToNext or skipToPrevious  will working error , but i don't see any error log, it just doesn't has any response

**Comment by marcbaechinger** [comment]
Difficult to tell from your description alone. I assume you are using `MediaControllerCompat.TransportControll` to send your commands.

If you want to help me to look into this then I need some more information. The best thing would be the following:

1) Add `EventLogger` to the player with `player.setEventListener` (see [DevGuide](https://exoplayer.dev/listening-to-player-events.html#using-eventlogger)). This will help to see what ExoPlayer is doing and how it is behaving.
2) Add some logs at the moment when you call skipToNext/skipToPrevious. This will help to evaluate what you mean with 'too fast'.
3) Ideally if you can edit the source code of the library, add some logging in `MediaSessionConnector.ComponentListener.onSkipToNext`/`MediaSessionConnector.ComponentListener.onSkipToPrevious` so we can see whether the command you are sending in 2) actually arrive at the player.
4) Get the logs from when you are doing the scenario you describe above and upload it here.

Adding this information makes the issue actionable for us.

**Comment by Colaman0** [comment]
Thanks for you reply.

1. If i change music position too fast ,such as click the seekbar too fast, it will buffer long time .  i don't know how to fix it.

2. I have been resolve the skip problem,  when i use DefaultControlDispatcher in exoplayer, it will check the position when i call  skipPre/Nextfunction. So i override function and call seekTo(0) before skipPre/Next function.

**Comment by marcbaechinger** [comment]
Thanks!

Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md). If you're unable to share bug reports or test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #9351", where "#9351" should be replaced with your issue number. Please also update this issue to indicate you’ve done this.

Please read [my comment from above](https://github.com/google/ExoPlayer/issues/9351#issuecomment-909277864) also.
