### ISSUE TITLE
Black Screen Appear when press home button and then come back  also in pip mode.

### ISSUE THREAD

**Issue by waqasyousafy** [google/ExoPlayer#9354]
I press home button and then brows the app at front getting black screen on some of specific videos . Also when going to picture in picture mode or floating window mode also black screen for infite time . 
please help me I haved wasted alot of time with stackoverflow and other solutions.

also i have attached a recorded video of issue with discription 

https://user-images.githubusercontent.com/22340353/131290969-970471c5-0db9-4378-be75-625003d77e63.mp4

**Comment by kim-vde** [comment]
I am afraid I don't have sufficient information to help. It all depends on how you implemented your app. Is there an easy way to reproduce?

Can you also explain why you think this issue is ExoPlayer specific?

**Comment by waqasyousafy** [comment]
Thank you for reply @kim-vde . I also have used it in another project's  activity . With same video sample when we press home button and then come back it shows black screen . If you think  that sample video can help you , I am sharing it with you now . this happens in just in lollipop version devices. I have tested in oppoA37f . 


https://user-images.githubusercontent.com/22340353/131622821-587ab18a-a363-4c10-a0d7-a2b647db897d.mp4





reproduction steps 
1-play video
2-press home button 
3-brows app form recents or from home (i want to say brows app to front)
4-repeat it for 3 to 4 times black screen will appear .
Also sending you the reproduction video
  

https://user-images.githubusercontent.com/22340353/131622712-9a9b2c71-7356-4b9a-8aa8-b37e6db8a930.mp4


I am sending you other project video also


https://user-images.githubusercontent.com/22340353/131622974-e61dd441-b501-402b-9ce5-dcf6ba482028.mp4
