### ISSUE TITLE
Unable to find old versions

### ISSUE THREAD

**Issue by olgunkaya** [google/ExoPlayer#9362]
Hi,

I am trying to maintain a react-native project which has exoplayer dependency of 2.11.4 I tried some repositories in my build.gradle file but could not make it to find the required version. 

in maven central there are only versions of 2.13.x, 2.14.x and 2.15.x. I tried jcenter ( https://dl.bintray.com/google/exoplayer/ )but it is also forbidden. How can I find this required version for my app ?

**Comment by andrewlewis** [comment]
Jcenter is being sunset but the last update said they'd continue serving packages (read-only): https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/ So I think this should be working using Jcenter.

I wonder if this is a temporary outage as all the `dl.bintray.com` artifact links I've been able to find are returning 'Forbidden!'. We have an internal tracking bug to republish versions before 2.13.3 to Google Maven [internal: b/185882704] but so far we haven't prioritized it (mainly because jcenter continued to work in read-only mode).

**Comment by olgunkaya** [comment]
> Jcenter is being sunset but the last update said they'd continue serving packages (read-only): https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/ So I think this should be working using Jcenter.
> 
> I wonder if this is a temporary outage as all the `dl.bintray.com` artifact links I've been able to find are returning 'Forbidden!'. We have an internal tracking bug to republish versions before 2.13.3 to Google Maven [internal: b/185882704] but so far we haven't prioritized it (mainly because jcenter continued to work in read-only mode).

Thanks Andrew. Unfortunately I am having the same response "Forbidden!" for me too. Obviously the readonly story by jcenter is seen just on paper. It would be great to have older releases, but can not determine your priorities. Just praying for the earliest to happen :)

**Comment by ag2s20150909** [comment]
Use aliyun's mirror maven

maven {
      url 'https://maven.aliyun.com/repository/jcenter/'
    }

**Comment by andrewlewis** [comment]
We generally don't recommend using alternative repositories so I am going to hide the previous message (and this one).

**Comment by andrewlewis** [comment]
I just tried depending on 2.11.4 and it worked fine. The AAR was downloaded from `https://jcenter.bintray.com/com/google/android/exoplayer/exoplayer/2.11.4/exoplayer-2.11.4.aar`. How did you produce the URL from the original post?

**Comment by olgunkaya** [comment]
I tried the same way you did. I also tried with explanation given here https://mvnrepository.com/artifact/com.google.android.exoplayer/exoplayer/2.11.4

> Note: this artifact is located at Exoplayer repository (https://dl.bintray.com/google/exoplayer/)

I can say I tried almost everything. 

ftw, just now I got it working too.
