### ISSUE TITLE
M3u8 live streaming error: PlaylistStuckException

### ISSUE THREAD

**Issue by gemiren** [google/ExoPlayer#9364]
I was trying to play a m3u8 URL (https://stream.ginnet.cloud/live0130lo-yfyo/_definst_/fm/playlist.m3u8) but not able to play for more than 30 seconds. It throws the following error:
```
ExoPlayer error caught.
    com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.source.hls.playlist.HlsPlaylistTracker$PlaylistStuckException
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:394)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.source.hls.playlist.HlsPlaylistTracker$PlaylistStuckException
        at com.google.android.exoplayer2.source.hls.playlist.DefaultHlsPlaylistTracker$MediaPlaylistBundle.processLoadedPlaylist(DefaultHlsPlaylistTracker.java:640)
        at com.google.android.exoplayer2.source.hls.playlist.DefaultHlsPlaylistTracker$MediaPlaylistBundle.onLoadCompleted(DefaultHlsPlaylistTracker.java:521)
        at com.google.android.exoplayer2.source.hls.playlist.DefaultHlsPlaylistTracker$MediaPlaylistBundle.onLoadCompleted(DefaultHlsPlaylistTracker.java:445)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.handleMessage(Loader.java:487)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
```

**Comment by marcbaechinger** [comment]
This error is thrown if the player requested the media playlist several times and the server responded with the same playlist for [`3.5 x targetDuration`](https://github.com/google/ExoPlayer/blob/r2.13.0/library/hls/src/main/java/com/google/android/exoplayer2/source/hls/playlist/DefaultHlsPlaylistTracker.java#L714). The target duration of your stream is 11 seconds, so this means that the server returned the same playlist for more than 30 seconds. After this, the player gave up and threw the exception.

I'm listening to this stream in the demo app for quite some time now without any problems. ALso when I download the media playlist with curl it updates nicely.

Can you still repro this and how often did you see this happen?

**Comment by gemiren** [comment]
Thanks very much for looking into the issue. It happens to me all the time. I'm using Exoplayer version 2.11.8.

**Comment by gemiren** [comment]
Tried with the latest 2.15.0 version. It still always stops at 29 seconds.

**Comment by marcbaechinger** [comment]
If your playlist has 3 segments each with a duration of 11 seconds and you say it stops after 29 seconds than the player gets probably the same playlist for each request. 

Are you sure these requests from the player arrive at the server? 

Can you check whether you have caching enabled which makes the `CacheDataSource` return the same playlist each time? If that's not the case can you try a different network (mobile/wifi) and make sure there is no proxy in between that would have caching functionality?

**Comment by gemiren** [comment]
You nailed it! I do have cache enabled. The m3u8 playlist continues to play once I turn off the caching. 

Now, the question is how can I make the m3u8 playlist continue to play but still enable the caching? Is that possible?

**Comment by marcbaechinger** [comment]
That's a good question indeed, but I don't have a really good answer.

Basically I wonder what you want to achieve with caching with a live stream. 

The only thing that comes to mind is that you want to cache the media segments so in case the user seeks backwards the segments can be read from the cache. I doubt a bit that this is worth the effort for live streams, but it's not on me to judge this. If that's the case then you can probably use an `HlsMediaSource` directly and pass your custom `HlsDataSourcefactory` to the constructor of the source. Then you can use the `CacheDataSource` for media only and use a normal data source for the playlist. 

Said this it is obvious that the cached media segments are only requested when they are part of the playlist which is about 33 seconds of eternity. When they move out of the 33 sec live window, the player will never access them again, so it is a bit pointless to cache these. You could create your own playlist and accumulate all the segments that you ever find in a playlist, cache them and list them all in the same playlist. But then you have to do a lot of custom work yourself to for instance make sure the list does not get too big, is in sync with the cache and such things. We can't give you support for such an endavour.

So in general, I would just not cache stuff for live streams?

**Comment by gemiren** [comment]
I'll disable the cache. Thanks very much for your help!

**Comment by ojw28** [comment]
> Now, the question is how can I make the m3u8 playlist continue to play but still enable the caching? Is that possible?

I think the general answer to this would be for us to implement https://github.com/google/ExoPlayer/issues/4188. If the server is doing the right thing, it will probably be setting cache control headers to tell the player that the media playlist should not be cached (at least for as long as the stream is live). Using these would allow the player to "do the right thing", rather than requiring the developer to avoid putting `CacheDataSource` in the `DataSource` chain when playing live streams. I'd suggest following along that issue if you're interested in knowing when we add support for this.
