### ISSUE TITLE
Does IMA SDK depends on Google Play Services?

### ISSUE THREAD

**Issue by ArcherEmiya05** [google/ExoPlayer#9365]
ExoPlayer Core does not depend on Google Play Services, however we would like to know if IMA SDK does?

**Comment by ojw28** [comment]
From [this thread](https://groups.google.com/g/ima-sdk/c/u2cSTqia8kA/m/bWpP3ueSBQAJ):

> To be clear, the SDK requires Google Play Services to be bundled into your app. In fact, if you check our basic sample app (with IMA ExoPlayer integration), you will see play-services being appended as part of the external libraries (attached screenshot). [...] **However, if the Play Services or Play Store isn’t available on the device, as mentioned by my colleague earlier, the IMA SDK is compatible for devices with or without the Play Service, and should have no issues regarding the said dependencies.**

**Comment by ArcherEmiya05** [comment]
> 
> 
> From [this thread](https://groups.google.com/g/ima-sdk/c/u2cSTqia8kA/m/bWpP3ueSBQAJ):
> 
> > To be clear, the SDK requires Google Play Services to be bundled into your app. In fact, if you check our basic sample app (with IMA ExoPlayer integration), you will see play-services being appended as part of the external libraries (attached screenshot). [...] **However, if the Play Services or Play Store isn’t available on the device, as mentioned by my colleague earlier, the IMA SDK is compatible for devices with or without the Play Service, and should have no issues regarding the said dependencies.**

Then it is **optional/recommended** but **not required**, thanks you just give me the link of my old question 😄 which I can no longer find thus I ask it here again.
