### ISSUE TITLE
Make choice of BaseURL deterministic for downloaded DASH content

### ISSUE THREAD

**Issue by marcbaechinger** [google/ExoPlayer#9370]
When a DASH manifest has multiple base URLs that are load-balanced, the player randomly selects a base URL from a set of alternatives. When downloading a stream with such a manifest the `DashDownloader` always just chooses the first base URL from the list of available base URLs without a random selection. 

However, when the same DASH manifest is being played with the player, the base URL is randomly selected again producing cache misses.

To allow such manifests to be downloaded and played the choice of base URLs needs to be deterministic at download and playback time.

**Comment by ojw28** [comment]
As discussed, an alternative (and more flexible) solution would be to ensure that regardless of which BaseURL is selected, the cache key(s) always end up being the same.

This approach would generalize to caching for regular playbacks (i.e., if a different BaseURL is selected when the user plays a stream that has been played before, we still want to use the cached segments where possible), and and any future support for correct use of multiple BaseURLs for download use cases.
