### ISSUE TITLE
Player Seekbar Time vs Video Time

### ISSUE THREAD

**Issue by androaddict** [google/ExoPlayer#9371]
I have a simple Application with Exoplayer, Its a loaded with Live Streaming. My URL is https://cph-p2p-msl.akamaized.net/hls/live/2000341/test/master.m3u8

If I run the above URL in my player means, **Seekbar** never move up 2:00 Mints. So in this case I try to get **currentPosition** of the player it always same ways. Because it loaded again and again in between 2:00 mints.

so, If I want to get the current position of the player means it always wrong values. So If it is possible to get accurate time of the player**(like iOS AVPlayer)**

I attached the screenshot please explain about what is **Marked1 and Marked2 points.**

My guess is 2:00 is **segment** size. If its right means I don't want to show the segment time in seekbar, I want to show the **Mark1** time in my seekar. How to do that? And also how to get Mark1 time from player??

![131656608-7b3c6626-73c7-43af-8e82-9587ebb6242c](https://user-images.githubusercontent.com/56875650/131657813-22ae6a15-7a87-430e-af51-58c8a0d9bd40.png)

**What other information do I need to provide ?**

**Comment by marcbaechinger** [comment]
I'm not sure what time is displayed in Mark1. I assume it's a wall clock time of the current position in a unusual format. So 11 would be the hour of the day of 11:16am. 

I think the `Timeline.Window` has some properties than can help you calculating what you need:
```
long startOfWindowInUnixTime = window.windowStartTimeMs;
long endOfTheWindowInUnixTime = window.windowStartTimeMs + window.getDurationMs();
long currentPositionInUnixTime = window.windowStartTimeMs + player.getContentPosition();
```

You can find more details in the [JavaDoc](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/Timeline.Window.html).

LMK if that helps.
