### ISSUE TITLE
Provide application with more control over which decoders are instantiated

### ISSUE THREAD

**Issue by dnutcracker** [google/ExoPlayer#938]
Increase the visibility of DecoderInfo constructor from package to public.
This will allow easily changing the video decoder by simply extending MediaCodecVideoTrackRenderer and overriding getDecoderInfo().

   
For example - replacing the H264 decoder:

    @Override
    protected DecoderInfo getDecoderInfo(String mimeType, boolean requiresSecureDecoder) throws     MediaCodecUtil.DecoderQueryException {
    if (mimeType.equals(MimeTypes.VIDEO_H264)) {
            // Original DecodeInfo visibility was changed from package to public to allow us to return our own.
            return new DecoderInfo(A_MUCH_BETTER_H264_DECODER_NAME, false);
        } else {
            return super.getDecoderInfo(mimeType, requiresSecureDecoder);
        }
    }

**Comment by ojw28** [comment]
Extension isn't the best way to achieve this, but we have some related work that will allow injection of a decoder factory into the renderer. This will provide the flexibility you desire.

**Comment by dnutcracker** [comment]
Great.
Currently that's the cleanest way I've found - but looking forward for the
new solution.
