### ISSUE TITLE
Question about dynamically editing HLS streams

### ISSUE THREAD

**Issue by DipLimbani** [google/ExoPlayer#9382]
How to changing m3u8 file dynamically during runtime means is it possible to edit .m3u8 file  runtime in exoplayer The scenario is as follows: lets say i have multiple .ts files ready to play in a sequence, for example 1.ts , 2.ts , 3.ts etc...  Now during run time, i want to change the order to 1.ts , 3.ts and only then 2.ts

**Comment by ojw28** [comment]
At the point where you're wanting to dynamically edit the order of a sequence of files for playback, you should probably not be using HLS. You could instead add the individual TS files to the player directly, using ExoPlayer's [playlist support](https://exoplayer.dev/playlists.html). You could then use `moveMediaItem` to perform reordering.
