### ISSUE TITLE
how to play video  exoplayer like youtube. 

### ISSUE THREAD

**Issue by Programmingtimes** [google/ExoPlayer#9383]
I have created an app called movie app, here i use exoplayer to play movies. when i click the play button it directly plays in the landscape but i would like it to play both in landscape and portrait-like youtube. wherein landscape we will see the only video in full screen when the user turns to portrait user can see details like movie description , similar movies  including video play in portait player

**Comment by ag2s20150909** [comment]
playerView.setControllerOnFullScreenModeChangedListener(this::requestFull);

https://github.com/google/ExoPlayer/blob/02f7aafe67b4893134a31ea55a3ba0f0535df145/library/ui/src/main/java/com/google/android/exoplayer2/ui/StyledPlayerView.java#L943

**Comment by Programmingtimes** [comment]
is this directly code or I am suppose to declare anything in video player activity ?

**Comment by kim-vde** [comment]
If my understanding of the question is correct, this is a general Android question and not an ExoPlayer question. You should read [this page](https://developer.android.com/training/multiscreen/screensizes#alternative-layouts).

If this is ExoPlayer specific, please provide more details and explain why you think it is ExoPlayer specific.

**Comment by Programmingtimes** [comment]
Thanks for the reply. yeah, I think your asking this because of my recent question ? 

> is this directly code or I am suppose to declare anything in video player activity ?

**Comment by Programmingtimes** [comment]
if not. I can explain why this is exoplayer related because, if user rotate screen the exoplayer have to convert to portait mode like youtube android app. as per my guess i dont think thats on android side it must be on exoplayer side. there must be some function to control the screen rotation 
exoplayer in portait in youtube 
https://cdn.vox-cdn.com/thumbor/A1x0joPH-IL6rs0oiIi95WBC4iA=/1400x1050/filters:format(png)/cdn.vox-cdn.com/uploads/chorus_asset/file/21989580/Untitled.png
exoplayer in full screen in mobile youtube
https://www.gizbot.com/img/2018/09/how-enable-full-screen-video-playback-youtube-on-the-vivo-v11-pro2-1537442685.jpg

**Comment by kim-vde** [comment]
I still think it is Android related. You want a different layout when the user rotates their phone to landscape mode, right? You can do that by following the page I linked above, and then link the ExoPlayer player to the PlayerView/SurfaceView/something else that you will have added to your layouts.
