### ISSUE TITLE
How to play set of videos after pressing next 

### ISSUE THREAD

**Issue by Programmingtimes** [google/ExoPlayer#9384]
i would like  to play set of video like episode and it should play automatically after ep 1 get over is it possible

**Comment by marcbaechinger** [comment]
Sounds like the playlist API is what you want to read about in the DevGuide: https://exoplayer.dev/playlists.html

**Comment by Programmingtimes** [comment]
thanks for the reply. yeah, I have read that. I am new to this android dev. my videos source are also coming from api 
https://raw.githubusercontent.com/windowschares/charles/main/1/all_movies.json
json file but they are seperated I dont know how to add them in cluter

**Comment by marcbaechinger** [comment]
You just parse the JSON file and then for each JSON object you create a `MediaItem`:

(untested code to demostrate the approach)

```
JsonArray movies = parseJson(...);
List<MediaItem> mediaItems = new ArrayList();
for (int i = 0; i < movies.size(); i++) {
   mediaItems.add(MediaItem.fromUri(movies.getJsonObject(i).getString("fileUri")));
}
player.setMediaItems(mediaItems);
player.prepare();
player.play();
```

**Comment by Programmingtimes** [comment]
```
protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_video_player);
        videoPlayer = findViewById(R.id.exo_player);
        setUpExoplayer(getIntent().getStringExtra("url"));
        getWindow().setFlags(WindowManager.LayoutParams.FLAG_SECURE, WindowManager.LayoutParams.FLAG_SECURE);
    }
    private void setUpExoplayer(String url)
    {
        simpleExoPlayer = ExoPlayerFactory.newSimpleInstance(this);
        videoPlayer.setPlayer(simpleExoPlayer);
        DataSource.Factory dataSourceFactory= new DefaultDataSourceFactory(this, Util.getUserAgent(this,"ChristianGospelApp"));
        MediaSource mediaSource = new ExtractorMediaSource.Factory(dataSourceFactory).createMediaSource(Uri.parse(url));
        simpleExoPlayer.prepare(mediaSource);
        simpleExoPlayer.setPlayWhenReady(true);
    }
```
this is the code I have in my video player activity where "URL" get the file from JSON

**Comment by marcbaechinger** [comment]
Yes, instead use 

```
player.setMediaItems(mediaItems);
player.prepare();
player.play();
```

I think the answer to the question how to play multiple media items in a playlist is answered with the snippet above and the link to the Playlist page in the DevGuide.

I can not give you 1:1 support for developing your app I'm afraid.  I leave this issue open for a while so other can answer your questions.

**Comment by Programmingtimes** [comment]
Thank you for answering my query very patiently. no, I dont want one and one support to develop entire app. unfortuantly i have not found the exact direction for how they do have make single exoplayer to play multiple video . and I do my best in try and fix . thankyou for support  marcbaechinger. will workaround with the code and idea that you gave
