### ISSUE TITLE
How to make exoplayer resume to exact position after player released

### ISSUE THREAD

**Issue by Programmingtimes** [google/ExoPlayer#9387]
I have successfully finished my app. I would like to add continue watching feature. where if a person watching a movie and stopped it at 50:00 Minutes and after some time if they start the app they could able to resume from that position . is it possible to implement that feature using exoplayer. I know we need to store session but  I have not implement login feature so is it possible to store the current player position after player released

**Comment by ojw28** [comment]
It should be as simple as querying the player's playback position when playback stops, storing it somewhere, and seeking some new instance of the player to that position when playback is resumed.

How to store a piece of application state sounds like a general Android development question. [This page seems like a good starting point to learn about this](https://developer.android.com/guide/topics/data).
