### ISSUE TITLE
Unable to get RTSP audio stream for PCMA

### ISSUE THREAD

**Issue by SreeniMannem** [google/ExoPlayer#9393]
Hi Team, i am using ExoPlayer 2.15.0 version to stream RTSP using ip camera. My Ip camera is having below configurations

Video: **a=rtpmap:96 H264/90000**
Audio: **a=rtpmap:8 PCMA/8000/1**

I am able to get Video but Audio is missing from the output stream. This is a known issue it seems, from @claincly comment for one of my question. [Reference](https://github.com/google/ExoPlayer/issues/9346#issuecomment-910390708) 

I have gone through ExoPlayer docs, mentioned like [here](https://exoplayer.dev/troubleshooting.html#how-can-i-get-a-decoding-extension-to-load-and-be-used-for-playback) by adding _Ffmpeg extension_ we can achieve this.

Now my question is, shall we play audio by adding _Ffmpeg Extension_ with the existing ExoPlayer v2.15.0?

Thanks in advance!!!

**Comment by claincly** [comment]
In RTSP/RTP, a bitstream is split into UDP-packet sized chunks, and sent through the network in RTP packets. The chunks are usually smaller than 1500 bytes. 

You can only use ffmpeg to render the reconstructed bitstream. In ExoPlayer the `RtpPayloadReaders` demux the incoming RTP packet and reconstructing the bitstream. So what's missing is an `RtpPayloadReader` that handles PCMA RTP packets, using ffmpeg will not help.

The only way around this: implement [RFC3551](https://www.rfc-editor.org/rfc/rfc3551.html) as `RtpPcmaReader`. We don't have it planned at the moment. In the meantime, you may find [this implementation](https://github.com/portizb/ExoPlayer/blob/dev-v2-rtsp/library/rtp/src/main/java/com/google/android/exoplayer2/source/rtp/extractor/RtpG711PayloadReader.java) helpful.

**Comment by SreeniMannem** [comment]
Thanks @claincly for your detailed explanation. For the time being, i will try with the above mentioned implementation.

**Comment by claincly** [comment]
I'm closing this issue for now, please feel free to re-open if you have further questions.
