### ISSUE TITLE
How to stream m3u8 file with exoplayer

### ISSUE THREAD

**Issue by Programmingtimes** [google/ExoPlayer#9394]
Hi,
I have created a video streamingapp. I would like to add live tv to it (its personal app so I will be using it for my personal use only ). 

**https://wowzaprod270-i.akamaihd.net/hls/live/1007388/e7a2aac8/e7a2aac8_1_1872000/chunklist.m3u8**

my rest of video source is coming from an Api powered by retrofit (json file) all the video files are .Mp4 format. 
My doubt is how to implement m3u8 code with exoplayer. 
all other files are mp4 but the streaming format is m3u8 can you guys help me. if possible a small piece of codes will be useful and short note on how to implement that so I can steam both mp4, m3u8 file formats.

background
app is backed by Java and xml 
backend JSON file
using retro fit as client or server 
all the files images videos are coming from recycler view
adapter, models are used for recycler view
`   private void setUpExoplayer(String url)
    {
        simpleExoPlayer = ExoPlayerFactory.newSimpleInstance(this);
        videoPlayer.setPlayer(simpleExoPlayer);
        DataSource.Factory dataSourceFactory= new DefaultDataSourceFactory(this, Util.getUserAgent(this,"ChristianGospelApp"));
        MediaSource mediaSource = new ExtractorMediaSource.Factory(dataSourceFactory).createMediaSource(Uri.parse(url));
        simpleExoPlayer.prepare(mediaSource);
        simpleExoPlayer.setPlayWhenReady(true);

    }`
Current coding is really short and perfectly working but i don't know how to implement another url so they will stream separately without disturbing the current mp4 files
my json file :https://raw.githubusercontent.com/windowschares/charles/main/1/all_movies.json

**Comment by ojw28** [comment]
I'm not sure what version of ExoPlayer you're using, but `ExtractorMediaSource` was deprecated a long time ago, and was entirely removed two major releases ago.

I'd suggest that you should first update to the latest version. In recent versions, playing an HLS stream (which typically has the m3u8 file extension) is normally no different to playing any other file. How to do so is documented in our [developer guide](https://exoplayer.dev/hello-world.html).
