### ISSUE TITLE
Lost control animation but seekbar animation is still enabled

### ISSUE THREAD

**Issue by MathiasOhrstrom** [google/ExoPlayer#9405]
We use `StyledPlayerControlView` that previously had a fade animation that now seems to have been removed but the delay to hide `StyledPlayerControlView` is still there, and the Y-translation on the seekbar is still present (which was not easy to remove #9072). So now the seekbar go behind other views before the whole `StyledPlayerControlView` goes away

We updated from `2.12.3` to `2.15.0`

https://user-images.githubusercontent.com/26031482/132504183-78d072d0-daeb-418f-b107-eb659c49a8e0.mp4

**Comment by ojw28** [comment]
Judging by how it looks, I suspect that you're applying some customizations to your `StyledPlayerControlView`, either in code or in layout xml.

I think whatever you've customized is probably incompatible with some changes that we've made between `2.12.3` and `2.15.0`. If you're overriding one of ExoPlayer's layout files, a good next step would be for you to look at how ExoPlayer's equivalent layout file changed between `2.12.3` and `2.15.0`, and see whether you need to make equivalent changes in your own layout files.

**Comment by ojw28** [comment]
Closing on the assumption this issue was caused by app specific customizations. If you're still stuck, please reply with a small sample project (as source code) that we can use to reproduce the problem, and we will re-open the issue and take a look.
