### ISSUE TITLE
Watermark

### ISSUE THREAD

**Issue by BejanCorneliu** [google/ExoPlayer#9406]
Hello there

Can you please tell me how can i add watermark on current video running in exoplayer?

Thanks

**Comment by andrewlewis** [comment]
Does the watermark just consist of an image? If so it should work just to show it in an image view on top of the player view. If you need more control over composition (for example, showing the watermark only over certain frames) then the [GL demo](https://github.com/google/ExoPlayer/tree/r2.15.0/demos/gl) shows how to composite an image with frames using a GL shader and output to a `GLSurfaceView`.

**Comment by andrewlewis** [comment]
Closing on the assumption that the answer above helped.
