### ISSUE TITLE
IMA Learn More and Skip Ad buttons rendered incorrect

### ISSUE THREAD

**Issue by olgunkaya** [google/ExoPlayer#9410]
hi,

We have our react-native app integrated with react-native-video where it utilize exo player. The Learn More and Skip Ad buttons rendered out of container when device rotated to landscape mode. Same app works fine with emulator. 
Emulator : Pixel 2 API 28 OS Version: Android 9
Real Device : Redmi Note 8 Pro OS Version: Android 11

![WhatsApp Image 2021-09-09 at 12 54 17](https://user-images.githubusercontent.com/1777728/132670368-ccf181bf-b72d-4ecd-a7dc-4ea952aeefcb.jpeg)
![WhatsApp Image 2021-09-09 at 12 54 17 (1)](https://user-images.githubusercontent.com/1777728/132670374-779d9f91-a06c-4f80-be15-b95ed3910423.jpeg)
![WhatsApp Image 2021-09-09 at 12 54 17 (2)](https://user-images.githubusercontent.com/1777728/132670650-75391dd9-45e1-44f3-a429-f57e61c44c78.jpeg)
![WhatsApp Image 2021-09-09 at 12 54 17 (3)](https://user-images.githubusercontent.com/1777728/132670652-4a2b6f10-c609-4496-89c5-c22874d28f51.jpeg)

**Comment by tonihei** [comment]
Sorry for the delay. 

The IMA buttons are rendered in a `WebView` that sits on top of the `PlayerView` with the video playback. It looks as if something with the view setup is not done correctly. Assuming the `View`s are handled by react-native-video, I'd suggest to report a bug to them. ExoPlayer just takes the view as it is and lets IMA render the buttons, so there isn't much we can do about it within the library.

**Comment by olgunkaya** [comment]
thanks a lot. I think it's at a manageable level for us. Issue present only on some kind of devices and we are still working on it to understand what's actually happening. Thanks again!
