### ISSUE TITLE
RTSP session header parser can't parse timeout parameter

### ISSUE THREAD

**Issue by ekindino** [google/ExoPlayer#9416]
The fix for the issue #9254 disregards the timeout parameter that mat be present in session descriptors.

The previous SESSION_HEADER_PATTERN  regex was supposed to parse the ";timeout=X" part at the end which some devices use. The current regex returns the timeout parameter as a part of the session id causing a mismatch on the next request and the timeout parameter is not being parsed at all.

As an example "parseSessionHeader" function with the "headerValue" "45266830;timeout=5" returns "sessionId" as "45266830;timeout=5" and returns the default timeout.  The session id should be "45266830" and the timeout value should be returned as 5.

**Comment by claincly** [comment]
Able to repro, will be fixed soon.
