### ISSUE TITLE
Switch multiple GLSurfaceViews smoothly without flicker

### ISSUE THREAD

**Issue by tdc-w** [google/ExoPlayer#9420]
I'm trying to switch videos using two ExoPlayers and two GLSurfaceViews.
Each GLSurfaceView is linked with ExoPlayer.VideoComponent.setVideoSurface().
FrameLayout is defined in the layout, and two GLSurfaceViews are switched to containerView by addView/removeView in the code.

The problem here is that when addView, a black screen is displayed for a moment and flickers.
AddView is executed when the STATE of ExoPlayer to be displayed next is switched from BUFFERING to READY.
Immediately after that, I'm trying to removeView the GLSurfaceView that was already addView, but even if I specify the index with addView and try to display it on the back, it seems that it is displayed on the front.

My goal is to prepare the video to be displayed on GLSurfaceView2(ExoPlayer2) while GLSurfaceView1(ExoPlayer1) was displayed, and smoothly switch to GLSurfaceView2 when GLSurfaceView2 was ready to play.

https://github.com/google/ExoPlayer/issues/9248#issuecomment-895312677
With reference to this, I tried to removeView at the timing of onRenderedFirstFrame, but it did not improve.

```
private var removePreviousView: (() -> Unit)? = null

// in onPlayerStateChanged() (playbackState is STATE_READY)
containerView.addView(surfaceView2, 0)

removePreviousView = {
    containerView.removeView(surfaceView1)
}

// in onRenderedFirstFrame()
removePreviousView?.invoke()
removePreviousView = null
```

Is there any other way to solve this problem?
I would be grateful if you could give me some advice.

**Comment by Samrobbo** [comment]
@andrewlewis You were the assignee of #9248, do you have any thoughts/suggestions?

**Comment by andrewlewis** [comment]
Do you have both views in the layout at the same time (both added and visible) with one on top of the other? And you hide the one on top after you receive `onRenderedFirstFrame`? I'd be surprised if you see a flash in that case. Do you see the same behavior if you use `SurfaceView` directly instead of `GLSurfaceView`?

**Comment by tdc-w** [comment]
Since surfaceView1 is removed at the timing of onRenderedFirstFrame, I think that both surfaceView1 and surfaceView2 will be added to containerView until onRenderedFirstFrame is called.
However, it is unknown which surfaceView is displayed in the foreground at this time.

![Untitled Diagram drawio](https://user-images.githubusercontent.com/38201241/134622688-e4ec5727-3cf1-41b9-b7f7-808dfbd0201b.png)

I don't know if I can try it on SurfaceView right away.

**Comment by andrewlewis** [comment]
I don't follow why you'd need to remove `surfaceView1` in that picture. If you have view 2 on top of view 1 and you've received `onRenderedFirstFrame` for view 1, I'd expect there not to be a flash when hiding view 2.

**Comment by tdc-w** [comment]
There may be other problems because flicker occurs without removing view.

Another approach is to have one SurfaceView and two SurfaceTextures managed by Renderer.
This issue will be closed as it seems that this approach will achieve the purpose.
