### ISSUE TITLE
H.264 High 10 profile support

### ISSUE THREAD

**Issue by Weevild** [google/ExoPlayer#9424]
### [REQUIRED] Use case description

Hi, so if I didn't somehow miraculously miss an already open request about this I was wondering: Would it be possible to implement support for 10-bit on the x264 codec? An exemplary justification is the wide use of the standard when it comes to medium such as animated shows (anime, cartoons etc.) which still very much favors the codec, and on this codec's quality zenith is the high 10 profile (10-bit).

### Proposed solution

Software implementation if possible, since hardware support for 10-bit nowadays is almost exclusively HEVC.

**Comment by Samrobbo** [comment]
It's likely that ExoPlayer already supports this, as long as the device has a MediaCodec component that supports it. We don't have an extension that bundles a H.264 software decoder currently.

**Comment by Weevild** [comment]
Do you reckon that the Nvidia Shield TV has said component? If so then something might be wrong on my end but it's infamous for supporting almost all and every codecs/formats etc.

**Comment by Samrobbo** [comment]
[The specs listed on the nvidia site](www.nvidia.com/en-gb/shield/specs/) mention support for H.264, but nothing about the 10-bit codec specifically. I would ask on their forums and see what you get back.

**Comment by AnonymousWebHacker** [comment]
@Samrobbo you know about support for H265 HEVC 10 bit?

**Comment by emveepee** [comment]
A user's h264 Hi10p mp4 recordings are failing here https://github.com/androidx/media/blob/release/libraries/extractor/src/main/java/androidx/media3/extractor/AvcConfig.java#L47 Is that the same issue of no h/w support?  If I don't throw an the error it does play with poor video quality.

**Comment by andrewlewis** [comment]
A failure on that line is not related to hardware capabilities -- it means the AVC decoder configuration record is invalid as the NAL unit length needs to be 1, 2 or 4 bytes based on the specification (so the media is broken/invalid, or there's a parsing bug that I think that's less likely).

I'll close this issue as it's been open for a long time and as noted above it should just work on devices where media codec supports these formats, so I think the question has been answered.
