### ISSUE TITLE
DefaultBandwidthMeter$ConnectivityActionReceiver time consuming

### ISSUE THREAD

**Issue by lizuojing** [google/ExoPlayer#9427]
hi:
      action&ReceiveClass :
android.net.conn.CONNECTIVITY_CHANGE&com.google.android.exoplayer2.upstream.DefaultBandwidthMeter$ConnectivityActionReceiver.
     
exoplayer verison infomation:
    implementation "com.google.android.exoplayer:exoplayer-core:2.12.2"
    implementation "com.google.android.exoplayer:exoplayer-ui:2.12.2"
    implementation "com.google.android.exoplayer:exoplayer-hls:2.12.2"

**Comment by Samrobbo** [comment]
Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md). If you're unable to share bug reports or test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Please also update this issue to indicate you’ve done this.
