### ISSUE TITLE
Mime Type for DTS:X streams should be "vnd.dts.uhd;profile=p2"

### ISSUE THREAD

**Issue by cedricxperi** [google/ExoPlayer#9429]
As mentioned in one of the comments in the following pull requests, https://github.com/google/ExoPlayer/pull/9162, the correct mimetype for streams with "dtsx" should be "vnd.dts.uhd;profile=p2" instead of "vnd.dts.uhd". This is defined in https://www.iana.org/assignments/media-types/audio/vnd.dts.uhd

**Comment by icbaker** [comment]
Assigning to @kim-vde as the reviewer of #9163 where this MIME type was added to `MimeTypes.java` (merged in https://github.com/google/ExoPlayer/commit/8e29e76b517157decf3a5993cbc32ffc759173ca).

CC @ProtoScott as the author of #9163 and #9162 and @krocard who pointed out the `profile=p2` thing in #9162.

**Comment by christosts** [comment]
The fix will be included in the upcoming 2.15.1 release.

**Comment by cedricxperi** [comment]
Thanks to all. Looking forward to this fix.
