### ISSUE TITLE
Change ATTRIBUTE_PATTERN in SessionDescriptionParser

### ISSUE THREAD

**Issue by nibblis** [google/ExoPlayer#9430]
Can you change [SessionDescriptionParser](https://github.com/google/ExoPlayer/blob/release-v2/library/rtsp/src/main/java/com/google/android/exoplayer2/source/rtsp/SessionDescriptionParser.java)?

I would like to change:
`ATTRIBUTE_PATTERN = Pattern.compile("([0-9A-Za-z-]+)(?::(.*))?");`
to
`ATTRIBUTE_PATTERN = Pattern.compile("([0-9A-Za-z-_]+)(?::(.*))?");`
add `_`

The problem is that my camera's response contains the line `a=Media_header:MEDIAINFO=494D4B48010100000400010000000000000000000000000000000000000000000000000000000000;` and an exception is thrown:

> Caused by: com.google.android.exoplayer2.ParserException: Malformed Attribute line: a=Media_header:MEDIAINFO=494D4B48010100000400010000000000000000000000000000000000000000000000000000000000;
>         at com.google.android.exoplayer2.source.rtsp.SessionDescriptionParser.parse(SessionDescriptionParser.java:159)
>         at com.google.android.exoplayer2.source.rtsp.RtspClient$MessageListener.handleRtspMessage(RtspClient.java:476)

**Comment by claincly** [comment]
Support for special characters is added in RFC4566, while we implemented RFC2327. 

There will be a patch soon.
