### ISSUE TITLE
How to deploy locally modified library to JitPack

### ISSUE THREAD

**Issue by marcqtan** [google/ExoPlayer#9434]
Hello, I've fork this library and modified it in my local. I've follow the instructions from https://github.com/google/ExoPlayer/blob/release-v2/README.md **(LOCALLY PART)**
and it's working fine. 

Since it is working fine, I've now pushed it to my dev branch so it will be available in jitpack. 

After pushing, I've added the dependency using 
`implementation 'com.github.marcqtan:ExoPlayer:exoplayer-ui:dev-SNAPSHOT'`

but it's not working. 
it's showing error below:
` Could not resolve com.github.marcqtan:ExoPlayer:exoplayer-ui.`

Any idea how to make it work ?

Thanks!

**Comment by Samrobbo** [comment]
This sounds like a `JitPack' issue, and not at all related to the development or use of ExoPlayer as a library. 

I recommend you ask this question on StackOverflow, or potentially on a `JitPack` based help forum.
