### ISSUE TITLE
How change the code in demo app to read json file from external server instead of Assets folder?

### ISSUE THREAD

**Issue by NimaTajfar** [google/ExoPlayer#9437]
Hi,
I use demo app within Exoplayer version 2.15.0 (latest release). Loading an external exolist.json file with deep links is not work with Google TV SDK 31 (at least with Emulator and but when i do same process and switch to Android TV SDK 28 it works please note local assets folder works in both versions (even Google TV SDK 31) . if i need to do make any other changes in Android.Manifest file in order to support Google TV SDK 31 loading an external please let me know ( using adb please let me know)

Step of produce:

very simple run the demo on Google TV SDK 31 emulator
adb shell am start -a android.intent.action.VIEW 
-d your.domain/exolist.json
Result : it DOESNT load and there is a toast (message) ""you don't have an app that can do this"

run the demo on Android TV SDK 28 emulator
adb shell am start -a android.intent.action.VIEW 
-d your.domain/exolist.json
Result : it loads
Thanks

**Comment by ojw28** [comment]
Passing a URI to a `exolist.json` file when starting the demo app, [as documented here](https://exoplayer.dev/demo-application.html#2-loading-an-external-exolistjson-file), should just work. If you want to edit the code to do this directly, you'll need to edit `SampleChooserActivity.onCreate`. The `uris` variable in that method is the list of URIs that get loaded.

Server certificates and DNS issues sound unrelated to ExoPlayer and outside the scope of this issue tracker.

**Comment by NimaTajfar** [comment]
@ojw28 Thanks for respond, i started emulator (Android TV SDK 31) but when i run adb command i get this error:                                                                               ```
Starting: Intent { act=com.android.action.VIEW dat=mydomai. }
Error: Activity not started, unable to resolve Intent { act=com.android.action.VIEW dat=mydomain.. flg=0x10000000 }
```
 what is starting path should i run this command : adb shell am start -a com.android.action.VIEW \
    -d https://yourdomain.com/samples.exolist.json

**Comment by ojw28** [comment]
Perhaps you figured it out, but I think there's actually a mistake in the document I linked to. It should be using `android.intent.action.VIEW` rather than `com.android.action.VIEW`. I'll get that updated.

**Comment by ojw28** [comment]
From https://github.com/google/ExoPlayer/issues/9441, it's stated that the intent does not work on the Google TV SDK 31 emulator. We will take a look.

**Comment by ojw28** [comment]
Please could you provide some more precise reproduction steps for the Google TV issue? I don't see any TV emulator images for SDK 31, so I'm a little on how to reproduce what you're doing. Thanks!

**Comment by NimaTajfar** [comment]
@ojw28 

1. just upate your Android studio to the latest stable version or which is Install Android Studio Arctfic Fox 2020.3.1 patch 2
2. from sdk manager , install Android 12.0 (S) Google TV X86 image
3. run the demo app on Google TV SDK 31 emulator
4. execute this command adb shell am start -a android.intent.action.VIEW 
-d your.domain/exolist.json
Result : it DOESNT load and there is a toast (message) ""you don't have an app that can do this"

but if you do same steps and instead of running on Google TV emulator SDK do it on Android TV SDK 28 deep link works fine and can run externaly json file from server.
Thanks!

**Comment by NimaTajfar** [comment]
@ojw28 I read document and google that but didnt find anything about this question also as another related question (different subject)  about loading external server , i am curious to know after executing this command:
```
 adb shell am start -a android.intent.action.VIEW
-d your.domain/exolist.json
```
after above command  if i exit the app or power off android devices then the list disapear which is not appropriate and intended. i mean if i want to permanently run external server with ExoPlayer is there any other adb command or any other workaround which i can executed in order to store and save the list of streams? 
Thanks,

**Comment by ojw28** [comment]
It would be helpful to know the exact `adb shell` command you're running (including the actual URI that you're using). I have not been able to reproduce the problem so far.

> after above command if i exit the app or power off android devices then the list disappear which is not appropriate and intended. i mean if i want to permanently run external server with ExoPlayer is there any other adb command or any other workaround which i can executed in order to store and save the list of streams?

The demo app is intended to be just that; a relatively simple demonstration app that both the library developers and application developers can use for testing purposes and to get some idea of ExoPlayer's capabilities. It's not intended to solve your exact production use case. You need to write your own app for that.
