### ISSUE TITLE
How can I play video from local files in ExoPlayer i android ??

### ISSUE THREAD

**Issue by tanishq14developer** [google/ExoPlayer#9439]
Please help...please provide me sample code and i have implemented stackoverflow answers it doesn't work

**Comment by tanishq14developer** [comment]
please help

**Comment by icbaker** [comment]
These instructions walk through playing a video: https://exoplayer.dev/hello-world.html

For `videoUri` you can use something like `file:///path/to/your/file` to play a local file.

You may also need to handle requesting permission to local files on the device: https://developer.android.com/training/data-storage

Our demo app supports playback of local files so you can look at that for more sample code: https://exoplayer.dev/demo-application.html
