### ISSUE TITLE
Misconfigured NDK Build for Opus

### ISSUE THREAD

**Issue by Brahmasmi** [google/ExoPlayer#944]
Building opus currently outputs a warning:

```Android NDK: WARNING: APP_PLATFORM android-21 is larger than android:minSdkVersion 9 in ExoPlayer/extensions/opus/src/main/AndroidManifest.xml```

Further investigation suggests that the APP_PLATFORM has been defined in the Android.mk file and not the Application.mk file in the ExoPlayer/extensions/opus/src/main/jni directory. Also it is set to "android-10".

We may want to move APP_PLATFORM from Android.mk to Application.mk and change it from "android-10" to "android-9".

**Comment by ojw28** [comment]
@vigneshvg - Could you comment on this? Thanks!

**Comment by vigneshvg** [comment]
yeah this change should be fine. i'll fix it sometime shortly.
