### ISSUE TITLE
Regarding the issue of playback freeze, please help.

### ISSUE THREAD

**Issue by niuyaweiqq** [google/ExoPlayer#9440]
May I ask if there is a method that can help the playback freeze, the network factor is definitely the main problem, but I want to know whether setting something can be helpful to solve the freeze, if so, I hope you can give me a hint, thank you again .

**Comment by icbaker** [comment]
Hi! Please provide complete information as requested in the question template. The template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/question.md).

Unfortunately we can't answer unclear questions or those with insufficient information.
