### ISSUE TITLE
How to optimize / handle large playlist and single thread Exoplayer approach

### ISSUE THREAD

**Issue by Tolriq** [google/ExoPlayer#9443]
I'm trying to optimize playback start when dealing with large playlists to avoid the delay of filling the playlist.

The basic solution to play 200 items starting at position 2 is:
Add the first 2 items.
Start playing the 2nd item.
Add the next items.

Unfortunately this is not as simple as that due the single threaded / messaging approach of Exoplayer.
The start playing is not instant as it might do background stuff to initialize codecs before retuning to the default thread.
But at that point the default thread is now handling the queuing of the future items and Exoplayer does not start playing until this operation is finished.

A simple solution is to add a delay before continuing to queue but its value is "unknown" due to codec initialisation time.
Adding complex wait on the player state can be very tricky if the items are invalid for example or other issues.

Do you have some insight about how to properly handle this?

**Comment by krocard** [comment]
@marcbaechinger are significant delay expected for large playlist?

@Tolriq as a workaround, add an item to the playlist on each `Player.Listener.onMediaItemTransition` callback. It is called every time the current item has finished playing.

**Comment by Tolriq** [comment]
I need to queue before to be able to have gapless transition and show the playlist to the users + delaying too much means that I need to have some proper mechanism to handle user interaction during the playlist filling like stopping or starting a new queue.

Many uses cases that are problematic to handle properly.

Once the codecs are initialized a very small delay is enough to have the song start and then continue to queue, but first init can take longer and is problematic :(

The delay is probably generated because I'm forced to use addMediaSource and generate the media source because of other previous issues to address some specific needs. For 100 items it's like 2 seconds in my case on pixel 3a

**Comment by krocard** [comment]
You don't have to push the next item to play, this would indeed break gapless playback and ExoPlayer ability to buffer over item transition.

Push the N first items (for example 5) before starting playback. Then on each `Player.Listener.onMediaItemTransition` add an item. That will make sure ExoPlayer always knows the next N items to play.

**Comment by Tolriq** [comment]
@krocard 

And how to you handle user cancelling the queue and starting another one while queuing is occurring? You need to implement a complex queue manager on top of everything.
How do you handle the user that want to reorder the queue if the items are not there yet? Duplicate all the queue handling on your own side?

Please don't close as this is certainly not a solution but a very ugly and limited workaround.

**Comment by krocard** [comment]
Presumably keeping just the next item in the playlist should not be too complex (playlist has the current and next item). Change it if your app's queue first item changes.

**Comment by krocard** [comment]
> delay of filling the playlist

Could you characterize that delay? How long are we talking about <100ms or over that.

Some ideas:
 - Are you using `addMediaItem(MediaItem)` to add each item one by one (lots of RPC) or using `addMediaItems(List<MediaItem>)` to add all MediaItem in one call.
 - Have you tried to use Android Studio's profiler to check what is slowing down the playlist insertion? Maybe the hot spot is in your code.

**Comment by Tolriq** [comment]
> Presumably keeping just the next item in the playlist should not be too complex (playlist has the current and next item). Change it if your app's queue first item changes.

That means handling the whole queue system and reordering, shuffle, repeat and everything on the app side, completely defeating the ExoPlayer playlist stuff.


> Could you characterize that delay? How long are we talking about <100ms or over that. Have you tried to use Android Studio's profiler to check what is slowing down the playlist insertion? Are you using `addMediaItem(MediaItem)` to add each item one by one (lots of RPC) or using `addMediaItems(List<MediaItem>)` to add all MediaItem in one call.

As described in a previous message I'm talking about couple of seconds for 100 items. Profiler is broken for me on AS Bumblebee. I should try systrace by adb if I can't fix that one.

I'm using the single ```addMediaSource``` as I had memory issues before, but I can try to slice the queue in smaller batch yet still greatly reduce the number of calls.

**Comment by krocard** [comment]
I just tried playing a 500 item playlist in the demo app and playback started instantly. It would be very helpful to have a profiling or a way to reproduce.

**Comment by Tolriq** [comment]
I've made a lot of tests and it seems to happen a lot more when using addMediaSources than addMediaItems but that it's in fact not 100% :(
I'll need to do more tests on real devices and release builds to be sure it's a real issue then I'll provide systrace.

**Comment by ojw28** [comment]
Marking `needs more info` pending the systrace being provided.

**Comment by Tolriq** [comment]
After more digging the issue is more about emulator and random codec init issues taking time then falling back to ffmpeg. Release mode on real device have proper performance when adding all the items in large batches.
