### ISSUE TITLE
How to cache dash  in exoplayer

### ISSUE THREAD

**Issue by ducanh3005** [google/ExoPlayer#9445]
i tried caching hls video and it works fine however when using dash video it doesn't work. Can you guide me?

**Comment by krocard** [comment]
> How to cache dash in exoplayer

By caching, do you mean downloading the video to be able to play it offline, or do you mean caching an amount of time around the playback position to allow for faster seeks?

Both are supported by ExoPlayer. The cache duration around playback can be controlled using [`DefaultLoadControl.Builder.setBufferDurationMs`](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/DefaultLoadControl.java#L151). To download media, see [`DownloadService`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/offline/DownloadService.html).

> i tried caching hls video and it works fine however when using dash video it doesn't work. 
Can you please describe what you are expecting and what you are observing. For example paste any errors.
