### ISSUE TITLE
add custom user-agent in exolist json

### ISSUE THREAD

**Issue by Zoom-Adr** [google/ExoPlayer#9448]
how to use custom header user-agent in exolist json?

      {
        "name": "Sample",
        "logo_uri": "http://logourl.com",
        "uri": "streamurl.m3u8"
        "custom_agent": "myuseragent"
      },

**Comment by ojw28** [comment]
This is not supported by the demo app. If you want to change it in code, [you can do so here](https://github.com/google/ExoPlayer/blob/r2.15.0/demos/main/src/main/java/com/google/android/exoplayer2/demo/DemoUtil.java#L64).
