### ISSUE TITLE
How can I detect incoming calls to pause and resume audio?

### ISSUE THREAD

**Issue by AleAmla987** [google/ExoPlayer#9451]
How can I detect incoming calls to pause and resume audio?

**Comment by moneytoo** [comment]
AudioFocus solves that: https://medium.com/google-exoplayer/easy-audio-focus-with-exoplayer-a2dcbbe4640e

**Comment by AleAmla987** [comment]
> AudioFocus solves that: https://medium.com/google-exoplayer/easy-audio-focus-with-exoplayer-a2dcbbe4640e

thank you help me
