### ISSUE TITLE
Will ExoPlayer supports playing RTSP stream in the background

### ISSUE THREAD

**Issue by SreeniMannem** [google/ExoPlayer#9457]
Hi Team,

I am using ExoPlayer 2.15.0 version to stream RTSP using ip camera.

I am able to stream through RTSP to Android app.

When the App pushed to background, it is unable to get stream from IP Camera and hence YouTube not receiving any stream from my app.

Could you please let me know, will it supports streaming while app in the background. If Yes, please help me how to achieve this.

Thank you !!!

**Comment by claincly** [comment]
Please provide more details.

I'm not sure what you are trying to do: 

> When the App pushed to background, it is unable to get stream from IP Camera

Is ExoPlayer not receiving packets from the camera?

> hence YouTube not receiving any stream from my app.

Please specify how you are using ExoPlayer + YouTube, it all seems unclear.
