### ISSUE TITLE
MediaMetaData returns null values if player is set to Player.REPEAT_MODE_ONE

### ISSUE THREAD

**Issue by marcqtan** [google/ExoPlayer#9458]
- ExoPlayer version number: 2.15.0
- Android version: OS 10
- Android device: Samsung a35

I am playing a local mp3 and to get its information,I've override onMediaMetadataChanged to get the title information like below:

```
    override fun onMediaMetadataChanged(mediaMetadata: MediaMetadata) {
        title = mediaMetadata.albumTitle.toString()
    }
```
At first run, It's successfully showing the title of the currently playing item, but when I set the player.repeatmode to REPEAT_MODE_ONE and right after player goes back to 00:01 position, the `onMediaMetadataChanged` gets called again but right now all datas are null including the title. See image below:

<img width="491" alt="Screen Shot 2021-09-21 at 4 01 08 PM" src="https://user-images.githubusercontent.com/66229352/134134303-e23b5a3b-968d-4684-8cfb-a994692508b9.png">

It should retain all the datas from before. Any idea why this is happening?

Thanks!

**Comment by marcqtan** [comment]
It's working fine in v2.14.2..

**Comment by marcqtan** [comment]
Hello any updates on this? Thanks! @marcbaechinger

**Comment by ojw28** [comment]
@Samrobbo - I think the condition [here](https://github.com/google/ExoPlayer/blob/r2.15.0/library/core/src/main/java/com/google/android/exoplayer2/ExoPlayerImpl.java#L1270) probably needs to be:

```
if (mediaItemTransitioned
    || !previousPlaybackInfo.staticMetadata.equals(newPlaybackInfo.staticMetadata)) {
```

else `staticMetadata` doesn't get correctly merged into `newMediaMetadata` in the case that `newMediaMetadata` has been updated by the code block above, but `staticMetadata` is unchanged. It would be good if we could get a fix in for the next minor release. Thanks!
