### ISSUE TITLE
Design problem with seeking to live edge

### ISSUE THREAD

**Issue by pajatopmr** [google/ExoPlayer#946]
The current ExoPlayer strategy for seeking to the live edge is to use a seekTo(0) to mean seek to live edge.  But this will cause a problem with a live event (playlist type == EVENT for HLS) and possibly a live stream with DVR that has a valid playback position value of "0".   I would suggest a seekToLiveEdge() method be used instead, with seekTo(0) being used to go to the beginning of the live stream.  An implementation for HLS is readily available via PR #848.

**Comment by RKNai** [comment]
+1

**Comment by miyaji27** [comment]
+1

**Comment by ojw28** [comment]
ExoPlayer V2 has a `seekToDefaultPosition()`, which will seek to the live edge for live streams. `seekTo(0)` is freed up for legitimate seeks to `t=0`. Note that we still don't support seeking in the live window for HLS (we do for DASH and SmoothStreaming), but this should land sometime fairly soon now for V2.
