### ISSUE TITLE
About resolution selection.

### ISSUE THREAD

**Issue by SuryaChundawat** [google/ExoPlayer#9460]
In case of auto resolution, How to know which resolution is selected . In attached image it shows auto 720p. so here my question is how to get auto is running on 720 p. i take this picture from youtube for better explaining my question.

![image](https://user-images.githubusercontent.com/21680499/134176240-6c563f95-227a-4352-a7ca-209040138de9.png)

**Comment by arunkumartdr** [comment]
hai ,can  you please help me to implement quality selector(java).
Thanks.

**Comment by krocard** [comment]
> How to know which resolution is selected 

Assuming you are using the default track selector, use `player.getCurrentTrackSelection()`. Here is a example:
~~~ kotlin
val currentVideoWidth = player.getCurrentTrackSelection()
    .filter { it.getType() == C.TRACK_TYPE_VIDEO }
    .map { (it as ExoTrackSelection).getSelectedFormat().width }
    .max()
~~~
Having multiple video track group is unlikely though.

Does that answer your question?

**Comment by arunkumartdr** [comment]
Here , i think you are providing a way to get current resolution used by the player.
But,
I would like to implement the quality selector with UI  also.
Ex : youtube

![image](https://user-images.githubusercontent.com/31769796/134496153-67224a35-00b5-4870-8ee8-2c1f6bbe0ada.png)


See this question raised by me here: https://github.com/google/ExoPlayer/issues/9471

**Comment by krocard** [comment]
You can set the prefered width using [’TrackSelectionParamters.setMaxVideoSize’](https://github.com/google/ExoPlayer/blob/r2.15.1/library/common/src/main/java/com/google/android/exoplayer2/trackselection/TrackSelectionParameters.java#L171):
Example:
~~~ kotlin
 player.trackSelectionParameters =
     player.trackSelectionParameters
         .buildUpon()
         .setMaxVideoSize(1080, C.MAX_VALUE)
         .setMinVideoSize(1080, 0)
         .build();
~~~

A more complicated alternative is to set a specific track instead of just the width:
You can force a given bitrate using [`DefaultTrackSelector.SelectionOverride`](https://github.com/google/ExoPlayer/blob/r2.15.1/library/core/src/main/java/com/google/android/exoplayer2/trackselection/DefaultTrackSelector.java#L118):
Example to force the playback at the `trackIndice`'s track of the  `groupIndex`th TrackGroup in the TrackArray:
~~~ java
DefaultTrackSelector defaultTrackSelector = (DefaultTrackSelector)player.getTrackSelector();
SelectionOverride selectionOverride = new SelectionOverride(groupIndex, trackIndice);
trackSelector.setParameters(
     trackSelector
         .buildUponParameters()
         .setSelectionOverride(rendererIndex, rendererTrackGroups, selectionOverride));
~~~

**Comment by krocard** [comment]
Note that you should clear max and min video size on track change in case the next track doesn't have this video width (which would result in nothing playing.) For example if the users selects 1080p but the next video is only available up to 750p, you should clear the constraints or nothing will play.
Does that answer you question?

**Comment by SuryaChundawat** [comment]
Hi I am adding one more question over here. If i am adding normal youtube video than how to put it on auto resolution if it support multiple resolution.

**Comment by arunkumartdr** [comment]
Thankyou @krocard but nothing works.. I think you have not understand my question.

Consider i have a .mpd mpeg dash File that has Multiple video quality ..

What iam asking is how can i give option to my users to change prefered video quality.

like 1080p , 720p , etc............

I think first i have to parse the .mpd file and get qualities available and i have to map the available qualities to the ui.

I came across internet and i get to know that i have to implement a quality selector dialog but i don't know how to do it..

**Comment by SuryaChundawat** [comment]
@arunkumartdr  can you please help to how to create .mpd mpeg dash file with multiple resolution if i have 4k mp4 video.

**Comment by krocard** [comment]
> Can you please help to how to create .mpd mpeg dash file with multiple resolution if i have 4k mp4 video.

@SuryaChundawat Please open a new issue for any off question not directly related to this issue (track selection).

**Comment by krocard** [comment]
> Hi I am adding one more question over here. If i am adding normal youtube video than how to put it on auto resolution if it support multiple resolution.

@SuryaChundawat This is the default, ExoPlayer will pick the best bitrate for your network condition.

Please do not add question to issues, create your own one.

**Comment by krocard** [comment]
> I think first i have to parse the .mpd file and get qualities available and i have to map the available qualities to the ui.

You don't need to parse it yourself, ExoPlayer will do it for you. `player.getCurrentTrackGroups()` will return all tracks of the media, including their format (size, bitrate...) and then force any resolution to be selected as explained in my previous comment https://github.com/google/ExoPlayer/issues/9460#issuecomment-929314540.

You can look at [ExoPlayer's demo app](https://exoplayer.dev/demo-application.html) code that supports a similar feature:

![image](https://user-images.githubusercontent.com/6862950/135257296-d23621d3-654d-4812-ad99-4c70bfc2d112.png)

**Comment by krocard** [comment]
Is this what you are looking for?

**Comment by arunkumartdr** [comment]
Yes thank you, I found this implementation here too : https://www.youtube.com/watch?v=suJHE30rQo8

Thankyou @krocard for your help..
