### ISSUE TITLE
Video won't start programmatically

### ISSUE THREAD

**Issue by AleksaDjordjevic97** [google/ExoPlayer#9461]
Video won't start when calling the start() function programmatically. It wont pause also. I want to apply those functions on my custom button outside the View, without using the MediaController.

**Comment by krocard** [comment]
There are many reason that the "video won't start" when `play()` is called:
 - play was not actually called when your button was pressed
 - prepare was not called
 - the content could not be downloaded
 - the content could not be decoded

It is not possible for us to help you with the information provided. Please take a look at our demo application and our [minimal example](https://exoplayer.dev/hello-world.html) for how to use ExoPlayer.

If you still have an issue and your sure you registered a surface, called `prepare()` and `play()`, please provide us with a minimal reproduction sample. Additionally the media tested and a bug report would be greatly appreciated.

If you're unable to share [bug reports](https://developer.android.com/studio/debug/bug-report) or test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #1234" ("#1234" is replaced with your issue number). Please also update this issue to indicate you've done this.

**Comment by krocard** [comment]
I assumed in my previous answer that you meant `play` when you wrote `start` as ExoPlayer has no `start` method. Could you clarify what `start` method your app is calling.
