### ISSUE TITLE
Enable Audio Offload to Minimize Battery Usage

### ISSUE THREAD

**Issue by ezflutter** [google/ExoPlayer#9464]
I cannot find "DefaultRenderersFactory.setEnableAudioOffload" and "ExoPlayer.experimentalSetOffloadSchedulingEnabled" for more details on how to enable audio offload for exoplayer.

https://exoplayer.dev/battery-consumption.html

- ExoPlayer version number:  2.15.0
- Android version:  11
- Android device:  Samsung A32

**Comment by krocard** [comment]
I'm not sure why you could not find them. Github search bar finds them for me. Here are direct links:
 - [`DefaultRenderersFactory.setEnableAudioOffload`](https://github.com/google/ExoPlayer/blob/r2.15.0/library/core/src/main/java/com/google/android/exoplayer2/DefaultRenderersFactory.java#L240-L257)
 - [`ExoPlayer.experimentalSetOffloadSchedulingEnabled`](https://github.com/google/ExoPlayer/blob/r2.15.0/library/core/src/main/java/com/google/android/exoplayer2/ExoPlayer.java#L1095-L1132)

Note that offload support is still experimental, read the extensive documentation of those methods.

Additionally we have some known bug such as some device don't support gapless playback in offload, and some device+headphone combination have playback failures. We are working on solving those problems.
