### ISSUE TITLE
HLS Adaptive won't change to higher bitrate from audio only

### ISSUE THREAD

**Issue by SnowcatSVK** [google/ExoPlayer#947]
Hello,
i have been trying adaptive HLS with ExoPlayer, we have two Audio only and two video streams in master playlist, player starts with audio only, but even after few minutes it wil not jump to higher bitrate with video,it worked well when there were no audio only streams, connection speed should not be an issue since phone is connected to 100Mbps wifi.
I have tested apple advanced stream and it work very well, it jumps directly to video.
Here is a link to our stream: http://88.212.15.15:5000/live/stvtest_abr/playlist.m3u8
link to stream from apple: https://devimages.apple.com.edgekey.net/streaming/examples/bipbop_16x9/bipbop_16x9_variant.m3u8

our stream work perfectly on iOS and in VLC player.

Thanks in advance for any kind of help

**Comment by Srinidhikandi** [comment]
Hi,
Looks like a similar issue , check this #545

**Comment by ojw28** [comment]
Yes, same as #545.

**Comment by SnowcatSVK** [comment]
Thank you very much for the answers, we have deleted the audio only streams
