### ISSUE TITLE
exo_playback_control_view: Error inflating class ImageButton

### ISSUE THREAD

**Issue by MohitDixit** [google/ExoPlayer#9470]
Hi Team,

I am getting these firebase crashlytics issues in exoplayer version 2.10.5 is this known issue?

I am using   <com.google.android.exoplayer2.ui.PlayerView in my xml file.

P.S. I am working on upgrade on latest version but is it breaking due to latest version changes? As it was pretty stable back then.
Logs:
Fatal Exception: java.lang.RuntimeException
Error inflating class com.google.android.exoplayer2.ui.PlayerView

Caused by android.view.InflateException
Error inflating class com.google.android.exoplayer2.ui.PlayerView

Caused by android.view.InflateException
layout/exo_playback_control_view: Error inflating class ImageButton

Caused by android.content.res.Resources$NotFoundException
Drawable (missing name) with resource ID #0x7f080096

**Comment by krocard** [comment]
I'm am not aware of any resource id missing issue, nor could find any. It's surprising that any resource missing would not be a consistent issue. Are you able to reproduce the issue locally? It might be a problem with your app packaging, rather than with exoplayer.
@ojw28 might know more.

**Comment by ojw28** [comment]
This isn't something we've seen before. Is it possible that it's a problem with the way the app is being distributed, as per [this StackOverflow post](https://stackoverflow.com/questions/52469914/app-sometimes-crashes-with-resourcesnotfoundexception-after-switching-to-androi)?

It's also possible that the problem could be introduced by some customizations that you've done to the ExoPlayer UI components. Have you done any such customizations?

**Comment by MohitDixit** [comment]
@krocard I had tried but these logs only coming from firebase crashlytics. @ojw28 thanks for referring me the possible solution, I think it is possible that this resource not found exception related to app bundle distribution, I will try to handle this exception in my code, will report if happen again. For customization part I haven't done such customization, app using pure exoplayer functions.
