### ISSUE TITLE
h262 support codec tag

### ISSUE THREAD

**Issue by emveepee** [google/ExoPlayer#9472]
Is there a way to modify the codec tag support for h262 files in software without changing the core library?  A user has provided several video samples from the US with CableCard mpeg2video that have  0x80 in the codec_tag.   Exoplayer default does not detect video or flag a warning that video isn't support by the player.  Video will  play  if I hard-code  this in DefaultTsPayloadReaderFactory

```
      case TsExtractor.TS_STREAM_TYPE_H262:
      case 0x80:
        return new PesReader(new H262Reader(buildUserDataReader(esInfo)));
```

Based on this old information https://bugzilla.gnome.org/show_bug.cgi?id=697892#c3  it appears to be a know issue. gstreamer seems to support it https://github.com/GStreamer/gst-plugins-bad/blob/master/gst/mpegtsdemux/gstmpegdefs.h#L50 

It looks like the alternate LPCM definition for 0x80 is not defined in ExoPlayer so while there could be issues there wouldn't be a conflict.

**Comment by kim-vde** [comment]
Hi! Can you please provide an example of media file? If you're unable to share test content publicly, please send them to dev.exoplayer@gmail.com using subject "Issue #9472". Please also update this issue to indicate you've done this.

**Comment by emveepee** [comment]
Ok email sent.

**Comment by kim-vde** [comment]
I have added the change directly to ExoPlayer.

Could you please confirm that it fixes the issue? Thanks.

**Comment by emveepee** [comment]
> 
> 
> I have added the change directly to ExoPlayer.
> 
> Could you please confirm that it fixes the issue? Thanks.

That is is the same (except the define name) as the code I use and it fixes the file in my testing,  The user that reported the issue can play live tv on several channels now that didn't work before so this should fix the issue unless the 0x80 PCM audio is ever in the stream.

**Comment by kim-vde** [comment]
I will close the issue then. Please open another issue if you still encounter problems.
