### ISSUE TITLE
How do I get the currently displayed subtitle content without showing it on the video.

### ISSUE THREAD

**Issue by gfslx999** [google/ExoPlayer#9473]
I have a need,  how do I get the currently displayed subtitle content without showing it on the video.
Would you please help me? Thank you

**Comment by icbaker** [comment]
Add a `Player.Listener` using [`Player#addListener`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/Player.html#addListener(com.google.android.exoplayer2.Player.Listener)) and implement the [`onTextOutput`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/text/TextOutput.html#onCues(java.util.List)) method.

That method will be called every time the cues "on screen" should be updated. It will be called with an empty list to indicate that the cues "on screen" should be removed.

**Comment by icbaker** [comment]
Also [`Player#getCurrentCues()`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/Player.html#getCurrentCues()).
