### ISSUE TITLE
I am playing an audio from a 1 minute url, how can I get an event or verify that it already plays 30 seconds?

### ISSUE THREAD

**Issue by AleAmla987** [google/ExoPlayer#9475]
I am playing an audio from a 1 minute url, how can I get an event or verify that it already plays 30 seconds?

**Comment by krocard** [comment]
Could you please explain what is a 1 minute url and provide us an example. If you are asking how to get the current progress in the media, call `Player.getCurrentPosition()`:
https://github.com/google/ExoPlayer/blob/2a88f0fb295ff5b56e6fbcbe7e91bdf922cbae13/library/common/src/main/java/com/google/android/exoplayer2/Player.java#L2011-L2016

**Comment by icbaker** [comment]
Or register a callback that will be fired when playback reaches a certain point: https://exoplayer.dev/listening-to-player-events.html#firing-events-at-specified-playback-positions

(note that if you register this at 30s this will still fire if your user seeks to 29.5s and then only plays 1s of audio - it's unclear from your question whether that meets your requirements or not)
