### ISSUE TITLE
IndexOutOfBoundException at HlsChunkSource.getNextSegmentHolder

### ISSUE THREAD

**Issue by dino-saurabh** [google/ExoPlayer#9479]
1. We are getting IndexOutOfBoundException at https://github.com/google/ExoPlayer/blob/release-v2/library/hls/src/main/java/com/google/android/exoplayer2/source/hls/HlsChunkSource.java#L470 
2. Possibly due to this `==` check at https://github.com/google/ExoPlayer/blob/release-v2/library/hls/src/main/java/com/google/android/exoplayer2/source/hls/HlsChunkSource.java#L463
3. is this a deliberate `==` check or a bug, will replacing it with >= be of any help?

StackTrace:
-------------------------
```
com.google.common.base.Preconditions.checkElementIndex (Preconditions.java:1402)
com.google.common.base.Preconditions.checkElementIndex (Preconditions.java:1384)
com.google.common.collect.RegularImmutableList.get (RegularImmutableList.java:77)
com.google.android.exoplayer2.source.hls.HlsChunkSource.getNextSegmentHolder (HlsChunkSource.java:480)
com.google.android.exoplayer2.source.hls.HlsChunkSource.getNextChunk (HlsChunkSource.java:399)
com.google.android.exoplayer2.source.hls.HlsSampleStreamWrapper.continueLoading (HlsSampleStreamWrapper.java:708)
com.google.android.exoplayer2.source.CompositeSequenceableLoader.continueLoading (CompositeSequenceableLoader.java:78)
com.google.android.exoplayer2.source.hls.HlsMediaPeriod.continueLoading (HlsMediaPeriod.java:371)
com.google.android.exoplayer2.source.MaskingMediaPeriod.continueLoading (MaskingMediaPeriod.java:226)
com.google.android.exoplayer2.source.MaskingMediaPeriod.continueLoading (MaskingMediaPeriod.java:226)
com.google.android.exoplayer2.MediaPeriodHolder.continueLoading (MediaPeriodHolder.java:221)
com.google.android.exoplayer2.ExoPlayerImplInternal.maybeContinueLoading (ExoPlayerImplInternal.java:2222)
com.google.android.exoplayer2.ExoPlayerImplInternal.handleContinueLoadingRequested (ExoPlayerImplInternal.java:2185)
com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage (ExoPlayerImplInternal.java:500)
android.os.Handler.dispatchMessage (Handler.java:103)
android.os.Looper.loop (Looper.java:237)
android.os.HandlerThread.run (HandlerThread.java:67)
```

Specifications
---------------------------
Exo player version 2.14.1

Reproduction
-------------------------

The Issue was reproducible on a live-stream, we can share the test-stream if required, it would need some work on our side. please let me know if its required.

**Comment by dino-saurabh** [comment]
^^ @nmtiwari-hs @vinodkputta

**Comment by vinodkputta** [comment]
@icbaker @ojw28 Can someone look into this issue? We are facing this issue on live streams.

**Comment by marcbaechinger** [comment]
> is this a deliberate == check or a bug, will replacing it with >= be of any help?

Yes, that seems to be correct to me. If the `segmentIndexInPlaylist` is larger than the size of the list of segment by more then one, then either the playlist is invalid or we have a bug elsewhere. At that particular line the check is correct.

However, we would like to look into this. @LuGO0 , can you please provide with a sample stream so we can reproduce on our end? 

If you're unable to share publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #9479". Please also update this issue to indicate you’ve done this.

**Comment by dino-saurabh** [comment]
Sure @marcbaechinger we will try to share the test-stream ASAP and will notify the same on this Issue when done.

**Comment by SaurabhOfficial** [comment]
Hey @marcbaechinger I have sent a mail for getting the IPs which we will whitelist for the test-stream could you please check it once.

**Comment by marcbaechinger** [comment]
Hmm, this may be difficult. In the internal network IPs may change and given the WFH situation which is still in place for some engineering sites this can be even more complicated.  Using a VPN client on our side is fine for us but the IP approach has been difficult in the past. Do you have another way to make the stream available?

**Comment by dino-saurabh** [comment]
We can close this Issue, the issue was with the stream itself. Thanks !!
