### ISSUE TITLE
How can I customised the fastforward and fastbackward time limit in exoplayer 2.15.0 lib

### ISSUE THREAD

**Issue by neeluagrawal04** [google/ExoPlayer#9492]
Hi 
I need to customize the fast forward and fast backward functionality of exoplayer from 5 sec to 15 sec. Can I customize it or how can I do this?

**Comment by kim-vde** [comment]
Assuming you are using `SimpleExoPlayer.Builder` to create the player, you can set these values using methods [`setSeekBackIncrementMs`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/SimpleExoPlayer.Builder.html#setSeekBackIncrementMs(long)) and [`setSeekForwardIncrementMs`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/SimpleExoPlayer.Builder.html#setSeekForwardIncrementMs(long)).

Please provide more details if you are building your player differently.

**Comment by neeluagrawal04** [comment]
Yes I am using the same SimpleExoPlayer.Builder to create the player, but setSeekBackIncrementMs and setSeekForwardIncrementMs fucntions could not found in SeekParameters.java class. And if I am using the player.seekParameters?.toleranceAfterUs = 15000L
 player.seekParameters?.toleranceBeforeUs = 15000L
I am not able to reassign the value of toleranceAfterUs  and toleranceBeforeUs  because they are final variables defined in  SeekParameters.java class
How to do it after updating the exoplayer lib to 2.15.0? Could you please help me in this?

**Comment by kim-vde** [comment]
`setSeekBackIncrementMs`/`setSeekForwardIncrementMs` and `seekParameters.toleranceAfterUs`/`toleranceBeforeUs` are doing different things:

* `setSeekBackIncrementMs`/`setSeekForwardIncrementMs` set the increments when pushing on the fastForward/rewind buttons in the UI.
* `seekParameters.toleranceAfterUs`/`toleranceBeforeUs` set the error tolerances when seeking to a specific time in the media file. You can set these values by using [`SimpleExoPlayer.setSeekParameters`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/SimpleExoPlayer.html#setSeekParameters(com.google.android.exoplayer2.SeekParameters))  or [`SimpleExoPlayer.Builder.setSeekParameters`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/SimpleExoPlayer.Builder.html#setSeekParameters(com.google.android.exoplayer2.SeekParameters)) and the [`SeekParameters` constructor](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/SeekParameters.html#%3Cinit%3E(long,long)).

Please clarify what your question is if this doesn't answer it.

**Comment by neeluagrawal04** [comment]
Shared image on dev.exoplayer@gmail.com and I can found that setSeekBackIncrementMs/setSeekForwardIncrementMs methods when using in exoplayer lib 2.15.0 in kotlin can have only get methods and if I am setting the  player.seekForwardIncrement = 15000L or player.seekBackIncrement = 15000L gives the error as Val cannot be reassigned. Please help in this issue

**Comment by kim-vde** [comment]
That's probably because the setters are on the builder (e.g. `SimpleExoPlayer.Builder.setSeekBackIncrementMs`).

**Comment by neeluagrawal04** [comment]
Okay, I am really great for your reply. Thanks for helping in this issue to solve it.

**Comment by MiaJiaXa** [comment]
Hello, How can we reset the `setSeekBackIncrementMs ` after the `SimpleExoPlayer.Builder.build()`? using the player object to reset this increment? I can't see the setter or other API for this in the player object. and also can't get the builder from the player object.
using 2.16.0
@kim-vde  it very appreciates if you can help me out :)

**Comment by neeluagrawal04** [comment]
Hi @MiaJiaXa 
you can simply reset the increment fast forward or backward via setting in exoplayer object while creating it like:-
val player  =  SimpleExoPlayer.Builder()
                    .setSeekBackIncrementMs(15000L)
                    .setSeekForwardIncrementMs(15000L)
                    .build()
This will works.

Thanks

**Comment by MiaJiaXa** [comment]
Thanks for the quick reaction. Sorry. Let me make the question clear. 
It's my question: https://github.com/google/ExoPlayer/issues/9683
I need to double the increment somehow **after** the player is created. (after `player.Builder.build()`) when the user taps on the button on the controller while playbacking

For example, it is 15S when it is initialized, and it can increase to 30S, 60S when you click the double-speed playback button during playback.. (forward and backward) 
so I hope the seekForwardIncrementsMs/seekbackwardIncrementsMs can reset many times. But I'm not finding a way to set it without the EXOPlayer.Builder.

Could you please help to have a look?

**Comment by neeluagrawal04** [comment]
you can customise via using the  player.seekTo() method to achieve this till exoplayer does not give the set method for seekBackIncrement/seekForwardIncrement
Check if this can help you.
Thanks
