### ISSUE TITLE
Exoplayer 2.10.8 - First Frame of video coming late

### ISSUE THREAD

**Issue by vasusachin** [google/ExoPlayer#9502]
While playing a HLS Stream in Exoplayer 2.10.8,
The first video frame is rendered very late compared to older exoplayer version 2.6.1

In Exoplayer 2.6.1, the first frame is rendered first , freezes for some time and then smooth playback is started

In Exoplayer 2.10.8, there is no first frame, black screen for some time and then there is smooth playback without freeze

Is this behavior made configurable in 2.10.8
Please let us know how to keep the same user experience as 2.6.1 to show the first frame quicker in 2.10.8 also

Please note that, In both 2.6.1 and 2.10.8, Tunneling is enabled

Regards,
M.Vijayasarathy

**Comment by krocard** [comment]
2.6.1 was published on Jan 3, 2018, 2.10.8 on Nov 19, 2019. Looking at the blame of [MediaCodecVideoRenderer](https://github.com/google/ExoPlayer/blame/r2.10.8/library/core/src/main/java/com/google/android/exoplayer2/video/MediaCodecVideoRenderer.java) and the output of `git log --grep tunneling r2.6.1..r2.10.8`, there are a few cl that affected tunneling:
 - 53934c13b2800cdcc49c7f3df5005b0a9b3d7943 Select non-primary tunneling decoder
 - 03fe503f1c4744848a1a2a68950b96d81c2f845c Temporarily disable codec reuse
 - 03fe503f1c4744848a1a2a68950b96d81c2f845c Propagate output format in tunneling mode
 - efe8f09f45fe7804e8c92089f744d717502f9019 Propagate EoS in renderer when using video tunneling
 - 7d6b0e1fdab2708f4192cec1621fb50d384a06e1 Move renderer flags, overrides and tunneling ID into Parameters

But I can't see how any of them would affect the first frame speed behaviour. @andrewlewis were responsible for tunneling at the time, does this ring a bell?

**Comment by andrewlewis** [comment]
This doesn't ring any bells. 2.10.8 is still quite old though, please could you check if this is reproducible on a recent version, in case a bug was fixed?

Do you have any customizations or are you using `MediaCodecVideoRenderer` directly?

If it's still reproducible the next thing I'd check is whether `MediaCodecVideoRenderer.maybeNotifyRenderedFirstFrame` is happening later than it used to.
