### ISSUE TITLE
AWS Media Tailor integration

### ISSUE THREAD

**Issue by fjb02** [google/ExoPlayer#9503]
Does anyone know what server side beaconing solution ExoPlayer supports?
We are trying to integrate it with AWS MediaTailor.

**Comment by krocard** [comment]
@andrewlewis, do you know if our client side adds insertion supports MediaTrailor?

**Comment by andrewlewis** [comment]
Currently I don't think we have any built-in support for beaconing on the client for server-side ad insertion, but we do surface some types of timed metadata events during playback that apps can use to implement this themselves.

(Side note: for client-side ad insertion, the IMA extension takes care of beaconing for standard VAST/VMAP streams, but this seems like a question about server-side ad insertion.)

**Comment by fjb02** [comment]
Hi @andrewlewis , thanks for the information, but yes, the question is related to server side insertion.
Do you have information about the integration with AWS and how it collects the metadata (beaconing)?
Tks!!

**Comment by andrewlewis** [comment]
> Do you have information about the integration with AWS and how it collects the metadata (beaconing)?

We don't have any information on this.

I'd try using the information here as a starting point: https://docs.aws.amazon.com/mediatailor/latest/ug/ad-reporting.html

**Comment by fjb02** [comment]
Last question. Do you have any idea if the MediaTailor integration is on the roadmap?
Thanks for your time!

**Comment by andrewlewis** [comment]
It isn't on the ExoPlayer roadmap to have a direct integration with this service.
