### ISSUE TITLE
Cannot resolve method 'createWithNotificationChannel' in 'PlayerNotificationManager'

### ISSUE THREAD

**Issue by pawaom** [google/ExoPlayer#9506]
I recently migrated from `exoplayer:2.11.6` to `exoplayer 2.15` and to android studio arctic fox, and i am testing on  android 11.

I am getting this error `Cannot resolve method 'createWithNotificationChannel' in 'PlayerNotificationManager'`

This used to work fine earlier how can we resolve the issue.

there are similar issue on stackoverflow

here 

https://stackoverflow.com/questions/69306536/how-to-fix-this-playernotificationmanager-createwithnotificationchannel-error

https://stackoverflow.com/questions/69311723/i-cannot-resolve-symbol-createwithnotificationchannel

**Comment by krocard** [comment]
The telescopique constructors `PlayerNotificationManager.createWithNotificationChannel` were deprecated in favor of `PlayerNotificationManager.Builder`. You can easily find this by looking at the file in different versions:
https://github.com/google/ExoPlayer/blob/92e05bcd6608b48cc4d20974f55e6a9136274c33/library/ui/src/main/java/com/google/android/exoplayer2/ui/PlayerNotificationManager.java#L717-L719

  2.15 has removed them. Please migrate to the `Builder` which is more ergonomic and support the same features and more. The builder allows us to add parameters to the class without deprecating constructors constantly. So this API will be more stable now.
