### ISSUE TITLE
Receiving DESCRIBE 401 for Tapo_Camera_3A1E (Tapo C100) camera while streaming using rtsp

### ISSUE THREAD

**Issue by SreeniMannem** [google/ExoPlayer#9508]
Hi team, i am unable to stream RTSP using Tapo_Camera_3A1E (Tapo C100) camera.

I am getting same error like **Receiving DESCRIBE 401**. And i followed the steps which are mentioned in the #9070. But i am unable to get the stream.

Even i followed ticket #9428, but no luck.

Please help in connecting and getting stream through ExoPlayer using the above camera.
 

Reference#
Long story short, an RTSP request contains a cseq number, and the response carry the same sequence number, that's how the RTSP client knows which request corresponds to the incoming response. 

You could try move the cSeq definition on `RtspClient:L299` to the otter class, and remove the line `RtspClient:L426` that checks for the cseq.

_Originally posted by @claincly in https://github.com/google/ExoPlayer/issues/9070#issuecomment-864834077_

**Comment by claincly** [comment]
Please provide a log of RTSP messages.

The easiest way is to use the `RtspMediaSource.Factory` method `setDebugLoggingEnabled()`
