### ISSUE TITLE
(trackSelector as MappingTrackSelector).currentMappedTrackInfo always returns null

### ISSUE THREAD

**Issue by grndvl1** [google/ExoPlayer#9513]
mappedTrackinfo always returns null

I do 
```
    private val eventListener: Player.EventListener = object : Player.EventListener {
        override fun onPlayerStateChanged(playWhenReady: Boolean, playbackState: Int) {
            if (playbackState == Player.STATE_READY) {
                // look for MappedTrackInfo
                Timber.d("JOHN: ${closedCaptionManager.checkAndSetClosedCaptions()}")
            }
        }
    }

class ClosedCaptionManager constructor(
    var trackSelector: TrackSelector,
    var player: SimpleExoPlayer
) {
    // These two could be fields OR passed around
    var textTrackIndex = 0
    var trackGroups: TrackGroupArray? = null
    var pairTrackList: ArrayList<Pair<Int, Int>> = ArrayList()
    // ((videoPlayer.metadataComponent as SimpleExoPlayer).trackSelector as DefaultTrackSelector)
    // .currentMappedTrackInfo.getTrackGroups()2
    val mappingTrackInfo: MappingTrackSelector = trackSelector as MappingTrackSelector

    fun checkAndSetClosedCaptions(): Boolean {
        // This is the body of the logic  for see if there are even video tracks
        // It also does some field setting
        val mappedTrackInfo = mappingTrackInfo.currentMappedTrackInfo  // always returns null on a video I know has CC data
        for (i in 0 until mappedTrackInfo?.rendererCount!!) {
            trackGroups = mappedTrackInfo.getTrackGroups(i)
            if (trackGroups!!.length != 0) {
                when (player.getRendererType(i)) {
                    C.TRACK_TYPE_TEXT -> {
                        textTrackIndex = i
                        return true
                    }
                }
            }
        }
        return false
    }

```

No clear example on how to get CC data from player.  This is horrible, why is there no easy way to find if there is CC data and then to enable disable it.  It seems a basic function that should get its own treatment of special methods

 ExoPlayer version number 2.13.3

**Comment by ojw28** [comment]
Does the ExoPlayer demo app (or equivalently, `StyledPlayerView`) provide the option to select CC for the video you're testing with? It would probably be helpful if you could provide a link to the video you're using, so that we can reproduce what you're seeing.

**Comment by grndvl1** [comment]
I found out the issue.  The current documentation is horrible especially for ClosedCaptioning and finding examples that were not old was a nightmare.  It literally took me days to get this right and due to this long time I am no longer on the project.  Please for the sake of us lowly programmers update the documents to something that we all can understand and use 

Here was the issue, we used a DI to provide the player when needed.  The player was created like this 

`SimpleExoPlayer.Builder(fragment.requireContext()).build()`

It is now created like this

        val renderersFactory: RenderersFactory = DefaultRenderersFactory(fragment.requireContext())
            .setExtensionRendererMode(DefaultRenderersFactory.EXTENSION_RENDERER_MODE_OFF)

        val builder: DefaultTrackSelector.ParametersBuilder =
            DefaultTrackSelector.ParametersBuilder(fragment.requireContext())

        // set this to false if you want it on automatically when video starts, use it for testing
        // Or future it for if we have saved parameters
        val trackSelectorParameters = builder.setRendererDisabled(C.TRACK_TYPE_VIDEO, true)
            .setPreferredTextLanguages("eng")
            .build()
        val trackSelector = DefaultTrackSelector(fragment.requireContext())
        trackSelector.parameters = trackSelectorParameters

        return SimpleExoPlayer.Builder(fragment.requireContext(), renderersFactory)
            .setTrackSelector(trackSelector)
            .build()

Some indication as to why it is null would have been nice.  Instead I was just chasing the player and throwing stuff at it and see what worked eventually I got it but got removed from the client.
