### ISSUE TITLE
How to turn off logging

### ISSUE THREAD

**Issue by ParticleCore** [google/ExoPlayer#9514]
The current status of the exoplayer spams the logcat immensely and that makes it quite hard to locate information that I need that is not related to exoplayer. I looked for a way to turn off logging completely from exoplayer, but there is no clear way available online on how to do this. I checked the documentation, but it only explains how to get even more detailed logging, and absolutely no mention on how to turn it off: https://exoplayer.dev/debug-logging.html

How can I turn off all logging from the exoplayer? Currently the log spam is INSANE and unworkable! This here is just a sample, there's more of it from multiple different locations all related to the exoplayer.

![image](https://user-images.githubusercontent.com/9222661/135494155-f943514f-69e9-4f42-8057-ad062128bbd6.png)

![image](https://user-images.githubusercontent.com/9222661/135493673-44c44cb9-0eb4-4a3e-8863-5a5efa6b66ae.png)

**Comment by icbaker** [comment]
None of the log lines shown in your screenshots are coming from ExoPlayer code. It looks like they're all coming from the Android Framework.

I'm afraid there's nothing we can change in the ExoPlayer library to reduce this logging.

The BufferQueueProducer error logging specifically is tracked by [internal b/140581935].

If you find the other logs too spammy I suggest you report it to the Android Framework: https://source.android.com/setup/contribute/report-bugs

**Comment by ParticleCore** [comment]
The log spam is introduced by the use of ExoPlayer. I cannot find anywhere else how to disable these other than to not use ExoPlayer completely. Please provide some sort of way for us to turn off this log spam seeing that it is literally because ExoPlayer library is being used.

**Comment by icbaker** [comment]
This logging is coming from inside the OS. There's nothing we, as an application-level library, can do to reduce or change it.

I suspect you'd see very similar logging if you were to play media using the same Android Framework components as ExoPlayer does without using ExoPlayer to do it - because this logging is coming from those components.
