### ISSUE TITLE
Inquiries regarding YouTube video playback logs

### ISSUE THREAD

**Issue by yyms3275** [google/ExoPlayer#9515]
I checked the log contents below when playing with the player. Do you know any information related to this log?

**<LOG>**

> client requested max input size 86400, which is smaller than what component recommended (184320); overriding with component recommendation. This behavior is subject to change. It is recommended that app developers double check whether the requested max input size is in reasonable range.

**Comment by ojw28** [comment]
All this is saying is that the decoder is allocating larger input buffers than ExoPlayer requested. As an application developer, you should be able to safely ignore this message.
