### ISSUE TITLE
Video recorded by camera app not playing in Nokia G10

### ISSUE THREAD

**Issue by razi3742** [google/ExoPlayer#9518]
I am using Exoplayer latest version 2.15.0
in android Device nokia g10 OS 11 

I am recording [this ](https://www.youtube.com/watch?v=aqfPb_I7NwI)Video by default Video Intent and it saves video to storage. when i play video from storage it play video but stop on last second. it seems camera not able to record last second video. I understand there is any issue with my camera app. but i believe Exoplayer should play that video before last second.

video Link : https://www.youtube.com/watch?v=aqfPb_I7NwI

when i try to play Exoplayer shows total video length but did not play.  and send message in logcat

```
2021-10-01 14:53:36.120 19572-19942/com.surveyauto.surveyauto E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:624)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:600)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: java.io.EOFException
        at com.google.android.exoplayer2.source.SampleDataQueue.sampleData(SampleDataQueue.java:184)
        at com.google.android.exoplayer2.source.SampleQueue.sampleData(SampleQueue.java:579)
        at com.google.android.exoplayer2.extractor.TrackOutput$-CC.$default$sampleData(TrackOutput.java:153)
        at com.google.android.exoplayer2.source.SampleQueue.sampleData(Unknown Source:0)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readSample(Mp4Extractor.java:629)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:247)
        at com.google.android.exoplayer2.source.BundledExtractorsAdapter.read(BundledExtractorsAdapter.java:127)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1047)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:409)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
```

but when i drag cursor little bit it starting playing video untill last second.

this is the code i am using to play video from local storage.

```
import android.app.Activity
import android.net.Uri
import com.google.android.exoplayer2.MediaItem
import com.google.android.exoplayer2.Player
import com.google.android.exoplayer2.SimpleExoPlayer
import com.google.android.exoplayer2.source.DefaultMediaSourceFactory
import com.google.android.exoplayer2.source.MediaSource
import com.google.android.exoplayer2.source.ProgressiveMediaSource
import com.google.android.exoplayer2.source.dash.DashMediaSource
import com.google.android.exoplayer2.ui.PlayerView
import com.google.android.exoplayer2.upstream.*
import com.surveyauto.surveyauto.utils.AppUtil
import com.surveyauto.surveyauto.utils.CurrentUserRole


class ExoPlayerHandler(var playerView: PlayerView,var url: String, var activity: Activity,var listener : Player.Listener) {

    private var playWhenReady = true
    private var currentWindow = 0
    private var playbackPosition: Long = 0


    var player: SimpleExoPlayer? = null

    fun startPlayer() {
        if (player == null) {
            initializePlayer()
            initializeMediaItem()
            playMedia()
            setUpListener()
        }
    }

    private fun initializePlayer() {

        val builder = SimpleExoPlayer.Builder(activity)
        if (AppUtil.isValidUrl(url)) {
            builder.setMediaSourceFactory(getDefaultMediaSource())
        }
        player = builder.build()
        playerView.player = player
    }

    private fun initializeMediaItem() {
        val mediaItem = MediaItem.fromUri(Uri.parse(url))
        player?.setMediaItem(mediaItem)
    }


    fun stopPlayer() {
        if (player != null) {
            playWhenReady = player!!.playWhenReady
            playbackPosition = player!!.currentPosition
            currentWindow = player!!.currentWindowIndex
            player!!.release()
            player = null
        }
    }

    private fun setUpListener() {
        player?.addListener(listener)
    }

    private fun playMedia() {
        player?.playWhenReady = playWhenReady
        player?.seekTo(currentWindow, playbackPosition)
        player?.prepare()
    }

    private fun buildMediaSource(uri: Uri, type: String): MediaSource {
        val dataSourceFactory: DataSource.Factory by lazy {
            DefaultDataSourceFactory(activity, "exoplayer-sample")
        }

        var data = if (type == "dash") {
            DashMediaSource.Factory(dataSourceFactory)
                .createMediaSource(MediaItem.fromUri(uri))
        } else {
            ProgressiveMediaSource.Factory(dataSourceFactory)
                .createMediaSource(MediaItem.fromUri(uri))
        }
        return data
    }


    private fun getDefaultMediaSource(): DefaultMediaSourceFactory {

        val httpDataSourceFactory: HttpDataSource.Factory =
            DefaultHttpDataSource.Factory().setAllowCrossProtocolRedirects(true)

        val dataSourceFactory: DataSource.Factory = DataSource.Factory {
            val dataSource: HttpDataSource = httpDataSourceFactory.createDataSource()
            // Set a custom authentication request header.
            dataSource.setRequestProperty(
                "Authorization",
                CurrentUserRole.getAuthorizationToken()
            )
            dataSource
        }

        return DefaultMediaSourceFactory(dataSourceFactory)
    }


}
```

**Comment by ojw28** [comment]
If the file being played is not a valid media file, then this may be expected. If you want us to take a look, you'll need to provide the actual problematic media file. I'm not sure if you intended to link to it with your first link, but it currently links to YouTube rather than to a media file.

**Comment by razi3742** [comment]
@ojw28 thanks for the quick response.

please find the actual video here
https://drive.google.com/file/d/1Es1wARs_Crvz7ZTPUEUcnKfFHcjPRD_9/view?usp=sharing

please closely look into the seekbar of exo player in video.

**Comment by ojw28** [comment]
You seem to have provided a video of the video. We need the actual video file that you're passing to ExoPlayer so that we can reproduce the problem, not a video of what happens when you do this.

**Comment by razi3742** [comment]
oops sorry. please find the newly created mp4 file

https://drive.google.com/file/d/1sI82hCTq3rxQF3ZkvO4h4BabbVMX8hCI/view?usp=sharing

**Comment by ojw28** [comment]
It looks like the file is broken toward the start. Note that Chrome isn't able to play the file either. QuickTime player can play the file, but the first couple of seconds are distorted. VLC is able to play the file by skipping the first couple of seconds.

I don't think it's a good use of time for us to try too hard to make this file play correctly, particularly given support in other players is also very variable. The correct fix is to make sure whatever's recording these files generates valid output.

**Comment by razi3742** [comment]
@ojw28 thanks for the quick investigation. i have one question videoview is also playing this file while its corrupted output. but i think if videoview is playing this file then exoplayer should also play this file. 
 
If File is corrupt for exoplayer then why its showing video total time and not playing but if we drag cursor little bit its playing. don't you think exoplayer behaviour should be same for all use cases

**Comment by ojw28** [comment]
As observed above, support by different players may vary, but will likely be quite patchy. We don't promise to handle every malformed media file as well as `VideoView`, or any other player. Note also that it's quite likely that ExoPlayer does a better job than `VideoView` of handling some other class of malformed video file; how well it works in each case is really going to come down to the detail of how the player handles whatever the malformed part of the file is.

**Comment by razi3742** [comment]
Okay, Thanks for the detail explanation.
