### ISSUE TITLE
Handling of invalid periods in DASH MPDs

### ISSUE THREAD

**Issue by Bastian35022** [google/ExoPlayer#952]
In `MediaPresentationDescriptionParser` in method `parseMediaPresentationDescription`, it is possible that one or more periods are discarded/ignored. This can lead to an empty list of Periods for the MPD. Example: live profile, and only one period element, which lacks the start attribute (I know this is an erroneous MPD).

In this case, the whole app will crash due to an uncaught `IndexOutOfBoundsException`, when requesting the first period in `DashRendererBuilder.buildRenderers()`, line `Period period = manifest.getPeriod(0);`.

As there has to be at least one Period according to the spec anyway, I would suggest doing something along the following lines at the end of `parseMediaPresentationDescription`, in order to have a graceful shutdown of the player.

```
if (periods.isEmpty()) {
  throw new ParseException(
      "no valid periods present in media presentation description");
}
```

**Comment by ojw28** [comment]
Feel free to send a pull request, if you'd like this change! Thanks.
