### ISSUE TITLE
Stop video when clicking on a different RecyclerView item?

### ISSUE THREAD

**Issue by user849651** [google/ExoPlayer#9521]
I have a RecyclerView, where each item plays a video. I share one instance of `ExoPlayer`, and only play one video on the screen at a time. When a user taps on a video's thumbnail, it opens the player in a fullscreen dialog.

However, my current problem is that if a video is playing in RecyclerView item 1, and the user taps the video thumbnail in RecyclerView item 2, it plays the video of item 2 (which is correct), but I don't know how to stop the video/show a thumbnail for RecyclerView item 1 (since they clicked on item 2).

Here is the relevant code from the `onBindViewHolder`:

```
holder.videoThumbnail.setOnClickListener(new View.OnClickListener() {
    @Override
    public void onClick(View view) {
        holder.openFullscreenVideoDialog();
    }
});
```

Here is the `openFullscreenVideoDialog()` method in the view holder:

```

    public class PostViewHolder extends RecyclerView.ViewHolder implements View.OnClickListener, FullscreenVideoDialogFragment.FullscreenVideoDialogFragmentListener {
        public Post post;

        public ConstraintLayout contentView;

        public ImageView videoThumbnail;

        public HlsMediaSource hlsMediaSource;

        public PlayerView playerView;

        public PostViewHolder(View v) {
            super(v);

            contentView = v.findViewById(R.id.content_view);

            videoThumbnail = v.findViewById(R.id.video_thumbnail);
            playerView = v.findViewById(R.id.player_view);

            setupVideoDialog();
        }

        private void setupVideoDialog() {
            mFullScreenDialog = new Dialog(context, android.R.style.Theme_Black_NoTitleBar_Fullscreen) {
                public void onBackPressed() {
                    super.onBackPressed();
                }
            };
        }

        private void openFullscreenVideoDialog() {
            mExoPlayerFullscreen = true;

            FragmentManager fm = ((FragmentActivity) context).getSupportFragmentManager();
            FullscreenVideoDialogFragment dialog = FullscreenVideoDialogFragment.newInstance(post, hlsMediaSource, exoPlayer);
            dialog.setFullscreenVideoDialogFragmentListener(this);
            dialog.show(fm, "fragment_video_dialog");

            playerView.setPlayer(null);
        }
    }
}
```

At its most basic level, my question is: how do I change views from item 1 when a user taps on the video thumbnail in item 2?

**Comment by user849651** [comment]
Because I'm using just one instance of ExoPlayer, is it possible to listen for an event where, if the player changes (maybe in state or to some other view), I can set it to show a thumbnail over item 1 again when item 2's video is tapped?

**Comment by andrewlewis** [comment]
> Because I'm using just one instance of ExoPlayer, is it possible to listen for an event where, if the player changes (maybe in state or to some other view), I can set it to show a thumbnail over item 1 again when item 2's video is tapped?

I don't follow why an event is needed for this case -- can't you show a thumbnail on top of the old player position just before you call `setPlayer` on its `PlayerView`, then wait for `onRenderedFirstFrame` to hide the thumbnail on top of the new player position?
