### ISSUE TITLE
DASH ULL CMAF feature

### ISSUE THREAD

**Issue by luquilh** [google/ExoPlayer#9529]
Hi! Can anyone tell me if ExoPlayer supports DASH ULL (Ultra Low Latency) with CMAF?
Starting with wich ExoPlayer version is this feature supported?

Particullarly, we need DASH ULL CMAF with both HD and UHD 4K video.

Thanks in advanced

**Comment by andrewlewis** [comment]
I think this is supported though I'm not certain about using CMAF segments. Over to @christosts to confirm/correct. Thanks!

**Comment by christosts** [comment]
Yes, please refer to the [format support](https://exoplayer.dev/supported-formats.html#adaptive-streaming) and our related [blog post](https://medium.com/google-exoplayer/low-latency-live-streaming-with-exoplayer-8552d5841060) for low-latency support (DASH & HLS).

Feel free to file an issue if your low-latency streams do not work as expected.
