### ISSUE TITLE
[ExoLayer] The player has ugly picture when starting play HLS from low bitrate on Amlogic

### ISSUE THREAD

**Issue by Avetri** [google/ExoPlayer#953]
ExoPlayer 1.5.1, Android 4.4, Amlogic 812, player demo
Stream's URL http://qthttp.apple.com.edgesuite.net/1010qwoeiuryfg/sl.m3u8

The player has ugly picture when starting play HLS from a low bitrate. Even if it turns to playing a high bitrate stream.
If I make it to start from a high bitrate stream video looks good as on my LG G2.

**Comment by Avetri** [comment]
I don't get MediaCodec.INFO_OUTPUT_FORMAT_CHANGED code from the MediaCodec::dequeueOutputBuffer().

**Comment by Avetri** [comment]
To start from a high bitrate need to use following changes:

--- library/src/main/java/com/google/android/exoplayer/hls/HlsChunkSource.java	(revision )
+++ library/src/main/java/com/google/android/exoplayer/hls/HlsChunkSource.java	(revision )
@@ -204,7 +204,7 @@
-       int minOriginalVariantIndex = Integer.MAX_VALUE;
+      int minOriginalVariantIndex = Integer.MIN_VALUE;
       for (int i = 0; i < variants.length; i++) {
         int originalVariantIndex = masterPlaylistVariants.indexOf(variants[i]);
-        if (originalVariantIndex < minOriginalVariantIndex) {
+        if (originalVariantIndex > minOriginalVariantIndex) {
           minOriginalVariantIndex = originalVariantIndex;
           selectedVariantIndex = i;
         }

**Comment by ojw28** [comment]
Are you sure the player is switching to the high bitrate stream (without your modification to have it start start with that stream)? If so, it feels like a device specific issue to me?

**Comment by Avetri** [comment]
Yes, I am sure.
It is very notably on that stream. Bitrate changes and quality of video too.

**Comment by Avetri** [comment]
If it is alright we should see messages like below in logcat:
<pre>11-13 02:15:00.676 30906-30906/com.google.android.exoplayer.demo D/EventLogger: videoSizeChanged [640, 360, 0, 1.0]</pre>
I get it once, at start of a playing.

Could anybody check it on their Amlogic's devices please?

**Comment by ojw28** [comment]
You should report this issue to AmLogic. I don't think it's a problem with ExoPlayer.

As a side note - There's insufficient information in this bug to tell exactly which device, Android build and ExoPlayer build this issue reproduces with. Please provide complete information in any future bug reports, as requested in the issue template.
