### ISSUE TITLE
Buffer setting and loading problems with video playback

### ISSUE THREAD

**Issue by yyms3275** [google/ExoPlayer#9531]
I am currently playing youtube url through exoplayer.
However, for some reason, there are times when the video is played immediately when it is loaded, but sometimes the buffering time is long.

Main symptoms:

1. 3~4 seconds of buffering occurs when loading video
2. Repeated buffy worms occur after video loading and playback

I am loading the video in the following way, which plays the video and audio together.

MediaSource videoSource = new ProgressiveMediaSource.Factory(new DefaultDataSourceFactory(context)).createMediaSource(MediaItem.fromUri(video));
MediaSource audioSource = new ProgressiveMediaSource.Factory(new DefaultDataSourceFactory(context)).createMediaSource(MediaItem.fromUri(audio));
return new MergingMediaSource(videoSource, audioSource);

And the settings below are the settings created when loading a video through exoplayer.
Is there something wrong with the settings?

DefaultLoadControl loadControl = new DefaultLoadControl.Builder()
	.setAllocator(new DefaultAllocator(true,  C.DEFAULT_BUFFER_SEGMENT_SIZE))
	.setBufferDurationsMs(30_000, 60_000, 1000,1000)
	.setTargetBufferBytes(C.LENGTH_UNSET)
	.setPrioritizeTimeOverSizeThresholds(true)
	.setBackBuffer(1000 * 15,true)
	.build();

 DataSource.Factory cacheDataSourceFactory = new CacheDataSource.Factory()
                .setCache(VideoCache.getInstance(context))
                .setUpstreamDataSourceFactory(dataSourceFactory);

DefaultBandwidthMeter defaultBandwidthMeter = new DefaultBandwidthMeter
	.Builder(this)
	.setResetOnNetworkTypeChange(true)
	.setSlidingWindowMaxWeight(2000)
	.setInitialBitrateEstimate(Integer.MAX_VALUE)
	.build();

DefaultTrackSelector trackSelector = new DefaultTrackSelector(this);
trackSelector.setParameters(trackSelector
	.buildUponParameters()
	.setForceLowestBitrate(true)
	.setForceHighestSupportedBitrate(true)
	.setMaxVideoSizeSd());

exoPlayerVideo = new SimpleExoPlayer.Builder(this)
    .setLoadControl(loadControl)
    .setMediaSourceFactory(new DefaultMediaSourceFactory(cacheDataSourceFactory))
    .setBandwidthMeter(defaultBandwidthMeter)
    .setTrackSelector(trackSelector)
    .setUseLazyPreparation(true)
    .build();

https://user-images.githubusercontent.com/41143436/135980822-9451f3a6-c547-4c59-8617-857feea3aaff.mp4

**Comment by andrewlewis** [comment]
As things stand I don't think we can efficiently investigate this as we don't have access to the media you are trying to play and you've made a lot of customizations. Please could you try removing some customizations one by one to simplify the setup? This may help diagnose where the issue is. For example, you could try removing the load control customizations, the caching layer and the merging (just play video for example) and see if that makes a difference to the behavior.

**Comment by yyms3275** [comment]
> As things stand I don't think we can efficiently investigate this as we don't have access to the media you are trying to play and you've made a lot of customizations. Please could you try removing some customizations one by one to simplify the setup? This may help diagnose where the issue is. For example, you could try removing the load control customizations, the caching layer and the merging (just play video for example) and see if that makes a difference to the behavior.

If I remove all the settings and play, the symptoms get worse. Don't worry, it's a little less if you do the customization like that. The buffering of images is the same, and not all images show the same symptoms. However, the buffered image takes almost the same buffering. Do I need other options or other tuning than the ones I set?

**Comment by andrewlewis** [comment]
If you play just the video URL in the ExoPlayer demo app (with no modifications) using [these instructions](https://exoplayer.dev/demo-application.html) do you still find that playback isn't smooth?
