### ISSUE TITLE
Ad cue points not getting removed after Ad completes

### ISSUE THREAD

**Issue by danish241194** [google/ExoPlayer#9533]
Following is code snippet used for ad integration 
```
ImaAdsLoader.Builder builder = new ImaAdsLoader.Builder(mContext);
ImaSdkSettings imaSdkSettings = ImaSdkFactory.getInstance().createImaSdkSettings();
ImaAdsLoader imaAdsLoader = builder.setImaSdkSettings(imaSdkSettings).buildForAdTag(Uri.parse(urlString));

MediaSource mediaSourceWithAds = new AdsMediaSource(
                        mediaSources,
                        dataSourceFactory,
                        imaAdsLoader,
                        this);
mSimpleExoPlayer.prepare(mediaSourceWithAds);
```

Ads are running properly, but whenever some ad runs ,gets completed and if user seeks back to position before the same ad , the ad runs again. 

I want one Ad at particular point to get played only once ,this ad should get removed from Ad Cue points once it runs. Is there any way of achieving this.

**Comment by andrewlewis** [comment]
Can you reproduce this in the ExoPlayer demo app at the latest version? Do you see IMA's ad overlay views (countdown timer, more info link) the first time the ad plays?

If we need to investigate further it would be useful to have a link to your ad tag, or at least a logcat snippet taking after a playback where you saw the issue, with debug mode enabled via `ImaAdsLoader.Builder.setDebugModeEnabled(true)`. You can provide that information here or email it to dev.exoplayer@gmail.com with subject "Issue #9533" (and update this issue to indicate you've done this).

Aside: I don't think you need to create your own `ImaSdkSettings` instance -- the builder takes care of constructing a default one for you.
