### ISSUE TITLE
Duration and time bar not display when play webm file in exoplayer 2.15.0

### ISSUE THREAD

**Issue by boisset** [google/ExoPlayer#9534]
When i play webm file with exoplayer 2.15.0 the duration is still 0 and time bar not display.
I use ExoPlayerDemo for my test and the file webm is in the zip
[108wvk31fdo2b9155s4sz.zip](https://github.com/google/ExoPlayer/files/7291287/108wvk31fdo2b9155s4sz.zip)

**Comment by andrewlewis** [comment]
This is similar to #4856 -- `MatroskaExtractor` is not finding cues.
