### ISSUE TITLE
How do you set the Album Art Image for an AndroidX MediaRouteCastDialog using the Exoplayer Cast Library extension

### ISSUE THREAD

**Issue by vindhyapratap** [google/ExoPlayer#9539]
My Question is clearly stated herein StackOverflow(https://stackoverflow.com/questions/64457358/how-do-you-set-the-album-art-image-for-an-androidx-mediaroutecastdialog-using-th). But no one answered this.

I stated here as well, I am using cast-extension of Exoplayer 2.15. Here we can pass Medi info in MediaItem. Setting MediaMetadata here I have option Title, Subtitle but not getting from where to add image url or image to this for the video for cast dialog that appears. Pelase let me know how to do this.

Thanks,

**Comment by andrewlewis** [comment]
@marcbaechinger Please could you take a look as a Cast extension question? Thanks.

**Comment by marcbaechinger** [comment]
Sorry for my late response. The Stackoverflow link does not work I'm afraid.
There is currently no support for passing an image to the cast receiver with the `CastPlayer`.

Could you clarify which API of the Cast SDK you would use for achieving what you mean?

**Comment by ziem** [comment]
I think this is the exact copy of the StackOverflow question from the first comment: https://askandroidquestions.com/2020/10/21/how-do-you-set-the-album-art-image-for-an-androidx-mediaroutecastdialog-using-the-exoplayer-cast-library-extension/
