### ISSUE TITLE
Hide debug banner when in playback view

### ISSUE THREAD

**Issue by Eric0021** [google/ExoPlayer#9540]
Hi, sorry if this is a really simple question as I am a complete noob in android development. I am running the exoplayer demo on my phone. When I am in playback view after having selected a video, there is this black overlay banner on the top that seems like a debugger, it shows the state of variables like playWhenReady and playbackState. How do I hide this overlay banner? 

Thanks,

**Comment by andrewlewis** [comment]
You could hide it in the layout [here](https://github.com/google/ExoPlayer/blob/aa67685/demos/main/src/main/res/layout/player_activity.xml#L36), or remove it and the various the references using it in [`PlayerActivity.java`](https://github.com/google/ExoPlayer/blob/aa67685071a1507dfd199be53939c8d853131e65/demos/main/src/main/java/com/google/android/exoplayer2/demo/PlayerActivity.java#L127).

**Comment by Eric0021** [comment]
Thank you for the response Andrew, it is fixed.
