### ISSUE TITLE
HLS playback issue

### ISSUE THREAD

**Issue by zeeshan999** [google/ExoPlayer#955]
Hi,

I want to integrate exoplayer in my application. I added an HLS link to the sample app but it is not working. These links works fine with android media player.

http://cds.n2p5u8x8.hwcdn.net/Movies/Hindi/HLS/Featured/HLS/Don/index.m3u8

http://wpc.FC2A.edgecastcdn.net/80FC2A/PH2/jdorigin/jdARYMusic849.stream/playlist.m3u8?3c0e9e5f113cfe7f51ee1ce68b0beb91a2399ebff00e6d0717dc81c3efe86e13a638bdcb1b853c558bca9d80f6c6894fc8bedc6a8d

(exoplayer sample app 1.5.2)

Similar to #337 
log

11-13 12:42:50.792: E/OMXMaster(4910): A component of name 'OMX.google.alac.decoder' already exists, ignoring this one.
11-13 12:42:50.802: E/OMXNodeInstance(4910): OMX_GetExtensionIndex failed
11-13 12:42:50.822: E/OMXMaster(4910): A component of name 'OMX.google.alac.decoder' already exists, ignoring this one.
11-13 12:42:50.832: E/OMXNodeInstance(4910): OMX_GetExtensionIndex failed
11-13 12:42:50.862: E/SoftAVC(4910): Decoder failed: -2
11-13 12:42:50.862: E/ACodec(4910): [OMX.google.h264.decoder] ERROR(0x80001001)
11-13 12:42:50.862: E/MediaCodec(4910): Codec reported an error. (omx error 0x80001001, internalError -2147483648)
11-13 12:42:50.872: E/ExoPlayerImplInternal(4910): Internal runtime error.
11-13 12:42:50.872: E/ExoPlayerImplInternal(4910): java.lang.IllegalStateException
11-13 12:42:50.872: E/ExoPlayerImplInternal(4910): 	at android.media.MediaCodec.queueInputBuffer(Native Method)
11-13 12:42:50.872: E/ExoPlayerImplInternal(4910): 	at com.google.android.exoplayer.MediaCodecTrackRenderer.feedInputBuffer(MediaCodecTrackRenderer.java:646)
11-13 12:42:50.872: E/ExoPlayerImplInternal(4910): 	at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:460)
11-13 12:42:50.872: E/ExoPlayerImplInternal(4910): 	at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431)
11-13 12:42:50.872: E/ExoPlayerImplInternal(4910): 	at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
11-13 12:42:50.872: E/ExoPlayerImplInternal(4910): 	at android.os.Handler.dispatchMessage(Handler.java:95)
11-13 12:42:50.872: E/ExoPlayerImplInternal(4910): 	at android.os.Looper.loop(Looper.java:137)
11-13 12:42:50.872: E/ExoPlayerImplInternal(4910): 	at android.os.HandlerThread.run(HandlerThread.java:60)
11-13 12:42:50.872: E/ExoPlayerImplInternal(4910): 	at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
11-13 12:42:50.902: E/EventLogger(4910): playerFailed [2.89]
11-13 12:42:50.902: E/EventLogger(4910): com.google.android.exoplayer.ExoPlaybackException: java.lang.IllegalStateException
11-13 12:42:50.902: E/EventLogger(4910): 	at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:246)
11-13 12:42:50.902: E/EventLogger(4910): 	at android.os.Handler.dispatchMessage(Handler.java:95)
11-13 12:42:50.902: E/EventLogger(4910): 	at android.os.Looper.loop(Looper.java:137)
11-13 12:42:50.902: E/EventLogger(4910): 	at android.os.HandlerThread.run(HandlerThread.java:60)
11-13 12:42:50.902: E/EventLogger(4910): 	at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
11-13 12:42:50.902: E/EventLogger(4910): Caused by: java.lang.IllegalStateException
11-13 12:42:50.902: E/EventLogger(4910): 	at android.media.MediaCodec.queueInputBuffer(Native Method)
11-13 12:42:50.902: E/EventLogger(4910): 	at com.google.android.exoplayer.MediaCodecTrackRenderer.feedInputBuffer(MediaCodecTrackRenderer.java:646)
11-13 12:42:50.902: E/EventLogger(4910): 	at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:460)
11-13 12:42:50.902: E/EventLogger(4910): 	at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431)
11-13 12:42:50.902: E/EventLogger(4910): 	at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
11-13 12:42:50.902: E/EventLogger(4910): 	... 4 more

**Comment by ojw28** [comment]
Both links work fine in the demo app for me. Please file a new issue providing more information, as described [here](https://google.github.io/ExoPlayer/2015/10/01/reporting-issues.html). Note that if you're running on an emulator, it's likely an emulator specific issue. Please try on a real device / real devices.

**Comment by solidfunday** [comment]
Hello, zeeshan

Do you have skype id? I wanted to chat with you.
