### ISSUE TITLE
android.app.remoteserviceexception: bad notification for startforeground

### ISSUE THREAD

**Issue by lakshaymudgal88** [google/ExoPlayer#9550]
#1234
Hi Exoplayer Team, I am getting errors with the latest version 2.15.1 when trying to show notifications in the notification tray. Why is this issue here? I am using the following code.

```
      notificationManager = new PlayerNotificationManager
                .Builder(this, NOTIFICATION_ID, PLAYBACK_ID)
                .setMediaDescriptionAdapter(mediaDescriptionAdapter)
//                .setChannelNameResourceId(2)
//                .setChannelDescriptionResourceId(2)
                .setNotificationListener(notificationListener)
                .build();

```
and in the notificationlistener my code is

```
    private final PlayerNotificationManager.NotificationListener notificationListener =
            new PlayerNotificationManager.NotificationListener() {

                @Override
                public void onNotificationCancelled(int notificationId, boolean dismissedByUser) {
                    if (dismissedByUser) {
                        stopSelf();
                    }
                }

                @Override
                public void onNotificationPosted(int notificationId, @NotNull Notification notification, boolean ongoing) {
                    Toast.makeText(getApplicationContext(), "n " + notificationId, Toast.LENGTH_SHORT).show();
                    if (!ongoing) {
                        stopForeground(true);
                    } else {
//                        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
//                            startForeground(notificationId, notification, ServiceInfo.FOREGROUND_SERVICE_TYPE_MEDIA_PLAYBACK);
//                        } else {
//                            startForeground(notificationId, notification);
//                        }
                    }
                }
            };
```

the notification listener code works well in android 11 1 yeat back when I think I am using the 2.10.0 version, but now I think the issue is in android 11 only because of check-in version 9 and it works well. Please help me to fix it for my app because I have to publish an update of the app next week.

Hope you understand and help me to find out

Android Device -  Redmi Note10S
Android Version - 11

**Comment by claincly** [comment]
I have trouble understanding your question. It seems the notification works with Android 11 and ExoPlayer 2.10.0?

@marcbaechinger Could you take a quick look to see if it's related to #8500?

**Comment by Sayum24** [comment]
I have got the same error updating the Exoplayer librarys from **2.15.1** to **2.16.0.**
At the old version everything is working fine, now I get the error.
I'm gonna rollback to the old version for now...

**Comment by merlin-zaraza** [comment]
You have to set `setChannelNameResourceId` to make notification channel. Hey, ExoPlayer team, please move `ChannelNameResourceId` to Builder constructor - it's mandatory field.

**Comment by marcbaechinger** [comment]
@merlin-zaraza Some apps may want to create the channel itself instead of having it created automatically. In such a case only the `channelId` needs to be set. The java doc of `setChannelNameResourceId` is saying that it needs to be set to a valid value if the channel should be automatically created.

**Comment by marcbaechinger** [comment]
I marked this as a `documentation candidate` to document the constructor argument `channelId` in more detail/. It should say that the channel needs to be already created or else `setChannelNameResourceId` needs to be called.

**Comment by marcbaechinger** [comment]
Closing this issue as the need for an existing channel has been documented and there wasn't any more activity. Please reopen if this is still an issue.
