### ISSUE TITLE
How to use exoplayer demo app to play local video files?

### ISSUE THREAD

**Issue by dubeyabhijeet** [google/ExoPlayer#9552]
Hi,

I want to use exoplayer to test Video performance. Idea is to use different performance metrics to get the platform performance issues. So, my query is how to use the demo exoplayer app to play local video files on phone ?

I want to run different videos to get dropped frames rather than relying on surfaceflinger frame drop.

Right now we can only stream different video files by configuring the json. 

Is there any direct way to use demo app? May be by configuring just the json itself or i need write new player itself?

Regards,
Abhijeet

**Comment by wangxuan217** [comment]
You can put some media resources locally (and make sure you have permission to them), and then call them in this way
``` java
MediaSource[] mediaSources = new MediaSource[paths.length];
mediaSources[i] = new ProgressiveMediaSource.Factory(new FileDataSource.Factory())
                    .createMediaSource(MediaItem.fromUri(paths[i]));
exoPlayer.setMediaSource(mediaSources);
exoPlayer.prepare();
exoPlayer.setPlayWhenReady(true);
```

**Comment by claincly** [comment]
I'm not sure what is lacking if you modify the `media.exolist.json` file? Is it that you want to play local videos continuously? If that's the case you can take a look at [playlist](https://exoplayer.dev/playlists.html).

**Comment by ojw28** [comment]
See also [this documentation](https://exoplayer.dev/demo-application.html#playing-your-own-content), which includes a description of how to launch the demo app using intents and/or via `adb shell`. That said, you should probably just edit the demo app source code to make it do exactly what you want.

**Comment by dubeyabhijeet** [comment]
@claincly media.exolist.json will stream video from some domain where video are hosted. My requirement is keep videos in phone file manager and run exoplayer . Collect all performance metrics for different type of videos.

**Comment by claincly** [comment]
You can put local file path in media.exolist.json. The player will
recognize it's a local file. Please also see Oliver's comment above.

**Comment by dubeyabhijeet** [comment]
Thanks! Its working.

One more help needed. Is there any open source for secure video content?

**Comment by dubeyabhijeet** [comment]
I mean link which i can add in json to stream secure videos

**Comment by ojw28** [comment]
The DRM systems supported across Android devices are Widevine and ClearKey. They have different characteristics, including the level of security they're able to offer. You'll need to do your own research into this. Thanks!
