### ISSUE TITLE
Live stream buffering

### ISSUE THREAD

**Issue by kalpeshat20** [google/ExoPlayer#9554]
Hi, 

I am working on live stream/radio app, in my case if I pause the stream from PlayerNotificationManager and resume its get started from last index i.e. where ever I had pause.

I want to play the stream from from the latest playing index, from UI am able to achieve that by using seekTo(0) but from notification am not able apply seekTo() method as it cause different behavior.

I want some listener which will help me to apply seekTo(0) method before resuming the stream from PlayerNotificationManager. 

I am using exoplayer version 2.15.1. Please help.

**Comment by claincly** [comment]
@marcbaechinger could you take a look?

**Comment by kalpeshat20** [comment]
Its urgent please provide your feedback.

**Comment by marcbaechinger** [comment]
Can you use a `ForwardingPlayer` to intercept the calls to `play()`?

```
    ForwardingPlayer forwardingPlayer = new ForwardingPlayer(player) {
      @Override
      public void play() {
        player.seekTo(0);
        player.play();
      }
    };
    playerNotificationManager.setPlayer(forwardingPlayer);
```

**Comment by kalpeshat20** [comment]
Tried not working

```
private fun setupNotifications(mediaController: MediaControllerCompat) {

        val forwardingPlayer: ForwardingPlayer = object : ForwardingPlayer(exoPlayer) {
            override fun play() {
                exoPlayer.seekTo(0)
                exoPlayer.play()
            }
        }

        playerNotificationManager = PlayerNotificationManager.Builder(
            this@PlayerService,
            NOTIFICATION_ID,
            CHANNEL_ID
        ).setMediaDescriptionAdapter(DescriptionAdapter(this, mediaController))
            .setNotificationListener(notificationListener)
            .setChannelNameResourceId(R.string.notification_channel)
            .setChannelDescriptionResourceId(R.string.notification_channel_description)
            .build()

        playerNotificationManager.apply {
            setUseNextAction(false)
            setUsePreviousAction(false)
            setUseFastForwardAction(false)
            setUseFastForwardActionInCompactView(false)
            setUseRewindAction(false)
            setUseRewindActionInCompactView(false)
            setUseStopAction(false)
            setColorized(true)
            setPlayer(forwardingPlayer)
            setSmallIcon(R.drawable.ic_music_note_single)
            setVisibility(NotificationCompat.VISIBILITY_PUBLIC)
            setPriority(NotificationCompat.PRIORITY_LOW)
            setUseChronometer(false)
        }
    }
```

**Comment by marcbaechinger** [comment]
Can you put a breakpoint or a logging statement in `play`, `pause` and `playWhenReady` of the `ForwardingPlayer` to see whether one of these methods get called when you use the buttons in the notification? 

It may be tied to the version of the ExoPlayer library which of these methods are called. Please let me know which version you are using in case that does not help.

**Comment by kalpeshat20** [comment]
am using version 2.15.1

**Comment by marcbaechinger** [comment]
Thanks. What did you find when you were investigating the calls in `ForwardingPlayer` with breakpoints or log statements?

**Comment by kalpeshat20** [comment]
logs not getting triggered in `onPlay()` method of `ForwardingPlayer`

**Comment by marcbaechinger** [comment]
Ok. And now try `onPlayWhenReady()`? Accept my apologies if I'm asking for too much. :)   See also the comment [above](https://github.com/google/ExoPlayer/issues/9554#issuecomment-953257418).

**Comment by kalpeshat20** [comment]
No logs

```
val forwardingPlayer: ForwardingPlayer = object : ForwardingPlayer(exoPlayer) {
            override fun play() {
                super.play()
                Timber.d("ForwardingPlayer Play : ")
                exoPlayer.seekTo(0)
                exoPlayer.play()
            }
            override fun pause() {
                super.pause()
                Timber.d("ForwardingPlayer Pause : ")
            }
            override fun getPlayWhenReady(): Boolean {
                Timber.d("ForwardingPlayer getPlayWhenReady : ")
                return super.getPlayWhenReady()
            }
            override fun setPlayWhenReady(playWhenReady: Boolean) {
                super.setPlayWhenReady(playWhenReady)
                Timber.d("ForwardingPlayer setPlayWhenReady : ")
            }
        }
```

**Comment by marcbaechinger** [comment]
If you do a `ForwardingPlayer` and set this player to the `PlayerNotificationManager`, then the forwarding player is called. I have done this several times and it is working.

Closing this issue due to lack of information (minimalistic answers) and lack of activity. Please feel free to reopen if you still have problems and you have investigated this a bit more closely yourself.
