### ISSUE TITLE
MediaQueue: Error fetching queue item ids (error for a local file)

### ISSUE THREAD

**Issue by sanojlawrence** [google/ExoPlayer#9555]
I was working around with exoplayer-cast demo app, And i wanted to play a local mp4 file from my device storage.
The mp4 video was playing on player so i wanted to play on cast, when i tried to mp4 file i get following error.

````
2021-10-11 16:53:22.059 10864-10864/com.example.exoplayercast W/MediaControlChannel: received unexpected error: Invalid Request.
2021-10-11 16:53:22.069 10864-10864/com.example.exoplayercast W/MediaQueue: Error fetching queue item ids, statusCode=2100, statusMessage=null
````

that's the only message am getting in log.

Exoplayer version : 2.15.1

sample file : https://file-examples-com.github.io/uploads/2017/04/file_example_MP4_640_3MG.mp4

DemoUtils: 

````
samples.add(
        new MediaItem.Builder()
            .setUri("/storage/emulated/0/Download/test_sample.mp4")
            .setMediaMetadata(new MediaMetadata.Builder().setTitle("test video").build())
            .setMimeType(MIME_TYPE_VIDEO_MP4)
            .build());
````

i have added `READ_EXTERNAL_STORAGE` in manifest also.

When i remove all other content and tried to play only the local file, i don't get any error and the video is also not playing in cast

````
static {
    ArrayList<MediaItem> samples = new ArrayList<>();

    samples.add(
        new MediaItem.Builder()
            .setUri("/storage/emulated/0/Download/test_sample.mp4")
            .setMediaMetadata(new MediaMetadata.Builder().setTitle("test video").build())
            .setMimeType(MIME_TYPE_VIDEO_MP4)
            .build());

    SAMPLES = Collections.unmodifiableList(samples);
  }
````

**Comment by claincly** [comment]
Playing a local file on cast devices would require a local server to stream the file content to the cast device.

Please see

#7249
#7110
#4995
