### ISSUE TITLE
[Widevine] [MPD Content] No Audio without Headphones

### ISSUE THREAD

**Issue by Taranlayal10** [google/ExoPlayer#9557]
Hi @ojw28 

I have a content that is playing video without any issue but audio is not coming for it. If I play the same content by using any ear phone then I can hear the audio. I have tried the playback in the Sample Exo player as well and observed the same issue. 

Please help with this issue at your earliest.

ExoPlayer Version
2.11.5

I have sent the bug report and adb logs to dev.exoplayer@gmail.com using a subject in the
format "Issue #1234".

**Comment by icbaker** [comment]
Thanks for the bug report - it looks like this was taken from a Pixel (1). Both the bug report and adb logs look like they're running 2.11.0 not 2.11.5:
> 2021-10-12 11:43:37.741 14351-14351/com.google.android.exoplayer2.demo I/ExoPlayerImpl: Init a779ea3 [ExoPlayerLib/2.11.0] [sailfish, Pixel, Google, 29]

> 10-12 11:47:58.122 10188 14351 14351 I ExoPlayerImpl: Release a779ea3 [ExoPlayerLib/2.11.0] [sailfish, Pixel, Google, 29] [goog.exo.core, goog.exo.ui, goog.exo.dash]

I didn't see anything obvious in the bug report that would explain the symptoms you describe. Some follow-up questions:
1. When you say 'using any ear phone', are these bluetooth, wired 3.5mm or wired USB-C headphones?
2. Have you observed the same symptoms on any other devices? If so, which ones?
3. Can you please provide us with content we can use to reproduce the problem? You can email it in the same way you emailed the BR.
4. Do you observe the same problem in the demo app of the latest version of ExoPlayer (2.15.1)?

**Comment by Taranlayal10** [comment]
Hi @icbaker 

Yes the sample I checked on is 2.11.0 and the integrated version in the app is 2.11.5.

This issue seems to be in the EPG side of the content and was resolved automatically without any change on any sides.
If this issue reproduced again then I will reopen this issue and will provide more details that you asked for your help.
