### ISSUE TITLE
CacheDataSource guarantees

### ISSUE THREAD

**Issue by abdallah95** [google/ExoPlayer#956]
hello :-)
if I integrated my datasource inside a cachedatasource...and let's say the range 0-8000 was read at first and it succeeded and then the range 3000-8000 was requested again...does the cachedatasource give any guarantee that the range 3000-8000 will be read from the cache not from the upstream datasource?
another question how BUFFER_SEGMENT_SIZE and BUFFER_SEGMENT_COUNT should be assigned?

**Comment by ojw28** [comment]
CacheDataSource currently only works for bounded range requests. Unless you're implementing VOD DASH this is probably not the type of request that the player is issuing, in which case CacheDataSource may not do any caching at all. There is an issue tracking making CacheDataSource more generally useful (#420).

In general, it's not feasible to make hard guarantees about when cache hits/misses occur. For example, the device might have no free space into which media can be cached. So you should always assume that a request might need to go to the network.
