### ISSUE TITLE
5.1 AAC not correctly decoding on a Sony Bravia TV within ExoPlayer

### ISSUE THREAD

**Issue by ProtoScott** [google/ExoPlayer#9561]
There seems to be a problem with Sony TVs running ExoPlayer that they are not correctly decoding 5.1 AAC as 5.1, other devices all playback 5.1.

- Clear reproduction steps including observed and expected behaviour

Play the 5.1 AAC below in ExoPlayer on a Sony TV connected to an AVR (5.1 home theatre system), observe that the AVR reports that the track is a 2.0 stereo track.

Play the 5.1 AAC below in ExoPlayer on a Chromecast with Google TV connected to an AVR, observe that the AVR reports that the track is 5.1 surround sound.

Play the 5.1 AAC below in the "Media Player" app on a Sony TV connected to an AVR, observe that the AVR reports that the track is 5.1 surround sound.

- URI to test content for reproduction
https://cdn.watchcorridor.com/test/51aac/51aac.mpd
https://cdn.watchcorridor.com/test/51aac/51aac.mp4

- ExoPlayer version number
2.14+ (all 2.x versions we've tested)
- Android version
Android TV 10
- Android device
Sony Bravia VH2 (2020 / 2021 Sony TVs)

**Comment by claincly** [comment]
Can you confirm if the behaviour is observed using our demo app? The demo app running on phones can decode your linked file to 5.1.

Also, please attach a bug report so that we could check for other things, like `MediaCapability`, etc.
