### ISSUE TITLE
Drawable for thumbs up/down icon?

### ISSUE THREAD

**Issue by HectorRicardo** [google/ExoPlayer#9570]
Simple question...do you have a drawable for a thumbs up/down icon?

I was expecting to find those drawables under [/library/ui/src/main/res/drawable-anydpi-v21](https://github.com/google/ExoPlayer/tree/release-v2/library/ui/src/main/res/drawable-anydpi-v21), but I was surprised I didn't, given that those icons are commonly used.

![image](https://user-images.githubusercontent.com/16261233/137549883-dba74639-5ab9-47bc-ad61-d7aab59c5a38.png)

**Comment by moneytoo** [comment]
https://fonts.google.com/icons?selected=Material%20Icons%3Athumb_up%3A

**Comment by tonihei** [comment]
Seems like the question was answered by @moneytoo already. ExoPlayer only includes the icons it needs for its own UI elements. All other UI elements can be taken from elsewhere, like the Material design library linked above.
