### ISSUE TITLE
How to play next video in json inside exoplayer using id 

### ISSUE THREAD

**Issue by Programmingtimes** [google/ExoPlayer#9572]
i have exoplayer powered video app , i would like to play videos in the list but my videos are coming from json file so how i can convert them to list and play it in order. 
for example my cat 1 has 5 video exoplayer must play that 5 video and stop.
then cat 2 have 10 mean it should do same and stop 
[https://github.com/windowschares/charles/blob/main/1/all_movies.json](Json File) 

```
private void playVideo() {
        ExoTrackSelection.Factory videoTrackSelectionFactory = new
                AdaptiveTrackSelection.Factory();
        trackSelector = new
                DefaultTrackSelector(VideoPlayerActivity.this, videoTrackSelectionFactory);
        DefaultRenderersFactory renderersFactory = new DefaultRenderersFactory(this);
        renderersFactory.setExtensionRendererMode(DefaultRenderersFactory.EXTENSION_RENDERER_MODE_PREFER);
        simpleExoPlayer = new SimpleExoPlayer.Builder(this, renderersFactory)
                .setTrackSelector(trackSelector)
                .build();
        videoPlayer.setPlayer(simpleExoPlayer);
        DataSource.Factory dataSourceFactory = new DefaultDataSourceFactory(this,
                Util.getUserAgent(this, "ChristianGospelApp"));
        MediaSource mediaSource = new ProgressiveMediaSource.Factory(dataSourceFactory)
                .createMediaSource(MediaItem.fromUri(Uri.parse(setUpExoplayer)));
        ConcatenatingMediaSource concatenatedSource =
                new ConcatenatingMediaSource(mediaSource, mediaSource);
        simpleExoPlayer.prepare(concatenatedSource);
        simpleExoPlayer.setPlayWhenReady(true);
```

As per suggestions previously i tried with dynamic url by keeping two variable and playing from them but issue is only url I am getting so all other detail in the video remain same 
so i want a good method to play next video in the list comes from JSON file using video id 

` private void getAllMoviesData(Integer categoryId) {

        CompositeDisposable compositeDisposable = new CompositeDisposable();
        compositeDisposable.add(RetrofitClient.getRetroFitClient().getAllCategoryMovies(categoryId)
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribeWith(new DisposableObserver<List<AllCategory>>() {
                    @Override
                    public void onNext(List<AllCategory> allCategoryList) {
                        for (int i = 0; i < allCategoryList.size(); i++) {
                            setMainRecycler(allCategoryList);
                        }

                    }

                    @Override
                    public void onError(Throwable e) {
                        Log.d("bannerData", "" + e);
                    }

                    @Override
                    public void onComplete() {

                    }
                })

        );
    }`
this is how my recycler view get videos

**Comment by tonihei** [comment]
I'm afraid we can't give detailed app development advice if it's not about an ExoPlayer bug or feature request. Loading json lists and handling views is definitely outside the scope of this issue tracker. Please also have a look at our [demo app](https://github.com/google/ExoPlayer/tree/release-v2/demos/main) which already handles loading playlists from json files.

**Comment by Programmingtimes** [comment]
thankyou somuch for reply
