### ISSUE TITLE
How to continue play video segment when audio segment download fail （Dash）

### ISSUE THREAD

**Issue by wangnaiwen** [google/ExoPlayer#9577]
hello guys

We use ExoPlayer to play Dash Stream Files,  In some special scenarios, our streaming files have lost audio segments, I got an 404 errorCode and play error when ExoPlayer can not find the audio segment but video segment is exist,  So we want to continue play video segment when audio segment is not exist, such as VLC media player， Is there any way to configure it, or how to modify it？？ Thank you very much.

**Comment by wangnaiwen** [comment]
[dash_files.zip](https://github.com/google/ExoPlayer/files/7370923/dash_files.zip)

**Comment by tonihei** [comment]
This isn't supported at the moment, but could be solved by #4688 once implemented. I'll mark it as a duplicate.
