### ISSUE TITLE
Retrieve `EssentialProperty` from a DashManifest image Representation

### ISSUE THREAD

**Issue by mestefy** [google/ExoPlayer#9579]
I have the following `AdaptionSet` from a DASH manifest file
```
<AdaptationSet id="3" mimeType="image/jpeg" contentType="image">
      <SegmentTemplate media="template_goes_here">
        <SegmentTimeline>
          <S d="40000" r="126"/>
          <S d="24000"/>
        </SegmentTimeline>
      </SegmentTemplate>
      <Representation id="10" bandwidth="36864" width="1280" height="720" frameRate="0">
        <EssentialProperty schemeIdUri="http://dashif.org/guidelines/thumbnail_tile" value="5x5"/>
      </Representation>
</AdaptationSet>
```
As you can see, it defines the template for images of sizes 1280x720 and in the `Representation` we have an  `EssentialProperty` of value `5x5` which describes the fact that the image is basically an image atlas of 25 images each of 256x144 each.

**Is there a way to retrieve that `EssentialProperty` so that I can display the correct tile from that image?**

I have checked the property `essentialProperties` from the `AdaptionSet` class however it is an empty list and the `Representation.MultiSegmentRepresentation` does not seem to have an `essentialProperties` of it's own, just the `inbandEventStreams` property.

As a side note I have found this related [issue](https://github.com/google/ExoPlayer/issues/9500), however the [fix](https://github.com/google/ExoPlayer/commit/585b0bddcc965e269ad9eb8810b6f8da2b062996) for it seems to just set the image width and height from the representation in the format structure.

Thanks in advance!

**Comment by tonihei** [comment]
Although we parse the values, we currently don't save the result in the `Representation` class. Will mark as an enhancement.

**Comment by tonihei** [comment]
Added support by the commit above.
