### ISSUE TITLE
DRM: Prefetching a Widevine License in a multiperiod MPD

### ISSUE THREAD

**Issue by yotta-raj** [google/ExoPlayer#9581]
How do I request in ExoPlayer to prefetch a license ahead of the new period for a seemless transition from one period to another. 

The situation is that the application can make a request by providing the PSSH to ExoPlayer in order to generate a license request so that the same app can send the license request to the license server and hand the license to ExoPlayer. 

Alternatively ExoPlayer can be instructed to look ahead and utilising session Sharing.

**Comment by icbaker** [comment]
ExoPlayer added support for pre-fetching DRM licenses in 2.14.0 (#4133, [release notes](https://github.com/google/ExoPlayer/blob/release-v2/RELEASENOTES.md#2140-2021-05-13)).

It should mean that the keys are requested when the player starts buffering the upcoming period (which with default settings will generally be about 50s before the playback position reaches it).

Does that answer your question?

If not, could you please provide more detail of what you're expecting, and ideally a test stream we can use in the demo app to reproduce the non-seamless transitions that you're seeing.

**Comment by yotta-raj** [comment]
Thanks for the quick reply, in the #4133 you stated the following; 

> This doesn't help for content with key rotation - so I'll keep the issue open to track implementing proper key-prefetching.

So the upcoming period would be using a different content ID so Encrypted ContentID1 to Encrypted ContentId2. However if ContentID2 required authentication prior to fetching the license, I need to get hold of the licenseRequest message in the app rather than exoplayer trying to fetch it at the buffering point. 

So the application has to do an authentication prior to the period before getting the license to hand back to the Player, but the player does not know what;s coming down the OTA pipe as its LIVE, otherwise the app could get all licenses prior to playback.  

FYI, this use case is for ATSC 3.0 OTA Live Dash encrypted stream using Widevine DRM.

**Comment by icbaker** [comment]
> Thanks for the quick reply, in the #4133 you stated the following;
> 
> > This doesn't help for content with key rotation - so I'll keep the issue open to track implementing proper key-prefetching.

The [comment you quoted](https://github.com/google/ExoPlayer/issues/4133#issuecomment-653560102) is from July 2020. It was referring to https://github.com/google/ExoPlayer/commit/316f8a88cdaeff2b1b5d219097b2739ef607b2c4 which is in 2.12.0. The pre-fetching support I'm referring to above, that landed in 2.14.0 and should work for key-rotated content, is https://github.com/google/ExoPlayer/commit/74ad0949fd09be26bfc60702794d3eb6e8a213e1 and https://github.com/google/ExoPlayer/commit/795ddfee40cba83eba8e9f39da01fba2f1f8775c.

----

> However if ContentID2 required authentication prior to fetching the license, I need to get hold of the licenseRequest message in the app rather than exoplayer trying to fetch it at the buffering point.

ExoPlayer will make all licence requests (both pre-fetches and 'just in time' fetches) using an `MediaDrmCallback` instance. If you need to do additional logic during a license request, you should be able to do so by providing a custom [`MediaDrmCallback`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/drm/MediaDrmCallback.html) implementation when instantiating your `DefaultDrmSessionManager`. You may find it easiest to delegate the actual HTTP requests to [`HttpMediaDrmCallback`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/drm/HttpMediaDrmCallback.html). There's some more info on plumbing in a custom `DrmSessionManager` here: https://exoplayer.dev/drm.html#using-a-custom-drmsessionmanager.

**Comment by yotta-raj** [comment]
So using the custom drmSessionManager, a application can initiate a session, for encrypted content and decrypting the content of a live stream. 
Then let's say in 120s ahead there is a contentID change, so a new session can be created in order to generate a license request, the callback will provide the license request, the application (users may need to do an action in the application) can fetch the license and hand this back to the custom session, then the application and/or exoplay can switch to use the new session when the period arrives at the live point?

**Comment by icbaker** [comment]
I think the information provided above should be enough for you to try this out. If it doesn't work please come back here with specific questions.

**Comment by yotta-raj** [comment]
Thanks Ian. We'll take a look into the custom drmsessionmanager with our 3rd party who are looking into the implementation.
