### ISSUE TITLE
How to play HLS CatchUp fast?

### ISSUE THREAD

**Issue by kocetod** [google/ExoPlayer#9582]
Hello. I have a big problem with HLS Playing in Exoplayer. My CatchUp source is like this below, play after 6 to 10 sec. It is possible to run video after 2-3 sec.? (this is *.m3u8).

#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:10
#EXTINF:10.0000,
http://tshr.aesbg.net:5000/cgi-bin/strm.ts?len=10&ch=3&utc=1634245015
#EXTINF:10.0000,
http://tshr.aesbg.net:5000/cgi-bin/strm.ts?len=10&ch=3&utc=1634245025
#EXTINF:10.0000,
http://tshr.aesbg.net:5000/cgi-bin/strm.ts?len=10&ch=3&utc=1634245035
#EXTINF:10.0000,
http://tshr.aesbg.net:5000/cgi-bin/strm.ts?len=10&ch=3&utc=1634245045
#EXTINF:10.0000,
http://tshr.aesbg.net:5000/cgi-bin/strm.ts?len=10&ch=3&utc=1634245055
#EXTINF:10.0000,
http://tshr.aesbg.net:5000/cgi-bin/strm.ts?len=10&ch=3&utc=1634245065
#EXTINF:10.0000,
http://tshr.aesbg.net:5000/cgi-bin/strm.ts?len=10&ch=3&utc=1634245075
#EXTINF:10.0000,
http://tshr.aesbg.net:5000/cgi-bin/strm.ts?len=10&ch=3&utc=1634245085
#EXTINF:10.0000,
http://tshr.aesbg.net:5000/cgi-bin/strm.ts?len=10&ch=3&utc=1634245095....

**Comment by tonihei** [comment]
If you are talking about the time it takes for playback to start, then this is to a large extent influenced by the time it takes to load these segments over the network. You can try to reduce [bufferForPlaybackMs](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/DefaultLoadControl.Builder.html#setBufferDurationsMs(int,int,int,int)) in the DefaultLoadControl.Builder, which you can provide in the SimpleExoPlayer.Builder.
