### ISSUE TITLE
How to force stop ad in ExoPlayer above 2.12.x

### ISSUE THREAD

**Issue by fredysug** [google/ExoPlayer#9590]
Previously we were using ExoPlayer version 2.11.4 and we had to show custom skip ads button (video ad) in ExoPlayer. When this button is clicked, we will call the "imaAdsLoader.stopAd()" method.

However, after we tried to upgrade ExoPlayer to version 2.13.2, the approach we used no longer works because the "stopAd()" method is no longer available.

We plan to use "adsManager.discardAdBreak()" as an alternative, but we are having trouble getting an instance of AdsManager because "imaAdsLoader.adsLoader" returns null. 

```
...
  imaAdsLoader.adsLoader?.addAdsLoadedListener(
     {
        adsManager = it.adsManager
     }
  )
...

private fun discardAd() {
    adsManager()?.discardAdBreak()
}
```

We also noticed there is another issue thread discussing "imaAdsLoader.adsLoader returns null" but for other purposes (https://github.com/google/ExoPlayer/issues/8565).

Would you tell us the proper way to get an instance of AdsManager so that we can use the "adsManager.discardAd()" method? Or is there another interface/method we can use to only discard current ad?

**Comment by tonihei** [comment]
`imaAdsLoader.stopAd()` was never meant to be a public API as it's just a  IMA internal callback handled by `ImaAdsLoader`. In the past this callback was implemented by `ImaAdsLoader` directly allowing you to call the method, but this moved to an inner class for better encapsulation.

> we had to show custom skip ads button (video ad) in ExoPlayer

Note that customizing the skip button is not generally allowed per IMA policy. See [this thread](https://groups.google.com/g/ima-sdk/c/c9Ed45PedFk/m/6Md7CELQIQAJ) and similar issues like #8098 or #7415.

There is a new option to customize the UI if your Google Ad Manager account is enabled for it (see [here](https://developers.google.com/interactive-media-ads/docs/sdks/android/client-side/custom-ui) for details). We track the necessary ExoPlayer changes to support this in #9504.
