### ISSUE TITLE
RTMP client has been moved to different repository

### ISSUE THREAD

**Issue by menscikov** [google/ExoPlayer#9591]
Hello,

Just wanted to tell that RTMP client is now published here:
https://github.com/ant-media/LibRtmp-Client-for-Android/issues/96#issuecomment-948433592

Please update it, so we can remove `jcenter()`.

**Comment by ojw28** [comment]
Fixed in https://github.com/google/ExoPlayer/commit/2dc7ac38513a7c7eef8f4de9242ec7c5ed2b1029.

**Comment by ojw28** [comment]
And `jcenter()` dependency removed in https://github.com/google/ExoPlayer/commit/647d69b950d9bebb43401cef05f25f40f1ecc3d9.
