### ISSUE TITLE
PlaybackStats information during playback

### ISSUE THREAD

**Issue by imranbuet63** [google/ExoPlayer#9594]
Hi, I am using the player for doing some video analytics research. I am interested in collecting some metrics such as current bitrate, resolution, buffer size, stall event count, stall event duration, mean time between two stalls, etc. I came across the PlaybackStats class. I am not sure how to use it. Can you provide some example code on how to access those variables and wherein the code I should put the logging information? I want the metrics at a finer granularity, not for a whole session. Is it possible to access get the metrics at 1sec granularity?

**Comment by ojw28** [comment]
Analytics functionality is documented in a reasonable amount of detail in the [developer guide](https://exoplayer.dev/analytics.html). I'd suggest giving that page a read. As per that page:

> It’s also possible to query the PlaybackStats for the current playback session at any time using PlaybackStatsListener.getPlaybackStats().

So once you've registered a `PlaybackStatsListener`, you should be able to poll the stats every second using that method.

Note that for your use case, it might be better to implement an `AnalyticsListener` directly, at which point you'll be able to tap into a whole host of events as they occur within the player. You are then free to derive stats based on those events in whatever way you choose, in realtime, during playback. You could look at what the `PlaybackStatsListener` implementation does as some inspiration for how to get started.
