### ISSUE TITLE
How to share the surface between video rendering and canvas drawing?

### ISSUE THREAD

**Issue by robin2046** [google/ExoPlayer#9604]
I am using a framework to develop my app, which I can only have access to a single surface instance.
I need to render video by ExoPlayer to this surface, and also do canvas drawing on it.
These operations are performed time-divided, not simultaneously.

However, I always got the following error from exoplayer

```
`E/SurfaceUtils: Failed to connect to surface 0xb40000712241a960, err -22`
`E/MediaCodec: nativeWindowConnect returned an error: Invalid argument (-22)`
`E/MediaCodec: configure failed with err 0xffffffea, resetting...`
`E/MediaCodecVideoRenderer: Video codec errorcom.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, null, video/avc, avc1.4D401E, -1, null, [640, 800, 29.99915], [-1, -1])`
```

I tried create a simple app like following, which demonstrates using a single surface among following operations:
1. Start ExoPlayer video playback: OK
2. Stop video playback, release exoplayer and perform canvas drawing: OK
3. Stop canvas drawing and try to do video playback again: failed

```
  class SurfaceViewActivity : AppCompatActivity() {
    companion object {
        private const val TAG = "SurfaceActivity"
    }

    private var player: ExoPlayer? = null

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_surface_view)

        startVideoPlaying()

        CoroutineScope(Dispatchers.IO).launch {
            delay(3000L) //Let the video to play 3s

            CoroutineScope(Dispatchers.Main).launch {
                player?.release()
                player = null
            }

            delay(500L)
            val surface = findViewById<SurfaceView>(R.id.surfaceView).holder.surface
            drawColorOnSurface(Color.RED, surface)
            delay(500L)
            drawColorOnSurface(Color.GREEN, surface)
            delay(500L)
            drawColorOnSurface(Color.BLUE, surface)
            delay(500L)

            CoroutineScope(Dispatchers.Main).launch {
                startVideoPlaying()
            }
        }

    }

    private fun drawColorOnSurface(color: Int, surface: Surface) {
        val canvas = surface.lockCanvas(null)
        canvas.drawColor(color)
        surface.unlockCanvasAndPost(canvas)
    }

    private fun startVideoPlaying() {
        player = SimpleExoPlayer.Builder(this, DefaultRenderersFactory(this)).build().apply {
            setVideoSurfaceHolder(findViewById<SurfaceView>(R.id.surfaceView).holder)
            setMediaItem(MediaItem.fromUri(intent.data!!))
            prepare()
            play()
        }
    }

    override fun onDestroy() {
        super.onDestroy()
        player?.release()
    }
}

```

**Comment by ojw28** [comment]
Unfortunately, this is not possible due to a limitation in the underlying platform, described on [this page](https://source.android.com/devices/graphics/arch-sh):

> Caution: You can't draw on a surface with GLES or send it frames from a video decoder if you've ever called lockCanvas(). lockCanvas() connects the CPU renderer to the producer side of the BufferQueue and doesn't disconnect until the surface is destroyed. The canvas-based CPU renderer can't be disconnected and reconnected to a surface, unlike most producers (like GLES or Vulkan).

The only solutions are:

1. To have multiple surfaces, one way or another.
2. Use a non-`MediaCodec` based video decoder that renders to the surface with the CPU renderer. ExoPlayer's VP9 and AV1 decoder extensions allow for this, but this approach is not good for performance, limits you to using VP9 or AV1, and requires bundling a decoder directly into your application.
