### ISSUE TITLE
playback failed on android 11

### ISSUE THREAD

**Issue by zhangyaoo123** [google/ExoPlayer#9612]
when I play a online video which startwith "https"  on android 11 , got error message : com.google.android.exoplayer2.ExoPlaybackException: Source error       error code is 2001
can you help me ? device is Pixel 4a

**Comment by ojw28** [comment]
Hi! Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md). If you're unable to share [bug reports](https://developer.android.com/studio/debug/bug-report) or test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #1234" ("#1234" is replaced with your issue number). Please also update this issue to indicate you've done this.

**Comment by zhangyaoo123** [comment]
hello,I installed the demo app on my Pixel 4a  android 11. open any item such as :
     
![exo1](https://user-images.githubusercontent.com/13558487/139170950-909ea084-6b17-4127-9c57-dd6f29af2b42.jpg)


I will get next error message:
![exo2](https://user-images.githubusercontent.com/13558487/139170990-ed3a6cac-8c69-4242-81df-da436c4bc8b6.jpg)

**Comment by ojw28** [comment]
`ERR_CERT_DATE_INVALID` indicates that the device thinks the server's SSL certificate has expired.

It should be noted that your device will probably use its clock to determine whether the certificate has expired, and judging by the logging you've provided, your device clock seems to be set incorrectly (`2021-05-11`). So you may well find that setting the device clock to the correct date and time will resolve this.

If that's not the case, then the server's SSL certificate has probably actually expired. Either way, I don't think this is an ExoPlayer issue.
