### ISSUE TITLE
How can i play RTSP stream without audio codecs?

### ISSUE THREAD

**Issue by LostInAbyss** [google/ExoPlayer#9614]
How can i play RTSP stream without audio codecs? I need only video?I can't start watch stream because camera using g.711 for audio.

**Comment by claincly** [comment]
The player drops the formats that it cannot play and plays the playable formats only. In your case, G711 will be automatically dropped and the player should start playing video only.

Please comment if that's not the case.

**Comment by LostInAbyss** [comment]
Thanks for answer!

**Comment by claincly** [comment]
I'm closing it for now, please feel free to re-open.
