### ISSUE TITLE
Exoplayer getDuration returns a wrong duration

### ISSUE THREAD

**Issue by Suleiman-Ahmad** [google/ExoPlayer#9618]
I use Exoplayer to play local videos but calling getDuration returns a wrong (very large) duration for some videos. It also displays the same wrong duration on a textview with the ID exo_duration.
This issue is explained in detail here https://github.com/google/ExoPlayer/issues/9593 but I've received no answers yet.
Please use the video file in that issue since it produces the same error.

**Comment by ojw28** [comment]
> This issue is explained in detail here #9593 but I've received no answers yet.

If you have already posted the issue, please refrain from filing additional issues about the same thing. Closing as a duplicate.

**Comment by Suleiman-Ahmad** [comment]
Okay, but please go through https://github.com/google/ExoPlayer/issues/9593. It's been several days now.
