### ISSUE TITLE
Build instructions for extensions for Apple M1 (ARM chips)

### ISSUE THREAD

**Issue by menscikov** [google/ExoPlayer#9621]
As you probably know, Apple has moved away from Intel systems to its M1.
I would like to move from my old MacBook to the new MacBook M1 soon.
Is it possible to add build instructions for extensions such as ffmpeg, av1, vp9, etc.?
Or this can't be done on the new M1 (ARM) at this moment?

**Comment by AquilesCanta** [comment]
The ExoPlayer build system is host-agnostic. The host-dependency stems from the NDK, which needs a host to be specified. The current possible hosts are documented here: https://developer.android.com/ndk/guides/other_build_systems. I believe `darwin-x86_64` should just work. Is that not the case? Is this a concrete issue or are you anticipating the possiblity of the build not working?

**Comment by menscikov** [comment]
I don't own MacBook with M1 yet, but i think that it won't build with "darwin-x86_64", because new Apple chip is totally different from Intel.
It's "ARMv8.4-A" according to [Wikipedia](https://en.wikipedia.org/wiki/Apple_M1).

Android NDK for M1 is not available yet also.
It is possible to use Android NDK (darwin-x86_64) only with Apple emulator "Rosetta 2".

Maybe someone already had experience compiling these extensions with Apple M1?

**Comment by AquilesCanta** [comment]
> i think that it won't build with "darwin-x86_64", because new Apple chip is totally different from Intel.

There's nothing for us to do here, until we know for certain it doesn't work. It's worth tracking https://github.com/android/ndk/issues/1299, too. If someone has issues building the extensions in a new mac, we can reopen this.
