### ISSUE TITLE
how to prevent the autoplay after setMediaItem?

### ISSUE THREAD

**Issue by TracyZhangLei** [google/ExoPlayer#9623]
library version is 2.15.1

when a music is played to the end, then i set another music using setMediaItem,  it plays automatically which is not expected.
setPlayWhenReady(false) not work. 
how can i prevent the autoplay after setMediaItem?

**Comment by ojw28** [comment]
I tried letting a playback transition to the ended state, and then calling:
```
player.setPlayWhenReady(false);
player.setMediaItem(MediaItem.fromUri(" some new uri "));
```
It worked as expected (i.e., it did not automatically start playing). I tested this with 2.15.1.

So I cannot reproduce the issue. Please provide more concrete reproduction steps, ideally as a small patch to our demo application, if you'd like us to investigate further.
