### ISSUE TITLE
Prevent audio player recording

### ISSUE THREAD

**Issue by preetiworkplace** [google/ExoPlayer#9624]
I am using exoplayer to play my audio files. These audio files are paid.  I want to prevent my audio if third-party app starts recording the app using a screen recorder. I used android:allowAudioPlaybackCapture="false , also set audio capture policy but its not working. 

Is there any method provided by exoplayer to achieve this?

**Comment by ojw28** [comment]
I think `android:allowAudioPlaybackCapture="false"` should be sufficient to stop a third party app capturing audio from your app. It's unclear what you mean by "if third-party app starts recording the app using a screen recorder". Please could you clarify, and provide a concrete example of an application that's able to capture your app's audio despite having set this.

It should be noted that someone who wants to capture your audio could just plug a recording device into the headphone jack, and do it that way, so in general it's not really possible to protect your audio from a determined attacker. I think the industry largely moved away from trying to do this years ago, in favour of providing streaming services that are sufficiently polished and convenient that consumers are willing to pay for them.

**Comment by preetiworkplace** [comment]
I am playing the number of the audio file. I also set Window flag Secure to achieve this. below is my sample code
```
  val videoTrackSelectionFactory: TrackSelection.Factory =
                AdaptiveTrackSelection.Factory(DefaultBandwidthMeter())
        val trackSelector: TrackSelector = DefaultTrackSelector(videoTrackSelectionFactory)
        val loadControl: LoadControl = DefaultLoadControl()
        val audioAttributes: AudioAttributes =
                AudioAttributes.Builder()
                        .setAllowedCapturePolicy(ALLOW_CAPTURE_BY_NONE)
                        .setUsage(C.USAGE_MEDIA)

                        .setContentType(C.CONTENT_TYPE_MOVIE)
                        .build()

        exoPlayer = ExoPlayerFactory.newSimpleInstance(this, trackSelector, loadControl)
        val dataSourceFactory =
                DefaultDataSourceFactory(this, Util.getUserAgent(this, "exoplayer2example"), null)
        val extractorsFactory: ExtractorsFactory = DefaultExtractorsFactory()
        val audioSource: MediaSource =
                ExtractorMediaSource(uri, dataSourceFactory, extractorsFactory, null, null)
        exoPlayer.audioAttributes = audioAttributes
        exoPlayer.prepare(audioSource)
```
When I do screen recording using third party app like Xrecorder.  On recording black window get captured but I am able to listen audio files. I have disable the screen recording .

**Comment by ojw28** [comment]
Xrecorder appears to just be using the device microphone to record sound. This will capture the audio being played out of the device speaker, but it will also capture all other ambient sound in the environment as well (e.g., if you talk whilst trying to reproduce this, you'll hear your own voice in the Xrecorder captured video). Similarly, if you're using headphones, you wont hear the audio that's being played, since the microphone wont be able to pick it up.

There's fundamentally nothing that can prevent someone using a microphone to record audio being played out of a speaker.
