### ISSUE TITLE
How to make RadioButton instead of CheckBox in change quality of video source over player

### ISSUE THREAD

**Issue by sojolrana** [google/ExoPlayer#9634]
I want to know that how can I use RadioButton instead of CheckBox when I change the quality of video in Exoplayer

**Comment by icbaker** [comment]
Assuming you're asking about the UI built by [`TrackSelectionDialogBuilder`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/ui/TrackSelectionDialogBuilder.html), you can switch from checkboxes to radio buttons by passing `false` to [`setAllowAdaptiveSelections`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/ui/TrackSelectionDialogBuilder.html#setAllowAdaptiveSelections(boolean)).

If this doesn't answer the question then please clarify which UI element you're asking about (possibly by attaching a screenshot).

**Comment by sojolrana** [comment]
@icbaker Thanks for your response. Look at the image, which I mean
![IMG_20211101_224445](https://user-images.githubusercontent.com/48207446/139708401-5b9e605d-27fd-436c-a76f-cf214a71e7b8.jpg)

**Comment by icbaker** [comment]
The left hand screenshot looks like the UI that `TrackSelectionDialogBuilder` produces, so my answer above should apply.

**Comment by sojolrana** [comment]
I want to know, how can I turn that UI with the right-hand screenshot?
