### ISSUE TITLE
seekbar time not correct 

### ISSUE THREAD

**Issue by aungxinmoe** [google/ExoPlayer#9637]
player show  video time wrong and seekbar not correct time.

**Comment by icbaker** [comment]
Hi! Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md). If you're unable to share [bug reports](https://developer.android.com/studio/debug/bug-report) or test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format `Issue #1234` (`#1234` is replaced with your issue number). Please also update this issue to indicate you've done this.

**Comment by aungxinmoe** [comment]
Video Duration not set correctly (exoplayer2)

player show video time wrong and seekbar not correct time forward.Example video real time is 52:01 but seekbar and time show 32:02.

ExoPlayer version number
2.15.1
Android version
9
Android device
Mi Note 3

**Comment by icbaker** [comment]
Please provide media we can use to reproduce this problem in the [ExoPlayer demo app](https://exoplayer.dev/demo-application.html). Please either upload it here or send to dev.exoplayer@gmail.com using a subject in the format `Issue #1234` (where `#1234` should be replaced with this issue number.) Please also update this issue to indicate you’ve done this.

**Comment by aungxinmoe** [comment]
i send email to dev.exoplayer@gmail.com

**Comment by icbaker** [comment]
I can reproduce the issue in the 2.15.1 demo app by directly playing the URL provided. When playback reaches 32:02 it continues past that point.

I'd like to get a local copy of the video in order to inspect it using https://gpac.github.io/mp4box.js/test/filereader.html. However when I try and download this file in Chrome it hangs at 8MB (of 517MB) and when I `curl` it the connection is closed after transferring 20MB. Please can you provide a link I can use to obtain a local copy of the entire file, so that I can inspect it.

**Comment by aungxinmoe** [comment]
i replied resend link your email.

**Comment by icbaker** [comment]
The new link returns an HTTP 404 error.

**Comment by aungxinmoe** [comment]
i replied again new link.

**Comment by icbaker** [comment]
This is the same issue as https://github.com/google/ExoPlayer/issues/9593. See screenshot attached, and compare to the screenshot and analysis by @ojw28 in https://github.com/google/ExoPlayer/issues/9593#issuecomment-956186528.

The 32:02 number is coming from the media, so closing as 'bad media'.

![Screenshot 2021-11-01 at 17 10 50](https://user-images.githubusercontent.com/1279752/139711783-292bb36c-d1e5-4bf8-a9df-99cb10b33061.png)

**Comment by Suleiman-Ahmad** [comment]
Is there a way to manually set the duration ourselves?
