### ISSUE TITLE
SmoothStreaming AES Support

### ISSUE THREAD

**Issue by SachiraChin** [google/ExoPlayer#964]
I've recently worked with SharePoint Video API which only provides AES encrypted videos. This API uses Azure Media Services to stream videos. Only two options available are

- HLS + AES
- Smooth Streaming + AES

For HLS, even though it has AES implemented, because of multitrack audio issue, it does not work properly. If you can implement AES Smooth Streaming, it will be big win for this scenario. 

I have attached Smooth Streaming manifest which we get from the server. 
[Manifest.txt](https://github.com/google/ExoPlayer/files/36553/Manifest.txt)

Note the Protection element in manifest, it's as below.

```
        <Protection>
            <ProtectionHeader SystemID="B47B251A-2409-4B42-958E-08DBAE7B4EE9">
                <ContentProtection schemeIdUri="urn:mpeg:dash:sea:2012" xmlns:sea="urn:mpeg:dash:schema:sea:2012">
                    <sea:SegmentEncryption schemeIdUri="urn:mpeg:dash:sea:aes128-cbc:2013" />
                    <sea:KeySystem keySystemUri="urn:mpeg:dash:sea:keysys:http:2013" />
                    <sea:CryptoPeriod IV="0x178BB7E6F004F334F6D0E29371FE74EF" keyUriTemplate="https://cvprbl201m01.keydelivery.mediaservices.windows.net/?kid=433c74f3-28fb-4795-9c22-d0447b9a6c4c" />
                </ContentProtection>
            </ProtectionHeader>
        </Protection>
```

I myself tried few things for this, one thing I observed was SystemId *B47B251A-2409-4B42-958E-08DBAE7B4EE9* does not supported by *MediaDrm* of Android. But I didn't had enough knowledge to continue working on it further.

One more thing needed for this is the access token to decrypt data. To get Manifest url and the token, I wrote sample application. If needed, I can share the sample application and credentials to use application with you.

One more option to get sample manifest and token is to use below article.

[https://msdn.microsoft.com/en-us/office/office365/api/video-rest-operations](https://msdn.microsoft.com/en-us/office/office365/api/video-rest-operations)

You can get manifest from [this section](https://msdn.microsoft.com/en-us/office/office365/api/video-rest-operations#VideooperationsGetinformationaboutplayingavideo) and token from section immediate after that.

Hope you have enough information here. Please let me know anything else needed.

**Comment by SachiraChin** [comment]
@ojw28 If you can give any hints or places to look at, I can try implement this. Thanks.

**Comment by ojw28** [comment]
Sorry, I don't think we have a plan to ever support this. We already support Widevine and PlayReady DRM protection for SmoothStreaming (although the latter is limited to AndroidTV). I don't think there's sufficient demand to make this feature worthwhile, since it's not in line with how the majority of the industry is delivering DRM protected content. The industry does not appear to be moving in this direction either.

**Comment by ojw28** [comment]
To answer your question - You are of course welcome to dig around in the source code and figure it out, but we can't really provide assistance with this. Sorry.
