### ISSUE TITLE
White screen after click on setting before loading the source in Exoplayer

### ISSUE THREAD

**Issue by sojolrana** [google/ExoPlayer#9642]
I have implemented Exoplayer on my Live TV app. But when I click the setting icon (which will change the video quality from the source) before loading the source URL, the screen will white and after that automatically return to the home screen. But if I wait for full loading even if video buffering, setting icons work perfectly. For my question clarification, I added an image.
![PicsArt_11-02-03 43 30](https://user-images.githubusercontent.com/48207446/139806336-5bd93025-219d-4227-b3c4-8f708ccb282d.jpg)

Here is the java code of settings button:
```imgAudio.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                MappingTrackSelector.MappedTrackInfo mappedTrackInfo;
                DefaultTrackSelector.Parameters parameters = trackSelector.getParameters();
                TrackSelectionDialog trackSelectionDialog =
                        TrackSelectionDialog.createForTrackSelector(
                                trackSelector,
                                /* onDismissListener= */ dismissedDialog -> {
                                });
                trackSelectionDialog.show(getSupportFragmentManager(), null);
            }
        })```

and the XML layout code:
```<ImageView
            android:id="@+id/img_audio"
            app:srcCompat="@drawable/ic_settings_white"
            android:layout_width="35dp"
            android:layout_height="35dp"
            android:padding="5dp"/>```

How can I solve this problem?

**Comment by icbaker** [comment]
There's no way for us to help with this issue without being able to reproduce the problem.

Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that demonstrates the problem in a way that we can build locally. 

This could be an Android Studio project on GitHub, or zipped up and sent to dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Please also update this issue to indicate you’ve done this.
