### ISSUE TITLE
Seek in pause in tunneling mode doesn't refresh frame

### ISSUE THREAD

**Issue by zubcoco** [google/ExoPlayer#9646]
Hello,

With the ExoPlayer demo app, version 2.15.1, we have a problem when activating tunneling mode.

Reproduction steps :
 - Add setTunnelingEnabled(true) on the DefaultTrackSelector on the ExoPlayer demo app
 - Launch ExoPlayer demo app
 - Start stream (i.e. Clear DASH - HD (MP4, H264)
 - Paus stream
 - Seek (-5/+15)

When we seek, the displayed frame isn't updated.
But when we've tested without tunneling mode, it works well, the frame is updated after each seek.
We have launched our tests on a Technicolor (Android version 9) box and a Sony TV (Android version 8) and they both have the problem.

Do you have an idea to improve this behavior ?

Thanks,

**Comment by krocard** [comment]
ExoPlayer doesn't currently support this feature for tunneling. Marking as enhancement. A feasibility study is needed first to determined if the tunneling SDK API support it.

**Comment by zubcoco** [comment]
Ok! Thanks for replying.
While waiting for a possible fix, is there a workaround for this problem?

**Comment by krocard** [comment]
I discussed it further, and this is a platform limitation. Supporting this is on Android's roadmap but devices won't support it until the next Android release at the earliest.

**Comment by krocard** [comment]
I'll close this issue as this is an Android platform limitation not an ExoPlayer one.
