### ISSUE TITLE
[dev branch] H262 support - pixelWidthHeightRatio bug

### ISSUE THREAD

**Issue by jacktech24** [google/ExoPlayer#965]
You have bugs in H262 support added in dev branch today, first the pixelWidthHeightRatio is calculated incorrectly, you have: 
```java
switch(aspectRatioCode) {
      case 2:
        pixelWidthHeightRatio = (3 * width) / (float) (4 * height);
        break;
      case 3:
        pixelWidthHeightRatio = (9 * width) / (float) (16 * height);
        break;
      case 4:
        pixelWidthHeightRatio = (100 * width) / (float) (121 * height);
        break;
      default:
        // Do nothing.
        break;
    }
```

but it should be
```java
switch(aspectRatioCode) {
      case 2:
        pixelWidthHeightRatio = (4 * height) / (float) (3 * width);
        break;
      case 3:
        pixelWidthHeightRatio = (16 * height) / (float) (9 * width);
        break;
      case 4:
        pixelWidthHeightRatio = (121 * height) / (float) (100 * width);
        break;
      default:
        // Do nothing.
        break;
    }
```
i can provide an example video so you can see it

**Comment by Avetri** [comment]
How to made according to the standard:
<pre>
...
//                    If there no sequence_display_extension()
//                                horizontal_size
//                    SAR = DAR × ---------------
//                                vertical_size
//
//                    aspect_ratio_information  Sample Aspect    Ratio DAR
//                                0000              forbidden      forbidden
//                                0001             1,0 (Square
//                                                   Sample)           -
//                                0010                  -             3÷4
//                                0011                  -             9÷16
//                                0100                  -             1÷2,21
//                                0101                  -           reserved
//                                ...                                 ...
//                                1111                  -           reserved
                    float DAR[] = {-1f, -1f, 3f/4f, 9f/16f, 1f/2.21f};


                    float pixelWidthHeightRatio = 1.0f;
                    if (seqHeader.getAspectRatioInformation()>=2 || seqHeader.getAspectRatioInformation()<=4)
                    {
                        pixelWidthHeightRatio = DAR[seqHeader.getAspectRatioInformation()]*((float)seqHeader.getHorizontalSizeValue()/(float)seqHeader.getVerticalSizeValue());
                    }
...
</pre>

**Comment by ojw28** [comment]
I'm slightly unclear why you think the existing code doesn't match the spec. Looking just at the first case in the existing code:

```
pixelWidthHeightRatio = (3 * width) / (float) (4 * height);
```

Which (ignoring floating point considerations) is the same as `(3/4)*(width/height)`, where `3/4` is the correct `DAR` value, and `width/height` is `horizontal_size/vertical_size`.

Did I misunderstand something? Also, do you have sample content with non-square samples that you could share? I have a sample that has `aspectRatioCode = 3`, but the pixels are still square, meaning that both code blocks produce an identical result (i.e. It's not a useful sample :)).

**Comment by Avetri** [comment]
@ojw28 Hi.
If did You ask me it is just a sample. And I am not in a condition to answer You completely.

The main goal is the first line <b>according to the standard</b> and the third one <b>If there no sequence_display_extension()</b>.

**Comment by ojw28** [comment]
Oh. I think you're suggesting it's wrong because `SAR` is actually defined as `vertical/horizontal`, where-as `pixelWidthHeightRatio` is a `horizontal/vertical` value?

**Comment by ojw28** [comment]
We'll push a fix for this. Thanks.
