### ISSUE TITLE
Redmi note 8 pro  突然 无法播放视频连接，也不报错误信息  

### ISSUE THREAD

**Issue by roger54920** [google/ExoPlayer#9651]
Unfortunately we can't answer all questions. Unclear questions or questions with
insufficient information may not get attention.

Before filing a question:
-------------------------

2021.11.4 号13点时，可以正常使用，突然下一秒就无法使用了，未修改过代码

**Comment by icbaker** [comment]
Hi! Please provide complete information as requested in the question template. The template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/question.md).

Unfortunately we can't answer unclear questions or those with insufficient information.
