### ISSUE TITLE
playerNotificationManager.setPlayer(null) throws error

### ISSUE THREAD

**Issue by SiddhiBlackLotus** [google/ExoPlayer#9652]
playerNotificationManager.setPlayer(null) java.lang.IllegalStateException. Im not running the player in main thread.

**Comment by icbaker** [comment]
> Im not running the player in main thread.

If you're using ExoPlayer's UI components you must always access the player from the main thread. From our [dev guide](https://exoplayer.dev/hello-world.html#a-note-on-threading):
> Using the application’s main thread is a requirement when using ExoPlayer’s UI components or the IMA extension.
