### ISSUE TITLE
Language Key from .m3u8 file doesn't match language key in track group

### ISSUE THREAD

**Issue by tinder-sophiafrench** [google/ExoPlayer#9656]
In my .m3u8 file, I have a track for subtitles in Indonesian, with language key "id". 
It looks like this: 
`#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID="subs",NAME="Indonesian",DEFAULT=NO,AUTOSELECT=YES,FORCED=NO,LANGUAGE="id",URI="main_id.m3u8"`

After it's parsed into the player's track group, the language key is "ms-ind-d"
It looks like this: 
`Format(subs:Indonesian _ Indonesia, Indonesian _ Indonesia, application/x-mpegURL, text/vtt, null, -1, ms-ind-id, [-1, -1, -1.0], [-1, -1])`

The same thing happens with Norwegian. The language key in the .m3u8 file is "nb", but when it's parsed by the player, it becomes "no-nob".

Why does this happen?

**Comment by tonihei** [comment]
> Language Key from .m3u8 file doesn't match language key in track group

The reason why this happens in general is to allow comparison between values and ensuring everything is in the same format. ExoPlayer receives language keys from at least 3 different sources: The media itself (like the m3u8 file), user preferences that are set in the parameters (e.g. TrackSelectionParameters.preferredAudioLanguages) and also system Locale information. All 3 sources use potentially different formats and standards to represent a language, so we normalize all language input to a consistent format. 

> "id" to "ms-ind" and "nb" to" no-nob"

Our chosen standardization format is ISO 639-1, including mapping all existing individual language codes within a macrolanguage to the equivalent full macrolanguage code. The macrolanguage code is the most modern representation and the only one we can easily use for normalization from all variants. For example, "id" is a code that was defined for Indonesian originally, but then the standardization body later introduced "ms" for the Malayan macrolanguage Indonesion is part of. So we map "id" to "ms-ind" and other deprecated codes like "in", "ind" are also mapped to "ms-ind".  The same happens for "nb", "nob" and "no-bok", which are all mapped to its full modern macrolanguage code of "no-nob".

**Comment by tinder-sophiafrench** [comment]
Thank you for the explanation.
