### ISSUE TITLE
Android 11 AAC playback is choppy

### ISSUE THREAD

**Issue by dhcracchiolo** [google/ExoPlayer#9657]
I'm using the Just Audio package in Flutter which uses Exoplayer for the Android implementation.  I've spoken with the creator of the package and he's convinced it doesn't' have anything to do with his code but that the problem is within Exoplayer.  It doesn't matter if it's played from a local asset or from the network.  All AAC sounds terrible on every Android 11 device I have tried including real devices and emulators.
To recreate the issues just stream this file with Exoplayer:
https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview125/v4/e8/28/29/e828299c-cea7-dd3e-8612-77a632bd60e3/mzaf_7797752939119995161.plus.aac.p.m4a

The problem is definitely in Android 11.  Every other version of Android is totally fine.
Any ideas?

**Comment by christosts** [comment]
I tested this on a Pixel 3a and a Pixel 3 emulator both on Android 11 with ExoPlayer 2.16, and did not hear a problem. Also compared with Pixels 3 & 4 on Android 12, but I could not spot a difference. 

May I ask more details on you setup? Which specific Android 11 devices did you use? Was the emulator for a specific device? 

> To recreate the issues just stream this file with Exoplayer

Does this mean you tried streaming the file with the ExoPlayer demo app? If yes, what version? If no, can you please try so?
