### ISSUE TITLE
Subtitles stopped working in 2.16.0

### ISSUE THREAD

**Issue by bhjortsberg** [google/ExoPlayer#9658]
I'm using StylePlayerView for selecting subtitles in the player.
On 2.15.1 everything worked fine. On 2.16.0 selecting subtitles seems broken. Selecting the first subtitle in the list seem to work a few times (ie. going subtitle1 -> none -> subtitle1 -> none -> subtitle1 will also not work after a few switches). Selecting any subtitle but the first has no effect.

Examples where it does not work:
https://devstreaming-cdn.apple.com/videos/streaming/examples/bipbop_16x9/bipbop_16x9_variant.m3u8
https://storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd
https://media.axprod.net/TestVectors/v7-Clear/Manifest_MultiPeriod_1080p.mpd

I've been running this on Android 11 - OnePlus Nord and Android 12 - Pixel3a Android Emulator.

**Comment by moneytoo** [comment]
It's a bug in 2.16.0: #9649

**Comment by bhjortsberg** [comment]
Ah, missed that. Thanks for the fix!
