### ISSUE TITLE
MPEGTS seeking capability

### ISSUE THREAD

**Issue by abdallah95** [google/ExoPlayer#966]
Hello...why isn't possible to seek a MPEGTS stream? MPEGTS is providing a great advantage for my application but the drawback is that I'm not able to seek. My case is that I'm streaming MP4 through UDP, and some packets might get dropped so instead of re-transmission I replace the dropped frame by an old frame but doing this is causing problem with Exoplayer(the video doesn't even play) unless I used MPEGTS container format where it distorts as expected but at least it continues playing.

**Comment by abdallah95** [comment]
I will take a look into HLS if I could do a work around. 
Well it will only be possible to seek backward and not forward using a cache.
I'm replacing frames because I cannot skip frames, and I guess this should be the case when live streaming, and my case is that I'm not using a media source from which to request the data at anytime, request happens only once and then data transmission starts through UDP until end of stream is reached.

**Comment by Avetri** [comment]
Indexing of TS files there are In solutions like DVR. So, if somebody would be so interested, an indexer might help.

**Comment by abdallah95** [comment]
Actually I already worked on it and used PCR value in the TS packet header for indexing. You can take a look at it on pull request #1274

**Comment by ojw28** [comment]
Now supported in `dev-v2`.
