### ISSUE TITLE
getPlayerError() should be annotated @Nullable

### ISSUE THREAD

**Issue by hnljp** [google/ExoPlayer#9660]
ExoPlayer version number : 2.16.0

https://github.com/google/ExoPlayer/blob/7fe9ecc1c592b758e76f6b458e0dc43cce282e5f/library/core/src/main/java/com/google/android/exoplayer2/ExoPlayer.java#L985

getPlayerError() should be annotated @Nullable

See Player:
https://github.com/google/ExoPlayer/blob/7fe9ecc1c592b758e76f6b458e0dc43cce282e5f/library/common/src/main/java/com/google/android/exoplayer2/Player.java#L1721

**Comment by tonihei** [comment]
Thanks, it should be @Nullable indeed.

**Comment by tonihei** [comment]
Fixed by the commit above.
