### ISSUE TITLE
Switching between encrypted streams

### ISSUE THREAD

**Issue by SnowcatSVK** [google/ExoPlayer#967]
Hello,
I have encountered a problem while switching between encrypted HLS streams after upgrading to ExoPlayer 1.5.2 from 1.4.1, I am switching between streams as advised in question #931
Switching between non-encrypted streams is fine, also between encrypted and non-encrypted. But when switching between encrypted streams i get this exception

```java
11-18 13:32:27.926 13748-13847/? E/LoadTask: Unexpected exception loading stream
11-18 13:32:27.926 13748-13847/? E/LoadTask: java.lang.IllegalArgumentException
11-18 13:32:27.926 13748-13847/? E/LoadTask:     at com.google.android.exoplayer.util.Assertions.checkArgument(Assertions.java:39)
11-18 13:32:27.926 13748-13847/? E/LoadTask:     at com.google.android.exoplayer.util.ParsableByteArray.setPosition(ParsableByteArray.java:133)
11-18 13:32:27.926 13748-13847/? E/LoadTask:     at com.google.android.exoplayer.util.ParsableByteArray.skipBytes(ParsableByteArray.java:145)
11-18 13:32:27.926 13748-13847/? E/LoadTask:     at com.google.android.exoplayer.extractor.ts.TsExtractor.read(TsExtractor.java:141)
11-18 13:32:27.926 13748-13847/? E/LoadTask:     at com.google.android.exoplayer.hls.HlsExtractorWrapper.read(HlsExtractorWrapper.java:240)
11-18 13:32:27.926 13748-13847/? E/LoadTask:     at com.google.android.exoplayer.hls.TsChunk.load(TsChunk.java:108)
11-18 13:32:27.926 13748-13847/? E/LoadTask:     at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
11-18 13:32:27.926 13748-13847/? E/LoadTask:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
11-18 13:32:27.926 13748-13847/? E/LoadTask:     at java.util.concurrent.FutureTask.run(FutureTask.java:234)
11-18 13:32:27.926 13748-13847/? E/LoadTask:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
11-18 13:32:27.926 13748-13847/? E/LoadTask:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
11-18 13:32:27.926 13748-13847/? E/LoadTask:     at java.lang.Thread.run(Thread.java:841)
```

I have tried to track down the issue and found out that TS Extractor is trying to skip adaptation field longer than the size of tsPacket Buffer:

```java
11-18 13:32:27.625 13748-13773/? E/null check: position: 5, bytes: 7, limit: 188
11-18 13:32:27.625 13748-13773/? E/null check: position: 6, bytes: 1, limit: 9
11-18 13:32:27.625 13748-13773/? E/null check: position: 9, bytes: 0, limit: 9
11-18 13:32:27.625 13748-13748/? E/Status: preparing
11-18 13:32:27.896 13748-13847/? E/null check: position: 5, bytes: 10, limit: 188
11-18 13:32:27.926 13748-13847/? E/null check: position: 5, bytes: 185, limit: 188
```

where preparing is status of player after switching and bytes is the number if bytes extractor is trying to skip. This never happened while i was using version 1.4.1. Encryption is standard AES so it should be replicable with any encrypted HLS streams.

**Comment by ojw28** [comment]
You're probably not fully rebuilding the renderers when you switch. You shouldn't re-use any objects that you used to build one set of renderers when building the next set, particularly things like DataSource instances. Is it possible that you are re-using them? If so, try not doing so.

**Comment by SnowcatSVK** [comment]
Well, i am using DemoPlayer and HLSRendererBuilder from demo directory in project, these are the methods i am using for switching:

```java
private HlsRendererBuilder createRenderer() {
        String userAgent = Util.getUserAgent(this, "ExoplayerTest");
        return new HlsRendererBuilder(this, userAgent, contentUri.toString());
    }

    private void preparePlayer() {
        if (player == null) {
            player = new DemoPlayer(createRenderer());
            player.addListener(this);
            player.setCaptionListener(this);
            player.setMetadataListener(this);
            playerNeedsPrepare = true;

        }
        if (playerNeedsPrepare) {
            player.prepare();
            playerNeedsPrepare = false;
        }
        player.setSurface(surfaceView.getHolder().getSurface());
        player.setPlayWhenReady(true);
    }

    private void releasePlayer() {
        if (player != null) {
            //playerPosition = player.getCurrentPosition();
            player.release();
            player = null;

        }
    }
```

and this is the way i am using those methods: 

```javascript
    releasePlayer();
    preparePlayer();
```

only thing i am reusing is surfaceView, unless there is something in DemoPlayer and HLSRendererBuilder that i have missed, but that shouldn't be the case since it never happened with nonencrypted streams

**Comment by ojw28** [comment]
If that's the case then the two playbacks should be completely independent to one another. It's pretty much equivalent to backing out of playback in the demo activity and selecting another sample. In which case I don't understand how one playback could affect the next (at a theoretical level)?

Can you modify the demo app in some way to reproduce the issue? And if so, can you upload it to GitHub so that we can reproduce ourselves?

**Comment by SnowcatSVK** [comment]
I have my whole project in private repository on GitHub, i can privately send you link to that repository so you can test it yourself

**Comment by ojw28** [comment]
The issue is related to the way that you've made `HlsChunkSource.encryptionKeyUri`static in your branch. The breaks the assumption that the second playback is independent of the first, because state is being left lying around from the first playback in the static variable. If I null it out where the player is released, then the second playback works fine.

So the conclude - It looks like an issue with your local modifications. As a general style point, it's worth exploring solutions that don't require statics except in the specific case of singletons (which definitely isn't the case for this particular variable). I also noticed some interesting code in User.java where initSingletons re-initializes singletons potentially multiple times, which looks wrong to me.

**Comment by SnowcatSVK** [comment]
Thank you very much for help, I must have left it there from the time when I was trying different solutions and forgot about it, shame I couldn't find it myself, as for User.java, this is a recycled class from an older project written by different developer, I have recycled it as it was working well with our API and I needed to get going fast with testing, this project was just for testing purposes, so I am completely rewriting it since all of the issues are resolved now.
