### ISSUE TITLE
Why InitializationVector consists of an 8-byte nonce and an 8-byte counter 

### ISSUE THREAD

**Issue by syg4806** [google/ExoPlayer#9670]
AesFlushingCipher get instance with "AES/CTR/NoPadding" and initialize with IV via getInitializationVector()
But getInitializationVector's parameters are long nonce which is an 8-byte and long counter which is an 8-byte.
It means, the Initialization Vector consists of an 8-byte nonce and an 8-byte counter.
But the IV on AES/CTR/NoPadding is supposed to be a 12-byte nonce and a 4-byte counter.

```java
public final class AesFlushingCipher {
  ...
  public AesFlushingCipher(int mode, byte[] secretKey, long nonce, long offset) {
    try {
      cipher = Cipher.getInstance("AES/CTR/NoPadding");
      blockSize = cipher.getBlockSize();
      zerosBlock = new byte[blockSize];
      flushedBlock = new byte[blockSize];
      long counter = offset / blockSize;
      int startPadding = (int) (offset % blockSize);
      cipher.init(
          mode,
          new SecretKeySpec(secretKey, Util.splitAtFirst(cipher.getAlgorithm(), "/")[0]),
          new IvParameterSpec(getInitializationVector(nonce, counter)));
      if (startPadding != 0) {
        updateInPlace(new byte[startPadding], 0, startPadding);
      }
    } catch (NoSuchAlgorithmException
        | NoSuchPaddingException
        | InvalidKeyException
        | InvalidAlgorithmParameterException e) {
      // Should never happen.
      throw new RuntimeException(e);
    }
  }
  ...
  private byte[] getInitializationVector(long nonce, long counter) {
    return ByteBuffer.allocate(16).putLong(nonce).putLong(counter).array();
  }
  ...
}
```

### Isn't should be like below?
As-Is:
```java
  private byte[] getInitializationVector(long nonce, long counter) {
    return ByteBuffer.allocate(16).putLong(nonce).putLong(counter).array();
  }
```
To-Be:
```java
  private byte[] getInitializationVector(byte[] nonce, int counter) {
    return ByteBuffer.allocate(16).put(nonce, 0, 12).putInt(counter).array();
  }
```

**Comment by ojw28** [comment]
> But the IV on AES/CTR/NoPadding is supposed to be a 12-byte nonce and a 4-byte counter.

Please can you provide a citation for this? From the quick search I did, it seems to be somewhat of a convention/recommendation. It doesn't appear to be a requirement.

**Comment by syg4806** [comment]
I research this with [Using Advanced Encryption Standard (AES) Counter Mode With IPsec Encapsulating Security Payload (ESP)](https://datatracker.ietf.org/doc/html/rfc3686), and it seems a standard.
I think the better word for IV in AES/CTR is `Counter Block` according to the above doc.
[Counter Block Format](https://datatracker.ietf.org/doc/html/rfc3686#section-4) is a 4-byte nonce, 8-byte IV, and 4-byte Block Counter.

```
    0                   1                   2                   3
    0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |                            Nonce                              |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |                  Initialization Vector (IV)                   |
   |                                                               |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |                         Block Counter                         |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+

     Figure 2.  Counter Block Format
```
Unlike the standard specification, `javax.crypto.Cipher` doesn't care about this inner specification and it handles just as a 16-byte IvParameterSpec.
I think the `AesFlushingCipher` also should not have a dependency on how iv is constructed but it cares of only the counter.

So, I add a few functions to do this to explain what I want to tell.
Please take a look.
https://github.com/syg4806/ExoPlayer/commit/03f921c14b1b025dfa425f50a0519d72d11f490d

**Comment by ojw28** [comment]
> I research this with Using Advanced Encryption Standard (AES) Counter Mode With IPsec Encapsulating Security Payload (ESP), and it seems a standard.

It is _a standard_, but it appears to be a standard relating to use of AES specifically in IPsec. I don't think it's _the_ standard for how counter blocks should be generated for AES/CTR, and I'm not sure that such a standard exists. As a counter point, [NIST Recommendation - Appendix B.2](https://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-38a.pdf) suggests using half the bits for the nonce and the other half for the counter:

> A second approach to satisfying the uniqueness property across messages is to assign to each message a unique string of b/2 bits (rounding up, if b is odd), in other words, a message nonce, and to incorporate the message nonce into every counter block for the message. The leading b/2 bits (rounding up, if b is odd) of each counter block would be the message nonce, and the standard incrementing function would be applied to the remaining m bits to provide an index to the counter blocks for the message. 

It goes on to say:

> The number of blocks, n, in any message must satisfy n < 2^m .

In ExoPlayer's use case, a "message" could be an entire video file. Video files over 32GB would violate this rule when using a 4 byte counter. Whilst that's definitely on the high end, a 32GB video file is not implausible (and will likely become more commonplace in the future). Hence this would also suggest that allocating 8 bytes to the counter might be a good idea.
