### ISSUE TITLE
How to get selected `Format` with `TracksInfo`?

### ISSUE THREAD

**Issue by Goshin** [google/ExoPlayer#9674]
I used `Player.getCurrentTrackSelections()` and `ExoTrackSelection.getSelectedFormat()` to get some info of a playing HLS video:

```java
TrackSelectionArray trackSelectionArray = player.getCurrentTrackSelections();
for (int i = 0; i < trackSelectionArray.length; i++) {
    TrackSelection trackSelection = trackSelectionArray.get(i);
    if (trackSelection instanceof ExoTrackSelection) {
        ExoTrackSelection exoTrackSelection = (ExoTrackSelection) trackSelection;
        Format format = exoTrackSelection.getSelectedFormat();
        // Obtain format.codecs, format.bitrate, format.height ... here
    }
}
```

Since `Player.getCurrentTrackSelections()` is now marked deprecated, I try using `Player.getCurrentTracksInfo()` instead, which is suggested in the documentation.

However, a `TracksInfo` does not provide `TrackSelection` or the selected `Format` as `getCurrentTrackSelections()` does. I can see there is a similar method named `TrackGroupInfo.isTrackSelected(int trackIndex)` but it is not equivalent as documented and tested by myself.

```java
    /**
     * Returns if a track in a {@link TrackGroup} is selected for playback.
     *
     * <p>Multiple tracks of a track group may be selected. This is common in adaptive streaming,
     * where multiple tracks of different quality are selected and the player switches between them
     * depending on the network and the {@link TrackSelectionParameters}.
     *
     * <p>While this class doesn't provide which selected track is currently playing, some player
     * implementations have ways of getting such information. For example ExoPlayer provides this
     * information in {@code ExoTrackSelection.getSelectedFormat}.
     *
     * @param trackIndex The index of the track in the {@link TrackGroup}.
     * @return true if the track is selected, false otherwise.
     */
    public boolean isTrackSelected(int trackIndex) {
      return trackSelected[trackIndex];
    }
```

I was wondering what the proper way is to obtain `ExoTrackSelection` for now?

**Comment by moneytoo** [comment]
You can get `Format` from `Player.getCurrentTracksInfo()`, check the code sample here: https://github.com/google/ExoPlayer/issues/9665#issuecomment-963947863

**Comment by Goshin** [comment]
@moneytoo
> You can get `Format` from `Player.getCurrentTracksInfo()`, check the code sample here: [#9665 (comment)](https://github.com/google/ExoPlayer/issues/9665#issuecomment-963947863)

I see, to my understanding, that sample only shows how to get a `Format` by its index in a `TrackGroupInfo`, but I want to obtain the selected format like that provided by `ExoTrackSelection.getSelectedFormat()`.

**Comment by tonihei** [comment]
> but I want to obtain the selected format like that provided by ExoTrackSelection.getSelectedFormat().

`(Exo)TrackSelection.getSelectedFormat()` was never meant to be called by app code as it's not thread safe and also not aligned with the rest of the player state.

The simplest way to listen to adaptive video format changes is to listen to `Player.Listener.onVideoSizeChanged`, or alternatively to `AnalyticsListener.onDownstreamFormatChanged` (which contains more details like the actual `Format` and the reason for the change). You can also obtain the current video size by calling `Player.getVideoSize()`.

**Comment by Goshin** [comment]
@tonihei Many thanks. `AnalyticsListener.onDownstreamFormatChanged`works, but seems like it does not work for HLS streams with only one track.
Then I try `AnalyticsListener.onVideoInputFormatChanged` instead and it works like a charm!
