### ISSUE TITLE
r.2.16.0 addTextOutput alternative

### ISSUE THREAD

**Issue by FunkyMuse** [google/ExoPlayer#9679]
Before I was able to add custom styled subtitles view with because my video applications implements our own UI

```kotlin
 exoPlayer.textComponent.addTextOutput(styledSubtitlesView)
```
then it was deprecated and replaced with

```kotlin
SimpleExoPlayer.setTextOutput(TextOutput) 
```
Now it's totally removed, the suggestion is to use Player

![image](https://user-images.githubusercontent.com/25645122/141136730-6315179a-f71c-4b4e-8e80-1752656fc215.png)

But I'm unable to find the implementation for the `TextComponent` within the Player where I can set the `styledSubtitlesView`

**Comment by icbaker** [comment]
From the [2.16.0 release notes](https://github.com/google/ExoPlayer/blob/r2.16.0/RELEASENOTES.md#2160-2021-11-04):
> `SubtitleView` no longer implements `TextOutput`. `SubtitleView` implements `Player.Listener`, so can be registered to a player with `Player.addListener`.
