### ISSUE TITLE
Download content only through Wifi

### ISSUE THREAD

**Issue by SashiWork** [google/ExoPlayer#9681]
Hi Team,
Is there a way to download the content through Wifi only.
If there is a way, please do let us know.

**Comment by christosts** [comment]
I'm assuming you're referring to downloads for viewing content offline and not general streaming. If my assumption is correct, I'll redirect you to the guide on [Downloading Media](https://exoplayer.dev/downloading-media.html) and specifically on [Setting the requirements for downloads to progress](https://exoplayer.dev/downloading-media.html#setting-the-requirements-for-downloads-to-progress) where you can specify requirement to download content only on [NETWORK_UNMETERED](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/scheduler/Requirements.html#NETWORK_UNMETERED).

I'll close this issue, please feel free to re-open if my response did not fully answer your question.
