### ISSUE TITLE
How to add subtitle to exoplayer in new version

### ISSUE THREAD

**Issue by shelby-000** [google/ExoPlayer#9682]
Format textFormat = Format.createTextSampleFormat(null, MimeTypes.APPLICATION_SUBRIP,
        null, Format.NO_VALUE, Format.NO_VALUE, "en", null, Format.OFFSET_SAMPLE_RELATIVE);

`createTextSampleFormat` is throwing error says can not resolve method.

**Comment by moneytoo** [comment]
I'm adding SRT subtitles like this:
```java
MediaItem.SubtitleConfiguration subtitle = new MediaItem.SubtitleConfiguration.Builder(subtitleUri)
		.setMimeType(subtitleMime)
		.setLanguage(subtitleLanguage)
		.setSelectionFlags(C.SELECTION_FLAG_DEFAULT)
		.setRoleFlags(C.ROLE_FLAG_SUBTITLE)
		.setLabel(subtitleName)
		.build();
mediaItemBuilder.setSubtitleConfigurations(Collections.singletonList(subtitle));
```

**Comment by icbaker** [comment]
@moneytoo's suggestion looks right - there's some docs on the same topic here: https://exoplayer.dev/media-items.html#sideloading-subtitle-tracks
