### ISSUE TITLE
How to reset the back/forward increments on 2.16.0?

### ISSUE THREAD

**Issue by MiaJiaXa** [google/ExoPlayer#9683]
I need to implement **multi-speed** fast-forward/backward when the user multi-tap the forward/backward button. 

> Remove ControlDispatcher and DefaultControlDispatcher. Operations can be customized by using a ForwardingPlayer, or when configuring the player (for example by using ExoPlayer.Builder.setSeekBackIncrementMs).

The above is written at the release note for 2.16.0
we were using the `DefaultControlDispatcher(long fastForwardIncrementMs, long rewindIncrementMs)` or `playerView.setFastForwardIncrementMs(positionOffset)`/`playerView.setRewindIncrementMs(positionOffset)`.

but this class is already removed. we should using `ExoPlayer.Builder.setSeekBackIncrementMs` according to the release note. but I can't see how we can reset the increments after the player is built.

Could you guys please help to figure out it? maybe I am missing sth.

**Comment by christosts** [comment]
Let me confirm I understood the question, I also read your comments on #9492: In your app, when the user changes the player speed, you would re-construct the `DefaultControlDispatcher` with the updated `fastForwardIncrementMs` and  `rewindIncrementMs`, is this correct?

If my understanding is correct, you can achieve the same by using the `ForwardingPlayer`: wrap the `Player` in a `ForwardingPlayer` and override the `ForwardingPlayer``s `seekForward` and `seekBack` . Your implementation of these two methods can take the player's forward or backward increment values, multiply them by a factor (2x for double speed?) and then call `Player.seekTo` accordingly, for example

```
ForwardingPlayer forwardingPlayer = new ForwardingPlayer(player) {
      @Override
      public void seekForward() {        
        // Double the forward increment.
        long seekForwardIncrement = player.getSeekForwardIncrement() * 2;
        seekToOffset(seekForwardIncrement);
      }

      // Copied from DefaultContorlDispatcher implementation.
      private void seekToOffset(long offsetMs) {
        long positionMs = player.getCurrentPosition() + offsetMs;
        long durationMs = player.getDuration();
        if (durationMs != C.TIME_UNSET) {
          positionMs = min(positionMs, durationMs);
        }
        positionMs = max(positionMs, 0);
        player.seekTo(positionMs);
      }
    };
```

You'll need of course to find a way to update the multiplication factors in your `ForwardingPlayer`, but that's a general programming task (e.g., you can subclass `ForwardingPlayer` and add additional setters). Please let me know if that works for your app, so we can close this issue.

**Comment by MiaJiaXa** [comment]
Yeah, It helped. A lot of thanks! @christosts  :)
