### ISSUE TITLE
Get screenshot of the video stream when using SurfaceView

### ISSUE THREAD

**Issue by Anatolf** [google/ExoPlayer#9686]
Im using exoPlayer.setVideoSurface(surfaceView). How easy way to get screenshot of the video stream when using SurfaceView?
I have no way to use TextureView because my SurfaceView is ZoomSurfaceView.
How can I get Bitmap from ExoPlayer when using SurfaceView?

**Comment by christosts** [comment]
Have you looked at the [PixelCopy](https://developer.android.com/reference/android/view/PixelCopy) class?

**Comment by Anatolf** [comment]
> Have you looked at the [PixelCopy](https://developer.android.com/reference/android/view/PixelCopy) class?

PixelCopy gives me the ability to save a picture from a surface.
Its resolution is equal to the width and height of the area on the screen.
If my video stream has a resolution of 1920x1080р, then a screenshot using PixelCopy can be much lower (for example 640x360p).

Is it possible to get a screenshot with the original resolution of the video stream?

Bitmap bitmap = Bitmap.createBitmap(
                zoomPlayerView.getWidth(),
                zoomPlayerView.getHeight(),
                Bitmap.Config.ARGB_8888);

PixelCopy.request(surfacePlayerView, bitmap, (copyResult) ->

**Comment by christosts** [comment]
In your code snippet, you're setting the bitmap's size to the view size. Have you tried setting the size based on the video size? See [Player.getVideoSize()](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/Player.html#getVideoSize()).

**Comment by th1nk3r-ing** [comment]
When using `PixelCopy` takes a screenshot of `SurfaceView` on Android 14, and a black area appears at the top of the returned image, which appears to be an AOSP bug.
Does anyone else have the same problem?

**Comment by th1nk3r-ing** [comment]
> When using `PixelCopy` takes a screenshot of `SurfaceView` on Android 14, and a black area appears at the top of the returned image, which appears to be an AOSP bug. Does anyone else have the same problem?

好像是多线程 bug, 需要加入 `sleep()` 才行. 
Android-14 刚改了 `PixelCopy` 内部的实现, 可能 bug 由此引入....
