### ISSUE TITLE
Subtitle track selection resets after switching audio track

### ISSUE THREAD

**Issue by moneytoo** [google/ExoPlayer#9690]
@tonihei Here's another track selection issue (this one was reported to me by @DarremMolko).

I added this [test5.mkv](https://raw.githubusercontent.com/ietf-wg-cellar/matroska-test-files/master/test_files/test5.mkv) file to the json in the ExoPlayer Demo.

Steps:

1. Switch the subtitle from the default "English" to let's say "German".
2. Switch audio from "Auto" to "English, Mono".

The subtitle selection then resets back to English. (This applies also the other way round - switching audio first and then subtitle.) This wasn't happening in 2.15.1.

- ExoPlayer version number: `dev-v2-r2.16.1` (head currently at a29d7cf684028cc7cbdddb15df3eb9619fe80c57)
- Android version: Android 10
- Android device: OnePlus 7

**Comment by tonihei** [comment]
Thanks, that was an oversight in https://github.com/google/ExoPlayer/commit/cb60425aabe12904531c26bd24a88ed83764a20e where we replace the selections instead of adding to them.
