### ISSUE TITLE
Unable to select subtitle track after disabling

### ISSUE THREAD

**Issue by moneytoo** [google/ExoPlayer#9692]
@tonihei Here's another track selection issue, which still lives in the `dev-v2` branch (as well as in `dev-v2-r2.16.1`). 

I added this [test5.mkv](https://raw.githubusercontent.com/ietf-wg-cellar/matroska-test-files/master/test_files/test5.mkv) file to the json in the ExoPlayer Demo.

Steps:
1. Switch the subtitle from the default "English" to "None".
2. Try switching back to the "English" - this doesn't work

- ExoPlayer version number: `dev-v2` (head currently at fde78bc3a74ba069a3f0e2e8a4eec8dc46c6f91e)
- Android version: Android 10
- Android device: OnePlus 7

**Comment by tonihei** [comment]
Thanks, we also discovered this yesterday. There is also another similar issue where the "Auto" button for audio doesn't work when the audio tracks have been manually disabled by app code.
