### ISSUE TITLE
Custom DataSource.Factory with different headers

### ISSUE THREAD

**Issue by SashiWork** [google/ExoPlayer#9693]
Hi Team,

We are using a Custom DataSource.Factory for playing the encrypted HLS content where we pass a Token in headers.

But when we are sideloading the Subtitles. The subtitles are not working because of the Header Token which we added for HLS content. 

Is there a way to overcome this situation?
where we can exclude the header for subtitles through Custom DataSource.Factory.

Below is the Custom DataSpurce.Factory
```
class CustomDataSourcesFactory
/**
 * Constructs a DefaultHttpDataSourceFactory. Sets [ ][DefaultHttpDataSource.DEFAULT_CONNECT_TIMEOUT_MILLIS] as the connection timeout, [ ][DefaultHttpDataSource.DEFAULT_READ_TIMEOUT_MILLIS] as the read timeout and disables
 * cross-protocol redirects.
 *
 * @param userAgent The User-Agent string that should be used.
 */ @JvmOverloads constructor(
    private val userAgent: String?,
    private val token: String?,
    @field:Nullable @param:Nullable private val listener: TransferListener? = null,
    private val connectTimeoutMillis: Int = DefaultHttpDataSource.DEFAULT_CONNECT_TIMEOUT_MILLIS,
    private val readTimeoutMillis: Int =
        DefaultHttpDataSource.DEFAULT_READ_TIMEOUT_MILLIS,
    private val allowCrossProtocolRedirects: Boolean = false
) : BaseFactory() {

    override fun createDataSourceInternal(
        defaultRequestProperties: RequestProperties
    ): HttpDataSource {
        val defaultHttpDataSource = DefaultHttpDataSource(
            userAgent, connectTimeoutMillis, readTimeoutMillis,
            allowCrossProtocolRedirects, defaultRequestProperties
        )
        defaultHttpDataSource.setRequestProperty(AUTHORIZATION,
            "$BEARER$token"
        )
        return defaultHttpDataSource
    }
}
```

Please do let us know if any feasibility available.

**Comment by marcbaechinger** [comment]
I'm not entirely sure how you are achieving what you do  from the information you provided. So I assume you are injecting your `CustomDataSourceFactory` to the `DefaultMediaSourrceFactory` which you then use for building your player. You then define the subtitles in a `MediaItem` which you pass to `player.setMediaItem(mediaItem)` or another media item based method.

If this is the case then the `DataSourceFactory` that you inject is used by the `DefaultMediaSourcefactory` for the content and the subtitles requests. So the token is sent to the server that serves the subtitle files as well as to the server that serves the HLS playlist and media files.

The `DefaultMediaSourceFactory` currently does not offer an API to set different `DataSourceFactory` for different request. I think you could solve this by using a `ResolvingDataSource.Factory` and implement a custom `Resolver`. This resolver would check whether it is a subtitle or an HLS request and then add the bearer token to HLS requests by modifiyng the `DataSpec`.

As an alternative, you can also create a custom `MediaSourceFactory` and use thiat factory when you build the player, but this would require you to kind of build all the features that are in `DefaultMediaSourceFactory` again (you can do a composite and delegate to an instance of the `DefaultMediaSourceFactory`, but you have to create a `MergedMediaSource` yourself and such things). Seems this is more complicated, so I'd look into the resolver first.

**Comment by SashiWork** [comment]
@marcbaechinger  thank you, the ```ResolvingDataSource.Factory```  worked for me. Cheers Mate
