### ISSUE TITLE
Sequence check in RtpH264Reader.processFragmentationUnitPacket skips packet number 65,535

### ISSUE THREAD

**Issue by pavhofman** [google/ExoPlayer#9697]
Hi,
IMO the check in https://github.com/google/ExoPlayer/blob/02f7aafe67b4893134a31ea55a3ba0f0535df145/library/rtsp/src/main/java/com/google/android/exoplayer2/source/rtsp/reader/RtpH264Reader.java#L262 skips and drops new packet number 65,535. The current calculation yields 0 for previousSequenceNumber = 65,534, however the next packet has number 65,535, while its successive packet has 0.

IMO the calculation should be

`int expectedSequenceNumber = (previousSequenceNumber + 1) % (RtpPacket.MAX_SEQUENCE_NUMBER + 1);`

Thanks a lot for considering the change.

Best regards,

Pavel.

**Comment by pavhofman** [comment]
Actually my RTP camera sends packets numbered from 1 to 65,535 which requires the check to be
int expectedSequenceNumber = (previousSequenceNumber % RtpPacket.MAX_SEQUENCE_NUMBER) + 1;

It's possible other RTP sources send numbers from 0 to 65,534 for which the existing code is correct. So I will just modify my local exoplayer source.

Thanks,

Pavel.

**Comment by claincly** [comment]
It is indeed problematic, will fix.

**Comment by pavhofman** [comment]
Thanks a lot. I could not find any official specs for the packet numbering, just that it's 16bit and numbers should be sequential. Maybe some devices start with 0, some with 1 (my camera). It would be surprising if some ended at 65,534, IMO 65,535 is the most logical value.
