### ISSUE TITLE
Incorrect label in audio track selector overview

### ISSUE THREAD

**Issue by moneytoo** [google/ExoPlayer#9698]
@tonihei Here's another smaller issue in the `dev-v2` branch. 

I added this [test5.mkv](https://raw.githubusercontent.com/ietf-wg-cellar/matroska-test-files/master/test_files/test5.mkv) file to the json in the ExoPlayer Demo.

Steps:
1. Switch the audio from the default "Auto" to "English, Mono".
2. The selection overview still shows "Auto".

<img src="https://user-images.githubusercontent.com/1071643/142063219-08833486-b650-4894-9a3f-a1fe69a47bbd.png" height="240">

- ExoPlayer version number: `dev-v2` (head currently at 21107693233d7a9414f59add65a006abdf10e2e4)
- Android version: Android 10
- Android device: OnePlus 7

**Comment by tonihei** [comment]
Fixed by the commit above.
