### ISSUE TITLE
The window in Timeline Class was not found

### ISSUE THREAD

**Issue by paulocoutinhox** [google/ExoPlayer#9699]
Hi,

I start have this problem recently:

```
Fatal Exception: java.lang.NoSuchMethodError
No virtual method getWindow(ILcom/google/android/exoplayer2/Timeline$Window;Z)Lcom/google/android/exoplayer2/Timeline$Window; in class Lcom/google/android/exoplayer2/Timeline; or its super classes (declaration of 'com.google.android.exoplayer2.Timeline' appears in base.apk!classes2.dex)
io.audioengine.mobile.FindawayMediaPlayer.seekTo (FindawayMediaPlayer.java:212)
io.audioengine.mobile.FindawayMediaPlayer.onTimelineChanged (FindawayMediaPlayer.java:378)
```

Maybe it was removed in some ExoPlayer version.

Can anyone confirm?

**Comment by paulocoutinhox** [comment]
This commit can be related?
https://github.com/google/ExoPlayer/commit/b95fba2cb71c62f3c845a532252266a4e178126a#diff-6ce8af6d1d94ca1abe561ae76eb53a9caf7d5358fba7988c2ce7a0ff64cc84b0

**Comment by marcbaechinger** [comment]
This deprecated method has been removed.

The JavaDoc that you linked above says

```
/** @deprecated Use {@link #getWindow(int, Window)} instead. Tags will always be set. */
```

Is this an option for you?

**Comment by paulocoutinhox** [comment]
Hi,

The problem is the SDK that we are using. The SDK has an old version of ExoPlayer that use the removed method.

I open a ticket on the company support.

I back to ExoPlayer version 2.14 :(

Thanks.
