### ISSUE TITLE
How to provide a renderers list when using ExoPlayer.Builder?

### ISSUE THREAD

**Issue by giovannyvelezalt** [google/ExoPlayer#9700]
Hello team, 

When we use `ExoPlayer.Builder` we currently provide a list of Renderers that is created using `DefaultRenderersFactory.createRenderers` where we provide some custom listeners. 

`exoPlayer = ExoPlayer.Builder(
        exoRenderers as Array<out Renderer>,
        exoTrackSelector,
        exoMediaSourceFactory,
        exoLoadControl,
        bandwidthMeter
      )`

Now that the builder doesn't have a proper way to provide this list of Renderers it uses an internally instanced `ComponentListener` see `SimpleExoPlayer.java` line 446 from the [SimpleExoPlayer.java fron tag r2.16.0 ](https://github.com/google/ExoPlayer/blob/r2.16.0/library/core/src/main/java/com/google/android/exoplayer2/SimpleExoPlayer.java). Is there a way to provide our custom listeners instead of the internal `ComponentListener` or is there a suggested way?

**Comment by marcbaechinger** [comment]
I would expect that any event that is sent to one of these listeners can be listen to with an `AnalyticsListener`. 

You can do something [similar like the demo app does](https://github.com/google/ExoPlayer/blob/release-v2/demos/main/src/main/java/com/google/android/exoplayer2/demo/PlayerActivity.java#L278) to add an analytics listener:

```
player =
    new ExoPlayer.Builder(/* context= */ this)
        .build();
player.addAnalyticsListener(new MyAnalyticsListener());
```

**Comment by giovannyvelezalt** [comment]
Thank you @marcbaechinger, I reviewed and it will do for almost everything, so I'll ask for a last one that is missing. In the `createRenderers` method we can provide a `TextOutput` implementation which essentially is a listener for cues `TextOutput.onCues(List<Cue> cues)` how can we provide this and where?

**Comment by giovannyvelezalt** [comment]
I will answer myself here if it's useful for someone in the future. 

The `Player` interface contains an `addListener(Listener listener)` method and the `Listener` interface has an `onCues(List<Cue> cues)` call.
