### ISSUE TITLE
DefaultTrackSelector doesn't select preferred audio track

### ISSUE THREAD

**Issue by moneytoo** [google/ExoPlayer#9701]
@tonihei Here's another issue in the `dev-v2` branch. 

I added this [test5.mkv](https://raw.githubusercontent.com/ietf-wg-cellar/matroska-test-files/master/test_files/test5.mkv) file to the json in the ExoPlayer Demo. Then I added following code to `PlayerActivity`:

```java
trackSelector.setParameters(trackSelector.buildUponParameters()
  .setPreferredAudioLanguages("eng")
);
```

In 2.15.1, the track selector successfully selected the English audio track:

```
Audio #2
ID                                       : 10
Format                                   : AAC LC
Format/Info                              : Advanced Audio Codec Low Complexity
Codec ID                                 : A_AAC-2
Duration                                 : 46 s 665 ms
Channel(s)                               : 1 channel
Channel layout                           : C
Sampling rate                            : 22.05 kHz
Frame rate                               : 21.533 FPS (1024 SPF)
Compression mode                         : Lossy
Delay relative to video                  : 9 ms
Title                                    : Commentary
Language                                 : English
Default                                  : No
Forced                                   : No
```

In `dev-v2`, it keeps selected the default one:

```
Audio #1
ID                                       : 2
Format                                   : AAC LC
Format/Info                              : Advanced Audio Codec Low Complexity
Codec ID                                 : A_AAC-2
Duration                                 : 46 s 665 ms
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 46.875 FPS (1024 SPF)
Compression mode                         : Lossy
Delay relative to video                  : 12 ms
Default                                  : Yes
Forced                                   : No
```

- ExoPlayer version number: `dev-v2` (head currently at 21107693233d7a9414f59add65a006abdf10e2e4)
- Android version: Android 10
- Android device: OnePlus 7

**Comment by tonihei** [comment]
I can't reproduce that. Adding the code snippet above to the demo app correctly selects the English commentary track for this media file. 

Note that the `StyledPlayerView` UI doesn't reflect this override (and still shows `Auto`) because it no longer knows about the old style overrides. This is an intentional design decision to allow us to remove a dependency from the UI module to the core ExoPlayer module.

**Comment by moneytoo** [comment]
I see that now. My bad. I put the snippet on o wrong line - where it was overridden later on. I initially noticed this issue in my ExoPlayer branch where I probably missed to cherry pick some commits with fixes.
