### ISSUE TITLE
Crash ExoPlayer.Builder in android version 5 and 6 (android api 21 and 23)

### ISSUE THREAD

**Issue by mrj976** [google/ExoPlayer#9704]
When I upgrade exoplayer to version 2.16.0, it crashes when I run the line below the code:
`exoPlayer = ExoPlayer.Builder(this).build()`

I tested on higher Androids version like 10 and 11 (android api 29 and 30) and there is no problem, but in Android version 5 and 6 it crashes (android api 21 and 23)
Previously, in version 2.11.8, which I used, it ran without any problems in all versions of Android, but since I updated it to version 2.16.0, I have seen this problem in Android version 5 and 6.

What should I do to solve this problem?

My error log:

   ```
 java.lang.NoClassDefFoundError: com.google.android.exoplayer2.ExoPlayer$Builder$$ExternalSyntheticLambda0
        at com.google.android.exoplayer2.ExoPlayer$Builder.<init>(ExoPlayer.java:440)
        at com.myapp.Activity.VideoActivity_Online.onCreate(VideoActivity_Online.kt:58)
        at android.app.Activity.performCreate(Activity.java:6237)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
        at android.app.ActivityThread.-wrap11(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by christosts** [comment]
We tested ExoPlayer 2.16.0 with a device running Android 5.1 (API level 22) and a Nexus 5 emulator on  API 23 and did not see the issue raised. The stacktrace is coming from a lambda, but there have been lamdas elsewhere in the code for a long time, so I guess it's not an issue with lambda support in the runtime of those devices. 

It's a long shot, I wonder if this is somehow related to how proguard, maybe thje specific runtimes can't load DefaultRenderersFactory/DefaultMediaSourceFactory/DefaultExtractorsFactory which are referenced from the lambdas. You already said that the app works on Android 10/11, so the classes are there.

I will need your assistance to further debug this:
- Does the raised `NoClassDefFoundError` have a message indicating what class is missing? Is it possible to log the message of the exception and let us know if there's anything valuable?
- Can you try to build and run the ExoPlayer demo app on these devices, building a release variant too (e.g. `noDecodersExtensionRelease`) to at least verify the issue is not with general lambda support on these runtimes?
- Does this happen on your app when you're building a specific variant? Eg does it fail on release build with proguard enabled, but works on a debug build?

**Comment by mrj976** [comment]
> We tested ExoPlayer 2.16.0 with a device running Android 5.1 (API level 22) and a Nexus 5 emulator on API 23 and did not see the issue raised. The stacktrace is coming from a lambda, but there have been lamdas elsewhere in the code for a long time, so I guess it's not an issue with lambda support in the runtime of those devices.
> 
> It's a long shot, I wonder if this is somehow related to how proguard, maybe thje specific runtimes can't load DefaultRenderersFactory/DefaultMediaSourceFactory/DefaultExtractorsFactory which are referenced from the lambdas. You already said that the app works on Android 10/11, so the classes are there.
> 
> I will need your assistance to further debug this:
> 
> * Does the raised `NoClassDefFoundError` have a message indicating what class is missing? Is it possible to log the message of the exception and let us know if there's anything valuable?
> * Can you try to build and run the ExoPlayer demo app on these devices, building a release variant too (e.g. `noDecodersExtensionRelease`) to at least verify the issue is not with general lambda support on these runtimes?
> * Does this happen on your app when you're building a specific variant? Eg does it fail on release build with proguard enabled, but works on a debug build?

I tested the demo on the device with Android 6 (API level 23) and it ran without any problems
But when I install my application on the same device, it crashes and gives an error
`com.google.android.exoplayer2.ExoPlayer $ Builder $$ ExternalSyntheticLambda0`
Can be seen in the log

I tested my application in both debug and release versions (enabled and disabled proguard) and there is a problem
I do not know why
Thank you for helping me solve this problem

**Comment by christosts** [comment]
Next step of investigation: the runtime on these devices does not like the inline lambdas in ExoPlayer.Builder (not sure why and we have plenty of lambdas elsewhere in the code)

Let's try two things:
1. Can you please share with us a minimal Android Studio project where this is happening? You can either attach a project here or share a link. If you can't share anything publicly, you can send us an email at dev.exoplayer@gmail.com with subject `Issue #9704` and update this issue so to indicate you've sent it over email.

1. I've created a patch on ExoPlayer.Builder to replace lambdas with anonymous classes, see link at the end of this comment. Please checkout the ExoPlayer code at `r2.16.0` and set your project to depend on local ExoPlayer sources ([instructions](https://github.com/google/ExoPlayer/blob/r2.16.0/README.md#locally)). Run your project **without modifying the ExoPlayer code first** to verify the error still occurs on Android 6. Then apply the attached patch and retry and let us know if the patch fixed the issue. Please do not skip testing with the umodified sources, we need to verify the patch indeed fixes the issue.

Thanks

[exoplayer-builder.patch.zip](https://github.com/google/ExoPlayer/files/7569904/exoplayer-builder.patch.zip)

**Comment by icbaker** [comment]
@mrj976 What version of the Android Gradle Plugin are you using in your project? I think for lambda support it must be higher than 3.0.0: https://developer.android.com/studio/write/java8-support#supported_features

The ExoPlayer demo app uses 7.0.3: https://github.com/google/ExoPlayer/blob/r2.16.1/build.gradle#L20

You must also turn on Java 8 support in every `build.gradle` file in your project that transitively depends on ExoPlayer, as documented here: https://github.com/google/ExoPlayer/blob/release-v2/README.md#2-turn-on-java-8-support

**Comment by mrj976** [comment]
> @mrj976 What version of the Android Gradle Plugin are you using in your project? I think for lambda support it must be higher than 3.0.0: https://developer.android.com/studio/write/java8-support#supported_features
> 
> The ExoPlayer demo app uses 7.0.3: https://github.com/google/ExoPlayer/blob/r2.16.1/build.gradle#L20
> 
> You must also turn on Java 8 support in every `build.gradle` file in your project that transitively depends on ExoPlayer, as documented here: https://github.com/google/ExoPlayer/blob/release-v2/README.md#2-turn-on-java-8-support

Yes, I have Java 8 support enabled and using version 7.0.2 of Gradle

**Comment by mrj976** [comment]
> Next step of investigation: the runtime on these devices does not like the inline lambdas in ExoPlayer.Builder (not sure why and we have plenty of lambdas elsewhere in the code)
> 
> Let's try two things:
> 
> 1. Can you please share with us a minimal Android Studio project where this is happening? You can either attach a project here or share a link. If you can't share anything publicly, you can send us an email at [dev.exoplayer@gmail.com](mailto:dev.exoplayer@gmail.com) with subject `Issue #9704` and update this issue so to indicate you've sent it over email.
> 2. I've created a patch on ExoPlayer.Builder to replace lambdas with anonymous classes, see link at the end of this comment. Please checkout the ExoPlayer code at `r2.16.0` and set your project to depend on local ExoPlayer sources ([instructions](https://github.com/google/ExoPlayer/blob/r2.16.0/README.md#locally)). Run your project **without modifying the ExoPlayer code first** to verify the error still occurs on Android 6. Then apply the attached patch and retry and let us know if the patch fixed the issue. Please do not skip testing with the umodified sources, we need to verify the patch indeed fixes the issue.
> 
> Thanks
> 
> [exoplayer-builder.patch.zip](https://github.com/google/ExoPlayer/files/7569904/exoplayer-builder.patch.zip)

Fortunately, I understood the reason for the problem, and that is the use 
`implementation group: 'com.google.guava', name: 'guava', version: '30.1-jre'`
 in Gradle
This problem is solved when I remove it
Is there a solution so I can use it without crashing?

**Comment by icbaker** [comment]
> Fortunately, I understood the reason for the problem, and that is the use
> `implementation group: 'com.google.guava', name: 'guava', version: '30.1-jre'`
> in Gradle
> This problem is solved when I remove it
> Is there a solution so I can use it without crashing?

Thanks for pin-pointing the root cause. I was able to reproduce a `NoClassDefFoundError` crash on a Nexus 5 emulator running API 23 with a small app with the following in `build.gradle` and `MainActivity`:

```
dependencies {
    implementation 'com.google.guava:guava:30.1-jre'
    implementation 'com.google.android.exoplayer:exoplayer:2.16.0'

   // Dont think these are relevant, but including them for completeness:
    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'com.google.android.material:material:1.4.0'
}


public class MainActivity extends AppCompatActivity {

  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_main);

    ExoPlayer player = new ExoPlayer.Builder(this).build();
    player.setMediaItem(
        new MediaItem.Builder()
            .setUri("https://html5demos.com/assets/dizzy.mp4")
            .setSubtitleConfigurations(
                ImmutableList.of(
                    new MediaItem.SubtitleConfiguration.Builder(
                            Uri.parse(
                                "https://storage.googleapis.com/exoplayer-test-media-1/webvtt/numeric-lines.vtt"))
                        .setMimeType(MimeTypes.TEXT_VTT)
                        .build()))
            .build());
    player.prepare();
  }

}
```

And I got this stack trace when launching the app:

```
2021-11-22 10:38:14.383 8149-8149/com.google.ibaker.exoplayerbarebones E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.google.ibaker.exoplayerbarebones, PID: 8149
    java.lang.NoClassDefFoundError: t0.r
        at t0.p$b.<init>(:440)
        at com.google.ibaker.exoplayerbarebones.MainActivity.onCreate(:19)
        at android.app.Activity.performCreate(Activity.java:6237)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
        at android.app.ActivityThread.-wrap11(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
2021-11-22 10:38:25.658 8149-8149/? I/Process: Sending signal. PID: 8149 SIG: 9

```

 (it looks a bit different to yours, but I think it's the same root cause - [L440 of `ExoPlayer` at 2.16.0](https://github.com/google/ExoPlayer/blob/r2.16.0/library/core/src/main/java/com/google/android/exoplayer2/ExoPlayer.java#L440) is the constructor call that uses a lambda).

I changed the Guava dep to the [Android-specific variant](https://github.com/google/guava#adding-guava-to-your-build), and the app no longer crashes:
```
implementation 'com.google.guava:guava:30.1-android'
```

Hopefully that resolves your problem? I'm going to close this, but please reply here if you need more help on this issue and I'm happy to re-open it.
