### ISSUE TITLE
Closed captions not being displayed

### ISSUE THREAD

**Issue by emig09** [google/ExoPlayer#9706]
I'm facing a problem using DASH for a live TV channel since I cannot see CC

Formats I see (for an specific channel) are these 3:

Format(audio_20003=145200.track_id=20003, null, audio/mp4, audio/mp4a-latm, mp4a.40.2, 145200, es, [-1, -1, -1.0], [2, 48000])
Format(audio_20004=145200.track_id=20004, null, audio/mp4, audio/mp4a-latm, mp4a.40.2, 145200, en, [-1, -1, -1.0], [2, 48000])
Format(video=379968.track_id=10016, null, video/mp4, video/avc, avc1.4D401E, 379968, null, [416, 240, 29.97003], [-1, -1])

Are CC coming as an application/ttml+xml type format or they generate in another way?
Do they need an extra configuration in order to be displayed?

**Comment by marcbaechinger** [comment]
If you are [using `EventLogger`](https://exoplayer.dev/debug-logging.html#media-tracks) it is very easy to see the tracks of a stream in the logs.

Selecting a subtitle track can be done by using `TrackSelectionParameters` like the snippet below shows:

```
TrackSelectionParameters trackSelectionParameters = player.getTrackSelectionParameters();
player.setTrackSelectionParameters(
    trackSelectionParameters.buildUpon().setPreferredTextLanguage("es").build());
```

**Comment by emig09** [comment]
Thanks @marcbaechinger I've added the EventLogger and, for an specific channel I have:

>  tracks [eventTime=832.15, mediaPos=7196.49, window=0, period=0
   MediaCodecVideoRenderer [
     Group:0, adaptive_supported=YES [
       [X] Track:0, id=video=379968.track_id=10011, mimeType=video/avc, bitrate=379968, codecs=avc1.4D401E, drm=[widevine], res=416x240, fps=29.97003, supported=YES
       [X] Track:1, id=video=579968.track_id=10010, mimeType=video/avc, bitrate=579968, codecs=avc1.4D401E, drm=[widevine], res=640x360, fps=29.97003, supported=YES
       [X] Track:2, id=video=899968.track_id=10009, mimeType=video/avc, bitrate=899968, codecs=avc1.4D401F, drm=[widevine], res=854x480, fps=29.97003, supported=YES
       [X] Track:3, id=video=1499968.track_id=10008, mimeType=video/avc, bitrate=1499968, codecs=avc1.4D401F, drm=[widevine], res=1024x576, fps=29.97003, supported=YES
       [X] Track:4, id=video=2499968.track_id=10007, mimeType=video/avc, bitrate=2499968, codecs=avc1.4D401F, drm=[widevine], res=1280x720, fps=29.97003, supported=YES
     ]
   ]
   MediaCodecAudioRenderer [
     Group:0, adaptive_supported=N/A [
       [X] Track:0, id=audio_20003=145200.track_id=20003, mimeType=audio/mp4a-latm, bitrate=145200, codecs=mp4a.40.2, drm=[widevine], channels=2, sample_rate=48000, language=es, supported=YES
    ]
    Group:1, adaptive_supported=N/A [
      [ ] Track:0, id=audio_20004=145200.track_id=20004, mimeType=audio/mp4a-latm, bitrate=145200, codecs=mp4a.40.2, drm=[widevine], channels=2, sample_rate=48000, language=en, supported=YES ]
   ]
  TextRenderer []
   MetadataRenderer []
   CameraMotionRenderer [] ]

So I supposed (since there is no TextRenderer) I won't be able to see CC?

**Comment by marcbaechinger** [comment]
Yes, it seems that the stream does not contain text tracks. For ttml you would see something like

```
D/EventLogger:   TextRenderer [
D/EventLogger:     Group:0, adaptive_supported=N/A [
D/EventLogger:       [X] Track:0, id=null, mimeType=application/ttml+xml, language=en, supported=YES
D/EventLogger:     ]
D/EventLogger:   ]
```

**Comment by icbaker** [comment]
If you believe this stream ought to contain subtitles can you either share a link to the stream here or send it to dev.exoplayer@gmail.com using a subject in the format `Issue #1234` (where `#1234` should be replaced with this issue number)? Please also update this issue to indicate you’ve done this.
