### ISSUE TITLE
EventListener, onLoadStarted and onLoadCompleted never gets activated 

### ISSUE THREAD

**Issue by boburger** [google/ExoPlayer#971]
Using HLS for Video-Streaming it looks like that onLoadStarted and onLoadCompleted never gets activated but onDownstreamformatChanged from the same EventListener(BaseChunkSampleSource) gets activated. Is there any solution for this problem? THANKS

**Comment by ojw28** [comment]
Wait, I'm confused. These events are being reported in the demo app for HLS playbacks. Are you sure you're not using an old version of ExoPlayer?

**Comment by boburger** [comment]
Sorry my fault, just updated the ExoPlayer version and it worked
