### ISSUE TITLE
嗨，能否实现Recyclerview 视频列表同时播放的问题？这功能非常棒~

### ISSUE THREAD

**Issue by yanghuabang05** [google/ExoPlayer#9714]
Before filing a feature request:
-----------------------
- Search existing open issues, specifically with the label ‘enhancement’:
  https://github.com/google/ExoPlayer/labels/enhancement
- Search existing pull requests: https://github.com/google/ExoPlayer/pulls

When filing a feature request:
-----------------------
Replace the content in the sections below.

### [REQUIRED] Use case description
Describe the use case or problem you are trying to solve in detail. If there are
any standards or specifications involved, please provide the relevant details.

### Proposed solution
A clear and concise description of your proposed solution, if you have one.

### Alternatives considered
A clear and concise description of any alternative solutions you considered,
if applicable.

**Comment by tonihei** [comment]
Please file issues with complete information as requested in the issue template. 

Existing advice for how to use ExoPlayer in RecyclerView can be found in #867.
