### ISSUE TITLE
Playing DRM protected DASH videos going blank

### ISSUE THREAD

**Issue by sriram-mohan** [google/ExoPlayer#9715]
**Issue:**
- Playing DRM dash videos we could notice that sometimes the video goes blank (while the audio still plays) especially when we open the video from PiP screen (video attached for reference), we're able to reproduce this only intermittently, though we've had a lot of customer complaints about this issue. Curious if you're aware of such issue and if you've any suggestions/help.
 
Exoplayer version used:: `2.14.1`
DRM: `Widevine`

Attaching the bug report for reference, please do reach out if you need more info. Thank you!

**Output of running `$ adb bugreport` in the console:**
[bugreport-sdk_gphone_x86_arm-PSR1.180720.117-2021-11-22-12-55-57.zip](https://github.com/google/ExoPlayer/files/7584375/bugreport-sdk_gphone_x86_arm-PSR1.180720.117-2021-11-22-12-55-57.zip)

**Video for reference:**
https://user-images.githubusercontent.com/40211649/142935803-aa935666-6446-4f86-8b97-900708f2fb46.mp4

**Comment by tonihei** [comment]
It looks like the bugreport was taken on an emulator. Can you reproduce the problem on a real device as well?

**Comment by sriram-mohan** [comment]
> It looks like the bugreport was taken on an emulator. Can you reproduce the problem on a real device as well?

@tonihei - let me try to reproduce it on a real device and get back to you...thank you!

**Comment by PoojanEnv** [comment]
here is an example of this issue with my device 
https://user-images.githubusercontent.com/90393073/144058499-88a032de-dd79-4364-ba4d-90f08a7816a4.mp4

here is a bug report which should help with diagnosing the issue
[dumpstate-2021-11-30-13-40-37.zip](https://github.com/google/ExoPlayer/files/7626145/dumpstate-2021-11-30-13-40-37.zip)

**Comment by szaboa** [comment]
@sriram-mohan did you figure it out? We are having the same issue.
