### ISSUE TITLE
Kindle Fire HD Issue playing HLS  storeMetaDataInBuffers failed w/ err -2147483648

### ISSUE THREAD

**Issue by biodatacomp** [google/ExoPlayer#972]
Getting error playing HLS on Kindle Fire HD7

11-19 17:31:16.492 1761-1761/tv.pluto.android I/ExoPlayerImpl: Init 1.4.2
11-19 17:31:16.791 1761-1761/tv.pluto.android I/OMXClient: Using client-side OMX mux.
11-19 17:31:16.823 1761-1761/tv.pluto.android I/MediaCodecList: itemAt(i) 7f000001, isEncoder 0 
11-19 17:31:16.840 1761-1761/tv.pluto.android I/dalvikvm: Could not find method android.media.MediaCodec.releaseOutputBuffer, referenced from method com.google.android.exoplayer.MediaCodecVideoTrackRenderer.renderOutputBufferV21
11-19 17:31:16.840 1761-1761/tv.pluto.android W/dalvikvm: VFY: unable to resolve virtual method 7928: Landroid/media/MediaCodec;.releaseOutputBuffer (IJ)V
11-19 17:31:16.840 1761-1761/tv.pluto.android D/dalvikvm: VFY: replacing opcode 0x6e at 0x0008
11-19 17:31:16.844 1761-1761/tv.pluto.android I/dalvikvm: Could not find method android.media.AudioTrack.write, referenced from method com.google.android.exoplayer.audio.AudioTrack.writeNonBlockingV21
11-19 17:31:16.844 1761-1761/tv.pluto.android W/dalvikvm: VFY: unable to resolve virtual method 7989: Landroid/media/AudioTrack;.write (Ljava/nio/ByteBuffer;II)I
11-19 17:31:16.844 1761-1761/tv.pluto.android D/dalvikvm: VFY: replacing opcode 0x6e at 0x0001
11-19 17:31:17.111 1761-3136/tv.pluto.android I/OMXClient: Using client-side OMX mux.
11-19 17:31:17.118 1761-3136/tv.pluto.android E/ACodec: [OMX.MTK.VIDEO.DECODER.AVC] storeMetaDataInBuffers failed w/ err -2147483648
11-19 17:31:17.122 1761-3117/tv.pluto.android E/MediaCodec: cabc file /sys/bus/omapdss/devices/display0/cabc_mode open error: No such file or directory!
11-19 17:31:17.122 1761-3135/tv.pluto.android D/MediaCodec: MediaCodec Start Playaback. Turning Dolby ON
11-19 17:31:17.122 1761-3135/tv.pluto.android I/MediaCodec: MediaCodec::sendDolbyProfile  ForwardUtilService started...for nProfile 0
11-19 17:31:17.124 1761-3135/tv.pluto.android I/MediaCodec: MediaCodec::sendDolbyProfile get ForwardUtilService replied with code 0 
11-19 17:31:17.152 1761-3136/tv.pluto.android D/ACodec: native_window_set_buffers_geometry W(1920), H(1088), Stride(1920), SliceH(1088)
11-19 17:31:17.308 1761-3117/tv.pluto.android I/OMXClient: Using client-side OMX mux.
11-19 17:31:17.333 1761-3149/tv.pluto.android I/OMXClient: Using client-side OMX mux.

**Comment by ojw28** [comment]
What version of Fire OS is this device running?

**Comment by ojw28** [comment]
By the way, it's very unclear to me whether the log you paste is the actual error (the specific line you refer to is normally harmless). Please always attach full bug reports rather than excerpts from logcat, as described [here](https://google.github.io/ExoPlayer/2015/10/01/reporting-issues.html).

**Comment by triwav** [comment]
I'll go ahead and chime in here. I've attached two bug reports. One for playing an HLS file like mentioned above and another for an MP4 file. Steps to reproduce are to clone the master branch of the ExoPlayer repo. I'm launching it in Eclipse after importing the both the library and demo project. For HLS I hit the Apple master playlist which is the first one. For MP4 I hit Big Buck Bunny under MISC. For the HLS it doesn't even try to play and the MP4 plays for under a second and then stops. This is a Fire HD 7 (4th Generation). It's running Fire OS 4 as Fire OS 5 is not available for me to test on this gen. It reports as 4.4.3. Here is the logcat output from trying to play the HLS file. The one thing I'm seeing that's standing out is the virtual methods can't be found. Could that be what's causing the issue? Let me know what else I need to provide I can verify that Exoplayer works fine on the Fire TV and Fire TV stick but the tablets have never worked for us.

```
11-30 11:40:52.424: I/ExoPlayerImpl(20707): Init 1.5.2
11-30 11:40:52.427: D/EventLogger(20707): start [0]
11-30 11:40:52.427: D/EventLogger(20707): state [0.00, false, P]
11-30 11:40:52.431: D/EventLogger(20707): state [0.00, true, P]
11-30 11:40:53.247: D/CRLSetManager(20707): getInstance binder: android.os.BinderProxy@41e89520
11-30 11:40:53.468: I/OMXClient(20707): Using client-side OMX mux.
11-30 11:40:53.481: I/MediaCodecList(20707): itemAt(i) 7f000001, isEncoder 0 
11-30 11:40:53.491: I/dalvikvm(20707): Could not find method android.media.MediaCodec.releaseOutputBuffer, referenced from method com.google.android.exoplayer.MediaCodecVideoTrackRenderer.renderOutputBufferV21
11-30 11:40:53.491: W/dalvikvm(20707): VFY: unable to resolve virtual method 1649: Landroid/media/MediaCodec;.releaseOutputBuffer (IJ)V
11-30 11:40:53.491: D/dalvikvm(20707): VFY: replacing opcode 0x6e at 0x0008
11-30 11:40:53.497: I/dalvikvm(20707): Could not find method android.media.AudioTrack.write, referenced from method com.google.android.exoplayer.audio.AudioTrack.writeNonBlockingV21
11-30 11:40:53.497: W/dalvikvm(20707): VFY: unable to resolve virtual method 199: Landroid/media/AudioTrack;.write (Ljava/nio/ByteBuffer;II)I
11-30 11:40:53.497: D/dalvikvm(20707): VFY: replacing opcode 0x6e at 0x0001
11-30 11:40:53.686: I/OMXClient(20707): Using client-side OMX mux.
11-30 11:40:53.697: D/EventLogger(20707): state [1.27, true, B]
11-30 11:40:53.697: D/EventLogger(20707): videoFormat [1.27, 0, 0]
11-30 11:40:53.698: I/OMXClient(20707): Using client-side OMX mux.
11-30 11:40:53.704: E/ACodec(20707): [OMX.MTK.VIDEO.DECODER.AVC] storeMetaDataInBuffers failed w/ err -2147483648
11-30 11:40:53.707: E/MediaCodec(20707): cabc file /sys/bus/omapdss/devices/display0/cabc_mode open error: No such file or directory!
11-30 11:40:53.708: D/MediaCodec(20707): MediaCodec Start Playaback. Turning Dolby ON
11-30 11:40:53.708: I/MediaCodec(20707): MediaCodec::sendDolbyProfile  ForwardUtilService started...for nProfile 0
11-30 11:40:53.712: I/MediaCodec(20707): MediaCodec::sendDolbyProfile get ForwardUtilService replied with code 0 
11-30 11:40:53.766: D/ACodec(20707): native_window_set_buffers_geometry W(1920), H(1088), Stride(1920), SliceH(1088)
11-30 11:40:53.882: D/EventLogger(20707): decoderInitialized [1.45, OMX.MTK.VIDEO.DECODER.AVC]
11-30 11:40:53.887: I/OMXClient(20707): Using client-side OMX mux.
11-30 11:40:53.901: D/EventLogger(20707): decoderInitialized [1.47, OMX.MTK.AUDIO.DECODER.AAC]
11-30 11:40:53.924: E/ACodec(20707): [OMX.MTK.VIDEO.DECODER.AVC] ERROR(0x80001005)
11-30 11:40:53.925: E/MediaCodec(20707): Codec reported an error. (omx error 0x80001005, internalError -2147483648)
11-30 11:40:53.926: E/ExoPlayerImplInternal(20707): Internal runtime error.
11-30 11:40:53.926: E/ExoPlayerImplInternal(20707): java.lang.IllegalStateException
11-30 11:40:53.926: E/ExoPlayerImplInternal(20707): 	at android.media.MediaCodec.dequeueInputBuffer(Native Method)
11-30 11:40:53.926: E/ExoPlayerImplInternal(20707): 	at com.google.android.exoplayer.MediaCodecTrackRenderer.feedInputBuffer(MediaCodecTrackRenderer.java:529)
11-30 11:40:53.926: E/ExoPlayerImplInternal(20707): 	at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:460)
11-30 11:40:53.926: E/ExoPlayerImplInternal(20707): 	at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431)
11-30 11:40:53.926: E/ExoPlayerImplInternal(20707): 	at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
11-30 11:40:53.926: E/ExoPlayerImplInternal(20707): 	at android.os.Handler.dispatchMessage(Handler.java:98)
11-30 11:40:53.926: E/ExoPlayerImplInternal(20707): 	at android.os.Looper.loop(Looper.java:145)
11-30 11:40:53.926: E/ExoPlayerImplInternal(20707): 	at android.os.HandlerThread.run(HandlerThread.java:61)
11-30 11:40:53.926: E/ExoPlayerImplInternal(20707): 	at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
11-30 11:40:53.926: E/MediaCodec(20707): cabc file /sys/bus/omapdss/devices/display0/cabc_mode open error: No such file or directory!
11-30 11:40:53.926: D/MediaCodec(20707): MediaCodec Release. Turning Dolby OFF
11-30 11:40:53.926: I/MediaCodec(20707): MediaCodec::sendDolbyProfile  ForwardUtilService started...for nProfile -1
11-30 11:40:53.927: I/MediaCodec(20707): MediaCodec::sendDolbyProfile get ForwardUtilService replied with code 0 
11-30 11:40:53.945: E/EventLogger(20707): playerFailed [1.52]
11-30 11:40:53.945: E/EventLogger(20707): com.google.android.exoplayer.ExoPlaybackException: java.lang.IllegalStateException
11-30 11:40:53.945: E/EventLogger(20707): 	at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:246)
11-30 11:40:53.945: E/EventLogger(20707): 	at android.os.Handler.dispatchMessage(Handler.java:98)
11-30 11:40:53.945: E/EventLogger(20707): 	at android.os.Looper.loop(Looper.java:145)
11-30 11:40:53.945: E/EventLogger(20707): 	at android.os.HandlerThread.run(HandlerThread.java:61)
11-30 11:40:53.945: E/EventLogger(20707): 	at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
11-30 11:40:53.945: E/EventLogger(20707): Caused by: java.lang.IllegalStateException
11-30 11:40:53.945: E/EventLogger(20707): 	at android.media.MediaCodec.dequeueInputBuffer(Native Method)
11-30 11:40:53.945: E/EventLogger(20707): 	at com.google.android.exoplayer.MediaCodecTrackRenderer.feedInputBuffer(MediaCodecTrackRenderer.java:529)
11-30 11:40:53.945: E/EventLogger(20707): 	at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:460)
11-30 11:40:53.945: E/EventLogger(20707): 	at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431)
11-30 11:40:53.945: E/EventLogger(20707): 	at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
```

[hls-bugreport.txt](https://github.com/google/ExoPlayer/files/47524/hls-bugreport.txt)
[mp4-bugreport.txt](https://github.com/google/ExoPlayer/files/47525/mp4-bugreport.txt)

**Comment by ojw28** [comment]
There are multiple issues with FireOS4's underlying media support / compatibility that require an unreasonably large amount of workaround code to handle. So, unfortunately, you shouldn't expect ExoPlayer to work correctly on FireOS4. FireOS5 resolved most of the underlying issues, and I would expect playback to be successful there.

I suggest you request to Amazon that they consider updating these devices to FireOS5, or that they backport their compatibility fixes to FireOS4.

**Comment by biodatacomp** [comment]
@ojw28 Just curious, if we know for sure that its an issue with FireOS4* , or its more attributed to the underlying MediaTek chipset / SOC and the devices using it

**Comment by triwav** [comment]
Good point. Like I said the Fire TV and Fire TV stick both worked fine on it when they were running Fire OS 4

**Comment by ojw28** [comment]
I don't know the answer to that question, but if you mean literally hardware when you say the underlying chipset, I think that's highly unlikely.
