### ISSUE TITLE
[Chromecast] ExoPlayer integration with the ShakaPlayer Receiver.

### ISSUE THREAD

**Issue by ProtoScott** [google/ExoPlayer#9723]
Has anyone done an implementation of ExoPlayer with the Shaka Receiver rather than the Chromecast default/custom receivers?

**Comment by tonihei** [comment]
There was some previous work in this area (see #5486), but this has been suspended and [deleted](go/gh/google/ExoPlayer/commit/7798c07f64d58a5363ff2af1a72cdcad9a8ae2de) and never published. We are more likely to continue improving the existing `CastPlayer` working with the default receiver.

**Comment by ProtoScott** [comment]
Okay thanks for the info, we're going to look into either update the existing CastPlayer to support a conversion to a Shaka MediaItem or look at updating the Shaka Receiver to support the ExoPlayer MediaItem.

**Comment by tonihei** [comment]
Closing because the question was answered.
