### ISSUE TITLE
Rotation metadata of video is ignored on Huawei devices (Android 8)

### ISSUE THREAD

**Issue by Saursinet** [google/ExoPlayer#9724]
I have a video recorded on an IPhone in portrait mode (rotation is set in metadata as 90°).
When I play it with ExoPlayer it shows a rotated video and stretched (see screenshot). I'd say that the phone just ignores the rotation.
![device-2021-11-24-093117](https://user-images.githubusercontent.com/10145464/143202533-b0253c91-6eab-429a-afd2-edfeab2f8585.png)

The bug appears on a Huawei p20 lite (Android 8) but there is no problem with OnePlus 6t nor Samsung S8.
We use ExoPlayer 2.15.1.

I saw the issue #8928 but it didn't seem to bring nowhere. And my issue is on Android 8+.

I investigated further and tried to analyse differences between two videos, one that works normally and one that doesn't on the Huawei device.

Here are the differences in the metadata (omitting dateCreation, lastEdited, etc..): 
<img width="1460" alt="Screenshot 2021-11-23 at 18 25 11" src="https://user-images.githubusercontent.com/10145464/143073794-c8889163-bc2d-4af2-864a-906e1cc7f499.png">
The video having the bug being the green version (1920x1080)

Here is the video https://drive.google.com/file/d/16q5r_nac_rOEkjA9msgr1bbuA2oEO8ko/view?usp=sharing

And here is a simple code to show that with minimal configuration we do have the bug on Huawei: https://github.com/Saursinet/ExoPlayerDemo

**Comment by tonihei** [comment]
Sounds like this device isn't applying the format's rotation correctly. I verified that ExoPlayer's parsing extracts the expected rotation degrees (=90), which is does and which is why it works on all other devices. You could report this to Huawei and ask them to fix it. But other than that, there is nothing we can do inside ExoPlayer to fix the problem.
