### ISSUE TITLE
Exoplayer compile time issue

### ISSUE THREAD

**Issue by hamedborna** [google/ExoPlayer#9728]
Hi guys

First of all sorry for my bad english , actually I faced issue with ExoPlayer when I try to run project. I tried so many thing in order to fixing issue but I couldn't succeed.. here is issue log :

/Users/home/Documents/projects/karafs-redesign/app/build/generated/data_binding_base_class_source_out/stagingGooglePlayDebug/out/ir/karafsapp/karafs/android/redesign/databinding/ExoSimplePlayerViewBinding.java:93: error: cannot find symbol
      PlaybackControlView exoController = rootView.findViewById(id);
      ^
  symbol:   class PlaybackControlView
  location: class ExoSimplePlayerViewBinding

**Comment by tonihei** [comment]
This sounds like a generic gradle or project setup question we can't help you with in detail. You probably need to make sure you have a dependency on ExoPlayer's UI module available at this code location and/or clean your build environment in case it has problems picking up recent changes.

**Comment by tonihei** [comment]
`PlaybackControlView` was also removed in ExoPlayer 2.12.0 because it was deprecated and replaced by `PlayerControlView`. So maybe you have recently upgraded and the class is now missing for this reason?
