### ISSUE TITLE
Dynamically load media items from internet

### ISSUE THREAD

**Issue by re-ovo** [google/ExoPlayer#9737]
I am implementing a music player, which has a "Personalized FM" function, which requests data from the back-end API to obtain **a song** information and then play it. 
I'm wondering whether ExoPlayer can dynamically load media items, and request the next MediaItem from the backend when the song ends or when the user clicks on the next song

**Comment by ojw28** [comment]
I would have thought you could implement this with application level logic on top of the player. Once you've made your API call to determine what the next media item is, you can add it to the player using [playlist functionality](https://exoplayer.dev/playlists.html).

It's unclear to me whether a deeper integration would be necessary, but if that's what you're trying to do then you could take a look at `ResolvingDataSource`. It might be possible to make your back-end API call within a `ResolvingDataSource` instance. There is some documentation [here](https://exoplayer.dev/customization.html#customizing-server-interactions) that may be useful (although isn't for exactly the use case you describe). There are also various closed issues on this issue tracker that are perhaps a bit closer.

**Comment by re-ovo** [comment]
> I would have thought you could implement this with application level logic on top of the player. Once you've made your API call to determine what the next media item is, you can add it to the player using [playlist functionality](https://exoplayer.dev/playlists.html).
> 
> It's unclear to me whether a deeper integration would be necessary, but if that's what you're trying to do then you could take a look at `ResolvingDataSource`. It might be possible to make your back-end API call within a `ResolvingDataSource` instance. There is some documentation [here](https://exoplayer.dev/customization.html#customizing-server-interactions) that may be useful (although isn't for exactly the use case you describe). There are also various closed issues on this issue tracker that are perhaps a bit closer.

It seems that ResolvingDataSource can only be used to dynamically load the MediaItem URL(?), I need to dynamically load the entire MediaItem

**Comment by ojw28** [comment]
Ah. You should probably just do that with application level logic on top of the player, in that case.
