### ISSUE TITLE
Caching All Videos But Playing Only single video when there is no network.

### ISSUE THREAD

**Issue by adnan94** [google/ExoPlayer#9738]
**Here is Caching Code**

private fun preCacheVideo(videosList: ArrayList<String>?) {
        var videoUrl: String? = null
        if (!videosList.isNullOrEmpty()) {
            videoUrl = videosList[0]
            videosList.removeAt(0)
        } else {
            stopSelf()
        }
        if (!videoUrl.isNullOrBlank()) {
            val videoUri = Uri.parse(videoUrl)
            val dataSpec = DataSpec(videoUri,0,200*1024)

            val progressListener =
                CacheWriter.ProgressListener { requestLength, bytesCached, newBytesCached ->
                    val downloadPercentage: Double = (bytesCached * 100.0
                            / requestLength)

                    Log.d(TAG, "downloadPercentage $downloadPercentage videoUri: $videoUri")
                }

            cachingJob = GlobalScope.launch(Dispatchers.IO) {
                cacheVideo(dataSpec, progressListener)
                preCacheVideo(videosList)
            }
        }
    }

    private fun cacheVideo(
        dataSpec: DataSpec,
        progressListener: CacheWriter.ProgressListener
    ) {
        runCatching {
            CacheWriter(
                cacheDataSourceFactory,
                dataSpec,
                true,
                null,
                progressListener
            ).cache()
        }.onFailure {
            it.printStackTrace()
        }
    }

**Here is Player Code**

    httpDataSourceFactory = DefaultHttpDataSource.Factory()
            .setAllowCrossProtocolRedirects(true)

        defaultDataSourceFactory = DefaultDataSourceFactory(
            requireContext(), httpDataSourceFactory
        )

        cacheDataSourceFactory = CacheDataSource.Factory()
            .setCache(simpleCache)
            .setUpstreamDataSourceFactory(httpDataSourceFactory)
            .setFlags(CacheDataSource.FLAG_IGNORE_CACHE_ON_ERROR)

        simpleExoPlayer = SimpleExoPlayer.Builder(requireContext())
            .setMediaSourceFactory(DefaultMediaSourceFactory(cacheDataSourceFactory)).build()

        val videoUri = Uri.parse(videoUrl)
        val mediaItem = MediaItem.fromUri(videoUri)
        val mediaSource = ProgressiveMediaSource.Factory(cacheDataSourceFactory).createMediaSource(mediaItem)

        playerView.player = simpleExoPlayer
        simpleExoPlayer.playWhenReady = true
        simpleExoPlayer.seekTo(0, 0)
        simpleExoPlayer.repeatMode = Player.REPEAT_MODE_OFF
        simpleExoPlayer.setMediaSource(mediaSource, true)
        simpleExoPlayer.prepare()

**Comment by adnan94** [comment]
https://github.com/iambaljeet/VideoPreLoading here is code which i am following

**Comment by adnan94** [comment]
val dataSpec = DataSpec(videoUri,0,200*1024)

after this line only one video playing but caching both 2 videos

**Comment by ojw28** [comment]
Please could you properly fill out the issue template when filing issues. In particular, please ensure you provide some concrete reproduction steps (e.g., a small sample project that we can check out as source code, which reproduces the issue). Just pasting a bunch of code into an issue tracker doesn't help us to efficiently investigate or answer any questions.

Please also avoid filing four issues that all appear to be about essentially the same thing. I will leave this one open for you to provide additional information in, including clear reproduction steps, and close the other two. Thanks!

**Comment by augustinePepul** [comment]
Im getting little slow when i load my list of videos in viewpager and I'm getting the Black screen for each videos.
