### ISSUE TITLE
Is there any way to use stepByCount like AVPlayer on iOS ?

### ISSUE THREAD

**Issue by eshkoliGilad** [google/ExoPlayer#974]
Hello, all.

Is there a way to jump forward or backward to a frame using frame-by-frame in a video file like in AVPlayer on iOS?

**Comment by ojw28** [comment]
There is no way to advance forward and backward by a single frame, no. Sorry!

**Comment by ptran-gpfw** [comment]
Its a little involved but I've been able to extend [MediaCodecVideoTrackRenderer](https://github.com/google/ExoPlayer/blob/master/library/src/main/java/com/google/android/exoplayer/MediaCodecVideoTrackRenderer.java#L376) to render one frame and then return false in processOutputBuffer. This is done with no audio renderer and my extended MediaCodecVideoTrackRenderer being the MediaClock.
