### ISSUE TITLE
Exoplayer can't play video (with mp3 audio), while VideoView can play it

### ISSUE THREAD

**Issue by ShkurtiA** [google/ExoPlayer#9740]
I have created a sample with both exoPlayer and android videoView. In exoPlayer it fails to play video on some specific devices (from crashlytics) and I have one device where I can reproduce it. 

One of them is (here VideoView works fine): 

Build: BAH-W09C100B257
Build fingerprint: 'HUAWEI/BAH/HWBAH-Q:7.0/HUAWEIBAH-W09/C100B257:user/release-keys'

The log message is: 

```
E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: MediaCodecAudioRenderer error, index=1, format=Format(2, null, null, audio/mpeg, null, -1, en, [-1, -1, -1.0], [2, 44100]), format_supported=YES
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:562)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:156)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecDecoderException: Decoder failed: OMX.google.mp3.decoder
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.createDecoderException(MediaCodecRenderer.java:918)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:799)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:982)
....
```

Sample:
```
        val player = ExoPlayer.Builder(requireContext()).build()
        videoExoView.setPlayer(player);
        val mediaItem: MediaItem = MediaItem.fromUri(videoUri)
        player.setMediaItem(mediaItem)
        player.prepare()
        player.play()   
```

ExoPlayer Verision: 2.16.1

The other device that I get from crashlytics are:

<img src="https://user-images.githubusercontent.com/8733915/144027285-c261f0f8-c67c-4940-8ca0-4ff7562f6d67.png" width="380">

I have seen previous issues related to this problem and I understand that you apply a workaround for a specific device, but in my case it would be difficult to gather all the devices. Is there a way to fix this problem for most of devices?

I will send you and email with the `adb bugreport` and the attached video

The `ffmpeg -i` of the video is this:

```
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 's312154.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.29.100
  Duration: 00:00:46.84, start: 0.000000, bitrate: 1566 kb/s
  Stream #0:0(eng): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1920x1080, 1174 kb/s, 30 fps, 30 tbr, 15360 tbn, 60 tbc (default)
    Metadata:
      handler_name    : ?Mainconcept Video Media Handler
      vendor_id       : [0][0][0][0]
  Stream #0:1(eng): Audio: mp3 (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 383 kb/s (default)
    Metadata:
      handler_name    : #Mainconcept MP4 Sound Media Handler
      vendor_id       : [0][0][0][0]

```

**Comment by ojw28** [comment]
> I have seen previous issues related to this problem and I understand that you apply a workaround for a specific device

This is not the case for this issue. It looks like the standard mp3 software decoder is unable to decode the audio stream in the sample file you've provided. There's not much we can do to work around that on devices that don't also ship with additional mp3 decoders. You will likely find that many devices are affected by the issue.

Whenever I try and re-encode the sample, the resulting output file does play successfully. This is true even if I keep the audio in mp3 when re-encoding. For example, this command produces a file that plays successfully:

```
ffmpeg -i s312154.mp4 -c:a mp3 output.mp4
```

It's notable that your file has audio encoded at a very high bitrate for mp3:
```
Stream #0:1(eng): Audio: mp3 (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 383 kb/s (default)
```
That bitrate is actually beyond what the standard defines, as per [Wikipedia](https://en.wikipedia.org/wiki/MP3#Bit_rate), and so mp3 decoders are not required to be able to decode them successfully:

> Non-standard bit rates up to 640 kbit/s can be achieved with the LAME encoder and the freeformat option, although few MP3 players can play those files. According to the ISO standard, decoders are only required to be able to decode streams up to 320 kbit/s.

The command I've provided above re-encodes the audio at 128kb/s, so perhaps that's what fixes the issue.

I would suggest:

1. Re-encoding the content to use AAC, which is far more standard than embedding mp3 inside mp4.
1. If using mp3, use a bitrate that's required to be supported as per the specification.

**Comment by ShkurtiA** [comment]
Thanks for the investigation, its very helpful
