### ISSUE TITLE
Want to achieve the same page, play multiple videos at the same time

### ISSUE THREAD

**Issue by iqiluwxy** [google/ExoPlayer#9742]
Requirements describe

Play multiple videos simultaneously on the same page

scenario

monitoring

Whether other apps are implemented

Yes.
Screenshot or video description
[https://pointshow.oss-cn-hangzhou.aliyuncs.com/20-08-05-18-04-07.mp4]
[https://user-images.githubusercontent.com/26036692/89399776-80181a80-d745-11ea-947d-6e47b186b88a.png](url)

**Comment by ojw28** [comment]
If the streams are coming from separate sources, you'll need 4 instances of the player. You'll probably have to customize the UI components for your use case as well, but it should be possible to do this yourself (possibly forking the UI components provided in ExoPlayer's UI module as a starting point).

Note that some Android devices may only be able to provide a limited number of simultaneous video decoders, so you may run into some device limitations, particularly if the streams are each at a high resolution.

I don't think you need any functionality implemented directly into the ExoPlayer library to build what you're trying to build, so marking this as a "question". We're unable to provide detailed guidance on how to build each individual app, but if you have any questions specifically about ExoPlayer, please let us know.

**Comment by chowg1762** [comment]
Hello, I don't 100% understand the multiple videos simultaneously in the same view but if you mean one ExoPlayer supports multiple videos, I think that you would be better to follow the @ojw28 's suggestion.

Making multiple videos to play on the one player has a lot of things to be considered.  For example, if you want to play two videos in the single player, and each video has different framerate, the player should synchronize its framerate when rendering the frames on the surface. 

However, if you use the separated players on each video, the each player has its own extractor, decoder, and output surface, so it doesn't need to synchronize its frame rate and other things. I think @ojw28 's suggestion is the best.
