### ISSUE TITLE
Audio Secure

### ISSUE THREAD

**Issue by SudoDios** [google/ExoPlayer#9743]
Hello.
how to secure play an audio.
That is, how do we stop the audio record while it is being recorded (from **mic** source or **device system sound**) ?

**Comment by ojw28** [comment]
To prevent system capture, you can use the can configure the audio capture policy [as documented here](https://developer.android.com/guide/topics/media/av-capture). For example, by adding `android:allowAudioPlaybackCapture=false to your `AndroidManifest.xml` file. You can also prevent capture on a single ExoPlayer instance:

```
val audioAttributes: AudioAttributes =
        AudioAttributes.Builder()
                .setAllowedCapturePolicy(ALLOW_CAPTURE_BY_NONE)
                .setUsage(C.USAGE_MEDIA)
                .setContentType(C.CONTENT_TYPE_MOVIE)
                .build()
exoPlayer = ExoPlayerFactory.newSimpleInstance(this, trackSelector, loadControl)
exoPlayer.audioAttributes = audioAttributes
...
```

I don't think there's a way to disable the microphone to prevent capture of audio from the environment, including audio that your app might be playing. In any case, someone wishing to capture the audio could just get a second device and capture it with that, and preventing this is clearly impossible.

**Comment by SudoDios** [comment]
Thanks. 👌👌🌹

**Comment by SudoDios** [comment]
I tested this samples and working.
But in screen recorder on xiaomi devices not work.
You have a solution ?

**Comment by ojw28** [comment]
Are you sure the Xiaomi app isn't capturing audio using the microphone? It should be easy for you to test this by making additional noise whilst recording. If it is, then there's nothing that can be done to prevent this, as already noted above.

If you're sure that the Xiaomi app is capturing audio internally, without using the microphone, then that's an issue with the underlying platform and you should probably file a bug about it here: https://issuetracker.google.com/issues/new?component=898361&template=1458029%2B.
