### ISSUE TITLE
exception that can't be caught

### ISSUE THREAD

**Issue by ghotik** [google/ExoPlayer#9744]
Hi, this is my first post here, so please forgive me if I perhaps break the guidelines a little.

I'm developing a security cams viewer that should show up to 4 rtsp live streams on the same surface.
The environment where this Android App runs is far from clean, there are etherogeneous cameras, bad configurations, network (WLan) errors and so forth, so I would expect that not all cameras may work perfectly. In that case, it would be acceptable to have some "black hole" on the screen about the "bad" cameras.
Unfortunately, some situations generate a "AndroidRuntime: FATAL EXCEPTION" that I couldn't envelope in a try/catch block to insulate its effect and that causes the App crash.
I add that the App is perfectly able to show 4 live streams for properly configured camera devices, so I assume that the coding is fine.

This is an extract of the viewer code, the method that gets called up to 4 times for different uri and 4 different SurfaceView aligned in a vertical LinearLayout:

        try {
            player = new ExoPlayer.Builder(s.getContext()).build();
            MediaSource mediaSource =
                    new RtspMediaSource.Factory().setForceUseRtpTcp(true)
                            .createMediaSource(MediaItem.fromUri(uri));
            player.setMediaSource(mediaSource);
            player.prepare();
            player.setVideoSurfaceView(findViewById(surfaceView));
            player.setPlayWhenReady(true);
        }
        catch(java.lang.IllegalArgumentException e){
            e.printStackTrace();
        }
        catch(Exception e){
            e.printStackTrace();
        }

this is the gradle configuration where I used the most recent version bbecause of the need of support of rtsp autenticated streams:

    implementation 'com.google.android.exoplayer:exoplayer-core:2.16.1'
    implementation 'com.google.android.exoplayer:exoplayer-dash:2.16.1'
    implementation 'com.google.android.exoplayer:exoplayer-ui:2.16.1'
    implementation 'com.google.android.exoplayer:exoplayer-rtsp:2.16.1'

In attach I add the logcat trace about two different tests, exo2exception.txt about a configuration with 4 cameras and exo2exception_cam100.txt about a configuration with a single "bad" camera.

The question is: is there a way to prevent uncaught exceptions in Exoplayer components?

[exo2exception.txt](https://github.com/google/ExoPlayer/files/7632968/exo2exception.txt)
[exo2exception_cam100.txt](https://github.com/google/ExoPlayer/files/7632969/exo2exception_cam100.txt)

**Comment by ojw28** [comment]
@claincly - Please take a look. I'm not sure if this indicates the stream is malformed, but even if it does, we should make sure the error is propagated as a playback failure rather than causing process death.

**Comment by claincly** [comment]
Looking at `exo2exception.txt`, the check at `RtspMediaTrack.java:129` failed. The check is for "whether the RTSP payload type is smaller than 96". I'll change it on our side to handle this error better. If you are in a time sensitive situation, I suggest removing `RtspMediaTrack.java:129` yourself.

In the meantime, it might be helpful to post the RTSP messages for further investigation.

The easiest way is to use the `RtspMediaSource.Factory` method `setDebugLoggingEnabled()`

That is, set the media source factory when building the ExoPlayer instance, like this:

```
     SimpleExoPlayer player =
          new ExoPlayer.Builder(/* context= */ this)
              .set... // all other customization
              .setMediaSourceFactory(new RtspMediaSource.Factory().setDebugLoggingEnabled(true))
              .build()
```

**Comment by ghotik** [comment]
Thanks for the really fast answer.
Today I'm on smart work with no direct access to the cameras, but luckily I saved a few logs grabbed with the Packet Capture App.
Tomorrow I could do more tests and publish mode data, if needed.

the attached files camera100crash.txt and  camera100crash(2).txt show the packet flow between the App and the camera at final ip 100 that crashed the App. As far as I could remember, that should be a Bochs ip camera. The file camera105ok.txt instead shows a successful streaming session from an Axis ip camera

[camera100crash.txt](https://github.com/google/ExoPlayer/files/7633491/camera100crash.txt)
[camera105ok.txt](https://github.com/google/ExoPlayer/files/7633492/camera105ok.txt)
[camera100crash(2).txt](https://github.com/google/ExoPlayer/files/7633493/camera100crash.2.txt)
.

**Comment by claincly** [comment]
From your logs, the failed case has line in the SDP (in DESCRIBE response)
```
a=rtpmap:35 H264/90000
```

where the successful case has line
```
a=rtpmap:96 H264/90000
```

The only difference is the number 35 and 96. This number is used for an RTP receiver to determine what payload is being received. Please find the mapping table [here](https://www.iana.org/assignments/rtp-parameters/rtp-parameters.xhtml#rtp-parameters-1). In short, if a client sees payload type 34, it can be certain that the payload is H263 data. However, H264 is must use a "dynamic" payload type, meaning the payload type has to be between 96 and 127. As such, using 35, an unassigned value, is not valid per RTSP/RTP spec.

That said, our RTSP implementation does not use the payload type number to determine the actual payload type, so it is OK for us to drop the check.

**Comment by ghotik** [comment]
Thank you again. With no forecast of a next release I tried to make the change by myself, following your instructions and those in the project pages. I git-pulled a copy of the project in a folder on my project, located the RtspMediaTrack.java:129 and commented it, then I tried to link my project with this forked version of EXOPlayer.
Sadly, I couldn't get a result despite many attempts.
Linking the two projects in Android Studio this way failed:

    gradle.ext.exoplayerModulePrefix = 'exoplayer-'
    apply from: file("$rootDir/../SC2RtspX4EXO/ExoPlayer/core_settings.gradle")

    implementation project(':exoplayer-library-common')
    implementation project(':exoplayer-library-core')
    implementation project(':exoplayer-library-dash')
    implementation project(':exoplayer-library-rtsp')
    implementation project(':exoplayer-library-ui')

the error message:

   Gradle sync failed: Could not find method include() for arguments [:exoplayer-library-common] on project ':app' of type org.gradle.api.Project.

I also tried to build the EXOPlayer project alone and locate and copy the necessary modules, but I couldn't find any rtsp library (.jar or .aar or whatever else?) in the file system.

Please, can you help me to build this forked release connected to my project (or publish a r2.16.2 release with the enhancement)?

**Comment by icbaker** [comment]
@ghotik Please file a new issue about your problems when depending on a local copy of the ExoPlayer library (it's probably not related to RTSP, so better to keep it separate). You will need to include a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that demonstrates the problem in a way that we can build locally. 

This could be an Android Studio project on GitHub, or zipped up and sent to dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Please also update the new issue to indicate you’ve done this.
