### ISSUE TITLE
Retrieving metadata from video without playback

### ISSUE THREAD

**Issue by sanojlawrence** [google/ExoPlayer#9745]
As mentioned here https://exoplayer.dev/retrieving-metadata.html#without-playback how can i retrieve metadata without playback ?

here is what i tried:

````
ListenableFuture<TrackGroupArray> trackGroupsFuture =
                MetadataRetriever.retrieveMetadata(this, mediaItem);
        Futures.addCallback(trackGroupsFuture, new FutureCallback<TrackGroupArray>() {
            @Override
            public void onSuccess(TrackGroupArray trackGroups) {
                Log.d(TAG, "onSuccess: ");
                for(int i = 0; i < trackGroups.length; i++){
                    String format = trackGroups.get(i).getFormat(0).sampleMimeType;
                    String lang = trackGroups.get(i).getFormat(0).language;
                    String id = trackGroups.get(i).getFormat(0).id;

                    if(format.contains("audio") && id != null && lang != null){
                        Log.d(TAG, "onSuccess: " + lang + " " + id);
                    }
                }
            }

            @Override
            public void onFailure(@NonNull Throwable t) {
                //handleFailure(t);
                Log.d(TAG, "onFailure: " + t);
            }
        }, executor);
````

I coudn't get any data ?. Is there any documentation, i looked at demo app and there is no example for that so kindly help me through  this.

**Comment by ojw28** [comment]
I copy/pasted your code and it worked fine for me. Maybe the piece of content you're testing with just doesn't define a format `lang` for its audio tracks. Or format `id`. Your code only prints a line if both of these fields are non-null.

If you have a piece of content where you know both of these fields should be non-null, and no log line is being printed, then please share it with us and we'll take a look.

**Comment by sanojlawrence** [comment]
Am not sure what mistake I did, can you kindly please provide a small gist https://gist.github.com/
For retrieve metadata that would be so great full.
And thanks for your guidance.

**Comment by ojw28** [comment]
As above, I copy/pasted your code and it worked fine. If you'd like us to investigate then you need to provide clearer reproduction steps, including the piece of media that you're using when you reproduce the problem.
