### ISSUE TITLE
Decrypt HLS AES stream with external key

### ISSUE THREAD

**Issue by katerynapeikova** [google/ExoPlayer#9746]
HLS file
```
#EXTM3U
#EXT-X-VERSION:5
#EXT-X-STREAM-INF:BANDWIDTH=319747,CODECS="mp4a.40.34"
chunklist_w1971464514_tkd293emF0b2tlbnN0YXJ0dGltZT0xNjM4MzcxNjAzJndvd3phdG9rZW5lbmR0aW1lPTE2MzgzODk2MDMmd293emF0b2tlbmhhc2g9ZHhhUjMxSExLNFA1ZlZraGdoU0lQSDNwWE80TFFhQnRmREtSZXQ3QVF3Nm53Q01yaFRtWTdJc2FlVTdTbUc5dQ==.m3u8
```
Stream is encrypted with AES-128. There is no DRM server. (The stream engine is wowza). 

I have to retrieve decryption key from separate end-point from our BE.

How can I manually set decryption key in ExoPlayer? Should there be additional keys in HLS file (i.e. encryption method)?

**Comment by ojw28** [comment]
In HLS you're supposed to specify the key(s) within the media playlist files, as per the [HLS RFC](https://datatracker.ietf.org/doc/html/rfc8216#section-4.3.2.4). The media playlist file in your case is the one located at `chunklist_w1971464514_tkd293emF0b2tlbnN0YXJ0dGltZT0xNjM4MzcxNjAzJndvd3phdG9rZW5lbmR0aW1lPTE2MzgzODk2MDMmd293emF0b2tlbmhhc2g9ZHhhUjMxSExLNFA1ZlZraGdoU0lQSDNwWE80TFFhQnRmREtSZXQ3QVF3Nm53Q01yaFRtWTdJc2FlVTdTbUc5dQ==.m3u8`. You can see an example [8.3 of the spec](https://datatracker.ietf.org/doc/html/rfc8216#section-8.3).

It's probably possible to convince ExoPlayer to use external keys one way or another. https://github.com/google/ExoPlayer/issues/4590#issuecomment-408763177 suggests injecting a custom `HlsPlaylistParser`, for example. This (and other approaches) are non-standard, and are not something we can dedicate time to helping with.
