### ISSUE TITLE
seekToPrevious() in PlayerControlView can't change to the previous mediaItem

### ISSUE THREAD

**Issue by lizebinbin** [google/ExoPlayer#9751]
I'm used PlayeControlView in the xml layout, when I clicked previous button, it's just seek to the start of current mediaItem.

I find that there is a method `seekToPreviousMediaItem()` , but in PlayeControlView, it's called `seekToPrevious()`, then it's will get the current playing position and judge is change to previous or seek to 0 of current item.

I just want to change the previous item, but I can't control it if I use PlayeControlView ,since I can't override the onClick()

**Comment by ojw28** [comment]
You can achieve this by wrapping the player in a `ForwardingPlayer`, and overriding the `seekToPrevious()` behavior:

```
Player forwardingPlayer = new ForwardingPlayer(player) {
  @Override
  public long getMaxSeekToPreviousPosition() {
      return 0;
  }
  @Override
  public final void seekToPrevious() {
    seekToPreviousMediaItem();
  }
};
playerView.setPlayer(forwardingPlayer);
```

**Comment by lizebinbin** [comment]
than

> You can achieve this by wrapping the player in a `ForwardingPlayer`, and overriding the `seekToPrevious()` behavior:
> 
> ```
> Player forwardingPlayer = new ForwardingPlayer(player) {
>   @Override
>   public long getMaxSeekToPreviousPosition() {
>       return 0;
>   }
>   @Override
>   public final void seekToPrevious() {
>     seekToPreviousMediaItem();
>   }
> };
> playerView.setPlayer(forwardingPlayer);
> ```

Thanks～
