### ISSUE TITLE
Why 2.16.1 Removed ControlDispatcher and DefaultControlDispatcher

### ISSUE THREAD

**Issue by greyski** [google/ExoPlayer#9756]
We've just upgraded ExoPlayer from `2.14.2` to `2.16.1` and were using the `DefaultControlDispatcher` to listen for callbacks made from the "play"/"pause" buttons found in the `PlayerControlView` (for example, we have context logging and a few other state related changes we want to make off of those callbacks).

Now in `2.16.1` we no longer have those callbacks as the `DefaultControlDispatcher` was removed from the API. This means we've had to:

1. Grab the views ourselves via `findViewById`
2. Attach our own onClickListener
3. Essentially copy-paste the logic being done under-the-hood in the `PlayerControlView` so as not to change any functionality

While the commit that made the change suggests "...use the `ForwardingPlayer`" this doesn't actually provide us the functionality of listening for the onClick event for play/pause.

Is this the desired API change? If so, that's fine, it's just unfortunate that we no longer have a way to both:

1. Let the play/pause buttons behave as-is under-the-hood (ie invoke the necessary player callbacks)
2. Listen for when these buttons are pressed

For example, under-the-hood in `PlayerControlView` we see:
```

  private void dispatchPlay(Player player) {
    @State int state = player.getPlaybackState();
    if (state == Player.STATE_IDLE) {
      player.prepare();
    } else if (state == Player.STATE_ENDED) {
      seekTo(player, player.getCurrentMediaItemIndex(), C.TIME_UNSET);
    }
    player.play();
  }

  private void dispatchPause(Player player) {
    player.pause();
  }
  ```
  This happens when play/pause is pressed. It's easy to repro the pause code, but to copy and paste this play code into our own onClickListener feels dirty. This is where the dispatcher used to live where we could let the `PlayerControlView` invoke the appropriate player callbacks and simply listen to the onClick events without having to "reinvent the wheel".

**Comment by marcbaechinger** [comment]
You can wrap the player in a [`ForwardingPlayer`](https://github.com/google/ExoPlayer/blob/7fe9ecc1c592b758e76f6b458e0dc43cce282e5f/library/common/src/main/java/com/google/android/exoplayer2/ForwardingPlayer.java) and set the `ForwardingPlayer` to the `PlayerControlView` instead. You can then intercept any call to the forwarding player by overriding the methods of `ForwardingPlayer`

**Comment by greyski** [comment]
@marcbaechinger `ForwardingPlayer` doesn't provide the `onPlaystateToggled(boolean)` method (the callback we listened to in `DefaultControlDispatcher`) which is effectively called from inside `PlayerControlView` when the UI buttons were clicked and conveniently invoked the expected state changes to the `ExoPlayer`.

We want to grab the click event from the play/pause button in `PlayerControlView` without having to:

1. Create our own onClickListener
2. Copy-paste the expected callbacks found inside the `PlayerControlView` class

The `DefaultControlDispatcher` worked around this and the `ForwardingPlayer` doesn't provide a solution for this. Or at least I don't immediately see a method that parallels these callbacks.

**Comment by marcbaechinger** [comment]
Hmmm, accept my apologies, I don't know of a `onPlaystateToggled` method. I looked into the [`DefaultControlDispatcher` of 2.14.2.](https://github.com/google/ExoPlayer/blob/r2.14.2/library/common/src/main/java/com/google/android/exoplayer2/DefaultControlDispatcher.java) and couldn't find it. Also not in `PlayerView` or `PlayerControlView` of 2.14.2.

I'm trying to understand. So please bear with me, if I may ask silly questions. :) 

When in 2.16.1 a user clicks the play button, the `ComponentListener.onClick(View)` method is called which delegates to [`dispatchPlay()`](https://github.com/google/ExoPlayer/blob/r2.16.1/library/ui/src/main/java/com/google/android/exoplayer2/ui/PlayerControlView.java#L1348) like you describe. Then the logic in `dispatchPlay` is executed and calls the player method `prepare()`, `seekTo` or `play` according to the current state of the player.

For my understanding this works in the same way as before with the exception, that instead of calling the `ControlDispatcher` now the player is called directly which can now be a `ForwardingPlayer` that receives these calls.

In 2.14.2 the `onClick` method could not be intercepted and `dispatchPlay()` was called from there as well AFAIU. 

Maybe I need a nudge regarding `onPlaystateToggled(boolean)` that you are mentioning.

**Comment by greyski** [comment]
Oh shoot, I'm sorry I referenced one of my own wrapping methods. I apologize. Let me clarify a few things:

So looking at `2.14.2` we have this method in `PlayerControlView` (added comments are my own)

```
  private void dispatchPlay(Player player) {
    @State int state = player.getPlaybackState();
    if (state == Player.STATE_IDLE) {
      if (playbackPreparer != null) {
        playbackPreparer.preparePlayback();
      } else {
        controlDispatcher.dispatchPrepare(player);
      }
    } else if (state == Player.STATE_ENDED) {
      seekTo(player, player.getCurrentWindowIndex(), C.TIME_UNSET);
    }
    controlDispatcher.dispatchSetPlayWhenReady(player, /* playWhenReady= */ true); // <= this was helpful for us to effectively listen to play/pause click events without having to make all the above player callbacks
  }
  
    private void dispatchPause(Player player) {
    controlDispatcher.dispatchSetPlayWhenReady(player, /* playWhenReady= */ false); // <= same here
  }
  ```
  
In `2.16.1` the `DefaultControlDispatcher` class is gone so we no longer get this convenient callback for when the play/pause is clicked on the control view. So yes `ForwardingPlayer` has `setPlayWhenReady` however that's no longer being called by the `PlayerControlView`. Even though `player.play()` and `player.pause()` are called in the latest `PlayerControlView` (which invokes `setPlayWhenReady`), this doesn't let us distinguish play/pause from the control UI vs other consumer/lifecycle methods (ie we call these methods in other locations of our codebase).

I was also looking at the code change and noticed, perhaps we were just fortunate to have `dispatchSetPlayWhenReady` only being invoked by both the `dispatchPlay` and `dispatchPause` callbacks found in `PlayerControlView` as it gave us a convenient method to listen for when the play/pause buttons were clicked.

Maybe my question is more of a feature request:

Ability to listen to when the play/pause buttons in `PlayerControlView` are clicked, without overwriting the `onClickListener` set inside the class. If that makes sense?

**Comment by marcbaechinger** [comment]
If you use a `ForwardingPlayer` exclusively for being used to `playerView.setPlayer(yourForwardingPlayer)` then you know that it is called from the control view only. All your other call sites do not need to go through the forwarding player but just use the plain player. So you would know in the forwarding player these calls come from the player view. I think this could work if I understand correctly.

**Comment by greyski** [comment]
Oh, I think I understand now. Haha I like how it took like 2+ times for this `ForwardingPlayer` concept to finally hit home. Ok, I see.

I guess the weird part is that we get ALL these callbacks that we won't use, but that's not a huge deal. Ok, so for future readers, I'll do something _like_ this inside my class extending `PlayerControlView`
```
    private var forwardingPlayer: ForwardingPlayer? = null

    override fun setPlayer(player: Player?) {
        player?.let {
            forwardingPlayer = object : ForwardingPlayer(player) {
                override fun play() {
                    super.play()
                    // handle play action
                }

                override fun pause() {
                    super.pause()
                    // handle pause action
                }
            }
        }
        super.setPlayer(player)
    }

    override fun getPlayer(): Player? {
        return forwardingPlayer?.wrappedPlayer
    }
```
Thanks for your help @marcbaechinger!

Edit: I should probably reset `forwardingPlayer` to null when `player` is null
