### ISSUE TITLE
Depend on a local copy of ExoPlayer

### ISSUE THREAD

**Issue by ghotik** [google/ExoPlayer#9761]
Hi, thank you again for your wonderful support.

Following the bug #9744 I tried to follow your advice and fix the rtsp module as you suggested in a local branch of ExoPlayer, this up to when the fix will be merged in the mainstream release.
I found a guide [here](https://medium.com/google-exoplayer/howto-2-depend-on-a-local-checkout-of-exoplayer-bcd7f8531720) and started to follow the steps.
I cloned the v2.16.1 release in a local folder, then modified my project settings.gradle file as indicated and sync-ed the project.
Unfortunately I got this error message:

`Gradle sync failed: Could not find method include() for arguments [:exoplayer-library-common] on project ':app' of type org.gradle.api.Project. 
`
I'm using AndroidStudio Arctic Fox 2020.3.1 patch 2 
The search on the web for similar problems suggested to use .\gradlew directly from the command prompt, but the method didn't work giving a similar error.

Can you help me?

**Comment by zhoujielun111** [comment]
谢谢啦！邮件我已经收到了！！

**Comment by icbaker** [comment]
As requested in https://github.com/google/ExoPlayer/issues/9744#issuecomment-986693988, please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that demonstrates the problem in a way that we can build locally. 

This could be an Android Studio project on GitHub, or zipped up and sent to dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Please also update this issue to indicate you’ve done this.

**Comment by ghotik** [comment]
The sample project was dropped on GitHub here: https://github.com/ghotik/RtspPlayerX4
Note: because the Android Studio project includes many files automatically generated, I could not push the single files, so I created the project with a single .rar archive holding everything.
I Git-cloned the EXOPlayer project in the C:\exoplayer folder of my system and tried to build the project in attach, receiving the reported error 

Gradle sync failed: Could not find method include() for arguments [:exoplayer-library-common] on project ':app' of type org.gradle.api.Project.

In the app build.gradle file you can find the commented working references to the GitHub EXOPlayer project and, just below and uncommented, the new references to the EXOPlayer local cloned release.

**Comment by icbaker** [comment]
I don't have the ability to open .rar files - it's a proprietary format with very limited support on the OSes that I'm using.

It's unclear to me why you need to create an archive before you can push to GitHub, git & GitHub can generally handle quite a high number of individual files in a repository.

Please either use a more open archive format (zip, tarball/gzip) or upload the project files directly to GitHub without archiving them.

Or if it would be easier, maybe you can just post here the full content of your `settings.gradle` file that you've edited as described in the relevant section of the README: 
https://github.com/google/ExoPlayer/blob/release-v2/README.md#locally

**Comment by ghotik** [comment]
I apologize for the mess caused by my poor knowledge of the git protocol.
I just now committed the zipped archive to the project (file SC2RtspX4EXO.zip). Please, ignore the other file SC2RtspX4EXO.rar. Just use this project on GitHub as a simple way to transfer the file. I'm going to delete it as soon as no longer needed.
The changes that made a working project linking EXOPlayer from GitHub into a troublesome project that couldn't link a local branch of EXOPlayer are made in the app/build.gradle file, you can find there the working commented lines and the non-working new references to EXOPlayer local project. The local branch of EXOPlayer was stored in my build machine in C:\exoplayer

**Comment by icbaker** [comment]
You haven't correctly followed the instructions that you and I both linked (I suggest you follow mine though, they're likely to be more up-to-date than a blog post from 2017).

You've added this snippet to the app-level `build.gradle` file. As both guides say, you need to add it to the project's `settings.gradle` file instead:
```
gradle.ext.exoplayerRoot = 'c:/exoplayer/ExoPlayer'
gradle.ext.exoplayerModulePrefix = 'exoplayer-'
apply from: new File(
    gradle.ext.exoplayerRoot, 'core_settings.gradle')
```

Please try that.

**Comment by ghotik** [comment]
Wow, thank you, it finally worked!!
Now I will be able to make my own patches to the sources, and of course whenever I'll find anything worth mentioning from my troublesome testbed I'll keep in touch and let you know, EXOPlayer deserves first class improvements.
Also, I'll try to polish my test project and pull it to GitHub, just in case anyone could be interested (display of 4 rtsp live streams could be common among security and surveillance systems).

**Comment by icbaker** [comment]
Glad you got it working!
