### ISSUE TITLE
issue with Closed Caption for  DRM(WIDEVINE) content 

### ISSUE THREAD

**Issue by kunapuligayathri** [google/ExoPlayer#9763]
the issue is that we are not getting closed captions for a DRM (widevine) media  item
I have tried using the the license URl and the Stream url inside the demo application.. was not able to get the closed captions over there too
but the same streams are showing cc in bitmovin(https://bitmovin.com/demos/drm)
you can enable subtitles from settings button in bitmovin

since it is protected content:
 will share the Stream Url and Liscense URL in mail

ExoPlayer version number -- 2.10 
demo app exoplayer version : 2.15
- Android version -- All versions
- Android device  --  All devices

**Comment by icbaker** [comment]
I can reproduce that no text track is detected by ExoPlayer (2.16.1) when playing the provided content, while the bitmovin player does allow selection of a CC1 track:
```
TextRenderer []
```

When I look at the manifest I don't see any explicit text tracks, nor any `<Accessibility ...>` nodes on any of the video tracks. @ojw28 can comment further on whether this content is in-line with the DASH spec or not.

**Comment by ojw28** [comment]
If the captions are embedded 608, then DASH-IF interoperability points require that corresponding `Accessibility` elements are specified in the manifest. See section 6.4.3 of https://dashif.org/docs/DASH-IF-IOP-v4.3.pdf. See in particular 6.4.3.3 and the examples in 6.4.3.5. ExoPlayer requires such `Accessibility` elements to detect the existence of captions in the stream.

I think the fix here is to correctly include `Accessibility` elements in the manifest.
