### ISSUE TITLE
Numbers in rew / fwd button not visible in dark mode

### ISSUE THREAD

**Issue by tobiasKaminsky** [google/ExoPlayer#9765]
On Exoplayer 2.16.1:

Light mode:
![image](https://user-images.githubusercontent.com/5836855/145064258-45a2132a-53fa-47e0-a1d9-79d24334fd48.png)

Dark mode:
![image](https://user-images.githubusercontent.com/5836855/145064217-448adbc5-0528-45c6-9215-804f1aec759a.png)

It seems that the numbers are adapted to black/white depending on light/dark mode.

(ref: https://github.com/google/ExoPlayer/blob/3509f50783967f8de23db17ea5c4b65732434dd0/library/ui/src/main/res/values/styles.xml#L97)

**Comment by ojw28** [comment]
Could you provide complete steps explaining how to reproduce this? E.g., what device are you using, how are you enabling night mode, and anything else relevant.

**Comment by ojw28** [comment]
I can reproduce this when using:
```
<style name="AppTheme" parent="Theme.MaterialComponents.DayNight">
```
It doesn't reproduce when using:
```
<style name="AppTheme" parent="Theme.AppCompat.DayNight">
```
Nevertheless, please confirm your exact use case.

**Comment by tobiasKaminsky** [comment]
This is happening in https://github.com/nextcloud/android
and we use
https://github.com/nextcloud/android/blob/bcafbbbd5ba7606dcd658f573500921b504aca76/src/main/res/values/styles.xml#L23
