### ISSUE TITLE
getMetrics usage for MediaCodecAdapter

### ISSUE THREAD

**Issue by harini113** [google/ExoPlayer#9766]
is the api getMetrics() supported with the new MediaCodecAdapter  in exoplayer library 2.15.1 or newer

I have been using the getMetrics() api to retrieve information like Encoder/Decoder/Ht/Width and other information for the codec created. But in the new library, we migrated to using MediaCodecAdapter instead of MediaCodec. I do not see the getMetrics api supported for this? Is this something that will be added in future versions or is there a different approach for usage of this api.

**Comment by harini113** [comment]
hi christosts, Any update on the usage?

**Comment by christosts** [comment]
We will add getMetric() on MediaCodecAdapter - I will post an update once the commit is submitted.

**Comment by christosts** [comment]
Please see the commit linked above - the API will be available on the next release

**Comment by harini113** [comment]
thank you
