### ISSUE TITLE
[exoplayer-ui] Allow PlayerView customization without providing separate layouts

### ISSUE THREAD

**Issue by denis-bezrukov** [google/ExoPlayer#9769]
Existing open issue
-----------------------
The closest feature request seems to be https://github.com/google/ExoPlayer/issues/5417

### [REQUIRED] Use case description
We want to defer a player control logic to exoplayer-ui, but currently we met multiple issues: 
1. It complicates work with ViewBinding as mentioned in #5417 
2. We need to maintain multiple layouts (fragment, player, controls, overlay that needs to be inflated separately into playerView.overlayFrameLayout)
3. It's hard to get an access to custom views in your playback controls (`you need to use playerView.findViewById<ViewGroup>(R.id.exo_controls).getChildAt(0)`) if you have any.

### Proposed solution
Since `PlayerView` is a `ViewGroup`, we can use its children to describe overlays/controls/other components, so on a high level a fragment layout will look:

<details>
<summary>layout example</summary>

```
<com.google.android.exoplayer2.ui.PlayerView
    android:id="@+id/player_view"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    app:show_buffering="when_playing"
    app:surface_type="texture_view"
    app:use_controller="true">

    <ProgressBar android:id="@id/exo_buffering"
        android:layout_width="200dp"
        android:layout_height="200dp"
        android:indeterminate="true"
        android:layout_gravity="center"/>

    <FrameLayout
        android:id="@+id/your_custom_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"/>

    <FrameLayout
        android:id="@+id/your_another_custom_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"/>

    <PlayerControlView
        android:id="@id/exo_controller"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <!-- exo_rew -->
        <!-- exo_ffwd -->
        <!-- exo_progress -->

    </FrameLayout>

</com.google.android.exoplayer2.ui.PlayerView>
```
</details>

It's already possible to add any views via xml, but exoplayer won't pick them because the initialization happen in a `PlayerView` constructor. 
So on the implementation level the idea is to handle initialization in `onFinishInflate()` once all the children are added to a `PlayerView`. 

#### Open questions
1. How to handle the case if a component will be specified twice (e.g. exo_buffering is specified in player_layout directly plus as a `PlayerView` child in fragment layout)

### Alternatives considered
1. Maintain multiple layouts and *Binding objects with the current implementation
2. provide PlayerView.setControlsView(controlsView). In this case both PlayerView and Controls can be declared in fragment XML, and then connected programmatically. Obvious cons is it is not flexible, so it will need PlayerView.setShutterView/PlayerView.setBufferingView etc. 

If proposal looks reasonable and you will accept a PR I can try to implement this.

**Comment by ojw28** [comment]
At the point where you need significant customization, you're really best off just implementing your own UI components (optionally, you can fork the ones that ExoPlayer provides as a starting point). This is suggested [here](https://exoplayer.dev/ui-components.html#further-customization), and is what the vast majority of major streaming apps that use ExoPlayer do.

It's simply not possible for our out-of-the-box UI components to do a good job of supporting all of the specific customizations that individual applications want.
