### ISSUE TITLE
how does getCurrentPosition() calculated ?

### ISSUE THREAD

**Issue by eshkoliGilad** [google/ExoPlayer#977]
I need to get the exact position when pausing, but ExoPlayer seems to return every time a slightly different value at that scope of time (2.456 sec is the current position when frame is starting at 2.333 sec, for example).

Does ExoPlayer takes into account FPS when calculating this value ?

It seems that when I paused I don't necessarily get the exact frame I need (When using 15 FPS - most of the times it's OK but sometimes I'm a frame behind or 1-2 frames ahead).

Is there anyway to get ExoPlayer to take account of the FPS the video is having to calculate current position ?

Thanks in advance.

**Comment by ojw28** [comment]
You're defining the exact position as the timestamp of the video frame being displayed, but in general that's not the case or what someone using the player would want. As an example, consider a case where there's video at a very low frame-rate (e.g. just a single frame at the start of the media) and also an audio track. It's unlikely that a user of the player would want the position to never update in that case.

If you need the exact frame position, you'll have to extend `MediaCodecVideoTrackRenderer` and override something like `processOutputBuffer`, like:

```
  @Override
  protected boolean processOutputBuffer(long positionUs, long elapsedRealtimeUs,
      ExoMediaCodec codec, ByteBuffer buffer, MediaCodec.BufferInfo bufferInfo, int bufferIndex,
      boolean shouldSkip) {
    boolean processed = super.processOutputBuffer(positionUs, elapsedRealtimeUs, codec, buffer,
        bufferInfo, bufferIndex, shouldSkip);
    if (!shouldSkip && processed) {
      lastOutputBufferTimestamp = bufferInfo.presentationTimeUs;
    }
    return processed;
  }
```

Where `lastOutputBufferTimestamp` is the timestamp of the frame currently being displayed.

**Comment by eshkoliGilad** [comment]
Thank you for the quick response.

I tried it now, and it looks much better, but still sometimes the current visible frame after setPlayWhenReady(false) is one ahead than the time I receive in lastOutputBufferTimestamp.
I print the time on the video frames when rendering and print the time returned by lastOutputBufferTimestamp and I see no match at some cases.

Any idea why ?

**Comment by ojw28** [comment]
Are you sure `lastOutputBufferTimestamp` isn't updated after you query it? I'm not sure what you mean when you say they're not matching. It's unclear exactly what you're printing, but if I understood correctly then both values should originate from `bufferInfo.presentationTimeUs`.

**Comment by eshkoliGilad** [comment]
Again, thanks for the quick response.

What I meant to say is that I stream a video already have the current time-stamp watermarked inside in every single frame with the current time-stamp of that frame. Now I need that precise time-stamp from ExoPlayer in order to show some overlay on top of video with content related to this particular frame .

When I pause the video (in onStateChangd callback), I check for lastOutputBufferTimestamp and put its value in a TextView on top of the video.

In this state, I have the watermarked timestamp and the value in the TextView from lastOutputBufferTimestamp visible and comparable. 80% of the time it shows the same exact value and the overlay I put on top of video matches the frame perfectly, but on 20% of times when I pause I get one frame that is earlier. So now the overlay I put does not match the correct frame.

For example, when frame is really 4.0 sec, when I print lastOutputBufferTimestamp value on pause state I get 3.9333 sec.

Do you know what may be causing this irregularity/delay ?

**Comment by eshkoliGilad** [comment]
@ojw28 

Sorry for the misunderstanding, I had a problem which was fixed now and it's working fine as it should. Thank you very much, this issue should be closed now.

**Comment by TonyTangAndroid** [comment]
@eshkoliGilad I have came into a similar question as you raise here. ExoPlayer.getCurrentPosition() would not return the same value after it has been paused. The Current Position matters for my application because I use it to decide whether it should resume the playback or seek to the new position before continuing the playback. Could you please share how did you fix it? Should I add a range of difference like 50 ms?  This is a hacker way. I would prefer not to do it in this way.
