### ISSUE TITLE
Not found Attribute PlayerView 

### ISSUE THREAD

**Issue by behroozAlborzi** [google/ExoPlayer#9770]
two Attribute xml Not found : 
````
 <com.google.android.exoplayer2.ui.PlayerView
        android:id="@+id/player_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:fastforward_increment="5000"
        app:rewind_increment="5000" />

````

- app:fastforward_increment="5000"
- app:rewind_increment="5000"  

Don't set xml why ?

**Comment by icbaker** [comment]
From the [2.15.0 release notes](https://github.com/google/ExoPlayer/blob/release-v2/RELEASENOTES.md#2150-2021-08-10):
> Remove `rewind_increment` and `fastforward_increment` attributes from `PlayerControlView` and `StyledPlayerControlView`. These increments can be customized by configuring the `Player` (see `setSeekBackIncrementMs` and `setSeekForwardIncrementMs` in `SimpleExoPlayer.Builder`), or by using a `ForwardingPlayer` that overrides `getSeekBackIncrement`, `seekBack`, `getSeekForwardIncrement` and `seekForward`. The rewind and fast forward buttons can be disabled by using a `ForwardingPlayer` that removes `COMMAND_SEEK_BACK` and `COMMAND_SEEK_FORWARD` from the available commands.
