### ISSUE TITLE
DISCONTINUITY_REASON_PERIOD_TRANSITION not triggering when i am playing DASH videos

### ISSUE THREAD

**Issue by wahdatjan** [google/ExoPlayer#9771]
I am using exoplayer 2.12 where i am using DRM for dash videos , I use onPositionDiscontinuity event listener for automatic transition and clickable transition to next or previous  every thing works fine but for dash DRM protected videos `onpositiondiscontuinity's Player.DISCONTINUITY_REASON_PERIOD_TRANSITION` does not getting triggered for DASH drm protected videos but works for others. while as other reasons are getting triggered fine .

**Comment by icbaker** [comment]
Are you able to reproduce the issue in the latest [ExoPlayer demo app](https://exoplayer.dev/demo-application.html) (2.16.1)?

If so, please provide media we can use to reproduce the issue. Please either upload it here or send to dev.exoplayer@gmail.com using a subject in the format `Issue #1234` (where `#1234` should be replaced with this issue number.) Please also update this issue to indicate you’ve done this.

**Comment by wahdatjan** [comment]
@icbaker i have not tried it in the latest version, i will do that but how can we fix it in the 2.12
