### ISSUE TITLE
Can‘t play channel  with  CronetDataSource when port is 80 

### ISSUE THREAD

**Issue by DorisGM** [google/ExoPlayer#9774]
When  play url is http://xxxxx:80//xxxxx   , CronetUrlRequest throw Error_unsaft_port.  I guess because of CronetUrlRequst base on chrome http . Chrome http think 80 is unsaft port.  But  I want to know. Is there have some way to ingore this restrictions?  I want to use CronetDataSource as well as can play channel which url contain 80 port. What can i do ?
![exoplayer80](https://user-images.githubusercontent.com/22267767/145499067-364a280c-dbed-4028-869b-82b24584e7de.png)

Enviorment:

ExoPlayer version number : 2.16.1
Android version: 9.0
Android device Amlogic S905X

**Comment by icbaker** [comment]
I don't think port 80 is considered unsafe by cronet by default. There's a full list of 'unsafe' ports here and I don't see 80 listed:
https://chromium.googlesource.com/chromium/src.git/+/refs/heads/main/net/base/port_util.cc

It would seem strange for an HTTP library to block connections to port 80, given it's the standard HTTP port: https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers

That said, questions about customising cronet aren't really in scope for this issue tracker - it's a library that we provide easy integration with, but we can't offer detailed support on its internal workings. You may want to file your feedback on the [Chromium issue tracker](https://bugs.chromium.org/p/chromium/issues/list) (linked from the [Android docs about cronet](https://developer.android.com/guide/topics/connectivity/cronet)).
