### ISSUE TITLE
tolerance for rtsp track timing

### ISSUE THREAD

**Issue by ghotik** [google/ExoPlayer#9775]
### [REQUIRED] Use case description
In my app, when developing disconnected from the cameras vpn, I find it handy to steal some frames from public rtsp streams, and this one is my favourite one:

rtsp://31.0.225.93/cam/realmonitor?channel=3&subtype=00&authbasic=YWRtaW46MTIzOTg3

but EXOPlayer doesn't show frames from this public camera because of the following error:

Server did not provide timing for track ...  

### Proposed solution
I understand that the protocol from that camera may be not fully compliant to rtsp standards, but I found that commenting lines 516-519 in RtspMediaPeriod.java make the camera perfectly visible.

### Alternatives considered
Add an EXOPlayer settings option to make the control optional

**Comment by claincly** [comment]
We have received a few similar issues now. Will include an option to ignore the timing info.

**Comment by ghotik** [comment]
Thanks a lot!

**Comment by NicolasGodfather** [comment]
The same. I am waiting this update too. How soon you plan to fix it in new release?
