### ISSUE TITLE
Stuttering and abnormally fast playing radio streams

### ISSUE THREAD

**Issue by traxformania** [google/ExoPlayer#9778]
Sometimes i hear very bad audio quality(sometimes it fixes byself after some seconds), sometimes it plays abnormally fast radio streams.

Sample radio stream :   https://23603.live.streamtheworld.com/SC010_SO1AAC.aac

When I play this stream with VLC, I didn't encounter these problems a single time.

I'm using default settings.

What can I try?

**Comment by christosts** [comment]
I quickly tested the radio stream and did not notice any issue on a Pixel 4 with ExoPlayer 2.16. 

To assist you we need more information such as the ExoPlayer version you're using and details about the device (including the Android version) you're experiencing problems with, and a bugreport grabbed just after the problem occurs. For more information you can refer to the issue template [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md).

If you're unable to share [bug reports](https://developer.android.com/studio/debug/bug-report) or
test content publicly, please send them to dev.exoplayer@gmail.com with subject "Issue #9778".
