### ISSUE TITLE
onTracksInfoChanged called multiple times 

### ISSUE THREAD

**Issue by FTW-Khushal** [google/ExoPlayer#9779]
What I want:
-----------------------

- I want to listen for track changed so I make other methods in class aware which track is currently playing and prepare thing for the same
-  To do above function I found this listener #Player.onTracksInfoChanged which called when track is changed

What I did:
------------------------
- i implemented #Player.onTracksInfoChanged and use #player.seekToNext(); on next button click of my exoplayer but #Player.onTracksInfoChanged is calling two times instead of one 
- So i thought to  #player.seekToNext(); is not the best way to change track so i used 
  - player.seekToDefaultPosition(player.getNextMediaItemIndex());
  - player.seekToNextMediaItem();
  But all above three method result in calling #Player.onTracksInfoChanged two times

What is the Question/Problem:
--------------------------
- Is there other way to listener for track changed ? <b>OR</b> I need to use different way to changed track and then #Player.onTracksInfoChanged  will work correctly ? 

Thank you for reading through and sorry for my terrible English

**Comment by christosts** [comment]
Please refer to the documentation page [Detecting when playback transitions to another media item](https://exoplayer.dev/playlists.html#detecting-when-playback-transitions-to-another-media-item). It sounds like `Listener.onMediaItemTransition()` is the callback you need.

Thanks
