### ISSUE TITLE
Enabling vnd.dvb.ait

### ISSUE THREAD

**Issue by emveepee** [google/ExoPlayer#9780]
How can I enable vnd.dvb.ait from an mpeg-ts.  I am able to enable dvbsubs and closed captioning  but the teletext sub's don't show

```
D/EventLogger:   MetadataRenderer [
D/EventLogger:     Group:0, adaptive_supported=N/A [
D/EventLogger:       [X] Track:0, id=null, mimeType=application/vnd.dvb.ait, supported=YES
D/EventLogger:     ]
D/EventLogger:   ]
```

For the other type I simply had to enable text so I simply added metadata.  Perhaps more is required?  I didn't change PlayerView

```
                                 builder.setRendererDisabled(C.TRACK_TYPE_TEXT, false);
                                 builder.setRendererDisabled(C.TRACK_TYPE_METADATA, false);
                                 builder.setPreferredTextLanguage("en");
```

**Comment by emveepee** [comment]
A user provided this sample file https://drive.protonmail.com/urls/1CBRBEGEXR#lSYOoGtzu2TL  I am not sure how long it will be active.

**Comment by icbaker** [comment]
I think you might be asking about two separate things?

> How can I enable vnd.dvb.ait from an mpeg-ts.

ExoPlayer has minimal support for Application Information Table (AIT) data (added in https://github.com/google/ExoPlayer/pull/6922) and it exposes this information as a metadata (not text) track, as you've shown in the logcat snippet. The AIT is defined in section 5.3.4 of [TS 102 809](https://www.etsi.org/deliver/etsi_ts/102800_102899/102809/01.01.01_60/ts_102809v010101p.pdf). You can receive this metadata track by listening to [`Player.Listener#onMetadata`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/Player.Listener.html#onMetadata(com.google.android.exoplayer2.metadata.Metadata)): https://exoplayer.dev/retrieving-metadata.html#during-playback

> the teletext sub's don't show

ExoPlayer does not support teletext subtitles. Support is tracked by https://github.com/google/ExoPlayer/issues/5491.

**Comment by emveepee** [comment]
Thanks yes there are two questions and you answered them both, I incorrectly assumption ExoPlayer supported teletext and it was in the AIT metadata.  I forgot only enabled the metadata listener in audio.
