### ISSUE TITLE
Execution failed for task ':extension-ffmpeg:configureCMakeRelWithDebInfo'.

### ISSUE THREAD

**Issue by JiannaiJ** [google/ExoPlayer#9783]
when i assembleRelease extension-ffmpeg

extensions/ffmpeg/src/main/jni/ffmpeg/android-libs/ -->>
armeabi-v7a/libavcodec.a
armeabi-v7a/libavutil.a
armeabi-v7a/libswresample.a

Execution failed for task ':extension-ffmpeg:configureCMakeRelWithDebInfo'.
> java.lang.NullPointerException (no error message)

**Comment by SteveKin3** [comment]
> when i assembleRelease extension-ffmpeg
> 
> extensions/ffmpeg/src/main/jni/ffmpeg/android-libs/ -->> armeabi-v7a/libavcodec.a armeabi-v7a/libavutil.a armeabi-v7a/libswresample.a
> 
> Execution failed for task ':extension-ffmpeg:configureCMakeRelWithDebInfo'.
> 
> > java.lang.NullPointerException (no error message)

**Comment by Gnzlt** [comment]
I'm having the same issue, any update on this?
