### ISSUE TITLE
Huge increase in number of dropped frames after upgrading from v2.11.8 to v2.16.1

### ISSUE THREAD

**Issue by MBakhshi96** [google/ExoPlayer#9788]
After upgrading from exoplayer v2.11.8 to the latest version, I am experiencing a huge increase in dropped frames on my device. To better understand the problem, I tried to test with versions in between, but it didn't help. Actually, v2.12.3 was the highest version that frame drops were negligible, and the problem persisted in later versions. It seems that there has been some changes that have changed video decoding from hardware codecs to software.

The problem exists on most of media items. As an example when playing [this url](http://cdn.theoplayer.com/video/elephants-dream/playlist.m3u8), more than half of the frames are reported to be dropped.

- ExoPlayer version number: higher than v2.12.3 
- Android version: 9

Useful parts of logcat when playing the content (exoplayer version was v2.15.1 for this run):
```
I/ExoPlayerImpl: Init c325edf [ExoPlayerLib/2.15.1] [petrel-p1, MBOX, Allwinner, 28]
I/cr_CronetLibraryLoader: Cronet version: 95.0.4638.50, arch: armv8l
D/CronetUtil: CronetEngine built using App-Packaged-Cronet-Provider
...
W/VideoCapabilities: Unrecognized profile 4 for video/hevc
W/VideoCapabilities: Unrecognized profile/level 1/32 for video/mp4v-es
    Unrecognized profile/level 32768/2 for video/mp4v-es
I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
D/MediaCodecInfo: NoSupport [codec.profileLevel, avc1.640029, video/avc] [OMX.allwinner.video.decoder.avc, video/avc] [petrel-p1, MBOX, Allwinner, 28]
...
I/MediaCodec: [OMX.google.h264.decoder] setting surface generation to 13085697
D/EventLogger: videoDecoderInitialized [eventTime=2.28, mediaPos=0.00, window=0, period=0, OMX.google.h264.decoder]
D/EventLogger: videoInputFormat [eventTime=2.29, mediaPos=0.00, window=0, period=0, id=1, mimeType=video/avc, codecs=avc1.640029, res=1280x640, language=und]
D/EventLogger: downstreamFormat [eventTime=2.30, mediaPos=0.00, window=0, period=0, id=2, mimeType=audio/mp4a-latm, codecs=mp4a.40.2, channels=2, sample_rate=48000, language=und]
D/EventLogger: audioDecoderInitialized [eventTime=2.32, mediaPos=0.00, window=0, period=0, OMX.google.aac.decoder]
D/EventLogger: audioInputFormat [eventTime=2.33, mediaPos=0.00, window=0, period=0, id=2, mimeType=audio/mp4a-latm, codecs=mp4a.40.2, channels=2, sample_rate=48000, language=und]
...
D/EventLogger: isPlaying [eventTime=2.83, mediaPos=0.05, window=0, period=0, true]
D/EventLogger: droppedFrames [eventTime=5.49, mediaPos=2.72, window=0, period=0, 50]
D/EventLogger: droppedFrames [eventTime=6.43, mediaPos=3.65, window=0, period=0, 50]
D/EventLogger: loading [eventTime=7.85, mediaPos=5.07, window=0, period=0, false]
D/EventLogger: droppedFrames [eventTime=8.20, mediaPos=5.42, window=0, period=0, 50]
D/EventLogger: droppedFrames [eventTime=8.55, mediaPos=5.77, window=0, period=0, 71]
D/EventLogger: droppedFrames [eventTime=10.05, mediaPos=7.27, window=0, period=0, 50]
D/EventLogger: droppedFrames [eventTime=11.22, mediaPos=8.38, window=0, period=0, 40]
I/MediaCodec: [OMX.google.h264.decoder] setting surface generation to 13085698
I/ExoPlayerImpl: Release c325edf [ExoPlayerLib/2.15.1] [petrel-p1, MBOX, Allwinner, 28] [goog.exo.core, goog.exo.cronet]
D/EventLogger: videoDecoderReleased [eventTime=12.47, mediaPos=8.39, window=0, period=0, OMX.google.h264.decoder]
D/EventLogger: audioDecoderReleased [eventTime=12.48, mediaPos=8.39, window=0, period=0, OMX.google.aac.decoder]
```

**Comment by MBakhshi96** [comment]
I have edited the comment with some more lines from the logcat.

**Comment by christosts** [comment]
I assume that your tests are with the ExoPlayer demo app. Please correct me if that'n not true.

According to the log, the device's decoder (`OMX.allwinner.video.decoder.avc` - which I assume is a hardware one) cannot decode the stream and the player uses the software decoder `OMX.google.h264.decoder`. It wouldn't be surprising if the frames are dropped because the software decoder is used, althoough the codec selection logic has not changed between 2.12.3 and 2.13.1. However, let's verify what happens.

Can you please play the same stream with the two ExoPlayer versions in question 2.11.8 (or 2.12.3) and 2.16.1 on the specific device and grab a [bugreport](https://developer.android.com/studio/debug/bug-report) right after playback? Reboot the device between playbacks so that each bugreport contains fresh logs.

If you're unable to share [bug reports](https://developer.android.com/studio/debug/bug-report) please send them to dev.exoplayer@gmail.com using the subject "Issue #9788" and update this issue to indicate you've done this.

The point of the test is to verify what decoder was picked in each ExoPlayer version. It's preferable to grab bugreports than just copying the logcat output.

**Comment by MBakhshi96** [comment]
No, I'm not using the demo app. I can test the url with the demo app, if it's necessary, but I think the problem will persist.

I can confirm that the problem is a caused by not using the hardware decoder (`OMX.allwinner.video.decoder.avc`) in newer versions. I suspect that it might be a consequence of a change in decoder selection. Here you can find the same part of logcat using v2.12.3 (which is similar to v2.11.8):
```
I/MediaCodec: [OMX.allwinner.video.decoder.avc] setting surface generation to 22511617
...
D/EventLogger: videoDecoderInitialized [eventTime=2.54, mediaPos=0.00, window=0, period=0, OMX.allwinner.video.decoder.avc]
...
I/ExoPlayerImpl: Release eace93 [ExoPlayerLib/2.12.3] [petrel-p1, MBOX, Allwinner, 28] [goog.exo.core, goog.exo.cronet]
D/EventLogger: videoDisabled [eventTime=10.05, mediaPos=6.26, window=0, period=0]
D/EventLogger: audioDisabled [eventTime=10.05, mediaPos=6.26, window=0, period=0]
```
comparing to logcat from the next version, v2.13.0 (which is similar to v2.16.1):
```
D/MediaCodecInfo: NoSupport [codec.profileLevel, avc1.640029, video/avc] [OMX.allwinner.video.decoder.avc, video/avc] [petrel-p1, MBOX, Allwinner, 28]
D/MediaCodecInfo: NoSupport [codec.profileLevel, avc1.640029, video/avc] [OMX.allwinner.video.decoder.avc, video/avc] [petrel-p1, MBOX, Allwinner, 28]
...
I/MediaCodec: [OMX.google.h264.decoder] setting surface generation to 23183361
...
D/EventLogger: videoDecoderInitialized [eventTime=2.71, mediaPos=0.00, window=0, period=0, OMX.google.h264.decoder]
...
D/EventLogger: droppedFrames [eventTime=6.01, mediaPos=2.81, window=0, period=0, 50]
D/EventLogger: droppedFrames [eventTime=6.13, mediaPos=2.93, window=0, period=0, 51]
D/EventLogger: droppedFrames [eventTime=8.18, mediaPos=4.93, window=0, period=0, 42]
...
I/ExoPlayerImpl: Release eace93 [ExoPlayerLib/2.13.0] [petrel-p1, MBOX, Allwinner, 28] [goog.exo.core, goog.exo.cronet]
D/EventLogger: videoDisabled [eventTime=9.04, mediaPos=4.95, window=0, period=0]
D/EventLogger: audioDisabled [eventTime=9.04, mediaPos=4.95, window=0, period=0]
D/EventLogger: videoDecoderReleased [eventTime=9.05, mediaPos=4.95, window=0, period=0, OMX.google.h264.decoder]
D/EventLogger: audioDecoderReleased [eventTime=9.05, mediaPos=4.95, window=0, period=0, OMX.google.aac.decoder]
```


For sharing bug reports, I need to get a permission, so if the provided information is not sufficient, please let me know.

**Comment by christosts** [comment]
First, here's a workaround to make ExoPlayer pick the hardware decoder: pass a custom `MediaCodecSelector` to the player

```java
RenderersFactory renderersFactory =
    new DefaultRenderersFactory(context)
        ....
        .setMediaCodecSelector(
            (mimeType, requiresSecureDecoder, requiresTunnelingDecoder) -> {
              List<MediaCodecInfo> codecs = MediaCodecSelector.DEFAULT.getDecoderInfos(
                  mimeType,
                  requiresSecureDecoder,
                  requiresTunnelingDecoder);
              if (codecs.isEmpty()) {
                return Collections.emptyList();
              }
              // Only consider the first decoder, or iterate the list and select the decoder
              // that is hardwareAccelerated.
              return Collections.singletonList(codecs.get(0));
            }
        );

player =
    new ExoPlayer.Builder(context)
        ...
        .setRenderersFactory(renderersFactory)
        .build();
```

Let us know if that fixed codec selection on your device.

Second, we have already submitted an improvement to prefer the hardware-accelerated codec. The code is in the dev-v2 branch and will be part of the next release. I'd appreciate if you could checkout the code from dev-v2, try the ExoPlayer demo app on your device using your test stream without any other customizations ~and confirm if the player picked the hardware decoder~. If you do so, please copy and attach the demo logcat output, we're especially interested on the logs that print track support per decoder, e.g.

```
D/EventLogger: tracks [eventTime=0.57, mediaPos=0.00, window=0, period=0
      MediaCodecVideoRenderer [
        Group:1, adaptive_supported=YES [
          [X] Track:0, id=1, mimeType=video/avc, bitrate=769255, codecs=avc1.42c01e, res=320x142, fps=24.0, supported=YES, accelerated=YES
          [X] Track:1, id=2, mimeType=video/avc, bitrate=1774254, codecs=avc1.4d401f, res=854x380, fps=24.0, supported=YES, accelerated=YES
          [X] Track:2, id=3, mimeType=video/avc, bitrate=7203938, codecs=avc1.4d4028, res=1280x570, fps=24.0, supported=YES, accelerated=YES
        ]
      ]
``` 

Thank you

[update] the feature is not fully submitted to the dev-v2 branch; the logcat output will inform for codec support, but codec selection is still in review

**Comment by MBakhshi96** [comment]
Seems that your provided solution by using a custom `MediaCodecSelector` has fixed the problem. The hardware codec was present in the list of the available codecs but the sorting logic used inside `MediaCodecVideoRenderer` seems to have prioritized the software codec.

**Comment by christosts** [comment]
I'll close this issue for now. 

I'd appreciate if you have the time to revisit this when 2.17 is released. The player should pick the hardware decoder without any customization needed. If you test this, there's no need to re-open the issue, a simple comment would work.

Thanks!
