### ISSUE TITLE
Expose ID3 metadata for mp3 + mp4

### ISSUE THREAD

**Issue by Sicness** [google/ExoPlayer#979]
Is it possible to get metadata (like artist, song name and etc) from HTTP mp3 stream (radio) via some of ExoPlayer classes? Does the player has such functionality? If no, do you have recommendation how to get the metadata?

**Comment by ojw28** [comment]
We could probably support this relatively easily, given we already have ID3 parsing for MPEG-TS.

**Comment by ojw28** [comment]
@cbfiddle - For mp4 do you think it's fine to propagate the metadata in the audio track only? I've made this change on `dev-v2-id3`, but wonder whether you can think of any edge cases? We could add it to the video track for the specific case where no audio track is present to handle that edge case, but in practice it seems unlikely we'd encounter this case.

**Comment by cbfiddle** [comment]
I have no opinion. My use case is audio only.

**Comment by ojw28** [comment]
ID3 support for MP3 and MP4 has been merged in https://github.com/google/ExoPlayer/pull/2008.

**Comment by cbfiddle** [comment]
One of my goals for ID3 support was to implement replay gain (level matching between tracks). However, I have not found a way to introduce gain (the volume parameter only supports level reduction). Is there a way to do this?

Thanks.

  Alan

**Comment by ojw28** [comment]
I don't think it would be possible to implement this properly by receiving the ID3 data and then setting something back on the player. You'd really need this to happen synchronously within the player itself. If there are standard tags for this then please file a new issue to track implementing this, together with details about the standard tags and sample media we can test with.
