### ISSUE TITLE
onIsPlayingChanged not called when casting  

### ISSUE THREAD

**Issue by mikescamell** [google/ExoPlayer#9792]
Hi I'm trying to implement the cast extension in our app but I'm having some issues with callbacks.

When casting using the ExoPlayer cast extension, pausing and playing the `onIsPlayingChanged()` callback does not called. 

To reproduce 

- Add this block of code to the `PlayerManager`
```
    @Override
    public void onIsPlayingChanged(boolean isPlaying) {
        if (isPlaying) {
            Log.d("isPlaying","Is playing");
        } else {
            Log.d("isPlaying","Is not playing");
        }
    }
```
- Load the demo and play some content
- Cast
- Play/Pause content repeatedly

Expected: The `onIsPlayingChanged()` callback i called with the correct playing state
Actual: The `onIsPlayingChanged()` is never called

I have noticed `onPlayWhenReadyChanged()` does get called but we already use `onIsPlayingChanged()`

- ExoPlayer version number: 2.16.1

**Comment by marcbaechinger** [comment]
I can confirm this behaviour. We will provide a fix for this. Thanks for reporting!
