### ISSUE TITLE
Provide custom data in MediaQueueItem to be used by the Cast API

### ISSUE THREAD

**Issue by schnaps1981** [google/ExoPlayer#9798]
some time i used Exoplayer v2.14

This version had method addItems(MediaQueueItem... items) in CastPlayer class
And I was able to add custom data for items (for example boolean) like this

`mediaQueueItem.media.customData?.put(KEY, true)`

my cast receiver get this boolean and show some icon if value is true

but in one of last version of Exoplayer method **addItems** was removed and now i can't send custom data in receiver.

please tell me, how i can do it?

sorry for my english

**Comment by marcbaechinger** [comment]
When you create an instance of the `CastPlayer` you can pass a custom [`MediaItemConverter`](https://github.com/google/ExoPlayer/blob/7fe9ecc1c592b758e76f6b458e0dc43cce282e5f/extensions/cast/src/main/java/com/google/android/exoplayer2/ext/cast/MediaItemConverter.java) to the [constructor](https://github.com/google/ExoPlayer/blob/7fe9ecc1c592b758e76f6b458e0dc43cce282e5f/extensions/cast/src/main/java/com/google/android/exoplayer2/ext/cast/CastPlayer.java#L183) of `CastPlayer`. This gets called when you use the `setMediaItem/setMediaItems` methods on `CastPlayer` to convert from `Mediaitem` to `MediaQueueItem` that is sent to the Cast API.

So you can create your custom implementation of `MediaItemConverter` that is creating the `MediaQueueItem` by adding the custom property. Then constructor-inject the converter to the `CastPlayer`.

**Comment by schnaps1981** [comment]
thank you so much! 
i'll try it

**Comment by schnaps1981** [comment]
thank you so much! it's works
