### ISSUE TITLE
Memory leak in r2.16.1

### ISSUE THREAD

**Issue by unDEFER** [google/ExoPlayer#9799]
Hello!
I have detected memory leak in exoplayer 2.16.1 with speed ~50 Mb per minute in the next point:
![Allocation_Call_Stack](https://user-images.githubusercontent.com/6921745/146769925-53609493-966a-42eb-8574-7835ed7b7a0a.png)
Which info must be provided more to be fixed?

**Comment by marcbaechinger** [comment]
Please describe the memory leak that you have detected in more detail. The screenshot you provide shows that there is memory allocated when reading for extracting media data for HLS. This is something that happens very often when playing media as it is part of the process. There is no indication that this is a memory leak from the information provided.

How did you find the leak? If you have a stack trace with an out of memory this would be helpful to see at what point the OOM is thrown.

Please provide us with more information about the memory leak you detected. It would be helpful to have reproduction steps so we can reproduce this. If this includes playing a certain media file, please provide the URI to that file and tell us in what moment of playback you have observed the problem. A more detailed description of the problem you actually see (for instance a stack trace) would be informative as well.

**Comment by unDEFER** [comment]
OK, I agree that from the screenshot is not clear that it is memory leak. Here more full:
![Memory_Leak](https://user-images.githubusercontent.com/6921745/146889904-45b1cbc3-9105-429c-8308-2a988610a083.png)
From this you can see how many GC times worked, but this memory still not deallocated.
I found this leak on device with small amount of RAM, I have out of memory stack, but out of memory exception may happen not in the point of real memory leak, isn't it? So I'm providing info from profiler. Of course we can hope that this memory will deallocated in the future, but I tried to wait while it eats and 200 and 300 Mb, I can try wait while it eats all VM memory, but real device have less free memory and there it crashes really fast.
I will try to provide minimal application to reproduce tomorrow.

**Comment by ojw28** [comment]
There's an issue with the emulator that can cause this behavior (see https://github.com/google/ExoPlayer/issues/8801), which might be what you're seeing above since it looks like you were using an emulator when profiling. Please try profiling on a physical device instead, and you will likely not see this leak behavior.
