### ISSUE TITLE
Is it possible to use TextureView rather than SurfaceView?

### ISSUE THREAD

**Issue by nschwermann** [google/ExoPlayer#98]
TextureView seems to be the better choice if the device supports it but it appears that it isn't supported by Exoplayer. Is this the case? Could we get support for SurfaceTexture?

**Comment by LittleKey** [comment]
thx a lot!

**Comment by shelarsuhas** [comment]
I'm new to implementing videos. Can any one explain me how to pass the surface to ExoPlayer ?
Thanks!

**Comment by andrewlewis** [comment]
When using TextureView you pass the Surface in the same way as for SurfaceView (see the [demo app code](https://github.com/google/ExoPlayer/blob/dev/demo/src/main/java/com/google/android/exoplayer/demo/player/DemoPlayer.java#L588)), but you need to [construct the Surface from a SurfaceTexture](http://developer.android.com/reference/android/view/Surface.html#Surface(android.graphics.SurfaceTexture)), which you get in the TextureView's surface texture listener (see [this example code](http://developer.android.com/reference/android/view/TextureView.html)). It is probably also a good idea to release the Surface when the surface texture is destroyed.
