### ISSUE TITLE
I get a MediaDrmStateException on SHARP devices with Android 11.

### ISSUE THREAD

**Issue by KazukiSugiyama107** [google/ExoPlayer#9801]
An error may occur during playback of streaming or download.
The device that occurs is a SHARP terminal, and the OS is Android 11.
System update and security update will be after May 1st.

Do you know the relevance of system update and security update?

We will submit a bug report, so please check it.

- Streaming playback
```
onPlayerError error com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.drm.DrmSession$DrmSessionException: android.media.MediaDrm$MediaDrmStateException: Failed to get key request: General DRM error
ExoPlaybackException.TYPE_SOURCE
android.media.MediaDrm$MediaDrmStateException: Failed to get key request: General DRM error
```

- Download playback
```
reacquisition of license : none
downloadOfflineDrm Exception : com.google.android.exoplayer2.drm.DrmSession$DrmSessionException: android.media.MediaDrm$MediaDrmStateException: Failed to get key request: General DRM error
MediaDrm.MediaDrmStateException : android.media.MediaDrm.error_neg_2000
```

- Android version：Android 11
- Android device：SH-02M、SHV46、SH-RM12、SH-02M

**Comment by icbaker** [comment]
The bug report provided over email does not contain `MediaDrmStateException` anywhere in the logcat. Please reproduce the issue immediately before capturing the bug report (ideally in the [ExoPlayer demo app](https://exoplayer.dev/demo-application.html), or [with an `EventLogger` attached](https://exoplayer.dev/debug-logging.html), as it will include more detailed logging that may help to diagnose the issue).

**Comment by KazukiSugiyama107** [comment]
We will ask the user to provide the bug report again, so we will send it to the email address as soon as it is provided.
I will comment here as soon as it is sent to the e-mail address, so thank you.

**Comment by ojw28** [comment]
Thanks. Marking as "needs more info" pending that.
