### ISSUE TITLE
StyledPlayerView - Automatically Playback speed resets on onResume

### ISSUE THREAD

**Issue by ponthamaya** [google/ExoPlayer#9810]
Exoplayer : v2.16.1 (Demo project)
Device : OnePlus 6T

Reproduce:

When we resume back to the player the old playback speed resets back to normal.

**Comment by marcbaechinger** [comment]
The value in the `StyledPlayerControlView` corresponds to the speed of the player.

The `StyledPlayerControlView` displays [the speed of the player or the closest matching value in the list of available speeds](https://github.com/google/ExoPlayer/blob/7fe9ecc1c592b758e76f6b458e0dc43cce282e5f/library/ui/src/main/java/com/google/android/exoplayer2/ui/StyledPlayerControlView.java#L1888). In this regard, the `StyledPlayerControlView` is just a view presenting the speed value of the player which is the model. 

I assume with `onResume` you mean the life-cycle callback of the `Activity`. If this is the case, you need to recreate the player and put it into the same state on `onStart/onResume` as the player was when `onPause/onStop` was called. 

You can do this in the same way as for instance the demo app is doing it for the start position. When the activity is put into the background by the user, the `PlayerActivity` [stores some values like the current position or window index in member fields](https://github.com/google/ExoPlayer/blob/release-v2/demos/main/src/main/java/com/google/android/exoplayer2/demo/PlayerActivity.java#L383) that are later used to create the player in `initializePlayer`. Then when the activity is resumed, the player is re-created and the stored values are used to put the player into the same state as before. Doing the same for the `speed` of the player can be done in the same way by adding the float value of the speed to the values that are stored. Aside: when using `saveInstanceState` like the `PlayerActivity` is doing, these values could also survive an app restart.
