### ISSUE TITLE
Use appropriate decimal separator in playback speeds

### ISSUE THREAD

**Issue by moneytoo** [google/ExoPlayer#9811]
The [exo_playback_speeds array](https://github.com/google/ExoPlayer/blob/r2.16.1/library/ui/src/main/res/values/arrays.xml#L28-L36) contains values with hardcoded [decimal separator](https://en.wikipedia.org/wiki/Decimal_separator) (`.`). 

When I have my device set to Czech language (and therefore to Czech locale), I would expect to see values like `1,5x` (instead of `1.5x`).

While it's probably clear to users from the context, in Czech locale `1.5x` would meant _1500 times_.

Other apps like YouTube and Files by Google use the localized values.

EDIT: YouTube also uses actual [multiplication sign](https://en.wikipedia.org/wiki/Multiplication_sign) `×` instead of the latin letter `x`.

**Comment by ojw28** [comment]
We should make sure these strings are translated. Thanks for reporting!

**Comment by ojw28** [comment]
We will fix this across a few of commits:

1. Add translatable strings
2. Add translations for the strings
3. Update the UI components to use the translatable strings
