### ISSUE TITLE
How to direct audio without Dolby certified chip?

### ISSUE THREAD

**Issue by JiannaiJ** [google/ExoPlayer#9812]
The chip of the device does not have Dolby certification, so AudioCapabilities.supportsEncoding() does not include Dolby, but HDMI supports direct Dolby to audio amplifier. How can I modify this support?

**Comment by krocard** [comment]
The supported formats are retrieved from the HDMI intent:

https://github.com/google/ExoPlayer/blob/7fe9ecc1c592b758e76f6b458e0dc43cce282e5f/library/core/src/main/java/com/google/android/exoplayer2/audio/AudioCapabilities.java#L102-L105

If the format desired is not present, this means Android has not detected its support by the HDMI remote device. There is nothing ExoPlayer can do.

You can run `adb shell dumpsys media.audio_policy` and check the formats supported by the HDMI output as detected by the Android audio stack.

If the desired format is present, you can try creating an AudioCapabilities using [its constructor](https://github.com/google/ExoPlayer/blob/7fe9ecc1c592b758e76f6b458e0dc43cce282e5f/library/core/src/main/java/com/google/android/exoplayer2/audio/AudioCapabilities.java#L134) directly, adding whatever format you want to try playback. Playback will  fail with an unsupported format error from the AudioTrack if the HDMI really doesn't support the format.
