### ISSUE TITLE
Get ad information from DASH manifest where ad is SSAI.

### ISSUE THREAD

**Issue by wishygupta** [google/ExoPlayer#9818]
From my dash manifest I need to get some advt information which is part of event stream objects.
The ads are being inserted on server side via SSAI.
I am using the function `onTimelineChanged` but it gets called multiple times. And I am unable to get when the ad is being started or completed.
Is there any other method or callback for SSAI ads on DASH?

**Comment by marcbaechinger** [comment]
There is a list of `EventStream` objects in the `Period` of the `DashManifest`. You can access the manifest as soon as you receive a timeline update for a reason of `TIMELINE_CHANGE_REASON_SOURCE_UPDATE`. If the dash stream is the only media item that is in the playlist, the code below show how you can access the manifest with `player.getCurrentManifest()` and the `EventStream` information that is in the manifest.

```
    @Override
    public void onTimelineChanged(Timeline timeline, @Player.TimelineChangeReason int reason) {
      if (reason == Player.TIMELINE_CHANGE_REASON_SOURCE_UPDATE) {
        // assuming the stream in question is the only media item in the playlist
        DashManifest manifest = (DashManifest) player.getCurrentManifest();
        for (int i = 0; i < manifest.getPeriodCount(); i++) {
          for (int j = 0; j < manifest.getPeriod(i).eventStreams.size(); j++) {
            // Here we go.
          }
        }
      }
    }
```

I'm not sure whether you also need information of timed metadata that may be delivered as in-band metadata. In such a case you should be able to listen to the arrival of timed metadata by using the `onMetadata` callback of the `Player.Listener`. 

```
    @Override
    public void onMetadata(Metadata metadata) {
        // timed metadata arrived...
    }
```

**Comment by wishygupta** [comment]
Thank you for the response. I can get started with this.
