### ISSUE TITLE
drm with textureView not working

### ISSUE THREAD

**Issue by karamgharam** [google/ExoPlayer#9825]
I have sliding view with player View inside it and not work expect put surface type texture View 
but when chose this type the drm content not work .

so drm with texture View  not work and cant load video

ExoPlayer versions 2.15.1
all android devices and versions

**Comment by marcbaechinger** [comment]
`TextureView` does not support DRM content. For protected content you need to use a `SurfaceView`.

https://source.android.com/devices/graphics/arch-tv#surface_or_texture

**Comment by karamgharam** [comment]
> `TextureView` does not support DRM content. For protected content you need to use a `SurfaceView`.
> 
> https://source.android.com/devices/graphics/arch-tv#surface_or_texture

thanks but how can play drm content with sliding view or recycle view because player not work if not TextureView

**Comment by ojw28** [comment]
There is also some ExoPlayer specific guidance on the available surface types here:

https://exoplayer.dev/ui-components.html#choosing-a-surface-type

One way or another you will need to design your app within the constraints and limitations described there and on the page linked above.
