### ISSUE TITLE
Stereoscopic(Left-Right) video to single frame(Left or Right) 

### ISSUE THREAD

**Issue by airtel121** [google/ExoPlayer#9829]
###  Use case description

We are working on building 2d-3d video player, which basically playing stereoscopic(left-right) view in Exoplayer. Now we wanted an ability to switch from left-right(side by side) to single frame view(left or right only) and vise versa in same video content.

### Proposed solution
As seen in exoplayer support, **SimpleExoPlayerView** has ablity to define **surface_type="spherical_gl_surface_view"** but it converts side by side view to single frame in 360 degree mode, which is not required. So wanted same but not in VR or 360 degree mode but normal mode(no rotation but still show video like 2d) with either left view or right view only.

Is there any alternet surface type available for given feature request?

**Comment by ojw28** [comment]
This is not something we support out of the box, so you would need to build your own UI components to do this rather than relying on `PlayerView`/`StyledPlayerView`.
