### ISSUE TITLE
can Exoplayer play live hls stream ?

### ISSUE THREAD

**Issue by lnmcc** [google/ExoPlayer#983]
the address like this :  http://xxx.xxx.xxx:8080/video.m3u8?test=1

Thank you !

**Comment by ojw28** [comment]
Yes.

**Comment by lnmcc** [comment]
Thanks for your reply. But I cannot play this test URL: http://221.181.100.81:8080/56ff9d67c9a3495db38acd1c8fa1e01f/20151124/56ff9d67c9a3495db38acd1c8fa1e01f_20151124_174419.ts?test=1  .  and I can Play it using VLC or HTML.  Can you help me ? Thanks.
