### ISSUE TITLE
Exoplayer supports lowercase hex numbering in segment template but not upper case hex numbering

### ISSUE THREAD

**Issue by TheJohnBowers** [google/ExoPlayer#9832]
Before filing a bug:
-------------------------
I do not see any existing bugs that describ this issue.

When reporting a bug:
-------------------------
Using the exoplayer demo app try to play this back:

      {
        "name": "Dash CBCS uppercase Hex numbering segment template",
        "uri": "https://content-ause2-dt-drm1.downlynk.com/42e9b05315164dd89dda60464acadd6c.mpd?m4fenctype=cbcs&show_dash_subtitles=0",
        "drm_scheme": "widevine",
        "drm_license_url": "https://content-ause2-dt-drm1.downlynk.com/wv",
        "drm_multi_session": true
      },

- ExoPlayer version number
2.16.1
- Android version
9
- Android device
Pixel

In UrlTemplate.Java - ParseTemplate() - only %d or %x format specifiers are allowed in $Number$ in the template.  This media uses %X for capital Hex.  As exoplayer already supports lowercase hex, it makes sense to support uppercase hex.  I should add that both Roku and Shaka player support this already.

**Comment by TheJohnBowers** [comment]
I am trying to push a PR off of dev-v2, but I don't appear to have access.  I have a signed corporate contribution agreement from contributing to a few small changes to shaka, but I suspect I probably would need to be granted rights to push a PR?

**Comment by ojw28** [comment]
Merged https://github.com/google/ExoPlayer/pull/9834. Thanks!
