### ISSUE TITLE
Exo Not play video profile high

### ISSUE THREAD

**Issue by duycong998** [google/ExoPlayer#9837]
I can't not play video in exoplayer 

This is video info : 
![image](https://user-images.githubusercontent.com/54490794/148177101-555fbe44-b785-4b62-bba3-c58860906200.png)

I've looked into maybe the problem lies in profile of video . Because it Profile High 
https://developer.android.com/guide/topics/media/media-formats#video-formats

Here my code :  I added many attributes but it still doesn't work
![image](https://user-images.githubusercontent.com/54490794/148178671-26b99c3a-bc82-49ee-901b-a51c6d37a3f1.png)

But , if i use mediaplayer in android -> video is play
Can you help me? 
Is there any way to solve this problem?
Thanks you

**Comment by ojw28** [comment]
Hi! Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md). If you're unable to share [bug reports](https://developer.android.com/studio/debug/bug-report) or test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #1234" ("#1234" is replaced with your issue number). Please also update this issue to indicate you've done this.

**Comment by duycong998** [comment]
I have provided all the information, what do you want to know more? . 
I just want to play video(h264-high) with exoplayer , but it not working 
And information  video above . Please check help me?

**Comment by ojw28** [comment]
The issue template requests useful information like:

> - URI to test content for reproduction
> - ExoPlayer version number
> - Android version
> - Android device
> 
> If there's something you don't want to post publicly, please submit the issue,
then email the link/bug report to dev.exoplayer@gmail.com using a subject in the
format "Issue #1234", where #1234 is your issue number (we don't reply to
emails).
