### ISSUE TITLE
Disney+ incorrectly autodetecting 5.1 audio

### ISSUE THREAD

**Issue by jreicher** [google/ExoPlayer#9838]
From what I can tell Disney+ uses exoplayer2, and on a Changhong TV with builtin stereo speakers it is incorrectly attempting to play more than two channels.

I suspect the problem is that Changong's audio policy is incorrect, but is there an easy way you can help me confirm this so I can ask them to update?

Excerpt of "adb shell dumpsys media.audio_policy" (please tell me if a different excerpt is required):

  - Declared devices:
    Device 1:
    - id:  2
    - tag name: Speaker
    - type: AUDIO_DEVICE_OUT_SPEAKER
    - Profiles:
        Profile 0:
            - format: AUDIO_FORMAT_PCM_16_BIT
            - sampling rates:48000
            - channel masks:0x0003
        Profile 1:
            - format: AUDIO_FORMAT_AC3
            - sampling rates:8000, 11025, 12000, 16000, 22050, 24000, 32000, 44100, 48000, 96000, 192000
            - channel masks:0x0001, 0x0003, 0x0007, 0x000b, 0x0033, 0x0037, 0x003f, 0x0103, 0x0107, 0x013f, 0x0603, 0x060f, 0x063f, 0xc0003, 0xc0007, 0xc000b, 0xc000f, 0xc003f
        Profile 2:
            - format: AUDIO_FORMAT_E_AC3
            - sampling rates:8000, 11025, 12000, 16000, 22050, 24000, 32000, 44100, 48000, 96000, 192000
            - channel masks:0x0001, 0x0003, 0x0007, 0x000b, 0x0033, 0x0037, 0x003f, 0x0103, 0x0107, 0x013f, 0x0603, 0x060f, 0x063f, 0xc0003, 0xc0007, 0xc000b, 0xc000f, 0xc003f
        Profile 3:
            - format: AUDIO_FORMAT_E_AC3_JOC
            - sampling rates:8000, 11025, 12000, 16000, 22050, 24000, 32000, 44100, 48000, 96000, 192000
            - channel masks:0x0001, 0x0003, 0x0007, 0x000b, 0x0033, 0x0037, 0x003f, 0x0103, 0x0107, 0x013f, 0x0603, 0x060f, 0x063f, 0xc0003, 0xc0007, 0xc000b, 0xc000f, 0xc003f

**Comment by ojw28** [comment]
Disney+ most likely have their own logic for choosing when to use surround audio, so I think you'd have to reach out to them about it. Thanks!
