### ISSUE TITLE
Player jumps video when seek or repeat again track.

### ISSUE THREAD

**Issue by nisecap12** [google/ExoPlayer#9849]
I have a problem when playing the file below. 
https://drive.google.com/file/d/10invVkxpKGd4Lms8ybVH73H-ipuNi3-X/view

The first playback is normal. but try to seek or repeat again the file, ExoPlayer jump video with 
UnexpectedDiscontinuityException.

============== discontinuos Error====================
01-10 11:04:53.861 E 22494    22550    MediaCodecAudioRenderer:                                 Audio sink error 
01-10 11:04:53.861 E 22494    22550    MediaCodecAudioRenderer:                                   com.google.android.exoplayer2.audio.AudioSink$UnexpectedDiscontinuityException: Unexpected audio track timestamp discontinuity: expected -9223372036854743807, got 971367 
01-10 11:04:53.861 E 22494    22550    MediaCodecAudioRenderer:                                       at com.google.android.exoplayer2.audio.DefaultAudioSink.handleBuffer(DefaultAudioSink.java:792) 
01-10 11:04:53.861 E 22494    22550    MediaCodecAudioRenderer:                                       at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(MediaCodecAudioRenderer.java:637) 
01-10 11:04:53.861 E 22494    22550    MediaCodecAudioRenderer:                                       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1917) 
01-10 11:04:53.861 E 22494    22550    MediaCodecAudioRenderer:                                       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:843) 
01-10 11:04:53.861 E 22494    22550    MediaCodecAudioRenderer:                                       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:945) 
01-10 11:04:53.861 E 22494    22550    MediaCodecAudioRenderer:                                       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:478) 
01-10 11:04:53.861 E 22494    22550    MediaCodecAudioRenderer:                                       at android.os.Handler.dispatchMessage(Handler.java:103) 
01-10 11:04:53.861 E 22494    22550    MediaCodecAudioRenderer:                                       at android.os.Looper.loop(Looper.java:214) 
01-10 11:04:53.861 E 22494    22550    MediaCodecAudioRenderer:                                       at android.os.HandlerThread.run(HandlerThread.java:67) 

=========== test code =============
private void createPlayer() {
        player = new SimpleExoPlayer.Builder(this).build();
        try {

            for(File file : files) {
                player.addMediaItem(MediaItem.fromUri("file://" + file.getAbsolutePath()));
            }

            player.setVideoSurface(surface);
            player.setPlayWhenReady(true);
            player.setRepeatMode(Player.REPEAT_MODE_ALL);
            player.addAnalyticsListener(new ExoPlayerEventListener());
            player.prepare();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

ExoPlayer version : 2.14.1
Android Version : 10.x

Please let me know what options I should set on ExoPlayer. or file error.
Thank you

**Comment by christosts** [comment]
I do see something is going wrong in 2.14.2 but it appears to be working on 2.16.2. Can you please use/upgrade to the latest ExoPlayer version (currently 2.16.2) and try?

**Comment by nisecap12** [comment]
I checked the file plays well on latest ExoPlayer version (2.16.1).
Thank you for your help!
