### ISSUE TITLE
Green stripe up the top in HLS/H265 stream

### ISSUE THREAD

**Issue by cizekmilan** [google/ExoPlayer#985]
Hi,
I have TV box RK3128 with Android 4.4.4, ExoPlayer 1.5.2 and I have problem with HLS (H265) playback with ExoPlayer.
My stream is played, I see/hear video and audio content.
But one of the colours in video has small offset and small green stripe on the top is showed.
Color offset and stripe height is depended on video resolution.

http://download.mazana.tv/windows/h265test/01.jpg
http://download.mazana.tv/windows/h265test/02.jpg

Other H265 demos play correctly without this problem.
My H265 stream is created by ffmpeg and CUDA/nvenc_h265. Other players (VLC, MXPlayer...) work without this problem (or does not play due H265 is not supported).
http://download.mazana.tv/windows/h265test/vlc.jpg

I sent my stream url private.

The debug log seems good.
Thank you for help.

11-24 12:58:47.261 30320-30320/com.google.android.exoplayer.demo I/dalvikvm: Could not find method android.view.accessibility.CaptioningManager$CaptionStyle.hasForegroundColor, referenced from method com.google.android.exoplayer.text.CaptionStyleCompat.createFromCaptionStyleV21
11-24 12:58:47.261 30320-30320/com.google.android.exoplayer.demo W/dalvikvm: VFY: unable to resolve virtual method 275: Landroid/view/accessibility/CaptioningManager$CaptionStyle;.hasForegroundColor ()Z
11-24 12:58:47.261 30320-30320/com.google.android.exoplayer.demo D/dalvikvm: VFY: replacing opcode 0x6e at 0x0002
11-24 12:58:47.271 30320-30320/com.google.android.exoplayer.demo D/dalvikvm: DexOpt: couldn't find field Landroid/view/accessibility/CaptioningManager$CaptionStyle;.windowColor
11-24 12:58:47.271 30320-30320/com.google.android.exoplayer.demo I/dalvikvm: DexOpt: unable to optimize instance field ref 0x002c at 0x18 in Lcom/google/android/exoplayer/text/CaptionStyleCompat;.createFromCaptionStyleV21
11-24 12:58:47.341 30320-30320/com.google.android.exoplayer.demo D/dalvikvm: GC_FOR_ALLOC freed 184K, 6% free 3361K/3572K, paused 29ms, total 30ms
11-24 12:58:47.501 30320-30320/com.google.android.exoplayer.demo I/ExoPlayerImpl: Init 1.5.2
11-24 12:58:47.521 30320-30320/com.google.android.exoplayer.demo D/EventLogger: start [0]
11-24 12:58:47.521 30320-30320/com.google.android.exoplayer.demo D/EventLogger: state [0.00, false, P]
11-24 12:58:47.531 30320-30320/com.google.android.exoplayer.demo D/EventLogger: state [0.01, true, P]
11-24 12:58:47.791 30320-30320/com.google.android.exoplayer.demo I/dalvikvm: Could not find method android.media.MediaCodec.releaseOutputBuffer, referenced from method com.google.android.exoplayer.MediaCodecVideoTrackRenderer.renderOutputBufferV21
11-24 12:58:47.791 30320-30320/com.google.android.exoplayer.demo W/dalvikvm: VFY: unable to resolve virtual method 81: Landroid/media/MediaCodec;.releaseOutputBuffer (IJ)V
11-24 12:58:47.791 30320-30320/com.google.android.exoplayer.demo D/dalvikvm: VFY: replacing opcode 0x6e at 0x0008
11-24 12:58:47.801 30320-30320/com.google.android.exoplayer.demo I/dalvikvm: Could not find method android.media.AudioTrack.write, referenced from method com.google.android.exoplayer.audio.AudioTrack.writeNonBlockingV21
11-24 12:58:47.801 30320-30320/com.google.android.exoplayer.demo W/dalvikvm: VFY: unable to resolve virtual method 64: Landroid/media/AudioTrack;.write (Ljava/nio/ByteBuffer;II)I
11-24 12:58:47.801 30320-30320/com.google.android.exoplayer.demo D/dalvikvm: VFY: replacing opcode 0x6e at 0x0001
11-24 12:58:47.881 30320-30887/com.google.android.exoplayer.demo D/dalvikvm: GC_FOR_ALLOC freed 442K, 11% free 3870K/4340K, paused 33ms, total 33ms
11-24 12:58:47.921 30320-30880/com.google.android.exoplayer.demo I/OMXClient: Using client-side OMX mux.
11-24 12:58:47.941 30320-30880/com.google.android.exoplayer.demo I/OMXClient: Using client-side OMX mux.
11-24 12:58:47.981 30320-30897/com.google.android.exoplayer.demo I/OMXClient: Using client-side OMX mux.
11-24 12:58:47.981 30320-30320/com.google.android.exoplayer.demo D/EventLogger: state [0.46, true, B]
11-24 12:58:47.981 30320-30320/com.google.android.exoplayer.demo D/EventLogger: videoFormat [0.46, 0, 0]
11-24 12:58:47.991 30320-30897/com.google.android.exoplayer.demo E/ACodec: [OMX.rk.video_decoder.hevc] storeMetaDataInBuffers failed w/ err -2147483648
11-24 12:58:48.421 30320-30320/com.google.android.exoplayer.demo D/EventLogger: decoderInitialized [0.90, OMX.rk.video_decoder.hevc]
11-24 12:58:48.441 30320-30904/com.google.android.exoplayer.demo I/OMXClient: Using client-side OMX mux.
11-24 12:58:48.501 30320-30904/com.google.android.exoplayer.demo D/ACodec: MEDIA_MIMETYPE_AUDIO_AAC sampleRate 44100 wifidisplay_flag 0 info 5fbe1d90
11-24 12:58:48.511 30320-30320/com.google.android.exoplayer.demo D/EventLogger: decoderInitialized [0.99, OMX.google.aac.decoder]
11-24 12:58:48.511 30320-30906/com.google.android.exoplayer.demo I/SoftAAC2: Reconfiguring decoder: 0->44100 Hz, 0->2 channels
11-24 12:58:48.521 30320-30880/com.google.android.exoplayer.demo I/Choreographer: Skipped 32 frames!  The application may be doing too much work on its main thread.
11-24 12:58:48.621 30320-30887/com.google.android.exoplayer.demo D/dalvikvm: GC_FOR_ALLOC freed 40K, 9% free 4607K/5020K, paused 37ms, total 38ms
11-24 12:58:48.701 30320-30320/com.google.android.exoplayer.demo D/EventLogger: videoSizeChanged [1920, 1080, 0, 1.0]
11-24 12:58:48.751 30320-30320/com.google.android.exoplayer.demo D/EventLogger: state [1.23, true, R]
11-24 12:58:50.281 30320-30887/com.google.android.exoplayer.demo D/dalvikvm: GC_FOR_ALLOC freed 20K, 7% free 5573K/5972K, paused 37ms, total 37ms

[341719.330335] type=1400 audit(1448371652.291:22): avc:  denied  { write } for pid=21137 comm="ExoPlayerImplIn" name="property_service" dev="tmpfs" ino=3310s context=u:r:untrusted_app:s0 tcontext=u:object_r:property_socket:s0 tclass=sock_file permissive=1
[341719.330946] init: sys_prop: permission denied uid:10072  name:media.cfg.audio.soundeffect
[341719.336527] hevc_service: power on
[341719.419194] lowmemorykiller: Killing 'com.svox.pico' (3669), adj 1000,
[341719.419194]    to free 17188kB on behalf of 'kswapd0' (55) because
[341719.419194]    cache 59548kB is below limit 61440kB for oom_score_adj 1000
[341719.419194]    Free memory is 1468kB above reserved
[341720.292022] 10180000.usb resume, HPRT0:0x1000
[341720.292189] 10180000.usb suspend, HPRT0:0x1000
[341721.384491] 10180000.usb resume, HPRT0:0x1000
[341721.384705] 10180000.usb suspend, HPRT0:0x1000
[341722.216450] lowmemorykiller: Killing 'chip.devicetest' (540), adj 1000,
[341722.216450]    to free 17056kB on behalf of 'kswapd0' (55) because
[341722.216450]    cache 59008kB is below limit 61440kB for oom_score_adj 1000
[341722.216450]    Free memory is -2004kB above reserved
[341722.226720] lowmemorykiller: Killing 'ericenceService' (31737), adj 1000,
[341722.226720]    to free 16848kB on behalf of 'kswapd0' (55) because
[341722.226720]    cache 55984kB is below limit 61440kB for oom_score_adj 1000
[341722.226720]    Free memory is 1608kB above reserved
[341722.477504] 10180000.usb resume, HPRT0:0x1000
[341722.477860] 10180000.usb suspend, HPRT0:0x1000
[341723.568484] 10180000.usb resume, HPRT0:0x1000
[341723.568668] 10180000.usb suspend, HPRT0:0x1000
[341724.661347] 10180000.usb resume, HPRT0:0x1000
[341724.661709] 10180000.usb suspend, HPRT0:0x1000
[341725.356881] hevc_service: power off...
[341725.356969] done

**Comment by ojw28** [comment]
This is either a decoder issue specific to RK3128 or an issue with the content. Probably the first one.

**Comment by ojw28** [comment]
This doesn't reproduce on other devices (at least not the ones I tested on). You'll need to report the issue to the device manufacturer.

**Comment by cizekmilan** [comment]
We can donate one RK3128 for debugging.

**Comment by ojw28** [comment]
What is the H265 decoder being used on the device? Unless it's a google provided software decoder then the device manufacturer needs to fix the issue, and having access to a device wont help. You'd have to report the issue to the device manufacturer directly.

**Comment by ssaguiar** [comment]
I have the same problem with my Samsung Galaxy S3 9GT-I9300), Android 4.3 original from Samsung.
I can't find how to disable hardware acceleration in exoplayer code.
We had this problem before and used vlc lib to implement the player, so we could disable hardware acceleration if needed. This solved the problem.
![hard](https://cloud.githubusercontent.com/assets/5515284/15114381/1599efc0-15d0-11e6-8410-32d29fcabf93.png)
