### ISSUE TITLE
Video recorded with an IOS device(iphone 8) is not beeing smooth rendered within the player

### ISSUE THREAD

**Issue by petruseldiana** [google/ExoPlayer#9854]
Here is the link to the video: https://storage.googleapis.com/ring4all-stg/cdL9sx3OvLzf1WY.mp4
Even if it is jerkily rendered within the browser too, it is being played smoothly on an IOS device.

Android version: 9
ExoPlayer version number: 2.16.1

**Comment by icbaker** [comment]
I played the provided video on a OnePlus AC2003 and a Pixel 5 using the [ExoPlayer demo app](https://exoplayer.dev/demo-application.html) at version 2.16.1. In both cases the playback seems smooth.

What devices are you seeing not-smooth playback on? Please also provide an `adb bugreport` taken after observing the non-smooth playback with the demo app. Please either upload it here or send to dev.exoplayer@gmail.com using a subject in the format `Issue #1234` (where `#1234` should be replaced with this issue number). Please also update this issue to indicate you’ve done this.

**Comment by petruseldiana** [comment]
I have played it within the ExoPlayer demo app and has the same behavior, the video is not being rendered smooth, has interruptions. So you can find the adb bugreport below.
The device is: Tablet TDS10192T, android version 9.
[ExoPlayer.zip](https://github.com/google/ExoPlayer/files/7856242/ExoPlayer.zip)

**Comment by petruseldiana** [comment]
I have played the same video within the ExoPlayer demo app on an OnePlus2 device, Android Version 6.0.1, Model number ONE A2003 and the video is not being played at all. The following error is being thrown: 

E/EventLogger: playerFailed [eventTime=3.84, mediaPos=0.00, window=0, period=0, errorCode=ERROR_CODE_DECODING_FAILED
      com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(2, null, null, video/avc, avc1.640034, -1, null, [3840, 2160, 60.0], [-1, -1]), format_supported=NO_EXCEEDS_CAPABILITIES
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:562)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:152)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: com.google.android.exoplayer2.video.MediaCodecVideoDecoderException: Decoder failed: OMX.qcom.video.decoder.avc
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1470)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:799)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:982)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:486)
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:152) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
     Caused by: java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2379)
        at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.dequeueOutputBufferIndex(SynchronousMediaCodecAdapter.java:122)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1764)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:778)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:982) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:486) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:152) 
        at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by icbaker** [comment]
The bug report provided seems to be using the [ExoPlayer GL Demo App](https://github.com/google/ExoPlayer/tree/release-v2/demos/gl) - is that deliberate? It would probably be more representative of a 'normal' playback to use the [main demo app](https://github.com/google/ExoPlayer/tree/release-v2/demos/main).

The error from the OnePlus2 looks expected - the device states the video is beyond its capabilities (`format_supported=NO_EXCEEDS_CAPABILITIES`), probably because the resolution is too high for the decoder. ExoPlayer still tries to play the video because sometimes playback succeeds despite this warning - but not in this case it seems.

**Comment by petruseldiana** [comment]
I have generated the report using the main demo app, the behavior is the same, there are interruptions on the tablet device. Please check the attached zip.
[ExoPlayer-main-demo-app.zip](https://github.com/google/ExoPlayer/files/7856470/ExoPlayer-main-demo-app.zip)

**Comment by icbaker** [comment]
I'm not sure why, but both bug reports seem to be missing some lines I'd expect to see, in particular a line like this (probably with a different codec name):

```
D/EventLogger: videoDecoderInitialized [eventTime=0.43, mediaPos=0.00, window=0, period=0, c2.qti.avc.decoder]
```

And another like this (obviously with different resolution/codec details):
```
D/EventLogger: tracks [eventTime=0.13, mediaPos=0.00, window=0, period=0
D/EventLogger:   MediaCodecVideoRenderer [
D/EventLogger:     Group:0, adaptive_supported=N/A [
D/EventLogger:       [X] Track:0, id=2, mimeType=video/avc, codecs=avc1.016742, res=480x360, fps=30.0, supported=YES
D/EventLogger:     ]
D/EventLogger:   ]
D/EventLogger:   MediaCodecAudioRenderer [
D/EventLogger:     Group:0, adaptive_supported=N/A [
D/EventLogger:       [X] Track:0, id=1, mimeType=audio/mp4a-latm, codecs=mp4a.40.2, channels=2, sample_rate=44100, language=und, supported=YES
D/EventLogger:     ]
D/EventLogger:   ]
D/EventLogger:   TextRenderer []
D/EventLogger:   MetadataRenderer []
D/EventLogger:   CameraMotionRenderer []
D/EventLogger: ]
```

In particular I'm interested to see:
* Whether the playback is using a hardware or software decoder
* Whether the chosen video decoder claims to support the video format

My suspicion (for which I don't have any/much evidence) is that the AVC hardware decoder on this device doesn't support content of this resolution, and so ExoPlayer chooses a software decoder - which is then unable to play it smoothly. Basically, I suspect this device is just not performant enough to play this 4k content - and there's not really much ExoPlayer can do about that I'm afraid.

If you can spot lines like those I've pasted above in the logcat when you play the content and can paste them back here it might be able to support or discredit my hypothesis.

**Comment by petruseldiana** [comment]
You can find the missing lines from the report below: 

D/EventLogger: videoDecoderInitialized [eventTime=1.86, mediaPos=0.00, window=0, period=0, OMX.MTK.VIDEO.DECODER.AVC]

D/EventLogger: tracks [eventTime=1.71, mediaPos=0.00, window=0, period=0
D/EventLogger:   MediaCodecVideoRenderer [
D/EventLogger:     Group:0, adaptive_supported=N/A [
D/EventLogger:       [X] Track:0, id=2, mimeType=video/avc, codecs=avc1.640034, res=3840x2160, fps=60.0, supported=NO_EXCEEDS_CAPABILITIES
D/EventLogger:     ]
D/EventLogger:   ]
D/EventLogger:   MediaCodecAudioRenderer [
D/EventLogger:     Group:0, adaptive_supported=N/A [
D/EventLogger:       [X] Track:0, id=1, mimeType=audio/mp4a-latm, codecs=mp4a.40.2, channels=1, sample_rate=44100, language=und, supported=YES
D/EventLogger:     ]
D/EventLogger:   ]

**Comment by icbaker** [comment]
Thanks - it looks like my theory was half-correct: The decoder selected looks like a hardware decoder (`OMX.MTK.VIDEO.DECODER.AVC`) but it is reporting the video is beyond its capabilities (`supported=NO_EXCEEDS_CAPABILITIES`), so it's understandable that the playback is not smooth.

The conclusion is the same: This device's decoder is not performant enough to play this video in real-time without frame drops. I'm going to close this issue because there's nothing ExoPlayer can really do here.

**Comment by petruseldiana** [comment]
Thank you very much for your time and for your explanations.
