### ISSUE TITLE
FFMPEG EXTENSION USAGE

### ISSUE THREAD

**Issue by SrRapero720** [google/ExoPlayer#9858]
I just installed the FFmpeg extension and it seems to fit but I don't know how to use it and the information in the README.md doesn't help me much.

If someone can help me? I already looked elsewhere for its use and I only find how to compile it but not how to use it

**Comment by icbaker** [comment]
The README page has a section on 'Using the module': https://github.com/google/ExoPlayer/blob/release-v2/extensions/ffmpeg/README.md#using-the-module

In order to help you further we need much more information about what you've tried and what happened.

**Comment by SrRapero720** [comment]
I am trying to play a MKV video with AC3 audio format. but it always threw this error
`E / ACodec: [OMX.google.h264.decoder] setPortMode on output to DynamicANWBuffer failed w / err -1010`

then I checked the list of supported codecs and saw that AC3 and EAC3 were not supported. so install the FFMPEG EXTENSION to support the. but in 
https://github.com/google/ExoPlayer/blob/release-v2/extensions/ffmpeg/README.md#using-the-module 
doesn't tell me anything about how to use it

**Comment by SrRapero720** [comment]
i found an example
