### ISSUE TITLE
PlayerView click handling if finger is lifted outside view

### ISSUE THREAD

**Issue by ivk1800** [google/ExoPlayer#9861]
If drag finger started on player view and end on outside view, triggered MotionEvent.ACTION_UP event and triggered toggle player controls. also if begin drag finger on playerview and end on it, player controls same triggered. 

Reproduction steps:
-------------------------

open demo app, modify player_activity.xml set some fixed hegiht for playerview, example 100dp
run on device or emulator. play any example from list.

- ExoPlayer version number: r2.16.1
- Android version: any supported version
- Android device: any supported device

**Comment by icbaker** [comment]
I can reproduce the described behaviour (using `StyledPlayerView` for completeness) - over to Olly to decide whether both of these are bugs and how to handle them:
* drag finger starting on player view and end outside view: player controls are shown
* drag finger starting on player view and elsewhere inside the view: player controls are shown

I note that touching outside the player view and dragging a finger inside it before releasing **does not** trigger the controls.

**Comment by ojw28** [comment]
Fixed in `dev-v2`. The fix will be included in 2.18.
