### ISSUE TITLE
This stream does not play

### ISSUE THREAD

**Issue by lpv-1902** [google/ExoPlayer#9863]
Hello, may we know why this stream does not work on ExoPlayer but works on VLC. Thank you!

http://hdstreamzz.xyz:9981/Joe_joe/XTj5JLv4PW/16

**Comment by christosts** [comment]
The video played fine on a Pixel 4 device with ExoPlayer 2.16.1. Can you please provide more information on the behavior you are observing? Consider providing us with the information requested in the [issue template](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md), such as the version of the player used, the device and OS version, and a [bug report](https://developer.android.com/studio/debug/bug-report) obtained from the device after the issue occurs.

Note that if you're unable to share a bug report publicly, please send them to dev.exoplayer@gmail.com with subject "Issue #9863" and update this issue to indicate you've done this.

Thank you.

**Comment by lpv-1902** [comment]
Thank you for replying. I've been getting a "com.google.android.exoplayer2.source.UnrecognizedInputFormatException: Input does not start with the #EXTM3U header." error. 

Device: Android TV on Android 10
Exoplayer version: 2.11.7

It's quite difficult to upgrade as we are using a Xamarin fork of the player. Might there be a workaround for this?

**Comment by christosts** [comment]
The error indicates that you are using an `HlsMediaSource`, expecting the media to be `HLS`. However the link you provided is not HLS and it is progressive type for which you should use the `ProgressiveMediaSource`

**Comment by lourokuph** [comment]
tried testing. your stream does not load at all.

**Comment by lourokuph** [comment]
> Hello, may we know why this stream does not work on ExoPlayer but works on VLC. Thank you!
> 
> http://hdstreamzz.xyz:9981/Joe_joe/XTj5JLv4PW/16

stream wont load.
