### ISSUE TITLE
Talkback gets interrupted while exoplayer starts playback

### ISSUE THREAD

**Issue by sandeepReddyG** [google/ExoPlayer#9867]
I am currently working on exoplayer and I come across this issue while testing a simple application with exoplayer. I was testing Talkback with my application and when exoplayer initially starts playback , the contentDescription for the current selected button view gets interrupted in between. 

Here is my application code:
-------------------------------
  ```
public class MainActivity extends Activity {

  private RelativeLayout mRootView;
  private RelativeLayout otherView;
  private RelativeLayout playPauseButton;
  private Button mBtn;
  private AudioManager mAudioManager;
  private PlayerView mExoplyerView;
  private ExoPlayer mExoplayer;
  private Format format;
  //Set the URL of the video you want to play here (currently hls clear playback)
  private final static String mVideoURI = "https://d3bqrzf9w11pn3.cloudfront.net/basic_hls_bbb_clear/index.m3u8";


  @override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);

    setContentView(R.layout.content_main);

    mExoplyerView = findViewById(R.id.ExoplayerView);
    mRootView = findViewById(R.id.rl_root_view);
    otherView = findViewById(R.id.other_view);
    playPauseButton = findViewById(R.id.play_pause_button);

    mExoplayer= new ExoPlayer.Builder(getApplicationContext()).build();
    MediaItem mediaItem = new MediaItem.Builder().setUri(Uri.parse(mVideoURI)).build();
    mExoplayer.setMediaItem(mediaItem);
    AudioAttributes audioAttributes = new AudioAttributes.Builder()
            .setUsage(C.USAGE_MEDIA)
            .setContentType(C.CONTENT_TYPE_MOVIE)
            .build();
    mExoplayer.setAudioAttributes(audioAttributes,true);
    mExoplayer.prepare();
    mExoplayer.setPlayWhenReady(false);
    mExoplyerView.setPlayer(mExoplayer);

    mExoplyerView.setContentDescription("SDIDI");

    playPauseButton.setOnClickListener(new View.OnClickListener() {
      @Override
      public void onClick(View view) {
        new Handler().postDelayed(new Runnable() {
          @Override
          public void run() {

            mExoplayer.play();
          }
        }, 2000);
      }
    });
  }

 
  @Override
  public void onPause() {
    super.onPause();
    mExoplayer.pause();
  }


  @Override
  public void onResume() {
    super.onResume();

  }

}
```

Here is my Layout:
--------------------
```
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/rl_root_view"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <com.google.android.exoplayer2.ui.PlayerView
        android:id="@+id/ExoplayerView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
 />

    <RelativeLayout
        android:id="@+id/other_view"
        android:layout_width="100dp"
        android:layout_height="100dp"
        android:background="@android:color/holo_blue_bright"
        android:layout_marginBottom="100dp"
        android:contentDescription="This is a very long text that must be read until the end, so we can test the accessibility feature."
        android:importantForAccessibility="yes" />

    <RelativeLayout
        android:id="@+id/play_pause_button"
        android:layout_width="100dp"
        android:layout_height="100dp"
        android:background="@android:color/holo_green_dark"
        android:contentDescription="This is a very long text that must be read until the end, so we can test the accessibility feature."
        android:importantForAccessibility="yes"
        android:layout_below="@+id/other_view" />

</RelativeLayout>
```

Steps to reproduce issue:
--------------------------
- Enable talkback and launch application and tap a button to see if talkback reading contentDescription of button.
- Double tap the play/pause button to start playback after 2 seconds and within these two seconds tap one of the button in layout to start talkback reading its content description.
- While talkback reading the content description of button, the playback starts and interrupts the talkback .
- I am expecting the content description to continue while playback starting up or if talkback gets interrupted ,the talkback should read playerView content description.

**Comment by christosts** [comment]
> I am expecting the content description to continue while playback starting up or if talkback gets interrupted ,the talkback should read playerView content description.

As far as I understand, this is currently working as intended. When the player gains audio focus, this interrupts on-going text-to-speech. Have you observed a different behavior on this, or do you have a link to a document suggesting otherwise?

**Comment by zgzong** [comment]
Thanks @christosts for your reply. 
After player gain the audio focus, talkback can speak while player is playing audio together. 
Even set player start with audio focus type AUDIOFOCUS_GAIN_TRANSIENT_MAY_DUCK, the talkback speech still be interrupted when player starts playback.

**Comment by christosts** [comment]
Thank you for testing with a different audio focus type.

As mentioned above, this seems to be working as expected: when the player starts playing audio and requests audio focus, that interrupts any on-going text-to-speech. It is expected that text-to-speech will be interrupted in this use-case. 

You previously wrote that you expect `the content description to continue while playback starting` which I think is not the expected behavior. This behavior is coming from TalkBack and/or the Android audio system and not from ExoPlayer.

My question is whether you have observed your expected behavior: Have you seen another use-case where Talkback continues to speak while another app starts outputting audio?

**Comment by sandeepReddyG** [comment]
@christosts  thanks for your support. Closing the issue as this is the expected behaviour.
