### ISSUE TITLE
Imaads not playing with mediasource

### ISSUE THREAD

**Issue by NagarjunaVeeramalla** [google/ExoPlayer#9869]
I'm implementing IMA-ads with exoplayer, I have different kinds of feeds like hls, dash etc. When I'm trying to build the media source with any of the feed like HLS or Dash, ads are not getting initiated. Please find my code below for better understanding. I'm not getting any kind of error in logs also.

    private var adsLoader: ImaAdsLoader? = null
    private var dataSourceFactory: DataSource.Factory? = null

    dataSourceFactory= DefaultDataSource.Factory(this)

        val mediaSourceFactory: DefaultMediaSourceFactory =
            DefaultMediaSourceFactory(
            dataSourceFactory!!
        )
            .setAdsLoaderProvider(this::getAdsLoader)
            .setAdsLoaderProvider(DefaultMediaSourceFactory.AdsLoaderProvider { unusedAdTagUri: MediaItem.AdsConfiguration? -> adsLoader })
            .setAdViewProvider(playerView)

    private fun buildMediaSource(uri: Uri): MediaSource? {
        @C.ContentType val type = Util.inferContentType(uri)
        return when (type) {
            com.google.android.exoplayer2.C.TYPE_DASH -> DashMediaSource.Factory(
                dataSourceFactory!!
            ).createMediaSource(createMediaItem(uri)!!)
            com.google.android.exoplayer2.C.TYPE_SS -> SsMediaSource.Factory(
                dataSourceFactory!!
            )
                .createMediaSource(createMediaItem(uri)!!)
            com.google.android.exoplayer2.C.TYPE_HLS ->
                HlsMediaSource.Factory(
                dataSourceFactory!!
            )
                .setAllowChunklessPreparation(true)
                    .createMediaSource(createMediaItem(uri)!!)
            com.google.android.exoplayer2.C.TYPE_OTHER -> ProgressiveMediaSource.Factory(
                dataSourceFactory!!
            ).createMediaSource(createMediaItem(uri)!!)
            else -> throw IllegalStateException("Unsupported type: $type")
        }
    }

    private fun createMediaItem(uri: Uri): MediaItem? {
        val adTagUri =
            Uri.parse("https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ar%3Dpreonly&cmsid=496&vid=short_onecue&correlator=")
        @C.ContentType val type = Util.inferContentType(uri)
        return when (type) {
            C.TYPE_DASH,
            C.TYPE_HLS -> MediaItem.Builder()
                .setUri(uri)
                .setAdsConfiguration(MediaItem.AdsConfiguration.Builder(adTagUri).build())
                .setMimeType(MimeTypes.APPLICATION_M3U8)
                .build()
            C.TYPE_SS -> MediaItem.Builder()
                .setUri(uri)
                .setAdsConfiguration(MediaItem.AdsConfiguration.Builder(adTagUri).build())
                .setMimeType(MimeTypes.APPLICATION_SS)
                .build()
            C.TYPE_OTHER -> MediaItem.Builder()
                .setUri(uri)
                .setAdsConfiguration(MediaItem.AdsConfiguration.Builder(adTagUri).build())
                .setMimeType(MimeTypes.BASE_TYPE_APPLICATION)
                .build()
            else -> throw IllegalStateException("Unsupported type: $type")
        }
    }

**Comment by marcbaechinger** [comment]
Please also consult the [Developer Guide that covers playing ads](https://exoplayer.dev/ad-insertion.html).

The easiest way to play ads is by only using a `MediaItem` and then let the player build the `MediaSource` for it:

#### 1. Add the dependency to the IMA extension
See the [README](https://github.com/google/ExoPlayer/tree/release-v2/extensions/ima) for that.

#### 2. Set up the `DefaultMediaSourceFactory`

You already have a snippet in your code above that does this. Here is a [snippet from the demo app](https://github.com/google/ExoPlayer/blob/release-v2/demos/main/src/main/java/com/google/android/exoplayer2/demo/PlayerActivity.java#L264
).

```
MediaSourceFactory mediaSourceFactory =
    new DefaultMediaSourceFactory(dataSourceFactory)
        .setAdsLoaderProvider(this::getAdsLoader)
        .setAdViewProvider(playerView);
```

#### 3. Build the `Player` with the `DefaultMediaSourceFactory`

```
player =
    new ExoPlayer.Builder(/* context= */ this)
    .setMediaSourceFactory(mediaSourceFactory)
    .build();
```

#### 4. Build a `MediaItem` and set it to the player

```
MediaItem mediaItem =
    new MediaItem.Builder()
        .setUri(videoUri)
        .setAdsConfiguration(
            new MediaItem.AdsConfiguration.Builder(adTagUri).build())
        .build();

player.setMediaItem(mediaItem);
```

This works with all stream types (DASH, HLS and progressive streams). There is no need to create the `MediaSource` yourself unless you have very specific requirements. By using a declarative with the `MediaItem` you are all set. 

In case you can infer the type of the media from the URI like your code above suggests, you can even drop the MIME  type as ExoPlayer does infer the type in the same way from the URI. If you want to set the MIME type, you should not use the same MIME type for HLS and DASH as your code above does. Instead use (`MimeTypes.imeTypes.APPLICATION_M3U8` for HLS and `MimeTypes.APPLICATION_MPD` for DASH.)
