### ISSUE TITLE
Upgrade from 1.4.2 to 1.5.0: Android Studio shows compiler errors but "cannot resolve symbol"

### ISSUE THREAD

**Issue by DavidMihola** [google/ExoPlayer#987]
I just tried to upgrade from version 1.4.2 to version 1.5.0 (or any version above that).

The sync after the change in my `build.gradle` worked and the `build/intermediates/exploded-aar/com.google.android.exoplayer/exoplayer/r1.5.0/jars/classes.jar` does exist. So, it seems that AS was able to download the new version of Exoplayer.

Also, I get compiler errors for changed method signatures, for example, `BaseChunkSampleSourceEventListener`.

And yet, AS at the same time claims that it cannot resolve any symbol from the Exoplayer library, all the exoplayer imports are marked as errors and Alt-Enter does not propose to import the class.

I've also tried "Invalidate caches & restart' as well as completely re-importing the project as a Gradle project. Nothing worked.

I have never this when upgrading any other depedency, nor with earlier Exoplayer updates, but I do not seem to be the only one with this problem: http://stackoverflow.com/questions/33079547/after-updating-library-in-android-studio-cannot-see-any-class

What is going on?

**Comment by DavidMihola** [comment]
I now fixed all the compiler errors (by looking at the error message and using the source code to work out a solution) and now AS is suddenly able to find all the Exoplayer classes again...

**Comment by ojw28** [comment]
We don't aim to retain API compatibility between versions of ExoPlayer. The API is so large due to its extensible/flexible nature, that trying to retain compatibility would significantly hinder our efforts to make the library better.

As for why AS decided to show you errors for every import, that sounds like an AS issue rather than anything related to ExoPlayer :).

**Comment by DavidMihola** [comment]
@ojw28 Thank you very much for your reply!

Regarding "breaking API changes": Yes, of course and I only mentioned them to illustrate that somehow AS does know about the upgraded ExoPlayer library, not to complain about them.

Regarding "import errors in AS": OK, but is there anything peculiar to the ExoPlayer library that could play into that weird behavior? As I said, I'm not the only one to experience this problem with exactly this upgrade but not with any others... But I do realize that it is probably not a pressing issue for many and I am asking mostly out of curiosity.

Thanks again!
