### ISSUE TITLE
Unable to fetch the Chunk Size and Latency during playing the video

### ISSUE THREAD

**Issue by satishkumar-tudip** [google/ExoPlayer#9870]
Hi Team,

Currently, I am using the 2.12.1 version and trying to fetch the Chunk Size and Latency by calling the MediaSourceEventListener but I didn't get a call inside the onLoadCompleted Override method.

Please find the onLoadCompleted method logic

@Override
    public void onLoadCompleted(int windowIndex, @Nullable MediaSource.MediaPeriodId mediaPeriodId, LoadEventInfo loadEventInfo, MediaLoadData mediaLoadData) {
        mLatestChunkLatency = loadEventInfo.loadDurationMs;
        mLatestChunkSize = (int) ((mediaLoadData.mediaEndTimeMs - mediaLoadData.mediaStartTimeMs) / 1000);
    }
    
    How to find the Chunk Size and Latency without updating the version?

**Comment by christosts** [comment]
I don't know how you are creating MediaSources and attaching listeners to them in your app, however can you try attaching an `AnalyticsListener` to the player and override its `onLoadCompleted()`?

Let me know if that worked.

**Comment by satishkumar-tudip** [comment]
Hi @christosts 
Thank you for the reply, I have already attached the AnalyticsListener and it's working now.
