### ISSUE TITLE
bytesSkipped() and  bytesRead() DefaultHttpDataSource 

### ISSUE THREAD

**Issue by louiewh** [google/ExoPlayer#9873]
Before filing a feature request:
-----------------------
- Search existing open issues, specifically with the label ‘enhancement’:
  https://github.com/google/ExoPlayer/labels/enhancement
- Search existing pull requests: https://github.com/google/ExoPlayer/pulls

When filing a feature request:
-----------------------
Replace the content in the sections below.

### [REQUIRED] 
DefaultHttpDataSource have two function 
bytesSkipped() and  bytesRead();  so can know  the byte pointer at url file.

### Proposed solution
bytesSkipped() and  bytesRead() supply at DefaultHttpDataSource, may be supply a function getPositon()

**Comment by ojw28** [comment]
It's unclear what problem you're trying to solve. Please could you more clearly describe your use case.

**Comment by louiewh** [comment]
DefaultHttpDataSource  has bytesSkipped() and bytesRead() function at old version . bytesSkipped() and bytesRead() function has remove at new version.  I need bytesSkipped() and bytesRead()  function to solve some problem. Thanks.

**Comment by ojw28** [comment]
My request is for you to please describe "some problem" that you're solving. It doesn't make sense for us to blindly add and maintain API surface when we don't understand the corresponding use case.

**Comment by cineplex-projects** [comment]
I also need this.  I have added some string before the video file and know the actual byte position from where the video will play so I need that I can read the string that added before the video using bytesread first then if validate then skip string bytes to play the video.

**Comment by ojw28** [comment]
@cineplex-projects - I don't think that you need the specified API to do that. I think you could implement what you need with a `DataSource` implementation that wraps the `HttpDataSource`. As an aside, what you're doing sounds quite strange. Why wouldn't you just put the extra string in a HTTP response header?

**Comment by ojw28** [comment]
Closing because no use case or specific problem has been described in sufficient detail for us to understand why this feature would be required.
