### ISSUE TITLE
Detecting ad slate from Dash Manifest

### ISSUE THREAD

**Issue by wishygupta** [google/ExoPlayer#9874]
I am developing a solution to detect ad slate in live content over SSAI. So far we have been able to detect the ad slate in HLSManifest. 
However I don't see any relevant object or information when it comes for DashManifest.
I see `EventStream` which is responsible for ad display
I am using the `onTimelineChanged` to read the manifest changes

```kotlin
override fun onTimelineChanged(timeline: Timeline, reason: Int) {
                super.onTimelineChanged(timeline, reason)
                val manifest: Any? = exoPlayer.currentManifest
                if (manifest is HlsManifest) readHLSManifest(manifest)
                else if (manifest is DashManifest) readDASHManifest(manifest)
            }
```

Not able to figure what I can use for ad slate detection from Dash.
Is it possible?

**Comment by tonihei** [comment]
There is no universal detection mechanism to identify ads or ad periods in a DASH manifest (nor in an HLS manifest for that matter). This all depends on how the SSAI stream is generated and which stream guarantees or metadata the stream creator provides. 

In case this is a stream created by IMA, you can wait until the next ExoPlayer release which will contain direct support for SSAI streams and correctly publishes all metadata.

**Comment by tonihei** [comment]
Closing issue as the question was answered.
