### ISSUE TITLE
Video not seekable video is mkv .

### ISSUE THREAD

**Issue by waqasyousafy** [google/ExoPlayer#9887]
Video not seekable am playing the video format mkv 3840x2160 4k hdr(ultra hd) 60fps.
 I have tested in other players like xplayer and mx player it is seekable but in exo that i am using not seekable .
Using exo 2.14.2 
android version: 5 to 11

**Comment by marcbaechinger** [comment]
Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md). If you're unable to share bug reports or test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #9887". Please also update this issue to indicate you’ve done this.

**Comment by waqasyousafy** [comment]
Video not seekable am playing the video format mkv 3840x2160 4k hdr(ultra hd) 60fps.
I have tested in other players like xplayer and mx player it is seekable but in exo not seekable .
Using exo 2.14.2
android version: 5 to 11
not seekable in all devices 

this is the video link
https://drive.google.com/file/d/1OY9ZFJuCGc-CUBm4k9ANanDsAgkgE4hq/view

**Comment by waqasyousafy** [comment]
any help sir?
