### ISSUE TITLE
Change Subtitle Font Style

### ISSUE THREAD

**Issue by Kaaveh** [google/ExoPlayer#9888]
Is there any way to change subtitle font style with font file in `asset` folder?

**Comment by icbaker** [comment]
If you're using ExoPlayer's UI components:

It looks like you can create a `Typeface` from an asset using [`Typeface#createFromAsset`](https://developer.android.com/reference/android/graphics/Typeface#createFromAsset(android.content.res.AssetManager,%20java.lang.String)) (I haven't tested this bit).

You can then construct an ExoPlayer [`CaptionStyleCompat`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/ui/CaptionStyleCompat.html) using this `Typeface` and pass it to [`SubtitleView#setStyle`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/ui/SubtitleView.html#setStyle(com.google.android.exoplayer2.ui.CaptionStyleCompat)). You can access the `SubtitleView` using [`PlayerView#getSubtitleView`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/ui/PlayerView.html#getSubtitleView()).

**Comment by Kaaveh** [comment]
Thanks @icbaker it worked. For those who seek solution in future, I used this code:

```kotlin
var newStyle: CaptionStyleCompat
val myTypeFace = ResourcesCompat.getFont(applicationContext, R.font.comforter)

viewModel.subtitleStyle.value.apply {
    newStyle = CaptionStyleCompat(
        foregroundColor,
        backgroundColor,
        windowColor,
        edgeType,
        edgeColor,
        myTypeFace,
    )
}
viewModel.subtitleStyle.value = newStyle
subtitleView?.setStyle(newStyle)
```
