### ISSUE TITLE
BadPaddingException when try to play HLS content with AES128 protection 

### ISSUE THREAD

**Issue by Gian84** [google/ExoPlayer#989]
When I try to play an HLS AES128 content I get a BadPaddingException (Error while finalizing cipher), but the same content was correctly played on a previous ExoPlayer version.

Log attached:
[log_HlsAes128.txt](https://github.com/google/ExoPlayer/files/44816/log_HlsAes128.txt)

Is it possible ask to you a test utl to try it in your demo app?
Thanks

**Comment by ojw28** [comment]
We do have some internal streams testing HLS+AES, but they're still working correctly on new versions of ExoPlayer. You'd need to provide more information to allow us to investigate this issue, like a sample stream, what version of ExoPlayer you're using, what device you're using it on, and what OS version the device is running.

**Comment by Gian84** [comment]
We have only content protected by a key exchange system; to generate content to let you try it will take me some time.
Anyway thank you for confirmation, we will be working on more content trying to understand why we get this error and let you know asap.
Thank you

We are using last ExoPlayer version (49374e9).
Devices: 
1) Nexus 5 - Android 6.0;
2) GT-I9505 - Android 5.01;
3) SGP321 - Android 4.4.4;

**Comment by Gian84** [comment]
It works properly, it was our problem of key exchange.
I close this issue.
Thanks for the support.
