### ISSUE TITLE
HLS multi language: double language but works only one

### ISSUE THREAD

**Issue by Gian84** [google/ExoPlayer#990]
When I try to play a double language HLS content I can get/select only a language.
I'm using the last ExoPlayer version (49374e9).

This is a test url:
http://80.20.149.244/web2/SUB/TERMINATOR/HLSV4_CLEAR/ALL.m3u8

Is it possible ask to you a multi language test url to try in your demo app?
Thanks

**Comment by ojw28** [comment]
Tracked by https://github.com/google/ExoPlayer/issues/73

**Comment by Gian84** [comment]
I had read issue 73, so I should change my contents.
Thanks a lot ojw28! :)

**Comment by Gian84** [comment]
Unless I misunderstood the point 73, I tried these contents, but both are still silent.

http://80.20.149.244/web2/SUB/TERMINATOR/HLSV4_CLEAR_NOMUX/ALL.m3u8

http://80.20.149.244/web2/SUB/TERMINATOR/HLSV4_CLEAR_NOMUX/NOSUB.m3u8

Can I ask you a suggestion?
Thanks

**Comment by ojw28** [comment]
WebVTT subtitle support isn't implemented yet, so it's not expected to work. #73 tracks implementing this feature.

**Comment by guidofranceschini** [comment]
But the second URL has no subtitles...
Can you check it?
Thanks

**Comment by ojw28** [comment]
Sorry, I got confused above. To clarify, we don't support multi-audio, demuxed-audio streams or multi-subtitles for HLS at this point in time. #73 tracks implementing multi-audio and demuxed-audio stream support. #151 tracks implementing WebVTT multi-subtitle support.

Until #73 is implemented, demuxed-audio streams such as the ones in your sample playlists will not play correctly. Note that in general, we recommend DASH or SmoothStreaming over HLS, and already support de-muxed audio streams for those standards.

**Comment by Gian84** [comment]
What kind of protection should I use with DASH contents?
