### ISSUE TITLE
Load srt file from local

### ISSUE THREAD

**Issue by Kaaveh** [google/ExoPlayer#9900]
I want to load `.srt` file from local device. I read [this](https://github.com/google/ExoPlayer/issues/3869#issuecomment-367067013) and rewrite it like this:

```kotlin
val srtUri = event.uri

val dataSourceFactory = DefaultDataSourceFactory(this@PlayerActivity, null)
val videoItem = MediaItem.fromUri(viewModel.url)
val videoSource: MediaSource =  ProgressiveMediaSource.Factory(dataSourceFactory).createMediaSource(videoItem)

val subtitleConfiguration = MediaItem.SubtitleConfiguration.Builder(srtUri).build()
val textMediaSource: MediaSource =
    SingleSampleMediaSource.Factory(dataSourceFactory)
        .createMediaSource(subtitleConfiguration, C.TIME_UNSET)

val mediaSource: MediaSource =
    MergingMediaSource(videoSource, textMediaSource)

player?.prepare(mediaSource, false, false)
```

but it's not working. What's my mistake? I use `2.16.1` version.

**Comment by icbaker** [comment]
The issue you've linked to is about ExoPlayer 2.6.1, which is >4 years old. The code you've pasted looks broadly correct, but needlessly complicated if you're using 2.16.1. Our website has up-to-date information about using subtitle files on the latest version of the library: https://exoplayer.dev/media-items.html#sideloading-subtitle-tracks

Please try using just the `MediaItem` API and see if that works.

Note that the subtitle track will not be selected by default, unless you've customised the [track selection behaviour of the player](https://exoplayer.dev/track-selection.html). If you want this subtitle track to always be selected, you could pass `C.SELECTION_FLAG_DEFAULT` to `SubtitleConfiguration.Builder#setSelectionFlags`.

**Comment by Kaaveh** [comment]
Thanks @icbaker , As I mentioned, I'm using `2.16.1` not `2.6.1`.
I used `MediaItem` API and worked correctly. For those who seek solution in future, I used this code:

```kotlin
val subtitle = MediaItem.SubtitleConfiguration.Builder(srtUri)
    .setMimeType(MimeTypes.APPLICATION_SUBRIP)
    .setLanguage("fa")
    .setSelectionFlags(C.SELECTION_FLAG_DEFAULT)
    .build()
val mediaItem = MediaItem.Builder()
    .setUri(videoUrl)
    .setSubtitleConfigurations(ImmutableList.of(subtitle))
    .build()

player?.setMediaItem(mediaItem)
```
