### ISSUE TITLE
Mp4 file no sound playing

### ISSUE THREAD

**Issue by FunnyDevs** [google/ExoPlayer#9903]
Hi, 
i have recorded an mp4 file on Android muxing it with jcodec. The file is played well by Windows media player, VLC, ffmpeg but, when I use it on Exoplayer, the sound is not played. I haven't any error code message.

The file is this one: https://we.tl/t-AMpWNlZnuD

Any suggestions?

I need to encode it with Jcodec and not Android MediaMuxer

Thank you

**Comment by marcbaechinger** [comment]
Yes, I can confirm the audio track is missing in ExoPlayer while I can see the track with ffprobe.

```
Stream #0:1(eng): Audio: aac (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 65 kb/s (default)
```

@kim-vde May I ask you to have a look?

**Comment by kim-vde** [comment]
The WeTransfer linked has expired. Could you please re-transfer the file? I will try to have a look more quickly this time.

**Comment by FunnyDevs** [comment]
I have recorded a new video.

https://we.tl/t-eIqQVqdhDg

**Comment by kim-vde** [comment]
Thanks. The file provided is invalid because it doesn't contain an `esds` box under `moov`>`trak`>`mdia`>`minf`>`stbl`>`stsd`>`mp4a`, which is required (see ISO/IEC 14496-14).

**Comment by FunnyDevs** [comment]
ok, thank you for your feedback :)
