### ISSUE TITLE
Image gets broken after seeking into a segment with ad-insertion

### ISSUE THREAD

**Issue by lazarflorian** [google/ExoPlayer#9905]
**Steps to reproduce:**

1. Start playing the PLAY ME video (first 26 seconds contain the ad-insertion segment, the rest is the regular video content)
2. Wait for the playback to reach the end of the ad segment (00:26)
3. Press the Jump back 5s from the player UI
4. Wait for the ad segment to finish playing 

**Expected:** the video continues playing

**Actual:** the ad segment finishes playing, but when the regular video content should start the image gets broken (https://photos.app.goo.gl/9CFUdHZafXS5Rf8i7) 

**NOTE:** If no seeking is done to reach the end of the ad-insertion the playback works just fine; also seeking outside the ad-insertion segment works.

------------------------------------------------------------

**Logs:**

[bugreport-uzx8020chm-PTT1.211012.002-2022-01-28-14-38-56.zip](https://github.com/google/ExoPlayer/files/7958764/bugreport-uzx8020chm-PTT1.211012.002-2022-01-28-14-38-56.zip)
[logcat.txt](https://github.com/google/ExoPlayer/files/7958766/logcat.txt)

------------------------------------------------------------

**Stream details:**

 {
      "name": "PLAY ME",
      "uri": "https://csm-e-cecomhaeuw1vpr208-062a72b33bfa67e52.tls1.yospace.com/csm/builder/415911938,435975634,415911942,438104088,proxy.1,415913402,438107289,435976423,434608808,438127330,433253568,438130442,433269785,422576869,435974686,438107402,415913409,436202079,438109219,proxy.2.mpd?yo.p.si=csm-e-cecomhaeuw1vpr208-062a72b33bfa67e52-64-1643619154819&yo.p.ci=382123541&yo.p.fn=ZGFzaC9jZW5jL0hELzI1ZnBzL2hpZ2gvMmNoLzJuZC9iZDJhYjAyNi1iZDQ3LTRiNDctODk3NS1hMGRlZTNlMzA0M2QvbWFuaWZlc3Q&yo.p.bp=VMAP&yo.p.cu=RFVadw==&deviceType=android_tv&screenSize=1920x1080&yo.ac=true&contentId=se.tv4.content.200073231&yo.p.fo=true&userId=5ae77f51eba3425366d2b341ba1e7b7c&yo.oh=dm9kcC1lLWNvbWhlbS1lYi50bHMxLnlvc3BhY2UuY29t&channelId=29&yo.up=https%3A%2F%2Fvcdn.tv.comhem.se%2Fad%2Fdash%2Fcenc%2FSD%2F25fps%2Fmid%2F2ch%2F2nd%2Ftv4.se%2F",
      "drm_scheme": "widevine",
      "extension": "mpd",
      "drm_license_url":"https://api-staging.tv.comhem.se/license/widevine/lHmJDUAtayi5IUWk4LTFCJYRcMnD1AkR_iMRJZLvyQMwKz8UK5MOYGG3iRbcAUqadKsc1-nq3Fv8kw-F4Zgg9YyEkVEaJzdxbYI8q2qSB90x908AijoDU9RXF-jWo3pehkWnph9Om-OwhwOW1evRQHLKB1y1AyXj3tDoVCSyt7bKUaijAknusm_kXuWw4TjJ"
    }

------------------------------------------------------------

ExoPlayer version: 2.16.1
Android device: Technicolor UZX8020CHM (https://sites.google.com/view/droid-tv/pay-tv-provider/com-hem-tv-hub) -> Android 9, SEI Robotics SEI700TE (https://www.androidtv-guide.com/pay-tv-provider/tele2-tv-hub-mini/)

**Comment by marcbaechinger** [comment]
When I try to play this I get a HTTP 400 from the license server when the ad is over. I can not really reproduce. Seems there is a georestriction or something in place that prevents me to get the license. Let me know how I can make this work if you want me to look into this.

At the first glace it looks like a bug in the DRM codec of that device that is triggered by this stream. That would match to what you say about unencrypted parts work fine. 

What happens when you play the same stream on a different device like on mobile?

**Comment by lazarflorian** [comment]
I've updated the URLs for the stream and DRM license as the session has likely expired.

I've tested on a mobile (Android 10) and wasn't able to reproduce the issue. However, on the 2 STB's that I manage to reproduce the issue, using the previous version of ExoPlayer that we had integrated (2.12.1) the issue didn't reproduce.

**Comment by lazarflorian** [comment]
I updated the URIs for the stream and DRM license as they are expiring after a certain amount of time.

I tested on a mobile (Android 10) and the issue was't reproducible.

I also tested with the previous ExoPlayer we had integrated (2.12.1) on the STBs and the issue was also reproducible on that version as well.

**Comment by lazarflorian** [comment]
We've applied the workaround from https://github.com/google/ExoPlayer/issues/9476 to set the `"drm_session_for_clear_content" : true ` for the stream and this fixes the issue.
