### ISSUE TITLE
Authorisation needed

### ISSUE THREAD

**Issue by hannesa2** [google/ExoPlayer#9912]
Hi, when I use own urls which needs authorization I run into an 401 error
https://github.com/google/ExoPlayer/blob/029a2b27cbdc27cf9d51d4a73ebeb503968849f6/demos/cast/src/main/java/com/google/android/exoplayer2/castdemo/MainActivity.java#L181

1. How to add such a header anyhow to the `MediaItem` ?
2. How to log the url access with header ?

Thank you !

**Comment by tonihei** [comment]
I'm not sure I fully understand the question or request. But it sounds as if you'd like to add a custom request headers for the network request done by the cast receiver?

`CastPlayer` uses a `MediaItemConverter` to convert `MediaItem`s to cast `MediaInfo` objects. You can set to your custom converter in the `CastPlayer` constructor if you want. The `DefaultMediaItemConverter` will already [set request headers](https://github.com/google/ExoPlayer/blob/029a2b27cbdc27cf9d51d4a73ebeb503968849f6/extensions/cast/src/main/java/com/google/android/exoplayer2/ext/cast/DefaultMediaItemConverter.java#L177) for the DRM configuration, but it sounds as if this is not what you are looking for.

**Comment by hannesa2** [comment]
When I set request header 

        Map<String, String> requestHeaders = new HashMap<>();
        requestHeaders.put("Authorization", "Bearer Fyabcdefghijklmnopxx");
        requestHeaders.put(HttpConstants.USER_AGENT_HEADER, SingleSessionManager.getUserAgent());
        requestHeaders.put(HttpConstants.ACCEPT_ENCODING_HEADER, HttpConstants.ACCEPT_ENCODING_IDENTITY);

        MediaItem mediaItemX = new MediaItem.Builder()
                // .setUri("https://storage.googleapis.com/wvmedia/clear/h264/tears/tears.mpd")
                .setUri("https://www.myserver.info/owncloud/remote.php/dav/files/hannes/Movies/Doku/Alpha%20A.mp4")
                .setDrmLicenseRequestHeaders(requestHeaders)
                .setMimeType(MimeTypes.APPLICATION_MPD)
                .build();

I see this. 

<img width="919" alt="image" src="https://user-images.githubusercontent.com/3314607/152123353-c339bb21-d913-4646-ab03-7e5c5d5335e4.png">

1. How to add such a header anyhow to the `MediaItem` right ?
2. [Optional for my help] How to log the url access with header ?

**Comment by tonihei** [comment]
Based on the error in the screenshot, this isn't about `CastPlayer`, but about `ExoPlayer` playbacks? 

If you need to set custom headers for HTTP connections in ExoPlayer, you have multiple options depending on whether you want to set the same headers for every request or need more dynamic access to the headers. Please refer to https://exoplayer.dev/customization.html#customizing-server-interactions for details. 

The `setDrmLicenseRequestHeaders` is only relevant for DRM license requests and it's unclear if that's what you need here. Based on the file type, it seems likely that this file isn't DRM protected and just need to set custom HTTP headers? 

> How to log the url access with header 

It depends on what you'd like to log exactly, but I guess it might be most useful to add an `AnalyticsListener` and listen to `onLoadStarted`, which contains all information about the started load, including request headers in the `loadEventInfo.dataSpec.httpRequestHeaders`

**Comment by hannesa2** [comment]
It wotks now. Thanks a lot !
