### ISSUE TITLE
FLV live stream

### ISSUE THREAD

**Issue by kosmich87** [google/ExoPlayer#9916]
Hi!
I have a problem with play flv live stream. I have URL like "http://{ip}/live/item.flv". Create media item with this url and prepare exoplayer, add listener for playback state changed, state always STATE_BUFFERING and not playing video. Why it's happened?

If i use url for archive video it's play normal, but for live stream strange behavior. Please help. Vlc play live stream normal and don't want use this lib

**Comment by tonihei** [comment]
Please provide us with example media if you want us to take a closer look. Based on the problem description it sounds as if something in the media or the ExoPlayer parsing code might be wrong, and it's impossible to say that without testing it out.

**Comment by kosmich87** [comment]
Sorry, but i can't provide example media, live stream works only in VPN. Video stream works on frontend using videojs. I'll try to get package structure.

**Comment by kosmich87** [comment]
I clone repo and play with FlvExtractor.  In readFlvHeader method hasVideo always value is false for live stream, i change it to true and video start playing.
headerBuffer for live stream have bytes: [70,76,86,1,0,0,0,0,9] - hasVideo = false
headerBuffer for flv files with fix length bytes: [70,76,86,1,1,0,0,0,9] - hasVideo = true
