### ISSUE TITLE
Question about how exoplayer implement the download buffer control.

### ISSUE THREAD

**Issue by jsw-zorro** [google/ExoPlayer#9919]
Hi all, I am currently trying to customized the DataSource to implement my own way of buffering the videos ahead. 

What I basically did is to use most structure in `DefaultHttpDataSource.java` and modified the `open` part in it. In my implementation of `open` part, I initialize a download client and implement my customized video buffering function there. And the client will return an inputstream back to datasource, which will later be used in `read` function in `DataSource`.

However, the part I am confused is, how to control the video pre-buffering size in my video buffering function? Currently, I am just passing the url to the video download function, and it will start a thread to download all parts of the video. However, it seems not reasonable to me to do this. Thus, I am wondering, is there any message from Datasource I can pass to my client to control the pre-buffer size?

Thanks a lot for your help in advance!

**Comment by tonihei** [comment]
To better understand your use case and to suggest a good solution it would be helpful to understand what you are doing inside `open`. It sounds like you are trying to reimplement existing ExoPlayer functionality that already exists at other layers in the player, but that all depends on what "customized video buffering function" means.

Some more pointers on how things usually work with the default components:
 - `LoadControl.shouldContinueLoading` controls if the player should continue loading data. This method is called regularly either between segments in adaptive streams or every x bytes in progressive streams. If you want to customize this logic, you can either tweak `DefaultLoadControl` parameters or provide your custom implementation.
 - The buffering itself is reading data from a `DataSource` and extracts the media container as quickly as possible to write data to the sample queue (=that's the main buffer hold by ExoPlayer). There is not expected to be another larger buffer behind the `DataSource` in most cases.
 - The `DataSource` itself is just the adapter to read data from a source (which could be anything that provides bytes). The expectation is that the source can be opened and read in small byte chunks (even single bytes) and eventually closed. All these methods can block for as long as they need to fulfil the request. All our HTTP sources (default, OkHttp and Cronet) open the connection and then leverage the small internal buffer of the HTTP stack to allow efficient reads. If the player isn't reading data, these HTTP sources will simply keep the connection open but don't transfer further data.
 - Caching (for later reuse) or permanent downloading can be achieved by wrapping the normal `DataSource` with a `CacheDataSource`. (https://exoplayer.dev/customization.html#caching-data-loaded-from-the-network)
 - If you need to customize the data request to work with your custom `DataSource`, there is also a `ResolvingDataSource` that can amend requests in the chain if needed.  (https://exoplayer.dev/customization.html#caching-data-loaded-from-the-network)

**Comment by jsw-zorro** [comment]
Hi, Thanks a lot for your clarification and help! 
Right now, what I did in my `open` is to initiate a client to pre-buffer chunks from a groups of devices, and then merge the chunks in order to form a stream. And in my customized datasource, I will just use such stream to read.
Thus, the current problem I am facing is that in my `client` part, I am not quite sure how to set the proper download range for pre-buffering. Right now, my implementation is just continously requesting chunks until the end of the file reaches.  I am not quite sure whether it is a suitable way? Since, it is not wise to prebuffering such a large chunk of data. I wonder whether there are any variable I can pass to my client from datasource to indicate a specified download range?

**Comment by tonihei** [comment]
> to initiate a client to pre-buffer chunks from a groups of devices, and then merge the chunks in order to form a stream

I'm assuming this is a 'pull' process, that is, your client request these chunks from the remote devices. Would it be possible to only pull the next chunk, or whatever minimal version is needed to create the stream? And then you only continue pulling in other chunks once the `read` method is called and needs more data. This idea would try to minimize the buffer you need in the DataSource because the player already holds its main buffer in a sample queue at another layer. The 'download range' as you called it, would then be determined by the player's `LoadControl` as explained above.

**Comment by jsw-zorro** [comment]
Hi, tonihei:
Thanks a lot for your detailed answering. I got it.
