### ISSUE TITLE
Widevine Dash Streaming gives NPE when playing is aborted and back pressed.

### ISSUE THREAD

**Issue by Amritpal33** [google/ExoPlayer#992]
I am using Widevine with DASH Streaming. While the player prepares for Streaming and Back is pressed,it gives NPE with following logs:

```
-14713/com.jio.media.jod.dev E/AndroidRuntime: FATAL EXCEPTION: main
11-27 15:26:19.599 14713-14713/com.jio.media.jod.dev E/AndroidRuntime: Process: com.jio.media.jod.dev, PID: 14713
11-27 15:26:19.599 14713-14713/com.jio.media.jod.dev E/AndroidRuntime: java.lang.NullPointerException: Attempt to read from field 'android.os.MessageQueue android.os.Looper.mQueue' on a null object reference
11-27 15:26:19.599 14713-14713/com.jio.media.jod.dev E/AndroidRuntime:     at android.os.Handler.<init>(Handler.java:229)
11-27 15:26:19.599 14713-14713/com.jio.media.jod.dev E/AndroidRuntime:     at android.os.Handler.<init>(Handler.java:137)
11-27 15:26:19.599 14713-14713/com.jio.media.jod.dev E/AndroidRuntime:     at com.google.android.exoplayer.drm.StreamingDrmSessionManager$MediaDrmHandler.<init>(StreamingDrmSessionManager.java:434)
11-27 15:26:19.599 14713-14713/com.jio.media.jod.dev E/AndroidRuntime:     at com.google.android.exoplayer.drm.StreamingDrmSessionManager.<init>(StreamingDrmSessionManager.java:187)
11-27 15:26:19.599 14713-14713/com.jio.media.jod.dev E/AndroidRuntime:     at com.google.android.exoplayer.drm.StreamingDrmSessionManager.newWidevineInstance(StreamingDrmSessionManager.java:126)
11-27 15:26:19.599 14713-14713/com.jio.media.jod.dev E/AndroidRuntime:     at com.jio.media.mobile.apps.jioondemand.mediaplayer.exoplayer.DashRendererBuilder$AsyncRendererBuilder.buildRenderers(DashRendererBuilder.java:229)
11-27 15:26:19.599 14713-14713/com.jio.media.jod.dev E/AndroidRuntime:     at com.jio.media.mobile.apps.jioondemand.mediaplayer.exoplayer.DashRendererBuilder$AsyncRendererBuilder.onSingleManifest(DashRendererBuilder.java:159)
11-27 15:26:19.599 14713-14713/com.jio.media.jod.dev E/AndroidRuntime:     at com.jio.media.mobile.apps.jioondemand.mediaplayer.exoplayer.DashRendererBuilder$AsyncRendererBuilder.onSingleManifest(DashRendererBuilder.java:106)
11-27 15:26:19.599 14713-14713/com.jio.media.jod.dev E/AndroidRuntime:     at com.google.android.exoplayer.util.ManifestFetcher$SingleFetchHelper.onLoadCompleted(ManifestFetcher.java:369)
11-27 15:26:19.599 14713-14713/com.jio.media.jod.dev E/AndroidRuntime:     at com.google.android.exoplayer.upstream.Loader$LoadTask.handleMessage(Loader.java:245)
11-27 15:26:19.599 14713-14713/com.jio.media.jod.dev E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102)
11-27 15:26:19.599 14713-14713/com.jio.media.jod.dev E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:145)
11-27 15:26:19.599 14713-14713/com.jio.media.jod.dev E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:6126)
11-27 15:26:19.599 14713-14713/com.jio.media.jod.dev E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
11-27 15:26:19.599 14713-14713/com.jio.media.jod.dev E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:372)
11-27 15:26:19.599 14713-14713/com.jio.media.jod.dev E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
11-27 15:26:19.599 14713-14713/com.jio.media.jod.dev E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
```

Please support how can i fix this.

**Comment by ojw28** [comment]
I believe this is fixed in recent versions of the demo app, specifically in https://github.com/google/ExoPlayer/commit/e89c40cfd3464f5a6c13b8e0498d569194abd955 which is in r1.4.2 and later. Are you using an code taken from an older version?

**Comment by Amritpal33** [comment]
I am using Latest version 1.5.2 with All the updated classes and still facing this issue.

**Comment by ojw28** [comment]
Does that include updating the code that you probably copied into your app from the demo app at some point? For example `jioondemand.mediaplayer.exoplayer.DashRendererBuilder`, which I'm guessing originated from the demo app?

If you're using up to date versions of `DemoPlayer` and `DashRendererBuilder`, then all I can think of is that your app is missing a call to `DemoPlayer.release`. Note that this call would cancel the renderer builder, which prevents the above issue from occurring.

**Comment by Amritpal33** [comment]
Hi, 
I am releasing the player properly by invoking this method.

 public void releaseMediaPlayer()
    {
        if (_vodExoPlayer != null)
        {
            if (_vodExoPlayer.getPlayerControl().isPlaying())
            {
                _vodExoPlayer.setPlayWhenReady(false);
            }
            _vodExoPlayer.removeListener(this);
            _vodExoPlayer.release();
            _vodExoPlayer = null;
            _durationSet.clear();
         
            SurfaceHolder surfaceHolder = _surfaceView.getHolder();
            surfaceHolder.setFormat(PixelFormat.TRANSPARENT);
            surfaceHolder.setFormat(PixelFormat.OPAQUE);

            if (_eventLogger != null)
            {
                _eventLogger.endSession();
                _eventLogger = null;
            }
            SubtileManager.getInstance().removeSrtCallback();
        }

But still facing the crash

**Comment by ojw28** [comment]
Does the issue occur in the demo app? If it doesn't, then it's likely to be an issue in your own code as opposed to with ExoPlayer.

**Comment by Amritpal33** [comment]
After a little Debugging i found that there is a method cancel() in AsyncRendererBuilder builder Which is never get invoked because the reference to currentAsyncBuilder is found null. 

Please debug and fix the issue.

**Comment by ojw28** [comment]
Are you aware that the code you're referring to is in your own application code (possibly copied from ExoPlayer's demo app) and not in the ExoPlayer library? In the demo app it's definitely set to a non-null value [here](https://github.com/google/ExoPlayer/blob/master/demo/src/main/java/com/google/android/exoplayer/demo/player/DashRendererBuilder.java#L90) and is null'd out again only after cancel is called [here](https://github.com/google/ExoPlayer/blob/master/demo/src/main/java/com/google/android/exoplayer/demo/player/DashRendererBuilder.java#L98).

If you can't reproduce the issue in the demo app, it feels very much like a mistake in your application code to me.

**Comment by Amritpal33** [comment]
I have fetched latest code and it is working fine now. So closing this issue.
