### ISSUE TITLE
Player does not play audio when the PMT is updated 

### ISSUE THREAD

**Issue by jpujol** [google/ExoPlayer#9920]
### Description of the media used
Please find the stream attached
[UpdatePmtHls.zip](https://github.com/google/ExoPlayer/files/7982136/UpdatePmtHls.zip)

I have a HLS stream with TS files. Each segment is ~2 seconds long. The first segment has only video during the first second, and afterwards both audio and video are in present, for the reminder of the video. 

The internal structure of the TS file has multiple Program Map Tables (PMT) that declare the streams in the program. For the first second, only a video stream is declared in the PMT, and as soon as audio is present, the PMT is updated to declare both audio and video.

### Observed behaviour:
Exoplayer will not play the audio at all. Video is played correctly. Tested version: commit `029a2b27cbdc27cf9d51d4a73ebeb503968849f6`, release-v2
Other players (Safari, VLC, ffplay) play the stream fine, with audio and video

### Notes:

To my understanding of the TS standard [1], the PMT can be updated, and there is a "version_number" that gets incrementented when the PMT changes:

"version_number – This 5-bit field is the version number of the TS_program_map_section. The version number shall be
incremented by 1 modulo 32 when a change in the information carried within the section occurs. Version number refers
to the definition of a single program, and therefore to a single section. When the current_next_indicator is set to '1', then
the version_number shall be that of the currently applicable TS_program_map_section. When the current_next_indicator
is set to '0', then the version_number shall be that of the next applicable TS_program_map_section."  

Here is a dump of the first segment, analyzing the PMT packets with `tstools` [2]. Note that the first 3 PMT packets only declare the video stream, and the version number is 00. The fourth PMT packet (starting in byte 2444) has version number 01, and declares both audio and video

```
$ ./tsreport -v 0.ts | grep -A 10 PMT | more
     188: TS Packet  2 PID 1000 [pusi] PMT
  section length:  012 (18)
  program number: 0001
  version number 00, current next 1, section number 0, last section number 0
  PCR PID: 0100
  program info length: 0
  Program streams:
    PID 0100 -> Stream 1b H.264/14496-10 video (MPEG-4/AVC)
     376: TS Packet  3 PID 0100 [pusi] stream type 1b (H.264/14496-10 video (MPEG-4/AVC))
  PES header
    Start code:        00 00 01
--
     940: TS Packet  6 PID 1000 [pusi] PMT
  section length:  012 (18)
  program number: 0001
  version number 00, current next 1, section number 0, last section number 0
  PCR PID: 0100
  program info length: 0
  Program streams:
    PID 0100 -> Stream 1b H.264/14496-10 video (MPEG-4/AVC)
    1128: TS Packet  7 PID 0100 [pusi] stream type 1b (H.264/14496-10 video (MPEG-4/AVC))
  Adaptation field len 117 [flags 00]
  PES header
--
    1692: TS Packet 10 PID 1000 [pusi] PMT
  section length:  012 (18)
  program number: 0001
  version number 00, current next 1, section number 0, last section number 0
  PCR PID: 0100
  program info length: 0
  Program streams:
    PID 0100 -> Stream 1b H.264/14496-10 video (MPEG-4/AVC)
    1880: TS Packet 11 PID 0100 [pusi] stream type 1b (H.264/14496-10 video (MPEG-4/AVC))
  Adaptation field len 116 [flags 00]
  PES header
--
    2444: TS Packet 14 PID 1000 [pusi] PMT
  section length:  017 (23)
  program number: 0001
  version number 01, current next 1, section number 0, last section number 0
  PCR PID: 0100
  program info length: 0
  Program streams:
    PID 0100 -> Stream 1b H.264/14496-10 video (MPEG-4/AVC)
    PID 0101 -> Stream 0f 13818-7 Audio with ADTS transport syntax
    2632: TS Packet 15 PID 0101 [pusi] stream type 0f (13818-7 Audio with ADTS transport syntax)
  Adaptation field len 158 [flags 00]
--
```

## Related issues
* https://github.com/google/ExoPlayer/issues/716

## References

[1] ISO/IEC 13818-1: Information technology — Generic coding of moving pictures and associated audio information — Part 1: Systems
[2] https://github.com/kynesim/tstools

**Comment by tonihei** [comment]
You can probably play the TS file with `ProgressiveMediaSource` and setting `DefaultExtractorsFactory.setTsExtractorMode(TsExtractor.MODE_MULTI_PMT)`.  (This turns on support for multiple PMTs as you described above).

However HLS specifically demands TS files with a single PMT, and that's why this isn't supported when playing an HLS playlist. See https://datatracker.ietf.org/doc/html/rfc8216#section-3.2 (_"Transport Stream Segments MUST contain a single MPEG-2 Program; playback of Multi-Program Transport Streams is not defined."_)

**Comment by jpujol** [comment]
Thanks for looking into this. 

The stream has only one PMT: it's PID `0x1000`, as declared in the PAT. The streams inside the program do change.

**Comment by tonihei** [comment]
In this case, please disregard my initial reply! I think I was slightly misguided by `the TS file has multiple Program Map Tables (PMT)` :) 

Updating the same PMT with additional tracks is currently not supported in ExoPlayer, but we have an open feature request to handle such files. See #7873.

**Comment by jpujol** [comment]
Ah, great! thanks for the pointer. And apologies for the poorly chosen words. I guess I meant "multiple PMT packets" :)
