### ISSUE TITLE
Add support for HTTP headers in MediaItem.AdsConfiguration and DefaultMediaSourceFactory

### ISSUE THREAD

**Issue by cdongieux** [google/ExoPlayer#9925]
ExoPlayer does not allow to pass HTTP headers for Ads requests, only [adTagUri](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/MediaItem.AdsConfiguration.html#adTagUri) parameter is available.

`MediaItem.AdsConfiguration` should add a map of header name to header value, like for exemple being able to set a User-Agent in ads requests.

Then, in `DefaultMediaSourceFactory`, the `maybeWrapWithAdsMediaSource()` method should create a new `AdsMediaSource` with this `DataSpec`:
```
DataSpec.Builder()
    .setUri(<ad_tag_uri>)
    .setHttpRequestHeaders(<ad_http_headers>)
    .build()
```

**Comment by tonihei** [comment]
ExoPlayer's IMA extension eventually needs to map all data in the `MediaItem` to an [IMA AdsRequest](https://developers.google.com/interactive-media-ads/docs/sdks/android/client-side/api/reference/com/google/ads/interactivemedia/v3/api/AdsRequest.html). As far as I can see there is no option in the IMA class to set HTTP request headers for this request. So I don't think this is possible unless you know of a way to specify this in the IMA classes?

**Comment by cdongieux** [comment]
You seem to be right, I thought the HTTP request was executed on the ExoPlayer side but after reading again `ImaUtil` I'm wrong.

**Comment by tonihei** [comment]
I'll close the issue then :)
