### ISSUE TITLE
Add support for Ads payload in MediaItem.AdsConfiguration and IMA extension

### ISSUE THREAD

**Issue by cdongieux** [google/ExoPlayer#9926]
ExoPlayer does not allow to pass Ads payload for Ads, only [adTagUri](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/MediaItem.AdsConfiguration.html#adTagUri) parameter is available.

`MediaItem.AdsConfiguration` should add a String property to be able to store Ads payload instead of Ads tag URI (see [VastAdsRequest.Builder](https://developers.google.com/android/reference/com/google/android/gms/cast/VastAdsRequest.Builder) in the Cast SDK).

Then:
- the `AdsMediaSource` should add a new constructor to allow passing the Ads payload
- in the IMA extension, `ImaAdsLoader` should add a new start() method to allow passing the Ads payload
- in the IMA extension, `ImaTagLoader.requestAds(...)` should build the `AdsRequest` with this payload if present, or with the ads tag URI otherwise

**Comment by tonihei** [comment]
Could you clarify what you mean by 'payload'? The [VastAdsRequest.Builder](https://developers.google.com/android/reference/com/google/android/gms/cast/VastAdsRequest.Builder) only allows to set the `URI` or the preloaded ads response and I can't see another method to add payload data. 

In case you mean the preloaded ads response: You can already set that by providing the data as a data URI. See the class documentation of [`ImaAdsLoader`](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/ext/ima/ImaAdsLoader.html).

**Comment by cdongieux** [comment]
Hi,

By "payload" I mean "preloaded ads response", yes. Something like 
```
<?xml version="1.0"?>
<VAST version="3.0">
...
</VAST>
```

Providing the data as a data URI is not what I need, I need to be able to create a `MediaItem.AdsConfiguration` with a preloaded ads response (see above) as a String.

**Comment by tonihei** [comment]
> Providing the data as a data URI is not what I need, I need to be able to create a MediaItem.AdsConfiguration with a preloaded ads response (see above) as a String.

The `AdsConfiguration` contains the URI, so you can set it like this:
```
new MediaItem.Builder()
   .setUri(contentUri)
   .setAdsConfiguration(
       new AdsConfiguration.Builder()
          .setAdTagUri(Util.getDataUriForString("text/xml", adsResponseXmlString))
          .build())
   .build();
```

**Comment by cdongieux** [comment]
Oh great! Thanks a lot :+1:
