### ISSUE TITLE
Unable to renew license while using OfflineLicenseHelper

### ISSUE THREAD

**Issue by neeluagrawal04** [google/ExoPlayer#9927]
Hi Team,

Using `OfflineLicenseHelper` class I am able to generate the license via `downloadLicense()` function but when passing the `byte[]` generated via `downloadLicense()` in `renewLicense(byte[])` I am getting the exception as: "Failed to get key request"

```
System.err: com.google.android.exoplayer2.drm.DrmSession$DrmSessionException: android.media.MediaDrm$MediaDrmStateException: Failed to get key request
System.err:     at com.google.android.exoplayer2.drm.DefaultDrmSession.onError(DefaultDrmSession.java:518)
System.err:     at com.google.android.exoplayer2.drm.DefaultDrmSession.onKeysError(DefaultDrmSession.java:513)
System.err:     at com.google.android.exoplayer2.drm.DefaultDrmSession.postKeyRequest(DefaultDrmSession.java:464)
System.err:     at com.google.android.exoplayer2.drm.DefaultDrmSession.doLicense(DefaultDrmSession.java:420)
System.err:     at com.google.android.exoplayer2.drm.DefaultDrmSession.acquire(DefaultDrmSession.java:288)
System.err:     at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.createAndAcquireSession(DefaultDrmSessionManager.java:686)
System.err: at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.createAndAcquireSessionWithRetry(DefaultDrmSessionManager.java:626)
System.err:     at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.acquireSession(DefaultDrmSessionManager.java:513)
System.err:     at com.google.android.exoplayer2.drm.OfflineLicenseHelper.openBlockingKeyRequest(OfflineLicenseHelper.java:286)
System.err:     at com.google.android.exoplayer2.drm.OfflineLicenseHelper.blockingKeyRequest(OfflineLicenseHelper.java:269)
System.err:     at com.google.android.exoplayer2.drm.OfflineLicenseHelper.renewLicense(OfflineLicenseHelper.java:207)
```

Kindly check this issue as unable to renew the current license key.

Thanks!

**Comment by icbaker** [comment]
We need more info:
* What device(s) do you observe this problem with?
   * Does the operation succeed on any of the devices you've tried with?
   * If you try with a device on Android 12 (API 31) you may find that the DRM stack trace contains a lot more detailed login from the DRM plug-in.
* Does your DRM license policy explicitly allow renewal? [1]

Please also provide the output of `adb bugreport` and test media (including DRM license server info) that I can use to reproduce the problem, as requested in the [issue template](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md). If you're unable to share [bug reports](https://developer.android.com/studio/debug/bug-report) or test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format `Issue #1234` (`#1234` is replaced with your issue number). Please also update this issue to indicate you've done this.

[1] Note that many of the samples in the demo app **do not** support license renewal, and trying to renew them generates a similar looking stack trace, e.g. https://github.com/google/ExoPlayer/issues/9852 and https://github.com/google/ExoPlayer/issues/8554.

**Comment by neeluagrawal04** [comment]
Hi Icbaker,

It happens in each and every device but checked in Android 9 and Android 10 OS version.
I am not sure about whether the DRM license policy explicitly allow renewal. But if it does not allows the renewal of license then is there any other way for the downloaded videos to continue playing when license is expired but without downloading of those videos?

Looking forward to hear from you.

Thanks!!

**Comment by icbaker** [comment]
> I am not sure about whether the DRM license policy explicitly allow renewal.

You should find this information out - if the license doesn't allow renewal then what you're seeing is expected, and not a bug.

> But if it does not allows the renewal of license then is there any other way for the downloaded videos to continue playing when license is expired but without downloading of those videos?

This is a question for your DRM provider (but I suspect the answer is no). If you're a Widevine partner you can also get support directly from them: https://www.widevine.com/contact.

**Comment by neeluagrawal04** [comment]
Hi Icbaker, 

Thank you for the quick response!

Yes you are right, the DRM license policy does not have any renewal mechanism right now configured. So want to ask is there any other way to continue playing the downloaded DRM videos if the license is expired after 30 days?

Thanks!

**Comment by icbaker** [comment]
> So want to ask is there any other way to continue playing the downloaded DRM videos if the license is expired after 30 days?

See above - this is a question specific to your DRM mechanism, not really related to ExoPlayer:
> This is a question for your DRM provider (but I suspect the answer is no). If you're a Widevine partner you can also get support directly from them: https://www.widevine.com/contact.

**Comment by neeluagrawal04** [comment]
Hi Icbaker,

Thank you for your quick response!

Since our license partner does not provide the support for renewal of license and we are not in state to switch for DRM license partner. 

For now I can generate a new license for that downloaded videos. So is there any way to attach a new license for that downloaded videos because we can't provide a functionality to re-download a video once the license is expired after a period of time (e.g. 20 days).

Looking forward to hear from you.

Thanks!!

**Comment by icbaker** [comment]
Assuming two things:
* You've already acquired the new license, and you know `newOfflineKeySetId`
* The content you've already downloaded can be decrypted with the new license

Then you can set `newOfflineKeySetId` on the `MediaItem` you derive from `DownloadRequest` before passing it to the Player, either by using `DownloadRequest.copyWithKeySetId` or `MediaItem.DrmConfiguration.Builder#setKeySetId()`.

**Comment by neeluagrawal04** [comment]
Hi Icbaker,

Thank you for your reply!

Well it works after generating a new license say newOfflineKeySetId  and updating it to downloadRequest object via DownloadRequest.copyWithKeySetId or passing the newOfflineKeySetId to MediaItem.DrmConfiguration.Builder#setKeySetId(). But this will not updating the existing exoplayer database value keySetId. Hence I need to generate a new license every time when I want to play the downloaded video and its license is expired.

So I want to know if there is any way to update this newOfflineKeySetId to exoplayer database corresponding to the downloaded video url? So that the downloadRequest object will pick the newOfflineKeySetId instead of oldOfflineKeySetId and I don't need to generate a new license every-time when the user wants to play the downloaded video.

Eagerly waiting for your response!

Thanks

**Comment by icbaker** [comment]
You can update the info stored in ExoPlayer's download database using `WritableDownloadIndex#putDownload` (on the `WritableDownloadIndex` instance that you provided when you constructed your `DownloadManager`), and passing in a `Download` you just retrieved with only the `keySetId` changed - just make sure that you leave all the other properties untouched.

**Comment by neeluagrawal04** [comment]
Thank you it worked!
