### ISSUE TITLE
Position discontinuity behavior is different between last mid ad point and others. ( This behavior causes audio lag in some devices )

### ISSUE THREAD

**Issue by dev-platong** [google/ExoPlayer#9929]
I have a problem of audio lag at specific device. So I investigated, finally I found position discontinuity behavior is different between final mid ad point and others.

This behavior is always replicated when vast is empty and IMA SDK cannot insert an ad.

1. Final mid ad point

Position Discontinuity reason is always `AUTO_TRANSITION`. This cause an audio lag issue in some devices.

2. Others (except final mid ad point)

Position Discontinuity reason is always `SKIP`.

So that I think `SKIP` is correct when IMA SDK failed to insert ad at last mid ad point.

# Reproduction Step

I prepare reproduction demo app at https://github.com/dev-platong/ExoPlayer/tree/issues-position-discontinuity-reason branch.

1. Open demo app
2. Select a stream ( I removed other streams )

- ExoPlayer version number `r.2.16.1`
- Android version `11` ( I think any android os versions reproduction )
- Android device `Any devices and emulators`

# Video

https://user-images.githubusercontent.com/33997070/152301412-21040c22-0795-4049-8d4b-f1cd2088f41d.mov

**Comment by dev-platong** [comment]
related changes: https://github.com/google/ExoPlayer/releases/tag/r2.14.0

**Comment by tonihei** [comment]
Thanks for reporting! We can provide a fix for this.

**Comment by tonihei** [comment]
Fixed by the commit above.
