### ISSUE TITLE
Question about splitting a video chunks to images in ExoPlayer

### ISSUE THREAD

**Issue by jsw-zorro** [google/ExoPlayer#9932]
Hi, Currently, I am trying to use exoplayer to display the video. However, I need some additional processing to the videos after the video is downloaded. For example, when using the DASH format, I need to convert a video chunk to mulitple images, and after some processing to images, I need to merge these back to a DASH chunk. 
Is there any potential ways, I can use some function inside ExoPlayer to do these splitting and merging stuffs? 
Thanks a lot for your help in advance!

**Comment by ojw28** [comment]
This sounds sufficiently custom that it's not going to be something we're able to provide support on; sorry! It's not something that ExoPlayer is designed to support.
