### ISSUE TITLE
hls Source error

### ISSUE THREAD

**Issue by niuyaweiqq** [google/ExoPlayer#9937]
When playing the video stream of m3u8, if there is an invalid ts file in the middle, it cannot continue to play the uninvalidated ts file, it will return me Source error

Here is my playing address: 
https: //b-g-eu-11.betterstream.co: 2222 / v3-hls-playback / a4476380e3be179e47fdbc9af42b05bf3be52d32dd19844cdb91209b976c199562f24d9024e54ca27d57befdd65a33182de349ddf3c45a1ba0839ecc07e3b095c71a9f95f090732215004304362a8511a096e0fbf85a560f1ead7a5c84946c9ba8726df113280703b6f08dbd22aa40b9191df10aa26382ac1ff1e2e9682ccf7bc6437175ff901cb5ce8c2a05f670b297e593dd17c493ed6bbaa1c5e0d7497b8011cf1549c94442595520b486cb91f17e62a4258fa3be34bef398467cff7a42fe2e1237fcb5e9e2b2cecc7068940f3ade / playlist.m3u8

If the address is invalid, please tell me in time, I will give you the latest playback address

**Comment by ojw28** [comment]
If the TS file is invalid, then isn's that the cause of failure? I suggest fixing the media to not contain invalid segments.
