### ISSUE TITLE
MPD.Location uri in relative format can't be resolved.

### ISSUE THREAD

**Issue by zgzong** [google/ExoPlayer#9939]
We have a DASH live stream, it's MPD manifest Location url is a relative url. 
 <Location>../another_path/manifest.mpd?device_profile=DASH_STB_NGRSSP_LIVE_SD</Location>

When using 2.16.1 demo application to play this stream, the following error has been throw by exoplayer. 
2022-02-04 11:52:53.239 17085-17085/com.google.android.exoplayer2.demo E/EventLogger: internalError [eventTime=2.02, mediaPos=27.76, window=0, loadError
      com.google.android.exoplayer2.upstream.FileDataSource$FileDataSourceException: uri has query and/or fragment, which are not supported. Did you call Uri.parse() on a string containing '?' or '#'? Use Uri.fromFile(new File(path)) to avoid this. 

- The expected behaviour
Exoplayer could resolve the relative path MPD.Location and use it for manifest refresh.

- The actual behaviour
Exoplayer detect the MPD.Location as a local file path. 

- ExoPlayer version number
2.16.1

**Comment by zgzong** [comment]
@ojw28 
here below is a way to resolve this issue. What's your opinion? 
`manifestUri = resolveManifestLocation(loadable.getUri(), manifest.location);`

  /**
   \* Resolve Manifest location.
   \*
   \* @param baseUri this is the uri after 302 redirection.
   \* @param location this is uri parsed from the MPD.Location
   \* @return the resolved uri for manifest.
   */
  private Uri resolveManifestLocation(Uri baseUri, Uri location) {
    if(location == null) {
      return baseUri;
    }
    if(location.isAbsolute()) {
      return location;
    }else{
      //resolve the location's relative path against the uri after 302 redirection.
      return UriUtil.resolveToUri(baseUri.toString(), location.toString());
    }
  }

**Comment by ojw28** [comment]
Our plan is to solve the problem in `DashManifestParser`. Will will update this issue with a commit shortly.

**Comment by zgzong** [comment]
Thanks that's even better. Resolve the location immediately after it has been parsed.

**Comment by ludoven** [comment]
I also encountered this problem, have you solved it?
