### ISSUE TITLE
Demo app throws Exception. 

### ISSUE THREAD

**Issue by IlyaMyasoedov** [google/ExoPlayer#994]
I compiled the source code of ExoPlayer in Android Studio. When i launch the app and click some button in it i get the Exception. Could you fix this?
Thanks ....

**Comment by ojw28** [comment]
There isn't sufficient information here to understand your problem.

**Comment by IlyaMyasoedov** [comment]
When i click the button Google Glass under "DASH-VP9 ONLY" i get the exception:

11-27 18:06:02.628: E/AndroidRuntime(24637): FATAL EXCEPTION: Thread-23043
11-27 18:06:02.628: E/AndroidRuntime(24637): Process: com.google.android.exoplayer.demo.vp9opus, PID: 24637
11-27 18:06:02.628: E/AndroidRuntime(24637): java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.google.android.exoplayer.demo.vp9opus-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]] couldn't find "libvpx.so"
11-27 18:06:02.628: E/AndroidRuntime(24637): 	at java.lang.Runtime.loadLibrary(Runtime.java:366)
11-27 18:06:02.628: E/AndroidRuntime(24637): 	at java.lang.System.loadLibrary(System.java:989)
11-27 18:06:02.628: E/AndroidRuntime(24637): 	at com.google.android.exoplayer.ext.vp9.VpxDecoder.<clinit>(VpxDecoder.java:30)
11-27 18:06:02.628: E/AndroidRuntime(24637): 	at com.google.android.exoplayer.ext.vp9.VpxDecoderWrapper.run(VpxDecoderWrapper.java:152)

**Comment by ojw28** [comment]
That's the VP9/Opus software decoder demo app. Unless you have a specific VP9/Opus software decoder requirement, you should use the standard demo app instead. If you do require the VP9/Opus software decoders, you'll need to set up the native library parts of the VP9 and Opus extensions, as described here:

https://github.com/google/ExoPlayer/tree/master/extensions/opus
https://github.com/google/ExoPlayer/tree/master/extensions/vp9

**Comment by IlyaMyasoedov** [comment]
Sorry, I made a mistake. 
Thanks for your reply. 
I suppose the issue can be closed.
Best regards.
