### ISSUE TITLE
Support downloading live content

### ISSUE THREAD

**Issue by comdigi** [google/ExoPlayer#9940]
Hi!
I downloaded live content(m3u8) but got an error message saying "This demo app does not support downloading live content"
Is it impossible to download live content?

Thanks

**Comment by marcbaechinger** [comment]
The library does not support downloading live content out-of-the-box. There are no plans to provide this in the near future I'm afraid.

There is a tracking bug about this feature. Closing as a duplicate of #3877

**Comment by comdigi** [comment]
Thanks!
