### ISSUE TITLE
ChannelMappingProcessor loses its effect after calling player.nextMediaItem()

### ISSUE THREAD

**Issue by tingyu995** [google/ExoPlayer#9942]
I added ``ChannelMappingProcessor`` to the player by subclassing ``DefaultRenderersFactory`` and override ``buildAudioSink()`` in order to make both speakers play the same channel (left or right).

Having multiple ``MediaItem``s in the playlist, the ``ChannelMappingProcessor`` works across different ``MediaItem``s, but if I call ``player.nextMediaItem()`` or click "next media" icon in the UI controls provided by the player, the effect of ``ChannelMappingProcessor`` will disappear. 

Is this expected behavior?

Currently, I can workaround this issue by calling ``player.seekTo(player.currentMediaItemIndex, player.duration - 1)`` instead.

**Comment by ojw28** [comment]
That doesn't sound expected, no. Please could you provide a small patch that we can apply to our demo app to reproduce this issue? Alternatively, it works well if you fork the project and then make a commit to your fork. Thanks!
