### ISSUE TITLE
How can I unsync / delay video audio (hls) in Exo Player

### ISSUE THREAD

**Issue by coveroid** [google/ExoPlayer#9947]
Hello,

I would like delay video and sound by 500ms in exoplayer (unsync them) on hls stream.

If anyone of you have any idea please show me right direction to do it.

Thanks in Advance

**Comment by ojw28** [comment]
This is not something we support, sorry! It would likely be possible to achieve by forking ExoPlayer and modifying the internals, but this is not something we can provide support on.
