### ISSUE TITLE
the subtitle cannot be displayed on the network  ？

### ISSUE THREAD

**Issue by tmi111** [google/ExoPlayer#9948]
// String subtitleSrt = getFilesDir() + "/how.srt";
       String subtitleSrt = "http://128.199.91.128:8280/output/xxx.srt";
        MediaItem.SubtitleConfiguration subtitle =
                    new MediaItem.SubtitleConfiguration.Builder(Uri.parse(subtitleSrt))
                        .setMimeType(MimeTypes.APPLICATION_SUBRIP)
                        .setLanguage("en")
                        .setSelectionFlags(C.SELECTION_FLAG_DEFAULT)
                        .build();
the subtitle cannot be displayed on the network  ？

**Comment by ojw28** [comment]
It's not possible for us to help you from the very limited information provided. Please see our [documentation](https://exoplayer.dev/media-items.html#sideloading-subtitle-tracks) for instructions on sideloading subtitles.

If you're following these instructions and finding that things are not working, you'll need to provide clear reproduction steps for us to take a look at, ideally in the form of a patch to our demo app that reproduces the issue.

**Comment by tmi111** [comment]
I have this subtitle address in the network, how do I display this subtitle

**Comment by tmi111** [comment]
Can I fill in a network URI address for this subtitle URI

**Comment by tmi111** [comment]
solved
