### ISSUE TITLE
Unable to instantiate decoder 'CIPAACDecoder'

### ISSUE THREAD

**Issue by IlyaMyasoedov** [google/ExoPlayer#995]
Hello..
I tried to launch a demo app but i get the exeption "Decoder init failed: CIPAACDecode" . My device:
ZTE Zeek Android 4.2.2
The log in txt
[log.txt](https://github.com/google/ExoPlayer/files/46513/log.txt)

**Comment by ojw28** [comment]
This is fixed in the `dev` branch in https://github.com/google/ExoPlayer/commit/b64986ce8275dc3c723bb15bf9f00a808ab19b16.
