### ISSUE TITLE
Thumbnails/Image from DashManifest

### ISSUE THREAD

**Issue by Xlcghs** [google/ExoPlayer#9951]
Hello,

Can we display thumbnails in the progress bar using the adaptationSet image in a DASH manifest? 
if so, is there a specific config to activate on the Player side in this case?

Through an adaptation-set Image in a DASH manifest, can we display a full-screen image in the Player view ?

Thank you

**Comment by ojw28** [comment]
This is a duplicate of https://github.com/google/ExoPlayer/issues/3752.
