### ISSUE TITLE
Meaning of `SelectionFlags` on `MediaItem`

### ISSUE THREAD

**Issue by GouravSna** [google/ExoPlayer#9959]
**ExoPlayer version: v2.16.1**

I am building `MediaItem.SubtitleConfiguration` on my end and passing some external subtitles to 'ExoPlayer'. On builder object, there is an api `setSelectionFlags` (https://github.com/google/ExoPlayer/blob/029a2b27cbdc27cf9d51d4a73ebeb503968849f6/library/common/src/main/java/com/google/android/exoplayer2/MediaItem.java#L1279) where it needs the values from which are these,
(https://github.com/google/ExoPlayer/blob/029a2b27cbdc27cf9d51d4a73ebeb503968849f6/library/common/src/main/java/com/google/android/exoplayer2/C.java#L592)

**Issue:**
Currently, I was using following selection flag constants in my code. But while using `setSelectionFlags` on `MediaItem.SubtitleConfiguration` builder, it is giving error because it is expecting these [SelectionFlags](https://github.com/google/ExoPlayer/blob/029a2b27cbdc27cf9d51d4a73ebeb503968849f6/library/common/src/main/java/com/google/android/exoplayer2/C.java#L592)

```java
public static final int DEFAULT_TRACK_SELECTION_FLAG_HLS = 5;
public static final int DEFAULT_TRACK_SELECTION_FLAG_DASH = 1;
```

Things become interesting when I check a media having internal subtitles with DEFAULT value for subtitles like this,

`#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID="subs",NAME="French",DEFAULT=YES,AUTOSELECT=YES,FORCED=NO,LANGUAGE="fr"`

And eventually when I get `mappedTrackInfo` from ExoPlayer, it contains `SelectionFlag` value **5 or 1** not the one which are expected in `MediaItem.SubtitleConfiguration` builder.

Can you please let me know what is the gap here ?

**Comment by ojw28** [comment]
I do not understand where `DEFAULT_TRACK_SELECTION_FLAG_HLS` and `DEFAULT_TRACK_SELECTION_FLAG_DASH` are coming from. I don't think these constants are defined by ExoPlayer. You should be using the flags defined by `C.SelectionFlags`, which you've already located.

Note that, as with flags in general, multiple flags can be combined together. For example `SELECTION_FLAG_AUTOSELECT | SELECTION_FLAG_DEFAULT` is a valid value. This is why you're seeing `5` for HLS tracks that specify `DEFAULT=YES,AUTOSELECT=YES`. Perhaps you didn't realise that you could combine flags in this way?

**Comment by GouravSna** [comment]
Thanks @ojw28 , Got your point. Those were our internal constants but yes, I missed this point that those were the combination of C.SelectionFlags only :)
