### ISSUE TITLE
Can exoplayer play the segmented video?

### ISSUE THREAD

**Issue by Asa-Walker** [google/ExoPlayer#996]
As title.

**Comment by ojw28** [comment]
It's unclear what you mean by segmented video. It would also be best if you just got a sample of the type of video you're interested in playing, and tried to play it.

**Comment by Asa-Walker** [comment]
The video is composed of 3 segments, how to play this segments of the video with exoplayer as one video?

**Comment by Avetri** [comment]
Try to create playlist.

**Comment by ojw28** [comment]
We don't have support for doing this in a seamless way (i.e. without a brief buffering spinner between each segment). We may look at adding support next year.

**Comment by Asa-Walker** [comment]
Next year??? Oh my god,too long. Ffmpeg support concat protocol for playlist. Exoplayer should also support concat protocol ,i think.

**Comment by Avetri** [comment]
@Asa-Walker do You have any sample?
